### ISSUE TITLE
Hulk car shoving.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#1003]
When a hulk encounters a car while chasing the player, it should shove it out of the way roughly in the direction of the player.
##

**Comment by ituluwituluwzev** [comment]
Closing - No progress for over a year. Feel free to reopen if there's still interest.

**Comment by Broken-Admin** [comment]
I believe this will be great, was the PR ever merged?

**Comment by Night-Pryanik** [comment]
This could help with #22802.
