### ISSUE TITLE
'Disorganized' math incorrect

### ISSUE THREAD

**Issue by MattAmmann** [CleverRaven/Cataclysm-DDA#10044]
When my character is wearing nothing but an 'emergency jacket' with a storage of 2, my total volume is 0. If the Disorganized trait is still -40%, the adjusted volume should be 1, as 2 - (.4 \* 2) = 1.2. 

Similarly, if I put on a winter coat with a storage of 12, my total volume is 6. Correct calcuation: 12 - (.4 \* 12) = 7.2.

I'm using version 74e5b81d3dec879916abc4d0f215d083e27a5133

Perhaps the problem lies with the description of the trait: "You can carry 40% less volume." If the intention is that the player can only carry 40% of their max volume (instead of 60%) the trait description needs to be reworded.
##

**Comment by Oskar636** [comment]
Build 5900 windows 64bit console. Since volume got reworked I'm pretty sure this works correctly since I couldn't reproduce it.
Winter coat 3l storage - 3000ml - 1200ml _( 300ml*4 )_ = 1.8l
Emergency jacket 0.5l storage - 500ml - 200ml _( 50ml*4 )_ = 0.3l
