### ISSUE TITLE
Data file editing utility program(s)

### ISSUE THREAD

**Issue by ethankaminski** [CleverRaven/Cataclysm-DDA#1004]
It would be nice to have a utility program of some sort designed to edit data files in an easy-to-use manner. This would make it easier to mod stuff without having to trawl through a massive data file, and would also make it so non-coders don't have to worry about missing/extra commas. Should probably be GUI-based, and would be best if it were cross-platform.

Bonus points if it lets you swap between different mods, as well.
##

**Comment by mugling** [comment]
One of the original objections to automated tools was their JSON output usually being terrible for which #17431 provides some mitigation
