### ISSUE TITLE
0.B SDL graphic glitch

### ISSUE THREAD

**Issue by Vsevolod-Shustov** [CleverRaven/Cataclysm-DDA#10069]
It looks like some parts of some symbols are nor erased on screen refresh.
![cata3](https://cloud.githubusercontent.com/assets/1062138/5073443/f76fabba-6e92-11e4-8c6d-38ab57f160f0.PNG)
![cata2](https://cloud.githubusercontent.com/assets/1062138/5073381/87651b48-6e92-11e4-91ec-a242e4f8e277.PNG)

**Comment by Vsevolod-Shustov** [comment]
Still present in 0.C.1.

**Comment by illi-kun** [comment]
I can't reproduce this in the current master (in Windows/SDL version).

@Vsevolod-Shustov could you confirm it still happens?

**Comment by Vsevolod-Shustov** [comment]
Whoops. No, it does not.
