### ISSUE TITLE
(s)mashing windows generates less sound than prying open windows/doors with a crowbar

### ISSUE THREAD

**Issue by Chaz-Serir** [CleverRaven/Cataclysm-DDA#10070]
I've always been told that prying open doors and windows with a crowbar is the most quiet way to go about being sneaky in Cataclysm, however while using the crowbar generates 12 sound, (s)mashing the window only generates 4 sound. Also, in the event that I accidentally smash a window while trying to pry it open with a crowbar, it generates 24 sound.

Is it possible that the sound value for smashing windows in general was meant to be 24 but the 2 in front was forgotten? :o
##

**Comment by Oskar636** [comment]
Build 5900 windows 64bit console. For my character prying windows and doors made 12 noise, while smashing windows made 16 noise.

**Comment by Night-Pryanik** [comment]
0.C-6369, Win 10 x64, curses. Prying - 7, smashing - 11.
Should be closed?
