### ISSUE TITLE
"Reloading" tools causes recoil

### ISSUE THREAD

**Issue by FunnyMan3595** [CleverRaven/Cataclysm-DDA#1008]
When you "reload" a tool (like a bone needle) while wielding a ranged weapon (like a longbow), you will get a "Recoil" status message.  While this isn't exactly a problem, since you're not likely to be threading a needle mid-combat, it's... bizarre, and should probably be fixed.

That said, I do love the mental imagery this gives me.  Walk out into the middle of town, stare down a zombie horde, cock your sewing kit (with appropriate sound effects, of course), shout "Alright, I'll give you one chance to shamble out of town, no strings attached.  Anyone?  No?  Good, I *like* strings.", and open up with blasts of thread.

**Comment by mugling** [comment]
The entire realoading code has been replaced. Please re-open if this can be reproduced  in `master`
