### ISSUE TITLE
Rapier doesnt train Piercing

### ISSUE THREAD

**Issue by CosmicKobal** [CleverRaven/Cataclysm-DDA#10168]
I've had my Rapier for about 3 days and and have killed at least 40 or 50 enemies with it. My cutting is almost to level 3, but my piercing is only at 22% lvl 0. Maybe this is the way it's supposed to be, but It seems like a weapon that does 2 bash damage and 30 stab damage would train piercing faster that cutting?

**Comment by illi-kun** [comment]
Works just fine in the ```current master```.
