### ISSUE TITLE
Clipping words in hotkeys window.

### ISSUE THREAD

**Issue by Lain-** [CleverRaven/Cataclysm-DDA#10216]
See screenshot:
http://i.imgur.com/iHa3BFd.png

Affected words:
- Advanced Inventory **Management**
- List All Items around **Player**
- Unload or Empty Wielded **Item**
- Drop Item to Adjacent **Title**
- Toggle Attack Mode of Wielded **Item**

**Comment by illi-kun** [comment]
That's not an issue anymore (since #12404 is landed).
