### ISSUE TITLE
Edge of tilefield flashes underground/in the dark

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#10233]
Specifically, most of the time there's 1-tile-wide black edge on it, but when doing actions that take time (waiting, sleeping, crafting...) or cancelling them that black edge gets replaced by same tiles as the rest of viewscreen, grey `#`s. 
Repeatability: `|`, `x`.
With the edge: http://i.imgur.com/H6UCb4Y.png
Without the edge: http://i.imgur.com/J3vXuZk.png

Happens in experimentals at least since 0.A 2328, but did _not_ happen in 2160, so was introduced somewhere inbetween and is extremely annoying. If it's intended, can be flashing please fixed, or option added to remove the edge entirely and keep the behavior of old versions?
##

**Comment by Barhandar** [comment]
Still flashing. Could it be either forced to not flash or be given an option to disable the border altogether like the old versions were?

**Comment by Leland** [comment]
Fixed by #13997
