### ISSUE TITLE
Zombie Brute special and Furniture

### ISSUE THREAD

**Issue by BromIDE** [CleverRaven/Cataclysm-DDA#10249]
![ghgh](https://cloud.githubusercontent.com/assets/4941996/5230456/77a91d50-771e-11e4-9106-2bd91c180f0a.png)
So when a zombie brute's special sends the PC flying, it knocks them through "floors" instead of the respective furniture. In this picture, my PC was knocked through multiple metal display cases, but as you can see, they're regarded in the log as "floor".
##

**Comment by Oskar636** [comment]
Build 5900 windows 64bit console. Currently when you get launched to the air with a powerfull atack and you're knocked against something, it displays "You're knocked against x" the zombie brute atack is powerfull enough to destroy normal walls when he launches you, and a bit of luck to destroy concrete walls. The zombie hulk atack destroys concrete walls really easily.

**Comment by kevingranade** [comment]
Just confirmed on 0.C-20702-g08d5d29 that this is still happening.

**Comment by kevingranade** [comment]
Can't check at the moment, but I suspect this has been refactored away at some point, if not it's happening in player::impact()
https://github.com/CleverRaven/Cataclysm-DDA/blob/df475f2fd1844ae82655d18db99943788e9c68e6/src/player.cpp#L3456

**Comment by ZhilkinSerg** [comment]
I believe it was addressed in #12540.
