### ISSUE TITLE
Bionic Armor does nothing.

### ISSUE THREAD

**Issue by freezerbunny** [CleverRaven/Cataclysm-DDA#10297]
Just did some testing.

With bionic armor, received 3 - 5 damage from crawling zombie.
Without bionic armor, received 3 - 5 damage from crawling zombie.

Checking the code there's absolutely nothing that references the bio_armor ids, so it effectively does nothing as far as I'm aware.

**Comment by kevingranade** [comment]
Cherry picking and cleaning up the fixes.

**Comment by Rivet-the-Zombie** [comment]
Has this finally been fixed for sure?

**Comment by KA101** [comment]
If so, I'm not aware of it.  :-/

**Comment by Lain-** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/commit/107d6f87498ad6d7d0d34cc39eba60511410b366 fixed it, I think.
