### ISSUE TITLE
Mines crash the game

### ISSUE THREAD

**Issue by kardas666** [CleverRaven/Cataclysm-DDA#10315]
2 times this happened, both times in mines.
Both times I found artefacts in them, first was the summon wind elemental one, and it crashed the game, second time if you look at minimap theres a purple @ all around, whitch I assume is also artefact location.

Screenshot of said crash:

http://i.imgur.com/IIUq6ML.png

**Comment by mugling** [comment]
Closing as unconfirmed in over a year
