### ISSUE TITLE
Steak Knife melee messages.

### ISSUE THREAD

**Issue by 2birdie** [CleverRaven/Cataclysm-DDA#10311]
When using a steak knife to fight, you'll receive messages such as 'You batter the zombie for 16 damage.' 
Is it really so bad of an edge that it's better to smack enemies with the side of the blade? :P

**Comment by illi-kun** [comment]
I tested steak knife with various levels of skills and got only proper messages (i.e. related to stabbing). I guess it was fixed by Coolthulhu in #12600.
