### ISSUE TITLE
Crafting: Rock problems.

### ISSUE THREAD

**Issue by meyar** [CleverRaven/Cataclysm-DDA#10326]
Trying to craft a stone axe, pot, shovel, hammer, pebbles, knives, and other things currently does not work in the experimental 2473. Using a ceramic shard where applicable works, but trying to use rocks do not.

Camp fire drill and Rock in a Sock works. Reason unknown.

**Comment by kevingranade** [comment]
Probably caused by the rocks as ammo thing? Is this still happening?

**Comment by OzoneH3** [comment]
This is working in latest experimental.
