### ISSUE TITLE
NPC Deathcam issue

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#10353]
hi all info

Win7
Latest EXP build (tiles)

Well I got killed by an NPC and I decided to watch what happend after my death.

For the last day the NPC that killed me is just sitting there shooting my body he is doing nothing else?.

This all so happens if a zombie kills me to they just attack my dead body and this goes on for ever.

Should NPC`s not loot my body then just move on or even butcher me.
##

**Comment by Leland** [comment]
Old issue – closing. Feel free to let me know if you want it reopened; or just create a new issue.
