### ISSUE TITLE
Batch Crafting Only offers Experience for one Item

### ISSUE THREAD

**Issue by thebombsauce** [CleverRaven/Cataclysm-DDA#10393]
When batch crafting items the experience gained is only equated for a single item disallowing batch crafting from lowering a significant amount of the grind within the game. This is probably going to be solved by an eventual redo of the system which calculates based on singular items which would also fix a similar issue in which you either entirely succeed at making the items or you entirely fail.

**Comment by BevapDin** [comment]
This was implemented by #11695 - specifically the "Crafting is tied to craft duration" part of it.
