### ISSUE TITLE
Common Cold Lasting Forever

### ISSUE THREAD

**Issue by slawr34** [CleverRaven/Cataclysm-DDA#10407]
I've had the common cold for the past 9 in game days. Regularly eating vitamins, staying out of the rain and getting tons of sleep has not done anything.

I'd also like to take this moment to say: really? You get a cold from being in the cold/rain? You know that's not how it works right? 

Maybe make a hypothermia condition instead? It's the most common killer of campers or hikers.
##

**Comment by kevingranade** [comment]
Not actionable.
