### ISSUE TITLE
[Suggestion] - Remove equipped items directly from layering menu.

### ISSUE THREAD

**Issue by Hague** [CleverRaven/Cataclysm-DDA#10417]
Just what it says in the title. I suggest adding a feature that will allow you to remove equipment directly from the layering menu. Shift-T seems like a fitting key in this instance.

An additional feature would be 'greyed out' clothing bits that are in your inventory unworn but could be equipped with a key press. Shift-W

**Comment by sparr** [comment]
I haven't figured out the UI enough to say this for certain, but I think an architectural problem with this idea is that taking clothes off takes time, but time can't pass while most dialogs are open (the advanced inventory screen being one explicitly coded exception)

**Comment by KA101** [comment]
Not sure how portable the AIM code would be, either.

(Advanced Inventory Manager)

**Comment by BevapDin** [comment]
DavidKeaton implemented this in #11714.

**Comment by DavidKeaton** [comment]
I did. Can equip and unequip, with a nice little filtered inventory_ui for equipping. Time passage accounted for. :-) I'd say this is closable.
