### ISSUE TITLE
Lost boot knife from tailor fail

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#10421]
I am using Windows Tile Experimental 8b38e05.
I was trying to repair a pair of combat boots with a combat knife sheathed in them. I failed at tailoring and destroyed the boots. Apparently, it was an epic failure as the knife went with them. I suspect this is not the intended behavior. I searched my inventory and the ground nearby, but the knife was no more.

**Comment by Rivet-the-Zombie** [comment]
I can confirm this one is still happening for sure. I lost a handgun to a failed roll on a damaged holster.
