### ISSUE TITLE
Freeze when generating terrain during the game

### ISSUE THREAD

**Issue by arcke** [CleverRaven/Cataclysm-DDA#10462]
The game completely freezes occasionally. I created a couple of debug characters and kept exploring new terrain fast. I have several occasions where there is a complete freeze, except for the "Really quit..." when Ctrl-C. If I use gdb and it freezes I can only get the backtrace in a screenshot (https://i.imgur.com/Y4aQtKD.png).

So far all backtraces I got involve all functions in the trace from generate to make_hiway. I suspect the A\* in there isnt terminating in some cases. I don't understand some of that code, but I can simplify the A\* and try to reproduce the freeze.
##

**Comment by keyspace** [comment]
#7534 tracks the buggyness of highways/hiways. Since they don't seem to be generated anymore, and therefore don't cause freezes, can this be closed?.. :D
