### ISSUE TITLE
Food items with "(fresh)" tag not being auto pickup'd

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#10478]
Version: 0.B-1323-gfb239d8-dirty
1. Added `cucumber` to auto pickup list. Testing matched to "cucumber", as expected.
2. Went to a farm.
3. Did not auto pickup cucumbers.
4. Added `cucumber (fresh)` to auto pickup list. Testing matched to nothing.
5. Auto pickup'd fresh cucumbers.
6. `cucumber*` will also auto pickup.

Similar behavior can be observed for other food items e.g. celery, broccoli, etc. Not sure if this is intended behavior. If it is, auto pickup testing should match "cucumber (fresh)" to "cucumber (fresh)", as opposed to nothing.

e: formatting for clarity.
##

**Comment by Oskar636** [comment]
Definietly still an issue in build 5864. And the bug being that it only displayes _apple_ and doesn't _apple (fresh)_ in the autopickup test menu.

**Comment by OzoneH3** [comment]
All the functionality here is intended behaviour. There is no easy way to
generate all the item suffixes in the item test menu.

Thats why it says that it won't display those:
```_("Won't display bottled and suffixes=(fits)"));```
