### ISSUE TITLE
Red Dot Sight says it gives 90 sight dispersion, doesn't actually do anything?

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#10473]
Version: 0.B-1323-gfb239d8-dirty

Red Dot Sight item description indicates it increases sight dispersion by 90, but when attached to a gun with 60 sight dispersion, the gun's sight dispersion does not change.

Specifically, I debug-spawned a SCAR-H and a Red Dot Sight. SCAR-H with no attachments has sight dispersion 60; attaching the Red Dot Sight doesn't change this value.

**Comment by illi-kun** [comment]
This is obsolete issue so it should be closed (interface issue was solved in #11082).
