### ISSUE TITLE
Copper Tubing, Copper Wire recipes don't involve the use of Copper

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#10493]
I'm not a metalworker, but it seems odd to me that Copper Tubing can be made with approximately every single metal in CDDA _except_ actual copper.

Copper Wire simply involves 40 volume's worth of wire (i.e. 20 units) and some duct tape.

Also, not sure intentional or not, but bullet recipes that use Copper Tubing don't allow for Copper as an alternative, while producing Copper when disassembled using the Kinetic Bullet Puller.
##

**Comment by Oskar636** [comment]
Build 5900 windows 64bit console. Crafting recipe for copper tubing and copper wire is only available with copper as a metal. For the bullets part, I guess they got reworked since copper tubings aren't a component in a single crafting recipe in the game.

**Comment by codemime** [comment]
@Oskar636 Thanks for your help.
