### ISSUE TITLE
Mod pack suggestion: No otherworld beasts.

### ISSUE THREAD

**Issue by 2birdie** [CleverRaven/Cataclysm-DDA#10504]
I may be using the wrong terminology, but a mod option to remove things like mi-gos and krecks would be nice.

**Comment by Asmageddon** [comment]
I was talking about enemies that can instagib a minmaxed character in power armor btw, like the TankBot or whatever it was. If I recall correctly, there were a few more enemies that could basically shred anything not inside a tank vehicle.
