### ISSUE TITLE
Make sawn-off shotgun holster-able

### ISSUE THREAD

**Issue by slawr34** [CleverRaven/Cataclysm-DDA#10515]
I'm not sure if this would entail rewriting its properties to be a pistol, but would it be possible to make the sawn-off holster-able?

I'm envisioning Mad Max right now...

**Comment by xyder** [comment]
I think this issue is fixed in the latest version.

**Comment by Night-Pryanik** [comment]
Should this issue be closed?

**Comment by mugling** [comment]
> Should this issue be closed?

Yes, a number of suitable holsters exist
