### ISSUE TITLE
Shortened Barrel only has partially-visible effects

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#10513]
Version: 0.B-1422-g06a286c-dirty

The Shortened Barrel weapon mod's item description says it reduces sight dispersion by 1 and weapon speed by 1, but when attached to a weapon, these changes are not reflected.

The recoil reduction and increase in dispersion are showing up correctly.

(Not sure if the effects are actually being applied or not; it's just that they're not showing up on the weapon on inspection inspecting.)
##

**Comment by DarkRainX** [comment]
As far as I can see the displayed are always as follows: *Sight dispersion* will always be the *lowest* value in either the weapon or any installed mod, while the *aim speed* is always the *highest* value in either weapon or any mod installed.

**Comment by kevingranade** [comment]
Sight dispersion and aim speed aren't modifiers, when you add a new sight
(which is any mod with sight dispersion and aim speed defined), you get a
new sight that is used when aiming (when it's the 'fastest' sight on the
gun that allows for further decrease in aim dispersion), there is no way
for a gun mod to *modify* the aiming properties of the gun.
What you'd want to do is give shortened barrel aim speed and sight
dispersion stats in between rifle and pistol iron sights.

**Comment by Griffinhart** [comment]
That the different modifiers/stats don't have the same progression (i.e. bigger numbers aren't always better, smaller numbers aren't always worse, some numbers are the min/max of the equipped gunmod stats as opposed to a sum, etc.) should be explained somewhere in the game.
