### ISSUE TITLE
Can't wear any head-gear with Chitinous Plate

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#10526]
Chitinous Plate adds +1 encumberment to all locations, head included and when attempting to wear even a cloth hat, yah know, because it's freezing, you get the message "You cannot wear a helmet!"
##

**Comment by Night-Pryanik** [comment]
If "Chitinous Plate" was renamed to "Chitinous Armor", then it is covering only torso and legs and therefore doesn't conflicts with any headgear.
Should be closed?

**Comment by Coolthulhu** [comment]
Nope, it's the mutation.

**Comment by Night-Pryanik** [comment]
Message is different: "Your mutation Chitinous Plate prevents you from wearing that x."
Bug or intended?

**Comment by Leland** [comment]
Closing - old and no movement. Feel free to ping me here if there's still interest, or make a new issue.
