### ISSUE TITLE
player::skillLevel and player::get_skill_level are used interchangeably

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#10531]
While one returns a copy of `SkillLevel`, and the other returns a reference, there are no instances of the reference being used. There also exists set_skill_level, which is used only in `src/npc.cpp`. The only other difference is that one indexes the skill map, while the other iterates over it.

I'm not yet acquainted enough with Cataclysm's source code to know what convention is more common - I've seen `prop(); prop(new_value)` style getters/setters, as well as `get_` and `set_`, and manipulating references.

Either way, one should be phased out, and there should instead be two variants of the same function(s) - one const-correct, and one mutable, if mutability is even needed. From what I have seen, it is not.

Since I'm working on some skill stuff of my own, I am perfectly fine with making this change, I just need someone more informed than me to make the decision.
##

**Comment by kevingranade** [comment]
The skillLevel accessors have been removed.
