### ISSUE TITLE
Vehicles can achieve unrealistic speeds due to broken aerodynamics

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#10536]
For example, the sports car can achieve over 600km/h as "safe speed", and if you really want to, you can go much, muuch higher than that. This is certainly not how vehicles are supposed to work. It's unrealistic and counterintuitive, and has impacts on balance -as far as I'm concerned, it means that the power/fuel usage grows linearly with speed, removing the need/ability to conserve fuel by driving at an optimal cruising speed. Speaking of optimal cruising speed, that's probably another addition that should be made, but that's topic for another issue.

**Comment by illi-kun** [comment]
Superseded by similar discussion with more details in #15839.
