### ISSUE TITLE
Inventory (highlighted text)

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#10549]
WIN7
Latest exp build
tiles (mshock)

Not sure how to explain this one but I really would love this issue fixed as it makes using inventory slower for me.

When I press i to go into my inventory normally the top left item is highlighted in blue but it is not.
I now have to press down arrow for it to be highlighted in blue not a huge problem

BUT

when I want to say activate a crowbar I am weilding I have to press a then down to show blue high lighting then press left to go to the right hand side of the menu then press down again to show blue highlighting again

Normally all I had to do was press the left arrow whice took me to the right hand side of the inventory menu then press right to activate it because the top item was allways highlighted.

I think the main issue is then there is nothing highlighted the first times you enter the inventory menu untill u press down once.

If this is not clear please let me know.

**Comment by illi-kun** [comment]
Inventory was updated recently, so closing it.
