### ISSUE TITLE
When doing long task, if you ignore NPC they can rob you blind

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#10554]
I am using Windows Experimental version 8b38e05.
I was installing parts on an armored personnel carrier and made the mistake of ignoring a distant NPC who was asking to talk. Next thing I know the dialogue prompt opened and I failed all my intimidation rolls. I then proceeded to automatically continue installing an armored plate while he stole almost all my possessions. I guess I would like a "You are being robbed! Stop doing whatever? (Y/N)" prompt.

**Comment by BevapDin** [comment]
Fixed by #17551.
