### ISSUE TITLE
Wooden Vehicle Construction

### ISSUE THREAD

**Issue by McTuttles** [CleverRaven/Cataclysm-DDA#10552]
Wooden vehicles are currently a sub-optimal choice and have very little place in the game. I propose the construction requirements be changed to only require a hammer and nails. Making wooden construction require much more common parts would give value to the option of wood construction that it does not currently have. 

Optimal would be to have installing a wooden component cost nails and have a hammer. Uninstalling it would require a crowbar, and fixing it would require nails and 2x4s.

If that is too complex, then just requiring a hammer to install, and leaving the rest would work well. You can always bash it apart to get nails back, and the idea that a wooden cart is too flimsy to repair easily makes balance sense. It could actually be interesting to make little carts you abandon when they get broken.

**Comment by mugling** [comment]
This was effectively closed by #10945
