### ISSUE TITLE
How controversial is changing JSON entry file layout?

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#10553]
I'm currently working on something of an overhaul of the recipe/requirement system, first off to remove the split between primary and secondary skills required, second off to use difficulty formulas that can be calculated ahead of time(the current ones are actually broken, but more on that once I make a PR), and third off to open path to using the same requirement functionality for construction, vehicle construction, and, if needed, item usage.

Now, I'm not introducing a lot of new data file variables, though some are necessary. Particularly for skill requirements, I'm splitting difficulty into minimum skill required to learn/use a recipe, and a difficulty factor. Additionally, to allow using the system for other actions, which might not be based around the 50% success rate, I'm introducing a base success rate variable.

Also, while I'm at it, I want to move recipe/other requirements into a separate JSON subentry, rather than include multiple top-level properties in each recipe.

The added benefit of that would be making requirements (much) easier to include in other entry types than recipes, and I most certainly want to do it, but I don't want to screw up other people's branches too much.

I believe that in the long term it would be a beneficial bit of cleanup, but since the decisions aren't exactly up to me, I'd rather consult people here.

**Comment by kevingranade** [comment]
Question was answered.
