### ISSUE TITLE
Bionics assigned to ! and = can't be used/inspected

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#10563]
The keys ! and = are already used by the Bionics menu for toggling between inspect/use mode and for key reassignment, respectively, so any bionics assigned to those keys (either automatically i.e. because the player has so many bionics, or manually by the player) can't be used without first reassigning them.

Might as well as make them unavailable as assignable keys?

**Comment by BevapDin** [comment]
This was fixed. The list of allowed hotkeys for bionics does not include `!`, `-` nor `=` anymore.
The list can also be navigated via the arrows keys, allowing access to any bionic without using its hotkey. And the key bindings can be changed anyway.
