### ISSUE TITLE
Crash when declining being taught as quest reward.

### ISSUE THREAD

**Issue by skyhog281** [CleverRaven/Cataclysm-DDA#10574]
Completed a quest for an NPC that involved me going to a nearby house, collecting a dog, and escorting the dog back to said NPC.

Upon returning to the NPC I chose the 'teach me something' reward which gave me a list of skills I could improve but changed my mind. I chose the "eh, never mind" option which crashed the game.

**Comment by mugling** [comment]
Duplicate of #1990
