### ISSUE TITLE
LOS occasionally violated by turrets (which then instantly kill you)

### ISSUE THREAD

**Issue by madamimadam** [CleverRaven/Cataclysm-DDA#10576]
I've had this happen a few times while trying the lab challenge. Before this last one it was always the same issue, and involved a setup that looked like this: (W = wall, D = Door, B = bureau/dresser, P = player)

    WWDWW
      PB

I would open the door, and see nothing interesting in the room. Then I'd take a step into the doorway and see a turret off to the right. Normally I would then step diagonally down and to the right, to get the wall between myself and the turret, but this is impossible because of the bureau. So I step directly back, confident that, because it could not see me last round, it would not have LOS to me now either. And then it shreds me and I'm dead.

I just found an even more straightforward example of this, though. This time it was like this:

    WWDWW
     P

I opened the door, and there was a turret up and to the right a few spaces. So I shut the door. And, once the door was shut (and the door graphic was closed), the turret shot right on through it and blew a zillion holes in my torso (and its 20+ points of armor). While it was shooting it was still lit and visible even though there was now a door in between us.

What's weird to me, though, is that most of the time if I open a door and then close it immediately, without moving, this doesn't happen. If I step into a doorway, see a turret, and then immediately step out again so that there is a wall between me and a turret, this doesn't happen ever. So it isn't a straightforward old-LOS bug or anything like that.

It's AMAZINGLY frustrating, though. It's killed the three most promising lab escape attempts that I have had. It really is quite annoying to be killed repeatedly by the same bug.

**Comment by kevingranade** [comment]
Looks like this particular issue is caused by using the player transparency cache.
I'm throwing a cache invalidation in before the monsters act, which should fix it.

**Comment by KA101** [comment]
Huh.  That might have caused the peeking issue too.  Thanks.

**Comment by kevingranade** [comment]
I'm fairly certain there was never a peeking issue, just the turret using
old info and using a different LOS calculation.
