### ISSUE TITLE
Peeking problems.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#10583]
Using the peek command to look around corners or doorways allows turrets to shoot you as if you were standing in the open; they fire off a burst when you end the action, which sends bullets curving around the intervening obstruction(s) in order to kill you.

Also reported here: http://smf.cataclysmdda.com/index.php?topic=7727.msg178133#msg178133
##

**Comment by KA101** [comment]
Duplicated Rivet's description, as I posted.  Sorry, all.

**Comment by DeNarr** [comment]
I also just noticed that you can't peek down stairs. I hit some stairs where it warns me there is a LOT of heat coming from down there. Well, I'd like to be able to see what's down there before putting myself into mortal danger. (I was too curious to pass it up, so went down stairs. Figured my environmental 40 armor should have protected me. It was freaking lava! Also, there was no way back up, even though I had long rope AND a grappling hook)
