### ISSUE TITLE
Highway rework?

### ISSUE THREAD

**Issue by KA101** [CleverRaven/Cataclysm-DDA#10622]
Was responding to the building-suggestion thread and offhand thought that one way to achieve an interstate-length highway without too much overhauling in mapgen.cpp would be to make them follow the same parameters as rivers: one (or two, one each way??) per overmap section, running across it.

More I think about it, the more it seems like it might actually be worth following up on.  But then I don't usually mess with the actual generation part of mapgen.

Thoughts?
##

**Comment by Stretop** [comment]
Long distance travel can be useful for migration =)

Consider this: as game goes on and more overworld is explored, savegame tends to bloat with all unused loot, completely looted locations and so on. So I think it would be interesting to have an option to travel "far, far away" via highway, remove old worldmap and get you character and your vehicle on completely new worldmap.

**Comment by KA101** [comment]
Ugh.  New Game + is a thing, but this ain't the issue for it.

**Comment by illi-kun** [comment]
Discussion about highways is in #7534, so no need to keep this open.
