### ISSUE TITLE
Proposal: vehicle-mounted cameras

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#10628]
With code that would be similar to the wing mirrors, we could have video cameras that could be mounted on a vehicle.

Implementation notes:
- Cameras might be directional (like headlights) or just give omnidirectional vision around themselves. The existing FOV code should already handle the latter, but the former would look better. For best support, do both, make the omnicam more expensive.
- Cameras should consume power -- if no power is available, they shouldn't work.
- Viewing the cameras should require either that the player is standing on or next to the vehicle controls tile, or that there be a "monitor" vehicle part in the same tile. For simplicity, I'd go with vehicle controls -- as **JENTHULTHU** said on IRC: they're advanced enough to run turret guns.

**Comment by Zireael07** [comment]
I think this should be closed?

**Comment by narc0tiq** [comment]
Good call -- yes, it should.
