### ISSUE TITLE
Mutations Suggestions (contain mild spoilers).

### ISSUE THREAD

**Issue by Stretop** [CleverRaven/Cataclysm-DDA#10676]
Version: 0.B Brin

1) "Toe Roots" should cancel and be cancelled by "Toe Talons"
2) "Gills" and "Cephalopod gills" should either cancel each other, or cephalopod ones should evolve from usual ones.
2) "Bird" and "Lizard" mutation categories really can use mutations like "Less Thrist" and stronger versions of it. Because their organisms are very good at retaining water (due to their efficient excretory systems).
3) "Rat" and "Troglobite" mutation categories really can use mutations like "Small" (an inverse of "Large"). Because they are, usually, small.
4) "Lizard" mutation category should include "Hibernation". Because this is what lizards do just as well as bears.
5) "Large", "Huge", "Solidly Built" and "TAAANK" post-threshold mutations should be added to both Chimera and Lizard thresholds, and "Inconviniently Large" and "Freakishly Huge" should be added to Chimera and Lizard categories. Because lizards are cold-blooded and can potentially grow to become very large (think "dinosaurs"), and chimeras "contain" lizards and cattle, also it seems fitting for their "constant and diverse growth" theme.
6) Troglobite and Chimera thresholds should include "Reptile healing". Chimeras - because they are part-lizards and because such healing is theme-fitting for them (in vein of "Hyper-Metabolism"-style regeneration). Troglobite - because they are simply so good at regeneration in general.

P.S. 5.5) An idea: add vehicle parts like "High Roof", "High Boards", "High Windshields" (and their reinforced versions), "XL seat" and "XL controls" for Huge survivors. Sure you cannot find any cars premade for your frame, but you should be able to construct one such vehicle yourself.

Also I would like to say that I am completely in love with your new "Plant" and "Cephalopod" post-threshold mutations - I find them endlessly amusing =)
##

**Comment by kevingranade** [comment]
DDA is not "like any other roguelike", we don't ignore issues like that
just because they might be inconvenient.

**Comment by Stretop** [comment]
"troglobite is cave-dwelling humanoid, not something particularly smaller than normal"

Well, this is... very not obvious. Since "troglobite mutagen" require "chunks of meat" I thought troglobites are about olms, trogloraptors and the like. If this category is about something like C.H.U.Ds - shouldn't it use "human flesh" instead of some generic "meat"? 

"I'd wanted to point that dinosaurs were grown to such sizes because of different atmosphere (higher oxygen levels)"

Is is merely a theory. Other theory is that cold-blooded (inertial endothermics, actually, but this is different question) reptiles have slower cellular metabolism and as such can maintain their bodies with slower blood circulation, which allows them to grow bigger without overtaxing their cardiovascular systems.

But anyway, this was just a shorthand. Here is argument from nowadays: 
polar bear - weight is up to 750 kg; 
domestic cow (large continental breeds) - weight is up to 1 200 kg; 
saltwater crocodile - weight is up to 2 000 kg. 
And "cattle" and "bear" both have "Huge" mutation.

**Comment by KA101** [comment]
And they have cardio trouble as a result.  I'll look into it in good time.

**Comment by Stretop** [comment]
Also, mutation "Canine ears" lists mutation "Lupine ears" in "Becomes"; but "Lupine ears" lists "Canine ears" in "Cancels", while it should be listed in "Prereqs" instead.

I was unable to gain mutation "Lupine ears" in-game (even by using "lupine mutagens") without cheats, and I think this is the reason for it. Though I may have been just unlucky.

**Comment by KA101** [comment]
Will be looked into.

**Comment by railmonkey** [comment]
Speaking of Canine Ears, I've been wondering for a while why there isn't a corresponding Feline Ears mutation. Cats actually have considerably better hearing than dogs, considerably better than most animals in fact. Never mind the cosmetic aspect, though that's a draw, too.

**Comment by KA101** [comment]
And folks complain that good-hearing mutations are a liability.

**Comment by Rivet-the-Zombie** [comment]
Tell them to wear earplugs?

**Comment by Stretop** [comment]
Another two suggestions: 
1) Can we remove "Lightly Furried" mutation from chimera mutcat? It has annoying tendency to constantly cancel and get canceled by "Scales" mutation (which is also in chimera mutcat), when chimera mutagens and seriums are used to breach the threshold.
2) Can we add "Thick Scales" to chimera threshold? It is the most battle-oriented skin mutation and seems to be fitting the "shock troop" aspect of chimeric threshold.

**Comment by Leland** [comment]
This is an old suggestion thread that hasn't seen movement in months - if there's still interest, feel free to reopen or create a new issue.
