### ISSUE TITLE
More armor improvements

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#10703]
**SONY** on the IRC was just asking for a way to see the cut/bash/environmental protections of their worn clothing. I was just thinking that could be easily fit into the existing interface if a key (say, tab?) changed the "Storage" column next to the list of clothing into a "Cut", then "Bash", etc., column. For visual reference, I mean the one highlighted in red below:

![that one](http://i.imgur.com/jubKhP5.png)

On a similar note, if anyone can find a way to do it, it would be _really_ nice if the [@] screen could show the total protection values for each body part. Perhaps press a key to change the Encumbrance section into a protection section, with columns for "C/B/E" protections?

Edit: Oh, combining the two -- how about the Storage column on the [+] screen could change into a combined C/B/E column? All those values are two digits at longest, so there should be plenty of room to show all three together.
##

**Comment by Snaaty** [comment]
+1 on the C/B/E column

However, displaying all protection values in the  @-screen is hard to do as you also have to take into account the chances of which the protection actually protects you (the coverage value of the clothing piece).

**Comment by BevapDin** [comment]
> All those values are two digits at longest, so there should be plenty of room to show all three together.

Plenty of room, you say. #5646 disagrees there and should be kept in mind.

**Comment by KA101** [comment]
Gotta remember those 80x24 people.

(Who still uses 80x24???  Seems a major limitation and I'd like to be rid of it.)

**Comment by Griffinhart** [comment]
>All those values are two digits at longest

What? No, they're not. Heavy powered armor has Cut and Bash protection values at three digits.

**Comment by narc0tiq** [comment]
Friggin' exceptions...

**Comment by i2amroy** [comment]
>(Who still uses 80x24??? Seems a major limitation and I'd like to be rid of it.)

Agreed there. If nobody is using it it would be really nice for UI design to bump that up a bit to give ourselves some more room.

**Comment by kevingranade** [comment]
Anyone using a classic terminal.  I'm not sure if anyone is, at the least
we'd need a user survey of some kind to determine what the new minimum
should be.

**Comment by Rivet-the-Zombie** [comment]
I'd like to see the baseline resolution change as well. I can dig that we're maintaining compatibility with the oldest possible hardware, but is it really necessary to stretch clear back to the 70s?

**Comment by OzoneH3** [comment]
Since there is currently a survey running: #14273

**Comment by Night-Pryanik** [comment]
Good idea, but the discussion is stalled for years, so closing for now.
