### ISSUE TITLE
Crafting results in incorrect quantity

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#10727]
Craft a batch of, say, 5 nachos. The result will be a single nacho rather than a stack of 15.

**Comment by Apersonperson** [comment]
This issue Seem to have more than that problem. It must have occurred in version 6733480 or before. Also almost all items at least in the food section of crafting seem to have the crafting portions reduced to 1 that are not supposed to have that. Cause 45 minuttes of crafting and lots of items for 1 granola seems wrong.
