### ISSUE TITLE
Display of Dexterity for wired reflexes

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#10732]
This is a small interface bug I've noticed. 

When using the Bionic "Wired Reflexes" your Dexterity is improved by two, but the "new", improved number is always green and not white, as it should be. 
I guess that this might be the case with other stat-improving bionics too, I didn't have the chance to check, yet. 

As a side effect, once you reach your "original" dex-level e.g. due to pain, DEX gets displayed in white.

**Comment by KA101** [comment]
Bionics are considered a buff, not a changed baseline, so the stat is perma-green.  Working as intended, sorry for the confusion.

**Comment by Snaaty** [comment]
Hm, is that really so logical? 
I am not going to argue, if it has already been established otherwise. 

I thought different colors are there to indicate an out-of-ordinary situation to the player (like being in pain, being high, being drunk, ...) that is temporary (by definition, because otherwise it wouldn't be out of the ordinary). Since there is no way of suddenly losing your bionics and the player is probably well aware of those he has, so there is no need to tell him/her via coloring.

**Comment by narc0tiq** [comment]
You can remove your bionics, which may not be a "sudden" loss, but will
revert your stats to their normal state. Furthermore, the coloring improves
discoverability, to some extent -- a player might not remember what buffs
they're getting from installed bionics; while the coloring doesn't say more
than "it's more than it usually is", it does provide a starting point
("Wait, what's affecting my dexterity?").

**Comment by Snaaty** [comment]
Hm, perhaps I simply see bionics more as a part of the player than you guys.

The way it is now, imho bionics are so much part of you, they -are- you. In-game it is currently even easier to lose/swap/change mutations (voluntarily and involuntarily) than bionics.

Also, for example, a white colouring of my "starting" dexterity indicates to me that things are fine, while in fact they are not, because I am in pain which causes me to actually "lose" two points of dexterity.

**Comment by KA101** [comment]
I'm not opposed to that reasoning, but it wasn't my idea.  So far as I can tell people would rather mutations be considered buffs rather than changing the base stat, too.

But I'd as soon that not happen.

**Comment by Snaaty** [comment]
Hm, should I open a forum thread to evaluate what the "people" think, then? 

Although it's not the most important thing in the game, and if you/Kevin oppose it anyway it would make such a thread would be rather pointless.

**Comment by KA101** [comment]
I don't know who made that determination, truth be told.
