### ISSUE TITLE
Low level archery no longer possible?

### ISSUE THREAD

**Issue by bpwatts** [CleverRaven/Cataclysm-DDA#10731]
It seems after a recent change, low level archery no longer is available? Brand new character,daily build, had 0 skill in archery. Made small game arrow and self bow but wasn't able to fire any. Debugged myself a shortbow still cant fire. A debugged quiver also couldn't store my small game arrows or field point arrows. Debugging myseIf wooden arrows made archery possible.  Is this by design and I'm just missing something? If by design it would seem slingshot is the new low level archery items to make? Also we could remove now all low level archery recipes as they are no longer functional.

**Comment by Snaaty** [comment]
Are you sure you didn't try to fire the arrow-shafts? 

Quite possibly those are no longer eligible ammo, as those are really just sticks and not meant to be fired.

**Comment by BevapDin** [comment]
Look at the the item info, the mentioned, non-functional arrows are listed as being of (ammo) type "components". It should be "arrows". That might be the bug.

**Comment by bpwatts** [comment]
Yes, I debugged myself field arrows and it wouldnt fire either. I believe BevapDin has it.

**Comment by bpwatts** [comment]
The quiver would also not store the field arrows.

**Comment by KA101** [comment]
That was a specific change as unfletched arrows are so inaccurate as to be useless after about a tile or two.  You need fletched field point arrows to shoot.

Working as intended.

**Comment by bpwatts** [comment]
field point arrows are not unfletched and small game arrows are still craftable but not fireable.

**Comment by BevapDin** [comment]
They should probably be called "foo arrow shafts" or similar and not "foo arrows" as the later indicates usable arrows.

**Comment by bpwatts** [comment]
I agree shafts should NOT be fireable, but the field point arrows and small game arrows are final products, not components. BevapDin, should I open a new issue to get the final arrow products moved back to fireable arrows?

**Comment by bpwatts** [comment]
If the intent is for only fletched items to be fired then we need recipes in game to reflect this and the item name changes BevapDin laid out. Otherwise low level starting archers are a bit hosed.

**Comment by Chaz-Moth** [comment]
I agree that the incomplete items should be renamed to "x arrow shafts", to remove confusion regarding the items. So you'd go "Wooden arrow shafts -> Small game arrow shafts -> Fletched small game arrows", for instance.

However, there are already recipes in the game, when you gain enough skill in Survival and Fabrication you'll see them. Fletching requires 1 Survival and 1 Fabrication to create, and can be made from a variety of items found around the place. It is still fully possible to make usable arrows early in the game, it just requires a little bit more work  now.
