### ISSUE TITLE
Incorrect "metabolism" mutation line cancellation... Again.

### ISSUE THREAD

**Issue by Stretop** [CleverRaven/Cataclysm-DDA#10739]
Version: 0.B Brin

1) Survivor had "Light Eater" innate trait.
2) Survivor mutated through "metabolism" mutation line to "Extreme Metabolism"
3) Survivor evolved past "Chimera" threshold and gained "Hyper-metabolism" mutation.
4) Survivor uses bird mutagen.

At this moment survivor's "Extreme Metabolism" changes into "Very Fast Metabolism" and at the same time he gains his "Light Eater" innate trait. So now he has "Hyper-metabolism", "Very Fast Metabolism" and "Light Eater" all at the same time.

**Comment by KA101** [comment]
More along the lines of "Not intended for that sort of finagl-y stuff", but sure.

**Comment by KA101** [comment]
OK, one of those was a check that had never been updated for the new infrastructure.  Found and fixed on my end.  Probably needs sequential checking for the other one though and I'm not sure where exactly that's acting up.

Will look into it more tomorrow.

**Comment by KA101** [comment]
Looked into, half-fix seems to have unfixed itself.  >_<  No promises on a completion point.

**Comment by Stretop** [comment]
It sems that this bug is present in all mutations concerning innate traits removal/returning. It is simply more obvious with sequential mutations.

For example: if you have "Fleet-footed" as innate trait and then gain "Ponderous" mutation and then again "Fleet-footed" mutation - it is always shown in log as if you gained "Fleet-footed" mutation twice.

Also, what seems strange to me is that when game calls for mutation_1 that cancels you present mutation_2 - you only lose mutation_2, you do not immediately gain mutation_1. But if game calls for mutation that cancels you present innate trait - you simultaneously lose your innate trait and gain called mutation. Is this intended to work this way?
