### ISSUE TITLE
Dome lights overwrite floodlights

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#10747]
Setup: 1 tile vehicle with floodlight, seat, battery and controls.
Turning on floodlight produces a lot of light, but turning on dome lights dims it to dome light level.

**Comment by DavidKeaton** [comment]
Interesting... I used add_light_source for it.

**Comment by BevapDin** [comment]
Give you a hint: look at what `map::add_light_source` does: it just overrides the previously added light source at the target. Could probably use a std::max there.

**Comment by DavidKeaton** [comment]
Ahhh. Okay. I am a bit nervous to change lightmap and map, bet that's what git reviews are for!

**Comment by DavidKeaton** [comment]
Let me know if this fixes your test Mr. @Coolthulhu
