### ISSUE TITLE
Honey as junk food?

### ISSUE THREAD

**Issue by Alasnuyo** [CleverRaven/Cataclysm-DDA#10743]
This is kind of a minor issue, but it has been bugging me. Should honey really be tagged as junk food? It's not really junk food in real life, and I don't think it should be one in CDDA either.

**Comment by Rivet-the-Zombie** [comment]
I'm guessing the original logic is because it's concentrated sugars. That being said, I'm fine with changing the material; could use ````null```` for simplicity.

**Comment by KA101** [comment]
Makes it OK for folks with junkfood intolerance, so minor buff.  I'm not opposed either, though.

**Comment by KA101** [comment]
Fixed in the latest merge.
