### ISSUE TITLE
Costs seem Far, Far too High - Am I Missing Something?

### ISSUE THREAD

**Issue by QuantumInvictus** [CleverRaven/Cataclysm-DDA#10742]
I was looking through the item JSONs, and I've noticed a few places where prices are far, far out of the range they should be. I know that the current prices are more or less placeholders, but things like the M72 LAW (~10x modern prices) and the flamethrowers (with prices that are even further from what I would expect) make me hesitate to just change them - is there something I'm not accounting for here?

**Comment by JohnDvorak** [comment]
I believe the costs are in cents, if that changes anything.

**Comment by QuantumInvictus** [comment]
It really doesn't - the M72 LAW is $8500, a far cry from its modern <$900 pricepoint.

**Comment by vache** [comment]
That's all?  Let me go down to my local gun store and pick one up.

**Comment by QuantumInvictus** [comment]
Wiki has it that unit cost of an M72 LAW is somewhere around $880. This makes sense - it's basically nothing but a tube, a rocket, and a trigger. The reason you'd not be able to get one here is that they are for fairly obvious reasons strictly illegal for civilian ownership. The world of Cataclysm, however, had greatly reduced regulations on and greatly increased encouragement of gun ownership before the cataclysm, to the point where M72s would almost certainly be legal to own. Frankly, I'd say we should go even lower to $500 or less, since from a practical standpoint both before and after the apocalypse, they're nowhere near as useful as almost any other type of firearm, as well as being dirt cheap to mass produce.

**Comment by vache** [comment]
I don't know.  There's a pretty big difference between guns and explosives.  You never (rarely?) see explosives in gun shops or gun basements.

**Comment by QuantumInvictus** [comment]
Well, yeah - it's pretty much a given that any for of explosive will be harder to come by than an equally high-end firearm. I suppose $500 is pushing it on that basis alone, but pegging it at the current $900 price point (which, unless I'm mistaken, is the price used for vending machines, not NPCs, so it shouldn't really reflect scarcity too much) would be a vast improvement over the currently obscene prices. Really all I'm asking is what these prices are supposed to represent, since I have a nagging feeling I'm missing something.

**Comment by Rivet-the-Zombie** [comment]
So PR a price audit?

Am I missing something here?

**Comment by KA101** [comment]
NPCs use the same base pricing, modified by comparative barter skills.  NPC pricing reflecting "realities" of the post-cataclysm world is another project, I think, as that involves adding i modifiers based on the NPC's goals, dis/likes, etc.

**Comment by BevapDin** [comment]
How about adding a post-cataclysm price (optional, defaults to the pre-cataclysm price)? NPCs would use the post, vending machines the pre price.

**Comment by QuantumInvictus** [comment]
Thanks - that clears it up. I'll set up a branch and PR to fix a few bits I've spotted, then. Probably be done tomorrow.

**Comment by i2amroy** [comment]
Personally I think the way to go might just be to tie faction info into cost category modifiers, which would allow different factions to have different desires. A group of cyborg half-robots might place a much lower value on food then a group of fast metabolism mutants, for example.

**Comment by Rivet-the-Zombie** [comment]
That's a very clever idea, @i2amroy. I like it!

**Comment by kevingranade** [comment]
BevapDin: That's what we're planning on doing, but due to the number of items, a full price audit is a multi-month ordeal.

**Comment by Snaaty** [comment]
Adding proper cataclysmic prices is something I'd like to see as well. 
I guess tyng it into faction could work after the prices have been revisited?

**Comment by Stretop** [comment]
Well the game world is sometime in the future, so how do we know how much inflation had happened before the Cataclysm?

Also I must attract your attention to the fact that in the post-Cataclismyc world firearms are no longer mass-produced, so their prices would unavoidably become much higher.

And about costs in general: can you attach a price tag to sunlight? To happiness? To wicked finger-mounted lasers and adamantium claws? To horribly dangerous mutagenic substances? In short: how are we going to price items with no real world counterparts?

**Comment by QuantumInvictus** [comment]
My understanding is that the prices in the JSONs are only used unmodified by things like vending machines, where post-cataclysm scarcity wouldn't be raising prices.

As far as inflation goes, to my knowledge no strict value has been decided for such. Regardless, since the game is set in the pretty near future, prices shouldn't be too far off what they are now.

**Comment by QuantumInvictus** [comment]
You know, a variation on BevapDin's idea might also be useful here, but instead of a second price, I would suggest a multiplier - I suspect that such would be easier to manage, since a price change would still only need to be changed in one place, rather than two.

**Comment by kevingranade** [comment]
I don't see any reason to tie them together, if we decide after the fact to
change a pre-cataclysm price, that doesn't imply that the post-cataclysm
price should change.

**Comment by Shoes01** [comment]
Other than vending machines, are there other "pre-cataclysm" ways of buying items? If not, only a handful of item types would really need a pre-cataclysm price.

**Comment by kevingranade** [comment]
Vending machines and robot factions are the main sources, but that could
easily cover every item.

**Comment by QuantumInvictus** [comment]
You have a good point there - tying them together would mean a single change would propagate to both, but that could well not be something desirable.

**Comment by kevingranade** [comment]
Dual pricing has nothing to do with this issue, it just came up in the
discussion.

**Comment by KA101** [comment]
Yeah, I misunderstood the reason for the price drop on the LAW.

Long story short, no, we're not selling one-shot, disposable, and fairly easily portable launchers, capable of blowing up a police car or police *station* (or perhaps if the propellant goes off with age, the *user*), on the open market.  RPG likewise no, as that's a commie terrorist weapon and this is 'Murrica.  We don't use those here.

**Comment by QuantumInvictus** [comment]
I think you are overestimating the power of these things. I just tested it in-game and all it did was knock out a single wall tile from a standard house, and did nothing against a fire station's metal doors at all. Something like a tank wouldn't even flinch at one of these things, and all could do to a police station or other building is knock a bit of a hole in the wall.

Fair enough on the RPG since the cost of importing would impose a premium, but as it stood the prices were definitely too high - the cost of an M72 was three times that of an AK-47! I can see two possibilities for this weapon, and both of them support having a very low price:
1. It was sold on the open market, which would make it cheap to buy due to its simple construction and the fact that it is disposable rather than reloadable.
2. It was not sold on the open market, which makes the pricing somewhat more of a moot point with the exception of NPC trading - in the absence of dual pricing, the price in this case would be referencing the post-apocalyptic price, which would be even lower due to it being a cumbersome weapon that can't be reused and isn't really useful against the hoards of zombies.

**Comment by QuantumInvictus** [comment]
Depending on what the electrical components are supposed to represent, that could well make sense. Look at the internals of a modern PC - in a lot of ways, assembling one is no harder than assembling a Lego set, since the various connects more or less slot right together. It's not inconceivable that one could, with the right parts, assemble an implantable laser or battery system. Guns are different, however - barring specialized equipment (which, granted, I'd like to see in the game at some point), it'd be all but impossible to, for instance, rifle a barrel.

**Comment by Stretop** [comment]
"Look at the internals of a modern PC - in a lot of ways, assembling one is no harder than assembling a Lego set"
True, but this is because they are _specifically designed_ for this. And even then for same task there are many incompatible parts from different architectures. 
In game you can throw together any 2 power converters, 2 amfiplier circuts, 2 lenses and 2 CPUs and somehow end up with implantable laser. This is some extreme MacGyvering right here.

Specialized equipment? Sure it would be needed, but we already have forge along with swage and die set for melee weapons and hand press and die set for bullets, so why not?

**Comment by QuantumInvictus** [comment]
I looked it up, and it looks like a rifling machine is actually quite simple to make and operate - I might look into implementing that at some point. It shouldn't be too involved. For reference, here's a good video I found of such a machine in action:
americanprecision.org/rifling-animation-video/100-uncategorised/297-rifling-animation-video

But even with that I don't think it's realistic to be able to assemble, say, an M249 or an AUG. Such machines work as well as they do thanks entirely to highly precise machining techniques, which require massively complex machines which themselves require highly precise machining. I'd imagine that something along the lines of an AK-47 would be simple enough for the character to assemble, albeit with a very high fabrication skill.

Hm. I think I'll open an issue for this myself, and get some input from the other contributors.

**Comment by Stretop** [comment]
- But even with that I don't think it's realistic to be able to assemble, say, an M249 or an AUG. Such machines work as well as they do thanks entirely to highly precise machining techniques, which require massively complex machines which themselves require highly precise machining.

News flash! Right now it is possible to craft some firearms from parts, fabricated by 3d-printers: http://www.youtube.com/watch?v=DconsfGsXyA 
Massively complex machines? Nope, never heard about them =)

- Hm. I think I'll open an issue for this myself, and get some input from the other contributors.

Good. Sounds like plan to me. But please do reference here from there (or vice versa).

**Comment by QuantumInvictus** [comment]
It's over on issue #10787. I'll respond to your post there.

**Comment by Rivet-the-Zombie** [comment]
>fabricated by 3d-printers

![300px-xp002](https://cloud.githubusercontent.com/assets/5084581/5651812/712c5ee4-9670-11e4-9692-59a8a98354c0.jpg)

That's some military-grade firepower right there.

**Comment by KA101** [comment]
I think the RL re-price addressed this; if not, let us know and we'll reopen.
