### ISSUE TITLE
Minor text hitch when auto-assign letters is disabled.

### ISSUE THREAD

**Issue by Chaz-Moth** [CleverRaven/Cataclysm-DDA#10768]
When "Auto-assign letters" is set to "False" in the Interface options, any time a new item is picked up, there's an open bracket shows up next to the "You pick up:" text.
![cataexperimentalautoassignfalseglitch](https://cloud.githubusercontent.com/assets/4246670/5632463/e5c844e8-95c6-11e4-8533-f23ba20c0ed7.png)

I'll need to keep testing to see if there are any other similar graphics issues when auto-assign letters is set to false, but that was the most prominent one to me.

**Comment by DavidKeaton** [comment]
Ah i noticed this too but forgot to make a note. Thanks mate. I'll make a fix.
