### ISSUE TITLE
Dropping an item on an active item deactivates it

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#10761]
An active item "covered" by any item stops being active. "Uncovering" it doesn't activate it back, but picking it up does.

For example, dropping 2 active flashlights on one tile will cause the first one to stop consuming charges. Dropping a stack of active C-4s will result in only one explosion. Covering a grenade with a rag will make it stop ticking.

**Comment by Rivet-the-Zombie** [comment]
>Covering a grenade with a rag will make it stop ticking.

Abracadabra!

**Comment by DavidKeaton** [comment]
*Puts cardboard box on mininuke*
It is now in a state of active and not active at the same time!

**Comment by Coolthulhu** [comment]
There's also that party trick where you do meth, light a molotov, throw it and then throw a rock at it. If you hit, the molotov won't go off.

**Comment by DavidKeaton** [comment]
And of course, doing Meth is the key part.

**Comment by kevingranade** [comment]
That's more a case of, "you were at a party, so you were doing meth",
right? :)

**Comment by DavidKeaton** [comment]
Hey man, if it's *there*...

**Comment by DavidKeaton** [comment]
Also, curious if this is also why rechargeable items don't recharge.

**Comment by Coolthulhu** [comment]
Just tested, but no - rechargeable items don't recharge regardless of order.
Found out why do they start with -1 charges - it's because they take over mod's charges, which start at -1. Changing it to something else doesn't fix much, though.

**Comment by BevapDin** [comment]
Rechargeable items don't recharge because thy are not active and thereby ignored by the active item handling code.

**Comment by DavidKeaton** [comment]
Well that's no bueno.
