### ISSUE TITLE
Item display scrolling bug

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#10788]
If there is a large stack of items on the ground such that viewing them all requires scrolling (pgup/pgdn), scrolling past the last item does not put you at the first page but on the second page. The only way to return to the first page is to scroll up.

Goes both ways too. Scrolling up from the first page puts you on the second-to-last page. Just to clarify, this only happens using the full page scroll (pgup/pgdn) and not arrow keys.

**Comment by KA101** [comment]
I recall hearing that before but thought we fixed it.  :-/
