### ISSUE TITLE
Duplicated items

### ISSUE THREAD

**Issue by Sheco** [CleverRaven/Cataclysm-DDA#10795]
There are three duplicated items, in [the handloaded bullets file](../tree/master/data/json/items/handloaded_bullets.json):

* reloaded_300_winmag
* reloaded_32_acp
* reloaded_762_54R

They have slighty different values, I don't know which one should stay. But I'd say the ones between lines 296 and 370 are wrong, just because they have different indentation from the rest of the file.

**Comment by Sheco** [comment]
Checking the file blame, those lines (296-370) were commited by @kevingranade, so now I think those are the correct items.

**Comment by kevingranade** [comment]
This is very likely to date from a merge in my aiming overhaul, if the
dispersion values for one group are 15x higher than the other, that's
definitely it, and the higher values are correct.

**Comment by Sheco** [comment]
On the linked PR I also mentioned something about the RECYCLE effect, the correct items (the ones with the  higher dispersion) don't have that effect, should I add it to the PR?

**Comment by KA101** [comment]
You should, as I commented there.

**Comment by Sheco** [comment]
Yes, you're right, it's done. 

The PR is ready.
