### ISSUE TITLE
'A' ing a gun stored in a 'WIELDED' back holster will destroy gun.

### ISSUE THREAD

**Issue by CosmicKobal** [CleverRaven/Cataclysm-DDA#10800]
I sometimes press the wrong key and end up wielding my back holster instead of wielding the weapon stored within it. once the back holster is being wielded, if you attempt to 'a' the wielded back holster to get the weapon out, it will cause the weapon to just vanish.

**Comment by KA101** [comment]
Known issue on the forums; thanks for reporting here.

**Comment by bkentel** [comment]
Can't reproduce it with a back holster and AK-47. The holster plus contained gun just end up back in my inventory (or on the ground when full). Any foolproof way to reproduce it?

**Comment by CosmicKobal** [comment]
Hmm.... I want to say that I had either a pneumatic bolt thrower thing (the name escapes me) holstered, or a reflex recurve bow holstered.


Sent from my U.S. Cellular® Smartphone

<div>-------- Original message --------</div><div>From: Brandon Kentel <notifications@github.com> </div><div>Date:01/12/2015  8:47 AM  (GMT-05:00) </div><div>To: CleverRaven/Cataclysm-DDA <Cataclysm-DDA@noreply.github.com> </div><div>Cc: CosmicKobal <CosmicKobal@hotmail.com> </div><div>Subject: Re: [Cataclysm-DDA] 'A' ing a gun stored in a 'WIELDED' back holster will destroy gun. (#10800) </div><div>
</div>Can't reproduce it with a back holster and AK-47. The holster plus contained gun just end up back in my inventory (or on the ground when full). Any foolproof way to reproduce it?
