### ISSUE TITLE
Niten Working with all weapons.

### ISSUE THREAD

**Issue by Shadefang** [CleverRaven/Cataclysm-DDA#10803]
Was experimenting with niten style and found I could apply it's techniques with most anything (discovered it when I accidentally wielded a jack). I think this is caused by the "melee_allowed" flags in techniques.json overriding the list of weapons in martialarts.json, but I'm not sure.

**Comment by KA101** [comment]
Probably it, yeah.  Thinking this was already reported but thanks.
