### ISSUE TITLE
New Interaction: Russian Roulette

### ISSUE THREAD

**Issue by Shoes01** [CleverRaven/Cataclysm-DDA#10805]
Goal: create an interaction with appropriate weapons that allows the player to play Russian roulette.

Purpose: Mainly for fun, and winning would give adrenaline boosts, long lasting morale boosts, and maybe other perks. Losing would result in death.

Approach: "A"ctivating a revolver-style gun would pop up a menu "Play Russian Roulette?" with "yes" and "no" as options. You need at least one bullet to play. Perhaps the "yes" option could also have a success percentage in case revolvers aren't also six chambers, and to really drive home the point that you might die. Losing is easy to code: kill the player, have blood spatter too. Winning would require giving the perks (adrenaline, morale, other?) and also unloading all but one bullet from the gun. Additionally, this game could interact with traits, CBMs, mutations, or anything else as needed. For example, attempting to play with a power helmet on might result in a message saying "you feel like this is cheating". I can imagine the Psychotic trait would have an interesting reaction. I can imagine the spiritual trait would have a message saying "you knew your deity would protect you". Optimistic could say "you knew you would win!". The tombstone could have an equally funny death message too. Its feels appropriate to involve alcohol in this game... perhaps you need to be at least tipsy to play?

 - [ ] Allow revolvers to be activated, creating the y/n menu/prompt
 - [ ] Display a chance to succeed in the prompt (1/x, x being the number of chambers)
 - [ ] Check if the player can play the game, needs to pass one of the following:
    - [ ] Low morale
    - [ ] Psychotic
    - [ ] Tipsy/Drunk
 - [ ] Create the lose scenario, with the following:
    - [ ] Player dies
    - [ ] Blood splatter
    - [ ] Gun is empty
    - [ ] Unique tombstone message, maybe related to traits
 - [ ] Create the win scenario, with the following:
    - [ ] Gun only has one bullet in the chamber
    - [ ] Buffs to the player, such as adrenaline and death-defying morale boost
    - [ ] Victory message related to traits and whatnot
 - [ ] Create no-play scenarios, with the following:
    - [ ] Wearing strong helmets prevents play
    - [ ] Consider mutations and CBMs as reasons that you can't play
    - [ ] Warn the player that non-revolver-type weapons aren't designed to play Russian roulette

Here are some thoughts on how certain traits would interact. 
 - Psychotic can play sober
 - Masochist can play sober? 
 - High adrenaline can play sober
 - Wired Reflexes CBM would make you dodge the shot...?

Here are some thoughts on how this could interact with NPCs.
 - You could challenge an NPC for items (thanks Darkyhard!)
 - A crazy NPC could give it to you as a quest for no reason (perhaps as a 3 part fetch quest: 1 gun, 1 bullet, and then you have to shoot yourself to "win")

**Comment by Darkyhard** [comment]
If this gets implemented, it would be a good idea to be able to play with NPCs too, probably for items or something.

**Comment by narc0tiq** [comment]
> Wired Reflexes CBM would make you dodge the shot...?

Or even just make you unable to play. "You try to point the %s[weapon] at yourself, but can't!"

**Comment by Shoes01** [comment]
I was thinking the same thing for NPCs!

**Comment by ejseto** [comment]
You should be able to play with a variable number of bullets, i.e. whatever's in the gun at the time. The reward could scale with the risk. The tombstone message could say how many bullets you played with, and make some snide remark if you happened to play with a full cylinder.

**Comment by Griffinhart** [comment]
Hmm. I feel like you could expand this to make suicide (i.e. default key `Q`) diegetic. I mean, CDDA already kind-of sort-of has some stuff that allows for diegetic suicide (explosives, setting yourself on fire, drinking bleach, etc.), but why not allow Russian Roulette with a semi-auto?

**Comment by Rivet-the-Zombie** [comment]
>expand this to make suicide (i.e. default key Q) diegetic

It's been suggested in the past, and the answer has always been 'no'.

**Comment by Shoes01** [comment]
I wouldn't want to not implement something because save scummers would abuse it. However, after 3 "wins" in a row, the penalty could be a steep loss of morale and a "There is no escape from this hell on Earth" or something similar. Like when Bruce Banner realizes he can never get rid of the hulk.

**Comment by KA101** [comment]
Yeah, grindy for no significant story value + potential trigger for suicide-relatives = no-go.  Sorry, Shoes.

**Comment by Shoes01** [comment]
No worries, I understand!
