### ISSUE TITLE
0.B: are Military Outposts supposed to have no doors?

### ISSUE THREAD

**Issue by madamimadam** [CleverRaven/Cataclysm-DDA#10814]
Now seen two military outposts, in two different games, and neither of them had doors, just concrete walls all around. Seemed odd.

I got inside one (with a teleporter and a little luck) and found that it was made up of two rectangular rooms with a double-thickness of wall between them. There was one door that penetrated both thicknesses of wall, leading from one room to the other and another door that only went through half of the wall, so I suspect that one was supposed to be pointing towards the outside instead of the other wall?

**Comment by KA101** [comment]
Nope, mapgen weirdness.  Sorry about that.

**Comment by mugling** [comment]
Resolved in `master`
