### ISSUE TITLE
SIGSEGV in release build caused by rattlesnake

### ISSUE THREAD

**Issue by namarrgon** [CleverRaven/Cataclysm-DDA#10817]
- use release build (has to be built with clang++, not gcc)
- spawn a rattlesnake
- wait a few turns, sometimes player-movement triggers it, too

Unfortunately this only happens in optimized builds, -O0 "fixes" the issue.

```
(gdb) run
Starting program: /home/alex/build/cataclysm-git/cataclysm-tiles 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff4dc2700 (LWP 8099)]
[New Thread 0x7fffe8b3d700 (LWP 8100)]
[Thread 0x7fffe8b3d700 (LWP 8100) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff73f87af in __dynamic_cast () from /usr/lib/libstdc++.so.6
(gdb) bt
#0  0x00007ffff73f87af in __dynamic_cast () from /usr/lib/libstdc++.so.6
#1  0x000055555561ea04 in monster::attitude_to (this=0x55555b0dee00, other=...) at src/monster.cpp:461
#2  0x000055555561e8ca in monster::attack_target (this=0x55555b0dee00) at src/monster.cpp:444
#3  0x00005555556f5a36 in mattack::rattle (this=<optimized out>, z=0x55555b0dee00, index=0) at src/monattack.cpp:161
#4  0x0000555555640208 in monster::move (this=0x55555b0dee00) at src/monmove.cpp:267
#5  0x0000555555655b6b in game::monmove (this=0x555559184880) at src/game.cpp:6525
#6  0x00005555556500f1 in game::do_turn (this=0x555559184880) at src/game.cpp:1484
#7  0x000055555582a82b in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:296
(gdb)
```

git [bisect](https://gist.github.com/namarrgon/9bf0f0b11581ab7eec7b) points at five commits of which none will build due to various issues:

3ed386291fdc1cbbc096f2eb34546cf11ad6dbc2 Fix bad fix
41d6ed5fbd382667ba339d35b43777a703a146bc Fixing errors at manual merge
41da7a0535d42fd0a5017fc2c26ea4b0db85b509 Remove unused parameter to silence warning
6befa0db18eecbf18554af9642158ebce5ae21a2 Merge branch 'master' into playerless-monattacks
5b254c4f283ce65b45e81c789990705830cba318 Allow some of the special abilities to target non-players

**Comment by bkentel** [comment]
Can't reproduce it under an optimized MSVC build.

**Comment by namarrgon** [comment]
Thanks, @bkentel, your comment made me realize that I only tested it with clang, not gcc, and It seems that only clang generates code that leads to the above issue, a gcc build doesn't run into that crash.

**Comment by drbig** [comment]
Seems to happen to me also. Some additional data:

    make -j4 CCACHE=1 CLANG=1 NATIVE=linux64 RELEASE=1 TILES=1
    clang version 3.5.1 (tags/RELEASE_351/final)
    ccache version 3.2.1

Tested at commits: 637f3b7 and 21e8661

GDB says:

    #0  0x00007f81f1ee97af in __dynamic_cast () from /usr/lib/libstdc++.so.6

**Comment by KA101** [comment]
Made this a blocker since release builds (such as 0.C stable) are optimized.
