### ISSUE TITLE
Something is dorked around the stomach system

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#10823]
I report this issue because I might forget it otherwise. Therefore, please excuse my vagueness, but I am pretty sure there is something wrong.

Some time ago there was a system introduced that checked for stomach content and would prevent vomiting if the stomach was already empt (afaik). 

However, I just recently had some pemmicans and (I think I had just went from Full to nothing) had to vomit but the game said that my stomach had no contents. I tried to reproduce which led to similar results. Perhaps I can find some time to look into the code, maybe the numbers are just really off, but something is not working as intended. 

I will try to produce further evidence. 
##

**Comment by Rivet-the-Zombie** [comment]
How long had it been since you'd eaten the pemmican?

**Comment by Snaaty** [comment]
I can't quite remember, but it was not a long time ago. Also, iirc I went from full to -nothing- just shortly before (or maybe I was even full?), so there should be something in my stomach.

**Comment by bkentel** [comment]
`void player::vomit()` always completely empties one's stomach and modifies hunger and thirst accordingly -- what's the bug here?

**Comment by KA101** [comment]
Stomach should have been full and emptied, rather than coming up empty.

**Comment by Snaaty** [comment]
I will try to simulate this by taking the vomitous trait and eating stuff, I'll be back...

**Comment by BevapDin** [comment]
Could this relate to #8789?
