### ISSUE TITLE
Size of VARIABLE_SIZE vehicle parts is randomized in the wish menu

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#10820]
E.g. one time you might open the menu to find 12" bicycle wheels, another time you might find 18" ones. Additionally, when you actually spawn them, they're randomized yet again, so instead of 2x12" and 2x18" like you'd expect from previous example, you will obtain for example 2x9" wheels and 2x17" ones.

**Comment by KA101** [comment]
I'm not sure the dimensions are so important as to make getting a particular size mandatory for test purposes; if you need matching sets, ordering more at once will produce a pile of the same size.

**Comment by Asmageddon** [comment]
Yeah, figured that out, still, it was quite confusing when trying to complete a set of wheels. It's not a huge problem, but nonetheless bug, so I'm reporting it here. Feel free to tag on some low priority label onto it or whatever. A more serious related issue would be not being able to choose wheel size when installing more wheels.

**Comment by kevingranade** [comment]
Issues in the debug systems don't rate a bug unless they're keeping you from testing something.  If you want to extend the menu to specify size go ahead, but we're already drowning in issues here.
