### ISSUE TITLE
XL suggestions. #1: XL power armor.

### ISSUE THREAD

**Issue by Stretop** [CleverRaven/Cataclysm-DDA#10831]
Seeing that XL-size-fits-all-mutations concept is going to stay with us for a while, I want to present this idea for you:
1) XL basic power armor
2) XL light power armor
3) XL heavy power armor
4) XL power armor frame
+ respective XL helmets.

All those should be craftable from steel (or plastic and superalloy in case of XL light power armor), some electronics and "power armor parts" (that contain required internal wiring) that should be salvageable from "salvaged power armor" (which in turn should be salvageable not only from basic power armor, but from heavy power armor as well; light power armor should have disassemble recipe directly into electronics, superalloy, plastic and "power armor parts"). This craft should require forge (as usual), soldering iron (for electronics), anvil, aluminium tongs, metalworking chisel (those three - to form steel into form-fitting parts of plating) and it should require high skills in computers, mechanics, electronics and fabrication.

With this "Power Armor Interface CBM" and its Mk. II version would stop to be just a waste of screen space for mutants, unlucky mutant would have some chance to not be instakilled by upgraded turrets and ectothermics everywhere would rejoice =)

**Comment by Darkyhard** [comment]
How XL power armor can even exist, even if we presume that it was manufactured before the cataclysm for mutant-soldiers or something like this? Its description says that it needs direct skin contact to work properly (that's also the reason you can't wear other clothing under the power armor). Yet you need some space in the armor to handle all the possible mutations you could get for the WHOLE body. How can this work?

However, it should probably be possible to craft normal power armor using some parts that you got from disassembling another power armor. Because if you took it apart, you could assemble it like it was before, right?

Also, you can already remove bionics if you don't need it for some reason.

**Comment by Stretop** [comment]
What do you mean by "how it can even exist"? It does not exist until crafted by survivor, just like any other XL-gear.

> Its description says that it needs direct skin contact to work properly (that's also the reason you can't wear other clothing under the power armor). Yet you need some space in the armor to handle all the possible mutations you could get for the WHOLE body. How can this work?

I think that "needs direct skin contact" requirement is not entirely accurate (for the sake of brevity). What it actually needs is absence of thermal insulation layer between it and user's body. "Do not wear things under it" is just a shorthand simplification of this.

And for question "how can XL-something accomodate all possible mutations" - direct it towards @KA101 . I was said that "XL fits all" - I roll with it =)

**Comment by Darkyhard** [comment]
Well, if you wanted to wear your power armor with "Huge" mutation, you would need the armor to be twice as large or like so to fit you. However, if you just have some talons on your hands or if you are a normal human, the huge-sized armor would be extremely loose for you. You couldn't wear it properly even if it didn't require skin contact at all: your hand wouldn't reach the place where it needs to be, same with head, legs, feet etc.

**Comment by Stretop** [comment]
It is all very good and well (and true), but again: as it stands now, XL-gear fits all mutations. Such is @KA101 and @kevingranade decision and we abide by it.

I offered this with "Large" (and "Huge") and heavily mutated survivors in mind (yep, it would also be awesome to meet huge survivor zed wearing this), but again it would fit them all. Do not ask me "how" or "why" =)

**Comment by Zireael07** [comment]
That's a pretty cool idea, the only problem is figuring out how much stuff the recipes should take.

**Comment by Stretop** [comment]
By my rough estimates full disassebling of four (maybe five) power armors should give you enough materials for one "Huge-worthy" XL power armor.

**Comment by KA101** [comment]
We've also said in the design doc that you can't make power armor (machining that is not and will not be operational, no matter how much whining you do), and I'm getting flak on the forums for the game being too easy as is.

So, no means no.

**Comment by Stretop** [comment]
> I'm getting flak on the forums for the game being too easy

But this can actually be used to make the game _harder_. Sheesh.

**Comment by Griffinhart** [comment]
>you can't make power armor

Except that this isn't making power armor, at least not from scratch. Just have power armor (or salvaged power armor) be a recipe requirement. Now you can have XL power armor, but it's still got the same minimum bar to get (i.e. RNGesus blesses you with a suit [or more] of PA), *plus* you'd need to learn the recipe, *and* you'd need the materials and tools to convert a suit of PA into XLPA.

**Comment by narc0tiq** [comment]
Altering an existing power armor seems like it should be at least somewhat
feasible, but require a very specialized set of tools, likely including a
fair few bits of powered and computerized equipment. The initial suggestion
using "some electronics and 'power armor parts'" feels too simplified, and
the suggested tools seem far too crude for the desired operations (and
adding advanced tools that would be used for only this one job... doesn't
seem sensible).

Overall, it seems like balancing it "correctly" would make it far more work
than most people would ever be willing to put in, and therefore would
hardly ever be exercised at all. Combined with the non-trivial amount of
work to implement it in the first place, I have to agree with @KA101 and
@kevingranade -- it doesn't make much sense currently.

**Comment by Griffinhart** [comment]
>adding advanced tools that would be used for only this one job... doesn't
seem sensible

And I suppose that adding a CVD machine, plus a whole new lab ending just
to house said CVD machine, just for a small set of diamond-coated melee
weapons *is* sensible?

**Comment by Stretop** [comment]
> feels too simplified

And that seems to be because none of you actually researched, how those power armors are made. I researched this, but I think it would be better to continue this on forums: http://smf.cataclysmdda.com/index.php?topic=9250.0

**Comment by narc0tiq** [comment]
On Tue, Jan 13, 2015 at 7:17 PM, Griffinhart <notifications@github.com>
wrote:

>
> And I suppose that adding a CVD machine, plus a whole new lab ending just
> to house said CVD machine, just for a small set of diamond-coated melee
> weapons *is* sensible?



Nope.

**Comment by KA101** [comment]
OK, we can start the pull process on diamond weapons anytime.  Give the word.

**Comment by Rivet-the-Zombie** [comment]
We could add some more recipes to the CVD machines so they're not so limited. Maybe use them to make high-end solar panels with the right materials, or use them to improve armors as well.

**Comment by KA101** [comment]
I'd support solar-panel (possibly even quantum-panel) crafting via CVD, and have gone on record with that support earlier.

**Comment by Stretop** [comment]
By the way, I have looked up modern day CVDs - they look like they can totally be fitted into large enough vehicle: http://www.products.cvdequipment.com/products/lpcvd/in_product1/ Maybe even as multitiled system: http://rchassociates.com/index_files/Page477.htm

**Comment by Griffinhart** [comment]
Personally, I'd rather see lathes added to CDDA before CVD machines, since that would allow for the possibility of turning gun barrels.

**Comment by Stretop** [comment]
Personally, I'd rather see metal-rolling ([like this](http://www.statga.lt/var/ezwebin_site/storage/images/statga/galimybes/valcavimas/valcavimas/valcavimas_02/3484-1-lit-LT/valcavimas_02_galleryqueryfull.jpg)) and metal-extruding ([like this](http://3.imimg.com/data3/TI/ET/MY-2580998/single-screw-extruder-250x250.jpg)) machines added to CDDA, since that would allow for the possibility of advanced metalworking. Creation of all that is craftable now via simple forge and anvil really strains suspension of disbelief.
