### ISSUE TITLE
XL suggestions. #2: XL melee weapons, throwing weapons, bows and crossbows (with XL arrows and bolts).

### ISSUE THREAD

**Issue by Stretop** [CleverRaven/Cataclysm-DDA#10834]
Well, this one is strictly for "Large" and "Huge" mutants.

As mutant's body grows bigger - it is logical, that normal weapons would become too little for him to use effectively. So I offer to create XL variants of most melee weapons, throwing weapons, bows and crossbows (and ammo for them). They would be heavier, larger, they will do more damage but they would have less accuracy and require more time and resources to craft. "Large" mutants should be able to use XL weapons as well as normal weapons, but "Huge" mutants sould be able to use only XL weapons.

P. S. These weapons should be avaiable to mutant factions as well for proper arming of their larger members.
##

**Comment by Rivet-the-Zombie** [comment]
What about normal-size characters that are freakishly strong/skilled?

If these become a thing, somebody is going to want to play a character based off somebody like Pier Gerlofs Donia or a Landsknecht re-enactor.

**Comment by Stretop** [comment]
> What about normal-size characters that are freakishly strong/skilled?

It is not about strengh or skill. If you are not large enough, for example, for that bow - you would simply not have enough length of arms to draw it or place an arrow on it properly. As for melee weapons - it is question of center of mass and moment arm. Something that heavy and that long would shift your total center of mass towards weapon (as a result unstead of swinging weapon yourself you will swing yourself over that weapon) would throw you completely out of balance after first swing (even if you would be able to lift it without falling over it). And its handle would be too thick for normal-sized arm.

> Landsknecht re-enactor.

Isn't there already some kind of two-handed sword for that (if I remember correctly - even with "fiery" variant)?

**Comment by Rivet-the-Zombie** [comment]
>for that bow - you would simply not have enough length of arms to draw it or place an arrow on it properly.

I'll grant that a too-large bow would be pretty much impossible to use in the standard fashion, but humans are very adaptive.

![footbow](https://cloud.githubusercontent.com/assets/5084581/5697745/6b0c2344-99bf-11e4-9961-9089f294691c.jpg)

>As for melee weapons - it is question of center of mass and moment arm. Something that heavy and that long would shift your total center of mass towards weapon (as a result unstead of swinging weapon yourself you will swing yourself over that weapon) and also would throw you completely out of balance after first swing (even if you would be able to lift it without falling over it).

Unwieldy? Yes. Very difficult to use? Yes. Sword somehow throws *you* when you swing *it*? Physics says no. How much do you think a sword (even a really huge one) weighs? They're surprisingly light for their size.

>Isn't there already some kind of two-handed sword for that (if I remember correctly - even with "fiery" variant)? 

The Landsknecht used zweihander, yes, but they were renowned for using swords that were unusually large, even by the standards of a zweihander.

**Comment by Stretop** [comment]
> I'll grant that a too-large bow would be pretty much impossible to use in the standard fashion, but humans are very adaptive.

Do you imply that humans would do this when surrounded by zeds or running away from swarm of angry giant bees? =)

> How much do you think a sword (even a really huge one) weighs?

Normal one? 2-3 kgs. There are lighter variants, sure. But if we suppose that "Huge" mutant is twice as big in every direction compared to normal - XL weapon then should be twice as long and 8 times as heavy as normal one.

> Sword somehow throws you when you swing it? Physics says no.

I know. This was a "russia reversal"-like joke =)

On more serious note - this game really needs fatigue system. It would have been useful for such issues,

**Comment by Rivet-the-Zombie** [comment]
>this game really needs fatigue system

I PRed a simple one a while back, which @kevingranade used as inspiration for a much better system (I'm still hoping to see it finished, Kevin! I really liked it.) so the idea is there, it's just not been implemented yet.

**Comment by Stretop** [comment]
> You shoot them before you have to run away.

Okay, and how do you aim from such position? =)

**Comment by Rivet-the-Zombie** [comment]
Research indicates you aim a footbow the same way you aim most bows without specialized sights; you sight down the arrow, or you add some of those specialized sights to it.

**Comment by Stretop** [comment]
And my research shows that such footbows were used mainly for volley fire by large formation of archers due to it having really poor individual accuracy. I doubt that such mode of fire would be useful for individual archer (especially considering how much time you would have to spend on "reloading").

By the way, it reminds me: XL bows and crossobows should have longer ranges of fire and less spread (but still lower "to-hit" bonus), since bigger and heavier arrows and bolts are less vulnerable to wind and other accuracy-reducing factors.

**Comment by Stretop** [comment]
As side idea: if you can use a really big bow and really big arrow, how about adding to it a really big smoke-generating arrowhead ad then shoot it into giant bee-hive? Bees are smoked out and you can raid it for honey and royal jelly.

Ursine mutants would surely approve =)

**Comment by NaturesWitness** [comment]
I like the idea of equipment that's been designed for characters with physical strength beyond the normal human threshold, but trying to hard-lock gear to the size system feels like a recipe for massive headaches.  The system we have (normal, large, huge) just doesn't feel robust enough to say "you can't use this sword, no matter HOW strong you are".
Its not quite the same as the XL armor, which I've always felt was never actually about size at all.  It meant that the item was designed to be far more adjustable than would be considered needed for an average human being;  it's truly " one size fits ALL".  You could be 8 feet high or 3 feet, this gear is meant to be sufficiently adjustable enough to accomadate you.

We also hit the issue of mutations that specifically affect the arms.  Say someone has tentacle arms.  Your character should probably have the needed reach and flexibility to handle ANY size of weapon, provided they have the physical strength to do so.

My thought is we should either stick to using the required strength system to simulate gear for massively big players, or size-oriented equipment should only extend to speed and to-hit bonuses for being the right size, not hard "you can't use this" locks.  This is Cata after all, you can beat a zed to undeath with a ham sandwich if you want.

**Comment by Stretop** [comment]
> but trying to hard-lock gear to the size system feels like a recipe for massive headaches

Nope. We alredy have equipment-locking for certain mutations, so implementing this is not going to be that difficult.

> My thought is we should either stick to using the required strength system to simulate gear for massively big players,

But size is not about strength at all - it is about center of mass.

> Say someone has tentacle arms. Your character should probably have the needed reach and flexibility to handle ANY size of weapon, provided they have the physical strength to do so.

But absence of bones in that "arms" would likely preclude them from using any heavy weapon at all.

**Comment by Rivet-the-Zombie** [comment]
>so implementing this is not going to be that difficult

The system that handles wielding items is not the same system as the one that handles wearing them. Please don't declare a coding task trivial if you don't actually know whether it is.

**Comment by Stretop** [comment]
Well then. There is a system that makes glass pane so spectacularly shatter when used as weapon. Why not make XL weapons knock down their inappropriately sized users when used as weapon?

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
