### ISSUE TITLE
Rocket Launchers OP

### ISSUE THREAD

**Issue by JoeKlesczewski** [CleverRaven/Cataclysm-DDA#10835]
So a few days ago, @KA101 and I were discussing the pricing for rocket launchers (over on issue #10765), and a bit of research has lead me to believe that, currently, the in-game rocket launchers are significantly overpowered when compared to their real-life counterparts.

[Here's a source I'm using for the M72.](http://www.inetres.com/gp/military/infantry/antiarmor/M72.html)
[And here's a source I'm using for the RPG-7](http://www.armyrecognition.com/russia_russian_army_light_heavy_weapons_uk/rpg-7_anti-tank_grenade_rocket_launcher_technical_data_sheet_specifications_information_description.html#identification)
And of course, I'm also using the wiki pages.

For instance, in-game testing with an M72 LAW showed it able to knock out a single wall tile from a standard house upon a direct hit while my aforementioned source says:

> Three LAW rounds fired at the same area of a wood-frame wall usually produce a man-sized hole.

From the looks of things, it's not a useful weapon in real life except in a single-target anti-light-armor role (which, somewhat unsurprisingly, is what it was originally designed for). Hence, as part of this issue, I am suggesting that the effect of the rocket's explosion be nerfed.

The rocket that we are using for the RPG-7 - the PG-7VL rocket - has roughly double the penetration of the M72, which is also reflected in the JSONs (though it would, of course, have to also be adjusted down if that of the M72 is adjusted down). While I would like to suggest that we move the "default" RPG-7 rockets down to the older PG-7V ones, which are comparable in ability to the M72, that might be something better suited to its own issue/PR. However, even with the larger rocket, it's still somewhat overpowered - I could get the thing to reliably punch two-tile holes in walls, which is more than is realistic.

Common to the two, however, is a factor that makes them much more powerful than they are in real life - explosion radius. In Cataclysm, we handle all explosives from TNT to frag grenades in roughly the same manner - they have a blast radius, and anything in them is damaged. Now, the problem here is that none of the rockets we are using for the rocket launchers are fragmentation rounds, but instead HEAT ones. This makes sense - the pre-cataclysm world would probably not have had overmuch issue with civilians owning heavy anti-tank munitions (due to the looming threat of invasion), it's very much a stretch to extend that to heavy anti-personnel munitions.

Regardless, despite the fact that these things are launching anti-armor rockets (which is a fact that I think should stay) they have a fairly considerable blast radius. This should probably be corrected, so that the rockets are single-target only, or at least with only scratch damage to extremely close soft targets.

The reason I opened an issue for this is twofold: for one, I don't understand how or where the blast radius calculations, etc. are done, so I felt it best to first obtain advice and line up a plan for what should be changed, and secondly this is something of a significant change, gameplay wise, so I'd thought it best to see if there was some manner of outstanding objection to the change.
##

**Comment by KA101** [comment]
Removing the explosion tags (or writing new, tightly-focused ones) would probably suffice for the area-effect problem.

**Comment by QuantumInvictus** [comment]
That's probably what will need to be done, but could you direct me to where the explosions are actually handled? I haven't been able to find the right bit of code.

**Comment by QuantumInvictus** [comment]
Taking a look at the fragmentation-handling system right now. It's interesting. Would be nice if there was some central document explaining the general, top-level idea behind these systems - don't suppose that such a thing exists anywhere?

**Comment by KA101** [comment]
Those generally track critters, so at -1 they're blank.

damage.cpp is a good starting point for the effects of the EXPLOSIVE tags.

**Comment by QuantumInvictus** [comment]
Yeah, I figured as much - just would nice to have a central reference like there is for e.g. game balance.

Anyways, it would appear that part of the problem I mentioned in the last part of my post wasn't actually a problem so much - the problem with frag damage was that loss-of-damage wasn't being kept between tile-checks, not that the game didn't distinguish between fragmentation and concussion damage.

Of course, I still can't seem to find where the armor penetration stuff is applied for tiles. Always in the last place you look and all that.

**Comment by KA101** [comment]
Yeah, if there's fragmentation you'll see it draw shrapnel.  Not sure we model concussion falloff that thoroughly, truth be told.

**Comment by QuantumInvictus** [comment]
A quick look at game::do_blast() seems to indicate that it isn't - even sitting behind a wall doesn't appear to be able to protect you from a full hit from a blast, which should probably be changed. First it looks like I should figure out if monster::get_armor_cut() and the like work for NPCs - they don't appear to, or at least don't appear to work *correctly*.

**Comment by QuantumInvictus** [comment]
A bit of an update - *monster::get_armor_cut()* claims that it doesn't take into account worn armor, but *player::get_armor_cut()* works exactly the same way (though using a different bonus, strangely enough) without noting the same. Does anyone know which one is right?

**Comment by BevapDin** [comment]
`monster::get_armor_cut` is *only* used on monsters, `player::get_armor_cut` is only used by player/NPCs. Monsters don't have worn items, so it *can* not take worn items into account.

**Comment by QuantumInvictus** [comment]
Yeah, I just looked again, and it looks like I didn't notice the function call to `player::get_armor_cut_base`. Whoops.

**Comment by BevapDin** [comment]
>  like I'd expect - is this a bug?

Most likely. It seems to be swapped, `monster::get_armor_bash` uses `armor_cut_bonus`.

> Wait, don't some monsters have worn items, e.g. firefighter, police, and military zombies? 

The description is purely for the player, look at the `monster` / `mtype` classes, they don't have any worn items vector or similar. The firefighter has bash/cut armor values of 6 each, a standard zombie has 0 for both. These values simulate the armor they wear.

**Comment by narc0tiq** [comment]
Yeah, any clothing you may find in the same tile as a monster corpse was generated at the same time as the corpse was created (rezzed zombies have a flag that makes them omit clothing generation when they die). Anything they may be described as wearing can be considered part of the monster itself.

**Comment by QuantumInvictus** [comment]
Alright, fixed the mixup.

Anyway, that's an interesting way for monsters to work - is there any particular reason for it, or is it a case of "that's how it was implemented and nobody's gotten around to changing it"?

**Comment by narc0tiq** [comment]
Just at a guess: it's much simpler, there are many more monsters than there are players and NPCs, and it mostly makes sense.

**Comment by QuantumInvictus** [comment]
That makes sense - if we don't need to track all those clothing items until the zombie's dead, then we might as well not do so.

**Comment by Leland** [comment]
Closing - old and no movement. Feel free to ping me here if there's still interest, or make a new issue.
