### ISSUE TITLE
Policebots and Mutants

### ISSUE THREAD

**Issue by Stretop** [CleverRaven/Cataclysm-DDA#10847]
It was mentioned in the lore, that bots do not consider zeds to be enemies because "animals cannot be criminals". If it is so, shouldn't those same bots stop considering post-threshold mutants to be enemies, since they are (except Alphas, Meds and Elfs) demonstrably non-human?
##

**Comment by KA101** [comment]
Will be looked into.

**Comment by Griffinhart** [comment]
>that bots do not consider zeds to be enemies because "animals cannot be criminals"

Just out of curiosity, since this just happened in my game, but does "bots" encompass "turrets"? Because I just saw a turret shoot a zombear to death.

```
From the west you hear P-p-p-pow! x 8
You activate your Power Armor Interface Mk.
II.
Your power armor engages.
The turret fires its smg!
From the west you hear P-p-p-pow!
The zombear dies!
The turret shoots the zombear.
From the west you hear P-p-p-pow! x 3
```

**Comment by KA101** [comment]
That's the other half of the problem, namely that we *are8 getting bots to finally engage zeds and that lore is due for a change.  Waiting on balance data and critter factionalization.

**Comment by chaosvolt** [comment]
Agreed, this is a lore issue. Same reason the wiki still claims the Mycus are caused by the blob when they're now in conflict (as hinted at in the source code concerning how Mycus threshold and mutagen don't mix).

**Comment by Soyweiser** [comment]
Where on the wiki? Not that hard to change. But I have no idea what has changed lorewise.

**Comment by Coolthulhu** [comment]
Lorewise robots no longer treat zombies and mutant as animals and attack according to perceived danger.

**Comment by chaosvolt** [comment]
Need to find the lore page on the wiki, I guess. Hmm. And if I can find where the latest lore is...

**Comment by Soyweiser** [comment]
http://www.wiki.cataclysmdda.com/index.php?title=Lore

**Comment by chaosvolt** [comment]
Hmm. Looks like the lore page itself isn't where the AI oddity is mentioned, it's in timeline.

> In an effort to combat the new threats of both large amounts of undead humans and various otherworldly horrors, the automated security forces are quickly reprogrammed to behave much more aggressively, killing threats instead of just trying to arrest them if they were supposed to, and adopting a much wider view of what constitutes a threat. Unfortunately, this backfires - they still fail to identify the undead as humans, and continue to ignore them since animals can't be criminals, but the new settings lead them to turn on the human "trespassers" running the security network, and the networked security systems identify almost any living human as a hostile threat to be eliminated. The larger network itself collapses shortly afterwards, leaving no way to adjust the settings back, as each security unit - police station, military turret, autonomous hunter vehicle - reverts to independent control operating under the last instructions received

Of course, moose prove a hundred times over that maybe the turrets should regard animals as potential hostiles. XP

**Comment by Coolthulhu** [comment]
That's an old version. I think there is an updated one on the forum that no longer has this "identify as human" thing, which no longer applies.

**Comment by chaosvolt** [comment]
Definitely another thing to eventually be updated on the wiki. I'd rather quickly wound up swamped just trying to update item, profession, and other game-related additions. @_@
