### ISSUE TITLE
Windows builds failing to load JSON data.

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#10857]
As of a906bb20c25d216fafa763071959b4f271ed8d3b, Windows Curses and Tiles versions are failing to load JSON data (which is an improvement over the previous two attempted builds, which didn't build at all!). Presumably still due to #10830. Needs a priority fix.

**Comment by narc0tiq** [comment]
Initial findings: <http://dev.narc.ro/cataclysm/debug-b2130.txt>

I made a version that _actually tells you what file_ it was statting, and it gave me this: <http://dev.narc.ro/cataclysm/debug-b2130-informative.txt> -- obviously those paths don't exist in the current working directory. Should read something like `data/mods/Animatronics` and `save/Beagle`.

Unfortunately, that's about as much time as I have to spend on this right now. Of note is that the same code works on Linux, so I'm guessing the path walking algorithm includes parent directories there.

**Comment by narc0tiq** [comment]
@bkentel Can you take care of this? Else I'll poke at it again tomorrow if nobody else picks it up.

**Comment by bkentel** [comment]
I'm going to look into it now; thanks for the report.
