### ISSUE TITLE
Assualt on precinct Z. started in locked room that I couldn't escape

### ISSUE THREAD

**Issue by CosmicKobal** [CleverRaven/Cataclysm-DDA#10855]
I assume that I was in some kind of supply room based on the loot in the lockers. Thought it was a nice touch to include a clown suit in there! :)
##

**Comment by KA101** [comment]
That's the evidence locker, most likely, and I suppose there should be a door-release of some sort from the inside.  Probably checks for police & matching badge and logs you (or sounds an alarm if not) and opens the door.

**Comment by Leland** [comment]
This is most likely a bug, but it's an old thread and is a difficult bug to test for.

If anyone runs into this again, please provide a savefile and either comment here or start a new issue to get it addressed.

Thanks!
