### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by DavidKeaton** [CleverRaven/Cataclysm-DDA#10850]
So, this is put here to either get a talk going or something along those lines. Most of this is merely my opinion, so I am obviously not trying to _change_ anything as far as how the coding style is dictated, but I wanted to share my thoughts.

I am fine with the general coding style in the repository, but one thing that is driving me *bonkers* lately is all the `auto` usage. The addition of `auto` iterators on behalf of kevingranade has been great, simplifying a lot of needless boilerplate, and makes it _much_ cleaner. However, declaration of `auto` variables as their type, instead of its true type is much more of a hassle than it's worth. Why hide the type of the variable? If one does not know the inherit type spit out by a function, or does not wish to constantly check where it morphs into another magical variable container, why would you want to make it harder?

At one point, a `static_cast<int>` on an `auto` var is used, when simply declaring as `int` is more than suitable, and makes it apparant as to what it will hold. If the type shifts as it is filled with a different variable, this change won't be apparent to anyone but the person coding it, and would make bugs harder to find unless debugging the program itself. 

I have no qualms with `auto` in most cases, as it is glorious if used correctly (see also: my opinion), but to use it needlessly just makes the code look like a clusterf**k.

Everyone has their coding styles, which is completely fine, but let's not make the code look like crap. Nowhere else in the code have I seen `auto` splattered around without reason. Hell, it was solely used in iterators. Wouldn't keeping it this way keep skimming the code _vastly_ more sane?

Sorry for the vent, and I am not trying to point at anyone or bash styles. I just want the code to be easily accessible to all contributors who may not have the easiest time discerning what is going on in the code, and I know that keeping it simple and accessible is important from what I have gathered.

**Comment by Griffinhart** [comment]
Having not looked at CDDA's usage of `auto`, but having used `auto` extensively in one of my own engines, `auto` *does* make things easier. Use `auto` when the data type is irrelevant to the code you're writing, and cast it when it *is* relevant.

**Comment by KA101** [comment]
Autos may be tougher for new folks to really "get"--I know I don't think to use them--though I think this comes off a bit harsh.  :-/

**Comment by DavidKeaton** [comment]
It does, and I want to apologize ahead of time. :-\ I don't wish to reword myself, but I will claim responsibility for coming off like a total asshole.

**Comment by kevingranade** [comment]
I agree that something like ```auto num = 1;``` is rather nonsensical, and
I think the main thing that triggered this issue.
I'm not sure how to state this clearly for a coding standard though.

**Comment by DavidKeaton** [comment]
It just seems counterproductive both from a worthy coding standpoint, and from you guys' standpoint of this being very accessible, which is why I agree with you against using boost. It's great, but I have had my gentoo build up for months and yet to install boost.

**Comment by DavidKeaton** [comment]
Perhaps stating `auto` to be reserved for iterators and special use cases only?

**Comment by DavidKeaton** [comment]
@Griffinhart while I understand to a point that logic, as a person who prefers to read the code quickly in most cases, I don't want to have to keep up with dozens of `auto` vars and how they have morphed over time. Not only that, but most of the code declares type to its true type, so why start shoving in `auto` everywhere all of a sudden.

**Comment by Griffinhart** [comment]
>I don't want to have to keep up with dozens of auto vars and how they have morphed over time

So... don't? Again, if it doesn't actually matter to the code you're writing, why do you care about the different stages of an `auto` variable? Again, not having looked at CDDA's code, is there actually an instance where the actual type of an `auto` variable both matters *and* can't be casted so you can do what you want to it?

**Comment by DavidKeaton** [comment]
I am going to agree to disagree here, as I don't want things to escalate in any regard.

**Comment by narc0tiq** [comment]
I've learned that `auto some_var = int{ initial_value }` tends to be "the C++11 way", at least according to Herb Sutter. `static_cast` and friends probably shouldn't be used much anymore.

I'm not sure why `auto num = 1` is nonsensical (it makes a default-sized int; you could make it `auto num = 1UL` if you wanted, say, an unsigned long).

That said, I'm totally not a C++ person at all, so this is just based on a little reading I've done over the past week.

**Comment by DavidKeaton** [comment]
Fair enough. :-)
