### ISSUE TITLE
Vehicle Examine Interface: Repair auto-snap does not work in Horizontal/Hybrid modes

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#10873]
In vertical mode, `r` will auto-snap to damaged sections (i.e. if the currently-highlighted section has no damaged parts) so if you're repairing a vehicle in its entirety, you can just hold down `r` and hit Enter occasionally to choose the tool to repair with.

In Horizontal/Hybrid modes, repeatedly hitting `r` when a non-damaged section is highlighted just makes the cursor snap around randomly, as far as I can tell.

**Comment by KA101** [comment]
Hadn't known it was supposed to snap around, so IMO expanding that's a feature request.
