### ISSUE TITLE
Acid with no containers

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#10878]
It spawns without a container. As a liquid this means you can't pick it up.

**Comment by DavidKeaton** [comment]
Same applies to hydrogen peroxide.

**Comment by BevapDin** [comment]
@EkarusRyndren Acid does not spawn naturally, so it doesn't need a container. An acid item in the players inventory (spawned through the debug menu) works fine for crafting or similar. However, setting a container is simple, what container should it spawn in?

**Comment by Lain-** [comment]
Not @EkarusRyndren, but I would say it should spawn in a glass container.

**Comment by BevapDin** [comment]
Actually, after testing this: acid and acid water and weak acid water already spawn in a container: a gallon jug. That works fine when spawned from the debug menu.

**Comment by kevingranade** [comment]
Addressed by #10903
