### ISSUE TITLE
Veh turrets ignoring zed dogs/kids

### ISSUE THREAD

**Issue by KA101** [CleverRaven/Cataclysm-DDA#10875]
Apparently the vehicle turrets won't try to target zombie children or dogs.  They can still kill them just fine if they happen to be between the turret and its intended target, but turrets don't seem to aim directly at 'em (to the point where the kid can smash the MIC front bumper unimpeded).

**Comment by mugling** [comment]
Vehicle turrets currently broken for other reasons. This issue dependent upon #17071
