### ISSUE TITLE
Vehicle stereo system has huge range

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#10879]
Version: 0.B-2487-ge57fa9f

I'm 10 map tiles away from my vehicle and I'm still getting the full Music morale bonus.

**Comment by KA101** [comment]
Yep, your bass isn't *that* thumping.  XD

**Comment by DavidKeaton** [comment]
It really *is* all about that base.

**Comment by Lain-** [comment]
If the player can hear the music from ten map titles away. Does this means that if roaming horse is enabled the horse can be summoned by the music from ten titles away to? That's nasty.

**Comment by Griffinhart** [comment]
Vehicle music is also audible underground (i.e. `From the <direction> you hear You listen to <music>` strings are printed. Didn't check if the morale bonus was still being maintained).

**Comment by mugling** [comment]
Fairly sure this is fixed in `master`
