### ISSUE TITLE
Vehicle stereo system string badness

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#10880]
Version: 0.B-2487-ge57fa9f

1. Get a Music CD and a vehicle with stereo system installed.
2. Play music in the vehicle (i.e. `Turn on music` in the vehicle control menu).
3. Walk away from the vehicle.

```
From the south you hear You listen to a
funky bassline.
From the south you hear You listen to a
sweet guitar solo!
```

Should probably be `From the <direction> you hear a <music>` or something.

**Comment by KA101** [comment]
This came up once before and I recall it got dismissed, as changing the string would mess u the mp3 player.  Could be fixed but entails a bit more work than one would think.
