### ISSUE TITLE
Codeblocks

### ISSUE THREAD

**Issue by bkentel** [CleverRaven/Cataclysm-DDA#10894]
The project file has a lot of cruft in it that references one person's specific environment; for example:
```
<Add directory="WinDepend/SDLttf/SDL_ttf-2.0.11/include" />
<Add directory="WinDepend/SDL-1.2.15/include/SDL" />
<Add directory="WinDepend/SDLImg_binVC/SDL_image-1.2.12/include" />
```
I'd like to clean up the project file to change these sort of references. Include directories and the like should be specified in the user's configuration settings, not the project's. This change could break someone's build, but without the change the build is already broken for everyone else.

**Comment by macrosblackd** [comment]
A big issue is that C::B doesn't have a separate user config per project. It's all bundled in to the project file.
One suggestion I would make is to just include the dependencies for non *nix users. Every time I have to recreate my workspace for CDDA I generally spend about 2-3 days figuring out all the dependencies and setting them up. Alternatively, we should have a script to automatically download and setup the dependencies if we can't include the libraries directly.

**Comment by bkentel** [comment]
The dependencies can be included, but they should be given without a path.
i.e.

```<Add library="WinDepend\SDL-1.2.15\lib\libSDL.dll.a" />```
Should be
```<Add library="SDL2" />```

Since C::B doesn't have per project user config, the global variables setting in C::B could be used?

**Comment by macrosblackd** [comment]
Setting it up in the global settings would enable those libraries for every project compiled - not a huge I imagine for most cdda devs, but something to keep in mind.

When you say they should be given without a path, Just adding "SDL2" wouldn't work unless SDL2 was a directory in the top level of the project directory. The first path is using a relative path, so it's saying that there is a WinDepend directory with SDL-1.2.15\... 

Ideally we should try to get the static libraries included in the repository, set up the C::B projects to perform a static build and then tell everyone to not touch it again... This would actually be a very good thing since it would eliminate any possible library version issues. I know that the latest version of SDL2 has a bad header file that needs to be replaced.

**Comment by bkentel** [comment]
By Global I mean ```Settings->Global Variables...```.
```<Add library="SDL2" />``` isn't a path, but a rather a filename which codeblocks will interpret as $(user library paths)/libSDL2.a under gcc at least.

**Comment by bkentel** [comment]
What was the issue with the SDL2 header? I've built with it on my box with no problems.

**Comment by macrosblackd** [comment]
They may have already fixed it then. The version I had downloaded needed SDL_platform.h replaced.

**Comment by kevingranade** [comment]
Bundling the dependencies in the distribution is a possibility, but
libraries do not go in the repository.

**Comment by narc0tiq** [comment]
I could throw up a premade zip of the WinDepends folder somewhere on
dev.narc.ro/cataclysm, if someone will make that for me.

**Comment by DavidKeaton** [comment]
Hmm, at times like this I say, Vim is the way to go! ;-)

**Comment by macrosblackd** [comment]
Vim is never the way to go. IDE's exist to remove a lot of the hassle
involved with getting something as obtuse as VIM configured into a
workable editor.

**Comment by DavidKeaton** [comment]
oh sweet god _ouch_
Well if you have vim configured you don't need to configure it anymore. A few plugins, a nicely written vimrc, and it is far from obtuse! ;-)

**Comment by macrosblackd** [comment]
Sure, good luck finding the right plugins. The few times I tried to
figure out VIM left me with a really bad impression of it.

**Comment by DavidKeaton** [comment]
It can be obtuse, especially getting it _set up_, so I can agree with you there all bias aside. The plugin system is _very_ archaic, but there are plugins that are made specifically to be a plugin manager, and allow easy access and installation to most of the plugins out there. Vundle is an amazing one, it just uses github user/repo pairs or vimscript numbers (from vim.org plugins page) and auto sets them up in a way that doesn't overwrite anything. I will admit getting my vimrc to where it is now (where I haven't had to change a thing in months) took a while, and some pain in the ass moments. I will say though, set up, that thing is a _beast_. Have been using it for about 6 years now.

**Comment by macrosblackd** [comment]
Yep, and all I did was download and install visual studio + resharper.

**Comment by DavidKeaton** [comment]
To each their own matey.

**Comment by narc0tiq** [comment]
I'm highly tempted to remove a bunch of posts. No editor holy wars in the issues, please.

**Comment by DavidKeaton** [comment]
Not my intentions but duly noted.

**Comment by Griffinhart** [comment]
>Vim is never the way to go. IDE's exist to remove a lot of the hassle involved with getting something as obtuse as VIM configured into a workable editor.

>Every time I have to recreate my workspace for CDDA I generally spend about 2-3 days figuring out all the dependencies and setting them up

You say "vim is worse than all IDEs", but what I'm seeing is "it takes me 2-3 days to set up a project in my IDE".

**Comment by KA101** [comment]
>I'm highly tempted to remove a bunch of posts. No editor holy wars in the issues, please.

Seconded.

**Comment by mugling** [comment]
This nolonger appears to be a problem.
