### ISSUE TITLE
No collisions when dragging vehicles sometimes

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#10898]
This one's a little tricky to reproduce, so bear with me here:

- Get a food vendor cart, or something else that's draggable and two tiles long.
- Grab it by the rear tile (i.e., the kitchen unit, not the fridge).
- Move one tile such that the _front_ tile of the vehicle goes into the same tile you're in.
- Your next tile, walk into a wall, closed door, or other impassable object.

Doing this, I managed to find myself in this position:
![im in ur wallz](http://i.imgur.com/27aXMwd.png)
...which is impressive, given that there's a wall right under me.

**Comment by mugling** [comment]
@Coolthulhu rewrote vehicle dragging some time ago
