### ISSUE TITLE
Critter crash

### ISSUE THREAD

**Issue by KA101** [CleverRaven/Cataclysm-DDA#10895]
Looks like killing a critter with a knockdown/back attack, in the presence of friendly critters (I've had it crop up with friendly/hostile giant bees, but first occurrence was before Coolthulhu's fix at #10886 ), segfaults the critter planning AI.

Stack trace: http://pastebin.com/Cdx5HiVY

Little fiddly to reproduce, this is how I managed it for that stack trace: get some giant bees (2 each, friendly and not) close enough that the not-friendly go Hostile.  Help out "your" bees, using a style/skill that lets you do knockdowns or knockbacks (I used Dragon KF here; Brawling got it last night but I couldn't reproduce with a debugger attached), and fight until you defeat a hostile bee with such an attack (spawn additional bees as needed).  Segfault.

**Comment by kevingranade** [comment]
Is something in the ai code holding a pointer to a monster?

**Comment by KA101** [comment]
Was a faction thing, apparently.
