### ISSUE TITLE
Hostile vermin

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#10891]
Vermin can be hostile. They can't attack, but can trigger "the <veminname> is approaching! stop crafting?" type messages.

**Comment by KA101** [comment]
Question being whether to make them non-hostile, or to ignore their approach.

(Or to let them nibble at you for perhaps one point of damage, if you're not armored?)

**Comment by Rivet-the-Zombie** [comment]
I vote for nibbling in appropriate cases.

**Comment by KA101** [comment]
Or auto-kill 'em if they're hostile and you move into their square, I'd imagine.

**Comment by Shoes01** [comment]
Can we get a stomping skill then? It could tie into stomping grapes to make wine, and stomping out fires. 

:3

**Comment by KA101** [comment]
Only if we can supply power to the arcade and have a stomping game (I've seen one with spiders, or perhaps make "Dance Dance Anarchy" and let it train dodge as well?) to let people level up.

;-)

**Comment by DavidKeaton** [comment]
With stomping, you can *really* portray your anger at a situation!

**Comment by BromIDE** [comment]
Or stomping on prone monsters, which could make Aikido useful!

**Comment by Dozed12** [comment]
Stomping a crawling zombie = life complete

**Comment by DavidKeaton** [comment]
Dozed, I like the cut of your jib.
