### ISSUE TITLE
Some chemicals have odd weights/volume

### ISSUE THREAD

**Issue by Ygdrad** [CleverRaven/Cataclysm-DDA#10909]
A pack of Calcium Carbide for example has a volume of 1 but a weight of 176lbs which makes little sense.

**Comment by KA101** [comment]
Just merged a fix for that, I thought--you on latest?

*KA101 wonders if the "fix" just broke things further--he uses kg in-game*

**Comment by Ygdrad** [comment]
Alright my bad, thought i had updated, still was on yesterday's version
