### ISSUE TITLE
Segfault while walking around inside a lab finale

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#10916]
Version: 0.B-2646-gc9c38cb

Portal finale, if it matters. I released the specimens and was walking to get to the rear cells to kill things when crash occurred. Did not activate the portal or initiate a resonance cascade.

```
Program received signal SIGSEGV, segmentation fault.
muto::acquire(unsigned long)@8 (this=this@entry=0x61196d60 <mallock>, ms=ms@entry=424967295) at /usr/src/debug/cygwin-1.7.33-1/winsup/cygwin/sync.cc:78
78        void *this_tls = &_my_tls;
```

```
(gdb) bt
#0  muto::acquire(unsigned long)@8 (this=this@entry=0x61196d60 <mallock>, ms=ms@entry=4294967295) at /usr/src/debug/cygwin-1.7.33-1/winsup/cygwin/sync.cc:78
#1  0x6108377f in malloc (size=20) at /usr/src/debug/cygwin-1.7.33-1/winsup/cygwin/malloc_wrapper.cc:60
#2  0x610d9885 in _sigfe () from /usr/bin/cygwin1.dll
#3  0x00000000 in ?? ()
```

**Comment by Griffinhart** [comment]
Finally got a save that consistently crashes.

https://dl.dropboxusercontent.com/u/3273892/Bull%20Valley.zip

Walk south.

**Comment by DavidKeaton** [comment]
Interesting. Does cygwin thread things by default? I don't think any part of the code uses parallelization?

**Comment by kevingranade** [comment]
Cygwin doesn't AFAIK, but SDL does.

**Comment by DavidKeaton** [comment]
Ah hence the statements of thread sanity for its refresh functions in the docs IIRC

**Comment by kevingranade** [comment]
Tried the provided save, doesn't reproduce here either on a debug build or a release build.
Frankly I don't think a malloc(20) failing has anything to do with the game.
