### ISSUE TITLE
[488d615] Locked Doors Cannot Be Boarded Up

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#10918]
Attempting to board up a locked door you've yet to unlock one way or another is currently impossible, presumably because the 'board up door' recipe doesn't check for locked doors.

Probably a safe bet there are several other affected recipes.
##

**Comment by KA101** [comment]
I'm content with that as is, since we'd need a separate terrain for locked doors.  Likewise reinforced, etc.
