### ISSUE TITLE
Worn armors disappear when equiped hairpin is destoryed during an attamption to picklock

### ISSUE THREAD

**Issue by cellxiecao** [CleverRaven/Cataclysm-DDA#10932]
0.b
before
![before2](https://cloud.githubusercontent.com/assets/8348288/5812192/ae68d7d6-a09f-11e4-8600-74251b538cd3.jpg)
after
![after1](https://cloud.githubusercontent.com/assets/8348288/5812184/81fec2be-a09f-11e4-83bd-f14d54d128ea.jpg)
All equiped armors below hairpin have gone missing.

**Comment by sparr** [comment]
I cannot reproduce this bug in current git master

**Comment by Rivet-the-Zombie** [comment]
This should have been fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/10261.
