### ISSUE TITLE
MinGW/Code::Blocks build is broken.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#10930]
Attempts to compile the current version result in:

||=== Build: Release in Cataclysm (compiler: GNU GCC Compiler) ===|
C:\CDDA\src\advanced_inv.cpp||In member function 'bool advanced_inventory::query_charges(aim_location, const advanced_inv_listitem&, bool, long int&)':|
C:\CDDA\src\advanced_inv.cpp|1634|error: 'stoi' is not a member of 'std'|
||=== Build failed: 1 error(s), 0 warning(s) (0 minute(s), 12 second(s)) ===|

**Comment by KA101** [comment]
Fixed by #10931.
