### ISSUE TITLE
Code::Blocks fails to compile with new win header

### ISSUE THREAD

**Issue by ThinkInvis** [CleverRaven/Cataclysm-DDA#10941]
Upon compiling with Code::Blocks, the following error is instantly given:
File: [path]/Cataclysm-DDA/src/platform_win.h
Line: 17
Message: fatal error: sdkddkver.h: No such file or directory

**Comment by Rivet-the-Zombie** [comment]
Confirmed.

Why are so many recent changes hostile to Windows?

**Comment by DavidKeaton** [comment]
ddk is not installed by default, you need the windows ddk downloaded and installed (or at the very least sdk) iirc

**Comment by ThinkInvis** [comment]
I've never needed 'the windows ddk' before and I have no idea what it is. Also, it's a .h file that isn't present, not a .dll or similar; looks like someone forgot to add/deleted an important file.

**Comment by DavidKeaton** [comment]
Windows sdk/ddk provides mostly ".h" files. It's a dev kit duder.

**Comment by Rivet-the-Zombie** [comment]
What we **need** is for the code to compile correctly without continually adding extra hoops to jump through.

It was working before, and now it is not. This is a problem.

**Comment by DavidKeaton** [comment]
I wasn't disagreeing. :-)

**Comment by KA101** [comment]
Last one was @bkentel 's, merged by Kevin.  I've been letting him handle those as considered him better able to check them.

At this rate, nope.

**Comment by bkentel** [comment]
Didn't realize that sdkddkver.h wasn't available universally; I'll make a PR.

**Comment by ThinkInvis** [comment]
Compiling with MinGW, as per [the wiki] (http://www.wiki.cataclysmdda.com/index.php?title=How_to_compile), does work. Same system (windows 8.1), no changes since compiling with Code::Blocks.

**Comment by kevingranade** [comment]
My apologies, like brandon I thought it was a system library, not a
development one.

**Comment by bkentel** [comment]
No need to make apologies for me, I can say sorry for my oversight. I didn't realize that sdkddkver.h wasn't available universally; I'll make a PR. Sorry again guys who were affected :disappointed:

**Comment by KA101** [comment]
Fixed.
