### ISSUE TITLE
data/json/vehicle_parts.json contains a massive amount of duplicates

### ISSUE THREAD

**Issue by ThinkInvis** [CleverRaven/Cataclysm-DDA#10944]
I was digging around in data/json/vehicle_parts.json in order to add something as part of a feature; I noticed that a lot of the entries appeared twice. For example, "foot pedals" appears at both line 2597-2616 and line 4845-4864. The formatting is different but the properties are EXACTLY the same.

Is there any particular reason for this or should I try to delete some of them?

**Comment by BevapDin** [comment]
If the have the same "id" entry, they second definition will override the previous one. So go ahead and delete the duplicates them.

**Comment by KA101** [comment]
Duplicate tag more for the humor value, this is a real one.  ;-)

**Comment by DavidKeaton** [comment]
I lol'd

**Comment by Rivet-the-Zombie** [comment]
Redundant duplicates for double the redundancy!
