### ISSUE TITLE
rain inside garage - specific to special house type

### ISSUE THREAD

**Issue by pipehat** [CleverRaven/Cataclysm-DDA#10947]
Not sure what the house/terrain type is - house had boarded windows and traps inside, heavily stocked garage with lots of tools. When it rains, there is visible rain inside this house's garage and the player gets wet standing in it.

The bench tiles around the garage show 'indoor' and 'roof' in the debug map editor but the central concrete tiles do not have those labels.

![screen shot 2015-01-21 at 2 42 54 am](https://cloud.githubusercontent.com/assets/253436/5829788/7d988e12-a117-11e4-8986-5d82440e7bdf.png)

**Comment by KA101** [comment]
Probably the external concrete rather than internal rock_floor.  JSON fix, can throw it into the merge.
