### ISSUE TITLE
Marloss messages

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#10955]
Might be worth reducing the frequency of the "You want seeds" to at least a few turns before another message, it's kinda irritating getting flooded with "You daydream about nutty cyan seeds as big as your hand. You Daydream about succulent, pale golden gel, sweet but light" over, and over, and over, and over...

![new canvas](https://cloud.githubusercontent.com/assets/5553443/5846221/106b419e-a190-11e4-8821-66839b55c563.jpg)

**Comment by swwu** [comment]
Should be fixed in #10962.
