### ISSUE TITLE
Necropolis(?) grocery store's gate or opener has incorrect starting position

### ISSUE THREAD

**Issue by ThinkInvis** [CleverRaven/Cataclysm-DDA#10957]
I'm pretty sure what I found was a necropolis - pretty nice buildings with a bunch of craters, and the grocery store layout didn't match the normal ones, the only other being labeled 'necropolis' in the JSONs.
The grocery store had a garage-type attachment, containing a lot of food crates and a metal gate. The gate started in the closed position, but when I used the gate opener the chat log said I closed the gate (and it did, indeed, remain closed). Using the gate opener again properly opened the gate.

**Comment by DavidKeaton** [comment]
I ran into a Necropolis to try this out, couldn't seem to reproduce.

**Comment by mugling** [comment]
Much of this mapgen was overhauled by @Mshock777. Closed as no recent reports

**Comment by Mshock777** [comment]
My bad: forgot to mention this in my PR. And yes, it seems to be fixed.
