### ISSUE TITLE
Procedural generation of science labs needs work

### ISSUE THREAD

**Issue by FlorinTeal** [CleverRaven/Cataclysm-DDA#10958]
I'm repeatedly encountering labs with the entry stairwell plummeting multiple z-levels (requiring a rope to descend) directly into the lab's final room. I've also encountered several labs with the final room completely inaccessible from the rest of the lab, i.e. lacking a stairwell and surrounded on all sides by rock.

---

Edit by @Leland

There are a lot of issues relating to lab mapgen. This will be the central place to discuss them.

Previous issues:

- **Lab mapgen hallway misalignment** - #11728
- **Stairs in lab armory** - #13312
- **Lab final can spawn disconnected from all other rooms** -  #9726
- **Lab stairs can spawns in closed off areas** - #6151
- **Lab stairs connect to each other via an alternate dimension** - #1808
- **Corpse spawned inside lab wall** - #19957

##

**Comment by ThinkInvis** [comment]
I haven't ever encountered anything like this, but they do need a little more content. Encountering the same 4 rooms (counters, goo+fridge, dissector, turret) in the majority of the lab gets pretty boring.

**Comment by Snaaty** [comment]
Yeah, I have never encountered strange multi-level drops, but more diversity would definitely be a good thing. Also, I guess we could add the new chemicals to item spawns.

**Comment by Ataman** [comment]
Still an issue on 0.C-10145-g935039e

Upper room: 
![Upper level](http://bhtp.net/ataman/cdda/icelab_lvl_5_.png)
Lower room: 
![Lower level](http://bhtp.net/ataman/cdda/icelab_lvl_6_.png)

Save: http://bhtp.net/ataman/cdda/cdda_save.zip

**Comment by Oskar636** [comment]
Is this considered mapgen?

**Comment by Leland** [comment]
Making this the master issue specifically for science lab procedural generation issues. I've updated the issue description with a list of the existing ones. There are many other ones that can be found as duplicates referenced on those issues as well.

I have a feeling that there needs to be a fairly close look taken at the way the science lab goes about mapgen. We'd probably be better off having a central place for those issues rather than creating new ones each time.

**Comment by sparr** [comment]
There were some good contributions on the forum for lab mapgen improvements. Someone went so far as to rewrite it, even. If anyone can recover a cache of those posts, that would be useful here.

**Comment by ZhilkinSerg** [comment]
https://discourse.cataclysmdda.org/t/lab-mapgen-jsonization-problem-of-adjacency/14353

**Comment by ZhilkinSerg** [comment]
A lot has been done to the lab generation recently. While there is more to be done no need for open issue.
