### ISSUE TITLE
Endless farming of computer skill from lab map/project info terminals

### ISSUE THREAD

**Issue by FlorinTeal** [CleverRaven/Cataclysm-DDA#10959]
Currently able to farm infinite computer skill by logging into one of these terminals, passing the initial hack, reading the project info, and then repeatedly downloading the map data; each subsequent accessing of the map data makes another hack check.

**Comment by DavidKeaton** [comment]
it's a Unix system, I know this.

**Comment by KA101** [comment]
OK, now to make map data increase the security too.  Shouldn't be too difficult.
