### ISSUE TITLE
enemies fire at closed metal doors when player is on the other side

### ISSUE THREAD

**Issue by gcaliber** [CleverRaven/Cataclysm-DDA#10967]
You can stand next to a closed metal door with a turret on the other side, once you have alerted it, and it will fire all its ammo into the closed door. Security bots do the same thing.

Easily reproducible in labs with turret rooms. Open the door to alert the turret, then close the door and stand on the other side while it fires all its ammo at you.

EDIT: Only seems to happen under certain conditions, possibly when they are close to the door.

EDIT: This also happens with reinforced glass, and that makes slightly more sense, but I'd still think the turret/bot AI shouldn't be that stupid.

**Comment by FlorinTeal** [comment]
Turrets and robots might be stupid enough to repeatedly fire at reinforced glass, but you'd imagine NPCs would not be.

**Comment by kevingranade** [comment]
And this is a closed door anyway.  This is likely a bug in handling FOV
updates.

**Comment by kevingranade** [comment]
Fixed by #11447
