### ISSUE TITLE
Give check for PULL_METAL_WEAPON?

### ISSUE THREAD

**Issue by swwu** [CleverRaven/Cataclysm-DDA#10963]
Not entirely sure what the lore is here, but would it make sense to allow players / NPCs to make some kind of stat-dependent check to avoid losing their weapons? It seems reasonable that e.g. being incredibly strong would allow you to maintain your grip on whatever you're holding.

**Comment by Gabriel-SE** [comment]
Here's my proposal :

Katana will check player's cutting skill
AK-47 will check player's marksmanship skill
Powered quarterstaff will check player's bashing skill

In other words, if it's weapon, check it with str + player's weapon skill
else, str only.

WP = Player's skill with wielded weapon.
Chance for zombie technician to pull your weapon away :

| STR | WP 0 | WP 1 | WP 2 | WP 3 | WP 4 | WP 5 | WP 6 | WP 7 | WP 8 | WP 9 | WP 10 |
|----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|------:|
|   4 |  100 |   95 |   90 |   85 |   80 |   75 |   70 |   65 |   60 |   55 |    50 |
|   5 |   95 |   90 |   85 |   80 |   75 |   70 |   65 |   60 |   55 |   50 |    45 |
|   6 |   90 |   85 |   80 |   75 |   70 |   65 |   60 |   55 |   50 |   45 |    40 |
|   7 |   85 |   80 |   75 |   70 |   65 |   60 |   55 |   50 |   45 |   40 |    35 |
|   8 |   80 |   75 |   70 |   65 |   60 |   55 |   50 |   45 |   40 |   35 |    30 |
|   9 |   75 |   70 |   65 |   60 |   55 |   50 |   45 |   40 |   35 |   30 |    25 |
|  10 |   70 |   65 |   60 |   55 |   50 |   45 |   40 |   35 |   30 |   25 |    20 |
|  11 |   65 |   60 |   55 |   50 |   45 |   40 |   35 |   30 |   25 |   20 |    15 |
|  12 |   60 |   55 |   50 |   45 |   40 |   35 |   30 |   25 |   20 |   15 |    10 |
|  13 |   55 |   50 |   45 |   40 |   35 |   30 |   25 |   20 |   15 |   10 |     5 |
|  14 |   50 |   45 |   40 |   35 |   30 |   25 |   20 |   15 |   10 |    5 |     0 |
|  15 |   45 |   40 |   35 |   30 |   25 |   20 |   15 |   10 |    5 |    0 |       |
|  16 |   40 |   35 |   30 |   25 |   20 |   15 |   10 |    5 |    0 |      |       |
|  17 |   35 |   30 |   25 |   20 |   15 |   10 |    5 |    0 |      |      |       |
|  18 |   30 |   25 |   20 |   15 |   10 |    5 |    0 |      |      |      |       |
|  19 |   25 |   20 |   15 |   10 |    5 |    0 |      |      |      |      |       |
|  20 |   20 |   15 |   10 |    5 |    0 |      |      |      |      |      |       |
|  21 |   15 |   10 |    5 |    0 |      |      |      |      |      |      |       |
|  22 |   10 |    5 |    0 |      |      |      |      |      |      |      |       |
|  23 |    5 |    0 |      |      |      |      |      |      |      |      |       |
|  24 |    0 |      |      |      |      |      |      |      |      |      |       |

**Comment by KA101** [comment]
Every item in DDA is a melee weapon, or at least can be wielded as one.  Probably better to go with the highest damage value on the wielded object..

I'd want to move the starting points up a bit (need ST 5-6 or at least one point of skill to have a chance at retaining the weapon), personally, but apart from those points this seems workable.

**Comment by Rivet-the-Zombie** [comment]
Welcome back, @swwu!

**Comment by Gabriel-SE** [comment]
> Every item in DDA is a melee weapon, or at least can be wielded as one. Probably better to go with the highest damage value on the wielded object..

I'll use existing is_gun(), is_cutting_weapon() and is_bashing_weapon() function, in that order.

> I'd want to move the starting points up a bit (need ST 5-6 or at least one point of skill to have a chance at retaining the weapon), personally, but apart from 
those points this seems workable.

Like this ? 

Chance for zombie technician to pull away player's metal weapon :

| STR | WP 0 | WP 1 | WP 2 | WP 3 | WP 4 | WP 5 | WP 6 | WP 7 | WP 8 | WP 9 | WP 10 |
|----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|------:|
|   4 |  100 |  100 |  100 |  100 |  100 |  100 |  100 |  100 |  100 |  100 |   100 |
|   5 |  100 |   95 |   90 |   85 |   80 |   75 |   70 |   65 |   60 |   55 |    50 |
|   6 |  100 |   90 |   85 |   80 |   75 |   70 |   65 |   60 |   55 |   50 |    45 |
|   7 |  100 |   85 |   80 |   75 |   70 |   65 |   60 |   55 |   50 |   45 |    40 |
|   8 |  100 |   80 |   75 |   70 |   65 |   60 |   55 |   50 |   45 |   40 |    35 |
|   9 |  100 |   75 |   70 |   65 |   60 |   55 |   50 |   45 |   40 |   35 |    30 |
|  10 |  100 |   70 |   65 |   60 |   55 |   50 |   45 |   40 |   35 |   30 |    25 |
|  11 |  100 |   65 |   60 |   55 |   50 |   45 |   40 |   35 |   30 |   25 |    20 |
|  12 |  100 |   60 |   55 |   50 |   45 |   40 |   35 |   30 |   25 |   20 |    15 |
|  13 |  100 |   55 |   50 |   45 |   40 |   35 |   30 |   25 |   20 |   15 |    10 |
|  14 |  100 |   50 |   45 |   40 |   35 |   30 |   25 |   20 |   15 |   10 |     5 |
|  15 |  100 |   45 |   40 |   35 |   30 |   25 |   20 |   15 |   10 |    5 |     0 |
|  16 |  100 |   40 |   35 |   30 |   25 |   20 |   15 |   10 |    5 |    0 |       |
|  17 |  100 |   35 |   30 |   25 |   20 |   15 |   10 |    5 |    0 |      |       |
|  18 |  100 |   30 |   25 |   20 |   15 |   10 |    5 |    0 |      |      |       |
|  19 |  100 |   25 |   20 |   15 |   10 |    5 |    0 |      |      |      |       |
|  20 |  100 |   20 |   15 |   10 |    5 |    0 |      |      |      |      |       |
|  21 |  100 |   15 |   10 |    5 |    0 |      |      |      |      |      |       |
|  22 |  100 |   10 |    5 |    0 |      |      |      |      |      |      |       |
|  23 |  100 |    5 |    0 |      |      |      |      |      |      |      |       |
|  24 |  100 |    0 |      |      |      |      |      |      |      |      |       |
|  25 |  100 |      |      |      |      |      |      |      |      |      |       |

Anyway, the Str + Skill check PR is ready, I'm just waiting to see if my table is acceptable or not before pushing it to public.

**Comment by swwu** [comment]
@Rivet-the-Zombie Thanks! Real life keeps getting in the way of things but hopefully I get time to finish some stuff this time.

@Gabriel-SE The new numbers seem slightly high, but I haven't played much with technicians (nor do I know how often they use their special attack). I think maybe a higher penalty for low skill/str and a lower penalty for high skill/str would be reasonable, assuming that these guys are meant to be threatening midgame enemies. Also, 0 skill might not always cause you to drop your weapon if you happen to also be freakishly strong.

Something like:

| STR \ Skill | 0   | 1   | 2   | 3   | 4   | 5   | 6   | 7   | 8   | 9   | 10  |
|-------------|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| 4           | 100 | 100 | 100 | 100 | 100 | 100 | 100 | 100 | 100 | 100 | 100 |
| 5           | 100 | 100 | 94  | 88  | 82  | 76  | 70  | 64  | 58  | 52  | 46  |
| 6           | 100 | 94  | 88  | 82  | 76  | 70  | 64  | 58  | 52  | 46  | 40  |
| 7           | 94  | 88  | 82  | 76  | 70  | 64  | 58  | 52  | 46  | 40  | 34  |
| 8           | 88  | 82  | 76  | 70  | 64  | 58  | 52  | 46  | 40  | 34  | 28  |
| 9           | 82  | 76  | 70  | 64  | 58  | 52  | 46  | 40  | 34  | 28  | 22  |
| 10          | 76  | 70  | 64  | 58  | 52  | 46  | 40  | 34  | 28  | 22  | 16  |
| 11          | 70  | 64  | 58  | 52  | 46  | 40  | 34  | 28  | 22  | 16  | 10  |
| 12          | 64  | 58  | 52  | 46  | 40  | 34  | 28  | 22  | 16  | 10  | 4   |
| 13          | 58  | 52  | 46  | 40  | 34  | 28  | 22  | 16  | 10  | 4   | 0   |
| 14          | 52  | 46  | 40  | 34  | 28  | 22  | 16  | 10  | 4   | 0   | 0   |
| 15          | 46  | 40  | 34  | 28  | 22  | 16  | 10  | 4   | 0   | 0   | 0   |
| 16          | 40  | 34  | 28  | 22  | 16  | 10  | 4   | 0   | 0   | 0   | 0   |
| 17          | 34  | 28  | 22  | 16  | 10  | 4   | 0   | 0   | 0   | 0   | 0   |
| 18          | 28  | 22  | 16  | 10  | 4   | 0   | 0   | 0   | 0   | 0   | 0   |
| 19          | 22  | 16  | 10  | 4   | 0   | 0   | 0   | 0   | 0   | 0   | 0   |
| 20          | 16  | 10  | 4   | 0   | 0   | 0   | 0   | 0   | 0   | 0   | 0   |
| 21          | 10  | 4   | 0   | 0   | 0   | 0   | 0   | 0   | 0   | 0   | 0   |

Namely, it would take the form of `(136 - (str + skill) * 6)%`, obviously capping at 100%.

**Comment by KA101** [comment]
Some benchmarks: 8 is adult human average in a stat, with 14 being very good and any better indicating either world-class dedication to that stat (at the expense of other aspects of a "normal" life), or significant mutation/augmentation.  0 skill is marginal familiarity (seen it done, at most); 3 is trained or talented beginner; 5-7 is professional, 8 is expert, 9-10 world-class.

**Comment by kevingranade** [comment]
On the other side, why is it that technicians are amazing at taking your
weapon away when no other zombies can do it at all?

**Comment by swwu** [comment]
@KA101 I agree re: balance issues at 20+, even though there are some fairly reliable ways to get 20+ strength (CBM: hydraulic muscles, for instance). But there's no reason the system should stop making sense at those values, and I think this is actually a particularly interesting example of being able to counterplay - you might activate your hydraulic muscles when you see a tech so he can't take your weapon.

@kevingranade I have no idea; I assume there's some lore reason for them similar to shocker zombies' lightning attacks. Based on it only working on iron and steel weapons it seems to be magnetic?

**Comment by KA101** [comment]
>why is it that technicians are amazing at taking your weapon away when no other zombies can do it at all? / Based on it only working on iron and steel weapons it seems to be magnetic?

Yep, they've got the electromagnet aug.

And no, the system can still handle values larger than 20, sure--just that one shouldn't have a base stat above 20 (so you need some limited-use boost, like the hydraulic muscles or drugs, to get/stay that far up).

**Comment by Gabriel-SE** [comment]
@swwu
> Namely, it would take the form of (136 - (str + skill) * 6)%, obviously capping at 100%, and <= 4 str being an auto-drop.

With your table, I'd go with 
```c++
int success = 100;
if ( foe->str_cur > min_str ) {
    success = std::max(100 - (6 * (foe->str_cur - 6)) - (6 * wp_skill), 0);
}
```
because it's more tweakable. If later someone decides weapon skill value should give 10 decrement in success rate, it's as simple as replacing 6 * wp_skill with 10 * wp_skill.

I agree with swuu on the str issue. Someone as strong as hulk shouldn't have problem holding a sword tight even if he doesn't know how to use it efficiently.

I'll wait for more discussions but if no one has better idea, I'll push the PR tomorrow with swwu's table because Kevin said str / skill check was urgent.

**Comment by KA101** [comment]
If you can get the PR up, I'll merge it tonight.  I'll be out of town over the weekend and may not be able to merge as effectively as usual.
