### ISSUE TITLE
tec_dragon_grab technique is bugged?

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#10961]
This is the code:

 "type" : "technique",
"id" : "tec_dragon_grab",
"name" : "Dragon Snatch",
"min_unarmed" : 4,
"unarmed_allowed" : true,
"messages" : [
"You grab and knee %s!",
"<npcname> grabs and knees %s!"

Which doesn't do anything, it's just a normal attack. I believe it's missing the "down_dur" : 1, that exists in all the grab techniques

**Comment by KA101** [comment]
Or I decided that it doesn't knockdown.  Can look into giving it something else though.

**Comment by swwu** [comment]
Hm, weren't these grappling moves that we never properly added grappling components to because we hadn't added grappling yet? I vaguely remember discussion of a grappling system but I don't know if that ever got anywhere.

**Comment by KA101** [comment]
Yeah, movement-restricting grabs haven't happened.  Mostly they're a flavorful attack.
