### ISSUE TITLE
[Discuss] Optional json fields

### ISSUE THREAD

**Issue by bkentel** [CleverRaven/Cataclysm-DDA#10965]
Like I posted in the issue about save file size and what can be done about it, I mentioned not writing optional json values; values which have a well defined and sensible default value. I did some fiddling around to see what sort of interface I could offer to simplify things. It's merely a wrapper around some of the existing json framework, but it allows defining everything related to a json field in one location (function names and whatnot are not set in stone).

```cpp
// NAME  name of the field in a json object (a valid identifier)
// TYPE  the expected type (any primitive type)
// DEF_V the default value for missing fields; nullptr ~> required value
// MIN_V the minimum value to clamp values to; nullptr ~> no min
// MAX_V the maximum value to clamp values to; nullptr ~> no max
#define DEFINE_JSON_FIELD(NAME, TYPE, DEF_V, MIN_V, MAX_V)

// A similar interface for arrays
// Here Name is merely the typename generated.
// This interface I haven't implemented yet, but ought to be simple.
#define DEFINE_JSON_INDEX(NAME, TYPE, DEF_V, MIN_V, MAX_V)

namespace jid {
// an optional field called "name" with type string with a default value of "<noname>", and no min/max
DEFINE_JSON_FIELD(name, std::string, "<noname>", nullptr, nullptr);

// a optional field called "str_mod" with type int, a default value of 0, and no min/max
DEFINE_JSON_FIELD(str_mod, int, 0, nullptr, nullptr);

// a required field called "per_mod" with type double, and a range of [-10, 10]
DEFINE_JSON_FIELD(per_mod, double, nullptr, -10.0, 10.0);

// a required field called "int_mod" with type double, and a range of [-10, inf)
DEFINE_JSON_FIELD(int_mod, double, nullptr, -10.0, nullptr);
}

template <typename Field, typename Source, typename T = typename Field::type>
T get_json_value(Source &src);

template <typename Field, typename Dest, typename T = typename Field::type>
void set_json_value(Dest &dst, T const &value);

void foo() {
    JsonObject jo;

    auto a = get_json_value<jid::name>(jo);    //string "<noname>" if missing
    auto b = get_json_value<jid::str_mod>(jo); //int    0 if missing
    auto c = get_json_value<jid::per_mod>(jo); //double [-10, 10]; required
    auto d = get_json_value<jid::int_mod>(jo); //double [-10, inf); required

    JsonOut jout;
    
    // Write nothing if unchanged from the default value.
    jout.start_object();
    set_json_value<jid::name>(jout, a);
    set_json_value<jid::str_mod>(jout, b);
    set_json_value<jid::per_mod>(jout, c);
    set_json_value<jid::int_mod>(jout, d);
    jout.end_object();
    
    // Not yet implemented, but
    JsonArray ja;
    auto a0 = get_json_value<jid::arr_val>(ja, 0); //get from index 0
    
    jout.start_array();
    set_json_value<jid::arr_val>(jout, a0);
    jout.end_array();
}
```
The macro itself it quite simple; nothing magical. The real work is done with function overloading and templates. All very tiny.
```cpp
#define DEFINE_JSON_FIELD(NAME, TYPE, DEF_V, MIN_V, MAX_V)  \
struct NAME {                                               \
    using type = TYPE;                                      \
                                                            \
    static std::string const& id() noexcept {               \
        static std::string const result {#NAME};            \
        return result;                                      \
    }                                                       \
                                                            \
    static decltype(DEF_V) def() noexcept { return DEF_V; } \
    static decltype(MIN_V) min() noexcept { return MIN_V; } \
    static decltype(MAX_V) max() noexcept { return MAX_V; } \
}
```
Things like the `noexcept` could need tweaking, but this is mostly for exposition and getting opinions.

**Comment by narc0tiq** [comment]
That looks pretty readable to me; I don't speak C++ well enough to tell if it's idiomatic, but I can easily imagine so.

Two things that come to mind:
- you don't seem to mention JSON objects as values (things like `armor_data`, `book_data`, etc. come to mind; do they maybe not need anything special here?)
- I think it'd be better if the array interface were special (perhaps even including some specializations): 
  * it makes less sense to speak of minimum and maximum values for an array, and if that actually refers to min/max number of values, that should be explicit;
  * most of the arrays we use are fairly specialized, e.g. arrays of flags, or the fairly common array of key-value pairs used in recipes;
  * even disregarding the specializations, arrays are not directly a value type, and should stand out so that it's obvious they need to be iterated or something.

These are just thoughts, as I honestly haven't looked into Cataclysm's JSON stuff very deeply at all, but they might be useful to you.

**Comment by bkentel** [comment]
It wouldn't be used for arrays as a whole or more complex structures, just the basic fields or individual array elements. Anything more complex would be build on top of this like it is now. This would be a fairly minor change, but would consolidate and make explicit and consistent the various json field names, default values, and constraints.

**Comment by narc0tiq** [comment]
That works for me, then.

**Comment by kevingranade** [comment]
I don't find the wrapper to add value, it's extremely helpful to have all
the definitions for the json sterilization in one place, and this splits
off the type mapping so that it's not immediately visible.
I honestly don't think we have a big enough json schema to need to define
it formally, but if we do, we should skip this kind of thing and jump
straight to a formal schema. See jsonschema.org
Side note, I intensely dislike macros.  Projects that use them extensively
are some of the most unreadable code I've ever encountered.

**Comment by bkentel** [comment]
A formal schema is nice, but a bit heavyweight here, no?
Macros are something I try to avoid as well; here there isn't a way to offer a nice syntax without macros because of the rules for in class initializes. I'd love if it could be avoided, but I think there is room for tasteful and limited use of macros.

This wrapper would be the difference between the two below equivalent examples.

What we need now:
```cpp
static std::string const field_a {"field_a"};
static std::string const field_a_default {"default"};

static std::string const field_b {"field_b"};
constexpr int field_b_default = 10;

static std::string const field_c {"field_c"};
constexpr double field_c_default = 10.0;
constexpr double field_c_min = 0.0;
constexpr double field_c_max = 100.0;

static std::string const field_d {"field_d"}; //required

void read_from_json(JsonIn& jin) {
    JsonObject jo = jin.get_object();

    a = jo.get_string(field_a, field_a_default);
    b = jo.get_int(field_b, field_b_default);

    c = jo.get_float(field_c, field_c_default);
    if (c < field_c_min) {
        c = field_c_min;
        //print warning
    } else if (c > field_c_max) {
        c = field_c_max;
        //print warning
    }

    d = jo.get_string(field_d); //required
}

void write_to_json(JsonOut& jout) {
    jout.start_object();
    if (a != field_a_default) {
        jout.member(field_a, a);
    }

    if (b != field_b_default) {
        jout.member(field_b, b);
    }

    if (c != field_c_default) {
        jout.member(field_c, c);
    }

    jout.member(field_d); //required

    jout.end_object();
}
```

What this would allow:
```cpp
DEFINE_JSON_FIELD(field_a, std::string, "default", nullptr, nullptr);
DEFINE_JSON_FIELD(field_b, int,         10,        nullptr, nullptr);
DEFINE_JSON_FIELD(field_c, double,      10.0,      0.0,     100.0);
DEFINE_JSON_FIELD(field_d, std::string, nullptr,   nullptr, nullptr);

void read_from_json(JsonIn& jin) {
    JsonObject jo = jin.get_object();
    a = get_json_value<field_a>(jo);
    b = get_json_value<field_b>(jo);
    c = get_json_value<field_c>(jo);
    d = get_json_value<field_d>(jo);
}

void write_to_json(JsonOut& jout) {
    jout.start_object();

    set_json_value<field_a>(jout, a);
    set_json_value<field_a>(jout, b);
    set_json_value<field_a>(jout, c);
    set_json_value<field_a>(jout, d);

    jout.end_object();
}
```

**Comment by kevingranade** [comment]
No, the alternative without the wrapper is something like this:
```
void read_from_json(JsonIn& jin) {
    JsonObject jo = jin.get_object();

    jo.read( "field_a", a, "default" );
    jo.read( "field_b", b, 10 );
    jo.read( "field_c", c, 10.0, 0.0, 100.0 );
    jo.read( "field_d", d );
}

void write_to_json(JsonOut& jout) {
    jout.start_object();

    jout.member( "field_a", a, "default" );    
    jout.member( "field_b", b, 10 );
    jout.member( "field_c", c, 10.0 );
    jout.member( "field_d", d );

    jout.end_object();
}
```
You just supply the defaults to both read and write, the min/max is only needed on the read side since the game logic should be enforcing them as well.

**Comment by BevapDin** [comment]
I doubt the usefulness if min/max settings here for the serialize/deserialize part: The part should simply works as "what goes in, comes out exactly the same".

- Adding a range check here creates an obscure dependency on the usage of that data. Assume currently the value of `x` will always be positive, so one adds `min=0`. But someone slightly changes the meaning of `x` or just adds an alternative meaning when it's negative and suddenly a negative `x` is fine. The deserialization code does not know that and the developer who changed the meaning does not known about this dependency in the deserialization either.

- It doesn't replace a real validation with more and complex rules and it makes sense only for numbers, strings must be validated separately.

For loading world data (item type definition etc.): they don't need this system at all. Writing `new_thing->member1 = json.get_int( "x_member", 0 );` is completely fine. It contains all the connected parts in one line: the member name of the C++ class, the name of the json member it is loaded from, the type and the default value in one line. Applying the `jid` system there would only separate them, adding another step to find the connection between values in json and C++.

----

I'd like to inform about a different system (only used for serialization / deserialization):

Currently one has to add code for loading and separate code in a separate function for storing the data. That is redundant and leaves rooms for simple mistakes (the faction code had those: description would be stored in the member "description", but loaded from "desc").

I like the boost approach, it makes the process symmetrical by using the same function for loading and storing values. The (template) parameter to that function determines whether it loads or stores the members - it can either be an input archive or an output archive. This also avoids the redundant type declaration (the code known what type `member1` has).

One only has to implement a function `connect(Archive&)` (boost uses `operator&`), where `Archive` is a template (the function can be implemented in savegame_json.cpp, it does not need to be in a header, it will only be used with two actual Archive types and can be instantiated in that cpp file):
```C++
template<typename Archive>
void monster::connect(Archive &archive) {
    archive.connect("member1", member1);
    archive.connect("member2", member2);
    ...
}
```
The serialization library has input and output archive classes (`JsonIn` / `JsonOut` can be reuse) that implement the `connect` function differently. This assures that a value is always loaded from the same json member it has been stored into.
```C++
void OutputArchive::connect(std::string name, int v) {
    json.member(name, v);
}
void InputArchive::connect(std::string name, int &v) {
    json.read(name, v);
}
```

`connect` can be extended to support a default value.
```C++
    archive.connect("member1", member1, 10);

// connect can be implemented as simple template function,
// ready to be used for all the basic types
template<typename T>
void OutputArchive::connect(std::string name, const T &v, const T &def) {
    if(v != def) {
        json.member(name, v);
    }
}
template<typename T>
void InputArchive::connect(std::string name, T &v, T def) {
    if(!json.read(name, v)) {
        v = def;
    }
}
```
This approach is symmetrical and keeps the C++ member name, the json member name and the default value tightly together. And if you allow a simple macro, one can get away without any duplication at all:
```C++
#define ADD_TO_SERIALIZE_1(MEMBER) archive.connect(#MEMBER, MEMBER)
#define ADD_TO_SERIALIZE_2(MEMBER, DEF) archive.connect(#MEMBER, MEMBER, DEF)
template<typename Archive>
void monster::connect(Archive &archive) {
    ADD_TO_SERIALIZE_1(member1);
    ADD_TO_SERIALIZE_2(member2, 10);
    ...
}
```

Names of functions / macros / other identifiers are just suggestions and could probably be better.

**Comment by bkentel** [comment]
Along the same lines, there's also [cereal](http://uscilab.github.io/cereal/).

**Comment by kevingranade** [comment]
I'm a bit skeptical if min/max too, but wanted to give an apples/apples
code comparison.
I'd be happy with an archive interface for the json library, that looks
straightforward and elegant.
None of this needed for supporting optional arguments though, just add a
single optional parameter to the json read/write methods to establish a
default and apply it to various json entities.

**Comment by mugling** [comment]
See `assign` in `generic_factory.h` which provides default values, bounds checking and stricter parsing
