### ISSUE TITLE
Wildlife dont seem to care about zombies and vice versa [$25]

### ISSUE THREAD

**Issue by JimboJamerson** [CleverRaven/Cataclysm-DDA#1098]
it happens too much to me that ill be murdered by a bear or cougar in the middle of a huge swarm of zombies. Which doesnt make any sence cause the zombies should try to eat the bear if he is closer to me and the bear should want to kill the zombies for whatever reason he has against me, instead of it deftly weaving its way through hundreds of zombies to pour more hate upon me. Lets end this friendship pact between the animals and zombies.

**Comment by Coolthulhu** [comment]
Oh hey, there's a bounty on that.

I'm pretty sure my monster infighting system does that. Can I get the bounty?

**Comment by KA101** [comment]
Yep, you've ended the era of non-caring wildlife.  Critter factions aren't required for this one.  I vote this fulfilled.

Kevin, shall I photochop your face onto the Moneyman from UFO: Enemy Unknown?  :-)

**Comment by Rivet-the-Zombie** [comment]
Hooray! Congratulations, Coolthulhu!

**Comment by macrosblackd** [comment]
Grats Coolthulhu, this bounty stuff is pretty interesting :)

**Comment by kevingranade** [comment]
Congratulations!
Since the original set of PRs didn't reference this, make an empty PR that
claims to fix the issue (Fixes #blabla), and when it is merged the bounty
should be assigned to you.  I'll also poke at bountysource docs and see if
there's a more direct way to do it.

**Comment by KA101** [comment]
Just linked the original, FWIW.
