### ISSUE TITLE
failure to compile filesystem.cpp under cygwin

### ISSUE THREAD

**Issue by nulman** [CleverRaven/Cataclysm-DDA#10988]
src/filesystem.cpp:98:53: error: ‘rename’ was not declared in this scope

this seems to get fixed if i include \<cstdio>
i have no idea if it adds the right "rename" function

**Comment by dholmes215** [comment]
Adding stdio also fixed it for me.  Pretty sure it is correct.

**Comment by KA101** [comment]
This one should be fixed, at least.
