### ISSUE TITLE
free weapon blocks

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#10998]
If no weapon is wielded, or wielded weapon has no 'parry' technique. Character still does weapon blocks with the message:

You block a little of the damage with your !

**Comment by KA101** [comment]
At one level it makes sense to be able to at least try to get the weapon between you and the attack.  Other level, yeah, that's what the blocking abilities are for.

**Comment by aierce** [comment]
the block is missing the weapon name before the exclimation mark and block
happens for unarmed as well (not arm block)

**Comment by swwu** [comment]
I believe blocking techniques increase the blocked amount (from ~30% to ~50%? something like that), but blocks are still meant to happen normally (I could be wrong, it's been a while since I've looked at that code). This is probably just missing a special-case handler in the melee code.

**Comment by swwu** [comment]
Okay, just looked at it. This is something that happens if you can't limb block but you trigger a block anyways (which is possible because even without martial arts your `num_blocks` is at least one.

@aierce, were you using any martial arts when you triggered this?

**Comment by aierce** [comment]
i was using a martial art without any arm or leg blocks (tiger) and unarmed when this triggered

**Comment by aierce** [comment]
num_blocks is for creatures. blocks_left is for players. The problem is blocks_left is never defined anywhere.

I would like to add a line to melee.cpp something like if player has a blocking technique, set blocks_left to 1, otherwise set to 0.

The problem is martialarts.cpp also has a few lines that adds bonus_block to the value of blocks_left, and I don't know which file is run first, melee.cpp or martialarts.cpp. I don't want to override martialarts.cpp bonus blocks and break styles like karate

**Comment by swwu** [comment]
The relationship between blocks_left and num_blocks is the same as the
relationship between "current HP" and "max HP". At the beginning of every
turn blocks_left is set to num_blocks (when player::normalize or
player::reset are called, I don't remember which).


Steven

**Comment by aierce** [comment]
i know, i deleted that comment already, guess you are replaying in the email?
