### ISSUE TITLE
segfault on [e]xamine lighter under cygwin

### ISSUE THREAD

**Issue by nulman** [CleverRaven/Cataclysm-DDA#10991]
if i try to [e] a square with a lighter in it the game segfaults. im able to pick it up using advanced inventory.
if i drop a lighter i already have and try to examine that square, it also segfaults.
tried making a fresh world and several fresh characters, this always happens.

im playing version  0.B-2747-gf9ee723-dirty

**Comment by DavidKeaton** [comment]
Dirty builds denote local changes to source IIRC, is that the case here?

**Comment by nulman** [comment]
Yes, i have included cstdio in filesystem.cpp (look at my previous report for more info)

**Comment by i2amroy** [comment]
Latest version for me is working fine with said Cygwin fixes present. Can anyone else replicate this?

**Comment by KA101** [comment]
Just merged the cygwin fixes, so yeah.

**Comment by nulman** [comment]
great, it works!
