### ISSUE TITLE
Carved writing is not persistent

### ISSUE THREAD

**Issue by Mattamue** [CleverRaven/Cataclysm-DDA#10993]
1. Take a picture
2. Upload to SD card
3. Carve what the pic is on the SD card
4. Load pic onto e-ink tablet
5. SD card loses carved writing
##

**Comment by KA101** [comment]
Not sure if uploading the data removes it from the card (if so, that's likely an item change, so enough work to fix that I'd call it an Enhancement).  Otherwise, yeah, bug.

**Comment by Mattamue** [comment]
Spot on, the upload removes it. Guessing it gets replaced with a new blank item.

**Comment by ituluwituluwzev** [comment]
When you reinforce a CD, insert it into car stereo, and then get it back, it turns into an unreinforced one.

**Comment by Leland** [comment]
Closing due to lack of active discussion
