### ISSUE TITLE
Butchering rotten corpses creates "fresh" meat

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#11005]
Of course, it's still actually decayed, but only the first spoilable item in the list has the correct visible spoiling - be it nothing, "old", or "rotten". The rest will appear as "fresh" until they're picked up or world-rot function runs through them. Seems like some iterator is broken!

**Comment by Coolthulhu** [comment]
Some more details:
The freshly butchered stack will rot sequentially. The first turn after butchering, the first piece of meat will be rotten. The second piece will rot in the second turn and so on.

**Comment by narc0tiq** [comment]
Well, not necessarily. It's more that the pieces are processed at different
times, based on some randomness. Each piece presumably rots as soon as it
actually gets actively processed.

**Comment by kevingranade** [comment]
Oh, less that iteration is broken and more that the time delay I added for performance is visible here.
