### ISSUE TITLE
Butchering corpses broken

### ISSUE THREAD

**Issue by AlexTes** [CleverRaven/Cataclysm-DDA#11009]
This morning I updated from 56f7407 to e539b39. Standing over a corpse and pressing Butcher correctly lists the corpse for butchering. But upon pressing 'B' again, the game reports there is no corpse to butcher, and the corpse stays unbutchered.

(Don't take my word for the problem being between 56f7407 / e539b39, but it's likely, and surely a recent bug, if only because people butcher all day)

**Comment by KA101** [comment]
Confirmed in dev builds.

**Comment by KA101** [comment]
Got a fix for straight butchering.  Butcher-all is being recalcitrant and it's late, so that may or may not get fixed tonight.
