### ISSUE TITLE
Passive attack on / passively killing, a blob segfaults

### ISSUE THREAD

**Issue by AlexTes** [CleverRaven/Cataclysm-DDA#11011]
My situation while this is reproducible:
Have a rapier. 
Fencing technique. 
and I believe high enough skill to do the 'stop-trust' reactive attack.
Passively do it to a blob.
Segfault

**Comment by KA101** [comment]
Couldn't reproduce in dev with gdb attached.  Anyone else?

**Comment by AlexTes** [comment]
.. it's gone for me too. How strange.
I reproduced it 3 times to be sure. However trying it now, spawning in a blob it works fine.
Close it for now I guess. I'll try to make it happen again next time I visit a lab, attach my save if I get it reproducible again.
