### ISSUE TITLE
Constructed charcoal kiln can't be used for crafting clay items

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#11018]
Additionally, recipes don't use any fuel for it, and from context they seem to imply that the small kiln is placed over a fire.

What if brick kiln is renamed to "clay-firing kiln" and clay recipes start using it and fuel? (Also, why does it use up 20 charcoal per measly brick? Also, what about batch crafting also allowing to discount the tool charges to simulate parallel crafting, e.g. firing multiple bricks at once?)

P.S. Also, placing items in the furniture-kiln says "You put your %s in the empty charcoal kiln" regardless of whether it's actually empty or not.

**Comment by KA101** [comment]
Let's keep it to one "also" at a time please.  Most of these would probably be doable but involve inter-PR work, so are separate things from their origin PRs.
