### ISSUE TITLE
Fuel and fire bug

### ISSUE THREAD

**Issue by esavier** [CleverRaven/Cataclysm-DDA#11015]
I am only one who noticed that pouring gasoline into fire do... nothing? That means gasoline, diesel,  cooking oil (this is 100% not flammable sic!, despite that, with great success, it is used as diesel engine fuel in real world) some solid stuff and other stuff lacks some !!FUN!!. 

 Also some corpses are indestructible - that means there is no possibility to burn zombie corpses - they are keeps raising until butchered.
##

**Comment by Barhandar** [comment]
Poured gasoline served as a nice fuel for the fire last I checked. Presumably it's because fire checks for things on the ground instead of things that you've just dropped in, so just dropping will do nothing until it actually gets consumed.

To note, gasoline and diesel should be validly flammable. Probably not cooking oil, though.

**Comment by Rivet-the-Zombie** [comment]
Most cooking oil has to get really hot before it will burn (the smoke point) so it shouldn't burn unless the fire is already fairly intense.

**Comment by FireCrow1973** [comment]
So this is a little on the side but if you pore bleach in a puddle of ammonia, nothing happens aether.
Perhaps the 'poring stuff on the ground engine' needs some work?

**Comment by narc0tiq** [comment]
Considering one doesn't exist, perhaps so.

**Comment by Esavier** [comment]
hmm, actually you can pour gasoline on the ground and its flammable ( it is considered as able to ...ehmm... be... set on fire?) but its not acting as a fuel - 10k units of gasoline burns as small fire over few turns, same with other liquid fuels... shorter than one two-by-four wood plank.

btw cooking oil is almost exactly same as diesel, its flammable under same circumstances as raw oil, can be used fuel for diesel, can be mixed with methanol to make biodiesel, and is capable of providing almost  10KWhh (Kilo watt hours) from 1L.

**Comment by Night-Pryanik** [comment]
Discussion is stalled for years, so closing for now.
