### ISSUE TITLE
Placed Charcoal Forge eats charcoal

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#11021]
As reported by MormonPartyboat [here](http://smf.cataclysmdda.com/index.php?topic=9412.msg214174#msg214174), the built charcoal forge code (f_forge) sets the charcoal amount to what's placed, instead of adding it.

Apparent relevant code:

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iexamine.cpp#L2331
```
if (amount != 0) {
        item it(ammo->id, 0);
        it.charges = amount;
        m->add_item( examx, examy, it );
    }
```

**Comment by sprawl15** [comment]
MormonPartyboat here.  I did a bit more testing using the placed forge, and I found another quirk. There is no maximum for how much you can put into the forge - I was able to put ten million charcoal in at once.

Deconstruction seems to be WAI, it returns exactly as much charcoal as the forge thinks it contains.
