### ISSUE TITLE
Activating Power Armor

### ISSUE THREAD

**Issue by i2amroy** [CleverRaven/Cataclysm-DDA#11034]
Two things:
1) Power armor must be activated, but the 'a'ctivate option is currently red.
2) The Power armor interface bionic must be activated separately.

Suggested Fixes:
1) Make the activate option green (ideally check if they have a charged UPS or interface bionic present and toggle based on that).
2) Make the power armor interface bionic passive, same as a UPS is.
##

**Comment by kevingranade** [comment]
The reason it's still active is so people can use that as a toggle for
which power source to use.  The UPSs are considered similar enough that
it's kind of pointless, but bio power vs ups power have different uses.

**Comment by aierce** [comment]
there are actually 2 bionic source of power for power armor, unified power system (the bionic, not the item)  and the power armor interface. If you don't toggle on the power armor interface, powers will be drawn from the unified power system instead

**Comment by Griffinhart** [comment]
Honestly, if the player has all three of bio-UPS, PAI Mk1, and PAI Mk2, is there ever a reason they'd *want* to use the less-efficient power sources for power armor?

**Comment by kevingranade** [comment]
Yes, because they have tons of ups power but not much bionic power.

**Comment by Griffinhart** [comment]
Uh, I didn't say anything about UPS power. "bio-UPS" as in "the bionic that lets you run UPS-powered equipment without a UPS".

**Comment by i2amroy** [comment]
>The reason it's still active is so people can use that as a toggle for
which power source to use.  The UPSs are considered similar enough that
it's kind of pointless, but bio power vs ups power have different uses.

Fair enough. If we're going to keep it like that it would be nice to instead have the bionic automatically turn on/off if the player activates/deactivates the power armor without a UPS in their inventory. I can understand having the ability to determine between the two, but it seems kind of silly to be doubling the number of key presses for those who solely use bionic power when they don't have a UPS present.

**Comment by Griffinhart** [comment]
IIRC, power armor draws from inventory UPS over bio-UPS, and only uses bio-UPS if there are no powered inventory UPSes (and PAI isn't activated). (Which is in and of itself a different-but-related problem, in that a player can't carry any powered UPSes if they want to power PA with bio-UPS.)

Button presses is only problematic if the user wants to use PAI, since bio-UPS is a passive bionic.

**Comment by Leland** [comment]
Closing - discussion's stalled, and this topic is over 2 years old. Feel free to comment here if you still want it open, or make a new issue.
