### ISSUE TITLE
Knocked into smoke, decided against entering it

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#11044]
I was knocked by a brute into thin smoke, and was prompted to agree to enter it. I said no, and it complied.

**Comment by KA101** [comment]
So did that cancel the entire knockback, or only stop you early?

**Comment by Headjack** [comment]
It stopped me at the edge of the smoke.

**Comment by kevingranade** [comment]
I can't see how this can happen, and it didn't happen in a quick test with a smoker and a brute.

**Comment by kevingranade** [comment]
I'm going to close under the theory that headjack was moving away from the brute and the movement triggered after he landed.

**Comment by Headjack** [comment]
Can't rightly remember, though I feel I was closer to the smoke than that, given the distance brutes usually knock me. If it doesn't reproduce, then it was probably my mistake.
