### ISSUE TITLE
Hot air blocks display of fire/fire-bursts underground

### ISSUE THREAD

**Issue by KA101** [CleverRaven/Cataclysm-DDA#11046]
I imagine the same applies indoors and the issue is the hot-air not dispersing.  Thinking it's one of the infrastructure overhauls, but could well be wrong there.

Long story short, debug your way to a Strange Temple fire-burst hallway or set a fire in a triffid HQ (as reported here: http://smf.cataclysmdda.com/index.php?topic=9397.0 ) and marvel at how flames are briefly--if at all--visible before being covered back up.  (You can tell they're around thanks to the light they give off: leave the NV off for this one.)
##

**Comment by Shoes01** [comment]
I had made some changes to glyph drawing priority a long time ago, but I don't think it's related.

fd_fire_vent and fd_hot_air1 have a priority of -1, whereas fd_flame_burst has a priority of 4. A look at the addField and remField functions say that a new field is drawn if it has priority greater than or equal. It seems the vent can be covered up, but the burst should not. 

Hope that helps narrow down the source of the glitch.

**Comment by KA101** [comment]
Yeah, I'm wondering if somehow we made -1 an override or something.  *shrug*

**Comment by int-ua** [comment]
I've seen it previously but cannot reproduce now.
