### ISSUE TITLE
Quick Load

### ISSUE THREAD

**Issue by Gabriel-SE** [CleverRaven/Cataclysm-DDA#11055]
As contributor, there are plenty of situations where I must reload my save to get back to the initial state of debugging and a Quick Load hotkey will definitely help with that.
Make the Quick Load available in "List of all commands" if the game is compiled with "make DEV=1" so only developers have access to it.

Anyway, I'd like to hear other people's opinions before working on this issue since this topic is controversial.

**Comment by KA101** [comment]
IME on windows, closing the window and relaunching is quick enough.

**Comment by kevingranade** [comment]
I'm fine with it being in debug (non RELEASE=1) builds.  I'm not sure how
invasive it's going to be though, do you have the implementation planned
out, or just the idea?

**Comment by Gabriel-SE** [comment]
Just the idea I guess, I can't say much without looking at the source code first.
But if the implementation is too invasive or requires many hacks to the source code I won't push this change.

**Comment by bkentel** [comment]
You would have the hotkey function from the opening screen? Or would it be better as a command line parameter?

**Comment by narc0tiq** [comment]
I understood it as an in-game hotkey at the same level as quicksave. You
can see how that would be a bit cheaty for release builds, but if you're
trying to reproduce a bug...

**Comment by Gabriel-SE** [comment]
@bkentel 
> You would have the hotkey function from the opening screen? 

I usually load the same world and player name, hence the Quick Load name. It's the counterpart of Quick Save.
But another dev hotkey to load > World Name > Player Name function will be better as different name, "Load" maybe.

> Or would it be better as a command line parameter?

Command line parameter to load existing world will be nice, something like ./cataclysm --world world_name --name name
main.cpp has some sort of map sharing command line, but I'm not sure if it can be used to load existing world instantly without investigating it first.

@narc0tiq 
>I understood it as an in-game hotkey at the same level as quicksave.

Yeah, this is correct.

@kevingranade 
>I'm fine with it being in debug (non RELEASE=1) builds.

Debug build is kinda slow for me to compile, 3-4x slower than the speed of release build, so I want this on my release build but Quick Load definitely won't appear in RELEASE build of the bot.
It will only appear on _GLIBCXX_DEBUG (default debug mode) or when they compile the game with DEV=1.

**Comment by kevingranade** [comment]
It's specifically _GLIBCXX_DEBUG that makes debug builds slow, try removing it.
