### ISSUE TITLE
Change how recipes are specified in JSON

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#11052]
For a while now I've been bothered by the current setup for specifying recipes, so here's an alternative proposal @Barhandar and I have been twisting every which way:

``` JSON
{
    "type" : "recipe",
    [...]

    "recipe":
        { "all_of": [
                { "quality": "CUT" },
                { "quality": "COOK", "level": 2 },
                { "any_of": [
                        { "tool": "hotplate", "charges": 10 },
                        { "tool": "char_smoker", "charges": 1 },
                        { "all_of": [
                                { "tool": "toolset", "charges": 10 },
                                { "component": "skewer", "amount": 2 }
                            ]
                        },
                        { "all_of": [
                                { "tool": "fire" },
                                { "component": "skewer", "amount": 2 }
                            ]
                        }
                    ]
                }
                { "component": "hotdogs_frozen" },
                { "component": "chili" }
                { "any_of": [
                        { "component": "bread", "amount": 4 },
                        { "component": "hardtack", "amount": 8 }
                    ]
                },
                { "reagent": "spicy_hot", "amount": 4 }
            ]
        }
}
```

The above is a slightly modified recipe for chili dogs:
- skewers are required (for some reason) when cooking it using integrated toolset or a nearby fire
- the proposed reagent system (see #11051) is used instead of explicit references to condiments

Here's a break down of what the different pieces would be (and their defaults):
- `{ "quality": "NAME_OF_QUALITY", "level": 1, "amount": 1 }`
- `{ "tool": "item_id", "charges": -1 }`
- `{ "component": "item_id", "amount": 1 }`
- `{ "any_of": [ ... ] }`
- `{ "all_of": [ ... ] }`

where the `[ ... ]` arrays can be filled with any number of any of the pieces.

It looks... pretty okay to me, but I'd like more people's thoughts and/or refinements. Also questions.
##

**Comment by Barhandar** [comment]
The first level could probably have the all_of designation implicit, since it's VEEERY unlikely it'd be used, and even then it would be explicit any_of. Like so:
```
    "recipe":
        { { "quality": "CUT" },
            [...]
            { "any_of": [ [...] ] }
        }
```

```
    "recipe":
        { "any_of": [
                { "component": "leather_patch", "amount": 6 },
                { "component": "tanned_hide", "amount": 1 }
            ]
        }
```

**Comment by narc0tiq** [comment]
It doesn't really make enough of a difference, and I'm inclined to keep from having too many exceptions (implicit default values are already a thing we have, but an implicit object is unusual).

---

Semi-relatedly (I'll edit this into the OP, too), let's break down what the different pieces are (and what their defaults are):

- `{ "quality": "NAME_OF_QUALITY", "level": 1, "amount": 1 }`
- `{ "tool": "item_id", "charges": -1 }`
- `{ "component": "item_id", "amount": 1 }`
- `{ "any_of": [ ... ] }`
- `{ "all_of": [ ... ] }`

where the `[ ... ]` arrays can be filled with any number of any of the pieces.

**Comment by vache** [comment]
I like this.  Would it be possible to use the "all_of" or "any_of" type in other jsons outside of recipes?  I could see it being used in mapgen for a store having an items placement saying "any_of":[ "ladies_clothing_store_items", "mens_clothing_store_items", "childrens_clothing_store_items", ... ]

**Comment by BevapDin** [comment]
You can do something similar with items groups (used during the normal mapgen):

An item group can be a distribution or a collection: In a Collection each entry is chosen independently from the other entries. A Distribution is a weighted list (the default), exactly one entry is chosen from it.

See doc/ITEM_SPAWN.md for documentation or data/json/mapgen/abandoned01.json for an example.

Reusing the recipe system for item spawn seems not very good, it does not contain any chance values.

**Comment by vache** [comment]
Not necessarily for item spawns, but for selecting a group of items from a set of groups and working from there.  Basically, to create a generic shop, then fill the shelves based on whatever item group gets selected.

**Comment by kevingranade** [comment]
One thing for implementing this if it happens, version the recipe somehow
so we can convert the recipes piecemeal, I'm not landing a gigantic
auto-conversion of every recipe :)

**Comment by Barhandar** [comment]
>One thing for implementing this if it happens, version the recipe somehow so we can convert the recipes piecemeal, I'm not landing a gigantic auto-conversion of every recipe :)

That was the idea, yes, so they can be changed one by one and for the mods that aren't in here yet to remain compatible.

**Comment by narc0tiq** [comment]
Yeah, absolutely. Thankfully, the format is different enough that you can
just go "does this have a 'recipe' member? No? Okay, then it's the
old-style recipe type."

**Comment by narc0tiq** [comment]
To keep the discussion here going, and seeing as how the JSON part seems fine, I have a big concern that I'm not sure how to fix: UI. Namely, how to display to the player the tree of possible components, tools, and qualities which could occur at pretty much any depth. I don't think anyone wants their recipes resembling a small Lisp program.

To be fair, I'm already somewhat bothered by the recipe display for other reasons (primary vs. secondary skills), but this seems like it could be all that much worse. Yay, go, me.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
