### ISSUE TITLE
Diamond bayonet(s) autolearn at Fab 1, diamond weapons unobtainable until Fab 10

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#11060]
So from the nearly-beginning and until the near-end they dangle in crafting list, being completely useless. I propose either making the recipe be in the same book as diamond weapons and not autolearn, or switching it to diamonding actual bayonets and not just tying diamond weapons to your guns. (The issue is there because IRC disagreed on how to fix it. The easiest would to bump them to 9 fabrication.)

Also, judging by normal bayonet recipes being identical except for the weapon, they're copypasta.

**Comment by Dozed12** [comment]
This should be fixed: #11355
