### ISSUE TITLE
A feature request: Are you sure? That could take up to x turns!

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#11076]
Coming from a run that ended because I tried throwing a metal tank full of gas at a bee not realizing that throwing now respects speed, I'd like to request a feature. 
Not sure how you'd implement it, but it'd be nice if there were an option to (or I guess if it were default) enable a turn safety. 

The safety would show up if there's an attack or throw action you're going to take when there's an agro monster in view, but the attack or throw action could take more than a few turns. This way you don't stupid your run away standing there for 24 turns doing silly things like throwing metal tanks at enemies or whacking zombies with zombie corpses (unless you really want to I guess, then flip the turn safety off or don't turn it on in the first place).

**Comment by nulman** [comment]
I feel your pain then again, now you know better :)

**Comment by KA101** [comment]
Folks get annoyed at the Y/N already, so I'm thinking no on this one.

**Comment by kevingranade** [comment]
Agreed, we need less prompts, not more.
A possible solution would be enhancing the action menu such that it shows you how many turns it takes to take an action, or even the throw menu for that matter.
