### ISSUE TITLE
Some strong painkillers are working not enough fast

### ISSUE THREAD

**Issue by BFG1992** [CleverRaven/Cataclysm-DDA#11072]
~~It seems that painkillers are now broken again on latest builds :(~~
I was wandering on some minefield, stepped on mine and got almost broken torso and pain level at 117. I've got back into my trusty RaVager (heavily modified RV) and shoot up some morphine. Waited a few turns... still 117. Took some codeine to make sure - and yep, 117 again. Then I patched myself up with some first aid kits - and pain began to fall. Sloooooowly. And then I saw a bear in the woods and decided to take some vodka - pain dropped down to 83 (from 94 or smth).
So, the alcohol working as a painkiller, but only alcohol. ~~Other painkillers are broken.~~ That problem exists for some time (I remember myself playing a two or three weeks ago getting same trouble with now-useless painkillers). I'm currently playing build 27471a4.

**UPD:** It revealed, that painkillers do work, but in a more realistic way, much slower than they were before. But strong enough drugs like heroin and morphin should work faster, as they do in reality. So I think it would be right to fix 'em :)

**Comment by Midaychi** [comment]
Using the same build and found that aspirin didn't seem to do much either; only the natural reduction of pain over time.

**Comment by Midaychi** [comment]
Actually now that i've gotten hurt a lot more and tested painkillers, it seems like they DO work now, but they take a lot longer to take effect and are more gradual than they used to be.

**Comment by KA101** [comment]
So first-aid's more immediate effect might be either a bug (still kicks in fast) or confounded (there's fast-time whilst you're applying the kit, so depending on when the painkiller gets administered, it may have taken effect/pain naturally decreased).

In either event, sounds like this one's closable.  Can reopen if needed.

**Comment by BFG1992** [comment]
Point taken.
But, actually, I think that powerful stuff like morphin should work much faster (and morphin is administered right in bloodstream), so I think it needs to be fixed.
And another one... If this change of how do painkillers work (according to what I read there, it was, but I missed it, my bad) is to make it more realistic, so how about adding a "Painkillers" effect in "Effects" field, so player would know that painkiller he take actually begins to work?

Anyway, I think I need to retest it again, more carefully and possibly with screenshots, and post here results (if they will prove anything) :)

**Comment by KA101** [comment]
Morphine should be fairly quick, same with heroin, I'd imagine.  If those are the issue, sure.

**Comment by BFG1992** [comment]
Hmm... should I change the title and the description a bit then?

**Comment by KA101** [comment]
Feel free.

**Comment by BFG1992** [comment]
Done.

**Comment by mugling** [comment]
Discussion concerning balance of medications continues in #16017
