### ISSUE TITLE
1 vehicle related bug and 1 vehicle related (feature?)

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#11073]
While messing with a pretty recent version 27471a4 , using a couple of mods including the vehicle addon mod and boats, the first part I found that you can get a vehicle to get stuck at -9 speed, and the second part I also found how to make a generator bike.

I found that by attaching a truck and car alternator to a foot crack on a vehicle with enough wheels, attempting to drive the vehicle would just cause it to get stuck at -9 mp/h and be unable to stop or move the vehicle forward. I noticed that power was being generated though, so I tried weighing it down.

I attached a minifridge and a kitchen unit to it, extra batteries, and weighed the minifridge down with stuff. I found that cruisecontrol fixed itself and let you set a speed again, but the vehicle was stuck in place due to too much weight. However, as long as you were holding the controls and cruise control was set to max, the bike would generate power through the alternators at a decent pace.

I am able to craft while 'pedaling' this stationary bike and generate enough electricity for the minifridge and the kitchen unit + extra.

https://www.dropbox.com/s/7j7k1kf0duja1wk/American%20Fork.zip?dl=0

**Comment by KA101** [comment]
Generator bike is intended.

**Comment by Midaychi** [comment]
I figured as much, but the first one is a bug right? You'd have to remove the minifridge/kitchen thing and the junk from storage to unweigh it so it starts doing it again in the save. If you take control it goes to -9 mph and moves away backwards, can't set it to 0 mph or forward at all.

**Comment by KA101** [comment]
Probably is, yeah.  Not sure how you'd jam it in reverse anyway.
