### ISSUE TITLE
Stereo system destroying CDs when vehicle batteries are dead

### ISSUE THREAD

**Issue by BFG1992** [CleverRaven/Cataclysm-DDA#11083]
Just as the title says.
Steps to reproduce:
1. Turn stereo on;
2. Leave controls (maybe not necessary);
3. Let the vehicle batteries die.
Result: your music CD is gone.

**Comment by narc0tiq** [comment]
I was sure this one had already been reported, but now I can't find it.
Yep, needs to be fixed.

**Comment by nulman** [comment]
It would be great if the fix just made the stereo capable of holding a cd without being on. (It gets annoying having to keep poping it in and out)

**Comment by BFG1992** [comment]
**nulman** +1!
I think that's a great idea :)
But if it means adding yet another string in the controls menu (like "Insert/Eject CD") it might not be good...

**Comment by Coolthulhu** [comment]
How about just removing the CDs altogether? They're a bit of an ancient tech even today.

**Comment by Barhandar** [comment]
>How about just removing the CDs altogether? They're a bit of an ancient tech even today.

Quite a bit of cars now run with *casettes*. If something like Germany's "give up your car and receive a modern one free of charge" didn't happen in CataUSA, there still will be cars with CD stereos. Though most will be using flash drives, likely.

**Comment by illi-kun** [comment]
CDs were removed in #12237, so let's close this issue.
