### ISSUE TITLE
Remove Y/N prompt for clearing rubble?

### ISSUE THREAD

**Issue by AllisonBW** [CleverRaven/Cataclysm-DDA#11099]
...and similar things, like ash, from iexamine.cpp. It'd *massively* reduce the keystrokes required to clear large piles of rubble, ash, and wreckage, considerably improving quality of life with regards to doing these things. If I were brave enough to play with hardcode yet I'd do it myself and PR it.

**Comment by Snaaty** [comment]
How about a general option that allows for disabling specific Y/N prompts? Like, when the prompt pops up in the top right corner theres a "press x to prevent this query from appearing again". 
I guess this is also relevant for shrubs where the query got removed, but people complained that they can't check for items in shrubs with 'e' without searching for mushrooms.

**Comment by DavidKeaton** [comment]
Disabling them totally seems like a bad time. Instead, a turn counter or so should be used.

**Comment by vache** [comment]
How about if instead of having examining the terrain be used to clear it if you have a shovel, you activate a shovel to clear it?

**Comment by kevingranade** [comment]
Alternately move the examine stuff that does things to a new hotkey with no Y/N prompt and just leave examine as examine, not "interact with".

**Comment by Zireael07** [comment]
I like Snaaty's idea.

**Comment by AllisonBW** [comment]
I could see Snaaty's idea working, particularly if it's easy to switch the option on when you're about to take on a big wreckage-clearing/foraging job and then turn it off afterwards. Or Kevin's. Kevin's idea would also fix the issue with people who want to grab an item on an underbrush tile without foraging.

**Comment by kevingranade** [comment]
Yes shifting it to a new keybinding would be painful for a while, perhaps
have it print a message that it's deprecated and to use the new command for
a release or so?
This is a problem that's been looming for a while now, and it's not just
about the prompts.  As we add more and more things to examine functions,
there start to be collisions all over the place (such as the forage/pickup
issue).  I'm not super happy about the solution either, would love to hear
alternatives.

**Comment by vache** [comment]
Picking up items could be moved to pick up->select direction->list items, with another hotkey to pick up items here.  It doesn't really make things more efficient because you're moving keypresses from one area to another, but it combines related actions a little better.  Also, I think in the general case that having it prompt you to use an item on a location is a similar problem, it combines using things in your inventory with examining/interacting, and you should just activate the item on the location instead.

**Comment by bookofguns** [comment]
One really long and really annoying way about doing things is to create a list in options to let the player decide which interactions will cause the Y/N prompt to pop up or will automatically trigger Y upon examination of the location or object. Currently though I don't know how options look in the code and don't know if this could happen sort of new here.

**Comment by Rivet-the-Zombie** [comment]
Here's an idea: What if the prompt said something to the effect of ````Clear rubble? Y/N Press S to affirmatively suppress future queries of this sort.```` where pressing S would cause the query to automatically be confirmed until the game is reloaded.

**Comment by narc0tiq** [comment]
Y/N/A -- Yes/No/Always.

Honestly, I'd rather have separate examine and interact keys. The different
kinds of lookaround could probably be streamlined, as well.

**Comment by DanmakuDan** [comment]
#11554 applies the update for this.
