### ISSUE TITLE
Unusual loot drops

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#11090]
Solved, nevermind first part.

On the topic of drops, brick kilns and cement mixers are showing up abnormally much on regular walkers, when they probably shouldn't be drop items at all. Probably aluminum kegs, too, are too bulky to imagine a zed carrying
##

**Comment by KA101** [comment]
Pretty sure zeds pull from other item_groups rather than having a specific drop list, so I'm not too worried about this one.

**Comment by Leland** [comment]
Discussion's been stalled on this one for over 2 years now. Closing. If anyone still has an interest in this, free to let me know here that you want it reopened; or just create a new issue.
