### ISSUE TITLE
Hallucinations kill zombie slaves

### ISSUE THREAD

**Issue by ValidAQ** [CleverRaven/Cataclysm-DDA#11100]
0.B-2687-289e460 Curses 
Windows 7 x86
After making a zombie slave out of feral hunter, I noticed that sometimes it would die for no apparent reason while tied up in another room. Turns out that when the character is hallucinating, appearing hallucinations of monsters can and will attack zombie slaves, causing damage.
The logs from one of these events read:
```
"The charred nightmare hits the feral hunter!"
"The feral hunter dies!"
"You block none of the damage with your !"
"The charred nightmare hits your left arm."
"You whack the charred nightmare for 21 damage. Critical!"
"The charred nightmare disappears."
```
I'm not sure if this occurs with unrestrained slaves as well, but it definetly happens if they are tied up.
Also, note the odd message about blocking damage. I was unarmed at the time. 
Finally, a question. When a tied up zombie slave dies, the rope that was restraining it disappears. Was it supposed to work this way or is it a bug?

**Comment by KA101** [comment]
Hallucination causing damage and the loss of rope are both bugs.  Thought we fixed the blocking message, but I guess not.

**Comment by ValidAQ** [comment]
So, the damage thing was caused by `monster::hit_monster` not checking whether attacker is hallucination before applying damage. I'll submit a pull request soon.
How should the rope issue be handled? By actually adding a rope to slave's inventory or through `"tied"`effect?

**Comment by KA101** [comment]
>How should the rope issue be handled? By actually adding a rope to slave's inventory or through "tied"effect?

Exactly what you said, I'd imagine: if the critter dies whilst under the "tied" effect, add a rope to its inventory.
