### ISSUE TITLE
WTB: Carryable non-backpackable items, aka buckets

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#11125]
Buckets are a fairly common container for various liquids in real life, but they make no appearances in Cataclysm due to being a fairly useless thing to have -- being non-sealable means they either couldn't be carryable when full, or would allow you to have literal buckets of water in your backpack. A related issue already occurs with things like lit charcoal furnaces, which you _can_ carry around in your backpack despite being presumably quite hot and possibly dangerous.

A proposed solution would be to have one or two flags that would allow us to say that _an item may be carried in one's hands, **but not in one's main inventory**_, optionally only when the item has liquid contents. This would also allow us to use tin cans and aluminum cans as impromptu water buckets, because who doesn't want to carry their water to the fire for boiling one charge at a time?

Of special note: cardboard boxes probably shouldn't be able to carry water. Just saying.

**Comment by Headjack** [comment]
If you're doing this, maybe make it so containers of liquids can be boiled as-is. IE, jar of water to car of clean water, when you have no other containers. (glass jars should probably also have Boiling 1)

**Comment by Barhandar** [comment]
>(glass jars should probably also have Boiling 1)

And take damage with each crafting operation. Glass doesn't really like being heated by flames, you need a heat spreader (a large plate with lots of small holes) to use them.
>If you're doing this, maybe make it so containers of liquids can be boiled as-is. IE, jar of water to jar of clean water, when you have no other containers.
#171

**Comment by i2amroy** [comment]
>If you're doing this, maybe make it so containers of liquids can be boiled as-is. IE, jar of water to jar of clean water, when you have no other containers.

Yeah, that's a totally different chunk of the code and is quite a bit more serious to try to implement.
