### ISSUE TITLE
Control laptop could 'copy' files

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#11132]
The control laptop uses HackPro software off a USB as a component, which makes sense, but it should really use it as a tool, since you would be smart to just copy the files in case you have to make another one later. I'd submit this, but really don't understand Git that well :/ .

**Comment by KA101** [comment]
Fair enough, since hackers probably wouldn't bug the soft to delete itself after copying.

**Comment by DavidKeaton** [comment]
I guess there'd be no need to hide those 0day b0fs anymore. ;-)
