### ISSUE TITLE
Active zeds probably shouldn't spawn at roadblocks/outposts

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#11131]
I'm noticing some incongruities. For example, military turrets are shooting zombie soldiers and bio operators. Same for turrets at roadblocks and the cops. I bet lab turrets shoot scientists too.  Fungal zombies are fighting regulars and vice versa, when probably they wouldn't realize any difference. And everybody goes after spore clouds, when they seem like they should be ignored.
##

**Comment by Headjack** [comment]
Dermatiks are fighting giant mosqitoes and other swamp bugs, and giant frogs are in there too. Some of that makes sense, the mosquitoes would need to bite the frogs on occasion to get enough blood, but they shouldnt always be at war. Maybe occasionally they track and attack?

**Comment by KA101** [comment]
Uh, no, just because turrets are targeting critters as well as the player doesn't magically undo the fact that they turned on their programmers.  I even designed roadblocks (before this rework) with the assumption that the turrets shot the staff crewing 'em.

Sheesh!

**Comment by Headjack** [comment]
Well it is at least a little strange that this always waits to happen until you're around. Maybe there shouldn't be active zombies spawned in those areas anymore, just corpses that can rise when you get close enough? The swamp fighting is still sort of over-the-top, littering the area with corpses whenever the species clash.

**Comment by KA101** [comment]
>no active zeds

Sure, that's doable.
