### ISSUE TITLE
to close an open crate message

### ISSUE THREAD

**Issue by lifelike** [CleverRaven/Cataclysm-DDA#11142]
I built an open crate. Not sure what they are for, but since it was described as being "open" I tried to close it and got the less than helpful reply "There's an open crate in the way!". Now I think it was an user error to try to close the crate, realizing now that I should have used the construction to seal it, but the message could have told me that or at least say something more intelligent.

**Comment by lifelike** [comment]
version 0.B-2997-g621b063

**Comment by KA101** [comment]
Concur, much like applying a shovel.

**Comment by BevapDin** [comment]
Fixed by #11664.
