### ISSUE TITLE
Using B to "butcher" some clothes disassembles them instead (taking time)

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#11162]
As said, it defaults to pulling it apart with your hands rather than using a knife if you have one, resulting in ludicrously long periods spent dissecting a blanket or some cargo pants. Only certain items do this. Point is, clothes should probably default to being cut up rather than pulled apart so long as you've got a knife.

**Comment by Barhandar** [comment]
Strange, because it defaults to cutting them up for me (in most cases, that is: if there's long string, for example, it's disassembled, not cut up).

**Comment by ejseto** [comment]
Disassembly is always the default if you have the tools (i.e. charged sewing kit).

**Comment by Headjack** [comment]
It's only some things, try it on a blanket or cargo pants that are on the floor.

**Comment by ejseto** [comment]
You could always just unload your sewing kit until you need it.

**Comment by Barhandar** [comment]
>It's only some things, try it on a blanket or cargo pants that are on the floor.

B -> 1. The menu rather explicitly states it's disassembly, and cut up is the different-key options.

**Comment by Headjack** [comment]
Well my main point is that the default should probably be cut-up, since there's really no benefit to dissembling textiles unless you have no knife.

**Comment by ejseto** [comment]
How is there no benefit? I just crafted a blanket which took 35 rags and cut it up and only received 9. Preserving nearly 75% of the materials is not a benefit? The butchery menu also doesn't discern between clothes and other types of items. You might not consider the loss of a few rags of any note, but disassembling electronics and receiving only plastic chunks might be a different story. If you don't like having the disassembly of clothes appear before the salvaging of clothes, the solution is quite simple: don't carry a loaded sewing kit.

**Comment by KA101** [comment]
Recategorized as the time v. efficiency issue bears discussion.

**Comment by narc0tiq** [comment]
The fact that only _some_ clothing recipes have disassembly enabled always struck me as a bug. There's no rhyme or reason to it as far as I can tell. Either (almost) all of them should be reversible, or (almost) none should.

Beyond that, salvage being lossy is actually a point in its favor, and rags aren't terribly rare. So as far as clothing is concerned, I fully support making salvage the only way to break them down (obvious exception: rags to string; I don't care how good you are with a pair of scissors, you can't make strings that way).

For everything else, disassembly is much preferable, so the existing order (disassembly recipes first) is already correct.

**Comment by Barhandar** [comment]
>So as far as clothing is concerned, I fully support making salvage the only way to break them down (obvious exception: rags to string; I don't care how good you are with a pair of scissors, you can't make strings that way)

Sheets should be disassemblable by hand, same for bolts of cloth if these get added sometime - you only need the initial cut to tear most of these apart by hand and anything even remotely sharp would suffice, and it's much faster than using a knife or a scissor all the way. For other clothes, disassembly vs. cut-up is presumably "cut the seams vs. randomly slash at it until it comes apart", and so can be just simplified into the "cut at the seams" part, e.g. cutup.

**Comment by narc0tiq** [comment]
To the best of my knowledge, disassembly of clothing is somehow "sewing the item apart", including consuming sewing kit charges. That may have changed since the last time I tried it, though.

**Comment by KA101** [comment]
If disassembly of clothing consumes sewing charges, that's a bug.
