### ISSUE TITLE
Disentangle checking for interruptions from drawing.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#11178]
As encountered in #10970 triggering a screen refresh triggers a check for interruptions such as nearby monsters which can cause the current activity to be invalidated while its being processed.
Checking for interruptions should not be tied to drawing logic, because we should be able to trigger a redraw for purely UI reasons without having any in-game effects.
##

**Comment by anothersimulacrum** [comment]
Note: This prevents safe mode from functioning at all when the compass panel is disabled.

**Comment by I-am-Erk** [comment]
Snup states that this doesn't appear to be the case anymore as of some time prior to #54672 - let me know if I am wrong to reopen.
