### ISSUE TITLE
Slowish debug builds

### ISSUE THREAD

**Issue by bkentel** [CleverRaven/Cataclysm-DDA#11180]
Since the slowish debug builds have been hindering my productivity, I did some profiling along the hot path and managed to find a few places to make some significant improvements (up to 100% better in a few places).

Over the next week I plan to submit the changes as a small series of smaller PRs for review. The changes are in general not drastic; mostly trying to access data in a more cache friendly way.

The relative timings (sampling) can be seen below to the right in each image; before and then after. You can see the time spent shift away from a few high profile paths into the various other (unmodified) paths indicating a good improvement.

![cata_tweak_before](https://cloud.githubusercontent.com/assets/780369/6096881/83481e54-afea-11e4-89bd-cf8630c1c5d4.png)

![cata_tweak_after](https://cloud.githubusercontent.com/assets/780369/6096883/8a43b25e-afea-11e4-9290-c6d2d3712122.png)

**Comment by kevingranade** [comment]
Is this with or without _GLIBXX_DEBUG defined?  If that is defined it renders pretty much any profiling pointless as it increases the overhead of std container operations by orders of magnitude.

**Comment by bkentel** [comment]
Yes debug iterators are off, and these handful of changes aren't actually strongly tied to container operations at all anyway, but rather (1) the way that the submap arrays are accessed, (2) adding one new int variable to submap to avoid having to traverse item stacks during lightmap calculation for the common case, (3) being more careful with memory allocations in a few tight loops.

**Comment by kevingranade** [comment]
All the PRs are filed, and can stand on their own.
