### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Gabriel-SE** [CleverRaven/Cataclysm-DDA#11205]
Game always crash every time I load existing character or when I create a new world and new character after "Are you SURE you're finished? Your name will be randomly generated."

Setting : Software rendering = True, Linux build.
I tried with tiles and curses version, both version crashed.

```
Program received signal SIGSEGV, Segmentation fault.
0x086b14a1 in map::generate_lightmap (this=0xb7a020b4) at src/lightmap.cpp:96
96                  if (get_submap_at(sx, sy, lx, ly)->lum[lx][ly]) {

bt
#0  0x086b14a1 in map::generate_lightmap (this=0xb7a020b4) at src/lightmap.cpp:96
#1  0x0870767e in map::build_map_cache (this=0xb7a020b4) at src/map.cpp:5268
#2  0x083e7eac in game::draw_ter (this=0xb7a02008, posx=61, posy=62, looking=false) at src/game.cpp:5081
#3  0x083e4632 in game::draw_ter (this=0xb7a02008, posx=-999, posy=-999) at src/game.cpp:5064
#4  0x083929f8 in game::draw (this=0xb7a02008) at src/game.cpp:4909
#5  0x08390936 in game::do_turn (this=0xb7a02008) at src/game.cpp:1417
#6  0x086bfa58 in main (argc=0, argv=0xbffff098) at src/main.cpp:295
```

Game worked fine before I integrated this week's PR into my local master branch.
It's probably related to this PR :

https://github.com/CleverRaven/Cataclysm-DDA/pull/11185

**Comment by KA101** [comment]
We *just* merged a PR touching that issue, I believe: mind upgrading and letting us know?

**Comment by narc0tiq** [comment]
I had this when building with clang++, as per the comments on the linked
issue. #11201 fixed it for me, possibly combined with upgrading to
clang-3.5. Please do give it a try.

**Comment by Gabriel-SE** [comment]
Yeah, I don't have the crash problem anymore now.
