### ISSUE TITLE
Tough feet vs other foot mutations

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#11221]
Foot mutations generally forbid wearing footwear, but don't always remove the speed penalty for no footwear.

While it kinda makes sense for foot talon (it is both realistic and balanced), pretty sure leg tentacles (which already cause a separate penalty) should not require nor benefit from XL boots nor tough feet.

Tough feet also doesn't conflict with padded feet, hooves and ROOTS2, all of which negate the shoeless penalty.

Other than mutants with weird feet, tough feet is generally a useless trait.

**Comment by KA101** [comment]
FWIW I've thought Hooves should negate the speed penalty, but then that's me.

**Comment by Coolthulhu** [comment]
Yeah, hooves do negate the penalty. This makes tough feet+hooves pointless, but also weird (how can you have tough feet with no feet?).

**Comment by KA101** [comment]
Hooves are a giant toenail.  Horses have feet but don't walk on them.

**Comment by Midaychi** [comment]
What about mutation synergies? If you have certain mutations they either conflict or work together to make a new effect?
Like, having both tough feet and hooves might give an additional bonus to something, or tough feet and tentacles negate the silence bonus? Idk.

**Comment by Barhandar** [comment]
>Yeah, hooves do negate the penalty. This makes tough feet+hooves pointless, but also weird (how can you have tough feet with no feet?).

Tough "frog", the soft part inside the horse's hoof. Basically fingerpad.

**Comment by kevingranade** [comment]
I'm not clear what the problem is, not all foot mutations *should* negate
the no shoes penalty, they're supposed to be bad for you.

**Comment by Coolthulhu** [comment]
Leg tentacles doesn't deserve an extra nerf for not having tough feet. They're already really, really bad.
Padded feet and hooves could cancel tough feet, because they override them.
