### ISSUE TITLE
Tiles build broken in CBP

### ISSUE THREAD

**Issue by MattAmmann** [CleverRaven/Cataclysm-DDA#11236]
Looks like GCC doesn't like const and constexpr on the same line.
Build: SDL -Release
CBP version: 13.12
GCC version: 4.71

![2015-02-13 - 04_06_33pm](https://cloud.githubusercontent.com/assets/193401/6195271/595284c8-b39a-11e4-923d-9d60955c9fd0.png)

**Comment by KA101** [comment]
OK, that should fix it--let us know.

**Comment by MattAmmann** [comment]
That did the trick! Thanks.
