### ISSUE TITLE
Sleep and multi-tile mouse movement issues

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#11238]
(Alternate title: `[Tiles] Animations still don't animate!`)

As far as I'm aware from reading up on #7426 and #6780, both sleep and multi-tile mouse movement are animations. They work correctly in curses (ncurses for mouse movement: Windows Curses build doesn't work with mouse at all), but not in tiles. With sleeping it results in a big chunk of unresponsive CDDA, with movement - everything instantly changing. Other animations could possibly have the same problem still, but I haven't encountered these.

**Comment by DavidKeaton** [comment]
The animations for SCT and precipitation are tied into mouse handling during input polling.
