### ISSUE TITLE
 Question: how to change the vehicle's cruiser control speed ?

### ISSUE THREAD

**Issue by Eldhelion** [CleverRaven/Cataclysm-DDA#11244]
hello guys, I don't know if here is the place to ask this by I din't find other place.

Question: how to change the vehicle's cruiser control speed ?

I didn't find any  key to this on the wiki (http://www.wiki.cataclysmdda.com/index.php?title=Driving) nor on the in game help and my RV is with the cruiser control set to -126 
:(

**Comment by DavidKeaton** [comment]
Should just be `j` or `k`

**Comment by Eldhelion** [comment]
when the cruiser control is disabled, j and k change the vehicle's speed just like 8 and 2.

but on this way I need to adjust the speed time to time, I want to use cruiser control. but when it is enabled 8/k nor 2/j seens to do anything as the "desired speed" stay at -126

**Comment by DavidKeaton** [comment]
That sounds quite odd.

**Comment by narc0tiq** [comment]
> my RV is with the cruiser control set to -126 

Yeah, that's a bug that should've been fixed by #11175. What version of the game are you running?

**Comment by Eldhelion** [comment]
hm, it makes sense. I'm with 0.B that is available to download at wiki.

I think it time to me to try compile the game again, I failed to compile the game because of lua :( when I was presented to the game, last year.

thanks guys!

**Comment by narc0tiq** [comment]
Unless you're on Mac, the experimental builds should be at least as good as compiling your own.
