### ISSUE TITLE
Crash on boarded house start

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#11245]
Doesn't happen on 2695 build.
Happens on 2745.
Happens on 2725 with debug message "Tried to access invalid map position (0,24)"
Happens on console and x86 versions too.
Happens even if options, worldgen options and character setting are untouched.

**Comment by bkentel** [comment]
Investigating -- could be somehow related to the lighting tweaks.

**Comment by bkentel** [comment]
Mmm definitely something strange afoot :

![fishy](https://cloud.githubusercontent.com/assets/780369/6203303/420009fc-b55d-11e4-8d66-b3a5531e4daf.png)

**Comment by bkentel** [comment]
Looks like the above is a separate issue related to `t_thconc_floor` having no tile? No crash anyway. Continuing to investigate.

**Comment by Mshock777** [comment]
Only things I change: change it to missed and boarded house. Just tested again on 2750.

**Comment by bkentel** [comment]
Does it happen on a freshly generated world too?

**Comment by BevapDin** [comment]
Not tested, but:

`start_location::setup` calls `start_location::prepare_map`, which calls `map::build_map_cache` on a `tinymap`, which calls `map::generate_lightmap`, which goes through `MAPSIZE x MAPSIZE` submaps, but the tinymap has only 2x2 submaps. This could be the problem (`map::generate_lightmap`):
```C++
    auto const stride = my_MAPSIZE;
    for (int smx = 0; smx < MAPSIZE; ++smx) {
        for (int smy = 0; smy < MAPSIZE; ++smy) {
        auto const cur_submap = grid[smx + smy * stride];
```
It uses `stride` (correctly) for the submap index, but it iterates using `MAPSIZE`, not `stride`. To avoid this kind of bug, one can use `map::get_submap_at_grid` (or directly `map::get_nonant`), `get_nonant` checks its parameters and prints a debugmsg.

**Comment by bkentel** [comment]
:bow: didn't realize that could happen; I'll make the changes if you haven't.

**Comment by Gabriel-SE** [comment]
I can confirm this.

Console version
Scenario : Missed
Starting Location : Boarded up house
Crash on new world and new character.
```
/usr/include//c++/4.8/debug/vector:346:error: attempt to subscript container with out-of-bounds index 4, but container only holds 4 elements.
Objects involved in the operation: sequence "this" @ 0x0xbfff9914 { type = Nst7__debug6vectorIP6submapSaIS2_EEE; }

Program received signal SIGABRT, Aborted.
0xb7fdd424 in __kernel_vsyscall ()

bt
#0  0xb7fdd424 in __kernel_vsyscall ()
#1  0xb7cad577 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0xb7cb09a3 in __GI_abort () at abort.c:89
#3  0xb7f330a0 in __gnu_debug::_Error_formatter::_M_error() const () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#4  0x086ce87f in std::__debug::vector<submap*, std::allocator<submap*> >::operator[] (this=0xbfff9914, __n=4) at /usr/include//c++/4.8/debug/vector:346
#5  0x086c91ae in map::build_transparency_cache (this=0xbffa8848) at src/lightmap.cpp:51
#6  0x0871f950 in map::build_map_cache (this=0xbffa8848) at src/map.cpp:5335
#7  0x08d1d1e8 in start_location::prepare_map (this=0x96f21fc, m=...) at src/start_location.cpp:186
#8  0x08d1d4cd in start_location::setup (this=0x96f21fc, cur_om=@0xb7c140b0: 0xb7698008, levx=@0xb7c651c0: 0, levy=@0xb7c651c4: 0, levz=@0xb7c651c8: 0)
    at src/start_location.cpp:210
#9  0x0837e4d9 in game::start_game (this=0xb7c14008, worldname=...) at src/game.cpp:612
#10 0x086dd205 in game::opening_screen (this=0xb7c14008) at src/main_menu.cpp:427
#11 0x086d8692 in main (argc=0, argv=0xbffff098) at src/main.cpp:292
A debugging session is active.
```
