### ISSUE TITLE
Painkillers are broken again. v2748

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#11256]
Only stuff that directly removes pain seems to work.

The timed-release painkillers like opiates are all nonfunctional.

**Comment by DavidKeaton** [comment]
Not again! :-(

**Comment by KA101** [comment]
Pretty confident this was reported already, never been fixed.

**Comment by i2amroy** [comment]
In a check of the near-latest experimental I couldn't replicate this at all. Both aspirin and oxycodone successfully reduced my pain levels. Is anyone still encountering this problem?

**Comment by Rivet-the-Zombie** [comment]
Most recent testing proves this has been fixed.
