### ISSUE TITLE
Invisibility prevent player from seeing his own body in tiles version

### ISSUE THREAD

**Issue by Gabriel-SE** [CleverRaven/Cataclysm-DDA#11264]
Maybe it's to hide NPC with Cloacking System CBM, but it's hard to move with invisibility when you can't see your own body.
Ideally the game should draw with 50% transparency for player, NPC can be 100% invisible.
##

**Comment by kevingranade** [comment]
This is a tileset issue, the tileset is missing a tile for a cloaked pc/npc.

**Comment by Gabriel-SE** [comment]
Shouldn't tileset fall back to ascii when it can't find the tile ?

**Comment by KA101** [comment]
Not all tilesets have fallback configured.
