### ISSUE TITLE
Wish menu display is broken

### ISSUE THREAD

**Issue by Gabriel-SE** [CleverRaven/Cataclysm-DDA#11265]
Probably related to @OzoneH3's tailoring PR

![Wish menu](http://i.imgur.com/zva5RQX.png)

**Comment by KA101** [comment]
Gotta love people complaining that the debug menu doesn't look purty.  I didn't consider it a major problem.

**Comment by Rivet-the-Zombie** [comment]
If anybody PRs a fix, I'd still merge it.

**Comment by KA101** [comment]
It's been fixed.  Thanks, OzoneH3.
