### ISSUE TITLE
Paper ammunition recipes cannot count

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#11279]
They take, per 25 bullets (single unit): 1 money bundle, 1 [paper wrapper](http://www.jonathanfongstyle.com/wp-content/uploads/2013/02/chocolate2.jpg), 1 [plastic bag](http://th08.deviantart.net/images/PRE/i/2002/24/4/2/Plastic_Bag.jpg) or __25__ papers.

A single book makes `volume * 20` pages, seeming to imply that each "paper" is a whole page from one.
Therefore, given the above pictures, if using paper it miraculously takes twenty-five more of it.

Colt Navy/Army also used nitrated paper cartridges so it would burn up completely instead of leaving residue in the chambers. Perhaps if saltpetre and/or ammonium nitrate are a bit more common, the recipe could be adjusted to take some (say, 5 portions: dissolving it goes a long way) along with water?

**Comment by KA101** [comment]
Misclick there.

**Comment by Dozed12** [comment]
I think this is what you mean: #11354
