### ISSUE TITLE
Hexamine is present, but supposedly common Esbit stove isn't

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#11280]
The description could reference the preference of scavengers to just dismantle it and use hexamine for explosives, explaining the rarity, I dunno.

**Comment by KA101** [comment]
More along the lines of hexamine being added after the mess kits.  Preferences are touchy as someone's gonna come along and prefer the opposite.

**Comment by Barhandar** [comment]
>More along the lines of hexamine being added after the mess kits.

Yeah, I know, it's more along the lines of wondering why the stove wasn't added when hexamine was. And clearly, preferring the opposite is how the players would be able to read the description. Which is equal to "often dismantled for parts", I guess.

**Comment by KA101** [comment]
I think Aenye's a bit of a pyro* when it comes to chemistry, so her focus was on explosives, not practical use.  Fair enough, there's always room to improve.

*And we like her just the same, thanks.

**Comment by Barhandar** [comment]
More Survival Tools mod adds the stove now.
