### ISSUE TITLE
Can't scroll bionics screen

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#11299]
If list gets too large, you can't see lower portion.

**Comment by KA101** [comment]
Little bit both bug (interface didn't keep up with players) and enhancement (interface expands to accommodate more augs).

**Comment by DanmakuDan** [comment]
I noticed  #9693 was an interface update for it, is it still relevant?

**Comment by KA101** [comment]
Likely a pain to rez, but can be looked into.

**Comment by DanmakuDan** [comment]
Actually, it looks like the window scrolls with the up/down arrows when the list is long enough.

**Comment by kevingranade** [comment]
Yep, it scrolls now.
