### ISSUE TITLE
Pull metal weapon monster ability checks wrong skills to resist

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#11291]
It only respects skills marksmanship, bashing and cutting. Weapons with cutting/bashing damage lower than 8 get no skill bonus and spears can only get the bashing bonus (because they are never cutting weapons).

Piercing weapon and unarmed combat skills do not ever contribute to the roll.

First bonus is used rather than the most appropriate or highest one, meaning that a weapon with 8 bashing and 20 cutting damage will use bashing skill, even if the defender has 10 cutting skill and 0 bashing.

Marksmanship doesn't really sound like a good skill to use here. It would probably be better to treat guns as melee weapons for this purpose.

**Comment by Rivet-the-Zombie** [comment]
It seems to me that ````melee```` would be a good catchall skill for resisting.

**Comment by Gabriel-SE** [comment]
> It seems to me that melee would be a good catchall skill for resisting.

For purist martial arts master, his cutting weapon / bashing weapon skill is probably 0.
It'll be weird if someone that never use a sword before knows how to grip katana efficiently.

>Weapons with cutting/bashing damage lower than 8 get no skill bonus

This is intended. The idea here is that if you wield tin can, zombie technician should be able to take it easily from you since you never use it in combat as weapon, you're not familiar with it.
Item with cutting / bashing < 8 is probably not a weapon and you shouldn't use it in combat.

> Piercing weapon and unarmed combat skills do not ever contribute to the roll.

This is a mistake on my part. Piercing weapon should use piercing weapon skill.
I'm not sure about unarmed combat.

> Marksmanship doesn't really sound like a good skill to use here. It would probably be better to treat guns as melee weapons for this purpose.

See my martial arts argument above. If you're trained to use guns often, you'll know how to handle it better with experience, like how to use two hands to enhance your grip.

**Comment by KA101** [comment]
Unarmed might apply to UNARMED_WEAPON stuff.

**Comment by Rivet-the-Zombie** [comment]
Also most of the UNARMED_WEAPONs have cutting/basing < 8; they just give small boosts.

**Comment by Coolthulhu** [comment]
> For purist martial arts master

I think a martial artist would have gripping things worked out pretty well. And a sledgehammer wielder should easily use the same skills to prevent a halberd or a fire axe being ripped out from his hands. At the same time, sword wielder wouldn't be good at holding an axe.

I agree with Rivet on this one: `melee` sounds good as a general combat skill, representing things like footing, proper weight balancing etc. that every fighter needs to know. Just like marksmanship represents installing weapon mods (and probably maintaining weapons too). Specific weapon skills sound odd to me here (back to the axe/sword example).

> I'm not sure about unarmed combat.

Those are generally low-damage (some below 8 in both damage categories), but are gripped really well (worn like gloves rather than handled). One option would be to treat them like stuck weapons do - stuck unarmed weapons are never pulled out of user's grip.

> If you're trained to use guns often, you'll know how to handle it better with experience, like how to use two hands to enhance your grip.

Here I'd actually split into weapon types. Rifles, pistols and crossbows are all handled totally differently - I'd say the difference is bigger than between holding a spear and holding an axe.
Still, I'd rather see `melee` here - handling recoil and handling weapon suddenly jerking forward sound quite different to me (never held a gun in my hands, though).

**Comment by KA101** [comment]
Holding a gun for melee use and for shooting are significantly different grips, bayonets notwithstanding.

**Comment by Gabriel-SE** [comment]
Ok, I read all of your arguments and melee could work too.
I'll post a PR and change the resistance to use melee skill instead of weapon skill.
