### ISSUE TITLE
Build broken in Code::Blocks.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#11293]
Ugly brick of error code:

||=== Build: Release in Cataclysm (compiler: GNU GCC Compiler) ===
C:\CDDA\src\json.h||In instantiation of 'bool JsonIn::read(T&) [with T = std::set<std::basic_string<char> >; typename std::enable_if<std::is_same<typename T::key_type, typename T::value_type>::value, void>::type* <anonymous> = 0u]':
C:\CDDA\src\json.h|594|required from 'bool JsonObject::read(const string&, T&) [with T = std::set<std::basic_string<char> >; std::string = std::basic_string<char>]'
C:\CDDA\src\savegame_json.cpp|1090|required from here
**C:\CDDA\src\json.h|268|error: 'class std::set<std::basic_string<char> >' has no member named 'emplace'**
C:\CDDA\src\json.h||In instantiation of 'bool JsonIn::read(T&) [with T = std::set<label>; typename std::enable_if<std::is_same<typename T::key_type, typename T::value_type>::value, void>::type* <anonymous> = 0u]':
C:\CDDA\src\json.h|594|required from 'bool JsonObject::read(const string&, T&) [with T = std::set<label>; std::string = std::basic_string<char>]'
C:\CDDA\src\savegame_json.cpp|1351|required from here
**C:\CDDA\src\json.h|268|error: 'class std::set<label>' has no member named 'emplace'**
||=== Build failed: 2 error(s), 6 warning(s) (7 minute(s), 23 second(s)) ===

**Comment by KA101** [comment]
Been out for a few days: MinGW32 issue.  I've been running the Backup Compiler.  Sick of having to make the same argument repeatedly.

**Comment by bkentel** [comment]
Looking into it.

**Comment by bkentel** [comment]
Hmm, clearly std::set does have emplace: http://en.cppreference.com/w/cpp/container/set .
What version of gcc

**Comment by bkentel** [comment]
If this is indeed related to mingw using older version of GCC, a fix would be to use `insert` instead of `emplace` either specifically for old version of libstdc++, or in general.

**Comment by bkentel** [comment]
Looks like it's fixed as of GCC 4.8?

**Comment by MattAmmann** [comment]
This error was fixed in later versions of the GCC than what CBP comes with. I was able to fix this error by downloading and installing the latest GCC release from TDM-GCC's website. When I changed the compiler path to the install path of that program, the error went away and the code compiled.

**Comment by i2amroy** [comment]
Yeah, it's an older/incomplete version of GCC (which, strangely enough, doesn't affect the Cygwin build the usual victim of these type of problems :P).

From what I could see the answer is exactly as Matt outlined it, just download and install a newer version of GCC.

**Comment by MattAmmann** [comment]
To further clarify, download the 32-bit version. Also, the path that needs to be changed in CBP is here: Setting->Compiler->Toolchain Executables tab. Change the "Compiler's installation directory" to the bin folder where TDM-GCC was installed. For example, mine is C:\Program Files (x86)\TDM-GCC-32\bin.

**Comment by Rivet-the-Zombie** [comment]
I had to update C::B at the same time to make it work, but @MattAmmann's fix worked for me.

This still seems like a bit of a hurdle for new contributors to cross.

**Comment by KA101** [comment]
>This still seems like a bit of a hurdle for new contributors to cross. Is there no better alternative?

Changing the code would be preferable.

**Comment by kevingranade** [comment]
Yea, emplace isn't THAT magical an interface that it's worth making new
contributor's lives harder.

**Comment by kevingranade** [comment]
Removed call to set.emplace().
