### ISSUE TITLE
Aiming at a luminescent target in darkness not working correctly

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#11302]
When aiming at a luminescent target that is only visible due to its luminescence, aiming will break if the target enters a spot not covered by own luminescence in the last turn.

For example:
* Aiming at a shocker in the darkness
* Shocker moves
* Shocker is visible, but aiming menu reports "no visible targets" and doesn't target it

It also does happen with shocker brutes, but only if they move 2 tiles in one direction. ie. When they move into a spot that wasn't covered by their luminescence in the last turn.

**Comment by kevingranade** [comment]
Looks like get_visible_creatures() returns no monsters sometimes when called by game::pl_target_ui()
