### ISSUE TITLE
Burning Building scenario fire fields incorrectly placed

### ISSUE THREAD

**Issue by MattAmmann** [CleverRaven/Cataclysm-DDA#11319]
In the Burning Building scenario, sometimes (but not always), the fire fields are outside of the actual building. Here's an example (start building is a Library):
![2015-02-18 - 02_52_12pm](https://cloud.githubusercontent.com/assets/193401/6255500/54ee0640-b77e-11e4-9af8-256672f5aa5a.png)

I've uploaded the save file where this happened:
http://www.mediafire.com/download/03y2kekhytc5616/Roaming_Shores.zip

Cata version: 14fea4514ebb5d161de81473ffd1aec5e2ab5aab

**Comment by DavidKeaton** [comment]
This start brought to you by a Guy who can't throw molotovs

**Comment by MattAmmann** [comment]
Here's a screenshot of another instance where this happened. This time, I was doing the Really Bad Day scenario. The common thread seems to be houses that are spawned on an intersection:

![2015-02-22 - 04_29_48pm](https://cloud.githubusercontent.com/assets/193401/6320606/584c628e-bab0-11e4-9fea-2e0d6ea529f8.png)
