### ISSUE TITLE
Plant mutagen requires tainted veggy, produced mainly by fungi creatures.

### ISSUE THREAD

**Issue by Tomcost** [CleverRaven/Cataclysm-DDA#11322]
As the title says, this is counter-intuitive. A character willing to go through the plant path should go kill triffids, not fungaloids. I am not sure if, according to lore, fungaloids should even be creatures from which you could make mutagen at all.

Changing veggy_tainted by veggy in the recipe should be enough, I suppose.

**Comment by KA101** [comment]
Yeah, the Mycus changes undermined this.  I'm OK with the proposed fix.

**Comment by i2amroy** [comment]
Closing, since this was fixed and didn't auto-close.
