### ISSUE TITLE
Bad format string for printf when describing in crafting menu

### ISSUE THREAD

**Issue by DanmakuDan** [CleverRaven/Cataclysm-DDA#11331]
0.B-2768 (381dacd)

Error only shows so far for (sleeveless) survivor trenchcoat/duster. Might have to do with the percent signs in the notes for them in the JSON? Also happens with a book (probably Handloader's Helper, but not sure) where it would normally print the list of recipes.

![bug_bad_format_string_printf](https://cloud.githubusercontent.com/assets/9610892/6281621/2995596e-b88a-11e4-805f-c250573770fc.png)

**Comment by KA101** [comment]
Could have sworn we dealt with this months ago.  Thanks for reporting.

**Comment by Dozed12** [comment]
What does the error mean, does it mean that it failed to print the description because its not a proper string? I'm trying to help here but I'm not sure what the error means.

**Comment by BevapDin** [comment]
It means the format string (first parameter to the `string_format` function in output.cpp) contains an invalid format.

For example in the format string "The %s hits you!" the %s is replaced with the actual monster name. The `%` indicates that something should be inserted there, the `s` tells what is to be expected (in this case another string). If the format string was "The %d hits you!", the function would expect and insert a number (`d` = decimal integer).

Something like "The %" is invalid, because the `%` is the last character and the function does not know *what* to insert there. Similar "%v" is also invalid as `v` is not a format identifier.

The behavior of the formating function differs on Windows and Linux, what operating system do you use? And is this the result of pressing 'e' to view the description of the resulting item?

**Comment by DanmakuDan** [comment]
This is the Windows Tiles version, and that screen is from attempting to view the description.

**Comment by DavidKeaton** [comment]
In addition to BevapDin's statement, if you are trying to show a percent sign, you need to escape it.

**Comment by Dozed12** [comment]
I really dont see why this gets the error, the json is correct, the problem most likely is ( as the issue author stated) related to the notes and how it has diferrent behaviors when it uses an existent "sleeved" trench coat and when it creates one from scrath but even in that situation, although I'm pretty new to cataclysm script structure, I dont see the problem... ( 2 years working with Unity without touching c++ dont help either).

**Comment by narc0tiq** [comment]
I'll tell you what, it's not the notes -- those don't get stored anywhere
in the item object and therefore cannot possibly be printed.

**Comment by narc0tiq** [comment]
Further details: it reproduces in the Jenkins Windows builds (both 32- and 64-bit, both Curses and Tiles), but not the Linux Curses build. I don't have a lintiles machine handy, but expect it should be working there, as well.

**Comment by Dozed12** [comment]
The thing is the notes refer to a special crafting behavior, when the player has and when he doesnt have a trenchcoat, that might be the problem.

**Comment by BevapDin** [comment]
> The thing is the notes

That is easy to test, just remove the note from json and try to reproduce the bug, but as a Linux user I can't really help there.

**Comment by narc0tiq** [comment]
@Dozed12 
> the notes refer to a special crafting behavior [...]

The notes refer to how the recipes for those items should be written -- for example, the sleeveless survivor trenchcoat has two recipes, whose components, etc., presumably all follow the rules as set out in the notes. They're comments in the JSON, nothing more.


@BevapDin 
> remove the note from json

Done. Bug continues to reproduce. Big surprise.


As best I can tell with a purely cursory examination, the part that seems to be busted is [this line of src/crafting.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/29f8aa5717c399026993c35f5bdb4663a101fb00/src/crafting.cpp#L806):
```C++
full_screen_popup("%s\n%s", tmp.type_name( 1 ).c_str(), tmp.info(true).c_str());
```

Technically, it might be something inside the calls to `item::type_name` or `item::info`, but the behaviour doesn't match: either both would fail (leading to two errors), or one would fail and the other succeed (leading to one error and partial information).

Personally, I don't see how `"%s\n%s"` could be a bad format string, especially with the result of a pair of `std::string::c_str` calls being plugged in as the varargs, but there you have it.

**Comment by narc0tiq** [comment]
[A quick googling](https://www.google.com/search?q=mingw-w64+vsnprintf&hl=en) suggests that [mingw-w64 by default uses Microsoft's vsnprintf implementation](http://sourceforge.net/p/mingw-w64/wiki2/printf%20and%20scanf%20family/), which returns -1 if the output buffer isn't large enough. This is [mentioned in output.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/48e232c09ac12b62d8e80ba981e8a6e26d26cb55/src/output.cpp#L1496) as a reference to "some non-standard versions":

```C++
// Standards conformant versions return -1 on error only.
// Some non-standard versions return -1 to indicate a bigger buffer is needed.
if (result < 0 && errno) {
    return std::string("Bad format string for printf.");
}
```

**Comment by KA101** [comment]
Bloody hell.  My apologies, all.  >_<

**Comment by narc0tiq** [comment]
@KA101 No worries, it only shows up on, like, a few items with really long descriptions. Look at it this way: now we know what items have sufficiently long descriptions to be really good testing fodder!

**Comment by bkentel** [comment]
Looking into things after talking with @narc0tiq on IRC.

**Comment by DavidKeaton** [comment]
I'd hardly be upset about a merge that only made a few strings from displaying. Could always be the one to merge a b0f!
