### ISSUE TITLE
fatal error: 'type_traits' file not found on MAC 10.9.5

### ISSUE THREAD

**Issue by ZETEADOR** [CleverRaven/Cataclysm-DDA#11338]
```
Cloning into 'Cataclysm-DDA'...
remote: Counting objects: 145024, done.
Receiving objects: 100% (145024/145024), 345.83 MiB | 4.56 MiB/s, done.
remote: Total 145024 (delta 0), reused 0 (delta 0)
Resolving deltas: 100% (113306/113306), done.
Checking connectivity... done.
iMac-de-NOLU:Cataclysm-DDA NOLU$ cd Cataclysm-DDA
iMac-de-NOLU:Cataclysm-DDA NOLU$ make NATIVE=osx
#define VERSION "0.B-3535-g5aec41c"
mkdir -p obj
g++ -DMACOSX -DLOCALIZE -Werror -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-missing-braces -g -D_GLIBCXX_DEBUG  --std=c++11 -MMD -mmacosx-version-min=10.5 -c src/action.cpp -o obj/action.o
In file included from src/action.cpp:2:
In file included from src/output.h:5:
In file included from src/line.h:6:
In file included from src/enums.h:4:
src/json.h:4:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^
1 error generated.
make: *** [obj/action.o] Error 1
```

**Comment by ZETEADOR** [comment]
And if i use the launcher this is the report:

Last login: Fri Feb 20 19:22:29 on ttys000
/Users/Cataclysm-DDA/cataclysm-launcher ; exit;
iMac-de-NOLU:~ NOLU$ /Users/Cataclysm-DDA/cataclysm-launcher ; exit;
Couldn't find cataclysm game binary in /Users/Cataclysm-DDA/
logout

**Comment by kevingranade** [comment]
http://stackoverflow.com/questions/9345271/xcode-4-3-and-c11-include-paths
It looks like gcc needs the flag ```-stdlib=libc++```, the clang build already uses it, not sure why the gcc one doesn't.
Can you try moving lines 129-131 above the ```ifdef CLANG``` line?  I think that will fix it.

**Comment by NicholasTao** [comment]
I met the same problem, and I did the move thing, but it's still not be solved, is there another way?
I use the 0.C version, On last Xcode

**Comment by illi-kun** [comment]
Is this still an issue? I know some PRs modified makefile (PRs like #13206, #16167), so maybe this issue is gone already?

@remyroy you're the only developer on OSX I know so could you shed light on this, if it's possible?

**Comment by remyroy** [comment]
This is not an issue anymore. You can close it.

**Comment by illi-kun** [comment]
Wow, thanks for help & fast reply!

Revising of [```OSX```] (/CleverRaven/Cataclysm-DDA/labels/OSX) bug reports & tracking their status is an issue for me.
