### ISSUE TITLE
Debug spam when removing boardable aisle from vehicle while standing on it

### ISSUE THREAD

**Issue by DanmakuDan** [CleverRaven/Cataclysm-DDA#11330]
Using 0.B-2768 (381dacd).
Debug message spam happens on each movement until I leave the vehicle, but doesn't occur again until I remove another aisle I am standing on. Probably some boarding state didn't change when the part was removed.

![bug_boarding_walk](https://cloud.githubusercontent.com/assets/9610892/6281560/273e9e1a-b889-11e4-87d7-8d1830dc283c.png)
![bug_boarding_before](https://cloud.githubusercontent.com/assets/9610892/6281561/273f7678-b889-11e4-9825-cefe38b28a1a.png)
![bug_boarding_after](https://cloud.githubusercontent.com/assets/9610892/6281559/273d0b7c-b889-11e4-8335-29448652b393.png)

**Comment by DanmakuDan** [comment]
As far as I can tell, the vehicle is 'boarded' by my player entering a tile with a boardable part. When the boardable part I am standing on is removed, the player is still 'in' the vehicle, but the 'inside vehicle' status isn't cleared. Because the debug message is activating, the 'inside vehicle' status doesn't get cleared until I walk into another boardable part. Because there is a door on the end before I can get out, my status will coincidentally clear and end the message spam. If there were only steel frames to a path out of the vehicle, I would probably see "map::unboard_vehicle: vehicle not found" and it would kick me out in the debug clause.

I think vehicle::remove_part is missing a catchall for any boardable part, since it does perform unboarding for a seat that is removed from the vehicle.

```
    if(part_flag(p, "SEAT")) {
        ...
        // Also unboard entity if seat gets removed
        std::vector<int> bp = boarded_parts();
        for( auto &elem : bp ) {
            if( elem == p ) {
                g->m.unboard_vehicle( global_x() + parts[p].precalc[0].x,
                                      global_y() + parts[p].precalc[0].y );
            }
        }
```

**Comment by narc0tiq** [comment]
@DanmakuDan I believe you have it -- and fixing it should be as simple as replacing "SEAT" with "BOARDABLE" in that block.
