### ISSUE TITLE
Tailor's kit issues.

### ISSUE THREAD

**Issue by Darkyhard** [CleverRaven/Cataclysm-DDA#11345]
1. You can modify an item with a tailor's kit even if this item can't be worn. Well, adding kevlar plates on a canvas bag is possible, but doesn't make any sense since you're not going to wear it anyway, so why would you want to do that?
2. If you choose to repair an item with a tailor's kit, you are asked about which item to repair for the second time.
3. Tailor's kit description says that it contains a heating element and you need a lighter to craft it, yet it doesn't require the lighter to contain any fuel. I would suggest to use appopriate tools from inventory if you are working with plastic instead of making it included in the kit itself.

Also, I would suggest to prevent modifying an item if it won't benefit from this (if storage/warmth/protection won't increase at all after modification) and to add some way to remove modifications.

**Comment by Coolthulhu** [comment]
Also from forums:
It's impossible to repair a doubly modified item with the tailor's kit.
