### ISSUE TITLE
Bone needles from human or zombie bones?

### ISSUE THREAD

**Issue by FredZeppelin** [CleverRaven/Cataclysm-DDA#11352]
New to the game, and expected to be able to make a bone needle from a human or zombie bone, but you couldn't. Had to go track down an animal bone. Seems like all bones should work for bone needles, no?

**Comment by Rivet-the-Zombie** [comment]
Human bones totally ought to work for this, but the tainted bones specifically mention that they're spongy and all messed up from the goo, so stuff like a bone needle isn't really doable with them.

**Comment by Dozed12** [comment]
This should fix it: #11353

**Comment by FredZeppelin** [comment]
Thanks, you guys are amazing. :)

**Comment by Dozed12** [comment]
These little things are quite easy, if your game crashes for some reason I wouldnt be the guy to ask for a solution ;D
