### ISSUE TITLE
Kompot & crafting

### ISSUE THREAD

**Issue by KA101** [CleverRaven/Cataclysm-DDA#11360]
OK, so kompot being counted by charges makes it act Weird when folks move it around.

http://smf.cataclysmdda.com/index.php?topic=9597.msg220854#msg220854

It's straightforward to upmass it and take it off charges to fix the volume complaint, but then:
1) using the byproducts system to give the full 12 charges breaks things, as the game can't determine that you have a container (tested to a plastic jerrycan) suitable to hold the kompot;
2) removing the byproducts line ended up consuming 1 sugar, four apples, the time, and probably the charges--but not the water.

**Comment by BevapDin** [comment]
The kompot item has 12 charges (each weights 21 units) and takes up 1 volume (all 12 charges together). The (empty) 3-l jar has a volume of 12 and can contain 12 volume (seems to be very thin glass). So technically a 3-l jar of kompot should contain 12*12 charges of kompot (which would have 12 volume).

I suggest changing the kompot item to have 12 volume (1 volume per charge), that would make the 3-l jar of kompot item full.

About the mass: the jar_3l_glass weights 365, one charge of kompot weights 21, so a 3-l jar of kompot should be 21*12+365=617.

Btw. in json the weight is per single charge, but the volume is per default stack size, this is a bit confusing.

**Comment by KA101** [comment]
Issue: As I understand volume-of-charges, it's an all-or-nothing deal.  One charge (either the first or the last in a given stack of charges, I'm not sure) costs the full volume, and the rest are free.  I'm betting that's been fixed, though.

If it hasn't, making kompot vol 12 then breaks transferring it to smaller containers: either it takes no space or it greatly overflows the unit.  The original problem would persist.  :-/

**Comment by BevapDin** [comment]
> Issue: As I understand volume-of-charges, it's an all-or-nothing deal. One charge (either the first or the last in a given stack of charges, I'm not sure) costs the full volume, and the rest are free. I'm betting that's been fixed, though.

Yes, but it's rounded down, kompot (11) has 0 volume, kompot (12) has 1 volume, kompot (23) has 1 volume. Its not fixed, is the volume is an integer number without fractional part. Kompot (6) would have 0.5 volume but that can not be represented currently.

> If it hasn't, making kompot vol 12 then breaks transferring it to smaller containers: either it takes no space or it greatly overflows the unit. The original problem would persist. :-/

I tried that, it does indeed not work that easy. What works is:
- setting charges of kompot 1.
- "result_mult": 12 to the recipe for kompot (not the 3-l jar recipe).

Now kompot (12) has 12 volume, unloading it into a plastic bottle results in 2 charges kompot in it.

**Comment by KA101** [comment]
OK, you did what I did.  Encountered problem 2, or was that just me?

**Comment by BevapDin** [comment]
Putting kompot in a bottle works now like with water (normal bottle 2 charges, small bottle 1 charge), but it was indeed broken before this.

**Comment by KA101** [comment]
Uh, ,problem 2 in the OP: it didsn't actually consume all the crafting ingredients.

**Comment by BevapDin** [comment]
I couldn't reproduce that bug, maybe your character was near a natural water source and used that?

**Comment by KA101** [comment]
Nor could I in mergetesting, so probably a fluke.  (Was in the evac shelter, but might have had other water nearby or something.)
