### ISSUE TITLE
Eskrima doesn't recognise some knives

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#11366]
Noteable missing knives from Eskrima use - trench knife and hunting knife.

It looks like Pentjak Silat is missing the same ones, and also switchblade (which works with Eskrima).

I can edit the json, but wanted to check none of these was a deliberate choice.

**Comment by KA101** [comment]
I think trench/hunting knives might be as they're more utilitarian (trench with its handguard, huntinig only has the single edge).  Could be wrong though.

**Comment by romkuma** [comment]
Looking at the history, trench knife was deliberately left out in #6581. Switchblade was added to Eskrima at that time, but no discussion about why it was left out of Pentjak. Could be an oversight?

Hunting knife was added in #8932, and the other knives there were added to the MA styles in #8946. Looks like a deliberate choice by @Rivet-the-Zombie - it wasn't intuitive to me as a player that the hunting knife wouldn't work but no big deal.

**Comment by KA101** [comment]
Well, the hunting knife is designed to skin/butcher the game once you kill it, not to kill the game.  Sharp edge and all, but it's not built with combat in mind.  Agreed that it might bear stating that in the description, but string freeze.  (If you file a PR, it'll get in once 0.C stable lands.)
