### ISSUE TITLE
TV disappears after smashing

### ISSUE THREAD

**Issue by MattAmmann** [CleverRaven/Cataclysm-DDA#11388]
For an item with so many "delicious electronics", it's odd that smashing a television doesn't yield something, even if it's just a couple chunks of plastic or steel.

**Comment by Rivet-the-Zombie** [comment]
Sounds like something wrong in the unified butcher/disassemble action code, as manually disassembling it from your inventory does indeed return a great deal of 'delicious' electronics.

**Comment by Darkyhard** [comment]
I think MattAmmann meant that he smashed a TV lying on the floor using smashing command and didn't got anything from it.

**Comment by KA101** [comment]
And got exactly what he deserved, IMO.  Smashing stuff is destructive extraction, so any recoverable electronic parts would be a bonus.  (Agreed re plastic/steel, though.)

**Comment by Coolthulhu** [comment]
It's because TV has a glass component. Glass items get smashed into nothing.

**Comment by Dozed12** [comment]
It could produce glass shards but they are pretty common.

**Comment by Coolthulhu** [comment]
Destroyed items don't produce stuff other than their contents (and those only if they're containers).
I'd say TVs should just lose the glass component, because nobody cares about the glass part and it only makes them more fragile.

**Comment by KA101** [comment]
Agreed, lose the glass.
