### ISSUE TITLE
"You parry the zombie for XX damage"

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#11386]
Same problem as #7695 but with Parry instead of Block. Saw this yesterday with a character armed with a survival knife, using Eskrima.

**Comment by kevingranade** [comment]
What version did you see this in? The fix for #7695 was applied to the parry technique too.

**Comment by romkuma** [comment]
I was using the latest experimental at the time of the report. I've been updating it regularly but the save is only a few weeks old. Currently have g468c52e running and I'm pretty sure I've still seen it in the last few days.

Is there value in a clean install and transferring the save across to check if it fixes it?

Alternatively, I could try to replicate with a clean install with a similar character and weapon? Let me know what you think is best.

**Comment by romkuma** [comment]
Just updated to the latest experimental, playing tonight had it again - screenshot attached.

![screenshot from 2015-03-03 21 50 17](https://cloud.githubusercontent.com/assets/8448518/6460906/5d7704a8-c1ef-11e4-8888-47a792b0d052.png)

Linux & tiles if that is a factor.
