### ISSUE TITLE
Lava can spawn inside buildings

### ISSUE THREAD

**Issue by MattAmmann** [CleverRaven/Cataclysm-DDA#11393]
Is this a bug or a feature?

![2015-02-25 - 08_44_47am](https://cloud.githubusercontent.com/assets/193401/6371556/fb16ce5c-bcca-11e4-839f-92ed71532d51.png)

Version: 76c8120

**Comment by Dozed12** [comment]
I dont know the lore behind lava on surface but I guess its a feature.

**Comment by BevapDin** [comment]
The lave-on-surface feature is quite old, and not a bug at all. It's a map extra (see `map::add_extra`), this one is called `mx_fumarole`.

**Comment by MattAmmann** [comment]
I had a feeling it was intended. Thanks for the info! Alright, closing since it's WAI.

**Comment by KA101** [comment]
Ideally we'd have lava originate from a hellmouth (portal to Hot Nether, much like ideally ice labs would finale in a portal to Cold Nether) and go vertically up from there.

But yeah, not there yet.
