### ISSUE TITLE
Copbots and turrets: do they fight zombies or not?

### ISSUE THREAD

**Issue by Packbat** [CleverRaven/Cataclysm-DDA#11394]
I've noticed that in recent builds (I'm playing 0.B fca8c33) there seems to be a conflict between the in-game lore and game behavior: on the one side, you have newspaper articles and notes talking about how the automated police turrets don't fight the 'invaders':
![2015-02-25 copbots ignore them](https://cloud.githubusercontent.com/assets/11142302/6372149/e52651bc-bccf-11e4-82c5-2729c6272221.png)
...but when you have zombies and turrets on the same screen, they fight each other. What is the intended behavior here?

**Comment by vache** [comment]
Fighting each other is the intended behavior I think.  It didn't used to be possible, so notes like those were added to explain a little bit about it, but now that it is possible, those notes should probably be removed.

**Comment by i2amroy** [comment]
IIRC the current lore basically goes like this:
At first the copbots and turrets basically just ignored the zombies. In order to fix that problem they ran an update to make them more hostile, but in the rush someone made a simple mistake. As a result now they are hostile to zombies and other things, but they are also hostile to *all other humans* as well.

**Comment by KA101** [comment]
Yeah, that's pretty much it, and I'm on board with removing the note.  Whether that can be done during the string freeze is another question--I don't think removing a line should disrupt other translated lines, so I'm inclined to nail it now.

**Comment by Packbat** [comment]
Cool - makes sense! I think there's a newspaper article that would need updating as well to match that lore.

**Comment by kevingranade** [comment]
I think string removals are fine.
