### ISSUE TITLE
Idea: Select a recipe to focus on when reading a 'recipe-giving-source'

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#11402]
What it says on the tin: a mechanic where after the first skim of a recipe-giving-source you can focus on a particular recipe you want to learn.

This seems to be quite prevalent that you're interested in maybe 3 out of a dozen or more of recipes in a book, and it would also follow the real-life/role-play approach (did you memorize a whole cookbook ever? or just the recipes you liked?).

The main point of discussion in my opinion is how to balance it, so you get some sort of a trade-off between focused reading and the current mechanic of 'read it until you finally manage to get the one recipe you actually need, like yesterday'.

Note: I have no idea how recipe learning works in-code right now.

My initial idea is that you should be able to select any recipe, and the time it takes you to grok that recipe with focused reading is proportional to the difference between skill you have and the skill needed to do that recipe. Each focused read then bumps your skill so that you will eventually get that recipe, but the trade-off is you won't learn any other recipe in the meantime.

Please discuss both ends (player - developer).

**Comment by Rivet-the-Zombie** [comment]
Sounds like a grand idea.

**Comment by KA101** [comment]
This is kinda implemented already, in that you can do recipes just by having the book skimmed and in the 6-tile crafting radius.  You don't actually have to have the recipe memorized; in fact, crafting the recipe using a book for reference gives a chance to memorize that recipe.

So if you skim books and then use them for reference, you'll (sooner or later) memorize the recipes you use.  Frankly, it might be simpler to just cut out recipe-memorization from reading entirely, and just have it derived from the reference material.

(I'm pretty sure we added a line in the Help to explain this, but I could be wrong or it might not be clear.  Thoughts?)

**Comment by KrazyTheFox** [comment]
> Frankly, it might be simpler to just cut out recipe-memorization from reading entirely, and just have it derived from the reference material.

I rather like this approach, myself. I've always found it a bit weird that I could learn everything there is about, say, metalworking just by reading. One must practice what they read to truly become an expert. Perhaps a trade-off might work here? Simple recipes could be learned through only reading, but more complex stuff requires reference material?

**Comment by drbig** [comment]
@KrazyTheFox & @KA101:

I'm aware of the `book near` mechanic but: Do I understand correctly that I'll need the ingredients for the recipe before I can try (and only then maybe learn it by doing it)?

**Comment by KA101** [comment]
Yes, and you'll need skill reasonably close to the learning difficulty (which need not be the difficulty to *succeed at making* the recipe) for it to show up.  Some books are easier to work/learn from than others.

**Comment by drbig** [comment]
@KA101 Aye, and I agree with that current mechanic. And with that I think the `focused reading` is not obsoleted. You can memorize and understand the steps given enough time without using/wasting anything (my in-game justification is that you read and contemplate what you need to be confident in doing that particular recipe you've been focusing on).

@KrazyTheFox Yeah, for a lot of stuff just 'learning it' is so-so. The question with all of this is in terms of 'balance' and 'it's just a game'.

**Comment by kevingranade** [comment]
I PRed removing direct memorization right after adding crafting-from-books,
but got shot down.  I think the outcome there was 'lower the learning rate
from reading, but don't remove it'.
Not particularly in favor of more focused memorization, both from an
interaction (grind for the recipes you've picked out as useful when you get
a book that has them, throw book away) point of view and from a UI point of
view (och boy, more menus).

**Comment by DavidKeaton** [comment]
You could have it scale on: difficulty of recipe, recipe's tools, or recipe's components; perhaps all three, to give you a factor to test against to see if it can be taught by reading vs doing.

**Comment by KA101** [comment]
If I was the one who shot you down, I'd guess it was thanks to insufficient experience with the new (now current) system.  Sorry it didn't work out.

**Comment by kevingranade** [comment]
If people's positions have changed I'm still in favor of simply removing memorization straight from books, or as DavidKeaton points out, limiting it to certain recipes.

**Comment by KrazyTheFox** [comment]
I'll put a vote in for limiting it. Complete removal of learning recipes from books doesn't quite make as much sense as I'm sure there's things you can pick up on without practice. Either way would be fine with me, though. I keep my books around til I've learned everything from them regardless.

**Comment by drbig** [comment]
Closing in favour of #12657.
