### ISSUE TITLE
Can't see more than 5 fuel levels in Vertical Vehicle Interface

### ISSUE THREAD

**Issue by RealZogzog** [CleverRaven/Cataclysm-DDA#11403]
When the Vehicle interface is set to 'Vertical' One can only see fuel levels for 5 types of fuels.

In my case adding a reactor (Plutonium fuel) on a 'car' already having Gasoline, Diesel, Batteries, Hydrogen and Water, replace the water level.

The issue is only present in Vertical mode, It display fine in Horizontal or Hybrid mode.

**Comment by KA101** [comment]
If that's the interface I'm thinking of, there's only so much room we have available in an 80x24 (minimum screen size, so we design to that spec) screen.

At one point we considered moving the fuels up but it turned out that doing so would impinge on the name field or somesuch and thus be a nontrivial overhaul, so I was content with five.

**Comment by RealZogzog** [comment]
I'll see what it look like on the minimum screen size, but I think there is some place for a second column, if not scrolling may be an option.

**Comment by DavidKeaton** [comment]
Hopefully scrolling is _always_ an option.

**Comment by kevingranade** [comment]
It is always an option, the only question is how much time you're going to
spend on the menu.

**Comment by RealZogzog** [comment]
Even on 80x24 there is place for at least an extra info line, so adding a line to the bottom part of the vehicle interact window work just fine ... that is until the next new fuel source.
![screenshot from 2015-02-27 04 08 56](https://cloud.githubusercontent.com/assets/11041453/6406948/5dfdef10-be37-11e4-86c0-4c8b279f12c4.png)


I think scrolling is a bad option in this case, because it should be 'easy to access' information, I don't want a 10key combo to check my water tank level.

It might be worth splitting the 'vehicle building interface' and the 'info/command Interface' that way It's more space for everyone, yeah.

**Comment by kevingranade** [comment]
So that would probably be a toggle at the top level, and ideally it would
remember the previous state.  It's a good idea, but requires overhauling
the whole menu.

**Comment by BevapDin** [comment]
Implemented by #13366.
