### ISSUE TITLE
ROT2 and ROT3 interrupt actions and sleep

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#11419]
Mutations from the deterioration tree use `hurtall` function, which triggers 6 separate "do you want to cancel action" prompts and ends sleep.
This doesn't make sense, because the rot is supposed to be gradual.

Other than that, their ingame effects are very minor for vast majority of survivors (easily countered by regular sleep). Could stand a buff, though that's a separate issue.

Is there any reason those are in `game::do_turn` instead of `player::suffer`?

**Comment by KA101** [comment]
ROT3 might keep one awake, as it's significantly noticeable.  Location is probably an artifact of their dating to Whales.
