### ISSUE TITLE
Mosin-Nagant infinite conversion kit loop

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#11420]
The Mosin-Nagant 1891/30 can be disassembled into the EBR variant which can be disassembled back into the classic variant, producing (apparently useless) conversion kits.

**Comment by KA101** [comment]
>_<  OK, that's a straightforward fix but not with the freeze on (needs a new item).  My mistake.

**Comment by aierce** [comment]
how about just remove the "reversible" tag for the recipies. it's much much easier than added a new 'barrel' item to the recipies

**Comment by KA101** [comment]
Can be looked into, sure.

**Comment by KA101** [comment]
Thanks, closing.
