### ISSUE TITLE
Advanced inventory index moves

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#11423]
When you have items visible in the advanced inventory that decay, the line you are currently on will change as time passes. This is on 0.B-3670-g61fee41

Steps to reproduce: 
1. Kill a creature (for example a zombie) and butcher it.
2. Drop 20 various items on the ground
3. Go to advanced inventory and select something below the zombie meat. 
4. The item you are currently hovering will change up/down as the meat decays.

**Comment by kevingranade** [comment]
I think you're skipping a few steps:
3.1 exit advanced inventory
3.2 wait long enough for the meat to rot
right?

**Comment by KrazyTheFox** [comment]
This is noticeable when moving items around, as moving items takes time. This is problematic when it changes your selection to something you weren't expecting.

**Comment by tivec** [comment]
Actually, you do not have to leave the advanced inventory for this to be noticable, as shown in the gif by @KrazyTheFox here. It seems like all the meat that dropped from monster X has different decay times, and as such stops stacking up. Perhaps it shouldn't be splitting the stacks unless one has changed state from fresh to old to rotten?
