### ISSUE TITLE
Several bugs involving the constructed charcoal forge.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#11431]
[Reported here.](http://www.bay12forums.com/smf/index.php?PHPSESSID=3baaba859c3d619e1efeb8c998462714&topic=121194.msg6070009#msg6070009)

>Using the construction menu to place a charcoal forge makes it buggy. You can keep dumping hundreds of charcoal in the forge and it only registers the last load you put in. Also, adding new charcoal overwrites the exiting total. However, you can just pick the forge up and reload it in your inventory as usual, then drop the item on the ground and use it for crafting as per normal. This is as of last night's version (2/27).

**Comment by narc0tiq** [comment]
This was also reported in #11021, modulo the workaround.

**Comment by narc0tiq** [comment]
(also, this seems to be a single bug -- "only registers the last load" and "overwrites the existing total" are basically the same thing, or am I missing something?)
