### ISSUE TITLE
CBM indicator (have it?)

### ISSUE THREAD

**Issue by hunakos57** [CleverRaven/Cataclysm-DDA#11432]
A simple idea to help the player to know what CMB he already installed. Since most of the CBMs only can be installed once it would be quite helpful when the player looking for the new ones with a bunch of CMBs installed. And the solution is as simple as the idea, basically it's just a color change, like books have.

**Comment by Zireael07** [comment]
Too quick to close - the PR hasn't been merged yet.

**Comment by BevapDin** [comment]
Implemented by #12478.
