### ISSUE TITLE
Hang when saving map

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#11440]
On 0.B-3726-g0fd876f, when I walk around the map and get the occasional autosave, the game freezes at this message:

![Frozen](http://i.imgur.com/cq80Kzc.png)

I can save using the key I've bound to saving and that works fine. To get past the frozen message, I have to press Ctrl+C to abort, restart the game, and load the save. Haven't found any issues with the save, but corruption might happen I guess?

**Comment by tivec** [comment]
There's also an addition to this - there's been a few crashes as well. Should mention that I compiled it myself. Could it have anything to do with the new compile flag ZLEVELS?

**Comment by Coolthulhu** [comment]
Should probably be fixed by #11441

The save function doesn't have a good way of soft-locking itself, so it probably happens after it's done and the game tries to address one of the deleted submaps.

**Comment by Coolthulhu** [comment]
Report if the hang still happens. A possible fix was merged.

**Comment by tivec** [comment]
I have played a bit with the newest merged fix, but haven't had the issue happen. I'll play some more today and report back.

**Comment by Coolthulhu** [comment]
It would originally hang if some of the terrain loaded was underground and some above ground.

**Comment by tivec** [comment]
I can confirm that this hasn't happened over many hours of playtime since the fix in %11441. We can close this issue.
