### ISSUE TITLE
View shifting does not work when going west/east in a vehicle

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#11450]
Here is a screenshot of me doing 80km/h going west:
http://i.imgur.com/3gN8aNi.png

Here is a screenshot of me doing 80km/h going north:
http://i.imgur.com/pOLvCyJ.png

**Comment by narc0tiq** [comment]
I'm pretty sure there's just no more "west" to show you -- that width looks about right for the full size of the reality bubble.

**Comment by Mattamue** [comment]
Square font? If not, the east and west view distances will look like they show more because the game can render more tiles in those directions if the tiles are thinner than they are taller.

**Comment by drbig** [comment]
@tivec Try the square.ttf - it's included in cata's distribution.

**Comment by Griffinhart** [comment]
I just did a manual count of tiles in the images - 57 tiles west, 31 tiles north.

So if anything, you're seeing *fewer* tiles going north than when going west.

**Comment by KrazyTheFox** [comment]
@Griffinhart 
The edge of the view distance is well off the screen to the north; counting the tiles from these screenshots is not even remotely an accurate comparison:
![x7a568zt](https://cloud.githubusercontent.com/assets/3086301/6477307/2b54b758-c1f0-11e4-8753-e437fe669ae7.png)

**Comment by tivec** [comment]
I did a few tests on this, and it is indeed because of the font dimensions not being square. Also, at a bit of further investigation, the view does shift but only by a few characters. Closing the issue.
