### ISSUE TITLE
Zeds following you upstairs ignore pathfinding

### ISSUE THREAD

**Issue by MattAmmann** [CleverRaven/Cataclysm-DDA#11451]
Zeds that are blocked by doors, and are following the character, magically get past the doors and emerge behind you when you go upstairs.

Here's the easiest way to reproduce this: Start in an evac shelter and go to the basement. Open the doors, and debug spawn a zombie in the chamber. Wait for the zombie to get within 2-3 tiles, and close the doors. Return to the surface, and the zombie will soon appear behind directly behind you.

**Comment by Coolthulhu** [comment]
Zeds going up/downstairs a rather hacky system - they use NPC pathfinding, which includes (among other things) the ability to open doors. If a NPC path exists and is short enough, the zed will follow.
This path length is quite short - 8 tiles in case of most zeds.

It will be removed relatively soon (when z-levels get mature enough).

**Comment by KA101** [comment]
Thought we broke out the door-use for folks who can't open 'em.  Hacky it may be, but if it lets the mooks cheat, it's a bug.  (They should have to smash the doors, and if not capable of it in the window, not follow.)

**Comment by kevingranade** [comment]
I think I might know what happened, it probably checked that it was
bashable, but that has become quite a bit more nuanced recently.  Short
term probably have them blocked by bashable obstacles, with luck we'll have
the z-level version of the feature before too long.

**Comment by Coolthulhu** [comment]
Disabled mon-stair bashing (and aquatic monsters following up/down stairs) in #11460
