### ISSUE TITLE
pulling aiming weapon crashes game

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#11453]
If a zombie technician pulls your weapon away from you while you are aiming with it, game will crash.

(well game crashed twice while firing at technicians, might be something else too)

**Comment by kevingranade** [comment]
Ooh thanks, that's a nasty one.

**Comment by kevingranade** [comment]
Did it crash or lock up?  I'm seeing lockups but not crashes.

**Comment by aierce** [comment]
the game freezes, mouses turning into spinning circle waiting icon, but the game doesn't close itself

**Comment by kevingranade** [comment]
Ok, the linked PR fixes that issue, thanks again for catching it.
