### ISSUE TITLE
Rework COMPILING.md

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#11466]
The file `COMPILING.md` needs some love.

It is missing the following information:
* How to build *without* debugging symbols (which tend to slow down C:DDA a lot) (`RELEASE=1`)
* The fact that by default, debug version is build, and the fact that this is slow and used for … well … debugging. ;-)
* The meaning of a couple of other `make` parameters which could be useful
* More distribution-neutral information, not every-one uses Debian or one of its derivates (This can be done by adding some lists of software names, ideally together with version numbers).

**Comment by drbig** [comment]
Given I've been acting as a guide for 'how do I compile' recently on IRC I'd be happy to look into this.

**Comment by drbig** [comment]
Proposed general guide along with consistent formatting: https://github.com/CleverRaven/Cataclysm-DDA/pull/11513

**Comment by KA101** [comment]
Merged.
