### ISSUE TITLE
Update MOTD for 0.C

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#11465]
The obligatory reminder: Don't forget to update the MOTD when you are about to release 0.C.

Also say “@Wuzzy” as a reply to this issue, or write me in IRC, as soon as the MOTD is ready for translation; I will then post a translation into German as soon as possible.
You may want to contact other translators as well.

**Comment by KA101** [comment]
There, now it'll get done.

**Comment by kevingranade** [comment]
Reminder is ok, I probably wouldn't have remembered tonight.

**Comment by kevingranade** [comment]
@Wuzzy2 I've posted a draft MOTD, which is unlikely to change much at #11469
