### ISSUE TITLE
Pull German translation for 0.C from Transifex

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#11464]
German translation is ready (100%) for 0.C, you may take it from Transifex (NOT Launchpad!).

I know most of this is automated, but I just wanted to make sure you pull in the German translation from the correct source.

I may make some updates to the string from time to time, to correct mistakes I find.

Please note that German is now worked on primarily on Transifex. So `doc/TRANSLATING.md` needs to be updated.
I hope Launchpad will be closed (for German, of course) to avoid redundancy, but I don't know who to contact.

**Comment by KA101** [comment]
@yobbobanana, I think this is you.

**Comment by VlasovVitaly** [comment]
I will push it on Monday, ok? I allway do this on Mondays.

So, you will push or motd/credits directly on github or will translate them on transifex and wait for my pushes?

**Comment by Wuzzy2** [comment]
GitHub, because the way MOTD and credits are handled on Transifex is broken by design. I explain it somewhere else.
Also, I already opened a PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/11484
