### ISSUE TITLE
Weird zombie master transformations

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#11476]
Zombie masters upgrading zeds can cause weird transformations such as:

`...zombie becomes a zombie!`, `...zombie becomes a zombie dog!`, `...zombie becomes a survivor zombie!` (drops better items)

**Comment by Zireael07** [comment]
LOL'ed at first two.

**Comment by Lain-** [comment]
I suspect it has something to do with PR #11458

**Comment by KA101** [comment]
Yep.  Zombie cops too, no less.  I'll whip something up.
