### ISSUE TITLE
0.C branch

### ISSUE THREAD

**Issue by VlasovVitaly** [CleverRaven/Cataclysm-DDA#11485]
We need 0.C branch to push some translations updates (motd, credits etc) to it.

**Comment by Zireael07** [comment]
You push translation updates to master branch. Everything not 0.C related is on hold/not merged in yet.

**Comment by VlasovVitaly** [comment]
Stil not released? Ok, I need this branch after actual release.
I need to push to this branch motd/credits and some translations update.

There 2 reasons for that:
Translations need some time to translate motd/credits, perhaps week may be more... And we push them after release.
And translations templates(lang/po/cataclysm-dda.po) taken from some github branch. We can set master branch for 0.C but master must be updated recently while 0.C should be stable.

**Comment by Zireael07** [comment]
0.C is not released yet. 

@VlasovVitaly, you should head over to Cata forums and post in the translations section that translations will take more than a week, in which case @kevingranade will probably do the 0.C release now and make a branch for you indeed.

**Comment by kevingranade** [comment]
Branch created, sorry about that, I'm going to update my release checklist to make sure it happens immediately next time.
