### ISSUE TITLE
Disappearing tracking device note

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#11494]
It's a small thing but, as of commit 2829, if you save and quit a game that has an active tracking device note on the minimap, the note disappears upon reloading the game. The tracking device remains active, but must be turned off and back on to restore the note.
##

**Comment by KA101** [comment]
Depending on where the tracking device happens to be, that's not such a small thing.  Thing's supposed to be there for folks who can't find their vehicle and need a note, which then is no longer there.

**Comment by railmonkey** [comment]
Right, and I'm one of them, trust me. For reference, here's where my tracking device is installed, if that's what you meant:

![tracking device location](https://cloud.githubusercontent.com/assets/6116024/6548764/1b387b00-c5da-11e4-8721-b0c81d1748d0.png)

**Comment by KA101** [comment]
No, was talking about the map functionality, sorry for the confusion.

**Comment by railmonkey** [comment]
Ah. That makes sense now. Not a problem.

**Comment by Oskar636** [comment]
Tracking devices are obsolete with the current "remember vehicle position" mechanic. I'm not sure they even work now because I can't figure out how to enable one.
Build 5892 windows 64bit console
