### ISSUE TITLE
Debug message spam from PR #11477

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#11509]
With the PR #11477, I'm being repeatedly spammed by the debug message "DEBUG: Submap at x,y,z has n fields, but n+1 field_count".

x,y,z can be any submap coordinate, and the field count seems to be always one higher than the fields. 

Obligatory screenshot:
http://i.imgur.com/9b08kOe.png

**Comment by tivec** [comment]
As shown in the screenshot of #11508, the field count is not always one higher than the fields.

**Comment by Coolthulhu** [comment]
#11516 should remove the spam. It doesn't remove the underlying problem though. The problem with fields not being cleared properly for some reason.
