### ISSUE TITLE
Furniture in hospital spawns inside walls

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#11500]
I believe this is/was known, but given my today's 0.C play:

Furniture still tends to spawn 'inside' walls in hospitals. I've got a counter sticking out the outer wall, and some metal racks (with items) sticking through internal walls. The tiles still behaved like walls: not possible to walk through/over, not possible to access items.

**Comment by drbig** [comment]
Already pasted in the mansion layout issue, but shouldn't hurt to add it here too:

NE:
http://i.imgur.com/zzuE1b4.png
http://i.imgur.com/AwEsHJo.png

NW:
http://i.imgur.com/aGwZHOH.png
http://i.imgur.com/6rW4rip.png

I can pick up items from the 'wall-fused furniture' but only if I Examine it (i.e. not via AIM); can't move into the tiles (i.e. they act like a wall). This world has been generated right around 0.C release, and AFAIR all the hospitals I've visited were broken exactly like that. I also believe similar off-by-one placement errors happen within the hospital (will upload a screenshot when I see one).

**Comment by sparr** [comment]
I've seen this bug, too. It's almost certainly a simple off-by-one somewhere in the relevant mapgen functions.
