### ISSUE TITLE
Text rendering issue ('boxes')

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#11501]
This has been reported on IRC as happening in ncurses build on OS X. It seems to also be present in tiles on Linux. Screenshots:

http://i.imgur.com/Hkd6RO6.png
http://i.imgur.com/OaMizcP.png
http://i.imgur.com/sTsZPGP.png (Linux, C:DDA 0.C, tiles)

Which suggests the actual bug is not related to OS, backend or fonts.

I believe someone suggested it might be 'control characters being displayed'...

**Comment by BevapDin** [comment]
Either the terminal emulator does not support Unicode (specifically UTF-8 in this case) or the font (of the terminal) does not contain a glyph for the ellipsis `…` and shows a default glyph instead.

There is an item "niño nachos with cheese", the name contains a Unicode sequence and not just plain ASCII as most of the other strings do. If this name is not shown correctly, it's definitely an Unicode issue.

**Comment by drbig** [comment]
I don't think this is UTF-8 issue (maybe still related though).

My testing:
http://i.imgur.com/Qgpldy2.png (Linux, 0.C, tiles)
http://i.imgur.com/Rq0wHpx.png (Linux, 0.C, ncurses)
http://i.imgur.com/oDvgd7h.png (Linux, urxvt as above, 'ellipsis'…)

But I do agree it looks like the box should be … instead.

**Comment by drbig** [comment]
Might it be a locale issue? Would that also be the case for the tiles build? Or maybe a bad codepoint for `…`?

I can test this as needed on Linux.

**Comment by BevapDin** [comment]
Easy way to test the Unicode issue: from the main menu go into the option menu, go into the second tab ("Interface"). The option information at the top will list the available languages, including some Asian once that *need* Unicode to be displayed properly.

In my konsole:

`LANG=en_GB ./cataclysm` - language names are not displayed correctly.
`LANG=en_GB.utf8 ./cataclysm` - language names are displayed correctly.

So it's properly (at least for the ncurses version) a problem with the terminal emulation. The terminal seems to not recognize the output of the program as UTF-8, but assumes it's ASCII. This btw. is with the system language setting in the options, so `gettext` and the translation system are ignored.

**Comment by drbig** [comment]
Same setup:

    drbig@swordfish:19 ~/Projects/cdda-dev $ echo $LANG
    en_GB.UTF-8

http://i.imgur.com/nrNhC7Q.png

I actually do use UTF-8 daily, and `fish` uses ellipsis when browsing command history and it works. My bet right now is on bad codepoint for ellipsis.

**Comment by BevapDin** [comment]
The ellipsis shows up fine for me:
![screenschot-2015-03-09-21-41-43](https://cloud.githubusercontent.com/assets/5095435/6564018/c09a8694-c6a5-11e4-8d98-6e9a8869569f.png)


Can you look at the end of src/catacharset.cpp, the comment there contains the ellipsis, does it show up correctly in your editor? What about the ellipsis in src/output.cpp at line 171? And another one in src/inventory_ui.cpp at line 20. This might just be a font issue after all.

**Comment by drbig** [comment]
Sure. It seems to work fine:

http://i.imgur.com/dav9Xng.png
http://i.imgur.com/xVpPpOP.png
http://i.imgur.com/S9bjTf2.png

**Comment by drbig** [comment]
Ok, some sort of new information:

http://i.imgur.com/YiiJMNJ.png

It seems to work in ncurses here. Why doesn't it work in tiles, or OSX?

**Comment by drbig** [comment]
That might be it (ellipsis width).

For locale settings on Unices: Maybe we should display a prompt like for insufficient terminal size if we detect a non-UTF-8 locale with a warning and possibly a choice to try force the locale to UTF-8 version?

**Comment by kevingranade** [comment]
That's less a warning and more a 'terminal' error (ahahahaha)
... ahem
Forcing a setting seems a bit extreme if it leaves the system in a
mostly-working state, but a warning with an option to try it sounds
reasonable.

**Comment by illi-kun** [comment]
This issue is superseded by #16254.
