### ISSUE TITLE
Debug HVAC mutation not toggling

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#11518]
Debug HVAC mutation (the first mutation in debug mutation menu) can't be toggled in the debug menu.

**Comment by KA101** [comment]
News to me, was working fine as of 02 March.

**Comment by KA101** [comment]
OK, some clever dev reset the list so now (for some reason that makes no sense to me) HVAC is the first one.  Same problem as has been around for a while, first mutation isn't toggleable.  Betting something isn't set.
