### ISSUE TITLE
Modded ammo types are always flammable

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#11520]
Item flammability for ammo is tested for with an ugly hack: `is_ammo() && ammo_type() != "hardcoded_type1" && ammo_type() != "hardcoded_type2"...`

Most (if not all) non-flammable core items are handled properly, but modded ones don't need to be. For example, Blazemod treats rocks as ammo, which results in some buildings burning infinitely.

Proper solution here would probably be one of:
* Adding some material to all firearm ammo (for example, "powder")
* Checking for cookoff/similar tags
* Adding a new tag basically saying "this item is flammable even though its materials aren't"
* (Semi-hacky) Marking entire ammo types as flammable/non-flammable with a json
* Making a big change to flammability system by moving burning effect data (smoke, how much it fuels, different effects depending on fire density etc.) to jsons thus nailing that huge if-else block in fire processing, possibly speeding up fire processing heavily

Checking for cookoff type tags would be very easy, but probably the slowest of them all. It would still be less of a hack than what we have now.

**Comment by kevingranade** [comment]
I'm in favor of that last solution as long as it's not me doing it ;)
But seriously, I don't think it would be that hard to go that route.

**Comment by Coolthulhu** [comment]
It wouldn't be hard, it's just that it would be work that someone would have to perform.

If it doesn't happen by the time I'm doing z-level fields (the actual issue itself, not just field_at(x,y,z) ), I'll probably do it then.

**Comment by aierce** [comment]
:O that's why craters are flammable
