### ISSUE TITLE
ups_drain bug

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#11526]
when using bionic ups, or advanced ups, firing a weapon will always cost only drain 1 charge.

this bug is located at ranged.cpp line 356 and 357

adv_ups_drain = std::min( 1, ups_drain * 3 / 5 );
bio_power_drain = std::min( 1, ups_drain / 5 );

the std::min function will always result in 1.

Don't know what's the intended result so not submitting a PR yet.

**Comment by BevapDin** [comment]
It should probably be `std::max`, so it always consumes at least one charge, even if `ups_drain` is only 1 and dividing it would yield 0.
