### ISSUE TITLE
Master branch fails to compile

### ISSUE THREAD

**Issue by KA101** [CleverRaven/Cataclysm-DDA#11530]
||=== Build: Debug in Cataclysm (compiler: GNU GCC Compiler) ===|
C:\Documents and Settings\---\My Documents\GitHub\Cataclysm-DDA\src\artifact.h|61|error: looser throw specifier for 'virtual it_artifact_tool::~it_artifact_tool()'|
C:\Documents and Settings\---\My Documents\GitHub\Cataclysm-DDA\src\itype.h|570|error:   overriding 'virtual it_tool::~it_tool() noexcept (true)'|
C:\Documents and Settings\---\My Documents\GitHub\Cataclysm-DDA\src\artifact.h|91|error: looser throw specifier for 'virtual it_artifact_armor::~it_artifact_armor()'|
C:\Documents and Settings\---\My Documents\GitHub\Cataclysm-DDA\src\itype.h|522|error:   overriding 'virtual itype::~itype() noexcept (true)'|
||=== Build failed: 4 error(s), 0 warning(s) (0 minute(s), 5 second(s)) ===|

Sorry, folks, guess I'm not mergetesting anything tonight.

**Comment by kevingranade** [comment]
Looks like fallout from #11275, I think I know or can look up the fix for this.

**Comment by narc0tiq** [comment]
Was this a clean master? I don't see any mention of a virtual explicitly-default destructor on either `it_artifact_tool` or `it_artifact_armor` in [src/artifact.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/artifact.h#L61).

**Comment by velddrinn** [comment]
Got the same problem yesterday.
![looser throw specifier](https://cloud.githubusercontent.com/assets/5492522/6591211/4b8c530e-c7cd-11e4-8f27-dee8d6ffe5d4.png)

**Comment by DavidKeaton** [comment]
on clang there are no compile issues?

**Comment by velddrinn** [comment]
OK, just had to update g++ and all the entangled stuff to get it working again.

**Comment by KA101** [comment]
>Was this a clean master?

If not, that's news to me: was the result of both the merge test and master branch, hence why I filed the issue.
