### ISSUE TITLE
Warning when loading incomplete/outdated tileset

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11539]
While going through all of the tilesets I found that some of them are missing various items/tiles. I'd love to get warned of that when I load them, rather than finding out an hour later when I've gotten used to the tileset (because I'm probably going to stop using it when I discover it's missing things).

It seems like all the necessary data is available when the tileset is loaded. The tileset's json describes every id it has a sprite for, and the item/tile/etc data files enumerate every id that needs a tile. I'm submitting this as a suggestion, and if it gets positive feedback I'll try implementing it.

**Comment by narc0tiq** [comment]
Agreed, that would be useful. It may also be worth including a note about whether the tileset has fall-back tiles or not -- those that do should still be useful, if the player doesn't mind the occasional letter instead of a monster graphic, or the like.

**Comment by sparr** [comment]
@narc0tiq I do see a 'missing tile' tile in some of the tilesets. A magenta (/) in one, a white skull and crossbones in another. I have not seen a tileset that falls back to letters; is that possible?

**Comment by narc0tiq** [comment]
I believe so, but I don't play with tilesets, and I may be remembering something else. Best bet would be to check the code and see if there's any affordance for it.

**Comment by BevapDin** [comment]
Tilesets are nearly *always* incomplete. You would get a warning as soon as somebody adds a new item / furniture / terrain / monster / etc.

And what about items from mods? Those might not be loaded (when you play in a world without the mod).

However this seems to be usable for tileset creators and for a stable version (with stable content).

> fallback tiles

Those are in the tileset configuration, look for the "ascii" entry (because it's the fallback to ASCII, it displays the stuff just like it would be in a terminal).

**Comment by KA101** [comment]
Yeah, BevapDin's point is well made.  This would be counterproductive in experimentals, as it's impossible for tileset artists to keep up with content dev.  (That's why we have content freezes as part of the release process.)

Tie this to a release flag, and sure, could work; otherwise, no point.

**Comment by kevingranade** [comment]
How about some kind of completeness summary?
60% unique tiles
20% generic tiles
10% placeholder tiles
10% ascii fallback tiles

**Comment by KA101** [comment]
If automated, reasonable.  Otherwise, maintenance nightmare.  But you knew that already.  ;-)

**Comment by sparr** [comment]
I gave this a quick try and had trouble getting ahold of the tile types (terrain, items, fields, etc) at the time the tileset is loaded. If someone could point me towards the right object and members/methods, that would be a great boon.

https://github.com/sparr/Cataclysm-DDA/commit/6ec41b258349081398b272784d2737d48c4ed7c0

**Comment by BevapDin** [comment]
World data is loaded only when you load a save. Before that, the game does not know which mods to load and therefor does not load anything at all. With your code, try the option menu from within a loaded game.

**Comment by sparr** [comment]
@BevapDin that seems so obvious in retrospect. Thanks.

**Comment by sparr** [comment]
I could still use some pointers for things other than terrain. items, fields, anything else that can have a tile (and I don't even know the full list of what those things are).

**Comment by BevapDin** [comment]
> anything else that can have a tile (and I don't even know the full list of what those things are).

Look at all the stuff that `cata_tiles` uses, it's all in that class.
