### ISSUE TITLE
tweaking a mod?

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#11545]
What is the etiquette on PR for other people's mods. I think it would be really awesome if UNARMED_WEAPON tag is added to the wrist dread from icecoon's weapon pack.

**Comment by KA101** [comment]
If icecoon was around, it'd be nice-but-not-strictly-required to ask xyr input.

Xe's not been around, so far as I know, so just have at it.  DDA's licensing lets folks mess with the code without asking permission, that's pretty much the point of CC-BY-SA.
