### ISSUE TITLE
Flintlock rifle / pistol do not give skill when used.

### ISSUE THREAD

**Issue by WarRage333** [CleverRaven/Cataclysm-DDA#11548]
Rifle nor pistol give skill to marksmanship or their respective category (handguns for pistol etc)

I did not test the flintlock carbine but i assume its the same for it.

**Comment by kevingranade** [comment]
My first guess is that they're simply too inaccurate, in which case it's
working as intended.

**Comment by graysage1** [comment]
I've never made flintlock anything, so I don't know, but does the game inform the player when the weapon is not accurate enough to serve a learning tool?  The game should say something like "This weapon is too inaccurate to be able to improve your marksmanship."  That way the players will not be confused and will understand right away that it's intended to be that way.  If it's already like that, please forgive this comment.

**Comment by IFailAtGaming** [comment]
@graysage1 yes it does i can't remember the exact message but it yelled at me for trying to improve my skills with just a revolver

**Comment by WarRage333** [comment]
I went back in the game and tried to see if the message appears when i used it. 20 shots later no skill gain nor the message saying skill is not gained. So i guess that it then.

**Comment by BevapDin** [comment]
What version do you use?

I tested this with a flintlock rifle. It gives experience at level 0 and 1 to marksmanship and riffle. Upon level 2 it prints (occasional) the message "You'll need a more accurate gun to keep improving your aim."

**Comment by WarRage333** [comment]
0.C Tested at 3rd and 4th marksman level and rifle 3 and 4

**Comment by graysage1** [comment]
>I understand it should not give skill at higher levels

I am confused.  So not only do weapons fail to increase the skills if they're too inaccurate, even if your marksmanship is 0, but they also have a skill cap as well?  If that's true, I can see how it can make sense (after all snipers probably don't get to their high level of skill with rusty muskets).  Maybe weapon descriptions should contain skill level caps, and the weapon being too inaccurate to help one practice the shooting skill should probably be announced through a message during its use?  Or maybe all this info can be dynamically generated in the weapon description, or both?  I don't know what is the best way.  I think the player shouldn't be kept in the dark about this game mechanic.  It seems kind of an important and justifiable game mechanic to me.

**Comment by KA101** [comment]
Quick check: what PE stats are people using?  That influences the ability to skill up as well.
