### ISSUE TITLE
Submap error

### ISSUE THREAD

**Issue by Nick0010** [CleverRaven/Cataclysm-DDA#11541]
Build 0.C bd8ffc3
the game freezes with the debug message:
submap at 5,5,0 has 3 fields but 6 field_count
i have tried several different saves and even different versions. i get the same error on the latest stable build as well. usually an hour or two into the game. Any known fixes?

**Comment by KA101** [comment]
Yes, waiting on mergetest, which will be happening tonight.  Thanks.
