### ISSUE TITLE
UI discrepancies between ASCII and tiles w/ hallucination and scent vision

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#11549]
This is my first time using github to leave a bug report, so if I am not following github's or cdda team's best practices, please let me know.

This bug is currently always duplicatable with the experimental build cataclysmdda-0.C-2856.zip released on 2015-03-12.

What happens:

Hallucination from the visual disruptor bionic produces virtually no effect when using MShock24 or RetroDays20px.  I get similar results from the schezophrenic trait as from the bionic.  Activating scent vision bionic seems to have no discernible effect when using MShock24 or RetroDays20px.

When using ASCII hallucinations function very obviously and very severely (I think they should be toned down, personally, because when they work, they work like crazy, pardon the pun).  Sometimes even the location of your character gets lost when hallucinating in ASCII.  Also scent vision bionic produces an obvious visual effect depicting one's scent cloud.

What should happen:

There should be parity between tiles and ASCII when it comes to game features.

To duplicate:

Start a character with a Bionic Monster background.  Activate scent vision or just wait for the visual distortion hallucinatory effect to kick in.  Once scent vision and/or hallucination effect is active, switch between tiles and ASCII and observe the differences.
##

**Comment by KA101** [comment]
Pretty thorough report.  Thanks.

**Comment by Night-Pryanik** [comment]
While sight pixelation is no more, scent vision in tiles mode doesn't show anything.

**Comment by mlangsdorf** [comment]
Did #28789 resolve this?

**Comment by DaviBones** [comment]
Just tested, active Scent Vision bionic does not bring up the debug scent numbers added in #28789.

**Comment by int-ua** [comment]
I think this can be closed as scent vision was obsoleted and tilesets missing some sprites for hallucinations should not be tracked here. Both MShock descendant and RetroDays currently reside in https://github.com/I-am-Erk/CDDA-Tilesets/tree/master/gfx and there is an issue tracker available.
