### ISSUE TITLE
Hitchikers don't start with shoes

### ISSUE THREAD

**Issue by i2amroy** [CleverRaven/Cataclysm-DDA#11553]
As title. I know we're referencing hitchhiker's guide to the galaxy but they should probably start with at least slippers (if not basic old shoes, which I'm pretty sure he had in the movie at least).

**Comment by graysage1** [comment]
Also, if we want to go all the way, then if you choose a Hitchiker as your background, then the NPC that greets you if you have the static NPCs turned on, should probably be Ford Prefect.

https://en.wikipedia.org/wiki/Ford_Prefect_%28character%29

**Comment by KA101** [comment]
Nah, Ford Prefect is probably too much IP reuse.  Maybe have The Darkling Wolf show up or something?

(Provided he'd actually want to?  Dunno if we've a backer who'd qualify as an experienced Cataclysm-survivor.)
