### ISSUE TITLE
Read time in book descriptions is confusing

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#11556]
When I find books they often contain a line in the description that says something like "This book takes 7 minutes to read."  Or "This book takes 20 minutes to read."  When I first saw this, I expected it to be literally true in terms of in-game time.  20 minutes is nearly instant.  It's only four 5 minute ticks.  Of course the reality is quite different.  The reality is that some books take multiple in-game days to read from start to finish, and yet they say it takes 20 minutes to read them and such.

So I think the simplest solution is to just remove the misleading description from the books.  However, it would be nicer if books contained a more intuitive estimate of how long they take to read from start to finish, or maybe an estimate of how long it takes to gain 1 level of skill from said book, or how long it will probably take to learn all the remaining recipes in the book, etc.

This is a minor issue for me.  I just noticed it and thought it was weird.  And I still don't know what those read times in book descriptions refer to.

**Comment by KA101** [comment]
Reading is in cycles, not start-end.  Chapter books are per chapter, and each one is a shot of morale so you might want to spread 'em out.  Textbooks/recipe books are for studying the thing.

I'm pretty hyperlexic IRL and a day for a book is about right, if the book's good.  Otherwise, 2-3.

**Comment by graysage1** [comment]
>Reading is in cycles, not start-end.

OK, but what is a "cycle" from a player's perspective?  Imagine that you're a player who is not at all familiar with the game implementation.  So the term "cycle" probably has little or no meaning to you, right?  So 7 minutes per cycle means what exactly?  How many cycles are in a book?

As an avid reader myself I've never thought about reading books in terms of cycles.

I think all game objects descriptions should be player-oriented and not developer-oriented.  The term "cycle" probably means nothing to a typical player.

I am mostly talking about skill manuals here, btw.  So let's say I pick a ham radio manual, and it tells me it takes 7 minutes per cycle (I just made that up), what does that mean?  On the other hand, if the book was described as "This ham radio manual contains 20 chapters and it takes 7 minutes to read each chapter." that would be eminently understandable, imo.

It even doesn't say "per cycle."  It only says "This book takes 7 minutes to read."  The end.  I don't think there is "per cycle" verbiage in the description, and if there was, it would be confusing.

**Comment by narc0tiq** [comment]
Agreed that the phrasing should be "Each chapter of this book takes about X
minutes to read". For regular books, the chapters are the number of
charges, shown in parentheses after the book name in your inventory.

Skill books contain a flexible number of chapters (or, alternatively, an
infinite number thereof) -- you can keep reading them forever.

**Comment by graysage1** [comment]
>Skill books contain a flexible number of chapters (or, alternatively, an infinite number thereof) -- you can keep reading them forever.

Right now maybe the description is fine for books with charges, but not for manuals.  A ham radio manual cannot take just minutes to read (and understand).  Also manuals stop when events happen or when a certain amount of times passes?  When you still have skill points to learn, I know the game stops reading when you've learned a skill point.  But when you just have some formulas/recipes to memorize, it also eventually stops, but it's not clear when.  And the game tells the player that this process can be stopped manually too.  So as far as skill manuals go, it's not obvious what the read times mean.

Imagine if the skill book said something like, "It take 4 hours to gain a skill level given your reading proficiency."  Not only would this be more intuitive to a typical player, imo, but it would also possibly help to plan your game day.  When I read something like "It takes 7 minutes to read this book" I have no idea what to think about it.  Is it easy to read?  Hard?  No clue.  I guess I just have to read it and find out.  It's a case where the description is not descriptive.

If we're talking about books with charges and I takes exactly 7 minutes to use up a charge, then it completely makes sense in that case, because the game stops the reading process as soon as the charge is used up.  But a similar description makes little sense for skill manuals, imo.

**Comment by Zireael07** [comment]
Agree with @narc0tiq
