### ISSUE TITLE
Game balance: unrealistic hunger and sleep deprivation implementation.

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#11550]
Currently both hunger and sleep deprivation have a similar flaw: they act as bank accounts when in the real world neither hunger nor sleep deprivation function the way bank accounts do.

This was the case with the 0.C stable release, and I didn't have the time to test it with the latest experimental builds yet.

What happens:

The game seemingly tracks one's hunger and sleep debts as though they were bank accounts.  So when you get into a heavy sleep debt, you have to sleep 3 times to get back to well rested.  The issue is much worse with hunger.  When you get into a heavy hunger debt, you have to eat for what seems like days to get back to satiated, which is not how the real world works.

What should happen:

It should take one good meal to get back to satiated, regardless of how long you've been fasting, and it should take about 1 good night's worth of sleep to get back to well rested status regardless of how long you've been staying up.

I've fasted before, btw, and so I speak from experience.  When fasting for a week, just having a normal meal breaks the fast and makes one satiated in the sense that one doesn't want to eat anymore and one is satisfied.  However, for about one day following a week's fast, one's physical condition is somewhat weakened.  This is a mild effect and it doesn't prevent one from doing what needs to be done.  It just makes one less happy let's say and less enthusiastic about doing things.  It's a kind of "blah" feeling.  Well, this is how it worked for me anyway.  I bet people who are more experienced with fasting get over it even better and smoother than I had.

I've also stayed up for 3 consecutive days, and it doesn't take 21 hours of sleep to catch up from that either.  With sleep maybe one needs more sleep than usual to catch up, but it's not like a bank account.  I'm thinking in the worst case you'll need about 50% more sleep time compared to normal.

The point is, sleep and hunger do not work like bank accounts in the real life, and I don't think that's how they should work in the game either.  The problem is worse with hunger.  Eating for days and days to get back to satiated status is not realistic, no matter how starved you have been before.  I think the issue with sleep is relatively minor by comparison.

**Comment by Zireael07** [comment]
On eating, see #11514.

On sleep, good points, the question is when someone codes it.

**Comment by eliotcougar** [comment]
I think the idea behind a better implementation of hunger will need additional parameter, let's call it nourishment (current "healthiness" parameter works more like immune system status)...
If you keep yourself well fed, nourishment is maximum and doesn't have any effect...
If you start starving (Very hungry and lower), each hour you'll lose "nourishment" at some rate depending on your healthiness, thirst, fatigue and other statuses. Exactly which parameters to track here is another big topic...
If you are not starving (Hungry and higher, not inclusive) "nourishment" increases...
Character gains cumulative negative effects from both "hunger" (short term, easy to solve) and "nourishment" (long term, needs time to solve)...
The amount you can physically eat and drink should be limited of course... At the same time, the amount you need to eat should be lower, and should not depend too much on current Hunger... "Hungry" and "Starving" statuses must be solvable by the same amount of food...

The idea is that after starvation (if you didn't die), your body will be weak, and you'll have to spend some time "not starving" continuously to recover...
Hunger may have effect on Focus and Speed, whereas Nourishment should have effect on Focus, Speed and also on basic attributes...

Sleep deprivation may be added simply as another condition, similar to "Schizophrenia" or "Mood swings"... Almost copy-paste... Auditory hallucinations are mandatory...
Almost any amount of sleep deprivation should be solvable by good long comfortable sleep... Additional short-term hangover effect may be added after removing "sleep deprivation" (-1 Int, -1 Per)...

(End of the line crazy idea: track sugar/protein/fat intake to determine nourishment and healthiness)

**Comment by graysage1** [comment]
I mostly agree with your reasoning.  However, if your body has stored fat to burn, it's not going to burn muscle mass.  In other words, the negative long term effect you're probably thinking of is not going to happen unless something very epic happens.  A single 7 day fast isn't going to damage the body.  You would need to be undereating routinely for a long time to notice muscle atrophy and similar effects.  People generally don't go from chubby to anorexic in a week of fasting.

But one thing is clear, it makes no sense that you have to eat and eat for days and days to get back to non-hungry status after you fasted for some days.  It just makes no sense whatsoever.  Our stomachs are not bank accounts.  Maybe our stored body fat is closer to a bank account.

**Comment by eliotcougar** [comment]
Right now 1 day in the game is approximately equal to 1 week real time, given the default 14 days per season setting (annual-time)... However, all actions and crafting recipes are measured in game-time which is 7 times faster than annual-time... Physiological effects may be accounted on annual-time scale and not the game-time scale... That's complicated, unless we converge both to the common denominator...
Anyway, there should be an incentive to avoid starvation in the game mechanics... Starving for the whole season (3 months) is not the same as starving for 14 days...

**Comment by eliotcougar** [comment]
There's another way we can look at it...
For example, eating a portion of woods soup, two hamburgers and four apples during an in-game day to fill your Hunger to full may be imagined as a real-world alternative to "This week you were eating some soup, a couple of hamburgers and mostly apples during the week and it was enough. No starvation penalty."

**Comment by KA101** [comment]
Folks, you mind moving this over to the discussion Zireael linked?  Thanks.
