### ISSUE TITLE
Block panning (for map, peek etc.)

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#11555]
Enable a block/jump panning: e.g shift/alt/whatever + arrow = move 10 tiles in that direction.

This should be uniform for wherever panning is a thing, and while we're at it we can make the jump distance configurable in interface options.

**Comment by BevapDin** [comment]
Is this issue in any way similar to #7100?

> This should be uniform for wherever panning is a thing, and while we're at it we can make the jump distance configurable in interface options.

Options -> Interface -> Move view offset

**Comment by drbig** [comment]
@BevapDin Similar.

The current 'change the default from 1 to something sensible' and 'it only works with peek around' and 'you need to press f first' is rather far from what I meant.

I'd leave it as it is if it at least worked with the map view.

**Comment by drbig** [comment]
And regarding ncurses: the point would be to have consistent modifier+arrow for block jumping. Or anything that is consistent and explained.

**Comment by DavidKeaton** [comment]
I think the shift+hjkl (or any movement key) should be enough where panning should be an option.

**Comment by drbig** [comment]
@DavidKeaton Indeed: mod+movement_key - to be precise & indifferent.

**Comment by DavidKeaton** [comment]
fair enough! :-)
