### ISSUE TITLE
snow can partially "erase" blindness

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11565]
I blinded myself with a flashbang. In one particular square part of the screen, I could still see snow falling. As the snow fell, it "erased" the blindness one tile at a time, leaving this view:

https://www.dropbox.com/s/klz4tdcofhe3b1s/Screenshot%202015-03-13%2014.52.33.png?dl=0

I blinded myself again and it happened again for that same chunk of land. The vehicle visible at the bottom of the screenshot is at/near the center of the revealed area. I can't see anything immediately unusual about the vehicle, though.
##

**Comment by KA101** [comment]
Problem with the precip and other such visual effects: this was reported for hallucinations IIRC and we deemed it acceptable there.  For precip, no, not so much.

**Comment by sparr** [comment]
could be related to #11621

**Comment by Night-Pryanik** [comment]
Wasn't able to reproduce on 0.C-6372, Win 10 x64, nor tiles neither curses.
