### ISSUE TITLE
Info about boots' ability to hold knives

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#11560]
I think we should give information to players about boots' ability to hold knives in item description. I played a lot and learned about it totally by chance (looking at second screenshot at this (http://smf.cataclysmdda.com/index.php?topic=5745.msg226556#msg226556) post) because there is no other source of information about it. 
3 variants of doing it:
* Manually add text like "You can hold a knife in this footwear" to every footwear description;
* Make a flag like [BOOTS] and add aforementioned text to this flag, then add this flag to all appropriate footwear;
* Add check for iuse_function_list["BOOTS"] or iuse::boots (don't know what is better and if it even possible) in item.cpp with aforementioned text.

**Comment by graysage1** [comment]
Yes please, assuming that screen cap isn't a fluke, lol.  In general *informing the player* seems to be a recurrent theme in some of these issues.

Can all boots do this or just the military?

**Comment by Night-Pryanik** [comment]
All boots with "use_action" : "BOOTS" string in item.cpp can do this.
I made it myself by going the second way (made a flag "BOOTS", then added this flag to all appropriate footwear, then added text with check for this flag in item.cpp). PR'ed (https://github.com/CleverRaven/Cataclysm-DDA/pull/11566)
