### ISSUE TITLE
Change starting map to center on "home", not spawn?

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11572]
It doesn't make sense for an evacuee to already be familiar with the area around their shelter. They should, instead, know the layout around the town they are from. For some scenarios/professions it might even make sense for the starting map to not show anything, or to show an area that does not contain the player's starting area. Perhaps professions and/or scenarios should be able to dictate something about how the starting map explored-ness is determined?
##

**Comment by Snaaty** [comment]
For now you can reduce the initially visible area with the debug options before starting your game.

**Comment by KA101** [comment]
Yeah, not trivial to determine "where this survivor is from", I'm afraid.  Could be a local town, could be the other side of the state, depending on the story, profession, etc.

**Comment by sparr** [comment]
I'm thinking professions might have a "what part of the map should be revealed at spawn" field, with a handful of possible options, including:

N squares around spawn, as it is now

N squares around nearest town (this would be the most common, simply assuming evacuees/etc are sent to a shelter near their home town)

small-N squares around the nearest of a specific kind of building (probably the kind they start in)

just the roads in a certain area (town, multiple towns, ??)

**Comment by kevingranade** [comment]
Needs a lot more detail and someone interested in tackling it, as such I'm closing.
