### ISSUE TITLE
Reloading when more than one type of ammo is available

### ISSUE THREAD

**Issue by AndrasZodon** [CleverRaven/Cataclysm-DDA#11588]
In the stable release of 0.C, if you have more than one type of ammunition available for a firearm, for example .45 ACP and .45 FMJ, and you try to reload a MAC-10, it will ask you to choose which type of ammunition to use, as expected.  However, when you select one, you will be given the message "Out of ammo!".

Working around this requires dropping all types of ammunition usable by the weapon besides the type you wish to load.

EDIT: Whoops, thanks for adding the Bug label, this is the first time I've used github.

**Comment by KA101** [comment]
I've not encountered this with crossbows, the only time when I've had multiple ammo types for a weapon, at the same time, post 0.C.  I'm on WinCurses.

What OS/engine are you using?

**Comment by AndrasZodon** [comment]
Win7, Windows SDL/Tiles.  I've experienced this only with firearms, I'm fairly new to the game and haven't had a chance to use crossbows, bows, or energy weapons yet.

I've specifically encountered this bug with MAC-10's, Survivor Six-Shooter, L2031 Enforcer, SIG Pro .40, S&W 610, MP5, and RM2000.  Ammunitions involved have been various .40 types, various .45 types, various 9mm types, and various 8x40mm Caseless types.

**Comment by KA101** [comment]
OK, so it's all multishot guns.  Thanks.

**Comment by AndrasZodon** [comment]
I'm also getting this issue with a Pneumatic Rifle I found on a survivor zombie. When it is loaded with Marbles, and I possess pebbles but no marbles, it will say "Out of ammo!" if I attempt to reload. I unloaded the gun (getting the marbles out of it) and attempted to reload.  I was prompted to choose marbles or pebbles, and either option outputs the message "Out of ammo!" and does not load the gun.

**Comment by MattAmmann** [comment]
I can't reproduce this in 0.C stable or the most recent experimental, using the guns and ammo Andras mentioned. Tested on experimental [SDL] and stable [SDL].

Andras, are you using any mods? Uploading a .zip file with your save might help diagnose the issue.

**Comment by AndrasZodon** [comment]
Oh, right. Mods. I've experienced this over different saves, but I think 

![](http://i.gyazo.com/0a8ab3a5b07b09f872f83c278b85a87a.png)

my default mods are the only ones that could be affecting it. I'm pretty sure I've had Boats enabled on every single save I've made, and probably zombie reviving. Others vary. Specific save later if necessary, don't have the time atm.

**Comment by KA101** [comment]
OK, I'm betting the veh additions pack is causing the trouble: it uses some additional ammo types and that's caused confusion in the past.

**Comment by FireCrow1973** [comment]
hi @AndrasZodon don't know if your still involved with this issue.
Kan i just ask you some things about this problem.
when the prompt appears and you select the ammo, are you hitting Enter/Return or are you hitting the Right arrow key?

**Comment by AndrasZodon** [comment]
I haven't played C:DDA for a week or two, but I still have the save I was playing on and same version, so I'll try both later.  Sorry for not responding sooner.

**Comment by FireCrow1973** [comment]
No no, thank you for replying!
i'm suspecting its an issue for all the reload actions, or the reload prompt.

**Comment by AndrasZodon** [comment]
Haha! Yeah, it only happens when I confirm ammo selection with the right arrow key. I almost always confirm selections like that on menus with less options like an ammo select.  Both the enter key and key-shortcut work properly.

I tested this with my trusty pneumatic rifle using Marbles and Pebbles, but I assume this issue will be identical for most or all weapons.

**Comment by mugling** [comment]
> However, when you select one, you will be given the message "Out of ammo!".
> Yeah, it only happens when I confirm ammo selection with the right arrow key

Now displays the correct message *"Never mind"*
