### ISSUE TITLE
game idea: a real world survival tactic allows one to get potable water from dew

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#11583]
[Source](http://wildwoodsurvival.com/survival/water/men72/index.html):

>Collecting dew is probably the *simplest, and safest*, way to obtain potable water in a survival situation, and it's the method I most frequently use and recommend to my students.
>
>The only equipment needed to gather dew is a rag or piece of clothing ... or a handful of dried, nontoxic, grasses. Just wipe the moisture from the landscape and wring the liquid into a container or your mouth. Collect the condensed droplets from grass, rocks, leaves, and even sand. (Do not, of course, gather moisture from poisonous plants, near a highway or a city, or in area that's been sprayed with chemicals.)
>
>You'll have to get up early and work hard (dew doesn't stay around very long!), but don't let the simplicity of this method lead you to believe that it's ineffective. Students of mine have collected more than a quart a day in some of the hottest Southwest deserts ... and at my farm in New Jersey, two pupils once used this technique to fill a 20-gallon garbage can with water in less than two hours!

So all one needs is a cotton something or other, a cotton towel would probably be ideal.  One needs to wait till morning.  Brush the cotton item along the grass or sand.  The cotton item gets wet.  Wring the cotton item into a water container.

I'd prefer something like this over having to drink from toilets.  Every toilet invariably containing 24 units of water is not 100% realistic, imo.  However the water situation doesn't have to be a nightmare if CDDA were to implement this survival tactic.

What's more, it appears that all water thus collected is potable and doesn't need further purification.  The only downside is that one has to wait for a 2 hour window in the morning.

And if it's raining, or been raining recently, it should be trivial to collect rain water off the grass and other natural surfaces in the same way as collecting dew in the morning.  In fact the game already produces a wet towel if it's 'a'pplied to wipe off the rain wetness.  It would only be a small step to implement wringing it into a water container instead of allowing it to dry.

"Simplest, safest" implies it should be an entry level survival skill too.

It's just an idea.  What do people think of this?

**Comment by KA101** [comment]
Aside from handling dew presence (one tile of grass should not have infinite dew during a two-hour window, and otherwise be dry: another inviso-field?  hot air has had its share of problems), sure, no argument on my end.

**Comment by John-Candlebury** [comment]
Seems like it would trivialize getting a water supply too much for may tastes, as I like the few situations in which you are forced to risk your life for some water (Forex: playing with increased monster spawns).

Perhaps add a small survivor skill requirement of 2 or 3 .

**Comment by graysage1** [comment]
The article I'm quoting says the water is potable, but what if there is dirt on the grass, like say animal droppings, which are known to spoil water, which get caught up on the towel together with the dew?

I'm not the one to argue with a survival expert, as I think Tom Brown Jr. probably knows what he's talking about, but maybe for the sake of game balance the water could be unclean and not yet ready to drink.

Another way to balance it might be to require this process to be somewhat laborious.  It would make it less fun, which might be detract from the game.  Maybe in order to wet the towel on the grass/sand one will be required to walk a number of steps and then the water wrung from the towel will be a small amount?

The amount of dew can vary by location, season, and weather.  Maybe on some days there isn't much dew to collect.  But since it rains often in CDDA's world, it seems like wet grass will be relatively plentiful in the current implementation, regardless of the morning dew situation.

Also in the winter maybe the dew doesn't form on the snow so this method will not work as is (gliding the towel over the snow?).  However, collecting snow and melting it and then boiling it is a standard tactic in winter survival.

It's possible to implement a world in CDDA that's harsher than Earth and then explain it (away) by saying that, well the alien goo has changed the ecological balance and now the dew just forms much less, but this will be hard to argue when it rains all the time.  If the rains were toned down, it would open the argument that maybe the dew is not all that plentiful in the morning, but then it would also increase the solar power time and manufacturing quality light time.

As it stands it makes little sense that I can put a funner outside in the rain and collect water, but I can't glide the towel over the wet grass and wring it.  It also makes no sense that funnels gather water, but if I drag a bathtub outside the apartment, it fails to collect any rain water.

I realize people want a world that's harsh and inhospitable, but it also should probably be logically coherent.  It's not logically coherent that funnels work but bathtubs don't, and that you can wet your towel simply by applying it during the rainy weather, but then can't wring it into a container and have to wait for it to dry.

So I think if people really want CDDA to be closer to Dune (by Frank Herbert), *the whole world* has to be coherently and consistently setup that way.  But in Dune they have still suits and they reclaim water from corpses by burning them and collecting vapor, etc.  In other words, even in Dune people know how to survive efficiently.  So environmental harshness only goes so far, because people will always resist harsh environments and will always innovate ways around trouble, imo.

Just some thoughts.  I think the game is fine as is, but it seems like the water situation is not logically coherent with how the world presents itself.  Maybe it's a necessary sacrifice for the sake of fun gameplay.  I'd prefer a more realistic/consistent simulation as far a water collection goes.  If it rains often, there is water aplenty.  Then why can't I get it?  Why is it hard?

I can understand bionics being made very hard to get, because they are technological marvels and are probably heavily guarded, but water?  I agree that I should be made to endanger myself over *something* in CDDA's world, but I am not sure if water is that something.  Just my 2c.

**Comment by Zireael07** [comment]
+1 for the water possibly being unclean.

**Comment by graysage1** [comment]
I just thought of another realistic way to possibly balance this idea: maybe scraping cotton along the grass and sand imposes a relatively heavy wear on the item?  This could be implemented as an item receiving damage as if from a zombie, maybe based on a percent chance per tile or per activation.  That way if you constantly use your towel to collect dew or rain water from the ground, maybe after a week of game time the towel would be destroyed assuming it wasn't maintained via tailoring.

The problem is, while this is probably realistic, it's also possibly going to increase tedium.  I'm just throwing it out there as an idea anyway.

**Comment by graysage1** [comment]
Another potential way to balance this method: maybe the act of wringing the water is relatively strenuous, and so this possibly makes one more tired (sleepy) and slightly more hungry.  This penalty could be adjusted based on strength.

Another idea: if it's raining, it should be possible to spread a cotton sheet or a towel on the ground and just allowing it to get wet in the rain.  This should not impose any undue wear and tear compared to dragging cotton items along the various surfaces, but will only work in the rain.

Another idea is to use a cotton sheet similar to a water funnel like so: bury/plant one tall stick into the ground, and two shorter ones and tie the three corners of a sheet to each stick such that the sheet is sloped at a 45 degree angle toward the ground, and the last corner of the sheet is hanging loose.  This loose corner can then be inserted into a water container.  Then when it rains, this setup will gather water and move it via capillary action into the water container.

Another thing that should be possible is to simply collect the water that rolls off the roofs.  I'm assuming every building was at least originally built with a roof and functioning rain gutters.  Maybe the rain gutters have to be cleaned out before this can work, but the roof of a building together with a system of rain gutters is much more efficient than any water funnel I can imagine.  What could stop this from working is if the roof was damaged, or the rain gutters were broken.  One could still leverage the roof by putting a sloping sheet setup described above under the roof as opposed to away from the shelter.  When done that way, it should work faster even if the water gutter is damaged and if the water is not all going into a single water drain pipe.  This might be too much detail to simulate in the game.  But the point is, roofs of buildings normally would be the best way to collect rain water, imo.  The only reason survivalist don't talk about it is because it's assumed they're doing wilderness survival where you don't have roofs.  But in an urban survival situation roofs are everywhere and it would be silly not to leverage them for water.

**Comment by graysage1** [comment]
Some more ideas.

Maybe in order to catch the wrung water into a narrow-necked container the player should need a loose funnel available nearby as a tool.  Wide-necked containers should probably be exempt from this requirement.  So it could be possible to wring cotton into a drum or a vat without any extra tools.

What should also work: a) wringing the cotton item over a tile with a stationary funnel (as opposed to one that's in the inventory), with the container on the same tile, the same setup as for rain water collection, b) wringing the cotton item over a sink, bathtub, toilet, maybe some types of trash cans.  I am assuming the sinks and bathtubs can be plugged up.

**Comment by KA101** [comment]
I'm not concerned re damaging the item or charging the player other resources--just how to implement collection in a realistic/non-game-y manner whilst also keeping the code and processing manageable.

**Comment by graysage1** [comment]
>I'm not concerned re damaging the item or charging the player other resources--just how to implement collection in a realistic/non-game-y manner whilst also keeping the code and processing manageable.

I don't think it makes sense to precisely simulate landed moisture unless you want this to be very generic such that it will be used all over the place.  So for example, if you do store moisture content on tiles, you can then simulate vehicle skidding more precisely.  But if you're not interested in such a detailed simulation, I think it would work to have a special "wring" actively menu available on some or all cotton items.  This activate menu could work similarly to the knife's activate menu.  Knives are multipurpose tools, so the player can do something like four different things with a knife by activating it.  Cotton items can be the same way.  This could be limited to towels and sheets, or it can be generic with regard to cotton as a material.

So you'd hit 'a' then pick your towel, then you'd have a list of options like:

1. Dry off.
2. Begin gathering ground moisture.
3. Wring out.

So if you choose 1, then it works the same as the towel's current activation.  It dries off your character.  If you choose 2, then the towel enters a special state, maybe tracked via charges similar to jumper cables.  So then your towel may say "towel, gathering moisture (10)" then each time you walk over a tile that doesn't have a roof over it and that isn't occupied by a tree or other junk (I think the tile should be open) this charge counter is decreased by one.  So when you take 10 steps over exposed and empty tiles, then it should be in the same state as after drying off, like "towel (wet)."  Then if you apply it and choose to wring it, it might ask you which container to dump the water into (a funnel might be required for narrow necked containers).

So this way you really wouldn't need to simulate water content too precisely.

Maybe during moisture gathering state the towel should check if it's an appropriate hour of the morning, or if it's currently raining.  Then if yes, and you have just activated it for the first time or walked once, it successfully gathers moisture.  How much moisture it gathers can also be determined at that time.

If you put the towel into a moisture gathering state and walk into a building or a vehicle, it should abort the state and fail to gather anything.  And there might be other fail states.

**Comment by KA101** [comment]
Sounds reasonable.  My concern was folks parking on one grass tile and obtaining All The Water.

**Comment by graysage1** [comment]
My description is pretty rough.  I think the actual implementation is going to be a bit more complex because it will need to consider many conditions.  Should the charge counter decrement on every step?  Or should it decrement only when moisture was gathered?  Maybe it should just track steps, and then it's possible that after 10 steps no moisture gets gathered, such as if you walk inside a shelter (roofed tile), or if you drive a vehicle for 10 turns after activating your towel to gather moisture.  Like I said, it's almost certain that I am not thinking it through very thoroughly.  The actual implementation may be more complex than what I am describing here.

**Comment by graysage1** [comment]
>Sounds reasonable. My concern was folks parking on one grass tile and obtaining All The Water.

OK, I see your point.  The way I was thinking, tiles would indeed be reusable unless they were marked as "dry."

To make tiles non-reusable, they'd probably need to have a "wet/dry" binary state, at minimum.  Without that it's true that you can just walk back and forth over two tiles and fill up the towel.

**Comment by graysage1** [comment]
On a second thought, "wet/dry" probably makes no sense in the rain.  But it does make sense with the dew situation in the morning.  I'm thinking during the rain no matter how busy you were picking up moisture on the grass, it would quickly get wet again, so maybe it wouldn't be worth tracking.  But for dew I can see how it would be a concern.

Hmm, so if you don't want tiles to be quickly reusable, I think you're right KA101 and each tile would need to store at minimum a binary wet/dry state.  This could be a pain.  After the rain, it's wet.  When the rain stops, tiles get dry after say an hour or two.  This could require a lot of updates to the individual tiles, which could slow down the game.  On the plus side, if you were to go all this way, you could use tile wetness indicator to increase vehicle skidding and maybe for some other purposes.

As a quick and dirty hack, maybe gathering moisture via towel could be limited to once per day or once per two hours, no matter what, even if you have multiple towels/sheets.  This wouldn't be realistic, but at least it would limit the amount of water you can collect without the need to track to wetness status of the individual tiles.

**Comment by graysage1** [comment]
Thinking about it some more, the amount of wet tiles is going to be stupendous anyway, so it's probably not a concern whether the player reuses two tiles or legitimately walks around into the freshly dewed tiles.  There will be a limitless supply of tiles with the dew on them, so even if you were to track the wetness of each tile individually, it wouldn't really put a significant limit on the player.

The main limiting factor I think is the time of day, as far as dew is concerned.  So dew gathering can only be done, let's say from 5am to 6am, and that's it.  Or maybe from 5am to 7am.  That would be the main limit.  And the tiles should probably be open to the sky and unoccupied.

Are there any maps where you legitimately only have say 10 squares of open land and that's it?  In that case gathering dew may be unrealistic.  This might actually happen on some maps, but I can't think of any right now.  Most maps that come to mind are either full of wilderness squares, or have none at all, like when you start in a lab as a mutant, then every square is roofed, and so you couldn't possibly gather water that way inside the lab, unless you went all the way to the roof perhaps.  Maybe on the roof floor it should work.  But the roof floor is still sufficiently big that you'd have more than enough water, even if you were to track the use of each tile?  What do you think?

I think in most situations there are so many wet tiles that it doesn't matter, but maybe in some situations it would matter.  Like if you were on top of a 4x4 roof, it would only allow you to gather a very limited amount of dew water if you were to try wet/dry status of each tile.  But does this ever happen?

**Comment by graysage1** [comment]
Here's something that might be relevant:

http://www.theweatherprediction.com/wxlore/i/

If I understand correctly, it says dew mostly forms on clear (no clouds) nights, when the temps drop below the dew point.  I think CDDA tracks cloudiness already, so this info can probably be used to determine if the dew was able to form the previous night or not.  "Dew" can be a weather condition similar to other ones such as rain and thunderstorm in this case, as opposed to something that's tracked on a per-tile basis.  Although dew can probably occur concurrently with some other weather conditions, but it could still be tracked globally instead of locally on per-tile basis.  (Unless the game tracks sunlight and cloudiness on per-tile basis already?)

**Comment by sparr** [comment]
even if the water is clean, this strategy assumes you have a clean-enough-to-eat-off-of towel, which I am comfortable assuming our survivors' towels are not.

collecting dew with disinfected rags/bandages might yield clean water. collecting with other random cloth items should not.

**Comment by graysage1** [comment]
>even if the water is clean, this strategy assumes you have a clean-enough-to-eat-off-of towel, which I am comfortable assuming our survivors' towels are not.

I think you make a good point.

>collecting dew with disinfected rags/bandages might yield clean water. collecting with other random cloth items should not.

Maybe so, but practically speaking, I don't think bandages are voluminous enough to be used in this way.  I could be wrong.  Maybe someone with survivalism/bushcraft experience can chime in.  I imagine one needs a relatively large cloth that is also at least a little sturdy.  A typical bandage when rolled up is at most about the size of a fist.  Also bandages are usually made from gauze, which is not exactly a sturdy fabric.  Maybe if you joined 50 bandages together you'd have enough cotton mass to be able to effectively gather water with it.  It's hard for me to imagine how practical this would be.

I think a t-shirt may be OK to use in a pinch, but a pair of underwear is already probably too small to be of use.  A single rag is probably too small as well.  A towel or a sheet or a big cotton item like say a hoodie, those seem ideal.  And I agree, they'll be dirty, most likely.

So *I could be wrong* and maybe bandages would be serviceable, but right now I doubt it.  If we really wanted to go that route, maybe we could consider a formula for disinfecting an entire towel.  Actually now that I think about it, boiling your towel or a hoodie will work.  But your towel will only stay clean for a short time.  It's going to catch germs pretty quickly.  And if you just boiled your towel, you could have boiled water instead, so it seems to defeat the purpose.

**Comment by KA101** [comment]
Or this doesn't provide clean water, but just water.  Regular water is usually kinda-sorta safe enough to be "potable".

*KA101 blends a pile of cannabis into the water*  What?  Isn't that what "potable" means?  ;-P

(Yeah, I know, that's a joke.)

**Comment by kevingranade** [comment]
One, this isn't remotely common knowledge, so either a survival threshold
check, or finding out about it from a book for balance.
Two, *rain* doesn't give 'clean water', so there's no reason for this
procedure to.
Three, we could store a list of coordinates the player has harvested water
from in the player object itself, that way nothing but this code would care
about it.

**Comment by graysage1** [comment]
@kevingranade sounds good, and the third point seems like an elegant solution, since the list probably won't get very long and it will expire after some time.  "Why didn't I think of that!"

**Comment by chaosvolt** [comment]
I like this idea, but unsure how it'd be implemented. Being able to wring dry a wet item into a container would be the most sensible first step, THEN we can work out how to get dew onto, say, rags tried to the ankles.

Transpiration bags and solar stills would be other, potentially easier to code low-yield water options.

**Comment by graysage1** [comment]
@chaosvolt 

>Being able to wring dry a wet item into a container would be the most sensible first step, THEN we can work out how to get dew onto, say, rags tried to the ankles.

I agree.  We already have a 'towel' item that is capable of getting 'wet'.  If only we could wring it, right?  I don't know if your mod can do that or not.  I don't know what the extent of power of mods is.

**Comment by Coolthulhu** [comment]
Mods currently couldn't do it. You'd need C++ here.
There's no good way of telling how wet the towel/clothing are, though. Currently towel always gets wet for 300 turns and clothing doesn't store any wetness variable (it's all essentially stored on player's body).

**Comment by graysage1** [comment]
To be honest, maybe I am going crazy and maybe it's always been like this, but it seems like funnels maybe have been buffed?  Or maybe 'funnels' were always very effective compared to makeshift funnel and leather funnel, and maybe I just never got to using a real funnel before?  I don't know.  But with the funnel item as effective as it is now, water really isn't much of an issue.

So to me this proposal, while realistic and a "real" bushcraft "thing" as it were, is not terribly necessary.  If it were implemented, it would I think add flavor to the game and be nice, just another nice option for getting water, but honestly I don't feel as passionate about this proposal as I once used to.  I still like it, but I am content to wait indefinitely for it.  I don't "have to have it" or anything. :)

**Comment by Coolthulhu** [comment]
> Or maybe 'funnels' were always very effective compared to makeshift funnel and leather funnel

This one. They're about 20 times more effective due to quadratic scaling with radius.

**Comment by graysage1** [comment]
> They're about 20 times more effective due to quadratic scaling with radius.

This is jaw-dropping.  Are the non-professionally produced water funnels really *that* bad? :)

**Comment by Coolthulhu** [comment]
I think the contributor who got them in just forgot to check if the scaling is linear and assumed it is.

**Comment by chaosvolt** [comment]
And in highly-belated response, yeah. One could mess with the source to change use action of towels to allow wringing them out into a container, but that could still cause problems. Realistically it'd only make sense if the towel's drying period could be affected by HOW wet your clothes are, then add a threshold for how soaked it has to be to allow wringing out.

Solar stills and such could also be viable, but you'd have to keep in mind how bloody slow they are. Plus, solar-powered terrain would also be a nuisance to code.

There's also this: http://en.wikipedia.org/wiki/Condensation_trap

"If there are no large trees in the area, clumps of grass or small bushes can be placed inside the bag. If this is done the foliage will have to be replaced at regular intervals when water production is reduced, particularly if the foliage must be uprooted to place it in the bag."

This is probably the easiest method to code, something involving plants, a bag, a crafting recipe, and a delayed_transform allowing the eventual harvesting of a small amount of water.

**Comment by graysage1** [comment]
Thing is, the method outlined here is reported to be not too slow.  It's probably faster than a solar still.

Players can already make makeshift funnels and leather funnels which are ridiculously slow. :)

Maybe the two early crafteable funnels should simply be upgraded.

**Comment by chaosvolt** [comment]
Hmm, maybe. If we had some code model for dew and allowing the player to gather it. The "get it from a towel" idea would be slightly simpler, but that would also be dependent on rain, and only be practical for survivors that haven't set up funnels. Or wading through water, in which case you could gather the water instead and boil it. o3o

Thing is, the player can eventually build a well anyway with the right skills and materials, if I recall.

**Comment by graysage1** [comment]
@chaosvolt 

>Thing is, the player can eventually build a well anyway with the right skills and materials, if I recall.

Construction 9 I believe?  You have to be world's foremost construction authority to build a well.

**Comment by chaosvolt** [comment]
Unfortunately, yeah. Would probably be easier if I could find any level-8 construction tasks. Weird. O.o

**Comment by graysage1** [comment]
@chaosvolt Fair points, both.  Suffice to say, wells are pretty much out of question I think.  It would be better to think about upgrading the makeshift and leather funnels, but that probably belongs in the main game and not a mod.
