### ISSUE TITLE
Large part of the roof supported by a window

### ISSUE THREAD

**Issue by Eldhelion** [CleverRaven/Cataclysm-DDA#11594]
I don't know if this work as intended but on 0.C - 2860, 
I found  a farm and was going to transform it on my new shelter, I got the idea of removing on of it's window to build a vehicle section there (aka, put a vehicle half way in with head lights and the other part out with solar panels)
but when I smashed said window of a farm barn, literally half of the barn's roof came down.

What got me to wander if this is a bug, because it's pretty strange [non intuitive] one 'building tile' supporting so much roof
##

**Comment by DavidKeaton** [comment]
iirc they squashed this issue a bit ago, but this I'd say may have been missed in that fix

**Comment by BevapDin** [comment]
I had this, too. But it's random, sometimes smashing a window will only destroy the window itself, sometimes half the house. I even smashed a while house wall by wall and at the end some floor (and roof!) remained without any wall to keep it there.

This is one of the issues that really needs z-levels to work properly at all.

**Comment by KA101** [comment]
Yeah, not ideal but a proper fix is a long time coming, I'm afraid.

**Comment by kevingranade** [comment]
The issue as stated is working as intended, window frames are generally structural elements, so destroying them will definitely cause damage to the building.
