### ISSUE TITLE
Eat items on the ground?

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11598]
This is a feature that I miss from Nethack. If I'm standing on a tile with food, having to pick it up can be arbitrarily tedious[1]. I'd like to be able to see ground items in the [E]at interface, similar to the interface for comparing items ("I.").

Some folks on IRC think this feature would be annoying, so perhaps it should be optional.

[1] It could be multiple pages down on the AIM interface. I might not know exactly how many items I'm going to eat in advance. etc

**Comment by FireCrow1973** [comment]
i would love this feature, in regard to "annoying": i am a fan of giving options in the.....options-menu.

**Comment by Coolthulhu** [comment]
You could put the items at the end of the inventory, in a separate category.

There's at least one instance of this kind of thing happening in the code: you can pour liquid to containers at your feet.

Though now that I look at the code for liquid pouring, it is quite hacky. I thought the solution would be obvious, but it's rather complicated and involves doubling inventory display code.

**Comment by sparr** [comment]
@Coolthulhu I haven't checked yet, but might the code for [I]compare applied to the square you're standing on be a useful alternative approach?

**Comment by ejseto** [comment]
Maybe it should be linked to mutations. "I used to have to eat with my hands, but then I mutated a snout and now I'm beyond such tedium!"

**Comment by Coolthulhu** [comment]
It is less about eating off the ground directly, and more about just not having the player waste clicks. It would be fine for off-the-ground eating to consume extra 100 move points for the pickup.

**Comment by ejseto** [comment]
It was a joke.

**Comment by mugling** [comment]
@drbig fixed in #13986
