### ISSUE TITLE
Reading is very finicky regarding light levels

### ISSUE THREAD

**Issue by Peeping-Peacock** [CleverRaven/Cataclysm-DDA#11595]
Reading a book next to a window is slower than climbing into the window frame to read.

On a similar note, during a drizzle its too dark to read. This might be my ignorance of New England weather,  but during a drizzle isn't it still bright enough to read?

Assuming drizzles look something like this-
![04 drizzle](https://cloud.githubusercontent.com/assets/11481347/6656696/286bba7a-cb08-11e4-9fe6-56c5b8cf0b7c.jpg)
##

**Comment by graysage1** [comment]
I agree.

**Comment by Zireael07** [comment]
I agree, too.

**Comment by FireCrow1973** [comment]
I agree, tree.

**Comment by kevingranade** [comment]
Need a bit more to go on, what should the penalty be?
Ideally bug reports have steps to reproduce, expected results and actual
results, it can be informal, and sometimes expected is obvious, but here
it's not.
As for the drizzle, no that pic is not representative, there are palm trees
in the shot, indicating that it's in or near the tropics, 1,000 miles or
more closer to the equator than new england.  Drizzle in new england
implies overcast, leaving things fairly dark.  Possibly enough to read by,
but again you didn't state your expectation.

**Comment by Peeping-Peacock** [comment]
First time using git, so thanks for giving me some direction here.

Currently reading indoors will always produce the "its hard to make out fine details" message and slow down reading regardless of your location in the building if you are relying on natural light, standing next to a window or standing in the center of the building both apparently give the same light level for reading. The only locations in a house that prevent the penalty are door frames and window frames, or really any tile 1 block away from natural light. I would think that being next to a window would allow you to read with no penalty at all. Unless the windows are tinted to protect from air raids or something like that, there's no reason it would be substantially more difficult to read on the interior side of a window than it is in the window frame. As to how far from a window you can get before you get faint vision, someone more familiar with measurement in this game would be better suited to answering that than me.

For the question about drizzles, I live in Florida, so that's just a weather question I had, thank you for clearing it up.

**Comment by graysage1** [comment]
It's currently sunny where I am.  I've closed vertical window blinds in my bedroom and closed the door.  There are no artificial light sources.  So the only light getting in is whatever can get through the small cracks around the window blinds.  I just opened a book, and yea, I can read it just fine.  A human eye doesn't need much light to read.  If you can see colors, you can certainly read.  Even if it's so dark that you're no longer able to distinguish colors, you can probably still read.

Does it ever get so overcast in New England that you lose your color sense?

http://www.flickr.com/photos/43071435@N08/13497405535

http://www.flickr.com/photos/hsnali/2692731808/

http://www.flickr.com/photos/gammaman/9477555888/

It's my experience that I can read pretty much any time when the sun's out, regardless of cloud cover.  I can imagine a solar eclipse would pose a challenge.  I don't even think tornados make reading impossible.

https://duckduckgo.com/?q=tornado&iax=1&ia=images

How about hurricanes?

http://2eyeswatching.com/2012/11/01/on-the-ground-hurricane-sandy-in-images/

I've yet to see an image that shows colors verging on gray-scale.  So I think it's safe to say if color perception is still active, there is enough light to read a book, to craft, etc.

**Comment by Peeping-Peacock** [comment]
I've given this more thought and would like to add reading in non-clear weather, as well as wanting to update the title and post contents, would a major rewrite call for a new issue and closing this one or just modifying the original one?

Thank you for you wonderfully informative post graysage1, it's what made me realize that being able to build a car while its raining but not read a book is absurd.

**Comment by Leland** [comment]
Closing - discussion has stalled and this is a topic over 2 years old now. Feel free to comment here if you still want it open, or make a new issue.
