### ISSUE TITLE
Revamp furniture and empty tile storage volume, moving furniture with items, item access times, etc

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11602]
It feels like there's a lot of room here for realism that should be pretty obvious to players.

Right now, 4000 volume (a cubic meter, densely packed) of stuff on the ground is just as fast to pick through as four books on a bookshelf. That seems silly. Ditto putting things "on" a bookshelf or table, then [G]rabbing the furniture and dragging it out from under the stuff.

What if furniture had a storage volume limit, and that limit was higher than the limit for an empty tile in most cases? And grabbing things from storage furniture was faster than grabbing from the ground? And grabbing from the ground took longer the more stuff was piled there? And maybe even walking through a square with more than a few hundred volume of items could be slow?
##

**Comment by BevapDin** [comment]
> What if furniture had a storage volume limit, and that limit was higher than the limit for an empty tile in most cases?

You mean the thing that is already implemented? Default max storage volume is 4000, lockers have 8000 display racks 7000 other furniture similar, indoor plants afaik have 2000, etc.

This is btw shown in the adv. inventory.

----

Also, related forum thread http://smf.cataclysmdda.com/index.php?topic=9761.0 (it's about speed of picking up items).

**Comment by sparr** [comment]
@BevapDin ok, yeah, that's definitely what I meant with that detail, although those numbers are unrealistically high I think. Storing a cubic meter of easily-sortable items in a one meter square area is rather ludicrous.

**Comment by BevapDin** [comment]
Volume of items is not necessarily the actual physical volume. It also represents how bulky an item is and is mostly used in relation to the storage volume that worn cloth provides.

Also: who says that a tile is one meter square? A whole jabberwock fits in it! Tiles are merely an abstraction.

----

I agree with the grabbing problem, furniture keeps its contents only if it has the CONTAINER or SEALED flag, lockers have CONTAINER, book shelfs haven't.

**Comment by Lorith** [comment]
My issue is that a display rack can hold more 55 gallon drums than the same space without a display rack.  And if you have 1,000 items, you can find exactly the item you are looking for the same speed as if there is one item.  IMO, there should be something to limit you to maximum size plus something to control speed based on number of items (that could be reduced for certain furniture)

It should be easy to find something on a display rack or bookcase compared to the same set of items in a pile on the ground.  Likewise, it should be impossible to stick a 55 gallon drum in a bookcase or dresser.

**Comment by Zireael07** [comment]
Book shelves should have the CONTAINER tag.

**Comment by ejseto** [comment]
There's no way 1 tile is 1 cubic meter. First of all, personal space would be 1 meter radius, so a tile should be ~4 square meters, depending on whether you view squares as circles (gg roguelike geometry). Fighting someone, especially zombies, would be very difficult from that distance as well. And why would you be limited to 1 meter of height?

**Comment by sparr** [comment]
@ejseto according to a few bits of documentation and source, a tile is one square meter (doors are 1 meter wide, tables are 1mx1m, etc), and 1 volume is 0.25L. The capacity of an empty tile is 4000V, which is 1000L, which is 1m^3. So, a tile full of stuff is a 1mx1m pile stacked 1m high, which seems very implausible.

**Comment by Lorith** [comment]
And in that case, dressers/display racks are magically larger than the space they take up.

**Comment by Rivet-the-Zombie** [comment]
Or perhaps they're taller than a single meter?

**Comment by BevapDin** [comment]
> Book shelves should have the CONTAINER tag.

That flag also prevents anyone from seeing what's inside from far away, only when adjacent you can see what's inside. This seems to require a new flag.

**Comment by sparr** [comment]
@Lorith well, there's some amount of abstraction. 4V isn't just 1L. It's also "harder to stack/sort/handle than 1V". So, a bookshelf has more game-volume not because it has more physical-volume, but because it makes it easier to organize things. Sadly this abstraction means there will always be some inconsistency when using the same system to describe tiny hard-to-stack things and huge easy-to-stack things like 55 gallon drums.

**Comment by KA101** [comment]
Tiles have no official size, for this reason.  That said, a cubic meter is not the same as a square meter, and I'd imagine a z-level is about a story (10 USian feet or so) tall.  But that's just me opining w/o looking at the source.

**Comment by sparr** [comment]
@KA101 weather.cpp's rain collection function says a deployed funnel is 1m^2, and a lot of other game measurements match up to it being *about* 1m (furniture size, door size, vehicle size, etc). If it's not canonically 1m, it's darn close in practice.

What I said about a cubic meter was in reference to 4000V being 1000L which is 1m^3. If the stuff isn't well-stacked then the pile could be taller than a meter, but that's *more* insane, not less.

**Comment by KA101** [comment]
As I said, **tiles have no official dimensions**, for the reason that it's bloody impossible to reconcile everything.  One meter is a handy guidepost, but it's hardly a rule.  (A bicycle is not three meters long, forex.)

**Comment by sparr** [comment]
Even if it's four times that size, piling a cubic meter of stuff into that space would still be rather unwieldy to sort through, and nigh impossible to walk through without breaking things or tripping (we're talking about a *solid mass* of items 25cm deep, or a rough pile 40-60cm deep)

**Comment by drbig** [comment]
I'm all for more intricate storage furniture:

 1. Limit what can be put in (e.g. no 55 gallon drum in a bookshelf)
 2. Impose speed penalty/benefits (e.g. penalty for 4K volume of crap on ground, benefit for books/small items in a bookshelf).
 3. Fix the 'can see' and the 'drag with contents' attributes

The goal: it should be worthwhile to choose appropriate furniture for given type of items, and just dumping stuff on the ground should be the least pleasant option.

I would even suggest a mechanic where storage furniture benefits/penalties are based on stored item's category, so that putting books in a bookshelf is much better than putting books in a dresser (and vice-versa for clothes/armor). With this I can see (and justify) new proper storage furniture: tool rack, drug cabinet etc. A generic display rack would be perhaps the least 'biased' furniture (with little penalty/benefit), maybe also a locker.

**Comment by KA101** [comment]
1) Concur.
2) This has been a bugbear in the past when someone attempted it for crafting.

Mechanic sounds interesting, implementation can be fought over.

**Comment by Leland** [comment]
Good ideas here, but it's been over 2 years since the last movement. Closing.
