### ISSUE TITLE
Display more tile info in AIM

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11600]
The AIM has two panels, left and right. In the top left corner of each panel it tells you which direction/location that panel is pointed at. North, South, Directly Below You, Inventory, etc.

If the target tile has a container, that shows up below the direction.

There's a lot of extra space there. I'd like to see more info there. In particular, I'd love to know what furniture is in that tile, and if the tile is on fire, and if there are any traps or fields on the tile. I'm sure others here can think of more.

So I ask, is this a good idea? What else should be shown there, with what priority?

**Comment by KA101** [comment]
Haven't specifically looked, but is the extra space still there in 80x24 window size?  Some folks seem stuck there so that's the design spec within which everything has to fit.

**Comment by sparr** [comment]
Same amount of space at any window size. The same three rows that the [7][8][9]... grid takes up. Currently the first row is always used, the second row is used for [vehicle?] containers and "All 9 squares", and the third row is never used. So that's 1-2 rows of 21 character wide wasted space.

PS: I haven't played enough to know if there's anything else that ever goes there now. I imagine I'd find out when I hop into the source to try implementing this.

**Comment by narc0tiq** [comment]
Third row is used for labels -- get a marker and write on the ground, or
use the l[a]bel action in the vehicle interaction menu. I'm not aware of
any other things that go there, but there may be some. Either way, I
approve of having more information, so if you can fit it in, go for it.

**Comment by sparr** [comment]
OK, diving into the source...

Line 1 is "Inventory", "South West", "Grabbed Vehicle", etc. That's always populated, and the longest string ("Directly below you") barely fits in the given space on an 80x24 terminal. However, the other strings are much shorter. If the descriptive strings were shortened to the length of "Southwest", there would be room for an extra 7-character informative string there. And of course there's more room on bigger displays. Is it worth truncating those labels on a small screen to fit something like "FIRE" there?

Line 2 is the name of the vehicle you've pointed at, "All 9 squares", or stuff you've written on the ground if it's not a vehicle tile, or blank. Vehicle names and ground labels can be arbitrarily long, so they already get truncated sometimes. Would it be bad to truncate them a bit further to fit "TRAP", "SMOKE", "GAS", etc there?

Line 3 is supposed to be the vehicle tile label, or blank, but I can't figure out how to make it work. While testing, I've labeled the tile of the vehicle with storage (and every other tile of a vehicle) and I can't get that label to show up in the AIM no matter what I do. I need someone to walk me through how that feature is supposed to be used so I can see it in practice.

Skipping the truncation idea above, I might also propose moving vehicle tile labels up onto Line 2. When they do exist, they are higher priority info than the other things on that line. That would leave line 3 completely free for fire / trap / smoke / gas / etc.

**Comment by sparr** [comment]
Oh, in addition to fire, traps, fields, and furniture, I might also want to know if I'm dropping things onto a tile that slows movement, or a tile with a monster on it.

**Comment by sparr** [comment]
Opened PR #11609

**Comment by DavidKeaton** [comment]
why 80x24? seems a bit... archaic?

**Comment by sparr** [comment]
@DavidKeaton Lowest common denominator. I suspect the same reason everything has to work in 16 colors. The AIM (and a bunch of other interface elements) creates strings arbitrarily wide, and then truncates them to fit on the current display. We just need to make sure that when that truncation happens for the smallest display, things are still at least somewhat readable.

**Comment by sparr** [comment]
#11609 was merged
