### ISSUE TITLE
Folding wing mirrors

### ISSUE THREAD

**Issue by Zireael07** [CleverRaven/Cataclysm-DDA#11618]
IRL, in year 2015, many cars have the possibility to fold/unfold the mirror as needed in tight spaces.
Obviously, the mirrors provide no benefit when folded, but at least they would no longer impede me in tight spaces.

Currently, the only way to do it is remove/install them every time, which is 
a) a waste of time and resources
b) annoying
##

**Comment by sparr** [comment]
Maybe a "folding mirror" should just be a different item, which mounts inline with the vehicle body instead of one tile out? Abstract away the folding and unfolding.

**Comment by KA101** [comment]
DDA!wing mirrors are much larger than car mirrors, more like these:
http://www.rentnsave.net/images/moving-rental-trucks.jpg

(For that matter, they're crafted from a hand mirror on a stick, too.)  An OEM mirror might be foldable but crafted ones, not so much.

**Comment by Zireael07** [comment]
@KA101: All right then, let's roll with @sparr's suggestion of a folding mirror item.
