### ISSUE TITLE
Map-related issues

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#11611]
1) When trying to toggle blinking on map by pressing "B" and the blinking symbols aren't shown, the explored (gray) places are reverted to their original color.
2) At the moment science lab's "stairs down" is colored dark blue, so we can easily find it on map amongst blue-colored ordinary lab territory. I suggest to also color "stairs up" differently, because right now I have to manually make note about stairs up not to lose them in vast lab territories. The "Auto notes" option isn't working for me for some reason.

**Comment by KA101** [comment]
Auto notes not working is a bug; the grey is probably more an oversight but still worth fixing.  Lab stairs is more a question whether that's an enhancement.

**Comment by Night-Pryanik** [comment]
Should be closed after #11616.
