### ISSUE TITLE
Harvesting stomachs from humans counts as woodland creature stomachs

### ISSUE THREAD

**Issue by Cenobite000** [CleverRaven/Cataclysm-DDA#11612]
Game Version: O.C-2866

Started testing out the new version today and found that butchering a normal human corpse produces a stomach which states that it comes from a "woodland creature"

I'm guessing that eating it doesn't count as eating human flesh (I didn't see the Human Flesh tag on the item).

**Comment by Night-Pryanik** [comment]
The same for broken cyborg.

**Comment by tivec** [comment]
Thanks for the report. I will be working on a fix for this today.
