### ISSUE TITLE
Segfault while running around, experimental build 2870

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#11617]
Was just running around, minding my own business, when I got a segfault. It's not exactly reproducible, since when I got irritated enough to do a debug compile and run the debugger, it took several minutes of running around to happen again.

```
#0 00C97497	std::string::compare(char const*) const () (??:??)
#1 00BF6656	mcount () (??:??)
#2 00000008	?? () (??:??)
#3 00000009	?? () (??:??)
#4 0000000A	?? () (??:??)
#5 0000000A	?? () (??:??)
#6 00000008	?? () (??:??)
#7 00000008	?? () (??:??)
#8 00000008	?? () (??:??)
#9 00000008	?? () (??:??)
#10 00000064	?? () (??:??)
#11 ??	?? () (??:??)
```

**Comment by KA101** [comment]
Some more details on where you were running, etc might be helpful?

**Comment by ejseto** [comment]
That's the thing, it seems kind of random. Just running around along a road for several minutes, or fleeing town. I had a hell of a time reproducing it when I fired up the debugger, and as you can see, it doesn't look too helpful.

**Comment by Coolthulhu** [comment]
Is it a full debug build (make clean -> make) or did you rebuild only some parts?
The `??` suggests that it either it's a build stripped off debug symbols, that it's executing system functions or that it's a low-level fault involving reading random memory addresses.

The fact that the addresses below `mcount` are all very low suggests the last explanation. Also the fact that it crashed in `mcount`, which is a function supplied by the compiler.

Are you usually running a downloaded binary build or one you compiled yourself? Translated version? Version that can translate or can't (ie. LOCALIZE=0 or left at default 1)?

And finally: is your hardware working fine? Are you using a stable compiler or some experimental one?

**Comment by ejseto** [comment]
I'm using Code::Blocks with MinGW 64 4.9.0. I did a clean and then rebuild just to be sure. I've got the -g, -pg, and the default project-wide compiler switches (-Wall, -Wextra, -std=c++11, -march=corei7-avx, -Wno-switch, -Wno-sign-compare, -Wno-missing-braces, -Wno-unused-parameter) enabled. Only defines are SDLTILES and TILES.

**Comment by ejseto** [comment]
I'm also getting possibly related segfaults upon starting a new character in the "very bad day" challenge scenario. It happens in both the experimental builds and my own debug build about 50% of the time, if not more.

```
#0 00C84307	std::string::compare(char const*) const () (??:??)
#1 00BE34B6	mcount () (??:??)
```

**Comment by KA101** [comment]
Can confirm that I'm getting similar segfaults on Play Now! starts.  Intermittent, no noticeable rhyme or reason.

**Comment by ejseto** [comment]
I think #11672 fixes this. I haven't had any crashes in several hours, though I still had one when creating a new character.

**Comment by mugling** [comment]
OP reports resolved
