### ISSUE TITLE
Any plan to put CDDA on Steam and provide Steam integration?

### ISSUE THREAD

**Issue by caizixian** [CleverRaven/Cataclysm-DDA#11619]

**Comment by Zaweri** [comment]
...This has been dicussed many times before. NO. DRM is Bull****

**Comment by kevingranade** [comment]
Not just no but hell no.
Possibly desura or one of the other non-DRM distribution systems.

**Comment by sparr** [comment]
Steam allows DRM-free projects. Not sure if you can integrate Steam Workshop without also accepting their DRM, though.

**Comment by KA101** [comment]
If valve wants DDA they can bloody well fork the project like anyone else.  If their crap is compatible with CC-BY-SA, and I'm betting it's not.

We are NOT putting it on steam.  Deal.

**Comment by sparr** [comment]
@KA101 good point, re forking.

@caizixian If you decide you want to maintain a fork of DDA on Steam, I'd be willing to put some coding hours into that. There's a lot of work between here and there, though, including just keeping the GUI builds stable on all OSes.
