### ISSUE TITLE
finally got the SDL2 build to cross-compile to Windows with mxe

### ISSUE THREAD

**Issue by pouar** [CleverRaven/Cataclysm-DDA#11627]
but it required a few changes to do so, I want to tell people what I did, The instructions for cross-compiling for Windows are like the ones in COMPILING.md, but with the following changes

before compiling the dependencies in mxe, I had to do the following
I had to disable directx in ~/src/mxe/src/sdl2.mk because it had a compile-time error about IDXGIFactory2 and ID3D11Device1 "being an unknown type" that I couldn't figure out how to get around, if anyone knows what I need to do to get it working, please let me know

updaterev.sh seems to produce a broken SDL_revision.h in mxe for some reason. the following patch is a hack to work around it, place it in ~/src/mxe/src

http://pastebin.com/HWchpm5M

I then compiled the dependencies in mxe with this
```bash
make gcc glib sdl2 sdl2_ttf
```

when compiling Cataclysm:DDA I had to add the following to LDFLAGS in the Makefile in addition to the current ones [at the end of this line](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/Makefile#L368)

```Makefile
 -luuid -lcomctl32 -lwebp -lharfbuzz -lglib-2.0 -lws2_32 -lintl -lole32
```

If anyone knows a better way that works please let me know

**Comment by narc0tiq** [comment]
I've had the Jenkins doing mxe compiles for basically as long as it's existed, but I'm afraid I've never taken the time to write down a description of the process, and the current setup has an mxe from 12 months ago.

To the best of my recollection, the setup was this:
- clone mxe's master branch (**not** the stable)
- edit settings.mk to enable the static targets: `MXE_TARGETS :=  x86_64-w64-mingw32.static i686-w64-mingw32.static`
- `make sdl2 sdl2_ttf sdl2_image sdl2_mixer gettext lua`

Note that I may have missed a package, but I'm pretty sure gcc and glib don't need to be explicitly mentioned -- you'll need them to compile the packages you actually ask for.

---

The actual builds use the script at <http://dev.narc.ro/cataclysm/mainline-build.zsh>, where windows tiles, for instance, follows this series:
```bash
PLATFORM="i686-w64-mingw32.static"
export CROSS="/home/narc/mxe/usr/bin/${PLATFORM}-"
export CXX="ccache ${CROSS}"g++
export LD="ccache ${CROSS}"g++

export TILES=1
export SOUND=1

export LUA=1
export LANGUAGES="$(echo $(for i in lang/po/*.po; do echo $(basename $i .po); done))"

export RELEASE=1

make -R CXX=$CXX LD=$LD -j2
make bindist
```

The only change for 64-bit windows builds would be to use the appropriate value of PLATFORM, namely `x86_64-w64-mingw32.static`.

---

If you prefer shared libraries, drop the .static and add those libraries you mentioned. Of note, if you do that, you'll also have to provide the actual .dlls somewhere in your PATH when you run cataclysm -- I prefer the larger binary with fewer dependencies.

**Comment by pouar** [comment]
you're right about not having to glib and gcc not being mentioned, apparently glib gets pulled in by sdl2_ttf as a subdependency (or whatever the name is for a dependency of a dependency of a dependency). Same thing with gettext as it's a dependency of glib. The rest of what I mentioned in the first post still needs to be done as it didn't work unless I did that.

**Comment by pouar** [comment]
seems they fixed the problem with directx not working

**Comment by pouar** [comment]
ok, it's "make sdl2_ttf sdl2_image" as sdl2_ttf doesn't seem to pull in sdl2_image
