### ISSUE TITLE
Broken bionic drain?

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#11623]
The problem is weird:

I get my bionic power drained in multiples of 25 seemingly at random, with random in-between frequency too. No fighting, active bionics, bad bionics, enhanced memory banks, any messages as to what might be draining etc...

My investigation seems to point this bug has been introduced between commits `50f7767` and `f5d6b3b` (last one without this problem).

Bionics I have:
http://imgur.com/6ChQ7OK
http://imgur.com/hhpJLOi

The problem is easiest to see after sleeping:
http://i.imgur.com/uMkyjyS.png (my record!)

The counter seems to reset to > 0 on move, which I attribute to the joint torsion ratchet.

**Comment by BevapDin** [comment]
If you write the commit ids without formatting, github changes them into links: 50f7767 f5d6b3b, thanks for figuring out the problematic range.

**Comment by drbig** [comment]
My bad. Dutifully noted down.

**Comment by drbig** [comment]
@BevapDin I officially tip my virtual hat to you. I was looking at the commits and had exactly zero idea as to what could be the culprit...
