### ISSUE TITLE
Closed vehicles still sometimes provide vision/light

### ISSUE THREAD

**Issue by DanmakuDan** [CleverRaven/Cataclysm-DDA#11621]
31bdc81 Using Windows 0.C 2870 tiles
The player is at the top of the screen, some vehicles (anything not obscured by walls) are providing vision from inside them when I stepped into a house doorway. The time is around 5:46 AM ingame, so you can see the edge of the player vision ends before the cars. None of their lights appear to be on. Placing the examine cursor on most of the visible spaces outside normal vision shows Unseen, but in some cases pieces of sidewalk and car interior components are viewable in the examine window from the player's position.

![bug_vision_seen_unseen](https://cloud.githubusercontent.com/assets/9610892/6669531/6c488128-cbc7-11e4-8aa6-559121c7bfbe.png)
##

**Comment by KA101** [comment]
That screencap looks like veh lighting is on, and your "insideness" is making it show more effectively than it usually would.  Known issue, we've not been able to get a good fix for it.

**Comment by kevingranade** [comment]
It also might be the code for lighting interiors, which finds each window
and creates a fake light shining through it to simulate sunlight coming
through them.  This has two major problems, the first is that with vary
narrow interiors like a car, the fake light shines all the way through the
car and out the other side.  The second is that the way our lighting system
works, these areas count as lit from an external source, and become visible
in situations where they shouldn't, like this one.

I have a rework of the lighting system planned that should address the
second issue and at least hide the first one.

**Comment by Zireael07** [comment]
@kevingranade: Good to know about an upcoming rework!

**Comment by DavidKeaton** [comment]
Given the time I've spent looking at lightmap.{h,cpp},  you have your work cut out for you.

**Comment by kevingranade** [comment]
I wrote what are probably some of the most complicated parts of it, but I
don't get off that easy, it's the render and sight code that needs updating.

**Comment by Leland** [comment]
Also see #14329

> Space enclosed by boards and entirely roofed over, aisles on the floor (same results if I replace the bed with an aisle, by the way,) and the sun wakes me up every morning.
>
> The expected behavior is that I'd have a dark sleeping room. It works fine to block the aisle lights to the south, but sunlight pours in.
>
> You can reproduce this with a far simpler setup - 3x3 vehicle, boards, door, roof everything over.
