### ISSUE TITLE
Save compatibility: Sound Dampeners need to be given to characters that already have Enhanced Hearing

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#11628]
If my understanding of #11546 is correct, the Enhanced Hearing CBM also includes Sound Dampeners when installed.

However, saves prior to #11546 being merged that have Enhanced Hearing installed don't automagically acquire Sound Dampeners (just did a quick check on my testing character that had Enhanced Hearing installed before updating to latest experimental).

**Comment by KA101** [comment]
True, and thanks for the reminder.

**Comment by tivec** [comment]
I'll see if I can fix this :)
