### ISSUE TITLE
some mapgens only spawn one vehicle, poorly placed

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11629]
map generation for the parking lot could be a lot more creative. it seems to currently only spawn one vehicle, and that vehicle is always near the north end of the lot, and always oriented in the direction perpendicular to the parking spaces.

how about adding more vehicles, at random? or possibly simulating a wreck, as happens on the roads sometimes?

**Comment by sparr** [comment]
office_tower_b does a better job of this, with 1-3 vehicles parked appropriately

**Comment by sparr** [comment]
s_garage is a two-door garage, always with only one vehicle. if that vehicle is 4 tiles wide then it's parked such that it can't back straight out.

**Comment by sparr** [comment]
dirtlot, like s_lot, only ever spawns one vehicle, always with the same orientation. also with the same position.

**Comment by KA101** [comment]
Some lots were designed at different times than others.  Office lots are a function of that building; the parking lot is a grab-bag and dates to Whales.

**Comment by sparr** [comment]
To be clear, this is something I want to fix, I'm just hoping for feedback here about the pros and cons of the different existing approaches, and maybe if any of this was done on purpose (maybe the garage vehicle being off-center is intentional?)

**Comment by KA101** [comment]
The garage veh is likely a problem with the placement being designed for smaller vehicles and the spawn later being retrofit to randomly take larger ones.  Overhauling the parking lot would be helpful; auditing others probably so as well but increasingly tedious.

I'd imagine the parking lot should first roll for the veh, and based on that have a few pre-planned spots where it spawns the thing.  (Bear in mind that we're talking apocalypse-in-progress parking here, so let's forgive less-than perfect alignment.)
