### ISSUE TITLE
Rounding in new encumberance granularity patch

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11625]
#11497 changed the encumberance system so that things that used to be 1 are now 10, 3 is now 30, and some new things that used to be 0 or 1 are now less-than-10. This is a great change. I'd like to talk about some of the arithmetic involved, and the impact of rounding, and "rounding in reverse".

In player.cpp there are a lot of places where divisors and thresholds were multiplied by ten. So, 10-19 new encumberance both have the same penalties that 1 old encumberance had. If we consider that the old system was effectively a rounded version of the new system, it feels like that penalty should probably apply to 5-14, not 10-19. This would not change anything about the behavior of existing items (until their encumberence values get tweaked in the future), but would affect the less-than-10 encumberence modifications, and items to be added in the future.

https://github.com/CleverRaven/Cataclysm-DDA/pull/11497/files#diff-dc52f162280289dd2d4d97d82658362dL2999
In the dozen changed lines below this there are a lot of what might be integer arithmetic problems. I see a few casts to double, but a lot more int/int that will throw away precision.

**Comment by PropaneSoup** [comment]
> it feels like that penalty should probably apply to 5-14, not 10-19.

Interesting idea, it does mean though that adding fur to my trenchcoat would give me -1 melee and dodge, which is exactly what I was trying to avoid by creating this system.



> (until their encumbrance values get tweaked in the future)

Much to KA101's dismay, I am currently going through and tweaking some of the values, mostly + or - 5, to give a little better accuracy of how much any piece of clothing encumbers you.



> In the dozen changed lines below this there are a lot of what might be integer arithmetic problems. I see a few casts to double, but a lot more int/int that will throw away precision.

That's probably in part my fault. My conversion was kind of quick and dirty. In my testing though, I never saw anything that looked like an inconsistency.

**Comment by KA101** [comment]
>Much to KA101's dismay

???

**Comment by PropaneSoup** [comment]
>Ah, a JSON audit, what fun. >_< [From #11497]

Did I misinterpret that?

**Comment by KA101** [comment]
That was not wanting to go through every item in armor.json and manually redo their encumbrance.  I've done that for pricing already.

Audits are frickin' tedious, but if you're willing to do so, feel free.

**Comment by PropaneSoup** [comment]
Ahh, yes that's been my experience with it so far :P At least it's only the one json.

**Comment by PropaneSoup** [comment]
Carrying over the discussion from #11497, I believe the best solution is to not change the threshold to 5-14 but to make it a smooth penalty. This makes the most logical sense, going from 9 to 10 now won't suddenly give you penalties, having lower will always just be better.

**Comment by sparr** [comment]
Some of the penalties are already smooth, which is great. Some just need some arithmetic rearrangement to make them smooth, which is doable. Some, unfortunately, rely on changing the number of dice or number of sides in the "dice" algorithm, which is non-trivial to smooth out. That is, right now there's some code where you "roll" 4d8 when unencumbered, 4d7 with 10-19 encumbrance, 4d6 with 20-29, etc. I'll see if I can suss out a way to smooth that a bit. I'll try smoothing a bunch of stuff and submitting a PR soon.

**Comment by PropaneSoup** [comment]
I looked at the code right after I made that comment, hit_roll in melee.ccp specifically, and yea, this looks non-trivial to make "smooth". While you're figuring it out, the biggest thing to keep in mind is that it should be as close as possible to the current system at 10 enc, 20 enc... ect.

**Comment by Snaaty** [comment]
Imo, the skill penalties should be replaced by something else altogether. "Realistically" speaking that penalty was tolerable but not more than that. An extremely experienced fighter that is carrying three military backpacks is going to fight differently (not necessarily better) than a totally inexperienced fighter, for example. Why not give it a different penalty along the lines of melee attacks taking more time, reduced chance to crit, reduced chance to dodge. 
Melee cost and swim skill should be able to give much smoother penalties, as the values that we used to have there were high enough, right?

**Comment by kevingranade** [comment]
I'm totally fine with encumbrance giving explicit check-related penalties
instead of adjusting effective skill level.  Even switching them to give
the exact same effective penalties, but leaving the effective skill alone
would be an improvement (though I suspect a number of them are scaled based
on level vs level somehow, so it won't be a flat penalty).

**Comment by Coolthulhu** [comment]
Rounding no longer happens now.
