### ISSUE TITLE
bionic tool is broken

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#11637]
I think it's the combination of the PR that made the tool toggle-able, and the PR that separated passive and active bionics.

bionic tool shows up in passive tab, but it's text color suggests it's toggle-able (but can't be toggled)

**Comment by tivec** [comment]
I can't reproduce this - the integrated toolset is listed in my active tab. Can you show a screenshot of this?

**Comment by aierce** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10649716/6683266/9c720a0e-cc49-11e4-826e-d66231fbbc2c.png)

am on version 2867. made random char and recreated this, the color is normal again, but it's still in passive tab and can't be activated

**Comment by tivec** [comment]
Do you think you ould update to the latest build (2874) and test if you can recreate the bug there? On current git master, I am unable to make this happen.

**Comment by aierce** [comment]
2874, same thing happens

also forget about me mentioning the text colors. Power supply bionics are colored lighter cyan. It has nothing to do with this bug

**Comment by tivec** [comment]
Could you open up data/json/bionics.json, search for "bio_tools"? Does it look something like this:
`{     "type": "bionic",
        "id": "bio_tools",
        "name": "Integrated Toolset",
        "toggled": true,`

I'm looking specifically for that `"toggled": true` part.

**Comment by aierce** [comment]
I am dumb
