### ISSUE TITLE
Add ability to use wood axe/saw to cut up logs on the ground

### ISSUE THREAD

**Issue by NickTaylor-** [CleverRaven/Cataclysm-DDA#11649]
Currently if you want to cut a log into planks (i.e. two-by-fours and a lot of wood splinters) you need to have the log in your inventory. This means that cutting logs up becomes tedious, as they are both heavy and voluminous, so it becomes a game of pickup and drop, and then going through a bunch of menus.

I think you should either be able to (a)ctivate the axe/saw on items on the tile beneath you, or (even better) add it as a crafting recipe so you can do batch work as well. Currently I find it easier just to cut down another tree and convert that into planks (instead of logs), which is counter intuitive.

**Comment by tivec** [comment]
The construction menu lets you do exactly this, if you have a saw/axe, unless I am mistaking what you are asking for.

**Comment by NickTaylor-** [comment]
The construction menu allows you to convert felled tree trunks into planks, but if they have already been converted into logs, you have to do it through the saw/axe itself.

**Comment by DavidKeaton** [comment]
Something very helpful as well would be to add it to a `butcher` type of interaction as well/instead.

**Comment by Zireael07** [comment]
+1 for adding this kind of stuff to butchering.

#11615 would go a long way towards making it easier to use/expand the butchering code.

**Comment by DavidKeaton** [comment]
I like the idea you linked. A lot in fact... may look into that.

**Comment by Coolthulhu** [comment]
I don't think butchering rework would work here. Those are rather separate problems.

Butchering rework is concerned with butchering corpses into multiple components. It is concerned with finishing butchering, while the problem here is with starting butchering.

Deconstructing and salvaging items is "requested" in butchering function, but it does not trigger butchering - it starts totally different actions.

**Comment by DavidKeaton** [comment]
fair enough, I perhaps was thinking in a slightly offish direction, however similar logic could drive salvaging is where I'm going with this.

**Comment by Coolthulhu** [comment]
It could, but I don't think it's worth the effort right now.
Salvaging could be (hackily) used to allow turning logs into planks by adding a new material ("thick wood" or something) that would be salvaged into planks. This would make it impossible to craft skewers from logs, but would have a positive effect of making wood flammability calculations simpler.

**Comment by NickTaylor-** [comment]
Why would you need a new intermediary "thick wood"? What would stop a salvage system from just being able to convert logs to planks?

**Comment by Coolthulhu** [comment]
Salvage system converts items to the default material component, which in case of wood is a skewer.

Though now that I think about it, it wouldn't work even with a new material. An important part of sawing wood is its dependency on construction skill. Salvaging depends on fabrication and only for one of the components.

**Comment by NickTaylor-** [comment]
What about a complete overhaul of the salvage/disassembly system? Make a new JSON (or add to the items one) with skill required to salvage, components, salvage min/max, tools required, etc.

That way you could specifically salvage components from items, you could get 2x4s from a log, or all splinters.

**Comment by Coolthulhu** [comment]
Too much work for too little gain. What else would use it?

If you're eager to fix this, a better and much easier way would be to simply rewrite the wood sawing function to automatically saw the first log it encounters under player's feet and only asking for items if there are no logs there. Not perfect, but you could just wield the saw and 'A' repeatedly.
It would take like 6-10 lines of code at most.

**Comment by NickTaylor-** [comment]
Yeah, I guess it would really just be butcher that could get rolled into it. 

That's what I currently have atm, working out a few things that I think are a bit hacky, but thats just because I don't know the codebase all that well.
