### ISSUE TITLE
boarding up a shelter window makes the curtains disappear

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11655]
I'm not sure how the shelter windows are special and have curtains, but however that is, it gets lost when the windows are boarded up. I think the curtains (sheets, stick, etc) should get pulled down automatically when the window gets boarded up.

**Comment by KA101** [comment]
Because windows and their various states are a mess of special-casing and separate terrains, so they probably don't remember the curtain-state.  Write a PR for it and we'd probably merge that.
