### ISSUE TITLE
Negative bionic power

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11661]
I somehow ended up with -200/250 power on the Bionic Soldier profession without doing anything bionics related other than toggling my night vision a few times in the first few days of the game. I assumed this just meant I was too hungry for my metabolic interchange to work, but folks on IRC tell me this shouldn't happen, so I'm reporting it as a bug.

**Comment by drbig** [comment]
@sparr which version are you running exactly? Have a look at #11623.

**Comment by tivec** [comment]
The negative power won't automatically be resolved with that patch, however any power usage attempt should result in the value being clamped as of PR #11639. Try updating to a version from today and see if it resolves itself?

**Comment by sparr** [comment]
@drbig I was running from two days ago master, I think.

@tivec I'll update and try again tonight or tomorrow.

**Comment by tivec** [comment]
I pushed a savegame compatibility fix to this in PR #11684 which is merged, so old saves should have their bionic power set to 0 if it is negative. 

Waiting for confirmation from @sparr that the bug is truly fixed.

**Comment by sparr** [comment]
When I load my save with negative power, I see it negative in-game for 1 or 2 turns, then it goes to zero.

**Comment by KA101** [comment]
OK, probably an update-cycling thing.  I'd call that fixed; thanks, and closing.
