### ISSUE TITLE
Music does not play. 

### ISSUE THREAD

**Issue by shirishag75** [CleverRaven/Cataclysm-DDA#11670]
Hi all, 
I downloaded the music pieces as shared at http://smf.cataclysmdda.com/index.php?topic=6455.0 . This can be seen at :-

    ~/games/Cataclysm-DDA/data/sound$ll -h                                                                                                             
    total 17M
    -rw-r--r-- 1 shirish shirish 7.6M May 15  2014 cataclysmthemeREV6.ogg
    -rw-r--r-- 1 shirish shirish 8.8M May 15  2014 Dark_Days_Ahead_demo_2.ogg
    -rw-r--r-- 1 shirish shirish  399 Mar 18 05:15 soundset.json

I also looked at the soundset.json file and it shows these two files as well :-

    [$] cat soundset.json                                                                                                               
    {
        "playlists" : [
            {
                "id" : "title",
                "shuffle" : false,
                "files" : [
                    {
                        "file": "Dark_Days_Ahead_demo_2.ogg",
                        "volume": 128
                    },
                    {
                        "file": "cataclysmthemeREV6.ogg",
                        "volume": 90
                    }
                ]
            }
        ]
    }

changing shuffle from false to true does nothing. Maybe it has something to do with pulseaudio or something else altogether, can somebody help. I am willing to test if somebody takes the time to figure things out.

**Comment by BevapDin** [comment]
Just to make sure: you use the tiles version (sound is not included in the curses version)?

Have you checked the "Music Volume" in the option menu? If that option is not there, you definitely have the wrong version of the game.

Please show the content of the log file (config/debug.log), it will contain errors that have been encountered.

**Comment by shirishag75** [comment]
yup, using the tiles version. 

    ~/games/Cataclysm-DDA$./cataclysm-tiles  

This is the content of the config/debug.log . I have been liberal with my character for points and all. Dunno why the language is set as .cs when it should be en. 

    ~/games/Cataclysm-DDA/config$cat debug.log                                                                                                                   
    
    -----------------------------------------
    1:17:45.237 : Starting log.
    1:17:45.300 INFO : Language is set to: 'cs'
    1:17:47.179 INFO : mod_ui initialized
    1:17:54.529 INFO : Loaded material: Unknown
    1:17:54.529 INFO : Loaded material: Vegetable Matter
    1:17:54.529 INFO : Loaded material: Fruit Matter
    1:17:54.529 INFO : Loaded material: Honey
    1:17:54.529 INFO : Loaded material: Wheat
    1:17:54.529 INFO : Loaded material: Junk Food
    1:17:54.529 INFO : Loaded material: Flesh
    1:17:54.529 INFO : Loaded material: Powder
    1:17:54.529 INFO : Loaded material: Water
    1:17:54.529 INFO : Loaded material: Dairy
    1:17:54.529 INFO : Loaded material: Insect Flesh
    1:17:54.529 INFO : Loaded material: Human Flesh
    1:17:54.530 INFO : Loaded material: Cotton
    1:17:54.530 INFO : Loaded material: Wool
    1:17:54.530 INFO : Loaded material: Leather
    1:17:54.530 INFO : Loaded material: Kevlar
    1:17:54.530 INFO : Loaded material: Ceramic
    1:17:54.530 INFO : Loaded material: Fur
    1:17:54.530 INFO : Loaded material: Chitin
    1:17:54.530 INFO : Loaded material: Bone
    1:17:54.530 INFO : Loaded material: Stone
    1:17:54.530 INFO : Loaded material: Paper
    1:17:54.530 INFO : Loaded material: Wood
    1:17:54.530 INFO : Loaded material: Plastic
    1:17:54.531 INFO : Loaded material: Glass
    1:17:54.531 INFO : Loaded material: Iron
    1:17:54.531 INFO : Loaded material: Steel
    1:17:54.531 INFO : Loaded material: Superalloy
    1:17:54.531 INFO : Loaded material: Diamond
    1:17:54.531 INFO : Loaded material: Hard Steel
    1:17:54.531 INFO : Loaded material: Silver
    1:17:54.531 INFO : Loaded material: Nomex
    1:17:54.531 INFO : Loaded material: Gold
    1:17:54.531 INFO : Loaded material: Aluminum
    1:17:54.531 INFO : Loaded material: Lead
    1:17:54.531 INFO : Loaded material: Egg
    1:17:54.531 INFO : Loaded material: Fresh Clay
    1:17:54.532 INFO : Loaded material: Clay
    1:17:54.532 INFO : Loaded material: Alcohol
    1:17:54.532 INFO : Loaded material: Oil
    1:17:54.532 INFO : Loaded material: Hydrocarbons
    1:17:54.671 INFO : Loaded profession: bionic_prepper
    1:17:54.671 INFO : Loaded profession: unemployed
    1:17:54.671 INFO : Loaded profession: sheltered_survivor
    1:17:54.671 INFO : Loaded profession: tailor
    1:17:54.671 INFO : Loaded profession: chef
    1:17:54.671 INFO : Loaded profession: labtech
    1:17:54.671 INFO : Loaded profession: mechanic
    1:17:54.672 INFO : Loaded profession: scoundrel
    1:17:54.672 INFO : Loaded profession: beekeeper
    1:17:54.672 INFO : Loaded profession: basketball_player
    1:17:54.672 INFO : Loaded profession: cyclist
    1:17:54.672 INFO : Loaded profession: soldier
    1:17:54.672 INFO : Loaded profession: specops
    1:17:54.673 INFO : Loaded profession: maid
    1:17:54.673 INFO : Loaded profession: medic
    1:17:54.673 INFO : Loaded profession: gangster
    1:17:54.673 INFO : Loaded profession: security
    1:17:54.673 INFO : Loaded profession: survivalist
    1:17:54.673 INFO : Loaded profession: smoker
    1:17:54.673 INFO : Loaded profession: crackhead
    1:17:54.673 INFO : Loaded profession: homeless
    1:17:54.674 INFO : Loaded profession: tweaker
    1:17:54.674 INFO : Loaded profession: cop
    1:17:54.674 INFO : Loaded profession: detective
    1:17:54.674 INFO : Loaded profession: swat
    1:17:54.674 INFO : Loaded profession: salesman
    1:17:54.674 INFO : Loaded profession: bow_hunter
    1:17:54.674 INFO : Loaded profession: construction_worker
    1:17:54.674 INFO : Loaded profession: lumberjack
    1:17:54.675 INFO : Loaded profession: backpacker
    1:17:54.675 INFO : Loaded profession: fastfoodcook
    1:17:54.675 INFO : Loaded profession: electrician
    1:17:54.675 INFO : Loaded profession: hacker
    1:17:54.675 INFO : Loaded profession: student
    1:17:54.675 INFO : Loaded profession: svictim
    1:17:54.675 INFO : Loaded profession: biker
    1:17:54.675 INFO : Loaded profession: dancer
    1:17:54.675 INFO : Loaded profession: bionic_thief
    1:17:54.676 INFO : Loaded profession: bionic_patient
    1:17:54.676 INFO : Loaded profession: patient
    1:17:54.676 INFO : Loaded profession: mutant_patient
    1:17:54.676 INFO : Loaded profession: mutant_volunteer
    1:17:54.676 INFO : Loaded profession: bionic_worker
    1:17:54.676 INFO : Loaded profession: bionic_athlete
    1:17:54.676 INFO : Loaded profession: bionic_cop
    1:17:54.676 INFO : Loaded profession: bionic_firefighter
    1:17:54.677 INFO : Loaded profession: bionic_mentat
    1:17:54.677 INFO : Loaded profession: bio_soldier
    1:17:54.677 INFO : Loaded profession: bio_sniper
    1:17:54.677 INFO : Loaded profession: bionic_spy
    1:17:54.677 INFO : Loaded profession: bionic_hitman
    1:17:54.677 INFO : Loaded profession: faulty_bionic
    1:17:54.677 INFO : Loaded profession: bionic_customer
    1:17:54.678 INFO : Loaded profession: hitchhiker
    1:17:54.678 INFO : Loaded profession: trapper
    1:17:54.678 INFO : Loaded profession: blacksmith
    1:17:54.678 INFO : Loaded profession: clown
    1:17:54.678 INFO : Loaded profession: lost_sub
    1:17:54.678 INFO : Loaded profession: senior
    1:17:54.678 INFO : Loaded profession: cosplay
    1:17:54.678 INFO : Loaded profession: goalie
    1:17:54.678 INFO : Loaded profession: batter
    1:17:54.678 INFO : Loaded profession: linebacker
    1:17:54.679 INFO : Loaded profession: golfer
    1:17:54.679 INFO : Loaded profession: spouse
    1:17:54.679 INFO : Loaded profession: punkrockgirl
    1:17:54.679 INFO : Loaded profession: firefighter
    1:17:54.679 INFO : Loaded profession: skaboy
    1:17:54.679 INFO : Loaded profession: postman
    1:17:54.679 INFO : Loaded profession: convict
    1:17:54.679 INFO : Loaded profession: razorgirl
    1:17:54.680 INFO : Loaded profession: cyberjunkie
    1:17:54.680 INFO : Loaded profession: cykotic
    1:17:54.680 INFO : Loaded profession: lawyer
    1:17:54.680 INFO : Loaded profession: priest
    1:17:54.680 INFO : Loaded profession: shinto_priest
    1:17:54.680 INFO : Loaded profession: imam
    1:17:54.680 INFO : Loaded profession: rabbi
    1:17:54.681 INFO : Loaded profession: guru
    1:17:54.681 INFO : Loaded profession: preacher
    1:17:54.681 INFO : Loaded profession: blackbelt_novice
    1:17:54.681 INFO : Loaded profession: blackbelt_intermediate
    1:17:54.681 INFO : Loaded profession: blackbelt
    1:17:54.681 INFO : Loaded profession: pizzaboy
    1:17:54.681 INFO : Loaded profession: archaeologist
    1:17:54.682 INFO : Loaded profession: paperboy
    1:17:54.682 INFO : Loaded profession: rollerderby
    1:17:54.682 INFO : Loaded profession: farmer
    1:17:54.682 INFO : Loaded profession: national_guard
    1:17:54.682 INFO : Loaded profession: winter_survivor
    1:17:54.682 INFO : Loaded profession: winter_scavenger
    1:17:54.682 INFO : Loaded profession: mall_cop
    1:17:54.683 INFO : Loaded profession: naturalist
    1:17:54.683 INFO : Loaded profession: fisher
    1:17:54.683 INFO : Loaded profession: reenactor
    1:17:54.683 INFO : Loaded profession: reenactor2
    1:17:54.683 INFO : Loaded profession: drone_op
    1:17:54.683 INFO : Loaded profession: elementary_student
    1:17:54.684 INFO : Loaded profession: skaterkid
    1:17:54.684 INFO : Loaded profession: jdelinquent
    1:17:54.684 INFO : Loaded profession: prep_student
    1:17:54.684 INFO : Loaded profession: jr_survivalist
    1:17:54.684 INFO : Loaded profession: bionic_student
    1:17:54.684 INFO : Loaded profession: dodgeball_player
    1:17:54.684 INFO : Loaded profession: science_club_mem
    1:17:54.685 INFO : Loaded profession: av_club_mem
    1:17:54.685 INFO : Loaded profession: janitor
    1:17:54.685 INFO : Loaded profession: teacher
    1:17:54.685 INFO : Loaded profession: gym_teacher
    1:17:54.685 INFO : Loaded profession: poor_student
    1:17:54.686 INFO : Loaded skill: bartering
    1:17:54.686 INFO : Loaded skill: computers
    1:17:54.687 INFO : Loaded skill: construction
    1:17:54.687 INFO : Loaded skill: cooking
    1:17:54.687 INFO : Loaded skill: driving
    1:17:54.687 INFO : Loaded skill: electronics
    1:17:54.687 INFO : Loaded skill: fabrication
    1:17:54.687 INFO : Loaded skill: first aid
    1:17:54.687 INFO : Loaded skill: mechanics
    1:17:54.687 INFO : Loaded skill: speaking
    1:17:54.687 INFO : Loaded skill: survival
    1:17:54.687 INFO : Loaded skill: swimming
    1:17:54.687 INFO : Loaded skill: tailoring
    1:17:54.687 INFO : Loaded skill: trapping
    1:17:54.687 INFO : Loaded skill: archery
    1:17:54.687 INFO : Loaded skill: bashing weapons
    1:17:54.687 INFO : Loaded skill: cutting weapons
    1:17:54.687 INFO : Loaded skill: dodging
    1:17:54.687 INFO : Loaded skill: marksmanship
    1:17:54.687 INFO : Loaded skill: launchers
    1:17:54.687 INFO : Loaded skill: melee
    1:17:54.687 INFO : Loaded skill: piercing weapons
    1:17:54.687 INFO : Loaded skill: throwing
    1:17:54.687 INFO : Loaded skill: unarmed combat
    1:17:54.687 INFO : Loaded skill: handguns
    1:17:54.687 INFO : Loaded skill: rifles
    1:17:54.687 INFO : Loaded skill: shotguns
    1:17:54.687 INFO : Loaded skill: submachine guns
    1:17:56.842 INFO : Loaded scenario: evacuee
    1:17:56.842 INFO : Loaded scenario: missed
    1:17:56.843 INFO : Loaded scenario: infected
    1:17:56.844 INFO : Loaded scenario: fire
    1:17:56.844 INFO : Loaded scenario: bad_day
    1:17:56.844 INFO : Loaded scenario: lab_chal
    1:17:56.844 INFO : Loaded scenario: ambushed
    1:17:56.844 INFO : Loaded scenario: alone
    1:17:56.845 INFO : Loaded scenario: patient
    1:17:56.845 INFO : Loaded scenario: mutant
    1:17:56.845 INFO : Loaded scenario: mall_cop
    1:17:56.845 INFO : Loaded scenario: last_firefighter
    1:17:56.845 INFO : Loaded scenario: precinct_zed
    1:17:56.845 INFO : Loaded scenario: wilderness
    1:17:56.965 INFO : Loaded profession: fighter
    1:17:56.965 INFO : Loaded profession: rogue
    1:17:56.965 INFO : Loaded profession: barbarian
    1:17:56.966 INFO : Loaded profession: ranger
    1:17:56.966 INFO : Loaded profession: monk
    1:17:56.967 INFO : Loaded profession: knight
    1:17:56.967 INFO : Loaded profession: wizard
    1:17:56.967 WARNING : opendir [./save//Verplanck/mods] failed with "Adresář nebo soubor neexistuje".
    1:18:32.323 : Log shutdown.

I am using the git latest version, made it using the following commands :-

    ~/games/Cataclysm-DDA$make TILES=1 RELEASE=1

I am available to build the game with more debugging symbols if that helps, will just need to know which commands to do while running make if that is to be done.

**Comment by BevapDin** [comment]
> ~/games/Cataclysm-DDA$make TILES=1 RELEASE=1

Music is not automatically added with tiles, you have to add `SOUND=1` to the command.

**Comment by shirishag75** [comment]
umm.. then why is that not documented, this is not a bug per-se it's more of a documentation bug then.

**Comment by BevapDin** [comment]
It is documented in the Makefile and in COMPILING.md. Please make a pull request for where it should be documented additionally.

**Comment by shirishag75** [comment]
needs to be added here as well http://www.wiki.cataclysmdda.com/index.php?title=How_to_compile . Please add to it.

**Comment by KA101** [comment]
It's a wiki.  You're just as qualified to add it, though if you'd rather not we can see about it.
