### ISSUE TITLE
Allow random elements in JSON mapgen submaps with preprocessor

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11673]
Right now a few bits of json mapgen can involve randomness, such as item placement. However, this still  leaves most random generation behavior in the realm of C++ mapgen_functions. My idea is to extend the mapgen json format as follows:

Take any existing valid mapgen json, and replace any element (object, array, or value) with an object as follows:

    {
        "mapgen_random" : "arbitrary name for this random block",
        "options" : 
        [
            [ weight_integer, replacement_element ],
            [ weight_integer, replacement_element ]
            ...
        ]
    }

Then, after any mapgen json is loaded, a preprocessor will be applied to it. This preprocessor will recursively traverse the data looking for objects with a mapgen_random key, and replacing those objects with one of the replacement_element from the array inside, weighted according to the weight_integers specified.

So, say we have a map with two toilets, and currently the place_toilets feature does not allow for randomness:

    ...
    "place_toilets": [
        { "x": 2, "y": 21 },
        { "x": 6, "y": 21 }
    ],
    ...

If we want to randomly choose the existing toilet configuration 75% of the time, and a new configuration with the toilets closer together 25% of the time, we could replace that block of json with this:

    ...
    "place_toilets":
        {
            "mapgen_random" : "toilets",
            "options" : 
            [
                [ 75,
                    [
                        { "x": 2, "y": 21 },
                        { "x": 6, "y": 21 }
                    ]
                ],
                [ 25,
                    [
                        { "x": 3, "y": 21 },
                        { "x": 5, "y": 21 }
                    ]
                ]
            ]
        }
    ...

Having written that example out, it feels a bit bulky, but it's the best I could come up with while maintaining 100% backwards compatibility (no need to modify existing json files) and allowing random choice of every possible bit of map generation within a json file.

I submit this for feedback and improvement suggestions.

**Comment by sparr** [comment]
This could be made more concise, but less data-pure, if instead of an object with two keys we simply use an array where the first entry is a flag to get the attention of the preprocessor:

    ...
    "place_toilets":
        [
            "mapgen_random",
            [ 75,
                [
                    { "x": 2, "y": 21 },
                    { "x": 6, "y": 21 }
                ]
            ],
            [ 25,
                [
                    { "x": 3, "y": 21 },
                    { "x": 5, "y": 21 }
                ]
            ]
        ]
    ...

**Comment by BevapDin** [comment]
The hierarchy you suggested ("what" -> "random choice" -> "possible locations") is probably not very useful, because it does not allow spawning several things randomly but *together*, e.g. a display rack (placed randomly in the house) and items in it. You could make entries for the items to spawn randomly, and for the rack, but those two things would not necessarily spawn on the same (randomly chosen) place.

Therefor I suggest the other way:
```JSON
"where": [
    { "weight": 100, "x": 1, "y": 1 },
    { "weight": 50, "x": 4, "y": 1 },
    { "weight": 200, "x": 7, "y": 4 }
],
"what": [
    { "furniture": "f_rack" },
    { "items": "museum", "chance": 10 }
]
```
This would spawn the rack and the items on the very same place all the time.

It also nicely separates the "what" and the "where" which makes it easier to implement and way easier to extend.

**Comment by sparr** [comment]
Closing this based on info found in #11591
