### ISSUE TITLE
Vehicle rotation with multiple shears/skews instead of one

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11680]
I am not a huge fan of the current vehicle rotation system, which seems to only ever use a single shear/skew operation. I've got an idea to represent the rotated vehicles more accurately, but I'm not sure if it would be a problem for other game mechanics.

    Base zero degree layout:
    ^^^^
    ====
    +##+
    |--|
    |HH|
    -++-

    Current 25 degree rotation:
    ^^^^
    ====
     +##+
     |--|
      |HH|
      -++-

    New 25 degree rotation:
      ^^
    ^^==
    ==#+
    +#--|
     |HH|
     |++-
     -  

    Current 45 degree rotation:
    ^^^^
     ====
      +##+
       |--|
        |HH|
         -++-

    New 45 degree rotation:
       ┌    
      ┌=+
     ┌=#\\
    ┌=#/H/
    =+/H+
     \\+    
      /

My primary concern is that the bounding box of the vehicle currently only changes on one axis at a time. A 4x6 car will always be either 4 on one axis or 6 on one axis. With my proposal, a 4x6 car would be have a bounding box of up to 6x7 at some angles.

If there's some other problem that I've overlooked, I hope someone can point it out to me.

I feel like this change will allow a lot of other fixes and improvements to be implemented more easily, such as vehicle dragging (which currently breaks because vehicle rotation moves vehicle tiles more than one tile at a time) and vehicle towing (which is going to be difficult to implement anyway).

**Comment by kevingranade** [comment]
I can hardly recognize the new layouts, it might just take some getting
used to, but my initial impression is very poor.  It's definitely not an
improvement.

**Comment by sparr** [comment]
@kevingranade comment on the PR instead? it has a screenshot, and code, and at least one more vaguely compelling argument in favor of this approach.
