### ISSUE TITLE
allow balanced multi-tile one-wheel vehicle

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11686]
Currently a vehicle with one wheel only has "enough" wheels if it only has one tile of parts. I'd like to add the option to have a multi-tile one-wheel vehicle, with the caveat that the vehicle has to be balanced. We already have a method for finding the center of mass of a vehicle, so we could check if that's the tile containing the wheel.

**Comment by KA101** [comment]
Good luck keeping it balanced in use; apart from that, have at it.

**Comment by kevingranade** [comment]
Huh? You're talking about a vehicle that's over a meter long by definition, how is that staying upright with one wheel?

**Comment by sparr** [comment]
@kevingranade however it is that one-wheel "STABLE" vehicles stay upright already.

**Comment by KA101** [comment]
>how is that staying upright with one wheel?

Magical battletech gyroscope stuff, I'd guess.  ;-)

**Comment by ejseto** [comment]
The same way a unicycle stays upright. How are gyroscopes magical?

**Comment by sparr** [comment]
I'm gonna prematurely close this issue so it stops getting comments and hopefully people will comment on the PR instead. #11691

**Comment by KA101** [comment]
Battletech gyroscopes are the only thing keeping the giant walking armor upright, theoretically.  I'm not entirely sure how they're supposed to work and have never seen a good explanation.

But MW2: Mercs wasn't a bad game.

**Comment by sparr** [comment]
@KA101 since we aren't letting this thread die... https://www.youtube.com/watch?v=n_6p-1J551Y&t=45

**Comment by ejseto** [comment]
Are you saying you don't know how a gyroscope works, or you don't know how a *Battletech* gyroscope works? A gyroscope works on the same principle as rifled firearms. When something spins, it resists changes in the direction of its axis of rotation. The physics explanation is simple conservation of angular momentum. The layman's explanation is that a spinning top, for example, when it's about to tip over, the part that's falling quickly finds itself on the other side, falling the opposite direction, causing it to remain upright.

As for *Battletech* gyroscopes, I imagine that the gyro simply allows the mech to know which way is up, allowing it to remain oriented and standing.

**Comment by Rivet-the-Zombie** [comment]
Battletech gyros also resist tipping and impacts using counterforce reaction wheels. But keep in mind that we're talking about fictional gyroscopes that weigh multiple tons, too.

**Comment by sparr** [comment]
You really should check out that youtube link I posted. It's not just noise.

**Comment by ejseto** [comment]
I did. It's pretty cool, but not particularly interesting after the whole "huh, I guess that actually would work" revelation.

**Comment by Rivet-the-Zombie** [comment]
Careful, if you manage to tip it over *The Order of the Gash* comes out and wants to play.
