### ISSUE TITLE
Trap detection not applying new encumbrance.

### ISSUE THREAD

**Issue by DanmakuDan** [CleverRaven/Cataclysm-DDA#11689]
I stood next to the expected trap location of a dissector without detecting it, while in a lab and wearing light amp goggles (3*10 enc due to wearing another mask). Even the goo traps remained invisible. The -30 penalty makes it impossible to detect anything.

I think p.per_cur (line 69, bool trap::detect_trap trapdef.cpp) just needs to be multiplied by 10, if someone could confirm.

**Comment by PropaneSoup** [comment]
Divided by ten, but yea, I missed that. Getting a fix in now.
