### ISSUE TITLE
vehicle welding rig has some a couple of issues

### ISSUE THREAD

**Issue by nonymous** [CleverRaven/Cataclysm-DDA#11682]
It seems like  the welding rig recipe's required tools should allow the acetylene torch as an option.
Can't install a welding rig (volume 80) unless it is in your inventory.  Probably should be able to install it if it's at your feet.

**Comment by Rivet-the-Zombie** [comment]
The recipe assumes that you're soldering together small electrical components. That's not going to happen with an acetylene torch.

As for not being able to install it without having it in your inventory, that's a bug.

**Comment by nonymous** [comment]
It sounds like maybe you shouldn't be able to use a welder either, but a soldering iron.

**Comment by Catacstone** [comment]
Testing with 0.C-452-gcedb681, installation of welding rig works fine if the welding rig is anywhere accessible near you (welders & torch need welding goggles, as they should).

**Comment by Rivet-the-Zombie** [comment]
Wow, that was quick! Thanks, @Catacstone.

>It sounds like maybe you shouldn't be able to use a welder either, but a soldering iron.

Our 'welder' is so vague that it could be anything from a SMAW buzzbox to a MIG cabinet. Since it already fulfills the recipe requirement for a soldering iron in every other recipe, it's safe to assume that it will also work as a soldering iron in this one.

**Comment by nonymous** [comment]
Thanks, that happened since 2856, I should have updated to double check.

**Comment by nonymous** [comment]
So if it works as a soldering iron in this case, why isn't a soldering iron an equivalent tool?  I would think if it was supposed to be a welder, acetylene would work, if it was supposed to be a soldering iron, soldering iron would work.  There's not really a lot of places where one can't be used as another.  Soldering could be done with an acetylene torch and say a screwdriver or any hot piece of metal as long as you don't burn yourself.

**Comment by narc0tiq** [comment]
If memory serves, the reason the welding rig works as a soldering iron is
because it contains one. As in, a soldering iron is part of the recipe.

Did this change?

**Comment by Rivet-the-Zombie** [comment]
>Did this change?

No, it's still in there.
