### ISSUE TITLE
Rebalance profession costs

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11699]
I haven't gotten much traction in #11573, so this new issue is to suggest that a human audit happen. I'm willing to put some brainpower to work on the task, but I don't have enough experience with the game to be sure about more mid-to-late-game stuff.

To illustrate why I think this needs to happen, I want to highlight one current situations:

Survivor costs 0 points.
Survivalist Jr costs 3 points.
Survivalist costs 3 points.

Comparing Survivalist Jr to Survivor... Jr gets what I think is a superior inventory, basically trading (knife, matches, winter coat, winter boots) for (scissors, magnifying glass, flashlight, first aid kit, backpack). Then it includes three skill levels, worth ~1.5-3 points. Maybe Jr should cost 4 points instead of 3, or maybe 3 is right.

Now, comparing Survivalist to Survivor, things get crazy. Survivalist takes it up another notch. He trades a bit more warm clothes for even better functional starting items, which already makes him a little better than Jr in my mind. Then he gets 14 skill levels, worth ~8-14 points. Even if we say that packaged skills are less valuable than a-la-carte skills, 8 points worth of skills should cost a lot more than 3 points. Maybe 6 or 7?

Above I've assumed that skill levels are the definitive value basis for points. That doesn't have to be true. We could, instead, say that stat costs are the baseline. Either way, some of the professions are mis-priced.
##

**Comment by Griffinhart** [comment]
I say just remove Professions as they are (or replace it with a text field so that players can have custom profession titles), allow money to be bought with character creation points, and then allow gear to be purchased with aforementioned money.

**Comment by Rivet-the-Zombie** [comment]
A price audit would be a good thing.

>just remove Professions

This would not. The system needs tweaking, but it's not broken.

**Comment by KA101** [comment]
I've explained this repeatedly: skills are one factor; gear/absence thereof is another, addictions/bionics are a third.  Sure, we can audit 'em, and then we run into folks with differing philosophies: some feel that professions are there to start things faster and should be cheap, others that they're there to be a Serious Choice and should be expensive.

**Comment by sparr** [comment]
@KA101 skills vs gear vs addictions/bionics isn't really a solid position when we're comparing professions with no addictions, no bionics, and similar gear (or we just ignore the presence of better gear). Is there anyone who thinks that Survivor's tiny advantage of winter clothing makes up for the ~4 point under-cost of its skills?

**Comment by KA101** [comment]
>Sure, we can audit 'em

I'm not even disagreeing with you, for fae's sake.  Last audit was a while ago and ran into its own problems, namely the philosophical differences.

**Comment by sparr** [comment]
Here's a diff of all the professions against the default Survivor: https://gist.github.com/sparr/e6ec6470022e66ef35a1

I'll comment with my thoughts shortly.

**Comment by sparr** [comment]
First thought: We have a lot of professions. It's already annoying to search through it in-game. We might want to think about adding a category system. I'll also eventually side with the folks that want more of a "build" system for items and such.

More on topic, for now I'm just going to pick out the professions that seem to be underpriced by at least a couple of points. I'm going to give costs here as (profession point cost - point value of granted skill levels), since as I mentioned above, I'm using skill levels as my baseling. There's a good argument to be made that stat levels should be the baseline, but that adds more variables to consider here. And I'll be comparing starting items to Survivor.

bio_sniper costs -0.5 for a useful set of starting equipment and CBMs.

blackbelt gets a combat style and gives up all useful equipment. however, his net cost is a ridiculous -40, paying 8 points for 48 points worth of skill levels. this might indicate that high skill levels are over-priced, but that's not super relevant to most other professions that don't give more than 2-4 levels in any skill.

gangster costs -3 for equipment that's pretty useful, albeit no winter clothes.

naturalist, like blackbelt, highlights excessive skill costs. -21.5 points net cost, on top of a really nice set of practical starting items.

reenactor breaks even on skill cost, then gets a nicer set of starting items.

ditto reenactor2.

scoundrel costs -3 with an item set that seems on par.

sheltered_survivor costs -3 and trades his winter clothes for a multitool.

soldier breaks even on cost and gets a really nice set of items.

specops costs -2 with an even nicer set of items, so if nothing else specops-vs-soldier needs balancing in some way

survivalist costs -6 (the biggest skill discount of any profession that doesn't have single really high skills) and has nice items.

swat costs -1 and is well equipped for combat similarly to soldier.

Trapper costs -3 and trades matches for a bear trap, which I see as a win.

winter_scavenger is another large negative cost, -12, with great starting items.

ditto winter_survivor, at -18.

over-priced cheap professions:
convict is barely better than the shower victim. he should probably be -1 point, not 0. 
golfer is better than those two, but not as useful as survivor, maybe he should be -1, and convict/shower/hitchhiker should be -2, with tweaker down at -3?

**Comment by John-Candlebury** [comment]
While at it, I wanted to say that I think all the kid professions should have some sort of mechanical difference rather than just being different item lists. Should probably make them  more interesting .

- At the very least their Strength, Int and Dex should be capped. Perhaps as 8 as it max, which would probably be already very good for a kid between 10 and 15.
-Force some equivalent to the bad back trait.
-Melee combat disadvantage.
+Bonus to recruiting Npc followers.
+Good base perception.
-/+ Some other stuff

Also Some sort of categories for the profession menu could perhaps be helpful, list is getting pretty big.

**Comment by Zireael07** [comment]
@John-Candlebury: That's a great idea!

**Comment by kevingranade** [comment]
Not in principle adressable.

**Comment by sparr** [comment]
@kevingranade can you elaborate on the principle(s) in question? I feel like I made a pretty good case above about the relative value of the various skill and gear packages for a lot of the non-bionic non-addict professions. @KA101 suggested there will be differences in philosophies on particular issues, but I have a hard time believing anyone could say in good faith that Survivor and Survivalist and Naturalist are balanced.

**Comment by kevingranade** [comment]
There is no clear way to call this "done", and it has had no action for
over a year.  The status quo is it sitting here and doing no one any good.
