### ISSUE TITLE
Possibility to select what vehicle part in particular we want to mount

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#11706]
At the moment when installing vehicle parts and there are several of them with various condition, we don't have possibility to choose which one is to mount.
This is also especially inconvenient if we have multiple diameter wheels in inventory or in vicinity. Don't know what wheel in particular the game will install (last added to inventory? closest to player? random?).
I suggest to add some menu like "Install what?" (maybe like the one that the game shows when trying to reload weapon that can accept several ammo types) when clicking on installable part.
##

**Comment by KA101** [comment]
Diameters don't matter, probably for this reason.  So yeah.

**Comment by drbig** [comment]
Wheel sizes should and hopefully will matter. And besides: engines. There should be a way to select a particular part.

**Comment by BevapDin** [comment]
For now, you this technique:
- Drop all items (of the type you are going to install, e.g. all wheels, or all wide wheels) on the map or into a cargo vehicle part (in vehicle part counts as on the map).
- Keep the item you want to install in your inventory.
- When the installation finishes, the game will ask you which item to use, you can choose between items on the map (marked as "(nearby)" or items in you inventory (not marked). Chose the item in you inventory.

**Comment by drbig** [comment]
@BevapDin Indeed, and that should be imo easy to work out on your own, but it's still a workaround. For example you are going to be explicitly asked which welding tool to use if you have more than one. Having to do this item juggling is simply inconsistent. In a corner caste it prevents players from building a 'welding shop' and using it in a sane manner :)

**Comment by BevapDin** [comment]
> For example you are going to be explicitly asked which welding tool to use if you have more than one.

You're asked which **type** of tool you want to use. If you have several welders, it won't ask which welder to use (the damaged one, the half-full one, the one with the inscription).

But as all wheels are the same type (wheels is one type, wide wheels is another type, small wheel another), only different size, this won't apply there. A 9'' wheel has the same type as a 11'' wheel.

**Comment by drbig** [comment]
@BevapDin Fair point, and makes sense for tools, which are equivalent regardless of their state... 

Which might change someday - one should imagine using a badly damaged acetylene torch to not be such a good idea ('will it blow up?' is the question). But that's a tangent.

For the main topic - I'm for the vehicle construction menu to explicitly ask for a part when there are more parts of that type available and they do *differ*. This includes not only engines, but also any part where more than one item state/quality is available. It will also include wheels when the more realistic vehicle patches get in.

Ultimately it's about consistency and... yes: user experience.

**Comment by Night-Pryanik** [comment]
Closing after #17209.

**Comment by mugling** [comment]
Does #17209 actually resolve that issue?

**Comment by Night-Pryanik** [comment]
Uhmm, it seems no.

**Comment by Coolthulhu** [comment]
`consume_items` only understands ids and vague location (on player vs. on map). #17209 uses `consume_items`.

**Comment by mugling** [comment]
This is a deficiency I would like to correct
