### ISSUE TITLE
implanted night vision hides color in ascii mode, no missing info in tile mode

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11715]
Using the night vision CBM makes everything green in ascii mode. In tiles mode it has no effect on visible tiles. This is a strange discrepancy.

**Comment by KA101** [comment]
Not so strange if we don't have a way to throw an overlay on the tiles, and I'm not sure that we do.  Otherwise, sure, NVGreen would be the desired effect.

**Comment by OzoneH3** [comment]
Should be possible after this #13715 gets in.
