### ISSUE TITLE
Does the tileset need to be reloaded when tiles are turned off?

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11713]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/options.cpp#L1295-L1327

When the tileset changes or tiles are enabled/disabled, we re-init the tilecontext. Do we really need to do that when tiles are *disabled*? I can fix this quickly, but didn't want to submit a PR yet in case there's a reason for doing this.

**Comment by illi-kun** [comment]
Test it and PR the changes if you see (and can describe) benefits from it.
