### ISSUE TITLE
Lab mapgen hallway misalignment

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11728]
https://www.dropbox.com/s/sjadls4fuhrnfxs/Screenshot%202015-03-21%2022.43.30.png?dl=0

In this screenshot I am at the south end of one submap in a 2-wide hallway. The submap south of me has a 3-wide hallway  offset one tile too far to the left.
##

**Comment by sparr** [comment]
https://www.dropbox.com/s/t2zd3cwlg6bnc2j/Screenshot%202015-03-21%2022.46.15.png?dl=0

Here's another possible problem. Southeast corner of a submap with two halls and four rooms. Room south of me, on another submap, seems to have a wall where it shouldn't.

**Comment by BevapDin** [comment]
Hint: for better screenshots use the debug and either chose "Spawn Clairvoyance Artifact", or go into the Map editor and press 'v' to make every square on the map visible. Using the map editor that way (without actually editing the map) won't affect your game, whereas the "Clairvoyance Artifact" changes your world (by adding that artifact).

And of course this might spoil your game by showing other content of the map.

**Comment by DavidKeaton** [comment]
also it's aptly named `editmap_nsa_view`, lol

**Comment by sparr** [comment]
another problem, this time within a single submap: https://www.dropbox.com/s/vs4bwpfh2yx83dr/Screenshot%202015-03-24%2016.54.24.png?dl=0

**Comment by Leland** [comment]
Closing this in favor of the master science lab issue #10958.

This _is_ a particularly weird one, but since it's only been seen in the science lab I think it's appropriate. Definitely on the edge with this one, though.
