### ISSUE TITLE
Why can't the AIM move all items from AIM_ALL?

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11721]
```
if( spane.area == AIM_ALL ) {
    popup( _( "You have to choose a source area." ) );
    return false;
}
```

Is this just because the code to move items from all areas would be more complex? I'd like to take a crack at implementing it, if that's the only reason.
##

**Comment by Rivet-the-Zombie** [comment]
That'd be my guess. I'd love for it to work; it would make cleaning up an area sooooooo very much faster and easier.

**Comment by kevingranade** [comment]
Just complicated yea.

**Comment by DavidKeaton** [comment]
I'm planning on getting this in at some point soon.

**Comment by sethsimon** [comment]
This feature was implemented quite awhile ago, so this issue can be closed.
