### ISSUE TITLE
Folding vehicles require controls?

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11723]
There doesn't seem to be a way to fold up a folding vehicle without giving it controls. That seems rather silly for things like a folding shopping cart. Perhaps the controls dialog should be reachable for some specific subset of vehicles without controls (possibly just foldable vehicles)?

**Comment by DavidKeaton** [comment]
controls sole purpose is interaction

**Comment by sparr** [comment]
They make my folding gear too bulky :(

Maybe we need a new kind of controls for small vehicles. lower foldvol, doesn't interface with anything electric.

**Comment by DavidKeaton** [comment]
perhaps make the frame part for a shopping cart a new flag, `COLLAPSIBLE` or something. then in iexamine.cpp or pickup.cpp test for flag and add an option to fold it. :-)

**Comment by Zireael07** [comment]
+1 for small controls idea.

**Comment by drbig** [comment]
Yeah, vehicle controls on a folding cart are outright confusing. One already needs a folding frame and a folding basket - I assume they have a latch/other simple 'control' mechanism already built-in, so I'd suggest no additional part - examining such a vehicle should check if the components are all foldable (casters could get the foldable flag, or just check if it's 'all foldable + casters' explicitly if we want to limit the wheel selection) and if yes show a menu with 'Fold vehicle' and usual 'Get items' options.

**Comment by DavidKeaton** [comment]
@drbig well stated, my answer was at the early hours.

**Comment by sparr** [comment]
What if folding was moved from the [^] menu to the [e] menu entirely? I think right now folding is the only [^] menu item that never works when you're sitting in the driver's seat, so it's already exceptional.

**Comment by DavidKeaton** [comment]
I was thinking this already. `pickup.cpp` and/or `iexamine.cpp` is where you want to make additions and checks iirc.

**Comment by drbig** [comment]
@sparr Exactly from [^] to [e].

**Comment by sparr** [comment]
Thanks for the pointers @DavidKeaton !

**Comment by DavidKeaton** [comment]
@sparr np bro :-)
