### ISSUE TITLE
Multiple Fonts

### ISSUE THREAD

**Issue by Podesta** [CleverRaven/Cataclysm-DDA#11727]
I would like to know if it would be possible to use different fonts for different aspects of the game, somewhat similar to what we already have on the config>fonts,  that we can choose three different fonts (though I tried to see the difference between each of the options and just failed..).

Just to make it more clear, I would like to choose one font for the HUD, and a different one, in square format, for the 'game itself'. What happens is that once you get a square font all the text becomes horrible to read, and the HUD occupies almost half of the screen. So you can't have the best of two worlds, good and easy text, with 'realist' distance maps. Is it possible? Would it be difficult to implement?
##

**Comment by MattAmmann** [comment]
If I'm understanding you correctly, this is already possible by editing the "fonts.json" file in the config directory. I'm using square tiles for the map and the default rectangular tiles for the HUD. Here's an example:

{
    "fontblending" : false,
    "fontwidth" : 8,
    "fontheight" : 16,
    "fontsize" : 16,
    "typeface" : "Terminus",
    "map_fontwidth" : 14,
    "map_fontheight" : 14,
    "map_fontsize" : 14,
    "map_typeface" : "Terminus"
}

**Comment by Podesta** [comment]
Really? Today I've spent my entire afternoon messing up with those fonts and config files, and I've failed completely. I've just tried what you have typed, and it didn't work for me. Just for reference, I'm trying with the console version, not the sdl/tiles.
{
"fontblending" : false,
"fontwidth" : 8,
"fontheight" : 16,
"fontsize" : 8,
"typeface" : "Terminus",
"map_fontwidth" : 14,
"map_fontheight" : 14,
"map_fontsize" : 14,
"map_typeface" : "Terminus",
"overmap_fontwidth" : 14,
"overmap_fontheight" : 14, 
"overmap_fontsize" : 14,
"overmap_typeface" : "Terminus"
}

I have even tried this one, and what happens is that it simply ignores the bottom two configurations ("map..." and "overmap..."), no matter what I type in them. It seems to be taking into consideration exclusively the first section. Whatever I type there, is what it considers for everything. I've also tried the fontdata.json. On that case, does this one have any function, since it's values are overridden by the font.json? 

{
"fontblending" : false,
"fontwidth" : 8,
"fontheight" : 16,
"fontsize" : 16,
"typeface" : "Terminus",    
"map_fontwidth" : 10,
"map_fontheight" : 10,
"map_fontsize" : 8,
"map_typeface" : "Topaz-8",
"overmap_fontwidth" : 10,
"overmap_fontheight" : 10,
"overmap_fontsize" : 8,
"overmap_typeface" : "Topaz-8"
}

**Comment by DavidKeaton** [comment]
the font used in console is the font your terminal uses, you don't change that in json.

**Comment by Podesta** [comment]
@DavidKeaton you mean as I can't change it at all? Because I've successfully changed it, without any problems, with the config>font.json file. I can change it's size, making it in a square, change it's typeface, well, essentially anything, but out of the three options the file gives (as in one font for the text, and the other two for the map), it seems to consider the only the first one, and use it for all the other options. I do believe, like @MattAmmann said, it should be working as he said, but for some reason it is not? I'll try the sdl without tiles and see if it works, but I'm not sure if it'll solve the painful lag of playing on an old laptop.

**Comment by DavidKeaton** [comment]
how on earth did you get it to do that my good man, if it's solely console. was the font already Terminus? I doubt it's by the hidden win32api font manipulation functions, as curses doesn't handle fonts

**Comment by BevapDin** [comment]
Actually, DavidKeaton might have it: the windows console version does indeed use the font from the font config (see src/wincurse.cpp), because it's more of a terminal emulation, it does not use ncurses.

However, it's still a terminal and has therefor only one font. It's simply not possible to have different fonts in a (standard) terminal emulation.

**Comment by DavidKeaton** [comment]
@BevapDin I should've known you had it down. ;-)

**Comment by BevapDin** [comment]
Nah, I totally forgot about that windows special code until you reminded me.

Btw. @Podesta this just shows how important it is to *always* tell the version, curses or tiles and the operating system you tested your issue on.

**Comment by DavidKeaton** [comment]
iirc msdn still doesn't have RegisterConsoleFont or its sibling API documented. It's like the docs on win32 constants and PEB/TLS structure info, hacked together by reverse engineers

**Comment by Podesta** [comment]
Yeah guys, everything works perfectly on the tiles version. If I disable the tiles, it also runs smoother than the console version, which is even better. 

I'm on win 7, and apparently it handles things pretty well on the console. I mean, I can change anything, but like @BevapDin said, since it can't have more than one font, it would always stick to the first one. Even more interesting is that if on the "typeface" I type just some gibberish it will automatically select the 'standard' font, but would still recognize the change in width. 

But anyways, thanks for the help guys, and just to leave as suggestion, maybe we could add in the "tiles options" one option that disables the tile, and chooses a square font for the map. Considering the success that the retro tiles have been making it definitely seems like there are people who want that, with the benefit that it runs super fast on those currently with old pcs, which also seems to be a recurring issue, judging by the search I made today.. Who could imagine displaying those tiles could be so graphics intensive..

**Comment by drbig** [comment]
...Why aren't the font selections configurable in-game? Any reason for not including them?

**Comment by DavidKeaton** [comment]
for the sdl version, I don't know, surely an addition that would help

**Comment by MattAmmann** [comment]
I should've mentioned I was using the tiles version! As BevapDin said, the ncurses version of the game can only use one font, because it's in the terminal. I switched to tiles from ncurses because its performance is better on Windows, and because the map and HUD can be rendered in two different fonts. 

+1 on Podesta's suggestion to change the default map_typeface in fonts.json to a square font.

**Comment by drbig** [comment]
Regarding "Podesta's suggestion to change the default map_typeface in fonts.json to a square font": we do have square.ttf in the repo (in case someone missed it).

**Comment by KA101** [comment]
And now a square-smallcaps font too, thanks to sparr.

**Comment by Podesta** [comment]
Yeah, I saw there are square fonts in the game, and even simply making the terminus on a square is somewhat ok, but the suggestion would be to allow people to modify it, as in choose the font, and if possible, also alter it's dimensions, or just to simplify, give three options, small, medium and large.

I mean, sure, it's all a few clicks away from the .json files, but it would make it simpler for the players not so confident in messing with the files..

**Comment by DavidKeaton** [comment]
Does the game make/use any metadata regarding glyph information from fonts? (that is, do we do anything with the "font", so to speak, other than display it on screen?)

Also changing the font would be possible from SDL/Tiles, however would only support Windows (win32api junk I spouted above) if you were to programmatically change the font in console mode.

**Comment by Leland** [comment]
Closing due to age and lack of movement. Feel free to ping me here if this is still active and I'll reopen.
