### ISSUE TITLE
New emcumbrance and strange layering behavior

### ISSUE THREAD

**Issue by dreukrag** [CleverRaven/Cataclysm-DDA#11722]
experimental -0.C-2887
Wintiles
Windows 7

The new emcumbrance system while really good has a few problems with layers:

nomad gear - Normal
flame-resistant suit - Skintight
survivor duster - Outer

this combination gives me only 5 encumbrance on arms and legs, but 0 on torso, but this one:

flame-resistant suit - Skintight
nomad gear - Normal
survivor duster - Outer

Wich is the logical aproach to layering, gives me 10 encumbrance to both arms and legs and 0 to torso. The same behavior occurs if trying to wear leather gloves over fire-proof ones.
.
There's also problems with wearing headgear, I can't put on a boonie hat if I'm wearing a balaclava, or I can't wear a hood if I have a helmet. It seems to be tied to item emcumbrance tough, lowering it seemed to fix for headgear.

**Comment by Rivet-the-Zombie** [comment]
I think the new encumbrance numbers are having problems due to the fact that a lot of stuff that was never intended to contribute to your encumbrance value aside from stacking penalties now has a small encumbrance rating that adds up quickly.

**Comment by kevingranade** [comment]
We should consider ditching the layering penalty and just having everything
having some encumbrance.

**Comment by Rivet-the-Zombie** [comment]
I think like that idea. The extra layering penalties really only made sense when the encumbrance system used a much broader metric.

**Comment by Zireael07** [comment]
Jumping in to say:
Large quiver
MBR vest with ceramic plates
2x MOLLE
survivor runner pack

equaled 6 torso encumbrance under old system. Now it's 88 (48+40).

I'm not too appalled by it since it means Zs can actually hit me in melee, but the difference was quite surprising.

**Comment by dreukrag** [comment]
I don't think ditching layering would be a good idea, everything having emcumbrance is good but stacking things on the same layer should give you aditional encumbrance.

**Comment by Coolthulhu** [comment]
> We should consider ditching the layering penalty and just having everything having some encumbrance.

If there was no layering penalty, all the tags like `SKINTIGHT` would stop mattering.
The system would be simpler and easier to maintain, but clothing like t-shirts would become cumbersome. It could easily result in nudist+trenchcoat setups being the most correct way of handling things.

**Comment by Coolthulhu** [comment]
I think I localized the bug. In `player.cpp:11742`:
```
if( worn[i].get_encumber() > 0 && armorenc > 0 ) {
                        armorenc = armorenc - 10;
                        if (armorenc < 0 ){
                            armorenc = 0;
                        }
```
`armorenc` isn't the value of the current item, but the value of the current bodypart. This causes new unencumbering fitting items to reduce encumbrance accumulated before them.

**Comment by Zireael07** [comment]
I guess the layering penalty could be changed - instead of +10 per layer, it could be +8 or +5 or whatever. There's no reason for it to be in multiplies of 10 :)

**Comment by kevingranade** [comment]
> If there was no layering penalty, all the tags like SKINTIGHT would stop
mattering.
> The system would be simpler and easier to maintain, but clothing like
t-shirts would become cumbersome. It could easily result in
nudist+trenchcoat setups being the most correct way of handling things.

I'm not too worried about that considering 1 enc and no skintight is WAY
better than 0+fitted in the old system.
As for the nudist eventuality, I'm more interested in adding the
appropriate benefits to underclothes (comfort, warmth from layering,
probably others) than trying to keep them cheap enough that people wear
them out of habit.
