### ISSUE TITLE
An idea to penalize vehicles with unrealistically small wheelbases

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11732]
In #11691 there is some concern about wide wheelbarrows. I'd like to address that more broadly. I have the idea that vehicles should suffer some sort of penalty the more their weight is distributed away from the center of their wheelbase, especially for weight outside the wheelbase entirely (which would make the vehicle more prone to tipping over).

Anyone have feedback on this topic?
##

**Comment by Rivet-the-Zombie** [comment]
Maybe it'd force the vehicle to a stop every now and again with an appropriate message, particularly while turning.

**Comment by Coolthulhu** [comment]
Another component to speed/acceleration: `k_mass_center`. Equal to something along the lines of `1 / ( rl_dist( mass_center, wheel_center ) + 1 )`, except with floating point coordinates and distance.

Not perfectly realistic (adding weight could speed up the vehicle in some cases), but would be a good balance between a tough penalty and the very lenient system we have now.
Additional bonus: damaged wheels would shift the wheel center, making the vehicle slow down more than just what loss of wheel area would cause.
Additional bonus 2: a hulk getting onto the vehicle would slow it down harder than just a ton of evenly distributed stuff.

**Comment by sparr** [comment]
right now we don't include monster weight at all, and only NPCs if they are a legit passenger, I think? If we start including monster weight then monsters would have a chance of stopping wide vehicles by stepping on outside the wheelbase.

**Comment by BevapDin** [comment]
Monster can not board the vehicle anyway, only things with an ID can.

**Comment by sparr** [comment]
@BevapDin [insert tangential quibble about allowing things, monsters or items, to exist "on the ground" below or coinciding with vehicle tiles]

**Comment by KA101** [comment]
>Monster can not board the vehicle anyway, only things with an ID can

*Zombie bio-op pursues KA101, KA101 arrives at Car and frantically swipes his driver's license.  Door unlocks and he gets in, proceeding to try starting the engine*

*Zed bio-op catches up, can't open the door*

Car-alarm voice: "I'm gonna need to see some ID."  Cue bashing.

**Comment by sparr** [comment]
I'm thinking this would involve a few steps:

1. calculate the 'center of support' for the wheelbase, based on the locations of the wheels.
2. calculate the center of mass (there's already a function for this)
3. calculate the distribution of the mass (RMS distance, I think? whatever the 2d equivalent of the standard deviation is)
4. calculate what percentage of the mass lies outside the wheelbase entirely.

the difference in #2 and #1 would incur a penalty. the magnitude of #3 would incur a penalty. the magnitude of #4 would incur a larger penalty.

how does that sound?

**Comment by sparr** [comment]
the wide-wheelbarrow would suffer from #3 and #4 significantly

**Comment by Zireael07** [comment]
@sparr, fix your 1. and 2. please to stop referrring to ages-old PRs

**Comment by kevingranade** [comment]
How about considering the distribution of weight to each wheel?  If you
overload a particular wheel it will impact handling characteristics,
likewise for under-loading them.

**Comment by sparr** [comment]
Hmm, that's a neat idea. I'm not sure how the math behind that works, but I suspect there's a good known approximation algorithm for that somewhere, rather than trying to simulate it. I'll look into that.

**Comment by facepalm** [comment]
I don't know if the math works out completely, but try calculating a "center of support" based on the geometry of the wheels, then for each wheel a simple ratio - (dist_support/dist_mass)x(total_mass/total_support) - for how much of the vehicle is supported by that wheel.  If that goes over the wheel's safety rating, blow it out and recalculate the distribution.

**Comment by kevingranade** [comment]
Feedback requested in OP delivered.
