### ISSUE TITLE
Encumbrance weirdness

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#11739]
Start a new character, wish yourself some turnout boots, an ankle holster, leather patches, a tailor kit and 10 in all skills. Remove current footwear, put on turnout boots. Feet encumbrance is 30. Repair the ankle holster until it becomes fitted. Wear ankle holster. Feet encumbrance is now 25.

**Comment by Zireael07** [comment]
Duplicate of #11722
