### ISSUE TITLE
warmth problem, hard to reproduce

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11747]
It's winter, snowing. I'm indoors, with warmth 0 on head and mouth, wearing nothing on those slots, and nothing with a hood.

If I put on a balaclava indoors, those warmths drop to -16 and -17.

If I go outside with bare face/head, my warmths are both -30. Then I put on the balaclava and it drops ti -36 and -37.

I cannot reproduce this in a fresh game, and my save is rather large to post, so I am just recording this here in the hopes that someone looking through the relevant code will keep an eye out for this problem.

**Comment by Podesta** [comment]
If you compress it, the size usually becomes 10% of the original, so maybe this way it reaches a reasonable size?
