### ISSUE TITLE
cmake, version.h not found

### ISSUE THREAD

**Issue by lekto** [CleverRaven/Cataclysm-DDA#11745]
Hi, I found issue when I was compiling game after use cmake:

cmake -G "Unix Makefiles" -DLUA=OFF
make RELEASE=1
…
[ 11%] Building CXX object CMakeFiles/cataclysm.dir/src/version.cpp.o
/home/lekto/Cataclysm-DDA/src/version.cpp:9:21: fatal error: version.h: Nie ma takiego pliku ani katalogu
 #include "version.h"
                     ^
compilation terminated.

This error mean: there is no such file or directory.

My solve:
mv Makefile Makefile.bak
wget https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/master/Makefile
make version
rm Makefile
mv Makefile.bak Makefile
make

**Comment by drbig** [comment]
@lekto The GNU Makefile auto-generates version.h based on output from `git describe --tags --always --dirty --match "[0-9A-Z]*.[0-9A-Z]*` - if you prefer to use CMake feel free to contribute a patch that preferably does exactly the same in CMake.

In other words seems that CMake support is somewhat abandoned at the moment.

**Comment by NickTaylor-** [comment]
With the CMake patch I implemented, I added the version generation, so this should no longer be an issue. #11674

**Comment by illi-kun** [comment]
Can we close this, if it's not an issue anymore?

**Comment by lekto** [comment]
Sorry, I forgot about it, of course you can close it.
