### ISSUE TITLE
overmap location wrong by 12 squares after recent patch

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11752]
When I am standing in the bottom half of a submap, the overmap thinks I'm one submap south of where I really am.

**Comment by KA101** [comment]
Almost certainly a result of the coordinate conversion.  Thanks for posting this--reports have been flying around and we hadn't wrangled 'em to an issue.

**Comment by BevapDin** [comment]
Does this only happen when your on an overmap with negative coordinates (where either x *or* y is < 0)?

**Comment by sparr** [comment]
I don't think I've noticed that distinction, but 100% of my played map is positive coords, so I'll have to debug teleport somewhere new to find out. TBD.

**Comment by ejseto** [comment]
>Does this only happen when your on an overmap with negative coordinates (where either x or y is < 0)?

I want to say yes. I've been playing for several hours and didn't notice it, but just now found a bank in the next town over with some nice stuff, go to put a map note and realize it's on the wrong square. Lo and behold, the overmap x-coordinate is negative, and it just happens I was playing on the positive side all those previous hours.
