### ISSUE TITLE
Press 'f' for fire - The new aim system and bows

### ISSUE THREAD

**Issue by Podesta** [CleverRaven/Cataclysm-DDA#11751]
@kevingranade how have you handled the bows with your new AIM system, since they have pretty much zero recoil? I recently started an archer and was going through the different aims and checking how much action points each spend. Essentially, what I got was that the three options doesn't seem to have any difference, all ranging iirc something like 180 - 220 (if you want I can gather better data..), but if I use the 'f', it's always a steady 282(shortbow). Also, I could be wrong, but I didn't notice any difference in hits/dmg/crit with any of the options. The only difference is that I can't use your system to shoot at objects, I have to use 'f'.

**Comment by mugling** [comment]
Complete rewrite of aiming since this was asked
