### ISSUE TITLE
Martial Skills should have descriptions down just as it with traits. 

### ISSUE THREAD

**Issue by shirishag75** [CleverRaven/Cataclysm-DDA#11762]
The way it is now, I have to choose a Martial Skill to understand what it does afters, just like with traits and everything else, it should have messages just like when you are hovering over traits.

**Comment by drbig** [comment]
:+1: It's another case of UI inconsistency. I might take a look at this, but if someone else is on a coding spree feel free to resolve this before I even take a look at the code ;)

**Comment by KA101** [comment]
Issue is that the traits give the option of individual styles.  If you move style-picking earlier, that might be better, but I'm not sure how feasible that'd be.

**Comment by drbig** [comment]
@KA101 The style picker can stay where it is, just rework it to show the description alongside the style options, like pretty much everything else in the chargen screen.

**Comment by KA101** [comment]
UI menu issue, then.  Not a "just" sort of thing so far as I know.

**Comment by Parahacker** [comment]
You could always do what I do, have the CDDA wiki open for alt-tabbing ^_^

Though if I keep CDDA itself minimized for too long, it crashes. Trials of still using WinXP, I suppose.

**Comment by BevapDin** [comment]
> Though if I keep CDDA itself minimized for too long, it crashes. Trials of still using WinXP, I suppose.

Where is the bug report for that? Details are needed there: version and build type (sdl/curses), does it only happen in the main screen (before a game is loaded), while you choose your character, or also during the normal game play. How long is too long (minutes, seconds, ...)?

**Comment by drbig** [comment]
Also this particular issue can probably be safely closed (#11779).
