### ISSUE TITLE
Unloading a container onto the ground unnecessarily hard

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#11761]
If you have exactly one liquid container with a non-rotten liquid in your inventory, and you try unloading it, the game omits prompting you whether to pour the liquid on the ground, and instead pours the liquid from the source container *into the same container*.

My guess is that liquid handling first empties the source container, looks through your inventory (to prompt for a destination container), finds **exactly one** (the recently-emptied source container), and assumes that's where you wanted it.

As a workaround, if one truly wishes to pour something onto the ground, they may pick up another empty container (e.g. a plastic bottle), at which point the destination container code will have two options and actually prompt (which you can Esc out of), finally allowing you to pour the liquid on the ground.

**Comment by sparr** [comment]
I'm going to look into this.

**Comment by sparr** [comment]
I can't reproduce this. I've tried with a small plastic bottle of clean water (1 unit), a jug of clean water (15, 7, 1 units), a jug of gasoline (1200 units). In every case I was prompted to select a destination container and given an empty list, then pressed escape and was prompted for a direction. Can you narrow down the steps to reproduce?

**Comment by narc0tiq** [comment]
Yeah, I'm not seeing it, either. Must've had something weird going on the first time.
