### ISSUE TITLE
bike helmet gives more protection than motorcycle helmet

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11767]
The bike helmet is twice as protective as the motorcycle helmet (ignoring coverage).

The bike helmet is 100% plastic, with bash_resist 2.

The motorcycle helmet is 50% plastic, 50% nomex, with an average bash_resist of 1.5, which gets prematurely rounded down to 1.

I'm already going to submit a PR to remove the premature rounding. That will bring the disparity from 12/6 up to 12/9. Maybe the material_thickness on one or both of them should be tweaked? At the very least, there should be parity of bash/cut protection (motorcycle would be better then, with higher coverage).

**Comment by KA101** [comment]
Wonder if plastic, plastic, nomex would cure the problem: 2/3 plastic makes it 1.75 or so bash_resist?

**Comment by sparr** [comment]
That would help a little but no amount of extra plastic will get it up to parity with the bike helmet. And more plastic would hurt the stats contributed by the nomex :(

**Comment by KA101** [comment]
How about decreasing the bike helmet's thickness?  The ones I've used have been foam shells with a hard plastic liner, usually with air vents throughout.  Full-head motorcycle helmets are comparatively solid

**Comment by sparr** [comment]
That's a pretty easy fix. Shortest PR ever, if I submit it alone. Maybe I should take a few minutes and audit some other comparable armors?

**Comment by KA101** [comment]
Just make a clear list of what you're changing, please.
