### ISSUE TITLE
Player can only hear one sound per tile per turn

### ISSUE THREAD

**Issue by vickio** [CleverRaven/Cataclysm-DDA#11774]
In sounds.cpp, player sound events for each turn are stored in `std::unordered_map<point, sound_event> sounds_since_last_turn`. Since `point` is the key, sound events are discarded if there is already something queued at the same coords. This results in the player only hearing the first sound that happens on any tile/turn, unlike monsters, whose sound events are stored in `std::vector<std::pair<point, int>> recent_sounds`.

**Comment by sparr** [comment]
I'm unclear on how monster sounds are indexed with just an int.

That aside... Might the code changes required be less if sounds_since_last_turn was simply an unordered_multimap? A few references to it would need to be put inside loops, I think, without otherwise having to change their syntax.
