### ISSUE TITLE
failrue to compile item.cpp under cygwin

### ISSUE THREAD

**Issue by nulman** [CleverRaven/Cataclysm-DDA#11785]
there are several std::lround calls that break the compilation
i got it to work by removing the std::
and changing the function to round, because all of them are used as a return values in int functions

(am i the only guy still using cygwin?)

**Comment by karols146** [comment]
Cygwin is no longer supported( when last I ask)

**Comment by nulman** [comment]
whaaaaaaaaaaaat? i would play something else butt his is a windows box and the tiles versions are too tiny... (i got cygwin set to fontsize 22)

**Comment by karols146** [comment]
I have this problem too, You can try MinGw if you but it would run too in windows cmd so it not solve this problem, or You just don't commit all changes like me, and sometime cygwin build working normal after few releases.

**Comment by KA101** [comment]
Heh?  I'd not heard anything about dropping cygwin support, and @i2amroy would be shut out.  Not sure where you got that impression, and I'm sorry for what sounds like a bad inaccuracy on top of the compiler failure.  :-(

**Comment by sparr** [comment]
http://www.matpack.de/cygwin/index.html

**Comment by kevingranade** [comment]
Just echoing, we definitely support cygwin, and if the build is broken
under it, we will fix it.

**Comment by karols146** [comment]
I am glad to hear that, I can said that I am happy now too, I don't remember where I exacly heard that, but sorry for my mistake.

**Comment by sparr** [comment]
> changing the function to round, because all of them are used as a return values in int functions

can you elaborate on this? I chose lround because it returns an integer type (long). round returns a float.

Also, I'm fuzzy on how/why you can or would remove std::. There is no namespace used in item.cpp, so attempting to call round() instead of std::round() should fail.

**Comment by karols146** [comment]
If I try lround without std:: it work too. Cygwin is soo weird.

**Comment by mugling** [comment]
> there are several std::lround calls that break the compilation

A quick` grep` shows these are nolonger present so I'm presuming your issue was resolved
