### ISSUE TITLE
CBM Layer/Volume Proposal

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#11781]
Right now, people can install an infinite amount of CBMs. This is all cool but can make the character overwhelmingly powerful after some time. To combat this and make CBMs a bit more interesting, I propose a system where each CBM takes up volume, and each body part can take a certain volume as well.

You would have three "layers" for where CBMs can be installed: inner, outer, and skin. The inner layer is for CBMs that live entirely within the body (internal furnace, battery system, power storage), while the outer layer is for CBMs that require you to have visible parts (such as integrated toolset, cranial flashlight, mini flamethrower). The skin layer would take the armor CBMs, but also external sensors such as the thermometer. Some CBMs might have multiple layers where they can be installed. The player gets a choice for where to install the CBM once installation succeeds.

One would also have the ability to fit CBM sockets. These sockets have the added functionality to allow removal and installation of CBMs without destroying them. Installation can still fail, but that will be a fairly rare occurance. Low skill can, of course, destroy CBMs and/or wound the player.

The benefit of implementing this system is that we get better control over how overly powerful people can become with their bionics. It should make for a more balanced game. Limb loss can also result in the loss of CBMs, which makes it even more important for the player to protect themselves against such mishaps.

More so, when the player has better control over where the bionics are installed, each new bionic will have to be a choice, not just "yeah, I'll install that."

The way Power CBMs work will also need to be reworked. It would probably need to be possible to upgrade them, making the Mk2 power storage and perhaps even more advanced power storage something the serious bionic character need to be searching for.

A drawback of this is that the system is made more complicated. It requires some investment of player knowledge to work with a layered system and may put some off from using bionics. It will also require a bit of extra data to be stored in the jsons for the bionics (size, possible installation locations). 

Example bionic:
The Cranial Flashlight has a volume of 1, can only be installed in your head, and requires a skin slot. It can also be socketable, thus the hotplug tag.
```
"hotplug": true,
"installed_volume": 1,
"installation": [
    { 
        "limbs": [ "HEAD" ], 
        "layers": [ "SKIN" ] 
    }
]
```
Joint Torsion Ratchet has a volume of 4, can only be installed in one of your legs, and requires an inner slot. Once installed, it can not be removed ("oneshot"; you replace a joint with this thing).
```
"one_shot": true,
"installed_volume": 4,
"installation": [
    {
        "limbs": [ "LEFT_LEG", "RIGHT_LEG"],
        "layers": [ "INNER" ]
    }
]
```

This is just a suggestion, but I've had thoughts on working on the system in the future, and figured I'd put it here for public scrutiny and feedback. Discussion is encouraged. Besides, it gives me a place to keep the document for when I begin working with it :)

**Comment by ejseto** [comment]
I support this idea. Reminds me of Deus Ex, where you had to choose what to install in limited slots. It's silly how many bionics you can currently fit into one body, and even more silly that even after you have everything, you can continue to power up, literally.

>It requires some investment of player knowledge

I don't think this is a problem as long as the player is notified of what he is getting into (i.e. "This CBM is PERMANENT! You will never be able to remove it! Do you want to continue?"). Sure, a new player might not know exactly what they're missing out on, what they might find later that they wish they still had space to install, but I think that's fine. Or removal could require special equipment only found in hospitals or lab finales or something.

**Comment by Zireael07** [comment]
I believe a similar Deus Ex-style system has been suggested in the forums in the past.

**Comment by tivec** [comment]
@ejseto I do not want one_shot CBMs to be removable. Just like the fusion blaster replacing your hand/arm, the permanent ones would replace parts of your body. Unless you can grow bodyparts, then I suppose we can allow it at those places.

@Zireael07 Ah, I don't read the forums much. At any rate, the suggestion is in the tracker now, so it's easier to work on.

**Comment by narc0tiq** [comment]
> Some CBMs might have multiple layers where they can be installed. The
player gets a choice for where

Likewise, some CBMs may simply require space in multiple layers; the fusion
blaster arm probably shouldn't allow any further internal or external arm
CBMs on that one arm (it should probably still allow skin-level ones,
though).

**Comment by ejseto** [comment]
They shouldn't be removable alone, but I think there should be options to replace them. You can't remove the fusion blaster, but there should be a robo-arm or some such that could be swapped out. And lizard mutant characters CAN grow bodyparts, btw.

**Comment by KA101** [comment]
DX has been a perennial basis for bionic discussion.  Glad I bought the GOTY edition back in the day.

It's also a cautionary tale: nobody takes Run Silent IME, nor Combat Strength outside of specialized builds.  Likewise I could never convince myself to take Energy Shield or Synthetic Heart.  Creating competition for aug slots can seriously alter the metagame/balance.

As for the merits, I'm not opposed to the concept...the details, though, are gonna be a fight, I'm afraid.  Stuff like the thermometer probably should be trivial--seriously, who's gonna give up armor plating for a thermometer?--and I'd thought the JTR incorporated into all major joints in the body, not just one/both hips/knees/etc.

**Comment by ejseto** [comment]
Heh. The speed booster was just as silent, zooming around while crouched, and faster than run silent at the same time. I never took synthetic heart either.

The virtually worthless *widgets* like thermometer and chronometer should probably just be free. As it stands, the only benefit chronometer offers is 0.1 lbs of saved weight. Or certain bionics could have a certain amount of space for widgets which would be installed into them. Armored torso *with installed thermometer*, armored head *with flashlight* and so on.

**Comment by tivec** [comment]
@ejseto I like that idea. 0-volume bionics are also possible. They would be installed in a given limb but won't block other bionics.

And yes, @KA101, the details are going to be a fight ;) I still want it to be open and in an issue so people can discuss it contrary to just starting to code before anyone has a say in things.

**Comment by kevingranade** [comment]
I'm behind a slot-based system in general, my main concern is keeping the
changes at any time manageable, please consider just doing the limited
installs idea, then 'sockets', then layers, etc instead of doing them all
at once.

**Comment by drbig** [comment]
We indeed need a better bionics system, right now it gets insane really fast.

Volume per body part is a must, same with some bionics being more or less limited to certain body parts only.

The layering system sounds neat, but I'm afraid it might end up as an overkill (similar thoughts on clothing layers too). Focusing on balancing the volume requirements might be a better idea.

I have some problems with the sockets idea - most bionics are rather invasive, and the only stuff that I could imagine as 'plug-and-play' are the gadget-like things. As such I would leave this close to what it is now: removing some bionics is risky and painful, but doable; some can only be replaced (e.g. the fusion blaster arm), some can't be removed at all (joint torsion ratchet, probably a lot more here).

Having said that I think that a lab/hospital machine would be a great thing here (and I remember this idea being already mentioned): such machine could remove *anything* at lower risk, as it can conceivably 'fill in' the now empty spaces with some regenerative goo or other plausible magic dust.

For gadget-like things: either make them take very little volume (but non-zero) and easily player removable, or make them permanent but with 0 volume (and I'm more for the first approach while we're at it).

And last but not least: power storage CBMs *do need* to take volume too. Thus it's both volume and energy budget one has to think about.

**Comment by Shoes01** [comment]
This could probably be a suggestion on its own, but talking about limiting CBMs via slots or volume.. what if some CBMs worked together with others for synergy effects?

The way it would work is if you have CBM X and Y installed, you also get effect Z. Like hydro muscles and diamond cornea give you a throwing bonus.. 

The rationale : in light of a metagame shift in CBMs due to slots/volume, this could give suboptimal CBMs a reason to be installed: you get a 2-for-1 for the volume used. Another reason would be to sort of compete with the depth of mutations and their categories.

**Comment by ejseto** [comment]
>what if some CBMs worked together with others for synergy effects?

That's something I've had on my mind for a long time. Something like synergy between the targeting system and the perception or dex booster. It would also be cool if they had synergies with certain items, like a smart-link gun mod and so on.

**Comment by KA101** [comment]
>Synergy

Targeting + FBA ought to work very well (zero sight dispersion), yeah.  Definitely something to include for other augs as well.

**Comment by Snaaty** [comment]
I like limiting cbms, but two problems come to my mind immediately:

1. If you actually have to select a body-part to install the cbm, having a mutated character makes things really complicated, I imagine. 
2. Depending on how tough the limit is, we might have to reduce the penalty of removing bionics. Right now, it is extremely hard to do without screwing yourself up severely.

Apart from that, I am all for your idea. Somewhat limiting the power cbm also makes sense, imho, but I'd like a good replacement for what to do with them instead. 
Maybe we could do an upgradable system that demands exponential numbers of power cbms (meaning for level 1 of power level -> 1 power cbm, level 2 -> 2 power cbm, level 3 -> 4 power cbm, level 4 -> 8 power cbm, you get the gist...)

**Comment by Breligar** [comment]
Suggestion for power CBM: Instead of exponential amounts of power CBMs, perhaps quality levels for a single power source? Such as, Bionic Power Source Alpha, Bionic Power Source Beta, etc. Make the lowest grade relatively easy to come by as compared to current power CBMs, but make them progressively more difficult to encounter as the quality level goes up. They could occupy their own "slot" so as to not step on any other CBM's toes, and you would be unable to make use of some/most CBMs without one installed (Alloy Plating, for example, probably wouldn't need a power supply).

**Comment by KA101** [comment]
>They could occupy their own "slot" so as to not step on any other CBM's toes, and you would be unable to make use of some/most CBMs without one installed (Alloy Plating, for example, probably wouldn't need a power supply).

Already exists: power storage can be stacked ATM (this will likely be Nerfed as part of this process) and CBMs that don't draw power are fine without a power storage.

Rest of the post bears thought.

**Comment by Xpyder** [comment]
I strongly support Tivec's idea, and I'd like to add a couple of possible additional layer of depth to this option.

Firstly, if me make sockets special loot in labs/military complexes with only one per site and hints to their existence scattered in the world (newspapers and whatnot) this could create an optional exploration goal and would help keep the mid game interesting while you hunt for a full set.

Second, What do you guys think about Sockets actually being extensive limb modifications that remove and deny any mutations in that limb, creating an exclusivity between heavily bionic and heavily mutated characters?

**Comment by Skidborg** [comment]
I like most of these ideas, but I'm opposed to the layer-locking of CBMs. For example, you give the joint torsion ratchet as a device that can only be built directly into a joint on the inner layer.  However, I could design one that goes on the skin layer, wrapping around the joint and retrieving power without requiring invasive surgery.  This either means we'll have to create variant CBMs for different layer slots, or squabble about artificial limitations on installation areas.

Adding specific synergies between bionics is going to create hardships on people who want to create and add new CBMs, since it will require maintaining and balancing an increasing web of specific interactions.

Creating a cybernetics ascension path that blocks the upper levels of mutation is an interesting idea, which I would be quite okay with.  Converted limbs could also be immune to infected bites and other biological hazards.

My two main concerns with CBMs at the moment is the lack of any sort of cap on power storage, and there being no downsides at all to binge-installing CBMs.  Taking a full build of CBMs is always the right choice as soon as possible right now, as opposed to mutations that are a randomized risk until the highest skill levels.

**Comment by illi-kun** [comment]
Part of this issue related to "Limbs" (= bodyparts) is implemented and "layer" part isn't. "Layers" will add another dimension for balancing of all bionics, so I'd prefer to implement it much later (if it's actually needed at all).

**Comment by kevingranade** [comment]
The core of the concept, 'limit bionics a player can install" is implemented, but its hidden behind a debug trait, this can be closed when we merge a pr that completes the feature well enough to enable it without the trait.

**Comment by illi-kun** [comment]
Discussion if continued in #16920.
