### ISSUE TITLE
unwielding a weapon with a shoulder strap, no room, drop prompt should be preceded by wear prompt

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11786]
If I am at max volume and I wield a new weapon, I a prompted to drop my old weapon. If that old weapon has a shoulder strap, there should be a prompt to wear it, first.

**Comment by drbig** [comment]
I'd even make it a simple menu, so you can select what you want to do with one key press.

**Comment by mugling** [comment]
Effectively closed by #14870
