### ISSUE TITLE
map::draw() and cata_tiles::light_at() do the same job, not quite the same results

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11790]
It looks like these two functions do very similar tasks, one for ascii and one for tiles. However, they don't quite match up, for things like the indoors check in map::draw(). Am I missing something, or is this a bug?

I'd like to try to consolidate this code into one place, rather than having a bunch of dupicate information in map and cata_tiles (such as map.light_sight_range and cata_tiles.sightrange_light, etc).

This will reduce code duplication, remove inconsistencies between the two modes, and also make the relevant functionality usable elsewhere. If there's something I'm overlooking that explains why this needs to stay separate, please let me know?

**Comment by sparr** [comment]
Should I assume that map::draw() or cata_tiles::light_at() is authoritative, where they disagree?

**Comment by BevapDin** [comment]
This discontinuity seems to got back to the initial tile commit a658fee84c00123c3ee2c71be09f595ffffbbd1b. Using tiles bypasses the call to `map::draw`, which used to call `g->reset_light_level()` (and still does), so `cata_tiles` had to do that on its own. Moving this into a common function is surely a good thing.

As the non-tiles version is probably more used by developers, and it's after all the original version, the `map` functions seem authoritative.
