### ISSUE TITLE
vehicle with unfueled engine and an alternator has negative total power and max speed

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11804]
vehicle::total_power returns negative numbers for vehicles with alternators and no fuel. this leads to some unusual behavior of various vehicle interactions, including cruise control speeds getting clamped to negative numbers.
##

**Comment by mugling** [comment]
Implementation has heavily reworked since this was opened. Please re-open if reproducible in any recent version of `master`
