### ISSUE TITLE
Build-errors with clang '[…] overrides a member function but is not marked 'override'

### ISSUE THREAD

**Issue by namarrgon** [CleverRaven/Cataclysm-DDA#11805]
Currently (aa3bb42) it is not possible to compile a release build with clang++.
Example:

```
In file included from src/mapgenformat.cpp:9:
In file included from src/output.h:11:
In file included from src/item.h:11:
src/artifact.h:75:14: error: 'serialize' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        void serialize(JsonOut &json) const;
             ^
src/json.h:799:22: note: overridden virtual function is here
        virtual void serialize(JsonOut &jsout) const = 0;
                     ^
```
Full log: "make CLANG=1 RELEASE=1"
http://sprunge.us/aMJc

Both g++ builds don't even emit warnings for this; the debug clang build does (without -Werror) but compiles a working binary anyway.

**Comment by bkentel** [comment]
So compile without `-Winconsistent-missing-override` or make a PR which adds the missing `override` specifier (they ought to be there)? It may sound flippant, but what would you have us do?

**Comment by sparr** [comment]
@bkentel it's a tiny bit over-reaching to expect every person reporting a bug to be able to fix that bug (although the fix here is pretty easy), and a bit more to expect them to be able to submit PRs. You shouldn't discourage bare bug reports, especially as relatively good as this one is.

**Comment by namarrgon** [comment]
I'm aware that I could hack the build-system (seriously?) or that I could dive into the c++ innards to fix it myself.

I simply reported a defect, so that someone, perhaps more experienced with the code-base/language, could have a stab at it. In the worst case it still serves as a documented reminder. That's what an issue-tracker is for, right?

I'm also aware of how OSS projects work and the roles that I, as a non-programmer, can fill in them. I think I worded my report neutral enough to not make it sound like a demand so I'm not sure where the 'flippancy' is coming from and will just treat it is miscommunication (or the lack of coffee in the morning :P ).

**Comment by sparr** [comment]
I am building with clang right now and will issue a PR for this ASAP if I can duplicate the bug.

**Comment by bkentel** [comment]
Sorry if it sounded like I was being discouraging of reporting the bug. Also, I meant that *my* reply may come off as flippant, not your report. Thanks for reporting it regardless.

**Comment by bkentel** [comment]
@sparr it's probably going to be a big PR -- there are quite a few places in the code where `override` is going to need to be added to compile cleanly. It's for the best that it be done though; thanks for taking it upon yourself to clean it up.

**Comment by sparr** [comment]
I am not able to reproduce this. @namarrgon can you tell us what version of clang++ you're using?

    $ clang++ -v
    Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
    Target: x86_64-apple-darwin13.4.0
    Thread model: posix

**Comment by namarrgon** [comment]
Of course:
```
clang version 3.6.0 (tags/RELEASE_360/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.9.2
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib64/gcc/x86_64-unknown-linux-gnu/4.9.2
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9.2
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
clang: warning: argument unused during compilation: '-fPIE'
clang: warning: argument unused during compilation: '-pie'
clang: warning: argument unused during compilation: '-fstack-protector-strong'
```

**Comment by sparr** [comment]
I don't have a linux machine to test on right now. Unfortunately this will have to wait for someone else to take a look at it. Sorry.

**Comment by tivec** [comment]
This is my setup for clang++, and it works perfectly well. Unable to reproduce.

```
$ clang++ -v
Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
Target: x86_64-pc-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/4.8.2
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/4.9.1
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.1
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.1
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
```

**Comment by bkentel** [comment]
What if you specify `-Winconsistent-missing-override` explicitly?

**Comment by sparr** [comment]
I just upgraded my clang. `Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)` and `Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)` both say `-Winconsistent-missing-override` is an unknown warning option. It looks like this option may only be in cutting edge clang builds; having been added recently.

**Comment by narc0tiq** [comment]
I can put clang-3.6 on the build machine, if that's wanted. At the very least, I'll make an effort now to clear up the missing-override warnings and link back to this issue when it's ready.

**Comment by Reihar** [comment]
@narc0tiq I'm facing the same problem with the 0.C and clang 3.6. I tried using your clang-modernize command on the 0.C release but it does not appear to be working. Could you please make an equivalent patch for the 0.C?

**Comment by narc0tiq** [comment]
@Reihar Forgive my confusion, but why exactly are you building the 0.C release? Mac build? 64-bit Linux Tiles? I think the pre-existing binaries cover everything else.

Either way, yes, you can have a patch -- [here you go](https://github.com/narc0tiq/Cataclysm-DDA/commit/2e12a15fdbb32b5941d597e3cc774030445d483a) (or, if you prefer, [patch ](https://github.com/narc0tiq/Cataclysm-DDA/commit/2e12a15fdbb32b5941d597e3cc774030445d483a.patch) or [git diff](https://github.com/narc0tiq/Cataclysm-DDA/commit/2e12a15fdbb32b5941d597e3cc774030445d483a.diff) form).

**Comment by Reihar** [comment]
@narc0tiq Thank you. Distribution packaging guidelines. I'm making a community package for my distribution and good practices include compilation. A bit zealous maybe, considering it's not an official package but I like it.

**Comment by narc0tiq** [comment]
@Reihar Nice! Glad I could help, then.
