### ISSUE TITLE
Debug message on world load - related to folding vehicles?

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#11819]
I get this message on loading (an old save or a newly created world/character pair):

DEBUG: Error: folded part inflatable section has a volume of 0!

Error is repeated a few times, then it loads and plays fine (so far).

gf7c600e, Linux, Tiles

**Comment by aierce** [comment]
I'm having the same trouble, but i also get this extra error, "duplicate ammo id: mininuke_mod"

removing the extra vehicle addiction mod seems to fix all this

**Comment by Zireael07** [comment]
@aierce: This problem has already been reported on the forums to the mod's creator.
