### ISSUE TITLE
Monster indicator under character info showing the wrong directions 

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#11818]
Odd one - screenshots show it best.

![what it says](https://cloud.githubusercontent.com/assets/8448518/6865671/4f4c1020-d4c4-11e4-8675-77314eaaf398.png)

![where they are](https://cloud.githubusercontent.com/assets/8448518/6865675/5a4cd658-d4c4-11e4-8a33-c86728df9d68.png)

gf7c600e, Linux, Tiles

**Comment by tivec** [comment]
The monster information compass is drawn in the ´game::mon_info´ function. I suspect that this error has to do with PR #11561 that touched directions and rewrote how they work.

**Comment by drbig** [comment]
Can confirm seeing this too (running same version as Tivec apparently).
