### ISSUE TITLE
Smashing a shrub turns it into harvestable underbrush

### ISSUE THREAD

**Issue by facepalm** [CleverRaven/Cataclysm-DDA#11813]
Stuck without a forest in sight, and desperately need some wild vegetables?  Find some dark green shrubs in plains tiles or decorations in town, and punch them until they give up the goods!  Apparently, smashing such shrubs turns them into light green forest underbrush, which can then be foraged for items.  This also affects berry bushes.

I don't think this was intended.  If anything, I suspect it was meant in the other direction - that smashing (or foraging) underbrush would turn it into otherwise useless shrubs, instead of destroying it outright.

[ETA] And now I see a closed issue from two years ago about making it work *better* - this is intentional behavior?

**Comment by KA101** [comment]
Yep, intentional: there's no other way of getting new underbrush.  Having a seasonal growth-check or something would be better.

**Comment by Headjack** [comment]
If there was a growth check, it could probably also regenerate berries and fruit trees. Or maybe that's been achieved already and I hadn't heard.

**Comment by KA101** [comment]
Harvestables regen by having a separate terrain type and tracking when they were last harvested--it's terrain-based and localized, rather than time-based and global to the overmap(s).
