### ISSUE TITLE
Cut damage calculation error

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#11822]
Starting on line 788 of melee.cpp

```
    // 80%, 88%, 96%, 104%, 112%, 116%, 120%, 124%, 128%, 132%
    if (cutting_skill <= 5)
        ret *= 0.8 + 0.08 * cutting_skill;
    else
        ret *= 0.92 + 0.04 * cutting_skill;
```

The cut damage is being calculated incorrectly. There is a discontinuity where cutting skill 6 has a 116% multiplier while cutting skill 5 has a 120% multiplier. It also does not match the comment.

**Comment by facepalm** [comment]
A question of ettiquette, if you don't mind: if you're reading the code closely enough to find a bug like this, you've probably already worked out what the fix should be, namely changing the comparison to < 5, and bumping 0.92 to 0.96.  

Is it a matter of politeness that you don't just make a PR for it immediately?

**Comment by ejseto** [comment]
No, it's a matter of me not having Git set up. This one is pretty clear, since the comment says what it's supposed to be, but I don't really feel like learning git again, besides "git pull".

**Comment by kevingranade** [comment]
As a matter of etiquette, just bug reports are always ok.  Anything that
moves us closer to a solution to a problem is ok.  Please don't bug people
to submit PRs for bugfixes.

**Comment by facepalm** [comment]
I was asking for my own benefit - if I'd encountered such a bug, my inclination would have been to make a PR directly.  However, I've seen some projects where people get very ...insistent, that bugs be made issues of first, _then_ fixed.  Just one of those things.  And as the bugs I've seen PR fixes for here have had issues attached, I thought I'd ask.

Not wanting to fuss with git is a perfectly good reason.  It totally subscribes to the "powerful and complicated, learning curves be damned" school of thought so prevalent in linux.   I myself can't do more than basic commits without googling for the proper magic words every single time.

**Comment by kevingranade** [comment]
We don't require or even request a separate issue, if you find a bug and have an immediate solution, feel free to just make a PR that fixes it.
Apologies for my tone, we have had people be insistent about people making PRs for issues instead of just reporting them, so trying to quash that.
