### ISSUE TITLE
Windows not aligning with walls

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#11838]
Unless I actually managed to somehow break it:

![Unaligned window](http://i.imgur.com/lBNCn4E.png)

The window is obviously not aligned with the rest of the wall. The tile I'm standing on is roofed.

Given #11835 I'd assume the building buildings stuff is not well tested, which is ok, I'm gonna test it and report here.

The window is fully constructed and does seem to be fully functional, and in ncurses it's the usual `"`.

**Comment by Zireael07** [comment]
You're using a tileset, RetroDays from the looks of it. Looks like a tileset problem. Did you try another tileset?

**Comment by drbig** [comment]
The tileset is RetroDays and it includes horizontal windows, e.g. as in this generic house:

![Generic house](http://i.imgur.com/5EYoCZ4.png)

Which to me suggests that the "Build Window" code didn't create a properly wall-aligned window.

Also the wooden walls in my initial example are 'Log Walls' to be precise.

**Comment by BevapDin** [comment]
> Also the wooden walls in my initial example are 'Log Walls' to be precise.

There's probably the problem. Log walls don't have a direction (other walls come in vertical and horizontal form, which are different terrain types). Coincidentally log walls have the '#' symbol in the curses version. The game decides whether to align/rotate a symbol (in this case the window) based on the *terrain symbol* of the adjacent squares, it looks for `'` (open door), `+` (closed door), `"` (closed window) or the horizontal/vertical line symbols. The log wall matches neither of them.

**Comment by drbig** [comment]
I should have written that the walls are Log Walls much earlier, sorry.

The mechanic makes sense, and as such the solution here seems to make the Log Wall a wall like any other, with the distinction between horizontal and vertical (the tiles seem to work it out anyway).

**Comment by BevapDin** [comment]
> (the tiles seem to work it out anyway).

The tiles code has yet another feature that makes this possible: it looks for adjacent terrain of the very same type and searches for a tile tile matching that configuration (this does *not* work for vertical walls adjacent to horizontal walls, the type must match exactly). You can easily see this with blood splatters. Two adjacent fields of blood connect, whereas two separate fields form circular puddles.

This feature can be used on all terrain, field (probably furniture etc.) types, but (as said above) it only work if the adjacent tile is of the exact same type.

**Comment by FireCrow1973** [comment]
this has happened to me with normal glifs to.
was in a house with five glass windows, the middle tree was facing the wrong direction.
but this was a build from a couple of days/weeks ago, just a normal house.

**Comment by KA101** [comment]
That house is a known issue in the JSON, we've not had the time to nail down the fix.  Thanks for the reminder.

**Comment by sparr** [comment]
want to chime in with a plug for #11844. if we move forward with eliminating _v and _h in general then all sorts of walls could Just Work and log walls wouldn't need to be an exception.

**Comment by drbig** [comment]
@sparr I think I'd concur. Wall's a wall and the drawing code should join walls properly, regardless of material. I don't think I see any benefit to the _v/_h distinction as it is now (am I missing anything?).
