### ISSUE TITLE
Gasoline spawning outside reservoir

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#11833]
In large gas stations, the fuel is spawning outside the reservoir again. Smaller gas stations still work though.

**Comment by Zireael07** [comment]
Ugh, that's one recurring bug for sure. Can't count how many times I've seen it reported in various versions. :(

**Comment by kevingranade** [comment]
I've poked at this several times, haven't been able to reproduce it so far
:/
