### ISSUE TITLE
Direction indicator in HUD wildly incorrect

### ISSUE THREAD

**Issue by MattAmmann** [CleverRaven/Cataclysm-DDA#11834]
Animal is SW of the player, but HUD icon shows the monster is NW. 
Animal is NW of the player, but HUD icon shows it as S
Animal is N of the player, but HUD icon shows it as S
Animal is NE of the player, but HUD icon shows it as SW
Animal is E of the player, but HUD icon shows it as SW
Animals is SE of the player, no HUD icon at all

The directional indicator in the V menu doesn't seem to have this problem.

Build: SDL
Version: f7c600e
Platform: Windows 7 x64

**Comment by Zireael07** [comment]
Duplicate of #11818.

**Comment by MattAmmann** [comment]
Gotcha. Alright, closing.
