### ISSUE TITLE
Req: Unify question dialog box answers

### ISSUE THREAD

**Issue by codrus** [CleverRaven/Cataclysm-DDA#11831]
FEATURE REQUEST

Unify the question dialog boxes so that 'Y'es always means 'please continue with what I originally asked' and 'N'o means 'okay, lets not do it'.

Especially the boxes that open when butchering a corpse when a zombie is near, or the one that pops up when a zombie is approaching.  The way it is now we always have to stop and read the dialog to see if we need to hit Y or N to continue despite the warning, sometimes Y sometimes N which isn't smooth.
##

**Comment by drbig** [comment]
I'm all for this too. I wonder what else there is inverted besides butchering.

**Comment by KA101** [comment]
Right now I believe it's set to N being the "safe/stop" choice.  Entirely possible that we've missed a few spots, though, and an audit would probably be worthwhile.

**Comment by Zireael07** [comment]
Uh, safe (as in ignore those sounds) and stop (stop butchering) are not usually equal.

**Comment by drbig** [comment]
I'd even say there should be a toggle button for 'Ignore all until attacked', as butchering/inventory management near mobs (e.g. containment facilities in labs) is an endless annoyance at the UI.

**Comment by KA101** [comment]
As in "stop moving", but yeah, I could have been more precise.  That toggle seems like a good way for folks to forget about it in the "on" position though, so I'd suggest that it only work with safemode off  (rather than being a separate toggle).

**Comment by kevingranade** [comment]
This is worthwhile to have hapen, but 100% compliance with something like this isn't a very good scope for an issue since it becomes hard to call it closed, so I'm just going to close it.
