### ISSUE TITLE
_v and _h tiles are obsolete/redundant?

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11844]
It seems like the _v and _h tiles for walls and such are mostly deprecated by the additional-tiles mechanic in cata_tiles, and the corner-calculation feature in ascii mode could also easily determine if a non-intersection wall should render as wall_v or wall_h based on its neighbors.

Eliminating the _v and _h tiles would make for less work for tileset creators, and less overhead in creating wall enhancing features (such as electric fences someone on IRC is working on).

Can and should we eliminate the _v and _h distinction from terrain and furniture tiles?

**Comment by kevingranade** [comment]
Yes that would be good to be rid of.  AFAIK the only things explicit h and
v versions gives you is a little bit of stability when terrain is
destroyed, and disambiguation in certain circumstances like this:
'''
WWW
WWW
OOO
'''
I think there are solutions for this sort of thing though.

**Comment by BevapDin** [comment]
Ah, it has been approved (-:

It's a nice coincidence, I had the same idea, but mine was inspired by the fact that vertical and horizontal walls don't connect nicely. Go to lab (ground level), go into the map editor and show all:

![screenschot-2015-03-30-05-01-09](https://cloud.githubusercontent.com/assets/5095435/6899980/0b3ad212-d704-11e4-9231-5600b4fde568.png)


Similar the bunker:

![screenschot-2015-03-30-05-00-21](https://cloud.githubusercontent.com/assets/5095435/6899988/15a3a620-d704-11e4-81c7-5a65f4c530ab.png)


In the branch  https://github.com/BevapDin/Cataclysm-DDA/tree/standardize-walls, they look like that:

![screenschot-2015-03-30-05-02-26](https://cloud.githubusercontent.com/assets/5095435/6899995/1f1df0f2-d704-11e4-94f9-dc65842cd3e3.png)

![screenschot-2015-03-30-05-03-37](https://cloud.githubusercontent.com/assets/5095435/6900006/27a8a29e-d704-11e4-8917-39cb8abfa69c.png)


----

It does what you suggest in your issue: it combines the _v and _h terrains into one terrain. They will be draw with the usual line drawing system, that is not changed at all. The lines themself are not taken from the terrain symbol at all, but are automatically detected based on the adjacent terrains.

This is not yet complete, the tiles part is not ported at all.

It is fully compatible with old saves (old terrain will be converted).

----

I plan to add a CONNECT_WALL flag, which would be added to windows and doors and other structures that are technically a wall, and which would make adjacent walls connect to the window / door (and avoids the current hack that checks for terrain symbol `'` or `"` or `+`).

**Comment by sparr** [comment]
Amazing. I'm glad you posted before I started working on it.

Most of the work for tiles is already done, via the additional_tiles functionality.

**Comment by sparr** [comment]
relatedly, I have a crazy idea to extend additional_tiles to allow tiles with their corners filled in, so that walls that are 2+ tiles thick are solid instead of a grid in tiles mode.

**Comment by i2amroy** [comment]
Closed by #11895.
