### ISSUE TITLE
Shot before door to shoot through existed

### ISSUE THREAD

**Issue by codrus** [CleverRaven/Cataclysm-DDA#11856]
Using an acetylene torch to make an opening through a science-bunker door with a turret on the inside results in the turret getting to fire the entire time. 

Looking at my message history, I was shot by the turret inside for four minutes before I could do anything.

**Comment by kevingranade** [comment]
This is a side effect of the way standard actions are handled, namely the
action completes immediately, and the player is given a move penalty to
represent the duration of the action, driving their pool of move points
negative.  They are then unable to move until their pool goes positive.

The solution is to make the action into a 'long action' which at worst
completes and sets the player's move point pool to 0 at the end of the
duration.
