### ISSUE TITLE
Structure proposal: Building supplies megastore

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#11851]
Size of the megastore (or maybe 2x2?), but focused on: tools, raw materials and gardening supplies. Think Home Depot (and according to [wikipedia](http://upload.wikimedia.org/wikipedia/commons/8/85/Homedepotstoremap.png) there should be some in New England).

In terms of tools I'd see it as combining hardware store, gardening supply and home improvement store.

However the raw materials should be the main selling point: nails, rebar, 2x4s, logs, bags of concrete (I haven't seen any spawn anywhere in my current game), bags of sand, fertilizer, assorted chemicals, paint in large quantities, carpets, seeds etc.

No furniture, food only limited to a couple of vending machines. Maybe a bigger shopping cart (but that's an additional thing).

They should be as rare as megastores, or maybe slightly more rare.

I'd also like them to be stocked 'to the brim', at least in terms of raw materials, as I don't think people will be rushing to grab that bag of concrete during zombie attack.

Besides flavour the point of such store would be to enable players to actually dig into all that construction options.

**Comment by PropaneSoup** [comment]
I like the idea, especially since, like you said, it'd open up more construction options for players.

'Large shopping carts' should definitely be included in one. I know at least every Lowes I've ever been in has had trolleys for you to load up stacks of huge plywood boards.

**Comment by kevingranade** [comment]
No problem with the concept, have at it.

**Comment by drbig** [comment]
@PropaneSoup yeah, I did find whole two bags of concrete after all... that's a quarter of what is needed to get a single simple concrete wall up (and that's just the concrete). Also getting nails is 'weird': the best method I found is to smash counters... (much better than the folk wisdom of 'burn down a building'). I think I also have about 2 ~ 4 bricks...

Regarding the cart: places like Castorama here also have these, but they also have 'usual mall shopping carts' that are just bigger - I was thinking more about these originally. If a usual wire basket has ~200 volume these should have ~400 maybe? A car box has ~ 270 afair, but I have no idea how that car box is supposed to look like.

In any case: I'm not much of an items/mapgen person so anyone with some experience building structures is more than welcome to have fun with this.

**Comment by vache** [comment]
Actually stores like that do tend to have a bit of furniture, at least appliances.  Ovens, fridges, washers and dryers would all be common things to find.  There would certainly be things like model kitchen displays where they have various arrangements of cupboards and counters and appliances.  Also one aisle full of toilets.  Things like wheelbarrows would be common in the lawn and garden area.  Also carts like these I think are more what soup was thinking: http://www1.pictures.zimbio.com/gi/Alex+Sierr+Home+Depot+Net+Income+Increases+qTGgZfpge_Ql.jpg

This could end up being a very high priority building to hit early on though, especially if it has all the tools that it would be expected to have, especially considering that specials can't be placed directly in cities at the moment, so it would be away from the bulk of city zombie spawns.  I think the zombie population should have to be fairly high to compensate and deter the player for a little bit, otherwise it's an easy catapult through early scavenging.

**Comment by drbig** [comment]
Furniture/appliances: I'm against the in-game version having furniture (definitely) and appliances (at most very little). I guess that they might have it in US, but the EU ones tend no to - except the arranged bathroom/toilet displays (so it's in general not unrealistic for such a mall not to carry furniture and/or white-goods).

Though as usual I'd be OK if that's "how it would look like in New England".

Carts: the type you've linked to, and then 'flatbed' carts, and then just the plain shopping cart - just *larger*. I'm impartial to any and all (and any would be a cool addition).

Balance: Good point. The way I see it the tools are actually secondary to the raw materials - we have city shops for tools. I'd be ok with most of the tools being looted, but I wouldn't overrun it with zombies. In fact I'd put less zombies than the usual malls have (half/quarter?). I'd also be OK with the spawn rate of such mall to be lower than the usual mall. Sure if your fresh char spawns near this kind of mall it might be worthwhile to try get some tools relatively easily (and that's relatively, same deal as with public works imo).

The general point is: raw materials. Plenty of them. Not really useful if you have problems getting food and water.

**Comment by drbig** [comment]
In other words: By the time your char arrives at the building supplies mall it's mostly tons of concrete and gallons of paint and a couple dozen zombies that weren't fast enough to loot the cool stuff. And the vending machine has only pretzels and rotten juice.

**Comment by vache** [comment]
The furniture and appliances would be in a big box home improvement type store (Lowe's, Home Depot), which is what would likely be present in New England.  These stores are generally all-in-one type places with things like light fixtures, toilets and plumbing supplies, carpet, countertops, gardening and landscaping supplies, concrete, lumber, hardware, tools, cleaning supplies, electrical hardware, basically everything.  I wouldn't imagine they'd have raw logs though, mostly processed wood products like 2x4s and plywood sheets.  

Other places for just raw materials that might contain logs as well would be lumber yards and industrial supply stores (Grainger is one of the most common I can think of, mostly wholesale and not the type of store an average member of the general public would frequent).  These stores are often smaller than the big box stores, but much more specialized.

**Comment by drbig** [comment]
Aye. Sounds right.

> lumber yards and industrial supply stores

The grand idea here is: industrial zones - however such thing would look like in New England. This in my imagination would be the proper place to spawn literally tons of raw materials. But as I have no idea how this should actually look, I can't comment much more.

Given the above the building supply mall (can we call it somehow better?) is relatively small thing to actually make and could stand in temporarily for the proper industrial zones as a raw materials source. If and when such industrial zones were to be a feature then the mall could be scaled item-wise more into a proper Home Depot clone. Does that sound OK?

**Comment by PropaneSoup** [comment]
> the building supply mall (can we call it somehow better?)

I'm taking a stab at making this right now, and I've taken to calling it Home Improvement Megastore.

And I can agree, lots of raw materials, scarce amounts of tools.

**Comment by KA101** [comment]
Yeah, tools would totally be looted/appropriated (as would be a lot of 2x4s and plywood sheets) to fortify pre-Cataclysm.  Concrete, insulation, tile, windows (glass should be available!) etc would likely be around.  Same with copper wire, pipes, etc.

*KA101 has spent a fair amount of time and money in these recently thanks to renovating a house* >_<

**Comment by drbig** [comment]
Trees and therefore logs and 2x4s are already *very very* easy to obtain in for-construction quantities - as compared to nails, concrete, paint, carpets, rebar etc. - so I'm OK with lumber products being there in relatively smaller quantities (and yeah it makes sense looting-wise - we do see boarded up houses).

@PropaneSoup I'll definitely patch it in pre-official-merge and try it out as soon as you share it :)

**Comment by kevingranade** [comment]
I think a better fit for what you're trying to make, and that often exists
on the outskirts of new england towns is a building supply *lot*.
Surrounded by a fence, with a central courtyard.  On one side there's a
smallish building with expensive/small/weather sensitive items, and the
rest of the lot has mostly open sheds with bulk building materials (lumber,
sand, gravel, soil, lumber, tile).  Just a thought.

**Comment by drbig** [comment]
@kevingranade Noted down. I'm going to still push for the Home Improvement Megastore for starters as discussed here for starters.

@PropaneSoup /me goes testing.

**Comment by drbig** [comment]
@PropaneSoup After a long and arduous journey I did come upon a Home Improvement Superstore!

This is based on a single encounter:

What I liked:
 - The unusual 2x3 format
 - The drive-through section
 - The room with seeds
 - The relatively-well stocked crate room
 - Less numbers but stronger zombies (majority was tough zombies)

What I would change:
 - Bags of concrete directly, but the cement will be *useful*
 - More metal rack rows, the place seems eerily spacious for a superstore

Thank you for this great addition :)

And now please excuse me, I need to *drive back home*.

**Comment by PropaneSoup** [comment]
Glad you liked it! Don't think I could do a building this big again though, counting all those little characters over and over was an exercise in frustration, I have no idea how acidia does it with the Necropolis :P 

But credit where credit is due, the increase in stronger zombies is actually because of Frost-Wood's monster-group replacement PR. You probably found it after its 14 day break-off point for stronger zombie spawns.

**Comment by KrazyTheFox** [comment]
> Don't think I could do a building this big again though

When I start doing less programming at work I'll continue working on a map editor program for things exactly like this. It should make all that frustration a thing of the past.

**Comment by drbig** [comment]
This is done. (cleaning own issues for now)
