### ISSUE TITLE
Building boardable vehicle part below yourself doesn't board the vehicle or make it controllable

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11858]
If you're standing on a frame square of a vehicle and you install a seat and controls in that square, you can't control the vehicle without stepping off the square first.
##

**Comment by kevingranade** [comment]
Just a guess, sounds like a caching issue.

**Comment by KA101** [comment]
Concur re caching issue.  Annoying, more an oversight than a Bug, but yeah.
