### ISSUE TITLE
Fire spawning under some creatures causes them to teleport

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#11859]
Creature placement code checks if the creature can move onto the tile it is standing on. If it can't, a nearby tile is selected instead and the creature is moved there.

Movement code checks if the creature is afraid of fire (and sharp edged terrain etc.) and completely forbids moving onto the tile if this is the case.

Can be easily tested by attacking slow, idle creatures such as blank bodies with a flamethrower, but is more obvious when a tank drone or chicken walker does it (due to it being done on "monster turn").

A more rare and minor version of this bug happens when hulks smash fish out of the lake or land animals into it.
##

**Comment by KA101** [comment]
Hmm.  This seems like a recent addition, since aquatic critters are supposed to insta-die if knocked out of the water and SUNDEATH folks to get Massive Damage'd if in sunlight.  Therefore critters should be able to be moved into such no-go zones against their will.

**Comment by Leland** [comment]
#18038 adds the following:

> ...when a monster with the PATH_AVOID_DANGER_1 or PATH_AVOID_DANGER_2 flag is standing on a fire field, it gains the ability to teleport to a nearby clear square in order to get itself out of harms way. The range of teleportation appears to be limited to about 3 squares, which is what leads me to suspect that this is (at least partly) intended behavior.
>
> What's probably not intended behavior, though, is that the creature doesn't need a line-of-sight to arrive at said square. In my testing, I was able to get anything from raccoons to Mi-gos to teleport through a solid wall to get away from the fire. The circumstances necessary to cause this are fairly uncommon; the two most likely causes would be a thrown incendiary grenade (how I stumbled across this) or a monster getting cornered by fire in a building.
>
> Monsters without either of the above flags do not demonstrate this behavior.
