### ISSUE TITLE
'not able' changing between Active and Passive bionic list 

### ISSUE THREAD

**Issue by nanoglass** [CleverRaven/Cataclysm-DDA#11853]
I think you are supposed to be able to look/change between the (new) Active and Passive bionic lists, but when I press left, right, >, < or any other key that is not a bionic or used key (!, - and =) the bionic list goes away. 
The only way I found out to change between the lists is to examine a bionic that you know you have.
(being in active bionics, and examening a passive bionic because you know it is under the 'a' shortcut for example)

**Comment by BevapDin** [comment]
The tab key does the trick. It works in other tabbed windows as well. You can press `?` and edit the key bindings if you don't like them, this works in many other menus as well.
