### ISSUE TITLE
Merge vehicle and constructions systems

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11866]
This is a really crazy and farfetched idea, but I'm gonna at least make a quick brain dump of it...

I see a lot of more advanced players on IRC who put a hole in the side of a building and construct a vehicle there so their base can have access to structure-only stuff and vehicle-only stuff at the same time. That seems silly.

Equally silly is needing to make a dummy vehicle for things like a handcrank battery recharger. Or not being able to put wood-and-brick structures in the back of a truck.

Of course, if we move most of the "building things" parts of the construction system into something like the vehicle system, we'd need to leave a lot of the procedural construction stuff, like chopping down trees. I don't think this is a bad thing. I'd much rather chop down a tree by applying an axe to it than by using the construction menu.

This is just an idea, but it's one I'll be mulling over as I get deeper into the vehicle building system. One very basic beginning to implementing this, which is how I got started on this idea, would be to allow the player to use the vehicle interface to attach vehicle parts to walls (as if the wall was itself was a one-tile vehicle frame).
##

**Comment by PropaneSoup** [comment]
IMO, the construction menu is one of the most clunky parts of the game. If you have an idea on how to use bits of the vehicle menu to make it less clunky and give it more features, I would be thrilled.

How would you get into this menu though? Press 'e' on any wall to add stuff to it? If you do it exactly like the vehicle menu, you could then hide in a closet in your fortified house while installing turrets on the outside to kill the assaulting zombies perfectly safe.

**Comment by sparr** [comment]
Idea 1: treat each square of wall as a separate one-square vehicle. this is annoying because it won't let power and water move through your walls

Idea 2: implement vehicle/construction modification distance limits. this is annoying when you're just building a real vehicle, but I think that's more realistic anyway.

Idea 3: idea 2, plus optionally move the character when they move the vehicle modification cursor (unless they move it past an impassable tile), with an overlay on the main window so you can see monsters coming when you're moving.

Idea 4: like idea 3, but just move the whole vehicle manipulation screen out to the main interface, with additional info on the right panel, like the firing interface.

**Comment by kevingranade** [comment]
Concerning the initial idea, this has come up before, you could make
'appliances' that act like furniture, but under the hood are modelled as
vehicles and wired into the vehicle systems.  So you could make a
refrigerator that holds items and chills them, and is attached to a bank of
batteries by jumper cables or similar.  However it would have a flag that
prevents you from using the vehicle construction menu on them (or not, the
main thing is making construction of them more streamlined, right?).

As for the other list of ideas, what's the benefit?

**Comment by sparr** [comment]
Well, as PropaneSoup mentioned, it's somewhat silly and unrealistic to be able to build things onto vehicles many tiles away from your position. Fixing that would be a bonus.

Moving vehicle manipulation to the main interface would mean not needing to implement tiles in the vehicle interface, among other things.

**Comment by KA101** [comment]
re building things outside the crafting bubble: I'm inclined to let folks be presumed to move to the target area and return, since most veh/construction projects take at least half an hour.  Forcing folks to move seems realism that isn't strictly necessary.

**Comment by facepalm** [comment]
If I could propose an idea 5: use one virtual vehicle (or generic Construction superclass) per map tile.  Rebuild the construction menu in the vein of the vehicle menu, but show the entire tile (terrain and all), and don't enforce adjacency. Building a storage vat out in the front lawn is done exactly the same way as extending a wall or digging a pit.

This would also allow for an easy "power grid" implementation: a generator will be able to power everything in the tile without fussing with connectivity issues.  At some point in the future, I could also see adding a transformer construction to supply power to adjacent tiles, but just powering up one house would be great.

**Comment by sparr** [comment]
by map tile you mean a 24x24 square area, one overmap terrain space, four submaps?

**Comment by DavidKeaton** [comment]
Having one extra stored class on a map tile would increase size drastically.

**Comment by facepalm** [comment]
>by map tile you mean a 24x24 square area, one overmap terrain space, four submaps?
I believe so.  "A house" is the scale I was thinking of.  What do you mean by "four submaps," though?

**Comment by sparr** [comment]
@facepalm submaps are a weird abstraction layer that are only ever relevant if you're working on the game code. 12x12 blocks the world is made of, four per overmap terrain or mapgen area.

**Comment by DavidKeaton** [comment]
If you mean a class stored (that is, not a mere pointer to a class, which most tiles use iirc), would mean all that extra data tacked on. The methods, not so much, but the vars needed to handle all that would, in guesstimate, double (maybe triple?) The size of data for each map tile. However a pointer to that info, doubt it would be too bad, but it's more pointer handling.

**Comment by kevingranade** [comment]
As KA101 pointed out, the player is assumed to move as necessary to
complete vehicle modifications (and crafting and construction for that
matter), dealing with that in detail doesn't bring anything interesting to
the game.
As for wanting to draw the vehicle using tiles in the construction menu,
your idea 4, but *not* any of the other ideas is the only reasonable thing
on the list, everything else is irrelevant to your stated goal.
Kind of a point of order, the issue tracker is not the right place for
brainstorming, please do that on IRC or the forums.  The issue tracker is
for either bug reports or clearly defined feature requests.

**Comment by sparr** [comment]
I can word it more directly and put it higher next time, but the clearly defined feature request of this thread is "[eliminate the need to] put a hole in the side of a building and construct a vehicle there so their base can have access to structure-only stuff and vehicle-only stuff at the same time [and] needing to make a dummy vehicle for things like a handcrank battery recharger [and] not being able to put wood-and-brick structures in the back of a truck". Everything else is working on how to make that happen.

The vehicle-as-furniture idea could be a middle ground, but that wouldn't be enough for, e.g., solar panels on outside walls, water faucets on the outside of a building, anything involving electricity transmission through a house, etc.

The idea of a virtual-vehicle spanning the whole OMT would address those points, but still leaves behind the desire to put construction items (wood stove, fermenting vat, etc) on vehicles.

**Comment by kevingranade** [comment]
> The vehicle-as-furniture idea could be a middle ground, but that wouldn't
be enough for, e.g., solar panels on outside walls, water faucets on the
outside of a building, anything involving electricity transmission through
a house, etc.

You have a bad assumption here, which is that arbitrary walls can
meaningfully route power and water.  As I said previously, the player is
going to need to set up those links with jumper wires, pipes, or some new
items that act similarly.  If there's a handy window, grab a jumper cable
and climb through it, if we want to support running a cable through a wall
by drilling a hole, that's not too hard to do by making an intermediate
furniture item to represent the hole.

> The idea of a virtual-vehicle spanning the whole OMT would address these
points.

It wouldn't actually, since it would only span one OMT, it would break on
any larger building, this is precisely why jumper cables are implemented
the way they are.  You also couldn't use it to wire up two adjacent houses.

**Comment by sparr** [comment]
> You have a bad assumption here, which is that arbitrary walls can
meaningfully route power

I don't think this is a bad assumption at all. We already assume that arbitrary vehicle frames can route power, and that's far less realistic than expecting to find power conduits in normal building walls. Maybe a few wall types (stone, log) would need to be marked as non-power-transmitting, but most sorts of normal structures should be expected to already have electrical wiring that is *more* capable than what is found in vehicles.

Having pipes to transmit water is more of a stretch, but again we already assume that vehicles have those pipes, which is way more presumptive.

**Comment by KA101** [comment]
> but most sorts of normal structures should be expected to already have electrical wiring that is more capable than what is found in vehicles.

Hi, DIY electric-renovator here.  USian house walls (your typical DDA t_wall) are generally hollow: wood framing supporting electric cables to existing lighting/outlets, with drywall (pressed rock powder, more or less) coverings and then whatever paint/wallpaper/plaster/wev on top of that.  Most wall sections are not set up to take a power feed, and IME so much as moving an outlet from one spot to another can be an exercise in frustration.

Preexisting vehicle sections are far more likely to have conduits, etc than preexisting wall segments IME.

**Comment by sparr** [comment]
I don't think I can point at any 2m wide section of my apartment's walls that doesn't contain any electrical conduits. If I'm in a post-apocalyptic survival scenario and I need to get power from one part of a house to another, I'm going to plug my generator / batteries / solar panels / etc directly into any existing power outlet after opening the mains breaker. There aren't any diodes in a house electrical system, any power put into any outlet is going to be available from any other outlet. And this will work for enough power for a welder or moderate sized appliances, among other things.

Pick a random vehicle and try to get power from one side to the other in enough quantity to run the vehicle's motor, and you're going to have to add wiring.

**Comment by KA101** [comment]
I'd ask for a demonstration of that, but don't care to watch the videos.  Power seems like it'd be divided among all outlets with some connection, though, and at the end of the day you'd need to include he wiring components (copper wire, plastic, scrap metal) in each and every t_wall.

**Comment by sparr** [comment]
Rimworld has walls with and without built-in conduits.

Vehicles have some parts that require wired steel plates (although not nearly enough, since we're allowing power to transmit through every part anyway).

I'd be up for having walls with and without power conduit, and a construction task to add power cables to existing walls.

**Comment by Zireael07** [comment]
+1 for adding power cables to walls as construction.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
