### ISSUE TITLE
Build 2943 crashes on start while 2942 does not

### ISSUE THREAD

**Issue by Zireael07** [CleverRaven/Cataclysm-DDA#11868]
Build 2942 http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/cataclysmdda-0.C-2942.zip works, while 2943 http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/cataclysmdda-0.C-2943.zip doesn't.
Crash on startup with no error message nor any log I could find.

According to @Coolthulhu, happens with both SDL/Tiles and console. I experienced it only in SDL.

Win 7/SDL in both Luminem's (forums) and my case. I don't know what OS Coolthulhu is on.

**Comment by sparr** [comment]
If there's a log to be found, it will be config/debug.log wherever your config and saves and such are stored.

**Comment by KA101** [comment]
Ran fine on mine; apologies.  >_<
