### ISSUE TITLE
Fuel and battery level indicators are broken. Again.

### ISSUE THREAD

**Issue by jarmush** [CleverRaven/Cataclysm-DDA#11876]
In build 2945 linux tiles.

![cat](https://cloud.githubusercontent.com/assets/6452938/6938366/8bf58560-d86b-11e4-9a0b-83685e073dc5.png)

**Comment by KA101** [comment]
01 April, so most everything will need confirmed, I'm afraid.  Apart from that, yeah, looks like the color's out of that at least, and it could be something we missed in the custom-color PR.

**Comment by DavidKeaton** [comment]
I can confirm this issue.

**Comment by jarmush** [comment]
Seems to work fine in 2947
![1](https://cloud.githubusercontent.com/assets/6452938/6949032/9e703d80-d8ba-11e4-9bc0-e32732f3d83d.png)

**Comment by jarmush** [comment]
I've just started new game in linux tiles 2947 build and everything works fine.
![1](https://cloud.githubusercontent.com/assets/6452938/6949124/51859fbe-d8bb-11e4-960e-8a8b552b04ae.png)

**Comment by Zireael07** [comment]
Doesn't look fine - the battery/fuel indicators are supposed to be colored and are gray in your screenshot.

**Comment by DavidKeaton** [comment]
I'll peek on it.

**Comment by DavidKeaton** [comment]
In the process of a fix, I think I have it.
