### ISSUE TITLE
Idea: swappable fluid storage tanks

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11870]
Currently when I take a water tank out of a vehicle, I get an empty barrel. I'd like a way to install a mount for a swappable tank and then put tanks in and out without losing their contents. Is this feasible? Would it be useful?
##

**Comment by Rivet-the-Zombie** [comment]
>Is this feasible?

Anything is doable with enough elbow grease.

>Would it be useful?

Very useful. I'm pretty sure people would fall all over themselves to get at this.

**Comment by Coolthulhu** [comment]
> Currently when I take a water tank out of a vehicle, I get an empty barrel.

You mean you lose the water? That's a bug if that happens

**Comment by Leland** [comment]
Closing because this bug was never confirmed. Please reopen if it has.
