### ISSUE TITLE
Missing letters in confirmation queries when russian selected

### ISSUE THREAD

**Issue by jarmush** [CleverRaven/Cataclysm-DDA#11877]
Everything is OK in english.
![cat](https://cloud.githubusercontent.com/assets/6452938/6938883/b036d83a-d86f-11e4-8c90-56fd06ff0552.png)
![cat2](https://cloud.githubusercontent.com/assets/6452938/6938885/b314b414-d86f-11e4-9c10-54dad6c06c9c.png)

**Comment by VlasovVitaly** [comment]
```bool querry_yn() src/output.cpp``` Should be refactored to respect unicode chars.
Working on it.

Buuuuuuut may just simple clear Russian translation of "yn" string. This will work right now.

**Comment by VlasovVitaly** [comment]
can be closed.
