### ISSUE TITLE
Stamina display wraps after long actions

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#11884]
After performing an action that takes more than 999 moves, the last bar of stamina is pushed into the next line, like what happens to sound display when you hear a >99 volume sound.

**Comment by KA101** [comment]
Possible UI differential (my stamina bar is under the bionic power meter) and still 01 April here for about three more minutes.  I hadn't encountered this, but that doesn't mean that it isn't happening on the narrower sidebar.

**Comment by mugling** [comment]
Closed as unconfirmed
