### ISSUE TITLE
AEP_BAD_WEATHER doesn't do anything

### ISSUE THREAD

**Issue by Frost-wood** [CleverRaven/Cataclysm-DDA#11882]
I was curiously glancing at the artifact.cpp code, and I noticed that AEP_BAD_WEATHER doesn't do anything but give an ominous message "You feel storms coming", and yet there is nothing in to code to create the said storms.
##

**Comment by sparr** [comment]
I'm new here, but I believe there was a major removal of weather code due to a big refactor a while back, and a lot of stuff hasn't been re-implemented.

**Comment by KA101** [comment]
Yeah, we almost certainly lost that with the weather refactor: weather is now more or less on (externalized) rails rather than game-accessible, so artifact-storms (and the debug menu) can't mess with it.  :-/

**Comment by kevingranade** [comment]
To do so we'd need to add an override to the weather system to specifically
apply artifact effects on top of the existing weather system, not too hard,
but also not trivial.

**Comment by narc0tiq** [comment]
I seem to recall a discussion at one point that the mysterious portals
should also have some weather effects associated. This would, I imagine, be
more of the same.
