### ISSUE TITLE
Eliminate submaps?

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11880]
Do they serve a real purpose any more? It seems like all the game logic visible to the player happens at the OMT and map square level. While coding, the handling of MS->SM and SM->OMT seems like an unnecessary extra step.

What would go wrong if we ripped out submaps and just made the reality bubble 5x5 or 7x7 OMTs?

**Comment by BevapDin** [comment]
I thought about this some time ago, it certainly would be nice. Changes in the `map` would probably be simple, mainly the `get_submap_at` function needs to change, most other stuff would not even notice (except maybe some vehicle stuff). There is also some data that is stored as one value per submaps (temperature, computer, camp) which need special handling.

However, the real problem, imho, are the stored submap coordinates all over the place (NPCs have them, some things inside the overmap use them, vehicles use them etc. Converting those in a save compatible form is not simple.

Therefor: would this actually gain much? The submaps are mostly used in the map class and are encapsulated there (get_submap_at and the mapgen / load / save code use them).

It might be a good first step to convert the places that use submap coordinates to either overmap terrain (zoomed out) or map square (zoomed in) coordinates first. Once that is done, the size of the submaps won't have much meaning outside of themself and can be changed.

**Comment by Coolthulhu** [comment]
Could hurt performance if done incorrectly. Some game mechanics operate on submaps - for example fields.

I'd say that merging them "up" by altering overmaps would be easier.

**Comment by vache** [comment]
The biggest benefit I can see from removing submaps is greatly reducing the barrier of entry for map editing.  OMTs are easier to understand because they have a direct in-game representation, and their coordinate system is much simpler.

**Comment by kevingranade** [comment]
To be clear, when you say 'eliminate submaps', you mean 'double submap size
on both dimensions'.  This would be a massive coding effort, and I
guarantee it will break a lot of things.  I'm just not seeing a payoff
commensurate with the work involved.

**Comment by sparr** [comment]
When I say 'eliminate submaps' I mean 'put all the functionality of the current 12x12 submaps into the existing 24x24 OMTs'.

The payoff is eliminating a layer of coordinate conversion every time anyone wants to do something involving map squares and OMTs or overmaps. And removing some headache every time someone new (like me) wants to try doing anything with submaps and OMTs.

**Comment by kevingranade** [comment]
Oh, god no, that's not remotely an option.  The whole point of the
overmap/map/submap division is so we don't have the whole world loaded in
memory at once.  This would increase the memory footprint of the map by up
to 12,000x, not to mention requiring some kind of weird partially populated
overmap tile thing.

**Comment by sparr** [comment]
I don't know what you're replying to, but it's definitely not what I said. I'm suggesting increasing the memory footprint of *some* submap operations by a factor of 4, and the reality bubble would get about 62% larger if it was 7x7 OMTs instead of 11x11 SMs.

Currently we have the following divisions, afaik:
1 OM = 32400 OMT
1 OMT = 4 SM
1 SM = 144 MS

I am suggesting this:
1 OM = 32400 OMT
1 OMT = 576 MS

**Comment by narc0tiq** [comment]
@kevingranade said:
> when you say 'eliminate submaps', you mean 'double submap size on both dimensions'

@sparr said:
> When I say 'eliminate submaps' I mean 'put all the functionality of the current 12x12 submaps into the existing 24x24 OMTs'.

I fail to see how these are not exactly the same thing. You make a submap-like class that's 24x24 map squares, and you make it do all the things submaps already do anyway.

What I **really** don't see is how this would eliminate coordinate conversion -- perhaps I'm dense, but for the most part, you should be able to basically ignore submaps altogether, as @BevapDin said:

> The submaps are mostly used in the map class and are encapsulated there (get_submap_at and the mapgen / load / save code use them).

**Comment by sparr** [comment]
We already have a 24x24 thing, an OMT. The difference in what you said and what I said is that your version leaves us with two 24x24 structures, each handling different functions for coincident areas.

You can see some SM/OMT coordinate conversion in a PR I worked on recently here: https://github.com/CleverRaven/Cataclysm-DDA/pull/11802/files#diff-ab005ad9757130721ffb66a09833090aR4587

One place where this "problem" appears is that the relative coordinates in the reality bubble currently start on half-OMT boundaries, so there's not a simple conversion available. relative coordinate -1 and +1 could be in the same OMT (at coordinates 11 and 13) or in neighboring OMTs (at coordinates 23 and 1).

**Comment by BevapDin** [comment]
The OMT you means is an overmap terrain **type**, like a normal terrain type, it must not change during the game.

**Comment by vache** [comment]
I don't think OMT's are 24x24, except in the in-game's representation abstracting the submaps.  This was one of the difficulties for me trying to understand mapgen.  It seems like oter_t and oter_id are the two classes responsible for defining an omt, and they are only used during world gen and in rendering the map.  Except for those two situations, the OMT is largely abstract, and all of the physical data is in submaps.

**Comment by narc0tiq** [comment]
> your version leaves us with two 24x24 structures

Oh, I see where the misunderstanding comes from! No, there is not actually a structure that represents an overmap tile -- the overmap has `oter_id`s, which are just strings. The new structure would, in fact, be the only one.

As to the other problem, I won't take the time to read a big diff right now, but why use reality-bubble-relative coordinates at all? Convert them to (or acquire them in the first place as) absolute and let them be converted to OMTs with simple division.

**Comment by sparr** [comment]
@BevapDin I didn't mean to refer to the terrain type, but to the 24x24 block of map squares that one overmap square represents. If there's a better three-letter-or-fewer acronym for that, to go with Map Square and Sub Map and Over Map, I'll use it instead of OMT.

@narc0tiq I was using reality-bubble-relative coordinates because I was working in an existing context where those are the coordinates that are already available. Specifically, I was in the loops for "figure out which tiles the player can see due to lighting, LOS, view distance, etc". My link above should go to a specific line in the diff. The ~15 lines below that have some coordinate conversion in them.

@vache In addition to rendering the map and during mapgen, overmap coordinates are also used when calculating overmap visibility while you explore. Also for map note storage. I can't say for sure that that's all, but it's what I've encountered so far.

**Comment by sparr** [comment]
When I say I'm suggesting this:
1 OM = 32400 OMT
1 OMT = 576 MS

I could just as easily be suggesting this:
1 OM = 32400 SM
1 SM = 576 MS

I don't particularly care what name the intermediate structure gets, I'm just wanting to eliminate one mostly unneccessary step on that ladder.

**Comment by vache** [comment]
One problem I ran into working on the computer PR that might be alleviated by @narc0tiq 's suggestion was that if you wanted to specify coordinates, say a computer option would open a door located at 5,5, it lines up properly on a 2x2 tinymap, but during gameplay, the 11x11 it ends up being several submaps away.  I ended up having to do some coordinate voodoo (there was probably a much simpler way) and convert the coordinates when they're read to be relative to the computer the action would come from, and then use coordinates passed in from the iexamine function to relate to find where the action should take place.

Though this is probably a product of my misunderstanding of the coordinate conversion methods, it seems like it would be much easier to understand in the first place if it were easier to match in-game representations with in-code representations.  Also, omt level coordinates being the lowest would make map rotating SO much nicer.

**Comment by BevapDin** [comment]
> @BevapDin I didn't mean to refer to the terrain type, but to the 24x24 block of map squares that one overmap square represents. If there's a better three-letter-or-fewer acronym for that, to go with Map Square and Sub Map and Over Map, I'll use it instead of OMT.

Yes, I know, your wording is correct, OMT is fine. However, an overmap terrain is just an integer, just like `t_floor` or `t_window`, it contains nothing and as such can not be compared to submaps (which are large structures with content).

It determines what is shown in the overmap (just like `t_floor` determines what is shown in the main window), and what mapgen functions should be used to generate the map there.

> We already have a 24x24 thing, an OMT.

This is what is wrong, the OMT is *not* a 24x24 thing. It is just an integer, which is used to selected the mapgen function, the function in turn creates the 24x24 map squares, but it could as well create 48x48 map squares, the overmap terrain types does not store anything about this.

**Comment by sparr** [comment]
Maybe there's not a name for the OMT-coincident thing I'm describing. I'm talking about the thing that the _to_omt conversion functions reference. The thing, whether it exists as a concrete object or just as a concept, that overmap visibility is calculated based on.

**Comment by BevapDin** [comment]
> Maybe there's not a name for the OMT-coincident thing I'm describing. I'm talking about the thing that the _to_omt conversion functions reference. The thing, whether it exists as a concrete object or just as a concept, that overmap visibility is calculated based on.

Yes, that's the overmap terrain, you're absolutely right there and it's the proper name for it. I'm only concerned about this:

> We already have a 24x24 thing, an OMT. The difference in what you said and what I said is that your version leaves us with two 24x24 structures, each handling different functions for coincident areas.

The OMT is a simple int, not a "24x24 structure" (like the submap is a 12x12 structure), the submap can store 144 (possible different) terrains for each of the 144 map squares it contains. The overmap terrain is just an integer that applies to *all* the 2x2 submaps and *all* the 24x24 map squares.

----

I'm all for this change. What you want is (basically) to change SEEX and SEEY to 24 (and adjust all the dependencies, e.g. `map::get_submap_at` and loading submaps etc.), each overmap terrain would than contain exactly one submap. A submap coordinate would be the same as an OMT coordinate. The submap is than a 24x24 structure.

I'm completely for this, I have no clue why this separation was done in the first place, mapgen *always* operates one a 2x2 grid anyway. Every game has (theoretically) always either no submap or 2x2 submaps for any given overmap terrain.

**Comment by sparr** [comment]
I didn't mean a literal C++ "struct" when I said structure.

And it's not just a simple int. The place where an OMT is just an int is the least concerning to me. What I'm bothered by is the places where an OMT is a 24x24 block of ints (or enums, or pointers) inside a larger array (such as seen_cache for the reality bubble).

**Comment by BevapDin** [comment]
The seen cache (and all the other caches in the map) has nothing to do with overmaps. It's a 132x132 structure (11==MAPSIZE, 12==SEEX, 132==11*12). If you increase the size of submaps, you should reduce the MAPSIZE, otherwise the reality bubble will be bigger (which affects performance).

> And it's not just a simple int.

I'm wondering whether we talk about the same thing. What else do you think it is? Overmap terrain type is an instance of `oter_t`, which is an int id and a string id and some more flags and data. It's very much like `ter_t`.

It's stored in the overmap in a wrapper `oter_id`, which is literally just an integer with some additional functions for easier usage. It's very much like the `ter` array in `submap`.

**Comment by sparr** [comment]
I don't know how many ways I can re-state this. I'm not just talking about concrete declared separate data structures.

Within the 132x132 arrays related to the reality bubble, there are blocks of 24x24 entries that refer to an OMT. If you want to do something inside that array that applies to an OMT (like the patch I linked to above), you have to do multiple layers of coordinate conversion (not necessarily manually). I actually gave up on that and just stopped at submaps, which was a cheap out for me.

You can see, right there, where I'm doing something to an OMT in the context of map-square coordinates.

**Comment by Frost-wood** [comment]
The problem I think with changing the submap to a 24x24 piece is when the player is moving around.  Instead of loading a 12x12=144 piece, you are loading a 24x24 piece which requires 576 pieces and god forbid you have to load 2 24x24 pieces by moving diagonally.

The overmap terrain  is more a reference to a mapgen function than an actual type.

**Comment by sparr** [comment]
we already keep in memory all of the data about an area of 11x11 submaps centered on the player. This is the so-called "reality bubble". When you take a step northwest from one submap to another, we load 21 new 12x12 submaps into memory, 3024 tiles. If we, instead, used 7x7 OMTs for the reality bubble, we'd be loading 7488 tiles at that point, but we'd be doing it half as often. I don't expect that to be a very signficant problem.

**Comment by kevingranade** [comment]
I wouldn't be opposed to having 24x24 submaps, I'm just sceptical that the
payoff is worth the effort.
Larger than 24x24 runs into additional difficulties, because in practice
submaps are dealt with in 2x2 blocks in most cases anyway, including the
reality bubble, which pins 12x12 submaps in memory, but operates on 11x11
of them at any time.

**Comment by sparr** [comment]
OK. I think I'm going to try to tackle this, once I've landed a few more patches that touch map code.

**Comment by Coolthulhu** [comment]
Can it wait after Z-levels?
I already have tons of conflict with every map.h/cpp update...

**Comment by sparr** [comment]
You and me, both. It will wait until either my current map PRs land or I abandon them.

**Comment by kevingranade** [comment]
The z-level changes have priority.

**Comment by sparr** [comment]
The z-level changes have priority. (maybe exactly repeating what someone else says will adequately convey that I agree with them where conversation hasn't)

**Comment by tyrael93** [comment]
@ welcome to neoDDA's open source.

**Comment by kevingranade** [comment]
The question was answered as far as I can tell, we'd be fine with someone doubling the size of a submap so it is the same size as the area represented by an OMT.  It looks like a lot of work, and will almost certainly break a number of things for a while, but making mapgen and map implementation code work on a unit of the same size is a worthwhile thing to do.

**Comment by ZhilkinSerg** [comment]
Could someone please explain where does this limit of `360` come from? `OMAPX + OMAPY`? `2 * OMAPX`? I do not see this value anywhere, but in the comment.

https://github.com/CleverRaven/Cataclysm-DDA/blob/3ebcd5bc0ff3eaf40c29ce444d5b214ea1145dfe/src/coordinates.h#L27

**Comment by vache** [comment]
A single overmap is 180x180 overmap tiles, a single overmap tile is 2x2 submaps, therefore a single overmap is 360x360 submaps.

**Comment by ZhilkinSerg** [comment]
> A single overmap is 180x180 overmap tiles, a single overmap tile is 2x2 submaps, therefore a single overmap is 360x360 submaps.

So, it is not an `area`, but a `dimension`?

**Comment by vache** [comment]
Yeah, it's saying the overmap is 360 submaps wide.

**Comment by ZhilkinSerg** [comment]
> Yeah, it's saying the overmap is 360 submaps wide.

Thanks! That makes sense now.

**Comment by ZhilkinSerg** [comment]
Something went wrong  😄 

![image](https://user-images.githubusercontent.com/16213433/35947645-f721f220-0c79-11e8-87be-1b2e359a1a2e.png)

More in https://github.com/ZhilkinSerg/Cataclysm-DDA/tree/mapgen-submap-x2
