### ISSUE TITLE
Compiling with 'make' broken on Windows

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#11898]
Is the support for building from console on Windows dropped?
It worked a few revisions ago, then suddenly it started requiring `pkg-config` (easy to acquire in binary form) and ncurses (hard to get for windows).

Ncurses are only needed for linking phase, but not really because CodeBlocks projects doesn't even try linking them.

**Comment by DavidKeaton** [comment]
We could instead link against pdcurses for windows.

**Comment by Coolthulhu** [comment]
There's probably no need, as CodeBlocks project handles everything without any curses.

**Comment by DavidKeaton** [comment]
Oh right the windows term emulation

**Comment by narc0tiq** [comment]
I'm not entirely clear on what "building from console on Windows" implies
-- if it's something like `make NATIVE=win32`, it should be working.
Otherwise, this has been broken since before the 0.C release, at minimum.

**Comment by Coolthulhu** [comment]
Crap, might have forgotten that NATIVE part. Will try to compile with it and check.

**Comment by Coolthulhu** [comment]
OK, my fault. Closing
