### ISSUE TITLE
needles/guns can't be reloaded, if you right click when choosing thread, in the prompt.

### ISSUE THREAD

**Issue by FireCrow1973** [CleverRaven/Cataclysm-DDA#11892]
Let me just reload my new bone needle right quick! 

thread (200)
out of tread!

sinew (30)
out of tread! x 2

**Comment by facepalm** [comment]
It's working fine for me.  Is it really saying "tread" for you?

**Comment by FireCrow1973** [comment]
yes (out of tread! x 3) im on 2951 config fill copied from 2907.
just started a new character, made a bone needle, have tried:
tread (200), (100) and sinew (30).
nothing?

**Comment by facepalm** [comment]
No, I mean "tread," not "thread," with no 'h.'  

Are you playing on a translated version of the game?  If the game is looking for "tread" but it's finding "thread," that would cause that error message.

**Comment by FireCrow1973** [comment]
How embarrassing of me, i meant "thread", it sees "out of thread".
i play the game in English from:
http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Curses/
I have restarted the game, quit the game and still the same problem.

**Comment by Rivet-the-Zombie** [comment]
Just tested on 2952; cannot replicate.

**Comment by FireCrow1973** [comment]
i just started a new character gave him survival (2), wished for bone and made a bone needle, and it worked fine.
but when i reload the other save it still doesn't work!

i guess i could post a screen shot, but i would that help?
maybe i could post the entire game of somthing??

**Comment by facepalm** [comment]
Actually, I just ran into this myself.

When reloading a sewing tool, in the "choose your thread" screen that pops up when you have more than one type of thread, pressing return to select an option works, but pressing right (which is normally a select action) gives the reported error message.

**Comment by FireCrow1973** [comment]
@facepalm damn your good!
