### ISSUE TITLE
Pico Hydro

### ISSUE THREAD

**Issue by JimQuaid** [CleverRaven/Cataclysm-DDA#1189]
http://en.wikipedia.org/wiki/Pico_hydro

An electric power generator that can be set up near rivers. Makes sense from an in-universe point of view; if you can build a whole car from scratch and supply it with electric motors a small water driven power plant shouldn't be that big of a problem. Might be overpowered from a gamebalancing point of view though.

The way I envision it it would be considered "furniture" (as opposed to set and reset traps) that needs to be constructed on site. Can you build on shallow water? It would need to be surrounded by at least 3 deep water and 5 shallow water tiles. Skill requirements would be high, 10 construction and electronics as a secondary skill. Needed components would be an alternator (from disassembling V6 and V8 engines) some scrap metal, copper wire, rubber hoses and some sort of housing (a few gallon jugs?)

The pico hydro would take UPS-Units and charge them at a rate of 10% everyday. Once you put an UPS inside you cannot take it out until it's fully charged (makes it easier for coding - I guess?)

**Comment by mugling** [comment]
Closed due to lack of interest in over three years
