### ISSUE TITLE
"DEBUG: can't find t_leanto" on load or start new game

### ISSUE THREAD

**Issue by jarmush** [CleverRaven/Cataclysm-DDA#11908]
linux tiles 2960

![2015-04-04 16 16 26](https://cloud.githubusercontent.com/assets/6452938/6992767/fc078700-dae5-11e4-81b3-dfed4aacba48.png)

**Comment by BevapDin** [comment]
It's from a mod, but why is it loaded in "src/mapdata.cpp"
```
t_improvised_shelter, t_leanto,

t_leanto=terfind("t_leanto");
```

It shouldn't be there. It is not even used anywhere in the code, the variable is completely useless.

I suggest removing *all* those terrains and referring to them by there string-id. Any objections?

While we're at at: the variable `t_improvised_shelter` is defined and even used in player.cpp, but never loaded, that's another bug.

@KA101: what problems did you have with this terrain and the load order mentioned in the commit?

**Comment by KA101** [comment]
Had this problem when loading a world with the mod enabled.  Added it to mapgen and the problem did not recur.
