### ISSUE TITLE
Crafting clothing to accommodate mutations?

### ISSUE THREAD

**Issue by FredZeppelin** [CleverRaven/Cataclysm-DDA#11909]
My current character has developed an ursine muzzle. His head is also always cold because scarves and such don't fit anymore. I crafted a balaclava, but it still doesn't fit. You'd expect that if crafting a custom piece of clothing, you'd be able to size it to fit your current body shape. 

I realize that the craftable items are just simple recipes, but is there a way to accommodate this need?
##

**Comment by Zireael07** [comment]
Look for XL clothing. I think it was book-locked some time ago.

**Comment by Rivet-the-Zombie** [comment]
XL survivor gear fills this need nicely, and it's autolearned once you level your fabrication and tailoring skills high enough.

**Comment by KA101** [comment]
I'll add to the list of stuff to look into: tailoring kit grabbing a percentage of the components and making an XL-flag that such tailoring could add.
