### ISSUE TITLE
Display issue in keybinding menu

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#11918]
In the keybinding menu (via ? -> 1), some of the action descriptions are longer than the table column, resulting in the action spilling over in the key row, making it look weird and hard to see what the actual hotkey is. The window should probably be expanded in size.

**Comment by Zireael07** [comment]
Agreed, I'm seeing the same.

The keybinding menu is not the only culprit - armor layer screen is another.

**Comment by DavidKeaton** [comment]
I think the largest culprit is that we have to (?) support 80x24 terms. At least, KA has stated as such iirc.

**Comment by KA101** [comment]
Yeah, this has been around since ever and I don't expect it to go away, thanks to the magic of 80x24 and multi-column layouts that don't adequately "flex"/scroll/etc.  Would be glad to be wrong, though.

**Comment by molkemon** [comment]
Well, maybe it is possible to at shorten the action descriptions so they fit? Or can the window be of dynamic size depending on terminal width? That would also fix the problem for most players I guess.

**Comment by KA101** [comment]
>shorten the action descriptions

Then we have understandability & translation (same concept can take more/fewer characters in other languages) issues.  Bears thought, but no promises.

**Comment by DavidKeaton** [comment]
I actually wouldn't mind taking a look at the UI at some point. Was gonna help me in a personal project anyway. :-)

**Comment by kevingranade** [comment]
As for the minimum size, I'd need to see a lot of checking that we aren't
making the game unplayable for people.  Here's a series of things that we
could do to make it happen:
Forum survey to establish a target minimum resolution to support.
Add a warning screen that says something like, "We are considering
increasing the minimum supported resolution of DDA, and your resolution is
smaller than our target, please <do something that let's us know your
resolution> if you need your resolution supported."
Let the warning screen sit around for a while, including a release.
Using the feedback (or lack thereof) from the warning screen, set a new
minimum resolution.
Profit?

I'm not interested in running such a campaign, if someone else is and needs
help with the coding, I'd be happy to help with that part.

**Comment by DavidKeaton** [comment]
Since the forum definitely has presence on things that happen here, perhaps a forum campaign? :-O

**Comment by illi-kun** [comment]
#12404 significantly improves the described menu.
