### ISSUE TITLE
Request for a global "unload" hotkey

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#11917]
If you want to unload a flashlight, cardboxes or whatever, currently you have to go into the inventory screen, select the item, then (U)nload it. There should be a direct unload hotkey, so you only have to press that key and then select the item (at least setable in the keybindings menu), like there is one for disassembling.

**Comment by DavidKeaton** [comment]
U works for the currently wielded item.

**Comment by molkemon** [comment]
Yes it does, but that's not the point. If i have a large amount of items to unload (food in cardboxes, several flashlights etc), then it is annoying that I have to press an extra key everytime. There is a key for disassembling directly, so why shouldn't there be for unloading an item in the inventory?

**Comment by DavidKeaton** [comment]
Unloading seems to be less common than disassembling. I personally use AIM for most actions on multiple items.

**Comment by FireCrow1973** [comment]
i completely agree with @molkemon this slow and awkward process is the main reason why I don't make Molotov cocktail.
its super awkward!

**Comment by DavidKeaton** [comment]
Fair enough. :-) The only problem that we have is that we are running out of keys so quickly! D^:

**Comment by FireCrow1973** [comment]
i think to battle this problem efficiently it must bee attacked right away:
send everybody who downloads the game,a custom keyboard!!!!!!!!!  

How about this, a batch-action option in the advanced inventory menu(the "/" menu).
were you say what you want to do, like:
dissemble all guns in the shopping trolley,
unload all selected items
and so on.

**Comment by ejseto** [comment]
>Molotov cocktail

There is a button to unload bottles for that. 'E' ^_^

**Comment by KA101** [comment]
>i think to battle this problem efficiently it must bee attacked right away:
send everybody who downloads the game,a custom keyboard!!!!!!!!!

On your dime?  sure!  Forum PM me your contact information and I'll get in touch with Narc.

*KA101 fully expects FireCrow1973 was joking, and straight-lines xem anyway*

**Comment by DavidKeaton** [comment]
Gotta be an expensive Dvorak keyboard for me y'hear!

**Comment by molkemon** [comment]
Well, the action doesn't have to have a hotkey to begin with, just having to option to set one for the action would be great though.

**Comment by DavidKeaton** [comment]
Maybe at this to the action menu?

**Comment by FireCrow1973** [comment]
that is like one third of what i was saying!
1/3 group or category selections --> batch action
1/3 batch action -->  action menu
1/3 action menu --> 3/3

**Comment by ArikVhedrovix** [comment]
Yes, please! I am always gathering anything with batteries bc my tazer thirsts for the blood of innocent Z's. Unloading a stack of flashlights in my inventory with a single key press would be a dream come true. Even just a prompt if you unload an item in a stack that asks,"Unload all these Foos(100)?" or something would be awesome.
