### ISSUE TITLE
Tailoring kit improvement suggestions

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#11919]
1) Tailoring kit upgrades should tell you beforehand how they impact an item (statwise, especially encumbrance).

2) Upgrades should be reversible. 
##

**Comment by graysage1** [comment]
>1) Tailoring kit upgrades should tell you beforehand how they impact an item (statwise, especially encumbrance).

I would seriously want to see this happen.  Right now you just have to either guess what the each upgrade option does, or experiment and waste materials, or save scum.

**Comment by Zireael07** [comment]
Agreed completely with 1, on the fence about 2.

**Comment by Coolthulhu** [comment]
There should be a way to remove upgrades, even if it didn't return the materials.

I didn't use the kit for a while, but if the author changed it as I suggested (first select item, then upgrade, not the other way around), mentioning the stat changes (and the cost) in the description should be very easy.

**Comment by Leland** [comment]
Closing - old and no movement. Feel free to ping me here if there's still interest, or make a new issue.

**Comment by AMurkin** [comment]
no.1 is done already
![image](https://cloud.githubusercontent.com/assets/1931904/25614624/68c06f46-2f3b-11e7-8fbe-80643b1ccdb8.png)
