### ISSUE TITLE
Hydraulic muscles do not work

### ISSUE THREAD

**Issue by RadaRadaRada** [CleverRaven/Cataclysm-DDA#11924]
As noted in Cataclysm DDA thread on Bay12.

**Comment by BevapDin** [comment]
Which version? They work fine for me, I use them quite often lately, mostly to drag broken vehicles from the road. This does not work without activated muscles.

However, you have to wait for a turn after activating them before their strength affect is used, *that* might be bug.

**Comment by KA101** [comment]
Yeah, that and the sound wasn't playing every turn they were on, but they worked just fine IME.
