### ISSUE TITLE
Move # of a stack in advanced inventory should not have the current stacksize as auto-filled in suggestion

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#11921]
If you want to move a certain number of a stack using the advanced inventory management, per default the m key, the dialogue that pops up always has the entire stacksize already filled in. Since you use this dialogue SPECIFICALLY to only move a part of that stack, this is the exact opposite of what it should do. 

It results in you having to delete the already filled in number and then type the wished amount to move afterwards. The dialogue should start out empty, so you only have to type the number.

**Comment by sparr** [comment]
Do we have the ability to select/highlight text? Maybe start with a number, but have it selected so you typing overwrites it.

**Comment by DavidKeaton** [comment]
I don't think we do @sparr. I am currently doing some AIM improvements, I can slip this in.

**Comment by KA101** [comment]
Yeah, IME console windows don't allow text selection (at least the WinXP implementation does not).
