### ISSUE TITLE
Sores mutation not rebalanced for x10 encumbrance

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#11933]
http://smf.cataclysmdda.com/index.php?topic=14.msg229479#msg229479

Sores increase the pain to 5 + 4 * abs(encumbrance), where encumbrance is the highest encumbrance on the character (except torso, for some reason).

**Comment by facepalm** [comment]
I just assumed it was a "too bad, boyo, time to reroll" mutation.  

I imagine the torso exemption is to still allow for carrying a backpack or duffel bag.  The pain isn't great, but having absolutely no inventory room is the real killer.

I'll fix it tonight if no one gets to it before then, and add something in the description like "your limbs are covered in sores, etc" to hint that torso is exempt.
