### ISSUE TITLE
UTF8 locale-detection reports false-positive on composite locales

### ISSUE THREAD

**Issue by namarrgon** [CleverRaven/Cataclysm-DDA#11941]
#11525 and #11828 added a check for whether the system's locale supports the utf8 encoding and prints a warning in case it doesn't. The code expects `setlocale(LC_ALL, NULL)` to return either NULL or a string with a single locale but does not account for a different format on systems that override at least one of the LC_* variables e.g.: ```LANG=en_US.UTF8 LC_MESSAGE=ja_JP.UTF8``.

[This](http://www.lehman.cuny.edu/cgi-bin/man-cgi?setlocale+3) is for SunOS but it explains the behavior better than linux' ``man 3 setlocale``.
>For category LC_ALL, the behavior is slightly different.  If
>a  pointer  to  a  string  is given for locale and LC_ALL is
>given for category, setlocale() attempts to set  the  locale
>for all the categories to locale. **The locale may be a simple
>locale, consisting  of  a  single  locale,  or  a  composite
>locale.**  If  the locales for all the categories are the same
>after all the attempted  locale  changes,  setlocale()  will
>return  a pointer to the common simple locale. If there is a
>mixture of locales among the  categories,  setlocale()  will
>return a composite locale.

On a system configured via ``LANG=en_US.UTF8`` ``setlocale(LC_ALL, NULL)`` returns something like ``en_US.UTF8``.
On a system that overrides at least one LC_* var, e.g. ``LANG=en_US.UTF8 LC_MESSAGES=ja_JP.UTF8`` it will return the full list of supported LC_* variables on that platform: ``LC_ALL=en_US.UTF8;LC_NAMES=en_US.UTF8;LC_MESSAGES=ja_JP.UTF8;LC_TIME=en_US.UTF8;`` etc.
The [code](https://github.com/CleverRaven/Cataclysm-DDA/blob/b5bd1b2b/src/game.cpp#L13754-L13762) cannot deal with that and prints the warning even if everything will work as expected.

This happens on Archlinux and Debian, i didn't have the willpower to test on Gentoo but several people confirmed it on IRC and most glibc/posix systems will behave similar.

**Comment by DavidKeaton** [comment]
I am Gentoo, and this is where I found out to PR the fix I did. Would anyone be able to confirm this? Not doubting its legitimacy, just don't see off hand how this would still cause it to print, and I don't know if everyone you stated has issues is using that patch I put through.

**Comment by namarrgon** [comment]
Which patch do you mean? The one from #11828?

```c++
        for(size_t i = 0; i < locale.length(); ++i)
            locale[i] = toupper(locale[i]);
        auto index = locale.find("UTF");
        // were we able to find those three magical letters?
        not_utf8 = index == std::string::npos ? true : false;
        if(not_utf8 == false) {
            // replace entirety of string with important part
            locale.erase(0, index);
            // afterwards, it should simply be UTF8
            index = locale.find('-');
            if(index != std::string::npos)
                locale.erase(index, 1);
            // anything but zero indicates failure
            not_utf8 = locale.compare("UTF8") != 0;
```
The problem is that the code finds the first instance of ``UTF`` in the ``locale`` string, deletes everything in front of it and then compares the remainder to ``UTF8``. That works for ``en_US.UTF8`` but already fails for ``LC_ALL=en_US.UTF8;LC_TIME=en_US.UTF8``

**Comment by DavidKeaton** [comment]
I see.
