### ISSUE TITLE
Green fuel pumps can not be destoyed

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#11945]
Not really important but just a heads up that the green fuel pumps cant be destroyed or at least with what I have thrown at them.

Where as the red ones I punch them a few times and there in bits.

I have shot the green ones,hit them and nothing

http://i61.tinypic.com/ekizw3.png

**Comment by BevapDin** [comment]
Has been fixed by #12006 (green pumps are diesel pumps).
