### ISSUE TITLE
Tile error (Mshock)

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#11942]
Hi all latest version b5bd1b2 
windows 7 64bit

Using any of the Mshock tile sets I get errors and it resorts back to ascii

Thanks all :)

**Comment by stk2008** [comment]
Ok fixed one error there was lots of ========= at line 14490

removed them and still got errors when loading save :(

**Comment by BevapDin** [comment]
> Using any of the Mshock tile sets I get errors and it resorts back to ascii

What errors? In order to help you, we have to know *what* error you get.

**Comment by stk2008** [comment]
hi thanks for replying

when i select mshock32 once i save from optoins menu i get this error

[IMG]http://i62.tinypic.com/34gae7d.png[/IMG]

i press space bar to clear error

once i start a game it complains about missing tiles i assume to do with error above?

**Comment by stk2008** [comment]
maybe i should put this in here copy/pasted from other post i did
-----------------------------------------------------------------------------------

Hi BeapDin sorry to be a pain mate i get no error now when actually selecting the Mshock32 tile set in optoins but when i load a world im still getting errors like this

http://i60.tinypic.com/ws4mlu.png

there are a few of them if i hit space bar to skip error game does start so not sure whats going on?.

Thanks matey :)
