### ISSUE TITLE
0.C [2970] Tailoring repairs extremely fast

### ISSUE THREAD

**Issue by nonymous** [CleverRaven/Cataclysm-DDA#11953]
I guess I never noticed this before, but tailoring repairs are extremely fast.  At level 7 tailoring, I can take any piece of clothing from tattered to full normal condition in about a minute and a half or 3 minutes if the initial roll fails to be high enough. Doesn't that seem ridiculously fast?
I have fixed a failing harness in mid combat. Late game, high skills, and against a low threat zed, but it still seems broken.

**Comment by Frost-wood** [comment]
Tailoring is pretty fast, probably should scale to skill.

**Comment by mugling** [comment]
Obsolete following complete overhaul of item repair mechanics
