### ISSUE TITLE
stronger characters have less chance of breaking glass with crowbar

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11963]
//chance of breaking the glass if pry attempt fails
            if (dice(4, difficulty) > dice(2, p->skillLevel("mechanics")) + dice(2, p->str_cur)) {

Higher mechanics skill makes you less likely to break the glass, which makes sense. It feels like higher strength should do the opposite, though. And maybe dexterity should play a role here?

**Comment by kevingranade** [comment]
More strength = more control when applying strength, this is working as
intended.

**Comment by sparr** [comment]
if that's true then that would seem to contradict elsewhere when throwing items and strength results in less control over direction

**Comment by kevingranade** [comment]
Higher strength should never make accuracy lower, if that's the case it's
the throwing code that's bugged.

**Comment by sparr** [comment]
Roger that. I'll find that code and double-check it.
