### ISSUE TITLE
much code duplication in construct::done_dig_stair, construct::done_mine_downstair, trapfunc::sinkhole

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11961]
The code for falling into water or lava, or saving yourself, is broadly duplicated in these three locations. Other failure modes are also duplicated.

**Comment by kevingranade** [comment]
Please don't file issues for this sort of thing, the issue tracker is
already so overloaded it's hard to find things.

**Comment by KA101** [comment]
The stair-construction code was a project of mine (with code-understanding help from Kevin) back when I had more energy than C++ know-how.  (Now I have marginally more know-how and less energy.)  I'm sure it could be done more effectively.
