### ISSUE TITLE
dex has virtually no effect on avoiding damage from sharp terrain

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11966]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/game.cpp#L12052

It looks like someone meant for dex to have an impact here, but by my reading it mostly doesn't. At dex=0, the relevant factor is !one_in(40), which is 39/40 or 97.5%. At dex=20, !one_in(30) is 96.67%. That <1% different on top of the other factors turns out to be about half a percent. So, 20 points of dex makes you 0.5% less likely to cut yourself on a broken window (etc).

Maybe there was an arithmetic mistake here? Or maybe I'm reading it wrong.

**Comment by i2amroy** [comment]
My guess is that they were originally looking for something more like this:
```c++
!x_in_y(1+dex_cur/2, 40)
```
That would mean that at DEX 20 you would only have a 72.5% chance of hurting yourself.

**Comment by KA101** [comment]
Seems high, in any event.  Betting armor kicks in after that and/or I'm more attentive to the "rake" portion of break&rake than most, as I've really not seen that much injury from moving through broken windows.

**Comment by sparr** [comment]
The % we've been talking about is just one factor in a larger equation.

        ... !one_in(3) && !one_in(40 - int(u.dex_cur / 2)) || one_in(4) ...

So, where we've been saying X%, it's really (75% * 67% * X%) + 25%.

And then, as you guessed, armor matters, on a random body part.

**Comment by sparr** [comment]
I'm gonna run with i2amroy's idea. Instead of Dex 0..20 making the odds change by 1% they will change by about 25%. That's still one of the least odds-chancing effects of a 20 stat I've seen.
