### ISSUE TITLE
Strength effect on environment effects is backwards?

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11960]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/creature.cpp#L804

    if (dice(strength, 3) > dice(get_env_resist(vector), 3)) {
        // resist fails

right side of the > makes sense, having higher environmental resistance on that body part makes you less likely to fail, more likely to resist.

left side of the > seems wrong to me. having higher strength should make you more resistant, not less

**Comment by vache** [comment]
That is how it works.  You're rolling a ````strength```` sided dice 3 times.  Higher strength = bigger dice.

**Comment by sparr** [comment]
Ahh, I feel dumb. I misinterpreted this as character strength, not field strength.
