### ISSUE TITLE
meth hunger penalty calculation is weird

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11962]
This calculation produces a rather strange curve, probably unintentionally:

        int hungerpen = (p->str_cur < 10 ? 20 : 40 - p->str_cur);

Here's what the penalty looks like at different strengths:

    str pen
      1  20
    ...
      9  20
     10  30
     11  29
     12  28
     13  27
     14  26
     15  25
     16  24
     17  23
     18  22
     19  21
     20  20
     21  19
    ...
     29  11
     30  10

Also, maybe this should be based on str_max, which represents character size, rather than str_cur which has all sorts of temporary modifiers?

**Comment by KA101** [comment]
Yeah, that curve does look Weird.  Body size seems accurate in this case, but then I'm not one of the drug people.

**Comment by Rivet-the-Zombie** [comment]
That's some seriously odd math right there.

>maybe this should be based on str_max, which represents character size

Yeah; generally speaking, the bigger you are, the more of a drug it's gonna take to achieve the same effect.
