### ISSUE TITLE
recoil recovery barely affected by str and gun skill

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11965]
npc::move_to, npc::move_pause, game::plmove, and player::pause all reduce the character's recoil value by about half, down to MIN_RECOIL, with a small bonus for high strength and high gun skill.

That bonus is vanishingly small and doesn't seem effective. Starting at 1000 recoil, a character with 0 strength and 0 gun skill recovers to 500 recoil. A character with 20 strength and 10 gun skill recovers to 490 recoil. The number of turns it takes them to get down to MIN_RECOIL is going to be the same in the vast majority of cases, even with maxed stats and skills.

Perhaps this was an accident, or something was overlooked at some point in the past when an extra zero was added to the recoil values?
##

**Comment by kevingranade** [comment]
Yes, missed this when scaling dispersion from quarter-degrees to minutes of
arc, the scaling factor is x20.

**Comment by sparr** [comment]
Might that be x15?

**Comment by KA101** [comment]
15 is the number used in other scaling, IIRC.

**Comment by aierce** [comment]
is this patched already? (a quick look in game.cpp etc doesn't seems to be so).

Using a weapon with 585 recoil in game, 10 str 0 skills. Waiting 2 round is able recover full steadiness.

**Comment by sparr** [comment]
@kevingranade can you elaborate on the dispersion scaling? Are you saying the reduction of recoil based on str and gun skill should happen 15x as fast, or that guns should be setting their recoil values 15x as high, or that MIN_RECOIL should be 1/15th what it is, or something else?

**Comment by mugling** [comment]
Complete rewrite since this was opened
