### ISSUE TITLE
npc::player_danger uses str_cur once, str_max many times

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11964]
It seems like this is one of many places where str_max is used to represent the size of the player, and thus how intimidating they are in this context. However, one of the five checks uses str_cur instead, which seems out of place.

**Comment by KA101** [comment]
Without seeing the code in question, is it possible that it's looking for visibly-weakened PCs?

**Comment by sparr** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/npc.cpp#L1268-L1277

**Comment by KA101** [comment]
OK, yeah, that's based on the idea that folks *won't* have base ST over 20.  Nowadays, that's not a given (BUFFS!!!), but in practice it's designed to let folks hopped up on augs/drugs/hydraulics get an additional intimidation bonus.

This isn't a bug.  Thanks for checking.
