### ISSUE TITLE
Throwing deviation calculation has item weight and strength stat reversed for NPCs, also NPC-vs-player deviation calculation don't match up otherwise

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11974]
NPC: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/npcmove.cpp#L888
Player: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/ranged.cpp#L621

higher strength leads to higher deviation
higher item weight leads to lower deviation

This is probably wrong/backwards, partially per @kevingranade in #11963 

For context, deviation increases with hand/eye encumbrance, decreases with perception and throwing skill.

PS: perhaps these two locations could be consolidated into a function?
##

**Comment by sparr** [comment]
player ranged bug fixed in 2a9e6c4
NPC bug persists, and NPC and player deviation calculation have gotten even further out of sync.

Reiterate that consolidation into a function for both NPCs and Players (possibly as part of Character?) may be a good solution.

Paging @Coolthulhu for insight into improvements made to the player deviation code that could be used to extract this to a function and fix the npc deviation code.

**Comment by kevingranade** [comment]
This *was* pushed up into character at some point.
