### ISSUE TITLE
Using a winch lets the door open (and Zed in) far before you're "finished" using it.

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#11975]
Try opening a garage with a few outside. You're suddenly surrounded. Feels similar to my old one about how turrets shoot you by the time you're done using a jackhammer to reveal them.
##

**Comment by sparr** [comment]
Very similar. This is a moves-costing action, rather than a long interruptable activity. Same sort of solution as the turret problem.

**Comment by KA101** [comment]
Hmm.  Thinking about it, I can get under my garage door well before it's finished opening.  I'd imagine that zeds could do the same.  Not sure this should qualify as a bug.

**Comment by sparr** [comment]
@KA101 the bug isn't that they get in at all. It's that you're stuck glued to the chain for multiple turns after they get in. This should be an interruptable activity, so you can stop when a zombie gets under the door.

**Comment by KA101** [comment]
Wev.

**Comment by Headjack** [comment]
If it could just wait to happen until your moves are all spent that'd probably be good enough.

**Comment by sparr** [comment]
There are two basic paradigms for getting things done:

Actions(?) do something immediately then reduce the player's moves, and the player doesn't get to act again untl they make up the moves deficit. All monster actions happen after the player action has already been fully processed.

Activities queue something to be done, then the player uses moves in one-turn(?) chunks until they finish or get interrupted, while monsters get to keep acting along the way.

There isn't a middle ground.

**Comment by Leland** [comment]
I think this can be closed since #13466 was merged
