### ISSUE TITLE
liblua5.2.so.0 unnoticed by program

### ISSUE THREAD

**Issue by tsuma534** [CleverRaven/Cataclysm-DDA#11971]
When trying to launch Cataclysm I get the following message:
```
error while loading shared libraries: liblua5.2.so.0: cannot open shared object file: No such file or directory
```
Cataclysm version: 0.C
OS: Ubuntu 12.04
I had liblua5.2 installed, yet I removed it and installed again. The error remained after that.
Followink the hint from [this post](http://smf.cataclysmdda.com/index.php?topic=8571.msg197356#msg197356) I have found a liblua5.2 that is fit for my architecture ([supposedly](https://packages.debian.org/sid/liblua5.2-0)), but nothing changed after yet another reinstallation.

I am going to try out each version of liblua5.2 I find, but maybe someone has a better suggestion.

I can provide exact build versions, etc., once I get home.

**Comment by kevingranade** [comment]
Most likely you don't have a 32-bit build of liblua.

**Comment by narc0tiq** [comment]
Assuming you have multiarch set up (and further assuming you have a 64-bit
machine, which is a fairly safe bet), you probably want the package
liblua5.2:i386.

**Comment by tsuma534** [comment]
> Assuming you have multiarch set up (and further assuming you have a 64-bit
machine, which is a fairly safe bet), you probably want the package
liblua5.2:i386.

That apparently solved the problem, thank you. However, now I have a new error:
```
/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./cataclysm)
```
It appears that it's the same issue as [described here](https://github.com/jasonsanjose/brackets-sass/issues/53).
I have tried to install libstdc++6-4.7-dev as one of the commenters suggested, but it depends on some libraries that, according to aptitude, can't be installed.

I have some errands for now, I'll try to delve into it later.
Also, should I change the Issue name to "Missing libraries" or open a new one?

**Comment by narc0tiq** [comment]
As far as I can tell, Ubuntu 12.04 is stuck with libstdc++6 v4.6. To be
honest, it may be easier to just compile your own copy of Cataclysm with
native packages for your platform. Except I don't think g++-4.6 is even
going to recognize the existence of --std=c++11, so you'd need something
like
http://ubuntuhandbook.org/index.php/2013/08/install-gcc-4-8-via-ppa-in-ubuntu-12-04-13-04/

Libraries that can't be installed according to aptitude? Maybe it's just a
matter of enabling the 'universe' and/or 'multiverse' packages. Equally,
there may be a PPA with all the stuff backported to Ubuntu Precise.

Change the issue name, this is the same problem that's just evolved a bit
further (the issue being "Can't run Cataclysm 0.C on Ubuntu 12.04 64-bit").

**Comment by mugling** [comment]
This appears to be an issue with package management on Ubuntu which is beyond the project scope and also likely resolved given the age of the issue. @tsuma534 please feel free to re-open if you are continuing to have problems

**Comment by tsuma534** [comment]
Thank you @mugling for cleaning this up. I do have problems, but I think I just need to educate more about linux.
