### ISSUE TITLE
Fingerpick costs no energy

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#11980]
The description indicates it's supposed to cost 25, though it probably should be free considering all it saves you is 1.2 lbs for a picklock kit.

**Comment by KA101** [comment]
Except it should have a 100% success rate, whereas the kit doesn't always work and can be damaged at low skill.

**Comment by ejseto** [comment]
The kit also doesn't have a chance of saddling you with negative bionics when you fail your install.

**Comment by KA101** [comment]
Risk of any aug.  This remains a bug.

**Comment by ejseto** [comment]
Clearly it's a bug one way or the other, since the interface contradicts what actually happens.
