### ISSUE TITLE
Exiting game at tomb stone prompt, brings back the ghost of past and future!

### ISSUE THREAD

**Issue by FireCrow1973** [CleverRaven/Cataclysm-DDA#11986]
well i had a nice save, with a nice cop car and some nice stash in the trunk.
Having discovered a nice fueling station i decided to fill'er up as they say.
I gently crashed my car in the side of the building, because i'm an idiot like that!
Fueling station and car immediately exploded in a impressive sea of raging fire.
Not surprisingly i died horribly.

The tomb stone prompt came opp, i decided to just exit and re enter the game.
That would mean my save and world would not be destroyed.

I wake opp in my nice bed and everything is fine.
I got in a car and drove back to the fueling station.
Only to discover a burning fueling station and the wreckage of my nice cop car.

Everything stays as it was when you die...except you!
I kept doing this six more times, and eventually started to get some debug messages.
(but it still loaded) 
This works at the tomb stone prompt, the "history" list and the kill count.
I'm on v.2951

**Comment by i2amroy** [comment]
Yeah, it's a side effect of you purposely breaking the game. :P
