### ISSUE TITLE
Smoker zombies see through smoke.

### ISSUE THREAD

**Issue by xyder** [CleverRaven/Cataclysm-DDA#11995]
During the day they can spot the player from a range of 50+.
##

**Comment by facepalm** [comment]
They'd be pretty harmless if they couldn't, don't you think?

**Comment by xyder** [comment]
They're still pretty harmless, the smoke is what would get me. Without a filter mask or a gas mask the smoke easily gets about 30 hp before either dying or loosing the effect.
I couldn't test if other monsters were just as unaffected by the smoke because this time there was just this smoker, but if they aren't, I imagine a zombie hulk hiding in the smoke would be quite an interesting encounter.

**Comment by Rivet-the-Zombie** [comment]
Smoker zeds are primarily attracted to noises, since they can't see out of their smoke cloud all the time. When it clears enough for them to actually see a target, it's usually only for a turn or two, leading them to run to wherever they last saw it. This causes them to move about in  a rather erratic fashion that can be hard to predict.

I like the way they work now, and see no need to change it.

**Comment by xyder** [comment]
While i do enjoy the extra challenge, they didn't seem that erratic to me. It saw me and followed me without a hint of hindrance, adjusting it's path as it came.
For a kind of zombie that should have its vision impaired it seems to do better than most other monsters in that department. I can even single them out based on this alone, as most other zombies have a vision of 30-45 or so.
I'm not saying they don't have an interesting mechanism to them or that they should be changed, but it appeared to me that maybe they're not working as intended.

**Comment by Rivet-the-Zombie** [comment]
So perhaps they need their vision range adjusted down to normal zombie level?

**Comment by Zireael07** [comment]
+1 to adjusting their vision down.

**Comment by xyder** [comment]
Well as you said, the idea of it erratically follow the player is indeed appealing so maybe the the time between when it can see the player could be tweaked. I'm getting the impression that the smoke doesn't block its vision at all.
Also I managed to alert it at a new max range of 58 now, quite a bit over the 50 it should have, if I read the json correctly.

**Comment by Coolthulhu** [comment]
Visibility through smoke will soon be changed.

Current visibility works like that:
* Each tile has a opaqueness value. Empty air has 0
* If sum of opaqueness values on a path from `p1` to `p2` is 1 or more, you can't see `p2` from `p1`
* If that sum is lower, the range is unaffected
So if you can see through smoke, you can see 60 tiles through, but if that smoke density is just a tiny bit higher, you can't see at all.

New visibility (the way I understand it):
* Range variable doesn't exist
* Each tile - including empty air - has some opaqueness value
* Seeing through dense smoke will cut your visibility in that direction like seeing through many empty air tiles

So nerfing smokers right now may make them a bit blind, as their new sight ranges will probably be much shorter than now.

**Comment by KA101** [comment]
Smokers were more or less blind originally and I didn't have a problem with that.  Folks who want to reduce their vision, feel free.

**Comment by chaosvolt** [comment]
At present I haven't found them to be a severe hassle. I would be in favor of vision reductions if the coughing wasn't the only threat they've given most characters. At least, the times I keep default zeds on. =w=

**Comment by CIB** [comment]
The smoke also obscures the player's view, which can be a hazard while driving. I think there's nothing wrong with them being mostly a problem to people without smoke protection, but that might be because I don't run around with a gas mask 24/7 for roleplay reasons.

**Comment by kevingranade** [comment]
Issue as stated doesn't happen, and snokers are generally working as intended.
