### ISSUE TITLE
[0.C 2982] Advanced Inventory crash when moving items

### ISSUE THREAD

**Issue by Celethang** [CleverRaven/Cataclysm-DDA#11996]
I backtracked through the builds, and this started happening in 2982, up to 2985 (the current version at this time)

The first issue is when you use the advanced inventory management to either A) move any stacking item (batteries, wire, etc.) to another square, or B) move ANY item, stacking or not, from your inventory to the ground. If it's a stacking item, it will auto-input the number for all but ONE of the item in the quantity window, and if you finish the move, they'll move just fine, but the one will obviously be left behind.

The second issue is when you try to move that last item, OR when you try to move any single-stack item out of your inventory. At this point, the quantity window pops up, auto-fills in a 0, and obviously won't move the item after finishing. And if you try to change the 0 to a 1 and make the move, the game crashes with this message:

Assertion failed!
Program: C:\Cataclysm DDA\cataclysmdda\cataclysm-tiles.exe
File: src/advanced_inv.cpp, Line 1381

Expression: amount_to_move > 0

Abort closes the game, retry comes up with a runtime crash, and ignore goes back to the game, with the item unmoved.

Doesn't really make a lot of sense, because there wasn't even anything changed in advanced_inv.cpp in 2982 as far as I can tell XD

(this is my first time making a post here, let me know if you need any more info or if I need to explain it better :D)

**Comment by DavidKeaton** [comment]
I think this might be enough, I have been doing changes in that area (and am responsible for the amount - 1 change to that prompt). I'll take a look at it mate!
