### ISSUE TITLE
Using comestibles in action menu consumes no charges.

### ISSUE THREAD

**Issue by DavidKeaton** [CleverRaven/Cataclysm-DDA#11997]
1. Open the context sensitive action menu.
2. Eat vitamins
3. Do so forever
4. ????
5. Profit

I don't mind fixing, but wanted to post it for the sake of making it known.

**Comment by Rivet-the-Zombie** [comment]
The vitamin on the edge of forever.

**Comment by DavidKeaton** [comment]
There Bayer be a good way to fix this bug, or at least get some devs together and Centrum on this problem.

**Comment by Coolthulhu** [comment]
I was pretty sure I fixed this bug with the eat off the ground thing...

**Comment by DavidKeaton** [comment]
If you did, then I may have not updated as recently as I did. Will confirm.
