### ISSUE TITLE
Advanced INV manager eating items

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#12016]
Win 7 64bit
cata version 24fe0e0 64 bit

Hi all I have an issue

I had a boot full of stuff and I wanted to transfer items from one car to another so used the ADV inventory manager.

Well I was messing about trying to figure it all out using D,V etc but realised all my stuff had gone.

I exited ADV INV manager and looked on the car tile I had all my gear and nothing was there it vanished :(.

No I can promise it was ADV inventory manager but my items where gone I did nothing so its either.

Advanced inventory manager
Auto save

or some other wierd bug :(

**Comment by DavidKeaton** [comment]
This one is my bad @stk2008, sorry about your items :(

**Comment by stk2008** [comment]
TBH mate I really cant explain what I did all I know was the car was full of goodies :) and I was trying to transfer them to another car but I was unsure how to use the AIM menu so had a bit of a play till i got it right but I then noticed all my gear was gone.

I will be honest I cant say 100% that AIM is to blame but I have no idea what else it could be.

My brother also had a shit load of Kevla go missing to from a crate so maybe its now AIM it is a save iss or some thing?.

Any ways dont appologise mate I appriciate your work and every thing every one does for CDDA :)

**Comment by DavidKeaton** [comment]
It's probably an AIM issues, as I have fixed a few bugs here and there. I will take the blame on all that. Thanks for your kind words though. :-)
