### ISSUE TITLE
Headgear with encumbrance > 20 is unwearable

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#12010]
I've tried putting on a great helm (enc 40) and it says "You can't wear a helmet!"

Problem appears to be in this line https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/player.cpp#L10218 : it forbids wearing any headwear with enc > 20.

**Comment by i2amroy** [comment]
Pretty sure it should be > 200, but there are a couple of different ways the problem could be resolved there.

**Comment by KA101** [comment]
OK, yeah, you should be able to wear one headgear no matter its encumbrance (HUGE, etc notwithstanding).  Looks like that check should ask whether you're wearing_something_on your head already, and only run if you are.

**Comment by i2amroy** [comment]
I think we need a little more than just a disable if you aren't wearing anything. In that case if I put on a skintight cap and then tried to put my great helm over it I'd still get locked down and prevented from wearing it. Originally what it did is check if you didn't have any current head encumbrance, and then check the encumbrance of the new item.

@DavidKeaton can we get your opinion on what exactly you were trying to do when you changed this?

**Comment by KA101** [comment]
I'm thinking that the line was written to deal with folks who insist on Layering All The Crap and didn't want to bother putting the crap that layers easily on first.  However, it's also vulnerable to this sort of problem.

Better check might be if (current head encumb < 10) OR (to_wear_encumb < 10 AND it fits), I'm thinking.

**Comment by DavidKeaton** [comment]
@i2amroy I neglected to think about having no items on the head, so this was def my b.
