### ISSUE TITLE
Proposal: Use doxygen to document effects of/on stats and skills

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#12013]
I recently created these wiki pages:

http://www.wiki.cataclysmdda.com/index.php?title=Detailed_Strength_Effects
http://www.wiki.cataclysmdda.com/index.php?title=Detailed_Dexterity_Effects
http://www.wiki.cataclysmdda.com/index.php?title=Detailed_Perception_Effects
http://www.wiki.cataclysmdda.com/index.php?title=Detailed_Intelligence_Effects

I'd like to automate that process in the future. I would also like similar documentation in reverse, for things that affect your stats. And ditto (in both directions) for skills.

I think this could be accomplished with [Doxygen's \xrefitem command](http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdxrefitem). It would look something like this:

    ///\xrefitem Dexterity "Combat" "" { Dexterity > 8 reduces melee combat move cost }
    int dexbonus = (int)( std::pow(std::max(u.dex_cur - 8, 0), 0.8) * 3 );
    move_cost -= dexbonus;

This will result in there being a Doxygen page titled "Dexterity" with a section (among others) titled "Combat" containing a bullet point "Dexterity > 8 reduces melee combat move cost".

Would this sort of thing be welcome? If so, it will add a step to official builds, because the doxygen docs will need to be updated at compile time. Updating the wiki could be done manually, possibly only at major releases.

If welcome, is the structure I laid out above appropriate? Maybe we just have one page called Stats, with a section for Dexterity, and no further subdivision? How should we differentiate between things that are affected by dex and things that change your dex?

**Comment by KA101** [comment]
Pretty sure we've got doxygen integrated already, and more of it is generally appreciated.  I've no objection to what I see here.

**Comment by sparr** [comment]
I see a tiny bit of doxygen commenting in a few places, and a substantial chunk in the weather code, but it doesn't look like anyone has been maintaining the doxyfile_doc configuration lately. I'll throw something together to add functionality like I've described here (or as near as I can make actually work) and put it in a PR and see how that goes over.

**Comment by narc0tiq** [comment]
Yes, please, more doxygen!

One of Jenkins' on-push builds is a doxygen deployment to
http://dev.narc.ro/cataclysm/doxygen/ -- I would __love__ it if that were
more useful. Semi-relatedly, I'd be okay with mentioning that deployed
variant in README.md, if people thought it was good enough.

**Comment by kevingranade** [comment]
No objection here.

**Comment by sparr** [comment]
Please move further comment to #12021
