### ISSUE TITLE
Butcher attempts misuse integer division when calculating success

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#12020]
https://github.com/CleverRaven/Cataclysm-DDA/blob/152deb5010329270fe9a1a64fbaae7f811c82832/src/activity_handlers.cpp#L148-L153

rng() returns a long (integer), so the division is integer division. At no point here does skill_shift contain a non-integer value. I take the double type of skill_shift to indicate that this was meant to increment/decrement in fractions.

**Comment by facepalm** [comment]
>I take the double type of skill_shift to indicate that this was meant to increment/decrement in fractions.

Maybe it was meant to originally, but there aren't enough fractions to make much difference.  The only time the result would ever differ from int division is if you have poor (< 4) strength and a poor (< 0) butchering tool, and roll -0.5 twice.

**Comment by sparr** [comment]
I suspect the `skill_shift -= rng( 0, -factor / 5 );` a few lines below was also meant to have some non-integer effect. This would also be cummulative with the dex-based shift, and the low str shift.

**Comment by facepalm** [comment]
That's the butchering tool roll.  The dex-based shift is positive-only, and would act to reduce the potential for fractions to matter, since the rest are negative-only.

**Comment by sparr** [comment]
Right. A dex of 9-11 should sometimes/randomly offset a strength of 1-3.

**Comment by BevapDin** [comment]
> At no point here does skill_shift contain a non-integer value. 

Btw. that `skill_shift` variable (including its type `double`) comes straight from the initial commit 69ffbb2953c1e92a9b24d5380dabe7f26066223e and even there it did never contain any non-interger value. Maybe it was never intended to contain non-integers but everybody just left it as it was.

**Comment by sparr** [comment]
This was fixed at some point, all of the rng have become rng_float and all of the division is now float division.
