### ISSUE TITLE
Gun Skills Not Improving

### ISSUE THREAD

**Issue by DeNarr** [CleverRaven/Cataclysm-DDA#12022]
So I've never been much of a fan of ranged weapons in this game in general, as they've always seemed exceptionally weak compared to melee, but it appears that they also aren't even increasing in skill properly.

Test Case: I started out with a Swat Officer with 12 Dex and 12 Per (the point where neither gives a penalty to range), and no additional points allocated to skills (so the base of 3 marksman, handgun, and sub machine gun). I then loaded up my starting H&K, walked outside, and got a quest to kill the Jabberwalky (I have 100 focus at this point). After completely emptying a clip of 30, and going through half of the next clip, I manage to kill it (though only barely before it kills me), meanwhile neither my Marksman nor Submachine Gun skill raised by a single percent. I cannot imagine that this is intentional.

**Comment by ejseto** [comment]
I think there was a change where previously only your gun's dispersion had to be low, but now it includes the ammo dispersion as well which basically means all SMGs will never increase skill since they use terrible pistol ammo.

**Comment by facepalm** [comment]
The H&K MP5 is [explicitly mentioned](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/ranged.cpp#L36) in ranged_skill_offset as being a good submachine gun for training to max skill, however the calculations also assume the player has installed every possible gun mod that reduces dispersion.  It just needs to be rebalanced for unmodified weapons.

**Comment by DeNarr** [comment]
I'd just like to point out that this isn't off just by a little either. The training is supposed to be balanced around a Perception 8 character. My test character had perception 12 (even tested a second time with 14 per), and still could not train smg or marksman above 3. Some of those later mods require a high marksman to even install. So what, he is supposed to train with a rifle, to get better at being a marksman, just so he can mod a smg to finally get better at using a smg?

**Comment by ejseto** [comment]
Your gun can have 0 dispersion and it doesn't matter because even 9mm +P+ still has a dispersion of 120. The "gun" might be good for training but the ammo sure isn't.

**Comment by illi-kun** [comment]
Ranged weapons were rebalanced recently. Feel free to reopen this ticket if it's still an issue.
