### ISSUE TITLE
Advanced inventory - "move item stack" action does not work all the time

### ISSUE THREAD

**Issue by xyder** [CleverRaven/Cataclysm-DDA#12048]
From what I could test, it appears that it only works when the source pane is set to Inventory. I tested it with source and destination being set to Inventory, All, a direction, Grabbed Vehicle and Vehicle, both with the item type already existing in the destination pane and without.
In all cases it only worked when the source was from the Inventory.
Latest build tested was 3010.

**Comment by graysage1** [comment]
Yea, it appears 'm' and 'M' buttons don't do anything meaningful in many cases where you'd expect they would.

'm' should always move just one item, and 'M' should always move the whole stack.  There should never be any special exceptions.

**Comment by mugling** [comment]
Closed as unconfirmed
