### ISSUE TITLE
Fish go extinct quickly

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#12067]
So, I settle down near a bit of river near two different tiles where fish are jumping. fishing works fine for a bit, later on there are no jumper mobs since zeds have waded in and killed them all. Fishing still works fora while, but soon enough both of the spots go empty and I can't fish anymore. I remember that the mechanics changed in some way, but a number of reasons make this pretty disappointing.

For one, the whole river should be viable for fishing at some level. It's reasonable some spots are better, but not that making a catch is impossible elsewhere. Maybe you would need some bait on your rod to make it work there rather than a hotspot? Two, it's weird that the fish die out so quickly. I don't know what numbers change to cause that, but neither zeds scaring them off nor one man's impact on the environment should drive fish away so fast. If what a hotspot represents is some area that attracts fish, they'd keep coming back. Third, it's pretty disheartening to build a cabin by the river only to find it no longer a viable living situation. When you've got the enemies numbers jacked up and are Frail, having the chance to survive in one location is important.
##

**Comment by ejseto** [comment]
Pretty sure fishing kills the fish in the river and deposits their corpses next to you. No fish in the river means you won't catch anything, although I think there's always a very small chance of catching something regardless. It's silly that swimming Z's can kill fish though, fish should have a huge bonus to speed/dodge or something to protect them from people/Z's just wading in and slapping them to death.

**Comment by Coolthulhu** [comment]
Number of fish in a river tile is heavily limited. Current spawning system doesn't let anything except zed hordes migrate.

When something kills the fish, it's usually a zombified shark. Those are aggressive and have enough speed to catch up with fish. Regular swimmer zeds are too slow, all other zeds are nearly blind under water.

**Comment by graysage1** [comment]
I think fish should not be limited.  They should be infinite, essentially.  The only way to deplete the fish completely IRL is to overfish consistently for years.  A lone raider with a fishing rod has zero percent chance of overfishing a river.

**Comment by Zireael07** [comment]
+1 to fish being infinite (I used to fish IRL with my dad)

**Comment by Rivet-the-Zombie** [comment]
>fish being infinite

This is good. It's not a perfect solution, but it's a highly viable one. Plus if the fish only respawn when you leave an area it would simulate the way they can get disturbed by fishing in one spot all day and return after the disturbance ceases.

**Comment by i2amroy** [comment]
Personally I think the best way to go about this would be to have a timer that automatically adds new fish to the population (maybe make it seasonally based as well? so you would get less fish in the winter than say the summer). That would make it so that they were effectively infinite, but the answer to "I ran out of fish in my river" doesn't become "walk away and then walk back".

**Comment by Rivet-the-Zombie** [comment]
>That would make it so that they were effectively infinite, but the answer to "I ran out of fish in my river" doesn't become "walk away and then walk back".

I was thinking more of 'walk down the river a maptile or two' like you might do IRL, but that's a good point.

**Comment by Tharn** [comment]
Guess I'll necro this. Fishing parts of a river to death is still an issue, and it doesn't take long to do it either. When you think about it.. without human facilities running, rivers should rid themselves of waste and pollution within weeks if not days. That some get eaten shouldn't impact fish population as much as a healthy river does.

**Comment by DChieh1** [comment]
I'll necro this as well. Fish go extinct remarkably quickly - annoyingly so.
