### ISSUE TITLE
Music stores oddly common (ver 2547821)

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#12066]
I'm in a middle-sized town and there are six music stores. For comparison, there are three gas stations. They should probably be as common as banks or museums, both because they are of limited in-game utility and are a specialty service pre-apocalypse.

**Comment by Rivet-the-Zombie** [comment]
Fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/12068.
