### ISSUE TITLE
Deconstructing domestic windows does not yield long strings

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#12071]
While breaking them does.
##

**Comment by tvm1** [comment]
This seems to be more fundamental issue.

I've tried smashing domestic_windows and noticed that smashing is terribly consistent. It will get you 3x glass shard, 2x sheet, 1x heavy stick and long string **100% time**.

On other hand, deconstruction actually employs rng(). The long string might be present, if you are lucky enough. Deconstruction also yields nails (while smashing doesn't).

**Comment by Oskar636** [comment]
What do you guys think about this? Should windows drop a long string 100% of the time when deconstructed or not? 
BTW other windows ( household windows without curtains, shop windows ) drop items as expected when deconstruced - a sheet of glass. 
Build 5892 windows 64bit console

**Comment by Night-Pryanik** [comment]
I think that bashing should use rng too. 
Not a bug, in my opinion.
