### ISSUE TITLE
Axes and crowbars should be sheath-able or attach-able to a belt or strap

### ISSUE THREAD

**Issue by xyder** [CleverRaven/Cataclysm-DDA#12089]
In real life one would be able to attach axes and hatchets to a waist belt or a harness of sorts on the back. Crowbars and baseball bats should be sheath-able as well.

**Comment by drbig** [comment]
Given guns can now have straps attached I'd guess the code for handling that is in.

**Comment by kevingranade** [comment]
Yes, this should be a very easy change now, just replicate a holster but
only allow it to hold items it makes sense to put in a belt loop.

**Comment by mugling** [comment]
The firefighter belt seems like an obvious candidate for this considering the item description

How about an implementation providing the action BELT_LOOP with properties max_volume and max_weight and then the flag BELT_CLIP for items which should be attachable?

Should provide some flexibility for adding belt loops (of varying strength) to different clothing items?

**Comment by mugling** [comment]
This functionality was added in #13683 and the issue can now be closed
