### ISSUE TITLE
Unified Attack Menu

### ISSUE THREAD

**Issue by Frost-wood** [CleverRaven/Cataclysm-DDA#12090]
Per https://github.com/CleverRaven/Cataclysm-DDA/pull/11665, the argument against adding reach weapons was that it would complicate things.

I believe that merging the various attack actions into one key would be beneficial.  Based upon what you are using, the game would show the appropriate menu depending on what you are wielding(just like it does with items).  If you have a gun it will show the fire menu, if you have a weapon with long reach, then it will show that menu.  If you are just using your fists, perhaps there could be a menu to select the technique that you are going to use.  A hand-to-hand weapon could just show the fire menu with range 1 as you can still just walk into someone to attack them.

This would have the benefit of freeing up some keys, and keeping things in one location so the player has less to learn.

**Comment by kevingranade** [comment]
As far as I can tell the (F)ire menu already does this, and is what was
proposed except it doesn't support attacking an adjacent target with a
melee weapon.  That distinction is irrelevant since moving in the direction
of an adjacent enemy is strictly easier than using a menu.
My objection to reach weapons is the multiple keypresses required to
trigger an attack with one, which is unavoidable with ranged weapons but
not with melee.  I'm still not saying it's out of the question, I simply
haven't had time to mess with Coolthulu's PR that adds reach weapons and
see how it plays.

**Comment by narc0tiq** [comment]
> moving in the direction of an adjacent enemy is strictly easier than
using a menu

While this is true, I would still find the feature useful for attacking
repeatedly without accidentally moving (holding [f], rather than a
direction key).

**Comment by graysage1** [comment]
> the argument against adding reach weapons

There is already a reach weapon in the game.  I apologize if this was already mentioned.  It's called [bullwhip](http://cdda-trunk.estilofusion.com/bullwhip).  Maybe it's not up to your standard of elegance, I don't know, but bullwhip works fine to my own tastes, and it's a reach weapon that's already in the game.  So this isn't theoretical or speculative.  A reach weapon is already in the game and it doesn't complicate anything I can currently imagine.

**Comment by kevingranade** [comment]
When the bullwhip was added, it was added specifically as a one-off
exception, it has no bearing on whether other reach weapons are added.

**Comment by Cat09** [comment]
as in https://github.com/CleverRaven/Cataclysm-DDA/pull/11665, the tricky considerations are, what qualifies as a reach weapon? and How much virtualization are we already assuming in the current system?
to clarify, when you attack, how long does it take? are we assuming foot movement, and if so how much? what does a dodge look like, as you move 0 squares to do it?
gets kinda philosophical.

**Comment by Cat09** [comment]
I'm assuming that the UI question was resolved since Kevin merged Coolthulu's PR

**Comment by Coolthulhu** [comment]
> what qualifies as a reach weapon?

A weapon that has a reach attack tag.
The problem here is that weapon can be all 3 of: firearm, melee weapon, reach weapon. Unified menu would have to handle those too.

**Comment by kevingranade** [comment]
F currently does nothing if you're not wielding a ranged weapon, so making
it also handle targeting an enemy in melee range seems reasonable.

**Comment by Cat09** [comment]
:Facepalm:
I was talking about what really should, where said line should be drawn.
