### ISSUE TITLE
Jetbrains' Clion Open-Source License

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#12098]
So, I contacted Jetbrains a few days ago regarding their open source license program and got a reply today. Cataclysm does qualify for their open source program, however, because of the number of contributers they would need a member of the core team to submit the request. 

> I’m writing in regards to your request for free license.
> 
> We have been looking at your Open Source project and have come to the >conclusion that it qualifies for a free OS license.
> 
> However, since the license is given for the whole project, not just one committer, and yours is a very large project with lots of contributors, it'd be best if a member of the core team / author of this project could send the request for CLion.
> Please, pass this information and I'll happily issue a free OS license for your project.

I've been playing around with CLion, trying to get CDDA building under CLion and would really like if you would consider putting in the request for the license. I'm a frequent user of many of Jetbrains' other products and would back their products against any other on the market (free or paid). The biggest reason I recommend CLion is the fact that it is a cross-platform product and can be used by Windows, Linux and Mac users alike.

If there are worries about maintaining 'yet another project format', I would like to hopefully dispel those now. CLion uses CMake as it's project format, and there has been some work done recently to update our own cmake file(s).

If you're interested in giving this a try, check them out: https://www.jetbrains.com/clion/
##

**Comment by narc0tiq** [comment]
> CLion [...] is a cross-platform product and can be used by Windows, Linux
and Mac users alike.

I rather like that. We could even make it the officially-supported IDE
instead of (aging, creaky) Code::Blocks. @kevingranade?

**Comment by KrazyTheFox** [comment]
I would love to see this happen as well. I absolutely love IntelliJ and I'm sure CLion is of the same quality (or close to).

**Comment by kevingranade** [comment]
I'll take a look at it when I get home, would this mean I'd be handing out
licenses to developers to register/unlock/download a full version?
Probably I just need to read their page on the subject.

**Comment by Rivet-the-Zombie** [comment]
Do we really want to go with something that's going to add extra steps, and make it even harder for first-time contributors to work on the project? C::B is so easy to operate that just about anyone can use it 'right out of the box', it requires no licensing, and it even runs on super old hardware.

**Comment by macrosblackd** [comment]
except, quite frankly, it's and eyesore to use, lacks many features
inherent in modern IDE's, and requires more than simply installing it
and off you go. Because of our lack of dependency bundling or similar
functionality, no solution, currently, works 'right out of the box'.

**Comment by i2amroy** [comment]
To be honest I'd like this too. I use IntelliJ (which is made by the same people) for all my Java stuff and this is almost identical except for C/C++. In addition it could possibly allow me to start compiling up some common Mac versions as well without needing someone else to build them, (depending on a few other factors of course, but it's certainly a possibility).

**Comment by macrosblackd** [comment]
@kevingranade : In regards to the licensing, it looks like it is a single, multi-use key that you, or one of the other core members would be able to hand out on a per request basis.

**Comment by macrosblackd** [comment]
Also, for those of you who swear by vim... there is already a vim plugin that gives you similar functionality (I'm assuming this is the case, I've never used vim longer than a few minutes until installing something like nano)

**Comment by KrazyTheFox** [comment]
> Because of our lack of dependency bundling or similar
functionality, no solution, currently, works 'right out of the box'.

This is a major hurdle to get over, especially for people unfamiliar with C++, such as myself. Even with C::B, it took several hours for me to figure out how to get a build running in Windows. Linux didn't fare too much better, at nearly an hour. I think this would be far more problematic for first time contributors than getting used to a different IDE/getting licensing for it.

>C::B is so easy to operate that just about anyone can use it 'right out of the box'

As a counter-point, see above. IntelliJ has around the same learning curve as C::B if you ignore the dependencies/licensing, and, again, I imagine CLion would be similar in function to IntelliJ.

>it requires no licensing

I can't really comment on the feasibility one way or another on this one, though it certainly could be problematic if no other IDEs are officially supported.

As far as personal preference goes, I prefer to use a text editor over C::B due to the many more features I get in, say, Sublime Text.

**Comment by sparr** [comment]
Just in case anyone here isn't aware, some of us don't use C::B or IntelliJ or anything else like that. I check out the repo and type 'make'.

**Comment by macrosblackd** [comment]
It's great that you can get make working!

Some of us are running windows environments and the general consensus
has always been, "pfft, noob, just crosscompile from 'nix".

I personally don't want to be required to have a completely separate
environment just to contribute to CDDA. If I wanted to develop on
'nix, I would just develop and play cdda on nix.

**Comment by sparr** [comment]
Why doesn't make work in your windows environment? Maybe that's the problem we should be addressing...

**Comment by macrosblackd** [comment]
I've been able to get make working before, however, I don't want to
put in 12+ hours of effort just to build. Windows support for c++/sdl
development is severely lacking, it's not an issue specific to CDDA.

**Comment by kevingranade** [comment]
There's no dilemma here, I'm totally fine to *add* CLion support, but C::B
support isn't going away unless there's no one left to keep it working, and
I'm rather skeptical of that being a problem.

**Comment by Frost-wood** [comment]
Looks interesting.  How easy is it get the CataDDA project to build?

**Comment by macrosblackd** [comment]
I'm helping test windows builds for a cmake overhaul, so, when that is
finished and merged, it should be fairly simple to build.

**Comment by i2amroy** [comment]
Did we ever get around to contacting them for a license?

**Comment by macrosblackd** [comment]
no idea

**Comment by kevingranade** [comment]
Nope I dropped the ball there, sorry.  Will look into it as soon as I can.

**Comment by i2amroy** [comment]
Thanks, I'm definitely giving this a try once we get a license down, I quite enjoyed their IDE for Java, and am looking forwards to giving this new one a try once we have a license for it. :)

**Comment by macrosblackd** [comment]
Christian, you can get started with the 30 day trial, that way when
the license is obtained you'll already have the environment set up.

**Comment by kevingranade** [comment]
Sorry for the delay, I've applied for a license.

**Comment by macrosblackd** [comment]
Any news on this?

**Comment by kevingranade** [comment]
I made a request on the 19th (May) and received a confirmation that they
have it, but no contact since then.

**Comment by kevingranade** [comment]
I now have the license, contact me privately (kevin dot granade at gmail)
and I'll send it to you.  Please don't ask if you haven't made at least one
contribution to the codebase, I don't want to abuse JetBrains' generosity.

**Comment by macrosblackd** [comment]
Wohoo!

**Comment by DavidKeaton** [comment]
very nice!

**Comment by tvm1** [comment]
That is cool. 

Sadly, that thing requires 64-bit OS.

**Comment by DavidKeaton** [comment]
woah it's even got a Vim emulation plugin! thumbs up!

**Comment by DavidKeaton** [comment]
I have realized I love the ide, but dislike cmake.

**Comment by macrosblackd** [comment]
yea, I've been having the same experience.

**Comment by DavidKeaton** [comment]
wanted to give it a go on windows, but no luck. gonna try it under Linux (I'm sure it's a better experience there anyway).

**Comment by cfontes** [comment]
Hey any tips on how to make the project run on CLion?

I imported it but nothing works.

**Comment by Leland** [comment]
Closing - no movement here and not an issue.
