### ISSUE TITLE
Duplication glitch with inventory management screen

### ISSUE THREAD

**Issue by RightInfinity** [CleverRaven/Cataclysm-DDA#12095]
I just stumbled onto this while trying to get items out of a cart.

While attempting to remove items from a vehicle box with the "Surrounding area" selection, it instead just duplicates them, leaving the original in the cart.
![bug2](https://cloud.githubusercontent.com/assets/9588560/7245953/4e020d50-e838-11e4-8f8a-f8ce5de78961.png)

**Comment by drbig** [comment]
Thanks for reporting, but remember to include version and platform information next time.

(This bug is known and being worked on btw. - maybe even fixed in the experimentals).

**Comment by Coolthulhu** [comment]
Closed by #11998
