### ISSUE TITLE
AIM (advanced item menu) strange behavior in the most recent build 0.C-3041

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12109]
Right now it looks like in AIM the tile with the vehicle is a toggle, and this is big trouble for me personally.  Before the behavior was already how I liked it: simple and stable.  Now it's complicated and unstable.

Before: when I wanted ground, I'd use a number.  When I wanted 'd'ragged vehicle, I'd use 'd'.  Simple.  Reliable.  Good!

Now: when I want ground I use a number.  When I want a dragged vehicle, I have to first use a number, then 'd' and this changes '[D]' into an strangle colored '[V]'.  This is bad because it requires an extra key stroke for seemingly no reason.  But far worse than all this is the fact that this setting is not remembered.  So when I close and reopen AIM, looks like it's forgotten that I wanted to be looking at my dragged vehicle, and is now showing the ground :(.

But this isn't all.  The problems don't stop there.  Now I have another problem because of this annoying 'toggle' behavior.  Before I used to be able to hit 'd' in order to quickly flip the 'd' to the neighboring pane.  Now this fast and helpful behavior is gone.  Now I can no longer throw the 'd'ragged vehicle pane to the other pane by just hitting 'd'.  Now if I hit 'd', it just toggles 'D' to 'V', and that's all.  And if I hit it again, it toggles back!  How unfortunate.  Gone is the behavior when the 'D' pane would just switch to the right if it was on the left before.

This breaks one of the best parts of the game for me: AIM.

**Comment by Coolthulhu** [comment]
> When I want a dragged vehicle, I have to first use a number, then 'd' and this changes '[D]' into an strangle colored '[V]'.

Why do you have to first use a number? What's wrong with the behavior you get when just pressing 'd'?

Lack of remembered panes could be very easy to fix - by just making them static for now. Later on they should be saved to save json.

Toggle could be "fixed" by adding a button dedicated to it. Default would be like old behavior, trying to get ground under a vehicle would require using this new toggle button.

**Comment by graysage1** [comment]
>Why do you have to first use a number? What's wrong with the behavior you get when just pressing 'd'?

It doesn't seem to work?  I only played with it for like 5 minutes.  When I couldn't get the AIM to work I deleted 3041 and am back to playing 3035 where everything works fine still.

I can try to look it into more specifically.  I still have the 3041 zip file.

>Toggle could be "fixed" by adding a button dedicated to it.

Which toggle?  There are two toggles I can think of.  The first is how you can swap panes around.  That toggles has always worked in the past.  So if my AIM had [5] and [D] selected, which is when I am "vacuuming up" the good loot off the ground into my wheelbarrow, then hitting '5' would flip the panes and hitting '5' again would flip the panes again.  I really like this behavior because I don't need to know what my AIM is set to, when I open it, I can just hit d,d,5.  Then it would select d and throw it to the right, and select 5.  So I start with the destination location, hit its designator twice, and end with my source location.  Sometimes if I forgot that AIM was already set to the same thing, it ends up flipping the panels around, which I can flip back with a keystroke.  But if I quasi-remember what I am doing, it makes it easy to go from one AIM setup to another by just hitting destination twice and then source.  I do this all the time.  I especially do this before I can use a cart to move lots of objects around.  If I am moving heavy logs from one square to another square and I have to maneuver around obstacles, so I can't always move from 2 to 8, I sometimes have to move from 2 to 9, it's easy to change that -> 9,9,2.  In this case this would leave the pane in the wrong order, so an extra 2 would be required at the end to flip the 2 back.

The point is that sometimes AIM remembers its settings and so do I, and I just want to reuse them.  At other times, I open AIM and I know it's wrongly set, and I want to use the fewest keys possible to quickly setup both left and right panes and keep my cursor on the left side.

I don't mind fixes that cause me to retrain my behaviors if they end up in something consistent, stable, and efficient.  I don't like hitting any extra keys as a player of roguelikes.  So I am not dogmatic about any of this, I just want the end result to be consistent, powerful and efficient.

**Comment by Coolthulhu** [comment]
I was thinking about the vehicle toggle there. If pane flipping is important, having veh/ground toggle be a separate button would probably be the best solution.

**Comment by graysage1** [comment]
That's fine, so if you use 't' to toggle, then the new toggle behavior is out of the way as far as I am concerned.  Ideally I'd like to understand why the ground/vehicle toggle behavior is desirable at all, but if it's out of my way at least, I won't say anything. :)

**Comment by Coolthulhu** [comment]
Vehicle/ground is desirable when you drop too much on a veh tile, it all falls out and you're mad that you have no way to pick it up except with regular 'e'/'g' pickup.

**Comment by graysage1** [comment]
>Vehicle/ground is desirable when you drop too much on a veh tile, it all falls out and you're mad that you have no way to pick it up except with regular 'e'/'g' pickup.

So you're saying currently AIM would never show you the ground no matter what, if the vehicle was also in the tile?  This isn't something that I encounter often, so I can't say a lot about this.  You might be right.  If it's as you say, it's a problem because it then limits what the AIM can select.  AIM should be able to select anything that is whatsoever selectable by other means, imo.  So if you can select something with 'e', but not AIM, that's a bug.

**Comment by Coolthulhu** [comment]
No, I was saying that the ability to select ground even when the vehicle cargo is over it is desirable.
It didn't exist with the old AIM.

The way I see it:
* Selecting a tile should pick the vehicle by default
* Pressing some button should allow picking the ground below that vehicle

DaveK (who wrote most of the new AIM stuff) decided to add this functionality to the direction buttons instead. I don't know what his rationale was, but the decision makes sense to me. I don't use pane swapping, but if it's useful, I'll try to restore the old behavior here.

**Comment by graysage1** [comment]
>Pressing some button should allow picking the ground below that vehicle

This is where I disagree.  I much prefer, and currently depend on the present behavior: hitting the same button again throws the pane over to the other side.  I use this feature all the time, whereas needing to pick behind the vehicle is something I'd use once in a long while at best.

I am using the 'V' command shows accurately what's under the vehicle on the ground.  So if there is something interesting that 'V' shows, yea, I'll go looking for it in AIM.

> I don't use pane swapping, but if it's useful, I'll try to restore the old behavior here.

It's highly useful to me.  I use it **all the time.*  I can't imagine not using it.  What a chore would it be to have to use left/right keys to set up the panes correctly.

**Comment by Coolthulhu** [comment]
> This is where I disagree.

No, you don't, because you later say:
>  So if there is something interesting that 'V' shows, yea, I'll go looking for it in AIM.

Which wouldn't be possible if there was no way to view it in AIM.

But yeah, the decision to have this button replace the last direction button (and thus pane swap) is debatable.

**Comment by graysage1** [comment]
I think even the current common case is too slow, frankly.  3 keys to setup the panes is too much.  The game needs 2 keys to know the destination and source *in the common case*, and it shouldn't ask for more unless the case isn't a common one.

My ideal behavior would be like this.  I hit '/' then if I follow with any non-destination keys, it remembers the last configuration.  Or, I hit '/' followed by destination and source selections, destination pane on the right, source on the left (unless your country reads from right to left, where this needs to be reversed probably).  So '/85' will open AIM with 5 on the left side, the source, and 8 the destination on the right.  This will read "move to 8 from 5" if you like.  Or you can reverse from and to, I don't care.  The main point is that I get a new configuration in 3 keys total, and an old one in 1.

So when I hit '/' an old configuration opens, and assuming I don't hit any location keys, everything "just works."  So hitting 'enter' on the default first selection on the left side will "just work" to start moving it to the right.

However, if right after I hit '/' I hit '5' the game should "understand" that I want to perform AIM reconfiguration.  And in 2 keystrokes I can reconfigure right and left side.  Maybe start with the left.  So maybe source should be first, then destination.  I am assuming left-to-right country convention here.  So maybe if I follow / with '58' left pane should be 5 and right 8.  Done.  If 8 has a vehicle on it, then it would be /58t, or maybe not even 't'.

I still like the idea of tossing a pane over to the side with a single key stroke.  Maybe 't' should switch panes.

So two common use cases need to be fast:

1. I need to repeat a move with the same source and target locations as before.  This super be one key stroke: '/'

2. I need to designate a new source and target.  Whether AIM is already open or not, this should be a very fast action with minimum keystrokes.

So whatever is being done with the vehicle toggle should respect these use cases.

**Comment by Coolthulhu** [comment]
Makes sense. We could even have the panes automatically swap when any location button is pressed.
That way you could get any configuration with 2 keypresses regardless of menu state.

With my typical usage, it would be nice if tab didn't change the targeted pane, but only swapped them around, so that one pane (left?) would always be a source and the other one always the destination.

**Comment by graysage1** [comment]
>With my typical usage, it would be nice if tab didn't change the targeted pane, but only swapped them around, so that one pane (left?) would always be a source and the other one always the destination.

This might be very nice, now that I think about it.  Like I said, I tend to be open-minded about the specifics, and I only insist on the abstract principles.  So right now I believe the AIM implementation in 0.C-3041 breaks the principle of all common uses cases being maximally fast and easy to input.  So I would consider it a bug myself.  As for how to fix it, I agree there is more than one way to skin the cat.  

I used to love AIM before the few recent builds that introduced the vehicle toggle, and this new change really threw a wrench into my experience of CDDA.  But at the same time, I completely understand (now) the thing you're trying to address, which is a genuine grievance.

So however you end up fixing it, I hope the common uses cases will be fast, and that AIM will continue to be fun and fast to use like it has always been.  If we have to make the common case slow just so that occasionally someone has to look below the vehicle, to me that's not desirable at all.  I'd rather never be able to look below the vehicle if it meant slowing down (increasing the keystrokes) for the common case.

And it goes without saying, that '/' should always remember its previous selection.  I think remembering it between game saves (storing it in json) is probably overkill, but I won't talk about it if it gets implemented.  I don't see why it's so important to remember AIM settings between saves.  Also bloating save json is not a good idea.  But it's a tiny amount of bloat and maybe someone really will have a use case for this, so why not?  I am not against.

**Comment by kevingranade** [comment]
One correction, there shouldn't even be an option to select ground under a
vehicle tile unless the player is standing on the ground next to said tile.

**Comment by graysage1** [comment]
I'm thrilled to say that whatever I initially reported in this issue appears to be resolved in 0.C-3068 cb7dabb.  I knock on wood against future regressions. :)
