### ISSUE TITLE
Close all those PRs that won't ever get merged

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#12105]
We have quite a bit of ancient PRs that are not mergeable and no longer maintained. They only serve to confuse the build bot and make the PR list bigger than it needs to be.

I'd close all unmergeable PRs with more than a month of no updates with a note that this closing is not a rejection, but maintenance of the PR hopper and that I'll re-open them if the author replies.

Anything wrong with my idea?

**Comment by Rivet-the-Zombie** [comment]
Yeah, we've really needed to do this for a long time.

Good idea!

**Comment by drbig** [comment]
I fully support the idea.

I also feel similar treatment could be applied to issues.

**Comment by i2amroy** [comment]
I'm cool with PR's, and what issues we can filter out (notably older bug ones), but a large portion of the older issues are either feature enhancement plans that can't be closed so easily or are ancient NPC-type bugs that are still around in the present day. If someone wants to filter through the issues list and take off duplicates and solved ones that would be great, but it's not going to be anywhere near the ease of "cut off everything unmergeable from before X date" that the PR's are going to be.

**Comment by Zireael07** [comment]
Let's close the ancient unmergeable PRs first before getting into closing issues.

**Comment by kevingranade** [comment]
My current project is reimplementing the oldest unmergeable PR on the list,
and I plan to reimplement several others as I have time.  If nothing else
they serve as reminders of the issue,  if they're confusing the build bot,
consider making or finding a matching issue, linking to the PR, THEN close
the PR, but please don't simply close them unless they're abandoned or the
idea itself is bad or obsolete (as in implemented in a better way, not just
unmergeable).

**Comment by Coolthulhu** [comment]
> don't simply close them unless they're abandoned

I went by last update time, mergeability and user's presence. Most of the closed PRs were ones by users who are unlikely to return.
Some were truly obsolete (AI updates that are already in, in better form).

I'll list:
* #3798 (ancient, author no longer present, someone on forums is doing the same thing)
* #4029 (old "omnifaction" AI system)
* #4283 (technical, but no longer mergeable and maintained)
* #4366 Abandoned, however this one fits your "work on last unimplemented" idea. May be already implemented depending on how we look at it.
* #4975 (abandoned, highly sci-fi, the contributor "salvaged" the useable parts for a newer PR)
* #6564 (abandoned, littered with debug stuff)
* #6925 Another possibly re-openable. Abandoned for a while, but could be brought back to service with moderate amount of work. That said, writing it from scratch would also be moderate amount of work.
* #6954 (regards old tool quality system, giant and unsalvageable)
* #7892 Possibly re-openable. Abandoned and rather heavily unfinished, but a solid idea.
* #8159 (abandoned, a bit hacky and not really a good idea)
* #9992 (abandoned, not really finished, makes furniture that does some of the jobs vehicle system does)
* #10505 Abandoned. IMO this is a bad idea (modding weapons to be fancy? Should be inherent item quality, not a mod), but could be reopened if you don't mind the silliness.
* #10767 Possibly reopenable, but would take the author to come back and finish the job and the job is far more than just "making it mergeable".
* #10666 (abandoned, very "heavy", finishing it would take more work than rewriting from scratch. Idea itself is good, but is quite obvious and recurrent)

I think that's it.

**Comment by Frost-wood** [comment]
I'd argue:
 https://github.com/CleverRaven/Cataclysm-DDA/pull/11313 (user inactive, doesn't seem to have the desire to make mergable).
https://github.com/CleverRaven/Cataclysm-DDA/pull/7749(use inactive, really easy to redo).

**Comment by Coolthulhu** [comment]
#7749 could possibly be merged even right now, I think.

**Comment by BevapDin** [comment]
#7749 doesn't do anything. It adds terrain types that are used nowhere, if someone wants to use them, they can always merge that branch into their own work.
