### ISSUE TITLE
Using 'e' to clear away rubble with a shovel is too cumbersome when not under threat

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12114]
Let's assume the fight is over and the character is not threatened by anything.  In a situation like that, the game should relax the need for micromanagement.

So I suggest that if I hit 'e' once, it will highlight the tiles you can examine, like now.  But then if instead of a direction I hit 'e' again, it will perform an action on all the tiles.  Right now this can be tricky or even bad, because the game uses 'e' for so many diverse things.  You can use 'e' to look at a list of items on the neighboring tile.  Or you can use 'e' to clear away rubble.  Or you can use 'e' to interact with a vehicle.

When it comes specifically to clearing away rubble, I'd like to be able to clear it away en-masse, without getting picky about which specific tile right this turn.  So maybe the double-e will do something magic if you have a shovel and are surrounded by rubble and are not under threat?  Or maybe a more elegant solution is called for.  I don't know.

What I do know, is that right now I don't like looking at a 50 tile of rubble or crash site pile up and thinking how many times I'll need to hit 'e'+direction to get through it all.  I wish there was an easier way.

Maybe I should be able to select a wide area and say "till all this land in rows" or "clear away all the rubble in this giant 10x5 tiles square."  Then I let the game handle the minutia.  Then if a monster appears, this process stops and we're back to manual control.  Once I have dispatched the monster, there should be a "continue the previous process".  So if I was clearing away rubble, the game can take over my character and continue using the shovel to clear it away.

Tilling land and clearing away rubble are the only two tedious things I can think of at the moment that I sometimes may want to do a lot of in a row.
##

**Comment by Coolthulhu** [comment]
> Maybe I should be able to select a wide area and say "till all this land in rows" or "clear away all the rubble in this giant 10x5 tiles square." 

This is how I intend to eventually make it work. This way it could also be turned into an order you can give to an NPC. One of the reasons I started modernizing the NPC code.

**Comment by graysage1** [comment]
>This way it could also be turned into an order you can give to an NPC. 

If anything can improve what we can do with the NPCs, I am for it.

**Comment by Leland** [comment]
Discussion's been stalled on this one for over 2 years now. Closing. If anyone still has an interest in this, feel free to let me know here that you want it reopened; or just create a new issue.
