### ISSUE TITLE
Very minor: survival marker appears to create permanent effects.

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12118]
I thought it'd be nice to mark up my map with a survival marker.  What I didn't realize is that it leaves very visible highlights in ASCII mode (haven't tested in tiles), and I can't seem to erase them.  The best I can do is to use the survival marker on the same tile to edit the message to read something else.  But once I leave some message on a tile, there appears to be no obvious way to remove that message from the map.

Should there be a survival eraser?  Maybe the survival marker has an eraser on the other end of it? :)  I don't know.  I just know if I can't erase these messages, I will probably not use them freely.
##

**Comment by graysage1** [comment]
I noticed recently that leaving messages on items using a knife has a simple solution for erasing those messages: all you have to do is leave a message that is a single dot like so "." and the message gets erased.  Maybe this same mechanic could work for the survival marker.  I think it would be neat if those messages could be erased too, similar to how knife inscription can already be erased.

**Comment by Oskar636** [comment]
Build 5892 windows 64bit console. When you write something with the marker, it makes a message on the ground. When you write again on a tile with a message and input "." ( like it says on the window that it displays ) it removes the message. Can be closed.
