### ISSUE TITLE
Suggestion: a generic 'do last action again' button.

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12113]
I can't count the number of times I performed a multi-keystroke action and just wanted to repeat it again.  Right now we have this for fabrication with '-', but not for anything else important.  Not for construction.  Not for clearing out rubble.

As far as rubble goes, I wish I could hit a single key to clear all of it out instead of writing a small poem.  Yes, sometimes which square I clear out first is important if there is a baddie, but if there isn't a baddie around, I should be able to use the long-time-taking "do all this stuff at once" commands.  So for example, here's the space, clear it all up.  Or clear all the rubble around yourself (1 square away from yourself and on your own tile).  I'll make a separate issue about the 'e' button behavior, but it's slightly related because these are both about keystroke efficiency.

Being able to perform the last action again will go some ways toward making the game less keystroke intensive.

**Comment by narc0tiq** [comment]
Part of this is already mentioned in #574, but the clearing rubble enhancement is an interesting continuation.

**Comment by i2amroy** [comment]
Yeah, it's close enough that I'm marking it as a duplicate, especially considering the rubble stuff has been addressed in #12114. Closing.
