### ISSUE TITLE
AIM (advanced item menu), bug in the advanced searching semantics

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12110]
Currently AIM allows you to search items by hitting 'f' or '/' and then typing a comma separated list.  This is a tremendously helpful feature that I use all the time and can't imagine playing without.  It mostly works exactly as one would expect, which is great.

But there is one case where it does not work as expected, and that is if I have a list like this:

leather,-gloves

So I would expect any items with the title strings containing 'leather' to be selected, and from that list anything that contains 'gloves' should be deselected.  So it should be all leather save for the gloves.  It doesn't work this way.

Currently the minus operator only works if your list doesn't start with a default (or plus, if you like) operator.  So -leather,-gloves seems to work as expected by eliminating anything with the string 'leather' and anything with the string 'gloves' from the list.  If you _do_ start your list with a non-minused search term, it seems the minus operator stops working.  That's something I'd like to be able to do often.
##

**Comment by DavidKeaton** [comment]
I have a small bit of a filter class I want to implement that I hope will take care of this issue by centralizing filter searching. :-)

**Comment by Leland** [comment]
Closing due to lack of discussion.
