### ISSUE TITLE
Minor cosmetic issue: the keybinding help/configuration screens are somtimes malformatted

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12115]
Right now some of the keybindings have long descriptions that swallow up the key for that keybinding, making it sometimes hard to see at a glance which key a function with a long description is bound to.

This isn't a major issue for me, and it hardly detracts from the fun of playing the game, but for the sake of completeness I figured I'll log it anyway.  I don't look at the keybinding screens that often.

**Comment by BevapDin** [comment]
This pretty much what #11918 is about.

**Comment by graysage1** [comment]
I'm afraid you're right.  Sorry for the dupe.
