### ISSUE TITLE
Suggestion: maybe the game should have macros

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12116]
This suggestion is in similar spirit to the 'e' button suggestion I've made: basically it's a theme of reducing the keystroke input necessary to achieve game objectives.  This doesn't change the game balance, but only improves the player's convenience and expressiveness with the game.

Along this philosophy of reducing all redundant keystrokes to a minimum, why not consider macros?

Right now CDDA uses lots of keys in its keybindings, so this leaves mostly only the F keys on a typical keyboard, which is good, but not great.  I think we should take this into consideration too.  I'll return to this later.

So for example, if I have a pneumatic gun (which is awesome, btw, I love this thing and want to get married to it), I often want to convert rocks into pebbles.  This usually is: &, /, 'peb', enter, enter.  (Let's assume I was previously cooking meat so I can't use '-'.)  And this is with the advanced usage of searching in the construction menu!  (Thank you to whomever added and morally supported adding of the searching functionality to the construction!!!)  If I didn't use searching, many times this input would be far longer.  So if I wanted to cook meat, again that's a common occurrence, then &, pg-down, pd-down, down, down, down, down (however many times), then enter.  And you don't even know in advance how many times you need to hit down, you just have to look for it.  This is unnecessarily tedious.

So macros would solve this and many similar problems in a *generic way*.  *Generic* is the key word here.

Now, because we don't have the luxury of many unassigned keys, I suggest that macros all be hidden behind a macro key.  So for example, if I assign the sequence of keys to "make the pebbles" to "F1", then instead of hitting "F1" directly, I would first hit macro key, which maybe would open a list of my macros in a popup, or maybe just ask for more input similar to say the 'e' key, and then 'F1'.

In a way our current '%' is a hard-coded and (sorry people) in my view *clumsy* way of doing the same thing.  Instead there should be a generic macro system, and maybe the game should come prepackaged with some default macros which might be exactly like whatever is in the '%' menu now.

So prepackaged macros would work very similarly to how % (action) menu works now except they'd be arbitrarily configurable instead of being hard-coded to a few developer favorites.  Let the players make their own lists.  I like to make pebbles often.  Someone else makes them never.  We shouldn't all have the same action menu.  And when I get tired of making pebbles, I want to be able to stop seeing them in my list of macros as well.  So that's why it shouldn't be hard-coded imo.

The idea of making pebbles while standing on a rock and cooking meat with one or two keystrokes is something that's very appealing to me.  And making it configurable and generic as opposed to hard-coded is very appealing as well.  Hence macros.

**Comment by i2amroy** [comment]
Honestly? The amount of work required to create some sort of "generic hotkey system", combined with the further amount of work that is required to keep it up to date and fix the inevitable bugs when it falls behind in any given spot isn't worth the reward when you could accomplish the exact same effect by downloading an external program like [autohotkey](http://www.autohotkey.com/) to accomplish the exact same thing.

**Comment by Coolthulhu** [comment]
I don't think autohotkey would play nicely with DDA's tendency to drop input when stressed.
The best thing I can think off would be some sort of input queue system that could both buffer player input and accept some other source (file?).
It would depend on keybindings and the like, so it would be nowhere near perfect, but it wouldn't be unbelievably unmaintainable like a proper macro system.

**Comment by graysage1** [comment]
Maybe 100% generic macros is too much to wish for.  How about allowing the player to bind commonly used construction projects and commonly used fabrication projects to some keys?  This wouldn't be completely generic, but then you can make some safe assumptions about what's going to happen next.

And while this isn't macros, it would achieve a similar goal: NPCs which can build construction projects and fabricate items when supplied and taught to do so by the player.  So if an NPC can make me pebbles or duct tape, then I don't care if I can't macro it.

**Comment by kevingranade** [comment]
I'm very against a macro system, it's a sign of a "by programmers, for
programmers" program, and presents a ridiculously high barrier to entry, if
not for playing the game, then for playing the game well.  Any actions that
are repetitive and require too many keypresses should instead be
streamlined somehow to address the problem directly.

**Comment by graysage1** [comment]
@kevingranade I like your pro-average-player anti-elitist philosophy. :)  Looks like we agree on what's important: it's good roguelike design to try to always look for ways to remove needless keystrokes.

I'm going to close this issue then, but I'll probably say something here or there about keystroke efficiency, because it's a topic that's often on my mind when I play roguelikes.

**Comment by kevingranade** [comment]
No complaints at all about the anti-keystroke issues, they're legitimate.
