### ISSUE TITLE
Idea bank

### ISSUE THREAD

**Issue by illusionofchaos** [CleverRaven/Cataclysm-DDA#12124]
It would be nice to have something like [this](https://utorrentideas.uservoice.com/forums/47263-µtorrent-for-windows) to collect new ideas from the community and vote for them.

Here are some ideas:

## Railways and draisines

They would make a great addition to the game.
## Nutrition

It's possible to incorporate data from [this database](http://www.ars.usda.gov/Services/docs.htm?docid=24912) and  [DRI(Dietary Reference Intake)](http://en.wikipedia.org/wiki/Dietary_Reference_Intake) data into the game to make the player suffer penalties from inadequate nutrition (or at least use real calorie values instead of satiety).

## More items

[Here](http://deadrising.wikia.com/wiki/Category:Weapons) are some weapon suggestions and [here](http://deadrising.wikia.com/wiki/Category:Weapons) is really huge list of weapons from Dead Rising.

[Here](https://pzwiki.net/wiki/Category:Items) is the list of items from Project Zomboid (includes recipes and nice icons for MShock32 tileset).

**Comment by illi-kun** [comment]
What should happens after the vote? Who will put the selected ideas in code?

**Comment by graysage1** [comment]
Someone already implemented this idea.  Here it is, the bank that you want:

http://iv.cataclysmdda.com:8111/all

And if I understand correctly, the way it works is the same as with the issues people report here.  We can complain until we're blue in the face, but at the end of the day everything is entirely discretionary for the implementers.  Technically they don't owe us anything, but on a human level I imagine it's nice to at least pretend that we all work toward some overlapping goals with this game that we all seem to love, both the players and the developers.

In the spirit of open-source and free software, if someone really really doesn't like something, the ultimate freedom is forking the project. ;)

Well, considering the nature of distributed source control, this is even more subtle now.  Technically forking now happens all the time.  So nowadays "forking the project" is less about forking the source, and more about your alternative builds becoming popular, and perhaps becoming the new gold standard for the community.

**Comment by Headjack** [comment]
Nutrition is generally reflected in health/disease vulnerability, if I recall.

**Comment by kevingranade** [comment]
One suggestion per issue please, the point of an issue is not to get your idea out there, but to track whether it gets resolved or not, if it's not important enough for you to make separate issues, it's not important enough to be in the issue tracker.  Likewise, "add all the items from this other game" is not a productive suggestion, "please add this new *kind* of item would probably be productive, but simply more items is not.  If you want to do a brain dump, use the forums, they're perfectly fine there.
As for Illi-kun's question, voting is a way for people to show their support for an issue, but it doesn't necessarily mean it will be implemented.  However if an issue has dozens of votes, it would certainly get my attention and shift priorities to get it resolved sooner.
