### ISSUE TITLE
Minor: the game acts like a badly behaved application during '$' sleeping (Windows)

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12122]
This happens with the Windows build.  So when I sleep, it looks like the game appears unresponsive as an application, and I get an "hourglass" cursor (which is more like a circle these days on Windows), and it even looks like it's trying to readjust the window size??  I see the inner window edge jump around right before the sleep cycle ends.  All this seems completely unnecessary to me.

I realize that the game needs to simulate a lot of stuff.  That's fine.  However, the game should probably display its own progress bar and it should not appear unresponsive to Windows, and nor should it attempt to readjust the window size during sleeping, since this makes no sense at all.

Overall this has a very minor cosmetic impact on the experience.  It's not a huge priority for me as a player to get this fixed, but this weird behavior may signal bad "under the hood" coding practices which the devs might care about.  Usually well written code tends to be well behaved and doesn't act like this.

**Comment by BevapDin** [comment]
So... basically a specific version of #11238 (quote from there "With sleeping it results in a big chunk of unresponsive CDDA")

**Comment by Coolthulhu** [comment]
Also happens when saving the game with a large number of submaps

I'm not sure if it is actually fixable without multithreading or hacks.

**Comment by graysage1** [comment]
@BevapDin Maybe?  I don't have familiarity with the code, and don't plan on acquiring it in soon either.  I speak strictly as a player, and reading the issue you referenced it's not at all obvious to me.  But I realize you might be right since you know better what's going on under the hood.  Maybe it's related.  I don't know.

**Comment by graysage1** [comment]
I am mildly curious if this happens on Linux as well, in the tiles build.

**Comment by KrazyTheFox** [comment]
> I am mildly curious if this happens on Linux as well, in the tiles build.

I believe it does. I would go confirm that right now but I'm at work.

**Comment by FireCrow1973** [comment]
I have almost given up on this issue ever being fixed.
in some circumstances it gets better, and in other it gets worse.
and i cant tell whats making the difference, i'm at a loss!

**Comment by DanmakuDan** [comment]
I think you could add SDL_Delay to the sleep/save loop so Windows doesn't complain about losing control over a 100% CPU operation.

**Comment by i2amroy** [comment]
>I have almost given up on this issue ever being fixed.

Sadly this is one of the issues that tends to fall by the wayside due to "dev computer syndrome". For example it is personally difficult for me to attempt a fix for something like this when even in debug mode I can complete sleeping in seconds with no problems. :/

**Comment by tyrael93** [comment]
I can conform it does not happen on Linux. Much smoother gameplay, too.

**Comment by FireCrow1973** [comment]
don't get me wrong, i am not blaming anyone.
these days the game functions pretty smoothly.
most problems are bugs, and balancing issues.

but this is a big glaring....."thing", it moves the window,
resizes the graphics, freezes and says not responding.
its kinda jarring, is all.

**Comment by graysage1** [comment]
@i2amroy 

Is it possible, at least in theory, to ship a special instrumented binary to the experimental player community, and then ask the players to submit the log files that the instrumentation can collect?  You can do some profiling that way on computers other than your own, and then maybe, just maybe, you'll see where the game spends an abnormal amount of time.

I realize instrumenting code for this can be quite a chore, if it isn't already there.

Or maybe all game builds can already do this and the players should just be taught how to enable logs and/or other data collection methods?

**Comment by Zireael07** [comment]
I can be the guinea pig, too. The freezes and (not responding) notification can be pretty annoying.

**Comment by graysage1** [comment]
For me personally this isn't a huge issue probably in part because my computer is relatively beefy and has an SSD in it.  However I just realized that maybe some people with the less powerful computers may be suffering from this more than I.  I guess I was maybe being a little selfish when I called it "minor." :)

**Comment by graysage1** [comment]
The game on this end appears to behave better than before (build 0.C-3068 cb7dabb).  I no longer get an "hourglass" cursor on Windows here.  However, in my view the behavior of the game is still less than ideal because when I hit "Yes" to begin sleeping, it just pauses with the sleep dialog still open until the very end of the sleep cycle.

It would be nice if the game could postpone heavy simulation processing long enough to close the '$'leep dialog after "Yes" was selected and notify the player that the game is about to start simulating sleep time.

**Comment by graysage1** [comment]
Should this issue be closed?  I mean, the application behavior is definitely better than when I opened this issue.  Is it better enough for most people?

**Comment by Coolthulhu** [comment]
The console build still freaks out when locked up, at least on win7.

**Comment by DavidKeaton** [comment]
windows hates loops that don't touch the ui in X time.
