### ISSUE TITLE
Cosmetic: The game fails to instantly repaint what some popups have covered up.  (ASCII mode)

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12128]
Often the game needs to display a confirmation popup and/or similar, and when these popups go away, it looks like there is a black area left behind by the small window that just got closed.

Whenever any popup is closed the area it occupied should always be repainted.

To me this is a relatively minor issue.  It's cosmetic and the screen eventually does get painted in, at first by the rain/snow animation, and later through movement.  But if it's easy to fix, why not fix it.
##

**Comment by BevapDin** [comment]
Can you give some examples where this happens, because right off the top of my head, I only remember situations where it actually worked correctly.

**Comment by graysage1** [comment]
@BevapDin Sorry for the lack of specificity.  I'll try to keep an eye on them as I play.  For now I have quickly poked around and found one use case:

Inside the game hit 'V' to open the item (and monster) scanning view, then hit '?' to open a help screen popup within that view, hit ESC to close the popup.  What do you see?  I see an unpainted black square the size of the help screen's popup.  I do believe there are some other instances of this behavior in the game and from memory they're all relatively small-sized popups at the center of the screen.

OK, I found one more use case.

Hit 'Y' to open the zone manager, hit 'A' to add, designate the first and the second corners of a square, then the game opens a popup that asks for the name of the zone.  Once you type the name and hit enter, that popup will disappear and the screen will remain black/unpainted behind it.  It doesn't last long, because once you hit enter on the next popup, the screen does repaint itself.

Maybe with luck I can spot more.

**Comment by Zireael07** [comment]
Easiest way to trigger: move the mouse over some item so that you get the popup description in the sidebar. When you move the mouse to a tile which is empty, the popup disappears, leaving a black space where it was and the messages don't get redrawn.

**Comment by graysage1** [comment]
@BevapDin I just found one more case.  If I 'a'pply an already-lit torch, the popup leaves behind an unpainted area after I select "light something" option, but before I pick a direction.  Build 0.C-3106.

**Comment by graysage1** [comment]
@BevapDin Another one: when I was making "small strings" from threads and a zombie moved into my visual range at night, the game asked me if I wanted to stop crafting. That popup later left an unpainted area behind it.

**Comment by Leland** [comment]
Hasn't been active discussion on this one in over two years - closing. Feel free to let me know if want this reopened.
