### ISSUE TITLE
Amigara fault is broken

### ISSUE THREAD

**Issue by i2amroy** [CleverRaven/Cataclysm-DDA#12134]
As of this posting the amigara fault doesn't prevent you from looking away, killing horrors doesn't spawn an artifact, and you can initiate tremors multiple times.

**Comment by ejseto** [comment]
Couldn't you always initiate tremors multiple times?

**Comment by i2amroy** [comment]
Possibly, but if we allow it and the player can actually beat the amigara fault then it just becomes an infinite artifact farm. I could see allowing multiple uses if we had some lesser "strange" item (like the vortex stone) that would drop after the first successive use instead of the artifact, but as is infinite artifacts is kinda crazy.

**Comment by Headjack** [comment]
From what I recall, you could always multi-initiate, but needed to approach before a mob spawned.
