### ISSUE TITLE
Game-breaking: AIM (advanced item menu) is completely broken now, even worse than I thought at first.

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12132]
I'm now looking at 0.C-3048 to see what's going on with AIM, since as of 3041 it was in a truly sorry state.

Well, it looks like it's worse than I thought.

Firstly, all the problems I mentioned are still there and still very important to fix,

But now add to the list of those problems a severe game-breaking problem: whenever I select a stack to begin moving and hit 'enter' to try to move from my grabbed vehicle onto the floor tile, the vehicle becomes deselected!  All my vehicle stuff is now no longer displayed in the left pane (and the floor tile I was moving to was in the right pane).

Come on people.  If you want folks like me to keep testing every latest build, they can't stay broken for too long or be fundamentally broken in some important respects.  To me AIM menu is nearly the center of CDDA.  I spend probably 20% of all my CDDA time in that menu, which is a huge chunk.  A lot of important decisions get made in the menu.  I can't play CDDA without AIM.  Right now AIM is broken to the point of being useless.

Please, I beg of you, please revert all the recent AIM changes no matter how beneficial they were intended to be.  Let's go nice and slow with the AIM updates.  Let's test them.  Let's get input from the players to make sure people are happy with the result.  Recent changes break AIM in more than just one or two ways.  Now if one of your panels includes a grabbed vehicle, there is no way to set up both panels with 4 keystrokes, without having to use left/right buttons.  We're going backwards guys.  We're making AIM worse for the common case only to get it to work on some weird corner case.

EDIT: I just want to make sure I am clear in expressing myself: To me all the post 3040-ish builds as of now are unplayable.  They're not just slightly buggy.  They're unplayable.  I can't play because what I need to be doing all the time is literally no longer doable at all.  This isn't just maloptimization for the common case, which is bad enough and has to be fixed right away.  I mean, now even the basic functionality is broken, rather than just grossly suboptimal.

0.C-3035 was the last build I played that was still perfectly fine when it comes to AIM.

**Comment by i2amroy** [comment]
It's broken because there were some problems updating it that are currently working on being resolved (Right now we have something like 2 fixing PR's up already). The original merge went in due to the large number of other fixes that it contained, once we iron out the handful of new problems that it introduced (some of which were fairly serious) we should be back to where we were before. It's a drawback to playing the experimental; sometimes things break and it takes us a bit to fix them.

**Comment by Coolthulhu** [comment]
Experimentals are like that: experimental.

I did break things by prematurely merging a PR that was heavily WiP, but this was mostly because it also contained bugfixes for other serious bugs: duping or eating items.
So no, 0.C-3035 wasn't perfectly fine, it was broken in a different way.

To restore the AIM to "perfectly fine", we'd have to roll the AIM back ~3 weeks or so, removing the ability to select ground under vehicle tiles altogether. It would be more work than fixing the bugs we have right now.

**Comment by Coolthulhu** [comment]
OK, I tested the AIM a bit more and I see what do you mean by "completely broken".
PR'd a partial fix here: #12137

I thought I'm merging a bugfix, so I rushed it without testing too much.

**Comment by graysage1** [comment]
To me hauling behind yourself a 'G'rabbed cart is a core CDDA game tactic.  It's not something optional.  The game is designed such that your character, even with sky high stats of 14 is weak, and can't nearly carry all the super-heavy and super-bulky stuff in the game, and therefore needs a cart.

I'm sorry for slightly loosing my cool there for a second.  I love CDDA and I thank everyone who is working on it.

**Comment by graysage1** [comment]
@Coolthulhu 

What does #12137 fix?  I just loaded up 0.C-3050 and I don't see any of the bad behaviors fixed.  On top of that, I noticed a new way it breaks, if it's possible to believe.

Now I notice that it's not only when I move items away from the 'G'rabbed vehicle, but also when I move items *into* the 'G'rabbed vehicle that the vehicle selection disappears completely.  And it doesn't matter which panes the floor [8] and <V> occupy.  Whenever I move an item to <V> (which is my grabbed cart in this case), <V> switches to <D> and the list of items in the vehicle goes away.  The same happens when I move an item from <V> to [8].

So the game is still unplayable after the fix in exactly the way I described.  I don't understand what is fixed exactly.

**Comment by Rivet-the-Zombie** [comment]
>To me hauling behind yourself a 'G'rabbed cart is a core CDDA game tactic. It's not something optional. The game is designed such that your character, even with sky high stats of 14 is weak, and can't nearly carry all the super-heavy and super-bulky stuff in the game, and therefore needs a cart.

I rarely haul around a shopping trolley when I play, so I've not really been affected by the problems with AIM.

**Comment by graysage1** [comment]
>I rarely haul around a shopping trolley when I play, so I've not really been affected by the problems with AIM. It's never really struck me as being a non-optional core game mechanic.

Then you have other ways to convenient move large piles of stuff?  Or do you take packrat trait?  How do you manage?

**Comment by Rivet-the-Zombie** [comment]
A large backpack and marked caches of anything that's too big to haul constantly.

I'm a *S.T.A.L.K.E.R.* girl.

**Comment by graysage1** [comment]
Maybe my backpack is not large enough.  It's only 40 volume.  I can conceivably make one now that 50 or so.  I need torso encumbrance to be somewhat low because I melee often.  So I can't use the duffel bag, at least, not unless I always drop it to fight.  I really prefer the cart then which is hassle-free.

So then what about welding equipment and pot and so on?  These are all large volume items.  I like to have pot with me.  I also like to have an axe and a shovel, and the entrenching tool is not easy to get early on, but even then it's still 4 volume.  It all adds up.  I just like to have all this useful stuff always next to me so that if I see something cool, I can react immediately without making plans to come back to it with a shovel, then return the shovel back to its holding place, etc.

**Comment by sparr** [comment]
melee doesn't mix with high volume, period.

dragging a shopping cart should be much slower and louder than it currently is, especially on non-smooth terrain.

**Comment by graysage1** [comment]
@sparr 

>dragging a shopping cart should be much slower and louder than it currently is, especially on non-smooth terrain.

Not if the wheel is big enough.  Farmers use wheelbarrows all the time on non-smooth surfaces.

**Comment by sparr** [comment]
A wheelbarrow and a shopping cart aren't quite the same thing. Eventually they will behave differently.

**Comment by graysage1** [comment]
@sparr That's what I deserve for using such a reductionist language.  I call any one square vehicle with a big cargo space "cart," lol.  I even name my custom wheelbarrow "super-cart" in game.

I agree with you.

**Comment by graysage1** [comment]
Looks like in the build 0.C-3068 cb7dabb this is also no longer an issue. :) <-- this is a happy face.
