### ISSUE TITLE
Hydraulic muscles vs cars

### ISSUE THREAD

**Issue by tvm1** [CleverRaven/Cataclysm-DDA#12130]
If I boost my strength from 9 to 29 using hydraulic muscles, I'm still unable to grab and move 1080kg flatbed truck or 735kg car even by one square.

EDIT: Well, sometimes I magically manage to move the lighter car in seemingly random direction. All what's needed is the ability to push the car one or possibly more squares forward, while standing behind it (just as normal people push cars in real life). Would be very useful on blocked bridges.
##

**Comment by kevingranade** [comment]
You can drag vehicles that are up to 5x your lifting capacity.  It would be
reasonable to have a check to see if the vehicle can roll and is being
pulled or pushed in the direction its wheels are facing and increase that
multiplier, but that feature is a bit involved to add.

**Comment by sparr** [comment]
is that a desired feature? I think I've touched most of the relevant code recently and I'd be happy to try.

**Comment by Shadefang** [comment]
I would personally say it definitely is. Considering in a pinch I can actually push my car, why shouldn't the hulk of a cyborg be able to?

**Comment by Coolthulhu** [comment]
The feature would be good, but not in its current state. Try pulling a 3 tile bike and you'll see what I mean. Someone would have to re-do the push/pull function to properly re-position at least the grabbed point so that it always stays in the same orientation towards the player.

**Comment by Zireael07** [comment]
@Coolthulhu: +1, (G)rabbing a bike/motorbike is a PITA currently, I can't imagine grabbing anything bigger.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
