### ISSUE TITLE
Inconsistent handling of Kevlar(TM)

### ISSUE THREAD

**Issue by tvm1** [CleverRaven/Cataclysm-DDA#12145]
Currently it's possible to repair/upgrade Kevlar items only using soldering iron.

Oddly enough, it's possible to reinforce your clothes with Kevlar using tailoring kit.

Kevlar is a fabric that is tailored using thread and needles or sewing machines in real life, thus I suggest to make Kevlar repairable/upgradeable using sewing tools instead of soldering iron.
##

**Comment by Leland** [comment]
Hasn't been active discussion on this one in over two years - closing. Feel free to let me know if want this reopened.
