### ISSUE TITLE
Shower victim towel never dries?

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#12146]
g57d02ec Linux tiles

In the Really Bad Day scenario, the shower victim starts wearing a "towel (wet)". This item is not active and (I think) never dries. Can't confirm 100% that it never dries as I normally dump the towel somewhere before too long.

**Comment by i2amroy** [comment]
I can confirm this. It's not an active item, so it will never dry.

**Comment by mugling** [comment]
Duplicated by #14437 which contains the most recent discussion
