### ISSUE TITLE
More Survival Tools mod: the ember carrier exhibits strange behavior

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12143]
Firstly I want to say a word of thanks to the person behind More Survival Tools mod, and to the team that approved of merging it here. :)  I love this mod.

Now, the ember carrier initially allows to store within itself 50 tinder.  However, once lit, it can then store up to 100 tinder.  Is this intentional?  It seems strange to me.  Why are there two disparate tinder limits?

**Comment by i2amroy** [comment]
This would almost certainly be better off in the thread for the mod on the forums. The dev's here don't really tweak mods unless they we absolutely have to, we just merge the changes that the people managing them do.

**Comment by graysage1** [comment]
@i2amroy I hear ya.

**Comment by chaosvolt** [comment]
It would appear I fucked that up. Will fix in the Series 3 PR.
