### ISSUE TITLE
Light not getting into the buildings

### ISSUE THREAD

**Issue by tvm1** [CleverRaven/Cataclysm-DDA#12141]
Weather: sunny
Time: noon
Situation: Standing next to open window or doors (evac shelter)

Lighting:
0.B - brightly
0.C - dark
experimental - dark

Did the world became bit darker ? :-)

**Comment by stk2008** [comment]
i have noticed this to in a garage.

i was trying to read and it was early morning but still very light and i could not see to read i had to use a flashlight even though turning on the flashlight did not light up any more squares than what was already lit before i turned the flashlight on leading me to think i should be able to read with out it as it made no visual difference on screen.

**Comment by Treah** [comment]
I mentioned this on the IRC channel today and tvm1 was nice enough to post it here. 

I was running 0.C and have notice that the tiles around windows do not lighten up like they should to indicate that light was flowing in from outside. It did do this like tvm1 said before 0.C

**Comment by Treah** [comment]
This is fixed by the below change. 

"Light attenuation based system for FoV and dynamic lighting. #12290"

**Comment by illi-kun** [comment]
According to the previous comment, this issue was resolved during light system overhauling. @kevingranade, what do you think about that? Can we close this issue?

**Comment by tvm1** [comment]
This works correctly now and should be closed.
