### ISSUE TITLE
Minor: floor tiles claim they're smashable (description)

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12154]
In a regular house, when I use 'x' to examine floor tiles, they say:

```
floor; movement cost 100
Smashable.  Flat.
```

I was surprised to find that the floor was smashable, and intrigued.  I was just about to take advantage of this little hidden secret and smash the floor for its goodies, feeling smug for being so attentive to little details in descriptions I am certain many of my post-apocalyptic colleagues would have overlooked, when... nothing.  Yea, just as I expected.  Of course.  How can empty tiles be smashable?  What was I thinking?

**Comment by Coolthulhu** [comment]
Here "Smashable" means "can be destroyed", not "can be smashed with `s`".
You need tools like jackhammer or pickaxe.

Maybe later there will be a second floor you could reach by smashing down.

**Comment by graysage1** [comment]
I see.  I thought "smashable" explicitly was about "s".  Perhaps I made an unreasonable assumption then.  I still feel it's confusing initially, even if after your explanation it makes sense.  I think I'll close this issue for now, cause it's not just a word/flag change as I thought.
