### ISSUE TITLE
Unrealistc damage when using high cal sniper rifle

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#12155]
win 7 64bit
dev build 3054 64 bit

Hi all I am testing the damage done of high cal weapon so far I have tested the Barrett M107A1.

I placed a cow at the very edge of my view and increased skills to 10.
I placed AP rounds in the gun and added a scope.

I have to hit the cow 3 times 99% of the time before it dies now for a .50 cal round this is very very wrong.

I then tryed the API whice explode on impact though a bit better it still took 2 shots.

I think this needs to be changed to reflect real life damage these weapons do.

Thanks all

**Comment by sparr** [comment]
A 50-cal, or even an incendiary round, won't kill a cow immediately and in one hit if you hit it in the leg.

**Comment by stk2008** [comment]
I shall test this same weapon and ammo combo using a human or simuler :)

Thanks

**Comment by chaosvolt** [comment]
>AP rounds

While .50 BMG is one hell of a bullet, FMJ and AP rounds do fare a bit worse in terms of terminal ballistics compared to, say, JHP. In this case it likely isn't as severe a difference compared to, say, 9mm JHP versus FMJ, but it could have some affect. Then again I don't think the game HAS a JHP .50 to compare it to, and I'm unsure of the terminal ballistics of AP versus API.

Where you hit them, especially for an animal quite a bit larger than a human, would factor into it as well. Though I would bet that if it doesn't kill a cow in one shot, it should still leave quite a mark.

As it stands there's not much model for injuring or incapacitating monsters/NPCs. For one, shotguns would be a lot more Fun if they could bust an NPC's ribs underneath kevlar.

**Comment by DavidKeaton** [comment]
most rounds higher than a 9mm would knock the wind out of a Kevlar wearing target.

**Comment by chaosvolt** [comment]
Most certainly, yes. Again something that NPCs don't seem to account for, as far as I can tell.

Now what it'd do to a COW wearing kevlar, I dunno. o3o

**Comment by DavidKeaton** [comment]
It would moooo-st certainly protect it from udder annihilation.

**Comment by chaosvolt** [comment]
You and your puns, always dragon me down. =w=

**Comment by DavidKeaton** [comment]
Puns are fun!

**Comment by Cat09** [comment]
I think we need a little better vital organ / vital function handling for this to work properly, a hole in the head doesn't ACTUALLY damage the head 100% does it? >.>
maybe a few extra conditions for dead instead of flat hp?

**Comment by chaosvolt** [comment]
Or, again, incapacitation in general. owo
