### ISSUE TITLE
Knife is unavailable for fabrication when it's stored in the boots.

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12150]
I have a stone knife stored in the boots I am wearing.  There is splintered wood on the the same tile as my character.  My fabrication skill is 1.  When I enter fabrication menu '&' to craft a wooden needle, "1 tool with cutting of 1 or more" glows red, suggesting the knife is not available.  When I remove the knife from the boots by 'a'pplying the boots, the game allows me to make a wooden needle then.  If I resheath the knife, again it becomes unavailable for fabrication.

**Comment by DavidKeaton** [comment]
thought this got fixed a bit ago....

**Comment by graysage1** [comment]
@DavidKeaton I tested it in the latest build.  Please let me know if you can't dupe it.  I'll try to help.  I superficially think it's trivial to dupe but I may be overlooking some nuance.

**Comment by graysage1** [comment]
Build 67ba376.  New map generated without mods, city size 5, season length 30, static NPCs and defaults on the rest.  I start the default campaign.  I spawn boots and a diamond knife using debug menu and make sure no other knife is nearby to spoil my test.  Yup, it duplicates like a champ.  Looks like a 100% duplicatable bug to me at the moment.

**Comment by DavidKeaton** [comment]
there may have been an update touching that code, I believe ya. I'd dupe but need to finish the AIM stuff. :-)

**Comment by Coolthulhu** [comment]
The `has_quality` function doesn't recursively check contents. Easy to fix.
