### ISSUE TITLE
3 is drawn funny with the packaged square font.

### ISSUE THREAD

**Issue by blazeblue32** [CleverRaven/Cataclysm-DDA#12153]
![issue_with_no 3_square](https://cloud.githubusercontent.com/assets/12097867/7317213/9a831e04-eac1-11e4-929e-d60d1f9c9bf3.jpg)
I've tried multiple text sizes.

**Comment by sparr** [comment]
Good free-to-reuse square fonts are hard to find. We have a couple of open threads about replacing the default one with another.

**Comment by graysage1** [comment]
@sparr 

>Good free-to-reuse square fonts are hard to find.

Here's an almost square font that work really well as a square font, and it's free as near as I can tell:

http://www.squaregear.net/fonts/whitrabt.shtml

Use it, after installing it, with the following settings:

```
{
    "fontblending" : true,
    "fontwidth" : 8,
    "fontheight" : 16,
    "fontsize" : 16,
    "typeface" : "Terminus",
    "map_fontwidth" : 16,
    "map_fontheight" : 16,
    "map_fontsize" : 20,
    "map_typeface" : "White Rabbit",
    "overmap_fontwidth" : 16,
    "overmap_fontheight" : 16,
    "overmap_fontsize" : 20,
    "overmap_typeface" : "White Rabbit"
}
```
