### ISSUE TITLE
Intermittent bug: sometimes the 'Sheltered' scenario is unable to find a starting LMOE shelter

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12160]
This happens on some maps more than on others it seems, but once in a while when I try to run a 'Sheltered' scenario with its default LMOE location, during game start the game is unable to find an LMOE shelter.  It gives me the following error:

```
DEBUG: Could not find starting overmap terrain lmoe
  Press spacebar...
```

And then what happens is my character and the friendly starting NPC get dropped off in the middle of wilderness.

Also, I have a map where this seems to happen every time, as opposed to merely occasionally, if anyone's interested.

**Comment by graysage1** [comment]
Looks like I duped this bug.  Closing it.

**Comment by BevapDin** [comment]
Reported by #8649 (and maybe others as well), but with more information there: it depends on the chosen city size.
