### ISSUE TITLE
New advanced inventory management menu duping items

### ISSUE THREAD

**Issue by SarahJohnson489** [CleverRaven/Cataclysm-DDA#12167]
New advanced inventory management menu dupes when moving items from vehicle storage via the all-9-adjacent squares category into the inventory

cataclysmdda-0.C-3035
804c458

1. Put junk in your trunk
2. Get on top of the vehicle
3. Hit / to open the menu
4. Set left to all-9-adjacent to bring up items
5. Set right to inventory
6. Move items
7. ???
8. Get 8 funnels from one funnel and a buttload of combat boots

**Comment by Coolthulhu** [comment]
#12137 should fix it, I think.

**Comment by SarahJohnson489** [comment]
Thank you

**Comment by Coolthulhu** [comment]
Closed by #12137
