### ISSUE TITLE
0.C-3035 newspaper pages clump up strangely in the 'i'nventory menu

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12171]
So I am playing 0.C-3035 804c458 because I am waiting for AIM fixes to land, and if this bug report is slightly outdated, I apologize.

Throughout my play I tend to pick up newspaper pages because they're essentially weightless and sometimes I like to throw one out in front of a Zed or an animal to start a defensive or offensive fire.  I can also convert them to paper and then to tinder to feed into my hobo stove.

I noticed I now have:

```
X 7 newspaper pages
P 14 newspaper pages
Q 15 newspaper pages
v newspaper page
```

Not only does this appear strange and arbitrary to me, but this is also chewing up inventory letters, which the way I play is a precious commodity. :)

**Comment by BevapDin** [comment]
Those are different item types, therefor they don't stack together.

There are six item types defined in data/json/items/newspaper.json that all have the same visible name "newspaper page", each of those types creates a different stack, one stack for the type "months_old_newspaper", one for "weeks_old_newspaper" and so on.

**Comment by graysage1** [comment]
@BevapDin I understand what you're saying as a programmer, but to me as a player, a newspaper page is just fire fodder, if you know what I mean.  As long as they're not interestingly differentiated in terms of their impact on the game, there probably shouldn't be 6 types of them to begin with.

**Comment by graysage1** [comment]
@BevapDin 

OK, I see now they all have different blurbs in their descriptions.  OK, I guess it adds flavor.  I'll close this bug.

**Comment by BevapDin** [comment]
And I agree on the player view, I just described the implementation, so if anyone wants to change it, they known where to start.

Technically, this could be "solved" by giving each item type a unique name, like "old newspaper page", "tattered newspaper page", "nearly destroyed newspaper page" etc. - a JSON only change.

**Comment by Zireael07** [comment]
@BevapDin: Good point. Drop me some ideas here and I could whip up a quick PR tomorrow.
