### ISSUE TITLE
More AIM Problems

### ISSUE THREAD

**Issue by KrazyTheFox** [CleverRaven/Cataclysm-DDA#12178]
Looked around and didn't see these reported yet. Apologies if they have been and I missed them. Tested on the latest experimental (cb7dabb).

1. Can't move items between two ground tiles using "move item/move item stack":
![untitled-1](https://cloud.githubusercontent.com/assets/3086301/7335354/353ea6d4-eb85-11e4-83a8-f89bfb2a038f.png)

2. Moving anything with charges/multiples moves one charge/item at a time. This results in duplicated items with one charge apiece:
![untitled-2](https://cloud.githubusercontent.com/assets/3086301/7335361/bb96e44e-eb85-11e4-8bed-16aa8ceb17f0.png)

**Comment by Coolthulhu** [comment]
Crap, I was pretty sure I specifically handled the latter. Looks like I didn't.

The former is obvious in retrospect and should be easy to fix.

> Looked around and didn't see these reported yet.

These are new. From my fix to even worse bugs.
