### ISSUE TITLE
Very minor: strange behaviors in the 'm'ap view (build 0.C-3076 cac8af7)

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12193]
These are probably too minor to bother fixing at the moment, but for completeness' sake I figured I'll make a note of them.

1. When moving the mouse around I notice that the blinking behavior stops for so long as the mouse pointer is in motion over the game window.

2. When I use 'O' on the 'm'ap view to toggle overlays, the game forgets about its blinking setting.  I think ideally if the 'm'ap is currently set to non-blink, then 'O' should respect that when returning to displaying the overlays.  And if the 'm'ap is currently set to blink, then 'O' should respect *that* as well, and upon returning to displaying the overlays, also restore the blinking state.

In my view these things don't significantly interfere with the game play.  They're just weird.

**Comment by DavidKeaton** [comment]
Having looked at the `overmap` code recently, the overlay bit does this:
1.) If `overlay` is set to on, then `blink` is used if enabled.
2.) if `overlay` is set to off, then `blink` is _also_ disabled.
3.) if `overlay` is off, then `blink` doesn't matter.

iirc this is what it does, but my addition to `overmap` was small, so don't take this as fact.

**Comment by graysage1** [comment]
I am going to close this issue.  It's kind of arcane and doesn't imo affect gameplay sufficiently enough to warrant the bother.  I figured if it's something easy and quick, OK, otherwise this goes to the bit bucket.  Thanks @DavidKeaton

**Comment by DavidKeaton** [comment]
No problem broski.
