### ISSUE TITLE
Suggestion: disassembling an electronic device with batteries shouldn't destroy the batteries

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12194]
Right now if you want to save the batteries, before you disassemble a flashlight or a radio, you have to first unload it manually.  It would be nice if I didn't have to unload anything prior to disassembling it.  That way, if something had battery charges in it, the battery charges would just drop to the ground as a battery stack along with the other items.

**Comment by KrazyTheFox** [comment]
The batteries should end up in your inventory. I just disassembled a few fully charged items and all the batteries could be found in my inventory afterward.

**Comment by graysage1** [comment]
Ah, you're right.  I was expecting the battery stack to be in the same place as everything else.  Got it.  I'll close this issue.
