### ISSUE TITLE
Sometimes attempting to eat meat pie gives a false warning that I won't be able to finish it all (0.C-3076 cac8af7)

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12198]
I don't know if I can duplicate this reliably, but now I have some charges of meat pie which when I try to eat warn me about not being able to finish it, when my actual hunger level is "very hungry."  So when I tell the game to ignore the warning and eat it anyway, after a few gulps of the meat pie, my hunger level decreased to only "hungry," which is what I'd expect.

**Comment by Rivet-the-Zombie** [comment]
What's your thirst? It gives the same warning if the food grants quench and you're already slaked.

**Comment by graysage1** [comment]
@Rivet-the-Zombie 

Doh!  That's what it was.  My thirst was slaked and looks like meat pie gives 5 quench.  I didn't expect meat pies to quench thirst.  OK, I guess this isn't a bug.  I'll close this thing.
