### ISSUE TITLE
Sea of Manhacks

### ISSUE THREAD

**Issue by AlchemistExMachina** [CleverRaven/Cataclysm-DDA#12196]
I was exploring a lab one time, and when i opened a door, literally 95% of the floor was covered in manhacks. There were three zombie scientists puking them out by the handful. They seemed to be attacking a mi-go behind a glass wall. killing the manhacks was a jiffy with my Granade-enhanced strength of 39, but there really should be a limit to the number of manhacks a scientist can spawn, it's game-breaking.

**Comment by Rivet-the-Zombie** [comment]
>there really should be a limit to the number of manhacks a scientist can spawn

This has already been addressed.

Ever since https://github.com/CleverRaven/Cataclysm-DDA/pull/12034 they can release three manhacks before they run out.
