### ISSUE TITLE
Cosmetic: e'x'amining (some?) vehicle tiles overwrites the info popup borders (0.C-3076 cac8af7)

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12199]
When I stand a few tiles away from a car and e'x'amine it, I notice that on the right side I see "Ou" overwriting the info popup's border, and on the left side "t" is doing the same to the border (it spells "Out"?).  And when I place the cursor over a car tile with lots of installed items, then the bottom of the info popup also gets overwritten with one of the car parts.

Interestingly, when I mouse over the same car tiles, the info popup is much better behaved.  Nothing is overwritten.  "Out" is printed on the right hand side without overwriting the popup border.  And to top it off, when I hover over a tile with lots of parts, the popup expands to accommodate the extra line at the bottom.  So this problem only happens when I use 'x' to look at the 'Car' tiles.

**Comment by illi-kun** [comment]
I'm not able to reproduce this issue, it looks fine for me:
![exam](https://cloud.githubusercontent.com/assets/5421954/14754876/4fdb117a-08ef-11e6-83d2-7e3c037a07ac.png)
