### ISSUE TITLE
AIM appears to double list entries in a vehicle when using ALL view in the left pane and 'd'ragged view in the right 0.C-3076 cac8af7

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12207]
I have a wheelbarrow to the north and a dragged vehicle to the east.  My left pane is set to 'A'll, and right pane to 'd'ragged (displaying '<V>').  Everything in the vehicle to the north appears to be double listed.  If I move over to a different vehicle and position myself to the south of it, again the same thing happens and everything in that new vehicle to the north is also double listed.

At first I thought this was an item dupe bug, but if I hit enter on one of the double listed entries, it just moves the item and both duplicate listings disappear from the left pane.  It doesn't seem to duplicate items in my limited testing.

**Comment by DavidKeaton** [comment]
This should have been fixed with my last update, and in testing I can't reproduce. Is this the case for you bud? :-) If so, feel free to close this issue!

**Comment by graysage1** [comment]
This doesn't appear to be possible to duplicate anymore.  It's probably fixed.  Closing.
