### ISSUE TITLE
Nomad gear is just superior to light survivor suit

### ISSUE THREAD

**Issue by Necrophobia** [CleverRaven/Cataclysm-DDA#12209]
Less resource required, lower skil requirement, higher storage, protection and warmth, without any serious disadvantage. I doubt this is intended. 
Something not really related - why did nomad cowl have 20 base encumbrance?

**Comment by graysage1** [comment]
Warmth is a huge disadvantage in the summer and I believe there is also a difference in environmental protection.

**Comment by ejseto** [comment]
Head encumbrance has no effect other than to prevent you from putting on other encumbering headgear. It has 20 encumbrance to prevent precisely that.

**Comment by DeNarr** [comment]
Nomad Gear: 
Warmth 40
Encumbrance 5 (fits)
Armor 18/18
Environmental Protection 1 Storage 80


Light Survivor Suit:
Warmth 15
Encumbrance 5 (fits)
Armor 9/15
Environmental Protection 10 Storage 30

So yes, Nomad gear is better to wear if you don't care about it being too hot, and you don't need the environmental protection. The environmental protection is a large aspect of all the survival gear, and I think it is okay for other gear to be better in other aspects. There should not be one "best" gear for all situations.

**Comment by Rivet-the-Zombie** [comment]
Also keep in mind that survivor armor has the ````STURDY```` flag whereas nomad gear does not, so while the light survivor armor may protect you less, it also requires less frequent repairs.

**Comment by Necrophobia** [comment]
The part about warmth is very true indeed, -12 speed (and increased thirst, if I remember it right) could be quite nasty during summer. I stand corrected. 
As for environmental protection and STURDY flag... Well, I do have noticed it, but I personally believe this depends on the playstyle. Anyway, point taken since I'm probably a little bit too prepared. OK, now come to think about it, way too prepared really. :(
The biggest problem I have is they are too protective. Even leather body armor have less protection. While I do not believe survivor gear should be some sort of no-brainer, I do find it hard to believe that you can build something more protective than it (which requires kevlar) with nothing more than rag and leather (and a utility vest, which is also made of cotton). 
As for the cowl - well, they also cover face and mouth. So, game engine limitation like I thought?
Thank you all for your reply.

**Comment by Rivet-the-Zombie** [comment]
>The biggest problem I have is they are too protective. Even leather body armor have less protection. While I do not believe survivor gear should be some sort of no-brainer, I do find it hard to believe that you can build something more protective than it (which requires kevlar) with nothing more than rag and leather (and a utility vest, which is also made of cotton). 

A very good point. We can probably stand reduce the protection values a bit.

**Comment by Marrim** [comment]
Coverage. 100 wins over 95 any day.
And why does nomad gear have 5 enc? It was 3, then was reduced to 2, then the values got multiplied by 10 so it should be 20.

**Comment by Rivet-the-Zombie** [comment]
>And why does nomad gear have 5 enc? It was 3, then was reduced to 2, then the values got multiplied by 10 so it should be 20.

I don't imagine it's the only item to have suffered a weird encumbrance change during the changeover to the x10 system. I've addressed it in my tweak PR.

**Comment by Marrim** [comment]
I see now. Before x10, nomad gear was 2 enc and light survivor suit was 1, so the problem wasn't there. I wasn't playing for quite a while :)

**Comment by illi-kun** [comment]
Rivet's PR is landed, so what is the reason for keeping this issue open?
