### ISSUE TITLE
Minor suggestion: do not generate cash cards with less than 1000 cents

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12216]
I've been running around a bit with cash card autopickup and now I have cash cards with values:

```
cash card (1)
cash card (2)
cash card (5)
cash card (6)
cash card (9)
cash card (71)
cash card (89)
cash card (3472)
cash card (4896)
cash card (53468)
```
I suggest something very simple: why not leave cash card generation as is, except if the value of the card that's about to be dropped is less than 1000, don't drop anything.

There will be only slightly less money in the game then, but much less clutter, imo.

**Comment by i2amroy** [comment]
You can always use ATM's to transfer money to a single cash card. That said I think probably the best way to address this would be to just give cash cards the ability to transfer money directly from one to another, since it seems like a hypothetical cash card should have something that works equivalently to me paying you directly without both of us needing to go to a bank every time I owe you a buck.

**Comment by graysage1** [comment]
If I could have a cash card that automagically vacuumed the values of other cards and nuked them from the world to decrease the save json size, that would be cool.  It would save me the trip to the ATM too.

I like the idea of cash cards and I know I can use ATMs at gas stations to transfer everything in one fell swoop, but it still leaves behind these cards.  I figured the less of them in the world, the better.  Some of the cards have so little money on them, they just clutter the memory, imo.

In any case, this is a very minor thing.  If it's anything more than 1 "if" statement somewhere, I think it's not worth the effort.

**Comment by vache** [comment]
Once you combine them all onto a single card, I think you can cut them up for plastic chunks.

**Comment by graysage1** [comment]
> I think you can cut them up for plastic chunks.

I haven't been very lucky getting chunks from them.  I usually just burn them all to eliminate waste. :)

**Comment by kevingranade** [comment]
Clutter, ambiance, potato, potato
