### ISSUE TITLE
No Acid Prompt

### ISSUE THREAD

**Issue by KrazyTheFox** [CleverRaven/Cataclysm-DDA#12219]
Not sure if this one is intentional or not, but there's currently no prompt when entering an acid field regardless of traits or gear. I'm also not really sure how much of an issue this actually is given that acid is a little weak right now. Unless I'm running around barefoot it doesn't seem to do much.

**Comment by DavidKeaton** [comment]
acid could do with a nice buff, possibly it could erode equipment and it's env protection?

**Comment by Rivet-the-Zombie** [comment]
> possibly it could erode equipment

It already does, it's just not a very great system.

**Comment by DavidKeaton** [comment]
Well it does erode boots and all if walked in, does it also do damage to all other equip when splattered with it?

**Comment by Snaaty** [comment]
We could use a system utilizing the effects, that add (body part) - covered in acid, or something like that. (Sorry, for being OT.)

**Comment by DavidKeaton** [comment]
you are referring to `effects.{h,cpp}`?

**Comment by Snaaty** [comment]
I think it was fully jsonized by iamroy at some point, so I might even have a look at it. Although checking for equipment/damaging it, if not damaging the body part is probably not doable only via json.

**Comment by DavidKeaton** [comment]
yes, he extended it to json, but you'll have to add a custom effect, as iirc it's mostly medicinal and ailment type stuff.

**Comment by KrazyTheFox** [comment]
Fixed in #12392
