### ISSUE TITLE
AIM fails to show tile [5] under a certain condition (condition inside) 0.C-3076 cac8af7

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12212]
To duplicate this, 'G'rab a wheelbarrow first.  Then setup AIM with the 'd'ragged vehicle in the right pane, and 'A'll in the left.  Then let go of the wheelbarrow by hitting 'G' again, and go stand directly over some items on the ground.  Curiously if you stand right over them, they won't show.  But if you stand one tile to the side, they will show up as expected.

**Comment by DavidKeaton** [comment]
interesting.. gonna see if I inadvertently fixed this bug with my update branch.

**Comment by graysage1** [comment]
Nice @DavidKeaton .  What about the other new AIM bugs I logged?

**Comment by DavidKeaton** [comment]
I have to look at them all, I just started coding about 30 minutes ago. :-P

**Comment by DavidKeaton** [comment]
Can't reproduce this, so I am assuming I got it in the flurry of fixes on my current AIM fix branch.

**Comment by graysage1** [comment]
>Can't reproduce this, so I am assuming I got it in the flurry of fixes on my current AIM fix branch.

Are you testing on your private build or the build I mentioned in the issue?

**Comment by DavidKeaton** [comment]
the branch with the next wave of fixes.

**Comment by graysage1** [comment]
I cannot duplicate this bug anymore with the latest AIM PR merged.  Closing this.

**Comment by DavidKeaton** [comment]
right on! lemme know if you find anything else!

**Comment by graysage1** [comment]
@DavidKeaton Will do.  I found one minor bug #12433.  So far things look good. :)  Hopefully I will run across another vehicle soon so I can test one more old bug.
