### ISSUE TITLE
Speed effect display bug.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#12223]
The effect name displayed in the speed display of the @ screen is always the name of the comedown effect for whatever chemical is boosting your speed.

Example: Consume some methamphetamine and the speed display on the @ screen will read ````Meth comedown +90%```` when it should read ````High on Meth +90%````.

**Comment by BevapDin** [comment]
Fixed by #12226

@OzoneH3 The "Fixes: #12223" in your PR did not work because of the `:` in it. "Fixes #12223" should work.
