### ISSUE TITLE
Minor UI Request: Show "it layers easily" in layering screen

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#12227]
Just like the layering screen shows "it fits you well", "it is waterproof" etc, it should show you if an item layers easily, that would be very helpful.

**Comment by ejseto** [comment]
From what I can tell, "layers easily" isn't actually a thing. It describes 2 separate things combined, namely, an item that is both "FIT" and has 0 encumbrance or less. Since both of those properties are displayed and "layers easily" doesn't actually have any effects outside of those of its components, there wouldn't be a point to displaying that.

**Comment by DavidKeaton** [comment]
it would be useful once a layering overhaul is added (was mentioned some time ago)

**Comment by molkemon** [comment]
ejesto: no, this is not true at all.

first of all, layers easily applies ONLY if an item has 0 base encumbrance. e.g. if you have a 5 base encumbrance item and then fit it, which would make it -5 encumbrance, it does NOT layer easily. Additionally, if you enhance a base 0, easy layering item with like leather paches or kevlar via the tailoring kit, it will LOSE it's layers easily status.

Most importantly though, layers easily is a VERY IMPORTANT property, as it will allow you to add this item on the respective layer without incurring additional layering encumbrance penalty. (e.g. wool socks DON't layer easily, but when they are fitted, they have an encumbrance of less than zero, so 0. normal socks though have a base encumbrance of 0, so they do layer easily. So if you wear wool socks AND normal socks, you will still have 0 encumbrance on your feet. However, if you wear 2 pairs of wool socks, which both have 0 encumbrance when fitted (but not 0 base encumbrance), you will get a +10 layering penalty. )

**Comment by ejseto** [comment]
A better solution would be to just show base encumbrance as well as effective encumbrance and forego useless flowery descriptions.

**Comment by molkemon** [comment]
I agree that the crafting menu should show not only effective encumbrance after fitting, but also base encumbrance, but again, it's not just a flowery description. An item with base encumbrance of 0 is infinitly more useful than an item with effective encumbrance of 0 or below.

**Comment by ejseto** [comment]
It is flowery. "Layers easily" shows up one time. It's a description of a specific combination of other properties. It is not referenced in the encumbrance code. That would be like adding "This is a really powerful bullet!" to the description of any ammo with > X damage. Well no kidding, I can see that it is. Same as (if base encumbrance was shown like it *should* be) "layers easily."

**Comment by kevingranade** [comment]
layers easily is gone now.
