### ISSUE TITLE
Snippets are not being displayed properly in "V"-mode

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#12228]
WHat it says on the can. Find several pieces of newspaper, press V, change the selection between them, and it will always show the same text. I assume this is due to snippet stuff. 
##

**Comment by BevapDin** [comment]
> I assume this is due to snippet stuff.

No, at least not directly. The game stores an example items for each stack and displays the information from that example items when you select the stack. The example items is usually the first item of that type the game sees around, all other items only increase the stack size.

**Comment by Snaaty** [comment]
Oh, okay, I guess it only really matters for snippet stuff, because otherwise the description would be identical, right? I have no idea whatsoever, how to fix that, but it's also not super urgent.

**Comment by Leland** [comment]
#19232 notes the following:

>When there's more than one of a particular item around you, you can use the left and right arrow keys to scroll through all of them (the entry looks like `[1/38] (38) cash card`).However, the window at the bottom (where charges, price, weight, the item description, etc are shown) will always have the same information as it did for the first item. Similarly, if you try to examine any of the 38 items via `e`, it will show the first item's information instead.
