### ISSUE TITLE
Searching on the over'm'ap limits the scope only to a fragment 0.C-3083

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12234]
Build 350c5fe.

This might be an intended behavior for the sake of optimization, however, there is no indication to the player that searching is not going to include every discovered territory.

So when I search on the 'm'ap view using '/' for a string "Base ", which uniquely IDs the notes on my bases, what I find depends on where my cursor currently is.  If it's further south on my map here, it searches that quadrant or submap (or whatever you call it) down south.  If I manually move the cursor back north where I started the game, '/' can then find the two bases there that otherwise aren't found.

So either '/' should search all discovered territory, or, there should be an indication to the player that this is going to happen so there is no surprise.  (Edit: Or a 3rd choice, maybe let the player tell the game how widely to search?)

**Comment by BevapDin** [comment]
This is semi-inteded, see https://github.com/CleverRaven/Cataclysm-DDA/pull/9292#discussion_r18161565

> searches that quadrant or submap (or whatever you call it)

It's called an "overmap".

**Comment by graysage1** [comment]
@BevapDin I was talking about a city-sized piece of the map, not the whole thing.  So if that little piece is called overmap, then what do you call the map that's comprised of those little pieces?

**Comment by vache** [comment]
I don't think that has a name.  Game world?  World map?

**Comment by graysage1** [comment]
>I don't think that has a name

I see.  That's good to know.  I wouldn't have guessed that's what the word "overmap" meant.

So, I see that it's "semi-intentional."  I guess it makes no sense to keep this one open then.

**Comment by BevapDin** [comment]
> I wouldn't have guessed that's what the word "overmap" meant.

Well, that piece of data is represented by a C++ class of that name, so it makes sense for those reading and understanding the code. But everyone else is most likely not aware of it.

In the map view, you see at the bottom right the coordinates, something like:
`LEVEL A, B'C, D'E`
A is the z-level 
B,D are the coordinates of the overmap - when you scroll around, they rarely change, and when you start a new game they will usually be (0,0).
C,E are the coordinates of the terrain (e.g. house, forest, shop) within the overmap.

It's probably supposed to look like geographic coordinates (http://en.wikipedia.org/wiki/Geographic_coordinate_system), as with degrees, minutes and seconds

**Comment by graysage1** [comment]
@BevapDin Thank you for that detailed explanation.
