### ISSUE TITLE
"V" menu displays items from different locations in the same stack

### ISSUE THREAD

**Issue by i2amroy** [CleverRaven/Cataclysm-DDA#12231]
Example, I walk into a room with 2 t-shirts in one dresser nearby, 1 on the table right next to me, and 4 in the closet on the other side of the room. If I open the "V" menu it will display "t-shirt[7]" with the location being the table right next to me.

This could potentially be ok to display more data in the same space, but if that's what we're going to we need some button you can press to "split" the stacks and allow the players to view individual locations should they need that information.

**Comment by kevingranade** [comment]
Not saying it's an invalid issue, but AFAIK there is no non-cosmetic data
to look at here, just the different descriptions.
Also, unless it's an ammo or similar, it is actually a stack of items, so
e.g. if you dropped one, the description of the stack in your inventory and
the item on the ground should be different.

**Comment by i2amroy** [comment]
My problem isn't the cosmetic issue, it's the location one. I could have 1 gold bar sitting on the floor next to me and 200 gold bars through the laser field of death and the V menu will happily tell you that all 201 of them are sitting, accessible, on the floor next to you.

Basically when I use the V menu I'd like to have the option to be able to know where everything I'm seeing actually is, instead of just where the closest one of each type is located.

**Comment by Coolthulhu** [comment]
As far as I recall, you can scroll stacked items with left/right.

**Comment by i2amroy** [comment]
>As far as I recall, you can scroll stacked items with left/right.

It only seems to be this way with some things (maybe linked to counting by charges?). 2x4's or grenade hacks for example, are scrollable, while nails or splintered wood is not.

**Comment by DavidKeaton** [comment]
have the x's drawn go to all items in said stack? or possibly highlight all items with `*_hi()`?

**Comment by kevingranade** [comment]
Nails are an ammo and are probably acting odd because they're weird
pseudo-items like BevapDin mentioned that just hold a count of how many of
them there are, splintered wood might have had the same thing applied to it
because it is considered 'clutter'?
