### ISSUE TITLE
Flock of bats in the middle of a field in the middle of the day

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#12240]
I just came across a colony of bats in the middle of a field at 7:36pm on Spring day 6.  Closest forest is 5 world tiles away, no caves nearby.

**Comment by sparr** [comment]
7:36pm is not the middle of the day. Day 6 with 17-day seasons is the equivalent of day 32 of 91 in real world seasons. Day 32 of spring in the real world was about a week ago, and the sun set in Boston at 7:32PM. A flock of bats during twilight/dusk is perfectly normal.

The only way this is vaguely unrealistic is the lack of forests or caves nearby, but the game only represents caves big enough for a human to climb into. The presence of rock fissures is entirely abstracted away. Ditto bats in building attics.

I'm gonna say there's nothing wrong here.

**Comment by Xpyder** [comment]
sounds reasonable.  My Internal Chronometer prevents me from checking where the sun is so I was going based on my sight radius to judge whether the sun was still up

**Comment by sparr** [comment]
A more realistic sight radius over time curve for daylight hours and dawn/dusk would be pretty nice...

**Comment by kevingranade** [comment]
The lighting curve for dawn/dusk is VERY rudimentary, code or references to
formulas for calculating it would be appreciated.
