### ISSUE TITLE
'fedora' is categorized as a tool instead of clothing 0.C-3090

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12248]
Build da97264.

**Comment by Rivet-the-Zombie** [comment]
Mumble mumble something about tools who wear fedoras.

No flamewars, please; I kid.

**Comment by kevingranade** [comment]
This was originally because it needed to be a tool to enable the 'hat tip'
action, that can be cleared up now.

**Comment by DavidKeaton** [comment]
I'll have you know that retort retort flagrantly unfounded opinion regarding topic of which I'm no master, nor even slightly versed.
