### ISSUE TITLE
Start locations after evacuee edit

### ISSUE THREAD

**Issue by MIC132** [CleverRaven/Cataclysm-DDA#12246]
Since evacuee scenario was edited, few locations that it enabled are now impossible to start in:
grocery store, gun store, garage, pawn shop, bank, military surplus, furniture store, library and lmoe.
(cabin can be achieved through ambush scenario).

Shouldn't those locations be added to some alternative scenario? Or maybe just the description of evacuee should be edited to reflect the possibility, and the locations added back..

**Comment by Coolthulhu** [comment]
LMOE has its own scenario (or two). Missed covers the rest.

**Comment by MIC132** [comment]
Which ones start you in lmoe? Sheltered?
Also I always thought missed was only for house. If it really covers all
others then it's ok.

**Comment by Coolthulhu** [comment]
Yes, sheltered. It also forces a winter start.
I thought there was an alternative LMOE scenario, but looks like it didn't get in the game.
