### ISSUE TITLE
Can't put on a hood when already wearing a helm, but it works vice versa

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#12257]
I wear a heavy balaclava, a heavy survivor helmet, and helmet netting. Now I want to wear a light survivor hood aswell, but it tells me "you can't wear another helmet".

Taking off the balaclava and the netting still results in the same error message, however, when i have balaclava and helmet netting on, and remove the heavy helmet, and then put on the hood and then put the helmet back on, it works.

**Comment by drbig** [comment]
And that makes perfect sense. For reference see: #12938.

**Comment by Barhandar** [comment]
Except it doesn't, because you can adjust the layering. Also, hood could be large enough to be worn over the helmet.
