### ISSUE TITLE
NPC tries to tunnel through vehicle to board

### ISSUE THREAD

**Issue by AlchemistExMachina** [CleverRaven/Cataclysm-DDA#12252]
The NPCs seem to be coded to try to get on a boardable part of the vehicle by going in a straight line, and that involves smashing a hole in the car sometimes. They also don't favor seats over aisles and boxes, and also block other NPCs from boarding. It would probably make sense to have them go around the car to a door to board, prioritize seats over aisles over boxes, and perhaps ask the player if they should board?

**Comment by mugling** [comment]
Since this issue was opened NPC's now correctly board vehicles and take a seat
