### ISSUE TITLE
Center view on remote driving vehicles

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#12251]
As the title says, mostly because controlling from  remote vehicles from far away is not very user friendly right now.
##

**Comment by Chase-san** [comment]
While we are at it, have some way to look through the camera's on the remote vehicles. So I can send that automated street sweeper out to mow down and collect the drops of zombies for me.

**Comment by Leland** [comment]
Looks like discussion's been stalled on this for years now. Closing.
