### ISSUE TITLE
Water friendly does not work at all 0.C-3090

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#12256]
First noted on helmet netting: even though it's water friendly now, wearing it on the outermost layer will still cause wet penalty to accumulate up to 20. 

Switching the layering on my arms a bit, so a water friendly item was outermost (elbow pads) rather than a water proof item (survivor trenchcoat) also started to accumulate wet penalty. 

Conclusion: The water_friendly flag does not only does not work (as in it does not give you a morale boost), it will also cause you go gain a morale penalty, just like normal non-waterproofed items. 
##

**Comment by Frost-wood** [comment]
For water-friendly items... EVERYTHING must be water-friendly to get the bonus.

**Comment by molkemon** [comment]
Ok, but should it still at least not give negative morale penalty when worn?

**Comment by Zireael07** [comment]
The penalty comes from other items, not water-friendly ones.

**Comment by molkemon** [comment]
No, that's my point, it DOES come from water-friendly ones. 

On my head, I wear a Heavy Survivor helmet, which is water proof, and a Helmet Netting, which is water friendly. If I put the helmet as the outermost item in the layering screen, I do not get a wet penalty. If I put the helmet netting as the outermost item, I do get the wet penalty. Same thing with arms, where I wear survivor trenchoat (water proof) as outermost item), and elbow pads (friendly) below it. If I switch the layering, I get wet penalty.

**Comment by Coolthulhu** [comment]
It probably shouldn't depend on layer order.

The current system is quite simplified from the code side (which results in complexity everywhere else): water friendliness doesn't matter at all unless all your items on all the body parts "hit with water" are water friendly. This means that getting your feet wet could invert the morale penalty you got from standing in the rain if all you wear on your feet is water friendly.

A combination of water resistance and water friendliness won't work. You need ALL items to be water friendly. Water resistance is a bit more forgiving: you need all items on current body part to be resistant not to have it get wet (deep water will still get you wet).

So water friendliness does work, it is just rather complex and needs a rework.

**Comment by kevingranade** [comment]
I'm not sure about "shouldn't depend on order".  Water friendly should check if it's next to the skin, and water resistant should prevent lower layers from getting wet.
I agree it could use a rework though, what I'd like it to do is have clothes track how much water they have on them, and soak through to lower layers over time, the wet penalty kicks in once the innermost layer is wet.

**Comment by Coolthulhu** [comment]
> I'm not sure about "shouldn't depend on order".

I meant as in "what our current implementation does". Eventually yes - it probably should.
Though probably not before layer order is enforced, or at least soft-enforced by giving layering penalty when the item order is not correct.

**Comment by kevingranade** [comment]
Sounds like we're in total, irreconcilable agreement.
My preference is for the 'out of order' layering penalty as enforcement.  I
think that was also the consensus the last time it came up.
