### ISSUE TITLE
Idea: Balance Bionics using Limb Capacity

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#12260]
I've noticed that once I get a few bionics and my skills up I'm just eating every new bionic I come across and getting super crazy powerful during the midgame (years 2 and 3) when I would expect this to be happening more near the endgame.

What about making bionics take a certain capacity, having each limb having a set capacity, and having the final floor in labs (and military bunkers if they get expanded) having a single instance of a special "Cybernetic Limb" Bionic that if successfully installed destroys all installed bionics from that limb but removes the capacity limit for it?  You could even divide them up so the extremities are in labs and the torso one is in a heavily guarded military bunker to give each play style an opportunity while extending the goals during the midgame (combat vs. environmental challenge)

In addition to adding another game lever we can tweak to maintain balance, and providing a compelling exploration goal during the midgame (once you have your food and fuel needs met); I feel this would force you to make interesting tradeoffs early on balancing limb capacity, and picking whether  to install a valuable mod right away, or wait until you have the cybernetic limb for that slot or risk not finding a replacement.

**Comment by graysage1** [comment]
>I've noticed that once I get a few bionics and my skills up I'm just eating every new bionic I come across and getting super crazy powerful during the midgame (years 2 and 3) when I would expect this to be happening more near the endgame.

I play with 30 day seasons.  The standard is 14 days.  So, "year 2" is a big vague.  14*4 is only 56 days.  30*4 is 120.  56 + 56 = 112 (year 3), and 120 + 120 = 240 (year 3 in my style of play).

Have you looked at #11781?  How is your proposal different?

**Comment by Parahacker** [comment]
Hmm. I'm not sure, but I think I like this idea. The endgame-style infinite capacity limb, that is. I've seen capacity restrictions proposed before, and they worried me that future games won't let you make a Big Damned Survivor the way we can now.

**Comment by Xpyder** [comment]
@graysage1 I had not seen #11781 I did a search for Bionic and Capacity but I hadn't considered Layer as a similar idea.

I do like the ideas presented therein, possibly add the cyborg parts instead of the sockets tivec was talking about; the exchange being infinite bionic capacity in for losing all of your mutations in that body part.

This would create an actual tradeoff between being a super powerful cyborg or being an evolved monstrosity end game, while also being a lot less fiddly as sockets would net the same endless capacity in effect but require you to uninstall and reinstall everytime you want to change stuff.  Fiddly is fine early on when survival is a big issue but later on you typically want to move away from annoyances and direct players focus to soving more interesting problems

**Comment by graysage1** [comment]
I like the ideas of limiting and organizing bionics (right now they just go into a pile of sorts, where you can change their assigned letters, but short of removing and reinstalling everything there seems to be no way to organize how the bionics screen looks).  However I don't like the idea of limitless bionics limbs.

Installing bionic interfaces which then provide modular sockets for swappable parts, that makes a lot of sense.  It doesn't have to be fiddly either, because the game can keep track of bionic sets, and let you swap the sets at a press of a button or two.

**Comment by Xpyder** [comment]
What is it about the limitless limbs that you don't like?

As for swapping not being fiddly, I don't know if you've ever played a character with Hoarder and Pack Rat together before, but try it sometime and see how you end up feeling about needing to swap items later on.

For the IRL logic if bionics had reached that point in the game it probably wouldn't be as hard to uninstall them as it is currently.

**Comment by graysage1** [comment]
>What is it about the limitless limbs that you don't like?

Mainly that they're limitless. Aren't we trying to make people deal with some tradeoffs?  It sounds like once you install those limbs, that's it, we're back to the old style of bionics.  Unless I misunderstand you.

At least with bionic sets, there is retooling speed (it won't be instant) and you have to prepare the right set in advance of when you'll need it.  So if you're headed under ground, you may want a different set than for the forest.

>For the IRL logic if bionics had reached that point in the game it probably wouldn't be as hard to uninstall them as it is currently.

The tissue-non-tissue interface is the trickiest thing imo.  Once we figure out a way to get nanofibers to move toward the neurons in just the right way to connect, I still don't think we'll be uninstalling that stuff any time soon, at least, not gracefully.  You'll have to damage some nerve tissue and wait for it to regrow if you want to tear out the interface.

But if we can separate interface from the bionic, it's much more reasonable.  Think about clinics where they keep patients on long-term IVs.  How do they do it?  Well, they don't want to poke you with a needle 100's of times every day, so they install a port into your vein.  Then they install a separate needle into the port.  That port is basically a very primitive bionic interface.  So we already have the idea of an interface in use today.

**Comment by DeNarr** [comment]
I would say that if we are going to add a limit to the number of bionics we can have, that she should make it where we can install multiple of the same bionics (as long as it is under that limit). So maybe we can only have 3 things in our legs for example: that could be torsion joints, leg armor, and muscle augmentation, or it could now just be 3 things of leg armor.

**Comment by Xpyder** [comment]
@graysage1 
"Mainly that they're limitless"
The sockets are effectively limitless too, the main difference being that with the sockets some mods can be set to not be interchangeable, and I think that could be a reasonable approach.

As for tradeoffs, I'd suggest that if we were to go with the replacement limbs that it would deny any mutations in that limb, creating an exclusivity between lots of powerful bionics and lots of powerful mutations.  I would argue though that this could be applied to the socketing mechanic as well, as could the difficulty in finding the parts (1 per lab/military base forcing more exploration and extending the midgame).  And with the socketing there's the possible addition we could make a "Socketing compatible modification" mod you could apply to existing bionics that haven't been installed yet.

If we can find a reasonable way to group mods to make the swap out easier, making "sets" as it were, then I think the socket could work better and provide more options, provided it's not too difficult to code.

**Comment by Xpyder** [comment]
Shifting those ideas over to Tivec's suggestion as upon consideration I do like the some of the additional control the sockets would provide.
