### ISSUE TITLE
Early game balance suggestion: why not allow "tainted bone" in addition to "bone" for stone knives?

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12262]
I found at least one scenario (RBD w/ hordes) where it is sometimes surprisingly hard to get a stone knife going, but for a reason that seems somewhat artificial to my mind.  Unless you plan on eating the bone, the fact that it's tainted shouldn't cause much of a problem, right?  Tainted bones are already allowed in armor.

So I suggest adding "tainted bone" to the list of handles that a stone knife can use.  Right now it can use only "bone."  That way, if you get lucky and butcher a petty early zombie with a sharp rock (-50 butchering), you can upgrade yourself to a stone knife if you got a tainted bone to drop.

**Comment by Rivet-the-Zombie** [comment]
If I had to guess, I would say it's for the same reason you can't make a bone needle out of a tainted bone; they're too fragile for that sort of application.

**Comment by graysage1** [comment]
Makes sense, but how do you explain tainted bones in armor?  When I do a search for "c:tainted bone" in the fabrication screen, I see lots of formulas where strength is required.  They should then be taken out of the armor formulas and only be used for the superglue I guess?  My proposed change is consistent with how the game is currently setup.

**Comment by graysage1** [comment]
Example: http://cdda-trunk.estilofusion.com/bone_tainted/recipes/CC_ARMOR

**Comment by graysage1** [comment]
Also, if tainted bones are weak, the Zeds themselves would be weak as well.  Bone strength is essential for musculoskeletal strength.  The Zeds in the game are very tough, and show no indication of fragile bones.

**Comment by Coolthulhu** [comment]
> The Zeds in the game are very tough, and show no indication of fragile bones.

They are far more fragile than NPCs or the player.

**Comment by graysage1** [comment]
>They are far more fragile than NPCs or the player.

Only at the start of the game, and even then, only if you don't use "wanter spawns: true." :)  In which case, late-game Zeds seem to spawn instantly.

**Comment by graysage1** [comment]
Do Zeds always have fewer HPs than player characters?  That would be an indication of them being weaker in the musculoskeletal department.

**Comment by graysage1** [comment]
Another indication of Zeds bones being weaker would be if Zeds constantly got broken limbs.

**Comment by Coolthulhu** [comment]
> Do Zeds always have fewer HPs than player characters?

Yes. Even if you only consider head and torso, player has about 160 hp. Zombies with hp comparable to that are significantly larger than the player.

They get stunned a lot even by unarmed hits and human punches are enough to kill them.

**Comment by graysage1** [comment]
@Coolthulhu Good points.  Then how do we explain tainted bones in armor recipes?

**Comment by Coolthulhu** [comment]
Bone armor is more like stacked bone, possibly treated in some way (maybe add boiling-related elements to the recipe?). Individual bones don't need to be very dense.
With tools, each bone used needs to be good enough to be sharpened.

**Comment by graysage1** [comment]
>possibly treated in some way (maybe add boiling-related elements to the recipe?)

I was going to say, cutting and tailoring were the only qualities it required so far.

**Comment by graysage1** [comment]
Looks like this proposal was headbutting with game lore, but game lore was wearing helmet +10, and the proposal lost.
