### ISSUE TITLE
Let's talk about roving horde balance. (wander spawns)

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12263]
This issue is related to #12064, but not identical.

I personally like the idea of some kind of dynamism and renewal in the world, and one attempt at it is somewhat widely agreed to be a failed one, and that's the so-called "dynamic spawn" mode (In the world options, "Static spawn: false").

The shiny and new way forward, if I understand correctly, is to use the so-called "hordes."  In the world options that's "Wander spawns: true."  Please correct me if I am wrong.

So I've been playing RBD with wander spawns recently.  I seem to have learned how to fairly reliably get an RBD character going on pure static spawn mode.  But with wander spawns... oh boy.  It's like I am not playing the same game.  The difficulty level is *not even slightly close*.

So when the spawn factor is set to 1.0 (I assume it influences how hordes work, but I don't know for sure.) the number and the ferocity with which the spawns happen is, in my opinion, ridiculous.  I look outside the window on my very first night and I see nothing less than say 50 Zeds, many of which are very advanced versions like the mid or end-game torso-piercing Zeds, Masters, all kinds of brutes and hulks and what have you.  Not only is there an insane horde outside the window, but it seems it's constantly, constantly spawning right next to me, for seemingly no reason whatsoever.  I am sure there is of course a programmatic reason for it, don't get me wrong.  I'm speaking from player's POV here.

So for now I changed the spawn rate to 0.2 to see how it goes, but so far the difficulty doesn't appear to be reduced substantially because those roving Zeds still seem to be attracted to me like bees to honey or (less flattering) flies to horseshit.

In my opinion the wander spawns are not quite ready for prime time.

I think there should be a few things done to balance this thing out.

1. The spawn code should not have magical ESP about player's location.  I even tried taking 'light step' and 'inconspicuous' to try to limit the noise of my character, because I've heard the spawn is noise-based, but it didn't perceptibly change anything in my favor.  The wandering spawns were still insane and still seemingly ESP-knowledgeable about where my character was.  So let's first talk about doing away with the ESP of wander spawns.  Wander spawns should be driven by their own internal prerogatives that have nothing to do with the player per se.

2. The advancedness (for lack of a better term) of the Zeds in wander spawns seems to be absurd.  There appears to be no early-game break when playing RBD + wander spawns.  I don't expect to find middle or late game jumping Zeds that pierce the torso right on day one.  Those things are dangerous even when fully armored with all skills above 6, never mind a starter character.  Can the wander spawns be made to respect the general progression of difficulty that's evident in the rest of the game?  Or maybe the nastiest and most dangerous Zeds should be rare to begin with, regardless, beginning, middle or end of the game.  Or maybe the nastiest Zeds should be found in specific locations such as labs, military bunkers and so on.  That way if you just want to raid or escape a nearby city on your first week or two of gameplay, the danger level should be surmountable by a good player.

I find that the combination of 1 and 2 makes the gameplay unfun.  What does it matter how skilled I am if Zeds know where I am no matter what?  It feels like the game is cheating here.

In one game I was able to outrun the cloud of flashing green Zs on the 'm'ap because I found a functioning police car, but it's like they are coming for me anyway.  After 30 minutes of trying to grind some skills in the forest, what do you know, the flashing Z's are moving in full force. :(  I have a sense the game is purposefully moving the Z cloud toward me.  I could be wrong, but that's what it feels like.  It feels like there is no possibility of any respite from madness.

I like dynamic and renewing behaviors to keep the world fresh and relevant, but there has to be some reason to it, imo.  Throwing an endless stream of Zeds at the player doesn't seem to be a good way to go forward.

**Comment by graysage1** [comment]
In short, I think it would be better if wandering spawn hordes minded their own business and only targeted my character if I interfered in their business.  And it would be better if the hordes were not so highly advanced at the start.  As well it would be a good idea to lower the spawn values relative spawn factor.  What is now called 1.0 should probably be called 20 on a scale of 1 to 50.  What I am trying right now as 0.2 should be called something like 5 on the same scale.  In other words, the scale seems to be out of whack.  1.0 suggests a starter, default challenge, but doesn't feel like one.

**Comment by Coolthulhu** [comment]
The problem is, hordes can't despawn. Once they're on your map, they stay there.

When voluntarily despawning zeds and monster footsteps get in, hordes will act more sensibly.

**Comment by kevingranade** [comment]
'Wander spawns' are in fact not ready for prime time, that's why they
default to off.  I'm planning on scrapping most of the implementation and
starting it over, it's a very quick and dirty way to get some monsters
moving around at large scale, but the entire approach is unworkable.
The replacement I have in mind will simply have zombies and such moving
around on the map, that's it.  The dynamism as far as population is
concerned will come from zombies upgrading over time.

**Comment by graysage1** [comment]
@kevingranade very cool. :)  I'm looking forward to it.  I vote to close this issue then.
