### ISSUE TITLE
The game says "moving past X is slow" even with the parkour expert trait.

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12268]
Parkour expert trait works as expected, but the game still says something like "Moving past this shrub is slow."  Moving past shrubs would be slow in most cases, but not when you have "Parkour expert" trait.

**Comment by graysage1** [comment]
Looks like actually it's still slower even w/ parkour.

**Comment by DavidKeaton** [comment]
sounds like a sign issue iihtg
