### ISSUE TITLE
Mouth encumbrance drains stamina when walking

### ISSUE THREAD

**Issue by Rhonzie** [CleverRaven/Cataclysm-DDA#12279]
Tested with a gas mask and character can't walk far without getting tired.
##

**Comment by Rhonzie** [comment]
When you reach 1 mouth encumbrance it would drain your stamina even if your just walking. Maybe 2 or 3 mouth encumbrance should be the threshold before any stamina draining should happen when walking.

**Comment by Coolthulhu** [comment]
You probably have layering penalty or some trait that penalizes walking.
On a typical character, stamina doesn't start draining just while walking until 40 mouth encumbrance, while 30 (just a gas mask) negates regen while walking.

**Comment by kevingranade** [comment]
There is a kind of bug lurking here, if you are over-volume and wearing a gas mask it bumps encumbrance over the limit, being over-volume shouldn't affect mouth encumbrance (it shouldn't be possible at all, but that's another issue).

**Comment by kevingranade** [comment]
When encumbered, walking speed should drop instead of draining stamina.
