### ISSUE TITLE
Instant crash (cant even create world)

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#12281]
Win 7 64 bit
Dev build 3100 64 bit TILES

I choose new game
Select a saved preset character

And BOOM crash :(

So I created a new custom character exactly the same as my preset one and it works.

I assume some thing has been changed.

This is not a big deal as I have now created a new preset using latest DEV build but just curius more than any thing :)

**Comment by graysage1** [comment]
Can you dupe it?  Is it rare?  Did you get a "DEBUG" message before crash?  Is the new character that isn't crashing using some different traits/stats?

**Comment by wubblemeister** [comment]
I am also having this issue.

Windows 8.1
v0.C Cooper

It happens every time I try to load a preset character. If I make a new preset character and then go back before world gen and hit preset character, I can select any character but the one I just made, and the game does not crash. But if I then close down the game and open it back up and try to open preset character, it crashes like before (but seems to take a second or two longer to do so).

**Comment by mugling** [comment]
@stk2008 can this still be reproduced in a recent version of `master`?

**Comment by codemime** [comment]
I couldn't reproduce the crash itself on Linux Xubuntu x64 with the current `master`, but I can confirm this part:
> I can select any character but the one I just made, and the game does not crash. 

It looks like newly created templates aren't pushed to the `templates` vector.

**Comment by mugling** [comment]
Closed due to age and lack of recent reports

**Comment by codemime** [comment]
What about this part?
> I can select any character but the one I just made, and the game does not crash. 

It looks like a separate issue.

**Comment by mugling** [comment]
If that still exists feel free to report it as a new issue
