### ISSUE TITLE
weather stuck?

### ISSUE THREAD

**Issue by jcd000** [CleverRaven/Cataclysm-DDA#12285]
Version 0.C-2205-g6d40da1 (build today), the weather seems to not be changing during a season.
I mean, the whole Summer was sunny, and 13 days of Autumn in a row it drizzles.
I think that in the beginning of Spring i saw some snow, then endless drizzle, but so little variation seems fishy.

**Comment by jcd000** [comment]
To update this:
Till winter, the only state change of the weathers i have seen are:
During Spring: Flurries <-> Drizzle
At season change: Sunny until Autumn
During Autumn: Flurries <-> Drizzle
During Winter: Flurries <-> Drizzle

I may look into it on my own.

**Comment by Shoes01** [comment]
I don't think any one has touched weather in a while, so it might just seem like nothing is happening.

Grab some thermometers and check for yourself :)

**Comment by jcd000** [comment]
it must have been stuck somehow, since there was a year and a half where i only saw those weathers.

Still, i updated and i saw more normal weather transitions afterwards.
Closing it, but keeping an eye on it still.
