### ISSUE TITLE
V-menu option persistence

### ISSUE THREAD

**Issue by Ishindri** [CleverRaven/Cataclysm-DDA#12296]
I love the V-menu options, but the lack of persistence for them has frustrated me.

* ~~Sort choice (distance or category) is lost when the menu is closed.~~ (Fixed by #12480.)
* Filters and priorities are cleared when Cataclysm quits (the program, not quits to main menu).

I'd really like to be able to set permanent priorities.  (All clothing goes right to the bottom.)

**Comment by BevapDin** [comment]
> Filters and priorities are lost when Cataclysm quits (the program, not quits to main menu).

The last few filter strings are actually remembered: in the input dialog where you can enter it again, press the up key do view / select them.

**Comment by Ishindri** [comment]
Ooh, I never noticed that.  Cool.  Though I would still prefer if I didn't have to re-enter my priorities every time I start up the game.

**Comment by DavidKeaton** [comment]
This should be closed if it is solved!

**Comment by Zireael07** [comment]
The PR does not solve the filters/priorities, methinks, just the sorting part.

**Comment by DavidKeaton** [comment]
Point, but I think there may be an issue for it overall, is there?

**Comment by Ishindri** [comment]
Not that I'm aware of.  I opened this issue because I couldn't find any other issues relating to this.

**Comment by DavidKeaton** [comment]
Fair enough.
