### ISSUE TITLE
Another UI inconsistency (inv - consume screens)

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#12308]
Returned to Cata, needed a drink...:

![eat menu](http://i.imgur.com/8vZb4La.png)

...Now have a look at the plain inventory screen:

![inv menu](http://i.imgur.com/2NhezYq.png)

Do you notice ~~waldo~~ difference?

At 0.C-2379-g8a35cf1.

**Comment by graysage1** [comment]
I mentioned this same issue a short while ago.  Let's just say the 'E'at item menu is less than ideal and the devs seem to know about it.  We had a little chat about it, so they know.  But I'm glad you're bringing this up too, because it does bug me so.

**Comment by vache** [comment]
I'm not sure what the issue is here.  If anything, the eat screen should filter out the worn inventory too IMO.

**Comment by drbig** [comment]
The issue is that the eat menu 'eats' the text... like how much water is actually left in my canteen.

@graysage1 Was that the same issue you've reported?

**Comment by BevapDin** [comment]
That is the same column issue as I explained at https://github.com/CleverRaven/Cataclysm-DDA/issues/12140#issuecomment-97737181

Only the multi-drop and the compare item window should need three columns. The other windows allow only to select one item and immediately exist, so a third column with the selected item(s) would not be useless.

**Comment by graysage1** [comment]
@drbig: What @BevapDin said.
