### ISSUE TITLE
Multiplying oil lamps

### ISSUE THREAD

**Issue by NukeACitrus** [CleverRaven/Cataclysm-DDA#12301]
I've found a repeatable bug in 0.c-29659-ga209cc2 Experimental. 

When you move a oil lamp in the advanced inventory manager from one spot to another using "m", it's going to leave a brand new lamp in its place, containing 1 unit of oil, subtracted from the original lamp. 

Was able to repeat the bug, creating a bunch of oil lamps out of a single lamp containing oil.

Don't know if this is a thing in later versions but thought you might want to know anyway.

**Comment by BevapDin** [comment]
This might have been fixed by #12187 (bug was reported as #12178), does it still appear in the current experimental?

**Comment by tvm1** [comment]
Cannot replicate in current experimental, seems to be fixed.

**Comment by DavidKeaton** [comment]
Yeah it was an issue with charge based movement, this should've been fixed (and seems to be reported to be). Unless OP states otherwise, this can be closed. :-)
