### ISSUE TITLE
Follow XDG specifications on Linux

### ISSUE THREAD

**Issue by Ram-Z** [CleverRaven/Cataclysm-DDA#12315]
Please follow the [XDG Basedir Spec](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) on Linux, i.e.:
* put config files in `$XDG_CONFIG_HOME/cataclysm-dda` or `~/.config/cataclysm-dda`
* put data files in `$XDG_DATA_HOME/cataclysm-dda` or `~/.local/share/cataclysm-dda`

I'd be happy to write a patch myself.

**Comment by DavidKeaton** [comment]
could be just a makefile flag

**Comment by Ram-Z** [comment]
I'd prefer it'd be default, but would settle on makefile flag.

**Comment by DavidKeaton** [comment]
okay I see what your putting down. all the asset grabbing is done in a way where changing the default path shouldn't be an issue. one could edit the makefile, to make your changes, then introduce a makefile environment variable to choose a non default. USE_HOME_DIR could just be OUT=$HOME alias or some jazz.

**Comment by Ram-Z** [comment]
The thing is that XDG separates config files from data files, so it's not as trivial as you might assume.

This is a quick implementation of adding `USE_XDG_DIR` Makefile flag. But since it conflicts with `USE_HOME_DIR`, I'm not too fond of this.

```diff
diff --git a/Makefile b/Makefile
index 3de1a34..70fc933 100644
--- a/Makefile
+++ b/Makefile
@@ -37,6 +37,8 @@
 #  make install
 # Enable lua support. Required only for full-fledged mods.
 #  make LUA=1
+# Use user's XDG base directories for save files and configs.
+#  make USE_XDG_DIR=1
 # Use user's home directory for save files.
 #  make USE_HOME_DIR=1
 # Use dynamic linking (requires system libraries).
@@ -410,6 +412,10 @@ ifeq ($(USE_HOME_DIR),1)
   DEFINES += -DUSE_HOME_DIR
 endif
 
+ifeq ($(USE_XDG_DIR),1)
+  DEFINES += -DUSE_XDG_DIR
+endif
+
 all: version $(TARGET) $(L10N)
 	@
 
diff --git a/src/main.cpp b/src/main.cpp
index 756e36a..aafb244 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -73,7 +73,7 @@ int main(int argc, char *argv[])
     PATH_INFO::init_base_path("");
 #endif
 
-#ifdef USE_HOME_DIR
+#if (defined USE_HOME_DIR || defined USE_XDG_DIR)
     PATH_INFO::init_user_dir();
 #else
     PATH_INFO::init_user_dir("./");
diff --git a/src/path_info.cpp b/src/path_info.cpp
index 6c0410a..de34cc8 100644
--- a/src/path_info.cpp
+++ b/src/path_info.cpp
@@ -34,6 +34,13 @@ void PATH_INFO::init_user_dir(const char *ud)
 #elif defined MACOSX && defined TILES
         user_dir = getenv( "HOME" );
         dir = std::string( user_dir ) + "/Library/Application Support/Cataclysm/";
+#elif (defined USE_XDG_DIR)
+        if (user_dir = getenv("XDG_DATA_HOME")) {
+            dir = std::string(user_dir) + "/cataclysm-dda/";
+        } else {
+            user_dir = getenv("HOME");
+            dir = std::string(user_dir) + "/.local/share/cataclysm-dda/";
+        }
 #else
         user_dir = getenv("HOME");
         dir = std::string(user_dir) + "/.cataclysm-dda/";
@@ -144,7 +151,19 @@ void PATH_INFO::set_standard_filenames(void)
     update_pathname("savedir", FILENAMES["user_dir"] + "save/");
     update_pathname("memorialdir", FILENAMES["user_dir"] + "memorial/");
     update_pathname("templatedir", FILENAMES["user_dir"] + "templates/");
+#ifdef USE_XDG_DIR
+    const char *user_dir;
+    std::string dir;
+    if (user_dir = getenv("XDG_CONFIG_HOME")) {
+        dir = std::string(user_dir) + "/cataclysm-dda/";
+    } else {
+        user_dir = getenv("HOME");
+        dir = std::string(user_dir) + "/.config/cataclysm-dda/";
+    }
+    update_pathname("config_dir", dir);
+#else
     update_pathname("config_dir", FILENAMES["user_dir"] + "config/");
+#endif
     update_pathname("graveyarddir", FILENAMES["user_dir"] + "graveyard/");
 
     update_pathname("options", FILENAMES["config_dir"] + "options.txt");
```

**Comment by DavidKeaton** [comment]
I see no reason for a `USE_HOME_DIR` anymore if the fallback is to use it anyway.

**Comment by Ram-Z** [comment]
When the environment variables `XDG_CONFIG_HOME` and `XDG_DATA_HOME` are not set, the fallback is `~/.config` and `~/.local/share` respectively. This is not the same as `USE_HOME_DIR` which uses `~/.cataclysm-dda`.

**Comment by DavidKeaton** [comment]
True, but what I was saying (albeit I was not very concise), was USE_HOME_DIR could be done away with, and instead just do the fallback to `~/.config` and `~/.local/share` instead.

**Comment by drbig** [comment]
I'm not a big fan of whatever gets spat out by the freedesktop.org people, but having it as another option wouldn't hurt. If it's mutually exclusive with `USE_HOME_DIR` maybe just ad a guard in case someone/something tries to set both at the same time?

**Comment by Ram-Z** [comment]
I believe that XDG is one of the better things freedesktop.org did. I like my `~` to be clean and having config files all under one directory is so convenient. I don't understand why some people might not want this.

#12377 should cater to everybodys needs though.
