### ISSUE TITLE
[0.C stable]plant fungal seed occuring crash.

### ISSUE THREAD

**Issue by Imitea** [CleverRaven/Cataclysm-DDA#12330]
When I plant fungal seed in my farm, could not load save file and cataclysm crashed.

So I found fungal seed tile in save file,

5,5,[{"invlet":0,"typeid":"fungal_seeds","bday":2139068,"charges":1,"components":[]}],

and change it to zucchini.

5,5,[{"invlet":0,"typeid":"seed_zucchini","bday":2139068,"charges":1,"components":[]}],

After that, I could load that save file.

**Comment by BevapDin** [comment]
This should have been fixed by #11843 in the experimental version. You can get it at http://dev.narc.ro/cataclysm/jenkins-latest/ and test it.
