### ISSUE TITLE
Monsters Disappearing

### ISSUE THREAD

**Issue by KrazyTheFox** [CleverRaven/Cataclysm-DDA#12338]
In Experimental 3136, when a creature leaves the reality bubble it leaves the world forever. To replicate, spawn a creature at the edge of your visible range. Take a few steps away from it, then walk back. It will no longer exist.

**Comment by Rivet-the-Zombie** [comment]
Schrödinger's zombie?

**Comment by Coolthulhu** [comment]
Z-levödinger zombie.
They're probably trying to spawn deep underground or in the sky.
I'm writing a fix right now

**Comment by Rivet-the-Zombie** [comment]
This is likely related to the issue reported on the Bay12 forums where monsters and items are shifting z levels in odd ways, like finding sewer critters and items on Z level 0.
