### ISSUE TITLE
look_around doesn't describe monsters seen with IR vision.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#12339]
as title, highlighting the red '?' drawn for a monster seen with IR vision should describe the monster, at the least with a general, "You see a figure radiating heat".
##

**Comment by Rivet-the-Zombie** [comment]
Maybe also give a size indicator as well? 'You see a large(small/etc.) figure radiating heat.'

**Comment by Coolthulhu** [comment]
Same for footsteps.

I changed the sound marker display to say "a sound" when the sound has no description, but it still doesn't say "loud sound" or "heavy footsteps".

**Comment by kevingranade** [comment]
The various monsters could use some walking sound descriptions as well as
IR descriptions, but that's a bit more advanced than what I was getting at
here.  It's possible they should be categories instead of freeform strings
to avoid being able to tell monsters apart from their footsteps when not
intended.
