### ISSUE TITLE
Crash at start menu (Windows Tiles) if no sound card is present

### ISSUE THREAD

**Issue by DmytryVonBeef** [CleverRaven/Cataclysm-DDA#12348]
The game starts up fine, but as soon as I press any of the arrow keys/numpad arrows it states that Cataclysm has stopped working. I'm running the game on Win 7 32-bit. I run 0.C 3093 perfectly but crash in the latest experimentals.
##

**Comment by DmytryVonBeef** [comment]
Also, selecting options with letters and using the arrow keys in sub-menus/in game works fine.

**Comment by DmytryVonBeef** [comment]
I fixed it. Apparently playing the game without a sound card makes it crash when it's supposed to play a sound.

**Comment by narc0tiq** [comment]
I'd keep this open, but with a different title. Allow me.

**Comment by Leland** [comment]
Closing due to age. If anyone is playing CDDA without a sound card and runs into the same, feel free to make a new issue.
