### ISSUE TITLE
BlazeMod turrets citing non-existent build items.

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#12340]
Several of the turrets in the Vehicle Additions Pack cite items that do not exist, resulting in errors on the install screen.

![errors ensue](https://cloud.githubusercontent.com/assets/11582235/7556753/20b98d4e-f744-11e4-9264-50a94e6c6708.png)

This occurs the first time any such selection is highlighted, after which it demands an undefined item without further trouble, applying the same fix to any parts demanding the same non-existent item.

![a turret made out of nothing](https://cloud.githubusercontent.com/assets/11582235/7556765/87f45264-f744-11e4-9754-dac677c16cca.png)

All vehicle parts I can find that have this bug:

1. Mounted .22 dual turrets
2. Mounted .45 dual turrets
3. Mounted 9mm dual turrets
4. Dual nail turret
5. Mounted .22 quad cannon
6. Mounted .45 quad cannon
7. Mounted 9mm quad cannon
8. Quad nailer
9. Mounted MG turret
10. Mounted MG
11. Mounted energy turret
12. Mounted laser

**Comment by Coolthulhu** [comment]
Blazemod in mainline is outdated.
The more updated version in the forum thread may work properly.
Someone should PR the new version.

**Comment by chaosvolt** [comment]
Hmm. I'd tried to find the mod in the forum, I was hoping Blazemod would have a topic to post this in.

**Comment by Rivet-the-Zombie** [comment]
Blazemod is rife with oddities and errors, and it only seems to get worse with time. It really needs to either get up-to-date or GTFO.

**Comment by chaosvolt** [comment]
The only oddities I've discovered so far are missing items, not THAT much of a clusterfuck. >.o

**Comment by Rivet-the-Zombie** [comment]
There's also the whole issue where enabling it turns rocks into ammunition, and the bit where it raises the difficulty of installing a battery storage case to something like 50.

**Comment by chaosvolt** [comment]
Ah, that is weird. The rock thing I assume is for using random junk in one of the turrets, right?

Also, my mod turns javelins into ammo too, so... >_>

**Comment by Rivet-the-Zombie** [comment]
I'm in favor of migrating most (if not all) of your mod's content into the mainline anyway, but that's neither here nor there.

**Comment by chaosvolt** [comment]
Ah, neat. owo

In any case, battery case issue would be a simple change. As for the turrets I'm not sure if they're non-existent or simply misnamed.

The rocks though...no idea what all changing them to ammunition breaks. O.o

**Comment by Rivet-the-Zombie** [comment]
>The rocks though...no idea what all changing them to ammunition breaks. O.o

At one point it made them flammable, though I think we have that nailed by now.

**Comment by chaosvolt** [comment]
Ah, that makes sense.

Hopefully javelins are no more flammable than the norm?

**Comment by Coolthulhu** [comment]
Javelins were flammable already, because they're wooden.
The problem with rocks was that fire code had an ugly hardcoded list of flammable things, which included all ammo except some types. At one point I had to add water to this list to make it not burn.

New burning code doesn't have any hardcoded ammo references, only some hardcoded materials (I'll remove that later).

**Comment by Rivet-the-Zombie** [comment]
>At one point I had to add water to this list to make it not burn.

This is the best one yet.

**Comment by chaosvolt** [comment]
> At one point I had to add water to this list to make it not burn.

That is what happens when you crit-fail at boiling water, I guess. o3o

**Comment by Sirbab** [comment]
So, i'd like to point out that many of these issues were fixed, as they were bugs, eg the battery case, i'm using the updated version and am not experiencing any oddities. and i've been testing fairly extensively with regular play.

**Comment by chaosvolt** [comment]
Hmm. Where are you getting this updated version? Is it a recent PR, or something else?

**Comment by Sirbab** [comment]
http://www.mediafire.com/download/dpcc5k4xabkkm1i/blazemod.zip, or if you'd like the forum page;http://smf.cataclysmdda.com/index.php?topic=8060.0

**Comment by chaosvolt** [comment]
Are you sure? I tested the version listed on the first post, it is an older version with less parts.

**Comment by Sirbab** [comment]
If you open up the rar file, you'll notice one of the files was last updated may 2, i'm fairly certain this is the latest version. Unless there was a rollback of features?

**Comment by chaosvolt** [comment]
Huh, that's odd. Blaze might've removed some things then. O.o

**Comment by Sirbab** [comment]
Well, at the very least, i've had no more missing item errors, no case req 50 on cases, on the updated version, the one in mainline is fraught with bugs sadly. i would've made a post on his forum page, but i saw you already did.

**Comment by chaosvolt** [comment]
The updated version appears to be missing all the turrets that caused this issue, though.

**Comment by BevapDin** [comment]
The current version of the mod (newest file in the zip archive is from 2015-05-03 22:13) does not have the turrets in question (and therefor no problem with missing items). It looks as if the file with those vehicle parts should have been removed with the previous update (which removed the item types) because that file is not in the current version of the mod.

However, updating to this version will be problematic for saves that contain the removed vehicle parts. That problem was already introduced by the previous update as it removed the base items of those vehicles parts (items which might have still existed in a save).

Either remove the vehicle parts completely (as it was apparently intended by the creator of the mod) and live with the save incompatibility.
Or add the missing item types back in (for example the nx17s was removed with d64b4bef136f0dd2b1fe99bcc6e2fa648fbe12ef).

**Comment by chaosvolt** [comment]
Ah, so that is current? I see.

Anyone planning to fix this for the mainline mod?

**Comment by Sirbab** [comment]
Could you add dummy versions of the items required temporarily, then actually update the mod in mainline when another pr breaks save compatibility? As it stands, i'm perfectly fine with just breaking save compatibility.

**Comment by chaosvolt** [comment]
If anything I'd like to see whether Blaze is either able to take action, or give someone permission to implement a change for him.

**Comment by DavidKeaton** [comment]
@chaosvolt this should be fixed now, correct? If they happen to be, this can be closed. :-)

**Comment by chaosvolt** [comment]
Doh. Right, since I PR'd Blaze's fix for it. Forgot about this thread actually. owo

**Comment by DavidKeaton** [comment]
All good!
