### ISSUE TITLE
Any chance for a 32x32 version of ChestHole and MShock24Modded

### ISSUE THREAD

**Issue by pouar** [CleverRaven/Cataclysm-DDA#12352]
The lack of a 32x32 version is the only reason I'm not using it.
If you're not going to include one is there any way I can resize it without degrading the quality as the floors get blurred which causes the edges of the floor tiles to be visible instead of blending in.

**Comment by kevingranade** [comment]
It would probably be more productive to ask on the forums, none of the devs
do tilesets, and I don't know if any of the tileset authors follow github.

**Comment by stk2008** [comment]
I have been asking for an Mshock32modded for a while and it may happen so fingers crossed :)

**Comment by chaosvolt** [comment]
Hnng. I would need to develop further sprite edits for mine, as pure resizing is derp.

Possible but a potential pain in the ass. Then again, at the moment I don't have any urgent changes for More Survival Tools, though IRL distractions are distracting.

**Comment by chaosvolt** [comment]
And highly belatedly, I eventually did a thing. =w=

https://github.com/CleverRaven/Cataclysm-DDA/pull/12569
