### ISSUE TITLE
Visual map-corruption

### ISSUE THREAD

**Issue by namarrgon** [CleverRaven/Cataclysm-DDA#12358]
The shape of the player's current field of vision is visible in several regions of the map: 
http://imgur.com/a/9ZoHu

Multiple smaller, static shapes always show up in the west; the north and south show an unscaled shape that sometimes is redrawn while scrolling; the east shows noise.

This is visible with tilesets that use distinct tiles for 'lighting_lowlight_dark' and 'lighting_hidden', e.g. MShock or Blockhead's. The curses builds either don't exhibit the bug or it's just not visible.

**Comment by Zireael07** [comment]
IIRC you can't have tiles on in curses?

**Comment by namarrgon** [comment]
No, of course not but it wouldn't be visible anyway since the same character is used for both types of "tiles".

**Comment by kevingranade** [comment]
I could have sworn I fixed this... will look into it again.

**Comment by kevingranade** [comment]
Oh right, I fixed it for curses mode with #12005, didn't realize it was happening in tiles mode too.
Just needs some similar bounds checking I'm sure.

**Comment by BevapDin** [comment]
Fixed by #13706.
