### ISSUE TITLE
Build broken in minw32

### ISSUE THREAD

**Issue by PropaneSoup** [CleverRaven/Cataclysm-DDA#12351]
Windows 7, wingw32-gcc compiler in Code::Blocks.

obj\Release\src\game.o:game.cpp:(.text+0x415b8): undefined reference to `int_id<monfaction>::int_id(string_id<monfaction> const&)'
obj\Release\src\init.o:init.cpp:(.text+0x507b): undefined reference to `monfactions::finalize()'
obj\Release\src\init.o:init.cpp:(.text+0x7eef): undefined reference to `monfactions::load_monster_faction(JsonObject&)'
obj\Release\src\monmove.o:monmove.cpp:(.text+0x4e93): undefined reference to `int_id<monfaction>::int_id(string_id<monfaction> const&)'
obj\Release\src\monmove.o:monmove.cpp:(.text+0x53de): undefined reference to `int_id<monfaction>::id() const'
obj\Release\src\monmove.o:monmove.cpp:(.text+0x584d): undefined reference to `int_id<monfaction>::obj() const'
obj\Release\src\monmove.o:monmove.cpp:(.text+0x585e): undefined reference to `monfaction::attitude(int_id<monfaction> const&) const'
obj\Release\src\monster.o:monster.cpp:(.text+0x52dd): undefined reference to `int_id<monfaction>::obj() const'
obj\Release\src\monster.o:monster.cpp:(.text+0x52ed): undefined reference to `monfaction::attitude(int_id<monfaction> const&) const'
obj\Release\src\monstergenerator.o:monstergenerator.cpp:(.text+0xd152): undefined reference to `monfactions::get_or_add_faction(string_id<monfaction> const&)'
obj\Release\src\savegame_json.o:savegame_json.cpp:(.text+0xf811): undefined reference to `int_id<monfaction>::id() const'
obj\Release\src\savegame_json.o:savegame_json.cpp:(.text+0x21401): undefined reference to `string_id<monfaction>::is_valid() const'
obj\Release\src\savegame_json.o:savegame_json.cpp:(.text+0x2164f): undefined reference to `string_id<monfaction>::id() const'
obj\Release\src\savegame_json.o:savegame_json.cpp:(.text+0x2166d): undefined reference to `int_id<monfaction>::int_id(string_id<monfaction> const&)'

Based on the error messages, I've got a sneaking suspicion this is from #12335

**Comment by Coolthulhu** [comment]
May be a result of dependencies not being rebuilt.
Try cleaning and then rebuilding.

**Comment by PropaneSoup** [comment]
That didn't do it. I downloaded a fresh zip of the file from github as well. Everything should be fresh.
