### ISSUE TITLE
Installed Anti-Glare Compensators doesn't give GLARE quality

### ISSUE THREAD

**Issue by Darkyhard** [CleverRaven/Cataclysm-DDA#12368]
If you change a recipe to use GLARE quality instead of welding goggles, you will still need to use normal welding goggles even if you have Anti-Glare Compensators bionic installed.

**Comment by Nandorianen** [comment]
You do not even need to change anything. 
These recipes use require glare protection quality that doesn't take bionics into account:
- concrete mixer;
- brick kiln.
These construction tasks do so as well:
 - build concrete roof;
 - build reinforced concrete roof;
 - build standing tank.
I probably missed a few more.
I'm not sure how it should be fixed. If cata is moving away from items towards qualities and this is a start of the process, then we need a pseudo-item. If it's the other way around, then changing recipes and building tasks would suffice. I'm guessing it's the first one.

**Comment by Shadefang** [comment]
Just ran into this issue. The only recipe I see missing from Nandorianen's is the standard concrete roof.

As a secondary question, is the fact that only a few constructions use the WELD quality a result of intentionally moving away from it?

**Comment by Darkyhard** [comment]
This seems to be fixed now, closing it.
