### ISSUE TITLE
Opening lab doors with science ID card is broken

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#12374]
You slide the card, get a message along the lines 'the doors slide down into floor', but the actual doors remain closed. However it seems that using the card correctly prevents turret spawns inside (doors opened via map editor).

Seems this has been mentioned on IRC already. I've tested today at `0.C-2691-ga021303` and the bug is still present.

Something to do with the move to 3D coords for everything?

**Comment by Coolthulhu** [comment]
Oops, my bad.
It uses offsets as positions rather than adding offsets to positions.
