### ISSUE TITLE
Improper/missing Localization regarding the Flammenschwert

### ISSUE THREAD

**Issue by Sirbab** [CleverRaven/Cataclysm-DDA#12370]
Flammenschwert (flamesword, upgrade for zweihander) is missing an english description, as well as the term aus/an should be off/on.
"Ein großes zweihändiges Schwert aus Deutschland, an dessen Klinge sich, unter zuführung von Benzin, eine anhaltende Flamme erzeugen lässt. Es ist eine sehr mächtige Waffe." The literal translation is something like "Under supply of gasoline, a sustained flame generating a large two-handed sword from Germany, on its blade, can be. It is a very powerful weapon." Unless we assume all players understand German i think it should be translated to "When supplied with gasoline, this weapon is capable of creating a sustained flame along its blade. It is a very powerful weapon" (or substitute with fearsome, destructive etc).

**Comment by i2amroy** [comment]
Part of the point of these weapons is to be a funny addition more than a serious weapon. If the German is bad then feel free to fix it, but I'm of the opinion that it should stay in German for now (similar to how the Jacqueshammer is in French).

**Comment by Sirbab** [comment]
Ah,  i was unaware it was intended, (i assumed it was a German github contributor) I'll close the issue then.
