### ISSUE TITLE
Duplicate item: "BBs" and "bearings"

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#12373]
Just found this in-game, but confirmed with the item browser.

There is an item "bearings", described as a box of ball bearings, which is ammo type "pebbles". There is also an item "BBs", described as a box of small steel balls, which is ammo type "BBs" - used only in the BB gun (and in some others in the Blaze mod?).

Seems like these two should be combined (which would allow pebbles to be used in BB guns), or the "bearings" item eliminated (which would mean BBs couldn't be used in slingshots, etc).

**Comment by Rivet-the-Zombie** [comment]
This isn't a bug. BBs are .177 caliber (which only weighs five grains) metal balls made for use in airguns (like a Daisy Red Ryder airgun). So-called 'bearings' are various-sized metal spheres removed from bearing elements, and are considered to be a fair bit larger and heavier than .177 caliber.

The .177 caliber BBs are so small that they're really only useful in a weapon calibrated specifically for them, and even then they're really only good for shooting small game like squirrels.
