### ISSUE TITLE
Escape Key should Cancel All Screens

### ISSUE THREAD

**Issue by qbradq** [CleverRaven/Cataclysm-DDA#12378]
Currently the Escape key cancels or closes most screens, but not all. Some screens require the 'q' or 'x' key to close.

** Possibly Related Issues **
#8553

**Comment by BevapDin** [comment]
Isn't that issue covered by #12112? It only takes about popups, but surely it applies to all kind of menus/dialogs/windows/etc.

**Comment by qbradq** [comment]
Thanks DevapDin, I didn't come across that when I was researching issues. I will close this as duplicate.
