### ISSUE TITLE
Performance degradation in labs

### ISSUE THREAD

**Issue by jokermatt999** [CleverRaven/Cataclysm-DDA#12382]
I just tried a lab challenge. The game ran incredibly slowly. Like, basic movement taking several seconds. I'm guessing it's because labs can contain several z-levels with quite a few monsters in it, because I don't get that anywhere else.

**Comment by Coolthulhu** [comment]
With experimental z-level mode on or off?
If off, then the z-levels shouldn't affect it and there must be something else going on. Save could be useful.

If on, then it's expected - z-level code is experimental for a reason. I'll optimize it after I get it to work.

**Comment by mugling** [comment]
No clear path to resolution. Please re-open if further details are available or a test-case can be constructed
