### ISSUE TITLE
Attempt to get monster with index -1

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#12384]
Some recent addition can cause "deference" of monster index -1.
I suspect this line:
```
monster *zed = &g->zombie(g->mon_at(raised.first));
```
In monattack.cpp::resurrect.
Didn't run the debugger yet, but it is the best candidate because it is recent, because it has no safety checks and because it accesses monsters by index.

I can't really see how would it happen, but I saw a necro, then got a debug message and then my game crashed.
It could happen if I added a blacklist to an existing world and then a necro rezed a blacklisted mon, but I don't have any monster blacklists.

**Comment by BevapDin** [comment]
`monster_at` is usually called in this style:
```C++
{
                    if (g->summon_mon("mon_spore", sporep)) {
                        monster *spore = g->monster_at(sporep);
```
`summon_mon` only returns true if the monster has actually spawned there. If `Creature_tracker::add` has refused to spawn the monster (blacklisted, mon_null, already some monster there), it returns false. If it returns true, the caller can be relatively sure there is a monster now. (However, this falls flat when the tripoints used there do not match.)

> and because it accesses monsters by index.

Every code part does this. Some parts use `critter_at` (but that also calls `game::mon_at` and `game::zombie`). ideally everything would go through a function that return the monster/Creature pointer (and returns nullptr if there is no creature).

**Comment by Coolthulhu** [comment]
> Every code part does this.

Most do so indirectly, through `critter/mon_at`.

While `summon_mon` guarantees that the critter has been added when it returns true, `revive_corpse` doesn't, as it drops the return value of `add_zombie`.

Not sure how could the addition after revival fail silently. It would have to try to add a null or blacklisted monster.

Not sure how should I even try to replicate it. I only noticed a necro zed around the time the game debugmsg'd and crashed on me.

**Comment by BevapDin** [comment]
> It would have to try to add a null or blacklisted monster.

Technically this might happen when the blacklist changes saving and loading the save. A monster that existed (and was not blocked) could have died and left a corpse in the save. Upon loading the safe, the monster is blacklisted and will fail to revive. That might have been triggered by 5fa10db4ec63d288310792126345f1b1b2e34f5e (the monster types were added earlier).

**Comment by Coolthulhu** [comment]
The problem is, I didn't have any (monster) blacklists on that save.

**Comment by Coolthulhu** [comment]
OK, I think I got it: the new necro code doesn't check if the monster can exist after revival. As a result, burned corpses too weak to survive wake up dead.
`mon_at` checks for dead state and ignores dead monsters.
