### ISSUE TITLE
Books too complex even with boosted intelligence

### ISSUE THREAD

**Issue by tvm1** [CleverRaven/Cataclysm-DDA#12390]
Taking/installing intelligence enhancers (I've tested coffee, methacola, cerebral CBM) and buffing up your intelligence over the required level for easy reading doesn't works and "too complex to read" penalty is still present.

**Comment by Cat09** [comment]
does anyone know if the penalty is actually present or the game just tells us it is? (I can confirm the difficulty reading message when int is buffed, for win/graphical 3111)

**Comment by tvm1** [comment]
Looking at `player.cpp`, it shows the message and applies the penalty.

```c++
if (tmp->intel > int_cur && !continuous) {
 add_msg(m_warning, _("This book is too complex for you to easily understand. It will take longer to read."));
 // Lower int characters can read, at a speed penalty
 time += (tmp->time * (tmp->intel - int_cur) * 100); 
}
```

**Comment by DavidKeaton** [comment]
looks to be an issue with inverted comparison. the first line should be `<`, not `>`.

**Comment by tvm1** [comment]
`tmp` points to a book, if the required `intel` is larger than `int_cur`, throw message and slow down learning, that seems fine to me.

Oddly enough, i can't seem to replicate the buggy behavior today. The problem might be elsewhere.

**Comment by DavidKeaton** [comment]
ah, my b
