### ISSUE TITLE
Home Improvement Megastore Garden Section Renders Improperly

### ISSUE THREAD

**Issue by qbradq** [CleverRaven/Cataclysm-DDA#12393]
In the current master tiles build, concrete floors create graphical glitches. A good place to observe this is the garden section of the new home improvement megastore from

**Comment by qbradq** [comment]
...did not mean to hit send...

From #11869. I am not sure if this is because those tiles should not be use, have inappropriate flags, our there it's a bug.

Thank you

**Comment by BevapDin** [comment]
What (if any) tileset are you using?

Apparently it uses the terrain `t_thconc_floor`, which is not supported by all tilesets (that is a bug of those tilesets). RetroDaysTileser MShock24TilesetModded have it.

**Comment by qbradq** [comment]
I am using MShock32. I will give it a go with the above mentioned tile sets when I get back home and close or retitle the issue as needed.

Thank you!

**Comment by qbradq** [comment]
Confirmed, this works correctly in MShock24Modded tileset. Are tilesets expected to be updated to include definitions or fallbacks for all tiles prior to a stable release?

**Comment by Zireael07** [comment]
Nope, tileset updates generally come last before a stable hits.

**Comment by qbradq** [comment]
Yea, that's what I meant :) Closing. Thanks for helping me understand the issue.
