### ISSUE TITLE
Recipe search by quality has bad logic

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#12408]
As reported by `<levstk>` on IRC, searching recipes by quality (e.g. `q:hammer`) returns _recipes producing items that **have**_ the named quality, instead of returning recipes that **require** that quality. This is in contrast to searching by tool or component, where one obtains recipes that require said tools and components.

After further discussion, it occurs to me that both of these questions can be useful to have answers for: "What can I make that has the Xing quality?" and "What can I do with something that has the Xing quality?". Perhaps there should be ways to ask both.

And while you're there... the help function suggests `t:hammer` as an example search, but that filter doesn't work because no recipe explicitly calls for a hammer anymore. Maybe `t:fire` would be a better example?

**Comment by DavidKeaton** [comment]
I am working on a new filter system to combine all the stuff under a common class.

**Comment by drbig** [comment]
Looking into this now. The distinction between `t`ool and `q`uality makes it rather uneven (e.g. soldering iron, but hammering). For sake of consistency I'll change `q` to show recipes that require given quality. Adding another filter if needed could be done separately.

**Comment by HeadWar** [comment]
I'd much prefer if (t)ool searched both needed tool names and needed tool qualities. They both go under the "Tools required:" header. Having two different searches seems redundant at best, confusing and annoying at worst.

Keep (q)ualities as it is, it is extremely useful when you know you need a certain quality, but don't know how to get it.

**Comment by drbig** [comment]
@HeadWar Check out [this](https://github.com/CleverRaven/Cataclysm-DDA/pull/13258/files#diff-244fef9df19695eb07ac24b399d34e91R880) (the right-hand side).

**Comment by HeadWar** [comment]
That works I suppose, but I still think it's unnecessary to have separate entries for required tools and required tool qualities. =)

**Comment by drbig** [comment]
> but I still think it's unnecessary to have separate entries for required tools and required tool qualities. =)

Yeah the soldering iron vs. hammering/fine bolt turning/etc. isn't pretty but code-wise mixing these would be even worse for the player.

It might come to the point where all tool requirements are actually qualities, then unification here will be obvious.
