### ISSUE TITLE
H&K 416A5 with suppressor creates negative sound

### ISSUE THREAD

**Issue by Ronin1791** [CleverRaven/Cataclysm-DDA#12400]
Debug menu appears after every shot with the message "DEBUG: negative sound volume -10"

**Comment by Cat09** [comment]
definitely a bug, but I'd like to point out that negative sound could be a useful effect to have, noise cancelling devices could be modelled that way.

**Comment by i2amroy** [comment]
The sound system doesn't work in that way. If we wanted to make a noise canceling device, it would have to create an AoE where sound effects were lowered when they triggered, not by some sort of "negative strength" sound.
