### ISSUE TITLE
Sound effect issues

### ISSUE THREAD

**Issue by CIB** [CleverRaven/Cataclysm-DDA#12403]
- [ ] Improve documentation for installing a sound pack
- [ ] Make it possible to install and select among multiple sound packs
- [ ] Create a sound effect file cache so that having multiple entries with the same sound effect file name will not lead to loading the same sound effect multiple times into RAM
- [ ] Put a limit on the size of the sound effect cache so that not all sound effects need to be loaded into RAM at once, but are swapped in and out on demand
##

**Comment by Leland** [comment]
This is an old issue comprised of multiple suggestions. I'm closing this - if you want, feel free to open up new issues, but I'd highly recommend you create an issue for each of these. They're great ideas but individually represent a lot of work and are likely deserving of their own issue.
