### ISSUE TITLE
Bionic removal with active bioclaws or bioblade

### ISSUE THREAD

**Issue by DZiral** [CleverRaven/Cataclysm-DDA#12420]
Remove any bionic with active bionic claws or bionic blade cause these bionics (claws or blade) stuck in active mode. 
How to reproduce:
  Get character with bionic claws ("bionic monster" profession for example)
  Get fist aid kit (for bionic removal)
  Activate claws
  Remove some other bionic using bionic screen ("p" key)
  Try activate bionic claws again. We have claws in hand, but after bionic removal game disable active bionic. So game try to activate claws again and this fails because claws already in hand. As result character stuck with claws in his hands and no way to deactivate claw. Same for bionic blade.

**Comment by PropaneSoup** [comment]
Easiest solution would just prevent doing surgery on yourself with your blade or claw bionics activated. I know blade stops you from doing just about anything but attacking, I'm assuming they also already prevent you from crafting?

**Comment by DZiral** [comment]
No, active claws dont prevent bionic removal. And if all bionic deactivated during removal, claws must deactivate correctly (not just set bionic to disabled state, but also remove claws from hand). One time you forget to disable bionic claws before surgery and character stuck with claw in hand forever. This is not good.
I think there is tree options to fix it. First - prevent surgery with active claws, second - when activate claws check if claws already in hand and in this case set bionic to active state without replacing weapon. Third - do not auto disable bionics when surgery or disable claws correctly.

**Comment by Cat09** [comment]
yeah, seems like the same checks for crafting should be applied to bionics. although the blade might count as a scalpel for removal, you'd have to make sure that was not for the blade itself.

**Comment by alex-gh** [comment]
I have encountered the same bug in 3375 windows graphical experimental.

Apparently the fix for it was removed here: https://github.com/CleverRaven/Cataclysm-DDA/commit/11c198bf40adc3d2862f29bb8e8d8e5076ed46a9#diff-c25e930a24544fa310a045895df4013e
