### ISSUE TITLE
errors building in visual studios

### ISSUE THREAD

**Issue by hurnhu** [CleverRaven/Cataclysm-DDA#12426]
I just forked the git project, cloned it, and opened in and i get 14 errors. the errors are:
`14	IntelliSense: cannot open source file "cuchar"	e:\git\Cataclysm-DDA\msvc140\pch.hpp	28	1	Cataclysm`

`Error	1	error C2665: 'std::locale::facet::operator new' : none of the 2 overloads could convert all the argument types	c:\program files (x86)\microsoft visual studio 12.0\vc\include\xlocale	122	1	Cataclysm`

`Error	3	error C2665: 'operator new[]' : none of the 5 overloads could convert all the argument types	c:\program files (x86)\microsoft visual studio 12.0\vc\include\xlocale	794	1	Cataclysm
`

im running visual studios ultimate 2013

**Comment by macrosblackd** [comment]
You need to build with VS2015

**Comment by hurnhu** [comment]
i tried with vs15 and and am still getting errors... 

now my problem is this line below, in map.cpp. on line 4927

Code: [Select]
    int sm_squares_seen[my_MAPSIZE][my_MAPSIZE];
i have the error 

Code: [Select]
Error		IntelliSense: 'this' cannot be used in a constant expression

and also the error 

Code: [Select]
     bool padded_cache[padded_w][padded_h];

on line 6580. with the error

Code: [Select]
Error		IntelliSense: expression must have a constant value

**Comment by BevapDin** [comment]
> Error IntelliSense: expression must have a constant value

IntelliSense is wrong The code is perfectly valid, but IntelliSense is not up-to-date, see http://stackoverflow.com/questions/14713391/is-there-a-way-to-suppress-intellisense-errors-when-using-c11-features-specifi

Ignore IntelliSense as long as the *actual* compilation works.

**Comment by macrosblackd** [comment]
There actually seems to be something going wrong in the compile for visual
Studio

**Comment by hurnhu** [comment]
yeah, can confirm. i disabled intellisince and it still can not compile. with the error

`
Error	C2057	expected constant expression	
`
in the same place

**Comment by mugling** [comment]
@hurnhu is this still a problem for you?

**Comment by mugling** [comment]
> @hurnhu is this still a problem for you?

Presumably not
