### ISSUE TITLE
Time to craft as a function of tool type (and condition even?)

### ISSUE THREAD

**Issue by joneskun** [CleverRaven/Cataclysm-DDA#12425]
Eg, using a sharp rock to make a pointy stick could take longer and not give as good results as a full-on woodworking toolkit might. I'm not sure if a generalized approach is possible within the current json framework, but something basic might be doable without too much effort.

**Comment by Coolthulhu** [comment]
Nope, current crafting system doesn't allow different craft times based on tools. It could allow different difficulty, fuel usage, practice etc., but different craft time would require having to consume ingredients at start of crafting. Even just making it not waste ingredients on canceled craft could be quite hard.

**Comment by mugling** [comment]
Duplicated by  #14708
