### ISSUE TITLE
Defense mode is very buggy and lacking in features

### ISSUE THREAD

**Issue by Autastic** [CleverRaven/Cataclysm-DDA#12429]
bugs:
-you can use first aid kits indefinitely 
-you cannot load presets
-the prices for ammo are cheaper than they should be
-certain enemies such as spiders are untargettable with melee, hitting them simply displaces them.
-GUI is too small for the caravan, cutting off a few of the selections at the bottom and descriptions for a lot of items and weapons.
-you cannot use gasoline because you cant pick it up. the chainsaw is pointless as you cannot refill it.
-you cannot save the game so you can continue it later.
-while firing in burst mode, your character will target the generator after all nearby enemies are down.

features:
add more items to the caravan, including modded weapons such as rivtech
add skill books to the caravan
make the caravan have a lot less, but randomly chosen (including things that are not in the first caravan) whenever it visits. 
add more locations you can defend
allow repair/ armor/ upgrade of the generator with high electronics and mechanics skill.
make things that explode or cause fire less instant death when inside buildings with roofs

**Comment by Autastic** [comment]
forgot to mention that the GUI is too small for the caravan, cutting off a few of the selections at the bottom and descriptions for a lot of items and weapons.

**Comment by Autastic** [comment]
found another issue, you cannot use gasoline because you cant pick it up. the chainsaw is pointless as you cannot refill it. also, you cannot save the game so you can continue it later.

**Comment by Autastic** [comment]
and another issue, turrets will randomly decide that you are unfriendly if you place one and attack you instead of the enemies.

**Comment by BevapDin** [comment]
> you cannot save the game so you can continue it later.

AFAIK, This is more ore less working as intended.

> and another issue, turrets will randomly decide that you are unfriendly 

That is their normal behavior (applies to most/all electronically monsters that you can place). If your characters skill are low enough, they may screw up the programming of the turret and it may therefor start hostile. This is working as intended (through you could argue about the actual skill requirements).

**Comment by Autastic** [comment]
perhaps that might be the way that it's /intended/ to work, but that isnt the way that it /should/ work. i shouldnt be required to keep the window open at all times, or worry about battery or blue screens. make it an option, at the very least. as for the turrets, that seems like a fair counterbalance. however, they are still too cheap and i shouldnt be forced to dissassemble them whenevre i want to reload them, and since it's my turret, i should be able to adjust the burst size and the sight range. not a bug, those last two, but features that would make defense mode feel more like it should.

**Comment by drbig** [comment]
Given the lack of love for defence mode: maybe mark related issues with a label or some-such?

So it can get included in a milestone at some point?

@kevingranade Any opinion?

**Comment by kevingranade** [comment]
I'm for any and all tags that make things clearer, this sounds like a good
one.

**Comment by mischief** [comment]
+1 for fixing preset characters. given the number of positive/negative traits one might pick for this particular game mode, having to re-select them every time you play defense mode is quite painful.

**Comment by mugling** [comment]
Discussion continues in #17985
