### ISSUE TITLE
More Survival Tools Mod: Mainline Discussion

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#12430]
@Rivet-the-Zombie has suggested before the idea of mainlining some of the content from the mod, so might as well open up the issue of what should go in as main.

I hunger for input and feedback. owo

**Comment by Zireael07** [comment]
EVERYTHING :D

**Comment by chaosvolt** [comment]
Maximum derp. owo

For one, some of the edits to existing recipes would be a good start.

**Comment by Coolthulhu** [comment]
Hobo stove should probably stay a part of the mod until we can give it proper downsides.
Opposite problem with esbit stove - it is too expensive to use now, it will need some buffs.
Not sure about tinderbox. It is a bit unusual and only makes sense when lighters and matches are very expensive.
Flint and steel yes, but without the recipe for it. Or at least with the recipe becoming way more expensive (it is cheaper than fire drill at the moment), for example by requiring a forge or a welder. Could drop in sport supplies.

Curdling milk is also quite weird right now. I'd rather have it stay in the mod until we can clean up and allow it not be "hard-jsoned" to only work with one container type. And it also should rot even if not opened. Those are probably not possible now.

Copper material could be mainlined, probably as a separate PR.

Stone macuahuitl could be in. Or even better: it could totally replace the existing glass one, which no one uses anyway.

A big "no" for hand axe.

**Comment by chaosvolt** [comment]
Hmm. If we had a logical source of good steel for the flint and steel...

And yeah, a lot of these items are kinda derpy and possibly best as mod-only content.

**Comment by graysage1** [comment]
I vote everything +1 too.

@Coolthulhu 

>Hobo stove should probably stay a part of the mod until we can give it proper downsides.

It's bulkier than hotplate by 1 unit of volume and its fuel is twice as voluminous as batteries even with the latest update.  What other downside are you looking for?  I think it's already inferior in every way to the other stoves.  The only advantage is that it uses wood and paper for fuel, which allows you to save batteries (which can be important if you play slowly like me).

>A big "no" for hand axe.

It's just a flavor item.  What's wrong with it?  I don't even make it.  It's basically a wood saw that can cut.  Can you please explain what your concern is?

**Comment by graysage1** [comment]
@Coolthulhu  Is it possible to make the game drop flint and similar minerals as a rare stone?  Then if the flint and steel required actual flint, which was presumably rare, it would be fine, no?

**Comment by graysage1** [comment]
I'd take out the scrap metal option from the hobo stove's recipe.  Ditto ember carrier.  I think these items should only be made from tin or aluminum cans.  It's not like there is a shortage of cans in the game, and using scrap metal is not realistic imo.

**Comment by graysage1** [comment]
Or maybe a can *and* scrap metal.  I just have a hard time imagining how you'd make it from just scrap metal.

**Comment by graysage1** [comment]
Pine lean-to should maybe replace the makeshift shelter?  They serve more or less the same purpose and I don't know if the difference between them is interesting.  Also collecting 24 pine boughs is kind of annoying. :)

**Comment by graysage1** [comment]
For hand axe, it has a quality of tree cutting 1, and I always wondered what that was for.  What can one do with tree cutting 1?

**Comment by chaosvolt** [comment]
Eek. Holy shit, how did this thing not update with all your posts? ;A;

And I'm not sure if tree cutting 1 has any uses, but a couple existing tools DO have that, so it must be used for something.

Might also ponder taking the scrap metal requirement out, though taking smaller cans andmaking a coffee-can-sized hobo stove is derpy since we lack bigger cans.

**Comment by Coolthulhu** [comment]
> What other downside are you looking for?

Crafting time or (less likely) product quality. Neither is possible at the moment.

> The only advantage is that it uses wood and paper for fuel

Which, as you said in the other discussion, means that crafting is essentially free, only "costs" extra keypresses. Things that are balanced by extra keypresses aren't balanced.

> It's just a flavor item. What's wrong with it?

Nearly strictly superior to stone knife while being cheaper, changes the meaning of wood saw quality (if you can saw with a sharp rock, you can saw with a butcher knife). If we ever want to make wood sawing mean something (it doesn't mean much atm), an item like hand axe would be detrimental to that.

> @Coolthulhu Is it possible to make the game drop flint and similar minerals as a rare stone? Then if the flint and steel required actual flint, which was presumably rare, it would be fine, no?

That would require some good drop spot so that players who want it don't have to 'V' through all the rocks around looking for that one kind of rock.
Or have the recipe be not auto-unlock, so that the strict superiority of f&s would be behind a "paper wall".

> Would become an option if we mainlined it, but...

You can have .cpp code that isn't used without a mod. Entire boats mod only implements the parts, not the mechanics.
Though probably a more proper solution would be moving comfiness to a json.

**Comment by chaosvolt** [comment]
Hmm. Right now though, a lot of these items will need tweaking and other supporting elements to permit mainlining, as Coolthulhu has pointed out.

What about the edits to existing recipes though? I for one like the idea of using weed to make plant fiber, but adding hemp stems as a byproduct of harvesting it would be the more logical solution. ;w;

**Comment by chaosvolt** [comment]
Hmm. So, I'm pondering what all to mainline, gonna weigh in with the suggestions I can think of.

Materials:
* Copper material, with corresponding fixes to existing copper items,

Item tweaks:
* As above, tweaks to existing items that should use copper.
* The boost to sling damage.

Item additions:
* Boxer briefs.
* Work gloves, possibly with a further protection nerf from 7/7?
* Wool cloak, loincloth, hand wraps, and foot wraps.
* Metal water bottle.
* Garlic.
* Hard cheese, should probably keep the recipe mod-only for now though.
* Stone macuahuitl, possibly replacing the glass version like @Coolthulhu  said.

Recipe tweaks/additions:
* Curing hides/pelts over a fire, maybe?
* Italian seasoning, because garlic.
* Tweaks to stone hammer, stone shovel, stone axe, and stone adze allowing the use of withered plants for binding (like with stone knife).
* Leather pouch allowing the use of fur.
* Option to make sling from woven strings.

**Comment by Rivet-the-Zombie** [comment]
**All** of the things you just mentioned would be great in mainline.

**Comment by chaosvolt** [comment]
Yay? owo

Also, if/when boxer briefs and work gloves get mainlined, I'm in favor of them getting mixed into the starting gear for a few professions. In the latter case, there are a few working-class professions that start with leather gloves that might warrant work gloves instead.

For now, I'll want to wait until after Series 9 is done.

**Comment by Coolthulhu** [comment]
Work gloves should have higher encumbrance. 10 (when fitted) is still very little - it's as much encumbrance as backpack causes to torso. As work gloves, they shouldn't be suited to manipulating stuff.
Hand encumbrance doesn't affect swinging an axe much, unless it gets absolutely huge.

Non-craftable hard cheese would need some sensible source and be kept limited to it. Not just from regular fridges in houses - the cheese from those should spoil just like the regular cheese from a regular store (not counting the artificial plastic cheese-like products here). Or maybe as a rare (rare!) drop in fridges.

Not sure about metal bottle. Don't we already have few canteens, hip flasks etc.?

Rest of the list looks good.

**Comment by chaosvolt** [comment]
Hmm. When in doubt, add 10 more encumbrance I guess. :V

As for hard cheese, I think we have a "food stash" itemgroup that it might go in maybe.

And as for the metal bottle...true. It does have the boiling quality, but that doesn't work if the bottle is filled with something. If it could at least work while full of unclean water...

**Comment by chaosvolt** [comment]
Also, if I were to replace the glass macuahuitl with the stone version, I'm pondering whether to use the statistically-nerfed version, or simply give the glass version the stone material and tweak its recipe.

**Comment by chaosvolt** [comment]
And then there was a thing. https://github.com/CleverRaven/Cataclysm-DDA/pull/12682

**Comment by chaosvolt** [comment]
Doh. Sorry about that. @_@
