### ISSUE TITLE
Burst fire ignores hostility level (or has too large of an "AOE")

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#12446]
When using burst fire, additional target selection ignores hostility, resulting in silly situations where an NPC (or player) shoots a few zombies and then turns 90 degrees or more and shoots the player (or NPC) for no reason. It would be more reasonable if new targets had to be within, say, 30 degrees of the original target. Targets should also not be fired upon that are not at least as hostile as the original target, perhaps depending on skill. Or perhaps burst should be completely reworked to be similar to a frag grenade, randomly (or semi-randomly, depending on skill) shooting into an area centered on the target.

**Comment by DavidKeaton** [comment]
a rework may be in order, that sounds no fun (shooting your buddies)
