### ISSUE TITLE
Dissector on stairs

### ISSUE THREAD

**Issue by tvm1** [CleverRaven/Cataclysm-DDA#12441]
Today I've descended into laboratories only to find that there's dissector installed on stairs just beneath the surface level. Entering and leaving the labs is therefore very painful and this should be probably fixed.

**Comment by DavidKeaton** [comment]
not as painful as going in the shelter basement to drop into a river of lava!

**Comment by BevapDin** [comment]
Similar to #6127, #11610, this time it's traps, other times it was furniture.
