### ISSUE TITLE
Bugs are found when entering the world[version 0.C-3195]

### ISSUE THREAD

**Issue by nizhuan-jjr** [CleverRaven/Cataclysm-DDA#12453]
16:11:4.633 WARNING : opendir [./save//Glenview/mods] failed with "No such file or directory".
16:11:9.798 : src/veh_typedef.cpp:287 vehicle part laser_guns has the TURRET flag, but is not made from a gun item
17:7:45.275 : src/veh_typedef.cpp:287 vehicle part 2xnailer has the TURRET flag, but is not made from a gun item
17:7:45.714 : src/veh_typedef.cpp:287 vehicle part 4xnailer has the TURRET flag, but is not made from a gun item
17:7:46.88 : src/veh_typedef.cpp:287 vehicle part 2x9mm has the TURRET flag, but is not made from a gun item
17:7:46.888 : src/veh_typedef.cpp:287 vehicle part 4x9mm has the TURRET flag, but is not made from a gun item
17:7:47.476 : src/veh_typedef.cpp:287 vehicle part 2x45 has the TURRET flag, but is not made from a gun item
17:7:47.862 : src/veh_typedef.cpp:287 vehicle part 4x45 has the TURRET flag, but is not made from a gun item
17:7:48.260 : src/veh_typedef.cpp:287 vehicle part 2x22 has the TURRET flag, but is not made from a gun item
17:7:48.663 : src/veh_typedef.cpp:287 vehicle part 4x22 has the TURRET flag, but is not made from a gun item
17:7:49.40 : src/veh_typedef.cpp:287 vehicle part HMG has the TURRET flag, but is not made from a gun item
17:7:49.595 : src/veh_typedef.cpp:287 vehicle part AUTOHMG has the TURRET flag, but is not made from a gun item
17:7:49.1000 : src/veh_typedef.cpp:287 vehicle part lasguns has the TURRET flag, but is not made from a gun item

The mods activated are:
    "Animatronics",
    "ew_pack",
    "More_Survival_Tools",
    "nw_pack",
    "necromancy",
    "blazemod",
    "Zombie_Nightvision",
    "DinoMod",
    "JMod",
    "RL_Classes",
    "boats"

**Comment by Rivet-the-Zombie** [comment]
Sounds like blazemod is acting up again.

**Comment by nizhuan-jjr** [comment]
I've located the key file relating to these bugs, blaze_parts.json.

**Comment by nizhuan-jjr** [comment]
blaze_weapon.json may be another key file.

**Comment by nizhuan-jjr** [comment]
Take 'lasguns' as an example.
There's a code in blaze_parts.json saying "item" : "lasguns",
but nothing related to 'lasguns' can be found in blaze_weapons.json, where it should have something related to 'lasguns'.

**Comment by OsobistSCP** [comment]
So... Any thoughts how to fix it?

**Comment by nizhuan-jjr** [comment]
I think the problem has already been resolved in the lastest version.

**Comment by mugling** [comment]
OP reports resolved
