### ISSUE TITLE
0.C.1 deleting folder of a mod present in user-default-mods.json causes game to crash at attempt to generate new world

### ISSUE THREAD

**Issue by Vsevolod-Shustov** [CleverRaven/Cataclysm-DDA#12466]
Just what the title says.

**Comment by DavidKeaton** [comment]
well... yeah... :-P

**Comment by Rivet-the-Zombie** [comment]
By setting it to default, you're telling the game that it's required to generate a new world. When you delete it, the game gets confused.

Either disable it from that list, or else don't add it to the list in the first place.

It probably also wouldn't hurt if we changed it so the game would throw an error message in such cases, and then just skip the mod entirely, but that's a whole other thing.

**Comment by narc0tiq** [comment]
Crashing certainly isn't the right behaviour, regardless.

**Comment by DavidKeaton** [comment]
agreed, however it reminds me of the "killing process at tombstone" issue. lol.

**Comment by Rivet-the-Zombie** [comment]
Yeah there's a certain amount of 'you did it to yourself' at play in cases like this. I agree that it shouldn't crash in this case (as I pointed out in the closing lines of my comment) but there's only so much we can do to prevent people from figuratively shooting themselves in the foot.

**Comment by DavidKeaton** [comment]
agreed. at worst, handle the error and show it. at best continue world creation without the mod.
