### ISSUE TITLE
Make apparent that some scenarios ignore settings and start in winter

### ISSUE THREAD

**Issue by tvm1** [CleverRaven/Cataclysm-DDA#12465]
Many players wonder why their game starts in winter, although they have selected different season in the world creation dialog.

This issue was reported again today by Drunken_ on IRC. 

If there is override of the player defined starting season, it must be definitely emphasized in the scenario selection menu.

**Comment by narc0tiq** [comment]
Agreed. It might not be a bad idea to reformulate the interface to be more like the profession screen, with all the interesting relevant bits shown in order of importance (season override being the topmost of those, I would think).
