### ISSUE TITLE
Provide an in-game option for ambiguous-width characters

### ISSUE THREAD

**Issue by jakwings** [CleverRaven/Cataclysm-DDA#12474]
Related issue: #11387

Problem: Ambiguous-width characters are not handled properly for various fonts, leaving some rubbish after the erasure of text or making some characters overlaped with other characters.

Although iTerm2.app on Mac provides a toggle to treat ambiguous-width characters as single-ascii-char width, users still need to find a suitable CJK font for the game. And the translators must be very careful when translating.

The core function to deal with the ambiguous-width characters from iTerm2.app: https://github.com/gnachman/iTerm2/blob/35bfdc1d2e2e2aed05a6add20a9edb528a7748bf/sources/NSCharacterSet%2BiTerm.m

Common ambiguous-width characters:

```
“…”(ellipsis) “—”(em dash) “─│┐┘┌└┤┬├┴┃━┏┛┓┗┫┳┣┻…”
```

And a screenshot for text in a dialog from the game:

```
123456789012345678901234567890123
┌───────────────┐
│ a使用         │
│ R読む         │
│ E食べる       │
│ W着る         │
│ w装備         │
│ t投げる       │
│ T脱ぐ         │
│ d置く         │
│ U取り外す     │
│ r再装填       │
│ D分解         │
│ =キー割り当て │
│ +自動取得     │
│               │
│               │
│               │
│               │
└───────────────┘
123456789012345678901234567890123
```

![ambiguous-width characters](https://cloud.githubusercontent.com/assets/1451509/7826651/e99fc9e0-044f-11e5-953a-f8104136141c.png)

---

Some screenshots from #11387:

When “Treat ambiguous-width character as double width” is off:
(“…” overlaps with “│”)
![OFF](https://cloud.githubusercontent.com/assets/1451509/7825458/b0cd60d8-043f-11e5-804b-31391b6d5553.png)

When “Treat ambiguous-width character as double width” is on:
(“…” still overlaps with “│”)
![ON](https://cloud.githubusercontent.com/assets/1451509/7825463/b969b548-043f-11e5-874d-b70cd296f564.png)
##

**Comment by narc0tiq** [comment]
For comparison, I pasted the 33-character width text block into a vim session and got this:

![17 width](http://i.imgur.com/rd37E7N.png)

The ideograms look the same to my untrained eye, but something (Putty? DejaVu Sans Mono?) makes things fit nicely on my terminal. Peeking at my PuTTY options, I have the setting to "Treat CJK ambiguous characters as wide" turned off, for whatever that's worth.

**Comment by DavidKeaton** [comment]
same setup for my SSH Narc.

**Comment by jakwings** [comment]
@narc0tiq Yes, it is ok if you have the suitable font and you don't mind using that font. It mainly depends on the font, not the calculated width. With my font, the text will always get overlaped. I really like the high quality font on my mac… (Well, I know not many mac users play this kind of game.)

I'll try to obtain a list of ambiguous-width characters later.

**Comment by narc0tiq** [comment]
Thanks for the clarification. Yeah, I see that your font does look very nice indeed.

Beyond that, I'm not sure what we, as the application running inside the terminal, can do to help. Print spaces with the CJK characters to force them to take up two characters? Would that do it, or just break things?

**Comment by jakwings** [comment]
@narc0tiq The half-width space has been companied with the full/double-width kanji for a long time, so it is not necessary to use the full/double-width space “　” (U+3000) everywhere.

Only the tab characters, which are often used to draw maps and dialogs, need more careful calculation.

**Comment by jakwings** [comment]
Here is more screenshots of UI glitches:

![Different Rendering](https://cloud.githubusercontent.com/assets/1451509/7832262/4594d85e-0490-11e5-82f4-12dee5073989.png)

![Not properly cleared](https://cloud.githubusercontent.com/assets/1451509/7832266/4c63e404-0490-11e5-9d29-780c2e30a4d0.png)

**Comment by jakwings** [comment]
With regard to the size of houses and the floors and windows and doors…, I think it is better to leave the glitches for the borders, and to calculate the correct width for the readable text.

```
┌──────────────────────┐
│......................│
│......................│
│......................│
│......................│
│......................│
│......................│
│......................│
│......................│
│......................│
│......................│
│.........@............│
├─+"──+─"─'──"+───+───+┤
```

![Please don't mind the gap. ;-)](https://cloud.githubusercontent.com/assets/1451509/7833293/437a68ec-0498-11e5-962d-31f9616ed17a.png)

**Comment by jakwings** [comment]
Can you tell me where is the core functions to deal with all those text and borders, and the character set to draw maps. I know some C++ and maybe I can help to provide a better mac build. :-D

**Comment by BevapDin** [comment]
SDL: line drawing does not use the font, it manually draws lines, look at `Font::draw_ascii_lines` in sdltiles.cpp
ncurses: the values of the `LINE_XOXO` and similar constants (see output.h) are printed. They apparently match the `ACS_VLINE` and similar constants from ncurses.

**Comment by Leland** [comment]
@BrettDong should this be kept open?

**Comment by kevingranade** [comment]
Either this one or #11387 should stay open, it's a real and serious bug.

**Comment by Night-Pryanik** [comment]
We've done some serious work related to fonts. Can anyone confirm whether this issue is still valid?

**Comment by I-am-Erk** [comment]
I have not seen this issue on any of my language testing but I've only used the one platform. I am inclined to close this, and if someone can let us know it still exists, we can reopen it.
