### ISSUE TITLE
Recent changes to the lua-interface cause warnings/errors during compilation

### ISSUE THREAD

**Issue by namarrgon** [CleverRaven/Cataclysm-DDA#12470]
PR #12451 introduced warnings during the build with LUA=1 that turn into errors with RELEASE=1 and so cause the build-process to fail. Apart from that there doesn't seem to be anything obviously broken.
```
g++ -DLOCALIZE -Wall -Wextra -g -D_GLIBCXX_DEBUG  --std=c++11 -MMD    -DLUA  -c src/catalua.cpp -o obj/catalua.o
src/catalua.cpp: In instantiation of ‘static T& LuaValue<T>::get(lua_State*, int) [with T = point; lua_State = lua_State]’:
src/lua/catabindings.cpp:1429:46:   required from here
src/catalua.cpp:272:85: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
             return *(T*) luaL_error( L, "First argument to function is not a class" );
                                                                                     ^
src/catalua.cpp: In instantiation of ‘static T& LuaValue<T>::get(lua_State*, int) [with T = tripoint; lua_State = lua_State]’:
src/lua/catabindings.cpp:2434:52:   required from here
```
gcc version 5.1.0 (GCC):
https://gist.github.com/namarrgon/a3b19389247076eec5a1

clang version 3.6.1 (tags/RELEASE_361/final):
 https://gist.github.com/namarrgon/18faacd31875879516e5

**Comment by narc0tiq** [comment]
The Jenkins builds noticed, too, e.g., http://ci.narc.ro/job/Cataclysm-Matrix/Graphics=Curses,Platform=Linux_x64/3215/console -- looks fine on 32-bit, but all the 64-bit builds fail. With more errors than just that, even.

**Comment by BevapDin** [comment]
> but all the 64-bit builds fail.

Maybe the Pull Request builder should build a 64-bit binary? Otherwise those errors can go in easily. There is also the problem of `int` vs `long` which on 32-bit system seems to be the same, but on 64-bit they are different (wasn't that a problem recently).

**Comment by narc0tiq** [comment]
> Maybe the Pull Request builder should build a 64-bit binary?

Makes sense to me -- it wasn't an option when initially set up, but we can do that now and the 64-bit builds do seem to be the more fragile ones. Done.

**Comment by DavidKeaton** [comment]
`long long` vs `long`, etc etc
