### ISSUE TITLE
Options for removing walls without bringing the house down.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#12488]
Problem: When remodeling a house, you're likely to bring down sections of roof when you take out walls.

Some solutions I thought of:
Construction option to remove wall is the most straightforward.
A fun option is to add a floor jack that you can place as furniture that has the "supports roof" flag, then do your smashing, then take down the jack with no or very low chance of collapse.
##

**Comment by tvm1** [comment]
Yeah, wall deconstruction option is really necessary.

**Comment by Zireael07** [comment]
Both construction and floor jack are nice ideas.

**Comment by tvm1** [comment]
Floor jack could do it, rather heavy item. Could be found in home improvement store.

**Comment by kevingranade** [comment]
A more simulationist way to do this is to designate (either manually or algorithmically) some number of walls to be "load bearing" and a way to tell them apart, non-load-bearing walls would be relatively safe to smash without triggering a collapse, and load-bearing walls would also be tougher.  Ideally a horde of zombies is unlikely to smash the load-bearing members of a building, but will go ahead and destroy all the partition walls,
