### ISSUE TITLE
inconsistent encumberance between sleeveless items

### ISSUE THREAD

**Issue by Cat09** [CleverRaven/Cataclysm-DDA#12499]
some items, such as the duster and survivor duster don't change encumberance for the sleeveless versions, while others (like the trenchcoats) do.
if we have a specific way we want to go on that I can edit that file to make it consistent, my vote is to keep it the same - the arms pick up the encumberance of the added material

**Comment by PropaneSoup** [comment]
I'd say keep it the same as well, I couldn't think of a reason it wouldn't. I did go through the file a while ago, the inconsistency may be my fault.

**Comment by DavidKeaton** [comment]
The arms on the sleeveless version? I'd politely disagree! Leather jackets' arms are fairly prohibiting. I can recall several times I shed mine to do more dexterous tasks.

**Comment by PropaneSoup** [comment]
The idea is though that removing the sleeves decreases the encumbrance on the torso as well. Is that what you're talking about?

**Comment by DavidKeaton** [comment]
Ah in that effect, hell no. Lol. Still cumbersome to move the torso.
