### ISSUE TITLE
Friendly NPCs stand and watch as you are beaten to death by Hostile NPC

### ISSUE THREAD

**Issue by Dunkhan** [CleverRaven/Cataclysm-DDA#12506]
If an NPC goes hostile to a player who has followers, the followers remain set to neutral to the hostile NPC. This means you can be walking around with a group of multiple well aremed NPCs, and have them stand around watching as you are beaten to death by some ****** with a pool que.

I realise the system is WIP but this is something that needs to be thought out. The player generally expects that friendly NPCs will help out in such a situation, and if for any reason it is decided they should not (loyalty too low, afraid, etc.) the player should at least have some feedback about it.

**Comment by Ygdrad** [comment]
Is this really a bug? I was thinking of making modifications to NPC behavior and make them fight other NPC's and ran into this bit of code in npc.cpp

>Creature::Attitude npc::attitude_to( const Creature &other ) const
>{
>    if( other.is_npc() ) {
>        // No npc vs npc action, so simply ignore other npcs
>        return A_NEUTRAL;

Is their neutrality to other NPCs desired? Is this for balance or was this just put there until something else is implemented? I'd like to know if the devs want them to remain neutral so I don't pointlessly try to make them fight each other.

**Comment by Rivet-the-Zombie** [comment]
>Is their neutrality to other NPCs desired? Is this for balance or was this just put there until something else is implemented? I'd like to know if the devs want them to remain neutral so I don't pointlessly try to make them fight each other.

I'm pretty sure that's intended to be a placeholder until we have better NPC AI. Ideally NPCs would be capable of fighting each other when the situation calls for it.

**Comment by kevingranade** [comment]
Agreed, having friendly NPCs fight hostile NPCs is desirable.

**Comment by mugling** [comment]
Pretty sure it's fixed in `master`
