### ISSUE TITLE
Incorrect volume and weight value of battery 

### ISSUE THREAD

**Issue by Marberguson** [CleverRaven/Cataclysm-DDA#12519]
After pick up over 200 batterys happened this
![error2](https://cloud.githubusercontent.com/assets/12687419/7904122/c60c04ae-07f0-11e5-8343-81903f097b87.png)

 ![error](https://cloud.githubusercontent.com/assets/12687419/7904081/7fe6b52e-07ef-11e5-890e-3e12b1e85761.png)

**Comment by molkemon** [comment]
Well, if I pick up 200 batteries it seems to work fine, cannot reproduce here. Even if I (try) to pick up about 15000 batteries, the values seem ok (I can't actually do it because too little volume free).

**Comment by DavidKeaton** [comment]
Just sounds like an integer overflow/sign issue.

**Comment by mugling** [comment]
Closed due to lack of confirmation at 5 months. @Marberguso please re-open if you can reproduce in `master`
