### ISSUE TITLE
Improvement suggestions for normal inventory screen

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#12516]
The AIM screen has seen magnificent updates these past few weeks, but can we have some improvements to the standard inventory screen aswell? 

My base suggestions would be: 

-Alphabetical sorting within the categories
-Possibly have the equipped items divided by body part sub-categories, or at least alphabetical aswell. Right now, if you are wearing lot's of clothing, it is extremely tedious to find a specific item for improvement/taking off.

**Comment by BevapDin** [comment]
> Alphabetical sorting within the categories

Uhm, that's how it currently works, isn't it?

**Comment by molkemon** [comment]
It is in AIM, but on the normal inventory screen, it's basically completely random.

**Comment by Rivet-the-Zombie** [comment]
From the looks of that screenshot, it's sorting the items alphabetically by item_ids instead of the in-game names.

**Comment by BevapDin** [comment]
> It is in AIM, but on the normal inventory screen, it's basically completely random.

My fault, I misread your text.

> From the looks of that screenshot, it's sorting the items alphabetically by item_ids instead of the in-game names.

Exactly.

The inventory screen uses the order of the items in the inventory class, which in turn uses the `item::operator<` to sort the items. That operator compares by category, type (id) and charges (in that order). That should be changed.
