### ISSUE TITLE
[3234] plurial on aspirin

### ISSUE THREAD

**Issue by Bakit** [CleverRaven/Cataclysm-DDA#12511]
when you drop some aspirins you'll see "aspirinss" with 2 "s".

**Comment by Sirbab** [comment]
Is this in a vehicle, or no?

**Comment by Bakit** [comment]
Yes

**Comment by Sirbab** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/12342 Had a similar/related issue, afaik it was not fully addressed.

**Comment by DavidKeaton** [comment]
It still occurs in a few items. Probably just needs some hunting.

**Comment by BevapDin** [comment]
This was fixed by 2d3d6b8e.
