### ISSUE TITLE
AIM doesn't default to Vehicle storage

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#12523]
Advanced inventory management doesn't default to vehicle storage anymore. If I set AIM to have my inventory on one pane and 5 + Vehicle below me (so it should show me whatever is in the vehicle cargo space I'm standing on), and I move to another tile and open AIM again, it will have disabled the Vehicle option and instead show me the ground below the vehicle. This is extremely aggravating.

**Comment by DavidKeaton** [comment]
Oh it is irritating, I know. I was gonna add a quick fix for it today actually. Won't be hard.

**Comment by DavidKeaton** [comment]
There ya go mate. :-)

**Comment by molkemon** [comment]
Thank you a lot, this issue was slowly eating away my sanity :)

**Comment by DavidKeaton** [comment]
Oh I feel you, trust me. My own irritation is what made me want to fix it lol.

**Comment by DavidKeaton** [comment]
Thanks @Coolthulhu :-) Hope that helps OP!
