### ISSUE TITLE
Minifridge isn't cooling drinks properly

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#12522]
I think this is not a new issue in the current experimental, but it's the first time I really paid attention: Drinks in the fridge, which should get (cold) after a while really don't or at least not consistently/reliably. I've had some drinks for MONTH in the fridge, and they still are not cold. Some drinks temporarily switched to cold when it had -13°C outside and i left the doors open, but they have since returned to not-cold. Obviously, the fridge is turned on and I also got plenty of battery. As I said, sometimes, some drinks get temporarily cold, see screenshot. 

http://i.imgur.com/aDyyTFs.png

**Comment by Sirbab** [comment]
Something to consider, is that not all of the drinks in your fridge have the EATEN_COLD tag, afaik they will not be cooled without said tag.  That being said, the cola, energy drink and a lot of others in there should be getting cold.

**Comment by molkemon** [comment]
When it was -13C outside, some of the colas got cold (like 4 out of 6 etc), but never the entire stack, so there's that aswell.
