### ISSUE TITLE
"Armored" electronics store still has unarmored windows

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#12538]
The electronics stores with bars for windows still have easily smashable un-alarmed windows that allow easy entry.

**Comment by Night-Pryanik** [comment]
Should be closed? As for 0.C-4321 electronics shops have alarmed windows with metal bars.

**Comment by Coolthulhu** [comment]
There is one store that has armored doors and metal bars up front, but still has a backroom with regular windows and wooden doors.
