### ISSUE TITLE
Skeletal enemies no longer attacking player

### ISSUE THREAD

**Issue by PropaneSoup** [CleverRaven/Cataclysm-DDA#12530]
Both skeletal dogs and skeletons don't intentionally attack the player anymore. They are marked as hostile, but just stumble around randomly as if the player wasn't there. If you stand next to one long enough, it looks like it'll stumble into you and auto attack you, and they'll still use their special bite attack. But they will not chase down the player. No idea what could have caused this.

**Comment by Nioca** [comment]
It's not just skeletal enemies; as best I can tell, grenadier-launched hacks are also effected (they'll arm themselves, then just fidget about until they detonate), Animals also seem to be behaving oddly; I keep getting attacked by groundhogs and squirrels, but coyotes and bigger seem to just fidget even when hostile. I actually watched a Cougar engage a Zombie Grenadier... and do absolutely nothing. It leapt around, but never actually made an attack against the Grenadier despite getting mauled in return.

**Comment by Coolthulhu** [comment]
The problem affects all non-bashing monsters. The fix is in the referenced PR. I could extract it and PR separately, but I think it shouldn't be too buggy to hold it for long - it is rather small.
