### ISSUE TITLE
Cephalopod Vision removes uglyness and visibility ration.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12546]
The description of Cephalopod Vision ( http://www.wiki.cataclysmdda.com/index.php?title=Cephalopod_Vision ) hints that only the brain is changed, not the outer looks of the player (From the prereq: Cephalopod Eyes http://www.wiki.cataclysmdda.com/index.php?title=Cephalopod_Eyes). The visibility rating and uglyness rating is dropped however. Seems like a small oversight to add back in the uglyness and visibility of the eyes. ( 5, 8).

**Comment by DavidKeaton** [comment]
You bring this up because you *are* a Cephalopod! I see your picture!

**Comment by Soyweiser** [comment]
Well I was a half cephalopod half human, and people reacted strange. When I changed my transspecies conversion suddenly people acted normal. So I wondered what was up :P

On a more serious note, some of the other values might be off on mutations as well. And looking at some of the 'cancels' info seems off. Like different types of eyes not cancelling other types of high end night vision. But not sure how the mutation system works.

**Comment by DavidKeaton** [comment]
We've had to tweak the "cancels" in the past, however others may be better to ask in regards to that, I haven't messed with mutation code at all.

In regards to your new form, Congrats! I hope the insurance on species masking didn't cost you an arm and a leg and another arm and another leg... (... ad nauseum) :-P

**Comment by Soyweiser** [comment]
Seems no longer an issue, as the "Cephalopod Vision", now has "prereqs" : ["CEPH_EYES"] and no longer just cancels the upgrade mutation.
