### ISSUE TITLE
New AIM bug after vehicle fix

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#12542]
Fixing AIM to not default to vehicle tiles introduced a new bug unfortunatly: 
If you actually have stuff on the ground below the vehicle and try to move it anywhere (no matter if inventory or other tile/vehicle tile), after moving 1 item the pane with the ground view auto switches to vehicle view, causing massive confusion.

**Comment by DavidKeaton** [comment]
Aww man, you for real? :-(

**Comment by molkemon** [comment]
Afraid yes, but there's a bright side: While this new bug is in theory far more disruptive when you have to deal with it, it isn't quite as annoying as it was before, because it really only effects you if you actually  use the space below a parked vehicle, which is usually rarely to never, so it doesn't really impede the gameplay as much as the other bug did, but in the rare cases you need the inventory below the car, it gets really confusing :D

**Comment by DavidKeaton** [comment]
Still, seeing as how I rewrote most of AIM, I take it upon myself to fix bugs. Thought I had them all! Drats!
