### ISSUE TITLE
Weird black flashing while moving in newest experimental

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#12543]
With newest experimental, moving results in weird black flashes whenever you move a few steps in any direction. It's just for like 1 frame and the screen goes blank (and the message log appears blank the frame right after, but comes back if you take another step). This happens on old saves aswell as newly generated worlds.

**Comment by namarrgon** [comment]
git bisect is pointing at 857aae4b5d6f06e5874bd37bfc64d9a167784c2e as the first bad commit.
"Add some documentation to the item class [CR] #12520"

**Comment by BevapDin** [comment]
> git bisect is pointing at  857aae4  as the first bad commit.

I've got a very unsettling feeling about this. The PR does not change anything (at least it's not supposed to do). I'm looking into this. Thanks for bisecting it.
