### ISSUE TITLE
Negative effects from addiction not removed after satisfying it

### ISSUE THREAD

**Issue by joneskun** [CleverRaven/Cataclysm-DDA#12547]
Specifically, morale-based speed penalties persist. Perhaps others as well, but this one has the biggest impact.
##

**Comment by kevingranade** [comment]
I'll double check, but I think this is working as intended.  The effect of
the drug might offset the morale effect indirectly, but in general morale
effects don't disappear immediately when the cause disappears.

**Comment by joneskun** [comment]
I'm actually talking about withdrawal symptoms, somehow forgot to mention that. I haven't had any /ragequit moments with addiction effects proper.

**Comment by kevingranade** [comment]
What are we talking about?  Morale effects from withdrawal or something
else?  If it is, the source of the morale effect is irrelevant, they simply
don't go away when their cause is removed, it takes time.

The best would be steps to cause the issue, a description of what you
expect to happen, and a description of what actually happens.

**Comment by joneskun** [comment]
Simple enough. Roll some random characters until you get a hobo or a tweaker. These are 1pt professions. You'll soon end up with 0 INT, 0 DEX, 0 PER, 25 speed, hallucinations, etc.

It's cool if you can manage these effects, but the current abstractions result in a binary solution - you find a place to hide and sleep it off, or you don't. I think there's some good early gameplay here, just needs a little adjusting.
