### ISSUE TITLE
Bone glue recipe is missing the heat source

### ISSUE THREAD

**Issue by and-dmitry** [CleverRaven/Cataclysm-DDA#12564]
Bone glue recipe mentions boiling and requires a tool with cooking  2 or more but misses a heat source. It should require a nearby fire or a hotplate. I'm not sure if charcoal smoker or something else is also acceptable.

**Comment by illi-kun** [comment]
Charcoal smoker isn't a proper source of heat, I suppose.

**Comment by and-dmitry** [comment]
Here's a list of heat sources for making clean water:

```
      [ "hotplate", 3 ],
      [ "char_smoker", 1 ],
      [ "toolset", 3 ],
      [ "coffeemaker", 3],
      [ "atomic_coffeepot", -1 ],
      [ "fire", -1 ]
```

* toolset is described as a dummy item
* coffee machines will probably break if you use them for boiling glue
* hotplate or fire will do
* charcoal smoker description says "Good for weekend barbecuing and preserving meat with smoke." If it's suitable for barbecuing, it's suitable for boiling.

So I think it's fire, char_smoker and hotplate.

**Comment by illi-kun** [comment]
See discussion in #12058
