### ISSUE TITLE
Give item/creature classes a map of "flags with parameters"

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#12570]
We could have a `map<string, int>` for non-performance-intensive variables in item and creature (and item type and monster type) classes.
This would mimic the current flag set, except with an extra bit (64 bits more, to be precise) of extra customization.

Possible uses:
* `"bite_damage": 8` read in `monattack::bite`, letting tough zeds bite harder and decayed zeds infect more
* Nicely handling `LIGHT_x` flags instead of hardcoding them
* Giving creatures some customized AI information without using a horrid hack like in `monattack::searchlight`. This could be, for example, giving NPCs proper timed designations instead of the current `effect` method, which is a bit of an overkill
* Charger guns not re-using `poison` member, because even though it works, it sounds just silly
* Non-consumable items not even having the `poison` variable
* Multiples of the same mod. Quad battery flashlight! Double leather-reinforced leather chaps!

Anything wrong with this idea?

**Comment by Rivet-the-Zombie** [comment]
I like it.

**Comment by tyrael93** [comment]
Wonderful. Even though I'm not too keen on double Kevlar reinforced jumpsuits or god forbid heavy survivor armor

**Comment by BevapDin** [comment]
For monster/item types, that should be properly typed members. If that data is large, put it into an optional `unique_ptr`.

For monsters probably, too. They are not copied that often and there are usually not many of them on the map, so making the class larger won't harm much.

A generic `map<string,int>` removes all the advantages of a statically typed language.

----

> "bite_damage": 8  read in  monattack::bite , letting tough zeds bite harder and decayed zeds infect more

`monattack` should be a class (similar to `iuse_actor`), each monster type should have a set of instances of them.
```C++
class bit_attack : public monattack {
    int bite_damage;

    void attack( monster &z );
};
```

Maybe even make those instances copyable and give each individual monster their own instances (copied from the monster type):

```C++
class bit_attack : public monattack {
    int current_timeout = 0;
    int attack_timeout; // loaded from json
    int bite_damage; // loaded from json

    monattack *clone() {
        return new bit_attack(*this);
    }
    void try_attack( monster &z )
    {
        current_timeout--;
        if( current_timeout > 0 ) {
            return;
        }
        do_attack_internal( z );
        current_timeout = attack_timeout;
    }
};
```
`mtype` contains a list of pointers to those, each new monster makes a deep copy of that list. The base class `monattack` could also hold some of the helper function (target selecting etc.). Each monster could thereby have slightly different attacks.

> Nicely handling  LIGHT_x  flags instead of hardcoding them

Definitely a separate member of `mtype`. Same for item type.

> Giving creatures some customized AI information without using a horrid hack like in  monattack::searchlight . This could be, for example, giving NPCs proper timed designations instead of the current  effect  method, which is a bit of an overkill

Don't stuff all this into a map, use separate, properly typed members. AI would certainly require complex data structures.

> Charger guns not re-using  poison  member, because even though it works, it sounds just silly
> Non-consumable items not even having the  poison  variable
> Multiples of the same mod. Quad battery flashlight! Double leather-reinforced leather chaps!

Use `item_vars`, use `item::get_var(xxx, 0)` to get an integer (the function automatically converts the stored string to int). It is not nice, but seems to offer a good compromise in the case of single values.

Similar things exists as `Creature::values` (but without functions to access it).

----

For code that only needs one value (e.g. poison, charger gun status, number of leather reinforcements, mission-id, ...), the map is good.

For complex things (`monattack::searchlight` uses at least "SL_PREFER_UP", "SL_PREFER_DOWN", "SL_PREFER_RIGHT", "SL_PREFER_LEFT", "SL_SPOT_X", "SL_SPOT_Y"), put them in a proper struct.

**Comment by Coolthulhu** [comment]
> monattack should be a class (similar to iuse_actor), each monster type should have a set of instances of them.

I actually tried writing something like this. This would obviously be the "proper solution", but it's not all that lightweight (mostly boilerplate, but still). I may retry some day.

> Definitely a separate member of mtype. Same for item type.

Why? Is it more of a performance or a code quality kind of thing? If performance, then I have no further questions here, but if code quality then I don't really understand why.

> Don't stuff all this into a map, use separate, properly typed members. AI would certainly require complex data structures.

Yeah, the hack would only make sense for some simple tasks. While we're at AI, I'll ask a tangentially related question:

What about AI data that isn't shared between "tasks"?
Say, we have two tasks: "find item" and "kill monster you see". For small data sets it makes sense to include all the data of both in `npc`. But let's say that the item finding task carries a large block of data (searched locations), while the monster task instead remembers the entire `monster` as it was seen last time.

What would be the proper way to solve this?
I thought about making a base class (`task`) and deriving both tasks from it. The NPC would then have an unique_ptr for the task. However then I'd have to either cast the task to its derived class or expose a large part of npc class to the task and write a great deal of logic there.
Would cast be OK there? Any better way?

**Comment by kevingranade** [comment]
The general approach for the task thing would be to try and derive a set of
universal interactions like rate(), update(), perform() that the npc can
invoke on the task (or in pattern-ese 'strategy'), the base task class (a
pure abstract class ideally) defines those methods and the individual
strategy implementations override them and have whatever state they need
(unique_ptr is the right handle to hold onto if you need an instance of the
thing that holds or might hold state).
For the larger issue, I feel like there's a tradeoff to be made between
ease of implementation and robustness of the resulting code.  If an
attribute is used in one or two places as a simple value, I feel like what
you're suggesting is reasonable, but something like an AI strategy gets
complicated pretty fast, and needs to have its bounds carefully defined.

**Comment by BevapDin** [comment]
>>>LIGHT_*
>>Definitely a separate member of mtype. Same for item type.
>Why? Is it more of a performance or a code quality kind of thing? If performance, then I have no further questions here, but if code quality then I don't really understand why.

Both. About code quality: using a generic map disables the compile time checking, e.g. store the entry under "light", read it as "ligth". If it's a proper member, the compile tells you about this.

It's much more efficient (the member name is not stored in the binary), faster, and avoids conflicts with other data, e.g. several monster attacks might accidentally store their data in the very same map entry overriding each others data.

If you want the map, why not put *every* member of the class in a generic map?
