### ISSUE TITLE
Hotwiring message

### ISSUE THREAD

**Issue by wmafie** [CleverRaven/Cataclysm-DDA#12572]
Currently there is a message about hotwiring a vehicle specifically:

"You could use a screwdriver to hotwire it."

With the changes to screwdrivers no longer having screw_fine , should the message be re-written to reflect that the player would now need screwdriver set? Or should the conditions be changed so that hotwiring can be done with just a normal screwdriver?

**Comment by DavidKeaton** [comment]
Normal screwdriver would be fine, no need for a whole set.
