### ISSUE TITLE
Security camera vision range is square in "circular distances" mode

### ISSUE THREAD

**Issue by eliotcougar** [CleverRaven/Cataclysm-DDA#12585]
With the new vision and lighting system implementation, security cameras have been overlooked slightly... They should use circular distances too...

**Comment by DavidKeaton** [comment]
is it not using rl_dist()?

**Comment by DavidKeaton** [comment]
I am currently looking at this, but if someone else fixes it, by all means. :-P
I see the problem, just need to tinker with the fix.

**Comment by DavidKeaton** [comment]
the fix is a bit outside of my grasp, as this is only my second foray into lightmap. I see the issue, know where it needs to be, but can't quite get it there.

**Comment by eliotcougar** [comment]
Fixed.
