### ISSUE TITLE
Wrong skill used by a weapon

### ISSUE THREAD

**Issue by OsobistSCP** [CleverRaven/Cataclysm-DDA#12584]
RM228 shotgun uses a "handguns" skill instead of "shotguns".

**Comment by macrosblackd** [comment]
I believe this is intentional. `...the Rivtech RM228 caseless short double-barrel shotgun was designed for ...`

**Comment by OsobistSCP** [comment]
Don't think so. I always guessed that skill picks for weapons should be based on weapon mechanics, constrution and properties, not on its size.

**Comment by macrosblackd** [comment]
It's based on how it's handled during use. In this case, due to it's
size, it is handled more like a two shot pistol.

**Comment by Rivet-the-Zombie** [comment]
>It's based on how it's handled during use. In this case, due to it's size, it is handled more like a two shot pistol.

This right here. We also have the 12 gauge pistol which uses handgun skill as well.

**Comment by DavidKeaton** [comment]
I actually say I agree with @OsobistSCP on this one. Although for consistency it can be pistol, as the shotgun pistol uses pistol skill, not shotgun.

**Comment by OsobistSCP** [comment]
Um, it is possible to handle a common sawed-off shotgun like pistol, by one hand. Does it mean that it should use the "handguns" skill to?

**Comment by Frouade** [comment]
I agree with @OsobistSCP, even if it is small shotgun it is still shotgun and should use "shotguns" skill accordingly.

**Comment by kevingranade** [comment]
It's how you handle it, not what it is, and you can only handle a sawn-off
like a pistol if you really don't feel like hitting anything.

**Comment by Griffinhart** [comment]
Here's a conundrum for you, then: what skill would a [Taurus Judge](http://en.wikipedia.org/wiki/Taurus_Judge) use? It resembles a revolver in every single way, but it fires .410 bore shot shells.

(Personally I'm in agreement with the rest of the thread i.e. handling dictates skill, not the projectile, but I'm not a dev.)

**Comment by DavidKeaton** [comment]
Taurus = pistol. Fun firearm to shoot btw.
