### ISSUE TITLE
Inconsistent time usage of sling and slingshot

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12588]
While having 68+20 torso enc I can still shoot a sling in 90 time units, while a slingshot uses over 200. Seems like somewhere there is bug there.

Throwing skill 10, marksmanship 2.88, archery 0.95.

Edit:
The sling might be acting like a firearm, I assume firearms do not get speed penalties from torso enc.

**Comment by mightyagrippa** [comment]
A slingshot uses the archery skill, a sling uses the throwing skill. The disparity was probably due to your high throwing skill discounting both the reload time and firing time of the sling.

**Comment by Soyweiser** [comment]
Closed, see #16545
