### ISSUE TITLE
New behaviour system makes random monsters less agressive

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12581]
Using the new behaviour system some monsters seem to not be agressive at all.

Like ants, and the various hacks. I encountered a grenadier and his hacks flew around him like bees around a hive, and didn't seem to go for me. (not sure if that is as intended).

And random manhacks in labs didn't attack me at all.

Others also noticed this: http://smf.cataclysmdda.com/index.php?topic=19.msg235701#msg235701

As intended?

**Comment by Coolthulhu** [comment]
In newest experimental, manhacks attack just fine.

Ants don't get hostile though - I'll look into it.

**Comment by Coolthulhu** [comment]
OK, (non-soldier) ants simply aren't aggressive unless you're hurt, hurt them or their friends.

**Comment by Soyweiser** [comment]
Allright, fixed then. Will need to upgrade my experimental (not running the latest).
