### ISSUE TITLE
Launcher Skill Weapons

### ISSUE THREAD

**Issue by acidia** [CleverRaven/Cataclysm-DDA#12592]
The NPCs that have their primary weapon skill as "launcher" currently always use some type of flame thrower because those are the weakest weapons in the field.  I'd recommend converting spear guns and any other sub-sonic large projectile/ballistic weapons to the launcher skill to balance things out and provide a means of actually training the skill.  If there are any ideas for one or two more weak launchers then it'd be a big help preventing flame thrower spam.  I know we can't take two ammo types at once so potato guns, clay pigeon throwers, and pitching machines are kinda out.  I've been playing with NPCs that gen with the survival rocket launcher and it is weak enough to not be game breaking.  

Maybe a rod cannon or something, crafted from a bunch of pipes.  The ammo would be crafted from a paper cartridge and a rebar rail?  Medium damage, medium range, low accuracy, good armor penetration. 

Ideas?

**Comment by tyrael93** [comment]
Not to mention that NPCs with flamethrowers burning everything trying to kill squirrels are one of the reasons nobody uses dynamic NPCs.

**Comment by DeNarr** [comment]
Honestly, launchers is just a weird skill. Using a flamethrower, a grenade launcher, and a rocket launcher would all be very different skills, yet they all get lumped in here. Personally, I think it would be better if the skill were dissolved, and the weapons were spread out among SMGs, Shotguns, and Rifles.

**Comment by Coolthulhu** [comment]
I can kinda see grenade launcher using the shotgun skill, but flamethrower and rocket launcher are obviously neither shotguns, rifles nor SMGs.

**Comment by DeNarr** [comment]
I was thinking a flamethrower would be used similar to the SMGs, in that it is a sparing motion of continuous ammo.

A rocket launcher is a long distance, straight shooting projectile. Similar to a rifle.

At least, I think they are closer to those weapon types than they are to each other. I have no idea how going around setting zombies on fire with a flamethrower is going to make you better at shooting rockets.

**Comment by vache** [comment]
How do skills improve your abilities with a flamethrower, rocket launcher, or grenade launcher?  The only thing I can think of would be accuracy with the launchers, but I'm guessing as long as you're moderately accurate, it will get the job done anyway.  I don't see how high skill is supposed to improve flamethrowing though.

**Comment by Coolthulhu** [comment]
Flamethrower currently deals impact damage (which is all piercing).

Skill would matter if you wanted to reload quickly, shoot near obstacles, send grenades through windows etc.

**Comment by vache** [comment]
Back to the original question, I think in theory it would make more sense if launcher weapons were restricted to certain class-NPCs, like demo/heavy weapons specialist, and they got low handgun skill and a sidearm at the same time.  Then their AI should dictate that they would only use the launcher when facing very strong foes or when they think they have a high probability of dying.  

Ideally we would need a rules engine that we could assign to NPCs, that we could have a large set of presets for classes, then the player can modify their followers' rules.  It could also eventually support giving a specific command like "shoot this wall with your RPG".

**Comment by DavidKeaton** [comment]
I still think launchers deserve their own category. Over-generalizing has its downsides.

**Comment by Rivet-the-Zombie** [comment]
>I still think launchers deserve their own category. Over-generalizing has its downsides.

This right here. Also, flamethrowers used to use the shotgun skill, but that was changed to make the launcher skill have a bit more use.

**Comment by kevingranade** [comment]
One possibility is just saying that a lot of these weapons don't get a
second skill, they just use 'gun' for basic handling.  Rockets as a group
could stay with a dedicated skill, but then we're back to it being
impossible to train (which is realistic at least).
The catchall skill is kind of a cop-out, but I don't have a better idea at
the moment, and I don't think scattering them among the other gun skills is
a better option.

**Comment by Griffinhart** [comment]
>I was thinking a flamethrower would be used similar to the SMGs, in that it is a sparing motion of continuous ammo.

Two things: 1) [that's not how flamethrowers are used](https://www.youtube.com/watch?v=3AWPm8fEI2A), and 2) that's not how SMGs are supposed to be used. Or rather, that kind of usage is not unique to SMGs - you can just as easily continuously spray bullets around with any automatic weapon.

>A rocket launcher is a long distance, straight shooting projectile. Similar to a rifle.

So is a shotgun loaded with slugs, but CDDA differentiates between shotguns and rifles. Besides, [firing a rocket launcher](https://youtu.be/US2DQnU1lhE?t=40) is nothing like [firing a rifle](https://www.youtube.com/watch?v=8rLfYLM48Ms).

The rifle category is also too broad in a similar fashion to the launcher category: a modern light machinegun isn't really operated in the same way to a +120 year-old bolt-action rifle.

I'd argue that it's probably better to not have NPCs with launchers as their *primary* combat skill, seeing as that's a fairly impractical weaponset to rely on as your primary.

**Comment by Zireael07** [comment]
Agreed about the NPCs.

**Comment by ejseto** [comment]
>it's probably better to not have NPCs with launchers as their primary combat skill

Personally I think it adds flavor, seeing some psycho/fool burn everything including himself, and dying a spectacular death while taking hordes of zombies with him.

**Comment by Rivet-the-Zombie** [comment]
Not only that, we have a whole NPC archetype that's called 'arsonist' so it makes sense that they'd be playing around with fire.

**Comment by DavidKeaton** [comment]
I love seeing it!

**Comment by tyrael93** [comment]
Whole araonists exist, the fact they VA attack every single monster (squirrels and chipmunks included) creating a trail of fire and destroying cities is pretty dumb. It gets manageable if you recruit them and tell them not to try to kill anything that moves, but you can't most of the time.
I don't remember the arsonist in the commune bring equipped with a flamethrower, too. That's a sane decision because by the time you reached the community the place would be ashes.
You wouldn't give a flamethrower to a retard, which is what NPCs are when they see a target .

**Comment by Rivet-the-Zombie** [comment]
>You wouldn't give a flamethrower to a retard, which is what NPCs are when they see a target .

That's some unduly harsh wording, and moreover it misses the point entirely.

There's nobody out there in the world of DDA that's handing out guns to people based on whether they're fit to carry them; those NPCs are assumed to have scavenged/crafted their stuff just like the player. In this way it makes sense for firebug NPCs to have flamethrowers, as that's exactly the sort of weapon a person like that would gravitate to.

**Comment by DavidKeaton** [comment]
I won't pile up over the wording in that comment, but next time maybe better words would be fair. :-)

I'd totally be a firebug, and I would burn it all. Who's left to say I can't? :-P

**Comment by Rivet-the-Zombie** [comment]
*Some cartoon foxes just want to watch the world burn.*

**Comment by DavidKeaton** [comment]
Funny, a ring with your name on it just ended up in my mailbox.

**Comment by mugling** [comment]
NPC's with flamethrowers was dealt with by #16245
