### ISSUE TITLE
Butchered skeletons produce edible meat, stomach.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#12595]
Build 3272.

**Comment by Coolthulhu** [comment]
Looks like the skeleton lacks the "POISON" tag. I recall it dropping only bones last time and skeleton tags didn't change for a while.

**Comment by Coolthulhu** [comment]
OK, I see it now:
By default, every `mtype` starts with `hflesh` in materials, because the default corpse is the human one. This means that skeletons are made of (human) flesh and bone, while robots are made of (human) flesh and steel. Also explains #12596

Tanks drones are now Strogg.

**Comment by Rivet-the-Zombie** [comment]
*How can you choose cold metal over the splendor of flesh?*

**Comment by Coolthulhu** [comment]
Why not both?

Also, this wasn't a problem before because each monster had only one material type. Now it pushes back the new material rather than overwriting it. Until we can have multi-mat creatures (not possible at the moment), it should probably just overwrite.
