### ISSUE TITLE
[Holding water] Fancy mineral water

### ISSUE THREAD

**Issue by wmafie** [CleverRaven/Cataclysm-DDA#12607]
"Fancy mineral  water, so fancy it makes you feel fancy just holding it."

So after checking a vending machine and holding a button down to buy everything quickly, I discovered i have items in liquid form in my inventory, without the container. Surely this is a bug, yes?
##

**Comment by Rivet-the-Zombie** [comment]
Just tested; cannot replicate. Anyone else experiencing this?

**Comment by Coolthulhu** [comment]
Didn't try testing, but the only way I can imagine this happening would be if someone hit a vending machine with a hit strong enough to wreck glass but not the machine itself.

**Comment by tvm1** [comment]
Can't replicate that either.

**Comment by wmafie** [comment]
Replicated it. Coolthulhu is correct. Punched the machine once without breaking it. Was able to buy "mineral water".

**Comment by Rivet-the-Zombie** [comment]
I like how it proceeds to dispense the water directly into your hands.

An amusing bug, but still a bug.

**Comment by wmafie** [comment]
Version 0.D confirmed.D for dispenser. Main features: Water Dispenser.

**Comment by macrosblackd** [comment]
This is one of those where we fix the bug, but add this particular
behavior as an easter egg :)

**Comment by DavidKeaton** [comment]
or leave it in as a part of *the future*!

**Comment by kevingranade** [comment]
The water is THAT fancy.
