### ISSUE TITLE
Grammar: "The tough zombie climbs to it's feet!"

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#12608]
Version 0.C-3666-g3faa19b

`The tough zombie climbs to it's feet!` -> `the tough zombie climbs to it is feet!`

"it's" is a contraction of "it is". "its" is possessive.

http://dictionary.reference.com/browse/it's
http://dictionary.reference.com/browse/its

**Comment by Rivet-the-Zombie** [comment]
Hooray! It's one of my pet peeves! 

I must've missed this one.

**Comment by DavidKeaton** [comment]
oh no! it climbed on it is feet! :-O *gasp*
