### ISSUE TITLE
Water tanks on vehicles and general vehicle construction menu problem

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#12601]
*(Based on 0.C-3666-g3faa19b)*

So we used to have only clean water tanks on vehicles, which was an arbitrary limitation, but at least the whole thing around it worked.

Right now it seems we have the little, small and 'normal' (which uses 30 gallon drum specifically) variations for *dirty* water tanks, and only single option for clean water tank (the 30 gallon drum). Now the water faucet seems to work only with *clean* water tank, so the *dirty* water tanks are not much of an improvement over just storing the damn container in the vehicle (instead of grabbing the container you now have to have a rubber hose to siphon the dirty water back). Also the common metal tank seems to be inexplicably not usable at all for holding *any* kind of water.

A temporary solution would be to add the *dirty* and *clean* versions for all possible water tanks (metal tank = 'normal', X gallon drum = 'large') and *then also* have two version of water faucets.

Unless I'm missing some good reason where the current state makes sense...

--
And the above temporary solution brings us to another general problem with the vehicle menu: we have too many parts in a flat list that are variations of a single logical/physical item. A metal tank is a metal tank and doesn't care/limits what can be in it (even if the thing you pour in is gonna eat it: it should then get damaged progressively, but that's another matter).

Proposed sane solution: make part choosing a multi-level process. We already have a 'sub-menu' for choosing frame appearance, we should build on that mechanic.

Two examples:

 - In top-level menu you see: little metal tank, small metal tank, metal tank, 30 gallon drum
 - You selected small metal tank
 - Now you select fuel type for it: water, clean water, gasoline, diesel etc... You have selected clean water
 - This installs a 'small clean water tank'
 - You now select a vehicle faucet from the top-level menu
 - And it asks you for fuel type as above...

In case of fluid tanks this still keeps the mechanic where you don't need to install any piping, e.g. any X facuet will tap into all X tanks.

 - In the top level menu you see: door
 - You select it, and are presented with types: sliding, hatch, normal (outer?)...

Most of the items in the list can be logically grouped together, and the multi-level menu approach leaves room for more fancy future additions (like finally being able to select a specific engine of type X out of those lying around).

*Thank you for reading*

**Comment by DavidKeaton** [comment]
or tires! I'm SO for a multi level approach.

**Comment by drbig** [comment]
Also if I'm not mistaken even the Luxury RV doesn't include any water tank now.
Save of proof: https://dl.dropboxusercontent.com/u/897725/cdda/2015-06-09_220100 (it's a zip file).

*Co jak co* but a Luxury RV without water is not even a *simple* RV by my book.

**Comment by BevapDin** [comment]
> Also if I'm not mistaken even the Luxury RV doesn't include any water tank now.

As of 3faa19bd4aa0ab15dd2561f907799864ecaf4c88 it still has a water tank. Just tested in game and looked it up in data/json/vehicles/vehicles.json.

----

What about making tanks completely generic: you install a small/large/gigantic tank (no fuel mentioned). It will contain whatever you fill in it. Problems is see:
- fuel indication (X / Y, what would be the maximum fuel amount: including all unused tanks?)
- UI: make sure you refill the right tank.

**Comment by Rivet-the-Zombie** [comment]
Tanks that accept/faucets that dispense any liquid would be great, and it would solve this issue entirely.

**Comment by drbig** [comment]
*Disregarding the save.*

I actually like the 'low-level mechanic' of having designated tanks - it's simple code-wise and user-wise on all levels.

Other-way-around I could see it (specifically for *fluid tanks* and *facuet*) is: any tank accepts any input while empty, with any input it limits itself to that input. A faucet then presents a menu of what to pour. On it's own it makes *even more sense*, so yes I'd say that's the sanest solution here.

Still the multi-level vehicle menu construction UI stands on it's own.

**Comment by Rivet-the-Zombie** [comment]
>any tank accepts any input while empty, with any input it limits itself to that input. A faucet then presents a menu of what to pour. When back to empty it reverts to accepting anything.

This is a great idea.

**Comment by drbig** [comment]
It would also make siphoning not necessary as long as there's at least one faucet. I think it's ok.

We'd need to rename 'water faucet' to something else though.

**Comment by DavidKeaton** [comment]
good ol' water "spickit" mmhmmm *spits in spittoon*

**Comment by drbig** [comment]
'Faucet'? :)

**Comment by DavidKeaton** [comment]
I was referring to the glorious southern US dialect.

**Comment by drbig** [comment]
Or you can call it 'kran' and be done with it (attribute it to Polish plumber influence in the future of the USA).

**Comment by DavidKeaton** [comment]
Here in God's coun'ry we speak American.

**Comment by Soyweiser** [comment]
They speak American in Israel?

**Comment by illi-kun** [comment]
Thanks to @mugling, now we have tanks for any liquids.

AFAIK, faucets aren't yet associated to exact tanks but the general idea of generic tanks is implemented.
