### ISSUE TITLE
Third option to show both (Mph/Kph) and (Fahrenheit/Celsius) at the same time

### ISSUE THREAD

**Issue by TheFerc8** [CleverRaven/Cataclysm-DDA#1260]
Would be great if there was a third option to show vehicle speed in both miles and kilometers per hour, as most car speedometers show both at the same time. Also, same would be nice for temperature. I know both systems, but metric a bit more, and I think it would be a useful learning experience :) There might be some space issues with displaying it though, but I definitely would like to see it implemented.

P.S. Wanted to add a label of enhancement, but didn't see how :/

**Comment by illi-kun** [comment]
Do we really need this feature implemented? Will anyone use this on regular basis?

**Comment by kevingranade** [comment]
I'm not against having it, and presumably at least the person opening the
issue would use it.
However, I'm not interested enough to do the work, which might be
considerable due to requiring ui changes.

**Comment by mugling** [comment]
Would require extensive code changes for minority appeal
