### ISSUE TITLE
Bad JSON mapgen on loading game

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#12609]
Version 0.C-3666-g3faa19b

```
DEBUG: Bad JSON mapgen, discarding:
  line 35:25: Invalid terrain
                    ",": "t_pavement_y",
					"-": "t_pavement",
					"q":
					    ^
						 "t_wall_h",
					"x": "t_wall_v",
					"+": "t_door_glass_c",
  Press spacebar...
```

**Comment by Coolthulhu** [comment]
Must be some mod, I'm guessing dino.

**Comment by BevapDin** [comment]
No file in the data folder has contains "t_wall_h". @Griffinhart what mods are you using?

**Comment by Griffinhart** [comment]
```
[
	"Animatronics",
	"boats",
	"RL_Classes",
	"DinoMod",
	"no_religious_Texts",
	"ew_pack",
	"necromancy",
	"blazemod"
]
```

**Comment by BevapDin** [comment]
How (if at all) did you update your game?

Sometimes files (especially JSON) get removed or renamed, if you simple extract the new game version over an existing installation, the old JSON file will remain. `t_wall_h` was recently rename to `t_wall` and all files containing it have been updated accordingly, but if there still is an old file in your installation, it would contain the old ids.

Try updating this way: extract the game into a new folder and copy/move the save directory there. This should give you a clean installation.

**Comment by Griffinhart** [comment]
>How (if at all) did you update your game?

```
git pull
make clean
make
```

**Comment by DavidKeaton** [comment]
does this project have a proper `make distclean`?

**Comment by mugling** [comment]
Closed due to age and lack of reports in `master` (with or without mods)
