### ISSUE TITLE
Strength Bonus not Adding to Damage or HP

### ISSUE THREAD

**Issue by DeNarr** [CleverRaven/Cataclysm-DDA#12618]
Currently, any sort of "bonus" to strength does not actually raise the melee damage you do, or the about of HP you have. This includes all bionics, as well as taking drugs. (Some might think that HP shouldn't be effected by bonuses, bit I'd argue that someone hopped up on drugs or bursting with adrenaline should be harder to take down . . . temporarily).

**Comment by tvm1** [comment]
You are right.

I mentioned this in  #12473.

This will require some work and time to fix.

**Comment by tvm1** [comment]
This issue should be also closed because  #12473 happened.

**Comment by Coolthulhu** [comment]
Drugs not affecting hp is not a bug.
They already make the player more resistant by removing some of the pain. This makes more sense than a temporary hp buff.

**Comment by DeNarr** [comment]
I was thinking of Crack heads who don't die from what should be a lethal shot. Granted, the fact that they would die when they come down means it wouldn't be a great strategy for the game anyways, just seems like something that should happen though.

**Comment by Rivet-the-Zombie** [comment]
>I was thinking of Crack heads who don't die from what should be a lethal shot.

This is an urban legend created by American police.

**Comment by Coolthulhu** [comment]
It's more about them not being incapacitated than them not dying. Death from a gunshot wound can take a while, it's just that sober people generally spend that while lying down/losing consciousness.

**Comment by DavidKeaton** [comment]
shock leads to incapacitation. some drugs (PCP, for one) give the user lessened pain response to injury. mix that with adrenaline and you have an "invincibility" demeanor from the person receiving the gunshot. it doesn't keep them from dying, just from lack of entering shock and feeling pain.
