### ISSUE TITLE
You download 16997968 new photos into internal memory.

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#12611]
Version 0.C-3666-g3faa19b

Looted an electronic store and came out with 12 SD Memory Cards.

Downloaded the data off of one using the E-Ink Tablet PC, and apparently downloaded nearly 17 million photos.

~~Not sure if this is a bug, but it does seem vaguely excessive.~~ Pretty sure this is a bug; see edits below the image.

![](http://i.imgur.com/h9tKCb8.png)

e: The third SD Memory Card downloaded the exact same number of photos (16997968), but the E-Ink Tablet PC only increased photos by 51 (from 137 to 188).

e: Fourth card downloaded 16998088 songs, but the tablet PC's soung counter is at 49 (I don't remember what it was at before the download).

e: Sixth card: 16997968 photos, actual count on PC is 215 (up 27 from 188).

e: 11th card: 16997968 photos *and* 16998088 songs. Actual counts on PC are 223 (up from 215) and 59 (up from 49), respectively.

e: 12th card: same as 11th; actual counts are 233 and 67.

**Comment by DavidKeaton** [comment]
def a bug lol. it worked at one point, but a change in the iuse system broke it.

**Comment by kevingranade** [comment]
16 million, that's in the ballpark of int underflow IIRC.  Something
returning -1 for failure and getting turned into great success?

**Comment by DavidKeaton** [comment]
I was thinking the same thing, however if it's an int, it'd be closer to 2.4 x 10^9.

**Comment by Griffinhart** [comment]
I don't know how the print code is laid out, but it might also be that it's reading memory it shouldn't be.

**Comment by DavidKeaton** [comment]
it's fairly static as far as the numbers go, on each run. if it were, you'd be getting a stack mismatch (borked `RET`) or you'd get random junk data.

**Comment by narc0tiq** [comment]
As far as int underflow, my memory of int sizes suggests we would have to
be looking at numbers near 255, 65,535, 4,294,xxx,xxx, and somewhere in the
too many digits to comfortably keep track of (calculator suggests 20 digits
for unsigned 64-bit integers). 16 million is well short of the 32-bit
UINT_MAX and well over the 16-bit one.

**Comment by DavidKeaton** [comment]
in the case of the standard `int` it'd be 2.6*10^9, due to signage. always about half what a var type can store unless unsigned. :-)
