### ISSUE TITLE
Shift-tab (reverse tab) in player info screen is not working

### ISSUE THREAD

**Issue by dodzy** [CleverRaven/Cataclysm-DDA#12617]
also while experimenting, I found out that shift-tab in inventory screen works like enter. Probably not intended but no harm done I guess.
##

**Comment by DavidKeaton** [comment]
there are general input/ui inconsistencies that need worked out for sure. I plan on doing this in my UI update, but it'll be a bit.

**Comment by dodzy** [comment]
ok sounds good.
I looked at the code and I might do a pull request with the needed changes soon though.
We'll see.

**Comment by DavidKeaton** [comment]
if you want to, that's fine by me. at least it's a fix until I get my stuff going.
