### ISSUE TITLE
.44 Magnun ammunition is described as a handgun

### ISSUE THREAD

**Issue by 2birdie** [CleverRaven/Cataclysm-DDA#12628]
"Described (in in 1971) by Dirty Harry as "the most powerful handgun in the world," the .44 Magnum gained widespread popularity due to it's depictions in media. In reality, it's intense recoil makes it unsuitable in most cases."

**Comment by Rivet-the-Zombie** [comment]
I think it's an issue of somebody clumsily wording the description to reflect that a lot of people believe that the .44 magnum round is the most powerful handgun *cartridge* in the world. Protip: It's not.

So yeah, this phrasing could definitely be re-worded.

**Comment by 2birdie** [comment]
But was it the most powerful handgun cartridge in the world in 1971? O:

**Comment by KrazyTheFox** [comment]
The .454 Casull cartridge was designed in the late 50s and has significantly higher power. I don't recall numbers off the top of my head.

**Comment by Griffinhart** [comment]
The .454 Casull has approximately twice the energy of the .44 Magnum, but at the time of the film, .454 Casull was a wildcat cartridge. A more accurate line would've been "the most powerful handgun [cartridge] in full production in the world", but Hollywood's never been a stickler for accuracy.

**Comment by ejseto** [comment]
The description isn't (necessarily) wrong. It's not saying it is or was the most powerful handgun (or cartridge, since it's unclear which Dirty Harry was talking about, if not both) in the world, it's saying Dirty Harry *described* it as such. I've never actually watched the movie, but since the line is so famous, I assume he actually said it.

**Comment by kevingranade** [comment]
That's a good point, if the quote is accurate to the movie and it still
bothers people, let's ditch the quote rather than rephrasing it.  I'm fine
either way.
