### ISSUE TITLE
[CR] Radiation awareness

### ISSUE THREAD

**Issue by tvm1** [CleverRaven/Cataclysm-DDA#12620]
We currently have quite few hi-tech CBMs.

If player enters the area with radiation he can collect quite few Sieverts without even knowing (and possibly die afterwards). 

My proposal:
If the PC is equipped with Dosimeter CBM, give him "audible"  feedback when entering irradiated area. Perhaps a beep every five turns or something like that ?

Humans are currently able to manufacture watches that alert you, when the radiation is present. They should be able to handle this in 2040 as well.

**Comment by drbig** [comment]
I agree for an alarm beep when entering area where the radiation is *important*, and a message. Leave the rest to the player.

**Comment by kevingranade** [comment]
Sounds reasonable to me, there's a geiger counter that more or less gives this effect, so a miniturized and internal one is reasonable.

**Comment by tvm1** [comment]
Should we react only to external radiation ? I'd say yes.

Because this thing might become obnoxious quite fast with internal/inventory radiation leaks.
