### ISSUE TITLE
Atomic light gives no light

### ISSUE THREAD

**Issue by tvm1** [CleverRaven/Cataclysm-DDA#12629]
As reported by `CptCodpiece` on IRC today, atomic light doesn't gives enough light to read at all, after the overhaul of illumination system.

**Comment by kevingranade** [comment]
It should if you're holding it, but not if it's on the ground.

**Comment by tvm1** [comment]
I've just pulled upstream and compiled the very latest. Having and wielding dozens of atomic lights, game gives `You can't see to read` and the crafting menu shows `very dark`.

**Comment by tvm1** [comment]
This is probably a issue with `LIGHT_5` item flag. Atomic nightlight is only item that uses that. I couldn't find the relevant piece of code that handles that though.

**Comment by kevingranade** [comment]
It's icky, in I think item_factory.cpp, it checks for "LIGHT_*" and assigns
the numeric part to item::luminance.

**Comment by tvm1** [comment]
I suspected something like that. Anyways, luminance 5 is not enough. If set to 6, it produces the usual (wanted) result "can't see finer details". Not sure where the problem is.

**Comment by tvm1** [comment]
Well, can't we just bump the `LIGHT_` flags to 6 to make the light sources behave ?
