### ISSUE TITLE
How to "nicely" break save compatibility?

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#12634]
I may need to break saves in 3D mode by introducing a large mapgen alteration: aligning stairs.

Currently stairs are aligned only on overmap. This is fine for finding a new position for the player and NPCs, but it also wrecks monster 3D AI, results in weird shift of sound sources on z-level travel and makes it way harder to properly implement stair destruction.
Plus, it makes adding new features more tiresome, as stairs need to be special-handled.

Old saves could still be played in 2D mode, but in 3D mode the unaligned stairs would result in unescapable basements. Well, not unescapable - you could still make a stack of furniture and use that to climb. But it would look really weird to have unusable stairs and a hole in the ceiling.

Should I just ignore the old saves with 3D mode assuming players who turned the option on knew the risks or is there some clever way to handle this? Maybe bump up save number and display a warning/prompt to disable 3D mode when an old save is loaded?

**Comment by Rivet-the-Zombie** [comment]
>Maybe bump up save number and display a warning/prompt to disable 3D mode when an old save is loaded?

If you want to be really nice about it, this would probably be the best way to go.

Really though, if it's getting us closer to Z levels I wouldn't sweat breaking experimental 3D saves. It's experimental and that's the risk folks are taking.

**Comment by tvm1** [comment]
> Really though, if it's getting us closer to Z levels I wouldn't sweat breaking experimental 3D saves. It's experimental and that's the risk folks are taking.

 I agree, it's experimental version, with experimental feature. People will probably want to move saves between `0.C` and future stable version though. It would be good to handle this nicely. Bumping up save version & alerting player to disable 3D sounds reasonable.

**Comment by vache** [comment]
How are you going to handle the random way labs generate stairs right now?  Probably the easiest way is to force up/down sections to have a handful of set layouts right now to avoid all the problems that come with trying to randomly place stairs.

**Comment by Coolthulhu** [comment]
At first just random placement with verification that the stairs can be placed there on the other end.

**Comment by kevingranade** [comment]
The NICEST way to handle it is to update mapgen to generate aligned stairs,
do a stable release, blabla, and remove support for non-aligned stairs at
the next stable release or so.  I understand that timeline probably isn't
reasonable, so I'm just mentioning it.

Next best is patching submap load to generate matching stairs during the
transition, this can be combined with submap versioning so you can avoid
endlessly re-creating stairs, and endlessly checking for stairs even though
it has been checked already.
As for how that works, it can do any or all of: check x/y of up/down stair
at z of down/up stair for open space, check average of up/down stair x/y
locations at both z levels, or check for a x/y in the navigable range of
both stairs that are both clear.
In case of no match, we probably just want to generate a matching stair,
nonsensical stair placement is better than a disconnected map.
It might be better to bias this such that only up stairs or down stairs are
moved, possibly based on the submap type.  For example we probably don't
want to move the stairs in the shelter, but instead move the stairs in the
shelter basement.  I can't think of anywhere we'd want to move the down
stairs, but there might be one.
Another nice to have is removing the now-orphaned stairs where possible.

**Comment by DavidKeaton** [comment]
Since you are doing p much all the work for 3D, you should do what you feel is best, but being *experimental* is exactly that. The option mentions it can be buggy, so just add to it and if it breaks save compat, so be it! (I'll lose a character or 5, but hey... that's the price I pay for turning on alpha or beta options... ;-)

**Comment by kevingranade** [comment]
No davek, if it completely broke old saves, it wouldn't get turned on :/
Coolthulu is doing the right thing, as usual, thanks :)

**Comment by DavidKeaton** [comment]
fair enough. :-)
