### ISSUE TITLE
Too many bartenders!

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#12633]
Build 3287 Windows

I've got five sets of bartenders and mercenaries in the outpost bar right now, all with different names and equipment.

Are we spawning a bartender each time we gain new mercenaries, and if so why?
##

**Comment by tyrael93** [comment]
I guess people really, REALLY need a drink.

**Comment by DavidKeaton** [comment]
I know I would.

**Comment by Leland** [comment]
Closing this due to lack of corroborating reports over the years and no savefile – this will be difficult to reproduce. If anyone encounters this again, feel free to either ping me here to reopen, or just create a new issue.
