### ISSUE TITLE
can't open linux SDL version on ubuntu14.04

### ISSUE THREAD

**Issue by jiagoumengxiang** [CleverRaven/Cataclysm-DDA#12638]
./cataclysm-tiles: error while loading shared libraries: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory

where i can get the lib?

**Comment by BevapDin** [comment]
> where i can get the lib?

The same place you get all your other packages from. If you don't know the package name: http://lmgtfy.com/?q=Ubuntu+file+%22libSDL2_mixer-2.0.so.0%22

Or you could search for Ubunutu in the forum http://smf.cataclysmdda.com/index.php?board=4.0 - there are several threads about it, e.g. http://smf.cataclysmdda.com/index.php?topic=9560 or http://smf.cataclysmdda.com/index.php?topic=9560 - the search can be used without login.

Be aware that you need the 32 bit version of the library, even if you have a 64 bit system.

**Comment by Midaychi** [comment]
*unless you compile the 64bit version yourself, then you need the 64bit versions

**Comment by slyscorpion** [comment]
I get the same error message on Mint 17.1 when using the latest stable tiles release. I have a 64-bit system and if I want to install the 32-bit version (libsdl2-mixer-2.0-0:i386)
 it would entail removing the 64-bit version I have already in place and I don't feel comfortable with doing that.

**Comment by Midaychi** [comment]
Easiest way to get around running the 32bit version on 64bit linux is to follow to compiling guide and compile it yourself with NATIVE=linux64

Although the wiki is down for some reason atm.

**Comment by slyscorpion** [comment]
The wiki works for me and it should have that instruction in there for people like me :) 

Trying out your suggestion now, thanks!

**Comment by Midaychi** [comment]
You compile the program just fine but get a segfault?

**Comment by slyscorpion** [comment]
@Midaychi here's the pastebin of my terminal output when compiling the game via "make TILES=1 NATIVE=linux64"

http://pastebin.com/5S3m0b3j

**Comment by DavidKeaton** [comment]
Your distro does not support multilib? There should be no reason you *can't* have both 32 & 64 bit of the same libraries.

**Comment by Midaychi** [comment]
No the problem is that the sdl2 packages inherently cancel eachother when you try to install them on debian-based environments. Try it, and apt will demand you uninstall the other version first in the process.

**Comment by slyscorpion** [comment]
@DavidKeaton apparently sdl2 demands you choose to use the 32-bit OR 64-bit version. Can't have both sdl2 packages, I guess. 

In any case I've solved the problem by compiling the game with NATIVE=linux64 and it works now although it requires elevation in Mint 17.1 for some reason O.o

**Comment by DavidKeaton** [comment]
well I doubt it's the package itself demanding it, probably the package manager.

**Comment by Midaychi** [comment]
not to bash mint, but in my experience its lack of certain essential debian/ubuntu repositories + incompatibility with them and a number of poor choices renders it a poor compiling platform. Probably some weird compatibility issue with the toolchain.

**Comment by DavidKeaton** [comment]
I'm not as familiar with debian as a whole. I use Arch and Gentoo. :-P

**Comment by narc0tiq** [comment]
@DavidKeaton 
> well I doubt it's the package itself demanding it

Funny, I was thinking exactly the opposite -- you can have both 32- and 64-bit versions of some packages installed, but the packages have to have been built such that they install to arch-specific locations (e.g. `/usr/lib64` or `/usr/libx32` instead of `/usr/lib`). The sdl2 packages haven't, so they're mutually-exclusive.

The package manager shouldn't particularly care either way.

**Comment by DavidKeaton** [comment]
isn't the install location up to the package manager? albeit the makefile for the project could be at fault, lending to your notion.

**Comment by narc0tiq** [comment]
The install location is up to the package -- the package manager just has to allow/support it.

**Comment by DavidKeaton** [comment]
ah fair enough. I'm used to build systems where the install location is given via manifest.

**Comment by narc0tiq** [comment]
Uh, the manifest would be part of the package.

**Comment by DavidKeaton** [comment]
okay then i was misconstruing package, my bad b. :-P

**Comment by mugling** [comment]
This appears to be an issue with package management which is beyond the project scope and also likely resolved given the age of the issue. @jiagoumengxiang please feel free to re-open if you are continuing to have problems
