### ISSUE TITLE
autoexec.lua doesn't populate mods

### ISSUE THREAD

**Issue by DeNarr** [CleverRaven/Cataclysm-DDA#12641]
In trying to create my own mod using lua, I noticed that the callback functions never seemed to work. In digging into it, it looks like it is because the "mods" table in autoexec.lua never gets populated. Below, you can see where I added a couple game.add_msg lines for troubleshooting. The first line would get called, but the second wouldn't. As further troubleshooting, I was able to manually call the function from my mod using the lua debug, so I know the mod itself was loaded.

-- table containing our mods
mods = { }

function mod_callback(callback_name)
    game.add_msg("About to call mods")
    for modname, mod_instance in pairs(mods) do
        game.add_msg("Did this get called?")
        if type(mod_instance[callback_name]) == "function" then
            mod_instance[callback_name]()
        end
    end
end

**Comment by BevapDin** [comment]
You're mod is supposed to add itself to the mods table (a mod is not supposed to change files outside its own directory tree). See doc/sample_mods/elf_mod/main.lua as an example.

Put this in "data/mods/MyAwesomeLuaMod/main.lua" (or "preload.lua")
```Lua
local MOD = {}

mods["MyAwesomeLuaMod"] = MOD

function MyAwesomeLuaMod.on_day_passed()
    -- ...
end
```

**Comment by DeNarr** [comment]
Ah, thank you! I have been scouring the wiki and forums for example mods that use lua, but the only ones I could find were the fast/slow zombies, which don't do callbacks or add themselves to the MOD table. Quick note though, in your example it should be MOD.on_day_passed().
