### ISSUE TITLE
Lit charcoal kiln will be ready in 1 year

### ISSUE THREAD

**Issue by mikegogulski** [CleverRaven/Cataclysm-DDA#12648]
I lived for several year, filled and lit a kiln, died, started a new character and found my way back to my base. The charcoal kiln I left burning now says "will be ready in 1 year" and can't be disassembled.

**Comment by BevapDin** [comment]
Duplicate of #11700, tanning hides use the same mechanics that is used by the kiln.

**Comment by mikegogulski** [comment]
Thanks.
