### ISSUE TITLE
Bloated Z gas explosions reach past windows.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12652]
This situation: 
@
""--
Z

Caused the bloated Z to explode, and the gas reached me outside, while not blowing out the windows. (I was outside, he was inside, the windows not broken before, nor after).

Perhaps a bloated Z explosion should shatter glass just like boomers do.

**Comment by John-Candlebury** [comment]
I dont even know why it exploded, I think they were supposed to explode only when adjacent.

**Comment by Soyweiser** [comment]
Ow? they always explode when 2 squares off. Found that pretty annoying tbh. You are melleeing some Z's and the second row bloated one explodes and makes stuff worse.

**Comment by Rivet-the-Zombie** [comment]
>You are melleeing some Z's and the second row bloated one explodes and makes stuff worse.

I think that's the whole reason why they can explode two squares away.

**Comment by Coolthulhu** [comment]
Their job is making stuff worse.

Making them bash windows wouldn't help a lot - they would still smoke through glass walls, windshields (too though to get bashed down in one weak hit) and regular walls (if something on the other side made them explode).

**Comment by Soyweiser** [comment]
Well, seems I never gotten into close combat range with any of them. They always explode before that.

I just put on a gas mask and carry on.

**Comment by kevingranade** [comment]
I thought this was just a consistency issue, in which case it makes sense.
The good way to fix it is probably to route everything through
game::explosion() so things like this are consistent.

**Comment by Soyweiser** [comment]
Yeah, indeed, it is inconsistent.

**Comment by railmonkey** [comment]
Hm... I actually don't see much of a problem here, but then, I've been stuck on a Chromebook. Unless a door or window has been actively sealed against outside atmosphere, contaminants -will- get in. By which I mean towels, plastic, caulking, etc. Maybe address that with a new construction option? But yeah, gas getting through closed windows is perfectly in line with realism.

**Comment by Soyweiser** [comment]
It is a lot of gas pretty quickly. Not that realistic imho. (I do agree on normal windows etc not being totally airtight) But this is a bit extreme.

**Comment by railmonkey** [comment]
Yeah, that's fair. Hm... How does the gas expansion function work? Instant, yeah, but would it be possible to add a check for impediment, or lack thereof? Open window/door would let it through as normal, closed could start with maybe a square or two of light gas and spread from there, and a sealed window/door could start with a square of haze.

**Comment by Coolthulhu** [comment]
It would be possible to check for clear way, but then even a simple window would block it easily.

What wouldn't be possible yet is having expanding gas wreck windows on its way (and only on its way). Later on explosions will work like this, but they don't do it yet.

A compromise between those two would be bashing all stuff in radius 1 and expanding gas in radius 2 with a check for clear path.

**Comment by Soyweiser** [comment]
The 1 2 would work. No idea how easy it is to implement right now.

**Comment by railmonkey** [comment]
Well, blocking it is the idea, but is there no way at all to introduce degrees of blockage, or is it all or nothing? Maybe make it a variation of an armor check? Or wait... That's essentially what the 1 2 solution would be doing, right?

**Comment by kevingranade** [comment]
Actually I think explosion has the features we need, you can have a very
small explosion that will break nearby fragile terrain like windows that is
followed by a burst of gas that respects the path being clear.

**Comment by DavidKeaton** [comment]
a rapid expansion of gas near a window with adequate force (the pressure confining it into the zed's body for instance) should be enough to break glass.

**Comment by Soyweiser** [comment]
I think a boomer already breaks glass. But not sure. It breaks some stuff.

slightly related. A huge boomer should explode 5x5 and not just 3x3 like a small boomer.

**Comment by Rivet-the-Zombie** [comment]
>A huge boomer should explode 5x5 and not just 3x3 like a small boomer.

I've thought the same thing myself.

**Comment by DavidKeaton** [comment]
honestly haven't seen a hb up close, haven't had the time. lol.

**Comment by mugling** [comment]
Fixed by the field emit code PR
