### ISSUE TITLE
Core Devs: label for PRs in the merge pipeline

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#12659]
A simple rule: if you're working on merging a given PR add a specific label to it.

The point is anyone (including my ircbot) can then easily query github to list PRs in the merge pipeline.

A label is easier to search by than by assignee, it's self-explanatory and explicit, and you can remove it if the PR needs more work (or whatever if it's no longer in the merge pipeline), but still be the assignee if you e.g. want to work with the author on making it mergable.

This should also help you to filter out open PRs that are *not* in the pipeline.

While the total effectiveness of this scheme depends on you actually adding the label, it's not that anything's going to break if you don't add it, so I don't see any downsides. 

And as to the label itself: anything you all can agree on. 'for-merge' seems like a reasonable candidate.

*(the point is still for anyone to easily filter out PRs that are in the merge pipeline; I'd be happy with any mechanism that can do that; labels just seem the easiest way to me)*

**Comment by Rivet-the-Zombie** [comment]
We've got a system to assign PRs to each other/ourselves, but unfortunately we tend to forget to use it a lot of the time.

**Comment by drbig** [comment]
@Rivet-the-Zombie is it easy to filter by in github search queries?

**Comment by Rivet-the-Zombie** [comment]
There's an option to sort by assignee in the main PR list here on Github, if that's what you mean.

**Comment by drbig** [comment]
@Rivet-the-Zombie A label would still be easier then, plus my argument for self-explanation and explicitness of a label like 'for-merge' ('pipeline', 'to-be-in', 'XXX'... :D )

**Comment by narc0tiq** [comment]
<https://help.github.com/articles/searching-issues/#search-by-missing-metadata-on-an-issue-or-pull-request>

> **important no:assignee language:java type:issue**
>    Matches issues not associated with an assignee, containing the word "important," and in Java repositories.

So there's your filter: "no:assignee"

**Comment by narc0tiq** [comment]
And I just found the inverse query: "assignee:*" will list everything that has an assignee.

**Comment by drbig** [comment]
@narc0tiq aye, that's another way to approach it. Thank you :)

So is 'assignee set = for merge' a better overall approach?

**Comment by narc0tiq** [comment]
It does seem to be followed more often than not.

**Comment by Rivet-the-Zombie** [comment]
Please keep in mind that just because a PR is assigned, that doesn't mean it's necessarily getting merged right now; quite often a PR will be assigned and de-assigned multiple times throughout its testing process as various bugs are discovered and fixed.

**Comment by DavidKeaton** [comment]
honestly the assign/unassign thing is odd to me. i personally think (again, my opinion), think that for non wip PR, assigning should be static, as you work with the PR author to get it in.

**Comment by drbig** [comment]
> Please keep in mind that just because a PR is assigned, that doesn't mean it's necessarily getting merged right now; quite often a PR will be assigned and unassigned multiple times throughout its testing process as various bugs are discovered and fixed.

I did address this aspect in my initial statement... Which is why a recommend a label for explicitly **'towards the merge' goal**.

**Comment by drbig** [comment]
It is all about semantics now, so: assignee = "i'm currently taking care if this"; label = "it's currently in the process of merging". The two are not equivalent. And yeah the point is that'd you'd start your merge work with adding the label, and if all is smooth end up with a merge; if not remove the label.

**Comment by Coolthulhu** [comment]
Assigning/deassigning allows quickly discerning whether someone is working on the code right now. This helps to prevent the situations when two people try to merge conflicting changes.

**Comment by drbig** [comment]
@Coolthulhu indeed! the question/difference is if 'working on (because assigned)' = 'for merge'.

Two scenario examples:

1) You see a PR, like to merge it; assign yourself and set the label
2) You see some problems, so you comment on the code
3) The author says he needs some time to work it out; you unset the label but leave yourself assigned
4) Three days later the author did some commits, says it should be ok; you add the label again
5) It works, you merge it

1) You see a commit by other core dev; you assign yourself, you didn't set the label
2) It works, you've merged it

**Comment by DavidKeaton** [comment]
okay then this. I'm totes okay with drbig's answer.

**Comment by tvm1** [comment]
> honestly the assign/unassign thing is odd to me. i personally think (again, my opinion), think that for non wip PR, assigning should be static, as you work with the PR author to get it in.

I agree. It takes time and effort to get into the specifics of the given PR.

Then again, non-WIP stuff that works, or is being actively fixed is getting merged very quickly from what I've seen.  Only old, dated junk that no one cares about hangs in the PR tab.

This ecosystem seems to be working. The people involved don't seem to have any problems managing and coordinating the merging process, at least from my POV.

Less `bureaucracy` means usually more joy.

**Comment by Zireael07** [comment]
I think a 'for merge' label for bigger PRs would be a great thing. Minor fixes get merged nearly immediately, but some bigger stuff is often not clear if it's still being tested/worked or not.

**Comment by i2amroy** [comment]
Just a note, but I'd like to point out that the person who goes to merge something before any fixes and the one who actually merges it at the end are not always the same. :P

**Comment by drbig** [comment]
Addressing the bureaucracy: @tvm1 You're technically right, the *best kind* of right!

Would the core devs then agree anyone can assume "is assigned" == "is in the merge pipeline"? That'd work too, and wouldn't add any work (well, at least any *immediately visible work*).

My initial goal is still the same: being easily able to tell between stuff being merged and everything else.

In any case I'm planning to leave this open for a week or so and see if we get to any consensus. I'll close it afterwards regardless of the outcome.

**Comment by Coolthulhu** [comment]
Currently issues are generally not assigned until they're being mergetested.
I don't think we have a strict label for "is being reviewed" or anything like that.
