### ISSUE TITLE
[DISCUSS] Surroundings not visible using the deathcam if the player dies while blind.

### ISSUE THREAD

**Issue by argent0** [CleverRaven/Cataclysm-DDA#12666]
If the player is killed while blind the deathcam won't show you the surroundings.
##

**Comment by DavidKeaton** [comment]
NPCs can still chat with you too. Two bugs I never got to.

**Comment by Rivet-the-Zombie** [comment]
>NPCs can still chat with you too.

"Hey, buddy. Hey, buddy. HEY, BUDDY. Are you asleep or something? Where did your head go?"

**Comment by DavidKeaton** [comment]
I remember testing and I died, only to have a npc tell me to DROP YOUR WEAPON

**Comment by kevingranade** [comment]
Could easily remove blindness effect when you die, but I'm tempted to leave
NPCs trying to talk to you :D

**Comment by DavidKeaton** [comment]
you get lonely in an apocalypse. even a corpse is a good shoulder to lean on.

**Comment by jakwings** [comment]
And a masochist corpse will keep suffering and smile. ;-) Oh, what the hell. You are already in hell.

**Comment by DavidKeaton** [comment]
*Because I could not stop for Death, he kindly stopped for me.*

**Comment by Cat09** [comment]
I like the idea of messages still showing, only what you *could* perceive. very creepy

**Comment by illi-kun** [comment]
Pretty minor issue.
