### ISSUE TITLE
Bug noeng translate

### ISSUE THREAD

**Issue by korick** [CleverRaven/Cataclysm-DDA#12665]
..\config\fonts.json modify to all "Terminus" -> "Terminus 14" plz!

**Comment by DavidKeaton** [comment]
care to do this? :-)

**Comment by korick** [comment]
hi, ILTG!
Game has a definite future, no one rogue-like with the amazing realism, thx. I use RU-language translate.

- if stay ..\config\fonts.json "Terminus" no radding
![Uploading R111111111.jpg…]()
- if modify to all "Terminus 14" readding perfectly
![Uploading R222222222.jpg…]() 
![Uploading R333333333.jpg…]()

**Comment by korick** [comment]
hi, ILTG!
Game has a definite future, no one rogue-like with the amazing realism, thx. I use RU-language translate.

- if stay ..\config\fonts.json "Terminus" no radding
![Uploading R111111111.jpg…]()
- if modify to all "Terminus 14" readding perfectly
![Uploading R222222222.jpg…]() 
![Uploading R333333333.jpg…]()

**Comment by korick** [comment]
hi, ILTG
- if stay ..\config\fonts.json "Terminus" anyone no reading symbols
```
    flS&neij: 32ae91c
    [M0TD] [fa^aou] [Caa&opeou] [Ie&] [IniaiS] [Iioeel [Iiiiuu] [Oeodul [fiuoial
    la iaeaeao niiauaeoS 11 aa&cino kevin.granade@gmail.com eee ia 616oi3.
```
- if modify to all "Terminus 14" reading perfectly (in RU language of course)
```
    Версия: 32ае91с
    [MOTD] [Начать] [Загрузить] [Мир] [Особое] [Опции] [Помощь] [Титры] [Выход]
    Об ошибках сообщайте по адресу kevin.granade@gmail.com или на форуме.
```
In folder Fonts, no see Terminus, only Terminus 14.
Sorry, I can`t add image in my comment

**Comment by DavidKeaton** [comment]
it is okay. :-)

**Comment by illi-kun** [comment]
This is duplicate of #10155.
@korick, your proposition is not universal one and it hardly depends on used system/configuration.

**Comment by korick** [comment]
OK, thanks for your attention, guys don`t forget change the direction of game log
Done
