### ISSUE TITLE
"Kill 100 zombies" mission should track all zombie kills, not just regular ones

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#12662]
In my current playthrough, I have 0 "regular" zombie kills, presumably due to the evolution system, making completion of that quest impossible.
##

**Comment by Zireael07** [comment]
Which day are you at?

**Comment by tvm1** [comment]
Winter start ?

**Comment by ejseto** [comment]
Over a year, now that you mention it. I made an option to set the starting year.

**Comment by kevingranade** [comment]
Regardless of start date, it should sum up all the kills of monsters in the
zombie species instead of using the base zombie type.

**Comment by ClosetPankin** [comment]
Hey Kevin, I am doing this quest right now and have definitely killed over 100 zombies - cleared 3 largo Home Depo's, a school, small town and a public works station. Are you sure it counts all zombies, because I seem to recall when I got the quest, she specifically said "regular zombies."

Cheers.

**Comment by ClosetPankin** [comment]
Ignore my last comment, I deleted it because I was wrong.

**Comment by kevingranade** [comment]
I meant we should change to do that instead of checking for a specific
zombie type like we do now.

**Comment by ClosetPankin** [comment]
You don't, from what I can tell. it just doesn't tell you when you've killed 100.

**Comment by DangerNoodle** [comment]
I was searching for an example of a separate bug that I have noticed in several builds, dating from months ago to current builds.

Conversing with the quest giver without the kill count being complete with generate two error messages. The first reports number of zombies killed, the second reports the target number. After this, answering the NPC's question that you have not killed enough enemies will lead to the quest inexplicably resolving itself, returning them to normal dialogue.

Despite this, asking if they have further quests will reveal that they have progressed to offering the next quest in the series.

**Comment by Leland** [comment]
The rapidity of monster upgrading is a known issue, see #12313 for that. When that's resolved, this mission will presumably be doable. But yes, the main issue here is that the quest should likely be tracking all zombie kills, regardless of what kind of zombie was killed.

I've updated the issue title to reflect this.
