### ISSUE TITLE
Night Vision and Lighting

### ISSUE THREAD

**Issue by RickRollYou2** [CleverRaven/Cataclysm-DDA#12671]
Night Vision (perhaps due to the lighting changes?) now gives 5 tiles of vision in darkness, which decreases to 1 tile near weak light sources such as consoles.

**Comment by tyrael93** [comment]
I can confirm this happens even with high night vision.

**Comment by ejseto** [comment]
It is to some degree intentional, presumably to simulate your night vision being overloaded. Complaining may get them to tweak it though.

**Comment by RickRollYou2** [comment]
The issue I was trying to report was the 5 tiles vision, not so much the 1 tile thing (which may or may not be intentional). Unless something changed in the way NV works now? In which case the description needs to be changed.

**Comment by i2amroy** [comment]
I'm pretty sure the intent was that night vision turns off in the light (and it kinda makes sense for synthetic NV), but I'll agree that this is pretty ridiculous. My cat can see the bugs in the darkness at basically the same level whether they are sitting in a totally dark room or with a night light on. Heck, they probably see *better* with a bit of light. I'm gonna vote for only having NV turn itself off if the light source is at least as strong as the NV.

**Comment by Rivet-the-Zombie** [comment]
>I'm gonna vote for only having NV turn itself off if the light source is at least as strong as the NV.

This sounds like the best solution.

**Comment by DeNarr** [comment]
So, this may be related, but it seems that a light strip is no longer enough light to craft / read by. Considering that was practically the only thing to use light strips for, I'm assuming this is a mistake.

**Comment by tyrael93** [comment]
Same goes foe the light you get from a terminal and atomic night lights. You can craft (brightly lit) without a problem, but reading is possible only in full light or with a fire nearby.

**Comment by DeNarr** [comment]
@tyrael93 Well, the lightstrip does not allow reading or crafting.

**Comment by DavidKeaton** [comment]
I love lightstrips, that needs fixed.

**Comment by kevingranade** [comment]
A lightstrip allows reading and crafting if it is in your inventory, which is as intended.
I'm fine with someone tweaking the nightvision cutoff to where it never reduces effective sight range, my concern was preventing nightvision from extending view range in normal light.

**Comment by kevingranade** [comment]
Correction, testing failure.  You can't read with a lightstrip in inventory, will fix that.

**Comment by DeNarr** [comment]
Yea, the killing of night vision is making it so things like glow sticks and light strips don't really have a purpose anymore. They used to be the thing you would carry with you if you planned on doing impromptu crafting or reading at night. Now I find myself activating them, and then dropping them cause I can't really carry them with me. It was at this point that I realized that until the night vision gets fixed, it's better to just turn on a flashlight or lantern, do what I need, then turn them back off.

**Comment by DavidKeaton** [comment]
using a flashlight or lantern eats up batteries so fast though! :-(

**Comment by DeNarr** [comment]
@DavidKeaton I know, it's not an ideal solution, and I'd love the proper use of light strips / glowsticks again, but in the mean time it is better than making them just to drop them after crafting one thing.

**Comment by DavidKeaton** [comment]
True true. Are atomic night lights affected as well? (assuming one can craft it, and have access to plutonium...)

**Comment by DeNarr** [comment]
Yes, they are effected as well. (You can always just use the debug menu to do tests like that). I've also noticed that with all the small lights, you can no longer read well. It is considered dim lighting. I always considered them to be similar to reading lights, so this kind of confuses me. I get why reading by the glow of a monitor could be difficult, but with these lights you could hold them right up to the book...

**Comment by tyrael93** [comment]
Is it just me or basic night vision gives you a 5 tile FOV now

**Comment by Coolthulhu** [comment]
It does. That may require a nerf too - it was good with just the 2 tile FoV. Maybe 3, now that zeds also have theirs.

**Comment by DeNarr** [comment]
@tyrael93 That's not just you. But you will also notice that everything you see is shaded out. I still find myself flashing on my flashlight to get a quick look at things with color.

**Comment by DeNarr** [comment]
I also just noticed that if you have a window letting sunlight into a house, you go straight from brightly lit to dark when you step out of the path of the light. There's no light diffusion.

**Comment by kevingranade** [comment]
Of course there's no light diffusion, do you have any idea how expensive
that would be cpu wise?

**Comment by Barhandar** [comment]
If basic nightvision (trait) is going to continue having 5 tiles of nightsight instead of 2, at least fix the description.

**Comment by chaosvolt** [comment]
The lighting rework in a nutshell:

![how is photon formed](https://cloud.githubusercontent.com/assets/11582235/8945045/bd766eb6-3549-11e5-9326-f7dedc3bce9c.png)

**Comment by kevingranade** [comment]
Nightvision is working as intended, and the description has been updated by #13079

**Comment by chaosvolt** [comment]
Are the walls still Lovecraftian light-devouring monsters? :V

**Comment by kevingranade** [comment]
Probably, if there's still a problem, open a new issue, and in general
please don't report unrelated problems in issue comments, because they'll
get lost.

**Comment by DavidKeaton** [comment]
the irc is good too.

**Comment by chaosvolt** [comment]
Hnng. Will check latest version in a bit.
