### ISSUE TITLE
Corrosive zombie spit print error.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12676]
When the corrosive zombie spits, I think it is called acid spit, it gives a bad fprint error.

Do not have the specific message right now. Will update if I spot it.

**Comment by tvm1** [comment]
All that should be fixed now, please try to recompile the latest (or grab the latest build).

**Comment by Soyweiser** [comment]
Have not seen it recently, saw it this weekend. Will assume it is fixed. Thanks for fixing it.
