### ISSUE TITLE
Firing upgraded weapons lists the name wrong.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12675]
When I tried to use my ++ steel spear to reach it listed the name of this weapon as `<color_green>++ </color_green>`.

http://prntscr.com/7h6s5y

Just a minor interface issue.

**Comment by tvm1** [comment]
This affect all `REACH_ATTACK` weapons when they're reinforced. There's some extraneous color-related stuff getting passed to `game::target()`.

**Comment by DavidKeaton** [comment]
not to mention the lack of item name.
