### ISSUE TITLE
Peeking around corners should not reveal you.

### ISSUE THREAD

**Issue by LexLonbray** [CleverRaven/Cataclysm-DDA#12685]
Peeking corner functionality is useless if everyone around it detect you after that. It's possible to peek through curtains and stay undetected, is there a good reason that shouldn't work with corners?

**Comment by Snaaty** [comment]
I think it does save you a turn that you'd have to otherwise spend moving forth and back. Although generally, I'd prefer it as well to not reveal the player.

**Comment by LexLonbray** [comment]
It does, in fact, consume 200 action points, just about going forth and back.

**Comment by Snaaty** [comment]
If that is true the functionality should absolutely be changed. Can't find the code right now, but if it is also a fixed 200 ap, that would even mean that if you're faster than average it is smarter to just walk around the corner and then return.

**Comment by FireCrow1973** [comment]
The whole point of peeking around corners should be stealth.
If you are detected its kinda pointless.
However if you are detected because of smell or noise that's different, that's your own fault.

I also don't like that you can't pass time while looking around corners.
You have to exit peeking mode, pass the time, and then peek around the corner again.
Would be great if you could just hit 5.

**Comment by DavidKeaton** [comment]
it would need to be re-coded, as it uses the examine interface, which has no concept of passing turns.

**Comment by Coolthulhu** [comment]
It doesn't reveal you. Peeking and waiting 200 moves have the same effect on player's visibility. Both peeking with movement and peeking through windows.

There may be some issues where FoV is asymmetric and the player can't see a monster who can see back, but peeking has no effect on those.

**Comment by LexLonbray** [comment]
Oops, my bad. It's actually about FoV, not peeking itself. Looks like everyone around the corner was able to see me before I peek around it and will be able to see them. 

It's like they peek around every corner from any distance within their sight, all the time.

**Comment by kevingranade** [comment]
No, it's not, in some specific circumstances monsters can see the player
when the player cannot see the monster, and the opposite also happens.
It's just that the monsters don't have a github account, so we don't see
them complaining about it.

**Comment by LexLonbray** [comment]
Damn. I was confused by yellow "!" before their names. It does show that they notice me in peeking mode when I press V, even though they actually don't. Maybe this should be calculated for tile that player actually stand on and not for peeking tile. If it's intended to tell how much monsters I will alert after moving on peeking position, then it should be another symbol at least.

**Comment by ArikVhedrovix** [comment]
I have been shot at and hit by a turret after peeking around a corner. Still not sure how it could even have gotten LOS on me. Which sort of seems to make peeking useless if you can still be shot anywhere on the body while peeking. I would expect to only be hit in the head at least. Also LOL for complaining NPCs.

**Comment by DavidKeaton** [comment]
you peek with your pelvis and an air horn.

**Comment by Coolthulhu** [comment]
You peek with your entire body, but for time span of zero. From monsters' (and NPCs') point of view, you just stand still for 200 moves.

**Comment by DavidKeaton** [comment]
Considering you aren't moving your entire body into that space, shouldn't the move cost be lowered? Perhaps even halved? Your feet don't move when you "peek", your torso leans.

**Comment by ArikVhedrovix** [comment]
I dont understand how I got shot then. There was no line of sight. I was behind a closed door on a double door, then peeked out. When I exited the peek, a turret inside the room shot me, seemingly thru the door. It only really makes sense if I was exposed for 200 moves, got shot and then it just happened to be displayed in a strange way. It was rendered as if I was shot through the door, but I think that is a fluke of the fact the rendering happened after I "moved" out of peek.

**Comment by Coolthulhu** [comment]
FoV isn't exactly symmetrical. It is supposed to be as symmetrical as possible, but for performance reason some simplifications had to be made.

Yeah, rendering can sometimes show you in the old location. It could be the cause of confusion here.

I don't really see a good way of implementing "sticking to the wall", though.

**Comment by kevingranade** [comment]
The reason for the high move cost is that you are being *careful*.

**Comment by DavidKeaton** [comment]
But you may as well jump out and back in. I can understand being careful, but being open for p much the same cost as moving seems much.

**Comment by Coolthulhu** [comment]
By peeking, you greatly decrease the risk of getting shot or noticed by something that can't see you from your current position.

It's very useful in labs and moderately useful when trying to stay stealthy near dangerous stuff.
