### ISSUE TITLE
PG_UP/DOWN in some windows are broken

### ISSUE THREAD

**Issue by eliotcougar** [CleverRaven/Cataclysm-DDA#12689]
In [V]iew it switches between items and monsters, like Tab does instead of scrolling through list
In [i]nventory it switches to the next page, but in addition to that it moves the cursor to the other column and opens the [e]xamine view of the item that happens to be active after that...
In [@]character screen PG_DOWN switches between tabs, but PG_UP does not... Also > works, but < does not... Weird...
##

**Comment by cogreaper** [comment]
Its likely just not bound and it expects you to toggle through at most its a small ui issue.

**Comment by eliotcougar** [comment]
It didn't happen before, and these kinds of actions are hardcoded and not rebindable... First two cases are especially annoying...

**Comment by illi-kun** [comment]
Particular case of #12112.
