### ISSUE TITLE
[CR] Spammy seatbelt

### ISSUE THREAD

**Issue by tvm1** [CleverRaven/Cataclysm-DDA#12696]
As outlined in http://smf.cataclysmdda.com/index.php?topic=10492.0

While smashing my purposely constructed one tile car with frame, seat and seatbelt with humvee, following can happen (it happens quite often in more mundane car crashes too):

1) `damage_direct()` determines what parts to destroy on the given tile and creates a list of parts to destroy in the given tile (eg., parts with index 3 and 5)
2) `damage_direct()` executes for loop on vector with 3 and 5
3) `remove_part(3)` determines that 3 is a seat and checks for seatbelt, if it's present on the seat, it calls itself recursively `remove_part(5)`
4) parts 3 and 5 are removed and control is returned to `damage_direct()`
5) for loop in `damage_direct` tries to call `remove_part()` on part with index 5 (seatbelt)
6) since seatbelt was removed in step 4, `debugmsg()` whines and spams "Trying to remove already removed part"

This also happens with windows/curtains.

Obviously there are several obnoxious solutions to this. There can be some unnecessary check to check if the part was removed already and `damage_direct()` won't call `remove_part()`. Or some logical sorting of the vector in step 1. Or passing some more return values from `remove_part()`. Or getting rid of the `debugmsg()` altogether ?

**Comment by narc0tiq** [comment]
One can easily argue that trying to remove an already-removed part should
be a no-op, so I'd be in favor of removing the debugmsg (optionally
swapping it for a quieter log if necessary).

**Comment by tvm1** [comment]
> One can easily argue that trying to remove an already-removed part should be a no-op, so I'd be in favor of removing the debugmsg (optionally swapping it for a quieter log if necessary).

I agree.

**Comment by DavidKeaton** [comment]
perhaps the parts could be in a list, and the list is passed to `remove_part()`, which removes from the list any items it removed, so when control comes back it only processes what's left?
