### ISSUE TITLE
Knocked down has no effect when throwing.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12697]
For some reason when knocked down, I can throw and it costs no additional time. So I stand up automatically by throwing. 

Think other actions might also just remove the debuf.

Not 100% sure btw, but the only time I saw the 'you are standing up' message after being knocked down was after I moved immediately after being knocked down.
##

**Comment by Oskar636** [comment]
Inconsistent, sometimes it will display you standing up after getting knocked down and throwing, sometimes not. Without throwing it is the same.
Build 5864 windows 64bit console

**Comment by davidpwbrown** [comment]
Throwing uses up moves, when removes the downed effect automatically, and silently. same as if you wait in place after being knocked down.
If you try and move during the downed effect period, you get the "you struggle to stand" message, its the using up moves that removes the effect, not throwing specifically.

As to making it more difficult to throw when downed, is that really the case? surely you can throw something from the floor, almost as good as you can throw it standing up?

**Comment by Night-Pryanik** [comment]
> As to making it more difficult to throw when downed, is that really the case? surely you can throw something from the floor, almost as good as you can throw it standing up?

Surely no. You can't effectively swing out hands while downed, so your actual throw ability is severely hindered.

**Comment by davidpwbrown** [comment]
Reduce effective skill or use up more moves?

**Comment by Night-Pryanik** [comment]
> Reduce effective skill

This.
