### ISSUE TITLE
Foraging prompt still appears when standing on top of underbrush

### ISSUE THREAD

**Issue by Ishindri** [CleverRaven/Cataclysm-DDA#12700]
Windows 7 w/tiles, 0.C-3312.  When standing next to underbrush, activating it forages automatically.  When standing on top of it, activating it gives you the "Forage through underbrush? Y/N" prompt.

**Comment by Coolthulhu** [comment]
It is intended, because you can't see the brush.

**Comment by Ishindri** [comment]
Understood.
