### ISSUE TITLE
NPCs Forever Asleep

### ISSUE THREAD

**Issue by DeNarr** [CleverRaven/Cataclysm-DDA#12709]
So I've started messing around with having a base (Bulletin Board), and I've been collecting NPCs to stay at the base. Well, some of my NPCs seem to be stuck in sleep mode. They ask if I need them to do anything before going back to sleep, I tell them to "Wake up!", and nothing happens. I just keep getting the same dialog over and over. It also does not matter how much time I let pass (as in, letting them sleep). They will still be sleeping after days left alone.

**Comment by kevingranade** [comment]
I'm not at all sure that's even implemented, they might not be resting
(recovering fatigue).

**Comment by Coolthulhu** [comment]
I added NPC sleep (to heal up) some time ago, but apparently there are some problems with it. Will check up on it. Might be some player-specific code that is in `game` but should be in `player`.

**Comment by slyscorpion** [comment]
I have a similar issue where companion NPCs even after sleeping for two days will complain about being tired all the time. I can wake them up but they'll keep complaining about sleeping.
