### ISSUE TITLE
"Someone forgot to code this message..." prompt appearing when receiving a job from an NPC.

### ISSUE THREAD

**Issue by slyscorpion** [CleverRaven/Cataclysm-DDA#12708]
![message_id_78](https://cloud.githubusercontent.com/assets/12873013/8261303/a8d7b63e-16c9-11e5-9ab8-7fb9f3cbb626.jpeg)

I've attached a screenshot of this prompt. This occurs in the Linux version of CDDA build 0.C-3837-g207cae3.

**Comment by Coolthulhu** [comment]
Most likely no longer happens due to big rework of NPC mission code.
