### ISSUE TITLE
"Zombie not found in tracker" spammy debug message.

### ISSUE THREAD

**Issue by slyscorpion** [CleverRaven/Cataclysm-DDA#12714]
This message occurs when you go up the stairs and a regular zombie follows you above ground.

Steps to reproduce: 

1. Go underground to a basement with zombies in it.
2. Get a regular zombie next to you while you are standing on the stairs.
3. Go up.
4. Back away from the stairs and wait for the regular zombie to come up the stairs. 

You should get a debug message about the zombie not being found in the tracker along with some coordinates. This has been occurring in several of the experimental builds and when you try to constantly press space to get rid of the message, the game crashes to desktop without saving.

This debug message and crash has occurred on build 0.C-3871-g2474e51.

Also, this is what I got in terminal after the crash: 

/usr/include/c++/4.8/debug/vector:353:error: attempt to subscript container 
    with out-of-bounds index 9, but container only holds 9 elements.

Objects involved in the operation:
sequence "this" @ 0x0x539f9a0 {
  type = NSt7__debug6vectorIP7monsterSaIS2_EEE;
}

I've noticed that if you block line of sight of the zombie the debug message stops and only comes back when the zombie is in view. If an NPC happens to kill it then the debug message also stops.

**Comment by Soyweiser** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/12583 Same as this one.
