### ISSUE TITLE
Removing mutations overwriting traits doesn't give traits back

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#12727]
For example:
- Start a character with (inherent traits) Carnivore and Hates Fruit
- Mutate Herbivore
- Mutate back Carnivore

Should result in:
- Character gaining Carnivore and Hates Fruit

Results in:
- Character gaining Carnivore
##

**Comment by wapcaplet** [comment]
I could not reproduce this in 0.E-9737-g511ddcb179 using the original steps:

1. Create new character ("Volunteer Mutant") with "Carnivore" and "Hates Fruit"
2. Mutate to "Herbivore" - lost both "Carnivore" and "Hates Fruit" (OK)
3. Mutate to "Carnivore" - regained both "Carnivore" and "Hates Fruit" (OK)

both "Carnivore" and "Hates Fruit" (OK)
