### ISSUE TITLE
npc_class text missing in 0.C Stable and 0.C-3993-g49ec06d

### ISSUE THREAD

**Issue by slyscorpion** [CleverRaven/Cataclysm-DDA#12731]
I went back to playing 0.C stable due to random crashes affecting my games in the experimental builds for now and I came upon this minor issue. 

Basically all I did was ask "What are you doing?".

I am having issues with uploading images directly to Github so here's an imgur link: 

http://i.imgur.com/7nHXlf5.jpg

**Comment by Treah** [comment]
So it does not do this in the experimental build? 

If its fixed there I don't think anyone is going to back port it to the stable build. Also I think there was some discussion with moving that one up to a more current one anyway.

**Comment by slyscorpion** [comment]
I am not sure to be honest as most NPCs seem to respond properly in experimental when asked "What are you doing?" but maybe this issue is in experimental also?

**Comment by slyscorpion** [comment]
@Treah 

Actually, this issue DOES occur in experimental. I just had the same issue occur today in version 0.C-3993-g49ec06d.

See this screenshot: http://i.imgur.com/ZeB9zLs.jpg

**Comment by mugling** [comment]
Ancient bug and many changes to NPC code since then. Please re-open if reproducible in `master`
