### ISSUE TITLE
Player can move up and down stairs while grappled

### ISSUE THREAD

**Issue by Ishindri** [CleverRaven/Cataclysm-DDA#12736]
From [the forum](http://smf.cataclysmdda.com/index.php?topic=5865.msg238150#msg238150): you can still move up and down stairs while grabbed by zombies.
##

**Comment by tvm1** [comment]
This is more fundamental. Player (or npc) should go through the whole `character::move_effects()` when calling `game::vertical_move()`.

There are more occasions where player (or npc) can vertically move when they shouldn't (being downed, webbed, being trapped or crushed, etc.).
