### ISSUE TITLE
Single malt whiskey spawns in barrels

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#12733]
`(2800) Wooden barrel of single malt whiskey`

Maybe at least limit the amount of charges like with lighters?
##

**Comment by John-Candlebury** [comment]
Unless it spawns on a distillery, I see no reason to have it spawn in barrels at all.

**Comment by BevapDin** [comment]
What's the problem? Barrels *are* big, stuff that spawns in containers automatically fill up the whole container.

**Comment by Coolthulhu** [comment]
They spawn in many places where a bottle of wine is expected. For example, in a fridge.

**Comment by Rivet-the-Zombie** [comment]
I assure you that the barrels are quite intentional, since you can [buy whiskey by the barrel](http://www.jackdaniels.com/by-the-barrel).

Them showing up in refrigerators is wrong, though.

**Comment by ituluwituluwzev** [comment]
Closing - No active discussion for over a year. Feel free to reopen if there's still interest.
