### ISSUE TITLE
Disassembling with "B" but without proper tools fails without good reason.

### ISSUE THREAD

**Issue by Shoes01** [CleverRaven/Cataclysm-DDA#12763]
I try to "B"utcher a skitterbot without a soldering iron, and I am told "There are no corpses here!" instead of "You need a soldering iron for that!". The former could lead some players to believe that they can't "B"utcher skitterbots.

**Comment by narc0tiq** [comment]
Technically, they can't -- the "butchering" of skitterbots and the like is
a disassembly action that's being overloaded into the butcher menu. This
does not in the slightest invalidate that the error should be appropriate
to the task.
