### ISSUE TITLE
Translation bug in russian

### ISSUE THREAD

**Issue by jarmush** [CleverRaven/Cataclysm-DDA#12761]
Whitespaces instead of black powder ingredients in crafting window in russian
![2](https://cloud.githubusercontent.com/assets/6452938/8302736/7ace7aae-19a1-11e5-9e7a-e2ab72bcadbf.png)

OK in english
![2015-06-23 12 10 32](https://cloud.githubusercontent.com/assets/6452938/8302739/7d65b782-19a1-11e5-9332-1e823f4c9e05.png)

**Comment by Night-Pryanik** [comment]
I already fixed this translation oversight in transifex, as I said in [forum] (http://smf.cataclysmdda.com/index.php?topic=10473.0). We just need an updated translation template.

**Comment by drbig** [comment]
@Night-Pryanik Can you confirm here when it's (completely) fixed please?

**Comment by Night-Pryanik** [comment]
No problem.
As for 9335e21 this bug still exists.

**Comment by Night-Pryanik** [comment]
12d77c0. Problem solved.
