### ISSUE TITLE
Undefined zone crash

### ISSUE THREAD

**Issue by Lain-** [CleverRaven/Cataclysm-DDA#12771]
Reported by user mattychan here: http://smf.cataclysmdda.com/index.php?topic=10642.0

"I have both static, and random npcs enabled.
Had to set up the no auto pick up zones in a house, and at one point wanted to cancel out of a certain zone.
So what I did was press "Shift-Y" then "A" to add the zone, but changed my mind and mashed escape. It got stuck at the name screen so I didn't think and hit "Enter", and boom game crashed. :(

I am using experimental version 0.C 3286"

**Comment by Coolthulhu** [comment]
Will be closed by #12742

**Comment by Lain-** [comment]
As #12742 was merged, closing this.
