### ISSUE TITLE
Steeltoed boots cannot be cut up

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#12770]
Experimental v. c8854c6
Steeltoed boots cannot be cut up for materials. I get a message saying they are made of a material that cannot be cut up. They are part Steel, so I guess that part kind of make sense. I would think they should give at least a piece or two of leather and maybe some scrap metal.

**Comment by kevingranade** [comment]
The 'cut up' system is* a fallback for a disassembly recipe, but it only
makes sense on items that are made entirely of materials that can be cut
up, if there are extraneous bits, like the steel toe of a boot, the code
doesn't know what it should turn into, so it bails out.  For mixed-material
items, they need a disassembly recipe.

*It didn't start out that way, but that's how it has evolved.

**Comment by ArikVhedrovix** [comment]
I think I understand. Would adding a recipe to recipe_armor.json be enough so that they could then cut up? Or would steeltoe boots have to be disassembled even with a recipe because some of the material is not cuttable?
 
If a recipe is enough I can do a PR.
Something like:
```json
},{
  "type" : "recipe",
  "result": "boots_hiking",
  "category": "CC_ARMOR",
  "subcategory": "CSC_ARMOR_FEET",
  "skill_used": "tailor",
  "difficulty": 2,
  "time": 35000,
  "reversible": false,
  "autolearn": false,
  "tools": [
    [
      [ "needle_bone", 10 ],
      [ "needle_wood", 10 ],
      [ "tailors_kit", 10 ],
      [ "sewing_kit", 10 ]
    ]
  ],
  "components": [
    [
      [ "leather", 10 ],
      [ "tanned_hide", 2 ]
    ],
    [
      [ "scrap", 3 ],
      [ "steel_chunk", 1]
    ]
  ]
},{
```

**Comment by kevingranade** [comment]
I believe that would do it.
