### ISSUE TITLE
Suppress json output with default field to write().

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#12774]
We currently write out and read a lot of default values in save files, we could cut down a lot on the volume (and there fore time to write/read) if we had a simple way to suppress output if something is a default value.
What I'm thinking is an extension to the ```json::write(type)``` methods to accept a default value, so ```json_write(type value, type default)```.  If value == default, the method would simply write nothing, and on load, the field would stay initialized to its default value.

**Comment by tvm1** [comment]
That is good idea.

**Comment by mugling** [comment]
Fixed by #12791
