### ISSUE TITLE
mutation issues

### ISSUE THREAD

**Issue by KiwiTrinsic** [CleverRaven/Cataclysm-DDA#12784]
Further investigation following PR #12711 and Kevin's remark there and I think I've located the source of both the bug I fixed and additional mutation bugs. The toggle_mutation function in the character class. The function itself does not have a bug, but rather the way it is used. 

The function takes the given flag and either adds that mutation to the player if they don't have it, or removes it if they do have it. However, there don't seem to be any instances in the code where people actually use it that way, it is always called with the intention to either add a mutation or remove a mutation. This means whenever it is called without careful checking beforehand, one could remove a mutation when trying to add it or add it when trying to remove it.

It seems to me the cleanest fix would be to break the toggle_mutation into add_mutation and remove_mutation functions. Then the code will know which one people are trying to do and take the appropriate measures when any issues arise. I can put together a PR for this if it sounds like a reasonable solution to everyone else.

**Comment by kevingranade** [comment]
That does sound good, as far as I know there is no need for an explicit
toggle anywhere.

**Comment by DavidKeaton** [comment]
Yes, having a toggle is a bit silly, explicit add or removes is better.

**Comment by KiwiTrinsic** [comment]
Fixed with #12792
