### ISSUE TITLE
Access to map extras in char creation

### ISSUE THREAD

**Issue by joneskun** [CleverRaven/Cataclysm-DDA#12780]
I had a "chopper crash survivor" challenge scenario in mind. Can someone with a working cdda toolchain add at least mx_helicopter to a convenient place? And maybe scoop it up from existing maps if needed. Thanks!

**Comment by drbig** [comment]
This doesn't even sound like an issue...

@joneskun Given noone replied here can you at least elaborate what it is exactly you need *someone else to do for you*?

**Comment by Soyweiser** [comment]
So you want some tag added to the map when a heli crash event is created? So you can start a game there? Seems not a trivial thing to do. And ... then you would create a challenge scenario that is by default invalid on the creation of a new map. (crash sites are not generated at map creation iirc).
