### ISSUE TITLE
Show Save game message before saving

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#12797]
Every time I hit an autosave, I think my machine has stopped responding and I hit several moves before I realize it is just saving. Would it be possible to print the "Saving this may take a while" message BEFORE starting the save?

**Comment by jakwings** [comment]
You are right. And I want to know if it is really saved, not just "saving".

**Comment by drbig** [comment]
@ArikVhedrovix Which version are you playing?

Latest code seems to at least add the message before actually saving (though I guess it isn't displayed before the saving finishes...). I'm looking into this, obviously :)

**Comment by drbig** [comment]
Are we closing this, given the fact it doesn't work in tiles is unrelated (and deeper) issue?

**Comment by Coolthulhu** [comment]
I'd say it should stay open until we can fix the tiles one too.

**Comment by ArikVhedrovix** [comment]
Ok. Sorry I forgot to mention version. I am using Windows Experimental Console v c8854c6.
