### ISSUE TITLE
Build:error L_ERR_* etc not declared

### ISSUE THREAD

**Issue by Frost-wood** [CleverRaven/Cataclysm-DDA#12795]
It seems the complier is spitting out errors that :
||=== Build: Release in Cataclysm (compiler: GNU GCC Compiler) ===|
C:\cataclysm\Cataclysm-DDA\src\item.cpp||In member function 'long int item::get_remaining_capacity_for_liquid(const item&) const':|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4067|error: 'L_ERR_NONE' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp||In member function 'item::LIQUID_FILL_ERROR item::has_valid_capacity_for_liquid(const item&) const':|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4111|error: 'L_ERR_NOT_CONTAINER' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4115|error: 'L_ERR_FULL' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4119|error: 'L_ERR_NO_MIX' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4124|error: 'L_ERR_NOT_CONTAINER' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4129|error: 'L_ERR_NOT_WATERTIGHT' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4131|error: 'L_ERR_NOT_SEALED' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4135|error: 'L_ERR_NO_MIX' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4142|error: 'L_ERR_FULL' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4145|error: 'L_ERR_NONE' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp||In member function 'bool item::fill_with(item&, std::string&)':|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4193|error: 'L_ERR_NONE' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4195|error: 'L_ERR_NO_MIX' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4198|error: 'L_ERR_NOT_CONTAINER' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4201|error: 'L_ERR_NOT_WATERTIGHT' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4204|error: 'L_ERR_NOT_SEALED' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4207|error: 'L_ERR_FULL' was not declared in this scope|
C:\cataclysm\Cataclysm-DDA\src\item.cpp||In member function 'item::LIQUID_FILL_ERROR item::has_valid_capacity_for_liquid(const item&) const':|
C:\cataclysm\Cataclysm-DDA\src\item.cpp|4146|warning: control reaches end of non-void function [-Wreturn-type]|
||=== Build finished: 16 error(s), 1 warning(s) (1 minute(s), 5 second(s)) ===|

Using code-blocks

**Comment by BevapDin** [comment]
#12591

**Comment by Frost-wood** [comment]
Alright fixed by http://www.codeblocks.org/downloads/26 installing the new version of MingGW thanks!
