### ISSUE TITLE
Lost money after quest completion

### ISSUE THREAD

**Issue by stasalcatraz** [CleverRaven/Cataclysm-DDA#12793]
I found NPC site and take a quest. Before this I have 20000$ on my bank account. After that I've come to NPC and choose to take some items as payment. After that there was only 4000$.

**Comment by DavidKeaton** [comment]
Seems like you're paying for them without your consent. lol.

**Comment by stasalcatraz** [comment]
It seems like they gave me their account with reward instead of my account with my money :)

**Comment by DavidKeaton** [comment]
That could be possible!

**Comment by drbig** [comment]
@stasalcatraz Can you replicate the bug on newest experimental?

**Comment by stasalcatraz** [comment]
Can not reproduce on a1dfe6d, may be because NPC does not want to trade with me. I'll try later, when i find proper NPC.

**Comment by stasalcatraz** [comment]
Can't reproduce now
