### ISSUE TITLE
Manual vehicle turrets usage

### ISSUE THREAD

**Issue by Terranaut** [CleverRaven/Cataclysm-DDA#12801]
Version: 8c50fd2 (0.C-3351), double checked with f9144d4 (0.C-3359)
SDL

I'm not sure if that's exactly the case, but I think vehicle mounted turrets don't seem to be recognized by the game/vehicle at all. I was installing a turbolaser turret on my vehicle and went to activate it. The game says it was activated, but is configured not to shoot.
In the configuration menu, however, it says 'Cycle through turret modes' and only offers one option: "Finish"
Trying to aim manually tells me that the turret is offline and I can't use it.
I've confirmed this by spawning a vehicle that comes with a gun from the debug menu (humvee_gl, gun on the humvee is a mounted Mark 19 GL)

![image](https://cloud.githubusercontent.com/assets/3919555/8396454/33fb9356-1da6-11e5-8481-707ebef61f3a.png)

savefile if it matters:
https://www.dropbox.com/s/c276qj0nsbzjcjj/save.7z?dl=0

**Comment by Terranaut** [comment]
Turns out I'm an idiot that didn't quite know how one of the mods he ticked works, feel free to close at any time.
(at least my report structure wasn't completely awful)

**Comment by ArikVhedrovix** [comment]
I can't figure this out either. Lol. How do you fire the turrets?

**Comment by Terranaut** [comment]
You step onto the tile and press F with your hands free to use it manually. You need a certain item to make them autonomous which is, or so I've been told, crafted with a high mechanics and computer skill (the latter I currently lack so I can't confirm it right now).
This is, apparently, due to the vehicle additions mod.

**Comment by ArikVhedrovix** [comment]
Ah. Hands free. Doh. I tried to use the F key but my hands were full no doubt. Thanks!

**Comment by Coolthulhu** [comment]
I guess the manual turrets could get a line saying "manual only" or something like that.

**Comment by ArikVhedrovix** [comment]
Maybe a failure message about needing hands free. Idk.

**Comment by drbig** [comment]
> I guess the manual turrets could get a line saying "manual only" or something like that.

> Maybe a failure message about needing hands free. Idk.

Perhaps both? This smells like the "welding goggles issue".

**Comment by mugling** [comment]
Turret bugs are covered in other issues
