### ISSUE TITLE
Double Barreled Pipe Shotgun doesn't train shotguns skill

### ISSUE THREAD

**Issue by saladasa** [CleverRaven/Cataclysm-DDA#12812]
I've killed a few zombies with my Double Barreled Pipe Shotgun but my shotguns skill is still at 0%
##

**Comment by saladasa** [comment]
Forgot to mention I'm using 0.C-3313

**Comment by ArikVhedrovix** [comment]
Item data seems to say it trains shotguns. Are you sure you had some focus? Without focus you don't learn skills well/at all if I understand correctly. Poor morale and other things can reduce your focus as can learning/practising a bunch of other skills right before trying to practice shotguns. See: [Skills] (http://www.wiki.cataclysmdda.com/index.php?title=Skills) for a better, more detailed explanation.
```json
{
    "id": "pipe_double_shotgun",
    "type": "GUN",
    "symbol": "(",
    "color": "brown",
    "name": "double-barrel pipe shotgun",
    "description": "A home-made double-barreled shotgun.  It is simply two pipes attached to a stock, with a pair of hammers to strike the two rounds it holds.",
    "price": 50000, "//": "Should probably be either $300 or $500 - on the one hand, having one double-barreled shotgun is better than having two single-barreled shotguns, but on the other it takes more materials to make two single-barreled shotguns than one double-barreled shotgun",
    "material": ["steel", "wood"],
    "flags": ["RELOAD_ONE", "NEVER_JAMS", "MODE_BURST","RELOAD_EJECT"],
    "skill": "shotgun",
```

**Comment by Man-animal** [comment]
Double pipe shotgun has an extremely high base dispersion so it's possible you're running into the "gun too inaccurate to learn" mechanic.

What're your shotgun and marksmanship skills at?

**Comment by saladasa** [comment]
My marksmanship level is 5 and my shotgun level is 0 (0%). I've used the shotgun 4 or 5 times, only in dire circumstances which makes it pretty likely that my focus was low at the time. I'm new to the game and I'm still a bit confused as to how skill training works. I thought I came across a bug but I think I'm just learning how this game works lol. Sorry if I wasted anyone's time.

**Comment by Man-animal** [comment]
Yeah, it sounds like the gun is too inaccurate to reliably gain XP.

Whenever you make a ranged attack, the game takes your weapon and ammo dispersion, and compares them to your skill-based dispersion plus a random number based on PER.  If the first number is higher than the second, you don't gain any XP.

Don't feel bad, as it's not described anywhere in game and the only obvious indicator that you are running into this limit (aside from not gaining XP) is a 1-in-30 random message.

**Comment by ArikVhedrovix** [comment]
Yes, perhaps the message warning that no skill gain should be more common? That might get annoying though. I would think it should be based on your intelligence how quickly you notice the weapon isn't gonna improve your skill.

**Comment by BevapDin** [comment]
> Yes, perhaps the message warning that no skill gain should be more common? That might get annoying though.

Some people already complain that it's too common: http://smf.cataclysmdda.com/index.php?topic=10069

**Comment by narc0tiq** [comment]
It would probably be okay if it happened (reliably) once (the first time
you try it) per weapon/ammo combo per game session.

**Comment by mugling** [comment]
Training was completely reworked
