### ISSUE TITLE
Crash - unknown cause

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#12824]
I have a save that consistently crashes within a few turns of the reload.

Possible trigger is the interaction between the NPC and shocker zombie outside (south). Debug menu -> remove all monsters seems to prevent the crash.

Zipped save folder is here:
https://www.sendspace.com/file/2vz1ys

Linux, tiles, gcf3ca08

**Comment by BevapDin** [comment]
Thanks for the report and the save.

This is the crash:
```
Program received signal SIGFPE, Arithmetic exception.
0x089f9d4d in player::melee_attack (this=0xb306948, t=..., allow_special=true, force_technique=...) at src/melee.cpp:397
397         const int weight_cost = weapon.weight() / ( 12 * str_cur );
(gdb) print this->is_npc()
$4 = true
```
It's an NPC (`this->is_npc()` is true).

This is the output of `git blame`:
```
5ce7de46 (Coolthulhu 2015-05-31 22:44:56 +0200 397)     const int weight_cost = weapon.weight() / ( 12 * str_cur );
```

I think there needs to be a `std::max(1, str_cur)`. And a ping @Coolthulhu, just to be sure.

**Comment by Coolthulhu** [comment]
Yeah, should be `std::max` or `+1`. There may be some other divisions by 0 related to `[stat]_cur` variables, I'll grep them.

**Comment by romkuma** [comment]
Confirming this fixed the crash for me as well. Thanks!
