### ISSUE TITLE
Add stim values to tea and tea related items

### ISSUE THREAD

**Issue by mightyagrippa** [CleverRaven/Cataclysm-DDA#12836]
Tea, tea leaves, and milk tea have stim = 0. This seems to be an oversight since dandelion and herbal tea both have stim value.

A quick googling suggests tea has ~25% the caffeine of coffee, so stim = 3 for tea/milk tea and stim = 2 for raw tea leaves would be reasonable.

**Comment by Rivet-the-Zombie** [comment]
That's odd; they used to have a stim value. I bet they got changed when the stim system was altered a month or two ago.

**Comment by Cat09** [comment]
is there any suggestion for values for herbal / dandelion? I don't generally think of herbal as being stimulant-like. perhaps a temporary small focus effect... there are a lot of different herbal teas out there though...

**Comment by Rivet-the-Zombie** [comment]
It would probably be best to give the herbal teas a minimal effect, so that a caffeine addict can still get their fix from them, but it won't count for very much stimulant value.

**Comment by mightyagrippa** [comment]
Agreed, herbal and miscellaneous teas have trace amounts if any of caffeine. Stim value of 1 seems fine if that will let caffeine junkies use them as a desperation drink to soothe the shakes. Is there a precedent for fractional stim value?

**Comment by Cat09** [comment]
I'd rather remove caffeine from them entirely, since most have none. let the caffeine addicts go into withdrawl or find real tea.

**Comment by kevingranade** [comment]
Caffeine isn't the only mild stimulant around, IIRC the tinctures in
question do have other stimulants in them.
