### ISSUE TITLE
Impossible to break pavement?

### ISSUE THREAD

**Issue by StephenV25** [CleverRaven/Cataclysm-DDA#12833]
First off i have no idea if this is where to report bugs but it seems in the latest experimental i can't break pavement, tried using the jack hammer, the french hammer, and the pickaxe none of the 3 are able to break the pavment in the road. this is a screenshot ingame after trying to break the tile north of me with a pickaxe http://i.imgur.com/Zct8qG0.png .
##

**Comment by tyrael93** [comment]
as of now, no.
Nice penismobile, by the way.

**Comment by StephenV25** [comment]
"as of now, no." as in its a known bug? or removed feature? also that never dawned on me when i put a minesweeper on the front of a swat truck.....

**Comment by tyrael93** [comment]
No idea, coolthulu's the one working on Z levels, he'll brief you if he comes by.

**Comment by Coolthulhu** [comment]
It looks like the same bug that is preventing ceiling collapsing. I guess I'll have to hack up some solution for now (the real solution would be quite complex).

**Comment by StephenV25** [comment]
I'm not trying to dig a staircase in the pavement, just trying to break the pavement so i can dig a shallow pit to build a wall in. i wouldn't expect that to have anything to do with z-levels

**Comment by Coolthulhu** [comment]
It is z-levels related because I'm reworking floors/wall to be more like in Dwarf Fortress, where you have a floor section and a possible wall section below it. When you destroy the floor section but not the wall section below, the floor will be regenerated from the wall below it.

Before, the pavement would be destroyed to dirt+items. Now it can be destroyed to empty space instantly. I'll need an option to force it to regenerate the floor without attacking the wall below.

**Comment by StephenV25** [comment]
ah well this is all beyond me, so ill leave it to you devs. when this is closed does that me the issue will be fixed in the experimental branch? i don't quite understand github yet.

**Comment by Coolthulhu** [comment]
Yes, the issue will stay open until a fix (or at least an attempted fix that looks like a fix) gets merged.

**Comment by Eldhelion** [comment]
@Coolthulhu I'm new here, and have no idea how z-level are going,but instead of using DF approach, why not use the gnomoria one?

and sorry for changing topic :P

**Comment by Coolthulhu** [comment]
If I recall correctly (only seen gnomoria for like 30 minutes total and long ago), gnomoria has tiles above always check for tiles below rather than own tiles. In DDA this wouldn't be possible without rewriting a large part of the code or altering terrain/flag checking functions to check below (which wouldn't work in 2D mode).

**Comment by Eldhelion** [comment]
well, english is not my native language and I`am not sure if I understood correctly what you said.

In gnomoria, each z-level tile have 2 information (floor and wall), you can build a wall, if that tile have a floor. and you can build a floor, if there is a adjacent tile with floor or the tile below have a wall.

As I said, I'm new here, and didn't dove into the code, but if the map is a matriz (array of array) and it have a struct with the info of that tile.

I thing, you just need to rename the existent tile info to floor, add a new to wall.
And when something is built/deconstructed verify if there is wall below, or adjacent floor

Fences/pavement etc could be a passable 'wall', so when you deconstruct the pavement, you get to see and interact with the floor of said tile

**Comment by Coolthulhu** [comment]
Well, then it's more similar to Dwarf Fortress than I expected. In fact, it's directly copied from Dwarf Fortress.

**Comment by Rivet-the-Zombie** [comment]
From what I can tell, Gnomoria is a direct ripoff of DF with added isometric graphics. I wouldn't be surprised if most/all of the output of their UI is cribbed from it.

**Comment by Eldhelion** [comment]
how someone who play both, I don`t think that DF and gnomoria are equal on the map thing.

In DF, if you put a floor on a hole, you can't build a wall on top of said floor - This annoys me -
It's only possible build a wall on top of a natural floor, wich is very restrictive on terraforming and so on the way you build your fortress.

On the other hand, gnomoria have this "floor/wall struct" thing, which is more flexible and in my opinion more easy to code

**Comment by drbig** [comment]
@Eldhelion This is a long-term thing, and *We Know* ;) Please feel free to add more suggestions etc. here!

**Comment by drbig** [comment]
@StephenV25 The above also considers you.

We do welcome involvement!

**Comment by Eldhelion** [comment]
@drbig , I didn't get your point, on the "This is a long-term thing".
Anyway, I gave my 2 cents to the thread and without knowing the code I can't think on long term flaws on my suggestion. 
Well, I can think on plenty, but this is not a build simulator :P.

I could look the code, but, I`m waiting on the (CMake and CLion #12803) to dive on the code

**Comment by karlnp** [comment]
you can look at the code with Clion as is - it'll still do all the autocomplete things and be good at navigating the project. you just have to build it manually for now.   Give it a shot! I think it'll help answer your questions. :)

**Comment by Headjack** [comment]
Yeah, as per DF, the best way to manage the substance of a floor on one z-level differing from the substance of the 'wall' (or tile) on the z-level beneath it is to have a floor tile placed on the higher one, and allow it to be breakable or removable & thus reveal the substance of the tile below forming the new surface. As long as space-above-a-'wall' and flooring are both crossable and such, it functionally acts like road tiles being replaced with dirt has traditionally behaved.

**Comment by StephenV25** [comment]
@drbig I'm not smart enough to code, all I know how to do is report bugs and how they get fixed so I can finish my base in game. I'm a simple man.

**Comment by DavidKeaton** [comment]
*tips rancher hat*

**Comment by WizardOfOoo** [comment]
Pavement can now be broken by activating a pickaxe.
