### ISSUE TITLE
Crash (segfault) with corrupt stack

### ISSUE THREAD

**Issue by dholmes215** [CleverRaven/Cataclysm-DDA#12840]
I pulled 4410a63, started a game, an a few minutes in it crashed.  I had gdb attached but there's very little information to be had: 

(gdb) bt
#0  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) print $rip
$2 = (void (*)(void)) 0x0
(gdb) print $rsp
$3 = (void *) 0x22b268

I don't know how to go about debugging something like this.  If nobody else reports any problems, I could try poking through the raw stack memory.

I had previously been playing 834dde7 which I pulled yesterday morning, so it might be caused by something very recent.

**Comment by karlnp** [comment]
Is this still happening, @dholmes215 ?

**Comment by dholmes215** [comment]
It hasn't happened since.

**Comment by DavidKeaton** [comment]
what was happening? it was a dereference issue, curious where.

**Comment by drbig** [comment]
Indeed. @dholmes215 please close if it's fixed. Otherwise please tell so :)

**Comment by dholmes215** [comment]
I still have the crash in the debugger, but haven't had time to investigate it yet.  I will try digging into it tomorrow.

**Comment by dholmes215** [comment]
0x22b228:       0x00000006038a99e8      0x000000000022b270
0x22b238:       0x00000000fffffffc      0x000000000022b2d0
0x22b248:       0x0000000100544061      0x000000000022b270
0x22b258:       0x00000006038a8af8      0x000000000022b270
0x22b268:       0x00000003f7b349c6      0x00000006038a9640
0x22b278:       0x00000006038a99e8      0x00000006038a99e8
0x22b288:       0x0000000000000030      0x0000000c0725ebc0
0x22b298:       0x0000000100e60b80      0x0000000603b72a20
0x22b2a8:       0x000000000022b2b0      0x0000000000000000
0x22b2b8:       0x0000000000000000      0x0000001000000000
0x22b2c8:       0x00000001000017ec      0x000000060079e0d8
0x22b2d8:       0x0000000000000050      0x0000000000000031
0x22b2e8:       0x00000000fffffffc      0x0000000000000000
0x22b2f8:       0x00000001006e843d      0x00000006038a88f0
0x22b308:       0x0000000000000000      0x0000000603b72c28

The crash is at:

0x22b268:       0x00000003f7b349c6      0x00000006038a9640

0x00000003f7b349c6 is in cygstdc++-6!__dynamic_cast, which was called earlier form:

0x22b2f8:       0x00000001006e843d      0x00000006038a88f0

0x00000001006e843d is monster::die(), monster.cpp:1517:

    player *ch = dynamic_cast<player*>( get_killer() );

There are other comprehensible return addresses on the stack, but some of them look to be stale and unrelated to the current backtrace. Unfortunately I haven't managed bring gdb to its senses, and I think figuring this out from the data I have is going to be too much work to sign up for.

**Comment by DavidKeaton** [comment]
could be a nullptr being returned, it'll try to invoke some part of it, then that would explain the RIP = 0x0
