### ISSUE TITLE
Unusually resilient wire (vehicle)

### ISSUE THREAD

**Issue by DodgingRain** [CleverRaven/Cataclysm-DDA#12854]
Crashing a ~3,600 kg truck with a steel ram at a speed of 60 mph into a long line of wire that is part of a base perimeter outlining stops the truck completely.  Furthermore, the wire was barely damaged.  The -LONG- base perimiter weights ~1,100 kg.  If the wire was not attached to the base but was its own entity, it would be shoved to the left but with little to no damage.

**Comment by DavidKeaton** [comment]
Well that's no fun.

**Comment by drbig** [comment]
Aye. I wonder how to label it... The whole vehicle vs. environment thing is still a big issue overall.
