### ISSUE TITLE
Vehicle building game crash

### ISSUE THREAD

**Issue by Sacrez** [CleverRaven/Cataclysm-DDA#12869]
Version: 0.c-3984-g4fa2057-dirty
Running on a server for shared map: http://roguenex.us/#
Save file: http://s000.tinyupload.com/index.php?file_id=66623494146662238349

The error: Game crashes upon installing any vehicle part

I'm not sure how to get to reproduce the bug on another client, however, on the save file that's uploaded here, upon trying to install any kind of part on the car, on any tile of the car, I am getting the following error:
http://i.imgur.com/axE0FO9.png
http://i.imgur.com/PlrzQer.png
http://i.imgur.com/MieQVv8.png
http://i.imgur.com/MH5Ajca.png

All are the same error.

Steps to reproduce inside the save provided:
1) (E) Look at the car
2) Install any part
3) Move character
4) ERROR

**Comment by tvm1** [comment]
Can't reproduce with the save and current version. Seems to be fixed.

**Comment by Sacrez** [comment]
@tvm1 Do you see the car in your game? I've just downloaded the latest release, C 3391, to try on my local machine but the car is gone.

**Comment by tvm1** [comment]
Sure, it's perfectly visible.

**Comment by Sacrez** [comment]
I assume it's fixed on the newest release then. I will wait until the server also updates to check if the issue persists and it's not networking.

**Comment by drbig** [comment]
@Sacrez Aye. Please report back!

**Comment by Sacrez** [comment]
Ok, the issue has been fixed. Once the server updated the vehicle building works as intended!
