### ISSUE TITLE
Spore Clouds damage cars when run into

### ISSUE THREAD

**Issue by Shoes01** [CleverRaven/Cataclysm-DDA#12877]
Version c3588c3.

Running into spore clouds probably shouldn't impact driving, or the name should be changed in order to avoid confusion.
##

**Comment by Cat09** [comment]
where are creature stats stored? there must be a mass or weight stat somewhere.

**Comment by i2amroy** [comment]
The only thing that can be changed is the size, size is currently intrinsically hardcoded to control weight as well.

That said spores are TINY, so crashing into them shouldn't do anything more than crashing into a squirrel.

**Comment by Cat09** [comment]
"I broke my grille-mounted chemistry lab!"
size / weight being intrinsically connected makes me sad :(

**Comment by Oskar636** [comment]
Ramming a lot of spore clouds at 200 km/h with a sports car only damaged the headlights, which seems reasonable.
Build 5864 windows 64bit console

**Comment by Shoes01** [comment]
Given the effort to reduce the issue count, I will close this issue. I know there are a lot of changes happening to cars, so maybe this has become a non-issue anyway.

**Comment by codemime** [comment]
It would be very much appreciated if you could test the issue on the current `master` (or any of the latest builds).

**Comment by l29ah** [comment]
Reopen plz. Spore clouds have wrecked my car in the latest master.

**Comment by l29ah** [comment]
Should there be a size of DUST or something? I also find it interesting that i can beat spore clouds to death.

**Comment by l29ah** [comment]
```
        switch( critter->get_size() ) {
            case MS_TINY:    // Rodent
                mass2 = 1;
                break;
            case MS_SMALL:   // Half human
                mass2 = 41;
                break;
            default:
            case MS_MEDIUM:  // Human
                mass2 = 82;
                break;
            case MS_LARGE:   // Cow
                mass2 = 400;
                break;
            case MS_HUGE:     // TAAAANK
                mass2 = 1000;
                break;
        }
```
Why isn't `weight` that is specified in the JSON file used instead?

**Comment by kevingranade** [comment]
No good reason.
