### ISSUE TITLE
Build Failure on FreeBSD

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#12891]
In file included from src/pathfinding.cpp:1:
src/coordinates.h:42:27: error: use of undeclared identifier 'abs'
        const int normx = abs(absx);
                          ^
src/coordinates.h:43:27: error: use of undeclared identifier 'abs'
        const int normy = abs(absy);

FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.1
Thread model: posix

**Comment by drbig** [comment]
@mugling Checkout https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING.md - PRs for the BSDs section are most welcome.
