### ISSUE TITLE
Tailoring zero encumbrance head items when worn

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12897]
Tailor kit has an interesting bug, when you wear multiple zero enc head items you can upgrade them using tailoring to wear more on your head slot than normally possible. (this does increase the enc, but that does not matter on your head, so it does apply to other slots as well, but it is less relevant).

For example, wearing an heavy survivor helmet, and a beret and a cotton hat is possible. And then you can upgrade the beret and hat with kevlar. So you have increased protection. If you then take off the upgraded gear you cannot put it back on, as the enc is to high.

This allows you to cheat better head protection.
##

**Comment by StephenV25** [comment]
It might be a idea to require the player to remove clothing that they want to upgrade, it would be hard to reinforce a backpack with kevlar while wearing it irl.

**Comment by i2amroy** [comment]
Probably the best solution there.

**Comment by DeNarr** [comment]
@StephenV25 That sounds like it would add a large annoyance factor to the game though. I only ever modify the clothes I am wearing, as those are the clothes I care about. I assume the process abstracts the fact that it is being taken off and putting it back on, so that I don't have to manually do so.

**Comment by Soyweiser** [comment]
Not large imho, as you don't upgrade that many clothes. As long as repairing clothing does not require you to take them off it would not be a huge problem.

**Comment by Coolthulhu** [comment]
Could be special cased for helmets. Other clothes don't have an encumbrance limit.

Or a more complex solution: when generating list of modifications, create a temporary copy of player character, take off the item to be modified and try to put on a modified copy. If that fails, refuse to allow that modification.
Similar thing is already done for some inventory-related operation. I forgot which, but I'm sure that it makes a temporary copy of the player character.

**Comment by i2amroy** [comment]
Simple, if the player is wearing it just make them automatically take it off, then tailor it, and then put it back on. Easy peasy (though that might mess with layering just a tiny bit if that's like super important to you).

**Comment by DavidKeaton** [comment]
If you store where in the `worn` vector it came from it'd be easy. Hell you could just make a copy of the item, make changes, then overwrite the old item in the vector.

**Comment by Oskar636** [comment]
This issue works really strange. With the kevlar plated beret and cotton hat and heavy survivor helmet, take off the survivor helmet and you cannot wear it again. Take off either the beret or the cotton hat and you can simply wear it. There is also an inconsistency in checking for maximum encumberance on the head. The same also works with a kevlar padded heavy survivor helmet.

**Comment by Night-Pryanik** [comment]
I believe this was resolved in #23089. You can't wear survivor helmet, cotton hat and beret at the same time no more.
If you wear any other zero encumbrance headgear, for example, survivor helmet, cotton hat and knit hat at the same time, and then reinforce both hats with kevlar, you can take them off and then wear it again with no problems.
