### ISSUE TITLE
Build Error - item_location.cpp - Linux

### ISSUE THREAD

**Issue by phantom-voltage** [CleverRaven/Cataclysm-DDA#12899]
I have an error building the latest from github. Problem occurs in compiling item_location.cpp. Compiling on Debian 7 Wheezy. Compiled with release and no tiles. There seems to be no difference if compiling with the release flag and tiles=0 flag.

**Compiler Version:** g++ (Debian 4.7.2-5) 4.7.2
**CDDA Build**: VERSION "0.C-4396-g492cde8"

g++  -DLOCALIZE -ffast-math -Wall -Wextra -g -D_GLIBCXX_DEBUG  --std=c++11 -MMD -I/usr/include/ncursesw -c src/item_location.cpp -o obj/item_location.o
src/item_location.cpp:45:22: error: looser throw specifier for ‘virtual item_location::item_on_map::~item_on_map()’
src/item_location.cpp:17:13: error:   overriding ‘virtual item_location::impl::~impl() noexcept (true)’
src/item_location.cpp:168:22: error: looser throw specifier for ‘virtual item_location::item_on_vehicle::~item_on_vehicle()’
src/item_location.cpp:17:13: error:   overriding ‘virtual item_location::impl::~impl() noexcept (true)’
make: *** [obj/item_location.o] Error 1

**Comment by karlnp** [comment]
If I wasn't already all about unit testing & modularization, these persistent build errors would be a good argument for it. (puts nose to grindstone)

**Comment by drbig** [comment]
@phantom-voltage Remember to post your cdda version (commitish or Jenkins build number) and your `compiler --version`. Things move fast around here!

**Comment by phantom-voltage** [comment]
@drbig 
Thank you, I forgot about that. I updated my comment to provide the requested information.

**Comment by drbig** [comment]
@phantom-voltage aye. and I can tell you now: try gcc 4.8.x at the least. Also checkout https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING.md

**Comment by BevapDin** [comment]
> If I wasn't already all about unit testing & modularization, these persistent build errors would be a good argument for it. (puts nose to grindstone)

This error does not happen with a current version of gcc, to catch errors like this you would need to compile every PR with every compiler and every version of it.

**Comment by narc0tiq** [comment]
Correct. This is why the automated Jenkins builds for PRs only use the most
sensitive compiler we're aware of, which is clang -- most of the time, it
complains about things the others don't. It is rarer (but not impossible)
to have it pass on something that gcc chokes on.

The other guard we have are the actual on-push builds, which do use a
variety of compilers: clang, gcc-4.7.3, and gcc-4.8.whatever. Those rely on
people actually checking the build results after pushing, rather than being
proactive, but it's the best combination of completeness and speed we can
do.

**Comment by karlnp** [comment]
Fair enough - it was meant to be a general comment about automated testing, not a specific critique, but I am glad that it hasn't gone unconsidered. :)

**Comment by narc0tiq** [comment]
It's all good, I very much approve of automated testing -- anything you can do to make that easier is good.

**Comment by phantom-voltage** [comment]
Thank you for the help everyone. I updated my compiler and everything worked fine. Thank you.
