### ISSUE TITLE
Fit over sunglasses no longer fit over regular glasses

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#12904]
Presumably because of something in the recent layering/encumbrance changes.

A character with both regular eyeglasses and fit over sunglasses has 10 eye encumbrance. Both items are listed as on the normal layer.

An obvious fix would be to make the sunglasses outer layer, but not sure if that would clash with other items.

**Comment by tyrael93** [comment]
It doesn't, i edited the .json a while ago to do just that. Should be an easy fix.

**Comment by drbig** [comment]
@tyrael93 PR a bugfix then? :)

**Comment by tyrael93** [comment]
I'd love to, but not this month. I only have my phone nearby.
