### ISSUE TITLE
Upgrading system causes fungaloids to spawn fungloids on death.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12909]
I'm assuming the spores upgrade into fungaloids, but this means the fungaloids spawn fungaloids on death. Which makes it a bit hard to deal with a fungal infestation.

Currently in day 51 autumn of a spring start with 90 day long seasons, and a monster halflife factor of 2.

**Comment by drbig** [comment]
How does upgrades do anything to spawns on death?

**Comment by Soyweiser** [comment]
No idea. But fungaloids no longer spawn spores on death. Just full blown fungaloids. (So fungaloids are unkillable).

**Comment by drbig** [comment]
Indeed. After long enough period the on-death-spawned spore cloud will approach ~97% chance to upgrade to a fungaloid on spawn. I think an easy fix would be to add at least a half-life to `upgrade_time`.

**Comment by Soyweiser** [comment]
Seems that the upgrade system needs some sort of 'spawned at time X'  system just like various foodstuffs have for spoiling. imho.

**Comment by drbig** [comment]
> Seems that the upgrade system needs some sort of 'spawned at time X' system just like various foodstuffs have for spoiling.

That's actually super easily doable and would fix the issue here (and all of this class), but it would mess with the "monsters upgrade while you're not looking", e.g. if after a year at one place you move out to a new area you would again start with fresh mundane zombies there, instead of upgraded ones.

In any case your point belongs to upgrades discussion at #12313.

**Comment by Coolthulhu** [comment]
We could have summoned monsters get their "upgrades from" time set to current turn instead of `calendar::start`.

**Comment by i2amroy** [comment]
>We could have summoned monsters get their "upgrades from" time set to current turn instead of calendar::start.

Yeah, I was almost positive that that's what the older system already did for summoned monsters; maybe it accidentally got rolled back at some point during the fixes.

**Comment by drbig** [comment]
I'm working on that, and the functionality is exactly like that.
