### ISSUE TITLE
[Feature request] Make a debug function that deletes items.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12908]
We have an option to spawn items, but no way of removing items reliably. It would be great if we could remove them using a debug item. Perhaps a simple "remove all items from a square" option, that allows you to target a square and remove everything.

Edit: http://smf.cataclysmdda.com/index.php?topic=10688.0 (posted link to this issue here).

**Comment by Coolthulhu** [comment]
Could be also integrated with the editmap edit items on square option. Currently editmap allows only editing items on a single square, doesn't allow wishing quantities, deleting items, displaying items from multiple squares etc.

**Comment by kevingranade** [comment]
I'm sceptical that this is needed for debugging.

**Comment by Soyweiser** [comment]
Of course it isn't really needed for debugging, but it could help people to do whatever they want in this sandbox of ours. I have seen the request pop up before.

**Comment by Darkyhard** [comment]
Well, you can just create an acid field on the pile of items you want to remove.

**Comment by BevapDin** [comment]
Use the Lua debug console (in the debug menu) and enter `map:i_clear(player:pos())`, I have used this quite often and it works fine (it removes the items on the location of the player). Of course you can use specific points just as well: `map:i_clear(tripoint(1,2,3))`.

**Comment by Coolthulhu** [comment]
Would it be possible to have bindable Lua "macros"? Could be useful for some debugging cases.

**Comment by BevapDin** [comment]
> Would it be possible to have bindable Lua "macros"? Could be useful for some debugging cases.

You mean with configurable key bindings accessible from withing the main game environment? That would require some code with the main input context. Add an action and let it trigger some Lua code. But I think it's not that much useful. Calling the debug menu is one key press (I mapped it to `Q`), selecting Lua is another (`n`), pressing the up-arrow to get the least recently entered string and press enter twice.

The Lua console stores the last few entered strings (like the filter menu in "list items around you" view), you can press the up-key to access them.

Alternatively, you can put big function in data/json/main.lua or data/json/preload.lua, they can be called from the debug console.

**Comment by kevingranade** [comment]
Useful or not, it's a debug menu, not a "cheat" menu or "convenience" menu, cluttering it up with cheat options sets a bad precedent.

**Comment by Soyweiser** [comment]
Well, as you can use the Lua commands to already do this, you don't really need it. So, don't go implementing this.  Not closing the issue right now as I have some more questions.

Is there a Lua guide for CDDA? Or something like that? I sadly don't have a lot of Lua experience. Probably I should do something about that. So I have no idea what the capabilities of Lua are.

**Comment by BevapDin** [comment]
> Is there a Lua guide for CDDA? Or something like that? I sadly don't have a lot of Lua experience. Probably I should do something about that. So I have no idea what the capabilities of Lua are.

What do you need? Programming in Lua (http://www.lua.org/pil/contents.html) should give you enough information to understand the syntax, and there is doc/LUA_SUPPORT.md.

**Comment by Soyweiser** [comment]
Well, was thinking that for players it might be usefull to have some of the more requested commands listed somewhere.

But for myself, reading those will be enough.

**Comment by Barhandar** [comment]
Debug in a lava tile (which is currently only terrain with DESTROY_ITEM), drop items on it, remove lava tile.
