### ISSUE TITLE
Restaurant map reveals abandoned barns.

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#12912]
The `oter_id` of the abandoned barn is `barn_aban1`, which matches the entry `"bar"` from the `"terrain"` array at [data/json/items/tools.json:1561](https://github.com/CleverRaven/Cataclysm-DDA/blob/938936254625f30471c9788657f7c4252459c7b5/data/json/items/tools.json#L1561).

The rationale for allowing partial matches is undoubtedly to allow for the variations like `bar_north` and such that the overmap automatically creates for the rotated versions of buildings, so we want to keep that... but we should really make sure a partial match *is* actually a variation of this type.

The relevant location to change is [src/overmap.cpp:168](https://github.com/CleverRaven/Cataclysm-DDA/blob/938936254625f30471c9788657f7c4252459c7b5/src/overmap.cpp#L168), and the proper fix is most likely to ensure that if we have a match, it's either the entire string, or it has an `_` after it. I didn't feel like wrestling with `std::string`, or I'd've done it myself.

**Comment by BevapDin** [comment]
You probably want to check for the `omter::id_base`, that is the id string as it was read from json (before adding the `_north` etc. suffixes), it should be matched exactly against the requested string.

**Comment by narc0tiq** [comment]
Let me guess, the various rotations of roads are their own base terrain? I could see fixing that as being something useful...

**Comment by BevapDin** [comment]
> Let me guess, the various rotations of roads are their own base terrain?

Yes, but it's the same with houses and other stuff that has different symbols depending on the rotation. But there is also `road_end`, which also rotates and gives `road_end_north` and so on. `is_ot_type("road"` would succeed on normal roads and on `road_end`.

There are probably similar problems with other terrains.

**Comment by narc0tiq** [comment]
Right, so, check for trailing underscore if you have a partial match. That
should be pretty reliable.
