### ISSUE TITLE
Resilient mutation seems unobtainable.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12924]
The Resilient mutation:

        "type" : "mutation",
        "id" : "MUT_TOUGH",
        "name" : "Resilient",
        "points" : 3,
        "description" : "You can survive injuries that would incapacitate humans: you get a 20% bonus to all hit points.  Stacks with Tough, etc.",
        "prereqs" : ["LARGE_OK", "HUGE_OK", "STR_UP_3", "STR_UP_4", "MASOCHIST_MED"],
        "threshreq" : ["THRESH_URSINE", "THRESH_CATTLE", "THRESH_CHIMERA", "THRESH_MEDICAL", "THRESH_LIZARD", "THRESH_BEAST"],
        "cancels" : ["FLIMSY", "FLIMSY2", "FLIMSY3", "GLASSJAW"],
        "changes_to" : ["MUT_TOUGH2"],
        "category" : ["MUTCAT_URSINE", "MUTCAT_CATTLE", "MUTCAT_CHIMERA","MUTCAT_BEAST", "MUTCAT_LIZARD"]

Has as a prereq : masochist_med which is medical only, HUGE_OK, which is part of cattle/ursine (but not part of the threshold), LARGE_OK (which is part of the "THRESH_URSINE", "THRESH_CATTLE", "THRESH_LIZARD" line). Etc
The category does not include medical.

So is this mutation even obtainable? Or do you need one of the the prereqs? And not all of them?

(If you only need one, the missing MUTCAT_MEDICAL is still a bug).

**Comment by i2amroy** [comment]
IIRC the current prereq system works as an OR, not an AND. Mutations with multiple requirements (right now we support up to 2 + 1 threshold requirement) do it by having a "prereq":[X], "prereq2":[Y], "threshold":[Z].

**Comment by drbig** [comment]
@Soyweiser does that make it confirmed? (Remember to debug replicate it.)

**Comment by i2amroy** [comment]
No, that should make it invalid. :P You should be able to obtain the resilient mutation by having either LARGE_OK or HUGE_OK or STR_UP_3 or STR_UP_4 or MASOCHIST_MED, as well as having broken through either THRESH_URSINE or THRESH_CATTLE or THRESH_CHIMERA or THRESH_MEDICAL or THRESH_LIZARD or THRESH_BEAST. Realistically it should be one of the easier mutations to obtain because it's got so many different paths leading to it.

**Comment by drbig** [comment]
@Soyweiser Fix the missing MUTCAT_MEDICAL, please? :D

**Comment by Soyweiser** [comment]
i2amroy thanks for clearing it up. (and rivet for fixing it).
