### ISSUE TITLE
Hallucinations can cause acid puddles.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12931]
reported on the forum by Dlightfull
"When hitting a hallucination acidic zombie (spiter, corrosive etc.) the acid (which should only be a hallucination too) actually spills and damages items on the ground."

http://smf.cataclysmdda.com/index.php?topic=10745.0

Not confirmed.

Another thing that hallucinations can do is grab you. Encountered this myself.

**Comment by drbig** [comment]
My feeling is that there will be special attacks and/or other effects that don't check if the source mob is a hallucination.
