### ISSUE TITLE
Conflict with thermal eletric outfit and anbc suit

### ISSUE THREAD

**Issue by Eldhelion** [CleverRaven/Cataclysm-DDA#12938]
I don't know the system well enough to affirme that is a bug, 
but I have a thermal  eletrict outfit suit (fit) that says (Layer: close to skin)
and an ANBC suit (fit) with (layer: outer) but I can't wear both, when I try the error: "you cannot wear another helmet" pops up
##

**Comment by Night-Pryanik** [comment]
This is not about layers. Look at "Covers:" section. Both suits cover you from head to toe, so you cannot put on two helmets that are part of suits.

**Comment by Eldhelion** [comment]
Well, this is odd to me, because as is, you are saying to me that I cannot wear socks and tennis, because they use my feet ( what is false)
I can't use 2 pair of socks, this make sense to me, as they use the same layer.

Limit what can be wear by layer make more sense than just "body slots" that only work for certain body parts

I want to play with the frozen king (http://www.buzzfeed.com/davidmack/could-i-be-wearing-any-more-clothes#.xnRP2bXrYm)

**Comment by drbig** [comment]
The helmet limit is mostly sound, e.g. wearing an army helmet on top of a firefighter helmet is implausible. How this relates to cover-all suits is another matter though, e.g. a [cleansuit](http://i.kinja-img.com/gawker-media/image/upload/s--OxigP9Ei--/186pg9e5rczxcjpg.jpg) shouldn't really block wearing any kind of helmet on top of it (but obviously not the other way around).

Seems to me implementing well-working slots+layering system is a lot of work, both on the code part and the items part (seen only one game where it was done right).

**Comment by drbig** [comment]
Also related to #12741.

**Comment by Shadefang** [comment]
Just a thought here. What if you modified the current layering system? Make sure all the interfering helmets are listed as standard layer, so you can have stuff under them (helmet liner, skintight) or over them (rain hood/hazmat suit, outer layer) and prevent wearing anything on the head that causes layering penalties.

**Comment by DavidKeaton** [comment]
Perhaps a `HELMET` flag is necessary to keep the helmet issue to keep surfacing.

**Comment by Leland** [comment]
Looks like this has been stalled for years. Closing.
