### ISSUE TITLE
Crash when starting new game using Play Now! option

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#12947]
Since #12790 the window is nil for Play Now games.

**Comment by BevapDin** [comment]
Would you mind telling what build you use? Window/Linux/Whatever and tiles or curses?

**Comment by i2amroy** [comment]
Likely related to #12945 in some way as well.

**Comment by macrosblackd** [comment]
Same commit, but this is in new_character logic.

@BevapDin I built it on linux tiles

**Comment by karlnp** [comment]
Same here - WIndows 7/MINGW64/curses.
