### ISSUE TITLE
Should dissectors harm robots?

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12943]
Currently with the new explosions certain lab endings are quickly emptied because the dissectors cause the robots to explode. (That explosions cause to much damage to items, and not enough to people is a known issue I'm assuming).

I would suggest to implement that dissectors don't harm robots anymore. (This also fixes the badly placed broken cyborg who constantly wanders into the dissector).
##

**Comment by drbig** [comment]
> That explosions cause to much damage to items, and not enough to people is a known issue I'm assuming

Didn't know that.

I'm tagging it as a bug as it seems this is part of the explosions rework/enhancements.

**Comment by drbig** [comment]
Related to #12735.

**Comment by DeNarr** [comment]
@Soyweiser I've never seen a broken cyborg that wasn't on a dissector. I always thought it was a bait for the trap (people would want to cut up the cyborg), as well as a story for what the body was doing there. I didn't realize they were actually supposed to be alive.

Side note, I really want to be able to disarm dissectors. No matter how high I get my trapping, it still tells me that I should leave it alone. Well stop telling me what I should do game! I want to disassemble it dammit.

**Comment by Soyweiser** [comment]
Yeah the broken cyborgs are meant to be alive. Placing next to dissectors was a mistake on my part. They even have custom parrot lines.
