### ISSUE TITLE
Using EMP CBM on turret does not count as a kill

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12944]
Minor bug, but if you EMP a turret with the CBM implant it does not count as a kill.
##

**Comment by BevapDin** [comment]
Well, the robot reverts to the "bot_*" item and can be activated again. It's technically not a kill. But that brings up another ting: should killing revived zombies count as kill?

**Comment by drbig** [comment]
> Well, the robot reverts to the "bot_*" item and can be activated again. It's technically not a kill.

Indeed. EMP here is more of a 'disabling' than 'blowing up'.

> should killing revived zombies count as kill?

No idea on that one...

**Comment by kevingranade** [comment]
My understanding is the stat is more about your actions than the impact on
the game world, so both cases should count as a kill.

**Comment by Soyweiser** [comment]
The bot reverts only one 4 times or something. The other times it just explodes.

The reviving Z's thing is interesting. Should we stop people from 'kill list' farming? Would people mind if revived Z's get counted? What if a NPC kills the Z and you kill it again later?

**Comment by narc0tiq** [comment]
I don't expect killing a revived zombie brute to be any easier than killing
the brute in the first place, so... I see no problem with counting rezzed
zombie kills.

**Comment by Soyweiser** [comment]
They do have lower HP iirc.

**Comment by narc0tiq** [comment]
If true, I imagine that would be proportional to the damage their corpse
took. That might be okay for a different reason -- it might limit the
number of times you can re-kill the same zombie.

**Comment by Leland** [comment]
Closing - old and no movement. Feel free to ping me here if there's still interest, or make a new issue.
