### ISSUE TITLE
Tiles builds on NetBSD/amd64 7.0RC1 segfault, and even make gdb segfault

### ISSUE THREAD

**Issue by oldlaptop** [CleverRaven/Cataclysm-DDA#12950]
I don't know how to expand on the title, really. Not only do tiles builds segfault immediately:
```
$ ./cataclysm-tiles
Segmentation fault (core dumped)
$
```
but gdb even segfaults when trying to load their debug symbols!
```
$ gdb cataclysm-tiles
GNU gdb (GDB) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64--netbsd".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from cataclysm-tiles...Segmentation fault (core dumped)
$
```
Both these bugs seem 100% reproducible to me. It is possibly relevant that I'm doing this testing in a PV xen domU, and that the system was upgraded from 6.1.5 (plus patches). Further information may be forthcoming if I ever get around to setting up a clean VM (or a clean install on bare metal).

**Comment by drbig** [comment]
Which version exactly? Is this the same thing as #12945? (that would probably be very useful).

**Comment by oldlaptop** [comment]
The last revision I built on netbsd was a1dfe6d23ea397753ac1440f90330d19805921a8. I doubt 12945 is closely related, but it is interesting that there are other reports of catacylsm crashing gdb.

**Comment by drbig** [comment]
Given you get a segfault before (presumably) anything showing at all this is something new... Or maybe #12948? Weird coincidence though. Try latest, check curses build?

**Comment by oldlaptop** [comment]
Hm. An ncurses build from 83338828c1f1f4e4c8f8883fae6ebe30292c00ab segfaults on *starting* a game for me. Tiles build in an hour or so...

**Comment by BevapDin** [comment]
> Reading symbols from cataclysm-tiles...Segmentation fault (core dumped)

That looks like `gdb` crashes, and is therefor not directly related to cataclysm. The binary may just have triggered a bug in `gdb`. The current gdb version is 7.9.1, maybe you could debug the debugger? \*insert obscure reference to meme\*

`gdb --args gdb ./cataclysm` - it actually works.

**Comment by mugling** [comment]
@oldlaptop is this still a problem for you?

**Comment by mugling** [comment]
Presumably not

**Comment by oldlaptop** [comment]
Sorry, would you believe the spam filter ate this? :| I'll start a build now and let it run overnight, see what happens.

**Comment by oldlaptop** [comment]
With current git, I still get a crash, but I was able to get a backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007f7ff740d26e in getframeaddr () from /usr/pkg/lib/libexecinfo.so.1
(gdb) bt
#0  0x00007f7ff740d26e in getframeaddr () from /usr/pkg/lib/libexecinfo.so.1
#1  0x00007f7ff7400939 in backtrace () from /usr/pkg/lib/libexecinfo.so.1
#2  0x00000000007f3257 in DebugLog (lev=lev@entry=D_ERROR, cl=cl@entry=DC_ALL) at src/debug.cpp:323
#3  0x0000000000469bdf in color_manager::name_to_id (this=this@entry=0x130e560 <get_all_colors()::single_instance>, name=...) at src/color.cpp:81
#4  0x000000000046a829 in color_manager::highlight_from_names (this=this@entry=0x130e560 <get_all_colors()::single_instance>, name=..., bg_name=...) at src/color.cpp:192
#5  0x000000000046b830 in color_manager::finalize (this=this@entry=0x130e560 <get_all_colors()::single_instance>) at src/color.cpp:64
#6  0x000000000046bcc9 in color_manager::load_custom (this=0x130e560 <get_all_colors()::single_instance>, sPath=...) at src/color.cpp:943
#7  0x000000000047110f in init_colors () at src/color.cpp:443
#8  0x0000000000b5f1bb in main (argc=0, argv=0x7f7fffffdb30) at src/main.cpp:375
(gdb) q
```
This isn't the first trouble I've seen with the backtrace libraries on !linux. Discussion seems more appropriate in a new issue.
