### ISSUE TITLE
Nailboard Trap Pickup

### ISSUE THREAD

**Issue by nrfowler** [CleverRaven/Cataclysm-DDA#12957]
When you examine "e" a square that contains an active nailboard trap, it takes you to the Pick Up screen. If you select items and press enter, the Pick Up screen exits and you are left with a window that says "Disable Nailboard Trap?" If you choose yes, the Pick Up window is returned, but the items you selected are no longer selected, so you have to select them again.

**Comment by drbig** [comment]
So you're saying you didn't pick up the stuff you selected within the first pick up menu?

The reason for the second pick up menu is to make it easy for you immediately pick up the disabled trap.

**Comment by nrfowler** [comment]
Yes, you don't pick up the stuff that you selected in the first pick up menu if you chose to disable the nailboard trap. If you don't disable the trap you do pick up the items.

**Comment by karlnp** [comment]
@nrfowler - what platform is this on?

**Comment by nrfowler** [comment]
Windows
