### ISSUE TITLE
Zombie Scientist shock attack message without LOS to monsters

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#12958]
In a lab start, somewhere nearby a zombie scientist is fighting a skitterbot.

I get occasional messages of "The zombie scientist shocks the skitterbot" even though I don't have line of sight (and haven't even gone through the door where I think they are).

Linux, tiles, build today - let me know if you need info on mods or a save to replicate it.

**Comment by Soyweiser** [comment]
Can confirm this. This kind of stuff happend a lot in labs.

**Comment by karlnp** [comment]
This happens with chicken walkers as well.

**Comment by romkuma** [comment]
Did a little searching. The issue is these monsters use the code for tazers, which doesn't check for LOS.

The message is on line 2760 of monattack.cpp; line 2751 is the equivalent for NPCs.

I assume it needs something like line 42 of mondefense.cpp - this looks like a check for LOS.
