### ISSUE TITLE
Run key can't be found in the menus or anywhere

### ISSUE THREAD

**Issue by i2amroy** [CleverRaven/Cataclysm-DDA#12967]
As title, run key can't be rebound and isn't visible in any of the menus at all.

**Comment by Rivet-the-Zombie** [comment]
![run](https://cloud.githubusercontent.com/assets/5084581/8742971/4fc529ba-2c30-11e5-849e-cf050718b9ae.png)

**Comment by i2amroy** [comment]
Oh lol, for some reason my eyes skipped right over that... all three times I went through the menu looking for it. XD Closing this.
