### ISSUE TITLE
26% at git clone and 250Mb already?

### ISSUE THREAD

**Issue by szopin** [CleverRaven/Cataclysm-DDA#12963]
Is the repo full of garbage files, or is this really AAA sized game?

**Comment by Coolthulhu** [comment]
The game part of the repo is 100 mb, `.git` directory is 440 mb.
I guess it's all the logs and diffs that take up space.

**Comment by szopin** [comment]
100mb source? Neat (sorry, trying to compile this on device (jolla), and last time had 37 mb .cpp file it did not go well, thanks)

**Comment by Coolthulhu** [comment]
Sources are <10 mb, it's mostly translation data and graphics.

**Comment by szopin** [comment]
Oh, ok, thank you. Going for the ascii only mode for now (glad to see no errors/warnings just like in Whales times), keep up the good work guys!

**Comment by BevapDin** [comment]
If you clone the repo, you get *all* the previous commits (versions) right to the very first commit and all in between. That sums up.

If you don't care about the old commits, you can use the `--depth <depth>` parameter for `git clone`.

`git clone --depth 1 https://github.com/CleverRaven/Cataclysm-DDA.git` gives a directory containing only 128 MB (based on 31 MB downloaded data).

**Comment by szopin** [comment]
Wow, thank you very much! Usually just trying to get the latest, that will be handy. Any chance you guys can provide also ARM build? We used to have latest recompiles for maemo on tmo, working on one for Jolla atm, having official arm build like adom or frozen depths would make this unnecessary

**Comment by szopin** [comment]
btw should this look like that?
http://i.imgur.com/IbDjNoK.png

**Comment by karlnp** [comment]
We're trying to get the current architectures to be rock-solid first, but it could definitely happen in the future.

**Comment by szopin** [comment]
120MB for an executable is wow, but runs, thanks guys! (I hope all those qqqqq are ok, would assume they would be -----)

**Comment by Coolthulhu** [comment]
Executable itself should be 10 mb. Make sure you're compiling the release build, otherwise you get the huge and slow debug build which is quite useless for an end user.

**Comment by szopin** [comment]
Oh pok, got 120 MB binary, phew. 'make release'?

**Comment by karlnp** [comment]
Those q's look like a character set problem, but it should be playable? I'm not sure if ARM devices are supported, to be honest.

**Comment by szopin** [comment]
It is playable, just like original cata, jolla runs proper libc linux, no bionic, just git clone/make used to be enough. Just not sure how to fix those q's, are those some ANSI characters?

**Comment by kevingranade** [comment]
You probably want 'make RELEASE=1'.  The debug build turns on a debugging
mode for std:: containers, which makes it super slow.
I have to brag a little, whales' version was not -Wall clean, it suppressed
a bunch of classes of warnings, we've actually addressed them all.
ARM builds shouldn't be a problem, the build takes a ton of ram but the
game itself doesn't, we just don't have tooling set up for it.
As for the character thing, the only thing that comes to mind is gettext
interfering somehow.

**Comment by BevapDin** [comment]
> Just not sure how to fix those q's, are those some ANSI characters?

They are supposed to be Unicode line-drawing characters https://en.wikipedia.org/wiki/Box-drawing_character#Unicode - your system seems to have problems with UTF-8?

**Comment by szopin** [comment]
@kevingranade thanks, managed to build/run both debug and release oin jolla, just bit of rendering problems in its default term

@BevapDin thanks, will have a look what exactly is going on there
