### ISSUE TITLE
Unable to craft a recipe from a book without meeting the memorization skill requirements

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#12977]
The recipe that shows this issue clearest is the atomic coffee maker -- the recipe itself requires electronics 4, but the memorization requirement is electronics 8 (which makes sense, as per @Rivet-the-Zombie -- it's hard to memorize, but not quite as hard to use).

Unfortunately, even if one has the Rivtech design binder, one cannot craft the atomic coffee maker until they reach electronics skill level 8, which is to say, the memorization requirement. This seems to go against the intent of being able to use recipes from books (i.e. without memorizing).

Being this would be a mechanics change, I've tagged the issue appropriately. Any comments?

**Comment by karlnp** [comment]
Seems unintended, and if intended, I can't see the rationalization behind it.

**Comment by narc0tiq** [comment]
Most certainly unintended, but not really noticeable for most recipes, I think. It may be feasible to just revisit a few of them.

**Comment by Headjack** [comment]
I had the same thing happen with some lower end chem recipes. I don't know what numbers were in play with the old system and success chance, but I think this is worth amending closer to the old functionality.
