### ISSUE TITLE
Black Box Lighting bug

### ISSUE THREAD

**Issue by DodgingRain** [CleverRaven/Cataclysm-DDA#12970]
When stepping outside, sometimes the lighting suddenly become inverted that I see a lot of things outside my night vision but almost nothing at a direction within my normal night vision.

![untitled](https://cloud.githubusercontent.com/assets/13143681/8750046/d78578de-2c6a-11e5-842d-03fea5fce013.png)

Save file:
https://mega.nz/#!TIp1GRSB!e71zMvK8Y-gLnNc_Q2cyh1q2_K4jbLKM0UvuBADrn7E

**Comment by Soyweiser** [comment]
Thanks for providing a save!

**Comment by drbig** [comment]
This sounds familiar... perhaps the new lighting/nv code broke something in the case of lightning?

@DodgingRain Please report the version you're using here.

**Comment by DodgingRain** [comment]
Experimental 3427

**Comment by narc0tiq** [comment]
It's definitely something that came in from b0456746b4b4495222f1f7dba2d35b547324bafd -- two `git bisect`s can't be wrong. Unfortunately, I can't tell what's wrong.

**Comment by i2amroy** [comment]
Might be some tiny logical error in the code somewhere that's backlashing against us. I'll go over this with a fine-toothed comb sometime today to see if I can pin down exactly what's happening here.
