### ISSUE TITLE
Vehicle stuck on fungal bed, self-destructing.

### ISSUE THREAD

**Issue by Salganos** [CleverRaven/Cataclysm-DDA#12982]
I've gotten a slightly large motorcycle completely stuck in some fungal beds (it was night, I could see far enough that I didn't turn on headlights, so it was effectively invisible), with seemingly no way of getting it out.  I'd use fire, but this is not good for the vehicle's health.  The gas tanks tend to explode.  I would think I should be able to cut it out, though there doesn't seem to be a way to do that.

Also, the vehicle begins to tear itself apart going nowhere if I try to drive out, even at the slowest target speed, while never moving.  This seems unreasonable, considering I've had accidental bumping fights with a large number of things, from vehicles to walls, and had little more than scratches, often winning outright against less alien vegetation like trees (which also seems unreasonable for fully grown trees).

Finally, should something with a movement penalty and vehicle obstruction look exactly like grass and dirt aside from colour?

(Version is Windows Tiles 0.C-3427 / 3f1c109 (was not using a tileset))

**Comment by Rivet-the-Zombie** [comment]
I don't feel like fungal beds should really be obstructing vehicles.; it's basically a carpet of mycelium.

**Comment by Soadreqm** [comment]
As a workaround, you can use a shovel to till the soil. Changing the terrain type kills the fungus.

**Comment by drbig** [comment]
Confirmed. It's so stupid it's funny :D

**Comment by Salganos** [comment]
I'll try tilling more.  I don't quite remember why I stopped.   >.>

**Comment by mightyagrippa** [comment]
If you till, make sure to use x to examine all the tiles your vehicle is occupying for fungal beds. Those need to be tilled too, which means deconstructing that square of the vehicle. Or use the debug menu to change the fungal beds to dirt.

**Comment by Salganos** [comment]
I was able to till under the vehicle without unbuilding any of it, so that's not an issue.
