### ISSUE TITLE
Burned down building not visible in natural light

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#12999]
Every tile of a completely burned down house appears black. I can see all the rubble/nails if I activate my flashlight, and I can see behind the burned down house either way, but I cannot see into it without artificial light.
##

**Comment by drbig** [comment]
@ejseto Version you're playing? Tiles/Curses? (read [ISSUES.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/ISSUES.md) please).

**Comment by ejseto** [comment]
Tiles/Windows, did a git pull/recompile right before that session.

**Comment by kevingranade** [comment]
Most likely the problem is floor/ceiling tiles not getting destroyed in the
fire, so the spaces are still marked 'inside'.

**Comment by karlnp** [comment]
Maybe there are pillars still holding it up?

**Comment by Oskar636** [comment]
Not exactly sure how to reproduce this, but nobody has cofirmed this in over a year.
