### ISSUE TITLE
Stairs in house can spawn in wall

### ISSUE THREAD

**Issue by greattuna** [CleverRaven/Cataclysm-DDA#13008]
One of my houses, despite map clearly saying that there is basement, did not have stairs on them. I then debug-ported to a basement of that house and took stairs up, only to end up in a wall.
Version is 0.C-3438-3aae1a0, tiles.
Sorry for the wording in title, I couldn't quite put it up.
##

**Comment by BevapDin** [comment]
> Stairs in house can spawn in wall

This is technically impossible, because stairs are a terrain type, as are walls and each tile on the map can have only *one* terrain type. Each tile is therefor either a wall *or* stairs or something else, but not several of those.

What probably (just guessing) happened: the game could not find the down stairs in the house and placed the character the same tile as it was in the basement (only strict vertical movement), that place happened to contain a wall.

**Comment by drbig** [comment]
Hmm, that means it doesn't actually count as a bug?

**Comment by karlnp** [comment]
Sounds like the down stairs not spawning is the real bug.

**Comment by BevapDin** [comment]
Yes, @karlnp has a good description. I look at mapgen_functionc.cpp, line 2586, the stairs are added after the house has been created, but it only does 20 tries to find a suitable location, and it requires a `t_floor` there. Some houses may not have `t_floor` at all.

**Comment by drbig** [comment]
Aye. How relevant is this given the proper Z-level handling?

**Comment by greattuna** [comment]
Yes, I checked it and it seems that game placed me on the same x-y coordinate as in basement.
Still, no downstairs spawning seem to be a bug.

**Comment by kevingranade** [comment]
Z-level aware stair spawning will have to overhaul the whole system, since
up/down stairs must match in 3D.

**Comment by Barhandar** [comment]
>Z-level aware stair spawning will have to overhaul the whole system, since up/down stairs must match in 3D.

Basements are going to look funny after this one. They'll have to be able to have entrance, doors and all, at arbitrary point.

The alternative is forcing all houses to have stairs only south-center, which I imagine won't look good.

**Comment by gimlet90210** [comment]
I've seen stairs in labs spawn under furniture once in a while - without moving the furniture there's no clue there's stairs there either, just the surprise when coming up/down a set of stairs and finding that it was under furniture.  At least once was in the barracks storeroom where I came out on top of one of the racks.

**Comment by Ramza13** [comment]
With all houses now being custom defined and no more random house spawning this issue should be fixed right?

**Comment by ZhilkinSerg** [comment]
Yeah, but we still need to do proper migration before 0.E for old houses.

**Comment by Ramza13** [comment]
Oh that makes sense, thanks.

**Comment by anothersimulacrum** [comment]
We're after 0.E, do we have that migration yet?

**Comment by ZhilkinSerg** [comment]
> We're after 0.E, do we have that migration yet?

https://github.com/CleverRaven/Cataclysm-DDA/pull/38988 maybe

**Comment by Night-Pryanik** [comment]
I guess such an old issue could be safely closed.
