### ISSUE TITLE
Using first aid kit on ground does not use charge

### ISSUE THREAD

**Issue by eliandarkbrood** [CleverRaven/Cataclysm-DDA#13020]
OS: Windows
Version: experimental 3446 (Curses)

Simply having a first aid kit on the ground and pressing Shift + E and using the first aid kit healed and gave an error as shown in the picture. Cant test in other OS's. Tested on 2 different files and still does it. If need be, I can upload the save, but it may take a bit.
![untitled](https://cloud.githubusercontent.com/assets/13456233/8833635/c4ec002e-30ea-11e5-8915-ab79708265e8.png)

**Comment by BevapDin** [comment]
Thanks for reporting, but this was already reported as #12991 and is fixed. Please try the latest version, it should be fixed there.

**Comment by narc0tiq** [comment]
It's definitely not the curses version -- you've got tiles showing. Also, it's not Jenkins build 3446, either -- I just downloaded the Windows Curses build 3446 from <http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Curses/cataclysmdda-0.C-3446.zip> and debug-spawned a first aid kit. I can't [E]at it from my inventory nor off the ground.

**Comment by drbig** [comment]
Already fixed by #13002.
