### ISSUE TITLE
DEBUG Spam

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#13049]
OS: Windows 7 64bit 
BUILD VERSION: a441f82
JENKINS VERSION: 0.C-3458 
GAME TYPE: Tiles

Getting many debug errors when playing latest build for windows experimental. - Tiles version
Got the below leaving a ambulance from the back. 
DEBUG: map::unboard_vehicle: passenger not found 

Also getting the below when getting hit by attacks. 
DEBUG: Wacky body part hit! 

Problem was not present in 0.C-3453

**Comment by karlnp** [comment]
I got the wacky body part thing too, when hitting bandits with a school bus.

**Comment by Treah** [comment]
Same problem on another platform. 

MAC OSX 10.10 
BUILD VERSION: Commit a44if82

**Comment by drbig** [comment]
> DEBUG: Wacky body part hit!

Sounds cool.

No idea what's the actual problem, but I assume it's a bug (leftover debug spam?)

**Comment by Treah** [comment]
Looks like this might be some of the code that Kevin was working on thats causing the problems. When you do a git checkout on commit 5a939ff1a9b3d7d85cd22ae0e4cba9cd168c65a6 you dont get any of the  errors. I just got a new one when going to his commit about monster is already on that tile. 

Going to this commit 5693215a2429959d100ed719922927404777c21e and you start getting errors with debug messages.

**Comment by Coolthulhu** [comment]
Wacky body part is from missing `break`, #13052 fixes it.

**Comment by Treah** [comment]
ill close my PR it does the same as #13052
