### ISSUE TITLE
Bats shadow cars?

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#13041]
Every time I drive past a big cloud of bats at a slow enough speed, they start flying behind my RV until i turn sharply enough that they can see me, then they run away. It's probably because they hear the engine and follow it, then see me and their avoidance behavior kicks in. Possibly other animals too? Bats might just be the ones who are fast enough to keep up. 

Funny, but strange enough to be unintended behavior.

**Comment by Coolthulhu** [comment]
Currently all monsters that can hear will be attracted to sounds, never repulsed by them, even when the sounds cause them to be afraid.

**Comment by Headjack** [comment]
So it's just a kludge or something? Ok, just wanted to make sure it's known.

**Comment by Coolthulhu** [comment]
More like an oversight that wasn't fixed yet.
