### ISSUE TITLE
Turning off Mobile Spawns in-game does not stop them

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#13044]
Made a world with Mobile Spawns, it's too nuts at this zombie ratio, tried to turn them off with >?>2 . They're still generating, even after restarting, even in areas newly explored. I checked and it definitely is set to 'false' now.

**Comment by BevapDin** [comment]
What is "Mobile Spawns"? if you meant "Wander spawns", you have to reset the world when you change this.

**Comment by Headjack** [comment]
Crap, yes I did. Very tired. Oh, well is there maybe some value that can be edited anywhere to stop them from generating?

**Comment by BevapDin** [comment]
> Oh, well is there maybe some value that can be edited anywhere to stop them from generating?

They are added when the world is generated. But because the world is created in chunks, you might get rid of them if you move *really* far - at least to another overmap, and that might not be enough.

If you feel lucky, you can edit the "save/worldname/o.x.y" files, remove the entries with GROUP_ZOMBIE or so (no guarantee).

**Comment by drbig** [comment]
> "Wander spawns", you have to reset the world when you change this.

If I understand correctly then this is like "Static spawn" that is changing it via the "?" in-game doesn't have any effect (i.e. one has to reset the world). If so then this should be explicitly stated in the option description (like it is for "Static spawn" already).

**Comment by kevingranade** [comment]
Yes, changing this setting during a game is not supported, at best you're going to get some weird mixed behavior.

**Comment by drbig** [comment]
Aye. Then it's an UI issues with an easy fix. Time to make a PR.
