### ISSUE TITLE
New explosion variations overpower molotovs

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#13050]
I understand that explosives have been reworked, and that's cool, but when I threw a molotov it had an area of effect the size of a smallish house. Honestly the old 9-tile square was already excessive, since molotovs really just deliver their flaming payload and aren't particularly concussive.

![image](https://cloud.githubusercontent.com/assets/6004660/8886798/1777552c-3236-11e5-821d-de7f760f78c2.png)

**Comment by greattuna** [comment]
Wait a minute. Did you throw the molotov in point-blank range? Then you could just as easily suspect the raging fire that molotov created under your feet.

Also, IIRC the explosions have huge radius, but are extremely weak at edges, and in non-tiles version this is shown by colours gradually degrading from red to... white. So your explosion is likely to just create flames and not damage anyone (because white is "extremely weak").

**Comment by Headjack** [comment]
I threw it pretty close, but my point is that even a weak explosion more than a tile or so away from point of impact is unbelievable. From the deathcam, there were small fires visible throughout the radius, which is hard to explain under the glass-containing-fuel model. Here's a demonstrative video https://www.youtube.com/watch?v=lfvceHUBWnU . Based on that, I think it would be realistic to classify molotovs as a non-explosive and just scale them back to a smaller fireball.

**Comment by Skidborg** [comment]
Yeah, it's been bouncing around the IRC channel that Molotovs have been made ridiculous in recent versions. Here's the fire field left by a single thrown molotov.  It is, indeed, as big as a house, and much less useful compared to the denser 3x3 fire left by previous versions.
![molotov](https://cloud.githubusercontent.com/assets/8848477/8888395/4f1c2956-3260-11e5-90b0-2cb2740521f3.png)

**Comment by tvm1** [comment]
This can be closed. 

Not sure when it was fixed, but there are normal 3x3 explosions for molotovs.

![screenshot from 2015-08-14 10 09 06](https://cloud.githubusercontent.com/assets/12072674/9269719/8b1e4684-426c-11e5-84df-fc9f23985656.png)
