### ISSUE TITLE
Soldering iron cannot be used to cauterize

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#13097]
The option is permanently greyed out, regardless of charge, Masochist trait, or a presence of bleeding/infected/festering wound. Welder and makeshift welder share the action, so presumably they have this issue as well. 

P.S. How exactly cauterizing using a _stone_ knife (which I've did for the bleed soldering failed on) works? I've an assumption that to do so the tool needs to have higher thermal conductivity than stone.

**Comment by drbig** [comment]
Stone knife indeed sounds like it shouldn't be usable for cauterizing.

My opinion: soldering iron has too small tip to be useful in either direct cauterization or heating; welders would definitely do as a heat source for heating up some metal knife to do cauterization with, but I don't think open-flame cauterization is a good idea, hence they shouldn't be directly applicable. Getting this to be realistic seems like overdoing it. Metal knife + heat source should be enough.

**Comment by Barhandar** [comment]
The intention of this issue was to report a bug that soldering iron's "cauterize" action is not accessible at the same time a knife's one is. Please do add the "bug" label.

>but I don't think open-flame cauterization is a good idea, hence they shouldn't be directly applicable.

Electricity doesn't run on open-flame and you can apply sufficient current to metal electrodes to _heat them up_ through their resistance. Still incredibly awkward due to their size, but should be possible alone. Maybe adjust chances in the action json and notify player that it would be harder/easier than normal, based on these probabilities, instead of outright not having the action.  

Also, soldering irons, while impractical for actual cautery, should be usable by masochists.

**Comment by drbig** [comment]
> The intention of this issue was to report a bug that soldering iron's "cauterize" action is not accessible

Confirmed. Will look into it.

**Comment by Coolthulhu** [comment]
That's a tiny bit of inverted logic in iuse_actor.cpp.

**Comment by drbig** [comment]
That, but then it seems there's a another bug with charges ;)
