### ISSUE TITLE
Corrosives spit over walls. Also, something weird.

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#13107]
So I found this unusual occurrence.

![image](https://cloud.githubusercontent.com/assets/6004660/8947010/7f8afbdc-355b-11e5-88b4-903d99144bba.png)

Which, to my knowledge of the spawn code, should be statistically impossible. That's the file on which I toggled off Mobile Spawns, so maybe this is the abnormal behavior I was warned about. 

Anyhow, while standing on the other side of a log wall from this mess, I was still getting hit with acid bolts, which seems unintentional. They were probably on the tile right next to the log wall, and I was on the other. I wonder if that would also happen for things like Hollow biting and Grappler grabs.

**Comment by drbig** [comment]
> That's the file on which I toggled off Mobile Spawns, so maybe this is the abnormal behavior I was warned about.

It certainly doesn't help in making this a "Confirmed Bug".

> Anyhow, while standing on the other side of a log wall from this mess, I was still getting hit with acid bolts, which seems unintentional.

Yeah, walls should be solid.

> I wonder if that would also happen for things like Hollow biting and Grappler grabs.

Debug spawn a couple on the other side of the wall and see for yourself :)

**Comment by Coolthulhu** [comment]
Corrosives should no longer be able to spit over walls.
