### ISSUE TITLE
Zombies breaking walls results in a lot more rubble and noise than it should

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#13105]
It takes about three messages in the log (out of 20 or 30) before message about deafening and it generates ~5x5 rubble zone. Combined with monster upgrading and advanced zombies being _very_ OHYEAH-happy, it makes things like hospitals or mansions non-viable after a few days in the game until very strong weapons are found or crafted.

Proposal: when regular "walls" are smashed down, check amount of adjacent walls. If 2, generate ~3 squares of rubble tops without much noise. If 1, check the opposite direction, generating more and more rubble depending on distance to a wall terrain, with highest on 5 tiles. Generate same rubble as if 2 walls if distance is 6 or higher. If 3, generate a LOT of rubble, pretending that the wall is load-bearing.

**Comment by i2amroy** [comment]
The problem is without meta-info about the map stored somewhere it is *very* difficult to get a good collapsing mechanic. Ideally at some point we should add a tiny bit of meta-information somewhere (a well used map combined with a bitfield would cost a pittance of space) which lets us record viable information about how different tiles are actually supported and would collapse without needing to do a huge number of calculations every time something breaks. The problem is just that their are a lot of different viable building designs, and lots of the time it's better to err on the side of bringing everything down than to have the player and zeds be able to smash all of the walls away leaving a magical floating roof (which used to happen very reliably).

**Comment by Coolthulhu** [comment]
This will probably get a bit better once floor-ceiling split is done.

**Comment by HeadWar** [comment]
Could we, no matter what else is decided, reduce the noise a bit? I recently started a game in a burning building, and ended up being deaf for the first few hours of the game.

**Comment by Barhandar** [comment]
From what I've gleaned, there's two parts to the issue:

1. The entire rubble-generation happens instantly for practical purposes.
2. Even _one_ rubble-generation event is enough to deafen, a.k.a does WAY TOO MUCH noise. 

The 1 follows from 2, because "Your ears ring!" happens immediately after first message about hearing a crash... but it's then followed by few dozen more "heard crash" messages.

**Comment by Barhandar** [comment]
Okay, now I've personally smashed a window and it _did_ generate rubble, which is I'm pretty sure unintended behavior and a bug, because I remember _window-smashing generating rubble_ being fixed. Also, it results in __400__ noise and a myriad of "You hear crash!" messages.

**Comment by i2amroy** [comment]
Were you smashing the window? Or the "window frame"? Smashing windows should never result in rubble if everything is working right. Smashing window frames, on the other hand, should potentially result in it (albeit only rarely if it's got two solid walls on either side of it).

And yeah, if it's generating 400 noise that's almost certainly too much.

**Comment by Skidborg** [comment]
The noise level definitely needs to be fixed.  Having worked at demolishing houses, wooden-framed buildings simply aren't very loud (or fast) when they fall down at all.  And unless any other building collapses completely and suddenly enough to create an eardrum-rupturing shockwave, it will be merely loud, not debilitating.

**Comment by adrianrieck** [comment]
Collapsing walls still result in deafness and the result is a player becomes deaf in the city far too often to be realistic. IRL it would only be major explosions that causes deafness. I guess it is complicated to fix this as you want to call in hordes with noise but maybe we could adjust the threshold for deafness itself then?

**Comment by adrianrieck** [comment]
The current problem seems to be the FREQUENCY of sounds generated when a roof collapse happens. 

For what it is worth I have been playing with a cap or limit on the deafness caused by noise stacking.  Perhaps someone may find it useful until the real issue has been properly addressed. Shotguns etc still make you deaf for the same amount of time but if 1000 shotguns get fired in one turn then it will stack limit at 10. Which is much more reasonable when a building roof collapse happens. 

```
diff --git a/src/sounds.cpp b/src/sounds.cpp
index 0cf1877..92d036c 100644
--- a/src/sounds.cpp
+++ b/src/sounds.cpp
@@ -189,6 +189,8 @@ void sounds::process_sound_markers( player *p )
     bool is_deaf = p->is_deaf();
     const float volume_multiplier = p->hearing_ability();
     const int weather_vol = weather_data( g->weather ).sound_attn;
+    int sound_counter = 0;
+
     for( const auto &sound_event_pair : sounds_since_last_turn ) {
         const int volume = sound_event_pair.second.volume * volume_multiplier;
         const std::string& sfx_id = sound_event_pair.second.id;
@@ -207,6 +209,8 @@ void sounds::process_sound_markers( player *p )
                 // Prolong deafness, but not as much as if it was freshly applied
                 int duration = std::min( 40, ( max_volume - dist - 130 ) / 8 );
                 p->add_effect( "deaf", duration );
+		p->add_msg_if_player( m_bad, _( "A: Your're deaf for %i!" ),duration );
+
                 if( !p->has_trait( "DEADENED" ) ) {
                     p->add_msg_if_player( m_bad, _( "Your eardrums suddenly ache!" ) );
                     if( p->pain < 10 ) {
@@ -225,7 +229,11 @@ void sounds::process_sound_markers( player *p )
         // Check for deafness
         if( !p->is_immune_effect( "deaf" ) && rng((max_volume - dist) / 2, (max_volume - dist)) >= 150 ) {
             int duration = (max_volume - dist - 130) / 4;
-            p->add_effect("deaf", duration);
+	    if (sound_counter % 10 == 0){	
+            	p->add_effect("deaf", duration);
+	    	p->add_msg_if_player( m_bad, _( "B: Your're deaf for %i!" ),duration );
+  	    }
+	    sound_counter++;
             if( p->is_deaf() ) {
                 // Need to check for actual deafness
                 is_deaf = true;
```

**Comment by Coolthulhu** [comment]
Scaling deafness severity with player's hearing ability could help.
Something like, 20% deafness increase if the player is deaf (but full pain boost), scaling linearly back to 100%.
