### ISSUE TITLE
Generic house generation

### ISSUE THREAD

**Issue by aparent** [CleverRaven/Cataclysm-DDA#13100]
Right now generic houses do not have much variety.  I looked around for some papers on procedural floor planes.

This one looks reasonably nice and not too bad to implement:
http://www.hindawi.com/journals/ijcgt/2010/624817/

This seems to generate amazing multi-floor planes but unless they have an open source implementation up somewhere it would be pretty difficult to use:
http://graphics.stanford.edu/~pmerrell/floorplan-final.pdf

If anyone knows of any other good and reasonably implementable algorithms please add them to this thread.  I will try to implement the best looking one from a complexity of algorithm vs. quality of generation standpoint.
##

**Comment by FireCrow1973** [comment]
I think this will really bring the game world to life.
You spend a lot of time in the towns you visit, and variety is the spice of life!

There is nothing like cowering in the corner of a stylish house!

**Comment by DavidKeaton** [comment]
Holding an IKEA folding bar chair crying, I sat against the mauve painted wall, clinging even harder to my sanity.

**Comment by Headjack** [comment]
Things are a little more spiced up than they used to be. Someone was once working on a PR to add what you might call 'flavors' to buildings, like looted, pristine, damaged, burnt, etc. That would probably be a good move for variety too. IDK what happened to that guy's work though.

**Comment by aparent** [comment]
Could add that on top of floor layout generation since condition is mostly independent of layout.

Redoing furniture layout so that windows and doors are not blocked would also be nice.

**Comment by Barhandar** [comment]
>The stone houses and half-condos are a way bigger mixup than in the old days

Don't forget the glorious "house with farmland" one.

**Comment by Headjack** [comment]
Oh yeah, gardeners, and the quiverfull house.

**Comment by ituluwituluwzev** [comment]
Closing - new suggestion could be PRed.
