### ISSUE TITLE
Not possible to bootstrap metalwork - maybe deliberate?

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#13116]
In a lab challenge, I've found all the books, components and skills to construct a forge then a jackhammer to escape - except I haven't been able to find a hammer. I seem to be in a Catch-22, where to make a hammer I need a forge, but both types of forges require a level 3 hammer - a makeshift hammer isn't good enough.

#12045 allowed makeshift hammers to create anvil & tongs, but not forge. Not sure if forges were deliberately left out, or missed.

Alternatively, perhaps hammers could appear in crates/racks in the lab storerooms from time to time? Other tools do, but I haven't seen a hammer.

**Comment by Rivet-the-Zombie** [comment]
It's supposed to be possible to start from nothing and work your way up to a fully functioning kit. If I had to guess, I would say that something went wonky when we implemented tool qualities across the board.

The simplest fix would be to allow players to make the forge with a makeshift hammer.
