### ISSUE TITLE
[Bug] Lab armory control panel room wrong way.

### ISSUE THREAD

**Issue by DodgingRain** [CleverRaven/Cataclysm-DDA#13127]
Windows 8 64-bit
v3496 tile.  Bug present in current stable version 0.C.

In the science lab, there is a section that contains a lot of military weapons and utilitys on racks.  Barring that are two double doors which serves as barriers, and finally the control panels that has one metal door on each side with one of the metal doors locked and also is crucial to unlocking the double metal doors.  

The problem is that the metal door on the outside is locked while the metal door towards the armory is openable.  Essentially this means whoever is already inside the armory can access the panel while those on the outside have to resort breaking through the wall to access it which kind of renders it moot afterwards.

**Comment by drbig** [comment]
(Screenshot could be useful here)

I always thought that armory was like that by design - i.e. difficult to access from the outside. The panel on the inside being more of "checkout what you take/put here".

**Comment by DodgingRain** [comment]
![i3tb9hx](https://cloud.githubusercontent.com/assets/13143681/8977146/ee22fd28-365b-11e5-9c13-475982196d0d.png)

The north door is completely locked with the south one is unlocked.  It wouldn't really make much sense from a puzzle oriented point of view as destroying the wall or bypassing it are your options and computer skills are useless because you cannot access to console.

**Comment by drbig** [comment]
Yeah I think this is intentional design. That room you see would normally be a 'checkpoint'.

**Comment by kevingranade** [comment]
Yea, this is how this kind of thing is laid out in reality, you're not
supposed to be able to get in after all :)

**Comment by drbig** [comment]
Indeed. *Not a bug* confirmed.

**Comment by DavidKeaton** [comment]
A stick of dyno-MITE would clear that problem right up. The *ultimate* MVP pass!
