### ISSUE TITLE
Cygwin build is broken in multiple ways

### ISSUE THREAD

**Issue by dholmes215** [CleverRaven/Cataclysm-DDA#13124]
The Cygwin build hasn't worked for me for some time.  Starting with 7c03d10 it fails with:

g++  -DCATA_NO_CPP11_STRING_CONVERSIONS -DLOCALIZE -ffast-math -Wall -Wextra -g  --std=c++11 -MMD -D_XOPEN_SOURCE=600 -c src/advanced_inv.cpp -o obj/advanced_inv.o
src/advanced_inv.cpp: In member function ‘void advanced_inv_area::init()’:
src/advanced_inv.cpp:639:42: error: ‘is_any_of’ was not declared in this scope
     if(is_any_of(g->m.ter(pos), ter_water)) {
                                          ^
Makefile:477: recipe for target 'obj/advanced_inv.o' failed
make: *** [obj/advanced_inv.o] Error 1

...but current head fails with:

g++  -DCATA_NO_CPP11_STRING_CONVERSIONS -DLOCALIZE -ffast-math -Wall -Wextra -g  --std=c++11 -MMD -D_XOPEN_SOURCE=600 -c src/faction.cpp -o obj/faction.o
src/faction.cpp: In member function ‘bool faction::matches_us(faction_value)’:
src/faction.cpp:534:47: error: ‘abs’ was not declared in this scope
     if ((abs(facval_data[v].good     - avggood)  <= 3 ||
                                               ^
src/faction.cpp: In member function ‘int faction::response_time()’:
src/faction.cpp:587:40: error: ‘abs’ was not declared in this scope
     int base = abs(mapx - g->get_levx());
                                        ^
Makefile:477: recipe for target 'obj/faction.o' failed
make: *** [obj/faction.o] Error 1

I will continue investigating.

**Comment by dholmes215** [comment]
There is a sequence of commits:

* 23180e9 - changed code from "vec_to_array" to "std::move", so unneeded container translation function can be removed (2 days ago) <DavidKeaton>
* e892166 - added function to query amount of worn items on player by type_id (2 days ago) <DavidKeaton>
* f08f0d2 - added max worn items per type constant (2 days ago) <DavidKeaton>
* cd9bb2e - removed unneeded functions (using std::copy/move instead); changed headers to implicitly ask for <algorithm> instead of assuming enums.h supplies it (2 days ago) <DavidKeaton>
* 41b890c - (HEAD) clarify code, a good bit more; fixing item disappearance problems (2 days ago) <DavidKeaton>

41b890c compiles cleanly.  23180e9 fails with the 'abs' not declared error. The commits in between fail due to template errors.

**Comment by dholmes215** [comment]
Issue is now fixed.

**Comment by DavidKeaton** [comment]
have they all been fixed? I think the AIM one was from my change to using `std` instead of homegrown.

**Comment by dholmes215** [comment]
I don't know what caused the other errors, but it compiles cleanly now.
