### ISSUE TITLE
Reloading soldering irons and sewing kits (and other stuff?) from AIM no longer works

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#13133]
Reloading a soldering iron from AIM using examine->reload does nothing even with batteries in inventory, but also does not give an error message.

Reloading a sewing kit asks whether to use thread/sinew/etc, but whatever you choose it doesn't reload.

**Comment by drbig** [comment]
CDDA version?

**Comment by romkuma** [comment]
Sorry, Linux, tiles, today's experimental.

More playing reveals that this extends to other activities - reading from AIM doesn't work either, for example.

Maybe everything that calls long, interruptible actions?

**Comment by drbig** [comment]
Hmm, reporting from here (0.C-4954-g835283a, tiles):

- The actions menu for Examine shows only for items in Inventory (I assume this is correct (for now))
- First aid kit has red 'a'ctivate but green 'E'at; both are usable: show menu, one can select what to heal: no effect whatsoever and no errors
- Welder (with Masochist trait): green 'a'ctivate: shows action menu, one can select cauterize for fun, works as expected but log message only visible after exiting AIM (might be the known SDL redraw bug)
- Sewing kit reloading doesn't work, but unloading does work

Yeah. At least *one* bug...

**Comment by DavidKeaton** [comment]
Can one verify this only happens in AIM?

**Comment by romkuma** [comment]
Yes, reloading works normally from the regular inventory, and reading works
normally from the main screen. I haven't checked reading from the regular
inventory.
