### ISSUE TITLE
Remove multiple forage per underbrush

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#13130]
Having to 'e' few times per brush can be annoying when there's an item on the brush or when it's dark (and underbrush looks like foliage). It doesn't really add anything that could be solved in more player-friendly way, so I'd say it's safe to remove it.

To compensate, the chance to drop and forage time could be extended based on survival skill and perception.

Currently the mechanics work like this:
* Forage time is `500 / (surv + 1)` per attempt (500 at 0 skill, 46 at 10 skill)
* `one_in(12)` chance of trash regardless of skills
* Drop items if roll succeeds: `rng(1,100) < (surv * 1.5) + (per / 2) - 1`
* If item dropped or 50% chance otherwise, turn into foliage
Note that survival and perception decrease the amount of trash found

I'd change it to something like:
* Forage time is `5000 / ( 2 * surv + 5 )` (1000 at 0 skill, 200 at 10 skill). Maybe also add some perception here?
* `one_in(10)` chance of trash regardless of skills
* If skill roll `rng(1,100) < (surv * 1.5) + (per / 2) - 1` succeeds, drop item
* If the roll fails, 50% chance of retrying it (keep retrying up to like, 10 times, each time 50% chance of not retrying further)
* Always turn into folliage

This would preserve the chances of dropping stuff, without having to e->direction up to like 4 times on low skill.

Any objections?

**Comment by Rivet-the-Zombie** [comment]
I like it.

**Comment by kevingranade** [comment]
First, I agree 'one action and you're done' is a good thing to do.

My only problem with this approach is it leaves you with a small chance of
being stuck foraging for 10 minutes, which seems excessive.  I'd much
prefer the forage time to be deterministic based on skills/stats, and you
either find something or you don't.
So reality check, you're rummaging around in a sq meter of shrubbery, just
how long is it going to take you before you're convinced that if you
haven't found something, you aren't going to?  10 minutes seems really
long, 1 minute seems a bit short.  2 minutes sounds fairly reasonable to
me, but I don't make a habit of rummaging around in underbrush, so I'm not
married to that number.

**Comment by Coolthulhu** [comment]
I meant, each attempt always takes same time (based on skills), it's just that the roll itself is repeated to maintain consistency with the old version (same amount of drops).

Though variable time could also be cool. Failure could take full time, but success only a percentage of that proportional to number re-rolls.

**Comment by kevingranade** [comment]
Aah, in that case I have no problem, though I'm leaning toward 2 minutes as
the worst case foraging time instead of 1.

**Comment by ArikVhedrovix** [comment]
It could also be cool if the small neutral animals were occasionally flushed from hiding by foraging in their hiding place.
