### ISSUE TITLE
Boats in motion vanishing on load (with no apparent cause), crashing when pushed on land, folded boats can't deploy on water.

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#13147]
![i was right the first time](https://cloud.githubusercontent.com/assets/11582235/9020690/d8adaa52-37e0-11e5-8ae7-29d3ca60b41e.png)

First issue, boats will vanish on loading if the boat is in motion. Re-tested and discovered my part editing to my last game was NOT the cause.

Second issue, game crashes if you push a boat while it's on land, IF it has enough boat boards to float. Can't swim, it works just fine. This makes deploying the inflatable boat exactly as easy as you'd expect the bug to make it.

Third issue, inflatable boats (likely other float boats too) can't be deployed partially in water as deep water is treated as an obstacle for the purpose of unfolding vehicles. This plus issue 2 makes inflatable boats flat-out unusable.

**Comment by chaosvolt** [comment]
Also, now if I knew how to add the bug and crash labels... >.<

**Comment by DavidKeaton** [comment]
pound maybe?

**Comment by DavidKeaton** [comment]
#crash #bug

**Comment by chaosvolt** [comment]
Lemme try. >.<

**Comment by chaosvolt** [comment]
Double the nope.

**Comment by greattuna** [comment]
Why don't you just wait for the DrBiG, huh? I think only people like him (conrtibutors? collaborators?) can do it.
Speaking about the bug, maybe game assumes something along the lines of "holy, it's a vehicle with all 'wheels' in water, it should drown". Gotta try it out myself.

**Comment by chaosvolt** [comment]
Oh, schiesse. That seems odd in that the main reason you'd label an issue (or at least, the main reason I'd want labeling ability) is to highlight priority issues like crashes and failures to load... =w=

**Comment by Rivet-the-Zombie** [comment]
Yeah, it takes one of us devs to tag stuff.

**Comment by chaosvolt** [comment]
Doh. Ah, sorry. @_@

**Comment by chaosvolt** [comment]
In any case, have found that boats load-vanish while in motion both if you're manning the controls and if you'd let go of the controls (say, to clobber the kamikaze beavers that my latest survivor has been fending off constantly).

**Comment by chaosvolt** [comment]
...what. Okay, testing this with an inflatable boat after FINALLY getting one in the water by removing its airbags, pushing it in, then reinstalling.

It seems that while my wooden boat will vanish if loading the game while in motion, an INFLATABLE boat won't.

**Comment by chaosvolt** [comment]
Oh. OH. Fuck me. I just realized something that seems to have been the cause. I'd edited hand paddles to count as controls on mine, and it seems having paddles but no normal vehicle controls makes it bug out.

**Comment by chaosvolt** [comment]
Nope. Nope. So much nope. I just grabbed the latest experimental, assembled a canoe the right way without any part edits, got it up to speed and did a save-load test.

![i was right the first time](https://cloud.githubusercontent.com/assets/11582235/9020690/d8adaa52-37e0-11e5-8ae7-29d3ca60b41e.png)

I was right to begin with.

**Comment by chaosvolt** [comment]
This is giving me a headache. Did more testing.

1. Inflatable boat. No incidents on save-load test.
2. Replaced inflatable airbags with boat boards. No incidents.

3. Made a mockup of an inflatable boat with wooden frames instead of flatable sections. No incidents.
4. Replaced airbags with boards. No incidents.
5. Replaced folding seat with wooden seat. No incidents.
6. Removed seat entirely. No incidents.
7. Removed extra 4th frame and board. No incidents.
8. Removed remaining side panel and replaced with one behind driver, making a canoe layout. No incidents.
9. Added a wooden box to the back. No incidents.

10. Built conventional wooden 1x3 canoe with wooden seat and box in the back. No incident.
11. Removed seat from said canoe. Game finally remembered I'm not supposed to be able to control a boat without seat, so couldn't get it back up to speed to save-load test. Despite it not caring about this issue previously.
12. Added a folding seat. No incidents.

13. Went back to boat from tests 3-9, got it moving again.
14. Remembered that I had something in the canoe's box, took it out. NOW the canoe vanishes on load.

15. Mocked up another seatless canoe, this time lacking the wooden box. No incidents.
16. Gave it a wooden box in the back, left empty. No incidents.
17. Dumped a book in said box. No incidents.
18. Removed said book. No incidents.

**Comment by drbig** [comment]
I assume this is all about the Boats mod?

**Comment by chaosvolt** [comment]
Absolutely, yes. @_@

**Comment by chaosvolt** [comment]
So now I'm back to square one where I have no bloody clue what the exact cause of the vanishing boats is.

**Comment by drbig** [comment]
Bug hunting can can result in lots of *WTF*s. On the bright side (...): it doesn't exists until replicated ;)

**Comment by chaosvolt** [comment]
Maybe. And now I'm wondering whether confirmation needed means we need more people to test these bugs, or just finding out the cause. The "boat crashing when pushed" and "can't unfold boat in water" bugs are easy enough to confirm in the former sense, obviously.

And augh, bad Github, not refreshing the notification icon correctly. :V

**Comment by chaosvolt** [comment]
I'm going to assume nobody's found any info on the cause of any of these yet? ._.

**Comment by DanmakuDan** [comment]
I made a simple boat with boat boards on each tile, controls and a hand paddle in top left.
xx
xx

The game crashes when I pushed it across the land I built it on. 

In game::plmove, an arithmetic exception gets generated at line 11996 in game.cpp:
```
                    //if vehicle weighs too much, wheels don't provide a bonus.
                    if (grabbed_vehicle->valid_wheel_config() && str_req <= 40) {
                        //determine movecost for terrain touching wheels
                        std::vector<int> wheel_indices = grabbed_vehicle->all_parts_with_feature(VPFLAG_WHEEL);
                        for(auto p : wheel_indices) {
                            mc += (str_req / wheel_indices.size()) *
                                m.move_cost(grabbed_vehicle->global_x() + grabbed_vehicle->parts[p].precalc[0].x,
                                        grabbed_vehicle->global_y() + grabbed_vehicle->parts[p].precalc[0].y,
                                        grabbed_vehicle);
                        }
                        //set strength check threshold
                        //if vehicle has many or only one wheel (shopping cart), it is as if it had four.
                        if(wheel_indices.size() > 4 || wheel_indices.size() == 1) {
                            str_req = mc / 4 + 1;
                        } else {
                            str_req = mc / wheel_indices.size() + 1;
                        }
                    } else {
                        str_req++;
                        //if vehicle has no wheels str_req make a noise.
                        if (str_req <= u.get_str() ) {
                            sounds::sound( grabbed_vehicle->global_pos3(), str_req * 2,
                                _("a scraping noise."));
                        }
                    }
```

at
```
str_req = mc / wheel_indices.size() + 1;
```
wheel_indices.size() is 0, because there are no real wheels on the boat. The code is reached because grabbed_vehicle->valid_wheel_config is true when 3 boat pieces are detected. If boat pieces are expected at this part in the logic, it probably needs to have an alternative count of boat pieces instead to allow the boat to be pushed smoothly.

**Comment by DanmakuDan** [comment]
Also, I need some designs or a save where I can test the other problems.

**Comment by kevingranade** [comment]
Looks like all it needs is to change:
```str_req = mc / wheel_indices.size() + 1;```
To
``` str_req = mc / (wheel_indices.size() + 1);```
Which I think is what was intended.  Floats shouldn't allow easy dragging
on land.  Setting aside the wackiness of each added wheel reducing the
strength needed to drag...

**Comment by DanmakuDan** [comment]
I think it was supposed to mean at least 1 STR is needed for the strength required amount. Also, I tried substituting the floaty pieces as wheels in the code, since there is a code portion farther down that checks for wheels on traps, since those are the only pieces contacting the ground. How would the vehicle be checked for ground contact if there are no specific contact points (the whole vehicle instead)?

**Comment by DanmakuDan** [comment]
Also, a test boat in motion finally vanished after reloading a save. So far, it looks like the vehicle is deleted on save.

**Comment by chaosvolt** [comment]
Ooh swiggith swooty, glad to see someone's found a cause there.

As for designs, I favored a simple 1x3 canoe. All wooden frames with boat boards, wooden seat in the center, and a wooden box in the back.

Even without the box, and with or without a seat, I seem to get a sporadic boat vanishing, so no idea what triggers yet.

**Comment by chaosvolt** [comment]
Ah. So no consistant cause yet? o.O

**Comment by DanmakuDan** [comment]
I got it to happen once a minute ago, I checked the save file and the boat isn't there.

**Comment by chaosvolt** [comment]
So the save basically just eats the boat. That is...weird. :v

**Comment by DanmakuDan** [comment]
I made like 5-6 boats vanish, the debugger does not catch anything unusual happening. It looks like the submap where the vehicle is isn't saving. Coincidentally, the game camera seems to run away when steering a certain way with the boat.

**Comment by chaosvolt** [comment]
How the...what the...I've never had non-boat vehicles vanish, so no idea why the submap hates boats.

Have you had any disappearances with the inflatable boat, or has it only been handmade boats?

**Comment by DanmakuDan** [comment]
I only tested a handmade 2x2 boat. I was wondering if 
```
        save_quad( dirname.str(), quad_path.str(), om_addr, submaps_to_delete,
                   delete_after_save || zlev_del ||
                   om_addr.x < map_origin.x || om_addr.y < map_origin.y ||
                   om_addr.x > map_origin.x + (MAPSIZE / 2) ||
                   om_addr.y > map_origin.y + (MAPSIZE / 2) );
```
needs a ```om_addr.x < map_origin.x - (MAPSIZE / 2)```, I don't know if the map_origin is centered, since MAPSIZE / 2 implies that a center is being used. This could affect 
```
void mapbuffer::save_quad( const std::string &dirname, const std::string &filename, 
                           const tripoint &om_addr, std::list<tripoint> &submaps_to_delete, 
                           bool delete_after_save )
```

I am guessing if the delete_after_save flag is set, the uniform water surface could trigger a save ignore for the submap the vehicle is on, but I don't have a way to confirm that the logic is performing like that.

**Comment by chaosvolt** [comment]
Weird. Thing is I've yet to encounter this issue with inflatable boats, but...

Small problem with testing inflatable boats. Can't deploy them on water (issue 3), and can't push them into the water after deploying on land (issue 2). This means you have to remove some inflatable airbags, push it into water, THEN reinstall them.

Thing is, while that SHOULDN'T make the odds of boat disappearances any different from a purely untouched inflated boat, these bugs have been insane enough that I wouldn't be surprised if that affects the result of testing inflatable boats.

I swear, between this and https://github.com/CleverRaven/Cataclysm-DDA/pull/13175 I'm starting to think I have a supernatural ability to blunder into the weirdest possible bugs. XP

**Comment by chaosvolt** [comment]
Ooh, swiggity swooty.
