### ISSUE TITLE
"You disassemble your none into its components"

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#13146]
- Acquire valuable stuff that can be disassembled and has >0 volume
- Lose carrying capacity
- Start disassembling stuff before it tumbles out
- "You disassemble your none into its components"
- Both components and the item are now on the ground
##

**Comment by kevingranade** [comment]
Inventory overflow check when you open an inventory menu?  Seems like that
would close off the whole class of "interact with item that falls. Out of
inventory before action is resolved" errors.

**Comment by Barhandar** [comment]
I see you touching your none.

**Comment by chaosvolt** [comment]
I miss the days when we had encumbrance penalties instead of autodrop already. :V

**Comment by Oskar636** [comment]
This definietly cannot happen anymore, it either goes " item has vanished " for when something else is dropped or " the item might be gone, at least it is not at the expected position anymore " .
