### ISSUE TITLE
Read books on the ground

### ISSUE THREAD

**Issue by Ishindri** [CleverRaven/Cataclysm-DDA#13153]
Since we can eat food that's on the ground on the player's tile, could the same functionality be implemented for books?

**Comment by drbig** [comment]
If you were to ask me: given we are going in the direction of 'a'pply and 'e'at from inventory and ground, it would be logical and consistent to have all actions work with stuff from ground (perhaps including some additional move cost for picking the item up and then putting it down).

Having said that the framework for handling inventory from both sources is certainly not finished yet. I'm also afraid a bit that this might turn into a 'mudball' e.g. after this gets fully in people will want it to work from 3x3 tiles around player and so on...

**Comment by Rivet-the-Zombie** [comment]
On a semi-related note: maybe there could be an additional (small) morale bonus for reading while you're on a chair/couch/bed/whatever is comfortable to sit on.

**Comment by drbig** [comment]
> On a semi-related note: maybe there could be an additional (small) morale bonus for reading while you're on a chair/couch/bed/whatever is comfortable to sit on.

Oh yes. And that ties in with the "proper furniture" ideas nicely.

**Comment by Coolthulhu** [comment]
> after this gets fully in people will want it to work from 3x3 tiles around player and so on...

This one wouldn't be all that hard. The system for eating off the ground already addresses items by tiles rather than using player's tile.
The only real problem I see here would be extended actions, because the item can disappear. That said, the same problem already exists with extended actions in inventory due to inventory overflow.
