### ISSUE TITLE
Smoke bombs create transparent smoke, useless except for scent removal (and maybe not even that)

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#13150]
Additionally, it also disperses in three turns or so even inside a building.

**Comment by Coolthulhu** [comment]
The "Bug" label doesn't really fit.

Two ways to fix this:
* We make smoke bomb into a smoke grenade that takes a while to spew all the smoke. For few turns, it lies there re-producing the smokecloud
* Make a separate kind of smoke that isn't spawned by fires. This one could stay for way longer than smoke produced by fires without burdening fires with extra lagginess.

**Comment by Rivet-the-Zombie** [comment]
Actually, both of those fixes together would be great for smoke grenades.

They really ought to put out smoke for several turns, as that's how they work in real life, and the smoke should stick around for a bit longer (and be denser too) because the chemicals used in smoke grenades are used because they specifically put out long-lasting, dense smoke.

**Comment by Barhandar** [comment]
>We make smoke bomb into a smoke grenade that takes a while to spew all the smoke.

Would be great if it actually had a 5-turn trigger like explosive grenades instead of 20+ turn one and used the 15 turns in question to do smoke. Ditto for tear gas, and it'd welcome to make that one's name consistent (it's "tg canister" when inactive, but "tg grenade" when active).
>because they specifically put out long-lasting, dense smoke.

Which additionally usually doesn't cause suffocation like fire smoke does. Of course potassium nitrate-based ones cause headaches, but...

**Comment by illi-kun** [comment]
Thanks for reporting this issue, it was in my personal list for a while.

> The "bug", I presume, is smoke bombs being useless for their stated purpose.

I noted that when I've added spawn of 40mm smoke grenades to APCs and tried to set smoke screens.

**Comment by kevingranade** [comment]
I'm not seeing the same behavior that is being reported, when I test smoke bombs they produce a 5x5 area with varying levels of smoke density, a significant amount of which is thick, so it blocks all vision.
I agree with Coolthulu's suggestions though, both of those would be nice additions.

**Comment by mugling** [comment]
> We make smoke bomb into a smoke grenade that takes a while to spew all the smoke. For few turns, it lies there re-producing the smokecloud

This was done in `master`
