### ISSUE TITLE
infinite upward scrolling bug on launch

### ISSUE THREAD

**Issue by blerud** [CleverRaven/Cataclysm-DDA#13157]
When I launch the game, the cursor starts scrolling upwards and takes me to the world gen mod list page. Pressing and holding down will make the cursor scroll down, and pressing up just makes it scroll faster. Scrolling continues on other pages.

Currently running Windows 10; this happens in both the stable release and the latest build.

**Comment by drbig** [comment]
Sounds weird enough... Can anyone replicate it?

**Comment by Rivet-the-Zombie** [comment]
I recall someone having a similar problem that turned out to be caused by a malfunctioning joystick that was plugged in at the time.

**Comment by vache** [comment]
Yeah, connected controller ended up being the problem before.  I don't know if it was so much malfunctioning as it was that the game didn't support it.

**Comment by blerud** [comment]
That's odd. The only peripherals I have plugged in are my mouse, keyboard, and external hdd. I tried unplugging the keyboard and mouse, but the problem persists.

**Comment by Zireael07** [comment]
@blerud: Do you have any joystick drivers/software on your system?

**Comment by blerud** [comment]
@Zireael07 
Turns out it was my VJoy Virtual Joystick. Disabling that solved the issue.
