### ISSUE TITLE
AIM Crash When Selecting left direction

### ISSUE THREAD

**Issue by hustergeyser** [CleverRaven/Cataclysm-DDA#13155]
Version "0.C-3509-b3ab538", Linux, Curses.
Pull up aim and press 6 to select the right space, crashes the game and gives

cataclysm: src/advanced_inv.cpp:738: advanced_inv_listitem::advanced_inv_listitem(const std::list<item *> &, int, aim_location, bool): Assertion 'stacks ==1 || !items.front()->count_by_charges()'failed.
Aborted (core dumped)
https://www.dropbox.com/s/nrb8vew5mw97ox1/Bantam.zip?dl=0

**Comment by drbig** [comment]
@hustergeyser we are currently at `0.C-5012-g79a3689` - maybe first try a newer build? (e.g. Jenkins build 3514).

**Comment by hustergeyser** [comment]
Just downloaded the latest build and the same crash is happening.

**Comment by DavidKeaton** [comment]
I see the issue, can fix.

**Comment by Ishindri** [comment]
Confirming that I'm experiencing this issue on 0.C-3523, opening AIM with a dragged vehicle to the player's left.
