### ISSUE TITLE
charcoal kiln (the constructed version) does not accept human bones as kilnable

### ISSUE THREAD

**Issue by pipehat** [CleverRaven/Cataclysm-DDA#13158]
steps:
1. construct charcoal kiln (furniture construction menu, not the crafted kiln)
2. place human bones in the kiln
3. examine kiln
Result: Message "This kiln contains human bone, which can't be made into charcoal!" (from iexamine.cpp)

The 'filled charcoal kiln' recipe DOES allow human bone. So this seems to be an inconsistency with the constructed kiln version that uses examine instead of crafting.

Human Bone has two material types: bone and hflesh -- that duality causes it to fail the made_of_only (bone or wood) test in iexamine.cpp.

Could just switch the made_of_only() check to made_of_any()? Not sure if that would cause other complications.

**Comment by pipehat** [comment]
A quick scan to see what other bone/other material hybrids exist - see below. These matches hint at the broader array of stuff that could get thrown in the kiln if we were to allow anything that was at least partly bone.

I guess it would really be nicer to eliminate this crafting/examine duplication and have the constructed kiln satisfy the charcoal kiln crafting tool recipe.

~/Cataclysm-DDA/data/json/items $ grep "material.*bone" *
armor.json:        "material" : ["bone", "leather"],
armor.json:        "material" : ["bone", "leather"],
armor.json:        "material" : ["bone", "leather"],
armor.json:        "material" : ["bone", "null"],
armor.json:        "material" : ["bone", "silver"],
comestibles.json:        "material" : "bone",
comestibles.json:        "material" : ["bone", "hflesh"],
comestibles.json:        "material" : "bone",
comestibles.json:        "material" : "bone",
comestibles.json:        "material" : ["bone", "hflesh"],
melee.json:        "material": "bone",
tools.json:    "material": "bone",
tools.json:    "material": "bone",
tools.json:    "material": ["glass", "bone"],
tools.json:    "material": ["glass", "bone"],
vehicle_parts.json:        "material": ["bone", "null"],

**Comment by drbig** [comment]
@pipehat can you confirm version? I'm trying to (debug) replicate here at `0.C-5012-g79a3689` and debug spawned 1x charcoal kiln + 40x human bone work as well as hammerspace-ed 1x charcoal kiln + 40x deug spawned human bone.

**Comment by Coolthulhu** [comment]
The constructed version of kiln is a furniture, not an item.

**Comment by drbig** [comment]
Ok. Anyone can replicate?...

**Comment by pipehat** [comment]
confirmed with current dev version
0.C-5025-g661d11f-dirty

Added an extra step above to help clarify it's the constructed (furniture) kiln, not the item kiln.

**Comment by drbig** [comment]
@pipehat thank you for very decent issue reporting. Feel free to PR a solution! (just an encouragement, we'll look into this anyway).

**Comment by pipehat** [comment]
I looked a bit into enabling the furniture kiln to work with the crafting recipe but it looks tricky b/c the recipe requires the kiln as a component (to replace it with 'filled charcoal kiln') instead of as a tool.

Not sure if there's some way to still make that work. But here's a simple if hackish fix for now.
