### ISSUE TITLE
More natural salt sources

### ISSUE THREAD

**Issue by pipehat** [CleverRaven/Cataclysm-DDA#13164]
Looking for feedback.

Tried to play a wilderness-only run recently - couldn't find any natural salt source nearby spawn area though even after wandering for a day.

Since salt is so critical for tanning I'd like to have a couple more options for acquiring it in the wild if you're living au naturel.

Natural underground salt
* Occasional salt block wall in exposed natural underground locations (cave, mine, and when tunneling underground). Source: http://gizmodo.com/the-incredible-urban-salt-mines-hiding-underneath-our-f-1516664767

Boiling hickory roots
*  Perhaps a new forge-able 'hickory root' item from: bushes, or new special tree type, or maybe applying a DIGGING:1 tool against any tree or randomly digging near a tree? Source: http://www.survival-manual.com/hickory-salt.php

**Comment by drbig** [comment]
I'm certainly not against. "Salt water at swamps" probably gets very boring very soon.

**Comment by Zireael07** [comment]
+1 to underground salt. And I think hickory is in game (probably in a mod, though)

**Comment by Rivet-the-Zombie** [comment]
What about [natural salt licks](https://en.wikipedia.org/wiki/Mineral_lick)?

**Comment by pipehat** [comment]
Yeah, natural salt licks are a good idea. Tried to find info - sounds like they're usually mineral salt water springs.

Does sounds like that's a different thing than the new england 'salt marsh' represented by our current in-game salty swamps.

I couldn't tell if they're always near springs or if it's sometimes a left-over buildup of salt. Sounds like human intervention has probably cleared out most free standing natural salt buildups.

**Comment by Rivet-the-Zombie** [comment]
Yeah, basically they could be represented as a patch of specialized terrain made of special dirt that can be processed via unique recipe to produce salt.

**Comment by drbig** [comment]
Sodium chloride... mhm... :D

**Comment by chaosvolt** [comment]
Hickory salt, then we'd also have an excuse to add BBQ recipes...
