### ISSUE TITLE
Embedding weapons in small creatures

### ISSUE THREAD

**Issue by pipehat** [CleverRaven/Cataclysm-DDA#13165]
I threw my forked spear at a possum and the spear got embedded. And then the possum ran away!

Funny but not really fun or realistic. Recommend some balancing variation like:
* embed chance is random
* examine interaction to remove weapon from creature prior to death
* projectiles bigger than the target cannot embed - OR - if projectile is heavier than the creature, pin it in place?
* variation of 'pinning': creatures with embedded projectile suffer forced weight and volume encumbrance of the projectile. That could model slowing down/pinning small targets. 
* embedded projectiles causing bleeding and/or continuous damage while embedded - bonus if this leaves a blood trail. This would make spear hunting wild game pretty fun.

Attn: @Coolthulhu (who I think created this feature?) for discussion.

**Comment by Coolthulhu** [comment]
Pinning sounds like it could be quite a bit of work, so for now I'd say just disabling embedding of big projectiles in small creatures would be enough.

**Comment by Barhandar** [comment]
Embedded projectiles causing bleed could be nice, though.

**Comment by DavidKeaton** [comment]
depending on possibly another factor, it could have a chance to become dislodged.
