### ISSUE TITLE
Can No Longer "Eat" First Aid Kits

### ISSUE THREAD

**Issue by DeNarr** [CleverRaven/Cataclysm-DDA#13169]
Using E, you can no longer activate First Aid Kits, though you can still use Bandages and Cotton Balls this way.
##

**Comment by Coolthulhu** [comment]
Intended

**Comment by Coolthulhu** [comment]
Oops, closed a bit too fast: using kits in the inventory should be fine, just not the ones on the ground.

**Comment by DeNarr** [comment]
Is there a reason we can use cotton balls and bandages from the ground, but not first aid kits?

**Comment by Coolthulhu** [comment]
Extended action required to use the first aid kit.

Currently extended actions can't properly pick up kits from the ground.

**Comment by drbig** [comment]
As per #12991 discussion - 'E'ating First Aid Kits makes little sense. It makes no sense for either Bandages or Cotton Balls (unless you're aiming for indigestion (at best)). I'm against it ('a'pply should be the way to go).

**Comment by DeNarr** [comment]
@drbig I would agree, if it wasn't for the fact that pressing 'a' to apply gives a much larger list. It puts things on the list that can't even be applied. Since first aid kits are one of the things I need to consume the most often, and they are conveniently in the last grouping when eating (or were at least), it made it very easy to actually use what I wanted. So I just figured Eat meant consume, and was happy how it was.

**Comment by drbig** [comment]
> It puts things on the list that can't even be applied.

Maybe we should fix this instead?

> So I just figured Eat meant consume, and was happy how it was.

You may want to assign a key to the first aid kit. I do it for a bunch of often used stuff ('w' for canteen, 'l' for flashlight etc.) - thirsty? 'aw'; dark place? 'al'; back in sunlight? 'al'. *Very* useful.

**Comment by Zireael07** [comment]
I agree that eating a first aid kit makes little sense - it should be 'a'plied instead.

**Comment by Barhandar** [comment]
I disagree. Reality takes second set to convenience, thus 'E'ating should be usable for medicine and work identically to 'a'pplying it because of already-stated point of 'a' displaying a much longer list.

And no, I'm not assigning permament keys to something I use once per forever but need it used quickly, like painkillers.

**Comment by DeNarr** [comment]
@drbig "You may want to assign a key to the first aid kit. I do it for a bunch of often used stuff ('w' for canteen, 'l' for flashlight etc.) - thirsty? 'aw'; dark place? 'al'; back in sunlight? 'al'. Very useful."

Of course, if you can't Eat med supplies, you probably shouldn't be able to Activate water if you're thirsty :P

**Comment by drbig** [comment]
> Of course, if you can't Eat med supplies, you probably shouldn't be able to Activate water if you're thirsty :P

I'm activating a container here (applying, well). But yeah, I'm still for symmetry and it being easily explainable in English ("eat canteen" vs "apply canteen"; "eat your first aid kit" vs "apply first aid kit").

Still checkout whole of #12991 discussion - the idea there is to have for some stuff different actions between 'a'pply/ctivate and 'e'at.

**Comment by Skidborg** [comment]
I'm with the crowd that thinks stuff that can't actually be eaten shouldn't show up on the eat menu. If we're after convenience, then maybe a separate medication menu would be appropriate, but eating makes no sense.

**Comment by keyspace** [comment]
Note: [a]ctivate menu has been reworked.
