### ISSUE TITLE
Crash when attempting to craft lightstrip

### ISSUE THREAD

**Issue by Ishindri** [CleverRaven/Cataclysm-DDA#13177]
Windows 7 and SDL version, both `0.C-3515-661d11f` and `0.C-3523-c1dc4e5`, static NPCs enabled. I have a reliable crash when trying to craft a lightstrip.  Link to a save is [here](https://dl.dropboxusercontent.com/u/7857015/save.7z).  If there are any steps I can take to narrow it down, please let me know.

**Comment by DanmakuDan** [comment]
It looks like the electronics skill level is being checked as part of the memorization chance for the lightstrip recipe when crafting. The chance is divided by the skill level, which is zero in the save file, causing a divide by zero crash.
