### ISSUE TITLE
Exception in save load, expecting number but found " (MinGW 4.9.2, tiles build 3522?)

### ISSUE THREAD

**Issue by DanmakuDan** [CleverRaven/Cataclysm-DDA#13178]
There is a quiet exception being thrown in the save loader, when loading uistate.json, the part ```"adv_inv_filter":["",""]``` is expecting a number instead of a string. I'm not sure if the rest of the json is loaded after this exception is thrown.

My uistate.json:
```{"adv_inv_sort":[1,1],"adv_inv_area":[5,0],"adv_inv_index":[0,0],"adv_inv_in_vehicle":[false,false],"adv_inv_filter":["",""],"adv_inv_src":0,"adv_inv_dest":1,"adv_inv_last_popup_dest":0,"adv_inv_container_location":-1,"adv_inv_container_index":0,"adv_inv_container_in_vehicle":false,"adv_inv_container_type":"null","adv_inv_container_content_type":"null","editmap_nsa_viewmode":false,"overmap_blinking":true,"overmap_show_overlays":false,"list_item_mon":-1,"list_item_sort":0,"list_item_filter_active":false,"list_item_downvote_active":false,"list_item_priority_active":false,"input_history":{}}```

**Comment by DanmakuDan** [comment]
Looks like get_int_array is used instead of get_string_array, since this is apparently the filter text being used on the two sides of the AIM interface.

**Comment by drbig** [comment]
Yeah, AIM is unfortunately still very buggy.

**Comment by DanmakuDan** [comment]
The fix has been merged, this can be closed now.
