### ISSUE TITLE
Crafting clean water while standing on a vehicle with tank asks for direction

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#13170]
I'd really like it to only ask whether I want to refill it or not, since, you know, I'm already standing on it.

Or only ask for direction if there are several vehicles in reach.
##

**Comment by Oskar636** [comment]
In build 5864 when you're standing on a tile with a vehicle with a tank it queries you four options:

![water filling](https://cloud.githubusercontent.com/assets/7549186/20197780/8bdf67ec-a7a1-11e6-95aa-39bb61aaf9af.jpg)
But if there is one near you it asks you if you want to fill the second vehicle, too. The one you're standing on is higher on the list.
If one of the vehicles has more then one tank, it opens the vehicle menu and queries you which tank to fill, and you can select it then. I don't consider this issue an issue now.
