### ISSUE TITLE
Pipe combination gun disassembly produces an underbarrel shotgun 

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#13171]
The pipe combination gun introduced in #12961 behaves strangely in disassembly. You get back all the items (scrap metal, pipes, etc) used to create the combination gun, but also a "pipe combination gun shotgun" which is an underbarrel mod. The pipe combination gun shotgun itself can't be disassembled, so you don't create free parts, but you do get a free underbarrel shotgun.

Linux, tiles, g3891d64

Presumably the disassembly code first removes all modifications, even integrated ones.

Fix would be either:
1) changing the disassembly code to not remove integrated modifications; or
2) change the disassembly recipes - add a disassembly recipe for the underbarrel shotgun, and reduce the amount of material produced by disassembling the main gun.

**Comment by chaosvolt** [comment]
Oh that is weird. Never tried adding a reversible recipe for weapons with integral mods before that, so that would be a fail on my part.

**Comment by chaosvolt** [comment]
Went with the idea of making underbarrel pipe shotguns a craftable mod, and having that be integral to the pipe combination gun.

**Comment by chaosvolt** [comment]
Is there a tag for "this bug wasn't discovered until some lunatic did something the developers never expected" while we're at it? XP

**Comment by Barhandar** [comment]
>Is there a tag for "this bug wasn't discovered until some lunatic did something the developers never expected" while we're at it? XP

Yes. It's called "Bug".

**Comment by chaosvolt** [comment]
Bugs are bugs, and range from the mundane to the insane. Hence jokingly suggesting we need a tag for bugs that, rather than being introduced by some recent mistake, instead likely has been around forever until someone's changes brought it to light.
