### ISSUE TITLE
Build failed on Mac with new Makefile

### ISSUE THREAD

**Issue by DLaboratory** [CleverRaven/Cataclysm-DDA#13195]
After merged PR13129(build tests by default), building with either `clang++`(version 3.5) or `g++`(5.2.0 installed from Homebrew in order to support C++11 features used in Cataclysm-DDA) on Mac fails. After I invoked

    make CLANG=1 NATIVE=osx OSX_MIN=10.7 TILES=1 LOCALIZE=1 LANGUAGES="zh_CN" RELEASE=1 -j4

The compilation for `cataclysm-tiles` executable worked fine, but after a `ar rcs xxx.o` command, two lines of `xxx has no symbols` warning appear:

    ar rcs xxx.o xxx.o ... ... xxx.o
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xtoolchain/usr/bin/ranlib: file: cataclysm.a(posix_time.o) has no symbols
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xtoolchain/usr/bin/ranlib: file: cataclysm.a(wincurse.o) has no symbols

And then, after compiling a few .cpp files of "tests" with `clang++` correctly, 

    ... ...
    clang++ -DRELEASE ... ... -stdlib=libc++ --std=c++11 -MMD -mmacosx-version-min=10.7 ... ... -c test_main.cpp -o obj/test_main.o
    ... ...

when linking `cata_test` executable, wrong compiler was used:

    g++ -o cata_test -DRELEASE ... ... -stdlib=libc++ --std=c++11 -MMD -mmacosx-version-min=10.7 ....
    g++: error: unrecognized command line option '-stdlib=libc++'

I explicitly declared `CLANG=1` in my `make` command, but here it invoked `g++` to link the executable. Finally, `cataclysm-tiles` was build successfully, but `cata_test` failed to build.

Next, I executed `make clean` to clean current build, then use `g++` to build Cataclysm-DDA:

    make NATIVE=osx OSX_MIN=10.7 LOCALIZE=1 LANGUAGES="zh_CN" TILES=1 RELEASE=1 -j4

But another error comes:

    src/iexamine.cpp: In function ‘void iexamine::fswitch(player*, map*, const tripoint&)’:
    src/iexamine.cpp:1206:6: error：assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
     void iexamine::fswitch(player *p, map *m, const tripoint &examp)
            ^

**Comment by drbig** [comment]
@DLaboratory Can you apply and test this diff:
```diff
diff --git a/tests/Makefile b/tests/Makefile
index 41ec2e6..893b5d6 100644
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -13,18 +13,14 @@ ODIR := obj
 
 DDIR := .deps
 
-LDFLAGS += -L.
-
 # Allow use of any header files from cataclysm.
 # Catch sections throw unused variable warnings.
 CXXFLAGS += -I../src -Wno-unused-variable
 
-LD := $(CROSS)g++
-
 tests: cata_test
 
 cata_test: $(ODIR) $(DDIR) $(OBJS)
-       $(LD) $(W32FLAGS) -o $@ $(DEFINES) $(OBJS) $(CATA_LIB) $(CXXFLAGS) $(LDFLAGS)
+       $(CXX) $(W32FLAGS) -o $@ $(DEFINES) $(OBJS) $(CATA_LIB) $(CXXFLAGS) $(LDFLAGS)
 
 # Iterate over all the individual tests.
 check: cata_test
```

Make sure you have run `make clean` in `tests/`. Then run `make` with the usual params you use for building CDDA (from the top directory, not from within `tests/`).

**Comment by DLaboratory** [comment]
@drbig
After apply this patch I build with `clang++` **successfully**. But two warnings are still there:

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: cataclysm.a(posix_time.o) has no symbols
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: cataclysm.a(wincurse.o) has no symbols

Also, I wonder why Cataclysm-DDA failed to build with `g++`:

    src/iexamine.cpp: In function ‘void iexamine::fswitch(player*, map*, const tripoint&)’:
    src/iexamine.cpp:1206:6: error：assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
     void iexamine::fswitch(player *p, map *m, const tripoint &examp)
          ^

Thank you very much.

**Comment by BevapDin** [comment]
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: cataclysm.a(posix_time.o) has no symbols

That's fine. The file is only used when building for/on Windows. On other platforms, the native system library get used and the file is effectively empty. Same happens to cata_tiles.o and sdltiles.o on non-SDL builds.

> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: cataclysm.a(wincurse.o) has no symbols

Similar as the above. It's only used for curses-builds on Windows. It contains the curses emulation for Windows.

> Also, I wonder why Cataclysm-DDA failed to build with  g++ :
src/iexamine.cpp: In function ‘void iexamine::fswitch(player*, map*, const tripoint&)’:
src/iexamine.cpp:1206:6: error：assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void iexamine::fswitch(player *p, map *m, const tripoint &examp)

I had this, too. Looks like a false positive, just ignore it.

**Comment by DLaboratory** [comment]
@BevapDin Thank you very much, I used to thought it was an error. GCC seems incapable to build CDDA, is it a bug of optimization part of GCC, or a problem in our code?

**Comment by BevapDin** [comment]
> GCC seems incapable to build CDDA, is it a bug of optimization part of GCC, or a problem in our code?

I assume a bug in GCC, especially since Clang accepts it any my gcc (5.1.0) only complains with `-O3`.
