### ISSUE TITLE
Mods with "IRREMOVABLE" tag can be retained in inventory but not dropped following disassembly of main item

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#13196]
Uncovered in #13175 while attempting to fix #13171

To recreate:
1) create pipe combination gun
2) dismantle pipe combination gun
3) all components drop on floor
4) a combination gun shotgun mod item appears in inventory
5) drop combination gun shotgun mod item
6) mod item disappears

Linux, tiles, gc0aae08

A quick search says that the offending bit of code is around line 2329 of crafting.cpp - this is where the mods are removed before the gun is disassembled. Presumably this should exclude mods that are IRREMOVABLE.

**Comment by chaosvolt** [comment]
Ah, so the IRREMOVABLE flag is doubly broken, it seems. See? I knew I should've stuck with keeping the roundabout way of having it be a craftable item and using separate dismantling recipes for the weapon. >.<

**Comment by chaosvolt** [comment]
I'd heard someone claim they were going to PR a full fix of this? Has this gone through, or am I gonna have to RE-impement my original workaround of making the integral mod a usable underbarrel mod?
