### ISSUE TITLE
Make enhanced hearing sound levels more intuitive?

### ISSUE THREAD

**Issue by Shadefang** [CleverRaven/Cataclysm-DDA#13197]
Earlier I panicked because my electric car was making so much noise (50ish noise while going 39mph) and realized that it was displaying a noise number after applying the multiplier from the enhanced hearing CBM. After a bit of testing, all the hearing enhancements seem to work this way.

After thinking about it a bit it does make sense, but i'm curious about others' thoughts, and whether the sound meter is intended to work this way. 
When the only place you get a number for sound is how much sound you are making, and the only place that matters is how others perceive it, wouldn't it make  more sense from a gameplay perspective to give the actual noise value, as opposed to giving the modified noise value and forcing the player to look up all the modifiers they have on them if they want to make use of that number?

**Comment by kevingranade** [comment]
It is intended to work this way, it reports subjective sound.  If it reported an objective sound measurement, it would give the player more information than they are supposed to possess.
