### ISSUE TITLE
Fairly frequent crashes, often in NPC trade menu/item pickup menu

### ISSUE THREAD

**Issue by gimlet90210** [CleverRaven/Cataclysm-DDA#13200]
c3f2bd3/build 3520 - Windows, Tiles

AppName: cataclysm-tiles.exe	 AppVer: 0.0.0.0	 ModName: cataclysm-tiles.exe
ModVer: 0.0.0.0	 Offset: 007b4f16

from the error report:
Code: 0xc0000005
Address: 0x00000bb4f16

I can repeat this from the last save by immediately going into NPC trade menu and strumming fingers on item keys, on my side of trade.

Oh just started happening, last version I played with is about 2 weeks old, no crashes with similar gameplay.

ED:  OK tried on very latest c0aae08/build 3531 and cannot repeat immediately from save, crossing fingers.  Should have tried this first, sorry :D

**Comment by drbig** [comment]
Just in case leaving it open for now.

**Comment by gimlet90210** [comment]
OK happened again on latest 7a89664/build 3542   I have a save where it's repeatable for me, but it's 200+ mb so let me know if you want it.    cataclysm-tiles.exe  Offset: 007bc286 Address:  0x00000bbc286  Code 0xc0000005

Trading with NPC, selecting any item on my side does it

**Comment by BevapDin** [comment]
If *you* can not reproduce it in a new game, others won't be able to do, most likely because it's something in the save. In that case, we need the save.

> I can repeat this from the last save by immediately going into NPC trade menu and strumming fingers on item keys, on my side of trade.

This is a bit fuzzy. What does "strumming fingers on item keys" mean exactly? Are you pressing keys that are linked to the displayed items (a, b, c ...), if so which items are there displayed. Or are you pressing keys that should have no behavior at all?

**Comment by gimlet90210** [comment]
In that case, yeah I had to press keys on the trade screen, on my side of the trade, rapidly to make it happen (I call it "strumming - just press a,s,d,f,a,s,d,f rapidly), all of them were items, and it didn't really matter which page of the screen - although I had a LOT of items.

On the most recent one, it happens on the very 1st key I press, and it was one at or nearly at the very bottom (since I picked up some items to trade and it appears most recently picked up items go at the bottom).

I will upload the save!

**Comment by tvm1** [comment]
I've just checked briefly with curses, while the game doesn't crashes for me, there's indeed something fishy going on - the game sets my notebook on fire for 15+ seconds while doing some odd magic with inventory letters, at least that's what can I see from gdb. I will investigate some more.

**Comment by gimlet90210** [comment]
Ahh yeah, a few days before that my inventory letters got kind of mucked up - I *think* it may have been when I used AIM to take off all clothing / drop all items in prep for putting on powered armor, and then put them all back on again.    Or from a version upgrade - it was also around the time I moved the save to a new build - sorry that makes it tough to narrow down .  Even some items I had assigned letters to got different letters, letters I had not assigned got the yellow color suggesting they had been, and now looking at it there are 2 "v" items being worn, yellow colored, and I'm 99.9% sure I never assigned them that (or any) letter (but I do fat-finger things a lot, so it's not *impossible*)

Also I do play tiles version, in case that makes a difference.

**Comment by tvm1** [comment]
Curses vs tiles make barely any difference, unless it's related to visual stuff. 

But, from the save I saw that you're really terrible hoarder!

As shown above, BevapDin fixed this.
