### ISSUE TITLE
Inconsistent AIM time costs when moving all items

### ISSUE THREAD

**Issue by BTAxis** [CleverRaven/Cataclysm-DDA#13205]
(Apologies if this is a known issue or, indeed, intentional; I am not integrated in the CDDA community.)

Moving items using "move all" takes more time than moving each item manually. With a single Long String, this is 6 seconds for manual versus 12 seconds for move all. As a player I would not expect these times to be different.
##

**Comment by BevapDin** [comment]
I'm just linking this with similar issues: #9392, #13131

**Comment by drbig** [comment]
Given this will be the third issue on the same topic - is anything blocking fixes here?

**Comment by VlasovVitaly** [comment]
I tested this on FirstKit
m - 6 sec.
M(any value) - 6 sec.
, - 6 sec.

**Comment by BTAxis** [comment]
I can corroborate that, but it still behaves as previously described with the Long String.

**Comment by Oskar636** [comment]
This is also a duplicate of #9392.
