### ISSUE TITLE
eyeglasses description / flag consistency wrt fire starting

### ISSUE THREAD

**Issue by pipehat** [CleverRaven/Cataclysm-DDA#13224]
Looks like eyeglasses were changed to intentionally remove their use in starting fires (except for reading glasses and monacles).

But the eyeglass description still suggests they could be used for 'focusing sunlight'. And they still have the LENS flag which claims (doc/JSON_FLAGS.md) it means the item can start fires.

Looking for clarification on intent. If glasses shouldn't be capable of starting fires then presumably we need to update the description and remove the LENS flag. Also, monocle and glasses_reading presumably need the LENS flag added.

attn: @i2amroy especially - b/c it looks like your change, a279830c2b16d8c1b73986c4fa185233e505359a, is where firestarter feature was removed) - can you help clarify?
##

**Comment by romkuma** [comment]
The PR text (#12063) is:

> As pointed out by DooMJake on the forums, it's glasses for the far-sighted that can be used to make fires, not for the near-sighted.

Looks like the removal was deliberate, but it needs documentation as you suggest.

Just did some testing with the reading glasses, and they work properly as firelighters now - only slightly worse than a lighter on a sunny day. Not sure the effect of adding the LENS flag.

**Comment by Soyweiser** [comment]
Seems like the descriptions of this are properly updated right now. So I think this can be closed. (as of 5201).
