### ISSUE TITLE
portable game system can be stored in boots

### ISSUE THREAD

**Issue by pipehat** [CleverRaven/Cataclysm-DDA#13228]
Probably unintentional. But the portable game system can be stashed in boots like a knife.

To reproduce:
1. activate boots (while having game system in inventory)
2. select 'Put a knife in the boot'
3. select the game system from the list of allowed 'knives'

Result:
Game system now stored in boots. Works just fine except it's probably unintentional.

Expected:
only proper knives should be allowed in boots

**Comment by Coolthulhu** [comment]
Portable game has the `"SHEATH_KNIFE"` flag, so looks like author intended it to be used that way.
Still, it doesn't really make sense.

Though knives in boots don't make much sense in general - they don't cause any encumbrance and can even store the giant survival knives.

**Comment by illi-kun** [comment]
It was added in #6927.

**Comment by drbig** [comment]
> (in case of gaming emergency)

Points for humour :)

**Comment by CptBrogan** [comment]
Machetes as well, IF, you're wielding it. I believe there's a boot storage glitch with wielded things, seem to remember other weird stuff going in them.
Note to self, try to boot a 30 g barrel

**Comment by illi-kun** [comment]
@CptBrogan wielded machete (any item, I suppose) appears in "Put what?" list but if you're actually trying do put it in you got notification that's not a knife, so I see no issue here.
