### ISSUE TITLE
Request:  Don't Autopickup if it will cause drop of other items in inventory

### ISSUE THREAD

**Issue by gimlet90210** [CleverRaven/Cataclysm-DDA#13231]
I've dropped and left behind gear I really would have preferred to keep, often from autopickups that have juuuust tipped the volume of a stack of ordinarily 0 volume items up to 1.   Yeah I know I should pay closer attention, but it's easy to miss it in the movement spam.
##

**Comment by kevingranade** [comment]
That's legit, it never makes sense to autopickup if that would cause you to
drop things (outside of a joke packrat trait ;).

**Comment by kevingranade** [comment]
The reason for this is as you said, Pickup::pick_one_up() calls player::can_pickVolume(int volume) with the item to pick up's volume, but if that is an item with charges that's under the 1 volume threshold, and it gets merged with an existing stack, taking that stack over the charges to add one volume, and then you drop something at the end of the turn.  The only fix I can think of for this is to refuse to pick up items that have this property when your current volume equals your volume capacity.

**Comment by narc0tiq** [comment]
If `can_pickVolume` finds a matching stack of count-by-charges items in the
player's inventory, it can simulate the merged item and determine the new
volume based on that. Along the lines of: subtract existing item's volume,
create new item with charges = old_charges + new_charges, add new item's
volume and compare with the volume capacity.

**Comment by kevingranade** [comment]
True, if we pass the item itself to can_pockVolume() it can do all the logic to make that determination.  Personally I'd rather have autopickup cut out a little earlier and keep things simple, and once we switch the volume unit to mL and enforce everything having at least 1 vol, everything will be simple and consistent.

**Comment by Oskar636** [comment]
I'm pretty sure this cannot happen anymore, correct me if I'm wrong.
