### ISSUE TITLE
Humvee's front wheels and engine are on an open frame

### ISSUE THREAD

**Issue by md000** [CleverRaven/Cataclysm-DDA#13239]
It seems that humvee has missing quarterpanels on front. I am pretty sure that it is intentional but can't find any resoning behind it.

**Comment by drbig** [comment]
Maybe because it looks better in ASCII? Like the SUV design.

**Comment by md000** [comment]
The SUV does have actual quarterpanels for its hood which block movement and hide the wheels, they are just aligned unusally, which does in fact looks awesome. 

In case of humvee, you can just walk from one front wheel to another straight through the engine. And, at least for me, it doesn't really look very appealing, with its H frames and open wheels.

**Comment by md000** [comment]
Picture for reference
![humvee](https://cloud.githubusercontent.com/assets/12977811/9181947/7b1a5f16-3fb0-11e5-9204-4f523af04a1b.jpg)

**Comment by md000** [comment]
Also, just noticed that both front headlights are on the quarterpanels behind the engine and the wheels, making the design very weird indeed.

**Comment by md000** [comment]
I just realised that these must have been radiator grills by idea. And instead of adding quarterpanels to front i should move the engine and wheels back. On it.
