### ISSUE TITLE
Inventory max volume issue when removing an item.

### ISSUE THREAD

**Issue by Shukka** [CleverRaven/Cataclysm-DDA#13243]
Not sure how to describe exactly so I'll just say what happens:
Inv volume at 64/68
Remove gas mask
"no space in inv...drop?", Yes
pick up gas mask
Inv volume at 68/68
Why force drop if I had the space?

Also, when answering No, "Invalid selection." seems an odd response.

Version 3539

**Comment by drbig** [comment]
@Shukka Try to replicate on latest experimental. There was a problem with inventory checks using `<` instead of `<=` and I *think* it was fixed.

**Comment by Shukka** [comment]
Tested Ver 3546
Same results

**Comment by tvm1** [comment]
Wearables check for the inventory capacity elsewhere, it's fixed now.
