### ISSUE TITLE
Jackhammer/ Jacqueshammer

### ISSUE THREAD

**Issue by RafeHaab** [CleverRaven/Cataclysm-DDA#13241]
Those two have the same description in different languages. One in english, the other in french.

We should make both items the same.

**Comment by Coolthulhu** [comment]
It's a joke item.

**Comment by illi-kun** [comment]
RafeHaab: see #988 & #1811

**Comment by chaosvolt** [comment]
Now we just need a boatmod part with a description in Norwegian... :V
