### ISSUE TITLE
Move action-pause prompt from "tired" to "dead tired". A.K.A. "You're tired. Annoy player? Y/Y"

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#13248]
"Tired" state has negligible penalties, it happens in negligible time after resting (depending on rest, might even be a single turn - even if it was on a proper bed!), and it already has a log message. Meanwhile "Dead Tired" has very high penalties and spams the log up. It would be welcome if "Dead Tired" prompted to pause activity while "Tired" did not.

**Comment by Zireael07** [comment]
Seconded.

**Comment by chaosvolt** [comment]
I would prefer an option to push it back according to player preference, if possible. I at least prefer to stop and sleep when hitting tired status, lest my character's sleep schedule get all wonky. That said, having the option to set the prompt further back would be nice.

**Comment by kevingranade** [comment]
The interruption mechanism is for something dangerous happening.
I agree the first level of tiredness doesn't qualify so we should have it
not happen until later.

**Comment by Skidborg** [comment]
On the other hand, I'm often just waiting for that "tired" status effect to show up so I can sleep and heal wounds.

**Comment by chaosvolt** [comment]
Exactly. Unlike hunger and thirst, not sleeping promptly can cause MORE long-term player annoyance than that interrupt prompt.

**Comment by tvm1** [comment]
So, we move this as option into user UI settings and disable it by default ?

**Comment by Coolthulhu** [comment]
I don't recall even a single time when that prompt was anything but an annoyance to me, like with weather change warnings.

> So, we move this as option into user UI settings and disable it by default ?

Could work. The same option could also enable/disable weather interrupts and damage-less pain interrupts.
Could also be a toggle rather than option, similar to safe mode.

**Comment by chaosvolt** [comment]
Oh hell yes, being able to disable weather interrupts would make my day.

Or it could be like Dwarf Fortress' options if I recall, where a number of different events can be set it different intensities.

If we could have the choice between no interrupt, full yes/no interrupt, and the in-between yes/no/ignore interrupt maybe?

**Comment by tvm1** [comment]
> Adding a distinction between being spotted by a regular zombie/moose/whatever and something that can harm you at range would add to the complexity though.

Yeah, there's currently no distinction between these creatures (from code's POV). Only thing that I can see that the annoying prompt would appear depending on whether the creature tracks or ignores the PC.

> Could work. The same option could also enable/disable weather interrupts and damage-less pain interrupts.
> Could also be a toggle rather than option, similar to safe mode.

Safe-mode toggle uses time based timeout before it reactivates. I can't see that working for weather, which can change quite quickly (eg., leaving/entering buildings).

> If we could have the choice between no interrupt, full yes/no interrupt, and the in-between yes/no/ignore interrupt maybe?

I see only two states:

1) Nothing at all, just msg in log that PC is tired (can be still stoped with '.')
2) Current Y/N prompt "You're tired, want to stop doing  X?"

If you want to ignore this,  for how long ? Some hours ? Maybe that makes sense too.

As I've said, PC being tired is mostly and indicator (for me) that my character wants sleep and that he will able sleep properly.

**Comment by Coolthulhu** [comment]
> Safe-mode toggle uses time based timeout before it reactivates. I can't see that working for weather, which can change quite quickly (eg., leaving/entering buildings).

No, I'm talking about "like safe mode", not tied to safe mode.
Simply another toggle, similar to run, safe mode or debug mode.

> If you want to ignore this, for how long ? Some hours ? Maybe that makes sense too.

Once. Just a single prompt that either appears (if we're in "interrupt at slightest provocation" mode) or doesn't.

**Comment by tvm1** [comment]
@Coolthulhu 

Ah, I understand now.

So, let's bind a key that switches between "annoying" mode and silent mode.

Things that will be omitted when in silent mode:

- Weather changes
- Character becoming tired
- Something else ?

**Comment by Coolthulhu** [comment]
As I said, damage-less pain would fit too. For example, for chemically unbalanced characters who can randomly get spikes of pain.
Possibly also "degenerative damage", like from ROT2/3 mutations.

**Comment by kevingranade** [comment]
Setting aside the possible other warning level, the safe mode notification
should only trigger on things that can kill the player, the first level of
tiredness definitely does not qualify.
I'm against additional options for this kind of thing in general, the
player shouldn't need to tweak notification levels, that's a sign that
we're simply notifying too much.

**Comment by chaosvolt** [comment]
Maybe. A single toggle between the way it is now and disabled would be adequate then.

**Comment by tvm1** [comment]
> I'm against additional options for this kind of thing in general, the player shouldn't need to tweak notification levels, that's a sign that we're simply notifying too much.

Move this stuff to log only then ?

There are some significant things (eg., PC getting terribly cold) where there is no notification either.

**Comment by kevingranade** [comment]
"A single toggle" is "additional options for this kind of thing".
If you're doing a long action and specifically waiting for the player to become tired, doesn't the "tired" notification pop up in the sidebar?  Just hit '5' when that happens and you're good.
Alternately, "do X until tired" would be a reasonable thing to add (when waiting, reading, etc), but not an interruption to every possible action, or an option to toggle that behavior.

**Comment by chaosvolt** [comment]
Hmm. I'm still in favor of "warn when tired" though, then again sleep schedule lunacy isn't that big an annoyance.

**Comment by gimlet90210** [comment]
I've just started to appreciate this warning as a recent convert to "sleep as soon as possible after tired" instead of waiting til dead tired (2+ more hours of wakefulness, for starters, whee!).

But yea I could live with the '5' interrupt, especially if there was some notification in the message area to catch my attention - maybe not quite as spammy as reading does with "dead tired".  And with the sound incoming, maybe a good time for a yawning sound or something else appropriate?
