### ISSUE TITLE
English homonyms & translation

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#13263]
So far I found two examples of words with similar spelling, but with different meanings which make translation of them difficult.
1) "Cat" in MONSTER_from_json.py as animal, and "cat" in game.cpp as abbreviation for "category";
2) "W" in advanced_inv.cpp as "West", and "W" in player.cpp as "Walking".

I think using of English homonyms should be avoided in future, after patching aforementioned situation (if possible).

**Comment by narc0tiq** [comment]
There must be a way to mark the different instances for gettext to know
they're separate. Also, it seems the issue is mostly with abbreviations,
which should pretty much always have `//~ translator comments` to point out
what they're abbreviating, otherwise things would get very confusing very
fast.

**Comment by BevapDin** [comment]
> There must be a way to mark the different instances for gettext to know
they're separate.

Yes, use `pgettext`, the first parameter is the context (free string, is included in the data for the translators, but is not include in the return value), second is the actual string to be translated:
```C++
foo = pgettext( "abbr. for some direction", "Nor." );
bar = pgettext( "abbr. for the country", "Nor." );
```

**Comment by VlasovVitaly** [comment]
Fixing of "Cat" will be easy.

But what about "W" problem... It's only one letter, how this can be translated? May be just remove it from translations?

**Comment by narc0tiq** [comment]
```C++
pgettext("Cardinal direction, west", "W");
pgettext("Character is walking", "W");
```

These would then show up in the .pot as the keys `"Cardinal direction, west^W"` and `"Character is walking^W"`, which is fairly standard, as I understand it (based on the comments for translators of Battle for Wesnoth at <http://wiki.wesnoth.org/GettextForTranslators>).

If I were to translate these to Romanian, the first would be "V" (for "vest", the Romanian word for "west"), and the second would be something like "N" for "viteză [N]ormală" (translation: "normal speed" -- there isn't a single simple word in Romanian for "walk", though there is a word for "run").

---

There's only so much magic we can do for translators, but we certainly can do well enough to give them a chance at a correct translation.
