### ISSUE TITLE
Item Action Menu does not close on ESC

### ISSUE THREAD

**Issue by BTAxis** [CleverRaven/Cataclysm-DDA#13279]
As per title. The Item Action Menu (%) cannot be closed with ESC, though the key binding menu accessed from the IAM does list ESC for "Exit screen". To my knowledge this is the only menu that will not close on ESC.

**Comment by drbig** [comment]
That whole menu is a mess:

![Item Action Menu](http://i.imgur.com/vCyaBgx.png)

I wonder what these multiple "Turn off" entries are supposed to do...

In any case the PR above will make the menu exit on any unbound key. I could hack it to exit only on hard-coded `ESC`/`space`/whatever combination, but honestly... The whole menu looks like it needs a big re-think and re-work (separate issue, separate PR(s)).
