### ISSUE TITLE
.22 CB round is not silent as advertised

### ISSUE THREAD

**Issue by BTAxis** [CleverRaven/Cataclysm-DDA#13277]
The .22 CB ammo description claims firing it is "nearly silent". Firing such a round produces 155 sound, and hearing debuffs can result from this. One suspects the description is in error.

**Comment by tvm1** [comment]
Yeah, this needs updating.. Ammo has no "loudness" property and guns have fixed loudness values.

**Comment by drbig** [comment]
So just changing the description would be an acceptable "fix"?

**Comment by Rivet-the-Zombie** [comment]
That would be a decent kludge, yeah.

**Comment by kevingranade** [comment]
A little bit of research indicates that a unsupressed .22 is loud enough to cause hearing damage, so while our hearing damage model is a bit off, .22 guns aren't *that* quiet.

**Comment by kevingranade** [comment]
My bad, I was looking at sources that ignored CB, a little more reading reminded me that it's a mildly exotic round that in fact is super quiet.

**Comment by drbig** [comment]
Closed by #13334.
