### ISSUE TITLE
Cygwin x86 and std::to_string

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#13286]
So, it's a pretty [well-documented bug](http://www.cygwin.com/ml/cygwin/2015-01/msg00049.html) with Cygwin that `std::to_string` isn't a thing that exists.

Which is kiiiiind of a problem for CDDA, because src/item_group.cpp:470 has a call to `std::to_string`.

And commenting out `std` or `std::` on that call (i.e. so that it's `::to_string` [anonymous namespace] or `to_string` [local namespace]) results in:

```
src/item_group.cpp: In function ‘Group_tag get_unique_group_id()’:
src/item_group.cpp:470:83: error: call of overloaded ‘to_string(unsigned int)’ is ambiguous
         const Group_tag new_group = unique_prefix + /*std*/::to_string( next_id++ );
                                                                                   ^
src/item_group.cpp:470:83: note: candidates are:
In file included from src/rng.h:4:0,
                 from src/item_group.cpp:3:
src/compatibility.h:29:20: note: std::string to_string(long int)
 inline std::string to_string(long const n)
                    ^
src/compatibility.h:38:20: note: std::string to_string(int)
 inline std::string to_string(int const n)
                    ^
src/compatibility.h:47:20: note: std::string to_string(double)
 inline std::string to_string(double const n)
                    ^
g++  -DCATA_NO_CPP11_STRING_CONVERSIONS -DLOCALIZE -ffast-math -Wall -Wextra -g  --std=c++11 -MMD -D_XOPEN_SOURCE=600 -c src/ammo.cpp -o obj/ammo.o
Makefile:477: recipe for target 'obj/item_group.o' failed
make: *** [obj/item_group.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
```

I'm *assuming* this is because `next_id` is an `unsigned int`, which isn't the same thing as a `long int` or a plain (signed) `int` or a `double`, hence the ambiguous overload (i.e. `unsigned int` doesn't explicitly, exactly match any of the parameters in any of the overloads).

**Comment by Griffinhart** [comment]
Hm, yeah. Adding a new `to_string` overload to src/compatibility.h (well, more like "copying the existing `int` overload for `to_string` and replacing `int` with `unsigned int`") fixes the ambiguous overload error, but doesn't fix the part where I still have to remove the `std` from `std::to_string` in the call on src/item_group.cpp:470.

Also, not actually sure if the new overload actually works as intended, beyond working around the ambiguous overload error. (I.e. I'm *assuming* that `constexpr int size = std::numeric_limits<unsigned int>::digits10 + 2` is the correct math, based on the `long` and `int` overloads, but don't ask me to prove it.)

**Comment by i2amroy** [comment]
You could always just do something like this:
```C++
#include <string>
#include <sstream>

namespace std
{
    template < typename T > std::string to_string( const T& n )
    {
        std::ostringstream stm ;
        stm << n ;
        return stm.str() ;
    }
}
```

**Comment by Griffinhart** [comment]
Sure, but copypasting an existing function and making minor alterations to suit the minor difference was faster for testing my hypothesis of "this fails because `unsigned int` isn't the same thing as `long` or `int` or `double`".

Although that *does* beg the question of why CDDA isn't already doing a templated overload instead of having multiple, unique overloads.

(Also, isn't `namespace std` redundant with `std::string to_string`? It probably isn't, I just need to wake up. Or go to sleep.)

**Comment by i2amroy** [comment]
>(Also, isn't namespace std redundant with std::string to_string? It probably isn't, I just need to wake up. Or go to sleep.)

Certainly possible, I was just sketching that off the top of my head without any real checks.

**Comment by Griffinhart** [comment]
Thinking about it some more (and consulting with a friend), shouldn't [ADL](https://en.wikipedia.org/wiki/Argument-dependent_name_lookup) take care of this whole `std::to_string` issue if you just write a templated overload for `to_string` in a project-local namespace (i.e. outside in the `std` namespace, like how the current `to_string` overrides in compatability.h already are) and make calls to unqualified `to_string` (instead of `std::to_string`)?

Like, if my/our understanding of ADL is correct, ADL will try for things inside of the `std` namespace first (meaning on platforms where `std::to_string` is a thing that exists for the given parameter type, `std::to_string` will be invoked) because the return type (`std::string`) is in the `std` namespace; and if `to_string` doesn't exist in `std`, then the project-local `to_string` will be invoked.

**Comment by BevapDin** [comment]
ADL is *argument*-dependent lookup, but the argument to `to_string` is a built-in type (int, long, float, whatever), which does not reside in any specific namespace. ADL would find `std::to_string`, if the functions is called with a `std::string` as argument, or anything else that resides in the std namespaces.

Regarding the example from i2amroy above. `std::` inside the namespace `std` redundant, just `string` and `ostringstream` is fine (it's even a bit dangerous, there could be a `std::std::` namespace). Note that adding things to the namespace std is technically undefined behavior.

Btw. this compiles on gcc: `return (ostringstream() << n).str();` - but it's kind of cryptic.

**Comment by Griffinhart** [comment]
Ah, hm.

My thinking is that the problem isn't in compatibility.h (well, I mean, other than the missing overload), but it's with that specific call to `std::to_string` in item_group.cpp.

Since, see, the `to_string` overloads in compatibility.h aren't in the `std` namespace, meaning that the call to `std::to_string` will *never* be to those specific overloads.

The work around for having to comment out the scope qualifier on `std::to_string` in item_group.cpp would be to stick `using std::to_string` somewhere in item_group.cpp and make unqualified calls to `to_string`, which should then resolve this build issue on Cygwin, and shouldn't (assuming the ifdefs in compatibility.h aren't wrong) affect other platform builds.

**Comment by kevingranade** [comment]
In general, I'm strongly against 'using std*', all calls to it should be
namespaced with 'std::' to avoid confusion.
I'm not following why injecting a local to_string() into the std namespace
is bad, it's *supposed* to be there, we're working around a platform
deficiency by adding it.
Ideally we can check to see if it's defined, and define it only if it isn't
already.  Not sure how that's handled right now and on the bus so checking
it is a pain.

**Comment by i2amroy** [comment]
>I'm not following why injecting a local to_string() into the std namespace
is bad, it's *supposed* to be there, we're working around a platform
deficiency by adding it.

As far as I know the "adding to the std namespace is undefined" thing is more something that gets thrown around to point out the fact that stuff can get crazy if a future update messes with that bit of standard code, rather than a "this is a real bad thing to do and you shouldn't ever do it", type of undefined.

>It occurs to me that, given that this bug should've cropped up long before my bug report, I might be literally the only person who compiles CDDA with Cygwin.

It was one of the problems I had to roughly address in my attempts to get CLion working through Cygwin instead of MSYS2 though, so it is important.

**Comment by Griffinhart** [comment]
I've got a fix, just unfucking some things on my end to put together a PR.

**Comment by chantisnake** [comment]
uses Cygwin64 `to_string` function still do not work...
![capture](https://cloud.githubusercontent.com/assets/10100995/11759290/8a8d8d24-a045-11e5-864a-f119d3177290.PNG)
![capture1](https://cloud.githubusercontent.com/assets/10100995/11759291/8cbddc84-a045-11e5-9088-849c313b578f.PNG)

**Comment by Griffinhart** [comment]
You need to `#include <string>`; `to_string` isn't defined in `iostream`.

**Comment by chantisnake** [comment]
<img width="672" alt="capture" src="https://cloud.githubusercontent.com/assets/10100995/11798448/e4941ce8-a298-11e5-8326-5b779a98d8f6.PNG">

sorry about the inconvenience, but it is not working here. Did I do anything wrong?

**Comment by Griffinhart** [comment]
`to_string` is in the `std` namespace, so you'll need the scope resolution operator. (`std::to_string(1)` instead of `to_string(1)`, as it were.)

Note that this is for standard `to_string`; CDDA has its own implementation (inside `src/compatibility.h`).

Also, I'm not 100% sure that Cygwin *has* a standard `to_string` implementation. (I know it's been a sticking point of Cygwin for a while now, not sure if it's been resolved.)
