### ISSUE TITLE
An overlay tile for effects like poisoned, drunk and tired.

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#13293]
I think it would be a great addition to the game if we could have an overlay for effects from effects.json. I'd really like to tile tired, drunk, poisoned, and lots of the other effects that can befall your character and NPCs. 
##

**Comment by drbig** [comment]
I concur. Classical little icons for statuses!

**Comment by illi-kun** [comment]
Do not forget to update the tilesets with this new feature implemented!
