### ISSUE TITLE
Can we make enegry weapon blast not to cause flame field but other effect?

### ISSUE THREAD

**Issue by vipches** [CleverRaven/Cataclysm-DDA#13296]
We have FTK-93 fusion gun, fusion blaster rifle, Boeing XM-P plasma rifle, NX-17 charge rifle, but thing is, those weapon will cause target area ignite flames, do we really have to make flame field only but not other elements? can't we make a power surge, so the targer area will leave some electric cloud or something? or the fusion blaster rifle cause target area relase some airborne incendiary? and even make NX-17 cause a huge shock wave to blow away monsters, player and npcs? can we just make those weapon not only flame? we can't even control the flame with the fire extinguisher right now, unless some one has improved the extinguisher which it can release some extinguishing gas or something?

**Comment by vipches** [comment]
I think I make a issue in a wrong place, I have to going on forums to send this.

**Comment by kevingranade** [comment]
We can change the effects, but outside of a worthwhile and specific suggestion we're not going to.
Please don't open issues with a bunch of vague questions.
