### ISSUE TITLE
Petrol Generator

### ISSUE THREAD

**Issue by JimboJamerson** [CleverRaven/Cataclysm-DDA#1329]
I'm thinking there should be a way to hook up your welder, lights, fridges and other gizmos with petrol generators or solar power generators. Really help make your home base more permanent.

**Comment by mugling** [comment]
Covered in a number of other issues. We have a portable generator vehicle now. Wiring of household appliances is `WONTFIX` due to the extreme complexity (especially with reality bubbles)
