### ISSUE TITLE
Oxygen doesn't counter drowning

### ISSUE THREAD

**Issue by Rainboww** [CleverRaven/Cataclysm-DDA#13308]
On the latest experimentals (3577) using emergency oxygen, oxygen tanks, or any oxygen doesn't counter drowning underwater and doesn't refill the player's oxygen levels, though it feels like it should.

**Comment by Rivet-the-Zombie** [comment]
Those are medical oxygen systems. They're not the same sort of oxygen tanks that SCUBA divers wear.

**Comment by Coolthulhu** [comment]
Maybe it should fail on usage, though. If it could be used, it would refill oxygen.

**Comment by Zireael07** [comment]
@Rivet-the-Zombie: Do we have SCUBA oxygen tanks at all?

**Comment by Rainboww** [comment]
It might not be anything like what divers use, but if you somehow managed and were stupid enough, you could still survive underwater with medical oxygen just the same.

**Comment by Rivet-the-Zombie** [comment]
The most obvious problem is that the mouthpiece on a medical oxygen tank wouldn't keep water out, so there's no way you'd be capable of using it underwater.

>Maybe it should fail on usage, though.

Good solution.
