### ISSUE TITLE
Membrane oxygenator CBM still gives drowning messages

### ISSUE THREAD

**Issue by Rainboww** [CleverRaven/Cataclysm-DDA#13309]
Latest experimental (3577), going underwater with the membrane oxygenator CBM still displays drowning popups once you run out of 'normal' oxygen, though it takes power instead of health. This might be fine to simulate that you still have the feeling of drowning, but gameplay-wise it's extremely annoying to have to close the popup manually every tile you move - I would suggest either removing the message with the CBM and sufficient power, or at least just moving it to the normal text output instead of a seperate popup.

**Comment by Barhandar** [comment]
IRL, if the carbon dioxide is being removed from blood, you won't feel suffocating even if you're breathing anything _but_ oxygen and are dying. Conversely, if it's not being removed but oxygen is still being supplied, your body will panic with possibly deadly effects like passing out (in water!) and blood can develop acidosis, which is deadly as well.

**Comment by drbig** [comment]
> it's extremely annoying to have to close the popup manually every tile you move - I would suggest either removing the message with the CBM and sufficient power, or at least just moving it to the normal text output instead of a seperate popup.

"A membrane oxygenator is a device used to add oxygen to, and remove carbon dioxide from the blood." [Wiki](https://en.wikipedia.org/wiki/Membrane_oxygenator). No messages with sufficient power then...

**Comment by drbig** [comment]
Mhm, there is already code there that suppresses the popup if you have enough power left (`>= 25`). Check with current experimental? (3582).

**Comment by Rainboww** [comment]
Will check now.

**Comment by Rainboww** [comment]
Just tested with 3580, which is as of now the latest tiles build vailable - just waiting gives no message and makes energy move down, but moving a tile still gives the warning popup every single step you take, starting when (i assume) you run out of normal oxygen.
