### ISSUE TITLE
rechargable/UPS add-ons gain weight as if they had batteries

### ISSUE THREAD

**Issue by gimlet90210** [CleverRaven/Cataclysm-DDA#13306]
I was hoping, along with the other benefits,  to save the weight of batteries by installing the  rechargable/UPS powered add-ons to battery powered tools, but as they charge the item gains weight just as if it had that many batteries installed.

Minor, but  a bit annoying 'cause all that weight does add up...

**Comment by narc0tiq** [comment]
This is also noted as #12764 and we definitely agree: batteries make item weights weird in general -- rechargeable items are even more so. For now, I'll just close this as duplicate, but do keep track of that other one; I'm sure if something changes, it'll be noted there.
