### ISSUE TITLE
Various navigational keys register as different keys

### ISSUE THREAD

**Issue by BTAxis** [CleverRaven/Cataclysm-DDA#13305]
It appears some of the keys on my keyboard, these being PageUp, PageDown, Home, End and Delete are registering as other keys: 'S', 'R', ' ', 'h' and 'Q' respectively.

I first noticed this behavior in the Eat menu. I wanted to scroll the list using PageUp and PageDown, but my character kept attempting to eat her crossbow. As it turned out, the crossbow was assigned to 'R'. Clearing 'S' and 'R' from the inventory does allow me to scroll the list in the Eat menu. Additionally, when rebinding keys in the keybindings menu, PageUp and PageDown properly register as NPAGE and PPAGE, though in the inventory screen I can use them to assign items to 'S' and 'R'.

I am playing on Windows 8, CDDA version 79ddb5b with tiles.

**Comment by narc0tiq** [comment]
Ordinarily I'd guess at this being an issue with a terminal emulator, but we're the ones emulating the terminal! Definitely something that needs fixing.
