### ISSUE TITLE
vehicle tool parts aren't considered when checking crafting requirements

### ISSUE THREAD

**Issue by pipehat** [CleverRaven/Cataclysm-DDA#13317]
Expected:
- Welding Rig should satisfy welder tool requirement
- RV Kitchen Unit should satisfy hotplate tool requirement

Problem:
Standing next to one of the above (unbroken) parts in a powered vehicle, they can be 'e'xamined to interact with their tool capability but they are ignored when checking tool requirements. E.g. 
- cannot craft clean water with RV Kitchen Unit as the hotplate.
- cannot repair vehicle using welding rig (no 'powered welder')

**Comment by Rainboww** [comment]
I noticed this in a recent build but it was fixed right afterwards - try updating to latest?

**Comment by pipehat** [comment]
yeah just noticed that, recompiling now to confirm, gimme 10 mins

**Comment by pipehat** [comment]
yep it's fixed now in latest revision. Disregard!
