### ISSUE TITLE
Explosions consistently destroying everything valuable in certain areas

### ISSUE THREAD

**Issue by Rainboww** [CleverRaven/Cataclysm-DDA#13311]
First of all - I know this has been brought up many times, but I couldn't find anything on it so I assume it's never been actually reported - if I'm wrong and/or blind, I apologize.

Latest experimental (3577), certain lab finales (with secubots and loot on the floor not protected by reinforced glass walls) consistently have their rewards completely destroyed by secubots suiciding on the dissectors before you even get near the room. Similarly, military outposts have theirs destroyed by either explosions from grenadiers getting shot by turrets once you get it in your reality bubble, or the actual turrets (because there's very little opportunity to approach otherwise).

It might be realistic, but from a gameplay POV it's extremely annoying since it often renders a long travel through a lab completely without reward. Suggestion: protect the lab finales with reinforced glass similar to the CBM finale (would even work without terminal - players can find a way), though I'm not sure how to deal with the outposts apart from maybe locking the grenadiers inside without an easy way for them to break out (metal door, maybe?)

**Comment by drbig** [comment]
Kind of mentioned in #12943. Perhaps labs need some layout/spawns rework now.

**Comment by Coolthulhu** [comment]
Explosion damage vs items got nerfed a fair bit
