### ISSUE TITLE
Chainsaw-On badly behaving on Cutting Trees and Chopping Trunks(Chop Log)

### ISSUE THREAD

**Issue by Stevensonz** [CleverRaven/Cataclysm-DDA#1331]
So I was thinking that the chainsaw would be better and faster than a silly stone/wood axe and yet the chainsaw takes more time as it somehow bugs out by it continuously being on and using gasoline (I.E a 1-10 charge chainsaw would do it faster than full tank one)

Here is a log of me cutting up trunks(Chop-up log) with a chainsaw-on
![bad chainsaw](https://f.cloud.github.com/assets/4349651/596634/115b501c-cbae-11e2-946a-163c0bd0cc3f.png)
##

**Comment by Leland** [comment]
This is one of the oldest open issues in the repo! I'm closing this for now, but if there's still interest by anyone, let me know here and I'll reopen; or feel free to make a new issue.
