### ISSUE TITLE
Stairs in lab armory

### ISSUE THREAD

**Issue by Rainboww** [CleverRaven/Cataclysm-DDA#13312]
Latest experimental (3577), a small suggestion: As said in https://github.com/CleverRaven/Cataclysm-DDA/issues/13127 , it's intentional that it's very hard to get into the armory, but would it be possible for the inner terminal to unlock the door to/from the next room? It would help with being able to continue if, for example, there's a stair leading towards the actual armory and it's the only way to continue.
##

**Comment by kevingranade** [comment]
The bug here is that there are stairs leading into the armory at all.

**Comment by Rainboww** [comment]
If that's a bug, then fair enough - that'd render the whole thing moot anyway.

**Comment by drbig** [comment]
Seems to be same deal as with #13008. I wonder if hacking these cases is worth it given proper 3D levels will ensure a lot of this can't happen (I think?).

**Comment by Leland** [comment]
Closing this in favor of the master science lab issue #10958.
