### ISSUE TITLE
Common cold and health messages

### ISSUE THREAD

**Issue by Rainboww** [CleverRaven/Cataclysm-DDA#13314]
Latest experimental (3577), when you have the common cold and high base health, generic 'healthiness' messages still popup when waking up, which is slightly ridiculous since many of them state things like 'all the little sores from yesterday are gone' 'you feel very good' etcetera, even though your stats, morale and coughing clearly tell otherwise.

**Comment by drbig** [comment]
Will PR a fix soon. I wonder if anything else should go along common cold and flu though.
