### ISSUE TITLE
Allow erasing of graffiti

### ISSUE THREAD

**Issue by BTAxis** [CleverRaven/Cataclysm-DDA#13329]
I am in a position where I would like to remove some graffiti, but I haven't found a way to do so. It is possible to remove writing from an item by inputting '.', but the same is not true for writing applied to terrain.

**Comment by drbig** [comment]
Realism-wise I'd rather see you "overwrite" graffiti. We could agree that you can "erase" the graffiti by simply making a square to cover it (so you use spray can charges, but the terrain becomes clear writing-on-wise).

**Comment by BTAxis** [comment]
I did in fact overwrite the graffiti by changing the text to ' '. The problem is that every time I step into the square, the message log will still inform me something is written there.

I wrote it in charcoal, by the way.

**Comment by drbig** [comment]
Uhh, charcoal or chalk should probably disappear on its own rather sooner than later... For simplicity we can overlook it though. And yeah the fix should make writing '.' effectively clear the tile.
