### ISSUE TITLE
Multitile water not showing properly when it meets deep water.

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#13347]
The multi-tiles we have for shorelines show up when they meet corners deep water, as seen in this picture.

http://i.imgur.com/yUgwHkx.png
##

**Comment by Soyweiser** [comment]
Related forum thread: http://smf.cataclysmdda.com/index.php?topic=12755.0

**Comment by Leland** [comment]
@Chezzo this was fixed by #18266, right?

**Comment by Chezzo** [comment]
Yes, that is correct @Leland.
