### ISSUE TITLE
Asset licenses?

### ISSUE THREAD

**Issue by kozross** [CleverRaven/Cataclysm-DDA#13340]
Are your assets licensed the same way as you code, or differently?

**Comment by drbig** [comment]
Everything is under CC-BY-SA 3.0, with the almost-exception of the square.ttf font which is under CC-BY 3.0 (which has been simply imported here for convenience).

**Comment by kevingranade** [comment]
Unless something specifically says otherwise (some headers we've imported have different licenses, I don't think any assets except the square font have a different license), they're CC-BY-SA 3.0.
