### ISSUE TITLE
boeing plasma rifle too dangerous to be useable

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#13358]
Depends on size of explosion, you can be caught in your own explosion even if you aim it as far away as possible

**Comment by aierce** [comment]
recommend removing "explosives" flag

**Comment by kevingranade** [comment]
You can use it at max range -4 with negligible chance of being hit.
At max range, I don't know what you're doing to get hit, did you burst-fire it?  If that's the case you might have missed by a lot at some point and hit something closer to you.

**Comment by kevingranade** [comment]
Closing as I could never get the gun to hurt me when fired at max range, or even max range -4.
