### ISSUE TITLE
Scenarios with professions that only cost points don't properly subtract.

### ISSUE THREAD

**Issue by Metallumere** [CleverRaven/Cataclysm-DDA#13367]
What it says on the tin, this is currently happening for me on build 3599
For example, you have the default 6 points to spend. You select The Last Firefighter as your scenario, 
you then go over to the Professions tab to see that the currently selected profession(Firefighter) costs 2 points, but you still have your default 6.
If you then switch to the only other profession you can pick from that(Bionic Firefighter) which costs 5 points, you will find you then have only 3 points remaining, as if you had 8.

It seems that it gives you the points from Firefighter, when it should actually be taking them, and this seems to happen with any other scenario that only has professions that cost points, such as Assault On Precinct Z.

EDIT: I should add: It seems that selecting the Ambush scenario causes the profession Hardened Survivor to be selected by default, if you then select the plain-old Survivor, you then go from having 6 points to spend to 12.

**Comment by DeNarr** [comment]
You realize some scenarios give you extra points, as they are meant to be a disadvantageous start. In some cases the default profession may be counteracting the bonus though, making it seem as if it doesn't give a bonus.

**Comment by Metallumere** [comment]
Right. But You can plainly see that The Last Firefighter costs 0 points, and the cheapest profession it gives you costs 2, and though both are correctly selected, you still have your default points to spend.

**Comment by DeNarr** [comment]
I think you may have missed my second sentence. The Last Firefighter is actually worth 2 points. However, since the cheapest profession cost 2 points, it shows up as being worth 0 points. That's also why the Bionic Firefighter only costs 3 points to switch to, as you would be switching from a 2 point profession.

**Comment by drbig** [comment]
> However, since the cheapest profession cost 2 points, it shows up as being worth 0 points. That's also why the Bionic Firefighter only costs 3 points to switch to, as you would be switching from a 2 point profession.

That does make sense. Maybe it's just not conveyed clearly enough? (making this an UI issue)

**Comment by Metallumere** [comment]
If that is so, it does not say that cost in the files. It definitely says 0.

**Comment by DeNarr** [comment]
@Metallumere That's because it gives the default professions for "free", so it's balanced out by setting the points to what you want it to be while taking that into consideration. So if you wanted every scenario to show how many points they actually give, then the default profession for each would need to be a 0 cost profession.

**Comment by Metallumere** [comment]
Alright, if this is indeed intentional behavior, i'm closing the issue. Thanks!

**Comment by Rivet-the-Zombie** [comment]
The first pr4ofession listed under a scenario will always be the 'default' profession for that particular scenario. Check out how the sheltered scenario affects your points if you select the basic survivor profession - it gives you some more points.

On the one hand this can be less than intuitive for folks who are new to designing scenarios/professions, but on the other hand it gives you an extra layer of difficulty adjustment for your scenario's challenge.
