### ISSUE TITLE
Are stethoscope spawns too rare?

### ISSUE THREAD

**Issue by CptBrogan** [CleverRaven/Cataclysm-DDA#13364]
Suggested fix, new items. Chalk board, chalk, and a "just for fun" religious text titled "RnJesus, debugging and you."

**Comment by drbig** [comment]
Please rephrase both the title and the description - I can't make any sense of what it is supposed to be about. Also "joke" issues aren't very welcome (if it was supposed to be one).

**Comment by chaosvolt** [comment]
I am assuming from the issue name that stethoscopes are hideously rare spawns. Which, well, they are. In all the games I've played, I've NEVER seen one spawn naturally. Lemme check the item groups...

**Comment by vache** [comment]
Jacks are super common in the trunks of cars.

**Comment by chaosvolt** [comment]
Not quite. They're juuust at the point where some games I'll find plenty, and some games I'll scour a whole town and only find them into two trunks.

**Comment by gimlet90210** [comment]
Stethoscopes can spawn in hospitals too.  I don't have a problem with the rarity - they're the gateway to some VERY nice items in banks and safes.

**Comment by kevingranade** [comment]
PEBKAC

**Comment by chaosvolt** [comment]
You aren't getting into the bank vaults without computer skill or an acetylene torch, and other gun safes are rare.

Thing is, they SHOULD be at least uncommon in doctor's offices. Instead the smaller number of calls to that itemgroup, plus the uncommon nature of doctor's offices, PLUS their small size relative to hospitals, all combine to make doctor's offices almost never have even one stethoscope.

And realistically, even a small-town clinic can afford to have at least one bloody stethoscope.

**Comment by kevingranade** [comment]
> Bloody stethoscope

Someone used it as a weapon before being overrun?

**Comment by chaosvolt** [comment]
Call it tactical triage. XP

**Comment by chaosvolt** [comment]
In any case, there are two possible solutions. Aside from bumping up the item weight of stethoscopes slightly in the doctor's office item group. another option might be to add a basic selection of medical tools as a possible spawn in ambulances. They already spawn with assorted medical supplies, but nothing like scalpels, splints, or...um...not sure what other items are already in-game that'd qualify as medical TOOLS rather than supplies.

**Comment by Zireael07** [comment]
+1 to adding medical tools to ambulances. Splints, scalpels, stethoscopes would definitely be used in them - and left as the apocalypse hit.

**Comment by drbig** [comment]
> +1 to adding medical tools to ambulances. Splints, scalpels, stethoscopes would definitely be used in them - and left as the apocalypse hit.

That does make sense.

Btw. I still have no idea what the original issue is about :/

**Comment by chaosvolt** [comment]
> Btw. I still have no idea what the original issue is about :/

The OP seems to have implied their difficulty in finding a stethoscope was such that they had to debug for it. :V

**Comment by drbig** [comment]
> The OP seems to have implied their difficulty in finding a stethoscope was such that they had to debug for it. :V

I'd prefer the issues not need a translator :|

But OK, I agree with you lot :)

**Comment by chaosvolt** [comment]
Was a smartassed way of putting it, ja.

**Comment by illi-kun** [comment]
> +1 to adding medical tools to ambulances. Splints, scalpels, stethoscopes <...>

I'll do that during this weekend, it will be easy.

**Comment by chaosvolt** [comment]
Ah, will be good to see that.

**Comment by Rivet-the-Zombie** [comment]
Please don't give us nonsensical issue titles in the future. We can't fix it if we can't figure out what you're reporting in the first place.

**Comment by chaosvolt** [comment]
Moral of the story: if you're gonna be a smartass when naming an issue, at least make it comprehensible.

**Comment by Rivet-the-Zombie** [comment]
I like amusing titles for issues/PRs, I just don't like it when they try so hard to be funny that it becomes incomprehensible.

**Comment by chaosvolt** [comment]
Exactly. Keep it sane, basically.
