### ISSUE TITLE
Sometimes tests fail with out-of-bounds error

### ISSUE THREAD

**Issue by Maykeye** [CleverRaven/Cataclysm-DDA#13369]
Sometimes while running catatest it will fail with message like 

    % ./tests/cata_test
    /usr/include/c++/4.8/debug/vector:346:error: attempt to subscript container 
        with out-of-bounds index 21, but container only holds 0 elements.

    Objects involved in the operation:
    sequence "this" @ 0x0x24e2b30 {
      type = NSt7__debug6vectorINS0_I8tripointSaIS1_EEESaIS3_EEE;
    }

-----

AFAIU this is because when test_main generate world map, `g->m.load( g->get_levx(), g->get_levy(), g->get_levz(), false );` uses map instance which is not yet aware of traps: when game::game initializes map, map constructors does `traplocs.resize( trap::count() );`. But because traps are not yet loaded, traplocs still holds zero elements. 

By the time g->m.load is called, all traps information is loaded. When  

            // inside of map::loadn, which is called from map::load
            tinymap tmp_map;
            tmp_map.generate( newmapx, newmapy, gridz, calendar::turn );

generates map, tmp_map has full access to loaded traps and can place them. Then during map::actualize call, function tries to access trap_locs of original map which holds 0 elements.

-----

Game uses game::setup() which reinits map (`m = std::move( map( static_cast<bool>( ACTIVE_WORLD_OPTIONS["ZLEVELS"] ) ) );`) so it doesn't happen in the game, only in tests.

Also game::setup popups up window so it can't be called from tests that do not initialize curses.

I'm not sure if it's better to refactor game::setup to make it work without curses or simply reinit in test_main map as setup does  and hope that it's thing that necessary from setup()

**Comment by drbig** [comment]
Never run across any issues with tests. Care to elaborate on your setup? Linux, GCC 4.8.x? Which CDDA version exactly? Also you might try checking when compiled with `clang`.

**Comment by Maykeye** [comment]
Latest experimental with gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

**Comment by kevingranade** [comment]
I've seen this too, I think it happens when a test run tries to use a world
created by a previous test run.  Possibly two issues here (not necessarily
bugs). One is that the unit test exe doesn't make a fully populated world
directory. The second is that on exit those worlds are not removed.
There's a potential third issue, I'm not sure if the unit test exe will
work right if there are no existing worlds.

**Comment by drbig** [comment]
> The second is that on exit those worlds are not removed.

They are removed on successful runs since #13232.

As for the rest well... it all works all green here.

**Comment by Maykeye** [comment]
I found an easy way to reproduce: 
in data/json/regional_map_settings.json  file, change `map_extras/field/chance` from 90 to 5. Change `mx_portal` from 3 to 30000. This will cause map generator to place a lot of portals which will trigger the error
