### ISSUE TITLE
Sewing your own pockets into clothing. 

### ISSUE THREAD

**Issue by adrianrieck** [CleverRaven/Cataclysm-DDA#13365]
If one has a tailor kit you can line a clothing item with wool to increase warmth or pad it with leather to increase protection. How about allowing the user to sew in their own pocket. To keep it realistic, I think volume should be tied to the coverage % of the body part that the clothing is worn on.  For example creating a pocket for short pants may only allow for 4 extra volume but creating a pocket for a long pants would allow 10 extra volume. Pockets should also increase encumbrance.

**Comment by Coolthulhu** [comment]
It was once a thing, but it was removed because no one could come up with a good formula for storage and encumbrance.

**Comment by drbig** [comment]
Which of course doesn't mean someone someday will get a decent formula for it. See: #11365 and #11345 (for starters).

**Comment by kevingranade** [comment]
Closing as we don't have a way forward with it, if you have an idea for how to make it work, open an issue with a specific idea.  Please address all the issues raised in #11365, if some are not addressed it's not going to happen.
