### ISSUE TITLE
Character creation UI changes

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#13372]
(This came up from #13367 discussion)

Proposed changes:

1. Reorder tabs to: Scenario, Profession, Stats, Traits, Skills, Description.
 - Rationale: You need to select scenario and a profession, the first limits the second so having it close makes sense. Stats are actually most important so they go next, then completely optional traits and skills.
 - Question: shouldn't traits go before stats as there are actually the place where we all "tweak" our remaining points?
2. Print the default profession when selecting scenario
 - As the player is never told anywhere that "scenarios include points for their default profession" it might be good to convey it here.
3. Add an indicator for sorting mode to Scenario and Profession
 - It's in but I guess most players are unaware of it

There is definitely space for 2. Squeezing 3 might be more "fun".

Also this is a DISCUSS! issue - suggestions are very welcome.

**Comment by Coolthulhu** [comment]
> Question: shouldn't traits go before stats as there are actually the place where we all "tweak" our remaining points?

Makes sense to me.
While traits change (mutations), they're less "fluid" than stats, whose importance is strongly dependent on skills, effects, CBMs etc.
Alternatively, it could be explained as: character archetype first, then details, finally just number tweaking.

Traits aren't much more optional than stats. The 12 points from traits are more than most scenario+profession combos give. Any optimized character will take them, as will any "flavorful" one.

**Comment by Rivet-the-Zombie** [comment]
I'm with Coolthulhu on this; stats and skills should come last since they're usually the place where you round out your character with leftover points.

**Comment by drbig** [comment]
Aye, the order is then: Scenario, Profession, Traits, Stats, Skills, Description.

I'll probably (try) to PR something addressing this tomorrow local time, but suggestion on all aspects are very welcome still.
