### ISSUE TITLE
Maid clothing layering issue

### ISSUE THREAD

**Issue by Esdian** [CleverRaven/Cataclysm-DDA#13370]
When starting with the Maid profession, the layering on your clothing is kind of odd. Undergarments, outside of their Maid outfit. 
http://i.imgur.com/N1jcegN.png For reference.  Not major, But odd, Very odd.

**Comment by drbig** [comment]
Unless that is intentional... I wonder if the order of clothes in JSON would be enough to fix it.

**Comment by kevingranade** [comment]
If the clothes are in an array '[ ]', yes, if they're in an object '{ }' no.
Better fix is having the code that wears clothes put them in the right
order by default.  This is a feature we want in general too.

**Comment by drbig** [comment]
http://kaer.eu.org:8112/#blob:profession/maid - an array. So it seems to be an easy fix!

> Better fix is having the code that wears clothes put them in the right
order by default.  This is a feature we want in general too.

That looks to me like overdoing it. Use arrays and keep the order in code when wearing.

**Comment by kevingranade** [comment]
I mean when the player wears something manually, we want it to be placed at
the correct layer by default.  Then this would be re-used for the character
creation code.

**Comment by drbig** [comment]
> I mean when the player wears something manually, we want it to be placed at
the correct layer by default.  Then this would be re-used for the character
creation code.

Does make sense. Separate thing from this here though :)
