### ISSUE TITLE
Can close vehicle doors while standing on them

### ISSUE THREAD

**Issue by Ishindri** [CleverRaven/Cataclysm-DDA#13388]
Win 7 x64 w/tiles, build 0.C-3590.  As per the title.
##

**Comment by drbig** [comment]
Check current build for sanity. Don't think it will be solved but confirmation is always needed.

**Comment by Ishindri** [comment]
Fair enough.  Yep, still happens in 0.C-3603.

**Comment by drbig** [comment]
Apparently fixing it good is more involved.

**Comment by Mooses2k** [comment]
Appears to be fixed.

**Comment by anothersimulacrum** [comment]
I don't think so, the sliding and trunk doors that close more than one at a time still allow you to close a door on yourself.

**Comment by wapcaplet** [comment]
Still reproducible in 0.E-6177-g 9f4a1b841d using a Humvee or Hippie van with doors spanning 2-3 tiles:

![image](https://user-images.githubusercontent.com/238395/94311879-3378e080-ff39-11ea-9ab6-53403ed8ff31.png)
