### ISSUE TITLE
Suggestion: Add option to toggle sidebar from right-side to left.

### ISSUE THREAD

**Issue by Metallumere** [CleverRaven/Cataclysm-DDA#13384]
Just a small request someone asked me about.
Instead of the sidebar being just on the right side, add an option to switch it to the right side or left side of the screen.

**Comment by drbig** [comment]
As I said on IRC I can't see anything against it as long as it's sane to do code-wise (which I think it should be).

**Comment by kevingranade** [comment]
It's a sane thing to do, not sure it will be easy though.  There may be
many hard-coded assumptions about offsets.

**Comment by Rivet-the-Zombie** [comment]
Adding more options to control the interface is always a good goal!

**Comment by drbig** [comment]
(I'm thinking about making `validated` actually mean something.)
