### ISSUE TITLE
Medical supplies do not cure NPC bleeding

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#13382]
As of 3590, NPCs can use first aid kits and bandages to heal lost health, but neither will stop bleeding.

**Comment by adrianrieck** [comment]
I can confirm, NPC bleeding but does not heal itself even though there medical supplies. I have a savegame if that helps.  http://filebin.ca/2GPNMCF72vzu/dynamicnpcs.zip

**Comment by adrianrieck** [comment]
The same issue with infected limbs for a NPC. He/She cannot heal an infection and ends up dying even though meds are available.
