### ISSUE TITLE
Disassembling an activated grenade hack yields both inactive grenade hack and grenade. 

### ISSUE THREAD

**Issue by GiantWolfSpider** [CleverRaven/Cataclysm-DDA#13383]
I activated the grenade hack to go after a mil spec turret, but it just "scanned the area" and hovered around while I hit 5 to wait. I guess I was too far from it. Bummer. 

Anyway, I deactivated the hack and it produces both a grenade and the original grenade hack. 

I activated it and deactivated it again, and sure enough, another grenade + grenade hack. Saved and quit, retried, same result.

OS: Windows Vista Business 
Version: 27f5a63 Tiles

OT: About 10 minutes before this, I watched a Giant Wolf Spider kill a Zombie Hulk. That Spider's my hero.

**Comment by Griffinhart** [comment]
Confirming on Win7 Pro, Cygwin x86 ncurses build, Version: 0.C-5512-g9ac3681.

Repro:

1. Debug menu cheated for an `inactive grenade hack`.
2. `a`ctivated the inactive grenade hack and spawned a grenade hack creature into the world.
3. Walked into the grenade hack creature and deactivated it.
4. grenade hack creature disappears, tile it occupied now contains a `inactive grenade hack` and a `grenade`.

**Comment by Nymall** [comment]
This same behavior also happens with the mininuke, C4, Tear-gas and flashbang hacks. 

Win 8.1, Version: 58cca8c

Would it be feasible to consume ammo on any of the "hack" robots on disable? Possibly a flag to not drop ammo on disable?
