### ISSUE TITLE
Add (at least basic) filters to Scenario and Profession on chargen

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#13393]
Basic being by name. I tend to spend too much time already within the chargen UI...

Biggest benefit would be for professions as there is a lot of them. More "advanced" filters like the crafting filters could be the next step.

Discuss! please.

**Comment by Metallumere** [comment]
It would be pretty nice to easily see what all gives you a certain item, skill, bionic, trait, etc.
A flat word search would probably be a good start, not quite sure what else would nice.

**Comment by Rivet-the-Zombie** [comment]
Oh yes, this would be great!

Being able to filter by displayed name would be good, and being able to sort by skills/items/etc would be even better.

**Comment by drbig** [comment]
"Prevent player from closing vehicle doors when standing on them (partial fix) #13412" obviously has nothing to do with here... It was either me or GitHub, in any case I do apologize.

**Comment by drbig** [comment]
Experimental builds starting from 3626 will have this in.

The PR brought out a relatively important, related but separate, issue: synchronizing all the ad-hoc filter-using lists to use same backend code (namely `uimenu`). Or at least as many cases where it would make sense (AIM looks like a special cherry, as usual ;)).

The above begs the question of priorities: should we (me) focus first on extending `uimenu` to handle custom filters and other bits (sorting, indicator etc.) and then do the overhaul, or should I run with what we have now and enhance the chargen UI first? (that would be filters for traits, custom filters for all tabs, e.g. min/max points, items/traits given etc. - this could actually use more discussion regardless of the main issue). Note that the overhaul is the *proper* way to do it (we'll probably needed anyway), but it would mean more time spent on stuff that would be completely transparent to the players.

**Comment by illi-kun** [comment]
Basic filter in the mentioned screens is already implemented so this issue can be safely closed.
