### ISSUE TITLE
need option to delete character presets

### ISSUE THREAD

**Issue by tsaber** [CleverRaven/Cataclysm-DDA#13409]
I have 20 right now and I reinstall cata to get rid of them.

**Comment by Night-Pryanik** [comment]
You can get rid of them by deleting the ones you don't need in \templates dir of cata.

**Comment by drbig** [comment]
Still the game should provide a proper UI for this.

**Comment by kevingranade** [comment]
Should it?  It's literally deleting a file, why does the game need to
duplicate that functionality?

**Comment by narc0tiq** [comment]
'Cause we can't expect the player to understand a filesystem? Lots of
computer users don't.

**Comment by drbig** [comment]
> Should it?  It's literally deleting a file, why does the game need to
duplicate that functionality?

...By that notion why we provide an option to delete a world? It's literally deleting a folder.

I think the proper notion is: if you create something from within the game, you should be able to remove it from within the game too.

**Comment by tvm1** [comment]
@drbig I agree. If you can create something via game interface, it should be able deletable from there.

**Comment by Griffinhart** [comment]
>Should it?  It's literally deleting a file, why does the game need to
>duplicate that functionality?

This assumes that the player knows where to look for the file in the first place. CDDA (apparently) contains no documentation to that effect.

Also, +1 to the "if the game creates it, the game is responsible for deleting it" argument.
