### ISSUE TITLE
Zombies forget seen target after stumbling

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#13418]
Old stumbling had zombies go back to the point they stumbled from and then resume their pursuit.

New one doesn't have anything like it and creatures that are more than 1 tile away from their next planned tile erase their plans to prevent "jumps".

Is the planned track actually used for something important? It looks like a placeholder to me. It would be useful for monsters with pathfinding, but at the moment no such monster exists. Replacing the entire planned track with a point like one used for wandering (or even merging those two) would solve this problem and simplify the whole thing.

**Comment by i2amroy** [comment]
Only important parts of the plan that I know of are the next immediate step (i.e. whichever one is currently next to the monster) and the end target. Other then that I don't know of any uses for the tiles in the middle (save possibly caching).

**Comment by kevingranade** [comment]
I was just looking at that, it's pretty pointless right now outside of
something weird where a monster has a pre-programmed path of some kind to
follow.
I'm in the middle of adjusting stumbling a bit more, and I'll look at
ripping out plan while I'm at it.
