### ISSUE TITLE
Survival Knife unsheathable.

### ISSUE THREAD

**Issue by maxmurder** [CleverRaven/Cataclysm-DDA#13427]
Currently the Survival Knife does not have the SHEATH_KNIFE flag. 

It's description states that it is a "massive" knife, which may justify it not being sheathable. However, starting as a survivalist and being unable to sheath your starting knife seems a little jarring.

**Comment by Zireael07** [comment]
It's intended - you can sheath it in a sword sheath but not knife sheath due to size.

**Comment by Coolthulhu** [comment]
Does survivalist have a sheath? I guess it should be changed to a scabbard now or removed

**Comment by BevapDin** [comment]
> It's intended - you can sheath it in a sword sheath but not knife sheath due to size.

Maybe it should have the `SHEATH_SWORD` flag, which allows putting it into a scabbard, but not putting it into a sheath?
