### ISSUE TITLE
Retroactive vehicle processing (notably solar panels)

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#13435]
Currently solar panels only work on vehicles that are loaded into submap buffer. This makes vehicles work quite differently from all other stuff.

I assume this behavior is to make fuel/power usage on idling vehicles more realistic: if a vehicle has +300 power per day from solars and uses 400 per day on headlights, it loses roughly 100 power per day.
The problem is, it only works on vehicles that are in submap buffer.
All newly generated vehicles re-roll this chance, meaning that you can enter a town 5 years after the cataclysm started and there will be cars with shining headlights.

Additionally, it confuses players and I keep hearing the question: "do solar panels work outside bubble?", for which there is no simple yes/no answer.

This would change the "realism" a bit: vehicles which had active headlights would have empty batteries, vehicles which had idling engines would have empty tanks (but full batteries), solar vehicles would have full batteries. Except for the first few hours after player's spawn.

A negative effect would be that vehicles with solars producing 500 power and headlights consuming 100 power would first have the headlights empty the batteries (and turn off all epower users), then would charge them to 100% now that nothing uses epower.

Making the change wouldn't be hard. I already added retroactive funnels to vehicles, extending that to solars should be easy. Extending it to other parts could be harder due to possible performance problems (retroactively updating a 3 year vehicle), so I'd leave it for later.

Any objections?

**Comment by Rivet-the-Zombie** [comment]
I'd love to see a sane fix for the weird stuff like cars idling on a half tank of gas years into the cataclysm.

I'm in favor, so long as it's not too processor-intensive for players using older systems.

**Comment by drbig** [comment]
> This would change the "realism" a bit: vehicles which had active headlights would have empty batteries, vehicles which had idling engines would have empty tanks (but full batteries), solar vehicles would have full batteries. Except for the first few hours after player's spawn.

That does sound sane. I think some hard threshold (a week?) after which everything gets straight to that "final state" based on the initial roll. Maybe just leave the stuff as is now and let it "run out" on it's own? (e.g. headlights draining batteries, idling draining fuel etc.)

> Making the change wouldn't be hard. I already added retroactive funnels to vehicles, extending that to solars should be easy. Extending it to other parts could be harder due to possible performance problems (retroactively updating a 3 year vehicle), so I'd leave it for later.

What other parts?

The way I see it is "let it roll as it does now, just after a threshold new stuff will be auto-finalized".

**Comment by Coolthulhu** [comment]
> What other parts?

Everything other than funnels and solar panels. For example headlights.
Those would require some extra processing and so may require optimizing processing.

**Comment by kevingranade** [comment]
Hmm, at least for the moment, all power consumers in an idling vehicle are constant, so you could simply total the consumed epower, and only update the solar panel production.
