### ISSUE TITLE
Firing dialog leaks enemy location

### ISSUE THREAD

**Issue by woutershep** [CleverRaven/Cataclysm-DDA#13440]
OS: Linux (Exherbo)
Interface: curses
Version: 8086029ceb7dc83f4d6abe7f66ad0db94e865022 (Thu Aug 27 15:36:22 2015 +0200)

![positionleak](https://cloud.githubusercontent.com/assets/11578180/9554459/5e38297c-4dc6-11e5-9cbd-464030d3bbd8.png)

Top part is aiming my LACP handgun (using f, if that matters) into the darkness bottom left.
Bottom part is aimining one square to the left, suddenly there is a "Confidence" and "Steadyness".
Now i know there is any enemy there, this totally negates vision obstruction such as smoke because you can just 'scan' through it untill i get a "Confidence" and fire blindly to that spot untill its dead.

**Comment by drbig** [comment]
Does indeed look like a bug.
