### ISSUE TITLE
Build issues on OSX 10.10.5

### ISSUE THREAD

**Issue by nonymous** [CleverRaven/Cataclysm-DDA#13444]
Working from http://www.wiki.cataclysmdda.com/index.php?title=How_to_compile#Mac

```
make NATIVE=osx OSX_MIN=10.7 CLANG=1
```
ends in errors
```
src/line.cpp:467:20: error: no member named 'abs' in namespace 'std'; did you
      mean simply 'abs'?
    const int ax = std::abs( dx );
                   ^~~~~~~~
                   abs
/usr/include/stdlib.h:129:6: note: 'abs' declared here
int      abs(int) __pure2;
         ^
src/line.cpp:468:20: error: no member named 'abs' in namespace 'std'; did you
      mean simply 'abs'?
    const int ay = std::abs( dy );
                   ^~~~~~~~
                   abs
/usr/include/stdlib.h:129:6: note: 'abs' declared here
int      abs(int) __pure2;
         ^
2 errors generated.
make: *** [obj/line.o] Error 1
```

tried
```
make clean
make NATIVE=osx OSX_MIN=10.7 CLANG=1 MACPORTS=1
```
resulting in the same error messages.

**Comment by drbig** [comment]
@nonymous The wiki is not the best place for up-to-date information - read [COMPILING.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING.md). In case it's outdated/you have other instructions - PRs are very much welcome.

**Comment by nonymous** [comment]
update:  editing line.cpp:467 and 468 replacing "std::abs" with just "abs" appears to resolve this. It compiles and launches.  I'll post again if the game is broken because of this change.  
I didn't find any information on these errors in COMPILING.md

**Comment by nonymous** [comment]
I guess I can't be sure of the cause, but the interface is wack so I guess this does actually break the game.  Not sure if this kind of feedback helps, but I'm handing it out anyway.  I typically play on linux vm anyway.

**Comment by drbig** [comment]
> I'll post again if the game is broken because of this change.

It won't break. The `std::abs` is same issue some people have on Cygwin/MSYS. AFAIR it's due to what has been included with your compiler.

**Comment by nonymous** [comment]
I guess it's a font issue since I didn't mod.  lots of tiles were black or at least no contrast to background/forground text.
