### ISSUE TITLE
Ice Cream: A Tale of State Changes and Edible Containers

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#13441]
Basically, I noticed that we now have ice cream trucks. But, no ice cream? Far as I can tell, some things would be required to allow such a thing.

First and foremost, the ability for a comestible s solid/liquid state to depend on temperature. Basically ice cream would have the flag marking it as enjoyed cold, and some property making it solid when cold, and liquid otherwise.

Now, in the post-apocalyptic world, how do we make the inevitably melt ice cream still exist for the player to find? Simple. Cartons, waxed paper or plastic, would have to be watertight to ensure the item will be contained properly regardless of its state.

However, this gives one extra refinement we could add. Ice cream cones. Logically it could be a container for scoops of ice cream, but...they wouldn't be resealable, and wouldn't be watertight. This means once the ice cream melts, there goes your dessert. In order to make this have any viable effect, we would have to store it in ice cream trucks, possibly also boosting the odds of the minifridges being turned on when the vehicle is spawned. How long it'll be able to keep the pre-scooped ice cream frozen, if it does at all, would hinge on whether the vehicle generates with working batteries and fridges.
##

**Comment by Coolthulhu** [comment]
Would be easier to just say ice cream is liquid and add a flag that gives penalty for consuming it non-cold.

Implementing variable phase and leaking through containers just for that one item is a terminal case of "too much bother to bother with".

**Comment by chaosvolt** [comment]
Hmm. True, and in most cases it wouldn't be noticeable to players anyway.

Still think that edible containers would be amusing though. XP

**Comment by Coolthulhu** [comment]
Edible containers could be a lot of work too.

**Comment by chaosvolt** [comment]
As I figured, yes. Amusing, sure. But worth the hassle, likely not.

**Comment by BevapDin** [comment]
> Still think that edible containers would be amusing though. XP

This one is actually quite simple. Just add this to the item definition:
```JSON
        "container_data" : {
            "contains" : 40,
            "rigid" : true,
            "watertight" : true,
            "seals" : true
        },
```
This may not work for items counted by charges (sugar), but it works fine for other comestibles (tested with cooked fish). Eating a "cooked fish of water (fresh) (30)" only eats the water in it, but when it's empty, the fish itself is eaten.

**Comment by chaosvolt** [comment]
Probably would require the item to not use charges, yeah. You'd stack ice cream cones in box on a soft-serve machine maybe, but that would mess with being able to have something in them.

And it makes sense that you'd eat the contents first.

That reminds me, with the armor data property one actually COULD make jerky armor like I suggested on the bad ideas thread...

**Comment by ryvn** [comment]
>Implementing variable phase and leaking through containers just for that one item is a terminal case of "too much bother to bother with".

Well, there are other potential uses. This would also allow freezing water to be handled properly, which could be used to preserve food. To make ice you would need a freezer, but you could use it to keep food in coolers, either dragging them with you or in your other vehicles that aren't minifridge-equipped.

**Comment by chaosvolt** [comment]
Oh hell yes, ice would be useful.

Now if we had a freezegun too...

**Comment by stk2008** [comment]
Putting things in freezers and it gets the frozen tag say 2hrs later would
be cool :)

**Comment by Leland** [comment]
This thread hasn't seen an update in years. Closing for now. If anyone is still interested, I can reopen... or feel free to just make a new issue!
