### ISSUE TITLE
NPC`s dont take right paths and just smash every thing

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#13452]
OK I got an NPC following me and he instead of using the door to keep up with me took the shortest route VIA smashing the bloody window :(

[img]http://i.imgur.com/fMDYtIp.png[/img]

**Comment by stk2008** [comment]
awesome it dont crash now but...

Setting them to not bash and bumping into them and when it says attack pressing no they still bash into the car to move

http://imgur.com/tdt4qhx

MORE IMPORTANT THOUGH :)

when I get into a car the NPC just stops and does not even move to get in it stands there as if path finding is turned off or they have took it upon them self to not follow you again because as soon as your feet touch concrete again they run after you if you had drove of a little.

**Comment by Coolthulhu** [comment]
Can't replicate the car bug. Does your car have more than one seat? NPCs will only try to get into a car that has a free seat.

**Comment by stk2008** [comment]
Oh dam really?
I have spare seat could it be the vehicle mod ? The one shipped with cdda?

**Comment by stk2008** [comment]
Not sure if it matters I was using the npc from start shelter
