### ISSUE TITLE
Drawing damaged or reinforced knifes from survivor utility belt causes crash

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#13453]
Did some science of this after Thwap gave some more helpful info in the thread they posted about this ( http://smf.cataclysmdda.com/index.php?topic=11124.0 ).

Drawing a knife from the survivor utility belt will cause a crash if the knife is damage OR reinforced. Basically any condition besides the norm. Sheath, boots, and normal survivor belt all act normal.

Screenshots for the screenshot god, PNGs for the PNG throne:

![the crashening](https://cloud.githubusercontent.com/assets/11582235/9568082/4380aa24-4f05-11e5-9cd7-aac3c985641a.png)

![the revenge of the crashing](https://cloud.githubusercontent.com/assets/11582235/9568083/4619f1b4-4f05-11e5-8100-619521493ceb.png)

**Comment by Griffinhart** [comment]
Unable to reproduce on Cygwin x86 ncurses build version 0.C-5853-g1cad147.

Methodology:

1. Reset testing world.
2. New character.
3. Debug menu spawned `survivor utility belt`, `steak knife`, `soldering iron`, `scrap metal`.
4. `W`ore `|| survivor utility belt`.
5. `a`ctivated `|| soldering iron` and made the `|| steak knife` extra sturdy.
6. Sheathed the `++ steak knife` in the `|| survivor utility belt`.
7. Drew the `++ steak knife` from the `|| survivor utlity belt`.
8. Worked just fine.

**Comment by chaosvolt** [comment]
Not sure if that means it's fixed or if it's a specific build issue.

**Comment by Griffinhart** [comment]
I'm inclined to think the latter.

**Comment by chaosvolt** [comment]
I would assume so. I'm assuming Cygwin is a compiler? As both the OP in the thread and I used pre-compiled experimentals from the main site.

**Comment by Griffinhart** [comment]
Cygwin is a Unix-like environment for Windows (strictly speaking, it's a
DLL and an API layer) that includes many compilers. You can *kind* of think
of it like a Unix emulator, but that's entirely incorrect (and Red Hat
themselves explicitly note that Cygwin is *not* an emulator).

I compiled with Cygwin gcc (I want to say 4.9.3, but it might be 4.9.2; I'm
not at the machine to check).

**Comment by Coolthulhu** [comment]
Couldn't reproduce.

The only explanation I have for this goes like this:
* The fact that only damaged/reinforced items cause the crash suggests heavily that it has something to do with drawing of the colored health bars next to them. If I'm right, turning off health bars in options->interface should stop the crash
* The crash is probably related to something with pointers, hence why it doesn't reproduce reliably and why compiler choice affects it
* Different versions of the game may not have the crash, even though it wasn't actually fixed
* May be different in tiles/non-tiles and x32/x64. When you get a version that crashes, report the entire version. Tileset choice shouldn't affect it (should happen even with tiles off).

**Comment by chaosvolt** [comment]
Hmm. Very odd. Um...dafuq?

To quote Thwap in the thread:
> Confirmed: Turning off item health bars in the interface settings prevents the crash.

**Comment by chaosvolt** [comment]
As for why different versions do this...no idea. I might go download the latest Windows console experimental to see if it works.

**Comment by chaosvolt** [comment]
Well. Tested the ASCII version, latest experimental build 3646 (1cad147).

![more borks](https://cloud.githubusercontent.com/assets/11582235/9620400/7c414c52-50df-11e5-959d-598a060b3f72.png)

**Comment by chaosvolt** [comment]
To quote Thwap again:

>So I messed with the jsons a bit more and tested it a couple different ways, just to rule anything else out, and here's pretty much the final word on this bug in concise form:
>
>IF an item is wearable
>AND the item has a reinforced/damaged knife sheathed in it
>AND the item has more than one use_action, thus requiring the menu
>AND item health bars are enabled
>AND you're using the pre-compiled experimental from the website
>
>Then the game crashes as soon as the item is activated, without displaying the menu. If any one of these conditions aren't met then there's no crash, and no other conditions seem to apply. Maybe someone can paste this to the Git entry for the bug.

**Comment by kevingranade** [comment]
Pre-compiled likely just means 'built with RELEASE=1'

**Comment by chaosvolt** [comment]
Hmm. Anyone got more info on what builds do and do not exhibit this issue?
