### ISSUE TITLE
Tech Talk

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#13451]
This is taken from my forum post http://smf.cataclysmdda.com/index.php?topic=11156.0 I thought I would post it here to I hope this is allowed etc :)

So I have been thinking.
IRL we have mobile phones and tablets that can do all sorts of cool stuff.
As it stands in CDDA the phone can only act as a clock and a low poered torch.

I think it would be cool to allow more options.

I assume it would break gameplay to allow the mobile phone to act as a computer or turret hacker like the laptop?.

We have on modern phones

Wifi
Bluetooth
Infrared
GPS
etc etc

Why not allow us to use this.

Example one

You place a comunication device in a vehicle or even a turret and allow us to log in VIA mobile phone to control its varius functions this could be expanded to allow us to control the radio control cars?.

What about logging into the security cameras of cars etc to view whats going on.
Lets say you find a hacking software on memory stick that allows you to log into cameras from say within 50 tiles.

You install it onto the phone (and for balance reason you could have fixed storage space) then it allows you to cycle < > through all the cameras with in that radius to view remotly whats going on around them.

Most phones now have a add hoc type Wifi system where you can create your own network on them so lets say we set a phone up with a private network that acts as a router in our base.

We can then carry a second phone and log into the phone at the base and control varius items with in our base say a genorator to turn it on or off we could even be forced to place a system of these phones up to allow greater distances all ove the towns etc :O.

@Narc0tiq touched on some thing ages ago that has stuck with me.

Programmable chips

We could use mobile phones to create and actually write real code in game to allow custom functions from it.
We would off course have to be carfull as people (like me) who have zero programming idea could kill the game with bad codeing LOL.
But think about this

We grab a mobile phone and isntall a programming enviroment on it.
We use a USB cable to connect it to say a turret we have built and write code onto a programmable chip placed on the turret to write custom software for it that allows this perticuler turret to turn on or off at certain times of the day or only attack certain monsters etc.

If allowing full programming in CDDA scares you maybe do what carnage heart does and have programmable chips that allow certain functions.

http://i57.tinypic.com/wkpsvd.png

http://i.imgur.com/MMDmTfK.png

**Comment by kevingranade** [comment]
Omnibus (including a lot of separate features) issues are bad, because they
can be difficult to call 'done', please break it up into separate, specific
suggestions.
