### ISSUE TITLE
NPC not entering vehicles 

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#13468]
build : cataclysmdda-0.C-3646 64bit
tiles : yes modded m shock
windows 7 64 bit

Ok NPC from start shelter agreed to travel with me.

I went out side and spwaned a sports car I entered seat and woooot he got in and sat on spare seat.
I spawned a fire  truck and she just stands on the door never sitting on seat.

I then spawnded a metlab and same problem.

I have no idea why there not sitting 99% of the time :(

**Comment by kevingranade** [comment]
Sounds like 66% to me ;)
Do they not recognize the seat types?

**Comment by stk2008** [comment]
hmmm not sure mate :(.

**Comment by Coolthulhu** [comment]
They should recognize all boardable parts (not just seats, despite the function being named `free_seat`).

I think I may see another reason for why would the NPCs not enter some vehicles, especially big ones:
`free_seat` returns FIRST (by part number) boardable part it finds. This part may be inaccessible without bashing.

There is also a bug with my implementation of pathfinding: it doesn't consider opening vehicle doors if bashing is disabled. Opened doors will be pathed through just fine.

**Comment by stk2008** [comment]
Yay so you may have possibly spotted the problem if soo wooooooot :)
