### ISSUE TITLE
M2 extremely inaccurate

### ISSUE THREAD

**Issue by Jiamil** [CleverRaven/Cataclysm-DDA#13469]
Mounted a M2 on a vehicle and fired in several tests around 200 bullets in a Z-crowd. Skills in marksmanship is 5, rifles 3. Only hit one time one Z on range 8 with 15 damage.

**Comment by stk2008** [comment]
Plus one from me on this to.

I have seen the same thing its way way to inacurate to even bother with using :(.

I have not tested other mounted guns that you physically use (not ones controlled remotely).

**Comment by illi-kun** [comment]
AFAIR it wasn't updated during Kevin's overhauling of guns, and it will be easy to fix.

**Comment by stk2008** [comment]
Awesome this is good news :)

**Comment by illi-kun** [comment]
My assumption was incorrect, and M2 Browning actually was updated during overhaul. All we need is accurate tuning.

**Comment by Coolthulhu** [comment]
There is a penalty (hardcoded in ranged.cpp) for using large (in volume) ranged weapons at close range.

Dispersion is multiplied by `volume / (range * 3)` (if that is >=1). M2 has 20 volume.

Also, moving vehicles get an extra penalty.

**Comment by illi-kun** [comment]
I think I found the reason of this behavior: ```vehicle::manual_fire_turret``` doesn't read ```recoil``` value, in my debug build shooter has >22k points of recoil, and adding this dummy code in the named function solves the issue: ```        shooter.recoil = 100;```
