### ISSUE TITLE
Minefields do very little damage at all

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#13471]
cataclysmdda-0.C-3646 64bit
tiles modded mshock
win 7 64bit

all righty then
Found one of them random minefields and thought ha lets lure monsters into it.

I lured some children in there and boom they lived with some damage but should have died.
I then lured a normal zed in it and boom it did even less damage.

But the twist here is there was a car also in the mine field that got totaly killed.

Recap

It does very little damage to monsters where it should have killed them out right.
To vehicles it seems to total kill them so its very odd.

NOTE

I tested with a normal mine from the wish menu and buried it.
I lured a zombie onto it and boom it totaly blew the zombie into peices.

So I assume its just the minefields that spawn as part of the map.

**Comment by Headjack** [comment]
I've had the same experience, where leading mobs into minefields is really ineffective. I always assumed it was something to do with shrapnel being relatively useless against bloodless, organless zombies, but being at the center of the blast should probably be extra harmful to their legs or something. If it's true that spawned mines act differently, then yeah that should be adjusted.

**Comment by BevapDin** [comment]
Before this spreads even more:

> So I assume its just the minefields that spawn as part of the map.

It doesn't matter how the trap is created, it's always a `tr_landmine` or a `tr_landmine_buried`. Placing a trap via an item calls the very same function that places traps from within mapgen. You can spawn a trap directly via the editmap thingy and it is exactly the same as if had used the item and the same as if it was spawned via mapgen. Once the trap is placed, *no* reference to the original item (if there ever was one) remains.

Buried landmines and the non-buried landmines call the same function when triggered, they only differ in the visibility (how likely it is to spot them). The have therefor the very same effect when triggered. When triggered, the landmine calls `game::explosion`, which is responsibility for all the actual effects, like damaging etc. and explosions contain a lot randomness.

**Comment by Coolthulhu** [comment]
We got a bit of power creep: new explosives and gas tanks are way stronger than the old explosives. I balanced the explosions (and shrapnel) against the new ones more than the old ones.

Just buffing the mines (and grenades and C4) could help.

Another thing is that shrapnel has low accuracy vs. the critter in the center. It is still likely to get in a bunch of hits, but way less than the old one (that hit the center critter with all the shrapnel).

**Comment by BevapDin** [comment]
> But I wished a landmine and buried it and it killed zed's out right.
> All ready buried minefields do no damage really its practically zero.

That's why it's called random. It's random. Mandatory references: http://dilbert.com/strip/2001-10-25 and https://xkcd.com/221/

**Comment by i2amroy** [comment]
Do the new explosion functions allow for a differentiation between explosion power and size to allow for a "aimed" or "focused" explosion? IIRC that was part of the big problem with more realistic landmine values, real land mines generally have a rather focused explosion upwards, thus making them do lots of damage but in a very small area. I know that, at least previously, if you gave them that larger damage then you ended up with explosions that covered huge swaths of land when they should realistically be much smaller.

**Comment by Coolthulhu** [comment]
Changing the distance formula could be relatively easy. For example, just exposing the exponent as a parameter of explosion.

**Comment by iceball3** [comment]
@i2amroy I'm not currently aware if it does or doesn't, but if it doesn't, couldn't a temporary bandaid until a full rework be that high-powered focused explosion events would just call multiple low-powered explosions simultaneously?
