### ISSUE TITLE
Generic crash when loading character, related to grabbing a shopping cart during save?

### ISSUE THREAD

**Issue by Suga-H** [CleverRaven/Cataclysm-DDA#13474]
Using tiles experimental build 3646, on Windows 10 pro.

I get a Windows generic crash "cataclysm-tiles.exe has stopped working" when trying to load the character Delbert Brink, located on the Gateway world.  I've tried porting her to other worlds and the crash is the same, and other characters on Gateway work fine, and I've teleported to the area she was last at and nothing seemed weird.

The last save was when I was moving some inventory in to a vehicle.  I proceeded to drive the vehicle around a bit, I don't remember what happened, but I force quit because I'm a dirty save-scummer.  When I tried to reload, it kept crashing.

Save file: https://www.dropbox.com/s/5rhh111kgwj4rx6/Gateway%20%28STS%2CSlow%2CMods%29.zip?dl=0

**Comment by Suga-H** [comment]
After having done some save file shenanigans, I've narrowed the crash down.  It appears that it's related to grabbing the shopping cart.  I did some picking and choosing while trying to restore my items and stats, and everything transferred in to a new character just fine except for the "grab_type" : "OBJECT_VEHICLE"  part.

**Comment by VlasovVitaly** [comment]
OK
I don't know how but you saved game while move_item action somehow. Action was not finished and was saved without properly coordinates info. Segmentation fault error happens on this string:
```
void activity_on_turn_move_items()
...
const tripoint destination = g->u.activity.coords[0];
```
With dirty hack was able to avoid this sigfault. And this window was opened after loading:
![2015-09-08 14 46 10](https://cloud.githubusercontent.com/assets/5244047/9734023/a36e1ad6-5638-11e5-9092-56d294e2ca3f.png)

Guess error is in saving game process. Can you remember your last action just before saving? I need to know place where is game will broke save.

**Comment by Coolthulhu** [comment]
> I don't know how but you saved game while move_item action somehow.

Could be an autosave

**Comment by VlasovVitaly** [comment]
Oh. Forgot about this. Will be hard to reproduce so.

**Comment by BevapDin** [comment]
@VlasovVitaly If you want to fix this, the `coords` of `player_activity` is not saved at all. Take a look at `player_activity::serialize` and `player_activity::deserialize`, there it should appear, but it doesn't.

**Comment by VlasovVitaly** [comment]
This will break legacy saves if i will realize coords?

**Comment by kevingranade** [comment]
The loading code will need to handle legacy actions that don't have the
coordinates, possibly just by discarding the action.
