### ISSUE TITLE
DEBUG: unknown skill none (build 3649)

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#13479]
Attempting to disassemble gold/silver bars or jewelry produces this message.

**Comment by Night-Pryanik** [comment]
Build 3648 - successfully disassembled gold and silver bars and silver necklace.

**Comment by chaosvolt** [comment]
Weird. I'm guessing it's https://github.com/CleverRaven/Cataclysm-DDA/pull/13470 that did it, if the build before didn't do this.
