### ISSUE TITLE
Fix "Special Operator" profession to work better with mods

### ISSUE THREAD

**Issue by Chase-san** [CleverRaven/Cataclysm-DDA#13489]
This profession starts you with a Rivtech RM2000 submachine gun and some 8x40mm ammo. Unfortunately, the benefits of this profession are basically nullified if you use the mod "No Rivtech Guns".

I recommend changing this gun to some other tactical smg or machine pistol. I was thinking maybe the p90 due to it's rarer ammunition, similarity to rm2000's stats (except recoil, but it's closer than anything else that fits), and it fits the tactical feel of a special operator.

**Comment by Rivet-the-Zombie** [comment]
...and the various holy-person professions lose out on lots of gear if you use the no religious books mod.
...and the winter-ambush survivors are naked if you use the no survivor gear mod.
...and the re-enactors lose their guns if you use the no antique guns mod.
...and the archaeologists will lose their bullwhips if you use the no medieval weapons mod.
...and nobody gets a gun if you use the generic guns mod.

It's not really anything that we can account for in the base game, and it's the risk you take when you enable a mod that removes items from the game.

**Comment by Chase-san** [comment]
I think you misunderstand how mods work. It is not that they lose the items, since they don't, but with the mod in place you will never find any ammo for the gun. 

Also you might be a bit biased since you wrote/created the gun (and possibly the profession) .  ;) 

Honestly nothing against you work in particular, just trying to improve things in general.

**Comment by md000** [comment]
Even though I am a tiny commiter and as so maybe not entirely caught up with the game's direction, I don't think changing the design of the main game to appease the mods is the way to go. Couldn't this be handled by changing the profession in-mod? Or, if that doesn't work, a more generic solution of the game replacing blacklisted items from starting professions with a close equivalent?

**Comment by drbig** [comment]
All mods are completely optional and are mods exactly because they tend to change the overall balance of the game (in one way or another, more or less...). Writing mainline to "work with every possible mod combination" is not a thing that makes any sense.

Therefore there is nothing to "fix" or "improve" here.

**Comment by sztosz** [comment]
If anything it's the mods that should be changed, to also correct professions that use gear that mods modify. No Rivtech Guns should overwrite Special Operator gear etc. 
It's the mod job to ensure nothing is broken when using it, not the other way around.

**Comment by illi-kun** [comment]
I agree with Rivet & md000 here, and this suggestion is the best way to solve the described "issue":

> Couldn't this be handled by changing the profession in-mod?

If Special Operator is unplayable with enabled "No Rivtech guns" mod then this profession should be redefined in the mod itself.

**Comment by Chase-san** [comment]
That is certainly a good option in and of itself.

**Comment by kevingranade** [comment]
Agreeing with what looks like the majority here, I have *no* interest in
changing core content to accommodate mods, in particular content removal
mods.

**Comment by Chase-san** [comment]
Sorry, I hadn't thought of changing it in the mod itself, or that would have been the suggestion.

**Comment by drbig** [comment]
Adjusting professions etc. in the mod is sane - is that possible already, or would that need some infrastructure in place first?

**Comment by chaosvolt** [comment]
It should be doable, though I've never tried that. I've tested mod-overwriting pretty much everything except professions and vehicles, it seems.

However, on the off chance ANOTHER mod alters the same profession, I have no idea what'll happen. But that's also a risk you take when using mods, they might interact oddly.

**Comment by drbig** [comment]
> However, on the off chance ANOTHER mod alters the same profession, I have no idea what'll happen. 

Last file to be read would "win" the whole thing, at least as far as I can tell.
