### ISSUE TITLE
Update "No Rivtech Guns" to just "No Fictional Guns"

### ISSUE THREAD

**Issue by Chase-san** [CleverRaven/Cataclysm-DDA#13488]
Basically, include other fictional guns into the pack. Such as Leadworks, 

This should only apply to traditional firearms, as there is already a "No Energy Weapons" mod, and so forth.

Here is the known list of Leadworks Guns, luckily they seem to use standard ammunition. So we don't need to remove those as well.

l_sp_9mm
l_mp_9mm
l_lookout_9mm
l_sp_45
l_mp_45
l_enforcer_45
l_bak_223
l_def_12
l_base_223
l_car_223
l_mbr_223
l_dsr_223
l_lmg_223

**Comment by Night-Pryanik** [comment]
Placet.

**Comment by chaosvolt** [comment]
Interesting. Only thing is that the Leadworks guns are at last sorta grounded in reality, using conventional ammo at least. Oddest part of the Leadworks series is the drunken naming of their DMR version of that weapons system.

Rivtech meanwhile is all about silly caseless ammo and seems to think that an SMG, an LMG, and an HMG can all chamber the same ammo without someone calling shenanigans on that. :V

**Comment by Rivet-the-Zombie** [comment]
>an SMG, an LMG, and an HMG can all chamber the same ammo without someone calling shenanigans on that.

Those designations only refer to the overall design/functionality of the weapons; they have nothing to do with the caliber utilized.

**Comment by chaosvolt** [comment]
You mean real-world designation, or Rivtech's internal lore? Because...add assault rifles to the last of things an 8x40mm gun can be on top of ALL those things. :V

**Comment by kevingranade** [comment]
What's silly about caseless ammo?  People have been trying to make it work
for a long time now, and there in fact have been some working systems
developed (Metalstorm).
As for the different gun types chambering the same ammo, why not?  The
whole point of a SMG as I understand it is 'automatic fire with pistol
ammunition', it's not much of a stretch at all to posit a complete line of
gun types firing a universal ammunition, and it sounds like something the
military would dearly love to have happen.
Regardless of that side issue, widening this to 'no fictional (but
conventional firearm type) guns' makes perfect sense.

**Comment by Chase-san** [comment]
Caseless ammo is awesome in my opinion. This is just an expansion to remove all fictional (conventional) firearms, not just Rivtech stuff.

**Comment by chaosvolt** [comment]
Widening the mod to fictional weapons does make sense, admittedly. I still prefer Leadworks guns to Rivtech, admittedly. XP

**Comment by kevingranade** [comment]
In other words, go ahead and expand the mod :thumbsup:
