### ISSUE TITLE
Typos in any modinfo.json causes C:DDA to crash without feedback.

### ISSUE THREAD

**Issue by faerindel** [CleverRaven/Cataclysm-DDA#13487]
If any modinfo.json is not formatted correctly, it throws the Windows generic crash "cataclysm-tiles.exe has stopped working" on startup.

Closing inmediately is okay, but giving some info on the cause to the user would be nice.

**Comment by chaosvolt** [comment]
Could potentially cause a clusterfuck, yes. I would hope at present all default mods are working?

**Comment by drbig** [comment]
Crashing on malformed JSON is definitely not a good thing. Sane thing would be to spam errors telling what is missing/etc. and just ignoring the file completely then.

**Comment by chaosvolt** [comment]
Sanity is overrated.

**Comment by BevapDin** [comment]
Works fine here (3073b6ee2f57df7fe96599e13d1445a53bb274ac) on Linux:

![screenschot-2015-09-05-12-14-02](https://cloud.githubusercontent.com/assets/5095435/9698848/15061f76-53c9-11e5-8bf2-61c5c23cbdd6.png)

(Pressing space makes the game continue as usual, but without the mod.)

----

But you haven't specified the version you use, nor have you specified what "not formatted correctly" is (just post a modinfo.json, which triggers the crash). Your "not formatted correctly" may not be the same as what I tested.

**Comment by drbig** [comment]
Mhm, the debug stuff probably doesn't show in the tiles build due to the (known) redraw issues.

**Comment by faerindel** [comment]
Windows Tiles 0.C 3648 version, yes. And I think the other guy in IRC who had the same crash uses tiles version as well (don't know which exact build).

And by "not formatted correctly" is stuff like forgetting to close a string, or a period too many:
````
{
    "type": "MOD_INFO,
    "mod_type": "SUPPLEMENTAL",
    "ident": "test",
    "name": "test",
    "description": "test"
}
````
This unclosed string in MOD_INFO will cause the crash.
