### ISSUE TITLE
Magic and Arcana mod: to PR or not to PR?

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#13495]
At present, my mod for magical items is effectively my most fleshed-out mod that I haven't opted to PR, and with plenty of help from @BevapDin the major kinks in it were swiftly worked out. As such, it could be in a PRable state by now, but for this I'd want to get some feedback before deciding on it.

The relevant thread for the mod: http://smf.cataclysmdda.com/index.php?topic=11013.0

Now, to summarize what all the mod does, it primarily adds a new skill, used for crafting the various magic items, for success of summoning monsters, and as the skill for ranged magic weapons. The mod's magical system is explicitly item-centric. No spells.

It also edits a wide array of the more oddball, anomalous monsters so that they drop items relevant to the mod. The principal monster drop to be had is essence, needed as a major component for crafting most magical items, and for fueling some of them. Alternative resources are available and some items demand those alternatives instead.

In terms of fluff, over time I've built up a bit of implied lore behind the relevant books, and one mapgen addition added recently fleshes out the implications of one such faction. Besides that, most of the items and other content reference something, from historical alchemy to Lovecraft's work to various games.

From what I can tell, the general opinion on adding magic and such is it should stay mod-only, so it will if I PR it. Feedback before I commit to a commit (huehuehue) would be desired.

**Comment by kevingranade** [comment]
Totally fine as a mod :)

**Comment by chaosvolt** [comment]
*cue a Mr. Burns impression* Excellent.

I do wonder how much to break it up for PRing, as it's got enough content to likely warrant being added in installments like I did for the tank and medieval mods.

**Comment by chaosvolt** [comment]
Well, PR is up ( https://github.com/CleverRaven/Cataclysm-DDA/pull/13497 ), part 1 will be foundation of essences (except for dull essence), the two from-level-zero books (and the recipes in the latter beginner's book), and the two books that factor into making more essence/blood essence.

**Comment by chaosvolt** [comment]
Guess I could close it due to having decided to PR, though presently...waiting for Jently to start working. Any way for me to prod it into checking, or do I have to wait for someone else to do the poking?
