### ISSUE TITLE
"Failed to save Player Data" when attempting to save.

### ISSUE THREAD

**Issue by bigphilm** [CleverRaven/Cataclysm-DDA#13498]
Occasionally, when attempting to save my game, a box comes up saying "Failed to save player data."  From there I have no idea what to do.  The most recent time I threw a giant tantrum and deleted the game.  If it happens again, is there something I can do to help y'all out, let me know so I can do that next time.  I was using 0.C stable on Windows 7.  I may or not be correct in saying that this only happened when at some point O had used the Windows button to hop in or out of the game.  I might have to work out how to back up save files.

**Comment by drbig** [comment]
Does it happen all the time, or only sometimes? Do you have enough space left? Proper permissions to write?

**Comment by bigphilm** [comment]
Only occasionally (still infuriating when you are making progress in the game.)  Space is not an issue.  I'm not sure what you mean by "Proper permissions to write."

**Comment by drbig** [comment]
> Only occasionally (still infuriating when you are making progress in the game.)

The worst thing... No idea how to even pin-point the real issue.

**Comment by mugling** [comment]
No obvious path to resolution and not reported elsewhere
