### ISSUE TITLE
Monsters can see you when you view them using a vehicle Camera System

### ISSUE THREAD

**Issue by Xnfinity** [CleverRaven/Cataclysm-DDA#13491]
On v3603

is this intended?... 

when a turret opened fire at me when they just ignored on stable...

(ps will fuel tanks / vehicle battery on the interface ever show the % filled like cargo containers rather then just a global counter)
##

**Comment by drbig** [comment]
> is this intended?...

Hope not. Otherwise the cameras should be called "magic mirrors" or some such...

 > (ps will fuel tanks / vehicle battery on the interface ever show the % filled like cargo containers rather then just a global counter)

Cargo containers do that?... In any case that could be a separate issue for discussion.

**Comment by Xnfinity** [comment]
Some added details would be that wing mirrors and inboard mirrors also allow them to see you (though in this case i say that legit but might help find out)

and cargo containers meant when it says "cargo space (vol: foo/1000)" in the part menu

**Comment by kevingranade** [comment]
Oops, I thought I had kept this from happening, mirrors and cameras should
not let monsters see you.

**Comment by illi-kun** [comment]
As it stated in #14599 by Kevin:

> The reason this override exists is because the way we calculate FoV for players and monsters is not symmetric, the override forces symmetry. One way to implement one-way visibility is to store squares the player can see directly separately from squares the player can see via one-way mechanisms like cameras, and only force visibility from monsters that are viewed directly.

So, issue is confirmed and I hope that additional info will help.

**Comment by JeeDRGN** [comment]
Still a vexing regression issue...

**Comment by kevingranade** [comment]
Fixed by #24881
