### ISSUE TITLE
NPC and Cars (again so so sorry Coolthulhu)

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#13501]
TURN DOWN VOLUME

Hi all

Build : 	cataclysmdda-0.C-3655 64bit
tiles : chezzo
windows 7 64 bit

get npc to follow get in car he gets into a seat realy well now mate but when driving he keeps jumping out.
I think its when the car turns he/she gets confused?.

https://www.youtube.com/watch?v=P43kxrGbTA0&feature=youtu.be

sorry for bad Q

Also when an NPC flees he will run into a car still smashing the hell out of it instead of path finding his way around it.

Thanks

EDIT

I was getting debug messages on my last test will post here if I get them to come up again :)

**Comment by Coolthulhu** [comment]
Fleeing NPCs will still bash cars for a while. I don't have a good way of fixing that properly, it would require some sort of reverse pathfinding. For now only NPCs that are pushed away are prevented from bashing.

Will check out the turning bug.

**Comment by stk2008** [comment]
thanks again matey realy do appriciate you doing all this :)
