### ISSUE TITLE
Strange "You cannot wield a xxx with only one arm." message

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#13506]
0.C-3659, Win 10, tiles.
Have both arms fully healed. Have shotgun revolver. When I add recoil stock to it, and trying to wield the weapon, the game gives me the message in title.

**Comment by Coolthulhu** [comment]
Do you have the fusion blaster CBM? It states in the description that it costs you an arm.

**Comment by Night-Pryanik** [comment]
Yes, I have, but I wonder why adding custom stock to shotgun revolver (or maybe other weapons) makes it impossible to wield it?
I even think that this CBM is working somewhat incorrectly, because I can successfully wield shotgun revolver without that stock - and many other melee and ranged two-handed weapons.

**Comment by Coolthulhu** [comment]
An item is two-handed if it has the two-handed flag or if `(weight / 113) > strength * 4`. Stock increases weight, so it can make the item two-handed.
This isn't enforced too well, you can still use a two-handed item in one hand, you just can't wield it (put it in your hand) while it is. If it becomes two-handed after that, you can still use it normally.

**Comment by Night-Pryanik** [comment]
Okay, I got it. So this is not a problem or incorrect behavior.
One last thing: I think player should know this information (about two-handedness) from the game itself, not from the formulas deep in game code. Maybe we should alter a message a little, something like "You cannot wield a xxx with only one arm. Either it's handled only two-handed or your strength is insufficient to wield it one-handed"?

**Comment by Coolthulhu** [comment]
Yeah, it could be altered like that, preferably with separate messages for flag and weight.

It would be the best if it gave a rough estimate of either the required strength or the heaviest item that can be wielded one-handed.

It's a relatively low priority thing though, as having only one hand is a rare thing.

**Comment by Night-Pryanik** [comment]
Ok. Closing the issue.
