### ISSUE TITLE
player::thirst but Character::stomach_water

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#13520]
`thirst` and `fatigue` are both in `player` class, while `hunger` and `stomach_*` are in `Character`.

**Comment by drbig** [comment]
This seems to be unsynchronized - `thirst`, `hunger`, `fatigue` for all? (what are `stomach_*` even supposed to mean?).

**Comment by Rivet-the-Zombie** [comment]
I think that ````stomach_*```` tracks how much food/drink you've recently ingested, so that you can't vomit up stuff you ate three days ago.

**Comment by drbig** [comment]
Ok, that makes sense, then... `stomach_fullness`? Or do we care about actual contents (or even liquid - solid distinction)?...

**Comment by Rivet-the-Zombie** [comment]
I don't think it bothers to make a distinction.

**Comment by Coolthulhu** [comment]
> Ok, that makes sense, then... stomach_fullness?

No, it needs the precise values of hunger/thirst mitigated by recently consumed food. Otherwise you couldn't return the old (pre-vomit) levels.

**Comment by drbig** [comment]
So `stomach_liquids` and `stomach_solids`?

**Comment by kevingranade** [comment]
It really is just water though, possibly stomach_quench would be better to
align it with the quench value of the food, which is what it's referencing.

**Comment by i2amroy** [comment]
The next player->character attribute movement PR is planning to hit hunger, thirst, and fatigue. They're currently just like that because I've only managed to move over 2 of the 5 so far since those were the easiest ones to transfer.
