### ISSUE TITLE
Lighting: Atomic nightlight reduces vision in the dark

### ISSUE THREAD

**Issue by smmck** [CleverRaven/Cataclysm-DDA#13530]
In build 0.C-54b0f1b (Jenkins build 3667) from Sep 9, the atomic nightlight reduces my vision at night to only the squares around it. The normal vision range is 5, but as soon as I step beside the nightlight, my vision drops to only the surrounding squares.

I'm playing with: LInux curses (not 64); circular distances; basic nightvision (2 squares).

Also, crafting during the day in my barn with no windows resulted in "It's too dark to craft", but I'm guessing that behaviour is intentional.

On another note, the speed improvements are exceptional! I no longer have to get myself something to read when my character reads or sleeps. Great work!
##

**Comment by drbig** [comment]
Do you have night vision or something alike? This sounds familiar...

**Comment by Night-Pryanik** [comment]
>basic nightvision (2 squares).

The same issue - I also have nightvision (only 5 squares), and when I'm turning oil lamp on, visible area is shrinking to 2 squares.

**Comment by drbig** [comment]
Sorry for not reading thoroughly!

I believe this is intended in this case. Also have a look at #13101. I'm leaving this open for confirmation from @kevingranade or anybody else 'authoritative' on the topic.

**Comment by Coolthulhu** [comment]
Outside light reducing nightvision range is intended.

However held light reducing nightvision range is more of a result of vision mechanics than the indented behavior. Realistically, the character would keep the nightlight/lamp/etc. in backpack or otherwise out of sight and only take it out to read or craft.

**Comment by Night-Pryanik** [comment]
Indeed, when I look at something light-emitting (like my turned on oil lamp) at night, the size of my pupil is decreased, so I can see only closer things.

**Comment by drbig** [comment]
> Realistically, the character would keep the nightlight/lamp/etc. in backpack or otherwise out of sight and only take it out to read or craft.

Labeling as a bug on the basis of the above. I assume if the lamp is no wielded/used for reading/crafting it should not interfere with NV etc. (i.e. that would constitute the intended behaviour).

**Comment by Night-Pryanik** [comment]
Some offtopic: when I'm turning on my lamp and it's in my inventory (not wielded), then it's located somewhere deep in pockets of my equipment, right? Maybe the lamp shouldn't produce light in that case and produce it only when wielded or dropped on terrain?

**Comment by smmck** [comment]
>I believe this is intended in this case.

That's OK too; it was quite a shock going almost blind when I walked adjacent to the nightlight, but I can see how that would be realistic. It sounds like nightvision in general has a few contentious issues based on 13101.

**Comment by kevingranade** [comment]
Either you can use light sources without having to wield them, but lose
your nightvision due to it (the status quo), or you have to wield lights in
order to use them (a new feature, not a bug fix).

**Comment by Rivet-the-Zombie** [comment]
>you have to wield lights in order to use them

I'm in favor of this.

**Comment by drbig** [comment]
I'd be in favour if the player had two hands... so I can still use my machete and a flashlight at the same time. I think for now it's sane how it is.

**Comment by Rivet-the-Zombie** [comment]
Very good point.

**Comment by kevingranade** [comment]
And now we've come full circle, lack of an off hand to spare to wield a
light is exactly why it hasn't been changed yet.

**Comment by Dunkhan** [comment]
Almost a year after this was posted, this is still a thing. I wanted to add a couple of comments:

1) This applies to all dim light sources, not just atomic night lights as the title suggests.
2)Putting a dim light source on the ground does not enable crafting, but having the same light source in one's inventory enables crafting. (tested with atomic night light and light strip, candle still enables crafting when on the ground)
3) There are now two hands (sort of) so the original suggestion of forcing wielding (wearing) is now viable. All portable light sources could be made wearable in the same way that the briefcase and other hand held items are.

I am adding these for completeness, I do not see this as an issue that needs urgent resolution. It is however a little bit annoying. The argument of your eyes adjusting is valid, but this makes light strips very impractical If you have night vision. You have to pick them up to craft, but you cant take them with you or your vision is ruined.
