### ISSUE TITLE
Advanced inventory management screen and vehicle part labels (build 3669)

### ISSUE THREAD

**Issue by Vsevolod-Shustov** [CleverRaven/Cataclysm-DDA#13531]
Labels are stuck as if the vehicle is always heading east. 1-9 keys for switching tiles work, but label shown on tile is wrong and depends on vehicle rotation.

![labelbug](https://cloud.githubusercontent.com/assets/1062138/9795971/480f1f12-57fc-11e5-9192-a5cd713c2b8d.png)

**Comment by drbig** [comment]
Can you provide a screenshot?

**Comment by Vsevolod-Shustov** [comment]
Updated first comment with screenshot.

**Comment by drbig** [comment]
A bug indeed (it's AIM, it's like the home of bugs). The screenshot does make it much easier to understand, thanks!
