### ISSUE TITLE
Active floodlight on vehicle makes it too bright to sleep inside (build 3669)

### ISSUE THREAD

**Issue by Vsevolod-Shustov** [CleverRaven/Cataclysm-DDA#13532]
##

**Comment by drbig** [comment]
Are you trying to sleep in an enclosed "In" area? Do you have all non-opaque 'walls' covered with closed curtains?

**Comment by Vsevolod-Shustov** [comment]
Yes. I don't think there are any non-opaque walls, picrelated.
Might it be related to importing a vehicle from a version that's ~2 months old? I could sleep in that version. Though other people http://smf.cataclysmdda.com/index.php?topic=11192.0 seem to have this bug too.

![lightbug](https://cloud.githubusercontent.com/assets/1062138/9796157/51b0f99a-57fd-11e5-9ebb-779ae70c6939.PNG)
Note: I didn't try to sleep at 7am, just woke up.

**Comment by drbig** [comment]
Aye. My best guess this is due to the new lighting code. I'd still be for first debug-testing it in a sort of 'fully opaque cage' to be sure, but yeah looks like a bug.

**Comment by MisterFelixFox** [comment]
Is it possible that it's intentional for a floodlight to be too bright to sleep with? It's a floodlight, after all -- I'd understand being able to sleep with aisle lights on

**Comment by drbig** [comment]
I'd say no if you went all the trouble to build yourself a 'sleeping box'.

**Comment by Oskar636** [comment]
Related to #14329

**Comment by illi-kun** [comment]
Let's keep the issue reference by @Oskar636 open an close this as a duplicate.
