### ISSUE TITLE
Weird coloring in healing menu

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#13545]
Win 10, tiles, 0.C-3676.

![1111](https://cloud.githubusercontent.com/assets/11132525/9831030/c46f0c40-594e-11e5-9343-12b4752a22df.png)

To the left is actual health of my character. To the right is the healing menu popup.

**Comment by BevapDin** [comment]
This usually means the limb is infected, bleeding or similar. It's usually shown in the character info screen (`@`).

**Comment by Night-Pryanik** [comment]
No, I mean that earlier the color in the healing menu was identical to the health screen. Now my left and right arms and left leg are all dark green in the healing menu, but in the health screen they are bright green and yellow. My right leg is yellow, but in the healing menu it's red for some unknown reason.
