### ISSUE TITLE
Vehicles can spawn with blacklisted items

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#13559]
Create world with Rivtech blacklist mod loaded. Wish an FBI car. Check the seat for items. Repeat. Eventually an RM103 pistol and ammo will spawn.

**Comment by sztosz** [comment]
It's same problem as in #13489 mod should override what item's are spawned in FBI car.

**Comment by ejseto** [comment]
No, it's not the same problem. The problem with #13489 is that the profession is "robbed" of some of its equipment because blacklisted items do not, and should not, spawn. This is a case of blacklisted items spawning, bypassing the blacklisting mod mechanic entirely.

**Comment by sztosz** [comment]
Sorry, I read in a hurry and misunderstood you :(

**Comment by Chase-san** [comment]
No the problem with #13489 was (is still?) that blacklisted items do, but should not, spawn, and as such would have robbed the profession if fixed.
