### ISSUE TITLE
Can Move into Solid things while Dragging

### ISSUE THREAD

**Issue by Boredone** [CleverRaven/Cataclysm-DDA#13574]
Version: f782560 Windows Console AND Windows Tile
Problem: While dragging something (Tested with Shopping Cart and a Locker) you can move onto solid objects. You can't go through without letting go of the object though, as it still checks if THEY run into something.
OS if Relevent: Windows 7

**Comment by Night-Pryanik** [comment]
Confirming:
![default](https://cloud.githubusercontent.com/assets/11132525/9917427/2eca501c-5cca-11e5-9692-df7b7ab69c6b.png)
