### ISSUE TITLE
Mininuke launcher does not launch modified mininukes

### ISSUE THREAD

**Issue by stasalcatraz** [CleverRaven/Cataclysm-DDA#13579]
It perfectly launches rocks instead. Is it a feature?
Game version 0b1d181. Game save with this feature https://www.dropbox.com/s/992w2dohh5rqibi/mininukes.tgz?dl=0

**Comment by Coolthulhu** [comment]
Found it:
In blazemod, the mininuke doesn't override the existing mininuke, instead there are two different mininuke items (the core one and the mod one).

**Comment by Nymall** [comment]
Being as this is an issue with blazemod overriding the modified mininuke, can I propose a fix? Or should I just wait for @illi-kun to propose a fix? I'm not sure the restrictions to proposing fixes to issues with mods.

**Comment by Rivet-the-Zombie** [comment]
By all means, if you've got a fix for a bug go ahead and PR it.

**Comment by illi-kun** [comment]
Me? Why?? That's not even my mod (__blazemod__, you know)

Since mods are included in the repository, it's okay to work with them in the same manner as with the rest of files, i.e. fix bugs, change for supporting new features, etc.

**Comment by Malkeus** [comment]
yay, another fix to incorporate into the forum version! gimme gimme gimme nomnomnom

**Comment by Nymall** [comment]
Sorry about that - I was looking into it and it showed that you were the last person to post to the mod. I was not sure if mods submitted were still restricted to the mod author. Anyways, this override should fix the issue.

**Comment by kevingranade** [comment]
Mods definitely do not require special permision for fixes, the main
difference from mainline code is that the mod author (If present) will have
the final say about changes related to balance, tone, etc.
