### ISSUE TITLE
Minor JSON Issues

### ISSUE THREAD

**Issue by vache** [CleverRaven/Cataclysm-DDA#13572]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/terrain.json#L4652 is missing the "AUTO_WALL_SYMBOL" flag.

The "CHIP" and "ALLOW_FIELD_EFFECT" flags are not documented with the rest of the JSON flags.

**Comment by drbig** [comment]
I think the docs need: more people reading them... and more people caring about them.

**Comment by Coolthulhu** [comment]
"CHIP" does nothing, should probably be removed.

**Comment by vache** [comment]
It looks like it is used in constructions.json for removing paint from walls: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/construction.json#L1811
