### ISSUE TITLE
JSON Mapgen Requests

### ISSUE THREAD

**Issue by vache** [CleverRaven/Cataclysm-DDA#13585]
These are just a few improvements that I've noticed could be made to the json mapgen while working on the building editor in case someone wants something small to work on.
1.  Placeable graffiti through json
2.  jmapgen_gaspump only lets the user pick an amount, and then it randomly picks gasoline or diesel.  It should probably allow the user to specify which fuel type, and only randomly select if left blank.
3.  jmapgen_vehicle takes an array for random rotation and then selects an entry from this array as the rotation value.  I would have expected it would take a range (like 0-359) and then randomly selected a value from this range.  The current behavior is not exactly incorrect, but it's not what I expected from the way other randomly selected fields are specified.
4.  Consistency in how the symbol is specified.  The overmap_terrain's are specified as the ASCII equivalent of the character, while terrain, furniture, monsters, and items use the actual symbol.  The "LINE_OXOX" type convention can be used for line drawing omts.
##

**Comment by drbig** [comment]
> The overmap_terrain's are specified as the ASCII equivalent of the character

That actually isn't technically correct. It's even "worse": they're specified as a number or an array of numbers, *most* of which happen to be ASCII (symbols for lines are not ASCII). And roads need different handling. Hence e.g. [this](https://github.com/drbig/catatools/blob/master/overmapper-2.rb#L260) and [this](https://github.com/drbig/catatools/blob/master/overmapper-2.rb#L10).

**Comment by Leland** [comment]
Hasn't been active discussion on this one in over two years - closing. Feel free to let me know if want this reopened.
