### ISSUE TITLE
Bashing non-stumbling monsters' AI broken

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#13580]
Consider this setup:
```
..Z
..#
..#
@.#
```
The `Z` is any non-stumbling bashing monster, for example survivor zombie or mi-go. Preferably the survivor zombie, as it has GROUP_BASH skill.

The `Z` will bash the `#` rather than moving. Maybe the `bash_rating` should be used to decrease the chances of considering this tile?

**Comment by Headjack** [comment]
Confirming, fighting monsters next to a wall often sees them knock against it several times. A slight delay is expected, but they don't need to knock their heads on it.
