### ISSUE TITLE
Reinforced glass can be shot through

### ISSUE THREAD

**Issue by md000** [CleverRaven/Cataclysm-DDA#13593]
Windows 8.1
Curses build 691dc5f

When a gun with high-ish damage (my guess is over 40, since that's the str_min value of reinforced glass walls) is fired through a reinforced glass wall, it passes through without destroying it and then deals ludicrous damage to whatever it hits. Replicated with M4A1(48dmg), Barret .50cal rifle(~70dmg) and RM99 revolver(~50dmg). AK-47(38dmg) rounds were stopped properly.

Screenshot:
![cdda_reinf_glass_bug](https://cloud.githubusercontent.com/assets/12977811/9958604/63c0c210-5e14-11e5-8584-f791fd8afdcb.png)

**Comment by ejseto** [comment]
On line 3904 of map.cpp:
```
    // Rescale the damage
    if( dam <= 0 ) {
        proj.impact.damage_units.clear();
    } else {
        proj.impact.mult_damage( static_cast<double>( initial_damage ) / dam );
    }
```
Shouldn't dam be the numerator and not denominator? If the bullet initially was going to do 41 points of damage and the reinforced glass absorbed 40 damage, the projectile would actually have its damage multiplied by 41, rather than 1/41 as you'd expect.

**Comment by md000** [comment]
Well, that would definitely explain it.

**Comment by chaosvolt** [comment]
Oh wow. :V
