### ISSUE TITLE
Error and displacement when traversing z-level.

### ISSUE THREAD

**Issue by DodgingRain** [CleverRaven/Cataclysm-DDA#13602]
Utilizing any stairs gives the error game::vertical_notes invalid arguments: z_before == 0, z_after == 0 and may displace me to a random tile nearby. Bug present in v3703

**Comment by drbig** [comment]
Looks like maybe some missing staircase and debug-induced teleport instead of crashing?

**Comment by DodgingRain** [comment]
It also occurs when I make a brand new world and new character as well.

**Comment by Foffy123** [comment]
I'd like to add that this is definitely confirmed.
