### ISSUE TITLE
Unhandled case in 3D bresenham

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#13601]
Bug affects all usages of `bresenham` where exactly one of `dx` or `dy` is equal to `dz`.
Those points will not be reached by the function at the end.
For example, `line_to` from `(0, 0, 0)` to `(1, 0, 1)` will only check the point `(1, 0, 0)` and then end iteration.

The points above will use the section:

```
if( ax > ay ) {
            while( cur.x != loc2.x ) {
                if( t > 0 ) {
                    cur.y += sy;
                    t -= ax;
                }
                if( t2 > 0 ) {
                    cur.z += sz;
                    t2 -= ax;
                }
                cur.x += sx;
                t += ay;
                t2 += az;
                if( !interact( cur ) ) {
                    break;
                }
            }
        }
```

And iterate like:
- `t` and `t2` are both 0
- increment `cur.x` (to 1)
- `t += 0; t2 += 2`
- `interact( {1, 0, 0} )`
- Loop check: `cur.x == loc2.x`, in this case `1 == 1` - loop ends even though z coord wasn't incremented
##

**Comment by anothersimulacrum** [comment]
Could #38730 have fixed this?

**Comment by kevingranade** [comment]
Oh right, yes this is precisely the issue I found.
