### ISSUE TITLE
Miniflamethrower bionic with item transform action

### ISSUE THREAD

**Issue by Xnfinity** [CleverRaven/Cataclysm-DDA#13616]
Miniflamethrower dosn't use Bionic power when dealing with transform's need_fire

And i hit enter way to early by mistake...so it posted it like that...weird...

ps still on 0.C-3667 / 54bof1b

**Comment by Nymall** [comment]
Confirmed.

Steps to reporduce:
    -spawn and use Power Storage CBM, Joint Tortion Ratchet CBM and Mini Flamethrower CBM.
    -spawn torch.
    -use torch.

Does not use any charges to light the torch. Version: 0.C 3782 - f29320c Curses

**Comment by Soyweiser** [comment]
Looking at the code player::has_fire and player::use_fire I'm wondering why the bio_tools CBM can be used to light stuff on fire.
