### ISSUE TITLE
Frequent Long-Range Deafening (4b8c3de)

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#13618]
I did a search for issues addressing this recently, but haven't seen anything, and so it might not have been addressed. However, the version I'm in is experimental 4b8c3de, and it's so perfidious I thought it might have been noticed already.

Deafness is out of control. Louder sounds, particularly hulk wall-smashing and NPC gunshots, are causing lengthy deafness from ludicrous distances. I've ended up deaf from a hulk breaking walls down in another tile entirely. There should be little need to explain that this is a surreal depiction of sound travel, regardless of how loud we want to say the smashing is. 

With the exception of cases like atomic bombs, deafness should require someone to be within a few yards of the source to actually damage their hearing for the periods of time the character is experiencing. The distances needed and the effect length should likely both be scaled back sharply.

**Comment by Skidborg** [comment]
This was discussed quite a bit in #13105, several weeks ago.  Deafness is in dire need of balancing.

**Comment by Headjack** [comment]
So it was! I must've missed it due to the search terms and titles.

**Comment by Headjack** [comment]
One other thing I noticed is that shriekers don't seem to cause deafness, even if they're right next to you, nor even ear-ringing. I've always assumed that they were meant to attract nearby zombies and disorient you, but is that functioning correctly if there's no intense sound occurring?

**Comment by Skidborg** [comment]
#13813 just got merged.  It deals with the rubble collapse issue.

**Comment by mugling** [comment]
> #13813 just got merged. It deals with the rubble collapse issue.

And gun `loudness` as also addressed some time ago.
