### ISSUE TITLE
It is possible to construct in darkness

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#13610]
Impossible to sew in darkness - check!
Impossible to solder in darkness (https://github.com/CleverRaven/Cataclysm-DDA/pull/13421) - check!
Impossible to repair in darkness (https://github.com/CleverRaven/Cataclysm-DDA/pull/13547) - check!
Now it's time for constructing. 
##

**Comment by chaosvolt** [comment]
Dang, digging a moat is my favored way to pass the time until midnight. ;A;

**Comment by Headjack** [comment]
Some things are probably OK to do in near-darkness, like digging. Maybe a new light level like "starlight" is appropriate. Ina  world without city lights, doing things like that, though not full-on crafting, is pretty reasonable.

**Comment by chaosvolt** [comment]
Some tasks could possibly also be doable in darkness, but that would require adding a "minimum light level needed" property to both construction entries and recipe entries.

**Comment by Coolthulhu** [comment]
Or just flagging some of them as "simple".

**Comment by Headjack** [comment]
Yeah, a 'do it blind' marker might be apropos sometimes.

**Comment by chaosvolt** [comment]
That would work too, yes. So basically a "ignore light level" flag or other such thing?

**Comment by Night-Pryanik** [comment]
IMO there's no need in flags. We can just make the lightness level to be "shady" (not "dark" or "very dark") when it is night and the weather is "clear". Assume this is starlight (don't take phases of Moon into account, yet).

**Comment by drbig** [comment]
Yeah, constructions are behind due to probably not-so-many-players actually paying much attention to them. There's no filter in the UI, and the mechanics are indeed quite silly light-level-wise. I think there would be only few thing one can actually do "properly" without any light: digging? sounds ok, constructing furniture? not really. I also wonder if they are "pauseable" - they'd need to be if light level becomes a thing (so you can finish that bed next day while you sleep the night on the floor).

**Comment by Night-Pryanik** [comment]
Interruptible constructing? Yes, please.

**Comment by chaosvolt** [comment]
That sounds like a clusterfuck in the making. For one,if we applied this to crafting...there goes the currently-essential fire bug. ;w;

**Comment by drbig** [comment]
Realism-wise UrW does constructions much closer to what you'd expect trying to do such stuff on your own. I'm not sure it would be a good idea to borrow that approach to C:DDA, but "Interruptible constructing" would be a must if lack of light is going to stop you.

(UrW for one has fully interruptible constructions, and you can reliably hire NPCs to at least chop wood while you spend your day or three constructing a single wall tile. And making a simple log cabin is a major endeavour. But then that's pretty much as far as UrW goes construction-wise, we have *a lot* more cool stuff in this department.)

**Comment by chaosvolt** [comment]
Or we could go the DF route, and designate multiple NPCs to build it, only for all of them to go on break, attending a part, or on break FROM partying instead. x3

**Comment by Zireael07** [comment]
Interruptible constructions would be great. I'm against a total ban on constructing in darkness, as it'd wreak havoc on e.g. boarding up windows.

**Comment by Night-Pryanik** [comment]
>boarding up windows.

You can't sew, solder, repair, read, disassemble in darkness, but you can board up windows? This is inconsistent.

**Comment by BevapDin** [comment]
> Interruptible constructing? Yes, please.

This is possible since a long time ago. Just press '.' or '5' or whatever you mapped the pause action to. Same goes for crafting.

Doing the same construction/recipe resumes the tasks (which means the time already spend on it will be skipped).

**Comment by Night-Pryanik** [comment]
>This is possible since a long time ago. Just press '.' or '5' or whatever you mapped the pause action to. Same goes for crafting.

>Doing the same construction/recipe resumes the tasks (which means the time already spend on it will be skipped).

That feel when you post something, but didn't bother to test it in game by yourself.

**Comment by drbig** [comment]
Well, the major blocker is therefore a non-issue. The questions now are: "what does require light? do we make it yes/no thing? thing depending on light level? something else?".

**Comment by Night-Pryanik** [comment]
I'd say don't allow construction if ```fine_detail_vision_mod() > 4```, as always, and
>make the lightness level to be "shady" (not "dark" or "very dark") when it is night and the weather is "clear".

so we can construct smth at night without artificial lighting, although it takes increased time.

**Comment by BevapDin** [comment]
> make the lightness level to be "shady" (not "dark" or "very dark") when it is night and the weather is "clear".

That may interfere with night vision, if it's too bright, night vision does not set in and is practically useless.

A flag seems to be better as different construction require different detail vision. A pit can be made in near darkness (same as placing a metal frame, an anvil), construction/deconstruction furniture requires more light.

**Comment by Zireael07** [comment]
Boarding up windows could also work in near darkness.

**Comment by Night-Pryanik** [comment]
Flagging is also a viable way, of course. I just think that a little shifting of threshold after which NV is activated is easier to do rather than manual flagging of construction options.

**Comment by Night-Pryanik** [comment]
Discussion is stalled for a long time, closing for now.
