### ISSUE TITLE
Misplaced text in (multi)drop selection-menu

### ISSUE THREAD

**Issue by namarrgon** [CleverRaven/Cataclysm-DDA#13615]
Trying to drop the currently wielded item, the name of the marked item jumps to the wrong place on the screen, overwriting part of the interface, whereas selecting other items lists them on the right side of the screen, as intended.
The location seems to depend on the the size and geometry of the window. Both, tiles and curses, builds are affected.

![http://imgur.com/wc7IrTe](http://i.imgur.com/wc7IrTe.gif)

**Comment by drbig** [comment]
Version & platform information?

**Comment by Night-Pryanik** [comment]
Confirming on win 10, 0.C-3706.

**Comment by namarrgon** [comment]
Linux, 0.C-6287-gc1e4131
