### ISSUE TITLE
NPCs attempt to shoot enemies through your vehicle

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#13629]
An allied NPC riding in your vehicle will shoot at enemies even with a solid door/quarterpanel in the way, damaging nothing but your vehicle in the process. It should be changed to check firing line-of-sight instead of just vision, or at least prevent an NPC on an inside vehicle tile from shooting outside.

**Comment by drbig** [comment]
Version & platform info?

**Comment by ejseto** [comment]
Win/Tiles, was up to date when I posted that.

**Comment by drbig** [comment]
Which isn't the answer I'm looking for :) ([hint](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/ISSUES.md))

**Comment by Coolthulhu** [comment]
Confirming it happens in newest experimental.

**Comment by mugling** [comment]
Pretty sure the aiming fixed for NPC's resolved this. Feel free to reopen if I'm wrong

**Comment by serv-inc** [comment]
Just wrecked a my chemistry lab, a windshield, two solar panels, ...
