### ISSUE TITLE
rollerblades/skates don't work diagonally

### ISSUE THREAD

**Issue by canlo** [CleverRaven/Cataclysm-DDA#13636]
They don't work diagonally, it is like going on grass.

**Comment by Rivet-the-Zombie** [comment]
Do you have circular distances turned on? When that setting is enabled, moving diagonally takes extra movement points.

**Comment by Xnfinity** [comment]
With circular distances on, moving diagonally on flat terrain like roads has the same penalty/cost as moving diagonally on dirt/grass, is probably the problem OP is saying

**Comment by Rivet-the-Zombie** [comment]
Indeed - to clarify: rollerblades properly reduce movement costs when moving orthogonally across a smooth surface like a road, but the movement cost when moving diagonally on the same surface results in the exact same movement cost as when on non-smooth surfaces (225 on roads and grass).
