### ISSUE TITLE
Rebalance movement bonuses/penalties against stamina

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#13643]
Stamina is still used by relatively few mechanics. Could have some more uses:
- Rollerblades IRL don't help much with going fast, but do help with not getting tired over long distances
- Being overloaded should cause fatigue before it causes pain
- Pulling/pushing heavy things. Maybe light things too, to make cart pushing less free?
- Fleet footed trait. The +15% to movement speed is now quite weak
- Foot encumbrance vs. leg encumbrance. One of those could cause movement penalty, the other stamina penalty

Anything else?
##

**Comment by kevingranade** [comment]
I'm pretty sure cycling costs need tweaking, probably all of max speed,
stamina cost, and acceleration.
I've seen people commenting that they butcher instead of pulping to work
around the stamina cost of pulping, not sure which way that needs to go but
it's definitely broken if it encourages that behavior.

**Comment by Night-Pryanik** [comment]
>Pulling/pushing heavy things. Maybe light things too, to make cart pushing less free?

This. Especially for fully loaded and thus heavy carts.

>I've seen people commenting that they butcher instead of pulping to work around the stamina cost of pulping, not sure which way that needs to go but it's definitely broken if it encourages that behavior.

Butchering now is a sort of way to restore stamina. Straightforward way to correct this is to add stamina cost to butchering.

**Comment by Headjack** [comment]
I imagine butchering, in the context of revive-stopping, to be a quick eyestab, spinecut, or curbstomp. That's what smash seems like it should be to me, a literal total pulping is probably excessive. Unless we want to find a median between full butchering for meat and disabling a corpse, or say that, yes, a zed needs to be mush before it'll stop moving, then smash should be made quicker and easier, while butchering should be made longer and, really, still pretty easy stamina-wise. It's hardly jogging. The fact that necromancers can now revive even pulped corpses implies that they aren't really mushed so much as excessively disabled, which I think supports the notion that smashing should be seen as a quick, low-stamina action against vital body parts.

**Comment by Headjack** [comment]
Pickaxe and vibrator use should probably affect stamina, instead of fatigue. Right now they seem to put you into sleep-debt instead of make you tired/sore.

**Comment by Coolthulhu** [comment]
> I imagine butchering, in the context of revive-stopping, to be a quick eyestab, spinecut, or curbstomp.

Butchering is supposed to be separating the corpse into usable parts.

> The fact that necromancers can now revive even pulped corpses

This could probably be reverted to old behavior. Smashing corpses in battle should be a good way to stop necros.

> Pickaxe and vibrator use should probably affect stamina, instead of fatigue.

That wouldn't work too well. Stamina is very short term. We'd need some "long term stamina" for it to make sense. It could drain stamina (to 0) in addition to fatigue, though.

**Comment by Headjack** [comment]
It could be a long-term malus or something, maybe? I'm mostly bringing it up because getting extra-sleepy after these things more often than not just makes you feel like you'd lost a night's sleep, which  doesn't feel right. Try using the vibrator three times in a day and it'll basically whomp you with Dead Tired until you take a day to catch up.

**Comment by kevingranade** [comment]
The reason the vibrator in particular increases fatigue is to make it
easier to sleep.  Some effect that does this directly instead of
manipulating fatigue would be the best option I think.

**Comment by Headjack** [comment]
Yeah, I've long wanted cold medicine and sleeping pills to use an 'illusory fatigue' that lets you FEEL tired, then fall asleep and stay asleep long enough to regain fatigue without actually causing you to need more.

**Comment by kevingranade** [comment]
Closing for staleness, yes we want stamina/fatigue/etc to factor into more things, but there's nothing super insightful in this issue.
