### ISSUE TITLE
solid comestible with charge: 1 with a stack_size defined do not stack

### ISSUE THREAD

**Issue by Xnfinity** [CleverRaven/Cataclysm-DDA#13640]
(or does nobody else notice the rock-sized hemp seeds)

http://puu.sh/klync.png

**Comment by Headjack** [comment]
Yeah, hemp seeds are still oversized. I thought it was corrected?

**Comment by mugling** [comment]
Link is dead. Stacking issues should have been resolved by a series of recent PR's. Please re-open if remains of concern
