### ISSUE TITLE
crash in template selection menu

### ISSUE THREAD

**Issue by golgepapaz** [CleverRaven/Cataclysm-DDA#13657]
the change committed in c7de60a and its fix 3e24205 still crashes when choosing a template
offending line is 
   `std::string wn = world_generator->all_worldnames[sel3];` in main_menu.cpp
Crash can be avoided by deleting the line and the conditional below but I have no idea what is the author's intention @VlasovVitaly

**Comment by DanmakuDan** [comment]
It looks like the code causing the crash needs to be moved into the conditional below "// Load Game". It's crashing because it's expecting to be in the load game option in order to prevent a non-Lua build from loading a game save that is using a Lua build.

**Comment by BevapDin** [comment]
Fixed by #13668.
