### ISSUE TITLE
Disassembling bug

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#13650]
The game permits to disassemble robots (I tested on them) even if you get rid of your soldering iron or welder, i.e. with bare hands, after you destroy the robot.

Win 10, 0.C-3722, tiles.

**Comment by Coolthulhu** [comment]
"Get rid" means "drop" or "drop further than 6 tiles from the character"?

**Comment by Night-Pryanik** [comment]
![11111111111111111](https://cloud.githubusercontent.com/assets/11132525/10082146/ff263942-6300-11e5-8d77-3be5687cab42.png)
There's happening something really strange.
The bots in west and east can be disassembled even without tools (welder or soldering iron), if you had them after destroying bots and dropping them on the ground.
The bot to the south can only be disassembled by soldering iron (welder won't work).
The bot to the north can only be disassembled by welder (soldering iron won't work).
"Get rid" means dropping it to the ground (as seen on the pic), distance doesn't had any effect.

**Comment by Night-Pryanik** [comment]
After prolonged testing I came to conclusion that player must have BOTH soldering iron AND welder to disassemble. The strange thing is that only makeshift welder works for this, the ordinary welder doesn't.

**Comment by Coolthulhu** [comment]
The player shouldn't need a welder but a hacksaw. That's a bug - makeshift welder should be handled the same as regular welder here.

Can't confirm any of the tool-less uncrafting.

**Comment by Night-Pryanik** [comment]
Don't pay attention to tool-less uncrafting - this is result of my unclean testing. I simply forgot about 6 tile distance.
Nevertheless the player should have information about what tools he must have to disassemble.

**Comment by Coolthulhu** [comment]
Usually has, just not in the butcher menu.

**Comment by Night-Pryanik** [comment]
Bug in makeshift welder is other issue, so I'm closing this one (it's not an issue at all, after all).
