### ISSUE TITLE
Lasers pistrol triggers window alarm with no damage.

### ISSUE THREAD

**Issue by DodgingRain** [CleverRaven/Cataclysm-DDA#13663]
http://i.imgur.com/QfcsHb1.png

You can take a LACP laser pistol (or any other laser), fire through the windows of a radio station, pawn shop, or gunstore and it will trigger the alarm without causing any damage to the windows.  

Windows 8 Tiles. v3720

**Comment by kevingranade** [comment]
Both of those seem reasonable, lasers intentionally do not break windows,
but it's at least reasonable that there's some way to detect the beam, and
that in a world with commercial laser guns that method would be deployed.
If someone wants to silence the alarm, I'm fine with it either way.

**Comment by Rivet-the-Zombie** [comment]
I rather like the current behavior.

**Comment by DodgingRain** [comment]
I don't mind really.  I was just wondering if it was intended that laser pistols to trigger alarms without breaking the glass.  If it is, I can close this if you wish.

**Comment by kevingranade** [comment]
It's not specifically intended, but I think it's fine to leave it like it
is.
We do appreciate you bringing it up though.

**Comment by DodgingRain** [comment]
Not a problem.  Closing this then.
