### ISSUE TITLE
Crash on FreeBSD creating new game

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#13670]
For build 4a296296 (and likely earlier) choosing New Game -> Preset Character when the save folder is empty results in segfgault

FreeBSD 10.1-RELEASE-p9 on amd64
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512

I'll run this through gdb later and update further

**Comment by mugling** [comment]
#0  basic_string (this=0x7fffffff5920, __str=@0x0) at string:1529
#1  0x0000000000ab58ff in game::opening_screen (this=0x80e1df000) at src/main_menu.cpp:622
#2  0x00000000016f4c74 in main (argc=0, argv=0x7fffffffe910) at src/main.cpp:436

Although offending line recently changed in 3e2420 reverting this commit does not prevent the crash

**Comment by BevapDin** [comment]
This may have been fixed by #13668 (no crash for me), but I'm not using FreeBSD, nor amd64, so someone else has to confirm it.

**Comment by mugling** [comment]
Yes, is resolved on FreeBSD/amd64 by #13668
