### ISSUE TITLE
Impossible to cut metal bars on windows with hacksaw

### ISSUE THREAD

**Issue by OsobistSCP** [CleverRaven/Cataclysm-DDA#13677]
The metal bars in prisons or sewers are cuttable, but metal burs on windows are not. This seems strange because in both cases it's the same metal bar.

**Comment by chaosvolt** [comment]
Hmm. Not sure if error or intended. Trying to work a hacksaw with the window itself in the way might be more awkward.

**Comment by OsobistSCP** [comment]
I think that window's bars should be thinner than prison's bars but not vice versa.

**Comment by Rivet-the-Zombie** [comment]
The problem with the barred windows isn't that their bars are too thick; it's that the bars are backed by some sort of heavy (possibly bulletproof) glass that prevents you from getting the saw in there in the first place.

**Comment by chaosvolt** [comment]
That's basically what my response was suggesting, yeah. :V

**Comment by kevingranade** [comment]
A potential solution is to give terrain and furniture descriptions in
addition to names, then the description could make that kind of thing clear.

**Comment by OsobistSCP** [comment]
For balancing reasons possible to make gunshop's windows actually reinforced. We can cut bars, yeah but glass remains intact and player needs a new solution to break into building (like crush a wall with sledgehammer, quite simple and no alarms activated).

**Comment by Zireael07** [comment]
+1 for terrain descriptions,
