### ISSUE TITLE
Snap-To-Target camera doesn't follow target in tiles mode

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#13675]
Last tested ea94807 in fullscreen on ubuntu 32bit but unknown when it started.

How to test: Start up cataclysm and try to fire a gun with snap to target on, with tiles on and with tiles off.

Expected result: Camera follows reticule around in both ascii and tiles mode.

Current result:
In ascii mode, the camera will follow the reticule. In tiles mode, the snapping still functions, but the camera remains static.
##

**Comment by ejseto** [comment]
There's a comment in the code saying this feature is broken.

**Comment by madprogrammi** [comment]
Confirmed. Had this problem a while ago, and it irked me then. Why is this broken when it's possible to follow the pointer in eXamine mode?

**Comment by Night-Pryanik** [comment]
Tested on latest experimental as of September 27, 2019. Cannot confirm the issue, snap-to-target works fine in both modes.
