### ISSUE TITLE
Cannot put a bomb to RC car

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#13682]
When 'a'ctivating my RC car and selecting "Put a bomb to car", there are no valid options to choose, though I have a bunch of different bombs and grenades in my inventory.

Win 10, 0.C-3738, tiles.

**Comment by Rivet-the-Zombie** [comment]
Are they remotely detonated type bombs?

**Comment by Night-Pryanik** [comment]
Well, I mean I tried not special "radio dynamite" or "radio pipe bomb" versions, but basic versions like black gunpowder bomb with radio activation mod added.

**Comment by Coolthulhu** [comment]
Only radio pipebomb and radio dynamite have the necessary RADIOCARITEM flags.
Changing radio mod item to add them would be quite simple.

Alternatively the tag could be removed and changed to check for RADIO_ACTIVATION, BOMB and some volume and weight comparison. This would have the benefit of not requiring re-applying the mod in old saves.

**Comment by Night-Pryanik** [comment]
I chose the @Coolthulhu's first proposition and PR'ed it (https://github.com/CleverRaven/Cataclysm-DDA/pull/13684).
