### ISSUE TITLE
APC Vehicle Layout oddity.

### ISSUE THREAD

**Issue by DodgingRain** [CleverRaven/Cataclysm-DDA#13686]
For some reason, in the two seats in the APC, the vehicle control and the camera control at on two different seat.  This results in a situation that if you sit in the driver (left) seat, you can see a very narrow area ahead of you while if you sit in the other front seat, you can see in almost all direction (with very tiny blind spots).  I'm not sure if this is an error or but but it seems rather odd and doesn't quite make sense realistic wise (unless I am missing something).

**Comment by illi-kun** [comment]
I did it intentionally: gunner should have 360deg vision, so cameras are used, and driver doesn't obtain it for simulating the fact that typically APCs provide limited view. But I agree that combination of these two points doesn't work well and seems to be irrational, so I'm ready to add camera controls at driver's seat (it will be a great buff of APCs, which are great vehicles already).

**Comment by chaosvolt** [comment]
I was pondering whether to do the same with Tank mod vehicles, but wound up giving the driver and gunner cameras. Depending on if @illi-kun changes things or not, I should probably shift the driver's camera setup to the commander's position.

**Comment by kevingranade** [comment]
Any looking into this has only increased confidence that the driver of an APC typically has very restricted FoV.
