### ISSUE TITLE
CBM interfering with rotting?

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#13687]
Do installing the Recycler Unit and/or the Expanded Digestion CBMs cause food in the inventory, particularly meat, to stop spoiling? Ever since using them it seems like meat isn't going bad. I don't know why that would happen, but I keep noticing it.

Confirmation needed, but I think I have a pretty good idea of when it normally rots. If it's just me being able to eat rotten food, that should be conveyed differently.

**Comment by ejseto** [comment]
Meat won't rot below a certain temperature (I think 50F). It might just be coincidence that the meat isn't rotting.

**Comment by Coolthulhu** [comment]
Pretty sure it should not be possible for CBMs, mutations or any other player state to influence food rot.
Probably just temperature.

**Comment by Headjack** [comment]
Temperature might be it then; it is autumn. I'll reopen this if it's still happening in warm seasons.
