### ISSUE TITLE
Robber NPCs sometimes shoot at you when you raise your hands in surrender

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#13690]
Not sure if bug or just really scumbag move, but it happens. If it's intentional, maybe there should be some feedback, perhaps depending on perception, of how likely your character thinks the robber is to attack you when you're defenseless.
##

**Comment by Coolthulhu** [comment]
Currently the only way NPCs can recognize other NPCs is by randomly stumbling into them.

**Comment by chaosvolt** [comment]
> Currently the only way NPCs can recognize other NPCs is by randomly stumbling into them.

This is an issue about NPC actions towards the player, though. Unless the description in the OP implied something involving NPC/NPC relations before being edited? ;w;

**Comment by mugling** [comment]
Closed as unconfirmed
