### ISSUE TITLE
KSG intergated gunmod, possibly others

### ISSUE THREAD

**Issue by Xnfinity** [CleverRaven/Cataclysm-DDA#13692]
It is possible to remove an internal mod by "unloading" when the gun is empty i would guess it just missing the unremoval flag or something along them lines

ref img > http://puu.sh/ktDAW.png

(minor nitpick.. it uses the underbarrel slot, probably due to been copypasted off one of the underbarrel shotguns but it doesn't really make sense to me to take that slot...)

**Comment by Midaychi** [comment]
I can confirm this. I can also confirm that the KSP mod lets you load an infinite amount of ammo until you unload it and attach it to a new gun, then it properly handles ammo cap.

**Comment by chaosvolt** [comment]
Ack. Still unsure how to solve that. @_@

And the underbarrel slot would be due to copy-pasting, though also because I wasn't sure where to slot it. Magazine might've been the more logical choice.

**Comment by Midaychi** [comment]
Or Mechanism.

**Comment by chaosvolt** [comment]
That could work, yeah. That reminds me, I don't think most mods apply their effects to attached weapon mods...

case in point, slap a brass catch on the KSG, switch to the second tube.

**Comment by Xnfinity** [comment]
Tried the 'IRREMOVABLE' flag? as for mods effecting mods-weapons... 
You could just be a cheap and remove other mod slots outright

(also did you solve the flintlock+space mag)

**Comment by chaosvolt** [comment]
Hmm. This thing already SHOULD have the irremovable flag though. ;w;

And...doh. I forgot that. @_@

**Comment by chaosvolt** [comment]
So, I just realized something. Wouldn't the ideal solution be to just remove the ability to uninstall gunmods via unloading?

Codewise I can't figure out how to add a way to exclude integral mods from the mod-removing function, whereas just disabling that function would be easier to do. For guns, removing gunmods is the entire reason the activate option has been hijacked. Meaning for modded electronics, you're expected to use a screwdriver on it.

**Comment by kevingranade** [comment]
Is overloading unload to remove gunmods a problem from a UI point of view?
It seems like a pretty handy feature to me.

**Comment by chaosvolt** [comment]
Hmm. I'm not not sure if it's essential, but...on the one hand, I've never found it any more or less convenient that activating the weapon instead.

On the other hand, I've never accidentally removed all my gunmods by hitting unload too many times.

Might be better to find a way to make the unload function ignore integral gunmods, if people find removing the mods via unload to be useful. As it stands it's not an essential feature, but some people might find it useful. Unsure.

**Comment by BevapDin** [comment]
> Is overloading unload to remove gunmods a problem from a UI point of view?
> It seems like a pretty handy feature to me.

It's a bit unexpected behavior and it's redundant: one can remove all mods by activating the gun, the menu there has the option to remove all mods at once.

> On the other hand, I've never accidentally removed all my gunmods by hitting unload too many times.

I did, and it's annoying. Therefor I support removing that behavior from the unloading action.

**Comment by Zireael07** [comment]
+1 to removing the possibility to Unload gunmods.

**Comment by chaosvolt** [comment]
Hmm. Since I'm unsure how to rig the unload code to ignore integral gun mods, guess I could do so.

**Comment by Xnfinity** [comment]
I have had more problems with unloading gunmods form my weapons due to using unload to unload things at my feat any forgetting i had my weapon in hand at the time...

I guess this is fixed now

**Comment by chaosvolt** [comment]
There are some minor bugs involving gunmods in general, as Coolthulhu mentioned in the PR, but thankfully the oddball stuff like this shouldn't recur.
