### ISSUE TITLE
"You can't wear x with power armor" is order dependent

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#13707]
* Can't put on protective mouthpiece with power armor (body, not helmet) on despite no collision
* Can put power armor while wearing mouthpiece, at least from the ground
* Can put infrared goggles while wearing power armor helmet(!)

**Comment by Barhandar** [comment]
>Can put infrared goggles while wearing power armor helmet(!)

Aren't infrared googles relatively large strap-on thing, so as long as eyeports line up, you'll be able to strap them over the helmet? Similar to "should be able to put a hat on most helmets" thing.

**Comment by Night-Pryanik** [comment]
Should be closed after #14764? At least for the mouthgear part.

**Comment by Coolthulhu** [comment]
I don't see that PR changing the goggle part, though.

**Comment by Night-Pryanik** [comment]
Well, I agree with @Barhandar on goggle part, but not sure if @kevingranade accept it after our discussion in #14764.

**Comment by Coolthulhu** [comment]
Wearing goggles on heavy, bulky helmet with a visor unadapted to having an extra pair of goggles over it would be quite tough.

**Comment by kevingranade** [comment]
You definitely should not be able to wear unmodified it goggles with a PA
helmet.

My statement at the end of #14764 was that the proposed change was
unacceptable, and any similar changes would meet a lot of resistance, not
sure where you got the impression of ambivalence.
