### ISSUE TITLE
Some explosives with radio activation mod detonate with delay

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#13711]
This issue was derived from discussion in https://github.com/CleverRaven/Cataclysm-DDA/pull/13684.
For example, using the radio control to activate the radio-modded grenade makes it detonate after 4 turns rather then immediately. Also tested on black gunpowder charge. Incendiary grenade works as intended.

Win 10, x32, tiles, 0.C-3749.

**Comment by Coolthulhu** [comment]
I couldn't replicate on:
Win 7, x32, tiles and console, 0.C-3749 downloaded from jenkins and built in GCC-4.9.1

I think I have a suspect in the code: undefined behavior related to `list::erase` followed by reinsertion. Win 7 may have more predictable behavior there, which would explain why I can't replicate it.

I'll try to fix it, but I won't be able to test if the fix actually fixes it.

**Comment by Night-Pryanik** [comment]
You could send build with your fix to me, and I'll test it.

**Comment by Coolthulhu** [comment]
Merge my patch (from the linked PR above) to your PR. It shouldn't cause conflicts.
