### ISSUE TITLE
Inconsistency in battle rifle description

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#13722]
Looking at the description for the battle rifle, it states that the weapon holds thirty rounds of rifle ammo, but the ammunition entry for the same weapon says twenty rounds.

![Image](http://i.imgur.com/jA4s6M6.png)

**Comment by narc0tiq** [comment]
The static description probably shouldn't mention magazine size at all,
given that there are ways to change them (e.g., gunmods).

**Comment by vache** [comment]
Note: this is from the generic guns mod.

**Comment by chaosvolt** [comment]
I was gonna say, from the issue title alone, I initially assumed it was concerning the battle rifle conversion gunmod.
