### ISSUE TITLE
Build error in linux under file test_main.cpp

### ISSUE THREAD

**Issue by heema** [CleverRaven/Cataclysm-DDA#13731]
using arch linux 64

while compiling with the command
make CLANG=1 CCACHE=1 RELEASE=1 TILES=1 SOUND=1 LUA=1

gives this error:
test_main.cpp:34:12: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
    g->m = std::move( map( static_cast<bool>( ACTIVE_WORLD_OPTIONS["ZLEVELS"] ) ) );
           ^
test_main.cpp:34:12: note: remove std::move call here
    g->m = std::move( map( static_cast<bool>( ACTIVE_WORLD_OPTIONS["ZLEVELS"] ) ) );
           ^~~~~~~~~~~                                                            ~
1 error generated.
Makefile:41: recipe for target 'obj/test_main.o' failed
make[1]: *** [obj/test_main.o] Error 1

![errcomp1](https://cloud.githubusercontent.com/assets/287527/10364756/79ece6e0-6dbe-11e5-9699-179971ca97bb.jpg)

**Comment by kevingranade** [comment]
Some people went std::move() happy a while back, looks like we'll want to
back at least some of them out.  Thanks for reporting.

**Comment by heema** [comment]
This issue can be closed now as its working with the fix thanks
