### ISSUE TITLE
Game crashes during the drizzle

### ISSUE THREAD

**Issue by OsobistSCP** [CleverRaven/Cataclysm-DDA#13737]
Game crashes when drizzle weather is due. If weather changed to "clear", everything is okay. Game's modified, so below links to my build as-is and save file in place where crash happens.

https://www.dropbox.com/s/8w6llr57kzc2dm2/Cataclysm%20DDA.rar?dl=0 - game itself with all mods and settings.
https://www.dropbox.com/s/rmsase8rkvdqzf9/save.rar?dl=0 - save file.

**Comment by tivec** [comment]
I loaded up this save and set of mods on linux64 and ran a backtrace. The game crash is:

`/usr/include/c++/4.9/debug/vector:364:error: attempt to subscript container with out-of-bounds index 42, but container only holds 42 elements.`

Backtrace shows that it happens in weather.cpp line 265, `fill_funnels` as it is calling `g->m.trap_locations(tr.loadid)`

**Comment by kevingranade** [comment]
What exactly do you mean by "game is modified"?

Did you add some trap definitions?  If so it will scramble the load order of traps, and this is one of the possible outcomes.

**Comment by tivec** [comment]
```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   mods/Arcana/monster_drops.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	mods/Animatronics/regional_map_settings.json
	mods/Arcana/mapgen.json
	mods/Artyoms' Gun Emporium/
	mods/AutoGasStations/
	mods/Carlos_Turrets/
	mods/DinoMod/regional_map_settings.json
	mods/Duros'_Doings/
	mods/EXTENDED_BUILDINGS/
	mods/Jury_Rigged_Robots/
	mods/Locations_plus/
	mods/Medieval_Stuff/martial_arts_manuals.json
	mods/Medieval_Stuff/martialarts.json
	mods/Medieval_Stuff/mutations.json
	mods/Medieval_Stuff/overrides.json
	mods/Medieval_Stuff/professions.json
	mods/Medieval_Stuff/recipe_shields.json
	mods/Medieval_Stuff/shields.json
	mods/Medieval_Stuff/techniques.json
	mods/Medieval_pack/
	mods/Nanites v0.5/
	mods/Nimian_Manufacture/
	mods/Payday_pack/
	mods/RemoteVehicles/
	mods/Remote_Control/
	mods/Survivor_Mod/
	mods/Tanks/dummied_out.json
	mods/Tanks/overmap_specials.json
	mods/Tanks/overmap_terrain.json
	mods/Wilderness_Overhaul/
	mods/old_guns/

no changes added to commit (use "git add" and/or "git commit -a")
```

Mostly mods, but it's possible at least one of them adds a trap or two.

**Comment by OsobistSCP** [comment]
Game is using mods, that what I wanted to say. no additions in code. Trap definitions? Tivec said that it might be a problem with funnels. In my case funnels are touched in next lines:
![image](https://cloud.githubusercontent.com/assets/11258465/10412621/4d97c876-6fad-11e5-874e-1a4922ebdfa3.png)

**Comment by Coolthulhu** [comment]
I think I get it:
* `g->m.trap_locations(tr.loadid)` simply returns the size of `traplocs` vector
* This vector has the same size as `trap::count()`, which in turn has the size of `trap::trapmap`
* Since `trapmap` is a `std::map`, overwriting elements in it does NOT increase its size
* However, on overwrite, trap's `loadid` is bumped up to size of `traplist`, which DOES increase when overwriting a trap, as if a new trap was created

As a result, overwriting a trap (in a mod or otherwise) gives the trap an id that is equal to or larger than the biggest valid position in `traplocs` vector.

Proper fix would be to actually handle overwriting traps by detecting id collisions. Until this is done, no mod can overwrite a trap. Or at least a funnel, as `traplocs` seems to be only ever used for those.

**Comment by chaosvolt** [comment]
Looking up and seeing a shitload of old content from my mods (dummied-out tank mod mapgen, the old Cleansing Flame mapgen file in arcana mod) plus the not-yet-PR'd hacky shields made me worry for a moment that something in there was the cause. >.>

**Comment by OsobistSCP** [comment]
I've temporary removed the "override" section from "Wilderness Overhaul" mod. For now everything seems fine, so maybe this is the source of trouble.

**Comment by chaosvolt** [comment]
Ah, weird. o.O

**Comment by Coolthulhu** [comment]
> Ah, weird.

I explained exactly how does it happen.

**Comment by chaosvolt** [comment]
Right. I'm guessing that specific mod included a trap or trap override?

I'm glad I changed upright swords to be furniture instead of a trap. >.>
