### ISSUE TITLE
Small mapgen errors

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#13743]
I'm having problems with GitShell, so can someone fix these?
In house_quiverfull.json trashcans inside and outside should be separated so it doesn't spawn dirt inside.
In house_duplex.json there's wooden floor under trashcan outside.

**Comment by chaosvolt** [comment]
Holy shit, MShock's alive. o3o

And...hmm. I've seen similar errors in the bandit camp, if I recall.

**Comment by Mshock777** [comment]
Also house_modern_lx.json has some items designated to be placed inside a wall, but I'm not sure that's causing them to spawn outside.

**Comment by chaosvolt** [comment]
Doh. Might need to look into that.

And ah, I see. I haven't yet considered adding overlays, actually. Still been steadily adding updates for unsprited stuff in general. ^^"
