### ISSUE TITLE
Message Log Spamming

### ISSUE THREAD

**Issue by sctjkc01** [CleverRaven/Cataclysm-DDA#13744]
I've got an issue coming from version d213304 (Windows Tiles): my message log is being spammed with a large amount of information with every step I take:

![image](https://cloud.githubusercontent.com/assets/1090204/10420283/dda6eb3a-705d-11e5-902e-403613781e2d.png)

Oddly, as I was reporting this, the game corrected itself and stopped soon after.  Regardless, a save file for right around this point is available right [on my Dropbox](https://dl.dropboxusercontent.com/u/21179667/cdda/cataclysmdda-0.C-EXP.zip).

**Comment by ejseto** [comment]
Debug mode is on. Either you turned it on by accident (I *think* the default key is ~), or an NPC didn't use its moves and the game turned it on for you (why does it do this).
