### ISSUE TITLE
fungaloid turns zombie dog into (human) fungal zombie

### ISSUE THREAD

**Issue by btbonval** [CleverRaven/Cataclysm-DDA#13742]
I'm in 0.C running around a fungal bloom.

A zombie dog starts attacking a fungaloid, brings it to severely injured, then:

> The zombie dog hits the fungaloid! x 2
> Spores are released from the fungaloid!
> The zombie dog is covered in tiny spores!

Poof. No more zombie dog (thankfully). Instead, there is a big grey Z: a fungal zombie with the description "Once human..."

That makes sense when the zombies are humanoid, but not other kinds of zombies. Perhaps the fungal zombie description should be less specific to humans, or perhaps there should be different kinds of fungal zombies.

**Comment by Rivet-the-Zombie** [comment]
I shall call him *Sharik*.

**Comment by illi-kun** [comment]
Previously, only professors were able to do that, and now any mindless fundaloid can do the same... I'm calling this progress.

(Rivet, that's impressive knowledge of Russian literature).

**Comment by btbonval** [comment]
Yeah I had to look up the reference to Sharik. The only Russian literature I've read is Baba Yaga.

I might be more inclined to believe I just met the Fungaloid equivalent of Dr. Moreau.

**Comment by btbonval** [comment]
Description of fungal zombie is here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/0.C-branch/data/json/monsters.json#L2096-L2125

Looks like code to convert into fungal slave is here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/0.C-branch/src/monster.cpp#L1505-L1552

Here is the list of monsters which convert into fungal zombie.
https://github.com/CleverRaven/Cataclysm-DDA/blob/0.C-branch/src/monster.cpp#L1518-L1527

"mon_zombie_dog" is clearly in that list. In the newest version, zombie dogs are not in any poly list, so they are probably not converted to any kind of fungus.
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/monster.cpp#L1790-L1853

It looks like this bug might be fixed in master. Too bad, it was quite handy having the zombie dog dealt with by the fungaloid.

**Comment by chaosvolt** [comment]
Hmm. Could be useful to add some sort of canine fungal zombie, even if this bug as been fixed.

**Comment by btbonval** [comment]
I fully support a feature request (to continue) allowing fungaloids to eliminate the zombie dog nuisance.

To consider for conversion:
* zombie dog (`"mon_zombie_dog"`)
* rot-weiler (`"mon_dog_zombie_rot"`)

For Z-9 (`"monster_zombie_dog_cop"`): does the distinction between zombie dog and Z-9 matter for fungal conversion? I think the difference is armor. Maybe the fungal infection dissolves armor.

The skeletal dog (`"mon_dog_skeleton"`) doesn't seem as obvious for turning into a fungus. I don't really know much about the physiology or mycological implications of a skeletal being, though.

I think that covers all the dogs in the zombie faction.

**Comment by Coolthulhu** [comment]
The whole fungal conversion function needs to be rewritten.
It is inherently bad - a huge block of hardcoded special cases.
Should be changed to be a property of monster type: `"fungalizes_to": "monster_type_here"`, with only 3 special cases: converting to stated monster, damaged on fungalization attempt and immune to all fungalization.

Does this bug still happen in current experimental? If not, it should be closed (bug reports are for experimentals).
Discussion about fungal dogs can get a separate issue that doesn't have a bug report attached.

**Comment by btbonval** [comment]
I'm not currently running experimental, but looking at master and comparing to the bug I found in 0.C, I don't see how it is possible that this bug persists.

If fungal zombie dogs are still desired as a feature, perhaps I'll leave that to @chaosvolt to file as a new issue. Sounds like exact implementation might change soon regardless.
