### ISSUE TITLE
Segfault after crashing into the back of a motel

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#13776]
Was driving around and accidentally made too sharp a turn, slammed right into the backside of a motel and through a bathtub, then crash. Luckily I was running symbolized cataclysm through GDB at the time, and I compiled it with -0g.

https://dl.dropbox.com/s/axcecljnxkdoe02/gdb.txt

Here's the last save before the crash and the non-standard mods I'm using. I hadn't explored up the north road yet, where the motel generated past the swamp. Not sure I could reproduce the crash reliably, but at least you can see my vehicle setup in case that's important.

https://dl.dropbox.com/s/kwgmx93m6etw0nk/Pond%20Creek_.zip
https://dl.dropbox.com/s/9ifhkqqsg84a1gp/3rdprtymods.zip

Edit: actually looking at the backtrace, it _might_ have had something to do with the portal cargospace I have from arcana mod, but not sure and I didn't see it get damaged or even touched during the crash.. Crammed full of junk, it is.
##

**Comment by drbig** [comment]
Bonus point for the stack ~~trace~~ bomb.

**Comment by drbig** [comment]
(Confirmation needed for replication on current. Didn't read the stack bomb)

**Comment by Midaychi** [comment]
I'll try to replicate it with a closer save.

**Comment by drbig** [comment]
Aye, that would count as replicated (btw. in case you haven't noticed I do slap `Confirmation Needed` on most stuff, please don't take it personally).

**Comment by Midaychi** [comment]
Derp. Just crashed into the motel, after having to move an suv out of the way by installing wheels from a hatchback down the road and everything. Didn't even stutter, let alone crash. Might have to go at this from a few angles.

**Comment by Midaychi** [comment]
Nope. I've crashed into this motel backside at least 10 times at different angles and speeds. Works just fine now.

**Comment by drbig** [comment]
Aye. I'll keep the issue open in case the traceback is useful (I'll need to actually "read" it, won't hurt to have this on here in any case).

**Comment by Midaychi** [comment]
The only difference I could think of is that I might have been skidding at the time. There was a lot of wildlife I was plowing through on the crash play.

**Comment by DanmakuDan** [comment]
It's a divide by zero error at line 4462 in vehicle.cpp:
```vpart_dens /= vpart_item_mats.size(); // average```
It sounds like whatever is taking damage here is not made from other items, so the divide by zero happens and crashes the game.

**Comment by Midaychi** [comment]
That's odd. Maybe a frame got smashed off and a ram that was attached to it was left floating? Or heck, I dunno what could cause that.

**Comment by DanmakuDan** [comment]
It's probably the cargo dimension that took damage, it's not made of any components ("breaks_into" in the json). The divide by zero happens because normally every vehicle part specifies what it consists of so vehicle physics can be calculated when it bumps into something.

**Comment by Midaychi** [comment]
So, short term fix is to fix the arcana mod's entry, long term maybe code in a default components that takes effect if the part has no components defined?

**Comment by kevingranade** [comment]
Or a sanity check that refuses to load json if the part isn't specified, it
should probably be mandatory.

**Comment by mugling** [comment]
> It's a divide by zero error at line 4462 in vehicle.cpp:
> vpart_dens /= vpart_item_mats.size(); // average

Code has changed considerably since then
