### ISSUE TITLE
Nuclear missile not valid way to complete "Kill Bandit Leader"

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#13770]
So I got this mission, thinking "Ok this'll just be a short walk in the woods like usual", but then it takes forever to generate and shows up over 400 units away from the survivor center. 

In light of this information, I went to a missile silo I had found earlier and hacked it, and launched said missile at Bandit Leader's location. "Surely this will complete the mission, right?"

![toughnpcs](https://cloud.githubusercontent.com/assets/1968809/10554813/dfdf3594-741b-11e5-9c39-5b1e2273f2ad.png)
##

**Comment by Rivet-the-Zombie** [comment]
We really ought to fix this one. Your solution is the best use for missile silos I've ever heard.

**Comment by chaosvolt** [comment]
I remain disappointed in the effect of silo nukes on things outside your reality bubble. ;w;

**Comment by Midaychi** [comment]
Maybe Nuclear Missling somewhere should give you a 'camera view of the area asploding'? That way it loads it into reality bubble, then asplodes it, then returns you back.

**Comment by chaosvolt** [comment]
Hmm. That reminds me, does the nuke do any damage in the unlikely event that you DO target something in your reality bubble?

As it stands, I think that CAN occur if you enable z-levels.

**Comment by ZhilkinSerg** [comment]
No nuclear launches anymore after #35242.
