### ISSUE TITLE
2.5l canteen encumbrance seems unreasonably high

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#13779]
Currently, the 2.5l canteen has an encumbrance of 10. I can understand it if they have increased weight for the water, but it's really not that much an encumbrance if you have a canteen strapped to your belt is it?

My suggestion would be to drop it to 6, perhaps 8, it seems more reasonable.

**Comment by Rivet-the-Zombie** [comment]
I second this.

**Comment by tivec** [comment]
Let me whip up a PR then.

**Comment by tivec** [comment]
While looking, it seems the military-style cantenn (1.5l) has 0 encumbrance. I'm going to drop the 2.5l one down to 4.

**Comment by tivec** [comment]
Pull request fail from my side there, pushed several commits that were not supposed to be and then rebase refused to work my way. Ah well, PR #14781 is the right one :P

**Comment by Midaychi** [comment]
You mean 13781?

**Comment by tivec** [comment]
Yes... #13781. Haha!
