### ISSUE TITLE
Picklocking doesn't spend any time

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#13772]
Neither successful, nor unsuccessful using of picklock appears to happen without spending any time on it.
![222222222222222222](https://cloud.githubusercontent.com/assets/11132525/10557264/48bb377a-74ad-11e5-895a-45be6793c3dd.png)
0.C-3790, Win 10, tiles.

**Comment by drbig** [comment]
Anyone cared to replicate? Also my feeling (haha) is this should be an easy-fix.

**Comment by Rivet-the-Zombie** [comment]
Confirmed; no time is used to pick locks.
