### ISSUE TITLE
Water poison fixes required

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#13774]
Water pumps currently give clean water without poison. They should not. This issue is more a remined for myself to fix these things up when I'm in my dev environment, but anyone can have a stab at it :)
- Update `map::water_from` to include `t_water_pump` with a chance for poison. We can probably use similar values as `t_water_sh`
- Update `inventory::form_from_map` to properly call `map::water_from` when creating water.
- Check through the code if water is created from the map in other ways and fix them too.
##

**Comment by stk2008** [comment]
Hi

I might be miss reading this but do we have pumps with pipework now? :o

**Comment by Midaychi** [comment]
No, the handpumps that you often find at farms. Also, aww. I was fond of my infinate clean water source.

**Comment by stk2008** [comment]
Ah I see :)

Thanks for replying

**Comment by tivec** [comment]
> Ok I guess it could be clean in certain circumstances, but catadda isn't that granular.
Yes, well, you have the rng function, so there could be a chance in x that you get dirty water. Was planning for something like that as it is on pool water and rivers.

**Comment by Midaychi** [comment]
Honestly dirty water in cata should infect you, to fit in more with the lore.

**Comment by chaosvolt** [comment]
I'm still disappointed at the fact that you get dirty water from toilets. I'm sorry, are we all canine mutants? Why are we drinking out of the bowl when the tank has clean water?

Granted, the tank could potentially be dirty, you might also have bits of rubber if the flapper is old, but still. >.>

**Comment by Rivet-the-Zombie** [comment]
>Honestly dirty water in cata should infect you, to fit in more with the lore. 

You're already infected. Everything is already infected.

**Comment by chaosvolt** [comment]
> You're already infected. Everything is already infected.

Kill it with fire. ;A;

**Comment by tivec** [comment]
It's just a matter of time.

**Comment by Headjack** [comment]
I always figured that you're just part of some .001% of humans whose bodies can fight off the pathogens, thus accounting for why there are only a few postapoc survivors and no holdout, well-defended positions formed pre-cataclysm, like a functioning military base.

**Comment by Midaychi** [comment]
Well it's not.. *technically* a pathogen.

**Comment by chaosvolt** [comment]
Still, I'm fairly certain that the food poisoning from water is because of mundane pathogens, not the blob. I think. <.<

**Comment by drbig** [comment]
(Haven't read the backlog)

My points:

I think it would be nice to have water being poison a chance thing by source:
  - toilet: high ~60/70%
  - standing water: medium ~50/60%
  - rainfall/river: low: ~30/50%

In general the balance is again tightly packed at starting and that's OK imo. Having this kind of gradation should be cool though.

**Comment by chaosvolt** [comment]
I could've sworn the wiki claimed this did indeed occur, assuming you drink it straight.

Even if that's true, it's presumably likely that filling up a container with it first bypasses this.

**Comment by Coolthulhu** [comment]
> I think it would be nice to have water being poison a chance thing by source

It is already a thing.

**Comment by chaosvolt** [comment]
That's what I thought, assuming the wiki wasn't wrong.

Still, if I recall filling a container with said water doesn't preserve that information, does it?

**Comment by Coolthulhu** [comment]
Pretty sure it should pass the poison from the first water put into the container.
Meaning that if you have a poison-less water container, you can keep refilling it with sewer water and it will not become poisonous, as long as you don't empty it at no point.

Water poison should probably be reworked and unified. Having different poison values is a minor detail, not worth keeping this badly designed system for.
A single "is poisonous" flag would be better than all that stuff that isn't properly passed around, requires an entire variable for itself that isn't used by any other food item (fun fact: it isn't only used by water, but also by charger guns. if you could eat charger guns, they would poison you) and is hardcoded rather than being jsonized in any way.

**Comment by chaosvolt** [comment]
> A single "is poisonous" flag would be better than all that stuff that isn't properly passed around, requires an entire variable for itself that isn't used by any other food item (fun fact: it isn't only used by water, but also by charger guns. if you could eat charger guns, they would poison you) and is hardcoded rather than being jsonized in any way.

That just gives me hilarious mod ideas.

**Comment by IOSYN** [comment]
Groundwater wouldn't necessarily be filled with bacteria. It's filtered through hundreds of tons of clay, sand, silt, rock etc. Obviously lore/goo is already in it, but poisonous? 
Cleaner than drinking from a toilet at least. I'd say a 25-35% chance for the groundwater max.

Remember the toilets might have... leftovers in. 
Not to mention the UV light test that bleach/toilet cleaner adverts are so fond of.

Rainwater again shouldn't be poisonous. It's effectively filtered by precipitation/condensation, although having more weather effects such as poisonous, polluted or acid rain would be fun. 
A polluted/poisonous smog/fog weather effect might be nice. Drastically cut vision, maybe screw with scent.

**Comment by chaosvolt** [comment]
> Remember the toilets might have... leftovers in.
Not to mention the UV light test that bleach/toilet cleaner adverts are so fond of.

Again, is there a reason we're drinking from the bowl? This makes a negative amount of sense.

**Comment by kevingranade** [comment]
chaosvolt: The game does assum the water retrieved from a toilet is from the tank.  Please open the tank of a toilet in a not-brand-new house and seriously ponder to yourself how potable it looks.  Every tank I've ever looked in has had mysterious things growing in it.  As a last resort in a survival situation, very preferably after treatment of some kind, yea it'd be an option, but I would not consider toilet tank water safe.

More generally, most water sources in the game are somewhat more unforgiving than IRL, the reason for this is to make survival somewhat challenging, the rationale is that the goo or something similar has infiltrated most water sources and makes them more dangerous.  Just because you're already infected doesn't mean that repeated exposure to more goo is safe.  This is similar to the overly-harsh "cold" and "flu", which are actually neither, they're flare-ups of your goo infection.

**Comment by tivec** [comment]
> >Remember the toilets might have... leftovers in.
Not to mention the UV light test that bleach/toilet cleaner adverts are so fond of.

> Again, is there a reason we're drinking from the bowl? This makes a negative amount of sense.

We're not drinking from the bowl. The cistern fills up with (relatively) clean water. Now, I wouldn't drink from it myself, but during an apocalypse I guess why not...

> Groundwater wouldn't necessarily be filled with bacteria.
> Rainwater again shouldn't be poisonous. It's effectively filtered by precipitation/condensation, although having more weather effects such as poisonous, polluted or acid rain would be fun. 

I'm not going to change the lore, as per @kevingranade the ground water is polluted. As for rainwater being clean or not, maybe "poisonous" isn't the word for it, but that is the functionality that is in the game per today. Perhaps that can be expanded on over time, but that's out of the scope of this issue, I think.

**Comment by chaosvolt** [comment]
I have mentioned that it wouldn't be an ideal option, yes. It likely would still be less risky than taking it straight from a river though, whereas the odds of sickness from toilet water relative to other sources don't reflect this. >.>

**Comment by tivec** [comment]
I'm not a plumber but... I wonder if bacteria creeps up into the reservoir of the toilet...

**Comment by Nymall** [comment]
Bacteria, algae and insects can crop up in the reservoir. It really depends on where you're getting the water from, the temperature and how long it's been sitting there. General rule of thumb is that all city water is going to be treated chemically, while well water(which may be better or worse, depending) has not, as well as well water having a larger volume of natural minerals, easing growth. It is very much dependent on the systems at play, and how well they are maintained.

**Comment by Nioca** [comment]
> Just because you're already infected doesn't mean that repeated exposure to more goo is safe. This is similar to the overly-harsh "cold" and "flu", which are actually neither, they're flare-ups of your goo infection.

Wait, if that's the case, then why does a Flu Shot prevent you from getting goo-flu? (Glu?)

**Comment by vache** [comment]
I like to imagine that instead of being goo illness, the super powered illnesses are just goo-boosted normal bacteria and viruses.

**Comment by drbig** [comment]
> I like to imagine that instead of being goo illness, the super powered illnesses are just goo-boosted normal bacteria and viruses.

I like this line of reasoning (so goo is smaller than a virus then? that's proper magic :D)

**Comment by chaosvolt** [comment]
Nanomachines, son.

Or would be picomachines at that point?

**Comment by Midaychi** [comment]
Goo is a substance from the subprime. Its either a communal micro-organism or just a chemical with weird properties. It can attach to shit to give it a touch of the magical eldritch. Its properties are not limited to animation, but really depend what you're fiddling it with.

Zombies, blobs, fungus, those weird monsters that pop out of portals, Jabberwocks, etc all have tainted meat or poisonous goo in them, and are examples of the long term effect of blob

Mutative chemicals, radiation-mutation, mutated but not tainted animals like bees and wasps and ants and swamp creatures that aren't full of tainted meat/at, triffids, worms, and modified normal diseases are examples of stuff that's been effected by blob but not tainted by it.

**Comment by drbig** [comment]
Actually nanomachines might cut it:

> Most viruses that have been studied have a diameter between 20 and 300 nanometres

> [on nanomachines] with devices ranging in size from 0.1–10 micrometres and constructed of nanoscale or molecular components [0.1 micrometers = 100 nanometers]

So the traditional-SF swarm of `gray goo` could potentially edit viruses too. I'm still not happy with the perpetual-motion zombies though (I'll plug in Peter Watt's Echopraxia here and the pretty sound future-tech p-zombies; wouldn't make for a zombie apocalypse unfortunately).

**Comment by chaosvolt** [comment]
Wow, when's the last time having me reference a dumb meme actually helped? o3o

**Comment by Midaychi** [comment]
I guess technically, goo could be a nanomachine sized wibbly wobbly. Maybe the previous earth's 2040 made them?

**Comment by IOSYN** [comment]
>I like to imagine that instead of being goo illness, the super powered illnesses are just goo-boosted normal bacteria and viruses. 
> - vache
+1. That's enough handwavium to justify it I think.

As to Nanomachines... Feels a little too much of a copout. Humans already have a pretty good general idea about the field and it kinda takes the mystery out of the subprime/nether stuff.

Besides, there's the superscience we understand and the superscience we don't. How about something like a sub-atomic contagion, or a quantum energy virus?

**Comment by Midaychi** [comment]
Now you're just adding pseudoscience prefixes.

**Comment by chaosvolt** [comment]
Meh, I quite prefer keeping it ambiguous as to whether the extradimensional entities are supernatural in nature. o3o

**Comment by IOSYN** [comment]
The point I was getting at is that we need to keep the ambiguity. 
Doesn't matter what it's called but nanomachines are too easily understandable-- hell we might actually have nanomedicine IRL by 2040.  

Also it's amazing how far we've gotten off track for a proposed change to poisoned water.

**Comment by drbig** [comment]
Don't want to spoil the fun but this has been derailed enough... I get an email for every comment here, and general musings seems best suited to for the forum.

**Comment by Oskar636** [comment]
Still an issue in build 5864 windows 64bit tiles

**Comment by WizardOfOoo** [comment]
Why not just change water pumps to output "water" instead of "clean water" and close this issue?

**Comment by Night-Pryanik** [comment]
Water from water pump is ordinary water, not clean water.
