### ISSUE TITLE
Corrosive zombie's acid spit fly through windows with bars

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#13773]
![default](https://cloud.githubusercontent.com/assets/11132525/10557276/b0e9aa98-74ad-11e5-8499-a29d3e6d6eb5.PNG)
0.C-3790, Win 10, tiles.

**Comment by Coolthulhu** [comment]
I'd say it's intended. Spitter spits a big glob, corrosive only a small one. Or possibly a jet of acid (like archerfish IRL).

**Comment by Night-Pryanik** [comment]
But I thought these windows have not only bars, but glass too.

**Comment by Coolthulhu** [comment]
I missed the glass part somehow. Yes, then it is a bug.
It probably also means that shooting through windows with bars (with any weapon, including slings) is not working right.
