### ISSUE TITLE
Attack still occurs after mutation attack kills monster

### ISSUE THREAD

**Issue by chrahunt** [CleverRaven/Cataclysm-DDA#13789]
I wanted to separate this to keep things simple. As mentioned by @vache in #13655 and visible in the image for that issue:

![image](https://cloud.githubusercontent.com/assets/12977811/10104450/5765be64-63b2-11e5-8ebe-6610e47dcfb2.png)

the primary melee attack still goes through after the mutation attack has killed the target enemy, making the text a little awkward. It wouldn't be difficult to check for target enemy death and abort before carrying out the attack, but I wanted to open it up for discussion. Should the order of attacks always be Mutation then primary?

I considered that a text change would be easier but it might be silly if the text is something like "You hit the {}, but it's already dead" for a monster that melts away or explodes.

Side note: the [side effects](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/melee.cpp#L314) would also need to be moved so they only occur also be moved so they only occur if the primary attack occurs.

**Comment by drbig** [comment]
Not really sure if opening this with #13655 being there is going to help the thing.

Seems to me chained/multiple attacks need to check if the target is already dead. The useless "do no damage" messages are then more of a symptom than actual problem.
