### ISSUE TITLE
Night vision interacts oddly with buildings at certain light levels

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#13786]
Old screenshot:

![how is photon formed](https://cloud.githubusercontent.com/assets/11582235/8945045/bd766eb6-3549-11e5-9326-f7dedc3bce9c.png)

Newer screenshot (build 3790):

![augh](https://cloud.githubusercontent.com/assets/11582235/10584817/c01e5a06-7659-11e5-9928-3b445d4f879a.png)

Third screenshot, demonstrating the oddity later in the morning, with circular distances off, and in a different area:

![the aughening](https://cloud.githubusercontent.com/assets/11582235/10584914/548cb570-765a-11e5-82c8-bfcf6b571e8b.png)

And finally, with tiles disabled solely for the sake of being thorough:

![das grau ening](https://cloud.githubusercontent.com/assets/11582235/10585031/0900809a-765b-11e5-91be-f695ac2a7e89.png)

This is one of those things I keep forgetting to report because it only seems to come up at a certain point when natural light level is at the right point.

Additionally tested to see if disabling circular distances solves it, but nope.

**Comment by Midaychi** [comment]
I don't remember any recent PRs to nerf night vision, but I have noticed that nightvision works better sometimes than others. Maybe the moon is out better or its not cloudy?

**Comment by chaosvolt** [comment]
It does seem to hinge on a specific light level, far as I can tell.

Still, I'm not sure if light-devouring walls are an intended consequence. >.>

**Comment by Midaychi** [comment]
I know that if you have nightvision and get close to a lightsource, your nightvision dims or turns off.

**Comment by chaosvolt** [comment]
Note that, as should be evident from the screenshots, the vision range isn't being reduced at these specific points. It's just outright STOPPING upon hitting a wall.

**Comment by drbig** [comment]
Hmm, this looks actually OK to me. Unless you're getting the '3 tiles in front' only at a small (specific) level of lighting.

**Comment by chaosvolt** [comment]
....how is not being able to see a wall unless it's adjacent to you OK? >.>

Especially since you can see father than that in other directions.

**Comment by drbig** [comment]
Stand really close to a wall and do a 360 look-around. You can clearly see the 180 behind you (given you're facing a wall of a building in otherwise open terrain, just like in your examples), but in front of you only a small angle as rest vanishes (the perspective thing) very quickly. You being at a tile adjacent to a wall is close enough to have a wide-angle peak through a window == 'face at the wall' (or close enough to lockpick a door). At least that's the line of reasoning that makes this OK to me :D

**Comment by chaosvolt** [comment]
It still gives a very weird effect due to the walls outright vanishing into pitch blackness.

Additionally, if I step back from the wall, said wall in front of me is also pitch black. The 3 sections of wall are only revealed because I'm NEXT to them, not because of perspective. >.>

**Comment by drbig** [comment]
Yep, which is why `Confirmation Needed`. Maybe @kevingranade will have a (final) word on this :)

**Comment by chaosvolt** [comment]
Hopefully that screenshot should demonstrate a bit more clearly that the walls are basically eating light for reasons that make it hard to determine if it's intended or not. >.>

**Comment by vache** [comment]
The 4th screenshot at the very top, console version, looks wonky to me as well.  Notice the area west of the character, the wall goes from seen to unseen, then past the end of the building, the ground goes seen again.  Doesn't seem like the fov is correct there.

**Comment by kevingranade** [comment]
Agreed, looks like a bug.  Will need to be careful not to wreck
@coolthulu's 3D FoV stuff in the process though.

**Comment by chaosvolt** [comment]
Yeah, might be best to wait until that's done before anyone works on a solution.
