### ISSUE TITLE
Hordes ignore zombie upgrade frequencies entirely

### ISSUE THREAD

**Issue by Nioca** [CleverRaven/Cataclysm-DDA#13803]
Build 3803 console, Windows 7.

I was tinkering with adding some new monsters to the game (upgrades of existing zombies), and doing some testing, I noticed something odd. When a monster evolves (either naturally, or via a zombie master), and that monster has a group it can choose from, it'll ignore the frequency inherent to that monster group and simply select one at random. Using bog-standard zombies as an example, despite the zombie upgrade group having Hulks at frequency 1 and Shriekers at frequency 30, you'll see them with roughly the same frequency as every other monster in that monster group. (it's easier to see with a smaller group though).

Not 100% sure if this is intended or a bug, but seeing as the base Zombie Upgrade monster group has varying frequencies, it suggests that the current behavior isn't intended.

**Comment by IOSYN** [comment]
Quite sure I've run in to this-- seeing a *lot* of dangerous specials quite early on compared to the last stable. I'm not sure they're respecting the evolution timer either, tried testing with both low and high evolution rates but I need to test a larger sample first to be sure.

**Comment by drbig** [comment]
I believe the frequencies are for spawn only. Evolution being separate here. But I agree that with evolving into group (== select one from the group) respecting the spawn frequencies would make sense.

**Comment by Coolthulhu** [comment]
Confirming that `monster::try_upgrade` does indeed drop frequencies.

This sounds quite unbalanced and probably not what author intended, seeing as the frequencies are all set.

**Comment by IOSYN** [comment]
Could just tie the upgrade timer to the season length defined on worldgen until the frequencies are properly tied in.

It's a band aid, but it would give us a better perspective on the problem and scaling difficulty per season would be pretty intuitive.

**Comment by kevingranade** [comment]
That doesn't address the problem, it'll be just as easy to have the
upgrades respect weighting.

**Comment by Leland** [comment]
Flagging this one as a priority – hordes being able to evolve without being tied to frequencies smacks me as something pretty serious. Be sure to see @keyspace's work on https://github.com/CleverRaven/Cataclysm-DDA/issues/14692#issuecomment-269129962. Developed a way to generate stats on zombie kills.

**Comment by Toybasher** [comment]
Agreed. This is irritating as I prefer wander spawns [I like the idea of making noise attracting zombies, nornally clear areas becoming reinfested, etc.] but it's frustrating to see super high level zombies so early on. 

Even if ignoring the upgrade "evolution time" I'd be fine if this issue was fixed as since it's selecting zombies at random, the "save this zombie and only spawn him rarely as he's super tough and like a miniboss" zombies are appearing just as common as any other zombie, which is pretty unbalanced.
