### ISSUE TITLE
Manhacks are unkillable.

### ISSUE THREAD

**Issue by WJohn** [CleverRaven/Cataclysm-DDA#13800]
I ran over a manhack several times, got out, and successfully shot it point-blank 3 times, dealing its entire health bar. The manhack was completely unharmed.

**Comment by Coolthulhu** [comment]
Can't reproduce. Might be some weird bugged manhack. Save could be useful, even just the `.sav` file from it made somewhere with manhack in vision.

How was the 'hack created? From item (by player), by zombie scientist or spawned on its own?

**Comment by WJohn** [comment]
The hack was created from a zombie scientist just as I was running him over with my car.

**Comment by IOSYN** [comment]
Tested. Can't reproduce-- killed with the glock in 2 aimed shots.

Remember you are wearing -30% melee worth of encumberance and only have 3 melee skill-- and manhacks have crazy dodge skills anyway.
How it managed to avoid the car though I'm not sure. 

When you shot it did it actually say it was doing damage? e.g Blam! you hit the manhack for X?

**Comment by DanmakuDan** [comment]
Tested, you have to run over the manhack with the vehicle again. It appears to be healing past manhack max HP every time it gets run over (it went from injured to uninjured). The game-saving process might be clamping the manhack's HP back to its normal maximum.

**Comment by WJohn** [comment]
So I guess the real bug here is running over monsters with low weight actually heals, and even overheals them?

**Comment by Coolthulhu** [comment]
> So I guess the real bug here is running over monsters with low weight actually heals, and even overheals them?

It's less about weight and more about the armor being applied twice and only capped once. As a result, any collision which would deal amount of damage below creature's armor will heal it.

Additionally, low speed collisions cause a lot of mini-collisions. This compounds the bug above.

I am addressing both of those in #13804

**Comment by chaosvolt** [comment]
Oh wow, that is the weirdest bug cause I've seen in a while.

**Comment by Zireael07** [comment]
I guess this can be closed?
