### ISSUE TITLE
Nails disappearing from shopping cart on overflow.

### ISSUE THREAD

**Issue by Cynthius** [CleverRaven/Cataclysm-DDA#13819]
I've been trying to renovate my base, and been carrying all the resources I gather in a shopping cart, but I've noticed that every time the cart overflows, it removes the nails in it without dropping them on the ground. They just disappear. They're not in the cart or on the ground. I've been using the "move all" function in AIM, if that helps. Until this is fixed I'll be moving the nails into the cart manually via AIM, so that it stops me from overfilling.

I'm using the Windows Tiles build 3812 (49c6fa8)

**Comment by Midaychi** [comment]
I swear I've run into this bug as well, though haven't been able to prove it. Happens with more than just nails though. I swear I lost a whole bunch of copper wire and some useful things overloading a trunk in a car.

**Comment by IOSYN** [comment]
Noticed this before-- it's not just nails or wire, it happens with anything if it's a stack of stuff IIRC. 
It's still there and there's a workaround to get it back but damned if I can remember what it is right now.

**Comment by drbig** [comment]
> AIM

A bug in AIM? *C'est impossible!* (insert some very sarcastic meme here).

**Comment by Midaychi** [comment]
It usually happens when you've got a pile of crud and you've just finally managed to get a car up and running to escape the encroaching fungal horde, and you're piling stuff into the trunk with AIM. Some stacked items just randomly fall into hammerspace and you end up miles away confused where all that copper wire and your stacks of cour syrup went.

**Comment by Midaychi** [comment]
Semi-relatedly, I've been noticing that picking up usb sticks with software contained using AIM as part of a mass item movement from all into your inventory will sometimes end up turning them all into "usb sticks of nothing", especially when you're trying to pick up more volume then you can hold and have to hold N to go through a lot of y/n prompts.

**Comment by Midaychi** [comment]
Here's a repeatable example on a modless world, in hopes that someone fixes the shoggoth eating vital scavenged supplies.
https://dl.dropbox.com/s/emu21o5xur78md8/AIMtest.zip

To cause this massive stack of batteries to spontaneously disappear into a puff of smoke, simply load the save, open the AIM interface, and press the move all button (default , comma)

**Comment by ejseto** [comment]
This might be related: you can overload a vehicle trunk by dropping a single charge, say, 1 battery, filling up the rest of the trunk with other stuff, then dropping further batteries. The game will allow you to continue adding charges without regard to volume as long as there is at least one charge of the item already in the trunk. But, if you then remove some charges, leaving some behind, the remaining charges will fall to the ground.

**Comment by DanmakuDan** [comment]
I tried following what was going on with AIMtest.zip. The nails get moved from player's position into the northeast square and the original item stack is deleted from the old square. The code then seems to try repeating the move again for some reason, moving the 10000 battery charges onto itself, creating a stack of 20000, then deleting the whole stack. The second move (which is marked as a "nested call" in the code handling the AIM GUI) seems to be moving the items from the northeast square to the northeast square (same square), and the delete is used to clean up the source northeast tile (the delete removes the "stack" regardless of charges). Still looking at the issue.

**Comment by Midaychi** [comment]
It might be the quantizing bit that passes time as you move stuff. It moves a thing, but you're still set on "all directions" so that new item that fits the filters that you were moving all of registers at the top of the stack before the loop decides to go "oh we're done", so it detects there's still stuff to move, continues and moves it again, but then you move it into extradimensional hammerspace and feed ti to the shogoth.

**Comment by DanmakuDan** [comment]
It looks like the move-all from "all directions" to one direction processes each source direction one at a time, starting with southwest and ending at northeast. It might not be filtering out the destination from the sequential processing list, so the northeast in this case gets processed as the source and destination, causing items to get deleted when you use move all.

**Comment by kevingranade** [comment]
If for any reason you try and place an item with over 4,000 volume (this includes a stack with a ridiculous number of charges) on the map, it will fail, and if placing the item is forced, it will lose the item.  This is probably what you're seeing sometimes.
The most likely fix is to add something in map::add_item_or_charges() to detect this kind of overflow and break up the mega-item into smaller items that will fit in each square.  It also needs a check to prevent adding charges to items if that would make the resulting item overflow the square.

**Comment by Midaychi** [comment]
This save will demonstrate the 'disappearing stacked items via AIM'

Load save, open aim, press move all button. All three tiles of 10,000 nails will be stuffed into the vehicle, turning into one stack of 10,000.

https://dl.dropbox.com/s/9ea4cn3ac5yib7v/Nailtest.zip

Also to verify, that last fix that was recently merged fixes AIM for cases that don't involve vehicles.
