### ISSUE TITLE
Intermittent Segfault fighting thugs/bandits

### ISSUE THREAD

**Issue by rsofaer** [CleverRaven/Cataclysm-DDA#13814]
![screen shot 2015-10-24 at 9 49 52 am](https://cloud.githubusercontent.com/assets/212750/10710753/4148c038-7a35-11e5-82d6-aaeeafe6c451.png)

It happens in melee combat, not on every hit.  I'm working on getting a better stack trace, and would appreciate any advice about getting Cataclysm to run cleanly under lldb or a different way to get the trace.

**Comment by Coolthulhu** [comment]
What weapon are you using? What martial art (if any)?

**Comment by rsofaer** [comment]
I'm using a steel spear, I don't think I'm using any martial art.

**Comment by Coolthulhu** [comment]
Reach attacks or only pure melee?

**Comment by rsofaer** [comment]
I couldn't replicate it with reach attacks, only pure melee.

**Comment by rsofaer** [comment]
I'm 99% sure it's an index out of bounds happening on line 1252 of melee.cpp. `mon_targets` is empty, `victim` is 0, and there's an EXC_BAD_ACCESS.

**Comment by Coolthulhu** [comment]
Yeah, could be it. That 
```
if (victim > mon_targets.size()) {
``` 

should probably be 
```
if (victim >= mon_targets.size()) {
```

**Comment by drbig** [comment]
@rsofaer btw. https://github.com/CleverRaven/Cataclysm-DDA/blob/master/ISSUES.md (mostly the version number and platform info)

**Comment by rsofaer** [comment]
Thanks, I'll be more detailed and follow the guidelines next time.
