### ISSUE TITLE
0e3ddf0 warning in iexamine.cpp on compile

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#13818]
0e3ddf0, compiling with make CCACHE=1 LUA=1 TILES=1 SOUND=1 RELEASE=1

I get:

src/iexamine.cpp: In function ‘void iexamine::fswitch(player*, map*, const tripoint&)’:
src/iexamine.cpp:1238:6: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow]
 void iexamine::fswitch(player *p, map *m, const tripoint &examp)
        ^

Game seems to compile and run fine if you compile without -Werror though.

**Comment by drbig** [comment]
a75a558 compiles fine here. Please check the latests? And if it were to fail please provide complete setup info (os, distro, platform gcc/clang version etc.).

**Comment by Midaychi** [comment]
g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
32bit 15.10 
The warning seems to only occur when compiling with -03. When compiling with just -Os the warning does not occur.

The last build I compiled with -O3 without this warning was 49c6fa8, but the first build I compiled after that was 0e3ddf0 and got the warning.

**Comment by mugling** [comment]
These functions were changed recently in #15717 so closing for now. Please re-open if you can reproduce the warnings with any version following this PR
