### ISSUE TITLE
Text prompts in top left of map do not appear

### ISSUE THREAD

**Issue by alexcraig** [CleverRaven/Cataclysm-DDA#13828]
Using the Tiles version, text prompts which should appear in the top left of the map view (things like "Compare where? (Direction Button)", etc.) do not appear when "Use tiles" is set to true. The text prompts do appear correctly when "Use tiles" is set to false. Symptoms are the same as issue #7055 (Closed).

Seen in version b8b399f, as well as 0.C stable, on Windows 7.

**Comment by drbig** [comment]
@OzoneH3 is this due to the long standing "broken curses emulation in SDL"?

**Comment by OzoneH3** [comment]
Not sure what you mean by broken SDL emulation.

It's exactly as CIB described it in #7055

>The issue is that it draws into the curses window(which actually still exists, but is obscured by the tiles window). It needs to either draw into an UI window(for example, a new window rendered over the tiles window), or we need to implement a way to draw text into the tiles window.

Not really sure why it got changed from ```stdscr``` to ```g->w_terrain``` again, but with the pending fix this won't be a problem anymore.

**Comment by drbig** [comment]
@OzoneH3 I mean the bugs where stuff updates in curses but not in tiles: e.g. #12956 #12797 (I tried to hack something around the last one but didn't get very far).
