### ISSUE TITLE
a75a558 - Mod crosstalk between worlds

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#13821]
I noticed recently when trying to make a new survivor that certain mods that I had that added scenarios and professions were showing up in chargen, despite using a world that didn't have that mod loaded.

After a bit of fiddling I found out how to reproduce this. At least on my end. I'm using ubuntu 32bit with the save directory in the root dir of cata, rather than using home folders or anything.

Step 1: Have a mod in your mod folder that adds scenarios. (or at least, have noctifer's bioweapon and/or survivor mod in there, cause that's the one I tested with)

Step 2: make a world that doesn't use that mod. Try creating a character and notice that the professions and scenarios from that mod aren't listed.

Step 3: make another world that uses that mod. Try creating a character and notice the professions and scenarios from that mod are listed.

Step 4: All's good right? Not quite. Go back and try to create a character in the world that doesn't have the above mod. Notice that there are new entries from the mod, despite the mod not being in the world's modlist.

Edit: seems like quitting and reloading clears this up. Weird. It didn't before. I gotta test this further.

Edit 2: no guess I was just imagining things. Best guess is that json isn't being cleared between loading worlds, but is cleared on quitting.

**Comment by chaosvolt** [comment]
Hmm. Very odd, I'm having trouble reproducing this. First I tried simply loading the character creation screens, viewing the profession list, then cancelling character creation for steps 2 and 3.

Then I went and outright made a character and saved for steps 2 and 3, still couldn't get it to affect the profession list. ._.

Not sure if my being on Windows instead would be the issue here or not.

**Comment by Midaychi** [comment]
On ubuntu I can reproduce it by going into char creation on the modded world, then backing out and going into the char creation of the unmodded world. The scenario and profession from the mods show up. 

Maybe it's a compiler difference? Idk.

**Comment by Midaychi** [comment]
If I can reproduce it and you can't, then there must be something more to it.

**Comment by chaosvolt** [comment]
Might need others to toy with trying it, then.

**Comment by Midaychi** [comment]
I compiled without lua and got the same results, so it's not that.
I'm using Notcifer's survivor mod as the mod, making a clean no-mod world and a world with only the survivor mod to test. Maybe its a specific mod issue?

**Comment by chaosvolt** [comment]
Not sure how the survivor mod would cause that.

Maybe try it with the mods that come with the game, like classic roguelike classes or more survival tools?

Would be weird if one specific mod did that though. >.>

**Comment by Midaychi** [comment]
Ok yeah. It only happens if the mod adds a scenario. Otherwise choosing a scenario in the unmodded world clears and fixes the profession list.

**Comment by chaosvolt** [comment]
Ah, weird. I was thinking maybe MST would cause it too if that's the case, but simply overwriting a scenario is different from adding a new one.

I should've dragged my S.T.A.L.K.E.R. bandit mod out to test with.

**Comment by mugling** [comment]
Closed as unconfirmed
