### ISSUE TITLE
Palisade Gate doesn't play well with others

### ISSUE THREAD

**Issue by KA101** [CleverRaven/Cataclysm-DDA#1385]
Apparently the Palisade Gate requires Palisade Walls on either side in order to work.  This wasn't obvious to at least one player, and it's a pretty expensive lesson to learn through construction fail.  Seems worth either making a note in the menu or loosening the restriction.

See http://smf.cataclysmdda.com/index.php?topic=14.msg19238#msg19238 .
##

**Comment by eliotcougar** [comment]
0.C-19186-g23a9665 (tiles)
Palisade gate does not seem to have an open state at all... It is not considered a door... It has nothing to do with adjacent walls...
