### ISSUE TITLE
Closed windows

### ISSUE THREAD

**Issue by Oskar636** [CleverRaven/Cataclysm-DDA#13858]
After you tear down a cutrain from a window in a house, you can't open it.

**Comment by Mshock777** [comment]
It's been around since 2014 #8165.

**Comment by drbig** [comment]
Yeah, it's a manifestation of how the constructions are implemented.

**Comment by drbig** [comment]
Though quoting @KA101:
> Known. Curtains and openable-window are linked. Windows w/o curtains are deemed Commercial type--as seen in stores, etc, and are not openable. 

This does make sense on one level... still a bug with the implementation IMHO.
