### ISSUE TITLE
Stairs lead to open air with z-levels enabled

### ISSUE THREAD

**Issue by Autastic** [CleverRaven/Cataclysm-DDA#13852]
i spawned at the LMOE shelter with z-levels enabled, and if i climb up where you are supposed to climb down, you climb into empty air with no way to get down unless you fall and take damage. this happens in other places too, but i cant remember them.

**Comment by drbig** [comment]
Maybe related to #13008.

**Comment by namarrgon** [comment]
This also happens if you walk 'up' on the above-ground stairs of a lab.

**Comment by Coolthulhu** [comment]
Oh, I identified the cause:
It's because roof doesn't exist and climbing the walls is quite easy.

You can climb down by 'e'xamining any of the empty tiles.
