### ISSUE TITLE
Repeated mystery freeze

### ISSUE THREAD

**Issue by scorpion451** [CleverRaven/Cataclysm-DDA#13864]
Just updated to experimental 0.C-3833, 64bit windows graphical build. As soon as I walk about 100 tiles west to an area where a previously unmet NPC begins to follow me, the game locks. 100% reproducible.

The in-game debug log pinpoints the exact lock point as following the two checks for my dragon style/dragons flight buffs on the turn after I see the message about NPC chose option "follow", but there's not one being produced for the freeze itself, so the game doesn't seem aware of it.

~~Engaging in conversation before the NPC defeats the blob they are fighting does not lock, NPC fleeing afterward does not lock, possibly hostile tracking locks(?)(*character build tends to either terrify or recruit NPC's so this scenario is unreliable to produce*). The turn after they start following me, the game freezes.~~

Fixing to roll back to 0.C-3829 to see if the same thing happens.

Update 1: Yep, this time without the NPC showing up. Seems like it might be the location rather than the NPC. More poking with sticks to ensue.

Update 2: Back to 0.C 3833. Maybe something with updating buffs and effects at this exact place? This time locked between updating dragon style and dragons flight. Also, noticing it might not be a true lock so much as a loop or absurd lag; process monitor says its doing *something* despite being unresponsive and seemingly stuck between turns for ~~5min+~~ 10min+. (Just for benchmark, this is on my art rig, so it's not a resource issue: the phase "Negligable Load" comes to mind.)

Update 3: Might have pinpointed the root(?) turned off z-levels world option, no more freezing in that area. Perhaps I'm standing on top of a slime swarm or something...

**Comment by drbig** [comment]
Please provide a save? Sounds intriguing...

**Comment by Midaychi** [comment]
I don't have a save but I vaguely remember something about this.

When dealing with random npcs, sometimes it'll mess up and npc will not have used all its moves or something, and then it'll spontaneously drop whatever it was holding, and then for some reason the game will check your current style vs the npc over and over for no apparent reason.

Other times when npcs see you but you're in a moving car, they'll trigger this and run at you unarmed leaving their guns behind. It's kinda silly.

**Comment by scorpion451** [comment]
As an update, since disabling the z-levels option, the issue has vanished and not returned. 
Not sure if that's what fixed it or just the ghost in the machine deciding to work again, though, because further exploration hasn't revealed anything underground.
What Midaychi describes sounds a lot like the issue I was seeing, especially the part where it just stopped doing it for no obviously-related reason.
Willing to share the save if needed, but this is fairly long running, large world weighing in at 163MB. Might be better to see if anyone else has a slightly smaller file with the same issue.
