### ISSUE TITLE
Two-Way Radio Recipe Cannot Be Learned from Disassembling

### ISSUE THREAD

**Issue by Lakstoties** [CleverRaven/Cataclysm-DDA#13866]
In recipe_electronics.json, the "two_way_radio" recipe is missing the "decomp_learn" attribute.  Hence, it makes it impossible for a character to learn the recipe through disassembling.  Also, it might be prudent to allow the recipe to be learned from appropriate literature, such as:  Ham Radio Illustrated, Advanced Electronics, Electronic Circuit Theory, and/or Amateur Home Radio for Enthusiasts.

**Comment by Midaychi** [comment]
There was a large span of time where I forgot that two-ray radios were even a thing, because I'd never seen them drop. It wasn't till I eventually got into the survivor missions when I was like, "Oh right. Those are actually things."
