### ISSUE TITLE
Health Value calculations don't factor in Recycler Unit CBM

### ISSUE THREAD

**Issue by Lakstoties** [CleverRaven/Cataclysm-DDA#13879]
After installing a Recycler Unit CBM in my character, I noticed that my health value was going down after being fairly constant and gradually increasing.  Now, it has decreased significantly.

From what information I know, I believe the reduction in the need to eat is affecting the Health Value calculations.  The Recycler Unit CBM decreases the need for food, and to maintain your Health Value you need to eat good food.  Hence, the reduce need to eat causes a decline in Health Value.  So, either the Health Value calculation needs to factor in the Recycler Unit CBM or the Recycler Unit CBM needs to alter the Health Value calculation in a fashion similar to what it does to Hunger and Thirst values.  (Maybe stagnating the health value decline rate.)

**Comment by kevingranade** [comment]
This is unintended, but I'm not sure it's a problem, it's totally
reasonable for use of a recycler system to require you to eat less, but
higher quality food to maintain your health.

**Comment by Lakstoties** [comment]
But, the thematic point of the Recycler Unit CBM is to extract the nutrients that would otherwise be wasted and in a sense allow you to grain more nutrition from the same food.

Mechanically, the Health Value calculation is tuned and geared towards a character eating a certain amount over a day.  The trouble is when that character ISN'T eating that amount due to the Recycler Unit affecting Hunger and Thirst, the calculation makes that seem like malnutrition is happening.

For example:  The Health Value calculation is expecting X units of nutrition to maintain health.  For the sake of argument,  Y average food = X nutrition.  Works fine for the average character, but fails for a character with the Recycler Unit CBM.  Why?  They can only eat Y/2 amount of food (or even less).  So, they literally can't get enough food into their system to satisfy the Health Value calculation, even if the food is of higher quality.  It doesn't matter how nutritious the food is, if you can only ever eat a 1/2 or 1/3 or less of it before the Health Value calculation fires off.

So, the Recycler Unit CBM needs to practically enhance the amount of nutrition coming from food equally as much as it reduces a character's need to eat, otherwise the Health Value calculation starts to err.  As it stands right now the Recycler Unit CBM is a HUGE detriment, rather than the boon it should be when it comes to Health.

**Comment by Coolthulhu** [comment]
Currently all the food nutrition is totally overshadowed by vitamins. This isn't really a good thing, but it is a thing.

Also, the health values of nutrition-dense food are very low, next to negligible. Vast majority of foods with `health > 1` are drinks and fruit.

I'd say it makes sense for an artificial part to impact natural processes. Recycler is for survivalists and soldiers who need all they can get.
And also for cyborgs who are using that extra nutrition to power their metabolic interchange CBM, which undoes what recycler does, allowing gorging on that nutrition-dense food like fried rice.

**Comment by Leland** [comment]
Looks like discussion's stalled on this suggestion, closing. Feel free to let me know if you want it reopened; or just create a new issue.
