### ISSUE TITLE
Is smoked meat volume set wrong?

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#13883]
Three pieces take up 1 volume and are 44 x 3 = 132 nutrition.
It's better ratio than sausage, which is considerably more difficult to craft -- six pieces take up 2 volume and are 32 x 6 = 192 nutrition (92 per one volume).
Could it be that each piece was supposed to take 1 volume, not the three pieces together?

**Comment by Rivet-the-Zombie** [comment]
Yeah that sounds like the portion/stack size got messed up at some point.

**Comment by MehMuffin** [comment]
Should that be changed to 1 apiece or maybe 2/3 or something, though? I'm not sure if any sort of volume savings are supposed to be there or not, but if it were tripled smoked meat would end up just as long term cooked meat.

**Comment by Marrim** [comment]
I think it's supposed to be just long term cooked meat, with some taste advantage.
Better volume is what sausages and pemmican are for (they contain fat, thus packing more energy into less volume).

**Comment by IOSYN** [comment]
Looks like it's splitting the volume between the charges. 
Might want to check the volume/charges in `fish_smoked` as well.

**Comment by illi-kun** [comment]
I guess it was fixed in  #13967 and should be closed.

**Comment by Oskar636** [comment]
@illi-kun Currently smoked meat is 104 nutrition per 1 liter and sausage is 384 nutrition per liter so this didn't get changed ( I think ) since your last comment and can be closed.
