### ISSUE TITLE
Multidropping Items + Wearables should drop items first

### ISSUE THREAD

**Issue by madprogrammi** [CleverRaven/Cataclysm-DDA#13894]
Say I wear a backpack. I fill the backpack with food. If I multidrop the food + the backpack, and select the backpack first, I drop the backpack, and a bunch of "Attempted to access inventory item" errors occur. Afterwards, "Some items tumble to the ground.", because I'm no longer wearing my backpack. Items always need to be dropped first, so that you can drop the backpack without over-voluming the character.

**Comment by Midaychi** [comment]
I can confirm that this happens. If you exceed volume and drop items + equipped items at the same time, the game will process dropping the worn items, then drop some random objects in the inventory due to volume overflow, then derp itself silly.

**Comment by madprogrammi** [comment]
Oops, apparently I didn't proofread my title.

**Comment by drbig** [comment]
Yeah it's pretty annoying.

**Comment by JoeKlesczewski** [comment]
I suppose I can take a crack at this.

**Comment by JoeKlesczewski** [comment]
I've got a PR up that addresses this. PR #13954 to be specific.
