### ISSUE TITLE
Bartering can sometimes result in NPC paying you to take goods away.

### ISSUE THREAD

**Issue by Lakstoties** [CleverRaven/Cataclysm-DDA#13890]
Ran into this issue.  I think the Player VS. NPC discount code has a glitch where the calculation can allow a negative percentage of sorts that affects the price.  That or the calculation is trying to subtract a flat amount that's gotten too big.

So, there probably needs to be a floor via the math or the logic to limit how discounted an item can get.

Picture of the issue:
![payittotakeitaway](https://cloud.githubusercontent.com/assets/2147265/10918975/f46a6fd6-822d-11e5-8191-283cb860fe71.png)

Current Character Stats:
PLEASE NOTE:  I am using the Stats from Skills mod that alters stats based on skill ranks.  So, the stats are ridiculously high and probably outside the scope of a normal game, but it shows there is a possible erroneous edge case in the calculations and logic.

![currentstats](https://cloud.githubusercontent.com/assets/2147265/10918983/0292520e-822e-11e5-8a44-67c96a92e5c2.png)

**Comment by kevingranade** [comment]
The price the NPC charges for something should be "what the NPC thinks the
item is worth" plus (or multiplied by) "profit the NPC wants to charge",
and only the second should be adjusted by barter skill or similar, and it
should never be negative (or less than 1 if it's a multiplier).

**Comment by NickTaylor-** [comment]
The adjustment for the prices is based on the following bit of code in npctalk.cpp:

```
const auto their_adjust = (price_adjustment(p->skillLevel( skill_barter ) - g->u.skillLevel( skill_barter )) +
                              (p->int_cur - g->u.int_cur) / 20.0);
```

While the ```price_adjustment``` function does limit the minimum adjustment to 1, but the intelligence adjustment is where its getting skewed.

With your intelligence of 27, assuming their intelligence is like 7 or something, you're effectively getting a result of ~-1, or they pay you full value to take it off. This would occur whenever you had a sufficiently higher barter skill (5 or higher) as well as any sort of intelligence advantage.

This whole calculation should probably just be forced to be a minimum of 1 (i.e. nothing will ever be sold below cost).

**Comment by Lakstoties** [comment]
Looking at the code, it seems like it might be worth having a calculation to determine the NPC/Player price bias, and use it in such a manner to make it impossible to get a negative price and make it hard to completely devalue an item.

Something similar to this pseudo code.

//Start out a 1:1 ratio, then alter the bias with both skill and int ranks.  Also, make sure we have something other than a 0 to start out with when considering the player.
priceBiasPoint = (1 + NPCSkill + NPCInt) / (1 + PlayerSkill + PlayerInt);

//Vendors are running a business and behave differently.
if (NPCType == "Vendor")
{
    //Vendors won't sell below their cost and like to charge their profit.
    ValueOfNPCItem = rawCost + (rawCost * priceBiasPoint);
}
else
{
    //Free market trading between regular NPCs and players.
    ValueOfNPCItem = (rawCost * priceBiasPoint);
}
//Vendors will value player goods at a starting 50% bias and other NPC's don't care about player's cost.
ValueOfPlayerItem = (rawCost / priceBiasPoint);

Now there's probably a few other factors that'd need to going into the biasing and such (and someone check my math because I just came up with this on the fly), but this way you don't have to worry about using special case logic to handle edge weirdnesscases, and it makes it a bit harder to really work over NPCs unless you have a ridiculous combo of barter skill and intelligence.

Just suggestion, I'm not familiar enough with the code base to really know if that would blow something else out down the line.
