### ISSUE TITLE
Mining with a pickaxe causes pain, which causes interruption query

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#13901]
You get a little pain at the end of a mining activity, but before it actually ends, resulting in
"Ouch, you were hurt! Stop mining?"
I hit "n" and the next millisecond the mining is finished.

**Comment by drbig** [comment]
Unless this is somehow intended (`too weak to mine`?)...

**Comment by Coolthulhu** [comment]
Confirming.
No, it's not intended, it's the result of code first causing pain (which prompts the interrupt) and only then removing the activity.

**Comment by NickTaylor-** [comment]
Looking at the code ``mod_pain`` triggers ``cancel_activity_query``. Only easy solution to this that I could see would be having something like ``mod_pain_no_confirm`` which would not confirm with the player if they want to continue. In this case as well, the pain is only added at the end of the action, so cancelling would not have any real effect.

**Comment by madprogrammi** [comment]
Another solution would be to add a boolean flag as an argument (I'm not sure which is the generally preferred method for the codebase though)

**Comment by mugling** [comment]
This just got fixed in `master`
