### ISSUE TITLE
Description of .38 FMJ

### ISSUE THREAD

**Issue by VlasovVitaly** [CleverRaven/Cataclysm-DDA#13910]
I have report from one of translators about description of .38 FMJ ammo

Item: ".38 FMJ"
Description: ".38 Special ammunition with brass jacketed 130gr bullets.  The .38 Special round has been known from its inception for its accuracy and low recoil."
Q from reporter: "Name mismatch in the original text, that should be .38 FMJ?"

So if nothing wrong here just close this issue.

**Comment by Rivet-the-Zombie** [comment]
.38 Special is the caliber, brass jacketed FMJ is the type of slug. The description is correct.
