### ISSUE TITLE
Adding quantity parameter to non-ammo items

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#13915]
Hoarding items seems to be a very big source of lag. When you have those 500 scrap metal pieces and 1000 rags everything is slow. Using inventory is slow, crafting menus are slow, etc.
Meanwhile there are ammo-type items that handle this a little better. You have a thread item with stack size set to 1000, not 1000 separate units of thread. And yet you can separate it however you like.

So why not make normal items behave closer to their ammo counterparts code-wise? When an item is placed / moved somewhere, be it a tile or an inventory, check if the same item is there already and if it can be stacked. If there is, increase "quantity" by 1. A check for stackable items is already there to draw items as stacked in AIM. It already checks for freshness and damage.

My limited coding knowledge tells me that it should be pretty easy to implement for someone who actually knows how to code. I do not foresee any real problems with save compatibility either. This should make mid-late game much more smooth for hoarders, reduce save bloat and make developer's private life better by 20% by improving morale and karma.

**Comment by Zireael07** [comment]
I believe this idea has been thrown around multiple times, both on GitHub and forums.
I do not recall what the problem was.

**Comment by drbig** [comment]
Yeah well, we currently have this `charges` thing and I _believe_ ammo is actually done differently. In any case AFAIR there are some corner cases with this and it turns out not so easy (ripping the current system(s) and writing a new one from scratch is also not an "Easy-fix"). I too believe this is being brought up periodically. Looks to me like another "Long-term" thing.

**Comment by kevingranade** [comment]
The charges thing causes terrible corner cases and bloats the code
(everything interacting with items has to be aware of the distinction),
extending it to more things is going to cause a lot of bugs and increase
code bloat.
We can look at some alternatives for items getting handled a lot and
causing slowdown though.

**Comment by JoeKlesczewski** [comment]
Without knowing overmuch about how items are currently handled, it strikes me as possible for items to be combined into "groups" by the player (via the `charges` thing) that are then translated by whatever functions we currently use to get items into regular lists of items. This would allow us to get the benefits of grouping items without refactoring large amounts of code. Unless I am mistaken on how things work, of course - like I said, I don't know overmuch about how we currently handle getting lists of items for internal use.

This also could probably improve some item management stuff, I suppose.

**Comment by BevapDin** [comment]
> Without knowing overmuch about how items are currently handled,

And that's your problem, you're making assumption based on what you see on the outside, without knowing anything about the inside. That usually doesn't work well.

> it strikes me as possible

C++ is Turing complete, everything is possible (-:

(Yes, I'm great at parties. Why are you asking?)

> Unless I am mistaken on how things work, of course

You are. Items are nearly always handled as single item (like a gun, or a chunk of steel). A stack of 100 arrows is *one* single item to the computer. Only some places handled those items specially (and correctly), for example the item drop menu: if you drop part of a stack, it removes charges.

For example, a vending machine sells singles items, if you put a stack of 200 aspirin in it, you can only buy the whole stack, not part of it. The aspirin is *one* item and the code for the machine does only work on that level. This is similar in many other menus.

**Comment by JoeKlesczewski** [comment]
>You are. Items are nearly always handled as single item (like a gun, or a chunk of steel). A stack of 100 arrows is one single item to the computer. Only some places handled those items specially (and correctly), for example the item drop menu: if you drop part of a stack, it removes charges.

I said I didn't know much about how items are handled, not that I knew nothing. Namely, what I *don't* know is how tightly coupled the code is to to this implementation. Depending on how items are normally accessed, it could be relatively simple to drop in a different item storage format. Having paged through the code a bit more, I even have a potential solution.

What we currently have boils down to storing items in a `std::list` that includes multiples of (most) items as different entries. To start transitioning this to storing items in a `std::list` with repeated items grouped up via `charges` we can write up a pair of functions, call them `expand(std::list)` and `contract(std::list)`, that turn `charges`-based stacks into repeated items and back, respectively. A tag could be used to note any exceptions to this, such as keeping batteries in stacks. If you don't want to ever collapse a vending machine's inventory, that's fine - you don't ever need to call `collapse(inv);` on it.

This also avoids the problem @kevingranade brought up about lots of code needing to be aware of the new setup. Adding an item to an inventory would stay the same, with any additions swept up in the next call to `contract(inv)`. Removals are trickier, though - absent refactoring such functions could be papered over with something like:

    expand(inv);
    //do whatever removal you want

This may also need to be followed by a `collapse(inv);` in some situations, though similar to additions that can potentially be left undone and handled elsewhere.

This is where my lack of experience with this code base comes into the picture, however. If there are a great many places where items are directly removed from lists that it'll A) be a pain to ensure we have them all and B) increase the chances that inventories don't get re-collapsed in a timely manner. Without a solid understanding of the code base as a whole, I cannot make a particularly confident prediction regarding the extent to which this is the case.

**Comment by BevapDin** [comment]
> Having paged through the code a bit more, I even have a potential solution.

Good, I really like to see that.

> What we currently have boils down to storing items in a  std::list  that includes multiples of (most) items as different entries. To start transitioning this to storing items in a  std::list  with repeated items grouped up via  charges  we can write up a pair of functions, call them  expand(std::list)  and  contract(std::list) , that turn  charges -based stacks into repeated items and back, respectively.

`exapand` converts a single item "soap (20)" to 20 items "soap (1)" in the stored lists (in-place) and the other function reverts it?

The conversion will be a huge slowdown: considering items with thousands of charges and may not be possible at all (I currently have a survivor with more than 100,000 units of duct tape).

> If there are a great many places where items are directly removed from lists that it'll A) be a pain to ensure we have them all and B) increase the chances that inventories don't get re-collapsed in a timely manner.

For what it's worth: the remove functions will work fine if they use the item type or similar property of the item. Removing 150 charges of duct type from the map will remove as many actual items as needed (e.g. one item of 100 charges, than 50 charges from another "duct tape (100)" item). It will work just fine if you have 100 items of "duct tape (1)".

only the functions that use a pointer to the item may be problematic. The pointer must stay valid for this to work, so you have to call `expand` or `contract` before getting the pointer and can only call the functions after the item has been removed.

Btw. have you looked at the advanced inventory management? It does something like the contract function (a similar function is in inventory_ui.cpp). They create a *view* of the item lists, stored as `list<pair<item*, int>>`, the pointer points to the item object in the list (which is not changed) and the int is the (summed up) count.

**Comment by JoeKlesczewski** [comment]
>`exapand` converts a single item "soap (20)" to 20 items "soap (1)" in the stored lists (in-place) and the other function reverts it?

That's the idea, yeah.

>The conversion will be a huge slowdown: considering items with thousands of charges and may not be possible at all (I currently have a survivor with more than 100,000 units of duct tape).

Situations like those are what the tag I mentioned would be for. Duct tape, thread, and batteries are all things that one are likely to have many instances of, and therefore would be extremely slow to expand. Besides - most of the point of the functions would be to ease refactoring of old functions, so they should translate into the old behavior as closely as possible.

>only the functions that use a pointer to the item may be problematic. The pointer must stay valid for this to work, so you have to call `expand` or `contract` before getting the pointer and can only call the functions after the item has been removed.

That's a good point, though I think it's an addressable one. Ensuring that the `expand` function keeps the stack it is expanding and simply decreases its size as it adds new item entries should ensure the pointer stays valid.

>Btw. have you looked at the advanced inventory management?

Yes, I noticed it while I was working on one of the pull requests I have open (#13954 to be specific). That should still work so long as it is working off of a `collapse`-ed list rather than an `expand`-ed one. What it would do in other situations is somewhat difficult for me to see, I'm afraid.

**Comment by mugling** [comment]
> The charges thing causes terrible corner cases and bloats the code

The core of this suggestion is subject to this flaw
