### ISSUE TITLE
Segfault when trying to craft with a certain item in range

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#13921]
In the following save, steps to reproduce:
Examine the nearby car, remove any of the damaged seatbelts, then try to open craft menu. Segfault.
(Trying to craft without removing the seatbelt works fine.)

Note: the whole world folder was too big, I had to trim the map files and leave only the local map. It doesn't seem to affect the reproducibility of the bug.

Link: http://www.4shared.com/zip/wJIDsGwSba/buggy_save_seatbelts1.html

**Comment by remyroy** [comment]
In which version did you have this issue? What OS are you using?

**Comment by chaosvolt** [comment]
It seems something's giving me this issue too. Windows 7, tiles build 3861.

**Comment by dholmes215** [comment]
This is probably #13916.  Short ropes are a component of shoulder straps, so trying to craft with them in range might move "shoulder strap" to the top of your crafting menu, causing it to be selected as soon as you open the menu.

**Comment by chaosvolt** [comment]
Well shit, that explains it.

**Comment by Zireael07** [comment]
Should be fixed with #13922

**Comment by Marrim** [comment]
If that still matters, I was on 534a656, Linux.

**Comment by mugling** [comment]
sorry, looks like an oversight on my part

**Comment by drbig** [comment]
@Marrim Can you confirm this has been fixed in the latest experimental? (If so please feel free to close the issue).

**Comment by Marrim** [comment]
It seems fixed now.
