### ISSUE TITLE
No way to rebind keys in-game in the SORT_ARMOR menu

### ISSUE THREAD

**Issue by CIB** [CleverRaven/Cataclysm-DDA#13959]
The re-layer clothing menu doesn't allow you to rebind keys. When hitting '?', it brings up a custom help instead that doesn't allow to rebind keybindings.

**Comment by illi-kun** [comment]
This is not the issue anymore. Currently, the custom help menu is associated with the separate key ('F1' by default), it also can be reassigned via standard keybinding menu (which is available via '?').
