### ISSUE TITLE
Quest-giver NPC's avoid player

### ISSUE THREAD

**Issue by Ygdrad** [CleverRaven/Cataclysm-DDA#13956]
I've been playing the latest experimental builds and currently it is impossible to complete most of the quests given by mobile NPC's since as soon as they give you the quest they do their best to stay away from the player and are often somewhat faster too.

**Comment by Ygdrad** [comment]
After that character's death NPC's were no longer running away quite as often. It might have been a bug with that character/world or the fact that highly trained martial artists are considered as heavily-armed by npcs.

**Comment by illi-kun** [comment]
Superseded by #16812.
