### ISSUE TITLE
Consume adjacent items

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#13955]
You can already *examine* an adjacent tile and interact with the contents. Somebody has also helpfully added the ability to *eat* items from the ground.

Combining the two would eliminate some tedium so I'd like to change it so that you can *eat* items located within a 1 square radius. This would cut down a lot on keystrokes especially when the inventory is nearly full.

I can't see how this changes balance but is there anything else to consider?

I'd likely extend `game::inv_map_splice` to have a radius parameter (defaulting to 1) as this functionality could be of future use although if anyone has a better suggestion I'd be interested.

**Comment by kevingranade** [comment]
Sounds reasonable to me :)

**Comment by Rivet-the-Zombie** [comment]
You mean we'll finally be able to lick up gobbets of human flesh without having to take them out of the fridge first? Count me in!

**Comment by mugling** [comment]
Ok, I'll start with adding a boolean parameter `adjacent` as that should cover most possibilities. Starting to calculate the radius would perhaps be a little excessive

**Comment by remyroy** [comment]
inventory::form_from_map does something similar mainly to get items for crafting. There might be opportunities to unify, refactor or simply these methods.

For performances reasons, it seems like the result of inventory::form_from_map is cached in player.cached_crafting_inventory .

**Comment by remyroy** [comment]
A range parameter on `game::inv_map_splice` would definitely help to implement #13907.

**Comment by mugling** [comment]
I'm also considering implementing an *unload* action for adjacent items (especially batteries)

**Comment by scorpion451** [comment]
I am strongly in favor of this entire "not having to juggle items to use them" concept.
Would this change also allow reading adjacent books? Always kind of a pain having to swap around inventory just to read the book sitting on the bed right next to my character, and then gather everything back up and drop the book again.
