### ISSUE TITLE
Disassembling bugs

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#13978]
1. You can disassemble items which require hacksaw (steel chunk, for example) with makeshift welder (regular welder won't work);
2. To disassemble items made with help of needles or sewing kits (quiver, for example), you need these needles, not some sharp tool like knife or scissors.

Win 10, 0.C-3871, tiles.

**Comment by chaosvolt** [comment]
Second issue is actually because many of those sewable items just use a straight reversible recipe, which will make it require the same tools as needed to craft it. Giving it a separate dismantle recipe would avoid this.

**Comment by Rivet-the-Zombie** [comment]
It would be better if we could catch the reversible recipes that use sewing equipment and make them call for a cutting tool within the code that handles disassembling items.

**Comment by chaosvolt** [comment]
Might work, though what other exceptions would be needed? For forged items, as an example...

**Comment by kevingranade** [comment]
Basically any time we trigger disassembly for an item, it should use the
best available means of disassembly. The only down side to that I can think
of is disassembling something in a hurry, but I don't think the time
difference is big enough for that to be a problem.
