### ISSUE TITLE
Cataclysmdda website not reachable without the right subdomain

### ISSUE THREAD

**Issue by OzoneH3** [CleverRaven/Cataclysm-DDA#13996]
While testing #6043 I noticed that one can not just navigate to cataclysmdda.com nor www.cataclysmdda.com

Only the direct link to one of the language sites is working as expected (en.cataclysmdda.com)

Those two mentioned above should be redirecting to en.cataclysmdda.com

**Comment by chaosvolt** [comment]
Ah, strange. I never noticed due to usually googling it when grabbing a new version. o.O

**Comment by remyroy** [comment]
@GlyphGryph Is there something that can be done for this?

**Comment by GlyphGryph** [comment]
We're switching to a new host, hopefully this week

**Comment by mugling** [comment]
> Only the direct link to one of the language sites is working as expected (en.cataclysmdda.com)

This remains the case

**Comment by illi-kun** [comment]
Nothing changes, this still an issue.

**Comment by illi-kun** [comment]
Fixed by @GlyphGryph.
