### ISSUE TITLE
Completed missions can become failed when quest giver dies

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#13994]
To reproduce:
* Spawn NPC with mission
* Get mission
* Finish mission (can lie, which is 100% chance with debug mind control)
* Check that the mission is completed
* Kill NPC (murder, debug kill or anything else)

A debugmsg may (will?) print and the completed mission will be moved to failed.
Debugmsg will complain about mission not being in active list.

**Comment by chaosvolt** [comment]
Didn't I mention or report this ages ago?

I recall we couldn't determine if this was because of my dirty savescumming or not. >_>

**Comment by Coolthulhu** [comment]
Well, it reproduces without savescumming now.

**Comment by chaosvolt** [comment]
Ah, weird. Now it does, and not before? o.O

**Comment by chaosvolt** [comment]
Well, I just had a whole series of NPC bugs, ranging from persuasion odds going from 100 to 0, to the little pest looting from a no NPC pickup zone, and finally ending in this issue when I got fed up and murdered him.

![ragnar s revenge](https://cloud.githubusercontent.com/assets/11582235/11152697/ae489068-89f9-11e5-9fe3-9db8424c371e.png)

Rest in Pieces, Also-Ragnar.
