### ISSUE TITLE
Background image needed for DMG distribution file for OSX

### ISSUE THREAD

**Issue by remyroy** [CleverRaven/Cataclysm-DDA#14001]
I'm currently working on adding a DMG distribution target in our Makefile to automate the production of such a file. DMG is a common format for application distribution on OSX. It is a disk format that is automatically mounted and displayed when opened. It looks like this. This one is from the Firefox DMG:

![Firefox DMG view](http://i.imgur.com/laSB42x.png)

The user is invited to drag the application (the Firefox icon on the left) to the Applications folder (the Folder with an A made out of brushes on the right side). When the application is dragged and dropped onto the Application folder, it is effectively copied in `/Applications` making it available from the Launchpad. The application becomes *installed*. This convention is well known to OSX users.

In order to produce this nice view, I would need a background image. It should look like the one for Firefox:

![Firefox background DMG image](http://i.imgur.com/CMkbRZQ.png)

That background image should not include our Application icon nor the Application folder icon like in the background image from Firefox. Those icons are shown by Finder, the OSX file explorer. We already have a nice icon for OSX located in `data/osx/AppIcon.iconset/icon_128x128.png`. The size of this background image should probably be like the one from Firefox: 512 × 320. The location of the icons can be different, ie. we could have a design to invite the user to drag our application from the right to the left with an arrow pointing left or from the top to the bottom with a different design.

If you are an artist and you would like to produce such background, let me know. If you know the current graphical assets that have been produced for Cataclysm or that could be good for which we would have the right to use in this context with our license, let me know. If no artist shows up to produce this background image, I will do it myself with whatever assets I can find around.

This is probably going to be the start of an unofficial Mac OSX distribution of the game from me but this could also be used for an official distribution if we ever get an OSX jerkins slave or a working cross-build from Linux.

**Comment by vickio** [comment]
It's nothing fancy, but here's the image I used for my 0.C release (http://ge.tt/9sYHxvB2).

![cataclysm dmg bg](https://cloud.githubusercontent.com/assets/3583786/11168693/80acc6fc-8bab-11e5-8147-e37f4f720c46.png)

**Comment by vickio** [comment]
DMG Makefile target would be great, btw!

**Comment by remyroy** [comment]
That is good enough for me. Thanks.

**Comment by remyroy** [comment]
The dmg target is coming in #14072. Now that we have the background, I'm closing this.
