### ISSUE TITLE
Text overlapping in Sort Armor window on default height

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#14006]
![111111111111111111](https://cloud.githubusercontent.com/assets/11132525/11146318/5f384ebc-8a1e-11e5-9450-e6b2a12e1930.png)
On default terminal height (24) the descriptions text in center column is overlapped by encumbrance and warmth info.
Win 10, 0.C-3883, tiles.

**Comment by OzoneH3** [comment]
Not sure if there is much that can be done here. It was a problem even before arm, hand, leg and feet got split into two lines.
