### ISSUE TITLE
Builds from past few days won't run.

### ISSUE THREAD

**Issue by scorpion451** [CleverRaven/Cataclysm-DDA#14018]
Windows 7 64bit, saw another person in the forums who might be having the same problem also with windows 7.
I haven't tested all of them, but the builds from the past few days (starting somewhere between 0.C 3864 and 3882) don't seem to run more than once, if that. 

As in, some of them boot once after being freshly unpacked, and thereafter any attempt to run them results in them appearing in my task manager, opening a single thread, and ceasing to do anything further. No cpu usage, no i/o readings, and cannot be terminated aside from a reboot.

Takes the cake as the weirdest error I've ever seen. =/

Update: Okay, figured out *what*'s going on, if not *why*: they seem to be triggering Data Execution Prevention, and getting put on lockdown. Poking with sticks to ensue.

update 2: *sound of stick breaking* 8[
Okay, um, so there's something pretty wrong happening here...
Using das Uber task-manager "Process Hacker" tried to kill one of those with kernel level thread halting and memory overwrites. Still there, doing nothing. Aside from crashing Process Hacker when I tried to view the adamanitum thread's properties.

**Comment by DanmakuDan** [comment]
The downloads do the same thing for me. It appears to have started at 0.C-3872 (3871 is commit 492db8e). I don't know what came in the commit after 3871, but I guess it would be compiler related. The game runs when I build it with MinGW.

**Comment by remyroy** [comment]
I'm running the official 3889 right now on Windows 7 64bit without any problem for my main game. I've just tested 3882 and it works without any main issue. I was able to create a new world, a new character and loading the game with that character.

**Comment by scorpion451** [comment]
We you able to then reopen the game with that character? Like I said, 3882 worked *once* for me- it was the second time where the problems started.

**Comment by remyroy** [comment]
@scorpion451 I tried 3882 again and I was again to reopen the game with my character.

I doubt this is related to #13932 or #11627. Those are just build issues not problems running the game.

**Comment by scorpion451** [comment]
That's the thing though, something changed around 0.C 3872, and suddenly DEP is flagging the exe as a potentially dangerous file as soon as it tries to initiate from memory.

**Comment by Zireael07** [comment]
Are you all on Win 7 x64? Tried running the game as admin account? Are you using software or hardware acceleration setting?

**Comment by scorpion451** [comment]
1) I am
2) Only one on my computer, but also tried running it elevated. Gave me an error about not being able to run an elevated program from pagefile.
3) Last I checked, software, because I've heard people saying that hardware can cause problems, but I've never noticed any difference between the two. I've also tried completely deleting configs and letting them be regenerated on repeat runs, but no luck there either.

**Comment by remyroy** [comment]
> Maybe that something is how its compiling now, or is related to what was causing the compliling issue?

Compiling has not changed recently from my understanding. The various PR for build changes have not been merged yet.

> Are you all on Win 7 x64? Tried running the game as admin account? Are you using software or hardware acceleration setting?

I am on Win 7 64bit running the game with an admin account without elevated privileges. I'm using hardware acceleration.

**Comment by DanmakuDan** [comment]
I tried running a version on elevated, it opened for me, and every other version that failed is opening normally now. I was debugging for a different Cataclysm issue earlier, I don't know if that is related.

**Comment by kevingranade** [comment]
It's possible that we're randomly matching the signature of something in
Microsoft's database, that happens on occasion when you have a long enough
series of versions.

**Comment by DanmakuDan** [comment]
Speaking of database, I found out toggling Avast's DeepScreen option will allow me to open the game now. It's only ever been running when it looks at each new cataclysm-tiles.exe, and I realized it hasn't been popping up to tell me that it is scanning like it usually would. It spams 3 copies of the same .exe and just sits there.

**Comment by kevingranade** [comment]
If avast decided it doesn't like the exe, there's not much we can do about
it :/

**Comment by DanmakuDan** [comment]
It's more like they broke their sandboxing program on older Avast versions with their new update.

**Comment by scorpion451** [comment]
Could be the issue for me as well, updating Avast.

**Comment by chaosvolt** [comment]
I think I've just had a friend I've been pestering to play this hit the same problem.

I always have to deal with Avast derpscreening a new version on mine, and causing issues if I get impatient and attempt opening multiple times, but just sitting back and letting it do that initial screen causes no further trouble for THAT build.

My friend however has it apparently going FUBAR anyway even if given enough time that Avast SHOULD be able to screen unhindered, on 64-bit Windows 7.

**Comment by remyroy** [comment]
Some instruction for [Avast users on reddit](https://www.reddit.com/r/cataclysmdda/comments/3t6rxj/users_with_avast_might_not_be_able_to_run_the_game/) for a workaround:

> Fix that worked for me: (On mobile so this might not be exactly correct) Go into the realtime protection section of avast, then settings, and find the exclusions section. Add the whole folder that Cata is in, click apply and ok. Then it should work like new!

**Comment by chaosvolt** [comment]
Hmm. Since my last grabbed version has been Deepscreen'd already, I might update and see how well it works for MY issue, but no idea if it'll fix the issue he's having.

**Comment by mugling** [comment]
Has been tagged **confirmation needed** for nearing 6 months. @scorpion451 please re-open if you are still having the reported difficulties with a recent nightly.
