### ISSUE TITLE
Hordes magically become larger

### ISSUE THREAD

**Issue by CIB** [CleverRaven/Cataclysm-DDA#14012]
This is an issue with my latest set of changes to hordes, as reported at: http://smf.cataclysmdda.com/index.php?topic=11579.0

The problem is that I foolishly assumed that the population corresponded to the number of zombies. However, it seems it actually corresponds to the *number of packs*. I don't see a good solution for this that involves spawning absorbed hordes as packs again; That'd "at best" leading to a pack of boomers turning into a pack of shriekers when you move back and forth. Instead I'll try doing what I intended anyway: Keeping track of the individual zombies in hordes that result from re-absorbing.

**Comment by kevingranade** [comment]
The last report I heard was that this is no longer happening, please reopen if it recurs.
