### ISSUE TITLE
Can't open crafting window when morale too low.

### ISSUE THREAD

**Issue by JornVernee** [CleverRaven/Cataclysm-DDA#14028]
I was looking to do a small code simplification. But before I can say that's a good idea I have to know something.

Currently, you can't open the crafting window (&) when your morale is too low. I was wondering if this is an intended feature (or bug), because you CAN open the crafting window when you can't see to craft.

**Comment by Rivet-the-Zombie** [comment]
It really should allow you to open it when your morale is too low, just not actually craft.

**Comment by Coolthulhu** [comment]
Yeah, it's inconsistent - darkness allows opening the menu, just not crafting.

Though there should be some indication that it's just for show. Having the entire menu change color?

**Comment by JornVernee** [comment]
I agree a player should be able to browse recipes, even if morale is too low (to craft).

**Comment by chaosvolt** [comment]
I'm not sure if that idea sounds good. If the player opens the crafting menu, settles on what they want to make, then...psyche! You can't actually do that because you're sad. Or rather, your character's sad, but now you are too. o3o

Having a clear indicator that you can't actually craft would at least make that sensible though.

**Comment by JornVernee** [comment]
The PR I made is to fix the inconsistency with it being too dark to craft (and to clean op the code).

The indicator sounds like a nice idea. The crafting screen already has a light indicator, but not one for morale. It might be a better idea just to replace the light indicator with a with a 'can craft: yes/no' indicator. Thought that might break immersion a little.

**Comment by chaosvolt** [comment]
Maybe. Granted, the easier way would be making it consistent from the other direction, but I can see the occasional instance where knowing WHAT you can craft is useful even if it can't be made.

Some form on in-crafting-menu feedback to avoid accidentally faking out the player would be sensible though, especially when reversing a gameplay element that players might've gotten used to by now.

**Comment by Zireael07** [comment]
Is there enough space to add the smiley next to/below the light indicator in crafting screen?

**Comment by JornVernee** [comment]
There is on my screen, but it depends on the size of screen you're using. Glancing at the code, it looks like the existing lighting indicator just prints over top anything that might be there if the screen is too small.

**Comment by chaosvolt** [comment]
Seems like that could work, but the breaking point for crafting is firmly in the generic ): point, not the D: point. This would cause confusion because that negative morale that still allows crafting would yield the same symbol as negative morale at or just below the breaking point.

**Comment by JornVernee** [comment]
It looks like with the standard size of the window, there is not enough room for another indicator. 

I made a test "yes/no" indicator, which replaces the lighting one. It would print if it's too dark or you haven't got enough morale, in the message window. But you can't really see that well when the crafting window is open.

Could also do something like "Can craft: L/M" where the color of the letters would indicate whether we haven enough light/morale.

**Comment by JornVernee** [comment]
[indicator] (http://imgur.com/m0IY8pm)

**Comment by JornVernee** [comment]
whoops

**Comment by narc0tiq** [comment]
Let's be less cryptic (but keep it brief): how about a phrase that can be
any of "yes", "too dark", "too sad", with appropriate colorization?

**Comment by chaosvolt** [comment]
That seems like the clearest way to do so. What if it's dark and gloomy at the same time, though? X3

**Comment by narc0tiq** [comment]
Pick the one that's most immediately important -- "too dark".

**Comment by chaosvolt** [comment]
Probably, yeah. You can't cure darkness by snorting things, unlike morale.

**Comment by JornVernee** [comment]
Yeah, that's a good idea. I'm also thinking about any future features that might prevent crafting (like having really cold/damaged hands). With that kind of indicator, it wouldn't be hard to add those on.

**Comment by chaosvolt** [comment]
Cold hands....hnng. Enjoy being unable to make gloves to fix that. >_>

Missing hands would be funny except you can have broken arms, not hands. Which I guess would be close enough.

**Comment by JornVernee** [comment]
Yeah, it would just prevent you from crafting, which can be quite finicky, but you could still light a fire to warm your hands, or bandage up to heal your arms.

**Comment by JornVernee** [comment]
[too dark] (http://imgur.com/dPDv4z9)
[yes] (http://imgur.com/nRLGAz8)

I see a problem with the second one. Maybe the indicator needs a background.

**Comment by chaosvolt** [comment]
A background might help, yes. o.o

**Comment by JornVernee** [comment]
I don't know how to do that though xD.

**Comment by JornVernee** [comment]
and what color?

**Comment by chaosvolt** [comment]
Don't look at me, the source code tends to catch fire when I touch it. ;w;

Idea-wise, hmm. I'd rather suggest the grey background for any instance when you can't craft, since that's the norm for the lighting display being at real dark, it would convey inability to craft in a way players would already expect.

But how to handle backgrounds for when you can craft, unsure.

**Comment by JornVernee** [comment]
Ok, I figured something out, you can pas a color with a background (e.g. h_red is blue highlighted red). Changing that for the entire crafting window might take some time... Maybe there's an easier way though.

**Comment by chaosvolt** [comment]
Ah, unsure how best to handle that, but it would work.

Hmm. But what colors to use for the background of "yes" in that case...

**Comment by JornVernee** [comment]
Blue background doesn't look too good, but it might be the best option, there aren't too many background options unfortunately.

**Comment by JornVernee** [comment]
Could do inverted text: [inverted] (http://imgur.com/dxlXhqn)

**Comment by chaosvolt** [comment]
Hmm, inverted might work, does add to the whole "tell at a glance" idea.
