### ISSUE TITLE
Read skill books not stacking

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14026]
I noticed that if you read a skill book, it won't stack with other similar skill books which you haven't read. Skimming through the save file I found that read ones have item_var "remaining-chapters-1" that is set to 0. Should it work that way for books without chapters?

**Comment by drbig** [comment]
I think all books have "chapters" (for the purpose of not reading the whole thing at once).

**Comment by mightyagrippa** [comment]
This seems fixed. Skill books are currently stacking properly. The only counterexample that comes to mind is the standpipe maintenance log, which is one display name used for two distinct items.

The chapters attribute is set to zero for skill books. It's used as a charge counter for "fun" books and when it runs out the book is half as fun. This isn't completely consistent, though; comic books have no chapters and last forever. And some skill books like Popular Mechanics are effective morale books without chapters.

**Comment by mugling** [comment]
> This seems fixed

As above

**Comment by 11132113** [comment]
This issue is back in build 6513.
Experiencing it with "Under the Hood", "Popular Mechanics" and "The Bowyer's Buddy".
