### ISSUE TITLE
Evolved monsters can take down buildings

### ISSUE THREAD

**Issue by mauledbybears** [CleverRaven/Cataclysm-DDA#14027]
https://ipfs.pics/QmRkEUc1QYmZ6kV4dvZj9xCUoe1HARz7msFtU3R55T65ja

It's crazy for human sized zombies to be able to knock down walls in small numbers. Digging through rubble after corrosive zombies trash everything is irritating. Hospitals are pretty much no-go now. On open ground they're an interesting enemy and they could be interesting in close quarters but being able to destroy walls makes them broken.

**Comment by Headjack** [comment]
I mostly agree. I guess the intent was that they dissolve walls? Maybe it'd work better if they do so only rarely, or take time/deal damage over time to achieve it. Hospitals are a pain, but navigable.

**Comment by Coolthulhu** [comment]
Corrosives got their melee nerfed, now it's back to brutes being the strongest wreckers around.
