### ISSUE TITLE
Borderless window: alt-tabbing puts cata at the end of the alt-tab list

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14024]
Normally alt-tabbing out of a fullscreen application puts it on the end of the list of things you can alt-tab back to. This is kinda sorta reasonable when alt-tabbing takes awhile and you don't want to do it accidentally.
However, games with borderless windowed mode enabled usually behave like windowed programs for that purpose, meaning that when you alt-tab out, they get to be second in the list of programs for alt-tab purposes. That means that you can press alt-tab once to get to your browser and then press alt-tab once to get back.
For me, borderless cata alt-tabs like it should (instantly), but then puts itself on the end of alt-tab list like a fullscreen application, meaning I have to press alt-tab 5-15 times to get back depending on the number of stuff I have open. This isn't the case with windowed mode and it's very desireable for it to work the same with borderless fullscreen.

**Comment by DanmakuDan** [comment]
I'm getting the normal behavior on borderless window alt-tabbing, it's the second item on the alt-tab list. Using Windows 7 64 bit. It may be an issue with older versions of Windows? You can use shift-alt-tab to go backwards on the alt-tab window list.

**Comment by Nandorianen** [comment]
I am using winXP, so it is possible. The fact that normal windowed mode behaves properly gives me hope it can be fixed, however.

**Comment by remyroy** [comment]
I've just tested this again on Windows 7 64 bit and alt-tabbing works properly. When I'm in CDDA FSWB and I alt-tab, it goes to the next window in the list. If I alt-tab again once, it goes back to CDDA FSWB.

I'll see if I can test this on a clean Windows XP VM in the next few days.

**Comment by remyroy** [comment]
I just tested this on Windows XP SP3. I can confirm it puts the CDDA window at the end of the list *most of the time*. This is somewhat inconsistent. I tried it many time and once in a while, it will be the CDDA window in the second slot.

I just retested this on Windows 7 64 bit and it does the same thing. It sometimes put the CDDA window towards the end of the list. It is highly inconsistent to me.

**Comment by Nandorianen** [comment]
Some circular code that gives different results depending on where you are in the loop at the time of button press? Is it possible to compare this with windowed behavior or it's too low-level?

**Comment by kevingranade** [comment]
Does anyone here know how applications even interact with this?  Also, any
pointers to guidelines for 'proper' behavior?

**Comment by remyroy** [comment]
On wikipedia, they have [a detailed description](https://en.wikipedia.org/wiki/Alt-Tab) of how it is supposed to work. The interesting part is this:

> In the absence of "always on top" windows such as Task Manager, pressing Alt, pressing Tab ↹, releasing Tab ↹, and releasing Alt (the typical way keyboard modifiers are used) will always alternate between the two most recent tasks.
Alt+⇧ Shift+Tab ↹ can restore the most recently minimized window. (If there are "always on top" windows, the lowest of these will be selected instead.)

For some reason, it seems like when we are in fullscreen borderless and we push alt-tab, we *sometime* lose our *recent* status or flag.

I've noticed that CDDA has multiple windows involved. When I close CDDA, I see the main windows closing, but I see 2 more closing behind. It might have something to do with these 2 others.

**Comment by Nandorianen** [comment]
Maybe it thinks it was minimized instead of just being switched out of?

**Comment by remyroy** [comment]
This is fixed with #15817.

**Comment by Nandorianen** [comment]
Awesome. Thanks!
