### ISSUE TITLE
Borderless window: screen corruption after alt-tab in hardware mode

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14023]
Alt-tabing in hardware mode works fine first 1-3 times, then corrupts the screen. White noise instead of graphics on lower 80% of the screen. Software mode looks okay so far.

Win-tiles without graphics, 3989, winXP, oldish hardware. Testing in main menu.
Dimensions: 160 x 60 tiles, 1920 x 1080 resolution, fontwidth 12, fontheight 18, fontsize 16, fontblending off.

**Comment by DanmakuDan** [comment]
DirectX (most likely hardware mode renderer that SDL picks) doesn't guarantee that the graphics data will be preserved when tabbing away from a fullscreen app. I don't think the code checks for this, since there is/was a separate issue with draw fail spam in the debug log when you tab away from fullscreen mode. I am not sure what actual data is lost on returning to the game screen.

**Comment by remyroy** [comment]
I tried alt-tabbing using WinXP in fullscreen borderless and I didn't have more issue than with windowed. In both software and hardware graphics mode, it seems like I had a few issues with some kind of shadows (straight lines) on ground tiles. See [software](http://i.imgur.com/k3mP0hF.png) and [hardware](http://i.imgur.com/RGRAZ63.png).

I'm guessing this is a hardware/driver issue. Have you tried updating your graphics drivers?

**Comment by Zireael07** [comment]
I can confirm that screen corruption sometimes happens in windowed mode, too. (I play Cata while doing other things, and occasionally when I reopen/refocus Cata it will be missing chunks of the play window or the log).
I work around it by going to the map screen and back (forcing a redraw, in other words)

**Comment by remyroy** [comment]
This is a little hard to reproduce for me. If it's only happening in hardware mode, it's even harder to debug.

We would need screenshots or videos, more hardware info (like what GPU and CPU you are using), drivers info (version, feature support, etc). Even with this information, there is likely little we can do about it. Without it, we are pretty much blind,

**Comment by Nandorianen** [comment]
It sounds like a lot of work for a very little chance of a very little gain. Not worth it.
Should I close the issue?

**Comment by DLaboratory** [comment]
Still occur as of now. Windows 10 64-bit, Intel iGPU. Maybe we should post it on SDL bug tracker.

**Comment by DLaboratory** [comment]
Filed a bug on SDL bug tracker. [https://bugzilla.libsdl.org/show_bug.cgi?id=3381](https://bugzilla.libsdl.org/show_bug.cgi?id=3381)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.C-7145, Windows XP SP3, tiles, both software and hardware rendering. If this is still reproducible, ping me.
