### ISSUE TITLE
Crash when removing power armor

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#14035]
When wearing a power armor, power armor helmet and hauling frame, when you decide to drop all three at once, the game crashes. Only crashes if they are arranged in specific order.

Steps to reproduce:
1) create a character
2) drop everything
3) wish for light power armor, light power armor helmet, power armor hauling frame
4) wear all three
5) open layering menu and rearrange them: frame first, then the armor, then the helmet
6) open multidrop menu, select all three items, drop them
7) crash:
src/activity_item_handling.cpp:80: tripoint get_item_pointers_from_activity(std::list<item *> &, std::list<int> &, std::list<item *>, std::list<int> &): Assertion `!armor.is_null' failed

**Comment by DanmakuDan** [comment]
The power armor is dropping first, and the other items probably get taken off early as a result. The crash is occurring since it is still processing the other armor items as if they were still there, waiting to be taken off.

**Comment by aleksander** [comment]
I just caught this with 0.C release trying to drop "bindle" simultaneously with other items from the multidrop menu.

**Comment by sparr** [comment]
Confirming bug exists in recent git master.

**Comment by Coolthulhu** [comment]
Does it still happen?

**Comment by codemime** [comment]
> Does it still happen?

Affirmative. I'm on it.
