### ISSUE TITLE
Solar Panels bionic is not working next to [INDOOR] tiles

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14039]
I've been crafting in the open for months with Solar Panels CBM installed in all kinds of weather and my power level hasn't increased once.
Searching through the source code I found this check:
if( has_bionic("bio_solar") && g->is_in_sunlight( pos3() ) ).
However, all other checks like this look like
g->is_in_sunlight(pos()).
Could this pos3 part be the case? I have no idea what it means, but it stands out.

**Comment by BevapDin** [comment]
This is the implementation of `pos3` and `pos` (in creature.h):
```C++
        virtual const tripoint &pos() const = 0;
        virtual const tripoint &pos3() const
        {
            return pos();
        }
```
`pos3` is by all means equivalent to `pos`. (The version with the `3` was created to distinguish it from the the old `pos` function that used to return a 2D-point.)

> my power level haven't increased once.

That might be a stupid question, but is your current power level below the maximum?

**Comment by Nandorianen** [comment]
Naturally.

**Comment by BevapDin** [comment]
Btw. you're looking at old code, 28cd2df5cc83bd084ec704d6bc68fb21b93642a3 changed that `pos3` to `pos`.

**Comment by Nandorianen** [comment]
Err, yeah, sorry about that, haven't updated local source in awhile. Still, I am playing 3900 and have this problem. This should be easy to verify.

**Comment by Nandorianen** [comment]
Did some more testing.
When I stand next to a tile with [INDOORS] tag, I get no power. Moving one tile away from [INDOOR] tile makes Solar Panels work again.
[ROOF] tag doesn't do this. I can stand near or on in a tile with [ROOF] tag and as long as there is no [INDOOR] tiles nearby, I get power.
Is this intended?

**Comment by DanmakuDan** [comment]
According to `map::build_outside_cache( const int zlev )`, anything one tile around an INDOOR tile is counted as inside.

**Comment by kevingranade** [comment]
It's not necessarily ideal, but yes it's intended. Originally this
functionality was added so that single tiles of furniture indoors would not
count as being outside.

**Comment by Nandorianen** [comment]
Shouldn't [ROOF] do that instead? Since they are separated, being indoors without being under a roof shouldn't logically block sunlight.

**Comment by kevingranade** [comment]
Anyway, now that we have furniture and terrain separate, we might be able
to remove this logic.

**Comment by drbig** [comment]
No idea how to label this one.

**Comment by Nandorianen** [comment]
Now that it's clear this is WAI, this is suggestion at most. I could edit OP to reflect that or we can just close it altogether.

**Comment by Leland** [comment]
Closing.
