### ISSUE TITLE
OSX - SDL2 #includes not found - SOLVED (but not fixed)

### ISSUE THREAD

**Issue by LMariachi** [CleverRaven/Cataclysm-DDA#14043]
There are a few #includes that reference `SDL2/SDL.h`, `SDL2/SDL_ttf.h`, and so forth. These came up as not found for me until I deleted the `SDL2/` part, after which everything compiled cleanly.

The files in question are `cata_tiles.cpp`, `cata_tiles.h`, `sdl_tiles.cpp`, `sounds.cpp`, and `player.cpp`. I’d submit patches but I don’t know what the proper #ifdef would be.

Xcode 7.1.1 (7B1005)
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix

**Comment by vickio** [comment]
Using `NATIVE=osx` in your `make` params should fix this as well. Have you read through the Mac OS X section of `COMPILING.md`?

**Comment by LMariachi** [comment]
See [my comment about that on the other thread] (https://github.com/CleverRaven/Cataclysm-DDA/issues/14041#issuecomment-156809290)

**Comment by LMariachi** [comment]
Closed with the same resolution as other thread. Thanks again!
