### ISSUE TITLE
No monsters spawn after worldgen with hordes off 

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14042]
I've generated a new world in 3813 and have been playing it up to 3900.
Static spawn: false, wander spawns: false.
I've played for a year with seasons length set to 30.
The world is populated by zombies and wildlife. However, no additional monsters spawned since world was generated. I've hunted down wildlife around my home base and it's now a dead area, it didn't repopulate. I cleared a few towns and they are now also empty. Loud noises including multiple explosions do not help.
This is the kind of behavior I would expect with static spawn = true.
Was dynamic spawn system disabled completely and replaced with hordes? If so, I think worldgen options need clarification.

**Comment by drbig** [comment]
With both static and wander spawn off I'd say you've just turned off all monsters... (wildlife should spawn though).

**Comment by Nandorianen** [comment]
Well, the description says "spawn zombies at game start instead of during game". I think it's not a mistake to read like this: "true" would make game behave like described above and "false" would mean no native zombie population, but gradual spawn. I set it to latter and got the former.
Second switch's description implies that it moves around spawn points, which doesn't mean that they will be disabled when set to "false".
Together they look like they are separate subsystems, not at all the same as "static NPCs" and "random NPCs", whose description clearly implies that one switch is for initial population only and the other is for dynamic spawning only.
I also remember it previously working like described above. Hence my confusion.
Wildlife also doesn't spawn. I even changed spawn density from 1 to 10 mid-game to make sure.

**Comment by mugling** [comment]
I can't see the bug here?
