### ISSUE TITLE
Item blacklist mods cause crash on worldgen or loading

### ISSUE THREAD

**Issue by ZombiesAreUs** [CleverRaven/Cataclysm-DDA#14044]
Tested on v3899 and v3901. No Joke Monsters mod worked, No fictional guns didn't.

**Comment by chaosvolt** [comment]
Whee, time for me to update to take a look at this, as my desktop version is 22 builds out of date.

On an amusing note, I just discovered that back in build 3879, the blacklist mod does jack shit to profession loadouts. o3o

**Comment by chaosvolt** [comment]
Works:
No religious texts

Doesn't Work:
No mutagen
No antique firearms
No energy weapons
No fictional guns
No flaming weapons
No medieval items
No power armor
No survivor armor

I'm not sure whether to be amused or creeped out that the "disables religious texts" mod is the only item blacklist mod that's still working.
