### ISSUE TITLE
Building with MSYS2, linker fails.

### ISSUE THREAD

**Issue by JornVernee** [CleverRaven/Cataclysm-DDA#14069]
Today I wanted to try to build with msys2 to take advantage of my 8 cpu cores (and in an attempt to get lua builds working. Which wasn't succeeding with code::blocks). I followed the instructions in COMPILING.md but the linker returns the following error (using ```make MSYS2=1 RELEASE=1 NATIVE=win64 -j8```)

```
J:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lncurses
collect2.exe: error: ld returned 1 exit status
Makefile:467: recipe for target 'cataclysm.exe' failed
make: *** [cataclysm.exe] Error 1
make: *** Waiting for unfinished jobs....
J:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lncurses
collect2.exe: error: ld returned 1 exit status
Makefile:25: recipe for target 'cata_test' failed
make[1]: *** [cata_test] Error 1
make[1]: Leaving directory '/j/Cataclysm-DDA/tests'
Makefile:672: recipe for target 'tests' failed
make: *** [tests] Error 2
```

Looks like I need a ```pacman -S mingw-w64-x86_64-ncurses``` ? So that's what I did, and it works now.  

But I'm not so sure if that was really THE fix, or I did something else that fixed it :/ (I was messing around a bit). Like I said, this is my first time building with msys2. So I thought I'd make it an issue, instead of going to update the instructions myself.

**Comment by pouar** [comment]
No, that is the fix.

**Comment by JornVernee** [comment]
thnx
