### ISSUE TITLE
Lag spikes

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14067]
After playing multiple versions between 3813 and 3900 I can report several places where game just hangs up for a few seconds.
1. First time I open my map after loading game. Don't know if it's related to #13077 .
2. When I scroll my map sufficiently to the side.
3. Each time dynamic NPC spawn occurs. This one is heavy, going on for 10-15 seconds for me.
4. When NPCs spawn someone for quests like their zombie mothers. Probably related to number 3.
There is also an issue of game loading pretty slowly and crafting menu opening slowly in my hoarder base, but those are different.

Using win-tiles with no tiles, tried both software and hardware modes, didn't notice any difference. WinXP, 2 GB RAM. Tried on normal hard drive and on SDL. Also no difference.

**Comment by DanmakuDan** [comment]
For the map scrolling, the unserialize method being used on the overmap has a significant delay before continuing. With a debugger, most of the delay was from loading the "layers" and "mongroup" from the overmap file.

**Comment by mugling** [comment]
One of a series of PR's that likely relate to blob division so closing these and tagging #14308 as performance concern

**Comment by Nandorianen** [comment]
Not sure I understand. How is map loading/scrolling and NPC spawning related to blob division? This happened right from the world start, by the way, no blobs in sight.

**Comment by DanmakuDan** [comment]
I was checking the random NPC spawning scenario, everything in this list is related to #13077. Loading an overmap has slow performance. 
1. It looks like the main overmap isn't completely loaded until you open the map.
2. Scrolling enough that another overmap (that you have already generated) is in view on the map screen will load the overmap.
3, 4. If a NPC is assigned a mission that requires having a nearby town, it will check the overmaps in a 3x3 square to find a closest town. This causes basically 9x the lag of case 1.

This has nothing to do with #14308, btw.
