### ISSUE TITLE
Readme file: md2html conversion in stored Jenkins builds

### ISSUE THREAD

**Issue by illi-kun** [CleverRaven/Cataclysm-DDA#14089]
I have a specific request (to @narc0tiq, mostly) but I'm not sure is it welcomed by community & users.

Is it possible to convert readme.md to its html analogue in builds stored in archives of Jenkins builds (http://dev.narc.ro/cataclysm/jenkins-latest/) or in stable builds at least? I found some utilities (markdown2html) but I don't test it well.

I'm asking about that because common user is more familiar with html extension/file format than markdown (random text editor will display content of the file but without some nice features, like headers, links and so on).

**Comment by narc0tiq** [comment]
Wouldn't be too hard to make it work in Jenkins builds, but it looks pretty shit: <http://dev.narc.ro/cataclysm/README.md-sample.html> (this is using [waylan/Python-markdown](/waylan/Python-markdown), in the form of the deb package `python3-markdown`; command line was `python3 -m markdown -o html5 -n < README.md`).

To the best of my knowledge, Markdown's intent was to be readable as is, and is based on commonly-accepted plain-text email "formatting". Rendering it to HTML seems to me like it defeats the purpose, for minimal benefit.

**Comment by drbig** [comment]
Well, we could add a .css to it. It could look very neat with minimal effort.

**Comment by illi-kun** [comment]
@narc0tiq, thank you for instant reaction on my request, I appreciate it.
It seems that I want to fix non-existent issue. Well, it happens :-)
