### ISSUE TITLE
The new minimap overlaps on the message log on minimum screen size

### ISSUE THREAD

**Issue by remyroy** [CleverRaven/Cataclysm-DDA#14094]
See:

![minimap overlap](http://i.imgur.com/ejQ9mku.png)

That was taken on OSX with version 7536-g243b52d. The terminal width is 80. The terminal height is 24.

**Comment by remyroy** [comment]
The same problem happens on Windows as well:

![minimap overlap](http://i.imgur.com/iIFVkxK.png)

**Comment by chaosvolt** [comment]
Also of note, it still cuts short the message log on larger window sizes, and will fuck it up even when the option is disabled in options.

**Comment by chaosvolt** [comment]
And to confirm my earlier statement:

![can we fix it](https://cloud.githubusercontent.com/assets/11582235/11311641/b221f998-8f96-11e5-87e9-456d37c97702.png)

![nope its fucked](https://cloud.githubusercontent.com/assets/11582235/11311648/b595ab24-8f96-11e5-968f-4107d75d2e0e.png)

**Comment by drbig** [comment]
You do know there's an option to have recent log messages on top? :D

**Comment by chaosvolt** [comment]
Okay, um...I'm having some weird shit going on.

When I saved and loaded the game after turning the minimap off, it stopped eating the message bar. >_>

**Comment by drbig** [comment]
> When I saved and loaded the game after turning the minimap off, it stopped eating the message bar. 

That actually sounds exactly what you'd expect after turning the minimap off and restarting :)

**Comment by chaosvolt** [comment]
That's good at least. If it was permanently blocking the message bar, I'd be annoyed. XP

**Comment by remyroy** [comment]
This can be closed since #14105 was merged.
