### ISSUE TITLE
Game generates "destination area is full" for every item in a stack player tries to move

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14095]
There is an item number limit for any tile, which seems to be 4096. It's not that hard to reach if you disassemble all useless consoles throughout a lab raid and store all the scrap in your car.
If you try to put more items in a tile that already stores 4096 items, game will generate a message saying you can't. You have to press spacebar to close it.
![area full](https://cloud.githubusercontent.com/assets/7211122/11317942/b3ef116a-9050-11e5-8c7b-ff3c4ff9aafa.PNG)
Interestingly, it generates incorrect message for vehicle tiles. "Area is full" is for volume limits. "Too many items" should be generated instead.
Trying to place too many items on the floor gives appropriate message.
![area full 2](https://cloud.githubusercontent.com/assets/7211122/11317944/bb708540-9050-11e5-934b-da0b739cf5aa.PNG)

So, here is the problem: when moving a stack of items in an already full vehicle tile, game will generate a warning message for each item in the stack. So trying to move 100 too many scrap items means you will have to press space bar 100 times to get on with your life. There is very little visual indication that something is happening in some cases, so it may look like your game hanged - you press buttons, but nothing happens.
When you try placing too many items on the floor, you only get one message. This should be the case for vehicle tiles too.

I am pretty sure it's not platform-specific, but anyway:
Win-tiles, 0.C-3934 and many more before that. Windows XP.

**Comment by drbig** [comment]
Hmm, was that in red as in `DEBUG: ...` spam?

Also reading [this](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/ISSUES.md) would make you state version and platform etc. so e.g. I could try to replicate it quickly.

**Comment by Nandorianen** [comment]
Sorry, after reading OP another time I can see it's not too clear what I meant. Updating it to clarify.

**Comment by etmoonshade** [comment]
I've had a similar experience with too many items. I -do- notice the message blink occasionally when hitting space, but it definitely seems weird - the message should only display once.

I had this issue in 0.C-3894.

**Comment by ifreund** [comment]
This has been fixed, though I can't find the exact pull request that did it.
