### ISSUE TITLE
Handload stats

### ISSUE THREAD

**Issue by mauledbybears** [CleverRaven/Cataclysm-DDA#14090]
See #14075

A standard for handload stats would be useful. I'm thinking 95% damage, 100% recoil, 105% dispersion, 80% pierce and 95% range, all rounded to the nearest integer.

**Comment by illi-kun** [comment]
I've found this interesting note:
>"Reloads CAN be more accurate than factory ammo, generally they are but not all loads fit all rifles. So, the same rationale fits for factory ammo, it CAN be accurate in most rifles but not all. And yes, the tuning/fitting/level of consistency between loads is why reloads are more accurate than factory."

So, reloaded ammo can be even better than its factory alternative but it should be prepared for exact type of firearms.

**Comment by mauledbybears** [comment]
I think developing wildcat cartridges is beyond the scope of the current crafting system. Cata's reloads would be aiming to be as close to factory rounds as you can get without real manufacturing equipment and materials.

Remember that in 2015 people reload with properly made bullets. Your survivor has to make whatever works with any metal to hand and copper tubes. The bullets you can make like that wouldn't perform as well as pre-cataclysm projectiles.

**Comment by Robik81** [comment]
Yeah, some kind of standard is IMO way to go. Last time i balanced reloaded ammo (long time ago), I used this system, it was before big aiming overhaul, so numbers most likely does not make sense anymore:

Differences of reloaded vs. factory ammo:
only these parameters can be different: Damage, Armor Penetration, Dispersion and Recoil
if parameter in question is <= 5, it has same value anyway
Damage and AP value changes by -1
Dispersion and Recoil value changes by +1

Examples:
.223 Remington
Damage: 36 -> 35
AP: 2 -> 2
Dispersion: 7 -> 8
Recoil: 30 -> 31

.30-06 AP
Damage: 50 -> 49
AP: 30 -> 29
Dispersion: 1 -> 1
Recoil: 36 -> 37

**Comment by illi-kun** [comment]
Any consistent & properly declared system is much better than no system at all.
Comparing two versions (@mauledbybears vs. @Robik81) first one is better from my point of view.

**Comment by mugling** [comment]
Standardised system was implemented via `copy-from` inheritance. Adjustments to balance are readily possible if anyone feels the chosen values are incorrect and wants to submit a PR.
