### ISSUE TITLE
Curses log broken

### ISSUE THREAD

**Issue by tvm1** [CleverRaven/Cataclysm-DDA#14097]
The merge of this new minimap b0rked log window.

With 80x24 term I get exactly one line of log.
![screenshot from 2015-11-20 13 26 26](https://cloud.githubusercontent.com/assets/12072674/11299913/0a815a22-8f8b-11e5-930c-ab2f40ebf7e9.png)

With larger term I get more lines, but the log will never use whole space that is available.
![screenshot from 2015-11-20 13 28 10](https://cloud.githubusercontent.com/assets/12072674/11299914/0a890646-8f8b-11e5-9902-e976b4f35bc1.png)

**Comment by Zireael07** [comment]
I guess the space for new minimap is reserved regardless whether you're using tiles or not, but the new minimap is only displayed in tiles mode.

**Comment by chaosvolt** [comment]
Seems the minimap has broken the message log in general. >.>

**Comment by remyroy** [comment]
Related to #14094.

**Comment by drbig** [comment]
Tested locally. No idea if it's the minimap, but something is seriously broken indeed, proof:

[What?](http://i.imgur.com/FbYV9f5.png)

**Comment by chaosvolt** [comment]
...your sidebar looks like its in full-on Zalgo mode. ;w;

**Comment by CIB** [comment]
Those are all screenshots from wide sidebar style. Does https://github.com/CleverRaven/Cataclysm-DDA/pull/14105 fix?

**Comment by CIB** [comment]
Yup it does.

**Comment by chaosvolt** [comment]
So I'm assuming this can be closed, or...?

**Comment by drbig** [comment]
@tvm1 Check if fixed and close please :) (When you have some time for that of course!)

**Comment by tvm1** [comment]
Yep, works fine now. Closing.
