### ISSUE TITLE
Warnings about dogs are unnecessary with Animal Empathy

### ISSUE THREAD

**Issue by MisterFelixFox** [CleverRaven/Cataclysm-DDA#14119]
Dogs never attack the player if they have wild empathy, but the game constantly screams about 'THERE IS DOG NEARBY' and interrupts everything because of it. Can it be changed to not freak out at the player when they have Animal Empathy?

**Comment by chaosvolt** [comment]
I've noticed that even without that trait, dogs rarely go beyond tracking mode. Funny enough, the only time I've been attacked by a dog was the "friend" dog from the "go fetch my dog" NPC quest.

**Comment by madprogrammi** [comment]
Is this with safe-mode enabled?

**Comment by MisterFelixFox** [comment]
@madprogrammi Yes, this is with safe mode enabled

**Comment by Night-Pryanik** [comment]
0.C-6372, Win 10 x64, curses.
Dog's aggro turns to "Ignoring" with Animal Empathy, so safe mode isn't reacting on it.
Should be closed?
