### ISSUE TITLE
Human corpses shouldn't be naked

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14112]
I suddenly realised that it's pretty weird that human corpses generated inside labs are all naked. Maybe in other locations too. They probably should have some clothing and items even if they are prisoners, test subjects and such, more so if they are scientists, technicians, guards, soldiers or other personnel.

**Comment by chaosvolt** [comment]
Hmm. Looks like it might be feasible to replace the "place_body" calls with place_items and give it item groups to reference. Assuming that allows collections instead of distributions?

**Comment by Headjack** [comment]
It'd be nice if they were rotten or bones if enough time has passed before generating that tile.

**Comment by ejseto** [comment]
I believe they would, if labs weren't almost universally below 50F. Corpses on the surface, like those in the drug dealer massacre, will yield rotten meat after a season or so, and after a couple years, the corpses won't even appear, just their belongings.

**Comment by Headjack** [comment]
Huh. Maybe you're right? I've thought before that they usually rot shortly after being found, and definitely faster if butchered. Could be wrong or outdated.

**Comment by chaosvolt** [comment]
Slower than if the same corpses were on the surface. Enough that it makes lab challenges a little easier if you have the Psychopath trait, as you have less pressure to hurry up, get level 4 cooking, and secure your immediate food needs. Which buys more time to explore and secure the method of escape. XP

**Comment by Leland** [comment]
Closing - old and no movement. Feel free to ping me here if there's still interest, or make a new issue.
