### ISSUE TITLE
Suggestion: Change the background of "Bookstore" maptile text

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#14126]
http://i.imgur.com/XLerpXz.jpg

White on yellow is *atrocious* to read.

**Comment by madprogrammi** [comment]
I came across this problem too. My color scheme made it very hard to read - a temporary workaround was to change the color scheme a bit. This should really be changed though. I believe the biggest barrier is that CDDA is running out of color selections, but I don't think this should have been one in the first place.

**Comment by mugling** [comment]
This appears to have been completed

**Comment by sethsimon** [comment]
This should be reopened. On version 9c3959973f1aa3f6517f6726c70f78170e0152f9, it uses the same colors:
![bookstore01](https://cloud.githubusercontent.com/assets/16765166/16966991/0b7fdcc4-4dd5-11e6-8e63-ed0774083399.png)
