### ISSUE TITLE
Sound pack/set just like tiles

### ISSUE THREAD

**Issue by remyroy** [CleverRaven/Cataclysm-DDA#14127]
It would be nice to have sound packs/set that could be chosen in the options just like the tileset. It would also be nice to have them in an alternate path from the game directory so they can be preserved when updating the game similar to how configs and saves are stored when using `USE_HOME_DIR=1`.

**Comment by chaosvolt** [comment]
Only issue with this is that it adds to the file size to have the sounds included in the game. Though at this point the tilesets likely outweigh most sound packs. @_@

However, simply adding support for that feature, then having the default setting be to not use sound packs, would be a good way to do so.

**Comment by drbig** [comment]
Yeah having UI for soundpack choice sounds very natural. It's very unlikely any non-bare-bones soundpack will ever be shipped with the game, but the UI should be there IMO.

**Comment by remyroy** [comment]
This has been implemented with #14218.
