### ISSUE TITLE
Arachnid arms and torso armor

### ISSUE THREAD

**Issue by Ygdrad** [CleverRaven/Cataclysm-DDA#14129]
I've been looking up why my arachnid arms are giving dex and making me lose dex when wearing torso armor. Turns out that searching on github does not turn up all the results it should. Manually looking through files individually, I ran into the following bit of code in src/player.cpp.

>    if (has_trait("ARACHNID_ARMS_OK")) {
>        if (!wearing_something_on(bp_torso)) {
>            mod_dex_bonus(2);
>        }
>        else {
>            mod_dex_bonus(-2);
>            add_miss_reason(_("Your clothing constricts your arachnid limbs."), 2);
>        }
>    }

I find it incredible that the character can create all sorts of clothing to deal with all sorts of things and yet is unable to make something that wont get in the way of his extra arms to the point of not only cancelling the dexterity bonus, but actually turning it into a malus.

This doesn't seem to make much sense. We've got all manners of loose and/or sleeveless clothing pieces already and failing that any sort of wrappings carefully placed should do the trick. Any kind of cloak or tabard touching nothing but the front and/or back of the torso would also fail to get in the way of the arms.

**Comment by chaosvolt** [comment]
At a bare minimum, it should check for the "OVERSIZE" flag. -w-

**Comment by Ygdrad** [comment]
Maybe make it +2 dex with no clothes, 0 dex with oversized, and -2 with normal clothes?

**Comment by mugling** [comment]
Fixed by  #14178
