### ISSUE TITLE
High strength causes pickup from advanced inventory to fail.

### ISSUE THREAD

**Issue by etmoonshade** [CleverRaven/Cataclysm-DDA#14122]
With a strength of 200 (shush, playing with the debug menu :) ) attempting to move items from elsewhere to the characters inventory generates an "This is too heavy!." message.

Playing with it a bit, I noticed that the maximum I can set my strength to without causing this message is 105. Oddly, I can pick items up off the ground just fine using "," - I assume the bug is specifically in advanced inventory.

Also, note the weird punctuation in the message - "!." instead of "!".

https://dl.dropboxusercontent.com/u/22571912/Pics/Games/DDA/TooHeavy.PNG Screenshot of the issue after trying to move an item.

Edit: This is on 0.C-3934, Windows x64 Tiles.

**Comment by madprogrammi** [comment]
Confirmed working, Linux 64bit, latest git, terminal build.

**Comment by madprogrammi** [comment]
Stepping through this a bit, it looks like an integer overflow causing it to be negative, which trips the "This is too heavy!." message. Turns out the punctuation is actually written that way in the code. I don't think this is really an issue, since the only time you'll have that much strength is during zany debug sessions. :)

**Comment by etmoonshade** [comment]
It's the inconsistency more than the bug itself that bothers me. :)

I can pick stuff up fine - it just makes it so I can't use my advanced inventory when I want to do so.

**Comment by kevingranade** [comment]
There's a reason we have max stats, we use all kinds of formulas based on them that are prone to this kind of thing, problems that are only reachable by setting your strength out of bounds are not bugs.
