### ISSUE TITLE
Getting pulled by a grabber zombie while aiming a heavy machine gun will cause a crash

### ISSUE THREAD

**Issue by PhilUranus** [CleverRaven/Cataclysm-DDA#14121]
I was sitting on an empty window frame, mowing down a horde with my shiny RM298 HMG. There he laid, the last zombie (a grabber, mind you). I steady my aim, then just before I pull the trigger BOOM - He cheats and saves his life by making the game crash.

**Comment by drbig** [comment]
Getting that replicable would be the first step. And/or debug...

**Comment by mugling** [comment]
Much of the firing code has since been replaced out so I'm closing this unless it can be reproduced
