### ISSUE TITLE
Crafting consumes HackPro charges

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14134]
If you found a USB with HackPro software, you can craft control laptop. One. Apparently this piece of software spawns with 1 charge that is not displayed anywhere, and crafting with it consumes that charge, making it useless.
Probably works like this for software in general, but there is not much use for other programs for it to affect anything.
Win-tiles 0.C-3934.

**Comment by chaosvolt** [comment]
This falls under the general issue of not being able to specify "container, fulla what we want" as a component. It's either "container as component, ignorant of what it contains" or "contents as a tool, thus leaving the container/tool drained" and neither is ideal.

**Comment by BevapDin** [comment]
> This falls under the general issue of not being able to specify "container, fulla what we want" as a component.

I disagree:
1. the software is supposed to be *not* be consumed at all.
2. even if the software were to consume, the USB stick should remain.

**Comment by chaosvolt** [comment]
Hmm. Possibly. So many simply set it to demand some Hackpro as a tool, but not to consume it?

And thus the player-character masters the sorcery that is copy-paste.
