### ISSUE TITLE
Disappearing medications

### ISSUE THREAD

**Issue by Salganos** [CleverRaven/Cataclysm-DDA#14137]
Some items have mysteriously and conspicuously vanished from my medication pile in my house, notably aspirin, vitamins, and antifungal drugs.  They are nowhere to be found.  I'm quite certain I had lots of aspirin, at the least, as i keep finding the stuff in large amounts.  Yet it is all gone.

Dynamic NPCs are off; version is efc0cca, Windows graphical.

I don't think this has ever happened before.  It is not good for one's sanity.

Edit: add every random pharmaceutical I looted from two doctors offices to the list of missing things.  The missing items, as far as I can tell, are all pills.  The only ones remaining are some antibiotics.

**Comment by Zireael07** [comment]
Did you use the AIM to move them? How many items are there in the pile? Did you move the saves between versions?

**Comment by Salganos** [comment]
I used AIM to add to the pile, on occasion.  The pile had quite a number of items, but not as much as some, such as my ammo pile, which does not appear to have shrunk any.  I do move saves up versions.

**Comment by Nandorianen** [comment]
Do you use vehicles to drive around your piles? Then I have bad news for you. I recently discovered that they damage items on the ground now. Hard. And you probably have tons more stuff you are now missing.
Had to roll back to a day-old save when I accidentally discovered that one. Not a fan.

**Comment by Salganos** [comment]
I have not driven vehicles inside my shelter.  I have dragged laden flat-bed shopping-carts over things, but I do that all the time, and deliberate experimentation has shown no sign of damage from doing so even now.

**Comment by Beanzy** [comment]
Did you try moving all the items in the pile to a different location (like an adjacent tile). Are the pills still gone if you do this?

**Comment by Salganos** [comment]
I move all the remaining "Drugs" in the pile elsewhere, but I did leave some other stuff in the pile there.  Next decent chance I get I will move the rest as well, just to be sure.

**Comment by Salganos** [comment]
I've moved the rest of the stuff.  Still gone.  Total mystery.  Ugh.

**Comment by Headjack** [comment]
Sometimes I autopickup things accidentally. Do you use that?

**Comment by Salganos** [comment]
Nope.  And I'd probably have noticed the piles of iodine, aspirin, vitamins, and random prescription meds cluttering my inventory.

Is there anything in the game code that is even able to just remove items like that?

**Comment by Zireael07** [comment]
The only thing I can think of is the AIM bitching and refusing to move stuff. Sometimes it has resulted in items disappearing. I've yet to experience something similar when dropping via normal inventory.

**Comment by Salganos** [comment]
Now I've found that the chemistry sets are missing.  I was sure I had at least one from a mobile meth-lab with a broken lab part which gave an intact chemistry set when removed.  The meth-lab is still where I left it, with the part removed ...

There was another mobile meth-lab somewhere else in the town to salvage from, so I'm not outright screwed, but this is very disturbing.  I don't know if it vanished in the same event that ate the pills, but I don't feel like I can trust this game the leave stuff where I put it anymore.

**Comment by Nandorianen** [comment]
Did it happen before these got merged? #13861, #13880.
They also link to an issue. Sounds similar to yours?

**Comment by Salganos** [comment]
May be similar, but I was moving things from a cart to the ground, in general, which is the inverse of the issue these reference.

**Comment by Nandorianen** [comment]
Do you normally use "move all" button or move stacks separately? I hear "move all" may still have some bugs. Never had any problems with moving stuff separately, which I do A LOT.

Also when you moved your cart over stuff to test if it breaks anything did you try it with empty cart? This mechanic is most likely affected by weight, so it should be tested with heavily loaded cart. Also some items may not be affected (metal? cloth?), but some definitely are (flesh, vegetable matter, etc).

**Comment by Salganos** [comment]
I had tested it with a rather full cart, just to be sure.  And I generally moved things over one at a time, so i could sort things into the appropriate tile.  Sometimes I even dropped stuff right out of my inventory.

This mystery is likely as solvable as its existence is provable. :(
