### ISSUE TITLE
Cygwin Crash

### ISSUE THREAD

**Issue by karols146** [CleverRaven/Cataclysm-DDA#14131]
![bug](https://cloud.githubusercontent.com/assets/7023710/11324197/621c6a3c-912b-11e5-8a1d-460b4ca7fc2c.jpg)

just like always std stuff 
pulled source just today

**Comment by BevapDin** [comment]
This looks suspiciously like #14124.

**Comment by karols146** [comment]
Yea I just don't see that error.

**Comment by illi-kun** [comment]
Can be closed since #14111 is merged.
