### ISSUE TITLE
Rain does not fade out when indoors no more

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#14130]
Build 3938 64bit

Rain does not fade out no more like it used to.

Befor if I went indoors or inside my car the rain sound would fade out and you would not be able to hear it no more now its 100% volume all the time.

http://smf.cataclysmdda.com/index.php?topic=10390.165

**Comment by stk2008** [comment]
Build 3938 64bit

Rain does not fade out no more like it used to.

Befor if I went indoors or inside my car the rain sound would fade out and you would not be able to hear it no more now its 100% volume all the time.

http://smf.cataclysmdda.com/index.php?topic=10390.165

**Comment by drbig** [comment]
Hear it as in the character hearing it or as in you with sounds?

**Comment by stk2008** [comment]
Ah hearing as in me hearing it.

**Comment by drbig** [comment]
Yeah, don't think "the sounds" are that advanced yet :)

**Comment by stk2008** [comment]
No im saying befor one of the updates the rain sound would drop in volume
it might have actually changed to a different sound all together when u
went indoors.

Now the rain stays at 100% volume

**Comment by stk2008** [comment]
After going back to it today it now seems to work as it did befor.
Very odd maybe saving it and reloading it fixed the issue?.

This can be closed now

Thanks
