### ISSUE TITLE
Add option to disable ASCII/Tile light filters

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#14148]
![tief im nacken](https://cloud.githubusercontent.com/assets/11582235/11343758/164b8c20-91d3-11e5-80a3-3a972ffa0145.png)

![das grauen sitzt](https://cloud.githubusercontent.com/assets/11582235/11343815/7d7ef710-91d3-11e5-9c97-fd15cc59b273.png)

While https://github.com/CleverRaven/Cataclysm-DDA/pull/13715 certainly added an interesting effect, here are times when I wish it was optional. Regardless of realism, would it be that much of an immersion-breaker to allow disabling it?

**Comment by DanmakuDan** [comment]
Are you talking tiles only? The ASCII shading was added by someone else some time before I did the tiles.

**Comment by chaosvolt** [comment]
Ah. Hmm. Since I've rarely messed around with ASCII mode...odd. I would assume that making it optional in either display mode might be best, if that's feasible. That would increase complexity though. ^^"

**Comment by kevingranade** [comment]
You need a strong reason to make features optional, 'I think this is
annoying' doesn't cut it.  Options make the code more complicated and make
the game harder to configure.

**Comment by chaosvolt** [comment]
There is the fact that most of ASCII mode, and a large amount of sprites in tiles mode, rely on coloration to distinguish different terrain, items, and monsters. >.>

**Comment by vache** [comment]
And the dark shading is the game's way of telling you that it is not bright enough to distinguish defining features easily.

**Comment by DanmakuDan** [comment]
Should we have monsters in tiles display with regular color then?

**Comment by chaosvolt** [comment]
That might be a good bit of consistency, yeah. Especially since that has the highest potential for "oh shit" moments.

**Comment by kevingranade** [comment]
How is it 'consistent' for monsters to be effectively lit when in shadow?
And yes, things in shadow means they are hard to see, at some point the
rest of the system will catch up and not tell you exactly what items or
monsters in shadow are, for example saying something like 'a humanoid
figure' for most zombies.

**Comment by chaosvolt** [comment]
Though this will inevitably create inconsitancies like "why does this steel compactor look like a busted door" or "holy shit I can't tell which zed is a hulk and which is a normal one unless I examine them" etc etc.

If we're going to go for player confusion, it should first be fleshed out to avoid instances where attempted realism just makes things more absurd. >_>

**Comment by DanmakuDan** [comment]
Based on kevin's description, if you examined a hulk in the dark, it would just be some 'huge figure'.

**Comment by chaosvolt** [comment]
Hmm. Having size factor into it would be a good idea, yes.

However adding the foundation for this should probably be prioritized over greying out the monsters in ASCII mode.

**Comment by kevingranade** [comment]
It's not a matter of priority, one is infinitely easier than the other.

**Comment by chaosvolt** [comment]
Right. Easier, yes. But likely should still have the more complex change dealt with beforehand.

In addition, is there any sane reason for you adding the "wontfix" label? If you're flat-out vetoing this suggestion, then just say so, and either tell me to close it or close it yourself. Adding that label serves no useful purpose whatsoever.

**Comment by Rivet-the-Zombie** [comment]
It's informative if/when somebody searches for this topic to see if it's already been suggested.

**Comment by chaosvolt** [comment]
Hmm. Understandable then. Sorry.
