### ISSUE TITLE
Candles work underwater

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#14151]
`iuse::autotransform` is bugged in that the check for `when_underwater` will never be called

**Comment by BevapDin** [comment]
@mugling Did your PR fix the issue? If so, this should be closed, otherwise it should explain why and how it is still an issue.

**Comment by mugling** [comment]
@BevapDin No, the issue remains outstanding but I have identified the problem and have a fix in mind. 

I was intending to submit a further PR deprecating `auto_iuse_transform` as its broken and implement the required functionality in `iuse_transform`. It's likely to be the weekend however before I have time to commit anything.

The long term goal would be to extending `iuse_transform` so that items can be transformed when dropped/worn/damaged etc. The original motivation was the problem noted by @Coolthulhu in #13925

**Comment by scorpion451** [comment]
I have to say, this might be one of the funniest bugs I've ever seen. X3
