### ISSUE TITLE
Vehicles unexpectedly flip 180 degrees when pushed/pulled

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#14169]
If you grab a vehicle from the front and push towards it, or grab a vehicle at the back and pull it, then it unexpectedly flips 180 degrees (and you usually end up losing your grab because the flip moves the edge of the vehicle out of reach or on top of you)

Before, vehicle grabbed, it's facing north:

![veh-grab-move-1](https://cloud.githubusercontent.com/assets/3055062/11401909/eea4eba6-938c-11e5-9b97-f5ec37e8294a.png)

After moving one tile south, now it's facing south (and it's displaced sideways too)

![veh-grab-move-2](https://cloud.githubusercontent.com/assets/3055062/11401915/f416769a-938c-11e5-8144-a1c366885773.png)

This is very noticeable with two-tile hauling carts as they invariably flip out of reach all the time. Also if you're trying to move a multi-tile thing around in a confined space it will collide unexpectedly as it flips.

The correct behaviour here I think is:
- rotate the vehicle so that the player position, grabbed part, and vehicle center are in a line. There will be two solutions, pick the one that rotates less.
- translate the vehicle in the direction the player moved until it is adjacent to the player

**Comment by scorpion451** [comment]
Would also love to see this implimented, if only because it would make pushed/pulled carts larger than 1x1 a functional part of the game.

**Comment by sparr** [comment]
the new vehicle pivot logic should make this solvable

**Comment by Oskar636** [comment]
@illi-kun Vehicles still do this. They can be grabbed anywhere but essentially the game will work it's way so only the front gets grabbed. The system is really awkard for moving vehicles larger than two tiles, and even two tile ones do these teleportations if you grab them by the back which cause. Another issue is that you can't push vehicles even when grabbed by the front, sometimes it works for a few tiles but that's it.
Build 5864 windows 64bit tiles

**Comment by wapcaplet** [comment]
Still reproducible in 0.E-6177-g 9f4a1b841d

**Comment by NetSysFire** [comment]
Can confirm this is still reproducible and also probably related to #53555, as I could reproduce the parts duplication when the city car flipped and I was also suddenly in the car.

**Comment by anoobindisguise** [comment]
Still happening as of 12/20/22
