### ISSUE TITLE
3755ac8 breaks my modded tileset

### ISSUE THREAD

**Issue by pouar** [CleverRaven/Cataclysm-DDA#14163]
I keep my parts in a separate png file as it makes it much easier to update and reduces diff size between changes. anyway 3755ac8d81b7063ecf8e202159ae354f434097e3 causes my tileset to throw "invalid value for fg (out of range)"

my tileset is located here in my branch btw
https://github.com/pouar/Cataclysm-DDA/tree/diaperfur/gfx/MShock32DiaperfurTileset

**Comment by BevapDin** [comment]
What is the exact error message? It should contain line number and column and show the surrounding JSON data.

**Comment by pouar** [comment]
```
src/sdltiles.cpp:1503: failed to initialize tile: line 23269:11: invalid value for fg (out of range)
```

**Comment by chaosvolt** [comment]
I would assume it means your tileset file isn't large enough for that specific sprite assignment to reference a valid section of the image.

**Comment by pouar** [comment]
weird, it worked perfectly fine before this commit

**Comment by chaosvolt** [comment]
Hmm. Can you pinpoint what parts of it are causing the error?

**Comment by pouar** [comment]
this is the line the game started complaining about after 3755ac8
https://github.com/pouar/Cataclysm-DDA/blob/diaperfur/gfx/MShock32DiaperfurTileset/tile_config.json#L23269

**Comment by chaosvolt** [comment]
Hmm. It absolutely shouldn't be freaking out over using the second sprite space. I'm guessing that's the first comment in the file. I've never tried placing comments in tile_config. See if removing that comment unfucks it or at least moves the error to the next sprite assignment. If it DOES then either it dislikes comments, or dislikes having URLs in comments. Which is a weird thing for it to suddenly start doing. o.O

**Comment by pouar** [comment]
issue still there

**Comment by chaosvolt** [comment]
It didn't move to freaking out about the next sprite assignment? o.O

**Comment by pouar** [comment]
nope

**Comment by chaosvolt** [comment]
Odd.  o.O
