### ISSUE TITLE
ARM: patch for -Werror=sign-compare

### ISSUE THREAD

**Issue by keenerd** [CleverRaven/Cataclysm-DDA#14161]
Arm assumes that char types are unsigned while x86 assumes they are signed.  This creates problems with comparisons.  Specifically

    src/wcwidth.h: In function ‘int bisearch(wchar_t, const interval*, int)’:
    src/wcwidth.h:76:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
       if (ucs < table[0].first || ucs > table[max].last)

The file `src/wcwidth.h` should have the interval struct changed to be

    struct interval {
      wchar_t first;
      wchar_t last;
    };

Tested on armv7, i686 and x86_64.  This issue is also present in the 0.C release, and is the only ARM issue I could find.

**Comment by narc0tiq** [comment]
Yeah, that seems pretty straightforward -- we're comparing a `wchar_t` to the elements in the `struct interval`s in the passed-in array, so clearly those elements should be `wchar_t`, as well.

I assume there's a reason you didn't submit this as a Pull Request? I can formulate one fairly quickly, if you'd like.

**Comment by keenerd** [comment]
Go right ahead.  (I didn't create a pull request because git won't let you do that from a shallow clone, and downloading 500MB per line of patch seems excessive.)  Does project accept email patches (`git format-patch` and `git send-email`)?

**Comment by narc0tiq** [comment]
We have nothing for automatically doing so, but if you paste me a patch in
the right format, I'll put it into a file and run `git am` over it. That
may be the easiest way to preserve authorship.

**Comment by keenerd** [comment]
I really don't care one way or the other.

**Comment by narc0tiq** [comment]
On `x86_64-w64-mingw32.static-g++` (Linux-to-Windows64 cross-compile), this patch fails with implicit narrowing conversions (`-Werror=narrowing`):

```
ccache /home/narc/mxe/usr/bin/x86_64-w64-mingw32.static-g++  -DRELEASE -DCROSS_LINUX \
-DGIT_VERSION -DTILES -DLOCALIZE -ffast-math -Os -Wall -Wextra -Werror --std=c++11 -MMD \
-I/home/narc/mxe/usr/x86_64-w64-mingw32.static/include/SDL2 -DSDL_SOUND -DLUA \
-I/home/narc/mxe/usr/x86_64-w64-mingw32.static/include/SDL2 \
-I/home/narc/mxe/usr/x86_64-w64-mingw32.static/include/SDL2 \
-I/home/narc/mxe/usr/x86_64-w64-mingw32.static/include/libpng16 \
-I/home/narc/mxe/usr/x86_64-w64-mingw32.static/include/SDL2 \
-I/home/narc/mxe/usr/x86_64-w64-mingw32.static/include/freetype2 \
-c src/catacharset.cpp -o objwin/tiles/catacharset.o
[...parts ellided...]
In file included from src/catacharset.cpp:5:0:
src/wcwidth.h: In function 'int mk_wcwidth(uint32_t)':
src/wcwidth.h:177:3: error: narrowing conversion of '68097' from 'int' to 'wchar_t' inside { } [-Werror=narrowing]
   };
   ^
```

The complete build log is available at <http://dev.narc.ro/cataclysm/14161-oops.txt>. Realistically, this probably just means running through and putting `UL` after all the constants, but that's definitely not as simple as a two-liner patch.
