### ISSUE TITLE
Blank character instead of hashtag in map.

### ISSUE THREAD

**Issue by lekto** [CleverRaven/Cataclysm-DDA#14189]
I stand in shelter, 1 square to the north from broken console, with open left window on north wall. When I press 'm', in place where was unlighted bench I get blank character on map.

version: 0.C-7759-g8841bf9
compiled: make -j4 TILES=1 LOCALIZE=0 LUA=1 DYNAMIC_LINKING=1
system: Gentoo x64
![cataclysm bug](https://cloud.githubusercontent.com/assets/10973738/11429684/91d130ac-947b-11e5-999b-c693f877de17.png)
![cataclysm bug2](https://cloud.githubusercontent.com/assets/10973738/11429686/9a299230-947b-11e5-8ddb-cd3039e66aaf.png)

**Comment by Zireael07** [comment]
Getting the same, same version and hash, Win 7.

**Comment by lekto** [comment]
Same effect with dirt and field (brown dot).

**Comment by DanmakuDan** [comment]
There was an erase/refresh cycle added to the map legend window to clear the pixel minimap (#13960) when switching maps, but it has the unintended effect of deleting whatever the map buffer is setting up.

**Comment by lekto** [comment]
Works fine now.
