### ISSUE TITLE
Item interface: learned recipes no longer have different color

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14188]
After #14057 (I think) recipes are no longer differentiated by color depending on their known/unknown status on book item screen.
Wintiles-3950.

**Comment by Zireael07** [comment]
Can confirm. Thought it was just me.

**Comment by chaosvolt** [comment]
And to confirm and post on the older issue...

![der grau ening](https://cloud.githubusercontent.com/assets/11582235/11459822/2ef4a9d8-96a5-11e5-9f73-49a50d17875e.png)

Add that to the list of problems to be dealt with. -_-
