### ISSUE TITLE
Stacking tanning pelts unifies time left

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14181]
Craft tanning pelts, drop them on tile X.
Wait for them to get ready.
Craft some more tanning pelts.
Read "pelts will be ready in a few days".
Drop new pelts on tile X.
They are now all ready. You can activate them all. Tanning time remaining is unified based on the lowest value in a stack.

Tried that with fermenting sauerkraut. Didn't seem to work. It will stack, game will display "it's ready" for a whole bunch, but activating them one by one will eventually lead to those not ready and everything will work as expected.

Wintiles-3950, seen that happen for awhile before that.

**Comment by Oskar636** [comment]
This isn't an issue anymore. What happens is the pelt/hide that is ready gets thrown "on top of the stack" and it activates it first. 
Build 5864 windows 64bit tiles
