### ISSUE TITLE
The Wiki is totally broken...

### ISSUE THREAD

**Issue by i2amroy** [CleverRaven/Cataclysm-DDA#14194]
and has apparently been that way for a couple of weeks now. It's throwing up compilation error messages randomly throughout. Can we contact whoever is responsible for handling this to get it fixed? Or barring an ability to contact them possibly look into a new hosting location or something where we can get to it to fix it?

I mean the wiki has never exactly been up to date all of the way, but a lot of people still use it, and having large pages of error codes show up on something that comes up right along with the main site when new players are looking for our game does not do much to inspire confidence.

**Comment by sparr** [comment]
feedback on IRC is that the wiki is moving to a new host and this is a problem pending that move to fix

**Comment by remyroy** [comment]
It might be fixed today! Cross your fingers.

**Comment by i2amroy** [comment]
>feedback on IRC is that the wiki is moving to a new host and this is a problem pending that move to fix

Good to hear.

**Comment by kevingranade** [comment]
Fixed, thanks @remyroy @drbig and @GlyphGryph
