### ISSUE TITLE
Putting JQ scripts in repo, merits and organization?

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14205]
I would like to add a collection of jq scripts to the repository to make it easier to parse out certain types of information from the json files. 

Here is an example of one such script, which summarizes data about all the armor in the game: https://gist.github.com/sparr/3d065bd7cca1edb760f2

Is it a good idea to include things like this in the repo?

Could we use these to enhance doxygen documentation later?

Where should these scripts live, and how should they be internally documented? As indicated by the comments in my example, I'm currently considering putting them in a subdirectory of data/json/

Should there be cross referencing comments in the main source indicating where some calculation is duplicated in a jq script, to avoid the scripts becoming obsolete?

**Comment by kevingranade** [comment]
I don't see any reason not to include them, there are already a number of json querying tools in the tools/json_tools/ folder.

Enhancing doxygen sounds reasonable-ish, except I'm a little wary of adding more dependencies to the build process.

tools/json_tools/some_subdir would be my suggestion, documentation in docs/

Cross referencing sounds like something worth trying, but the real question is whether either users or build scripts use them enough to keep them in sync.

**Comment by illi-kun** [comment]
> documentation in docs/

This is very important part of Kevin's message.

It seems that your scripts allow us to gather and handle big amount of data and that's very good but please give a clue to community how to run it (write at least brief info required for running such scripts into some documentation file).

**Comment by sparr** [comment]
I don't have much to say in the way of documentation yet. The description and usage comment at the top of each file is pretty much all I'd say in any doc, and duplicating that seems pointless.

If you want to run the script you can use the command in the second comment at the top of each script.
