### ISSUE TITLE
Tailor's kit: reduce advantages and disadvantages for low-ENC items

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#14204]
![tactical socks](https://cloud.githubusercontent.com/assets/11582235/11446946/4b1737f4-9504-11e5-96d4-6dc78b18307d.png)

This is a suggestion I made ages ago while discussing a PR someone else attempted (https://github.com/CleverRaven/Cataclysm-DDA/pull/13344).

Basically, most low-encumbrance items receive a massive penalty to encumbrance when padded with leather or kevlar. I interpreted this as implying the survivor is adding as much material as the item could feasibly support, instead of only as much as is comfortable.

If encumbrance affected both the protection gained as well as the encumbrance increase, it would make the option more tempting while still retaining a measure of balance. Essentially, nerfing enhancement of low-encumbrance item by approaching it from the opposite direction.

However, as the discussion in said PR demonstrates, we need concrete math and coding for how to handle this, in addition to someone able to implement without the source code imploding, which is how it'd likely go if I attempted it. :V

**Comment by karlnp** [comment]
I want to help. Hopefully I'll be able to.

**Comment by chaosvolt** [comment]
Ah, would be helpful, yes. ^^"

**Comment by chaosvolt** [comment]
I'm going to assume this was closed due to the drama between Kevin and I, and not actually fixed.

**Comment by Coolthulhu** [comment]
Formulas were rebalanced significantly. It's fixed for majority of items.

**Comment by chaosvolt** [comment]
Ah. It took some searching before finding your PR that effectively fixed this, because this issue wasn't linked from it. >.>
