### ISSUE TITLE
Inconsistant keybinding

### ISSUE THREAD

**Issue by floriandutheil** [CleverRaven/Cataclysm-DDA#14209]
In character creation menu, the keybinding is inconsistant:
- in every tab except 'skills', pageUp/pageDown change tab.
- in the 'skills' tab, it makes scroll the skill description.
Note that it doesn't scroll the starting profession description.

What do you think the keybinding scheme should be here?

**Comment by remyroy** [comment]
What do you think @OzoneH3 ?. I believe part of this inconstancy comes from #14102 .

**Comment by OzoneH3** [comment]
I think that page up/down shouldn't even be a thing to change tabs in any window whatsoever.

Like <,> and TAB, BACKTAB isn't enough for that. Page up/down should be used for pagescrolling not tabbing. Probably shoud just remove it from the default tab keybindings.

**Comment by floriandutheil** [comment]
Yes, that seems to be the sensible option. In addition, we should makes pageUp/down to scroll the description of the starter professions

**Comment by CIB** [comment]
I would like to note that last I checked, on the German Keyboard layout, the < > keys don't work with CDDA. Let me check that again..

**Comment by OzoneH3** [comment]
They work with a german keyboard, always used those to tab.

**Comment by CIB** [comment]
Yeah, it works just fine in both tiles and curses mode. But the person who originally discovered this couldn't use < > for some reason, not sure why.
