### ISSUE TITLE
Time fast-forward speed issues

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14214]
Fast-forwarding time seems to be highly variable.
When you craft, you get 5-minute ticks at average speed.
When you disassemble, you (since only recently, I believe) get 5-minute ticks at much faster speed.
When you sleep, you get 30-minute ticks at average speed.

This leads me to question: how do these pauses between ticks work?
If Cata tries to do them at maximum possible speed, then we have optimization problem (crafting vs disassembly).
If Cata has these pauses' length defined somewhere, then it would be great if players could tweak these values. If possible, in options menu. If you do many short actions in potentially dangerous places (like repairing vehicles in town), you may want average speed to be able to stop in time. If you spend day and night in your remote base crafting 9-hour katanas and then sleeping, you absolutely would trade faster fast-forward for fine control. You have safemode interruptions for that anyway.

Wintiles-3966, WinXP.

**Comment by Coolthulhu** [comment]
Those are just screen refreshes. Only the draw calls and input loop are affected.

The actual underlying logic is identical for crafting and disassembling, with the exception of the very last turn. Pretty sure all the differences in speed here are the result of the environment or different character speed.
In fact, both crafting and disassembling use the default long action handling, which is just counting total moves.

Tweakable pause lengths could be a thing, but it would be really clunky if the player had to go to options to change them or to toggle "long pause" vs "short pause" option like safe mode.
I'd rather see it as a function of time left on the action, by action type or by enemy proximity/existence in field of vision.

**Comment by Nandorianen** [comment]
Can someone test it?
I am crafting an electric forge in my hoarder base with high INT character.
Crafting takes about 2.5 hours with INT bonus.
Disassembling it back takes 2.5 hours.
3 hours of crafting take up 10 seconds of real time.
3 hours of disassembling take up 5 seconds of real time.
I don't think character speed has anything to do with it. And if I understood you correctly, it's not about screen refreshing either.

As for changing pause length mid-game, personally, I'd be glad to have a high-speed option even without the ability to tweak it. I can work around the dangers of imprecise stopping. I can't work around having to wait and watch the grass grow. Clunky controls seem like the least of the issues here.

**Comment by Coolthulhu** [comment]
> I don't think character speed has anything to do with it.

You mean that the speed didn't change during the test or that it did change but didn't affect crafting speed?
Because speed has a clear (linear) effect on crafting time.

Could be just a result of background stuff. For example caching of the overmap (which usually happens shortly after the game starts), saving and (important around large stashes) caching of the crafting inventory.

I don't see anything that could affect the crafting vs. disassembly "real time". They use incredibly similar code that has no place for performance differences - they're both as fast as waiting a set amount of moves.

**Comment by Nandorianen** [comment]
Speed didn't change. Speed would affect in-game crafting/disassembly time anyway, not a real time, but it was identical in both cases.

It is very noticeable and does not change if I try this immediately after game-load or after a few in-game days of gameplay without exiting.

I tried to pinpoint it a little bit better. Did some cleaner tests. I tried crafting, disassembling and waiting. Speed 100, no mood changes, no speed changes, nothing. 3 hours exactly.
I tried that in the middle of my base, few screens away from base and very far away in the middle of nowhere. Tried that without debug mutations, and with hammerspace, hvac and life support mutations enabled.

Inside base, regardless of mutations:
crafting 11.5s, uncrafting 4.5s.
Outside base, without mutations or with hammerspace only:
crafting 11.5s, uncrafting 4.5s.
Outside base, all 3 mutations enabled:
crafting 10s, uncrafting 4s.
Far from base, without mutations or with hammerspace only:
crafting 11s, uncrafting 4s.
Far from base, all 3 mutations enabled:
crafting 9.5s, uncrafting 3s.

Waiting time in all case was consistent with crafting time (equal, as far as I can tell).
Out of 3 mutations hvac seems to be affecting results the most.

**Comment by Coolthulhu** [comment]
OK, I just tried it and it indeed does happen much faster. The crafting time is comparable to waiting, while disassembly time ticks like mad, as if disassembly skipped some waiting time somehow.

I have no idea what could be causing it. The code handles both of them in the same way.
