### ISSUE TITLE
Unused flags in monsters.json

### ISSUE THREAD

**Issue by illi-kun** [CleverRaven/Cataclysm-DDA#14211]
Some flags in ```monsters.json``` have no coded effects, namely ```WOOL``` (sheep) and ```SMALL_BITES``` (some vermin).  It's possible to just remove these flags but maybe anyone wants to implement them, or at least have any good ideas how to use them?

Decent place for handling of ```WOOL``` flag is function ```activity_handlers::butcher_finish``` (in the same manner it's done for fur, leather, and feathers) but we need to add new item ("raw" wool) and way to process it to something useful.

Concerning ```SMALL_BITES```, I see no easy way of using it and prefer to just wipe it out.

Both flags were introduced in #3837 (two years ago).

**Comment by illi-kun** [comment]
I didn't notice this before but we have yarn in the game (see #9854), so making 'wool' flag workable is easier than I expected.

**Comment by chaosvolt** [comment]
Will be nice to see the wool get used, yes.

Any way to make small_bites do anything? Logically it should set damage to zero without negating the pain said attack should cause. HOW to implement that, I have no idea.

**Comment by illi-kun** [comment]
What such implementation of ```small_bites``` will give to player except annoyance?

**Comment by illi-kun** [comment]
Initial implementation of wool processing is introduced. Discussion about "small_bites" migrates to #14225.
