### ISSUE TITLE
Additional clothing reduces warmth - related to injury or layering?

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#14213]
Linux, tiles, gf9fe75b

I have a character with badly injured legs, and (presumably due to the injury) the legs are very cold. Adding extra clothing increases warmth to a limited extent, but some items seem to have a negative impact on warmth.

To repeat, load this save:

https://www.sendspace.com/file/jzws7w

and put on the leg warmers in the character's inventory. Leg warmth will drop from -28 to -41, instead of rising.

**Comment by illi-kun** [comment]
Thank you for save file, it really helps. I understood the reason of this issue and will try to implement bugfix.

**Comment by illi-kun** [comment]
Damn, I used incorrect magic git word and this issue isn't closed automatically. PR #14241 fixed this issue, so it should be closed.
