### ISSUE TITLE
Mod: No Powered Armor is in incorrect category under mods list.

### ISSUE THREAD

**Issue by etmoonshade** [CleverRaven/Cataclysm-DDA#14210]
Exactly what it says on the tin. It shows up under "default" rather than "balance."

Windows Tiles, 0.C-3966, x64

**Comment by chaosvolt** [comment]
Specifically it gets the "no category" sub-category that implies it lacks a category definition.

Technically it should be under the blacklist section, not balance.

**Comment by Night-Pryanik** [comment]
Should be closed after #14220?
