### ISSUE TITLE
Recharging bionic power with vehicle station?

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14228]
Found one thread with a similar idea. DIdn't find anything here.
http://smf.cataclysmdda.com/index.php?topic=10297.0

Right now player's bionic power can come from renewable sources (moving around, staying in sunlight) or from weird hacky stuff like eating conventional batteries en masse, drinking alcohol or burning stuff. Yeah, and an unsafe plutonium reactor. It's all fun and interesting, but it doesn't seem like a way pre-cataclysm cyborgs would get their power. You have proper ways to get it efficiently - using electricity that is omnipresent in any city.

If you are a military cyborg, you sure as hell shouldn't rely on sunny weather, running around or drinking a bucket of vodka to get you going after you leave your base. It's the opposite - you are, most likely, being used for short action-intense tasks that require you to spend lots of power you have to store beforehand. So power should come while you rest, like your physical body strength.

For player it's the other way around right now: you can only recharge power when you are doing something actively, and you lose power if you stay indoors immobile with any sustained bionics active or just listening to an mp3 player via an integrated UPS.

It should not be like this. Power shortage should be inversely proportional to your mobility and distance from stationary centers of power generation and distribution. It would be nice if player had a way to utilize vehicle powerbase. This is as close as we're getting to normal pre-cataclysm power generation and utilities right now.

I'd say it should be a new separate bionic. And possibly a separate vehicle part from current recharging station.
Depending on how you see it balance-wise, several limitations could exist.
- Bionic itself could be rare and uncrafteable or it could be craftable moderately easy.
- Recharging station could also require uncrafteable parts (from labs? military bases?) or it could be craftable somewhere high up the tech tree.
- Recharging process could happen as a side-effect of being in a tile with recharging station, or it could be limited to sleeping in that tile.
- Recharging station's power consumption could be set to high levels so that you have to ensure you have a very good power source for your vehicle.
- Bionic itself could conflict with other ways of getting power. For example, player could be presented with a choice: recharge from vehicle beforehand or have options to get power on a short notice.
- Finally, current power-out-of-nothing bionics could be nerfed from being main means of getting sustainable power to support situational extenders of your power reserves. I think both torsion ratchet and solar panels give unbelievable amounts of power if you compare it to the stuff you do. Repair nanobots is 125 power. That's 25 minutes standing outside in sunny weather. You are more or less a human, you have very little area these panels can cover. Making comparable amounts of power by walking around also doesn't sound too realistic. You're gonna struggle to keep a flashlight powered by dynamo generator for a few minutes, what EMP blasts are we talking about here?

**Comment by Coolthulhu** [comment]
I see it like this:
* Easy to craft bionic (easiest of recharge bionics)
* Easy to craft station (comparable to bionic), maybe even totally optional (could just use the regular recharge station or jumper cables)
* High energy cost of recharging bionic power, 10% effectiveness or something like this
* Moderate recharging speed, 10 per turn or so
* Ability to use the station at range, by attaching a jumper cable to it and holding the other end in the inventory (with lower energy efficiency of course)
* Ability to dump bionic energy back to vehicle at near 100% efficiency (without any refund for the lost 90%, though). This one could always require a jumper cable

**Comment by Nandorianen** [comment]
Interesting idea with jumper cables. So you'll be able to scavenge power in cities and run around your car crafting stuff, while simultaneously being able to juice up any car you want to start. More options is always nice.
Recharging stations should have more efficiency than jumper cables. Maybe specialized recharging station could give even more efficiency / speed?

**Comment by Soyweiser** [comment]
It seems this is implemented now right?

**Comment by Coolthulhu** [comment]
Pretty much

**Comment by Soyweiser** [comment]
I liked the military cyborg idea. Should be added to a few cyborg starts then (perhaps they already have, ignore this then). However, you do have the problem of getting jumper cables. And don't know if military personal should start with one of those.
