### ISSUE TITLE
color coding broke book recipe highlighting

### ISSUE THREAD

**Issue by MehMuffin** [CleverRaven/Cataclysm-DDA#14232]
Something in the new color-coded item descriptions seems to have changed whatever it was before that dulled out known recipes in books--now the whole section is gray, instead of only unknown recipes, so there's no easy way to tell what you have left to learn from a book.

**Comment by chaosvolt** [comment]
Posting to confirm:

![der grau ening](https://cloud.githubusercontent.com/assets/11582235/11459822/2ef4a9d8-96a5-11e5-9f73-49a50d17875e.png)

Add that to the list of problems to be dealt with. -_-

**Comment by BevapDin** [comment]
Isn't this the same as #14188?

**Comment by chaosvolt** [comment]
Oh derp. My fault, saw this one first. @_@
