### ISSUE TITLE
many monster special attacks print nothing on a successful uncanny dodge

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14238]
In monattack.cpp there are many attacks which can be dodged normally, and more that can be uncannily dodged. Some of them print something for one or both types of dodges. Many of them simply allow the attack to silently miss, with no indication to the player that they were attacked and dodged.

**Comment by drbig** [comment]
I think I've seen something else also regarding special attacks and messages...

**Comment by mugling** [comment]
Closed as unconfirmed
