### ISSUE TITLE
Bionics asking for target should hide bionics screen

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14247]
EMP, fingerpick and mini-flamethrower, for example, ask you to choose nearby tile to use them on. But they do not hide installed bionics window, so you have choose blindly or remember the direction.
Mild inconvenience, but it should work like far targeting (for example, for finger-mounted laser).
Wintiles-3978, in case it's not a universal thing.

**Comment by scorpion451** [comment]
Also seeing this in wintiles build. Very annoying.

**Comment by drbig** [comment]
It did hide it when I was adding the "looped bionics menu" :|
