### ISSUE TITLE
Page Up/Down doesn't work at some places!

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#14257]
^As the title say - The places I have discovered so far:

* Crafting menu
* Third tab of character creation

**Comment by remyroy** [comment]
This is probably partially a duplicate of #14209.

**Comment by drbig** [comment]
It is. Also the last effort of making the UI consistent died of natural causes.

**Comment by OzoneH3** [comment]
Fixed with #14256

**Comment by harald921** [comment]
@OzoneH3 How is removing something "fixing"? That's like shooting your sick pet with a rifle and saying you cured it..
