### ISSUE TITLE
Harvesting blueberry bushes produces -1 count items

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#14252]
8cd25f454aed187c8abab9d8fb0e29ff1f752f3a :

![negative-blueberries](https://cloud.githubusercontent.com/assets/3055062/11480173/e4ce45fa-978d-11e5-9a84-f3e2e6a6dbae.png)

**Comment by mutability** [comment]
Actually, this looks like a much more widespread problem, with tainted bones/meat also showing up as -1.

**Comment by mutability** [comment]
Might be 9fb4ff5349a9272ef4030500a85d8da52383d4fe

**Comment by drbig** [comment]
First reported in #14248.
