### ISSUE TITLE
modded items used in crafting do not return mods, but cannot be filtered out

### ISSUE THREAD

**Issue by scorpion451** [CleverRaven/Cataclysm-DDA#14271]
Another user in the forums reminded me about a long-standing quirk in the crafting system I've been meaning to make a ticket for:

When I go to craft an item that requires, say, a UPS as one of its components, I am asked whether I want to use a UPS in my inventory, or one nearby. What I am not asked is whether I want to use one of the fully charged rechargeable UPS's in my inventory and recharging station, or or one of the unmodded ones that I have laying around. If the game should happen to find and use a rechargeable UPS, I don't get that rechargeable battery mod back. This is somewhat annoying.

I'd suggest at least one of the following, preferably both:
- modded and/or charged items should be listed separately from empty and unmodded items when crafting
- If a modded item is used for crafting, the mod should be removed and returned, same as with batteries. If this cannot be done, then do not show modded items on the list of available components for crafting.

**Comment by drbig** [comment]
And this looks similar to "let me select precise item when building a vehicle".

**Comment by kevingranade** [comment]
Does this still happen? It's a pretty painful bug if so.
