### ISSUE TITLE
Keybinding window missing redraw

### ISSUE THREAD

**Issue by lekto** [CleverRaven/Cataclysm-DDA#14270]
1. Press '@'
2. Press '?'
3. Press 'Esc'
4. Now you have black square in the middle of the screen.

**Comment by drbig** [comment]
I assume it disappears the moment you move?

**Comment by lekto** [comment]
It disappears when I get out of player info (press 'Esc' again).

**Comment by drbig** [comment]
Hmm, curses. I'd say it's a bug then.

**Comment by lekto** [comment]
It happens in ncurses (bash) and also SDL2.

**Comment by drbig** [comment]
Then it might be also that long-term topic about sdl/ncurses, *-buffering and redraws.

**Comment by Sir-Kernicus** [comment]
If you press esc it goes away then you can press @ again

**Comment by mugling** [comment]
Have seen in recent `master`

**Comment by Leland** [comment]
#19233 notes that the <kbd>V</kbd> keybinding window has the same issue.

To replicate, press V, then press ?, then press Esc.

Can confirm both that and the issue here still exist.

**Comment by Leland** [comment]
Duplicate of #8514
