### ISSUE TITLE
DEBUG: Missing Item UPS

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#14290]
AFAIK the only mention of a "UPS" item id is as ammo for laser weapons, which obviously don't shoot UPSes but rather use UPS charge. But I believe NPCs armed with LACP pistols are causing this, possibly by trying to reload it with a nonexistent ammo. Seems like it might also be caused by opening trade with an NPC while having an LACP pistol in your inventory.

**Comment by remyroy** [comment]
Check out [http://www.chiark.greenend.org.uk/~sgtatham/bugs.html](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) and help us help you.

**Comment by ejseto** [comment]
Gee, "show me how to show myself?" I thought that's exactly what I did. Get an LACP pistol, open trade. Spare me your patronizing and read it next time.

**Comment by mugling** [comment]
I've made some recent changes to the handling of weapons that use UPS instead of ammo. It would be interesting to know if you have since encountered this issue @ejseto?

**Comment by ejseto** [comment]
It's still happening, although now the message just says "DEBUG: Missing item (check item_groups.json)". The game then creates an entry in the artifacts.gsav file with a blank id "" and name "undefined-s".

**Comment by mugling** [comment]
The ammo theory is certainly a possibility. I'll look into it.

**Comment by ejseto** [comment]
This can be fixed by modifying item::find_type() to return nullptr if type == "", though I don't know if this has any adverse effects.

**Comment by mugling** [comment]
Not sure if this still exists. Can be reopened if reproducible in any recent version of `master`
