### ISSUE TITLE
Add the ability to manipulate the position of enemy monsters through a "push" command

### ISSUE THREAD

**Issue by GlyphGryph** [CleverRaven/Cataclysm-DDA#1429]
Add the ability for a player to "push" adjacent monsters. 

The player then selects the monster they wish to push. At lower levels, this immediately begins the action, to push the monster a space away from the player.

On success: "You shove the _monster_ back." or a variant thereof.

A pushed monster will immediately be moved one space, and has a chance of being knocked down depending on the success of the push and the mskill of the monster.

The success of the push should be based on the characters unarmed skill (a basic to-hit unarmed attack) and the difference between the strength of the pushing character and the size of the target (to determine whether or not the push is successful). Pushing a regular zombie should be easy, but a bear or hulk should be far more difficult.

A very successful to hit roll means the player does a kick instead of a push, which usually has the same mechanical effect but does damage. Against smaller enemies such as squirrels, however, this can send the creature multiple tiles. 

On success with damage: "You kick the _monster_ away from you," or a variant thereof.

At higher levels of skill players may choose to WHERE to push the monster to. At lv4, the options are not just straight back, but back diagonally. At lv7, they include the spaces directly to the side of the monster. At lv10, they include all three spaces on the opposite side of the player from the monster. However, the check becomes more difficult for pushes that are not straight back, and more difficult still for pushes to behind the player.

On success with damage, diagonal: "Your spinning kick sends the _monster_ staggering to the side"
On success without damage, diagonal: "You shove the _monster_ out of the way."
On success without damage, reverse: "Ducking to the side, you pull the monster past you, sending it flying."
On success with damage, reverse: "You deliver a devestating roundhouse kick, sending the _monster_ flying past you."

If any push would send the monster into a solid object, it takes damage instead and remains where it is, with the added message tail: "into the _object_, leaving it shaken."

If a push would send it into a trap, the trap is triggered and the tail message is added: "right into the _trap_"

Knowledge of Judo gives a significant bonus to this ability, and gives the player the full push direction options from the getgo.
##

**Comment by Leland** [comment]
We're nearly 4 years out from the last comment here. Closing – if there's still interest by anyone feel free to either let me know you want it reopened here or just create a new issue.
