### ISSUE TITLE
Iaijutsu broken?

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#14297]
Version: 0.C-7918-g744ef80

Using a test character with 20 in all attributes and 11 in all skills, I was unable to get any of the "masterfully draw" text when unsheathing a `diamond katana` from a `scabbard` (by `a`ctivating the latter), nor was there a prompt to select an attack direction when in melee range (adjacent) to a hostile and `a`ctivating the `scabbard`.

**Comment by Griffinhart** [comment]
Issue persists after updating to 0.C-7949-gc1d5f78.

`doc/JSON_FLAGS.md` states that iai draws should be possible with a Cutting skill >7 "and a roll is passed", though I have no idea where this roll is taking place in code.

**Comment by ejseto** [comment]
> I have no idea where this roll is taking place in code.

A project-wide search for the flag "IAIJUTSU" turned up nothing, so I'm guessing the answer is "nowhere." Rather than being broken, it appears to have never been implemented.

**Comment by Griffinhart** [comment]
I know for a fact that iai drawing has been a thing in CDDA, having done it in previous builds.

**Comment by illi-kun** [comment]
It seems that checking of Iaijutsu flag was removed in PR #14052 (unintentionally, I suppose).

**Comment by Griffinhart** [comment]
Looks like it breaks the VORPAL flag as well.

**Comment by mugling** [comment]
> unintentionally, I suppose

Yes. I'll look into that

**Comment by mugling** [comment]
So as discussed in #14306 the concept of iaijutsu drawing is currently a penalty rather than benefit. If a consensus can be reached as to how the feature should work I'll complete it in the PR

**Comment by mugling** [comment]
No consensus reached and the priority at the moment should be balancing holster, scabbard and ammo pouch usage times rather than adding new functionality.
