### ISSUE TITLE
Underground tiles not being revealed on the map properly

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#14309]
Version: 0.C-7949-gc1d5f78

![](http://i.imgur.com/B2KTbbY.jpg)

If you take a look at that map, you'll see that my character is surrounded (on the cardinals) by impassable `solid rock`-type maps, but is standing *in* an `unexplored` map. (It's the downstairs part of a `strange grove`; I don't know what it's actually called because, well, of this bug.)

The `solid rock` map tiles were being revealed as I wandered around in the current map tile; as I got far enough in a cardinal direction (but obviously not leaving the current tile), the adjacent tile was revealed.

I've been suspecting this was happening for a while, but didn't have a good way to confirm it until I found now. Previously I was noticing that underground `lab` tiles were being revealed even though my character wasn't actually in those tiles, but wasn't sure it was a bug.

If it matters (and I suspect it does), I'm using z-levels.

**Comment by Zireael07** [comment]
I'm not using z-levels and I'm sure I was standing in an unexplored map at least once when wandering the sewers.

**Comment by sparr** [comment]
the reveal of the neighboring tiles is due to a patch I submitted many months ago, which reveals a tile if you can see enough of it.

your current tile not being revealed... I have no idea what would cause that bug.

**Comment by DanmakuDan** [comment]
Maybe somewhat related, on the main z-level, when wandering around with at night the night vision trait (11x11 vision area), some overmap tiles are being revealed when moving onto the submap before that overmap tile (12 spaces away before the player is actually on the next overmap tile).

**Comment by sparr** [comment]
An overmap tile is revealed as soon as the player can see 36 tiles in a submap in that tile. So yes, you will often reveal an OMT while you are not in it yet.

**Comment by DanmakuDan** [comment]
The behavior I get is more like
```
ab
cd

ef
gh
```
The overmap tile containing efgh is revealed when I cross from submap a to c, but I only have a vision radius of 5 tiles at night without any extra light while using night vision. It feels like the math is off by one submap whenever you cross between submaps.

**Comment by DanmakuDan** [comment]
I think what is happening is that since the player remains in the (5,5) local space submap, crossing the submap border places you in the next submap, then applies the overmap view update which shifts the local submap location back to center, causing the wrong overmap tile to be revealed when you cross the border.

For example, moving east from local submap (5,5) to (6,5) causes the game to shift all submaps west; (6,5) becomes the new (5,5), but (6,5) is still applied as the overmap view update, which is actually pointing at (7,5).

**Comment by DanmakuDan** [comment]
This should be fixed already by #14631.

**Comment by Night-Pryanik** [comment]
Should be closed then?

**Comment by DanmakuDan** [comment]
Yes.

**Comment by BevapDin** [comment]
Fixed by the linked PR.
