### ISSUE TITLE
High latency due to dividing blobs

### ISSUE THREAD

**Issue by dodzy** [CleverRaven/Cataclysm-DDA#14308]
Day 2.
There is a slime pit nearby, but yeah the game is pretty much unplayable due to the number of blobs.

0.C-7949-gc1d5f78 ( http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/cataclysmdda-0.C-3993.zip )
Windows 7 64 bit

link to savefile:
https://drive.google.com/file/d/0ByEVAW7ALsCxRVNUd2xVbXdLUkE/view?usp=sharing

**Comment by stk2008** [comment]
Ahh i thought this was fixed..
i had same issue a while back.

**Comment by Zireael07** [comment]
There were ideas being kicked around (don't generate blobs if their total number is over x or give split ability only to large ones) but they were never implemented. I can't find the issue though as the title didn't mention blobs specifically.

**Comment by Griffinhart** [comment]
Possible duplicate of #14068.

**Comment by Coolthulhu** [comment]
Blobs no longer multiply indefinitely. They can still reach high numbers, but can no longer nuke a map like before.

Still, a horde of blobs and a small group of anything blobs are hostile to could cause a performance problem.
