### ISSUE TITLE
Blood Filter can purge hallucinations debuff

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#14310]
Version: 0.C-7949-gc1d5f78
1. Stepped into a `shimmering portal`.
2. A few turns later, I had `a sudden nostalgic feeling.`
3. Used the Blood Analysis CBM, saw I had `hallucinations`.
4. Used the Blood Filter CBM.
5. Used the Blood Analysis CBM again, saw I had `No effects.`

The Blood Filter CBM description says that it "allows you to filter out chemical impurities" and will "have limited impact on viruses", but I don't think spoopy-induced hallucinations fall into either of those categories.

**Comment by kevingranade** [comment]
Huh, semi-intended, but I agree this is wrong.
We'll need to add a "non-chemical" hallucination effect that doesn't get
purified.
A nice to have would be a "bloodborne" effect tag that signals whether
those CBMs work on them.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
