### ISSUE TITLE
Feature request: match vehicle door-toggling interface to engine selection interface

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#14311]
`door motor`s can be attached to `curtain`s, so the door-toggling option of vehicle controls lets you open/close curtains remotely, which is awesome.

What's not awesome is that you have to open the vehicle controls each time you want to open/close a curtain, because the door-toggling interface closes as soon as a door/curtain is selected. This isn't too bad if you have only one curtain, but it becomes more and more tedious as your curtain count increases. (Specifically, it takes 3 keypresses per curtain - 1 to open the vehicle menu, 1 to select the door-toggling interface, and 1 more to select the curtain.)

The engine selection (as well as turret toggling) interfaces let you toggle multiple engines (and turrets, respectively) at once, which is _significantly_ more convenient.

**Comment by Leland** [comment]
Old suggestion and no recent discussion here. Closing. Feel free to let me know if you want it reopened.

**Comment by mlangsdorf** [comment]
Dead issue, but fixed by #24256
