### ISSUE TITLE
Eating from vehicle storage can show invalid hotkey assignment for item

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14321]
I have an item in my vehicle's storage compartment that had a hotkey ("j") assigned when it was in my inventory. When I press "E" to eat, the item is still listed as having that hotkey. However, pressing that hotkey actually tries to eat the current "j" item in my inventory.

**Comment by remyroy** [comment]
Do you have a save file or some way to reproduce this easily?

**Comment by sparr** [comment]
Reproduction is easy. Drop 11 food items into a vehicle. Open the E dialog, see the 11th one has its old hotkey (instead of the 0-9 hotkeys assigned to the first vehicle/nearby slots). Open your inventory, choose another item, reassign it to that hotkey. Reopen E dialog, see that 11th item still showing that hotkey.

Now that I've done this in curses mode I can see that the hotkey is highlighted in yellow if there's a conflict. I don't think that highlight is visible in tiles mode, nor do I think it's sufficient in curses mode.

**Comment by remyroy** [comment]
I can confirm this is a bug.
