### ISSUE TITLE
Enclosed "In" tiles on vehicles don't block ambient light.

### ISSUE THREAD

**Issue by etmoonshade** [CleverRaven/Cataclysm-DDA#14329]
Example setup: https://dl.dropboxusercontent.com/u/22571912/Pics/Games/DDA/BrightIndoorRV.PNG

Pretty simple. Space enclosed by boards and entirely roofed over, aisles on the floor (same results if I replace the bed with an aisle, by the way,) and the sun wakes me up every morning.

The expected behavior is that I'd have a dark sleeping room. It works fine to block the aisle lights to the south, but sunlight pours in.

You can reproduce this with a far simpler setup - 3x3 vehicle, boards, door, roof everything over.

**Comment by etmoonshade** [comment]
This is still happening in 0.C-4321.

**Comment by Oskar636** [comment]
#17561 is essentially the same.

**Comment by Leland** [comment]
Closing in favor of #11621
