### ISSUE TITLE
Debug mapgen does not redraw soon enough in tiles mode

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14333]
When using the mapgen debug function, in ascii mode you can see the proposed new generated map and either [1]Regenerate or [3]Apply it. In tiles mode, you can't see it until you apply it.

**Comment by remyroy** [comment]
What are the steps to reproduce this? What do you observe exactly at which step and what do you expect?

**Comment by sparr** [comment]
press ` for debug menu
press g for map editor
press o for overmap editor
scroll down to some overmap in the top right list
press enter

at this point in ascii mode you can see the newly mapgenned omt on screen. in tiles mode you can't.

press 1 to regenerate the map

at this point in ascii mode you can see the newly mapgenned omt on screen. in tiles mode you can't.

press 3 to apply the changes

at this point both modes show the new map, as it's now part of the world.

**Comment by remyroy** [comment]
I can confirm this is a bug.

**Comment by Night-Pryanik** [comment]
Cannot confirm on latest experimental as of September 27, 2019. All is working as expected. It seems that #33619 fixed this issue.
