### ISSUE TITLE
Add sub-type to overmap terrains, discovered on seeing them

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14339]
Right now you get the same amount of info from walking into an OMT as you do seeing it from a mile away. All 9 tiles of M are still just "mansion". What if each mapgen could give itself a more detailed name, which would replace the base name once you've explored the map? So once you've been inside a hospital, you can see later on your map where the pharmacy was, etc. "mansion" would clarify to "mansion library" or "mansion dining hall" or "mansion pool" etc.

**Comment by Zireael07** [comment]
Great idea!

**Comment by kevingranade** [comment]
This could also give some info like, "prepper house" or "large family
house" instead of generic house.
Sounds intetesting.

**Comment by sparr** [comment]
Where should this info live, in terms of the game's data structures? A vector of 32400 strings attached to the overmap doesn't necessarily seem ideal. Is there some struct that represents one OMT (four submaps) that this info could be attached to at mapgen time?

**Comment by sparr** [comment]
I'm going to start by adding `std::unordered_map<std::pair<int,int>, std::string> terrain_closeup_name;` to `map_layer`, with the idea that the vast majority of tiles won't have a sub-type / closeup-name. Moving this info somewhere else shouldn't be too hard if kevin or bevapdin or coolthulu point me another direction later.

**Comment by Coolthulhu** [comment]
The idea sounds good. `map_layer` looks like a proper place to put this info.
Use `point` rather than `pair<int, int>`.

Would be nice (though not necessary) if instead of storing the name as "Prepper house" you stored its id, which would be used to look up the proper name. That would mirror what is happening with regular `oter_id`s more closely and also be more portable.
Just saving the name would work, but could stop working (or at least look weird) in some weird cases.

**Comment by sparr** [comment]
a `point` makes sense.

Storing an ID could work. When a new name is generated, I could push it into [some structure X]. This would require X being indexable, for turning IDs back into names, and referencable by name. I'm not sure if there's a STL type that does both of those in O(1).

**Comment by sparr** [comment]
move further comment to the PR, please. especially if you can help me figure out something I've done wrong there.

**Comment by kevingranade** [comment]
Since it's only going to be use internally, it could just be stored as a
pointer until a table of terrain types, much like the system that monsters
and items use. Look up "flyweight pattern" for details.
