### ISSUE TITLE
[Bug] Inaccessible basement in house.

### ISSUE THREAD

**Issue by Totentag** [CleverRaven/Cataclysm-DDA#14332]
So, after mentioning this issue on IRC, and dicking around in the debug to make sure it was actually a bug, a couple users said I ought to submit this as an issue here. This is my first experience with GitHub, so expect things to be messy. 

Bug is as follows. Day one, I'm exploring the local town in search of starting supplies. I happen across this solitary house, loot it, and keep getting interrupted by WHUMP! noises underneath me. Finally, after gearing up nicely, I start smashing and moving furniture in hopes of finding the hidden staircase to the basement. When this fails, I go to the IRC and learn how to abuse the debug menu in oh so many ways. First, I reveal the map and confirm there is a basement. Then, I Long-Range Teleport my way INTO the basement, and follow the staircase up. This spawns me on the floor, next to an interior wall. I then Wish myself a sledgehammer and tear down all the walls near where I spawned, all to no avail. It appears there is simply no ground-level entrance into this basement. 

Relavent information:
OS:                          Windows 7 64 Bit
CDDA Version:        Tiles #4002
Save:                       https://www.dropbox.com/s/gk5h1b83hf8xegn/Wilsons%20Mills.rar?dl=0
IRC Conversation:   http://pastebin.com/TDNe48V2

The save file contains only one character, and that character should spawn in the bedroom of the house in question. This is before any debugging has occurred, and only basic searching for the staircase.

**Comment by BevapDin** [comment]
> I start smashing and moving furniture in hopes of finding the hidden staircase to the basement. When this fails,

Stairs are terrain, as are walls and floor and each tile can have only one terrain. If the tile is floor or wall, there can not be stairs there, so you only have to check the places where you can't see the terrain. The look around command shows the terrain and the furniture and that's enough to find the stairs, no destruction of anything needed at all.

**Comment by Totentag** [comment]
>...no destruction of anything needed at all.

There's nothing wrong with a bit of thoroughness. ;D 

Considering all other options had been exhausted, I see no reason I shouldn't have experimented with other possibilities before declaring there was literally no staircase.
