### ISSUE TITLE
[Suggestion] Add recipes for eggnog

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#14331]
'Tis the season, and while nursing a quart of the stuff, it occurred to me that the game doesn't seem to have that most iconic of Christmas drinks: eggnog! It's filling, tastes good cold or warm, can be used in other recipes, and (possibly most importantly) can be alcoholic or non-alcoholic. Alcoholic keeps for much longer, but I doubt you need to worry about making batches of non-alcoholic large enough to start going bad before you're done with it. You can always make more! The recipe is simple: Eggs, sugar, milk, and heavy cream, liquor optional. (Do we have cream in? We really should.) Can link a recipe for suggested proportions if desired.

**Comment by sparr** [comment]
This is the sort of thing that seems very likely to be accepted if you submit a pull request with a few new recipes.

**Comment by railmonkey** [comment]
Heh. Exactly the sort of thing I'm still trying to work out. I can edit jsons just fine. It's pushing them that I have trouble with. I'll see what I can do, though.

**Comment by Griffinhart** [comment]
Here's how I do it.

Setup:
[Properly fork the CDDA repo.](https://help.github.com/articles/fork-a-repo/)

Making and committing and PRing changes:
1. `git branch new-feature`
2. `git checkout new-feature`
3. [Make your changes]
4. `git status` lists all the changes you've made.
5. `git add <file>` stages the file for committing.
6. `git commit -m="Implemented a new feature!"` actually commits the changes (the message should be changed to something relevant)
7. `git push origin new-feature` pushes your changes to *your* repository.
8. Go to your GitHub repo and submit a PR through there.

Mind you, I (try to) work exclusively in a terminal. I have no idea how any git GUIs work.

**Comment by Zireael07** [comment]
For Git UI, I recommend SourceTree.

**Comment by Nymall** [comment]
Sourcetree is nice. Git GUI is also a relatively nice feature. You have to set your upstream\master branch yourself, but it remembers the settings. It's nice for a tabular view of everything your working on. I also really enjoy working with TortiseGit, though it has some definite quirks.

**Comment by railmonkey** [comment]
Okay, awesome. After dealing with life, and with some dithering, I'm all set up. Now, aside from the recipes, I also want them to be spawned and dropped. What files will I be sticking my nose into?

**Comment by sparr** [comment]
you need to add an eggnog item. and a recipe to make it. and you want to add that item to some item groups, so it will randomly spawn in the right places. I can't remember which file the item groups are in, but they shouldn't be hard to find.

**Comment by Coolthulhu** [comment]
data/item_groups.json

**Comment by railmonkey** [comment]
Ah, thank you. I'll go ahead and tackle that in a bit, then. In the meantime, now that I actually know how to do it, I'll get Git broken in with a few other PRs.

**Comment by railmonkey** [comment]
How do item weights work again? Percent chance to spawn? I was thinking of giving it a weight of 35.

**Comment by Coolthulhu** [comment]
35 is a lot. It would make it almost as common as canned beans.
Something like 1, 2 or 3 would be much more like real life.

**Comment by railmonkey** [comment]
Ah. Was using milk as a measuring stick. I think 2 will work, then. Now... Once I have a recipe for it (possibly with recipes that use it) and define it in item_groups.json, where else do I have to define it?

**Comment by Coolthulhu** [comment]
The actual item definition in data/json/items/comestibles.json
Once it's in items/comestibles.json, recipes/recipe_food.json and item_groups.json it should be both craftable and spawning randomly.

**Comment by railmonkey** [comment]
Perfect, thank you. So, for spoilage, what measure is used? Days?

**Comment by Coolthulhu** [comment]
As far as I recall it's days at some reference temperature near room temperature.
It will rot faster than that in summer and slower in winter.

**Comment by railmonkey** [comment]
I see. Well, I was looking, and I noticed that alcoholic drinks in general don't spoil, so really, it's just the regular stuff that I need to worry about. I'm going off of regular milk for that. I'll need some help getting the recipes right. Going to open a WIP pull request.

**Comment by mugling** [comment]
Was added in #14382
