### ISSUE TITLE
dropping items due to over-volume inside a vehicle drops to the ground instead of the vehicle

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14346]
This really doesn't make sense. If I take off my backpack while driving, the items should fall off inside the car. When I'm prompted to drop the backpack, it should also end up in the car.

**Comment by Coolthulhu** [comment]
There is no good way of handling vehicle overload right now. There is no mechanic for handling "stray" items in vehicles.
Marking as suggestion because I don't see how could this be fixed properly.

**Comment by narc0tiq** [comment]
If I read it correctly, it's not the vehicle that's overloaded but the player.

**Comment by kevingranade** [comment]
Coolthulu's point is that if the vehicle becomes overloaded by the dropped
item, we don't have a way to handle it.

**Comment by sparr** [comment]
When using the AIM to "move all" to a vehicle tile, overflow ends up on the ground in that tile. Is that functionality not generally appropriate/available for such a situation?

**Comment by Headjack** [comment]
The point is that items which can't fit somewhere end up outside the car, and will be driven away from. However, there's no way to model having extra items kicking around on the floor of the vehicle, so they just fall out. It's wonky, but can't really be changed without serious reworking of vehicles.
