### ISSUE TITLE
regression: adv inv handling of containers on the ground no longer works

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#14355]
As at 1cf825189dec9cc1cd2399b0d1da89da538b8c8f, trying to access the contents of a container on the ground from advanced inventory via 'c' always fails, producing an "invalid container" pane. This worked previously.

I suspect 33a62a6d5316adcd0d27db57bb726eced4234257 / #14299 broke this.

**Comment by sparr** [comment]
I apologize. I'll fix this momentarily.
