### ISSUE TITLE
Vehicle construction cursor disappears without explanation on some map tiles

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14357]
Examine a vehicle and move the cursor outside the vehicle. The blue cursor will disappear seemingly at random. This actually indicates that the tile in question is occupied in the world so can't accommodate any vehicle construction. I think this situation needs more feedback.

**Comment by Leland** [comment]
This issue is over 1.5 years old, and a lot's changed over that time. Closing for now. If anyone is still interested, I can reopen... or feel free to just make a new issue!
