### ISSUE TITLE
Steerable wheels have different sizes from non-steerable ones on mapgen vehicles

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14365]
The old uniform wheel size system only handles wheels of the same exact type. Since steerable wheels are of different type, they get their own sizes that usually isn't the same as the non-steerable ones.

As a result cars generated by mapgen can have front 13" front wheels and 17" back wheels.

**Comment by chaosvolt** [comment]
So basically we've accidentally invented dragster cars. o3o

**Comment by mugling** [comment]
Wheels nolonger have variable sizes
