### ISSUE TITLE
[Bug] Reloading advanced UPS consumes all plutonium in inventory.

### ISSUE THREAD

**Issue by lauriwesterlund** [CleverRaven/Cataclysm-DDA#14363]
Version 0.C-8042-g1cf8251.
Reloading an advanced UPS seems to consume all the plutonium it can find in your inventory, even if you have more than 5. Dropping the extra plutonium on the ground while reloading helps, but isn't really doable in the heat of battle.

The bug doesn't seem to connected to my save file, because I was able to replicate this in a new world, but here's a link to my save file anyway: https://www.dropbox.com/s/tocofgxm63hs0xv/Cataclysm_bug_save.zip?dl=0

**Comment by mugling** [comment]
Confirmed. May relate to #14260. Does the problem exist before b72e25b?

**Comment by illi-kun** [comment]
I found the reason of this bug and working on fix, thanks for save file, it helps.

**Comment by mugling** [comment]
@illi-kun within `item::reload`?

**Comment by illi-kun** [comment]
Yup, L:4178

**Comment by mugling** [comment]
Agreed. You win by minutes, you want to PR or should I?

**Comment by illi-kun** [comment]
Hehe, that's not important, feel free to create a PR.

**Comment by illi-kun** [comment]
@lauriwesterlund thanks for good bug report!
@mugling you PRed pretty smart boolean hack!

**Comment by mugling** [comment]
@illi-kun yes, a C idiom for the ceiling of an integer division
