### ISSUE TITLE
[Bug] debug "reveal map" reveals wrong overmap near corners

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14361]
Standing in OMT 0,0 or 1,1 when I do "reveal map", the overmap northwest of my currrent overmap is revealed. There's probably an off-by-two error somewhere in the coordinate conversion calculations.

**Comment by DanmakuDan** [comment]
I noticed this too when I was looking at the result of the city density thing. The northwest portion of the screen contains the (179, 179) position of the northwest overmap. The abs_sub (absolute submap coordinates) is probably aligned to the northwest corner of the viewable screen (the player's local coordinates are relative to the top left corner of the screen).
