### ISSUE TITLE
[Suggestion] Mapgen city spacing/density

### ISSUE THREAD

**Issue by etmoonshade** [CleverRaven/Cataclysm-DDA#14360]
Ever since I started playing CDDA and discovered the scale of the game, I've had trouble reconciling it with the layout of the overmap. There are a bunch of really tiny "cities" spaced (seemingly) 500m-1km apart, and it seems weird to me.

Per a bit of discussion on IRC, I'd like a way to finagle the mapgen to create one big (like, size 8-12) city per overmap tile rather than the current distribution. Obviously defaults should be exactly as they are now - it's just that options would be nice.

To be honest, this might be rolled into future plans for mapgen in general - more tile types, more customizability, more toys - I just wanted to get this specific one out there though.

**Comment by DeadLeaves** [comment]
Speaking of mapgen, I'd love if there were bigger water areas aswell. Like huge lakes with islands and hunting cabins etc. With the great survival tools mod, making a living in the wilderness is crazy fun, and with some more varied nature it'd be even better. This also ties in with city generation in that cities near water masses should have more fishing and boating related buildings and items.

**Comment by sparr** [comment]
I'm taking a crack at making a city spacing option. I've discovered some very old bugs in mapgen that make the current city spacing entirely unintentional.
