### ISSUE TITLE
"shuffle" : true, does not work in music.json

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#14379]
When making a soundset with music, I noticed that "shuffle" : true, does not work in music.json

If you use this soundset here:

http://chezzo.com/cdda/ChestHole.zip

Every time you open the game, it starts on the same song, and goes through the list from the top.

**Comment by madprogrammi** [comment]
Looks like it just queues the next song to play - there's no shuffling involved. 
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/sdltiles.cpp#L2029 is where the magic happens.
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/sdltiles.cpp#L2044 is where it should shuffle.
