### ISSUE TITLE
New tile drawing code is causing multiple randomization issues

### ISSUE THREAD

**Issue by gbeck** [CleverRaven/Cataclysm-DDA#14375]
Version 0.C-8093-g0b042ff
Mac OS 10.11.1

Somehow the drops are not being randomized. For me, regular zombies are always dropping: leather belt, dress shirt, pair of western boots, and cash card (1592). Tough zombies always dropping: dress, sports jersey, pair of sneakers, and L12 Defender.

**Comment by gbeck** [comment]
The content of the drops seems to differ between saves. Saving and reloading the same game doesn't seem to change the content of the drops.

**Comment by gbeck** [comment]
On further testing, it appears to be a little more complicated. Different zombies do drop different items, but identical drops (including exact content of cash cards, etc.) reoccur very frequently.

**Comment by gbeck** [comment]
I think this is caused by recently added cata_tiles.cpp:1320, which is re-seeding the rng for every displayed map tile. This is also causing other anomalies: bashing furniture either works the first time or never works, escaping from traps never succeeds, and presumably others. Commenting out the line fixes these problems, but I don't want to make the fix myself because I don't know what effect it will have on the new tile randomization code. I'm renaming this issue to reflect that it's a broader problem with the rng.

**Comment by Zireael07** [comment]
Then it's related to #14172 
:eyes: @kevingranade , @sparr

**Comment by sparr** [comment]
Almost certainly related. I did not realize that a single RNG was being used for everything. I'll need to set up a second RNG for the tile stuff. Very sorry.

**Comment by adrianrieck** [comment]
I can confirm even with sewing clothes for example. Either you will always enhance clothes first time every time or you never will be able too.  Heh, No wonder I could never escape that bear trap last night.

**Comment by mugling** [comment]
> I can confirm even with sewing clothes for example

And picking locks etc...

**Comment by gbeck** [comment]
Unless I'm misunderstanding what the code is supposed to do, I don't think re-seeding the rng is doing anything useful here. It should only need to be seeded once on game initialization. Re-seeding doesn't make the numbers more random.

**Comment by gbeck** [comment]
I see what the code is doing now. It produces a random number that always comes out the same for particular tile coordinates. Using a seed seems like a logical way to do that. So you just need to re-seed with the time before returning control to the rest of the game. Or make your own number generator instead of using the global one.

**Comment by adrianrieck** [comment]
I tried commenting cata_tiles.cpp:1320 but it won't compile then. Does anyone know the latest version I could go back to before this bug was introduced?

**Comment by stk2008** [comment]
Thanks Coolthulhu I knew I was not going mad LOL.
Damn its unplayable in this state.
Will roll back but to what version as asked by adrianrieck

**Comment by sparr** [comment]
Immediate answer: Play in ascii mode
Less immediate answer: I'll submit a PR that fixes this bug ASAP.

**Comment by stk2008** [comment]
pfffft ascii dude you crazy :P

**Comment by adrianrieck** [comment]
There might be something newer but I went back to 1 December with a 
git checkout e8f8f1509f75fbe3c1dd162c6c7a4241dd4747f2
