### ISSUE TITLE
Recipe learning due to starting skills allows learning uncraft recipes

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14377]
Starting with 2 electronics will let you craft broken eyebots.
They aren't listed anywhere in the craft menu, but can be searched for.
Laptop computer can be crafted with 0 electronics.

**Comment by chaosvolt** [comment]
Odd. So they can only be accessed by using the find function?

Closing that loophole would be presumably a good first step, if feasible.
