### ISSUE TITLE
Add option to disable info text color highlighting

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#14388]
See issue: https://github.com/CleverRaven/Cataclysm-DDA/issues/14143

See PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/14154

See discussion that ensued on the "needful things" forum: http://smf.cataclysmdda.com/index.php?topic=5865.2715 and http://smf.cataclysmdda.com/index.php?topic=5865.2730

The addition of text color highlighting for various parts of the inventory has caused more player annoyance and inconsistencies then might have been expected. As @Coolthulhu suggested, making an issue to discuss this and possible alternatives. If I have to start quoting others that have expressed annoyance at this feature... >_>

**Comment by kevingranade** [comment]
Speaking of quotes:
See http://smf.cataclysmdda.com/index.php?topic=10444.msg244402#msg244402
```The project isn't a democracy, no number of "me too"s or votes is going to change something we've decided on, however we listen to peoples opinions and arguments for or against things.  A good reason to make a change has more impact than any number of votes.```
In this particular case, we've had a handful of people say, "I don't like it", with the only constructive feedback being "the brown color is too dark on many systems".  The brown color has been replaced, and the only remaining complaint is "I don't like it" from a few people.
The cost of adding options for toggling UI elements is very high, it makes the UI code more complicated and prone to bugs, hides bugs that depend on one setting or another, creates additional work to keep the options all working, and enlarges the options menu, making the game less approachable and more confusing to use.
As such I have no intention of having an option to toggle this feature based on the current (non) arguments for it, if there are additional arguments for why that should happen, feel free to make them.

**Comment by Coolthulhu** [comment]
What's the reason for multiple colors anyway?

I see one good split here: "constant" text and values. Usually in the form of `key: value`, where the key doesn't change (for example, "Bashing:"), where the value does.
It makes things more readable.

Why are more than two colors used? I see light blue for qualities, dark blue (moderately hard to read here) for materials and techniques, purple for category, bold white for volume (why just volume?)...
This means more chances for the hard to read color being used for something.
Readability isn't improved much because a great deal of it comes from the structure of text (which doesn't change with colors).

**Comment by chaosvolt** [comment]
I should also point out that the end result of the colors shown is highly variable based on the user's terminal. Inconsistencies are inevitable.

Between that and the fact it ate it the "stuff you've learned" when  first implemented, should've made it clear that a feature like this warrants further testing before being implemented. Or made optional because congrats, you approved a feature and made it mandatory without verifying whether doing so was worth bothering with.

It is a messy, inconsistent, unhelpful feature that has done more harm than good. There has been constant disagreement on HOW to implement this feature,and on whether it actually serves its intended purpose. That should've been argument enough to remove the bloody thing, let alone allow users to disable it.

**Comment by sparr** [comment]
@chaosvolt the colors can differ between systems, but their definitions don't. If "red" is a good color to represent fire, then "red" is the color we should use for things on fire, regardless of what your terminal might interpret "red" as.

**Comment by chaosvolt** [comment]
The issue isn't if your terminal's red is red. The issue is if your terminal's red is readable. :V

**Comment by sparr** [comment]
If any combination of colors is not readable, that's an issue to be fixed with your terminal.

I've used terminals that make white-on-white and black-on-black readable, even.

**Comment by kevingranade** [comment]
> I see one good split here: "constant" text and values. Usually in the form of key: value, where the key doesn't change (for example, "Bashing:"), but the value does.

That sounds reasonable, I'll buy the number of different colors being an issue.
Not sure how hard it'd be, but ideally we'd have a configurable "text color" and a "highlight text color". With that indirection people can select colors that contrast with their backgrounds and with each other, and people who don't want highlighting could just make them match.

**Comment by chaosvolt** [comment]
So you're saying no to adding an option to toggle text highlights due to option bloat. But saying yes to adding configurable highlight text colors.

Seems legit.

**Comment by Zireael07** [comment]
@chaosvolt: We already have some sort of a custom color handler (for colorblind folks), which does not live in options. I think what @kevingranade proposed would go there too.

**Comment by mugling** [comment]
> The cost of adding options for toggling UI elements is very high, it makes the UI code more complicated and prone to bugs

This would seem the strongest argument. The linked forum posts include preferences for and against certain colours as well as the horizontal dividers. Supporting each option can double the number of potential code paths.

> What's the reason for multiple colors anyway? ... Readability isn't improved much because a great deal of it comes from the structure of text ... and the "binary" part of the split: colored vs. non-colored

We could change the various `<stat>`, `<good>`, `<dark>`, `<...>` tags to just `<e>` which also has the added benefit that any text added in the future is easy to markup.

> Not sure how hard it'd be, but ideally we'd have a configurable "text color" and a "highlight text color".

This sounds like the best plan and is also one of the simplest to both implement and **maintain**.

**Comment by scorpion451** [comment]
Speaking as someone in the creative industry, I just would like to say this:
Ensuring that the audience is able to experience a creation properly is the responsibility of the creator(s), not the audience.

If I paint something entirely with >5% value, I should not be surprised when people without perfectly calibrated monitors say it looks like a black rectangle. If I do things which make the interface harder to read for even a few people and offer players no way to opt out of that, I should not be surprised when people complain about it. 

Part of what it means to be a successful creator of stuff is learning that there can occasionally be a massive gulf between "things that suit a creator's personal preferences" and "things your audience will like". At that point you have to choose whether you want to make something solely for yourself or whether you are trying to make it accessible to others.

**Comment by chaosvolt** [comment]
Hmm. While I'm at it, I'll quote blazing_glory who summed up the objection I have with this, much more competently that I've been able to.

> So I don't know how long it has been there but I downloaded the latest experimental and got just a bit ticked off at the new examine screen.
>
> http://i.imgur.com/9i6f165.png
>
> On the old screen, I find it pretty tight and easy to read, but the new one has colors seeking to distract you from seeing the whole thing and it's darker and thus, harder to see, I also find that the Horizontal Rule's (at least as the forum calls them.) clutter the screen rather then make it easier to digest the information.
>
> But, I'm not asking to ditch the new one, I'm just asking for an option somewhere to use the old screen so that I (and anyone else who is bothered by it) don't have to deal with the new one.
>
> Of course, this would also apply to the (e)xamine screen when you look at something, which has also been changed to the new one.

**Comment by Griffinhart** [comment]
>The project isn't a democracy, no number of "me too"s or votes is going to change something

CDDA Web Tools -> http://tools.cataclysmdda.com/iv ?

**Comment by kevingranade** [comment]
@scorpion451 Let me clarify, there are two situations in play here:
1. SDL rendering: In this case we are supplying a RGB value to SDL, so modulo monitor configuration or driver overrides of some kind we are in control of the actual displayed color, we need to make sure those colors represent a relatively high-contrast palette and generally work together.
2. Curses/terminal rendering: In this case we are asking the terminal we are displaying in to render an enumerated color, the RGB value these enumerations correspond to is not standardized, and AFAIK the application is unable to adjust them in any way.  For these we can choose a palette and use it in a way that should maintain enough contrast, but short of restricting ourselves to only black & white (or to a lesser extent, 4 or 8 colors instead of 16) there is no way to guarantee that any particular combination of colors will have a reasonable amount of contrast.

@Griffinhart that site is there to gauge interest, not make yes/no decisions about features.

**Comment by CIB** [comment]
Yes, I think having a mechanism for transforming colors to help out colorblind folk would be ideal. I already want something like that for the minimap, but it would help with many things.
