### ISSUE TITLE
[Bug] After a few ressurections from a zombie necromancer an NPC will ignore res'd zombie.

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#14384]
After finding this bug in game I found it reproducible in debug mode.
1. Go into debug functions.
2. Summon NPC.
3. Summon Zombie.
4. Summon Zombie Necromancer a distance away.
5. Watch as NPC kills zombie a few times then slays the zombie necromancer... then starts taking it on the chin from the remaining res'd zombie.

Here is copy of the save where I faced this bug in game.
[Bug-Passive_NPC.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/59029/Bug-Passive_NPC.zip)

**Comment by remyroy** [comment]
I was not able to reproduce the bug. This is not an issue for me. Even with your save file, on [BevapDin:wyk](https://github.com/BevapDin/Cataclysm-DDA/tree/wyk) which fix the issue of world loading, I could [see the NPC attacking the zombie](http://i.imgur.com/cvQ5Vgp.png).

Here is what I noticed. The NPCs tend to prioritize fighting the necromancer first. Once that is completed, they will go for zombies.

**Comment by RogueYun** [comment]
I guess this was an error on my part. I can't seem to reproduce this bug either. Please close.
