### ISSUE TITLE
Add a 2 frame animation for head bobbing

### ISSUE THREAD

**Issue by remyroy** [CleverRaven/Cataclysm-DDA#14394]
It would be nice to have more animations in the game. As a small initial step, it would be nice to make it possible for tilesets to provide a 2 frame animation for head bobbing.

**Comment by drbig** [comment]
Question is - are these just aesthetics? There should be parity of information exposure between curses and tiles versions (as far as I can tell/would actually want at least).

**Comment by remyroy** [comment]
It would be nice to have them for curses as well. It should be possible.

**Comment by Coolthulhu** [comment]
Having critters (zombies) and fires dance around would make them more visible, which is good.
Even something like Dwarf Fortress style blinking would go a long way towards making stuff hide in plain sight less.

**Comment by drbig** [comment]
True. And "2 frame" should be doable in curses even with blinking.

**Comment by sparr** [comment]
Adding animations to tiles mode would not be very difficult, although the structure of a tile_config.json is getting pretty deep and we might want to discuss refactoring it.

Adding blinking "animations" to curses mode is... interesting. If monsters can blink, can they have two different letters/colors? That makes a lot of things more distinguishable. Players without the blinking turned on would still get as much info as they do now. However future contributors would have to be careful to keep in mind not to convey game-critical information through blinking.

**Comment by kevingranade** [comment]
The portal tile cycles IIRC.

**Comment by chaosvolt** [comment]
So would zombies get to alternate between their normal tile and a light blue ñ like in DF? XP

**Comment by Chezzo** [comment]
The portal does indeed cycle in ASCII mode, but does not show up whatsoever in tiles mode.

**Comment by chaosvolt** [comment]
Hmm. Being able to add cycling tiles for things that cycle in ASCII mode would be a good minimum application of this concept.
