### ISSUE TITLE
Can't make an item extra sturdy from brazier fire

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#14409]
Hi, this bug requires more testing, but I can definitly say that when you are in a dark room (like all curtains closed) and light a fire in a brazier (light indicator says brightly), using a sewing or tailoring kit allows you to repair an item to full, but after that you will always get "practice your sewing". There is 0 chance you can make the item extra sturdy. 

As soon as I move to a window and open it (assuming its light outside, again, indicator says brightly) using the kits once immediatly achievs the desired sturdying. 

I haven't tested with other indoor light sources yet though.

**Comment by remyroy** [comment]
I cannot reproduce this. This is not an issue for me. On [BevapDin:wyk](https://github.com/BevapDin/Cataclysm-DDA/tree/wyk) which fix the issue of world loading, I was able to [make boxer shorts extra sturdy in the shelter next to a lit brazier](http://i.imgur.com/BPfKnQh.png).

**Comment by narc0tiq** [comment]
It sounds to me like <https://github.com/CleverRaven/Cataclysm-DDA/issues/14375#issuecomment-163867513>, which should have been resolved by #14393.

It might not be, though:
- were you playing with tiles?
- were you playing a version between 0b042ff32f32e2ef5a8513c6397dbed9c5be8676 and a1c7976cd38067df014bfc7fe76917ea84e6746e (alternately, an experimental build between [4015](http://ci.narc.ro/job/Cataclysm-Matrix/4015/) and [4030](http://ci.narc.ro/job/Cataclysm-Matrix/4030/))?

**Comment by sparr** [comment]
@molkemon can you zip up a save and post it somewhere for this, if it's still happening?

**Comment by molkemon** [comment]
@narc0tiq: yeah that was it, i was running 4018, i experienced both the loot bug and further testing revealed that it wasn't the brazier, but the specific tile i was standing on next to the brazier. Moving to another tile made item improvement possible again. Since this has been resolved already, I will close the issue. With my current build (self-compiled), the loot tables are random again (a bit sad, boomers would always drop powdered eggs for me which was really nice and swimmer zombies dropped 40k cash cards each :D).
