### ISSUE TITLE
Don't shift focus of adv. inventory away from [A]rea when moving items

### ISSUE THREAD

**Issue by scorpion451** [CleverRaven/Cataclysm-DDA#14403]
So this has been bugging me for a while.
Scenario:
one tab of the advanced inventory window is open to [A]rea, and the other is on, say, [I]nventory. 
When moving an item out of inventory to area, I am prompted to select one of the surrounding tiles.

Here's where the trouble comes in:

Formerly, this merely moved the item to that tile without changing the focus away from area. This was a wonderful feature which made it a simple, quick process to rapidly sort and shuffle items between various surrounding containers and my inventory: I could simply leave one tab on area and flip the other to whatever place I wanted to move items to and from at the moment. Each item move only took 2 button presses- one to move the items, the other to choose where they should go. If I had several items that went to the same place, I could even just double tap return to reselect the same destination.  This was wonderful.

At some point in the recent inventory management tweaking, however, my wonderful sorting tool was broken. Now selecting the tile to drop an item to changes the focus of the window from Area to whatever tile I moved the item to. This is bad: Now moving an item takes 5 button presses: one to move the item, one to select where to move the item to, "tab" to switch over to the panel which is supposed to be on area and is now on whatever tile I moved the item to, "a" to switch back to area, and "tab" to switch back to the panel I'm trying to sort things into and out of. Repeat x however many items I'm trying to sort out into my storage bins. This is rather annoying.

**Comment by sparr** [comment]
I, too, am not a fan of this change.

**Comment by Coolthulhu** [comment]
I don't think anyone really likes it, it was probably a side effect.

**Comment by sparr** [comment]
This appears to be a side effect, but a naively necessary one. The AIM can only move items into the panes, so the destination picker changes the destination pane. See my PR for an attempt to fix this, but the second half of the fix is going to be more complex.
