### ISSUE TITLE
Random vehicles not spawning

### ISSUE THREAD

**Issue by hitbutton** [CleverRaven/Cataclysm-DDA#14410]
When starting a new world, no random vehicles are spawning on roads in cities.

It seem that the first bad commit where this starts occurring is: 84a8913976ced0b31b5e816811a64c32dd61da16

**Comment by remyroy** [comment]
This is not an issue for me. On [BevapDin:wyk](https://github.com/BevapDin/Cataclysm-DDA/tree/wyk) which fix the issue of world loading, I can [see multiple vehicles on the roads](http://i.imgur.com/MWJBaT2.png).

**Comment by hitbutton** [comment]
I'm testing from CleverRaven/Cataclysm-DDA/master from commit 89584e6 (with the teashop json manually changed to prevent the crash bug) so that should be essentially the same.

I start a new world and don't see any vehicles on roads.
If I revert the changes to weighted_list.h, recompile and start a new world, multiple vehicles appear.

**Comment by remyroy** [comment]
I'm guessing the problem was already fixed in master or in BevapDin:wyk.

**Comment by remyroy** [comment]
I just tested 84a8913 and I can see vehicles on the road on my system.

**Comment by remyroy** [comment]
I just tested 84a8913 and BevapDin:wyk on Windows with MSYS2 and both do not spawn vehicles. It seems to be a Windows problem only. I'll investigate more.

**Comment by Malkeus** [comment]
I'm using Windows-64 tiles experimental 4032. I'm not seeing any vehicles in the streets, only ones that always spawn with a given building, like the buses around the refugee center. Theres a report on the forums someone made a few minutes ago as well: http://smf.cataclysmdda.com/index.php?topic=11804.0

**Comment by Malkeus** [comment]
I've tested the changes made in #14413 on windows, it appears to have restored random vehicles to cities and roads.

**Comment by molkemon** [comment]
I also compiled this and Vehicles started to appear in before unexplored Towns. My starting town remains empty though, is there a debug command where I can force Vehicle spawn or something?

**Comment by Malkeus** [comment]
I don't think you can force random spawns. When I want the world to regen, I delete all the map files except for the ones right around my base. You can find the right ones fairly easy by saving in the area you want to keep and then checking timestamps. I'm not sure how to reset the overmap though *shrug*

**Comment by RogueYun** [comment]
I was thinking it odd that the only vehicles I've been seeing are at road blocks or in parking lots.
