### ISSUE TITLE
Support monocles

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#14417]
`LEG_EITHER`, `ARM_EITHER` and `HAND_EITHER` were added in #13888. Logically we should also support `EYE_EITHER`.

I'm thinking various monocles (range finder, night vision), probably all with the `FRAGILE` tag.

![monocole](https://cloud.githubusercontent.com/assets/12238606/11767599/63d513ac-a1ab-11e5-85ec-75bb1f94c4d2.jpg)

Any suggestions as to what monocles to implement, their crafting requirements, durability and encumbrance penalties?

Should they go in the `BELTED`, `OUTER` or regular layer?

Should we restrict the player to one monocle per eye? Possibly via a flag that limits a player to one item in the item layer for the covered body part(s)?

**Comment by Coolthulhu** [comment]
Eyes are currently one part.
Monocles would need some really clever penalty calculations. They may not impair scoped sniping, but for stuff like traps, slings and hipfire they should apply the worst penalty (as if the monocle was covering both eyes).
Plus, we'd run into stupid cases like NV monocle + sniping, where the player would spot the critter with NV monocle, then snipe with the naked eye that can't see it.

It's certainly not just a matter of splitting the eye slot into two eyes.

**Comment by kevingranade** [comment]
A monocle is going to keep you from wearing other glasses, and it doesn't
make sense to wear different monocles, what is the benefit of special
handling for them?

**Comment by Headjack** [comment]
Disappointingly, I think Kevin is right. It sort doesn't do much unless they can do something other eyewear can't, like be flipped down or something. Mod-worthy, perhaps? Or maybe it would make sense if you had some kind of mutation or injury, for example if a hypothetical EYE_EITHER let you lose one eye, then you used a cybernetic prosthesis there.

**Comment by Malkeus** [comment]
Perhaps some hands-free type lenses. I think they are mainly used to easily
magnify small objects such as circuit board components or for gemstone
cutting without tying up a hand. They could provide a speed boost to
electronics work or be a new tool requirement for delicate work such as
CBMs. I can't think of a tactical use for one atm though.

**Comment by Malkeus** [comment]
Something like these: http://www.delpozzo.com/magnifiers.htm

**Comment by Shadefang** [comment]
Those seem like they'd take the same slot as clip-on sunglasses. As interesting as it seems, I can't think of anything that this would significantly improve.
