### ISSUE TITLE
'e' then direction to check on vehicle while driving forbidden, 'g' then 'e' is not

### ISSUE THREAD

**Issue by valuial** [CleverRaven/Cataclysm-DDA#14415]
I've tried for several days to check my vehicle status while driving (damage, fuel, safe speed etc.) but the usual way I open the vehicle menu, 'e' then the direction of a vehicle part, is disabled while driving and will not work on moving vehicles when letting go of the controls for a second.

Now railmonkey told me you could go with 'g' then select 'e' to examine vehicle, which works while driving. Should'nt the first method be valid as well?

**Comment by Headjack** [comment]
I've often done this. I dunno why checking is forbidden to begin with.

**Comment by CIB** [comment]
Does it allow you to do vehicle modifications when using g while driving? :)

**Comment by illi-kun** [comment]
Duplicate of #11037.
