### ISSUE TITLE
Combine arm/hand/leg/foot rows in various screens

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14422]
I sometimes play on a small screen. I'd like to have to scroll less often. 99% of the time, almost every detail of my left and right arms are the same. Ditto legs, hands, feet.

I'd like to update the player info and layering screens to combine each pair iff the pair show identical info in the given interface. In the usual case where they all match, this means the player info screen will have just 8 rows instead of 12, which means no scrolling at all will be required to see all the info.

Since this will involve a lot of tedious data manipulation coding, I'm asking here first whether it is a desirable/acceptable change.

**Comment by kevingranade** [comment]
That seems reasonable, the only concern I'd have is it means those will be tested mostly with one configuration, and bugs with the other configuration might creep in, but I dom't think that's worth blocking a nice UI improvement over.
