### ISSUE TITLE
Headlights orientation is random

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#14434]
When building a car and installing headlights, most of the time the desired light orientation won't work, and the light cones will shine somewhere randomly instead. Sometimes it randomly works.

**Comment by kevingranade** [comment]
When installing, do you hit enter a few times, or hit enter, move the
cursor, then hit enter again?
Regardless I know the ui for installing headlights is terrible, just trying
to determine if it's that or a new bug.

**Comment by Coolthulhu** [comment]
It's probably the result of the new vehicle pivot point code.

The starting point of the light (the default point presented to player) depends on vehicle pivot, while the calculation of the direction of the light assumes pivot is `(0, 0)`. So it's not random, but can be hard to predict.

**Comment by mutability** [comment]
I accounted for the new origin at the time, but there was a typo in it.
