### ISSUE TITLE
Game crashes frequently for unknown reason

### ISSUE THREAD

**Issue by lauriwesterlund** [CleverRaven/Cataclysm-DDA#14430]
Current version is 0.C-8197-g1f7d1bc, but this started in earlier versions within the last three days or so. Ncurses, Ubuntu 14.04.

Screenshot: https://www.dropbox.com/s/3fma21yll088rvl/crashscreen.png?dl=0
Save: https://www.dropbox.com/s/h1dhuetha02kwzk/crash.zip?dl=0

The game crashes very frequently in some areas. It might be related to certain monsters and their special attacks. This usually happens when fungals are nearby, but I've also run into it several times in science labs and in the vicinity of slime pits. The save file I've provided always crashes for me within 5 turns if I keep driving forward with the speed the car is currently going. I managed to get away and continue the game by accelerating to high speeds and driving away before the crash happened.

**Comment by CIB** [comment]
It most definitely is related to special attacks. I have a reproducable crash file but I can't figure out what's wrong. Will upload.

**Comment by CIB** [comment]
https://www.dropbox.com/s/eaktzfanbf5hsm6/crashsave.tar.gz?dl=0 <- Crashes for me if I keep driving for maybe 20 steps.

**Comment by CIB** [comment]
Output from gdb. This usually means somebody is modifying the container during iteration, though I can't fathom how.

```
/usr/include/c++/5.2.0/debug/safe_iterator.h:331:error: attempt to 
    increment a singular iterator.

Objects involved in the operation:
iterator "this" @ 0x0x7fffffffd560 {
type = N11__gnu_debug14_Safe_iteratorINSt8__detail14_Node_iteratorISt4pairIKSs18mon_special_attackELb0ELb1EEENSt7__debug13unordered_mapISsS5_St4hashISsESt8equal_toISsESaIS6_EEEEE (mutable iterator);
  state = singular;
  references sequence with type `NSt7__debug13unordered_mapISs18mon_special_attackSt4hashISsESt8equal_toISsESaISt4pairIKSsS1_EEEE' @ 0x0x1aaf86b8
}

Program received signal SIGABRT, Aborted.
0x00007ffff63fe5f8 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff63fe5f8 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff63ffa7a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff6d39595 in __gnu_debug::_Error_formatter::_M_error (this=0x7fffffffd610)
    at /build/gcc/src/gcc-5.2.0/libstdc++-v3/src/c++11/debug.cc:782
#3  0x000000000051ec24 in __gnu_debug::_Safe_iterator<std::__detail::_Node_iterator<std::pair<std::string const, mon_special_attack>, false, true>, std::__debug::unordered_map<std::string, mon_special_attack, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mon_special_attack> > > >::operator++ (
    this=0x7fffffffd560) at /usr/include/c++/5.2.0/debug/safe_iterator.h:329
#4  monster::move (this=this@entry=0x1aaf8490) at src/monmove.cpp:487
#5  0x0000000000843bf9 in game::monmove (this=this@entry=0x72b00c0) at src/game.cpp:6060
#6  0x0000000000856b6e in game::do_turn (this=0x72b00c0) at src/game.cpp:1391
#7  0x0000000000a98100 in main (argc=0, argv=0x7fffffffe890) at src/main.cpp:434
```
