### ISSUE TITLE
Boards block vehicle turrets' line of sight on auto-fire mode

### ISSUE THREAD

**Issue by lauriwesterlund** [CleverRaven/Cataclysm-DDA#14439]
The title says it all. My turret refused to work until I replaced all heavy duty boards nearby with heavy duty quarterpanels. Not sure if regular boards do that. It doesn't really make sense for boards to do that unless zombies get really close. The turret will sometimes shoot when moving diagonally, but never when going straight.

Here's a save with the rear boards still there. Going to the south in reverse you should meet some zombies that won't get blasted by the rear turret. The other turret in the front that's surrounded by quarterpanels will happily shoot everything that gets in range and isn't blocked by the rear boards.

https://www.dropbox.com/s/9i2oewaap14xoao/turretbug.zip?dl=0

**Comment by sparr** [comment]
Does it just block automatic firing, or does it also block your visual LOS when you man the turret? And do the bullets impact the vehicle when you manually fire in that direction?

**Comment by lauriwesterlund** [comment]
Automatic fire only. Manual firing works fine and doesn't seem to harm the vehicle.

**Comment by Mooses2k** [comment]
Tested fixed with M60 mounted on interior of RV, firing through boards. Operates as expected, no damage to boards.
