### ISSUE TITLE
Multiple [,] Move All Items to the [I]nventory in a row in the AIM fails

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14444]
In the AIM if you move all items from your inventory to the ground nearby, then back, then do it again, the second attempt will have no effect. I tried to trace this past the call to `advanced_inventory::do_return_entry` but got stuck. There's a comment attributed to @kevingranade that tries to explain what's going on and it's above my head.

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/advanced_inv.cpp#L1187-L1199

**Comment by Oskar636** [comment]
Can't reproduce in build 5864 windows 64bit.

**Comment by kevingranade** [comment]
Issue no longer reproduces.
