### ISSUE TITLE
Map notes disappear when examined and escaped

### ISSUE THREAD

**Issue by aeoo** [CleverRaven/Cataclysm-DDA#14443]
Build 0.C-8241 or 4043 on jenkins.

If I examine a Map note and hit escape it seems like the note just gets deleted.  This isn't desirable.  If I hit the escape button I want whatever was there to be preserved (no action taken, I just want to get out of the screen).

So to reproduce, hit "m" inside the running game to get to the map screen.  Then hit "N" to make a note.  Make some note and hit enter.  Then hit "N" again on the same square to examine the note.  Then hit escape.  The note appears to have been deleted.  Ideally it should be left intact.

**Comment by aeoo** [comment]
@sparr There is already a delete note function via the "D" key inside the map screen.  Should "N" also allow note deletion?  "N" is described on the map screen with a label "Add/Edit a note."  So even the label says it doesn't delete notes.

I'd rather the escape button simply closed the note dialogue without altering any of the contents of the note and without any prompts.

**Comment by sparr** [comment]
@aeoo the punchline is that currently pressing escape is the same as erasing the string then pressing enter; both produce an empty string as the return of the dialog. changing that would require modifying a lot more code. so, being stuck with that, the question is what behavior is acceptable for both cases?

**Comment by aeoo** [comment]
@sparr Is it hard to just close the window?  Alternatively escape can be made equivalent to hitting enter.  There is already code that handles the enter key.  Making escape do exactly what the enter does shouldn't be hard, at least in theory.  The enter key doesn't delete anything so the code path that does the right thing already exists and doesn't need to be written again.

Given no other choice, of course I will prefer a dialogue that confirms deletion of the note over the notes being silently and surprisingly removed by a function that doesn't advertise deletion.  But that seems like a lot of extra work.  You have to spring a confirmation dialogue, parse its input, do different things based on that input, etc.  I think it should be easier to exercise a code path that must already exist without any extra popups.  To my mind adding a confirmation popup is harder to code and it performs useless work anyway.  So a lot of effort for nothing.  But that's just me.

**Comment by sparr** [comment]
The code for that window is used many other places. It's a generic "show a prompt, get a line of text". In all those other places, escape is an intentional "quit and return nothing" action.

We could ditch the confirmation and just not delete. Treat escape and blank-line-enter as NOPs and leave the note in place silently. If anyone is using N-^H-^H-^H-^H-ENTER instead of D-Y to delete a note, they can switch to doing it the right way.

**Comment by mutability** [comment]
Why not add more behaviour to string_input_popup? It's already got a bunch of default args that control behaviour, add another to say "I want the original string on escape" or even "please return a different magic value to differentiate enter and esc"

**Comment by BevapDin** [comment]
> both produce an empty string as the return of the dialog

Why would anybody want an empty note? It's probably safe to assume empty == canceled.

**Comment by mutability** [comment]
@BevapDin: You can currently delete a note by editing it and deleting all the text.

**Comment by BevapDin** [comment]
> @BevapDin: You can currently delete a note by editing it and deleting all the text.

I meant: why would the function need to distinguish between "user explicitly entered an empty string" and "user pressed escape"? An empty note is quite useless and it can be assumed the user has just canceled the input. Why make things more complicated than necessary?

**Comment by mutability** [comment]
Because "user pressed escape" should retain the old note text, and "user explicitly entered an empty string" should delete the old text.

**Comment by mutability** [comment]
Talking in circles a bit I think. The argument seems to be that if a user has explicitly deleted all the text, they must have meant to cancel because there is another way of deleting notes. I don't understand that argument: if the user has _explicitly deleted all the text_, surely they did not mean to retain the original note unchanged, regardless of whether there's an easier way of doing it. From the user's point of view, it would look like the game is throwing away their action.

**Comment by aeoo** [comment]
>Because "user pressed escape" should retain the old note text, and "user explicitly entered an empty string" should delete the old text.

I agree that what you describe is ideal, but in practical terms is it possible to ask people if they use the edit function to delete notes often?  It seems like a corner case.  Ideally it's good to handle corner cases in a manner consistent with the "least surprise" principle.  But assuming we have a genuine corner case there, it's rare.  So the easiest thing to do is to code an 80% solution.  Handle all the common cases and leave the rare ones alone.  The common way to delete a note is, I assume, with a "D" button.  Backspacing through an edited note is a strange way to delete a note.  But I agree that ideally if someone really went through the trouble of backspacing everything via edit, they should be rewarded with a deleted note, lol.  Ideally.  But that wouldn't be a part of my 80% solution tho.   This is how I think about it.  I might say something else if we had polled the users and we knew for a fact that perhaps backspacing through notes is a very common occurrence.

**Comment by mutability** [comment]
Personally, I deleted notes by clearing them quite a bit early on because I could remember N, but remembering another infrequently used key didn't make it into muscle memory.

Same reason I can never remember the delete-word keystrokes in <insert editor> :)

**Comment by aeoo** [comment]
@mutability I hear ya.  Well, what you suggested originally is functionally the best implementation in my opinion.  I was just trying to give some support to what I thought @BevapDin was trying to say too, which I believe is to code something that's mostly good (as opposed to perfectly good), you know the 80% thing.
