### ISSUE TITLE
Suggestion : Mutated NPC defined json file.

### ISSUE THREAD

**Issue by lagnas2000** [CleverRaven/Cataclysm-DDA#14458]
How about add Mutated NPC with random selection in categorized mutation group like npc`s item_group?

If add mutated npc, I can vary npc`s apperance. 

1. Add apperance mutations in json file. (ex : blonde hair, black hair, blonde eye, black eye... etc)
2. Add oversprites each apperance mutation. 
3. When NPC created in game, have hair and eye apearance mutation. So, the NPC have variety looks.

**Comment by Coolthulhu** [comment]
> Add apperance mutations in json file. (ex : blonde hair, black hair, blonde eye, black eye... etc)

"Mutations" this cosmetic should have their own category, not be bundled with mutations and traits.
Bundling them with mutations would make their processing slower, pollute menus and possibly cause bugs.

If it's just about tiles, it might as well be a set of strings that describe the looks.
