### ISSUE TITLE
Add an option to make the map square-fonted instead?

### ISSUE THREAD

**Issue by Dalenacio** [CleverRaven/Cataclysm-DDA#14456]
When I use the map, I really need to be able to calculate distances correctly, which is irritatingly difficult with rectangular tiles. Having an option to set the map in square-font would allow for much better proportions and awareness of space in general, while still leaving the die-hard fans of rectangular the possibility to stick with the current one.

**Comment by sparr** [comment]
This can already be done in the font configuration json. Exposing all of those options through the in-game options menus would be useful.

**Comment by Nioca** [comment]
Does this work in the console (non-tiles) version? I attempted to change the used font in my game, and nothing seemed to work.

**Comment by sparr** [comment]
No. In the console you're stuck with whatever font your console is using.

**Comment by hitbutton** [comment]
Since the ability to set differing fonts is exclusive to tiles, would it make sense to move font configuration into tilesets?

**Comment by narc0tiq** [comment]
The Windows Curses version of the game is a console emulator -- see
src/wincurse.cpp for the implementation. It uses, to the best of my
knowledge, GDI+ for rendering. While it is not built to render different
sections of the screen with different fonts, it does still require font
configuration.

**Comment by SunshineDistillery** [comment]
In fontdata.json I usually change the width to 16 and then leave the actual fonts alone. That gives a square map but makes the text  s e e m   r e a l l y  w i d e l y  s p a c e d. I find that to be a pretty minor problem compared to crashing my car into stuff.
