### ISSUE TITLE
Welder usable where it shouldn't be/Acetylene torch unusable where it should be.

### ISSUE THREAD

**Issue by Shadefang** [CleverRaven/Cataclysm-DDA#14459]
Many of the vehicle parts (e.g. FOODCO Kitchen Buddy and vehicle controls) can be made with the welder, makeshift welder, or integrated toolset, but not the acetylene torch.

In addition many clothing recipes (mostly survivor gear) require a welder, soldering iron, or integrated toolset.

I'm pretty sure the first is unintended, and I'm curious what peoples' thoughts are on the second one.

Note, I have a list of the first one, and can make a list of the second category if anyone wants them.

**Comment by Rivet-the-Zombie** [comment]
It's intentional. Try soldering a PCB or fusing polymer with an oxy torch and see how well that pans out.

**Comment by Shadefang** [comment]
I'd imagine it'd work a bit better than trying to use an arc welder.

**Comment by kevingranade** [comment]
So that's a bug with the arc welder :)

**Comment by Shadefang** [comment]
Okay. Having revisited it, there seem to be three main categories and a handful of edge cases.
First, the edge cases. 
* The heavy survivor gear combines kevlar and metal plating. Seeing as you can repair metal with a soldering iron you may or may nor need a welder in addition to a soldering iron.
* ANFO charge. Not sure what to think here. The description says a plastic drum, the recipe calls for a steel one. In either case, I'm not sure you'd need or want to use a heat source for this.
* Reinforced glass. There's a whole can of worms behind this one that we probably shouldn't get into here. But given the current recipes, it seems to make _more_ sense to use an acetylene torch than an electric welder, or even a soldering iron.

And the more clear cut ones:
* Cases where using any type of welding should work:
 * mechanical pump
 * folding bicycle
 * large steel drum (also needs makeshift welder added)
 * wooden barrel (welding the ring)
 * reinforced headlight (recipe implies you weld a wire cage together and glue the light into it)
 * seat (recipe implies you weld the frame together and stitch the cover over)
 * reinforced solar panels. (recipe/description seems to imply you're using scrap metal to hold the reinforced glass over the panel)
* Cases where welders should not be used at all
 * (all plastic/kevlar clothing without metal parts, too many to list here)
* Cases where you need welding and soldering ability
 * drive by wire controls (already has soldering iron)
 * vehicle welding rig
 * foodco kitchen buddy
 * onboard chemistry lab
 * rv kitchen unit
 * vehicle controls
 * electric forge (currently requires welding OR soldering, not welding AND soldering)
 * ferromagnetic rail rifle
 * electric jackhammer
 * electric chainsaw
 * seed drill (electric motor and processor board)
 * plow (electric motor)

**Comment by Voker57** [comment]
Welder is unusable for cutting open metal doors (despite being well able to take apart and build whole vehicles) and acetylene torch is usable. Is this intentional?

**Comment by Rivet-the-Zombie** [comment]
Welders are made to weld metal stuff together, whereas an acetylene torch can weld or cut.

So yeah, it's intentional that you can cut stuff with a cutting torch, but not with an arc welding rig.

**Comment by Voker57** [comment]
But why can you cut vehicles apart with welder then?

**Comment by Coolthulhu** [comment]
You can't, you need a hacksaw or an acetylene torch.
