### ISSUE TITLE
[Action Menu] Sheathe/draw a knife not working?

### ISSUE THREAD

**Issue by SeanMirrsen** [CleverRaven/Cataclysm-DDA#14452]
I'm not sure if it ever worked, but now I started several Military Recruit characters, who start with a sheath and a combat knife, and in the `%` Action Menu I have the option of using a combat boot as a holster, but the `Sheathe/draw a knife` option is always greyed out and unavailable, regardless of which state either the sheath or the knife are in relation to each other. Is that a bug, or just an unimplemented feature?

**Comment by Coolthulhu** [comment]
Bug
Sheathe/draw action no longer exists (it's all a part of the holster action now), but it still has an entry in `item_actions.json`.

**Comment by SeanMirrsen** [comment]
Aha. Okay. Then why is the holster action not available for the sheath? I just see the holster action for the boots, and trying to use that tells me that the boots aren't big enough to fit the combat knife. Nothing else present in the menu, despite the sheath being worn as usual. Even checked that it is worn on the outer layer, just in case the game checks for that.

**Comment by Coolthulhu** [comment]
Limitation
Currently the item action menu is rather simple - it was created when most actions were described mostly just by their name and cost to execute.
It picks the first suitable item it finds rather than the one that is most suitable.

**Comment by SeanMirrsen** [comment]
Aha. Thanks for the explanation. I guess it's something of a low priority at the moment. Though I have to say it'd be quite a nice quality-of-life tool overall, if it were made more flexible.

**Comment by scorpion451** [comment]
Maybe the new "f" holster popup menu thing could be expanded/adapted/used as inspiration for something that would allow re-holstering, sheathing, and attaching tools to loops, all in one menu? If nothing else, it'd save a ton of menu shuffling.

**Comment by mugling** [comment]
> Thanks for the explanation. I guess it's something of a low priority at the moment

If this is considered a regression I would like to fix this. There is however the argument that the action menu already has far too many options.

> Maybe the new "f" holster popup menu thing could be expanded/adapted/used as inspiration for something that would allow re-holstering, sheathing, and attaching tools to loops, all in one menu?

I am planning to expand upon #14217 at some point but I'm not sure exactly what the best UI would be?

**Comment by Oskar636** [comment]
This bug is still in, but it works strange. In the action menu the sheath knife option doesn't work but the " use holster " one works, _but_ it only recognizes one holster you have on your body so if you for example:
Have a katana and a knife on you,
A sheath and a scabbard worn,
It will only recognize one of the holsters and then when you sheath the item you can activate it to unsheath it ( so it will display " use holster [ scabbard with katana ( left ) ] " instead of displaying a diffrent one ) .

**Comment by I-am-Erk** [comment]
This appears to be quite out of date to me. Closing until contradicted.
