### ISSUE TITLE
Home Frontier Starter Pack apparently needs a manual.

### ISSUE THREAD

**Issue by SeanMirrsen** [CleverRaven/Cataclysm-DDA#14479]
The Home Frontier Starter Pack is a neat little item in principle, but the uncraft recipe for it is not learned automatically. Honestly, learning it automatically would make little sense because then it'd be sitting in your recipe list like the go bag does, but as per my other issue I believe we need to start looking into ways that items can supply their own recipes to the player.

As an idea, perhaps the same way books do? The recipes wouldn't be memorizable and would only exist as long as the item in question exists. So, if you find a Home Frontier Starter Pack, or a go bag, or anything of the sort (that can be modified, cooked, etc, but it wouldn't make sense for its recipe to always be available for one reason or another), then you would have its recipe(s) shown to you. And you would no longer have those recipes in your list when you no longer have the item (i.e. you've opened the Pack or sawed off the shotgun, etc). If you want to have the recipe reversable, it could be learned from doing that, or alternatively, as in the case of the Pack, a "manual" item could be added that comes from disassembling the Pack, which would provide the necessary crafting recipe to repack the Pack.

**Comment by Coolthulhu** [comment]
Deconstruction recipes are not supposed to be memorizable, ever. They work fine without that.
Knowing recipes like the one for the toaster or broken eyebot is a bug.

**Comment by SeanMirrsen** [comment]
No, I mean it (the Pack) can't be disassembled, because the deconstruction recipe is not autolearned. And I meant memorizing the re-constructing recipes from performing the deconstructing ones (such as for the go-bag, which beginning characters without military backgrounds have no business knowing in the first place).

**Comment by Coolthulhu** [comment]
> No, I mean it (the Pack) can't be disassembled, because the deconstruction recipe is not autolearned.

What does it say when you try disassembling it?
May be some weird bug, because here it just allows disassembling it on a fresh character.

The only two deconstruction recipes in the game that are autolearned are those for power armor and power armor helmet.
This is a bug, because a deconstruction recipe that is learned allows constructing the item, but doesn't list it in any crafting category (has to be searched for).

**Comment by SeanMirrsen** [comment]
This is what I'm seeing: https://dl.dropboxusercontent.com/u/4152380/Screenshots/BuggedFrontierPack.png

The "disassemble" option is grey, and I tried using it anyway there just previously, it says the item cannot be disassembled. I have a hammer and a screwdriver on my person, and a hacksaw in one of the nearby piles so that it's a valid crafting tool. Lighting is bright, fabrication skill is 2, so I've no idea what is wrong here.

**Comment by Coolthulhu** [comment]
The recipe doesn't depend on any tools, it should be possible to disassemble the pack without any tools or skills.
It must mean that either game somehow couldn't load the recipe, a mod changed the recipe somehow, a mod introduced some "fake" starter kit that lacks the proper id or that there is a yet-undiscovered bug with crafting.

What mods are you using?
Did you try saving and reloading?
A save uploaded somewhere may be helpful. When packing the save, if it is too huge, you can skip the "maps" directory and the huge "o.0.0" files as long as the bugged starter pack is in your inventory. They contain map data like terrain, buildings, items not carried by player etc., but aren't useful when finding bugs in crafting.

**Comment by SeanMirrsen** [comment]
Of standard mods I'm using, let's see. More Survival Tools, Boats, and Folding Parts Pack, plus various blacklist mods to remove fictional/futuristic/silly weapons/armor and joke monsters.
Nonstandard I've replaced the `names/en.json` file to swap original backer names for a list of non-immersion-breaking random names, and I play with my trifecta of custom bitmap fonts.

Yes, I had the game saved, and reloaded it to take that screenshot.

The save isn't big, this world is a fresh one I've started pending resolution of #14453 so that my character in another world doesn't have her feet freeze off. Here you go: https://dl.dropboxusercontent.com/u/4152380/Lyons%20Plain.zip

**Comment by BevapDin** [comment]
> plus various blacklist mods to remove fictional/futuristic/silly weapons/armor and joke monsters.

No_Rivtech_Guns and Generic_Guns both remove the L2031 Enforcer from the game. That gun is used in the Home Frontier Starter Pack recipe. Because there is no alternative to that component, the recipe would be invalid and is therefor (automatically) removed.

One of these mods should perhaps add their own disassemble recipe, or the core recipe could be changed to have a list of possible guns (default created items will use use the first item in the list anyway).

**Comment by SeanMirrsen** [comment]
Hm. Okay, that makes sense. I guess it's a mod oversight. The mod should either replace the gun it removes in the disassemble recipe, or remove the pack itself as it does the gun.

**Comment by sparr** [comment]
@BevapDin I would consider that a bug. I agree that the *assemble* recipe shouldn't be valid if a mod removes one of the components, but the *disassemble* recipe should still work and just not produce that component.

**Comment by SeanMirrsen** [comment]
Or that can work too, at least as a catch-all.
At the same time, I am now thinking of that idea I had while typing up the OP. How slow is the code responsible for books propagating their recipes to the player, I wonder?

**Comment by BevapDin** [comment]
> but the disassemble recipe should still work and just not produce that component.

The Starter Pack explicitly states that it contains a "Enforcer autorevolver", if disassembling skips that, you'll get another set of bug reports.

**Comment by SeanMirrsen** [comment]
I'm looking at what the Pack produces, and... what the hell is a L1820 Long Ranger, and why is it not also removed by the "No Fictional Guns" mod? It seems like the mod should either completely remove the Pack, or replace it with another item containing different guns, and a different description.

**Comment by sparr** [comment]
@SeanMirrsen the recipe propagation code is fast enough that we run it to collect local books every time we populate the recipe list when you open the crafting dialog, iirc.

@BevapDin good point. I'd just be sad to see such a cascade of item removals :(

**Comment by SeanMirrsen** [comment]
I'd say change the mod to provide a replacement Home Frontier Starter Pack. The item makes sense, it just needs to have a different pair of guns, and probably not being made by a fictional company.

@sparr Is it fast enough to still work well when there could potentially be hundreds of "books" around?

**Comment by chaosvolt** [comment]
Hmm. I'm in favor of just adding the HFSP (Hidden Fun Stuff Pack? Nyet.) to the fictional guns blacklist, as that'd be simpler than adding an override for the item and recipe to yield non-fictional weapons.

**Comment by SeanMirrsen** [comment]
That would probably be simpler, yes, especially since the mod has a bug either way since it isn't blacklisting the /other/ gun in the pack, which is also, AFAICT, fictional.

I don't suppose it's possible, however, that disassembling a pre-assembled item would not necessarily yield all the items from it? I mean. I just found a heavy box labeled "Home Frontier Starter Pack" in somebody's basement. Besides what the label is promising me, how do I know the package actually contains what it says it does? The family could have been storing excess money in it. Or a violin kit. It's just a box, after all. And CDDA is, nominally at least, a roguelike, so unknown-result items shouldn't be /that/ surprising.

**Comment by chaosvolt** [comment]
That sounds like another slipup in that the other futuregun I'm guessing isn't in the blacklist.

**Comment by sparr** [comment]
It's easy for someone to not think to update the blacklist mods when adding items to the game.

**Comment by chaosvolt** [comment]
True. I've done that myself. ;w;

**Comment by SeanMirrsen** [comment]
Hm. How does one override an item's disassembly recipe? The usual way of just adding a recipe with the same ID creates a conflict instead.
https://dl.dropboxusercontent.com/u/4152380/Screenshots/AlteredStarterPack.png

**Comment by chaosvolt** [comment]
There's an `Override: true` property you can add to a recipe.

**Comment by SeanMirrsen** [comment]
Okay. Thank ye kindly. :)
So for myself, I've altered the "No Fictional Guns" mod to provide a substitute for the HFSP (as seen above), which yields just the repair kit, gun manual, and a few batteries, with the understanding that the owners took the guns and the holster before they left. This is probably not a solution that should be PRed, since per the mod the guns in question shouldn't exist in the first place, but I didn't feel like cheating myself out of a firearm repair kit. :P
