### ISSUE TITLE
Weather and/or items warmth (win sdl 4061)

### ISSUE THREAD

**Issue by Vsevolod-Shustov** [CleverRaven/Cataclysm-DDA#14473]
How to reproduce:
1) Start in spring or summer.
2) Observe all body parts at -100 temp.
3) Try to sew something to warm yourself.
4) Freeze to death.
I'm pretty sure it's not how weather is supposed to work.
https://github.com/CleverRaven/Cataclysm-DDA/commit/c69598c4f9af02ad597343f74d339aba4fd153ce might have something to do with it.
![cata66](https://cloud.githubusercontent.com/assets/1062138/11895328/eafe9434-a58e-11e5-8949-036a77c9e122.PNG)

**Comment by gbeck** [comment]
I can confirm my body temperature suddenly dropped to -100 on latest build with environmental temperature of 67F. This has got to be related to #14279.
