### ISSUE TITLE
Better butchering items don't help

### ISSUE THREAD

**Issue by cherrydev** [CleverRaven/Cataclysm-DDA#14486]
It appears this is a long-standing bug that was reported as far back as 0.9 [here](http://smf.cataclysmdda.com/index.php?topic=4324.0).  I have survival 5 and have been butchering with a hunting knife (butchering 30) and slaughtered an entire basement full of giant black widows (probably 40 or more of them).  Absolutely zero chitin dropped from them.  I have not yet tested to see if other spiders drop it or not.  Dex is 8, Str is 8.
Looking at the code, my skill shift should be up to:
5 - 4 = +1 for survival 4
+0 for dex
+0 for str (Oops, I think there's a bug in that code!)

``` cpp
///\EFFECT_STR >4 randomly increases butcher rolls, <4 decreases
        if( p->str_cur < 4 ) {
            skill_shift -= rng_float( 0, 5 * ( 4 - p->str_cur ) ) / 4.0;
        }
```

Right now it doesn't give any bonus for strength.
So, my skill shift is at most +1 total.

Pieces/skins start at 2 for a 'small' creature (weird that giant black widows, giant black widow spiderlings and regular black widows are ALL 'small' creatures).

`skins +=    std::min( 0, roll_butchery() - 4 );` should give me at best -3 + 2 = -1, which means that I can't possibly get a single piece of chitin until my survival skill is 7?

So, is there a missing piece of code there for the effect of strength on butchering?  It appears that it MIGHT be supposed to be giving me a bonus of 0-5 for having strength 8.  On the other hand, getting a +0-5 butchering bonus for being average strength seems OP for meat and other items, so perhaps this is just a bad comment in the code, which makes sense since I can't really see how being stronger could help you butcher better past a minimal point.

But this IS surprising!: It appears that having a butchering tool with a value over 0 does not do anything at all for you:

``` cpp
        if( factor < 0 ) {
            skill_shift -= rng_float( 0, -factor / 5.0 );
        }
```

Where `factor` is `const int factor = p->butcher_factor();` and where `butcher_factor()` is the butcher level of the best butchering item in your inventory.  If the factor gave you a bonus equal to the penalty, I would get between 0-6 for having a hunting knife (the 2nd best butchering item in the game).

**Comment by sparr** [comment]
The behavior of rng*() with negative values is misunderstood by a bunch of the [previous] devs. Refactoring this code should not be difficult.

**Comment by cherrydev** [comment]
Can you extremely briefly describe what I seem to have misunderstood?  Thanks.

**Comment by sparr** [comment]
`+rng(0,X)` is the same as `-rng(0,-X)`

**Comment by cherrydev** [comment]
I don't see where I've made a mistake in that.

My point is that strength only has an effect if it's less than 4 (contrary to the comment) and that the `butcher_factor()` only has an effect if it's less than zero, meaning a better butchering tool (greater than zero) isn't better, which seems like a bug.

**Comment by sparr** [comment]
Oh, hmm. Either I screwed up that comment, or I broke the code when I added the comment. Good catch.

**Comment by cherrydev** [comment]
What about the behaviour of the butchering tool?  What's the intended logic for factoring in the benefit of a good butchering tool?  Do you agree that's not currently being taken into account (except when it's below zero)?

**Comment by Coolthulhu** [comment]
Good butchering tool isn't supposed to give more drops, only speed up butchering.
Currently the effect is minor because butchering times are quite low (a whole deer in 5 minutes or so).

I don't think strength ever gave a bonus, the comment is probably just wrong. It doesn't really make sense that hydraulic muscles would allow you to recover more meat and skins.

That said, the butchering math doesn't have any strict balancing going on. There may be a better way to do all of it - one that doesn't have so many "thresholds" and doesn't make low skill survivors unable to recover a single handful of meat from a whole dog.

**Comment by sparr** [comment]
Thanks for the summary @Coolthulhu, the distinction between drops and speed is an important one, and the two rightly behave differently. Sorry for the bad comment.
