### ISSUE TITLE
Defining multiple tile types in tileset_config

### ISSUE THREAD

**Issue by hitbutton** [CleverRaven/Cataclysm-DDA#14489]
It would be nice if tileset_config could take an array for the "id" field, allowing you to define tiles for multiple types with a single definition. Tile definitions can get quite lengthy with the various different types of tile that can be defined, and I often find myself copying fairly large blocks and only changing the "id" field.

This would purely be a quality of life change for tileset authors, so I'd consider this a low priority feature request.

**Comment by sparr** [comment]
This will be pretty easy to do. However, it's getting to the point that we definitely need to document the layout of tile_config.json. The various features are no longer intuitively graspable at a glance. When I tackle this issue, I'll also write a doc.
