### ISSUE TITLE
Line drawn in firing interface is not consistent or evenly sloped

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14494]
Open the [f]ire interface for a gun (or whip) with range 3-4 and move the cursor around the edge of the range. You'll see the dotted line jump around as you move, and sometimes lines that should be symmetric are not.

**Comment by kevingranade** [comment]
Define "jump around", and "should be symmetric".
The lines are rendered onto the grid in valid ways, and if there's an obstacle on one of those lines that leaves an alternate but valid line clear, it will use that line instead.  Why does the exact line chosen matter?

**Comment by sparr** [comment]
Re "jump around"... If you aim at a distant point, and move the cursor one square north, some points along the path can/will move *south*:

    pre:
    ____
    _OOX
    @___
    ____

    post:
    ___X
    __O_
    @O__
    ____

The character is adjusting their aim to their left, but the bullet path diverges to their right?

Re "symmetric"... 

    good:
    ____
    __OX
    @O__
    ____

    bad:
    ____
    _OOX
    @___
    ____

Both of these make it harder for a player to rely on bullet paths when positioning themselves to shoot around/past cover. They probably have the same underlying cause.

**Comment by kevingranade** [comment]
Re-read my first answer, if it can go around obstacles it will.

**Comment by sparr** [comment]
Ahh, in that case this is just a graphical problem, not gameplay. But it's still really weird, graphically.
