### ISSUE TITLE
Mods can't blacklist/overwrite recipes. 

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#14491]
Here's my problem:

In a mod, I want to replace the recipe for chainmail with a new one.
If I use the same recipe ID as the original, it causes an error. If I use an ID suffix, both recipes will be present. 
I could blacklist the current chainmail item and make a whole new one, but then I have to mess with all the item groups, and some things--like chainmail spawning in mansions--isn't in the jsons. 

I'd like it if recipes overwrote the originals, like how items work. Or, since that might cause trouble with multiple mods all overwriting one thing, a recipe blacklist might be better. (If there's a way to do this already, I couldn't find it.)

**Comment by SeanMirrsen** [comment]
Pft. I just asked the same question in an issue of my own a little while ago. XD
There is an "override" parameter you can add to the recipe, as `"override" : true,"`, which will cause the recipe to, well, override, any previously loaded one of the same name.

**Comment by SunshineDistillery** [comment]
Sweet. Thanks!
