### ISSUE TITLE
DANGEROUS ACID option

### ISSUE THREAD

**Issue by joneskun** [CleverRaven/Cataclysm-DDA#14509]
When encountering spitter/acidic zombies there's no gameplay in keeping their projectiles off of items on the ground, since acid (probably mostly realistically) no longer will destroy almost everything. This may also apply to grenadier/tankbot death drops/projectiles, haven't run into one recently.

Also, acid rain has gone missing and never returned.

**Comment by Rivet-the-Zombie** [comment]
>This may also apply to grenadier/tankbot death drops/projectiles

Explosions currently damage the heck out of items on the ground.

>Also, acid rain has gone missing and never returned.

It will be back as soon as somebody comes up with a system for it that doesn't suck as bad as the old one.

**Comment by kevingranade** [comment]
These aren't bugs, they're working as intended.

**Comment by joneskun** [comment]
The title clearly states option.
