### ISSUE TITLE
Random tile tool does not randomize items or NPCs

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#14503]
Using the random tile tool, it looks like, for items, it just uses the first on the list and does not ever show any others. 

I randomized the bags, boxes, cans drink and cans food, Try this tileset and teleport to a grocery and you will notice they are all the same, despite me giving them equal weights. 

http://chezzo.com/cdda/ChestHoleTilesetRBBC.zip

**Comment by sparr** [comment]
case C_ITEM:
        case C_FURNITURE:
        case C_TRAP:
        case C_NONE:
        case C_BULLET:
        case C_HIT_ENTITY:
        case C_WEATHER:
            // TODO come up with ways to make random sprites consistent for these types
            break;

As far as I can tell, items don't have a unique identifier that follows them through the game. Adding one would be non-trivial, but possible.

**Comment by Chezzo** [comment]
Hmmn, what about player sprites and npc sprites, @sparr? It is always pulling the same PC and NPC sprites for my random sprites, and that working was what I had people put the bounty on to accomplish.

**Comment by sparr** [comment]
Oh, that's a different matter, then. NPC sprites were definitely randomized when I submitted that patch.

**Comment by SunshineDistillery** [comment]
Items can have unique IDs for text strings. It's used for newspapers and flyers. It's also used for the sports jersey to give each item a team-name. 

That might be useable for tiles.
