### ISSUE TITLE
Reach weapon ranges shorted when circular distances enabled.

### ISSUE THREAD

**Issue by Skidborg** [CleverRaven/Cataclysm-DDA#14512]
Reach weapons ranges are rounded down when circular distances are enabled.  This makes diagonal attacks impossible with spears, pitchforks, etc.

The illustration below shows the reach distance of a spear with circular distances enabled (red) vs disabled (blue).

![illustration](https://cloud.githubusercontent.com/assets/8848477/11915667/7c228858-a666-11e5-870b-9796bac04c8a.png)

**Comment by Coolthulhu** [comment]
Currently ranges are expressed as integers. Fixing that will probably require changing them to floats.

**Comment by narc0tiq** [comment]
So, if your weapon's reach is 2 distance units, does that mean it should be able to hit the tile that's 2.236... (sqrt(5)) distance units away (up 2 tiles, left 1 tile)? How about 2.828... distance units away (up 2 tiles, left 2 tiles)?

**Comment by Malkeus** [comment]
Please correct me if I'm wrong, but doesn't this conform to circular
distances? It takes more time to walk diagonally because it's further away.
I believe the math was done in the comment above mine.

**Comment by sparr** [comment]
Please move further discussion to the PR, where I am already addressing your concern, @Malkeus
