### ISSUE TITLE
rl_dist vs trig_dist in non-movement contexts

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14519]
There are a number of places in the code that call `trig_dist` explicitly with the intent to produce circular patterns/behaviors. This is generally more aesthetically pleasing than doing the same things in a square pattern. However, from a game balance perspective, the edges of those areas SHOULD be a constant distance apart, which means using `rl_dist`.

I'd like to use this issue to discuss these situations.

1. The Zones interface uses `trig_dist` to tell how far away a zone is, which is misleading if it's a diagonal direction
2. Marloss items use `trig_dist` to spread their spores
3. Resonance cascades propagate in a `trig_dist` circular pattern
4. Many mapgen functions use `trig_dist` to draw circles (this is the most aesthetically important place, and the one I'm least likely to propose changing)
5. The overmap generator uses `trig_dist` to keep forests away from cities, and to place buildings
6. Diffuse monster groups spawn in a `trig_dist` circular pattern

**Comment by codemime** [comment]
One case was covered by #20020.

**Comment by kevingranade** [comment]
I propose that for the purposes of distributing entities on the map,
trig_dist is reasonable and should be kept, that is:

many mapgen functions use trig_dist to draw circles (this is the most
aesthetically important place, and the one I'm least likely to propose
changing)

the overmap generator uses trig_dist to keep forests away from cities, and
to place buildings

diffuse monster groups spawn in a trig_dist circular pattern

This leaves

Marloss items use trig_dist to spread their spores

resonance cascades propagate in a trig_dist circular pattern

the Zones interface uses trig_dist to tell how far away a zone is, which is
misleading if it's a diagonal direction.

My only question about resonance cascade is, is it something the player
will run from or is it purely visual?
