### ISSUE TITLE
Isometric Movement and Advanced Inventory Control

### ISSUE THREAD

**Issue by hitbutton** [CleverRaven/Cataclysm-DDA#14510]
Commit e6da996 added rotation to the movement keys in isometric mode to make movement more intuitive. This was a welcome addition :)

It would be nice if that support also extended to the Advanced Inventory screen, as the discrepancy between movement and choosing locations in Advanced Inventory is pretty confusing.

Ideally this should extend beyond simply remapping the keys, and also affect the display in the AIS. e.g. It would be odd if pressing 7 on the numpad (to select north) highlighted the 8 in the AIS.

**Comment by sparr** [comment]
Perhaps it would look something like this?

        [8]
      [7] [9]
    [4] [5] [6]
      [1] [3]
        [2]

This would be 2 lines taller than the existing display. How should it be made to fit?

**Comment by hitbutton** [comment]
I think the current layout is fine
7 8 9
4 5 6
1 2 3

But 7 should select N, 8 should select NE and so on...

**Comment by sparr** [comment]
oh, hmm. I guess that can work. very doable. will also involve changing the layout of the "you're moving to [A]rea, which way do you mean?" dialog.

**Comment by sparr** [comment]
This is turning out to be pretty tricky because of all the duplication of information between the various bits of the AIM code. I'll have to take a tougher look at it.
