### ISSUE TITLE
Constant crashes :(

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#14524]
Hi all this is anoying me now.
I keep getting random crashes

cataclysmdda-0.C-4072.zip 64bit (chesto tile set)
Win 7 64bit

Its crashing a lot normaly CDDA is very solid for me but lately its not.

Please could some on tell me what file I need to upload to help debug this please :)

Thanks all

**Comment by stk2008** [comment]
Ok i it crashes every time in about the same spot
I found a debug file at the end I see this

13:16:24.680 WARNING : opendir [data/mods//No_Joke_Monsters/modinfo.json] failed with "Not a directory".

could this be the issue? :(

**Comment by stk2008** [comment]
as suggested on IRC here is the save

Load it and move East (Right) you will see a dog ignore and it will crash after a few more steps

https://www.sendspace.com/file/v2ytqc

**Comment by stk2008** [comment]
Ok been getting amazeing help from 

SeanMirrsen
AlecWhite

On IRC and if you tell NPC NOT TO SHOOT it does NOT crash.

**Comment by mugling** [comment]
@stk2008 does 42ab7b9 resolve this for you?

**Comment by stk2008** [comment]
Hi muglin :)
Wow fast reply thanks.I cant test fix I have no wa to compile :(

**Comment by kevingranade** [comment]
The linked change was reasonable so I merged it, need confirmation that it actually fixed the issue though.

**Comment by SeanMirrsen** [comment]
Loaded the provided save in new version and observing no crash. Should still probably wait for the submitter to test it.

**Comment by mugling** [comment]
@stk2008 try nightly experimental build

**Comment by kevingranade** [comment]
Closing, but feel free to reopen if you get around to testing and find that it's still happening.
