### ISSUE TITLE
Crash when using slings and bows

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14533]
Ubuntu 15.10 gcc-5 RELEASE=1 console build
Segmentation fault as soon as I fire a pebble/marble/whatever, before the projectile is drawn on the screen. Happens regardless of whether there is only one ammo type or more than one.
Bows are also affected. It's probably RELOAD_AND_SHOOT handling.

**Comment by Etherdreamer** [comment]
Download the lastest version, seems is fixed now.

**Comment by SeanMirrsen** [comment]
Yeah, not seeing any problems with bows in the latest build.

**Comment by mugling** [comment]
Possible duplicate of #14524?

**Comment by Etherdreamer** [comment]
The issue was the targeting code (?) but thanks for fixing it!

**Comment by Coolthulhu** [comment]
OK, seems to be fixed now
