### ISSUE TITLE
Measured distance to objects often uses the wrong dist function

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14537]
inv_map_splice and the zone editor and the ;V interface and a few other interfaces all tell the user how far away and in what direction an object is. Some of these locations use square_dist, some use trig_dist. I think they should all be using rl_dist, because we need to be informing the player accurately of which items are closer. Discussion here will lead to me submitting a PR to make these things consistent, I'm just not sure in which direction the consensus will go.

**Comment by Leland** [comment]
I wonder if this has anything to do with how buggy zone creation is, e.g #19876
