### ISSUE TITLE
Mouse automove in isometric mode

### ISSUE THREAD

**Issue by hitbutton** [CleverRaven/Cataclysm-DDA#14548]
In isometric mode, attempting to automove using mouse left-click results in a single square being moved in an incorrect direction, then the automove is aborted.

**Comment by Chezzo** [comment]
Really? I am able to automove by clicking on my iso set. It works kind of slowly, but it works. Could you post yours? Mine is here:

http://chezzo.com/cdda/ChestHole32Tileset_iso.zip

**Comment by hitbutton** [comment]
I'm still getting the same behaviour using your tileset.
Build is Master at commit 93c2d5bc
compiled with MinGW in Windows 10

Are you using a build which automatically reassigns movement keys in isometric?
