### ISSUE TITLE
"Tried to find monster with invalid index -1" crash (win sdl)

### ISSUE THREAD

**Issue by Vsevolod-Shustov** [CleverRaven/Cataclysm-DDA#14542]
It's been randomly happening to me since I moved from 0.C to experimentals. The most surefire way to replicate it is to find slime pit and walk near it. Is there a way to at least suppress that debug message? I'll take not having a monster or two spawn over restarting a game from latest save (which I pretty much must create before walking down every lab level).

**Comment by sparr** [comment]
zip up your save folder in a situation where the problem is about to happen and tell us how to reproduce it from there.

**Comment by Vsevolod-Shustov** [comment]
save: [Green Hill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/68264/Green.Hill.zip)
custom mods: [mods.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/68266/mods.zip)
config: [config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/68268/config.zip)

How to reproduce: Get win sdl 4068. Walk down the stairs. If it doesn't crash, walk around next level for a bit or restart and try again.

**Comment by Vsevolod-Shustov** [comment]
After few test runs (which I really should have done before creating this issue) it looks like it's my mod that kills NETHER with LUA causing crashes. I made it back when blacklists didn't work on overmap and random encounters, so, yeah. Still weird, because it manages to kill these mi-go on surface without crashing the game.
