### ISSUE TITLE
Barefoot speed penalty not shown in interface

### ISSUE THREAD

**Issue by Skidborg** [CleverRaven/Cataclysm-DDA#14546]
The movement penalty caused by running around barefoot doesn't appear to be explained in the interface anywhere.  It shows as increased base movement cost in the @ menu, but doesn't provide any notation as to what is causing it. 

Mystified me for a while earlier before I realized that my shoes had been torn off.  And is probably a stumbling block to newbies who haven't read the wiki.

**Comment by Coolthulhu** [comment]
Any idea where should it go? '@' menu is a bit cluttered.
Maybe it could pretend to be a status, like penalties/bonuses from pain.

**Comment by Skidborg** [comment]
A status effect would make sense.  Or it might go directly in the speed section since that's usually less than full.

**Comment by nanovad** [comment]
Maybe, like pain, it could be both. However, status effects do get cluttered easily. There's enough contrast though that I don't think it'd be a big issue.

**Comment by Leland** [comment]
No movement in years, closing. If there's interest in keeping this open for purposes of discussion/development, please ping me and will reopen.
