### ISSUE TITLE
Allow sprites to specify a vertical shift for later sprites drawn on the same tile

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14550]
If a furniture sprite definition could say "I am 8px tall" then items and characters drawn on the same tile could be shifted upwards 8px, so it's visually obvious they are sitting on the furniture, rather than hovering in front of the furniture in a bad rendering.

**Comment by sparr** [comment]
My implementation concept for this is to allow a tile type to have a vertical offset and alter the whole hierarchy of cata_tiles::draw... functions to return the stack height for the tile instead of a boolean.

This would break the current usage of those functions returning false to indicate they had not drawn anything. Fixing that would require breaking the draw-or-not-draw logic out into separate functions, then calling those functions first before actually doing the drawing.

A more complicated option would be to define a struct `render_result` which would serve as a simple two-tuple of a success value and an offset. The extra complexity would make it a much shorter step to changing the offset from an into to a point, which would allow tiles to have horizontal stacking offsets as well.

Paging @BevapDin @Coolthulhu @kevingranade for feedback before I move forward.

**Comment by sparr** [comment]
A simpler but less elegant solution would be to track temporary rendering state at a higher level in the tiles class, so all the sub-functions could read and write it.

**Comment by Coolthulhu** [comment]
Sounds rather tough and most tiles would look weird shifted.

The struct sounds like a better idea to me.

Or keep the `bool` return value, but add the struct as an argument passed by reference. Then the functions would alter the struct and return `true` if they did anything at all.
That way instead of keeping the stack height (and possibly other arguments) in the outermost function, you could have an in/out argument that would carry all the necessary per-tile data - placement, "shaders" (darkness), stuff already drawn there etc.
This could be impractical in partial redraw, though.

**Comment by sparr** [comment]
Passing the struct down the chain by reference seems viable. And it would enable a lot more interesting rendering stuff in the future, as well.

**Comment by BevapDin** [comment]
> Passing the struct down the chain by reference seems viable. And it would enable a lot more interesting rendering stuff in the future, as well.

If the number of parameters of the drawing functions becomes to large, you can put them into a struct and only pass an instance of that struct around. The struct can be used for input and output parameters.

**Comment by Leland** [comment]
This is obviously a fantastic idea, but discussion's been stalled for years now. Closing – feel free to ping me to reopen if there's interest, or just make a new issue.

**Comment by sparr** [comment]
Odd. I wrote a patch for this. Maybe I never PR'd it? I shall find it and PR it and reference this issue, next time I'm developing CDDA stuff.

**Comment by Leland** [comment]
@sparr awesome, I'm super excited to see that.

**Comment by Chezzo** [comment]
You already did it, @sparr.  My chesthole_iso tileset does it all over the place. 

![image](https://cloud.githubusercontent.com/assets/2432177/26382446/39e1837a-3ffa-11e7-8a5c-a2ba7a2e49e8.png)

**Comment by sparr** [comment]
Oh, ha. I lost track, and couldn't find the PR.

https://github.com/CleverRaven/Cataclysm-DDA/pull/14568
