### ISSUE TITLE
Certain explosives light-able without fire

### ISSUE THREAD

**Issue by Gstayton** [CleverRaven/Cataclysm-DDA#14556]
There's a variety of items that have a fuse, but don't use the need_fire parameter. My guess is that this is due to the remote mods not being being able to ignite them under these circumstances?

Items I noticed skimming through the json:
black gunpowder bomb
RDX sand bomb
ANFO charge

All of them say you light them, but don't require any fire.

**Comment by nanovad** [comment]
Confirmed for all three, build 0.C-8282.
