### ISSUE TITLE
Made an XL holster, thought I'd share.

### ISSUE THREAD

**Issue by scorpion451** [CleverRaven/Cataclysm-DDA#14567]
So I got tired of not being able to holster my modded handguns, smgs, sawn-off shotguns, and laser pistols, so I made a bigger holster that fits guns of up to 12 volume. Has an encumbrance of 7 because it straps to the thigh like a cavalry holster and is used to hold large clunky guns (thats 3 more than a 2.5 liter canteen for comparison). To craft it requires 5 tailoring and 3 pistol skill, and costs three more leather and twice the string as a regular holster, and also requires a hammer and 3 scrap to represent the buckles.
(and is worth every bit of it)

Have no idea how to go about making one of those pull request thingies (and the forum seems to imply it would require wasting more hours on wild Cygwin chases... XP) so I'll just post it here.
[xl holster item.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/70394/xl.holster.item.txt)
[xl holster recipe.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/70379/xl.holster.recipe.txt)

**Comment by chaosvolt** [comment]
Hmm. Would be interesting.

**Comment by Rivet-the-Zombie** [comment]
I like it!

**Comment by chaosvolt** [comment]
Tempted to PR it, if you wish.

**Comment by Rivet-the-Zombie** [comment]
I'd like that, but please give it a *small* ````draw_speed```` penalty as well.

**Comment by chaosvolt** [comment]
Ah, very well. And also doing the usual stylin' for the recipe, and devouring the tabs (delicious). o3o

**Comment by scorpion451** [comment]
I had though about doing the draw speed penalty thing myself, just didn't know the proper invocation for it- I cribbed off the basic holster which doesn't have a draw_cost apparently. (is that unintentional? because the quick draw holster has a draw_cost of 3...) 16 seems about right for the mental image I had of this thing, somewhere between the [old west style "I want to carry my shotgun like a pistol" holster](https://img0.etsystatic.com/008/0/5932296/il_570xN.375849022_1ksx.jpg) and the [modern tactical holster](http://blog.cheaperthandirt.com/wp-content/uploads/2009/09/TornadoTactical1.jpg)

**Comment by mugling** [comment]
> I cribbed off the basic holster which doesn't have a draw_cost apparently. (is that unintentional?

Intentional - when unspecified a default value is used, currently equivalent to `VOLUME_MOVE_COST` however this may later be updated in #14306.

**Comment by chaosvolt** [comment]
And The Mergening has ensued. Hope that having had to shave the volume capacity to 9 was acceptable?

**Comment by illi-kun** [comment]
I think it can be closed since the PR is landed.

**Comment by illi-kun** [comment]
This issue can be closed since the PR #14569 is landed.
