### ISSUE TITLE
Bindist archives contain unnecessary file

### ISSUE THREAD

**Issue by illi-kun** [CleverRaven/Cataclysm-DDA#14565]
Archives available via http://dev.narc.ro/cataclysm/jenkins-latest/ contain file ```astyled_whitelist``` which is not targeted to the end-users, so it should be excluded from the further deliveries.

**Comment by illi-kun** [comment]
@narc0tiq is it possible to fix it?

**Comment by narc0tiq** [comment]
It's in the `data/` folder. [The `Makefile` says the `data/` folder is to be included entirely](https://github.com/CleverRaven/Cataclysm-DDA/blob/9ff25dafbd38870ad3b294f6da23c1f77206bc77/Makefile#L190). This is not a Jenkins problem at all.

Of course it's possible to fix it. Take it out of the `data/` folder or add more junk to the `Makefile` to explicitly exclude it. I'd strongly advise against doing the latter.

**Comment by illi-kun** [comment]
Great, thanks for reply.

**Comment by illi-kun** [comment]
Fixed in #14943.
