### ISSUE TITLE
Possible issue with strength requirements for dragging?

### ISSUE THREAD

**Issue by SeanMirrsen** [CleverRaven/Cataclysm-DDA#14574]
I have here a helicopter-crash-survivor military recruit woman, who can carry 60 kilograms of stuff on her without slowing down.

She is standing next to a garden variety trash can. When the trash can is empty, she can grab it and drag it around easily enough. When 20Kg worth of random stuff is piled into the trash can, she is straining to drag it (as in, can't drag, incurs pain when trying). Inventory is nearly empty for the purpose of testing, just 10Kg total load from clothing. Something seems wrong here.

**Comment by DanmakuDan** [comment]
The trash can has a STR requirement of 5 to move, and items on furniture require 1 STR extra per 4 Kg, from looking at the code.

**Comment by SeanMirrsen** [comment]
I know there's no bug per se, I'm questioning how it's set up. I can, personally, drag and otherwise move around items /far heavier/ than I can carry, let alone lift. Yet here a character can carry 60kg, but just 20kg of stuff inside a plastic bin makes her unable to so much as budge it. This system needs to be revised to make sense.

**Comment by SeanMirrsen** [comment]
Okay, so this might not be realistic as such, but I've consulted the GURPS rulebook on how much weight a character can carry or drag. The stat score values are different of course, but as a general rule, dragging something over a rough surface is as hard as carrying, and a smooth surface means you can halve the weight for the purposes of dragging.

We can't differentiate between smooth and rough surfaces AFAIK, so we can assume that all surfaces are "rough" until further notice, since that's easier. So my character, who can carry 60kg, should be able to drag 60kg of stuff around, or 7.5kg per point of strength. If this is true for the existing system, we have to assume that the plastic trashcan in question (that you get only two plastic chunks from smashing) weighs just shy of 40kg, which seems... excessive.

I think we can start by setting proper weight for all furniture items, and changing the dragging system to work strictly by weight. We can then think of adding modifiers such as smooth or rough surfaces, or whether or not the dragged object has wheels. (GURPS defines the maximum drag weight of something on wheels as 10 times that of something without, halved as well for smooth surface. Which could solve the problem of pushing cars around, I think, as an average-strength character (i.e. mine) would be able to push a car of 1.2 tons if it's got intact wheels and is on a road. Well, half the problem, other half being direction limits.)

**Comment by sparr** [comment]
This should definitely scale and penalize more in line with carry capacity than with the arbitrary pattern DanmakuDan describes.

**Comment by DanmakuDan** [comment]
Some extra information: when dragging a vehicle, each point of STR allows you to pull an additional 25 Kg.

**Comment by SeanMirrsen** [comment]
Vehicles should scale with whether they have enough wheels or not. Insufficient wheels should be as hard to drag as furniture. Enough wheels applies a "weight discount". Whether the weight discount should be the x10 that GURPS alludes to, probably should be discussed.

**Comment by Chezzo** [comment]
Haha, good job @SeanMirrsen, I think we should go to the GURPS rule book for more things. Should I make that a separate issue?

**Comment by Leland** [comment]
Closing due to lack of discussion.
