### ISSUE TITLE
chain_fence_v and chain_fence_h should connect

### ISSUE THREAD

**Issue by hitbutton** [CleverRaven/Cataclysm-DDA#14585]
There are two chain_fence terrains, vertical and horizontal. Both can have rotational/connecting sprites which will orient them as expected. However, the two pieces do not connect with each other:
![image](https://cloud.githubusercontent.com/assets/16194079/11985204/3cc5bf2a-a9ba-11e5-9e3b-1e5e2c75c8fc.png)

This makes it difficult to tile them nicely, as mapgen (power substation, tennis court, etc ) etc generally follows the left hand example.

**Comment by sparr** [comment]
is there a reason for both of them to exist other than to specify a direction for one-tile fences?

**Comment by hitbutton** [comment]
I'm not sure about that.

While discussing it - it would be ideal if they also connected with:
"t_chaingate_o", "t_chaingate_c", "t_chaingate_l" and maybe "t_chainfence_posts".

**Comment by hitbutton** [comment]
This is also an issue with "fence_v" and "fence_h".

**Comment by drbig** [comment]
The whole `_v`/`_h` distinction is IMO a bit silly/problematic. Same thing with player-built windows not aligning properly.

**Comment by kevingranade** [comment]
Yea, these originated in a time when rendering wasn't as dynamic.

**Comment by hitbutton** [comment]
Also an issue with "railing_v" and "railing_h"

I think that's the last of the terrain types with a v/h split.
