### ISSUE TITLE
Crash at world load 0.C-8503 (experimental 4094)

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#14590]
I'm running windows 7 64-bit. The game crashes when loading an existing save and upon creating a new world with no mods, the game crashed upon trying to create a new character, after selecting the world to create it in.
The pop-up is, as usual, generic and unhelpful to most: http://i.imgur.com/sen2pOc.png.

I suspect PR-#14579, I'm going to dl the version prior to this PR and check.

**Comment by Malkeus** [comment]
0.C-8501 (experimental 4093) works just fine.

**Comment by illi-kun** [comment]
This crash happens all time you load your world? If so, can you provide me your save file for this world?

**Comment by Malkeus** [comment]
Hmm... I can't reproduce it on a freshly installed version of 0.C - 8503. It may be something I screwed up on update. I'll close this until I can reproduce it. Sorry illi-kun, you do good work :)

**Comment by illi-kun** [comment]
> Sorry illi-kun, you do good work :)

I agree I broke enough stuff last time ;-)
I'm trying to decrease of effect of this by fixing other bugs...

**Comment by Malkeus** [comment]
It turns out it was changes I had made to my monsters.json and monstergroups.json. I'm trying to figure out what changed and when...

**Comment by Malkeus** [comment]
i traced it to monstergroups.json, but I'll be damned if I can figure out which change is busting it...i'll take this to the forum post I got them from.

**Comment by Malkeus** [comment]
Always watch for those trailing comma's kids...
