### ISSUE TITLE
Can't reload an auxiliary fire mod on a "NO_AMMO" weapon

### ISSUE THREAD

**Issue by scorpion451** [CleverRaven/Cataclysm-DDA#14603]
Just like the title says: if you put an auxiliary fire weapon on a "NO_AMMO" weapon like a UPS powered laser weapon,  it doesn't seem to understand that now it does in fact have something which can be reloaded. (Even when the fire mode is swapped over to the auxiliary weapon.) 
Noticed this after attaching a aux shotgun mod to an A7 laser rifle, and testing confirms the same problem with a grenade launcher.
 
UPS powered weapons which do use some sort of ammo like plasma rifles, and the charge rifle which activates by "reloading", are unaffected. It just seems to be that the check for the "NO_AMMO" flag isn't taking into account attached mods.

**Comment by mugling** [comment]
I suspect this is because `item::has_flag` inherits flags from contained items (which includes gunmods) and the new reload code checks earlier for `NO_AMMO`. I'll look in to this.

**Comment by mugling** [comment]
@scorpion451 I can reproduce your problem and have a fix in 6325a7b. Please could you confirm this resolves the problem for you.

**Comment by scorpion451** [comment]
Not until its committed to the main unfortunately- I'm on Windows 7 64bit, so no compiling or source tinkering with cata for me, unless there's been progress on that front that I'm not aware of.
