### ISSUE TITLE
Body temperature system based on heat conduction

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14605]
Discussion started in #14586, but it is only tangentially related to the PR, so it would fit better in own issue.

Basic idea is to have heat exchange body temperature model, as opposed to current "heat in vs. heat out" model.
The most important difference would be that most "warm" clothing would start protecting from radiant heat of fires and scorching sun, but wouldn't warm up a cold-blooded mutant.

Current model works like this:
- Air temperature is the "base" temperature
- Player's body produces heat based on current body temperature ("Very cold" produces 2x as much as "Very hot") multiplied by how warm is the clothing (note: naked body part produces no heat)
- The above 2 values and windchill are summed up to get the body temperature
- Mutations, hunger, tiredness, effects, fires etc. add to/subtract from this temperature, usually just by a flat value
- Temperature is normalized across adjacent bodyparts
- Finally player's current body temperature is moved in the direction of this calculated new temperature. The bigger the difference between those two, the faster is the change.

Isolation-based model would work like this:
- Player's body produces heat based on how cold is it, on mutations, on tiredness etc.
- Effects such as fire are added to air temperature
- Body heat is compared to air temperature to find out whether is the air heating us up or cooling us down. The magnitude of this effect is scaled inversely with isolation and positively with humidity and body wetness
- Similarly as above, body temperature is compared with unmodified air temperature, for windchill. This time we use wind resistance rather than isolation to scale down the difference.
- We apply those scaled differences to body temperature

Some examples of what would change in-game:
- Nomex gear would protect from high temperatures for a while (by slowing down the exchange) rather than actually producing heat
- Wrapping self in a mountain of blankets would not scorch your skin, but would still cause overheating (most likely up to "very hot"). Unless the survivor was very weak, cold-blooded or otherwise incapable of producing own heat.
- Cold-blooded mutants currently check for ambient temperature, meaning they can be boiling inside and still suffer from cold-blooded penalty. This change would allow them to stop producing body heat above certain value or something like that. They could supplement that with artificial heat sources (heated underwear, fires).
- Naked body parts wouldn't cool down to ambient temperature. This could allow more realistic units.
- Warm wind wouldn't cool down a frozen survivor emerging from an ice lab

But then, balancing all that could be hard. The current system may not work for everything, but it exists already and works for most stuff.
Fire radiant heat could be just hacked around by scaling it down with environmental protection or something like that.

**Comment by Rivet-the-Zombie** [comment]
I like the sound of this a lot.

**Comment by DeadLeaves** [comment]
While clearly it requires some major overhaul of the temperature system. but probably, the big workload is balancing all the items for the new system. However, once implemented, I think it would be a major improvement to one of the bigger flaws with this game. As it is now, heat management kinda sucks. 

One thing to consider would probably be to add inter-body conductivity. Right now you might be overheating everywhere, but you have nothing on your hand and its freezing. Realistically your blood flow evens out your body temperature to a certain extent and would make the game a lot more sensible.

**Comment by hitbutton** [comment]
I'm not sure what the best way to display / communicate the thermal resistance of clothing would be under this sytem.

It should be relatively simple to work out what the current temperature equilibrium would be for your current environment/clothing. But this value would change in different conditions, and would make assessing clothing be less simple than "this hat has 10 warmth so it makes me 10 warmer".

**Comment by SeanMirrsen** [comment]
It probably also bears mentioning that waterproof clothing has a tendency to be punishing in hot environments, because you can't sweat to lose heat. The notion of losing heat by sweating should probably be taken into account as well, so that you lose heat faster if hot than if cold, especially via windchill. And some mutations could prevent sweating as well.

**Comment by Rivet-the-Zombie** [comment]
>It probably also bears mentioning that waterproof clothing has a tendency to be punishing in hot environments, because you can't sweat to lose heat.

This can vary greatly depending on the particular design of the clothing in question. If we're to properly handle it, it would warrant an additional flag to differentiate.

>The notion of losing heat by sweating should probably be taken into account as well, so that you lose heat faster if hot than if cold, especially via windchill. And some mutations could prevent sweating as well.

Good point!

**Comment by chaosvolt** [comment]
Ah, good to see these ideas.

Also? Polyester. I'm wondering how well to handle such a material if it was added. Not very insulating, but less affected by water compared to cotton. My initial assumption was maybe to just slap the WATER_FRIENDLY flag on such items, but you would also expect that flag on wool items, and their behaviors when wet are different.

**Comment by scorpion451** [comment]
Might take the opportunity to factor metabolism into the process: 
For instance one of the advantages of cold bloodedness is that it doesn't burn calories to stay warm, and their metabolism gets slower as they get colder.  Warm blooded creatures need calories to keep the furnace going, and burn through them faster as it gets colder. So a character with Extreme Metabolism might be able to walk around in shorts on level two of an ice lab, but they'd starve in a few hours doing it; a character with Ectothermic would have to be wearing fur-lined everything at the same level, but might only need to eat every few days in the winter.

**Comment by Malkeus** [comment]
A cold blooded creature would need to warm itself somehow,  no matter how
many layers it was wearing. Insulated gear works by trapping heat from your
body, and an ectotherm wouldn't produce any. You would need to warm
yourself up naked by a fire(not strictly necessary, but fastest way to
increase your internal body temperature according to above rules) and then
wear your cold weather gear to trap that heat as long as possible. Or
electric thermal gear. Cold body = slow body = slow metabolism. Ectotherm's
sun themselves to increase their metabolic efficiency also, higher body
temperature lets them get more out of a meal.

**Comment by chaosvolt** [comment]
Though that idea still sounds more fleshed out than the existing "get cold = say goodbye to your speed" system. Possibly harder to manage, but a more fleshed-out insulation system would mitigate that and might make it less hassle in the long run.

Be a snek mutant, eat all the things, sun on a rock for a while...

**Comment by Malkeus** [comment]
Radiant heat from things warned in the sun would be a great mechanic, but I
would settle for lounging by the lava pool or a corpse burn pile after a
good winter gorge. After the food was digested I'd want to find a spot that
was survivably cool and spend the winter reading. Like snakes but with more
book learning.

**Comment by scorpion451** [comment]
Just for the record, the intended inference was that you would be warming up beforehand, and then wearing fur lined everything to slow your transition into a popsicle. X3

One thing that comes to mind on how to do this in a simple and intuitive way is to tie hunger ticks and heat production ticks into the same check, called at more frequent intervals than it currently is (once every half hour, if I'm correctly informed?). That would make it a literal representation of the process within the code. The json entry for each metabolism mutation would have a modifier variable that it applied, representing the ratio of temperature to metabolism rate vs the default metabolism.  
 
Sort of thinking as I type here...
both types would burn calories at the same rate at standard comfortable temperature, which is here considered 65F (also known here in Texas as  "winter" X3)
cold blooded = **v** hunger tick value, **v** temp increase tick value  as outside temp decreases 
warm blooded = **^** hunger tick value, **^** temp increase tick value as outside temp decreases 
The reverse is true as temperature increases.
so maybe something like (pardon the pseudocode)...
```javascript
({outside temp}-{comfortable temp})/{comfortable temp} = {temp modifier}
//{comfortable temp is the game's representation of 65F above absolute zero
//also need to factor in their current body temp, but just hammering out the concept here...
1+{temp modifier}*{metabolism modifier} = {tick modifier}
//metabolism modifier is between 4 (hyperactive metabolism) and -1 (ectothermic) 
// then we convert {tick modifier} into the hunger and temperature ticks
// important bit is having that negative number flip between warm and cold blooded, 
// without needing a whole bunch of if/else statements

**Comment by chaosvolt** [comment]
So basically give mutant players even more reasons to eat NPCs. XP

**Comment by hitbutton** [comment]
Since we're pseudocoding, here's some numbers I banged together to get something working within broadly the same ranges as the current system. Humidity, Wetness and Windchill are ignored.

```
// CONSTANTS
Constant_BodyTemp = 310; // Average body temperature (Kelvin)
Constant_Warmth = 0.015625; // = ( 1 / 64 )
                                                 // Affects quantity of thermal resistance
                                                 // provided by Warmth.
Constant_T = 1; // this constant is an arbitrary number that
                          // affects the rate of temperature change.
Constant_MaxBodyHeat = 38; // Body heat produced is a range, to represent
Constant_MinBodyHeat = 8;    // the body's ability to regulate temperature.
MaxBodyHeat = Constant_MaxBodyHeat * Constant_T
MinBodyHeat = Constant_MinBodyHeat * Constant_T

// ARGS
Environ_Temperature;
Current_Temperature;
Warmth;

// BODY TEMPERATURE UPDATE
Warmth_Coefficient = 1 + ( Warmth * Warmth_Constant );
Current_Temperature += ( Environ_Temperature - Current_Temperature ) * Constant_T / Warmth_Coefficient;

Current_Temperature += min( max( Constant_BodyTemp - Current_Temperature , MinBodyHeat ) , MaxBodyHeat );
```
Any body temperature above or below 310K / 37°C / 98.6°F is feeling cold/warm.
Below 301K / -28°C / 82°F is dangerously cold (Freezing)
Above 317K / 44°C / 111°F is dangerously hot (Scorching)
With these numbers I get the following thresholds at differing levels of clothing Warmth:
```
Warmth    Freezing              Cold             Comfortable             Hot             Scorching
     0  262K / -11C / 12F    271K / -2C / 28F     287K / 14C / 57F    303K / 30C / 86F   309K / 36C / 97F
    10  256K / -17C / 1F     266K / -7C / 19F     284K / 11C / 51F    301K / 28C / 82F   308K / 35C / 95F
    20  250K / -23C / -9F    260K / -13C / 9F     280K / 7C / 45F     300K / 27C / 81F   307K / 34C / 93F
    30  244K / -29C / -20F   254K / -19C / -2F    277K / 4C / 38F     299K / 26C / 79F   306K / 33C / 91F
    40  238K / -35C / -31F   248K / -25C / -13F   273K / 0C / 32F     298K / 25C / 77F   304K / 31C / 88F
    50  232K / -41C / -42F   242K / -31C / -24F   269K / -4C / 25F    296K / 23C / 73F   303K / 30C / 86F
    60  226K / -47C / -53F   236K / -37C / -35F   266K / -8C / 19F    295K / 22C / 72F   302K / 29C / 84F
    70  220K / -53C / -63F   230K / -43C / -45F   262K / -11C / 12F   294K / 21C / 70F   301K / 28C / 82F
    80  214K / -59C / -74F   224K / -49C / -56F   259K / -15C / 6F    293K / 20C / 68F   299K / 26C / 79F
    90  208K / -65C / -85F   218K / -55C / -67F   255K / -19C / -1F   291K / 18C / 64F   298K / 25C / 77F
   100  202K / -71C / -96F   212K / -61C / -78F   251K / -22C / -8F   290K / 17C / 63F   297K / 24C / 75F
```
Warm clothing may be too forgiving in hotter conditions with that formula, and some additional factor should maybe be added to represent it inhibiting the body's ability to regulate heat through sweating.

**Comment by Leland** [comment]
Closing - old and no movement. Feel free to ping me here if there's still interest, or make a new issue.
