### ISSUE TITLE
Persuading NPC to give you equipment also increases your trading Credit with them

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#14619]
Start a new game with fellow NPC
Ask him for giving you some equipment
Take the gift
Trade with him
???????
Profit! No, really, see some strange "profit" sum for nothing.

![11111111111111111](https://cloud.githubusercontent.com/assets/11132525/12005539/50779b8a-abbb-11e5-91ca-de9d64d9d8ab.png)
Win 10, 0.C-4103, tiles.

**Comment by mugling** [comment]
Confirmed

**Comment by chaosvolt** [comment]
And now that ancient song is stuck in my head. Thanks for that.

**Comment by Chezzo** [comment]
You can also break down a bench and sell the 2x4s for around a hundred bucks each.

**Comment by elricsfate** [comment]
@Chezzo 

Each 2x4 itself is worth a hundred bucks each? That's insane!

**Comment by Coolthulhu** [comment]
This should only happen if the given item has negative price. Negative prices were fixed a while ago. Does this still happen? Any reliable way to replicate?

**Comment by Night-Pryanik** [comment]
As for 0.C-4417 the bug still exist. Manual in first message of this issue is working.

**Comment by Vidiveni** [comment]
Nowadays this bug has it the other way around. Trades after the gift will "cost" the value of the gift.

**Comment by Leland** [comment]
Discussion's been stalled here for a few years. Closing. And according to @Vidiveni's note, it might be worth opening a new issue.

**Comment by Night-Pryanik** [comment]
Reopening, bug is still here, reproduced it a few days ago.

**Comment by int-ua** [comment]
Still relevant. May I suggest the title be changed to something like "**Persuading NPC to give you equipment also increases your trading Credit with them**"?
