### ISSUE TITLE
[Build 4073] Ammo disappears during "move all" to dragged container in AIM.

### ISSUE THREAD

**Issue by SeanMirrsen** [CleverRaven/Cataclysm-DDA#14610]
I have a bit of a technical issue (data plan running out) preventing me from checking the latest build for this behavior, but besides one PR that seems to fix something relevant I don't really see anything that would have fixed it since then. Submitting for checking, as well as, if necessary, fixing.

In short: When moved via AIM, from "`A`ll" locations, to "`D'ragged" container, ammo (and batteries, etc), completely disappears.

In long: There is some inconsistency to how it happens, as I've been able to *at times* to get it to work without the bug, but it is not random so much as it seems to require particular circumstances. I've tested various combinations of multiple source tiles, multiple source tiles, source tiles containing furniture and not, etc, the only common variable is that "Move All" is used with the destination set as the dragged container. Notably, the "moving all" of one stack of ammo results in three messages simultaneously - two for "you put the item in the box", one for "you put the item on the carpet", and (since I'm playing in ASCII) the box tile inverts to show that the item is there, and then immediately reverts back as the item disappears *after* being moved.

I could be speculating all day here, so I'll just provide a save and let people with code access take a look at what's actually happening.
https://dl.dropboxusercontent.com/u/4152380/Lyons%20Plain%20%28ammo%20box%20bug%29.zip

Replication: from where you're standing after you load the save, just open AIM, select the right half as `D`ragged, select left half as `A`ll, press `,` to 'move all' from A to D.
(good thing I had the save backed up from reporting another issue. I seem to be having a lot of them with this character. XD)

**Comment by Totentag** [comment]
I can confirm this bug is still occurring in v.4099 at this time. Notably, the bug did NOT occur when moving all to the tile containing the vehicle, but did occur when moving to the 'D'ragged item.

**Comment by DanmakuDan** [comment]
Btw, the move-all function starts in the southwest corner, moving to northeast. If there is a problem with the logic determining which square is being moved, when the location overlaps with the vehicle, items with a quantity will be erased (like ammo). If your vehicle sits in the southwest when you move all items, you can kind of avoid the bug.

**Comment by mugling** [comment]
@SeanMirrsen can you confirm #14612 resolves this for you?
