### ISSUE TITLE
"There's a something in the way" needs to be rebalanced

### ISSUE THREAD

**Issue by nanovad** [CleverRaven/Cataclysm-DDA#14625]
When closing a door, I got this notification: "There's a \. sweatshirt in the way that is too big to just nudge out of the way."
I think I can nudge a sweatshirt out of the way with my foot... I'm assuming there's something wrong with the calculations, else there isn't handling for actually nudging items. Either way, this should be looked at - it's bothersome to use the AIM every time I kill a zombie in a doorway.

**Comment by chaosvolt** [comment]
How many other items are in the same spot? It seems like when the total amount of crap in a doorway is just barely over the limit, it seems to single out an item instead of the generic "too much crap in doorway" message that appears when even more stuff is in the way.

**Comment by nanovad** [comment]
About 8, I killed a zombie which dropped clothes some food and a corpse.

**Comment by sparr** [comment]
I think @chaosvolt has it right. The corpse was the real problem, but it was unhelpfully reporting the last item in the square.

**Comment by chaosvolt** [comment]
Hmm. So we might have to ensure the code points to the heaviest object, assuming that's the only object preventing door closure.

**Comment by Night-Pryanik** [comment]
Did #15548 fix this issue?

**Comment by Coolthulhu** [comment]
The problem is not the display, it's the fact that you can't close the door with small items in the way.

**Comment by Night-Pryanik** [comment]
Well, looking at the code, it seems that one can't nudge item with volume > 10 or items with volume > 10 in sum. Maybe just rise this limit? Pair of knee-high boots, for example, has volume 15. I'm sure that one is perfectly able to nudge them out the way.

**Comment by Mshock777** [comment]
Maybe make it depend on weight instead?

**Comment by kevingranade** [comment]
I don't see an argument here, just that a particular value doesn't "feel"
right.
"it's bothersome to use the AIM every time I kill a zombie in a doorway" in
particular is precisely what is intended with this feature.
