### ISSUE TITLE
Sawing down and porting barrels

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#14629]
We currently have `shortened barrel`, `ported barrel` and `barrel extension` gunmods. I'd like to change these to be intrinsic (and therefore permanent) characteristics of a weapon and applicable concurrently (eg. shortened and ported). Barrel extensions would change to the `muzzle` slot.

For example
`hacksaw + gun = gun (short) + pipe`
`drill + gun = gun (ported) + scrap metal`

How should these changes be displayed by `item::display_name` and other functions?
How would we handle migration for existing saved games?

**Comment by Coolthulhu** [comment]
> How would we handle migration for existing saved games?

You could just add a flag that prevents removing those mods, essentially making them "become in-built". There should be a warning message when installing those, though.
I think this flag already exists, but it may need some extra adjustments to work correctly with installable mods.

**Comment by DeadLeaves** [comment]
I don't think that will work, as the built-in mods needs to be defined when the weapon is made. (It's a separate json-field)
>built_in_mods

**Comment by Coolthulhu** [comment]
Yeah, but they all have "IRREMOVABLE" flag, which is checked for in all relevant code.
In fact, the in-built mods section is handled in the same way as default mods, except that the in-built mods get IRREMOVABLE flag inserted while default ones are just added without it.

**Comment by DeadLeaves** [comment]
Yes that is correct.

On another note. I don't know how github works really. Are the edits I made invisible?

**Comment by Coolthulhu** [comment]
> I don't know how github works really. Are the edits I made invisible?

It doesn't always reload properly. I see them now, but didn't see them when I commented.

**Comment by DeadLeaves** [comment]
I actually realize that using the ```IRREMOVABLE``` flag  will add the ```[Integrated]``` text to the mod, regardless of whether it's in a gun or not.

**Comment by Coolthulhu** [comment]
And it could prevent the mod from spawning anywhere.

It could be hacked around by having a "becomes irremovable" flag, which would turn into proper IRREMOVABLE on apply.
Or by getting rid of itemized barrel mods and just having them inserted by iuse of relevant tools.

**Comment by Shadefang** [comment]
While this makes sense as a recipe for crude versions of ported and shortened barrels, a long barrel would most definitely a removable mod. The only way it would work effectively is if you're swapping out the whole barrel, and if you can do that in one direction you can do it in both. Swapping out a barrel is relatively easy if you have  the barrel already, and fitting a barrel to a gun, while not particularly easy, is well within what a cataclysm character could do.  Note that this is already a large part of what you'd be doing with the ammo type conversion kits. The main restriction on whether or not you could put on an extended barrel is if you have one of the right caliber. Moving forward, if extended barrels are still a thing taking this into consideration, there's little reason you couldn't find equivalent ported or shortened barrels that _could_ be swapped out.

On another topic, what would the reasoning behind moving the extended and shortened barrels to the muzzle location? There's no reason you shouldn't be able to mount a mod on the end of the modified barrel.

**Comment by Rivet-the-Zombie** [comment]
>On another topic, what would the reasoning behind moving the extended and shortened barrels to the muzzle location? There's no reason you shouldn't be able to mount a mod on the end of the modified barrel.

A very good point.
