### ISSUE TITLE
Misleading "Out of ammo type" messages

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14630]
Reloading an item partially loaded with named ammo prints name of the ammo type, even when a specific type is expected.
For example:
* Load wooden needle with plant fiber below its full capacity
* Have thread in inventory
* Try to reload needle
* "Out of thread" even though there is thread in the inventory, just not of the specific type (plant fiber)

**Comment by chaosvolt** [comment]
Wait what?

I thought tools where ammo-blind? When did that get changed? ;w;

**Comment by Rivet-the-Zombie** [comment]
I'm not sure, but it means that sewing kits no longer transmute sinew/plant fiber into thread, so I'm fine with that aspect of it.

**Comment by chaosvolt** [comment]
Odd, as last I checked (build 4-thousand...something) I could've sworn ammo still got loaded together the way it used to. o.O

Personally it seems to me like allowing the tool to load multiple ammo of the same type, but being able to track the loaded quantities separately (while still looking at TOTAL capacity for the sake of consuming charges and reloading) would be the ideal, but most complex, way to go.

**Comment by chaosvolt** [comment]
Aw fuck. You're right, some maniac broke tools so now it can't be loaded with mutlple sorts of the same ammo type.

Is turning sinew into thread really that big a price to pay for being able to actually USE my disparate assortments of thread? This plus having any repairs drain constant amounts of thread might make innawood characters a bit impractical given you'll be juggling sinew and plant fiber, and maybe scavenged thread.

**Comment by mugling** [comment]
> I'm not sure, but it means that sewing kits no longer transmute sinew/plant fiber into thread, so I'm fine with that aspect of it.

> Aw fuck. You're right, some maniac broke tools so now it can't be loaded with mutlple sorts of the same ammo type.

The intention of both the previous and replacement code was to prevent transmutation of ammo. The new code is however more strict about this resulting in the above message (which could easily be changed).

> Personally it seems to me like allowing the tool to load multiple ammo of the same type, but being able to track the loaded quantities separately would be the ideal, but most complex, way to go.

The new magazines implementation I'm working on will eventually support this with magazines storing (possibly varying) ammo as contents. We should be able to support for example realistic tracer ammo.

> Is turning sinew into thread really that big a price to pay

Likely the price would be subtle bugs, for example your reloaded 223 just became 5.56 NATO. If there is a UI/usability problem with tailoring we should try to solve it at that level rather than as a special within the reloading code.

**Comment by chaosvolt** [comment]
> Likely the price would be subtle bugs, for example your reloaded 223 just became 5.56 NATO. If there is a UI/usability problem with tailoring we should try to solve it at that level rather than as a special within the reloading code.

Um. Excuse me? Guns used to be ammo-specific, whereas tools used to be ammo-blind. So something in these tweaks made a problem where there wasn't one. >.>

**Comment by mugling** [comment]
@Coolthulhu I've changed the message where a specific type is expected in 64d43b7

> Personally it seems to me like allowing the tool to load multiple ammo of the same type, but being able to track the loaded quantities separately (while still looking at TOTAL capacity for the sake of consuming charges and reloading) would be the ideal, but most complex, way to go.

@chaosvolt We already have `item::ammo_capacity()`, `item::ammo_remaining()` and `item::ammo_consume()` so we only need to write `item::ammo_load()` and then it should be reasonably practical to implement the above.

**Comment by chaosvolt** [comment]
But again, your changes to gun handling of ammo was extended to tool handling of ammo. Was that intended? :V

**Comment by mugling** [comment]
Yes, items that are reloaded with ammo are (with a few limited exceptions) handled via the same code. In the future I would like to separate the handling of electrical power but that's very much a long term goal.

**Comment by chaosvolt** [comment]
Ah, I see. Guess it makes sense, but considering transmuting most tool ammo is less severe than transmuting bullets, it might've been worth not altering tool properties until after the ability to mix ammo was implemented. ._.

**Comment by mugling** [comment]
The previous code is a twisty maze, so short of throwing everything out and writing a huge (and likely unmergeable PR), we are unfortunately stuck with piecewise refactoring. Incidentally the next step in the puzzle will be reloading from the ground or adjacent tiles in `item::pick_reload_ammo` which is itself waiting on #14600.

**Comment by chaosvolt** [comment]
Hmm. Does make sense, yeah. ;w;
