### ISSUE TITLE
Re-add PageUp & PageDown for menu scrolling

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#14647]
I am not sure if this is where I am supposed to post suggestions, I just did it because I saw someone else do it. If I am not supposed to; please inform me. Also feel free to respond, I am more than happy to argue and bounce ideas in a mature way.

Anyhow, until a few weeks ago you were able to scroll in menues with PageUp and PageDown, however this was removed to improve consistency, or at least that's what I assume.

I just find it odd that scrolling a menu requires you to hold the shift key and pressing a button located in such an unergonomical position, instead of just using the two perfectly fine keys located just above your right hand. No drawbacks, and a big plus. 
As a person who often play on my laptop while lying in bed (Sweden is cold, don't judge me), it's a pain having to stretch my hand in that weird angle.

Wouldn't simply turning all "<" into "PageDown" and all ">" into "PageUp" be a much better way of adding consistency? Maybe even have a toggle option for this in the settings for those who don't like it? :)

**Comment by SeanMirrsen** [comment]
I would say that the keybinds for that are remappable, but I could not find where they are for scrolling specifically. One thing I would like to comment on, in that light, is that there isn't a centralized list of ALL keybinds, that could be accessed, reviewed, and rebound in one place.

And I'd also like to say that, for laptops without a numpad also, PgUp/PgDn are much better for scrolling than `<`/`>`, because you can hold down the `Fn` key and scroll with the arrow keys without having to shift your hand to a different part of the keyboard when navigating lists.

**Comment by harald921** [comment]
On my laptop I even have the Page Up and Page Down above the left and right arrows. And on my desktop Page Up and Page Down are located just above the arrow key section, so I could very comfortably use them quickly and easily, with no need of using two keys just to move in a direction. It would be interesting to see if anything will happen with this.

**Comment by kevingranade** [comment]
I agree with the gist of what sean said, the bug is that these can't be remapped (if that's the case, I haven't checked).

**Comment by remyroy** [comment]
The original discussions that lead to removing Page Up and Page Down for changing menus: #14209 and #14257.

**Comment by harald921** [comment]
Would it be possible to create some kind of alternative or workaround? I think most people can agree having to use Shift + <key> simply to move in a direction, especially considering how the said keys are located on a normal keyboard, is kind of lame. Is it possible to let the user choose what keys are used for menu scrolling, letting him to input his own keys assuming PageUp and PageDown simply would be too bothersome? Honestly, anything is better than the current system. In my opinion that is. :)

**Comment by illi-kun** [comment]
Particular case of #12112.
