### ISSUE TITLE
[Suggestion] Add rubber material  

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#14643]
Thinking about adding rubber. Like when you break down rubber things like tires, rain-boots and hoses you get scrap rubber instead. It could open up some new items to craft and some items to need new ingredients (like firearm waterproofing). Also we could have it be a requirement to patch up tires. Instead of using the welder you could use a piece of scrap rubber or something like that. Just a thought.

**Comment by illi-kun** [comment]
As a possibility, you can start creating new items / receipts with existing plastic material  as temporary placeholder and then replace it by rubber (when critical mass of items will be achieved for this splitting).

**Comment by harald921** [comment]
Got me thinking a bit - wouldn't it be cool to be able to smelt things down to improve ease of transport? I mean yes, you can rip some boots to plastic chunks or counter into scrap metal but wouldn't that be a mess to transport? Wouldn't it be cool to be able to smelt scrap metal into a large and heavy metal bar that would be considerably easier to transport than all the metals it was worth? Make a large block of plastic? Make a bale out of cloth rags + long strings?

**Comment by chaosvolt** [comment]
A suggestion of this sort has been suggested before, yes.

Another possible use would be adding a latex allergy, but that alone wouldn't work well as there aren't many rubber items to wear.

Extending it to things like siphoning fuel would be more complex and a pain in the ass for players, unless we instead allowed the player to do so at the cost of some irritation later on (and ADDITIONALLY add plastic hoses as an alternative).

As for other uses for rubber, I'm unsure. Could be interesting.

**Comment by Cyrano7** [comment]
I've thought of some more. Having rubber be a requirement for making shoes. Like 1 scrap for shoes, 2 scraps for boots. Chance of getting some on disassemble. And makeshift tires, made from scrap rubber and wire.

**Comment by chaosvolt** [comment]
Depends on what style of shoe you're making, and whether historically used alternatives exist. o3o

**Comment by Cyrano7** [comment]
True. I was more referring to modern shoes.

**Comment by chaosvolt** [comment]
True, though that does present the possibility of alternative materials in addition to rubber, while still allowing the general idea of a sole represented in the recipe.

Maybe wouldn't want to add rubber to the boot's materials list though, in case we add latex allergy.

**Comment by Cyrano7** [comment]
I think that it would only be added to the rain boots. Including it in the recipe as the sole element wouldn't warrant the rubber material label on it.
@chaosvolt On a side note did you see my last edited comment on https://github.com/CleverRaven/Cataclysm-DDA/pull/14638

**Comment by chaosvolt** [comment]
There are also rubber boots and gloves and a handful of other items that might warrant it, but to make an allergy trait worth adding more involved mechanics will be needed.

**Comment by Coolthulhu** [comment]
Latex allergy sounds like a -0.1 point trait and as such is not too likely to become a thing soon.

Though I don't really see the point of separating plastic from rubber.
Would rubber even be workable with the post-apocalyptic tools?

**Comment by Cyrano7** [comment]
@Coolthulhu  Rubber can be molded or cut to fit to make soles of shoes. Tire patches are just pieces of rubber really. Hoses, gaskets, rubberized fabric. It would be do-able if you know what your doing. We have some pretty complex metal working already.

@chaosvolt @Coolthulhu Id have to agree about the latex allergy. Having it be a starting trait would be a free point. You could always throw it in as a non starting low chance mutation though. Like for the elf or medical.

**Comment by chaosvolt** [comment]
True. It would depend largely on how fleshed out the effects would be.

**Comment by kevingranade** [comment]
[Citation needed]
I'm very skeptical that rubber is as easy to work with as you indicate, and
for a number of your examples it would not produce seamless results.  e.g.
replacing a shoe sole with a "chunk of rubber" is going to have a big
impact on performance.
There are certainly a number of things you could reasonably do with it
though, tire sandals, tire armor,or incorporation into recipes that use
chunks for stiffening or armor make sense.

**Comment by Malkeus** [comment]
I've worked with tires. They aren't made with just rubber and metal,
there's nylon belts forming the casing, steel bands form the bead,
interwoven steel wire belts under the tread abs the rubber used in the
tread has special additives, like silica and wax, to increase weathering
resistance and grip.
I have my doubts about anything a survivor built by hand being viable. I've
always considered 'repairing' a broken wheel to be simply swapping out a
flat tire/damaged rim for a good one. And repairs to a damaged wheel were
just melting a bit of rubber and smearing it around til the leak stopped
(inadvisable irl, but doable) or welding on a bit of metal to shore up the
rim. Inflation of the tire was just ignored fir the sake of simplicity and
tedium removal.
Ingame, we don't simulate air pressure or vibrations from an imbalanced
tire. Building a rim is fairly straight-forward sand casting, if you ignore
the coatings and heat treatment; building a tire involves multiple stages,
including a vat of molten rubber, a giant mold with hundreds of
injectors,huge tanks of water to check integrity and large and sensitive
machines to check balance. I'm not saying it can't be done, but the result
will not be viable at high speed without a lot of industrial machines.

Objections to making tires aside, making things FROM tires is pretty easy,
you can cut rubber with a sharp knife, the steel belts succumb to a sawzall
easily. With a bit of buffing and just enough vulcanizing rubber cement,
you can make rubber on rubber connections. Melting the surface of a piece
of rubber til it bubbles but does not burn will let you  adhere it to
cloth. It can be sewn to things with a very heavy gauge needle and thread
(or by burning holes in it with a hot nail). It's not flexible, light or
fun to work with though (stinks).
I think the soldering iron would let the survivor do quite a bit with an
old tire.
[Citation needed]
I'm very skeptical that rubber is as easy to work with as you indicate, and
for a number of your examples it would not produce seamless results. e.g.
replacing a shoe sole with a "chunk of rubber" is going to have a big
impact on performance.
There are certainly a number of things you could reasonably do with it
though, tire sandals, tire armor,or incorporation into recipes that use
chunks for stiffening or armor make sense.

—
Reply to this email directly or view it on GitHub
<https://github.com/CleverRaven/Cataclysm-DDA/issues/14643#issuecomment-167808251>
.

**Comment by chaosvolt** [comment]
As I suspected. Making our own tires would be right out, but finding additional uses for a worn-out spare seems a bit more feasible. Though again, whether the idea of adding rubber has merit overall would depend on how MANY plausible uses are available.

...said by the derpdragon that added copper with a deficit of good uses for it. ;w;

**Comment by Malkeus** [comment]
Kevin covered a few, sandals, armor, reinforcing clothing. More: vehicle
bumpers - for taking hits (without damaging either the vehicle or the thing
run in to), vehicle seats- (ever seen an old tire turned into playground
equipment? Same concept.), water proofing clothes, rubber washers and
gaskets for appropriate recipes (water faucet, fuel tanks, flame thrower,
for starters), fuel for fires(stinky, but effective), more to follow...

**Comment by chaosvolt** [comment]
Bumpers, that sounds like an interesting idea. Do wish we had more options coding different ways that armor-type parts could function. Shocks from Vehicle Additions Pack would be interesting if they performed in a more sensible way, and a padded bumper would likewise be interesting.

Also? Tire armor. I can see that being hilarious.

![Raider armor is less derpy though](http://vignette1.wikia.nocookie.net/fallout/images/2/28/FB8_Khan_Tire_Armor_concept_art.png/revision/latest?cb=20100125113728)

**Comment by Malkeus** [comment]
Lol, that's fantastic. It's pretty much exactly what I was picturing,
except the legs were wrapped in pieces of wheel barrow tire. Did you draw
that, it's great :)

more ideas: a polearm weapon with sections of tread with the cut sections
facing outwards. The exposed steel cord is great for shedding flesh...we
called the pieces of tread semis drop in the highway 'gators' due to this
fact. Also they tended to flop around unpredictably when you move them, and
would occasionally 'get' you. Good times, many scars were had.

Water-containers - tires hold a lot of water just when left outdoors, one
could use the casing (the airtight balloon the tread is grafted onto) to
make a fairly light container.

Floor covering - water proof, easy to clean and quiet to walk on(unless you
have wet shoes). Also window covering, a good seal at the edges would leave
it airtight, could be melted into position as well.

**Comment by chaosvolt** [comment]
Pbbbt. I wish I could draw that well. Was linked from the Fallout wiki, of concept art pertaining to the first game.

Also on the idea list, I recall large truck tires also being re-purposed for gardening, though given the availability of dirt, it wouldn't be that useful to add planting containers unless growing indoors or on a paved courtyard.
