### ISSUE TITLE
Spare magazines don't work

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#14642]
When you try to reload a weapon's spare magazine you get told that it's already fully loaded.

1. Attach spare magazine to a firearm
2. (r)eload it once
3. Attempt to (r)eload it again
4. 'Your x is fully loaded!' but your spare magazine is not

I think it was busted in #14623

**Comment by mugling** [comment]
Can reproduce and have fix

**Comment by mugling** [comment]
@sick-trigger thanks for the concise bug report. Please let me know if 2448408 resolves it for you?

**Comment by sick-trigger** [comment]
@mugling yep that did it, cheers
