### ISSUE TITLE
Turn rock tile into dirt

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#14645]
I am actually unsure whether or not this is a bug. Anyhow, this is how I did:

1) Pull chair onto rock tile (This was a house cellar)
2) Set it on fire
3) Make a digging stick
4) "Dig pit" on the ashes  of the chair after it finished burning (I tried to get rid of the ashes)
5) Turn the pit into a mound
6) Turn the mound into normal dirt

Rock floor -> Dirt floor

Bug or intentional? Seems weird imo. Oh and btw, the ashes are still there but that's not a bug :P

**Comment by kevingranade** [comment]
Bug/limitation of the terrain system.
