### ISSUE TITLE
wall connection to solid rock

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#14650]
In mapgen, terrain with the autowall flag will connect to any wall, including solid rock. That means at the edges of labs, the outer wall has a distinct 'double wall'  look. Right now that's not a big deal, but if there are changes to make labs more maze like, that will spoil some of the exploration.

It would be good "no connect" flag that could be put on solid stone.

**Comment by kevingranade** [comment]
Or a wall type with the desired behavior on the lab side, adding this flag
to every possible terrain type that might be on the other side of a lab
wall is error prone and is likely to cause unwanted side effects.

**Comment by hitbutton** [comment]
Making t_rock not connect to things would also affect doors/windows in locations made of t_rock (churches/basements).

But I agree its odd that you can see connections on non-visible sides of walls. It's strange to walk past the outside of a building, and be able to see the positions of the inner walls.

**Comment by SunshineDistillery** [comment]
Yeah, some type of buffer wall would also be fine. 

I think using solid rock to make buildings is silly. It would be better to make a new type of wall called cut stone or something. Even basements should have cement walls/floors. That's a different issue though.

**Comment by Leland** [comment]
Discussion's been stalled here for a few years – closing.
