### ISSUE TITLE
Tile disappears when curtains torn down

### ISSUE THREAD

**Issue by DeadMate** [CleverRaven/Cataclysm-DDA#14656]
The window without curtains creates a strange glitch. 

![Image of Yaktocat](http://i.imgur.com/7BL7xTs.png)

Discussion - http://smf.cataclysmdda.com/index.php?topic=11862.0

**Comment by hitbutton** [comment]
That's just because the chesthole tileset doesn't currently have a tile for "t_window_no_curtains". Chezzo posted in the linked thread saying he's going to add one.

**Comment by chaosvolt** [comment]
Wow, I'm actually ahead of Chezzo for once, in one regard? What a surprise. o3o

**Comment by Chezzo** [comment]
It is in now.

**Comment by chaosvolt** [comment]
Nice. <3

**Comment by DeadMate** [comment]
Fixed really fast. Thanx, Chezzo!
