### ISSUE TITLE
Picking up stackable items doesn't show the volume increase from completing a stack.

### ISSUE THREAD

**Issue by DanmakuDan** [CleverRaven/Cataclysm-DDA#14653]
For example, if 5 first aid kits are dropped on the ground, picking up 3 kits followed by 2 kits does not show your resulting volume correctly on the pickup menu. This can cause the player to drop some items if they were on the edge of their volume limit once the items are in your inventory. Picking up all 5 at once shows the volume increase in the pickup menu.

**Comment by illi-kun** [comment]
I think it was fixed in #15585.

BTW, maybe the referenced fix causes #15728, but I'm not sure about that.
