### ISSUE TITLE
Noise from below covers player

### ISSUE THREAD

**Issue by Sternenfisch** [CleverRaven/Cataclysm-DDA#14665]
In the newest build I noticed that walking over a region with noise from below causes the players @ to be covered by the yellow 'v' which are indicating sound.

This is rather easy to replicate, just take a character into a melee over the caves of a slime pit. 1 out of 3 turns the players @ will be covered with yellow 'v' so its impossible to tell where one is. 
Even more annoyingly, this can happen again even when you move, leaving you to look really sharply and guess where you actually are.

As much as I'm happy with sound and z-levels, this cant be a feature. Players @ field should always be excluded from displaying 'v' on top of it, unless its the only sound around. If there is more than one sound 'v' around, there is no reason to show one on @ position as well...

**Comment by SeanMirrsen** [comment]
Stuff like that is why Dwarf Fortress has blinking and alternating tiles. It could probably be just made to have the player tile on top of all others as a stopgap solution, but something to more comprehensibly show when a thing is in the same place as another thing of a different kind would be ideal here.

**Comment by Sternenfisch** [comment]
Yeah for sure thats why alternating blinking tiles are nice. However all that needs to be done as I see it is to remove the noise marker from the field the player (and potentially any monsters) are standing on. That way melee's over noise sources underground are at least not made into guessing games as to who is where.
