### ISSUE TITLE
Spilled liquids can be consumed

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14666]
* Debug spawn a liquid, say vodka
* Drop it
* 'E'at it off the ground, like some sort of a (party) animal

**Comment by Rivet-the-Zombie** [comment]
On one hand I want to just say 'yep, that's a bug' but on the other hand I feel that this should be possible in some limited fashion - if one is desperate enough, licking spilled stuff off the floor should be a possibility.

**Comment by Coolthulhu** [comment]
It would have to be a really smooth floor for it to work.
I could see it being used in three situations:
* Breaking vending machines, then drinking the spilled drinks
* Collapsing bank ceilings on safes, removing the rubble then drinking the spilled purifier
* Dying zed dropped some hydrogen peroxide in a glass bottle, then boomer broke it. Survivor then rubs own infected wound over the spilled h2o0 to disinfect it

I just tested the last one because I had to be sure if it really works. It does.
I should make a list of the most hilarious bug somewhere or I'll forget them.

**Comment by kevingranade** [comment]
If you want to code up whether a particular floor will cause liquid to
puddle instead of soak in, feel free,otherwise it's a bug :)

**Comment by sparr** [comment]
Non-alcoholic liquids consumed or used from the floor should have a high chance of producing food poisoning (or some more appropriate effect if we have one?)

**Comment by sparr** [comment]
Could we re-use the skate-friendly flag (ROAD, I think?) to control puddle-forming?

**Comment by Coolthulhu** [comment]
I'd say that consuming liquids off the ground should be strictly forbidden for all types of floors.
The only sensible reason for puddles I can think of is interaction with fire - gasoline fuels it, water kills it.

**Comment by scorpion451** [comment]
What if it just vastly lowered enjoyability and had a chance to cause food poisoning? 

Like Rivet, I've always mentally justified it as my desperate survivor licking water/soup/booze off the ground. You aren't going to ever get it back in the bottle, no, and it isn't going to be pleasant, but if you're desperate enough it's totally something you could do in real life. There are times when the pragmatic "thinking" part of the mind and the instinctive "must survive" part just nod at each other and shut off the "eww, its on the ground!" part.

Doing the negative-enjoyability-and-contamination thing would make it similar to having the option to eat rotten food: you can do it, yes, but that doesn't make it a good idea...but the option is still there if you're really desperate.

**Comment by Zireael07** [comment]
Negative fun and food poisoning chance sound like good ideas.

**Comment by Coolthulhu** [comment]
> Fluids spilled on the ground don't just disappear, even in dirt. They just get a lot less consumer-friendly.

If it's on pavement, it may as well disappear. It's within the cracks and there's no retrieving more than the taste of it.
Getting it from dirt would require eating said dirt.

And in case of purifier, it won't even be on dirt - it will be buried in rubble or within the cracks of the floor.
To get a single dose worth of purifier from the ground, you'd need to spill 5 or so of them first.

Going back to as it was before - not allowing using spilled purifiers, drinks and the like - would be both easier to handle and more sensible.
Maybe an exception could be made for thick soups and stuff like ketchup - those could be licked off the floor by someone desperate enough.

**Comment by scorpion451** [comment]
>Getting it from dirt would require eating said dirt.
Exactly. Hence the chance to become violently ill, contract parasites, whatever else one can think of. But thanks to people with [geophagia](https://en.wikipedia.org/wiki/Geophagia) we know that eating dirt isn't going to kill you in and of itself. Might even be healthy in some cases (trace minerals).

Also agree with all the above points in general, just not on the conclusion that the current handling is a flaw. It just needs a dose of reality.
Pavement- I'd call 50/50 on the chance for it to pool. There's all sorts of different types of pavement- some drain well, some don't, and even on the same road some places get sealed better than others. Same thing for rubble- clear it away and see if it pooled underneath rather than splattering everywhere.
Concrete, rock, metal, and tile would be optimal. Lots of water-tight grooves for stuff to pool in. My cats can confirm that things spilled on concrete and tile floorings pool very well and can be lapped up while your owner yells at you and runs for a towel. 
Wood floor... also depends on what sort; tightly joined modern wood floor over concrete, or drafty old flooring you can see through? 
Stone floor- same thing; solid stone like a mineshaft? Large pavers sealed with concrete? Loosely fitted bricks?
Carpet- it's gone.
Dirt- how desperate are you?

**Comment by Malkeus** [comment]
I have to disagree on the carpet. I spent most of yesterday vacuuming water
out of my basement, the carpeted section retained about 50 gallons of water
even after the sump pump came back on drained out the standing water. I
imagine if someone was desperate they could have sucked water out of the
carpet, the same way one would suck water from a sponge. It's certainly no
worse than eating dirt to get the liquid contents.

**Comment by chaosvolt** [comment]
The best ways to drink booze are ever the dwarven way (either straight or of the barrel, or only in mugs), or the...I guess kobold way, that sounds like a kobold way to do things. :V

**Comment by Malkeus** [comment]
In adventure mode, i get the majority of my fluids by licking them off my
own body...I always seem to be covered in SOMETHING drinkable n it hardly
ever kills me.

**Comment by chaosvolt** [comment]
> In adventure mode, i get the majority of my fluids by licking them off my own body...I always seem to be covered in SOMETHING drinkable n it hardly ever kills me.

I've noticed that no longer seems to solve thirst as of DF2014. ;w;

**Comment by harald921** [comment]
If you can drink directly from a toilet, I believe it should be possible to drink directly from a floor.. With morale being affected, and also risk for sicknesses and nasty stuff. *Just scrolled down to say this, haven't read through entirely*

**Comment by Malkeus** [comment]
@chaosvolt I've avoided upgrading to 2014 since it runs really slowly on my cruddish pc. Maybe I'll get a new one this year.

**Comment by chaosvolt** [comment]
Aw. It hasn't really seemed that laggy compared to DF2012, in most cases. Now adventure mode, if you go near a dark fortress or a dwarven fort...yeah. You're hosed. o3o

**Comment by Malkeus** [comment]
I tried it of course, but it's unplayably slow, just trekking across barren wilderness in adventurer mode is painful, and in fortress it starts to enter 10fps speeds after about 15 dwarves, worse if there is a lot of water on the map. It was entertaining finding ways to murder migrants without undue morale loss, but it lost it's shine real quick. Someday

**Comment by chaosvolt** [comment]
Ouch. When even my potato of a 2009 PC can manage DF better, that's a bad sign. Sorry to hear.

In any case, to get us back on topic...I do agree that yes, whether it should be possible to drink a spilled liquid will need to be dependent on the surface, if we allow it at all.

Also, what about potential contamination from the presence of fields, at least the liquid ones like blood and acid splatters?

**Comment by kevingranade** [comment]
Please discuss this in a dedicated issue or the forums, because this one is
going to be closed as soon as drinking from the ground is disabled again.

**Comment by mugling** [comment]
#14680 effectively stops interaction with liquids except those within a container
