### ISSUE TITLE
Herbal Tea crash

### ISSUE THREAD

**Issue by Priapism** [CleverRaven/Cataclysm-DDA#14660]
First time posting a bug, so I'm sorry if i miss something. Whenever I'm crafting herbal tea and I drink it straight from my hands, everything is fine. If I craft it a second time and try to drink it from my hands, it crashes. This has happened multiple times now. I'm using experimental build 0.C-4078. It was a build from 12/21.

**Comment by Priapism** [comment]
I've investigated more. When you make the herbal tea and drink from your hands, it creates a left over item on the ground called herbal tea (hot) (0) . When you try to create another and drink it by hand, then it tries to drop another one of those items onto the same spot and that is what causes the crash.

**Comment by Malkeus** [comment]
This is obviously punishment for drinking hot tea from your bare hands.
Darwinism at work here...

**Comment by Coolthulhu** [comment]
The problem seems to affect entire `handle_liquid` invocations which don't end in entire liquid getting poured.

For example, unloading a drink from a can will ask twice, with the second time being bugged and not actually resulting in drinking on "yes" answer.

**Comment by ryvn** [comment]
Ah, that sounds similar to a problem I noticed recently, where if I (e)xamine a toilet with no containers in my inventory, the "Drink from your hands?" prompt must be denied twice before it disappears.

**Comment by Coolthulhu** [comment]
Drink from hand code was rewritten, reopen if it still happens.
