### ISSUE TITLE
"It will be done in 3 seasons" Eternal seasons messes with delayed_transform message

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#14675]
![wat](https://cloud.githubusercontent.com/assets/11582235/12068410/df7659b4-afd2-11e5-8bfd-30f8e00c6e7e.png)

Windows tile build 4104, with Eternal Seasons on in winter.

I have no idea if this a display bug, a bug involving delayed transform items in general, or a bizarre interaction with eternal seasons.

If it's already been reported, I will feel silly. ;w;

EDIT: Can confirm it's still FUBAR as of build 4118.

EDIT 2: And can confirm that it behaves sanely with eternal seasons off.

EDIT 3: Welp. Found out that I wasn't waiting long enough.

**Comment by DanmakuDan** [comment]
Eternal season is overriding the season used when converting the current time into a duration, but the text printout in `calendar::textify_period()` still sees the winter start as '3 seasons from spring.' From what I can tell, the tanning pelt finishes in 2 days anyway.

**Comment by chaosvolt** [comment]
Um. Hmm. Are you sure? I could've sworn I waited a while that the display should've changed...

**Comment by DanmakuDan** [comment]
The game knows the timer is set to 2 days, the modification that eternal season does for the current season affects what the game is using to print a text version of the duration.

**Comment by chaosvolt** [comment]
Hmm. Guess I'll double-check that. Might not've have given it enough time.

**Comment by DanmakuDan** [comment]
I used the debug menu to fast forward the time by two days when I tested, and the tanning hide description said it was ready.

**Comment by chaosvolt** [comment]
Hmm. Very odd.

Let me commit some !!SCIENCE!! on this I guess. And I might have to do it the old-fashioned way, debugged "sleep is for the weak" trait plus some waiting.

**Comment by joneskun** [comment]
Check the game log (shift p) for more entertainment. "3 seasons ago..."

**Comment by chaosvolt** [comment]
...ow, my sanity.

**Comment by chaosvolt** [comment]
Derp. I should've commented on or otherwise watched @DanmakuDan's PR fixing this. Sorry about that.
