### ISSUE TITLE
Superalloy/ceramics repair?

### ISSUE THREAD

**Issue by ValidAQ** [CleverRaven/Cataclysm-DDA#14689]
Currently items made from most materials can be repaired, whether by welding, sewing, or duct taping.
Some materials, however, don't have a specified way to do so, even when they logically should.

Specifically, items made from superalloy or ceramics cannot be repaired at all. A noticeable example is the RX12 jet injector.

Superalloy probably should be added to list of materials that can be welded/soldered, taking superalloy sheets/ingots.
Ceramics - possibly could be repaired with duct tape? Considering bone and chitin already can be, doesn't seem like much of a stretch to include ceramics as well.

**Comment by kevingranade** [comment]
Ceramics are notorious for being unrepairable, this is working as intended.

**Comment by ValidAQ** [comment]
Fair enough. But superalloy should be repairable, shouldn't it?

**Comment by Coolthulhu** [comment]
Ceramic items should probably get a special flag to forbid all repairs.
They can be repaired by "targeting" the other material, usually Kevlar.
But then a bonus to damage resistance (of the items themselves) would also make sense.

**Comment by kevingranade** [comment]
Nope, it's specifically a high tech alloy that the survivor isn't going to
be ankle to work with.

**Comment by ValidAQ** [comment]
In that case, things like crafting Alloy Plating CBMs or installing/repairing superalloy plating with welder don't really make sense, either.
Besides, RX11 stimulant delivery system is also made of superalloy, but with kevlar as second material. It can be repaired just fine.

**Comment by Rivet-the-Zombie** [comment]
>Ceramic items should probably get a special flag to forbid all repairs.
They can be repaired by "targeting" the other material, usually Kevlar.
But then a bonus to damage resistance (of the items themselves) would also make sense.

In some cases, like the RM13 armor, this is intentional; non-repairable armor is nigh useless in DDA.

**Comment by ValidAQ** [comment]
Yes, this makes sense.
Also, aside from being able to repair superalloy plating (but only if it's installed on a vehicle), you can also repair minireactors the same way.
The weird thing is, they are composed from exactly those two materials - superalloy and ceramic. Repairing them isn't easy, granted, but possible.

**Comment by ValidAQ** [comment]
Though, I guess superalloy plating is a part of the same thing you mention, @Rivet-the-Zombie? Non-repairable vehicle armor doesn't sound all that useful, either.

**Comment by Rivet-the-Zombie** [comment]
Yeah it all falls under pretty much the same heading.

**Comment by Coolthulhu** [comment]
Maybe they could all (including vehicle ones) require ceramic plates to repair?
That would make them expensive to maintain, but not unmaintainable.

**Comment by kevingranade** [comment]
Agree with coolthulu, "repairing" the armor would consist of replacing
plates, reactors should not be repairable  (but should be tough enough that
it doesn't matter).

**Comment by ValidAQ** [comment]
So I guess this falls under wontfix, then?
Though I still find inconsistency with RX11 and RX12 strange, it's not particulary important.

**Comment by kevingranade** [comment]
It's not wontfix, it's working as intended.

**Comment by ValidAQ** [comment]
Right, wrong word.
Understood, thank you.
