### ISSUE TITLE
Linux Ogg files do not play but wav files do.

### ISSUE THREAD

**Issue by adrianrieck** [CleverRaven/Cataclysm-DDA#14686]
In my soundset.json I play dooropen1.wav in the menu it works but when I change the wav out for an ogg file it does not play. 

Does work:
[
    {
        "type": "sound_effect",
        "id" : "menu_move",
        "volume" : 100,
        "files" : [
            "dooropen1.wav"
        ]
    }
]

Does Not work:
[
    {
        "type": "sound_effect",
        "id" : "menu_move",
        "volume" : 100,
        "files" : [
            "dooropen1.ogg"
        ]
    }
]

My system:
Debian Linux 8 
Kernel 3.16.0-4-amd64 
Arch x86_64 
Cata version is commit eada8220a9dc17df311ebb8a28c6c9f723888eb1

I can play ogg files using VLC on my system. I am guessing this is most likely not a bug maybe the problem lies with how to compile ogg support with tiles? 
I have all the dependencies that http://www.wiki.cataclysmdda.com/index.php?title=How_to_compile mentions, is there perhaps something extra needed for ogg tiles Linux support?

**Comment by hitbutton** [comment]
I just checked compiling on with GCC on Windows 10, and ogg sounds work correctly.

You might be missing some libraries maybe? I believe ogg support requires:
libvorbis-0.dll
libvorbisfile-3.dll
libogg-0.dll
in the same directory as SDL_mixer.dll

**Comment by remyroy** [comment]
http://www.wiki.cataclysmdda.com/index.php?title=How_to_compile does not mention SDL_mixer but you need it to compile with sound support. SDL_mixer depends on libVorbis and libogg which should provide support for reading ogg files.

**Comment by remyroy** [comment]
Checkout [COMPILING.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING.md) for a more accurate compiling guide.

**Comment by adrianrieck** [comment]
Thank you the compiling guide is super useful. So it does look like the issue would be with my SDL_mixer compilation and not cata itself.
