### ISSUE TITLE
NPC with no matches/lighter fails to use molotov, loses all turns

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14693]
NPCs who don't have a source of fire don't understand that they can't use molotovs and spend all their turns trying to activate it.

**Comment by renlok** [comment]
I'm new and just trying to learn the code so I might be wrong but do you need to just add an additional check to
in npcmove.cpp
to bool npc::alt_attack_available()

is there an npc equivalent of p->has_charges("fire", 1)?

**Comment by Coolthulhu** [comment]
There is a semi-done fix at #15536, but it's old and wasn't updated for almost 3 weeks.

The bug doesn't happen in master right now - I hacked around it by allowing NPCs to magically activate their molotovs and other fiery stuff, as if they always had a lighter (or a nearby fire).

**Comment by kevingranade** [comment]
I think that's a pretty reasonable assumption to make, maintaining
firestarting charges is pretty trivial.

**Comment by kevingranade** [comment]
Tried to verify that this had been fixed, but I don't know how to induce a NPC to use a Molotov.  If I spawn one and only give them Molotovs as weapons, they walk up to zombies and smash them with the Molotov bottles.  If I restrict them to not approaching monsters on their own, they just don't attack.  Seems to happen with grenades too.

**Comment by Coolthulhu** [comment]
NPCs won't use alt weapons (or burst fire or support items) unless there is an "emergency", which is related to danger and bravery.

Spawning a shoggoth generally works.

**Comment by Coolthulhu** [comment]
The hack should handle it for now
