### ISSUE TITLE
Cygwin build is broken (‘round’ is not a member of ‘std’)

### ISSUE THREAD

**Issue by dholmes215** [CleverRaven/Cataclysm-DDA#14696]
The Cygwin build fails:

```
$ make
/bin/sh: astyle: command not found
g++  -DCATA_NO_CPP11_STRING_CONVERSIONS -DGIT_VERSION -DLOCALIZE -ffast-math -Og -Wall -Wextra -g  --std=c++11 -MMD -c src/ranged.cpp -o obj/ranged.o
src/ranged.cpp: In member function ‘std::vector<tripoint> game::target(tripoint&, const tripoint&, const tripoint&, std::vector<Creature*>, int&, item*, target_mode, const tripoint&)’:
src/ranged.cpp:895:37: error: ‘round’ is not a member of ‘std’
         if(trigdist && range > 1 && std::round(trig_dist( from, p )) > range) {
                                     ^
src/ranged.cpp:895:37: note: suggested alternative:
In file included from /usr/lib/gcc/x86_64-pc-cygwin/5.2.0/include/c++/cmath:44:0,
                 from src/ranged.cpp:3:
/usr/include/math.h:282:15: note:   ‘round’
 extern double round _PARAMS((double));
               ^
src/ranged.cpp:899:21: error: ‘round’ is not a member of ‘std’
                 if( std::round(trig_dist( from, ret[i] )) > range ) {
                     ^
src/ranged.cpp:899:21: note: suggested alternative:
In file included from /usr/lib/gcc/x86_64-pc-cygwin/5.2.0/include/c++/cmath:44:0,
                 from src/ranged.cpp:3:
/usr/include/math.h:282:15: note:   ‘round’
 extern double round _PARAMS((double));
               ^
Makefile:549: recipe for target 'obj/ranged.o' failed
make: *** [obj/ranged.o] Error 1
```

This one looks like another typical case of cygwin/newlib stupidity:

https://cygwin.com/ml/cygwin/2015-03/msg00247.html

A workaround might be necessary.

**Comment by Wad67** [comment]
Broken again?

`src/harvest.cpp: In lambda function:
src/harvest.cpp:141:48: error: ‘round’ is not a member of ‘std’
         int max_drops = std::min<int>( en.max, std::round( std::max( 0.0f, max_f ) ) );
                                                ^
src/harvest.cpp:141:48: note: suggested alternative:
In file included from src/line.h:9:0,
                 from src/item.h:18,
                 from src/harvest.cpp:7:
/usr/include/math.h:331:15: note:   ‘round’
 extern double round _PARAMS((double));
               ^
src/harvest.cpp:142:46: error: ‘round’ is not a member of ‘std’
         int min_drops = std::max<int>( 0.0f, std::round( std::min( min_f, max_f ) ) );
                                              ^
src/harvest.cpp:142:46: note: suggested alternative:
In file included from src/line.h:9:0,
                 from src/item.h:18,
                 from src/harvest.cpp:7:
/usr/include/math.h:331:15: note:   ‘round’
 extern double round _PARAMS((double));
               ^
g++  -DCATA_NO_CPP11_STRING_CONVERSIONS -DGIT_VERSION -DLOCALIZE -D_GLIBCXX_USE_C99_MATH_TR1 -ffast-math -Og -Wall -Wextra  -g  -fsigned-char -std=gnu++11 -MMD -c src/npc.cpp -o obj/npc.o
make: *** [Makefile:687: obj/harvest.o] Error 1
make: *** Waiting for unfinished jobs....

`

**Comment by Wad67** [comment]
Seems fairly trivial to fix, I'm going to attempt to replace every instance of std::round with just round().
