### ISSUE TITLE
Infected NPC died after completing mission, and mission appears in "failed" list twice

### ISSUE THREAD

**Issue by dholmes215** [CleverRaven/Cataclysm-DDA#14699]
I started a new character in a new world, and my NPC buddy was infected (the "Find Antibiotics" mission).  I found antibiotics and gave them to her, and went about my business.  Two days later I found her dead.

I checked my mission list, and see the mission in the "completed missions list"... and also two more copies of the same mission in the "failed missions" list. All three missions have the same deadline.

Game version is da2bfd6 on Cygwin.

**Comment by Coolthulhu** [comment]
Should be fixed now.
