### ISSUE TITLE
Zombie renaming discussion

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14702]
Started in #14677

From the old discussion:
> Out of human zeds, the lowest "standard of naming" is probably the bloated one - it describes only how it looks, not what it does. The second would be corrosive and/or acidic - they're both non-natural ("look out, a corrosive!" doesn't sound good) and only suggest that they are related to acid, not how.

> It does have "gasbag" in its ID though. Gasbag zombie sounds a bit silly, but would be more descriptive.

> most of the names seem reasonable now, though snotgobbler and sproglodyte are a bit odd.
> Poppers and Leaplings.

I like the popper - sounds like a mini-boomer right there. The acne-related everything isn't "in-your-face", but almost subtle, which is a plus.

**Comment by chaosvolt** [comment]
Swiggity swooty. Still dunno where the difference in ID and name came from, regarding bloated zombies.

**Comment by hitbutton** [comment]
> the lowest "standard of naming" is probably the bloated one - it describes only how it looks, not what it does.

Bloated seems fine functionally to me. Given the context it should be obvious that a zombie bloated with <substance> is probably going to release <substance> and it will be nasty. I think its enough for a name to hint at abilities/characteristics rather than having to spell them out.

My biggest issue with the new child zombie naming is that they're generally flippant, cute, and/or contain puns. There are a lot of comedy aspects to cdda, but at it's heart it is a survival horror game. Common enemies with comedy names undermine that aspect of the game's atmosphere. Snotgobbler is the most heinous offender here, but all the new child zombies bar howling waif are unnecessarily cutesy. The only other comedy zombie names are "rot-weiler" and "z9". Rot-weiler is especially misleading, as it isn't apparent that it's a zombie if you miss that it's a joke name.

On a separate note - I'm not sure why it's just "boomer". The single-word short name - with no indication that it's a zombie - is out of keeping with the rest of the zombie lineup. "boomer zombie" would be better.

**Comment by i2amroy** [comment]
>On a separate note - I'm not sure why it's just "boomer". The single-word short name - with no indication that it's a zombie - is out of keeping with the rest of the zombie lineup. "boomer zombie" would be better.

Because it's one of the oldest zombies and many of the originals were cribbed directly from Left4Dead, which just calls it a boomer. I know I'd be totally fine with renaming it to "boomer zombie".

**Comment by Malkeus** [comment]
Snotgobbler -> Popper, boomer -> boomer zombie, sproglodyte -> ??

Anything else?

**Comment by chaosvolt** [comment]
Springy sprout? That was a silly suggestion I made, if i recall. o3o

**Comment by kevingranade** [comment]
I'm on board with the first two suggestions.
Sprog -> emaciated zombie?
-> skittering zombie?

**Comment by Malkeus** [comment]
I like skittering zombie. But it doesn't say 'jumping' to me. Otoh, neither
does hunting zombie. What are those little jumping bastards from Diablo
called?

**Comment by Malkeus** [comment]
Lame, they are literally called 'Leapers'. No good. How about swarmer, make them normal speed with a long leap range, but very very weak attack. They only spawn in groups of 15 or more.

**Comment by kevingranade** [comment]
Change the monster to match the name? That's a bit odd.

**Comment by Malkeus** [comment]
You're right. I should just create a new monster. Skittering zombie is an
ok name for the sprog.

**Comment by Coolthulhu** [comment]
Skittering sounds OK.
Or maybe more nickname-ish - shortening to just "skitter".

Alternatively: springy, hopper, froggy, flea, batty

**Comment by Malkeus** [comment]
Skipper zombies. With the right sprite that would be something out a horror movie. Imagine their rictus grins as they skip along in your wake, occasionally taking flying leaps towards you.

**Comment by hitbutton** [comment]
Boomer -> Boomer zombie
Snotgobbler -> Tiny boomer (to match Huge boomer)
Sproglodyte -> Feral scamperer (leaping zombies have Feral prefix)
Anklebiter -> Slavering child zombie (to match Slavering Biter, which is the larger version)
Creepy Crawler -> Skittering child zombie (skittering seems a better match for CLIMB)

**Comment by harald921** [comment]
Have I missed out on something? What is a sproglodyte? Anklebiter? What is going on?

**Comment by Malkeus** [comment]
Checkout #14677

**Comment by ryvn** [comment]
I know I don't comment here often - I mostly come here to see what people are working on - but I'm going un-lurk to go against the grain here and say that Rivet's "joke" names are far better than calling everything "adjective zombie" or "zombie verber." The tile (z) already tells you it's a zombie, it doesn't need the word "zombie" in its name - especially when zombies are the most common class of enemy you'll be facing anyway. "Snotgobbler" is evocative - it's the kind of name that makes the monster a better monster *just by naming it.*

To steal an example from another game I've been playing recently, think what a loss it would be if the enemies in Borderlands were called "alien dog," "spitting alien dog," "huge alien dog," etc.

**Comment by Coolthulhu** [comment]
Snotgobbler is evocative (I'd say too evocative) about how it looks, but not how it works - neither mechanically nor in "roleplay".
It basically says "it is disgusting". And since disgust isn't really a mechanic in the game, this isn't really relevant. What is relevant is that it grabs and explodes like a popped zit.
Plus, it is dangerously near the whole bodily functions thing. We already omit vomit (except as "you vomit" message and "zombie barfs acid"), nose being runny during cold, wounds filling with pus etc. Those are good in the description, not out there in the open.

> think what a loss it would be if the enemies in Borderlands were called "alien dog," "spitting alien dog," "huge alien dog,"

Not much of a loss at all, honestly.
The only thing memorable about them is how they look and attack. Plus, naming a big variant "alpha" is about as creative as naming a buffed zombie "tough".

I'd say even robot names in Total Annihilation or Supreme Commander would be a better example than Borderlands.

**Comment by harald921** [comment]
Isn't the purpose of the names to give an idea what the monster is, then the description describes the monster, then it's up to the player to fantasize about what the monster looks like apart from that and give it nicknames, etc?

**Comment by kevingranade** [comment]
The purpose of the name is to give it a distinctive label so you can
recognize it without checking the description. Everything else is extra.
I think the current names are fine, but I don't have a strong opinion about
keeping them.
