### ISSUE TITLE
Crossbow trap bug

### ISSUE THREAD

**Issue by Priapism** [CleverRaven/Cataclysm-DDA#14705]
When I create a crossbow trap, it also creates wooden crossbow bolt (0). I'm using a steel crossbow bolt to create the trap, so the empty stack of wooden appear from nowhere.

**Comment by illi-kun** [comment]
I accidentally reproduced that bug but only once and I still don't get how to reproduce it accurately.

**Comment by Oskar636** [comment]
How did you guys reproduce this?

**Comment by Night-Pryanik** [comment]
Can't reproduce on 0.C-6368, Win 10 x64, curses.

**Comment by kevingranade** [comment]
Closing until we can get a repeatable reproduction case.
