### ISSUE TITLE
Game crash during gas pump explosion

### ISSUE THREAD

**Issue by drayath** [CleverRaven/Cataclysm-DDA#14712]
In vehicle, blaze turret (with pulse rifle in auto burst mode) hit gas-pump (in automated gas station, console had been hacked but gas not yet collected) causing an explosion. Log showed it got as far as explosion doing a few points of damage to me, there were a couple of log lines after that i did not have a chance to read and the game crashed (before i had a turn to move).

Crash dump attached for version: cataclysmdda-0.C-4127 (experimental-windows sdl).
Last save was an hour or two before,

[cataclysm-tiles.exe.2216.dmp.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/77494/cataclysm-tiles.exe.2216.dmp.zip)

**Comment by ValidAQ** [comment]
It seems that this crash is connected to player being caught in an explosion and taking damage. 
I've successfully crashed the game by blowing up a gas station, standing near exploding C-4 charge, grenade hacks and shooting a fully charged NX-17 rifle.
For example, this is the last turn before crashing with NX-17.
![z](https://cloud.githubusercontent.com/assets/8605315/12118349/04d7eeb8-b3d7-11e5-9e5b-401db4ae0eaa.png)
Crash occurs immediately after shooting.

What I noticed during testing is that crash may not occur if player takes no damage from explosion. 
In the above example, standing 3-5 tiles to the south (with heavy survivor armor) would result in no damage and no crash:
![z](https://cloud.githubusercontent.com/assets/8605315/12119085/8f0787b2-b3da-11e5-9c1d-c07365fa1d0c.png)

**Comment by Zireael07** [comment]
@ValidAQ: Do you have a save?

**Comment by ValidAQ** [comment]
Sure, give me a few minutes.

**Comment by ValidAQ** [comment]
[Here is the save.](https://www.mediafire.com/?oloix0kuay36os2)
Hmm. I created another, completely new character in a fresh world. I cannot replicate the crash there.
