### ISSUE TITLE
Alarm System CBM reacts to hallucinations

### ISSUE THREAD

**Issue by ValidAQ** [CleverRaven/Cataclysm-DDA#14714]
Windows x86 Curses 0.C-8705-g3ed52ea, build 4134.
Not much to add, really.
Install the Alarm System CBM, activate it, then spawn a hallucinatory monster nearby. Motion alarm will go off.
![z](https://cloud.githubusercontent.com/assets/8605315/12102848/efed760e-b34e-11e5-8390-43e95b93a854.png)
Relevant log messages highlighted.
Z-9 was a hallucinatory monster spawned for testing. No other monsters were close enough for the alarm to trigger.

**Comment by nanovad** [comment]
Is this a bug or a feature? Should the CBM detect what you think you see, or what you actually see?

**Comment by kevingranade** [comment]
It should detect what's actually there.
Even if it hijacks you eyes to detect things (which it doesn't since it
works when you are asleep) that isn't where hallucinations originate.
