### ISSUE TITLE
[Suggestion] "Nerf" for the Corrosive Zombie

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#14726]
The Corrosive Zombie is just ridiculous at the moment. When you don't mind going 1v2 melee against hulks but run away as soon as you see a Corrosive Zombie aproaching, then something is a little off. Just make their "bullets" (spits) not create puddles under you, but just hurt you but keep the mechanic of acid splashing out of them when they get hurt. Or just lower the rate of fire. I know they should be seen as a threat but right now they are just ridiculous.

No spit puddles + more health? Lower spit rate of fire and make them able to grab you? Lower spit distance and make them more rare?

What do you guys think?

**Comment by Coolthulhu** [comment]
Removing spit puddles sounds OK to me.
To offset that, I'd give them low cooldown barf attack (like what acidic zeds use) to use in melee. This one would still create puddles.

Corrosives become quite harmless once you know "the trick". That is, standing on a vehicle, which immunizes you to puddles.

**Comment by kevingranade** [comment]
I'm fine with puddles going away, the volume of acid implied is ludicrous. (for corrosives and the other spitters)
Does the 'puddle trick' have an issue for it?  I can see certain vehicle parts (open frames for example) not allowing acid to pool, but a vehicle tile with a quarterpanel or similar (now that I think of it, do the cars even have hoods, or just an exposed engine?) should allow the acid to pool.

**Comment by Mecares** [comment]
I like them, they are one of the few things even well equipped survivors have to be careful against.

**Comment by hitbutton** [comment]
Having enemies with threatening attacks that force you to adapt seems more feature than bug to me. If you're at a point in the game where hulks aren't a threat, then you'll also have means to protect your legs and feet from acid.

> I'm fine with puddles going away, the volume of acid implied is ludicrous. (for corrosives and the other spitters)

The area denial of acid spitters is a gameplay element worth keeping though. I think its worth handwaving the science of extradimensional slime zombies producing implausible volumes of acid :)

**Comment by Coolthulhu** [comment]
> Does the 'puddle trick' have an issue for it?

If it has one, it has to be an old one (pre 10k).
> I can see certain vehicle parts (open frames for example) not allowing acid to pool

The problem is that a shopping cart is enough to immunize self to acid and a shopping cart most certainly won't allow acid to pool inside.

**Comment by harald921** [comment]
I think it would be better if there could be some more concrete threat rather than something that makes you want to facepalm. "Oh great a corrosive zombie, time to bandage my legs for the next 48h". Perhaps even buff other zombies? Like the hulks? (Hp wise that is)

**Comment by Malkeus** [comment]
Mainline Bio-Weapons!

**Comment by adrianrieck** [comment]
The acidic zombie in it's current form is more comparable to 'Alien' from the movie. Well maybe just give it feral predator speed and call it alien. I would be okay with that if we reduce their frequency or limit them to specific areas like ants.

**Comment by Rivet-the-Zombie** [comment]
Sounds good to me. Also, I really like Coolthulhu's idea for the special close-range attack.
