### ISSUE TITLE
Water collection long action is broken.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#14731]
Build 4143

It's defaulting to a single action of ten water units each time you examine a water source and attempt to fill a container - item type containers, not vehicle tanks. Doesn't matter if it's in your hands, your inventory, in a vehicle trunk, or on the ground.

**Comment by DanmakuDan** [comment]
The process for picking up water from an infinite source generates a fake water item with 10 charges. The activity itself is given -1 moves, so it completes its task after processing for one turn. A simple solution would be to change the initial `water.charges` to a large number capable of filling any container in general.
