### ISSUE TITLE
0.C-8877-ga44b390 Double Lab Spawns

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#14749]
Probable Cause: #14475

Lately, each lab spawns 2 overmap tiles. Sometimes only one will have connecting stairs. I don't know what the new lab layouts should look like, so I can't tell if they are doubling up or if it's just one complex with 2 entrances.

[Overview, Ground Level](http://imgur.com/7rpKY1r) -4 Labs present, but 8 lab tiles showing on overmap.
[Overview, 1st Floor](http://imgur.com/PHFBXQR).

[Lower right, Inside](http://imgur.com/hEY48dW) -Right next to each other.
 -[Interior, 1st Floor](http://imgur.com/02nGkUD) .

[Upper left, Outside](http://imgur.com/uC0OIn0) -Separated by 1 tile.
 -[Interior, 1st Floor](http://imgur.com/3kRIZ6w).

**Comment by DanmakuDan** [comment]
Special tiles like labs are placed on a grid of 15x15 overmap tiles, one per 15x15 group. I can't tell from the picture, but I am guessing those labs in the pictures are on separate 15x15 tiles. Maybe there was a mechanism that deletes extra labs in a certain radius?

**Comment by sparr** [comment]
It's possible something I did with the lab overmap generator is adding a map tile to Z=0 somehow.

**Comment by DanmakuDan** [comment]
It might be the part in `overmap::build_lab` that generates a lab_stairs if the generated_lab group didn't find a stairway above its tiles.

**Comment by DanmakuDan** [comment]
Fixed by #14939.

**Comment by Malkeus** [comment]
Thank you DanmakuDan :)
