### ISSUE TITLE
[Suggestion] (Tiles) Random Character Sprite

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#14742]
I am not sure whether or not this is a feature within other texture packs, but I am using mshock32modded atm and I can't help but feeling that the player character should be randomized at game start. Is this a feature of other packs? Would it make it hard to see which character is yours? Is this even possible? What are your thoughts?

**Comment by hitbutton** [comment]
#14573 is an open PR for that.

**Comment by Chezzo** [comment]
My tileset does this, but until that pr drops, it randomizes only once per world and then spits out every player or npc with that skin.

**Comment by sparr** [comment]
fixed by 14573
