### ISSUE TITLE
M14 is semi-automatic in-game, but automatic in real life. 

### ISSUE THREAD

**Issue by Totentag** [CleverRaven/Cataclysm-DDA#14745]
This is a minor quibble, and one that is probably more balanced as-is, but I feel like it should be mentioned anyway. 

The M14 is a pretty major mark in US firearms history, serving as the stop-gap BR as we we entered Vietnam, and morphing into the DMR we often think of it as today. In my personal opinion, the fact that the M14 was fully-automatic is an incredibly important aspect of the weapon's history and use; it was designed as such to serve as a replacement for both the M3 submachine gun and the BAR light machine gun (simultaneously). While it may have failed in both of these roles, and veterans who used the M14 in combat often report that they never used it in its fully automatic configuration, the gun would never have been designed the way it was, if it was not intended to be automatic. 

As it stands. my suggestion is pretty simple. The existing M14 item could be renamed the [M1A](https://en.wikipedia.org/wiki/Springfield_Armory_M1A) (the modern civilian model, only available in semi-automatic configuration), while a replacement M14 could be copied from it, given a burst size fitting its use (I'd wager a burst of 5 rounds, but I don't know how you fine devs balance burst), and perhaps weighed up slightly to account for the altered mechanics that, in real life, weighed almost half a kilogram more.

**Comment by SunshineDistillery** [comment]
But existing m14s now are almost all semi auto, and in the 20xx that would probably be the same. 
If you want a selective fire m14, there is always a full auto conversion mod.

**Comment by Totentag** [comment]
"Existing M14s" refers almost exclusively to M1A rifles, as opposed to actual M14s, unless you mean M14s in military hands today. In that case, you'd likely be referring to any of the [many variations](https://en.wikipedia.org/wiki/M14_rifle#Military), many of which are still in use. In this universe where I can find an automatic FN FAL in a gun store or random basement, I can't help but assume the similarly dated M14 could be found right alongside it, in its original configuration.

**Comment by chaosvolt** [comment]
> But existing m14s now are almost all semi auto, and in the 20xx that would probably be the same.
If you want a selective fire m14, there is always a full auto conversion mod. 

Going back to the gun nerd question at hand. Are the majority of existing M14 derivitives actually M14s, or are they M1As? This would be nothing but a simple rename, followed by double-checking the weight to make sure we don't have the same griping that renaming the AK-47 and 74 caused. o3o

**Comment by Totentag** [comment]
>Are the majority of existing M14 derivitives actually M14s, or are they M1As?

The military variants are, for the most part, machined to suit their titled purpose, and are technically neither. As for the guns one might find in the average gun-nuts collection, nine times out of ten you can expect it will be an M1A. A select-fire M14A1 today costs upwards of $5,000 US, not to mention the $500 stamp required to own a Class III firearm. 

By comparison, the bone-stock M1A is about $1,200, with no nasty paperwork required.

**Comment by chaosvolt** [comment]
As I figured. So just rename, double-check weight, and double-check the normal stock material (wood versus plastic, basically). Adding a select-fire variant can be done later. owo

**Comment by chaosvolt** [comment]
Anyway, adding a PR for it. Link will go here:

**Comment by kevingranade** [comment]
Not to mention, the number of select-fire M14A rifles seems to be around 50
according to the wiki article.

**Comment by chaosvolt** [comment]
That does sound like it might be best not to add the select-fire version, yeah.
