### ISSUE TITLE
The date (days survived) appears over the hour, making impossible to see what time is it.

### ISSUE THREAD

**Issue by Theradin** [CleverRaven/Cataclysm-DDA#14748]
This is probably due to the translation. Spring is translated as "Primavera" in Spanish and the word length is probably causing the overlap:

![e9mbtbp](https://cloud.githubusercontent.com/assets/16598417/12179727/bfd5f604-b578-11e5-8b75-d586127a3bb3.png)

**Comment by Oskar636** [comment]
From what I can see, in build 5864, the season name doesn't get translated in any language so this isn't an issue now.

**Comment by illi-kun** [comment]
It's definetely not a proper solution.

**Comment by Mooses2k** [comment]
Completely shooting in the dark here, but require a certain character length for season names, anything else has to be appreviated, such as prima, verano, otono, invier?

**Comment by ZhilkinSerg** [comment]
Translation was updated to "Prima." since ticket was opened. It is readable in all panel layouts now. I've also tested some other languages and all looked fine.
