### ISSUE TITLE
CBM Telescopic Eyes does not fix all vision problems as discribed

### ISSUE THREAD

**Issue by kd8qdz** [CleverRaven/Cataclysm-DDA#14751]
CBM Telescopic Eyes description says  it fixes all vision problems.   When installed on character with both Near and Far sighted traits, only removed Far sighted; thus not fixing all vision problems.

**Comment by sparr** [comment]
How did you get a character with both of those traits?

**Comment by Malkeus** [comment]
You can pick both at chargen sparr. For like...forever.

**Comment by Malkeus** [comment]
It leaves you pretty useless unless you have bifocals

**Comment by Cyrano7** [comment]
If you pick both on game start does it start you with bifocals? Cause we should change that to.

**Comment by Malkeus** [comment]
it does start you with bifocals, yes.

**Comment by Malkeus** [comment]
change it to what?

**Comment by Cyrano7** [comment]
I meant if It didn't start you with them. Sry not clear.

**Comment by Cyrano7** [comment]
@kd8qdz okay this https://github.com/CleverRaven/Cataclysm-DDA/pull/14752 should fix the issue and fix your character when you update your game.

**Comment by kd8qdz** [comment]
Thanks!

**Comment by Coolthulhu** [comment]
Another minor problem:
Installing the CBM will remove the traits, but removing it (for example due to mis-installation of other CBM) won't bring them back.

**Comment by Cyrano7** [comment]
hhmmm this is true. The question of bringing them back is more a question of telling which ones you had in the first place though. hhmmm....

**Comment by Cyrano7** [comment]
Oh btw it can only be removed by botched install of another CBM. It blocks you from uninstalling it currently.

**Comment by Cyrano7** [comment]
Does anyone know if starting traits are saved? Like for purifier. I'm pretty sure purifier won't take away starting traits.

**Comment by Malkeus** [comment]
Just a thought, if telescopic eyes performed like a permanent pair of
bifocals rather than removing the poor vision traits, the whole issue of
trying to save which trait you had originally goes away. You could add a
check wherever the @ menu gets its list of traits and suppress the display
if telescopic eyes are present. Then, if you lose them somehow, the
suppression check goes away and the trait reappears.

**Comment by Cyrano7** [comment]
Another option is to leave the traits as is and instead add a permanent eye effect. Which is lost if they are damaged. Or just making it so that they don't get damaged on a botched install but that's just a hackish way of doing it.

**Comment by kevingranade** [comment]
I'm not sure if removing the original trait or the ability to uninstall the
CBM is the real problem.

If they replace your eyes, removing vision traits (btw, they should remove
positive vision traits as well) makes sense, but it also means they should
not be removable.

**Comment by Cyrano7** [comment]
It's currently not removable. So just blocking it from becoming destroyed by botched install of another cbm will fix this. I like your idea about blocking all eye traits though I might have to expand on that later.
