### ISSUE TITLE
[Bug] "It's too dark to solder" when darkness cancels sewing

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#14759]
You can replicate this when using the second alternative while trying to repair something and then letting your lights go out. Just a small "typo", which I assume exists becuase sewing is a "form of soldering"? Possible to fix or too much work for such a small detail?

**Comment by nanovad** [comment]
Do you mean "You can't see to solder"? In that case, it's just a typo in the code. I haven't been able to find "It's too dark to solder" in the source anywhere.

**Comment by Sir-Kernicus** [comment]
It does come up. start sewing and set on repeat then when it gets dark it states it is to dark to solder.
