### ISSUE TITLE
"You can't hit reliably without your glasses" sometimes seen when wearing contact lenses

### ISSUE THREAD

**Issue by jedibob5** [CleverRaven/Cataclysm-DDA#14754]
![capture](https://cloud.githubusercontent.com/assets/13815411/12189430/279ddb76-b583-11e5-9848-a422e636ef50.PNG)
I'm not entirely sure what causes it, but it just seems to happen sometimes when fighting. I'm not sure what to look for when it comes to isolating and reproducing it, but I can do some more testing if necessary.

**Comment by Coolthulhu** [comment]
It's because miss reason code is hardcoded to check only for worn glasses.
It should all be moved into a function that returns some measure of vision impairment.

**Comment by Night-Pryanik** [comment]
Maybe alter *player::sight_impaired()* in player.cpp to take all types of vision impairment into account and replace all hardcoded checks in crafting, melee, computer using and the like with this updated check?
