### ISSUE TITLE
Light mechanics and Construction walls not blocking them

### ISSUE THREAD

**Issue by Stevensonz** [CleverRaven/Cataclysm-DDA#1475]
some form of light seems to seep through on walls with closed curtains/taped windows and it says it's dark too read yet your awaken by the light when sleeping, so I decided to start construction of walls that isn't palisade and I built a sleeping quarters with 3 rows of doors and walls inside a location with no basement/under ground yet somehow I cannot sleep like the vampire would in an enclosed coffin from my sleeping quarters during the day.

**Comment by Barhandar** [comment]
It could be changed to use the lighting value that's used for crafting, which is accurate. It will cause players to not be able to sleep with atomic nightlight with them, but hey, maybe they want to be in the dark. Or the nightlight's effect could be ignored.

**Comment by KA101** [comment]
It's a nightlight, so folks ought to be able to handle it without too much trouble.

**Comment by kevingranade** [comment]
Need to make a call one way or the other, either it's bright enough to read
by, or dim enough to sleep under, it can't be both.

**Comment by KA101** [comment]
*KA101 rolls over and faces away from the atomic nightlight*

But yeah, if it's on your person I'd imagine it might make sleep difficult.  No objection on my end.

**Comment by kevingranade** [comment]
This got overhauled a while back, the "woken up by light" check uses ambient light instead of natural light level now.
