### ISSUE TITLE
[Bug(?)] Misc. Software from disassembling USB drive

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#14750]
So I disassembled a USB drive with some misc software on it.. got the software as a physical object. Proceeded to smack a table to pieces with it, however it damaged the software. I'd like to find the creator of that software and shake his hand.

No but seriously, just disassemble a USB drive with misc software to replicate the problem. :)

**Comment by Cyrano7** [comment]
What else did it break down into? A usb drive? ram?

**Comment by Zireael07** [comment]
According to item browser, it should give RAM, but AFAIR USB drives with software break down into USB + software instead.
