### ISSUE TITLE
Road Mapgen - Cul de Sac's Gone

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#14760]
Before the recent road changes in #14323, we had nice looking cul de sac's with neat little roundabouts, like this:
http://puu.sh/mo54H/072a4b565b.jpg

Now they are squared off and incomplete, like this:
http://puu.sh/mnJHt/7f895ac229.jpg

**Comment by sparr** [comment]
The old code should have produced dead ends and cul de sacs both, with different criteria. The new code is supposed to do the same, but I probably messed up. The incompleteness is due to some sides of a dead end "deserving" sidewalks or not.

I'll look into this.

**Comment by sparr** [comment]
Looking at the old code again, I think I got the cul de sac probability right. 1/3 of dead ends with any sidewalks get turned into cul de sacs. The other 2/3, and all dead ends without sidewalks, stay straight dead ends.

The sidewalks on the dead ends are another matter... In the old system, all roads had sidewalks on all or no sides, no partials. I changed this to allow sidewalks just on the sides near sidewalk-having buildings, so roads on the edge of a town would look better. I think that worked, mostly. The four-way intersection here shouldn't have sidewalk in the bottom left, I think. In this case, what should it look like? Should the dead end have sidewalks on the no-house side? Should it have sidewalks on the end?

**Comment by sparr** [comment]
The reason the four-way has sidewalk in the bottom left is that a road gets left-side sidewalks if there's a sidewalk-having building in any of the up+left, left, or down+left locations. so the house to the northwest causes a southwest sidewalk.

I can make that logic smarter, if we can decide how it should look.

**Comment by kevingranade** [comment]
In that example I think it should either extend the sidewalk to all sides, or not have a sidewalk on the end.  In the latter case the 4-way shouldn't have that floating chunk of sidewalk.

**Comment by Malkeus** [comment]
Cul de sac's confirmed. I found one earlier today while testing something else, it looked ok, maybe more oval than circle, but it was smoother than the original iirc.

**Comment by sparr** [comment]
The 4-way extra sidewalk was actually a logic/arithmetic bug.
