### ISSUE TITLE
Hallucinations destroying items (build 4160)

### ISSUE THREAD

**Issue by MisterFelixFox** [CleverRaven/Cataclysm-DDA#14763]
I was hallucinating for some reason and trying to read a book. I was ignoring the hallucination monsters until I suddenly stopped reading because somehow one destroyed my book.

http://puu.sh/molh1/cd5ecb539d.png (the pain is just from running around in the cold for too long)

Another hallucination was attacking the NPC in my shelter, but I can't tell if her weapon was damaged.

**Comment by nanovad** [comment]
That's odd, I'd say monsters really shouldn't be able to deal damage if they're hallucinations... But can you hallucinate if an item gets damaged?

**Comment by sparr** [comment]
Your body can certainly do things that you perceive the hallucinations as doing.

See also: Fight Club. Calvin and Hobbes.

**Comment by ValidAQ** [comment]
This could be thought of as damage from survivor swinging the book around, trying to deflect the imaginary blow.
Though I don't really think it's supposed to work that way.

**Comment by kevingranade** [comment]
I'd say bug outside a specific mechanic and message to the user saying what
happened.
