### ISSUE TITLE
Shady zombies still appear on the minimap while they are otherwise invisible.

### ISSUE THREAD

**Issue by Dalenacio** [CleverRaven/Cataclysm-DDA#14777]
This really breaks the fun of getting jumped by one if you happen to glance at the minimap and prepare for the coming ambush.

**Comment by DanmakuDan** [comment]
It should be fixed by #14538, when it gets added.

**Comment by kevingranade** [comment]
It was fixed at some point, probably by #14538 as @DanmakuDan said it would.
