### ISSUE TITLE
No pumpkin seeds after growing pumpkins

### ISSUE THREAD

**Issue by jcd000** [CleverRaven/Cataclysm-DDA#14786]
Possible cause of the problem: from the json, the seed_data field reads:

        "seed_data": {
            "plant_name": "pumpkin",
            "fruit": "pumpkin",
            "fruit_div": 3,
            "byproducts": [ "withered" ],
            "grow" : 91
        }

.... but the: fruit_div": 3,  line seems out of place. No other seeds have it. (actually a json grep found no other occurences of the fruit_div string)

I did not delve into the code to verify so i won't PR this right now. 
I will change the local json value so i will know if this was the problem when harvesting time comes again.

**Comment by Rivet-the-Zombie** [comment]
I'm not sure what 'fruit_div' is about, but this doesn't really seem like a bug; if you want pumpkin seeds, you should have to crack open one of your pumpkins to get them - they don't grow on the vine alongside the fruit.

**Comment by Chezzo** [comment]
That is a great idea, @Rivet-the-Zombie, you totally SHOULD be able to disassemble fruit to get seeds.

**Comment by Coolthulhu** [comment]
I'd prefer separate seeds here.
With "seed crafting", we'd need an additional item to represent seedless pumpkin flesh and another crafting step for every harvest. Unless that crafting step was relatively expensive time-wise, it may as well be skipped, for player's convenience.

The fruit/seed separation hack is unrealistic, but until we get automatic seed separation on consumption/crafting, it is more convenient without any real balance downsides.

There are some plants that require processing - most notably grains that need to be milled - but those include relatively high processing time. In case of those, existence of another step makes sense.

As for `fruit_div` - it was a variable created for pumpkins, to make them spawn less than full stacks of fruit. If it affects seed drops directly, that's probably a bug.

**Comment by jcd000** [comment]
yup it does affect seeds. 4/4 of my pumpkins spawned with 'with pumpkin seeds(0)'. And this item was plantable (!), but didn't stack with other seeds(0).
Best guess (again no source read) is that the normal 2 seeds are divided by 3 and the (integer) result is 0.

Having the ability to make plans able to grow less than full stacks of produce is nice btw.


@Rivet-the-Zombie: Its true, most plants should give seeds as a byproduct of cooking/processing. But this will become very problematic with the way recipes work. Unless you add the 'seedless' (processsed) variety as @Coolthulhu says, again with big problems as he says.
