### ISSUE TITLE
Crash: Trying to Dissasemble a Sewing Kit crashes the game

### ISSUE THREAD

**Issue by MgDark** [CleverRaven/Cataclysm-DDA#14780]
OS: Windows 10
Build: 0.C-8885-g35ddeeb, upgraded later to latest experimental, still happens
Reproduction Rate: 100%

How to Crash: In inventory, select a sewing kit (charges doesnt matter) and press D to dissasemble, the action is greyed out but it makes you crash

**Comment by Coolthulhu** [comment]
Duplicate of #14735
