### ISSUE TITLE
Specific guns for robots

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#14798]
Right now turrets and robots just use existing weapons.  Turrets use the mp5, m4a1, and m-whatever that .50cal sniper rifle is called. I don't like that for two reasons. One, robots have to use a weapon that's balanced for the player instead of one balanced for a mob.  Two, disassembling a robot can garner you a working gun meant to be operated by human hands, which isn't a balance problem, but is a little weird. 

I was thinking there could be a set of dummy weapons for robots (or other monsters) to use.  Then you could alter their stats for balance. You could, for example, lower a turret's burst size so it doesn't burn through ammo so quickly. Disassembling a robot wouldn't yield its gun; it would leave a set of spare parts. Then there would be a recipe for making those spare parts into a crappy jury-rigged gun, similar to how you can mount a fusion blaster arm on a 2x4 to make a gun, or using them to make a new turret. That way robot weapons and human weapons stay separate things.

**Comment by chaosvolt** [comment]
Interesting. The tankbot is, if I recall, a notable example of a robot assigned a non-player dummy weapon. Then again, when's the last time anyone has even seen a tankbot use its main gun? ;w;

**Comment by mugling** [comment]
Quite the opposite approach is being preferred (for example the monster attack actors) and eventually vehicle turrets. The problem with such one-of definition is that they rapidly become outdated and unbalanced against the player weapons
