### ISSUE TITLE
Going to sleep while playing an instrument results in "Something is making noise"

### ISSUE THREAD

**Issue by nanovad** [CleverRaven/Cataclysm-DDA#14791]
Just tried to go to sleep when playing a harmonica. I kept waking up immediately with "Something is making noise" until I disabled it.
Sleeping should make you stop playing instruments automatically.
Is there any way to tell if an object is an instrument? If so, the player could either be kept awake, or the 'offending' noisemaker could be deactivated.

**Comment by Rivet-the-Zombie** [comment]
Snoring through the reeds of your harmonica maybe?

Yeah, this is definitely a weird behavior that shouldn't be happening.

**Comment by Zireael07** [comment]
> 'offending' noisemaker

<3

**Comment by i2amroy** [comment]
You're just so bluesy that not even sleep can stop the beat! :P
