### ISSUE TITLE
House generation has a weird habit of duplicating specific mapgen in a small area.

### ISSUE THREAD

**Issue by DanmakuDan** [CleverRaven/Cataclysm-DDA#14803]
Over the last month or more, I've noticed that certain houses are appearing twice within 2-3 overmap tiles of each other. For example, the house with an outdoor grill party setup appeared twice in a row, with the houses right next to each other. I don't know if the repeat generation is related to how many candidates are being generated in one pass (player spawning covering an X by Y area, or revealing a row of houses by traveling in one direction).

**Comment by i2amroy** [comment]
For what it's worth this is something that may be simply explained by RNG rolls. At the current point if there are two houses next to each other the chance of the RNG picking the same specific house twice is sitting right around 2.4%, so if you've looked at more than 50 pairs of houses than it's pretty likely that you're going to run into at least one duplicate that is right next to it's copy. If that is the case then this problem should automatically sort itself out as we add more houses to the pool.

**Comment by mugling** [comment]
> For what it's worth this is something that may be simply explained by RNG rolls

Likely this.

> If that is the case then this problem should automatically sort itself out as we add more houses to the pool.

This is ongoing, for example see #15722
