### ISSUE TITLE
[Suggestion] Thermal lances, and possible weaponization

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#14810]
This is perhaps poorly timed due to due recent discussion regarding balancing of the acetylene torch, but I had an idea that I initially thought was best as only a joke suggestion, before ideas started to hit me regarding possible ways to make it actually plausible (the actual "joke" was specifically weaponizing this suggestion for a Fallout shout-out, not the tool idea itself).

Basically, a thermal lance as an alternative cutting tool. Depending on what resources it ends up requiring, it might even be viable to make it a reloadable source of torch-cutting, but this would need a lot to balance it. Either way, I'll go through an array of POSSIBLE ideas for this.

* Possibility of finding pre-assembled, disposable thermal lances. This idea has little reason for existence beyond flavor and variety, unless its balance of size and uses-per-tool can give it a sensible niche relative to acetylene torches.
* An alternative would be rare, reloadable thermal lances with whatever balancing factors are needed to MAKE them reasonable as an alternative. At a minimum you need pressurized oxygen, and steel (sometimes a bit of aluminum) rods assuming they aren't left abstract. If BOTH aren't abstracted out, this allows a basic way to restrict usage by having the ammo basically be all the prerequisite materials in one usable package. Making them craftable (possibly an inferior or inefficient alternative) might be acceptable, but it might FURTHER require balancing to be sensible. Even then, I can see this ammo idea being booklearned-only.
* An additional option is the possibility of simple makeshift cutting tools. This would logically need to be booklearned-only, and require an assortment for (potentially hard to replace) items for an inefficient, ultimately non-reloadable tool. Dismantling to recover whatever's still reusable might still be an option.
* Yet another option might be to keep things simple and restrict things to an item that only requires a simple resource PLUS power from a UPS. Whether it merely be oxygen, merely be metal, or even a proprietary ammo item, this allows us to beat it with the rarity stick if it becomes necessary.
* And finally, the punchline to my original joke suggestion, weaponizing the device by crafting a version you can burnstab things with. Unsure how to implement it, but the old-and-unwieldy option of using a (short) ranged attack might be the less annoying method. The "fire weapon" option could also work, though. Add that to the list of things that probably won't be autolearned.

Regardless of what form it would take, it might be viable as something that's exclusively a cutting tool. An acetylene torch is a must-have for enterprising survivor because it's an entry tool, a hassle-free (but not logistics-free) vehicle repair tool, AND useful for an assortment of crafting recipes.

A tool that's specialized in being a door-cutter would certainly be useful, but not the versatile wonder device that is an acetylene torch. Which does at least give a specialist tool a niche that most of the weld/solder tools don't cover, and make it (slightly) less of a pain in the ass to balance.

In any case, apologies for what is ultimately a poorly-timed suggestion.

**Comment by kevingranade** [comment]
As a cutting tool its great, as a weapon it's pretty terrible, yes they'd do respectable damage if used in a stabbly motion, but they'd be prohibitively unwieldy, something like -5 to-hit as a ballpark.  That having been said, giving an active thermal lance decent cutting damage and terrible to-hit might be worthwhile, who knows, there might be a slow-moving but super tough enemy it would be worth using on, maybe a shoggoth.

**Comment by chaosvolt** [comment]
So a similar "awesome yet impractical" idea as the chainsaw lajatang?

Granted, that's part of the reason behind making the weaponized version a different item. Though the other part would be the fact that a flame-weapon or pseudo-gun might be incompatible with giving it the cutting tool's use_action.

**Comment by mugling** [comment]
As discussed elsewhere such weapons could be PR'd as part of an `unrealistic weapons` mod
