### ISSUE TITLE
Build error in linux under file requirements.cpp

### ISSUE THREAD

**Issue by heema** [CleverRaven/Cataclysm-DDA#14813]
using arch linux 64

while compiling with the command
make CLANG=1 CCACHE=1 RELEASE=1 TILES=1 SOUND=1 LUA=1

gives this error:

src/requirements.cpp:653:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
    return std::move( ret );
           ^
src/requirements.cpp:653:12: note: remove std::move call here
    return std::move( ret );
           ^~~~~~~~~~~    ~
1 error generated.
Makefile:553: recipe for target 'obj/tiles/requirements.o' failed
make: *** [obj/tiles/requirements.o] Error 1

![err](https://cloud.githubusercontent.com/assets/287527/12265161/49c77f3a-b944-11e5-95f6-59cad320d045.jpg)

**solution:**

changed line number 653
from : return std::move( ret );
to : return ret;

fixed the error

**Comment by kevingranade** [comment]
Fix merged
