### ISSUE TITLE
color on bookshelf map position

### ISSUE THREAD

**Issue by karols146** [CleverRaven/Cataclysm-DDA#14819]
Updated couple days ago, but there is no way to see that title. 
Any way to change that or it just should be like this ?
http://prntscr.com/9pdbz8

**Comment by nanovad** [comment]
Colors are a nice orange/gray on my terminal. I think it's just your color scheme.
What OS/build are you using? Tiles or ASCII?

**Comment by joneskun** [comment]
Looks like Terminal on osx. There are some nice SIMBL utils for tweaking Terminal out there, including a color wheel for ansi color codes, or you could use an alternative xterm derivative. If you don't into tweaking or rolling your own the console/tiles experimentals (thanks Narc!) work great under wine/parallels/vmware.

**Comment by karols146** [comment]
nanovad what do you use ?

**Comment by nanovad** [comment]
GNOME terminal on Linux with the Linux color scheme.

**Comment by kevingranade** [comment]
Contrast is bad with your particular color scheme, we can't control it from within the application.
