### ISSUE TITLE
[Suggestion] Rework Weather Reader CBM

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#14821]
At the moment this is one of the most useless CBMs. Its a cool feature but its not really worth the risk of install or the power drain. Some thoughts I had to make it more useful were if we took down the power cost from 10 to 5 or even 1 and added a second bundled passive CBM that just gave you the temperature all the time like the diving watch. This would be pretty easy to implement as the functionality already exists in void game::draw_sidebar() and you could just add it to existing characters for save game support. Is this a good addition? Anyone have any other ideas?
Edit: The cost is actually 25.

**Comment by Rivet-the-Zombie** [comment]
>added a second bundled passive CBM that just gave you the temperature all the time

It wouldn't even require an extra CBM; we could make this a side effect of having it in the first place.

**Comment by Cyrano7** [comment]
ohhh your right. I was thinking about has_active_bionic because it was a active bionic. I could just use has_bionic. Silly me.

**Comment by Core0verload** [comment]
@Rivet-the-Zombie, can you close it?
