### ISSUE TITLE
Dehydrated meat seems strictly superior to canned

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#14829]
No need for tin cans or glass jars, or even water, to make.
Better volume efficiency in case of glass jars.
Less skill requirement and faster to make.
Useable in more recipes, according to item browser.

One drawback is dehydrating uses more meat (2 dehydrated strips are typically equivalent to 1 chunk of canned meat, but take twice the ingredients to make), but my experience has been typically that so much meat goes to waste anyway.

Canned meat also has a slight advantage in nutrition, but this almost never comes up unless you eat it directly instead of using it in a recipe.

**Comment by Mecares** [comment]
Well it has higher energy requirements (takes more charges to craft) perhaps it could also be balanced via the crafting time which is currently quite short (18 min) compared to canned (24 min) and sealed jar (30 min)

**Comment by Marrim** [comment]
Doubt that would be enough to make me ever want to switch to canned meat. Typically at that point in character advancement, time is a cheaper investment than a gazillion of glass jars.

Maybe canned meat should be buffed instead since it takes so much investment to make, and has worse return than dehydrated meat.

**Comment by Mecares** [comment]
If the big difference is the not needed container contrary to other methods, then one could argue that dehydrated meat will hardly stay dehydrated if it is not stored in a container that prevents contact with air humidity and therefor dehydrated meat would need some kind of container to stay edible over extended time.

**Comment by Coolthulhu** [comment]
The main appeal of dehydrated meat is the low requirement of crafting and storing it.
I'd rather double its crafting cost than remove the easy storage.

Plus, if we're getting this deep in realism, most dry food spoils when stored badly - flour, rice, powdered anything.
We'd need a lower grade "PRESERVE" flag used for all dried food containers.
And the ability to put food back into containers.

**Comment by chaosvolt** [comment]
Hmm. I always assumed that the big balancing factor was the need for a food dehydrator or charcoal smoker. And most of my characters rarely find a dehydrator before they hit level 3 cooking, at which point Jerkymania ensues.

**Comment by pingpong2011** [comment]
A dehydrator item would be nice. We already have stuff like the charcoal furnace, which is a placeable that converts one item to another over time. A dehydrator could be a charged item you place to convert non-rotten meats to dehydrated meats after so much time. Thinking about it, are there special place-ables like braziers that consume pre-existing charge over time?

This item could also be useful for fruits, and would remove a category of recipes from the cooking menus. This could also be useful because if the code worked well, you could do the same thing with smoked or even dried foods and such, i.e. the cooking item is placed to passively cook instead of being a static recipe.

**Comment by chaosvolt** [comment]
> A dehydrator item would be nice. We already have stuff like the charcoal furnace, which is a placeable that converts one item to another over time. A dehydrator could be a charged item you place to convert non-rotten meats to dehydrated meats after so much time.

Derp? Unless you mean a furniture version, we already have a food dehydrator. :V

**Comment by Soyweiser** [comment]
Hey, just an update, I think the canned meat is even worse nowadays, as for some recipes you need a special can sealer : http://cdda-trunk.estilofusion.com/can_sealer which has no crafting recipe, and I have never found.

**Comment by Leland** [comment]
This thread hasn't seen an update in about 8 months. Closing for now. If anyone is still interested, I can reopen... or feel free to just make a new issue!
