### ISSUE TITLE
[Suggestion/Request] Add world-relative controls to iso tiles mode.

### ISSUE THREAD

**Issue by SeanMirrsen** [CleverRaven/Cataclysm-DDA#14828]
Now, I may not be playing *any* tiles mode often, let alone iso tiles. But I tried it out recently.

I have to say, the proposed default controls are hideous. Seeing as I lack a numpad (playing on a laplet), I not only have to resort to yubn keys more often, but I also *can't access half the map squares, when moving, viewing, or targeting*, without using them. Yes I know all controls can be rebound, but how about adding profiles for control sets then? I can't rebind controls every time I want to check out a new iso set, as I still primarily play in ASCII. And it's not exactly a very easy task with the ingame interface.

There's a reason camera-relative controls are only ever set by default in isometric-view games that *do not have tile-based movement*. Even in isometric strategy games like the Super Robot Wars Alpha games on the Playstation, the *option* to use camera-relative controls is not the default.

IIRC there already was a PR to allow it as an option. I'm not going to point fingers, but whoever's bright idea it was to turn it down, I really urge you to reconsider.

**Comment by hitbutton** [comment]
> I also can't access half the map squares, when moving, viewing, or targeting, without using them.

This does seems a very valid criticism, and a good reason for the control scheme to be optional.

**Comment by hitbutton** [comment]
It does subvert expectations though. People expect to be able to select any tile moving the cursor with the keys associated with cardinal directions, and its a reason people might have that a control system feels "wierd" without being able to exactly define why.

**Comment by SeanMirrsen** [comment]
>If you are playing a roguelike with any bias against using diagonal movement, you're already doing yourself an extreme disservice. No part of the game is balanced or designed for players who don't move diagonally.

I do move diagonally. I learned to use the yubn keys early on. Problem is, they're in the middle of the keyboard, and the arrow keys are off in the corner. I have to split my attention between the arrow keys - which I use for navigating menus as well - to the yubn block, which, while far from a crippling inconvenience, is an inconvenience nevertheless. In other words, I don't move diagonally unless I *have to*, and I never use diagonals for moving the viewing or aiming cursor because it's pointless there. With circular distances on, I'm at no severe disadvantage sticking to four directions even in combat, a lot of the time. And that's in regular, non-isometric situations.

In iso, I basically have to constantly keep one hand on the diagonals, because in cardinal directions I'm missing half the map, like some misplaced chess bishop, which drives the inconvenience rather higher.

**Comment by kevingranade** [comment]
I'm not adding an option for a basically unusable rotated input scheme because you don't want to map an 8-way direction cluster, this is specifically what hjkl is for and it's why it's the default.
Easily swappable input mappoings would be an extremely welcome addition.

**Comment by SeanMirrsen** [comment]
"Basically unusable" is what the current scheme is for me. :\
You're willing to clutter tile-drawing code for the sake of a temporary solution to isometric combat text display, but a simple switch for isometric controls is too much? *facepalm*

**Comment by kevingranade** [comment]
1. I don't know what you're talking about WRT SCT.
2. It's not remotely a "simple switch", it would require special handling everywhere iso input is handled to make it act correctly with iso, orthogonal, and iso-with-option.
3. Even if the code were simple, the effect on the project is not small, adding additional system configurations has a massively disproportionate impact on creation and hiding of bugs, since it multiplies the number of code paths that are effectively "dead" in one configuration or another.  In particular, since you would be in the vast minority in using the option you suggest, it would be very prone to breakage and to staying broken for long periods, since no developers would be testing against it before releasing changes.

**Comment by hitbutton** [comment]
Code-wise, everywhere that currently checks (iso_mode && use_tiles) to see if control should be rotated could instead check (iso_mode && use_tiles && option). The logic of whether to rotate control should also be abstracted out to a single function but thats a separate matter.

The point about introducing multiple options making testing more difficult is definitely pertinent. FWIW I would quite likely use the option that SeanMirrsen is advocating for. I've used both control schemes in isometric games in the past, and marginally prefer non-rotated.

There are a lot of differences between Diagonal vs Cardinal movement in a grid, its not simply a matter of direction. The question is whether you preserve the control direction:
1. Pressing "Up" takes you to upwards in screen space
or you preserve control behavior:
2. Pressing "Up" then "Right" will take you to the same place as "Diagonal UpRight"

In my experience a change in the first is easier to adapt to and internalise than a change in the second.
