### ISSUE TITLE
Explosions are drawn away from their origin

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14834]
Ubuntu 14.04, native curses mode (non-tiles build)
Explosions are drawn significantly offset from their origin, often off screen.

**Comment by mutt3x** [comment]
It seems its always in the lower right region (for me at least).
win7 64-bit tiles (with no tiles)


![Glitch](http://i.imgur.com/BCFKOZt.jpg)

**Comment by BevapDin** [comment]
So, did the linked PR fix this issue?
