### ISSUE TITLE
vibrator working on male chars

### ISSUE THREAD

**Issue by taclipoka** [CleverRaven/Cataclysm-DDA#14833]
shouldn't it work only with women?

**Comment by Malkeus** [comment]
Oi...my understanding is this device is a muscle massager, rather than a phallic symbol. And in any case, men can use the phallic object as well. I'm sure google can provide you with examples.

**Comment by RadaRadaRada** [comment]
The description of vibrator is left vague on purpose. It could be muscle massager or some sort of sex item to get off (doesn't even have to be phallic in shape).

**Comment by chaosvolt** [comment]
[Immature Humor Intensifies]

**Comment by nanovad** [comment]
[vibrating intensifies] :+1:

**Comment by Dalenacio** [comment]
I mean, when you use the chesthole tileset, which is default these days if I recall, it DOES have an illustration that suggests a phallic nature, an it IS bright pink and plastic. But let's not jump to unbecoming assumptions.
[vibrating noise in the background]

**Comment by chaosvolt** [comment]
It's extra hilarious in the MShock series.

**Comment by MisterFelixFox** [comment]
and they said there would be no confusion

**Comment by chaosvolt** [comment]
Right. Totally just a back massager. o3o

**Comment by i2amroy** [comment]
>Right. Totally just a back massager. o3o

To be fair that's what the very first vibrators were sold as. :P

And yeah, the description is purposely vague. What different tilesets interpret that description as is totally up to them and is completely unrelated. :P

**Comment by Chezzo** [comment]
Fun fact: There is a special noise that is played with the sound pack when you hit something with a vibrator.

That, and dolls, horns, airhorns...

And, of course, the cowbell.

**Comment by chaosvolt** [comment]
Oh god that sounds like a real reason to bother with the soundpack. o3o
