### ISSUE TITLE
http://en.cataclysmdda.com/ and http://smf.cataclysmdda.com/index.php appear to be down

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#14848]
Recently the forums have been down, since the past few days. The first sign I saw of this was only an intermittent occurrence, but soon I found it to be out completely.

> Connection Problems
> Sorry, SMF was unable to connect to the database. This may be caused by the server being busy. Please try again later. 

So I was going to try and find the IRC to determine whether anyone was aware of this, and what the cause was, after I'd checked that it wasn't an issue on my end. Then I realized that, having never BEEN on the IRC before, I couldn't find it. So I figured I'd check the main site.

> Application Error
> An error occurred in the application and your page could not be served. Please try again in a few moments.
> If you are the application owner, check your logs for details.

Same problem, consistent error, and doesn't seem to be solely on my end.

**Comment by Zireael07** [comment]
Having the same problems for at least two days.

**Comment by chaosvolt** [comment]
Glad to see more evidence that it's not merely my potato of a computer.

Any word of it on the IRC? Or is that down too? ._.

**Comment by Zireael07** [comment]
IRC is up: #CataclysmDDA on Freenode

**Comment by Malkeus** [comment]
http://webchat.freenode.net/?channels=#CataclysmDDA
Full address for the IRC web client. Join us as we discuss irrelevancies and ignore the looming website issue...

**Comment by chaosvolt** [comment]
Thank you. Was on it briefly, not many others on at the time. >.>

**Comment by Malkeus** [comment]
midday/early morning CST is pretty dead there. it picks up around 6 cst, until 2am or so it starts tapering off to just the diehard nosleepers ;)

**Comment by chaosvolt** [comment]
As I figured, yeah. XP

**Comment by chaosvolt** [comment]
Huh. Looks like the forum site is back for the moment, haven't checked the main site.

What'd I miss?
