### ISSUE TITLE
Add a "salvaged" class of CBMs.

### ISSUE THREAD

**Issue by Dalenacio** [CleverRaven/Cataclysm-DDA#14845]
CBMs are not bionics. They are bionic installation *kits*. They come with all the tools you'll need to install a bionic, even on yourself. That makes sense, after all.

However, what makes less sense is CBMs that come from butchered enemies, such as shocker zombies or zombie scientists. You literally just cut out the implant from the festering body, why does it come with the tools? Obviously, you should not be able to rip out the leukocyte breeding system out of someone's corpse and instantly install it on yourself.

To solve this inconsistency, and to make bionic installation a bit more difficult (*not* risky, mind you), I propose making such CBMs have the "reclaimed" tag. When you have a "reclaimed" CBM, it means that you have the implant, in good condition, but *not* the installation kit that came with the original packaging.

The way to install them would be very simple. you would simply need another CBM, non-reclaimed, and which you are not intending on installing, and use the tools from that one to install your "reclaimed" one. This could be achieved through the crafting menu or simply through an "a"ctivation menu.

Thoughts and ideas?

**Comment by illi-kun** [comment]
You will find requested thoughts and ideas in #12964.
