### ISSUE TITLE
Miscategorized item list

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14855]
Some items in the game are categorized badly. I made an issue for food: #14851 because in some cases it may require semi-complex mechanical changes.
In other cases it may be as simple as changing the category of an item or moving it into a different file.

List of items:
- [ ] Crafting ingredients that are comestibles but shouldn't ever be consumed, like salt, bleach and seeds (those which grant 0 nutrition)
- [ ] Construction items that can double as weapons like pipes and two-by-fours
- [x] Crafting items that aren't weapons but are placed in melee.json, for example processor, glass shard, pinecone
- [x] Generic items that don't fit anywhere but are placed in melee.json like wire or candlestick
- [x] Half of melee.json doesn't fit actually

Anything else?

**Comment by Zireael07** [comment]
Uh, I think someone recently moved some of the bloat from melee.json?

**Comment by Coolthulhu** [comment]
Yeah, that was a good step towards cleaning that up. But there is still a load of totally-not-melee stuff in there - almost (or over?) a half of the file.

**Comment by Zireael07** [comment]
Also, concerning foodstuffs - there's two outstanding PRs touching comestibles.json (#14613 and #13857 which requires the former before further work can be done)

**Comment by illi-kun** [comment]
Yeah, I did it and want to continue but I'm waiting for merging other PRs in line (which change the same json files). From other point of view, they look stale so I'll ignore them soon.

**Comment by chaosvolt** [comment]
Hmm. I guess it does seem odd to sort sticks, boards, pipes etc as weapons.

However, well over half my inventory screen in any given game tends to be taken up by the TOOLS section, not weapons.

If anything, shitloads of lighters, cash cards, and matchbooks that all have different levels of charge account for way more inventory clutter than a few misplaced construction materials.

**Comment by kevingranade** [comment]
There is some confusion here, the category and the file an item is defined
in don't necessarily have anything to do with each other.

**Comment by chaosvolt** [comment]
> In other cases it may be as simple as changing the category of an item or moving it into a different file.

So, is the primary focus of this issue whether the category of an item is correct, the file of an item is correct, or both?

The first would make this issue relevant to players, the second makes this issue relevant to the contributors, and third makes it important to both.

**Comment by illi-kun** [comment]
Good point, Kevin, and it's much easier to define proper category as first step and move item to proper json as second step. Currently I'm on ```melee.json```, let's see what can I do.

**Comment by illi-kun** [comment]
Blitz quiz! Choose a correct category for following items:
* burnt out torch (tools or spare parts or other)?
* hockey stick (weapons or other)?
* golf club (weapons or other)?
* sharpened toothbrush (weapons or other)?

**Comment by Rivet-the-Zombie** [comment]
>burnt out torch

I'd say 'other'.

'Weapons' for the rest.

**Comment by illi-kun** [comment]
Sport is  ~~Life~~ Death. _Accepted!_

**Comment by illi-kun** [comment]
What is a proper file for gas discount cards? ```generic.json```?

**Comment by Rivet-the-Zombie** [comment]
I almost want to say *tools* because they're a means to an end, but they're not really used as a tool either, so *generic* seems like the best choice.

**Comment by illi-kun** [comment]
That's exactly what I'm thinking about it, thanks for confirming my thoughts.

**Comment by Leland** [comment]
Per #19930, seeds and containers should probably get their own categories.

**Comment by kevingranade** [comment]
Omnibus issue
