### ISSUE TITLE
Un-comestible inedible stuff

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14851]
Stuff like most seeds, flour, salt, bleach etc. only pollutes the "eat" menu, there is no reason for anyone to ever consume any of those.
Basically, anything with fun, nutrition and quench all below 1 and without an use action should be non-comestible.

Making it non-comestible could also help to break up comestibles.json, which got bloated up to almost 700 entries, many of which are crafting ingredients (bleach, ammonia, flour), seeds or drugs.

Then, moving MEDS to another file could also help. Meds are currently comestibles, but separating them from food both makes sense and could help making them non-comestibles eventually.
This would free the menu up a bit and help prevent stuff like gourmand helping with heroin injections and buffing morale boost from heroin - even if gourmand was just a generic hedonist, injecting heroin should still take more the full time.

**Comment by sparr** [comment]
It is plausible to intentionally eat salt to increase thirst.

**Comment by Rivet-the-Zombie** [comment]
Flour might not be ready-to-eat when you get it, but desperate characters really ought to be allowed to gag some down if they're starving.

**Comment by chaosvolt** [comment]
Yeah. Eating flour if you have nothing else, I can see. Drinking bleach though? No. Just no.

Only issue here is tainted meat and such. Would you really eat it? And yet it might or might not need to be a comestible in order to rot.

Would it maybe be sane for raw meat and other "you should only eat this if you have no choice" to maybe prompt a warning? I've mistyped and inhaled unboiled water and raw meat too many damn times.

**Comment by Rivet-the-Zombie** [comment]
>Only issue here is tainted meat and such. Would you really eat it?

There's a perk (Eater of the Dead) whose whole purpose is to allow you to do just that.

**Comment by chaosvolt** [comment]
True. Ahem. Traits and of course abuse of the revenant crown. Though the latter won't protect from morale loss from tainted meat being disgusting. o3o

**Comment by hitbutton** [comment]
> Stuff like most seeds, flour, salt, bleach etc. only pollutes the "eat" menu

If this is the issue, then better sorting / categorisation options for the menu might be a better answer?

**Comment by Rivet-the-Zombie** [comment]
We really could use a few more categories on the inventory screen, like medical drugs and items versus recreational substances or containers versus *everything else* in the 'other' category.

**Comment by hitbutton** [comment]
To clarify: I was talking about the "Consume Item" menu (E) which has absolutely no categorisation or sorting at all.

**Comment by Coolthulhu** [comment]
> It is plausible to intentionally eat salt to increase thirst.

Why would you ever want to increase thirst? Thirst doesn't limit consumption in any way.

> Flour might not be ready-to-eat when you get it, but desperate characters really ought to be allowed to gag some down if they're starving.

Flatbread is trivial to craft, flour is way too precious to eat it for the minimal nutrition it provides (1 point, as opposed to 40 per flour unit as flatbread).

> If this is the issue, then better sorting / categorisation options for the menu might be a better answer?

For (most) seeds and salt? No, those are simply not food and there is never a reason to eat those. The exceptions are seeds that occupy volume (fungal and hemp), but it's better to have exceptions than to have something completely useless (ability to eat seeds that give no nutrition and no effects) and yet takes slots in the menu.

Could work for flour, though I haven't ran into a situation where consuming flour would be beneficial. Not once during the whole time I played DDA.
Had few characters subsist on zombie meat (nearly harmless with Poison Resistance) and few others fast into starvation while waiting out winter (to gorge on bountiful spring forage drops), though.

**Comment by Zireael07** [comment]
Many seeds are edible IRL.

As for salt, eating it can be used to induce vomiting to purge poisons.

**Comment by Mecares** [comment]
Well one portion of Salt in game are 60g enough to kill a human of 60kg (LD50 is 1g/kg bodyweight) which makes me wonder why anyone would want to endanger his life by taking more poison to get rid of poison if a finger in your throat gets the same results.

**Comment by iceball3** [comment]
http://whs.rocklinusd.org/documents/Science/Lethal_Dose_Table.pdf
According to this, the 50% lethal dose for humans is around 12g/kg, which means 120g for a 60 kg human.

**Comment by pingpong2011** [comment]
Something important: the menu can show whatever it wants, but you can have the action still go through. It's pretty common in inventory-biased games as far as I know, to have "extended" actions which either you don't expect, or are bad ideas, but are permitted anyway. I'm sure it's in Nethack, as there are a lot of jokes of eating horrible things (like a Gorgon's head), or wielding dumb stuff. I'm actually kinda horrified it's not that way already.

**Comment by elricsfate** [comment]
@pingpong2011 

I agree with Pingpong that this should be a feature. It is in many other rogue-likes
