### ISSUE TITLE
Dissembling a two-by-four crashes the game

### ISSUE THREAD

**Issue by pingpong2011** [CleverRaven/Cataclysm-DDA#14876]
Running 8883 g142debb and, yeah, I picked up a two-by-four and wanted to dissemble it, presumably into skewers, and the game just wept and crashed.

**Comment by ValidAQ** [comment]
I think that was fixed already by #14785, seeing as I get "The two by four cannot be disassembled!" in Win x86 0.C-9321-g13890ac.

**Comment by illi-kun** [comment]
ValidAQ is right, the latest experimental build works correctly.
