### ISSUE TITLE
[Bug]R13 Power Armor now increases weight for each unit of power

### ISSUE THREAD

**Issue by Nymall** [CleverRaven/Cataclysm-DDA#14872]
5 plutonium cells(weight:0.1 kg each) when input to the R13 Power Armor(weight: 0.07kg) cause it's weight to become 206kg.

Exp Build 4203

**Comment by Rivet-the-Zombie** [comment]
The RM13 armor should weigh 6.82 kilograms when unloaded, not .07 kilograms.

The plutonium weight thing is particularly strange as well.

**Comment by mugling** [comment]
Possibly relates to #14837?

**Comment by mugling** [comment]
> R13 Power Armor

What is the itype_id for this, I'm struggling to reproduce this?

**Comment by ValidAQ** [comment]
`rm13_armor`, I believe.
Also, can confirm the bug occurs on Win x86 Curses 0.C-9277-g6d9e541.
Armor weighs 6.8 kg when unloaded, 406.8 kg when loaded with 10 plutonium cells.

**Comment by Nymall** [comment]
Reverting to Exp 4200 removed the issue. So it's probably somewhere between 4200 and 4203.

**Comment by Nymall** [comment]
Looking farther into it, there's three commits in the time period that might have caused the change:

https://github.com/CleverRaven/Cataclysm-DDA/commit/bae98c6aa2c67abad29f2a4c16b71b6f129bb219
https://github.com/CleverRaven/Cataclysm-DDA/commit/f2960e0dc9be2a3fa5ac7c06158c3cbdf9edd7b1
https://github.com/CleverRaven/Cataclysm-DDA/commit/c849e01f08c68a82685375c70d5e5cce48aef6f7

These are the commits made between 4200, and 4203 where I encountered the error. Unfortunatly, I don't have the time to investigate further.

**Comment by Zireael07** [comment]
Those three are:
1) calories
2) iso tiles
3) pixel minimap

So none of those even touch charges/ammo.

**Comment by ValidAQ** [comment]
After looking at this closer, I think the problem occurs because in `item::weight` `if ( ammo_data() )` is true for plutonium-using devices, so `else if( ammo_type() == "plutonium" )` never happens and added weight isn't divided by 500.
Switching their places around, like this:
```
        if( ammo_type() == "plutonium" ) {
            ret += ammo_remaining() * find_type( default_ammo( ammo_type() ) )->weight / 500;
        } else if ( ammo_data() ) {
            ret += ammo_remaining() * ammo_data()->weight;
        } else if ( ammo_type() != "null" ) {
            ret += ammo_remaining() * find_type( default_ammo( ammo_type() ) )->weight;
        }
```
seems to fix the problem, but I'm not sure I understand the logic of this block completely, so I might've missed something.

**Comment by mugling** [comment]
@ValidAQ this is indeed #14837, I'll look in to a fix

**Comment by mugling** [comment]
305dfe2 fixes for me, and for you @Nymall?
