### ISSUE TITLE
NPCs get blocked by vermin

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14883]
As in title. They won't displace or attack them.

**Comment by illi-kun** [comment]
This shouldn't be a release blocker anymore since vermins are disabled; I propose to mark this as a long-term issue (and keep it as a reminder for anyone who will re-implement vermins).

**Comment by kevingranade** [comment]
Or close it, since vermin no longer exist.

**Comment by Coolthulhu** [comment]
If someone re-implements vermin, there will be a lot to review anyway. The would probably get a separate critter tracker or something like that.

**Comment by illi-kun** [comment]
Well, that's another possible solution, huh.
