### ISSUE TITLE
Discarding remote control does not exit remote control interface.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#14886]
Spawn in a RC car, activate it, drop it on the ground, spawn a RC control item, activate it, control the car, move the car around, throw the RC control item.
Expected:
Lose control of RC car and move normally.
Actual:
You continue controlling RC car with your mind, but are unable to move your own body.

Thanks to Seaweedseal on IRC for reporting.

**Comment by hitbutton** [comment]
> Thanks to Seaweedseal on IRC for reporting.

You're welcome, but don't call me Seaweedseal :)
