### ISSUE TITLE
NPCs only use melee damage to evaluate their effectiveness.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#14887]
When a NPC is using the "engage weak" engagement rule, it uses npc::average_damage_dealt() to estimate its damage output, meaning if it has a good ranged weapon it will assume it is incapable of fighting much of anything.

**Comment by chaosvolt** [comment]
So, in a nutshell...

![huehuehue](https://i.ytimg.com/vi/tytiJ6AJmos/maxresdefault.jpg)
