### ISSUE TITLE
New NPC engagement mode, "onmly engage if you don't have to move".

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#14889]
While messing with some NPC AI code, I noticed "engage when close" has a pretty major problem in that it will not ensure that the NPC doesn't run off attacking monsters, only that they will not move very far *per monster*.  If there is a steady stream of monsters, the NPC will walk up the chain indefinitely and probably get into trouble.

I think a mode of "engage, but don't move to do it", would do what we really want, which is the NPC will shoot enemies when it has a good shot, but it won't chase them down to do it.  Similarly melee NPCs will only defend themselves when a monster reaches them instead of running everywhere hacking at them.

**Comment by stk2008** [comment]
This is awesome many times ive lost and had to run after an npc and help
kill monsters because he/she was insisitng we kill every bloody one of them.

Even though we could have snuck around and avoided combat in the first place

**Comment by Coolthulhu** [comment]
Also, the "don't engage unless close" could be changed to be "centered" around the player rather than NPC.
In most cases it would be useful for the NPC to protect the crafting/butchering/welding player and it would also fix the problem with NPCs running off.

**Comment by kevingranade** [comment]
Probably separate out the "center point", which may be the player, or may be a spot the NPC is guarding, or may be the NPC themselves (in case they are acting on "got to some location).
I think "attack, but don't move to attack" stands on its own either way.

**Comment by chaosvolt** [comment]
And that is why I tend to just leave the NPCs set to "only engage what I attack" mode. >.>

Even then that has the disadvantages in that they won't protect you automatically if you're occupied, and if the target runs off they like to pursue.

**Comment by mugling** [comment]
#15506 added the option *'attack if you don't need to move'*
