### ISSUE TITLE
Stuck weapon pulling can remove "NO_UNWIELD" items

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14882]
If you manage to hit something with that -8 to_hit of electronic handcuffs, they can get stuck inside the target, which unequips them from the player.

Doesn't affect bionic weapons because unarmed weapons can't be stuck in target.
Could affect the arcanamod stormbringer, but it would most likely require low skills and strength to happen.

**Comment by mugling** [comment]
We could check `player::can_unwield` from #14870 in `player::melee_special_effects` before applying the stuck weapon penalty.

**Comment by chaosvolt** [comment]
Would it make sense to give handcuffs and an active cursed sword the "no stuckins" flag?

**Comment by pingpong2011** [comment]
Doesn't stuck-in effect only happen to piercing or cutting weapons?

**Comment by mugling** [comment]
Stuck weapons don't exist any more
