### ISSUE TITLE
NPCs ignore relatively weak monsters until they are extremely close.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#14888]
Spawn a friendly NPC with a decent ranged weapon and some ammo, give it decent ranged stats/skills.
Set the NPC engagement rule to something relatively permissive, like "engage nearby" or "engage everything".
Spawn a regular zombie at ~20 squares away from the NPC.
Expected: NPC waits until it has a decent chance of hitting and starts shooting the zombie as it approaches.
Actual: NPC ignores zombie until it is about 2 squares away, then unloads on it.

The reason seems to be the code in npc::choose_monster_target(), which calculates a priority score based on the monster and its distance from the NPC (scaled by enemy speed, which is a nice touch).  This code produces a very low score for regular zombies and a lot of other weak enemies, meaning the NPC is literally unaware of their presence until they are very close.

**Comment by chaosvolt** [comment]
I can see this causing problems, yeah.

But on the other hand, that's amusingly consistent with how I play when using a ranged weapon. Always gotta have that maxed-out steadiness.

**Comment by kevingranade** [comment]
While looking at that code it made me realize it would be nice for npcs to
have a personality aspect or similar that influences when they start
firing, more calm ones could wait to the last second, more nervous types
might not even spend the time to aim properly.

**Comment by chaosvolt** [comment]
That does sound like it might be an interesting occurrence.

Do any of the existing NPC stats sound useful for determining that? I think they have a...confidence or something value, or maybe fear. Not sure. If an existing stat can be used for that, that allows for the possibility of NPCs getting worn down and unnerved until they get an itchy trigger finger, rather than it being a fixed part of their personality.

**Comment by Night-Pryanik** [comment]
Well, tested on latest experimental as of April 07 2019.

Gave NPC M14, set it to 10 in all skills, set her engagement rules to engage all enemies and fire when it's convenient.
![изображение](https://user-images.githubusercontent.com/11132525/55679346-04247d00-591b-11e9-8baf-b2283c6a289f.png)

![изображение](https://user-images.githubusercontent.com/11132525/55679330-adb73e80-591a-11e9-9a38-b652793c0c7b.png)

The distance at which she started to fire is 6, which is definitely not 2 tiles away and seems to be just like fine distance for that kind of monster.

Should be closed?
