### ISSUE TITLE
unwielding bionic claws when activating a weapon from a holster.

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#14892]
If you have bionic claws out and you activate a weapon from a holster your claws go into your inventory and your weapon goes in your hand. You can even drop the claws and walk away haha. I imagine it is the same with the bio_blade.

**Comment by chaosvolt** [comment]
I've seen this before. Is this simply an issue that's reoccurred due to (presumably) changes to holster code, or was it an issue that never got fixed and got forgotten about?

**Comment by mugling** [comment]
It can occur in other situations but is most easily reproduced using a holstered item as described above. Relates to #14882 and more distantly to #14885 in that we currently don't correctly enforce `NO_UNWIELD`. #14870 adds a check in `player::wield` but at a minimum we either need to add a similar check to `player::wield_contents` or better yet refactor that function to defer to `player::wield`

**Comment by chaosvolt** [comment]
Again, how old is this bug? I know I've seen this several months ago. >.>

**Comment by John-Candlebury** [comment]
Best thing since Throwable karate!

**Comment by codemime** [comment]
Not an issue anymore.
