### ISSUE TITLE
Hazy clouds and smoke pass through walls

### ISSUE THREAD

**Issue by Sir-Kernicus** [CleverRaven/Cataclysm-DDA#14894]
I looked through some issues and didn't find this listed.  I was in a sporting goods store's back room, and there was hazy clouds passing through the walls.

**Comment by nanovad** [comment]
Yeah, if I smoke a cigarette near a wall, the smoke drifts too... Doesn't this happen with smoker zombies as well?

**Comment by Headjack** [comment]
I think I had this happening a while ago, yeah with smoker zeds. I thought it was addressed though? Must not be if it's still happening.

**Comment by Mshock777** [comment]
Probably will help adding move cost >0 and permeable flag check before spawning fields.
Probably monattack.cpp and mondeath.cpp for smoker and such.
item.cpp and iuse.cpp for smoking.

**Comment by mugling** [comment]
This is mostly resolved by #14894 and once #17425 is done we can use the new `emit` type to hook into the field propagation code @Coolthulhu wrote.
