### ISSUE TITLE
Disturbing Scream morale penalty ignores deafness

### ISSUE THREAD

**Issue by ValidAQ** [CleverRaven/Cataclysm-DDA#14899]
In both cases where this penalty is applied - that is, petrified eye mine event and artifact use - it is applied even if player character would be actually unable to hear the scream itself.
Now, both of these cases obviously have supernatural causes, so I could see these screams affecting the character despite the deafness. 
So the question is - is this intended behavior?

**Comment by karols146** [comment]
I think that if you are deaf, it shouldn't affect you.

**Comment by nanovad** [comment]
I'm not so sure. If only you hear the scream... Then perhaps it's psychological, and not directly linked to your ears (which is where noise dampening gear tries to simulate deafness.)
On the other hand, if the scream is far away or echoes, etc, then it should be canceled out by noise-dampening headgear. I'm curious if it's an actual sound and can attract enemies, or if it's all in the char's head.

**Comment by ValidAQ** [comment]
It is an audible sound, and it works like one. 
Thing is, the morale effect is separate from the actual sound, and will be applied no matter what.

**Comment by chaosvolt** [comment]
You feeeel it in your booones. o3o

Then again yeah, should be consistent.

**Comment by illi-kun** [comment]
It seems to be fixed by #15829.
