### ISSUE TITLE
3D Vision allows targeting through the floor across z-levels.

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#14908]
0.C-9420-gfcdeea5 - Windows 7, 64bit SDL

Exactly as the title states. I noticed this while looting a floating temple from Arcana mod. I'm up on the 3rd floor inside the temple and I can see monsters down below me, pressing 'f' snaps to them down on the ground and I can shoot and kill them through the floor.

This is up in the temple, with a monster on the radar but not on screen: https://i.imgur.com/7NyN9Pe.png
After pressing 'f', it snaps to the target, through the floor and down 2 z-levels: https://i.imgur.com/krEEb5W.png
Something is in the way, a wall, a door, etc. I smashed the door to the north shooting something below me: https://i.imgur.com/x3SuVv6.png
Repeated firings end up killing the monster: https://i.imgur.com/CqaKvaK.png

I will see about reproducing this without any custom mods and get a save file uploaded if needed, but I don't see it happening any differently with a vanilla gun and a zombie.

**Comment by Coolthulhu** [comment]
Targeting is one thing - you should be able to target anything you see. Though monsters seen with clairvoyance should probably get a lower priority.
The bigger problem is that projectiles aren't stopped by the floors.

**Comment by Malkeus** [comment]
I don't think I should be able to see them, since the entire top of the tower is enclosed by walls. And I don't have clairvoyance on.

**Comment by Shadefang** [comment]
I actually had a similar issue to this a few builds ago with IR vision allowing me to target stuff through the floor that's probably related. I'll see if I can replicate it.

**Comment by Coolthulhu** [comment]
Should be fixed now
