### ISSUE TITLE
Mics fixes to sks and mosin nagant.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#14909]
I have noticed some inconsistencies with a couple of fire arms. Specifically the mosin nagant and the sks (could apply to more fire arms but these two come to  mind). 

  The mosin nagant and the sks both an non-detachable integrated magazine. This means they should reload one cartridge at a time (unless stripper clips are used), the mosin already does this but the sks does not.

   Now with bayonets and variants.  The 91/30 mosin has a the ability to attach a bayonet on the muzzle. The sks and the m44 mosin both have integrated bayonets. The sks has an underbarrel folding bayonet while the m44 has one folding from the right side. Internal mods are already a thing so adding this should not be an issue. This would require the sks to lose its underbarrel mod slot however.

  The m44 is meant to be a carbine version of the 91/30, but that is the m38. The m38 is pretty much a m44 with no bayonet. Adding the m38 would be just renaming the m44 and making the m44 a clone of it with an integrated bayonet.

![600px-comparestocks](https://cloud.githubusercontent.com/assets/16777044/12419125/abe54082-be79-11e5-9255-deb0358952ef.png)

**Comment by IFailAtGaming** [comment]
Sks can use either detachable and integrated magazine would post pics but I suck at git

**Comment by Noctifer-de-Mortem** [comment]
With modifications, sure. There are various upgrades to take even ak mags but the stock sks doesn't do that.

**Comment by chaosvolt** [comment]
If there was a way for weapon mods to rermove flags instead of add them, we could implement that by adding a mod for certain rifles to accept detachable magazines.

Though as there's @mugling's series of magazine changes going on, that idea will have to wait. Simply giving it a flag seems acceptable.

**Comment by mugling** [comment]
> If there was a way for weapon mods to rermove flags instead of add them, we could implement that by adding a mod for certain rifles to accept detachable magazines

No more abuse of the gunmod code - it's scary enough as it is

> unless stripper clips are used

This is covered separately in an issue raised by @Rivet-the-Zombie 

> This means they should reload one cartridge at a time

This is fixed in #15770
