### ISSUE TITLE
"Stop wielding [item]?" menu not cancellable

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14910]
This isn't much of a problem in the case of single held item, but it is a regression in case of weapon swaps.

Example:
* Worn rifle with a shoulder strap
* Held knife
* Not enough inventory capacity to store anything
* Trying to wield the rifle
* Under the old menu, player would be asked to drop the knife or do nothing
* Under the new menu, player is asked to select an option, but only one option is allowed. Escaping doesn't work
* Player is forced to drop the held item

**Comment by mugling** [comment]
Does escape not work (that was my intention)

**Comment by mugling** [comment]
Yes, it was supposed to be possible to cancel via escape but I think that got lost somewhere along the way
