### ISSUE TITLE
Pickup::pick_one_up and player::wield code duplication

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14913]
The new `player::wield` menu allows sheathing held knives, storing items in the inventory etc.

`Pickup::pick_one_up` only allows swapping the item on the ground with the held one, but could probably easily use the `player::wield` instead.

**Comment by mugling** [comment]
Noted, I'll look in to that. Also `player::wield_contents` contains some duplicate logic that could be deferred to `player::wield`

**Comment by kevingranade** [comment]
Random observation, not a valid issue.
