### ISSUE TITLE
Acid damage inconsitency

### ISSUE THREAD

**Issue by Soadreqm** [CleverRaven/Cataclysm-DDA#14921]
When standing in an acid puddle wearing an ANBC suit, the acid doesn't seem to do any noticeable damage. This seems reasonable, as the ANBC suit is described as "impermeable", and specifically designed to protect the wearer from hazardous materials. However, the game still spams constant "you were hurt" warnings when attempting to do long actions, and it's possible for clothing under the suit to be damaged. I somehow managed to tear my underwear, which really shouldn't be possible considering the relative coverage values.

I'm not sure how the acid damage is supposed to work, but whether it's puddles, foam or fumes, undamaged clothing with 100% coverage should probably prevent it. If the acid isn't damaging the items, it should be safe to assume that it isn't permeating deep enough to burn skin.

**Comment by Coolthulhu** [comment]
Acid damaging items counts as a bug - it doesn't damage lying items, so it shouldn't damage worn ones either.
#14922 should fix that one.

As for the "You were hurt" message - this one will require some more complex solution.
Currently all attacks trigger this message and acid field is treated like an attack (4 attacks actually).
In most cases it is a good thing to be informed that you are standing in dangerous field, even if it doesn't damage you at the moment.
May need a special case like "if you have 100% coverage with 5+ acid resistance on all affected body parts, don't perform acid attacks at all" or other such hack.

**Comment by chaosvolt** [comment]
Though the only annoying inconsistency I'll note about the lack of acid item damage is you can rapidly loose your legs and feet, while your clothes are unharmed. :V

**Comment by Malkeus** [comment]
https://www.youtube.com/watch?v=y91uHr-QW6A

**Comment by chaosvolt** [comment]
Ow that is some painfully low quality recording. ;w;

**Comment by Malkeus** [comment]
I'm pretty sure that episode predates high def. The audio is really bad though, I agree. 

On topic: It looks like Coolthulhu left a nice blank function describing acid damages effects on armor, just begging to be filled with something painful.
https://github.com/Coolthulhu/Cataclysm-DDA/commit/cadfda78a1344ff42885c47978937a51c89afdd3
