### ISSUE TITLE
Need a way to rotate the view

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14923]
With isometric mode approaching maturity and at least one person on the forums working on a zelda perspective tileset, we need a way to rotate the viewport, probably in 90 degree increments. This feature is important so that the player can more easily see what's hiding "behind" an obstruction.

This will involve making a lot of drawing and input handling code more generally capable.

**Comment by hitbutton** [comment]
This is a feature I've advocated for :)

That said, this wouldn't resolve the obstruction problem where a tile is surrounded by obstructing tiles (for example, a tile bordered by 4 trees). It could also be somewhat disorienting.

I've been pondering something along the lines of defining an extra set of tiles for terrain/furniture that obstructs other tiles. The user could then toggle between the different tiles, essentially turning the drawing of walls on or off (though you could still only see what was in your LOS obviously).

**Comment by sparr** [comment]
a key to toggle half-height tall-sprites is something that appears in some other games

also a way to make tall sprites partially transparent when they obscure something

**Comment by hitbutton** [comment]
Yes, exactly. I was thinking that handing control of that to tiles_config.json (e.g. manually defining the half-height sprites for different ids) would probably be the best approach. That would allow for either of your approaches, on a case by case basis, at the discretion of the tileset author.

**Comment by SeanMirrsen** [comment]
While a good idea in theory, it might be (quoting a Cards Against Humanity card) kind of a mess in practice. Very easy to lose track of which direction is which, you need to add rotated-state code to the main view, the minimap, the overmap, the pixelmap, the AIM window, not to mention the controls.

This would an order of magnitude more work than to add even a simple toggle for world-relative or camera-relative controls, and you probably remember how difficult *that* is. ;) :P

**Comment by Malkeus** [comment]
I've got a question about the half-height sprites thing. Why does it require a separate sprite to implement them?  Would it be possible to add code that displays the top half of the sprite in the space occupied by the bottom half? It may be impractical or ugly without designing the tile around such a thing, but it would decrease the overall size of a tileset, which would seem important, since the iso tilesets tend to be quite a bit larger than the others.

**Comment by sparr** [comment]
@Malkeus "top half" is non-trivial to determine for isometric sprites

**Comment by Malkeus** [comment]
Fair enough, I had to ask though. It just occured to me how rough that idea would be with oversized sprites thrown into the mix as well.

**Comment by hitbutton** [comment]
> Would it be possible to add code that displays the top half of the sprite in the space occupied by the bottom half?

This is a little too ambiguous to interpret, and of the few obvious ways I can think to interpret it, all of them would look really weird.

Here's a visual reference for stuff we're talking about if it helps.
![image](https://cloud.githubusercontent.com/assets/16194079/12488800/42451a60-c065-11e5-911a-d422651d26f0.png)

I'd probably do zero height versions of my obstructing tiles, as it's the only option that gives the player a truly unobstructed view of surrounding tiles. Although the 33% alpha version is also tempting (easier!) and could be even be automatically applied to prevent unnecessary spritesheet bloat.

@sparr -do you think discussion of that feature should be split into a different issue, or is it cool to make this a general "prevent tile obstruction in isometric/zeldaperspective" issue?

**Comment by Malkeus** [comment]
Wow, thank you hitbutton for the awesome response. See-through tiles would be a pretty amazing thing to see in cataclysm. Could something like that be used to display z-levels below the player, instead of the blue air tile that is the current default for holes in the ground?

**Comment by hitbutton** [comment]
Seeing other z-levels as a third option - 
e.g. normal view / remove obstructing tiles / draw all z-levels
would be pretty cool (see the original XCOM game for an example of this)

However it would require some pretty complex changes to visibility caching, and I think that is really out of scope for this issue.

**Comment by Leland** [comment]
This is a massive undertaking and it hasn't seen discussion in over a year. This is certainly worthwhile but I'm closing due to lack of movement. Of course, if anyone's interested in further discussion on this, feel free to ping me to reopen or just make a new issue.
