### ISSUE TITLE
Sight dispersion above MIN_RECOIL is not respected

### ISSUE THREAD

**Issue by hitbutton** [CleverRaven/Cataclysm-DDA#14928]
Not a huge issue, since there aren't many weapons with a sight dispersion above 150. One example (possibly the only one?) is the M134D-H Minigun.

When entering the firing interface with it, the steadiness meter will wrap onto the next line in the window, because your recoil is less than the weapon's sight dispersion.

**Comment by kevingranade** [comment]
No longer reproduces.
