### ISSUE TITLE
Plastic bottles are disappearing after drinking from them.

### ISSUE THREAD

**Issue by YeAdventurer** [CleverRaven/Cataclysm-DDA#14924]
On build 4223. I'll select plastic bottle of clear water, Eat, my character drinks it down, and the plastic bottle is just gone. It's not on the ground, either.

Changing the 'Drop empty containers' option doesn't make a difference.

**Comment by Rivet-the-Zombie** [comment]
Just tested; can't replicate.

I'm not sure what would be causing it. Is anyone else experiencing this?

**Comment by YeAdventurer** [comment]
Are you in chat right now? I'll stream it.

**Comment by Zireael07** [comment]
Not seeing on 0.C-9461-g991ce56 (4221).

**Comment by YeAdventurer** [comment]
http://www.twitch.tv/yeadventurer/v/36620260

**Comment by YeAdventurer** [comment]
Here is the save and my config.
https://www.dropbox.com/s/asfcdywg5ungttl/Bug-Test.zip?dl=0

**Comment by Malkeus** [comment]
A plastic bottle holds 2 charges of water. After you drink the final charge it should leave behind an empty plastic bottle.

**Comment by YeAdventurer** [comment]
I am a fucking retard.
