### ISSUE TITLE
Yelling using 'C','a' causes sound level 2, whereas walking causes sound level 6.

### ISSUE THREAD

**Issue by aeoo** [CleverRaven/Cataclysm-DDA#14929]
This appears to be true in the build 0.C-9476.  I think that's strange.  I figure if I yell at the top of my lungs I should do better than the footsteps noise.  I don't know what the best solution is.  Just wanted to make a note of a discrepancy.

**Comment by Skidborg** [comment]
The purpose of shouting (as I would use it) is to attract enemies to a predictable place.  If that 2 volume is accurate and not just an interface issue, it does seem severely underpowered.

**Comment by Malkeus** [comment]
I have used shout recently. I don't know what number was on the sound meter but it attracted monsters from further away than a sound level of 2 (walking with the light step perk) attracts monsters.

**Comment by chaosvolt** [comment]
If that's true, this sounds like a display bug, rather than a volume bug.

**Comment by Oskar636** [comment]
In build 5864 this bug ( because it was a display bug ) can't be reproduced as shouting shows you a sound level of 50 being made.

**Comment by Oskar636** [comment]
Can somebody confirm this so it can be closed?

**Comment by aeoo** [comment]
Build 0.C-5883, 'C', 'a' now display sound level 30, and walking is still 6.  I'll close this issue and if there is a further complaint, then someone should open a new one.
