### ISSUE TITLE
"No names for effect type, ID:" for martial arts effects

### ISSUE THREAD

**Issue by ValidAQ** [CleverRaven/Cataclysm-DDA#14934]
Windows x86 Curses, 0.C-9502-g7088d57, build 4226.
Trying to open player info screen when using unarmed style that applies effects, such as Boxing, will result in this message.
It seems that effects like `mabuff:boxing_move_buff` and `mabuff:boxing_static` and such aren't handled correctly.
I suspect a connection to #14920.

**Comment by Malkeus** [comment]
I had some fun with this one, didn't notice it had been reported already, made my own issue #14941. I had to edit the save to get the effect to go away, and attacking with a rifle bayonet brought it right back.
Does the bayonet  use medieval swordsmanship without updating the Fight Style in status bar?
