### ISSUE TITLE
Mutations rebalance.

### ISSUE THREAD

**Issue by Dalenacio** [CleverRaven/Cataclysm-DDA#14932]
At the moment, there are two main paths to improve a character. Bionics and mutations. It follows that these two paths should be, if not equal in risk:reward, at least somewhat similar. Maybe one path should be a bit more risky, but carry better rewards, or just be easier to take. The problem is that, as things currently stand, one of these paths is strictly superior to the other.

Though one might argue that post-threshold mutations are superior to bionics (which is debatable), but  this tiny (or nonexistant) advantage does not justify the massive difficulty and risk present in mutations but absent from bionics. Long story short, mutations are just not VALID when compared to bionics.

-------------------------------------------

Bionics are easy to obtain. Incredibly easy. Just butcher a shocker or zombie scientist and poof, there you go. Then installing them is also easy. The success rates are pretty high for basic bionics, and can easily be increased through adderal or all manner of drugs. Even if you mess up and get a broken bionic, all you need to remove them is a first aid kit, hardly the most difficult thing to find, and they tend to not be that penalizing anyway. Also, you get better at them as time (and skills) goes on, so they become progressively easier.

All in all, it is very easy to go down the bionics route, as the risk is fairly low, even to an early character, availability is great, and the rewards are awesome (sonic resonator? Yes please!)

--------------------------------------

Now, onto mutations.

Mutations have, by default, a 2/3 chance of giving a random mutation, and a 1/3 chance of giving a bad one. The ONLY way, in the ENTIRE GAME, to affect this rate is buying the "Robust Genetics" trait, which you have to spend two character creation points to obtain, points which you can never earn back. And even then, they only change the "1/3 bad" to "1/3 good". Again, there is no other way to raise this odd in the entire game.

If it was just that, fine, maybe they'd be worth it (if you have robust genetics, that is). But the consequence for missing is much heavier. There are mutations that can really screw a character over, such as the radioactivity branch, or carnivore, or any other such mutation. Even the common "size" mutations can be awful, as they prevent you from wearing crucial armor on a body part, and will destroy whatever you had over that. Worse is that you can skip stones and get several from the same bad branch in one gulp or injection. You can go from normal survivor to "gradually losing health every x turns" with a single unlucky mutagen. And even if you don't, getting something like "weakening" means you're not touching another mutagen ever until it's gone.

Of course, there's a way to deal with bad mutations. Purifier! Except even that is very hit and miss. It removes random mutations, so it has a chance of leaving you with the bad ones and taking away the good ones, which means you might undo your entire progress in mutations while attempting to remove that ONE mutation that really screwed over your game. And all that's assuming you can find that much purifier. 

Mutagens are NOT easy to find. You probably won't ever encounter one before visiting a lab, and it requires a very high cooking (and specific books) to be able to make them yourself. Of course, you can always make "tainted tornados" with cooking 4 or 5, a specialized crafting base, and a lot of zombie meat. If you know you can do that. And it's totally random. Purifier (which you practically NEED to have on hand as mutations stand now) are even worse, as they don't have a moonshine stand-in option, and are even harder to make than regular mutagen. By the time you can afford to mutate, purify, and start again, you're already so powerful it's an afterthought.

So the end result is that trying to make a mutations character is like throwing 10 ping pong balls in the air in a single throw, and hope they land, at least mostly, in 10 plastic cups. Except you have to pay 10 000$ to pick a random amount of balls back up. And you have a chance to accidentally ram a ball down your throat and choke on it. which you're not guaranteed to take out when you pay your 10k bucks.

Bionics are picking up the balls and placing them in the cups.

---------------------------

Now I think I've made my point, mutations have a balance problem: They're like flipping a coin and hoping for the best. 10 times in a row. There are many minor fixes that could go a long way to helping make them more balanced, such special purifiers that can be targeted at certain mutations to have a better chance to remove that one, and only that one. Allowing one to improve the positive rates of mutagen and serum through crafting. I'm sure better people than me will come up with better ideas, but the truth is simple enough: Mutations need to be rebalanced to be valid again.

**Comment by illi-kun** [comment]
As Kevin recently [said] (https://github.com/CleverRaven/Cataclysm-DDA/issues/14914#issuecomment-173075033):
> If you want to start a discussion about a potential feature, please open a thread on the forums, the issue tracker is intended for more concrete ideas (which we're not perfect at, a lot of the very vague issues open now are likely to be removed to cut down on clutter)

So I think it's better to move the raised issue to forum. Let's keep issue tracker for more concrete requests.

**Comment by Dalenacio** [comment]
Well, this isn't a "potential feature", but rather a rebalance for an existing feature. I agree that a post on the forums will be beneficial for this, but I'd argue that its spot on the issue tracker is legitimate, at least as far as my interpretation of Kevin's quote goes. Of course, if he comes forth telling me to remove it, I will.

**Comment by Zireael07** [comment]
How would you rebalance the mutations then, @Dalenacio?

My ideas are as follows:
1) a low-level purifier stand-in similar to the tainted tornado
2) even more targeted purifiers (IIRC we already have category purifiers)
3) add Robust Genetics to some mutation trees

**Comment by Coolthulhu** [comment]
The problem isn't mutations being too bad, but bionics being too good.

I'm against upgrading the mutation scumming.
Targetted purifiers are pretty much the most wrong thing to add to mutations.

**Comment by Dalenacio** [comment]
I agree with Cool, part of the problem is that Bionics are just so good, there's no real reason NOT to use them.

The real problem here is *balance*. The two need to be about as valid as the other. Though I don't see that happening any day soon with the way mutations are set up.

**Comment by Coolthulhu** [comment]
The problem with bionics is that they are unlimited and have no downsides.
Even when you do get a bad bionic, you can just selectively remove it.

The balancing of mutations vs. bionics should be about:
* Removing the ability to make self into a monstrosity made mostly of metal, either by limiting amount of bionics that can be installed (with a strict limit, not just a skill based one) or by making bionics after some limit always come with significant negative effects
* Nerfing the impact of the most horrid of bad mutations (webbed hands mean no hazmat or power armor)
* Moving some moderately-good mutations out of threshold into regular pool and some really bad mutations into good thresholds
* Nerfing game mechanics that make mutations meaningless - health impact on hp healing makes regeneration pointless, for example

With the first point being the most important one.
No matter how slight the effect of bionics is, when you can stack them indefinitely, they're bound to get huge by the end.

**Comment by illi-kun** [comment]
@Coolthulhu Slot system for bionics was discussed previously and implementing it can be a good first step for solving the raised issue.

**Comment by illi-kun** [comment]
@Dalenacio I agree that we don't have (yet) some strict criteria what's for issue tracker and what's not but the main problem with your issue is there is no objective final condition which allows to conclude that your issue is finally solved.

**Comment by karols146** [comment]
As Dalenacio said:
>all you need to remove them is a first aid kit.
Maybe we should nerf that too, invent a new harder way to remove bionics

**Comment by mutt3x** [comment]
Regarding CBMs...
I particularly dislike that you can import infinite number of Power Storage units.
The way i would do it is simply add 10 slots for PS.
10 PS Units = 1000 power
10 PS MK II = 2500 power

2500 is quite a lot and all thouse who think its not, well... why would you need more really. It also seems more realistic. idk. (have 18k+ of cbm power, no wonder the end game is easy)

I am unsure about other body parts, i guess it you could implement the same slot feature.
2 slots arms, 2 slots legs.... 

The other thing that comes to my view is the implementation of CBM rejection.
''Your body is rejecting the xy CBM'' - would give you pain and demage your body part over time more and more. This could happen randomly after the successful installation for like 3 days.

Like Cool said there should be downsides:
I mean if you have the Joint Torsion Ratchet you should be running slower.
Some CBMs could inflict slight radiation like that clock cbm and the teleportaion/move thru walls cbms. Others might add encumberment.
And here is a good one: CBMs could have a firmware virus or something that corrupts the installed cbm and other cbm on that body part. why not, might be interesting.

Removing the same would require a first aid kit, skalpel, scissors(?), alchocol. To that you can also add further consequences (muaahaha).

I cant really speak for mutations, they seem slightly rare but hey, i personally believe that if you balance bionics then the mutation would gain a balance.

**Comment by karols146** [comment]
>The other thing that comes to my view is the implementation of CBM rejection.
>''Your body is rejecting the xy CBM'' - would give you pain and demage your body part over time more >and more. This could happen randomly after the successful installation for like 3 days.

About that. We can add some drugs with can stop this, or maybe decrease chance of rejection

**Comment by Zireael07** [comment]
+1 to rejecting CBM and more tools requirements for removal.

**Comment by mutt3x** [comment]
>About that. We can add some drugs with can decrease chance of rejection

Very good! Anti-Rejection drugs: after you installed the CBM you take... lets say 1pill per day. This may or may not help, it just lowers the % of the rejection to happen. You could go whithout them but the rejection would have a higher %. Taking more than one would have detrimental effect.

From that to the firmware virus idea...
You could detect it if you have a laptop/pda (since they dont have that much uses) and a high enough computer skill perhaps. The skill required depends on the CBM. Just imagine you have 9 PSU and you find that good ol' MK II. Install it - figure out it has a firmware virus and all your PSUs get corrupted >> prepare the vodka its removing time. Vicious.

Also Shockers might corrupt your CBMs. Seems reasonable.


>I agree with Cool, part of the problem is that Bionics are just so good, there's no real reason NOT to use them.

>The real problem here is balance. The two need to be about as valid as the other. Though I don't see that happening any day soon with the way mutations are set up.


The slot idea, perhaps the slots may go up or down... depending on mutations, but thats too much of code i guess. Some might want more eyes to have more eye slots. < This might give more reason to gain mutations. This is giving in the symbiosis between mutations and bionics. Mutant fly cyborg biker (driving a bus) < fear him.

Power Storage 10 slots
Head 2 slots
Eyes 2 slots
Hands 3 slots
Torso 3 or 4 slots
Legs 2 slots
Skin 2 or 3 slots >> heat, muscle, underskin cbms would go here.

As you can obviously calculate there is not enough slots to install all CBMs, you would have to chose them wisely. Thru pain and suffering.

Thats it from me and my ideas, really hope something from all that gets in. ;)

**Comment by kevingranade** [comment]
1. This is definitely something for the forums, it's almost impossible to
call this 'fixed'.
2. Your first premise that mutations and bionics should be equivalent in
some way has no basis.

**Comment by Malkeus** [comment]
@Dalenacio  "Apples are easier than math. We should make math as easy as apples or apples as hard as math." - What my brain hears while trying to follow your logic.

Yes, bionics are easy to find and easy to install, they need some attention. Yes, mutations are random and difficult to work with, I don't see anything wrong with that. The two are not sitting on a scale, they are two paths in a forest. One path is inherently more difficult than the other. That's OK. 

Please don't nerf mutation difficulty for the sake of some nebulous and arbitrary 'balance'. There's nothing wrong with the current system. It's fun and can be !FUN!.
Please do enhance bionics so they are less cheesy. A chance of infection, mutually exclusive bionics, pain on installation, recovery time...something.

**Comment by YeAdventurer** [comment]
>1. This is definitely something for the forums, it's almost impossible to call this 'fixed'.

Maybe it's just me but I've noticed a lack of contributor input on the forums, and a lot more people looking to start an argument. I mean, I think we have the latter a lot here, but with the forums it seems like it's a lot worse.

Could there perhaps be a compromise? I think discussion is good to have on here, why not just let it happen and then close it after a week or so or whenever it becomes inactive, whichever comes last?

**Comment by Coolthulhu** [comment]
> There's nothing wrong with the current system.

I disagree, it's too grindy and unavailable until endgame (except for Unstable Genetics mutants, which are some of the most fun characters to play for that reason).
IMO it should be moved further away from CBMs in role, made chaotic and uncontrollable, then buffed to make the gamble worthwhile.
As it stands, it is "guided personal evolution" rather than mutation.

**Comment by illi-kun** [comment]
Some random thoughts about bionics changes:

It's possible to use "points" system instead of slot one:

- Each body part has some amount of available space (= points), and mutations can affect number of points, for example ```Eyes``` have 2 points by default but "Spider" mutation branch increases it to 8 points (and Trilobite branch decreases it to 1, trade-offs and so on, you know).

- Each CBM takes some number of points (really good CBMs can be described as massive units, and it will explain why those CBMs take a lot of points and also it allows us to balance it properly).

- For making this system more flexible it's possible to allow the player choose location of installation of some CBMs.

- Some (the most powerful, probably) CBMs can require points at many body parts.

And here is possible UI for new bionics menu:
![ui](https://cloud.githubusercontent.com/assets/5421954/12500612/c62241f4-c0c5-11e5-99e6-042e7a5baa57.png)



/ It's 5 a.m. here so I'm sorry for possible typos.

**Comment by Rivet-the-Zombie** [comment]
I like everything about this, @illi-kun!

**Comment by illi-kun** [comment]
Thanks, I'm glad to hear that, Rivet!

**Comment by kevingranade** [comment]
> I think discussion is good to have on here, why not just let it happen and then close it after a week or so or whenever it becomes inactive, whichever comes last?

Because the issue tracker is for *tracking* issues that are actionable, everything about it is designed around that, and allowing "discussions" on it subverts that purpose by burying issues that can and need to be addressed.  There are already way too many issues open to keep track of the important ones, and if we atart allowing speculation and discussion on here, it'll only get worse.
