### ISSUE TITLE
Aiming reduces excess recoil very slowly

### ISSUE THREAD

**Issue by hitbutton** [CleverRaven/Cataclysm-DDA#14938]
The only way to reduce recoil below MIN_RECOIL is to specifically aim at something.
It would make sense if deliberately steadying your aim is the fastest way to reduce recoil (and it often is), but there are times that this is not the case.

Quickly firing a gun multiple times will boost your recoil extremely high. After shooting 10 times from the hip it will take you 10 times longer to subsequently aim at something than if you had shot from the hip once. I don't think that scaling should be quite so static

If you have high recoil (greater than ~600) you will almost certainly lose recoil faster by moving or pausing outside of the f menu (as moving and pausing reduce recoil by a flat amount then divide by 2) than you would by specifically aiming the gun at something.

This difference can be pretty huge. I tried firing a Saiga 12 until I hit bright red recoil, then saved the game and tried reducing recoil by aiming and pausing. Pausing, it took me 3 turns to go back to no recoil shown in the firing menu. Using aiming, it took me 9 turns to go back to no recoil shown in the firing menu (for clarification that's 9 full turns, not just 9 presses of the "steady aim" button).

I'd suggest either:
a) Adding a scaling component when an entire turn has been spent aiming, so that if recoil is greater than MIN_RECOIL, it is reduced by the difference / 2.
b) Remove multiplicative reduction from pausing and moving, and instead make recoil addition from gunfire scale to the current level of recoil. Something along the lines of (pseudocode):
<code>recoil += gunrecoil * MINRECOIL / max( MINRECOIL, recoil )</code>

**Comment by kevingranade** [comment]
There's a third change, which is determining a max recoil and capping
recoil at that number, this would go a long way toward tightening up the
aiming activity.  As it is you can end up with levels of recoil so high it
takes you several seconds to even bring your gun to bear on the target,
which is absurd.

**Comment by hitbutton** [comment]
Unless it was extremely low, it would still probably lead to some situations where pausing/moving was more effective than aiming, which is probably something we want to avoid. Also it occurs to me that it's possible to aim until you're nearly out of moves, exit the firing interface, then wait. That will would give you the benefits of aiming AND the recoil halfing effect from waiting.

**Comment by kevingranade** [comment]
Wasn't clear, that was an additional fix, not a sole fix.

**Comment by hitbutton** [comment]
In the base game, the worst recoil possible from a single shot is 1080. That's a sawn-off M2 Browning with diamond sword bayonet, firing .50 BMG Ball/AP - a pretty badass weapon.

so 1000 seems a fair value for MAX_RECOIL

**Comment by kevingranade** [comment]
How long does that take to burn down to something reasonable with iron
sights and no skills? That time would represent time to just swing the
barrel back into position.
Alternately maybe looking up firing rates from military and law enforcement
and working backwards from that should be better.

**Comment by hitbutton** [comment]
> How long does that take to burn down to something reasonable with iron
> sights and no skills

Through moving or pausing - 2 to 3 turns.
Unskilled Aiming - probably somewhere in the region of 6 to 8 turns.

Balancing the recoil duration by reducing max recoil would mean that you'd lose the ability for some weapons to have a greater recoil malus immediately after firing.

Quite possibly it would make sense for weapons to only boost recoil to a maximum determined by their recoil stat (possibly with some scaling factors, if still you want multiple shots to incur more recoil than a single shot).

**Comment by hitbutton** [comment]
Also I just think that recoil reduction should be standardized more across all methods. Moving / pausing are very similar already, pausing simply doubles that flat bonus received.

That could stop funny things such as str having no effect on recoil reduction when aiming, and dex having no effect on recoil reduction when not aiming.

**Comment by elricsfate** [comment]
@kevingranade 

Assuming a turn lasts 6 seconds, it should take one turn or less to bring your weapon "back on target". 

For example, even upon firing an entire 30 round clip at full auto from most infantry weapons (For example, an M4) it's not going to take anymore than 2-5 seconds to bring your rifle back in the general direction of your target.

**Comment by kevingranade** [comment]
Source? What we have is some mix of "feels right" and game balance oriented
numbers, injecting more "I think it should be about x" isn't going to help,
but hard numbers will.

**Comment by elricsfate** [comment]
@kevingranade 

I've fired that weapon on full auto, as well as numerous others (m249, m240, both in game) and it does not take a significant amount of time to resettle on your target at short range . 

Here is an example of someone firing an m4 carbine at full auto (in both small and large bursts) 

https://youtu.be/onZm5WF06BM?t=64

As you can tell, the deviation while firing isn't particularly significant (at least at short ranges) and the time to "resettle" the gun after the burst ends is very minimal.

**Comment by elricsfate** [comment]
Also worth bringing up, any consideration for an aiming system as seen in the original Fallout games? That seems like a perfect fit for Cata. 

Implementing such a system could provide extra incentive for firing weapon accurately (instead of using burst fire)

**Comment by kevingranade** [comment]
I don't like the concept of targeting limbs in dda, in fallout they're
modelling all kinds of things about the bodies of enemies and space around
enemies, so it's very interesting.
In dda it would just be some static numbers.

It would be possible to have "shoot to cripple" vs "shoot to kill" or
similar, but it seems like it would be very rare for that to be worthwhile.

**Comment by Coolthulhu** [comment]
> Implementing such a system could provide extra incentive for firing weapon accurately (instead of using burst fire)

We don't need any more incentive to aim accurately. Maybe except for laser weapons, where bursts are free.

**Comment by elricsfate** [comment]
@kevingranade 

Are you sure you're not thinking about Fallout's after the 1st and 2nd? The original Fallout's were isometric turn based RPGs so I don't believe they'd be doing anything much more complicated than what could be accomplished in Cata.

@Coolthulhu 

You could create incentive, for example, by making something like head damage more effective (And thus easier to take something down). This would add a lot of interest to the combat system when combined with aiming.

Do I take the time for a more aimed shot or go full tilt? That sort of thing.

**Comment by Coolthulhu** [comment]
> Do I take the time for a more aimed shot or go full tilt? That sort of thing. 

It wouldn't. We already have enough of an incentive to aim instead of going anywhere near full auto.
Adding yet another mechanic that benefits only high accuracy would only make full auto even less appealing than it is now.

Headshots are already more effective than any other hit. There is no need to add a special headshot mechanic, because it wouldn't really change anything.
Aiming for body parts would make sense if NPCs were routinely wearing heavy armor. But they aren't, so automatic part selection picks the part you'd aim for anyway.
