### ISSUE TITLE
Turn autosave on by default

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14936]
Since most of DDA development is about experimental releases, not everything is guaranteed to be stable. Crashes are usually rather rare, but once in a while a crash causing bug happens, causing a loss of progress.

It would also lower the memory usage:
All loaded submaps are kept in memory until a save is made. 21 times more data is stored in z-level mode, meaning that z-levels + long time between saves + low ram can actually result in crashes that aren't from bugs.

Plus, this would help with finding bugs: when the game crashes short time after a save, there is a chance that it will produce a crashing save or save from which it is easy to reproduce the crash.

On the downside, autosave prompt randomly popping up can be a bit annoying at times.

**Comment by aeoo** [comment]
>once in a while a crash causing bug happens

This is why I play with autosave on by default.  Game turns between saves = 200, minutes between saves = 5.  Those are my settings.

>21 times more data is stored in z-level mode

Is there any way to squeeze that?  z-levels are mostly used in high tower type buildings, right?  I am pretty ignorant of how z-levels are used right now, so please forgive me.  Maybe you want birds to actually fly in the sky.  Do z-levels use sparse arrays or are z-levels stored in actual complete cube arrays of data?

>Plus, this would help with finding bugs: when the game crashes short time after a save, there is a chance that it will produce a crashing save or save from which it is easy to reproduce the crash.

This is a great point, imo.

>On the downside, autosave prompt randomly popping up can be a bit annoying at times.

Exactly.  It's a little bit annoying, but for me personally it's completely doable.  I've learned to ignore the popup.  Maybe the popup can be swapped for a spinner type widget that shows up in combat log if you really want to make it subtle but still clearly notified to the player that "hey autosave is in progress."  Then people with fast computers will experience a barely perceptible occasional slow down with virtually no visual disturbance at the center of the screen, and people with slow computers will have their notification spinner in the combat log so they will know why the game is temporarily unresponsive.

Overall I support this idea even as it stands, without any further modifications.  I mean, I use the autosave feature all the time now anyway.

**Comment by chaosvolt** [comment]
Strange. I've rather rarely encountered crash-inducing bugs. Lag and other oddities in the past, yes. But somehow my potato of a PC has been crash-free with this game.

And it's annoying enough that I have to disable "safemode on by default" off every update. :V

**Comment by hitbutton** [comment]
> On the downside, autosave prompt randomly popping up can be a bit annoying at times.

Would the "prompt save when sleeping" option be a good replacement, or do you think that's too infrequent? I use that one to remind me to save regularly, and it's a lot less invasive than the autosave prompt - which is more likely to irritate the user and prompt them to turn it off.

**Comment by kevingranade** [comment]
The reason the default was changed was autosave was taking upwards of a
minute to complete, that is long since fixed, and I think turning it back
on by default is the right thing to do.

**Comment by Malkeus** [comment]
@chaosvolt, use the launcher it transfers configs...

On topic, I use prompt before sleeping, works out well since I either want to sleep and intend to stop playing for a moment anyway.

**Comment by harald921** [comment]
I have just bound autosave to my § key. I savescum to explore this game without spending literally months, but I'd vote for save at sleep. I mean, you shouldn't need to save several times a day, then something is just wrong, right?

**Comment by mugling** [comment]
Was this not updated to be the default?
