### ISSUE TITLE
Military searchlights seem to have been removed (possibly dummied-out outpost type)

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#14940]
The past several military outposts I've seen have all been the type that has turrets but neither a plutonium generator, nor any searchlights. I don't know if this was intentional, a mapgen error, or a coincidence.

**Comment by BevapDin** [comment]
There is a 1-in-3 chance for the generator and searchlights. It works fine for me, a generator spawns sometimes, but not always.

**Comment by Malkeus** [comment]
I have a Military Outpost with searchlights in my current save, i'd never seen such madness before and it cost me a survivor :)

**Comment by chaosvolt** [comment]
Hmm. I'll need to start going after more outposts it seems. :V
