### ISSUE TITLE
0.C-9502-g7088d57 - No names for effect type, ID:

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#14941]
I get the message in the title when using '@' to view character stats.
From the debug log.
18:44:59.869 : src/effect.cpp:442 No names for effect type, ID: 

Just this. Glancing at the code, it seems like it should be giving a number after 'ID:'?

effect.cpp line 439-442:
 if (eff_type->name.empty()) {
         debugmsg("No names for effect type, ID: %s", eff_type->id.c_str());
         return "";	
     }

Using debug mode, I have an effect with no ID which is counting down. It's currently at -3507.
"ID: , Duration -3507" 
It must have hit me right before I started cracking this safe, since cracking the next safe took me from -3507 to -5600, which seems logical bc my mechanics skill went up 2 points on the first one...

**Comment by Malkeus** [comment]
Ok, I saved and then checked my save file. The blank effect comes from medieval swordsmanship:

        "effects" : {
            "mabuff:swordsmanship_attack_buff" : {
                "12" : {
                    "eff_type" : "",
                    "duration" : -7825,
                    "bp" : 12,
                    "permanent" : false,
                    "intensity" : 1,
                    "start_turn" : 36298
                }
            }
        },
I'm wielding a rifle with a bayonet, and the status bar displays Normal for fighting style. Unequiping the rifle changes that to Medieval Swordsmanship. Changing my style to 'No style' changes it back to Normal, but the effect is still present and still counting down.
I'm going to cut the effect out of the save and see what happens...

**Comment by BevapDin** [comment]
Duplicate of #14934?

**Comment by Malkeus** [comment]
I removed it from the save. Attacking with the bayonet on the rifle reapplies the effect with a massive duration.
"ID: , Duration 16169118" 1st swing
"ID: , Duration 32338234" 2nd swing
"ID: , Duration 48507351" 3rd swing
etc.
After a short fight, the save now has this in it:
        "effects" : {
            "mabuff:swordsmanship_attack_buff" : {
                "12" : {
                    "eff_type" : "",
                    "duration" : 242536740,
                    "bp" : 12,
                    "permanent" : false,
                    "intensity" : 1,
                    "start_turn" : 44941
                }
            }
It must have overloaded whatever variable its sitting in to go negative the last time. I can't get it to go away without hacking the save :/

**Comment by Malkeus** [comment]
ah, didn't see that. closing this one.
