### ISSUE TITLE
Computer Hacker Description 

### ISSUE THREAD

**Issue by DeadLeaves** [CleverRaven/Cataclysm-DDA#14953]
The computer hacker profession's description is now going out of bounds and does not display the last part of it. Presumably due to the usage of double spacing after periods.

**Comment by illi-kun** [comment]
```Basketball player``` description also requires some editor's attention.

**Comment by Rivet-the-Zombie** [comment]
Or some hotkeys to allow scrolling the descriptive text.

**Comment by elricsfate** [comment]
@Rivet-the-Zombie 

That seems like it would allow more flexibility later. +1
