### ISSUE TITLE
Auxiliary weapon mods with BURST and BURST_ONLY flags still fire semi automatic

### ISSUE THREAD

**Issue by DeadLeaves** [CleverRaven/Cataclysm-DDA#14951]
Auxiliary weapon mods with BURST and BURST_ONLY flags still almost always fire semi automatic. I'm saying ``almost always`` because if you have trigger happy trait it can still happen. 

While I assume the trigger happy thing is a bug, I see no reason why an aux weapon cannot have burst. I realize that the aux weapon have no way of switching firing modes (Although this would be an awesome feature) but if a mod has BURST_ONLY it should still be able to fire burst IMO.

**Comment by mugling** [comment]
> Auxiliary weapon mods with BURST and BURST_ONLY flags still almost always fire semi automatic

Is this a regression or an omission?

> I see no reason why an aux weapon cannot have burst

Agreed

> I realize that the aux weapon have no way of switching firing modes (Although this would be an awesome feature)

If this is a regression I'll fix this now. If it's a missing feature this would be worth adding as part of an overhaul of the gunmod code.

**Comment by Coolthulhu** [comment]
> Is this a regression or an omission?

There is no core gunmod that isn't strictly single fire by design.
For this reason there is no auxiliary+burst mode, only regular, auxiliary and burst.

**Comment by mugling** [comment]
So `enhancement` rather than `bug`?

**Comment by DeadLeaves** [comment]
Well the bug is that the gun can in very specific cases still fire burst while in aux mode. But yes, allowing aux to fire burst would be an amazing enhancement.

**Comment by mugling** [comment]
> Well the bug is that the gun can in very specific cases still fire burst while in aux mode

True
