### ISSUE TITLE
0.C-9527-g2a74ce9 - Invalid effect type ID:

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#14958]
Getting this with these effects in my save file:

```
"effects" : {
    "flushot" : {
        "12" : {
            "eff_type" : "flushot",
            "duration" : 1,
            "bp" : 12,
            "permanent" : true,
            "intensity" : 1,
            "start_turn" : 29036
        }
    },
    "mabuff:eskrima_hit_buff" : {
        "12" : {
            "eff_type" : "",
            "duration" : -35846,
            "bp" : 12,
            "permanent" : false,
            "intensity" : 1,
            "start_turn" : 28003
        }
    },
    "mabuff:eskrima_bash" : {
        "12" : {
            "eff_type" : "",
            "duration" : -38229,
            "bp" : 12,
            "permanent" : false,
            "intensity" : 1,
            "start_turn" : 25620
        }
    }
},
```

**Comment by ValidAQ** [comment]
This was already fixed, wasn't it? By #14935.

**Comment by macrosblackd** [comment]
I updated to the latest, but it didn't fix the issue.

**Comment by ValidAQ** [comment]
Oh wait, I remember it still occurs with saves from previous version.
Editing your save to remove martial arts effects should fix it, I think.

**Comment by macrosblackd** [comment]
Breaking saves is bad, mmkay?

**Comment by ValidAQ** [comment]
So I guess the problem is glitchy effects that aren't removed properly?

**Comment by macrosblackd** [comment]
There needs to be a fallback for loading the old values.

**Comment by chaosvolt** [comment]
Derp. This is why I left the gilded aegis' old "cure assorted things" effect in when I updated Arcana mod to use artifact properties. :V

**Comment by mugling** [comment]
Lack of recent reports suggests nolonger a problem
