### ISSUE TITLE
Recipes passing flags from components to results

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14950]
We have quite a bit of recipes that are either duplicates with 1 or 2 values changed or that don't track some variables.
Most of those are food items: cannibal items and allergens.

I propose a system that would combine the duplicates and allow easily adding new recipes using stuff with "side effects" without losing said side effects:
- Effects like poison, human flesh and allergens would be moved to flags
- Certain flags, such as the ones above, would be added to results of crafting recipe that uses components with those flags
- List of flags that would be passed could be hardcoded at first, later jsonized and with the ability to insert them per-recipe. At first probably only food recipes would pass flags.
- In order to skip this flag passing, a recipe would specify a recipe flag like "DROP_COMPONENT_FLAGS" to avoid mutagens having to be poisonous. Alternatively, for some selected recipes, there could be lists of flags they don't pass.
- Components with "passable" flags wouldn't stack with ones that don't have them and would get extra notes for some of them. That is, unless they had HIDDEN_POISON or the like.
- Later on we could have flag pairs: input flag->output flag. So that, for example, cooking zombie meat could downgrade the poison but not remove it.

As a result:
- Cannibal food wouldn't require new entries for everything. Could still have them for fancy names
- Allergens and poison would get passed down the line automatically, allowing dehydrated poisoned/hallucinogenic shrooms (and then hallucinogenic pemmican), wheat vs. corn tortillas, broth becoming non-vegan when eggs are used etc.
- Possibility of cooking with zombie flesh for desperate (or mutated) survivors - at a steep morale penalty. Only if it makes sense, I guess - if they no longer taste like long pork, they may need own recipes. Or if we don't want easy grinding of cooking on zed flesh.

Sounds relatively simple to implement to me. Did I miss some important detail, like UI problems?
Or is it too "automatic" and we should control all of that by hand?

**Comment by Zireael07** [comment]
Sounds good to me.

**Comment by illi-kun** [comment]
You will meet some issues in edge cases probably but in general it sounds good/reasonable for me.

**Comment by kevingranade** [comment]
Where it's a property of the ingredient  (which it almost always is I
think) this makes perfect sense.
Vaguely relatedly, human flesh could have a hidden property that is
rendered un-hidden if the item is crafted by the player. This would
currently be pretty pointless since the only unknown cannibal dishes would
have been prepared by a former player in the same world.

More practically, an ingredient trait could trigger an alternate
name/description for the item containing it, allowing the alliterative
cannibal recipes to be folded into the regular versions.

**Comment by chaosvolt** [comment]
> This would currently be pretty pointless since the only unknown cannibal dishes would have been prepared by a former player in the same world.

As I've pointed out the last time discussion of this nature popped up, human pizzas in pizzerias (assuming they haven't been removed), and cooked creeps in police evidence lockers. The human pizzas are probably the only scenario where "I ate WHAT!?" is a distinct, hilarious possibility.

**Comment by nornagon** [comment]
This would also fix the fact that making "fruity" items out of non-fruit ingredients causes them to become fruit-containing. eg. making granola out of peanut butter candies. If the inputs aren't fruit, the outputs shouldn't suddenly become fruit!

Would the flags also have the potential to impact nutritional content?

**Comment by keyspace** [comment]
> Would the flags also have the potential to impact nutritional content?

I'd like to hope so.

Can the current data structures for crafted tools/clothes ("Made from" in the UI) be re-used for consumables?..

**Comment by kevingranade** [comment]
Obsoleted by https://github.com/CleverRaven/Cataclysm-DDA/pull/27252 and friends.
