### ISSUE TITLE
[Suggestion] Allow cutting up from ground/adjacent tiles

### ISSUE THREAD

**Issue by MisterFelixFox** [CleverRaven/Cataclysm-DDA#14967]
We've got stuff like eating, reading, etc. from adjacent tiles, but what about cutting stuff up with a held knife/axe?

I'd like to carve up stuff on the ground/chop logs into planks and all that. Specifcally, I want to use a knife to cut up a heavy stick on the ground, but since I only have one hand, I've spent the last few days foraging for a sixth rag for a bindle...

**Comment by Rivet-the-Zombie** [comment]
>I'd like to carve up stuff on the ground/chop logs into planks and all that.

Hold a wood saw and stand in the same square as the log. **A**pply it.

>Specifcally, I want to use a knife to cut up a heavy stick on the ground

Stand over the stick and **B**utcher it.

**Comment by MisterFelixFox** [comment]
Oh my goodness. I knew about butchering but completely forgot and it seems like applying an axe also works for the logs. Thank you very much
