### ISSUE TITLE
UPS-compatible recharging station doesn't charge UPS

### ISSUE THREAD

**Issue by Ataman** [CleverRaven/Cataclysm-DDA#14976]
For Build 4237:
The UPS-compatible recharging station doesn't charge UPSs or advanced UPSs.

The station however **does** charge items modded with the "UPS conversion mod" **but** those refuse to use that charge.
For example: Equip the UPS conversion mod to a jackhammer, charge it with the station and use it. It will refuse to work without a charged UPS in your inventory. (Despite being charged itself).

**Comment by pipehat** [comment]
I was able to charge and use a makeshift welder just fine. What other UPS-modded item did you try to use that failed to work?

I used to be possible to mod the UPS too so you could recharge it. Apparently that's not allowed now. Not sure if intentional or a mistake.

**Comment by Ataman** [comment]
I can confirm it works with crafting recipes (and construction) and also a some items.

The vibrator with UPS mod for example (don't picture it) does charge and can be used.
The electric jackhammer and the PBS Helmet does not.

**Comment by Core0verload** [comment]
Station not charging UPS or advanced UPS is intended. But UPS-modded equipment not working is clearly a bug.

**Comment by ValidAQ** [comment]
So, does that mean weapons that use UPS by default, like laser pistols, cannot be powered from the station at all? It's still necessary to use batteries or plutonium cells through UPS in your inventory?

**Comment by Malkeus** [comment]
UPS powered weapons only draw power on a shot by shot basis, they don't store it. However, I don't like the fact that you can't charge a UPS in the recharging station, this limits them to only being powered via batteries/cells, when there's a perfectly capable power supply already in place. 

I haven't obtained a recharging station since the change, I'll have to do some testing of my own...

**Comment by pipehat** [comment]
I agree w/ Malkeus. I think rechargeable UPS makes sense and is more fun than the new restriction.

**Comment by 3721assistant** [comment]
Just make these batteries you torn from vehicles rechargeable and everything will be fine I think?

**Comment by Core0verload** [comment]
I can make UPS rechargeable in this station, but then I must remove the ability to unload it to avoid power cells dupe.

**Comment by ValidAQ** [comment]
Why not make another UPS version that can only be recharged in the station?

**Comment by pipehat** [comment]
I'm happy with CoreOverload's plan. I didn't know UPS was unload-able anyway.

Alternately, possible hybrid with ValidAQ's comment - I think previously you had to recharge-mod the UPS to make it chargeable via the recharge station.

**Comment by Malkeus** [comment]
Maybe a recharge mod for the ups? The set of all persons who have a recharging station does not include all of the set of all persons who need to use a UPS. Those unfortunates will want to use the UPS as usual.

**Comment by Rivet-the-Zombie** [comment]
>I can make UPS rechargeable in this station, but then I must remove the ability to unload it to avoid power cells dupe. 

Add a check for the rechargeable battery mod when unloading an item; if it has the mod, block unloading.

**Comment by 3721assistant** [comment]
I think the best way is to make the storage batteries or car batteries rechargeable in the station. They ARE rechargeable anyway. The UPS/ADV UPS then becomes a kind of device that converts normal battery/plutonium cells to UPS-compattable devices.

**Comment by Coolthulhu** [comment]
If storage batteries are to be allowed to fuel UPS, UPS should consume them at an increased charge rate, not 1-to-1. Should be at most 100 UPS charges per unit of battery volume.

**Comment by NathanH-** [comment]
What was the purpose of this change? it seems like it just renamed the rechargeable battery mod, with the exception of requiring slightly more micromanagement(have to put 1 battery into a UPS to use anything assuming that isn't going to finally get fixed), and of course nerfing energy weapons, which is admittedly not the worst thing in the world.

"I didn't know UPS was unload-able anyway." - rechargeable battery modded UPS couldn't be unloaded, but regular battery powered ones could be. UPS were also forbidden from having the UPS conversion mod, but I think that was more about preventing silliness than getting free power.

**Comment by Malkeus** [comment]
UPS only chargeable via batteries is really hurting my survivors that haven't found a bionic UPS, and seems unnecessarily restrictive. The power is right there in my car batteries. I can add to the car batteries with this handful of AA's, same as the UPS, so obviously they are using the same type of power. I should be able to transfer power from the car's batteries to the UPS.

**Comment by Core0verload** [comment]
Uploading a fix right now. Sadly, it's coming in at full speed of my 10 kb/s internet and all your lang and tileset updates are ~30mb, so it's going to be a loooooong way up.
