### ISSUE TITLE
NPC Crash during combat

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#14984]
Save file attached - mods are all the default that come with game. Just keep going to the east (right) and let the NPC engage the throng of manhacks.

[Save File](https://www.dropbox.com/s/9wgahgwouydzj2r/npc-combat-crash.7z?dl=0)

**Comment by DanmakuDan** [comment]
Seems to be caused by 93b7b817169c779f4c17cb96a216fe4914a83c4b, the NPC will consider if its weapon could be thrown or fired (unlikely for a combat knife), but since it's not allowed to throw its knife, the game divides by zero doing a friendly fire check.
