### ISSUE TITLE
Guns spawning with magazines

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#14992]
Split from #14981

> If we're talking the ones found on soldier zeds and dead soldiers, then they should probably still have a magazine in them.

> A possibly empty one, but yeah.

The current implementation supports always/never spawning with a magazine (`default_mods`) which always contains none/the same amount of ammo (`count` property of magazine).

We probably need to support more than this?

**Comment by chaosvolt** [comment]
Also, it might be viable to give professions the ability to spawn with pre-loaded magazines. You'd still have to load the gun (as in the normal first step), but it's superior to having to load the mags.

**Comment by Rivet-the-Zombie** [comment]
Guns can spawn with no mag, an empty mag, or even a prefilled mag? I'm not sure what more it needs?

**Comment by chaosvolt** [comment]
Ah, it can? Nice. How is that handled?

**Comment by Rivet-the-Zombie** [comment]
I'm not entirely sure. I was going by what @mugling said.

**Comment by chaosvolt** [comment]
Right, but Mugling's also said not to use the default_mod property for magazines, as that just causes a given weapon to spawn with a magazine in it 100% of the time. No control over individual instances of a gun having magazines.

**Comment by mugling** [comment]
@Rivet-the-Zombie Sorry that wasn't well explained on my part:

* The `count` property sets the number of magazines a spawned magazine contains and is by default 0 except for ammo belts.

* The `default_mod` property on a gun functions as @chaosvolt describes but is something I'd like to avoid as it discourages proper balancing of the item rarity in `item_groups.json`

I would like to implement variable spawning of a magazines with guns, something like '10% chance to spawn with magazine in gunshop, 50% chance in home, 90% on zombie soldier) etc but it will be a few days until I can get to looking at this.

Hope that makes things somewhat clearer.

**Comment by chaosvolt** [comment]
Oh derp. I never thought to assign a count for M13 belts. We could leave DM1 belts empty or though, they're meant to be

I had a thought though. There's charges min/max settings for items in item groups. That might allow for magazines that show up in item groups to spawn with variable charges.

**Comment by mugling** [comment]
> That might allow for magazines that show up in item groups to spawn with variable charges.

Won't work at present but yes something along these lines is what I have in mind

**Comment by chaosvolt** [comment]
Ah, bugger. Doesn't work? Then again, even if works right, it wouldn't outright imply what kind of ammo would fill the magazine.

What about the way that jerrycans of gasoline and diesel are spawned by default?
