### ISSUE TITLE
Bulk Disassemble should capture list of items so as not to disassemble components further

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#15006]
When you do a bulk disassemble, the game will continue to disassemble components after it is finished disassembling the original stack of items. It should only disassemble the initial items.

**Comment by Malkeus** [comment]
Iirc there are two options for disassemble, 'Disassemble Everything' and
'Disassemble Everything Once', is the second option not working currently?

**Comment by macrosblackd** [comment]
Not that I can tell - it was disassembling components when I finally stopped it due to hunger.

**Comment by hitbutton** [comment]
Doing a brief test, "Disassemble Everything Once" appears to be working.

I dropped a couple of storage batteries on the ground, entered the butcher menu and chose "Disassemble Everything Once".
They were disassembled to medium storage batteries (and some other junk), then the bulk disassembly ended.
I could then enter the butcher menu again to bulk dissasemble the medium storage batteries.

What were the steps you took when it went wrong?

**Comment by macrosblackd** [comment]
I think I may have had components on the tile when I tried this, which is what confused me. Closing
