### ISSUE TITLE
Windows Tiles (may happen with console) not capturing lua errors - causing hard crash

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#15001]
I'm not positive that this is happening on the jenkins builds (Will retest when STS changes are merged) but for contributors, this could be a very big issue as there is no way to capture the actual lua error message.

**Comment by BevapDin** [comment]
Can you give a way to reproduce such a crash. Does it make a difference when the Lua code is loaded from a file or when it's entered via the Lua console?

**Comment by macrosblackd** [comment]
Perform arithmetic on a nil value will reproduce the issue:
```
local ermagerd
ermagerd = ermagerd + 1
```

**Comment by BevapDin** [comment]
Well, I can't help, it works "fine" here on Linux with Lua 5.3.1 (but the build bot seems to use 5.2.3 for the windows version). By "fine" I mean: it displays a proper error message in the form of a debug message, no crash at all.

**Comment by macrosblackd** [comment]
Yea, thats why I specified Windows :) I was only able to track it down because I setup a linux VM to track the issue down.

**Comment by macrosblackd** [comment]
So I looked into this a bit more - it looks like we're not compiling the Windows binaries with a compatible exception handler. Windows supports SEH (Structured Exception Handling) & sjlj (setjump, longjump). I'll keep doing more digging to find out exactly HOW we support those.

**Comment by kevingranade** [comment]
No LUA support going forward = no need to adress this.
