### ISSUE TITLE
Stop Prime strength/dexterity/perception/intelligence from nerfing high stat characters.

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#15019]
The current implementation sets any stat value of 15 and higher to 18. If you managed to achieve higher than 18 stats, via granades or statsthruskills mod, it's gone and set to 18.

} else if (mut == "STR_ALPHA") {
///\EFFECT_STR_MAX determines bonus from STR mutation
if (str_max <= 6) {
str_max = 8;
} else if (str_max <= 7) {
str_max = 11;
} else if (str_max <= 14) {
str_max = 15;
} else {
str_max = 18;
}

**Comment by Malkeus** [comment]
I propose altering that last else condition to:
else if (str_max <= 18) {
str_max = 18;
} else{ 
//do nothing
}

It would negate the mutation for high stat characters, but you wouldn't be nerfing your character either.

**Comment by kevingranade** [comment]
Need more detail, IIRC this is working as intended, in that if you already
have uber stats prime is not going to help, and may actually weaken you.

**Comment by Malkeus** [comment]
If that's the intended function, I guess it is working correctly.
