### ISSUE TITLE
Climbing in tiles mode shows sea of blue sky and no walls

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#15020]
When you climb walls with z levels on in tiles mode, all you see is blue sky.

This is ASCII:

![Image ](http://i.imgur.com/s5ZdKLm.png)

And this is tiles:

![Image ](http://i.imgur.com/pGwOGXR.png)

I was thinking it might be overlaying the blue sky over some tiles, but I made it transparent and was left with this:

![Image ](http://i.imgur.com/yhBV4cs.png)

Which does show the walls, but one off. And no fair loading your map or inventory. And the weather plays the worlds quickest game of connect four.

**Comment by stk2008** [comment]
Yeah I would love for this to work correctly in TILES :)
