### ISSUE TITLE
Unexpected shortage of ammo whilst firing flamethrower

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#15028]
Latest Dev build 64bit using tiles

I have found a bandit bulldozer and it has a flamethrower on it if I fire flamethrower I get this error message in red

Unexpected shortage of ammo whilst firing flamethrower

It still fires flames and kills monsters so not a big deal tbh

Thanks :)

**Comment by chaosvolt** [comment]
Huh, that's odd. D:

**Comment by Ataman** [comment]
Same problem with the dragon turret.

**Comment by mugling** [comment]
Probable issue somewhere with `item::ammo_consume()`. Will look into this

**Comment by BevapDin** [comment]
This may be caused by `vehicle::fire_turret` not giving the flamethrower enough charges. Changing
```C++
    long charges = std::max( 1, turret_data.gun.burst_size() );
```
to
```C++
    long charges = std::max( 1, turret_data.gun.burst_size() ) * turret_data.gun.ammo_required();
```
may fix it, but it leads to a crash in `player::fire_gun`:
```
#0  player::fire_gun (this=0xbfe08400, target=..., shots=400, gun=...) at src/ranged.cpp:398
#1  0x0875718c in vehicle::automatic_fire_turret (this=0xc79d7f0, p=22, guntype=..., ammotype=..., charges=@0xbfe09490: 400) at src/vehicle.cpp:6417
#2  0x0875782d in vehicle::fire_turret (this=0xc79d7f0, p=22, manual=false) at src/vehicle.cpp:6304
#3  0x08757ac5 in vehicle::gain_moves (this=0xc79d7f0) at src/vehicle.cpp:5130
#4  0x085b80ac in map::vehmove (this=0x904ef88) at src/map.cpp:358
#5  0x08195e9b in game::do_turn (this=0x903dca0) at src/game.cpp:1430
#6  0x086574cc in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:434
```
`item::ammo_data` returns null here. I suspect the code in vehicle.cpp doesn't set up the ammo data correctly. The temporary gun items in the code there don't get any magazines.
