### ISSUE TITLE
Onion fried is not a valid template

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#15026]
Get this error on latest EXP using 64bit windows with tiles.

Not a great deal I dont think I only get this error in red once on first load of my save game

**Comment by illi-kun** [comment]
#15024 will fix that.

**Comment by stk2008** [comment]
Wow that was fast :).

Thanks :)

**Comment by illi-kun** [comment]
It was done even before this issue ;-)
