### ISSUE TITLE
Redraw screen when window regains focus (Tiles mode)

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#15033]
The screen doesn't redraw if you change focus to another window and then go back to the game. The creates situations where the game can appear to be frozen, but is actually waiting for the user's input.

**Comment by Zireael07** [comment]
Just press 'm' to bring up the map, whoo! magic redraw :)

**Comment by macrosblackd** [comment]
If the game is currently waiting for input from the player, pressing m does nothing.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.C-6851, Windows XP SP3 x86.

**Comment by AMurkin** [comment]
At least a minimap in most cases are black, and occasionally - almost whole screen. I'm opening the map by 'm' at this cases. But minimap redraws only if player changes position.
Windows 10.
