### ISSUE TITLE
Fingerhack bionic is an active bionic, but is only used passively

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15032]
Using the fingerhack from bionic menu will only cause power level to drop by 25.

**Comment by chaosvolt** [comment]
Hmm. That is odd. So the actual use of fingerhack is all hardcoded into the function for using the card readers/electronic safes, right?

**Comment by nanovad** [comment]
data/json/bionics.json:497
If this field is removed it seems the game classifies it as a passive bionic.

**Comment by Cyrano7** [comment]
anybody fix this yet?

**Comment by chaosvolt** [comment]
If I have to do it myself... -w-

**Comment by Cyrano7** [comment]
Well I was thinking about ways to do it. It should be passive but still use power when used. But if you don't have enough power It should prevent you from using it.

**Comment by chaosvolt** [comment]
Ah, hmm. Does it actually cite any power drain when used to hack though? Could've sworn not. It could be given some, but two things:

One, that would be more complex by needing source tweaks, whereas making the fingerhack passive is a simple JSON tweak.
Two, electrohacks already don't need any power, so it would cause an inconsistency.

**Comment by Cyrano7** [comment]
Ya I suppose your right about reason two. On reason one your right too but that's terrible reason why not to add something.

**Comment by chaosvolt** [comment]
True. Technical it might be a valid reason to make the electrohack require batteries, assuming there isn't a lore reason for it not needing power. XP

That would further add complexity to such solutions though.

**Comment by Cyrano7** [comment]
I guess this could be closed now
