### ISSUE TITLE
Car batterys not displaying CHARGE AMOUNT

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#15046]
Latest Dev version 64bit tiles

A while ago not sure when if I removed a car battery I would have a number next to it showing the capacity of that battery now I dont see this which makes it hard some times to know which battery to refit into my car as I cant tell if I am fitting the flat one or charged one.

**Comment by Mecares** [comment]
Okay, it might be inconvenient but contrary to the average gas tank it is much harder to guess how much a battery is filled without special tools.

**Comment by stk2008** [comment]
Ah so its now a feature and intended.

If so do we have multi meters in game if not that could be cool :)

**Comment by Coolthulhu** [comment]
Don't make it into a feature - this isn't realistic when you think about it.
"Identical" batteries usually aren't identical - they have different brands, sizes, even location in the trunk (say, you put full ones to the right and empty ones to the left). Meaning you could easily remember a detail like that IRL.
And even if it wasn't the case, you could just use a knife to carve the number into the battery in the game, just that it would be tedious to do so.

This would only make sense for batteries with charges that were never known, but at the moment the only way for such a battery to exist is if you found a battery charged by a different player in the same world.

**Comment by Shadefang** [comment]
Seeing as we can already automatically tell the level of batteries that are installed in a vehicle it would make sense to display the charges, at least until we implement some tool (multimeter, etc.) for testing it, and possibly also make said tool required for viewing the charge level of a vehicle. Though the second half of that would essentially force the vehicle controls item to be split into separate parts (guages, steering column, etc.) so I'm not sure whether or not that's a road we want to go down.

**Comment by Malkeus** [comment]
This may be related: in the past weren't we able to use a loose battery to
re'f'ill a battery installed in a vehicle? I'll double check to confirm,
but I think that functionality has been lost as well.

**Comment by Shadefang** [comment]
I only ever remember being able to use plain battery items to do so, not other car/storage batteries, but I could be wrong. Either way, without some sort of device to transfer the charge, it doesn't really make sense to me to be able to do that.

**Comment by Malkeus** [comment]
Jumper cables ? I've done that dozens of times irl. It's not precisely the
same since irl the charges will equalize between the two batteries, but
then again, we currently use handfuls of batteries with no transfer
mechanism to charge vehicles. And said batteries evaporate upon use.
Transferring charge from one actual physical battery to another doesn't
seem that far fetched, esp. if it requires you to have cables on hand like
siphoning fuel requires a house.

**Comment by Shadefang** [comment]
Aye, that would work. But my personal inclination would be to remove the ability to refill car batteries with normal ones without some sort of charging device. Said charging device could theoretically take other car batteries as well, allowing it to be a kind of tier upgrade past jumper cables. Normally you have to find a new battery and install it in the car if it's dead. Jumper cables allow you to hook up another battery without installing it and equalize the charge, and the charger wold allow you to actually siphon off of other batteries to top yours off.

**Comment by Malkeus** [comment]
Jump starting a car straight from a battery would be pretty sweet. I carry around a folded extra-light frame with a charged battery and some jumper cables when I want to do something like that, but it's heavy and bulky. Though, I suppose a similar setup irl isn't exactly something you'd carry around in a backpack everyday.

**Comment by Shadefang** [comment]
Not everyday, but it's something that would definitely fit in a backpack. IRL, all you'd need is the battery and jumper cable. Plus a bit of circuitry if you're trying to completely drain one into the other. Anything more is just extraneous/quality of life (carrying handles, casing, etc.). And even using the smallest one I can find (a handle) it seems a bit excessive to have the handle on your battery rig be almost as big as the battery itself (using a car battery, that is)

**Comment by Malkeus** [comment]
True. One of these: http://www.thebatterycellonline.co.nz/product/1256276 + a battery and jumper cables shouldn't take up 12 times the volume of the battery alone, though the weight is probably about right: https://i.imgur.com/xyxvyN7.png https://i.imgur.com/C2fWAKf.png. 

On topic: I've nearly gotten a recharging station setup to begin testing things.

**Comment by Shadefang** [comment]
I see little reason it'd be any heavier or bigger than the items used for it. meaning for a jumper cable (vol 2, weight 0.2 lbs, this weight is probably quite low, but I don't have cables to weigh) and a car battery (vol 4, weight 39 lbs) shouldn't be more than 45 lbs and 7 volume (note that many car batteries have integrated handles nowadays)
for the setup you're talking about, jumper cable and small storage battery (vol 1, weight 0.7 lbs) it shouldn't be much more than a pound, and around volume 3-4.
Though at the moment none of these would be more effective than just carrying a small storage battery around with you, as it doesn't take any tools to install.

**Comment by kevingranade** [comment]
The only reason "reloading" using battery items was allowed in the past was
because a long time ago cars were quite rare so it was unreasonably
difficult to get a car started.
Now there are a lot of options for that, so removing that crutch would be
great.
Supporting both equalizing charge across batteries with just a jumper cable
and building a recharging circuit to completely drain one battery into
another would be nice.
Side note. Keep in mind you're going to lose quite a lot of charge using
either method.

**Comment by chaosvolt** [comment]
So what's the current (pun not intended) idea for whether to restore display charges for a car battery?

Adding useful things like equalizing charge and charge transfer is interesting, but beyond the scope of this issue, which involves the current (pun still not intended) inability to tell how much charge a battery has, making it unrealistically easy to get it mixed up with an empty if you have it with other loose car batteries.

Though I fear there may be some resistance (pun DEFINITELY intended) to the idea of adding that feature back in.

**Comment by Shadefang** [comment]
I feel it should be added back in (possibly as a percentage) for the sake of consistency. Seeing as all you need to do at the moment to measure the charge of a battery is bolt it to an arbitrary frame, it seems safer to assume that the batteries have integrated gauges. 

We may want to eventually add in voltmeters/multimeters to read charge, and require them for reading it on the vehicle construction screen. That's not even getting into how vehicle controls give you gas, diesel, hydrogen, plutonium and battery levels with copper wire being the most complex item used in making them, but both of those are issues for another time and place.

**Comment by Malkeus** [comment]
It's PFM. I mostly agree with you, @Shadefang, but I'd like to see the actual number of charges. It will match the display on fuel tanks and just be more useful. 

Perhaps someday we could get an actual gauge part coupled with a gauge display that would need to be present to view levels in the vehicle construction screen. It would add a degree of realism to have fuel/battery charges present but unknown after your vehicle recieves battle damage.

**Comment by mugling** [comment]
Both OP issue and disallowing refilling of vehicle batteries with stacks of `battery` are now resolved
