### ISSUE TITLE
[CR] Neoprene crafting

### ISSUE THREAD

**Issue by DeadLeaves** [CleverRaven/Cataclysm-DDA#15040]
So when I was playing earlier today I realized after my spring suit broke that they're not craftable. So I thought I'd fix that. 

Seeing as neoprene is quite an advanced material I was thinking that crafting the items out of plastic directly feels wrong. So what I'm planning on is some recipe to turn plastic + chemicals into neoprene sheets,  that can later be sewn into clothes.

So for what I need help with deciding is:
* Crafting process of neoprene - I'm thinking plastic + some chemical. And tools needed would be something like chemical lab and heat source.

* The difficulty for crafting the items. Seeing as neoprene is kind of late early game clothing it'd require something like 4-5 tailoring to make. It's also kind of a hard material to work with, so that works in well with realism.

* Lastly what items. The items I have in mind are the following:

1. Springsuit
2. Wetsuit
3. Neoprene armsleeves.

But im pretty sure i've seen other items mention being made of neoprene.aswell. 

Also, all in all. What do you think of this whole idea? Could it be mainline. or should it be a mod?

**Comment by Rivet-the-Zombie** [comment]
The simplest (though hardly safe) method for a survivor to use would be combining chlorine and 1,3-butadiene to produce 2-chlorobuta-1,3-diene, then polymerizing it with potassium persulfate.

In DDA terms this would be something like:

Produce 1,3-butadiene using the Lebedev process - combining ethanol and scrap metal in your chemistry set.
Produce chlorine by reacting hydrochloric acid and sodium hypochlorite - combining strong acid and bleach in your chemistry set.
Produce chloroprene by combining the two in your chemistry set.
Polymerize the chloroprene by reacting it with potassium persulfate - oxidizer powder in DDA terms - and crosslink the polymerized strands using metal oxide - more scrap metal.

**Comment by DeadLeaves** [comment]
How much power is lots. Seeing as the chemistry set can hold 200. Im thinking 100 might be fair. Though that sounds a lot compared to other things in the game.

**Comment by DeadLeaves** [comment]
Well it all depends on how "big" one sheet of neoprene is. 4 sheets should be fine for a springsuit, maybe 6 or 7 for the wetsuit. I feel that ratio is fair, since it allows smaller things to  be made out of 1 maybe 2  sheets.

**Comment by Rivet-the-Zombie** [comment]
If it's not broken into intermediate steps, then something like 100 would probably do.

**Comment by Zireael07** [comment]
*bounce bounce*

That's what I do when I see more use for my baby (the chemistry set) :dancer:

**Comment by Coolthulhu** [comment]
> Seeing as the chemistry set can hold 200.

It's fine for some recipes to go above that and be either vehicle only or require more than one copy of a tool.
In this case the recipe could require just CHEM 2 rather than chem set charges and just use the charges from generic hotplates (chemset is a hotplate).

**Comment by DeadLeaves** [comment]
> It's fine for some recipes to go above that and be either vehicle only or require more than one copy of a tool.

Wait, you can have a recipe require more than one of a tool? That's neat. How does one specify that in the json?

Also, it might take a few days before you see any visual progress on this. I'm not very quick at working since I'm basically on a sick leave for a year due to medical complications.

**Comment by DeadLeaves** [comment]
@Rivet-the-Zombie I'm working on implementing the recipe for making the neoprene sheets. Im wondering if you have any input on the following item requirements. I went with what feels balanced, but since I don't really know the process that well. It'd would be nice with some input on the realism side of it aswell.

```
      [ "ehtanol", 2 ],
      [ "scrap_copper", 1 ],
      [ "strong_acid", 1 ],
      [ "bleach", 2 ],
      [ "oxy_powder", 2 ],
      [ "scrap", 1 ]
```

**Comment by Rivet-the-Zombie** [comment]
That looks good, and if later we decide that it needs to be adjusted, we can do that too.

**Comment by Coolthulhu** [comment]
> Wait, you can have a recipe require more than one of a tool?

No, but you can set the required charges above that of a single item, in which case you will need more than one to meet the requirements.

**Comment by ValidAQ** [comment]
Would that kind of requirement mean that the crafting recipe in question would be impossible to complete with only one tool, no matter how many charges you could possibly provide for it?

Say, there is a crafting recipe with 400 hotplate charges required. 
Does that mean that one fully charged hotplate and 1000 batteries in reserve are insufficient for it, but two fully charged hotplates are?

**Comment by DeadLeaves** [comment]
I'm thinking I should implement neoprene as a material, seeing as that's necessary for cutting up items made with it. what kinds of stats should it have? (Resists, density etc) I have never before looked in that file so I have no idea what is appropriate.

**Comment by Rivet-the-Zombie** [comment]
>Also due to how cutting items up works, I have had to increase the materials needed to craft about threefold. So I'm thinking crafting neoprene yields 2 or 3 per craft. I know it's doable, but not I don't know how.

Alternatively, reduce the wetsuits' volume by a bit - they're ridiculously high for what they are - and give neoprene a batch crafting bonus.

**Comment by DeadLeaves** [comment]
That's doable and makes some sense, wetsuits are very compactable. However this requires volume reduction on the survivor wetsuit parts as they almost return as much neoprene as a normal wetsuit. but they're also ridiculously big so it's probably fine.

**Comment by karols146** [comment]
I think that tailor kit would be good, but maybe we can add some new needle to craft. 
Soldering iron + wetsuit just don't sound good.

**Comment by DeadLeaves** [comment]
Yeah sounds good, tailors kit to start with, and ill work on adding a proprietary needle for working with neoprene.

**Comment by Coolthulhu** [comment]
Closing because it is in already.
