### ISSUE TITLE
More Locations mapgen error

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#15049]
https://i.imgur.com/ex1PkH8.png

omtype 3storyA_roof_west, "house roof" (id_mapgen 3storyA_roof) seems to be missing?
This happens fairly regularly as I enter a new city.

In 0.C-9701-g3e9dc60

**Comment by DeadLeaves** [comment]
I get the same in build 4231

**Comment by Leland** [comment]
We haven't seen any more tickets regarding this, and I can't find anything about it on the forums. I also have been unable to reproduce this. Closing for now – if you still encounter it, let me know here and I'll reopen the issue.
