### ISSUE TITLE
Inferior jians and scimitars exist in mainline, real version is mod content

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#15053]
Slight inconsistency. I'd assumed initially that when inferior replica weapons were added, the smart thing would be to add the inferior version of Medieval Mod content to Medieval Mod itself.

Either someone forgot what is and isn't mod content, or someone was so adamant about mainlining Medieval Stuff content that they jumped the gun on adding the cheap-ass variant. :V

EDIT: Also, same derping occurred with arming swords.

**Comment by hitbutton** [comment]
I don't think it's inconsistent. Being able to obtain a cheap steel weapon doesn't necessarily mean that you can also find a better quality one.

**Comment by chaosvolt** [comment]
Important point: this means that cheap jians, scimitars, and arming swordscan be acquired in normal Cataclysm, but real versions flat-out don't exist. This will only serve to cause player confusion and disappointment.

Also note that the aluminum fakes are also mod-only. So it's not just "the real deal doesn't exist" it's also "the even SHITTIER versions don't exist" -_-

**Comment by hitbutton** [comment]
But It isn't implied anywhere that a better version of the weapon does exist.

**Comment by chaosvolt** [comment]
Which still serves even less gameplay purpose than the fake weapons already do. -_-

**Comment by hitbutton** [comment]
Are you implying that the only purpose of the inferior weapons is as "breadcrumb" clues to the existence of the better versions? I don't think that's the intention.

They're still effective melee weapons. I'd quite happily hit some zombies with an inferior arming sword (until it eventually breaks).

**Comment by chaosvolt** [comment]
No. The main purpose of the inferior weapons is as a balancing factor, by making the real deal rarer, and as a side effect encourages players to look into weaponsmithing to fabricate their own.

Obviously it can serve neither of those functions if the real weapon doesn't exist. >_>

**Comment by Shoes01** [comment]
If a fake weapon exists, it implies a real one exists somewhere. If the fake weapon makes for a good weapon, then it's not a fake weapon. Why not call the fake weapon "real" and the real weapon "authentic" or "artifact" weapon or something.

**Comment by chaosvolt** [comment]
The latter point there is beyond the scope of this issue, but the former point does fall in line with what I'm trying to point out.

**Comment by Rivet-the-Zombie** [comment]
What's the point of this discussion? There's no reason for the items in question to be specific to a mod.

**Comment by chaosvolt** [comment]
Mostly pointing out things that might be next on the list of mainlining if desired, given they're currently causing inconsistencies. ;w;

**Comment by hitbutton** [comment]
I'm not particularly opposed to adding new high quality weapons, but I disagree that it's inconsistent if they aren't present.

It's also contrary to the intention of the PR that introduced the cheap steel weapons - e.g. it makes high quality weapons a bit more common, when the purpose was to increase their rarity.

**Comment by kevingranade** [comment]
It's perfectly reasonable for cheap versions of these weapons to be in the
game, but the real versions to be so rare that they practically or actually
never appear. There is no inconsistency.

**Comment by chaosvolt** [comment]
-_-

It does not serve the same gameplay purpose as the other existing inferior weapons. Additionally, there is a difference between "so rare that they practically never appear" and "literally do not exist on this world, even in debug"

**Comment by Coolthulhu** [comment]
> It does not serve the same gameplay purpose as the other existing inferior weapons.

It does. Except with less annoyance, because it's obvious that it's trash without having to read the stat block.

**Comment by chaosvolt** [comment]
So basically pollute the game with junk items, without the same redeeming features that the other fake/inferior weapons present.

I don't personally mind whether those items are mainlined or not. I just think it should be applied consistently.

**Comment by Coolthulhu** [comment]
> So basically pollute the game with junk items

Fake items yes, inferior ones can be useful very early on.
> without the same redeeming features that the other fake/inferior weapons present.

Pretending to be a better item until you read the statblock is not a redeeming feature. Quite the opposite.

**Comment by chaosvolt** [comment]
Which makes me question why we added fake weapons in the first place, if that's your evaluation of them.

Thing is, I don't mind the fake and inferior weapons. As I said, they aren't COMPLETELY useless. They're a balancing factor, by adjusting the rarity of the real deal.

This issue is not about the idea of fake or inferior weapons as a whole, or about how useless they are. It is about the fake jian, scimitar, and arming sword being used in a manner inconsistent with the other weapons.

And as @Rivet-the-Zombie pointed out, it might be acceptable to mainline them anyway. But having only a specific type of those weapons exist in, with neither the bottom-of-the-barrel NOR the real deal obtainable? It serves no gameplay purpose, and does not contribute to realism despite @kevingranade's claims to the contrary (especially with the fake versions being unobtainable as well).

**Comment by kevingranade** [comment]
> Additionally, there is a difference between...

Yes there is, which is why I said
> they *practically* or *actually* never appear.

You can't evaluate the realism of an item based on the absence of other items.  If the 'fake' items exist in the real world (they do, in massive numbers), it is realistic to depict them in the game, full stop.
Whether 'real' weapons exist in sufficient numbers to bother with spawning them is a separate issue.

**Comment by chaosvolt** [comment]
Right. Still, it remains a case of inconsistent behavior, and retains the issue of not serving the purpose that inferior medieval weapons are intended to serve.

Furthermore, outright closing this issue implies that you are vetoing the idea of mainlining the real and fake versions of the jian, scimitar, and arming sword. Because either mainlining the other variants or moving the budget versions to the mod would actually resolve this issue, and forcibly closing it implies you support doing neither.

**Comment by illi-kun** [comment]
> Furthermore, outright closing this issue implies that you are vetoing the idea of mainlining the real and fake versions of the jian, scimitar, and arming sword. Because either mainlining the other variants or moving the budget versions to the mod would actually resolve this issue, and forcibly closing it implies you support doing neither.

@Darkyhard is already working on mainlining Medieval stuff. #14602 contains real versions of items you named and the only reason it wasn't merged (AFAIK) is size of PR, not the content of PR. Author of the mentioned PR realized the issue with his initial PR and now successfully lands mainlining of ancient weaponry item by item (see #14997 and #14955 as example). Merging his PRs to project codebase contradicts with your conclusion about 'veto' on real weapon in the core game.
