### ISSUE TITLE
Need new milestone

### ISSUE THREAD

**Issue by Chase-san** [CleverRaven/Cataclysm-DDA#15063]
It's been awhile since the last release, and thus we need a new milestone for blocking of release 0.D. This way it can be cleaned up, eventually get a feature lock and get released.

**Comment by chaosvolt** [comment]
Last I checked, the big things that are being worked on before there can be any talk about a new stable version are...3D levels being fleshed about, and NPCs being more sane. Also there's now the big magazine feature that will likely need to be completed.

**Comment by kevingranade** [comment]
Sorry, I don't take orders about project management :P

**Comment by Chase-san** [comment]
Well whatever.

**Comment by chaosvolt** [comment]
Huehuehue. A consistent outline of what the highest priority features would be useful, but still. No need to demand a new stable version just yet. :V

**Comment by Cyrano7** [comment]
> Sorry, I don't take orders about project management :P

Its good being king sometimes hehehe.

**Comment by Chase-san** [comment]
Was it fun waiting so long? ;)
