### ISSUE TITLE
Make horde-spawned zeds inherit horde's target

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15064]
Making loud noises will get hordes near you and into bubble, but once they're spawned in the bubble, they will stop and go back to stumbling until they hear or see something.

Giving them a point in the submap they targeted as horde upon their spawn would make the horde/reality split less visible.

**Comment by Mecares** [comment]
I agree Zombies should spawn as if they have already heard the noise that made them spawn.
