### ISSUE TITLE
Reload from ground fails when insufficient inventory space

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#15079]
`game::reload` is bugged when the inventory is too full to temporarily contain the item.

To reproduce:

- Spawn STANAG magazine and drop it
- Ensure you have no free inventory space and empty hands
- Spawn AR-15 and wield it
- Try to reload using STANAG magazine from ground

Sequence of events is:

- Item is picked up by `item_location::obtain` and placed in inventory
- `player::assign_activity` is called to start reloading using the item
- `Character::process_turn` calls `drop_inventory_overflow`
-  Activity fails with debugmsg *"Tried to get an item from a character who doesn't have it"*

Possible solutions:

* Require sufficient space when calling `item_location::obtain` (trivial)
* Mark item as `job item` and exclude it from inventory volume calculations until activity completes
* Rework activity handlers to use `item_location` (difficult)
* **... any others?**

**Comment by macrosblackd** [comment]
Just a note - I ran into this last night as well when doing some crafting and trying to reload with 8000 batteries.

As for solutions, I kind of like your second suggestion of marking it as job_item.

**Comment by mugling** [comment]
"Urist McBrains cancels reload action - job item misplaced"

**Comment by mugling** [comment]
Silliness aside marking the job item is probably the cleanest solution

**Comment by kevingranade** [comment]
This also happens if the magazine is in an ammo pouch.
Ideally the magazine would go into an "off-hand" storage location for the
duration of the action. For the time being suspending volume limits should
be ok, but I'd also be fine with requiring free space for the item and
failing the action instead of triggering inventory overflow or similar.

**Comment by mugling** [comment]
Yes, indeed knowing the fault I can replicate it in a number of further ways.

I'm going to go with suspending the check for storage limits whilst any player activity is pending.

**Comment by kevingranade** [comment]
Any player action? Is that really necessary?
I thought reloading was the only action that stashed an item in the
inventory.

**Comment by mugling** [comment]
No, the conditional in #15084 could be changed to check for `ACT_RELOAD` however I chose the more generic approach for consistency and future expansion. For example `ACT_READ` could benefit from this?

Eventually we should consider proper off-hand mechanics but that's still in the pipeline and a long way from completion.

If you'd prefer the more specific `ACT_RELOAD` conditional then I can change this and add a more explanatory comment.

**Comment by kevingranade** [comment]
I'd much prefer a targeted workaround, otherwise you start papering over issues.

**Comment by mugling** [comment]
Ok, can I go with the `ACT_RELOAD` conditional and a `@todo` comment explaining this. Eventually I'd like to implement off-hand mechanics as started in #14870 but this is some time away.

**Comment by mugling** [comment]
I'm stuck for a better solution here as player activities only work for items within the inventory. I'm working on @BevapDin's suggestion to grab less ammo but there are still situations where the inventory is going to temporarily overspill. In the long term player activities could work using `item_location` but that's a big change.

I preferred general suspension of volume checks during activities as it generalised well, eg. for `ACT_READ you pick up the book, zombie bites you, you stop reading, no space to keep the book so you drop it.

Granted it's a blunt solution so if we don't want to go with that the next step down is a more targeted workaround (just `ACT_RELOAD`) until a more permanent solution can be found (probably an off-hand location with a matching `item_location` class).

I can't push revisions to the original branch which is somewhere in the ether so I'm going to rebase against master and push a new one.
