### ISSUE TITLE
NPCs confused by magazines

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15088]
More about future design than current NPCs.

Reload functions should be written in such a way that it is easy to do all of the:
* Finding compatible gun/mag pairs
* Finding the remaining number of "shots" in a gun, preferably as a single function
* Reloading without too much concern about ammo type (quantity > quality)

**Comment by mugling** [comment]
> Finding compatible gun/mag pairs

`item::magazine_compatible()`

> Finding the remaining number of "shots" in a gun, preferably as a single function

`item::ammo_remaining()`

> Reloading without too much concern about ammo type (quantity > quality)

This logic could be put within `item::pick_reload_ammo()` rather than just selecting the first compatible?

**Comment by chaosvolt** [comment]
Oh this I was afraid of. ;w;

**Comment by mugling** [comment]
This would seem to go hand in hand with simplifying reloading so that when you have only one empty magazine loaded in the gun it automatically ejects the magazine, reloads the magazine and then reloads the gun. NPC's can then make use of such logic.

The sticking point remains that the legacy code we inherited was not structured with this in mind with the functionality split somewhat awkwardly.

**Comment by chaosvolt** [comment]
Right. We need some function so that reload can automatically unload. This would also simplify the use of magazine-fed guns for players, since that means less keypresses.

**Comment by Coolthulhu** [comment]
As long as it can be relatively easily converted, it should go smoothly.
It would be really good if the "ammo for weapon" function was a separate one rather than an inlined one. NPC functions would benefit from being able to count ammo, especially once reloads become slow and restricted mostly to magazines.

**Comment by chaosvolt** [comment]
Hmm, if possible.

Though if all else fails, there's still guns that don't use detachable magazines, but still. ;w;

**Comment by mugling** [comment]
> Though if all else fails, there's still guns that don't use detachable magazines, but still

This is a good temporary fix. We could set all NPC's to use weapons with integral magazines

**Comment by chaosvolt** [comment]
That would sharply limit their options though.

**Comment by mugling** [comment]
@Coolthulhu are you happy to call this complete as of your recent PR?

**Comment by Coolthulhu** [comment]
Yeah, they're acceptable for now.
