### ISSUE TITLE
"edit-mode" : "modify", removes special attack - 0.C-10014-gf519400

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#15095]
While I am glad that they've decided to quit smoking, I feel that this was not an intentional change. I've never seen one that isn't enshrouded in a cloud, they are pretty foul looking. Looking at monster.json shows they still have the smokecloud special attack in additon to the newly reformatted bite attack. Photo evidence, only one is a natural spawn, I debugged in the rest to confirm weirdness:

[Non-Smoking Smokers](https://i.imgur.com/OInM2AI.png)

Could someone confirm this issue? I don't have any mods going that change mon_zombie_smoker but some weird interaction is a possibility.

**edit: Not an issue in the base game, but still an issue with the "edit-mode" : "modify", function.
Details below in my 2nd comment.**

**Comment by Night-Pryanik** [comment]
Spawned smokers in clean 0.C-4304, and they immediately generated smoke clouds.

**Comment by Rivet-the-Zombie** [comment]
I'm unable to reproduce this.

**Comment by Malkeus** [comment]
It seems to be a strange interaction with 
"edit-mode" : "modify",
Pisskops Rebalance mod has this entry which adds an upgrade, but it makes them stop smoking:
{
    "type" : "MONSTER",
    "id" : "mon_zombie_smoker",
    "edit-mode" : "modify",
 	    "upgrades":{
      "into": "mon_zombie_gasbag_pk",
      "half_life": 28
      }
}

Duplicating  the special attacks section from core monsters.json makes them start smoking again:
{
    "type" : "MONSTER",
    "id" : "mon_zombie_smoker",
    "edit-mode" : "modify",
        "special_attacks":[
        ["SMOKECLOUD", 1],
        {
            "type" : "bite",
            "cooldown" : 5
        }
    ],
 	    "upgrades":{
      "into": "mon_zombie_gasbag_pk",
      "half_life": 28
      }
}

Correct me if I'm wrong, but that's not the way edit mode - modify is supposed to work, right?

**Comment by pisskop** [comment]
They were not smoking, but would when I removed the mod or added the special attack back in.
