### ISSUE TITLE
#14559 breaks save game compatibility

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#15102]
By virtue of removing an item id from the JSON without any logic to handle the conversion, older save games are going to be broken. This was just brought to my attention due to a forum post regarding this PR.
#14559

**Comment by Malkeus** [comment]
#14559 also breaks UPS as details in another forum post http://smf.cataclysmdda.com/index.php?topic=12053.0
Calling all @Core0verload 's, please fix.

**Comment by BevapDin** [comment]
> By virtue of removing an item id from the JSON without any logic to handle the conversion, older save games are going to be broken

What id had been removed? The linked PR adds a few items and moves some definitions around, but I can't see entries that have been removed.

**Comment by macrosblackd** [comment]
Guess you're right - I coulda swore I saw a missing ID - that's what I get for looking at anything with 4 hours of sleep.

**Comment by Core0verload** [comment]
I did NOT removed any IDs. As for "Broken UPS charging" - there is #14976 that's I'm now trying to fix. Sadly, it's easier to talk about "balance" than to test my changes with various tools and point out the issues.

**Comment by illi-kun** [comment]
> Sadly, it's easier to talk about "balance" than to test my changes with various tools and point out the issues.

That's mostly your responsibility to test changes you're proposing to merge, no need to blame anyone else about that.

**Comment by macrosblackd** [comment]
Since I was mistaken about the save breakage, closing - I need more sleep.

**Comment by Core0verload** [comment]
>That's mostly your responsibility to test changes you're proposing to merge, no need to blame anyone else about that.

I'm just still a bit mad about all that pointless balance talk.
