### ISSUE TITLE
When butchering broken cyborgs in labs you get message "You harvest some meat."

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#15115]
cataclysmdda-0.C-4271
So I get the message about "You discover a (any bionic)" and message "You harvest some meat."
But only the bionic is on the ground after. Are you suppose to get meat from broken cyborgs?

**Comment by Coolthulhu** [comment]
I changed the message to that because in most cases it was just that and "you butcher a corpse" wasn't enough.
I guess we'll need to special case it or change the messages to print the exact name of what was dropped.

**Comment by Rivet-the-Zombie** [comment]
If they're 'cyborgs' as opposed to 'robots' then they probably should produce a quantity of human flesh and bone when butchered.

**Comment by codemime** [comment]
Yeah, according to the description you can expect at least a scalp of your defeated enemy.
