### ISSUE TITLE
Cannot modify UPS Weapons without unloading them first. Cannot unload UPS weapons. 0.C-9984-ga87baf6

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#15128]
Steps to reproduce: 
Spawn in an A7 laser rifle and your choice of UPS (item or cbm), and a shoulder strap.
Power the UPS
Fire the rifle once
'A'ctivate the shoulder strap and select the A7 laser rifle as the target.
You will get the message: "Unload your A7 laser rifle before trying to modify it."
https://i.imgur.com/pfgmQ7y.png
Alternatively, spawn in the laser rifle and the shoulder strap, attach the shoulder strap in the normal fashion and THEN fire the weapon. Try 'A'ctivating the laser rifle to remove the mod and you will recieve the same message.

Before firing, there is no ammuntion present in the line below the ammo specification: https://i.imgur.com/ZPrtkiF.png

After firing, placeholder ammunition is present: https://i.imgur.com/J4zm011.png

The weapon CANNOT be unloaded: https://i.imgur.com/ENJUP18.png

Some kind of method for bypassing the unloaded-only modification restriction for UPS powered weapons is needed.

**Comment by Malkeus** [comment]
I reproduced the entire sequence in a clean unmodded game just to be certain:
https://i.imgur.com/zIK3sa6.png

**Comment by mugling** [comment]
Certainly #15000, either we get rid of fake ammo (a long term goal) or special case `item::gunmod_compatible`. Good issue report btw.

**Comment by Malkeus** [comment]
Thanks, I've been working on my reporting. It's easier when it's a nice
clearcut error that's readily reproduced.
I don't know how the a7 and ups interact, but if it didn't load the fake
ammo till you actually fired and left the gun empty otherwise, this
wouldn't be an issue.

**Comment by Noctifer-de-Mortem** [comment]
Maybe a flag "UPS_AMMO" or something like that to exempt ups only firearms?

**Comment by Malkeus** [comment]
Quote from @mugling in #15128:
> Yes, this is on the list of things I want to look at but a special case in gunmod_compatible is the wrong solution. ammo_remaining() and 
ammo_data() need to become more aware of 'fake' ammo types.

I'm not sure what mugling intends, but it's beyond my fairly limited c++ abilities.

**Comment by Malkeus** [comment]
![image](https://cloud.githubusercontent.com/assets/16219776/13331632/eb74bc3e-dbc3-11e5-9d9e-12bcd20d69f0.png)

0.C-11261-g75886c0 - remains in full effect.
