### ISSUE TITLE
Misleading "out of ammo" due to no magazine

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15122]
Got a drop of 5x50mm and SPIW for it, both are shown as green, but reloading results in "out of ammo".
I assume this is because I lack the magazine.

**Comment by mugling** [comment]
Will look into this

**Comment by mugling** [comment]
Can reproduce. Additionally magazines should be displayed green when reloadable

**Comment by mugling** [comment]
Do you have any idea where the relevant code for setting the item color is?

**Comment by DeadLeaves** [comment]
I think also the issue is that it says "out of ammo" even when you have ammo. maybe something more descriptive would help "No magazine that fits" or similar.

**Comment by mugling** [comment]
The latter is a simple (and rational) extension but I'm uncertain where the code that adds the green text is to be found

**Comment by macrosblackd** [comment]
If you take a look at Coolthulhu's recent change with food, that should be the same area that the coloring happens.

**Comment by DanmakuDan** [comment]
It's in `src/item.cpp`, in `item::color_in_inventory` https://github.com/CleverRaven/Cataclysm-DDA/blob/522dc33a33658022219ba42693063851f587770f/src/item.cpp#L1843
