### ISSUE TITLE
RM121 aux shotgun ammo display error.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#15130]
The ammo counter displays incorrectly when the weapon's fire mode has been switched to use this gun mod.

----
Example:

When the fire mode is set to either of the rifle settings:
![rifle mode](https://cloud.githubusercontent.com/assets/5084581/12706077/66859618-c842-11e5-97ee-47878038e572.png)

Now set it to the shotgun:
![aux mode](https://cloud.githubusercontent.com/assets/5084581/12706079/6a59a63a-c842-11e5-9dcb-049aa44093a3.png)

It's still loaded and can be fired, it just doesn't display the current ammo count properly.

**Comment by mugling** [comment]
Can reproduce, the bug is in `player::weapname`
