### ISSUE TITLE
wool_suit - What is it?

### ISSUE THREAD

**Issue by shokolatOtobus** [CleverRaven/Cataclysm-DDA#15145]
Added in 2014, Exists only as an (unconnected?) recipe and a tea shop (shop) spawn.

I'm torn between what it is supposed to be; currently I theorize that it is either:

Some sort of esoteric cold-armor:
- It is classed as type:"ARMOR"
- "It looks like a full body armor but it only protects against cold, sadly." - latter end of description

Something like [this](https://s-media-cache-ak0.pinimg.com/236x/82/82/ce/8282ce35ae0e879afb983b8c24e96bee.jpg):
- it spawns in a tea shop (shop) - I found it in a pile of fancy clothing
- "An encumbering wool suit covered in nice patterns." - former end of description, implies to not be makeshift?

And even if it is either three things still confuse me:
- Color is light red?
- 70 warmth, even for its encumbrance?
- It covers EVERY part of the body?

The actual fixing should be rather simple, but the question here is just what this thing should be.

**Comment by Rivet-the-Zombie** [comment]
Something like [this](http://storage.coolfeed.co/2012/12/Full-body-knitted-suit-for-those-harsh-winter-mornings-coolfeed.co_.jpg) maybe?

**Comment by shokolatOtobus** [comment]
I'm pretty off my image search game!
That looks pretty in-line with the description and classification, so I suppose all that is needed is a parameter re-tune and probably removal from the tea shop (shop) spawn list - though that shop shop needs quite the touch up also.

**Comment by Rivet-the-Zombie** [comment]
Make sure to fix the recipe too!

Also, it probably shouldn't cover the face either.

**Comment by kevingranade** [comment]
Weird, the color makes me think an over- version of wool long johns.

**Comment by Rivet-the-Zombie** [comment]
Good point. The 'covered in nice patterns' part and the fact that it covered the whole body made me think of some sort of weird costume though.

**Comment by shokolatOtobus** [comment]
Closing on account of PR being merged.
