### ISSUE TITLE
Should ammunition books contain magazine crafting recipes?

### ISSUE THREAD

**Issue by Ataman** [CleverRaven/Cataclysm-DDA#15166]
Since books like The Handloader's Helper and the Rivtech design binder contain recipes for bullets it sounds reasonable to me adding recipes for magazines as well.
What do you guys think?

**Comment by chaosvolt** [comment]
Perhaps depends strongly on the style of magazine. An AKM or Sten for example uses stamped sheet metal, and is overall perhaps easiest. Makeshift Sten magazines exist largely because they're even more improvised than a Sten mag would normally be.

A standard MP-40 or Sten mag is double-column, single-feed design, which is mechanically complex but easy to replicate if adequate design documents are available. The makeshift version is outright stated to be simplified via being a pure single-stack, additionally explaining its reduced capacity.

AKM mags would maybe be feasible, but we don't have mags for them yet. I have them statted out but was waiting on a big itemgroup rework @mugling is working on. After that, if they don't add the versions I offered up, I can later on re-add the magazines to my PR that was reworking Icecoon's Weapons Pack to use the magazine system.

**Comment by mugling** [comment]
For the most part magazines are **not** intended to be craftable as their rarity is supposed to provide an interesting set of choices to the player.

See `doc/GAME_BALANCE.md` and also the discussion in #14981 from which the below quote is taken:

> One thing about magazines is that in certain circumstances it would be reasonable for them to be quite rare post-cataclysm

That said considerably inferior home-crafted alternatives such as @chaosvolt's makeshift STEN magazine are both thematic and well balanced. These makeshift versions should always be worse than scavenged factory-specification magazines. Milspec magazines should never be craftable.

From a game-play perspective the only reason for multiple ammo types to exist is if they have different properties. `7.62x39mm` should have some better stats than `223`. Given that you can reload ammunition (a good thing) we can't balance it by making the ammo rarer but we can balance it by making the guns and magazines less common, except of course if you can craft a large supply of them also.

**Comment by chaosvolt** [comment]
Right, makes sense. I was thinking that even a player-crafted AKM magazine could still be given higher weight and lower reliability than a factory AK mag. So even the rare handful of magazines the player could craft should be balanced against the design they're copying.

**Comment by Ataman** [comment]
Adding makeshift magazines sounds great. I think it fits since we have the reloaded ammo quality as well.

**Comment by mugling** [comment]
> Adding makeshift magazines sounds great.

> So even the rare handful of magazine types the player could craft

I'd agree with both **rare** and **handful**. Effectively a case by case basis. I'd actually rather avoid a craftable AKM magazine at all for the reasons above. Your thoughts as to this @chaosvolt?

> I think it fits since we have the reloaded ammo quality as well.

Remember though craftable gunpowder was dropped because with it guns were unstoppable (that and the recipe was a serious departure from reality). Magazines are intended as an overall nerf to guns so that, presuming we get the balance correct, some other factors (range and possibly damage) can later be buffed.

**Comment by Ataman** [comment]
The makeshift magazines could render reload time, recoil and accuracy horrible. It certainly should not be the preferred solution but it would make the gun at least fireable. (In case your milspec magazine breaks and you need an emergency solution for example).

**Comment by chaosvolt** [comment]
Well, I was thinking of the AKM magazine as a realistic example. Home metalsmithing setups do make them feasible to make, and thus a makeshift variant would be a natural choice for that version. The idea would be to have a fairly small selection of options for player-crafted magazines. Aside from Sten mags, AKM mags, and M1 en-bloc clips, I can't actually think of any ADDITIONAL realistic options for player-crafted magazines. So limiting it to the 4 different chamberings these options leave available might be acceptible.

Note that I also intended for the makeshift Sten mags to be booklearned-only, which adds an additional balancing factor.

**Comment by mugling** [comment]
> (In case your milspec magazine breaks and you need an emergency solution for example).

Say like a handgun in an ankle holster, drawing a knife, driving/running/limping away? I want magazines to add to your tactical choices not merely make you press `r` twice when reloading.

> The makeshift magazines could render reload time, recoil and accuracy horrible

Increased reload time won't be relevant past a certain point especially as the plan is to make standard magazines a good long wait in any case. Recoil and accuracy won't be changed by the magazine.

> I can't actually think of any ADDITIONAL realistic options for player-crafted magazines.

There's ammo belts and I'm still deciding how these should actually be made (probably via crafting?)

**Comment by chaosvolt** [comment]
Hmm, maybe. Ammo belts might not be a practical option, but I'd need to find info on that.

If it made LMGs more worth using though... o3o

**Comment by Ataman** [comment]
@mugling you're right that adding reload time alone wouldn't help. I assumed accuracy and recoil could be effected by the magazine.

**Comment by chaosvolt** [comment]
Maybe, not sure.

**Comment by Ataman** [comment]
The Reliability section of doc/GAME_BALANCE.md states several levels and already limits makeshift magazines to a reliability of 5(usable) maybe 6(acceptable). Wouldn't the risk of catastrophic failure and severe damage to the gun (and player) balance it already by a good amount?

**Comment by Rivet-the-Zombie** [comment]
A magazine malfunction is going to cause a failure to feed or come unseated, not do anything catastrophic.

**Comment by chaosvolt** [comment]
Probably would still be Fun. However...if a failure could damage the magazine itself? Though that sounds just as annoying and video-game-y as a stovepipe damaging the gun. :V

**Comment by Ataman** [comment]
How about a stuck magazine as catastrophic failure? (Being unable to swap your empty magazine with a dozen zombies coming at you could very well end 'catastrophic' for your well being).
Your makeshift magazine getting stuck in your gun after firing actually sounds pretty likely to happen. Stuck to a point where you need a repair tool and at least half an hour to get it unstuck.

**Comment by chaosvolt** [comment]
Ohgod. ;w;

**Comment by mugling** [comment]
A `jammed` status is being considered

**Comment by mugling** [comment]
Most guns now have magazines and the spawn frequency issues are largely resolved so I'm closing this issue as redundant
