### ISSUE TITLE
Instability increases

### ISSUE THREAD

**Issue by DeadLeaves** [CleverRaven/Cataclysm-DDA#15170]
The latest versions are really unstable and work kinda funky. Latest version I've run for a "long" while was 4231 and it was perfectly fine. maybe 1-2 crashes every 10 hours. no real biggie. However the latest 4310 and now 4312 are really acting weird on me. I've been playing 4310 for a couple of hours and I've had loads of things acting up on me.
* First are the crashes, they seem to come all time time. 10-15 min at best. and sometimes almost instantly. The crashes seem to be related to fires and explosions. And this is happening even after the shrapnel fix of 4312.
* Secondly, monster damage seem to be insane sometimes. I've had regular zombies on-shot me at more than 80% health (No -%life traits). And some zombies just chew through tanks and buildings as if they were paper.  (More or less walking through them destroying as they go)

As of writing I have no way to consistently reproduce either (mostly due to world deletion on character death), but I will keep playing tomorrow and try to replicate them if possible.

**Comment by DeadLeaves** [comment]
The crashes seems to have been fixed by a PR earlier by coolthulu. 

Still seeing zombies attack for massive damage sometimes. No idea what causes it.

**Comment by Coolthulhu** [comment]
Are you sure they're hitting for a lot of damage and not just multiple times?
Counter attacks take time and when your melee time penalty is high enough, it can easily take more time to counter attack than you have per turn. This results in #15101
I haven't seen the damage bug, but the counter attack lockdown is quite easy to reproduce.

**Comment by DeadLeaves** [comment]
That could very well be it. Though can that happen without a without any martial art? If so, then that is probably the explanation.

**Comment by Coolthulhu** [comment]
No, but brawling has a counter attack.

**Comment by DeadLeaves** [comment]
The crashes are gone, and I haven't had an instakill in over 20 hours. So I'm marking this closed.
