### ISSUE TITLE
Single load weapons with no magazines

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#15172]
It should be possible to fire some magazine-less firearms by  loading the bullets directly into the chamber. Should probably include a chance of damaging some weapons, and be outright impossible in others.

Guess the same mechanic would also allow for the  magazine +1  current chambered bullet thing.

**Comment by mugling** [comment]
Will consider but only once all of the existing magazine framework is complete

**Comment by chaosvolt** [comment]
Aye, this has been discussed. o3o

**Comment by Rivet-the-Zombie** [comment]
Good idea!

**Comment by mugling** [comment]
Duplicated by #15513 where most of the recent discussion can be found (and continued if anyone has further comments)
