### ISSUE TITLE
Perishables in containers that do not prevent spoilage are no longer color-coded

### ISSUE THREAD

**Issue by Man-animal** [CleverRaven/Cataclysm-DDA#15173]
Somewhat annoying as you typically want to consume perishables first.

**Comment by Malkeus** [comment]
Confirmed. And ditto on the annoyance factor. I like that stuff I'm allergic too appears to be shown in red now, except I'm not sure that's what's happening since ketchup, mustard and milk are red and I only have junk food intolerence.

**Comment by chaosvolt** [comment]
Oh shit. I assumed it was just tin cans and others that would do this.

![immortal bread](https://cloud.githubusercontent.com/assets/11582235/12739376/c8b90a3a-c92e-11e5-82a0-4bd625e244d0.png)

**Comment by Zireael07** [comment]
Hmm, related to #15057?

**Comment by chaosvolt** [comment]
Maybe? I'm not sure, I'm looking at @Coolthulhu's summary on code changes and I'm struggling to see anything that could've plausibly changed display coding.

**Comment by Coolthulhu** [comment]
I combined 2 nearly identical sections of code: one checked if the current item can rot, the other if the item contained in current item can. I even added a temporary variable to check which item should dictate the color, but I forgot to use it where it was required, so colors were only taken from current item (the container or container-less food).

**Comment by chaosvolt** [comment]
Ah, I see. o.o
