### ISSUE TITLE
Can't drink when full  0.C-10087-g5c1adc3 (4312)

### ISSUE THREAD

**Issue by NickGrease** [CleverRaven/Cataclysm-DDA#15178]
When my character is Full + VeryThirsty, trying to drink a bottle of Fruit Juice, prompts me that I won't be able to finish it - I drink anyways - tells me I couldn't finish it all - but my thirst doesn't go down. After 6 bottles - still very thirsty.

My guess, since fruit juice has a nutrition value, it's failing the eat check (full) and bailing out before doing the thirst check. (Or something like that, I'm tired :)

**Comment by chaosvolt** [comment]
Old problem is old. :V

**Comment by NickGrease** [comment]
What can I say, its been a while since I played. Thanks.
