### ISSUE TITLE
Turbolaser turret triggers "Tried to burst fire a semi-auto" debug-message

### ISSUE THREAD

**Issue by Ataman** [CleverRaven/Cataclysm-DDA#15174]
Version: 0.C-10085-g6b59b99 (tiles)

Firing the turbolaser turret from a vehicle results in the mentioned debug message.
turret mode doesn't matter, the message always appears when firing, manually or otherwise.
The turret itself doesn't have a burst mode either, only single and manual mode.
Apart from that, it works fine and the laser shoots happily at any grumpy zombies which happen to be in front of it, much to their discomfort.

**Comment by mugling** [comment]
I thought that code branch was dead, but obviously not
