### ISSUE TITLE
Setting up a Metal Funnel fails with an odd message and deletes the funnel. 0.C-10087-g5c1adc3

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#15180]
This was on reddit: https://www.reddit.com/r/cataclysmdda/comments/43ldm0/metal_funnel_bugged/ So I tried it out and it's definently wonky.

https://i.imgur.com/dhTs2DP.png

" Tried to set a trap. But got confused!
  metal funnel "

I don't think it should make a difference, but my trap skill is 4.

To reproduce, spawn in a metal funnel and 'A'ctivate it. Pick any open square as the direction.

Funnel, leather funnel and makeshift funnel work correctly.
https://i.imgur.com/hopaZ22.png

**Comment by chaosvolt** [comment]
I can see this being another good use from JSONization of trap properties...or at the very least, JSONizing the use_action itself.

The issue that the trap-placing use_action is hardcoded to look at what to place, based on a select list of item IDs it looks for.
