### ISSUE TITLE
Easier reloading suggestion.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#15185]
I'm in love with @mugling's magazine expansion, but can we get something to make ejecting spent magazines a bit easier?

----
Currently it works as such:

You empty the magazine in your currently equipped firearm into the approaching horde.
You press `U` to remove the empty magazine.
You press `r` to bring up the magazine selection menu.
You select a magazine and it loads into the firearm.

But it would be much easier for the player if it worked like *this*:

You empty the magazine in your currently equipped firearm into the approaching horde.
You press `r` and the game brings up the magazine selection menu.
You select a magazine and the game automatically removes the current magazine then loads your firearm with the one you just selected.

**Comment by chaosvolt** [comment]
I've suggested this before, yes. o3o

**Comment by kevingranade** [comment]
Yep, that's a must have.
When ejecting, it should give you options for dropping it (fast) or
stashing it (either slower or much slower depending on whether you have a
free ammo pouch).

**Comment by chaosvolt** [comment]
Yeah. Basic series of events is to automatically unload a magazine on hitting reload, if I recall. Among other things that would entail details to be worked out.

**Comment by mugling** [comment]
> You select a magazine and the game automatically removes the current magazine then loads your firearm with the one you just selected.

This is simpler than the other suggestions (which included reloading the empty magazine itself with ammo). I can't think of a situation where you don't want to eject an empty magazine.

> When ejecting, it should give you options for dropping it (fast) or stashing it (either slower or much slower depending on whether you have a free ammo pouch).

Probably should refactor the list of options from `player::wield` to be a more generic `player::stash` and we can then target the latter for automation of some actions dependent upon the situation.

Unless there are objections I'm going to start using the following terminology to reduce confusion:
* You **reload** magazines with ammo
* You **unload** magazines with ammo
* A magazine is **loaded** when it contains ammo
* A magazine is **empty** when it contains no ammo
* You **insert** a **loaded** magazine into a gun
* You **eject** an **empty** magazine from a gun

**Comment by chaosvolt** [comment]
Glorious grammar issues, yay. o3o

**Comment by mugling** [comment]
Was fixed in #15185 although some further enhancements are pending in #15413
