### ISSUE TITLE
The FTK-93 fusion gun shoots through walls on 0.C-10145-g935039e

### ISSUE THREAD

**Issue by Ataman** [CleverRaven/Cataclysm-DDA#15198]
On version: 0.C-10145-g935039e (tiles)

Not only is it possible to miss with the fusion gun now, you will also shoot through walls when doing so.
This behaviour is not only problematic in some situations but could also potentionally be abused in certain others. Knowing the average range and some guessing you can hit any monsters without fair of retaliation by standing behind walls.

(Trying to fight your way into the science lab loot chamber is kinda hard with the fusion gun at the moment, since most shots end up flying through the walls and setting the chamber on fire, even when not shooting directly through the doors).

**Comment by kevingranade** [comment]
Haven't you seen Eraser? This is totally reasonable.


Not really, definitely a bug, thanks :)

**Comment by Ataman** [comment]
No problem! 
I didn't see Eraser but I played Perfect Dark in the old days. That was the last time I saw weapons firing through walls. ^^

**Comment by Coolthulhu** [comment]
I'm pretty sure this doesn't happen anymore.
