### ISSUE TITLE
Reloading item with liquid dumps the liquid into inventory with no (easy) way of returning the liquid to a container.

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#15200]
As per this comment on the forum: http://smf.cataclysmdda.com/index.php?topic=14.msg266539#msg266539

I've verified that this happening, to reproduce:
- Item that uses liquid charges (I used oil lamp)
- reload item so that there is spare charges remaining (get 400/800 charges, then refill with full bottle (800) of lamp oil)
- Oil will now be in inventory.

**Comment by mugling** [comment]
Can reproduce, have potential fix in #15206

**Comment by macrosblackd** [comment]
Seems to be fixed.
