### ISSUE TITLE
Ursine Vision not affected by Telescopic Eyes CBM

### ISSUE THREAD

**Issue by velddrinn** [CleverRaven/Cataclysm-DDA#15211]
Right now Ursine Vision sight limitation can be neglected with glasses or contact lenses. However, Telescopic Eyes is also supposed to be like "any vision problems you might have had are now gone", but it doesn`t affect Ursine Eyes in any way.

Maybe it should be treated as "integrated glasses" and remove Ursine Vision range handicap totally?

**Comment by elricsfate** [comment]
@kevingranade 

Is the "fixes eyesight" thing some sort of flag on items? If so, this should be trivial to add and makes sense.

**Comment by velddrinn** [comment]
Thats from bionics.cpp:

        if( bioid == "bio_eye_optic" && has_trait( "HYPEROPIC" ) ) {
            remove_mutation( "HYPEROPIC" );
        }
        if( bioid == "bio_eye_optic" && has_trait( "MYOPIC" ) ) {
            remove_mutation( "MYOPIC" );

So right now it just removes "Near-sighted" and "Far-sighted" from Traits list on "Telescopic eyes" CBM installation event.

**Comment by velddrinn** [comment]
However, there is a section in character.cpp that affects sight_max:

// Set sight_max.
    if (has_effect( effect_blind ) || worn_with_flag("BLIND") || has_active_bionic("bio_blindfold")) {
        sight_max = 0;
    } else if( has_effect( effect_boomered ) && (!(has_trait("PER_SLIME_OK"))) ) {
        sight_max = 1;
        vision_mode_cache.set( BOOMERED );
    } else if (has_effect( effect_in_pit ) ||
            (underwater && !has_bionic("bio_membrane") &&
                !has_trait("MEMBRANE") && !worn_with_flag("SWIM_GOGGLES") &&
                !has_trait("CEPH_EYES") && !has_trait("PER_SLIME_OK") ) ) {
        sight_max = 1;
    } else if (has_active_mutation("SHELL2")) {
        // You can kinda see out a bit.
        sight_max = 2;
    } else if ( (has_trait("MYOPIC") || has_trait("URSINE_EYE")) &&
            !is_wearing("glasses_eye") && !is_wearing("glasses_monocle") &&
            !is_wearing("glasses_bifocal") && !has_effect( effect_contacts )) {
        sight_max = 4;
    } else if (has_trait("PER_SLIME")) {
        sight_max = 6;
    } else if( has_effect( effect_darkness ) ) {
        vision_mode_cache.set( DARKNESS );
        sight_max = 10;

Maybe a workaround could be added here to check if a chacter has "bio_eye_optic".

**Comment by Malkeus** [comment]
should be as simple as adding 
&& !has_bionic("bio_eye_optic")
into the 4th elseif, right?

**Comment by Malkeus** [comment]
I would have thought telescopic vision would have worked like this in the first place, but it apparently completely replaces the eye which is why it removed myopic and hyperopic in the first place. Perhaps it should remove ursine vision on install and prevent it from being added in the event of a mutation instead of a simple workaround as above. Would be an interesting mechanic for a bionic to affect mutation. Does Ursine vision lead to anything in the mutation tree?

**Comment by velddrinn** [comment]
Thats the good point, actually, as long as we treat "Telescopic eyes" as full replacement of organic ones.This should have same effect on all other eyes mutations probably.

**Comment by elricsfate** [comment]
Side note: Would a more apt name for "Telescopic Eyes" be something like "Cybernetic Eyes"? I'm thinking of something from Ghost in the Shell when I envision this.

**Comment by nulman** [comment]
i agree the bionic should fix the vision problem, but i dont think it should remove the trait.
the trait is genetic, just because you replaced your eyes doesnt mean your genetics changed, or at least it shouldnt impact your threshold.
