### ISSUE TITLE
Reloaded 9mm ammo descriptions messed up

### ISSUE THREAD

**Issue by velddrinn** [CleverRaven/Cataclysm-DDA#15212]
Some descriptions and "pierce" stats in 9mm.json are not complient, like:

    "id": "reloaded_9mm",
    "type": "AMMO",
    "name": "reloaded 9x19mm FMJ",
    "description": "9x19mm ammunition with a hand-reloaded jacketed hollow point bullet...",
    "damage": 23,
    "pierce": 2,

and

    "id": "reloaded_9mmfmj",
    "type": "AMMO",
    "name": "reloaded 9x19mm JHP",
    "description": "9x19mm ammunition with a brass jacketed hand-reloaded bullet...",
    "casing": "9mm_casing",
    "damage": 25,
    "pierce": 2,

Looks like either "Name" or "Description" should be changed places, and "Pierce" value removed on JHP.

**Comment by mugling** [comment]
#15162 didn't change any values. I remember some time ago ammo was update with new descriptions for FMJ so possibly handloaded ammo was missed out at the time?

It might best to swap the `id`s for `9mm` and `9mmfmj`?
