### ISSUE TITLE
Stats Through Skills: Inconsistant stat calculation

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#15226]
So, I'd started toying with the recently-changed Stats Through Skills mod. Right away I discovered it was sharply...sorta buffed, sorta nerfed, by making it look at total skill points linked to a given stat. So while that means you can mix and match your skills and still get stat points, the total amount of stat points earned is reduced.

Further testing revealed an anomaly though, as after discovered I gained a point at 4 strength-linked skills, I couldn't find the next threshold point beyond that. When it got to the point of investing 2 points in 5 skills, I realized something seemed fishy. It wasn't until I hit 12 that the second point was gained.

EDIT: I done derped, the blackbelt example was due to unarmed being a dex skill. >.<

**Comment by chaosvolt** [comment]
Additionally, testing INT I found I didn't gain a second stat point until hitting...12. So you get stat points at 4, 12..this is some seriously wonky shit even when it's working right. Which kinda seems like they went too FAR in the course of nerfing this.

**Comment by macrosblackd** [comment]
You've got that backwards, unarmed and dodge are dex skills, melee is str.

**Comment by macrosblackd** [comment]
If I'm looking at the calculations correctly, As you pointed out the first two thresholds are 4 & 12. The rest are: 4, 12, 24, 40, 60 & 84. I'm thinking about possibly using a function rather than a simple threshold to determine bonus though.

**Comment by chaosvolt** [comment]
Huh, that's odd...oh. Shit, that explains it. I could've sworn unarmed was a strength skill. Doh.

**Comment by chaosvolt** [comment]
That said, I like that threshold idea, but it'd really be a lot saner if it was linear.

**Comment by chaosvolt** [comment]
I guess technically the original bugs here were just a mistake on my end, should probably close this as the only complaint left is how much of a jump it is between one stat point and the next.

Though that is inconsistent in its own way.

**Comment by Malkeus** [comment]
skill_total = skill_total / 7
    skill_bonus = math.floor(skill_total + .5)

I'm using this in place of the long series of if/else statements. It's doesn't have a cap and gives enough bonus to keep me happy. I haven't had the time to test it extensively or do the math, but it works for me so far.
