### ISSUE TITLE
Ammo in burning magazines not affected by fire

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15239]
Since most magazines aren't flammable, this means that ammo can be stored in raging fire just fine.

**Comment by macrosblackd** [comment]
Aren't most mags plastic or composites anyway? I would think they should burn.

**Comment by DeadLeaves** [comment]
Even if the magazines themselves aren't flammable, the ammo inside should IMO cook off real quick anyway.

**Comment by Rivet-the-Zombie** [comment]
>Even if the magazines themselves aren't flammable, the ammo inside should IMO cook off real quick anyway. 

This right here.
