### ISSUE TITLE
I keep having Zombie Dancers Spawn everywhere

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#15246]
Zombie Dancers Keep spawning, as early as 4 hours into the game.  This has happened in multiple worlds with different characters.  Given how fast and tanky they are . . .

This isnt a funny joke :|

**Comment by Zireael07** [comment]
Points to no joke monsters mod.

Are you on dynamic or static spawn? If dynamic (as I guess from 4 hrs mention), it's near obsolete

**Comment by kevingranade** [comment]
If they're spawning without a Thriller it's a bug.
If a Thriller is spawning and making dancers they're relatively harmless.

**Comment by pisskop** [comment]
I had seen 1 thriller in 1 world, then the dancers would appear across the rather large city.

In the new worlds I didnt see any.  Nor have I seen them since.
