### ISSUE TITLE
Vehicle-mounted flamethrowers print debugmsg every shot

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15240]
"Unexpected shortage of ammo"
Happens regardless of whether burst mode is on or off.

**Comment by stk2008** [comment]
i reported this last week i think i was sure some one said they fixed it.
obviusly i was wrong if your getting dame error.

At least it was not me doing some thing silly...for a change :)

**Comment by BevapDin** [comment]
@mugling In `vehicle::fire_turret` (vehicle.cpp:6274) the charges for the temporary gun item of the turret are limited to the burst size:
```C++
long charges = std::max( 1, turret_data.gun.burst_size() );
```
Flamethrowers have a burst size of 4, so they only get 4 charges, but they require 100 charges for each shot (`item::ammo_required` or so, used to be the FIRE_100 flag). Maybe the burst size should be multiplied by that?
