### ISSUE TITLE
Innate STR loss when purifying HUGE_OK

### ISSUE THREAD

**Issue by joneskun** [CleverRaven/Cataclysm-DDA#15245]
Seems to be 4-8 points depending on your level of STR_UP_x at the time HUGE/HUGE_OK is purified or lost, and whether or not they both get purified in the same call.

**Comment by kevingranade** [comment]
This is working as intended, HUGE_OK gives +4 strength, if you lose it, you lose the bonus, if you purify away other strength boosting mutations at the same time, you also lose them.
