### ISSUE TITLE
NPC Follow Broken - Build 4336

### ISSUE THREAD

**Issue by elricsfate** [CleverRaven/Cataclysm-DDA#15248]
Build: 0.C-4336 Graphical
Platform: Windows 7 x64
Bug: NPC Followers do not follow Player Character around. 

Replication Steps: Successfully recruit an NPC follower. Walk outside range NPC should start following (~5 blocks). NPC does not follow.  

**NOTE:** fresh world on the new spawn NPC.

**Comment by Coolthulhu** [comment]
Can't replicate. Need more data.

Turn on debug mode (by default shift+`) and wait a turn to see what action is the NPC trying to pick.

**Comment by DeadLeaves** [comment]
I've been running 4337 and I have followers working just fine. Cannot replicate

**Comment by stk2008** [comment]
Will need to ceck version but the static npc in start shelter agreed to be
with me but he would not follow.

I will try at so,e point to get debug message

**Comment by elricsfate** [comment]
Alright, I downloaded the latest version, 4338, and confirm it's occurring on this version too. I know that it wasn't broken on 4296. 

I have Icecoons, all the vehicles mods, and all building mods but animatronics enabled.

Pictures attached demonstrating bug. Debug enabled. 

![screenshot 2016-02-05 20 20 27](https://cloud.githubusercontent.com/assets/523926/12864048/303bfebe-cc46-11e5-9582-66695c1f4ca4.png)

![screenshot 2016-02-05 20 20 48](https://cloud.githubusercontent.com/assets/523926/12864047/2d782504-cc46-11e5-95d7-c038a25d1689.png)

**Comment by kevingranade** [comment]
I think I see your problem, the brothers in Arrested Development just don't
get along, so of course they won't follow each other.

**Comment by DeadLeaves** [comment]
I think it might be the starting NPC near you. Have you gotten the bug with anyone but him/her?

**Comment by elricsfate** [comment]
Open and shut case ladies and gentlemen. lol

Anything I can do to aid a fix? Seems like it's only effecting some people.

**Comment by DeadLeaves** [comment]
Well, if you could confirm if it can happen to any NPCs or only the one starting beside you at a new game. that'd help narrow it down.

**Comment by Coolthulhu** [comment]
OK, I found it.
In my refactoring to re-allow NPCs to pick up stuff, I made them prioritize their mission over following the player. Which would be all OK, except the NPC agreed to follow and so should ignore the mission.
Worse - the NPC would probably follow you if you entered a vehicle.

If you want a quick fix for now (I might not have the time to fix it until ~Tuesday), debug in debug mindcontrol mutation, tell the NPC to guard and then tell the NPC to stop guarding. Then debug the MC mutation off or all your NPC dialogue chances will be 100%.

**Comment by elricsfate** [comment]
@Coolthulhu 

Good find. I can confirm the portion about them trying to get in the vehicles with you. 

Would it be possible to roll back to the working commit and then reintroduce the code later or is that not best practice? I mean simply rolling back the errant portion of the code.

**Comment by Coolthulhu** [comment]
That would be more work than properly fixing it.
