### ISSUE TITLE
Let's nominate a list of dark craftable recipes that preserve balance

### ISSUE THREAD

**Issue by nonymous** [CleverRaven/Cataclysm-DDA#15260]
Obviously some things can be done blind, guided by touch, smell and sound cues.  Probably nothing too extreme, let's nominate a list. I nominate these recipes:

Things you just chuck in a pot and boil or heat:
clean water
cooked meat
fried spam
boiled stomach
large boiled stomach
boiled egg
broth
bone broth
tallow
cooked burrito
cooked tv dinner
boiled noodles
cooked acorn meal
roasted hickory nuts
pine nuts
bark tea
pine tea
bee balm tea
dandelion tea
tea

Things you just mix or possibly assemble 2-3 things lying around:
milk (water and powder)
milk tea
coffee milk
sweet water
lemonade (from mix)
protein drink (powder & water)
popcorn (tells you when it's done)
almost every cocktail recipe
vodka (ethanol and water)
insta salad
meat sandwich
peanut butter sandwich
jam sandwich
pb&j sandwich
ph&h sandwich
boring sandwich
cheese sandwich
nachos with cheese
s'mores

Things you can just do by feel anyway:
shelled hickory nuts

**Comment by Coolthulhu** [comment]
> cooked acorn meal

Preparing acorns requires chopping them up. That could be dangerous in total darkness.

**Comment by nonymous** [comment]
Checked that one, and I agree it's too complex for the inexperienced while completely blind.  Two methods of cooking required, probably ought to be able to see the mid step.  
Chopping them however would never be as dangerous as crawling through vehicle wrecks or broken windows or even reaching into a bag full of sharp stuff.

**Comment by kevingranade** [comment]
So perhaps those other things should have a chance of injury.  Comparison
to other game features is almost never a valid argument, because it's just
as likely to be an oversight, and the tradeoffs involved are different.

**Comment by nonymous** [comment]
That seems pretty legit Kevin.

**Comment by nonymous** [comment]
To clarify I agree there should be more chances to get incidentally wounded. If I have a backpack full of razorblades and broken glass, it's risky A.F. to be trying to use that as a source for thrown missiles mid combat.  Same goes for a backpack full of lawndarts and rebar, hows that going to treat me if I jump from my car?

**Comment by Man-animal** [comment]
What would that actually contribute to gameplay, though, other than simply making it so players will never carry those things around?

**Comment by Beanzy** [comment]
That reminds me, didn't a blind lady win on Masterchef before?

Maybe a trait to expand the range of blind recipes could be added at some point too. Something along the lines of: "A lifetime of poor eyesight/blindness has made it easier for you to craft in total darkness".

Just a random thought I had.

**Comment by kevingranade** [comment]
We've talked about having permanently blind players before as an extreme
challenge, but we need probably an entirely new system for them to use for
navigation and detecting enemies. Until that's in place, adding random
things to crafting is pointless.

**Comment by Leland** [comment]
We're past a year since the last comment on this, so closing. If there's still interest by anyone, let me know here and I'll reopen; or feel free to make a new issue.
