### ISSUE TITLE
Unable to see count of arrows in quiver

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#15266]
Not sure if this is a regression or just something that was never really noticed, but I can't see how many arrows are in a quiver. Even going into the quiver info screen only shows the arrow stats, but not the count.

**Comment by mugling** [comment]
Not a recent regression and I don't think the info screen ever showed this. Not being able to determine the current number of contained arrows is however a bug so I'll look into this.
