### ISSUE TITLE
Was able to reinforce a Molotov cocktail with a Tailor's Kit.

### ISSUE THREAD

**Issue by Nymall** [CleverRaven/Cataclysm-DDA#15262]
Version 0.c-10271-g8627981, Build 4337.

I am able to reinforce Molotov Cocktails with a Tailors Kit because of the cotton component of the item.

**Comment by BevapDin** [comment]
Duplicate of #7761

**Comment by elricsfate** [comment]
If this is a dupe, please close @Nymall
