### ISSUE TITLE
Core Dumps after hitting mine with car

### ISSUE THREAD

**Issue by nutstrength** [CleverRaven/Cataclysm-DDA#15278]
from the subreddit: https://www.reddit.com/r/cataclysmdda/comments/443lot/backed_over_a_mine_and_the_game_exploded/

More description:

I hit a mine with a car, and everything was fine, but the wheel that hit the mine was grey, still attached but broken.  Then, I hit another mine and the core dumped.  I saw this in an earlier version as well, driving into minefields is something I should probably stop doing.

In the past I've actually driven through a minefield and fixed my car, and since the minefield was the easiest way to return, just driven the same path as before on the way out of an area.  Then last fall I played a short round where, getting a regular car up and running, I decided to take a no headlights night drive away from my base where I was out of food.  I almost immediately hit a minefield and had a coredump/tableflip as I had not saved for hours.

This time I built an armored car from hummer and apc parts.  Starting with 3 garages and a public works in sight, it was no problem.  So it resisted one mine, but the second one dumped the core.  I had had the foresight to save, and at Rivet's prompting I pulled and recompiled and then tried the minefield again, boom, core dumps.

**Comment by DanmakuDan** [comment]
If you still have that save, can you upload it here?
