### ISSUE TITLE
Activating certain items causes them to disappear 0.C-10370-g2b93914 

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#15283]
Items tested:
- MP3 Player
- Locksmith Tools

**Comment by Rivet-the-Zombie** [comment]
Confirmed for both.

**Comment by articulateSPLINE** [comment]
I've just noticed it with the crowbar and heavy duty flashlight as well!

**Comment by adrianrieck** [comment]
I noticed the same thing with trying to throw a Molotov cocktail, It just vanished after I lit it. Must be a quite recent bug as I did pull about a week ago and it wasn't happening then. Seems pretty unplayable in the current state.

**Comment by Zireael07** [comment]
Just a hunch, related to #15195? That's the most likely culprit as it has a lot to do with activatable items...

**Comment by zj44** [comment]
I did some poking around in experimental versions and it appears that the bug appeared something after version 4344. I didn't test 4345, but 4346 and on experience the issue.

**Comment by mugling** [comment]
@Zireael07 yes, #15195 is responsible
