### ISSUE TITLE
Debug Messages appearing when using Scabbards and other Sheaths

### ISSUE THREAD

**Issue by Boredone** [CleverRaven/Cataclysm-DDA#15296]
Whenever I try to mess with a scabbard, sheath, holster, boots, etc, I get a debug message. They still work though, and when putting stuff in it lets me choose what to put in before the message.
Said Debug Message is below on a separate line.
DEBUG: Tried to consume charges for a non-tool, non-food item
Again, they still work as far as I can tell so probably not too big a priority.

**Comment by mugling** [comment]
@Boredone relates to #15283

@BevapDin We could further relax the preconditions of `item::consume_charges` to make this also a no-op but I'm not sure if this would necessarily end there. Possibly we could look at better defining the return value of `itype::invoke` and performing more of the required logic in `item::invoke_item`?
