### ISSUE TITLE
"Slimy" mutation allows cheesing zombie AI

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15303]
Slime fields have a hidden feature where they produce smell.
Zombies' AI goes sight->smell->sound, so zombies standing on patches of slime will not react to any sound, no matter how loud.

**Comment by macrosblackd** [comment]
I would almost say this is a feature - the slime is producing an overwhelming smell that 'captivates' the zombies. Otherwise we need to parallelize the inputs and use a weighting/priority system to pick the best input to follow.

**Comment by Coolthulhu** [comment]
We could get rid of the slime smell thing. It isn't well documented.
And with it, the slime field. From what I heard, it is one of the hated traits, due to how it paints everything green.

**Comment by secretfire42** [comment]
This is a great mutation! Besides, why should a slimy ooze or a cephalopod or a slimy fish attract zombies/animals looking for human scent?

**Comment by pisskop** [comment]
If slime 'evaporated' instead of hanging around. As a field effect instead of just sitting on the ground.
