### ISSUE TITLE
Reload time depends on total ammo volume rather than stack size volume

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#15315]
With 50 ammo, reloading one round in a Ruger Redhawk takes 6 seconds on a character with 100 speed. With 1000 ammo, it takes 72 seconds. The time should logically depend on the size of each individual cartridge, rather than the total stack volume, and inversely on the amount of ammo (finding one cartridge in a mountain of them should be easy). Even if the handling cost disregards the ease of finding the item, you're not handling 1000 cartridges, you're handling one at a time.

**Comment by mugling** [comment]
> finding one cartridge in a mountain of them should be easy

I want to make handling items from vehicles work like this. Fetching a shotgun from underneath the front `seat` should be easy but finding one cartridge in hurry in your full `cargo_space` should be hard.

> Even if the handling cost disregards the ease of finding the item, you're not handling 1000 cartridges, you're handling one at a time.

This goes hand-in-hand with @BevapDin's suggestion of `item_location::obtain` only fetching the minimal amount of ammo actually required. This idea itself is waiting on merging of #15324 and refactoring of the ammo fetching code.
