### ISSUE TITLE
"Debug mod" with examples to make complex PR testing faster and as auto-doc

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15317]
With complex PRs that change the ways jsons are parsed, we have 3 options:
* Change some in-game json to show off the new features, risking the merge being delayed due to balancing
* Add a debug json to the game that is out of place in most categories
* Don't add anything to the game and just describe it in the PR

I like the second option the most, but it can't always be done.
For example, when adding a mod that specifically changes an existing in-game feature

Instead, we could have a single mod where we'd dump all the examples to show off new features before they're fully introduced to the core game.

Copying the examples from the PR description isn't much work, but a file could hold more examples than PR description, with some complex multiple-overwrite ones that would be too huge in the PR description.

Having a mod just for testing would also allow easy testing of load order (in)dependence.

Finally, it would be a whole mod of good examples on recent stuff. Whenever someone would ask "how to use new feature x", that mod would be the first place to look for examples.

As a downside, having such a mod would allow both the writer and the tester to test the exact same thing, possibly hiding some bugs due to more similar testing process on both sides.

Few examples of recent additions where such a mod would help with testing:
* BevapDin's scenario, profession and monster override changes (due to them being overrides, also examples)
* mugling's magazine and gunmod changes (balancing vs mechanics, magazine examples)
* My zed melee attack and bite changes (balancing vs mechanics, also examples)

**Comment by Malkeus** [comment]
The recent PR's allowing for custom attacks and modification of files have been awesome features, but also sources of frustration as forum and custom mods get broken. It takes a long time to track down which PR outdated something and even longer to understand the changes enough to update the content.

I'm in favor of an example mod showcasing all the new customization and override abilities you and BevapDin have given us, they are very powerful but the lack of documentation forces one to experiment to see what works as opposed to just creating content. This mod could placed in doc\sample_mods to avoid cluttering the in-game list. It wouldn't be a big deal to copy/paste it into mods for testing, and it would be easily accessible to look at actual usage of the features.

Alongside an example mod for testing purposes, some documentation for each new feature should be added to the appropriate file in docs or a new file if an existing one isn't appropriate. BevapDin's overrides could go into JSON_INFO.md with a possible mention in MODDING.txt. And the same with your attack and bite changes, they aren't just flags anymore. The balance of magazines would seem appropriate in GAME_BALANCE.md, near the ammo stats.

**Comment by Coolthulhu** [comment]
> This mod could placed in doc\sample_mods to avoid cluttering the in-game list. It wouldn't be a big deal to copy/paste it into mods for testing, and it would be easily accessible to look at actual usage of the features.

That would defeat the whole part about not having to copy/paste anything.
If it is necessary for it to be hidden, there must be a more usable solution.

> custom mods get broken

A unit test could possibly handle loading all the mods, I think. Even better if it could be automated.
On an unrelated note, Jenkins could probably handle checking if new .cpp/.h files are added to codeblocks and cmake lists too.

**Comment by kevingranade** [comment]
I think by custom he means local, which we obviously can't test against.
I think the debug mod idea is great.

**Comment by mugling** [comment]
Effectively superseded by #17398
