### ISSUE TITLE
Volume rounds up not to nearest 1, but entire volume stat

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15331]
For example: biscuit is volume 4 for 8 charges. Expected behavior:
* 1-2 charges have volume 1
* 3-4 charges have volume 2
* 5-6 charges have volume 3
* 7-8 charges have volume 4

Actual behavior:
* 1-8 charges have volume 4

**Comment by mugling** [comment]
Will fix. Perhaps we should try and enforce `stack_size` being per unit of `volume` in the JSON? It does make direct comparison of items easier and could be helpful if we later migrate to any alternative volume using higher granularity.
