### ISSUE TITLE
Autoholstering

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#15336]
Frequently suggested on the forums. Equally applicable to stashing used magazines when reloading. Has a number of problems in the details:

Consider the following scenario:

* Surrounded by multiple enemies
* Current weapon contains an empty magazine
* Two ammo pouches, one contains nothing, the other a full magazine
* Player hits `[r]` to reload

Obviously the player wants to reload using the full magazine and we would already default to this if the weapon had no magazine. The question is what to do with the spent magazine:

* Drop it (costs no moves, possibly appropriate in the above scenario)
* Stash it in the ammo pouch (relatively quick, if this magazine was rare handy if we later run away)
* Put it back in the inventory (slow, zombies continue to attack)

How about if we now only have the one ammo pouch:
* Drop it
* Back to inventory
* Implement logic to swap the spent magazine from the weapon with the loaded one in the pouch?

As always the difficulties are in the details.

I'm going to implement a menu for disposing of the empty magazine in a similar manner to the unwield prompt. This improves both keystrokes and the UI but I'm open to any **well defined** suggestions as to the above.

**Comment by Night-Pryanik** [comment]
>implement a menu for disposing of the empty magazine in a similar manner to the unwield prompt.

This.

**Comment by kevingranade** [comment]
I don't think there's a sensible automatic action that will always work, if
the player has a hulk bearing down on them, they might want to drop the
empty magazine even if it only saves them tens of move points.
Relatedly, can you annotate that menu with how many move points it will
cost (or even better, a descriptive string like "instant", "less than a
second", "a second", "a few seconds")?

**Comment by mugling** [comment]
> Relatedly, can you annotate that menu with how many move points it will cost

Yes
