### ISSUE TITLE
Atomic battery mod can not be reloaded

### ISSUE THREAD

**Issue by 3721assistant** [CleverRaven/Cataclysm-DDA#15337]
Make an atomic battery mod and attach it to anything, and you will not be able to reload plutonium cells or normal batteries into the item.

**Comment by mugling** [comment]
Having investigated this does **not** relate directly to the reloading code.

There are two problems:
1. You can attach an atomic battery to a tool that is already loaded with batteries
2. Once the mod is attached `ammo_current()` still returns the `battery` itype

There were recent changes in the addition/removal of the battery mods? That code at a minimum needs to perform a check for (1) and its possible that appropriately setting `curammo` will resolve (2).

**Comment by Coolthulhu** [comment]
Last time I checked this, the modded items could be reloaded, just not the mod itself.

Neither modded items not the mod could be unloaded. Though this makes sense as the capacity of the loaded mod is something like 200 volume of plutonium cells.

**Comment by mugling** [comment]
Currently unknown if bug still exists

**Comment by Coolthulhu** [comment]
I'm pretty sure the code for it didn't significantly change since I last checked.

**Comment by Coolthulhu** [comment]
Confirming, happens in current version. For the item to be reloadable, it must be manually reloaded before applying the battery mod.

**Comment by mugling** [comment]
Now fixed in `master` via the recent toolmod PR's
