### ISSUE TITLE
Trying to 'd'rop an item causes std::bad_alloc and crash

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15352]
Happens before the menu is drawn.
Happens both with regular drop menu and the directional one.
Dropping items with 'i'nventory->select item->'d'rop seems to be unaffected. AIM seems unaffected.
Console, Linux

**Comment by Rivet-the-Zombie** [comment]
Something specific to Linux, maybe? I can't replicate it at any rate.
SDL, Windows x64

**Comment by codemime** [comment]
I can't do it either (Tiles on Linux x64). Do you have a saved game? Maybe it occurs under certain conditions only?

**Comment by Coolthulhu** [comment]
False alarm, my build got b0rked by bad object file due to hard drive getting full. Cleaned up HD, then `make clean`, rebuilt, and now it works.
