### ISSUE TITLE
Generic Guns mod debugmsg on load

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15366]
"Magazine %s defined but not used"

**Comment by nanovad** [comment]
Yep, can confirm this on 0.C-10349. Guess it has something to do with @mugling's magazine changes?

**Comment by mugling** [comment]
I would suspect so. Unless anyone wants to tackle it sooner I'm going to try and close all the outstanding issues with the reloading code and migrate all the weapons and deal with the mod at the end.

**Comment by mugling** [comment]
This was resolved by #15666
