### ISSUE TITLE
Build error in linux under file itype.h

### ISSUE THREAD

**Issue by heema** [CleverRaven/Cataclysm-DDA#15392]
using arch linux 64

while compiling with the command
make CLANG=1 CCACHE=1 RELEASE=1 TILES=1 SOUND=1 LUA=1

gives this error:

In file included from src/bionics.cpp:20:
src/itype.h:668:17: error: 'charges_default' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    virtual int charges_default() const {
                ^
src/itype.h:579:17: note: overridden virtual function is here
    virtual int charges_default() const {
                ^
src/itype.h:699:17: error: 'charges_default' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    virtual int charges_default() const {
                ^
src/itype.h:579:17: note: overridden virtual function is here
    virtual int charges_default() const {
                ^
2 errors generated.
Makefile:573: recipe for target 'obj/tiles/bionics.o' failed
make: *** [obj/tiles/bionics.o] Error 1

![err-lin](https://cloud.githubusercontent.com/assets/287527/13033465/6dd5f8da-d31f-11e5-8950-39f8ef447af5.jpg)

**Comment by comword** [comment]
You can remove RELEASE=1

**Comment by DanmakuDan** [comment]
It looks like the 64-bit linux jenkins build has been broken by this error since the commits in 0.C-4368.

**Comment by heema** [comment]
@DanmakuDan i hope this will fix it. its compiling fine now with this fix
