### ISSUE TITLE
Bows and the atlatl report "out of ammo," regardless of quiver or inventory.

### ISSUE THREAD

**Issue by Totentag** [CleverRaven/Cataclysm-DDA#15390]
I was able to confirm this with every bow, and the atlatl. I have a [screenshot](http://i.imgur.com/UttSNWy.png) of this bug occurring with the atlatl, but didn't think to take any with the bows. Regardless, it's easy enough to confirm by wishing in any bow and arrow combination you feel like. I haven't tested this with any other weapons that might load and fire in the same action (as I can't think of any offhand) but I suspect it will occur in anything that works the same way.

**Comment by devilstars** [comment]
I can confirm this. Always says "out of ammo" even if i have arrows in quiver

**Comment by karols146** [comment]
what version do you use ? I can't replicate that with bow, all working for me. You got last dev version ? 
but atlatl don't working too, i think that someone who design that thing just think that thrown(t) would work better that normal f use. I shouldn't be difficult to change that

**Comment by AdonaiJr** [comment]
I just installed a fully latest fresh install, and the problem persists.

**Comment by OldSedan** [comment]
Same bug also affects the sling and slingshot. I'm getting it with those and bows as of 4403.

**Comment by mugling** [comment]
Can reproduce in `master`, affects all `RELOAD_AND_SHOOT` items
