### ISSUE TITLE
Crash when burst firing flamethrower and running out of gas mid-burst

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15405]
Seems to only affect RM451.
* Load RM451 with gas
* Use up ammo until the charge count is less than 100 but more than 20
* Burst fire at a target that will survive the entire burst (say, a Debug Monster)

**Comment by mugling** [comment]
I'm going to try and reproduce but if you have one a stacktrace would be very helpful

**Comment by Coolthulhu** [comment]
Didn't get a stacktrace, but I think I can see at least one way it can crash:

In `ranged.cpp` at line 398:
```
if( !handle_gun_damage( *gun.type, gun.ammo_data()->ammo->ammo_effects ) ) {
```

`gun.ammo_data()` is `nullptr` when the gun has no ammo set. This will result in `nullptr` deference.

Additionally, `item::ammo_remaining()` does not understand "FIRE_[number]" flags, so the line
```
shots = std::min( shots, int( gun.ammo_remaining() ) );
```

Will not limit the shots properly.

**Comment by mugling** [comment]
> handle_gun_damage

This is due for refactoring when we add jams so I'll address that then

> item::ammo_remaining() does not understand "FIRE_[number]" flags, so the line

Will look into
