### ISSUE TITLE
Morale drops off quicker than expected

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15408]
Morale predictably stays constant until it reaches its decay point. At this point it starts dropping off really quickly. For example, morale bonus from 10 fun food will stay 10 until 30 minutes pass, then drop to 0 within 10 minutes, despite having an actual timeout at 60 minutes.

The line at fault is most likely:
```
bonus *= logarithmic_range( decay_start, duration, age );
```

Rather than the expected usage of `logarithmic_range` which would be:
```
bonus = base_bonus * logarithmic_range( decay_start, duration, age );
```

**Comment by codemime** [comment]
Will be fixed in a forthcoming PR.
