### ISSUE TITLE
Magazine trouble

### ISSUE THREAD

**Issue by codemastergh** [CleverRaven/Cataclysm-DDA#15402]
I have an empty Glock in my hand and a full 30/30 extended Glock mag in my inventory and reloading it does not work but the Sten I have works with the magazine.

**Comment by mugling** [comment]
What are the **exact** sequence of steps

**Comment by mugling** [comment]
And which build? Any mods?

**Comment by codemastergh** [comment]
Found out it was a mod I was using and fixed it.

**Comment by mugling** [comment]
Which mod?

**Comment by mugling** [comment]
Needs closing
