### ISSUE TITLE
Get rid of blowgun

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15403]
Blowgun doesn't make sense:
* Uses and trains archery, but is totally unlike bow or crossbow
* Only useful for training, at which it is unreasonably good due to low dispersion of the blowgun and very low dispersion of the darts
* Made from a piece of wood and glue and the darts are made just from pure wood. This means it is easy to get in the city (harder in the wilderness) and nearly free to use
* Suffers from momentum drop, meaning the darts fall to the ground rather quickly
* You can use it with a gas mask on with no reduction in anything
* Even if it poisoned enemies on wounding, it would most likely be nearly useless in vast majority of cases. It could only be useful against non-brute shockers in the middle of the night, due to their thin skin and dangerous attacks

**Comment by Rivet-the-Zombie** [comment]
Those are all good points.

Maybe it's supposed to be for hunting small game?

**Comment by kevingranade** [comment]
Irl the only things they're good for is small game hunting and perhaps
poison delivery.

**Comment by Mecares** [comment]
Could be useful for not existing quests that demand to anesthetize some kind of creature and bring it to some Scientist/Doctor for research purposes.
But yes in the current game it seems rather pointless.

**Comment by tyrael93** [comment]
No matter what, if it doesn't get removed it's always going to be a training stick that makes you a better archer and marksman than any other kind of gun or bow, for free.
But hey, breathing practice is critically important when shooting, right?

**Comment by kevingranade** [comment]
It's niche enough to not practice a specific skill at all, then it would
only practice generic marksmanship.  Also just give it some dispersion,
they're not remotely that accurate IRL.

**Comment by Zireael07** [comment]
I believe blowgun shouldn't train archery, just markmanship. And I'm against removing them wholesale. 

*starts thinking of poisoned darts recipes*

**Comment by Defraggler** [comment]
How could one prevent blowgun use when mouth is encumbered?
Should the dart, the gun, or both get more dispersion?

**Comment by kevingranade** [comment]
The blowgun would need a flag like "breath activated", and the firing code in ranged.cpp would need to check for that flag and then check for mouth encumbrance if it's present.
Probably both should get more dispersion, blowgun darts aren't particularly finely stabilized (usually just a flag or other small piece that adds drag to the back, in addition to acting as a wad for air pressure to push against in the tube), and blowgun tubes don't have the tolerances that most ranged weapons have, or a design that makes the tolerances moot, like a bow.

**Comment by WizardOfOoo** [comment]
Do we want PCs with beaks and other misshapen mouths to be able to use blowguns?

**Comment by kevingranade** [comment]
Leaning toward no, but not strongly, it's somewhat reasonable that they could make a seal with their tounge or something.
