### ISSUE TITLE
Allow selecting first magazine/ammo with fire/reload button

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15406]
Current behavior:
* Press fire or reload with more than one magazine/ammo type available
* Menu appears
* Pressing same button cancels the menu, have to confirm with enter

Suggested:
* Press fire or reload
* Menu appears
* Confirm the default selection with fire or reload, checking the in-game binding, similar to how you can confirm vehicle repair with 'r'

For example, when using a sling with marbles and bearings, pressing 'f' thrice would first go into targeting mode, then confirm target and open ammo menu, then confirm the ammo type.

**Comment by mugling** [comment]
Sounds good. I'm also going to make the changes discussed in #15383 so that reloading using magazines always shows the menu whereas `RELOAD_ONE` skips it if there is only one choice
