### ISSUE TITLE
Adrenaline injector causes constant asthma for 200+ rounds

### ISSUE THREAD

**Issue by mightyagrippa** [CleverRaven/Cataclysm-DDA#15416]
Adrenaline injector says in description that it's an emergency cure for an asthma attack. But after using one a player goes into an insane constant asthma spiral for hundreds of turns. Testing in build 4410, one adrenaline injection resulted in asthma attacks that ate through 2 full inhalers and killed the player.

I think what's happening is that adrenaline_injector from iuse.cpp is giving the player the adrenaline effect, then checking for the adrenaline effect and finding it with a resulting +80 stim boost, then fixing the asthma attack. There's a 1 in (3600 - 50*stim) chance of future asthma attacks, so perma-asthma until stim goes below 72.

adrenaline_injector should probably apply effect_adrenaline after checking for it. Or if the +80 stim on first injection is intended, the asthma check should be rescaled so a real-world treatment isn't an in-game death sentence.

**Comment by sethsimon** [comment]
I tested this on a new character in version 4555 and got the same result- between dusk and dawn I used up 2.5 inhalers.

The conversation in [PR 2441](https://github.com/CleverRaven/Cataclysm-DDA/pull/2441) makes it clear that the stimulant effect was intended to only be applied on subsequent uses. 

The old (relevant) code looked like this:
`if(p->has_disease("adrenaline")) {`
`     //Increase current surge by 3 minutes (if not on comedown)`
`     p->add_disease("adrenaline", 30);`
`     //Also massively boost stimulant level, risking death on an extended chain`
`     p->stim += 80;`
`} else `
`     //No current adrenaline surge: Give the full duration`
`     p->add_disease("adrenaline", 200);`
`}`

The logic in adrenaline_injector changed in [this commit](https://github.com/CleverRaven/Cataclysm-DDA/commit/fb22f11e00b5a0663292d1f5fe5b3d4ec2a9632e), which implements [this pull request](https://github.com/CleverRaven/Cataclysm-DDA/pull/9469). The purpose of that PR was not to change the logic of adrenaline_injector, but to overhaul to a new, JSON'ized effect/disease system. After the commit, the relevant code became:
`p->add_effect("adrenaline", 200);`
`if (p->has_disease("adrenaline")) {`
`//Massively boost stimulant level, risking death on an extended chain`
`p->stim += 80;`
`}`

Therefore, the logic (probably including the 3-minute extension on subsequent uses) should probably be reverted to the original.

**Comment by Coolthulhu** [comment]
Or we could make it not grant any stim and instead handle the overdose in some other way.

For example, datura is hardcoded to instakill based on duration.

This would have another great positive effect of preventing using adrenaline to boost intelligence, which doesn't make much sense.

**Comment by sethsimon** [comment]
Handling adrenaline overdoses the same way as datura sounds like a good idea. Not only would it prevent the unrealistic intelligence effects, but also, as it currently stands, it's not possible to overdose on the adrenaline CBM, but it probably should be.
