### ISSUE TITLE
Magazine_converted variable being applied indiscriminately

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#15425]
The variable is being applied to non-firearms. It is also being applied to currently unconverted firearms, meaning they will become useless once they are converted unless the player immediately finds a magazine.

**Comment by mugling** [comment]
I'm not quite sure what you mean. Can you give me an example?

**Comment by ejseto** [comment]
Just started a new game in a gun shop. Picked up an SKS, which has the magazine_converted variable, even though it is still a magazine_internal() weapon. If it is ever converted, it'll be useless until I find a magazine. I thought the intention behind the conversion was that any weapon which was previously usable should remain so. Thus, it makes sense to apply the flag to newly-spawned weapons that have already been converted since they are not usable anyway, but not to weapons that have an internal magazine which may be converted to external magazines in the future.

Started another game in a pawn shop. The cutlass I picked up has the magazine_converted variable, despite not being a firearm. So does the extinguisher, the vacuum sealer, the firefighter PBA mask, the zweihander, etc. Each of these items now has several extra bytes of useless information being saved. Multiply that by potentially thousands or tens of thousands...

**Comment by mugling** [comment]
> Picked up an SKS, which has the magazine_converted variable, even though it is still a magazine_internal() weapon. If it is ever converted, it'll be useless until I find a magazine

Good point. I'll look into that.

> The cutlass I picked up has the magazine_converted variable, despite not being a firearm

The long term plan is to extend magazine support to include tools.

> Multiply that by potentially thousands or tens of thousands...

10'000 items at 20 bytes is ~195kB and that's presuming no compression by either the game(?), OS or in some cases the underlying storage.

**Comment by ejseto** [comment]
Might not sound like much, but it's a slippery slope that leads to things like Windows 10.

**Comment by mugling** [comment]
*"We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil."*
