### ISSUE TITLE
Low intelligence nerf: disable book leveling below int threshold

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15421]
Currently intelligence is of very low importance: everything a genius can do, an idiot can do to, just that an idiot will take more time and/or attempts.

Having books strictly require some intelligence to use for levelling would help making that stat meaningful. Low intelligence characters could still learn, but they'd learn by doing rather than by reading.

Also, low intelligence could disable book learning. Same as a above: to learn recipe from a book, a low intelligence character would need to craft said thing, once again to learn by doing.

To prevent it from fluctuating too much, intelligence used here could be the maximum one instead of current one (to avoid having meth "unlock" books).

The restriction could be more fluid: having 1-2 intelligence points could radically slow down levelling, but not prevent it. Having 2 points above requirement could lower skill requirements by one.

**Comment by Rivet-the-Zombie** [comment]
>having 1-2 intelligence points could radically slow down levelling, but not prevent it.

I like this better, at least until we have some means of improving one's abilities outside of mutations/CBMs.

**Comment by mugling** [comment]
The lower bound can be easily implemented via `player::can_use`

**Comment by kevingranade** [comment]
On Feb 15, 2016 1:43 PM, "Angela Graves" <notifications@github.com> wrote:
>>
>> having 1-2 intelligence points could radically slow down levelling, but
not prevent it.
>
> I like this better, at least until we have some means of improving one's
abilities outside of mutations/CBMs.

Why? If you don't want the effect, don't take a very low int score.

**Comment by Rivet-the-Zombie** [comment]
Even complete morons are still capable of learning stuff. I don't like the idea of an implementation that completely bars some characters from being able to benefit from reading a book because their intelligence stat is a point lower than the book demands. I could totally dig it if it slows them down a whole bunch, but unless they've taken the illiterate trait, I don't think we should lock them out of any books entirely.

**Comment by Coolthulhu** [comment]
> I could totally dig it if it slows them down a whole bunch, but unless they've taken the illiterate trait, I don't think we should lock them out of any books entirely.

We already do that. The result is that anything a genius can learn, a moron can too, just with more time. No one needs to learn by doing.

If hard caps are out, I'd suggest something halfway there ("al-dente cap"?):  
For every point/2 points of lacking intelligence, the maximum skill level available from the book is lowered by 1.

**Comment by mugling** [comment]
How about hard cap at a very low level and increasing success after this?

> For every point/2 points of lacking intelligence, the maximum skill level available from the book is lowered by 1.

Although this is also an interesting proposal

**Comment by Rivet-the-Zombie** [comment]
>For every point/2 points of lacking intelligence, the maximum skill level available from the book is lowered by 1.

This is a neat idea. It makes low INT properly suck, but doesn't completely cripple dumb characters.

**Comment by ZhilkinSerg** [comment]
http://smf.cataclysmdda.com/index.php?topic=14935.0
