### ISSUE TITLE
New items not stacking with old items

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#15423]
Items are now spawning with an explicit charges field, even for non-count-by-charges items, i.e. charges = 0 or 1 always, causing them to not stack with items from saves before the change. Furthermore, this redundant (as far as I can tell) info is being saved, causing save file bloat.

Certain items spawning with 0 charges, e.g. etched human skull, sell for 0 to NPCs as well.

**Comment by mugling** [comment]
Probably #15374. We can either migrate all the old items to `charges == 0` or more correctly fix the stacking code?
