### ISSUE TITLE
[4422] Flint and steel non-functional

### ISSUE THREAD

**Issue by zj44** [CleverRaven/Cataclysm-DDA#15438]
Trying to use a flint and steel on 4422 (0.C-10917-gff691e8). Might be an item from More Survival Tools, was working a before I updated (4393).

EDIT: Was functional on build 4393. Bug appears at MINIMUM build 4399 (could not access earlier versions). This bug appeared at least three days ago as of writing (I've been playing with an older version until updating today.)

Expected: Asked where to light a fire.
Actual: Nothing happens.

**Comment by chaosvolt** [comment]
An item from More Survival Tools, yes. Have you tested whether fire drills and magnifying glasses work? They should use the same function (though magnifying glasses require sunny weather).

**Comment by zj44** [comment]
@chaosvolt Fire drill and magnifying glass work fine

**Comment by chaosvolt** [comment]
Aw crap.

**Comment by zj44** [comment]
@chaosvolt This seems to be spanning multiple versions -- the last good version I have downloaded at this time is 4393 and the bug appears at minimum 4403. I'm trying versions between them to see where exactly it stops working.

**Comment by chaosvolt** [comment]
I'm not sure what the likely cause is, especially if the magnifying glass is working. It's possible that the extended_firestarter use_action was broken such that it now requires the presence of the lens or fire_drill flags.

**Comment by Malkeus** [comment]
I agree, you beat me to it by 2 minutes. That seems to be the only difference between the 3 tools, the 2 that work have related flags, the broken one has none. is extended_firestarter even implemented anymore?

**Comment by chaosvolt** [comment]
It should be, since fire drills and lenses use it. I'll look into it. I could PR a fix, but I'm unsure if it would be acceptable to do so.

**Comment by Malkeus** [comment]
You know who to discuss that with. It would be prudent to deal with that issue before submitting a PR.

**Comment by zj44** [comment]
I had a hunch and it turned out to be right -- flint and steel is functional if you add charges to it. I think this bug **might** have something to do with #15374

**Comment by chaosvolt** [comment]
I likely will have to, yes.

In any case, it seems that just adding "FIRE_DRILL" isn't enough. So yeah, it needs charges.

**Comment by Malkeus** [comment]
It could be modified to have a fairly large number of charges. Flint and steel will last a really long time IRL, but not forever.

**Comment by Malkeus** [comment]
what seems like a good amount, 1000?

**Comment by chaosvolt** [comment]
That was something I'd originally considered back when I was adding it. 1000 might work, being the amount camp fire drills have. Or even twice that. Would also nerf them via making the player need to recraft it eventually.

**Comment by Malkeus** [comment]
I can submit a PR for this one, I updated my repository the other day, should still be current enough to merge. So 2000 charges, 1 charge per use?

**Comment by chaosvolt** [comment]
Seems acceptable, yes. Thank you.

**Comment by Malkeus** [comment]
No worries :D

**Comment by chaosvolt** [comment]
Yeah. While it seems I have been allowed to comment on things as of late, I would consider it too soon to press the issue of contributing again. I feel like even discussing it like this seems a bit rude of me.

**Comment by Malkeus** [comment]
Could be. Not talking about it won't help any either. Maybe a more private forum would be appropriate?

**Comment by chaosvolt** [comment]
Likely, but I'm not sure that PMing Kevin about it would be a good idea.

**Comment by Malkeus** [comment]
Fair enough.
On the PR:turns per charge. I'm not clear on how taht interacts with extended_firestarter.

**Comment by Malkeus** [comment]
i'm not sure what it even does tbh...

**Comment by chaosvolt** [comment]
I don't think turns per charge does anything with items that aren't considered active, like flashlights.

**Comment by Malkeus** [comment]
Oh ok. yeah flashlight has a value there. ok makes sense, i'll leave it as is.

**Comment by Malkeus** [comment]
All done, thanks for the help chaosvolt.

**Comment by NickGrease** [comment]
Just a suggestion, since a lot of PRs lately seem to be pushing for more realistic mechanics, maybe the number of charges used on F'n'S could be random between say 1-8, and use survival skill to push it closer to 1. I imagine someone who has no idea how to start a fire, using F'n'S on whole logs and 2x4's, where someone with more knowledge prepares a tinder bed to accept the spark.

**Comment by chaosvolt** [comment]
Extended firestarters already have a duration affected by survival skill, it's just that the amount of charges used is...if I recall, still fixed.
