### ISSUE TITLE
[Website] "Support Cataclysm" button not functional

### ISSUE THREAD

**Issue by sctjkc01** [CleverRaven/Cataclysm-DDA#15442]
Clicking the golden "Support Cataclysm" button takes the user to a page that does not exist: http://en.cataclysmdda.com/pages/17/display

**Comment by Night-Pryanik** [comment]
This link is no longer exists.

**Comment by sctjkc01** [comment]
Considering a cursory look didn't display the original golden link (and I couldn't remember where the link was originally - over a year since this issue was posted!) I'm inclined to agree.
