### ISSUE TITLE
Vending machines give tons of loot once broken.

### ISSUE THREAD

**Issue by martin509** [CleverRaven/Cataclysm-DDA#15458]
Currently, vending machines hold absolutely ridiculous amounts of food/drink when broken into. It's not uncommon for there to be a few days of food in there, if you only eat the meat jerky and pork sticks. As for drink I've observed 20+ bottles of water in one vending machine along with everything else. Breaking a vending machine guarantees a supply of either food or water for many days ahead.

Possible fixes:
- Greatly reducing the number of spawns in a vending machine. This kind of negates the purpose of those unbroken machines as places where you can buy stuff via cash card from them if there isn't very much to buy in the first place. On the other hand it wouldn't hurt to half the number of spawns inside a vending machine.
- Making them harder to break into. I don't find this plausible, as it's tempered glass, not reinforced steel. But it's a game, and I'm fine with breaking into a vendor needing tools of some sort (welder, drill, circular saw, anything really) and take some time. 
- Making them straight-up unbreakable, like ATMs. I'm fine with this as well, though it doesn't make a whole ton of sense if there are broken vending machines along with unbreakable ones.
- Reducing the spawn rate of intact vending machines. Broken vending machines have far less loot, but personally I like the idea of some vendors being scattered about and having plenty of food/water if you have the money.
- Making the punishment for breaking them and sounding the alarm far harsher. Right now, if you smash a vending machine, it sounds an alarm for 1 turn and that's it. It might cause a problem during a night raid in a city, but way out on the highways at gas stations, it's pretty much safe to break them open. I suggest making the alarm sound continuously for a long while (enough to attract a significant number of zombies if horde spawns are on) or perhaps spawn a police-bot, really anything to punish breaking a vendor open. In my opinion, this is the most mechanically interesting option for the early-game when the player most needs food and water: Having to choose between buying food with a cash card obtained by killing zombies, or dealing with cop-bots is a cool choice.

Either way, I feel like vending machines are far too cheap a way to get effectively unlimited food and water early on.

**Comment by Malkeus** [comment]
I like bith the extended alarm and copbot spawning ideas, it ipens up some
interesting tactics as well. Running from a hirde? Smash a vending machine
to bring down a distraction. Make them tougher so it isnt aquick job
either, that would inhect some tension into the situation.

P.s. sorry fir the rypos, my swype keyboard has quit wirking and i have
ogre sized thumbs...

**Comment by Rivet-the-Zombie** [comment]
>P.s. sorry fir the rypos, my swype keyboard has quit wirking and i have ogre sized thumbs...

Shhhhh... it's all ogre now.

**Comment by Malkeus** [comment]
Do I detect a fellow dvz player? :)

**Comment by Rivet-the-Zombie** [comment]
I'm going to go with 'no' because I don't know what 'dvz' is?

**Comment by Malkeus** [comment]
Fair enough. Where's that quote from if you don't mind my asking? I thought
it was just something the kids said in dwarves vs zombies to drive me crazy
during doom events ☺

**Comment by Rivet-the-Zombie** [comment]
>Where's that quote from if you don't mind my asking?

A really depraved copypasta that's been slithering around the internet for a few years now. I think I originally came across it on 4chan.

**Comment by Zireael07** [comment]
+1 to extended alarm + harsher penalties.

**Comment by Malkeus** [comment]
Google seems to be pointing the finger at Shrek, with a side of 4chan. I should have known. Also, should have known better than to do a search that involved 4chan in any way on a public library computer...good thing nobody saw.

**Comment by kevingranade** [comment]
One possibility is having vending machines break some of their contents
when they're broken.

**Comment by Mshock777** [comment]
Even using 0.4 item spawn scale I still get amount of food that isn't natural for vending machines irl.
I'm for decreasing amount of items 5 times or more.

**Comment by Rivet-the-Zombie** [comment]
>get amount of food that isn't natural for vending machines irl

I've not found it to be that bad, I just think the risk is too low for the reward.

**Comment by etmoonshade** [comment]
My suggestions for this would be to:
A: Have them require a tool to get open (e.g. crowbar, probably via disassembly.) If you just smash them, you mangle some of the contents. I've always found it odd that I can disassemble a fridge, but not a vending machine.
B: Have some (more?) of them start broken - possibly based on time if possible. Surely you're not the only survivor to notice all the tasty tasty junk food in those.
C: Maybe have a random chance of it falling over on you if you try to smash it. ;)

I've found the amount of loot in them realistic - a soda machine IRL can easily hold 20+ cans per column (times 8 columns) from what I remember seeing, and IRL snack vending machines hold (potentially) hundreds of items.

**Comment by John-Candlebury** [comment]
I  do think that the pristine vending machines have about the right amount of stuff in them.

They pristine ones could stand to be rarer though, could probably be relegated to places that were quickly overrun by zombies or that are really out the way.

**Comment by MystiaLorelei** [comment]
Correct me if I'm wrong, but didn't breaking a vending machine use to spawn an eyebot? Then said eyebot would then beeline for you and snap a picture, which would then bring riot bots down upon you, which which also attract zombies via sirens and what not.

I think this changed when the bots and zeds were changed to infight. Maybe bring back that behavior? It was a loot piñata alright, but one you had to loot quickly and get out of dodge before you got swarmed.

I wouldn't mind some kind of tool interaction to crack one open with less a chance for the alarm to go off in exchange for it taking awhile, as well as pre-looted variants for the flavor if nothing else.

**Comment by SeanMirrsen** [comment]
I think that vending machines, intact vending machines, should be left as they are. They are realistic, in durability and contents, though the contents should perhaps be more randomized in quantity. What I think could change, is their rarity. Finding a vending machine full of provisions should be an incredible windfall - most machines would have been broken and raided by panicking civilians searching for food, or by shambling hordes chasing said civilians (and most items would have been torn open/trampled over by said hordes, or scavenged by vermin or survivors).

So make the broken vending machines have little usable loot, and have intact vending machines have only a small chance of appearing, and I think it'll be fine.

As far as risk, most vending machines I've seen were in places where there is a large amount of roaming zombies (megastores, etc), so the risk is already there, it's emergent. It's on par with finding someone's basement full of guns.
