### ISSUE TITLE
Ambush scenario not spawning zombies

### ISSUE THREAD

**Issue by martin509** [CleverRaven/Cataclysm-DDA#15454]
The 'ambush' scenario does not spawn zombies outside of the cabin anymore.

**Comment by karols146** [comment]
I think that you need set in options "Surrounded start" to get this scenario to work. You got this on "True" ?

**Comment by player0981234** [comment]
this scenario is so buggy :/

**Comment by kevingranade** [comment]
Doesn't spawn zombies outside cabin even if world options have surrounded start set.

**Comment by Coolthulhu** [comment]
It's not a bug per se, but rather unimplemented feature.

Surrounded start was never implemented for anything other than evac center.

**Comment by kevingranade** [comment]
A number of scenarios say it works though, either the implementation or
documentation needs changing.
