### ISSUE TITLE
Assigning inventory letter to multiple items in a stack doesn't work (feat. reloading)

### ISSUE THREAD

**Issue by martin509** [CleverRaven/Cataclysm-DDA#15455]
Say I have 3 STANAG mags in my inventory, all loaded with the same ammo, and all thus assigned the same letter. When I go to reload them, the menu comes up with 3 options, one for each mag, and all assigned the same letter for selecting them. Selecting a mag with the arrow keys and pressing 'enter' works fine, but selecting them by pressing the letter crashes the game, probably because I technically just selected all 3 magazines at once.

**Comment by mugling** [comment]
Crash is fixed by #15465 and is unrelated to invlets.

Ability to assign `invlet` to multiple items is a wider issue so @martin509 please consider renaming your issue accordingly and leaving it open for further review?

**Comment by Night-Pryanik** [comment]
Tested on 0.E.-2149. Can't confirm, I was able to successfully assign an invlet to and successfully reload magazines.
