### ISSUE TITLE
NPCs attempt to fire '0 or negative' shots from ranged weapons

### ISSUE THREAD

**Issue by martin509** [CleverRaven/Cataclysm-DDA#15456]
Whenever an armed NPC tries to shoot a gun, the game gives an error regarding to the fact that you cannot fire 0 or negative shots from a weapon.

**Comment by Malkeus** [comment]
A PR was merged last night to fix this, what version are you using? I didnt
get this error on 4425. Instead i get a debug message about attempting to
reload, which ill put up an issue for when im on a pc

**Comment by martin509** [comment]
My apologies, it seems development moves faster than I can record a bug. I will update my version, if only there were a way to have the game stay automatically updated.

**Comment by Malkeus** [comment]
Automatic would be nifty, but until then, there's remyroys launcher to make
updates easy. Look for it at the top of the mod list in the Lab on the
forums.

**Comment by martin509** [comment]
Thank you, will look into that.

**Comment by Rasip** [comment]
I did get this error on 4438.
