### ISSUE TITLE
Guns in vehicles don't come with magazines.

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#15461]
Since there is no reasonable explanation why they shouldn't and I haven't seen it being discussed...
pls don't forget about it (<3 @mugling).
P.S. Guns in vehicle should probably spawn loaded (with extra loaded mags?)
P.P.S. Since we are in New England, maybe we should add a small chance of maybe... a handgun spawning in civilian car?
P.P.P.S. Guns that drop from zombies should also come with mags (fully loaded?) 99% of the time.

**Comment by Karbine** [comment]
Loaded guns in vehicles could go either way. Some people transport guns unloaded for legal reasons (no permit for the state they're passing through, no CHP but headed to the range). 

Based on a quick search the states in New England that track active permits add up to a ballpark of around 500,000 permits for 14.7m citizens. If we factor in Vermont we could probably call it safe to say at least 4% of New Englanders carry handguns sometimes if not regularly. Based on what I remember of the lore it sounds like the pre-Cataclysm US was a pretty gun-happy place though, so rates could be higher than they are today.

Zombies with firearms could have fired some or all of their rounds before succumbing to whatever killed them. I think having drop rates with an even spread of weapons between 0-100% capacity would make the most sense, with a full load being somewhat less likely.

**Comment by Mshock777** [comment]
Also I think guns in mansions spawn without mags.

**Comment by mugling** [comment]
> Also I think guns in mansions spawn without mags.

This was resolved by #15663 

Vehicle spawns remains an outstanding issue and needs code changes to support it
