### ISSUE TITLE
Opening trade window with NPC deletes inventory item hotkeys

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#15478]
Items not in inventory but which have assigned hotkeys appear to be safe from this, as do worn items.

Edit: Caused by accepting trade, even with no items traded. Pressing ESC preserves hotkeys. Dropping and picking up affected items also restores the hotkeys.

**Comment by BevapDin** [comment]
This was actually fixed by #15587. That PR linked (incorrectly) to #15435, which was fixed #15588. Both issues were fixed.
