### ISSUE TITLE
Eye glasses cannot start a fire.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#15484]
In the description of eye glasses it states that you can focus the sunlight to make fire similar to binoculars but when you activate them it states your can't do anything interesting with them.

While I am at the topic, shouldn't biofocal glasses also allow fire starting since they can focus light the same way eyeglasses?

**Comment by Malkeus** [comment]
It seems the "LENS" flag alone is no longer enough to start a fire, it needs extended_firestarter defined as a use action. I'll PR a fix for Eye Glasses, Bifocal Glasses and Reading Glasses, with updates to the descriptions.  Are there any other items that need this fix that you are aware of?

I tested the fixes in game already, they are all working the same as the magnifying glass now:
https://i.imgur.com/g46YPQj.png

**Comment by Noctifer-de-Mortem** [comment]
Tested binoculars,survivor telescope and magnifying glass and they all work.

**Comment by Malkeus** [comment]
generic lens and monocle have the correct code as well. I'll get that PR up in a moment.

**Comment by Malkeus** [comment]
herp derp...i just sent my own repositories master branch a pull request from a branch in my own repository...

**Comment by Malkeus** [comment]
There. That took 10x longer than testing the fix did...damn my fumble fingers.
