### ISSUE TITLE
Oil lamp refuses to be loaded.

### ISSUE THREAD

**Issue by Rasip** [CleverRaven/Cataclysm-DDA#15494]
Experimental 0.c-10999-g9015d70

I made an oil lamp and a gallon of lamp oil. when i try to reload the lamp it gives the "Out of lamp oil!" error message. I'm holding the lamp and the jug of lamp oil.
I have tried save/quitting and restarting Cataclysm and moving the oil to different containers.

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/139138/save.zip)

**Comment by karols146** [comment]
0.C-10999-g9015d70 - Can't replicate all working. 
You use titles or something like that ? I just have pure ASCII and everything work.

**Comment by Rasip** [comment]
Just tried in askii, same result. Did you use my save file for testing? 
Also, shortly before i made the lamp there was an error message saying something about an NPC not being able to reload with no ammo.

**Comment by Night-Pryanik** [comment]
Can't reproduce on win 10, tiles, 0.C-4442.

**Comment by ejseto** [comment]
Can reproduce. Crafting produces an oil lamp that has curammo set to lamp_oil but with 0 charges. Debug wished lamps also have curammo set to lamp_oil but come with 800 charges. If you unload the wished lamp, it has 0 charges but also does not have curammo set.

**Comment by karols146** [comment]
`  "components": [
    [
      [ "tallow", 2 ],
      [ "tallow_tainted", 2 ],
      [ "lard", 2 ],
      [ "cooking_oil", 5 ]`
If we look at components, we should have lamp with full ammo after crafting.

**Comment by ejseto** [comment]
Those aren't in the recipe...

**Comment by karols146** [comment]
Ok my bad, I have no idea where I find this, 
So if I find it right there is scrap and rag only?
