### ISSUE TITLE
The addition of three new "future drugs"

### ISSUE THREAD

**Issue by GlyphGryph** [CleverRaven/Cataclysm-DDA#1549]
Hype - A major stimulant boost combined with hallucinatory effects, but very short lived. Fairly addictive, lowers Int, has a lingering effect similar to being drunk but without the boosts.

Lox - This drug knocks you out, putting you to "sleep", but moves you to a pitch black area full of nothing but hallucinations that you can walk around in for half an hour. Lots of different colours may appear. Depending on the type of trip you roll, they can be generally good and result in a huge morale boost, or generally bad and result in a huge drop, open your mind (temp int boost) or give your character a mental problem. There may be more to this strange dream realm than meets the eye, and using Lox next a portal, well... Character recovers completely shortly after the trip is completed.

Kine - This drug boost your sense of smell by an incredibly amount for a short period of time, by hooking it into the brains visual circuits. Literally lets you see smells. Not addictive. (Uses scent bionic rules) Has a comedown of mild pain (headache), overdose is extreme headache and loss of sight for several hours.

**Comment by kevingranade** [comment]
TODO for a specific developer who is no longer around, no reason to keep it.
