### ISSUE TITLE
NPC can't reload - so his brain explodes

### ISSUE THREAD

**Issue by mouseturd** [CleverRaven/Cataclysm-DDA#15508]
Running latest experimental 4374.
Issue happens a lot when I'm at the refugee center and a zombie gets inside.
NPC wielding a ranged weapon will attempt to fire at the zombie, but can't reload.
The following message appears:DEBUG: NPC_REload Failed: No usable ammo
The NPC's brain then explodes.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/139782/save.zip)
![explosion](https://cloud.githubusercontent.com/assets/17355888/13204465/94d99c50-d89e-11e5-9dc5-24cc8251925a.jpg)

**Comment by pisskop** [comment]
This happens.  A hostile NPC tried to reload a crossbow and kaput.  And even static NPCs

**Comment by mouseturd** [comment]
So it was inevitable?

**Comment by martin509** [comment]
Can confirm as of latest-lastest experimental that actually compiles. Happens for any weapon that needs reloading, pretty much.

**Comment by nanovad** [comment]
I think this may be a side effect of mugling's magazine changes. I haven't looked at the code, but the NPC might be looking for ammo that exists in inventory, but requires a magazine to use.

**Comment by dbackeus** [comment]
+1

**Comment by jcd000** [comment]
Hmm, so if this was fixed, what caused this: http://smf.cataclysmdda.com/index.php?topic=19.msg273174#msg273174

?

**Comment by nanovad** [comment]
I think an NPC's brain exploding just signifies there was an issue that
couldn't be resolved.
