### ISSUE TITLE
Tiles mode zoom functions aren't exact inverses

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#15504]
Zooming in multiplies tileset_zoom by 1.5. Zooming out divides it by 1.5. But the variable is an int, so those operations result in truncation. Also, the function names are the opposite of what they actually do.

Furthermore, it is possible to zoom in to arbitrarily large values; game::zoom_out() (actually this zooms in) appears to have been intended to max out at a zoom level of 64, however since the function checks for tileset_zoom == 64 and not tileset_zoom >= 64, it's possible to increase zoom level beyond that by zooming in and out, causing truncation of the zoom level. For example, if you zoom in to zoom level 64 (by zooming out until it resets) and then zoom out and zoom in, truncation will cause the zoom level to be 63. From this point, you can zoom in as much as you wish.

This probably wasn't intended (since there is a check, albeit incorrect, for maximum zoom level) and can be confusing if a player keeps zooming in wondering why it won't reset.

**Comment by hitbutton** [comment]
Where are you seeing the 1.5 multiplier? The zoom_in() and zoom_out() functions in game.cpp divide/multiply the zoom level by 2. That shouldn't cause any truncation issues with ( default / min / max ) zoom levels of ( 16 / 4 / 64 )

You do seem to be correct that the functions are reversed though.

**Comment by ejseto** [comment]
Hmm, never mind, I think I changed that in my local fork a long time ago and forgot. My b.
