### ISSUE TITLE
Jenkins is having Out of Memory Issues

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#15505]
Build 4449 and 4450 failed for all builds except 32bit linux: tiles and curses. http://ci.narc.ro/job/Cataclysm-Matrix/4450/console

> src/inventory.cpp:1212:1: fatal error: error writing to /tmp/ccS7HlDn.s: No space left on device

I'm sure @narc0tiq has received an email about this by now, this is just a heads up for all devs building from source who may not be aware the last few merges haven't reached most of the public yet.

**Comment by Malkeus** [comment]
Crisis over with nary a peep...

**Comment by chaosvolt** [comment]
Yay?

**Comment by Malkeus** [comment]
Yay confirmed ;)
