### ISSUE TITLE
guns does not accept loaded magazine

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#15502]
tested with TDI vector m4a1 and AK all didnt work works fine with empty magazines

**Comment by ejseto** [comment]
Can't reproduce. Fresh pull/compile, new character, wish m4a1, 2x stanag, 5.56 ammo, reload one mag, wield m4a1, reload weapon. Works for both loaded mag and unloaded.

Are you playing on the most current experimental? If not, which build number? Exact steps to reproduce? Can you upload your save?

**Comment by player0981234** [comment]
I'm playing on the latest experimental
the steps are exactly the same as yours except i'm using the tiles version on jenkins

**Comment by Moonsabrt** [comment]
.....Are you using the right magazine?

**Comment by player0981234** [comment]
Yes i can load an empty one

**Comment by articulateSPLINE** [comment]
I think this might be an issue with trying to use a save from a previous version. I dropped my relatively ancient save from  0.C-4407 into -4445 and suddenly my firearms would only accept empty magazines. I had a loaded AK74 in my vehicle, so I tried unloading and reloading it only to get the same "Your AK74 cannot be reloaded!" message.

I'm willing to upload my save, but it's a bit large at ~400MB.

**Comment by player0981234** [comment]
probably not cuz this bug exists on new worlds 
do have a save from 4398 though

**Comment by mugling** [comment]
> which build number

This, and any mods

> Exact steps to reproduce?

And this

**Comment by articulateSPLINE** [comment]
Just downloaded 0.C-4448 (or 0.C-11096-g60dd09f, not sure which build number you guys actually need). New world without mods, new character with the Heli Crash scenario and Recruit profession.

To reproduce:
1) Load STANAG magazine with .223
2) Attempt to reload M4A1

Message given is "Out of ammo!" (I was misremembering the cannot be reloaded message). It'll only accept the magazine if it's empty, and it doesn't ask me if I'm sure I want to reload with an empty mag.

**Comment by mugling** [comment]
> and it doesn't ask me if I'm sure I want to reload with an empty mag.

this part is intentional

**Comment by articulateSPLINE** [comment]
> this part is intentional

Ah, my bad. I remember seeing you add that message at some point, must've missed it being removed.

**Comment by mugling** [comment]
Cannot reproduce in `master`

> I'm playing on the latest experimental

> Just downloaded 0.C-4448

This isn't the latest experimental.

I'm wary this is going to follow the same sequence as #15492

**Comment by articulateSPLINE** [comment]
> This isn't the latest experimental.

Huh, double my bad. I always assumed the latest build available from [here](http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/) would be the latest experimental. Sorry about that!

**Comment by mugling** [comment]
Try http://ci.narc.ro/view/Cataclysm-DDA/job/Cataclysm-Matrix/ and then presuming it works correctly you can close your issue

**Comment by Zireael07** [comment]
Judging by my launcher, build 4448 is indeed the latest.

**Comment by Malkeus** [comment]
4448 is the latest for all but a couple versions. Jenkins is having some memory issues it seems and 4449 and 4450 didn't get built for anything but 32bit curses and tiles Linux.

**Comment by mugling** [comment]
> You are compiling from source, right mugling?

Yes

**Comment by mugling** [comment]
> 4449 and 4450 didn't get built for anything but 32bit curses and tiles Linux

That would explain things somewhat

**Comment by player0981234** [comment]
fixed gonna close this
