### ISSUE TITLE
Ammo selection dialog shows unusable choices

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#15517]
New character, wish Remington 700, masterkey shotgun attachment, skill to attach it, and ammo for both. Attach masterkey. Reload the masterkey. Even when it's full, the ammo selection dialog still shows shotgun ammo. Selecting the shotgun ammo results in "Can't reload your Remington 700+".

**Comment by mugling** [comment]
Can reproduce. Bug is in `item::can_reload`. Working on fix
