### ISSUE TITLE
Laser turret bug

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#15531]
version 0.c-11144-gcbf4940
when the laser turret tries to fire it displays a debug message(DEBUG:attempted to fire zero or negative shots with TX-5LR laser cannon) with a regular message (the laser turret's barrel spins and fires).does not actually fire.
nothing happens when the laser turret does not have enough light to fire (A flashing LED on the laser turret appears to indicate low light.  The laser turret's barrel spins, but nothing happens.)

**Comment by player0981234** [comment]
Hey why nobody see this

**Comment by karols146** [comment]
Maybe no one have free time now ;p

**Comment by player0981234** [comment]
You guys need to fix this
