### ISSUE TITLE
Sewing kit consumes 1 charge even when cancelling operation

### ISSUE THREAD

**Issue by Zireael07** [CleverRaven/Cataclysm-DDA#15530]
I've seen it on build 4454 (gf36ed08) 

Repro
1) grab a sewing kit with a nice number of charges (say, ten or twenty)
2) press a, apply kit to whatever
3) press cancel where it prompts you to repair/reinforce/repeat/whatever
4) note the number of charges is no longer ten but 9!

**Comment by karols146** [comment]
should be easy for fix

**Comment by Coolthulhu** [comment]
The charges are actually consumed because an attempt at repair is made before the menu appears. This was a request back then when the first repair PR landed, though I guess it only lead to confusion now.

If you have high enough skill, you can actually repair things with the initial attempt.

**Comment by NickGrease** [comment]
@Coolthulhu Should I leave it the way it was then? Or maybe if damage==0 have 'Cancel' highlighted when the dialog is shown to the user?

**Comment by Coolthulhu** [comment]
You could change the order in which the function is executed or add the menu to the initial function that sets up the activity, but both of those would require some non-trivial C++ skills.

**Comment by NickGrease** [comment]
I can give it a try - I'll close the pr for now. Just so we're on the same page, for clothing, when activating a needle, there are two menu windows - the first asks if you want to repair or modify the clothing or cancel -  the second asks ~how much to repair or cancel. The first window is necessary and I could add 'Repair Now' which would make an attempt to repair before the second window appears. Or just have both windows appear as normal and don't do anything until the user selects an option (How it is now with my 'fix')

**Comment by Coolthulhu** [comment]
> he first asks if you want to repair or modify the clothing or cancel

Modifying this one wouldn't be as easy as it sounds. This menu allows selecting different actions from the item, while we want just different parameters for a single action. You'd have to make 4 copies of the action, which wouldn't be easy either.

**Comment by NickGrease** [comment]
Yes, backtracking through `repair_item_finish` is quite a journey. Adding menus looks challenging, maybe a little to challenging for now.

But if you could answer this one question - What *is* the functionality we're after here? I'm not sure the average player is in a position to take advantage of an 'auto' attempt prior to getting the choice of how to continue - I could be wrong. And two menus to get to the repair doesn't seem to much to ask, so what outcome are we looking for other then not secretly stealing a single thread?

**Comment by Zireael07** [comment]
At high skill levels, the auto attempt might be advantageous. I'm now at tailoring 3 and that auto-attempts amounts to mysteriously lost thread though. :P

**Comment by kevingranade** [comment]
Can we fix it by just printing a message when the menu is exited? Maybe it
should print a summary of what happened, like, "10 attempts, 3 successes,
15 units of thread used".

**Comment by NickGrease** [comment]
@kevingranade Yes and No - the issue here is that a single attempt at repairing is being made without the players knowledge/permission. We *can* tell them the attempt was made - but I suspect it's the *attempt* that's the problem here. I was just looking for some guidance on what is the desired functionality before I decide if its in the range of my capabilities.

**Comment by kevingranade** [comment]
> without the players knowledge/permission.

This stops being the case if the ui tells them about it.

> We can tell them the attempt was made - but I suspect it's the attempt
that's the problem here.

I'm not at all sure that making the attempt is the problem, they obviously
want to repair the item at least once, otherwise they wouldn't have
activated a repair item and selected a target. It looks to me like lack of
feedback about what happened is the real problem.

**Comment by NickGrease** [comment]
With the current form of repair dialog boxes, the second dialog shows you your chance at success or failure. I would imagine I'm not the only one that's gone through the repair menu to check if I have a good chance at repair. Moreover, though I haven't noticed it myself, wouldn't it be possible for the item to be destroyed during that hidden attempt?

**Comment by Salganos** [comment]
I found this behaviour weird as well.  I had honestly thought it might have been some WIP remnant that got left in.

One could argue that one might need to try at repairing the item to know one's chances, but I think it makes more sense for the player to merely need to hold the tool and target, ready to start, to realize when they have no idea what they are doing.  :P

**Comment by Zireael07** [comment]
> I would imagine I'm not the only one that's gone through the repair menu to check if I have a good chance at repair. 

No, you're not the only one.

**Comment by kevingranade** [comment]
Took another look and I have to change my position snd agree with what seems to be the consensus, the "try to repair once" feature seems counterproductive, especially with the use case of using the menu to check costs and chance of success, I'm taking a look at removing it.
