### ISSUE TITLE
No spawns in More Locations mod houses

### ISSUE THREAD

**Issue by martin509** [CleverRaven/Cataclysm-DDA#15541]
I'm aware that this is reporting an issue with a mod and not part of the main game but since it is an official mod and all I'll post this here.
The 2- and 3- story houses added by the More Locations mod have no item spawns in them aside from water in the toilets.

**Comment by kevingranade** [comment]
As long as it ships with the game it's legit to report it here :)

**Comment by DeadLeaves** [comment]
last time I looked none of the more locations mod buildings have any item spawns. While it says WIP on the description, I agree it needs more work.

**Comment by Leland** [comment]
Closing - old and no movement. Feel free to ping me here if there's still interest, or make a new issue.

**Comment by AMurkin** [comment]
And it's fixed by #20835
