### ISSUE TITLE
The dermatik itchiness interrupts long actions

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#15558]
Everytime you scratch the afflicted body part you'll interrupt stuff like reading or waiting

**Comment by karols146** [comment]
Maybe it should be like that, we don't know how much it itchiness. It can be so hard that only thought you had in your head is to scratch, and you can't focus on 
But it's only my weird theory,

**Comment by Coolthulhu** [comment]
It's hardcoded to do exactly that - cancel any activity. Meaning it's not a bug but intended behavior.

That doesn't mean it's good - it's quite annoying with itchy bionic, but rather inconsequential.

**Comment by mugling** [comment]
> Meaning it's not a bug but intended behavior.
