### ISSUE TITLE
Fencing, other armed styles no longer work

### ISSUE THREAD

**Issue by Ernst-Blofeld** [CleverRaven/Cataclysm-DDA#15551]
Experimental 4467.
Fencing no longer gives you any of the special moves or footwork bonuses.
To replicate, create a character with knowledge of fencing, wish for a fencing weapon and melee skill

**Comment by Ernst-Blofeld** [comment]
After more tests, Niten Ichi-Ryu doesn't seem to work either. Eskrima and Silat seem to get passive/hit buffs, but don't give any special techniques with armed attacks.

**Comment by player0981234** [comment]
replicated in 4473
