### ISSUE TITLE
Ammo/gun normalization minor issues

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#15556]
Reloaded 4.6mm ammo has the same display name as factory spec ammo, causing confusion.

Reloaded 7.62x51mm incendiary has extremely low damage and high pierce compared to factory spec. The description also seems to be some amalgamation of the old and new descriptions. Is it incendiary? Is it one-in-five tracer?

Overall, the whole incendiary vs. tracer concept has been very ill-defined as well. According to the description, tracer ammo is a one-in-five mix, which means 80% of tracer ammo is actually just normal ammo. Furthermore, the purpose of tracer rounds is show bullet trajectory, rather than apply special effects. Despite this, and despite the fact that only one in every five rounds is actually different from normal ammo, tracer ammo as implemented can set flesh on fire.

10mm Auto has lower damage than .40 S&W, despite having a larger case, and presumably more powder. While the weakest 10mm loads do have less powder than the strongest .40 S&W, that would be a counter-intuitive assumption to make.

All .223 caliber guns retain their ranged damage bonuses while others have had theirs removed. At the extreme ends, this means a 12 damage differential between the M249 and HK G36. It also means only a 4 damage differential between the G36 and 7.62x51mm guns. Guns should be able to affect damage, as muzzle energy is dependent on barrel length. Perhaps it could be modified to depend on the new barrel length parameter instead of being an explicitly defined bonus, which could be removed in the case of sawn-off weapons. Either way, the bonuses to .223 guns is an anomaly.

**Comment by martin509** [comment]
If we're talking about ammo balance, don't forget how little of a difference (aside from recoil!) there is between .45ACP and 9x19mm ammo.
.45 JHP ammo does 1 point of damage /less/ than 9x19mm JHP, though it does gain 2 points of armourpiercing.
.45 FMJ does 3 points of damage less than 9x19mm for 2 points extra of AP.
Meanwhile overpressurized 9x19 ammo is out-and-out better than .45 in every respect, including recoil.

**Comment by mugling** [comment]
> Overall, the whole incendiary vs. tracer concept has been very ill-defined as well

Yes , I have noticed this during the normalization of the ammo but haven't as yet come up with any better replacement.

**Comment by Ernst-Blofeld** [comment]
> If we're talking about ammo balance, don't forget how little of a difference (aside from recoil!) there is between .45ACP and 9x19mm ammo

Guns chambered in .45 tend to have higher damage stat:
4 dam for L39-45 vs 1 dam for L39
1 dam for USP 45 vs -1 dam for USP 9 (and volume 1 vs 2 for some reason)
whooping 6 damage for m1911 vs -1 damage for beretta m9

**Comment by mugling** [comment]
Most of these issues are either resolved with the remainder in-progress as part of other issues or PR's
