### ISSUE TITLE
Field campsite occasionally spawn right in the middle of the road, not nearby it.

### ISSUE THREAD

**Issue by OsobistSCP** [CleverRaven/Cataclysm-DDA#15564]
It doesn't look good, when a road is broken by some camp, looks kinda strange.

**Comment by player0981234** [comment]
It can spawn anywhere I found one spawning in the middle of a river

**Comment by mugling** [comment]
Spawn frequency is also arguably a little too high

**Comment by Nioca** [comment]
I'd also argue that they either need their loot toned down a bit, or have some reason to not simply charge one the instant they show up on the overmap for free food.

Also, while I can't top spawning in the middle of a river, I did have one spawn in the middle of a mall once.

**Comment by kevingranade** [comment]
Please open this as a separate issue.

**Comment by Mshock777** [comment]
Hah, nice, field campsite is broken because there's no such overmap location as "field", BUT it can be declared [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/overmap.cpp#L3922-L3938).
