### ISSUE TITLE
Screen view moving when steadying gun during the aiming

### ISSUE THREAD

**Issue by OsobistSCP** [CleverRaven/Cataclysm-DDA#15561]
When you tap "." for steadying gun the screen moving into enemy direction and remains still far from the player position. Then you need to tap "center view" to restore screen normal condition.

**Comment by mugling** [comment]
Can reproduce

**Comment by Firestorm01X2** [comment]
Reproduced.

**Comment by nulman** [comment]
It happens to me as well, a workaround is to save and load

**Comment by mugling** [comment]
@nulman you can also recenter the view which is by default bound to `:`

**Comment by player0981234** [comment]
The  :  key does nothing for me

**Comment by nulman** [comment]
@mugling  ohh wow, that saves me so much time, thanks!

**Comment by mugling** [comment]
@nulman indeed, but underlying issue still needs addressing

**Comment by OsobistSCP** [comment]
Should I provide something else?

**Comment by mugling** [comment]
No (unless of course you know of a fix)

**Comment by OsobistSCP** [comment]
Sorry, I can't into a code :( I would love to fix it.

Maybe we should tag this issue as bug?

**Comment by calibraptor** [comment]
View also seems to automatically snap to my target, regardless of whether I have snapping disabled or not.

**Comment by Firestorm01X2** [comment]
This bug should have higher priority. It is unvoidibible bug. And it makes aiming punishing for player.
