### ISSUE TITLE
All tents in Incomplete cabin/camps are Large Tents

### ISSUE THREAD

**Issue by Murumuru** [CleverRaven/Cataclysm-DDA#15569]
As title says, all tents in places like Incomplete Cabin and Camps are Large Tents. 

Issues:

- [ ] If player takes down 3x3 tent, they will get 5x5 tent
- [x] If the tent player tries to take down is damaged, the player will still get undamaged Large Tent (fixed by #20841)

Edit by @Leland: moved to checklist

**Comment by player0981234** [comment]
replicated in 4479

**Comment by Night-Pryanik** [comment]
Fixed after #20157?

**Comment by Leland** [comment]
@Night-Pryanik the second half of the issue – "If the tent player tries to take down is damaged..." – is fixed by #20157 and #20841. The first half is not.

Small tents taken down are still large tents.

**Comment by Night-Pryanik** [comment]
Tested right now on 0.C-6851, Windows XP SP3 x86. Taking down 3x3 tent gives you 3x3 tent.
