### ISSUE TITLE
Emepty magazines still connected with ammo type and cannot be unloaded

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#15578]
If you shoot all bullets from magazine then it will be marked as magazine with zero bullets. But it still will be connected with ammo type that was loaded before.
You can't unload that magazine. And you can't reload it with another type of ammo that fits ino magazine. So if you have no  ammo of that type- your magazine will be deadlocked.

Reproducing:
- Shoot all ammo from magazine (important: shoot out but not unload);
- Try to load with another type of ammo but with same caliber;
- You can't do that becuase magazine still remember old type of ammo and and it can't be unloaded, becuse it containts no ammo.

**Comment by Zireael07** [comment]
Empty magazines are not supposed to be 'one size fits all' kind of devices.

**Comment by Firestorm01X2** [comment]
It happens even if bullets should fit into magazine. I tested but with .45 caliber bullets of different types (refited, normal JPH).

**Comment by mugling** [comment]
What are the **exact** sequence of steps

**Comment by Firestorm01X2** [comment]
- Take M1911;
- Take 7 .45 FMJ reifeted bulets and 7 .45 ACP JHP bullets
- Take emepty magazine .45
- Load it with .45 FMJ reifeted
- Load magazine into pistol
- Shoot out ALL bullets
- Unload emetpy magazine from pistol
- Try to load .45 ACP JHP bullets into that magazine
- You can't do it becuase mag wait FMJ reifeted

**Comment by mugling** [comment]
`item::ammo_consume` incorrectly retains an empty ammo item witch `charges == 0`

**Comment by mugling** [comment]
@Firestorm01X2 your original title is more concise and therefore preferred
