### ISSUE TITLE
0 price for some items

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#15573]
The price is 0 for same items, like grenades, turrets, landmines, melee weapons, etc

**Comment by ejseto** [comment]
Caused by recent changes forcing charges = 0 (rather than -1) for tool items. In item::price():
```
    // if tool has no ammo (eg. spray can) reduce price proportional to remaining charges
    if( is_tool() && ammo_type() == "NULL" && ammo_remaining() > -1 ) {
        ret *= ammo_remaining() / double( std::max( dynamic_cast<const it_tool *>( type )->def_charges, 1L ) );
    }
```
There needs to be a new way to differentiate tools that have run out of charge and tools that cannot be charged. Simply checking for max charges > 0 might suffice.

**Comment by mugling** [comment]
I'll look into this
