### ISSUE TITLE
CBM: Active Defense System (Deflects bullets?)

### ISSUE THREAD

**Issue by Stevensonz** [CleverRaven/Cataclysm-DDA#1558]
Has anyone actually deflected bullets with this CBM (Might be missing Deflection Code?) or the description is misleading? As I'm pretty sure it's not 100% deflection rate or if there is any at all as getting shot from turrets with these doesn't seem to drain extra Power.
##

**Comment by Leland** [comment]
This is one of the oldest open issues in the repo! I'm closing this for now, but if there's still interest by anyone, let me know here and I'll reopen; or feel free to make a new issue.

**Comment by vlad1492** [comment]
There is still interest!
