### ISSUE TITLE
[Mod]  Invalid casing property NULL

### ISSUE THREAD

**Issue by Rasip** [CleverRaven/Cataclysm-DDA#15592]
Latest build 4481 (0.C-11316-g6b7fce1)  is throwing warning on world load for essence, essence_blood, and essence_dull. This is with a fresh world and no other mods active.
My copied over world from 4478 (0.C-11272-gb46e4cc) with lots of mods also has this warning for lance_charge and lance_charge_shot.

**Comment by mugling** [comment]
Likely regression from #15576

> is throwing warning on world load for essence, essence_blood, and essence_dull. This is with a fresh world and no other mods active.

These are items from mods?
