### ISSUE TITLE
Windows builds broken.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#15608]
Ever since [build 4482](http://ci.narc.ro/job/Cataclysm-Matrix/4482/).

Looks like it's [due to the new encumbrance caching](http://ci.narc.ro/job/Cataclysm-Matrix/4482/Graphics=Curses,Platform=Windows/console).

**Comment by kevingranade** [comment]
If it's the missing initializer thing I pushed a fix.

**Comment by Rivet-the-Zombie** [comment]
That looks to have fixed it!
