### ISSUE TITLE
Found a "Cannabis Seed (0)" in a pot farm basement

### ISSUE THREAD

**Issue by jedibob5** [CleverRaven/Cataclysm-DDA#15605]
Schroedinger's seed?
![capture](https://cloud.githubusercontent.com/assets/13815411/13381687/c9798388-de27-11e5-857d-e11f4c93e625.PNG)
Version 0.C-11316-g6b7fce1

Edit: All of the seeds in the basement spawned in stacks of 0, making them pretty much unusable.

**Comment by NickGrease** [comment]
Any chance you were using an older save? On a new world, new save, every pot basement I jumped to had (if any) `cannabis seed (2)` I'm still learning the code, but it doesn't look like it can spawn with anything other than 2 seeds currently.

**Comment by jedibob5** [comment]
That's probably it. The character was created on an older experimental. Should I close this, then?

**Comment by NickGrease** [comment]
I think it's safe to close.

**Comment by mugling** [comment]
I'm fairly confident this is a remnant from older saves before we introduced the charges normalization in #15571 but please re-open if you see further instances
