### ISSUE TITLE
Gizzard mutation is weird; prevents fullness.

### ISSUE THREAD

**Issue by Salganos** [CleverRaven/Cataclysm-DDA#15603]
Things I have noticed about the Gizzard mutation:
- It prevents one from being full or slaked: being able to hold less food should still result in fullness at maximum capacity.
- It lies about remaining capacity for water and food: drinking water when "thirsty" often warns the player that there is not enough room; ignoring this warning and drinking anyway does not result in a message about not being able to finish it all.  (Warning is often accurate when not "thirsty"; see above.  Sometimes happens with food as well.)
- It derives from a trait/mutation that directly opposes it: Gizzard descends from Light Eater, which appears to increase food efficiency by 50%, from slowing the metabolism by 2/3rds; Gizzard, conversely, directly decreases food efficiency by 40%, and just makes one always somewhat hungry, rather than eat lightly.
- None of this seems to have much to do with actual gizzards: the gizzard of a bird is, if anything, to improve its digestion, reducing the need for chewing (which birds are generally bad at); being a chamber of the stomach, it is not clear that it should lower capacity in any significant sense.  (And let's not get into crops.)

Edit: Because I forgot: a version about which to anchor this: 9ccc9ff.  (Sorry.)

**Comment by WizardOfOoo** [comment]
If I'm reading consumption.cpp correctly the only function of "gizzard" is to reduce the nutrition you get from food by 40%.  

    if( has_trait( "GIZZARD" 
        factor *= 0.6f;

and later: 

    mod_hunger( -nutr * factor * hunger_factor ); 

I tried it and with beak, bird, and gizzard MY PC can't get full now matter how much I eat or drink.

I'd recommend changing the bug to "Can't get full with Gizzard mutation"

Also the description needs to be changed since it doesn't affect your metabolic rate at all.

**Comment by WizardOfOoo** [comment]
Does the description needs to be changed or the effect changed?

**Comment by Salganos** [comment]
It has an additional effect in `player::stomach_capacity()` of lowering the capacity by "20", which is does by not increasing it by 20 (negative values appear to be increases here, considering the `HIBERNATE` flag).

Reducing the efficiency of food has the same effect, balance wise, as increasing metabolism, since the time it gains one from eating a piece of food is lowered either way.  The back-end is different, and it would stack differently with the metabolism effect, though, which might matter if it didn't eat the only one in the bird line upon acquisition.

I think the effect of lower capacity needs some debugging, and the trait itself needs revising or removal, since it makes very little sense both in its prerequisites and its theme.  One might argue that some birds have fast metabolisms (hummingbirds come to mind), but much of that is a function of activity, and avian digestion is typically as good as mammalian digestion, from diet to diet.

**Comment by WizardOfOoo** [comment]
What about changing the description to "You get hungry frequently, and you never quite feel full." ?

That might be turning a bug into a feature, not good coding practice.  But I don't know the intent of the original coder.

**Comment by Salganos** [comment]
I feel that would still be better served by just replacing it (and Light Metabolism, by extension) with Fast Metabolism, if birds just need to be hungry for balance reasons.

**Comment by Salganos** [comment]
To have a logical gizzard mutation, it would be something that improves digestion of certain foods (hard non-meat foods, mostly) if one has swallowed some small pebbles recently.  This would have to be offset by not being able to get that exact same bonus by chewing, due to having almost certainly gained a beak.  (Do bird mutants still have teeth in this game?  Would effectively just be a limited mutation version of the expanded digestion CBM in that case.)

**Comment by WizardOfOoo** [comment]
I don't think the game models chewing or ability to chew.

I think that you are right in that it's misnamed .  It is a negative mutation, it needs to be bad or mostly bad.

I'm up for replacing it with one of the increased matabolism mutations, but it would take a good bit of color out of being a bird mutant.  Maybe having a Gizzard just takes up space that would otherwise be  your stomach, effectively making your stomach smaller.  You could speed eat up eating time like Gourmaund to account for the fact that your gizzard is doing the chewing.

**Comment by Salganos** [comment]
Well, gizzards do take up space from the stomach, being chambers of the stomach, but they then have most of that taken capacity as capacity of their own, and I don't see how that ought to have an effect worth implementing at that point.

Also, bird for which stomach capacity and, more importantly, ingestion speed is an issue tend to have crops, which flip the situation around completely.

**Comment by secretfire42** [comment]
Here's an idea. Bird mutants with the gizzard mutation can no longer eat cooked food (or most normal food) - but instead can eat fresh flesh (like from animals, like vultures), or occasionally peck at the ground when idle for small nutrient bonuses? (like chickens). It would require a beak mutation, and signify moving away from a mammalian/human diet.

**Comment by WizardOfOoo** [comment]
What about replacing gizzard with carnivore?  It would make your more like a buzzard or vulture.

**Comment by Salganos** [comment]
I don't see why bird mutants wouldn't be able to eat most anything we can.  A gizzard is a literal replacement for molars, and I'm not even sure those have fallen out here (the beak can do the work of incisors and canines just fine, and a bit more).  It has no effect on raw meat, since chewing meat, especially raw meat, is mostly redundant, since acid and pepsin can permeate most soft tissues quite well.  Most carnivores don't even bother chewing, and carnivorous birds have highly reduced or repurposed gizzards (one species stuffs it with its own feathers to filter out small fish bones that haven't dissolved yet).

Replacing gizzard with carnivore would result in vampire hummingbirds.  (Hummingbirds don't even need gizzards.  >.> )

Honestly, though, neat as having two beaks seems on paper, I can see no reason (other than really liking hummingbirds) anyone wouldn't just chug more mutagen until the beak that _doesn't_ suck appears.  But that's another matter.

**Comment by Leland** [comment]
Closing - old and no movement. Feel free to ping me here if there's still interest, or make a new issue.
