### ISSUE TITLE
Disabled Magazines causes 9mm guns to use .45 capacity magazines

### ISSUE THREAD

**Issue by Nioca** [CleverRaven/Cataclysm-DDA#15601]
_Windows Console, Experimental 0.C-11316-g6b7fce1_

What it says in the title. If Disabled Magazines is active, 9mm firearms that can make use of a .45 ACP magazine will use the .45 magazine to determine it's capacity (resulting in 9mm weapons with greatly reduced capacity).

It's possible other firearms which use two sets of magazines are effected as well, but a quick test suggests the issue is limited to 9mm. Possible JSON load order issue?

**Comment by mugling** [comment]
Can reproduce
