### ISSUE TITLE
[Critical] Time passage problem in today's build

### ISSUE THREAD

**Issue by Zireael07** [CleverRaven/Cataclysm-DDA#15615]
In build 4493 (ge86fc60), taking any sort of action upon starting/loading a game will cause the game to become unresponsive and a large chunk of time to pass (from day 32 6 pm to day 34 3:30 pm in my case).
All I did was release the cart, so even physically moving from tile to tile isn't necessary to trigger it.

Forum link: http://smf.cataclysmdda.com/index.php?topic=12217.0

**Comment by mugling** [comment]
Do we know the most reason version without the bug?

**Comment by Zireael07** [comment]
I can confirm that 4481 doesn't have the bug.
Someone on the forums said that 4482-4488 are unavailable? 4489 onwards seem to have the bug.
