### ISSUE TITLE
Fusion blaster does not function as intended.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#15610]
Reported in the forums here:
http://smf.cataclysmdda.com/index.php?topic=12175.0

The shots from the blaster pass through enemies and walls and then the projectile explodes at maximum range as if it had hit something. Nothing gets damaged by the shot itself but only by the explosion afterwards.

**Comment by Rivet-the-Zombie** [comment]
This is currently affecting all explosive projectiles. They don't trigger when they hit a creature; they just pass through.

**Comment by player0981234** [comment]
Doesnt happen with my grenade launcher hits zombies as intended

**Comment by player0981234** [comment]
It does hit by the shot itself
