### ISSUE TITLE
Wrong invalide JSON escape in data/json/mapgen/roadstop_a.json

### ISSUE THREAD

**Issue by VlasovVitaly** [CleverRaven/Cataclysm-DDA#15626]
Line 53.
`"i": "This was once a infromation map for the \<city\> area, but it has long since been eroded beyond usefullness. There are small holders for tourist maps attached."`

So this `\<city\>` is invalid JSON escape sequence. I can't update translations template due Python JSON parser will raise exception. I can ignore this file but this is wrong.

Where this part of mapgen JSON is used? May be we can do `\<city\>` => `<city>`

**Comment by vache** [comment]
`<city>` should work correctly.
