### ISSUE TITLE
TEC9 do not use magazines.

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#15620]
Windows Tiles x64 0.C-11441-g59f0c3c
I've go dropped TEC9 from zombie survivor. For some reason it don't need magazines and ca be reloaded directly using ammo.

But TEC9 uses magazines: http://www.cdnnsports.com/national-mag-intratec-tec-9-9mm-32rd-mag.html#.VtSiYeYUP_I

NOTE: I don't use mod that disables magazines.

Steps:
- Get TEC9;
- Get 9x19 ammo;
- Try to reload it with ammo:
- Reloading will be successful but it shouldn't be.

Possibly TEC9 magazine not in game yet? Or simpyl it is config error?

**Comment by Firestorm01X2** [comment]
I checked data\json\items\magazine\9mm.json
Looks like TEC9 magazine not in game yet.

**Comment by bumpkindda** [comment]
There's still a bunch of guns that should have magazines but don't. I'm not sure if mugling is still working through the meat and potatoes of adding magazines, or if he is getting close to finished and would find it helpful to have a list made up of guns that should have mags but don't. If it's the latter I could start a forum thread and get people to contribute.

Off the top of my head I know the TEC-9 and Calico M960 are missing mags, (at least some of) the flamethrowers should probably have detachable tanks, the repeating crossbow and bolt driver should have craftable bolt hoppers, and the heavy automatic shotgun and Mark 19 could use some kind of ammo belts.

**Comment by mugling** [comment]
> find it helpful to have a list made up of guns that should have mags but don't

Everything within `data/json/items/gun` has been converted and everything in `data/json/items/ranged.json` remains outstanding.

> could use some kind of ammo belts.

Are still a work in progress. The missing part is how these should be created from the ammo plus linkages.

**Comment by bumpkindda** [comment]
Yeah I noticed the .223 and .308 belts aren't fully done yet.

You're doing amazing work and I love the changes btw, just thought I'd let you know.

**Comment by kevingranade** [comment]
Nit, repeating crossbow has a hopper, not a detachable magazine, so that
should stay as it is.

**Comment by Rivet-the-Zombie** [comment]
Same with the bolt driver having multiple barrels and requiring air pressure - it's not capable of using magazines.

**Comment by bumpkindda** [comment]
Ah yeah, for some reason I thought those hoppers were detachable. My bad.

**Comment by kevingranade** [comment]
This is a very well known issue so I'm closing as a duplicate.
