### ISSUE TITLE
Snap to target always enabled

### ISSUE THREAD

**Issue by calibraptor** [CleverRaven/Cataclysm-DDA#15639]
Set it to false, still snaps to target when I take aim with a firearm on the latest experimental build.

**Comment by NickGrease** [comment]
Are you able to move the cross-hairs with the arrow keys?

**Comment by calibraptor** [comment]
Can still move the crosshair but the camera stays centered on where I'm aiming

**Comment by player0981234** [comment]
Also if you turn off snap to target with the * key the camera gets locked to the target instead of the player
