### ISSUE TITLE
Wrong vehicle part removal requirements displayed

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15651]
Removing wrenchable/screwable components requires a wrench/screwdriver, but still displays that it requires a hacksaw.

**Comment by NickGrease** [comment]
Would this style be agreeable? 
![clipboard01](https://cloud.githubusercontent.com/assets/854582/13720974/2c522c40-e7e6-11e5-8563-1303020368e9.png)

![clipboard02](https://cloud.githubusercontent.com/assets/854582/13720985/46cc6108-e7e6-11e5-885f-782aeeb2c507.png)

![clipboard03](https://cloud.githubusercontent.com/assets/854582/13720986/4b15cce0-e7e6-11e5-9dbd-3f602c8e238f.png)

Alternate (Secondary separators)
![clipboard04](https://cloud.githubusercontent.com/assets/854582/13721015/07fbd354-e7e7-11e5-8e11-f6cbb1ae21d0.png)

I guess I can remove the `(s)` on Primary tool(s)

**Comment by Night-Pryanik** [comment]
Will "ESC-back" be visible on all variants or only on the second one?

**Comment by NickGrease** [comment]
> Will "ESC-back" be visible on all variants or only on the second one?

That was actually me making sure that the text fit in the 3 different vehicle window display modes (horizontal, vertical, hybrid) and I just happened to take a screenshot inbetween changing modes. I believe the ESC is there in hybrid mode (that is to say, I didn't add it, it was there already).

**Comment by illi-kun** [comment]
PR #15992 is landed, so this should be closed, I suppose.
