### ISSUE TITLE
High dodge and precise aim softlock

### ISSUE THREAD

**Issue by vulkans22** [CleverRaven/Cataclysm-DDA#15652]
I suspect the combination of #14628 and #14704 has made it possible to get stuck on an infinite loop when a player has a high (8+) dodge and a slow to aim weapon.

Where:

1. Player enters aim mode and selects precise aim on an adjacent target.
2. Adjacent target swings at player before player is able to fire.
3. Player dodges and receives recoil penalty, thereby bumping the stability meter back down.
4. Lock condition begins where player is stuck aiming and dodging, where the recoil penalty overpowers aim speed.

The only way to get out of this state is by getting hit or just waiting until you collapse from lack of sleep. My last test had me waiting for 2 whole in-game days before the latter happened.

**Comment by NickGrease** [comment]
`recoil += std::max( weapon.volume() - get_skill_level( skill_dodge ), 0 ) * rng( 0, 100 );`

As written, it *looks* infinity cumulative, which is a problem. But as you describe it, even putting a cap on recoil wouldn't solve your particular problem, since you'd quickly reach any cap and then stay there as long as you are in combat. I mean, technically speaking, if your constantly dodging, you *can't* take precise aim. Putting a cap on recoil would however prevent you from having to wait days for recoil to wear off. Any suggestions on what the cap should be... `weapon.volume() * 100` ?

**Comment by Coolthulhu** [comment]
I'd say the formula shouldn't be linear with volume. Linear is fine at low volume (makes modded pistols harder to use, which is a good thing), but once we get to shotguns, dodging hits is often worse than taking them.

Also, the recoil penalty should be applied regardless of dodge success. It doesn't make sense that dodging penalizes the player harder than not dodging.

**Comment by NickGrease** [comment]
> I'd say the formula shouldn't be linear with volume.

Are you referring to the recoil formula as it is now? Or the formula for determining the cap?

> Also, the recoil penalty should be applied regardless of dodge success.

Agree, but should a hit that deals no/little damage affect recoil?

**Comment by Coolthulhu** [comment]
> Are you referring to the recoil formula as it is now? Or the formula for determining the cap?

The former, but it could apply to the cap too.

> Agree, but should a hit that deals no/little damage affect recoil?

Yes, just less. It's not possible to snipe while dogs jump at you.

**Comment by vulkans22** [comment]
Perhaps I should have added: I looked at the function, thought about the formula, the results and how to go about avoiding the never ending loop between recoil and confidence.

And then it hit me- the fact that you're gaining more recoil than confidence isn't necessarily the problem (Quite the opposite, I agree that this is what should happen), the problem is that you can't interrupt the process so the solution was trivial: Just add a long action interrupt whenever your character dodges while using one of the long action aim options and be done with it. I've made the change on my end and it suits me just fine.

**Comment by NickGrease** [comment]
`recoil = std::max( weapon.volume() - ( (get_dex() / 2 / 10 ) * get_str() ) , 0 ) *  weapon.volume();`
Would making recoil amount based on str and dex work?

Wep.Vol | Dex|Str|Recoil
------------ | -------------| -------------| -------------|
5|10|10|0
5|5|10|12.5
5|5|5|18.75
10|10|10|50
10|5|10|75
10|5|5|87.5
15|10|10|150
15|5|10|187.5
15|5|5|206.25
20|10|10|300
20|5|10|350
20|5|5|375

I'm assuming that if you're dodging multiple monsters at the same time, these values will add up. As for capping the total recoil (from dodging) - do we need a formula or just a flat cap - say three times the recoil cost of dodging? Keep in mind, this is *just* the recoil cost of dodging - other recoil costs (firing/getting hit) are also added elsewhere.

**Comment by NickGrease** [comment]
Does that solve the problem of recoil going off into infinity if you're constantly dodging?

**Comment by Coolthulhu** [comment]
Hardcoding interrupt for just one weapon type could be confusing.

**Comment by NickGrease** [comment]
Maybe I'm looking at this wrong. I agree with @Coolthulhu that the recoil formula could be reworked. I just keep coming back to the `recoil +=` and thinking it should just be `recoil =` or `recoil +=` with a sane cap (a few turns max). Dodging 10 times in a row shouldn't equal 10 times the recoil, if I'm reading the code right.

**Comment by vulkans22** [comment]
@NickGrease Not directly, in that recoil won't skyrocket if I interrupt the action before it has a chance to. Though some kind of cap to recoil would probably be sensible as trying to shoot after a good 5 hours of dodging while trying to squeeze off a shot means you have to wait a corresponding amount of time to be able to shoot again, which is totally nonsensical.

@Coolthulhu Are there any other weapon types that have a long action associated with their use? I can't seem to think of any at the moment. Just so that we're on the same page, this is a problem specific to the Precise aim option which aims until you reach maximum confidence, a condition that because of the constant recoil penalty, is never going to happen hence the game getting stuck and needing to be process killed.

I know not a lot of players use these alternative options (And I'm also thinking some players aren't even aware of their existence) and rather elect to use the Aim key manually, though I use it because it's quicker from a "Number of keypresses required" perspective. If an interrupt would be confusing, perhaps the precise aim option needs a rework.

**Comment by Coolthulhu** [comment]
> Are there any other weapon types that have a long action associated with their use?

There are lots of long actions not tied to weapon uses.

Tying it to actual aim action could make sense, but tying it to weapon type would only make it confusing.

**Comment by vulkans22** [comment]
I see now what you're suggesting, placing the interrupt at the aim action would be better. Beyond that, I can't think of any other way to solve this one without reworking what the precise aim action does.

**Comment by mugling** [comment]
Does this still exist after extensive alterations to aiming?
