### ISSUE TITLE
Build failing on Ubuntu 14.04

### ISSUE THREAD

**Issue by jwpartain1** [CleverRaven/Cataclysm-DDA#15667]
Building with "make CLANG=1 CACHE=1 RELEASE=1". Was able to build a week or so ago.

src/mapgen.cpp:1697:40: error: no member named 'basic_bind' in namespace 'mapf'
", mapf::ter_bind("*", t_paper), mapf::basic_bind(""));

**Comment by Treah** [comment]
Caused by this https://github.com/CleverRaven/Cataclysm-DDA/pull/15649
