### ISSUE TITLE
Helmet netting doesn't give storage

### ISSUE THREAD

**Issue by 11132113** [CleverRaven/Cataclysm-DDA#15664]
Windows tile build 0.C-4480

Either on dropped items or in crafting menu, the helmet netting show Storage: 0.
Equipping it gives no storage either.

**Comment by Zireael07** [comment]
I fail to see why this is a problem. Not all items give storage.

**Comment by mugling** [comment]
@11132113 that was change a long time ago to have no storage

**Comment by 11132113** [comment]
I'll close the issue then.

**Comment by mugling** [comment]
@11132113 I'd leave it open actually. Once the PR queue has got a little quieter I'll push that into `obsolete.json` unless anyone objects prior.
