### ISSUE TITLE
Drop Kel-Tec KSG and pipe combination gun

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#15661]
These two weapons (ab)use gunmods to achieve multiple ammo types. I don't think either realistically sees much use and its arguable the extra complexity isn't worth maintaining.

Unless there are any objections I'd like to mark them as obsolete until we extend the reloading code sufficiently enough to correctly allow multiple magazines and alternative ammo types.

**Comment by John-Candlebury** [comment]
The Lemat revolver and the normal combination gun work like this too. The combination gun isnt very good, but the ability of the Lemat revolver to hold both shotgun-shell and .44 makes it a really good fallback sidearm.

I wouldn't support marking those as obsolete before the magazine system is extended

**Comment by mugling** [comment]
> The Lemat revolver ... a really good fallback sidearm.

That's a good point
