### ISSUE TITLE
Aisle light charge solar panels

### ISSUE THREAD

**Issue by 11132113** [CleverRaven/Cataclysm-DDA#15671]
Windows tiles build 0.C-4480

Aisle light charge solar panels mounted on the same vehicle.

The setup was 7 solar panels, 1 truck battery and 1 aisle light on an RV van.
Note that 2 squares adjacent to the aisle light were considered "outside" (only frame and roof built on them).

It looks similar to  #4712

edit: Battery charge even if the vehicle is all closed up.

**Comment by ZombiesAreUs** [comment]
Are you sure it's the aisle lights charging them? I just checked on a recent build and moonlight also charges solar panels, ever so slightly (perhaps not as slight as it should though). Aisle lights didn't seem to have any effect, nor could I find any reason they would in the code.

**Comment by 11132113** [comment]
I did more testing and I think you are right it seems to be the moonlight responsible and not the aisle light.


The charge rate for solar panels is in vehicle.cpp

`epower += ( part_epower( part ) * accum_weather.sunlight ) / DAYLIGHT_LEVEL;`


The code for the lighting is a bit too complex for me so I can't figure out the exact difference between day and night.

As for the balance, I'm not sure this is relevant considering the OPness of solar panels and cars in general.
