### ISSUE TITLE
Hardened scavenger in ambush scenarion doesn't have magazines for FN SCAR-H

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#15674]
Hardened scavenger in ambush scenarion doesn' have magazines FN SCAR-H.

To reproduce
- Start custom character
- Select "Ambush" scenario;
- Select hardened scavenger;
- You will notice that he has no magazine for his  FN SCAR-H but has ammo. Description says that he found "best gear". So he should have magazines.

**Comment by player0981234** [comment]
All professions with guns, found guns(excluding dropped guns) and defense mode guns have the same problem

**Comment by mugling** [comment]
@player0981234 also needs addressing so please open a separate issue for this
