### ISSUE TITLE
Throwing items creates a lightning sound on impact.

### ISSUE THREAD

**Issue by NickGrease** [CleverRaven/Cataclysm-DDA#15693]
Any item I throw, the impact sound is 'lightning'. Kinda cool at first, but pebbles sounding like Thor is a bit 
much. Affects _any_ thrown item.

Stack after throwing a javelin by hand
```
1	game::explosion	explosion.cpp	283	0xa03ac7	
2	Creature::projectile_attack	ranged.cpp	282	0x8a6480	
3	Creature::projectile_attack	ranged.cpp	60	0x8a6bf3	
4	player::throw_item	ranged.cpp	678	0x8a7a57	
5	game::plthrow	game.cpp	10579	0x97707b	
6	game::handle_action	game.cpp	2818	0x98b4fd	
7	game::do_turn	game.cpp	1396	0x98e614	
8	main	main.cpp	434	0xcb4245	
```
Warning: Novice attempt at tracking this down.
I _think_ this has _something_ to do with `projectile::projectile` & `projectile::operator=` in `damage.cpp`

By the time we get to this line:
`ranged.cpp: Line: 282: g->explosion( tp, proj.get_custom_explosion() );`
I think the expected value for `itype->explosion` would be `null` (for say a javelin) but because `proj` has had an assignment at:
`ranged.cpp: Line: 116: projectile &proj = attack.proj;` itype->explosion *is* a `null_explosion` but not a `nullptr`, which `projectile::operator=` checks during the `proj.get_custom_explosion()` above. 

(i think null_explosion gets default values from explosion.h `explosion_data`) 

So I think I'm in the right area, but unsure how to proceed...

**Comment by mugling** [comment]
Possibly relatedly gunfire is intermittently producing small explosions at the target square. The potential connection is that they both involve `projectile`

**Comment by NickGrease** [comment]
@Coolthulhu Thanks for the quick fix. I had just added the same lines to ranged.ccp, so I was close :)
