### ISSUE TITLE
Crafting inventory includes ammo contained in magazines

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#15692]
Noticed whilst working on an implementation of ammo belts. Items should not be considered available for crafting if they are already contained by a gun, magazine or tool.

**Comment by ejseto** [comment]
Happens with attached gunmods too (if you mod in gunmods made of other gunmods). It'll strip them right off, even before the ones already in inventory.

**Comment by mugling** [comment]
Fixed by #15948 and #16061
