### ISSUE TITLE
Portable structures aren't handled by assign_activity

### ISSUE THREAD

**Issue by defrost256** [CleverRaven/Cataclysm-DDA#15700]
Version: 0.C-11734-gca9e530

Unlike foraging, butchering.. etc. taking down portable structures aren't handled by the players activity management.

This becomes apparent in the following situation: While taking down your tent in the middle of the forest you are attacked by a wild moose. The game gives you no queries about getting approached/attacked/hurt, you can just simply die (as I did).

Seems like a simple change, though I'm not familiar with the source enough to make a PR.

**Comment by Leland** [comment]
Looks like discussion's stalled for at least a year. Closing. If there's still interest, let me know here and I'll reopen.
