### ISSUE TITLE
Escaping out of sort menu in advanced inventory causes ui display glitch 

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#15708]
When you esc out of the sort menu you get a black box on the screen where the menu was. It mostly goes away once you hit a key and the inventory screen redraws.

**Comment by illi-kun** [comment]
@Cyrano7 is it still an issue? We have some progress in fixing these glitches, but I need you confirmation concerning exactly this menu.

**Comment by illi-kun** [comment]
I've checked that in current master, it still happens.

**Comment by Cyrano7** [comment]
I was the one who caused the glitch originally actually https://github.com/CleverRaven/Cataclysm-DDA/pull/15699

**Comment by illi-kun** [comment]
No need to worry about that, it's easy fixable.
