### ISSUE TITLE
Throwing of items with bashing<=0 should not deal significant damage (if any)

### ISSUE THREAD

**Issue by illi-kun** [CleverRaven/Cataclysm-DDA#15714]
Unsuccesful attempt of fix and discussion of issue is available in #15280.

**Comment by Shadefang** [comment]
My main issue with this is that with high throwing skill it makes sense to be able to effectively use unorthodox thrown weapons. For a real life example, see axe (as in wood axe) throwing competitions.

**Comment by Coolthulhu** [comment]
Axes do have bashing value, so it's not a problem.

Things with zero bashing damage are generally too soft, too bulky compared to their weight or too tiny to be used as weapons.

A thrown pair of pants won't deal damage, a thrown book will just stop mid-flight (unless it has heavy bindings), a thrown 9mm cartridge will be too light to do anything more than getting attention.

**Comment by Shadefang** [comment]
And i now realize i dragged way too much from the last discussion over.

I fully agree with you on the points/items you brought up, but I don't feel that it should be based solely on bashing damage. 
In example, lawn darts don't have any bashing damage, and shouldn't really, but are ideal thrown weapons. Or in a more extreme case, a glass shiv (given it's volume it's around the size of a knife) doesn't,, and shouldn't, have bashing damage, but someone who's skilled at throwing weapons should still be able to land it point first and apply its cutting damage.

**Comment by ituluwituluwzev** [comment]
#20414 

Closing - more updated discussion can be found in issue 20414
