### ISSUE TITLE
More potential comestibles.json optimization  

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#15710]
Once all the PRs modifying the comestibles file are resolved i'm considering going back and trimming up a bit. Some potential candidates are...
"tool" : "null", appears 659 times + "tool": "null", 21
"addiction_potential" : 0, 513  + "addiction_potential": 0, 21
"addiction_type" : "none", 525 + "addiction_type": "none", 48
"stim" : 0, 474 + "stim": 0, 19
2280 lines total

tool seems to be "null", addiction_potential : 0, and stim : 0 by default already.

**Comment by Rivet-the-Zombie** [comment]
Nice!

**Comment by illi-kun** [comment]
I see no reason for keeping this issue open - just implement it (if it works correctly and doesn't brake anything).

**Comment by mugling** [comment]
Agreed
