### ISSUE TITLE
Missing/wrong food materials/allergens

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15726]
- [x] Acorns are typeless and can be consumed by everyone (#22457)
- [x] Paper is typeless
- [x] Starch is typeless
- [x] Boozeberry contain no berries, contrary to description
- [x] Cornmeals are typeless
- [x] Lard is junk food, meaning it can be consumed by herbivores but not carnivores
- [x] Burgers don't contain wheat
- [x] Musts (for wine etc.) are typeless
- [x] Cooked mushrooms are typeless

**Comment by Leland** [comment]
So far, from https://github.com/CleverRaven/Cataclysm-DDA/pull/17573 and https://github.com/CleverRaven/Cataclysm-DDA/pull/15813:

- Acorns are typeless and can be consumed by everyone
- Paper is typeless
- Starch is typeless
- ~~Boozeberry contain no berries, contrary to description~~
- ~~Cornmeals are typeless~~
- ~~Lard is junk food, meaning it can be consumed by herbivores but not carnivores~~
- ~~Burgers don't contain wheat~~
- ~~Musts (for wine etc.) are typeless~~
- ~~Cooked mushrooms are typeless~~

I'm pretty sure paper (https://git.io/v9KX2) wasn't typeless at the creation of this PR, but could be wrong.

**Comment by Night-Pryanik** [comment]
All issues are resolved, closing.
