### ISSUE TITLE
Picking up parts of stack issue

### ISSUE THREAD

**Issue by Murumuru** [CleverRaven/Cataclysm-DDA#15728]
Game does not check if player has incomplete stack of an item player tries to pick up.
This results in situations, when player with full volume filled cannot pick up items.
Example: player has 10/10 volume filled, 1 of the volume is rhubarb, player found other 1 rhubarb, but cannot pick it up, because it goes over the volume. It is still possible to pick up by dropping rhubarb from the inventory on the rhubarb lying on the ground and then picking them both.

**Comment by kevingranade** [comment]
#16732 is a partial fix, but the reported issue still happens.
