### ISSUE TITLE
Regaining traits can override conflicting mutation clearing

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15725]
"Your Saprovore mutation turns into Herbivore!"

Saprovore has Carnivore as a requirement. That carnivore wasn't cleared for some reason.

The resulting mutant can't eat meat, eggs or plants, hates junk food and basically has to subsist on milk, acorns (which aren't plant matter, I assume due to oversight), paper, alcohol and own misery.

Could be restricted to traits which were lost due to conflicting mutation, but later regained, as my character started with herbivore (to avoid the inevitable Carnivore creeping in).

**Comment by Rivet-the-Zombie** [comment]
>The resulting mutant can't eat meat, eggs or plants, hates junk food and basically has to subsist on milk, acorns (which aren't plant matter, I assume due to oversight), paper, alcohol and own misery.

That's a pretty brutal collision of traits!

**Comment by wapcaplet** [comment]
I could not reproduce this in 0.E-9737-g511ddcb179. The "Saprovore" mutation does not require "Carnivore" (nor does it have any other prerequisites). If I debug mutate "Carnivore", then "Saprovore", I can have them both, but as soon as I mutate "Herbivore", the "Carnivore" mutation is canceled as expected:

![image](https://user-images.githubusercontent.com/238395/108566188-377c1500-72c3-11eb-8cf0-72cb1deef872.png)
