### ISSUE TITLE
Categories and subcategories names' in crafting menu are untranslatable

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#15734]
Windows 10, tiles, x86, 0.C-4536. At least in Russian.
They were translatable some time ago, but I didn't remember exactly the moment when they become untranslatable.

**Comment by cainiaowu** [comment]
Same in Chinese(simplified) with 100% translated mo.

**Comment by VlasovVitaly** [comment]
So after template update all category should be translated again. sry.
