### ISSUE TITLE
Getting stuck in follower NPC dialog

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#15733]
Sorry the title is vague, don't know how to phrase it, give me a better title and i'll change it.

When I have a follower and I talk to them, sometimes the "let's go" option is assigned to the "l" key. ![Screen Shot](http://imgur.com/yeqmLcI.jpg).

if I hit "l" to try to leave the conversation It instead shows me the "look at" result.  ![Screen Shot](http://imgur.com/zl3y6OM.jpg)

My caps lock is off  And I have tried both "l" and "L", it give me the same results.

I can get out of the loop by selecting the "hold on to this item," not giving them anything and then hitting "a" for lets go.

**Comment by WizardOfOoo** [comment]
This has been going on for several days now.  

Using: 
0.C-11844-gc9234a9 and several of the last few days builds from the main site.
Windows version with tiles x64
Windows 10 x64

**Comment by Coolthulhu** [comment]
For now I'll just remove the lowercase 'l' bind, though a more proper fix would be to redesign the whole menu.
