### ISSUE TITLE
Ruger 223 mags should only be compatible with the Mini-14

### ISSUE THREAD

**Issue by articulateSPLINE** [CleverRaven/Cataclysm-DDA#15758]
As of 0.C-4543 (unmodded), the Ruger 223 magazine is accepted in STANAG weapons and the description specifically states it is STANAG compatible. I know it's pretty nit-picky, but IRL Ruger Mini-14 mags are proprietary and simply wouldn't work in any other weapon without a lot of modification. The main difference is how they lock in to place within the magazine well - a STANAG mag is pushed straight in whereas the Mini-14 mag is rocked into place (very similar to AK pattern rifles in that regard).

As such, I propose the following changes be made:
- Remove STANAG compatibility from Ruger 223 magazines
- Rename the magazine for accuracy, perhaps "Ruger Mini-14 magazine" (or "Ruger Mini-14 10 rd magazine" if higher capacity Mini-14 magazines are added down the line)
- Change the magazine description to reflect these changes

After searching here and the on the forums, I couldn't find any discussion as to why the magazine is STANAG compatible so I assumed this is an oversight - many apologies if it's intended for some reason!

**Comment by mugling** [comment]
Welcome @articulateSPLINE. Thanks for searching before posting. This was discussed and resolved some time ago but I am also struggling to find the issue to link to.

The outcome was that we were going to try and limit the number of magazines in `master` for balance purposes to prevent the situation where the player struggles to find a matching magazine. There will of course be some departures from realism in doing so (the `bore` conversions spring to mind also). The idea of a mod that adds/adjusts magazines has been suggested but as yet nobody has stepped forward to express interest in curating this.

I'm closing this issue for now as it's already been covered and indeed the decision is somewhat grandfathered now we have a large number of existing saves dependent upon such compatibility. If you have more suggestions please feel free to re-open it and/or if you want to contribute mod content I'd be happy to explain how the magazine internals work.

**Comment by illi-kun** [comment]
I remember this discussion too, @articulateSPLINE you can read #14981 and other mugling's PRs for more info.

**Comment by mugling** [comment]
@illi-kun thanks, I forgot where all that had been covered

@articulateSPLINE further suggestions as to reworking of item descriptions is not to be discouraged especially if these won't affect gameplay or save compatibility

**Comment by articulateSPLINE** [comment]
Thanks for the replies and link @mugling and @illi-kun, and many apologies for the duplicate issue! I tried a number of searches in commits, issues and pull requests (both open and closed) but couldn't for the life of me find the right discussion. 

The reasoning here and in the provided link makes perfect sense though I would like to suggest giving the Mini-14 STANAG compatibility for simplicity/consistency's sake - as a github nub I'm not sure where it would be best to make such comments, and even then I'm pretty sure it'll throw save compatibility issues.

> The idea of a mod that adds/adjusts magazines has been suggested but as yet nobody has stepped forward to express interest in curating this [...] I'd be happy to explain how the magazine internals work.

I've actually been playing with the idea of a high capacity/aftermarket magazine mod for a couple days now - I can't promise I'll be able to make it a reality (my previous attempts at coding have left me with epic headaches!) but I'm willing to give it a try if you point me in the right direction. 

Thanks again guys, especially for your work on magazines in the first place!

**Comment by illi-kun** [comment]
@articulateSPLINE No need to apologize since searching of this wasn't trivial.
It will be interesting to see your mod!

**Comment by BorkBorkGoesTheCode** [comment]
Could this be reopened?

**Comment by kevingranade** [comment]
Yep, particularly since as far as I can tell, "this was discussed and resolved" means, "this is what I said".
