### ISSUE TITLE
"Play Now!" issues

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#15757]
1. Sometimes this mode creates player with no profession at all:
![11111111111111111](https://cloud.githubusercontent.com/assets/11132525/13721652/42596528-e83e-11e5-8317-34c09edf1769.png)
2. I assume that this mode should get us straight to fully random world with fully random character, right? But character always spawns only in shelter. Is there any specific reason for forbidding random scenario and random starting location in this mode?

**Comment by kevingranade** [comment]
1. Of course it does, no profession is an option.
2. No, reasonably random, fully random would frequently be unplayable.

**Comment by Night-Pryanik** [comment]
But there's no "No profession" to choose when creating custom character.

**Comment by codemime** [comment]
> But there's no "No profession" to choose when creating custom character.

That's a fair point.

**Comment by BevapDin** [comment]
> But there's no "No profession" to choose when creating custom character.

There is. It is called "Survivor". Try it out. It does not appear in the character screen, but is otherwise just like nay other profession.

**Comment by codemime** [comment]
@BevapDin You're right. That probably means, that the issue can be closed.
