### ISSUE TITLE
Chain Lightning CBM is not shocking mobs

### ISSUE THREAD

**Issue by Brian361** [CleverRaven/Cataclysm-DDA#15753]
Chain Lightning acts like a normal gun only shooting a single mob without electrifying them, does not create a cloud of electricity as the description implies and does not affect more than one mob.

**Comment by NickGrease** [comment]
Sorry - I referenced the wrong issue - not sure how to fix...

**Comment by HereticChurch** [comment]
I think this might be happening for the same reason https://github.com/CleverRaven/Cataclysm-DDA/issues/15732 is - "apply_ammo_effects" was tacked on to some weapons that were moved from ranged.json to their respective .json files in the guns folder, but it doesn't work. Manually going into the ups.json and bio.json and changing "apply_ammo_effects" to "ammo_effects" fixes the issue.
