### ISSUE TITLE
JSON packing

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#15777]
@kevingranade recently touched upon the idea that whilst our JSON hierarchy is helpful for editing it could be inefficient for the parser to load.

Performance testing suggests this is indeed the case. The `--dump-stats` option from #15765 is an ideal test-case as it parses everything under `data/` before aborting:

|                  | real       | user       | system  |
|--------------|----------- |------------|-----------|
| current     | 15.96     | 15.34     | 0.48      |
| packed     | 11.46     | 10.88     | 0.46      |
|                 | **-28%** | **-29%** | **4%**   |

Times are in seconds (averaged to account for any OS or hardware caching)

The (naive) packed solution is 2.4M and fast to produce:

```
time jq '[ .[] ]' `find data/json -name '*.json' > packed.json
    0m0.19s real     0m0.18s user     0m0.00s system
```

I suspect it's highly compressible but the above benchmarks suggest raw IO isn't a limiting factor.

It's probable that sorting the data before concatenation and then using C++ insert hints could further improve upon the naive solution as could the ongoing work to specify and remove defaulted values.

One trivial approach would be to read from `data/` for `DEBUG` builds and `packed.json` for `RELEASE`. Alternatively we could just rebuild the packed form as necessary given it can be achieved in ~200ms? Neither approach restricts how we arrange or edit files under `data/`

**Comment by kevingranade** [comment]
I was thinking rebuild as necessary after comparing timestamps, if that
doesn't add too much overhead.

**Comment by mugling** [comment]
Frustratingly having written such a packing tool I'm unable to reproduce the above (or indeed any) performance benefits

**Comment by kevingranade** [comment]
Can you PR what you have? I'm really surprised at it not having a benefit
and would like to see if I can figure out what is stopping it.

**Comment by mugling** [comment]
Sure, let me clean it up a bit first. I'm away for a few days so if nothing towards the weekend might be worth bumping this issue then
