### ISSUE TITLE
Explosions don't bash the starting point

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15772]
Discovered while attempting to reproduce the crash in #15764
- Spawn an electric car (any multi-tile car has no gas/diesel/plasma tank)
- Spawn 10 RDX charges
- Activate them all
- Have them all detonate over the same car tile
- Car is vaporized, that one tile is unscratched

**Comment by Night-Pryanik** [comment]
Yeah, I realized that too after I couldn't destroy my shopping cart with two ACHT charges.

**Comment by BevapDin** [comment]
I can't reproduce this. Is this with Z-levels enabled or disabled? With z-levels it makes an impressive crater, several z-levels deep. However the grass/dirt tiles directly under the car survive remain, but underneath them is open air. Very strange but beautiful. Anyhow, the car is completely gone.

**Comment by Night-Pryanik** [comment]
Tested right now with Z-levels disabled. Still as issue on 0.C-5114.
