### ISSUE TITLE
Fire Station Wenches no longer open the doors.

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#15779]
The diagnally placed wenches in fire stations no longer open to allow access into the stations.

**Comment by dbackeus** [comment]
Can confirm that this happened to me a few days ago as well.

**Comment by ejseto** [comment]
How do you expect them to open the doors from the kitchen?

**Comment by Night-Pryanik** [comment]
That's because now fire stations are made from brick, not from generic wall. I'll try to repair that.
