### ISSUE TITLE
electric jackhammer bug

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#15787]
when modified with ups conversion mod electric jackhammer have unlimited charges and dont need to recharge ever.i enjoyed that for some extreme tunneling but i dont think its intended.

**Comment by jcd000** [comment]
i can't reproduce this. latest experimental seems to work as it should.

**Comment by baraba3** [comment]
sorry for late reply,

last version i played is tiles 4567 and i was experiencing that bug.saw
that one man also complanined about gunsmith repair kit which isnt draining
power on ups i think so they probably fixed it along that.


2016-03-17 20:15 GMT+01:00 jcd000 <notifications@github.com>:

**Comment by kevingranade** [comment]
Reported fixed, good, thanks for reporting.
