### ISSUE TITLE
'Chance' Variable has different definitions based on where it is used

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#15780]
'Chance', as used for placing furniture, terrain, and items in mapgen .jsons varies in definition between
- '1 in n' chance of spawning
- ''x' percent'

Meaning that if you use 10 as the variable it works out to the same 10% chance (1 in 10), but otherwise its somehwat confusing that the same variable uses different definitions, especially when a 'prob' variable exists for items.

**Comment by Leland** [comment]
Looks like discussion's stalled for at least a year. Closing. If there's still interest, let me know here and I'll reopen.
