### ISSUE TITLE
Shockwave resonator makes it possible to get SMASH!! sound

### ISSUE THREAD

**Issue by EditorRUS** [CleverRaven/Cataclysm-DDA#15797]
http://i.imgur.com/tq2XXSI.jpg

So it seems like Sonic Resonator costs 0 moves to activate yet performs destruction leading to what is on the screenshot.

**Comment by Leland** [comment]
Looks like discussion's stalled for at least a year. Closing. If there's still interest, let me know here and I'll reopen.
