### ISSUE TITLE
Is there a standard style json files should be written in? 

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#15791]
I didn't see anything about it in CODE_STYLE.txt. For example its annoying when searching for one field that's written in two different styles. Like "stim": 0, and "stim" : 0,. It's also kinda weird having fields be standardized throughout a whole file but be standardized differently then others like in recipe_food.json "type" : "recipe", and "skill_used": "cooking",

**Comment by Coolthulhu** [comment]
It doesn't look like there is one. It could be useful. A json astyle would be even better.

**Comment by kevingranade** [comment]
Unfortunately I wasn't able to find an auto styler for json that meets our
needs, they seem to be mostly aimed at making json barely readable, and are
frequently all-or-nothing (you can't tell them to fix indents but not wrap
your lines).
As a quick stab at the most important issues:
2 space indents
No tabs
Spaces around colons
Attach commas to left element

Other issues are fuzzy, e.g. I don't consider mandatory line wrap after an
open brace to be reasonable in json.

**Comment by mugling** [comment]
OP question was answered so closing

> A json astyle would be even better.

See #17431
