### ISSUE TITLE
Foot pedals allow controlling other engines

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15798]
- Install V12 and gas tank on a bicycle
- Start up bicycle
- Turn off foot pedals
- Drive around controlling the V12 with your feet somehow

**Comment by jcd000** [comment]
I won't say it was intended, but theoretically, if one could pedal-move the car with a gasoline engine in gear (and keys at the 'on' position of course), the engine would start after a few meters.

I've seen this at work a few years back, at a downslope and a dead-battery car (or when the spark plug of my uncle's motorbike wouldn't work properly)

So it could be seen as a feature, no? :)

**Comment by mugling** [comment]
Fixed in `master`
