### ISSUE TITLE
Steel jerrycan can still hold 100 units of water

### ISSUE THREAD

**Issue by Rizoel95** [CleverRaven/Cataclysm-DDA#15800]
Steel jerrycan was recently changed to take up 80 volume, down from 100 volume. But it can still carry 100 units of water.

To reproduce:

1. Spawn steel jerrycan
2. Go to a river or somewhere with a lot of water
3. Fill'er up
4. End up carrying 100 units of water in a very not-flexible 80 volume container.

Also tested with other liquids like gasoline from gas pumps; same thing is true.

**Comment by Mshock777** [comment]
I think he forgot to change `contains` value.

**Comment by mugling** [comment]
> I think he forgot to change contains value

Yes, that was it
