### ISSUE TITLE
"electronic control unit" strictly inferior to regular controls

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15807]
Regular controls include the CTRL_ELECTRONIC flag of the control unit, but have more hp, are foldable, have lower installation difficulty and allow actually controlling the vehicle.

What is the electronic control unit supposed to do? Maybe it should use a different part and be easier to install or something.

If it is supposed to only control the electronics themselves, it could have 1 difficulty, require only a screwdriver and use something cheaper than controls (not sure what). Alternatively, the regular controls could have a higher difficulty instead.

**Comment by mutt3x** [comment]
>What is the electronic control unit supposed to do?

The way i see it is it should allow you to control things from a diff spot in your vehicle. I mostly have one installed near my bed so i dont have to go (all the way) to the main vehicle controls.
Its purpose may also be intended for those non mobile bases to control things inside the house/base, in that case its somewhat odd to put vehicle controls.

**Comment by illi-kun** [comment]
It was implemented in #13963 and original idea was (afair) to separate controlling of electronics from actual steering controls. It definetely can be tweaked.

**Comment by illi-kun** [comment]
One of the possible ways to solve this issue is to separate control part to two different parts: steering device + (electronics) control panel.

**Comment by illi-kun** [comment]
I have the following solution for this issue (which I expect to use as a roadmap in case of support of it):
- add new non-foldable vehicle part, a ```dashboard```, with ```CTRL_ELECTRONIC``` flag to represent controls for all electrical systems;
- add ```dashboard``` to most templates of predefined vehicles;
- make ```electronic control unit``` foldable, with a role of supplemental electrical control panel in big vehicles / a light foldable version of ```dashboard``` for smaller vehicles.
- add quite simple crafting recipe for ```electronic control unit```;
- remove ```CTRL_ELECTRONIC``` flag from ```controls``` (which are steering & pedals controls); the only purpose of this vehicle's part will be the motion control of a vehicle;

**Comment by kevingranade** [comment]
That sounds reasonable :+1:

**Comment by mlangsdorf** [comment]
Illi-kun seems to have dropped this issue. I'm going to pick up the rest of it:

- make electronic control unit foldable, with a role of supplemental electrical control panel in big vehicles / a light foldable version of dashboard for smaller vehicles.
- add quite simple crafting recipe for electronic control unit;
- remove CTRL_ELECTRONIC flag from controls (which are steering & pedals controls); the only purpose of this vehicle's part will be the motion control of a vehicle;
