### ISSUE TITLE
Volume of some items should be adjusted

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#15810]
Since in recent PR `metal_tank_little` increased in volume, some items that have it inside should be adjusted too for continuity.

**Comment by veox** [comment]
With a [small python script](https://gist.github.com/veox/24a10ae71e0dd695ef63) I've limited it to these items:

```
json/recipes/recipe_electronics.json trimmer_off
json/recipes/recipe_electronics.json bio_reactor
json/recipes/recipe_electronics.json bio_plut_filter
json/recipes/recipe_others.json chainsaw_off
json/recipes/recipe_others.json jackhammer
json/recipes/recipe_others.json charcoal_cooker
json/recipes/recipe_weapon.json aux_flamer
json/recipes/recipe_weapon.json combatsaw_off
json/recipes/recipe_weapon.json tihar
json/recipes/recipe_weapon.json helsing
json/recipes/recipe_weapon.json chemical_thrower
json/recipes/recipe_deconstruction.json lawnmower
json/recipes/recipe_deconstruction.json oxy_torch
json/recipes/recipe_deconstruction.json oxygen_tank
json/recipes/recipe_deconstruction.json sm_extinguisher
mods/blazemod/blaze_autoweapons_recipes.json flamethrower1
mods/blazemod/blaze_autoweapons_recipes.json flamethrower2
mods/blazemod/blaze_autoweapons_recipes.json flamethrower3
mods/blazemod/blaze_other_recipes.json smokescreen
```

**Comment by Cat09** [comment]
alternatively, a "mini" tank could be created for some of these items
Note: -future possibility-  variable size storage tank spawning and variable size recepie (range) which carries over volume taken and storage capacity, and fuel bladders which shrink / expand.

**Comment by mugling** [comment]
> alternatively, a "mini" tank could be created for some of these items

We have too many containers already. It would be best to consolidate and improve upon the existing set rather than add more

**Comment by kd8qdz** [comment]
what was the old volume?   I cant find the PR.

**Comment by Mshock777** [comment]
#15773, it increased from 5 to 8.

**Comment by archer77** [comment]
Is there any reason why volume is using integers rather than doubles? wouldn't it make it much easier if we make the volume of an item an (unsigned) double, thus allowing us to make items with a volume less than 1? Why are we using signed integers anyways?

**Comment by Coolthulhu** [comment]
Using integers prevents stupid and unrealistic micromanagement, like carrying just 5 tiny pills or 3 9mm bullets or few pinches of salt, from being optimal.
Having everything require a "slot" is much more like what would happen in real life, with boxes and containers for everything.

**Comment by kevingranade** [comment]
Floating point numbers introduce complexity and failure modes that integers
don't have, plus c++ in particular makes typing and such with mixed
floating point and integral operations a pain.
We use signed integers by default for some of the same reasons, unsigned
underflow in particular turns an easy to check for a negative number into a
non-obvious huge number.

**Comment by mugling** [comment]
In summary floating point no, rescale maybe, specific item changes please submit PR.
