### ISSUE TITLE
Various tools now require jerrycan_big, not metal_tank

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#15814]
Fallout from #15773 

The following recipes now need jerrycan_big, which in turn requires metal_tank. Previously the recipes needed metal_tank_small. It is a little weird to need to craft the jerrycan as an intermediate step; perhaps they should just directly require metal_tank?
- still
- char_kiln
- char_forge
- char_smoker
- brick_kiln
- con_mix

**Comment by keyspace** [comment]
Agreed. `jerrycan_big` consists of `metal_tank`, `string_36`, and `scrap` (1 of each). The latter two are the handle?..

`still` now has different requirements (see 69ea0938a62a217552a8ebe85d29a6370dda6bef, part of #16044). True still for the other five.
