### ISSUE TITLE
New overmap_specials option

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#15811]
Just a small feature request from me, not a very important one.

Some mapgen uses asphalt (i.e. for parking lots) but it gets completely ruined by 4 lines of sidewalk.
It would be nice to be able to add `"connect": "road_turn"` instead of `"connect": "road"` to replace sidewalk with asphalt. (this is handled in overmap.cpp on line 3882)
Or maybe allow each json determine how connection should look like.

If anyone is crazy enough to look into it, it would be nice to the ability to specify if there is more than 1 connection to the road.

Edit: OR inside `overmap_terrain.json` we can convert `"sidewalk" :` from bool to string so each overmap_terrain can set type of terrain they prefer ( it is done in overmap.cpp on line 357, mapgen_functions.cpp on line 1047 (and mapgen.cpp on line 10477?))

P.S. I don't want to create new issue, but it would be nice to have something like `"connect": "sewer"` for connecting mapgen houses to sewer system.

**Comment by Leland** [comment]
Looks like discussion has stalled on this suggestion. Closing. If there's still interest, let me know and I can reopen.
