### ISSUE TITLE
Colliding with monsters when vehicle is in reverse makes monster bounce in the wrong direction.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#15827]
While testing #15804, I noticed that backing into a monster such that the left side of my vehicle hit the monster made the monster bounce to the right, and vice versa, I'm sure a sign just needs to be flipped somewhere.

**Comment by pisskop** [comment]
Monsters have long been colliding with the windshield when they are on your vehicle and you speed off.

**Comment by keyspace** [comment]
If this hasn't been fixed yet - it's probably the particuar `do-while` that's discussed in #19974. The one that deals with velocity and displacement in `vehicle::part_collision()`. Perhaps this?..

``` c++
const int angle_sum = vel2_a > 0 ?
    move.dir() + angle : -(move.dir() + angle);
g->fling_creature( critter, angle_sum, push_force );
```

**Comment by keyspace** [comment]
Ah, no, the current code's been added in 1bc4cf2a0ce81e39c423c4fa35fe86e3b399427e (part of #13436).
