### ISSUE TITLE
Muscle engines drain hunger/thirst/stamina even when turned off

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15820]
* Install torsion racket bionic and power storage (needed later)
* Install a muscle engine and a non-muscle engine on a vehicle
* Turn off the muscle engine, but keep the non-muscle one turned on
* Drive around
* Torsion racket will charge the power storage, meaning it is draining player's resources

**Comment by Zireael07** [comment]
Electric bicycle has two engines by default, so you don't have to install anything if you find one.
