### ISSUE TITLE
Wool allergy not registering for some wool items.

### ISSUE THREAD

**Issue by JasonNAwesome** [CleverRaven/Cataclysm-DDA#15834]
Characters with a wool allergy are still able to wear certain items made of wool, such as "long wool scarf", "wool chest wrap", and "pair of wool foot wraps" despite the material being tagged as wool.

**Comment by Night-Pryanik** [comment]
That's because the items with you mentioned have `OVERSIZE` flag, which don't prevent item with it from being worn with allergy.

**Comment by JasonNAwesome** [comment]
So oversize items are exempt? It seems as thought those items should still be off limits to characters with wool allergies.

**Comment by Coolthulhu** [comment]
Sounds to me like that OVERSIZE part is a bug.

There may be an even worse one, just below it: OVERSIZE prevents the helmet wearing check, meaning you could wear 2 XL survivor helmets on top of a regular one. Same for boots.
