### ISSUE TITLE
Saved game results in crash after a certain amount of time

### ISSUE THREAD

**Issue by Nasuga** [CleverRaven/Cataclysm-DDA#15830]
I'm not sure if a certain behaviour is causing this crash but I'm able to trigger it within 11 ingame minutes by either walking around or holding '5'.

A brief recap, I built a vehicle welding rig and installed it in my Solar Tanker. I saved and started crashing shortly after. I've had the same crash with the same savegame earlier but it was rare and had no pattern. Now, it crashes within very little time. 

I'm running the tiled version 0.C-12172-g0eafbbf on Linux (Trisquel 7; a FOSS only distro of Ubuntu 14.04 and Linux Mint 17.3). I don't have access to a Windows machine to test it on. When the game crashes ( both tiled and ncurses), the window closes and I get an error returned in terminal:

```
nasuga@Lenovo-G50-30:~/Downloads/Git/Cataclysm-DDA$ ./cataclysm-launcher 
/usr/include/c++/4.8/debug/safe_iterator.h:171:error: attempt to copy-
    construct an iterator from a singular iterator.

Objects involved in the operation:
iterator "this" @ 0x0xda0f428 {
type = N11__gnu_debug14_Safe_iteratorINSt9__cxx199814_List_iteratorI4itemEENSt7__debug4listIS3_SaIS3_EEEEE (mutable iterator);
  state = dereferenceable;
  references sequence with type `NSt7__debug4listI4itemSaIS1_EEE' @ 0x0xda0f428
}
iterator "other" @ 0x0xdfa2468 {
type = N11__gnu_debug14_Safe_iteratorINSt9__cxx199814_List_iteratorI4itemEENSt7__debug4listIS3_SaIS3_EEEEE (mutable iterator);
  state = singular;
  references sequence with type `NSt7__debug4listI4itemSaIS1_EEE' @ 0x0xdfa2468
}
Aborted
```

Dropbox to an archive contained both my save game and configuration files:
https://www.dropbox.com/s/oj9nx3vcyrl0afg/save-and-config-data.tar.xz?dl=0

**Comment by narc0tiq** [comment]
The debug container issue strikes again (most recently discussed in #15628). Try adding `RELEASE=1` to your `make` invocation?

**Comment by Nasuga** [comment]
@narc0tiq That solved the issue. Thanks.
