### ISSUE TITLE
Have allergies not only effect morale but cause pain.

### ISSUE THREAD

**Issue by JasonNAwesome** [CleverRaven/Cataclysm-DDA#15833]
The severity of the pain can be discussed here, but it seems to be logical that allergies would not only effect morale but cause some pretty bad rashes/stomach pains.

**Comment by Night-Pryanik** [comment]
Did you mean only food allergies? Because if one have wool allergy, he can't wear wool clothing at all, so he don't get no morale penalty and no rash or pain.

**Comment by JasonNAwesome** [comment]
Yes, then wool is obviously out of the question since it's unwearable. Food allergies though, such as specifically wheat allergies, should cause some amount of pain.

**Comment by Leland** [comment]
Looks like discussion's stalled for at least a year. Closing. If there's still interest, let me know here and I'll reopen.
