### ISSUE TITLE
Minimap trouble (flickering, distortions)

### ISSUE THREAD

**Issue by Zireael07** [CleverRaven/Cataclysm-DDA#15842]
When walking around, I see the minimap flicker. At night, the flicker is where I believe Full Night Vision would let me see, every few tiles. During the day, the flicker happens every time I go past a building - the indoor tiles are displayed for a second or two and then hidden by the proper fog of war.

What is going on? Some kind of caching being done too late?

Visible in build g26c1f77. I ran the last version I have downloaded to check, nothing such in g0c77ec5. This means whatever happened, happened in the last three days.

**Comment by Zireael07** [comment]
![cata distorted minimap](https://cloud.githubusercontent.com/assets/4525388/13906498/cec72fe6-eed7-11e5-8d65-c189d4a4a9c6.png)

AArgh. See the screen. It's definitely more than just indoor tiles being problematic.

-> Black block on the right hand part
-> Stripes above the house at the top of the minimap

**Comment by codemime** [comment]
I've turned on the minimap and can confirm that. I have the same issue.

**Comment by lucianposton** [comment]
a26fddfea332695e47978d36c3bcd6fb27127086 is the first bad commit according to bisect.

a26fddf  2 days ago  Rearange main rendering method to place curses cursor on @ at the end.

**Comment by codemime** [comment]
Reversing #15828 solved the issue for me.

**Comment by Beanzy** [comment]
#15828 Also breaks the UI refresh when I use SDL ASCII with non default fonts. Prior to #15828 there was no issue.

![cdda issue](https://cloud.githubusercontent.com/assets/15885173/13907707/c8e66c2a-eeca-11e5-87b8-9f47a5624bcd.PNG)

In the picture above the advanced inventory screen was opened and then closed, however the image still remains on screen.

**Comment by DanmakuDan** [comment]
It looks like with the rearrangement of the draw cycle, the minimap is getting drawn with the previous submap offset before the game updates the location where the player is. It looks like it also breaks the minimap when traveling between floors.

**Comment by kevingranade** [comment]
I think there is some caching weirdnwss, but I also see some issues caused
by game::ter_view_z not being initialized

**Comment by DanmakuDan** [comment]
Looks like the minimap draw was implicitly depending on `void map::draw( WINDOW* w, const tripoint &center )` inside `draw_ter()` updating the visibility cache (line 5849 in map.cpp):
```
    visibility_variables cache;
    update_visibility_cache( cache, center.z );
```

Manually adding the call in `game::draw` makes it act normal again. Maybe some of the cache updates can be collected in a function separate from the draw logic?
