### ISSUE TITLE
Segfaults coming from backtrace libraries on NetBSD, OpenBSD

### ISSUE THREAD

**Issue by oldlaptop** [CleverRaven/Cataclysm-DDA#15841]
I've seen a number of segfaults (see #12950 for an example) stemming from the quick-and-dirty replacement for libexecinfo used on *BSD. Since this is not exactly critical functionality, would a PR to make backtrace support optional be appreciated? The other workaround would be to add BSDs to certain ifdefs that already guard backtrace() on Windows, but that seems rather nasty to me. I've tried digging through the source of the offending library (https://github.com/conformal/backtrace/blob/master/libbacktrace/backtrace.c) for a fix there; I don't think much of my chances of even writing a reasonable bug report for it. Possibly it was never meant for C++ programs?

**Comment by lucianposton** [comment]
Can you try building with -fno-omit-frame-pointer? I don't have a *BSD handy to test it, otherwise I would.

**Comment by mugling** [comment]
Presumably fixed by #16073
