### ISSUE TITLE
On hidden squares, live_view shows black window instead of the "Unseen" message like lookview

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#15852]
![before](https://cloud.githubusercontent.com/assets/646121/13912666/e1003192-eefc-11e5-8037-63ec6339bc7d.png)
![fix](https://cloud.githubusercontent.com/assets/646121/13912667/e102c768-eefc-11e5-8ac2-d341f1863e91.png)

**Comment by lucianposton** [comment]
Probably related to this issue is that the empty black window remains even after the mouse is moved to the sidebar. When the live_view window properly renders info for a viewable square, the window disappears when the mouse is moved to the sidebar. The consequence of this is the a section of the sidebar has a black hole (See the first image above).

**Comment by Night-Pryanik** [comment]
Is #11708 related?

**Comment by lucianposton** [comment]
@Night-Pryanik I couldn't reproduce #11708 on the master branch. Is it still an issue? Tiles that normally lit (even with artificial light) seem to show up with mouse look in the current experimental build.

However, if you mouse over the black tiles beyond the car's artificial light, that is definitely this issue.

**Comment by Night-Pryanik** [comment]
Yeah, I couldn't reproduce it either.
