### ISSUE TITLE
Fix mem leaks due to missing delwin()s for newwin()s

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#15851]
They're all over the place. There are several in game::init_ui(), which is called whenever dimensions of the main UI change e.g. toggle_fullscreen(), toggle_sidebar_style(), etc. 264k per call to init_ui().

Ought to just used shared_ptr with a custom deleter for such things.

**Comment by BevapDin** [comment]
> Ought to just used shared_ptr with a custom deleter for such things.

Yes, there is WINDOW_PTR (see output.h) for that purpose.
