### ISSUE TITLE
Can't put items on furniture with SEALED flag

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#15866]
Map::can_put_items() checks whether the SEALED flag is present on the position. Is this a bug? It seems wrong that one cannot put an item on top of a SEALED container e.g. on top of a crate.

https://github.com/CleverRaven/Cataclysm-DDA/blob/cb1881d11c09b72adbb57993c66601bec42c720f/src/map.cpp#L2399

**Comment by Coolthulhu** [comment]
Furniture doesn't have a separate item list, meaning that "in" and "on" are context-dependent.

If placing items on tiles with SEALED furniture was allowed, it would mean putting them inside said furniture.

**Comment by lucianposton** [comment]
@Coolthulhu Thanks for the explanation.
