### ISSUE TITLE
Invalid light level calculations

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15861]
Light levels seem to be normalized against two different values: 0 and LIGHT_AMBIENT_MINIMAL (3.7f). No (inbounds) tile in the game can ever get below the latter, but some mechanics still use the former.

For example:
- Monster vision range is interpolated between day and night vision range using `light / DAYLIGHT` as the parameter. This means that a critter with a lot of day vision and no night vision will still have >1 night vision range in total darkness
- Light level LL_DARK does not seem to be achievable without involving transparency. Since light everywhere is >= 3.7, it can't get below 3.5 which is the lower limit of LL_LOW, except when transparency multiplies it low enough. For example, `map::light_at` will never reach the last statement.
- In `iexamine::dirtmound` there is a comment stating that `ambient_light_at` doesn't work and below a commented out section that compares ambient light to LIGHT_AMBIENT_LOW (3.5).

**Comment by kevingranade** [comment]
This is (somewhat) intentional, 0 is total darkness and
LIGHT_AMBIENT_MINIMAL is as low as it gets in practice to avoid frustrating
user experience from total blindness.
Everything about vision should use 0, everything about setting light level
should have a lower cap of LIGHT_AMBIENT_MINIMAL.
