### ISSUE TITLE
[Suggestion] Accessibility option: Log-less sidebar mode.

### ISSUE THREAD

**Issue by SeanMirrsen** [CleverRaven/Cataclysm-DDA#15864]
Following the discussion [here](http://smf.cataclysmdda.com/index.php?topic=12309.0), I'll be making a list of reasonably small changes and additions to the game that would make the game more playable for players who are forced to use screen-reader software to "see" the game screen due to disabilities of vision. All of this obviously applies only to "console" builds of the game.

* "Log-less mode" option - make the message log in the sidebar blank out on every update, so that only new messages are visible. This makes screen-reader software able to actually detect the new messages, instead of reading through the entire list as the messages scroll. The full log would still be available in the dedicated message log window.

~~* "Navigate to viewed tile" hotkey - reuse the code currently used for mouse-controlled movement, to navigate the character to the currently focused tile when using the `x` look command, or `V` item list. The feature could be occasionally useful to all players as well.~~
~~* Accessible readouts - In combination with the log-less mode, there will be enough empty space on the screen to display some information that can't be easily, well... seen at a glance... in the circumstances. Things like the current sight radius in tiles, the heading of the currently driven vehicle, the direction and distance to nearest hostile monster, etc.~~

edit: Struck out the move-to-viewed-tile suggestion as already implemented (if undocumented), split accessible readouts into a separate issue for tracking.

**Comment by lucianposton** [comment]
> "Log-less mode" option 

This ought to be pretty easy. It already changes the text color as turns pass. Presumably, the window could be cleared prior to each character movement/action so that only actions since the last movement show.

> "Navigate to viewed tile" hotkey

This already exists in some contexts, particularly the 2 you mention, look around and list items. See the TRAVEL_TO action and where it's used in game.cpp. For example, in the look around mode (default x hotkey) you can travel (default t hotkey, I believe). Same with item list (default V hotkey).

**Comment by BlindGuyNW** [comment]
Hi,

Caplin here from the forums. I’m surprised to see this was already a thing. I guess I missed it in the help system. I’ll have to experiment and see how well it works in practice.
Thanks :)

**Comment by lucianposton** [comment]
@BlindGuyNW FYI, I don't see the TRAVEL_TO action in version 0.C. The experimental build has it though.

**Comment by Chezzo** [comment]
I sure wish the sound set worked with console!

**Comment by kevingranade** [comment]
Please open separate issues, otherwise it'll get hard to track what is and
isn't done.

**Comment by SeanMirrsen** [comment]
>This already exists in some contexts, particularly the 2 you mention, look around and list items. See the TRAVEL_TO action and where it's used in game.cpp. For example, in the look around mode (default x hotkey) you can travel (default t hotkey, I believe). Same with item list (default V hotkey).

Okay, we **REALLY** need a centralized list of keybinds. This is listed **nowhere** where I can look ingame. But it's great that it's already in.

>Please open separate issues, otherwise it'll get hard to track what is and isn't done.

Well, one of the three can already be crossed off the list. I guess I'll leave this one up for the log-less mode, and open a separate issue for accessible readouts.

**Comment by lucianposton** [comment]
FYI, here's a podcast about design roguelikes for visually impaired. Rather long, but might have some ideas worth investigating.

http://www.roguelikeradio.com/2012/10/episode-48-designing-for-visually.html
