### ISSUE TITLE
UI Refresh issue when map and console fonts have different size settings

### ISSUE THREAD

**Issue by Beanzy** [CleverRaven/Cataclysm-DDA#15881]
Cata version: Experimental v. 4583 x64 tiles

Since #15828 using custom fonts (ascii instead of tiles) can cause the UI to not refresh properly. Example below.

![catadda2](https://cloud.githubusercontent.com/assets/15885173/14002211/dcba6ba4-f120-11e5-9d01-6ba3b33349dc.PNG)

The advanced inventory ui remains on screen even after it's been closed. Other ui elements have this issue too.

**Edit**: Here is a copy of my fonts and config, [link](https://www.dropbox.com/s/82w8wvoyi9qs1qk/font.zip?dl=0)

**Comment by mutt3x** [comment]
Well well...
This happens only if you change the default w and h in fonts.json
If the default w:8 h:16 is set then there is no bug, oddly.
From what ive seen it happens on any font and on both 32 and 64 bit.

This bug makes the game pretty much unplayable considering the annoyance factor.

**Comment by Beanzy** [comment]
I've realized it's more than non-default values.

If the values for console fonts (i.e. `"fontwidth"` & `"fontheight"`) are different from the map fonts (i.e. `"map_fontwidth"` & `"map_fontheight"`) in fonts.json the refresh issue will occur. 

As far as I've seen, the issue doesn't occur as long as the console and map fonts have the same value (whatever that may be).

**Comment by BFG1992** [comment]
Made a dublicate issue (this one ↑), but it has a video I made of a game's behaviour, here: https://www.youtube.com/watch?v=m4ET-WEG4jA

**Comment by devilstars** [comment]
Same here. Windows build, experimental. Game is unplayable now.
![2016-04-01_092213](https://cloud.githubusercontent.com/assets/12907959/14196966/4107223e-f7eb-11e5-90ca-79e4b966be50.png)

**Comment by SeanMirrsen** [comment]
Can confirm still being an issue, even with bitmap fonts.  
From what I can tell it's a caching issue. Instead of blanking the changed lines in the font and coordinates of the console, it does so in the font and coordinates of the map. It's probably due to the rearranged sequence of `draw_sidebar()` and `draw_ter()` in #15828 .
