### ISSUE TITLE
Issues with buckets

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15892]
I missed a few cases with the buckets. Those are:
* Plastic bags, cardboard boxes and some other similar containers count as buckets even though they shouldn't
* Sometimes other items - glass bottles in particular - can count as buckets when being inserted into a vehicle
* Sometimes cans count as buckets. Cans shouldn't count as buckets because they preserve contents, stopping all rot, so all refilling should be done with dedicated recipes.

Anything else?

EDIT: The first point no longer applies - boxes and bags are no longer buckets.

**Comment by codemime** [comment]
If proper determination causes so much trouble, why not add an appropriate flag (`"BUCKET"`) to the containers explicitly?

**Comment by Coolthulhu** [comment]
The second and third cases are bugs that shouldn't happen with the current implementation.

Having to hardcode bucket for everything is unnecessary. We have 3 container properties - sealable, watertight and preserving. The missed cases are just non-sealable non-watertight containers - they are actually sealable, but don't have that set because before buckets, sealable didn't do anything without watertight.

**Comment by Labtop-215** [comment]
I don't see why you couldn't put a hook on a plastic bag and lower it down into some water to pull up water.  That one sounds legit actually.  A cardboard box or a peice of paper, not so much.  But that's because they are made of paper.

**Comment by dodzy** [comment]
yes, you should be able to use cans as containers (buckets), and they should only preserve the contents if they are sealed (then they are no longer a bucket). The "preserves from spoiling" flag should only be on the aluminum and tin cans when they are sealed.

What bothers me is that right now you can fill f.e. an aluminum can of water, and take it next to a fire, but you can't purify it, only when you have a container that is resealable (bottles etc), you can.
btw i can unwield an aluminum can of water and store in my inventory (should not be possible).

**Comment by Labtop-215** [comment]
It shouldn't be possible, but it reminds me of Unreal World RPG in a sense.  In that game you can carve wooden bowls and fill them with water, then put them in your inventory, chase after a moose, kill that moose, butcher that moose for meat cuts, fall asleep, wake up, cook the meat cuts, and the water is still in the bowl when you want to down those meat cuts with something to drink.

**Comment by DanmakuDan** [comment]
Pudding (and probably yogurt) cups are still considered buckets since the container is non-preserving. Even debugging a pudding cup will have it auto-dumped since it goes straight into your inventory without wielding.

**Comment by mugling** [comment]
How many of these remain problems?

**Comment by Coolthulhu** [comment]
I think the plastic cups are still buckets
