### ISSUE TITLE
Makeshift crowbar uses more volume than the pipe used to craft it.

### ISSUE THREAD

**Issue by nanovad** [CleverRaven/Cataclysm-DDA#15913]
When crafting a makeshift crowbar, the pipe uses 4 volume, the crowbar (when finished) takes 6. Is this intentional?
Either a pipe should be larger or the crowbar should be smaller. I can't see how bending the end of a pipe would make it take more volume.

**Comment by mugling** [comment]
> I can't see how bending the end of a pipe would make it take more volume.

Try drawing that on squared paper...

**Comment by nanovad** [comment]
It's not a 2-volume bend, is what I mean. A crowbar only has a fraction of the end of the pipe bent.

**Comment by mugling** [comment]
The only reasonable option would be to increase the volume of `pipe` but before that check what else uses it...

**Comment by Night-Pryanik** [comment]
Why not lower makeshift crowbar volume to 4?

**Comment by mugling** [comment]
It might upset early game balance too much (makeshit crowbar is #1 early weapon for good reason)

**Comment by Zireael07** [comment]
Don't link to PR one, please :P

**Comment by Night-Pryanik** [comment]
Plain pipe is just 1 cut damage lower than the makeshift crowbar, so pipe is good enough too (maybe number 2?) for an early melee weapon.
Btw, why makeshift crowbar's weight is 0,5 kgs less than pipe?

**Comment by Rivet-the-Zombie** [comment]
>Btw, why makeshift crowbar's weight is 0,5 kgs less than pipe? 

Probably a copying error.

**Comment by mugling** [comment]
> so pipe is good enough too (maybe number 2?) for an early melee weapon

Crowbar is much better (opens windows and doors)

**Comment by Night-Pryanik** [comment]
> Crowbar is much better (opens windows and doors)

But it is not a quality of a weapon itself, but of a tool.

**Comment by mugling** [comment]
Sure, but the point being it's a very versatile item when early on inventory volume is the major issue. It upsets balance for it to be smaller

**Comment by kevingranade** [comment]
Volume is, "how much space it takes up in a container", bending a pipe can
absolutely make it pack less well.
This is intentional.

**Comment by Night-Pryanik** [comment]
> It's not a 2-volume bend, is what I mean. A crowbar only has a fraction of the end of the pipe bent.

**Comment by mugling** [comment]
> This is intentional
