### ISSUE TITLE
Enemies are climbing up and down through z levels when it dosn't make sense to do so

### ISSUE THREAD

**Issue by Labtop-215** [CleverRaven/Cataclysm-DDA#15916]
Lately, (as of the latest experimental available, 0.C-12307-g8d17bd3) zombies have been ascending and descending z levels without using appropriate means to do so.  Basically they don't use the stairs, and instead just pop up out of nowhere.  I've attached a save file that should help demonstrate the issue as I have a Shrieker zombie following my character.  When that zombie shrieks, or if you get to close to a monster that is below you, they will pop up out of the ground essentially.

I have attached a save file here that should help demonstrate the issue.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/190144/save.zip)

I'm using a the 64 bit variant of the experimental tiles version 0.C-12307-g8d17bd3.  (0.C-4590)
It may be worth noting that I'm playing with Experimental z-levels on, as well as I've loaded More Locations, Tall Buildings, and Boats modifications into the world.

I have weighed in on the issue here http://smf.cataclysmdda.com/index.php?topic=12299.0 previously, but I haven't seen any response, and I wanted to make sure this issue was seen.

**Comment by Coolthulhu** [comment]
I've seen it, but I'm not sure what is the best solution for this. I think I'll special case it in some simple way that will prevent zombies climbing out of holes for now.

**Comment by Labtop-215** [comment]
Sweet!  I can't wait to try the next experimental!
