### ISSUE TITLE
Look dosn't highlight the tile I'm looking at

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#15925]
From http://smf.cataclysmdda.com/index.php?topic=12328.0

This bug is due to this compile time check I added: https://github.com/CleverRaven/Cataclysm-DDA/commit/2cd080d48ec8b4ed9172220888ff8b9203de63df#diff-18513665750ef5adf42b5ec29e14162eR8961 . I didn't realize you could disable tiles in a build compiled with TILES=1.

I'll send a fix PR shortly.

**Comment by BFG1992** [comment]
I have posted a probably related issue here: #15983. Maybe you could look into it, please?
I just thought that it would be easier to fix for a person who've just fixed somewhat similar bug :)
