### ISSUE TITLE
Eating cigarette butts improves morale

### ISSUE THREAD

**Issue by flitvious** [CleverRaven/Cataclysm-DDA#15931]
Eating cigarette butts improves morale. Also works with joint roaches. 

Ho to reproduce:
1. Smoke a joint for 15 morale
2. Eat the roach for extra 12 morale

![2016-03-26_16-44-11](https://cloud.githubusercontent.com/assets/7687709/14060336/696089b4-f372-11e5-9200-dc377d67006a.png)

**Comment by karols146** [comment]
`       "type" : "COMESTIBLE",
        "id" : "cig_butt",
        "name" : "cigarette butt"
`
I think that type is a problem here, maybe changing to generic can help ?

**Comment by mugling** [comment]
> I think that "type" is a problem here, maybe changing to generic can help ?

Yes, try `GENERIC`

**Comment by karols146** [comment]
Should working now (tested by me)
https://github.com/CleverRaven/Cataclysm-DDA/pull/15932

**Comment by flitvious** [comment]
Also, cigar butts work as intended. "Can't do anything interesting".

**Comment by illi-kun** [comment]
I guess this issue can be closed since #15932 is landed.
