### ISSUE TITLE
[Answered] Is there a reason the default entry for nutrition in comestibles is -1?

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#15943]
Should we just make it 0 instead?

**Comment by Rivet-the-Zombie** [comment]
That's an odd default, and I agree that zero would probably be better.

**Comment by Cyrano7** [comment]
I wonder if they have already removed any -1 values from the jsons yet. If not I guess the default should be changed to 0.

**Comment by mugling** [comment]
It's a magic value meaning check calories field (which we don't use at all in JSON).

This is addressed by #15910 which changes it so that internally the game always uses the `nutrition` units but allows specification in `calories` with an implicit conversion upon loading from JSON.

**Comment by Cyrano7** [comment]
So how does this relate to 0 values in json? Should 0 values be removed?

**Comment by mugling** [comment]
Yes (after #15910)
