### ISSUE TITLE
At startup, error messages about missing colors

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#15947]
The color_manager::finalize() code iterates over all possibilities of
color+hilight combinations, the majority of which don't exist, e.g.
c_black_red, c_magenta_cyan_white, creating a huge amount of
errors in the log.

See https://github.com/CleverRaven/Cataclysm-DDA/blob/9002859222d72f8492a211f0859ec19bf9583217/src/color.cpp#L81

**Comment by illi-kun** [comment]
Duplicate of #14808.
