### ISSUE TITLE
Graffiti is shown in look view even when tile is not visible

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#15946]
![before](https://cloud.githubusercontent.com/assets/646121/14067604/92cd38f6-f41c-11e5-9264-b92f2e510145.png)

**Comment by illi-kun** [comment]
Please do not create an issue if you have a solution - I spend some time to fix this and now I'm seeing you also have it. Create a PR with description of solved issue is fine.

**Comment by lucianposton** [comment]
@illi-kun Sorry about that. Just trying to keep all these issues documented. I'll better note when issues have a solution already available in a PR.
