### ISSUE TITLE
Battery-powered items disappear when they run out of charges

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#15954]
like flashlight(on).

**Comment by mugling** [comment]
Can reproduce. I think  #15901 triggers some undefined behavior elsewhere. Specifically `target_charges` for the `transform` actor is unspecified.

**Comment by mugling** [comment]
Occurred prior to the recent changes made to `tools.json` by @Cyrano7

**Comment by Voker57** [comment]
I've done the bisection and first bad commit is 2915bc5c139e69a29fefae1271901a2.

**Comment by DanmakuDan** [comment]
While testing a flashlight, the `revert_to` field is `null` when the flashlight runs out of charges. It is checking for the revert type (which is available in the JSON), but it is not loaded properly by the JSON loading procedure. I'm not sure why it is failing yet.

**Comment by DanmakuDan** [comment]
In `iuse_transform::use`, the flashlight (on) is aware that the flashlight (off) is the target type, but that information is not available in `type->tool->revert_to`.

**Comment by DanmakuDan** [comment]
Apparently, `type->invoke( carrier != nullptr ? carrier : &g->u, this, pos );` in `item.cpp:5410` already converts the flashlight(on) into flashlight(off), so the check for `type->tool->revert_to` is `null` since the flashlight is already off and does not have a form to revert to after that.
