### ISSUE TITLE
Auto notes don't remain deleted

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#15959]
With auto notes enabled, deleted auto notes will reappear when you use stairs at a new location.
1. Enter location A with stairs. Go down stairs. Auto note A will be created.
2. Leave location A.
3. Delete auto note A.
4. Enter location B with stairs. Go down stairs. Auto note B will be created. **Auto note A will also be recreated.**

**Comment by kevingranade** [comment]
This is working as intended, though if someone is interested it would be fairly simple to add a "deleted" note that is not displayed on the map and suppresses auto-generation of notes.

**Comment by Leland** [comment]
Closing due to lack of discussion
