### ISSUE TITLE
Add couplers

### ISSUE THREAD

**Issue by OsobistSCP** [CleverRaven/Cataclysm-DDA#15966]
Looks like a lot of enhancement work, but screw it. Add a couplers to make coupled magazines for a weapons. Not for every single weapon, but for those weapons which uses common-shaped magazines, like STANAG or AK. Also add a crafting recipe to create makeshift coupled magazines with a duct tape.

Worth it?

**Comment by Coolthulhu** [comment]
I don't think its worth the effort.

It could be doable with a "meta magazine" structure - creating a magazine that contains magazines and uses some of them to return ammo. So a coupler would contain 2 magazines, feed only from the first one and swap them on activation.

**Comment by mugling** [comment]
> Worth it?

Reload time with a magazine is ~100 moves plus whatever it takes to fetch the magazine from a pouch or the inventory.

Jungle clipped magazines won't fit in most pouches.

Considering the above is it really worth the effort and extra complexity?

**Comment by mugling** [comment]
Closing for now as there's no indication of any need for this feature vs the considerable effort and complexity of an implementation. Feel free to re-open if you can propose an example use-case.
