### ISSUE TITLE
Difficult to find Refugee Center

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#15979]
As a new player, I was unable to find the Refugee Center because it was a full screen off of the revealed area of my overmap. I assumed it was broken until someone in irc said otherwise.

Perhaps there should be a better way to indicate where the refugee center is. Some ideas:
1. Add a map note so that it can be searched.
2. Make it an active mission.

**Comment by kevingranade** [comment]
Do you mean after revealing it with the console in the starting shelter? If
so, adding a mission to investigate it would be reasonable.

**Comment by lucianposton** [comment]
> Do you mean after revealing it with the console in the starting shelter?

Yes.

The console says something to the effect that you add the location to your map, but if it's a full screen away, new players aren't likely to see it (at least I didn't, as I assumed it didn't actually work).

**Comment by Coolthulhu** [comment]
Finding the shortest road and adding it to map could help.

Do we have overmap pathfinding? Could be useful later on (for autotravel and NPCs).

**Comment by lucianposton** [comment]
> Finding the shortest road and adding it to map could help.

I like this option most. Presumably the console could give the directions revealed by the pathfinding.

**Comment by kevingranade** [comment]
Adding as a mission should do the right thing I think, because you'll get a little arrow-like thing on the edge of the map pointing to it.  Revealing a route from the shelter to the refugee center shouldn't be too hard though.

**Comment by Oskar636** [comment]
It's really easy now to find the refugee center using the road path thanks to codemime's PR.

**Comment by codemime** [comment]
I like the idea of adding the mission. I'm gonna add it too.

**Comment by keyspace** [comment]
Revealing location via shelter computer is in. Mission to find it is in.

Haven't tested yet, but perhaps OK to close?..

**Comment by codemime** [comment]
Yeah, this one is resolved.
