### ISSUE TITLE
Double "Drink %s from your hands?" prompt on toilet iexamine

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#15989]
I'm surprised I haven't heard anything about it since it has been occurring for a while. Is it just me?

Only thing i can say - it happens on versions 4617, 4570, but not 3770.

It's handled in iexamine.cpp line 548 (maybe map.cpp line 5094, player.cpp line 9283).

**Comment by Coolthulhu** [comment]
Still happens. Sounds like that handling in iexamine is redundant - `handle_liquid` already handles drinking from hands.

**Comment by nanovad** [comment]
Can confirm. I thought it was just not reading the keypress because I didn't see a flash, but it's possible that it's a duplicate call to the menu. Going to investigate...

**Comment by nanovad** [comment]
Deleting the whole ```if``` block at 10235 seems to have fixed it, but I don't know what other side effects that might have.

**Comment by DanmakuDan** [comment]
The `if` block in game.cpp:10235 offers the 'drink from hands' option to any drink you are pouring out. The `else if` in iexamine.cpp:572 would probably be a better choice to remove.

Is the usage of `drink from hands` actually relevant to pouring out items, or was it specifically intended for drinking from water sources?

**Comment by kevingranade** [comment]
> Is the usage of drink from hands actually
> relevant to pouring out items, or was it
> specifically intended for drinking from water
> sources?

Good point, it's only intended for use with water sources.
