### ISSUE TITLE
Compass and visible monster list are disappearing permanently after doing (almost) any action

### ISSUE THREAD

**Issue by BFG1992** [CleverRaven/Cataclysm-DDA#15985]
I was making a bug report #15983, and somehow managed to lose another bug that was introduced in the very latest build - 0.C-12511-g9ff3363 (Jenkins #4615).

After doing some actions (like walking over a counter or examining an item through `e`) makes compass and visible monster list to disappear completely and permanently. This is persistent even if loading a save.

To reproduce:
1. Start a new game;
2. Walk over a counter/bench or examine an item;
3. Voila! No compass anymore.

In a video I made to demonstrate #15983 (https://www.youtube.com/watch?v=m4ET-WEG4jA) there are no compass present too, but it is missing from the beginning of the vid.

This is present in **both** Curses and Tiles builds and is not related to issue #15881 (I think?).

**Comment by illi-kun** [comment]
Is #15984 related to this?

**Comment by BFG1992** [comment]
Oh god, I missed it AGAIN. Sorry :(
Next time I will check pull requests too >_<

Will wait till this PR will be merged.

**Comment by lucianposton** [comment]
> Do I need to close this issue? It's kinda not fixed yet, but fix is pending

You can keep it open so others see the issue.

**Comment by BFG1992** [comment]
Ok, thanks :)
