### ISSUE TITLE
Wierd ghosting bug in Cataclysm-Tiles with tiles disabled and custom font settings

### ISSUE THREAD

**Issue by BFG1992** [CleverRaven/Cataclysm-DDA#15983]
I don't know how to explain this in plain text, and it would be hard to in screenshots, so I've made a video of an issue:
https://www.youtube.com/watch?v=m4ET-WEG4jA

Using Cataclysm DDA 0.C-12511-g9ff3363 Windows x64 tiles build.
OS Windows 10, Optimus graphics (tried on both Intel and NVIDIA).

I think it's worth noting that until the latest build (Jenkins #4615) pressing `x` and moving the view to any direction wiped all ghosting present in viewport, until induced again by calling any overlaying menu. Now it's not.

My fonts.json:
```json
{
    "fontblending" : true,
    "fontwidth" : 8,
    "fontheight" : 16,
    "fontsize" : 16,
    "typeface" : "Terminus",
    "map_fontwidth" : 14,
    "map_fontheight" : 14,
    "map_fontsize" : 14,
    "map_typeface" : "Terminus",
    "overmap_fontwidth" : 14,
    "overmap_fontheight" : 14,
    "overmap_fontsize" : 14,
    "overmap_typeface" : "Terminus"
}
```

**Comment by lucianposton** [comment]
Is https://github.com/CleverRaven/Cataclysm-DDA/issues/15881 the issue you're experiencing?

**Comment by BFG1992** [comment]
Ah, really, it is.
Sorry for the duplicate.
Will search through open issues better next time >_<
