### ISSUE TITLE
More loot in garage 

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#15990]
I don't have code blocks installed, but it would be nice to add some stuff to these always empty lockers in garage. I even prepared a list.

>```
    "id" : "clothing_garage",
    "type" : "item_group",
    "items" : [
      { "technician_shirt_blue", 100 },
      { "technician_pants_blue", 100 },
      { "mask_dust", 75 },
      { "gloves_work", 75 },
      { "apron_leather", 70 },
      { "glasses_safety", 60 },
      { "jumpsuit", 40 },
      { "mask_filter", 40 },
      { "ear_plugs", 30 }
      { "wearable_light", 15 },
	]

        m->place_items("clothing_garage", 60, SEEX * 2 - 6, SEEY * 2 - 5, SEEX * 2 - 4, SEEY * 2 - 5, true, 0);

Garage is in mapgen_functions.cpp on line 3496.

**Comment by Coolthulhu** [comment]
It could be, but it should be wrapped in a separate item group. For as long as garage is a hardcoded mapgen function, it shouldn't get "small" item groups. Instead, it could have a "garage" itemgroup that would include both the current item group ("mechanics") and any new item groups.

Though jsonizing the garage wouldn't be too hard.

**Comment by Mshock777** [comment]
I know, that item_group should go in `data\json\itemgroups\clothing.json`, thats why (mugling?) created it.

**Comment by mugling** [comment]
Or following #16061 we should perhaps define a new jumbo welding cylinder with an infrequent chance to spawn there?

**Comment by Mshock777** [comment]
I think there is another empty room in a garage by the way.

**Comment by mugling** [comment]
Sounds good for parts but IRL gas cylinders are often kept in cages/lockers

**Comment by Mshock777** [comment]
![2](https://cloud.githubusercontent.com/assets/8539541/14353126/cd9ec10a-fce8-11e5-8464-0af0f3bc9afb.png)
I mean... there's room, you can put lockers there too.

**Comment by mugling** [comment]
We could really do with converting that mapgen to JSON and then adding some variants.
