### ISSUE TITLE
Autopickup Manager [S]witch option is non-functional

### ISSUE THREAD

**Issue by Rod-Serling** [CleverRaven/Cataclysm-DDA#15998]
Version: Jenkins builds: 4606 (Earliest I checked) -> 4619 (Current as of this bug report) Windows 10 x64 Tiles

In the autopickup manager, there is a indicator that identifies if Autopickup is enabled or not, and next to it is a [S]witch option. Pressing shift-s or s alone does not toggle the status of the autopickup.

Switching autopickup on or off through the options does correctly change the status indicator, but the [S]witch option does not.

**Comment by sethsimon** [comment]
This was fixed by #19627.

**Comment by Rod-Serling** [comment]
Yep, fixed. thanks.
