### ISSUE TITLE
Recipes are no longer autolearned when taking enough skill to know them

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#16002]
When you are taking a skill, it tells you all the recipes you are going to get. But it no longer gives them to you.

On an old copy I had saved, 4275, you take electronics 3, and you can craft all sorts of things, and atomic lamp is one of them.

**Comment by Labtop-215** [comment]
If I understand correctly, stuff like the atomic lamp is a Rive tech company trade secret, isn't it?  It sounds like this may be intentional.

**Comment by Zireael07** [comment]
Is the issue that atomic lamp is uncraftable or that it is wrongly listed?

**Comment by Coolthulhu** [comment]
Granting rare recipes is an important part of the starting skill selection that does a lot to balance crafting skills against useful early game skills like dodging. So it should grant even the secret ones.

**Comment by kevingranade** [comment]
I disagree, some recipes should definitely be only learnable via
interaction in the game world.
