### ISSUE TITLE
Killed by small fire/Fire Nerf Ideas

### ISSUE THREAD

**Issue by karols146** [CleverRaven/Cataclysm-DDA#16015]
I don't know exactly that is a bug, but it's a weird stuff. 
You can be killed by 18 cigarettes laying on ground, when you lit them. 
To reproduce simply drop cigarettes, step on them, and drop lighted cigarette for example.
Starting fire is just normal, but dying from 18 burning cigarettes is just weird.

**Comment by Labtop-215** [comment]
Not really, you stepped into a small fire.  You got caught on fire and died.

The only weird thing here is that you can't stop, drop, and roll.

**Comment by karols146** [comment]
Soo small fire from 18 cigarettes isn't weird ?

**Comment by Coolthulhu** [comment]
Not any more weird than small fire from a single skewer, a single page from a book or a single unit of thread.

**Comment by karols146** [comment]
See that first time, and don't know about that other stuff, so i think that we can just close that.
But if we got it like that, small fire shouldn't kill you, maybe just hurt or damage your shoes. Never heard a dead in fire from one skewer.

**Comment by Labtop-215** [comment]
It might be worth boosting what is considered enough to fuel a small fire before creating one with a a lighter, matchbook, or firedrill.  Then again, where was this fire?  Maybe fires lit on grass should have the potential to light the rest of you on fire or kill you.  Bush fires and forest fires are something that happens in real life.

Basically what you are suggesting is that if you step into a small fire, that it somehow shouldn't spread to your clothing if you stand over it?

**Comment by karols146** [comment]
I am just think that If you step in fire from single page from a book - like Coolthulhu said. You should be fine and just put down the flame maybe or something like that. Dead from that is just ridiculous, but i know that too that this issue can be hard to solve, and it isn't so much important, maybe I try do something myself.

**Comment by Coolthulhu** [comment]
There was a plan (even a PR) to nerf small fire, but it never got finished.

**Comment by karols146** [comment]
It's hard to do or what.
why it got never finished ?

**Comment by kevingranade** [comment]
It has nothing to do with cigarettes, it's a well known issue caused by
only having 3 sized of fire.

**Comment by karols146** [comment]
Just change a name a little, I just thinking about it, and maybe warring window (something like safemode) should pop up when you step in small fire, and ask you "Do you want put down flame". 
Because that small fire would be normally possible to extinguished by just steeping on it.

**Comment by Labtop-215** [comment]
You get a warning from it like you would if you stepped into smoke without a gas-mask, or lava, or a bear-trap.  I just tried it and it doesn't kill you immediately either.
