### ISSUE TITLE
 furniture dragging bug

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#16013]
when moving sideways( not pushing nor pulling) instead of moving the @ character the grabbed furniture moves in the way of the keypress

**Comment by Coolthulhu** [comment]
It's not really a bug, just different behavior.

**Comment by lucianposton** [comment]
Seems okay to me. I just tested this with my couch, and was able to reproduce IRL.

At most, I'd add an additional penalty since it's a slightly tougher maneuver.

**Comment by kevingranade** [comment]
This is intentional in order to let the player position furniture easily.
