### ISSUE TITLE
Make "Really step into X?" movement prompts less obnoxious

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#16016]
The "Really step into the thing in all squares around you? (y/n)" prompts can get obnoxious at times.

To mitigate the pain point, add a way to permanently dismiss prompts of a specific type e.g. never prompt about smoke, but always prompt for fire & acid. This could simply be another key e.g. "(y/n/A)"

Anyone have other ideas to address this issue?

**Comment by karols146** [comment]
Maybe just make it possible to turning of like safe mode ?

**Comment by FlaKougar** [comment]
A good choice might be Y is remembered a short period of time (10 turns)  Let's you get away, resets without you needing to think about

**Comment by lucianposton** [comment]
Some others in irc were suggesting an approach like safe mode, where you can temporarily disable prompts for a period of time until the object leaves the screen. For example, after you've temporarily dismissed smoke prompts, they will not disturb you until after there no longer any smoke on screen.
