### ISSUE TITLE
User-installable Mods: Install soundpacks/gfxpacks/mods w/o modifying system files (or compiling)

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#16023]
A user who has normally installed CDDA (not compiled) has no way to add
soundpacks, gfx packs, or mods to the game without mucking with system
directories e.g. manually adding files to /usr/share/cataclysm-dda.

I propose loading mods and packs from the user's directory. This directory
already exists (and varies across platforms and compile-time flags), so we
could simply add folders to it to help users understand where to install mods
they've downloaded.

To be clear, the use case here is that the user wants to install additional
gfx packs, sound packs, and/or mods to the game installed on the
system where the user cannot (or doesn't want to) modify system files e.g.
/usr/share/cataclysm-dda/mods. This is distinct from modders who may
want to modify or overwrite existing mods/packs.

My proposal to solve this issue: https://github.com/CleverRaven/Cataclysm-DDA/pull/15836

**Comment by Leland** [comment]
I sure hope this gets implemented at some point! The soundpack installation process right now seems *very* hacky.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
