### ISSUE TITLE
Some clothing is unwearable¹ if it is in furniture and you only have one arm

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#16034]
¹ Except for through Advanced Inventory Manager. Or by wielding something else. Or by smashing the dresser. Still, you should be able to wear them out of the dresser.

I noticed that you if you pick up clothing with nothing in your hands, you wield it, instead of wearing it, like you used to.

So, I did something I had been wanting to do for a long time. I made a tileset where everything is wieldable: http://www.chezzo.com/cdda/ChestHole32TilesetWieldEverything.zip

When you break one your arms, and are in an incredible amount of pain and are just looking for the tender embrace of your snuggie and leather pants however, you either have to wield something else, or use the Advanced Inventory Manager to put them on. Or smash it.

**Comment by Rivet-the-Zombie** [comment]
>So, I did something I had been wanting to do for a long time. I made a tileset where everything is wieldable

This is cool! You really should add it to your current tilesets.

**Comment by Skidborg** [comment]
A bit tangential to this issue, the fact that it auto-wields clothing you pick up can make life unexpectedly dangerous if you weren't ready for the extra standing-around time for a bulky piece of gear.

**Comment by kevingranade** [comment]
Seems to have been fixed at some point.
Spawned a character, got a friendly zombie to break one of his arms, dropped all storage-providing items, put some pants in a dresser, then 'e'xamined dresser and selected pants.  It gave me a prompt to either wield or wear, choosing wear worked.
