### ISSUE TITLE
Automatically adjusting windows to screen size

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#16038]
We have lots of free space in some windows, examples are Create World, Create Character, Sort Armor, and others.

![3333](https://cloud.githubusercontent.com/assets/11132525/14231997/a3d82326-f9a9-11e5-945f-54ddc3ccf884.png)

Will it take too much effort to make these windows auto-adjustable, like Crafting Menu, for instance?

**Comment by illi-kun** [comment]
It's not so difficult but I'm not sure we need to expand all windows in the same manner.

**Comment by illi-kun** [comment]
This issue is very similar to #7103.

**Comment by illi-kun** [comment]
Closing as a duplicate.
