### ISSUE TITLE
SDL rendering bug with different font sizes

### ISSUE THREAD

**Issue by MattAmmann** [CleverRaven/Cataclysm-DDA#16033]
When the map font size differs from the interface font size, the screen does not refresh properly. This manifests itself after closing a UI window, and is almost unplayable as a result. I encountered the bug myself, and it is confirmed by Beanzy in [this forum thread](http://smf.cataclysmdda.com/index.php?topic=12345.0). 

The issue does not occur when using the same font height & font width settings as your map_fontwidth and map_fontheight.

Here is what is inside my fonts.json file:
`{
    "fontblending" : false,
    "fontwidth" : 8,
    "fontheight" : 16,
    "fontsize" : 16,
    "typeface" : "Terminus",
    "map_fontwidth" : 16,
    "map_fontheight" : 16,
    "map_fontsize" : 16,
    "map_typeface" : "whitrabt",
    "overmap_fontwidth" : 16,
    "overmap_fontheight" : 16,
    "overmap_fontsize" : 16,
    "overmap_typeface" : "Terminus"
}`

The only workaround I have come up with so far is to open and close the map, which forces a complete screen redraw. 

Reproduction Steps:
1) Open the inventory
2) Select an item
3) Press Escape twice to get back to the map
4) Examine any tile

**Game Options**
Display: Tested on all three display modes
Use Tiles: False
Software Rendering: Tested on both modes

**Details**
Build: Tiles 0.C-4624 (pre-compiled binary on 4/2/2016)
Platform: Windows 7 x64
Screenshot:
![2016-04-02 - 10_02_32pm](https://cloud.githubusercontent.com/assets/193401/14230334/d72c77b6-f91f-11e5-8f27-815cddaeeb02.png)

**Comment by lucianposton** [comment]
dupe of https://github.com/CleverRaven/Cataclysm-DDA/issues/15881 ?

**Comment by MattAmmann** [comment]
This looks to be a duplicate, yes. I searched open issues before submitting, but didn't find that one.
