### ISSUE TITLE
Coloring issue in Sort Armor menu

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#16036]
Items that can be worn on left or right side of the body are still coloring both of these sides in Sort Armor menu.
![1111](https://cloud.githubusercontent.com/assets/11132525/14231829/37780ac6-f9a3-11e5-858e-b680ce0c49af.png)

Win 10 x64, tiles, 0.C-4626.

**Comment by illi-kun** [comment]
I'm on it.
The issue is in ```void player::print_encumbrance()```.

**Comment by illi-kun** [comment]
Okay, deleting of ```selected_clothing->covers( static_cast<body_part>( bp_aiOther[bp] ) )``` in [player.cpp#L13507](/CleverRaven/Cataclysm-DDA/blob/master/src/player.cpp#L13507) fixes the issue but it seems to be intentional condition. I'll try to do further investigation.

**Comment by illi-kun** [comment]
Okay, #14772 changes these lines, and [this comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/14772#issuecomment-170328789) states the exactly the same issue as noted in the current issue description.
