### ISSUE TITLE
MBR vests weight less than their components

### ISSUE THREAD

**Issue by EditorRUS** [CleverRaven/Cataclysm-DDA#16043]
You can assemble and disassemble MBR vests.
2 superalloy platings weight 21.6 kg and are used to craft MBR vest (superalloy). MBR vest (superalloy) weights only 8.5 kg.
http://i.imgur.com/l8MV7Xh.png
http://i.imgur.com/ieThgF0.png

**Comment by Mshock777** [comment]
Also 2 `superalloy plating` =/= 8 `superalloy sheet` in terms of weight.

**Comment by jcd000** [comment]
I always assumed that you cut the platings in order to fit into the vest and throw the leftovers. Not quite 21.6 - > 8.5 kg though, and it does not explain why the platings can be used as such after dissasembling the vest though.

**Comment by kd8qdz** [comment]
All the vests are messed up in some way.
https://docs.google.com/spreadsheets/d/12jOEze54stW4qYYuQdDL4Yq8K3hxk7kGIFt6DL3FIvo/edit?usp=sharing

**Comment by kd8qdz** [comment]
So what do we want to do about this?

(can we add the discussion label to this issue?)

**Comment by kd8qdz** [comment]
It was noted in the IRC channel that its odd/unreasonable to require two steel plates to armor a person, when one can armor an entire vehicle section.   It was suggested that the pieces for the armor vests be craftables steel_armor_inserts or something.  This does require creating new components.

**Comment by Mshock777** [comment]
We can decrease requirements to 1 plate. But I see no point in creating new items just for vests.

**Comment by kd8qdz** [comment]
Conceptually, a steel plate big enough to armor a significant part of a car is much much larger than the plates used in vests.   Unless another item already exists in the game, I can't see how we have any choice but to add new items, or change how the MBR vests work significantly.

**Comment by Mshock777** [comment]
Vest volume is 24, plate volume is 12. If anything is needed to be tweaked, it is amount of plates used for vehicle construction.

**Comment by kd8qdz** [comment]
Nope that wont fix it because this issue is about _weight_ not volume. Making it one plate still would make the disparity less, but it would still be a disparity.   Not to mention, its only a fix for a few of the vests.  Some of them use a bunch more plates.   Did you look at the spreadsheet?

**Comment by Mshock777** [comment]
I'm pretty sure no one is stopping from tweaking as many numbers as you want. You can play around with weight, volume, amount of plates all at the same time.

**Comment by kevingranade** [comment]
Smaller plate for MBR is fine, including allowing a number of the smaller plates to be used for vehicle plating, but I'm closing this as the last conversation was almost a year ago.
