### ISSUE TITLE
Free gas or hydrogen if you add to a tank on your car, remove it, and unload it

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#16051]
If you have a car with a tank on it, then fill the tank with 10 units, then remove the tank from your car and unload it, it produces 1,000 units of whatever you had in the tank.

**Comment by EditorRUS** [comment]
This bug is long gone. Update to experimentals.

**Comment by Chezzo** [comment]
Aww, YOU told me about it! Alright, I will close this.
