### ISSUE TITLE
Small change to the "unwield" menu.

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#16069]
Would it be possible to assign  the letters w (store in inventory), d(drop), and h (holster) for the three options in the menu?

So you can simply double tap "w" to wield different stuff. Making the menu navigation faster/unnoticeable for what I imagine is the most common scenario.

**Comment by Coolthulhu** [comment]
Sounds good. Could actually get the bindings too (similar to butchery getting the 'B' as "butcher first corpse").

The holster part is ambiguous, though. Which holster? Always the first one?

**Comment by John-Candlebury** [comment]
>The holster part is ambiguous, though. Which holster? Always the first one?

My bad, the actual last option in the menu is "wear item", in which case having "h" as a binding wouldn't make much sense. The binding "W" could be used instead.

Being able to holster stuff from that menu would be nice, but unrelated, addition.

**Comment by lucianposton** [comment]
May want to just use the input_context for the menu so that people can reassign hotkeys to whatever they want via the ? help menu that you get for free with input_context.

**Comment by Leland** [comment]
Looks like discussion has stalled on this suggestion. Closing. If there's still interest, let me know and I can reopen.
