### ISSUE TITLE
Blinded characters are still able to see working console and interact with it

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#16060]
![4444](https://cloud.githubusercontent.com/assets/11132525/14247264/088d6586-fa7e-11e5-8eba-2a830a2cded1.png)

Win 10 x64, tiles, 0.C-4632.

**Comment by nanovad** [comment]
Being able to see it is probably a feature™, because it's just listed as "bright light" when using X to look around. As for interacting with it... I'd say that's a bug.

**Comment by illi-kun** [comment]
Any other opinions about visibility of working console for blind characters (feature or bug)?

**Comment by Night-Pryanik** [comment]
Should be closed, I think.
