### ISSUE TITLE
[Spoiler] Canon Check:  Containment Procedures and Rampant AI

### ISSUE THREAD

**Issue by acidia** [CleverRaven/Cataclysm-DDA#1607]
Containment Procedures and Rampant AI

For all researchers that still have access to the Melchior Research Mainframe, follow this publication and distribute the information contained to all contractors and federal employees.  

At the beginning of the outbreak necessary measures were taken to contain the spreading of the sub-prime mutagens and fauna.  It was during this time that a number of mistakes were made by scientists relying on flawed theories concerning the spread of the mutagen and the state of carriers.  Most AIs controlling security and military protocols were first instructed to kill the re-animated and sub-prime fauna when encountered.  This was successful to a limited degree but as individuals who were not believed to be infected were found to re-animate, a more stringent algorithm for determining infection was created.  Without sufficient testing, the new analysis algorithm correctly identified almost everyone as infected.  The nearly instantaneous massacre resulted in numerous disabled labs and scattered any remaining staff that may have been capable of reversing the update.  It must be made known that this massacre was not intentional and that contractors and federal employees are being asked to remain faithful to their original contracts.  We need every bit of help to implement emergency procedures and recover what resources remain.

Any lab that is still operational, to any degree, is requested to send word on the Melchior network so that assistance can be distributed and resources can be accounted for. 

[Sorry, I have no idea why these things won't format correctly...]
[Note:  These are for the scientist mission tree... or anyone else who happens to break into the Melchior network in the data lab room]

**Comment by qbradq** [comment]
Given that this question contains no feature requests can we close the issue?

**Comment by narc0tiq** [comment]
Can do, and thank you.
