### ISSUE TITLE
List all items around the player

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#16077]
I only now noticed that doesn't list all visible items, but only ones that are in certain range (29?), can it be customized?
Also this area is rectangular, and distance to the item seems to be the largest from vertical and horizontal distance.

**Comment by kevingranade** [comment]
Outside of it making updates too slow, there's no good reason to artificially limit it more than what you can see with "look_around", although now that I think of it, you can't see things in detail there either.
