### ISSUE TITLE
Bad, unupdated and weird alcohol recipes

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16081]
Discovered while testing #16044 

* Vodka, rum and whiskey are made from wort, which needs to be distilled in a still, THEN set to ferment. Then it ferments into distilled alcohol.
* Moonshine mash is crafted in a similar way, plus it specifies the still explicitly (rather than requiring distillation quality) and allows V6 and V8 engines to work as a still. This is way too specific, non-standard and not worth keeping just for a reference to some weird practice. Adding weak distillation ability to those engines could work, "makeshift still" crafted from them could work, but keeping them like that is just asking for keeping it unupdated and ignored for years
* Tainted tornado doesn't allow hotplates and is specific enough not to really be craftable until it's no longer useful. Should probably allow any strong alcohol or maybe just pure ethanol.
* Cheap wine must is incredibly hard to craft. Seriously, "craft cheap wine must in a 1.0 item spawn world" would be harder than most DDA challenges I've seen (including ones like "spawn 9 jabberwocks on self, kill them and survive"). Plus, it is fortified before it ferments, which sounds like a good way of guaranteeing it would not ferment, except maybe into vinegar.

**Comment by mugling** [comment]
Brewing is indeed a spectacular mess.

> but keeping them like that is just asking for keeping it unupdated and ignored for years

Removing recipes does have the advantage it doesn't break any existing saves

**Comment by Kordian459** [comment]
Is baking yeast actually usable for brewing purpose IRL?

**Comment by mugling** [comment]
Yes and in any case multiple types of yeast isn't likely to add much from a gameplay perspective.
