### ISSUE TITLE
Crafting Cooking oil causes the program to become non responsive.

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#16094]
0.C-12726-gcfc59e9
Win x64

Save directory:
https://mega.nz/#!qwFlgYoJ!QkVdKwRwRlDdBYY6PX5j9BE-bJzfGwvfW-7MBtORSRw

When I craft cooking oil, it does not show any containers I have in my inventory or nearby.  This results in me having to dump the oil on the floor, which crashed the game.  I don't get any debug messages.

It does, however show the container if I hold it.  If I put it into a held container, ie a gallon jug, I get a "Gallon jug of cooking oil" with no listed amount. 

Wishing for cooking oil results in  "cooking oil (0)", or "Gallon jug of cooking oil" if I wish for it in a container.

Neither shows up in my crafting menu as usable.

I have tried making a new world with new survivor, same results.

**Comment by WizardOfOoo** [comment]
Updated to 0.C-12756-gf2fb560.  Tried different PC, same bug, still crashes when I dump the oil.

**Comment by WizardOfOoo** [comment]
I bet it has something to do with the strangeness here.
![image](https://cloud.githubusercontent.com/assets/17521661/14374365/7e76dd38-fd1a-11e5-894e-41da08f45829.png)

**Comment by Zireael07** [comment]
Is it the only liquid to have this strangeness?

**Comment by Coolthulhu** [comment]
I think I found it:

ae7e366 removes charges from cooking oil. Default charges are 0, not 1.

**Comment by mugling** [comment]
I'm working on a PR that makes `charges: 1` the default so that should resolve this issue

**Comment by Rivet-the-Zombie** [comment]
It's also supposed to be two charges per volume, not one.
