### ISSUE TITLE
Incorrect description when a character is bumping into car

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#16095]
![2222](https://cloud.githubusercontent.com/assets/11132525/14341911/aa1ed5d6-fca6-11e5-8cc3-1cc16d05db3c.png)
I'm blind, and there is a car with headlights turned on to the south of me. When I'm going south, there is a message like in pic above. I suppose there should be description of car's part, not a terrain.

**Comment by illi-kun** [comment]
Easily reproducible with a blindfold.
