### ISSUE TITLE
unloading a flamethrower does not remove fuel in it

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#16107]
i have 3000 gasoline in my flamethrower and then i unloaded them and poured the gas on the ground but i still have 3000 gas in the flamethrower

**Comment by illi-kun** [comment]
Confirmed.

**Comment by mugling** [comment]
Can reproduce, tagged `magazine` as involves the reloading code

**Comment by mugling** [comment]
Only occurs when pouring out to adjacent tiles
