### ISSUE TITLE
"Bag of cotton ballss"

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16111]
Missing "name_plural" maybe?

**Comment by Bubbadoo** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/16114 I went ahead and did it. I _think_ I did it right, correct? This is the first time I have had to work GitHub.

**Comment by Night-Pryanik** [comment]
@Bubbadoo yeah, you did it right.

**Comment by EditorRUS** [comment]
It seems Cata has problems with uncountable nouns including but not limited to drugs, fuel, ammo(?), substances in general. Thorazines, Adderals, Gasolines and stuff.

**Comment by illi-kun** [comment]
Yeah, I've shown some weird plural names in the snapshot in #15381.

**Comment by illi-kun** [comment]
This issue should be closed because a proper fix in PR #16114 was landed.
