### ISSUE TITLE
Translated scenario string is not loaded at character creation screen.

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#16127]
The scenario name/description/start location are still in English.

Tested with 100% translated Chinese(Simplified) .mo file.
![a](https://cloud.githubusercontent.com/assets/4143592/14377683/a24bf07a-fda3-11e5-9018-955286161e14.jpg)

0.c-12763-g100d5bd ,windows

**Comment by cainiaowu** [comment]
![a](https://cloud.githubusercontent.com/assets/4143592/14377648/7f7929fa-fda3-11e5-81e5-e36131597167.jpg)

**Comment by lucianposton** [comment]
Looks like the msgctxt's are missing from the po's for the scenarios
