### ISSUE TITLE
Mouth warmth not showing up.

### ISSUE THREAD

**Issue by Ygdrad** [CleverRaven/Cataclysm-DDA#16122]
I'm not sure if this happens under all circumstances, but on my current character, despite wearing a long patchwork scarf, the mouth has 0 warmth despite the scarf claiming to offer 20. Here is my current save file to help figure this out http://www.filedropper.com/save
Edit: Having the same issue with a ballistic mask, this may have something to do with a recent mouth flap mutation, but not sure why the mouth can be covered but still not get warmth. After equipping more stuff on the mouth, the warmth remained 0, but the temperature went up.

**Comment by kevingranade** [comment]
Is your character cold? Some clothes will only supply warmth when needed,
the player is assumed to be adjusting them to stay comfortable.

**Comment by Ygdrad** [comment]
He was. This seems to affect most body parts, they seem to be warmed up properly, but the armor sorting/reordering screen(+) is currently showing me 0 warmth on most body parts despite plenty of clothes.
