### ISSUE TITLE
Character moves at full speed even if both legs are broken

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#16130]
currently movement speed depends on stamina and encumberance and not the status of legs this effectively makes you crawl at walking speed

**Comment by Night-Pryanik** [comment]
Well, in my testing there was a decrease in speed with both legs broken, but 'twas rather small (from 100 to 88).

**Comment by karols146** [comment]
I think that with two legs broken crawling should be only way to move.

**Comment by illi-kun** [comment]
It's probably duplicate of #11116.

**Comment by illi-kun** [comment]
... and #1941.

**Comment by DLaboratory** [comment]
= =
OLD BUG SINCE 2013

**Comment by illi-kun** [comment]
Closed as a duplicate.

**Comment by mugling** [comment]
I had a run at closing a lot of open issues a month ago but couldn't get the total open issues below 1000. Further such attempts would be very useful

**Comment by illi-kun** [comment]
Yeah, your attempts inspired me to start checking the old issues.
