### ISSUE TITLE
Vegetable sandwich made with wastebread turns to flatbread once disassembled

### ISSUE THREAD

**Issue by Kordian459** [CleverRaven/Cataclysm-DDA#16137]
I made some vegetable sandwiches using wastebread + vegetable aspic. Inspecting them through inventory mode the game says they can be disassembled and yield 2x flatbread and 1x cooked plant marrow. Can confirm you can turn wastebread into flatbread, I guess it can happen with cornbread and bread too.

Same goes for vegetable ingredient: you can turn something like pine nuts or veg. aspic into cooked plant marrow.

**Comment by karols146** [comment]
Confirmed in 0.C-12802-g1f2abca. So disassemble sandwiches need more checkout before proceed.
