### ISSUE TITLE
Food/vitamins balancing (fruit)

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#16135]
Follows  #16118.

I'd like to go with @Coolthulhu's suggestion that `healthy` affects absorption of vitamins from a foodstuff. We have a very large number of food items already defined so my intention is to break them into similarly themed groups. This issue is a request for comments about fruit.

As items are migrated they will use the new `calories` field along with typical `weight` which should provide differentiation between items in addition to recipes that require specific fruit(s).

The overall balance is to provide common fruits, slightly better but rarer exotic fruits, forageable but perishable berries and valuable storable fruits.

### Common fruit
* Readily available
* Spoils in 10 days
* Smallest `fun` and `quench` values
* `orange` and `lemon` have unique values

|          | vol | charges | spoils | healthy | fun | quench
|--------|-----|---------|--------|---------|-----|-------
| apple | 1 | 1 | 240 | 1 | 2 | 2
| banana | 1 | 1 | 240 | 1 | 2 | 2
| grapes | 1 | 2 | 240 | 1 | 2 | 2
| lemon | 1 | 1 | 240 | 1 | -4 | 2
| orange | 1 | 1 | 240 | 1 | 2 | 8
| pear | 1 | 1 | 240 | 1 | 2 | 2

### Exotic fruit
* Less frequently available
* Shorter shelf-life (spoils in 5 days)
* Improved `fun` and `quench` values

|          | vol | charges | spoils | healthy | fun | quench
|--------|-----|---------|--------|---------|-----|-------
| apricot | 1 | 1 | 120 | 1 | 4 | 4
| cherries | 1 | 1 | 120 | 1 | 4 | 4
| kiwi | 1 | 1 | 120 | 1 | 4 | 4
| mango | 1 | 1 | 120 | 1 | 4 | 4
| melon | 1 | 1 | 120 | 1 | 4 | 4
| plums | 1 | 1 | 120 | 1 | 4 | 4
| papaya | 1 | 1 | 120 | 1 | 4 | 4

### Berries
* Frequently available including via foraging
* Much reduced shelf life spoiling in 2.5 days
* Two `charges` and higher `healthy` makes for good vitamin source preventing deficiency

|          | vol | charges | spoils | healthy | fun | quench
|--------|-----|---------|--------|---------|-----|-------
| blackberries | 1 | 2 | 60 | 2 | 4 | 4
| blueberries | 1 | 2 | 60 | 4 | 0 | 4
| cranberries | 1 | 2 | 60 | 4 | 0 | 4
| raspberries | 1 | 2 | 60 | 2 | 4 | 4
| strawberries | 1 | 2 | 60 | 2 | 4 | 4

### Storage fruits
* Equal rarity to exotic fruits
* Markedly extended shelf life spoiling in 10 days
* Good stats compared to common fruit
* Two charges to offset `volume 2`

|          | vol | charges | spoils | healthy | fun | quench
|--------|-----|---------|--------|---------|-----|-------
| coconut | 2 | 2 | 240 | 1 | 8 | 12
| pineapple | 2 | 2 | 240 | 1 | 8 | 8
| pomegranate | 2 | 2 | 240 | 1 | 4 | 4

**Comment by Coolthulhu** [comment]
I don't like how uniform they look. Categories themselves are OK, but they could use more variance inside the categories.

I see it like this:
* Less quench and more nutrition for sweet fruit like bananas, strawberries, pineapples
* Divide berries into sweet (higher nutrition and fun) and sour (healthier)
* Move banana, grapes and lemons to exotic, cherries and plums to common, then we have a clear split between common (spawns after start) and exotic (stops existing after a while)
* Give melon more charges, make it proportionally more rare
* Make pineapple and pomegranate more healthy, coconut more nutritious, all of them more rare
* Small fruit like lemons, grapes, plums, kiwis etc. could get better charge/volume ratio, possibly offset by lower stats
* I'd make the baseline healthy value higher than 1. Health values are currently incredibly subtle, you need to drink alcohol by gallon to really affect your health. At 2 health per 10 nutrition, you'd most likely stabilize around 10 health even if you got a diet made of healthy berries

**Comment by mugling** [comment]
> I don't like how uniform they look.

Weight and calories provides some significant variation

> Divide berries into sweet (higher nutrition and fun) and sour (healthier)

Sounds good. I'd prefer variation that makes items markedly different rather than just +1/-1 just because.

> Move banana, grapes and lemons to exotic, cherries and plums to common, then we have a clear split between common (spawns after start) and exotic (stops existing after a while)

Each new reality bubble starts with unspoilt food? Also why this particular split?

> Give melon more charges, make it proportionally more rare

Yes

> I'd make the baseline healthy value higher than 1.

What would be a good baseline value?

**Comment by Coolthulhu** [comment]
> Each new reality bubble starts with unspoilt food?

Nope. Food spawns pre-spoiled. After ~10 days, all the food I'd define as exotic would be only available in irradiated varieties, while your current split would make it so that some exotic food would be available long after all imports stop.

I forgot apricots - those grow in the wild too.

> Also why this particular split?

Because then "exotic" would mean "imported, doesn't grow here", while "common" would mean "it grows in the wild around here", which would be pretty close to "intuitive definitions" of "exotic" and "common" that most people have.

Also, lemons and oranges have non-food uses and taste different to common fruit and closer to exotic.

**Comment by Coolthulhu** [comment]
> What would be a good baseline value?

That depends on nutrition.

Some uniform standard could be good here. For example, healthy food gets 33% of nutrition as health, very healthy gets 50%. Calories are worth `~1/9` nutrition, so 5% for moderately healthy and 7.5% for healthy?

Health system isn't tightly balanced. In fact, it is nearly impossible to get wildly varying values from food alone right now, meaning it can be safely shaken up and destabilized.

**Comment by mugling** [comment]
> After ~10 days, all the food I'd define as exotic would be only available in irradiated varieties

Ok, makes sense but I'll probably proportionally increase spoilage times for all the fruit if each reality bubble is pre-spawned.

**Comment by mugling** [comment]
> Health system isn't tightly balanced. In fact, it is nearly impossible to get wildly varying values from food alone right now, meaning it can be safely shaken up and destabilized.

How does it currently work in summary?

**Comment by Labtop-215** [comment]
> How does it currently work in summary?
Nom on vitamins before going to sleep for good health, drink tons of hard liquor if you want bad health.

Elsewise, eating junkfood over long periods of time will hurt your health too, but not as badly.

**Comment by Coolthulhu** [comment]
> How does it currently work in summary?

There are two values: actual health and health mod. Health mod is the one affected by food. If `health_mod - health > rng(-100,100)`, health is incremented, otherwise decremented. Then health mod is multiplied by 75%.

This happens every 30 minutes or so.

Due to how stable it is, getting it outside `[-30, 30]` range requires hardcore drug abuse, vitamins or CBMs. Achieving it with food would require gorging way past the point of vomiting.

**Comment by kevingranade** [comment]
On Apr 8, 2016 2:01 PM, "mugling" <notifications@github.com> wrote:
>>
>> After ~10 days, all the food I'd define as exotic would be only
available in irradiated varieties
>
> Ok, makes sense but I'll probably proportionally increase spoilage times
for all the fruit if each reality bubble is pre-spawned.

Why? It should be fairly easy to look up how long different types of fruits
take to spoil (hint, not long), so just use that.

**Comment by Zireael07** [comment]
I like the way you're thinking, @mugling, but slightly more variety would be nice as @Coolthulhu pointed out.

**Comment by Night-Pryanik** [comment]
There are also peaches, watermelons and grapefruits.

**Comment by John-Candlebury** [comment]
Should also factor possible canned fruit variants.

I think those even come in vitamin enriched versions sometimes.
