### ISSUE TITLE
Barrel length modifications should probably not be permanent alterations for some guns

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#16140]
Apparently the `shortened barrel` weapon mod is now a permanent modification to guns (e.g. a `SCAR-H` modified with a `shortened barrel` becomes a `sawn-off SCAR-H`), but that doesn't mirror reality for some modern rifles.

For example, a [real-world SCAR-H's](http://www.americanspecialops.com/special-ops-weapons/mk17-scar.php) "barrels are designed to be easily exchanged".

**Comment by mugling** [comment]
This has come up previously with the consensus being that we should support changeable barrels
