### ISSUE TITLE
Firefighter helmet has no fire protection

### ISSUE THREAD

**Issue by Ygdrad** [CleverRaven/Cataclysm-DDA#16153]
The firefighter helmet has 0 fire protection and does not protect the face or eyes at all. a lot of models also have a visor of some sort that can be either attached or flipped to protect the face.

https://en.wikipedia.org/wiki/Firefighter's_helmet#F1_helmet

**Comment by karols146** [comment]
That can be harder than it looks. For what i find for now, I don't see any exactly fire protection implemented in code. Only Environmental protection with is just a general stat.

**Comment by Coolthulhu** [comment]
Protection values are based on materials. Fire helmet would need to get nomex material or something like that. That would lower its physical protection, though.

**Comment by kevingranade** [comment]
What are they made if IRL?

**Comment by codemime** [comment]
Mostly of fibreglass composite (for solid parts) and nomex/kevlar (for straps and soft heat shields).
Source: http://us.msasafety.com/Head-Protection/Fire/Helmets/Cairns%26reg%3B-1044-Traditional-Composite-Fire-Helmet/p/000360000200001003

**Comment by Zireael07** [comment]
So adding nomex would be a good fix.

**Comment by Night-Pryanik** [comment]
>So adding nomex would be a good fix.

Not only that, but replace steel as material to something more fiberglass-y (plastic? kevlar?)

**Comment by Ygdrad** [comment]
material thickness could be modified to keep some of its physical protection.
