### ISSUE TITLE
Cygwin compilation issues

### ISSUE THREAD

**Issue by Salganos** [CleverRaven/Cataclysm-DDA#16154]
The makefile indicates that nothing special needs to be appended to "make" with Cygwin, and COMPILING.md gives no instructions involving Cygwin.

Attempting to make eventually results in:

g++  -DCATA_NO_CPP11_STRING_CONVERSIONS -DGIT_VERSION -DLOCALIZE -ffast-math -Og -Wall -Wextra -g  --std=c++11 -MMD -c src/translations.cpp -o obj/translations.o
src/translations.cpp: In function ‘void set_language(bool)’:
src/translations.cpp:48:56: error: ‘setenv’ was not declared in this scope
         if( setenv( "LANGUAGE", lang_opt.c_str(), true ) != 0 ) {

Adding `#undef LOCALIZE` to translations.cpp gets me around that one, but then I eventually get:

g++  -o [...] -lncurses -lintl -liconv
obj/mod_manager_ui.o: In function `mod_ui::get_information(MOD_INFORMATION*)':
/home/Salganos/Cataclysm-DDA/src/mod_manager_ui.cpp:89: undefined reference to `pgettext(char const*, char const*)'
/home/Salganos/Cataclysm-DDA/src/mod_manager_ui.cpp:89:(.text+0x25a4): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `pgettext(char const*, char const*)'
/home/Salganos/Cataclysm-DDA/src/mod_manager_ui.cpp:105: undefined reference to `pgettext(char const*, char const*)'
/home/Salganos/Cataclysm-DDA/src/mod_manager_ui.cpp:105:(.text+0x295b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `pgettext(char const*, char const*)'
obj/main_menu.o: In function `game::opening_screen()':
/home/Salganos/Cataclysm-DDA/src/main_menu.cpp:225: undefined reference to `pgettext(char const*, char const*)'
/home/Salganos/Cataclysm-DDA/src/main_menu.cpp:225:(.text+0x2156): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `pgettext(char const*, char const*)'
/home/Salganos/Cataclysm-DDA/src/main_menu.cpp:226: undefined reference to `pgettext(char const*, char const*)'
/home/Salganos/Cataclysm-DDA/src/main_menu.cpp:226:(.text+0x21c8): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `pgettext(char const*, char const*)'
/home/Salganos/Cataclysm-DDA/src/main_menu.cpp:227: undefined reference to `pgettext(char const*, char const*)'
/home/Salganos/Cataclysm-DDA/src/main_menu.cpp:227:(.text+0x223a): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `pgettext(char const*, char const*)'
obj/main_menu.o:/home/Salganos/Cataclysm-DDA/src/main_menu.cpp:228: more undefined references to `pgettext(char const*, char const*)' follow
obj/main_menu.o: In function `game::opening_screen()':
/home/Salganos/Cataclysm-DDA/src/main_menu.cpp:228:(.text+0x22ac): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `pgettext(char const*, char const*)'
/home/Salganos/Cataclysm-DDA/src/main_menu.cpp:229:(.text+0x231e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `pgettext(char const*, char const*)'
/home/Salganos/Cataclysm-DDA/src/main_menu.cpp:230:(.text+0x2390): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `pgettext(char const*, char const*)'
/home/Salganos/Cataclysm-DDA/src/main_menu.cpp:231:(.text+0x2402): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `pgettext(char const*, char const*)'
/home/Salganos/Cataclysm-DDA/src/main_menu.cpp:232:(.text+0x2474): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `pgettext(char const*, char const*)'
/home/Salganos/Cataclysm-DDA/src/main_menu.cpp:233:(.text+0x24e6): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status

I have installed gettext in on Cygwin, and have no idea what this is actually looking for.  Some instructions would be helpful.  Or some advice.

Advice like whether I should delete Cygwin from my hard drive and use MSYS2 instead.  >.>  (Yes I am aware MSYS2 sort of runs on Cygwin.)

**Comment by lucianposton** [comment]
Maybe gettext libraries were compiled without -fPIC? Not sure where the library is installed offhand, but if `objdump -r` returns more than the filetype e.g. it gives you offsets for R_X86_64_32 or similar, it probably wasn't compiled with -fPIC. `objdump -r /usr/lib/libintl.so` might work.

You might also try passing the gcc  parameter -mmodel=large 

If that doesn't work, try passing LOCALIZE=0 to make to avoid linking gettext all together.

**Comment by Salganos** [comment]
I'm fairly sure I've given up with Cygwin.  I've almost given up with MSYS2.  I'm becoming upset with CodeBlocks.

I like programming, but compilation pipelines make me very unhappy.

**Comment by karols146** [comment]
What Gcc pacages you use ?

**Comment by Salganos** [comment]
With Cygwin, the ones that come with Cygwin.  With MSYS2, the ones listed in COMPILE.md.  With CodeBlocks, mingw-w56, which finally worked.

I still want MSYS2 to work, since I like command-lines, and it might facilitate testing and pushing commits to branches, so that I can maybe contribute things.

**Comment by karols146** [comment]
I think that problem cause Gcc-core 5.3.0-3, when i update to that, got some weird errors too. 
Just try use 4.9.3-1 like me and it should compile without any problem. 
Just remember to set up Gcc-C++ compiler to 4.9 too

**Comment by Salganos** [comment]
Interestingly, that solved the Cygwin issues.  All of them.  Thanks!

**Comment by Griffinhart** [comment]
Hmm.

```
Griffinhart@Joyeuse ~
$ gcc --version
gcc (GCC) 4.9.3
```

Builds fine on my machine as well. I wasn't aware 5.3 was out yet; I'll update on my end when I can and see what explodes.
