### ISSUE TITLE
What is savegame_legacy.cpp

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#16176]
Is this dead code?

**Comment by DanmakuDan** [comment]
It appears to handle loading/conversion of old save files into the current version, when overmap saving was JSON based and item saving was doing whatever it is doing in there.

**Comment by mugling** [comment]
One of the last remaining calls to `set_curammo` is contained within it. Is there any need to refactor or just drop the caller entirely?

**Comment by kevingranade** [comment]
Code in savegame_legacy can be removed after determining that it is old
enough, the current goal is to load saves generated by the latest stable
release, so a lot of savegame_legacy can go away after 0.D.
There is likely some stuff in there to support 0.B or even 0.A, if that's
the case it can be re moved now

**Comment by DanmakuDan** [comment]
I've been digging, it looks like that item loader expects something from before NPCs were saved as JSON, which is somewhere before September 2013.
