### ISSUE TITLE
NPCs with flamethrower drop a jerrycan of gasoline upon spawning

### ISSUE THREAD

**Issue by flitvious** [CleverRaven/Cataclysm-DDA#16187]
It seems that they spawn with ammo for their weapon, and then drop it because of volume or weight.

Reproduced this through debug menu, but originally noticed it by finding four jerrycans of gasoline on a single tile near a refugee center.

![image](https://cloud.githubusercontent.com/assets/7687709/14496801/1ad6bcf8-019d-11e6-8c2a-845401b2579a.png)

**Comment by mugling** [comment]
I suspect I know the cause of this but I'm not sure what the most appropriate fix is. Either we can special case for `gasoline` ammo but it's tempting to propose instead that the NPC inventory code only generates items limited by the amount an NPC can actually carry?

**Comment by Coolthulhu** [comment]
I'd just remove flamethrower NPCs. Nobody likes those anyway, plus their flamethrowers are uncraftable and really hard to acquire through other means.

The bug started happening when gasoline container was changed from plastic bottle to jerrycan. Then NPCs started spawning with 40 times as much gasoline.

**Comment by mugling** [comment]
Sounds like a good solution

**Comment by mugling** [comment]
I'm going to rework the NPC weapon groups
