### ISSUE TITLE
NPCs that want to talk are heard by a deaf player

### ISSUE THREAD

**Issue by flitvious** [CleverRaven/Cataclysm-DDA#16188]
NPCs will state that they want to talk, and it will be printed in the log, as if the player can hear them:
![image](https://cloud.githubusercontent.com/assets/7687709/14497215/c1a2cfe4-019e-11e6-98fb-a0dab8828449.png)

**Comment by Musaab** [comment]
Perhaps it should say something like "Ollie Morton appears to be saying something" if the NPC is in your LoS.
