### ISSUE TITLE
You need a welder to do a simple tire change.

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#16198]
I can understand needing it if you are installing a new wheel.  I don't think it's very realistic to require a welder for a simple tire change.

Album with notes:
http://imgur.com/a/sFz7a

Same result if the wheel is just yellow damaged.

http://imgur.com/UGJbFoo

Current Winx64 Experimental
O.C-12855-g4269a38

This is in a freshly created world, I spawned, revealed the map, spawned some gear, and teleported to a car.

There is some duct tape in the room so the south.

Save game:
https://mega.nz/#!a5MllRRD!047klsp_Xa0Lc-oYR9qLnO7fICyl1Fb_EUIXFnvEk1Y

**Comment by SeanMirrsen** [comment]
Have you tried the `c`hange tire option? You need a welder to actually repair a damaged wheel, but for a change you just need a wrench, a jack, and a new wheel.

**Comment by WizardOfOoo** [comment]
I see.  Well NVM!  Thanks for your help!
