### ISSUE TITLE
Issue with smoking pipes

### ISSUE THREAD

**Issue by illi-kun** [CleverRaven/Cataclysm-DDA#16195]
It's not possible to use a smoking pipe if you have more than 1 smoking pipe in your inventory.

Steps to reproduce the bug:
1) wish rolling tobacco, a lighter, and any two pipes (for example, a crack pipe and a tobacco pipe);
2) try to activate rolling tobacco, you will see the following message: "You need a smoking device and a source of flame to consume rolling tobacco".
3) Drop one of pipes, move away from the dropped item, try to smoke again (successfully).

I suppose the issue appears due to line 611 in ```src/visitable.cpp```:
```return qty != limit ? VisitResponse::NEXT : VisitResponse::SKIP;```

**Comment by illi-kun** [comment]
@mugling I think you're the best person to resolve that (and sorry if I'm too annoying).

I'm not sure that replacement of ```!=``` by ```>=``` will resolve the issue (and another thing which should be taken into account is that required amount of apparatus is ```-1```). I can try to fix this by myself but I don't want to brake any other things by this fix.

**Comment by mugling** [comment]
@illi-kun thats fine I'll look into that

**Comment by uzairahmadkl** [comment]
use these pipes, you will get 15% off, <a href="https://cosmosartceramics.com/collections/girly-smoking-pipes">girly pipes</a>
