### ISSUE TITLE
Should all debug items be moved to their own json file?

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#16199]
Like debug.json in the items folder. Might be good to put them all in one place instead of loose with the other entries. I was thinking of even returning their default values to them.

**Comment by mugling** [comment]
Can you give examples of the items you want to move? What would be the benefits?

**Comment by Cyrano7** [comment]
So the question came about while moving the meds. Since the chloroform soaked rag is a med but is only a debug item I was wondering what to do with it. Having them all to together in one place who make them easier to find if you were looking to do something with specifically a debug item. Putting the default values back onto the diet pill would be similar to how we have a map tile template and example mod. For example if I was to test addiction I could just write over the 0 and null for the addiction related values. I wouldn't do it for the chloroform soaked rag and things that have a specific function though.

**Comment by illi-kun** [comment]
I think that even debug only MED items should stay together with other MED items, and so on (at least as an example of possible fields and non-typical features: diet pills in the file with comestibles demonstrates how to use some field(s) which are not widespreaded yet but already used in pills).
