### ISSUE TITLE
Cold Negative Mood Modifier Stacking to Ridiculous Levels (Currently -450) and not Falling Off

### ISSUE THREAD

**Issue by Tsevion** [CleverRaven/Cataclysm-DDA#16204]
In the current Experimental (0.C-12973-g5234160, Tiles version on Windows x64, Running on Windows 7), the Cold moodlet is stacking up and not going away. Just start a new survivalist outdoor game and run around for a bit. I've even lit a fire and am currently quite hot (+40ish on most bodyparts), and yet I still have a -450 modifier listed as Cold in the v menu.

Obviously this makes crafting impossible.

I'm guessing it's something introduced with codemime's morale changes, but I don't see any obvious specific culprit.

**Comment by codemime** [comment]
I'm on it.
