### ISSUE TITLE
All PR builds marked as failure due to Makefile discrepancy

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16206]
Does makefile need to be separately accepted or something like that?

**Comment by lucianposton** [comment]
The OSX build machine is having intermittent issues, which is causing the build server to block on the IRC updates. (at least, that's what I gathered from the discussion of the issue on irc)

**Comment by narc0tiq** [comment]
The build server was blocked this morning on IRC notifications. This happens sometimes, it's a known Jenkins stupidity.

I guess the reference repo may have gotten out of sync with reality. I'll try kicking it again and we'll see what comes of it. It looks like it hasn't been listening to IRC requests, either, so goodness only knows what's really wrong with it. Will update when I have time to investigate further.

**Comment by narc0tiq** [comment]
Problem temporarily suspended - I updated the reference repo manually, but
it'll probably fall behind again. However, this is the best I can do
tonight.

Please leave the issue open for further status updates.

**Comment by narc0tiq** [comment]
And now properly resolved. Some config changes on the Jenkins were resulting in the reference repo not being updated with each experimental build, which was rather unfortunate for obvious reasons. I've gone ahead and fixed the config and everything seems right now.
