### ISSUE TITLE
Small Storage Battery recipe is no longer in books

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#16202]
http://cdda-trunk.estilofusion.com/small_storage_battery/craft

**Comment by narc0tiq** [comment]
Changed in  #14559, which explicitly mentions:
> Small storage cells are no longer craftable. DIY lead-acid batteries are possible, but storage cells are something closer to modern Li-Po I think. Anyway, there is no point in crafting them when you can get 24 small cells out of one big storage cell.

It is not uncommon for the item browser to lag behind the experimentals by a month or two. It is currently claiming to show the state as of 75886c0 (i.e., Feb 25).
