### ISSUE TITLE
reloading from floor crashes cataclysm

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#16205]
Example: wish for m1A, m14 magazine, drop magazine, try to reload with it.

**Comment by DanmakuDan** [comment]
I ran into a similar problem with a UPS and batteries on floor:

For @mugling
`int item::reload_option::moves() const` is crashing because `*ammo` (the "what" reference stored in the item_location) is a null pointer at line 4293 in item.cpp:
`int mv = ammo.obtain_cost( *who, qty() ) + who->item_reload_cost( *target, *ammo, qty() );`

**Comment by Coolthulhu** [comment]
Can't reproduce the crash, but I managed to cause a related bug:
* Spawn M1A and 3 M14 magazines
* Reload M1A with any of them
* Reload M1A with the second magazine from the list
* Debugmsg about trying to remove an inexistent item, then magazine is duplicated

Looks like something inventory is being scrambled and then accessed by pointers.

**Comment by Rod-Serling** [comment]
I seem to have a reproduction of this crash using a crafted tailor's kit, so I don't believe it's necessarily directly related to magazines.

Save File:
https://www.dropbox.com/s/br0dl3chtacemfr/Crashtown.7z?dl=0

Simply load in, and reload the tailor's kit from the thread on the floor. I'm not sure exactly the steps to get it into this or if it's completely related, but it sounds fairly related.

**Comment by mugling** [comment]
I've tagged it magazine as the most likely candidate is the reloading code

**Comment by mugling** [comment]
@DanmakuDan do you have a full stacktrace as it would be helpful to know from where that method is being called

**Comment by DanmakuDan** [comment]
Using debug built for 0.C-13078-g7178ce8:
In the case of loading a UPS with batteries, the UPS originally needs to be empty to cause the segfault.

```
Program received signal SIGSEGV, Segmentation fault.
At C:\Base\Dev\CataDev\Cataclysm-DDA\src\item.cpp:3264

[debug]> bt 30
[debug]#0  0x0000000000694f7b in item::is_ammo (this=0x0) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\item.cpp:3264
[debug]#1  0x0000000000a94cb5 in player::item_reload_cost (this=0x3af57f60, it=..., ammo=..., qty=412) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\player.cpp:9962
[debug]#2  0x000000000069be0e in item::reload_option::moves (this=0xfc7d180) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\item.cpp:4293
[debug]#3  0x00000000005f9577 in game::reload (this=0x3b5d5510, pos=0, prompt=false) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\game.cpp:11411
[debug]#4  0x00000000005ade0c in game::inventory_item_menu (this=0x3b5d5510, pos=0, iStartX=0, iWidth=50, position=game::RIGHT_OF_INFO) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\game.cpp:1864
[debug]#5  0x00000000005b6f50 in game::handle_action (this=0x3b5d5510) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\game.cpp:2704
[debug]#6  0x00000000005aaf75 in game::do_turn (this=0x3b5d5510) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\game.cpp:1383
[debug]#7  0x0000000000765df6 in main (argc=0, argv=0x2eb4a8) at C:\Base\Dev\CataDev\Cataclysm-DDA\src\main.cpp:451
[debug]>>>>>>cb_gdb:
```

**Comment by mugling** [comment]
Thanks, I think I've got it worked out

**Comment by Azarikesh** [comment]
I've noticed it with any device that requires batteries as well. If i reload using batteries on my person, it appears to work fine, if they are on a tile around or beneath me, the game crashes.
