### ISSUE TITLE
Duplicate milk recipe.

### ISSUE THREAD

**Issue by Lain-** [CleverRaven/Cataclysm-DDA#16218]
In the lastest experimental (0.C-13017-gc5aad12), there are two seperate recipes for the same product "milk". One uses "condensed milk" while the other uses "powdered milk". I assumed this is not intentional?

**Comment by DanmakuDan** [comment]
The recipe using condensed milk generates 2 milk portions per craft compared to 1 per powder.

**Comment by Lain-** [comment]
I will close this, then.
