### ISSUE TITLE
Place_loot enhancement

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#16216]
It would be nice to be able to override `ammo` and `magazine` in your mapgen. (currently it uses values defined in item_group I think)

**Comment by mugling** [comment]
I've considered this and came to the conclusion that we should aim to migrate fully to JSON rather than update the compiled mapgen code. I do however want to extend `place_loot` to support random ammo amount and types.

**Comment by Mshock777** [comment]
Shouldn't we instead  allow each location to specify these values for better customization instead of, in a way, "harcoding" it?

**Comment by Leland** [comment]
Seems like this is just more of a note to update `place_loot` at some point – this thread hasn't seen an update in over a year. Closing for now. If anyone is still interested, I can reopen... or feel free to just make a new issue.
