### ISSUE TITLE
inhaler_stimgas does not spawn anywhere and cannot be crafted

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#16223]
inhaler_stimgas does not spawn anywhere, cannot be crafted and is missing a "use_action" field. There are also no notes saying its a debug item or yet to be implemented. Should we make this item useful? or get rid of it? It would be kinda cool to have a CDDA take on jet from Fallout.

**Comment by Coolthulhu** [comment]
It has the use as a stimulant with fun but also negative health. It doesn't need iuse at the moment, but could get one just to make it more useful and/or future proof.

I'd give it the inhaler iuse. Or just remove it.
