### ISSUE TITLE
Proper name for Kel-Tec SUB-200 is Kel-Tec SUB-2000

### ISSUE THREAD

**Issue by flitvious** [CleverRaven/Cataclysm-DDA#16228]
As it says here:
https://en.wikipedia.org/wiki/Kel-Tec_SUB-2000

**Comment by illi-kun** [comment]
This gun was added in #15086 and missing "0" in name seems to be a typo because plural name is correct:
```
"name": "Kel-Tec SUB-200",
"name_plural": "Kel-Tech SUB-2000",
```
I'll fix this in a moment, thanks for the report.
