### ISSUE TITLE
[Spoiler] Canon Check:  Fortress of Solitude Proposal

### ISSUE THREAD

**Issue by acidia** [CleverRaven/Cataclysm-DDA#1623]
Fortress of Solitude Proposal

To all Coalition nations that have endured, the emergency council has convened and unanimously voted to enact what will henceforth be termed the 'Fortress of Solitude Proposal.'  We understand the extent of destruction that each country faces on its own accord but discoveries made in the past two days into dimensional transposition has altered our contingency plans as a united force. 

Dimensional transposition has, until now, been considered the preeminent Coalition secret.  For this reason, this proposal may be the first time that your nation's leaders have been officially  informed of the existence of such technology.  Under controlled conditions, we have the capacity to instantly transport material and people between two points in space.  The applications of this technology are only limited by the power consumption that is dependent upon the mass of the object being transported, the distance traveled, and the change in gravitational potential.  Within these gates there are certain 'frequencies' called resonances that allow matter to be transported to locations far enough away that they completely elude attempts at orientation.  Although daunting, one such location lies deep in space beyond the reach of any of our enemies.  There, we propose to build a space station that will be able to act as a sanctuary and control center for operations to purge and recolonize the Earth. 

As this letter reaches you, facilities around the globe are being converted or built to accommodate hourly transposition of bulk cargo to the site.  It is imperative that all resources that can be spared go towards this project.  For fear of retaliatory actions from the Sino Block, from which we have not heard word, we have only included the closest bulk cargo transposition site in the addendum.  All survivors are to contact these headquarters to organize rescue and recovery efforts.

Marcus O'Neal
United States Senator,
Coalition Representative

Addendum:
Northeast United States and Eastern Canada
Vice Adm.  John Ward, Commander of USN 2nd Fleet
Flagship, CVN-78 Gerald R. Ford
Contact:  VHF channel 16 (156.8 MHz)

[Time Line:  Outbreak +4 days, Player starts at outbreak +5 days I believe]

**Comment by qbradq** [comment]
Can we apply the "Enhancement" tag?

**Comment by narc0tiq** [comment]
Maybe, but I'd also be willing to close it (so I will). This issue is effectively resolved by Kevin's answer: yes, it fits in canon.

If this does not appear to be correct, please feel free to reopen.
