### ISSUE TITLE
When sewing, reported damage and success chances lack units

### ISSUE THREAD

**Issue by argent0** [CleverRaven/Cataclysm-DDA#16259]
When you try to sew something, the game displays the damage and success chances as

Success chance 0,0
Damage chance 2,4

in my locale. I think it would be clearer to have something like

Success chance: 0,0 %
Damage chance: 2,4 %

Note the ':' and the '%'.

Regards

**Comment by lucianposton** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/8091a2ee8ef770960d60f5776b934719f69c0e48/src/activity_handlers.cpp#L1476-L1478
