### ISSUE TITLE
Vegetable Sandwich in Meat subcategory of Food. 

### ISSUE THREAD

**Issue by kd8qdz** [CleverRaven/Cataclysm-DDA#16260]
Vegetable is not meat. Should be in the vegetable subcategory.

**Comment by mugling** [comment]
Good find. Have you considered submitting a PR?

**Comment by kd8qdz** [comment]
im always confused as to what goes in PR.

**Comment by kd8qdz** [comment]
I fixed the catagory of the veggie sandwich #16264
