### ISSUE TITLE
Problems with roadblocks

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#16266]
- [ ] They don't rotate. I somewhat get the problem, but I still decide to make an issue since there wasn't one to keep track of it. (it's done in `mapgen.cpp` in `void mx_roadblock`)
- [x] In "military" case barbed fence spawns on top of barricade. It should be moved to "Police roadblock" case.

**Comment by Night-Pryanik** [comment]
Long ago I asked about the first issue (http://smf.cataclysmdda.com/index.php?topic=9760.0).

**Comment by keyspace** [comment]
Issue can be closed?..

11b0435 mentions that

> Currently doesn't handle adjacency to turns or intersections well, we may want to abort in future

**Comment by Asmageddon** [comment]
Probably not worth creating a new issue for and might be unrelated, but I've also encountered a food stall in the middle of the road, at a 90 angle.

**Comment by Coolthulhu** [comment]
Seems solved since then
