### ISSUE TITLE
Firing mounted A7 laser rifle produces debug messages about invalid ammo

### ISSUE THREAD

**Issue by flitvious** [CleverRaven/Cataclysm-DDA#16276]
Firing mounted A7 laser rifle produces this debug message: "Tried to set invalid ammo of none for fake UPS".

Reproducing:
1. Wish for an A7 laser rife
2. Install it to a vehicle
3. Try to shoot it

![image](https://cloud.githubusercontent.com/assets/7687709/14640312/a7742726-0649-11e6-8c88-40bdd48aff28.png)

**Comment by Coolthulhu** [comment]
Fixed by recent changes

**Comment by mugling** [comment]
Can we leave this open. I've only kludged it rather than definitively fixed the fault

**Comment by kevingranade** [comment]
Another solution is to open an issue describing the kludge that points to
this issue.  If the reported bug no longer happens it's confusing to leave
this issue open.

**Comment by mugling** [comment]
Is expected to be resolved by #17028
