### ISSUE TITLE
Gun types in "Used on:" ("launcher", "smg" et cetera) are untranslatable

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#16275]
0.C-4723.

**Comment by illi-kun** [comment]
Did you mean skills? Please provide more details.

**Comment by Night-Pryanik** [comment]
![111111111111](https://cloud.githubusercontent.com/assets/11132525/14646934/8b48e172-066c-11e6-9d6c-3b51b5181596.png)
Crossbow is translated somehow.

**Comment by mugling** [comment]
Appears to be marked for translation `item.cpp:1044`

**Comment by Night-Pryanik** [comment]
I encounter this issue once again on 0.C-6872.
![default](https://user-images.githubusercontent.com/11132525/32067796-106d10dc-ba8d-11e7-98ee-cb4712337397.png)
