### ISSUE TITLE
Flaming arrows are weird

### ISSUE THREAD

**Issue by Ygdrad** [CleverRaven/Cataclysm-DDA#16298]
I was working on a pull request to add flaming crossbow bolts and looked into how the flaming arrows worked and noticed just how much of a mess they were. Before I add flaming bolts I want to know if it's ok to change flaming arrows first, here are the issues for them.
1. The naming for flaming arrows is inverted in places and has some typos, making following it in the files more hassle than it ought to be.
2. The flaming arrow comes in 2 stages. When crafted it comes as a 5-charge flammable arrow item with the TOOL type which makes it incompatible with quivers. You need to activate it to use one charge and get one flaming arrow which has the AMMO type and now nonsensically can be put into a quiver while on fire.

I want to fix the naming convention and turn them into a simple 1-stage ammo since the 2-stage thing makes them interact weirdly with quivers. I could see keeping a 2-stage setup if they used lighter charges for balance purpose, but they don't use anything to light so I see no point in keeping them as is.

Edit: There is an extra move cost associated with lighting the arrow but this would probably be better implemented as different ammo/magazine types having an effect on reload time.

**Comment by kevingranade** [comment]
If by naming you mean the name field, go ahead and make it consistent, if
you mean the I'd field, leave it.
Viable options for the other issue are removing them or making them take
extra time and Firestarter charges to fire instead of activation.  Making
them magically burst into flames when fired isn't.

**Comment by Ygdrad** [comment]
Is it currently possible to change requirements and move cost of firing a projectile or would that need to be implemented first? Having ammo/magazines have an effect on reload time could make sense given that some guns have access to different magazine types and a double drum magazine would be much bulkier and slower to attach than a straight magazine.

Turns out that the tool action on flammable arrows does need a source of fire. It was somehow using a mini flamethrower cbm despite there being no power for it.

**Comment by Leland** [comment]
Old suggestion and no recent discussion here. Closing. Feel free to let me know if you want it reopened.
