### ISSUE TITLE
Ability for gunmods to contribute "ammo_effects" to the main weapon

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#16296]
Could prove useful for adding high-tech mods. Namely for stuff like the laser and plasma scattering lens of fallout 4, electrolaser conversions for the laser guns, and probably more.

**Comment by kevingranade** [comment]
If you have an effect in mind, propose it, raw infrastructure without a use
case isn't particularly useful.

**Comment by John-Candlebury** [comment]
Sure:
```
[
  {
    "id": "beam_scatterer",
    "type": "GUNMOD",
    "name": "beam scatterer",
    "description": "A set of optics made to fit in the muzzle of laser weapons, which will diffract the laser beam into several lower powered beams .  This increases point-blank damage, but greatly reduces range.",
    "weight": 380,
    "volume": 1,
    "price": 84000,
    "material": [ "steel" ],
    "symbol": ":",
    "color": "light_gray",
    "location": "lens",
    "mod_targets": [ "rifle", "pistol" ],
    "min_skills": [ [ "gun", 2 ] ],
    "damage_modifier": 10,
    "range_modifier": -25,    
    "ammo_effects" : [ "SHOT" ]
  }
  ]

```
Basically it makes your laser gun do this, in a more controlled manner:
![image](https://cloud.githubusercontent.com/assets/5290912/14696482/a144a5c0-0738-11e6-96d9-7f69257032ef.png)

So you now have a laser "shotgun".

**Comment by mugling** [comment]
I know how this could be implemented. Can you please provide an example for mainline content as I agree with @kevingranade that I only want to commit code that's going to get significant use (eg. continuous testing)

**Comment by John-Candlebury** [comment]
This is something that should only ever work for energy weapons, so I guess most of it could be considered a bit far out there.

I can, however, name two more sensible examples:

```
  {
    "id": "electrolaser_conversion",
    "type": "GUNMOD",
    "name": "electrolaser conversion",
    "description": "A set of high-tech electronics and optics.  This converts a laser pistol into a less-lethal electrolaser capable of stunning targets, at the cost of a decreased damage output and increased power consumption.",
    "weight": 380,
    "volume": 4,
    "price": 84000,
    "material": [ "steel" ],
    "symbol": ":",
    "color": "light_gray",
    "location": "emitter",
    "mod_targets": [ "pistol" ],
    "min_skills": [ [ "gun", 2 ] ],
    "damage_modifier": -5,
    "range_modifier": -5,    
    "ups_charges": 5,
    "ammo_effects" : [ "BEANBAG" ]
  },
  {
    "id": "high density capacitor",
    "type": "GUNMOD",
    "name": "high density capacitor",
    "description": "A higher density capacitor increases range, damage, and the likelihood of setting the target on fire;  at the cost of a markedly increased power consumption.",
    "weight": 380,
    "volume": 1,
    "price": 84000,
    "material": [ "steel" ],
    "symbol": ":",
    "color": "light_gray",
    "location": "capacitor",
    "mod_targets": [ "pistol", "rifle" ],
    "min_skills": [ [ "gun", 2 ] ],
    "damage_modifier": 10,
    "range_modifier": 5,    
    "ups_charges": 30,
    "ammo_effects" : [ "FLARE" ]
  }
```

-Maybe you could also add a variant of the "MUZZLE_SMOKE"  tag to the shortened barrel mode for  machine guns

Another use that involve mods would be
 -Enchanting bows in the arcane mod (AKA mods that can give the acid, flare, electricity and explosive effects)

**Comment by Leland** [comment]
This is an _awesome_ idea, but we're past a year since the last comment. I'm closing this for now, but if there's still interest by anyone, let me know here and I'll reopen; or feel free to make a new issue.
