### ISSUE TITLE
Cannot remove tires from vehicles.

### ISSUE THREAD

**Issue by Nymall** [CleverRaven/Cataclysm-DDA#16299]
Character gened as a bionic prepper. 8 strength, found a bottle jack, 3 mechanics, cannot remove the wheels off any vehicle. Debugged strength to 25(minimum requirement without jack), gave self wrench, would still not remove the tire from ANY vehicle.

All indicators on repair screen are yellow. Everything looks good, but it still does not remove the tire. No error message, just fails as if missing an item.

Version 0.c-13312-gdff120d

**Comment by Lazasar** [comment]
Yep. Same problem.

**Comment by mugling** [comment]
Can reproduce. Fixed by #16325
