### ISSUE TITLE
Game does not read mods,saved worlds or character templates.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#16305]
Experimental 13314-g9b71645

I downloaded game it would not recognize any mods, prepackaged with the game or otherwise. It will say there are no worlds when I try to use the load option and when you try to create a new world it says there are no mods listed. Even if you create a new world, the game will simply say there are none. I can confirm all mods and saves are in their respected folders.

**Comment by illi-kun** [comment]
I'm not able to reproduce this. Please provide more details: what is your OS, where did you download the game, etc.

**Comment by Noctifer-de-Mortem** [comment]
I am using windows 10 home edition running 64 bits. The game is in a usb. Here are some screen shots:

This is what it shows in the world creation screen.
![no_mods](https://cloud.githubusercontent.com/assets/16777044/14720015/f9d3892c-07c4-11e6-9708-f046f9e996a3.png)

As you see I do have mods in the correct folder.
![the_mods](https://cloud.githubusercontent.com/assets/16777044/14720016/f9d4588e-07c4-11e6-8020-cf58c6cc76dc.png)

**Comment by Noctifer-de-Mortem** [comment]
Problem fixed, for whatever reason, moving the game to a hidden folder makes the following issue arises; moving it back to normal folder fixes the issue.
