### ISSUE TITLE
Rolled smokeables have unusual volume.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#16300]
0.C-13314-g9b71645 (tiles)

Joints and hand-rolled cigarettes take up a point of volume *each*, refusing to utilize ````stack_size```` properly.

**Comment by mugling** [comment]
Not sure on that one but will look into it.

I'd quite like to merge factory and handrolled cigarattes as one (craftable) kind. There shouldn't be so much difference between the two. Pipes are sufficiently different to remain.

The rationale being that addicted players should need a large stockpile and it would reduce inventory spam and improve the UI if they could assign an `invlet` to a single stack.

By the same logic I'd like to drop stubs as well. There's no improvement in gameplay by forcing more key-presses to either drop frequently drop unrequired stubs or to recraft a single cigarette from many stubs. Cigarettes should just last 10% longer.

Finally cigarettes and tobacco are too plentiful. Addiction would be a problem in the cataclysm, especially later on

**Comment by Rivet-the-Zombie** [comment]
>I'd quite like to merge factory and handrolled cigarattes as one (craftable) kind. There shouldn't be so much difference between the two.

As a longtime smoker, I beg to differ. Factory-made smokes are a lot better than the ones you make from rolling tobacco or (ugh) re-rolled butts.

>Finally cigarettes and tobacco are too plentiful. Addiction would be a problem in the cataclysm, especially later on

I've always thought that we should give them more downsides (for cigarettes it could be something like reduced stamina regeneration and an intermittent cough that grows worse as the addiction worsens) rather than imposing artificial scarcity.

**Comment by mugling** [comment]
> As a longtime smoker, I beg to differ. Factory-made smokes are a lot better than the ones you make from rolling tobacco or (ugh) re-rolled butts.

I always considered the opposite (not the butts part obviously). I agree IRL there's a difference but I don't think simulating it in-game adds much (especially the re-rolled butts part). Both are as unhealthy, addictive and would have similar other effects. Modelling which type the survivor prefers would seem somewhat excessive.

Addiction:
* Quick to occur (more than one cigarette on the same day, instantly for addictive personality)
* Withdrawal occurs after 1-day (to allow for sleeping)
* Withdrawal takes 5 days, with the degree worsening on each day
* Nicotine gum lessens severity but not the duration
* Addiction is instant if you've ever been addicted before (bitter experience)

Rarity:
* All zombies have reasonably frequent chance to drop mostly empty packet
* Overall more sources but less in one place (its currently possible to obtain >100 on the first day)

Crafting:
* One type plus pipes and joints. Preferences exist IRL but aren't of much gameplay significance
* Unlike cigarettes tobacco is found in full packets (but at a low frequency) making it good loot

As to bonuses:
* +1 `INT` for 6 hours after each cigarette.

As to penalties:
* Penalties to`healthy` stat with all the emergent behavior that results from that

Code/interface:
* Overhaul charges randomisation including allow specifying min/max percentage in `item_group`

**Comment by illi-kun** [comment]
BTW, "SMOKING" ```use_action``` defined for cigarettes, cigars, and other smokable stuff is redundant and can be replaced by ```use_action``` and ```effects``` fields. I've tried to do this earlier but met one issue: activation of cigarettes lights up the entire stack (instead of one charge only).

**Comment by kevingranade** [comment]
Re: merging, please no. These are distinct items irl, having a thematic
differentiation between the two is more than sufficient reason to keep them
separate.

**Comment by John-Candlebury** [comment]
>Overall more sources but less in one place (its currently possible to obtain >100 on the first day)

To be honest most small stores probably have hundreds of cigarettes in them, supermarkets surely have thousands. 

Almost every gas station, bar, general store, booze shop should pretty much guarantee several  packs. 

It would be much better if addiction could increase to the point in which you smoke a pack or more per day.

**Comment by mugling** [comment]
I've looked in to the underlying stacking bug and I'm not the wiser. Anyone else shed any light?

**Comment by Hague** [comment]
Comparing the Entries in data/json/items/comestibles/med.json I noticed that the hand-rolled items: joints and handrolled cigarettes are missing: `"charges" : 1,`

All the other medical comestibles stack properly and have a charges entry. It seems like it might be related as these items are the only ones affected. It appears that `"id" : "flu_shot",` is also missing this entry. Testing stacks of flu shots from debug menu revealed a 2 stack of flu shots takes up 2 volume but the `stack_size` entry under flu shot is also 40. It seems that this would confirm that these entries missing charge amounts breaks their use of `stack_size`

**Comment by illi-kun** [comment]
Fixed by #16497.
