### ISSUE TITLE
wielded guns does not show damage

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#16306]
![qq 20160421172151](https://cloud.githubusercontent.com/assets/17041809/14703575/14a605f4-07e3-11e6-8215-6ccc695633e5.png)

**Comment by mugling** [comment]
Not a bug. The top display is the remaining ammo count.

**Comment by Zireael07** [comment]
He means the item health bars aren't displayed at the top.

**Comment by mugling** [comment]
Not sure that's a bug either but further comments are sought

**Comment by Night-Pryanik** [comment]
Well, I like consistency. Besides, that's just two more symbols.

**Comment by kevingranade** [comment]
It's not a bug. "just two symbols" in the sidebar is a really big deal.

**Comment by illi-kun** [comment]
We already have a lack of space in this line, and adding two more symbols will highlight this issue even more:
![lack_of_space](https://cloud.githubusercontent.com/assets/5421954/14737827/26c98466-088f-11e6-9172-9e2519791795.png)

The purpose of this record is showing the ammo, not quality of your gun (you can check it in inventory easily).

Anyone, feel free to provide a possible solution for that in the dedicated issue, but simple adding of two more symbol isn't a reasonable "fix".

**Comment by narc0tiq** [comment]
Speaking purely for myself, I'd be really happy to trim the item name in favour of ensuring the ammo and item damage both remain visible (warning, terrible mock-up):

![terrible](http://i.imgur.com/sFjR9vi.png)

**Comment by illi-kun** [comment]
@narc0tiq sounds interesting.

Talking about that, we also need to keep in mind other possible weapon mods, like ```(Mod)```, ```... (Bayonet)``` and ```...(Burst)``` (defined in function ```print_gun_mode()``` in ```player.cpp```).
