### ISSUE TITLE
Can't refill car with gas from container

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#16319]
Had a 60L tank filled with gas in my hands, and a hose. trying to refill I am told that there is no access to refill

**Comment by mugling** [comment]
What is the specific message?

**Comment by Lazasar** [comment]
Ok, so what is interesting is it works fine if I "U"nload a jerrycan or anything carrying fuel. The I get a prompt asking me if I want to refill a vehicle and then a direction request.

The problem only exists when I try and use the refill command from the vehicle menu.

**Comment by Rivet-the-Zombie** [comment]
Do you have the gas tank selected when you're trying to refill it from the vehicle screen?

**Comment by mugling** [comment]
> What is the specific message?

Liquids are handled (badly) in several near-identical functions. The specific message is required to narrow this down somewhat

**Comment by Lazasar** [comment]
Ok. I have lost my latest save due to some launcher wierdness. On my next playthough, I will give it a try

**Comment by Lazasar** [comment]
@Rivet-the-Zombie I don't think I did. D'oh.

**Comment by Lazasar** [comment]
You can close this. It was my mistake about how the whole thing worked.
