### ISSUE TITLE
NPCs being attacked upstairs show up on screen downstairs.

### ISSUE THREAD

**Issue by Rojersm** [CleverRaven/Cataclysm-DDA#16310]
Pretty self Explanatory, I led some zombies into the evac shelter and as they attacked him he lit up on the screen downstairs with each turn. Not sure if this was because of him taking damage or firing his crossbow though sorry to say. Experimental version 0.C-13314-g9b71645

**Comment by kevingranade** [comment]
Was it a brief flash when they were hit? There's a hit box animation
function that might not be z-level aware.

**Comment by Rojersm** [comment]
It was a flash but unless it was him firing i would assume that it was him getting hit since there were multiple hostiles.
