### ISSUE TITLE
Ballance MBR Vests to weigh inline with their components

### ISSUE THREAD

**Issue by kd8qdz** [CleverRaven/Cataclysm-DDA#16315]
#16043 pointed out problems with the superaloy vest.  I did a bit of math [here](https://docs.google.com/spreadsheets/d/12jOEze54stW4qYYuQdDL4Yq8K3hxk7kGIFt6DL3FIvo/edit?usp=sharing) and it looks like they all need tweeking. Comments on how we should handle this?

**Comment by Zireael07** [comment]
Why make a duplicate issue? Continue discussion in #16043.

**Comment by illi-kun** [comment]
I agree with @Zireael07, no need to duplicate the same issue.

**Comment by kd8qdz** [comment]
Because #16043 was only about one vest.

**Comment by illi-kun** [comment]
OK, I renamed the mentioned issue.
