### ISSUE TITLE
Inhaler is grossly overweight.

### ISSUE THREAD

**Issue by Totentag** [CleverRaven/Cataclysm-DDA#16324]
So, I just updated and reloaded a game for the first time in about two weeks, to find my asthmatic character is carrying an inhaler with a volume of 2, weight of 4.3, and 194 charges of albuterol. After my initial freakout, I went to WISH for a new inhaler out of curiosity and found they are, by default, volume 1 and weight 2.2 at 100 charges. 

While I'm going to assume the over-charge that lead to the weight gain and volume increase is a separate bug from reloading a comparatively old save, the weight of 2.2 lbs seems to be FAR too high to be realistic. I'd say the same for the volume of 1 (which I've heard described in IRC as "fist sized"), but that's less severe of an issue I imagine. 

As it stands, I'd suggest dropping the weight of a full inhaler to at most maybe 0.2 or 0.3 lbs, based on estimates I've gotten from nearby nurses and friends online who use rescue inhalers. I'll edit this with an exact answer if I can finally get Google to cooperate and not tell me all about "steroids and weight loss" when trying to find an answer to this. 

EDIT: I have found one answer thus far, [here](https://healthunlocked.com/blf/posts/130770168/has-anyone-got-a-way-of-tracking-how-much-is-left-in-a-ventolin-inhaler) listing the weight of a full inhaler canister (without the inhaler body) at 34 grams or ~0.07 lbs. Will update later.

**Comment by Rivet-the-Zombie** [comment]
Sounds like it's counting the charges as part of its weight.

**Comment by mugling** [comment]
Isn't mass usually expressed per charge?

**Comment by Coolthulhu** [comment]
Volume shouldn't be 0, unless the item's volume is totally negligible. Especially if the item is fragile and can't be covered with crap without breaking. Since inhaler is not a charged item but item counted by charges, this technically it isn't a single inhaler, but 194 inhalers, just named "inhaler" so that it looks like a single inhaler on the outside. Similar problem as with batteries which stack like powder or liquid rather than like IRL batteries.

**Comment by Totentag** [comment]
In regards to the volume, coolthulhu, is it possible to give items a decimal volume? If not, I wouldn't really push the matter much further, as 1 volume is completely comparable to the pill bottles we've all gotten used to lugging around. 

Regardless, the biggest issue here I would say is the weight; the weight of a single inhaler absolutely is negligible, in comparison to the 2.2 lbs a single "full" item in-game has. As such, I'd very much prefer to see a "full" inhaler listed as weightless, if the alternative is each charge at minimum weight adding up to an item some characters have to carry /at all times/ being problematically heavy.

**Comment by Coolthulhu** [comment]
> In regards to the volume, coolthulhu, is it possible to give items a decimal volume?

Not directly. All volume has to round up. It's intentional that almost everything takes that 1 volume or more, because otherwise it results in clutter and micromanagement.

The weight is a bug, but the volume isn't.
