### ISSUE TITLE
Can't remove tires from car.

### ISSUE THREAD

**Issue by Napalm222** [CleverRaven/Cataclysm-DDA#16327]
build 0.C-13331-geb1a3b6

Have wrench, lifting equipment of right level, and level 2 mechanics. Can't remove the 28" tire from a security van. Can't select the option with enter key. Tried to remove tire from small car with strength high enough and still can't remove any tire.

Created a new character to test and still can't remove any tires.

**Comment by mugling** [comment]
Duplicate of #16299
