### ISSUE TITLE
can't uninstall wheel from 6t vehicle despite having boom crane

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#16331]
I have a boom crane installed on separate vehicle, 'lifting equipment' is green on vehicle screen, but I still can't uninstall a wheel.

Save: http://dump.bitcheese.net/files/bopigob/save.zip

**Comment by mugling** [comment]
Try against latest `master` there was a recent bugfix affecting this

**Comment by Voker57** [comment]
indeed.
