### ISSUE TITLE
survivor naginata cannot be sheathed, put into scabbard,or strapped by other way

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#16335]
survivor naginata cannot be sheathed, put into scabbard,or strapped by other way

"you can't put your survivor naginata in your back scabbard"
"survivor naginata is too big to fit in your scabbard"
"survivor naginata is too big to fit in your sheath"

**Comment by Coolthulhu** [comment]
Not sure how would you want to sheathe a spear.

**Comment by kevingranade** [comment]
In principle you could attach a shoulder strap to it, not sure if that's
implemented.

**Comment by kd8qdz** [comment]
shoulder straps for pole/long weapons are not implemented.   I don't think they should be, not very practical.

**Comment by Chezzo** [comment]
Napoleon Dynamite says you can do it: https://www.youtube.com/watch?v=FDNAw99ZqOU

**Comment by Beanzy** [comment]
I suppose you could prop it up on your shoulder, and have it encumber an arm and corresponding hand. Basically the same way the game handles a [bindle](http://cdda-trunk.estilofusion.com/bindle).
