### ISSUE TITLE
Every computer has accessibility features, let's let illiterate people use them.

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#16348]
Every major OS has built in accessibility features, isn't it corporate discrimination that the ones in CDDA don't? I think we should change computers to let blind and illiterate players use them, like in real life.

Also, this would make Illiterate playable.

**Comment by jcd000** [comment]
I'm sorry, but accessibility features can't help someone who can't read. Afaik there are zero OS'es able to let people work with just symbols on a touchscreen. And to voice control a PC you'd need to understand what it's doing (so you'd have to read the text on the screen). At least until someone IRL implements a pure voice-based human-pc interface, able to do the kind of stuff we do with a PC in-game (photos, texts, hacking)

For blind people, absolutely, if they possess a kind of braille screen.

**Comment by lucianposton** [comment]
> I'm sorry, but accessibility features can't help someone who can't read.

Screen reader

**Comment by lucianposton** [comment]
More discussion in https://github.com/CleverRaven/Cataclysm-DDA/pull/16349

**Comment by mugling** [comment]
Continued in superseding issue #16349
