### ISSUE TITLE
Mismatch between stack size of casing/primer and stack size of product in reloaded ammo crafting

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#16350]
A lot of them dont add up.
For example: 
reloaded .30-06 Springfield require 10 casings to craft 20 bullets.
reloaded .44 FMJ require 50 casings to craft 20 bullets.

It would be nice to extract the casing/primer requirement from the stack size of end product dynamically.

PS. some item names also dont line up. We have "handloaded" .22 FMJ and "reloaded" .44 FMJ.

**Comment by Rivet-the-Zombie** [comment]
>reloaded .30-06 Springfield require 10 casings to craft 20 bullets.
reloaded .44 FMJ require 50 casings to craft 20 bullets.

Probably copy/paste errors.

**Comment by mugling** [comment]
> It would be nice to extract the casing/primer requirement from the stacksize of end product dynamicly.

Yes, but the question is how, for example `22` provides a notable exception to the rule.

**Comment by kevingranade** [comment]
So you just have a recipe that has result, quantity, primer type, casing
type, powder/round, bullet material/round.
That is a good idea.

**Comment by mugling** [comment]
template recipes?

**Comment by kevingranade** [comment]
It doesn't have to cover every recipe, if it covers 90% of them it's
worthwhile, considering their numbers.

**Comment by mugling** [comment]
I've begun work on sequentially cleaning up ammo recipes starting with `shot` in #17385

**Comment by Coolthulhu** [comment]
BTW why is handloading using big stack sizes? Shouldn't it be possible to handload single bullets?

**Comment by Rivet-the-Zombie** [comment]
>Shouldn't it be possible to handload single rounds?

It really should be; sometimes you've only got a partial stack of brass to work with - though it would go much easier if the batch crafting could go to amounts higher than twenty for when you want to do a lot of them at once.

**Comment by Coolthulhu** [comment]
Anyone got a list of jsons that still need changing?

**Comment by kolsurma** [comment]
Version 21585 - wall of table. 

There are still a few recipes that have mismatched input/output. Some recipes like the .500 S&W & .44 have a high charge cost per output. If 1 casing = 1 bullet, then the per craft charge cost should lowered.


|name|casing|ammo|HP&D set charges|hotplate charges|
|------|-------|-------|-------|-------|
|**handloaded .22 FMJ**|**100**|**80**|2|-|
|**handloaded .22 LR**|**100**|**80**|2|-|
|makeshift shotgun shot|2|2|-|-|
|reloaded .223 Remington|30|30|2|-|
|reloaded .270 Winchester|20|20|2|-|
|reloaded .30-06 incendiary|10|10|2|-|
|reloaded .30-06 M2 AP|10|10|2|-|
|reloaded .30-06 Springfield|10|10|2|-|
|reloaded .300 Winchester Magnum|10|10|2|-|
|reloaded .308 Winchester|20|20|2|-|
|reloaded .32 ACP|1|1|-|4|
|reloaded .38 FMJ|1|1|-|4|
|reloaded .38 Special|1|1|-|4|
|reloaded .38 Super|1|1|-|4|
|reloaded .40 S&W FMJ|1|1|-|4|
|reloaded .40 S&W JHP|1|1|-|4|
|reloaded .44 FMJ|1|1|-|10|
|reloaded .44 Magnum|1|1|-|10|
|reloaded .45 ACP +P|1|1|-|6|
|reloaded .45 ACP JHP|1|1|-|6|
|reloaded .45 FMJ|1|1|-|6|
|reloaded .454 Casull|1|1|-|10|
|reloaded .50 BMG AP|10|10|2|-|
|reloaded .50 BMG API|10|10|2|-|
|**reloaded .50 BMG Ball**|**30**|**25**|2|-|
|reloaded .500 S&W Magnum|1|1|-|12|
|**reloaded .700 NX**|**1**|**10**|2|-|
|reloaded 00 shot|1|1|-|2|
|reloaded 10mm Auto|1|1|-|4|
|reloaded 4.6x30mm|1|1|-|4|
|reloaded 5.45x39mm|30|30|2|2|
|reloaded 5.45x39mm AP|30|30|2|2|
|reloaded 5.56 NATO|30|30|2|-|
|reloaded 5.56 NATO tracer|30|30|2|-|
|reloaded 5.7x28mm|1|1|-|4|
|reloaded 5x50mm flechette|100|100|2|-|
|reloaded 7.62x25|1|1|-|4|
|**reloaded 7.62x39mm M43**|**80**|**30**|2|-|
|**reloaded 7.62x39mm M67**|**80**|**30**|2|-|
|reloaded 7.62x51mm|20|20|2|-|
|reloaded 7.62x51mm incendiary|20|20|2|-|
|reloaded 7.62x54mmR|20|20|2|-|
|reloaded 9.19mm +P|1|1|-|4|
|reloaded 9.19mm JHP|1|1|-|4|
|reloaded 9x18mm|1|1|-|4|
|reloaded 9x18mm +P+|1|1|-|4|
|reloaded 9x18mm FMJ|1|1|-|4|
|reloaded 9x19mm +P+|1|1|-|4|
|reloaded 9x19mm FMJ|1|1|-|4|
|reloaded birdshot|1|1|-|2|
|reloaded flechette shell|1|1|-|-|
|reloaded Shotgun Slug|1|1|-|2|
