### ISSUE TITLE
Incorrect handling of batteries inside a Shopping Cart - 0.C-13343-gc118316

### ISSUE THREAD

**Issue by somervillanthony** [CleverRaven/Cataclysm-DDA#16355]
I reloaded my makeshift welder with batteries from inside of a shopping cart and it reloaded it to 400 without taking any batteries out of the shopping cart. After a little experimentation I realized this only happens when you attempt to use up all of the batteries inside the cart, otherwise it works fine.

**Comment by mugling** [comment]
which version?

**Comment by somervillanthony** [comment]
0.C-4741, sorry about that late reply. I thought the one shown at the title screen would suffice. Anyways, I figured out today that it works with ammo as well from a trunk. So I assume it works with all "reloadable" items/ammos.

**Comment by pisskop** [comment]
This affects thread inside all vehicles.

**Comment by Coolthulhu** [comment]
Didn't see it happen for a while
