### ISSUE TITLE
NPC training Brawling keeps increasing Melee skill

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#16361]
I have this NPC following me around. Every time I ask him to training me in Brawling (which has no skill level, it seems), I just raise another level of Melee

**Comment by BevapDin** [comment]
The NPC might teach the Brawling *martial art style*. How much did the NC charge for it? And did you gain that style? The style is automatically learned upon level 2 of unarmed combat skill, so what was your current level of that skill?

**Comment by Coolthulhu** [comment]
Can't reproduce

**Comment by mugling** [comment]
Closed as unconfirmed
