### ISSUE TITLE
Skill books train skills to level 0 (0.C-13425-g3dcd70b tiles)

### ISSUE THREAD

**Issue by Karbine** [CleverRaven/Cataclysm-DDA#16360]
All books I've found once identified say "can train skill x to level 0" and display as greyed out or yellow accordingly. If you read them they behave as though they have nothing to teach you. Confirmed in new world generated without any mods.

Steps to reproduce:
1. Generate new character without any skills
2. Wish for any book that teaches skills, like Beauty Magazine
3. Book will display as being able to raise tailoring to level 0.

**Comment by mugling** [comment]
Suspect regression from #16339
