### ISSUE TITLE
Color issue in log

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#16374]
![333](https://cloud.githubusercontent.com/assets/11132525/14767901/ddaf7e74-0a42-11e6-9cad-73411117b46b.png)

Win 10, tiles, 0.C-4750.

**Comment by lucianposton** [comment]
Which log? The big popup window? If so, https://github.com/CleverRaven/Cataclysm-DDA/pull/16367 fixed that.

**Comment by Night-Pryanik** [comment]
Ok, I just didn't checked that after update. Closing.
