### ISSUE TITLE
NPC brain explodes

### ISSUE THREAD

**Issue by jcd000** [CleverRaven/Cataclysm-DDA#16386]
http://smf.cataclysmdda.com/index.php?topic=19.msg273174#msg273174

Basically i was driving around when i notice an NPC brain explosion. I got the save. 
In the body i found a wooden spear, food, clothes, a lighter.

**Comment by kevingranade** [comment]
This is a NPC ai failsafe when they can't make a decision, and would
otherwise soft-lock the game. Without some context about what caused it, we
can't do anything about this particular instance.
That having been said, they should dump some debug info before exploding so
we can track it down.

**Comment by kevingranade** [comment]
Post the save file and maybe someone can track down what caused it, but otherwise there's not enough information to go on here.

**Comment by jcd000** [comment]
Here is the link:
https://www.dropbox.com/s/qc9wgjqi3q5pyel/brain-exploded-save.tar.gz?dl=0

I compile with RELEASE=1 with iirc disables some debugging functionality, but it still may be of use.
