### ISSUE TITLE
Refugee Center merchant and Rep come outside

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#16389]
at some stage they both came outside, which got them dead by roving zombies. They should stay inside where it is safe :)

**Comment by Leland** [comment]
Looks like discussion has stalled on this suggestion. Closing. If there's still interest, let me know and I can reopen.

**Comment by Night-Pryanik** [comment]
I don't think it's a discussion issue, I'd say it's a bug in mapgen or something like that.

**Comment by Leland** [comment]
@Night-Pryanik up to you! This smacks of an AI suggestion to me.
