### ISSUE TITLE
Vehicle installation requirements

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#16385]
A pictures worth a thousand words, or at least several thousand bytes:

![screenshot-2](https://cloud.githubusercontent.com/assets/12238606/14770239/4a22f4ac-0a64-11e6-8dab-2fa8c3574ce5.png)

Any objections or caveats to overhauling vehicle installation requirements to use the same JSON specification and C++ implementation as crafting requirements? Would replace the current tangled mess of flags `TOOL_SCREWDRIVER`, `TOOL_WRENCH` etc.

Could bring some other advantages (need copper wire to install electricals etc)

**Comment by Mshock777** [comment]
Is this going to fix #10260?

**Comment by mugling** [comment]
How to handle `duct_tape` OR `goggles_welding`?

**Comment by jcd000** [comment]
Maybe add ADHESIVE_TAPE and WELDING_GOGGLES qualities?

**Comment by mugling** [comment]
Well there is `GLARE` quality, the difficulty is matching it up with a powered welder

**Comment by mugling** [comment]
To be honest the idea of using tape in place of a welder is silly so it might be easier to just scrap that

**Comment by jcd000** [comment]
To me it sounds silly too, but there are people who actually used duct tape for that, as @Rivet-the-Zombie  will be able to testify.

**Comment by mugling** [comment]
Welding metal and taping it together aren't even slightly equivalent. Similarly duct taping an alternator to an engine is equally silly

**Comment by Rivet-the-Zombie** [comment]
I can dig not allowing it for installing parts, but we ought to keep it possible to use duct tape for repairing damaged parts at the very least.

**Comment by mugling** [comment]
That sounds both reasonable and practical to implement

**Comment by Coolthulhu** [comment]
Interesting bonus:
If implemented in `requirements`, it could also allow stat-based requirements to recipes

**Comment by mugling** [comment]
> Interesting bonus:
> If implemented in requirements, it could also allow stat-based requirements to recipes

It's tempting to provide `STRENGTH`, `PERCEPTION` etc as pseudo-tool qualities. The implementation already exists for selecting between different tool qualities

**Comment by mugling** [comment]
1 tool with magnifying of 1 or more OR perception 10

**Comment by kevingranade** [comment]
I'm very much in favor of this, up to and including dropping (and at least
documenting them fo future re-add) some current features of vehicle
crafting (like the welder/goggles thing) to remove blockers to it.

**Comment by mugling** [comment]
Using the requirement data is a big win. The vehicle installation code is twisty maze of conditionals with the displayed requirements not always equivalent to what is actually consumed

**Comment by mugling** [comment]
Ideally in the long run we'd have `WELD 2` require one of the electrical welders + goggles but that requires some non-trivial work on the charge consumption code

**Comment by Coolthulhu** [comment]
Charge multiplier could be a relatively simple way of doing that. We already have it for plutonium UPS.

**Comment by mugling** [comment]
Sure, but the bigger difficulty is that it's the last major chunk of the `charges` code that isn't migrated to the `visitable` interface. It's not impossible to make that so, just laborious and something I haven't as-yet got around to

**Comment by Hague** [comment]
It would additionally fix some of the inconsistencies with wooden wheels and other primitive part types requiring wrenches to install. Presuming qualities will be available, being able to use Wood Sawing or Prying quality levels for removing parts from wooden frames and so on. Using qualities would allow graded Lifting Quality equipment: Removing engines fundamentally requires stronger lifting equipment than a jack to avoid damaging it, such as a hoist or stable block and tackle. Larger wrenches and specialized tools are needed for removing parts from heavy equipment. Your standard automotive wrench can't come close to the diameter on most heavy loading equipment, let alone a tank. (Torquing quality? Opens up to pneumatic wrench sets)

**Comment by Lazasar** [comment]
Please do something to require resources for repairing vehicle parts. That would greatly lessen the huge leap forward of power provided by vehicles.

**Comment by Mshock777** [comment]
@mugling What do you think about finally adding tire iron?

**Comment by Coolthulhu** [comment]
We should wait with that until we have optional requirements.

**Comment by mugling** [comment]
Now in `master`
