### ISSUE TITLE
Can't end game after DeathCam

### ISSUE THREAD

**Issue by Greiger** [CleverRaven/Cataclysm-DDA#16387]
Happened with 0.C 4750. Title screen says 0.C-13427-gde66270.  Not sure which of those are the actual numbers y'all use to keep track of versioning.

Anyway like it says on the title activating a deathcam prevents normal ending of the game.  It flashes at you to push the buttons to accept your fate at the top, but it seems the game is too busy processing turns to actually accept the input, as none of the keys do anything.

**Comment by illi-kun** [comment]
Did you tried to press space?

**Comment by illi-kun** [comment]
Nvm, confirmed.

**Comment by Rod-Serling** [comment]
Issue present for me in in:
Windows x64 Tiles 0.C 4760 (Latest)
Windows x64 Tiles 0.C 4740 (Earliest Jenkins Build I have access to)

This places the issue before 5bf7ec2
Tried to look around game.cpp player death handlers with git blame, couldn't find anything useful.

**Comment by kevingranade** [comment]
My suspect would be the code that adjusted the main input loop a little
while back.

**Comment by illi-kun** [comment]
Fixed in #16413.
