### ISSUE TITLE
Extra lines of white spaces after last line of text in several files.

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#16394]
Is this really a thing? and is it worth making a PR to fix?
for example...
comestibles.json 1 extra line,
itype.h 2,
med.json 1,
recipe_food.json 1,
mapgen.cpp 1 + a line of //////// s+ 1 more

Edit: There also seems to be quite a few lines in the files that end in white spaces too.

**Comment by Rivet-the-Zombie** [comment]
>Is this really a thing? and is it worth making a PR to fix?

Yes and yes.
