### ISSUE TITLE
Can't change or add tire - claims I have no lifting equiptment

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#16391]
Have both a  bottle jack and a scissor jack in inventory, but "lifting equipment" in red and can't change a tire, add a tire or remove a tire.

**Comment by mugling** [comment]
Duplicates #16327 and #16299. Fixed in `master`

**Comment by Lazasar** [comment]
Are you sure? In the previous issue the indication was that I had the lifting equipment (text was yellow or green) it just didn't work.... now I get red text.

**Comment by mugling** [comment]
Was yellow?

Which version are you using (Jenkins got behind recently building the experimentals). If you can reproduce this in `master` it's a new bug so should be re-opened if so

**Comment by Lazasar** [comment]
Ok, my bad. It seems that the problem is that I didn't have a jack strong enough to lift the car. Will open an issue asking for more feedback to provided to the user.
