### ISSUE TITLE
MSVC140 Project does not compile

### ISSUE THREAD

**Issue by Rod-Serling** [CleverRaven/Cataclysm-DDA#16399]
There are at least a few issues with MSVC compilation.

1. MSVC as a compiler does not support C99 compound literals. Input.cpp(782) has one.
This can be fixed fairly easily using different ISO C++ standard techniques.

2. ..\src\explosion.cpp(52): fatal error C1001: An internal error has occurred in the compiler. 
I don't know enough about C++ or MSVC to diagnose this issue.

3. Visual Studios 2015 Update 2 utilizes new Intellisense cache files that should be added to .gitignore
msvc140\Cataclysm.VC.db
msvc140\Cataclysm.VC.VC.opendb
msvc140\ipch\*

I can fairly easily fix 1 & 3, and submit a PR, but I have no idea what's going on with explosion.cpp(52). I've tried google and MSDN, but it's just beyond my C++ skillset. Until that's resolved I can't verify any MSVC compiling, so I'd rather not submit a PR with a "Partial fix"

Edit: Self-Reproducible on fresh machine with a fresh install of Visual Studio Community 2015 Update 2

**Comment by DLaboratory** [comment]
In `crafting.cpp` and `bionics_ui.cpp`, there are also some override errors.

Internal Error in `explosion.cpp` is weird. It is likely a bug in MSVC, I guess it is related to STL containers. Sometimes, when I just inserted a blank line, which makes the file changed, and then recompile the code, the compiler internal error disappears, instead some warnings pop up.

Using MSVC to build Cataclysm is just like a cataclysm to my laptop. It eats around 300MB of RAM and 100% CPU resource, produces extreme hot and fan noise, and the painful process takes about more than 10 minutes. (Intel i5-5250U)
