### ISSUE TITLE
Jabberwock Mission completion makes giver unfriendly

### ISSUE THREAD

**Issue by Hague** [CleverRaven/Cataclysm-DDA#16403]
I've completed two Jabberwock missions in my recent playthrough. Both times, completing the mission moved the Mission giver NPC from 0 friendliness to -80 (Looks at you as an extreme liability). Looking at some debug values it seems this NPC has Altruism -3, which could account for this behavior. However, it seems a bit much that completing a mission for a NPC would make them dislike you even if they aren't charitable (Killing a horrible monstrosity for them would make you at least formidable in their eyes, right?). I think this might be a bug. I wasn't able to check the altruism level of the first NPC that did this to me but the results were the same. NPC hate for mission completion. Debug menu could use some options for modifying NPC personality values for testing this sort of thing.

Current version is: 0.C-13425-g3dcd70b (tiles)

**Comment by baraba3** [comment]
along that i had same experience with finding corporate ledger one and npc relation going down the drain.
