### ISSUE TITLE
(Suggestion) Make mod's monstergroups not override each other.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#16401]
I assume with 0.D around the corner this will take a back seat as non-priority but I might as well get it out there. I am not sure how difficult it would be to implement but it would be very helpful for modders if instead of monstergroups over ridding each other in mods they would instead just be additive. This would work similar to item groups where in a mod you simply add the item to the corresponding itemgroup and it adds it to that item group instead of having to write all the item group again. One work around for this was created by @Malkeus in what he called the CombineMonsterGroups Mod; this mod if loaded last would over write all other mods' monstergroups but it was a combination of many mods' monstergroups.

**Comment by illi-kun** [comment]
What is the difference between this issue and & #14947?

**Comment by Noctifer-de-Mortem** [comment]
Sorry, I did not see that issue, should this one be closed then?

**Comment by illi-kun** [comment]
Yes, please continue discussion in the initial issue.
