### ISSUE TITLE
Need info on what level of lifting equipment needed for vehicle modification

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#16407]
Currently, "lifting equipment" is in red with no indication that you need a better / stronger jack

**Comment by Coolthulhu** [comment]
Also, jacks and cranes share the same message.

**Comment by mugling** [comment]
Agreed. The vehicle requirement code is currently spaghetti but I'm working on a refactoring to use the `requirement` JSON
