### ISSUE TITLE
Having a default name and pressing "Play Now!" overwrites characters of the same name.

### ISSUE THREAD

**Issue by FlamesWillLive** [CleverRaven/Cataclysm-DDA#16419]
Running Build: 4763
It also doesn't inform you its overwriting anything, if its supposed too.
(I'm new to this, sorry if I screwed up somehow, or forgot something)

**Comment by BevapDin** [comment]
Works the same when preparing the character manually. Choosing an existing name overrides the existing save. It should probably inform the player before starting the game and simply decline using that name.

**Comment by Leland** [comment]
This is one of the most insanely frustrating issues I've ever encountered, to be frank.

**Comment by Night-Pryanik** [comment]
I'd say that's not a bug, but a UI missing one prompt.
