### ISSUE TITLE
SDL Refresh Issue, Font Sizing

### ISSUE THREAD

**Issue by Beanzy** [CleverRaven/Cataclysm-DDA#16416]
Cata version: Experimental v. 4764 x64 tiles

Basically a continuation of #15881 (also see [here](http://smf.cataclysmdda.com/index.php?topic=12345.0) for more details).

While #16162 and #16211 fixed most of the issues, there are still some lingering refresh issues caused by having different console and map font size settings in: config > fonts.json.

1st Issue: A black 'box' appears on screen when the headlights/overhead-lights are used in a vehicle. Example below.

![cdda](https://cloud.githubusercontent.com/assets/15885173/14865930/1bc2fc60-0c8f-11e6-9ca6-ab8f14f515b3.PNG)

2nd Issue: A similar black box appears when the "select material" box pops up during crafting.

**Comment by Podesta** [comment]
Are we missing something to merge #16692 ? The bug still persists on 0.C-4936. 
```
   "fontblending": false,
    "fontwidth": 8,
    "fontheight": 16,
    "fontsize": 16,
    "typeface": "Terminus",
    "map_fontwidth": 8,
    "map_fontheight": 16,
    "map_fontsize": 16,
    "map_typeface": "Terminus"`
```
![cdda bug](https://cloud.githubusercontent.com/assets/11512008/15623340/e39a288c-2448-11e6-905b-a925212374d5.png)
