### ISSUE TITLE
MISSION_RANCH_NURSE_3 require 200 vitamins which is obsoleted

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#16424]
With new vitamin system, the quest item is no longer obtainable. Or should we change the description to multivitamins?

PS. The mission system is all hard coded mess. It would be nice to jsonize them so that non coder could add more missions.

**Comment by AppleConnoiseur** [comment]
When i did the quest where you are getting a ranch ledger i noticed it was not tracking it properly with waypoints. Like it points to the one you currently got on you instead of back to the quest giver.

**Comment by Coolthulhu** [comment]
> Or should we change the description to multivitamins

Multivitamins are using the old ID, meaning that they will work for the quest. Only the description needs to be changed.
