### ISSUE TITLE
acidbomb_act needs to be obsoleted 

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#16422]
- [x] Fertilizer bomb and active one have different weight.
- [x] Items with `ACT_ON_RANGED_HIT` should do so when they are hit too (acid bomb).
- [ ] `acidbomb_act` should be moved to obsolete.

Edit by @Leland: moved to checklist

**Comment by illi-kun** [comment]
You merged unrelated issues to one bug report, this isn't a good practice, so please try to avoid this in future (the rule is "one issue = one report").

**Comment by WizardOfOoo** [comment]
1. I put in a PR to fix that, See #20275
2. Acid Bomb works now see #15152
3. I think Acidbomb_Act is needed for the item to work.  @Rivet-the-Zombie was the last one to make changes to acid bomb. Mx Rivet, would you be so kind as to close issue if you fixed it in #15152

**Comment by kevingranade** [comment]
There is now no way to create an acidbomb_act item, so yes it should be obsoleted.

**Comment by Leland** [comment]
Updated title accordingly
