### ISSUE TITLE
Item info should indicate disassembly time

### ISSUE THREAD

**Issue by rriegs** [CleverRaven/Cataclysm-DDA#16421]
Screens that show the "Disassembling this item might yield:" information should also indicate how long it will take to do so, e.g.
```
Disassembling this item might yield:
1 rock, 1 pair of socks
Time to disassemble: 1 minute
```

**Comment by Zireael07** [comment]
That's a very good point.

**Comment by rriegs** [comment]
I've noticed that some items (e.g. electronics) also require certain equipment and/or charges to disassemble, and further, that some disassembly recipes require a considerable amount of some particular skill.  It seems that this information should also be relayed to the user somehow, though adding all of it to the item info screens risks making them even more verbose than they currently are.

**Comment by Night-Pryanik** [comment]
We can easily find room for all this info in popup window.

**Comment by latagore** [comment]
`Disassembling this item takes 1 minute and might yield 1 rock, 1 pair of socks`
might be a tiny bit more brief.
