### ISSUE TITLE
Feed NPC with LSD -> you see hallucination monsters attack you

### ISSUE THREAD

**Issue by 3721assistant** [CleverRaven/Cataclysm-DDA#16425]
If the player is not affected by the chemicals these hallucinations should not appear, I think.

**Comment by nanovad** [comment]
How would the NPC act on LSD? I suppose they could attempt to fight, but they'd just "swipe at air!" or "dodge nothing!" or somesuch?

**Comment by kevingranade** [comment]
That might be fun, but for the time being we should probably just disallow tripping NPCs.
