### ISSUE TITLE
Item pile duplicates when picked up and there is not enough room in inventory

### ISSUE THREAD

**Issue by Suseika** [CleverRaven/Cataclysm-DDA#16433]
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/241617/save.zip)

In this savefile, my character stands on top of a pile of arrows. When I try to pick up those arrows by pressing `g`, they are not picked up, and the number of arrows in the pile doubles.

Version: experimental at 1cb0ee3af2034f880cdd72cd2acc265f54c88ea3

![](https://gyazo.com/0adac8ba5161da4d3b069bcba01829c0.png)

**Comment by FlaKougar** [comment]
Fixed by #16121
