### ISSUE TITLE
Get rid of "Sealed jar of [permafood]"

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16446]
A bunch of recipes result in sealed jars. Sealed jars make sense (though are annoying to deal with) when the contents are perishable, but are totally bad design and pure annoyance for permafood, where jar could only count as a tool.

* Sauerkraut
* Pickled meat
* Pickled veggy
* Pickled fish
* Pickled punk

Also, sealed jars can result in #16322. Out of the above, only sauerkraut seems to cause it.

The best way to solve it would be to rework sealedness as an item tag removed on access, as this would also allow making cans into buckets and make the whole thing less annoying. But that's just for the non-permafood recipes, permafood shouldn't go into jars at all.

**Comment by mugling** [comment]
> Out of the above, only sauerkraut seems to cause it.

That sounds worryingly like the bug involves undefined behavior

**Comment by harald921** [comment]
I definitely agree. Permafood shouldn't go into jars. No point from a gameplay perspective, and just confusing for the player.

**Comment by mugling** [comment]
@Coolthulhu was this fixed by your sealed container PR?

**Comment by Coolthulhu** [comment]
Mostly - sauerkraut still has it because it has the horrible delayed transform mechanic. But that's a special case.
