### ISSUE TITLE
npc dialog: "special talk" actions cause repeated give/use item action

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#16443]
1. Talk to an NPC follower.
2. Ask him to hold an item (h hotkey).
3. Give him an item or exit w/o giving him an item.
4. Perform "special talk" action e.g. size up the NPC (Shift+S hotkey).
5. Say "Okay" on the following prompt.

Expected result: Return to TALK_FRIEND main dialog

Actual result: User is prompted to give an item. (TALK_GIVE_ITEM is repeated)

Also affects TALK_USE_ITEM.

TALK_USE_ITEM and TALK_GIVE_ITEM are a bit complex due to the sequence of multiple npc/player dialog iteractions that take place. The end result is that TALK_USE_ITEM (or TALK_GIVE_ITEM) is at the top of the dialog stack when their dialog sequences are complete. The "special talk" dialog options, upon completion, push TALK_NONE to the dialog topic stack, causing the last dialog option to repeat.

**Comment by lucianposton** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/16444 creates a topic category for TALK_FRIEND, TALK_USE_ITEM, and TALK_GIVE_ITEM. With that merged, a roundabout/risky way to solve this would be to collapse topic categories more aggressively (See https://github.com/CleverRaven/Cataclysm-DDA/blob/7178ce84833052635a8b5182e849983819f21f3e/src/npctalk.cpp#L319-L322 ) so that the oldest topic is used instead of latest. Could very well break other topics that don't expect that behavior.

**Comment by lucianposton** [comment]
Now that I think about it, this could affect dialog topics besides give/use item. The issue may be more general.

**Comment by mugling** [comment]
Recent rewrite of affected code. Please re-open if reproducible in `master`
