### ISSUE TITLE
Ruger 10/22 magazine clone bug.

### ISSUE THREAD

**Issue by slawr34** [CleverRaven/Cataclysm-DDA#16445]
#When reloading a magazine inside a Ruger 10/22 with a magazine in your inventory, the below bug occured and additionally - whilst my Ruger 10/22 was reloaded successfully and the depleted/empty magazine was added to my inventory - I would gain an additional magazine of the same type/ammunition type/rounds within the magazine.

> Debug: Tried to remove an item from a character who doesn't have it
> 
> Function: virtual void item_location::item_on_person::remove_item()
> File: src/item_location.cpp
> Line: 216

**Comment by slawr34** [comment]
0.C-13528-g13127dc sorry, forgot the version. It only seems to happen when the mag is 4/10 full.

**Comment by hesu** [comment]
Has it been fixed? I was unable to reproduce.

**Comment by DLaboratory** [comment]
RM88 Battle Rifle with RMBG100 magazine also reproduces this issue. Reload the gun, then the same debug message jumps out. Both builds by MinGW from latest commit and MSVC from my PR has the problem.

**Comment by mugling** [comment]
Many recent changes. Anyone reproduce this in a recent copy of `master`?

**Comment by DLaboratory** [comment]
I didn't reproduce this issue in the latest `master` branch (9e2ccb1a).

BTW, it seems that #16771 is a duplication of this issue.

**Comment by BorkBorkGoesTheCode** [comment]
0.C 15158 g1dbdddb
spawn 4 mp5 magazines, 1 mp5, and 4 stacks of 9mm jhp.
wield gun, r load mag 1 into the mp5, r load the mp5 with cartridges, r switch to mag 2,  store mag 1 in inventory, load mag 2 with cartridges, switch to mag 3, ERROR.

Tried removing item from object which did not contain it.
item visitable<T>: : removeitem (item&) [with T = character]
file src/visitable.cpp
line 427

and another error message for line 234

**Comment by DLaboratory** [comment]
I found a simpler way to reproduce the error:

 

1.     Spawn a H&K MP5 and an empty magazine.

2.     Wield the gun, [r]eload the empty magazine, then ERROR.

**Comment by BorkBorkGoesTheCode** [comment]
Something must have changed, because it only happens in the order I described.

**Comment by DLaboratory** [comment]
> Something must have changed, because it only happens in the order I described. It is completely reproducible.

I can reproduce the issue by the simpler method in the commit yesterday (9e2ccb1ac8f1ed236f775d0e4cfc93a6e3dee621).

**Comment by Lord-Helmchen** [comment]
as of 5313, this happens reliably to me.
new world, mods 
spawn Glock 22, 2 Glock. 40S&W mags, a few .40 bullets.
reload gun with mag, reload mag-in-gun with bullets, reload gun with empty mag from inventory.
-> DEBUG: item location does not point to valid item
FUNCTION: void item_location::remove_item()
FILE: src/item_location.cpp
LINE: 546

**Comment by mugling** [comment]
That `debugmsg` was added by #17732 although the bug is older. Prior to that PR I suspect the game went on to clone or otherwise mishandle an item.

**Comment by mugling** [comment]
Can reproduce
