### ISSUE TITLE
Wheel size is not displayed in the vehicle examine menu

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16452]
Wheels still have bigness at the moment. They should either gain bigness display back or lose bigness altogether.

The latter would probably be a better solution. Wheel sizes don't differ too much and different sizes only serve to introduce weirdness (like cars with steerables of one size and non-steerables of the other) and trigger OCD.

**Comment by mugling** [comment]
The plan is to drop variable bigness entirely. Item inheritance is a cleaner solution

**Comment by Night-Pryanik** [comment]
Wheel size is displayed by hovering over tile with wheel. Bigness was dropped some time ago.
