### ISSUE TITLE
LOS issues

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#16453]
Current master at 11bb7bb

Notice how I've a huge line of sight even though I'm against the wall of the building. The building's walls should block los.

![beforer](https://cloud.githubusercontent.com/assets/646121/14933978/e70ee772-0e55-11e6-833e-edde1285abdb.png)

**Comment by Coolthulhu** [comment]
Looks like clairvoyance to me.

**Comment by lucianposton** [comment]
Oh, that was it. Didn't know clairvoyance was a thing. Thanks
