### ISSUE TITLE
Engine power is specified separately from other engine stats

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16462]
Engines lost their bigness parameter, which is now per-itype. But each itype can only be attached as one kind of part.

All engine stats related to actually being used as an engine should be in one place. That is:
- Power
- ePower
- Fuel type

The rest can be specified where it fits more, but those 3 stats should be together.

**Comment by mugling** [comment]
Yes, I'm actively working on this at the moment

**Comment by illi-kun** [comment]
This was modified in #19275.
