### ISSUE TITLE
CBM feature duplication

### ISSUE THREAD

**Issue by AppleConnoiseur** [CleverRaven/Cataclysm-DDA#16467]
After playing for a while with my most successful character so far i can't just help to notice that the **Power Armor Interface CBM** kinda duplicates features of the **UPS CBM**. Except that it doesn't power UPS modded equipment.

Am i using it wrong or is incomplete feature wise?

**Comment by Coolthulhu** [comment]
It was cheaper to use at one point. Plus, UPS is far more useful, as it can be used for everything else. I don't think that's enough to excuse its existence, though.

We certainly don't need two armor interface CBMs that only differ by energy cost.

**Comment by AppleConnoiseur** [comment]
Could differentiate it by making it remove the encumbrance penalty entirely from the gear instead of 10. Considering it is connected directly to its user with access to nervous system and brain.

Turning it into a passive that way.

Also  i want to be able to wear jumpsuits underneath power armor xD.

**Comment by John-Candlebury** [comment]
+1 for fallout plugsuits err brotherhood of steel uniforms.

**Comment by Leland** [comment]
Looks like discussion has stalled on this suggestion. Closing. If there's still interest, let me know and I can reopen.
