### ISSUE TITLE
"Unknown comestible type of item: campfire hot dogs (hot)" error

### ISSUE THREAD

**Issue by Ishindri** [CleverRaven/Cataclysm-DDA#16460]
When cooking and eating hot dogs, the following error is displayed. Win 7x64 w/tiles, build 4774.

![error](https://cloud.githubusercontent.com/assets/5974640/14937702/b30168d2-0edd-11e6-87a9-2c5c11c5bc36.PNG)

**Comment by Cyrano7** [comment]
Is this a older game you updated to build 4774? and do you have the more survival tools mod installed? What type of hot dog specifically were you trying to eat? The campfire one or the one with the bun?
