### ISSUE TITLE
Mutation control UI does not draw properly when switching to examine

### ISSUE THREAD

**Issue by Tyralocus** [CleverRaven/Cataclysm-DDA#16468]
I'm using the latest tiles experimental, build 4782, but already noticed this yesterday (I believe build 4778). When opening the mutation control UI, everything looks fine. In my current game, I have a dozen or so passive mutations and two active ones. When switching to "examining" mode, using the default '!' hotkey, the bottom half of the screen turns black and the entire screen becomes unresponsive. It's possible to escape out of this (or hit '!' again), but makes it impossible to examine mutation descriptions.

I'm no expert, but possibly related to this?
https://github.com/CleverRaven/Cataclysm-DDA/pull/16432

**Comment by illi-kun** [comment]
I'll take a look.

**Comment by illi-kun** [comment]
I've tested the discussed menu and it works fine for me.

Is it possible to show me some screenshots of the issue? Did you tried to press symbols (invlets) associated with mutations to see their description?

**Comment by Tyralocus** [comment]
I tried resizing the terminal (to approximately half size of the screenshots) to see if that would make a difference, and no luck. I also tried pressing the invlets, and they appear to do nothing when in the "examining" state, or at least there are no changes on the screen.

Here's after injecting some random serums from a lab:
![1](https://cloud.githubusercontent.com/assets/9115556/14941809/739c589c-0fa9-11e6-97d2-b78f24da1330.jpg)

And then when I hit '!":
![2](https://cloud.githubusercontent.com/assets/9115556/14941811/7ad24036-0fa9-11e6-98d0-13dd132cc666.jpg)

**Comment by illi-kun** [comment]
Thanks for snapshots. I'm able to reproduce this in Windows version (with tiles) emulated in Wine.

**Comment by illi-kun** [comment]
@Tyralocus could you confirm that ```current master``` version works properly for you?

**Comment by Tyralocus** [comment]
It works perfectly now, @illi-kun, great job!

**Comment by illi-kun** [comment]
Thanks for descriptive bug report & confirmation.
