### ISSUE TITLE
Liquid handling limitations

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16478]
* After uncrafting an item that has liquid components, the selection of containers is much more limited than for successful crafting - it seems that only the current inventory is offered. Most easily seen with car battery uncrafting
* After successful crafting of a liquid ammo item, it can't be loaded into tools, at least tools that aren't in the inventory. Pretty sure it was a feature at one time. For example, lamp oil cooker can't be loaded with freshly crafted lamp oil

**Comment by codemime** [comment]
Both are possible now. Looks like #16995 and #17348 together did the trick. The issue can be closed.
