### ISSUE TITLE
"Tried to set invalid ammo none for [UPS item here]"

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16485]
Happens every time I use the welder for car repairs. Doesn't actually make it not work or not take charges - indeed I didn't see it cause anything more serious than the debugmsg.

Saving and loading didn't fix it. It didn't look weird in the save, except for the fact that it has no `"curammo"` field.

EDIT: Same thing happens for electric forge. I assume it affects all UPS items right now.

**Comment by Lazasar** [comment]
Sounds a lot like the bug I submitted - #16160

**Comment by Coolthulhu** [comment]
It's probably the same bug, I'll rename it to make it more general.

**Comment by baldamundo** [comment]
I'm getting this as well. Seems ostensibly kinda inconsistent - doesn't trigger for most things charging in my car, but everytime I use the soldering iron thats charging there the error pops up, and I get spammed with it if something's charging in my inventory. Seems as if everything's actually working though.

P.S. Not played in ages and am amazed by all the progress on the game! (as usual, not bothered to post anything until something breaks...)

**Comment by Coolthulhu** [comment]
I think it may be caused by UPS item using its last charge. This would trigger setting ammo type to 0, but UPS charging code probably doesn't set the ammo type back.
