### ISSUE TITLE
Gun sights balancing

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16480]
* Improved iron sights, which are easy to craft and are listed in every gun book, have 45 dispersion
* Only holographic sights and scopes have less than 45 dispersion
* Rail laser sights do not allow improving accuracy even over (some) unmodded guns
* Red dot sight is less accurate than plain improved iron sights
* Underbarrel laser sight is strictly better than rail one when it comes to aim speed and accuracy

Is all of this intended? It means that generally there is only one step up in accuracy: when the player finds a scope. It also means that someone who can barely use a gun (say, some practice with BBs) can improve its iron sights over the factory ones.

**Comment by illi-kun** [comment]
Discussion in #14230 can be somehow related to the current topic.

**Comment by Coolthulhu** [comment]
Oh, I see why are those two laser sights different:
Underbarrel slot is much more useful than rail slot. Rail allows installing only the rail crossbow or the rail laser, while underbarrel allows a forward grip.

**Comment by mugling** [comment]
Recent aiming PR dealt with this
