### ISSUE TITLE
food and some other misc things have a black foreground text color on Solarized

### ISSUE THREAD

**Issue by mischief** [CleverRaven/Cataclysm-DDA#16494]
somewhere since ee17562 (according to git reflog), food now has a black text color when it used to be white.

my color scheme is Solarized dark, on xterm, so maybe cataclysm makes a lot of assumptions that are incompatible with it. other notable things are old message log entries, recipies and constructions that can't be crafted.

overall it makes things very hard to read.

perhaps foreground color of some things could be changed to make them more visible in solarized dark? or should i find another colorscheme to play cdda under?

![2016-05-02-213006_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1487996/14974711/5d49ccd2-10ad-11e6-8f04-7910b9e31f7f.png)

**Comment by kevingranade** [comment]
The fix here is to either change your terminal settings or to adjust
cataclysm's color settings

**Comment by Coolthulhu** [comment]
The color is dark gray. Most of the color schemes have readable dark gray.

Solarized doesn't look too good to play DDA in - just look at how everything looks in the dark. You could use the color manager (?->4) to change the dark gray to something else or just give it a background.

**Comment by mischief** [comment]
seems reasonable to use color manager.
