### ISSUE TITLE
Soda Can Stove Kit / Ethanol charges very wrong

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#16529]
The description of the Soda Can Stove Kit says it includes a 500ml bottle to hold fuel, but the charges are way way less than a 500ml bottle holds.  The quantity may be for balance, but if so the description should be changed to just Plastic bottle rather than specifying a volume.

Existing charges: 28 units of ethanol
500ml bottle holds: 500 units of Ethanol

**Comment by Xpyder** [comment]
btw, for real life comparison, 500ml of ethanol (or realistically denatured alcohol) will properly boil approximately 7.5l (30 game units) of water long enough to sanitize it.

that would be 90 charges of denatured alcohol in a 500ml bottle

**Comment by Xpyder** [comment]
Based on the above, I'd say both the game units for ethanol and the holding capacity of the Soda Can Stove kit are wrong.  The Stove kit should probably be increased to 90 units, but not sure how best to handle the unit conversion for ethanol storage.  Maybe make it easy to convert to denatured alcohol and change the units per volume of that, and require the stove to use that instead?

**Comment by Hague** [comment]
Why not just add the fuel alcohols to the same ammunition group "fuel alcohol" so the stove can use denatured alcohol the same as ethanol? It still burns (relatively) the same.

**Comment by Xpyder** [comment]
Stove already uses fuel alcohol.  The issue is the quantities are WAY WAY off.

**Comment by Coolthulhu** [comment]
The problems started when alcohol values got rescaled to use same values as gasoline and lamp oil.

I'd just allow stupidly efficient ethanol. Compare to other stupidly efficient energy sources:
* Gasoline cooker lets you disinfect water with just 2 ml of gas
* Lamp oil cooker allows the same with just 2 ml of lamp oil, which in turn is made from 2 ml of cooking oil, tallow or 4 ml of tainted tallow
* Vehicle-mounted hotplate in RV kit on a vehicle with an alternator lets you turn 1 ml of gas into something like a hundred charges of electric power, which is enough for 10+ liters of water
* Ethanol/denaturated alcohol is noticeably more valuable than lamp oil, as lamp oil can't be used to craft bandages for infinite healing

It's not good for balance to have all those weird effects going on, but soda can stove is already the most expensive one of those to maintain, only being beaten by the battery hotplace.

It would have to be solved by a charge consumption multiplier or something like that.

**Comment by Labtop-215** [comment]
Could we get more capacity on this soda can stove kit?  Or perhaps a hotplate that takes denatured alcohol (or actually takes ethanol!) with a better capacity for this stuff?

The real problem with trying to use ethanol or denatured alcohol, is that by the point that I can use this stuff as a source of fuel, I can also use lamp oil, and it's just infinity easier to use lamp oil.

Basically denatured alcohol requites that you either start with 3 cooking, or it requires a chemistry textbook to know the recipe, and either a basic (or better) chemistry set or a still, alcohol, and 60 charges of fuel if you aren't using a fire.

By comparison, lamp oil requires reaching 4 cooking (not hard to reach something-cooking oil), a pot, and 20 charges of fuel if you aren't using a fire.  Oh, and it's hotplate equivalent can hold 800 charges.

Heck, all I really want is an hotplate type object that can use alcohol and has more capacity, something comparable to the lamp oil or gasoline cooker.

**Comment by Barhandar** [comment]
It already can use ethanol, denaturate is an inherited object from that.
