### ISSUE TITLE
Vehicle from Scratch attempt failed due to inacessible steerin wheels.

### ISSUE THREAD

**Issue by Shudokai** [CleverRaven/Cataclysm-DDA#16520]
Been trying to build a Vehicle entirely from scratch, the only part I can't craft myself is steering wheels.

I don't think it's unreasonable for a Survivor of modern times to be able to think of a simple steering mechanism for cart wheels or similar.

It seems like most scavengable wheels have an option to be installed as steerable wheels with no additional cost, but that doesn't apply to crafted early game wheels.

**Comment by kevingranade** [comment]
Please propose an actual mechanism, "a simple  steering mechanism for cart
wheels" doesn't have enough detail to act on, it should be based on
something that actually exists and works.

**Comment by Shudokai** [comment]
http://www.buildyourowngokart.com/oneperson/FrontWheelSteeringAssembly.php

That would be a reasonable example.

Other than that there is the probably simplest steering mechanist I could think of: The one used in Bobby cars for example, where a turn of the steering wheel would not rotate the wheels individually but the entire axle, it wouldn't make for excellent turning capabilities but it would allow a Vehicle like that to turn at all and it doesn't need any advanced engineering skills, it is basically a bunch of pipes attached to the steering wheel with another pipe running through it with the wheels sitting on top.

I don't see no difference in gameplay quality of life reasons or realism reasons between selfmade wooden wheels and a bicycle wheel for example.

**Comment by kevingranade** [comment]
> http://www.buildyourowngokart.com/oneperson/FrontWheelSteeringAssembly.php

This is perfect, thanks! And even a part list!
I'm not sure the wagon wheel type thing is worth dealing with considering how simple the go-kart linkage is.

> And before I forget ... bycicle steering is pretty darn simple.

It's actually not, the tolerances are pretty crazy.

**Comment by 321nick** [comment]
> It's actually not, the tolerances are pretty crazy.

i think he means the concept, a rotatable stick connecting too a wheel.

**Comment by kevingranade** [comment]
I misunderstood anyway, he was referencing bikevwheeks, not a bike steering
assembly.
However I stand by a bicycle steering assembly not being easy to make.

**Comment by Leland** [comment]
Looks like discussion has stalled on this topic. Closing. If there's still interest, let me know and I can reopen.
