### ISSUE TITLE
Cooked fish does not have nutrition value and vitamins

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#16523]
Cooked fish does not have a nutrition value and vitamins. It also has volume 0 and weight 0.
See the screenshots below. The second screenshot is made after eating a cooked fish.
http://imgur.com/a/MdbSw

To fix this problem, the line 
"copy-from": "fish",
should be added after the line
"id": "fish_cooked",
in the file 
data/json/items/comestibles/carnivore.json

I do not know how to commit the change, so I will not commit it at least for the next few days. Please commit it if you can.

**Comment by Rivet-the-Zombie** [comment]
>On the first screenshot, the fish is both 'cooked fish (hot)' and 'cooked fish' at the same time, which also seems wrong.

All items work like this; the top is the displayed name with all the bells and whistles added on, like (hot) or an engraved name. The bottom part is the base item name.

**Comment by tsulh** [comment]
> All items work like this;
Thanks for pointing it out. I removed this part from the problem description.

**Comment by mugling** [comment]
This is already resolved in `master` as part of a separate PR
