### ISSUE TITLE
Unknown comestible type of item: cooked fish (hot) 0.C-4758

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#16525]
![hotfish-error](https://cloud.githubusercontent.com/assets/19196781/15032516/c33988d8-122f-11e6-8872-b6ca920afef9.JPG)

**Comment by illi-kun** [comment]
As it stated [here](https://github.com/CleverRaven/Cataclysm-DDA/issues/16523#issuecomment-217007304), it's already fixed. Feel free to re-open if it happens to you in the ```current master```.
