### ISSUE TITLE
Chesthole32: Many rifles are using pistol sprites

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#16530]
Several rifles are using the M1911 sprite. The rifles affected are:

- M1903
- Browning Automatic Rifle
- M1 Garand

This issue affects all versions of Chesthole32 included in mainline from experimental 0.C - 12634 - gce8cc6c onwards.

**Comment by lucianposton** [comment]
@Chezzo fyi
