### ISSUE TITLE
"dudereally" and "buddyreally" are used to address player

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#16533]
I noticed NPCs addressing the player as "buddyreally". I briefly looked at the code, and seems like it might be a bug. I believe I saw "dudereally" also, but don't have a pic.

![beforer](https://cloud.githubusercontent.com/assets/646121/15038825/2fd69a90-125c-11e6-8cb8-c4963e9ac405.png)

**Comment by Coolthulhu** [comment]
Could be the same bug as #16437. Some of the snippets have other snippets nested in.

**Comment by Coolthulhu** [comment]
Now that #16437 is fixed, this one should be too.

**Comment by Rivet-the-Zombie** [comment]
Dudebuddy!

**Comment by lucianposton** [comment]
That appears to be the fix. I'll reopen if I encounter it again.
