### ISSUE TITLE
Small problem with exceeding volume limit while pouring liquid in resizable containers

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#16538]
Steps to reproduce:
1. Unload liquid into a sealed stomach that is in your inventory, so that the volume of the stomach would increase, and the inventory volume limit would be exceeded.
2. Try to put some items on a neighbouring cell. Get a error in the ingame-console and a message that some items tumble to the ground.

The items probably should tumble right after you unload liquid to the stomach, and the error should not appear.

**Comment by kevingranade** [comment]
Even better, have it stop pouring if the inventory s volume limit would be exceeded.
