### ISSUE TITLE
Meat jerky gives more nutrition and vitamins than cooked meat

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#16536]
From 1 raw meat, we can cook 3 meat jerky (12 nutrition each) or 1 cooked meat (28 nutrition).
The fact that meat jerky gives 8 more nutrition points seems unrealistic.
But the worst part is that each jerky piece gives as much vitamins as 1 cooked meat, so it also gives 3 times more vitamins... unless vitamins values are relative to weight/volume?

upd: Canned meat (made from 1 piece of raw meat) gives 50 nutrition (cooked meat was giving the same 50 only a few days ago).

**Comment by AppleConnoiseur** [comment]
Would not be bad for jerky being nerfed in nutrition and vitamins if you could craft them in the same way of leather and fur.

1 hour ingame now for what it does is kinda fair i guess.

**Comment by Headjack** [comment]
Is cooked meat no longer 50 nutrition? I'm in favor of encouraging more complex cooking, but that seems like the wrong direction.

**Comment by Leland** [comment]
Looks like discussion's stalled on this suggestion, closing. Feel free to let me know if you want it reopened; or just create a new issue.
