### ISSUE TITLE
Eating seeds gives the same amount of vitamins as the entire plant

### ISSUE THREAD

**Issue by sanyaskillpro** [CleverRaven/Cataclysm-DDA#16546]
For example you can craft dandelion seeds from raw dandelions and eat them, bypassing the nutrition and morale penalties.
With wild veggies you can even double the amount because 1 veggie crafts into 2 stems.

**Comment by Headjack** [comment]
Oh, good tip. Should probably be reduced though.

**Comment by Coolthulhu** [comment]
Seeds shouldn't really be edible at all.

**Comment by karols146** [comment]
Or maybe it should be edible, but need more penalties  , or even a stomach problems.

**Comment by Coolthulhu** [comment]
Allowing eating seeds in most cases only pollutes the menu with unnecessary entries that no one ever selects, except as a mistake.

**Comment by Leland** [comment]
This thread hasn't seen an update in about a year. Closing for now. If anyone is still interested, I can reopen... or feel free to just make a new issue!
