### ISSUE TITLE
Dismantled car headlights spawn with batteries

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16547]
Car headlights are flashlights and flashlights by default spawn with 100 charges of batteries.

**Comment by Rivet-the-Zombie** [comment]
The best fix for this would be to have an actual 'car headlight' item, since the flashlight thing is completely ridiculous.

**Comment by AppleConnoiseur** [comment]
> The best fix for this would be to add an actual 'car headlight' item, since the flashlight thing is completely ridiculous.

Sounds well needed. Could pretty much just have the same crafting components with maybe a little more more copper wire and metal needed.

**Comment by Mshock777** [comment]
We should also add light bulbs: used in flashlights, floodlights, car lights, maybe searchlights, fridges,..

**Comment by Coolthulhu** [comment]
Many of those specifically mention LED lights, not bulbs.

**Comment by Mshock777** [comment]
I only found it being mentioned for heavy flashlight, and even so we can assume that by the year the game starts LED bulbs are used almost everywhere.
And if we can't, normal and LED lights can probably used interchangeably.
