### ISSUE TITLE
MSYS2 CMake compilation failure

### ISSUE THREAD

**Issue by i2amroy** [CleverRaven/Cataclysm-DDA#16542]
Right now I'm getting this whenever I try to compile:
```
CMakeFiles\cataclysm.dir/objects.a(init.cpp.obj): In function `DynamicDataLoader::unload_data()':
D:/Github/Cataclysm-DDA/src/init.cpp:366: undefined reference to `reset_overlay_ordering()'
CMakeFiles\cataclysm.dir/objects.a(init.cpp.obj):init.cpp:(.rdata$.refptr._Z21load_overlay_orderingR10JsonObject[.refptr._Z21load_overlay_orderingR10JsonObject]+0x0): undefined reference to `load_overlay_ordering(JsonObject&)'
CMakeFiles\cataclysm.dir/objects.a(player.cpp.obj):player.cpp:(.rdata$.refptr._Z33tileset_mutation_overlay_orderingB5cxx11[.refptr._Z33tileset_mutation_overlay_orderingB5cxx11]+0x0): undefined reference to `tileset_mutation_overlay_ordering[abi:cxx11]'
CMakeFiles\cataclysm.dir/objects.a(player.cpp.obj):player.cpp:(.rdata$.refptr._Z30base_mutation_overlay_orderingB5cxx11[.refptr._Z30base_mutation_overlay_orderingB5cxx11]+0x0): undefined reference to `base_mutation_overlay_ordering[abi:cxx11]'
collect2.exe: error: ld returned 1 exit status
```

Is anyone else having this issue? Some digging on the [abi:cxx11] seems to point to it being a problem when trying to combine gcc 4.9 and gcc 5+ compiled libraries, but I'm not seeing any in that particular bit of code.

If anyone has any ideas I'd greatly love to hear them, because at the moment my last resort seems to be quickly becoming "install Linux, then rebuild your entire development environment". :P

**Comment by kevingranade** [comment]
Possibly dumb question, have you cleared out all previous build artifacts
before building? Otherwise not familiar with that error, good luck.

**Comment by i2amroy** [comment]
Yeah, cleaned out everything. :/

**Comment by narc0tiq** [comment]
Since you're using CMake, did you try adding `src/overlay_ordering.cpp` to `src/CMakeLists.txt`? It doesn't seem to be present in latest master.

**Comment by i2amroy** [comment]
Adding that (and a few other files) seems to have fixed the problem. Thanks! :D
