### ISSUE TITLE
Using RELOAD_AND_SHOOT weapons takes very long time

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16545]
Even at 10 archery, when firing a single arrow from a quiver (until #16486 is merged, full quivers will be slower than almost-empty ones), the time to draw a single arrow is almost a full turn.

It is even worse in case of RELOAD_AND_SHOOT weapons that have no quivers, for example slings. At 10 skill, a single pebble takes 137 moves just to reload, then about half that to fire.

Since most RELOAD_AND_SHOOT weapons are rather weak, it would be better to just hardcode some lower cost for them than to try to balance the same formula against weapons and ammo.

**Comment by Rivet-the-Zombie** [comment]
>It is even worse in case of RELOAD_AND_SHOOT weapons that have no quivers, for example slings. At 10 skill, a single pebble takes 137 moves just to reload, then about half that to fire.

Some sort of pouch made to carry sling bullets would be good as well.

**Comment by Shudokai** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/16537

**Comment by Soyweiser** [comment]
This is probably what caused #12588 so will close that issue.

**Comment by Coolthulhu** [comment]
I am trying to fix the clunky reloads and I've noticed something weird:
When selecting ammo options from a quiver, both `parent` and `target` point to the same item, which is the bow.
There is no way to get the container for the item without searching all items to find the actual parent.

This is misleading, really ugly and also deadbeat parenting.
