### ISSUE TITLE
Firearm actions

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#16566]
Whilst working on #16488 I noticed that our current `gunmod` system allows creating fully-automatic revolvers and other such impossibilities.

We could do with adding an `action` field to `gun` that mods can use to check their compatibility. Possibly some flags `RELOAD_EJECT` could also be made obsolete following this.

What actions exist that we should attempt to model? Any suggestions @Rivet-the-Zombie et al?

**Comment by BorkBorkGoesTheCode** [comment]
Wikipedia has a list: https://en.wikipedia.org/wiki/Action_(firearms)

**Comment by mugling** [comment]
Sure. We need to decide which to model though and what their in-game characteristics would be.

**Comment by BorkBorkGoesTheCode** [comment]
The simplest start would be to clone STR_RELOAD for manual action firearms.

**Comment by mugling** [comment]
I suppose `RELOAD_AND_SHOOT` is technically an action for our purposes as bows are type `GUN`

**Comment by Coolthulhu** [comment]
> We could do with adding an action field to gun that mods can use to check their compatibility. Possibly some flags RELOAD_EJECT could also be made obsolete following this.

I'm against bundling traits together with high-level descriptors. This only causes problems when an item needs to have only some of the properties.
Action sounds like a set of properties, not a property itself.

Preventing full-auto revolvers would be better handled with just a "NO_BURST" flag. Then gunmods could have flags_required and flags_conflicting fields to prevent installing them on those weapons.

**Comment by BorkBorkGoesTheCode** [comment]
To my knowledge, autorevolvers are only limited by the fact that the revolving cylinder needed to take advantage of burst fire is less space-efficient than the spring magazine.

**Comment by mugling** [comment]
> This only causes problems when an item needs to have only some of the properties

That can be handled via a separate action that covers that scenario. At either end of the spectrum is overly specific properties or tag soup (many flags with only a single occurrence).

> Then gunmods could have flags_required and flags_conflicting fields to prevent installing them on those weapons.

This is a good idea regardless and trivial to implement.

**Comment by BorkBorkGoesTheCode** [comment]
Some bolt actions can be reloaded using stripper clips.

**Comment by mugling** [comment]
That doesn't change their action though

**Comment by BorkBorkGoesTheCode** [comment]
I mentioned that because bolt-actions are currently defined by their RELOAD_ONE flag.

**Comment by BorkBorkGoesTheCode** [comment]
Sorry, I thought that bolt actions were defined by RELOAD_ONE in game.

**Comment by mugling** [comment]
No need to apologise - the issue I want to address is that many of flags have multiple meanings and it's a source of frequent confusion and errors. The question is what groupings of flags can be combined into actions without being overly restrictive

**Comment by Rivet-the-Zombie** [comment]
I'm not sure I understand what the benefit would be, grouping a bunch of flags under singular entries like that. Coolthulhu's suggestion about a straightforward 'NO_BURST' flag sounds a lot easier to implement, and easier for people to understand when adding new content.

**Comment by kevingranade** [comment]
I tend to agree with Coolthulu and Rivet here, but let's list out some
actions and some properties to at least see what it looks like.

Breech: integral single-round magazine, ejects casings on reload. Can't jam.

Double-barreled breech: as above but can hold two rounds.

Tube magazine lever action: integral magazine holding a number of rounds,
ejects casings when firing, very long reload time, slow firing.

Tube magazine semi auto: as above but faster firing.

Revolver: integral (usually) magazine holding a number of rounds, ejects
casings on reload. Has single- and double-action variants, the difference
is probably irrelevant to dda other than perhaps firing speed. Main
adjustment to firing speed accomplished with basic maintenance and handling
skill.

Box magazine semiautomatic action: compatible with specific magazines,
ejects casings when firing, fast reload of new magazine, potential to
tamper with action to adjust firing speed with side effects like excessive
jamming.

I'm not seeing any traits that I wouldn't want to call out on a per gun
basis, they pretty much all need tweaking, all the integral magazines need
sizes for example.

**Comment by mugling** [comment]
`modes`, `flags` and limited use of `abstract` to group them is a better solution that my original plan
