### ISSUE TITLE
honey ball and honeygold brew cannot be obtained in game

### ISSUE THREAD

**Issue by remyroy** [CleverRaven/Cataclysm-DDA#16569]
The item **honey ball** (id = `honey_ant`) is used to craft **honeygold brew** (id = `honey_gold`) but it cannot be obtain in game. It does not drop from any monster and it does not spawn anywhere.

The item **honeygold brew** (id = `honey_gold`) does not drop from any monster and it does not spawn anywhere.

They should probably be removed.

**Comment by Mecares** [comment]
Would not implementing a way to acquire them benefit the game more?

**Comment by Headjack** [comment]
Sounds like it's supposed to be [https://en.wikipedia.org/wiki/Honeypot_ant](https://en.wikipedia.org/wiki/Honeypot_ant)

**Comment by Rivet-the-Zombie** [comment]
>They should ~~probably be removed~~ added to item spawn lists.

That's better.

**Comment by Headjack** [comment]
I'd say, make an ant that moves slowly & only appears in Anthill undergrounds, and have them drop the Ball.

**Comment by BorkBorkGoesTheCode** [comment]
Just tell me where to put the drop entry, and I will PR it.
