### ISSUE TITLE
Errors compiling Release

### ISSUE THREAD

**Issue by hickop** [CleverRaven/Cataclysm-DDA#16576]
I'm compiling with:

```
make clean && make RELEASE=1
```

Using g++ 6.1.1 20160501

Errors:

```
src/filesystem.cpp: Dans la fonction ‘bool assure_dir_exist(const string&)’:
src/filesystem.cpp:61:45: erreur : ignoring attributes on template argument ‘int (*)(DIR*) {aka int (*)(__dirstream*)}’ [-Werror=ignored-attributes]
     std::unique_ptr<DIR, decltype(&closedir)> dir {opendir(path.c_str()), closedir};
                                             ^
src/filesystem.cpp: Dans la fonction ‘void {anonymous}::for_each_dir_entry(const string&, Function)’:
src/filesystem.cpp:117:61: erreur : ignoring attributes on template argument ‘int (*)(DIR*) {aka int (*)(__dirstream*)}’ [-Werror=ignored-attributes]
     using dir_ptr = std::unique_ptr<DIR, decltype(&closedir)>;
                                                             ^
g++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra   -Werror -std=c++11 -MMD -c src/explosion.cpp -o obj/explosion.o
cc1plus : les avertissements sont traités comme des erreurs
Makefile:623 : la recette pour la cible « obj/filesystem.o » a échouée
make: *** [obj/filesystem.o] Erreur 1
make: *** Attente des tâches non terminées....
```

**Comment by karols146** [comment]
Try with 4.9.3

**Comment by nanovad** [comment]
Can confirm this happens with GCC 6.1.1.

**Comment by nanovad** [comment]
According to a GCC bug report, ["C++ PATCH for c++/48138 (losing __attribute ((aligned)) on template argument)"](https://gcc.gnu.org/ml/gcc-patches/2011-06/msg01557.html),

> ...except that we don't want to retain attributes on template type arguments, since they aren't part of mangling, so you could get a class template instantiation that is the same type regardless of the alignment of the argument, but the effective argument varies depending on which alignment was first used to instantiate it.

> The PR suggests a warning when we drop the attributes, which makes sense. This patch does not yet provide the warning in the case of function templates, but does for class templates. Warning for function templates will wait until after Nathan's patch to improve template overloading diagnostics.

The compiler just throws an error about this issue now, instead of ignoring it like it used to.

**Comment by heema** [comment]
Can confirm, running Arch
gcc (GCC) 6.1.1 20160501

make RELEASE=1 TILES=1 SOUND=1 LUA=1 USE_HOME_DIR=1


![gcc-err](https://cloud.githubusercontent.com/assets/287527/15454106/ea2f92f4-202e-11e6-867d-c457ae6faecb.jpg)

**Comment by onlurking** [comment]
I was getting this, and this [same issue](https://github.com/CleverRaven/Cataclysm-DDA/issues/16576) error too, while compiling with both clang and gcc.
The issue for me was gcc-libs-multilib, i've switch to gcc-libs on Arch Linux.
Can you check this out?

**Comment by hickop** [comment]
I got a new error now, either with gcc-libs and gcc-libs-multilib:

```
src/mondeath.cpp:82:94: erreur : no matching function for call to ‘min(float, double)’
```
