### ISSUE TITLE
bad bionic from faulty installations

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#16585]
i tried installing some bionics, not quite sure exactly what they were, but i installed 1, and it was faulty, ( i didnt check what the faulty bionic was) i installed another one, it was success , and then i installed another faulty one, and i got a bad bionic (i only checked bionics screen after doing the installing)
im doing this in build 4824

**Comment by Labtop-215** [comment]
So what is the problem here?

**Comment by 321nick** [comment]
a bad bionics description is something along the lines of "this bionic was not setup properly, this is a bug"

**Comment by illi-kun** [comment]
Your savefile could be useful.

**Comment by 321nick** [comment]
the char died a while ago, and i deleted the world. regardless, its a small bug. maybe i need too do some more testing of it, should i close this for now?
