### ISSUE TITLE
Hopper fed automatic guns / ammo hopper gun mod

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#16589]
basically, theres a thing where you have a hopper that funnels bullets into a gun, and the hopper is attached too the gun and doesent detatch, and its basically a automatic gun with a internal magazine, so it doesent need multiple magazines. also, you can reload bullets fast because you can just drop them in the hopper, im not sure if it should be each bullet individually loaded, or untill the hopper is full, but i think it would be a neat addition. examples: https://www.youtube.com/watch?v=JH9VQGht8CU http://www.forgottenweapons.com/light-machine-guns/kubynov-hopper-fed-dp28/  http://www.forgottenweapons.com/wp-content/uploads/2011/03/DPKubynov4.jpg (this picture shows bullets in the hopper, without magazine or stripper clip or etc)

**Comment by cainiaowu** [comment]
From wiki:
https://en.wikipedia.org/wiki/Type_11_light_machine_gun

>The inherent disadvantage of the hopper was that the open feeder box allowed dust and grit to enter the gun, which was liable to jam in muddy or dirty conditions due to issues with poor dimensional tolerances, which gave the weapon a bad reputation with Japanese troops.[6] Another issue was that the weight of the rifle cartridges in the side-mounted hopper unbalanced the weapon when fully loaded. To compensate, the buttstock was designed in a way that it bent to the right, leading to the Chinese nickname for the weapon "bent buttstock" (Chinese: 歪把子). Reloading the weapon during an assault charge proved impossible due to the clip feeding system.

Could we correctly model the jamming in our current gun system?

**Comment by 321nick** [comment]
it can maybe allow a chance too jam regardless of ammo used when the gun is being fired, if thats possible?

**Comment by mugling** [comment]
> Could we correctly model the jamming in our current gun system?

I'm working on it
