### ISSUE TITLE
"Truck stop" has crazed underground noise

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#16599]
I am not fully sure how to report this issue.

There seems be a truckstop kind of location. It has a church, and a motel, grocery, double garage attached to a gas station, etc.

With Z-levels turned on there is an incredible amount of noise spam filling the UI to the extent that you can't see what the heck is going on. I also can't figure out how to go down a level and see whats down there

**Comment by Labtop-215** [comment]
Not going to spoil anything, but yes, there is something going on down there.  This is more of an issue of noise markers just not going away when you wait.  Maybe, there should be a limit to how many noise markers are on screen at one time?

**Comment by Rivet-the-Zombie** [comment]
Perhaps noise shouldn't propagate between Z levels so readily.

**Comment by WizardOfOoo** [comment]
Earplugs.

**Comment by Leland** [comment]
Closing – for noise propagation between Z levels see #14123.
