### ISSUE TITLE
When set too underslung shotgun firemode, gun becomes unwearable

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#16609]
i have a marlin .22 rifle with a shoulder strap, underslung shotgun, and some other generic mods, and wheneiver i have the fire mode set too use the underslung shotgun, i cant wear it.

**Comment by illi-kun** [comment]
Why do you close the issue?

**Comment by codemime** [comment]
Confirmed. Please reopen the issue. A rifle that has a shoulder strap, but uses an underslung shotgun to fire, returns `false` for `item::is_armor()` (normally it should return `true` regardless of the shotgun).

**Comment by 321nick** [comment]
oh sorry, i..... forgot why i did close it. maybe its just that the fix is very easy- just switch too normal fire mode and u can wear it normally, but idk.

**Comment by codemime** [comment]
I'd say that even minor bugs shouldn't be ignored because they may be symptoms of more serious issues (and I suppose it's the case).

**Comment by mugling** [comment]
Likely fixed in #16488 and not since reported. Please reopen if reproducible in any recent version of `master`
