### ISSUE TITLE
"When we drinkin'?" is not a swear word.

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#16604]
I noticed CDDA thinks, "When we drinkin'?" is a swear word, both in this instance and when they not so politely ask you to move.

![image](https://cloud.githubusercontent.com/assets/2432177/15135826/bb6d00ea-1648-11e6-91c0-3c1cbcf3c4df.png)

**Comment by mugling** [comment]
Likely resolved in `master` following recent updates to NPC dialog. Please reopen if reproducible
