### ISSUE TITLE
Suggestion: add offal to haggis recipe

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#16615]
Description of haggis recipe includes offal. It would make sense to add offal to ingredients.

**Comment by Headjack** [comment]
Is there an offal item? Besides the stomach, I mean.

**Comment by BorkBorkGoesTheCode** [comment]
Yes.

**Comment by Headjack** [comment]
Then it makes sense so long as most larger mammals give it.

On another note, should insects really have stomachs? Of course they have stomach-like structures, but I doubt it's the same kind of thing you could make haggis and waterskins from.

**Comment by tsulh** [comment]
> On another note, should insects really have stomachs? Of course they have stomach-like structures, but I doubt it's the same kind of thing you could make haggis and waterskins from.

Agree, but those insects are heavily mutated, so butchering a stomach from them is not that impossible. It would be great to at least reduce the probability of getting a stomach from insects.

**Comment by Hague** [comment]
Could use a quality [tripe](https://en.wikipedia.org/wiki/Tripe) and [chitlins](https://en.wikipedia.org/wiki/Chitterlings) recipe.
