### ISSUE TITLE
mistake in a batter fried fish recipe?

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#16614]
In a batter fried fish recipe, cooking oil/tallow/lard is a tool, not a component.
>  "note": "the cooking oil isn't supposed to be expended since you can recycle it after frying the fish"

It does not seem realistic.

**Comment by Headjack** [comment]
You fry it in the oil, then re-use it later. It's how _I_fry food, at least.

**Comment by tsulh** [comment]
How is it supposed to work with tallow or lard? Also, some oil will be left on the food, and the oil will loose quality after usage. Maybe one oil should have ~10 charges?

**Comment by Headjack** [comment]
Those heat up into liquids. The oil gets gross but you do a lot of stuff in Cata that's gross which you wouldn't consider doing before the world ends.

**Comment by Rivet-the-Zombie** [comment]
Not a bug.

>You fry it in the oil, then re-use it later.

This right here.

**Comment by tsulh** [comment]
TIL people actually reuse tallow irl. It is not healthy though. I guess I will just cook something else from tallow after using it as a tool.
