### ISSUE TITLE
.22 aux pistol mod cant be attatched too shotguns

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#16611]
why? it seems logical enough. i mean, if i can attatch a underslung shotgun too a .22 rifle, then why cant i attatch a .22 pistol too a shotgun?

**Comment by BorkBorkGoesTheCode** [comment]
Are you asking for an underslung .22 rifle mod?

**Comment by 321nick** [comment]
isnt there a .22 underslung pistol mod already in game? was that added by a mod? i couldve sworn its something in the game standard.

**Comment by BorkBorkGoesTheCode** [comment]
There is a crossbow mod, and a aux flamethrower mod, but no .22 pistol mod. If you want a .22 mod, it can be made using the same code as the underslung shotgun, you just need to change the cartridge used and the stats.

**Comment by 321nick** [comment]
oh in that case nvm this issue , im gonna close it now because i thouht the aux .22 pistol mod was a ingame item, not added through mods but i am wrong, sorry.
