### ISSUE TITLE
Plastic cup of yogurt is wonky

### ISSUE THREAD

**Issue by Drygva** [CleverRaven/Cataclysm-DDA#16628]
Trying to use e to pick up a plastic cup of yogurt forces you to choose between dropping your equipped weapon or trying to transfer the liquid. First option drops weapon and equips yogurt, and the second gives you the plastic cup and throws the yogurt on the floor.

**Comment by Hague** [comment]
Yeah, this is the same with all containers that hold liquid but are not resealable. Duplicated with cups of pudding too. Only choice for storage now is to transfer the liquid to a secondary container or eat the cup directly off the ground.

Possibly replace pudding and yogurt cups with sealed variants that when activated turn into their unsealed originals.
