### ISSUE TITLE
Allow the player to start with unworn clothing.

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#16624]
Whenever a character is created, the game autoequips every article of clothing listed in the chosen profession. It would be good if there was some way to tell the game to store some clothing in inventory instead.

**Comment by Shoes01** [comment]
As a band-aid fix, you could create a sort of "equipment box" that's like the Go-Bag. "Use" the box, and then you get your earplugs/whatever else.

**Comment by codemime** [comment]
> "Use" the box, and then you get your earplugs/whatever else.

Sounds reasonable since earplugs are shipped in individual packages IRL.
![144410_ts](https://cloud.githubusercontent.com/assets/11905613/15177274/3d49f2a2-1780-11e6-8c51-d6bef83d311f.jpg)

**Comment by Cyrano7** [comment]
> "Use" the box, and then you get your earplugs/whatever else.
That sounds pretty hack to me. Its best not to do band-aid type fixes as they tend to stay around for a while. Better to make a way to not equip specific wearable items on game start.

**Comment by BorkBorkGoesTheCode** [comment]
Reopening

**Comment by Leland** [comment]
Closing due to lack of discussion. @BorkBorkGoesTheCode do reopen if you're still interested in this

**Comment by BorkBorkGoesTheCode** [comment]
Still interested, just lack the skill to implement it.
