### ISSUE TITLE
Cant use acetylene torch too burn through metal doors.

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#16621]
when having a acetelyne torch, loaded with a magazine with 240 charges, i cant break down the door by activating the acetylene torch, it says i need welding googles, when i do have them in my inventory.

**Comment by RydellV** [comment]
Can confirm its bugged. Running the latest experimental tells me that I need welding goggles. Possibly related to #16559?

**Comment by AppleConnoiseur** [comment]
Can confirm the acetylene torch won't let me activate it no matter if i got the goggles equipped or not.

**Comment by mugling** [comment]
Still present in `master`?

**Comment by Autastic** [comment]
can confirm it works correctly on metal bars (gun shop) and metal door (police station) but does not register correctly when fixing vehicles.

**Comment by mugling** [comment]
> but does not register correctly when fixing vehicles

separate issue
