### ISSUE TITLE
offical Mac OS X build compile corrupt and does not run

### ISSUE THREAD

**Issue by ashtiboy** [CleverRaven/Cataclysm-DDA#16622]
offical Mac OS X build compile corrupt and does not run the info_array in pid 863 failed at address 7fff61b9a030 which in mac build turms means the build falied and got corrupted lets just let rremyroy do the oifcal mac os x builds sence his builds work

**Comment by remyroy** [comment]
#16612 should fix that.

**Comment by illi-kun** [comment]
Fix is landed. Feel free to re-open if it's still an issue.
