### ISSUE TITLE
Sheltered Scenario Costs and Bonuses are Unbalanced

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#16631]
The default Profession is "Sheltered Militia" which says it costs 4, but I suspect since it is the default it has been given for free. Netting anyone who chooses this profession + 5 assignable skill points and the + 4 skill points already assigned **for a total of + 9 skill points.**

The choosing the "Survivor" is even more wonky, giving **a +9 skill points to be assigned how you please!**

On top of that, choosing Sheltered Survivor ( equal cost to sheltered militia) gives the starting character +14 of predetermined skills. Netting whosoever chooses this class **a whopping +19 skill points!**... that's pretty insane.

I suspect this is not the intended bonus for starting the game in winter in a safe secure shelter.

I'm slightly lysdexic with math so I beg your pardon if I my math is way off

**Comment by BorkBorkGoesTheCode** [comment]
Which version of the game are you using?

**Comment by RogueYun** [comment]
13996-g6de88ee or 4847 It's one I downloaded about an hour ago or so.

**Comment by RogueYun** [comment]
It seems the problem of the defualt profession lies in which of the professions is first in the list...
In the scenarios.json:
"professions" : ["sheltered_militia","sheltered_survivor","unemployed"]

Moving "unemployed" to the front of the list...
"professions" : ["unemployed","sheltered_militia","sheltered_survivor"]

...makes the plain "Survivor" the defualt selection and gives the correct/expected amount of initial skill points. I noticed some other scenarios have "unemployed" at the end of their lists. I suspect they might have incorrect values as well. I'll see if I can set up a pull request to fix this though I might struggle with it.. I stink at github.

**Comment by RogueYun** [comment]
It might be worth making another issue about the problem of default scenario professions being given for free and leave this thread as a discussion for the "Sheltered Survivor" getting +14 skill points at a cost of 4 skill points.

**Comment by Rivet-the-Zombie** [comment]
In cases where the default is something other than 'unemployed', the cost has already been figured against the current default profession.

>Yeah, scenario "Ambush" ( + 0 Skill points) has the same ordering problem with "unemployed" making the default profession of "Hardened Survivor" (Cost 6 but given for free) netting the "Survivor" +6 skill points.

'Unemployed' grants extra bonus points because the scenario assumes you'll be starting with enough decent equipment to survive the advanced season and such. Taking 'unemployed' is a huge handicap here.

**Comment by RogueYun** [comment]
The balance to this still seems a bit off to me. Challenge - Really Bad Day "Shower Victim" (+ 1 skill point) now gives + 0 skill points for selecting it because it is the default. And the "Tweaker" (+ 2 skill points) only gives you + 1 skill point. So the most skill points you are able to receive from RBD is + 11. In contrast to starting with all the afflictions really bad day tweaker (burning building in the middle of town, few clothes, no shoes, drunk, infected, withdrawals, hallucinations, etc) sets upon you to the + 19 given from the "Sheltered Survivor" (who starts in winter with a safe shelter, clothed, healthy, and a multi-tool) something does seem a bit fishy with the balance. 

I'd prefer a straight 0 cost character for the default of each scenario so the pros and cons can be weighed at each scenario selection over having to choose the scenario to see what options you have.

**Comment by RogueYun** [comment]
The point have been reallocated since this so that the scenario is more balanced. I think this can be closed.
