### ISSUE TITLE
cant holster pistol or sheath knife exp v 4797

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#16639]
Attempted to holster an M1911 in a holster and a survival knife in an ankle sheath.  Never saw the weapon as an option when it asked what to store.  Maybe the weapons are too large but theres no indication that they wont fit.  Survival knife is described as 'large' so maybe there should be a large sheath.

Not fixed as of 4847

**Comment by sanyaskillpro** [comment]
Was it ankle holster? it has 2 volume 2 weight limit, 1911 may be too heavy or bulky for it if modded.
survival knife is too large for a sheath too, actually there's a profession that starts with it and it also starts with a scabbard.

**Comment by Coolthulhu** [comment]
Not a bug, just too big items.

You can still select the items by using their inventory ids to see why you can't holster/sheath them.

**Comment by illi-kun** [comment]
It's better to create a dedicated issue to state that it's not possible to see limitations for holsters. (I mean, I see only one possibility to get info about max weight and volume for each holster - to find it in json).
