### ISSUE TITLE
Weapon Conversion Kits disappear when dropped.

### ISSUE THREAD

**Issue by Shudokai** [CleverRaven/Cataclysm-DDA#16635]
The weapon calibre weapon mods disappear as soon as you drop them out of your inventory, that probably means they will also disappear on world generation which makes them unobtainable.

Mods affected by this are:
.22 conversion kit
.223 conversion kit
.308 conversion kit
.45 conversion kit
4.5mm conversion kit
5.7mm conversion kit
9mm conversion kit

There might be more items affected by this.
This has been confirmed by  <kd8qdz> and <shudokai> so far.

**Comment by BorkBorkGoesTheCode** [comment]
I have confirmed this. .22 caliber conversion kits disappear when dropped and cannot be found using shift+v.

**Comment by mugling** [comment]
Still an issue?

**Comment by Rivet-the-Zombie** [comment]
The 'rapid blowback' weapon mod also exhibits this behavior.

**Comment by mugling** [comment]
Probably relates to `IRREMOVABLE` flag
