### ISSUE TITLE
Bokken and Scimitar have no associated styles?

### ISSUE THREAD

**Issue by Drygva** [CleverRaven/Cataclysm-DDA#16649]
Bokken could easily fit under Niten-itchi Ryu, and Scimitar into Penchak Silat. It just seems odd. Scimitar is a decent weapon but outclassed by ones with worse stats on the premise that not only does it only have Block, but it doesn't coordinate with a style.

**Comment by Boredone** [comment]
Checked, Bokken actually is under Niten (I think), but Scimitar doesn't have any styles with it yeah.

**Comment by BorkBorkGoesTheCode** [comment]
Has this been fixed?
