### ISSUE TITLE
Proposed Keffiyeh changes

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#16642]
A basic change to start getting used to submitting contributions.  I put them here, but I think I did something wrong since it's not showing in the master pull requests, if someone can tell me what I did wrong I'd appreciate it.

https://github.com/Xpyder/Cataclysm-DDA/pull/1

Summary: I made a fork to try and propose a change to the Keffiyeh recipe to make it more realistic

**Comment by Cyrano7** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/CONTRIBUTING.md Have you checked out this page? It will give you a basic run down.

**Comment by Xpyder** [comment]
I glanced at it but i didn't see the instructions from Github Desktop and doing stuff locally.  I'll  look into it and post if I need more help.

**Comment by Xpyder** [comment]
ok, I posted it here.  Normally I'd let it get scooped up whenever but since it's my first change attempt could someone look over it and make sure i did everything correctly?

Updated keffiyeh recipe #16644: https://github.com/CleverRaven/Cataclysm-DDA/pull/16644

**Comment by Cyrano7** [comment]
You seem to have it down now so you can close this.
