### ISSUE TITLE
Build 4851: Wielded item not show in 'T'ake off menu

### ISSUE THREAD

**Issue by AppleConnoiseur** [CleverRaven/Cataclysm-DDA#16645]
Exactly what it says on the tin.

I use this functionality a lot when playing so i noticed that i could not simply unwield a item through that menu anymore. Strangely enough the key assigned to wielded item still works in the menu.

Bring back plox :D.

**Comment by codemime** [comment]
I'm not so sure that wielded items should be shown in the 'Take off' menu. There's a dedicated menu for wielding/unwielding stuff ('w' by default). Do they really should? Will look into invlets, though. Looks like a bug.

**Comment by AppleConnoiseur** [comment]
> There's a dedicated menu for wielding/unwielding stuff ('w' by default).
You can't unwield and use just your fists there. Doing it with the 'T' menu in the 4820 build i could easily put my currently wielded item into a appropiate sheathe, holster or bandolier by doing that.

Also make a lot of sense to use 'T' to 'take off' your weapon in your hands.

**Comment by codemime** [comment]
> You can't unwield and use just your fists there. Doing it with the 'T' menu in the 4820 build i could easily put my currently wielded item into a appropiate sheathe, holster or bandolier by doing that.

Why not? You can do both in the current experimental.

> Also make a lot of sense to use 'T' to 'take off' your weapon in your hands.

Arguable.

**Comment by AppleConnoiseur** [comment]
> Arguable.

Indeed. Pretty **_subjective_** this. For me it is a lot quicker and made more sense to just use 'T' to unequip currently wielded item with just 2-3 key presses. (Add one if you include Shift :P)

I wonder what other people think of this since this is pretty subjective on whether this should be kept to the _in the book_ description of 'T'aking off **worn** item or let _leave a little leeway_ in letting the same menu serve the purpose of unequipping **wielded** item(s).

I can adapt to the new changes, so no hard feefees about it :).

**Comment by Charlesilv4** [comment]
I agree with the bear on cocaine

**Comment by Shudokai** [comment]
There is probably a reasonable difference for Take off and wield/unwield functionality, especially now that the inventory is a lot cleaner on several actions.( #16152 )

if you press "w" it will open the wield and unwield screen giving you all wieldable items in your inventory, if you press "T" it will only show the items you have currently equipped to your body.

I also think it is a lot clearer given the wording, you usually don't take off the item you've been swinging around, you "d"rop or un"w"ield it, other than clothing which you'd not unwield but "T"ake off.

**Comment by illi-kun** [comment]
Controversial suggestion.
