### ISSUE TITLE
superalloy sheet cannot be obtained in game

### ISSUE THREAD

**Issue by remyroy** [CleverRaven/Cataclysm-DDA#16641]
It is used in a few recipes but you cannot obtain it. It does not drop from any monster. It is not part of any disassemble. It is not part of any loot.

id = `alloy_sheet`

**Comment by BevapDin** [comment]
It can be obtained by disassembling various CBMs http://cdda-trunk.estilofusion.com/alloy_sheet - their recipes are all reversible.
