### ISSUE TITLE
Quick pickup and drop when also picking up or dropping containers

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#16653]
I would like to suggest that when you pick up and drop bags like suitcases and duffel bags and the like, and you also drop or pickup other items, that it just cost the time it would take to put on or drop the bag, and you pick up or drop the items for free.

This would work nicely with #16652 but as Coolthulhu pointed out in #16650, it would not be necessary to make this mechanics suggestion work.

**Comment by Coolthulhu** [comment]
I think there was some mechanic like that for dropping, but I've never seen it in action.

Also, it could probably be solved simply by capping max pickup time by some function of maximum storage. The assumption would be that the character drops the bag to the ground, fills it, then puts it back on automatically.
This would make it more elegant than requiring the player to drop a bag on things to pick them up faster.
