### ISSUE TITLE
Turret is bleeding

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#16655]
From 0.C-4623

Rammed a turret slowly and repeatedly with a spiked vehicle. It was pushed back for a while, then I realized it seemed to be leaving a blood trail.

![blood](https://cloud.githubusercontent.com/assets/6004660/15238501/289eacd4-189e-11e6-99d5-b63ae9cdab98.png)

Probably shouldn't.

**Comment by karols146** [comment]
It happened only with spiked cars, normal car just push it.

**Comment by archer77** [comment]
Does this happen for all things that shouldn't bleed? In other words, can all monsters bleed? Maybe we can check if a monster is a robot before we allow applying bleed effects. also is the bleed effect actually doing anything to them? or is it just used for knowing whether or not to color the terrain with blood?

**Comment by karols146** [comment]
I think that turret is the first. That checking is nice idea, we can use material type for example, only bots and turret use that type.

**Comment by archer77** [comment]
I see that the turret uses the "steel" type but do all things that don't bleed. ie. bots and mechanical monsters, use that type? I'm not opposed to the idea of using the material type but I want to make sure that that will be a full fix.

**Comment by karols146** [comment]
All monster which are in defense_bot.json, that will be full fix for them. 
And if somebody find something later, we start thinking about that. 
Btw, if some monster is made from steel there is now way that he can bleed in any way.

**Comment by illi-kun** [comment]
Just a guess (without checking of actual code): cyborgs can be made of mixup flesh and steel, so I'd prefer to check (!flesh) condition rather than (steel). Keep in mind glass/stone/wood/etc which also don't bleed.

**Comment by archer77** [comment]
True. I'm still having trouble finding where in the source code the game decides to color the terrain with blood. I'm still learning exactly what's what in the source code, but I am getting used to it. I'm fairly certain it creates a field when the monster gets damaged, and that's where we should put the check, but I haven't found it.

**Comment by codemime** [comment]
[Here's](https://github.com/CleverRaven/Cataclysm-DDA/blob/0e2bad39fdc0c6f14c08e4bb39035a3835cf0cab/src/ranged.cpp#L1602) the code and the check you're looking for.

**Comment by karols146** [comment]
Cyborgs got `"material":"steel",`, there is a question they should bleed or not.

**Comment by archer77** [comment]
things can only have one material so based off of that classification then they shouldn't but I think that's a more complicated problem like what parts of then are mechanical and what parts aren't (body parts would need a material)(much more complex). Does bleed affect a monster's health or impact them physically at all?

**Comment by illi-kun** [comment]
Vehicle.cpp, line 4785 (search for fd_blood) is what you want to find.

**Comment by codemime** [comment]
@karols146 You get it right, but an npc-turret nevertheless can :). I've just pointed the check, no more than that.

**Comment by karols146** [comment]
#16728 Waiting for comments guys, It's working, but I am not sure that I did it right.

**Comment by codemime** [comment]
Will PR a solution pretty soon.
@karols146 sorry once again.
