### ISSUE TITLE
Toolbox Recipe does not accept the hammer

### ISSUE THREAD

**Issue by Shudokai** [CleverRaven/Cataclysm-DDA#16654]
The fixed Toolbox recipe requires a hammer but it will not accept the hammer, this makes the toolbox uncraftable.

After playing for a bit longer it seems like there is two different types of hammers spawning in the game, one of them has "seeing this is a bug" as its description, so I guess there is items spawning as loot that are not supposed to be there.

**Comment by Coolthulhu** [comment]
Can't reproduce

**Comment by Shudokai** [comment]
The first two hammers I found both had the bug description, haven't found any more of those ever since, guess it was a short term issue.

**Comment by Coolthulhu** [comment]
The weird hammers are a bug though. Could you open an issue for that and provide a save? If you're playing with some weird mods, it may be those.
