### ISSUE TITLE
Alternator Type Frequency / Possible Mismatches

### ISSUE THREAD

**Issue by Drygva** [CleverRaven/Cataclysm-DDA#16664]
Just found it odd that car alternators are found in flatbed trucks, pickup trucks, and even an ambulance with a V8 Engine. Seems like some trucks and other larger vehicles should have truck alternators. These are just the ones I have checked so far, but there may be other examples.

**Comment by mugling** [comment]
Fair enough. We should also start enforcing one alternator per engine (or at least require high mechanics skill to install multiple)

**Comment by Coolthulhu** [comment]
> We should also start enforcing one alternator per engine

Why should we?

**Comment by Rivet-the-Zombie** [comment]
I agree with Coolthulhu; the current system seems to work quite well.

**Comment by mugling** [comment]
Given most engine mounts only allow for one adding extras should require a degree of skill?

**Comment by mugling** [comment]
This came up also some time ago but I can't find the issue

**Comment by Xpyder** [comment]
I'd like to PR this, but should Vans also have truck alternators?

**Comment by kevingranade** [comment]
Adding an additional alternator would just require some welding to install
a new bracket, so ideally alternators after the first would have that
requirement, but in practice I'm not sure it's worth doing, at least not
until the vehicle repair system is a good bit more polished.

**Comment by mugling** [comment]
You'd have to find appropriate sites to mount them with either an appropriately long belt (or multiple belts). That implies a degree of mechanical aptitude? I'm not sure welding to an engine block would be particularly easy - aren't most cast?

That said we probably do indeed have more urgent requirements including overhauling vehicle repair/installation requirements.
