### ISSUE TITLE
Unable to mend faulty engine

### ISSUE THREAD

**Issue by Drygva** [CleverRaven/Cataclysm-DDA#16666]
I am unable to 'mend' a faulty immobilizer even though both the skill requirements of 2 mechanics and 5 electronics, and the tool requirements of 1 fine screw driving are met.

Type is 2.5L Inline-4 Engine.
Build is 4844.

**Comment by codemime** [comment]
Duplicates #16438.

**Comment by mugling** [comment]
Not a duplicate. Incidentally discovered the cause whilst working on #16941
