### ISSUE TITLE
Sheath swords illogic

### ISSUE THREAD

**Issue by BigBadRobin** [CleverRaven/Cataclysm-DDA#16662]
Bokken has no SHEATH_SWORD flag (due to it's blade width, I guess), but 2-by-sword and crude sword have one, while they have pretty more non-sword shape of blade than elegant bokken. 
So it may be corrected by removing flag from both 2-by-swords's, or adding it to bokken, or maybe first option with adding special wide plastic sheath for bokken (exist IRL) with new SHEATH_BOKKEN flag.

**Comment by Coolthulhu** [comment]
2-by and crude shouldn't fit.

If both the katana and a broadsword can fit in the same sheath, the bokken could fit too.
Otherwise we'd need a new sheath for every exotic sword and that would quickly become unnecessary detail no one really wants, and also would be misleading unless the "regular" sheath was removed/renamed.

**Comment by Hague** [comment]
"A leather scabbard, big enough for **almost any sword.** Designed to be strapped to the back and very difficult to draw from without considerable practice. Activate to sheath/draw a sword."

Description of the back scabbard. Seems like the Bokken should fit.

**Comment by BigBadRobin** [comment]
This is regular scabbards
![60](https://cloud.githubusercontent.com/assets/18753194/15250508/cb302222-192d-11e6-9844-2c81360fea4a.jpg)
![9](https://cloud.githubusercontent.com/assets/18753194/15250509/cb3386f6-192d-11e6-90d9-3e4f750dd2eb.JPG)
And this is bokken scabbard
![ebg-com-iai-boksaya-set-2](https://cloud.githubusercontent.com/assets/18753194/15250518/dc158a0a-192d-11e6-8f73-03814a87d421.jpg)
![w914-7](https://cloud.githubusercontent.com/assets/18753194/15250519/dc19b27e-192d-11e6-9641-ff5ec772179e.jpg)
So I think bokken need personal scabbard

**Comment by Hague** [comment]
Sounds unnecessary. Scimitar easily needs its own scabbard as well as others for every other curved and straight sword of various lengths. The same logic applies to knife sheathes. Survival knife is massive compared to hunting knife, likewise a butcher's knife. No one wants to sort through 30 different scabbards and sheathes or find a sheath and realize it doesn't fit the only blade they carry. If granularity is desired, it would make more sense to make a fitting system for generic scabbards/sheathes for each weapon and have that quality determine the efficiency of the draw speed. Still seems like a lot of work for not much gain.

Bokken has no edge to preserve so it doesn't really need a scabbard anyway just a few loops to slide it through across your back. As a training device the purpose of a sword-case for a bokken is to teach Iai-do, the flowing scabbard-to-strike-to-scabbard technique known to Japanese swordsmen.

**Comment by BigBadRobin** [comment]
> No one wants to sort through 30 different scabbards and sheathes or find a sheath and realize it doesn't fit the only blade they carry.

Can tell same about ammo and magazines. How about make specialized uncraftable comfortable sheaths for all(or almost all) types of swords and make them spawn ONLY with swords in it (along with swords without scabbard, so it prevent from finding useless scabbards: all scabbard will have sword, but not vice versa); and rename all handmade sheats to "one-size-fits-all-or-something" version (unwanted thing IRL, but handy in zombie-apocalypse world). It can be wide flat rectangular scabbard that can securely hold all types of flat blades(straight and curved) not due to scabbard blade-like shape, but due to dense fur on inner surface of it. Btw will be nice add something oily(maybe as tool) and some piece of fur to scabbard recipe(wikipedia approve). It's maybe a lot of work, but one more step from simplism to realism, though it certainly not urgent.

**Comment by kevingranade** [comment]
If someone wants to make a feature for handling sheath fitting, that's
cool, and we can debate whether it should be on by default or enabled with
a mod, but it sounds like no one is interested in doing that work.

As for the listed three, IMO wood swords shouldn't fit, metal ones should,
it's a pretty clear distinction about blade width even if it isn't
perfectly accurate.

**Comment by Shudokai** [comment]
To add some apocalyptic vision to that: Most modern Scabbards are made out of plastics or cooked or hardened leather with metal reinforcements, the scabbard you can make yourself in the game is usually made from soft leather, a tiny bit of glue, a few nails and some wood so I guess its soft enough to adjust its shape to most blades in the game, even the bokken, so if anything, the bokken should get the sheath sword flag.

**Comment by Hague** [comment]
Why not just make the wooden swords wearable on tool belts? They are essentially just clubs with hilts for the most part, they could easily be held on the hammer loop of your standard tool-belt or cinched or tucked into the belt. Nord and scrap metal sword are probably ineligible (too big and too sharp) but the cudgel, 2-by-sword, and bokken would easily slip into a tightened belt, or sash without much trouble at all. Scabbard is just so you don't cut yourself and the edge doesn't get exposed to the weather and whatever whetting quality you get from drawing it. No edge, no scabbard necessary

**Comment by harald921** [comment]
I vote Yes for simply allowing the bokken to be sheathed. Easier to understand, does make sense, not unbalanced, not very unrealistic. Better for everyone.

**Comment by Xpyder** [comment]
I vote for adding SHEATH_SWORD to bokken for consistency, and moving the discussion of custom sheaths to a separate discussion until that's decided.

**Comment by Xpyder** [comment]
PR posted here: https://github.com/CleverRaven/Cataclysm-DDA/pull/16722
Didn't tag as fixes this, in case we want to continue the larger change discussion here instead of moving to a new issue.  Mods feel free to link them if desired.

**Comment by mugling** [comment]
Linked PR is merged and nobody has expressed interest in further extension
