### ISSUE TITLE
recepies of 'tin can of X' are called just 'X'

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#16675]
Recepies of 'tin can of X' are called just 'X', while recepies of 'sealed jar of X' are called 'sealed jar of X'.

I suppose, it should be 'tin can of X'.

**Comment by Xpyder** [comment]
I looked at the code for this and it's not creating separate items, but adding a suffix to the resulting object.  This may be an issue with the way the items are generated, not sure how the engine is handling the naming of the resulting objects.

If no one else can come up with a better way of doing this I could probably make this work like Jars, i.e. having a separate "Can of xxx" tool that generates a can with the given item in it when you use it.  It's messy so if there's a better way of doing it I'm happy to listen.

**Comment by Leland** [comment]
Looks like discussion has stalled on this suggestion. Closing. If there's still interest, let me know and I can reopen.
