### ISSUE TITLE
Calcium and iron balance in fish, meat and soups

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#16677]
Fish and meat now have the same amount of calcium and iron, which seems highly unrealistic.
It's hard to set 'realistic' values, but I would set calcium in fish and dishes made of fish to 2x of what is set for meat and dishes made of meat.

Regarding iron, I would half iron amount in fish and dishes made of fish (http://www.mckinley.illinois.edu/handouts/dietary_sources_iron.html).

**Comment by mugling** [comment]
> It's hard to set 'realistic' values

Agreed, but the above is a reasonable start and can be part of a plan for incremental improvement. If you have any other suggestions please open further issues

**Comment by keyspace** [comment]
The most straightforward way I see is to define a new material, and `copy-from` `flesh`.

That could go fractal, requiring to review items where fish is optional (e.g. `soup_woods` as highlighted in #16676).

**Comment by keyspace** [comment]
Tangent: perhaps crafted item `components` could be used? I'll open another issue if I come up with a viable prototype.

**Comment by Leland** [comment]
Combining #16676 with this. @tsulh's notes from that issue:

>Woods soup has 8% of calcium, while vegetable, meat, fish, muchroom and sap soups have only half of that amount.
>
> Is there any validation for woods soup to have more calcium than all others? I would expect fish soup to give more calcium instead (or both woods and fish soups, since woods soup can include both fish and beans).

**Comment by Leland** [comment]
Closing due to lack of recent discussion. Feel free to ping me here to reopen if there's interest in continued discussion/development.
