### ISSUE TITLE
Calcium balance in soups

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#16676]
Woods soup has 8% of calcium, while vegetable, meat, fish, muchroom and sap soups have only half of that amount.

Is there any validation for woods soup to have more calcium than all others? I would expect fish soup to give more calcium instead (or both woods and fish soups, since woods soup can include both fish and beans).

( the issue is complementary to #16677 )

**Comment by Leland** [comment]
Closing in favor of #16677
