### ISSUE TITLE
Trapping skill description wrong about trap detection

### ISSUE THREAD

**Issue by Skidborg** [CleverRaven/Cataclysm-DDA#16673]
The description for the Trapping skill in character creation says:
> Your skill in setting and disarming traps safely and effectively.  **This skill does not affect the detection of hidden traps**, or the evasion of traps that are triggered.

However, the actual code for trap detection in trap.cpp includes:
```
// ...bonus from trap skill...
///\EFFECT_TRAPS increases chance of detecting a trap
( p.get_skill_level( skill_traps ) * 2 ) +
```

And testing in-game with a 4 perception character proves that 10 trapping skill will instantly reveal nearby buried landmines, while a character without skill is free to wander into them.

I'm fairly sure the in-game behavior is correct, and makes sense.  The description text is just a blatant lie.

**Comment by BorkBorkGoesTheCode** [comment]
#16871

**Comment by codemime** [comment]
@BorkBorkGoesTheCode Issues will be closed automatically if you [write something like "fixes #xxxxx"](https://help.github.com/articles/closing-issues-via-commit-messages/) in the description.
