### ISSUE TITLE
Quick menu: Draw weapons\whatever

### ISSUE THREAD

**Issue by AppleConnoiseur** [CleverRaven/Cataclysm-DDA#16683]
Exactly what it says on the tin :P.

When you press '%' by default it could be convenient to let us draw ALL our holstered and sheathed weapons from there. _Right now_ it will only show the first item i happened to equip i guess. Regardless whether it got anything in it or not.

Maybe let us attempt to holster our currently held weapon into a suitable holster\pouch as well from the quick menu?

**Comment by Leland** [comment]
Looks like discussion has stalled on this suggestion. Closing. If there's still interest, let me know and I can reopen.
