### ISSUE TITLE
Smoke floats through walls

### ISSUE THREAD

**Issue by Drygva** [CleverRaven/Cataclysm-DDA#16695]
The exhaust of an engine will float through a wall if the square where the exhaust would normally be is occupied by a wall. The thin smoke defies physics and creates a cloud in the room on the other side via the following diagram:

+++x+++
-----s-----
++sss++

x = engine or other exhaust
+ = empty space
s = smoke
- = wall

**Comment by codemime** [comment]
The issue most likely duplicates #14894.
