### ISSUE TITLE
blob feed fermenters return stack of 0 blob feed

### ISSUE THREAD

**Issue by Anticheese** [CleverRaven/Cataclysm-DDA#16705]
As per the title, opening a blob feed fermenter in the current unstable build using the vehicle mod will produce a stack of 0 blob feed.
![blobfeed](https://cloud.githubusercontent.com/assets/2417316/15286768/f46beff4-1bb2-11e6-99c8-21a470ee7fb9.png)
Adjusting the capacity of the blob core container and the size/stackability of the blob feed did not fix the issue.

**Comment by Shudokai** [comment]
It seems like the version of Vehicle Additions Mod that comes with the game is badly outdated and needs to be replaced with the most recent version provided in the cdda forums.


http://smf.cataclysmdda.com/index.php?topic=8060.585

**Comment by mugling** [comment]
> It seems like the version of Vehicle Additions Mod that comes with the game is badly outdated and needs to be replaced with the most recent version provided in the cdda forums.

This was done
