### ISSUE TITLE
Add mutation for Vitamin C biosynthesis

### ISSUE THREAD

**Issue by Skidborg** [CleverRaven/Cataclysm-DDA#16702]
In real life, the vast majority of plants and animals are fully capable of producing their own vitamin C.  It's an ability that has only atrophied in humans and species that have ready access to fruit.

However, several of the mutation paths add the carnivore trait, which cuts off that natural source.  It only makes sense that a mutagen that gives a character the ears, tail, and diet of a Feline should also give them the ability to survive having that diet in the long term.

**Comment by Shudokai** [comment]
Sounds like something that should be part of Alpha aswell. Seems like the disability to synthesize certrain nutrients is a major flaw of humans, so that should be something Alpha aims to take care of.

**Comment by Hague** [comment]
Alpha is the next step of the human evolutionary chain, accustomed to genetic experimentation and artificial technological interaction. Alpha should get the ability to better make use of artificial vitamin sources and gain an immunity to hypervitaminosis.

**Comment by Coolthulhu** [comment]
I like Hague's option more. Alpha being the "more human" option should be dependent on all sorts of drugs rather than producing everything internally, but should also be resistant to their toxicity and quickly flush out all excess.

**Comment by Leland** [comment]
Looks like discussion's stalled on this suggestion, closing. Feel free to let me know if you want it reopened; or just create a new issue.
