### ISSUE TITLE
[Bug] Graphical Vehicle Interface showing the wrong durability of armor

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#16712]
Version: 0.C-14084-gd5f8f59 (tiles)

The military composite rams of my vehicle shows up as damaged (red, light red, etc.) on the graphical interface on the left even though fully repaired in the text interface. (There are no damaged parts on this vehicle + text is dark green)

**Comment by illi-kun** [comment]
Screenshots are extremely helpful for such kind of issues.

**Comment by mugling** [comment]
Many recent changes to relevant code and remains unconfirmed. Please reopen with screenshot if reproducible in `master`
