### ISSUE TITLE
[Bug] Time Dilation bionic uses up all energy 

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#16714]
Version: 0.C-14084-gd5f8f59 (tiles)

Time Dilation bionic empties your energy despite saying it takes only 50 PU/act. (~2600 -> 0 in my case).

**Comment by codemime** [comment]
It's easy to fix. [This line](https://github.com/CleverRaven/Cataclysm-DDA/blame/master/src/bionics.cpp#L196) has to be deleted.

**Comment by Coolthulhu** [comment]
The bionic's effect scale with used power.

**Comment by i2amroy** [comment]
Yeah, some mention of the fact that it consumes all your power should definitely be present somewhere.

**Comment by codemime** [comment]
It would be nice to introduce a generic solution, so that we could produce yet another "greedy" bionic or undercut this one simply via adjusting JSON.

**Comment by harald921** [comment]
Is it really a nice design choice making it consume everything though? I mean, wouldn't it make more sense to either allow the player to choose the "power" of the use, or simply consume like.. half of it or something. Making everything shut down because of one bionic use seems a little bit insane.

Perhaps that is another discussion for a thread though.

**Comment by Griffinhart** [comment]
The original design was that you'd dump all your bio-energy and get time dilation based on the energy dumped. Personally I don't actually like that design, since it's useless at both low energy (you don't get enough time dilation) and at high energy (you spend forever in time dilation).

**Comment by i2amroy** [comment]
>and at high energy (you spend forever in time dilation).

LIES! You can never have too much time dilation!

:P

**Comment by Griffinhart** [comment]
True. The real disadvantage of high energy and using TD is then you have to restore all that energy... (protip: furnace + trees. Get your clearcutting on!)

**Comment by harald921** [comment]
Why not make it consume a specified amount? For example 1000PU? Expensive to use, lots of side effects, etc.

**Comment by kevingranade** [comment]
Consuming all your power is intended as a drawback to balance the OP-ness
of free turns on demand. In practice some other bionics are also broken (by
making it possible to recover bio-power in combat) so it doesn't actually
limit you as much as intended.

Basically, the intent us that once you use it, the rest of your CBMs are
disabled until you have some time to recover, and using all your power in
one burst is a good way to make that happen.

**Comment by Isaacssv552** [comment]
What about capping the effect at 1000 power, still using all power, and returning any excess power 10-30 minutes after use? Using it when you have 2000+ power is overkill against all but the largest of hordes, and leads to the bizarre situation of standing still waiting for it to end while taking "friction" damage. 

Even better would be an option to select how many turns you want and lose all excess power for something like 1 minute per turn, so a 10 turn boost might only cost 200 power with excess being lost for 10 minutes, but a 60 turn boost would cost 1200 power and lose excess for an hour.

**Comment by Coolthulhu** [comment]
> What about capping the effect at 1000 power, still using all power, and returning any excess power 10-30 minutes after use?

Capping would work, but returning that excess power is not needed.

All those giant power stores will be nerfed when the bionic slot nerf becomes a thing.

**Comment by Isaacssv552** [comment]
If the excess power isn't returned the problem is only made worse, now you're directly losing power for no gain. Simply capping the amount drained might work with the slot system, since players going above 1000 power are sacrificing something else to do so, but gives undesirable behavior until the slot system is finished.
