### ISSUE TITLE
NPC spammed phrases during training me melee

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#16716]
I completed the second quest of NPC 'Jim Weaver', and asked him to teach me some melee as a reward. During the training, he asked me to let him pass all the time, though I was in a doorway adjacent to a free doorway (see the screenshot below).
I learned archery from him after completing the first quest, and it went well.

![cata_npc_bug_2016-05-16](https://user-images.githubusercontent.com/714017/36578089-1aba0fc8-1829-11e8-9b6e-f0d39b16aed8.png)

...after that, he broke the window (I was not blocking him path to the window during the training) and ran back home, regardless the fact that I offered him a ride home...

**Comment by Leland** [comment]
Closing due to lack of response and lack of method to reproduce. @tsulh if you have a set of steps to reproduce this issue – or especially a savefile exhibiting this behavior – ping me here and I'll reopen 🙂
