### ISSUE TITLE
Balance of near-far sighted  trait and some related mechanics problems

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#16729]
Currently near and far sighted traits are basically free points.It shoud in therory force you to look out for your glasses but in all my melee characters with glasses i never once had broken glasses even without having additional eye protection and i played a lot.I dont think i have that much of luck.I suppose this is connected with simplification of hp pools into head,arms and legs where feet,eyes,mouth,feet doesnt have apropriate hp pools.
I am ok with this simplification but it seems that problem is that aproipriate clothing delegated to those parts never gets damaged which pretty much screws point of many choices.Having sturdy trait  fro things like leather armor boots is basically meaningless as things never get damaged,even dress shoes in acid preserve their integrity as they do against hordes of dogs.i am also not even sure how much are these parts of body targeted and does protection of them have meaningfull game impact.

As for opening problem-those traits have no meaningfull effect except in case you in purpose lose glasses.You in fact gets bonus of making fires for free in sunny days and both traits can be removed with telescopic eyes cbm.

what i would propose connected to this problem
1.,lower points for this traits to 1 instead of 2
2.make some penalty for ranged/melee combat regardless of having glasses on you or raise encubrance for glasses considerably
3.make changes to damage mechanics so there is danger to glasses.and other unrepresented parts of body.

i would prefer 3 gameplay wise but i am not sure how much changing of damage mechanics would that irequire

**Comment by Coolthulhu** [comment]
1. Makes sense. Far sighted certainly isn't worth 2 points and wouldn't be worth it even if glasses had 100 encumbrance
2. There is a small penalty for far sighted in melee combat, but nothing at all for ranged. There should probably be a big penalty for shooting things you can't see well.
2a. Encumbrance for glasses is currently 0. Could be safely raised to 10.
3. This would be more annoying than dangerous. Would just mean you'd have to collect glasses and keep repairing them.

**Comment by baraba3** [comment]
As for 4,yes having some glasses for backup or using additional eye protection for absorbing hits was my vision.glases are not hard to find anyway.also i didnt thought of player reciving hits in eyes constantly but having some theroretical risk to recive and lose/damage glasses.currently its seems that that risk doesnt exist at all   and realisticly i think its not real.
this change is not for only glasses but is  related to feet,mouth and hands clothing which seem to never get damaged. 

But maybe its annoying.

**Comment by Coolthulhu** [comment]
Eyes do get hit, just not a lot. They get hit more often by accurate critters, especially if the player can't dodge well.
Hands, feet and mouth only get targeted by special attacks such as bites and acid barf.

**Comment by Hague** [comment]
As a person with glasses whom has gotten in a fight more than a few times whilst wearing his glasses, I can say that after a good hit or during most grapples, those suckers go flying off. Usually don't get broken by getting hit. Most pairs of glasses I've every had destroyed were stepped on or rolled over during the fight.

Also, nearsightedness is not modeled properly at all. Removing my glasses doesn't cover my vision with an impenetrable wall of darkness. Everything just gets increasingly blurry a few feet from my face.

**Comment by Coolthulhu** [comment]
It's rather hard to model blurring, though. It would require special cases for visibility functions, for example hiding items on the tile, hiding small critters while leaving big ones etc.

**Comment by cainiaowu** [comment]
Could we replace the total darkness to light intensity greyscale map as blurring? You cant tell what is there, but you can see the shape of a building.

**Comment by Hague** [comment]
Nearsighted without glasses might remove your ability to use the shft+v viewing command. And attempting examine objects at a distance might replace the list of items you see with a generic "You see objects piled here. You can't make them out at this distance" You'd still be able to visually see the first object in the pile (possibly greyed out) via the tileset but you wouldn't be able to discern its condition, description, or any of the underlying objects until you got close to them. No details at range, basically.

**Comment by Coolthulhu** [comment]
> You'd still be able to visually see the first object in the pile (possibly greyed out) via the tileset

Dependency on tileset is a no-go.

**Comment by Hague** [comment]
Well, I mean you'd still see the first thing in the tile. It doesn't make any objects disappear, you'd just have to guess at what it was. This applies with terminal versions too, you'd still see [ or ] on a piece of clothing, but you'd have to get close to know if it was a jacket or whatever. Tilesets would get a distinct advantage (I'd argue that it's an advantage tilesets already have without any changes) I suppose a better way would be to replace blurry object tiles with generic characters like ! or ] (based on category) instead of their default texture / character until the player gets in range to see properly.

That said, even with myopia you can discern the general makeup of something: I can see a jacket hanging on a coat rack from across the room. I couldn't tell you what logos it had, how dirty/clean it is, its state of repair, nor read any reasonably-sized text embroidered on it without getting closer.

**Comment by kevingranade** [comment]
You're asking for an overhaul of how vision works everywhere. I want to do
this eventually but it's a very big set of changes and probably isn't going
to happen soon.

**Comment by Hague** [comment]
I agree. A lot of work to go into that. Just having your glasses get knocked off when knocked down or knocked back often and making them easy to smash if the ground tile they're in is targeted by a zombie or player smash (The same way glass bottles get smashed in vending machines.) Also a potential roll to damage the glasses if something steps into a tile where they are on the ground.

**Comment by kevingranade** [comment]
Really just the knocking off is enough, that at least makes it something
that occasionally happens.

**Comment by Leland** [comment]
Looks like discussion has stalled on this suggestion. Closing. If there's still interest, let me know and I can reopen.
