### ISSUE TITLE
Custom butchery drop for cyborgs and robots

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#16727]
As of 4876, butchering broken cyborgs and some varieties of zombie child evolutions (wailing waif, if memory serves) will print the title message. Butchering products seem to appear as normal, but I'm not certain about bionics for cyborg corpses.

EDIT: Confirmed that bionics will also appear upon butchering broken cyborgs.

**Comment by karols146** [comment]
Plus There is a message "You harvest some flesh", and there isn't any.

**Comment by codemime** [comment]
Since cyborgs aren't robots, they should be made partly of flesh.

**Comment by Shudokai** [comment]
Cyborgs are most commonly known to be enhanced organisms, so they are either clones or proper humans with cybernetic enhancements, so yes, there should be flesh.

**Comment by player0981234** [comment]
also butchering skeletons will display the message "You harvest some flesh" but there are only bones

**Comment by archer77** [comment]
so butchering should still give cybernetics for cyborgs and it should give bones? for skeletons?(are bones actual items or not?)

**Comment by Cyrano7** [comment]
Cyborgs use to drop bones and flesh actually. https://github.com/CleverRaven/Cataclysm-DDA/pull/15171
I'm not sure why that has changed though.

**Comment by karols146** [comment]
So there is something with flags, because cyborg got human flag if I remember right.

**Comment by Cyrano7** [comment]
Like I said Its had the human and bones flag since https://github.com/CleverRaven/Cataclysm-DDA/pull/15171/files and still has it currently.

**Comment by archer77** [comment]
would it be a better fix to have monsters be allowed to be made of multiple materials then each material has a chance to drop certain items? (this would be a large change)

**Comment by AppleConnoiseur** [comment]
From reading the broken cyborg description i get the impression that they are practically failed Robocops :P. Literally just a human head grafted onto a robotic body.

**Comment by archer77** [comment]
does anyone know the purpose of line 343 of activity_handler.cpp ?
    `skins = std::max( skins,0 );`

**Comment by BevapDin** [comment]
> would it be a better fix to have monsters be allowed to be made of multiple materials then each material has a chance to drop certain items? (this would be a large change)

Monsters can already have any amount of material. Some functions may only consider the first material or check only for specific materials, that would be bugs.

**Comment by Oskar636** [comment]
Can't reproduce any of the bugged messages in build 5862. I think some of the butcher code got reworked.

**Comment by railmonkey** [comment]
Still no flesh, though. Just bones.

**Comment by Oskar636** [comment]
The cyborg?

**Comment by railmonkey** [comment]
The very same.

**Comment by Oskar636** [comment]
It's description is: EKHEM 
" A robot body with the head of a human.  All kinds of electronic wires and devices are implanted in its head.  Patches of skin look diseased or rotting.  This cyborg moves erratically and has a confused and deranged look in its eyes. "

**Comment by railmonkey** [comment]
Eh. That's fine, then. Might want to have it drop superalloy, then. That's what the armor CBMs are made from, and they explicitly replace the skin. If not that, then steel at the very least.

**Comment by illi-kun** [comment]
Merging of PR #19209 will move railmonkey's suggestion about custom drop for cyborgs to "easy fix" category.
