### ISSUE TITLE
Crash Disassembling L523-CAR carbine

### ISSUE THREAD

**Issue by ifreund** [CleverRaven/Cataclysm-DDA#16721]
Crash occurs only if magazine is in gun.  Doesn't seem to matter what tool is used to disassemble.

Credit to Adrian219 for finding bug.

Edit: forgot to add that the terminal outputted "Segmentation fault: 11"

**Comment by mugling** [comment]
Likely the same bug whereby the code presumes `contents` contains only gunmods

**Comment by illi-kun** [comment]
Works fine / no crash happens.

Feel free to reopen the issue if it still happens for you.

**Comment by BorkBorkGoesTheCode** [comment]
@illi-kun GitHub doesn't allow volunteers to reopen issues closed by contributors.

**Comment by illi-kun** [comment]
Read my comment as "let me know if it's still an issue and will reopen it for you".
