### ISSUE TITLE
Armor mutations and CBMs suck

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16739]
Sample values:

| Name | Bash | Cut | Stab |
| --- | --- | --- | --- |
| Hoodie | 5 | 5 | 4 |
| Survivor suit | 12 | 18 | 14 |
| Sweatshirt+hoodie+underwear | 12 | 12 | 9 |
| Bionic armor | 3 | 3 | 2.4 |
| Carbon filaments | 2 | 4 | 3.2 |
| Chitin plates | 2 | 8 | 0 |
| Bark | 2 | 0 | 0 |
| Thick scales | 0 | 4 | 0 |
| Shell (actual) | 0 | 0 | 0 |
| Roomy shell (actual) | 0 | 0 | 0 |
| Shell (intended) | 6 | 14 | 0 |
| Roomy shell (intended) | 9 | 17 | 0 |

Mutant armors are clearly outclasses by plain cotton fabric. This is tolerable in case of mutations like bark and chitin skin and in case of armor bionics, which are just an extra +x on top of everything, but for chitin plates and roomy shell it means giving up the heavy-duty cotton exoskeleton for crap that doesn't even protect from zombie children.

**Comment by baraba3** [comment]
i agree..shell and chitin mutation were seriously dangerous for character survival.

though somewhat unrelated but as it appered in post  i must add that hoodie protection is  in my opinion unrealisticly high.i wear hoodies and very much doubt they are better in protection   than its main in game  rival trenchcoat.but they shoudl be far easier to wear than simulated compared to trenchcoat.-6 vs 7 encubrance in game.
protection of 5 is high and combined with 95% coverage make hoodies  very diserable to wear.even compared to gambeson which  have 80% coverage and protection of 8 and it was historical dedicated armor.

**Comment by AppleConnoiseur** [comment]
Can add the Rivtech power armor to the list as well. Sucks for what it does and seems broken in general in how you add Plutonium Cells to it.

Most players can just stick to the heavy survivor armor and do better without any high tech power armor.

**Comment by Coolthulhu** [comment]
> Can add the Rivtech power armor to the list as well. Sucks for what it does and seems broken in general in how you add Plutonium Cells to it.

It only sucks now due to a hardcore bug with reloading which I'll report in just a moment.
When it is working (getting 500 charges of plutonium per cell), it is one mean piece of heavily overpowered gear that protects from everything without encumbering anything.

**Comment by illi-kun** [comment]
What values are acceptable for bionics?

Description of bio plating states that
``` "The flesh on your torso has been replaced by a strong armor, protecting you greatly."```, so from one side, we need significant buff, but from another side it shouldn't be an ultimate armor by itself since it's only one layer of armor.

Carbon filaments should have pretty minor effect by design, so it's almost okay as it is.

How about this?

Name | Bash | Cut
--- | --- | ---
Rivtech Armor (ref.) | 15 | 38
Bionic armor (current) |	3 | 	3
Carbon filaments (current) |	2 |	4
Bionic armor (proposed) | 12 | 6
Carbon filaments (proposed) |	3 | 	6

**Comment by Coolthulhu** [comment]
Would be perfect if they could have non-linear effect, like 30% damage resistance.

In any case, no armor should grant more protection from bashing than cutting. Bashing is supposed to be the armor piercing type.

**Comment by mugling** [comment]
Would it not be better if `DT_BASH` was more effective against armor then? We could then start to have more easily comparable armor numbers.

Also thick padded armor should be good against `DT_BASH` but not so much against `DT_CUT` etc?

**Comment by Coolthulhu** [comment]
> Would it not be better if DT_BASH was more effective against armor then?

It has better crits, but monsters don't crit.
Hardcoded armor penetration not included in numbers would be a bad idea.

> Also thick padded armor should be good against DT_BASH but not so much against DT_CUT etc?

It is already the case - cutting damage is higher, meaning you need more armor or dedicated anti-cut armors.
If anything, leather should get a buff to cut resistance.

One of the problems with armor tweaks is the ugly thickness system. Someone thought it was a good idea to tie in-game properties to arbitrary approximation of real life properties.
But as with all such approximations of real life, it failed both at real life AND at game parts, resulting in 2 dresses having armor value of leather pants, shredded t-shirts offering real protection against punches, and zombies with enough strength to knock down houses being unable to damage a leather-trenchcoat-wearing fedoralord.

**Comment by mugling** [comment]
We have way to many armor items to start specifying absolute values for them all. The best I can think of is having all of our variants of pants derive from a common ancestor with carefully chosen armor stats and continue in that pattern?

**Comment by illi-kun** [comment]
@Coolthulhu 
> Would be perfect if they could have non-linear effect, like 30% damage resistance.

This maybe good from game balancing perspective but it's not understandable from player POV: something that (according to its description) ```replaces your flesh``` just reduces some part of damage? I see these CBMs more like integrated analogue of plate armor, so only high damage (above some reasonable threshold) should penetrate it (so ```applied damage = max( 0, total damage - threshold)```).

@mugling sounds good because currently any random item can be chosen as a reference and it means that we're not actually balancing items between each other, we just balancing two randomly selected items.

**Comment by Shinino** [comment]
Just curious -- this still a thing?  I'm reading this and it seems like what it's saying is:  Armor on clothing/bionics/everything needs to be redone.

Am i incorrect?

**Comment by kevingranade** [comment]
Nope, it's pretty much dead as a specific issue, but if someone wants to pick up some aspect of it they can feel free.
