### ISSUE TITLE
The mod name "PKs Rebalancing" might be misleading to new players.

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#16738]
No offence to @pisskop but the title "PKs Rebalancing" and description "Rebalances spawning and adds critters.  Currently in the process of updating, please see the forums for the full mod." does not describe the mod very well. I've not actually played this mod yet but I looked at the files and saw that this mod contains things like cyberdemons, space marine armor, and weapons like the napalm launcher. This may cause some confusion between whats in the mod and whats in the vanilla game to someone who is new to the game or does not follow the happenings on github. Perhaps adding Sci-fi fantasy somewhere in the title or description might help.

**Comment by pisskop** [comment]
I could likely lay out several reasons why the mod is no more scifi than the base game.

the least of which being the lack of supernatural elements such as wraithmen, the inclusion of what little scifi there is being a faction taken from a franchise with a clear theme of future-alien


The fact that the player has no access to this trumped up napalm cannon, that they cant wield the enormous rocket launcher, and that 'space marine helmets' are statistically weaker than power armor and on par with survivor gear is a reason.


the fact that this mod started as a rebalancing and has continued to do so while becoming a critternod is another

you have no real reason to rename it as a scifi mod because theres not a whole lot of science or fiction in ir.

**Comment by Coolthulhu** [comment]
> you have no real reason to rename it as a scifi mod because theres not a whole lot of science or fiction in it.

90% of the mod is pure sci-fi, though.

**Comment by pisskop** [comment]
all of your listed examples are lifted directly from the Doom submod, which has its own goals and development thread.
 ob
none of the guns or ammo given to the monsters are player obtainable without debugging, and they only serve to give the monsters their cannon ranged attacks.  the fact i have to use guns is a sign of rigidcode, not preference.

cybernetic monsters are few and strictly due to lore reasons.

**Comment by pisskop** [comment]
@coolthulu

except it isnt.

the base of the very game, mutating balps of goo, is whats scifi.  thios mod does little to introduce new mechanics, themes, or elements.

**Comment by Coolthulhu** [comment]
Firebreathing ants, electric larvae, ethereal zombies, giant tardigrade, kamikaze plants etc.
And the doom submod, which is a part of the mod.

If you want to keep your name in the mod, say so. Don't flat out lie that it isn't sci-fi when it clearly is.

**Comment by Cyrano7** [comment]
@pisskop This is a issue not a PR. I'm not trying to rename your mod. I'm just saying maybe you should put something in the title or description that says there is more than just rebalancing and critters in here. The other thing is the imps and demons and hell stuff isn't really part of the lore so having It sneak into peoples games is not good. Same with the space marine armor the setting is "near future".

**Comment by pisskop** [comment]
@coolthu

the part that gets here is how you, who added a magic healing blob, invasive plants from a franchise, passive fungaloids that allow you to retain sentience if you perform an elaborate ritual, eldritch abominations, teleporters,  snailman, a shadow summoning serial killer, aborted babies in fast food dumptsers, bandages that heal wounds mutations into new creatures, bionic cyborgs and several pop culture references but you want to label the mod as 'scifi'

Working with the above to create a more varied and combative experience

**Comment by Coolthulhu** [comment]
> aborted babies in fast food dumptsers

?

**Comment by pisskop** [comment]
the pizza hut babies

**Comment by pisskop** [comment]
_@pisskop This is a issue not a PR. I'm not trying to rename your mod. I'm just saying maybe you should put something in the title or description that says there is more than just rebalancing and critters in here. The other thing is the imps and demons and hell stuff isn't really part of the lore so having It sneak into peoples games is not good. Same with the space marine armor the setting is "near future"._

None of the mod is snuck in.  It clearly, in the thread, lays out what creatures are in the game.  In fact, its requested.  The description does have to be updated, but theres still PRs missing from the mod itself.


I do believe I tried to add the doomy bit seperate from the rebalancing bit.  It gained zero traction here.

I also provide blacklists upon request as well as any other relatively simple mods.

None of this has been foisted on the player.  Somebody using a mod that has 25000 lines of code should be reading a little more than just the description of the mod at the mod window.

**Comment by pisskop** [comment]
And assuming this is about keeping my name in the title is just a little insulting

**Comment by valuial** [comment]
Leave the PK, I've no issues with that. But it is by no means rebalancing. Maybe "PK Extension Mod" or PD additions? whatever. It's simply not rebalancing.

You add a lot of stuff, and "read the forums" isn't an option for ingame descriptions if you ask me. Do write what it does in a clear understandable way... Not every player (new player) will want to read the forums for a mod that's included in the game...

**Comment by pisskop** [comment]
A readme or something might be in order.  For offline reference.

**Comment by karols146** [comment]
Rebalancing can be simple confusing. Like @valuial write, 'PK Extension Mod' would be ok, in my opinion.

**Comment by strife26** [comment]
It's got a name that's not indicative of what it does and a descriptor that isn't remotely accurate telling users to go somewhere else. Change the name to "PK rebalancing/additions mod" and the descriptor to "adds a bunch of stuff that PK really feels should be in the main game for various reasons but isn't."

The sheer defensive hostility shown for a simple issue is somewhat surprising to me.

**Comment by pisskop** [comment]
It was and still is a mod aimed at rebalancing the factions and the difficulty level of the game.

My issue is with the idea that while acid spitting dead people are coolsauce, when spiders do it its scifi?  and that it should have a tag of such rubber stamped on it?

I rather like the name and acrynom that results, and I dont particularly see why a renaming was even an issue.  But Im not even interested in keeping my name on the mod.  This was never about my name being in the mod at all.

I dont have ready names for this.  It isnt something I was ever concerned with. PRM worked and that was enough.

**Comment by pisskop** [comment]
For shame community.  For shame on you.

**Comment by pisskop** [comment]
So what we have is a community who hasnt played the mod, most of the people who support its . . . whatever it is you want to do with it havnt even properly looked into the mods contents nor have you even don enough work to sass me correctly 

+1

**Comment by Coolthulhu** [comment]
> My issue is with the idea that while acid spitting dead people are coolsauce, when spiders do it its scifi?

You could say your mod isn't THAT much more sci-fi than core game, as the core game is already pretty sci-fi.

You didn't. You said
> you have no real reason to rename it as a scifi mod because theres not a whole lot of science or fiction in it.

which is clearly false and
> all of your listed examples are lifted directly from the Doom submod, which has its own goals and development thread.

which is really not an argument for as long as the submod is still a part of the mod.

I'm not saying it should be renamed or that if it was to be renamed it should say it's sci-fi.
But don't claim it isn't sci-fi when it clearly is sci-fi and more so than the core game.
> All the thumbs up only seem to indicate the crowd mentality here. 

Or maybe that people like some ideas you disagree with, and that they like those ideas for a good reason.
For example, the part where "rebalancing" suggests number tweaking, not adding a whole set of critters to every faction. Rebalancing is just a small part of the mod, rest is additions.

**Comment by Cyrano7** [comment]
Just fyi @pisskop anything you write here (even if its deleted or edited) can still be read in its original form. Please be sure you want to post something before you do. So ya... shame on me for opening this issue.

**Comment by John-Candlebury** [comment]
Yeah I would expect that a mod that labels itself as a rebalancing mod would only affect  spawning numbers, monster difficulty and  armors and weapons stats.

Some general indicator of how difficulty changes would be nice in the description

**Comment by pisskop** [comment]
Aye.

So rebalancing is a misleading term.  There does need to be a description that is a little longer than "adds stuff", and I should be telling people the intent of the modification is to make the game harder.  And a readme or link to the thread via a readme.

I dont regret what Ive posted v: they can come across as needlessly antagonistic.

**Comment by Coolthulhu** [comment]
>  There does need to be a description that is a little longer than "adds stuff", and I should be telling people the intent of the modification is to make the game harder.

Could be something like
> Adds many new creatures and rebalances existing ones to make the game more challenging.

**Comment by mugling** [comment]
Comments in this issue include ad hominem attacks which have no place in a technical forum. Additionally editing of comments has made much of the discussion difficult to follow. As a result nothing productive is being achieved nor is likely to be. Discussion can continue in #16767

**Comment by tsaber** [comment]
how similar the structure of this thread is to mine. Jerk-attack into circle-jerk
