### ISSUE TITLE
Lack of info about the latest features in the built-in Help

### ISSUE THREAD

**Issue by illi-kun** [CleverRaven/Cataclysm-DDA#16734]
There are no mentions of
- [ ] aiming system (including details about how sights are working),
- [x] vitamins (updated in #19321 with BeerBeer's text),
- [x] magazines (updated in #19506 with BeerBeer's text),
- [ ] faulty vehicle parts,
- [ ] NPC-related info,
  ... and maybe some other significant features added recently.

It will really great to see at least short notes about all of that.

**Comment by AppleConnoiseur** [comment]
New CBM system where slots will eventually be taken in account?

**Comment by Coolthulhu** [comment]
CBM slot system exactly isn't in the game yet. Same for vitamins.
It would be nice if their authors started documenting the features even before they're in, but it's not necessary.

**Comment by Labtop-215** [comment]
I'm kind of confused about why there are only vitamin amounts displays on some food, but not others.  Does honey give no vitamin's at all?

**Comment by kevingranade** [comment]
Very old wishlist issue, these are nice to haves, but immortal issues aren't a good way to track them (consider a project).
