### ISSUE TITLE
Invalid ammo none for soldering iron (UPS)

### ISSUE THREAD

**Issue by ifreund** [CleverRaven/Cataclysm-DDA#16736]
Debug message popped up while using a fully charged (200 charges) soldering iron (UPS) to craft an extra battery mod while a Unified Power System CBM was enabled

```
DEBUG     :  Tried to set invalid ammo of none for soldering iron (UPS)

FUNCTION  :  item &item::ammo_set(const itype_id &, long)
FILE      :  src/item.cpp
LINE      :  247
```

Didn't seem to cause any problem after pressing spacebar to continue

**Comment by illi-kun** [comment]
What game version do you use?

**Comment by codemime** [comment]
Duplicates #16287.
