### ISSUE TITLE
Unable to mop liquids out of containers in vehicles 

### ISSUE THREAD

**Issue by ifreund** [CleverRaven/Cataclysm-DDA#16748]
As far as I can tell, the only way to get rid of a liquid in a storage area of a vehicle and in no container (bottle, jar, etc.) is to remove the vehicle part in question and reinstall it.  This makes no sense, and while I question the ability of a wire basket to hold a liquid, I think the best fix to this would be to make mops work or supply some other method of emptying the vehicle storage of liquid.

**Comment by Coolthulhu** [comment]
How did it get there in the first place?

It should probably be spilled below instantly.

**Comment by ifreund** [comment]
Im not really sure, I think there was a glass bottle of mineral water in the cart which broke, or something along those lines.

**Comment by sethsimon** [comment]
I'm not sure if it's possible without using the debug menu (wish for liquid not in a container, then drop it in the cargo space). Based on my tests, smashing the part till it breaks results in either intact glass bottles of whatever landing a few tiles away or liquid on the ground. Throwing it at a cargo space yields liquid on the ground. And silly amounts of explosives also leave liquid on the ground.
