### ISSUE TITLE
Plutonium reloading broken

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16741]
Affects native plutonium items (RM13) and atomic battery mods.
When reloaded, those items consume a single plutonium cell charge and gain number of charges equal to size of the stack.

For example, a stack of 10 cells used to reload a RM13 will grant the RM13 10 charges and become a stack of 9 cells.

Additionally, atomic battery mod applied to items with batteries in them will turn it unreloadable. It can be fixed by applying a screwdriver to the modded item, loading it with batteries, unloading the batteries and reapplying the mod.

**Comment by karols146** [comment]
#16273 Similar

**Comment by player0981234** [comment]
nobody even cares about plutonium

**Comment by illi-kun** [comment]
@player0981234 your endless complains are quite annoying.

**Comment by player0981234** [comment]
That's how my parents complain about me.

**Comment by mugling** [comment]
Lots of recent changes to related code. Confirmation anyone?

**Comment by BorkBorkGoesTheCode** [comment]
Currently, reloading a RM-13 armor will remove 1 plutonium cell from inventory and add 500 charges to the armor.

**Comment by mugling** [comment]
That sounds correct

**Comment by Coolthulhu** [comment]
All other ammo types reload all at once. Unless RM-13 has the RELOAD_ONE flag, it shouldn't act like that.

**Comment by mugling** [comment]
> Unless RM-13 has the RELOAD_ONE flag

It doesn't and #19502 doesn't change anything in that repsect

**Comment by mugling** [comment]
Bug is probably in `item::reload_option::qty`
