### ISSUE TITLE
"Simplified nutrition" mod crashes the game when entering character creation

### ISSUE THREAD

**Issue by jedibob5** [CleverRaven/Cataclysm-DDA#16745]
When I create a world that has the simplified nutrition mod activated, attempting to create a character for that world immediately crashes the game, with a generic "cataclysm-tiles.exe has stopped working" message. Version: 0.C-14177-gae51d65

**Comment by karols146** [comment]
Work normally here. You have only that mod ?

**Comment by codemime** [comment]
Can confirm. It does crash for me too.
