### ISSUE TITLE
Butchering acid zombies should give acid sacks

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#16743]
currently smashing acidic and spitter zombies sprays acid everywhere, but butchering them just leaves tainted meat and bones.

It would be neat if butchering them yielded acid sacs, with a decent chance to rupture a sack and spill acid in your tile if your butchering skill is too low.

we'd have to balance the difficulty of using the sacs as anything other than thrown splash damage weapons since acid can make batteries, possibly at cooking 4 since that's where you can make concentrated acid from water.

**Comment by Coolthulhu** [comment]
I wanted to implement that for a while, but didn't want to hardcode yet another part. Butchery code is cluttered enough as is, it needs to be reworked before we add more parts.

**Comment by Xpyder** [comment]
fair enough, is there a tbd later tag?

**Comment by pisskop** [comment]
Why would it need to be a hardcoded item?

If its a fluidsac-like item its not going to be smashing like a glass bottle with acid in it.  And perhaps you could even get away with making it a container of acid.

If its more or less dangerous enough to hurt blob/zombies its going to be in a mucusy, protected organ, which will prevent it from being used as an effective thrown weapon without crafting.

And its purpose could be to craft acid from it. Whether it is a simple stab and drain motion or a full-scaled chemical refinement process.

**Comment by Coolthulhu** [comment]
> Why would it need to be a hardcoded item?

Because butchering drops need to be hardcoded at the moment.

**Comment by Xpyder** [comment]
I wonder if butchering could be adjusted to use the monster drop loot tables, like butchering transforms them into a xxx_butchered "virtual creature" that drops the butchered items.

**Comment by Coolthulhu** [comment]
Then skills couldn't determine drop results.

**Comment by AppleConnoiseur** [comment]
Wouldn't just acid zombies simply spill out all their contents on death since their description basically says it is a animated acid bag :P.

**Comment by Xpyder** [comment]
@Coolthulhu 
You're right... hurmpf.

**Comment by Labtop-215** [comment]
Wouldn't it just be better if butchering an acid zombie always spilled acid on your tile instead, to make them harder to get rid of?

**Comment by Xpyder** [comment]
The damage would force a few dozen prompts every time you tried to get rid of a spitter or acid zombie which would just be tedious, not interesting.

By dropping acid sacs (with a high chance to break them if using a low skill) we add an ingredient that can potentially be used for interesting recipes down the line or used in clever ways, especially if the acid works on plants or environmental objects

**Comment by Leland** [comment]
Haven't seen action on this suggestion in about a year, so I'm closing this. Feel free to create a new issue or comment here if anyone's still interested.
