### ISSUE TITLE
Fields on vehicles

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16740]
Vehicles can have blood on them. But nothing else - just blood.
Adding the ability to have certain types of fields on vehicles would allow:
- Smoke getting inside vehicles
- Smoke getting generated inside vehicles (say, from faulty engines)
- Sitting in vehicle not giving total immunity to acid fields
- Colorful stains on windshield
- Gibbed/biled-up windshields blocking vision. Would require changing how quarterpanels work against those, though
- Burning vehicles
- https://www.youtube.com/watch?v=rE7T7UQ4KxI

**Comment by Xpyder** [comment]
or painting your vehicle?

**Comment by Coolthulhu** [comment]
Painting with blood and guts, not paint.

**Comment by Xpyder** [comment]
well the red ones do go faster

**Comment by codemime** [comment]
Vehicles are already red in the most popular tilesets. I'd suggest repainting them in a more neutral color to prevent obscuring splatters of BLOOD (after we add them in the tiles version too).

**Comment by AppleConnoiseur** [comment]
Painting vehicles could be kewl. More flavor text and tilesets could have more visual variety :P.
Chromed shiny sports cars anyone?

**Comment by Xpyder** [comment]
I so want to paint myself a Stank Gum battle bus.  VIOLET VIOLENCE FOR LIFE

**Comment by Xpyder** [comment]
@codemime 
http://wh40k.lexicanum.com/wiki/Ork_Vehicle_Upgrades

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
