### ISSUE TITLE
Tool containing a null

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16751]
I killed a zombie and it dropped a curved needle that had "seeing this is a bug" below its own description.

I saved the game and checked the save to see what's going on and in the save, the needle had a null item (item with id "null") as its contents. This didn't change when I unloaded the needle.

That may be the cause of unusable tools described on forums. Tools with contents will not be used as components and possibly as tools either (cans with contents can't be used to boil water).

Tagging as magazine because it is clearly associated with changes to magazine system.

**Comment by pisskop** [comment]
This happens to welders and apparently acetylne torches that spawn.

Genning in new ones and loading them seems to work fine, as does crafting your own.


I was sure I commented somewhere on git in an issue already, but I guess not.

**Comment by Coolthulhu** [comment]
Didn't see it on git, if you can find a link I'll mark this one as duplicate. I've seen at least one post on forums describing it.

**Comment by pisskop** [comment]
I had a heating pack drop with the 'seeing this is a bug' descriptor.
