### ISSUE TITLE
Metal Sawing not considered properly when removing vehicle parts

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#16760]
Survival Knife has the same metal sawing level as a hacksaw (which itself might need to be changed), but when trying to remove a quarterpanel it says I'm still missing hacksaw.

This seems like something that still hasn't been ported over to the new qualities system.  If it's something I can submit a PR for just tell me where to find the appropriate files and something to use as an example.

**Comment by Coolthulhu** [comment]
Removing vehicle parts requires "fine metal sawing", while survival knife only grants the regular one.

**Comment by Xpyder** [comment]
Ah, ok.

**Comment by Xpyder** [comment]
is there any way to change the "needs hacksaw" to "needs fine metal sawing"?

**Comment by Coolthulhu** [comment]
@mugling said he wants to rework vehicle work requirements to more like crafting menu. This would make it display actual requirements (fine sawing) rather than tool names.

**Comment by Xpyder** [comment]
cool
