### ISSUE TITLE
overhead lights blocked by heavy duty hatch

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#16763]
overhead lights blocked by heavy duty hatch, if you open the hatch the light gets out.

I am using most of the vehicle packs so I don't know if the heavy duty hatch is in default, but it probably applies to the basic hatches too.  If not please let me know.

**Comment by kevingranade** [comment]
Are you saying it blocks light but shouldn't, or that it should?

**Comment by valuial** [comment]
I think what caused this issue, is that to some "overhead" implies the light source being above the vehicle, which would then not be blocked by other parts of the vehicle.
The current implementation though puts the light source inside the vehicle - the only difference to headlights the 360° of illumination - and thus being blocked by any opaque part. (for example the hatches, but also boards and more)

**Comment by Xpyder** [comment]
@kevingranade 
That it blocks light and it shouldn't

@valuial 
That's exactly right, Floodlights are designed to be mounted on top of a vehicle not inside, my assumption is that it shouldn't be blocked by internal components.

It also seems to happen with emergency lights like what's on an ambulance or security van.

**Comment by Night-Pryanik** [comment]
![изображение](https://user-images.githubusercontent.com/11132525/55679152-6c715f80-5917-11e9-81d6-a25482acf4a9.png)
![изображение](https://user-images.githubusercontent.com/11132525/55679155-76935e00-5917-11e9-9a72-db4239b4dc9f.png)
![изображение](https://user-images.githubusercontent.com/11132525/55679169-c4a86180-5917-11e9-8014-413f37cf617a.png)

Can't confirm. Tested on the latest experimental as of April 07 2019. I'd say floodlight lights up too much instead - I can see illuminated seats and boxes inside the vehicle.
