### ISSUE TITLE
Consistency in exiting menus

### ISSUE THREAD

**Issue by ifreund** [CleverRaven/Cataclysm-DDA#16765]
The new menu that pops up when examining a toilet gives options to drink the liquid or pour it on the ground.  However, unlike other menus in the game it has no cancel option.  I think this should be added to be consistent with other menus, such as butchering or repairing clothing.

**Comment by mugling** [comment]
Try escape key, this is consistent with many other menus

**Comment by ifreund** [comment]
I know that escape key works, I'm just saying that q for cancel should work as well

**Comment by mugling** [comment]
That behavior would cause problems in menu's that assign hotkeys based upon invlets (as `q` and `c` are both valid invlets). `Esc` doesn't have this problem

**Comment by ifreund** [comment]
Then, for consistency, would it make more sense to remove the **q** cancel option from butchering and repairing?

**Comment by mugling** [comment]
Yes, I think we should aim for consistency and using `Esc` guarantees no conflicts with existing hotkeys (however they are allocated)

**Comment by ifreund** [comment]
So moving forward, should we just remove the cancel option from menus that currently have it? Or replace it with ⎋? (I know that is unicode not ascii so that would be annoying.)  If we remove the cancel option would it be unclear how to exit a menu without choosing a listed option?

**Comment by illi-kun** [comment]
Particular case of #12112.
