### ISSUE TITLE
Broken limbs lack of feedback

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#16764]
Currently broken limbs just look like they're damaged and not healing which makes it look like a bug.

Could an Effect be added that better explains what's going on (even better if it could have different descriptions based on your first aid skill)?

**Comment by Skidborg** [comment]
I seem to recall that way back in the day broken limbs were a grey `:` rather than a red one.  That seemed to make things clear enough.

**Comment by Coolthulhu** [comment]
The math in `get_hp_bar` is incorrect:
```
double const ratio = static_cast<double>(cur_hp) / (max_hp ? max_hp : 1);
    return (ratio >= 1.0)            ? strings[0]  :
           (ratio >= 0.9 && !is_mon) ? strings[1]  :
           (ratio >= 0.8)            ? strings[2]  :
           (ratio >= 0.7 && !is_mon) ? strings[3]  :
           (ratio >= 0.6)            ? strings[4]  :
           (ratio >= 0.5 && !is_mon) ? strings[5]  :
           (ratio >= 0.4)            ? strings[6]  :
           (ratio >= 0.3 && !is_mon) ? strings[7]  :
           (ratio >= 0.2)            ? strings[8]  :
           (ratio >= 0.1 && !is_mon) ? strings[9]  :
           (ratio >= 0.0)            ? strings[10] : strings[11];
```

To print an empty HP bar, it would need a `<0` hp ratio, which obviously isn't possible.

**Comment by Xpyder** [comment]
I read on the forums that it might be possible for them to get destroyed entirely rather than just broken.

I suggested the effect because they will heal, it just takes about a week wearing a splint for it to start, and it's not obvious that it takes that long they way it's currently hinted at.  It's very easy to assume you're doing something wrong or that you need to do something more.

@Coolthulhu 
Also I thought the hp on a limb supported negative values?

**Comment by valuial** [comment]
The bars/slashes are nice to get an idea how much hp the limb/body part has, but broken and/or destroyed body parts don't really have hitpoints in that sense, so what prohibits us from using words or abbreviations to show broken (brkn?) or destroyed (destr?) body parts? It would make it both much more visible and give the desired feedback?

**Comment by kevingranade** [comment]
That's a good idea.
