### ISSUE TITLE
Gun point-blank accuracy penalty checks for "shot" ammo_type instead of "SHOT" ammo_effects

### ISSUE THREAD

**Issue by Crispy6** [CleverRaven/Cataclysm-DDA#16761]
Windows 10
Tiles
0.C-14084-gd5f8f59

The accuracy penalty for using bulky weapons at point-blank range (except when loaded with shot) is checking only for 12 gauge shotgun ammo,
```
if( gun.ammo_type() != "shot" )
```
instead of checking for the "SHOT" ammo effect, e.g.,
```
if( !weapon->ammo_effects().count( "SHOT" ) )
```

**Comment by mugling** [comment]
Fixed by #16799
