### ISSUE TITLE
Bug when reloading L523-MBR rifle ,got 2 fully loaded magazines

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#16771]
when i reloaded a L523-mbr rifle with a LW-30 magazine, it became fully loaded ,and i also got a error message, something about trying too take something from my inventory but failing too? im not sure, but i reloaded the rifle, and the clip still stayed there, and the rifle was loaded. what was wierd is that i had like, 4 or 5 fully loaded LW-30 magazines, all with 32 rounds of 5.56 nato, and yet one of them wasnt stacking. when shown in advanced inventory, it would show the 3 or 4 LW-30 magazines with 32 rounds of 5.56 nato in 1 row, with an ammount being shown as 3 or 4, (i may have had 5 or 4 magazines before the bug, im not sure but that shouldnt matter) and then 1 extra LW-30 magazine with 32 rounds of 5.56 nato in another row.

**Comment by 321nick** [comment]
oh and this is with build 4883

**Comment by DLaboratory** [comment]
Might be a duplicate of #16445?

**Comment by mugling** [comment]
Duplicated by #16771

**Comment by BorkBorkGoesTheCode** [comment]
>Duplicated by #16771 

Circular link. #16445

**Comment by mugling** [comment]
No this one was closed and the other was left open
