### ISSUE TITLE
Cantilever missing critical info 

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#16779]
I don't see any way to tell the lifting load of a cantilever.  All the jacks say how much they can lift but I can't find this info on either of the cantilevers

**Comment by Dozed12** [comment]
Each "JACK" quality point seems to give 500Kg lift, doing the math for the cantilever ...

cantilever_medium: 6 metric tonnes
cantilever_small: 1.5 metric tonnes or 1500Kg
