### ISSUE TITLE
Effect grack not used 

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#16784]
It was mentioned here also https://github.com/CleverRaven/Cataclysm-DDA/pull/12721
There is a reference to grack cocaine in iuse but besides that there is no item or recipe. In its current state its effects are super OP but it would be a interesting item if implemented. Like the grakens are from a drug experiment gone horribly wrong. If its not a fit for the game I guess it should be removed though.

**Comment by i2amroy** [comment]
IIRC it was an old debug item that essentially stopped time. The debug item was removed at some point, but the effect was missed.

**Comment by Cyrano7** [comment]
Okay. I guess I'll just take it out then.

**Comment by Cyrano7** [comment]
Ah okay.
