### ISSUE TITLE
Reloading Chemical Thrower takes an unusually long time

### ISSUE THREAD

**Issue by Hague** [CleverRaven/Cataclysm-DDA#16788]
Reloading the chemical thrower weapon from empty to full (800 units) takes over 8 hours of game time. Unloading the same thrower is nearly instantaneous.

Version: 0.C-14179-g7f3020a (tiles)

**Comment by mugling** [comment]
Known cause, will submit PR

**Comment by Coolthulhu** [comment]
Still happens in the most recent versions. Can be bypassed by unloading a container into the thrower instead of reloading the thrower.
