### ISSUE TITLE
Gas/Diesel ammo defaults to igniting when shot and should be inert instead?

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#16780]
Gasoline and diesel, as well as things like oil, default to igniting into fire and streams of flame when propelled by a gun.

The gas isn't ignited by the force of ejection, its ignited by the flamethrower or suchlike that shoots it.

  There have been a few requests to fire gasoline from a gun without setting it on fire, for the purposes of setting traps and setting it later.

  I find the idea that gas can be used as a trap dubious in reality, but under the rules of the C:DDA world its possible, and without evaporation even worthwhile to shot gasoline 50 units at a time onto the ground and then either use a match or a main-fire flameshot to ignite the gas in a massive glorious explosion.

And even cooler is the idea that you could use a refillable light to hollywood it up and toss a lit lighter at the gas.

**Comment by Coolthulhu** [comment]
This wouldn't work well with current fire mechanics. The fire would lose all fuel very quickly.

**Comment by pisskop** [comment]
It takes between 400 and 450 gas to make a 'fire' as opposed to a small fire.

Which is steep.
