### ISSUE TITLE
Dissasembling steel frames requires tool with glare protection 2 or more

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#16783]
such is the message i get when i forget to bring wielding googles or pba mask in field and i need some lumps of steel to cut with my toolbox from vehicle parts.toolbox or hacksaw as far as i now doesnt include welding.

**Comment by illi-kun** [comment]
I've changed the header because this bug is reproducible with a hacksaw too, so all you need to disassemble a frame is a hacksaw and welding goggles (without a welder).

**Comment by pabrams** [comment]
@illi-kun Why would you need welding goggles to use a hacksaw on a steel frame?

**Comment by Night-Pryanik** [comment]
Closed by #22774.
