### ISSUE TITLE
Bad code quality in mending long action finish function

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16792]
I merged #16464 despite the low quality of long action function because it fixed a confusing and annoying issue of not being able to fix an engine fault without picking the engine up.

The issue is that `player_activity` does not contain `item_location`, so instead coordinates, index and type of the item location are saved and `item_location` is reproduced on the other end.

This should be fixed before adding more fault-related features. It should also be handled when an old save containing this weird structure is loaded. Canceling the activity would be enough, but it shouldn't crash.

**Comment by mugling** [comment]
#16791 is intended to fix this

**Comment by kevingranade** [comment]
I've been looking into this as well, and am nearly finished with a slightly
different aporoach.

**Comment by mugling** [comment]
Presumably via serialization of `item_location`? Do you want to push a branch for that and/or collaborate?

**Comment by mugling** [comment]
Anything further for #16791?

**Comment by mugling** [comment]
Fixed in `master`
