### ISSUE TITLE
NPCs help with deconstruction while sleeping

### ISSUE THREAD

**Issue by ifreund** [CleverRaven/Cataclysm-DDA#16809]
My NPC friend was sleeping, and I wanted to make some rope, so i deconstructed a bed next to the NPC.  To my surprise, she helped me out!  At first I thought she had woken up, but it turns out she was still sleeping.  She even helped me disassemble the bed she was sleeping on!  This should probably be fixed at some point, but isn't really a huge deal.

**Comment by pisskop** [comment]
they also learn while asleep.

**Comment by valuial** [comment]
should fix npcs learning when asleep and reading books for you while sleeping as well as crafting/constructing...
