### ISSUE TITLE
Segmentation fault viewing A7 Laser Rifle in inventory

### ISSUE THREAD

**Issue by cdag** [CleverRaven/Cataclysm-DDA#16803]
On the latest experimental, when I pull my A7 Laser rifle out of my back holster and inspect it or drop it I get a segfault. I've included a backtrace... sort of new to this hope it helps.
**File Removed**

**Comment by mugling** [comment]
No debugging symbols

**Comment by cdag** [comment]
My apologies, forgot I wasn't using the debug build. Here is the new backtrace log... Hopefully i got it right this time :)
[gdb-log.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/276158/gdb-log.txt)

**Comment by mugling** [comment]
null pointer dereference via `item::info`. @cdag if you know how to bisect then great but I think I have an idea as to the faulty commit

**Comment by cdag** [comment]
I must be honest... I didn't even know what you meant by bisect till i looked up the git description of it... new to this stuff. Very willing to learn however if you ever have the time or are willing to point me in the right direction where to start...

**Comment by cdag** [comment]
ok... after reading how bisect works and figuring it out to the best of my abilities... 
[bisect-log.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/276259/bisect-log.txt)
hope this helps...

**Comment by mugling** [comment]
Yes, it looks like the recent gunmod changes are to blame

**Comment by BorkBorkGoesTheCode** [comment]
Any progress toward a fix?
