### ISSUE TITLE
Acid fields spawned by acid bombs do not dissipate

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#16808]
they stay forever.

**Comment by Coolthulhu** [comment]
Acid fields themselves aren't bugged, but for some reason the acid bomb won't remove itself

**Comment by baraba3** [comment]
i though of this as feature not bug lol .it was good for killing mobs  by dragging them to etarnal acid pools created by bombs.

**Comment by pisskop** [comment]
Couldn't I just add a charge (and a per-turn drain on that charge) to the acid bomb actives and have them revert to nothing?

Like 3 or something.

**Comment by pisskop** [comment]
Ive got some acidbomb replacements ready to go with recipes and all that if nobdy will object to them.

**Comment by pisskop** [comment]
Going from the top left and going clockwise:

micro acidbomb, small acidbomb, medium acidbomb, large acdibomb.  On the bottom is the everlasting acidbomb in the game currently.
[img]http://i.imgur.com/A4VGoAt.png[/img]

**Comment by pisskop** [comment]
fixed.  I presume.
