### ISSUE TITLE
Crash when Creating world with Perfect Reliability mod installed

### ISSUE THREAD

**Issue by DearVarun** [CleverRaven/Cataclysm-DDA#16827]
#On a fresh install, when ever I enabled the Perfect Reliability mod the game crashed when  it generated the world.

**Comment by codemime** [comment]
Does your build use sound?

**Comment by mugling** [comment]
Somewhat duplicates #16745

**Comment by codemime** [comment]
That's what I was going to investigate. It can be a different crash though.
