### ISSUE TITLE
Change name 'adrenaline injector' to 'shot of adrenaline'

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#16826]
Change the name of adrenaline injector to something that isn't usually the first on an alphabetical list.

If I had a dollar for every time Ive accidently popped an adrenaline shot on accident I'd buy myself a nice steak and potatoe.

Asprin is harmless.

**Comment by Rivet-the-Zombie** [comment]
It would be more accurate to the item as well, since it appears to be a simple syringe full of epinephrine, and not some sort of fancy autoinjector thingy.
