### ISSUE TITLE
The encumbrance penalties shown in Player Info don't match the real ones

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#16833]
Almost all of the encumbrance penalties shown under View Player Info > Encumbrance and Warmth are either out of sync with the actual penalties or are just a sentence with no numbers in it.

In the long run all the encumbrance code should probably be changed to share functions with player::disp_info() to keep this from happening again.

**Comment by Crispy6** [comment]
Closed my pull request, seems that choosing to write code similar to the existing code in `player::disp_info()` was highly objectionable. I won't make that “mistake” again.

**Comment by Crispy6** [comment]
Also, the display of falling damage increase due to encumbrance should probably display both numbers with and without a body part's encumbrance. Failing that, displaying it in "percentage points" might be reasonable. Just showing the difference in % would be misleading.

**Comment by Crispy6** [comment]
According to kevingranade, most of the sentences with no numbers were intended.

**Comment by Night-Pryanik** [comment]
What penalties in particular are out of sync?

**Comment by Zireael07** [comment]
This is very old and the person reporting is now a ghost, recommend closing.

**Comment by Night-Pryanik** [comment]
Okay, closing for now. Ping me if this is still an issue.
