### ISSUE TITLE
Should survivor basements be more rare?

### ISSUE THREAD

**Issue by sanyaskillpro** [CleverRaven/Cataclysm-DDA#16843]
Maybe it's just me, but every second or third basement i encounter is a survivor basement, the one with a bunch of surv\smoker zombies and 2 racks of weapons\ammo. Even though i play with 0.3 loot, on average i get 100-150 "good" ammo(not .22 or birdshot), 2 guns+1 in the safe if you can crack it, 2 mags, 1 gun mod and 1 tool. Surv zombies often carry good loot too.
Now you may say, these zombies are deadly for a weak character if they surround him, but them being in a basement removes all challenge. You can stand on the stairs, yell, and bait them above one by one, then use the regular burning bush or spear kiting tricks to kill them. If you get hurt, just go to sleep and proceed at the next day.
I suggest either lower the spawn rate of this basement, or make it more deadly. Add grappler zombie to drag the player from the stairs. Maybe add brutes to smash the player, if he already passed the gear check to beat the survivor zeds.

**Comment by Hague** [comment]
It has the same ratio that the old gun-nut basements had. There just need to be a greater pool of other basement prefabs to use and these will become rarer.

**Comment by RogueYun** [comment]
Add traps to protect the stash >.>

I feel the same way about every basement I encounter... "Does everyone grow pot in their basements?"

I think we need more basement variety and that is something I've working towards.

Here are some ideas that I had if anyone else was working towards this goal as well:
~Flooded Basement
~Nerd Dungeon (Computers, Linux t-shirts, cheap swords/armor, etc)
~Food Storage (My mom is big into that and that is what primarily fills up the space in her home)
~Carpenter Shop
~Kids Play Room
~Animal Collector (Snakes and such)
~Dojo / Exercise room
~Home theater
~Antique Collector
~Music Band Practice Room.
~Meth Lab
~Library/Study
~Warehouse (cardboard boxes and crates)
~Lan Party/server room.

Some of those can probably be mixed and matched... But those were just some brainstorming ideas... I asked Kevin a long time ago about checking to see if there was a way to contribute basement designs in .json file format. I haven't checked back with him on that though :/

**Comment by karols146** [comment]
@RogueYun Awesome ideas, maybe when i got some time, i just try make some of it real.
Nerd Dungeon :+1:

**Comment by Coolthulhu** [comment]
> Add traps to protect the stash >.>

This would only make sense if trap dungeons had no zombies and vice-versa.

Or if the traps were somehow zombie-friendly.

**Comment by Skidborg** [comment]
Would it be possible to set up the basement in a way so that the zombies were separated from the traps by doors or other obstacles?

**Comment by Headjack** [comment]
Really, there should just be a much higher occurrence of loads-of-junk basements.

**Comment by Hague** [comment]
Additional Basements

- Slime Pit basement
- Serial Killer basement
- Bondage dungeon

**Comment by mugling** [comment]
Original issue is effectively resolved by recent changes in `master`
