### ISSUE TITLE
Handloaded ammo cannot be disassembled

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#16849]
Windows 10
Tiles
Version 0.C-14379-ga3bc3ca

There is no way to disassemble handloaded ammunition.

Making the recipes reversible would be an improvement, even though that would only allow disassembling an entire batch at a time.

**Comment by BevapDin** [comment]
> even though that would only allow disassembling an entire batch at a time.

That has been fixed (tested with a single birdshot charge). The recipe needs the "UNCRAFT_SINGLE_CHARGE" flag (see birdshot example in data/json/recipes/recipe_deconstruction.json).
