### ISSUE TITLE
Github wiki

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#16846]
I've started some documentation in the projects github wiki. Contributions and corrections are welcomed. I'm aiming to provide concise documentation with examples for the code which I've written.

The motivation for this versus the player wiki is that it's easier to quickly update the github version when pushing commits. It should allow greater collaboration amongst developers than PR's that modify  the `doc/` subdir although it isn't a substitute for those either.

**Comment by karols146** [comment]
Have you thought about migrate a existing docs too ?

**Comment by mugling** [comment]
I don't want to supplant the existing documentation otherwise we'd need to keep both copies in sync. The goal is to provide short series of examples as to how a feature works in the hope that others will begin contributing similarly.

**Comment by illi-kun** [comment]
I see no significant benefit from wiki comparing to existing .md documentation. Maintaining both of these systems of docs requires more time/efforts, and can cause confusion.

**Comment by BorkBorkGoesTheCode** [comment]
Could the game display the contents of the .md files?

**Comment by mugling** [comment]
> I see no significant benefit from wiki comparing to existing .md documentation

It was easier to quickly write some documentation on the wiki as there was no need for a PR. Other developers can make small additions/corrections with similar ease.

> Maintaining both of these systems of docs requires more time/efforts, and can cause confusion.

We have a lack of documentation, especially as to the game internals. It's taken me about a year to get up to speed on the code base. I suspect this discourages new contributors. A visible wiki full of short examples might go a long way towards attracting new developers.

Keeping things in sync is a valid concern and I don't have a panacea for that. I'm going to keep writing on the wiki for now but I can move this to `doc`/ if that's the consensus. In particular I'd like to work on an overview of the code base which would be something hopefully everyone could collaborate on?

**Comment by illi-kun** [comment]
Just to make it clearer, I have no special attachment to .md files, I just want to rise the issue that we have two rival documentation systems (oh, BTW, we also have doxygen, so we have _three_ systems!)

@BorkBorkGoesTheCode, no, game doesn't use/interact with markdown (md) files.

**Comment by mugling** [comment]
> oh, BTW, we also have doxygen

We should aim to get that documentation online. It's massively underused considering recent work has greatly expanded upon the coverage

**Comment by BorkBorkGoesTheCode** [comment]
An entry for barrel_length is needed.

**Comment by narc0tiq** [comment]
> We should aim to get that documentation online

Like, at <http://dev.narc.ro/cataclysm/doxygen/>, maybe? That one's built by <http://ci.narc.ro/job/Cataclysm-Doxygen/> and triggered by the on-commit build.

**Comment by mugling** [comment]
That link should be advertised more widely

**Comment by narc0tiq** [comment]
Yup, it should.

**Comment by karols146** [comment]
Why not put this link on wiki home page.

**Comment by illi-kun** [comment]
Wow, this is a very cool link (dependencies diagrams are enabled, ni-i-ice)!

**Comment by narc0tiq** [comment]
I should have it advertise in IRC when it builds; I don't recall why I
didn't have it doing that from the start.

**Comment by BorkBorkGoesTheCode** [comment]
The M1014 uses burst fire to simulate manual rapid fire. I suggest naming manual rapid fire "doubletap" in the wiki.

**Comment by mugling** [comment]
That's an isolated case as opposed to a general rule (feel free to submit a PR however)

**Comment by BorkBorkGoesTheCode** [comment]
Done. #16858

**Comment by mugling** [comment]
Issue has served purpose, some initial documentation has been added. More would be good
