### ISSUE TITLE
offical Mac OS X compiled expmental builds website has lost it's data and needs to be rebult

### ISSUE THREAD

**Issue by ashtiboy** [CleverRaven/Cataclysm-DDA#16852]
offical Mac OS X compiled expmental builds website has lost it's data and needs to be rebult. here's the link tiles build: http://dev.narc.ro/cataclysm/jenkins-latest/OSX/Tiles/  and the curses build: http://dev.narc.ro/cataclysm/jenkins-latest/OSX/Curses/

**Comment by narc0tiq** [comment]
The OSX builds are offline until the person providing our build machine
comes back (the build machine is his laptop, which he needs for work).

**Comment by jakwings** [comment]
You can try my Travis CI deployment in #16224. If anyone think we should not waste large amount of the storage space of GitHub just for experimental builds, we can delete the old releases periodically.

**Comment by ashtiboy** [comment]
ok then jakwings then get the builds up to date the newset master should build for  mac os x now so get the travis cl to build the latest mac os x build from the master drectly
