### ISSUE TITLE
Item pickup bug - dispose of the "none"?

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#16855]
0.C- 14390-gd284582
When a shower victim picks up an item, a message appears asking if the player wants to dispose of the "none" object and wield the object.

EDIT: The dialog appears when the object has volume.

**Comment by Rivet-the-Zombie** [comment]
Can confirm - but it's affecting all professions, not just shower victims.
