### ISSUE TITLE
M1014 fire rate discussion

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#16858]
The in-game M1014 has a burst fire of 2. Judging from the description, somebody tried to use burst fire to simulate manual rapid fire. Should the M1014 have its burst removed, or should the firemode be named "doubletap" using the new firemodes system?

**Comment by Crispy6** [comment]
I vote to remove burst mode from the M1014. If doubletap is going to be added, it needs to be added to lots of guns, not just the M1014.

**Comment by BorkBorkGoesTheCode** [comment]
I have removed the burst fire in #16863 .

**Comment by kevingranade** [comment]
Burst should be removed, burst as implemented now should only be used for
weapons that fire continuously when a trigger is held.
