### ISSUE TITLE
Should the 9x18 derive some of its stats from the 9mm?

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#16859]
@mugling  has suggested that the 9x18 should copy-from the 9mm. Would anybody like to discuss this idea?

**Comment by mugling** [comment]
`"description": "9x18mm Makarov ammunition with 93gr steel core FMJ bullets.  Analogous to the western 9x19mm cartridge"`

That said I think we're perhaps overthinking this a little. Not every detail needs to be subject to decision by committee.

**Comment by BorkBorkGoesTheCode** [comment]
If I use copy-from to copy the 9mm, then copy-from the 9x18, the entries could look confusing. How do "relative" fields interact?

**Comment by mugling** [comment]
See the wiki. TBH I'd just go for `copy-from` then just specify `name` and `description` and leave everything else as-is

**Comment by BorkBorkGoesTheCode** [comment]
The wiki doesn't say what happens when a cartridge derives it's stats using "relative" from a cartridge that also derives it's stats using "relative". If I use copy-from the unique damage, piercing capability, dispersion, and recoil stats for each cartridge will be lost.

**Comment by mugling** [comment]
Each inheritance can be considered a discrete step, eg. 8 + 2 - 3 = 7;

`9mm` and `9x18` should be effectively identical anyway - the description alludes to this.

**Comment by BorkBorkGoesTheCode** [comment]
Okay. I have done this.

**Comment by kevingranade** [comment]
copy-from is an inheritance method, as such it should only be used if the
entity is expected to always inherit the attributes of its parents and
adjust them. If the 9x18 is a kind of 9mm round, with some well defined
difference between the two, that makes sense, but if they just happen to
have similar stats I would discourage you from using the feature.

**Comment by BorkBorkGoesTheCode** [comment]
@mugling  suggested using copy-from

This is the 9x18mm:
https://en.wikipedia.org/wiki/9%C3%9718mm_Makarov

This is the 9mm:
https://en.wikipedia.org/wiki/9%C3%9719mm_Parabellum


On a related matter: have I annoyed people so much that my guns and ammo discussions are actively ignored?

**Comment by Rivet-the-Zombie** [comment]
They're similar rounds, but they were developed independently and have some pretty sizeable differences in terms of performance. I'm inclined to keep them separate.

>On a related matter: have I annoyed people so much that my guns and ammo discussions are actively ignored?

Not on my part; I just don't always have anything to add. I hope I haven't come across as unappreciative of your work.

**Comment by BorkBorkGoesTheCode** [comment]
Okay. I started wondering if I was on an ignore list when people started commenting after I closed issues.

**Comment by illi-kun** [comment]
@BorkBorkGoesTheCode Please do not close your PR due to lack of instant replies. (1) It's not always possible to answer on question in the same time it was received, and (2), as Rivet correctly said,
> I just don't always have anything to add.

Even more: be sure you _will_ receive some comments if you do something definetely wrong.

**Comment by kevingranade** [comment]
For my part, I've just been really busy recently. I do appreciate your
changes.

**Comment by mugling** [comment]
> They're similar rounds, but they were developed independently and have some pretty sizeable differences in terms of performance. I'm inclined to keep them separate.

If there is evidence they differ I'll happily yield to that but we should update the item `description in that case`

> On a related matter: have I annoyed people so much that my guns and ammo discussions are actively ignored?

No I'm not aware of any such reason. It takes a little time to get used to github and I'm sure everyone is happy for you to take a little time to find your feet.

**Comment by Crispy6** [comment]
According to wikipedia, muzzle energy on [https://en.wikipedia.org/wiki/9x19mm_Parabellum](url) and [https://en.wikipedia.org/wiki/9%x18mm_Makarov](url) differ by nearly a factor of 2.

**Comment by mugling** [comment]
The consensus was no so this issue can be closed
