### ISSUE TITLE
Steel rail balance question

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#16868]
Is the steel rail supposed to have 0 recoil and dispersion?

**Comment by Shudokai** [comment]
I'm pretty sure it is since it's the "better" ammo for the rail rifle and takes ages to manufacture. The rail rifle has some recoil and dispersion to begin with and some people who tested the rail weapons said they are incredibly inaccurate even with high skills.

**Comment by Rivet-the-Zombie** [comment]
>Is the steel rail supposed to have 0 recoil and dispersion?

Yes - Shudokai's explanation is correct.
