### ISSUE TITLE
The traps skill is underused

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#16872]
When revising the description of Traps skill, I have noticed that, while the traps skill is referenced by several recipes, none of them require nonzero Traps skill.

**Comment by pisskop** [comment]
You read up traps.  And nailboards are you level 0 trap.

**Comment by baraba3** [comment]
almost every trap use trapping skill to produce.
blade trap is op.flick light in dark by trap and wait for zomibes to kil themself in hundreds.
low skill under 6 can result in wasting material and electric motors can be real bitch to find.
i would like more traps but blade trap is worth trapping skill alone as it s really powerfull.

**Comment by BorkBorkGoesTheCode** [comment]
My poorly worded post was referring to the fact that the Traps skill isn't really used to craft traps. Try debugging every skill except Traps to 10, then leave Traps at 0, then craft a trap.

**Comment by baraba3** [comment]
i debuggged skills and and i cant make any trap but nailobard trap even with books.
raising trapping skills activate traps.making traps improves skills at east in cases of blade trap i tried right now but i know that myslef i raised skills in trapping with nailboard traps and tripwire trap.

**Comment by BorkBorkGoesTheCode** [comment]
Well I was wrong. It appears the crafting recipes don't list the required Traps skill level.

**Comment by BorkBorkGoesTheCode** [comment]
Well I was wrong.
