### ISSUE TITLE
Manhacks not accepting damage (melee, ranged, firearms, vehicle ramming)

### ISSUE THREAD

**Issue by bpwatts** [CleverRaven/Cataclysm-DDA#16870]
Manhacks dont seem to be taking damage in the latest build. See below, RM228 shorty with 20x66mm buckshot loaded at close range does not appear to do any damage. Also, ramming with a vehicle or attempting melee (reach or hand-to-hand) doesn't appear to impart any damage. 

<img width="1074" alt="screen shot 2016-05-25 at 9 31 46 am" src="https://cloud.githubusercontent.com/assets/4484592/15544173/64d6dd66-225d-11e6-9141-a23254998096.png">

**Comment by bpwatts** [comment]
This happened with any manhack spawned on the surface. Didn't check below ground or other areas.

**Comment by BevapDin** [comment]
What did you change (the screenshot has "-dirty" in the version number)? Any mods in use? It works fine for me.

**Comment by Coolthulhu** [comment]
Was the manhack rammed by a car first? How was it created?

**Comment by bpwatts** [comment]
BevapDin - I have an error in item.cpp when I try to compile. I had to edit item.cpp and remove three lines for the latest experimental to compile. This error existed prior to the change -- I attempted a recompile and ran into the item.cpp error. 

std::map<std::string, const item::gun_mode> item::gun_all_modes() const
{
//    if( !is_gun() ) {
//        return {};
//    }

    std::map<std::string, const item::gun_mode> res;

    auto opts = gunmods();

Coolthulu: Created by Zombie Scientist. Ramming was attempted first (as I am a chicken and didn't want to chance getting killed).

**Comment by bpwatts** [comment]
BevapDin - Here is modlist:

[
    "boats",
    "no_religious_Texts",
    "deoxymod",
    "ew_pack",
    "Medieval_Stuff",
    "More_Survival_Tools",
    "Experimental-Z-Level",
    "blazemod",
    "Tanks",
    "more_locations",
    "Arcana",
    "No_Joke_Monsters",
    "survivorweaps"
]

**Comment by bpwatts** [comment]
This is on a 10.9.5 Mac, with this command line for building:

make NATIVE=osx OSX_MIN=10.7 RELEASE=1 LOCALIZE=0 CLANG=1 FRAMEWORK=1 TILES=1

**Comment by pisskop** [comment]
This has happened once for me on an older (still recent) experimental.  Reloading the game fixed it.

**Comment by bpwatts** [comment]
Reloading meaning just quit, ./cataclysm-tiles, load the same game? This doesn't fix it for me. I could attach the save file and see if it persists for you?

**Comment by codemime** [comment]
The fact that you had to comment out a couple of lines before you could be able to compile means that we have a more serious issue than bugged manhacks. Could you post here the error message you get when you try to compile the current build?

```c++
    if( !is_gun() ) {
        return {};  // I suppose this line is to blame
    }
    std::map<std::string, const item::gun_mode> res;
```
Rewriting it like this should prevent appearing the compile error:
```c++
    std::map<std::string, const item::gun_mode> res;
    if( !is_gun() ) {
        return res;
    }    
```

**Comment by bpwatts** [comment]
```
clang++  -DRELEASE -DMACOSX -DGIT_VERSION -DTILES -ffast-math -Os  -Wall -Wextra   -Werror -stdlib=libc++ -std=c++11 -MMD -mmacosx-version-min=10.7 -F/Library/Frameworks -I/Library/Frameworks/SDL2.framework/Headers -I/Library/Frameworks/SDL2_image.framework/Headers -I/Library/Frameworks/SDL2_ttf.framework/Headers -c src/item.cpp -o obj/tiles/item.o
src/item.cpp:4206:16: error: chosen constructor is explicit in copy-initialization
        return {};
               ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/map:838:14: note: constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
1 error generated.
make: *** [obj/tiles/item.o] Error 1
```

**Comment by codemime** [comment]
Thanks. Which version of `clang` you were using? Does the proposed solution fix the error?

**Comment by pisskop** [comment]
Aye, this is happening now in my game

http://imgur.com/vFHZDKM
^^ These 'lost souls' have 5 hp each, and Ive put a whole clip into just 2 of them. version 4882.


http://imgur.com/kH2HngB
^^ This is me quitting the game and going back.  This time it dies when I shoot it

**Comment by bpwatts** [comment]
planck:Cataclysm-DDA_tiles admin$ clang --version
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

**Comment by bpwatts** [comment]
Hooray! Thanks!
