### ISSUE TITLE
Vehicle initialization on mapgen doesn't respect (some?) faults

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16888]
For example, fuel pump fault prevents starting an engine, but doesn't prevent the engine from spawning started.

**Comment by mugling** [comment]
Good point. That needs addressing

**Comment by hexagonrecursion** [comment]
It appears that a very specific combination of conditions is required to trigger this bug:
* destroyEngine and has_no_key have to be false in order for the engine to spawn turned on
   https://github.com/CleverRaven/Cataclysm-DDA/blob/9d7ed7d6d918942cf1eedffb40477a3b3b33bf76/src/vehicle.cpp#L401-L405
* There is a 1 in 3 chance that faults will be added anyway
   https://github.com/CleverRaven/Cataclysm-DDA/blob/9d7ed7d6d918942cf1eedffb40477a3b3b33bf76/src/vehicle.cpp#L537-L541

This patch makes the issue reproducible:
https://github.com/hexagonrecursion/Cataclysm-DDA/commit/000e3049604fb328ef6d77197f9666e3a6c38976
