### ISSUE TITLE
Water zombies that spit water?

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#16909]
It is not a game changing suggestion, I just thought it would be kind of neat to get soaked by a water zombie puking its watery guts out. Which, in turn, would bring that mood changing "wet" variable into play more frequently. I imagine it similar to how an acid zombie works.

Possibly leaves a puddle of water on death/butchering?

It was just a silly idea that came to me.

**Comment by Shudokai** [comment]
Meh, would be more dangerous if that zombie spewed a stream of liquid in the attempt to drown you but in any case it comes to close to what other zombies do already and the "wet" mood is not to terrifying because its raining 24/7.

**Comment by Coolthulhu** [comment]
This would get weird with mutations that grant bonuses when you're wet.

**Comment by nanovad** [comment]
If this were implemented, it should probably be classified as a joke monster and placed in Crazy Cataclysm.

**Comment by mugling** [comment]
Limited appeal. OP could submit PR with idea if wanting proceed further
