### ISSUE TITLE
NPCs can't use non-"AUTO" burst fire modes

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16903]
Recent rework of firing modes has separated full auto and "partial auto" burst fire modes.
The code naively checks for "AUTO" mode, preventing using burst fire modes in guns that don't have full auto capability.

**Comment by BorkBorkGoesTheCode** [comment]
Quoting from @mugling 

>  AUTO  is used to handle the burst fire key and by NPC's. I'd like to deprecate the former and rework the latter so NPC's better understand their options. For now though that mode is probably best named  DOUBLE  as it's not automatic fire.

**Comment by BorkBorkGoesTheCode** [comment]
Quoting from @mugling 

>  AUTO  is used to handle the burst fire key and by NPC's. I'd like to deprecate the former and rework the latter so NPC's better understand their options.

**Comment by mugling** [comment]
Yes, I'd like to rework NPC's to correctly use all gun modes (including auxiliary mods)

**Comment by kevingranade** [comment]
Btw, "DOUBLE" shouldn't be a firing mode at all right now, as it fires two
rounds simultaneously, not in sequence, which we simply don't support right
now.

**Comment by mugling** [comment]
Would there be any difference apart from how recoil is calculated? It wouldn't be hard to extend the implementation to support it if so.

**Comment by kevingranade** [comment]
How recoil is calculated (don't apply recoil for the first to the second,
but apply both afterwards) and how it's drawn (one projectile instead of
two).

**Comment by mugling** [comment]
The first part of that is trivial, the latter probably is to someone who understands the SDL layer. I'm going extend the fire mode support to include optional flags that modify behavior with the first being `SIMULTANEOUS`. The alternative is magic names for modes eg. `DOUBLE` but that seems overall more brittle

**Comment by mugling** [comment]
Fixed by #16951
