### ISSUE TITLE
"Start vehicle construction" fails to create vehicle in z-level mode

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16918]
The frame is consumed, but the vehicle isn't spawned.

**Comment by BorkBorkGoesTheCode** [comment]
Which versions are affected?

**Comment by Rivet-the-Zombie** [comment]
It's also happening with Z-levels disabled.

**Comment by mugling** [comment]
Can reproduce

**Comment by Karlieb** [comment]
I can start a vehicle with: "folding_frame",  "folding_wooden_frame", "xlframe_vertical_2", "frame_wood_light_vertical_2" only (they have "INITIAL_PART" flag).

Adding "INITIAL_PART" to any of the other frames doesn't seem to work.
