### ISSUE TITLE
Zombie deaths are bugged

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#16913]
0.C-14583-g642d7f8

When a reach attack is performed against an adjacent target, the game crashes.

**Comment by BorkBorkGoesTheCode** [comment]
The game also crashes on the second reach attack.

**Comment by BorkBorkGoesTheCode** [comment]
It now appears that melee attacks against zombies cause a crash. This is in windows

**Comment by Fallingferret** [comment]
I've just made an account to say that it seems to appear with #16463 (4937). Sadly I wouldn't know where/how to get to the bottom of with, but if anyone just wants to play, 4936 is the last stable build.

**Comment by BorkBorkGoesTheCode** [comment]
It has been fixed
