### ISSUE TITLE
Ranged and throwing dispersion use a very poor approximation of tangent

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#16925]
Windows 10
Tiles
Version 0.C-14379-ga3bc3ca

Approximating tangent by multiplying angle by 0.745 is a very poor approximation. Multiplying by 1.0 would be a better approximation, which is very commonly used for small angles. As the angle gets larger the actual tangent will get higher and higher above the angle, so my vote is to use the actual tangent. On a miss, the same function calls `cos`, `sin`, and `atan2`, so it makes little sense to use an approximation for performance reasons.

in Creature::projectile_attack in ranged.cpp:
```
    // shot_dispersion is in MOA - 1/60 of a degree
    constexpr double moa = M_PI / 180 / 60;
    // We're approximating the tangent. Multiplying angle*range by ~0.745 does that (kinda).
    constexpr double to_tangent = 0.745;

    double range = rl_dist( source, target_arg );
    double missed_by = shot_dispersion * moa * to_tangent * range;
```

very closely related, the code for throwing seems to be applying this approximation twice, since the result gets sent to `projectile_attack`.

In player::throw_item in ranged.cpp:

```
    // Rescaling to use the same units as projectile_attack
    const double shot_dispersion = deviation * (.01 / 0.00021666666666666666);
```
```
    auto dealt_attack = projectile_attack( proj, target, shot_dispersion );
```

0.745 ⋅ π ∕ 180 ∕ 60 ≈ 0.0002167117, so my best guess is that this used to be a questionable approximation for the tangent of an angle in MOA that somebody rounded to 0.0002167 and then somebody else assumed that 0.0002167 was supposed to be 0.0021 ̅6. To explain the .01, I've got nothing. This should be changed to just a conversion from quarter degrees to MOA by multiplying by 15.
```
    constexpr double quarter_degrees_to_moa = 15;
    const double shot_dispersion = deviation * quarter_degrees_to_moa;
```

**Comment by mugling** [comment]
Fixed in #17656
