### ISSUE TITLE
What is the Base Barrel Length of the 8x40mm?

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#16926]
I have looked through GAME_BALANCE.md, but I haven't found the base barrel length for the 8x40mm.

**Comment by Crispy6** [comment]
I don’t see how to get you anything authoritative for a fictional weapon firing caseless ammunition, but the 8x40mm assault rifle has the same volume of 7 as a H&K 416A5 and it has a 5 ranged damage bonus to the H&K 416A5’s -2 damage, so I would guess that the base barrel length is less than the 20″ for .223 Remington. The 8x40mm pistol and smg have no damage penalty, so the base barrel length may be a lot less.

My fairly arbitrary vote is that the base barrel length be 8 3 ∕ 8″ to match the gun from Dirty Harry.

**Comment by Rivet-the-Zombie** [comment]
I never gave them barrel length stats because I figured that they're made in such a way that you can't just saw a piece off the barrel and have it still work right.

**Comment by BorkBorkGoesTheCode** [comment]
Thank you for telling me @Rivet-the-Zombie . I have started a PR to migrate the last Rivtech gun into 8x40mm.json
