### ISSUE TITLE
Add "undressing" prompt before sleeping.

### ISSUE THREAD

**Issue by Dalenacio** [CleverRaven/Cataclysm-DDA#16922]
One of the things that's bothered me for a long time is how my character can sleep wearing chain mail armor, a massive backpack, and several holsters, dump pouches, or slung rifles on his person, and wake up like he'd just had a nice normal restful sleep. I couldn't do that. Most people couldn't do that. Most people would toss and turn trying to find a single position that's not hell to sleep in, and probably loose most of their night to that. Well, actually, most people would just get undressed for the night and sleep that way.

My suggestion is very simple, easy to implement, and completely unobtrusive. When you go to sleep, add a simple Y/N prompt to "undress" and, if you do so, sleep as you normally would in the game's current state. If you don't, you might get some penalties to chance of falling asleep, or less fatigue recovered upon waking up. The entire process would be entirely automatic (You wouldn't actually have to remove or put back on your armor yourself), and would take essentially a single prompt's time from the player to complete.

What this brings to the table is reinforcing the necessity of making sure the coast is clear before trying to go to sleep. Right now, if a zombie were to burst in on you while you slept, it's an annoyance, really. You kill it without problem, as you popped out of bed fully armed and armored and ready for a fight. with this change though, a zombie surprising you while you sleep could be absolutely catastrophic, unless you chose to eat the fatigue penalty and went to sleep armored in case of a fight.

---

Of course, it's not _quite_ that simple, and it'd be necessary to go a bit more in depth to make this system work, but ultimately, it remains quite simple. 

 For one, it'd rarely make sense to _completely_ undress before going to sleep. If you've got a sweater and undershirt under all that armor, you might want to keep them on if it's cold, so as to not freeze to death. Maybe some very light armor could stay as well, just in case. Also, full plate armor should be more uncomfortable to sleep in than, say, a simple Kevlar vest.

My proposal this system would be for it to calculate the penalty based on overall body encumbrance, with more encumbrance resulting in a heavier penalty, and below a certain threshold being considered "negligible".

Furthermore, on the Armor Layering tab ("+" by default), you could define certain pieces of gear as "sleeping gear", which you would keep on yourself after undressing for the night.

This could be further mitigated or reinforced by positive and negative traits. A "Sensitive Sleeper" trait might harsher penalties to fatigue recovered from sleeping encumbered, and a "Comfortable Sleeper", whose sleep would be impeded very little by encumbrance.

While this may seem like a minor addition, it would do much for the game in the long run. For one, it'd make sleeping an actually risky activity (which, really, it should be) by adding the risk of being caught with your pants down and your hands empty. Of course, you could keep your gear to be ready for a bad surprise, but it'd add value to seeking a safe place to sleep, and consequences to failing to do so properly.

And, non-negligibly, it would add a lot to flavor to know your character isn't _actually_ sleeping in his full metal plate armor all the time.

Any suggestions and criticism are welcome!

**Comment by Coolthulhu** [comment]
Sounds intrusive and non-trivial to implement. At the same time it wouldn't actually do much to make sleeping more dangerous, since it is easy to find a safe spot and taking a hit from a zombie (even to naked body) is no big deal.

It would make being waken up by a zombie a major annoyance, as it would mix up the worn items, scramble automatic inventory letters and force the player to manually separate items dropped to sleep and items that were there before undressing to sleep.

**Comment by BorkBorkGoesTheCode** [comment]
Couldn't sleep difficulty be governed by encumbrance?

**Comment by BorkBorkGoesTheCode** [comment]
sorry, tl;dr.

**Comment by illi-kun** [comment]
For me, it's quite annoying micromanagment for tiny benefit.

**Comment by Rivet-the-Zombie** [comment]
I like the basic concept, but agree that there's no apparent good way to go about implementing it without adding a great deal of micromanagement.

**Comment by Podesta** [comment]
Yeah, the idea does seem really cool, but I also don't think it would be beneficial with how the inventory is implemented in cata. It would work better if the game tracked where each object is stored, so you could remove and pickup the backpack with all its items. But even that would add some annoying micromanagement, taking into account the amount of pockets/places you can store items.

**Comment by kevingranade** [comment]
Dressing down to skivvies would be fairly simple without layering on all
the optional micromanagement, and bundling items into e.g. a "pile" item
that preserves that state you want to recover should be straightforward.

As for "zombies aren't dangerous to a naked survivor", that's an obvious
bug in the monster definitions or combat code.

**Comment by Coolthulhu** [comment]
> As for "zombies aren't dangerous to a naked survivor", that's an obvious bug in the monster definitions or combat code.

Less of a bug and more a result of balancing.
There is no penalty on waking up, the survivors actually sleep standing.

The worst that could happen would be taking a few square hits and getting bitten in 1-2 body parts. Neither of those is particularly dangerous when cotton balls pulled out of a pillow cure hp damage and abundant disinfectant gets rid of infection (and also hp damage).
Then there's the pain, which has linear scaling, meaning it starts harmless, skips dangerous and almost instantly gets into very dangerous. Few regular zombie hits will stay in the "harmless" zone.

**Comment by i2amroy** [comment]
>and bundling items into e.g. a "pile" item
that preserves that state you want to recover should be straightforward.

I think this misses a key fact, though, which is that if I'm ambushed by a zombie in my skivvies I might not necessarily want to grab all of the things I dropped at once. If I want to, say, grab my helmet to prevent my glass jaw extremely fragile head, then there's no easy way for me to grab just the helmet out of the pile; it's everything or nothing (or lots of extra implementation).

I'd like to echo the others in here, it definitely seems like a cool idea, but I don't see any real good ways of implementation.
