### ISSUE TITLE
Astyle bug?

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#16928]

**Comment by BorkBorkGoesTheCode** [comment]
I have received an astyle error during my latest PR.

**Comment by Crispy6** [comment]
astyle is Artistic Style, and it’s basically a pretty printer. Somebody got two lines with the & aligned wrong on references past it somehow.

Fix the two lines in https://github.com/CleverRaven/Cataclysm-DDA/pull/16923/commits/6d3070b4c8c60e9cb92a400a819798fdb6d1c156 to get anything to compile.

**Comment by BorkBorkGoesTheCode** [comment]
Thank you.

**Comment by BorkBorkGoesTheCode** [comment]
The ghost was Crispy6, who made a fix.
