### ISSUE TITLE
Body-temperature seemingly broken at lower temperatures, wind speed does not affect body temperature

### ISSUE THREAD

**Issue by Voskhod-1** [CleverRaven/Cataclysm-DDA#16924]
After mucking about with the weather-reader CBM and a diver's watch (while entirely naked) I discovered a few anomalies: First off is that if temperatures (whether absolute or "feels like") dip below 32F, frostbite/frostnip does not always occur and body-temperature does not go below "Chilly" levels.

![tempbug](https://cloud.githubusercontent.com/assets/13146406/15630643/b3313860-24f8-11e6-8c95-9571baf92645.png)

Notice that absolute temperature is 31F and "Feels like" temperature is -25F because of 29mph wind speeds. Despite all of this (while, again, entirely naked) the character feels nothing more than "Chilly". No possible source of warmth is nearby, the character has no mutations at all (besides Debug Vision), and the only CBMs installed are the Weather Reader and Joint Torsion Ratchet.

Thus, body temperature is broken at lower temperatures, it would seem.

Furthermore is that frostbite, simply put, never happens. After standing naked in far-below-freezing temperatures ("Feels like" -61F) for an entire night's time, my character's outer-most extremities achieved only frostnip, but not frostbite, despite constant reassurance that "Your left X will be frostbitten within the hour!!" in the log menu.

![tempbug2](https://cloud.githubusercontent.com/assets/13146406/15630688/2a3158a4-24fa-11e6-9189-a9a701f0ccf8.png)

Cold temperatures are supposed to be dangerous, especially during Winter time. Yet it seems that cold-temperature acts as nothing more than a nuisance. Frostbite is impossible, the character's body temperature is seemingly 50 degrees Fahrenheit higher than it should be at all times (even in total absence of clothing), and there is no hypothermia to speak of in the game. This, in my opinion, goes entirely against the spirit of Cataclysm.

**Comment by Soadreqm** [comment]
Interesting. Spending the night naked in the cold outside really isn't a common test case, and I agree it should be very dangerous. I'd note that you've lost half your hitpoints, your speed's cut to a quarter, and your effective DEX and INT are both zero, so "nuisance" is maybe putting it a bit mildly. And I think "frostbite" is just when you take damage from the cold.

**Comment by kevingranade** [comment]
Please outline the exact expected results, "it's broken" isn't something we
can fix unless the desired behavior is obvious, which it isn't here.

**Comment by evilexecutive** [comment]
> Intelligence and Dexterity at 0
You know, I honestly think that the game should just outright kill you if any of your stats ever drop to 0. Same deal with D&D/Pathfinder. Intelligence/Wisdom/Charisma getting damaged down to 0 means you get to suffer brain-death. Or if your constitution/strength/dexterity is damaged to 0, your whole body just stops working, you suffer a heart attack and die. This is also a staple of other roguelikes, where in Nethack you also die if any of your stats reaches 0.
