### ISSUE TITLE
Vehicle Suggestion - Protrusion Mounting points and Deployable protrusions

### ISSUE THREAD

**Issue by Hague** [CleverRaven/Cataclysm-DDA#16938]
Currently protrusions simply mount to an orthogonal frame of a vehicle. If an interim component, a hard or firm point were required on frames, varieties of hard points that control how a protrusion behaves can be added:

- Quick-release protrusions. Rams, blades, scoops, etc. can be mounted to a mechanism that can allow them to be easily removed or replaced without tools (maybe some strength or a wrench if strength is low) These can be manual or automatic. Containers that are dropped via quick release drop their contents in the tile where the protrusion was. 

- Stowable / Retractable Protrusions. Since these protrusions would be attached to mounted points on a nearby frame, this would allow the protrusions state to be stored in a storage mount and deployed via controls. Retractable blades, internally stored turrets and deployable gunner seat, etc. Larger deployables would occupy the primary space (seat, box, quarterpanel, et al.) deployable quarterpanel for turret mounts, deployable seats and aisles (the deployable ramp in a commercial tractor-trailer) These would need a deployed and stowed state and tile so a sliding gunner seat would leave a space for an actor to stand upon. It would also need to handle ramming and collisions when attempting to deploy into an occupied space (or more simply a prompt that the space is blocked and a return) Stowed containers would be inaccessible while stowed and not included for fuel, batteries, ammo, etc until deployed (not strict if it can be balanced otherwise) 

EDIT: Deployable mounts could be given strength values based on the mount point. For instance, a powerful hydraulic or pneumatic ram mount that can improve the performance of weaponized protrusions.

**Comment by Coolthulhu** [comment]
Sounds hard to implement.
What would be the benefits?

The only actual use I see would be deploying blades, since those actually depend on collisions to work, but are useless and fragile when not used to ram things.

**Comment by Hague** [comment]
There are others: Quickly detachable and reattachable boxes so you can drop off loads at a campsite or base quicker. Generally speaking it would give the resident shop modders a lot more room to work for deployable weapon turrets.

There's also verisimilitude. Travel Trailers and campers have deployable sections for living quarters, kitchens, etc. Tractor trailers have deployable ramps.

**Comment by mugling** [comment]
Closed as limited appeal and has little chance of implementation given the degree of difficulty and relative priority compared to other aspects of the vehicle code
