### ISSUE TITLE
nauseous should be nauseated

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#16942]
Now and again I see the message "You feel nauseous."

If I am not mistaken, to be nauseous means to cause nausea. I believe "You feel nauseated" is more correct.

As an example, I believe both nauseate and nauseous are used correctly in the Mr. Grinch song...

https://youtu.be/ZgP0aUKlmNw?t=142

**Comment by Podesta** [comment]
A quick google search seem to agree with you. Either "You feel nausea" or "You feel nauseated" would be correct. "You feel nausea".

> Hi Grammar Girl. This is Brian from Seattle, and I have a question about the word nauseous. I always thought that nauseous meant that you were causing nausea, and that when someone says, "I'm feeling nauseous," they are causing me to throw up on them. But everyone says it! Everyone says, "I'm feeling nauseous." And I always thought it was wrong, but movie stars say it and books say it, and maybe I've been wrong this entire time. I thought if I'm feeling sick, I'm nauseated. And that big pile of trash on the floor is nauseous, meaning it's causing me to throw up. Anyway, I think you understand my question, I'd appreciate an answer. Thanks. Bye.
> 
> Brian is right! And this is a good reminder that I should get a flu shot, too, so thanks. It's common to hear people say they're nauseous when their stomach is upset, but language sticklers hold that nauseous means to induce nausea, whereas nauseated means you feel sick. So when you're describing how sick you feel, you should say you are nauseated; when you're describing something that makes you sick, you should call it nauseous. At least that's how you should do it if you want to be extremely proper. Most usage guides note that the improper use is far more common than the proper use (5, 6), which is always a bad sign for a rule. And the Merriam-Webster Dictionary of English Usage even goes so far as to say there is no basis for the rule (7). So it's likely that the confusion will continue for a while and eventually nobody will object when you say you feel nauseous when you're sick. Whether that will happen in 20 years or 200 years, I don't know.

http://www.quickanddirtytips.com/education/grammar/a-few-short-questions

https://www.vocabulary.com/articles/chooseyourwords/nauseated-nauseous/

**Comment by Crispy6** [comment]
There doesn't seem to be enough evidence that “You feel nauseous" is actually incorrect. A google search for "feel nauseous" returns roughly three times as many results as "feel nauseated", too.

That said, it may as well be changed, since I don't see that many people would object to “You feel nauseated.”

**Comment by i2amroy** [comment]
Eh, this is an excellent case where (as noted in the quote above) the so-called "improper" use far outweighs the so-called "proper" one (which is usually a sign that the actual living language itself has adapted and the "rules" just haven't caught up with the way people actually speak yet).

I mean it's not something I feel needs to be taken to hell-or-high-water, but I feel like the proper thing to do in this case is to simply stick with the one that is more common.

**Comment by ifreund** [comment]
@i2amroy agreed, same thing happened with sneaked and snuck.

**Comment by mugling** [comment]
Consensus appears to be for status quo. OP could submit PR if they wish to further pursue
