### ISSUE TITLE
Add a 'soup stock' item?

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#16947]
A meaty product that is too trash to be used as a chunk of meat, but not trash enough to throw away.
  Parts like the spare organs, the less savory muscles, stray cartiledge, the dingle dongers, etc.

It would be used in, well, soups and other products that recycle food.

**Comment by ifreund** [comment]
So pretty much another form of broth? we already have broth (that is made from veggies), bone broth (made from bones lol), and of course human broth.  I'm not sure if we need another broth with very similar uses.  In fact I think the uses of the proposed "soup stock" item would be identical to those of bone broth.  Maybe just add the bits of meat you talked about, probably represented in the game by the raw offal item, to the bone broth recipe and rename the product?

**Comment by Hague** [comment]
He's basically suggesting [chitlins](https://en.wikipedia.org/wiki/Chitterlings), or "gut soup." Add that to the ingredient list for meat soup replacing the broth component.

**Comment by Headjack** [comment]
How about we just let offal be used for some similar purpose?

**Comment by Hague** [comment]
I mean, it's boiled guts. Currently you can't eat offal without a really good chance to get brain parasites. There is no boiled offal recipe. It should taste worse for non-gourmands so it oughta be separate from regular broth as broth is non-meat and gut soup would clearly be a meat product and unpalatable to vegetarians. That said, looking it over, there's room for a meat stock or meat broth. Spices, a chunk of meat or canned chicken, and water would be all it would take. I stand firm that foods crafted from byproducts like stomach and offal should be less satisfying than meat.

On a side note: Predatory threshold mutations should get a big morale boost when they feast on fresh raw offal and meat. You gotta imagine a proto man-lion gets a lot of satisfaction from the gory warmth of a fresh kill.

**Comment by pisskop** [comment]
Why should meat soup be the only meaty soup?
  i had no intentions of suggesting it be equal to standard meat chunks.


you can cook offal these days.



Allowing more filler meat to drop as butcher product allows for more variety in cooking methods and diet, allows for less nutrients to encourage omnivores to do more than bait wolves and cougars to your car door so you can sling them to death, and goes further towards representing the anatomy of a critter/Role playing value of hunting

**Comment by ifreund** [comment]
Obviously some parts of the offal taste much better than others. I assume that choice parts such as the liver and heart would be used.  With this in mind, the resulting broth would actually be quite rich and nutritious, maybe good enough to be considered meat soup.

**Comment by pisskop** [comment]
offal isnt spare organs.  2 seperate items

**Comment by illi-kun** [comment]
We have a lot of food right now, so I see no strong need of that. Anyway, if someone want to implement it - feel free to give it a try.
