### ISSUE TITLE
Dying critters explode with gore

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16952]
Before the recent change to splatters, zombies would only explode in gore when overkilled. Now it's all Brutal Doom mode, with naked punches ripping chunks of guts from dying critters.

**Comment by Rivet-the-Zombie** [comment]
Rip and tear?

**Comment by Coolthulhu** [comment]
You're MS_HUGE. That means you have ~5.333 offal. Rip and tear, rip and tear your offal.
