### ISSUE TITLE
Royal Beef has 833% iron and 416% B12 content

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#16968]
Is this supposed to be?

**Comment by Shudokai** [comment]
Royal Beef is made using Royal Jelly and royal jelly is supposed to be some sort of super food which can cure almost if not any sickness and is also really really really nutritous, so I'd say yes, It's supposed to be like that.

**Comment by John-Candlebury** [comment]
Royal Jelly has no vitamins when eaten on its own, so royal beef probably shouldn't have such numbers.

It's most definetively a bug.

**Comment by Crispy6** [comment]
I'd say the bug is the other way around, that royal jelly should have the vitamin difference added rather than subtracting them from royal beef.

**Comment by BorkBorkGoesTheCode** [comment]
Will it cause iron poisoning? irl this level of iron consumption may cause poisoning.

**Comment by Crispy6** [comment]
Food can never cause any sort of hypervitaminosis.
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/consumption.cpp#L616

**Comment by BorkBorkGoesTheCode** [comment]
What happened to Crispy6?

**Comment by BorkBorkGoesTheCode** [comment]
Where did Crispy6 go?
