### ISSUE TITLE
Marloss Berry generates bushes that give more berries

### ISSUE THREAD

**Issue by DavidEdwards** [CleverRaven/Cataclysm-DDA#16974]
I read the [wiki entry for the Marloss Berry](http://www.wiki.cataclysmdda.com/index.php?title=Guide:_Marloss_Berry).

It clearly states that:

> spawns netherworld Marloss plants (which will not include berries), fungus, and slime patches around the consumer. A few friendly Blobs may show up as well.

However sometimes, if I am lucky, eating a berry will create a bush that gives more berries.

**Comment by Hague** [comment]
Well, it does warn you that it's out-of-date (as are many of the things on the wiki)

**Comment by DavidEdwards** [comment]
That's fine (I like the berries!). So this isn't a bug?

**Comment by i2amroy** [comment]
Yeah, this is a case where the wiki entry is very badly outdated. Nowdays the marloss berry is aligned with the fungal faction (not the blob one) and essentially spreads the fungus around you (which, if the area includes some bushes and you are fairly lucky, can result in more marloss berry bushes spawning).

**Comment by DavidEdwards** [comment]
Ok! I'll close this then.
