### ISSUE TITLE
error when opening jars

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#16979]
Using [   ]	cataclysmdda-0.C-4964.zip	2016-05-31 05:14	50M	 
![image](https://cloud.githubusercontent.com/assets/12039454/15692431/2bfa983a-2743-11e6-9819-6fd45a02bbcb.png)

happens when opening these items:
sealed jar of V8
sealed jar of canned fruit
sealed jar of broth
sealed jar of bone broth
sealed jar of human broth
sealed jar of sauerkraut
sealed jar of fish soup
sealed jar of sap soup
sealed jar of meat soup
sealed jar of mushroom soup
sealed jar of vegetable soup
sealed jar of woods soup
sealed jar of canned tomato

does NOT happen with these items:
sealed jar of canned fish
sealed jar of pickled fish
sealed jar of soylent slices
sealed jar of pickled human flesh
sealed jar of canned meat
sealed jar of pickled meat
sealed jar of canned veggy
sealed jar of pickled veggy

**Comment by Xpyder** [comment]
NOTE: #16973 is for a different issue, it's on hold until this one gets fixed

**Comment by ifreund** [comment]
Duplicates #16322?

**Comment by Xpyder** [comment]
@ifreund 

> Duplicates #16322

Thanks
