### ISSUE TITLE
Can't repair vehicles with welder

### ISSUE THREAD

**Issue by asciitaveller** [CleverRaven/Cataclysm-DDA#16976]
With the latest version (a013b04), it's not possible to repair vehicles using a charged welder item. Duct tape seems to be working.

![bug_b](https://cloud.githubusercontent.com/assets/19675251/15690835/be48b806-2785-11e6-8d43-9fc578a849ef.png)
![bug_a](https://cloud.githubusercontent.com/assets/19675251/15690836/be4da10e-2785-11e6-97bf-4b34532df15b.png)

**Comment by mischief** [comment]
in my recent experience with fixing an apc, a makeshift welder did work but a regular welder did not.

**Comment by Coolthulhu** [comment]
Does the welder have a "seeing this is a bug" in its description?

If so, it's caused by the same bug as #16751

**Comment by asciitaveller** [comment]
Yes, "seeing this is a bug".
Sorry for the duplicate.
