### ISSUE TITLE
Suggestion: Makes rubber hose craftable

### ISSUE THREAD

**Issue by RenegadeElement** [CleverRaven/Cataclysm-DDA#16998]
rubber hose or plastic hose. According to the item browser they are uncraftable and last I checked important for early game gas transposition. It should be called plastic hose.

**Comment by Coolthulhu** [comment]
They most likely won't become craftable unless someone links a good DIY guide on how to make a rubber/plastic hose from homemade materials.

**Comment by RenegadeElement** [comment]
heat and mold the plastic around something straight or glue a plastic sheets edges together, it is simple plastic welding. 
https://www.youtube.com/watch?v=AeVhNHa4kSg

good video on melting milk cartons and the like.
https://www.youtube.com/watch?v=rpXq6mnbCus.

step 1 melt plastic. step 2 mold into shape around form. step 3 let cool.
The only restriction is that you need to control the heat well to not burn the plastic so no fire based melt.

**Comment by Headjack** [comment]
That gives you a tube, but is it flexible enough to serve as a slingshot, etc? I think that the hose in question is [like this](https://www.fishersci.com/shop/products/fisherbrand-tygon-s3-e-3603-flexible-tubings-i-d-1-4-in-o-d-3-8-in-wall-thickness-1-16-in/14171104) sort of thing, which is probably findable in refrigerators. Maybe what you want is another way to siphon gas with some sort of makeshift straw?

**Comment by RenegadeElement** [comment]
Mainly just a siphon

**Comment by illi-kun** [comment]
Refrigerators are fairly common, so I see no issue with extraction of hoses from them and see no reason to implement something just to make siphoning even easier.

**Comment by mugling** [comment]
Consensus being no
