### ISSUE TITLE
Can't construct vehicle from scratch.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#16996]
0.C-14770-g135a344

Using the construction menu to create a vehicle fails to place the initial frame. Everything works normally up to the point after you enter the new vehicle's name, at which point nothing else happens. No vehicle is generated, no time passes, but the frame is consumed nonetheless.

**Comment by BorkBorkGoesTheCode** [comment]
Coolthulhu mention this in #16918

**Comment by Rivet-the-Zombie** [comment]
Right on. I must've missed that one.
