### ISSUE TITLE
Loading sinew into a bone needle produces thread when unloaded

### ISSUE THREAD

**Issue by tung** [CleverRaven/Cataclysm-DDA#1700]
Playing on Linux compiled from source (tag 0.6 / commit cf80a547ce8eb4b4e8b7d08ab3d29d8af138c379)

1. Get a bone needle and some sinew.
2. Reload the bone needle with the sinew.
3. Unload the bone needle.

I'd expect to see the sinew in the inventory once more, but instead I get thread.

**Comment by Treah** [comment]
This is fixed in the current experimental version 0.C-8474-g8401eeb

**Comment by Night-Pryanik** [comment]
Should be closed?
