### ISSUE TITLE
standardize numbers for terminal ballistics modifier in ammunition

### ISSUE THREAD

**Issue by moosestrangler** [CleverRaven/Cataclysm-DDA#17018]
The numbers used to account for terminal ballistics in firearm ammunition need standardizing. Right now half of them don't make any sense or are undocumented in GAME_BALANCE.md. Proposal:

JHP bullets give +3 damage, +5 dispersion
JSP bullets give +2 damage
no modifiers for FMJ
hardened AP bullets give -5 damage, +5 armor penetration
The effects of API rounds depend on exactly how they behave.

**Comment by BorkBorkGoesTheCode** [comment]
I have documented many of the modifiers in #17002 , would you like to take a look?

**Comment by moosestrangler** [comment]
I saw it. Several of the modifiers currently in use are unjustified. None of them adhere to a precise ruleset.

**Comment by BorkBorkGoesTheCode** [comment]
Are you going to distinguish between Jacketed Soft Point and Soft Point bullets.

**Comment by Leland** [comment]
Note that the documentation for weapon balance now lives here: https://github.com/CleverRaven/Cataclysm-DDA/wiki/Weapons-Balance

**Comment by BorkBorkGoesTheCode** [comment]
I've been using an arbitrary +1 or +2 damage for expanding ammunition as a standard for a while. The game badly needs to have situational multipliers.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
