### ISSUE TITLE
"Your none malfunctions"

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17022]
Pretty sure it wasn't caused by #17019 but I discovered it while testing it.

* Mount vehicle turret with low reliability - I used a water cannon
* Set bad weather conditions
* Shoot something
* After a while your none will malfunction

Caused by `handle_gun_damage` not having a gun argument but using `player.weapon` instead.

**Comment by mugling** [comment]
Earlier closure was accidental
