### ISSUE TITLE
[BUG] Being near a fungal spire sometimes causes an error relating to add_zombie to appear

### ISSUE THREAD

**Issue by hurston1** [CleverRaven/Cataclysm-DDA#17031]
Windows, 0.C-14896-g74b98a3 (tiles)

The message that appears every so often near a fungal spire or other heavily fungaled areas is :

DEBUG: add_zombie: there's already a monster at 61,61,0

FUNCTION: bool Creature_tracker::add(monster&)
FILE: src/creature_tracker.cpp
LINE: 68

**Comment by nanovad** [comment]
I've noticed this error when spawning large amounts of zombies in test scenarios, as well. It seems to occur when zombies are crowded.
