### ISSUE TITLE
Excessive wetness penalties

### ISSUE THREAD

**Issue by Soadreqm** [CleverRaven/Cataclysm-DDA#17033]
Right now, I'm getting -68 morale from ordinary rain. It is summer, and the temperature's a balmy +20C. It seems that the morale penalty has increased quite sharply since I last noticed it, as I can't remember getting more than -30 from weather before.

I don't think being wet should cause this much angst.

Also, I don't think the current combination of heat and wetness morale penalties really make sense. Getting soaked in real life can be unpleasant because you get cold, fast, but that doesn't happen In Cata. You can be both uncomfortably wet and uncomfortably hot. I think wetness shouldn't cause any morale drop on its own, and should instead reduce the warmth bonus of your clothes.

**Comment by Coolthulhu** [comment]
> I think wetness shouldn't cause any morale drop on its own, and should instead reduce the warmth bonus of your clothes.

Wet rags sticking to body, water sloshing around in the shoes and all similar experience is enough to be worth its own morale penalty.

> I don't think being wet should cause this much angst.

It doesn't usually get that high unless you're totally drenched and have your entire body covered.

> Getting soaked in real life can be unpleasant because you get cold, fast, but that doesn't happen In Cata.

That could work. Currently cold penalties are rather mild, even in winter.

**Comment by Leland** [comment]
Discussion never really took off on this one and we're approaching the year mark. Closing – if there's still interest by anyone feel free to either let me know you want it reopened or create a new issue.
