### ISSUE TITLE
[Bug] Applying a UPS conversion mod to an item produces a 'none' object in the inventory

### ISSUE THREAD

**Issue by hurston1** [CleverRaven/Cataclysm-DDA#17030]
Windows version 0.C-14896-g74b98a3 (tiles)
Applying a UPS conversion mod to an item (e.g. electric forge) produces a 'none' item in the inventory

**Comment by Coolthulhu** [comment]
Likely caused by #16751, which produces nulls in tools.

**Comment by Coolthulhu** [comment]
Since tools no longer contain `null`s, I assume this has been fixed.
