### ISSUE TITLE
Picking up a a bucket of water from the ground retains the water in the bucket AND spills it on the ground.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#17041]
As title, it's not abusable because water on the ground is unuseable, but it would be for e.g. gasoline for a trap.

**Comment by BFG1992** [comment]
Same shit is happening to yoghurts, except yoghurt caps will NOT retain the yoghurt and came empty in the inventory. That's when using the advanced inventory. If just grab it by "g" or by examining, the choice is given: either spill the yoghurt and have a cup or wield it (and get rid of what you're currently holding in hands). In the latter case, the yoghurt can be safely put in the inventory and/or consumed. Quite an irritating bug, 'cause I often forget about it and waste any yoghurt I find.
I have set to drop only watertight containers in the options, so maybe that setting have something to do with this bug, I'm not sure.
