### ISSUE TITLE
Lab challenge runtime

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#17043]
i'm getting crashes every time I play a lab challenge on the latest experimental. World is created fine, character spawns in, but exploring too much will crash the game. Happening on both tiles and curses. Seems to be fairly recent, happens on 4987, but haven't had it occur on 4964.

Steps:
1. Get latest experimental build from cdda website
2. Create default world, create random/blank lab challenge character
3. Move around some, maybe dive down some stairs, maybe turn a flashlight on
4. Runtime assertion

Error is
File: src/line.cpp, Line 321
Expression: !line.empty() && line.front() != line.back()

**Comment by Coolthulhu** [comment]
The most likely cause is #16991, though I don't see anything wrong with it and it worked during testing.

Are you playing with z-levels on? May be something 3D related.

**Comment by codemime** [comment]
> The most likely cause is #16991

Indeed. But it affects only aiming/shooting (was not mentioned). The saved game would be helpful.

**Comment by Fallingferret** [comment]
I get the same error, but with a nearby military outpost: https://www.dropbox.com/s/gt13buuc669bvhl/Granite%20Hills.7z?dl=0

I included the non-vanilla mods I use, just flip the ATV around and head to the military outpost/refugee center combo for a 100% crash.

**Comment by ifreund** [comment]
just got the same error:
```
Assertion failed: (!line.empty() && line.front() != line.back()), function slope_of, file src/line.cpp, line 321.
Abort trap: 6
````
but for me it happened after going to sleep on the -1 floor of a lab.  This was on a world I've had for a month or so irl.

**Comment by codemime** [comment]
@Fallingferret  There was a turret on the military outpost that tried to shoot itself. Turrets are probably not supposed to commit suicide.

**Comment by Coolthulhu** [comment]
Could be caused by the turret shooting something above/below it but covered by floor/roof, which would cut off its trajectory, possibly down to 1 point (the starting point). Then the assertion `line.front() != line.back()` would be false.

**Comment by codemime** [comment]
@Coolthulhu No, that was before cutting off the `trajectory`. I added a condition ` if( source == target_arg )` to `Creature::projectile_attack()` and it returned `true`. Besides, there's no cutting off `trajectroy` anymore, only decrementing `traj_len`.

**Comment by codemime** [comment]
Right now I can PR a quickfix that would prevent crashing due to violated assertion and issue a `debugmsg()` instead (or bail out silently). But I suppose the actual issue is somewhere in the monster code.

```c++
if( source == target_arg ) {
    debugmsg( "%s tried to commit suicide.", get_name().c_str() );
    return attack;
}
```

**Comment by Fallingferret** [comment]
i mean, maybe they're just tired of the turret life? they probably just want to end it on their own terms, instead of running out of ammo on zombies they can't pulp. the code shouldn't be so judgemental

**Comment by codemime** [comment]
@Fallingferret Thanks for the saved game BTW.

**Comment by codemime** [comment]
I've tracked the code and found the actual culprit. The case is more sophisticated than plain suicide, it's a bit schizophrenic. At first an [alter-ego](https://github.com/CleverRaven/Cataclysm-DDA/commit/4195497009aadab4df70efb92efb49daefc4e990#diff-57383a1f1e4c82e3f5a7ef4175334d1fR329
) gets created and [gets a gun](https://github.com/CleverRaven/Cataclysm-DDA/commit/4195497009aadab4df70efb92efb49daefc4e990#diff-57383a1f1e4c82e3f5a7ef4175334d1fR338). As soon as it has a gun, it [considers](https://github.com/CleverRaven/Cataclysm-DDA/commit/4c60924c4c368f7be833ecc8b68a438952fd1694#diff-c5873ed460ae46963dac594829494e52R465) the initial ego a valid target and attacks it.
