### ISSUE TITLE
Screen not redrawing correctly after prompts - tiles build with tiles off

### ISSUE THREAD

**Issue by gcaliber** [CleverRaven/Cataclysm-DDA#17047]
The part of the screen that is covered by a prompt is not being redrawn when the prompt is closed. To recreate just try to butcher something then cancel it. It only seems to be an issue on the tiles build with tiles set to false.

**Comment by DanmakuDan** [comment]
#17042 should fix this after it gets merged.

**Comment by illi-kun** [comment]
Closed as a dupe.
