### ISSUE TITLE
Craft salt and get nothing

### ISSUE THREAD

**Issue by DLaboratory** [CleverRaven/Cataclysm-DDA#17056]
Built from latest commit.

Reproduce: stand near a salt water tile in swamp, then craft salt from salt water. After long period of crafting process, the player get nothing. Charcoal is consumed.

**Comment by Zireael07** [comment]
Did you use normal crafting or batch crafting?

**Comment by DLaboratory** [comment]
Both normal crafting and batch crafting have this issue.

**Comment by kevingranade** [comment]
I think this is more general, you can't craft clean water from the map either.
So far what I've found is that with the following stacktrace:
```
#0  player::consume_items (this=0x5ba93a0, is=..., batch=<optimized out>) at src/crafting.cpp:1070
#1  0x0000000000d3ac77 in craft_command::consume_components (this=this@entry=0x5baa420) at src/craft_command.cpp:147
#2  0x0000000000bfa03c in player::complete_craft (this=this@entry=0x5ba93a0) at src/crafting.cpp:821
#3  0x000000000060cbea in player_activity::finish (this=this@entry=0x5ba9f78, p=p@entry=0x5ba93a0) at src/player_activity.cpp:360
#4  0x000000000060df5a in player_activity::do_turn (this=0x5ba9f78, p=0x5ba93a0) at src/player_activity.cpp:333
#5  0x0000000000511b40 in game::process_activity (this=this@entry=0x51d1bb0) at src/game.cpp:1591
#6  0x0000000000557a46 in game::do_turn (this=0x51d1bb0) at src/game.cpp:1399
#7  0x000000000040bcd8 in main (argc=<optimized out>, argv=0x7ffc060134e0) at src/main.cpp:468
```
It never finds any water despite standing next to some.
I'm a bit confused why craft_command::consume_components() builds a map inventory but doesn't consume from it.

Regardless, something on this path needs to include the logic to retrieve things from the map (the actual map, not just items in the map) if necessary and use them.

**Comment by kevingranade** [comment]
I suspect what happened here is #16995 fixed the preexisting bug where items on the map would not be consumed and the omission went undetected.  At some point this masked another bug, which is it didn't even try to consume items from certain sources.  After fixing the first bug, the second is exposed.
