### ISSUE TITLE
Dynamites Fuse exploding after 1 turn instead of 20

### ISSUE THREAD

**Issue by Kadian** [CleverRaven/Cataclysm-DDA#17055]
Dynamite will explode after exactly one turn after being lit on fire. This seems quite odd, since it was always a timer of 20 turns, and the json itself also states that the timer should be 20 turns, as seen here:
```
    "use_action": {
        "type": "transform",
        "target": "dynamite_act",
        "target_charges": 20,
        "need_fire": 1,
        "active": true,
        "msg": "You light the dynamite."
    }
```
One has to assume that something is wrong in the json, one of you might want to take a look at it. I checked it in Experimental 0.C 4971, which was at the time the newest Experimental.

**Comment by Zireael07** [comment]
JSON looks fine - I assume the error is code-side. Something somewhere not taking json into account?

**Comment by Coolthulhu** [comment]
Caused by `ammo_set` restricting the number of charges to maximum charge of the item.
Lit dynamite has no maximum number of charges, meaning it defaults to 0.

**Comment by mugling** [comment]
Doesn't `item` have a counter of some form we could use as an alternative?

**Comment by Coolthulhu** [comment]
That would require totally rewriting many functions that don't use `iuse_explosion`.

**Comment by pnpetroff** [comment]
Is this fixed? I dropped a dynamite, lighted it with a match and it exploded immediately. 

Using Build 7267.

**Comment by Night-Pryanik** [comment]
> I dropped a dynamite, lighted it with a match and it exploded immediately.

You should use a light source (matches) to light the fuse while dynamite is in your inventory. Lighting the dynamite while it is on the ground equals to throwing the dynamite in the small fire, so no wonder it exploded immediately.

**Comment by pnpetroff** [comment]
@Night-Pryanik Oh, guess it was my mistake then. Sorry.
