### ISSUE TITLE
Overzealous inventory filter prevent checking the reason for filtering

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17074]
For example, no message in `gunmod_compatible` will ever be printed, since it is not possible to select a weapon not compatible with a given gunmod.

**Comment by BevapDin** [comment]
Would it be a good idea to change the filter functions to return a string - empty string indication the item is allowed, non-empty string indicating it is not allowed and containing an error message?

The inventory view could be changed to show all items (toggleable?) and items that can not be used could get a small indicator or items that can be used get the indicator.

**Comment by codemime** [comment]
I'll tackle this, but I need #17009 settled.
