### ISSUE TITLE
Vending Machines in Gun Stores don't have any Ammunition/Magazines in them.

### ISSUE THREAD

**Issue by Kadian** [CleverRaven/Cataclysm-DDA#17081]
As the title says. The Issue seemed to emerge around Experimental 4771, with one person reporting it. I was able to duplicate the issue with Version 4834 back then [9th of May] and assumed that the Person who originally found the Issue reported it to github.
This does not seem to be the case however, as I just found out: The Vending machines are always empty it seems, and I spawned several gun stores, just to check if it was coincidence. Doesn't seem to be the case.
I'm currently using Version 5001 ; Maybe someone deleted the spawns from the vending machines when you added magazines?

**Comment by pisskop** [comment]
They used to, but then they stopped.

To be fair, most people would just smash them anyway.  But then alarms?
   Id start by checking why they were removed.

**Comment by Kadian** [comment]
The history does not explain why the Vending machines don't have ammo in them at all. Neither when you try to buy some nor when you smash the machines to get the Ammunition.
I can see that SunshineDistillery apparently deleted the Vending Machine spawngroups in the 4th of January, BUT he also changed the spawns at the vending machines to a different set of Spawngroups. This seems to be the last Change to the Vending machines, and since then they don't work anymore...and I have a feeling I know why.
Sunshine seems to use the following spawngroups for the Vending Machines: pistol_ammo, shotgun_ammo and rifle_ammo. These spawngroups are nonexistent though, at least i couldn't find them. This seems to be the Issue which needs fixing, right? Or did I miss something obvious in the History?

**Comment by BorkBorkGoesTheCode** [comment]
it looks like a mistake: 
cataclysmdda/data/json/itemgroups/main:  ammo_pistol_common, ammo_shotgun_common, ammo_rifle_common may be the intended itemgroups.

**Comment by BorkBorkGoesTheCode** [comment]
The vending machines lack a "vendingmachines": entry.

**Comment by Kadian** [comment]
I hate to bump this Issue, but I feel like people just...forgot about it? I don't know if anyone fixed it by now, considering that I didn't update my experimental in the last 2-3 weeks, but a word from a Contributor would be nice - is this issue something people will fix? It doesn't seem to be that big of an issue, right?
Or, if it is already, fixed, sorry to bump this :/

**Comment by illi-kun** [comment]
No need to bump any issues, it will be processed (sooner or later).

**Comment by Leland** [comment]
Fixed, possibly by #21598

**Comment by BorkBorkGoesTheCode** [comment]
It was fixed here: https://github.com/CleverRaven/Cataclysm-DDA/pull/20391
