### ISSUE TITLE
Turret refactor and blazemod

### ISSUE THREAD

**Issue by Vollinger** [CleverRaven/Cataclysm-DDA#17089]
@mugling #17028
> The undocumented MANUAL flag appears to be required by blazemod and prevents a turret being enabled for automatic targeting.

Seems like all turrets now start off in auto targeting mode so this mostly prevents from ever disabling a MANUAL flagged turret since it doesn't show up in the vehicle controls list. Even ruined turrets in wreckages will still fire on their also-undead comrades, when bribed with ammo. Worlds with blazemod and tanks mods enabled are especially affected because armed vehicles spawn with enough ammo to ruin dozens of eardrums.

Also you can no longer switch manual turret's firemode by walking on top of it and pressing shift+F.

**Comment by Fallingferret** [comment]
Enable wandering spawns for maximum !FUN! :)

I wouldn't mind if some of them were pre-activated, as that could make sense(?) with the military vehicles. IFF still functions at least, and I've yet to have a 120mm/155mm go off, so that's something.

**Comment by mugling** [comment]
That's multiple bugs the most serious of which is the destroyed turrets still firing

**Comment by velddrinn** [comment]
Well, my own most serious part is an 'aplha-strike' when trying to aim turrets manually. Unleashing a 120mm cannon, all flamelaunchers and LMGs on a single zombie dog is quite an overkill.

**Comment by mugling** [comment]
Everything in this is resolved or covered in other issues/PR's.
