### ISSUE TITLE
Bug Report: Deaf = Mugproof

### ISSUE THREAD

**Issue by Atusid** [CleverRaven/Cataclysm-DDA#17096]
Greetings.

Build: Experimental 5004.
OS: Windows
Using a tileset.

Currently running several very bad day games. My characters were repeatedly mugged by every NPC encountered. I died, created the exact same character, and happened to find a pair of earplugs in the first house. After using them, each NPC that I found would run up to me and try to talk to me. The only dialog option that I was given in this usual conversation was "a) Bye." - their text box mentioning that I couldn't hear them. I thought this was odd, so I tried another NPC. Same thing. Took the ear plugs out, and the next three NPCs I encountered mugged me.

World Creation Settings:
Mods:
More Survival Tools
Folding Parts pack
Tanks and Other Vehicles
Vehicle Additions Pack
Disable Religious texts
Mundane Zombies
Prevent Zombie Revivication
Slow Zombies

Static/Random NPCs enabled. Default settings otherwise.

Tested on two identical world gens. Tested with Survivor/Evac Center, also.

**Comment by pisskop** [comment]
Yup.

Deaf means no talking, so no mugging

**Comment by Atusid** [comment]
By design, or is this a bug?

**Comment by pisskop** [comment]
Most likely a bug.  There has to be player complience for the mugging because people dont like being suddenly shot at in the dark.

**Comment by Skidborg** [comment]
Perhaps replace NPC dialog with pantomime description when the player is deaf?  Something like:

`Fred raises his weapon and gesticulates angrily at yours.`

**Comment by Kadian** [comment]
I'm with Skidborg here - someone who wants to mug you would also threaten you with their weapon of choice and look mighty angry ; someone would see this.
On another note, would it be possible to have a dialog-option to take of the earplugs, when the player realizes the person wants something from them.This would give them the opportunity to start their real dialogue, and the player could automatically put them back on after the dialog ended?

**Comment by natsirt721** [comment]
I have had NPCs become angry after the 'bye' dialogue, but the majority just leave you alone.  Not sure if not responding pacifies them somewhat or if this is a genuine bug, but you can definitely still be mugged while deaf.
