### ISSUE TITLE
Missing WRENCH level 2

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#17119]
Braethias recently said the belt fed mod requires WRENCH level 2, but none of the tools have this tool quality.

**Comment by Soadreqm** [comment]
Maybe it's supposed to need WRENCH_FINE, which is the quality the wrench has and the pliers lack.

**Comment by mugling** [comment]
> Maybe it's supposed to need WRENCH_FINE

This was my intention
