### ISSUE TITLE
NPC Medical Aid Limited

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#17117]
Major Issues

 - They wont take antibodies outside of complete trust
 - They cant recieve antiseptic powder or liquid disinfectant
 - they wont take off splints when their wounds heal

Minor Issues

  - They wont take pain pills
  - Still wont drink booze
 

 - you can to 'trick' them into buffs by trading passive artifacts to them
 - Not all artifact powers work, and ones like teleport do while dexup does not.
 -  If you mod in extended effect armor (such as a wearable stimpack) they can be tricked into putting it on

**Comment by baraba3** [comment]
this also goes for antifungal drugs.
