### ISSUE TITLE
Vitamin/calories system disrupted Meat and Fish nutrition values

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#17123]
We don't need to include a daily protein requirement, but it should add protein to the nutrition meta value.  This is why meat and fish currently have half the nutrition they used to have

**Comment by pisskop** [comment]
I dont who wouldnt get enough protein in any given situation.

Maybe vegans-esque survivors?  meat is ample and easy to find.

**Comment by kevingranade** [comment]
If there's no requirement to consume protein what's the point of tracking
it?

**Comment by Xpyder** [comment]
The nutrition on meat is significantly off.

- If we just increase the "nutrition" value of calories then breads and pastas will get over valued
- If we increase the "calories" of meat then people who know what it actually has will repeatedly try to change it back to a realistic level without realizing why it's off.

I suppose we could have a generic adjustment rather than specifying protein, or we can remove the calories and go back to generic nutrition.  But I got the impression we were moving towards a more nuanced system like with gun mods, so I figured we wanted to be more specific rather than less.

Either way I don't mind whatever direction we go, but without some kind of secondary nutrition adjustment value most things converted to the calorie system will end up with inaccurate nutrition because nutrition is more than just calories and vitamins.

**Comment by pisskop** [comment]
So we should have a 'soup stock' meat that nerfs the amoun/quality of meat.

Like in #16947

**Comment by Coolthulhu** [comment]
Not even a pure bread diet would cause a protein deficiency.

I'd rather just buff the number of meat chunks per critter and buff dry meat's volume efficiency. And adjust recipes involving meat to the new caloric value.

**Comment by Xpyder** [comment]
However we want to deal with it is fine, but at the moment the values look weird because they suddenly dropped by half for raw and cooked meat and fish, but stayed at the previous values for anything that uses them in a recipe which is strange.

**Comment by Xpyder** [comment]
I just figured adding Protein to the nutrition calculation we're using (like calories) would be the easiest solution and would also facilitate transitioning other foods.

**Comment by kevingranade** [comment]
Nutrition should be calories*, full stop.
In fact I'd like to migrate them to literal calories instead of a unit-less
value.

If we factor in protein, I think that would be a good use of muglung's item
classes, the same as with the other vitamin values. The only reason to do
so is if we want to model protein deficiency, otherwise it's pointless.

*the only question I have is whether it should be calories or Calories. Not
sure if we need values as small as single or even hundreds of calories.

**Comment by Coolthulhu** [comment]
> the only question I have is whether it should be calories or Calories

We can list it as kcal to make it obvious.

**Comment by mugling** [comment]
> Nutrition should be calories*, full stop.

Possibly in calories per 100g. Much nutritional data is available in this format and would help with keeping the values in sync for items with various `charges` and `weight`

**Comment by Kadian** [comment]
If you change the nutrition officially to kcal, will there also be something like stature? Slim, lean builds vs. buff vs. fat builds. I would imagine that at least some lategame survivors might have some fat reserves on their body because they're eating pretty well.

**Comment by Xpyder** [comment]
I don't know if the engine supports this but we could have healing consume a "protein" vitamin, rather than trying to model protein deficiency.  It would make meat still a compelling food and important from a survival point of view, while also matching some realism without a lot of complexity.

**Comment by kevingranade** [comment]
I think you're missing the fact that the thing we're  trying to avoid is
adding protein values to a lot of food items, complexity other than that is
kind of irrelevant.
If we annotate a bunch of foods with protein values, we might as well have
a full protein deficiency system.

**Comment by mugling** [comment]
The goal of the vitamins system remains to prevent existing on `oatmeal` and `cooked meat` alone. Would adding protein values help much in terms of gameplay?

**Comment by kevingranade** [comment]
In terms of game impact, meat is one of the easiest foods to acquire in
high quantities, which lowers the priority of tracking protein.

**Comment by pingpong2011** [comment]
As much as a protein tracker might be nice, it's really obsessive. It would only increase microing unless you implement muscle building and/or renal failure.

Meat as-is is probably better than an alternative, because it gives a clear incentive to use the meat in recipes (preservation, food value, etc). Until they add some other attribute or buff morale from food, most simple foods could be nerfed.

**Comment by Xpyder** [comment]
Alright, that all sounds like a consensus against adding protein and for leaving meat with it's current nutrition.  It keeps coming up so feel free to link people here.

Also it might help to rename nutrition to kcal as @Coolthulhu suggested.
