### ISSUE TITLE
Cygwin build error under gcc 5.3.0

### ISSUE THREAD

**Issue by karols146** [CleverRaven/Cataclysm-DDA#17138]
Try to build today, got [this](http://image.prntscr.com/image/28016ae99de74d1884f13ec40ac2382f.png)
I find some way to fix it, changing c++11 to gnu++11, but i am not sure that it's a proper way to do it.

**Comment by karols146** [comment]
Just want to ask.
Cygwin is it still supported?

**Comment by kevingranade** [comment]
Aspirationally yes, but I don't know if anyone is actively maintaining it.
