### ISSUE TITLE
"Television" item represents CRTs, which are ancient even nowadays

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17131]
Unless we want retrofuturism, they should probably be changed to LCD or LED ones.

CRT technology is pretty much dead to the mainstream. CRTs are no longer produced, but they do keep burning out (the used ones, that is), meaning that it would be very unlikely that people would own working ones in DDA world.

**Comment by hurston1** [comment]
You would probably have to get rid of arcades too, as home computing killed those off. Arcade machines were all CRT. How about at the same time adding in a lot more computers in homes?

**Comment by BorkBorkGoesTheCode** [comment]
Ye Olde ~~Malt Shoppe~~ Video Arcade.
That isn't a bad idea. Why would pseudo-nostalgia stop in the future.

**Comment by mugling** [comment]
Fixed in #17061

**Comment by Rivet-the-Zombie** [comment]
>You would probably have to get rid of arcades too, as home computing killed those off.

Since when? They're certainly less common than they used to be, but there's still plenty of arcades in the USA.
