### ISSUE TITLE
Joints and cigarettes are too bright (crafting and reading possible)

### ISSUE THREAD

**Issue by flitvious** [CleverRaven/Cataclysm-DDA#17147]
Lit joints and cigarettes are too bright. They seem to behave like a small nightlight, and this causes the effects that aren't normally possible with a lit cigarette:
1. They light you up, so everyone sees you at night from a large distance.
2. They blind you in the darkness, so you cannot see past 1 tile radius.
3. You can craft in the dark while smoking.
4. You can read in the dark while smoking.

**Comment by kevingranade** [comment]
Your first issue is intended, the others I could see changing.

**Comment by Leland** [comment]
Closing - minimal discussion going on here, and we're approaching this being a year old. Feel free to comment here if you still want it open, or make a new issue.
