### ISSUE TITLE
Supporting directions in item or text

### ISSUE THREAD

**Issue by pingpong2011** [CleverRaven/Cataclysm-DDA#17168]
I've noticed whenever I use the shelter computer to find a camp, I then have to look really far off randomly on my overmap to find the location - and I'm using ASCII on a big screen.

Can compass and/or coordinates be added to text? This way, once a location is described, the item/terminal/NPC could tell you where to go. This could really open up NPC quests. It could also be used for local items, so you could find a pamphlet that says "come see our deals for X item over at Y place!" "This place appears to be [compass]" or an information board or road sign saying "military outpost - [x distance units]". If objects could have a local [geolocation] attribute, you could calculate compass, distance, absolute, etc, which all have their place in descriptions and text.

**Comment by BevapDin** [comment]
You cna search for locations on the overmap, have you tried that?

There is also the mission marker: a small (maybe too small) red character, either at on of the corners or at the middle of on of the the window borders in the overmap.

**Comment by natsirt721** [comment]
Don't quote me on this but I think I remember that using / to search the map will only search the visible area, that is it will only search the portion of the map that is shown when you start the search.  Alternatively, NPCs or consoles or whatever could add a note where the objective is, similar to auto-noting basements.  You can then just list all notes and scroll through until you find the right one.

**Comment by natsirt721** [comment]
Just kidding the bit about the search is entirely bogus.  A note on the camp would still be very beneficial.

**Comment by Leland** [comment]
Looks like discussion has stalled on this suggestion. Closing. If there's still interest, let me know and I can reopen.

**Comment by Night-Pryanik** [comment]
#19688 addressed this.
