### ISSUE TITLE
Adjust NPC equipment by rarity.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#1719]
As brought up in #1306, NPCs are equipped with weapons chosen at random from a list of all weapons, ignoring weighting for rarity.  This results in many more NPCs than intended having very high quality weaponry, both making them more dangerous than intended and making them rare item pinatas.

**Comment by mugling** [comment]
> The only exception are traders, who currently get a random item out of all items

They now obtain it from the `NC_EVAC_SHOPKEEPER_misc` and `NC_JUNK_SHOPKEEPER_misc` item groups
