### ISSUE TITLE
Survivor zombie itemgroups.

### ISSUE THREAD

**Issue by sanyaskillpro** [CleverRaven/Cataclysm-DDA#17194]
I was tinkering with jsons for a mod and noticed that survivor zombie itemgroups look wierd. 
There are 2 big itemgroups that combine some lesser groups: mon_zombie_survivor_death_drops and mon_zombie_survivor_elite_death_drops. The first one is used for survivor zombies, the second one is not used at all. Both have stuff like survival gear, food, weapons and books included. BUT, the first one is using civilian clothing item group - just like those worn by regular Zeds. The second one has more thematic makeshift and survival armor and clothing. Now i recall that a couple of months ago survivor z's used to drop stuff from the second item group. I guess it's a bug, but it may have been an attempt to nerf survivor zombie drops? Even if it was, i think the second item group is more thematically appropriate.

**Comment by Leland** [comment]
Looks like discussion has stalled on this suggestion. Closing. If there's still interest, let me know and I can reopen.
