### ISSUE TITLE
Infinite water sources are broken

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#17200]
Infinite water sources nolonger provide `water` and when in range also prevent using any `water` from any finite source.

EDIT: Possibly relates to #17067?

**Comment by BevapDin** [comment]
I fail to reproduce this, what is your test case?

**Comment by Coolthulhu** [comment]
Can't reproduce the
> when in range also prevent using any water from any finite source

part, but while testing washboard, the
> Infinite water sources nolonger provide water

happened every time I tried to use water from crafting inventory until I poured 40 units of water into a keg. Then infinite water started being usable for crafting.

**Comment by Rivet-the-Zombie** [comment]
Get yourself a pair of waterskins and a mess kit.  
Stand beside a river, pump, or whatever.  
Attempt to craft clean water. Fail.  
Fill one waterskin with water.  
Attempt to craft clean water again. Now it works.

**Comment by mugling** [comment]
Try also shelter start in LMOE, similar
