### ISSUE TITLE
Burning characters have their clothing disappear rather than take damage

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17217]
Now that burning is an `item` method, it could be pretty easy to just use said method to deal damage to clothing.

**Comment by Labtop-215** [comment]
Can't fire do both?

**Comment by Coolthulhu** [comment]
Why should it instantly destroy reinforced clothing though?

**Comment by Rivet-the-Zombie** [comment]
Yeah, it should be burning off the item's health bit by bit, not evaporating them all at once.

**Comment by Labtop-215** [comment]
Oh I think I get what you mean.  I thought you meant that burning characters only lose their clothing instead of taking damage.
