### ISSUE TITLE
Pipe rifles & revolvers not ejecting empty casings

### ISSUE THREAD

**Issue by Vollinger** [CleverRaven/Cataclysm-DDA#17211]
... until you reload a second round. This means you never get spent casing from pipe rifles since they can't hold more than a single round.

Example: fire all six shots from a revolver till it's empty, reload once - no ejection. Reload second time, get all six casings.

If you keep loading and firing only a single cartridge at a time, you can build up a huge backlog of brass that pours out like a deluge the moment you load two in a row.

**Comment by mugling** [comment]
Have identified cause but fix is not simple

**Comment by mugling** [comment]
`item::ammo_casing` depends upon loaded ammo to determine the casing type so `null` is returned when the last round is fired but `CASINGS` variable still accumulates producing the above behavior.

Could be kludged via `item::ammo_casing` but I'd rather go with the correct solution of storing the casings within the item.

**Comment by mugling** [comment]
Fixed in #17627
