### ISSUE TITLE
Addiction fades too quickly

### ISSUE THREAD

**Issue by pingpong2011** [CleverRaven/Cataclysm-DDA#17221]
According to my and a few persons experience on the forums, addictions don't seem to set in reliably, and/or end far too quickly. I normally play chain smoker, and my last character went through maybe a day of symptoms after smoking for a year.

http://smf.cataclysmdda.com/index.php?topic=12758.0

**Comment by Night-Pryanik** [comment]
What's your season length?

**Comment by pingpong2011** [comment]
14 days, normal. I don't see how that'd effect addiction, especially when other people are reporting the issue with stuff like acoholism and bad day.

**Comment by Night-Pryanik** [comment]
1 day of 14 days season is 6,4 days of 90 days season (similar to irl). It may require balance, but I think almost a week is enough to cancel negative effects of smoking.

**Comment by bumpkindda** [comment]
I play 92 day seasons and addiction is still gone within a day (if I start addicted, I don't seem to be able to build an addiction otherwise)

**Comment by Night-Pryanik** [comment]
Addiction length just should be proportional to season length.

**Comment by kevingranade** [comment]
Addiction length should *not* be proportional to season length.
As for how long addictions *should* last, please make some concrete
suggestions, "not long enough" doesn't give us a target to implement.

**Comment by Night-Pryanik** [comment]
> Addiction length should *not* be proportional to season length.

Why? 1 day out of 14 is bigger than 1 out of 30 (or even 1 out of 90).

**Comment by kevingranade** [comment]
Because season length changes only season length, it's not a general
purpose time dilation setting. The number of (arbitratily sized) years that
pass in a given time span is irrelevant to how long it takes to recover
from an addiction.

**Comment by Leland** [comment]
We're approaching the year mark since the last comment on this one. Closing – if there's still interest by anyone feel free to either let me know you want it reopened here or just create a new issue.
