### ISSUE TITLE
Generic factory doesn't allow assigning floats

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17226]
It handles integers, string-constructible types and a bunch of hardcoded types, but neither of those includes floats.

**Comment by mugling** [comment]
Do you mean the `assign` family of free functions?

**Comment by Coolthulhu** [comment]
Yes

Do others allow it? If so, I guess it doesn't really matter and this can be closed.

**Comment by mugling** [comment]
Resolved in `master`
