### ISSUE TITLE
Can the Elephant Gun spawn during mapgen?

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#17234]
The Elephant Gun does not seem to spawn during mapgen. Is this because it is a late-game reward or a debug item?

**Comment by bumpkindda** [comment]
I got one in my last game (started 10 few builds ago, max). It spawned in a mansion, I believe.

**Comment by Solusphere** [comment]
I've found one in a gun safe in a survivor basement before. That was about a month ago IIRC.

**Comment by illi-kun** [comment]
You can find it in item groups ```antique_rare``` and ```pawn``` (search for ```trex_gun```). BTW, it's better to ask such questions on the forum, because bug tracker is for bugs (obviously).
