### ISSUE TITLE
[5071] Completion of NPC antibiotic mission does not halt the deadline

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#17242]
My starting NPC was infected. After successfully completing the mission, I didn't think anything more of it, recruited her, and went on my merry way. However, the deadline continued to run even after the mission was completed. Once it hit, she died. A debug message was printed:

12:59:47.26 : src/player.cpp:13380 [void player::on_mission_finished(mission&)] completed mission 1 was not in the active_missions list

To duplicate, load world and walk around until the NPC dies.

[Smiley Park.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/321871/Smiley.Park.zip)

**Comment by Soyweiser** [comment]
It gives errors for each mission that was given by that npc. And they also all get added to the failed mission list. (find antibiotics twice even).
