### ISSUE TITLE
Filthy morale penalty is broken

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17247]
Filthy morale penalty is non-monotonous. That is - putting on filthy gear can decrease the penalty.

Could be caused by bugged saves, in which case the bug is morale data not being recalculated. It should be recalculated at the very least at every game load.

**Comment by Rivet-the-Zombie** [comment]
Even if you wash the gear, putting it on triggers the penalty, and it doesn't seem to go away even if you remove it.

**Comment by codemime** [comment]
>  It should be recalculated at the very least at every game load.

I can (will) add the recalculation at every game load, but that looks like a workaround if implemented without a debug message. By recalculating the morale we conceal the actual bugs that cause an inconsistent state.

**Comment by Coolthulhu** [comment]
> By recalculating the morale we conceal the actual bugs that cause an inconsistent state.

You can do what I suggested before: keep the state, recalculate it, then compare the results and debugmsg on inconsistency.
The morale system is way too fragile to trust it that it will stay in sync and too subtle to expect bugs in it to show.

The bugs will happen. A good system should report them (or otherwise make them obvious), then try to recover from them. The current morale system does neither.

**Comment by codemime** [comment]
> You can do what I suggested before: keep the state, recalculate it, then compare the results and debugmsg on inconsistency.

Will do that after finishing the drop code refactoring.

> A good system should report them (or otherwise make them obvious), then try to recover from them. 

True.
