### ISSUE TITLE
Door to the second computer in the lab barracks is locked

### ISSUE THREAD

**Issue by flitvious** [CleverRaven/Cataclysm-DDA#17246]
This makes the second computer useless.

Once you are inside (in the room with "living quarters") there is a second computer that opens the doors to the storage area. This computer is enclosed in a small room with two metal doors. There is no way to get to that room without bypassing the locked and unpickable metal door (bottom). But once you are inside, there is no need to hack the computer, because the internal door (top) is not locked and leads to the storage area. 

I think the doors must be locked the other way around, although from the security perspective that makes sense: one guy from the storage area sits inside without anyone being able to get into that room.
![untitled](https://cloud.githubusercontent.com/assets/7687709/16173616/f93ee196-35af-11e6-9a8a-ffee9003b4b5.png)

**Comment by TempestMaiden** [comment]
I'll note there's a specific time where that computer isn't useless: when stairs drop you into the armory.

I'm not sure _that_ is intended either, though - it seems pointless to lock the front door if you're going to leave the back wide open.

**Comment by Labtop-215** [comment]
The idea is that you are supposed to bypass that setup somehow.  You arn't supposed to be dropped in from above however.

**Comment by flitvious** [comment]
Currently there are two options for bypassing that can be boiled down to one: destroy walls or doors. This is done with a jackhammer or an acetylene torch and is a guaranteed success. Reversing locking order for those doors will create another viable (but not guaranteed) option of opening armory with a high computer skill.

**Comment by mutt3x** [comment]
I dont see any problem with the current way its made, takes some effort to get in rather than just hacking the terminal. Its not an ordinary room afterall.
Just hacking the terminal is lame. More creative fun is always better, no? I would even place a turret in there... because players in endgame use CBM to walk through walls.

>when stairs drop you into the armory

I think this is a bigger bug/problem than what **flitvious** points out.

**Comment by flitvious** [comment]
I don't see how adding another (possibly more difficult and not guaranteed) way to get into the armory makes the situation worse. If anything is too easy, it is blasting military-grade installation walls with a jackhammer from a home improvement store. There is nothing creative with blasting the toilet wall and walking inside the armory, whistling and smoking a joint. I do that all the time when looting labs, and that's the problem. It is too easy and it gets boring fast.

I like your idea about the turret. Suppose there is one milspec turret inside at all times, just like one on the laboratory entrance, but bigger. Now those jackhammer-toting intruders will get a nasty surprise. This also fixes that "get in from above" problem. There is a way in without a combat, with a difficult computer check that has the following outcomes:

1. _"Access granted. Have a nice day, colonel."_ Success. Turret gets deactivated and doors to the armory open. Have your loot, world-class hacker with 9 in computers.

2. _"Security shutdown initiated. Your biometric data has been logged. Contact your superior officer immediately."_ Minor failure. Console shutdown. Now you have to deal with walls and turrets.

3. _"User credentials do not match biometric data. Deploying security measures. Armory zone is off-limits to all personnel with access level below F."_ Moderate failure. Two turrets/drones spawn inside the armory. Now the situation got worse, so maybe leave this terminal alone next time.

4. _"Enemy force detected in the facility. Code RED. Deploying all security measures. Civilian  personnel must report to zone D."_ Major failure. Several turrets spawn in the armory and in the living quarters. Possibly on the external doors, blocking the player inside the tiny room. Now that's a situation that requires creative thinking to get out of.

This has risk/reward, choice and challenge. How's the idea?

**Comment by TempestMaiden** [comment]
I have to admit, for most of my lab runs all any of that would do is give me more ammo to loot.

The only exception is the occasional early character who'd be killed by the last - and that just means I'd wait a bit longer before busting open armories.

If you can credibly loot labs, you're likely to get access to the control laptop pretty quickly.

**Comment by Leland** [comment]
Discussion's been stalled on this one for a year, closing.
