### ISSUE TITLE
NPCs using the Tazer and Tazer not knowing how to be used by non-Players

### ISSUE THREAD

**Issue by RadaRadaRada** [CleverRaven/Cataclysm-DDA#17240]
1. Give NPC a loaded Tazer.
2. Engage in combat.
3. Occasionally, be prompted shock something, even if NPC is far away.

Edit.
4. If NPC is engaged in combat and there are no enemies around the player, then prompted to shock something, you have no choice but to shock yourself to death.

**Comment by mugling** [comment]
> If NPC is engaged in combat and there are no enemies around the player, then prompted to shock something, you have no choice but to shock yourself to death.

This is a pretty nasty bug
