### ISSUE TITLE
NPC escape item and alternative attack item code terribly outdated

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17258]
Causes #17240

NPCs use a hardcoded list of escape items and alternative attack items. This is obviously a horrible practice - it should be done at the very least with flags.

And it should be tested too. C4, mininuke and tazer are all player-only items at the moment.

**Comment by TheWebfrog** [comment]
So like if NPC has Makeshift Machete then it is coded to resort to like another weapon ( like a knife ) or something?

**Comment by Coolthulhu** [comment]
No, it only covers grenades and thrown weapons.
