### ISSUE TITLE
Own Laser turret turns hostile

### ISSUE THREAD

**Issue by Mecares** [CleverRaven/Cataclysm-DDA#17264]
My Laser-turret placed inside my Shelter as a light source has turned hostile. I am currently on build 5031.

**Comment by Taberone** [comment]
Was it friendly when you first placed it? IIRC(On the IOS version at least), Turrets have a chance of not recognizing you as friendly when you first place them, which usually results them turning you into a thin red paste soon after.

**Comment by Mecares** [comment]
I am not sure i placed him underground and laser turrets only shoot while in daylight. He still has enough power to be a light source for the room though.

**Comment by mugling** [comment]
Closed as unconfirmed
