### ISSUE TITLE
Inexcusably horrible hack in zlave code

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17267]
```
if( it.is_corpse() && mt->in_species( ZOMBIE ) && mt->made_of( material_id( "flesh" ) ) &&
    mt->sym == "Z" && it.active && !it.has_var( "zlave" ) ) {
    corpses.push_back( &it );
}
```

```
mt->sym == "Z"
```

The glyph is being used to determine properties of a critter. Granted, it's only zlave code so no one really needs to care, but seriously.

**Comment by Rivet-the-Zombie** [comment]
That's right up there with the hack we once had that determined whether clothes were a backpack or not using the item's glyph color.

**Comment by mugling** [comment]
That is indeed a fairly ugly hack
