### ISSUE TITLE
Crafted vehicles cannot be started

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17261]
I crafted from scratch three different vehicles:
1) a foldable bicycle from craft menu and unfold it;
2) regular vehicle, that still counts as bicycle;
3) electro-motor bike;
None of them can be driven. There a "The %s doesn't have an engine!" message in the log.
First two have foot cranks as an engine. Third have small electric motor and battery installed. All of them of course have control system, two weels and seat installed.

P.S. Playing build #5079

**Comment by bumpkindda** [comment]
Also occurs in normally spawned bicycles and electric bicycles.

**Comment by bumpkindda** [comment]
Actually, electric cars are affected too, seems to occur in every vehicle without a combustion engine.
