### ISSUE TITLE
Ammo volume in quivers affects reload time significantly

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17274]
* Spawn large quiver, bow and 80 arrows
* Load the quiver
* Spawn debug monster
* Set own skill levels to 10
* Shoot it while watching move cost meter

Move cost meter will go down from around 300 per shot to 100 per shot as the quiver gets emptier.

**Comment by mugling** [comment]
So that explains why we get different values

**Comment by mugling** [comment]
Did we fail to completely resolve the item stack bug (#15315)?

**Comment by Coolthulhu** [comment]
Looks like it.

Or something might have reintroduced it.

**Comment by kevingranade** [comment]
Your reproduction case looks specific enough to write a unit test around,
hinthint.

**Comment by mugling** [comment]
We should work more on the unit tests - at present they don't even compile and those that do have innumerable failures

**Comment by mugling** [comment]
Narrowed down to `player::item_reload_cost`

**Comment by kevingranade** [comment]
Really? They compile here and there are 6 tests with failures. If you are
seeing something different that's interesting.

**Comment by mugling** [comment]
Now back to compiling successfully but I'm going to look into which tests fail and why
