### ISSUE TITLE
Brown textcolor on back background is hard to read (filthy clothes)

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#17276]
i have a hard time to read the brown colored names of the filthy clothes that zombies drop, because of the black background. Please chose a color that is more visible.

**Comment by illi-kun** [comment]
If your console shows brown text unreadable you can replace this color by any other via color manager (which is built-in in the game).

**Comment by ZenZen2** [comment]
thanks a lot :)

**Comment by Rivet-the-Zombie** [comment]
It certainly wouldn't have been my first choice for a default color, but illi-kun has a very good point.
