### ISSUE TITLE
Radios work deep underground

### ISSUE THREAD

**Issue by TheWebfrog** [CleverRaven/Cataclysm-DDA#17278]
Pretty much what the title says

Radios work deep undergound which is quite unrealistic

maybe this could be fixed by adding a new `unuseable at under ( Z-level)` tag ( if there isnt one already ) 

Note: should be unusable under -1 or at most -2 Z level

**Comment by nanovad** [comment]
I agree with this. With Z-levels getting more and more usable, I'd imagine other items will come along which can't work at certain depths (anything radio controlled, perhaps?)  
However, an RC car failing to work at -2Z, even though you have line of sight is unrealistic. I'd say that if the transmitter/receiver are on different Z-levels **and** the signal has to pass through the ground, they should fail to work.

**Comment by mugling** [comment]
Radios no loger do anything so this bug is defunct
