### ISSUE TITLE
Can't reload an aux fire mod on UPS weapon

### ISSUE THREAD

**Issue by onyx44** [CleverRaven/Cataclysm-DDA#17281]
On build 0.C-5090 Windows with tiles I did the following:
1. Set skills to 10
2. Spawned A7 laser rifle, M320 GLM and a bunch of 40mm buckshot
3. Attached M320
4. Dropped some 40mm
5. Attempted to reload A7 in AIM, then wielded in both (F)ire modes

First there is a selection box for source of ammo, then a message "Can't reload the A7 laser rifle"
Looks similar to [#14603](https://github.com/CleverRaven/Cataclysm-DDA/issues/14603)

Maybe somehow related to [#15614](https://github.com/CleverRaven/Cataclysm-DDA/pull/15614)?

**Comment by mugling** [comment]
Suspect resolved in `master`. Please reopen if reproducible
