### ISSUE TITLE
Methacola is made of glass

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17293]
It is one of "those items" that no one crafts.

We should obsolete all those crappy drinks no one cares about.

**Comment by Labtop-215** [comment]
Maybe add it to the crazy cataclysm mod?

**Comment by Night-Pryanik** [comment]
> Maybe add it to the crazy cataclysm mod?

There's nothing "crazy" about it.

**Comment by bumpkindda** [comment]
I use it because meth is broken and worthless for anything but buffing your int for CBM installations at home. I'm with you on obsoleting methacola but only after meth has some practical usage (ie. doesn't last 30 minutes then make you sleep for 2 days, regardless of how rested you are before you take it).

**Comment by Cyrano7** [comment]
It's too bad meth is so broken. I like the idea of the methcola as one of those quarky cata things but broken is broken. Some others are honeygold brew which you need ant honey for(and i'm pretty sure you can't get anymore), sewer brew which has weak mutagen properties but doesn't tell you it does and sewage IMO shouldn't really be a way to mutate, and don't even get me started on strawberry surprise and boozeberry.

**Comment by Labtop-215** [comment]
I know some people would be upset if their boozeberry or strawberry surprise disappeared.

**Comment by Cyrano7** [comment]
Sooooo broken and half baked. I have no idea why people are so attached to them.....

**Comment by Labtop-215** [comment]
Because they are broken and half baked.

**Comment by Coolthulhu** [comment]
> I have no idea why people are so attached to them

Because they're permafood with high nutrition value that don't require specific containers.

**Comment by Cyrano7** [comment]
Also mixed weak alcohol is pretty silly to. It's not part of any recipes. The only thing you can do with it is drink it and why the hell would you when you can just drink the beer or whatever on its own.

**Comment by bumpkindda** [comment]
Boozeberry/SS should at least be removed from spawn drops, I doubt anyone's making and eating disgusting pruno sludge-food before the apocalypse.
