### ISSUE TITLE
Some vehicles still affected by 'this vehicle doesn't have an engine' bug

### ISSUE THREAD

**Issue by bumpkindda** [CleverRaven/Cataclysm-DDA#17298]
- Solar Car
- Electric Sports Car
- Atomic Sports Car
- Atomic Mini-Tank (tanks mod)

**Comment by Coolthulhu** [comment]
Seems that all of those vehicles have `>1` engine.

**Comment by mugling** [comment]
It should say "*all engines are currently disabled"*

**Comment by Coolthulhu** [comment]
```
has_engine = has_engine || is_engine_on( e );
```

I can't find "currently disabled" in any vehicle code related section.

**Comment by mugling** [comment]
`vehicle.cpp:1476` has faulty logic. It complains the vehicle has no engines when in fact they are just all switched off

**Comment by mugling** [comment]
This bug presumably existed prior but is now much more noticeable given that engines are disabled by default. We need to fix the message in any case.
