### ISSUE TITLE
Refilling cars from containers broken

### ISSUE THREAD

**Issue by bumpkindda** [CleverRaven/Cataclysm-DDA#17304]
1 - Start new world
2 - Spawn a gas/diesel vehicle, rubber hose, gallon jug
3 - Siphon out some fuel
4 - Attempt to refill it

**Comment by belazzz** [comment]
The same goes for refilling vehicle batteries.

**Comment by mugling** [comment]
What actually happens?

**Comment by belazzz** [comment]
Nothing at all, when you press [f], the vehicle screes just closes, with no message of any kind. The fuel/batteries are not consumed.

**Comment by bumpkindda** [comment]
Filling batteries was due to be phased out anyway, but not being able to refill your tanks is kinda gamebreaking.

**Comment by belazzz** [comment]
BTW, for liquids (fuel, water) this can be worked around by [U]nloading the container and selecting to fill the nearby vehicle.
