### ISSUE TITLE
Missing Item Definition

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#17307]
cataclysmdda-0.C-5092, no mods.
I was shooting a Zombie with a Glock 19, he was next to me, shooting without aiming just pressing F, F,....
then the game stopped (did not crash) and a debug window came up with the following:

DEBUG: Missing Item Definition
FUNCTION: const itype* Item_factory::find_template(const itype_id&) const
FILE: src/item_factory.cpp
LINE: 866

Pressed spacebar, next window:

DEBUG: Tried to set invalid ammo of undefined- for Feuerzeug
FUNCTION: item& item::ammo_set(const itype_id&, long int)
FILE: src/item.cpp
LINE: 253

Pressed spacebar again and it let me play.

**Comment by ZenZen2** [comment]
The Zombie droped a Feuerzeug (a lighter in english) without charges.

**Comment by mugling** [comment]
Suspect charge randomisation code could be at fault here. Does anyone love that feature sufficiently to justify the special case? I'm not sure balance would be adversely affected if we had `lighter (50)` as well as our already fixed `matchbook (20)`?

**Comment by flitvious** [comment]
From the game perspective, lighter(50) would become always inferior to refillable lighter(50). Right now there is a possibility of getting ~80-90 charge lighter on a lucky drop. 

Also, it makes sense that zombies drop used lighters, so a minor bit of immersion will go if lighters become standard. However, zombies already drop radio(100) and other such items with set amount of charges, so lighters are an exception.

**Comment by Zireael07** [comment]
I guess charges should be randomised for lighters, radios etc. instead of going back to standard things.
