### ISSUE TITLE
Game crash when picking up scrap metal

### ISSUE THREAD

**Issue by slowleakage** [CleverRaven/Cataclysm-DDA#17333]
Scrap metal listed as "scrap metal (0)" in game.  Error message upon pickup.  Updated from build 5102 to 5116.  Error message as follows:

Assertion failed!

Program... blah blah blah...\CDDA\catacysm-tiles.exe
File: src/advanced_inv.cpp, Line 2026

Expression: input_amount > 0

**Comment by BorkBorkGoesTheCode** [comment]
This happened without a crash to joints.

**Comment by Coolthulhu** [comment]
How did you get the (0) metal? From a save or dropped in game?

**Comment by Coolthulhu** [comment]
#17338 should fix it. Adding confirmation required now that it is merged and scrap has charged.

**Comment by DLaboratory** [comment]
No error appears when picking up scrap metals from car accidents in new generated world after that PR merged.
