### ISSUE TITLE
Game Crash when juggling filled open containers

### ISSUE THREAD

**Issue by nikheizen** [CleverRaven/Cataclysm-DDA#17334]
Bug - Crash
Linux-Debian Ubuntu(lubuntu)
ncurses - 0.C-15702-gaac586e
Reproducibility: Didn't try.
Cause:
- When trying to pick up a pile of items, I maxed out on volume.
- Given the option to dispose of my cudgel, or spill an open tin can of water, I disposed of the cudgel.
- Given the option to dispose of my tin can(No.1) or spill another open tin can(No.2), I disposed of tin can No.1.
- Then, the game asked me what to do with the water in tin can No.1, and I chose to consume it.
- Then the game crashed.

The save file was not corrupted, but was reverted to my last save unfortunately.

This is my first time reporting a bug in CDDA and I am fairly new to the game. If there is any more info I can provide, I would be happy to.

**Comment by Coolthulhu** [comment]
Reproduced.

Also managed to double the contents of the containers while canceling to pick them up.
