### ISSUE TITLE
Impossible to craft something with rope supplied by “Rope Webs” mutation.

### ISSUE THREAD

**Issue by onyx44** [CleverRaven/Cataclysm-DDA#17337]
Tried this on build 0.C-5117 windows tiles:
1. Debugged myself Arachnid threshold and Rope Webs mutations.
2. Attempted to craft long rope.

In the crafting window “short rope” component is colored light green, that supposedly indicates it’s availability. After hitting Enter crafting window closes, crafting action does not start, long rope does not appear in inventory (or nearby, for that matter), no message is added to the log, no error message is shown. The game acts like it didn’t register crafting attempt at all.
Debug “Edit player”->”Set needs” shows 1 Hunger. Setting it to -3000 and repeating craft doesn’t change anything.
1. Wished for some two-by-fours and nails.
2. Built empty door frame, then makeshift door. No problems there.

**Comment by Oskar636** [comment]
Rope webs mutation is a mutation that when you activate it, it produces a long rope. Don't know whether it was like this before but this bug can't be reproduced now. Build 5861
