### ISSUE TITLE
Turrets clone the shooter, preventing original shooter from being "responsible"

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17343]
* Spawn a flaming electric car
* Get on a turret
* Spawn a NPC
* Commit murder

Observations:
* Committing the murder may be hard due to the cutting armor bug thing (not related to this bug)
* You don't use up moves - your clone does
* You don't gain skill. If you are at 99% ranged skill, you will get messages about skill level increasing every time you shoot. But it won't actually increase on you, just the clone
* You will most likely not be penalized for murder since `killer != &g->u`

Character clones shouldn't be used for anything that may have any lasting effects, only getting information.

**Comment by mugling** [comment]
> Character clones shouldn't be used for anything

arguably shouldn't be used ~~for anything~~ at all (#17344, #17341, #17334)

**Comment by Coolthulhu** [comment]
Crash wasn't caused by clones, only the pseudo-spilling.
