### ISSUE TITLE
Clang debug build attempts fails at compiling the tests

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17340]
The main executable is produced, but tests are not:

```
fake_messages.cpp:14:10: error: chosen constructor is explicit in copy-initialization
      return {};
```

**Comment by codemime** [comment]
The reason is the same as for #17087 (and the same solution).

**Comment by kevingranade** [comment]
Installed clang, no dice, version "clang version 3.8.0".
I'll make the change blind and PR it so you can test.
