### ISSUE TITLE
Crash when using reapers on a car

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17357]
When tried to drive on a car with switched reapers on over the ripe plants (or also over already collected plants), game crashes. Uploaded world save to dropbox, don't forget to switch on reapers.
The car was spawned on a ranch hangar, I just repaired it a bit and installed few more batteries and solar panels.

https://dl.dropboxusercontent.com/u/9536595/CDDA_Test_Farm.zip

**Comment by Xelat84** [comment]
Probably the reason is because this car have already installed advanced reaper, which is impossible to install manually and also installed in a wrong place.
I just tested and when I dismantle advanced reapers from that car and installed regular one into proper place - no crashes occurs.

**Comment by kevingranade** [comment]
I'm also seeing a crash on the line:
```const item& seed = g->m.i_at(reaper_pos).front();```
because i_at() returns an empty vector, PR addressing this momentarily.
