### ISSUE TITLE
Starting commune battery mission causes crash

### ISSUE THREAD

**Issue by strife26** [CleverRaven/Cataclysm-DDA#17358]
Tested on 5124 and 4876 at least with a stack of the default mods and the map revealed. I'll continue troubleshooting it.

Attempting to start the commune mission where they send the PC to fetch car batteries causes a crash, starting with debug message
DEBUG: destroy_vehicle can't find it! name=Sports Car, submap:0,0,0

FUNCTION: void map::destroy_vehicle(vehicle*)
FILE: src/map.cpp
LINE: 352

**Comment by strife26** [comment]
Crash occurs on 5124 graphical with no mods or reveal, albeit with flatbed for the vehicle and 0,1,0 for the submap.

**Comment by codemime** [comment]
Could you upload a saved game?

**Comment by strife26** [comment]
Will do. This crash is really confusing me now. Both the 5124 and the 4876 games that were crashing are no longer doing it with no changes from my side that I can think of, unless it's something related to my computer.

**Comment by mugling** [comment]
@Coolthulhu is this fixed after your missions PR?

**Comment by Coolthulhu** [comment]
Unlikely, unless the crash was caused by invalid mission being acquired somehow.
Most likely caused by a really weird mechanic of hardcoded mapgen changes on mission start.

**Comment by Coolthulhu** [comment]
While mission code is still a horrible mess of spaghetti code with no good order, undefined behaviors and general fuckery, this particular bug should no longer happen due to changes in vehicle placement code.

**Comment by eliotcougar** [comment]
I've been testing missions lately, and didn't encounter this crash... However, between missions some random cars are placed on the ranch, and they sometimes overlap with terrain... It may be related to that... Or maybe not...

**Comment by Coolthulhu** [comment]
`destroy_car` was rewritten, meaning this specific crash should not be possible to reproduce.
