### ISSUE TITLE
filty clothes still buged if you wash them while not wearing them. 5092

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#17369]
It works well if you wash them while wearing. (didnt use clean water, just normal one from toilets).
If you wash them while they are in your bag, they will get clean but you get an unremoveable filthy clothes penality.
cataclysmdda-0.C-5092

**Comment by Night-Pryanik** [comment]
@ZenZen2 This was fixed in 5097. Is this still an issue?

**Comment by ZenZen2** [comment]
Im still on 5092. I assume its fixed then. Closing this.
