### ISSUE TITLE
Weapons disappearing when switched out and worn with shoulder strap.

### ISSUE THREAD

**Issue by iavatus** [CleverRaven/Cataclysm-DDA#17362]
Version 0.C-15797-g7dc0086 (tiles)
Build 5125 
Clean world, no mods selected.

Wielding a weapon with a shoulder strap, and swapping to something else. Choosing to wear the gun makes it disappear enitrely - not in inventory, on the ground nearby.
Holsters still work, just the strap doesn't.
Whatever mods are attached to the gun are removed when it disappears, including the strap.

**Comment by Breligar** [comment]
Similar enough issue that I'll add it here:

Choosing to store a wielded, modded weapon causes all of the mods to unequip and place themselves in your inventory, alongside the (now unmodded) weapon. No loss of items experienced.

**Comment by iavatus** [comment]
Dropping the gun with the Stop wielding (gun) menu, makes it disappear. Dropping it with the (d) command doesn't. So, appears to be the wield menu creating issues.
