### ISSUE TITLE
Cannot siphon fuel from gasoline pump into container in adjacent tile

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17371]
When trying to siphon fuel from gasoline pump into container that laying in my vehicle in the adjacent tile, game asks where I want to siphon, and when I selecting "c" - into container, it says that it cannot find any containers. But if I will stand over that tile with container - then everything works.

**Comment by codemime** [comment]
This behavior is probably intended. I guess the container you were trying to use is a "bucket" (can't be sealed). The game doesn't allow buckets filled with liquid to be put on vehicles, but this limitation will remain unclear to the user till #17074 resolves.

We could use another approach though: don't prohibit buckets, but spill their content (or some quantity of it) using a fair chance when the vehicle moves.

**Comment by Xelat84** [comment]
Nope, it was a metal tank (60L).
And notice again, if I stand over it when using gasoline pump, it will work.
BTW same behaviour for siphon fuel from vehicle.
Previously it was working for adjacent tiles too, like when you try to unload container with liquid.
So I think it's a bug.

**Comment by codemime** [comment]
It's a bug indeed and it's extremely trivial to fix.
