### ISSUE TITLE
Wrong metal counting. Cannot repair or improve items that require scrap metal

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17370]
Lately there was introduced charges counting system for scrap metal and few other metal items. So probably this bug caused by counting scrap metal by charges, and when improving action required more than one piece of scrap metal - it says that I need 2 pieces, but have only one (which contains say 4 "charges").

**Comment by BrotherCavalier** [comment]
Same thing happening in builds 5129 5137 but not in 4818. No others tested at this time.

**Comment by mugling** [comment]
Do you mean repairing?

**Comment by Xelat84** [comment]
I tested in a 5137 build too. I activate welder and then when trying to do something with fully repaired but not improved item, exactly "awl pike" in my case, it says that I "need 2 pieces of scrap metal, but I have only 1". But I have a lot of scrap iron, they just laying in a single pile and counting by charges.
It became broken exactly when counting system was implemented for scrap metal.

**Comment by mugling** [comment]
Have identified deficiency is in `repair_item_actor::handle_components` and am testing fix

**Comment by BrotherCavalier** [comment]
As long as reinforce and repair are the same function. Thanks, Mugling!

**Comment by mugling** [comment]
@BrotherCavalier you're welcome. Please test the fix and report back

**Comment by BrotherCavalier** [comment]
Nope. 
Just so you have the entire picture. 
)Download and unzip 5143 into new folder
)launch 5143
)gen new world all defaults, no mods
)bind the tlde hey to the debug menu
)spawn new vehicle > Welding Cart
)spawn 10 scap metal
)spawn diamond nodachi
)examine welder > Use Welding Rig >Repair metal/plastic/kevlar
)select nodachi
[You don't have enough scrap metals to do that. Have: 1, need:2]
)spawn diamond katana
)repeat previous steps ... That worked
)spawn steel halbard .. that fails same message [You don't have enough scrap metals to do that. Have: 1, need:2]

Strangely I also can not refill the storage battery on the welding cart, nor the minireactor that I installed.

Odd

**Comment by mugling** [comment]
Ah to be clear you need to test this specific PR or wait until it is merged
