### ISSUE TITLE
Blurred screen on Windows SDL occured possibly after switched to background

### ISSUE THREAD

**Issue by DLaboratory** [CleverRaven/Cataclysm-DDA#17378]
![gibberish](https://cloud.githubusercontent.com/assets/5671495/16360687/7b3a1976-3ba1-11e6-981e-64ad921d5372.png)

![gibberish2](https://cloud.githubusercontent.com/assets/5671495/16360689/7b3c1dfc-3ba1-11e6-8d32-c799757aa5bf.png)

![gibberish3](https://cloud.githubusercontent.com/assets/5671495/16360688/7b3af792-3ba1-11e6-98fd-7794cb04fa5f.png)

OS: Windows 10 x64
CPU: Intel Core i5-5250U
GPU: Integrated GPU of Intel Core i5-5250U

Both MinGW builds obtained from `ci.narc.ro` and MSVC builds I compiled myself have the issue.

This happens **possibly** after the window was switched to background a while ago, and when switch it back to focus, the screen contains gibberish. Not every time, but randomly happens.

**Comment by kevingranade** [comment]
Need to trawl through the SDL bug tracker and see if anything like this is
reported, I don't think we do anything that could possibly cause this.

**Comment by DLaboratory** [comment]
Sorry, this is a duplicate of #14023.
