### ISSUE TITLE
Strapped shotgun dissapears when worn.

### ISSUE THREAD

**Issue by nikheizen** [CleverRaven/Cataclysm-DDA#17375]
Bug - Minor
Linux - Debian Ubuntu (lubuntu)
ncurses - 0.c-15795-ge55edd1

After attaching a shoulder strap to my pump-action shotgun, I wore it once. Then I took it off to reload it, and when I put it back on after wielding my cudgel, the pump-action shotgun disappeared, while the shoulder strap was placed back into my inventory.
Perhaps the generic guns or disable distinct magazines mods are related?
Save file is attached. (if there is a preferred method for me to do this in the future, please tell me and I will use another service if that is preferred)

[Four_Buttes.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/333353/Four_Buttes.zip)

**Comment by Coolthulhu** [comment]
This was fixed like 2 hours ago. Try updating.

**Comment by nikheizen** [comment]
My bad. Thanks.
