### ISSUE TITLE
"Rings" of fuel in random places

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17390]
Sometimes mapgen spawns 3x3 blocks, with empty centers, made of gasoline or diesel. I suspect it could also happen with water.

It looks as if `vehicle::leak_fuel` was called on a car that didn't have proper coordinates set up.
`leak_fuel` is called by `vehicle::smash`, which is called by mapgen for smashed vehicles. At this point the vehicle doesn't have the coords set up yet, so fuel leaking shouldn't be called.

Apparently a similar bug was also happening with buckets. It doesn't happen at the moment because there are no buckets that spawn filled on mapgen. Back then it would sometimes cause yogurt to spawn near the fuel.

**Comment by Rivet-the-Zombie** [comment]
I've seen one of the puddles of guzzoline before, but at the time I figured it was the aftermath of something I'd done and forgotten about afterwards.

**Comment by TempestMaiden** [comment]
So _that's_ why I found those diesel puddles in the middle of a mansion. Had been wondering where they came from.

**Comment by BorkBorkGoesTheCode** [comment]
I thought those were some kind of trap.

**Comment by flitvious** [comment]
Cataclysm now has its own crop circles in red and green.

**Comment by nanovad** [comment]
I've seen these with water, diesel, and gasoline. Maybe it has something to do with leaky vehicle generation?
