### ISSUE TITLE
Overkill creates rotten meat

### ISSUE THREAD

**Issue by Priapism** [CleverRaven/Cataclysm-DDA#17399]
If you have high enough skill and a powerful weapon when you kill small critters they explode on death and throw a chunk of meat. I don't believe they used to be rotten chunks of meat, but now they are. Should be easy to replicate, spawn any overly powerful weapon and using high skill to utterly destroy any critter to replicate the effect.

**Comment by Xelat84** [comment]
Same happens to me few times.

**Comment by Rivet-the-Zombie** [comment]
Sounds like the meat fragments aren't having their creation time set properly.
