### ISSUE TITLE
Segfault when starting Really Bad Day

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17391]
Most likely caused in `start_location::burn`. Possibly only with Z-levels on.

Reproduces randomly. After few tries it generally works.

**Comment by Soyweiser** [comment]
Had the same problem with an infected start, normal house start.

**Comment by Coolthulhu** [comment]
Could be infection targeting a wrong body part then. For example, infecting a hp part when it should want a body part or vice versa.
