### ISSUE TITLE
Crash when moving specific amount of items counted by charges

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17396]
When trying to move from ground into inventory items that counted by charges through pressing "m" in advanced inventory window and entering specific amount - right after pressing "enter" game crashes.

If trying to explore that tile and take specific amount from "PICK UP" interface, everything works.

Build 5141,5144

**Comment by iavatus** [comment]
Seems the same issue, but includes ammo.

Version: 0.C-15980-g55e722e
Build: 5144
Clean world, clean char, no mods

Reproduce steps.

1: Wizard up 10 steel crossbow bolts
2: Open / item menu
3: Drop them on ground at same location. (No noticed difference with (d) menu)

4: Transfer 5 into inventory.

A: Game will crash.
OR
B: The remaining amount will disappear from the ground. (This seems to be what happens in vehicle cargo spaces, versus ground).

Tested on:
steel crossbow bolts
00 shot
pistol ammo
filled pistol magazines (DIDN'T OCCUR)
Shoulder strap (DIDN'T OCCUR)
Hand mirror (DIDN'T OCCUR)
extra battery mod (DIDN'T OCCUR)
Picked up the entire stack (DIDN'T OCCUR)

****

Conclusion: Seems to affect only items with charges - batteries, ammunition.
