### ISSUE TITLE
Even if you're driving, moving through sludge trails wastes moves

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#17405]
Version: 0.C-15980-g55e722e

To reproduce this:

- Spawn a vehicle and use the map editor to put 5 sludge trail fields in a line so that all of them will at some point be in the same location as the driver's seat when you drive.

- Drive.

- Watch in horror as you hopefully don't crash into any boulders/houses/etc.

**Comment by TheWebfrog** [comment]
So it spins your car out of control?

**Comment by Labtop-215** [comment]
This also happens when moving through water or traps on the ground if the traps slow down movement.

**Comment by sethsimon** [comment]
@TheWebfrog No, you just keep going the way you were going for awhile. One of my characters went 2 overmap tiles and crashed into a house, and that was at 10mph.

@Labtop-215 I didn't see any unexpected behavior when driving through traps or shallow water. But walking around in a car that's parked on traps or shallow water produces erroneous messages:
- `Moving past this shallow water is slow!` (but if it's on an aisle tile, there's no message or movement penalty)
- `Really step onto that sinkhole?` (saying yes has no consequences).
