### ISSUE TITLE
Canned ingredients aren't detected when crafting food

### ISSUE THREAD

**Issue by mightyagrippa** [CleverRaven/Cataclysm-DDA#17401]
When crafting food, certain canned ingredients aren't detected and aren't usable. If the canned ingredients are Unloaded (into another container for liquids, anywhere for solids) then the crafting interface does detect them. 

To replicate, wish for a steak knife, bread, and a container of red sauce. Attempt to craft a boring sandwich. I've checked this with tin cans of red sauce and canned chicken. Version was windows graphical build 5144, g55e722e.

In a build from 4 months ago, g0c7027b, this issue was not present.

**Comment by Soyweiser** [comment]
The bug of #17440 is probably related to this one. (Drink cans free in vending machines).

**Comment by mugling** [comment]
Long term breakage of lots of crafting recipes

**Comment by Coolthulhu** [comment]
They aren't really broken as they can still be unloaded, it just add an unnecessary step.

**Comment by mugling** [comment]
It's a pretty significant regression as those recipe show up as unavailable until you unseal the can at which point you can't go backwards

**Comment by busterbogheart** [comment]
Verified in exp 6045.

Checking recipes while on top of a can of red sauce, I noticed it shows as red.  Without moving or changing anything else, I pour it into a plastic bottle or open aluminum can, it shows green on the recipe.

Doesn't seem to affect things like cooking oil (in a gallon jug) or peanut butter (in a glass jar).
