### ISSUE TITLE
Inventory letters are sometimes incorrectly reported in the message area

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#17404]
Version: 0.C-15980-g55e722e
This is similar to #10165. A long time ago, it was closed as not a bug, but I disagree.

I started out with `m - plastic bag of pork sticks` and `n - plastic bag of potato chips` in my inventory. After eating the pork sticks, the message area reported `m - an empty plastic bag` (correct). Then I ate the chips and the message area reported `n - an empty plastic bag`, but in the inventory, no item was associated with `n` and the 2 empty plastic bags were associated with `m`.

If the message area reports something, it had better be accurate- the expected behavior is for the message area to report `m - 2 empty plastic bags` or something along those lines. It appears that this happens whenever there is already an empty container in the inventory.

**Comment by Coolthulhu** [comment]
Due to the way this bug works, it can't be fixed once and for all and may reappear for as long as we don't have strict inventory encapsulation.

**Comment by sethsimon** [comment]
It might be inelegant, but in `player::consume`, it looks like rather than simply removing the contents, removing the entire item, removing its contents, then adding the item back would fix this.

**Comment by Coolthulhu** [comment]
No, it just needs inventory sort/stacking/etc. invoked before printing the name.

**Comment by sethsimon** [comment]
That would work too, but both the position and the item reference would be invalidated by restacking, so that would need to be accounted for ( maybe via `visitable::items_with( item::stacks_with )` ). I'll try it both ways and go with whichever one looks clearer.

**Comment by sethsimon** [comment]
I was wrong about the reference being invalidated, but simply restacking and sorting after removing the item and before printing the letter doesn't solve the issue. It turns out that items in the same stack are allowed to have different letters, and only the letter of the front of the stack is used. So there are 2 ways to fix this issue:
- In `inventory::restack`, enforce a rule that items in the same stack must have the same letter (this way seems more appropriate). Is there a reason that there's never been a rule like that, or is it a remnant from the past?
- In `player::consume`, find out which stack `target` is in and print the letter of the front of the stack.
