### ISSUE TITLE
Recent Windows builds are missing the game executable

### ISSUE THREAD

**Issue by remyroy** [CleverRaven/Cataclysm-DDA#17422]
On http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/ , if you download the builds 5152 or later, you should notice a missing game executable in the archive.

**Comment by Rivet-the-Zombie** [comment]
That's definitely some new weirdness.

**Comment by Xelat84** [comment]
Probably because few last windows builds are failed.
http://ci.narc.ro/view/Cataclysm-DDA/job/Cataclysm-Matrix/

**Comment by kevingranade** [comment]
Circular definition of the executable name introduced by a recent feature I added to the makefile, just pushed a fix.

**Comment by kevingranade** [comment]
build 5158 successfully compiled win32/curses, I'm declaring mission accomplished.
