### ISSUE TITLE
Probably all window tiles should have flag SUPPORTS_ROOF

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17438]
Probably all window tiles should have flag `SUPPORTS_ROOF` in `terrain.json`.
Especially it affects building roof by hand, because once roof collapsed, sometimes you can't rebuild it back completely.
For example `t_window_frame` doesn't have this flag, while `t_window_empty` have it. And `t_window_frame` will turns into `t_window_empty` if broken.
Also for example `t_window_boarded` doesn't have this flag too, etc.

**Comment by BorkBorkGoesTheCode** [comment]
I think this was removed previously because zombies kept bringing the house down every time they attacked a player through a windowframe.

**Comment by Rivet-the-Zombie** [comment]
I seem to recall that. Sometimes they smack the window frame tile instead of attempting to crawl through it.

**Comment by Xelat84** [comment]
Then may be add another flag, which will be used in construction? So you can properly construct floor and roof.

**Comment by illi-kun** [comment]
We have a few similar issues open, so closing this as a duplicate.
