### ISSUE TITLE
Can't start vehicle construction, no more option in construction menu

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17443]
Have vehicle with welding rig, always used it to weld, also cart nearby with steel frames. When opening construction menu by pressing `*` there is no option `Start Vehicle Construction` at all.

Build 5165

**Comment by Soyweiser** [comment]
Was still working in 5163 for me.

**Comment by mugling** [comment]
Can reproduce

**Comment by BevapDin** [comment]
If you onto this, I assume it's because the requirement is initially empty and is therefor removed by the blacklisted-item-removal code. The actual requirement is added later based on a vehicle part flag.

**Comment by mugling** [comment]
Yes I'm on it and just found the problem described above in `finalize_constructions()`

**Comment by mugling** [comment]
Fixed by #17451 and #17487
