### ISSUE TITLE
Vending machines - Drinks in cans are free.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17440]
For some reason any drinks inside cans don't cost anything anymore in vending machines: http://prntscr.com/bnaagk .

This is new behaviour. They used to cost money at least up to 5032.

This bug is probably related to this one:  #17401

**Comment by BevapDin** [comment]
`visit_internal` in visitable.cpp always skips the content of items where `item::is_non_resealable_container` (not resealable and unseals into something) returns true.

This applies to aluminum cans.

As this check is deep inside the internals of the visitable interface, it applies to all items in all situations. This may have been introduced by 072bedf984616237d6232003d62b73897d2699b0. No idea how to fix it. It probably requires moving that check (where it's actually needed) into the callers.

**Comment by WizardOfOoo** [comment]
So this is fixed as far as I can tell. Close?
