### ISSUE TITLE
Refugee center - Broker selling, offering means you sell it.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17441]
No idea how to properly describe this one but in the refugee center, you have the broker who trades certain food items (like jerky) right? If you offer a food item to it. You automatically sell it: http://prntscr.com/bnahff . There should be an option b) "No, sorry that is not enough for me" so you can decline selling away your last food supplies by accident.

Right now you get no indication at all how much you get for selling the food, and when you offer it, it is automatically gone. Which is a bit odd. And not at all how trading works normally.

Another minor bug, there is no option to offer jerky made out of human meat. (jerk jerky). There should at least be a remark about trying to sell human meat.

**Comment by Coolthulhu** [comment]
The broker thing is horribly written and it needs to be redone from scratch.

**Comment by Soyweiser** [comment]
Yeah, was cheating my way into a location because I wanted to report something, but I cannot find that location anymore, so I guess that location was mod added. Just reporting some bugs I run into right now.

**Comment by Soyweiser** [comment]
I think the npc missions where you can offer items (the foreman quest line) has the same problem. If you have the items he needs and you chat with him.  You will give them, and they are gone forever. (which can mean you lose your welders, your first aid kits etc). Bit annoying. So I think that should also be fixed.
