### ISSUE TITLE
Match head bombs are free

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17442]
Minor issue but seems match head bombs don't have a value set:
http://prntscr.com/bnakth

(Yeah, I know, values of items are crazy anyways. But as long as I run into it, lets just report it).

They do have a value when you sell them. No idea what is up.

Same with sinew. Also free, and offered by a trader at the refugee center. (An easy quick fix would be to just look at the way value of the trade is calculated, and if the npc offers it for 0.00, just set it to 1 dollar and if debug mode is on, log a debug message).

**Comment by DLaboratory** [comment]
![1](https://cloud.githubusercontent.com/assets/5671495/17022607/84f66390-4f81-11e6-9a69-9f0d0ca19df8.png)

I don't have this problem here, the price of match head bombs are 4.5$.

**Comment by Soyweiser** [comment]
Well that is odd.

**Comment by WizardOfOoo** [comment]
I just tried to trade one to my starter NPC and he offered me about five bucks.

![image](https://cloud.githubusercontent.com/assets/17521661/22729584/fde03a22-eda8-11e6-9be2-0a90eab97039.png)


I think maybe your PC just had low social skills.  Or lower then the NPC?

**Comment by WizardOfOoo** [comment]
Close this?
