### ISSUE TITLE
Construction results incorrect. For example: a makeshift bed selection creates a sign.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17449]
In 5166, if you build a makeshift bed. It places a sign. Building a bench creates a sofa. Bulletin board ->  cupboard. I have not tested them all, but im going to assume most of them are broken.

Probably related to #17443 

Pits create pits as normal though.

Reported first here: https://www.reddit.com/r/cataclysmdda/comments/4qr0h0/signs_are_the_new_beds/?st=iq3m6h38&sh=d479b324

**Comment by mugling** [comment]
Fixed by #17451 and #17487
