### ISSUE TITLE
Best way to suggest fixes in buildings.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17459]
A lot of buildings have small problems (no roofs for example). Or the pumpstations fences being load bearing. (Smash one, and the roof comes down on you, seen here: http://prntscr.com/bnm6cv).

What is the best way to report or fix these issues? (Is there a Z-levels tag for example, or a map generation tag?).

**Comment by Coolthulhu** [comment]
We don't have a good way of telling apart roofed tiles and tiles that bear roofs. I'm afraid the proper fix would involve splitting the terrain into walls and floors (like in Dwarf Fortress).

**Comment by Soyweiser** [comment]
Right that is a different issue then. And a lot more work.
