### ISSUE TITLE
Silver/gold deconstructions yields inconsistent. 

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17464]
if you deconstruct a tie clip (0.1kg) you get 100 silver (0.3kg). 
A silver necklace (0.3kg) gives 100 silver (0.3kg). 
Silver earring (0.01kg) gives 60 silver (0.2kg). 
And the silver bracelet (0.04kg) gives 260 silver (0.8 kg) when deconstructed.  
And finally the big silver bar (4.83kg) gives 800 silver (2.4 kg). 
(there are several more: http://cdda-trunk.estilofusion.com/silver_small )

Gold items have similar weight related problems. *http://cdda-trunk.estilofusion.com/gold_small )

(have not looked at volumes or prices).

On the other hand, the collar pin. (made out of silver 0.01kg). Cannot be deconstructed at all.
A pocket watch (made out of glass and gold), deconstructs into 2 scrap metal and 1 clockworks.
And there are probably more items listed as being made out of gold or silver that either cannot be deconstructed, or don't give silver/gold when you do deconstruct them.

Sure these are minor issues. But should be an relatively easy task to correct the various json files to make the yields a bit more mass conservative. (I do not suggest also fixing the various ammo reloading recipies as that would be a bit odd. Just keep that in for game balance sake).

Note: this issue came up when I was disappointed you could not deconstruct collar pins, and the pocket watch not allowing me to create more ammo. And the frustration of going overweight after deconstructing a silver bracelet.

Yeah there are more conservation of mass issues. (A newspaper being volume 0 and the 2 paper yield being volume 1 for example) But this felt more pressing as it concerned the fancy high value items. Which i'm going to assume people would collect or store as 'loot'.

**Comment by Zaweri** [comment]
Yeah, oversight by me.

**Comment by Soyweiser** [comment]
No problem. Might be able to fix it myself, if I can ever get it to compile locally. Hope you are doing well Zaweri.

**Comment by Zaweri** [comment]
I am, thank you @Soyweiser !
