### ISSUE TITLE
Triffid queens create a lot of wood.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17467]
See this : http://prntscr.com/bno5z6 (I was standing on the roof, and had the queen run around a bit (it also trashed a car).

This was only one triffid queen. Normally several of them spawn, so they all create a lot of junk wood in your reality bubble. Perhaps this should be toned down. Or just make the queens special attack not create wood when it breaks trees. Otherwise queens will negatively affect game performance. (pressing V already lags in that location)

**Comment by Leland** [comment]
Looks like discussion has stalled on this topic. Closing. If there's still interest, let me know and I can reopen.
