### ISSUE TITLE
Lab barracks spawn without socks.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17466]
Minor issue, but I discovered that the lab sides, the barracks, always spawn with lockers filled with soldier clothing. A full set of clothes except one. Socks.

http://prntscr.com/bno3rj (No helmet as well this time, but they do spawn. Socks otoh do not).

(yeah minor issue, I know. I'm just working through, and confirming a list of small bugs/inconsistencies I found while playing).

**Comment by illi-kun** [comment]
Yes it's minor one but it's still an issue and it worth to be reported, so keep reporting such inconsistencies.

**Comment by nanovad** [comment]
According to item_groups.json, the socks do spawn. They're about as rare as bras. Either it was just chance that no socks spawned or the bug isn't an easy fix.

**Comment by Soyweiser** [comment]
Odd, as I teleported/played around a lot in the barracks, never found them. (I meant the barracks side thing, with the soldier clothing and weapons). Not the normal sleeping quarters.

**Comment by Soyweiser** [comment]
Looked in clothing_soldier_set that set does not seem to have socks in them.

`      { "group": "clothing_soldier_shirt" },
      { "item": "jacket_army" },
      { "item": "pants_army" },
      { "item": "boots_combat" },
      { "item": "helmet_army", "prob": 20 },
      { "item": "gloves_tactical", "prob": 10 },
      { "item": "elbow_pads", "prob": 10 },
      { "group": "clothing_tactical_leg", "prob": 15 },
      { "group": "clothing_tactical_torso", "prob": 15 },
      { "group": "underwear" },
      { "distribution": [
        { "group": "clothing_glasses", "prob": 60 },
        { "item": "glasses_bal", "prob": 30 },
        { "item": "goggles_nv", "prob": 5 },
        { "item": "goggles_ir", "prob": 5 }
      ], "prob": 20 },
      { "group": "clothing_watch", "prob": 5 }`
