### ISSUE TITLE
Creating dehydrated/canned veggies out of sacs is too efficient.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17465]
Fluid sacs (from triffids) give 4 nutrition and 18 quench. Which is fine, it is a good source of hydration if you cannot find any other source. (which can be hard on some maps).

But for the amount of nutrition it gives it can be converted to easy into higher nutrition sources. (with high cooking skill and items). 6 sacs (6x4= 24 nutrition input) becomes 2 dehydrated veggies. (40 nutrition). Add water, 44 nutrition total.

A canned veggy gives 28 nutrition for 3 fluid sacs (12) and one water.

My suggestion make the input 8 sacs. So 32 nutrition becomes 44 max. (Re/dehydrated veggies also have a lot of other usages. So making the input of sacs higher, reduces the ease of going around other food requirements in recipes. Where re/dehydrated veggies can be used instead of potatoes etc. http://cdda-trunk.estilofusion.com/dry_veggy/recipes/CC_FOOD see here for a list of dehydrated veggie recipes).

This makes it a bit harder to sidestep various food requirements, and makes a triffid grove nearby not a replacement for farming/scavenging of food.

Or, if you want to go a different route. As fluid sacs are created by triffids, and triffids also create plant marrow, and plant marrow can be used just like wild veggies in most of the recipes. Remove the conversion from fluid sacs into dehydrated/canned veggies.

Fluid sacs already never spoils, and is a good source of water. So to make them the easy to convert into nutrition (which also never spoils) is not a perfect game balance. (Of course for the conversion you ideally need a foodco vehicle which is at risk from a triffid queen, however slightly (easily dodged by not parking nearby of course)).

**Comment by Coolthulhu** [comment]
> Remove the conversion from fluid sacs into dehydrated/canned veggies.

I'd just go with that one.
This would make fungals less grindable (fungals drop those too), making the difference between fungals and triffid that one bit more pronounced.
A dried fluid sac would probably not be too palatable, as it would be mostly just a membrane with some oil in it anyway.

It may be a good idea to have a recipe to drain the fluid into containers.

**Comment by Soyweiser** [comment]
Well, fluid sacs can also be used to create cooking oil. So I think that is what happens when you dry it out.

**Comment by pisskop** [comment]
Fluid sacs should be having a chance for parasites, no?

**Comment by Coolthulhu** [comment]
> Fluid sacs should be having a chance for parasites, no?

The description clearly states they are safe to consume.

**Comment by Soyweiser** [comment]
Could be, I have no idea how that is handled. Dunno if triffids/fungals should have parasites. (fungals probably should have, dunno about triffids, currently they drop the same item. We could add that meat/plantmarrow etc remembers where it came from (like other roguelikes have 'corpse of X') which could make the parasites thing more interesting).

Ninjad by coolthulhu. Yeah... and that, the description. But we could change that. Dunno, triffids/fungals are already annoying enough, getting food of them is a bit of a benefit.

**Comment by pisskop** [comment]
descriptions are capable of change.


if the attempt is to make them less grindy than requiring preperation is a good way.

as well as making them rot over a period  of time.


i dont think a fresh source of water would be free of parasites.  if youd argue they are alien id argue theyd have foreign parasites

**Comment by Soyweiser** [comment]
Well, my pr fixes my issues I had with the sacs. Pisskop want to continue the discussion about sacs here? Or shall I close it?

Well, we already have alien parasites, being the blob right ;). But yeah, I think fungals should have parasites, but the triffid ones should not.

**Comment by pisskop** [comment]
close it
