### ISSUE TITLE
Mapgen: Some buildings don't spawn by a road

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#17475]
Most of the time, it's mansions, but I've also seen it with evac shelters, apartment towers, FEMA camps, military outposts (intended?), schools, and toxic waste dumps (intended?). I have screenshots if anyone is interested.

**Comment by pisskop** [comment]
Mansions and toxic dumps have no requisite to spawn next to a roadside.  In fact, there are versions of these that are made just so they dont.

Schools should always have a road connecting to their front (its in their coding to) and so should FEMA camps.


However, Ive seen fema camps without roads, in vast open fields.  Once or twice.  So Id imagine if there are simply no roads around, none can be connected.

**Comment by sethsimon** [comment]
>Mansions and toxic dumps have no requisite to spawn next to a roadside. In fact, there are versions of these that are made just so they dont.

Okay, no wonder mansions are the most common culprit.

>So Id imagine if there are simply no roads around, none can be connected.

That could be the reason for some of the instances. But take a look at this school:
![bug_school_nowhere](https://cloud.githubusercontent.com/assets/16765166/16547121/ebd00ada-4130-11e6-91e1-a22b778236ea.png)

Also, it looks like rivers may interfere:
![apartment_nowhere](https://cloud.githubusercontent.com/assets/16765166/16547130/5db7d786-4131-11e6-8f20-fab643c4032e.png)
