### ISSUE TITLE
Some doors are locked from all directions

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#17473]
Version: 0.C-16132-g9626f2c

Here are some examples:
- The doors in apartments that lead to the hallway
- The southeastern door in houses that have this layout:
  ![locked_house](https://cloud.githubusercontent.com/assets/16765166/16536601/da7e6c56-3fc1-11e6-8db5-7934e1094839.png)
- Find a house whose front door is locked (don't touch that door from the inside yet!). Grab a sledgehammer and collapse part of that house by the front door. Clear the rubble. Then try to open the door from the inside.

**Comment by Coolthulhu** [comment]
There is no inside once the house collapses.

**Comment by sethsimon** [comment]
I guess I meant the former inside.

**Comment by Coolthulhu** [comment]
I don't think there is a good way to fix it.
Having a different type of door for each locked side would be an inexcusably horrible hack, there is no good way to store direction data in map objects at the moment and it doesn't change much.

The best solution I see here would be wrecking all wooden doors adjacent to falling roof.

**Comment by sethsimon** [comment]
Okay, then this is a long-term issue. The apartment example is pretty important as it could kill someone who goes there on day 1.

**Comment by Coolthulhu** [comment]
The collapsing roof itself is a much more dangerous thing than the way it affects doors. It isn't important at all.

**Comment by sethsimon** [comment]
>The ones in apartment are intended - they are supposed to be locked.

Right, but from all 8 directions? I don't know what kind of doors they'll have in the future, but I'd imagine that they'd be pretty similar to today's doors.

> Not sure about the one near the glass room/patio/thing.

It's probably locked from all directions because the terrain on the patio is floor instead of dirt/grass.

**Comment by Treah** [comment]
I have come across some doors in houses that are locked when trying to open them from the inside. After getting into the house from a window the front door is locked from the inside. However this is not uncommon IRL since there are some doors that you cannot open without a key either way. I have one such door in my house so I figured this was intended.

**Comment by illi-kun** [comment]
I see no issue here. Please let me know if I wrong.
