### ISSUE TITLE
Eating a broken skitterbot with Internal Furnace recharges 6973 bionic power

### ISSUE THREAD

**Issue by Izicata** [CleverRaven/Cataclysm-DDA#17479]
Should you even be able to burn something made of plastic and steel? Regardless, just under 7000 power is probably way too much.

**Comment by Soyweiser** [comment]
Now im wondering, how much time did that take? Did you really just eat a whole skitterbot in 250 turns? (aka, 15 seconds)?

**Comment by Izicata** [comment]
Yup. 250 moves, just like everything else.

**Comment by AppleConnoiseur** [comment]
This is a funny mental image. Just like shoving an entire tree log into your artificial chest cavity.

**Comment by Mecares** [comment]
Perhaps a maximum size should be implemented. I doubt anything above 10 volume could be easily burned by the internal furnace.

**Comment by Soyweiser** [comment]
Well, most large items can also be desconstructed or cut up into smaller parts right? So that could work. I wonder if we could then also implement a  "you cannot eat it now, cut it into pieces/deconstruct it? And then eat the parts?" long action implementation.

**Comment by Leland** [comment]
Looks like discussion has stalled on this topic. Closing. If there's still interest, let me know and I can reopen.
