### ISSUE TITLE
Roadside foodcart in the middle of the road

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#17476]
On the left side:
![bug_roadside_foodcart_blocking_road](https://cloud.githubusercontent.com/assets/16765166/16537585/a7b842e8-3fd4-11e6-9c62-6f5f9ac93dc8.png)

It probably shouldn't try to spawn next to bridges.

**Comment by Oskar636** [comment]
This needs the mapgen label.

**Comment by illi-kun** [comment]
@Oskar636 thank you for help!

**Comment by Oskar636** [comment]
Just trying to help with the 1000 issues :P.

**Comment by Leland** [comment]
Marking as confirmed due to #19533, but closing as well due to lack of repro for devs. Been playing a lot and have literally never encountered this. These issues are also seriously old.

If anyone hits this again, please make a new issue with savefile included.
