### ISSUE TITLE
Make towns have signs to display town or city names.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17482]
A little known feature. (outside of people who read the map files), is that all towns have (and always had) names. This is where the strange name in morgue files comes from "died on a road in Morguesville".

Could we make these town names more visible? We could put down the signs #7952 just like next to minefields.

I however don't know how the city map generation system works. The most realistic way to implement it would be to have 'Welcome to McUristsburg' sign next to the road when you enter a town. But even just adding a sign in the middle of town (Assuming the map generator only picks a starting point for the town, and radiates out from there) would at least make the different cities and towns slightly more memorable.

(If a system like this is implemented, and we can actually recognize towns, we could even have npcs reference stuff. "McUristburg has a bank. Where is McUristburg? To the south west.". Without marking it on the map).

**Comment by Zireael07** [comment]
I believe this has already been discussed on git, but I can't find the issue  atm.

**Comment by Soyweiser** [comment]
Yeah, I was also looking for it. Could not find it.

**Comment by Leland** [comment]
Looks like discussion has stalled on this topic. Closing. If there's still interest, let me know and I can reopen.

**Comment by Leland** [comment]
PS future reference: the old discussion that @Zireael07 was talking about lives in #19292

**Comment by codemime** [comment]
I'm reviving the topic as I'm interested in implementing this feature.

**Comment by Night-Pryanik** [comment]
We have cities names on the overmap UI, so basically this issue is resolved.
We could add signs with cities names too, but I think there's no need to keep a separate issue for this.
