### ISSUE TITLE
Construction suggestion box not showing up in tiles version.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17488]
In the console version when you try to deconstruct something you get this: http://prntscr.com/bnxsrl see the highlighted window, and the highlighted benches. (Build 5032)

In the tiles version this is how it looks: http://prntscr.com/bnxtl9 (And the same in retrodays: http://prntscr.com/bnxtwe so it probably isn't a tileset problem (examples from build 5163)). So the small feature of showing players where you can do something is gone in the tiles version.

(This example uses deconstruction. It think the problem shows up in more locations. And I have no idea how to properly call this problem. So feel free to give a better suggestion for the title so it is searchable).

**Comment by Leland** [comment]
Closing in favor of #6308 - see @kevingranade's [note here](https://github.com/CleverRaven/Cataclysm-DDA/issues/6308#issuecomment-36146967) specifically.
