### ISSUE TITLE
add_zombie: there's already a monster at 12,77,0 (5092)

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#17483]
cataclysmdda-0.C-5092
horde is on.

after using stairs to go back up to town:

Debugg: add_zombie: there's already a monster at 12,77,0
FUNCTION : bool Creature_tracker::add(monster&)
FILE : src/creature_tracker.cpp
LINE : 68

Press spacebar.... and it let me play

**Comment by pisskop** [comment]
The game doesnt allow itself to place more than one monster on any given tile.

You can when debugging, place one on youself, but the game will always generate a 'bad spawn' debug message when it attempts to place a monster onto another preexisting monster.


That is another reason that wasps dont actually exist anymore.  Or slugs, or grubs, or all the little vermins.

**Comment by Coolthulhu** [comment]
Can be either hordes or stair monsters.

**Comment by Soyweiser** [comment]
I noticed stairs (with Z-levels on) to be way less of a problem nowadays. ZenZen2 did you enable Z-levels (as in, does the game simulate other Z levels when you play? Can you hear the Z's making sounds below and above you?).

I wonder, and have wondered about it before, when a add_zombie (or any add_monster) function fails, is the Z deleted from play?

**Comment by ZenZen2** [comment]
I didnt enable Z-levels.
I also didnt see any Zombie after the debugg message. I went down again, moved a few steps around the stairs and went up again and the Debug message came again. But i dont know if the coordinates were the same.

**Comment by Soyweiser** [comment]
Hmm, if you perhaps have a save game in which it is reproducable that would be nice. So the whole 'do they disappear' thing can be tested. (and what causes it. In some cases it is expected that stuff cannot be placed and the Z should be pushed back into the horde, or just wait a turn moving up).

**Comment by ZenZen2** [comment]
I didnt make a save game, but i wil do one when it happens again.

**Comment by mugling** [comment]
Generic error message with multiple causes. No clear path to resolution
