### ISSUE TITLE
The magazine distinction removal mod is broken

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#17489]
The mod that removes distinct magazines breaks magazines to where you can load them but are unable to load them into the guns themselves, requiring you to load every bullet individually.

**Comment by Taberone** [comment]
If it helps, I can also confirm that it was broken(At least last time I played CDDA). Having to slowly and painfully reload guns one bullet at a time is annoying to the point where just using the debug menu to give myself a magazine every time I pick up a gun without a magazine is a better option.

**Comment by mugling** [comment]
You can try `left` and `right` arrows to adjust the reloading amount. This needs to be more intuitively documented to the player but I'm not sure how to go about doing so.
