### ISSUE TITLE
Ambush scenario can't create start location

### ISSUE THREAD

**Issue by codrus** [CleverRaven/Cataclysm-DDA#17491]
Version: cataclysmdda-0.C-5174

When choosing the 'Ambush' scenario the game is unable to create a suitable start location. I tried it for all three professions on two different worlds.

**Comment by kevingranade** [comment]
Confirmed as of 0.C-21861-g965b631
Overmap generation has issues finding somewhere to stick cabins.

**Comment by Coolthulhu** [comment]
Technically not fixed yet, but now it should be rare enough not to matter.

**Comment by Leland** [comment]
@Coolthulhu gave this one a go across City Size from 1-16 and City Spacing from 0-8 and the scenario was able to find a location.

This is, of course, not an empirical study – but at the very least this scenario can repeatably spawn at all possible world options. (Save City Size: 0, see https://github.com/CleverRaven/Cataclysm-DDA/issues/21667).

For now, closing. Let me know if that's too hasty.
