### ISSUE TITLE
Memorizing recepies from books bug

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#17506]
Build 5177. Tiles Windows X64

- Get character with survival 0;
- Get book "Outdoor adventures";
- Read book "Outdoor adventures" to raise survival to level 1;
- "Outdoor adventures" contains recepie "fish bait - meat" that is not memorised yet. Book marked with yellow color in inventory;
- "Fish bait - meat" has difficulty  1 and use only survival as skill. You have access to it using book but that recepie is not memorized yet;
- Try to read book again. You will see "It would be fun, but it will not increase your survival";

Expected:
"This book contains unlearn recepies. Read it unitl you learn recepies"?

As far as I remeber you should get special message if you can read book to memorize recepies. For now I don't see that message for any book that marked with yellow color in inventory.

**Comment by Zireael07** [comment]
Books no longer grant recipies. You learn recipies via attempting to do them.

**Comment by mugling** [comment]
Not widely published enough but yes @Zireael07 has the correct answer to your question
