### ISSUE TITLE
Flaming Eyes can Stare at you through vehicle security cameras

### ISSUE THREAD

**Issue by Izicata** [CleverRaven/Cataclysm-DDA#17501]
Even if they shouldn't be able to see you because there's a LoS blocker in the way, they can still use their special on you if you can see them through the security camera. Possibly worth leaving in, just for the spooky value.

**Comment by BorkBorkGoesTheCode** [comment]
This should be kept.

**Comment by Soyweiser** [comment]
Perhaps detect it, and add some additional message part about staring into the abyss, and the abyss stares back?

**Comment by illi-kun** [comment]
This is a duplicate of #13491 (due to passed visibility check).
