### ISSUE TITLE
Zlave stashing should be possible with directional drop

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17519]
Having to examine zlaves just to stash stuff on them is pretty annoying.
Advanced inventory menu could also be updated to support them.

**Comment by nanovad** [comment]
Perhaps then this could be used to attempt to give things to NPCs - but replies would have to be sent as a message, and that seems likely to fragment NPC message code.

**Comment by Coolthulhu** [comment]
> but replies would have to be sent as a message, and that seems likely to fragment NPC message code.

NPC dialogue code is inter-dependent, but simple messages and queries can be sent without it.
For example, when sorting NPC's armor, you can attempt to take off their armor. If it fails because the NPC doesn't like you, it will open a regular popup, not a proper dialogue.

In this case it could be just a warning message like "Schlomo Silverstein refuses to take the gold bar: \"I'm overburdened, I can only carry 0.5kg more\"". Similar to how putting too many things in a cargo container will just result in "it falls through".

**Comment by kevingranade** [comment]
The reason this is restricted to an iexamine is to prevent this special case from spreading throughout the code.  In order to handle this properly it needs some kind of system where game entities can register themselves as drop/pickup targets, which is also the right thing (tm) to do for the rest of the code as well.

**Comment by Fris0uman** [comment]
Zlaves no longer exist so this should maybe get closed or refluffed to point at pet inventory in general?

**Comment by kevingranade** [comment]
Eh it's a random and ancient feature request, it should have aged off a long time ago.
