### ISSUE TITLE
Putting on/taking off dust mask takes next to no time

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17510]
The wear cost formula places way too much weight on volume.

**Comment by Rivet-the-Zombie** [comment]
It really should matter more which body parts it covers and what material it's made of.

**Comment by mugling** [comment]
Is the pun intentional?

**Comment by Breligar** [comment]
Likely too complex, but perhaps removal/wear times could be based on a combination of:

1. Location covered (hands and head could be quick, but taking off something covering your torso could take more time)
2. Amount of locations covered (something covering your arms, torso, and legs could be quite involved to put on/take off compared to something that just covers the torso)
3. Layer (something strapped on could be quick to put on/take off, but something normal/skin-tight could take longer)
4. Percentage of coverage (so something that covers your torso 100% like a flame-resistant suit would be harder to put on/take off than something that covers it only 10-20%, like a bra).

**Comment by pisskop** [comment]
Cant there be a modifier for json?

**Comment by bumpkindda** [comment]
> something that covers your torso 100%, like a flame-resistant suit, could be harder to put on/take off than something that covers it only 10-20%, like a bra

Add a +100% time taken to remove bras for male characters. +100000% if they roll otaku.

**Comment by kevingranade** [comment]
I agree with all your points Breligar, except gloves, they're often quite a pain to put on or remove compared to other clothing.  Maybe I just wear really tight gloves.

**Comment by mugling** [comment]
> Cant there be a modifier for json?

Painful to balance considering the number of items we have and should be reserved only to override a sane default input to the algorithm.
