### ISSUE TITLE
Bionic charger cable keeps draining energy even when full

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17515]
Quoted from the forums (http://smf.cataclysmdda.com/index.php?topic=12878.0):
"The cable charger bionic still draws power from vehicle batteries even when the player's bionic power is full.

If this behavior is intended, some warning would be appreciated - because plugging in before going to bed seems an obvious idea, otherwise.

If it's not intended, it would be nice if an active cable left in the bed could be counted for charging purposes, so the player doesn't have to manually pick it up every night and put it down every morning."

Confirmed it on 5166 with a shiny cable. It indeed drains the battery while you are already full and not draining power any other way.

Another small feature request, it seems you cannot drain power using the cable system from a car battery you are holding. Perhaps we could make it that you can 'eat' a car battery and then the charges are drained. I however think that might be a bit of a dirty hack.

**Comment by Xelat84** [comment]
It would be awesome too if your cable will not disconnect from car you are driving.
