### ISSUE TITLE
Vehicle smoke bugged

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17529]
It looks like vehicles creates not light smoke but very dense fog, which stays for very long time. It's very annoying and tedious.
Last tested build was 5194.
It works well at least in build 5116.

**Comment by mugling** [comment]
Does the engine have any faults as a broken air filter intentionally causes that?
Is the vehicle in an enclosed space as that's semi-intentional if so
Otherwise report back as I'm working on smoke balance at the moment.

**Comment by Xelat84** [comment]
@mugling Nope! No faults. Engine is brand new, whole vehicle crafted from scratch. Vehicle in open space, no trees, only bushes (ranch fields).
When I drive the roads, and then back to same place after few days, smoke that my car left is still here!

**Comment by mugling** [comment]
Precisely how long as days seems implausible.

**Comment by Xelat84** [comment]
@mugling Probably it's because while I'm drivinig "chunk" was unloaded before smoke is gone, as I'm driving 64-96 km/h. Especially for you I recorded test. :)
https://youtu.be/w7f3dkdoK-s

**Comment by mugling** [comment]
Ah, that's a problem with reality bubbles then and beyond the scope of #17530

**Comment by Xelat84** [comment]
> Ah, that's a problem with reality bubbles then and beyond the scope of #17530
Only related to smoke stays for days. But anyway, previously vehicle smoke was disappearing just in few steps, now it takes few minutes to disappear, and probably spawn more clouds of somke.

**Comment by mugling** [comment]
The latter is resolved in #17530 in which I've reduced the half-life by a factor of 5 and somewhat increased the diffusion rate

**Comment by Xelat84** [comment]
@mugling Oh, fine then! Thanks!
