### ISSUE TITLE
Cannot get money back from automated gas console

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17545]
Cannot `Refund cash` from `automated gas console` if I already bought all fuel. It says `This station is out of fuel.  We apologize for the inconvenience.`. But in the pump there a lot of fuel left.

**Comment by mugling** [comment]
Also cannot trade with NPC's. Possibly related?

**Comment by Xelat84** [comment]
@mugling you mean when they don't have anything to sale?
But anyway it's a definitely separate pieces of code. Automated gas console just need to modify some checks in `iexamine::pay_gas`.

**Comment by pisskop** [comment]
If you buy all the fuel it doesnt return a refund.  This has happened to me in versions past.

Once you buy it all, its bought, but if you left some in it there isnt.

**Comment by Soyweiser** [comment]
So the problem is that the automated gas console shuts down when you still have cash uploaded to the station?

Think the cashstation should not accept more cash than there is fuel inside. No, wait, that will of course break when you hack the station to get lower prices.

**Comment by Xelat84** [comment]
> Think the cashstation should not accept more cash than there is fuel inside.

No, it works different. You buy fuel, it transferred into pump from underground storage. Then you can take as much fuel from pump as you want from amount available in pump. But if some fuel left in the pump, you can take your money back for that fuel, and then fuel from pump will be removed back into underground storage.
