### ISSUE TITLE
Dropping support of heavily outdated versions

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17558]
The code is peppered with support for legacy versions older than 0.A.

Can we get rid of that?

**Comment by mugling** [comment]
I presume you mean the savegame code?

**Comment by codemime** [comment]
Does it actually work (the support)?

**Comment by Coolthulhu** [comment]
I didn't test it. It's most likely bitrotten into uselessness, though there is a chance that it still works.
There is no real reason to even test it, though. Why would anyone try to load a pre-0.A, binary save?

**Comment by illi-kun** [comment]
I guess it's okay to drop save support for pre-0.A versions before 0.D release, and drop support of pre-0.B versions after 0.D release.

**Comment by illi-kun** [comment]
I guess it's okay to drop save support for pre-0.A versions before 0.D release, and drop support of pre-0.B versions after 0.D release.

**Comment by mugling** [comment]
> Why would anyone try to load a pre-0.A, binary save?

Even if they did they could 'convert' it through the last known good version (which you should demarcate in the documentation).

> It's most likely bitrotten into uselessness,

That said yes it's probably broken anyway

**Comment by mugling** [comment]
@Coolthulhu see also #16176

**Comment by BorkBorkGoesTheCode** [comment]
This should be delayed until after 0.D.

**Comment by mugling** [comment]
> This should be delayed until after 0.D.

Why?

Note the comment in #16176

> the current goal is to load saves generated by the latest stable release

That would be 0.C which was JSON. It's a completely different format for preceding versions.

**Comment by nanovad** [comment]
My two cents here anything older than 0.C support should be dropped, leaving only 0.C and current savegame compatibility. Anybody that has an old (pre 0.C) savegame could probably either play with an old version of the game or wouldn't mind losing the world entirely.

**Comment by kevingranade** [comment]
Perfectly fine to drop 0.A save support any time, 0.B support can be
dropped as well if it causes any problems, but I'd prefer to keep it until
after 0.D unless it actually causes problems (or is broken anyway).

**Comment by keyspace** [comment]
Issue could assigned to `0.D` milestone?..

**Comment by kevingranade** [comment]
> it's a post-0.D activity, not a 0.D blocker, which is what the milestone tag is for.

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
