### ISSUE TITLE
Player fatigue/sleeping weirdness

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17550]
A lot of times I have weird issue. When night has come, I'm trying to sleep, but my caracter didn't want to. Of course I'm doing this staying over the bed with blanket and pillow laying in the same tile, and there is darkness around. I continously attempt to sleep till the morning, and then, when sun has risen and I change my mind about sleeping, right few minutes later my character became tired (`Fatigue`) and wants to sleep. It's very very strange and annoying!

So, if he didn't want to sleep all night, he don't have to right at the morning. Probably there should be some bounds like `he want to sleep` and `he will sleep`, and between them player should not be noticed about `Fatigue`, but catacter should sleep if you ask him.

Also Friendly NPC if following you, should try to sleep when you going to sleep, even if he still didn't want to, like example above, because right when I'm awake (or very close to), he going to sleep.

**Comment by Rivet-the-Zombie** [comment]
>A lot of times I have weird issue. When night has come, I'm trying to sleep, but my caracter didn't want to. Of course I'm doing this staying over the bed with blanket and pillow laying in the same tile, and there is darkness around. I continously attempt to sleep till the morning, and then, when sun has risen and I change my mind about sleeping, right few minutes later my character became tired (Fatigue) and wants to sleep. It's very very strange and annoying!

That sounds like a crappy sleep pattern, but not anything that I'd call a bug.

**Comment by Coolthulhu** [comment]
There is a bug that could cause it, though: lying in bed and trying to sleep currently stops fatigue accumulation.

**Comment by Rivet-the-Zombie** [comment]
> lying in bed and trying to sleep currently stops fatigue accumulation

Well that's plumb ridiculous.

**Comment by Soyweiser** [comment]
Perhaps it was some sort of 'well you try to sleep, so at least you should be getting some fatigue back' idea. Without thinking about what the final effect would be.

**Comment by Labtop-215** [comment]
I thought that was a trait of insomniacs.
