### ISSUE TITLE
Alternators can't be uncrafted

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17566]
Recipes for them exist, but apparently aren't read.

**Comment by mugling** [comment]
I'll claim that as I implemented the uncrafting recipes. I'm not sure why they aren't read though.

**Comment by BevapDin** [comment]
The recipes in data/json/uncraft/vehicle/alternator.json don't have any "reversible" member and its default is false, so the items are not uncraftable.

**Comment by mugling** [comment]
I might special case `CSC_UNCRAFT` to set `reversible` true?

**Comment by kevingranade** [comment]
> I might special case CSC_UNCRAFT to set
> reversible true?

Let me translate, "I want to use a ui label to imply semantics of a game
entity". Hopefully this makes it clear that it's a bad idea.

**Comment by Coolthulhu** [comment]
Though explicitly specifying uncraft recipes in some way sounds like a good idea in itself.
Something like `"uncraft": true` implying reversible, non-reverse-learnable, non-autolearnable and non-booklearnable and throwing (or just warning) on any recipes that try to be both uncraft and learnable in any way.

**Comment by mugling** [comment]
@kevingranade it's already a bad hack expressing item disassembly in this manner. At present you have to know the magic combo of settings to make it work and- I want to try and reduce future breakage by limiting the potential for invalid configuration.
