### ISSUE TITLE
No security system found

### ISSUE THREAD

**Issue by jarmush** [CleverRaven/Cataclysm-DDA#17569]
Get this message when try to turn off alarm in a car

![2016-07-06 14-26-58](https://cloud.githubusercontent.com/assets/6452938/16616414/37217c58-438e-11e6-894d-db8449a8432f.png)

**Comment by nanovad** [comment]
Can confirm, version 0.C-16410-gd490646.

**Comment by Oskar636** [comment]
In build 5681 when you attempt to turn off the alarm and fail you damage the controls, not the security system so you can't destroy it - the debug message doesn't appear.
