### ISSUE TITLE
Too Bright to Sleep in Vehicles

### ISSUE THREAD

**Issue by Breligar** [CleverRaven/Cataclysm-DDA#17561]
Reference topic discussion:

[http://smf.cataclysmdda.com/index.php?topic=12894.0](url)

Currently, despite there being vehicle options such as Roofs, Boards(Walls), Aisles(Floors), Curtains, Aisle Curtains, and Opaque Doors, all designed to create an enclosed space that blocks line of sight/line of effect, none of these options appear to block light well enough to allow uninterrupted sleep during daylight hours. The best option as it stands seems to be wearing a blindfold, which tells me the in-system vehicle options simply don't work, aren't working well enough (possibly intentional? Though I don't see a reason to deny sleeping in properly-designed vehicles), or aren't working in a way that is intuitive enough for the player to utilize them effectively.

Possible simple fix would be to allow a "Bed Curtain" or something similar that blocks light around the bed, either permanently or when opened/closed.

**Comment by illi-kun** [comment]
Closing as a duplicate.
