### ISSUE TITLE
[MSYS2] COMPILING.MD guide to MSYS2 incomplete

### ISSUE THREAD

**Issue by mightyagrippa** [CleverRaven/Cataclysm-DDA#17565]
It's excellent but missing a couple things. I just finished following it from ignorance to successful build and here are a couple gaps I saw.

Windows users will probably need to add the proper /bin directory to their path. The "Environment Settings" part of http://www.mingw.org/wiki/getting_started was really helpful to me here. Problems here produce a runtime error about a missing libwinpthread-1.dll, then a new runtime error for a different dll if you fix the problem with a copy paste into the main directory, etc, etc, etc.

On step 9, make requires a DYNAMIC_LINKING=1 flag per #15568. This still solves the libSDL2_mixer issue mentioned there.

I would change it but as a cargo cult user I don't feel qualified. Thanks for providing, drbig and remyroy.

**Comment by ZhilkinSerg** [comment]
I guess I can mark this as closed with #24130.
