### ISSUE TITLE
Lockpicking should be Interruptable

### ISSUE THREAD

**Issue by nikheizen** [CleverRaven/Cataclysm-DDA#17577]
For an action that takes somewhere around 600-700 "turns," It is certainly strange that you don't get warnings on approaching monsters, noises or _taking damage._
Especially noticeable since I usually pick locks when I don't want to make noise smashing windows because there are Zs around which I don't want to fight.

**Comment by Coolthulhu** [comment]
It could also use the repeat interface from repair actions. Generally you want to pick the lock until you succeed or have no more tools.

> For an action that takes somewhere around 600-700 "turns,"

Those are called "moves". Turns are a different thing.

**Comment by nikheizen** [comment]
How would repeated use affect the use of damaged lockpicks? Does lockpick durability factor into the picking chance? If not I guess it wouldn't matter, but if it does I would probably like to always use the highest durability pick.

>Those are called "moves". Turns are a different thing.

Ah, I see. I'm used to Angband's "turns" all being called turns (of different varieties).

**Comment by Coolthulhu** [comment]
> Does lockpick durability factor into the picking chance?

No, it just makes them break when it reaches 5.

> I'm used to Angband's "turns" all being called turns (of different varieties).

From what I recall, Angband's turns are closer to actual turns. I don't remember anything slower than me double-moving me in Poscheng, at least.
In DDA and I think also IVAN, two fast monsters can double-move (or more) each other every turn. Say, if a 500 speed monster is chasing you and you want to get the first strike, you need to be 5 tiles from it when waiting for it, even if your speed is 1000.

**Comment by nikheizen** [comment]
If someone is planning to make lockpicking repeatable/interruptible, may I also suggest doing the same for prying with a crowbar? Smashing objects should perhaps also repeat until normal interruptions or a tool is damaged unless there is a reason why it does not. Smashing corpses already "finishes the job" with a single keypress.

Ah, I see why they are called moves then.

PosChengband is probably a bad example since its energy randomization mechanics can allow slower monsters to double turn you quite frequently. Regulay Angband though, this will almost never happen outside of edge cases.

**Comment by kevingranade** [comment]
This reminds me, I'm pro-move randomization, the, "stand 5 squares away so
you can get a free hit in" type thing is nuts.

**Comment by mugling** [comment]
> This reminds me, I'm pro-move randomization

Even a small amount of variation would break tedious strategies like that

**Comment by kevingranade** [comment]
Yes, just 5% - 10% or so would render these kinds of move counting tactics
unworkable.

**Comment by nikheizen** [comment]
If movement randomization is introduced, perhaps the maximal degree of randomization should probably scale inversely with monster speeds (so very fast monsters do not seem hugely variable to a normal speed player, but still have enough randomization to abate these techs).

**Comment by Leland** [comment]
Pinging @Night-Pryanik since they're working on making washing clothes a long action in #21089

**Comment by Night-Pryanik** [comment]
Oh, I want to try to implement this, just want to be sure that my approach for making something a long action is right.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
