### ISSUE TITLE
Burst only on L.T. Carbine from Fictional Weapons mod only fires semi automatic.

### ISSUE THREAD

**Issue by DeadLeaves** [CleverRaven/Cataclysm-DDA#17571]
I assume someone did this to my mod when something changed with weapon flags. before it used BURST and BURST_ONLY flags. Now it uses something else. but it does not work and it only fires semi-automatic. 

If I'm given a few pointers on how to fix this I can do it myself in a PR along with some other updates and fixes to my mod.

**Comment by BorkBorkGoesTheCode** [comment]
Try using the following code:

`"modes": [
      [ "DEFAULT", "auto", 5 ]
    ],
    `

**Comment by mightyagrippa** [comment]
Change `mode_modifier` to `modes` on line 171 and that ought to do it. Same behavior used by core burst-only guns like the M249 and minigun.

**Comment by mugling** [comment]
I wrote some documentation on the github wiki explaining how the `modes` system work
