### ISSUE TITLE
Suggestion: default Vehicle Facing Indicator to true

### ISSUE THREAD

**Issue by mightyagrippa** [CleverRaven/Cataclysm-DDA#17582]
Since driving no longer has a hard and fast rule that one turn = 15 degrees turning, it would be a good idea to set VEHICLE_DIR_INDICATOR to true by default. I used it for the first time today and it's great. Is there a reason why it starts out turned off?

**Comment by TheWebfrog** [comment]
I'd enjoy it on by default TBH

**Comment by mugling** [comment]
Now in `master`
