### ISSUE TITLE
Vehicle part removal no longer trains any mechanics

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17598]
At the very least it should train it 1 above the level when it becomes availalble (2->3 in most cases).

**Comment by Skidborg** [comment]
Perhaps the possible skill gain should depend on the skill level required to install the part being removed?

**Comment by mugling** [comment]
Selected wrong tag. Can confirm but I'm not as yet sure why

**Comment by mugling** [comment]
Know cause
