### ISSUE TITLE
Refueling vehicle bug, fuel lost

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17593]
Refueling vehicle from container takes all fuel no matter how much was really poured into vehicle.
To reproduce create vehicle, install 10L fuel tank, take 20L canister full of fuel into inventory or adjacent tile, refuel vehicle by unloading container. Vehicle will be full of fuel, but canister became empty. 10L of fuel lost in nowhere.

Build 5210

**Comment by jarmush** [comment]
tried with water, reproduced
