### ISSUE TITLE
Many items spawning in rear bedroom of house

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#17606]
I just had over 80 items spawn in one bedroom of a house.

Tracked down the file, it is this one:
data/json/mapgen/house14.json

The problematic line looks to be:

                { "group" : "bedroom",      "chance" : 80, "x" : [17,20], "y" : [18,20], "repeat" : [145] },

Looking at the lines above and below, I assume this should be [1,5] or [1,4].

**Comment by pisskop** [comment]
Right.  What file was it in.
