### ISSUE TITLE
Allow fill Friendly NPCs containers with liquid

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17603]
When unloading liquid from containers (e.g. clean water) and selecting option `Pour into a container`, there can be also nearby Friendly NPCs containers, so you can easily refill them, especially when they wearing flasks.

**Comment by codemime** [comment]
Will do that. Actually, exactly the same idea had occurred to me before I saw your issue. #17602 has a step towards it.

**Comment by Xelat84** [comment]
@codemime great, thanks!

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
