### ISSUE TITLE
Vehicle Guns do not accept ammo belts or magazines only  stacks of individual bullets or grenades.

### ISSUE THREAD

**Issue by Mecares** [CleverRaven/Cataclysm-DDA#17618]
As the title says my freshly unloaded Mark 19 Grenade launcher would not accept the ammo belt i just took out of it, just the grenades after disassembling the ammo belt.

**Comment by BorkBorkGoesTheCode** [comment]
Does this affect the other machine guns?

**Comment by Mecares** [comment]
Same with the mounted M60, the ammo belt just falls to the ground while only the bullets can be loaded.

**Comment by mugling** [comment]
Turrets should really reload using belts (or equivalent magazines) not the current system we have of dropping bullets on the floor

**Comment by Mecares** [comment]
Yeah it is really counter intuitive right now, you can not install a weapon that has a magazine in it right now into your vehicle and then after installing you have to figure out how to load it and cant use the Magazine you just unloaded.

**Comment by jarmush** [comment]
maybe "reload turret" option should be added when you interact with the installed turret same as you interact with a kitchen unit or welder?
