### ISSUE TITLE
Debug: no security system found on vehicle

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#17615]
cataclysmdda-0.C-5092
Just a Minor bug on trying to turn off alarm on a vehicle, each try damages the security system. When its destroyed the UI doesnt update and on the next try to disarm alarm the debugg came. the UI updates when i leave it and take control again.

Debug: no security system found on vehicle

FUNKTION : void vehicle::smash_security_system()
FILE : src/vehicle.cpp
LINE : 880

pressing spacebar lets you play.

**Comment by illi-kun** [comment]
Duplicate of #17569
