### ISSUE TITLE
Suggestion: add sheet metals and wire to the Toolbox recipe

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#17622]
At present, the toolbox lacks an actual box to carry tools. I suggest adding sheet metal and wire to the recipe. It is plausible for a survivor to use the tools needed to create the toolbox to create the box itself.
This would make the toolbox recipe believable, and increase the difficulty of creating a toolbox.

**Comment by Breligar** [comment]
Possibly two recipes? One for the box at whatever skill level required, then one to dump the tools into the box with a skill requirement of zero (like the survivor belt/survivor utility belt). Could solve the common complaint of losing your tools when trying to craft a toolbox.

**Comment by pisskop** [comment]
Dont tell anyone this, but I often loot a day 0 toolbox.

I set a house on fire, make a noise/racket/be seen, and then let the zombies run into the fire and burn.

When thats done I scavange the remains.  Being made of metal, the toolbox has fre immunity.

**Comment by BorkBorkGoesTheCode** [comment]
Offtopic: @Rivet-the-Zombie , could you check the forums?
