### ISSUE TITLE
Random NPCs have no money

### ISSUE THREAD

**Issue by Vidiveni** [CleverRaven/Cataclysm-DDA#17620]
Build 5227. 

With some exceptions, the NPCs have no cash which means you can only trade using `T`. The NPCs in the refugee center don't seem to be affected. 

Also, when you buy training from NPCs they will only ask for payment sometimes and sometimes not. Maybe the player has invisible money after forcing a trade, which works when training? Could be unrelated though.

**Comment by baraba3** [comment]
been abusing this by trading with them for relations.one pistol or floodlight usually get them to maximum relation and they join you 100%.

**Comment by Vidiveni** [comment]
Closing this due to clarifications made in #17786. This was no bug, but a stepping stone to changes to trading.
