### ISSUE TITLE
restricts_gear mutations not allowing soft armor

### ISSUE THREAD

**Issue by mightyagrippa** [CleverRaven/Cataclysm-DDA#17624]
TAIL_LONG and some of the other tails say having the mutation "prevents wearing non-fabric pants". But it's currently preventing mutants from wearing any pants that don't have the OVERSIZE flag.

I'm getting the message "Your mutation Long Tail prevents you from wearing that cargo pants." Not sure if the issue is in player::can_wear or if it's in the recently jsonized softness stuff around item::is_soft.

**Comment by mightyagrippa** [comment]
Just tested in build 5225 and the problem also affects Antennae, forbidding even cotton headwear. "Your mutation Antennae prevents you from wearing that boonie hat."

Also, are plastic and kevlar meant to be non-soft? Some of the results (rain hood and survivor hood not accomodating antennae) seem off.

**Comment by Coolthulhu** [comment]
> Also, are plastic and kevlar meant to be non-soft?

Yes. Though softness should be determined by the presence of one soft material, not lack of non-soft ones.

**Comment by mightyagrippa** [comment]
That makes sense and answers all the examples I can think of right now.

**Comment by mightyagrippa** [comment]
Just checked and this was fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/17832. Thanks Coolthulhu!
