### ISSUE TITLE
Build 5219: Incendiary Grenade freezes and errors

### ISSUE THREAD

**Issue by RinneHellscythe** [CleverRaven/Cataclysm-DDA#17633]
First encounter:
Near an ant nest on a quest to kill bandits. I arrive and bandits are attacked by the army of giant ants. I throw an incendiary grenade to burn the bandits and the ants. I get multiple errors (I forgot to screenshot). I decide to have the game ignore further errors (since it was annoying).

Second encounter:
About 20+ zombie children in a park. I pull the pin out of a grenade and an incendiary grenade. I throw both of them to the zombie children. After exploding the game froze. Seems like it's related to the previous errors.

What I do remember about the errors was that it was related about limbs(?) and limb damage(?)

**Comment by mugling** [comment]
Closed as unconfirmed
