### ISSUE TITLE
Friendly NPC quest "Find a Book" is broken

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17630]
Accepted quest from friendly NPC, but all messages was `"Someone forgot to code message id is 78"`.
But in quest window I see active quest "Find a Book".
Looks like `mission_start::place_book` method is empty. So probably quest implementation is incomplete, and somehow merged into master.

**Comment by kevingranade** [comment]
Doesn't need implementing for 0.D, just disabling.
