### ISSUE TITLE
Multidropping issues

### ISSUE THREAD

**Issue by bumpkindda** [CleverRaven/Cataclysm-DDA#17634]
Multidropping will sometimes only drop a single item tagged. Not sure the exact cause but seems to happen if it includes stuff that stacks in inventory (one of which tends to be the single item dropped).

- Have a great big bunch of stuff
- Including a stack of cigarette butts or chunks of steel or something
- Try to directional drop it all

**Comment by Vidiveni** [comment]
Same thing sometimes happen im AIM when trying to move all from inventory.

**Comment by BevapDin** [comment]
> Also the pickup icon changes from a  +  to a  #  when this happens.

That `#` means you have only selected part of the stack. The `+` means all of the stack is selected.

You can select part of the stack the same way as in the inventory menu (when dropping them): by typing in the number of charges to pick up and selecting the stack afterwards, e.g. `1` `0` `c` (picks up 10 charges of the item of invlet `c`).

**Comment by Vidiveni** [comment]
Oh, now I get it. I must be consistently accidentally pressing numpad keys before pressing `right arrow`. Thanks for the explanation.
