### ISSUE TITLE
Semi zombie resurrection mod - suggestion

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#17639]
What about a mod that stop zombie resurrection. I know there is already one, but this one should not work on zombies that got shoot down, except headshots.

The idea is, in mele combat a survivor would already strike a zombie the way that he doesnt stand up again. But with guns the zombie should stand up if it wasnt killed by a headshot.
It should be a mod, for players that dont want it.

I love the idea that zombies can stand up, but it gets out of control if you play with many zombies. (i love the horde feature)

What do you think ?

**Comment by ZenZen2** [comment]
maybe not only by a headshot but also on a criticalshot.

**Comment by Labtop-215** [comment]
How would you make the distinction between shot zombies and melee zombies?  Also, if a zombie is head shot, and was pulped by this action, they already aren't getting up, except with a Necromancer nearby.

**Comment by kevingranade** [comment]
Supporting this in a nice way would be a bit tricky, the code that handles
monster death would need to track the cause of death in enough detail for
the resurrection code to figure out if it should resurrect.

**Comment by Breligar** [comment]
Actual implementation is beyond my knowledge, but there's already a mechanic that determines if you get a headshot with ranged attacks, and there's a system that determines how badly damaged a body is when the creature is killed. Could just tie it to those. For example, a "mangled" corpse = too damaged to get back up, and if you kill with a headshot hit it doesn't get back up. Just examples, but that's what comes to mind for me.

**Comment by BorkBorkGoesTheCode** [comment]
> For example, a "mangled" corpse = too damaged to get back up, and if you kill with a headshot hit it doesn't get back up. Just examples, but that's what comes to mind for me.

A spineshot might be better.

**Comment by DaliTimelord** [comment]
A headshot does not always kill a zombie in combat though, at least not something like a hulk.
Something simpler like checking the amount of damage a corpse has, rather than if it was pulped or not could be the best way. Worst comes to worst, the zombie being revived could be demoted into something like a crawling zombie?

**Comment by illi-kun** [comment]
We trying to reduce number of mods stored in the repo, at least for now, so this proposition is controversial.

**Comment by Oskar636** [comment]
Especially if we already have one that works fine ( at least last time I checked ).
