### ISSUE TITLE
Safe mode manager

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#17635]
I dont know if its possible to do it but having some sort of meny in which we coudl list enemies which would trigger safe mode would be great.Having safe mode activate when brute,hulk or some real danger appear in distance but not being triggered by one coniventional zombie or annoyed dog would really be convienience and make raiding more pleaserable when you are squishy character which hasnt got to point it can enter battle with some of more advanced threats.

**Comment by nikheizen** [comment]
A safemode whitelist of sorts which ignores "sighted" monsters, and only warns on approaching would be very good.

**Comment by Vidiveni** [comment]
This would be a major QOL improvement for me, comparable to autoavoiding trees or the already implemented autoattack  feature.

**Comment by kevingranade** [comment]
I've thought about this a bit, here's what I think it would look:
It would be whitelist based, i.e. by default it would trigger on a

**Comment by kevingranade** [comment]
I've thought about this a bit, here's what I think it would look:
It would be whitelist based, i.e. by default it would trigger on unknown
monsters.
We'd pre-populate a list of harmless monsters like squirrels.
The ui would present a list of every monster the player has seen so far in
the current game for addition to or removal from the whitelist.
A nice to have is a default list shared across games that players can also
easily manipulate.

**Comment by mugling** [comment]
> A nice to have is a default list shared across games that players can also easily manipulate.

This would be very nice indeed

**Comment by Breligar** [comment]
Absolutely love it, especially the auto-pickup-esque shared list concept. This is one of those things that I never knew I wanted until someone brought it up, and now I can't wait until it's implemented.
