### ISSUE TITLE
Improper form of the road in front of the prison gate

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#17638]
Build from commit 3d944164772f0f5ade446c8492b8a967734cb5a7.

![gate](https://cloud.githubusercontent.com/assets/5671495/16727816/898b2d44-4795-11e6-9b5e-631e60021c65.png)
![gate2](https://cloud.githubusercontent.com/assets/5671495/16727817/8995bc5a-4795-11e6-8d4b-06164499dc18.png)

**Comment by codemime** [comment]
I'm gonna fix the issue. BTW it's no prison, it's a refugee center.

**Comment by Oskar636** [comment]
@codemime This is still an issue ( build 5861 ).

**Comment by codemime** [comment]
@Oskar636 I know that. Did I say I've fixed it? I said: "I'm gonna fix the issue" and then (see the description) "this is a step towards fixing...". That takes some more work.

**Comment by Oskar636** [comment]
@codemime Ok, didn't notice, sorry.

**Comment by codemime** [comment]
@Oskar636 That's all right.
