### ISSUE TITLE
The material of candles are "veggy"?

### ISSUE THREAD

**Issue by DLaboratory** [CleverRaven/Cataclysm-DDA#17640]
```
  {
    "id": "candle",
    "type": "TOOL",
    "symbol": ",",
    "color": "white",
    "name": "candle",
    "description": "This is a thick candle.  It doesn't provide very much light, but it can burn for quite a long time.  You'll need a lighter or matches to light it.",
    "price": 100,
    "material": "veggy",
```

As far as I know, Paraffin wax, the substance in candles, is the mixture of hydrocarbon compounds which the number of carbon atoms is between 20 and 40. The main compositions of candles are C22H46, C28H58 and C17H35COOH. Paraffin wax is derived from oil. Therefore I think the material `veggy` isn't correct.

**Comment by DeadLeaves** [comment]
So, what do you suggest it should be?

**Comment by DLaboratory** [comment]
I suggest `hydrocarbons`, but I want to hear others' idea and comments.

**Comment by BorkBorkGoesTheCode** [comment]
Well the current candle recipe appears to be a combination of tallow, paraffin and vegetable candle recipes.

**Comment by mugling** [comment]
Possibly `oil`

**Comment by DLaboratory** [comment]
```
},{
        "type" : "material",
        "ident" : "oil",
        "name" : "Oil",
        "bash_resist" : 0,
        "cut_resist" : 0,
        "bash_dmg_verb" : "damaged",
        "cut_dmg_verb" : "damaged",
        "dmg_adj" : [
            "lightly damaged",
            "damaged",
            "very damaged",
            "thoroughly damaged"
        ],
        "acid_resist" : 0,
        "elec_resist" : 0,
        "fire_resist" : 0,
        "chip_resist" : 0,
        "density" : 1,
        "edible": true,
        "burn_data": [
            { "fuel": 300, "smoke": 3, "burn": 1 },
            { "fuel": 600, "smoke": 6, "burn": 2 },
            { "fuel": 900, "smoke": 9, "burn": 3 }
        ]
    },{
```

Material `oil` is edible, so material `hydrocarbons` (which is not edible) is better for this case?

**Comment by mugling** [comment]
Only `COMESTIBLE` is edible in any case

**Comment by kevingranade** [comment]
What is the in-game impact of the material being veggy?

**Comment by DLaboratory** [comment]
> What is the in-game impact of the material being veggy?

A player laughed about it on the forum, ``Candles are made from vegetables, but why I can't eat them?'' :laughing:
So I reported the wrong material here.

**Comment by kevingranade** [comment]
So... none :/

**Comment by DLaboratory** [comment]
Actually no critical impact, but incorrect.

**Comment by kevingranade** [comment]
I'm waiting for the impact if there is one. Someone not understanding how
things work isn't a bug. Things can have the veggy material without being
edible, for example corn husks would.

**Comment by DLaboratory** [comment]
Would you mind me open a pull request to change the material of candles to `hydrocarbons`?
Players are confused and laughing about it on our forum recently:

> 屎也是肉和菜变成的……一个道理……

> 这配方是胡编的吧，蔬菜怎么做蜡烛

> 成语：“味如嚼蜡”，像吃蜡一样，没有一点儿味。所以蜡烛应该是可以吃的，就是不好吃。

**Comment by kevingranade** [comment]
Yes, I would. There is no bug, so the there should be no change.
