### ISSUE TITLE
Issue while reloading magazines while having chest ammo pounch

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#17642]
Version: 5232 Windows Tiles X64

- Get Glock 19 with full magazine;
- Get 4 full glock magazines;
- Get chest ammo pounch with full Glock magazine in it and wear it;
- Try to reload your glock with magazine in your inventroy excluding first, last, and magazine in chesht ammo pounch.

Expected:
Glock should be successefully reloaded.

Result:
You will get errors:
src/visitable.cpp:428 [item visitable<T>::remove_item(item&) [with T = Character]] Tried removing item from object which did not contain it
src/item_location.cpp:234 [virtual void item_location::item_on_person::remove_item()] Tried to remove an item from a character who doesn't have it

Glock was reloaded after debug messages.

**Saves to reproduce:**
https://drive.google.com/open?id=0B1p1ntUqVzBJX3MwQXBCNEplZTg
- Load save;
- Reload with any magazine excluding first or last. For some reason with first and last magazines it works correctly.

**Comment by mugling** [comment]
Can result from inventory overflow

**Comment by Firestorm01X2** [comment]
If you don't mean non code term, I had free psace in inventory in that moment.

**Comment by Firestorm01X2** [comment]
Yes

**Comment by mugling** [comment]
What is the sequence of steps?

**Comment by Firestorm01X2** [comment]
Well. It will be better to send saves. Looks like bug reproducen not in that exact way. Investigating.

**Comment by Firestorm01X2** [comment]
OK. I catch it exactly. Just load my save and press R to reload:
https://drive.google.com/open?id=0B1p1ntUqVzBJX3MwQXBCNEplZTg

**Comment by Firestorm01X2** [comment]
Update: Reload with any magazine but first.

**Comment by mugling** [comment]
I think this was resolved in `master`. Please reopen if reproducible
