### ISSUE TITLE
Suggestion: Beds should contain springs, foam and fewer rags

### ISSUE THREAD

**Issue by nrfowler** [CleverRaven/Cataclysm-DDA#17646]
Smashing a bed recently and I found it to consist of roughly 100 rags which is excessive probably even if that is including the blankets. 50 would probably be more accurate. 

There should be "comfort foam" and springs. We would need two kinds of springs: the [springs that are used in the bed frame](http://www.ifurn.com/fashion-bed-group-twin-link-spring-480139.html) which hold the mattress above the floor and are essentially the same as the pre-existing springs in the game; and, the springs inside the mattress, which aren't as heavy duty and would have to be a new item. There should also be scrap metal corresponding to the rest of the metal frame.

So I propose each bed, after disassembly, includes 4 memory foam pads, 50 mattress springs, 20 springs, and 40 scraps of metal in addition to what it now contains. Smashing would obviously tear up the foam pads into shards of foam pads and turn some of the springs into scrap metal.

This would add more springs into the game, which are currently hard to find early on. You can also use comfort foam for a variety of uses, like bringing it back to your shelter to construct a bed, or using it as a cot. The mattress springs could be disassembled into scrap metal, and also used to construct beds and seats.

**Comment by kevingranade** [comment]
Unless you add a new variety of bed, I'd rather not have memory foam.  It
isn't ubiquitous in all beds.

**Comment by nrfowler** [comment]
OK, what I meant was just foam padding. I'm pretty sure most beds have foam of some kind, be it memory foam, comfort foam, or what have you.

**Comment by Breligar** [comment]
I don't think there needs to be a second type of spring, as the basic spring seems fairly mutli-role as it is; that is, they're already represented as being fairly nebulous in their length and width. But I do like the idea of springs being added to beds in general. As for foam padding, it just feels like an extra "thing". Usually the concept of warmth-/comfort-padding in things is hand-waved in some way during crafting.

**Comment by Izicata** [comment]
There's also a wire net in bed frames that holds the mattress up; you can see it in the picture nrfowler linked. I'm not sure how much wire that would translate to in-game, but beds should have some wires in them.

**Comment by mugling** [comment]
Against due to balance - at least minimal scavenging should be required to obtain springs and wire.

**Comment by BorkBorkGoesTheCode** [comment]
What are springs supposed to be ingame? I don't think the spring item is the same type of spring found in beds.

**Comment by nrfowler** [comment]
@Izicata I was thinking that would just go into the scrap metal, but now I realize that we have a wire item. With that in mind, I'd say add 10 wires to the component list.


So what I propose now is 20 springs, and 20 scraps of metal, and 10 wires. So that it doesn't upset the balance too much, 1/4 of beds will be like this. And all beds will now only have 50 rags.

**Comment by kevingranade** [comment]
It's not wire, that implies a conductive wire ready for use in electronics.
To represent the mesh in beds we'd need something like a bailing wire item.

**Comment by Coolthulhu** [comment]
> It's not wire, that implies a conductive wire ready for use in electronics.

Is bed wire worse for electronics that wire fence wire?
Currently fences are the best source of said wire.

> So what I propose now is 20 springs, and 20 scraps of metal, and 10 wires are added to the components. So that it doesn't upset the balance too much, 1/4 of beds will be like this.

Unless you want to introduce a new bed type, it would be better to have every single bed drop 1/4 of those components than to have 1/4 of the beds drop 100% of those components.

**Comment by Zireael07** [comment]
> Is bed wire worse for electronics that wire fence wire?
Currently fences are the best source of said wire.

:D

**Comment by mugling** [comment]
The scope creep here from beds contain too many rags (yes) to beds should provide `spring` and `wire` could have a lot of unintended consequences as to balance. It makes a lot of recipes much easier and takes away some of the necessity to scavenge and otherwise explore the world. Should beds provide components for vehicle controls?

I'd like to repeat the same argument (who?) when it was argued that the `hacksaw` is too rare compared to reality. The answer in summary was *'yes, but much of the early game becomes trivial if you find it in the first house'*.

We need to consider is gameplay improved or not by changes to resources/crafting components. Realism is subjective - there are dozens of variants of `spring` that we could model and I don't think anyone would find that fun.

**Comment by Izicata** [comment]
It seems like nobody disagrees that beds contain too many rags.

**Comment by mugling** [comment]
Fixed in #17704
