### ISSUE TITLE
Acid / Fire / Environment Resistance Added to "Modify Clothing" Command

### ISSUE THREAD

**Issue by Breligar** [CleverRaven/Cataclysm-DDA#17651]
Warmth and Cut/Bash resistance can already be added via a sewing/tailoring kit to equipment in exchange for extra encumbrance, allowing the player to make their own choices towards how to customize gear.

Suggestion is to add options for Acid, Fire, and Environmental resistance as well, as this seems in-line with current options. Materials used would be Plastic Chunks for Acid (assumed rubberized material; would fall in line with things like rubber boots), Nomex for Fire, and Duct Tape for Environmental Resistance (assumption of character sealing open areas like sleeves/pants legs).

**Comment by kevingranade** [comment]
The clothing modification action was a bad idea that we should probably get
rid of, I'm definitely not interested in expanding it.

The properties you mention are even more unsuitable for retrofitting than
the existing ones, as protection from fire, acid and gasses requires the
design of the clothing to accommodate that use case. The most trivial
example is clothing with less than 100% coverage (most clothing in in other
words), which is incapable of supporting these resistances.  Even among
clothes that have 100% coverage, it's still not necessarily a reasonable
thing to add.

**Comment by Breligar** [comment]
Didn't know clothing modification was on the chopping block, my bad. Is there interest in gear modification at all, long-term, or is the concept itself getting the boot?

**Comment by mugling** [comment]
> The clothing modification action was a bad idea that we should probably get rid of, I'm definitely not interested in expanding it.

We should aim to expand the range of interesting clothing not further extend the system of `+1 to foo` modifications

**Comment by Zilenan91** [comment]
As a player the concept of clothing modification was really cool

**Comment by DeadLeaves** [comment]
I have to agree with Zilenan91, modifying clothes is a fun feature of the game. Maybe it could use some changes to make it more useful but it's nonetheless something I really like.

**Comment by illi-kun** [comment]
This suggestion is estimated as controversial one.
