### ISSUE TITLE
Siphon fuel weirdness, splitted into a lot of iterations

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17657]
When trying to siphon fuel from vehicle, it poured in a small divided chunks, so to siphon all fuel from vehicle it can require about 5-10 iterations. For example vehicle have 10 liters, and I have in my inventory a 10L container, when I start to siphon fuel, game asks where to pour 10000 units of gasoline, I select `Pour into a container` and point my 10L canister. But only part of gasoline is poured, first time it was 2500 units, some times it's less. So I forced to repeat it again and again. It's very annoying, especially when you want to siphon large amounts of fuel.

**Comment by sethsimon** [comment]
It looks like this is an issue with filling containers with liquids in general. For example, it takes 2 tries to fill a 3L glass jar with water from a river (the first try gets it up to 10 units, the second try tops it off).
