### ISSUE TITLE
Lowering the size of the minimap doesn't cause the action log to expand

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#17663]
At the default it's huge and takes up all the space it's given. If you reduce it in the options menu, the minimap is smaller, but the actual minimap area still takes up all of the space it's in as if it was at the default setting despite the minimap not using all of it, meaning that making it smaller is rather pointless.

**Comment by illi-kun** [comment]
I'm going to close this as the issue is similar to #16062 (if I got everything correctly).

**Comment by Zilenan91** [comment]
I'll just do it
