### ISSUE TITLE
Some vehicles randomly lose wheel support

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17668]
May be related to center of weight calculations as it seems to affect bike type vehicles more than others.

Loss of wheel support makes the vehicle start creating mounds of dirt and causes it to slow down heavily.

**Comment by nikheizen** [comment]
I notice this most when turning on a bike on rough terrain.
Very annoying to think that my wheel collapsed with no message!

**Comment by sethsimon** [comment]
I've seen this happen with vehicles that have 3 functional wheels and 1 greyed-out one. Going straight works fine, but sometimes when it turns, it loses wheel support.

**Comment by kevingranade** [comment]
Hmm, I wonder if the vehicle data is uninitialized after the save is loaded.

**Comment by sethsimon** [comment]
Here's what I've found out so far. I have no idea why this is happening.

![wtf_inf](https://cloud.githubusercontent.com/assets/16765166/16860906/16cca16c-4a0a-11e6-991b-e86b7a1a763f.png)
