### ISSUE TITLE
NPC: "Thanks, pilgrim!" is used as a hostile threat message

### ISSUE THREAD

**Issue by nanovad** [CleverRaven/Cataclysm-DDA#17676]
Tiles, x64, 0.C-16674-g69176f8
I just had a hostile NPC walk up to me, and his threat was "Thanks pilgrim!"
![2016-07-13_09-03pm](https://cloud.githubusercontent.com/assets/16261742/16825784/35662486-493d-11e6-8d38-77e1261953b3.png)

**Comment by BorkBorkGoesTheCode** [comment]
This is the tip of the iceberg. I had a NPC say gibberish.
