### ISSUE TITLE
Inventory space - switching out wielded item. 

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#17686]
When you switch out what you currently have wielded in your hand with something from your inventory the game does not allow you to store in inventory even if the item removed will remove enough space. It seams to think you need to put both items into your backpack first before removing the next item. I am not sure if this was changed for realism sake or not but it gets a bit problematic as you now have to do a wield new item, drop old one  pick up dropped item and store in inventory. This is especially irritating since doing so now is several menus instead of the older system.

**Comment by sethsimon** [comment]
Duplicate of #16637. I made a PR to fix this, #17088, awhile ago, but it stagnated and never got merged.

**Comment by Treah** [comment]
Ahh cool ill close my issue then since it's a duplicate. I did check around before opening but I guess yours was sufficiently old enough for me not to check that far back :P
