### ISSUE TITLE
Missing shopkeeper item group

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#17690]
Version: 0.C-16721-g071b2cb
OS: 32-bit Linux

When loading a game, I get the below debug message 13 times (it doesn't seem to affect gameplay at all though). Usually, doing `make clean` then making again fixes JSON errors, but I think this one is a bug.
![shopkeeper_item_group](https://cloud.githubusercontent.com/assets/16765166/16856062/43a56242-49e6-11e6-8905-d9779ba156dc.png)

**Comment by mugling** [comment]
Same cause as #17653
