### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by jcd000** [CleverRaven/Cataclysm-DDA#17697]
Using arch linux, compiling latest experimental (15-Jul-16)
(RELEASE=1 LUA=1)

```
src/ranged.cpp: In member function ‘double player::gun_engagement_range(const item&, player::engagement, int) const’:
src/ranged.cpp:439:1: error: control reaches end of non-void function [-Werror=return-type]
 }

```

A quick 'n' dirty way to fix is to add unerneath the
```
case engagement::absolute_max:
            return gun_engagement_range( gun, -1, penalty, 10, accuracy_grazing );
```
this:
`default: return gun_engagement_range( gun, 0, penalty, 50, accuracy_goodhit );`

But of course i'd prefer to fix it by only having one return at the end of the function, the switch just modifying the variables to be returned.

Refraining from making a PR since i haven't checked what this function is supposed to do.

**Comment by Coolthulhu** [comment]
It would be better to print a debugmsg and then return `0.0` outside the switch.
This situation (value not being handled by the switch) should never happen anyway. Defaults in switches should be avoided if possible, since they prevent "value not handled in switch" warning.

**Comment by jcd000** [comment]
I agree. as i said, quick 'n' dirty, so that i could compile it fast.

But really, to my knowledge, best practice would be to only have one return each function so undefined behaviour never happens.

**Comment by Treah** [comment]
This is the PR that added in this function for reference. 

17656

**Comment by mugling** [comment]
Resolved in `master`
