### ISSUE TITLE
Weird location sorting order in item menus

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17700]
Sometimes inventory gets sorted after vehicles.
While items on map get their own column, those in the vehicle seem to be sorted in the same column as ones in the inventory.

**Comment by codemime** [comment]
That's made intentionally. Actually, map items and vehicle items behave similarly in the inventory (same code handles them): if there's not enough space on the screen for a separate column, it's content gets added to the first one. You can try it out with another set of items (either "longer" map items or "shorter" vehicle ones) and see that they are treated the same way.

**Comment by Coolthulhu** [comment]
Still, when adding them to the first one, the order should be preserved.

**Comment by codemime** [comment]
Do you mean the order of item categories? The map/vehicle items go first for now (at least I expect them to do so). Should I change the order so that they would go last?

**Comment by Coolthulhu** [comment]
The order should be inventory, vehicle, ground. Vehicle and ground should be sorted by distance (currently only thing that matters is that 0 distance should go before 1 distance).

A method to enforce the number of columns would also be useful. It isn't a good thing that it can drop to 2 when contents have long names.

**Comment by codemime** [comment]
> The order should be inventory, vehicle, ground. Vehicle and ground should be sorted by distance (currently only thing that matters is that 0 distance should go before 1 distance).

I'm working on a next inventory PR. Will include this into it.

> It isn't a good thing that it can drop to 2 when contents have long names.

The alternative is columns that overlap each other. I can add a new option for switching this.

**Comment by Coolthulhu** [comment]
> The alternative is columns that overlap each other.

Or just cutting off names. No need to always display all those ".. (filthy) (fits) badly burnt" etc.

**Comment by codemime** [comment]
> Or just cutting off names. 

Could be a third option value. I personally prefer to see the whole names: 

- they can be long on they own ( "copies of The Gospel of the Flying Spaghetti Monster" )
- all those "(filthy) (fits) ..." help to distinguish similar items (not a rare case).
