### ISSUE TITLE
Corrosives can shoot acid through impassable stuff

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#17709]
They can shoot acid through both impassable vehicle parts and impassable furniture/terrain. Is this intended?

**Comment by mugling** [comment]
No. It would be interesting to see how well `propagate_field` and `emit_field` could be used here?

**Comment by Night-Pryanik** [comment]
What furniture/terrain in particular?

**Comment by sethsimon** [comment]
In `Creature::projectile_attack` in `ranged.cpp:325`:
`if( !has_momentum && g->m.impassable( tp ) ) {`
`            // Don't let flamethrowers go through walls`
`            // TODO: Let them go through bars`
 `           traj_len = i;`
`            break;`
 `       }`

I guess that projectiles with momentum keep going so that bullets can go through some walls, RV doors, etc., as they can IRL. So maybe it should be:
`if( (!has_momentum || projectile deals no DT_CUT damage) && impassable)...`

>It would be interesting to see how well `propagate_field` and `emit_field` could be used here?

Do you mean something along the lines of making an acid pool or two at the point where the projectile lands (if it didn't hit any obstacles/creatures)? If so, then it would; it doesn't make sense for acid to disappear out of thin air.

>What furniture/terrain in particular?

Nothing in particular, it seems to go through all furniture and terrain. It's easiest to test with something that's transparent (e.g. dressers).
