### ISSUE TITLE
Exploding 40 mm frag grenades spawn tons of "shrapnel" items

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17727]
I assume it's a bug since each of those is useless, has 1 volume (total volume is much higher than that of the grenade) and there is way too many of them.
Probably some weirdness with chance to spawn, which should be 0 but is treated as `one_in( 0 )`.

**Comment by mugling** [comment]
They are supposed to spawn shrapnel but that implementation sounds bugged

**Comment by Coolthulhu** [comment]
That would be better illustrated by drawing a bunch of lines as the shrapnel-spewing item explodes.

**Comment by mugling** [comment]
`shrpanel` appears to need a `stack_size`. I don't see a problem with the existing system - nail bomb works the same. It also correctly displays the density of hits.

**Comment by kevingranade** [comment]
Issue as stated is not a bug, feel free to open an enhancement as opposed to a bug.
