### ISSUE TITLE
Mounted fusion gun costs 0 time to fire manually

### ISSUE THREAD

**Issue by Vidiveni** [CleverRaven/Cataclysm-DDA#17721]
You can spam it as much as you want atm. Time is stopped. 

![](http://i.imgur.com/sm05kRS.jpg)

Build 5243. 

EDIT: Apparently A7 laser has same problem: http://smf.cataclysmdda.com/index.php?topic=13054.0

**Comment by kevingranade** [comment]
Can't reproduce, in between shots I see monstars moving.
