### ISSUE TITLE
Stairs should take more than 100 movement points to navigate?

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#17737]
Stairs should be an obstacle to fights, not really somewhere to run for safety.

Im aware this could be seen as a pseudo-change with the upcoming 3d.

**Comment by Vidiveni** [comment]
May result in unavoidable instagibs when going down stairs if it's too costly, but when going up I wouldn't mind.

**Comment by Breligar** [comment]
Maybe a safe-mode/crafting interrupt warning sort of thing? "A Zombie Hulk is near the stairs, are you sure you want to go down? Y/N"

**Comment by pisskop** [comment]
As long as z-levels remains an optional addition, going up and down stairs shouldnt take more than normal.  Im talking more about the stairs taking longer to walk onto/over or the PC remaining on the current floor for longer before going down.

Rather than waiting at the new level.

**Comment by Skidborg** [comment]
It shouldn't take much longer as long as stairs are represented by a single tile.  In real life you don't climb a set of stairs by freezing at the bottom before suddenly teleporting to the top.    I can see burning extra stamina to move upwards, however.
