### ISSUE TITLE
Drop items glitch

### ISSUE THREAD

**Issue by TheWebfrog** [CleverRaven/Cataclysm-DDA#17731]
When you have "drop container" setting on and set to "Watertight" 
( I dont know about the other option ) and eat a can of food it will bug and give you a "none"

**Comment by Oskar636** [comment]
In build 5861 everything seems to work correctly - when set to all every container gets dropped, when set to watertight only for example cardboards get dropped and when set to none nothing gets dropped. No debug message.

**Comment by BrettDong** [comment]
Can't reproduce this issue either here. I set "drop container" to "watertight", and drank a tin of cola, ate a canned tuna fish, everything works fine.

**Comment by Night-Pryanik** [comment]
Should be closed?
