### ISSUE TITLE
maple tree spile doesn't produce syrup

### ISSUE THREAD

**Issue by EpicMarble** [CleverRaven/Cataclysm-DDA#17735]
version: 5243 - tiled
OS: windows 10

I installed a tree spile on several maple trees in the last days of fall. On day 10 (standard season length) of winter I have yet to see syrup in the containers. I also tried waiting next to the trees for a full day to see if the distance from my base (2 map tiles) was the problem, but no luck.

**Comment by TempestMaiden** [comment]
If I'm not misreading the code, maple trees produce sap from ~the 11th of winter through the 7th of Spring, standard season length.

**Comment by EpicMarble** [comment]
Ah, I assumed it would have started at least around mid winter so it is probably working as intended (will check when I get back).

When I searched this on the forums I saw another person with a similar issue. Perhaps a notification when examining the spile which tells you if the tree is currently producing sap would help prevent confusion.

**Comment by TempestMaiden** [comment]
It'd help, yeah. Players shouldn't have to code-dive for stuff like this.

**Comment by remyroy** [comment]
The description for the tree spile does give you some information about it:

> A hollow metal cylinder which is inserted in a tree crust in order to slowly harvest its sap.  Can be used on a maple tree in between late winter and early spring to harvest maple sap.

**Comment by Oskar636** [comment]
This isn't even an issue.
