### ISSUE TITLE
"Bad tag. '<thirst>' (0-11)" on localized game

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#17730]
![bad_tag_thirst](https://cloud.githubusercontent.com/assets/2535519/16900707/3bb5c350-4c35-11e6-9231-64141df9d475.png)
Probably occurs when NPC wants to say about his thirsty level.

**Comment by Coolthulhu** [comment]
Looks like someone translated the tag.

Not sure how to handle it properly - we either need to inform translators not to translate the tags ever or implement tag translation support.

**Comment by Xelat84** [comment]
If tags used as a display text, they should be translated.
```
say( _("<thirsty>") );
```
But probably when comparing those tags, they should be compared translated too. Currently method `parse_tags()` manipulate characters of phrases, so it definitely lose localization support. It should be implemented in a different way.

**Comment by Xelat84** [comment]
Btw, using same text could help. I mean instead of writing `say( _("<thirsty>") );` better to add category id's to `talk_tags.json` and write something like `say( SNIPPET.category_name("thirsty") );`, so tag will be translated only once - in a json.

**Comment by Coolthulhu** [comment]
> I mean instead of writing say( _("<thirsty>") ); better to add category id's to talk_tags.json and write something like say( SNIPPET.category_name("thirsty") );, so tag will be translated only once - in a json.

Tags must be translated uniformly or not at all. Having an exception for categories won't cut it.
Consider a valid sentence containing tags: `"<name_g><punc>  Let's talk."`.

**Comment by Xelat84** [comment]
@Coolthulhu yeah, you right. Hard decision. So, looks like tags should be translated everywhere, including `talk_tags.json`, either not translated at all.

**Comment by kevingranade** [comment]
Never translated is the answer here. Forcing every language to have useless
translations just in case some translator does something wrong would be a
huge waste of effort.

**Comment by cainiaowu** [comment]
Transifex will throw out a warning if someone trying to translate a tag IIRC.

**Comment by BrettDong** [comment]
Currently, the tag `<thirsty>` is

- kept as-is in Simplified Chinese, Japanese and Spanish

- translated in Russian, Traditional Chinese

- left blank (or maybe untranslated) in French, German, Korean, Italian, Portuguese.

What would be the solution of this issue?

**Comment by Coolthulhu** [comment]
Make it untranslated everywhere.

**Comment by BrettDong** [comment]
Then we need to inform translators of those languages.
