### ISSUE TITLE
Crash when NPC killed monster

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#17740]
build 5265 x64 tiles windows version
OS win 10 64bit

[img]http://i.imgur.com/3Vjoiad.png[/img]

not much help as I need dev build for debug messages.

Oh wait hang on let me load this up again and enable the basic debug function BRB :)

**Comment by stk2008** [comment]
Ahh this sucks I remember this being an issue a while ago when an NPC killed some thing game would crash oh well hope this is a little more help full at least?

[img]http://i.imgur.com/oICAqJx.png[/img]

**Comment by stk2008** [comment]
Ok this just happended again :(

as soon as the zombie child dies from being killed by my NPC follower the game hard crashes :(

**Comment by codemime** [comment]
Couldn't reproduce. 
@stk2008 Does this still happen? If it does, a saved game would be really useful.

**Comment by Oskar636** [comment]
This probably can be closed unless somebody posts some more info about this issue. Couldn't reproduce with a full out battle between npcs and zombies.
