### ISSUE TITLE
Can't use toilet water in crafting despite the toilet beeing in range and visible.

### ISSUE THREAD

**Issue by woutershep** [CleverRaven/Cataclysm-DDA#17747]
I was trying to boil some toilet water into clean water but the bathroom was dark so i had to stand in the other room or doorway, despite having eyes on the toilet it's water wasn't available. As soon as i set foot inside the bathroom it was, even if its further away from the toilet than i was originally.

![2016-07-19-171950_1920x1080_scrot](https://cloud.githubusercontent.com/assets/11578180/16955906/a2c15382-4dd6-11e6-9794-d56b73208e06.png)
![2016-07-19-172708_1920x1080_scrot](https://cloud.githubusercontent.com/assets/11578180/16955919/af0bef08-4dd6-11e6-9b31-247213564270.png)

**Comment by woutershep** [comment]
(P.S. smashing the sink made no difference)

**Comment by Coolthulhu** [comment]
The crafting material "finder" is somewhat more restrictive than vision.

**Comment by Zilenan91** [comment]
You need to be within 1 or 2 tiles away from it

**Comment by Coolthulhu** [comment]
You can be 6 tiles from it, provided the simplest straight line (the "most straight line" from center of your tile to center of toilet tile) has no impassable tiles.

**Comment by mugling** [comment]
Liquid handling bugs are being tracked separately elsewhere
