### ISSUE TITLE
Vehicle parts installation/removal time is the same for different tools

### ISSUE THREAD

**Issue by niglow** [CleverRaven/Cataclysm-DDA#17757]
0.C-16830-g0335683, Windows, tiles.

Spawn/find an "Electric Scooter". Try to remove some parts: a headlight (requires a screwdriver), a saddle (req. wrench), controls (req. hacksaw) and motorbike battery (no tools required): each task will take 27 minutes at mechanics level 2 and _each task_ needs minimal mechanics = 2 despite the fact that only "controls" have difficulty = 2 in "vehicle_parts.json".

Also, installing a part takes x2 time compared to its removal, but fastening nuts & screws is not 2 times harder/slower than loosing them, isn't it?

Other notes, might be related to the underlying issue:

In "vehicle_parts.json" part "stereo" has a flag ["TOOL_SCREWDRIVER"] but requires a hacksaw for removal and a welder for installation.
"Swappable storage battery" requires the same time to install/remove as a regular one.

**Comment by mugling** [comment]
This is all configurable in JSON
