### ISSUE TITLE
Vehicles don't accept any fuel other than gasoline and/or diesel

### ISSUE THREAD

**Issue by sakhmatd** [CleverRaven/Cataclysm-DDA#17754]
As of the few past builds, I have been unable to refuel vehicles with anything other than gasoline or diesel, i.e. hydrogen fuel is out of the picture and so is vortex core from Vehicle Additions.

To reproduce, create vehicle, attach a hydrogen tank, attempt to refuel hydrogen. Results in a "There is no refillable part here".

Using the latest experimental build, 16891.

**Comment by Soyweiser** [comment]
Can confirm, exp 5388.

**Comment by BorkBorkGoesTheCode** [comment]
I can refill hydrogen tanks with whiskey, but not hydrogen cylinders

**Comment by Oskar636** [comment]
From what I gather hydrogen engines got dropped, don't know about the vortex core though.
