### ISSUE TITLE
People who are lactose intolerant can eat cheeseburgers

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#17752]

**Comment by Rivet-the-Zombie** [comment]
Well we can in real life too.

But yeah, our simplistic 'food allergies' system really should prevent such characters from enjoying cheeseburgers.

**Comment by mugling** [comment]
Duplicate?

**Comment by remyroy** [comment]
This is related to #16539 which was rejected.

**Comment by mugling** [comment]
@remyroy  thanks. The comment at the bottom provides a proposed fix:

> If it's just for the allergies, you can add "ALLERGEN_MILK" flag and it will do the job.
