### ISSUE TITLE
Cancelling shot with Bow stores arrow in inventory instead of Quiver

### ISSUE THREAD

**Issue by Mecares** [CleverRaven/Cataclysm-DDA#17761]
Arrows that are picked up are automatically stored in the Quiver so i guess the same should be done with an arrow that the player decides to not shoot.

**Comment by Nanothaniel** [comment]
On a related note bolts no longer deposit directly into the quiver when you pick them up, they go straight to inventory.

**Comment by Nullsrc** [comment]
Nothing seems to directly deposit into the quiver anymore. The underlying code seems to have problems in several places, most likely caused by changes to ammo handling and the magazine system.

**Comment by kevingranade** [comment]
Still happens.
