### ISSUE TITLE
Aiming menu selects allies automatically

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17764]
Usually happens when there are no hostile targets nearby.

**Comment by DLaboratory** [comment]
So what we should do is to let the aiming menu only select hostile targets?

**Comment by Vidiveni** [comment]
This made my first ever deployable laser turret go 'bye bye'. Aiming also seems to prioritize enemies far away instead of closest ones first.

**Comment by baraba3** [comment]
yes,its very annoying especially with spears.

**Comment by Labtop-215** [comment]
As a counter point, it makes it easier to deal with temporary allies such as zombies that have been fooled by pheromones, monsters fooled by the effects of an artifact, and passive aggressive allies such as fungaliods created by spoiler fruit.

**Comment by mugling** [comment]
@Labtop-215 they can still be targeted manually. The automatic variant should only pick hostiles/neutral.

**Comment by mugling** [comment]
Fixed in #17767
