### ISSUE TITLE
Cable charger bionic and driving

### ISSUE THREAD

**Issue by stasalcatraz** [CleverRaven/Cataclysm-DDA#17772]
Cable is attached to ground position, not to vehicle, so bionic can not charge when driving.

**Comment by Aivean** [comment]
My two cents.

While having cables disconnect when either vehicle moves is simpler implementation wise it's certainly non-realistic. 

I think it makes sense to have cable (especially long cable) able to connect two moving vehicles (until it overextends).

Besides charging self while driving I can think of two other possible use cases:
* dragging connected welder cart around your main vehicle
* dragging cart with storage battery while wearing Power Armor (Cable Charging CBM + Power Armor interface CBM)

**Comment by smmck** [comment]
I ran into the same problem of trying to charge my bionic power while driving and having the cable pull loose when it moves. Running an experimental build from about a month ago.

**Comment by AMurkin** [comment]
Maybe introduce "cigarette lighter" at controls position of vehicle to charge bionics? :)
