### ISSUE TITLE
String with multiple arguments not using positional argument, making translating them handicapped.

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#17787]
Besides what caused the trouble in #17775, there are still a lot of strings scattered around the code not using positional argument, which causes translating them a little bit handicapped.

For example, in `src/iuse_actor.cpp` line 2125

`p->add_msg_if_player( _( "Insufficient %s to assemble %s" ),
                              ammo_name( mag.ammo_type() ).c_str(), mag.tname().c_str() );`

or in `src/item.cpp` line 2232

`maintext = rmp_format(_("<item_name>%s with %s"), label(quantity).c_str(), contents.front().tname( quantity, with_prefix ).c_str());`

It would be nice if someone with enough script-fu to replace them with positional argument.

**Comment by mugling** [comment]
> It would be nice if someone with enough script-fu to replace them with positional argument.

Needs to be a manual task as the same task should also add a translation comment via `//~`

**Comment by kevingranade** [comment]
You can treat any string like "Foo %s bar %s Baz %s" as if it were "Foo
%1$s bar %2$s Baz %3$s", there is no need to make the original string
explicitly use positional arguments.

**Comment by cainiaowu** [comment]
However due to grammar issue some of them will sound very awkwardly in Chinese.

For example we dont say "item a with quantity b" in chinese, we say "quantity b item a" instead.

**Comment by kevingranade** [comment]
You aren't following, if the original is, ( "nice %s for a %s.", "day",
"party" ), the translation can be, ( "a %2$s would be nice %1$s.", "today",
"soiree" ).
The original doesn't need to use positional arguments, they can be added by
the translation.

**Comment by cainiaowu** [comment]
Well, just tried. Transifex will throw an error for that.

![cap](https://cloud.githubusercontent.com/assets/4143592/17352014/e7307076-5965-11e6-8be2-a2e23162782b.jpg)

**Comment by DLaboratory** [comment]
If I add positional arguments in translation in xxx.po on my local machine, while the original text doesn't use positional arguments, the program works fine. It is approved by GNU gettext. Sadly, transifex is picky here, I can't even save the translation.

**Comment by kevingranade** [comment]
Oh wow that's terrible, I guess we can go through and make that update to
keep transifex happy, unless we can find a workaround.
Thanks for sticking through the long discussion.

**Comment by jbytheway** [comment]
Has anyone reported this issue to Transifex?  It would be better for everyone if they could fix it on their end.

**Comment by Night-Pryanik** [comment]
Fixed in #34183. If there are specific examples of strings not using positional arguments, we could reopen this issue or create a new one if needed.
