### ISSUE TITLE
Debug message when using entrenching tools

### ISSUE THREAD

**Issue by DLaboratory** [CleverRaven/Cataclysm-DDA#17788]
Press [a] to use entrenching tools, then the debug message jumps out.

```
DEBUG: Couldn't find item action named DIG

FUNCTION: get_action
FILE: src\item_action.cpp
LINE: 178
```

**Comment by mugling** [comment]
Version and mods in effect?

**Comment by primuspaul** [comment]
Getting it with 	cataclysmdda-0.C-5285.zip	2016-07-23 06:15 	51M	that I downloaded just now to help fix the problem, though the world may have been generated with a version a few days old. I did the lab start. No mods.

**Comment by DLaboratory** [comment]
Built from latest commit yesterday, 32c76db8908757ec96ada8ff35a3f42c62c1e0ec I think. Without any mod.
