### ISSUE TITLE
Sword lost it's binded letter when removed from scabbard 

### ISSUE THREAD

**Issue by stasalcatraz** [CleverRaven/Cataclysm-DDA#17789]
version 0.C-16984-gf95c70a
When I bind letter to sword, then hide it into scabbard and draw back, it has binded new default letter.

**Comment by Lord-Helmchen** [comment]
probably happens when a newly picked up item is autoassigned the bound letter while the sword is is the scabbard (at least that is what happens in my game). Maybe the bound item can somehow reclaim its letter from the autoasigned one upon unsheathing?

**Comment by Leland** [comment]
@Lord-Helmchen can you provide a set of steps to reliably reproduce this issue? @mugling was unable to in #14187

**Comment by Lord-Helmchen** [comment]
actually, if you load my save from #20862 and repeatedly hit a (to activate the baldric bound to a), you might see the Rising Sun switch back and forth between w (bound) to Q (unbound). At least that happened when I gave it a try a moment ago...

**Comment by illi-kun** [comment]
Confirmed per Lord-Helmchen's instructions.

**Comment by Qrox** [comment]
Could not reproduce with the provided save. Perhaps this is already fixed?

**Comment by Night-Pryanik** [comment]
Confirmed on 0.C-8110.
