### ISSUE TITLE
Smoke Vent's Toxic Gas dissipates too fast

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#17804]
Smoke/Gas vents produce gas that dissipates so fast its a nonfactor in 95% of the spelunking Ive done.

<a href="http://imgur.com/LnBqpil"><img src="http://i.imgur.com/LnBqpil.png" title="source: imgur.com" /></a>
^^  this is on my way out of the mines; the vent has had plenty of time to produce a layer of smog

**Comment by Leland** [comment]
Closing due to age and lack of discussion.

**Comment by pisskop** [comment]
its theoretically  fixed; or at least better.
