### ISSUE TITLE
Integrated mods are described in item info, but as "SEEING THIS IS A BUG"

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17816]
* Debug in crafting skills
* Unlock recipes
* Look at entry for pipe crafting gun

**Comment by OzoneH3** [comment]
There are four items in underbarrel.json with:
```"description": "IF YOU ARE SEEING THIS IT IS A BUG."```
which should actually have a real description instead of this text,
just like all the other 'built_in_mods' items have.
