### ISSUE TITLE
Crash upon steadying aim without an acquired target

### ISSUE THREAD

**Issue by BruceHoss** [CleverRaven/Cataclysm-DDA#17813]
Attempting to steady aim through any appropriate command ('.', 'a', 'c', 'p') without having a target under crosshair instantly crashes the game.
Reproducible on Linux and Windows console builds 0.C-17057-gac9d0c7, without mods.

Steps to reproduce:
1. Create a character that starts with a ranged weapon, equip it and reload.
2. Begin targeting. Target self or any other empty tile.
3. Steady aim.

**Comment by mugling** [comment]
Fixed in `master`
