### ISSUE TITLE
Siphon Display Bug

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#17819]
1.) Make sure you don't have any containers near or on you.
2.) With a rubber hose in your inventory, siphon fuel via the vehicle menu.
3.) Select the option to pour it in a container.
4.) Press space to close the popup that tells you that you have no containers.
5.) The screen will look something like this:
![siphon_display_1](https://cloud.githubusercontent.com/assets/16765166/17198170/37c120aa-5441-11e6-992e-2e2595ec37ef.png)

**Comment by illi-kun** [comment]
Still in ```master```:
![capture](https://cloud.githubusercontent.com/assets/5421954/19344189/e287303c-9141-11e6-8eac-123bdd97b67f.PNG)

**Comment by mugling** [comment]
I just pushed something related to that? Is it not now fixed?

**Comment by illi-kun** [comment]
Actually yes.
New minor bug was introduced (border wasn't redrawn):
State before siphoning (with borders):
![1](https://cloud.githubusercontent.com/assets/5421954/19345176/ec08bc94-9145-11e6-98c9-59066366a717.PNG)

State after siphoning (without borders):
![no_border](https://cloud.githubusercontent.com/assets/5421954/19345195/031a0ab4-9146-11e6-95d5-6b68e15bcb81.PNG)

**Comment by illi-kun** [comment]
I'll create a dedicated issue report for this or will fix it (because it's really easy to fix) tonight.
