### ISSUE TITLE
Instruments: "You hear you play"

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#17820]
Minor issue:
![you_hear_you_play](https://cloud.githubusercontent.com/assets/16765166/17200209/5ccc7f06-5451-11e6-9d66-28b7906f68e4.png)

**Comment by DaliTimelord** [comment]
It's src/sounds.cpp and data/json/items/tools.json having overlapping self-references.


        // Only print a description if it exists
        if( !description.empty() ) {
            // If it came from us, don't print a direction
            if( pos == p->pos() ) {
                add_msg( "You hear %s", description.c_str() );
            } else {
        ...
          {
    "type" : "TOOL",
    "id" : "flute",
    "name" : "flute",
    "name_plural": "flutes",
    "category" : "tools",
    "weight" : 250,
    "color" : "light_gray",
    "max_charges": 1,
    "initial_charges": 1,
    "use_action": {
        "type": "musical_instrument",
        "speed_penalty": 10,
        "volume": 12,
        "fun": -5,
        "fun_bonus": 2,
        "description_frequency": 20,
        "descriptions": [
            "You play a little tune on your flute.",
            "You play a beautiful piece on your flute.",
            "You play a piece on your flute that sounds harmonious with nature."
        ]
    },
    "symbol" : "-",
    "description" : "A simple silver-plated flute.",
    "price" : 5000,
    "material" : ["iron", "silver"],
    "volume" : 2,
    "bashing" : 2
        },

**Comment by I-am-Erk** [comment]
Fixed some time ago.
