### ISSUE TITLE
"Fuel usage" in vehicle menu is misleading

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17835]
Fuel usage displayed in vehicle menu is useless and actually misleading.

The displayed number correlates with fuel usage at safe speed, but so does engine displacement. Displacement is also more precise. The displayed number is pretty useless for electric engines, where power-to-consumption varies with type.

The display is also misleading, because it suggests that bigger engines use more fuel to perform the same work. This is only the case for idling big engines with small (or no) alternators.

"Fuel usage" should either be renamed (to unambiguously explain that it's fuel usage at safe speed) or removed.

**Comment by Nanothaniel** [comment]
So big engines use the small amount of fuel as smaller engines to go at the same speed? That's pretty unrealistic, there should be an incentive to use smaller engines in order to save gas compared to a larger engine going the same speed.

**Comment by kevingranade** [comment]
It's not necessarily unrealistic, larger engines are more efficient than
smaller ones when outputting their intended power.

**Comment by Coolthulhu** [comment]
But this isn't the case in game, except when straining the engine (going over safe speed).

**Comment by mugling** [comment]
> It's not necessarily unrealistic, larger engines are more efficient than smaller ones when outputting their intended power.

Yes, two stroke engines aren't especially efficient but have good power:weight. The problem is vehicle weight is currently rather irrelevant.

**Comment by Nanothaniel** [comment]
If we're comparing modern car engines a 1.5L city car might get 35mpg at 40mph and only 10mpg at 100mph. On the other hand a 5L muscle car engine might get 25mpg at 40mph and 15mpg at 100mph. Either way the small displacement engine is still getting better mileage at lower speeds, at higher speeds the large displacement engine will eventually surpass it. As it stands there is very little incentive to use a smaller engine when engine size should be one of the most important decisions when customizing a vehicle.

**Comment by MedievalNerd** [comment]
My issue with the numbers is that there is seemingly no context. Could the values be extrapolated into more 'user friendly' numbers?

Something along the lines of

On Road
@30 mph  X units of Fuel per Y units of distance
@60 mph X units of Fuel per Y units of distance
@90 mph X units of Fuel per Y units of distance

Offroad
@30 mph  X units of Fuel per Y units of distance
@60 mph X units of Fuel per Y units of distance
@90 mph X units of Fuel per Y units of distance

Or is this completely insane in term of calculating these values?

**Comment by kevingranade** [comment]
I'd prefer it simply be removed, examining the engine itself might reveal
some labelling indicating nominal fuel consumption rate, some vehicles will
display instantaneous MPG, but an official "this is the fuel consumption
rate for the vehicle as a whole" is misleading at best, especially
considering that if it does have such a label, it would have been derived
pre-cataclysm and therefore be irrelevant.  A continuously updating number
that reflects modifications is even more nonsensical.
