### ISSUE TITLE
Vehicle part category weirdness

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#17833]
The current vehicle part category is based on json flags unlike recipe which is defined in json, which lead to some weirdness in those category such as:

Scoop, seed drill and advance reaper etc are considered as cargo because of their capacity.

Vehicle control and electronic control are considered as lighting because DOME_LIGHT. 

Internal tanks lies in internal while external tanks lies in others, which should better in the cargo.

And all the remaining turrets, wheels etc cluster the other category.

It would be better if we add some more category like 'weapon', 'engine', 'wheel' or 'tank' etc.

**Comment by Leland** [comment]
No discussion in over a year and a half, closing.
