### ISSUE TITLE
Necropolis is currently not revealed by maps.

### ISSUE THREAD

**Issue by woutershep** [CleverRaven/Cataclysm-DDA#17839]
I used a roadmap and restaurantmap but whilst exploring one of the dead-end roads suddenly i had a bar and fast food restaurant pop up. I'm thinking 'hey! bug!' but then it dawned on me that this is a necropolis (seeing all the irradiated wanderers helped). I thought about adding these two (necropolis_a_74, necropolis_a_75) to the restaurant map's terrain:[] but then i thought the roadmap should also do the roads and police stations then, but then i wondered do we actually want maps to reveal necropolis structures? Being static spawns anyone who has ever seen one will probably instantly recognize it from the road layout or if not that the fact it has two adjacent police station tiles. The police station could be 'fixed' by just revealing the main entrance location and not the auxiliary tile but i cant think of something similar for the road. Discuss?

**Comment by WizardOfOoo** [comment]
I don't see an issue with the map showing the things from the necropolis.  

We know that that dead end roads are worth exploring, it's not much more of a help to recognize the necropolis.

**Comment by Leland** [comment]
Closing due to lack of discussion, feel free to comment if you'd prefer for this to remain open (or just open a new issue!).
