### ISSUE TITLE
CDDA Issue voting site needs to be sortable by score.

### ISSUE THREAD

**Issue by dreyskiy** [CleverRaven/Cataclysm-DDA#17834]
The site made to vote on top priority CDDA issues is not very user friendly as is.  If there was a way to sort by score it would be much more useful as highly voted issues would become more prominent and would garner more up (or down) votes thereby making them more visible.

http://iv.cataclysmdda.com:8111/all

**Comment by Soyweiser** [comment]
Not an issue for this project. Make an issue out of it here: https://github.com/drbig/cddaiv
