### ISSUE TITLE
Give circular saw metal saw quality or change description.

### ISSUE THREAD

**Issue by petermorck** [CleverRaven/Cataclysm-DDA#17838]
Circular saw description gives the impression you'll be able to saw metal with it, which is kind of disappointing when you realize it can't once you turn it on.

Description for circular saw (off) says:
> A lightweight handheld cordless circular saw.  Spins a circular blade fast enough to cut wood, **metal**, zombies, or in an emergency, pizza.

Once turned on, the qualities turn out to be:
`"qualities": [["SAW_W", 2], ["BUTCHER", 60]]`
No metal.
Given how blocked you are from a LOT of vehicle stuff if you're unable to find a hacksaw, giving the circular saw metal sawing 2, but NOT fine metal sawing quality would be nice, and realistic.

Perhaps the circular saw only has a wood cutting sawblade mounted? An idea could be requiring a metal cutting sawblade which I guess means we will need separate metal circular saw items. Too messy I guess. Why not just let it cut both?

**Comment by Coolthulhu** [comment]
It was possible to use circ saw to remove vehicle parts some versions ago, though this did cost charges.
