### ISSUE TITLE
Aiming at creatures can cause segfaults

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17840]
* Spawn a shotgun, load it with shot
* Remove vision-enhancing items and mutations
* Set the time to night (23 hour)
* Spawn a shocker in range
* Aim at it until it moves
* Segfault

Doesn't reproduce 100% reliably, but is still rather easy to reproduce. May require killing all critters first as there is a high chance it's index-dependent.
Could be related to the critter moving out of range, hence shotgun.

EDIT: Pinging @mugling who authored the most recent aiming PR and thus is the most likely to know what is causing this.
Forum thread:
http://smf.cataclysmdda.com/index.php?topic=13016.0

**Comment by BruceHoss** [comment]
Problem connected to report #17813.

**Comment by mugling** [comment]
> Pinging @mugling who authored the most recent aiming PR

PR was #17767

Does anyone have a stacktrace?

**Comment by mugling** [comment]
Can reproduce
```
do_aim (p=0x8051d7600, t=@0x7fffffff4ce0, target=@0x7fffffff4cdc, relevant=0x8051d78f0, tpos=@0x7fffffff4cf8)
    at src/ranged.cpp:943
943	    if( t[target]->pos() != tpos ) {
```
