### ISSUE TITLE
Survivor map and note are craftable

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17843]
EDIT: They don't show up in the crafting menu by default, but searching for "survivor" will find them.

**Comment by mugling** [comment]
Uncrafting bug?

**Comment by pisskop** [comment]
Now hang up, a custom made note isnt a bad idea.

And being able to leave survivor notes around the city also sounds like it has some modest value

**Comment by mugling** [comment]
Quite obviously a bug and not one we want to convert into a misfeature

**Comment by mugling** [comment]
Duplicate of #17876
