### ISSUE TITLE
Items clipped onto 'destroyed' clothing dissappear

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#17846]
If by combat or fire, a tool belt that gets destroyed will destroy a hammer clipped onto it.

or a holster will destroy a gun when it gets destroyed

**Comment by Soyweiser** [comment]
Aha, yeah, can confirm this happens. Had it happen in a game. Which caused my endgame char to die. (the shotguns I was carrying burned up). It was either they burned up, or they dropped and exploded without me noticing an explosion due to deafness.

**Comment by sethsimon** [comment]
This was fixed but the issue was never linked (see `player::absorb_hit`).
