### ISSUE TITLE
Byproducts 'charges_mult' field not working correctly.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17852]
In the recipes you can define byproducts. Seems that charges_mult does not charge the item correctly.

From looking at the code I think it is a charge multiplier which multiplies the default charges.  But when used on a tailor's kit like this: 

`"byproducts": { "id" : "tailors_kit", "charges_mult" : 2 }` it creates an empty tailor's kit with zero charges. And not one tailors kit with 100 charges as you would expect.  Mult 1 creates a zero kit as well. And a batch creates 2 kits.

Edit:
Looking at crafting.cpp recipe::create_byproducts it seems the charges_mult is only used when the result should go into a container or is counted by charges.

Also, currently due to #17849 this 'charges_mult' is not used anymore.

**Comment by BevapDin** [comment]
Tool like items (that can be reloaded) are always created without charges (hard coded). In this case, you should be a able to add two tailors kit and the matching amount of thread as separate entries. Yields effectively the same, but the player has to load them.

**Comment by Soyweiser** [comment]
Aha, that explains that part. But what is it then used for? It didn't work correctly for the non tool byproducts.

**Comment by BevapDin** [comment]
> Aha, that explains that part. But what is it then used for?

It is only applied when the created byproduct is counted by charges and when the result spawns in a container (`"contained": true` in JSON). The second condition could be a bug.

One can set a specific amount via a "amount" member: `"byproducts": { "id" : "tailors_kit", "amount": 2 }`.

**Comment by illi-kun** [comment]
Seems to be fixed.
Feel free to re-open if it happens again.
