### ISSUE TITLE
Vehicle repairs sometimes do not work

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17857]
http://smf.cataclysmdda.com/index.php?topic=13025

> some objects in vehicles wont repair, ever.
> http://i.imgur.com/vxFUtZS.png
> http://i.imgur.com/fnDc8wo.png

> pressing r to repair jumps to the tile the bed is on, r again highlights the bed itself, a third r starts the repairs and then it asks for a tool to use to repair, have tried welder, ductape, and integrated toolset. a minute passes in game time and then comes back to the vehicle screen and the bed is not repaired.

> this also happens with my heavy duty hatches and minireactor.

I couldn't reproduce, but looking at `vehicle::set_hp` there may be a rounding error. The math there looks rather fragile.

**Comment by mugling** [comment]
I'll take a look

**Comment by mugling** [comment]
Yes `vehicle::set_hp`. I'm going to special case for min and max durability for now as I want to overhaul vehicle repair to an interruptible long action which gradually repairs and item consuming time and other resources proportionally
