### ISSUE TITLE
reloading firearms throws error and duplicates magazines

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17869]
http://smf.cataclysmdda.com/index.php?topic=13028

> I can (U)nload firearms without problems, and (r)eload empty ones. I can un- and reload magazines with bullets. I can reload a firearm with an empty magazine with bullets.
> But when I (r)eload a firearm that contains a magazine with another magazine (whether from inventory or an ammo pouch), an error occurs:
> DEBUG: item location does not point to valid item
> FUNCTION: void item_location::remove_item()
> FILE: src/item_location.cpp
> LINE: 546

> when I continue, the magazine is added to inventory, but a copy is still in the weapon. Unloading the weapon afterwards results in the duped magazine (filled like the original to-be-unloaded ode) added to inventory and a third (empty) remaining in the gun. Once the empty mag is unloaded, the gun is finally empty...

Marking as priority because reloading is pretty vital.

**Comment by Lord-Helmchen** [comment]
steps to reproduce here: https://github.com/CleverRaven/Cataclysm-DDA/issues/16445

**Comment by Coolthulhu** [comment]
Closing as duplicate then.

**Comment by mugling** [comment]
Is this a recent regression or an older problem?

**Comment by Lord-Helmchen** [comment]
For me, it worked fine a few versions back. don't know when exactly I made the previous update. a few versions before the turret reloading was merged. 2302, iirc.

**Comment by mugling** [comment]
It's a different bug

**Comment by mugling** [comment]
Have identified cause

**Comment by Lord-Helmchen** [comment]
fyi, looks fixed in my game.
