### ISSUE TITLE
Skill-less uncraft recipes are autolearned

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17876]
Migrating them to the new `"uncraft"` pseudo-type most likely won't be enough, since it doesn't seem to guarantee non-learnability.

The recipes are accessible through search. Some sample recipes accessible this way:
* Blade (from scrap)
* Binoculars
* Laptop
* Lighter and refillable lighter
* Vacuum sealer
* Thyme
* Marijuana plant

Seems that most (all?) of the affected recipes have no skill assigned. Multi-cooker, which also is 0 lvl deconstruction recipe, is not available, possibly because it has electronics skill. Same for mess kit and military mess kit.

**Comment by mugling** [comment]
> Migrating them to the new "uncraft" pseudo-type most likely won't be enough, since it doesn't seem to guarantee non-learnability.

`uncraft` is just a wrapper around `recipe` which forces defaulting of some values. You are correct in your assessment the problem occurs later.
