### ISSUE TITLE
NPC morale doesn't decay

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17877]
Letting a NPC gorge on tasty food for a season will result in bonuses to speed and stats, not to mention great focus.

**Comment by codemime** [comment]
Is that a consequence of #17878?

**Comment by Coolthulhu** [comment]
No. Those are separate bugs, it's just that both of them are related to both NPCs and morale.

**Comment by NetSysFire** [comment]
Potentially relevant: #52853

**Comment by RenechCDDA** [comment]
Resolved by #65504
