### ISSUE TITLE
NPCs lose multiple stats on save

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17878]
The following stats are saved only for player, but used by NPCs:
- Driving recoil
- Stamina
- Morale - wouldn't be a big deal, but see #17877

**Comment by Ramza13** [comment]
Just tested for stamina and morale and found them saving for NPC's correctly.  Not exactly sure what driving recoil is.

**Comment by KorGgenT** [comment]
no longer accurate, especially with the player deprecation stuff going on
