### ISSUE TITLE
Whats the proper oxy_torch to welder charge ratio?

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#17873]
I know it's come up somewhat recently but I can't find it anymore. I see some are 2 to 5 and some are 1 to 5.

**Comment by Coolthulhu** [comment]
1 to 5 sounds better to me, but it may be a better idea to just buff the number of charges on oxytorch and get rid of the ratio.

**Comment by illi-kun** [comment]
@Cyrano7 will you utilize this somehow? Do you need this issue open?

**Comment by Cyrano7** [comment]
@illi-kun No this can be closed. I'll just link it to https://github.com/CleverRaven/Cataclysm-DDA/issues/17206 for documentation sake.
