### ISSUE TITLE
Debug menu: Various bugs.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17889]
Found quite a bit of unexpected behaviours using the debug menu.
- [x] When you use the debug menu to edit a player/npc's stats and use escape to cancel the number input screen, it sets the stat to zero.
- [x] When escaping from the weather selection menu you get NULL weather.

(I didn't test all escape key menu's btw. I'm only looking in all of them to add them to the wiki).
- [x] The 'test item group' menu can only be exited by selecting the last 'cancel' field. No escape key or 'q' key.
- [ ] Both 'Show sound clustering' and 'display weather' don't seem to do anything useful.

**Comment by illi-kun** [comment]
Updated issue with checkboxes and marked first issue as completed. BTW, comment from mugling in related PR is very important - merging a bunch of issues in one report is very inconvenient to handle, please avoid doing it in future.

**Comment by Leland** [comment]
Closing as the final issue in the list, "Show sound clustering' and 'display weather don't seem to do anything useful," is simply a question and likely won't be answered in the context of a nearly-one-year-old issue.

If that's still a question, either open a new issue, or ask around in the forums: http://smf.cataclysmdda.com/index.php?board=4.0
