### ISSUE TITLE
Auto-pickup picks up growing crops

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#17884]
Add seeds into auto-pickup rules, walk through the tile that has a crop growing, then the seed is picked up. Next if we examine that tile, debug message pops up saying the seed is missing.

**Comment by Rivet-the-Zombie** [comment]
Ouch.

**Comment by Rivet-the-Zombie** [comment]
That's a nasty sounding bug.

**Comment by Rivet-the-Zombie** [comment]
Confirmed.
