### ISSUE TITLE
Items pull off of cars may be fortified without player input.

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#17903]
Items removed from a police car at a turret roadblock were fortified.  Is this intentional?

<a href="http://imgur.com/fgKDFzN"><img src="http://i.imgur.com/fgKDFzN.png" title="source: imgur.com" /></a>

**Comment by mugling** [comment]
Not intentional. Needs retesting to see if persists after #17880 which fixes a similar issue is merged

**Comment by mugling** [comment]
Suspect resolved by #17880. Please reopen if reproducible in `master`
