### ISSUE TITLE
JSON linted whitelist

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#17902]
@narc0tiq do you have (or could it be provided) a copy of the perl5 JSON module for the buildbot? I'd like to start linting some JSON files and prevent regressions via a similar system to the current astyle whitelist. The lint tools sole dependency is p5-JSON module.

**Comment by narc0tiq** [comment]
If it's in the Ubuntu repos, I can get it easily. In fact, if it's the package they call `libjson-perl`, I already have it. Definitely go for it if you can, bearing in mind that it should be optional for anyone compiling on their own.
