### ISSUE TITLE
Cannot put the original magazine into ammo pouch when reloading.

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#17910]
Initial state: wielding a Glock 19 with a full extended magazine, and a full extended magazine in ammo pouch on right leg.

Press [r] to reload, select ammo menu appears, choose the only entry, the magazine in ammo pouch.

![select](https://cloud.githubusercontent.com/assets/5671495/17390830/39d6cb80-5a43-11e6-8463-b6261987af68.png)

And it asks you where to eject the original magazine.

![eject](https://cloud.githubusercontent.com/assets/5671495/17390811/06a62ff8-5a43-11e6-9411-d10b18b3faf4.png)

But there is no option to put the original magazine into ammo pouch.

Time is very **precious** in a battle. Reload the magazine from ammo pouch already costs one turn, eject the original magazine into ammo pouch only costs around 10 or 20 moves, but if I put it in my inventory, another turn is gone.

**Comment by mugling** [comment]
This one I can reproduce and at some point it was possible to exchange an empty magazine for a new one in an ammo pouch in a single move.

Does anyone know when the regression occurred?

**Comment by mugling** [comment]
Looking at the code I'm surprised this was ever possible. Perhaps we remember incorrectly. Either way it's a feature I'd like to support

**Comment by Lord-Helmchen** [comment]
I can confirm that is was possible. It may have gotten lost around 5312 iirc. I second the whish for it to return :)

**Comment by Night-Pryanik** [comment]
No more an issue on 0.D-8616. Trying to reload a Glock with full extended magazine (whilst having another full extended magazine in leg ammo pouch) asks you what to do with the magazine from your pistol. You can choose to store it in leg ammo pouch.
![изображение](https://user-images.githubusercontent.com/11132525/67095849-f607c100-f1c7-11e9-8075-29141f8c91e0.png)
