### ISSUE TITLE
Explosive shotgun slugs no longer craftable

### ISSUE THREAD

**Issue by mightyagrippa** [CleverRaven/Cataclysm-DDA#17919]
They seem to have been removed in https://github.com/CleverRaven/Cataclysm-DDA/pull/17385, but I don't see any mention of it in the commit comments or discussion. Was this intended?

**Comment by mugling** [comment]
Given the other changes are enumerated it appears to be an omission (presuming they were originally craftable). That said I'm not sure what would be both a realistic or balanced recipe for them.

**Comment by mightyagrippa** [comment]
They were craftable as of a few months ago. I'm not sure about the realism or balance either, but I'd like it if they were back in the game until a discussion about that happens.

**Comment by mightyagrippa** [comment]
To clarify my use case: prior to multipool, late game I would carry an ankle holstered 12ga pistol with explosive slugs. It would let me soften up a mob of zombies or make a lot of noise on command. In current state the explosion wouldn't kill zombies, break terrain, or guarantee a gas tank explosion. Now that I'm accustomed to the stricter weight restrictions of multipool I'd like to have that option again.

**Comment by Coolthulhu** [comment]
Their original recipe was pretty bullshitty (gasoline/diesel in shotgun slugs?), but allowing shotguns to function as makeshift grenade launchers isn't a bad idea.

If someone wants to re-add the recipe, it should use sane components, like RDX and incendiary. And hulls+gunpowder rather than entire loaded lead slugs.

**Comment by BorkBorkGoesTheCode** [comment]
Would they have mechanical or electrical detonators?

**Comment by Coolthulhu** [comment]
Electrical ones craftable with a soldering iron would be too big.
