### ISSUE TITLE
Changing your mind about unloading aluminum/tin cans of liquid unseals it

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#17924]
To reproduce:
Spawn an aluminum can of energy cola and a tin can of red sauce.
Unload them, and press escape when asked what to do with the liquid.
The items are now an opened aluminum can of energy cola and an opened tin can of red sauce.

**Comment by romkuma** [comment]
A related issue that I've noticed is that giving a can to an NPC follower using the "I want you to use this item" option does not open the can.

I've opened this separately as #17950 but including here in case they are related in the code.
