### ISSUE TITLE
Items that count with charges can break cargo size limits.

### ISSUE THREAD

**Issue by woutershep** [CleverRaven/Cataclysm-DDA#17934]
1. Spawn shopping cart
2. Spawn 199 rocks
3. Put 199 rocks in shopping cart.
4. Spawn 100 acorns.
5. put 1 acorn in shopping cart.
6. put remaining acorns in shopping cart.
7. 
   ![2016-08-05-163036_726x123_scrot](https://cloud.githubusercontent.com/assets/11578180/17439786/f8e49278-5b29-11e6-8437-feea40e339f6.png)

**Comment by sethsimon** [comment]
This is the same issue as #14115, which was fixed by #18195.
