### ISSUE TITLE
Exploder robot, unused.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17937]
http://cdda-trunk.estilofusion.com/monsters/mon_exploder

It seems this robot is never used anywhere. (The descriptions is also not correct, as it doesn't have SMGs).

We could remove it, or change it into something that does something.

**Comment by Coolthulhu** [comment]
Pretty sure it was kept only for compatibility.

Like most compatibility stuff, it could be removed as soon as we hit 0.D.

**Comment by pisskop** [comment]
Theres also a code that makes reviving robots display a message aboyut healing themselvers and standing up.

**Comment by Soyweiser** [comment]
Which is used by the broken cyborg.
