### ISSUE TITLE
DEBUG: Tried to set invalid ammo of none for mess kit (UPS)

### ISSUE THREAD

**Issue by woutershep** [CleverRaven/Cataclysm-DDA#17932]
![2016-08-02-170049_1920x1080_scrot](https://cloud.githubusercontent.com/assets/11578180/17439129/cba964d0-5b26-11e6-8416-e9550984d586.png)

Reproducable by trying to cook something through the crafting menu with the hotplate from a UPS modded mess kit powered by the UPS CBM. Seems to have no effect other than the message, charges are consumed properly and correctly refilled one per turn later.

**Comment by codemime** [comment]
Looks like the old bug (#16160, #16276, #16287) raises its ugly head again. Neither #16586 nor #17028  fixed it entirely.

**Comment by mugling** [comment]
Yes, quite likely related

**Comment by ZhilkinSerg** [comment]
Does not reproduce on current master now.
