### ISSUE TITLE
Jenkins reporting build failure

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17956]
Now that `json_format_check.sh` no longer exists, Jenkins considers all builds to be failures.

Pinging @narc0tiq

**Comment by mugling** [comment]
We could push an empty file and then @narc0tiq could remove this once the buildbot is updated?

**Comment by mugling** [comment]
It appears to be building ok?

**Comment by narc0tiq** [comment]
The PR builder is fixed; it will now be checking `tools/lint.sh` and `tools/format/format.pl`. It should be safe to revert 4ce39d45ec45f0d95a3605e82a90ab542122ab6b now.
