### ISSUE TITLE
Jacks carried in vehicles don't work at range

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17953]
- Spawn car
- Spawn jack
- Put jack in trunk
- Move 2 tiles away
- Try to remove wheel
- Unable to, jack not detected

**Comment by mugling** [comment]
Probably isn't but should be `PICKUP_RANGE`?

**Comment by Coolthulhu** [comment]
Yes.

I assume it's the whole thing with cranes.

The range restriction for cranes doesn't make much sense anyway. If the crane needs to be mounted on a separate vehicle, any further restrictions are unnecessary.

**Comment by Leland** [comment]
Would seem this was nixed in #20371

**Comment by kevingranade** [comment]
It was not, using, "Jacks can't be used at range" as a justification for making cranes also work at range is what was nixed.

**Comment by Night-Pryanik** [comment]
Resolved by #48640.
