### ISSUE TITLE
NPC drinking doesn't unseal cans if given via the "I want you to use this" option

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#17950]
As per the title.

To reproduce:
1) talk to NPC follower who is thirsty
2) choose "g: I want you to use this item"
3) select a sealed aluminum can
4) NPC will drink, leaving a sealed aluminum can in PC's inventory

**Comment by Treah** [comment]
Looked into this because of a forum post ( below ) but was unable to reproduce it. At this point I think this got resolved somewhere along the way. 

http://smf.cataclysmdda.com/index.php?topic=14701.0


I recommend this bug be closed.
