### ISSUE TITLE
Unloading turrets gives huge ammo belts.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17967]
Have not confirmed it, but see this topic on reddit: https://www.reddit.com/r/cataclysmdda/comments/4wmtrl/new_tip_ammo_belts

Text:
"When you walk up to a turret that had ammo now, DON'T PICK IT UP. instead, hit "e" towards the turret and you will get the option to unload. This gives you a full ammo belt for that gun type. M240 from a tank gives a wearable 500 round .308 belt. The browning gives 100 round .50 belt, etc. Probably a bug, but get while the gettin's good!"

Seems slightly overpowered to get those things that easily. Or is this WAD (works as designed)?

**Comment by mightyagrippa** [comment]
I recall getting 100-200 rounds from loaded vehicle turrets prior to belt changes. So 100 .50 cal is less than I used to find, 500 .308 is a lot more.

**Comment by Vidiveni** [comment]
Can confirm. Also getting random zombie M60 drops containing 500 bullets each.

**Comment by Soyweiser** [comment]
Yeah, just wondering, is it a bug? Or normal behaviour? Also, I don't know how loaded the belts are, I think the reddit user is refering to max belt size.

**Comment by mugling** [comment]
Suspect the 308 belt is missing a `count` parameter

**Comment by Shpid0inkle** [comment]
Hi, I made the original post on reddit. Some more info: reloading a turret with an ammo belt does not change the capacity. (You can pop a 500 round belt into an m60 and it still displays 0/40 charges. Dropping ammo onto the tile does affect this though)

**Comment by mugling** [comment]
Fixed in `master`
