### ISSUE TITLE
copper spear with none

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#17978]
found in a vault entrance (sewer?)

**Comment by Soyweiser** [comment]
Could you provide a little bit more information. What do you mean with none? Where did you find it specifically? Do you have screenshots?

How can a copper spear have none?

Are you using any mods?

**Comment by player0981234** [comment]
The structure always generates the same like this: 
RSRSCCRRR
RSSSS?SSR
RSSSSRSSR
RSSSSSSRR
SSSSSRSRS
SSRSSRSSS
SSRRSBSRS
RSSSSSSSS
SSSBSSSSS
R=solid rock S=sewer B=basement C=cavern ?=sewer?
with random stairs to the vault
Edit: That copper spear with none disappeared after I load my game. Gonna close this until I can find another one
