### ISSUE TITLE
DEBUG: Tried to learn unlearnable recipe vac_sealeruncraft

### ISSUE THREAD

**Issue by petermorck** [CleverRaven/Cataclysm-DDA#17972]
Platform: Windows 10.
Version: 0.C-17353-g1dcf6cf (tiles)
Crafted a vacuum sealer using the recipe from a book.
![image](https://cloud.githubusercontent.com/assets/20305709/17514814/0c88e352-5e35-11e6-87e7-1ea6785f39ea.png)

**Comment by MedievalNerd** [comment]
Got the same message when crafting a "Wire".

**Comment by HeadWar** [comment]
Got it with "spring". There are a number of items (can't remember any others right now though) that are obviously the reverse of disassembly recipes, if there is such a thing? They show up with a "not memorized yet" message, as if you had them in a book, except there are no books nearby. They all have a crafting time of 1 minute, and no skill requirements.
