### ISSUE TITLE
Pistol bandolier doesn't accept .40S&W

### ISSUE THREAD

**Issue by Stoukeer** [CleverRaven/Cataclysm-DDA#17988]
#5352 build. Is it working as intended or you just missed .40 in the list?

**Comment by BorkBorkGoesTheCode** [comment]
What holds the bullets in the bandolier anyway?

**Comment by Stoukeer** [comment]
>What holds the bullets in the bandolier anyway
I'd take a wild guess and choose material pressure of the bandolier itself (but they seems to be designed for particular calibers) [http://www.cowboyneeds.com/918.html]like here(url)

**Comment by mugling** [comment]
It's an omission
