### ISSUE TITLE
Defense no longer working.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17985]
Related to #17984. Same problem with the defense game mode.

Edit: seems defense mode has more issues: #16864, #12429 so perhaps we should just remove it in 0.D

And like I said in #17984 imho this should be part of the 0.D milestone. (Don't want to ship the new version with broken gamemodes).

**Comment by ZhilkinSerg** [comment]
It is possible to start Defence mode today, though there is a bug when Defence world uses saved list of default mods, which can prevent loading of DEFENCE world.

**Comment by Wuzzy2** [comment]
Oh. I just remembered you must press "S" in the first defense screen instead of the more common “>” …
xD
So, the defense mode works, but it is buggy.

**Comment by Wuzzy2** [comment]
List of defense mode bugs and issues:

* You can't leave the map square you started in, even if it's part of the spawned structure!
* Apparently Defense Mode does not reset the list of used mods for its world (see above)
* Outdated and clunky menus
    * 80×24
    * **Screen outside the 80×24 area is not cleared properly**
    * To get past the first screen you must press S (stupid choice, every other menu uses “>” or TAB)
    * It is impossible to go back, once you're in the defense mode screen

**Comment by I-am-Erk** [comment]
I believe

**Comment by Night-Pryanik** [comment]
Yeah, I checked it a couple of days ago. Defence mode is working, although it definitely need some love.
