### ISSUE TITLE
NPCs accept non-existent mission items

### ISSUE THREAD

**Issue by Vidiveni** [CleverRaven/Cataclysm-DDA#17995]
Build 5373. 

1. Start a new game with static NPCs enabled. 
2. Get the mission from the starter NPC and leave the dialogue. 
3. Repeat 1-2 until you get a 'retrieve item X' mission (or use debug). 
4. Talk to the NPC again. 
5. Congratulations. According to the NPC you have the mission item both in inventory and nearby. 

Tested with Americal flag, patient records, antibiotics and accounting ledger. Non retrieval missions seem to work fine still.

**Comment by DLaboratory** [comment]
A more simple way to reproduce this:

1. Spawn a NPC via debug menu
2. Use `d` entry in debug menu to add "find American flag" mission
3. Talk to that NPC to get that mission assigned
4. Again talk to that NPC, although you don't have the flag, the dialogue is as if you have got it in your inventory.
