### ISSUE TITLE
Mirror Vehicle Physics bug+repro

### ISSUE THREAD

**Issue by Thorbinator** [CleverRaven/Cataclysm-DDA#18006]
Short description: After ramming a mirror and parking, trying to get into the rammed vehicle instantly killed me

Reproduction steps:
1: download the world and load Zocialite/thorbinator
2: drive the tank (10mph)from the center tile north then east.
3: while going directly east, hit the front-right corner of the tank on the north mirror of the east-facing swat truck
4: park immediately after that without moving
5: get out of the tank and try to get into the back of the swat truck.
6: get hit infinity times and die.

If the tank is already facing east, north of the swat truck, then back up and hit it as prescribed in 3.

Build: 0.C-17528-g495100b, pulled from git 8/11/2016

This might need to be renamed mirrorbug.bz2.tar, was made with tar -czf Zocialite
[mirrorbug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/416205/mirrorbug.zip)

**Comment by Night-Pryanik** [comment]
Anyone cared to reproduce?

**Comment by mlangsdorf** [comment]
Can't reproduce.

**Comment by Night-Pryanik** [comment]
Closing as non-confirmed.
