### ISSUE TITLE
Suggestion: All pistol cartridges should fit into the pistol bandolier

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#18000]
An expanded suggestion from #17991 #17988

Here is a side-by-side comparison of many of the pistol cartridges found in the game:
(From left to right: .22 LR, .32 ACP, 7.62x25mm, .380 ACP, 9x18mm, 9mm, .38 Special, 40 s&w, .45 ACP)
https://upload.wikimedia.org/wikipedia/commons/5/5c/Cartridges.jpg.

**Comment by BorkBorkGoesTheCode** [comment]
.45 with scale
https://upload.wikimedia.org/wikipedia/commons/0/01/45caliberACP.jpg

**Comment by Soyweiser** [comment]
Sounds good, I was wondering about that while I added the .40. But I just don't know enough about cartridges/bullets/rounds (What is the correct word).

Currently the system works that you add general categories, I assumed it was the name of the .json file.

**Comment by BorkBorkGoesTheCode** [comment]
Since we're talking about cartridges in a game which has reloading as a game mechanic, I suggest using cartridge to refer to the combination of bullet+propellant+casing+primer and bullet to refer to the projectile that is fired from the gun.

https://en.wikipedia.org/wiki/Cartridge_(firearms)

**Comment by BorkBorkGoesTheCode** [comment]
Whoops

**Comment by mugling** [comment]
Perhaps we should really just have bandolier and wrist bandolier that accept all types?

**Comment by BorkBorkGoesTheCode** [comment]
It is easy to find cartridge measurements for all the cartridges in the game, so I think we should specify case dimensions in the descriptive text of the bandoliers and cartridges.

**Comment by mugling** [comment]
What is the benefit to gameplay over just allowing all? That sounds like a **lot** of work (and ongoing maintenance) for questionable benefit

**Comment by BorkBorkGoesTheCode** [comment]
It's a realism thing. If the bandolier uses friction to hold the cartridges in place, small cartridges like the .22 LR would fall out if the bandolier were designed for larger cartridges, and bulk becomes a problem for the big cartridges:
https://upload.wikimedia.org/wikipedia/commons/0/0e/Comparative_handgun_rounds.jpg
https://en.wikipedia.org/wiki/List_of_handgun_cartridges#/media/File:Many_bullets.jpg
https://upload.wikimedia.org/wikipedia/commons/a/ab/Rifle_cartridge_comparison.jpg

**Comment by Rivet-the-Zombie** [comment]
>What is the benefit to gameplay over just allowing all?

There isn't really one, and doing so would certainly simplify a lot of things.

> If the bandolier uses friction to hold the cartridges in place, small cartridges like the .22 LR would fall out if the bandolier were designed for larger cartridges, and bulk becomes a problem for the big cartridges

[What about stuff like this?](http://aef-doug.startlogic.com/fieldgearphotos/Rimmedeaglesnapcartbelt.jpg)

**Comment by BorkBorkGoesTheCode** [comment]
I was assuming bandoliers looked like this:
https://upload.wikimedia.org/wikipedia/commons/5/5e/Pancho_Villa_bandolier_crop.jpg

> Currently the system works that you add general categories, I assumed it was the name of the .json file.

Technically, the JSON files are named after the ammo_type of a particular cartridge, like the 22 for example. ammo_types are found in data/json/items/ammo_types.json

**Comment by Rivet-the-Zombie** [comment]
They could go either way.

**Comment by mugling** [comment]
> It's a realism thing.

It's a huge amount of work and would require ongoing maintenance for what would be minority appeal. You could submit a mod if you wanted to undertake this

**Comment by Zireael07** [comment]
> It's a realism thing.

I'm inclined to favor gameplay and maintainability over realism in this case. (And to avoid recurring discussions of why is this but not that cartridge allowed to fit) All pistol cartridges it should be.

**Comment by Soyweiser** [comment]
For gameplay and maintainability, I suggest we just make 3 types of bandoliers. A generic ammo cartridge bandolier, a shotgun shell bandolier, and a grenades bandolier.

Or even just allow a bandolier to even accept shotgun shells. And go with muglings, one bandolier fits all suggestion.

**Comment by mugling** [comment]
Grenade pouch is already a separate item and should remain that way. I'm ambivalent as to the shotgun bandolier being separate.

**Comment by BorkBorkGoesTheCode** [comment]
> Maintenance

Are you guys planning to add different ammo_types to core in future? If not I don't see the maintenance issue.

**Comment by mugling** [comment]
> so I think we should specify case dimensions in the descriptive text of the bandoliers and cartridges
> I don't see the maintenance issue.

The codebase is littered with abandoned ideas and I'd put money on that becoming one of them

**Comment by mugling** [comment]
> I'll quote mugling from #18000

Please don't cross-post unrelated discussion. Github is not a forum.

> (I don't bet. By the way mugling, what tone did you intend with that comment?)

None of the comments from the above posters are ambiguous. Discussion can continue in any submitted PR and preferably only there
