### ISSUE TITLE
Early gun skill gains have been drastically lowered in recent builds

### ISSUE THREAD

**Issue by mightyagrippa** [CleverRaven/Cataclysm-DDA#18012]
Using similar characters across builds, I got around 10% skill gain per shot in a new build as opposed to one from a few days ago. I suspect it may be due to https://github.com/CleverRaven/Cataclysm-DDA/pull/17962 affecting the skill dispersion/stat dispersion/gun dispersion math used for gun training.

In build 5310 I fired 10 rounds of .22 LR from an unmodified SIG Mosquito at one zombie. Range was between 1 and 5 tiles. Final skills were 1 (28%) handguns and 1 (4%) marksmanship.

In build 5380 I fired 57 rounds of .22 LR from an unmodified SIG Mosquito at various zombies. Range was between 1 and 5 tiles. Final skills were 0 (97%) handguns and 0 (52%) marksmanship.

Relevant character stats: 10 DEX, 8 PER, Far-sighted and Near-sighted traits with glasses, 7 total eye encumbrance, 8 total arm encumbrance, 0 starting skill in marksmanship and handgun.

**Comment by mightyagrippa** [comment]
May be due to change in character::skill_dispersion that reduced level 0 skill dispersion from 600 to 250. player::fire_gun checks for gun_dispersion < (player_dispersion + other stuff) before training skill, so that right side term has been reduced by 350 for starting characters.

**Comment by mugling** [comment]
I have a fix for `marksmanship` in #18020 but need to work on the weapon skills themselves. Suggestions are welcomed as to potential effects and training sources (possibly damage output?)

**Comment by mightyagrippa** [comment]
Comments added on #18020. Still leery of damage output as a training factor, that nerfs .22 and means any dead-on shot that deflects off armor gives no reward.

**Comment by mugling** [comment]
Fixed
