### ISSUE TITLE
NPCs train skills 1 level higher than they actually have

### ISSUE THREAD

**Issue by Izicata** [CleverRaven/Cataclysm-DDA#18017]
If an NPC has any amount of progress to the next skill level, they're considered to have that level of skill for training purposes. E.g. if NPC Bob has 5 melee skill and is 10% of the way to level 6, he can train you up to level 6 melee.

**Comment by ProfoundDarkness** [comment]
Did some testing and I think I found the culprit.  I'll try to add more soon but I'm still getting used to git and the code (I think I found the line in the code)...  I'm using linux x64 tiles 0.C-17562-g570d56b compiled w/o clang (flags: LUA=1, CCACHE=1, TILES=1, SOUND=1).  No mods, fresh world/char.

Basically NPCs are able to train the player, inappropriately, if the following is true:
* NPC and Player skill LEVEL is equal.
* NPC learned percent is GREATER THAN player learned percent.

I didn't see an option in debug menu to alter player/NPC learn percent so this was a fun state to work towards.
