### ISSUE TITLE
LeMat revolver (if you're seeing this - it's a bug message)

### ISSUE THREAD

**Issue by Stoukeer** [CleverRaven/Cataclysm-DDA#18029]
#5382
Picrelated 
![lemat](https://cloud.githubusercontent.com/assets/7186221/17649054/23cffe6a-623b-11e6-8a4b-45403b6a1849.JPG)

**Comment by mightyagrippa** [comment]
Also affects the Kel-Tec KSG's integrated second magazine.

**Comment by HeadWar** [comment]
Also pipe combination gun.
