### ISSUE TITLE
Sound Made by Certain Firearms Cause Negligible Hearing Loss / Hearing Debuffs Too Weak

### ISSUE THREAD

**Issue by DaliTimelord** [CleverRaven/Cataclysm-DDA#18027]
1. For reference, spawn a 12 gauge pistol and at least a dozen 00 shot in a world.
2. Reload gun and fire. Continue reloading and firing until you gain some hearing loss. Firing causes 160 sound.
3. Firing around 5 times causes 'your ears to ring' (which at this point would cause significant hearing loss IRL).
4. Continue firing or walk around a bit, but regardless the hearing impairment debuff will quickly be cured. There is also zero pain when firing guns without safety equipment.

This makes firearm safety equipment (earplugs, ear mufflers) useless?

Note: Was able to make myself deaf by firing explosive home-made rockets. These cause 340 sound. However, the Deaf debuff leaves very quickly. Thanks Barhandar!

**Comment by Rivet-the-Zombie** [comment]
>Firing around 5 times causes 'your ears to ring' (which at this point would cause significant hearing loss IRL).

Guns are loud, but unless you're doing something with one like holding the muzzle next to your ear when you fire it, they shouldn't be causing any long-lasting effects on your ears.

It's anecdotal, but I once fired a little under three hundred rounds of twelve gauge in about two hours at a get together/cookout/target shoot *without hearing protection* and the only impact it had on my ability to hear was it made my ears feel a bit stuffy for a few hours after.

**Comment by BorkBorkGoesTheCode** [comment]
It tends to vary from person to person, so I suggest giving a hearing loss resistance to strength and the tough mutation.

**Comment by Barhandar** [comment]
>It's anecdotal, but I once fired a little under three hundred rounds of twelve gauge

Where you fire it matters IRL. You probably were out in the open. Trying to do the same in the well-echoing indoors room is a _very bad idea_.   
Actually modelling sound reflection'd be probably not be very computationally fast, though.

Either way, hearing penalties from shooting really loud things without protection are very low in CDDA at the moment. If I use a power tool for a minute - noise far lower in decibels than gunshot - I'll be hearing worse for a few minutes. Not very noticeably worse, but still worse.

**Comment by Leland** [comment]
Unquantified suggestion without an active discussion in going on 9 months. Closing for now – if anyone wants this reopened, please ping me here, or just create a new issue. Thanks!
