### ISSUE TITLE
Brass catcher doesn't adding empty casings to player's character

### ISSUE THREAD

**Issue by Stoukeer** [CleverRaven/Cataclysm-DDA#18028]
Build #5382 If you will add a brass catcher to any gun - it will just remove spent casings from the game. After removing said mod casings and empty shells start dropping on the ground again. Was tested with a Glock22/Remington 870

**Comment by Barhandar** [comment]
They appear on reloading the gun instead of shooting.

**Comment by Stoukeer** [comment]
Whoops, indeed they are
