### ISSUE TITLE
PATH_AVOID_DANGER flags grant fire-based teleportation

### ISSUE THREAD

**Issue by Nioca** [CleverRaven/Cataclysm-DDA#18038]
Build 5380, Windows Console

Not sure if this is intended behavior or not, but when a monster with the PATH_AVOID_DANGER_1 or PATH_AVOID_DANGER_2 flag is standing on a fire field, it gains the ability to teleport to a nearby clear square in order to get itself out of harms way. The range of teleportation appears to be limited to about 3 squares, which is what leads me to suspect that this is (at least partly) intended behavior.

What's probably not intended behavior, though, is that the creature doesn't need a line-of-sight to arrive at said square. In my testing, I was able to get anything from raccoons to Mi-gos to teleport through a solid wall to get away from the fire. The circumstances necessary to cause this are fairly uncommon; the two most likely causes would be a thrown incendiary grenade (how I stumbled across this) or a monster getting cornered by fire in a building.

Monsters without either of the above flags do not demonstrate this behavior.

**Comment by Leland** [comment]
Combining with #11859
