### ISSUE TITLE
Juvenile Deliquent and Dodgeball Player professions should start with (better) storage clothing

### ISSUE THREAD

**Issue by shedya** [CleverRaven/Cataclysm-DDA#18031]
Not having a piece of clothing to store your books in in a School scenario makes no sense. Every other "Student" one (except for Poor Student that at least states a reason for not starting with a backpack) does have a backpack or a messenger bag (Bionic Student). This also should increase the point cost for JD. 
A fanny pack is clearly too small to store books in. Also, DP profession is already underpowered compared to other 1-point School professions.

**Comment by Night-Pryanik** [comment]
Should be closed after #18096?
