### ISSUE TITLE
look around reveals DIGS and NIGHT_INVISIBILITY monsters.

### ISSUE THREAD

**Issue by woutershep** [CleverRaven/Cataclysm-DDA#18037]
1. debug yourself with nightvision
2. go somewhere dark, say shelter basement.
3. wish for a giant worm and a shady zombie at the edge of your vision.
4. look around (;)
5. put cursor on tiles you spawned the monsters on

expected: highlighted floor glyph
actual: highlighted monster glyph

The tile info window does not reveal the hidden monsters. The code is probably missing a u->sees somewhere in the code that draws the tile highlighted - but i cant find out where.

**Comment by woutershep** [comment]
It also revealed a zombie in deep water.

**Comment by BrettDong** [comment]
> but i cant find out where.

Yeah, quite difficult to chase down.
