### ISSUE TITLE
Multi tiles do not work on vehicles (except broken)

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#18041]
None of the multi tiles work for vehicles, except the broken multi tile.

My computer is broken right now, but I might have left some in my tileset, that I was testing. I will remember to get some in when my computer gets fixed or replaced.

**Comment by kevingranade** [comment]
@Chezzo is this still happening, and can you provide a reproduction case?

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed.
