### ISSUE TITLE
UPS Recharge Station - Recipe doesn't appear in crafting menu

### ISSUE THREAD

**Issue by MedievalNerd** [CleverRaven/Cataclysm-DDA#18048]
On the latest build 5387, using Windows x64 & Tiles.

Although I have electronics at level 6, own a book that contains the recipe, when I open up the crafting menu I do not have the UPS compatible recharging station. I double checked in the .json file of my install build, and I see the recipe, and the requirements says 'electronics 6'.

If I do a search for UPS, I have the 'UPS' and the 'UPS conversion mod', but not the charging station.

I can provide a save file or other info if needed.

**Comment by Coolthulhu** [comment]
Which book? Only the robots book offers it at lvl 6, other books require 7 and 8.

**Comment by MedievalNerd** [comment]
Good grief, I just understood what the 'levels' meant in the item browser. Sorry for the trouble. :(
