### ISSUE TITLE
Medium storage battery has a terrible storage:weight ratio

### ISSUE THREAD

**Issue by OldSedan** [CleverRaven/Cataclysm-DDA#18045]
I know vehicle batteries are currently the subject of discussion and redesign, but at the moment the medium storage battery is fairly lame - twice the weight of car battery for less than a third the storage. 

Also perplexing that a full-size storage battery is the crafting equivalent of 4 medium storage batteries, but the medium size has 700 storage each to the full-size's 40k.

**Comment by Coolthulhu** [comment]
Could be a zero missing somewhere.

**Comment by OldSedan** [comment]
I've been manually changing the capacity in items\vehicle\battery.json which works nicely
