### ISSUE TITLE
Asked to Train NPC Bug

### ISSUE THREAD

**Issue by DaliTimelord** [CleverRaven/Cataclysm-DDA#18049]
![thfvl4r](https://cloud.githubusercontent.com/assets/20878878/17688403/02797c56-634d-11e6-9b94-87727d98b63a.png)

Saw this on an NPC I met, completed a few quests, asked for training, finished training, and then asking to know more about them.

**Comment by Coolthulhu** [comment]
It's a bug if you have it, it's not a bug for a NPC to have it.

**Comment by DaliTimelord** [comment]
Whoops trigger finger.
