### ISSUE TITLE
enhanced hearing cbm and anti glare compensators cbm installation lie about the slots used

### ISSUE THREAD

**Issue by BrainDamage** [CleverRaven/Cataclysm-DDA#18054]
enhanced hearing cbm installs 2 cbms:
enhanced hearing 3 slots
sound dampeners 3 slots
the installation information claims to use only 3 slots, probably referring only to the main one, but in practice each one of them uses 3 slots for a total of 6, making it rather confusing
moreover, it seems to me a mistake that actually 3 slots are being used for such secondary feature, making it rather expensive for something that can be jury rigged with few rags
anti glare compensators have the same problem
anti glare passive 1 eye slot
optical dampers 1 eye slot
yet the installation claims it only will occupy 1 slots, probably referring to the main bionic
depending how the max slots enforcement code works, they might even generate bugs if the secondary extra ones would exceed capacity limit but the single main one don't

**Comment by Rivet-the-Zombie** [comment]
The secondary CBMs really shouldn't cost any points.

**Comment by Soyweiser** [comment]
I think the other CBM that installs multiple things might have the same problem (think the reactor one). But have not tested it.
