### ISSUE TITLE
Evacuation shelters oversupplied if a zombie spawns in the basement

### ISSUE THREAD

**Issue by shedya** [CleverRaven/Cataclysm-DDA#18051]
![screen shot 2016-08-16 at 7 16 05 pm](https://cloud.githubusercontent.com/assets/17379794/17706751/e90234e0-63e5-11e6-960d-4f83f345405f.png)
Starting evacuation shelter, a boomer spawned there. That has already happened to me a few times. Did the government ACTUALLY do their job? Impossible!

Here's the world archive. 
[Placerville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/420775/Placerville.zip)

Btw, in the same save evac shelter spawned _too_ close to the city. Shouldn't the shelter be at least a bit farther away than a few meters?

**Comment by John-Candlebury** [comment]
Its intentional, with about a one in ten chances of happening.

**Comment by shedya** [comment]
Makes the game a bit too casual, no?

**Comment by John-Candlebury** [comment]
Only if you start-scum for it. Otherwise its just a random starting advantage as in many other roguelikes

**Comment by shedya** [comment]
But you basically don't have to leave the shelter at all for at least 3—7 days, and all it takes is just luck. Perhaps it should be nerfed a bit?

**Comment by Zireael07** [comment]
A well supplied basement has a zombie in it. The normal one never has a Zed.

**Comment by shedya** [comment]
Most of the zombies can be killed with a heavy stick (which is readily available) without problem, if they're alone.

**Comment by Soyweiser** [comment]
I hear people talk about these basements a lot, I also had them spawn quite often (it felt like) sure about the 1 in 10?

**Comment by player0981234** [comment]
I found a shocker brute once

**Comment by illi-kun** [comment]
Working as intended.
