### ISSUE TITLE
balance idea: enforce conservation of mass for reversible items

### ISSUE THREAD

**Issue by BrainDamage** [CleverRaven/Cataclysm-DDA#18058]
this might be a bit controversial:
currently the finished product of a recipe can have more or less mass than the original ingredients which is ok-ish, one could add or remove materials ( even some not speficially mentioned in the recipe ) to achieve the finished product; the problem arises with reversible items
if the mass of the finished product differs from the materials one can always assemble or disassemble an item to drop the mass ( and in some cases it can be significant ) to allow to transport it easily around, and reverse the operation on destination
moreover it's confusing and plain un-physical
the weight of the finished product for reversible recipes should be  automatically computed as the sum of the ingredients

**Comment by Soyweiser** [comment]
Think there are some problems with forcing items to have a certain weight via code. Best might be to use a script that checks for reversible recipes with mismatched mass/volume.

(I think mass is the big issue here, not volume)

**Comment by Barhandar** [comment]
> the weight of the finished product for reversible recipes should be automatically computed as the sum of the ingredients

No. You're just adding more pointless complexity and interfering with data.

What should be, is a separate utility that can scan recipes and items and alert if there are any reversible recipes that result in weight mismatches, so they can then be manually fixed.

**Comment by woutershep** [comment]
We already track what what something is made out of (components), isn't most groundwork done with that?

**Comment by Soyweiser** [comment]
Yeah wouter (dutch btw?), you are right. It is just a question of looping over all the items and finding the weights of all of them.

Not totally trivial of course, as Barhandar mentions, multi options are slightly an issue, as you need to calculate all the options. But that is also doable. I think at first (aka, the quick implementation) you can just easily pick the heaviest of a group of components (like `"components": [ [ ["bone", 1], ["bone_human", 1] ] ]`) and use that to calculate the min weight of that component group. And if the weight of the components goes below the weight of the result, just report the recipe. And then somebody irl can look at it.

**Comment by Cat09** [comment]
to be fair, most crafting recepies probably result in lower mass end products due to loss. cloth snippings, bone shavings, sawdust etc.
It would be nice to have some noticability on that front. perhaps tile effects of some sort, even if it's just flavor text.

**Comment by illi-kun** [comment]
Controversial idea with no code support (and non-trivial for implementation, BTW.)
