### ISSUE TITLE
grappling hook is single use

### ISSUE THREAD

**Issue by BrainDamage** [CleverRaven/Cataclysm-DDA#18057]
deploy grappling hook and it's impossible to pick back, not even if you climb up to the attachment point, making it effectively a single use item, this is rather odd and confusing behavior for a non consumable item, perhaps add a mention in the description?

**Comment by pisskop** [comment]
A climber's kit and reusable grappling hook would be awesome.  I imagine as 3d comes into play more theyll code it in.

Changing the description?  meh, it points out a blatant [current] code limitation...

**Comment by Leland** [comment]
This thread hasn't seen an update in 9 months. Closing for now. If anyone is still interested, I can reopen... or feel free to just make a new issue!
