### ISSUE TITLE
Ranged weapons that don't use magazines are still highlighted red, like ones with not-attached magazines

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#18068]
For example, most shotguns, BB gun, nail gun (but not nail rifle - it does have a magazine), bows, unloaded crossbows...

Only weapons that _have_ attachable magazines at all should be highlighted red if they don't have one attached.

**Comment by Night-Pryanik** [comment]
Cannot confirm:
![default](https://user-images.githubusercontent.com/11132525/34070492-630e91d6-e278-11e7-9da7-e06b4e66be91.png)
