### ISSUE TITLE
Impossible to immediatly put out 'on fire' effect with a low duration.

### ISSUE THREAD

**Issue by woutershep** [CleverRaven/Cataclysm-DDA#18060]
I got hit by a stray bullet from my mounted A7 laser rifle. It has INCENDIARY ammo and it in turn set me on fire. I had full health (the bullet bounced) and i immediatly tried to put it out by waiting but i was unsuccesful and slowly burned to death over the course of minutes. (sidenote: i even had my Thermal Dissipation active but that didnt do anything. checking code it only supresses blistering from bodytemp and onfire from fire fields, maybe it should make you immune to DT_HEAT?)

code says i get hit, get onfire from the incendiary with duration 1-4, intensity 1.

heres a transcript of a test character with 90 hp. (checked the .sav every time after saving, then loading him back up for the next one)
gave him onfire to to the torso (why is there no effect debug menu thing?), duration 2, intensity 1.

i attempt to put it out, duration is 2. intensity is 1.
i attempt to put it out, duration is now 3. intensity still 1.
i attempt to put it out, duration is still 3. intensity still 1.
i attempt to put it out, duration is still 3. intensity still 1.
i attempt to put it out, duration is still 3. intensity still 1.
i attempt to put it out, duration is still 3. intensity still 1.
i attempt to put it out, duration is still 3. intensity still 1.
i attempt to put it out, duration is still 3. intensity still 1.
15 times more, still duration 3, intensity 1.
10 times more still duration 3, intensity 1.
10 times more still duration 3, intensity 1.
4 times more, my clothes burn, duration 5, intensity 2.
5 times more aaaaaaaand im dead from 0 torso hp.

what DOES work is NOT trying to put it out untill you get a duration above 10, then you get downed and you CAN get rid of it by waiting before you die. this is really counterintuitive ofcourse.

what i think is happening is that, since onfire is dealing DT_HEAT damage, and DT_HEAT damage has a chance to add to the fire, that its simply not enough for pause() to decrease it by 1 but im not 100% sure. i am sure that something is amiss though.

**Comment by DaliTimelord** [comment]
This sounds like something white phosphorus would do to a body. Though I'm assuming that's not what incendiary weapons use.

**Comment by Barhandar** [comment]
A7 _laser_ turret. If the ballistic incendiaries actually use white phosphorus, there should be a separate tag for it, and separate one for just setting stuff on fire which lasers can do.

**Comment by Leland** [comment]
This thread hasn't seen an update in 9 months, and #19359 is more recent. Closing for now. If anyone is still interested, I can reopen... or feel free to just make a new issue!
