### ISSUE TITLE
Crafting does not respect "charges_per_use" of hotplate used

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#18067]
This value only affects using hotplate(-like) items to heat food by activating it directly.

It should be used as multiplier for charges called for, so certain hotplates can be made less _ludicrously_ efficient. However, that will require also using it as divisor so crafting menu shows the amount of crafting possible with the accessible stoves counting the actual usage, as opposed to taking flat charges (and then causing "you're lacking resources to craft" or overcrafting errors).

Related to #16529, but a different issue.

**Comment by pisskop** [comment]
Its not supposed to, thats not how that value works.

Charges per use only works when you use it. Using a hotplate/sodacankit/etc provides the option to heat up items.

**Comment by Barhandar** [comment]
The point is to _make_ it be supposed to do this.

**Comment by Coolthulhu** [comment]
Using `charges_per_use` wouldn't be good here. Should be more crafting-related, in recipes.
