### ISSUE TITLE
Mutation : time weirdness.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#18061]
Activatable Mutations can have a time value. Which starts a timer and every time the timer reaches zero the hunger/tiredness/thirst values of the player are increased. I think (not sure) there are some minor bugs here.

In activate_mutation, I don't think the `if (tdata.powered && tdata.charge > 0)` part will ever be true, when a mutation is powered, the mutation gui call deactivate_mutation. Not activate mutation.

Also, when a mutation is activated (with a time value set), the tdata.charge field is used as a counter, but set to time -1. Which means that for a value of time=1, the `tdata.charge > 0` will always evaluate to false. Causing the mutation to just use up hunger every turn. As tdata.powered and mdata.time are not related as far as I can tell, both time 0 and time 1 mutations use up their cost in resources every time activated or when player::suffer is called.

Sorry I couldn't test it more atm. I cannot get my trunk build to compile. So, I could be totally wrong here.

From player::activate_mutation :

````c++
if (tdata.powered && tdata.charge > 0) {
        // Already-on units just lose a bit of charge
        tdata.charge--;
} else {
        // Not-on units, or those with zero charge, have to pay the power cost
        if (mdata.cooldown > 0) {
                tdata.charge = mdata.cooldown - 1;
        }
        // ... (rest of else increases hunger and thirst)
````

From: player::suffer

````c++
if (tdata.powered && tdata.charge > 0) {
        // Already-on units just lose a bit of charge
        tdata.charge--;
} else {
        // Not-on units, or those with zero charge, have to pay the power cost
        if (mdata.cooldown > 0) {
                tdata.powered = true;
                tdata.charge = mdata.cooldown - 1;
        }
        // ... (rest of else increases hunger and thirst)
````

Another small thing, odd that in the player:suffer code `tdata.powered` is inside the `if (mdata.cooldown > 0) {` and in the other function (player::activate_mutation) it is outside it. (esp as the suffer powered must always be true, as there is a 

````c++
if (!tdata.powered ) {
            continue;
}
````

In the start of the for loop. So, I think the `tdata.powered = true;` in suffer can just be removed.

**Comment by Night-Pryanik** [comment]
Closing due to the lack of discussion in more than a year.
