### ISSUE TITLE
 Vitamins 90 days of the season do not work correctly

### ISSUE THREAD

**Issue by NEONZARIN** [CleverRaven/Cataclysm-DDA#18078]
When world settings season 90 days need a character does not work properly in vitamins. Scurvy and other diseases associated with vitamins come too early, literally every day. A character has to produce every day a lot of bones for calcium.
You can fix this?
By default, the game character's need for vitamins is valid for the duration of the season in 14 days?

**Comment by mugling** [comment]
Been discussed before, the answer is that no adjustments are intended for different world settings
