### ISSUE TITLE
Handguns skill is not affected by shooting

### ISSUE THREAD

**Issue by Stoukeer** [CleverRaven/Cataclysm-DDA#18071]
#5389 It simply doesn't levelling up no matter how many times and from which pistol you shoot. Tested on S&W619, SIG Mosquito and Glock 19.

**Comment by mightyagrippa** [comment]
This is probably same issue as https://github.com/CleverRaven/Cataclysm-DDA/issues/18012.

**Comment by Stoukeer** [comment]
Well, there the skill was working, just slowly. In current build it doesn't work at all with pistols (rifles, SMGs, and shotguns are fine) Probably related though.

**Comment by mugling** [comment]
Yes, duplicates #18012
