### ISSUE TITLE
Rework vehicle out-of-control behavior.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#1807]
Currently a vehicle with no driver goes out of control and starts yawing and losing speed rapidly.  This results in the vehicle probably going off the road very rapidly (no idea how realistic this is, but it's un-fun in-game) and coming to stop in an extremely short time (this is definitely unrealistic, especially since it's quite different from simply disabling cruise control).

This seems to stem from the vehicle being considered "skidding" even if it's motion is aligned with its facing.  At this point rolling resistance is multiplied by 10, leading to the vehicle coming to a stop very rapidly.  Replacing the simple "out of control" check with a vector comparison between vehicle facing and momentum in order to determine drag might be all that's required to make this behave more sensibly.

A nice additional option would be to brick the accelerator and tie the steering wheel to allow vehicles to be used as autonomous weapons (bonus points for putting bombs in them).  This could be something done from the vehicle interaction menu which requires a rope or similar and something to prop the accelerator.

The effect would be to reduce the frequency of vehicle turning, and to keep the cruise control going (or just thrust every turn?) even with no driver in control.  This would also be nice for other activities, like fighting zombies in the back seat, or firing LAWs.
##

**Comment by mlangsdorf** [comment]
```
-    int base_slowdown = veh.skidding ? 50 : 5;
-    if( should_fall ) {
-        // Just air resistance
-        base_slowdown = 1;
-    }
+    int base_slowdown;
+    if( should_fall ) {
+        // Just air resistance
+        base_slowdown = 1;
+    } else {
+        base_slowdown = 5 + std::floor( 5 * sin( abs( veh.face.dir() - veh.move.dir() ) ) )
+    }
```
That puts base slowdown at the following values, based on the difference between facing and movement:

Difference | Slowdown
-- | --
0 | 5
10 | 12
20 | 20
30 | 27
40 | 33
50 | 39
60 | 43
70 | 47
80 | 49
90 | 50
100 | 49
110 | 47
120 | 43
130 | 39
140 | 33
150 | 27
160 | 20
170 | 12
180 | 5

I'm probably going to implement this as part of the "move slowdown calculations inside vehicle:: where it belongs" PR. Unless people hate it.

**Comment by mlangsdorf** [comment]
The logic is that for that table is slowdown is basically air resistance and ground friction. For most CDDA vehicles, air resistance is possibly symmetrical along the vehicle's intended axis of movement, but gets worse the more the vehicle rotates away from that axis, maxing at 90 degrees.

If that's not appropriate, 5 + 45/180 * angle of difference is a simple calculation that increases skid friction by 50% from base for every 10 degrees of skew between facing and movement.
