### ISSUE TITLE
Glass shiv shouldn't conduct electricity

### ISSUE THREAD

**Issue by grisamentum** [CleverRaven/Cataclysm-DDA#18087]
weapon "glass shiv" conducts electricity. it should not, as glass is not a good conductor at regular temperatures.

**Comment by Izicata** [comment]
I knew removing that line about the poor guard would lead to confusion.

The idea is, the shiv is a very short weapon and doesn't have enough material between you and the zombie to reliably prevent direct skin contact or errant sparks from shocking you. Same thing for the toothbrush shiv.

**Comment by Soyweiser** [comment]
Is rebalance of the conductive flag related to this bug? : http://smf.cataclysmdda.com/index.php?topic=13110.0 (ukulele says it both conducts and doesn't conduct elec).

**Comment by grisamentum** [comment]
Ok, so if the issue is that the "poor guard" doesn't prevent you from touching the zombie, what does that have to do with whether the *weapon* conducts electricity? That simply isn't what the words "conducts electricity" means. It's just wrong.

What you're basically talking about is like... bonus coverage for hand/arm armor. Nothing to do with conductivity.

**Comment by Coolthulhu** [comment]
> That simply isn't what the words "conducts electricity" means.

It's better than a long "this weapon, when used to strike an electric target, will make either make contact with it or conduct electricity". It is also better than special casing "make contact" and "conduct electricity", since those are equivalent.

It's an UI note helping the player tell apart items that are safe to use against electric zeds, not a physical properties note.

**Comment by grisamentum** [comment]
Then just write "this weapon is safe to use against electrified targets" or not safe to use.

You say "it's not a physical properties note" but anyone who reads the words "this weapon conducts electricity" is going to think it's a physical properties note. That's just what conductivitiy _is_. The player has no reason to think, "oh, what that probably means is that the weapon doesn't adequately cover me from random sparks through the air."

**Comment by Leland** [comment]
Some decent ideas presented here, but discussion and work have been stalled for over 8 months now. Closing – if anyone wants this reopened for the purposes of discussion/development, just ping me here to do so, or feel free to make a new issue for the sake of visibility in the issue queue.
