### ISSUE TITLE
Lab stairs connect to each other via an alternate dimension

### ISSUE THREAD

**Issue by darth-servo** [CleverRaven/Cataclysm-DDA#1808]
Currently exploring level 8 of a lab (which is pretty nuts in itself), and I've discovered that the stairs up and down on this level (and probably others) are not connected logically.  2 sets of Up stairs which are in separate rooms a fair distance apart connect to the same set of Down stairs the level above, which only lead back to the 1st set of Up stairs below.  Basically, Stairs Down 1 lead to Stairs Up 1, Stairs Up 1 and Stairs Up 2 (far away) both lead to Stairs Down 1.
##

**Comment by WizardOfOoo** [comment]
Now that we have the "Align up and down stairs" setting.  Can this issue be closed?

**Comment by Coolthulhu** [comment]
No, stair alignment is only enforced for houses.
Enforcing it for labs would require separate code.

**Comment by Leland** [comment]
Closing this in favor of the master science lab issue #10958.
