### ISSUE TITLE
Allow mutation attacks to apply effects like techniques

### ISSUE THREAD

**Issue by Izicata** [CleverRaven/Cataclysm-DDA#18094]
Currently mutation attacks just add damage, nothing else. This is kind of boring; all mutation attacks are roughly the same. Allowing mutation attacks to apply varying effects would give them more variety and allow for greater differentiation between mutation lines. 

Of course, mutation attacks occur alongside the attack instead of replacing the attack. Therefore any mutation attack that applied an effect should be rare. However, currently mutation attacks don't really stay rare. It's not possible to have mutation attacks that occur slightly more than 10% of the time for an average survivor (dex 8 unarmed 4) but that don't occur 100% of the time for a high stat, high-skill mutant (dex 14 unarmed 8), due to the way the one_in calculation works.

However, if #18059 or something like it is merged, this will change. Creating mutations that will occur 12% of the time for an average survivor and 22% of the time for a high stat, high skill mutant becomes possible; simply set the chance to 100.

Combined with the jsonization of mutations that has already occurred, this would allow for a variety of mutation attacks similar to the variety of techniques that are available. Just as some examples, the Club Tail attack could be given chance 50 and down_dur 2, as you knock your target off-balance with your tail. The Curled Horns headbutt could have chance 80 and stun_dur 2. Huge could be given a body slam attack with chance 30 knockback 3, letting you frequently throw around smaller enemies like the hulking mass of muscle you are.

Much like how the martial art technique effects allow styles to have themes, this would allow for combat oriented mutation lines to have themes and to significantly change the way your character fights in melee. Mutation lines like Raptor and Feline could stay focused on frequently occurring damage-only attacks, being predators that try to kill their prey quickly. Other mutation lines, like Bear and Cattle, could have knockbacks and stuns, as their sheer strength allows them to throw enemies around like rag-dolls. Cephalopods and Plants could trip or throw enemies with their many limbs. Slimes could grab enemies by engulfing them.

This would, of course, require rebalancing all such changed mutation attacks. That's now much more feasible given that mutation attacks have been mostly jsonized, so you can change their values without recompiling.

**Comment by Coolthulhu** [comment]
Currently mutation attacks are hardcoded in a rather inflexible way. Extending it in current state could result in more work in the end.

If anyone wants to pick it up, I'd recommend adding a technique field to mutation rather than adding a custom reimplementation of it. `player::perform_technique` already exists and adapting it for mutations shouldn't be hard.

**Comment by Leland** [comment]
Closing due to age and lack of discussion. If anyone wants this reopened for purposes of continued discussion/development, please ping me here – or create a new issue and link it to this one.
