### ISSUE TITLE
Sometimes walk on dragged vehicles.

### ISSUE THREAD

**Issue by Beanzy** [CleverRaven/Cataclysm-DDA#18093]
Build: 5381 Windows x64 Tiles

Issue: When dragging a vehicle (e.g. a shopping cart) you can end up stepping on it (being in the same tile). This happens if the vehicle is at a cardinal direction relative to the player, and then you move in a diagonal direction towards the vehicle.

So, using the numpad as reference; if the player is at `5` and a shopping cart is being dragged at `4`, moving to `7` or `1` will cause the issue to occur.

**Comment by nanovad** [comment]
Can confirm, 0.C-17621-g817d3a5

**Comment by illi-kun** [comment]
Closing this as a dupe contains more info.
