### ISSUE TITLE
Unable to repair cars with a acetylene torch

### ISSUE THREAD

**Issue by Xnfinity** [CleverRaven/Cataclysm-DDA#18102]
Not sure if this is a repeat but;
Unable to repair cars with a acetylene torch

but if a welder or duct tape is nearby i can start repairing and use the acetylene torch at the menu on what to use for the action

build 5402

**Comment by nanovad** [comment]
What version is this?

**Comment by illi-kun** [comment]
Was your acetylene torch reloaded properly? Acetylene torch charged per proper welding tank works just fine for me.

@Xnfinity could you double check that?
