### ISSUE TITLE
missing firearms in itemgroups

### ISSUE THREAD

**Issue by crom7** [CleverRaven/Cataclysm-DDA#18104]
To be thorough, here is a list of all missing firearms from data/json/items/gun/ cross-referenced with data/json/itemgroups/guns.json
  
  /12mm.json         hk_g80
  /223.json             hk_g36
  /300.json             m2010
  /3006.json           survivor_special_700
  /308.json             rifle_308
  /38.json               2_shot_special
  /50.json               m2browning
  /50.json               m2browning_sawn 
  /bio.json              bio_blaster_gun
  /bio.json              bio_laser_gun
  /bio.json              bio_lightning
  /gasoline.json      flamethrower
  /gasoline.json      flamethrower_crude 
  /gasoline.json      flamethrower_simple 
  /gasoline.json      rm451_flamethrower 
  /metal_rail.json    heavy_rail_rifle
  /metal_rail.json    rebar_rifle
  /nail.json             coilgun
  /nail.json             nailgun
  /nail.json             nailrifle
  /signal_flare.json flaregun
  /ups.json            emp_gun
  /ups.json            laser_cannon
  /ups.json            laser_rifle
  /ups.json            unbio_blaster_gun
  /ups.json            v29 
  /ups.json            v29_cheap
  
These weapons are not listed in the /itemgroups/guns.json and I'm sure some weapons are intentionally missing, but some (like hk_g36) may have been overlooked.
  as of ver: 0.C-17711-gaf190e2

**Comment by BorkBorkGoesTheCode** [comment]
Thanks for pointing these out.

>  /223.json hk_g36
 /300.json m2010

These would be good in guns_rifle_rare

>  /signal_flare.json flaregun

tools.json;  tools_survival itemgroup.

> /3006.json survivor_special_700
 /308.json rifle_308
 /38.json 2_shot_special
 /50.json m2browning_sawn 
 /gasoline.json flamethrower_crude 
 /nail.json nailrifle

These are player-crafted weapons. They may make good additions to guns_[foo]_improvised

>/12mm.json hk_g80 

Discuss?

>  /metal_rail.json heavy_rail_rifle
 /metal_rail.json rebar_rifle
 /nail.json coilgun

These may need new itemgroup.

>  /nail.json nailgun

These are considered a tool for purposes of itemgroups. See tools.json.

> /ups.json emp_gun
 /ups.json laser_cannon
 /ups.json laser_rifle
 /ups.json unbio_blaster_gun
 /ups.json v29 
 /ups.json v29_cheap

These need a guns_[foo]_energy itemgroup.

>  /bio.json bio_blaster_gun
 /bio.json bio_laser_gun
 /bio.json bio_lightning

These are pseudoguns used by bionics. They aren't supposed to spawn.

>  /gasoline.json flamethrower
 /gasoline.json flamethrower_simple 
 /gasoline.json rm451_flamethrower 

Rot asked about these on the forums recently. He found them in some robots, but they could use wider availability. Maybe the "launchers" itemgroup could be used more often.


This would be a good time to rethink itemgroup rare.
