### ISSUE TITLE
Debug message when crafting blades

### ISSUE THREAD

**Issue by Mecares** [CleverRaven/Cataclysm-DDA#18108]
Debug : Tried to learn unlearnable recipe bladeuncraft
Function : void player :: learn_recipe(const recipe*, bool)
File : src/player.cpp
Line : 12875

I am currently using build 5406

**Comment by Barhandar** [comment]
You're not crafting blades, you're using a bugged disassembly recipe that shows up in the crafting menu for some, unknown to me reason.

**Comment by nanovad** [comment]
It doesn't seem to be on only blades either. It's possible to craft 1 glass shard->glass with no tools in 30s.

**Comment by Coolthulhu** [comment]
Caused by #17876
