### ISSUE TITLE
Add "torque" to engines (Diesel vs. Gas)

### ISSUE THREAD

**Issue by etmoonshade** [CleverRaven/Cataclysm-DDA#18109]
Diesel engines should have a higher pulling capacity, but a lower max speed. Gasoline engines, on the other hand, should have a higher max speed, but carried weight should have more of an effect.

Currently, diesel engines appear to be less-useful - V8D (V8 Diesel) and V8G (V8 Gas) engines are fairly common (especially if you're using the vehicle mods,) but diesel fuel is significantly less common overall. Since the V8G has an "upgrade" to a V12, it seems to me that it's a lot more practical to just go with gasoline.

My suggestion is adding a torque field, which would affect acceleration/max speed - a higher torque number would make weight have less of an effect on acceleration, but also decrease max speed/acceleration.

AFAIK, it's a simplified solution compared to reality, but I imagine that we're not going to be adding a bunch of engines in the first place.

**Comment by BorkBorkGoesTheCode** [comment]
This has nothing to do with the quality of your suggestion, but diesel can be fabricated ingame using a recipe from a book.

**Comment by etmoonshade** [comment]
Point made and taken. This was mentioned in the IRC when we were discussing it actually - despite being able to be fabricated though, gas is still a -lot- more common unless you're intentionally playing with a small city size and get unlucky with gas stations.

One of the automated filling stations will have 200k+ units of gas (granted, assuming you can hack it or pay for it,) and you can get 60-100k units off one of the "regular" filling stations. The former gas station doesn't even have diesel, and the latter seems to have 1-3 pumps of it.

And, of course, with a rubber hose, gasoline is quite plentiful. :D

**Comment by Coolthulhu** [comment]
Someone needs to do the math.
Suggestions that are just "x needs to be better/worse/more y" have low chances of implementation.

Some sort of a formula.
It needs to be something like "acceleration is decreased by `0.3 * weight / torque`".
Alternatively, instead of explicitly writing out the formula, a set of examples can be provided. But those need to be concrete examples, not "more" or "less", but "30% more" or exact values. For example, "a 3 ton vehicle should gain 30% acceleration and 15% safe velocity if its torque goes from 100 to 200". More than one example like that must be provided.

Then verification. Pick 4 or 6 sample vehicles (half gas, half diesel), spawn/construct them in game, note their weight, current acceleration and current safe velocity, then write the torque for their engines, expected acceleration and expected safe velocity.

**Comment by BorkBorkGoesTheCode** [comment]
@etmoonshade I quite like the idea of adding torque to the game. 

Ninja'd.

**Comment by etmoonshade** [comment]
@Coolthulhu: I was tossing it out there in case someone who was familiar with the code had toyed with this idea and could pull the numbers out of their... thin air.

I can do the number crunching if it means someone with some actual talent would be able to tweak the code to fit though.

**Comment by etmoonshade** [comment]
See the table at the bottom for the one problem I found during testing:

The following changes would simply apply a factor to all diesel engines. This would make diesel engines better at carrying heavy loads, but not at carrying them fast.

-----

Option 1:

A couple of code modifications:

vehicle::acceleration
	Multiply the effect of k_mass on acceleration by 0.8 if the engine is diesel. This actually -raises- acceleration, but as far as I can tell, the function is only used in the vehicle::thrust calculation.

vehicle::safe_velocity
	Lower diesel engine modifier in safe_velocity to 50. This lowers the overall max speed (less vroom, more chugga chugga chugga)

vechicle::thrust
	After initializing accel, check to see if the engine in question is diesel, and AFTER checking that accel != 0, multiply by 0.65 (bringing overall acceleration down by 20% vs. gasoline engines)

Pros:
A couple of tweaks to existing code and we'd get the benefits.

Cons:
This doesn't account for mix-and-match engines - one diesel engine and 6 V12 gas engines, and you get all the benefits and drawbacks of diesel, but -add- the benefit of being able to add V12 gas engines for the extra speed/acceleration.

-----

Option 2:

Add in logic to modify the effect of k_mass under vehicle::acceleration similar to what's contained in vehicle::safe_velocity. This allows us to provide a torque value for each engine type - gasoline would be a baseline of 1, modify diesel up to 1.2, and... really, just discuss the other types.

Pros:
This would avoid the overhead of changing all the configs, and make for an easy-to-understand value one way or another (e.g. diesel engines can pull 1.2 times the weight of a gas engine for a given power.) It would also account for all the engines separately - add a gas engine and you don't get the extra pull, and mixing diesel into the mix would be significantly less effective than going pure diesel.

Cons:
This might make for some sweeping changes if we're going for some sort of realism - for example, would an electric engine have a lower torque value? Where do we put a plasma engine? And muscle power might only be able to push a bike - more than that, and it's just too heavy to get the thing started (which actually might not be a bad thing.

-----

Option 3:

Similar to option 2, but add a field in engine configs that specifies a torque modifier.

Pros:
This is the most modder-friendly option - if you want to make a high-torque gas engine, go for it!

Cons:
Probably the most work, and requires a lot of config changes.

-----

None of this gets into the existing game balance itself - a bit of experimentation showed that mass doesn't actually appear to have -that- much of an effect on acceleration until you get to land battleships in the first place:

Test Vehicle:
```
|-|		Boards and quarterpanels, 2x armored wheel
|#|		Boards and quarterpanels, 2x 10L tank, controls/engine/battery
|#|		Boards and quarterpanels, cargo dimension, solar panels

```
Boards/quarterpanels added for second test, hard plating added on all parts for third test. Cargo dimension filled with V12ium for added mass.

```
Safe Speed	Top Speed	Acceleration	Dry Mass	Engine		Displacement	Wet Mass
7mph		24mph		0mph			1210kg		1cyl		0.3L			1220kg
15mph		48mph		1mph			1210kg		1cyl		0.6L			1230kg
24mph		80mph		2mph			1210kg		V-Twin		1L				1255kg
63mph		200mph		6mph			1210kg		Inline-4	2.5L			1280kg
101mph		320mph		10mph			1210kg		V6			4.0L			1310kg
110mph		320mph		10mph			1210kg		V6 D		4.0L			1320kg
165mph		480mph		16mph			1210kg		Inline-6 D	6.0L			1315kg
164mph		520mph		16mph			1210kg		V8			6.5L			1410kg
178mph		520mph		17mph			1210kg		V8 D		6.5L			1430kg
304mph		960mph		30mph			1210kg		V12			12.0L			1510kg

7mph		24mph		0mph			5363kg		1cyl		0.3L			5373kg
14mph		48mph		1mph			5363kg		1cyl		0.6L			5383kg
24mph		80mph		2mph			5363kg		V-Twin		1.0L			5408kg
60mph		200mph		5mph			5363kg		Inline-4	2.5L			5433kg
97mph		320mph		9mph			5363kg		V6			4.0L			5463kg
106mph		320mph		10mph			5363kg		V6 D		4.0L			5473kg
159mph		480mph		15mph			5363kg		Inline-6 D	6.0L			5468kg
159mph		520mph		15mph			5363kg		V8			6.5L			5563kg
172mph		520mph		16mph			5363kg		V8 D		6.5L			5583kg
294mph		960mph		28mph			5363kg		V12			12.0L			5663kg
	
5mph		24mph		0mph			35363kg		1cyl		0.3L			35373kg
11mph		48mph		0mph			35363kg		1cyl		0.6L			35383kg
19mph		80mph		1mph			35363kg		V-Twin		1.0L			35408kg
48mph		200mph		3mph			35363kg		Inline-4	2.5L			35433kg
78mph		320mph		5mph			35363kg		V6			4.0L			35463kg
84mph		320mph		6mph			35363kg		V6 D		4.0L			35473kg
127mph		480mph		9mph			35363kg		Inline-6 D	6.0L			35468kg
127mph		520mph		9mph			35363kg		V8			6.5L			35563kg
137mph		520mph		10mph			35363kg		V8 D		6.5L			35583kg
235mph		960mph		17mph			35363kg		V12			12.0L			35663kg
```

After looking at the numbers, I'd (personally) be better-served by just modding in a V12 diesel engine, and dealing with the awesome^H^H^H^H^H^H^Hunrealistic acceleration. I'm going to leave this here if someone else (with way better knowledge of game balance) wants to flesh it out to fix the mass issues that are brought up in the table along with some sort of torque number.

**Comment by Coolthulhu** [comment]
What do you mean by
> modify the effect of k_mass

`k_mass` is a multiplier. You mean changing the way it is applied (from a multiplier to something weird) or changing the way it is calculated? Also, what about multiple engines with different effect of k_mass?

> None of this gets into the existing game balance itself - a bit of experimentation showed that mass doesn't actually appear to have -that- much of an effect on acceleration until you get to land battleships in the first place

That would mean the whole deal needs to wait until mass starts being important. Or make it important in the process of adding torque.

**Comment by etmoonshade** [comment]
> k_mass is a multiplier. You mean changing the way it is applied (from a multiplier to something weird) or changing the way it is calculated? Also, what about multiple engines with different effect of k_mass?

Essentially the same as in option 1, but with different multipliers (torque values) based on how much torque the engine "should" have.

> That would mean the whole deal needs to wait until mass starts being important. Or make it important in the process of adding torque.

I'm glad you agree with me.

**Comment by Coolthulhu** [comment]
> Essentially the same as in option 1

Which is ambiguous:
> Multiply the effect of k_mass on acceleration by 0.8

Multiply effect of multiplier? You mean something like `acc = acc * k_mass * 0.8 + acc * 0.2`?

**Comment by etmoonshade** [comment]
In this line:
```
if( ( engine_on && has_engine_type_not( fuel_type_muscle, true ) ) || skidding ) {
return safe_velocity( fueled ) * k_mass() / ( 1 + strain () ) / 10;
```

I was thinking to change it to:
```
if( ( engine_on && has_engine_type_not( fuel_type_muscle, true ) ) || skidding ) {
return safe_velocity( fueled ) * ( <torque> * k_mass() ) / ( 1 + strain () ) / 10;
```
with <torque> being whatever multiplier - 0.8 in the example I gave. I might be mistaking k_mass for a "bad" multiplier that should be reduced though - unfortunately, digging through chunks of code isn't exactly my strong suit.

**Comment by Coolthulhu** [comment]
> I might be mistaking k_mass for a "bad" multiplier that should be reduced though

Yep
`k_mass` is a value between 0.0 and 1.0 that velocity and acceleration are multiplied by (acceleration is multiplied by it twice).

**Comment by illi-kun** [comment]
We have some progress in engine rewriting, thanks to @mugling.
