### ISSUE TITLE
Reinforcing bandages creates more bandages.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#18113]
Per http://smf.cataclysmdda.com/index.php?topic=13101.0

"Just a random odd bug I stumbled into this morning, I have a character in 0.C-17621-g817d3a5 that, when I use a wooden needle (activate option), not only are Bandages select-able; but reinforcing them actually creates MORE of the bandages."

Can confirm in 5412. Does require a rag.

**Comment by Xnfinity** [comment]
Same happens with first aid kits with a welder

**Comment by molkemon** [comment]
Can also confirm this bug per 5417, Windows Tiles.
