### ISSUE TITLE
slow menus

### ISSUE THREAD

**Issue by orbisvicis** [CleverRaven/Cataclysm-DDA#18118]
Long menus in tile mode are too slow to be usable (short menus like [Option] from the title screen, have some lag as well). Examples from the crafting menu:
- Switching between Electronics:CBMS <-> Electronics:Tools is laggy, even though both categories are empty (no entries yet)
- Scrolling down the  Other:All category (which has many entries) is incredibly, painfully slow

This is only in hardware mode, with a git build from today (fa09b808154dbaeb219aa3cb030c475d28f7dccb). Software mode is fine... but the tile graphics are glitchy in software mode. This is with the nvidia 340.96 driver for a geforce 8800GT.

I know the menus have changed, but I didn't have this problem with builds from about a year ago, even though the menus had approximately the same number of entries (for starting characters).

OS: Fedora 24

**Comment by kevingranade** [comment]
If changing the render mode affects the problem, I can only think of one
likely cause, excessive refreshes.

**Comment by schmithub** [comment]
I have the same issue.  If I use hardware rendering mode, menus like craft menu are very slow to move around in.  But if I use software rendering mode, the game is nice and smooth, but some textures show up with gaps.[http://imgur.com/a/vIlRq](url)

**Comment by Leland** [comment]
Closing due to lack of discussion. We do have a place of discussion for slowdowns, see #19304. If anyone feels that menus in particular deserve their own issue due to slowness, feel free to ping me here and I'll reopen.
