### ISSUE TITLE
Martial arts stuff

### ISSUE THREAD

**Issue by PeevedPenguin** [CleverRaven/Cataclysm-DDA#18117]
The boxing counter doesn't actually work since it isn't doesn't actually have a way to trigger the counter. Krav maga has a technique that isn't listed under it's techniques. I would submit fixes for this, but I don't know how to actually accomplish that on GitHub, so here's a dropbox link to the fixes. 
[https://www.dropbox.com/s/mkgcsdieilaxhdl/icannotintogithub.rar?dl=0](url)

**Comment by DaliTimelord** [comment]
Here is a link that gives you all the information [needed to start using Github.](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/CONTRIBUTING.md)

Without having to install Git Bash or doing a fancy dance, you can go to the [main page](https://github.com/CleverRaven/Cataclysm-DDA), click on Fork in the upper left, go to your own page, click on Branch, click on "Find or create a branch..." type in an arbitrary name for the branch, create the branch, then work on that branch. When you want to submit a complete change, you would go to [CleverRaven's pull requests](https://github.com/CleverRaven/Cataclysm-DDA/pulls), click on new poll request, click on "compare across forks", then select your own branch from your own fork of the game.

Also, the link doesn't work for me.

**Comment by illi-kun** [comment]
@PeevedPenguin please try to put your fixes in PR, that will be very useful.

**Comment by Leland** [comment]
Uploaded @PeevedPenguin's RAR here so that it isn't lost at some point. It doesn't look like they've been active in some time, so I'll give this a shot myself at some point and see it fixes it.

[icannotintogithub.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1032611/icannotintogithub.zip)
