### ISSUE TITLE
Rats have the vomiting mutation but in real life are completely unable to vomit.

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#18110]
In the game, the Rat mutation tree contains the vomitous mutation, but in real life rats are completely unable to vomit.

They have a powerful barrier between their stomach and esophagus, can't independently control their diaphragm and don't have a neural connection between their brain stem and vicera. From: http://www.ratbehavior.org/vomit.htm

**Comment by Rivet-the-Zombie** [comment]
Good catch!

**Comment by Soyweiser** [comment]
According to my rat keeping friend "Yes, rats cannot vomit. They do pica instead. Eating stuff like dirt etc to stop nausea".

Well... That will be an interesting mutation.

**Comment by Rivet-the-Zombie** [comment]
>One issue with just removing this from the mutation category. It is a preq for the Intestinal Fortitude (EATPOISON) mutation. So if we remove that, rats cannot get that anymore.

Or we could re-route around it using some other/new mutation.

**Comment by Soyweiser** [comment]
Yeah, I don't know enough about how the requirements of mutations work to easily fix that.

**Comment by Rivet-the-Zombie** [comment]
I like that idea!

**Comment by Soyweiser** [comment]
Yeah, me too, when this issue is fixed, and there is no pica addition, lets not forget to add that to a different issue then. (when this one is closed).

**Comment by Reclusive-reptile** [comment]
Should pica allow the mutant to eat wood? Rodents of all types chew on wood to maintain dental health.

**Comment by Reclusive-reptile** [comment]
Also, why does nausea lead to intestinal fortitude? Wouldn't strong stomach make more sense?

**Comment by Soyweiser** [comment]
There are several notes in the mutation file that show that going from nausea to intestinal fortitude was a conscious choice.

`"note" : "Yes, you eventually got over the massive digestive upset.  Mutations aren't easy on a system!",`

And allowing you to eat wood while nice would just add more special cases. I would be happy with just one option being implemented at all. (Wood prob also needs fangs)

**Comment by Leland** [comment]
This thread hasn't seen an update in 9 months. Closing for now. If anyone is still interested, I can reopen... or feel free to just make a new issue!

**Comment by realhoodthug** [comment]
I like the idea of this
