### ISSUE TITLE
Map extra firearms have no magazines.

### ISSUE THREAD

**Issue by Reclusive-reptile** [CleverRaven/Cataclysm-DDA#18122]
Like it says on the tin. None of the map extra item groups have the magazine field filled out so map extras (drugdealers, helicopter crash sites, etc.), Have magazines.
I don't believe it is standard operating procedure to deploy military units into active combat zones with no ammo.

**Comment by Soyweiser** [comment]
Wait there is more: 
http://smf.cataclysmdda.com/index.php?topic=12996.msg280553#msg280553
Vaults also don't have them. Spider. Should be easy enough to fix.

**Comment by Zilenan91** [comment]
I was wondering why none of the weapons I ever found at helicopter crashes never had any ammo or magazines in them.

**Comment by Reclusive-reptile** [comment]
This more difficult than it would first appear. In my own testing, giving magazine probabilities to the related .json entries fixes all but one case, when helicopter crashes spawn military arms. The helicopter special calls item groups inside of an array that doesn't have a magazine argument implemented so changing .json has no effect on the items spawned in that one case.
