### ISSUE TITLE
Dead electric bicycle: expected behavior?

### ISSUE THREAD

**Issue by SeanMirrsen** [CleverRaven/Cataclysm-DDA#18124]
So I've found an electric bicycle with a dead battery (as in empty, not broken). It has a foot crank and an electric engine. By selectively disabling the electric engine, the bicycle can be driven when the battery is dead - however, there is no charge trickling into the battery via the installed alternator. Is that supposed to happen? What is the game expecting to happen, exactly? Is the alternator hooked up to the electric motor? Or is the foot crank not producing enough energy for generating power?

**Comment by zwparchman** [comment]
I've noticed this as well. Removing the electric motor will enable charging. This seems to be caused by the electric motor still pulling charge even though it is off. I've just confirmed similar  behavior with a gas/electric hybrid I built. 

Currently disabled engines still consume resources.

**Comment by zwparchman** [comment]
You might want to double check the engine status. I've been bitten by that before. I thought you found a bug since my hybrid seemed to be doing the same thing, but somehow the engine turned back on.
