### ISSUE TITLE
Deathmobile won't move - "too heavy" despite insane amounts of engines

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#18125]
**RESOLVED! I managed to unbug the vehicle by searching for my vehicle name (NX-1) in the save directory with notepad++, and in the map file it was found i changed engine_on: false to engine_on: true, loaded up the save, engines were running and now everything is back in working order. However, since this does not explain how the game got stuck in the bugged state, this should probably still be investigated.**

**There is an additional oddity at work here: If you edit the save so the engines run on load, they do so and you can drive around normally. If you don't move and turn off the engines, you can not restart them again, the error is back then. However, if you drive ahead just a few tiles and then turn off engines, they remain unbugged and you can then use the vehicle as normal).**

**My best guess is that it has something to do with item overflow to adjacent tiles (in this case caterpillar tank tracks) which somehow bugs out the vehicle when stuff overflows onto vehicle tiles, but I couldnt test to reproduce yet).** 

Hi,

I'm currently building a death mobile and during construction, I noticed that it won't move. It says it's too heavy for my engines, but very clearly this is nonsense. 3 enhanced electric, 6 6,5l V8 Diesel and 3 V12 (I cheated those, but they are still not enough). It started out using Tank Treads, but I switched them out for wheels, which reduced the weight further, but the car still won't move. 

What's also irritating is, that the engines don't seem to start up at all. When I engage vehicle controls, it just tells me I'm taking them. There is no engine startup notification, and it seems they aren't actually running (no noise/smoke generated). I have no idea what could cause this. 

The project builds upon a previous death mobile, which ran just fine, even partways through construction, but somewhen the last 3 hours it stopped moving. 

I have tried almost everything. Disabling various engines, physically removing them (if I remove all engines, it correctly states the vehicle doesn't have engines if I try to drive). 

Here is the save: https://www.dropbox.com/s/exbu5sjzro8vfb3/Bowmanstown.7z?dl=0

Screenshot of vehicle: http://i.imgur.com/cvMMZDL.jpg
Interestingly, if I grab the controls and then stop driving and look at the vehicle screen before moving a tile, acceleration will suddenly say 0 kp/h/t. As soon as I move a tile in the car, the previous value is shown. 

Edit: Still won't move with 12 V12 Engines

Happens in newest experimental (5417), Windows Tiles,  I'm using the Vehicle Additions Mod. 
The exact error message is The %s (vehicle name) is too heavy for its engine(s)!
This message is generated only on this line: 
https://github.com/CleverRaven/Cataclysm-DDA/blob/e7509f1fa63f8dc4d5816198b165f72e0bfe0d65/src/vehicle.cpp#L4076

**Comment by mightyagrippa** [comment]
Replicated in windows graphical 5417. The curious thing is that attempting to start the engines from adjacent to the controls does nothing even when the car is stripped down to solely electric engines. You can ^, turn on controls all day and it gives you no messages or startup.

**Comment by molkemon** [comment]
Some more testing: As I said before, if I remove all engines I get the correct message (no engines). However, if I install just one engine, and I have no batteries or tanks installed, I still get the "regain control" message instead of "no fuel" or "no battery". The vehicle just seems to be stuck in "on" mode, except the engines aren't on at all..

**Comment by ZombiesAreUs** [comment]
Having nearly lost a character to the very same bug, here's what I can say after a bit of testing. By chance I found out that if a Hippie Van's right trunk position is destroyed it can't move. I debugged another Hippie Van and tried to destroy the left one instead, and it moved fine. Turning on debug mode, I noticed that the pivot line on the Hippie Van is on the right trunk position. Tried destroying the pivot position of several other vehicles. They all run fine afterwards until you open or close a door, upon which point they become "too heavy".

Hope this can help someone more knowledgeable than me diagnose the source of problem.

**Comment by belazzz** [comment]
Having the same issue with a vehicle I built from scratch. The mass is about 4 tons and the engine is V12. Editing the save as described above worked, but only until the engine was stopped, after that I could not start it again.

**Comment by Coolthulhu** [comment]
Could be some weird mass recalculation putting it outside the collision box or something like that.

**Comment by mugling** [comment]
OP has edited their premable as:

> RESOLVED!
