### ISSUE TITLE
Setting an item's to_hit to 0 in json breaks everything

### ISSUE THREAD

**Issue by Izicata** [CleverRaven/Cataclysm-DDA#18130]
When you try to play the game, it throws what must be hundreds of errors at you, saying it can't find tons and tons of stuff, including: building types, monster types, vehicle frames, nails, sheet metal, scrap, water, ammo types, tools, food, etc.

If you start a new game, it leads to a "nothing found" error, no game, and no way to gracefully terminate the process; you have to close the window. If you load an old save, it's broken. Tons of stuff is undefined and missing item definitions, vehicles don't have frames or engines, and it segfaulted when I tried to examine the cargo space with my guns.

Something major is broken, probably with how the game loads json files.

**Comment by Noctifer-de-Mortem** [comment]
Something similar happened to me and was somehow fixed when I changed all items with hit_bonus of 0 to 1 in the tools.json

**Comment by Izicata** [comment]
Oh wow, that really does fix it.

**Comment by Noctifer-de-Mortem** [comment]
#18023 may be to blame?

**Comment by Izicata** [comment]
Not really. Items have a default to_hit of 0 so explicitly setting it to 0 in the json entry is redundant, but that shouldn't break everything like this.

**Comment by DaliTimelord** [comment]
I shall forever remember this as the day half my car disappeared.

**Comment by Izicata** [comment]
I believe this has been fixed, so this issue can be closed.
