### ISSUE TITLE
'Safemode' or 'Safe mode'

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#18148]
We use 'safemode' in places and 'safe mode' in others. Just looks a bit strange. Which one is it?

**Comment by OzoneH3** [comment]
Pretty sure it's "Safe Mode" after googling and I F...d it up in #17916.
I blame my native language for concatinating all the words. (Donaudampfschiffahrtsgesellschaftskapitän)

**Comment by Soyweiser** [comment]
Yeah, concatenation is better :)
