### ISSUE TITLE
Mod shotgun loudness bugs

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#18156]
The double barrel pipe shotgun has a loudness field.

**Comment by illi-kun** [comment]
Could you expand your report? What are bugs you're mentioning in the title?

![shotgun](https://cloud.githubusercontent.com/assets/5421954/18566266/e53b1412-7b9b-11e6-90a1-775dbc18501a.png)

**Comment by BorkBorkGoesTheCode** [comment]
The combination_gun_shotgun_pipe and ksg_aux_shotgun underbarrel gunmods have "loudness" fields.
