### ISSUE TITLE
Some vehicle armors have too little durability

### ISSUE THREAD

**Issue by HeadWar** [CleverRaven/Cataclysm-DDA#18159]
Hard plating has 1000, the same as steel plating and compared to the 2300 of the heavy steel ram.
Military plating has 2000, as compared to the 3250 of the military composite ram.
The spiked plating has 500, compared to 900 for the spiked ram.

It seems reasonable that the rams and the platings have equal durability, since they are made from the same components and have the same weight.

Also, what's up with the superalloy plating (and ram)? Admittedly slightly lighter than steel plating, but also slightly less durability at 900.

**Comment by Coolthulhu** [comment]
Rams have unupdated values. They are pure HP and no damage reduction.

**Comment by HeadWar** [comment]
Wood, steel and superalloy platings/rams have the same values though.

I don't know how the damage reduction works. But unless the hard plating has more of that than the steel plating, it is still very odd that they have the same durability.

**Comment by Izicata** [comment]
You can look at the damage reduction values in the [vehicle parts json.](https://github.com/CleverRaven/Cataclysm-DDA/blob/8244744303c1de2accecaf42c6af026e7ce7eb52/data/json/items/vehicle_parts.json). Hard plating has 15 all DR, steel plating has 10 all DR, superalloy plating has 12 all DR. Pretty sure vehicle part DR should work just like player armor DR; if that part takes damage, it's reduced by the part's damage reduction.

**Comment by HeadWar** [comment]
I guess it would be nice if the DR values were displayed somewhere then. =)

**Comment by Leland** [comment]
Closing - non-issue. If you want, feel free to open a new issue regarding better presentation of DR values.
