### ISSUE TITLE
Vehicle batteries increase weight when powered.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#18158]
That just is a bit silly: https://i.imgur.com/lA4J4ue.png (image via reddit user Muffinut).

My suggestion would be to add a NO_CHARGE_WEIGHT flag.

I'm also wondering about this in battery.json why do some batteries have flags ( [ "NO_SALVAGE", "NO_UNLOAD", "NO_RELOAD" ] ) and the others don't.

**Comment by Oskar636** [comment]
This issue was made first #12764, the former needs some label changes.
