### ISSUE TITLE
CDDA Experimental 5413 reloading with magazines duplicates the magazine

### ISSUE THREAD

**Issue by Samtex98** [CleverRaven/Cataclysm-DDA#18160]

**Comment by Zireael07** [comment]
Again? :(

**Comment by Samtex98** [comment]
I was reloding a glock19 with a spare mag and suddenly a error pop up and i got a duplicate of the magazine with ammo. I tested with other weapons like the Scar-H in debug mode and still got the problem.

**Comment by Rivet-the-Zombie** [comment]
I'm not sure if it's so much 'again' as it is 'been there all along but only pops up occasionally'.

**Comment by mugling** [comment]
Same problem, source is still unfortunately unknown
