### ISSUE TITLE
Only unloaded vehicle parts can be installed

### ISSUE THREAD

**Issue by Harold76** [CleverRaven/Cataclysm-DDA#18182]
M249 gun does not appear to be installable on vehicle, despite having all required tools and available layer on vehicle

**Comment by Mecares** [comment]
Known bug, just take out the ammo belt or magazine and it should work.

**Comment by Harold76** [comment]
Awesome.  Thanks

**Comment by mugling** [comment]
Duplicate and also fixed in `master`
