### ISSUE TITLE
Robot Butlers for Mansions

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#18188]
Hey all us crazy folks over on the IRC thought it would be rad to have hostile robot butlers and possibly robot maids to mansions to make them a bit more of a challenge to secure. Since these locations are commonly filled with very usefull items. 

Also we could put in a chance for the robot butler to be named Jenkins as a cameo to the automated build system for CDDA. 

Please tag this as Enhancement.

**Comment by Chezzo** [comment]
Awesome, I would totally make a this guy in butler clothing:

![Not a butler, but might be](https://camo.githubusercontent.com/c81c96dccc5813bad5be9f270882d98a850b2b14/68747470733a2f2f7261772e6769746875622e636f6d2f64726269672f63617461626f742f6d61737465722f6173736574732f636f70706572747562652e706e67)

**Comment by Mecares** [comment]
A Robo Chef with a nice assortment of Knives

**Comment by Izicata** [comment]
Clunky, boxy robo-maids on wheels that someone has managed to fit into a frilly French Maid Dress.

**Comment by crom7** [comment]
Thanks, I just had flasbacks of Rosie from the Jetsons.

**Comment by 2birdie** [comment]
They should ignore you unless attacked if you are also a Butler or Maid, as even robotic Butlers and Maids follow the Caretaker's Code.
(I'm not certain if this should fully be a joke or not.)

**Comment by kevingranade** [comment]
Feel free to add this, but it doesn't really rate a spot in the issue tracker.
