### ISSUE TITLE
Some mod-defined locations (all of Arcana, some of More Locations) not spawning

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#18184]
Tested on different worlds so far with Arcana mod, Seeker of the Arcane scenario. None of the four areas could be found to start in, 

So I decided to jump into a world, hit reveal map, and take a look around. Sure enough, no fucking sign of the arcana locations. As far as I can tell, the mapgen, overmap_specials, and overmap_terrain entries still check out.

Then I got the idea of checking out the More Locations mod, just to ensure it wasn't an issue of no one remembering to check mods when updating something. The multi-story houses were readily apparent, but there were no sign of large military outposts or factories.

**Comment by BorkBorkGoesTheCode** [comment]
Low weights.

Chalice impact "weight": 100
Curious structure: "weight": 300
grove "weight": 300
sanguine "weight": 250
factory "weight": 250

gun basement "weight": 1,000

**Comment by chaosvolt** [comment]
I thought those only affected spawning when multiple items under the same mapgen ID (like the infinite array of houses) are available. Overall spawning for isolated, non-city structures is supposed to be control by the "occurrences" and "distance from cities" properties of overmap_specials.

Additionally, back when I was playing this game regularly, I ONLY had trouble starting in a modded-in location if the overmap definitions were put together improperly. So that implies that the way these structures spawn has been changed, with unforeseen consequences.

**Comment by chaosvolt** [comment]
...nope. Tested adding an extra 900 to the weights for all arcana structures, it doesn't seem to have any effect. Unless I have to do something moronic like boost the weights to 9001, then I'm afraid that is incorrect.

**Comment by BorkBorkGoesTheCode** [comment]
Which experimental are you using? I get the buildings without buffing the weights in 5026.

**Comment by chaosvolt** [comment]
5436, Windows graphical. Does it work for you in that version?

**Comment by chaosvolt** [comment]
I am furthermore feeling kinda dumb. City size seems to be affecting this. It happens less under current conditions if city size is left at 4, but at 1 it drops sharply.

I thought non-road-linked structures were meant to work even when cities are disabled?

**Comment by Leland** [comment]
With #20232 and #20373 this _should_ be fixed. @chaosvolt is this still an issue?

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed and most likely fixed.
