### ISSUE TITLE
Missions fail to complete

### ISSUE THREAD

**Issue by ifonly17** [CleverRaven/Cataclysm-DDA#18186]
Hello,

Version: 0.C-17954-g2a6ae47 [tiles]
OS: Windows

Bug: Missions fail to complete. I have mission "Find Corporate Accounts" and just found "Corporate accounting ledger" book, but mission fail to complete when I talk with NPC. I only receive 2 options:

a: "Not yet"
b: "No. I'll get back to it. Bye!"

Same happened few days ago with "Kill Zombie Mom" mission. I killed her, but mission failed to complete

Ps. Me English sucks, sorry for that

**Comment by Leland** [comment]
Closing due to age of this ticket and lack of info. I have a hunch this is a case of #20089, however.

If this truly is a discrete case, I recommend opening a new ticket with further details.
