### ISSUE TITLE
Survivor's map and survivor's note are craftable

### ISSUE THREAD

**Issue by LisacPisac** [CleverRaven/Cataclysm-DDA#18185]
When you search the crafting window for "survivor", 2 of the recipes are "survivor's map" and "survivor's" note and they are "not yet memorised". Crafting them results in a debug message that says you tried to memorize  an uncraftable (or something, I forgot) recipe. It shouldn't be possible to craft either, survivor's maps and notes should be items of interest that only spawn.

**Comment by Rivet-the-Zombie** [comment]
A known bug; recipes that are only supposed to be used fro 'uncrafting' items are showing up in the crafting menu and causing weird debug messages.
