### ISSUE TITLE
Crafting error - ingredient burns away while crafting in progress, cannot be found.

### ISSUE THREAD

**Issue by SeanMirrsen** [CleverRaven/Cataclysm-DDA#18191]
The situation is thus. The survivor stands near a burning brazier filled with heavy sticks, only some of which are burnt. The survivor attempts to craft a stone shovel, which takes a decent chunk of time - the only heavy stick usable as a crafting ingredient for the shovel is in the brazier. While the crafting is happening, the fire in the brazier burns down the sticks. The result is a debug error message - item cannot be found.

**Comment by illi-kun** [comment]
This is well known limitation of crafting system.

**Comment by SeanMirrsen** [comment]
The limitation is okay, it should probably just be a handled one rather than throwing a debug message.
