### ISSUE TITLE
Tried to install bionic bio_blindfold already installed

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#18198]
My poor bionic prepper class, who has been stripped of his knife and his flashlight, is throwing an error:

Tried to install bionic bio_blindfold already installed

**Comment by Noctifer-de-Mortem** [comment]
I recently did some changes to professions and was told that classes with the Anti-glare Compensators bionic need to have the Optical Dampers bionic as well since they come as a package but maybe that is included automatically and cause errors when included in the profession.
