### ISSUE TITLE
Hunter, Predator, Apex Predator, remembering hunts tied to skill rust level

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#18196]
Look at game::rustCheck()

Before the check for the `Your heart races as you recall your most recent hunt.` line. There is this check:
`if (u.rust_rate() <= rng(0, 1000)) {
            continue;
        }`
This means that it becomes less likely to recall hunts the higher the skill rust setting. Which is a bit of an odd game mechanic. This also means that the line:

"13 combat skills, 600 turns/hr, 7800 tests/hr. This means PRED2/PRED3/PRED4 think of hunting on average every 8/4/3 hours, enough for immersion without becoming an annoyance."

Is probably an overestimation on about how often this happens.

**Comment by Night-Pryanik** [comment]
Skill rust was overhauled lately, there is no more check like this in the function.
