### ISSUE TITLE
Mutated bodyparts in cloning vats rot

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#18194]
Except for the cold labs of course, mutated bodyparts inside the cloning vats rot away. Making it hard for players to find them.

**Comment by Coolthulhu** [comment]
Honestly they only really make sense for lab starts.
Everyone else who raids a lab will likely be at the point where eating mutated body parts is a bad idea.

**Comment by Zireael07** [comment]
I thought eating mutated body parts is a bad idea all around? :laughing:

**Comment by Coolthulhu** [comment]
In the lab, there are 4 sources of nutrition bigger than snacks: humans, mutant body parts, zed chunks and blob globs. So it's either eating some of those or starving.

**Comment by Leland** [comment]
Stalled discussion for going on 8 months. Closing for now – please ping me here to reopen if there's still interest.
