### ISSUE TITLE
Clean water is lost if you cook all the water from a container

### ISSUE THREAD

**Issue by LisacPisac** [CleverRaven/Cataclysm-DDA#18190]
When there is, for example, 9 water left in a toilet and I cook all of it, I get no prompt on what to do with that water and it simply disappears.

**Comment by Night-Pryanik** [comment]
Confirming on 0.C-6421, Windows XP SP3 x86, curses.

**Comment by lancewf** [comment]
I could not reproduce the bug on 0.C-31950-gd1b91f3-dirty.

**Comment by Night-Pryanik** [comment]
Closing then. If someone manage to reproduce, ping me.
