### ISSUE TITLE
craftable item appears only when searching w/ F  (exp build 5429)

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#18205]
Don't know if this is an actual bug but it does seem to be different behavior than previous versions.  Either way the item should appear craftable in the normal menus of tools, weapons, etc.  In the tradition of showing everything thats possible.

I searched for something that used a spike in its components, and steak knife appeared.  I did not see steak knife highlighted in any list (in white) before searching.

**Comment by busterbogheart** [comment]
Breaking news-- Attempting to craft the knife gives an error "Tried to learn unlearnable recipe knife_steakunlearn" something or other.

**Comment by busterbogheart** [comment]
And it said i used a book as a reference which is impossible

**Comment by Soyweiser** [comment]
Same issue as #18108
