### ISSUE TITLE
Tear gas hacks are broken

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#18218]
On fc2d82b619d4e53285ff21c17bf1d09a1240f350, tear gas hacks follow you around, but never do their kamikaze attack, even after waiting 50+ turns next to it.

**Comment by Leland** [comment]
Can confirm. I've faced this with grenade hacks as well.

**Comment by Night-Pryanik** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/f5723a09e75d9053b55fbb83edb2ef6181285682/src/monattack.cpp#L4283

That's because game searches for `use_action: transform` for tear gas hack, but it has `countdown_action: transform` instead.
