### ISSUE TITLE
NPC scenario flags proposal

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#18220]
I propose scenario flags that determine what npcs spawn there. For example, lets say we add a flag in ght Helicopter Crash scenario that makes it so that the npc that spawns there is also a soldier instead of the generic spawn npc that says "At least we go this shelter.". Other examples would be firefighters in the Last Firefighter scenario , cops in the Assault in Precinct Z, looters in the Missed scenario, etc. Flag specific npcs would have their dialogue tailored for their scenario, for exmple, the Helicopter Crash npc could say, "I hope nothing broke during the crash." Since they are flags future scenarios/ mod scenarios can use them as well.

**Comment by Zireael07** [comment]
Make the title more informative, such as 'Scenario flags determine NPC spawn',
Otherwise I like the idea.

**Comment by Leland** [comment]
Closing due to lack of recent discussion. Feel free to ping me here to reopen if there's interest in continued discussion/development.
