### ISSUE TITLE
UPS conversion mod disappears when "Disable distinct gun magazines" mod is added

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#18238]
Verified on build 5454 / 0.C-18039-gf84b927 from yesterday.
Steps to reproduce:
Create a new world, add the "Disable distinct gun magazines" mod, start game. Wish for "What's A Transistor" book and set your electronics skill to 3+, read the book. UPS conversion mod will not be in the recipes, while it's present without the magazines mod.

**Comment by mugling** [comment]
I'm reluctant to work further on the disable distinct gun magazines mod as it was originally provided whilst magazines were still buggy
