### ISSUE TITLE
The wrong item is selected in the reloading menu

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#18236]
1. Get a circular saw (in your inventory, not wielded) and 100 batteries.
2. Drop 50 batteries on the ground.
3. Reload the circular saw. When the menu shows up, select the 50 batteries that are in the inventory.
4. The ones on the ground are used instead.

Reloading guns works as expected. Reloading anything that's wielded also works as expected.

**Comment by Oskar636** [comment]
Can't reproduce in build 5861

**Comment by sethsimon** [comment]
Neither can I; I guess this was fixed without linking the issue.

**Comment by Oskar636** [comment]
I think somebody was reworking either how batteries work or ammo works.
