### ISSUE TITLE
Mainline parts of blazemod

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#18248]
Following #17456 and further cleanup some parts of blazemod could be moved to mainline. Suggestions?

**Comment by Noctifer-de-Mortem** [comment]
I believe the turret system is a good idea.

**Comment by Chezzo** [comment]
I just did a lot of tiles work for blazemod, so I wouldn't mind. 

Parts of blazemod are pretty silly though.

**Comment by Blaze-whatdoyoumeanitsalreadytaken** [comment]
Off the top of my head, the turret frame system and the ability to mount any gun if a turret frame is installed could get in as is, maybe tweaking the recipe and skill required. That would free me from having to update it with all the new guns coming in.

I'm going to stick Blob parts are going to moved to another "mutation mod" that adds things to various mutation; now that those are JSONized.

**Comment by BorkBorkGoesTheCode** [comment]
Please mainline the treads.

**Comment by Coolthulhu** [comment]
> That being said, the fact that it's piggybacking off of the "needs battery mount" flag is going to be ugly somewhere down the line.

It wouldn't be hard to turn the battery mount hack into a pair of "needs to be mounted on slot" and "provides mount slot" fields.

**Comment by mugling** [comment]
> It wouldn't be hard to turn the battery mount hack into a pair of "needs to be mounted on slot" and "provides mount slot" fields.

I have a more robust solution in the pipeline

**Comment by kevingranade** [comment]
Lapsed suggestion thread.
