### ISSUE TITLE
There should be a way to enable Wander Spawns in the middle of a game

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#18250]
I'm not sure if this should go here or on the forums, but this would be a really neat thing to do. I think you can already do it by messing around in your savefile and reloading the world as well.

**Comment by mugling** [comment]
Why would that be necessary?

**Comment by Chezzo** [comment]
I could have sworn that you were already able to do this. The way I did it was, turned hordes on in the world menu of the options, then quit to desktop.

**Comment by Karlieb** [comment]
> I could have sworn that you were already able to do this. The way I did it was, turned hordes on in the world menu of the options, then quit to desktop.

This has worked for me too.

**Comment by Zilenan91** [comment]
Oh wow if it's that simple then nevermind, thanks.

**Comment by Coolthulhu** [comment]
Does it actually work though?
From what I can tell, it "enables" hordes, but doesn't generate any.

**Comment by zanderzhng** [comment]
yeah it says must reset world directory after changing for it to take effects.
