### ISSUE TITLE
Weapon info

### ISSUE THREAD

**Issue by Xnfinity** [CleverRaven/Cataclysm-DDA#18267]
Weapons should probably give some information about being a unarmed weapon or durable melee weapon;

**Comment by DaliTimelord** [comment]
Sort of like how clothing and armor are descriptive in their functions, like being waterproof and suitable for abuse?

It wouldn't hurt to add to the game for any reason.

**Comment by Leland** [comment]
Closing - old and no movement. Feel free to ping me here if there's still interest, or make a new issue.
