### ISSUE TITLE
Squeamish trait retained in vanilla, forces filth effects if picked

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#18264]
The pull request https://github.com/CleverRaven/Cataclysm-DDA/pull/18233 seems to have had unintended consequences. It took me some trial and error to realize that the Squeamish trait had been simply left in vanilla, and that picking that trait automatically forces filth behavior on the player. Failure to adequately test on my part.

**Comment by DangerNoodle** [comment]
This is odd. It appears to be due to the use of some other mod besides Filthy Clothing causing this. Further testing without any of the normal mods I prefer revealed this.

**Comment by DangerNoodle** [comment]
No. That was a failure on my part. It seems that the Squeamish trait was retained in vanilla, and my neglecting to notice I had picked it was the cause. I should've paid attention to this.

**Comment by Coolthulhu** [comment]
Squeamish itself is more or less OK, it's the morale penalty that was bad.

**Comment by DangerNoodle** [comment]
I suppose it is acceptable then. Having it suddenly cause filthy clothing behavior when picked is peculiar behavior though. I could not tell whether or not this was intentional or a bug.
