### ISSUE TITLE
ml is too small of a unit for display

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18279]
Displaying it as liters would be much better. No one needs 1ml precision.
It gets really bad with big items, with a tail of zeros behind them.

**Comment by ZenZen2** [comment]
Does this new ml or l make things easier? from my view as a player its just confusing.
Im sure i will get used to it. But i would love an option to switch back to the old volume system. a switch just like with kilometer vs miles or 12h vs 24h.

**Comment by BevapDin** [comment]
> Im sure i will get used to it. But i would love an option to switch back to the old volume system. a switch just like with kilometer vs miles or 12h vs 24h.

Well, the idea is to enable items with volume precision of 1 milliliter. It's not just a display thing, items like USB sticks or lighters have a non-zero volume now (1 milliliter). Displaying this in the old system would at best lead to confusion (and the problem of rounding).

**Comment by mugling** [comment]
How about `%.2fL` similar to how we store in grams but display in kilograms?

**Comment by ZenZen2** [comment]
Ok that makes sense now. Thanks for the explanation.

**Comment by Karlieb** [comment]
Maybe show it in liters with a mouseover (or tab over) showing the amount in ml?

**Comment by AdonaiJr** [comment]
My suggestion is along:

"exhibit volumes just like it used to be" for volumes >1, but for volumes <1 exhibit it in "ml" or ".15", ".25" like mugling suggests.

Everything is defined by multiples of 250ml, the units we already are used too. I think it doesn't need to change on UI, it can change only internally to address the problem of 0 vol items.

(sorry the weird grammar/english)

**Comment by Treah** [comment]
Why not keep the ML calculations but display in the old volume system. This way you get the benefits of having 1ml precision without interface clutter.  You can then display the precise volume somewhere in the description so its known that its not actually 0 volume.

**Comment by mugling** [comment]
> Why not keep the ML calculations but display in the old volume system.

> Displaying this in the old system would at best lead to confusion (and the problem of rounding).

**Comment by mightyagrippa** [comment]
> Displaying this in the old system would at best lead to confusion (and the problem of rounding).

I disagree, at best it would resolve the confusion behind players suddenly having an established system replaced with 2000 mL of broadsword etc.

**Comment by Treah** [comment]
Hmmm yeah i guess that would be a bit confusing since it would display a volume of 0 and the player would wonder why they can't put more of something into their inventory when it shows Volume: 11/12. 

Maybe displaying it in L would be better and using the . to give fractional amounts is better.
