### ISSUE TITLE
Debug: do_reload failed: item could not be reloaded

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#18278]
NPC joined me and after a shot of his gun this debug came up:

Debug: do_reload failed: item could not be reloaded
FUNKTION : void npc::do_reload(item&)
FILE : src/npcmove.cpp
LINE : 3037

Game stops working.

Version 5466
mods:
medieval
PK Reimagining (latest from forum)
filthy
npc dont eat/sleep
no Z revival

**Comment by mugling** [comment]
> Game stops working.

Specifically what happens?

**Comment by ZenZen2** [comment]
Spacesbar didnt get me out of the debug window. Quicksave didnt work. Had to close the task. Didnt try anything else.
It was a fresh game, i have no savegame of it, no idea what kind of gun he used.

**Comment by mugling** [comment]
Can inconsistently reproduce. Ignoring `debugmsg` results in NPC entering endless loop

**Comment by Chezzo** [comment]
I experienced this with an NPC with a Kel Tech 2000 and a Glock 22. Their heads explode and free gun and you can go about your day, but still a pretty huge issue.

**Comment by jzambo** [comment]
I am aware of one similar sounding bug that crashes the game. Fired weapon is destroyed by explosion but is still referenced. Similar thing could be happening here - the weapon is no longer there and so reloading it fails.

**Comment by Night-Pryanik** [comment]
Last mention of this bug is more than 1.5 years ago. Also nor the original issue neither comments don't really describe reliable reproduction steps. There is a big chance that bug was fixed some time ago. Closing until reconfirmed.
