### ISSUE TITLE
Must be a bug: inventory space shows in ml since 5466

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#18273]
new bug in 5467
inventory space shows in ml, its a big number. Dont think thats intended?
because ml is for liquids and the big nummer is confusing.
wans't the case in 5466

**Comment by mugling** [comment]
Intentional change; `volume` is now represented in `ml`

**Comment by Coolthulhu** [comment]
Well the part where we have thousands in volume isn't exactly the right way to do it.
Should show in liters where possible.

**Comment by mugling** [comment]
`%.2fL` perhaps?

**Comment by ZenZen2** [comment]
Maybe the possibility to switch between these in the options, just like kilometers and miles.
