### ISSUE TITLE
Blazemod Vortex components broken

### ISSUE THREAD

**Issue by kilozombie** [CleverRaven/Cataclysm-DDA#18270]
At least in the most recent version I have (17944, haven't seen any PRs for blazemod since), there are two problems with the Vortex parts:
1. Neither one is capable of actually functioning. They seem to require a 'vortex core', and one is produced  in their recipes, but it doesn't seem possible to put that in your vehicle in any meaningful way. No 'vortex core holder' or anything.
2. The vortex generator produces only as much power as an upgraded solar panel. For such a high cost it is basically useless. Pretty sure it hasn't been updated for some new vehicles change or something. 1,000 battery wouldn't be unwarranted, considering its status as an endgame part.

**Comment by mugling** [comment]
It would be worth mentioning @Blaze-whatdoyoumeanitsalreadytaken for these issues

**Comment by Xnfinity** [comment]
Problem1 is just because the core is a solid item not a liquid so it cant be refilled...

Was blocking solid items for cars just to stop batteries?

**Comment by kilozombie** [comment]
I think you're right, @Xnfinity 

Also couldn't get minireactors to work. They run on solid items (plutonium cells) as well. So the problem is affecting mainline as well as blazemod.

**Comment by kilozombie** [comment]
Well, I've done my best. I tried amateur code-diving and making changes and debugging etc. and I can't fucking fix these broken-ass vortex generators and engines. Even if they're identical in everything but name to minireactors they don't work. And I got minireactors working, somehow.

pls help @Blaze-whatdoyoumeanitsalreadytaken

**Comment by Xnfinity** [comment]
My question is what version of blazemod was you using, the one that been part of the download for years' or the updated one? @kilozombie

**Comment by kilozombie** [comment]
@Xnfinity The one which comes with the download-- I use the launcher. It's been updated more recently than I thought. Not sure if there's an even more fixed one?

**Comment by mugling** [comment]
Fix requires attention of mod author who has been notified (this closure message should also bump the issue for them)
