### ISSUE TITLE
Kinetic Bullet Puller unable to be activated

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#18276]
http://i.imgur.com/05yuKkp.png

Didn't get any error logs while doing this.

**Comment by Rivet-the-Zombie** [comment]
You don't have to use it any more. Just have it on you/nearby and use the normal disassembly command on the ammunition.

**Comment by Zilenan91** [comment]
Oh wow okay. If you don't have to have the Puller near you to dissassemble ammunition it should probably be removed from spawnlists. If you still need it it should have its description updated to convey this to the player.

**Comment by DangerNoodle** [comment]
That seems to be incorrect. You have to have the bullet puller, it is used as a tool in disassembling the ammunition, if I recall.
