### ISSUE TITLE
Regression: single pill storage

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18289]
Storing a handful of pills in patchy pockets or on the bottom of the backpack is once again possible.

This (optimally) leads to cluttered inventories, less meaningful choices and just plain lack of realism when you store a handful of different pills together and pick the correct one in total darkness.

There needs to be some sort of a lower cap on item volume. Old 250 ml was pretty good.
Alternatively, mandatory containers for small items such as pills and powders. Those could be stored on the ground in any form, but in inventory only in containers, like liquids.

Labeling as bug because it's a significant regression.

**Comment by Treah** [comment]
I would think that having different volume / filled pill containers leads to more clutter not less. Also if they require containers then they should always spawn with one then. Having to go search for a container to pick up a handful of pills off the ground is unrealistic not more.

**Comment by BevapDin** [comment]
> This (optimally) leads to [...] and just plain lack of realism when you store a handful of different pills together and pick the correct one in total darkness.

vs.

> There needs to be some sort of a lower cap on item volume.

Does nobody see this as contradiction? What about candy where each piece is packed separately: http://www.google.com/search?q=candy+individually+packed&tbm=isch

I suggest: making pills a powder and enforcing contains for powder, similar to liquids.

**Comment by Snaaty** [comment]
I don't really see why this is such a bad thing. Keeping pills in boxes complicates things unneccessarily and now I can just 'assume' that I'm keeping them in a somehow sensible order. 
Personally I am fine with the inventory being as abstract as that.

**Comment by mugling** [comment]
> I suggest: making pills a powder and enforcing contains for powder, similar to liquids.

We need to make more use of containers. Currently they are (mostly) just inventory spam

**Comment by wapcaplet** [comment]
Nested containers, and in particular the pocket field "min_item_volume" for setting the smallest item that can be stored in any given pocket, would appear to solve these problems quite well:

- "Storing a handful of pills in patchy pockets or on the bottom of the backpack is once again possible...This (optimally) leads to cluttered inventories"
- "There needs to be some sort of a lower cap on item volume."
- "We need to make more use of containers. Currently they are (mostly) just inventory spam"

Closing issue.
