### ISSUE TITLE
Volume needs appropriate display units

### ISSUE THREAD

**Issue by pierredavidbelanger** [CleverRaven/Cataclysm-DDA#18288]
On OSX (`10.11.6`), with a custom build (compiled from a424d42 + [ChezzoSounds](https://github.com/Chezzo/Cataclysm-DDA/tree/ChezzoSounds)).

The `make` command I use:
```sh
make app -j4 NATIVE=osx OSX_MIN=10.11 TILES=1 SOUND=1 LOCALIZE=0 RELEASE=1 CLANG=1 MACPORTS=1 USE_HOME_DIR=1
```

I understand this is a work in progress, so if those are known bugs, please ignore this issue.

In this (`+` re-layer screen) capture, I see 2 strange things:

1) in the left column, I see `0`s and `m`s , are those supposed to be there, what they mean ?
2) also, storage does not seems to be consistent (see also the `i` inventory and `/` advanced inventory screen captures bellow)

![cataclysm__dark_days_ahead_-_0_c-18216-gb7e955e](https://cloud.githubusercontent.com/assets/1076726/18439387/1491ef5e-78d3-11e6-8756-b67e93426a12.png)

![cataclysm__dark_days_ahead_-_0_c-18216-gb7e955e](https://cloud.githubusercontent.com/assets/1076726/18439542/d582583e-78d3-11e6-82f9-2532fbfa5001.png)

![cataclysm__dark_days_ahead_-_0_c-18216-gb7e955e](https://cloud.githubusercontent.com/assets/1076726/18439655/3d7e4ce0-78d4-11e6-8b37-bd2ac58705d4.png)

EDIT (mugling):

Required fixes:
- [ ] Inventory
- [ ] Advanced inventory
- [ ] Sort armor
- [ ] Item info?

**Comment by Coolthulhu** [comment]
Duplicate? Of what?

**Comment by mugling** [comment]
#18273 and see also #18279

**Comment by pierredavidbelanger** [comment]
Closed because of [this one](https://github.com/CleverRaven/Cataclysm-DDA/pull/18275#issue-176247948) also, I guess.

But, what about the column on the left ?

I just started playing this game 2 weeks ago, I am new, but I am pretty sure the trailing `0 ml` was not there before, same for the bunch of  `0`s and `m`s.

**Comment by Coolthulhu** [comment]
The advanced inventory display bug doesn't seem to be reported anywhere else.

**Comment by pierredavidbelanger** [comment]
@Zireael07 oh, I understand, those are chars that overflows from the lines just before them ...

**Comment by pierredavidbelanger** [comment]
@Zireael07 so, I guess, the bug is a printing issue:  there is not enough room in the column to print the trailing ` ml` string after the volume

**Comment by pierredavidbelanger** [comment]
So...

Indeed @mugling is correct that, in the re-layer screen, the volume displayed in the left column is not the same as the center one, and this was reported before.

But, should I create 2 new issues for :

1. the ` ml` string printing overflow in the re-layer screen 
2. the advanced inventory volume inconsistency 

?

**Comment by mugling** [comment]
This issue is actually more descriptive so lets use this to track progress instead of #18273

**Comment by pierredavidbelanger** [comment]
Still on OSX, but now compiled from a791e3d .

I found this while (`I` comparing two items):

![cataclysm__dark_days_ahead_-_0_c-18331-gd88d88a](https://cloud.githubusercontent.com/assets/1076726/18497833/c5315ed0-79ff-11e6-8c2a-ee2345c856b7.png)

I know it's not a bug. I guess its more a call for an enhancement.. 

This is just to let you know that this one was rather confusing for a CDDA noob like me. It took me some time to figure why the storage does not match and, for example with the hydration pack, that the first volume is for the "dry" pocket and the one bellow was for the "liquid" bladder.

Before the refactor of display the volumes in ml, there was no confusion in this screen since the units were not the same.
