### ISSUE TITLE
Make Organic Non-Perishables Perishable?

### ISSUE THREAD

**Issue by DaliTimelord** [CleverRaven/Cataclysm-DDA#18303]
I'm going to assume IRL that you can't eat dehydrated rotting veggies or the fruit leather of moldy strawberries without suffering food poisoning. This isn't happening in-game though, as you can do the following without penalty. My only guess as to why you can bypass rotting through dehydrating or fruit-leathering is that this would make farming very inconvenient, as your crops can rot before you finish processing them.

This also applies to rotten milk. There generally isn't a (easy) way to get fresh milk in game, but is it safe to make dehydrated milk from rotting milk? 

Should there be a penalty for using rotten ingredients when making non-rotting goods, or is that too realistic? Should this be considered when balancing the game?

**Comment by Coolthulhu** [comment]
You mean that all perishables should be made perishable (like in title) or just that rotten perishables shouldn't un-rot on being crafted into unperishables?

The latter is a known bug.
The former would be a rather significant change that would get a load of criticism due to added tedium.

**Comment by DaliTimelord** [comment]
> just that rotten perishables shouldn't un-rot on being crafted into unperishables?
Yes that's what the change would cause. Again though that would be extremely annoying, but I feel weird being able to use rotten ingredients with impunity.

**Comment by Coolthulhu** [comment]
It could be fixed simply by requiring that all components of any recipe are un-rotten.
It doesn't make sense for some of the recipes to require fresh food, but for most it would be good enough to disallow rot.

**Comment by Leland** [comment]
Duplicate of #9879
