### ISSUE TITLE
Zombies will teleport Zlevels in order to attack a player

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#18301]
With Zlevels on, zombies will teleport up or down a level in order to attack a player.

If the player is on the ground level, zombies in the basement who can close to an adjacent square down there will teleport up in order to attack.

If the player is in a basement, they will teleport down to get you.

**Comment by Midaychi** [comment]
I haven't experienced the teleporting, but they certainly chase you around and make a mess down there smashing into things.

**Comment by Coolthulhu** [comment]
Does this still happen?

**Comment by pisskop** [comment]
havent recently seen them do it but Ive sworn Ive seen them actually climb up stairs on occassion?
