### ISSUE TITLE
Rivtech handloads not showing up in crafting submenus

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#18307]
Version: 0.C-18304-g6b4d4da

Rivtech handload rifle and shot cartridges (`bootleg 8x40mm JHP`, `handmade 20x66mm buckshot`, `handmade 20x66mm flechette`, `handmade 20x66mm slug`) only show up under the `ALL` submenu of the `AMMO` crafting menu.

Rivtech `reloaded 5x50mm flechette` cartridge only shows up under `ALL` and `OTHER`.

**Comment by DangerNoodle** [comment]
It took me a while to realize that the bootleg Rivtech recipes had been moved to the Craftable Gun Pack mod. Another subcategory problem, will fix shortly.
