### ISSUE TITLE
Handloaded cannon rounds not showing up in crafting submenus

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#18308]
Version: 0.C-18304-g6b4d4da

`reloaded 155mm slug`, `makeshift 120mm slug`, `reloaded 155mm shot`, `reloaded 120mm shot`, and `reloaded 30x113mm` only show up under the `ALL` submenu of the `AMMO` crafting category.

Not 100% sure if this is a bug or intended; my thinking is that they should at least maybe be slotted under `OTHER`.

**Comment by DangerNoodle** [comment]
Might include this in https://github.com/CleverRaven/Cataclysm-DDA/pull/18244 if desired.
