### ISSUE TITLE
Charcoal kiln balance (constructed verus tool)

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#18304]
Looking at the recipe for dismantling finished charcoal kilns, I noticed that you get 75 charcoal out of it.

In contrast, I filled a constructed stone charcoal kiln with the maximum of 12 logs, and the return was 172. If I had used a built kiln to make charcoal, those same logs would have yielded 900 charcoal.

Apparently construction skill has some effect on the amount of charcoal gained (mine was 4 at the time), but I don't know the exact returns per skill level. Either way, it seems like a massive reduction in yield given the disadvantage of having to rely on a stationary tool. The only real advantage you gain is it being less time-consuming to produce charcoal in bulk.

Or it would, if producing 75 at a time wasn't a lot less tedious than waiting 361 minutes for around twice that amount.

**Comment by DangerNoodle** [comment]
I took a closer look at the source and it seems that there is a loss stat that starts off at 90, and is reduced by 2 for each point in the construction skill. My best guess so far is that the number is taken as a percentage applied to the total amount of product obtained from a given volume of fuel.

This calculation is off by 10 when applied to my estimate of how much 12 logs should've yielded, assuming that the pre-loss value is 75 for every 20 of volume (and thus, equivalent to what 1 log in the portable kiln would yield). However, testing with one log returned 14 charcoal at 4 skill, and this is consistent with the math assuming rounding is used (13.5).

A base number or 50 or 60 might be overall less overkill.

**Comment by DangerNoodle** [comment]
Well, this is odd. I discovered that the new conversion to metric volume has completely and utterly fucked up my initial attempt to test a code-and-compile change to the code behind this.

**Comment by Coolthulhu** [comment]
Could be a better idea to obsolete mobile charcoal.
Does such a thing even exist? Even if it does, it should probably be 55 gal drum sized, not something that fits inside a backpack.

Charcoal is mostly useful for those who sit in one place for long. Or at least long enough to finish a batch.
Making charcoal on the go involves tedious mechanics - it should be emptied, refilled and lit in one crafting job, not THREE. Two first could easily be done with a duplicate recipe, the third could require a tiny addition to crafting system.

**Comment by DangerNoodle** [comment]
I would be in favor of increasing the yield for charcoal even if portable kilns are removed. The consumption tends to be high if you're smoking meat, and smithing can be a very heavy drain (though not as long-term as smoked food, since swords aren't edible).

**Comment by DangerNoodle** [comment]
On the other hand, attempting to find realistic figures for charcoal yield suggests that the 93.75% yield is way out of line. Game balance wise, reducing the amount demanded by recipes might be better.

**Comment by Rivet-the-Zombie** [comment]
>Could be a better idea to obsolete mobile charcoal.
Does such a thing even exist? Even if it does, it should probably be 55 gal drum sized, not something that fits inside a backpack.

The mobile charcoal kiln was originally just a kludge because I didn't know how to create a proper stationary kiln like we have now.

**Comment by DangerNoodle** [comment]
I can remove crafting recipes for it if desired, but I would also like feedback on the suggested changes in yield for stationary ones.

That said, portable charcoal kilns have their uses gameplay-wise.
