### ISSUE TITLE
Incorrect tab for fish baits in crafting menu

### ISSUE THREAD

**Issue by illi-kun** [CleverRaven/Cataclysm-DDA#18313]
Current category of fish baits is ```AMMO/OTHER```. Technically, baits _are_ ```ammo``` but it seems to be weird from player's point of view.

Any ideas about category for fish baits which fits better than current one?

**Comment by Mecares** [comment]
Perhaps move them to the traps category, that one is rather empty anyway and they are "trap-ammo"

**Comment by Treah** [comment]
I would say TRAP or OTHER
