### ISSUE TITLE
Asking NPCs to teach martial arts causes segmentation faults

### ISSUE THREAD

**Issue by 3t3rn4lfl4m3** [CleverRaven/Cataclysm-DDA#1831]
Every time I ask an NPC to teach me a martial art they know, I get a segmentation fault. Asking them to teach skills works without problems.

I am playing "Version: 0.6-116-gd1d6525".

**Comment by mugling** [comment]
Much of the NPC code has been rewritten since this was reported nearly 3 years ago. @3t3rn4lfl4m3 please re-open if you can reproduce in any recent version of `master`
