### ISSUE TITLE
Different types of static NPCs

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#18317]
Hey Y'all, so I'm not entirely sure how the future development of NPCs is supposed to go (are static NPCs supposed to go away at some point? If so, this whole issue becomes moot). I really like NPCs and what has happened to them in the last two years. I also think it is okay to have two different kinds of NPCs: the static ones that (ideally) provide lore and immersion and the dynamic ones that occasionally show up to make you adapt to the circumstances. I also have been more and more playing non-standard starting scenarios, mostly because the early game of the standard shelter start feels a little repetitive, that's why the different start locs and scenarios where added in the first place, I guess. Now here's an idea (sorry if it's been proposed before) that I feel would add substantially to lore/immersion/strategic choice of starting scenario: 
1. Create **different types of static NPCs for different starting scenarios**. The basic idea to have a companion you start out with is great. This should be modified accordingly, so that in Scenarios where it doesn't fit at all, you start without an NPC next to you. 
2. These NPCs should have many differences including, but not limited to:
   - Attributes  
   - Inventory
   - Skills
   - Dialogue (I find this important for flavour and immersion)
   - Missions (this might be added later)
   - Needs/Intentions (The fellow convict in the convict scenario should probably behave differently than a scared student in the school scenario.)

I for one really like the starting NPCs as a way to kickstart your game. Unfortunately the base shelter NPC works for the Shelter start scenario dialogue-wise but even there the strength of the NPC varies a lot based on their inventory and/or skills. Therefore adding specific NPCs would add a lot of flavour and replayability to the game imho. The standard NPC could act as fall back until all scenarios have appropriate starting NPCs or a lack thereof. 

Examples could be:
- Scared student for the school start with low stats but perhaps useful books and a higher willingness to join you hoping to get protected by you. Might get specific missions to look for the parents.
- Fellow Convict in the convict start, (these types could vary), but perhaps generally combat-capable but unlikely to be intimidated. Naturally he shouldn't carry anything really useful with him. 
- Your fellow police officer, for the police start, starts with a gun and the abilities to use it, is likely to join you. 
- The hospital start could allow for a doctor who didn't get away in time and decides to help you out of pity considering your predicament. 
- The missed start allows for a bunch of different types of NPCs like friends, family, colleagues, etc. 
  (these are just ideas to get the creative juiced flowing, really but the possibilities seem endless)

Now for the doability, I haven't had alook at the relevant code yet, but the good parts seem to be hardcoded. IIRC there already are different types of NPCs of the dynamic variant. 
Even if it was hardcoded, I suppose it should be possible for less code-y people like me to copy-and-paste some of the existing static NPCs (there are already several different types for the refugee center so it should be doable, I hope?)

(Sorry for not posting an actual "issue" here, this is more for collecting ideas that I can get back later to. If you have ideas regarding the doability please feel free to enlighten me. )

**Comment by ZenZen2** [comment]
I am sorry, i didnt see your post and started my own one. I made the suggestion to remove the starting NPC. Reason is, it feels wrong. Player needs the feel to be alone and lost with no hope.
And the first thing you see is a different friendly human face and not a zombie that wants to end your day.
The first moment for the player is to feel fear.

**Comment by Taberone** [comment]
Sounds good. Should add a lot to immersion, too.

**Comment by Snaaty** [comment]
You are aware, that you can simply disable static NPCs to get rid of the starting one, right? (That means you lose out on the reugee center too afaik).

But your Issue touches the same subject. 
As I said, certain starts should probably prohibit having a static NPCs next to you at start. To my mind come especially the challenge starts.

I am sorry, but I find your point not convincing. First off, there is no guarantee to make the NPCs friendly, imho in some cases having an initial mini-quest that makes the NPC friendly on completion would be appropriate or the usual "speech"-test you have to go through. 
Also there is literally _one_ person next to you, while there are hundreds of zombies. If the NPC isn't chuck norris that still means you're in a lot of trouble. Naturally their items need to be adjusted so they can't be looted early for a strong gun. The individual "advantage" of keeping them around should be different for each NPC, with varying degrees of actual "usefulness" depending on how it fits with the lore.

**Comment by Atavic** [comment]
Opposite view [here](https://github.com/CleverRaven/Cataclysm-DDA/issues/18319).

**Comment by Leland** [comment]
Stalled discussion for 8 months. Closing.
