### ISSUE TITLE
Remove the starting NPC from static NPCs

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#18319]
It doest feel right to meet a friendly NPC just right at the beginning. The player should need to search for a camp if he want to meet them, or just get lucky with a random NPC.
The starting NPC also makes some starting scenarios easier because he fights off zombies.

**Comment by mugling** [comment]
A hostile starting NPC is unreasonably difficult and a friendly one makes it a cakewalk

**Comment by pisskop** [comment]
we dont need any.  Or rather scenario specific ones would be suitable,

as it stands the one in the game rn has a guaranteed lighter, is a distraction for hostiles, and can have a good weapon/armor.  You can start a fire under them and take their goodies for free.

**Comment by Zilenan91** [comment]
I wouldn't say friendly NPCs make starts a cakewalk. I had a start a few days ago as a SWAT officer where a Remington 600-armed NPC who spawned in the police station with me got absolutely demolished by zombies breaking into the police building after me. I almost died myself there was so many.

**Comment by Leland** [comment]
Stalled discussion for 8 months. Closing.
