### ISSUE TITLE
New aiming interface

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#18320]
See also #15986

I want to rework the aiming UI. Any suggestions and requested features?

I'm thinking of three modes, snapshot (no aiming), careful (until 50% chance of `accuracy_goodhit`) and maximum (no further improvement possible). The options would be to spend one turn aiming, change mode or take the shot using the last selected mode.

Display would be the required moves and chance of achieving `accuracy_goodhit`.

I'd quite like to latch the aiming view so that you could fire at the same target sequentially (this solves the archery problem). Again suggestions as to how this could work as a UI?

**Comment by Zilenan91** [comment]
The UI is fine in terms of guns imo. It's also arguably fine for Archery too, since if you redraw your bow you aren't going to be aiming at the same target as you were before, requiring you to aim once again.

**Comment by mugling** [comment]
Goal is to update the interface, not the game mechanics.

**Comment by Zilenan91** [comment]
I feel as if the interface is pretty good already then. The thing I wrote about Archery was more justification as to why you have to re-aim after every shot as it is right now.

**Comment by mugling** [comment]
> why you have to re-aim after every shot as it is right now

* Actually you don't. You only return to `MIN_RECOIL` upon movement
* Current aiming display is misleading (values are calculated incorrectly)
* See also #15986

**Comment by Zilenan91** [comment]
With how long reloading takes and how fast zombies move you're rarely able to sit still while aiming a bow at even a singular target.

**Comment by mugling** [comment]
This issue is about how the interface should work not about changing the game mechanics

**Comment by Beanzy** [comment]
Could you outline what would specifically be different from the current UI? I take it this is related to the changes you implemented in aiming mechanics, right?

Like, how does snapshot, careful and maximum differ from the current implementation of aim, careful aim, and precise aim?

I know it might seem silly, but even just drawing an actual picture of the new UI you envision would really help here.

**Comment by mugling** [comment]
> I know it might seem silly, but even just drawing an actual picture of the new UI you envision would really help here.

The problem is I'm not sure what it should actually look like (although see #15986 for some related discussion)

> Like, how does snapshot, careful and maximum differ from the current implementation of aim, careful aim, and precise aim?

The proposed new definitions are as above. The old definitions were 33% aimed, 66% aimed, 100% aimed - this obviously was problematic as 66% aimed for a near shot is adequate but a disaster for a long distance one.

**Comment by Coolthulhu** [comment]
> careful (until 50% chance of accuracy_goodhit)

That's very weapon-dependent. Aiming to 50% of max aim sounds more useful.

**Comment by mugling** [comment]
> That's very weapon-dependent.

That's kind of the idea. Obviously a 'careful' shot at 3 tiles ought require less time than one at 20?

**Comment by Beanzy** [comment]
Would the change from bars to percentages be optional (as BlindGuyNW suggested) or would this be a permanent switch? I do think the bars are a good implementation, as they can provide immediate visualization of your chances to hit (assuming you can see).

For a text representation of it, maybe something like this:


```
Confidence/Chance to hit: 76% (Head: 15%, Torso: 45%, Graze: 16%)
Steadiness              : 85%
```

We replace the previous "+ = Hit" with a torso percentage, and use "to hit" to represent any chance of hitting the target.

As for the aiming modes being based on `accuracy_goodhit` that seems like a positive change. Though, how would careful aim act if you couldn't get a 50% of getting a good hit?

**Comment by mugling** [comment]
> Though, how would careful aim act if you couldn't get a 50% of getting a good hit?

It would be equivalent to selecting maximum aim

**Comment by mugling** [comment]
Relatedly I'd also prefer a system where NPC's could be assigned the same modes as the player

**Comment by Beanzy** [comment]
Hmm, here's an idiotic suggestion.

Do the aiming modes have to be hardcoded? Maybe a custom aiming mode (with user defined percentage) could be added. This would bring the aiming modes up to 4 which would match the current implementation.

**Comment by BorkBorkGoesTheCode** [comment]
The only thing I can think of is allowing the player to attack by double-clicking the LMB.

**Comment by hitbutton** [comment]
> Though, how would careful aim act if you couldn't get a 50% of getting a good hit?
> It would be equivalent to selecting maximum aim

This seems like a regression. Why not act like the current firing interface, and only offer options for higher levels of aiming where they are pertinent?

**Comment by mugling** [comment]
@hitbutton the detail is important - how exactly would that algorithm work?

**Comment by hitbutton** [comment]
I just meant that if maximum aim would not be sufficient to reach 50% chance of accuracy_goodhit, then you should not offer the option for achieving a 50% chance. That would be confusing/misleading.

Instead of basing it off a static value of accuracy_goodhit, you could instead offer options scaling from the maximum chance you could achieve with the weapon. The number of options could also vary based on the precision of the weapon. That would be functionally identical to how the current "aimed, carefully aimed, precisely aimed" UI.

Is there anything that's changed in the aiming code that would make implementing that a complex problem? I haven't kept up with the changes you've been making.

**Comment by hitbutton** [comment]
Something else that I think is important for the aiming interface, particularly if it may be defaulting to aim modes with predicted aim levels, is to always show the probability of firing immediately without aiming.

**Comment by Oskar636** [comment]
This is implemented now, right? If it is then I think #15986 can be closed.

**Comment by kevingranade** [comment]
My only question is what data inputs are required to determine, '50% chance
of accuracy_goodhit'?  This must not include information the player does
not know such as monster stats.

> The options would be to spend one turn aiming, change mode or take the
shot using the last selected mode.

I'd suggest 'change mode and use it' if at all possible. With the short
list of modes it may be reasonable to show all their costs so the player
doesn't have to toggle between them to decide which one to use.

**Comment by mugling** [comment]
> I'd suggest 'change mode and use it' if at all possible

Why not incremental aiming (during which zombies continue to advance)?

**Comment by kevingranade** [comment]
Incremental aiming should stay, I just mean, "change mode" and "use current
mode" should be "change and use mode" and "use mode".  I could be wrong but
it seems more streamlined at no cost

**Comment by kevingranade** [comment]
Stalled due to the contributor that was pushing for it being absent.
