### ISSUE TITLE
Coal can be used in charcoal forge items, but not built forges

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#18329]
Related to issue: https://github.com/CleverRaven/Cataclysm-DDA/issues/18304

Constructed charcoal forges do not allow the use of coal as a fuel, whereas the item version can freely make use of mined coal. Unlike the points mentioned in the prior issue, I do not know how to resolve this in a pull request.

The same disparity applies to charcoal smokers, but I suspect that smoking meat with straight coal would be a bad idea in reality.

**Comment by DangerNoodle** [comment]
I would like to propose a workaround.

Due to there being the ability to add overlapping ammo types, it might be viable to add a generic fuel item that both charcoal and coke can be made into. This fuel, charcoal, and coal could also be given a "coke" ammunition type, while charcoal would count only as the charcoal ammunition type. Food uses for charcoal could then be set to only allow charcoal, while other uses (kilns, forges) would be set to use this fuel ammunition type.

Then, by setting this processed fuel to the default ammunition type for coke, this would allow for constructed forges to make use of coal. It would be hacky to an extent, especially if the recipe was simplified rather than referencing real-world production of coke, but would be easier than trying to get `reload_furniture` to accept more than just default ammunition type.

If @Coolthulhu has any thoughts on this?

**Comment by Coolthulhu** [comment]
Pretty sure the problem here is hardcoded furniture ammo types. It should be fixed by allowing furniture to use more ammo types.
Adding a new item type just to handle furniture would not be the proper way to fix it.

**Comment by DangerNoodle** [comment]
As far as I can determine, the issue seems to be that the code is set to look up the default ammo for the ammo type it is set to use, actually.

Though as I said, a secondary use for this idea would be excluding coal from charcoal cooking. Essentially it is a hack that benefits the player in one way, but restricts the player in another.
