### ISSUE TITLE
JSON linting

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#18330]
The project currently has nearly 400k lines of JSON and growing. Much is badly formatted and contains outdated or incorrectly specified fields. We are currently pursuing three approaches to this problem:

* Reducing duplication via inheritance (`copy-from`)
* Enforcing constraints and preventing assignment of defaulted values (`assign strict`)
* Formatting and detection of incorrect fields via linting (`format.pl`)

The first two require careful review - inheritance needs to be well designed and constraints often involve changes to the surrounding code (eg. #18321). The third (linting) requires a different approach.

If we aimed to lint 50% of existing JSON via 1000 line PR's this would take over a year for a 48 hour review cycle. Manual review would also be very laborious and less accurate than an automated solution.

For this reason I designed the linter to be backed by unit tests that verify the output (see `tools/format/examples`) so that any change to the ruleset can be tested for regression. There is extensive documentation describing how to extend the ruleset and indeed other authors have since done so.

We followed this approach in #17456 when importing an updated version of `blazemod`. The linter identified a large number of issues and reformatted 13k lines without any problems. Helpfully that mod is now whitelisted against future regressions.

The only options for achieving reasonable linting coverage area are to increase PR line count or decrease review time. Given that manual review of linting is of very limited value it's best to optimise for lower line count as this reduces the risk of merge conflicts.

I take #18298 as majority consensus that automated linting without manual review is acceptable:

> If one other dev agrees (or at least "agrees if someone else agrees"), then I also agree. Then we'll have the active dev majority.

> So long as everything is properly tested, I see no problem with this PR.

But it would be best to confirm that assumption here and define what changes are reasonable. Important factors to consider include PR sizing, frequency and scope.

**Comment by Rivet-the-Zombie** [comment]
You've already got my opinion on this quoted, but I'll reiterate for the sake of clarity: I'm all for automated JSON linting as long as we follow sufficient testing practices to ensure that the process is handling everything properly without messing up any of the stuff that it's reformatting.

**Comment by Coolthulhu** [comment]
> If we aimed to lint 50% of existing JSON via 1000 line PR's this would take over a year for a 48 hour review cycle. Manual review would also be very laborious and less accurate than an automated solution.

Makes sense.

Though do split the fully automated changes from automated changes+adjustments. Preferably not just in commits, but entire PRs.

Since jsons are more orderly (less varied) than code, it may even be possible to just PR a giant, unreviewable mess of a lint as one and then go from there, though that would break most PRs that contain any json changes.

Kevin objected to such changes, but that was about code and also a different situation. Nowadays we don't have as many json additions, but have a ton of json changes. Reviewing a PR that is all about dropping an extra field from a billion entries is a waste of time, especially when it comes from a dev.

**Comment by Rivet-the-Zombie** [comment]
Apparently we can't apply the reaction emoticons to locked discussions, so I'll just quote something that I'd **really** like to underscore:

>Though do split the fully automated changes from automated changes+adjustments. Preferably not just in commits, but entire PRs.

A PR with automated formatting fixes is great, but one that changes numbers around at the same time is *double plus ungood*.

**Comment by mugling** [comment]
I'd obviously prefer en-masse in two stages - first to drop bad fields and then to actually do the linting. That way all value changes go in a tiny PR subject to manual review and then the automated go in a monster.

**Comment by illi-kun** [comment]
@mugling that seems to be a good approach.

**Comment by mugling** [comment]
To continue splitting out any semantic changes for manual review and then pushing automated changes separately
