### ISSUE TITLE
Potential Problems with Coolthulu's Regional Weather settings?

### ISSUE THREAD

**Issue by SeniorScore** [CleverRaven/Cataclysm-DDA#18344]
http://imgur.com/a/8lNkq

trying to start using the Next Summer Scenario, weather freaks out apparently

just checked, same thing happened on just a regular evacuee scenario

currently using 5499

**Comment by mugling** [comment]
What time of day is it?

**Comment by SeniorScore** [comment]
Supposed to be 8am, but the moon is out for some reason

**Comment by Coolthulhu** [comment]
Is the world old or new?

**Comment by Reclusive-reptile** [comment]
I've had the same problem with old and newly generated worlds.

**Comment by Coolthulhu** [comment]
What mods are you using? Does the bug happen in worlds with no mods?

**Comment by mugling** [comment]
This doesn't somehow relate to that can't always select a different weather setting bug?

**Comment by Coolthulhu** [comment]
Some mods may override the regional settings. If they do not specify weather field, the game might default to some "null generator".

An initialized weather generator will never return null weather.

**Comment by molkemon** [comment]
I had this bug just now after updating from a ~2 weeks old build. I loaded a save and I had NULL/BUG Weather. I killed the process, loaded another save, it worked fine there, and when I loaded the first save again, it was just fine aswell (I did not save with NULL Weather, just killed the Task in Taskmanager). Windows Tiles.

**Comment by DocHoncho** [comment]
Same thing happened to me, I fixed it by using debug menu to clear weather.  Mods installed: [
    "Medieval_Stuff",
    "More_Survival_Tools",
    "nw_pack",
    "boats",
    "deoxymod",
    "blazemod"
]

**Comment by molkemon** [comment]
I also have boats and more survival tools enabled, none of the other stuff though.

**Comment by adrianrieck** [comment]
Same happens to me when I gen a world with no mods enabled.
The only things I changed was to enable surround start,  static and dynamic npc the rest was default world settings.

**Comment by ZenZen2** [comment]
same here.

version: 5507
mods:
medieval
PK Reimagining
npc dont eat/sleep
filthy clothes
no Z revival

**Comment by ZenZen2** [comment]
the visibility indoors seem to work normal

**Comment by Murumuru** [comment]
This happens to me on 5507 with completely default settings.

**Comment by AsuraAce** [comment]
same problem.

version: 18364
- no mods
- default settings
- chesthole soundpack
- cdda game launcher

happened on game load or while crafting not 100% sure.

**Comment by Coolthulhu** [comment]
> version: 18364

What system? Console/tiles? When was it uploaded?
Is this the most recent version for this system?

Those versions are hard to track back because they don't have uniform numbering.

**Comment by Zireael07** [comment]
Build 5542 is version 18517. @AsuraAce, since you're using the game launcher, give us the letters and numbers that come last in the version field of the launcher, before it says (tiles) or (console)

**Comment by AsuraAce** [comment]
- Win10 64bit
- build 5507
- uploaded 3 days ago
- version 0.c-18364-g5a5f641
- tiles

**Comment by illi-kun** [comment]
@AsuraAce your build isn't the latest one, so you should to migrate to the fresh one.
