### ISSUE TITLE
Debug-monster while halluzinating

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#18343]
A Debug-monster shows up as halluzination.
Is this a bug?
version 5459

**Comment by pisskop** [comment]
I dont think its a bug, but if it is unintentional its a longstanding bug.

Hallucinations also emit fields #17790

**Comment by ZenZen2** [comment]
its description says somthing like "for testing only", a player shouldnt see that.

**Comment by mugling** [comment]
> Is this a bug?

Yes, a meta-bug
