### ISSUE TITLE
Poison and badpoison wear off too quickly to be very meaningful

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#18345]
Outside of the most immediate combat with the creature that likely inflicted you with the effect, venom and badvenom's effects are meaningless.  They last less than a minute.

**Comment by Coolthulhu** [comment]
Affects all sources of poison at the moment. Even poisonous food.
Poison would need to last hours to matter.
For example, a whiff of smoker's smoke tends to be more dangerous than standing in poison gas until it disperses.

**Comment by pisskop** [comment]
It would be possible to remove the venom tag and add an attack effect for creatures.

But even gas is weak.  Gas itself is a strong asphyxiant ingame.  the issue is it wont hang around.

**Comment by WizardOfOoo** [comment]
Needs to do damage for a while, kill you if not cured, paralyse a limb, necrotic wounds, or something equally horrible.  http://www.nytimes.com/health/guides/poison/snake-bite-poison/overview.html
A lot of the things on this list we already have ways to simulate.

Perhaps a high enough medical skill and or a medkit could reduce or negate the effects.

As a player, I never worry about poison.  There is a drive to make the game harder, this is a good place to do that.
