### ISSUE TITLE
Display conductivity only for items it is important for

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#18340]
So, I don't think the player needs to know whether that tin can of ravioli (fresh) does conduct electricity or not. Is conductivity relevant for defending against electric attacks? If not, I suggest displaying the Information only for weapons (and tools?) as it only clutters the already full interface for other items with information that is irrelevant.

**Comment by Coolthulhu** [comment]
It is supposed to be displayed for potential weapons. Cans might have positive damage stats, which would make them count as potential weapons.

**Comment by Treah** [comment]
I think this brings up another question as to why some items have cut and bash at all? A good example is the sock that has Bash:2 and Cut:2. Im not sure a sock will contribute at all to you hitting something with your hands in any measurable way. I have always seen stats like this on some clothing as nothing more than interface clutter.

**Comment by Snaaty** [comment]
Sorry, my bad, I didn't look closely. Aluminium cans with food in them also display the flag. 

Hm, adding a specific tag for the display of the conductivity is probably over the top. I guess this is a minor issue all in all, so if there's no elegant solution, we might as well close this one.

**Comment by WizardOfOoo** [comment]
I think it's safe to close this one.
