### ISSUE TITLE
Vehicle Construction used double starting parts

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#18372]
Wish for 2 light wooden frames
drop 1 on the ground, keep the other in inventory
start vehicle construction using the light wooden frame from your inventory
notice the light wooden frame on the ground has disappeared

**Comment by Midaychi** [comment]
Yeah. Vehicle construction requires two frames, for some reason. If you only have one it constructs the vehicle, but errors out with a missing ingredient debug message, consumes the frame, and produces no end vehicle after the naming screen.

**Comment by Xpyder** [comment]
Does deconstructing give back 2 frames?

**Comment by mugling** [comment]
We keep getting variants of this bug. It would be a good candidate for a unit test once the test framework is running again

**Comment by Coolthulhu** [comment]
From what I heard on forums, it seems to be associated with blazemod (vehicle additions).
Has anyone been able to replicate it without blazemod? If not, we should probably just remove it from there and possibly add a debugmsg when someone tries to manually overwrite the vehicle start recipe.

**Comment by Xpyder** [comment]
I do use vehicle additions pack so this is a definite possibility.

**Comment by tyrope** [comment]
Can confirm this issue is still valid as of build 5770, I get the same error as shown in #18701

**Comment by MisterFox** [comment]
This issue is does not occur if blazemod is not loaded. It may have something to do with the strange override entry (http://puu.sh/s0A2h/f54499bdf1.png), but I don't know how to fix it.

**Comment by ussdefiant60** [comment]
for the record, deleting the first entry in blazemod_override.json seems to correct this without any ill effect. the blazemod frames stay avaliable as a valid option for vehicle construction, but i'm not sure if there were any other reasons for that override being there.

**Comment by Xpyder** [comment]
Do we know if Blazemod is still being supported?

**Comment by hmstanley** [comment]
I asked the same question a few days ago :). And the answer was yes!

**Comment by illi-kun** [comment]
Was this fixed by #19471?

**Comment by BorkBorkGoesTheCode** [comment]
@illi-kun it seems to work. Have constructed a vehicle with 1 light wooden frame without other frames nearby.

**Comment by illi-kun** [comment]
@BorkBorkGoesTheCode thank you for information.
