### ISSUE TITLE
Strange repairing behavior

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#18375]
I had this with an awl pike.

What happened was I used the awl pike to smash, and got it down to purple durability. After this, I repaired it and it got to what was supposedly an improved state, stating 46 piercing damage, despite the awl pike in an improved state being at 54 piercing damage. This didn't seem right to me, and I tried smashing something else and it went right back to its previous purple durability after getting damaged once.

On exitting the game and reloading the awl pike stayed at a reinforced state but gained +8 damage and on damaging it it went to a green high durability state.

To my knowledge this sort of thing happens for more weapons than just the awl pike, reinforcing things in general is a bit buggy and inconsistent. I've had similar behavior on fire axes before.

**Comment by Coolthulhu** [comment]
Rounding errors in new damage system.
We'll probably need to hack it together with roundings.

**Comment by mugling** [comment]
Closed as duplicate
