### ISSUE TITLE
Eternal season breaks winter/summer start tags

### ISSUE THREAD

**Issue by Voskhod-1** [CleverRaven/Cataclysm-DDA#18379]
Enabling eternal season causes the starting season to always be Spring, regardless of if Sheltered, The Next Summer, or Ambush scenarios are selected.

**Comment by DangerNoodle** [comment]
Does it additionally set the eternal season to a different one if an eternal season other than spring is chosen?

If it does, this would be functional but merely intuitive behavior. If this combination enforces eternal spring regardless of what the starting season is in the world setting, then it would indeed be non-functional regardless of whether worldgen setting or scenario setting is expected to have priority.
