### ISSUE TITLE
Light wooden frames should attach using ropes not nails

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#18373]
In particular you shouldn't need nails to assemble a travois, potentially troublesome if you're using a wilderness start

**Comment by DangerNoodle** [comment]
Rope might additionally be more tedious to acquire, though more certain in a wilderness environment. Though any structure that is likely to trivialize rope production (via easy access to cloth) will likely also be a source of nails. So short ropes might be more accessible overall.

**Comment by Xpyder** [comment]
Yes but you still have wooden frames for nail worthy projects.

Sorry about the duplicate I thought I searched but I guess I forgot to on the second ticket.

**Comment by Xpyder** [comment]
Whoops, it's not a duplicate, that's a pull request.
