### ISSUE TITLE
Working Cars too scarce in town, country, at roadend locations

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#18370]
Working cars feel almost nonexistent in the latest versions.

Inside cities, the majority of running cars will be demolished quickly.  The rest tend to be scuttled come night time as a single zombie will smash a smashable object and then the rest hone in and do the same.

Outside of cities, the frequency of cars has been reduced.  Which is fine.  the frequency of _working_ cars, however, is waaay down.

In parking lots outside of mines, sewage treatment plants, sarcophgoi, etc, will yield no or mostly destroyed vehicles.

Under the Hood (UTH) _should_ _not_ be a requirement to get a vehicle running, and/or mechanics needs recipes to allow players to access the skilltree without finding a copy.

**Comment by Zilenan91** [comment]
Yeah this is a big problem. What you need to do right now is either start with points in mechanics or scavenge for hours to get UTH. After that you need to basically grind to get your mechanics high enough to repair everything.

A solution I proposed in the Construction overhaul would be to combine both mechanics and construction so players can solve immediate needs in the early game by boarding up windows and doors and then use the skills they learned later on a car.

**Comment by ZenZen2** [comment]
I am strong against combining construction and mech. In my opinion the game will become to easy with that.
Its already easy with cars because you can find a lot of fuel.

**Comment by jaked122** [comment]
@pisskop I'm not sure about the cars already running being an issue, it really feels about right to me. It's right in line with what I understand the behavior of zombies are supposed to be. 

Whenever I run into a car that's running, I turn it off first thing. Have you tried yelling at the zombies? That tends to distract them long enough to turn off the car.

That is a very risky strategy, and I feel that it might be fairly balanced considering the power that cars provide.

@ZenZen2 I agree, the mechanics and construction skills ought to be different. It's really not comparable, building a car versus building a house.

Of course, they could synergize fairly nicely, as the craftsmanship is generally helpful for both.

Construction tasks, like building a water pump should definitely give mechanical skill.

**Comment by latogato** [comment]
I disagree, getting a working car is big help, it's negates most dangers in the game. I think car should be earned as it was in the old releases where all cars was broken down or without fuel. I was awe when working cars was introduced and i found one in a garage, but really it's just takes away a big part of the challenge from the first few days. I think getting a working car should be an adventure, not an expected free object lying on the road. Rare working cars are fine.

**Comment by jaked122** [comment]
Working cars are very rare, I think appropriately so, as I suspect that
most people would try to flee in their cars or steal them, so I imagine
that only a few would be left in garages in remote or otherwise exceptional
locations.

I don't think they should be completely missing, as I don't think they were
ever completely absent since I've started playing.

**Comment by pisskop** [comment]
5 days guys.

Not 3 months.  5 days.

That there are cars in auto crashes sure.  That they ran out of gas, sure.  That they ran out of battery charge, yes.  Not that they are missing parts like they came out of a chop shop

**Comment by Zilenan91** [comment]
I feel like most of the map in general suffers from that problem. If there was things like blood stains, smashed doors, smashed windows and smashed furniture in houses or shell casings and zombie corpses in the streets to represent things actually being alive before the Apocalypse hit the world it would just feel more complete. 

It's the same with cars, it's surprising to me how 99% of them are broken and have ZERO battery and gas left in them. I don't think any of them should be as broken as they are five days after everybody dies.

**Comment by jaked122** [comment]
The empty gas and dead electricity seems like a result of damage to the
car, most gas tanks are damaged, and damaged gas tanks tend to leak.

**Comment by Rivet-the-Zombie** [comment]
>If there was things like blood stains, smashed doors, smashed windows and smashed furniture in houses or shell casings and zombie corpses in the streets to represent things actually being alive before the Apocalypse hit the world it would just feel more complete.

We had a PR like this in the works at one point, but it never got finished enough to be merged. That being said, I'd **LOVE** to see something like this.

**Comment by jaked122** [comment]
I'd honestly prefer if it was possible to turn it off. I like my unusually
intact houses with comfy couches and marijuana basements.

I don't know that I understand enough to do this reliably.

I'll check to see if there's any place in the code where this might fit in
without requiring a major json rewrite.

**Comment by pisskop** [comment]
I spent the night in the game dodging around the city, only to find exactly 2 vehicles with the requisite parts.

12 hours of night.  2 vheicles.

1 was an empty electric scooter.  Why do we have empty electric vehicles in the game again?
  Because by the time they are charged enough to be useful the player will have had a vehicle up and running if they had any intention on using one.  And by then theyll useful only for stripping.

1 was a fire truck that wouldnt start for no known reason.  It had wheels, a clean battery, good controls, gas, and a seat.  But it refused to start.

Reducing the amount of vehicles in the game and restricting entry into the mechanical skillset are not how you nerf deathmobiles.  You do that by not making steel the consistency of silly putty.

**Comment by jaked122** [comment]
I mean, there are *mechanical faults* that develop in cars now. At least if
you're using the development version.

That explains why that fire truck didn't work. Maybe five days is too short
a time for *any *of this to happen, but five days is about as long as you
would be able to eat most of the food left in random people's houses.

Besides, I think that the OPness of death mobiles is only not a problem in
real life because very few people are skilled enough to make them, and
those that are are well employed doing things.
Like the random dude with a facial tumor who changed my oil who claimed to
have king kong's finger from some movie.

You should try out the tank mod, those are fun because you can just run
through stuff.
