### ISSUE TITLE
0.C-18364 - "Webbed Fingers" encumbrance penalty activates when wearing watches

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#18389]
The flat +50 hand encumbrance from wearing gloves with the Webbed Fingers mutation triggers when wearing items on the hands using the Strapped/Belted layers, such as wristwatches and briefcases, which shouldn't realistically be affected.

Using windows 10 x64 tiled.

**Comment by illi-kun** [comment]
That's technical limitation of current system.

I'm going to close this soon if no one have any realistic ideas how to fix this easily.

**Comment by Zireael07** [comment]
Can't you exclude strapped/belted layers from the relevant code? (ie. make it check layer before applying penalty?)

**Comment by illi-kun** [comment]
@Zireael07 I like the way you're thinking. I think it's (should be) possible to define affected layers of mutation (i.e. representation of mutation "webbed fingers" as a pseudo-clothing with all layers affected except the belted one).

**Comment by Rivet-the-Zombie** [comment]
>Can't you exclude strapped/belted layers from the relevant code? (ie. make it check layer before applying penalty?)

Or we could make the watches work similar to belts - those go on the torso, but on a special `waist` layer. We could give hands or arms a special `wrist` layer that would ignore stuff like webbed hands and such.
