### ISSUE TITLE
Vehicle components should not be active when installed

### ISSUE THREAD

**Issue by HeadWar** [CleverRaven/Cataclysm-DDA#18384]
I just installed three headlights into my Humvee, only to be greeted by the message "The Humvee's battery dies!" as I finished the last one.

It seems most (all?) vehicle components are in active state when installed, which is rather annoying, since for many of them it isn't even possible to tell, at least not in daylight.

**Comment by mugling** [comment]
Installed parts obtain the state of any other parts of the same type. There isn't any other way of implementing a toggle interface and avoiding split state (some on, some off). In your case you presumably had the headlights on already when you started installing more.

If you can reproduce this when installing headlights with them turned off then please reopen as a bug.

**Comment by HeadWar** [comment]
Umm. I have no idea how to reopen an issue, nor how to label it as a bug. No permissions?

At any rate, the headlights of the car were turned off at the vehicle control menu, but I removed all lights, and then reinstalled them, so maybe there was no actual state of other similar parts to inherit from?

Also, this is a savegame from a version where you could control lights individually, even though it has been upgraded to the latest version, might that have an impact, something lingering?

**Comment by Griffinhart** [comment]
Confirming, parts (or at least, headlights; I assume this is true of other parts with on/off toggles e.g. mini fridges, engines, other lights) will default to "on" state when installed, even if other, similar parts are off. 

Version 0.C-18304-g6b4d4da

1. New world, new character. 
2. Wish for a `toolbox` and a `reinforced head light`.
3. Spawn an `armored car`. 
4. Make sure it has non-zero battery, that it had at least one working headlight installed, and that its headlight is off. 
5. Set time of day to any time at night (I used 0100).
6. Install the headlight in your inventory to the vehicle. 
7. Observe that the vehicle now has one headlight on (the just-installed one) and one (or more) that are off (the pre-existing headlights).

**Comment by Night-Pryanik** [comment]
That's not a bug, but a default behavior.
