### ISSUE TITLE
Jenkins is broken

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#18388]
Buildbot is currently struggling:

`Caused by: java.io.IOException: No space left on device`

Please be aware when submitting PR's that automatic checks including `astyle`, `json-check` (game binary) and `json-lint-check` (linter) are out of action as well as the experimental builds.

In particular modifications to files covered by `astyle_whitelist` or `json_whitelist` need checking locally to avoid breakage once this issue is resolved.

Was problematic before/not related to #18349

**Comment by Zireael07** [comment]
@narc0tiq? How much space does the buildbot have?

**Comment by DanmakuDan** [comment]
```<Narc0tiq> [08:41:39] (turned out /var/log/mail.log and syslog were about 5 GB each -- on a 28 GB disk; sadly, I just dumped them, so no idea what actually ate all the disk space)```

Maybe there's some recursion with one of the validating scripts?

**Comment by ZenZen2** [comment]
May i ask where i can get the latest version from? because i see you all still work on the Game even if the bot is not working.

**Comment by mugling** [comment]
> Maybe there's some recursion with one of the validating scripts?

Not an unreasonable suggestion but I checked already that the linter changes were pushed **after** the breakage had already occurred.

**Comment by mugling** [comment]
> May i ask where i can get the latest version from? because i see you all still work on the Game even if the bot is not working.

Most developers compile locally

**Comment by narc0tiq** [comment]
> @narc0tiq? How much space does the buildbot have?

Normally, it looks like this:
```
[narc@odin ~]% df -h
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/root      ext3       28G   16G   12G  59% /
devtmpfs       devtmpfs  998M  4.0K  998M   1% /dev
/dev/sdc       ext3       20G  6.1G   14G  32% /var/lib/jenkins
```

but I misconfigured the mail server and it ate those 12 GB with syslog entries. Fixed now.
