### ISSUE TITLE
Water cannon doesn't use vehicle water tanks any more

### ISSUE THREAD

**Issue by HeadWar** [CleverRaven/Cataclysm-DDA#18385]
I have a car with a water cannon installed, for some reason it has recently (when upgrading version, not sure between what versions it happened) stopped working. It seems that you now have to load the water cannon up manually, like other turrets, rather than it just pulling water from the vehicle tanks.

**Comment by DangerNoodle** [comment]
The same issue occurs with flamethrowers.

**Comment by Oskar636** [comment]
It seems to work with vehicle tanks properly now.
