### ISSUE TITLE
floodlight and Floodlight

### ISSUE THREAD

**Issue by HeadWar** [CleverRaven/Cataclysm-DDA#18387]
I just noticed there are two different install options for floodlights on vehicles, one "floodlight", that can only be installed "on top" of a regular headlight, and using the same amount of battery (-187), and one "Floodlight" that can be installed pretty much anywhere, and using -2000 battery.

**Comment by Karlieb** [comment]
Are you using a mod that adds a floodlight? Or someone accidentally uploaded a personal mod?

**Comment by HeadWar** [comment]
Not that I know of, the only mods I use are ones that come with the build. Perhaps the more dakka or military vehicles mods?

**Comment by Karlieb** [comment]
I found the extra part in Blazemod. Some interesting lines from it:

"id": "xfloodlight",
"location": "on_battery_mount",
 "flags": [ "NEEDS_BATTERY_MOUNT", "SOLAR_PANEL" ]

**Comment by Zireael07** [comment]
Looks like it, yes

**Comment by DangerNoodle** [comment]
Odd. That suggests they are solar-powered floodlights? I am unsure what they are intended to be.

**Comment by HeadWar** [comment]
Like those little lights you can put in the garden, perhaps?

**Comment by Midaychi** [comment]
It's a legacy part in blazemod. In order to have it mount on the top of the vehicle, they had to make it a modded solar panel in the backend.
