### ISSUE TITLE
 Jewelry doesn't grant morale buffs to stylish trait survivors.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#18398]
As decribed here: http://smf.cataclysmdda.com/index.php?topic=12850.0;topicseen
Even if they have the fancy tag it still does no moral boost. Also pocket watches are proposed to be wearable.

**Comment by tsulh** [comment]
I noticed that I get no buff from jewelry, but thought that it might give less than 1, and I just didn't put on enough to see the difference. Thanks for posting!

**Comment by codemime** [comment]
I suppose this could be fixed via adding:
```
"covers" : [ "WHATEVER" ],
"coverage" : zero or almost zero
```
to jewelry items. Also, an appropriate check on load wouldn't hurt (to catch all such cases and prevent regressions in the future). Or should the small items remain limb-independent?

**Comment by Noctifer-de-Mortem** [comment]
Adding coverage to all jewelry would fix this now but it might be an issue in the future with other clothing articles. A load check is a more "permanent" solution.
