### ISSUE TITLE
Aiming at yourself and pressing pause crashes the game

### ISSUE THREAD

**Issue by Rizoel95** [CleverRaven/Cataclysm-DDA#18407]
This only seems to crash the game if there is a creature around to aim at first. 

---

**To Reproduce:**

1) Spawn a gun, as well as a mag for it and some ammo (otherwise the game will just tell you that you need to reload and not let you aim it). Load the gun.

2) Spawn a zombie or literally any creature

3) Aim the weapon. Aiming should automatically lock onto the creature. Take aiming cursor off the creature and place it over your character.

4) Press '.' or '5' or whatever your pause button is.

5) Crash

**Comment by codemime** [comment]
[Here's the invokation](https://github.com/CleverRaven/Cataclysm-DDA/commit/0f40c970c6981e66f15b55926123045019adfeb1#diff-c5873ed460ae46963dac594829494e52R1325) that crashes. The `target` variable (passed by reference) gets assigned to `-1` at some point and causes range check error `t[-1]` on the next pass. I can quickfix it (return `target` as the result of the function and test), but I suppose @mugling knows better how this code is supposed to work.

**Comment by mugling** [comment]
Good work @codemime. I got halfway through refactoring that code - it's slow going as it's not very easy to read. A quick fix is more than acceptable as it really wants ripping out in it's entirety when I redo the aiming UI.
