### ISSUE TITLE
Bandit hideout bug

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#18408]
http://i.imgur.com/FtBrJhs.png
Bandits can spawn in walls sometimes
Build 0.C-18064

Also on another note it's very odd that bandit hideouts aren't marked on the map when things like unfinished log cabins and campsites are

**Comment by Zilenan91** [comment]
Oh what the heck. I found something else very very strange with this, every time I quit and reload the game the bandits randomly teleport around in different positions. I believe they may also respawn after death? I'll find out and see what happens to them.

**Comment by Midaychi** [comment]
This is a problem with the base game, not the mod specifically. It has to do with handling static npcs in cases where a map template is placed but also rotated. The static npc spawning orientation is sometimes different..

**Comment by Oskar636** [comment]
Did #18576 fix this?

**Comment by Coolthulhu** [comment]
Closing for now. If it happens again, it will be a different bug due to changes in NPC placement.
