### ISSUE TITLE
Mining stone with a pickaxe crashes your game

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#18418]
0.C-18064
Tested twice near an Anthill Food Storage
You whack away for a while then get a pain message, on seeing what was up with the pain message your game will crash.

I am running PK's Reimagining and those change ants so that might have something to do with it

**Comment by Zilenan91** [comment]
I would need to find an Anthill Food Storage in a vanilla world and that would take a long time to do. If anyone else can try and do a little debugging if they already have that situation in their game that'd be awesome.

**Comment by Rizoel95** [comment]
Just tested it in a completely new vanilla world in an evac shelter, and it did the thing. I don't think it's anything to do with anthills or any mods, just typing 'y' when it asks you to stop the action when you get hurt at the very end by the falling rocks and stuff seems to do it. Getting hurt by a monster while doing it doesn't seem to crash it.

**To Reproduce:**

1) Spawn Pickaxe

2) Start mining a wall. A rock or concrete one doesn't matter, just make sure there's a ceiling above your character when you do this.

3) At the very end, the player will get damaged by some falling debris, and the game will give you a message saying 'Ouch, something hurts! Stop mining? (y/n)'

4) Press 'y'es.

5) Crash

**Comment by Coolthulhu** [comment]
It's probably caused by pain canceling the activity just before the "official" cancel.
Just removing the pain should fix it. It's no big deal anyway, pain of this magnitude wears off quickly enough not to matter.

**Comment by codemime** [comment]
@Coolthulhu Good suggestion. I had published the PR (slightly different, slightly hacky approach) and then saw your comment here.

**Comment by DangerNoodle** [comment]
Also related is digging downstairs not generating a matching upstair. I need to get a newer version and test that before reporting.
