### ISSUE TITLE
Skeletal dogs don't leave any corpses

### ISSUE THREAD

**Issue by HeadWar** [CleverRaven/Cataclysm-DDA#18412]
I've been hitting them quite hard, but there should be something left anyway, right?

**Comment by Zilenan91** [comment]
There should be corpses yes

**Comment by Rivet-the-Zombie** [comment]
That depends on how hard you're actually hitting them. Do enough damage in a single blow and sometimes all that's left is bits of meat or bone.

**Comment by HeadWar** [comment]
There's not a single trace left.

**Comment by Treah** [comment]
This needs confirmation as the last time I killed one it left a corpse.

**Comment by Zilenan91** [comment]
Happened to me. Hitting skeletal dogs hard enough deletes the body and any remains/giblets that might fly off.

**Comment by Treah** [comment]
Hmmm that might be intended behavior since there is no other parts other then bone on that type of creature. So there wouldn't be any meat giblets to be left behind.

**Comment by Reclusive-reptile** [comment]
Skeletal zombies used to GiB into bones when overkilled, iirc
