### ISSUE TITLE
hallucinated yuggs cause mutations

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#18414]
Hallucinated yuggs cause mutation if you let them attack them

**Comment by pisskop** [comment]
related:  hallucintions emit fields

#17790

**Comment by Oskar636** [comment]
I was spawning a lot of debug hallucinations but the bug doesn't seem to reproduce. Neither did #17790. Would like for somebody else to confirm this too.

**Comment by pisskop** [comment]
The normal yuggs actually failed to mutate my character

But the emits from say, a giant slug that emits acid in a mod:
[img]http://i.imgur.com/XFH0Ipl.png?1[/img]

**Comment by Oskar636** [comment]
So you're using a mod? Which one?

**Comment by pisskop** [comment]
Heres an example of a coregame smoker zombie emitting smoke despite being a hallucination

<a href="http://imgur.com/mRSectz"><img src="http://i.imgur.com/mRSectz.png?1" title="source: imgur.com" /></a>

**Comment by Oskar636** [comment]
So far it is the only monster I have seen do that as a hallucination.

**Comment by pisskop** [comment]
Okay, perhaps it would help to know which monsters will emit fields before saying that you havent witnessed any doing so?

**Comment by Oskar636** [comment]
I tried doing that but don't know what to look for, currently I'm going monster by monster to see if they "affect reality".

**Comment by pisskop** [comment]
Searching monster.json for the term "emit_fields" will yield results

**Comment by Oskar636** [comment]
Anyway this issue is about slugs now I guess? Please edit it and tell me what mod did you use. If you did use a mod this issue would also require a "mod" label.

**Comment by Coolthulhu** [comment]
If it replicates with unmodded critters, it is not a mod issue.

**Comment by Oskar636** [comment]
That is what #17790 is about, but first off he said the yuggs didn't do anything and second off the hallucinated slugs don't generate acid in core.
