### ISSUE TITLE
Can we please have uniform display of volume across the UI?

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#18411]
Right now, we have display in litres in inventory and on the layering screen, millilitre in item info screen and the old volume units in advanced inventory, which is confusing even to me as a veteran players. 

Ideally, all unit displays should be uniform, and also customizable via the options (like let us set the display style ourselfs... I would prefer a 00,00 Litre display (also for weight, 00,00 kg instead of only 1 decimal), but someone else might like decilitre more, or even the millilitre display.

**Comment by Zireael07** [comment]
IMHO everything should work like the inventory (litres).

**Comment by DangerNoodle** [comment]
We just need to extend @mugling change to liters to be applied in all references to ingame volume. I can parse liters far more easily than milliliters, and I am saddened that the pull request only fixed a fraction of this change.

**Comment by mugling** [comment]
We need to be cautious here. An item occupying 10ml volume could cause a lot of trouble if the maximum precision displayed is 100ml.

**Comment by DangerNoodle** [comment]
An extra digit of decimal would be acceptable, as in general the decimal point still vastly improves readability over it being displayed purely in mL.

On the other hand, we have the same issues regarding display of weight, and most players are likely fine with that. When picking up an item, you have the switch the red volume/weight numbers as the first obvious clue that capacity is being exceeded. The only instance where this is a problem is in inventory display.

We could have it add a `<` to the listed volume if the item occupies less volume than can be displayed, similar to how Dwarf Fortress displays items weighing less than a kilogram.

**Comment by Oskar636** [comment]
This is implemented and can be closed.
