### ISSUE TITLE
Unit tests are broken again

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#18425]
Still investigating cause. Can anyone else confirm?

**Comment by codemime** [comment]
For me they compile, but fail to run properly. Lots and lots of error messages:

```
Finalizing and verifying
src/generic_factory.h:356 [int_id<T> generic_factory<ter_t>::convert(const string_id<T> &, const int_id<T> &) const [T = ter_t]] invalid terrain id "t_null"
src/generic_factory.h:356 [int_id<T> generic_factory<ter_t>::convert(const string_id<T> &, const int_id<T> &) const [T = ter_t]] invalid terrain id "t_hole"
src/generic_factory.h:356 [int_id<T> generic_factory<ter_t>::convert(const string_id<T> &, const int_id<T> &) const [T = ter_t]] invalid terrain id "t_dirt"
src/generic_factory.h:356 [int_id<T> generic_factory<ter_t>::convert(const string_id<T> &, const int_id<T> &) const [T = ter_t]] invalid terrain id "t_sand"
src/generic_factory.h:356 [int_id<T> generic_factory<ter_t>::convert(const string_id<T> &, const int_id<T> &) const [T = ter_t]] invalid terrain id "t_dirtmound"
src/generic_factory.h:356 [int_id<T> generic_factory<ter_t>::convert(const string_id<T> &, const int_id<T> &) const [T = ter_t]] invalid terrain id "t_pit_shallow"
src/generic_factory.h:356 [int_id<T> generic_factory<ter_t>::convert(const string_id<T> &, const int_id<T> &) const [T = ter_t]] invalid terrain id "t_pit"
src/generic_factory.h:356 [int_id<T> generic_factory<ter_t>::convert(const string_id<T> &, const int_id<T> &) const [T = ter_t]] invalid terrain id "t_pit_corpsed"
src/generic_factory.h:356 [int_id<T> generic_factory<ter_t>::convert(const string_id<T> &, const int_id<T> &) const [T = ter_t]] invalid terrain id "t_pit_covered"

...and so on for other objects
```

followed by a segfault.

**Comment by mugling** [comment]
Yes, I get the same. I have no idea why though as until recently they were working recently.

@narc0tiq if I can get the unit tests in better shape how would you feel about a collaboration to enable them for the release builds only (not the PR branches for obvious reasons)?

**Comment by narc0tiq** [comment]
Sure thing, as long as they don't make the build longer than 60 minutes in duration (global counter for all sub-builds, I think).

**Comment by mugling** [comment]
Think I have the cause identified

**Comment by codemime** [comment]
What was that? `NULL_ID`s?

**Comment by mugling** [comment]
If you add a `debugmsg` to `item_factory::finalize()` counting loaded templates you get zero. If you run the unit tests on a mod, eg. `--mods=blazemod` you get 118. We aren't loading core data for some reason. I'm working on a patch now.

**Comment by mugling** [comment]
@codemime you interested in a collaboration on fixing up or deprecated all the failing unit tests (a divide an conquer approach)?

**Comment by codemime** [comment]
Sure thing. Unit tests are must have if we want to progress faster and don't re-fix already fixed issues. How shall we split them?

**Comment by mugling** [comment]
Try pulling my branch `unitchk` and verifying that fix works for you.

> How shall we split them?

Priority is to get as much coverage as possible working so that we can add them to Jenkins release builds. No point in having unit tests that nobody runs (most definitely the current situation).

We can initially divide them into three groups:

* A: Working (or with expected failures)
* B: Not working but salvageable
* C: Permanently broken

Anything we both agree is C we can deprecate. We can distribute B between ourselves (and hopefully others) dependent upon opinion/area of expertise. Finally we can tackle any failures for A.

**Comment by mugling** [comment]
Further discussion would probably be best continued in #18461

**Comment by codemime** [comment]
> Try pulling my branch unitchk and verifying that fix works for you.

Yep, it did the trick. Where do I push my commits? I can't push back to `unitchk` (permission is denied).

**Comment by mugling** [comment]
You could submit a PR (against that branch)
