### ISSUE TITLE
Molotov cocktails won't stay lit

### ISSUE THREAD

**Issue by HeadWar** [CleverRaven/Cataclysm-DDA#18434]
You light the Molotov cocktail.
Your lit Molotov goes out.

Every time, and immediately. It's nice and sunny.

**Comment by Zilenan91** [comment]
Intended

It's RnG on if your molotov goes out after lighting it. Just keep trying to light it and you'll eventually be successful. Lighting it in the rain has a higher chance of putting it out.

**Comment by HeadWar** [comment]
Ah, I had an amazingly bad strike of luck I guess, must have missed it fifteen times in a row before reporting. Now I get it lit about one in five, which seems a bit low maybe, but never mind.

**Comment by Coolthulhu** [comment]
Actually, that IS a bug: the molotov code states it should only start going out after 5th turn.
Also, rain doesn't increase the chance.

**Comment by Izicata** [comment]
The molotov iuse code finds the molotov's age by subtracting the molotov's "birthday" turn from the current turn. Maybe it's using the turn the molotov was crafted rather than the turn it was activated?
