### ISSUE TITLE
Performing long actions next to a fire is too dangerous

### ISSUE THREAD

**Issue by Soadreqm** [CleverRaven/Cataclysm-DDA#18438]
A fire that isn't contained in a brazier or similar can spread unpredictably. This becomes a problem if you are doing something like reading or crafting near the fire, which is often exactly what you want to use a fire for. The first warning you get that the fire has become a problem is being prompted to stop because you are taking damage, at which point the fire has often literally engulfed you.

It's reasonable for an uncontained fire to be able to spread out of control, at least in some situations, but not for a person to catch fire without noticing. I would suggest prompting whether to continue every time a fire either spreads to a new tile, or grows into a larger fire tile. This would lead to some spam when trying to read books next to something like a burning building, but I don't think that's a very common usage case.

**Comment by pisskop** [comment]
Stand 3 or more tiles away when you can. At night you shouldnt be doing anything longterm by firelight.

**Comment by Xpyder** [comment]
I agree it should prompt you to stop a task when a fire you can see spreads.  This is almost always a dangerous situation

@pisskop  If you take the insomniac trait you're going to spending a lot of time up at night, and reading and crafting by firelight are some of the only things you can do to pass the time early game.  Especially if you choose a start other than the emergency shelter and don't have access to the console.

**Comment by Treah** [comment]
This is just another reason for you to build a container for your fire. However something like this could be utilized to prevent players from continuing to read / craft things after a fire has gone out when using the batch system.

**Comment by Xpyder** [comment]
@Treah You're not considering the scenario where a fire the player didn't start lights from outside the player's view.

There are a few things that can cause this, from zombies blundering into lava, to lightning strikes (it's unreasonable to assume the player with 360 their building for every single lightning strike), to an NPC spawning with a fire weapon or flamethrower and the player character being deaf.

**Comment by zwparchman** [comment]
Honestly fire feels a bit off. My first character was killed by a fire. I'd started lighting them indoors with no protection and it was fine for months. Then it killed me. The player should be more aware of fire (that fire's coming right at me!) and it should spread more often inside of a building if you light it on the floor. I shouldn't have been lead to believe it was safe by my first few tests (where I expected it to spread)

**Comment by CoroNaut** [comment]
I remember I lit a fire in an ice lab to warm myself, I used the waiting button to wait 30 minutes next to it and I just watched as my character was getting engulfed in flames, the wait action didn't stop while I was on fire either.

**Comment by pisskop** [comment]
you can cancel 'wait action' by pressing the period key, or whatever you mapped 'pause' to.  i use the number 5.


you guys realize that by willfully performing a long actiom by enemies or fire you implicitly accept a level pf risk.

i will not accept [you see a fire, stop Fooing?]. its ludicris hoe much hand holding people seem to.want

**Comment by Soadreqm** [comment]
>>you guys realize that by willfully performing a long actiom by enemies or fire you implicitly accept a level pf risk.

Only fire, actually. Enemies are quite safe. You get prompted to stop when a visible enemy approaches, and if you ignore that, you get another one when the enemy damages you. I often butcher corpses in view of enemies.

Fire, on the other hand, has no such "approach" prompt, and the first damage prompt you get is a symptom of a much larger systematic issue, ie. the fact that you are on fucking fire.

You can avoid the problems by only making fires on braziers and the like, so it's not a huge issue, but uncontained fires are still massive deathtraps.

**Comment by Xpyder** [comment]
> Fire, on the other hand, has no such "approach" prompt

^ This.

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
