### ISSUE TITLE
(Not sure if bug) Naming consistency: "headlight" and "head light"

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#18433]
Version: 0.C-18304-g6b4d4da

There is an item named `car headlight` and another named `reinforced head light`. Both serve essentially the same purpose (vehicle headlight), but there's an inconsistency in their naming. Which is preferred, or is this intentional?

**Comment by mugling** [comment]
Inconsistency/bug. Would prefer `headlight`
