### ISSUE TITLE
MShock32Modded transparency broken between 5541 and 5563 (MShock24Modded is fine)

### ISSUE THREAD

**Issue by davemichels** [CleverRaven/Cataclysm-DDA#18445]
Transparency on the MShock32Modded tileset broke at some point between 5541 and 5563 on at least Win64: http://i.imgur.com/bxjDtVb.png

MShock24Modded is fine, and I've tried hardware and software rendering on a fresh install. Thanks for taking a look!

**Comment by BorkBorkGoesTheCode** [comment]
@davemichels is the problem fixed?
