### ISSUE TITLE
Add search capability to vehicle building

### ISSUE THREAD

**Issue by jaked122** [CleverRaven/Cataclysm-DDA#18447]
Currently, the vehicle building screen is somewhat tedious to use due to the lack of the ability to search for the part that you desire to install. 

For players with few vehicle parts this isn't nearly as much of an issue because it does group all of the available parts at the top.

Adding the ability to search for the part that the player wants to install would make it considerably more convenient for players who have a well stocked garage.

This would also go a long way towards making most of the game able to perform searches, which is very convenient.

**Comment by mightyagrippa** [comment]
Agreed. Building vehicles or installing parts becomes a cumbersome menu bore once I have a cargo area full of random salvage.

Having available parts at the top is helpful. But it doesn't address the problem of finding an unavailable part you want to construct the components for. If a new player sees a cargo space on a truck and wants to build one, they need to search the entire list to get the information that a cargo carrier is the required item.

**Comment by ZenZen2** [comment]
if you use arrow button left and right (can not check in game right now but it must be left and right arrow button) you can switch between cargo items, funktional items and other different stuff. That helps to find faster what you need.

**Comment by jaked122** [comment]
Yeah, but the search function would make it easier, and I usually find that
it's pretty clunky in practice.

**Comment by pisskop** [comment]
What you can build isnt so important is as what you cant build --and why

**Comment by jaked122** [comment]
No, I agree, it should work like the recipe screen ideally,where you can
search by components (and more importantly get an expanded description or
ingredient list).

**Comment by Zilenan91** [comment]
Yeah the actual vehicle addition menu seriously needs some help. 

A problem I come into in particular is why I can't build specific parts. So if you want to put down a trunk on a tile that has an aisle on it it should tell you why you can't place one rather than just omitting it from the menu entirely and leaving the player who might not know any better confused.

**Comment by jaked122** [comment]
Yeah, I'm going to have to go through the code base to see what can be done
without a silly amount of work.

**Comment by jaked122** [comment]
So those filter tabs appear to be a very stripped down, non-customizable version of what we want here.

I'm wondering if it might make sense to add a sixth filter tab and then try to build some sort of functionality that would allow searching by name and/or flags.

Describing the parts is more challenging, as the parts themselves don't have descriptions like items do, and I think that I'd need some input from other developers of this game on whether or not they think that the extra effort is worth it.

Building a complete filter is likely going to be the easy part, making it jive with the rest of the gui here is likely going to require a _bit_ more consideration.

I'm going to start work on it anyway.

**Comment by illi-kun** [comment]
Implemented in #18516.
