### ISSUE TITLE
Digging/mining downstairs fails to generate matching upstairs (even with z-levels on)

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#18452]
Tested in Windows graphical, builds 5464 and 5564 (the latter being latest built at the time of opening this issue).

Creating stairs using the "dig downstairs" or "mine downstairs" constructions do not create an upwards stairway on the floor below. Further tests revealed that enabling z-levels had no effect on this.

![stair failure](https://cloud.githubusercontent.com/assets/22048567/18691759/42ae1ba4-7f5b-11e6-915a-579697cfe500.png)

**Comment by Rivet-the-Zombie** [comment]
I wonder when this broke. I can verify that it used to work properly at one point in time.

**Comment by DangerNoodle** [comment]
I sadly have no idea when this was broken. One hundred builds ago is a lot, but not a very long period of time.

**Comment by mugling** [comment]
Was there not a stair alignment PR?

**Comment by DangerNoodle** [comment]
That might be a possible cause. I did not think to test whether stair alignment affected it. All tests were done with it disabled, the default setting.

When I encountered this in my current character, I debug-teleported downstairs and spawned a clairvoyance artifact. No upstairs were visible. I then created an upstair with the map editor, and I was able to travel up and down afterward.

**Comment by Coolthulhu** [comment]
Could be the part where I simplified construction code.
But I'm sure I tested it both in z-level mode and without, specifically looking for bugs in up/down stair construction.
I might have missed edge cases.

Does this reproduce reliably?

**Comment by DangerNoodle** [comment]
All tests I have done so far produced this, except when the map tile already has downstairs existing, such as digging downstairs too close to an evac shelter.

**Comment by DangerNoodle** [comment]
Any other possible causes?

**Comment by BorkBorkGoesTheCode** [comment]
This is still happening. The player teleports to the nearest basement when going downstairs.

**Comment by DangerNoodle** [comment]
That is peculiar. Why does it claim I added the the z-levels label? I rather obviously have no such authority.

![anomaly](https://cloud.githubusercontent.com/assets/22048567/21582896/2ebf13c2-d02e-11e6-9698-6dfffb547fa1.png)

**Comment by BorkBorkGoesTheCode** [comment]
This is the second time you've been listed as label setter,

**Comment by DangerNoodle** [comment]
That was an uploaded crop of a screenshot actually. Still, uncertain what that means.

**Comment by BorkBorkGoesTheCode** [comment]
@DangerNoodle I was aware.
