### ISSUE TITLE
Soda can stove kit only uses denatured alcohol as fuel

### ISSUE THREAD

**Issue by keyspace** [CleverRaven/Cataclysm-DDA#18460]
IMO using pure ethanol should also be possible. [Wikipedia](https://en.wikipedia.org/wiki/Denatured_alcohol):

> Denatured alcohol <...> is ethanol that has additives to make it poisonous, bad tasting, foul smelling or nauseating, to discourage recreational consumption. In some cases it is also dyed.

Would provide PR, but unsure on how to proceed with multiple-supply items. Could add ammo type (using `thread` as an example), but `ethanol` is also a comestible...

**Comment by mugling** [comment]
There is already the `conc_alcohol` ammo type

**Comment by keyspace** [comment]
These are different:

* Adding denatured alcohol to `conc_alcohol` is wrong, since the latter is drinkable, while the former is not.
* The ethanol content is different. Making concentrated alcohol out of vodka and whiskey does not turn it into a high-proof fuel that can burn.

**Comment by mugling** [comment]
Ammo types don't have anything to do with comestible stats

**Comment by keyspace** [comment]
Ah, sorry. I was confusing "concentrated alcohol" with "mixed strong alcohol".

**Comment by keyspace** [comment]
Closing. Updated to latest (had yesterday's master), this has been fixed already.

**Comment by keyspace** [comment]
Sorry for the noise. :(
