### ISSUE TITLE
Can't learn Medieval Swordmanship from Book

### ISSUE THREAD

**Issue by asciitaveller** [CleverRaven/Cataclysm-DDA#18462]
Steps to reproduce:
1. Start a world with the Medieval_Stuff mod.
2. Start the game.
2. Wish for "The Medieval Warrior".
3. Read it twice.
4. Medieval Swordsmanship doesn't show up in the styles list('_').
Non-mod martial art manuals work.

Tested on Linux,
commit ac41eee0bf156be9d066f652472ea286228baf8f

**Comment by DangerNoodle** [comment]
That is odd. They used to work.

**Comment by XaoG** [comment]
This has been like this for a while, and it effects Pankration too. Looks like there was a syntax change at some point.  

You can fix this by going to the martial_arts_manual file in the mod directory and moving `"use_action": "MA_MANUAL"` out from under `"book_data":`

**Comment by DangerNoodle** [comment]
That is an easier fix than I expected. At present I am out and about and likely would have trouble opening a quick pull request on current wifi.
