### ISSUE TITLE
"[le"

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#18473]
The example modes field in the GitHub wiki has it.

**Comment by mugling** [comment]
??

**Comment by BorkBorkGoesTheCode** [comment]
GitHub wiki/Flags/
`"id": "triple_launcher_simple",
"type": "GUN",
"modes": [le
    [ "DEFAULT", "single", 1, "NPC_AVOID" ],
    [ "MULTI", "multi", 3, [ "NPC_AVOID", "SIMULTANEOUS" ]
]`

**Comment by mugling** [comment]
I see (fixed)
