### ISSUE TITLE
Autosave upon exit can be an issue.

### ISSUE THREAD

**Issue by Beanzy** [CleverRaven/Cataclysm-DDA#18486]
Some background info: http://smf.cataclysmdda.com/index.php?topic=13298.0

Since #18212 was merged it is no longer possible to avoid a gamesave by exiting the game via the close window button.

While C:DDA is ostensibly a roguelike, there are certainly situations where not autosaving is desirable (e.g.: preserving a save where a glitch or bug killed your character).

Anyway, this issue is here so that some official implementation of quitting without saving can be discussed and added to the game.

**Comment by pisskop** [comment]
Its not about savescumming.


But I think an 'autosave upon exit' (or option to turn it off in debug) would be prudent.
  And, just to throw it out, were just one step away from somehow integrating that into a check for, say achievements.  Such as a postable tally of monsters-killed or "x-mines completed" or something.

**Comment by mugling** [comment]
We could add a call to `abort()` in the debug menu?

**Comment by Beanzy** [comment]
One problem with the autosave being a preset option is that you can't change options on the `"Watch the last moments of your life..." ` screen.

If a player encounters a bug and then proceeds to die, they can't preserve the save unless they had the foresight to change the autosave option beforehand.

Maybe a keybind to exit without save while on the death screen?

**Comment by mugling** [comment]
That sounds like overt savescumming...

**Comment by Coolthulhu** [comment]
Save-less quit is useful for testing and debugging.
It's better to allow "soft savescumming" than to suffer having to enforce it.

**Comment by mugling** [comment]
Agreed - the quickest and easiest solution I can think of is via the debug menu though

**Comment by Beanzy** [comment]
Frankly, it would allow it.

It's just, if a bug leads to the players death. Not being able to preserve the save in some way will make bugs that much harder to find and replicate.

Perhaps have the previous save moved to backup folder instead? This would make savescumming more difficult (or at least tedious) while preserving any saves that could help with debugging.

**Comment by pisskop** [comment]
It perhaps works best as a debug.  This way we can preserve the intent of the feature and still allow people to turn it off if they need to.
