### ISSUE TITLE
Pepperbox pistol uses flintlock ammunition and does 50 damage

### ISSUE THREAD

**Issue by flitvious** [CleverRaven/Cataclysm-DDA#18483]
Pepperbox pistol shoots paper cartridge, which is the ammunition for flintlock rifle and pistol. It does 50 damage and can store 6 ammo. This makes it a small 6-barrel shotgun.

The game has .36 paper cartridge (17 damage) and .44 paper cartridge (26 damage). Maybe pepperbox should use one of those?

**Comment by DangerNoodle** [comment]
We should possibly make it use a smaller cartridge, maybe. The alternative of nerfing paper cartridges would be a bad idea.

A second alternative would be to add negative damage to the pepperbox.

**Comment by BorkBorkGoesTheCode** [comment]
> A second alternative would be to add negative damage to the pepperbox.

This fixes the damage, but it still doesn't allow the player to measure the level of gunpowder used in a black powder firearm.

**Comment by DangerNoodle** [comment]
True. I was thinking it only makes sense for some degree of unburnt powder due to barrel length. For anything more than a minus two or so, it would be more sensible to use a different ammo type.

**Comment by mugling** [comment]
Hang on a second - there's a feature trying to escape in there, and one that could make blackpowder weapons relevant. Let the player select how much powder to use from a bottle dependent upon the situation (up to the limit of the weapons capacity)

**Comment by DangerNoodle** [comment]
That would complicate things, and realistically be slower to load than prepared cartridges.

**Comment by Treah** [comment]
> That would complicate things, and realistically be slower to load than prepared cartridges.

Well IRL a paper cartridge is actually not a cartridge like in the traditional sense. Its a small container that holds a pre-measured amount of powder and a bullet. Technically the user has to tear the container , pour the powder, and then jam the ball in the barrel. This all takes alot of time unless your very skilled at doing so. 

I kinda agree with mugling here for firearms like this ( musket ) where the user can determine how much powder they wanna use if they are not using pre created paper cartridges. It would make the user have to decide if they want more damage or if they want more reserved use of a limited supply of black powder. Use Case would be if your hunting small game you wanna use minimum amounts but you wanna use more when dealing with more dangerous foes.

**Comment by DangerNoodle** [comment]
I mean tearing a pre-assembled package of ball and powder compared to pouring from a powder horn, yes.

**Comment by mugling** [comment]
Loading black powder weapons is slow no matter how you do it. We should go with whatever game mechanic is the most fun

**Comment by BorkBorkGoesTheCode** [comment]
If the musket is overloaded with powder, it could explode. Could we add a "pressure_resist": "foo", JSON field to guns and a "pressure": "foo", field to ammunition? If the pressure level of the ammunition is higher than the pressure resistance, the gun will malfunction; if it's very high the gun explodes. It could alternatively be replaced with a check against durability.

**Comment by DangerNoodle** [comment]
That is a terrible idea. That just gives players the option to (possibly accidentally) do something no sane person would do, in game or in real life.

**Comment by BorkBorkGoesTheCode** [comment]
> That is a terrible idea. That just gives players the option to (possibly accidentally) do something no sane person would do, in game or in real life.

First, I was not suggesting that the flintlock should be converted into an improvised grenade, so if you thought I was suggesting that, disregard the following.

1. Pressure ratings would appear on the inventory menu, so players can make an informed choice.

2. When is bleach drinking, walking into fire, dropping armed grenades at ones feet, etc.. going to be disallowed? For consistency with your idea.

**Comment by DangerNoodle** [comment]
If I recall, bleach-drinking and walking into fire are both buffered against by a "do you want to do that" prompt to guard against deaths by accidental keypress.

**Comment by BorkBorkGoesTheCode** [comment]
>If I recall, bleach-drinking and walking into fire are both buffered against by a "do you want to do that" prompt to guard against deaths by accidental keypress.

The same could be done if the player loads a cartribge with a dangerous pressure level.

> Let the player select how much powder to use from a bottle dependent upon the situation (up to the limit of the weapons capacity)

Why not load the gun like a bolt-action, where each level of powder requires a press of the "r" key?
Or open a dialogue asking the player to enter the number of charges/bullets and reload them at the normal reload rate?

**Comment by DangerNoodle** [comment]
Possibly. That said, I am not sure yet how essential this is. The same change could be applied to pressure of handloads though, but that is even more complex.

**Comment by flitvious** [comment]
What I wanted to say was that pepperbox is a small weapon. Where flintlock pistol can store one big bullet, pepperbox must store six. In game, revolvers that use paper cartridge are Colt M1861 Navy (.36 paper cartridge) and Colt M1860 Army (.44 paper cartridge). Maybe change pepperbox to use one of those too. No need to nerf the regular paper cartridge, it's perfectly fine.

**Comment by Treah** [comment]
True flitvious but I think what mugling was getting at was that there is potential for the muzzle loaders to have a interesting mechanic. I think when loading you should be prompted with 3 or options for amounts. 

1. Full Load
2. Half Load
3. Small Load

**Comment by DangerNoodle** [comment]
Back on topic, it would be reasonable to assume that the pepperbox was might likely inspired by the Allen & Thurber pepperboxes, which were percussion-cap pistols. They did have differing calibers, .36 was about the largest it was made in, termed the Dragoon model. I have my doubts as to whether they would be compatible with the rounds used in the Colt Navy, though.

**Comment by flitvious** [comment]
If the caliber is the same, they should be compatible. Colt Navy rounds are just lead balls with pre-measured amount of powder. The rounds aren't loaded like modern ammo. You can see the process here:
https://www.youtube.com/watch?v=0G2zFzaDXxc

It is interesting that the recipe requires abstract lead, gold, solder, e.t.c.  and no tools for smelting that stuff into shape. I think in reality this would require a mold, a crucible and at least a nearby fire. Crucible is not really a requirement, though. You can melt tin or lead in a steel spoon, and then pour into the mold. 

As for different loads, this can be implemented in JSON by adding several recipes for paper cartridges. For a player, this will be the same process: reload -> prompt -> done. No versatility in changing ammo type with each shot, but I think it's not worth the effort of implementing as a separate game mechanic.

**Comment by DangerNoodle** [comment]
True, though if I recall there are also cap-and-ball cartridges that can be inserted whole rather than torn and poured like a flintlock cartridge. Those require the paper to be nitrated to burn properly along with the powder, however. I can not recall the reload times per round the revolvers have relative to the flintlocks, but a significantly shorter reload time would be indicative that the person adding them had the nitrated paper cartridges in mind.

As for the bullet molds, if I recall all of them require the hand press and die set as a passive tool, in addition to the option of using a few charges from it as an alternative to a toolset or fire. I assumed this meant that the press also includes bullet molds, and molding lead is why the hand press can be loaded with batteries (as handloading with premade bullets realistically would not require power).

**Comment by Treah** [comment]
I created a PR to update the pepperbox to use .38 paper. This reduces its damage output down to 17

**Comment by DangerNoodle** [comment]
Ah, excellent.
