### ISSUE TITLE
Issues with the new recoil

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18488]
Merged experimentally since the new recoil wasn't broken, but it still needs a lot of polish:
- [x] The recommended strength name is misleading - for example, the laser rifle doesn't benefit from strength at all
- [ ] The strength requirement displayed seems to be approximate instead of exact
- [ ] The strength cap is very low, strength above 10 doesn't do much for guns now
- [ ] No way to preview or predict effects of gunmods without applying them
- [ ] Bows and slings have no recoil, meaning you can aim once and then get all the headshots you need without aiming
- [ ] The formula itself is confusing without reading the code, needs to be exposed more. Implementation details or not, hiding information that can be calculated by a determined player is a bad thing

**Comment by Zilenan91** [comment]
I think most guns not needing a strength over 10 for optimum recoil control is fine because you don't need to be that strong to fire most guns in real life

**Comment by mugling** [comment]
> The strength cap is very low, strength above 10 doesn't do much for guns now

This one isn't true. Look at the requirements for `m249` or `m60` which are `STR >25`

**Comment by Coolthulhu** [comment]
> you don't need to be that strong to fire most guns in real life

It's not about "need", but "benefit at all". Having 100 strength doesn't help over having 10 strength when wielding AK-74, for example.

> This one isn't true. Look at the requirements for m249 or m60 which are STR >25

Those are heavy machine guns you are unlikely to be using anyway. Cost of using those is huge (no short burst, only full auto), they require specific terrain and in general are too unwieldy to matter.

**Comment by mugling** [comment]
Window frames work quite well and can be viable tactic against a large group. Given we have `MAX_SKILL 10` to balance around what is the intended value of `MAX_STAT`. How about 20?

**Comment by mightyagrippa** [comment]
> Bows and slings have no recoil, meaning you can aim once and then get all the headshots you need without aiming

Not saying this isn't a problem, but this was the case for old recoil too. Same thing with laser weapons (possibly intended) and the pneumatic weapons (less probably intended).

**Comment by mightyagrippa** [comment]
For reference, some values under current system and chargen defaults:
- 9-10 STR: normal fit human
- 15 STR: peak physical condition for a normal human. Maximum available to a starting character without sacrificing other stats (15/8/8/8), also the result of the Prime Strength mutation.
- 20 STR: absolute maximum available to an unmutated starting character (20/4/4/4).
- +8: highest static bonus available to STR without penalties or crossing threshold. Extremely Strong mutation + Large mutation + Strength CBM.
- +13: highest static bonus available to STR with penalties and threshold. Insanely Strong mutation + Huge mutation + Strength CBM.
- +20: active Hydraulic Muscles. Rip and tear!

**Comment by DangerNoodle** [comment]
> Those are heavy machine guns you are unlikely to be using anyway. Cost of using those is huge (no short burst, only full auto), they require specific terrain and in general are too unwieldy to matter.

Light machine gun and medium machine gun, respectively.

**Comment by schmithub** [comment]
It's not very realistic that strength lessens the affect of recoil.  Dealing with recoil is more a measure of skill.  Strength of the wielder is however a factor in the "wieldiness" of a heavier weapon, i.e., better strength would improve one's time to acquire target with a heavy firearm.  However, as you start looking at lighter firearms this starts become more of a moot factor. Also all things being equal (outside of the inherent individual characteristics of different firearms), the heavier a firearm is the more it tends to dampen the affects of recoil.

**Comment by Firestorm01X2** [comment]
**Additionally this issue exist:
https://github.com/CleverRaven/Cataclysm-DDA/issues/27248

It was closed by mistake (Kevin's attitude). Issue still exist. Watch out.**
