### ISSUE TITLE
error during compilation

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#18480]
After getting the today's commit 64e350a5520644547a391e8db9fc39b5d119fb82, I get the error during compilation:
src/mapgen.cpp:1644:30: error: could not convert ‘id’ from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘oter_id {aka int_id<oter_t>}’

**Comment by mugling** [comment]
Jenkins shows no issues. What platform and compiler?

**Comment by tsulh** [comment]
Linux, gcc

**Comment by Voker57** [comment]
can reproduce, latest d370fe2c0207bb4332ee9a111c does not compile

linux, gcc too

**Comment by mugling** [comment]
Ping @codemime

**Comment by codemime** [comment]
Soon.

**Comment by illi-kun** [comment]
Confirm this issue. I saw it right before I leave my work place so I had no chance to report it earlier.

**Comment by codemime** [comment]
Have found what causes the build error. It only happens when Lua support is disabled.

**Comment by tsulh** [comment]
The issue is fixed for me. Just compiled the latest version.
