### ISSUE TITLE
AKM is loud enough to deafen survivors

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#18487]
I don't think it should be loud enough to mute your hearing period.
Has sound of 77 when shot, I believe that's louder than shotguns?

Edit: Originally closed due to confusion over how much sound was added by a muzzle brake
Edit: Additional testing involved spawning an unmodded M4 and an unmodded MP5. The MP5 had a sound on shot of 42 when shot using reloaded 9x19 +P+ ammo, and the M4 had a sound of 70 using default .223 remington though it wasn't enough to deafen unlike the AKM without any sound-increasing mods added to it.

**Comment by Zilenan91** [comment]
Turns out the AKM has a default sound of 70 that only gets bumped up by 7 when a muzzle brake is added. This is too much.

**Comment by BorkBorkGoesTheCode** [comment]
While you will not become completely deaf, even something as small as a pistol can impair hearing on the first shot. It depends on the person and the surrounding environment.

**Comment by Voskhod-1** [comment]
I agree with bork. Unless hearing protection is used, even something as small as a single round of 9mm is enough to consistently cause ringing ears and impaired hearing.

**Comment by zapa1928** [comment]
ptw
