### ISSUE TITLE
Shooter earmuffs don't prevent from hearing loss

### ISSUE THREAD

**Issue by zapa1928** [CleverRaven/Cataclysm-DDA#18496]
0.c build 5579 
Spawn 
-M4A1 (i also checked also with Garand)
-STANAG magazine 
-ammo
-shooter's earmuffs

Wear and Turn on earmuffs, reload magazine and rifle
Shoot once for ringing ears, twice for hearing loss

**Comment by Rivet-the-Zombie** [comment]
>(btw why 50 rounds STANAG drum magazine does not fit M4A1 or for that matter other STANAG accepting rifles (except m249)

That's not right at all; the M4 should be able to use the drum as well.. The entire purpose of the STANAG agreement is to ensure that all those firearms can use all types of STANAG mags, no matter where they were manufactured.

**Comment by zapa1928** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/18497 
As @mugling said it was discussed before (though didn't said where).
I'll remove that remark from this issue as it's not the point.
As if it should be this or other way, discuss there (In separate issue).

**Comment by illi-kun** [comment]
Shooter's earmuffs has flag ```PARTIAL_DEAF```.

This flag affects level of safe volume (in function ```sounds::process_sound_markers( player *p )``` ):
```const int safe_volume = p->worn_with_flag("PARTIAL_DEAF") ? 100 : 9999;```

So I guess those listed guns have loudness > 100 and it's working as intended.

BTW, description of earmuffs clearly states this:
```
They will block sounds over a certain decibel amount, assuming it is charged with batteries.
```

**Comment by illi-kun** [comment]
@zapa1928 could you confirm I didn't miss something important?

**Comment by zapa1928** [comment]
But the description suggests the loud sounds (code you referenced sugests above 100) are reduced to some same level.

``const int volume = std::min(safe_volume, (int)(sound_event_pair.second.volume * volume_multiplier));``
``const int max_volume = std::max( volume, sound_event_pair.second.volume ); ``
and
``if( !p->is_immune_effect( effect_deaf ) && rng((max_volume - dist) / 2, (max_volume - dist)) >= 150 )``

suggest you lose hearing from 150

So its not working as intended or I don't understand the point of using this item.

As i understand 
M4A1 has loudness around 167 (i don't remember) so it is above hearing loss threshold.
Earmuffs should reduce it to 100 and it should be below hearing loss threshold.

If not correct me.

**Comment by zapa1928** [comment]
I was checking this once again and game interface states that M4 is produce around 500 (sic! what unit is this O_o).
With Earmuffs on it is as intended reduced to 100. So earmuffs work but they doesn't prevent from hearing loss.

**Comment by illi-kun** [comment]
@zapa1928 got the same value using debugmsg instances in the discussed function but I have no idea why it's 500.

**Comment by zapa1928** [comment]
I've shot today 10 rounds with Barret and shooter`s earmuffs (As i reason it's bigger gun and uses larger amunition). And i only got "Ringing ears" (And such expected way of working earmuffs expected). 
After waiting for effect to pass i shot with M4 and after second shot i got "Deaf".

I don't know if it is relevant, but might pointing to problem is somewhere else.

**Comment by zapa1928** [comment]
Shooting with AKM and earmuffs you lose hearing (Deaf) after 3 shots.

**Comment by illi-kun** [comment]
I've double checked it once again (since loudness of weapons was updated and discussed weapon - M4A1 with .223 Remington ammo - has loudness 164) and it seems that earmuffs aren't worked: deaf check use ```max_volume``` which is 164 anyway. Reduced ```volume``` (with value of 100) isn't used in the mentioned check and this makes earmuffs useless.
