### ISSUE TITLE
Survivor weapons error

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#18491]
0.C 18713

1:1 value outside range, Perfectly reproducible

**Comment by illi-kun** [comment]
Confirmed.
```
Error loading data: data/mods//survivorweaps/gun.json: line 1:1: value outside supported range

[
^

  {
    "id": "2_shot_special",

```

**Comment by mugling** [comment]
That is not a very helpful error message. I'm going to work on improving that so it complains what exactly is out of range.

**Comment by pisskop** [comment]
My guess is 
durability: -2

https://github.com/CleverRaven/Cataclysm-DDA/blob/be97190025acfc212e675e0a004560a99302cf4c/data/mods/survivorweaps/gun.json#L11
