### ISSUE TITLE
Crafting secondary skills are not respected

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#18504]
Once you have the primary skill you can learn and craft the recipe - secondaries are entirely ignored. Unknown if resolved by #18286

**Comment by Treah** [comment]
Ahh so something that uses say tailoring but requires survivor 2 it does not matter if you have the actual skill level in survivor?

**Comment by mugling** [comment]
Yes, you put that better

**Comment by mugling** [comment]
Fixed in `master` by in #18286
