### ISSUE TITLE
Targeting indicator is offset one tile above selected tile

### ISSUE THREAD

**Issue by Izicata** [CleverRaven/Cataclysm-DDA#18506]
In both the [visible item list](https://i.sli.mg/zXXeWG.png) and the [gun aiming](https://i.sli.mg/hR4Ldz.png) modes, the targeting indicator is offset one tile higher than the selected tile. In both images, the tile selected is directly to the east of the player, but the indicator is one tile north of the actually selected tile.

**Comment by Izicata** [comment]
Okay, that was weird. When I saved and quit to the main menu, the game crashed, and when I loaded the save again the issue fixed itself.

**Comment by ZombiesAreUs** [comment]
I don't think this is a new issue, it has happened to me a lot. I believe it's related to the way driving offsets the targeting indicator (it doesn't always recover its normal position successfully), and simply saving&exiting, then reloading the game will fix it. The offset can happen in any direction if I recall correctly.

**Comment by kevingranade** [comment]
I think this may have been adressed, I can't reproduce because the offset snaps back to neutral when exiting the vehicle.
