### ISSUE TITLE
Custom Character Tab order confusing

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#18502]
When using the multiple pool setup the expected conveyance is that anything left over from earlier tabs can be used in later tabs, and this is reinforced by the left to right directionallity of the menu (starts you on the left and you finish on the right)

However currently the Stats tab is located AFTER Traits, and Professions affects I don't even know which pool, which is confusing.

**Comment by Leland** [comment]
Discussion's been stalled on this one for over 8 months – closing. If there's still interest, feel free to ping me here to reopen or just create a new one.
