### ISSUE TITLE
Ants giving infected bites

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#18505]
It's not just happening with ants, I've gotten infected bites from woodland animals too.

This might be intended as any of the following, but I couldn't find any PRs listing it specifically so I'm trying to determine if this is a bug or not.

Possible valid reasons, but none verified yet:
 - Non-zombie disease such as rabies
 - Animals are infected with the plague (ants shouldn't be since their physiology seems to be incompatible, I haven't seen any zombie ants in the game)
 - In character inaccurate first aid check, misidentifying the wound.

If it isn't a bug it would be nice to have confirmation this is intended behavior.

**Comment by Izicata** [comment]
This is intended behaviour. There is no zombie disease; zombies happen because of the blob. Bites get infected because mouths, human and animal, are cesspools filled with regular old bacteria.

**Comment by Xpyder** [comment]
@Izicata

Ok, thanks.  Also not sure if that's spoilers or expected to be common knowledge (I didn't know).  If it's spoilers maybe edit it to say "because of certain creatures"

**Comment by Izicata** [comment]
If you're posting on the github, I generally expect that you know certain things. But sure, I'll edit the comment.

**Comment by Zilenan91** [comment]
Also ants are infected with the blob so that could be a rationalization for that

**Comment by Coolthulhu** [comment]
It's PK mod, which follows own realism rules.
Core ants and animals don't bite, they just "hit".

**Comment by kilozombie** [comment]
Yeah this stuff is pretty general knowledge. An infection ingame is just grimy shit getting in the wound-- admittedly very realistic for a zombie to give, probably less so for an ant or woodland animal, but still possible.

If you want to know more about the Blob and its relation to zombies, a lot of it is in lab notes, fliers, newspapers, forum snippets and even some from survivor's notes. You can also observe plenty yourself ingame just by playing around with mutagen.

**Comment by pisskop** [comment]
Well, OTOH, a bite from an ant is in theory cleaner than the bite of a mammal, which is in turn cleaner than one from a dead corpse human.  the reason being is that bacteria andor virii that infect humans tend to be found on humans, surprise.  They also have less chance of jumping species if the the species is less related evolutionarily.  Not that examples of critters having complex lifecycles that include organisms as different as mollusks and humans dont exist.

OToH, its a giant ant who is nomming on rotting flesh or animals.  I could nerf it down, but I was pretty happy with the damage and resource cost this ant bit produced.

**Comment by Xpyder** [comment]
@pisskop Yep, the extreme differences in physiology is why it seemed strange to me.  I considered the leftover bacteria idea, but I had thought most ants don't eat directly but spit up digestive enzymes to break it down first.

It turns out I was wrong.  It seems have special pockets in their mouth to much and strain some food in the field, but mostly they just drag it back to the anthill and let the larva externally break it down before they eat it.  And many actually use the larva as food sacks, feeding on the internal "hemolymph" juices of the larva themselves.  Weird.

**Comment by pisskop** [comment]
Ill tone the infections down.  I still want it, but Ill make them 75% less common.  As soon as I can pr
