### ISSUE TITLE
Value outside supported range error on Improved Survivor Weapons

### ISSUE THREAD

**Issue by Taberone** [CleverRaven/Cataclysm-DDA#18518]
<a href="http://imgur.com/9dQFqnn"><img src="http://i.imgur.com/9dQFqnn.png" title="source: imgur.com" /></a>

Starting a new game with the Improved Survivor Weapons mod gives this error about the Two Shot Special on Version 0.C-18751-g206baaa (tiles)/Build 5585

**Comment by illi-kun** [comment]
Dupe of #18491.

**Comment by pisskop** [comment]
My guess is this:
        "durability": -2

https://github.com/CleverRaven/Cataclysm-DDA/blob/be97190025acfc212e675e0a004560a99302cf4c/data/mods/survivorweaps/gun.json#L11
