### ISSUE TITLE
Inconsistent rounding in damaged items

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18510]
Inconsistent rounding causes items to change status on save+load and also means full hp vehicle parts display as slightly damaged.

Marking as priority because it is confusing and likely to be causing more problems than visible on the surface.

**Comment by Zireael07** [comment]
Is #18315 related? I wasn't able to repro...

**Comment by Zilenan91** [comment]
It is. #18375 is also related.

**Comment by Coolthulhu** [comment]
I didn't see it in action for a while. Does it still happen?

**Comment by Coolthulhu** [comment]
I didn't see it recently. Seems to be fixed.
