### ISSUE TITLE
Commit history merge conflict

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#18513]
The Craft Gunpowder PR seems to produce rebase conflicts.

**Comment by illi-kun** [comment]
I have no idea what should we do with this. Anyone who know git magic better could comment this issue?

**Comment by BorkBorkGoesTheCode** [comment]
@narc0tiq ?

**Comment by narc0tiq** [comment]
I have no idea what you're referring to. Link me?

**Comment by BorkBorkGoesTheCode** [comment]
Hmm, it's the Generic Guns mod, not the CG mod.
gg_magazine_override
error: could not apply 0ba39do... Generic_Guns: Magazine naming tweaks.

**Comment by narc0tiq** [comment]
Still no idea what you're talking about. What are you trying to do, what's your initial state, what are you executing? Does anything in <http://help.github.com/>, like [Resolving a merge conflict from the command line](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/) help?

**Comment by illi-kun** [comment]
Closing since it seems to be a local issue with your repo.
