### ISSUE TITLE
Car Batteries should require mechanical 0 or alternatively electronics

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#18517]
Exactly what part of unbolting (or in many case hand unwinding) the battery and putting a new on into the casing is mechanical or requires more than a passing familiarity with how batteries or current work?

With the lack of working vehicles, even a simple change such as this allows a desperate player to walk around with a (heavy) encumbering battery in the hopes of finding a suitable host for it.

**Comment by Reclusive-reptile** [comment]
Worse yet, the swappable storage batteries were added to represent something a minimum wage  yahoo at a battery share service could hot swap in minutes takes 2 mech skill. Wonk all around.

**Comment by mugling** [comment]
Probably retain the `wrench` requirement but drop `mechanics 0`?

**Comment by Reclusive-reptile** [comment]
Bolt turning 1 at most. Tool quality of that level is woefully underused.
