### ISSUE TITLE
Suggestion: make drive by wire and normal controls mutally exclusive on same tile

### ISSUE THREAD

**Issue by Beanzy** [CleverRaven/Cataclysm-DDA#18519]
~~Jenkins build 5585, Windows x64 Tiles~~

~~I just noticed that the option to toggle dome lights for my character's deathmobile must have disappeared in one of the fairly recent builds.~~
![c](https://cloud.githubusercontent.com/assets/15885173/18812685/f34615c4-82a9-11e6-959d-f978a53bbaba.PNG)

~~The option to toggle dome lights still appears for other vehicles I've come across, so maybe it's related to the size of the control list?~~

NVM I'm an idiot.

So, drive by wire controls are functionally identical to normal controls _except_ for the ability to toggle dome lights apparently.

I assumed that both types of controls were mutually exclusive, but they are not.

So, suggestion to add dome light toggle to drive by wire controls, and make both types of controls mutually exclusive on the same tile. You can already drive a vehicle with exclusively one type of control, so I don't see why both need to be installed on a tile to have full control of a vehicle.

**Comment by Leland** [comment]
Closing - old and no movement. Feel free to ping me here if there's still interest, or make a new issue.
