### ISSUE TITLE
Kell-Tec SUB-2000 has price of 56$

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#18526]
Kell-Tec SUB-2000 has price of 56$ that is way too low. At the same time price of Glock 19 is 690$. 
Real price of Kell-Tec SUB-2000 should be around 750$:
 https://www.gunsamerica.com/948059068/ON-SALE-KelTec-Sub-2K-40SW-Mags-Kel-Tec-2000.htm

Actually you can google price lower that 700$, but we must take game balance in count. It is better that Glock 19 by stats,

**Comment by mugling** [comment]
Looks like typo, PR would be appropriate
