### ISSUE TITLE
Id conflict in Blaze mod

### ISSUE THREAD

**Issue by Reclusive-reptile** [CleverRaven/Cataclysm-DDA#18537]
The gel razor vehicle part has id: "sickle" which conflicts with the sickle tool in the base game resulting in an over-ride that spawns the gel razor in gardening supply stores.

**Comment by Xpyder** [comment]
omg, that's what happened in that ranch I visited!  I just thought the farmer who used to live there was some sort of psycho.

**Comment by mugling** [comment]
Mod author has had notification and this closure message should also bump the issue for them
