### ISSUE TITLE
Wander spawns not respecting escalation mechanic?

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#18531]
My understanding is that dynamic spawns are supposed to start with basic zombies and escalate to specials over time.  But I've just done 5 dynamic+wander spawn starts and run into 20-30 zombies before I can get to the first house, and that many again surrounding the nearest buildings, always with at least 1 brute and 1 or more shockers, and usually several more specials like feral hunters or acid spitters.  I've been running combat characters (starting with melee weapons, str 14, melee+unarmed+dodge all at 2, Krav Maga) and I keep getting overwhelmed before I can get into my first house, all within the first 12 in game hours.

This seems unintended because I just started a static+no wander start and there's almost no zombies to be found, there's only like 7 or 8 in the first 3 buildings.  The difference is staggering.

**Comment by Chezzo** [comment]
What do you mean dynamic + wander spawns?

**Comment by Xpyder** [comment]
The default I believe.  Static Spawns: False + Wander Spawns: True

**Comment by Vidiveni** [comment]
By default static spawns is 'on'. Dynamic spawns is an old system that isn't used much anymore. 

Game starts with plenty of specialized zombies regardless, which I think is intended.

**Comment by Zilenan91** [comment]
Static spawn worlds are far easier than wander spawns.

**Comment by Xpyder** [comment]
Static and wander are separate settings and not mutually exclusive.  And I know wanders are supposed to be harder, that's why I usually run them.

But in recent builds the setting seem to have changed dramatically and when I searched I didn't find any PR that seemed to be related and I'm just searching for what seems to be different.

I have been running the Bionic monster variants (Bionic Monster, Broken Cyborg, and the like).  It's possible the noise from the bionics is what's causing the spawns to get out of control, but in searching around I found posts about Dynamic spawns intentionally being modified to start with basic zombies, and Wander spawns (which seem to be the evolution of dynamic spawns) don't seem to be respecting that change.

Since I didn't find any other people mentioning it, I figured I'd shine a light and make sure it's not buggy.  If it's working as intended I'll keep modifying my build until I figure out what works.  I just don't like beating my head against a wall unless I know there's actually a passage behind it.

**Comment by pisskop** [comment]
Having started in the city since time immemorial, I can say that hordes have never, since their conception, respected the static spawn's '30 minute grace period'.

entirely intentional.

**Comment by Xpyder** [comment]
Tell me about it.  Remember back when every other day Antlered horrors and Zombears would spawn outside your sleeping area starting the first summer?  That was the pits, literally.  Spike pits everywhere man, as far as the eye could see.

**Comment by Xpyder** [comment]
I'll run a few silent ninjutsu starts see if that makes any difference.

**Comment by Barhandar** [comment]
"Intentional" does not mean "reasonable", nor does it mean "_intended_". And with how overpowered specials have become (presumably in response to player strength escalating), there _must_ be a grace period of only regular zombies with no base specials (changing evolution rate does not remove these), regardless of what kind of spawn you're running.

**Comment by pisskop** [comment]
they respect my spawnpool grace period

*shrug*

if theres an issue you should look at the spawn pool for early game zeds.

in monstergroups.json search for "_MID" and scroll to the top of that list

**Comment by Xpyder** [comment]
It seems that noise might be the key here.
I ran a few runs with ninjutsu and quiet and didn't get any specials.

There may be an unintended interaction between the noise escalation for wander spawns and any of the broken bionic starting classes.
