### ISSUE TITLE
Cloth roof installation time is negative

### ISSUE THREAD

**Issue by CR2041** [CleverRaven/Cataclysm-DDA#18532]
Vehicle construction menu lists install time for cloth roof as "-128849016 seconds". Attempting to install a cloth roof results in my survivor working on the vehicle until he dies of dehydration; even being interrupted by a 'You're tired' prompt doesn't stop the construction.

**Comment by Zilenan91** [comment]
We've done it. We've discovered post-apocalyptic time travel

**Comment by Teacher-Tim** [comment]
I'd die of dehydration too if I had to install a vehicle part for four point something years.

**Comment by mugling** [comment]
Cannot reproduce. What platform and build.

**Comment by rsofaer** [comment]
I'm pretty sure I also have this problem installing a travois.
