### ISSUE TITLE
The minigun needs an electrical power source

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#18551]
Previously, the minigun drained electrical power from a UPS when it was fired unmounted to a vehicle. Since this trait was removed, the minigun isn't as believable. If UPS gets fixed, please add a electrical drain feature to the minigun.

**Comment by mugling** [comment]
I'm not certain if ever drained UPS, but the idea itself is reasonable

**Comment by BorkBorkGoesTheCode** [comment]
I have an experimental in which the minigun drained 5 UPS power.

**Comment by Zilenan91** [comment]
It drains 5 UPS per shot currently, or at least says it does.

**Comment by mugling** [comment]
JSON specifies `ups_charges 1` so my error
