### ISSUE TITLE
Inconsistency in meat recipes

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#18555]
In some recipes, 2 dehydrated/rehydrated meats correspond to 2 raw/cooked meats (e.g. meat soup, meat pie, meat pizza, meat fried rice), while in others the ratio is 2:1 (nachos with meat, nachos with meat, and cheese, curry with meat). I suggest it to be corrected to 1:1 ratio in all recipes. 
Also, canned meat (tin can) requires 1 chunk of meat, while canned meat (glass jar) requires 2, though both recepies claim to produce 1 protion of canned meat.

(in latest experimental)

**Comment by Zilenan91** [comment]
Yeah it should be 1:1 for everything because in some ways you're deleting matter by requiring double the dehydrated food than regular food.

**Comment by DangerNoodle** [comment]
Smoked meat and jerky additionally contains vastly more nutrition per 

I suspect someone nerfed cooked meat without properly checking the math for all recipes. What was the reasoning though? Game balance wise, so far it has had no effect on my ability to stockpile meat to make starvation impossible, even moreso given I tend to always make smoked meat, jerky, or aspic (which uses bones and is therefore supposed to have slightly higher nutrition, if I recall).

If anything it only punishes early-game survivors who would resort to cooking meat to survive. This magnifies the disparity between early-game food concerns and late-game.

**Comment by tsulh** [comment]
> I suspect someone nerfed cooked meat without properly checking the math for all recipes. 
Yeah, it happened this spring, during my first game. Cooked meat was giving 50 nutrition before the change.

**Comment by Coolthulhu** [comment]
> I suspect someone nerfed cooked meat without properly checking the math for all recipes. What was the reasoning though?

I suspect it was something along the lines of "it's unrealistic, caloric value of meat is lower than the in-game one. I will fix the rest later". This is how most of the inconsistent and detrimental changes happen.

**Comment by DangerNoodle** [comment]
Same reasoning behind defunct nutrition deficiencies being in mainline?
