### ISSUE TITLE
JSON errors upon savegame loading cause world corruption

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#18558]
Trying to load a world with json errors will cause a duplicate character to be saved and make the world unplayable.

**Comment by Karlieb** [comment]
Why would it save... ah, yes; the new autosave thing.

**Comment by Zireael07** [comment]
I'm thinking the autosave on-exit thing should be made into an option which should default to off (so that the person who wants the game on a server and a save-on-connection-loss function can have it)

**Comment by Oskar636** [comment]
Did you close it because it's fixed? Or because some time has passed? Because unfixed bugs should not be closed.
