### ISSUE TITLE
Code::Blocks compile warning in iexamine.cpp.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#18568]
Getting the following warning every time I attempt to compile:

`E:\github\src\iexamine.cpp: In function 'void iexamine::fswitch(player&, const tripoint&)': E:\github\src\iexamine.cpp:1176:6: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow] void iexamine::fswitch(player &p, const tripoint &examp) ^`

Everything compiles and runs just fine when I disable warnings.

**Comment by BrettDong** [comment]
Which version of GCC are you using? I remember I also encountered this compile warning with GCC 5.3.0 on mac OS.

**Comment by Night-Pryanik** [comment]
Is this still an issue?

**Comment by Night-Pryanik** [comment]
Feel free to reopen if this still occurs.
