### ISSUE TITLE
Source control regression

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#18563]
I found f80fe5e in the commit log whilst trying to work out why a number of other PR's had become merge conflicts. That commit isn't attributed to a PR and contains 4.5k+ lines of unreviewed code changes.

The first priority is to verify this is just `astyle` and nothing else. From there we need to work out what to do next without causing further breakage.

Please can all contributors be aware that they should **not** rebase against those changes for now and could all developers please not merge any further code until we decide on a course of action.

**Comment by mugling** [comment]
It looks like that commit was added after #18548 which itself resulted in a buildbot failure

**Comment by Rivet-the-Zombie** [comment]
I tested https://github.com/CleverRaven/Cataclysm-DDA/pull/18548 and it compiled and ran fine. Did the merge and the buildbot choked on it due to astyle regression (can somebody please remind me how making the buildbot's operation so incredibly brittle is an improvement) so I ran the affected files through astyle in order to satisfy our picky little bot. It compiled properly.

**Comment by mugling** [comment]
> I tested #18548 and it compiled and ran fine. Did the merge and the buildbot choked on it due to astyle regression

The `astyle` check is automatically run for each PR and this has been the case for some time now. Wait for the green tick symbol before merging. If it doesn't appear (or you get a red cross) the buildbot found some problems with that PR.

> can somebody please remind me how making the buildbot's operation so incredibly brittle is an improvement

This isn't the case. Last week you merged an untested PR with a JSON error. The buildbot failed the build which is both the correct behavior and indeed the only possible outcome. For the more recent failures PR's were merged before automatic checks were complete. The `astyle` check has been around for a long time.

> so I ran the affected files through astyle

I don't think the changes to `game.cpp` are necessary to restore the build. Those 4.5k lines are untested and broke a large number of PR's due to merge conflicts. It is worth pointing out that they were also automatically pushed to a large number of users.

> to satisfy our picky little bot. It compiled properly.

AKA "It compiles - ship it", see [here](http://english.stackexchange.com/questions/48443/meaning-of-ship-it). All our recent buildbot problems have been due to human error - we push untested code and/or ignored automated test results. By the same logic should we turn off compiler warnings because they could risk breaking the build?

**Comment by Rivet-the-Zombie** [comment]
>This isn't the case.

When it comes to this stuff it is. Prior to enforced astyle, the buildbot was happy to do its job if the code compiled. Now we can have good code (like https://github.com/CleverRaven/Cataclysm-DDA/pull/18548) that the buildbot refuses to compile because there's a bit of whitespace that it doesn't like. That is not an improvement in my book.

>I don't think the changes to game.cpp are necessary to restore the build.

I see now that game.cpp is not listed in the astyle whitelist. I should have kept astyle away from that one.

>By the same logic should we turn off compiler warnings because they could risk breaking the build?

I've been having to do that on my end for several weeks now, yet apparently the buildbot doesn't care about the particular warning that I keep getting:

`E:\github\src\iexamine.cpp: In function 'void iexamine::fswitch(player&, const tripoint&)':  
E:\github\src\iexamine.cpp:1176:6: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow]  
 void iexamine::fswitch(player &p, const tripoint &examp)
      ^`

**Comment by mugling** [comment]
> When it comes to this stuff it is. Prior to enforced astyle, the buildbot was happy to do its job if the code compiled. Now we can have good code (like #18548) that the buildbot refuses to compile because there's a bit of whitespace that it doesn't like. That is not an improvement in my book.

At times I share your frustration about `astyle` but I'd prefer a coding standard even if it's one with which I wouldn't have picked myself. Overall code quality has improved a lot so we must be doing something right.

> I see now that game.cpp is not listed in the astyle whitelist. I should have kept astyle away from that one.

It's easily done though when you are hurrying for a fix. At some point this will happen again to one of us. If the fix doesn't look trivial then reverting the bad PR is probably a better option.

> I've been having to do that on my end for several weeks now, yet apparently the buildbot doesn't care about the particular warning that I keep getting:

It's because it cross-compiles and presumably doesn't output that error. You could PR any compiler warnings you are getting and I'll take a look at them.

Have you considered trying to merge in batches as opposed to picking one PR daily?

**Comment by Rivet-the-Zombie** [comment]
>Have you considered trying to merge in batches as opposed to picking one PR daily?

I used to do that, but Real Life™ has been getting in the way for a good while now. By the time I get home from work and get settled in for the night I've typically got just about enough time to do a single PR before I have to crash and start all over again.

**Comment by mugling** [comment]
If you're busy there's nothing wrong with skipping a day

**Comment by Rivet-the-Zombie** [comment]
After more than three years of work on this project without a single missed day? I'd probably have a conniption.

**Comment by mugling** [comment]
Excessively low review times have likely been contributory in the recent breakages. In particular only a few hours for review of a C++ PR is too short - we have a number of good reviewers who would probably have suggested refinements.

My other concern is if a JSON PR goes through and another developer objects necessitating reverting it that could upset the contributor if they have taken that as the signal to continue work on the subject. Again low review times exacerbate that.

Although the fix I've written for this should resolve the current problem I don't want to trivialise it too much - the PR queue is deadlocked and we ran 4.5k untested lines on an indeterminate number of users machines. If this hadn't been detected early, and any more PR's merged, we would be in serious difficulty now and stuck with doing a lot of manual rebasing.

If you want to maintain the GH stats then you could consider correcting JSON typos and the like - such single line changes are reasonable for self-merge and much preferable to merging a larger PR. The other alternative is to start work on a mod as there is no risk of a merge conflict and I can't see why anyone would object to a developer merging their own mod content.

**Comment by Rivet-the-Zombie** [comment]
Aside from fixing a broken build, it's policy that we never merge our own contributions.

**Comment by mugling** [comment]
It should also be policy that PR's are reviewed. Only a few hours for a C++ PR is inadequate and has caused some fairly significant problems as outlined above.

What do you propose to do on a day where there aren't any suitable PR's to merge?

**Comment by Rivet-the-Zombie** [comment]
Thus far I've used those days to submit fixes and new content of my own, and it's worked quite well for a little better than three years now.

**Comment by mugling** [comment]
Well there hasn't been a problem with anything controversial being merged so shall we leave this at not merging PR's until the buildbot displays the green tick symbol and/or the manual equivalent tests have been run?

**Comment by Rivet-the-Zombie** [comment]
That works for me.
