### ISSUE TITLE
Active item processing invalidates item_location

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#18570]
`process_item` at `map.cpp::4637` invalidates `item_location` for any active item. Doesn't look like it should have to do this - anyone know anything more?

**Comment by kevingranade** [comment]
Forgot to add why I was closing this.  There's no rationale for why item_location should NOT be invalidated by process_item.  item_location is not stable across any number of operations, and is documented as such, so expecting them to remain intact is the bug here.
