### ISSUE TITLE
Crafting menu search prefixes don't work

### ISSUE THREAD

**Issue by zapa1928** [CleverRaven/Cataclysm-DDA#18573]
Win 7 bulid ver.  0.C-18865-g595705b (tiles) / bulid 5601

- Unlock all recipes
- bring up crafting menu
- press / and type `c:dehydrated` or `t:hammer` or `s:elec `

It doesn't show any corresponding recipes.

It worked all right in bulid 5579 (i didn't download versions in between )

**Comment by jaked122** [comment]
`c:dehydrated` doesn't look right to me, but I just tried to run it and it looks like you might be right.

`c:food` also seems to be broken... This is odd.

I'm rebuilding right now, I'm going to look at the source to see if a call was flummoxed, but the search code itself hasn't changed for some time.

**Comment by jaked122** [comment]
It would appear that it was introduced here. dcb1d34751b9ee9ecd1133aeb528f62735ebed65

I don't see any indication that it wasn't intentional, but I don't understand why. 

I suspect that @mugling intended to go about writing a new search function, but never got around to it.

I'm a bit peeved that this happened, as it seems that there was no new system in place to replace the one that was removed. This was one of my favorite parts of the gui actually.

**Comment by mugling** [comment]
Yes, it's a known regression which I will be working on at some point. This fix might come after I update the crafting code to support mixed alternatives (eg. `WRENCH 2 OR MECHANICS 2`)

**Comment by jaked122** [comment]
Okay, that's good then. How was it broken though?

**Comment by mugling** [comment]
> How was it broken though?

The crafting code is horrible - I wrote the shortest implementation that would suffice. A new implementation might avoid the prefixes in favor of a specific search dialog?

**Comment by jaked122** [comment]
I honestly prefer the prefixes, less mucking about.

**Comment by mugling** [comment]
> I'd really prefer a unified gui for this, and the prefixes are, in my opinion, the best way to go about this. I think I'd be up for writing it if you would consider that.

Yes such a PR would definitely be considerd - an idea with a (clean) implementation is always more persuasive than an opinion without one.

**Comment by jaked122** [comment]
@mugling, I've written a basic implementation, I'm not sure that it's quite up to snuff with the code quality (It's also not quite finished yet), but the parts I've written seem to work as I would expect.

There's a lot of change, and the code wasn't much fun to write, so I'd rather have some feedback on it before I'm completely finished.
