### ISSUE TITLE
Flint and Steel should require forging, More Survival Tools

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#18586]
It significantly outclasses a fire drill at the moment.

The "flint" for one of these actually isn't that hard to find in real life, if you know what kinds of rocks can be used. But the sparks from a Flint and Steel come from the steel.  It requires a High Carbon steel (like a used metal file) that was tempered at a high temperature and then quenched to be hard enough to throw sparks.

I think it should be changed to a forged project and should require 1 chunk of steel and 1 sharp rock.  This would make it more balanced as a later game alternative to the lighter for high survival characters.  This is doable out in the wilderness now with the forges and kilns under the construction menu.

**Comment by Noctifer-de-Mortem** [comment]
If not so already, I should also be found in sporting good store, military surplus stores and the such. Instead of forging it should just require fire and water and have a high level survival and/or fabrication skill required.

**Comment by Xpyder** [comment]
That's not how tempering works.  A normal fire would actually remove the temper and make the steel too soft to throw sparks.

**Comment by Xpyder** [comment]
Here's a video showing how to do it: https://www.youtube.com/watch?v=d7I4Z5t8Xdo

**Comment by DangerNoodle** [comment]
Implemented in pull request https://github.com/CleverRaven/Cataclysm-DDA/pull/19905
