### ISSUE TITLE
New trait to lower NPC Fear.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#18580]
This new trait would be animal empathy for NPCs, this trait would reduce the NPC's fear of the player and maybe raise trust as well. If not already so, the terrifying trait should make NPC's fear of the player higher. I originally thought the name of the old defunct inconspicuous trait would suit it but other than that I don;t have an idea.

**Comment by Coolthulhu** [comment]
Pretty already does that.

**Comment by Noctifer-de-Mortem** [comment]
Reduces fear? So using pretty and terrifying is redundant?

**Comment by Coolthulhu** [comment]
Wait, I got it wrong: pretty raises trust and fear.
Terrifying raises fear a lot, doesn't touch trust.

Anyway, any mention of inconspicuous trait here is misleading, the trait has nothing to do with attitude.

**Comment by Noctifer-de-Mortem** [comment]
What other name do you suggest, I though of innocuous but that implies you actually are not dangerous.

**Comment by Coolthulhu** [comment]
Which is pretty much what opposite of terrifying would be.

**Comment by Noctifer-de-Mortem** [comment]
It would be, I would also cancel it and vice versa.

**Comment by Atavic** [comment]
Respect?
