### ISSUE TITLE
[Inconsistent] Can only craft clean water inside

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#18581]
It was working previously in this playthrough, not sure what broke.
Using build 5581 from 2016-09-23

I'm wearing a small waterskin with water in it, and have a fire nearby.
I can craft clean water inside the shelter
I cannot craft clean water outside the shelter, or in the doorway (it fails to recognize that I have water available, despite wielding a full waterskin and wearing a full waterskin)

![image](https://cloud.githubusercontent.com/assets/12039454/18971662/b07ab61a-864a-11e6-9fec-369a081862f3.png)

![image](https://cloud.githubusercontent.com/assets/12039454/18971589/6685fa10-864a-11e6-92f2-db91e602c61d.png)

![image](https://cloud.githubusercontent.com/assets/12039454/18971603/6e6bc2aa-864a-11e6-8bf3-12a40a459bff.png)

![image](https://cloud.githubusercontent.com/assets/12039454/18971608/74a97e96-864a-11e6-93b0-4edc63cd785e.png)

![image](https://cloud.githubusercontent.com/assets/12039454/18971673/c3110ab8-864a-11e6-9c63-640aa0926cf4.png)

**Comment by codemime** [comment]
We probably need a dedicated label for craft PRs/issues.

**Comment by Leland** [comment]
Should be fixed by #19149. If others encounter this bug again, please open a new issue.
