### ISSUE TITLE
Vehicle repairs take too much time

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18595]
Old repair formula was more forgiving at low damage values.
We don't have "repair all" command, so the times should be low enough that the player doesn't fall asleep having to tab to the game, 'r'->'r', tab out the game, shitpost somewhere, tab back to game once it's done etc.

**Comment by Mecares** [comment]
Also i would love if pressing r would take me to something i can actually repair instead to the one part that is fubar.

**Comment by jaked122** [comment]
@Coolthulhu do you suppose that it would be a good idea to write the repair all command as an action?

**Comment by mugling** [comment]
> We don't have "repair all" command

I'm actually working on this (implemented as an activity queue)

**Comment by PlasmaChroma** [comment]
I think there may be a bug somewhere in or around the function scale_time in veh_type.cpp.  I can't puzzle it out exactly just yet but I can comment on it's effects.

Specifically I played with tweaking my mechanics skill up&down in debug, everything from 2 to 20 had no effect on repair times.  In fact tweaking it below the minimum required actually shows a reduction in  total time (though making the repair impossible) so maybe something is inverted here.

According to the code (or the intent of the code) it should be possible to cut the repair times in half via skills up but this isn't observed in the actual behavior of it.
