### ISSUE TITLE
`result_mult` broken for canned/jarred items

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18596]
Example: `"meat_canned"` recipe has it, but the produced jar contains only 1 charge of the result.

I'm pretty sure I made it work at once point, so this is a regression and not a missing feature.

**Comment by DangerNoodle** [comment]
I am certain that result multipliers had been working for quite some time. Does it at least work as intended for items not being produced in containers?
