### ISSUE TITLE
Survivor wetsuit Gear op

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#18599]
<a href="http://imgur.com/IArsrlu"><img src="http://i.imgur.com/IArsrlu.png" title="source: imgur.com" /></a>

Where are we getting 10 envio prot from?  Sturdy?  Something like 49 storage?

**Comment by Rivet-the-Zombie** [comment]
The environmental protection is likely due to the type of materials it's made from, it's sturdy because all survivor gear is made with Kevlar reinforcement to serve as armor. I'm guessing the storage comes from the pouches and such used in the recipe.

**Comment by Voskhod-1** [comment]
Considering that there isn't that much protection (6 bash 7 cut) it seems alright.

**Comment by BorkBorkGoesTheCode** [comment]
Could swap 5 points of environment resistance for an equal number of cut resistance

**Comment by Zilenan91** [comment]
Yeah I think it's fine. The Encumbrance is kinda high but the protection values aren't even enough to protect against regular zombies. Basically a worse Scavenger/Nomad Gear.

The environmental protection is odd but I still think it's fine too.

**Comment by pisskop** [comment]
Its a fortified backpack that is also acidproof!

**Comment by pisskop** [comment]
And yes, its 20 encumbrance _unfit_. 10 fit

**Comment by Zilenan91** [comment]
Yeah I don't think it should be totally acidproof now that I think about it

**Comment by flitvious** [comment]
The warmth should be upped, survivor wetsuit has only 15. Wetsuits in real life are really oppressive. Fifteen minutes out of water in a zipped wetsuit, and you wish to die (or dive).

**Comment by BorkBorkGoesTheCode** [comment]
>The warmth should be upped, survivor wetsuit has only 15. Wetsuits in real life are really oppressive. Fifteen minutes out of water in a zipped wetsuit, and you wish to die (or dive).

35 warmth, if the wetsuit was cut up during the process of integrating Kevlar vest?

**Comment by flitvious** [comment]
The warmth issue is integral to what a wetsuit is. A wetsuit must have a tight fit to be useful. It traps water between neoprene and skin, thus keeping the diver warm underwater. If it doesn't keep the wearer warm, it's useless.

So if a survivor would cut out neoprene sections from a wetsuit and replace them with kevlar, the wetsuit would not trap water well. So I always imagined that survivor wetsuit is a regular wetsuit with stuff sewn on top of it. Pouches, pockets, strips of kevlar and the like. This way it can keep its 100% coverage and environmental protection qualities.

Everything said above is about the underwater usage of wetsuits. If a survivor wants to make a tight-fitting armored suit to bash fungaloids on the solid ground, then yes, cutting it up and mixing with kevlar is the way to go. I imagine the resulting suit would also be less encumbering.

**Comment by pisskop** [comment]
the swetsuit is not skintight, presumably on purpose and presumanly by elongating it interior volume by adding plastic or kevlar over plastic.


this suit should be hot ss balls,  and its got so many leather pouches strapped on you should sound like a knight in plate walking, as each pouch slaps against the heavy suffocating rubber that presumably fills the gap
