### ISSUE TITLE
"amount" in tool qualities isn't used anywhere

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18607]
In all crafting recipes, `"amount":` is always followed by the redundant `1`.

**Comment by BorkBorkGoesTheCode** [comment]
Why?

**Comment by Rivet-the-Zombie** [comment]
I can't really think of any recipes that would ever need more than one of the same tool, though I'm sure that now that I've said that, somebody will provide us with an example.

**Comment by Oskar636** [comment]
This issue can have the organization tag for better access.

**Comment by illi-kun** [comment]
I'm not sure about "organization" tag here. I guess it's something about refactoring / code clean up.
