### ISSUE TITLE
Is the buildbot broken again?

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#18604]
None of the new PRs have been tested.

**Comment by DangerNoodle** [comment]
It seems to get stuck on occasion, if I recall.

**Comment by BorkBorkGoesTheCode** [comment]
It looks like the buildbot stopped working before my rewriting PR.

**Comment by narc0tiq** [comment]
Poorly. There is a hunk of Ruby junk (Jently) running as a sort of daemon
that polls GitHub and triggers a parameterized build on Jenkins. It then
polls Jenkins until the build finishes and finally updates GitHub with the
PR status.

Every step on the way is fragile: Jenkins can get locked up (as it was just
doing), the Jently script can do the same, the network connection to GitHub
can fail, or other problems I'd never imagine, like the disk getting full
of logs.

I've kicked the Jenkins service and it seems okay now. Thanks for the ping!

**Comment by DangerNoodle** [comment]
When in doubt, kick Jenkins until it works. Or until it politely asks you to stop hitting it.
