### ISSUE TITLE
Can reload an item with the contents of an adjacent unopened safe

### ISSUE THREAD

**Issue by lauriwesterlund** [CleverRaven/Cataclysm-DDA#18613]
Latest experimental.

The character is sitting in a bank vault. Attempting to reload his RM13 gives the option to use plutonium cells from his inventory or from an adjacent unopened safe.

https://www.dropbox.com/s/appidnrwor2bps7/reloadfromsafebug.zip?dl=0

**Comment by Reclusive-reptile** [comment]
Just tested on 5616, also happens with sealed crates.

**Comment by illi-kun** [comment]
Your save file is super-helpful for testing the issue, thanks for providing it.

**Comment by illi-kun** [comment]
I think #19002 touches similar issue and it can be used as a reference for fixing this.
