### ISSUE TITLE
Calcium in the Wilderness

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#18625]
A large obstacle to adding nutritional penalties and boons is the availability of nutrients and the proportions it is found in.

For a player living off the woods; in a world devoid of major cities, where do they find calcium?  Milk, cheese, spinach, all rot and are hard to obtain.  Beans as well.

So what do?  What can be added to ensure players can get their vita-mans?

**Comment by pisskop** [comment]
One solution suggested was kelp and seaweed.

Whether found in rivers, grown in shallows, or found in healthfood stores or gyms, seaweed and kelp should help ease the burden of healthy living.

**Comment by mugling** [comment]
I like the idea of kelp

**Comment by Noctifer-de-Mortem** [comment]
How about low traces of calcium in things like bones and bone broth?

**Comment by John-Candlebury** [comment]
Wild vegetables could also have a some calcium.

**Comment by Rivet-the-Zombie** [comment]
Nuts and seeds are a pretty good source of calcium. We could make a separate food material type for them and then adjust its vitamin levels accordingly.

**Comment by Coolthulhu** [comment]
* Insects (grubs, crickets) - big negative morale, low nutrition, moderate rot time, lots of microelements. Basically ghetto multivitamins. Could require frying/boiling to remove parasites (but that shouldn't improve morale levels). Low morale because our survivor has lived whole life in western culture that teaches that insects are unclean. Gourmand would obviously help here.
* Finely ground bones IRL have so much calcium that they are toxic to carnivores. Humans absorb less of that due to weak stomach acids, but also have less resistance. Chewing on fried bones could be a weaker version of that.
* Bone broth doesn't have much of said calcium - extracting it would probably require leaching the bones in vinegar instead of boiling them. Veggy broth has more calcium than bone broth.

**Comment by Noctifer-de-Mortem** [comment]
I think gourmand should at least nullify the grossness of insect, there are some people who like eating insects and it is likely a gourmand would be one of them.

**Comment by Voskhod-1** [comment]
The generic wild vegetables should be given a small amount of calcium (10-20%) I think, if they don't have it already. Green vegetables usually have an appreciable amount of calcium.

**Comment by DangerNoodle** [comment]
This seems to be more reason to shift nutrition to an opt-in system.

**Comment by pisskop** [comment]
hummm?

**Comment by DangerNoodle** [comment]
The discussion has occurred before. Some of my intended changes to Simplified Nutrition, for example. In addition to it broadening the scope of the mod, it was suggested that the others are not yet fully sure how to handle nutrition in the long run. It could entail making the vitamin system shifted to a mod like Flithy Clothing, or it could mean just ensuring all oddities with the system are resolved.

I do suspect that there might be situations where adequate nutrition is beyond the player's control, which might be additional support for the idea of not having it be default behavior, at least for the time being.

**Comment by pisskop** [comment]
Ive got insect meat up and falling off ant corpses, but I cant get it to cook up into insect meat.

Can the game change the material of the product based on the materials used to craft it?
Is there any way to get the game to id the material of the meat when it cooks or does insect meat need its own special recipe?

**Comment by pisskop** [comment]
> I do suspect that there might be situations where adequate nutrition is beyond the player's control, which might be additional support for the idea of not having it be default behavior, at least for the time being.

An opt-out feature is preferable to an opt-in feature

**Comment by pisskop** [comment]
We need somebody willing to work with the code and make a tag.  Or merge a temporary measure.

**Comment by mugling** [comment]
The code support is nearly done, its balancing thats holding this up

**Comment by Leland** [comment]
@pisskop this one hasn't had a discussion ongoing for about 7 months now – I'm going to close, but this is a "soft" close. I think you're on the money about the vitamin thing. However, with over half a year passed without discussion, and >600 active issues, I'm being fairly proactive at closing up items.

If you want this to stay open, go for it.
