### ISSUE TITLE
blood splatter layering issue (exp 5612)

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#18622]
There was a four tile bed and after smashing up some zombies the bloody tiles have an unexpected layering order.  Seems the correct symbol would be a red hash, or just a regular hash.

Cursor in the 2nd screenshot is one to the left of the player.

![2016-10-02 14_05_48-greenshot](https://cloud.githubusercontent.com/assets/19196781/19022609/ec1ecb14-88a9-11e6-9273-e8a5ecaa90e9.jpg)
![2016-10-02 14_05_55-greenshot](https://cloud.githubusercontent.com/assets/19196781/19022608/ec1de352-88a9-11e6-8857-02ae94d44fd0.jpg)

**Comment by Leland** [comment]
Not sure what's going on here. @busterbogheart can you clarify?

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed and not clarified enough.
