### ISSUE TITLE
Buff bird spawn in the spring.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#18629]
Birds breed in the spring and as such it would be nice to see this represented in-game. This would give a good source of feathers to use as fetching for wilderness archers.

**Comment by Voskhod-1** [comment]
Could we also buff the spawn of eggs in the Spring as well? As it currently stands, trying to Bird mutagen serums in any large quantity is an absolute grind-fest nightmare.

**Comment by pisskop** [comment]
I just so happen to have a mod that adds more birdies, but I never really get my survival up high enough to see if small birds can be butchered for feathers.

Does anyone know if a crow can be turned into feathers?

**Comment by pisskop** [comment]
Part of the issue with birds or reptiles or giant bugs I have is temp-related.

The freezing nights of spring will hinder this stuff.  And should.

**Comment by Zireael07** [comment]
@pisskop: I've gotten my feathers mainly from crows in all the times I've played :)

**Comment by Leland** [comment]
Closing due to stalled discussion. Ping me here to reopen if there's still interest in discussion/development.
