### ISSUE TITLE
Eskrima allows punch dagger, but not the diamond punch dagger

### ISSUE THREAD

**Issue by jim-huynh** [CleverRaven/Cataclysm-DDA#18626]
Version 0.c - 18938-g4ffa21d (build 0.c-5620)

Eskrima allows punch dagger, but not the diamond punch dagger.

**Comment by mugling** [comment]
I'm actually working on this right now!

**Comment by mugling** [comment]
See #18627

**Comment by jim-huynh** [comment]
Excellent!  Thank you.

**Comment by mugling** [comment]
Although your welcome it's purely coincidental - I already had that code written
