### ISSUE TITLE
Vehicle storage not using liters

### ISSUE THREAD

**Issue by Hibou48888** [CleverRaven/Cataclysm-DDA#18634]
In the vehicle examination menu, the total storage in trunks and other parts is still measured using the old volume system as opposed to the new liter/milliliter measurements.

**Comment by PlasmaChroma** [comment]
Configurable volume units has been merged into master: https://github.com/CleverRaven/Cataclysm-DDA/commit/c35e34ef8af6c984e512b344fd8c5b7a3f9fd7ab
