### ISSUE TITLE
Broken build #5634

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#18639]
As of merging https://github.com/CleverRaven/Cataclysm-DDA/pull/18399 Jenkins has failed half the builds due to:

`src/pickup.cpp:52:10: error: declaration of 'item item_idx::item' [-fpermissive]
     item item;
          ^
In file included from src/inventory.h:5:0,
                 from src/character.h:6,
                 from src/player.h:4,
                 from src/pickup.cpp:5:
src/item.h:113:7: error: changes meaning of 'item' from 'class item' [-fpermissive]
 class item : public JsonSerializer, public JsonDeserializer, public visitable<item>
       ^`

For what it's worth the PR that triggered it compiled and ran (Windows curses/tiles) fine when I tested it. This error is beyond my ability to fix, but I'm holding off on simply reverting it (that UI update is pretty awesome) in case the fix is something that's simple for a person with more knowledge than myself.

**Comment by codemime** [comment]
The most probable culprit is [this line](https://github.com/CleverRaven/Cataclysm-DDA/pull/18399/files#diff-e610b54f8dd1a620dfc2a3b4f40a9c95R52): variables and their types should never have the same name.

> but I'm holding off on simply reverting it

IMHO it's not the worst option since that PR has certain ways of code improvements.

**Comment by Rivet-the-Zombie** [comment]
>IMHO reverting is not the worst option since that PR has certain ways of code improvements.

We can still do that just as easily, but I'm hoping that we don't have to lose that cool new item stacking functionality.

**Comment by Zireael07** [comment]
Pls don't revert. Item stacking is too good to lose.
