### ISSUE TITLE
NPC trainer provided incorrect training

### ISSUE THREAD

**Issue by Waladil** [CleverRaven/Cataclysm-DDA#18642]
Asked an allied NPC to teach me brawling. Instead, I trained my electronics from 5 to 6. He can't even teach electronics 6 normally! Did not receive brawling.

(Not complaining, the skill in electronics is more valuable to me, but it's definitely a bug)

**Comment by chugu** [comment]
this happened when character's unarmed skill is at 0 (brawling should be available at unarmed skill 1), I asked NPC to teach me brawling, got increase in bartering instead.
