### ISSUE TITLE
Correcting welding googles recepie if needed

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#18641]
Welding googles recepie was changed recently:
https://github.com/CleverRaven/Cataclysm-DDA/pull/18635

I personally think that current version far better than before.
Before change welding googles required "tailoring" 4 to craft. Now it require "mechanics" 3, just like crude welder.

The whole points of change were:
* Welding googles is used for welding, that is related to mechanics. Is not related to tailoring directly
* Player need to invest heavily in tailoring to craft welding goggles but at the same time in mechanincs to craft crude welder. But both of this items actually related to the same things - welding and mechanins
* goggles_nv at the same time require real profile skill: "electronics" that is logical
* Welding googles recepie looks like hand made improvisation (ductaping any google and covering it with spray) but not like something that require tailoring
* Car repair with ductape is heavily nerfed now. So if player have no access to "true" welder then the only option to proper repair - is crude welder. But it is unusable without welding googles.

But current version not ideal either. Currecntly welding googles require only mechanics 3 and do not use any other skills

Let's talk about it. Should it be changed or remeain as it is now?
Important thing- if you post suggestion than make your point and write reasons to your recommendation.

**Comment by Firestorm01X2** [comment]
I  think that yes, it should changed  to mechanicns 2 and fabrication 1 because:
* Night vision googles uses additional skill (tailoring 1) for crafting
* Welding gooles recepie looks like hand made tinkering. It is related to fabrication

I think better requirment should be mechanics 3 and fabrication 1. My point:
* It is should be easier to create welding ggogles thatn welder itself. That is why mechanins 2 (-1 from current version)
* Recepie should use fabrication because reasons I mentioned before. So that is why fabrication 1. Also it should compensate mechanics 2

**Comment by Oskar636** [comment]
I don't think it should use mechanics because mechanics is for engines, welding and such. It's like saying building a wheel should require driving skill. I would go for fabrication 2, because it does need to be pretty well made to protect you from the welding.

**Comment by Firestorm01X2** [comment]
Is there any thing for that you can use welding googles instead of welding?

**Comment by Treah** [comment]
Tailoring 4 is easy to get to as you can craft a needle pretty much day one, mechanics however is a much harder still to level up. If anything the change made them harder to get not easier. However I do think the crafting should be a duel skill such as fabrication 2 ( mechanics 3 ) or some such. I agree it has  nothing to do with Tailoring

**Comment by Oskar636** [comment]
I think mechanics are much easier to get then tailoring with the new tailoring system. Training tailoring requires a lot of thread and clothes and a lot of changing damaged clothing. When training mechanics requires you to have a soldering iron, 10 pipes and much less clicking.

**Comment by Firestorm01X2** [comment]
I think it shouldn't be about easy/hard. It should be about logical and balanced. 

Before change welding googles reqired tailoring 4 but at the same time crude welder require mechanics 2 only. But just compare what is harder to craft- googles from spray can and ductape or working welder from scrap and flashlight parts.

And actually I mistaked- crude welder requires mechanincs 2 not 3.
So crude welder require mechanics 2 only to be crafted. That' why I thnink crafting welding googles shouldn't be much harder.

**Comment by Firestorm01X2** [comment]
Here is vote poll:
http://smf.cataclysmdda.com/index.php?topic=13404.0

**Comment by SeanMirrsen** [comment]
>And actually I mistaked- crude welder requires mechanincs 2 not 3.
So crude welder require mechanics 2 only to be crafted. That' why I thnink crafting welding googles shouldn't be much harder.

See, the problem with that logic, is that different skill levels are not linearly difficult. They make sense within their own line of progression, not outside.

Using tailoring for what is not, fundamentally, a piece of clothing, is wrong, that much I agree with.
However tying Mechanics into making welding goggles, is just as wrong - there is nothing even remotely mechanical about them. You can't just tie welding goggles to a crude welder by required skill.

In that sense, fabrication is definitely the way to go for crafting the goggles.
Now for autolearn, yes, you could make a case for the mechanics skill. Even then, though, I see fabrication being just as likely a candidate.

And once you've arrived at the skill you're targeting, you need to look at what items are craftable at what level within that skill. The mechanics level needed to craft the crude welder has no relation to the complexity of the goggles. Swimming goggles, the sort that require a bit more effort to stay watertight, require Fabrication 4, in a recipe with a similar premise (convert a different kind of goggles). With that in mind, Fabrication 3 seems fair.

So I'll cast that as my vote, then. Fabrication 3. It makes sense in general, and you do learn the recipe from a book on Fabrication.

**Comment by illi-kun** [comment]
> Fabrication 3 seems fair.

This seems to be a good choice.
