### ISSUE TITLE
Different clothing for professions depending on season.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#18647]
This stems from the problem that professions have clothing suited for the spring where it still is cold but if you take a summer start then you have to find new clothes. I suggest a way similar to the male/female item differentiation of items in the professions.json but instead for seasons. For example, military professions could have winter army gear if a winter scenario/world option is chosen.

**Comment by codemime** [comment]
It's certainly not a duplicate (since no issue was opened), but [the same idea](https://github.com/CleverRaven/Cataclysm-DDA/pull/17222#issuecomment-226821874) was suggested by @pisskop in #17222.

**Comment by pisskop** [comment]
yuppers.

id like it, but it did have its own challenges.

- requiring ui changes for chargen or double the professions
- things average people wear all the time (hoodies and sweatpants, gloves, a hat) being considered too 'good' for starts
- why would a player take a tshirt when they could take a flannel jacket
- point balancing

**Comment by codemime** [comment]
I don't think we should allow players to choose their starting clothes during chargen. Hardcoded lists adjusted to seasons would suffice. See my comment there.

> things average people wear all the time (hoodies and sweatpants, gloves, a hat) being considered too 'good' for starts

Something warm enough, but very cumbersome?

**Comment by Noctifer-de-Mortem** [comment]
It would be coded into the json the same way other items are in professions, no choice given, it all depend on season that the player is starting int either by scenario flag or in world options.

> Hardcoded lists adjusted to seasons would suffice. See my comment there

While this would work exceptions for professions like military ones would be made to use winter army clothes instead of of regular army clothes.

**Comment by Barhandar** [comment]
In addendum: I would like to be able to override the season for clothes only, so that, for example, if I want to start out in winter in summer clothes (or vice versa) I can, and the game does not force me to have winter clothes in winter, merely defaults to them.

**Comment by kevingranade** [comment]
If someone wants to implement this, feel free.
