### ISSUE TITLE
Byproducts broken for batch crafting

### ISSUE THREAD

**Issue by Reclusive-reptile** [CleverRaven/Cataclysm-DDA#18653]
recipe :: create_byproducts does not multiply the result by the batch size, so only one byproduct is produced.

**Comment by illi-kun** [comment]
Could be related to #17852.

**Comment by Reclusive-reptile** [comment]
Clarification, there is a mismatch between the batch size and the number of byproduct produced.

1 cooked cattail= 1 cooked cattail + 10 plant fiber.
5 cooked cattail= 5 cooked cattail + 10 plant fiber.

The batch should have produced 50 plant fiber.

**Comment by WizardOfOoo** [comment]
Can confirm, same problem with making fruit juice.

**Comment by WizardOfOoo** [comment]
Was this fixed by #20309?

**Comment by Reclusive-reptile** [comment]
The last batch of lard I made gave me the proper count of cracklins. So, yes this is fixed now. Closing
