### ISSUE TITLE
Safe Mode Manager max view distance trigger is not max view distance

### ISSUE THREAD

**Issue by MisterFox** [CleverRaven/Cataclysm-DDA#18650]
I've been grappling with the Safe Mode Manager to try to understand it and for a while I thought that maybe it just didn't work -- turns out it's bugged when it comes to specifying trigger distance.

To test the distance where it stops triggering, I spawned a chicken and added it to my blacklist. Here are the rules:

![Safe Mode Manager rules](http://puu.sh/ryw37/e51630d0ff.png)

Expected result: Whenever a hostile monster or a chicken are within view, trigger safemode.
Actual result: Whenever a hostile monster or chicken are within 50 tiles, trigger safemode.

When I spawned the chicken, I activated safemode and let it run away from me to see when the safemode alert would trigger. When the chicken was 51 tiles away (but still within view!), safemode stopped triggering.

**Summary: According to the Safe Mode Manager UI, '0' for distance is supposed to be max viewdistance, but in reality only works up to 50 tiles.**

_Additionally, even with the 'test' returning the proper monsters, the * wildcard doesn't seem to trigger on hostile monsters at all._

**Comment by OzoneH3** [comment]
Yeah, it's a typo .. fix is up.

* is working fine here with hostile, friendly and any attitude.
Used the same settings as you, triggers on anything hostile and on chickens.
