### ISSUE TITLE
Eating from sealed container placed in vehicle storage spills the test liquid

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#18654]
Example: get tin can of meat soup, place in trunk, press E to eat it. 3 meat soup is spilled on the floor, empty tin can placed in trunk

**Comment by busterbogheart** [comment]
Possibly related to #18239 #17734

**Comment by eliotcougar** [comment]
I confirm that... It is not related to the #17734 which seems to be fixed...

**Comment by AdonaiJr** [comment]
I confirm that. Happened  a couple days ago, exactly like Voker57 said.

**Comment by Night-Pryanik** [comment]
Dupe of #18168.
