### ISSUE TITLE
Second mission for Free Merchants generate friendly bandits

### ISSUE THREAD

**Issue by eliotcougar** [CleverRaven/Cataclysm-DDA#18668]
0.C-18991-g142f3fd (tiles)
MISSION_FREE_MERCHANTS_EVAC_2

I got the mission, went to the destination, three bandits there... They don't attack me... I had to kill them one by one anyway... Mission completed successfully, but now I have -300 debuff feeling guilty for killing innocents...

**Comment by illi-kun** [comment]
I've created new label for all of these missions / quests issues.

**Comment by eliotcougar** [comment]
This bug applies also to MISSION_OLD_GUARD_REP_1, REP_2 and REP_4... It seems that bandits are always friendly towards the player...

**Comment by I-am-Erk** [comment]
No longer happens. Closing until contradicted.
