### ISSUE TITLE
ranged gunmod weapons cannot be installed anymore

### ISSUE THREAD

**Issue by BrainDamage** [CleverRaven/Cataclysm-DDA#18661]
M320 grenade launcher, AUX flamethrower, masterkey shotgun, etc cannot be installed anymore on weapons, the failure message is:
"This <modname> doesn't appear to be modded. You can't remove any mods from your <modname>"
probably because of the dual state of being a weapon and a gunmod, but now it seems that gun takes priority and it's trying to handle the gunmods instead of mounting it.
replication procedure:
wish for aux flamethrower
wish for M4A1
activate flamethrower mod to install
I suspect it's a conseguence of PR https://github.com/CleverRaven/Cataclysm-DDA/pull/18627/files altought i haven't done any bisecting/regression test to confirm it

**Comment by mugling** [comment]
Fixed in master
