### ISSUE TITLE
First Old Guard Mission sends to (0:0)

### ISSUE THREAD

**Issue by eliotcougar** [CleverRaven/Cataclysm-DDA#18667]
0.C-18991-g142f3fd (tiles)
MISSION_OLD_GUARD_REP_1

Just accepted the first mission at the Refugee Center and it sends me to the coordinates 0:0, and reveals 3x3 map there...
Refugee Center is at 82:165... I wonder, if I spend a lot of time to go to 0:0 will I find a quest objective there at all?..

**Comment by eliotcougar** [comment]
Re-testing this twice on a new map with debug console... This time it didn't even send me to (0:0)... Instead I got a debug message "Couldn't find bandit_cabin"... There's no mission objective marker at all...

**Comment by eliotcougar** [comment]
Okay, now I see that this is a duplicate of #16390 
If I understand it correctly, all we need is an overmap location bandit_cabin to spawn in the world... There's a bandit_cabin.json in mapgen... The mission worked almost fine when I placed it manually nearby before asking for a quest... (Bandits were friendly)

**Comment by illi-kun** [comment]
Closing as a dupe. Feel free to add more details to the initial issue.
