### ISSUE TITLE
Russian lang in Filter don't working

### ISSUE THREAD

**Issue by Meklon2007** [CleverRaven/Cataclysm-DDA#18672]
Hello.
In version 0.C-5623 of game i use Filter for find items in many menus in russian lang. It worked. But special prefixes in crafting menu didn't work. Example: 'нож' - is work, 'c:доска' - isn't work.
In version 0.C-5640, 0.C-5641 Filter don't work at all (filtering russian, only show english letters).

**Comment by BrettDong** [comment]
> But special prefixes in crafting menu didn't work. Example: 'нож' - is work, 'c:доска' - isn't work.

This problem was previously reported as #18573 , the root of this problem lies in the core program itself, the internationalization part is innocent.

> In version 0.C-5640, 0.C-5641 Filter don't work at all (filtering russian, only show english letters).

Would you like to describe more about this problem? Do you mean you input some Russian letters, but the game only accepts English letters?

**Comment by illi-kun** [comment]
First part of your report isn't relevant to language, as @BrettDong correctly stated.

Concerning second part, version 0.C-5642 works just fine for me (tested with part of word: "само"):
![1542](https://cloud.githubusercontent.com/assets/5421954/19184835/9c387280-8c87-11e6-8634-6891f0ff491a.PNG)

Please create another issue with more details about second part of your report if it's still an issue for you with more details about your OS, version of the game (with or without tiles support), etc.
