### ISSUE TITLE
It's impossible to type anything on non-English language in Windows CURSES version

### ISSUE THREAD

**Issue by Meklon2007** [CleverRaven/Cataclysm-DDA#18675]
Hello, i wrote about this problem late. Now i describe more about this problem:
![2016-10-07 14_50_53- _windows_](https://cloud.githubusercontent.com/assets/12417354/19189036/640cb756-8c9e-11e6-8af0-7e54c532e64a.png)
![2016-10-07 14_41_15-cataclysm_ dark days ahead - 0 c-18948-ge1a8223](https://cloud.githubusercontent.com/assets/12417354/19189038/69829250-8c9e-11e6-9233-ede320233aca.png)
![2016-10-07 14_46_51-](https://cloud.githubusercontent.com/assets/12417354/19189042/6c8fcc1a-8c9e-11e6-9fb9-7f829bde5ecf.png)

**Comment by BrettDong** [comment]
I tried on macOS, and I could successfully input Cyrillic letters without problem. So I guess the problem is related to Windows IME?

BTW, is commit `g0438f7a` on your own branch? I can't find it on git history.

**Comment by Meklon2007** [comment]
I understand where is the problem. It is not in build, it is in version. First i download tiles - the russian worked. When - i download only curses. In curses russian didn't worked. Only in curses.
Ok - will download tiles and set ascii mode.

g0438f7a - download from http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Curses/cataclysmdda-0.C-5642.zip

**Comment by illi-kun** [comment]
I confirmed that it's not possible to write any cyrillic symbols in any input fields.

**Comment by illi-kun** [comment]
Could be related to #6008.

**Comment by BrettDong** [comment]
Oh yes, it's related to Windows CURSES. I recall it's impossible to input any Chinese character in Windows CURSES builds too, IIRC. (Not 100% sure because I've been using macOS and linux for years, and haven't touched Windows so long)

**Comment by Night-Pryanik** [comment]
0.C-6372, Win 10 x64, curses.
Was able to successfully input cyrillic characters.
![default](https://cloud.githubusercontent.com/assets/11132525/24580080/27792072-1713-11e7-8bff-84854cdb4eb2.png)
Should be closed?

**Comment by kevingranade** [comment]
Looks like it, thanks for checking all of these, it's very helpful.
