### ISSUE TITLE
Repeater mod Vault missions - two starting points

### ISSUE THREAD

**Issue by eliotcougar** [CleverRaven/Cataclysm-DDA#18676]
In the Vault there are two quest givers: SFC and CPT... If you approach the CPT, you are given the mission to make the repeater mod and you are given the book to do that (MISSION_OLD_GUARD_NEC_COMMO_1)... However, if you approach the SFC, he gives you the third mission right away (MISSION_OLD_GUARD_NEC_COMMO_3) even if you didn't meet to the captain yet...

**Comment by Leland** [comment]
Probably best to just turn [this line](https://github.com/CleverRaven/Cataclysm-DDA/blob/69662e71acee1a69bd9e14b62777182194243b1a/data/json/npcs/npc.json#L53) to `MISSION_OLD_GUARD_NEC_COMMO_1`

**Comment by ZhilkinSerg** [comment]
Addressed in #21808.
