### ISSUE TITLE
NPC spawning on the Ranch during missions fails sometimes

### ISSUE THREAD

**Issue by eliotcougar** [CleverRaven/Cataclysm-DDA#18679]
After today mission tests I've ended up with the Ranch missing the Bartender NPC, so I can't really test brewery missions correctly... The code is in ranch_construct_16 and there are some weird checks for the case if Bartender is already there (what? how?)

And the Barber NPC that should appear in the barn appeared in the barn on the other ranch in the adjacent region of the map to the north... That region of the map was not even revealed before... The code is in ranch_construct_13

(I agree, mission/NPC code is a mess)

I forgot to note that it happens in version 5640, 0.C-18991-g142f3fd (tiles) after commit "Fix NPCs spawning in wrong places"...

**Comment by Leland** [comment]
Combining with #20862
