### ISSUE TITLE
Debug message about 'CVDMachine' when loading the game

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#18673]
```
DEBUG    : Could not find an iexamine function matching 'cvdmachine'!

FUNCTION : iexamine_function iexamin_function_from_string(const std::string &)
FILE     : src/iexamine.cpp
LINE     : 3548

Press spacebar to continue the game...
Press I (or i) to also ignore this particular message in the future...
```

Built from commit 142f3fd76b784e0430d3d5a120be124f4389634c.

**Comment by Coolthulhu** [comment]
Can't reproduce.
Does it stil happen with recent builds?

**Comment by mugling** [comment]
Have you edited JSON by any chance?

**Comment by BrettDong** [comment]
> Does it stil happen with recent builds?
OK, the debug message disappears in most recent builds.

> Have you edited JSON by any chance?
Nope, I didn't modified anything.
