### ISSUE TITLE
Maybe bug when crafting predmets

### ISSUE THREAD

**Issue by Meklon2007** [CleverRaven/Cataclysm-DDA#18683]
Hi. Maybe bug (my version g0438f7a). 
When i craft any thing (where i stay in save file) (example Дубина or Самодельная перевязь) and my inventory full, that this good making and drop down on the floor, but there nothing. Nothing in inventory and nothing on the floor, but program write to me  what - this was made.
If goto from place where i stay in the save file, thing making and drop down on the floor correct.
Saved file was attached.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/516946/save.zip)

**Comment by shedya** [comment]
офигенный инглиш...
все правильно, предмет дропается под игроком, его разве не видно, если в направлении указать 5?

**Comment by Meklon2007** [comment]
Уф, хорошо что можно писать на русском. Как уж смог написать... ;-)
В том и проблема, что не дропается предмет, скрин прилагаю. Создал предмет Дубина, там где стоял,  на камнях. Отошел и смотрю, дубины нет, сделал просмотр всех предметов по V Дубины не нашел. И так с разными предметами. Если уйти с камней, то дропается без всяких проблем.
Тут видно толи камни не нравится, то ли еще что.
Скрин приложил, что у меня выходит.
![2016-10-07 23_19_32-cataclysm_ dark days ahead - 0 c-18995-g0438f7a](https://cloud.githubusercontent.com/assets/12417354/19204379/3a28c83e-8ce5-11e6-9094-49ceb7d0f006.png)

**Comment by illi-kun** [comment]
@Meklon2007 @shedya the official language of this repository is English, please use it. We have a dedicated sub-section in the forum for discussions on Russian.

**Comment by shedya** [comment]
Can be closed as it's not a bug, pile of rubble (which was translated as кучка камней) hides items on its tile.
