### ISSUE TITLE
Error while loading save with attached bayonet

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#18689]
I have error while loading my save:
14:44:49.162 : src/item_factory.cpp:886 [const itype* Item_factory::find_template(const itype_id&) const] Missing item definition: bayonet

Bayonet was attachen to shotgun,
Save is here:
https://drive.google.com/open?id=0B1p1ntUqVzBJSlM2dWNPX0VCYjg

**Comment by codemime** [comment]
The bayonet was [removed completely](https://github.com/CleverRaven/Cataclysm-DDA/pull/18627/files#diff-8431b1d7c16a19e4a114a484b0958efdL27) in #18627 without a replacement for migration. Pinging @mugling.
