### ISSUE TITLE
Vehicle tank liquid has no weight

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18685]
I think it did have weight at one point, but I'm not sure.

Still, it doesn't have it at the moment. A giant tanker full of locksmith kits (2 liters of locksmith kits weigh a ton - it's >20 times denser than platinum and >10 times denser than V12 engines) will still only weight as much as a giant tanker. Would, if locksmith kits were liquid, but still.

**Comment by DangerNoodle** [comment]
The mental image of how lockpick-in-a-bottle would even work is now stuck in my head thanks to that example you gave

**Comment by mugling** [comment]
Fixed in master
