### ISSUE TITLE
H&K Railgun ammo and magazine rarity 

### ISSUE THREAD

**Issue by Mecares** [CleverRaven/Cataclysm-DDA#18680]
My current character has found around half a dozen H&K G80  Railguns but only a single magazine and not a single projectile of ammunition even after surviving several years and raiding many bunkers, military outposts and labs.

I am fine with having to find these three separately since it is a really good gun, but in my humble opinion it seems like the ammo is too hard to find. It seems weird if ammo is rarer than the gun using it. Unless of course i was just unlucky and it is caused by small sample size.

In general i would think of something like magazines should spawn more often than guns and ammo more often than magazines.

Even if i now would find some ammo for it, it would be a case of too good and rare to use and it would most likely keep collecting dust in my weapons pile.

Currently the guns to ammo droprate seems to be 1 to 1 but the magazines only drop in the "rare" item group and in there less often than for example power armor hauling frames.

So i would suggest to add the G80 magazine to the "mags_milspec" and "military" item groups and bump the drop rate of the ammo a bit and/or add it to the "ammo_rifle_milspec" item group.

Alternatively i would suggest to add a crafting recipe for a weaker handmade ammo made from another ferromagnetic material since there is no cobalt in the game.
Chromium dioxide for example could be used for that it is an almost useless item that already in the game not too easy to find and it is a weaker ferro-magnetic material than cobalt making it reasonable and realistic to reduce the stats of the handmade ammo by ca. 40% compared to factory made. It also could be balanced to require to have already some ammo for the G80 to craft them to get the dimensions of the projectiles right.

Before i try to implement that i would like to know what you think and if those suggestions would have a chance to be implemented if i made a pull request.

**Comment by Atavic** [comment]
@Mecares 

> It also could be balanced to require to have already some ammo for the G80 to craft them to get the dimensions of the projectiles right.

Just imagine a gun that's the best in game. This gun has no ammo: its bullets can be created only by crafting. That will leave the gun usable only with high Mechanics skill.

**Comment by mugling** [comment]
Fixed in master
