### ISSUE TITLE
Vehicle water purifier does not work when there is not any clean water in the vehicle

### ISSUE THREAD

**Issue by jim-huynh** [CleverRaven/Cataclysm-DDA#18702]
Version: 0.C-19058-g4b775d0 

The vehicle water purifier does not work when there is not any clean water in the vehicle.  I thought that this was a generic purifier not working bug, but when I added one charge of clean water, the purifier started working.

**Comment by mugling** [comment]
Fix is included in #18691

**Comment by mugling** [comment]
Fixed by #18691
