### ISSUE TITLE
cannot craft clean water with all tools and ingredients ready.

### ISSUE THREAD

**Issue by Autastic** [CleverRaven/Cataclysm-DDA#18709]
water ingredient shows up as red. i collected the water from the rain. using the latest experimental. 

proof: http://imgur.com/a/yFdeW

update: a little more info. the red is where i can craft water, the blue is where i can't craft water. http://imgur.com/a/Ag37v

things to note: its raining outside, the river is directly north, i'm using rain water, and visibility is not an issue. i've tried with flashlight on and off.

**Comment by Reclusive-reptile** [comment]
I think this also affects water stored in constructed barrels/standing tanks and has something to do with terrain providing materials.

**Comment by Treah** [comment]
Based on what you posted there, it looks like when you have the availability of 2 water sources ( one from the river and the other from the container ) then it flags it as no water is available. I am curious if you remove the funnel and attached container then are you able to craft water near the river again?  Also verify if you have a tool that can boil the water is in your inventory and not something that sitting in a counter somewhere. This would explain why you can and cannot clean it near the river but you can in your house.

**Comment by yowshi** [comment]
no if you have unclean water on hand or in a container near you you will not be able to use uncleaned water in any recipe. 
although you can use it if you have both clean and unclean water as options in the recipe and around you you can then use the uncleaned water in the popup menu.
this bug goes all the way back to 0C-5650

**Comment by Jiamil** [comment]
Bug also in 0.C-5647

**Comment by Oskar636** [comment]
Still an issue in build experimental 5861 .

**Comment by Xpyder** [comment]
Related to incomplete PR #19149

**Comment by kevingranade** [comment]
should be fixed with the overflow prevention.
