### ISSUE TITLE
Various Item Action Menu issues

### ISSUE THREAD

**Issue by eliotcougar** [CleverRaven/Cataclysm-DDA#18703]
- [x] Take vitamins action is grayed out even if you have multivitamins in your inventory.
- [ ] Heat up food does not take into account the kitchen unit in the vehicle.
- [ ] Repair metal/plastic/kevlar does not take into account the vehicle welding rig (also, Kevlar is not capitalized in the menu)...
- [x] ~~Sheath/draw a knife is grayed out always.~~ see #14452
- [x] Use holster prefers steeltoed boots as a holster and ignores other holsters on a body, thus unusable.
- [x] Pick a lock prefers using fancy hairpin over locksmith kit.
- [x] There are many grayed out nondescript "Turn on" and "Turn off" entries in the list. (fixed by #19367)
- [x] The menu itself is missing most hotkeys.
- [x] There is no ability to set those hotkeys.

**Comment by Reclusive-reptile** [comment]
> The menu itself is missing most hotkeys and there is no ability to set those hotkeys.

"?" can be used in the menu to set hot keys but is not communicated to the player in any way.

**Comment by Leland** [comment]
With the merge of #19367 all of this needs to be retested. Can anyone confirm which of these are still present?

I've moved the issue description to a checkbox list so we can more easily see which have been accomplished.

**Comment by eliotcougar** [comment]
The main issue right now is that some actions that can be performed with multiple items (vitamins, calcium, gummy vitamins; makeshift lock-pick, locksmith kit, hairpin; sheath, boots, scabbard; flashlight, head torch, gasoline lantern; and so on) will have only one action in the Action menu - the one with the item that was picked up first...
So, if you wear boots, then sheath, then scabbard, then you cannot put your sword in the scabbard, because there is only "sheath using boots" action in the menu... Same with lock-picking, multiple light sources, and taking vitamins...

Ability to set hotkeys in that menu (pressing ?) is still not communicated to the player, and also that other menu is hard to understand and contain a lot of nondescript duplicate entries...

The new [a]ction menu solves most problems, but does not take into account possible actions using vehicle-mounted components...

In the end it's better to leave only one of the menus... The new [a]ction menu being almost complete now, functionality-wise...

**Comment by wapcaplet** [comment]
Confirmed, several of these cases are still reproducible in 0.E-9737-g511ddcb179:

1. Spawn a calcium tablet, then spawn a vitamin. `%` only shows the calcium tablet.
2. Spawn a pair of western boots, then spawn a sheath. `%` only shows the western boots.
3. Spawn a fancy hairpin, then spawn an improvised lockpick. `%` only shows the fancy hairpin.

**Comment by hexagonrecursion** [comment]
> * The menu itself is missing most hotkeys.

I am sorry, but this is so vague that I do not know how to test this.

**Comment by hexagonrecursion** [comment]
> * Use holster prefers steeltoed boots as a holster and ignores other holsters on a body, thus unusable.

steeltoed boots can not be used as a holster anymore

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by hexagonrecursion** [comment]
> * Pick a lock prefers using fancy hairpin over locksmith kit.

Using a fancy hairpin (id: fc_hairpin) to pick locks is no longer allowed

**Comment by Lord-Helmchen** [comment]
does  [Magiclysm] Technomancer Toolbar cannot pry nails #53996 belong here ?

**Comment by hexagonrecursion** [comment]
> does [Magiclysm] Technomancer Toolbar cannot pry nails #53996 belong here ?

No. This issue is about actions that can be performed via other means, but are missing from the % item action menu.

https://github.com/CleverRaven/Cataclysm-DDA/issues/53996#issue-1092342476
> TToolbar now has nail prying 1, but it still can't be used for it, neither by **examining** a boarded up door, nor by **(a)ctivating** it nor via the actions menu.

Also: please don't lump many bugs together even if they are related in some way. It is often the case that they are debugged and fixed separately. Lumping them together makes it hard to keep track of the troubleshooting process.

**Comment by I-am-Erk** [comment]
I believe a majority of these are resolved, and I'm not a big fan of keeping too many separate individual issues in a blanket one like this because it leads to no longer accurate issues from six years ago getting revived infinitely.
