### ISSUE TITLE
World won't load because of extra slash in address

### ISSUE THREAD

**Issue by johnshanks** [CleverRaven/Cataclysm-DDA#18721]
My world, on multiple characters, will no longer load because of an extra slash being inserted in the address (e.g. save//World Name/...). 

This is triggering load errors on artifacts.gsav, a .map file in the maps dir, "o.0.0" in the top level of the world dir, "o.0.-1". From that point on, the loading process repeats between attempting the last two items.

This affects both characters I have in this world. A new test world (that many not have the same mods), did not have this issue on a brand new char after saving, exiting the app, and reopening.

This occurs on my previous version, 0.C-19031-g167a723 (don't have the build number), and on the current build 5677. I've never encountered this before. The world loaded fine two days ago, and has for the last few months.

If there is an edit I can make to the save to fix this, please let me know.

**Comment by Leland** [comment]
Closing because of age and lack of corroboration. However, I'm making a reference to this in #9972 so that this isn't forgotten.
