### ISSUE TITLE
examining vehicles no longer show type of vehicle in 5677

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#18720]
When examining a vehicle, you could get the type/name?  Currently in 5677, the type/name field of vehicle is blank in the list of items for the vehicle in the bottom right.

**Comment by eliotcougar** [comment]
If you press e to rename it and then escape without typing anything, the name of the vehicle is displayed...

**Comment by mugling** [comment]
Fixed in #18730
