### ISSUE TITLE
ranged gunmod weapons require a nonexistant skill

### ISSUE THREAD

**Issue by BrainDamage** [CleverRaven/Cataclysm-DDA#18739]
ranged gunmod weapons require a nonexistant skill and can't fire
steps to reproduce:
wish for M4A1
wish for masterkey shotgun
cheat yourself skills shotguns 1 and rifles 2 to install the mod
activate the mod to install
wield the weapon
cycle the fire mode until the mod is selected
fire ( doesn't matter if the weapon is loaded or not )

global error:
Skill "weapon" possessed by _PlayerName_ requires a non empty context.

while event log shows "You need at least weapon 2 to use this masterkey shotgun"
except of course such skill doesn't exist

**Comment by BorkBorkGoesTheCode** [comment]
Weird. Weapon is supposed to only affect installation of gunmods.

**Comment by MisterFox** [comment]
I suspect it may be related to #18660
