### ISSUE TITLE
Repair fuel tank with duct tape should be possible

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#18733]
Currently car repair with duct tape almost not possible with few exceptions. That is reasonable because of duct tape do not contain magic. But some things with it should be possible. Like fixing leaking fuel tanks.

Early player have no option to fix leaking fuel tank without welder. But it technically may be possible with duct tape. Example of using duct tape to fix holes in boat by Mythbusters is here:
https://www.youtube.com/watch?v=oIY-QauOxRY

Here is duct tape boat again by Mythbusters:
https://www.youtube.com/watch?v=MjL6WOgwzbY

If duct tape can help boat to stay afloat than it should work for holes in fuel tank (or even in other type of tanks like water tank). Certainly  duct tape IRL  can't fix almost trashed fuel tank but it can be simplified in game.

**Comment by mugling** [comment]
Try for a PR on this. The cloth roof should provide a good example of the require JSON

**Comment by Firestorm01X2** [comment]
I tried to play with JSON and kinda find problem. There is   in toolsets.json may be multiple "tools" in requirment and I certanly can create toolset for ducttaping and welding and  add "duct_tape,25" as tool in addtition to welding tools. But "welding_standard" contain  "qualities": [ { "id": "GLARE", "level": 2 } ]. I don't need glare protection for ducttaping.

**Comment by mugling** [comment]
Don't allow welding of tanks - simple

**Comment by Coolthulhu** [comment]
Duct tape can be rare, welding is the most common way of fixing everything vehicle-related.
Unusual components are bad.

**Comment by Firestorm01X2** [comment]
> Don't allow welding of tanks - simple
Long time ago it was possible and combine ductaping and welding. Is it possible now?

**Comment by mugling** [comment]
> Duct tape can be rare, welding is the most common way of fixing everything vehicle-related.
> Unusual components are bad.

Disagree. Damage should be less frequent but more challenging to resolve. Currently we have the worst of both - running down shrubs requires tedious repairs.

The vehicle mounted welder provides for no challenge. Gas tanks being rarely damaged but leaking slowly when they do and requiring precious duct tape is a novel mechanic. Other emergent mechanics then appear, for example multiple tanks to guard against breakdowns in the wilderness.

**Comment by DangerNoodle** [comment]
It is relatively easy to pick up the duct tape recipe, though.

**Comment by Coolthulhu** [comment]
> Gas tanks being rarely damaged but leaking slowly when they do and requiring precious duct tape is a novel mechanic.

It isn't.
Vehicle tanks are craftable with welders and never damaged (except on spawn).
Having them require unusual components would only add the tedium of having to find (or craft) a fresh tank and would still become meaningless as soon as you find relevant books.
This would be forced variety that only deviates from the good things.

**Comment by mugling** [comment]
> Vehicle tanks are craftable with welders

Plastic tanks (the majority?) are not

> and never damaged (except on spawn)

So we have a lot of leak handling code that does nothing?

Overall I want to try and break this cycle of vehicles being damaged really easily and then requiring repair using a plentiful but tedious to use resource (vehicle welding rig)

**Comment by Coolthulhu** [comment]
> Plastic tanks (the majority?)

Nope, they're too small to be useful. Most tanks are metal tanks scrapped from cars or welded from sheets. Number of slots taken is more important than tank availability, since gas tanks have to occupy internal tiles that aren't exposed to damage.

> So we have a lot of leak handling code that does nothing?

Yeah.
There is no reason for a tank to be on the outside of the vehicle since there is no benefit to not putting it inside where it is safe from the cinematic explosions that don't make sense anyway.

> Overall I want to try and break this cycle of vehicles being damaged really easily and then requiring repair using a plentiful but tedious to use resource (vehicle welding rig)

Cheap components should not require expensive repairs, though.
If we had compressed tanks, fuel enriching tanks, hydrogen storing tanks - those could require rare components.
But tanks crafted from scrap using a welder should not require anything more expensive than scrap and welding.

**Comment by mugling** [comment]
Well we do have external tanks?

If tanks don't leak and shouldn't explode lets just drop all that code - it doesn't work well and causes a lot of problems

**Comment by DangerNoodle** [comment]
Which presumably are only used by players that find an APC and lack the mechanics skill to install internal tanks. They are more exposed, and a leak in one turns the high capacity from an advantage to a drawback.

**Comment by Firestorm01X2** [comment]
So now duct taping and welding is not supported with JSON tweaking. Right?

**Comment by Chezzo** [comment]
There was an episode of Mythbusters where they made a car completely connected with duct tape and they drive it around and try to break it and are unable to.

Duct tape IS magic.

**Comment by kevingranade** [comment]
it's extremely questionable that this would work at all, gasoline is a pretty powerful solvent after all, and the only way we have of doing repairs is "good as new".
