### ISSUE TITLE
Vehicle-mounted water cannon and flamethrower report "empty" one shot too early

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18749]
- Spawn flaming electric car
- Drain its tanks
- Refill them with 200 gas and 2 water
- Fire 2 shots with water cannon and flamethrower each
- In both cases the second shot will fail with "no ammo" message
- Bursts will work just fine

**Comment by mugling** [comment]
Still present in `master`
