### ISSUE TITLE
Menu inconsistency: right direction selects or switches tab

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18748]
Some menus have right click as mark for selection, others have it only switch the tab.

**Comment by Zireael07** [comment]
'some'? I thought the only one which uses right as selection was multidrop.

**Comment by eliotcougar** [comment]
Yes, this "right = select" in multidrop is often an inconvenience... I've accidentally dropped some items in the past while trying to manage held/worn items in the past... I never get 100% used to it and prefer to use AIM whenever possible...
IMO, making 'spacebar' to select items in multidrop would be better, but 'enter' is so deep in the CDDA culture code now probably...

**Comment by illi-kun** [comment]
Particular case of #12112.
