### ISSUE TITLE
Construction Screen is cumbersome

### ISSUE THREAD

**Issue by jaked122** [CleverRaven/Cataclysm-DDA#18746]
The construction gui is very cumbersome because it combines the complexity of the crafting gui with absolutely no search support (beyond that provided by categories).

I am wondering if you all would mind if I took a shot at writing another search filter for it?

There are some things I have some questions about, why is there a keyboard shortcut for _everything_ that can be fitted into a keyboard shortcut? 

Nobody knows all the keyboard shortcuts so I'm not sure that it make sense to do it that way, the fact that the shortcuts change between the categories makes it inconsistent and worse, exposes the arbitrariness with which the constructions are assigned.

Even worse than this is that there isn't a way to scroll through the requirements and description of the constructions.

I would appreciate if you would weigh in on these ideas:

- [ ] Add a search filter
- [ ] Add a way to skip through the pages of construction
- [ ] Add a way to scroll through the description of the requirements of the construction.
- [ ] Find an alternative to assigning keyboard shortcuts arbitrarily  
    - Use tab and shift tab to move to the right and left categories, freeing up left and right to page through it.
    - Use page up and page down to scroll up and down the construction specification.

**Comment by Zireael07** [comment]
@codemime: You seem to have done a lot of cool stuff with inventory screen recently. Another candidate for improvement?

**Comment by mugling** [comment]
If you want to work on it I'm sure it would be appreciated

**Comment by Zireael07** [comment]
uh, @mugling, while I was a contributor once, it was a long time ago and I never contributed code, just jsons

**Comment by Coolthulhu** [comment]
The shortcuts in construction menu are horrible since they can't even stay consistent between versions.
No need to preserve those.

**Comment by jaked122** [comment]
Okay, nobody seems to mind.

I'm going to start working.

**Comment by mugling** [comment]
> uh, @mugling, while I was a contributor once, it was a long time ago and I never contributed code, just jsons

I mean @jaked122 is welcome to start work on it if they want to

**Comment by eliotcougar** [comment]
Just make a slightly modified copy of the regular crafting interface...

**Comment by mugling** [comment]
> Just make a slightly modified copy of the regular crafting interface...

Please don't, it's a horrible implementation

**Comment by eliotcougar** [comment]
> Please don't, it's a horrible implementation
Okay, another proposal: make a better implementation that is shared for both crafting and construction... And most importantly, it should have the same UI logic behind it (i.e. same keypresses do same actions, search everywhere)...

**Comment by mugling** [comment]
Try for incremental improvement based upon what we already have

**Comment by jaked122** [comment]
@Coolthulhu 

Well here's the source of that 

`std::string hotkeys = ctxt.get_available_single_char_hotkeys();`

If I remove that assignment, I won't have to deal with ripping it out.

@mugling I was just thinking name search for now (it also happens to be all that I know _how_ to do for constructions).

**Comment by mugling** [comment]
Constructions are really broken. Name search would help
