### ISSUE TITLE
Unified toolmod limitations

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18755]
* No message on application
* No warning on improper magazine/ammo settings. For example, you can mod a toolmod which expects plutonium stored in car battery
* Removing mods requires manual unloading first. Should unload automatically and fail mod removal if it isn't empty after unloading or list tools that can be unloaded automatically

**Comment by mugling** [comment]
> For example, you can mod a toolmod which expects plutonium stored in car battery

Can you explain and give an example?

**Comment by Coolthulhu** [comment]
No example, it's just that there is no warning if you try that.
I had it happen when working on the vehicle battery mod.

**Comment by mugling** [comment]
Did you specify `acceptable_ammo`?

**Comment by Coolthulhu** [comment]
Wait, it could be just that `magazine_integral` thing. Nevermind.

Still, it looks like there is nothing preventing specifying incompatible magazines. For example:
```
"magazine_adaptor": [ [ "arrow", [ "50cal_drum" ] ] ]
```

**Comment by mugling** [comment]
Good point. I added a check in the last PR that the magazines were actually valid, but not that they were actually sensible. I'll submit a PR against yours that adds that check

**Comment by mugling** [comment]
All of these were fixed in the addendums to #17008
