### ISSUE TITLE
Unable to use crafting recipes from books. 

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#18775]
Currently I am unable to craft duct tape even tho i have all of the required skills to craft this and I have a copy of mechanical mastery book in my inventory. I currently have Mech 6 and fab 3 which is above the requirements to learn this recipe. This is probably due to the previous bug where all recipes were available. 

1. Are recipes that are in books no longer usable until you learn them from books? 
2. Is this really a bug or is the requirements just different from the item browser? 
3. Can someone else confim this issue.

**Comment by mugling** [comment]
> Is this really a bug or is the requirements just different from the item browser?

Item browser is very outdated

**Comment by Treah** [comment]
Im guessing I can find the requirements somewhere in the json file but im not having luck locating it :( if this is indeed just not having the skill level needed that is.

**Comment by Treah** [comment]
Confirmed that this should work as I have fab 3 and the json file shows that i only need fab 3 to be able to craft this. 

Source: /json/recipes/recipe_others.json
```
{
  "type": "recipe",
  "result": "duct_tape" recipe,
  "category": "CC_OTHER" recipe_category,
  "subcategory": "CSC_OTHER_MATERIALS",
  "skill_used": "fabrication" skill,
  "difficulty": 3,
  "time": 18000,
  "book_learn": [
```

**Comment by illi-kun** [comment]
Try to spawn any other book from "book_learn" list or add +2 to your fabrication skill and try it again.

**Comment by Treah** [comment]
Created a new char and using the debug menu gave DYI Compendium then increased fab to 5 checked list of recipes and was able to find duct tape. Same char increased mech to 4 and gave the person Mechanical Mastery ( same book that I have ) and he was also able to craft duct tape..... Unsure why the other char cannot.. Maybe some file / world corruption caused by when all recipes were available?

**Comment by Treah** [comment]
Hmmm i guess ill close this as testing somehow destroyed my save game world and I cannot reproduce the problem. :(
