### ISSUE TITLE
M60 in inventory but cannot install on IFV (even though item exists to install)?

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#18778]
I have an M60 in my inventory and I have one the IFV's from the Tank mod.  I wanted to mount the M60 to the IFV, but it will not let me do this, even though I have one in my active inventory and can see the installation item in the vehicle installation list?  Furthermore, I also see multiple entries for other HMG's, M2 .50 and others, installing the same thing into the vehicle? I wondered why they have two of the same install? This is not automatic just manual M2 install and the M2 install.

**Comment by rsofaer** [comment]
I've been having a bug where items I've just acquired/crafted (a welding rig or an upgraded solar panel for instance) aren't being counted for installing on vehicles.  If I wait a turn/walk around it gets counted.  Is it the same bug?

**Comment by hmstanley** [comment]
Never been able to get it to acknowledge that I have it to install. Maybe?  Even if I walk around, still can't install the gun.

**Comment by Mecares** [comment]
Try unloading it, at the moment having a magazine or ammo belt prevents you from installing weapons into vehicles.

**Comment by mugling** [comment]
> at the moment having a magazine or ammo belt prevents you from installing weapons into vehicles.

I'd very much like to eliminate that limitation eventually

**Comment by hmstanley** [comment]
It was unloaded. No ammo.

**Comment by hmstanley** [comment]
Well. I narrowed this down a bit. It appears that any machine gun that is belt fed, with the exception of the M2, cannot be mounted on the turret, even when in my inventory. I added a belt fed mechanism to one of my FN-SCAR-L and before I could mount it, but after the modification, I could no longer mount the gun. Very odd to me. Any other belt fed machine gun, like the 249 or M60, would not indicate that I had the weapon, even though I had it in my inventory. Strange bug.

**Comment by hmstanley** [comment]
This is real pain too.. I have two HMG's that I want to mount and for the life of me cannot understand why they aren't mountable on the IFV?  The M2, all the assault guns, etc.. are mountable, but not the M60, M249, M240, etc.. all belt feed, (with the exception of the M2) are not mountable, even though I have them in my inventory.  When i go to construct the item, it indicates that it's not there?  Very very strange.

**Comment by hmstanley** [comment]
I think I've figured this out.. the M240, 249 and M60 all include an integrated MOD, a bi-pod.  If that mod is included in the firearm, it will NOT install on the turret.  Anything with mods will NOT install on a turret.  There doesn't seem to be a way to remove that mod from the weapon however.

**Comment by hmstanley** [comment]
Dupe of 18886
