### ISSUE TITLE
Drawing is slow on Windows

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18779]
Visible mostly on screens that redraw a lot - like main map and inventory.

**Comment by DangerNoodle** [comment]
I have noticed this, yes. I tend to get better results after playing around with software rendering mode and the scaling setting, but I forget the combinations that help.

Additionally, picking the wrong combination of settings tends to cause tile display to break.

**Comment by AdonaiJr** [comment]
It's running fine on my Windows (lastest experimental). I've experienced slowness like you said, in the past. As I remember, it's way better if you have a Graphics Acceleration Card (I have a "old" one, GTX260). When I use integrated graphics, it runs terrible.

I need to confirm it though. And Yes, the slowdown was mostly noticeable on craft menu and map.

**Comment by Leland** [comment]
Closing since this is a fairly vague issue and has been sitting for over 6 months now. Let me know if this was too hasty.
