### ISSUE TITLE
ARM Compilation issue

### ISSUE THREAD

**Issue by deathright82** [CleverRaven/Cataclysm-DDA#18776]
g++ seems to assume unspecified char is unsigned on arm.
changing line 9642 in /src/player.cpp to specify a signed char allows g++ to compile

don't really know much about c/c++, but i thought this was important as it was preventing me from playing on arm devices.

**Comment by BrettDong** [comment]
Which version of GCC are you using?

**Comment by illi-kun** [comment]
Line number isn't a good reference. Could you provide more context: text of error/warning, name of function with the described issue, etc.

**Comment by deathright82** [comment]
gcc (Debian 4.9.2-10) 4.9.2

screenshot is easier atm
![screenshot 2016-10-10 at 7 27 51 pm](https://cloud.githubusercontent.com/assets/10619383/19356942/baacb1f0-912c-11e6-8eb3-0fedfbf7f974.png)

**Comment by BrettDong** [comment]
Check this: [http://stackoverflow.com/questions/2054939/is-char-signed-or-unsigned-by-default](http://stackoverflow.com/questions/2054939/is-char-signed-or-unsigned-by-default)

GCC regard `char` as `signed char` on most platforms, but on Android GCC the default is `unsigned char`. Adding `-funsigned-char` solves the problem.
