### ISSUE TITLE
Crafting UI slowdown

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18781]
The recent crafting changes sped up some sections, but slowed down others.

Not sure what exactly slowed down, but opening the crafting menu on a tab with many entries takes ages, even in a relatively small crafting base.

**Comment by jaked122** [comment]
You wouldn't happen to know if it was after the search function was fixed for the crafting menu, would you?

**Comment by Oskar636** [comment]
It doesn't slow down on my laptop ( with all crafting recipes unlocked ) so I don't think this is a problem anymore.

**Comment by illi-kun** [comment]
@Coolthulhu could you double check this?

**Comment by Coolthulhu** [comment]
That specific slowdown seems to be fixed.
