### ISSUE TITLE
Combat knife crash (Wish for an item, crafting, maybe elsewhere)

### ISSUE THREAD

**Issue by eliotcougar** [CleverRaven/Cataclysm-DDA#18783]
Start a new game
Wish for an item
Search for "knife"
Move selection down to "combat knife"
Crash

Alternative: Learn all recipes, select combat knife in crafting menu...
Makeshift bayonet has the same effect...
Other (at least other craftable) items don't crash...

**Comment by mugling** [comment]
Same cause as #18774
