### ISSUE TITLE
regression: bows with installed modifications now require manual reloading

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#18780]
Somewhere between 477ed86fe0def2638cdc5583573d8ce5018e7acc and 0786eae11ed4877400ecca5eab8d191e89e0a4bc the longbow in my ongoing save started requiring manual reload, as if it had lost the RELOAD_AND_SHOOT flag.

It had a bow stabiliser / bow sight / arrow rest installed; removing those mods fixes it; reinstalling them breaks it again.

**Comment by mugling** [comment]
Fixed by  #18761
