### ISSUE TITLE
Automate the translation pot update

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#18796]
So that issue like #18657 could be spot earlier and make translation up to date.

If possbile, could someone setup the jerkins bot to also upload new translation pot to transifex?

http://docs.transifex.com/integrations/jenkins/
http://docs.transifex.com/integrations/github/

**Comment by BrettDong** [comment]
@cainiaowu May I have your contact?

**Comment by narc0tiq** [comment]
It's quite unclear to me what needs to be done here. Should I install something? Configure something?

I'm willing to add anything to the Jenkins that makes people's lives easier, but I know nothing of Transifex, so someone's going to need to unpack that for me.

**Comment by BrettDong** [comment]
[https://docs.transifex.com/projects/updating-content](Automatically updating source files)

**Comment by BrettDong** [comment]
The Transifex side has already been set, it automatically fetches the file `/lang/po/cataclysm-dda.pot` in master branch of this repo every day. So all we need to do is to set up a bot periodically runs `lang/update_pot.sh` and commit it.

**Comment by BrettDong** [comment]
The workflow of the automated script would be something like
0. Sync with the latest master branch: `git fetch upstream/master && git merge upstream/master && git push`
0. Delete the `translations` branch created last time: `git branch -d translations && git push origin :translations`
1. Checkout to a new branch: `git checkout -b translations`
2. Fetch translations from Transifex: `tx pull`
3. Run `lang/update_pot.sh`
4. Commit changes: `git commit -am 'Translations and pot update'`
5. [Submit a PR on GitHub](http://stackoverflow.com/questions/4037928/can-you-issue-pull-requests-from-the-command-line-on-github)
6. Reset to master branch: `git checkout master`

**Comment by narc0tiq** [comment]
Okay, well, Jenkins jobs tend to be read-only, but I know tooling (in the form of Jenkins plugins) exist for things like pushing branches and probably even making pull requests (might need an upgraded Github token; I don't think the current one has that privilege).

Would anyone like to look into it? I can grant you a login on [the new Jenkins](http://gorgon.narc.ro:8080/) (not a permanent URL) and sudo-capable SSH access to the machine it's running on. Poke me via email if you want to try it.

**Comment by BrettDong** [comment]
Okay, well, Jenkins jobs tend to be read-only, but I know tooling (in the
form of Jenkins plugins) exist for things like pushing branches and
probably even making pull requests (might need an upgraded Github token; I
don't think the current one has that privilege).

Would anyone like to look into it? I can grant you a login on the new
Jenkins <http://gorgon.narc.ro:8080/> (not a permanent URL) and
sudo-capable SSH access to the machine it's running on. Poke me via email
if you want to try it.

I found github-gem includes a command to submit pull requests on GitHub, so
we might implement the template and translation updates I do every week in
a bash script or something, then set it as a crontab task to execute every
Friday night for example.

**Comment by narc0tiq** [comment]
> github-gem includes a command to submit pull requests on GitHub

I've already got https://github.com/github/hub/ set up on ci.narc.ro, so that part is pretty well taken care of, but I'd imagine integrating as much as possible into the Jenkins to be the better idea. In fact, I like Jenkins even if only as a cron replacement, because we can save the logs and get status notifications easier.
