### ISSUE TITLE
Installed UPS conversion mods duplicated on save/load

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#18797]
Running 3e823735bd0932de194bce7623846ce0af9a9cc4:

On load, items with an installed UPS conversion mod appear to add an extra copy of it.

![ups-mods-for-everyone](https://cloud.githubusercontent.com/assets/3055062/19375333/e9839a86-91ca-11e6-9711-f375c1b3da8e.png)

I get an extra one on all three items on each save/load cycle.

**Comment by mutability** [comment]
The save json looks kinda crazy too, there are battery_ups items that contain more battery_ups items several levels deep

**Comment by Rivet-the-Zombie** [comment]
It's `battery_ups` all the way down.
