### ISSUE TITLE
Jently reports a OS X build failure

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#18795]
It started around #18737.

**Comment by cainiaowu** [comment]
In file included from src/armor_layers.cpp:8:
src/npc.h:748:24: error: 'get_path_avoid' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    std::set<tripoint> get_path_avoid() const;
                       ^
src/player.h:1447:28: note: overridden virtual function is here
        std::set<tripoint> get_path_avoid() const override;
                           ^
