### ISSUE TITLE
Slowdown when going downstairs

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#18798]
Going downstairs now takes about 4+ seconds instead of 2+. 

0.C 19195 g748c00f

**Comment by Coolthulhu** [comment]
Could easily be disc issue. It's incredibly variable.

**Comment by BorkBorkGoesTheCode** [comment]
>Could easily be disc issue. It's incredibly variable.

An earlier version didn't have this problem, and I ran both during the same timeframe.
