### ISSUE TITLE
Organized and Disorganized traits

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#18794]
Traits that affect the gross time to wield items from the inventory, in percentages.

This has a definitive impact on gameplay; at least as much as any other trait [deft, im looking at you].

This has combat effects and could encourage interesting playstyles.  This give us even more reason to want to store things on clothing or in easy to reach places.

Its good for roleplay; simple, vague, and easy to imagine.

**Comment by Coolthulhu** [comment]
First the numbers should be balanced globally. They're a mess at the moment - you can stunlock self to death by picking up a wrong item by accident.

**Comment by pisskop** [comment]
Wouldnt a Query to stop wielding/picking up/wearing suffice to eliminate that stunlicking?

**Comment by Night-Pryanik** [comment]
Closing due to the lack of discussion for more than a year.
