### ISSUE TITLE
Items that are damaged on vehicle are still shown as red even after repair

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#18809]
damaged the military ram in the front of the vehicle, fixed it and it still shown as red in the vehicle overview.  See screenshot: http://i1097.photobucket.com/albums/g355/wqcoleman/Capture_2.jpg.

Also, it is no longer reporting that no further repairs are needed for the vehicle, before, you would get a message, no message appears anymore upon further pressing of the "r" button.

**Comment by hmstanley** [comment]
it eventually turns back to Green.. after a few turns.. is this designed?

**Comment by Coolthulhu** [comment]
Could be just missing redraw.
Does it change colors if you close the menu and re-check after repair?

**Comment by mutability** [comment]
Did you perhaps damage the ram by.. running over zombies?
Parts with blood on them show up red (and gradually wash clean over time)

**Comment by hmstanley** [comment]
no and no. I did do a redraw, open and close, and repaired, open and close.. still red.. it eventually returns to green tho.

**Comment by hmstanley** [comment]
I would say after about 3-5 turns. I don't know exactly.

**Comment by Leland** [comment]
This seems like it was a one-time issue stemming from something else. Due to lack of corroboration and no further discussion in months, I'm closing this. If this is still an issue to the opener or anyone else, feel free to ping me here and I'll reopen; or just create a new issue.
