### ISSUE TITLE
Generic tanks, purification and funnels: UI hassle

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18815]
http://smf.cataclysmdda.com/index.php?topic=13464

Purifier now keeps water stored in the same tank. This tank is most likely the one under the funnel.
This means that you have to manually transfer the clean water to a separate tank if you want to keep funnel working.

Part of it could be fixed by allowing purifiers to be activated and making them clean the water before depositing, without intermediate stage of storing dirty water. This would allow funnels over clean water tanks to work.

**Comment by rsofaer** [comment]
I think a general ability to transfer liquids to/from an empty vehicle tank and between tanks of the same liquid would also work.  Then the clean water tank can be filled and the dirty water tank emptied so that rain can be captured again.

**Comment by Xpyder** [comment]
What about locking the purifier to it's own tank, like the funnel?  Long term it might be interesting for tanks to accept parts as input and output attachments, opening the way for more advanced automated sequences to be set up if we decide to head that route.
