### ISSUE TITLE
Crafting inventory (structure, not UI) sorting by ID

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18811]
Crafting inventory currently does a linear check for every single item it wants.
This is useful for abstract definitions of things, but also happens to be of linear complexity. Per every item - populating a craft menu requires checking every single ingredient for every single recipe on the page.
For example, if you have 100 non-stacking items and populate a page of 50 recipes with average of 2 ingredients, you need to do 1000 item checks. And that isn't even a big example - it's very easy to get a better one in the game.

A relatively simple way to fix that would be to bin inventory contents by item ID. This could be done on demand and stored in a `mutable` cache.
That is, a `std::map<item_id, std::vector<const item *>>` populated simply by going over all items and adding them to the list that has their type IDs as the key.

There is one problem here that needs solving first: the inability to have mixed AND/OR in recipes.
This functionality is actually used, using the subtype system for crafting tools.
Alternatively, a hack could be added: each item would "register" self both in its actual ID list and in the list for the subtype. This would slow things down by requiring ID checks, but would simplify writing and still easily offer speedups of up to 3 orders of magnitude.

Another problem is that currently the crafting system has some bugs. That's why this should probably wait a bit.

**Comment by mutability** [comment]
I don't think you even need to track the actual items, do you? Just a count.

**Comment by Coolthulhu** [comment]
Sometimes you do need the items, for example to tell apart `pseudo` items and real ones, to check battery special case, to count charges for tools etc.

**Comment by mutability** [comment]
Not sure about the battery special case but the others can be handled by an
aggregated value rather than needing the items?

**Comment by Coolthulhu** [comment]
Yes, but then we'd need an extra structure for every combination of traits: all items and non-pseudo items, tools that we need to count charges for and tools as components themselves and combinations of those.

At the moment it wouldn't be that much, but I'm planning to extend the crafting system to pass on flags like "rotten" (for permafood) and "contains human flesh". Those will need a warning when crafting.
It would be easier to do it with all the items on hand rather than just total counts.

**Comment by mutability** [comment]
You would need a cache entry for each type of requirement that can be specified, yes. But you need that logic _somewhere_. It would be a recasting of the logic currently in amount_of / charges_of to populate a cache rather than pick out a single item type.
