### ISSUE TITLE
Cannot remove ups mods

### ISSUE THREAD

**Issue by jim-huynh** [CleverRaven/Cataclysm-DDA#18820]
Version: 0.C-19202-gaf795c4

I cannot remove a ups mod from any tool (trying to clean up my control laptop++++), using a screwdriver.  The console says "you can't unload a rechargeable control laptop++++"

**Comment by illi-kun** [comment]
Working fine for me. @jim-huynh please let me know if this still an issue for you, and I'll re-open the report.

**Comment by illi-kun** [comment]
It happens with tools with _charged_ UPS mod because it's not possible to drop "batteries" (i.e. charges).

BTW, another issue is control laptop already contains integrated ups (which can be charged by a proper vehicle module), so attaching of UPS module is kind of useless.

**Comment by jim-huynh** [comment]
I had to add a UPS mod to it because it wouldn't recharge with the bionic UPS - only the vehicle UPS recharging system.  This was how it seems to have worked, at least at the time.

**Comment by illi-kun** [comment]
It's possible to remove UPS when it empty but not when it charged.

**Comment by ZhilkinSerg** [comment]
UPS conversion mod is permanent and should not be removed.
