### ISSUE TITLE
Disassembly times are unpredictable and unexpected

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#18830]
When disassembling items, the disassembly times are not intuitive (e.g. some things take 30 seconds; some things take an hour; there is little rhyme or reason why)

Two things to fix:
- Long disassembly times should be immediately visible at the point of disassembly so you don't commit to an hour-long disassembly unexpectedly;
- The disassembly times should probably be reviewed for sanity

PR #18826 tried to address the first item but there was plenty of pushback on the particular approach I took, so I will leave this for someone else to fix.

**Comment by Oskar636** [comment]
This may sound strange, but could you post some examples where disassembly is not intuitive? The only hour one I know is the rag, which seems reasonable to me because it'd seem tedious and long work to rip apart a rag into tiny thread.

**Comment by Coolthulhu** [comment]
Currently it seems to be like this:
* If it's crafted, it takes long time
* If it's uncraftable, it takes short time
* Except if it's a dead robot, then it takes very long time

Not perfect, but I don't see an obvious improvement here. Maybe except the robots.

**Comment by mutability** [comment]
I went through the pile of junk I had on hand and here's the disassembly times, in order (E&OE)

 * books (0.2 - 1.5 mins)
 * cell phone, desk fan, tablet PC (0.5 min)
 * lawnmower, lightstrip (1.0)
 * PDA (1.2)
 * copper tubing (1.2)
 * spring (1.5)
 * spike (3)
 * amplifier (4)
 * long string (5)
 * copper pot (7.5)
 * processor board (10)
 * flashlight, heavy flashlight (10)
 * chunk of steel (15)
 * small electric motor (20)
 * cordless drill (20)
 * circular saw (20)
 * electric motor (30)
 * bucket (30)
 * handheld game (60)
 * TV (60)
 * lump of steel (60)
 * rag (60)
 * laptop (60)
 * charcoal smoker (70)
 * concrete mixer (150)

So you can disassemble 50 PDAs in the time it takes to do one handheld game (similar complexity), a concrete mixer (big but simple) takes 2.5x as long as a laptop (small but complex), a lawnmower (machinery that needs tools to disassemble) is 30x faster than a bucket (dumb chunk of metal) to take apart, copper pots are 6x slower than copper tubing to turn into scrap, etc.
