### ISSUE TITLE
Repairing a max-damaged vehicle storage part dumps the contents on the ground

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#18834]
Ran into something on my motorbike, damaged a floor trunk full of stuff to max damage (grey).
It didn't dump the items at that point and the trunk showed a non-zero volume used, though the items were inaccessible.

Returned to base, repaired the trunk, and the contents of the trunk got dumped onto the surrounding few tiles.

Either that shouldn't happen at all, or the dump-on-the-ground behaviour should have happened when the damage was applied.

**Comment by mugling** [comment]
Probably needs handling in `vehicle::damage_direct`
