### ISSUE TITLE
Fluids from wooden keg construction are not spent in recepies

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#18838]
while making batteries from vinegar stored in wooden keg construction i noted it is not spent when making said batteries.i think its same for vine stored in keg which i used for denatured alcohol.

**Comment by jeremyshannon** [comment]
Can confirm. I have a keg full of water which will let me start crafting clean water, but if I try to do so, it spends the time and gives me nothing. The crafting silently fails when it comes time to get the water from the keg.

**Comment by AMurkin** [comment]
Would this be fixed?

**Comment by jeremyshannon** [comment]
Still fails silently, as of yesterday's code.
  Wish up a keg, a container of water, and a mess kit. Put the water in the keg, attempt to make clean water. Result: crafting starts, time passes, and then nothing happens.

**Comment by kevingranade** [comment]
works in latest experimental.

**Comment by baraba3** [comment]
I can confirm on my side at least that problem is happening again.
