### ISSUE TITLE
Getting an ammo error for 654 round upon game

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#18844]

**Comment by BorkBorkGoesTheCode** [comment]
Sorry,

**Comment by Nhatorama** [comment]
I'm also getting the same bug.
The only gun mod I believe I'm using is Icecoon's Weapons Pack.

<a href='https://postimg.org/image/gm64t92fx/' target='_blank'><img src='https://s6.postimg.org/j3hw0imch/item_id_handloaded_654_is_unknown.jpg' border='0' alt='item id handloaded_654 is unknown'/><br /><a target='_blank' href='https://postimage.org/'>images hosting</a><br /><br />
