### ISSUE TITLE
Can't reload mounted flamethrower in 5720

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#18843]
In 5717 could reload from a jerrycan but in 5720 it would indicate I'm out of ammo. Restored 5717, and was able to load fuel in flamethrower.

**Comment by hmstanley** [comment]
did you guys check this? it's really bad.. you cannot reload the mounted flamethrower on a vehicle.. it indicates you are out of Ammo, when you have plenty in hand, gasoline that is.

**Comment by Coolthulhu** [comment]
Last time I tested this, they didn't need explicit reloads and switched to new ammo on its own.

Could be caused by flamethrower wanting one ammo but not getting it, yet not allowing ammo change because ammo is needed to enter firing mode.
Pinging @mugling for extra insight.

**Comment by hmstanley** [comment]
Thanks for responding.  Before 5718, you had to "E" to the flamethrower and it would indicate Load/Unload "ammo" in this case, gasoline.  But after 5718, when you went to load the gas, and I tested it with NO gas, and only a jerrycans next to the flamethrower, thinking it might load automagically, it didn't.  And when you went to "load" ammo (fuel) it would indicate you are "out of ammo", this wasn't the behavior pre-5718.

**Comment by Coolthulhu** [comment]
Pretty sure it should consume the fuel in vehicle tanks.

What mods are you playing with? It may be something related to the vehicle additions mod.

**Comment by hmstanley** [comment]
Tanks and Vehicles addition mod, with the Infantry Fighting Vehicle.

**Comment by hmstanley** [comment]
I actually tried putting it into a tank, and that didn't work either.

**Comment by Coolthulhu** [comment]
OK, now I see it:
The most recent turret change has no support for turrets that have no "USE_TANKS" flag, but doesn't seem to enforce turrets having said flag.

This would make it both a mod issue (lacking flag) and vehicle issue (lack of check if the turret can actually fire).

**Comment by hmstanley** [comment]
I guess my other question related to this is the M60 and other belt fed SMG/MMG's not being mountable on the Infantry Fighting Vehicle?  Very strange.  It will allow you to mount a standard assault rifle, but not the standard turrets high caliber machine guns, with the exception of the M2.? is this connected to the Turret issue as well?

and, will the above be fixed in the mod? or do I need to NOT run this mod and just deal with standard in game vehicles that I find/create/design? etc?

**Comment by Coolthulhu** [comment]
The mod is supposed to be supported, meaning we will want to update it.
I just forgot to test it when testing the last turret update.

**Comment by BorkBorkGoesTheCode** [comment]
This issue affects handheld flamethrowers as well.
