### ISSUE TITLE
Mod description for Icecoon's Weapons Pack is not descriptive enough

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#18851]
It contains fictional guns and a fictional ammo type. It only contains 9 weapons. Maybe we could merge it with the other fictional weapons pack? 

Edit: The current description reads "For those gun nuts."

**Comment by BorkBorkGoesTheCode** [comment]
Indeed. I will be fixing this.

**Comment by Cyrano7** [comment]
via https://github.com/CleverRaven/Cataclysm-DDA/pull/18852
