### ISSUE TITLE
Inconsistent behavior for PageUp/PageDown key when using the Advanced Inventory Management

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#18878]
When the list on either column spans over more than one page, the PageUp/PageDown keys behave as expected. 

When the list is <= 1 page, the PageUp/PageDown expected behavior is inverted (PageUp highlights an item towards the bottom and PageDown highlights an item towards the top of the list).

**Comment by jaked122** [comment]
@Nhatorama That's from the fact that it wraps around.

 I think it's an okay behavior, but perhaps if you aren't already on the top or the bottom, it should move to the top or the bottom.

**Comment by Night-Pryanik** [comment]
I think that's okay too.
