### ISSUE TITLE
Add search to Pickup

### ISSUE THREAD

**Issue by jaked122** [CleverRaven/Cataclysm-DDA#18875]
Someone on reddit suggested that it might be nice to have some search function for the pickup screen.

I don't know if it makes sense to do it, as I _really_ don't feel like making another search implementation, but more importantly, this is getting onto a _lot_ of code copying. 

I think that it would be fairly simple, if not efficient, to take the advanced inventory's search function and call it from the Pickup::pickup function, since it doesn't need any additional functionality, this seems like the easiest way to go about it.

Does this sound unreasonable to anyone?

**Comment by Coolthulhu** [comment]
> I don't know if it makes sense to do it, as I really don't feel like making another search implementation, but more importantly, this is getting onto a lot of code copying. 

We need a unified search interface.
Something like `item_search.h/.cpp` that exposes `item_filter_from_string` function returning a `std::function<bool(const item &)>`.

**Comment by jaked122** [comment]
Okay. I'd be willing to give it a shot.

That actually sounds fairly easy. I guess that this going to be my first experience where changing the makefile is the proper way to fix something.

**Comment by jaked122** [comment]
@Coolthulhu It looks like there are no places in the code where I can use an unwrapped `bool(const item&)`, it's all either pointers or mapstacks.

Should I just write a little lambda dereference for the pointers, or is that a bad idea?

**Comment by Coolthulhu** [comment]
Not sure what you mean by that last part.

`Pickup::pick_up` uses mapstack only to populate the list of items. It shouldn't be that hard to filter out the extra ones later. The only problem is making sure that indices match.

**Comment by jaked122** [comment]
@Coolthulhu, whoops, well, now I've replaced the `game::list_items` method with this, which doesn't have a list of items at any point. :P

**Comment by cainiaowu** [comment]
Hi, can you test if unicode is supported? Otherwize it would be PITA for CJK user to use.

**Comment by Coolthulhu** [comment]
Now that I look at it, why just not reuse `list_items_match`?

**Comment by jaked122** [comment]
@Coolthulhu That's what I meant at first. :P
