### ISSUE TITLE
Compatible ammo for held gun is no longer green on inventory screens.

### ISSUE THREAD

**Issue by PlasmaChroma** [CleverRaven/Cataclysm-DDA#18872]
Ammo that is compatible with the current gun is no longer highlighted green in my inventory.  Is this intentional or fallout from ammo changes?  I'm much more in favor of the "before" style as it simplifies my life a lot.  The magazine remains green here at least.

Note that the situation is no better with an integrated clip, the M1014 shotgun is not highlighting 00 shot for me either.

Before:

![before](https://cloud.githubusercontent.com/assets/7933452/19456438/69298b58-948f-11e6-8ac6-a0d0d588ab94.png)

Now:

![after](https://cloud.githubusercontent.com/assets/7933452/19456451/78afd51e-948f-11e6-986e-dce63c2345c2.png)

Windows - 0.C-19234-g3b3d6f5

**Comment by Coolthulhu** [comment]
It seems that loaded guns make things not count as compatible.
