### ISSUE TITLE
Cans left unopened using advanced inventory movement

### ISSUE THREAD

**Issue by Sehn-Knight** [CleverRaven/Cataclysm-DDA#18873]
Moving liquids from a sealed aluminum can to another container using the advanced inventory leaves the can unopened and unusable in crafting. 

Specifically, I was moving soft drinks into gallon jugs with the advanced inventory's [C] function.

Build: 0.C-19230-g0caefe9 (tiles)
Windows10

**Comment by jaked122** [comment]
I've reproduced this bug.
