### ISSUE TITLE
Integrated bipod mod on HMG's (m60, M240, M249) prevents mounting of weapon on vehicle turret

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#18886]
Any weapon with an integrated mod, in this case, for the above, a bipod, will prevent the weapon from being mounted on a turret.  it will show in your inventory as NOT there.  Since there is no way to remove the integrated mod, you are left with a weapon that cannot be mounted on a vehicle.  I believe this is the cause of some of the turret bugs as well, since when you load your environment and it throws a turret error, this may be the cause of such an error.  But, any weapon with a mod, integrated or otherwise, will not be mountable on any vehicle.

**Comment by illi-kun** [comment]
Why do you duplicate your own issue?

**Comment by hmstanley** [comment]
Sorry.. I realized this after I wrote it.. my bad.

**Comment by hmstanley** [comment]
Is this related to the blazemod?  and if so, would this be fixed such that bipods on weapons can be mounted on turrets?  I think this also might be connected to that nagging turret error that appears when you cataclysm loads a new world space with a vehicle with a weapon that is, I think, mounted in a turret with a bipod? or something that prevents it being valid?

**Comment by DangerNoodle** [comment]
I was going to find the issue you were reporting in https://github.com/CleverRaven/Cataclysm-DDA/issues/17931 and tell you to discuss it there, due to being unrelated to

I am disappointed that you already reported this prior to doing so. Linking to this issue when asking if the two were related would have clarified your question.

**Comment by mugling** [comment]
Issue is in `item::allow_crafting_component()`
