### ISSUE TITLE
Atlatl suggestion

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#18887]
Current stats (using StatsThroughSkills Mod):
Throwing: 15
Strength: 12
Stone javelin range without atlatl: 16
Stone javelin range with atlatl: 28

I've been using the throwing skill quite a lot and have gone from 0 Throwing to 15 Throwing skill. As far as I can tell, the downsides of using an atlatl far outweigh the benefits it provides. Although using an atlatl increases the range of javelins from 16 to 28 (for a stone javelin) it also drastically reduces the accuracy of your throws which makes the extended range pointless.

Currently when using an atlatl, instead of using the throwing system, "t", the firing system, "f" is used. I think using the atlatl should use the throwing system, "t".

In my opinion using an atlatl should provide the following benefits/downsides:
+1 range for every 1-2 points in throwing.
+1 damage for every 1-2 points in throwing.
+1 Penetration for every 5-7 points in throwing or strength.
+0-5% accuracy for every 4 points in throwing (not sure how accuracy is calculated).
Using an atlatl adds 10-20 moves per attack (not sure if the value shown in the stone javelin description is used for both melee and throwing) for throwing a javelin. This may be slightly compensated by the javelin reaching its target sooner, since it is traveling at a higher speed than if it was thrown without an atlatl.

Just as you get knockdown/thrown across the room by brute zombies, javelins could also get a knockdown chance, which could work alongside the embed mechanic.
I would like to see more javelin tiers i.e.: steel javelin, tungsten javelin, diamond javelin (maybe this is too sci-fi), exploding javelin, etc.

Getting ready to use atlatl at max throwing range for non-atlatl
<a href='https://postimg.org/image/ivupndsbh/' target='_blank'><img src='https://s6.postimg.org/64gjgvijl/Using_atlatl_at_max_throwing_range_for_non_atlat.jpg' border='0' alt="Using atlatl at max throwing range for non-atlat"/></a><br/><br/>

Missed cat at 16 range while using atlatl at max steadiness
<a href='https://postimg.org/image/3vxrlsm1p/' target='_blank'><img src='https://s6.postimg.org/ostzqgk2p/Missed_cat_while_using_atlatl_at_max_confidence.jpg' border='0' alt="Missed cat while using atlatl at max confidence "/></a><br/><br/>

Hit cat at 16 range without using an atlatl
<a href='https://postimg.org/image/c05vqj8gt/' target='_blank'><img src='https://s6.postimg.org/3untsdk81/Hit_cat_at_16_range_without_using_an_atlatl.jpg' border='0' alt="Hit cat at 16 range without using an atlatl"/></a><br/><br/>

Chased after cat and struck him again with a javelin at 16 range
<a href='https://postimg.org/image/nnzxl2xlp/' target='_blank'><img src='https://s6.postimg.org/gxjgbnag1/Chased_after_cat_and_struck_him_with_a_javelin_a.jpg' border='0' alt="Chased after cat and struck him with a javelin a"/></a><br/><br/>

Stone javelin description
<a href='https://postimg.org/image/ab1dw7i59/' target='_blank'><img src='https://s6.postimg.org/wa7sjeyzl/Stone_javelin_description.jpg' border='0' alt="Stone javelin description"/></a><br/><br/>

**Comment by DangerNoodle** [comment]
Another alternative would be for dispersion to be altered to be in line with what throwing tends to yield.

**Comment by Oskar636** [comment]
It's way better to use the sling for your ranged damage, pebbles FTW! So yeah I think this needs to be rebalanced.

**Comment by Leland** [comment]
Closing in favor of #20414

**Comment by Lady-Luck** [comment]
@Leland In favor of what? You just linked an issue, not a PR...

**Comment by DangerNoodle** [comment]
I suspect that they meant that the issue being linked to supersedes this own, in that throwing by hand is regarded as superior to throwing by ranged weapon, and that throwing by hand can be unbalanced overall.
