### ISSUE TITLE
c:component name filter in crafting UI misses recipes requiring >1 of the item

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#18888]
Searching for "c:chunk of meat" finds some recipes that require it (e.g. "cooked meat") but does not find others e.g. "dehydrated meat".

Searching for "c:2 chunks of meat" finds dehydrated meat but not cooked meat.

This is because it's comparing the search string to the results of component::to_string(), which returns a formatted description of one component of a recipe _including the count of items required_

**Comment by jaked122** [comment]
Geez, that was a tough thing to write. I'll look into fixing it for you.

I guess that I should have compared it to the item's nname.
