### ISSUE TITLE
Crafting UI throws an invalid ammo error when selecting flamethrowers

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#18891]
When moving onto the spraycan flamethrower or simple flamethrower entry in the crafting UI, it reports a debug error: "Tried to set invalid ammo of gasoline for spraycan flamethrower" from item::ammo_set()

![flamethrower-crafting-error](https://cloud.githubusercontent.com/assets/3055062/19496173/44541c04-957e-11e6-9752-1a9a183f36e2.png)

**Comment by BorkBorkGoesTheCode** [comment]
A similar bug occurred when moving the selector onto any flamethrower entry in the debug menu. 0.C 19221

**Comment by PlasmaChroma** [comment]
Something has changed with flamethrower ammo types in: 6c9ef3b88d8f7098fd0275db107e4fb22b1d4cf8

I'm thinking the change in `"abstract": "flamethrower_base"`

`"ammo": "gasoline"` -> `"ammo": "flammable"`

Probably related to this and other issues with creating / using / reloading flamethrower based weaponry.

**Comment by BorkBorkGoesTheCode** [comment]
That was causing it. Ammo foo cannot be used as the default ammo in multiple ammo types. I think.

**Comment by BorkBorkGoesTheCode** [comment]
Okay. The error is gone, but I cannot reload a RM451 flamethrower from a jerrycan or jerrypack.

**Comment by mutability** [comment]
Stacktrace:

```
#0  realDebugmsg (filename=filename@entry=0x110533e "src/item.cpp", line=line@entry=0x1105914 "279", 
    funcname=funcname@entry=0x1107720 <item::ammo_set(std::string const&, long)::__PRETTY_FUNCTION__> "item& item::ammo_set(const itype_id&, long int)", 
    mes=mes@entry=0x1103b08 "Tried to set invalid ammo of %s for %s") at src/debug.cpp:51
#1  0x000000000084ba91 in item::ammo_set (this=this@entry=0x7fffffff8eb0, ammo="gasoline", qty=1600, qty@entry=-1) at src/item.cpp:279
#2  0x000000000085a3ba in item::info (this=this@entry=0x7fffffff9ee0, showtext=showtext@entry=true, info=std::__debug::vector of length 10, capacity 32 = {...}) at src/item.cpp:938
#3  0x0000000000602f50 in select_crafting_recipe (batch_size=batch_size@entry=@0x7fffffffa9bc: 0) at src/crafting_gui.cpp:473
#4  0x00000000005daa4f in player::craft (this=0x1685b850) at src/crafting.cpp:89
#5  0x0000000000763f39 in game::handle_action (this=this@entry=0x13142e10) at src/game.cpp:3078
#6  0x00000000007676ec in game::do_turn (this=0x13142e10) at src/game.cpp:1468
#7  0x00000000009858ad in main (argc=0, argv=0x7fffffffdbc0) at src/main.cpp:468
```

**Comment by codemime** [comment]
I cant reproduce the error. @mutability Did you fetch the new master before trying? According to @BorkBorkGoesTheCode it was gone before.

**Comment by mutability** [comment]
I will retry, but note the date of the original report

**Comment by mutability** [comment]
norepro on current master
