### ISSUE TITLE
Construction Menu Crashes with Right Arrow Key Press after previous construction

### ISSUE THREAD

**Issue by indigorain** [CleverRaven/Cataclysm-DDA#18890]
0.C-19238-g7dd7a8a compiled using git clone and pull on Ubuntu 16.04

When opening the construction menu and pressing the right arrow key, the game crashes. I can use the number pad to scroll through the different options, but the arrow key crashes my game.

The error message seems to read,

>/usr/include/c++/5/debug/vector:409:error: attempt to subscript container with out-of-bounds index 38, but container only holds 38 elements.

>Objects involved in the operation: sequence "this" @ 0x0x7ffd9866e140 {type = NSt7_debug6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS6_EEE;}

>Aborted (core dumped)

Just to note, I transcribed that from my screen, so there might be some typos and parts of the error might be missing, cause my terminal is all wonky due to the crash.

So far, it crashes when I press the right arrow key after having made a construction.
It crashed when I tried to use the search function to find crates typed: "cra"

**Comment by Maeyanie** [comment]
I got this crash too, and traced it to construction.cpp line 336.
For some reason, 'select' was ending up 1 off the end of the vector, so 'std::string current_desc = constructs[select];' caused a crash.

**Comment by jaked122** [comment]
@Maeyanie @indigorain Thanks for reporting this.

Just out of curiosity, did this happen in the tiles version or the curses version? I can't replicate it on my up to date tiles build.

**Comment by indigorain** [comment]
It was on curses

**Comment by illi-kun** [comment]
@jaked122 Successfully reproduced it in the latest exp, curses.
Steps to reproduce:
- open construction menu
- toggle unavailable constructions by ';'
- choose any _empty_ tab
- press up,
- press enter
- crash!

**Comment by jaked122** [comment]
@illi-kun Thanks for telling me that it had to be an empty tab.

I'll just add a thing to skip it if the construction list is empty. That's still very strange, as there isn't any curses specific code that I can see that leads up to that.

**Comment by jaked122** [comment]
That should do it.

**Comment by illi-kun** [comment]
> Edit: Nope It's not the printing part that does that part @illi-kun.
I think it's the build. I just need to prevent it from trying to place a building if there's nothing selected.

Of course it's not printing part, it's attempt to access wrong element in vector ```constructions```.

**Comment by jaked122** [comment]
The line that @Maeyanie mentioned was getting the name of the construction.

I added a check to make sure that the selection was reset to zero in the case of there not being a suitable index.

I also made it impossible to construct a building with an empty name or if the selection is again out of bounds.

**Comment by Maeyanie** [comment]
I was using a tiles build, so it wasn't curses-specific. But looks like you already got it figured out before I read the question anyhow. :)

**Comment by Maeyanie** [comment]
There's a typo in your fix-patch:
`if( constructions.empty() || select <= (int) constructions.size() ){`
Should be:
`if( constructions.empty() || select >= (int) constructions.size() ){`

**Comment by jaked122** [comment]
@Maeyanie Thanks, without you I would have actually made everyone unable to construct anything.
