### ISSUE TITLE
Battery and reactor CBMs do not work, no `ammo_type` for battery and plutonium

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18908]
Pinging @mugling who designed the ammo system.

Are those CBMs supposed to check `ammo_type`? They do it at the moment, but `ammo_type` returns `NULL_ID` for ammo.

**Comment by Rivet-the-Zombie** [comment]
Could this also be related to https://github.com/CleverRaven/Cataclysm-DDA/issues/18891?

**Comment by BorkBorkGoesTheCode** [comment]
In that case gasoline was specified as the default ammo for gasoline and flammable, which caused the error. More problems may exist.

**Comment by Coolthulhu** [comment]
"Bumping" this one.

Is ammo supposed to have `ammo_type` or not?

**Comment by mugling** [comment]
I'll claim this issue

**Comment by mugling** [comment]
> Is ammo supposed to have ammo_type or not?

No

**Comment by eriksr** [comment]
Bumping, I'm two levels down in a Laboratory, it's REALLY cold, and I can no longer see anything and my temperature is dropping rapidly...and I can't eat my batteries.

**Comment by mugling** [comment]
> Bumping

Isn't this issue resolved in `master`?
