### ISSUE TITLE
[Possible bug?] Construction option does not reset on menu close

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#18909]
Problem: If I open up the construction menu, scroll down and close it - when I reopen the menu, the chosen option is the one that was active when the menu was closed. 

I am not sure if this is intentional, but if it is, I don't think it's a good decision to leave it in since it breaks the standard which applies to basically every other menu in the game, and also unnecessary since a search function was implemented.

**Comment by jaked122** [comment]
They asked me for it when I wrote the search function :).

I think the idea is that it makes it easy to resume after you look for the requirements to build something then go find the components then go back to wherever and build it.

I'm really happy to hear that you like the search function though.

**Comment by illi-kun** [comment]
Feature, not Bug.
