### ISSUE TITLE
Distribution of ranged shot dispersions seems a bit weird

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#18905]
player::fire_gun() sets

```
  double dispersion = rng_normal( get_weapon_dispersion( gun ) ) + rng_normal( recoil_total() );
```

which is a little odd: this results in a (truncated) normal distribution with a mean of `get_weapon_dispersion(...) / 2 + recoil_total() / 2` and a standard deviation of `get_weapon_dispersion(...) / 4 + recoil_total() / 4`. If you plotted the resulting values, you will get more shots aimed at the (non-zero) mean angle than at a zero angle.

Shouldn't we be building a distribution that's centered on zero?
e.g.

```
  double dispersion_sigma = get_weapon_dispersion( gun ) / 2 + recoil_total() / 2;
  double signed_dispersion = normal_roll( 0.0, dispersion_sigma );
```

**Comment by mutability** [comment]
@mugling introduced this in c308805687b1322f9efd43fd52d6b4059ad381e5; any insight into how it's meant to behave?

**Comment by mutability** [comment]
I did a bit of analysis of the current code versus a zero-centered distribution, not sure if there's anything convincing either way to take away from this. The zero-centered distribution has sigma = (calculated total dispersion) / 1.3, picked by eye to give a miss chance curve that's somewhat similar.

![dispersion_600](https://cloud.githubusercontent.com/assets/3055062/19610511/bda3424e-97d4-11e6-94b3-4260b00f3c37.png)

The zero-centered distribution gives less abrupt transitions with range (no more 100% guaranteed hit under range 5) and a fatter tail (guns don't become _entirely_ useless beyond a certain range, just mostly useless). Note that with the new scheme the relative hit chances at longer ranges approach the base accuracy fractions i.e. if you hit, you get 10% headshots, 10% crits, 30% good hits, etc)

I think it makes more sense simulation-wise but in terms of balance, dunno.

**Comment by Coolthulhu** [comment]
Would be perfect if the `rng_normal` was moved further into the function.

That is, instead of doing something like:
```
int dispersion = ...
int rolled_dispersion = rng_normal( ... );
missed_by = ...
```
It was
```
int dispersion = ...
missed_by = rng_normal( ... )
```

That would significantly decrease the number of wild misses and could represent misses more sensibly. Would probably require some adjustments to numbers.

Decreasing point-blank accuracy in favor of long-ranged one is good. It cuts some of that boring hit-and-run thing.

**Comment by mutability** [comment]
I originally assumed that the code was intending to do what you first quoted. But what you have as "rolled_dispersion" isn't really a dispersion angle at all; it is something more like an abstract probability tied to the chances for headshots etc. rng_normal (x) gives you a distribution centered on x/2 that is limited to [0,x], it is a bit counterintuitive if you're expecting a more standard normal distribution. If you go back to the pre-rng_normal code that code would add up a bunch of uniformly-distributed random variables based on various stats to get a total that was used to decide how good the hit was. rng_normal isn't a bad way to get a similar result (central limit theorem etc). But in both cases the result is _not really an error angle_ because it's not distributed around zero.

That makes it really confusing when the projectile_attack code then goes on to treat "rolled_dispersion" like an angle for the purposes of misses..

What I'm suggesting is to make rolled_dispersion really be an angle. Given a gun+shooter dispersion of, say, X, generate a rolled dispersion - an _angle_ - for this particular shot that is normally distributed around _zero_ (not X/2 as currently done) with a standard deviation based on X. That's modelling the deflection between where you aimed and where the shot actually went. Smaller values of X give a tighter cone, the deflections tend to be closer to zero. Then you can do hit chance and deciding where missed shots go by using iso_tangent on the deflection. Wild misses are still occasionally possible, just very unlikely.

I think? you're in agreement with that but terminology is tricky :)

**Comment by Coolthulhu** [comment]
Pretty sure I get it.

Centering it at 0 sounds like a big buff, though I don't see it at the plots. Is there some hidden constant (other than the `1.3`), something I'm missing, or it it just how the math works here?
I'd expect miss chances to only go up in the cases where `rng_normal` clamps the distribution to `[0, 2*stddev]`.

What do you do with negative values? Just `abs`?

Overall it looks good to me.
Though one thing may need to be added with it: some correction of accuracy for monsters with heavy launcher weaponry. Just minor number tweaks to avoid random deaths, nothing huge.

**Comment by mutability** [comment]
My gut feeling was that it'd be a buff centering it on zero, which is why I simulated it and it turns out that just increasing the standard deviation seems to compensate enough. We could tweak the accuracy bands too, but they are used in other places which makes that more complex.

Right now there are about 2.5% "extra" headshots and not-so-bad-misses due to rng_normal clamping, I suspect it's mostly headshots as the right hand side of the distribution is going to be outright misses except at close range, so the clamping just turns a particularly bad miss into a not so bad miss.

iso_tangent only returns the positive root and cos is symmetric around zero so no need for abs. If you keep it signed, you can later use sgn(rolled_dispersion) to notice if the miss should be to the left or right.

Probably best if I put together a PR to hash out the details.

**Comment by mutability** [comment]
gist of scripts to generate the graphs here: https://gist.github.com/mutability/625b8edb72aceb6abfa161e0acc1c681
