### ISSUE TITLE
Unable to create new vehicle construction

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#18900]
Build: 5731

//////////////////////////////////////////////////////////////////////////
Error Debug message: "Attempted a recipte with no available components!"

Function: "comp_selection<item_comp> player::select_item_component(const std::vector<item_comp>&, int, inventory&, bool)"

File: "src/crafting.cpp"

Line: "825"
//////////////////////////////////////////////////////////////////////////

When does this issue occur? Whenever I try and create a new vehicle with either light or normal wooden frames. (Only ones I've tested so far)

**Comment by illi-kun** [comment]
Try it again with two identical frames in inventory.

**Comment by harald921** [comment]
That worked, but used up both frames. Miscalulated vector iteration?

**Comment by illi-kun** [comment]
I dunno, but that's duplicate of  #18372.
