### ISSUE TITLE
Survivor starts without shoes/boots if wool allergy is chosen

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#18916]
We should probably provide a non-wool alternative to Winter Boots for players who choose wool allergy on survivor characters.

**Comment by Nernums** [comment]
fur boots exist go ahead

**Comment by Coolthulhu** [comment]
Fur boots are supposed to be a step above winter ones.

**Comment by Nernums** [comment]
they're actually worse in practice usually because they tend to set your feet on fire due to being too efficient, but using just regular hiking boots would be fine too.

**Comment by DangerNoodle** [comment]
Hiking boots might be a more logical choice. Or regular boots.

One thing I have noticed is that in default spring conditions, a standard survivor indoors will be both hot and cold, and the "Comfortable (Rising/Falling)" status can only indicate one of those conditions.

**Comment by pisskop** [comment]
im not sure this needs fixing at all since it's part of the allergy

**Comment by DangerNoodle** [comment]
> im not sure this needs fixing at all since it's part of the allergy

You are allergic to wool, so you go barefoot in winter? That indicates this does indeed need something changed.

**Comment by DangerNoodle** [comment]
I would reason that even from a gameplay perspective it is a negative feature, and I would place higher priority on that than I would on how realistic it is.

Providing a viable alternative clothing item does not significantly detract from the intended detriment the allergy causes, so long as the replacement item is in some way inferior. Most like in terms of warmth and possibly protection, the former moreso given the main gameplay niche wool items have is warmth.

**Comment by Nernums** [comment]
pisskop are you fucking serious
being physically unable to wear something due to discomfort, vs morale penalties for being itchy as all hell
if you started wearing wool boots and had a morale penalty from the itchiness that would solve all the issues.

the real issue is how the allergy functions in gameplay terms
