### ISSUE TITLE
No longer possible to build things

### ISSUE THREAD

**Issue by jaked122** [CleverRaven/Cataclysm-DDA#18915]
After that remarkably quickly implemented fix to the earlier crash, now, since I accidentally made a typo which happened to still compile, it is no longer possible to construct things.

I've already made a pull request [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/18914) for it, as it is a fairly serious issue.

**Comment by illi-kun** [comment]
Sorry, I have to test it carefully.
