### ISSUE TITLE
electric chainsaw breaks when using UPS

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#18917]
install a UPS mod into an electric chainsaw, charge it, then try and use it on a log

Also Chainsaws in general appear to have a weird implementation.  It should be much faster to cut down a tree and cut it into logs and then planks using a chainsaw vs a regular ax.

I expected the Activate menu of the chainsaw to let me cut down a tree or section the fallen trunk, but neither seems to be an option.

**Comment by illi-kun** [comment]
It works fine for me:
```You cut the log into planks.```

@Xpyder could you confirm this still an issue for you?

**Comment by illi-kun** [comment]
Please inform me if it's still an issue and I'll re-open the report.
