### ISSUE TITLE
ChestHole soundpack "idoors_rain.ogg" playing despite not indoors while raining

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#18910]
I am not sure whether or not this is an issue on the soundpack's side, or the code that handles the sound output - but as the title says..

Problem: It seems like the sound file for "indoors rain" (the sound of rain hitting a metal roof) plays when it is raining, despite the player being located neither in nor close to a building.

**Comment by Chezzo** [comment]
I don't think it is on my side. I was able to reproduce this by going outside while it is raining, and saving the game. 

On reload, the noise that will be playing will indeed be indoors_rain.ogg.

**Comment by harald921** [comment]
I have not looked in the code, but I assume there has been changes to the way sounds are called then?

Or are sounds depending on a log file, like Dwarf Fortress or is it more built into the game?

I really should start diving into the code more.

**Comment by Leland** [comment]
`indoor_rain` is [triggered here.](https://github.com/CleverRaven/Cataclysm-DDA/blob/e79ded4f8ef1205cd9da0e224f362094fec58276/src/sounds.cpp#L511-L516) Don't immediately see any issues.

**Comment by BevapDin** [comment]
@Leland The if condition that triggers "indoors_rain" does not check the `is_sheltered" variable. Maybe it should? (I'm not confident with the sound and SDL part of the code.)

**Comment by kevingranade** [comment]
Fixed by #28006
