### ISSUE TITLE
Cannot reload flamethrower using gasoline from jerrycan

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#18919]
When I wield any flamethrower and hit "r" to reload from a full jerrycan of gas, the flamethrower doesn't recognize gasoline as a flammable ammo.

**Comment by hmstanley** [comment]
Yea, I filed this one already. Same on a vehicle.

**Comment by BorkBorkGoesTheCode** [comment]
It looks like retrieving ammo from a container is an issue. I have created ammo using the new multi-ammo_type system and loaded it into a weapon, no problem.

**Comment by hmstanley** [comment]
What do you mean create it? You made some gasoline inside ? And loaded it?  Just curious how you got it to work.

**Comment by BorkBorkGoesTheCode** [comment]
>What do you mean create it? You made some gasoline inside ? And loaded it? Just curious how you got it to work. 

Apologies for miscommunication. I modded in a .357 magnum ammo that uses both the `38` and `357` ammo groups.

**Comment by BorkBorkGoesTheCode** [comment]
EUREKA! I found the problem: Blazemod has a duplicate gasoline entry without ammo compatibility.
