### ISSUE TITLE
Regressions in visible item filter

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18925]
http://smf.cataclysmdda.com/index.php?topic=13515

* Multiple exclusions (for example, `-pulped,-mangled`) don't work
* Double comma (`,,`) locks up the game

**Comment by jaked122** [comment]
@Coolthulhu I'll try to fix it if you like.

I feel sort of responsible for this, after all.

**Comment by Coolthulhu** [comment]
Would be great

**Comment by jaked122** [comment]
@Coolthulhu So I've gotten most of it working now. 

I believe that the reason that the categories weren't working properly was because they were described using the former search syntax, I believe that removing the curly brackets from the string should allow them to work again.
