### ISSUE TITLE
Error when using electrohack with UPS conversion mod

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#18930]
![mage](http://puu.sh/rR2Nb/e528227732.png)

**Comment by illi-kun** [comment]
```electrohack+ (UPS) (n)``` works for me. Could you confirm that this still an issue for you?

**Comment by illi-kun** [comment]
I guess it was fixed in #18948. Please let me know if it's a false statement.

**Comment by dreyskiy** [comment]
This exact issue is occuring in my game currently.  Latest experimental.
