### ISSUE TITLE
Power usage of the optical cloak is excessive

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#18932]
It depletes a full advanced ups in about 17 steps, not even enough to cross a street.

**Comment by Rivet-the-Zombie** [comment]
Yeah that's pretty excessive.

**Comment by Coolthulhu** [comment]
I assume it is supposed to be powered through bionic power, which due to being unlimited, is effectively infinite.

**Comment by Mecares** [comment]
Perhaps a low base cost with increased cost for each bionic the player has would be better? (like 50 per turn +1% per Bionic) It could be explained with sensible electronics that get disturbed by the electromagnetic emissions of the bionic?

**Comment by pisskop** [comment]
50 is higher than the cost of it now.

**Comment by Mecares** [comment]
It was not realy meant as an actually suggested value more to elaborate what i mean.

**Comment by Asmageddon** [comment]
I think @John-Candlebury is referring to the item, which is wearable, and has a pretty bad 50 encumbrance across all body parts, and would likely be reasonable to have much lower power consumption than the bionic equivalent - 20 or 25 maybe?

**Comment by Leland** [comment]
If you want to tinker with it, the charge usage is located here: 
https://github.com/CleverRaven/Cataclysm-DDA/blob/1faea901ef543bec7c0a116f8b076861067056c6/src/player.cpp#L6756-L6759

**Comment by ZhilkinSerg** [comment]
Addressed in 21807.
