### ISSUE TITLE
Catacharset.cpp conditional error messages

### ISSUE THREAD

**Issue by i2amroy** [CleverRaven/Cataclysm-DDA#1895]
Currently upon compiling (Cygwin) Catacharset.cpp produces these error messages:

In file included from catacharset.cpp:4:0:
wcwidth.c: In function ‘int mk_wcwidth(wchar_t)’:
wcwidth.c:202:15: warning: comparison is always false due to limited range of data type [-Wtype-limits]
wcwidth.c:202:33: warning: comparison is always true due to limited range of data type [-Wtype-limits]
wcwidth.c:203:15: warning: comparison is always false due to limited range of data type [-Wtype-limits]
wcwidth.c:203:33: warning: comparison is always true due to limited range of data type [-Wtype-limits]

**Comment by mugling** [comment]
> Also, does this still happen?

Presumably not?
