### ISSUE TITLE
make install problem, at least on linux

### ISSUE THREAD

**Issue by Blank99** [CleverRaven/Cataclysm-DDA#18964]
I was having some trouble compiling from source when using make install, it compiled just fine, the exec (the one inside the git folder) worked just fine, but calling at cataclysm? nope, nada, thing didn't run.

The issue is that when one uses make install, the program tries to install everything on root, putting the exec on /bin, and everything else on /share. And then it couldn't find it's own files or something.

The simple solution is to pass it PREFIX=<directory> parameter, something like /usr/local does the trick.

Still, the PREFIX option isn't amongst the suggested options on the comment at the start of the makefile, or the compiling readme, so that should be added. And adding a couple lines to the makefile so if PREFIX is undefined it defaults to something sane wouldn't be remiss either.

**Comment by Leland** [comment]
Closing as we have CI now.

**Comment by kevingranade** [comment]
I don't follow what this has to do with CI, make install is supported and the suggestions are valid.

**Comment by unhammer** [comment]
COMPILING.md should then mention that you need PREFIX both on `make` and `make install`, e.g.
```
$ make PREFIX=$HOME/blah/meh 
$ make PREFIX=$HOME/blah/meh install
```
