### ISSUE TITLE
Acid thrown from/by the player should splatter onto mons and npcs

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#18965]
The player can only place these things at monsters feet.  Hitting something with a vial of acid should get it all over them, causing pain and DpS.  This is not the case.

Since we are on the cusp of making firehoses spray acid over things, this should be happening?

**Comment by BorkBorkGoesTheCode** [comment]
Should monsters experience pain?

**Comment by pisskop** [comment]
No.  Not unless its a directly speed or movement point reducer.  Maybe morale.

**Comment by Leland** [comment]
Closing this due to lack of discussion – this has been stalled for about 7 months now. @pisskop if you'd prefer this kept open, let me know!
