### ISSUE TITLE
Crafting Recipe Filter "S:" used skill broken

### ISSUE THREAD

**Issue by nonymous** [CleverRaven/Cataclysm-DDA#18974]
Filtering by used skill provides no results in the recipe menu.

**Comment by MisterFox** [comment]
I never really knew the difference between s: and S:, but it looks like S: was removed with the recent fix. Does s: work fine?

**Comment by jaked122** [comment]
Yeah, being the one who wrote the new code for this after the old stuff broke, just try a lowercase `s`.

**Comment by Oskar636** [comment]
This can be closed since it's not really an issue.
