### ISSUE TITLE
Can't apply Rail Laser Sight to Pneumatic Assault Rifle

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#18975]
the pneumatic rifle has accessory slots, and I don't see any reason why this would be an unreasonable attachment, I suspect it's just a missing tag or some sort of type mismatch.

**Comment by Nernums** [comment]
the rail laser sight goes on the rails silly.

**Comment by Reclusive-reptile** [comment]
And the pneumatic assault rifle doesn't have a rail slot.

**Comment by Solusphere** [comment]
To be fair, a picatinny rail would be childs play to build for someone who can make a goddamn pneumatic assault rifle, but balance and all that.
