### ISSUE TITLE
Filthy clothes cause nausea instead of morale loss

### ISSUE THREAD

**Issue by MisterFox** [CleverRaven/Cataclysm-DDA#18985]
I hear that the problem with filthy clothes is that people that didn't care could just wear them and ignore the morale penalty. I think if wearing filthy clothes had a chance to cause nausea (the more clothes, the higher the chance), that might make it more reasonable as a mechanic.

**Comment by Solusphere** [comment]
Eh, if people are willing to ignore the morale penalty, and suffer the consequences to their skill growth, let them. It's honestly silly to do so seeing as soap is so abundant, unless there's no water tiles on the map.

If they want to be filthy hobos covered in gore, as opposed to wearing a top hat, monocle and tuxedo like a TRUE survivor, that's their prerogative. You don't need to buff the penalty to the point that ignoring it is impossible.

**Comment by pisskop** [comment]
Yea.  nausea is overwhelmingly negative. just make squeamish people nauseous

**Comment by Taberone** [comment]
What about making filthy clothes just making it easier for zombies to smell you?

**Comment by fr1gid** [comment]
Or would that make it harder for them to smell you, like in Walking Dead.

**Comment by Solusphere** [comment]
Ooh, I approve of fr1gid's idea. That could be very cool.

**Comment by BorkBorkGoesTheCode** [comment]
>Or would that make it harder for them to smell you, like in Walking Dead.
 That could add and interesting cost-benefit situation if you want to sneak about.

How would this interact with zombie pheromone?
