### ISSUE TITLE
Jars of meat have wrong charges

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#18987]
Sealed Jars of meat should have 2 charges, not 1

Edit: fixed numbers

**Comment by MisterFox** [comment]
I think something may have been mistyped here

**Comment by Xpyder** [comment]
lol, ty.
If you unload them they have only 1 charge
compare to cans of meat and jars of soup.

**Comment by illi-kun** [comment]
Such comparison isn't valid. It's better to compare it using nutrition or any other reasonable parameter.

**Comment by Xpyder** [comment]
@illi-kun Yes, the comparison is valid but I will offer a more detailed explanation if that's what you're asking for.

Cans of "Canned Meat" are 1 volume in size, take 1 chunk of meat to make, and produce 1 Canned Meat with a total volume of 1 matching the same volume output of other can recipes.

Jars of "Canned Meat" are 2 volume in size, take 2 chunks of meat to make, and produce 1 Canned Meat with a total volume of 1 differing from other jar recipes which produce 2 volume of output.

Given the doubling of input ingredients, double the storage volume of the containers, and the fact that jars usually output 2 volume of contents, it's clear this is an unintended bug left over from when jars were 1 unit in volume instead of 2.

I'd also be willing to bet that the jar magically drops in weight just by opening, as did the other jar recipes before I fixed them.  I just missed the canned meat and canned veggies in that PR (#16715)

I don't have time to make the fixes myself atm, so I posted here in case someone else gets to it before I do.

**Comment by illi-kun** [comment]
@Xpyder, thanks for expanded comment. It's also important to check balance about nutrision of received portion of meat, but let's keeping this for someone who decide to fix the issue.

**Comment by Xpyder** [comment]
@illi-kun While I agree that the nutrition for the "canned meat" item could probably use some adjustment, that's irrelevant to this issue.

Also to cut down on confusion, for the rest of this post I'll refer to the actual item "canned meat" as SPAM

Both Jar of SPAM and Can of SPAM produce the same SPAM product, but the jar costs twice the materials and produces the same quantity for SPAM as the can does, so this is clearly a bug.

**Comment by Dracace** [comment]
just tested, i think this is fixed now
