### ISSUE TITLE
Wastebread and Bone Meal should have high calcium content

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#18980]
Bone meal because it's made from bone.
Wastebread because it's made from 3 bone meal and 1 flour.

Does anyone see any issues with this?

**Comment by Nhatorama** [comment]
I do, that's why I use the Simplified Nutrition mod.
When I was playing without the mod, hypocalcemia was my most common ailment.

It would be nice if we could make our own calcium supplements/pills.
https://youtu.be/3NtEVEOL8Gw?t=55

**Comment by DangerNoodle** [comment]
Planning to implement calcium added to wastebread, but I am uncertain about adding it to bone meal.

**Comment by keyspace** [comment]
#19541 added calcium to wastebread - I think, however, it could have been better as in the commit above.

Want me to PR this?

**Comment by Cyrano7** [comment]
@keyspace Yes you should try to PR it.

**Comment by Leland** [comment]
Closing due to lack of recent discussion. Feel free to ping me here to reopen if there's interest in continued discussion/development.
