### ISSUE TITLE
Leaving NPCs on guard in vehicles causes them to dissapear

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#18989]
This is the second time this has happened. After leaving a pair of NPCs on guard in my vehicle, I have returned to find them missing, though the map still shows the @ symbol in the tile where I left them. Moving the vehicle results in this message:

![image](https://cloud.githubusercontent.com/assets/19789267/19758674/c29ee66e-9c5b-11e6-977d-de3713357a8d.png)
![image](https://cloud.githubusercontent.com/assets/19789267/19758682/ccf20b50-9c5b-11e6-98aa-1a94100652a3.png)

Presumably this refers to the two seats in which they were sitting.

The map looks like this:

![image](https://cloud.githubusercontent.com/assets/19789267/19758701/e6a83f7e-9c5b-11e6-9282-013d9755e825.png)

Offroad Vengeance is the name of my vehicle.

**Comment by LyleSY** [comment]
Any chance this still exists? I do this constantly on a recent build with one NPC and have seen no issues, using a modified RV. Maybe specific to this vehicle, or needs more than one NPC to duplicate?

**Comment by Leland** [comment]
Closing due to lack of reproducibility.
