### ISSUE TITLE
Crash when opening the inventory

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#18991]
Version: fa2c85a
Made with: make CCACHE=1
g++ --version: g++ (Debian 6.1.1-11) 6.1.1 20160802

To reproduce, simply open an inventory window somehow ( 'i', 'w', etc).

Assertion message:
![crash](https://cloud.githubusercontent.com/assets/16765166/19788099/888c045c-9c74-11e6-8bba-b4cfcac72909.png)

Backtrace:
![backtrace](https://cloud.githubusercontent.com/assets/16765166/19788108/9044caf8-9c74-11e6-8ca6-8e0e95ca6bf2.png)

**Comment by Coolthulhu** [comment]
Looks like the inventory rework thing must rely on some sort of undefined behavior then.

Does it reproduce with empty inventory?

**Comment by sethsimon** [comment]
>Does it reproduce with empty inventory?

No.

**Comment by mutability** [comment]
```
bool inventory_selector_preset::sort_compare( const item_location &lhs, const item_location &rhs ) const
{
    return lhs->tname( 1 ).compare( rhs->tname( 1 ) ) <= 0; // Simple alphabetic order
}
```
Should probably be `<` not `<=`

**Comment by sethsimon** [comment]
> Should probably be < not <=

Yup.

**Comment by codemime** [comment]
Sorry for the crash and thanks for the fix. I use an older g++ (4.9.2) which doesn't put the `assert` there and the bug sneaked in unnoticed.

**Comment by sethsimon** [comment]
> Sorry for the crash and thanks for the fix.

No harm done and no problem.
