### ISSUE TITLE
All science SD memory cards contain the zweihander recipe

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#19005]
State of the art zweihanders?

**Comment by Rivet-the-Zombie** [comment]
Sounds like maybe it's grabbing onto the last item in an alphabetical list and using it?

**Comment by Solusphere** [comment]
"Whelp, we've done it boys. We've finished science! What more do we need when we have goddamn GIANT SWORDS!?"
*Scientists all cheer*
