### ISSUE TITLE
Completely dismantling vehicles (pre-existing or self-made) causes CTD.

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#19003]
If I destroy the last part of a vehicle the game doesn't crash.

<a href='https://postimg.org/image/3t1zmrmhp/' target='_blank'><img src='https://s6.postimg.org/r79yyp4f5/Removing_the_last_frame_of_a_Hatchback_CTD.jpg' border='0' alt='Removing the last frame of a Hatchback CTD'/><br />

<a href='https://postimg.org/image/u3wzyza8t/' target='_blank'><img src='https://s6.postimg.org/72get8ald/Completely_dismantling_pre_existing_vehicles_cau.jpg' border='0' alt='Completely dismantling pre-existing vehicles cau'/><br />

**Comment by warriorsofcats** [comment]
I have same problem and it started in build 5768

**Comment by Foffy123** [comment]
Confirming this on Windows Tiles 5775
