### ISSUE TITLE
print_aim_bars assumes a uniform distribution of hit qualities

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#19018]
print_aim_bars assumes that the chance of different types of hits is directly related to their accuracy constants, e.g. if the chance of a grazing hit is 90%, then the chance of a headshot is 9%.

This is not true as the dispersion follows a normal distribution, not a uniform distribution.

**Comment by illi-kun** [comment]
Another issue about aim bar is here: #16980.
