### ISSUE TITLE
Turrets probably shouldn't be able to dodge

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#19026]
![turret-dodge](https://cloud.githubusercontent.com/assets/3055062/19833554/f4414fe4-9e3c-11e6-9cdf-49d2168406d4.png)

**Comment by Coolthulhu** [comment]
We could change it to "but misses".

**Comment by mutability** [comment]
It seems to be a deeper problem than just rewording the message:

![turrets-again](https://cloud.githubusercontent.com/assets/3055062/19834459/f89f48c8-9e57-11e6-9c55-f3dc8f9a0b37.png)

Stationary objects like turrets should be failing all their dodge rolls, shouldn't they?

**Comment by ZenZen2** [comment]
maybe remove the dodge and increase the hp

**Comment by Coolthulhu** [comment]
> Stationary objects like turrets should be failing all their dodge rolls, shouldn't they?

No, because you can still miss them due to their small size.

**Comment by mutability** [comment]
But the to-hit roll has already happened at this point and has decided that the attack is on target.
If it's a size thing, shouldn't that should happen as part of deciding if the attack is on target (in projectile_attack in this case), not based on a dodge roll which is also dependent on things like projectile speed?

**Comment by mutability** [comment]
e.g. does it make sense that given a gunshot and a bowshot fired with the same accuracy, the gunshot is more likely to hit a stationary target?

**Comment by Coolthulhu** [comment]
Currently dodge rolls are all using the same formula, which includes both size and skill.
Turning it off would be a big buff to throwing - one it doesn't need at the moment, as thrown rocks are headshotting pretty consistently at the moment.

Separating them would be a good thing, though.

**Comment by mutability** [comment]
OK, I might line this up for another PR after the current ranged saga is over with.

**Comment by Coolthulhu** [comment]
Should no longer happen now that being small no longer grants dodge.
