### ISSUE TITLE
vehicle_turret unit test failures

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#19024]
Using 9d41e9fd4a4c453b799faa43a60d469295cf8eff:

```
-------------------------------------------------------------------------------
vehicle_turret
  mounted flamethrower
-------------------------------------------------------------------------------
vehicle_turrets.cpp:46
...............................................................................

vehicle_turrets.cpp:62: FAILED:
  REQUIRE( tank )
with expansion:
  false

-------------------------------------------------------------------------------
vehicle_turret
  water cannon
-------------------------------------------------------------------------------
vehicle_turrets.cpp:46
...............................................................................

vehicle_turrets.cpp:62: FAILED:
  REQUIRE( tank )
with expansion:
  false
```

**Comment by mugling** [comment]
It isn't necessary to enumerate each individual unit test failure as an issue

**Comment by mutability** [comment]
Where should they go, then?

**Comment by mugling** [comment]
Nowhere - you can easily get a list of failing unit tests by running them. Work to fix the failing tests is however very much appreciated

**Comment by mutability** [comment]
If these are expected to fail, wouldn't it make sense to hide them by default (and/or tag as "known to be broken"?)

Currently, if you make a change and rerun the unit tests it's hard to pick out breakage due to the change vs. broken unit tests.

**Comment by mugling** [comment]
See #18461

**Comment by mutability** [comment]
Not sure what I'm meant to take away from that other than the vehicle_turret failures are new in the last month.

**Comment by mutability** [comment]
Test passes in c19e766d245dfcce28729f25d35cea4866f2cd80. I'll bisect to find where it started failing. As this is a recent failure can you reopen this?

**Comment by mugling** [comment]
Sure

**Comment by mutability** [comment]
git bisect says: c09188b9da486d1e0587a6865e3bd5c085546f39 is the first bad commit

This is your PR #18566

**Comment by mugling** [comment]
Looks like a likely candidate
