### ISSUE TITLE
Linux 64 not configured

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19032]
@narc0tiq

**Comment by illi-kun** [comment]
Please provide more descriptive tickets.

**Comment by BorkBorkGoesTheCode** [comment]
ci.narc.ro reports that no Linux 64 builds are being made.

**Comment by illi-kun** [comment]
Linux x64 builds with tiles support were disabled long time ago.

**Comment by narc0tiq** [comment]
Right. The SDL2 packages for Ubuntu for x86_64 and i386 are mutually exclusive. You can have one or the other; I chose the latter because they're more widely compatible.
