### ISSUE TITLE
Removing NPC clothing causes crash

### ISSUE THREAD

**Issue by jeremyshannon** [CleverRaven/Cataclysm-DDA#19035]
On Debian linux using ascii, build 0.C-19389-gc5f5e72. Save file: https://mega.nz/#!4J9hFZTA!CGue6HAUofL15aaTcUHL_-FwgwXHUbdZy32s70RZ6dc

Attempting to remove the empty canteen from the NPC "Larion" via the Sort Armor menu entry will result in an immediate crash, with the message:
/usr/include/c++/4.9/debug/vector:357:error: attempt to subscript container
with out-of-bounds index 8, but container only holds 8 elements.
Objects involved in the operation:
sequence "this" @ 0x0xbf960e90 {
type = NSt7__debug6vectorIP4itemSaIS2_EEE;
}
Aborted

**Comment by baraba3** [comment]
empty waterskins in my experience did that too.issue also happened sometimes with other pieces of clothing if npc is carrying many items in inventory.

**Comment by jeremyshannon** [comment]
Yeah I had an earlier crash when he ran out of space and I tried to remove his light jacket before I put on a trenchcoat, which I imagine made him run out of space, but I didn't have a save anywhere near that event. I think it might be a separate issue, however. Since then I've quicksaved before fiddling with NPC armor, which gave me this nicely repeatable error.

**Comment by codemime** [comment]
Reproducible. I'll fix that.

**Comment by jeremyshannon** [comment]
Oh, this appear to only affect the very last item worn by an NPC, like a fencepost error or something.
 You can work around it by adding a new item before taking anything off them.

**Comment by jzambo** [comment]
I probably have a fix here: https://github.com/CleverRaven/Cataclysm-DDA/pull/21316

**Comment by Night-Pryanik** [comment]
Can anyone confirm if this is still an issue?

**Comment by jeremyshannon** [comment]
Just tested, no crashes in latest experimental..Seems to be fixed.

**Comment by Night-Pryanik** [comment]
Ok, closing.
