### ISSUE TITLE
Filtering in the Advanced Inventory screen.

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#19049]
Version: 0.C-19422-g6a73b0d (tiles)
Build: 5789

From what I remember the instructions on how to use the filter "f" function in the Advanced Inventory screen used to say:
Search [c]ategory or [m]aterial:
Example **{c:food}**

Now it shows:
Search [c]ategory or [m]aterial:
Example **c:food**

Even though you still need the **{}** to make it filter by category or material.

**Comment by Tharn** [comment]
This is important. I assumed the filtering was broken because the instructions as presented in-game make category and material filtering simply not work.
