### ISSUE TITLE
monster non_null has no description

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#19040]
Version: 0.C-19411-g20925fa (tiles)
Build: 5785
OS: Windows 7 Professional x64 SP1

Happens when I load a save.

<a href='https://postimg.org/image/7wu875km5/' target='_blank'><img src='https://s6.postimg.org/52r2tpig1/screenshot_bug_10_31_2016.jpg' border='0' alt='screenshot bug 10-31-2016'/>

**Comment by mugling** [comment]
Suspect #19020

**Comment by BrettDong** [comment]
![2016-10-31 10 06 53](https://cloud.githubusercontent.com/assets/21075502/19856958/bc0dbf42-9fb6-11e6-9d35-650c0f16908c.png)

Can confirm. Appears on loading game save.
