### ISSUE TITLE
100 zombies mission generates errors on conversing with quest-giver

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#19041]
I was searching for an example of this bug having been reported, having only found https://github.com/CleverRaven/Cataclysm-DDA/issues/12662 thus far.

Conversing with the quest giver without the kill count being complete with generate two error messages. The first reports number of zombies killed, the second reports the target number. After this, answering the NPC's question that you have not killed enough enemies will lead to the quest inexplicably resolving itself, returning them to normal dialogue.

Despite this, asking if they have further quests will reveal that they have progressed to offering the next quest in the series.

It is rather disheartening that the bug has been around for more months than I can recall without even signs of discovery, and I am disappointed in myself for not thinking to look into the matter sooner.

**Comment by sethsimon** [comment]
>Conversing with the quest giver without the kill count being complete with generate two error messages. 

They show up unconditionally. It looks like someone forgot to remove those debug messages from `mission::is_complete`.

>Despite this, asking if they have further quests will reveal that they have progressed to offering the next quest in the series.

I can't reproduce that. Do you happen to have a savegame so I can look into it?

**Comment by DangerNoodle** [comment]
Odd. That may have been a one-off event? Need to determine where to upload a save file, as I am not a big fan of dropbox.

**Comment by sethsimon** [comment]
I think you can upload any file by clicking on the "selecting them" link at the bottom of the comment box.

**Comment by DangerNoodle** [comment]
This is strange. This time I tested it and the mission remained active. I suspect the mission disappearing was either an anomaly, or a bug from an earlier build.

I will still upload the save however. It makes use of Mining Mod ( https://github.com/DangerNoodle/mining-mod ) however.

[Shipshewana.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/572985/Shipshewana.zip)

**Comment by sethsimon** [comment]
It works as expected for me for that save too (except for the debug messages, of course). So I'll submit a PR to get rid of those debug messages.

**Comment by DangerNoodle** [comment]
Very well then, thank you.

**Comment by sethsimon** [comment]
No problem.
