### ISSUE TITLE
Difficulty in crafting UI doesn't match empirical difficulty

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#19046]
Trying to crafting a UPS conversion mod with electronics 3, int 10, and the recipe from a book ("recipe not memorized yet") yielded:

 * a claimed difficulty of 3 in the crafting UI
 * 12 bad failures (lost materials) and 1 regular failure

That was enough to get electronics 4, which then yielded:

 * 3 regular failures
 * a success

I think either the difficulty calculation is off or the difficulty display is off, that failure rate seems way too high for skill == difficulty.

b6f66e50b03f4064bfb604373cdcfa759c489479 + local non-crafting-related changes.

**Comment by mutability** [comment]
From a quick look I don't see where the "custom difficulty" maintained by recipe_subset gets passed through to the the actual crafting command, so perhaps the bug here is that the crafting is ignoring the book and using the base difficulty of 5.

**Comment by Coolthulhu** [comment]
The book difficulty is only supposed to be difficulty of comprehension (being able to craft), not of actually crafting.

**Comment by mutability** [comment]
Ok, in which case the bug here is that the wrong difficulty is shown on the crafting UI.

recipe_subset goes to some lengths to track the difficulty associated with the recipe, lowering it if an available book is easier than the base recipe, so I wonder if there is some confusion about how this should work in the code.

**Comment by Treah** [comment]
yeah I stumbled across this too. Lost quite a bit of materials trying to make the conversion mod before i gave up and leveled up to elec 4. FYI I don't notice this problem in other things non electronics maybe its limited to that?
