### ISSUE TITLE
can't remove punch dagger from boots

### ISSUE THREAD

**Issue by BrainDamage** [CleverRaven/Cataclysm-DDA#19048]
[This PR](https://github.com/CleverRaven/Cataclysm-DDA/commit/4b5f1cd6314a8959a880442ffa4330033444926b) seems to have broken sheating of small knifes inside boots: 
not only now you cannot sheat a small ( <= 0.25L) knife anymore which isn't advertised in the summary, but since activation is disabled, you cannot remove any existing ones, so they are effectively stuck inside short of savefile editing

**Comment by mugling** [comment]
Old save games should be able to continue using boots as knife sheath (I just verified this again now)

**Comment by BrainDamage** [comment]
savefile: http://filebin.ca/30Mnmb4JDluy/U3Ryb25nbWFu.sav
this is what happends when i try to to un-sheate the boots: http://imgur.com/a/eNea6
perhaps it has to do that both boots are sheated in?

**Comment by mugling** [comment]
Is this a new savegame or an old?

**Comment by BrainDamage** [comment]
old savegame

**Comment by mugling** [comment]
No other reports of this
