### ISSUE TITLE
Inventory view centering

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#19059]
@codemime how hard would this be to implement  this (probably toggled via `bool fullscreen`):

![ready](https://cloud.githubusercontent.com/assets/11905613/19703102/a912d38e-9b13-11e6-8de5-e72a693fce9a.png)

I'm poking around in the code now but it might be obvious to the original author

**Comment by codemime** [comment]
That's fairly easy. I'm implementing [that](https://github.com/CleverRaven/Cataclysm-DDA/pull/18514#issuecomment-256186197) in a following PR (which is half-ready by now). The pick up menu will go afterwards.

**Comment by mugling** [comment]
Sounds good. Can you push a branch? I'm considering reworking crating item selection to use `inventory_selector`. Probably with a custom header/footer showing fulfilled requirements.

**Comment by codemime** [comment]
Sure thing, but later. It's not ready for sharing yet. 

> Probably with a custom header/footer showing fulfilled requirements.

To be easily customized, they could be either returned by `inventory_selector_preset`, or overridden by a descendant of `inventory_selector`.

**Comment by mugling** [comment]
The other things I'm trying to work out is a sane UI for holsters with multiple items. I can get the code to do custom column headers but what could work better if some items could be expanded/collapsed to display their contents. Have you looked a this and if so were there any obvious pitfalls?

**Comment by codemime** [comment]
> but what could work better if some items could be expanded/collapsed to display their contents. 

Why don't we keep them always expanded and show their contents using an indentation? Expanding/collapsing is tedious and, as far as I can say, would do more harm than good here.

> Have you looked a this and if so were there any obvious pitfalls?

Very briefly. As for the pitfalls, it depends on chosen design. Maybe none.

**Comment by codemime** [comment]
@mugling See #19230.
