### ISSUE TITLE
Many Rivtech weapons & ammo don't properly support loudness.

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#19057]
I was playing around with the RM11B scout rifle and it had the RK6S34 suppressor installed on it, however, every time I shoot it, it seems that it deafens me. Looking at the JSON data, it appears that the gun, nor the ammo it uses (8x40mm) has loudness defined.

**Comment by mugling** [comment]
That is quite normal. Loudness should be derived from the ammo itself.

**Comment by macrosblackd** [comment]
That's fine for the gun, but I also mentioned that ammo doesn't define loudness either.

**Comment by mugling** [comment]
...derived from the **properties** of the ammo itself

**Comment by macrosblackd** [comment]
Then suppressors don't do anything meaningful.

**Comment by macrosblackd** [comment]
How is loudness actually derived from the properties of the ammo?

**Comment by mugling** [comment]
Poke around in `item_factory.cpp` near the start

**Comment by macrosblackd** [comment]
According to this, the loudness of 8x40mm ammo is around 733 units. That is ridiculous, the games "safe" measurement is ~ < 150 units.

**Comment by Rivet-the-Zombie** [comment]
Yeah the base loudness levels on undefined ammo is pretty ridiculous.

**Comment by mugling** [comment]
loudness as a whole is pretty broken

**Comment by illi-kun** [comment]
Loudness bug is discussed in #18496.
Any reason to keep current issue open?

**Comment by macrosblackd** [comment]
That's talking about how the shooter's earmuffs aren't working properly.

**Comment by illi-kun** [comment]
@macrosblackd read the entire discussion in the reference issue. Weapon loudness exceeds the expect ed limitations, so broken shooter's earmuffs is only a side effect of that.

**Comment by macrosblackd** [comment]
The discussion in that thread is talking about how the logic is wrong when determining how loud a noise is to a given creature. The bug appears to be with the fact that max_volume is using max instead of min to cap the volume to the quietest sound. That has nothing to do with weapon loudness.

**Comment by macrosblackd** [comment]
I went through and did a chart with the current loudness of many ammo types, as well as a chart for a basic change that should alleviate some of the loudness issues with guns.


![](https://docs.google.com/spreadsheets/d/1O4qdSc9qy17jzVpN-DWcJfRYFU3mWS5TbUtrg3vMFUs/pubchart?oid=312110761&format=image)

![](https://docs.google.com/spreadsheets/d/1O4qdSc9qy17jzVpN-DWcJfRYFU3mWS5TbUtrg3vMFUs/pubchart?oid=1412519362&format=image)

This is still using Damage, Range & Piercing to derive the loudness, the mitigating factor is I'm no longer taking recoil into account.

**Comment by Griffinhart** [comment]
.50 BMG being one of the quieter ammo types is pretty hilarious, I've gotta say.

**Comment by macrosblackd** [comment]
Right? The major factor in a lot of the current numbers is recoil.

**Comment by BorkBorkGoesTheCode** [comment]
.50 BMG has 700 recoil right now. It's supposed to be 17000 or so.

**Comment by illi-kun** [comment]
I don't think it's an issue anymore (with #19310 merged).
