### ISSUE TITLE
Getting several errors on save load

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#19055]
My Mods:  (note, I'm using an updated version of Arts' Guns)
[
    "Arts' Guns",
    "Medieval_Stuff",
    "makeshift",
    "More_Survival_Tools",
    "Experimental-Z-Level",
    "boats",
    "deoxymod",
    "blazemod",
    "Tanks",
    "StatsThroughSkills"
]

![capture](https://cloud.githubusercontent.com/assets/1002600/19863619/1dacdf5e-9f52-11e6-8b85-2fd4c1febaaa.JPG)
![capture1](https://cloud.githubusercontent.com/assets/1002600/19863647/37a19a08-9f52-11e6-8c0a-38d1fec261fc.JPG)
![capture5](https://cloud.githubusercontent.com/assets/1002600/19863628/253f09ea-9f52-11e6-8d9c-5d3be34fd8b1.JPG)
![capture4](https://cloud.githubusercontent.com/assets/1002600/19863633/2996523c-9f52-11e6-8b14-31d2eff02741.JPG)
![capture3](https://cloud.githubusercontent.com/assets/1002600/19863635/2bb25250-9f52-11e6-929a-2b4b3d1d871c.JPG)

**Comment by macrosblackd** [comment]
I'm getting these as well.

**Comment by mugling** [comment]
Duplicate of #19040
Mod errors can be reported on the forum

**Comment by macrosblackd** [comment]
This is happening with the tanks mod - not an unpackaged mod.

**Comment by mugling** [comment]
What error specifically - the items in those messages don't exist in `core`

**Comment by macrosblackd** [comment]
https://puu.sh/s1UZn/e796331314.png

**Comment by BorkBorkGoesTheCode** [comment]
Can confirm

**Comment by mugling** [comment]
Fixed in master
