### ISSUE TITLE
Recipe learning bug.

### ISSUE THREAD

**Issue by Oskar636** [CleverRaven/Cataclysm-DDA#19061]
When you dissassemble enough flashlights to learn the recipe, and then craft the flashlight, the game states that you managed to memorize the recipe from a book and the crafting screen shows you two identical crafting recipes.
![crafting screen bug1](https://cloud.githubusercontent.com/assets/7549186/19873915/9d347bce-9ffc-11e6-8315-35970af3063a.png)
![crafting screen bug2](https://cloud.githubusercontent.com/assets/7549186/19873917/9dcbdfdc-9ffc-11e6-8eb0-d717dcb134d7.png)

**Comment by kevingranade** [comment]
Huh, this is a side effect of dissassembly being implimented as a reverse crafting, needs a special case for when it's actually disassembly.
