### ISSUE TITLE
Is Blazemod dead?

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#19065]
I'm curious since I'm confused as to the new turret logic and if it's even needed?  Can someone confirm for me, if it's eve needed for Tanks for example or other vehicles?

**Comment by DangerNoodle** [comment]
Tanks and Other Vehicles mod has Vehicle Additions Pack as a prerequistie, yes. It seems to primarily make use of the armored tracks for the tank.

It is still likely widely used by the player base, and has seen some expansions. I do not know if the mod author is actually maintaining it though, as they do not seem to be around frequently.

Either way, as far as I am aware there is no 'new' turret logic other than needing to reload them, and this feature causing issues ( https://github.com/CleverRaven/Cataclysm-DDA/issues/17931 ). So far turrets in mainline remain automated, with manually firing them being optional. Blazemod and Tank mod seem to be the only instances where manual-only turrets are actually used.

**Comment by hmstanley** [comment]
Thanks Danger.
