### ISSUE TITLE
H&K G80 Railgun has zero range

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#19083]
Neither the gun nor the ammo it uses specify a range, so it ends up having zero range.

**Comment by BorkBorkGoesTheCode** [comment]
Since the range cap is only intended to be temporary, could you increase range to 60?

**Comment by BorkBorkGoesTheCode** [comment]
Since the range cap is only intended to be temporary, could you increase range to 60?
