### ISSUE TITLE
Download from site fails to run on Linux

### ISSUE THREAD

**Issue by tukkek** [CleverRaven/Cataclysm-DDA#19095]
Hi, running `cataclysm-tiles` from the extracted directory "cataclysmdda-0.B" (or via `cataclysm-launcher`) produces the following error message:

> ~/bin/cataclysmdda-0.B$ ./cataclysm-tiles 
> bash: ./cataclysm-tiles: No such file or directory

The file is certainly there so the error message is probably referring to a resource not being found when running the binary. Using the launcher application gives the same message and seems to be working correctly by having the correct $BIN and $DIR values and reaching this line successfully https://github.com/CleverRaven/Cataclysm-DDA/blob/master/cataclysm-launcher#L33

Also the extracted file creates a 0.B directory when the website says the latest release is 0.C. Is it outdated or is the directory name wrong?

Running the latest experimental version (0.C-5811) gives the same exact error message for both launcher and binary. No further output is shown.

**Comment by tukkek** [comment]
Just to make it clear, because the error message is misleading: the binary is certainly there and is being run as far as I can tell. Let me know how I can help pinpoint the cause of the error message further if you need my help with further testing.

**Comment by tukkek** [comment]
I'm guessing it could be a missing library in my system? I've taken a look at the dependencies from _COMPILING.md_  and I seem to have them all. Also, when a missing file like this is causing the problem most games throw out a more informative message. Maybe you're catching a fatal exception and not printing all the details (like the actual missing resource name) to the terminal?

**Comment by tukkek** [comment]
Forgot to mention: running the latest experimental console version download gives the same error.

**Comment by BrettDong** [comment]
Did you download the correct architecture? Running a 64-bit binary on a 32-bit system could display the same error: `No such file or directory`. If you're sure you have downloaded the correct architecture, try `ls -la cataclysm-tiles` and see whether it has execution permission.

**Comment by tukkek** [comment]
What is the architecture for the Linux Graphical sidebar link on your website? You don't seem to have separate 32 and 64 bit downloads. Also I'm sure that the file was executable straight out of the .tar file but I'll happily try again once you point me to the correct 64 bit package.

Thanks for the reply. I'm really looking forward to testing out your game, have been for a while but just recently found out there's a tiles version, which made it a must-try :) Also I'll send you some graphical mode screenshots as soon as I get the game running because it's really a shame not to have them on your screenshots page, which I've visited a few times and always concluded the game was ASCII only.

**Comment by illi-kun** [comment]
We don't provide linux x64 builds with tiles support. For checking the assumption BrettDong's assumption, you can download curses version for x64 here:
http://dev.narc.ro/cataclysm/jenkins-latest/Linux_x64/Curses/

**Comment by tukkek** [comment]
Why? Should 64-bit Linux users compile the game themselves? I don't understand it, if you are able to provide a 64-bit download of the console version... 

Anyway you should know that 32 bit is quickly becoming obsolete, I doubt any of your players actually have 32 bit processors on their computers. If you need to select between 32 and 64 bit to provide as a download for the Linux tiles version you definitely should offer 64 bit instead.

**Comment by mugling** [comment]
> I doubt any of your players actually have 32 bit processors on their computers

I'm 100% certain those processors are capable of running 32-bit code

**Comment by tukkek** [comment]
Yes, mostly but there are issues involved. If processor architecture is not
the case then as you guys implied then I'm not sure why we're discussing
this.

**Comment by illi-kun** [comment]
To summarize the issue: you are not able to run x32 version of the game with tiles support but able to run x64 version without tiles support. Is that correct statement?

**Comment by tukkek** [comment]
I can't seem to run any version on Linux, neither stable or experimental
nor console or graphical. I'm not sure which architecture (32 or 64) I'm
using because your downloads don't specify that information as far as I can
tell.

**Comment by illi-kun** [comment]
Use this link to download all available versions (linux curses, linux tiles, linux x64 curses):
http://dev.narc.ro/cataclysm/jenkins-latest/

Also, you need to check permission.

**Comment by tukkek** [comment]
As I've said before, permission (+x) is always set. The download package
seems to take care of that during extraction.

Linux_x64/Curses - works (opens to title screen)
Linux/Curses - `No such file or directory`
Linux/Tiles - `No such file or directory`

The errors are the same either invoking the binary or the shell script
launcher.

Tested with latest versions available (0.C-5829) on the given link.

**Comment by mugling** [comment]
You likely need the 32-bit libraries via the package manager for your specific version of linux. You're likely to get better help on the forums than here.

**Comment by tukkek** [comment]
It's definitely a bug so it belongs here. I don't think most people are
willing to go through a multi-arch Linux install just for the sake of
testing a game when it's not even clear if that would solve the problem. I
know I'm not. You guys should work on that error message being more
specific and probably consider deploying the needed libraries or at least
providing better documentation or a x64 graphical mode download. Linux
probably isn't your priority as with most games but I consider CDDA
(graphical) unplayable right now on Linux so if you guys want Linux x64 to
be a target platform for your distribution system you need to work on it.

I don't mean to sound bitter or entitled, I'm just saying like it is - I'm
objectively unable to play your game with the packages from your website.
Also make no mistake: probably 99% of your Linux users are running x64
systems (is any of you running 32?) so they'll most likely get the same
issue as me when trying to runt he game.

**Comment by mugling** [comment]
> I don't think most people are willing to go through a multi-arch Linux install just for the sake of testing a game when it's not even clear if that would solve the problem. I know I'm not

You might want to read a little more about 32 and 64-bit software and possibly seek help from other users of your distribution. Packaging system libraries or adjusting the error messages from your kernel are a little beyond our scope here.

**Comment by illi-kun** [comment]
Closed. Please continue discussion on our forum.
