### ISSUE TITLE
Vehicle Smoke Persists Too Long

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#19093]
While driving around in experimental version 0.C-19402-gb6f66e5, I have noticed that the smoke left by my vehicle on the way out is still there on the way back. I have only really noticed it when traveling over 40 mph both ways. It is just really weird to watch the trail of smoke I left evaporate in front of me on the return trip, even days later. I am guessing this is a strange edge case to the reality bubble, but I really have no clue.

**Comment by mugling** [comment]
Yes, it's been discussed before (reality bubble). No readily practical fix at this time
