### ISSUE TITLE
ammo belt linkage no longer assemble ammo and do no unload to match rounds

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#19091]
Couple of issues.

1) when you have an ammo belt linkage and then click on it, say 200 of them, it will indicate insufficient ammo, when you have plenty of ammo.
2) when you unload an ammo belt, it unloads the ammo correctly, but leaves ONE linkage. 

Two bugs here.

**Comment by mugling** [comment]
Have identified cause and fix is in progress
