### ISSUE TITLE
Template system for items

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19115]
For example, we have cooked meat and cooked fish, jerky and salted fish, smoked meat and smoked fish, chunk of meat and fish fillet.
Those could be expressed as "[salted] chunk of meat", "[salted] fish fillet", with "[salted]" being a template lowering weight, volume, nutrition and quench and increasing charges. That is, changes from salting would be expressed as one template, for all salted objects.

This can't be done with "copy-from", because "copy-from" only allows one argument.

Template would basically be a definition that requires "copy-from" to be set, but doesn't set it on its own, instead relying on the parent to do that.

Example syntax:
```
"copy-from": [ "meat", "spiced", "salted" ]
OR
"copy-from": "meat",
"templates": [ "spiced", "salted" ]
```

Order of templates obviously matters.
This would be processed as:
* Start with "meat"
* Create "spiced meat" internally (can be dropped after next step), as if by copying "spiced" definition and adding `"copy-from": "meat"` to it
* Create the final "spiced and salted meat", as if by copying "salted" definition and adding `"copy-from": "spiced meat"` to it

This would allow defining sets of items in terms of relations:
* Reloaded 9mm is a 9mm that is also reloaded ammo
* Pipe shotgun is a single barrel shotgun that is also a makeshift gun
* .223 casing is a .223 cartridge that is also a casing (this one could be more complicated than what I described here, disregard this point if it is)
* Jerk jerky is a chunk of meat that is human and salted
* JHP ammo would all be JHP in the same way
* Diamond weapons would be generated at finalization instead of essentially being re-generated when their "diamondness" is needed

This would be self-documenting and maintainable. Balance notes like "reloaded ammo should have x recoil and y damage" would be obsolete.

Same thing could be applied to monsters, to create "fungal zombie predator", "zombified cow" and "acidic fungal zombie bio-operating domesticated giant wasp".

**Comment by mugling** [comment]
So we already have the partial templates in the form of `abstracts`. They already support `relative` and `proportional` properties. It wouldn't be hard to allow sequential `copy-from` (left-to-right).

That would provide 90+% of the solution for almost no code changes?

Added bonus - we could extend blacklisting to forbid templates which would make it really easy to eg. blacklist all fungal monsters, all reloaded ammo etc?

**Comment by spurdo** [comment]
It seems like this could massively reduce the amount of item bloat and make it easier to have more varied food items.

For instance when you craft canned fruit the recipe uses 2 fruit 1 water and 1 glass jar creating "canned fruit". But if instead you used 2 items with a fruit tag to add the canned (in glass) template then you could have "canned banana" and "canned apple" etc. this would apply to many of the food recipes and seems like it would make the food crafting much simpler.

**Comment by mugling** [comment]
It won't reduce item bloat only JSON bloat - it's a QOL fix for the developers.

**Comment by mugling** [comment]
In fact there is a hidden danger that such a system will be used to produce lots of item bloat. For example `spiked atomic fursuit`. In fact you could even have an autobloater mod that generated random combos - worryingly I suspect at least a few people might even want that.

**Comment by Coolthulhu** [comment]
> Added bonus - we could extend blacklisting to forbid templates which would make it really easy to eg. blacklist all fungal monsters, all reloaded ammo etc?

Didn't think about it, but it sounds like a good idea. Though that would not come for free - objects would need to record the templates they use or otherwise flag themselves as having the blacklisted property.

> For instance when you craft canned fruit the recipe uses 2 fruit 1 water and 1 glass jar creating "canned fruit". But if instead you used 2 items with a fruit tag to add the canned (in glass) template then you could have "canned banana" and "canned apple" etc. this would apply to many of the food recipes and seems like it would make the food crafting much simpler.

This would be a separate application that would first require some extra addition.
I see two ways to approach this:
* A list of templated objects to be generated. For example, a whole set of canned fruits. Could be automatically generated based on some sort of "request", like canning recipe requesting a separate object for a subset of inputs.
* A runtime system for requesting templated items. This one could spare us holding the massive bloat of multitude of variant items in memory, instead requesting them as required. Would require a rework of item factory, though.

Honestly I'd love runtime objects, but those are a much bigger undertaking than a simple type template system.

> In fact you could even have an autobloater mod that generated random combos - worryingly I suspect at least a few people might even want that.

We'd switch from "linear bloat" to "exponential bloat".
Though if it was approached properly, it could instead look less bloated than what we have now.

Consider the "autobloater" generating pairs: `(weapon, material)`.
This would be "quadratic bloat", yet the actual "obesity" of the game wouldn't increase that much.
Dwarf Fortress has something like this, though probably more implicit.

Being able to forge a salt-encrusted plastic sword with a furred handle would not produce much "perceived bloat" if it didn't include a separate recipe, instead generating (or just recalling) the type on craft time based on input components.

**Comment by MisterFox** [comment]
I would like to see templates have different nutrition, if possible -- something like (insect) meat being high in calcium compared to (animal) meat

**Comment by Zireael07** [comment]
> In fact there is a hidden danger that such a system will be used to produce lots of item bloat

I think this is not a real problem. The idea, however, would be useful, for instance, for all the 'can of x' items.

**Comment by Coolthulhu** [comment]
Cans and jars of food are implemented using different methods - by putting food inside containers.
This can already be done using jsons with no weird manipulation. Using templates here would have only one advantage: creating canned food template which would change nutrition/fun/volume etc. (NOT the container - this one isn't really a property of the item).

**Comment by kevingranade** [comment]
Old wishlist type issue with no progress in nearly a year.
