### ISSUE TITLE
Proposal to weaken the stone pot

### ISSUE THREAD

**Issue by MisterFox** [CleverRaven/Cataclysm-DDA#19111]
As it stands right now, there is very little reason to use a regular pot over a couple rocks tied together with a string. The only difference between a stone pot and a regular pot is that the regular pot isn't as heavy. There are also very few situations to even consider making a clay pot at all.

My proposal to balance the stone pot for its ease to craft would be to change its qualities to be equal of the 'makeshift' pots from the More Survival Tools mod. The new qualities would be as follows:

* Boiling 1
* Containing 1
* Food Cooking 2

That means a stone pot would no longer be sufficient for making:

* fungicide
* meth
* crack
* poppy drugs
* diazepam and other medicines
* concentrated acid
* some advanced cooking
* ...and many more items including superglue and tanning hides.

The idea behind this is that a stone pot is unbalanced by the fact that it's cheap to make and very powerful outside of using a chemisty set. **Weakening the stone pot will hopefully encourage players to either seek out a metal pot or work their way through making a clay pot through construction and use of a kiln.** This should do little to affect conventional cooking, but any sort of advanced crafting will need a better pot.

I can do the work to lower the qualities in a pull, but I wanted some discussion about it in case this was a change that nobody wants.

**Comment by BorkBorkGoesTheCode** [comment]
Why does creating a stone pot require string?

**Comment by MisterFox** [comment]
I'm not sure I can imagine how the stone pot is actually made -- the components make it sound like it's a bunch of rocks tied together (somehow) but you also need a hammering tool. Maybe you pound the rock with a hammer to make a cooking basin and then keep it held together with string?

**Comment by DangerNoodle** [comment]
Not being able to tan hides using a natural pot is a terrible idea.

**Comment by BorkBorkGoesTheCode** [comment]
It's a hollow stone, according to the description. D'oh! I just realized it's supposed to be a rope pot handle.

**Comment by MisterFox** [comment]
The alternative would be to change the quality requirements for the tanning hides. You can make a clay pot with the requirements for tanning out of nothing but rocks, wood, and clay, aside from having some construction skill.

**Comment by DangerNoodle** [comment]
It might be good to alter the requirement. If I recall, tallow requires a lower cooking quality, perhaps the quality could be lowered then.

**Comment by Voker57** [comment]
stone pot and lots of other makeshift tools should be properly weakened by implementing failure chance and/or crafting time multiplier depending on tool quality.

**Comment by MisterFox** [comment]
A flat failure chance would just result in frustration, especially when desperate to cook something to survive. A time multiplier might also be an option but unique code for the situation.

If we reduced the requirements for tanning down to Food Cooking 2 and Boiling 1, they could be made in the stone pot. This could be a preferable temporary measure until it's more clear how players can manage to make a clay pot -- there's nothing saying that the construction menu kilns can be used for the crafting aside from guesswork.

**Comment by Voker57** [comment]
> A flat failure chance would just result in frustration, especially when desperate to cook something to survive

Modified by your skill/mood, maybe. Crafting something with makeshift tools should result in taking chances frustration, to motivate switching to proper tools and not just happily sticking with can stove fed by kindling for the whole game.

**Comment by Nernums** [comment]
stone pots are already weaker than metal ones, they are heavier and have a lower cooking quality.
stone pots in real life are not bad at cooking or anything, they are just simply basic and a tad fragile when it comes to being shocked by cold water after heating, in the same way glass or ceramics are, just more so.

**Comment by Shoes01** [comment]
What is the stone pot or other makeshift items were to wear out after use? 

What if the "frustration" was abstracted as a morale penalty for the survivor rather than literal frustration for the player?

**Comment by illi-kun** [comment]
@Shoes01 no need to implement new mechanics (at least, as a fix of the raised issue).

**Comment by illi-kun** [comment]
@MisterFox So, what is your conclusion about provided feedback? Did you change your mind about rebalancing / drop this idea?

**Comment by DangerNoodle** [comment]
My recommendation is to lower the cooking requirements of tanning hies so that they are available with makeshift pots, then reduce the qualities of it.

I could implement this in a pull request if desired?

**Comment by illi-kun** [comment]
@DangerNoodle that sounds fine for me, feel free to implement it.

**Comment by DangerNoodle** [comment]
Very well then. aside from ensuring tallow and tanning work with the specifications makeshift pots have, any other recipes that might be desirable? Poppy recipes and related survival-manual recipes maybe?

**Comment by illi-kun** [comment]
I'm not sure about other recipes for changes. I guess it's okay to start from main changes and improve the details later.

**Comment by DangerNoodle** [comment]
So far I am only going with a minimum of changing the recipes for tanning hides and pelts. The main recipes, the modernized ones are left untouched at present.
