### ISSUE TITLE
I think the move stack "m" function in the Advanced Inventory screen is broken.

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#19127]
Version: 0.C-19469-gb7cad63 (tiles)
Build: 5814
OS: Windows 7 Professional x64 SP1

When trying to move a stack of 13 _chunks of fat (fresh) (1)_ using the **m** (move an amount of item) key, the game looks at the portions _(1)_ instead of 13 under the _amt_ (amount) column.
Shown in the screenshot below:
<a href='https://postimg.org/image/rfbujt0gt/' target='_blank'><img src='https://s6.postimg.org/z82ibs6g1/Bug_Trying_to_move_stacks_looks_at_portions_par.jpg' border='0' alt="Bug. Trying to move stacks looks at portions par"/></a>

Here I use the move stack key **m** (move an amount of item) to move a single _chunk of meat (fresh) (5)_, but instead of telling me that I have 1 chunk of meat, it tells me I have 5. The game does move whatever amount of the (5) portions I tell it to move.
<a href='https://postimg.org/image/ungbwumql/' target='_blank'><img src='https://s6.postimg.org/hw25qccyp/Bug_Trying_to_move_stacks_looks_at_portions.jpg' border='0' alt="Bug. Trying to move stacks looks at portions"/></a>

I've never used it before now, but the **M** (move item stack) only moves 1 item in a stack.
This bug seems to only affect foods where **(portions)** and **amt** (amount) >  1 are possible, pre-packaged foods like  _plastic bag of potato chips (3)_ don't seem to be affected. My guess is that minimally processed foods are the most affected i.e.: meat, fruit, etc.

**Comment by MisterFox** [comment]
Not just that - something changed recently that's made items in portions like that a whole lot more annoying to pick up in general. I have to repeatedly try to pick up individual cattail stalks or cherries, for example.

**Comment by ArikVhedrovix** [comment]
This also affects normal pickup using "," key of some items as well. Issue #19143

**Comment by AMurkin** [comment]
I was beginning to think that it is - a feature.

**Comment by AMurkin** [comment]
It seems fixed.
