### ISSUE TITLE
Shelters are bugged

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#19135]
They need some ... hammering out?
Maybe we should ... invest in finding the problem?

<a href="http://imgur.com/mg11Vye"><img src="http://i.imgur.com/mg11Vye.png?1" title="source: imgur.com" /></a>

Puns or not, theres anvils and atms everywhere in this unmodded world.

**Comment by mugling** [comment]
New world or savegame?

**Comment by pisskop** [comment]
New world.  Its stopped now; Ive recompiled after the merge

**Comment by hmstanley** [comment]
I'm still seeing this in the latest 32bit Windows build.

**Comment by dopeghoti** [comment]
![screen shot 2016-11-03 at 15 45 01](https://cloud.githubusercontent.com/assets/295727/19988358/e00abc2e-a1dc-11e6-91e5-a3f2cbe9e488.png)

New world on Macos.

**Comment by dopeghoti** [comment]
Looks like my build was one commit before e1c9cbe, which fixed this.  Pulled down the current commits, and this is no longer happening for me; this can probably be re-closed, @pisskop .  Sorry for the false alarm.

**Comment by mugling** [comment]
@pisskop consistently or randomly?

**Comment by pisskop** [comment]
All 3 times I tried.

**Comment by pisskop** [comment]
closing under the presumption its fixed for now
