### ISSUE TITLE
Can't Reload Spraycan Flamethrower

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#19131]
Using windows experimental cataclysmdda-0.C-5814:
Can't reload Spraycan Flamethrower even with Gasoline in inventory. Get message "Out of flammable liquid!" Wished up several other types of flamethrower and I can't load any of them either.

**Comment by BorkBorkGoesTheCode** [comment]
@ArikVhedrovix Flamethrowersin general are having trouble with loading gasoline from containers. Try using napalm until fixed.

**Comment by ArikVhedrovix** [comment]
I tried wishing up some napalm because my character doesn't have the recipe and I can't seem to load that either.

**Comment by BorkBorkGoesTheCode** [comment]
Does your world use blazemod?

**Comment by ArikVhedrovix** [comment]
![screen shot 2016-11-06 at 10 04 26 am](https://cloud.githubusercontent.com/assets/5952322/20039381/79e49db0-a408-11e6-8770-a836ec7af348.png)

I have been using the "Vehicles Additions" mod which says it is by a Blaze

**Comment by ArikVhedrovix** [comment]
I just tried a new world without that mod and I still couldn't reload a spraycan flamethrower with napalm I wised up.

**Comment by BorkBorkGoesTheCode** [comment]
Blazemod has a copy of the gasoline item which lacks multi-itemgroup support. If that entry is amended to include the flammable itemgroup, or deleted entirely, the flamethrowers will work. 

>I just tried a new world without that mod and I still couldn't reload a spraycan flamethrower with napalm I wised up.

That is a separate issue caused by the game's liquid handling.

**Comment by ArikVhedrovix** [comment]
Ok, great! I will try a world without the Blaze mod, and report back so this issue can be closed. Thanks!

**Comment by ArikVhedrovix** [comment]
Ok, I made a world without "Vehicle Additions" world mod, wished up a bottle, hose and spraycan flamethrower. I siphoned gas into the bottle and then I was able to reload the flamethrower. Thanks for your help, BorkGoesTheCode!
