### ISSUE TITLE
Can't deconstruct some "furniture" pieces.

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#19139]
Version: 0.C-19469-gb7cad63 (tiles)
Build: 5814
OS: Windows 7 Professional x64 SP1

Out of all the items in the Furniture list the Fermenting Vat, Wooden Keg, and Fire Ring cannot be deconstructed.
I expected to not be able to deconstruct Standing Tank, but it can be.
I did have the required deconstruction tools (hammer, screw driving).
I checked the action menu (%) for anything useful and also I looked it them (e).
I tried deconstructing the Fire Ring (it requires a pit to be constructed) with and without the pit, neither worked.

The only way to get rid of them is to destroy them. Is this intended?

**Comment by DangerNoodle** [comment]
I had intended to implement a way to dismantle things that logically should not require a hammer screwdriver (such as the fire ring), but I made no progress due to difficult implementing it.

**Comment by Nhatorama** [comment]
@DangerNoodle
Do you remember if the Fermenting Vat, Wooden Keg, and Fire Ring could be deconstructed in past builds? If it was possible before is there a way to easily restore that code without breaking things?

If there's no code to restore for the Fermenting Vat, Wooden Keg, and Fire Ring I would rather have the deconstruction code for the other furniture reused until a better way is found.
Unfortunately I can't lend a hand myself. :(

**Comment by DangerNoodle** [comment]
I do not not recall that being the case, no.

**Comment by Coolthulhu** [comment]
A relatively simple hack that could work would be having 2 deconstruction recipes: one for most things, one that takes no tools. Our current system already handles multiple recipes under the same name, for example if you want to build a wall.

Then the furniture easy to deconstruct would be marked with a flag or a `bool` switch. Stuff with that flag would allow the easy recipe to work for it.

This would require some minor hardcoding: the simple recipe would have to check `can_deconstruct` and that flag.

**Comment by DangerNoodle** [comment]
> A relatively simple hack that could work would be having 2 deconstruction recipes: one for most things, one that takes no tools. Our current system already handles multiple recipes under the same name, for example if you want to build a wall.

Any suggestions on implementing this? I could make another attempt at my pull request if possible. To be honest though, it would be easier to add deconstruct recipes item by item, as with my first attempt, as doing so requires do source code changes.

**Comment by Coolthulhu** [comment]
> Any suggestions on implementing this?

Simpler variant is with the flag:
* Add a `can_deconstruct` variant that checks `can_deconstruct` first and then the new flag
* Add a deconstruction recipe that uses the new variant instead of pure `can_deconstruct` and takes no tools
* Add the flag to some furniture

**Comment by DangerNoodle** [comment]
Hmm. I recall that was exactly what I attempted to implement, but there were a lot of code issues in my attempt due to lack of experience, and implementing a new context prompted the lint-check to fail.

What is abnormal is that my attempt compile-tested without any apparent issue.

**Comment by Leland** [comment]
Closing due to stalled discussion. @DangerNoodle you were the last to work on this, let me know if you'd like this kept open.

**Comment by DangerNoodle** [comment]
If I had made any signifigant progress in my prior attempts at it, I would resume work on it.
