### ISSUE TITLE
Harvesting flowers/bushes seems to produce multiple stacks

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#19143]
Using windows experimental cataclysmdda-0.C-5814:
When harvesting a flower or bush multiple stacks of the resulting harvest seem to be produced and each must be picked up separately. For example, I harvest a datura I get the message that I harvested 4 seeds, but there are still 3 stacks of datura seeds x 4 in the square the flower occupied. For Berries it seems to make some number of Berries (1), each of which must be picked up separately when using the "," pickup command even though they only take up 1 line in the pickup menu.

![harvestbug](https://cloud.githubusercontent.com/assets/5952322/19983812/8001e9b8-a1d9-11e6-86c3-7aaa6d6009e7.png)

In inventory I now have 12 total Datura seeds.

**Comment by Treah** [comment]
I wonder if this was intentional? If so its hyper-realistic tedium that is detrimental to game play....

**Comment by ArikVhedrovix** [comment]
This has been marked a bug and the label seems to fit to me. The behavior is different from picking up other stacks so I don't think it was intentional. Just my best guess though.
