### ISSUE TITLE
[MAC] Build error when trying to compile recent Mac clone

### ISSUE THREAD

**Issue by bpwatts** [CleverRaven/Cataclysm-DDA#19141]
clang++  -DRELEASE -DMACOSX -DGIT_VERSION -DTILES -ffast-math -Os  -Wall -Wextra   -fsigned-char -Werror -stdlib=libc++ -std=c++11 -MMD -mmacosx-version-min=10.7 -F/Library/Frameworks -I/Library/Frameworks/SDL2.framework/Headers -I/Library/Frameworks/SDL2_image.framework/Headers -I/Library/Frameworks/SDL2_ttf.framework/Headers -c src/action.cpp -o obj/tiles/action.o
In file included from src/action.cpp:17:
src/mapdata.h:246:9: error: chosen constructor is explicit in copy-initialization
        {}, {}, {}, {}
        ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/set:428:14: note: constructor declared here
    explicit set(const value_compare& __comp = value_compare())
             ^
In file included from src/action.cpp:17:
src/mapdata.h:246:13: error: chosen constructor is explicit in copy-initialization
        {}, {}, {}, {}
            ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/set:428:14: note: constructor declared here
    explicit set(const value_compare& __comp = value_compare())
             ^
In file included from src/action.cpp:17:
src/mapdata.h:246:17: error: chosen constructor is explicit in copy-initialization
        {}, {}, {}, {}
                ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/set:428:14: note: constructor declared here
    explicit set(const value_compare& __comp = value_compare())
             ^
In file included from src/action.cpp:17:
src/mapdata.h:246:21: error: chosen constructor is explicit in copy-initialization
        {}, {}, {}, {}
                    ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/set:428:14: note: constructor declared here
    explicit set(const value_compare& __comp = value_compare())
             ^
4 errors generated.
make: *** [obj/tiles/action.o] Error 1

Let me know what else you need!

**Comment by BrettDong** [comment]
Which Xcode version are you using?
I'm using Xcode 8.1.0 on mac OS 10.12.1 Sierra on my Macbook Air now, and I compiled successfully with the latest master branch.

**Comment by bpwatts** [comment]
XCode 5.5.0 on macOS 10.9.5

I'll see about updating XCode.

**Comment by bpwatts** [comment]
Crap, I dont think I can upgrade XCode anymore. We'll see if the store lets me update to a version that lets me compile successfully.

**Comment by BrettDong** [comment]
There might be some compile errors with old versions of clang. I suggest you could build a new LLVM/Clang toolchain and try to build CDDA with the newer compiler.

**Comment by bpwatts** [comment]
I'm afraid I'll have to update the base OS to do that -- and I've got existing incompatibilities with later versions of MacOS. The Mac Store seems to think there was an update to my compatible versions of xcode -- I'll give it a whirl.

**Comment by BrettDong** [comment]
You could download LLVM 3.9 and build it on your own.

**Comment by bpwatts** [comment]
Okay, did that. Same error. Got to LLVM 3.9

Macintosh-2:Cataclysm-DDA_tiles admin$ git pull && make NATIVE=osx OSX_MIN=10.7 RELEASE=1 LOCALIZE=0 CLANG=1 FRAMEWORK=1 TILES=1
Already up-to-date.
/bin/sh: astyle: command not found
Cannot run an astyle check, your system either does not have astyle, or it is too old.
Cannot lint JSON, missing usable perl binary and/or p5-JSON module
clang++  -DRELEASE -DMACOSX -DGIT_VERSION -DTILES -ffast-math -Os  -Wall -Wextra   -fsigned-char -Werror -stdlib=libc++ -std=c++11 -MMD -mmacosx-version-min=10.7 -F/Library/Frameworks -I/Library/Frameworks/SDL2.framework/Headers -I/Library/Frameworks/SDL2_image.framework/Headers -I/Library/Frameworks/SDL2_ttf.framework/Headers -c src/action.cpp -o obj/tiles/action.o
In file included from src/action.cpp:7:
In file included from src/map.h:12:
In file included from src/item.h:11:
In file included from src/visitable.h:10:
src/string_id.h:66:50: error: instantiation of variable 'string_id<emit>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/emit.h:14:18: note: in instantiation of member function 'string_id<emit>::string_id' requested here
        emit() : id_( NULL_ID ) {}
                 ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<emit>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
1 error generated.
make: *** [obj/tiles/action.o] Error 1

And my new clang version:

Macintosh-2:Cataclysm-DDA_tiles admin$ clang --version
clang version 3.9.0 (tags/RELEASE_390/final)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
InstalledDir: /Users/admin/Downloads/clang+llvm-3.9.0-x86_64-apple-darwin/bin

**Comment by patternoia** [comment]
Maybe this might help. `clang --version` output on the Jenkins CI OSX builder:

builder:~ user$ clang --version
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by bpwatts** [comment]
Well sure but I can't update OSX any further. It breaks too many things.

**Comment by bpwatts** [comment]
Okay yeah, I've confirmed on a test box you can build just fine from a freshly updated box (both Sierra and xcode 8.1). I guess someone has to update some documentation that says what the minimum required versions are to compile. Gotta be at least above 10.9.5!
