### ISSUE TITLE
When an M240 is in your inventory, you can't remove it from your inventory

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#19152]
Weird bug.

Go into one of those survivor shelters, the one with the wood stove and water on the ground, pick up the M240 from the dead survivor and then try to drop it, you can't.. I had to restore from save in order to remove the weapon from my inventory, or just quitting the game.  Anyway, not sure what this is about, but very strange.

**Comment by codemime** [comment]
That's very strange indeed. I can't even obtain it via debug menu.

**Comment by codemime** [comment]
Looks like `"built_in_mods": [ "bipod" ]` is an offending line. It works fine with the line removed.

**Comment by BorkBorkGoesTheCode** [comment]
Cannot replicate in 5846 using a debug m240. Will try to find a wild m240

**Comment by codemime** [comment]
I suspect the issue was fixed in #19179.
