### ISSUE TITLE
Windows 64 build failure

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19169]
`make: /home/narc/mxe/usr/bin/x86_64-w64-mingw32.static-ccache: Command not found
make: *** [cataclysm.exe] Error 127
Build step 'Execute shell' marked build as failure
Recording fingerprints
IRC notifier plugin: Sending notification to: #CDDA-dev
SSH: Current build result is [FAILURE], not going to run.
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] Skipped based on build state FAILURE
Finished: FAILURE
`

**Comment by illi-kun** [comment]
Duplicate of #19027.
