### ISSUE TITLE
You can be assigned to the same mission twice

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#19163]
To reproduce this, load the stable 0.C version, start a new character, and start a mission. Then switch to the experimental version, and load that save (You might get a debug message (pictured below), but strangely, sometimes I didn't).

Then talk to the same NPC again, and he'll treat the mission as if it were unassigned. If you accept the mission, you'll have 2 duplicate red entries ( your sole active mission is colored red ) in the mission window (M). You can complete one of the duplicate missions, but the other one will be impossible to complete (the NPC won't even ask "Have you finished the mission yet?") so the result is a permanent entry in the `Active Missions` tab in the mission window.

![mission0 c](https://cloud.githubusercontent.com/assets/16765166/20027059/e85913f4-a2df-11e6-812c-5d1864f8a07a.png)

**Comment by Zireael07** [comment]
> stable 0.C version

Have you checked that the bug is present in the experimentals? Mission handling has had improvements since then...

**Comment by sethsimon** [comment]
It's not present in the experimentals; the issue is that backward compatability is broken.
