### ISSUE TITLE
.50 BMG recoil is extremely low

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19177]
.50 BMG recoil is currently set to 700, comparable to pistol rounds.

**Comment by Coolthulhu** [comment]
We need some sane system for recoil.
Nowadays it can easily stack so high that you have to walk it off, but when it doesn't stack, it's rather harmless.

**Comment by Reclusive-reptile** [comment]
Is there an upper limit to  recoil?

**Comment by Coolthulhu** [comment]
Currently no, you can get thrown away so hard that you will stay "recoiled" after switching weapons.

**Comment by Leland** [comment]
Line in question for anyone interested in addressing: https://github.com/CleverRaven/Cataclysm-DDA/blob/46a287082ff52a2de3bc00ab18c4f5dcbd80bffc/data/json/items/ammo/50.json#L31

**Comment by elricsfate** [comment]
Kinetic energy of 9mm 

https://en.wikipedia.org/wiki/9×19mm_Parabellum

Kinetic energy of .50 BMG

~481 Joules

https://en.wikipedia.org/wiki/.50_BMG

~18,050 Joules 

There are differences in how much recoil one will feel and how much it effects firing.Examples: if the weapon has a stock, if a bipod or forward grip is used, how the weapon is held, and the firing position. There are likely more I'm forgetting.  

In general though a 50 BMG round would have ~37.5 times more recoil than a 9mm round. 

@Coolthulhu 

Recoil should absolutely be handled differently. Recoil should have a maximum cap and fire within a certain cone depending on skill level of the shooter. Recoil should also burn down far more quickly.
