### ISSUE TITLE
The RM11, AUG and SKS disappear from the world when dropped.

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19176]
Reported on the forum and verified on 5835

http://smf.cataclysmdda.com/index.php?topic=13611.msg287521#msg287521

**Comment by BorkBorkGoesTheCode** [comment]
latogato mentioned that machine guns with bipods are affected.

**Comment by Coolthulhu** [comment]
Seems that "NO_DROP" or "IRREMOVABLE" flag is passed down from gunmods.

**Comment by BorkBorkGoesTheCode** [comment]
The AUG doesn't have a gunmod with an IRREMOVABLE flag.

**Comment by Coolthulhu** [comment]
From what I recall, gunmods become IRREMOVABLE when they are integrated. This is what makes them integrated, as opposed to just spawning with the gun but removable.

**Comment by BorkBorkGoesTheCode** [comment]
The KSG shotgun and the combo guns are unaffected by this bug, even though they have integral gunmods.

**Comment by Coolthulhu** [comment]
Pipe combo gun has integral magazine. Do other unaffected guns have integral magazines only?
Do all affected guns have non-integral magazines?

**Comment by BorkBorkGoesTheCode** [comment]
All unaffected guns have integral mods with gun code.

**Comment by Coolthulhu** [comment]
I think I found it: #18997 removed a special case. "IRREMOVABLE" flag was supposed to only affect gunmods, not the attached item.
Now it can be solved more cleanly by making "IRREMOVABLE" a flag that isn't inherited.
