### ISSUE TITLE
The game won't launch on a 1GB RAM system

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#19171]
After double-clicking at `cataclysm-tiles.exe`, a white blank window appears. About half a minute has past, it is still pure white. Then, suddenly, the process disappears.
![2016-11-05 7 41 49](https://cloud.githubusercontent.com/assets/21075502/20030041/a1826652-a397-11e6-9fbc-d9e38f6021dd.png)

I traced it under GDB:
![2016-11-05 8 34 56](https://cloud.githubusercontent.com/assets/21075502/20030042/a1851c6c-a397-11e6-9dd4-693c10d0c530.png)

On MSDN documentation [(here)](https://msdn.microsoft.com/en-us/library/cc704588(d=lightweight,l=en-us,v=PROT.10).aspx) exception code `0xc0000017` seems to represent something like _out of memory_.

| 0xC0000017 |
|-|
| STATUS_NO_MEMORY |
| {Not Enough Quota} Not enough virtual memory or paging file quota is available to complete the specified operation. |

----

So the reason is that when loading the default tileset `ChestHole`, there's no enough memory, while `retrodays10` works fine. But the problem is, for a fresh unzipped CDDA, there's no way to avoid the program to load `ChestHole` unless manually copy `options.json` from another computer.

**Comment by DanmakuDan** [comment]
If you manually set the tileset in options.json to retrodays10 or retrodays20, does it load? Is there anything in debug.log?

**Comment by BrettDong** [comment]
`debug.log` is totally blank: 0KB

**Comment by DanmakuDan** [comment]
The game loads a tileset before the title screen appears, and the tileset memory usage will vary depending on the file size. My computer reports 200 MB RAM in use at the title screen using the smallest tileset, RetroASCII, and 600 MB RAM with ChestHole isometric. The wait before the program crashes is probably the memory manager trying to reserve memory and eventually running out.

**Comment by BrettDong** [comment]
`retrodays10` loads fine.

**Comment by DanmakuDan** [comment]
To avoid crashes like this, we should have something that prevents tileset loading until a game is loaded, or have some way of detecting out of memory errors. I think the tileset loading process has some functions that could notify about errors better. Separately, the texture duplication used for color filters could have an option to disable them for lower RAM systems. The texture memory usage could be lowered by using an openGL implementation with shaders, but compatibility could be an issue there.

**Comment by remyroy** [comment]
I started [a branch](https://github.com/remyroy/Cataclysm-DDA/tree/texture-load-progress) to delay texture loading and show a progress bar about it but my knowledge of SDL/OpenGL/Graphics is too poor to complete it :( .

**Comment by remyroy** [comment]
This is somewhat related to #16268.

**Comment by BevapDin** [comment]
@BrettDong This was recently (b192f47b1c138d79076fe54f3cffdea7d88e09d6) changed. The tileset is now loaded after the game data (the world) has been loaded, not upon game start.

Does the crash still happen?

**Comment by BrettDong** [comment]
Sorry, I am unable to test it easily now because the VM I was encountering the issue was two years ago and I’ve deleted it long time ago.
> @BrettDong <https://github.com/BrettDong> This was recently (b192f47 <https://github.com/CleverRaven/Cataclysm-DDA/commit/b192f47b1c138d79076fe54f3cffdea7d88e09d6>) changed. The tileset is now loaded after the game data (the world) has been loaded, not upon game start.
> 
> Does the crash still happen?
>

**Comment by Night-Pryanik** [comment]
My system has 1 GB RAM, and the game is starting without problems. I'm closing this now, if this problem is still an issue, ping me.
