### ISSUE TITLE
Vehicle engine continues to run without a battery

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19182]
A running Humvee spawned in the middle of several zombies, which started bashing it. Even though it has a faulty engine and no longer has a battery, it continues to make exhaust and noise.

It only ceased to function after I removed its alternator.

**Comment by Coolthulhu** [comment]
It's fine if it can run on the alternator alone.

**Comment by BorkBorkGoesTheCode** [comment]
Oh, sorry. Nice to know that this works.
