### ISSUE TITLE
Foraging tiles (foilage, berry bushes, trees) are resetting outside of the reality bubble

### ISSUE THREAD

**Issue by MisterFox** [CleverRaven/Cataclysm-DDA#19196]
I have been encountering this bug over the last dozen builds or so -- currently on 5835.

If you forage/pick trees/whatever and then leave the reality bubble and come back, the tile will have reset and allow you to harvest it again.

**Comment by Oskar636** [comment]
Can confirm, but it would be good for someone to investigate since what build does this bug exist. I can do it tomorrow.

**Comment by Oskar636** [comment]
I guess no need for me to check this now.
