### ISSUE TITLE
You squeeze the pheromone ball... ...but nothing happens. 100% of the time.

### ISSUE THREAD

**Issue by DeviateScaleCodpiece** [CleverRaven/Cataclysm-DDA#19195]
What's the point of this item if it never works?

After losing a character to a zombie tank due to trying to pheromone it peaceful, I started a new character up and wished 100 pheromone and all stats up to 10, thinking that skill was the issue.  

Wished it clear, sunny, rainy, all the weather under the sun, thinking maybe weather was washing the pheromones out of the air, but no dice.   There may be some reason that I'm missing why it doesn't work, but even if there *IS* a reason, there's no excuse for the lack of feedback to the player as to the *WHY* of it, especially at higher skill levels.

**Comment by Coolthulhu** [comment]
```
if( critter.type->in_species( ZOMBIE ) && critter.friendly == 0 && rng( 0, 500 ) > critter.get_hp() ) {
```

That last part is important here - chance scales down with zed's HP.
We could add a message saying something like "x shrugs it off", but that wouldn't still explain what it's all about.

**Comment by DeviateScaleCodpiece** [comment]
There's also the worry that using the pheromones in a crowd would spam the player's chat log with hundreds of "x shrugs it off!" messages, but an attempt -> fail message would get the idea across.  Thanks for letting me know about that with the chance scaling though.  With a tank's 650 HP, the chance of making it friendly was absolutely 0%, if 500 HP's the max range, thus my confusion.

**Comment by DeviateScaleCodpiece** [comment]
Closing this issue so as not to clutter the open issues, given this has been up for a week. If anyone wants to discuss this further, they can re-open it. c:
