### ISSUE TITLE
5x50 hull multiplication

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19198]
Any ammo casing using the old system is spawning in full stacks instead of individually when a cartridge is fired.

**Comment by hmstanley** [comment]
Yea, this is happening with 30mm, 120mm and other non standard ammo, mostly from tank mod that I use. Also, you can create new ammo belts from linkages, which I've already filed.

**Comment by BorkBorkGoesTheCode** [comment]
When the ammo links were generified, their count was removed.

**Comment by BorkBorkGoesTheCode** [comment]
A better description for issue: Whenever a 5x50 firearm is fired, 200 casings are spawned for every bullet, leading to giant piles of thousands of casings.
