### ISSUE TITLE
Problems with filling Vehicle Tanks

### ISSUE THREAD

**Issue by Kadian** [CleverRaven/Cataclysm-DDA#19199]
Version: 0.C-19545-g2a30efe / build: 5844

I was building my own Vehicle and added those 'shiny' generic Vehicle Tanks which are supposed to be refillable with all kinds of liquids. I then wanted to start filling those Tanks and...i can't.

I then went and used the debug functions to quickly do some testing. I built the following Vehicle Tanks:
60L , 2L , 20L , 10L as well as the external Tank with 200L.
Then I grabbed myself the following liquids - all of them in a container of course:
Water ; Clean Water ; Salt Water ; Gasoline ; Diesel ; Liquid Fertilizer ; Hydrogen Peroxide.

I couldn't fill any of the above liquids in any of the above tanks. As you can see, i not only tried the usual suspects (water, gas), but also some more random liquids one should be able to fill into the tanks, and neither seem to work.

What happens is the following:
I press (f) in the Car menu, in order to 'refill'. It then highlights the tanks in the list and I am able to choose a specific tank from the list I want to refill. After choosing a specific tank I go to my inventory menu where all the Containers with Liquids are listed and I choose one from the list. Then it goes...back to the Car menu and nothing happened. The Tank is still empty, and my container is still full.

As another test I installed a few funnels into my vehicle, just to test if they can be filled at all, and yes, the tanks will fill up when they are installed directly under the Funnel. You can then proceed to purify it by using a FOODCO kitchen buddy, and siphon the tanks as well.

Anything obvious I'm missing here? Looks like a bug to me, if I'm honest.

EDIT:
Tested in 0.C-19551-gc5ccca3 / 5849 ; This bug persists.

**Comment by Kadian** [comment]
Heya, small update from me: First off, newest Version (0.C-19554-g658421 / Build 5851) still has this bug (at least for me), no big surprise there I guess.
However, after playing a little bit around, i found out the following:
You can indirectly fill the Tanks of a Vehicle by unloading the Container with the liquid. I tested this with Napalm, mineral water, water and diesel, seems to work fine.

Considering this, could there be a problem with the refill option in the Car Menu (the very menu that shows up when you build on the car and/or examine it. Just to be clear.) ? The option could have been broken when the change to the tanks was made.

Hope this little bit of extra information helps :)

**Comment by ussdefiant60** [comment]
Note: Refill seems to be borked whether you select an empty tank or a tank that already has the stuff you're trying to load in it

**Comment by mugling** [comment]
Can reproduce although as yet I'm uncertain when or why this became an issue
