### ISSUE TITLE
Cannot correctly find resources for crafting

### ISSUE THREAD

**Issue by dodomorandi** [CleverRaven/Cataclysm-DDA#19200]
I have a makeshift welder recharged through a medium storage battery, two discharged makeshift welders and I am not able to craft the vehicle welding rig. The makeshift welder for the welding is marked as green, but the two needed for the crafting are brown.

I do not know if it could be related to this problem, but having a soldering iron recharged with storage batteries gives problem when trying to repair things. The system says that there are not enough charges.

Anyways, thanks a lot for your huge work!

**Comment by FlaKougar** [comment]
I came across this issue as well,  crafted 2 makeshift welders, went to craft vehicle welding rig.   Not enough makeshift welders.  Drop one, tried again and all was fine.  Hopefully that gives a useful hint to the problem.

**Comment by Leland** [comment]
Merging into #19461
