### ISSUE TITLE
Disassembling items on some vehicle tiles without inventory results in hard crash.

### ISSUE THREAD

**Issue by Ataman** [CleverRaven/Cataclysm-DDA#19208]
As in the title, trying to disassemble anything on those tiles ends with a crash after the character finishes disassembling. Example tiles are the aisle, aisle with lights or a broken windshield. Interestingly, an open door tile results in a message about the items having vanished. I assume that's a workaround partly in place?

System: Tiles version on Windows 10
Version: 0.C-19570-g40ca413 (But it's going at least as far back as 19551) 
Reproduction steps: Spawn RV, toolbox and an item you can disassemble. Move to aisle tile, disassemble the item.

**Comment by illi-kun** [comment]
We have a fix for this issue: #19132.

**Comment by Ataman** [comment]
Alright my bad, I just checked for open issues and didn't think about the pull requests.

**Comment by illi-kun** [comment]
Don't worry about that and thank you for the report.

**Comment by Ataman** [comment]
Well, thank YOU guys for having it already fixed. :)
