### ISSUE TITLE
musts with negative enjoyability? you ever try some?

### ISSUE THREAD

**Issue by nonymous** [CleverRaven/Cataclysm-DDA#19204]
Musts are all delicious, sweet and yummy liquids that will ferment into tasty alcoholic beverages.  The only reason to give them negative enjoyability is because screw reality, we want an impossible game for no one to enjoy.

**Comment by Cyrano7** [comment]
As someone who has worked in the wine industry I wouldn't say that eating/drinking wine must is particularly enjoyable.

**Comment by Kadian** [comment]
Must is freshly pressed juice that still contains seeds, skins and stems of the fruit, not just the juice, nomymous.
Moreover, we have to assume that said fruits weren't washed before the survivor turns them into must, so the possibility is high to find dirt, bugs and other stuff in it. Do you really think this would be enjoyable to eat...?

**Comment by John-Candlebury** [comment]
As a part-time brewer, i must say thar i find wort to be rather bad tasting, as it has a: taste between very sweet and bitter. 
 its no bad tasting enough to prevent drinking, but I wouldn't really drink a glass of i

**Comment by illi-kun** [comment]
Thanks for quick reaction, everyone.
