### ISSUE TITLE
Disassembling go bag segfaults the game

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#19211]
Build 5857 (0.C-19571-ga3e200d), Linux tiles.

**Comment by sethsimon** [comment]
Were you standing on a part of a vehicle where cargo can't be stored? If so, it will be fixed by #19132.

**Comment by int-ua** [comment]
I think all three times I was standing on a part where there was no room for resulting items in a vehicle, yes.
