### ISSUE TITLE
Some blazemod JSON issues i'm pondering making PRs about, want comments

### ISSUE THREAD

**Issue by ussdefiant60** [CleverRaven/Cataclysm-DDA#19217]
First off, my apologies if i happen to be stepping on @Blaze-whatdoyoumeanitsalreadytaken  toes or anyone elses here, but theres' a few JSON issues with Blazemod i've been considering doing something about, but i wanted some advice to make sure i'm not stepping on code-related land mines anywhere before tossing them up.

**1)** Removing the duplicate Start Vehicle Construction entry in blaze_override.json . I've done this already on my personal copy and it seems to fix issue #18372 and its relatives, and the default game SVC seems to work just fine with the frames that Blazemod adds without it. Is there anything non-obvious i might be breaking by doing this? 

**2)** The fluid capsules/coccoons/pods seem like they should be easy enough to go and genericize like base game tanks are now in order to declutter the part list from the 30 things they contribute now. My question here is two-fold:

**a)** Sizes: Capsule (gelatinous mass) = 10 L, Pod (oozing mass) = 20 L, Cocoon (grey mass) = 25 L at current size values for holding gas/diesel. The Capsule/Pod numbers seem reasonable enough to just port over, given they're the first two tier of blob mod parts and match the default tanks well enough. 25 L for the cocoon seems rather odd, but it is about 7 times more durable than the 60 L tank, Leave at 25 L and call it a really durable fuel tank, or boost capacity to 60 L to match the progression of the other two blob tanks vs. vanilla ones?

b)Given that "location":"fuel_source" is walkable on, is there any reason at all for the "location":"under" versions of the tanks to exist? Can they be removed? would result in 30 parts managing to be shrunk to 3.

**3) Turrets.** The blazemod turrets technically work and shoot, but the ammo based ones have magazine sizes that are either a) Single-shot or b)precisely enough to fire one burst and then require extensive reloading time. PR #17744 and #18566 seems to have broken the intended methods within Blazemod for dealing with ammo, either by removing the cargospace that were included to drop ammo into for one set of turrets, or by breaking the ammo racks that fed the other set of turrets from anywhere in the vehicle that technically functioned as fuel tanks. I wanted to ask @mugling a couple questions about the current state of the code, given that he wrote those two PRs:

**A)** Is it at all feasible for the generic vehicle tank code to be extended/adjusted to allow for the possibility of certain tanks being flagged to hold solids instead of liquids? Turrets in general being able to reload ammo and theoretically switching which type of ammo they're shooting ala the sprayable fungicide/water from the water cannon would be a fine thing, i think. Would also open the possibility the genericizing the 14ish blazemod ammo racks into one.

**B)** The non-elegant solution to the above Empty In One Shot/Burst issue (since the CARGO flag is apparently no longer a thing on turrets) would be for me to take the unmounted versions of the Blazemod turret weapons and extend their magazines to hold the amount of ammo a turret with CARGO could hold before (which i believe is 4 L worth of ammo)? Does this sound like a feasable solution to apply to those weapons that specifically state in their descriptions they need to be mounted on a turret before firing?

4)Fix Issue #18537 : Easy enough, should just need me to change it to a gel_sickle or gel_razor ID, right?

**Comment by Oskar636** [comment]
If you think you can do it, make pull requests ( but make them seperate for diffrent issues ). If the code happens to brake something we* can only see it then. I don't see any problem with fixing issues, implementing content is diffrent. And remember to test it yourself first.

*By we I mean people who work with the code.

**Comment by mugling** [comment]
> I wanted to ask @mugling a couple questions about the current state of the code, given that he wrote those two PRs:
> 
> A) Is it at all feasible for the generic vehicle tank code to be extended/adjusted to allow for the possibility of certain tanks being flagged to hold solids instead of liquids?

It's possible. Can you give some examples preferably with reference to existing JSON?

**Comment by ussdefiant60** [comment]
so, my apologizes for leaving this for so long, but a combination of RL events and a 2-week long flu left me in no shape to be working on anything.

I should be uploading a PR to address item 2 as soon as Git finishes cloning the repo so i can make a commit.

as far as @mugling 's question goes, i was specifically thinking about the large number of "BLAH rack" items in blazemod\blaze_other_parts.json . ATM its ignoring fuel_type completely (which may or may not be WAD), and you can only load liquids into the things. It'd be nice to, say, be able to genericize all those entries into an ammo bin that a vehicle turret can take ammo from in the same way that water cannons take water from tanks currently. It'd be a nice fix to the current issue with the Blazemod turrets only being able to fire one shot/burst before having to be manually reloaded.
