### ISSUE TITLE
Cannot refill fuel tanks from bottles

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#19228]
Using other vehicles or a gas pump seems to work as intended.

**Comment by Oskar636** [comment]
Can't reproduce in build 5864. What do you exactly mean by this? It doesn't allow you, it doesn't show you the bottle when you select fill, it shows a debug message? Are you sure you're using the " most current " version, any mods?

**Comment by pisskop** [comment]
when youre right youre right.  I updated and it worked fine.
