### ISSUE TITLE
The "find my dog" mission is being finished incorrectly, the dog won't be given to its owner

### ISSUE THREAD

**Issue by BFG1992** [CleverRaven/Cataclysm-DDA#19220]
In the mission where you must find and retrieve a dog for an NPC the dog will stay with you (friendly) even when the mission is completed and appears in Completed missions tab. Also, if this dog gets killed, the mission will be failed too, making it appear in _both_ Completed and Failed tabs.

**Comment by DangerNoodle** [comment]
For the first part, it might require some way to change what entity (player, NPC, or monster) a friendly creature is set to follow.

**Comment by tsulh** [comment]
The issue is still present, I just experienced the same problem after I delivered a cat to Clarie Isherwood (NPC that lives on a farm). The quest is completed, but the cat is still mine.

**Comment by tsulh** [comment]
I wanted to edit the cat owner in the save files. This is what I found when searching for the cat's unique name, and I don't understand how to change an owner here. Is it even possible now for a pet to follow an NPC?

{ "moves": 0, "pain": 0, "effects": { "pet": { "bp_null": { "eff_type": "pet", "duration": 1, "bp": "bp_null", "permanent": true, "intensity": 1, "start_turn": 7674898, "source": { "character_id": -1, "faction_id": "" } } } }, "damage_over_time_map": [  ], "values": {  }, "blocks_left": 1, "dodges_left": 1, "num_blocks_bonus": 0, "num_dodges_bonus": 0, "armor_bash_bonus": 0, "armor_cut_bonus": 0, "armor_bullet_bonus": 0, "speed": 150, "speed_bonus": 0, "dodge_bonus": 0.000000, "block_bonus": 0, "hit_bonus": 0.000000, "bash_bonus": 0, "cut_bonus": 0, "bash_mult": 1.000000, "cut_mult": 1.000000, "melee_quiet": false, "throw_resist": 0, "body": { "head": { "id": "head", "hp_cur": 60, "hp_max": 60, "damage_bandaged": 0, "damage_disinfected": 0, "wetness": 0, "temp_cur": 5000, "temp_conv": 5000, "frostbite_timer": 0 }, "torso": { "id": "torso", "hp_cur": 60, "hp_max": 60, "damage_bandaged": 0, "damage_disinfected": 0, "wetness": 0, "temp_cur": 5000, "temp_conv": 5000, "frostbite_timer": 0 } }, "typeid": "mon_cat", "unique_name": "Joshua", "posx": 69, "posy": 61, "posz": 0, "wandx": 70, "wandy": 60, "wandz": 0, "wandf": 107, "hp": 12, "special_attacks": { "scratch": { "cooldown": 0, "enabled": true } }, "friendly": -1, "fish_population": 1, "faction": "cat", "mission_ids": [ 21 ], "mission_fused": [  ], "no_extra_death_drops": false, "dead": false, "anger": -99, "morale": -100, "hallucination": false, "stairscount": 0, "destination": [ 0, 0, 0 ], "ammo": {  }, "underwater": false, "upgrades": false, "upgrade_time": -1, "last_updated": 7674728, "reproduces": true, "baby_timer": 12858728, "biosignatures": false, "biosig_timer": -1, "udder_timer": 7674728, "summon_time_limit": null, "inv": [  ], "dragged_foe_id": -1, "mounted_player_id": -1, "path": [  ] }

**Comment by LyleSY** [comment]
As far as I can tell there is no code to do this yet. A u_sell_monster flag would need to be created. This could be handy in other areas like Isherwood

**Comment by I-am-Erk** [comment]
I think we now have the ability to transfer monster ownership, but I may be mistaken there. If not this is almost worth making a blocker out of, as we have all the necessary framework
