### ISSUE TITLE
Minireactor installed to vehicle can't be filled

### ISSUE THREAD

**Issue by LlubNek** [CleverRaven/Cataclysm-DDA#19229]
While a minireactor can be reloaded with plutonium cells in the player's inventory, it can't be filled when installed to a vehicle, and doesn't retain it's charge when installed.

You can test this by spawning a bubble car and driving it.  The minireactor will spawn empty, quickly die and die again as soon as it's reactivated, and the car's battery will quickly discharge.  When you examine the vehicle, you can select the reactor to refuel, and it will allow you to select plutonium cells from your inventory, but they aren't actually loaded into the reactor.  Adding plutonium cells to a nearby cargo space, even in the same tile, doesn't work either.  I haven't been able to load an installed tank with plutonium slurry, but I doubt that works either.

Observed in version 0.C-5854 on Windows.

**Comment by mugling** [comment]
> While a minireactor can be reloaded with plutonium cells in the player's inventory, it can't be filled when installed to a vehicle, and doesn't retain it's charge when installed.

I can't reproduce any of these

**Comment by LlubNek** [comment]
Looks like this has been fixed.
I just tried filling a bubble car reactor in 0.C-5972 (Windows tiles build from the website), and it worked.
