### ISSUE TITLE
The V menu (list items) reports the incorrect item information

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#19232]
When there's more than one of a particular item around you, you can use the left and right arrow keys to scroll through all of them (the entry looks like `[1/38] (38) cash card`).However, the window at the bottom (where charges, price, weight, the item description, etc are shown) will always have the same information as it did for the first item. Similarly, if you try to examine any of the 38 items via `e`, it will show the first item's information instead.

**Comment by Leland** [comment]
Interesting, combining with #12228
