### ISSUE TITLE
Style not active?

### ISSUE THREAD

**Issue by charmstruck** [CleverRaven/Cataclysm-DDA#19234]
The style "Medieval Swordsmanship" is not active while wielding a replica Zweihander.

**Comment by illi-kun** [comment]
Are other styles work with replicas?

**Comment by charmstruck** [comment]
Confirmed that Niten Ichi-Ryu doesn't work with either of the replica katanas

Do you know if this is intentional or an oversight?

**Comment by BorkBorkGoesTheCode** [comment]
Since the arming sword has different volume, oversight.

**Comment by Leland** [comment]
Inferior weapons were added with #19927 – however, doesn't look like fakes should activate the requisite skill.
