### ISSUE TITLE
Default Starting Season Should be Autumn

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#19231]
Instead of the freezing spring, the defaults starting season should be autumn.

Reading here for the original discussion for the idea. -> http://smf.cataclysmdda.com/index.php?topic=13638.msg288069#msg288069

But to put is quickly:

 * Autumn will allow players to have to deal with both heat and cold
 * Autumn is not initially freezing at night, allowing players to run from zombies at the point when they are least capable of dealing with them.
 * Autumn Allows for less growing time, immediate farm setup, and allows for mods to make winter harsh and food conservation relevant.
 * Autumn starts Are not extreme like spring can be.  Not onslaught of rain, no freezing.

Autumn will allow use to utilize dodging more effectively since we wont be freezing.  Im not sure how feasible it is wrt the hardcoding of the game, but this would fix a lot of issues people seem to have with the earlygame.

**Comment by pisskop** [comment]
Ill take the silence as there being no dissent.

**Comment by Coolthulhu** [comment]
Sounds OK.
Spring has multiple disadvantages, like freezing the player when it is the most inconvenient (at start), going into summer (hardest season to pick armor for) and not dropping food from trees or shrubs yet.

One problem here is that winter is a bad season for food gathering, meaning the player won't have the time to prepare and will need to rely on early drops. Or just tank it and starve until spring (which is actually doable).

As for hardcoding: we only need to change the default value of an option.

**Comment by pisskop** [comment]
Spring starts give you time to find low warmth armor.

Autumn gives you time to get high warmth armor, but since youll have the same amount of time to do so the option to layer clothing as a subpar alternative isnt a bad thing.  the issue there being that a player will usually have access to kevlar vests for summer and usually be able to get sable coats for winter.


the lack of food is not a bad thing.  It add midgame pressure and then when summer rolls around in season 4 the endgame monsters are appearing with frequency.  this will also help encourage some farm reworking perhaps?  Since people will need food and farming is a great way to get it.

**Comment by Coolthulhu** [comment]
Farming from autumn is not going to happen. It's just one season and also the most important one (the first). At this point it's just gathering.

We could add some easy mode food to winter, like rare tubers (could be just wild veggies), burrowed maggots and edible moss, but that would risk turning winter into just another season when it comes to food.

Autumn starts would probably be a bit harder than spring starts (early game is one of the few parts of the game that shouldn't get harder), but could be more balanced.

**Comment by pisskop** [comment]
On the plus side, all fresh food that makes it to winter will stay preserved. Scavanging in winter will be viable

**Comment by pisskop** [comment]
Changing the default season doesnt prevent rot from starting at spring.

**Comment by pisskop** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/67668987fee36729cac0c24d9d7c99e8a29063a8/src/weather.cpp#L57
I think this is what determines rot from delayed seasonal starts.

https://github.com/CleverRaven/Cataclysm-DDA/blob/67668987fee36729cac0c24d9d7c99e8a29063a8/src/mongroup.cpp#L14
This determines if zombie-mid is used as a mon_group or not.  Other groups could in theory be used but currently zombie_mid is the only transitional group.

**Comment by WizardOfOoo** [comment]
I think we would have a lot more people dying from starving.

**Comment by kevingranade** [comment]
5 months have passed, discussion is far past done.
