### ISSUE TITLE
Fence gates cannot be opened

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19248]
It's been bugging me for a while: why aren't fence gates treated like doors?

**Comment by Oskar636** [comment]
Related to #12210. Do you mean the tile " closed wooden gate " or which one? I can open the tile i referenced with the letter "o". And possibly because you can climb over them.

**Comment by BorkBorkGoesTheCode** [comment]
I meant the closed picket fence gate. The behavior I expected is automatic door opening a la doors. It makes more sense for the player to open the gate when moving past instead of vaulting over.
