### ISSUE TITLE
Update http://cdda-trunk.estilofusion.com

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#19242]
How can we update the item browser and hook it back to experimental builds?  Is that something, someone like me could do?  I think it would help immensely if this followed all builds.

**Comment by remyroy** [comment]
The item browser is maintained by @Sheco on https://github.com/Sheco/cdda-itembrowser . You should try to get in touch with him.

**Comment by hmstanley** [comment]
Ok. I wrote him.  Nothing back. I wonder if we can take over the code and push it to the website ourselves?

**Comment by remyroy** [comment]
I'm pretty sure the author is also the owner of the website. We cannot simply push content to something we do not own.

Try to get in touch with the author again. Try different channels.

**Comment by DanmakuDan** [comment]
I'm currently taking a look at it. The backend uses PHP to build the indexed data, and some code needs to be updated to handle all the json structure changes since it was last used. @Chezzo wants to host it when it gets fixed.

**Comment by DanmakuDan** [comment]
I have a mostly working update in http://cdda-trunk.chezzo.com. I am still working on figuring out what configuration details need to be updated in my fork.

**Comment by remyroy** [comment]
Well done.
