### ISSUE TITLE
Steel spear (probably all spears) diagonal attack bug

### ISSUE THREAD

**Issue by Neversalimus** [CleverRaven/Cataclysm-DDA#19258]
By pressing F key, you can only attack diagonally adjacent enemy(near you), but pressing Tab you can also attack enemy 1 diagonal tile away, which otherwise is not possible if you press F key.

**Comment by Reclusive-reptile** [comment]
Circular distances cause this bug. Every time it's been brought up no one has  one up with a good solution.

**Comment by Neversalimus** [comment]
ahh sorry for  duplicating(

**Comment by DangerNoodle** [comment]
Does it work as expected if circular distance is disabled? The obvious solution would be for circular distance to explicitly not affect reach attacks.

**Comment by Leland** [comment]
Duplicate of #16400
