### ISSUE TITLE
Misleading Dexterity Stats in Character Screen

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#19256]
Latest experimental as of now, when looking at "Dexterity" in the character screen, it claims 14 dexterity will grant me a Melee to-hit bonus of "-1610612736".

Luckily, this doesn't seem to affect my actual melee to-hit bonus.

**Comment by BrettDong** [comment]
Are you sure you're playing the latest experimental? I've fixed this problem in #18941.

**Comment by harald921** [comment]
Haha, well. It was the latest available according to the CDDA Game Launcher when I played. Updating to check how it is now.

**Comment by Oskar636** [comment]
Next time please post number of build so we can have a reference.

**Comment by WizardOfOoo** [comment]
I can't repro it.

**Comment by illi-kun** [comment]
@harald921 So, what's th status of this issue? Did you check the latest experimental version?

**Comment by BorkBorkGoesTheCode** [comment]
I can confirm it. exp 5883 Dexterity 20: -1073741824

**Comment by mutability** [comment]
It is one of the format problems listed in #19276 

```
src/player.cpp:2976:82: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘double’ [-Wformat=]
                     mvwprintz( w_stats, 6, 22, c_magenta, "%+3d", get_hit_base() );
```
