### ISSUE TITLE
Hearing overflow crash

### ISSUE THREAD

**Issue by Neversalimus** [CleverRaven/Cataclysm-DDA#19259]
Z-levels enabled
Hordes enabled
How to reproduce:
Aggro the horde, barricade the basement so the zombies cant get to you, than sleep a lot without moving(so the markers do not disappear), its like 20-30 ingame hours to crash the game.
Sometimes it is randomly crashing after 3-4 hours(depend on amount of moves zombies make)

**Comment by pisskop** [comment]
I get a crash in the early early game as I flee a burning building in the middle of a city.  Zombies smashing walls and dressers and cars and the things dying all over.

I guess its this?

**Comment by codemime** [comment]
Could you upload a saved game (just before the crash)?

**Comment by sethsimon** [comment]
I followed the reproduction instructions several times, and came across 3 different parts of the code that cause a crash (#19756, #19749, and an active item processing crash that I'll open an issue for if I can't figure it out). 
@Neversalimus Do you have anything like an error message, backtrace, or a savegame from just before the crash (by setting auto-save to the smallest possible interval)  so we know which of these (or maybe it's something else) you're experiencing?

**Comment by codemime** [comment]
Fixed in #20010.
