### ISSUE TITLE
Non-magazine weapons reloading one at a time, regardless of RELOAD_ONE flag

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#19264]
Discovered in Windows graphical build 5862, tested with BB gun, weapons from Arcana and Magic Items (first discovered while checking for anomalies to be discussed in https://github.com/CleverRaven/Cataclysm-DDA/pull/19247).

I am uncertain when this bug was introduced.

**Comment by mugling** [comment]
Can you adjust the amount with left and right key?

**Comment by DangerNoodle** [comment]
There is only a prompt to select source and type of ammunition when first loading an empty weapon. From then on, further keypresses automatical load another single round, without any prompt. Which is, last I checked, how 'RELOAD_ONE' firearms work.

**Comment by chaosvolt** [comment]
Tested and confirming, it seems on the first prompt you can indeed load multiple via left/right, but only if the weapon is empty. Reloading a partially-full weapon still only works one at a time.

Still, that is needless tedium when "reload fully" should still be an option for non-magazine weapons.
