### ISSUE TITLE
Bug: all cash card drops have 0 cash on them

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#19266]
Game version 5870

Started a new game and the next 6 or 7 cash cards had 0 cash on them.

**Comment by Oskar636** [comment]
Duplicate of #16885 next time please search if there are already open issues for your bug, or maybe even closed ones.

**Comment by ZenZen2** [comment]
Sorry. I wasnt sure if thats already fixed. Because the 2000000 card was a rare drop and all other cards were ok. Now all are 0.
