### ISSUE TITLE
Compile Error on OSX

### ISSUE THREAD

**Issue by FlaKougar** [CleverRaven/Cataclysm-DDA#19278]
src/overmap.cpp:247:38: error: no member named 'accumulate' in namespace 'std'
    const size_t actual_count = std::accumulate(  specials.get_all().begin(), specials.get_all().end(), 0,
                                ~~~~~^
1 error generated.

**Comment by chrzyki** [comment]
Should be fixable by `#include <numeric>` in overmap.cpp.
