### ISSUE TITLE
Seats with CARGO prevent any turret installation

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19270]
When a normal or reclining seat is installed on a vehicle, the option to install any mounted weapon on the seat square is removed. The error affects vehicle spawns. 
Wooden seats without CARGO and blazemod seats are unaffected.

**Comment by mugling** [comment]
What error message?

**Comment by BorkBorkGoesTheCode** [comment]
Silent unless vehicles spawn with seats+turrets, as in #19185 .

**Comment by mugling** [comment]
Yes, so what message?

**Comment by BorkBorkGoesTheCode** [comment]
Vehicle spawn error:

DEBUG       : init_vehicles: 'Infantry Fighting Vehicle' part 'mounted_m240' (foo) can't be installed to x,y

FUNCTION : static void vehicle_prototype::finalize()
FILE            : src/veh_type.cpp
LINE           : 662

The above error ceases to appear if CARGO is removed from seat which is installed under a mounted gun.

**Comment by mugling** [comment]
No you're getting that error because the `location` of `seat` is conflicting with another part on that tile - it doesn't have anything to do with `CARGO`

**Comment by BorkBorkGoesTheCode** [comment]
@mugling, machine guns can be installed normally if CARGO is removed from the seat entry.

**Comment by mugling** [comment]
I tested that you can install `seat` and `m60` on the same tile

**Comment by BorkBorkGoesTheCode** [comment]
I have replicated your test successfully using a fresh world without game mods enabled. The error appears within a world with blazemod+tanks mods.

**Comment by mugling** [comment]
Your problem is other conflicting parts

**Comment by BorkBorkGoesTheCode** [comment]
I found the conflict: Blazemod has duplicate mounted weapons with CARGO flags in blaze_override.json. The turret cargo flags are conflicting with the seat cargo flags.
