### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by VZIKL** [CleverRaven/Cataclysm-DDA#19284]
src/overmap.cpp 247:38 error no member named accumulate in namespace std

**Comment by jaked122** [comment]
I'm getting this too.

It looks like someone screwed up the includes here.

**Comment by ChucklesTheBeard** [comment]
:+1: I'm also getting this.

**Comment by ChucklesTheBeard** [comment]
Duplicate of #19278

**Comment by codemime** [comment]
Needs to be closed.
