### ISSUE TITLE
Crafting issue with water

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#19301]
Version: Exp 5881

When 
1. water tiles nearby

and

2. water items in inventory

exist at the same time, the crafting menu doesn't think the player has water available.

**Comment by Zireael07** [comment]
I believe this is a duplicate and that the problem is due to an overflow... @mugling? @codemime? Can you find the original issue?

**Comment by ZenZen2** [comment]
looks like duplicate of #18709

(how do i link?)

**Comment by ZenZen2** [comment]
oh it does it automaticly :D

**Comment by Coolthulhu** [comment]
My attempt at fix: #19149

**Comment by ZenZen2** [comment]
i wish i would have your magic skills to help with the bug hunting

**Comment by BrettDong** [comment]
Oops, sorry for duplication. I typed wrong search query before I submitted this new issue.
