### ISSUE TITLE
Zombies at Night are Too good at finding the player

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#19308]
I just had a huge boomer hear my combat with a normal zombie from across the street when it was standing in front of a burning* building.

bullshit

**Comment by Coolthulhu** [comment]
Huge boomers have good hearing, meaning they can hear combat from 16 tiles away.

**Comment by pisskop** [comment]
A street is 24 tiles wide.

  In this case its following more likely following the scent of the player, weak as it should be after he fled a burning building, looted a second, and killed a monster; before leaving to see it path to the fire, mull a little, and path directly to the players direction.

  Likely I could make a case that smell is too powerful.  Theyre humans, still.  now dogs.

Its not just this one case of a boomer either.  whats likely happening is that hordes are spawning within the reality bubble, trashing some car close to the players location, and pulling more hordes in.  Since sounds dont exist outside the reality bubble, theres no competition.

**Comment by Coolthulhu** [comment]
Hordes are a separate issue.

If you were standing close to a burning building, it could have been just the light.
24 tiles would require 12 volume sound, which could happen if the zombie bashed something nearby, like a glass shard on the ground.

Scent is actually quite weak, except for chasing. Debug in the scent sight CBM and walk around with it to see how small is the area. It gets useless during rain.

**Comment by pisskop** [comment]
Did ... did you guys finally make flashlights cost movement turns?

It might actually be that using lights is creating a chance for them to see you.

I was trailed by something that couldnt smell and couldnt hear me running as I kept flashlight flicking.  When I realized it was following me I kept running but stopped flicking and it stopped.  Ive repeated it a few times now too....

**Comment by Coolthulhu** [comment]
It may be, but you'll need to show that it is first. In my tests it looked pretty bad.

**Comment by kevingranade** [comment]
Almost certainly due to flashlight flicking, RIP magic nighttime vision.
