### ISSUE TITLE
Reload eject weapons eject no casings

### ISSUE THREAD

**Issue by Reclusive-reptile** [CleverRaven/Cataclysm-DDA#19300]
Spawn S&W 610 and .40 S&W ammo. Load the gun and fire away. Reload and mourn the casings that have vanished into the aether.

**Comment by BorkBorkGoesTheCode** [comment]
Confirmed with a Ruger LCR .38, so it isn't a mod conflict.

**Comment by DangerNoodle** [comment]
Odd. I thought they were being placed into your inventory?

**Comment by BorkBorkGoesTheCode** [comment]
A similar problem affects the brass catcher: http://smf.cataclysmdda.com/index.php?topic=13672.msg288545#msg288545

**Comment by Reclusive-reptile** [comment]
> Odd. I thought they were being placed into your inventory?

They are supposed to do just that, but currently spawn no casings at all. I suspect the change of casings from ammo to generic is to blame. The code is probably expecting the wrong item type.

**Comment by pisskop** [comment]
this isnt an issue w/shotguns, iirc

**Comment by DangerNoodle** [comment]
Odd. I recall that shotgun hulls are defined slightly differently. What changes are unique to them? That might prove diagnostic.

**Comment by pisskop** [comment]
see '12 gauge pistol'

**Comment by DangerNoodle** [comment]
I will attempt to test it in the build I presently have on my desktop (5862), then double-check that the bug is present in that build (not sure when it first cropped up). If both are confirmed, I will look at the JSON entry for 12 gauge shotgun hulls.

**Comment by DangerNoodle** [comment]
Problem. In said build, shotgun hulls are indeed affected by this bug. I assume I will need to test a newer build, but I will need to be out and about soon.
