### ISSUE TITLE
Default inventory navigation keybindings should be pgup/pgdn

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#19306]

**Comment by codemime** [comment]
This was already [outlined](https://github.com/CleverRaven/Cataclysm-DDA/pull/19230#issuecomment-260298272) in #19230. No issue was created, through.

**Comment by codemime** [comment]
Needs a confirmation. Have you checked your keybindings?

**Comment by macrosblackd** [comment]
You're right - it looks like the keybinds aren't pgup/pgdn by default. Any way we could add those to the defaults?

**Comment by Leland** [comment]
Closing in favor of #12112
