### ISSUE TITLE
Interest in a revised main menu CDDA logo?

### ISSUE THREAD

**Issue by OzoneH3** [CleverRaven/Cataclysm-DDA#19313]
The current one feels a little boring after 3 years. Maybe even change the colors up a bit?! (Sprinkle in a little blood or something)

WIP:
![](http://i.imgur.com/MQmuYQ3.png)

**Comment by BorkBorkGoesTheCode** [comment]
The palette looks good; the pixel count needs to be increased.

**Comment by karols146** [comment]
I like old logo,  that old Ascii style is just perfect for Cata.

**Comment by Rivet-the-Zombie** [comment]
I like the original, but this is also nice.

**Comment by harald921** [comment]
I'd rather see a "HD version" of the one that is in right now, if anything else. I actually really like it!

**Comment by cosmiccoincidence** [comment]
This has been closed for a long time, but I actually really like this.

**Comment by OzoneH3** [comment]
I actually used this later for the Halloween theme #26306
