### ISSUE TITLE
Bashing type weapons getting damaged too easily ?

### ISSUE THREAD

**Issue by Sirdec** [CleverRaven/Cataclysm-DDA#19319]
Current survivor just made a nail bat. After 3 hits on a Z, the weapon got damaged by the force of the blow.

Same thing happened to earlier survivors with stuff like 2 by 4, or even a hammer !!!

Meanwhile my trench knife is still perfectly fine after a good hundred kills using it. This doesn't feel right at all.

**Comment by Rivet-the-Zombie** [comment]
It's not whether they're blunt or sharp; it's that a trench knife is made of stronger materials and is made to hit people with, so it's a lot more durable (it's got a special flag for this purpose) than an improvised weapon like a stick.

**Comment by ZenZen2** [comment]
baseball bat broke after 2 hits, but after repairing it and improvissing to ++ it didnt break after around 30 zombies yet

**Comment by pisskop** [comment]
the more annoying part is how random it feels.

but also a weapon that blocks attacks will be rolling for damage a lot more

**Comment by mugling** [comment]
No obvious course of action. If someone wants to make a specific suggestion can be reopened
