### ISSUE TITLE
Dynamic Spawn "Questgiver" NPCs are mug-proof until their missions complete or fail

### ISSUE THREAD

**Issue by Taberone** [CleverRaven/Cataclysm-DDA#19318]
"Questgiver" NPCs absolutely cannot be intimidated through dialogue until you either complete or fail (probably by lying to them and getting caught) their missions.

You can reproduce this by running into a dynamic spawn NPC and seeing if the first thing he'll do upon chatting with you is to give you a mission to kill his zombie mother, kill a jabberwock, get him antibiotics, etc. 

You could always accept the mission and then lie about it, but that would be particularly dangerous when you're in the middle of a forest and a NPC is asking you to kill a jabberwock. Accepting results in the Jabberwock spawning nearby.

It would take less keypresses to mug a questgiver if I could simply intimidate him right away. Something like this:

<a href="http://imgur.com/Crp1IVq"><img src="http://i.imgur.com/Crp1IVq.png" title="source: imgur.com" /></a>

**Comment by Coolthulhu** [comment]
Would be better solved by removing the whole important quest thing or only allowing it to be important the first time the player talks to the NPC.

**Comment by kevingranade** [comment]
Fixed by #28050
