### ISSUE TITLE
Left/Right sound triggers only function on main menu

### ISSUE THREAD

**Issue by Leland** [CleverRaven/Cataclysm-DDA#19311]
The main menu's [left/right movements](https://github.com/CleverRaven/Cataclysm-DDA/blob/ede2ddb8887daa551c911f62cc46b5495295747b/src/main_menu.cpp#L387-L394) sound triggers currently only occur on base menu items.

That is to say, secondary menu items do not have a noise triggered. E.g. opening "Special" from the home screen and then moving between "Defense" and "Tutorial."

**Comment by illi-kun** [comment]
We don't have a dedicated label for Sound / SDL issues, so interface is the best label from available pool, IMO.
