### ISSUE TITLE
Display doesn't consistently refresh

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#19317]
I am not sure if its intended.
As long as you sleep your screen frezzes. Window where you chose how long you sleep doesnt close until you wake up.

**Comment by Coolthulhu** [comment]
Do you have force redraw disabled?

**Comment by hmstanley** [comment]
Seen this bug too. And no, don't have force draw enabled. In current windows tiles build.

**Comment by Coolthulhu** [comment]
> And no, don't have force draw enabled.

That's expected behavior then.

**Comment by hmstanley** [comment]
Oops. Sorry Cool, I did have force draw enabled. My bad.

**Comment by ZenZen2** [comment]
force redraw is enabled

**Comment by pisskop** [comment]
The issue I have with sleeping is when I dont have a watch on.  perhaps we do need a more native way of seeing time progress without a watch.

**Comment by Shoes01** [comment]
Isn't there the sun/moon indicator? Otherwise, I think you're supposed to be unsure about how much time has passed.

**Comment by pisskop** [comment]
im more talking about waiting for the world to sim.

**Comment by kevingranade** [comment]
ideally this would blank the entire display, possibly show a simple spinner
to let you know it's working, and progress very rapidly.  you aren't
supposed to be aware of your surroundings while sleeping.

**Comment by mutability** [comment]
The OP's problem is probably just an outright bug in the force-redraw stuff: it does nothing to make a SDL build actually refresh the screen. draw() redraws everything to the backing buffer, but those changes only make it to the real display in try_sdl_update, which is generally only called while waiting for user input.

**Comment by ZenZen2** [comment]
Thanks mutability

**Comment by Xpyder** [comment]
I think it would be cute if it played some kind of screen saver graphic, like sheep hopping a fence or something to make it clear that you are sleeping and that the game isn't frozen

**Comment by BorkBorkGoesTheCode** [comment]
>ideally this would blank the entire display, possibly show a simple spinner
to let you know it's working, and progress very rapidly.  you aren't
supposed to be aware of your surroundings while sleeping.

Some people can notice their environment while asleep; some others can will themselves to wake up at a specific time.

**Comment by illi-kun** [comment]
> some kind of screen saver graphic, like sheep hopping a fence

Sheeps?
![sheep-56](https://cloud.githubusercontent.com/assets/5421954/20734223/213fca78-b6a9-11e6-9f98-ed1017280324.PNG)

We need Zheeps!
![zheep](https://cloud.githubusercontent.com/assets/5421954/20734225/26ce437a-b6a9-11e6-9caa-e0a68c368301.PNG)

**Comment by ZenZen2** [comment]
haha The Sheep idea is funny :)

I am happy the fix is merged, i didnt test it yet. But the problem wasnt only on sleep but also on other things like car crafting and driving a car. For example you drive a car at fast speed and the screen would only refesh at the destination. Your car jumps and dont drive anymore. you dont get a feel for speed and can crash into somthing easly.

**Comment by mugling** [comment]
> But the problem wasnt only on sleep but also on other things like car crafting and driving a car

Reopened and retitled

**Comment by ZenZen2** [comment]
Thanks Mugling for reopening and i am sorry for not writing a better report, that could have safe some dev work.

I just tested the latest 5986:
The merge fixed Sleep.
Driving a car is still a problem, screen jumps to destination.
I also think crafting on a car is not correct here. But i might be wrong because i dont know whats intended. You can craft nonstop on a car and never leave the crafting car menu, you have to leave it to see if you are hungry or if its day or night. I am not sure if its also a screen refresh problem here. Maybe it closes and after the work is done it reopens.

**Comment by Coolthulhu** [comment]
A very important question:
Does it only affect tiles or did anyone reproduce it in console?
If it only affects tiles, that's much less code to search through.

**Comment by ZenZen2** [comment]
Thanks a lot Coolthulhu, that bug was very annyoing.
