### ISSUE TITLE
Weirdness with 3-story house: debug error thrown when approaching/loading game, no items at all inside, and no stairs down on third floor

### ISSUE THREAD

**Issue by jedibob5** [CleverRaven/Cataclysm-DDA#19325]
90% sure this is either a problem with either the "More Locations" or "Tall Buildings" mod, my best guess being the latter. Anyway, when I was out scavenging, I started to approach a particular house (none of the other buildings in the area were houses, either), and about the point where it loaded into the reality bubble,  a debug message was thrown.
![untitled](https://cloud.githubusercontent.com/assets/13815411/20409590/d799608c-acdf-11e6-97e0-e44477a6504d.png)
The message also shows up when I load the game with the house inside the reality bubble. I was able to continue the game without a crash, though when I actually got to the house, there were absolutely no items inside. All of the furniture was there, but no items (except for the water in the toilets, funnily enough) had spawned. When I got to the third floor, I found that it had no stairs downward, so I had to debug in a downward staircase to be able to get out without jumping off the roof.

The save itself isn't very old, I started it just a handful of experimentals ago, though I keep it updated to the latest version with the launcher.

**Comment by elricsfate** [comment]
I can confirm that every multi-story house I've run into has had no items generated within.

**Comment by BorkBorkGoesTheCode** [comment]
3-story houses are in the More Locations mod. No spawn groups have been set for them.

**Comment by elricsfate** [comment]
Should the spawn groups be implemented in the More Locations mod or the regular game files? I'm guessing the mod?

**Comment by BorkBorkGoesTheCode** [comment]
@elricsfate Oh damn! I forgot to tell you how to set spawn groups.

There are already spawn groups for use with the 3-story house. They can be found in data/json/itemgroups/

There are many ways to set them in mapgen; there is the place loot method, which requires a range of x,y coordinate for every spawn Here's an example copied from the house04.json:
```

"place_loot": [
        { "group": "bed", "x": [ 4, 5 ], "y": [ 6, 7 ], "chance": 90, "repeat": [ 1, 3 ] },
        { "group": "bed", "x": [ 2, 3 ], "y": [ 14, 15 ], "chance": 90, "repeat": [ 1, 3 ] },
        { "group": "allclothes", "x": [ 7, 7 ], "y": [ 21, 21 ], "chance": 90, "repeat": [ 1, 2 ] },
        { "group": "allclothes", "x": [ 7, 7 ], "y": [ 15, 15 ], "chance": 90, "repeat": [ 1, 3 ] },
        { "group": "cleaning", "x": [ 13, 13 ], "y": [ 6, 6 ], "chance": 90, "repeat": [ 1, 2 ] },
        { "group": "dresser", "x": [ 2, 2 ], "y": [ 10, 11 ], "chance": 80, "repeat": [ 1, 3 ] },
        { "group": "dresser", "x": [ 2, 2 ], "y": [ 3, 4 ], "chance": 80, "repeat": [ 1, 3 ] },
        { "group": "fridge", "x": [ 21, 21 ], "y": [ 19, 19 ], "chance": 90, "repeat": [ 1, 5 ] },
        { "group": "guns_pistol_common", "x": [ 2, 2 ], "y": [ 13, 13 ], "chance": 5, "ammo": 90, "magazine": 100 },
        { "group": "kitchen", "x": [ 19, 19 ], "y": [ 21, 21 ], "chance": 30, "repeat": [ 1, 2 ] },
        { "group": "kitchen", "x": [ 17, 17 ], "y": [ 21, 21 ], "chance": 80, "repeat": [ 1, 2 ] },
        { "group": "kitchen", "x": [ 21, 21 ], "y": [ 20, 21 ], "chance": 60, "repeat": [ 1, 2 ] },
        { "group": "kitchen", "x": [ 21, 21 ], "y": [ 18, 18 ], "chance": 80, "repeat": [ 1, 2 ] },
        { "group": "livingroom", "x": [ 10, 18 ], "y": [ 10, 11 ], "chance": 90, "repeat": [ 1, 5 ] },
        { "group": "magazines", "x": [ 17, 17 ], "y": [ 7, 7 ], "chance": 80, "repeat": [ 1, 3 ] },
        { "group": "mischw", "x": [ 13, 13 ], "y": [ 2, 2 ], "chance": 60, "repeat": [ 1, 3 ] },
        { "group": "novels", "x": [ 7, 7 ], "y": [ 2, 3 ], "chance": 85, "repeat": [ 1, 4 ] },
        { "group": "office", "x": [ 3, 4 ], "y": [ 21, 21 ], "chance": 40, "repeat": [ 1, 2 ] },
        { "group": "office", "x": [ 2, 2 ], "y": [ 19, 21 ], "chance": 40, "repeat": [ 1, 2 ] },
        { "group": "office", "x": [ 19, 21 ], "y": [ 13, 13 ], "chance": 70, "repeat": [ 1, 2 ] },
        { "group": "oven", "x": [ 20, 21 ], "y": [ 20, 21 ], "chance": 75, "repeat": [ 1, 3 ] },
        { "group": "softdrugs", "x": [ 11, 11 ], "y": [ 15, 18 ], "chance": 75, "repeat": [ 1, 2 ] },
        { "group": "softdrugs", "x": [ 9, 9 ], "y": [ 5, 7 ], "chance": 75, "repeat": [ 1, 2 ] },
        { "group": "trash", "x": [ 19, 19 ], "y": [ 15, 15 ], "chance": 80, "repeat": [ 1, 3 ] },
        { "item": "television", "x": [ 21, 21 ], "y": [ 2, 2 ], "chance": 85 },
        { "item": "laptop", "x": [ 2, 2 ], "y": [ 20, 20 ], "chance": 3 }
      ],
      "place_monsters": [
        { "monster": "GROUP_ZOMBIE", "x": [ 2, 21 ], "y": [ 2, 21 ], "chance": 2 }
      ]
    }

```
