### ISSUE TITLE
movement seems slower with build 5892

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#19333]
Before this build, moving the character seemed fast, in that you could press up/down/right, etc and the character would move fast across the screen.  Now, this seems drastically slower?  Not sure why? I checked my settings and computer and didn't notice anything odd from the build before?

**Comment by pisskop** [comment]
???

Im not sure what you mean.  You mean character speed stat is lower?  That traveling through tiles take more movement points?

that the game is slower from move to move?  i.e. like its loading more stuff?

**Comment by hmstanley** [comment]
Yes, that's basically it. Moving through tiles is slow.

**Comment by mutability** [comment]
The only change between 5891 and 5892 was some trivial printf-related format changes, there's no way that would cause a slowdown. Can you identify the specific build that caused the slowdown?

**Comment by Oskar636** [comment]
Stating builds should be mandatory, even better with what system you have and which version you're using tiles/console, and if tiles then are you using a tileset.

**Comment by hmstanley** [comment]
Errant computer problem. Closing.
