### ISSUE TITLE
ncurses vehicle speed meter bug

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#19337]
Normal:
![2016-11-19 4 34 45](https://cloud.githubusercontent.com/assets/21075502/20454287/202731a6-ae77-11e6-9a27-1471608c4581.png)

But sometimes, after changing the speed by pressing _k_ and _j_ a few times, the display of speed meter might be messed up:
![2016-11-19 4 34 57](https://cloud.githubusercontent.com/assets/21075502/20454288/202cb41e-ae77-11e6-96a4-3bc0f5f1513d.png)
![2016-11-19 4 41 18](https://cloud.githubusercontent.com/assets/21075502/20454289/2034e9ae-ae77-11e6-802f-58cd62712ff4.png)

OS: macOS 10.12.1
Interface: ncurses

**Comment by Night-Pryanik** [comment]
Someone else encountered this?

**Comment by illi-kun** [comment]
Tried to reproduce that with 7xV12 engines but UI works properly even with really big numbers.
Maybe it's something locale depended, I dunno.

Let's close it for now. Anyone, feel free to create a new issue about that or request to re-open if it's possible to reproduce this bug.
