### ISSUE TITLE
Engines don't display enough stats

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19349]
Fallout from #19275

Engines have gotten new stats and those aren't displayed properly. It makes it impossible to properly gauge how will vehicle's stats change after installing a given engine.

**Comment by LordZanos** [comment]
Is it intentional that electric motors are considerably better than gasoline engines at the moment? Both the large/enhanced electric motors are better than a v12 in my current vehicle. Not sure if I'm missing something.

**Comment by TheMrBakit** [comment]
Just an idea. You could add a new coulun in the vehicle interface with some information like.
For the engine energy used
For the Tanks Leaking Yes/No
For Battries rechargeable Yes/No
For the Reactors On/Off
Turrets Auto/Semi-auto, Auto Target/Manual
![7679fd4aa6](https://cloud.githubusercontent.com/assets/18709806/20501461/04504354-b008-11e6-9760-f03a3ccd970f.png)
