### ISSUE TITLE
Multiple engine vehicles broken

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19346]
Fallout from #19275

Multiple engines don't work correctly - only one is active.

**Comment by mugling** [comment]
What combinations make sense? For example foot pedals and traction engine is silly. The first step I think is to allow combining of electric motors and allowing multiple manual engines. The latter is a feature we never had in the first place and would allow tandem bicycles and rowing boats?

**Comment by Coolthulhu** [comment]
Multiple identical engines should always work.
Engines with identical RPM+gearing should work (can be simplified to just identical ids).
Electric engines should work together with everything.

**Comment by mugling** [comment]
How about manual engines and electric engines?

**Comment by Coolthulhu** [comment]
We have electric bicycles already. Those should work and it would make perfect sense for them to work with no penalties.
Bikes should work perfectly with engines with lower power than them. Above that, there could be some sort of penalty. At 2x the bike's power, the pedals should only power the alternator.

**Comment by keyspace** [comment]
Revert of #19275 (Vehicle propulsion overhaul) might have made this obsolete.
