### ISSUE TITLE
Jet engines

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#19350]
How would they work? I'm thinking flames coming out the back when you thrust?

**Comment by BorkBorkGoesTheCode** [comment]
>How would they work? I'm thinking flames coming out the back when you thrust?

They would also require an air intake to collect oxygen: The player would need to prevent the unwanted entry of woodland creatures into the air intake.

**Comment by Oskar636** [comment]
@BorkBorkGoesTheCode Or not and use it as a meat grinder! But I think that would break it :(

**Comment by mutability** [comment]
If you want belching fire what you need is a pulsejet.. http://aardvark.co.nz/pjet/gokart.htm

**Comment by mugling** [comment]
How do we handle (or not) jet engines unevenly placed about the pivot?

**Comment by Coolthulhu** [comment]
That would require reworking how is vehicle velocity handled first.

**Comment by mutability** [comment]
Turboshaft engines are essentially jets that provide mechanical output rather than direct thrust from the exhaust, maybe that's a simpler model. (used on e.g. helicopters)

**Comment by BorkBorkGoesTheCode** [comment]
>Turboshaft engines are essentially jets that provide mechanical output rather than direct thrust from the exhaust, maybe that's a simpler model. (used on e.g. helicopters)

Also tanks.

**Comment by karols146** [comment]
Today jet engines 
Year later I just waiting for CDDA-Space Conquest :D 
Btw about jet engines, They need highly compressed air, and fuel at high pressure. I think firstly we can think about turbines itself. There was even one turbine [car](https://en.wikipedia.org/wiki/Chrysler_Turbine_Car) (only one If i get it right)

**Comment by illi-kun** [comment]
Why do we need these engines at all?

**Comment by mutability** [comment]
Any self-respecting mad-max-style deathmobile needs a jet engine!

more seriously, pulsejets could be a relatively low tech (i.e. constructable!) engine - they are loud and inefficient but you can make them from basically steel tubing, some reed valves, a fuel supply and a leafblower.

turboshaft engines are a high-tech high-rpm engine that you might see in things like tanks (as mentioned above) for cases where having 5 V12s isn't very plausible. They can probably be modelled directly with the existing (new) engine code, perhaps with a different set of faults.

**Comment by mugling** [comment]
> Why do we need these engines at all?

Variety - the real kind as opposed to insignificant stat changes

**Comment by Coolthulhu** [comment]
Extra propulsion engines is basically just stat changes.
Unless you allowed them to do things like acceleration in arbitrary directions (arbitrary movement directions for vehicles aren't supported yet) - then it would actually allow some weird maneuvers.

**Comment by mugling** [comment]
Well jet engines that provided temporary huge thrust using rare fuel would be a different mechanic. Or perhaps a reactor that provided good power output but produced unpleasant radioactive waste or heated up or something along those lines.

I'm not disagreeing with you about avoiding stat-changes but instead trying to come up with some novel mechanics

**Comment by Coolthulhu** [comment]
We could bring back plasma engine as the expensive but fast thing. This time not using the rare plasma containers (at least not exclusively), but some expensive to produce hydrogen (say, 10% batteries-to-hydrogen conversion efficiency) and only being contained in high-tech tanks with low capacity.

Full jet engines would only really make sense if vehicle physics could somehow reflect misaligned jets (quick rotations), bursts of speed (would need good coasting mechanics) and huge velocities (air resistance?).
Overall jets don't have a niche to fulfill. The only reason to ever accelerate very fast is starting quickly.

**Comment by BorkBorkGoesTheCode** [comment]
What would the lore for the plasma engine be?

**Comment by zwparchman** [comment]
Jet engines should be high power and able to use any flammable liquid as fuel. [Wikipedia](https://en.wikipedia.org/wiki/Jet_fuel) agrees that they can burn a large range of fuels, but normally burn some form of "jet fuel" which is a safer fuel that is harder to ignite than normal fuels. 

Some more quick research suggests that they should burn much more fuel at idle than a comparable piston engines, but less at full throttle. Gas turbines are also very light for the power they provide, and they also make great power sources for generators. Honestly a gas turbine could be interesting though if the implementation is faithful to real life they will likely be best used in a series hybrid to top off the battery (assuming you can get one that is well sized for your alternators).
