### ISSUE TITLE
Collisions are happening that shouldn't be

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#19353]
I ran into this sports car even though I was tiles away from it.

![car broke](http://imgur.com/z0hgB38.png)

Here's a copy of my save. Hitting five repeats the collison.

http://chezzo.com/cdda/CollisionSave.zip

**Comment by mugling** [comment]
How easy is it to repeat?

**Comment by mugling** [comment]
Can reproduce in a version before #19275 so not a regression from that PR

**Comment by Oskar636** [comment]
Is it the mirror?

**Comment by BorkBorkGoesTheCode** [comment]
Which vehicle square is 0,0?

**Comment by mugling** [comment]
> Which vehicle square is 0,0?

Good point, lets turn on debug mode and find out

**Comment by mugling** [comment]
To reproduce try and steer into the side of a vehicle. The collision appears to happen before the vehicle moves. I haven't fully bisected but I can reproduce in a master from a few weeks ago so looks like an older bug.

**Comment by AMurkin** [comment]
![collision](https://user-images.githubusercontent.com/1931904/31874272-044b36b2-b7d1-11e7-8dc9-5056032cc18c.png)
I've seen that too at build 6875 (side mirrors collides).
