### ISSUE TITLE
It's not possible to create a new world without enabled LUA support

### ISSUE THREAD

**Issue by illi-kun** [CleverRaven/Cataclysm-DDA#19365]
![mod](https://cloud.githubusercontent.com/assets/5421954/20462384/22f51744-af36-11e6-9e32-872e8d86b212.png)

**Comment by illi-kun** [comment]
It seems that the recent changes makes LUA support mandatory and not optional. I hope that this requirement is excessive and was defined mistakenly.

**Comment by mugling** [comment]
Looks like bug
