### ISSUE TITLE
Errors from cataclysm++ mod on latest build

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#19374]
Errors on seats, survivor vehicles, etc.  Also, ammolink22 still throwing error.

game is unplayable with crash to desktop when trying to eat

**Comment by Noctifer-de-Mortem** [comment]
Since my mod isn't included with the core game I doubt it will be looked at in GitHub.

I am currently using build 5759 and the mod works fine. I will out more details in the mod's thread in the forums: http://smf.cataclysmdda.com/index.php?topic=11248.0

**Comment by mugling** [comment]
You need to change `seat_nocargo` to `seat`. The food crash is something else I think

**Comment by codemime** [comment]
The food crash is #19372.

**Comment by mugling** [comment]
Closing because the required information is given to implement a fix
