### ISSUE TITLE
Trying to (E)at something causes crash on 0.C-19820-g779a385

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#19372]
This was a game saved under build 5900 (0.C-19721-g82f0627). It wasn't crashing at that point.

**Comment by codemime** [comment]
Can't reproduce. Do you still have the game?

**Comment by macrosblackd** [comment]
https://1drv.ms/u/s!AvB7YdRmAERpvz_bQeldElrz5Tuy

**Comment by codemime** [comment]
Thanks, but I still can't. What's the resolution of your screen (console)? This may be involved in the crash.

**Comment by macrosblackd** [comment]
Windowed Fullscreen @ 2560x1440

**Comment by macrosblackd** [comment]
Crash happens at 1920x1200 too.

**Comment by codemime** [comment]
No dice (on both resolutions).

**Comment by codemime** [comment]
It would be just great (and two-thirds of the solution) if you could provide a stack trace.

**Comment by macrosblackd** [comment]
I can't find a stack trace - any ideas on how to get one with windows x64 release version?

**Comment by macrosblackd** [comment]
There is what shows up in the Even Viewer:

```
Faulting application name: cataclysm-tiles.exe, version: 0.0.0.0, time stamp: 0xaef0aee8
Faulting module name: msvcrt.dll, version: 7.0.14393.0, time stamp: 0x57899b47
Exception code: 0xc0000005
Fault offset: 0x000000000004f68e
Faulting process id: 0xff4
Faulting application start time: 0x01d2435eddcfb9af
Faulting application path: D:\cdda\cataclysm-tiles.exe
Faulting module path: C:\WINDOWS\System32\msvcrt.dll
Report Id: 18b3c26e-5c3a-4e67-be42-91f8ed3d6cac
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by codemime** [comment]
> any ideas on how to get one with windows x64 release version?

Any compatible IDE (shipped with a compiler/debugger) would suffice (Code::Blocks, for example).

> There is what shows up in the Even Viewer:

This doesn't help much.

**Comment by macrosblackd** [comment]
The issue is #19339 . I used the build just prior to that and the new inventory works fine.

**Comment by hmstanley** [comment]
getting same error when trying to "E" a food.

Faulting application name: cataclysm-tiles.exe, version: 0.0.0.0, time stamp: 0xaef0aee8
Faulting module name: msvcrt.dll, version: 7.0.14393.0, time stamp: 0x57899b47
Exception code: 0xc0000005
Fault offset: 0x000000000004f68e
Faulting process id: 0x2934
Faulting application start time: 0x01d2436c051b39fb
Faulting application path: C:\Users\wqc\Desktop\cataclysmdda\cataclysm-tiles.exe
Faulting module path: C:\WINDOWS\System32\msvcrt.dll
Report Id: a8142229-bfe3-4860-bd44-31a8c8fa998a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by illi-kun** [comment]
Please check if the issue is gone in build 5920.

**Comment by macrosblackd** [comment]
Appears to be fixed.
