### ISSUE TITLE
Incomplete migration breaks saves, tries to load mod twice

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19385]
http://smf.cataclysmdda.com/index.php?topic=13715

Seems like (some?) migrated saves try to load the core data twice, which makes them unloadable and sometimes causes crashes.

**Comment by Kyune** [comment]
I have a save from release #5904 that was started on #5904 that I can currently reproduce a crash on consistently by loading the game, saving and then reloading it.  Confirmed to still happen in #5923.  Not sure if it's related to this particular issue or not.

**Comment by Coolthulhu** [comment]
Fuck, I can't even get it to debug properly. Need help from other devs here.

**Comment by mugling** [comment]
Are we sure this isn't to do with that `printf` bug? Random crashes with bad stack traces sounds more likely?

**Comment by codemime** [comment]
I've just tried the save. It loads/works normally. Saving and reloading don't lead to the crash on my system.

**Comment by mugling** [comment]
@Coolthulhu #19339 introduced some really odd behavior (including multiple segfaults in disparate parts of the code) for certain platforms and was then reverted. It could be the cause for this?

**Comment by Coolthulhu** [comment]
Could be something system-related. @codemime what OS and compiler are you using? I recall @mugling having FreeBSD.

Here on windows+MinGW it complains about duplicate bionics and vehicle faults and then goes back to main menu. One `gdb` version crashes when I set a breakpoint, other managed to break it properly and I'm checking out how does it look underneath now.

Windows treats paths differently - for example, it doesn't sort files when doing a `make`.

**Comment by codemime** [comment]
Heh, I can't create a new world. Or rather I can, but when I create a character in it, the game shouts at me and drops a ton of debug messages.

**Comment by mugling** [comment]
@Coolthulhu is this in latest `master` as the bad changes were reverted out?

**Comment by codemime** [comment]
> what OS and compiler are you using?

Ubuntu x64, gcc 4.9.2.

> Here on windows+MinGW it complains about duplicate bionics and vehicle faults and then goes back to main menu.

Same here, but with another save. I'll upload it.

**Comment by Coolthulhu** [comment]
> @Coolthulhu is this in latest master as the bad changes were reverted out?

Not the latest-latest, but with the changes reverted.

**Comment by Kyune** [comment]
Looks like I should have added this in my original comment, but I'm on Windows 10.

**Comment by Coolthulhu** [comment]
Found out how does it work:
For some reason, the CORE_VERSION isn't migrated correctly. Saves with CORE_VERSION: 5 will have the "dda" mod, but will get it once again during migration, causing the errors.

To fix individual save, remove the "dda" mod form list of mods or bump the CORE_VERSION to 6.

**Comment by mugling** [comment]
Have identified cause
