### ISSUE TITLE
Mapgen layers/templates/overlays

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19387]
I'll describe with an example:

`basement_game` (the one with pool table, alcoholic drinks, toilet and sofas) has 4 variants:
* Bookcases and no washing machines
* Bookcases and washing machines
* Armchairs and no washing machines
* Armchairs and washing machines

This could be instead expressed as `base + (bookcases OR armchairs) + chance to add washing machines`.

It could be as simple as having a nested mapgen definition and some way to pick which nested mapgens get applied on top of our base mapgen.

Those layers/templates/overlays could even be saved and reused, though they would most likely be quite useless except for groups of very similar base mapgens (basements).

A much more complex version would be having conditional overlays (ie. "If tile is `t_safe`, spawn gold"), but that could be quite complex to implement. That, however, would be useful for reusable overlays: damaged buildings, fungified buildings and fields, burnt buildings, collapsed basements etc.

**Comment by codemime** [comment]
> A much more complex version would be having conditional overlays (ie. "If tile is t_safe, spawn gold"), but that could be quite complex to implement. That, however, would be useful for reusable overlays: damaged buildings, fungified buildings and fields, burnt buildings, collapsed basements etc.

The idea is great, and it perfectly corresponds to #14339. We could get a nice variety of places with overlapping conditional overlays:

- `"house"`
- `"prepper house"`
- `"looted prepper house"`
- `"looted and burnt prepper house"`

e.t.c.

Something resembling an overlay already [exists](https://github.com/CleverRaven/Cataclysm-DDA/pull/19368/files#diff-90df0fb487770203c1f3f21de7b1b6bdR553) in the game, but it's hard-coded in the mission code and looks rather ugly. 

I look forward to implement this idea the right way.
