### ISSUE TITLE
data/json/preload.lua breaks non-lua builds

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19383]
Now that `dda` is a mod, it is subject to the usual check for lua dependence: existence of `main.lua` or `preload.lua` in mod's `path`. The `preload.lua` is just an example, it doesn't need to be there as it serves no function in the game.

EDIT: Ditto for `data/json/main.lua`.

**Comment by mugling** [comment]
Already fixed in `master`?
