### ISSUE TITLE
Assertion Failed at line 321 

### ISSUE THREAD

**Issue by zxpr0jk** [CleverRaven/Cataclysm-DDA#19396]
![assertionfailed](https://cloud.githubusercontent.com/assets/4273001/20497463/d89771ec-afee-11e6-8f6f-b41b768672e0.png)

Windows 10 Pro x64 v1607 - 14393.447
AMD FX 6350
16GB RAM

Version 0.C-5753

Game happened to autosave a few moments into entering this pizzeria. Have 3 NPCs in group. About 3-5 actions later, game crashes. I've had similar happen previously, but was able to walk in the opposite direction on reload and avoid the crash. Save file included.

[Casselberry.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/604611/Casselberry.zip)

**Comment by codemime** [comment]
Thanks for the save file.

**Comment by codemime** [comment]
The failed assertion doesn't show up. What exactly did you do to get it?

**Comment by zxpr0jk** [comment]
Anything at all. Even wielding the remington caused it to happen. I assumed something spawned or walked into the area that shouldn't have since it didn't matter what I did, the failure happened within 3 to 5 steps, or yelling for a couple turns, or talking to all the npcs, or wielding something in the inventory.

If you're not getting the crash at all, I'd have to ask what exactly you did that averted it.

**Comment by codemime** [comment]
> If you're not getting the crash at all, I'd have to ask what exactly you did that averted it.

Same here, anything at all. It just doesn't happen no matter what I do. It could be somehow related to UB (#19385), but I'm rather surprised anyways.

I'd appreciate if anyone would try to reproduce it and post a stack trace in case of success.

**Comment by keyspace** [comment]
Tried on a vastly different system here.

One weird thing that comes up consistently on the first turn is the NPC wielding a (magazined) rifle drops it.

@zxpr0jk, has that NPC ever fired that weapon?..

@codemime, if so, could the several-turn delay be from aiming?..

line.cpp:321 is `slope_of()`, which is only called by `move_along_line()` (same file), which has a comment about (I guess) ranged attacks.

P.S. Sorry if this is noise.

**Comment by mutability** [comment]
Note that 5753 is a couple-hundred builds old

**Comment by codemime** [comment]
@mutability You're absolutely right! Damn, how could I overlook that "detail". Thank you!

That probably means the issue can be closed.

**Comment by mutability** [comment]
Yeah, given the age of the build this is probably #18951 which was fixed about a month ago

**Comment by zxpr0jk** [comment]
Thank you, @mutability . I'll close this.
