### ISSUE TITLE
Getting errors for ammolink22, ammolink45 and ammolink762R

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#19394]
Mods

[
    "Arts' Guns",
    "Cata++",
    "Medieval_Stuff",
    "More_Survival_Tools",
    "StatsThroughSkills",
    "blazemod",
    "Tanks",
    "boats",
    "deoxymod",
    "more_classes_scenarios",
    "realguns",
    ""
]

**Comment by BorkBorkGoesTheCode** [comment]
I think the ammolinks are from cataclysm++

**Comment by illi-kun** [comment]
It shiuld be reverted in forum in this case.

**Comment by hmstanley** [comment]
do you know how I might fix it manually?

**Comment by BorkBorkGoesTheCode** [comment]
@hmstanley What is the error?

**Comment by mugling** [comment]
> I think the ammolinks are from cataclysm++

Ping @Noctifer-de-Mortem and will post in the JSON API changes thread

**Comment by BorkBorkGoesTheCode** [comment]
It looks like I was mistaken. Cataclysm++ has ordinary .22 magazines; so Artyom's Gun Emporium has the ammolink problem.

**Comment by hmstanley** [comment]
so, I found them in Art's mod:
error:
Must define at least one ammo type
FUNCTION:: void Item_factory::check_definitions() const
FILE src/item_factory.cpp
LINE 860

Errors for ammolink22, ammolink45, and ammolink762R

"id": "belt762R",
    "copy-from": "magazine_belt",
    "type": "MAGAZINE",
    "name": "7.62x54R ammo belt",
    "ammo_type": "762R",
    "capacity": 200,
    "count": 100,
    "linkage": "ammolink762R",
    "flags": [ "NO_RELOAD", "NO_UNLOAD", "MAG_DESTROY" ]
  },

**Comment by mugling** [comment]
Closing because it's published to the API changes issue and there isn't anything else we can provide here

**Comment by hmstanley** [comment]
mug, how could I fix this manually? I'm sure there is a way? do I add the ammo type? or change it to generic?

**Comment by mugling** [comment]
See the API changes issue which explains what to do

**Comment by hmstanley** [comment]
linky?

**Comment by hmstanley** [comment]
fixed it.
