### ISSUE TITLE
Extinguishing a `torch` that's about to burn out does not revert it to `burnt out torch`

### ISSUE THREAD

**Issue by keyspace** [CleverRaven/Cataclysm-DDA#19395]
**System:** Arch Linux, C:DDA built from git master snapshot on 2016.11.10 - git tag not known, sorry. ~~Can't easily test on newer version due to  #19373.~~

**Steps to reproduce:**

1. Light a `torch` in inventory.
2. Wait 'till it burns out. A menu will appear: 1 extinguish / 2 light something / 3 cancel.
3. Select "extinguish".

**Result:**

Item turns into `torch (-1)`. Additionally, saving and loading turns the item into `torch (0)`.

**Expected:**

Item turns into `burnt out torch`.

**Workaround:**

Selecting either of the two other options - "cancel" or "light something" (and then cancelling by pressing, say, `q`).

**Comment by keyspace** [comment]
Latest git master 7cc3f5ee4b84ef25d86413996d236073d1025aa2 still has this.

**Comment by keyspace** [comment]
Probably the same for Louisville Slaughterer.

**Comment by Autastic** [comment]
can confirm this in latest build 5990 for windows
