### ISSUE TITLE
One mod can be specified twice for the same world

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19404]
Part of #19385 bug.

There is no warning when a mod is specified twice for one world. This can't happen using the regular UI, but broken migration can cause it. World with the same mod twice will fail to load if it contains something that can't be overwritten.

**Comment by pisskop** [comment]
Im not sure if its at all related, but I was having trouble saving custom-added mods to the default list of mods to load when creating a new world

**Comment by mugling** [comment]
Does `mod_manager::load_mods_list` not check for this?

**Comment by mugling** [comment]
#19477 included deduplication
