### ISSUE TITLE
macOS Sierra lacks dmg background image

### ISSUE THREAD

**Issue by Leland** [CleverRaven/Cataclysm-DDA#19406]
The background image added to Mac DMG builds in #14001 no longer shows up on Sierra. It looks like this is a known underlying issue with the bundler utility we use, [dmgbuild](https://bitbucket.org/al45tair/dmgbuild/issues/9/backgrounds-no-longer-work-in-os-x-sierra), and is an issue other DMG creation tools have ran into, like [node-appdmg](https://github.com/LinusU/node-appdmg/issues/121).

For reference, here's how the DMG looks.
![sierra dmg screenshot](https://cloud.githubusercontent.com/assets/714017/20531001/485a50a8-b0a3-11e6-8661-15ae43e1a5a2.png)

**Comment by remyroy** [comment]
I'm sure @patternoia would like to know about this one.

**Comment by remyroy** [comment]
We might have to wait until the dmgbuild tool solve this issue. Alternatively [we have another Mac build process being worked on](https://github.com/CleverRaven/Cataclysm-DDA/pull/19320) which may solve it.

**Comment by Leland** [comment]
Fixed in the [new version of dmgbuild](https://bitbucket.org/al45tair/dmgbuild/commits/2297947). Can confirm that this works now.
