### ISSUE TITLE
Broken leg is perfectly good for walking on

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#1941]
Having a broken leg does not impose any effect, and it should probably reduce the speed, weight limit and/or add pain when used for walking.
##

**Comment by Shinino** [comment]
Taking a look at this.  It LOOKS like this is all handled in character.cpp -- reasonably, you'd expect a broken limb (any type) to cause pain over time.  This would also lower speed.  You'd also presume that a broken arm would cause problems doing things.  Lowered speed due to pain would handle skills, but that leaves crafting speed. 

So, what -appears- to need to happen is a change to character.cpp to cause a broken limb to incur pain, and a broken arm to decrease crafting speed.  Trying to see if I can puzzle this out with my non-existent code knowledge.

**Comment by Shinino** [comment]
More on this.  From game.cpp, in the section on moving furniture, there's this:  u.mod_pain(1); // Hurt ourselves. (this is from straining to move furniture).   So maybe something about limb_is_broken causing u.mod_pain(whatever) every turn -- that'd handle the pain and speed component of this, but not the crafting speed decrease.

**Comment by Shinino** [comment]
So more on the pain train

Here's what I believe we need -- probably in game.cpp:  

check for broken limbs, then calendar::once_every(1_turns) then a u.mod_pain(x) (x being the amount of pain)

The effect would be that every turn you're generating an amount of pain.  This may need to be changed to less often than one turn, though -- it'd require the player use painkillers to manage the pain, which gives all of those side effects also.  This would make a broken limb a major detriment, as it should be.

Other things which could also happen (requiring me to figure more out about coding):  Broken arms (if they're even able to be called) causing crafting time to be lowered and causing anything powered by Muscle_arms to not work as well (or at all) and broken legs causing anything with muscle_legs to work less effectively or not at all.

**Comment by aierce** [comment]
I just noticed broken arms doesn't apply debuff either. I can wield weapons and hit zombies as usual

**Comment by Kaltag1925** [comment]
> So more on the pain train
> 
> Here's what I believe we need -- probably in game.cpp:
> 
> check for broken limbs, then calendar::once_every(1_turns) then a u.mod_pain(x) (x being the amount of pain)
> 
> The effect would be that every turn you're generating an amount of pain. This may need to be changed to less often than one turn, though -- it'd require the player use painkillers to manage the pain, which gives all of those side effects also. This would make a broken limb a major detriment, as it should be.
> 
> Other things which could also happen (requiring me to figure more out about coding): Broken arms (if they're even able to be called) causing crafting time to be lowered and causing anything powered by Muscle_arms to not work as well (or at all) and broken legs causing anything with muscle_legs to work less effectively or not at all.

Would this be for broken arms as well? I don't imagine you would use a broken arm, as you're not really forced to like you are when walking.

Also maybe an option to put more weight on the broken limb and have the pain generated scale according to that?
