### ISSUE TITLE
overmap specials rotation only works for north facing terrains

### ISSUE THREAD

**Issue by egomassive** [CleverRaven/Cataclysm-DDA#19414]
Example:
If I have a declaration like this in an overmap_specials.json:
```
"overmaps" : [
      { "point":[0,0,0], "overmap": "house_west"},
      { "point":[1,0,0], "overmap": "house_north"},
      { "point":[2,0,0], "overmap": "house_east"}
]
```
then I get over terrain with correct facings if the whole structure faces North
```
<^>
```
but if it is randomly rotated to the East then every terrain faces East
```
>
>
>
```
when it should be
```
^
>
v
```
Win10, Tiles, 0.C-19846-gebe6fa5

**Comment by mutability** [comment]
from a quick look, it might be because load_overmap_terrain assigns exactly the same directional_peers to all of the _north _south _east _west variants (rather than e.g. the "south" rotation of _east being _west)

**Comment by codemime** [comment]
I've pretty much rewritten that old code (as a part of a bigger yet unpublished change). However, all the overmap specials we currently have are facing north.

**Comment by egomassive** [comment]
I have a mansion revamp on the way that uses randomly chosen pieces for corners and t-joints. This will be important when that's finished, which wont be soon.
