### ISSUE TITLE
Unstable Metabolism only lasts for 1 turn an hour

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#19415]
Thus, there can be no effects added to it because they never activate

**Comment by saneman226** [comment]
I've also had this problem, I was eating too many multivitamins and the hypervitaminosis didnt really have an effect. I also saw that the unstable metabolism was on/off constantly.

**Comment by tswood** [comment]
Is this the same issue as #18026?

**Comment by illi-kun** [comment]
Closing as a dupe.
