### ISSUE TITLE
Electric Vehicles out of battery don't slow down in 5933

### ISSUE THREAD

**Issue by MrWoot** [CleverRaven/Cataclysm-DDA#19417]
I have an electric scooter with a battery charged to 6%.  While travelling on a road, when the battery runs out, I can no longer adjust the desired speed at all - I can't set it any faster or slower.  The vehicle will continue on that road, apparently forever, without changing it's current speed.  If I take the vehicle off-road, it begins to slow down as expected, but the desired speed is still "stuck" at whatever speed it was set to when the battery died.

**Comment by MrWoot** [comment]
I'll also point out that I'm seeing batteries drain VERY quickly.  I'm using the Vehicle Additions mod, which I gather has been causing conflicts recently.

**Comment by Greiger** [comment]
I've been seeing something similar.  Though not quite exactly the same with gas engines that run out of fuel in superlight cars too.  They will slow down, very very slowly, but you seem to lose the brakes on any car that runs out of go juice.

**Comment by keyspace** [comment]
Can reproduce OP on commit ebe6fa5 (2 days old, no vehicle-related commits since).

Selecting "let go of the controls" seems to leave the vehicle perpetually rolling. Selecting "stop driving" slows the vehicle down (non-abruptly).
