### ISSUE TITLE
Vehicle Construction eats the first wooden frame when using wooden frames

### ISSUE THREAD

**Issue by Nymall** [CleverRaven/Cataclysm-DDA#19425]
When you start vehicle construction with just a wooden frame in inventory, it errors out that construction was started without material.

![image](https://cloud.githubusercontent.com/assets/7415730/20578770/da75593a-b17d-11e6-8ed0-91cae473e9f2.png)

With subsquent testing, it just eats the first frame and then cannot find the frame in player inventory. Two frames will work, but it still eats the first frame.

**Comment by illi-kun** [comment]
What is the version of your game? We fix this bug earlier...

**Comment by keyspace** [comment]
Can't reproduce with commit `ebe6fa5` (2 days old). Tried with wooden frames in inventory or on the ground nearby.

**Comment by MrWoot** [comment]
I'm seeing a similar bug, except I'm using extra-lite frames.  It "consumes" two to generate a vehicle with one frame.  I'm using version 5933.

**Comment by mutability** [comment]
I saw this with extra-light frames as at 6c4885edb32f230641ffa61e9a5f729616cfae49

**Comment by mugling** [comment]
Tentative close as I think this was a now resolved `blazemod` issue. Please re-open if reproducible in most recent build
