### ISSUE TITLE
Conversion mods to ammotypes without any magazines will crash the game

### ISSUE THREAD

**Issue by RightInfinity** [CleverRaven/Cataclysm-DDA#19429]
While fiddling with the latest experimental with the 'Realistic Guns' mod enabled I ran into an issue where the 410 bore conversion kit made weapons that would crash the game when being inspected if they were magazine fed. More prodding revealed that the kit works fine on weapons that have integral magazines (Double barrel shotguns etc).

It seems that if a conversion kit is used on a weapon that requires magazines but there are no magazines for that ammo type, the game crashes when you try and inspect them.

**Comment by DangerNoodle** [comment]
I had not considered this would be a problem. Apologies for that.

**Comment by mugling** [comment]
> I had not considered this would be a problem. Apologies for that.

It's not your fault. The game should never crash for bad JSON definitions

**Comment by DangerNoodle** [comment]
I am presently working on a pull request to fix all instances where a magazine-fed firearm can be converted to a crash-inducing ammo type.

**Comment by mugling** [comment]
Stack trace?

**Comment by DangerNoodle** [comment]
I am not sure how to accomplish that. Thus far I am simply overviewing all firearms of a convertible caliber manually, to see if any potential for this scenario exists in vanilla. Tedious, but simple and thorough.

I also intend to add a Saiga-410 to the mod to cover the scenario stated in the original post.

**Comment by DangerNoodle** [comment]
Manually finding instances of this problem in mainline proved to be simple. Far more tedious is adding a copy-from override for every single 5.56x45mm, 7.62x51mm, and 7.62x39mm firearm.

Maybe I should instead simply restrict the .410 conversion kit to 12 guage? This would mean I only need to add an override to the Saiga-12.
