### ISSUE TITLE
Non advanced inventory screen annoyingly small. 

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#19424]
Inventory screen size when eating or dropping items or doing other non advanced inventory tasks is inconsistent in size.. Sometimes its too small and your scrolling though a list to find what you want. Other times its properly sized.

**Comment by codemime** [comment]
> Sometimes its too small and your scrolling though a list to find what you want.

When it's small it doesn't scroll. Small size means small number of items => no need to scroll.

**Comment by mugling** [comment]
Duplicaeted by #19427
