### ISSUE TITLE
Idea: split item spawn scaling factor. Suggestion

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#19422]
As far as i know the Item spawn scaling factor count for items spawn in buildings and drops from monsters/zombies.
If a player wants low spawn factor and many zombies, he gets the problem that the zombies will get the main source of items and not buildings.

Is it possible to split this without to much work? and let the player set the factor for item spawn in buildings and a seperate option for item drops from zombies?

**Comment by DangerNoodle** [comment]
Potentially useful, but having the main source of items be zombie drops does male for an interesting challenge in its own right.

**Comment by TheWebfrog** [comment]
@DangerNoodle Even a playthrough where all items where purely found through zombos would be an interesting if inefficent challenge

**Comment by DangerNoodle** [comment]
Potentially, though "all" would be extremely hard to code. Already item spawns have a minimum value, butcher returns are unaffected, and deconstruction/bashing is likewise unaffected.

At least, as far as I am aware. I do recall that bashing terrain has been useful for early-game toolmaking when item spawns are low, as well as when the starting area has an inherent dearth of resources.

**Comment by ZenZen2** [comment]
When i started this suggestion i didnt know that the Itemspawnrate doesn't affect monster drops. Also the last comment is around 5 month ago. Im closing this.
