### ISSUE TITLE
Multiple stairs in the vault trap the player

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19435]
In a few areas there are up stairs in the vault that lead to a 1x1 room with no down stairs, and encased in solid rock and metal walls, effectively trapping the player. At minimum, there should be some down stairs so the player can go back.

**Comment by acidia** [comment]
May I ask where?  Its a kinda a large map.

**Comment by Regularitee** [comment]
The one I recall lead up into z-layers still in the vault rather than the sewers, so they'd have to be on the second or lower levels of the vault. It lead to a location outside the vault proper (in the solid rock that normally fills all the terrain outside the metal walls). 

The only I distinctly recall was all rock, except a metal tile to the south-east, which was some sort of bathroom. Sorry I can't help more, but I was stuck in a solid 1x1 room with no line-of-sight, and much of the vault's content is highly repetitive so doesn't stand out much in memory.

**Comment by Coolthulhu** [comment]
Upstairs don't have an error message on lack of matching stairs. They just do the move anyway (this was used for manholes). So any unmatched upstairs are a hazard.
This can be hacked around by special casing manholes and adding a stair check, but the proper fix would be to warn when a mapgen can generate unmatched stairs instead.

Semi-related:
Would it be possible for all future "big jsons" to have stairs arranged exactly above/below each other? This will be enforced at some time in the future and stairs that don't match will stop working in z-level mode.

**Comment by acidia** [comment]
Found it, the stair is just facing the wrong direction.  I've always stacked stairs directly on top of each other but sometimes I mix the up and down stairs keys (I think because they are the reverse of DF or some other game I play).  I'll push a fix.

**Comment by saneman226** [comment]
Ive also had this error: build 5941

**Comment by acidia** [comment]
Did you go up the stairs behind the basketball court on the lowest level of necropolis?

**Comment by saneman226** [comment]
I was in a hallway with the up and down stairs right next to each other and the up one put me in solid rock.

**Comment by acidia** [comment]
Do you know what level you were on, or what you were near?

**Comment by saneman226** [comment]
It was on -3 going up to -2. And it was a branch off the regular housing (I'm 95% sure).
