### ISSUE TITLE
Cannot consume negative quantity of ammo for minireactor

### ISSUE THREAD

**Issue by cdag** [CleverRaven/Cataclysm-DDA#19432]
Installed a minireactor in my vehicle, then filled it with Pu cells. Game is throwing this error every turn:

![catadebug](https://cloud.githubusercontent.com/assets/19315220/20589006/70a1545e-b1e7-11e6-9264-5b6661660be7.png)

Turning it on doesn't charge the batteries of the vehicle either.

EDIT:
After tinkering around a bit, it actually puts out power as long as I don't put more than 3 Pu cells in it (1500 units). If I fill it up past that it drains the battery to 0 and doesn't charge the battery. It also spams "The <vehicle's> battery dies!" if I load it up past 1500 units. I am using generic guns mod, not sure if that's related.

**Comment by creodor** [comment]
I'm seeing this same issue, however I seem to have it occur mostly at around 460 charges of plutonium. I also just had it occur at 1480 charges. Reinstalling the minireactor seems to solve it until it hits the values the system dislikes again. It wipes out all stored power when this happens, which is a problem.

**Comment by Regularitee** [comment]
Since this issue hasn't been solved after a week, could maybe someone simply limit the ammunition storage for the minireactor? Maybe change it to 1000 (2 plutonium cells) from its current 10000 (20 plutonium cells) as a work-around to avoid the error until it's fixed.

**Comment by mutability** [comment]
Generally the reason that something hasn't been fixed after `insert time period here` is that no-one with the time and interest has looked at it. A "simpler solution" doesn't really change that. If you think that a simpler solution is viable I'd encourage you to make the change, do the testing, and submit a PR.

**Comment by mugling** [comment]
I'm fairly confident it should be fixed by #19426 so I'm not wanting to write a further PR for this until that one is merged

**Comment by Regularitee** [comment]
I just suggested it because, if the bug was too difficult or time-consuming to solve given other issues, a band-aid solution like reducing the reactor cap. In theory it would involve only changing a single fixed value (the reactor ammo capacity) rather hunting for a bug that theoretically could be in any number of files or lines.

But it looks like mugling might already have solved it, so guess it was a moot suggestion.
