### ISSUE TITLE
Get rid of variable skill recipe unlocks in books

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19433]
Some recipes, despite having low difficulty, require high skill to be unlocked from specific books. I assume this is an attempt to make books more distinct, but it does so very badly, as it isn't communicated to the player in any way meaning it looks like a bug more often than not.

This sometimes does make sense for lower skill levels, since it means you're actually using the recipe without understanding it well to memorize it (this could be kept or even expanded on), but when you want to unlock say, forge rig (4 mechanics) and need 8 (!) mechanics to use the book for this, it's neither balanced, realistic nor novel in any way.

**Comment by kevingranade** [comment]
As discussed in #21553, this is a non-starter.
