### ISSUE TITLE
Vehicle water purifier (purifying vehicle containers)

### ISSUE THREAD

**Issue by saneman226** [CleverRaven/Cataclysm-DDA#19448]
Using the option on the vehicle water purifier to purify the water inside the vehicle changes the type of liquid the container is supposed to hold.

I want to be able to specify exactly which tank receives the clean water instead of it just converting my water tank to a clean water tank. 
As it is, I have to convert the water to make clean water, and then put it into a jerrycan to put it back into the right tank. Then I have to convert the new clean water tank back to water so that the funnel on the vehicle has somewhere to put the rain water it collects.

Can we also bring back the option to lock a vehicle tank so it only takes in one type of liquid? I found this feature very useful.

**Comment by Regularitee** [comment]
I agree it's a pain, but with game code for engines breaking across the board, it may be a lower priority at the moment. I guess it all depends on how hard it is to implement. Maybe it would be easier on the game code to make vehicle-mounted purifiers instantly purify water it collects via the funnel, sidestepping the issue of having two types of water.

For now, a decent work around is to have two funnels and water tanks, with one purified. Once one runs dry, you purify the other and use it as your clean water source as the now-empty old tank begins to collect rainwater. You lose an extra roof slot, but you don't need to use jerrycans or re-installing metal tanks.

**Comment by saneman226** [comment]
The automatic water purification sounds awesome, there should still be an on/off switch for it though. 
Also, I would still like some ability to lock the vehicle tanks to a certain liquid (in the vehicle menu perhaps). 

Thanks for the work around!

(Dont tell nobody but I was able to put batteries and an electric motor on a shopping cart and I started riding around on it! :D)

**Comment by Xpyder** [comment]
related to #7075

**Comment by Night-Pryanik** [comment]
I think this should be closed by #21095.
