### ISSUE TITLE
Solar panels can be installed on vehicle tiles which already have solar panels

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19445]
... if that tile also contains a "swappable storage battery case" with no storage batter y installed.

In my particular case, both were upgraded reinforced solar panels, so I don't know if the bug is specific to that variant or to all solar panels.

**Comment by Reclusive-reptile** [comment]
Do you use blaze mod? It adds a mounted solar panel that is installed on battery mounts/turret frames.

**Comment by Regularitee** [comment]
Accidentally had it enabled on a test world I setup. My mistake.
