### ISSUE TITLE
A number of vehicle parts are no longer repairable

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19446]
Yes, I mean those with even minor damage, and not totally destroyed modules, and yes, there is sufficient skill to perform repairs (12+ mechanics skill). Security systems and swappable storage batteries are the two modules I know this bug affects, but there's probably more I haven't tried.

**Comment by saneman226** [comment]
All batteries need to be taken off of vehicle and repaired via soldering iron.
