### ISSUE TITLE
Small storage battery recipe is missing

### ISSUE THREAD

**Issue by saneman226** [CleverRaven/Cataclysm-DDA#19450]
I look inside the crafting menu for the small storage battery, and get nothing. I am able to craft the medium and regular storage batteries, the small one doesn't appear. I looked on the CDDA item browser as well, and found that the recipe was in 3 books (What's a Transistor? (level 2), Ham Radio Illustrated (level 2), Under the Hood (level 3)). Then I looked under the development section of the item browser and it gives an error when clicking "Craft" or even "Disassemble" on the page. I believe the small storage battery is missing from the development branch of the game.

**Comment by BorkBorkGoesTheCode** [comment]
It has no recipe. It's still in the game.

**Comment by keyspace** [comment]
As I understand, storage batteries are high-tech items that can't be produced without the pre-apocalyptic industrial complex.

Small storage batteries are single (enclosed) cells; medium and "full-size" are banks of those - at least that's my interpretation from the recipes.

**Comment by Coolthulhu** [comment]
It is uncraftable, but obtainable through disassembling the bigger storage batteries.

**Comment by DangerNoodle** [comment]
I could have sworn that small storage batteries could be crafted in earlier versions. Removed for balancing reasons, I assume? Would also make sense if storage batteries are lithium-ion cells or something more science-fiction in nature.

Or it might be that I am thinking about the recipe for larger storage batteries, but I recall crafting them using components that were themselves crafted. I need to check whether large storage batteries allow mundane lead-acid batteries or not.

**Comment by saneman226** [comment]
So will it be permanently deleted? Also, will the main source of small storage batteries be the disassembled medium and regular storage batteries? I'm confused as to whether it is staying in the game or being removed.

**Comment by DangerNoodle** [comment]
It is still in game. It has to be scavenged instead.

Small storage batteries can still be obtained and installed, and still can be used to craft larger storage batteries.

**Comment by saneman226** [comment]
I believe the rate at which they spawn should be increased or for some other alternative way to get them to be made. I have only found 1 small storage battery in my 121 mb world as it is.

**Comment by BorkBorkGoesTheCode** [comment]
Storage batteries can be acquired by butchering a medium storage battery, which can be acquired by butchering a regular storage battery.

**Comment by Coolthulhu** [comment]
The rate is actually pretty huge once you start disassembling the vehicle batteries. It's trivial to get a ton of those.

We could add more "natural" spawns if we allowed storage batteries in tools that at the moment take 200+ batteries instead. For example, heavy duty flashlight.

**Comment by mugling** [comment]
Code infrastructure is 90% ready for discrete batteries. I'd quite like to go down that route providing we can come up with a sane UI.

**Comment by saneman226** [comment]
I would really prefer not to have to butcher large batteries to get the smaller versions, The way I thought of the storage battery for the longest time was a large industrial equipment battery. These are conventionally only for industrial equipment. I never thought of them as being rows of battery packs strapped together with duct tape, the inefficiency would be too harsh to think about :D.
