### ISSUE TITLE
Cannot repair batteries in vehicle repair menu

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#19451]
as the description states.

**Comment by saneman226** [comment]
Take it off the car and use a soldering iron to repair them.

**Comment by hmstanley** [comment]
oh, thanks.

**Comment by DangerNoodle** [comment]
That is an annoying inconsistency and suggests that they either should not be repairable as an item, or that they should be repairable in vehicles.

**Comment by mugling** [comment]
Indeed. They shouldn't be repairable but I don't want to implement that until we have more options for crafting them or more reliable sources (vehicle spawns are currently a mess)

**Comment by DangerNoodle** [comment]
Reliable sources might be the best option. I recall the idea of glass-cased, makeshift vehicle batteries being proposed at one point?

**Comment by saneman226** [comment]
I believe it should be repaired when off the vehicle using a soldering iron. Doing it this way is more real than repairing it while it is tied into the vehicle. Or perhaps we can still require the batteries to be repaired via soldering iron inside the car, but increase the time because it is a delicate job.

**Comment by WizardOfOoo** [comment]
I want to see crank start.

**Comment by saneman226** [comment]
If I'm not mistaken, you can hook an alternator up to a foot crank on a basic cart and hook it to your vehicle with jumper cables.

**Comment by WizardOfOoo** [comment]
https://www.youtube.com/watch?v=DArvPMlxHeQ

Don't need a battery.

**Comment by saneman226** [comment]
I never said you required a battery with the foot crank. :D

**Comment by Xpyder** [comment]
> Take it off the car and use a soldering iron to repair them.

You can't do this with storage batteries currently.  They're too heavy to hold and the repair menu doesn't show them as repairable nearby objects for either the Soldering Iron or the Makeshift Welder.

Also I don't see why you couldn't repair them if the case or the terminals got cracked, unless the actual cells got damaged?

**Comment by angoddu** [comment]
Is anyone working on this?
