### ISSUE TITLE
Ridiculus Log sizes

### ISSUE THREAD

**Issue by DeadLeaves** [CleverRaven/Cataclysm-DDA#19456]
My log files are blowing up like no tomorrow. They are growing with about 160000 (YES REALLY) lines per SECOND. All with this message: 
`16:46:16.791 SDL : src/cata_tiles.cpp:1803: SDL_RenderCopyEx() failed: SetTexture(): INVALIDCALL`

I'm  running build 5885 with win x64 SDL tiles. 
Downloaded from here: http://dev.narc.ro/cataclysm/jenkins-latest/Windows_x64/Tiles/

This is causing real issues for me since I run it on a USB drive to keep my cata playing portable. I can only play for an hour or so before I run out of space. My last play was about half an hour and that made a log file of 5.2GB

**Comment by DanmakuDan** [comment]
Are you running in fullscreen or borderless? Also, have you tried turning on software rendering, and checking if the logs are still increasing?

**Comment by mutability** [comment]
This is SDL reporting an underlying direct3d error. Software rendering will likely stop it (and go slow..)

**Comment by DanmakuDan** [comment]
I remember one of these errors happens when a Windows version of the game is alt-tabbed from fullscreen mode, the renderer (DirectX) can lose control of the screen until the window is active again.

**Comment by mutability** [comment]
It would probably make sense for debuglog to deduplicated repeated messages a la syslog

**Comment by illi-kun** [comment]
This issue is labeled as a ```bug``` due to SDL issue and as an ```enhancement``` due to request of debug log improvements.

**Comment by DeadLeaves** [comment]
A temporary fix I figured out is to make the log file read only and it will remain empty. At least this works in windows.

**Comment by Leland** [comment]
Can anyone reliably reproduce this?

**Comment by Leland** [comment]
Closing due to lack of reproduction – if this is still an issue for anyone, please make a _new_ issue for visibility. Log files growing that quickly is definitely a concern.
