### ISSUE TITLE
Safemode indicator no longer changes color

### ISSUE THREAD

**Issue by Taberone** [CleverRaven/Cataclysm-DDA#19467]
The Safemode indicator will always stay green no matter what in 0.C-19885-g4a966d2 (tiles)/Build 5945 (according to the CDDA Launcher). Previously, the Safemode indicator would turn entirely red when Safemode was disabled, and parts of the safemode indicator would gradually turn green again as the number of turns left before safemode was auto-enabled decreased.

To recreate this, have Auto Safe Mode, Safe Mode, and Turns to Re-Enable Safe Mode (Probably set it to 20 or something) enabled in the options, and then run around with safemode disabled while trying to see if the indicator will change colors at all.

**Comment by mutability** [comment]
This was broken by 3b6f6cf7d067c3bec20a092e3b14eb287c16b764, part of #19275
