### ISSUE TITLE
Linux T-shirt/Sports jersey mixup

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#19465]
Sometimes linux t-shirts have the description it should have, and sometimes they have a description that belongs on sports jerseys. Similarly, sometimes sports jerseys have the description it should have, and sometimes it has a description that belongs on Linux t-shirts. This can easily be reproduced by searching for `sports` or `t-shirt` in `debug menu- wish for an item`, and scrolling between 2 entries (the description changes each time).

**Comment by BrettDong** [comment]
Looking at this.
