### ISSUE TITLE
Suggestion: Self Repairing Vehicle Parts

### ISSUE THREAD

**Issue by jasonmbrown** [CleverRaven/Cataclysm-DDA#19463]
I was thinking about this, and it would be interesting to see vehicles that have more advanced technology in them (I mean we do have a nanite bionic that can heal body parts). Why not have something similar for vehicles using electricity or other fuel.

My thoughts on the features related to self repairing vehicle parts :

Ability to configure parts able to be repaired via json (I would assume that the nanites would not be able to fix anything/everything)

Ability to control What fuel is consumed and how much of the fuel is consumed per repair level.

The "Nanites" should be an accessory part that is applied to the frame of the vehicle (so you need to be able to craft 1 for each vehicle frame.
Self Repairing parts, that dont need anything installed to repair themselves (via json, and presumably for use in mods rather then the base game (Like blazemods Extra vehicle parts, Specifically the Blob vehicles, which are seemingly sentient beings)).

I have not looked into how hard it would be to implement a feature such as this, but I feel it wouldn't be horribly out of place to find the recipe to such a thing in a science lab, given the point of technology the game appears to be at. 

Let me know thoughts.

**Comment by Noctifer-de-Mortem** [comment]
Isn't there some kind of memory metal that is restored to a pre determined shape when electricity is applied no mattered how deformed?

**Comment by saneman226** [comment]
I personally don't find the concept appealing nor worth getting if it was implemented. The only real benefit you would get is the time you save from not repairing it yourself. The drain on the batteries would have to be pretty large for it to be balanced as well.

**Comment by mugling** [comment]
Too many vehicle bugs at the moment to consider further extensions
