### ISSUE TITLE
Two of the same recipe with exactly the same components

### ISSUE THREAD

**Issue by saneman226** [CleverRaven/Cataclysm-DDA#19464]
I have the medium storage battery recipe twice, the only difference being that one is memorized and the other is not. (build is 5941 btw)
![capture](https://cloud.githubusercontent.com/assets/12336871/20637496/f030da0c-b357-11e6-8623-3fa40c3f24ce.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12336871/20637499/f3611a98-b357-11e6-9e83-11d19ffeb9bb.PNG)

**Comment by Oskar636** [comment]
#19061 related, possibly duplicate.

**Comment by codemime** [comment]
> #19061 related, possibly duplicate.

Yes, it's a dupe.
