### ISSUE TITLE
PDA debug message

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19475]
Whenever I create a character in a world, the game complains about an unknowd PDA id.

**Comment by BrettDong** [comment]
I don't encounter this issue with latest master branch.

**Comment by mugling** [comment]
Me neither

**Comment by BorkBorkGoesTheCode** [comment]
This issue appeared when I loaded an old world.

**Comment by BrettDong** [comment]
You mean create a new character in an old world?

**Comment by BorkBorkGoesTheCode** [comment]
No. I copied one of my old worlds into the new experimental.

I found the issue: one of the mapgen mods I have has a custom itemgroup containing a PDA. Closing this.
