### ISSUE TITLE
Crash related to vehicle cargo

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19486]
0.C 19895: The game crashed when I carried a heavy frame onto a customized APC. It isn't consistently repeatable however.

**Comment by BrettDong** [comment]
Could you upload the save?

**Comment by mugling** [comment]
> Could you upload the save?

You can do this directly to this issue

**Comment by BorkBorkGoesTheCode** [comment]
Cannot reproduce anymore

**Comment by Leland** [comment]
Closing.
