### ISSUE TITLE
Integrated Toolset bionic does not unlock item action menu choices

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19489]
For example, the integrated toolset has a welder and solder function (based on its use in recipes), but can't be used to repair items unless you have a separate solder iron or welder to unlock the choices in the item action menu. Same for heating up food, it's not a choice unless you have a hotplate separate from your integrated toolset.

**Comment by Tharn** [comment]
Yeah, it being possible to use the Integrated Toolset through a trick feels sort of half-cocked. Maybe enabling the CBM could add a weightless meta-item to the player inventory.

**Comment by codemime** [comment]
The integrated toolset doesn't have such qualities:
```json
        "qualities": [
            [ "HAMMER", 3 ], [ "HAMMER_FINE", 1 ],
            [ "SAW_W", 1 ], [ "SAW_M", 2 ], [ "SAW_M_FINE", 1 ],
            [ "WRENCH", 2 ], [ "WRENCH_FINE", 1 ],
            [ "SCREW", 1 ], [ "SCREW_FINE", 1 ],
            [ "CUT", 2 ], [ "PRY", 1 ], ["DRILL", 1 ],
            [ "BUTCHER", -38 ]
```
It's description is deceptive.

**Comment by Tharn** [comment]
But you can use it to heat, weld and solder when the prompt to select a tool for the job is being called, and I believe that's as intended. The tool qualities listed there pertain to stuff like toolboxes and all various metal hand tools. I.e. soldering irons don't have a 'soldering 2' quality either. It doesn't exist AFAIK.

**Comment by Leland** [comment]
Looks like the bionic toolset was added to the item action menu in #12589.

That PR, from @Coolthulhu, notes:

> Only charge-less tools are supported. That is: hammer, hacksaw, woodsaw and knife.

Also see https://github.com/CleverRaven/Cataclysm-DDA/issues/19943#issuecomment-270312602, an issue that notes that the toolset can't be used for repair.

@Coolthulhu states in that issue:

>First, toolset does not provide an item. An item is necessary for item repair code to work, to use the repair actor.
> I a hacky solution for vehicle-mounted welders. This could be adapted relatively easily to toolset.
>
> Second, that's a bit of an UI problem. You can't force the % menu to use a particular tool and you can't access toolset's tools in any other way (except for crafting).
>If toolset had preference over tools, you'd need to turn it off or use the tools manually when trying to preserve bionic charges. If tools had preference, you'd need to drop them before using the toolset.
> Still, at the moment bionic charges are very cheap, so toolset over tools would suffice.

It sounds like what most likely needs to occur is a simple update to the [bionic toolset description](https://github.com/CleverRaven/Cataclysm-DDA/blob/9e5b5f83bb246fff258ccd372f3c9b3d5322dbea/data/json/bionics.json#L1187). It's really not an accurate depiction of what the CBM does.
