### ISSUE TITLE
Assigning ammo or magazines in an item group no longer works consistantly

### ISSUE THREAD

**Issue by Reclusive-reptile** [CleverRaven/Cataclysm-DDA#19481]
There is no rhyme or reason to this. default_zombie_death_drops, behindcounter, rare, and some others don't drop guns with mags/ammo, but the cop/soldier zombie death drops, mansion_guns, lmoe_guns do. I'm stumped.

**Comment by mugling** [comment]
Many drops include a percentage chance to include a magazine or ammo

**Comment by Reclusive-reptile** [comment]
And the above drop are all marked 100% for mags. If the ammo is rolling separately and overriding the magazine chance it would break every spawn that was intended to always have an empty magazine, but I don't think that is what is happening here.

**Comment by sethsimon** [comment]
Via `Test Item Group` in the debug menu, I tested `default_zombie_items` 10 times. Each time I filtered the list for "glock" and all 16 guns had no ammo or magazine. That item group has a 30% chance of ammo and a 100% chance for a magazine. There's definitely a bug somewhere. I'll look into it.
