### ISSUE TITLE
Adding missions to NPCs with the debug menu is unreliable

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19495]
The "Add mission" option sometimes selects a wrong mission. For example, I had NPCs start talking about relics after giving them the inhaler mission.

**Comment by maltouzes** [comment]
If you solve the "Find Relic" mission (or any others) you should afterwards "get" the good mission, i mean the one you choose (e.g "Find Inhaler" mission) is't it?

**Comment by Night-Pryanik** [comment]
Debug menu is unsupported.
