### ISSUE TITLE
Pistol auto-fire mechanism is broken

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19492]
It won't add a new firemode to the gun; if the player switches to the burst setting, the autofire mechanism will look like the KSG.

**Comment by mugling** [comment]
A little more detail?

**Comment by BorkBorkGoesTheCode** [comment]
@mugling The ui displays the name of the mod and a (0/0) ammo field instead of an automatic fire field.

A debug message also appears when the player fires the gun:

DEBUG        :  Item "auto-fire mechanism" hasn't provided a suitable context for skill "weapon" possessed by character.

FUNCTION  :  const SkillLevel& Character::get_skill_level(const skill_id&, const item&) const
FILE             :  src/character.cpp
LINE            :  1015

**Comment by DangerNoodle** [comment]
Possible side effect of the conversion from the burst-fire flag to defined automatic and burst modes, I would guess?

**Comment by mugling** [comment]
Can reproduce

**Comment by BorkBorkGoesTheCode** [comment]
This issue has returned.
