### ISSUE TITLE
Debug messages occur when NPC Bandits melee anything and the player wields a A7 Laser Rifle

### ISSUE THREAD

**Issue by Taberone** [CleverRaven/Cataclysm-DDA#19507]
<a href="http://imgur.com/hGFnV4b"><img src="http://i.imgur.com/hGFnV4b.png" title="source: imgur.com" /></a>

Build 5966/Version 0.C-19952-g3d4a0eb (tiles)

Give yourself an A7 Laser Rifle through the Debug Menu, wield it, and find some hostile Static NPCs (Bandits and Thugs that you have to kill for Old Guard quests, for example). Have the hostile Static NPCs either try to melee you or melee a zombie. Watch this message get spammed every time they do so.

**Comment by mugling** [comment]
`player::gun_value` needs some attention overall. I doubt it produces particularly sane values. It might be interesting to connect it to the stats dumper and see what NPC's idea of an ideal weapon is

**Comment by hmstanley** [comment]
Seeing this with cataclysm++ mod and laser weaponry.
