### ISSUE TITLE
cataclysm++ KRX Laser LMG has infinite ammo mounted on vehicle

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#19517]
I know this is a mod bug, but wanted to file it here for the mod author.  Not sure why, but the LMG is not draining the advanced UPS on the seat or in my inventory.  When I'm using the LMG, it is draining the UPS, but mounted, it will fire infinite.

**Comment by Noctifer-de-Mortem** [comment]
As far as I know, when ups powered guns are used as vehicle turrets, they will drain that vehicle's power as a ups substitute. If the weapon fires when the vehicle has 0% battery then it is firing as infinite.

**Comment by Noctifer-de-Mortem** [comment]
Pinging @mugling and @Coolthulhu to confirm.

**Comment by hmstanley** [comment]
ok..

**Comment by illi-kun** [comment]
We don't have this mod in the repo, so it's better to contact with its author via forum.
