### ISSUE TITLE
Pine needle tea should have high Vitamin C content

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#19521]
Pretty self-explanatory. If you're into history, this tea was introduced to American settlers by the natives as a way to cure scurvy.

**Comment by DangerNoodle** [comment]
That might be a good idea to implement. Was the idea of adding calcium to bone meal, broth, and/or wastebread ever implemented?

**Comment by Tharn** [comment]
Bone broth has a ton of Calcium. Wastebread and bone meal don't.

**Comment by DangerNoodle** [comment]
Then again, bone meal is not edible. Wastebread might be a logical choice for it, at least an amount based on how much bone meal is used relative to how many bones are used in bone broth.

**Comment by illi-kun** [comment]
Side note: Label [Vitamins](https://github.com/CleverRaven/Cataclysm-DDA/issues?q=is%3Aissue+is%3Aopen+label%3AVitamins) was introduced for easier handling and review of vitamins related topics.

**Comment by DangerNoodle** [comment]
Ah, thank you. When I am able to, I might look into this if it is not already presented as a pull request by someone else by the time I am next able to get on.

**Comment by DangerNoodle** [comment]
A question though. In the vitamin definition, how do the numbers given translate into RDA? I am unable to find where the game defines the amounts, as 'vitamin.json' only defines minimums and disease thresholds.

**Comment by DangerNoodle** [comment]
I mean in game it is not edible, as with flour and other items that are assumed to be used for crafting instead. I would need to figure out how to set it as edible again.

**Comment by Xpyder** [comment]
> I mean in game it is not edible

Oh, ok.  That makes more sense.

If we're under the assumption that the environment is still polluted (I know acid rain used to be a thing), then it might make sense for it to have a -healthy tag and have a cooking recipe (4+) to separate it into a safer more refined calcium supplement?

**Comment by DangerNoodle** [comment]
Possibly, assuming it is not used for a makeshift vitamin supplement, alongside whatever else might be a sensible addition.
