### ISSUE TITLE
Damaged tents can be taken down, set up as fully repaired tents

### ISSUE THREAD

**Issue by Leland** [CleverRaven/Cataclysm-DDA#19528]
One can come across damaged tents missing walls in field campsites. If it still has a groundsheet tile intact, one can take down the tent to have a fully repaired tent available.
(Note that you can see the unrelated issue #15569 present in these screenshots as well)

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/616547/save.zip)

<img width="1280" alt="screen shot 2016-11-28 at 9 25 10 am" src="https://cloud.githubusercontent.com/assets/714017/20671765/a9c6dfa2-b54c-11e6-9703-8e51341392e7.png">
<img width="1280" alt="screen shot 2016-11-28 at 9 25 26 am" src="https://cloud.githubusercontent.com/assets/714017/20671766/a9cd21f0-b54c-11e6-9213-e575714ed7b6.png">

**Comment by illi-kun** [comment]
Related discussion: #7112

**Comment by DangerNoodle** [comment]
Possible but hacky solution might be for damaged tents to use the "create damaged item" method that fur shelter kits use.

Other solutions include having a wall taking damage forcing the tent to collapse into an item (basically trigger the groundcloth action, sans prompt). Prevents odd tents like these from developing during gameplay, but still adds inconsistencies.

As for these tents specifically, one minor hack for tents that spawn damaged would be to use the non-interactive FEMA groundcloths.
