### ISSUE TITLE
Limbless/unarmored monsters and non-penetrating attack messages

### ISSUE THREAD

**Issue by articulateSPLINE** [CleverRaven/Cataclysm-DDA#19523]
![limblessarmorless](https://cloud.githubusercontent.com/assets/6367151/20655837/4f97c08a-b4db-11e6-994a-d4fcaca0c9cc.png)

Jenkins build 5968 on Win 8.1 and OSX 10.9, fresh games with no mods.

As shown above the game seems to be rolling attacks against limbs the victim monster doesn't have, and in the case of blobs stopped by armor the monster doesn't have.

Steps to recreate:
1) Spawn a robot
2) Spawn any other monster near the bot
3) Watch them fight

**Comment by Leland** [comment]
Still around as of 82a134dda422cbab2cf779d72961547e7e9755e1

**Comment by kevingranade** [comment]
Fixed by #28036
