### ISSUE TITLE
Weird sort order (unspecified?) for worn items

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19544]
Some menus display worn items as weirdly sorted, as if the sorting relied on `std::map` sort order rather than the index in `worn` vector.

Notably take off function.

**Comment by codemime** [comment]
Noted. I'll take a look.

**Comment by codemime** [comment]
> as if the sorting relied on std::map sort order rather than the index in worn vector.

They're sorted alphabetically (like the rest of items). This is probably undesirable.

**Comment by Cyrano7** [comment]
They are also sorted by condition. Reinforced items will appear first.

**Comment by codemime** [comment]
> They are also sorted by condition. Reinforced items will appear first.

I think it's a coincidence.
