### ISSUE TITLE
Aspic and rotten meat

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19552]
I'm no gourmand myself so I'm not sure if this is a bug or intentional, but apparently aspic can be successfully made from rotten meat. I'm guessing unlike perishable dishes, having rotten base ingredients doesn't result in a rotten product because aspic never rots.

I'm not sure if this is a bug only for aspic, or if it affects other nonperishable meat dishes like sausages, pickled meat, jerky, canned meat, etc.

**Comment by Cyrano7** [comment]
This bug has been around for awhile.
https://github.com/CleverRaven/Cataclysm-DDA/issues/18865
https://github.com/CleverRaven/Cataclysm-DDA/issues/13144
