### ISSUE TITLE
Issues with "spawn scaling factor" options

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#19576]
There are issues with "spawn scaling factor" options:

1. Value of "Item spawn scaling factor" option is set to 1.00 on world creation.
2. When pressing Enter and editing value comma is displayed as decimal separator, but is only possible to save non-integer value with dot as decimal separator.

See attached gif:

![ezgif com-1db1fcde34](https://cloud.githubusercontent.com/assets/16213433/20789001/eef1d482-b7c3-11e6-9144-f44739936710.gif)

These issues also affect other options where decimal separator is possible, for example "Spawn rate scaling factor" is set to 0 on world creation. 

Bug found on Windows 10 with tiles build 5991.

**Comment by BrettDong** [comment]
Looking into this...

**Comment by AMurkin** [comment]
Still an issue.

**Comment by illi-kun** [comment]
Superseded by #19720.
