### ISSUE TITLE
Food in containers doesn't cool down if container wasn't touched (e.g. was on the floor)

### ISSUE THREAD

**Issue by keyspace** [CleverRaven/Cataclysm-DDA#19577]
**System:** Arch Linux, C:DDA built from git fc7b3ba4bee27f473164d044b217b16384d7f8cd (yesterday). Don't remember experiencing ~ 2 weeks ago.

**Steps to reproduce:**

0. Start new vanilla game.
1. Cheat-wish tools, ingredients and skills for `broth` (that's `pot` and `hotplate`, `water` and `salt` and `dried mushrooms`, `cooking` 2).
2. Also cheat-wish 3 empty containers (tested with `small plastic bottle` and `opened aluminum can`).
3. Drop 2 empty containers *(a, b)* on the floor, leave 1 *(c)* in inventory.
4. Make 3 `broth`. When presented with a dialogue, pour into all three containers.
5. Drop *(c)*, pick up *(a)*.
5. Wait a long time (1800 heartbeats twice is enough, but same observed after a day).

**Result:**

_(a)_ and _(c)_ cooled down, _(b)_ didn't.

**Expected:**

Broth everywhere cools down equally.

**Notes:**

Tested while standing in a building, both early and late spring.

Perhaps this only happens for liquid food, since solid ones end up in the inventory without a dialogue. Didn't test what happens if inventory full.

I actually used `nearby fire`, not `hotplate`.

**Comment by Night-Pryanik** [comment]
It only happens if the container for hot liquid is not on the player position - both in inventory (obvious) and on the ground.
If the player places container right under his legs and then uses it to store hot liquid, then the liquid cools down properly. 

Suppose it's something related with `calc_rot( g->m.getabs( pos ) ) ` in `item::process_food`.

**Comment by kevingranade** [comment]
Could not reproduce by crafting a container and then dropping it, can reproduce by crafting directly into an adjacent container.

Current theory is that crafting code doesn't mark food poured into a container on the ground as active, so it's not processed.  If you pick it up or drop it it will get the active flag.

**Comment by kevingranade** [comment]
BTW, thanks for the good reproduction case, really helps.

**Comment by kevingranade** [comment]
Confirmed, I adjusted the liquid handling code to mark perishable liquids poured into a container on the ground as active.  No pull request though, I haven't handled all the cases yet.
