### ISSUE TITLE
Unable to pickup whole stack of harvested fruit/plants at once.

### ISSUE THREAD

**Issue by NickGrease** [CleverRaven/Cataclysm-DDA#19570]
Win 10 x64/0.C-20023-gb772ea3 (tiles)

Picking, say, an apple tree, the fruit is placed at your feet. Using 'e' or 'g' to pick it up, only picks up one (one apple out of a stack of 4 for example) at a time. Noticed this happen for picking Blueberries, Blackberries, Apples and Dandelions. Picking Pine trees, Willow, Blackjack doesn't seem to have this problem.

**Comment by ZenZen2** [comment]
It happens somtimes to butchered meat too.

**Comment by ZhilkinSerg** [comment]
Eggs are affected too.

**Comment by Tharn** [comment]
Same with cat tails and most of the stuff you get from shrubs.

**Comment by keyspace** [comment]
Guess it's safe to assume all items that come in stacks.

This only happens for harvested things. For example, picking dandelions gives `3 handfuls of dandelions (2)`. The items are (now) grouped by freshness (I assume), so if you pick those up, they become `handful of dandelions (6)`.

It is present in both `e`-pickup and `/`-inventory.

If you wish for 100 `chunk of meat`, it will all be in the same stack. If you drop them, wish 10 more, and drop those, too, it will be two stacks: `chunk of meat (100)` and `chunk of meat (10)`.

Looks like harvesting does not use this stacking mechanic.

**Comment by ZenZen2** [comment]
looks like not all stackable items, ive just killed a small rat and after butchering got 2x meat stacked (delicious), picked them up in one go.

**Comment by AMurkin** [comment]
Issue #19143?

**Comment by NickGrease** [comment]
That does appear to be the same issue - this one has a few more responses/info so I'll keep it open for now.

**Comment by Treah** [comment]
This issue should be merged with issue 19143 - That one also has proper labels.
