### ISSUE TITLE
0.C-20016-gda4f6a8 basement does not have staircase leading upstairs

### ISSUE THREAD

**Issue by dmitrymatveev** [CleverRaven/Cataclysm-DDA#19574]
Went down the stars into a basement of a house and can't get out. There was a closet/cabinet thing where I was spawned in the room instead of stars leading out of the basement... stuck

**Comment by dmitrymatveev** [comment]
[game_save_folders.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/623939/game_save_folders.zip)

**Comment by Zireael07** [comment]
Tried smashing and/or deconstructing the closet?

**Comment by ZhilkinSerg** [comment]
Trying to move furniture is also an option.

**Comment by dmitrymatveev** [comment]
There are two lockers and a boockshelf arranged in a corner from which I descended into the basement. None of which I have the strength to move :(

There just should not be anything on a staircase tile... I should be able to descend into the basement and appear to be blocked by furniture from proceeding into the room with only way back up.

**Comment by Zireael07** [comment]
Furniture spawning on stairs is a known bug.

**Comment by Zireael07** [comment]
As I said, you can smash them, not necessarily move.

**Comment by dmitrymatveev** [comment]
oh right... smashing is a thing in this game. thanks :)
