### ISSUE TITLE
Palette system for mapgen

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19578]
Looking at #19572 most of the mapgen is literally just specifying palettes.

I think I may be able to chalk up a simple palette system which would then work as such:
* Specify palette in one place
* Reference (by ids) an array of palettes at mapgen
* Override them in the same mapgen

A palette would contain the same specification of elements as mapgen, except for the point/line/rect ones. For example:

```
{
    "type": "palette",
    "id": "military_fence",
    "items": {
      "%": { "item": "fence_caught", "chance": 1 },
      "2": { "item": "forest", "chance": 1 }
    },
    "terrain": {
      " ": "t_thconc_floor",
      "!": "t_metal_floor"
    },
    "furniture": {
      " ": "f_chair"
    }
}
```

Multiple palettes could be loaded (in order), though overrides would have to be explicit. For example, if one palette specified that "c" is floor with chair, other that "c" is waxed floor, then the final result would be chair on waxed floor, not just waxed floor. To get just waxed floor, the second palette would need to specify that "c" is waxed floor with "f_null" on it.

Does it sound usable?

**Comment by codemime** [comment]
The idea is good, but it has a considerable disadvantage: one can never be sure which symbol means what by looking at `"mapgen"`s alone. That requires comparisons of different JSON files or "remembering", and can possibly make reviews harder (instead of easier).
