### ISSUE TITLE
Something intrinsically wrong with Fictional Weapons Mod fic_weapon file

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19588]
I experienced this problem when testing changes: if a json entry is modified (example: remove color from JHEC M128), any saves using the mod display a 1.1 error. This doesn't happen when editing other mod files.

**Comment by BrettDong** [comment]
How to reproduce? I didn't met this error.

**Comment by illi-kun** [comment]
Are you sure it's not client-side issue?

**Comment by BorkBorkGoesTheCode** [comment]
>How to reproduce? What is 1.1 error? Would you like to give a more detailed report of this issue?

Simple: Go to Fictional Weapons mod, open fic_weapons.json, remove color from item "id": "ficrico", save changes, start playing a world which uses the mod. None of the past experimentals fixed the issue.

>Are you sure it's not client-side issue?

Very specific bug. It doesn't happen when editing any other mods files.

**Comment by mutability** [comment]
Followed those instructions, couldn't reproduce it.

**Comment by mutability** [comment]
Things I have tried:

 * Make the json change, create a new world with mod enabled, create a character in that world. norepro.
 * Start from original json, create a world with mod enabled, create a character, save, exit, change json, restart, reload. norepro.
 * Start from original json, create a world with mod enabled, create a character, wish for a JHEC M128, save, exit, change json, restart, reload. norepro.

**Comment by BorkBorkGoesTheCode** [comment]
What OS are you using, and what editor?

**Comment by mutability** [comment]
Ubuntu and vi. What OS and editor are _you_ using?

**Comment by BorkBorkGoesTheCode** [comment]
I'm using Microsoft and notepad. Why italics?

**Comment by mutability** [comment]
Italics because it is basic information that you should have provided in the original bug report.

**Comment by BorkBorkGoesTheCode** [comment]
>Italics because it is basic information that you should have provided in the original bug report.

It is good practice to provide that information, since it simplifies the job of the bugtester. The issue is caused by an incompatability between notepad and that file, because editing other item files with notepad doesn't cause the error.

**Comment by BrettDong** [comment]
@BorkBorkGoesTheCode Would you like to upload your notepad-modified `fic_weapons.json`? Interesting issue.
