### ISSUE TITLE
Repairing damaged items skips full repair(||) and goes straight to (++)

### ISSUE THREAD

**Issue by NickGrease** [CleverRaven/Cataclysm-DDA#19582]
Win 10x64 0.C-20031-gea28c5b (#5991)(tiles)

Using Tailors Kit or Soldering Iron on damaged items always repairs to reinforced state regardless of option selected (Repair Once, Fully Repair no Reinforce, Repair to Success/Failure/Level Up)

`Ex.Repair (|.)->(|\)->(++) (Skips ||)`

Edit. Seems Repair Kits have this problem too.

**Comment by hmstanley** [comment]
yea,I've noticed this too.  You set the tool to only repair but NOT reinforce, but it still reinforces.

**Comment by mugling** [comment]
Think I know the cause of that one

**Comment by mugling** [comment]
Same cause as #19592
