### ISSUE TITLE
404 File not found on the side of a building

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#19598]
I see this random 404 file not found tag on the side of a building, I really don't know what to think about it. Its on the side of a (B) Bowling alley.
![capture](https://cloud.githubusercontent.com/assets/24307650/20846892/bb4872ea-b899-11e6-8ddc-771e0e34d8da.PNG)

**Comment by BorkBorkGoesTheCode** [comment]
Its an Easter egg.

**Comment by CoroNaut** [comment]
I thought of it that way before but how in the world would this be funny or cool to find in any way?

**Comment by mutability** [comment]
There should be a close button below the comment area that will do the trick

**Comment by BorkBorkGoesTheCode** [comment]
>There should be a close button below the comment area that will do the trick

I think @CoroNaut was asking about how to remove the 404 graffiti.

**Comment by mutability** [comment]
Oh. Modify tile_config.json for your chosen tileset and look at the sprite variations for t_wall, then.
