### ISSUE TITLE
Stats are taken into account twice when calculating turning penalty

### ISSUE THREAD

**Issue by keyspace** [CleverRaven/Cataclysm-DDA#19596]
EDIT: original title: **No more fumbling when driving a vehicle**

Observed driving `car` vehicle, zero-skilled character, default stats. Latest git (2907bee).

Started writing my findings here, but that turned into debugging.

Possibly relevant PRs:

* #17050 - Driving and traction rebalance
* #19275 - Vehicle propulsion overhaul

Possibly relevant commits:

* 693e465247446ea9527a0443fd256c093f200bff - introduced the code
* 35a6c481aba78c9fff72c28b9e62f20381ffcab3 - velocity rescaling

**Comment by mutability** [comment]
The first PR you linked starts with "No fumbling when driving straight - it was rather annoying and didn't have much impact"

**Comment by keyspace** [comment]
Ha! Incredible. I tucked those tabs, intending to review "later". :D

Guess it's OK to close.

**Comment by keyspace** [comment]
Actually, I still think there's a "logical" issue, so reopening.

I'd argue that making `penalty` stat-dependent (indirectly, via `skill`) is confusing. Here are partial notes I've taken while debugging.

-----

The "fumbling" is done when `penalty > skill`. `penalty` is `rng_float( 0.0f, handling_diff ) - skill`. `handling_diff` is gotten from `vehicle::handling_difficulty()`. `skill` is calculated as

```
std::min( 10.0f,
              u.get_skill_level( skill_driving ) +
              ( u.get_dex() + u.get_per() ) / 10.0f
        )
```

So at DEX 8, PER 8, this will result in an effective driving skill of 1.6.

The condition works out as follows:

```
rng_float( 0.0f, handling_diff ) - skill > skill
rng_float( 0.0f, handling_diff ) > 2 * skill
rng_float( 0.0f, handling_diff ) > 3.6
```

**Comment by mutability** [comment]
Yeah, if you're getting no fumbles while turning either then that does sound like a bug.

**Comment by keyspace** [comment]
Here's perhaps a more relevant code piece for the issue:

```
11130         if( penalty > 0.0f ) {
11130             // At 10 penalty (rather hard to get), we're taking 4 turns per turn                                                                                                                                                         
11131             cost = 100 * ( 1.0f + penalty / 2.5f );
11132         } else {
11133             // At 10 skill, with a perfect vehicle, we could turn up to 3 times per turn                                                                                                                                                 
11134             cost = std::max( u.get_speed(), 100 ) * ( 1.0f - ( -penalty / 10.0f ) * 2 / 3 );
11135         }
```

**Comment by keyspace** [comment]
This issue is a mess and a braindump.

@Coolthulhu, since the (perceived) issue [originated with your PR](https://github.com/CleverRaven/Cataclysm-DDA/pull/17050), would you like me to rewrite it more concisely?

**Comment by Coolthulhu** [comment]
Go for it
