### ISSUE TITLE
Auto-Safe Mode not sticking when enabled/disabled in-game.

### ISSUE THREAD

**Issue by NickGrease** [CleverRaven/Cataclysm-DDA#19597]
Win10 x64 0.C-20040-g20172c1 (#5995)(tiles)

Changing Auto-Safe mode in-in-game (either through settings or keybind) doesn't seem to work, only changes during the main menu/pre-load seem to stick. ie With Auto-Safe mode disabled in settings before starting a game, it will always be disabled, even if enabled in-game.

Related #19467 (to my original title)

**Comment by tswood** [comment]
Can confirm that I encountered this behavior while working on #19522.

**Comment by mugling** [comment]
May explain why I'm struggling to test that PR. Would be best if same PR fixed at the same time
