### ISSUE TITLE
Lava does not burn nearby flammables

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#19595]
I've stumbled upon some lava in the forest with some trees, shrubs, cobwebs and wooden stick near and directly over lava pools. There were no sign of fire. Shouldn't all flammable objects burn near lava?

![lava_webs_wood](https://cloud.githubusercontent.com/assets/16213433/20837777/a54bdece-b8b6-11e6-8661-1e87e0c3f10c.png)

Windows 10 tiles build 5994

**Comment by CoroNaut** [comment]
Maybe the lava should be generated and then anything flammable that is nearby could be deleted so random forest fires dont happen.

**Comment by ZhilkinSerg** [comment]
Addressed in #28629.
