### ISSUE TITLE
Failed update?

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19601]
Just updated by the launcher as I do every day or so. Rather than updating the game, this time it deleted files, including the exe. This is a hiccup on my end, or anyone else having this issue? Windows 64bit tileset version.

**Comment by NickGrease** [comment]
I've been using CDDA-Game-Launcher 1.3.8 for the past week or so, updating the game every day, as well as just now from 5995->5996 with no problems - same system - Win10 x64 as well as 64 bit game version.

**Comment by Regularitee** [comment]
Got a message from someone else saying it wasn't just me, so guess it wasn't just a fluke.

**Comment by CoroNaut** [comment]
My launcher doesn't say there is an update at all.

**Comment by ChucklesTheBeard** [comment]
This should presumably be submitted to https://github.com/remyroy/CDDA-Game-Launcher/issues instead

**Comment by illi-kun** [comment]
@remyroy you may be interested in this.
@Regularitee it seems that ChucklesTheBeard states the correct note: it's an issue of the launcher.

**Comment by Regularitee** [comment]
Alright, closing the issue since it appears it wasn't an issue with the github files.

**Comment by remyroy** [comment]
See the launcher FAQ about getting your files deleted: http://smf.cataclysmdda.com/index.php?topic=11895.0 . If there is still an issue, please [report it on the proper repository](https://github.com/remyroy/CDDA-Game-Launcher/issues/new).
