### ISSUE TITLE
Minireactor is (almost) free power

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19615]
Reactors got reworked in #19426

We went with the safe option of making them too strong rather than too weak. The power per plutonium cell is effectively infinite - you can expect a single cell to last a night of powering a laser rifle firing auto-continuously.

**Comment by mugling** [comment]
They're not free for propulsion (although generous)

The issue is partly that electrical power for hand tools is incredibly generous. For example boiling water is like 2kJ. Really that should be very difficult which would give the other stoves much more of a niche as matched in reality.

**Comment by Coolthulhu** [comment]
> They're not free for propulsion (although generous)

You'll most likely drain a full tank of gas before a single plutonium cell.

I just tested it: drained more than 5L of gas from factory-fresh Car-brand car before I drained a single charge (1/500 of a cell) from a weighted down (to 1.5 ton) atomic sports car. Both were traveling at almost 200 km/h.
This means that plutonium cell is "worth" at least 2500L of gas for purposes of propulsion.

**Comment by mugling** [comment]
Suggests needs rescale by factor of 100

**Comment by Coolthulhu** [comment]
Preferably as a part of fuel rebalance, with tests.

**Comment by Asmageddon** [comment]
Not sure since right now it doesn't work, but at this point minireactor is the only possibility for electric engines.
