### ISSUE TITLE
Items in stealing menu are all in same letter

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#19611]
![2016-12-03 9 45 48](https://cloud.githubusercontent.com/assets/21075502/20859738/24e0208c-b9a2-11e6-9043-365cc78350d5.png)

**Comment by codemime** [comment]
Can't reproduce. Under what circumstances did that happen?

**Comment by patternoia** [comment]
I had this when a copy of an NPC was passed to the menu-building lambda instead of a reference. Was there smth changed since then?

**Comment by BrettDong** [comment]
Can't reproduce. Under what circumstances did that happen?

I spawned a NPC through debug menu, and tried to steal something from
him, then the bug occurred.

**Comment by patternoia** [comment]
Confirm this on the latest build from CI (6017). It has the same inv. letter both on static npcs in the evac shelter and those spawned through debug menu.

**Comment by Leland** [comment]
Still an issue as of e1fe61f. Easily repeatable.

<img width="530" alt="screen shot 2017-08-18 at 10 22 36 pm" src="https://user-images.githubusercontent.com/714017/29482663-cc5c1622-8463-11e7-83d6-db295d1aa3fa.png">

**Comment by laeaton2001** [comment]
From what I can tell this is caused by assign_empty_invlet in inventory.cpp referencing the player instead of the NPC but I don't know my way around the code well enough to fix it yet.
