### ISSUE TITLE
Game wont start after successful build - Assertion failed

### ISSUE THREAD

**Issue by bpwatts** [CleverRaven/Cataclysm-DDA#19620]
Hey folks, just did a pull and build on my recently updated Mac and found I couldn't play due to the below error message. Not sure where to go from there

Macintosh-2:Cataclysm-DDA_tiles admin$ ./cataclysm-tiles 
Assertion failed: (frozen), function all, file src/item_factory.cpp, line 2301.
Abort trap: 6

**Comment by mugling** [comment]
See #19620

**Comment by bpwatts** [comment]
Isn't that my issue number?

**Comment by mugling** [comment]
Sorry, that should have been #19618

**Comment by bpwatts** [comment]
Ahh gotcha :) Was quite confused for a second. No worries. I can wait for a fix! Let that contributor sleep!

**Comment by 1skandar** [comment]
Just as a note, broken in Windows as well.

**Comment by bpwatts** [comment]
A million thank yous, @mugling @mutability @illi-kun
