### ISSUE TITLE
"Paper shot cartridge with none" found in gun safe

### ISSUE THREAD

**Issue by RBrandon** [CleverRaven/Cataclysm-DDA#19639]
I found this item in a gun safe in a basement. In the item description it says, "seeing this is a bug."

**Comment by mugling** [comment]
Tentatively the recent changes to item groups (#19584), any thoughts @sethsimon, unrelated?

**Comment by sethsimon** [comment]
I don't think so. In `Item_modifier::modify`, there's a check that it wouldn't pass (because `flintcock_shot` has type `AMMO`):
```
if( new_item.is_tool() || new_item.is_gun() || new_item.is_magazine() ) {
    // check other restrictions, roll the ammo and magazine chances
}
```

But I'd be happy to take a look at it anyway as soon as my outstanding PRs are done.

**Comment by mugling** [comment]
@RBrandon what version?

**Comment by RBrandon** [comment]
It was found playing on 0.C-20040-g20172c1. I generated the world on an older version from Nov. 17. I'm not sure when items of this kind are generated.

**Comment by sethsimon** [comment]
In master, I found a flintlock carbine with a none in a basement safe (note the `seeing this is a bug`). There's some code that strips null contents when saving, but I verified it with gdb.
![none](https://cloud.githubusercontent.com/assets/16765166/20912565/159bc02a-bb3e-11e6-87f9-f4c421d3543f.png)

**Comment by BorkBorkGoesTheCode** [comment]
>Tentatively the recent changes to item groups (#19584), any thoughts @sethsimon, unrelated?

Preexisting. I don't know what causes it.

Could the magazine and ammo entries in basement_guns cause this?
