### ISSUE TITLE
Specifying Roads for rotating specials causes ugly, unconnected overmap tiles

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#19635]
<a href="http://imgur.com/7zP1iRr"><img src="http://i.imgur.com/7zP1iRr.png?1" title="source: imgur.com" /></a>

See above, a custom-made township.  The roads are specified to run from north to south, and have until, I presume, #19518

**Comment by codemime** [comment]
I need more details.

**Comment by pisskop** [comment]
https://github.com/pisskop/PKs_Rebalancing/blob/master/pk_overmap.json#L184

I could update a save, however It might simply be faster to generate a world with the mod enabled.  All the parts are generic structures defined by the base game.

**Comment by codemime** [comment]
The issue existed before #19518, though it looked different. Thanks for the link.

**Comment by pisskop** [comment]
Its simply seems to have manifested itself since then
