### ISSUE TITLE
Console version have key asignments 'z' and 'Z' (zoom) which does nothing

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#19643]
Omit these options or implement zoom?

**Comment by codemime** [comment]
How would you implement it for the console version?

**Comment by AMurkin** [comment]
Maybe it could by fontsize*k at redraw?

**Comment by codemime** [comment]
That won't work for pure consoles - the game uses `ncurses` library, and there's no reliable cross-platform way of changing font size of a terminal, AFAIK.

However, that would work in the pseudo-console mode (SDL glyphs), but would also inevitably require using two fonts sizes  (to keep the sidebar and other menus unaffected). I doubt it's worth the effort for now, but you're free to try and implement it.

**Comment by AMurkin** [comment]
Yeah, i didn't realize that all glyphs must be the same size.
Then these options should be hidden in console version.

**Comment by illi-kun** [comment]
> Then these options should be hidden in console version.

This is a wrong approach: the same keybinding configuration file is used for both tiles and curses version, so it's weird that some keys can be bound to some hidden commands.

Generally, I estimate this as a really minor issue (if it's issue at all).

**Comment by muravey-omsk** [comment]
What about set another default keys for zoom? That's free keys for another action.
