### ISSUE TITLE
Dual leg splints not working?

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19645]
Need some confirmation on this one.

I've had two separate characters break both legs (god damned acid puddles), and both times I attempted to splint both legs, only one leg healed. The other would not heal after several additional days or even weeks of waiting (AFTER the first leg already healed), so both times I just gave up and went to find a Stem Cell treatment. And yes, leg splints were each set to a separate leg, and not both applied to the same leg.

Has anyone else encountered this issue, or could it just be a product of the randomness of the healing process?

**Comment by CoroNaut** [comment]
Build #?

**Comment by Regularitee** [comment]
Most recent. But it's been floating around a while. At first I thought it was just a fluke, so didn't take note, but it happened again.

Windows Tileset 64-bit

**Comment by Coolthulhu** [comment]
It's RNG. Broken limb healing is horribly designed ancient idea: 24 rolls per day (forgot exact chance), giving a ~95% chance to heal the limb in two weeks.
It needs to be changed to an effect or something like that.

**Comment by CoroNaut** [comment]
I've never had my legs broken for longer than a week so I figured there was a hard limit.
