### ISSUE TITLE
Open door shouldnt slow player movement (car).

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#19640]
It already takes time to open a door and to close it behind you. An open door shouldnt slow the players movement.

**Comment by ZhilkinSerg** [comment]
Entering a car (even through opened door) is slower than just passing by.

**Comment by sick-trigger** [comment]
that's modelled by moving from the door 'tile' to the seat. Moving onto the actual door just means moving into the space that the door occupies when it's closed, which is really only a couple of inches.

**Comment by ZenZen2** [comment]
You have to open a door and close behind you. You get a slow down by steping on the seat tile.
An open door is still a time lose, even after a slowdown removal, because you still have to pass ist.

**Comment by keyspace** [comment]
Open doors [like this](http://images.hgmsites.net/lrg/2010-scion-tc-2-door-hb-man-natl-open-doors_100256279_l.jpg) and the need to "walk around" them are effectively modeled by having an explicit `OBSTACLE` flag (see `data/json/vehicle_parts.json`), as suggested by @ZhilkinSerg's comment.

The penalty is of significance only when escaping monsters. Even then, monsters 

Although removing the flag would take less time than it took me to write the comment, IMO this is a non-issue. If the desire to have OP implemented is overwhelming, it can be done in a mod.

Request to close.

**Comment by ZenZen2** [comment]
Looks like to many dislike this idea, im closing this.
