### ISSUE TITLE
Tread balancing

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19646]
In reality treads are notable for much higher off-road performance than wheels, due to the fact they have much lower ground pressure (a far larger surface area in contact with the ground, compared to tires). This not only provides better grip on the terrain, but makes the vehicle far more resistant to sinking into mud and soft terrain. The cost for this is much lower fuel economy due to the friction and weight involved in moving a giant steel belt.

In a nutshell, this means treads :
- Treads have far better off-road performance than tires
- Treads have worse fuel economy overall, particularly on pavement, where their advantages over tires are nullified

However, looking at the game code, none of this seems to be represented in game, as far as I can tell. They perform about identically to the wide tires, both in terms of fuel economy and off-road performance.

I would recommend giving tread units much higher width (or whichever value represents off-road effectiveness), as well as higher weight to simulate the lower fuel economy. I think this would make them  fill a niche separate to that of existing tires.

**Comment by Xpyder** [comment]
An artificially high weight could cause jacking issues in large heavy vehicles.  But I would be in favor of your goals here

**Comment by ZhilkinSerg** [comment]
I believe treads can be replaced without lifting the whole vehicle. You just put the track on ground, roll the vehicle over it and then you make the track continuous.

https://www.youtube.com/watch?v=r8eaT3GEWQI

That looks heavy but manageable without having a tool with LIFT and JACK qualities 9999.

**Comment by Xpyder** [comment]
IRL? for sure.  But given how similar they are to wheels in the game I was assuming they need the vehicle lifted to install them.

One thing that I've wanted for a long time that's always been missing is that wheel/track install points be a separate part from the tires themselves.  This would allow separating the skill and time required to remove or replace them from the time to install a completely new location.

**Comment by DangerNoodle** [comment]
Treads already have massive weight, that is part of their current balancing relative to tires. They also tend to have a massive size (60 seems to be common), but I do not know how this affects traction.

**Comment by Regularitee** [comment]
Actually, they seem mostly on par with tires. For example, steel tracks (the mid-level ones) are roughly identical with 32" armoured tires in weight and size. Similarly the low-end rubber tracks also have tires which are functionally identical to them. Only the high end tracks (reinforced tracks) do not overlap with tires at all.

**Comment by DangerNoodle** [comment]
Ah, peculiar. Granted, I have had little experience with the non-armored treads, as they seem rare. Overall it seems that I have only ever seen them on vehicles in the Tanks and Other Vehicles mod, where armored treads are most common.

**Comment by hmstanley** [comment]
Seeing that they aren't represented, how could we balance them relative to the tires and other wheels?  I mean, it would be nice to have a way to remove and fix IFV's if they are lacking treads? I did this once, but cheated in that I gained strength to lift the vehicle. 

I would think there would be negatives like de-tracking and other problems (stuck in mud?) or in one current situation, you can only pass a bridge if you ram the vehicles or blow them up considering the IFV's/Tank size. 

I would love to figure out how to make these more interesting and hard mid/late game additions to the trek across the dead lands.

**Comment by BorkBorkGoesTheCode** [comment]
Tracks are more labor-intensive to maintain compared to wheels; they also tear up roadways under some circumstances, depending on vehicle weight and track design.

**Comment by kevingranade** [comment]
Tracks are more labor-intensive to maintain compared to wheels; they also
tear up roadways under some circumstances, depending on vehicle weight and
track design.

There's an interesting nuance here, due to the way tracks work, they will
either damage the surface they are running on or damage themselves, the
only question is which one is harder.  So if a track system is 'road safe'
it simply means it's going to wear itself faster.

Not totally sure how to represent this as we don't have tire wear, we'll
probably need to ignore it, at least for a first cut.

**Comment by DangerNoodle** [comment]
There is also the potential additions to steering behavior that would be awkward to implement.

**Comment by kevingranade** [comment]
We'd probably ignore the steering stuff at first, it's not required in
order to add treads as a high traction option.

**Comment by DangerNoodle** [comment]
True. Plus, I cannot even imagine how such behavior would be handled in case of halftracks and other mixed steering vehicles.

**Comment by Barhandar** [comment]
>Plus, I cannot even imagine how such behavior would be handled in case of halftracks and other mixed steering vehicles.

Pick the powered set, have steering match it. If engine drives the tracks on halftrack, it will be able to rotate (mostly - rotation entirely in place is only possible if you can run tracks in different directions at same time, e.g. electric transmission) in place, wheels or not. If it drives the wheels, the vehicle won't be able to rotate in place.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
