### ISSUE TITLE
linux compile error

### ISSUE THREAD

**Issue by VZIKL** [CleverRaven/Cataclysm-DDA#19656]
src/string_id.h:66:50: error: instantiation of variable 'string_id<ter_t>::NULL_ID' required here, but no definition is available [-Werror,-Wundefined-var-template]
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}
                                                 ^
src/mapdata.h:70:50: note: in instantiation of member function 'string_id<ter_t>::string_id' requested here
                      drop_group("EMPTY_GROUP"), ter_set(NULL_ID), furn_set(NULL_ID) {};
                                                 ^
src/string_id.h:154:35: note: forward declaration of template entity is here
        static const string_id<T> NULL_ID;
                                  ^
src/string_id.h:66:50: note: add an explicit instantiation declaration to suppress this warning if 'string_id<ter_t>::NULL_ID' is explicitly instantiated in another translation unit
        string_id( const null_id_type & ) : _id( NULL_ID._id ), _cid( NULL_ID._cid ) {}

**Comment by mugling** [comment]
As per #19197 assign a developer although this isn't an obligation so please feel free to unassign if this isn't relating to your current work

**Comment by codemime** [comment]
My clang is a bit outdated: it doesn't support `-Wundefined-var-template` so I can't properly check my fix until I update the compiler.

**Comment by codemime** [comment]
@VZIKL You can suppress the check as a temporary solution.

**Comment by VZIKL** [comment]
use gcc isn't error :D
