### ISSUE TITLE
Allow vehicle siphoning to siphon to another tank on the vehicle

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#19650]
I would like to make the suggestion to allow the siphon command to move liquid between tanks on the same vehicle. This addition would be simple, neat, and help players to manage their vehicle.

**Comment by Cosmitz** [comment]
I'm just bumping this as a thing that still should be done. Siphoning to and from the same vehicle should be possible, as well as siphoning from a vehicle to another vehicle.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.

**Comment by nornagon** [comment]
I'd love to have this ability, it's super tedious to move fuel between tanks via a gallon jug or something. Any chance this could be reopened?

**Comment by ArcanErasmus** [comment]
I am going to chime in here, I would **really** like the ability to merge half-full tanks, or just to reorganize my liquids so they are easier to see on the list.
