### ISSUE TITLE
Sleeping in pickup bed counts as pavement (win exp 5643)

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#19653]
As shown in screenshots, i tried to sleep in a pickup bed tile with frame and trunk (and a pile of clothes) but didn't count.  I really needed that sleep, man.

![2016-12-05 18_41_45-greenshot](https://cloud.githubusercontent.com/assets/19196781/20913116/11cc2246-bb43-11e6-97d3-f3d96b0d1dca.jpg)
![2016-12-05 18_41_59-greenshot](https://cloud.githubusercontent.com/assets/19196781/20913117/11cc4aaa-bb43-11e6-88ca-818091088de5.jpg)

**Comment by mugling** [comment]
> pickup bed tile

That's not the same thing as an actual vehicle bed part

**Comment by busterbogheart** [comment]
Right but i definitely shouldn't be on the pavement.

**Comment by Coolthulhu** [comment]
It lists pavement because there is no bonus for a vehicle part.

**Comment by busterbogheart** [comment]
Did seem something was off though, because I dropped a bunch of clothes and didn't see any message indicating that I was snuggling them.  Is this a non issue then?

**Comment by kevingranade** [comment]
It's valid IMO, this should work, but I'm not sure how easy that will be to
handle.

**Comment by Coolthulhu** [comment]
The only thing that needs changing here is description: the `sleep_spot` function already handles vehicle spots. Possibly by making vehicle trunk a bit better than pavement (say, as good as regular floor: +1 to sleepy).

The biggest problem here is that most sleep check code is horrible special cased mess stated in 3 places:
* `player::floor_bedding_warmth` - beds (all types) have hardcoded warmth bonuses
* `player::try_to_sleep` - just for "this is comfortable/uncomfortable" message (horrible! should be something like `sleep_spot > 0`)
* `player::sleep_spot` - calculates sleep difficulty, BUT also includes non-terrain effects, such as stims, meaning the `sleep_spot > 0` above is unusable, without first splitting this into two functions

Sleep spot mechanics are also insignificant and could use a big buff: a cup of beer is twice as effective at helping with sleep as moving from cold wooden floor to a proper bed.
And they only matter for falling asleep, not maintaining sleep: once you're tired (or drunk enough) a window frame full of broken glass is not any worse for maintaining sleep than bed+blanket, except for very cold temperatures (cold enough to wake up).
