### ISSUE TITLE
Internal Temperature affected by hit points.

### ISSUE THREAD

**Issue by Brian361** [CleverRaven/Cataclysm-DDA#19665]
While I'm not sure this could ever have an impact on non-cheated characters, having high HP on limbs can raise internal temperature to the point of permanently incapacitating a character.
This might have a slight effect on standard characters as they would always be slightly warmer/colder depending on starting STR. I'm not sure if this is intentional.

To recreate: Set limb HP to large amounts using the debug menu.
![debug](https://cloud.githubusercontent.com/assets/5396252/20953041/9d4d4708-bbfe-11e6-8ef9-b21ce6d09e8a.png)

**Comment by Coolthulhu** [comment]
It's purely a debug thing. The temperature is affected by relative difference from max HP, meaning that the only way to overheat from it is debugging hp above max. Same for supercooling - it doesn't matter if you have 0 hp out of million or out of 20.
