### ISSUE TITLE
prioritize {m:flesh} no longer marks bodies

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#19662]
To help me spot unpulped zombies I usually prioritize (+) "{m:flesh}" and filter "-pulped", but that prioritize isn't working anymore.

**Comment by Coolthulhu** [comment]
Try without the braces, just "m:flesh".

**Comment by Xpyder** [comment]
nope, doesn't work.

note: "{m:paper}" and "m:paper" both work, so it's almost certainly something about either corpses or the Flesh tag.
