### ISSUE TITLE
Vehicle Additions mod's ammo racks can only store liquids

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19675]
I've noticed that ammo racks can be... filled with liquid. The vehicle interface considers them liquid tanks. This bug is a few weeks old, so I assumed someone would have reported it or fixed it by now, but I don't see an open issue for it.

For that matter, are ammo racks supposed to have storage space for ammo? I notice they don't have their own storage capacity, but also that they don't restrict you to only building on cargo spaces (like UPS rechargers do). Maybe I'm just misunderstanding their proper use.

**Comment by Night-Pryanik** [comment]
Closing in favor of #23479.
