### ISSUE TITLE
pumpkins are not a vegetable they are fruits

### ISSUE THREAD

**Issue by harlimat** [CleverRaven/Cataclysm-DDA#19672]
I know it might be hard to comprehend but it bugs me to no end that pumpkins are classified as a veggy, when they are fruits.

        "type" : "COMESTIBLE",
        "id" : "pumpkin",
        "name" : "pumpkin",
        "weight" : 600,
        "color" : "light_red",
        "spoils_in" : 240,
        "comestible_type" : "FOOD",
        "symbol" : "%",
        "quench" : 5,
        "healthy" : 2,
        "nutrition" : 22,
        "description" : "A large vegetable, about the size of your head.  Not very tasty raw, but is great for cooking.",
        "price" : 750,
"material" : "veggy"

**Comment by codemime** [comment]
More precisely, they are berries.

**Comment by harlimat** [comment]
true of course, the biggest one as far as i know, though i was not sure if that classification is even in the game, but now that you mention it, of course that makes sense.

**Comment by Reclusive-reptile** [comment]
For that matter so are tomatoes. The culinary use of some of these comestibles is at odds with their botanical definition, which is important to address now that material determines vitamin content.

**Comment by Coolthulhu** [comment]
Pretty sure the fruit/veggy hate traits are supposed to be psychological, not biological aversions to fruits/vegetables themselves.
As such they should probably depend on cultural usage, not biology.

Though we should move away from fruit/veggy split and have one "veggy" material with "VEGETABLE_ALLERGY" and "FRUIT_ALLERGY" flags.

**Comment by codemime** [comment]
> Though we should move away from fruit/veggy split and have one "veggy" material with "VEGETABLE_ALLERGY" and "FRUIT_ALLERGY" flags.

What are the benefits?

**Comment by Coolthulhu** [comment]
> What are the benefits?

Currently just one less weird material, but it would help later with crafting flag passing.

**Comment by illi-kun** [comment]
Current definition is correct from culinary POV. Botanical classification is frequently surprising for common person, so I don't want to switch the game to it.
