### ISSUE TITLE
Rags dont work anymore

### ISSUE THREAD

**Issue by Dantheman1337** [CleverRaven/Cataclysm-DDA#19678]
Yeah you cant use rags... says you dont have enough of them even though you might be standing in a huge pile. This breaks tailoring.

**Comment by Coolthulhu** [comment]
Sounds like I missed some edge case in #18882
I explicitly tested rags there, though.

How does your setup look like? Can you reproduce it by just spawning a stack of rags in debug mode?
If not, a save could be useful. Or better: a description on how to get it to stop working.
