### ISSUE TITLE
Item fabrication was broken in build 6027

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#19679]
Start a new game. Grab a stick or 2х4 and smash nearest bed to get some rags. Make sure there are at least 3 rags on the ground. Got to fabrication menu and try to make some hand wraps and see that it is not possible due to missing ingredients.

This behavior started in build 6027.

I guess this commit broke that: https://github.com/CleverRaven/Cataclysm-DDA/commit/7a966a15460a97ed1f182816ebb8a889d9ce56b9

**Comment by Xetari** [comment]
Also can't craft items that require pipes despite having it nearby or in inventory.

**Comment by CarolAnd** [comment]
I can confirm this is still an issue with 6029. I just started a character with a fresh world, and trying to make things is strange. Pull down some curtains and the two sheets don't count as sheets for a sling, cut up one sheet to make rags, can't use the rags to make hand warmers even though I have almost twenty of them.

**Comment by mugling** [comment]
Tentatively #18882?

**Comment by Coolthulhu** [comment]
Looks like more general version of #19678 

I'm testing right now.

**Comment by RBrandon** [comment]
This is certainly interesting.

![image](https://cloud.githubusercontent.com/assets/476404/21010178/b0561684-bd18-11e6-9abd-2dc8f36354db.png)

There are 13 heavy sticks near me, but I can only craft with them if I use ALL of them. If I walk far enough away from the stack with one stick I can use it to craft again.

**Comment by Tharn** [comment]
Can confirm this also with Plastic Chunks & Leather Patches.
