### ISSUE TITLE
Crash on settings save O.C-20148-gf1309d6 (O.C 6024)

### ISSUE THREAD

**Issue by Greiger** [CleverRaven/Cataclysm-DDA#19673]
Howdy, just recently downloaded the latest experimental and I've been seeing a crash in the settings screen.  With an assertion failed error mentioning factory.cpp.

However after the crash the game will reload properly with the proper settings indicating it is successfully saving the settings before the crash.  Since you need to restart the game for settings to take effect anyway, this seems pretty minor.  But there may be other problems stemming from this.

Oop just missed a similar issue.  The title made me think it was something else when I did a quick skim over current issues. While I was not setting a tileset (I was disabling tiles entirely) this may be a duplicate of #19661.   Don't know how to tag it as such.

**Comment by codemime** [comment]
Yes, it's the same issue.
