### ISSUE TITLE
Food stacks are not getting collected at once

### ISSUE THREAD

**Issue by lucasmr** [CleverRaven/Cataclysm-DDA#19682]
On latest build, try to get an egg stack from a container. Even having volume and weight available, you only grab one egg everytime you try to grab the full stack.
I think there is something about different item spoilage. Cattail stalks show the same behaviour.

**Comment by BorkBorkGoesTheCode** [comment]
Can confirm: 17 bird eggs (1).

**Comment by AdonaiJr** [comment]
Can confirm, berries in general.

**Comment by ZenZen2** [comment]
i think that this may be a duplicate of #19143 but im not sure

**Comment by Asmageddon** [comment]
This is definitely not resolved - picking up only a single item out of a stack happens all the time with butchering products - but it's inconsistent and I have not been able to figure out when and why it happens or doesn't, sometimes I go for long stretches of time without it happening, sometimes it happens with every second corpse.
