### ISSUE TITLE
Mushroom effects are spoilered by crafting recipes helper

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#19695]
Not sure if this is intentional but "generic" mushrooms are described with the same warning no matter what they are. However, the "You could use it to craft" section gives it away. See these two examples:

![image](https://cloud.githubusercontent.com/assets/19356629/21054475/c699fa9e-bde2-11e6-800c-2095315ad5db.png)
![image](https://cloud.githubusercontent.com/assets/19356629/21054478/c96c418c-bde2-11e6-9e0b-a684385a1584.png)

**Comment by codemime** [comment]
It's a known side effect of a limitation in our crafting system (see #14950 and #15121).

**Comment by DangerNoodle** [comment]
It is possible that the code that displays crafting possibilities could have an 'if' statement checking for the absence of the item flag that hides their properties. Though making the crafting help reveal itself if your survival skill is high enough to reveal identify it would further complicate this.

I assume that checking the recipe screen would still reveal the presence of the right type of mushroom though.

**Comment by CoroNaut** [comment]
If this is only done to a select few items, I'm afraid people may think of this addition as a bug or an inconsistency in the crafting menu.

**Comment by Coolthulhu** [comment]
Those shrooms are only trouble. So much trouble for such a minuscule mechanic.
Unless someone wants to implement flag passing right now, it would be best to just migrate them to edible shrooms, maybe hack in a "poisonous" flag and handle it in consumption, then delete the remains.

**Comment by bouchacha** [comment]
It doesn't look like psilocybin mushrooms are even found naturally in New England: https://en.wikipedia.org/wiki/Psilocybe#Distribution_and_habitat

Removal seems fine. Are there even any benefits to doing shrooms aside from LPing a hippie?

**Comment by BorkBorkGoesTheCode** [comment]
The references say that Psilocybe has potential as an invasive species.

**Comment by elricsfate** [comment]
Even though they are not found naturally it makes sense they might still be found due to recreational users @bouchacha.

With that said, it probably makes more sense to prevent them from spawning naturally for now, even if they are later found on particular corpses or places (Like the basement grow op)
