### ISSUE TITLE
Tail mutations blocking things they really shouldn't

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19698]
By which I mean they prevent you from wearing things like "Hard Leg Guards" or "Metal Leg Guards", which don't even go above the knee when worn, so there's no logical way having a tail would prevent their use.

**Comment by keyspace** [comment]
Tail mutations restrict leg bodyparts. This is a code limitation.

It could be said that tail mutations add another body part, which is then pigeonholed into the existing body structure. Currently this works in some cases (like figuring out warmth, armor, etc.), but not others (like OP).

An implementation to address this "without hacks" would require a massive overhaul of the `bodypart` system, to allow for addition (and removal!) of parts.

**Comment by kevingranade** [comment]
If all it were tracking was impingement of mutated body parts with
clothing, it wouldn't have to modify the rest of the bodypart code, but it
WOULD have to add data to every effected article of clothing, which is a
non-starter.

**Comment by Regularitee** [comment]
I found a potential work around: From my testing and modding of clothes, the tail mutation allows the wearing of any pants so long as they contain cotton or leather. That's why, for example, **steel leg guards** (steel + leather) can be worn, while **hard leg guards** (plastic + neoprene) cannot.

So one potential solution is to make neoprene classified as a "soft" material rather than a "hard" one.

The other is simply to add cotton or leather to all leg slot items which should be tail compatible.

**Comment by keyspace** [comment]
A similar issue - #18416 - made `fur` soft.

`neoprene` description (neoprene sheet, in `data/json/items/generic.json`) says

> Can be used to craft light and stretchable clothing.

IMO classifying `neoprene` as soft is warranted.

-----

Neoprene's been [added](https://github.com/CleverRaven/Cataclysm-DDA/commit/e2b457ef80bef938de831390a48ede11b61430c7) before `is_soft` [was JSONised](https://github.com/CleverRaven/Cataclysm-DDA/commit/2c0a3f378004e512d026b213f508fe20c9c73330).

-----

A list of wearable items (from `data/json`) that have `neoprene` but not `{cotton,leather,fur}`:

* `boots_h20survivor` (pair of survivor wetsuit boots)
* `armguard_hard` (pair of hard arm guards)
* `gloves_h20survivor` (pair of survivor wetsuit gloves)
* `h20survivor_suit` (survivor wetsuit)
* `hood_h20survivor` (survivor wetsuit hood)
* `legguard_hard` (pair of hard leg guards)
* `stillsuit` (WS-47G moisture retention suit)

Making neoprene soft will make all these items wearable by all mutants AFAIU. None have `ALLOWS_NATURAL_ATTACKS`.

**Comment by Zireael07** [comment]
I agree that neoprene should be soft in light of the description.

**Comment by Regularitee** [comment]
Neoprene given a "soft" tag as per discussion here. Should now be tail-compatible.
