### ISSUE TITLE
Driving looks very choppy compared to earlier version

### ISSUE THREAD

**Issue by Retroman000** [CleverRaven/Cataclysm-DDA#19709]
So, sorry if this doesn't make sense, but I'm trying to figure out what exactly I'm trying to get across here.

I first started playing the game maybe 6-7 months ago, and haven't updated since then. After taking a hiatus from playing for a couple months (busy with irl stuff), I decided now's as good a time as ever to update. Everything works all fine from what I can tell, but one thing that's really bothering me is how things look while driving. From what I remember driving in-game on the last version I played, the scenery going by whenever you drove would, like, "slide by". When you waited for a turn, you'd kinda slide from your current position to the position you ended up at, if that makes sense. Now, however, it looks like your character and vehicle simply teleports from the starting position to the end position.

I just booted up the older version to make sure I'm not imagining things, and yeah, it definitely looked a lot smoother. I'm using the same tileset I always have, Mshock32modded, on both versions. I believe the specific versions are 0.C-16996-g9c50c17 that I played originally, and 0.C-20189-g6be479a that I just now updated to. Is this a problem with the latest experimental, just some option I forgot to change, etc.? I'm on Windows, if it makes any difference.

**Comment by codemime** [comment]
This may be related to screen updates.

**Comment by ZenZen2** [comment]
not only driving --> #19317

**Comment by Leland** [comment]
Should be fixed with #20218
