### ISSUE TITLE
Inventory menu sometimes fails to expand vertically

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19704]
Not sure what triggers it. Doesn't happen in inventory menu, but does in use menu.

![broken menu](https://cloud.githubusercontent.com/assets/1878860/21069281/8fcec044-be78-11e6-9cfd-8ff73c5f6bc0.png)

**Comment by codemime** [comment]
That's really weird.

**Comment by CoroNaut** [comment]
I thought someone already talked about the super awkward use menu. It is very awkward when I use it as well.

**Comment by kevingranade** [comment]
Odd, I'm not seeing an issue at all, is it possible something in the wincurses library isn't operating correctly?

**Comment by Coolthulhu** [comment]
Could be just unassigned variables. This would explain why it rarely reproduces even with the same setups.

**Comment by codemime** [comment]
I've managed to reliably reproduce this with `ncurses` build. At the same time, this never occurs in SDL builds.
