### ISSUE TITLE
Minireactors are not working.

### ISSUE THREAD

**Issue by TehPrettyPony** [CleverRaven/Cataclysm-DDA#19710]
Minireactors don't generate electricity or power electrical engines for vehicles. They can be refilled, turned on or off, but they don't process plutonium cells or generate power. Issue tested for builds 6038 and 6020.

**Comment by Coolthulhu** [comment]
They got changed: now they only work when batteries are down to 0 and form the reserves.

**Comment by TehPrettyPony** [comment]
Okay, then, I'll test it this way. Thanks.

**Comment by VladicusMagnus** [comment]
There is also a small problem. I did not find it on a normal, clean, map. Error in generation?
