### ISSUE TITLE
Item properties window overlaps map, doesn't fully update

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#19719]
The images tell all you need to know:
![capture2](https://cloud.githubusercontent.com/assets/24307650/21078057/023b4394-bf2f-11e6-93e8-db101c953d08.PNG)
![capture](https://cloud.githubusercontent.com/assets/24307650/21078058/06ded33e-bf2f-11e6-8350-f8ca7649e24f.PNG)
As you can see, the items properties when examining items pops up over top of the map window as it should, but it looks bad because you can see the map through parts of it. Can we make this item properties window not transparent?

**Comment by Qrox** [comment]
To me this happens escpecially often on a debug build. I am able to reproduce this and similar behavior on a debug build 1 or 2 out of 3 times. On a release build I am only able to reproduce this one out of dozens of times.

**Comment by Leland** [comment]
Adding confirmed flag due to the above note but I have a feeling this is a Windows-only bug.

**Comment by CoroNaut** [comment]
Closing as I haven't seen this happen at all recently, but I don't know which PR fixed this.
