### ISSUE TITLE
The buildbot is dormant

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19718]
It doesn't seem to be checking PRs at the moment.

**Comment by BorkBorkGoesTheCode** [comment]
@narc0tiq are you doing maintenance?

**Comment by narc0tiq** [comment]
No, the 'bot just got stuck, probably when I was messing around several days ago. Fixed, thank you.

**Comment by BorkBorkGoesTheCode** [comment]
@narc0tiq Just want to say, thank you for maintaining the build system.

**Comment by narc0tiq** [comment]
Sure thing, no worries. I hardly ever have to do anything to it, so it's not really a major occupation.
