### ISSUE TITLE
Light survivor cargo pants are heavier than "normal" survivor cargo pants

### ISSUE THREAD

**Issue by ReservoirHeadcrab** [CleverRaven/Cataclysm-DDA#19714]
"Light" is 2,10 kg (4,63 lbs) while the "Normal" is 0,92 kg (2,03 lbs)
Just a little thing I've noticed while crafting gear

**Comment by Asmageddon** [comment]
@ReservoirHeadcrab Since it was fixed and no one else is closing it, could you close the issue?
