### ISSUE TITLE
Some settings not loading from options.json

### ISSUE THREAD

**Issue by frsnoop** [CleverRaven/Cataclysm-DDA#19720]
Namely:

[World Defaults]
Spawn rate scaling factor
Item spawn scaling factor
NPC spawn rate scaling factor
Monster evolution scaling factor

It saves, but not loading.

**Comment by Vidiveni** [comment]
This is gamebreaking for some people. Custom worlds can not be properly created at all. 

A strange detail is that `Item spawn scaling` keeps resetting to the default 1.0 (I had it at 0.2 pre-bug), but `Monster evolution scaling` keeps resetting to my pre-bug custom setting of 3.75  (default is 4.0).

**Comment by BrettDong** [comment]
Cannot reproduce, on latest master branch (d22e4ef2e444136302ce22a7bc7a7718bbec148b), MSVC x64.

**Comment by Vidiveni** [comment]
Still broken for me on build 6191. Tiles Windows 10 x64. 

1. Change the above 4 settings in world defaults. 
2. Confirm the new settings are intact on world creation. Create a world. 
3. Make a char and load that world. 
4. Check current world options. The world uses older/other settings than the new ones just set. 

Haven't tested to completely wipe and re-download game yet.

**Comment by Bowab** [comment]
I tried to reproduce this on a re-downloaded client 6199

I changed any of the 4 settings:
Spawn rate scaling factor
Item spawn scaling factor
NPC spawn rate scaling factor
Monster evolution scaling factor

I created a character and indeed the settings are messed up once in-game. The settings in worldoptions.json are correct tho.

**Comment by Coolthulhu** [comment]
Found the reason:
It's locale messing up the `string_format`, causing it to separate integer and fraction parts of floats with a comma rather than period.
