### ISSUE TITLE
Create better change wheel menu for vehicles

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#19735]
Can we have a menu that displays all the different sizes of wheels that are accessible rather than just "Wheel" or "Armored Wheel", I would prefer it to display "17" Wheel" or "24" wide wheel". This would stop the game from adding the incorrect wheel size if you have many different sizes of wide wheels for example. 

Simple enhancement.

**Comment by illi-kun** [comment]
> Simple enhancement.
Do you want to implement it of it's simple for you?

**Comment by CoroNaut** [comment]
Its up to you guys to implement it at all, i's simply suggesting it lol :D

**Comment by keyspace** [comment]
Related to: #11706 

There's not much code reuse between`veh_interact::do_tirechange()` (this issue) and `veh_interact::do_install()` (referenced above). If the latter is addressed, this one can be in a similar manner.

**Comment by CoroNaut** [comment]
Could you reference another issue that overlaps this one or a PR that fixes this?
