### ISSUE TITLE
Duplicate reloading menu entries for the Kel-Tec KSG

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#19733]
I'm wielding a Kel-Tec KSG- the shotgun with 2 magazines. Neither of the 2 magazines are fully loaded. The reloading menu looks like this (my inventory has exactly 58 00 shots in it):
![reload](https://cloud.githubusercontent.com/assets/16765166/21085687/c68b3b92-bfe2-11e6-846a-05767b531073.png)
Selecting the first entry reloads the first magazine, and selecting the second entry or typing `l` reloads the second magazine.

The expected behavior is:
1) The 2 entries don't have the same hotkey (related: #15455).
2) The interface makes it clear that choosing one of the entries reloads the first magazine, and choosing the other entry reloads the second magazine.

**Comment by codemime** [comment]
3. They probably should consume equal number of moves (am I missing something?).

**Comment by sethsimon** [comment]
I assumed that it was intended for some reason, but I could be wrong.

**Comment by codemime** [comment]
I guess @mugling knows for sure.

**Comment by BorkBorkGoesTheCode** [comment]
>3.They probably should consume equal number of moves (am I missing something?).

The KSG is buggy:

1. The lack of mod weight causes the second magazine to have extremely high recoil.
2. The lack of volume also causes it to have a different aim behavior.

**Comment by mugling** [comment]
> The KSG is buggy:

It's a nasty hack and I also can't think of a good UI design for it

**Comment by Blank99** [comment]
Shouldn't aux guns use the same volume/weight of the parent? I could understand an aux gun defining a different damage, dispersion, ammo, recoil and stuff, but volume/weight?

**Comment by wapcaplet** [comment]
Dual-magazine guns are no longer supported, and the Kel-Tec KSG no longer has a second magazine, so the "reload" menu no longer displays the unnecessary prompt for selecting which ammo to reload with. Closing issue.
