### ISSUE TITLE
[Web linter] Missing contexts

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19745]
When trying to lint json/item_groups.json, the linter couldn't understand "note": and "repeat": fields.

**Comment by illi-kun** [comment]
I suppose it's not related to web linter, we just don't have rules for item groups yet.

**Comment by mugling** [comment]
`note` isn't a valid field so the error is correct. You can use `//` for a comment

**Comment by BorkBorkGoesTheCode** [comment]
> note  isn't a valid field so the error is correct. You can use  //  for a comment

The linter doesn't have the ability to replace `"note":` with `"//":`?

**Comment by mugling** [comment]
No, that's outside it's remit
