### ISSUE TITLE
Bionic guns weird aiming behavior 

### ISSUE THREAD

**Issue by ReservoirHeadcrab** [CleverRaven/Cataclysm-DDA#19741]
Bionic guns stop aiming if the target moves. In addition, if you are wielding a handgun, the aiming mode will change from the bionic gun to the handgun once the target moves.

**Comment by kevingranade** [comment]
Aiming across turns works by setting an action that causes you to re-enter
the aiming menu after the enemy turns are processed.  it sounds like bionic
aiming might be seeing this action, but without anything to label it as a
bionic-specific action.

**Comment by Leland** [comment]
This can be closed, #20030 was just missing a keyword to autoclose on merge.
