### ISSUE TITLE
Momentum Shift duration often ends before movement is complete

### ISSUE THREAD

**Issue by jesseking** [CleverRaven/Cataclysm-DDA#19748]
Repro:
1) Create character with Ninjutsu & activate it.
2) Turn on circular distances
3) Compare moving diagonally vs. moving in cardinal directions, note whether Momentum Shift is active after each move. It will much more frequently be inactive when moving diagonally due to the longer move duration in circular distance mode.

Any form of slower movement (encumbered, rough terrain, etc) will likewise cause momentum shift to often time out before your move is complete, as it's duration appears to be only 100 ticks or thereabouts? This means momentum shift has often timed out by the time creatures move to attack or you attempt to execute a melee attack following a move, rendering it frequently useless, even to a relatively lightly encumbered survivor.

Possible solutions:
1) Increase the duration of momentum shift to something significantly longer (~200-300 ticks)
2) Add your movement duration to Momentum Shift's base duration when it is applied so that it applies during your current move, and for at least one attack thereafter. (move duration + 100-200 ticks?)

**Comment by Leland** [comment]
No movement in over a year – closing. You might have greater success seeking an answer on the forums: https://discourse.cataclysmdda.org/

If there's still a want for discussion here, just ping me to reopen, or simply create a new issue.
