### ISSUE TITLE
NPCs: Cause infinite recursion and stack trace when trapped with acid.

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#19749]
I started a world with 50x spawn rate, hordes enabled, the largest cities and smallest distance between cities, went to the middle of a huge city and surrounded myself with solid rock. Then I spawned several dozen NPCs, several dozen hulks, a few dozen moose, and waited. After a few minutes, I got a segmentation fault, so I did a backtrace, and the text was 3.5MB. Everything in the middle is the same (`npc::move_to` and `npc::move_away_from` calling each other), so I'm only attaching its head and tail.
[huge_backtrace.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/647958/huge_backtrace.txt)

**Comment by sethsimon** [comment]
I looked into this a little and found a reliable way to reproduce this:
```
### - Walls
#@# - npc
#@# - npc
#@# - you
#Z# - spitter: When it spits, the NPCs go crazy.
###
```

**Comment by Night-Pryanik** [comment]
Confirmed on 0.C-7145, Windows XP SP3 x86, tiles.
