### ISSUE TITLE
Vehicle speed changed? 20mph is now 1 tile per turn? 40 mph 2 tiles per turn?

### ISSUE THREAD

**Issue by Greiger** [CleverRaven/Cataclysm-DDA#19754]
Not sure if this is a bug or just an intended change that I missed the commit for but vehicles seem to be going only half the speed they used to.

The speedometer says 20 mph, but the speed seems to match the old 10 mph when comparing to the speed of zombies and the car's smoke trail.  Possibly related but speed also only increases in increments of 20 mph, now.  From a freshly started car hitting up once sets the cruise to 20, twice sets it to 40, and so on.

I first noticed this issue around around 0.C-19825-gc44eb6a (jenkins 5921) and is still present in 0.C-20222-g21cd417 (jenkens 6043)

Again, not sure if it was intended or not, but it feels a bit odd that zombies appear to be powerwalking along at a brisk 17 or so mph, when compared to a car.

**Comment by mutability** [comment]
note that in-game distances aren't really comparable to real distances (at a slow walking speed of 1m/s, that would make each tile 6m wide) so things are going to be somewhat weird regardless.

**Comment by BorkBorkGoesTheCode** [comment]
Looks like the proportions are wrong.

**Comment by sniperm13** [comment]
Noticed this too... I used an electric bike before when scouting. Foot pedaled my way to my destination (charge the batteries) and used the motor to go back. But using even the regular bike isn't viable anymore even if only moderately encumbered, the speed is less than 30 mph, and its too slow now to be of any use as you can't even use it to go back to base camp when the bike is loaded with loot...

**Comment by Aivean** [comment]
Here I asked the same question:
https://github.com/CleverRaven/Cataclysm-DDA/pull/19275#issuecomment-265305309

Unfortunately it seems that it works as intended. No realism for us.

**Comment by CoroNaut** [comment]
This distance measurement needs to be sorted out at some point in the future. I didn't fully realize how bad this problem was until I read about it. If we are talking about balance, why was it thrown into orbit? Forget realism even, the problem is barely fictional material at this point. The distance measurements should really be fixed or at the very least looked at and improved. There should also be some concrete way to consistently generate these measurements so we don't have such inconsistency in the future.

**Comment by Greiger** [comment]
Hmm, from what I understand from reading those the speeds are how they are now for balance.   Fair nuf, but I figure it breaks suspension of disbelief more watching a zombie you can easily outrun on foot just about keep pace with a car, or a motorized pedal bike breaking 60, than cars having half a displayed speed.

From what I can determine by looking at engine jsons standard car engines have a redline ingame of around 4000 rpm.  My crappy chevy cruize has a redline in the 6000s according to google.  Could we simply handwave it in lore as the government responding to oil shortage and mandating manufacturers reduce engine RPMs and thus reducing vehicle speed nationwide?

That would give lore reasoning for otherwise high end cars having a relatively low top speed, and stop zombies from walking faster than I can pedal on my bike in rl.  Trickiest bit would be showing that lore to the player in some fashion.

**Comment by Aivean** [comment]
@Greiger having balance doesn't justify broken math. 

Here are two variants that fix the relationship between speed and distance:

Assume:

* turn = 1 sec
* tile = 2m (meters)

walk/jog = 2 m/s = 1 tile/turn  = 4.47 mph ≈ 5 mph
runing = 4 m/s = 2 tiles/turn   ≈ 10 mph

vehicle speed = up to 60 mph
>10 mph  ≈   2 tiles/turn
20 mph ≈  4 tiles/turn
30 mph ≈ 6 tiles/turn
....
60 mph ≈ 12 tiles/turn (half a map tile per turn)


**OR**

turn=1s
tile=2.24 meters

walk/jog = 5mph = 1 tiles/turn
running = 10 mph = 2 tiles/turn

vehicles:
>  ....
60 mph = 12 tiles/turn


In the first variant conversion from m/s to mph is not precise (≈10% off), in the second case tile is larger and not integer (in meters).

I personally like the first variant. And yes, both variants imply that turn duration has to be changed, which means a lot of work to rescale timing throughout the game. But I don't see how it affects balance.

**Comment by illi-kun** [comment]
As it was discussed in #19275, these is no easy way to make it realistic and have a good gameplay.

**Comment by kevingranade** [comment]
I do intend to rescale turns to be 1s long, it does make most everything
work better.
