### ISSUE TITLE
Easy fix-Clootie dumpling volume

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#19751]
currently its nutritous food in very small package -pill like lvl which i think is omission in new volume sistem.
http://prntscr.com/ditn23

although i havent eaten it myslef google search show its like usual sweet meal.
http://cookdiary.net/clootie-dumpling/#photo_1

**Comment by lucasmr** [comment]
Haha, 11 kg/L is hilarious. Denser than steel!

**Comment by Treah** [comment]
Easy fix its not.... Volume system in cata being the way it is makes this problematic. This item has a volume of 1 which should be 250ml or at least was. Ive no idea why it now calculates to this small volume size. A plastic bottle which has a volume of 500ml has volume of 2 and shows right. I am unsure why the volumes in json were not updated to reflect the volume changes in the main game.

**Comment by baraba3** [comment]
is this what you would consider fixed i fixied it in comestible json by changing stacksize which was 40 to 2
http://prntscr.com/dkwvyw

 "type" : "COMESTIBLE",
        "id" : "cloutie_dumpling",
        "name" : "cloutie dumpling",
        "weight" : 112,
        "color" : "brown",
        "container" : "box_small",
        "comestible_type" : "FOOD",
        "symbol" : "%",
        "quench" : -2,
        "nutrition" : 28,
        "description" : "This traditional Scottish treat is a sweet and filling little boiled cake studded with dried fruit.",
        "price" : 195,
        "material" : ["wheat", "fruit"],
        "volume" : 1,
        "charges" : 2,
        "stack_size" : 2, (was 40)
        "fun" : 9

or if we want 0,50l for it just change volume to 2 and stack to 2

**Comment by baraba3** [comment]
just did some more experimentation seems volume size is calucalted by charges/stack size* volume  whre volume of 1 represent as you said 0,25l

this is volume 1 charges 4 instead of 2 stack size 2
http://prntscr.com/dkx0oz

**Comment by BorkBorkGoesTheCode** [comment]
"volume": 1, "stack size": 40 currently

**Comment by BorkBorkGoesTheCode** [comment]
Would anybody mind if I change the clootie dumpling in the following ways:

```

    {
        "type" : "COMESTIBLE",
        "id" : "cloutie_dumpling",
        "name" : "clootie dumpling",
        "weight" : 112,
        "color" : "brown",
        "spoils_in": 48,
        "container" : "box_small",
        "comestible_type" : "FOOD",
        "symbol" : "%",
        "quench" : -1,
        "nutrition" : 14,
        "description" : "This traditional Scottish treat is a sweet and filling little boiled cake studded with dried fruit.",
        "price" : 195,
        "material" : ["wheat", "fruit"],
        "volume" : 1,
        "charges" : 4,
        "stack_size" : 1,
        "fun" : 9
    },


```

It would be larger and lose permafood status, but it would have two more charges. Vaccum-packed clootie dumpling could last 1+ years.

**Comment by BrettDong** [comment]
@BorkBorkGoesTheCode I second that!

**Comment by Night-Pryanik** [comment]
@BorkBorkGoesTheCode do you still plan to open PR with your changes?

**Comment by BorkBorkGoesTheCode** [comment]
@Night-Pryanik I had forgotten about it due to being busy offline, thanks for adding the code. I didn't dial down the nutrition values enough, is that a problem now?

**Comment by Night-Pryanik** [comment]
@BorkBorkGoesTheCode that wasn't me who added the code, it was @Leland. I'm pretty sure the problem is completely fixed by now.
