### ISSUE TITLE
Horsepower scaling?

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19766]
I've recently been playing around with a ~5 ton, eight-wheeled (32" armoured wheels) vehicle. When I upgraded from a 80 hp engine ("gasoline engine (2.0L)") to a 112 hp engine ("V6 engine (2.5L)"), the maximum speed only increased from 64 km/h to 74 km/h. That's a 40% horsepower increase translating into a paltry 16% speed increase.

I can't say I entirely understand all the new changes to engines in the game, so I'm not entirely certain if this is a bug or I'm just not understanding the whole torque versus speed of engines.

**Comment by CoroNaut** [comment]
The way that a portion of the devs have it setup already, They themselves have said that a single 1x1 tile could represent anywhere from 6 feet to 210 feet. I literally don't even know how the measurement system got so screwed up, but this is that problem. Your problem with the paltry speed increase is because cars go off of a different measurement system than the players. mugling was the one who made it this way, his engine concepts are good, but the measurements he uses to model turns/sec got screwed in the process. the entire games measurement system got screwed honestly. #19275 explains with a short novel, #19754 is the cliffnotes version :D

**Comment by kevingranade** [comment]
Minor correction, mugling didn't break scaling,  the scaling of various
things in the game has been totally nonsensical for the lifetime of the
game, and I wouldn't even call it a problem with the game, it's fundamental
to the way size and distance is handled in a roguelike.

We can tune various things to hide the mismatches, but it's not practical
to resolve them.

**Comment by Regularitee** [comment]
Well, putting aside the realism scaling thing, if an engine's description claims that it has 40% more whatever-arbitrary-unit-of-power, but gives an entirely different number in practice, then... what's the point of even giving the player in-game information? It just confuses players by providing false information.

**Comment by tinukedaya** [comment]
Just because the engine has 40% more power, does not mean you should have 40% increase in speed. HP does not equal speed.

**Comment by Regularitee** [comment]
Since it sounds like you know, what's the formula for converting horse power into speed in the context of the game? Has it changed since the engine overhaul?

**Comment by Aivean** [comment]
@Regularitee 
In real world air drag force is exponential. Here is the illustration:

![drag](http://www.phys.ttu.edu/~ritlg/courses/p1401/drag_plt.png)

Put simply, it means that at doubled speed drag will be more than two times stronger. 

That's why even if engine is able to provide thrust at unlimited speed (think jet engine) in atmosphere you will still have some terminal velocity.

**Comment by Regularitee** [comment]
I specifically made sure to add the words "_...in the context of the game_" to that sentence so that no one would be a smartass and just copy/paste a Wikipedia real-world answer, instead of the actual formula used by the game.

Actually, thinking back on it, I don't think I've ever manged to find a single person -- here, on the wiki, or on the reddit -- that knew about how precisely the game determines a vehicle's K aerodynamics, K friction, and K mass, and their exact effects. Whomever created the system didn't bother documenting it, or almost no one knows where the documentation is.

It could very well be the entire system works perfectly fine, and people like me think there are bugs popping up due to the highly opaque game mechanics.

**Comment by mugling** [comment]
> That's a 40% horsepower increase translating into a paltry 16% speed increase.

E=mv2. It's not a linear relationship.

> that knew about how precisely the game determines a vehicle's K aerodynamics, K friction, and K mass, and their exact effects. Whomever created the system didn't bother documenting it, or almost no one knows where the documentation is.

Coolthulhu wrote much of that and it is documented via doxygen comments

**Comment by CoroNaut** [comment]
Sorry mugling and granade, I thought that since the engines where being changed that it meant that the speed would be decreased. All these issues about speed and engine problems happened pretty fast for me. Is it really nonsensical to try to get a concrete method to determine measurements within the game? I understand the problems with the players speed and the distances relative to buildings and whatnot, but can it be tweaked? The very large range of measurement errors is what is getting to me, it doesn't even seem fictional to have such unreliable distances.

**Comment by Aivean** [comment]
@mugling, please don't take this as an offence, I haven't checked sources of your current implementation, I'll just point out how it works in real world.

Your formula (`E=mv2`) shows that you have to spend four times more energy to achieve double velocity.  Meaning, that under ideal conditions (no resistance) with constant force output from the engine you'll spend four times as much time to double the speed.  It doesn't limit the top speed.

Top speed in real world is limited by rolling resistance of the wheels, internal frictions in the drivetrain and, most significantly, by air drag force.  These increase exponentially with higher velocity and eventually become equal to the force of your engine.

**Comment by CoroNaut** [comment]
I believe mugling was referring to KE=(1/2)mv^2. This way, it isn't a linear relationship like he was talking about.

**Comment by Coolthulhu** [comment]
The formula for friction load at the moment is:
```
// kinetic energy (J)
double k = 0.5 * total_mass() * pow( current_velocity(), 2 );
// engine power (J/s) replaces energy lost via friction
double res = k * friction_loss / k_dynamics();
// if the wheels are slipping we need more power to maintain the same speed */
res *= 1.0 + k_traction( g->m.vehicle_wheel_traction( *this ) );
```

Looks wrong to me:
* If it was just air resistance, it shouldn't scale with mass
* If it was just rolling resistance, it shouldn't scale with velocity
* If it was both, it shouldn't multiply them by each other, but sum them

Additionally, `k_traction` increases load, meaning that a car digging in mud will be more efficient than one on road.

**Comment by Aivean** [comment]
@CoroNaut now I'm reading my comment and it seems confusing :(

I was talking about this formula `KE= ½ mV²` . This is formula for kinetic energy of the moving object. It also describes the amount of work required to accelerate an object to the given speed.

My point is that this formula only means that without any resistance you can spend exponential time to accelerate to any speed (speed is not limited, if you have infinite time).  Speed is limited only by friction/resistance.

**Comment by Aivean** [comment]
@Coolthulhu 
rolling resistance also scales with velocity, but negligibly compared to air resistance. 

For example [here is the article](http://www.solarjourneyusa.com/EVdistanceAnalysis5.php) with charts for Tesla Roadster.

![Power usage](http://www.solarjourneyusa.com/Pictures/PowervsSpeed.jpg)
Power usage vs speed

**Comment by Regularitee** [comment]
Does anyone have a link to the "doxygen comments" containing the documentation for how K mass, aerodynamics, and mass works? This is something that should really be posted on the wiki so players can actually understand how it works.

Though on second thought, it might be useless to do so right now, given how mass doesn't even work properly. (#19571: Collissions ignore relative mass of objects. Powered wheelchairs can bore through walls with minimal damage, and 20-ton tanks can be stopped by flowers). Maybe best to wait until game mechanics are fixed before we bother documenting anything for the players?

**Comment by illi-kun** [comment]
Doxygen comments about vehicle are available here:
http://dev.narc.ro/cataclysm/doxygen/classvehicle.html
