### ISSUE TITLE
Peanut butter should be pleasurable

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#19767]

**Comment by DangerNoodle** [comment]
I assume you mean a morale bonus for eating it. Because a title of that sort with no description for context presents amusing implications that I hope were unintentional.

**Comment by Regularitee** [comment]
I guess that interpretation depends on whether you own a pet dog or not.

**Comment by ZhilkinSerg** [comment]
Some people do not like roasted peanuts.

**Comment by busterbogheart** [comment]
But not all.  Good idea-- while were at it put in a nut allergy trait!
