### ISSUE TITLE
Vehicle scoop not picking up harvested crops.

### ISSUE THREAD

**Issue by Shpid0inkle** [CleverRaven/Cataclysm-DDA#19774]
Seems like it's only things that spoil, it picks everything else up just fine.

**Comment by Regularitee** [comment]
I may be mistaken, but isn't that what the reaper module is for? The scoop is just for collecting loose items on the ground, like debris from killed zombies.

**Comment by Shpid0inkle** [comment]
No, the reaper is for harvesting fully mature crops, it turns them into the actual food and seeds. It does not pick up the crops.

**Comment by illi-kun** [comment]
I've put 'bug' tag here but it's just an initial assumption - I didn't check if it's actually a bug or intended behavior.

**Comment by jaked122** [comment]
@Shpid0inkle when I wrote that bit that was specifically requested by the various maintainers that advised me.

Crops are called "unopened_containers" in the json, this is the flag that determines it, with it off it will vacuum the seeds right out of the earth.

That actually breaks harvesting entirely.

**Comment by BevapDin** [comment]
I just tested this with freshly *harvested* tomato (3 items: seed + fruit + plants) and the Automatic Street Sweeper. Note that the scoop will only pick up items within a maximal volume (and a stack of seeds counts as one item). It will also only pick up at most one item, and only if there are battery charges available and when there's cargo space available.

@Shpid0inkle If you encounter this again, please report the *exact* circumstances and ideally provide a reproducible test case.
