### ISSUE TITLE
UI strings aren't completely following the change of language

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#19779]
For example, I changed the language from English to Simplified Chinese, the ASCII art and the banner message was updated to the new language, but menu entries stayed in English, only after I closed and reopened the game, all UI strings were in correct language.

![2016-12-16 8 30 41](https://cloud.githubusercontent.com/assets/21075502/21262868/910146f2-c3ce-11e6-96dd-822996f558ae.png)
![2016-12-16 8 28 35](https://cloud.githubusercontent.com/assets/21075502/21262871/96d05730-c3ce-11e6-8d73-c95dc5dd359a.png)

**Comment by sethsimon** [comment]
I'll take care of this.
