### ISSUE TITLE
Bow Sight description

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#19773]
Using the Bow Sight mod on a reflex recurve changes aim time from 11->17 seconds. Using it on a short bow increases aim time from 13->22 seconds. I gather that it's supposed to work this way. You take longer to aim but place a more accurate shot thanks to a lower sight dispersion.

At any rate, the description should be fixed to reflect this. It says that the Bow Sight has no drawbacks; aiming time is a pretty hefty drawback. I'm not a 100% on the whole aiming procedure, but at least up-close it might actually decrease your performance with a bow? Or do those extra seconds only come into play when you're already using careful or precise aim?

**Comment by kevingranade** [comment]
On Dec 15, 2016 4:22 PM, "Tharn" <notifications@github.com> wrote:

Or do those extra seconds only come into play when you're already using
careful or precise aim?

Effectively this is what is happening. you aim using the fastest usable
sight for each aim action, so you don't use a slower sight until you have
to.
