### ISSUE TITLE
Night Vision and Candles

### ISSUE THREAD

**Issue by Podesta** [CleverRaven/Cataclysm-DDA#19795]
If you have the night vision trait, and lights up a candle in the night, your vision radius goes down, from whatever it was before, like 5 square radius, to just 1 square. Not sure if intended (as in your eyes are not used to the dark light anymore, or if a bug).
Edit: Latest version 6056

**Comment by Tharn** [comment]
I think this is intended. When you're affected by any light source, your eyes adapt. You'll notice that when you have Full Night Vision and approach a small light source at night, your night vision radius goes down gradually the closer you get.

**Comment by Podesta** [comment]
Indeed. Never realized the other instances. I do believe it is working as intended, so I'll close the issue.
