### ISSUE TITLE
Remembered vehicles on map persist after character death

### ISSUE THREAD

**Issue by kas** [CleverRaven/Cataclysm-DDA#19800]
Windows 10 Pro
CDDA 0.C-20222-g21cd417
ChestHole32

To reproduce:
On any character, move your character to a vehicle's controls. Press the ^ button to take the controls. Press the ^ button again to interact with the vehicle. Near the bottom there should be a "Remember Vehicle" button which puts the vehicle on the map so you can find it in the future. Press enter on it.

Hit the M button and take note of the coordinates in the lower right corner

Kill your character or just start a new character, using the same world.

Open the map again and navigate to those coordinates noted earlier. You should see your vehicle's name in the top left corner.

**Comment by Nymall** [comment]
I hate to say it, but I thought this was a feature of the latest exparimentals. I've been using remembered vehicles to gauge when I'm near old bases in persistent worlds.

**Comment by CoroNaut** [comment]
I would think this is a bug because this new character you create on the same world would and should have no clue that the other even existed.

**Comment by Zireael07** [comment]
> I would think this is a bug because this new character you create on the same world would and should have no clue that the other even existed.

That is one of many problems with playing multiple characters in the same world. Such as the food already being rotten in areas explored by the first character, being able to come across the corpse of the first even if the first died on day 40 and the second is on day 1... etc. etc.

**Comment by Leland** [comment]
Closing in favor of #19868
