### ISSUE TITLE
XL Holster encumbrance bugged

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#19802]
So, wearing a light survivor suit (enc 7) and a XL Holster (enc 9) my enc for that leg is... 9?! This is with a weapon in the holster, btw. The regular holster on my other leg is properly doing what it should.

Edit: And it fixed itself. Not sure what caused that or why, but it's ok now.

**Comment by illi-kun** [comment]
Please re-open if you will able to reproduce it.
