### ISSUE TITLE
When installing new parts on a vehicle, all items in the 'Cargo' category are missing

### ISSUE THREAD

**Issue by hurston1** [CleverRaven/Cataclysm-DDA#19806]
0.C-20267-g08a7676 (tiles)
My character has mechanics at 8.

**Comment by Aivean** [comment]
Are you trying to install cargo over the tile that already has cargo?

Please check flags and vehicle layers [here](http://www.wiki.cataclysmdda.com/index.php?title=Vehicle_construction#Part_locations).

Also some screenshot of what you're trying to do will help.
