### ISSUE TITLE
'Burning Building' scenario plus npc's mean all NPC houses are on fire

### ISSUE THREAD

**Issue by hurston1** [CleverRaven/Cataclysm-DDA#19805]
I tried NPCs for the first time, and the 'Burning Building' scenario at the same time, but now whenever I get near any house with an NPC inside, it starts burning down.

**Comment by ZhilkinSerg** [comment]
Is your character name Carrie?

**Comment by sethsimon** [comment]
@hurston1 I'm having trouble reproducing this. Do you have a list of world settings (and whether you changed any of them midgame)? Or even better, an uploaded savegame?

**Comment by hurston1** [comment]
Apart from the 'burning building' scenario and NPCs turned on, there wasn't anything particularly odd regarding the world settings. I've got to a point in the game where I am approaching a new house with an NPC, so I saved at a distance. Loading that save and approaching the house, it does indeed burn down. The save directory is 138Mb, so I'm not sure if it is viable to upload that, or are there just certain files that you are interested in?

**Comment by sethsimon** [comment]
The entire world would be best. If you didn't already remove the other worlds from the zip file, the save directory contains subdirectories, each of which correspond to a particular world- only the one subdirectory is needed. If it's still large, the `selecting them` link at the bottom of the comment box will reject the file, so a different method will have to be used (fortunately, based on a quick search, it looks like most file hosting sites will accept files that large).

**Comment by hurston1** [comment]
Here is a dropbox link to the world. I zipped it up from 138Mb to 10Mb.
The NPC is just to the south-east. the building will strt burning as you approach.

https://dl.dropboxusercontent.com/u/75731190/save.zip

**Comment by sethsimon** [comment]
Thanks! Those NPCs shouldn't even exist in the first place because random NPCs are off (if I recall correctly, the only static NPCs are the starting NPC and those at the refugee center). I'll look into it further.

**Comment by sethsimon** [comment]
Each burning house and its corresponding NPC are from your other 4 players who did the Burning Building scenario. Since fire isn't processed outside of the reality bubble, those areas of the map were in the same state that they were in when they died.

**Comment by hurston1** [comment]
I don't remember doing that many Burning Building's, but that certainly makes sense. I think that solves that issue.
