### ISSUE TITLE
Pistol Bandoleer doesn't hold .357 ammo

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#19813]
Very odd, but it won't hold that ammo type.  It will hold pretty much every other ammo type.  Also, it won't hold 10mm auto ammo.  Any ammo in the extended ammo pack.

**Comment by hmstanley** [comment]
you can easily mod the bandoleer in data/json/items/armor/bandolier.json.  Should allow those ammo types in the bandoleer in my opinion. Also, bandoleer is spelled wrong. It's not bandolier, but bandoleer

**Comment by Rivet-the-Zombie** [comment]
[Both spellings are correct for our purposes.](http://wikidiff.com/bandoleer/bandolier)

**Comment by BorkBorkGoesTheCode** [comment]
Ammo must be specifically listed as bandolier-capable in order to work with the bandolier. It might be pretty easy to fix in the mod.

**Comment by hmstanley** [comment]
I stand corrected Rivet..

**Comment by DangerNoodle** [comment]
Should be easy to fix, can start work on it now if others have not already.
