### ISSUE TITLE
Steel shutters on player-built reinforced glass windows cannot be opened

### ISSUE THREAD

**Issue by Shpid0inkle** [CleverRaven/Cataclysm-DDA#19817]
Stage 3 of reinforced glass windows have steel shutters on them, but I can't open them. I have tried (e)xamining them which gives the description of the window, and (o)pening them which says "there's no door there". Running latest experimental build.

**Comment by Night-Pryanik** [comment]
These windows have `OPENCLOSE_INSIDE` flag. I assume they just weren't installed in the `indoors` territory.
Tested right now - installing them in the right manner works just fine, they open as they should.
