### ISSUE TITLE
Wiki hosting ending

### ISSUE THREAD

**Issue by remyroy** [CleverRaven/Cataclysm-DDA#19811]
I will stop hosting [the wiki](http://www.wiki.cataclysmdda.com/) on January 2nd, 2017.

I will provide a dump of the database and a copy of the Wikimedia files on demand.

**Comment by mugling** [comment]
Thank you for your work to date on this.

I'd be interested in continuing the hosting of the wiki and as previously discussed possibly extending it to link in with the stats dumper. Can you provide me with access so I can dump what is necessary directly (usernames, passwords and other such details shouldn't be submitted to a file-upload service).

**Comment by remyroy** [comment]
How can I contact you privately?

**Comment by mugling** [comment]
I'll email you some details

**Comment by mugling** [comment]
FAO @remyroy 

```
20 ce 93 65 18 96 30 aa 9a 41 1a e5 f3 e2 21 4f 
12 4b d5 df 80 fb 3a 9b b4 a8 db d4 13 e0 5f 94 
6a 5e 46 bc 0d bc 1d d7 19 c4 d1 37 8e d9 ce 33 
37 28 36 88 cb 0b 62 78 57 db 55 46 67 db ea 77 
39 5a e1 df 94 61 e4 b2 a8 63 6b ec 1c c7 d6 78 
e8 b0 04 71 18 d4 d7 53 b6 4c 1d 6a 5a 3c be 1f
```

**Comment by Chezzo** [comment]
8a d3 e2 b0 07 74 77 50 15 da b7 19 4d 77 c8 57 
a3 74 80 cb d3 e7 65 94 e4 72 ed 05 06 20 f2 0d 
19 11 51 ad db 76 13 2f ac 1e ba 73 77 aa dc 97 
ed 0c f5 16 9b 7c 61 e1 39 f8 33 c3 cd 1b d3 06 
de 04 87 c3 81 ca 4d 57 24 4e 69 20 ca e4 03 c2 
87 7b 79 ed f7 8d 5d 78 dd e9 ba eb bb d5 c4 1e
