### ISSUE TITLE
Laser weapons generate no sound

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19827]
I've only tested it with the A7 laser rifle, but it presumably affects other energy weapons as well: they register as having no sound when firing. I don't mean they are merely very, very quiet, but they generate absolutely no sound whatsoever, not even one point of sound with Enhanced Hearing bionics enabled. 

Absolute silence seems like it gives an unnecessary advantage to an already pretty overpowered class of weapons, so I think some level of sound should be added to them. This is not only for the sake of game balance, but to a lesser extent, realism: high powered pulse lasers have been known generate large snaps or cracking sounds (the air heats up along the beam, creating an expanding high pressure zone, then afterwards cools down and implodes on itself, creating a sudden noise). Plus there's the generic buzz or humming sound that accompanies almost any sort of high voltage machinery, like power lines or transformers.

**Comment by hawkwinghasseler** [comment]
If anything, (pulsed) laser weapons should have no *recoil* but still produce a somewhat significant audible 'pop' from the capacitors discharging to fire.

**Comment by Regularitee** [comment]
I'm preparing to add sound to energy weapons in the base game, and I'm currently toying with various tests in the game. I've been thinking of a base loudness of 20 for the lighter energy weapons, all the way up to 60 for the big cannons. For the first release, at least. It'll probably change further based on feedback after implementation.

Any thoughts on the sound range for energy weapons? Is 20-60 too much, too little?

**Comment by kevingranade** [comment]
20 strikes me as a bit high for the low end, that is roughly, "enemies will
hear this from this many squares away". The low end laser pistol should
probably be silent and it'll scale up from there.

60 for big honking laser cannons sounds fine though.

**Comment by CoroNaut** [comment]
If this was fixed, can we close the issue?
