### ISSUE TITLE
Chopping down trees with Experimental Z-Levels is producing insanelly loud sound, to the point of deafening the player. 

### ISSUE THREAD

**Issue by Ahruvon** [CleverRaven/Cataclysm-DDA#19828]
![image](https://cloud.githubusercontent.com/assets/24622880/21397525/60be0802-c7a4-11e6-9953-95564e0a1dde.png)
That time there was no registered sound in the terminal, but i've seen occasions where sound level was over 190 when the tree fell.

**Comment by keyspace** [comment]
For reference: without Z-levels, the sound produced is around 75. Tested with `0.C-20421-gd55baf1` (current git master).

Can also confirm the displayed sound level often stays at 0 (both with and without `ZLEVELS`).

**Comment by kevingranade** [comment]
Need to check whether #35052 fixed this.

**Comment by ymber** [comment]
Cannot reproduce on current master. Looks like #35052 fixed it.
