### ISSUE TITLE
Some mods are missing from the Worldgen list

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#19835]
Namely,
```
Animatronic Monsters
Arcana and Magic Items
DinoMod
Fast Zombies
Mundane Zombies
Perfect Reliability
No Triffids
No Zombie Animals
PKs Reimagining
Slow Zombies
Tough Zombies
```

**Comment by Noctifer-de-Mortem** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/19124

**Comment by pisskop** [comment]
i have an issue with this too, since it affects myn3rd party mod

**Comment by pisskop** [comment]
they need to put it back on the list so it xan be saved as a default mod

**Comment by sethsimon** [comment]
I see. Sorry, I'm out of the loop. So if I understand this correctly, the only reason these mods are in core is so that we don't break saved games?

@pisskop I followed the installation instructions in your mod's forum [thread](http://smf.cataclysmdda.com/index.php?topic=12051.0), and it appeared in the list like it should.

**Comment by Barhandar** [comment]
>So if I understand this correctly, the only reason these mods are in core is so that we don't break saved games?

Pretty much. Also, you can remove the "obsolete" flag from their modinfo if you really need to pick them for some reason, but then it will be entirely on you: as intended.

**Comment by sethsimon** [comment]
Thanks, Barhandar!
