### ISSUE TITLE
Vehicle auto window tinting or auto close curtain

### ISSUE THREAD

**Issue by TheMrBakit** [CleverRaven/Cataclysm-DDA#19837]
Like the title said, I would like to throw an idea up.
I'm a little bored to close all the curtain on my windows(in my car) one by one so my idea would be one of those is a wooden (or whaterver material) panel that close with a swich (control of the vehicle) or something a swich that tinted the windows of the vehicle.

Maybe it's a bad idea but atleast i tried :)

_Sorry if i made some misspelling English is my second i learnt_         

                                                                                     TheMrBakit

**Comment by Regularitee** [comment]
It's the year 2040 in the game. We already have, in reality today, electrochromatic glass (glass that can become opaque with a change in electric current). This should totally be a thing, with a pseudo-curtain system you can toggle using the vehicle's electric controls.

**Comment by Aivean** [comment]
Question: do curtains currently do anything, beside blocking friendly turrets' line of sight?

From what I remember they don't block bright light. Do they prevent monsters from seeing you?

**Comment by TheMrBakit** [comment]
@Aivean, Yes currently curtains block sight of monsters

**Comment by Leland** [comment]
Closing due to a discussion that's been stalled for months. If anyone's still interested in pursuing or discussing this, ping me here and I can reopen. Or, feel free to make a new issue regarding it.
