### ISSUE TITLE
Can we have vehicle battery refilling brought back?

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19833]
Currently, energy can be converted like so:

Vehicle power -----> Bionic power (via cable charge system)
Bionic power -----> Battery power (indirectly, via UPS-compatibility mods and the UPS bionic)
Battery power -----> ??? (Cannot be used to refill vehicle batteries anymore, and the battery-consumption bionic is currently broken, last I heard)

**EDIT:** Battery consumption bionic was actually fixed, I just wasn't aware. But there's still no way of converting bionic or portable battery energy into vehicle energy.

Because batteries can no longer be converted into vehicle power (by filling vehicle batteries), they can have a habit of accumulating towards the late game as you have more solar power infrastructure, to the point you just throw them away due to their weight. It would be nice if there were a method to convert them into another type of power you might need, like vehicle power or bionic power.

**Comment by Regularitee** [comment]
Derp. Battery consumption mod was fixed. Missed that patch.

**Comment by kevingranade** [comment]
I can think of three batteries -> vehicle battery charge solutions that
would work in mainline. There are certainly others that would also work. It
just needs an intervening mechanism.

"Improvised car battery" recipe: a box,  some electrical wire,  batteries,
 and some soldering, very low skill requirements. Maybe reloadable with
loose batteries, not sure what that would look like.

"Passive car battery charger" (needs a better name). Can attach to a
vehicle to charge it over time.  Very inefficient but easy to make.
Requires same components as Improvised battery plus some extra cabling.

"Active car battery charger" (again, better name would be good). Works like
passive charger but is faster and more efficient.  Crafted from same
components plus some circuitry, requires a little electronics skill.

**Comment by Zireael07** [comment]
All three of those ideas are really nice!

**Comment by Regularitee** [comment]
Re-opened because people seem interested in the discussion after all, even if the initial assumption was wrong on my part.

**Comment by kevingranade** [comment]
Of the three options I listed, the improvised battery is the simplest, only
requiring a vehicle part, item, and crafting recipe.

The other two require new vehicle interaction code, some of which might be
extensive depending on details of how they work.

**Comment by Regularitee** [comment]
As long as it's the variant that's reloadable. It would be a pain in the arse to have to craft a makeshift battery, figure out how to get it to drain into the vehicle's "main" batteries to refill them (possibly having to make a second temporary vehicle and use jumpers), then uninstall the makeshift battery, then create and install another one, and repeat the process as needed.

**Comment by kevingranade** [comment]
There's no shortage of vehicle batteries, all the improvised battery is
need for is starting the engine, right?

**Comment by Barhandar** [comment]
>they can have a habit of accumulating towards the late game as you have more solar power infrastructure, to the point you just throw them away due to their weight.

The point isn't starting the engine, the point is consuming the batteries.

**Comment by kevingranade** [comment]
So you're looking for a way to use something that was valuable at some
point but then became obsolete?
Unless I'm missing something that's not a problem,  if batteries are
useless at some point in the game, just throw them away.

Wiring together enough portable batteries to meaningfully use in anything
other than a device expressly designed to be portable and battery-operated
is a pain in the ass and usually pointless, I don't see any reason to go
out of our way to change that.

Using the additions I outlined are acts of desperation at best and
time-wasting hoarding behaviors most of the time.  As the former they're
certainly worth adding, but there's no good reason to cater to the second
use case.

**Comment by CoroNaut** [comment]
Perhaps instead of bringing it back, we could create an item to transfer over this energy instead. The idea doesn't seem reasonable without some electrical engineering. Merry Christmas everyone!

**Comment by kevingranade** [comment]
On Dec 24, 2016 5:36 PM, "CoroNaut" <notifications@github.com> wrote:

Perhaps instead of bringing it back, we could create an item to transfer
over this energy instead.

That's why I said:
> "Passive car battery charger" (needs a better name). Can attach to a
vehicle to charge it over time.  Very inefficient but easy to make.
Requires same components as Improvised battery plus some extra cabling.

> "Active car battery charger" (again, better name would be good). Works
like passive charger but is faster and more efficient.  Crafted from same
components plus some circuitry, requires a little electronics skill.

The idea doesn't seem reasonable without some electrical engineering. Merry
Christmas everyone!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/CleverRaven/Cataclysm-DDA/issues/19833#issuecomment-269104251>,
or mute the thread

**Comment by 1skandar** [comment]
Yeah, a jump pack is a thing. A portable (albeit heavy) battery system with leads that is generally capable of starting a car once. Rechargeable via wall socket in real life, but disposable batteries could work in game. Holding 500 charge would get most cars going, I think.

**Comment by BorkBorkGoesTheCode** [comment]
https://en.wikipedia.org/wiki/Jump_start_(vehicle)#Battery_charger

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
