### ISSUE TITLE
C4 detonating on a gas tank should really do more damage

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#19834]
Just saying.  Anecdote-aly, you know like for a test case, when devs get around to this system.

As much as I complain, I should really contribute.

**Comment by kevingranade** [comment]
You mean we should detect that it's an improvised fuel-air bomb, or just
the c4 should have a larger explosion?

**Comment by busterbogheart** [comment]
Size seems appropriate (not experienced) but yea with the fuel should result in more than just some scrap metal laying around.  Plus the vehicle is still driveable afterwards which seems unrealistic.  Really only exciting after NPCs understand how to drive cars but.

ps Its an honor to speak to you sir

**Comment by Leland** [comment]
Discussion's been stalled on this for about 5 months, closing. Feel free to ping me here to reopen if there's still a want for discussion or work on this issue.
