### ISSUE TITLE
Crash after descending and ascending stairs in lab

### ISSUE THREAD

**Issue by AlexanderWatzinger** [CleverRaven/Cataclysm-DDA#1985]
Version: Stable Release 0.6 - compiled from source 
OS: Linux Debian Wheezy
Possible related to: #1808 

After descending on a lab level -3 and ascending again I arrive at a different location and in the top left a red message appears:

DEBUG: Wacky scent at -1, 29 (251547536) Press spacebar...

The game is unresponsive except pressing spacebar and crashes with a "Segmentation fault" after pressing spacebar after a few times.

It is reproducible and I can provide the save game if needed.

Screenshot attached

![operation_alice_bug](https://f.cloud.github.com/assets/1130113/766455/41e71c08-e863-11e2-9dd0-faeb27ebe29b.png)

**Comment by mugling** [comment]
Closed due to age and lack of recent reports in `master`. Please re-open if reproducible
