### ISSUE TITLE
Warning message no longer appears

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19859]
The warning message notifying the player that they can't remove an engine without removing the alternator no longer appears.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.C-6421, Windows XP SP3 x86, curses.
![1111111111](https://cloud.githubusercontent.com/assets/11132525/25771621/452505d4-325f-11e7-9db0-0f50b43cbdcf.PNG)
