### ISSUE TITLE
Zombie Slaves appear in random area after leaving and re-entering reality bubble.

### ISSUE THREAD

**Issue by TheSadFox** [CleverRaven/Cataclysm-DDA#19853]
Tying a slave in a specific place, moving far enough for it to leave reality bubble and then coming back results in the slave appearing in a random spot in the bubble rather than in the spot it was left in.

As is, the feature is more hassle than its worth (which is a shame, since having a bunch of zombie mules beats dragging a shopping cart or a box behind you by a lot immersion wise), having to constantly waste time playing hide and seek with the slave whenever you want to part ways with it for a moment, made even worse if the place you left it in is something with a lot of rooms like mansion, forcing you to search every single room over and over again trying to find the bastard, or praying they don't spawn somewhere outside near wildlife and get murdered before you get to them, et cetera.

**Comment by Coolthulhu** [comment]
Hordes on or off?

**Comment by SeikoTheSeal** [comment]
Hordes on.

**Comment by Coolthulhu** [comment]
Could possibly be caused by slaves forming 1-zed hordes. I don't see anything that would prevent "hording" behavior in zeds impaired in any way.

**Comment by keyspace** [comment]
Was viewing related code recently, pretty sure that's the case.

How should this be resolved? By [making another exception](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/overmap.cpp#L2907) in `overmap::move_hordes()`?..

**Comment by keyspace** [comment]
Reviewed this. A monster is set "zlave" like this in `game::revive_corpse()`:

``` c++
6832     if (it.get_var( "zlave" ) == "zlave" ) {
6833         critter.add_effect( effect_pacified, 1, num_bp, true );
6834         critter.add_effect( effect_pet, 1, num_bp, true );
6835     }
```

Not sure how to pigeonhole into `overmap::move_hordes()`:

``` c++
2969             auto& type = *(this_monster.type);
2970             if(
2971                 !type.species.count(species_id("ZOMBIE")) || // Only add zombies to hordes.
2972                 type.id == mtype_id("mon_jabberwock") || // Jabberwockies are an exception.
2973                 this_monster.mission_id != -1 // We mustn't delete monsters that are related to missions.
2974             ) {
2975                 // Don't delete the monster, just increment the iterator.
2976                 monster_map_it++;
2977                 continue;
2978             }
```

Semi-related to #20069 (Dropping the hardcoded "corpse" item).

**Comment by Coolthulhu** [comment]
Checking for either `pet` or `pacified` effect would be enough. Currently all zlaves are both pacified and pets. It would be possible for a non-zombie critter to be pacified if it breathed pacifying gas, or for a non-pacified zombie to be a pet if a mod created it.

Checking for `pet` sounds safer. Plus, it makes more sense: "tame" zombies should not hang around with wild ones, while de-fanged zombies should still try to act like zombies and mill about with other zombies.
