### ISSUE TITLE
Relaxation gas does not seem to stop friendly NPC from attacking.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19864]
Possibly applies to other NPC and/or creatures as well.

**Comment by I-am-Erk** [comment]
Do we even still have relaxation gas?

**Comment by Night-Pryanik** [comment]
> Do we even still have relaxation gas?

Yes, riot bot attacks by spraying relaxation gas.

**Comment by NetSysFire** [comment]
Also sleepwalker zombies

**Comment by MNG-cataclysm** [comment]
I tested this on the 12/1/2022 release. The relaxation gas does prevent the NPC from fighting.

**Comment by NetSysFire** [comment]
Closing as fixed. Yell at me to reopen if its still valid.
