### ISSUE TITLE
Spike(vehicle part) is bugged.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19869]
Forgive me for the vague description, but I didn't want to create two issues for two minor bugs, namely:

- Upon destruction the part drops a full health spike

- Repairing it uses twice as many welder charges as installing it.

**Comment by illi-kun** [comment]
First one is OK, the second one is a minor balance issue.

**Comment by CoroNaut** [comment]
I'm confused as to why a damaged spike on the vehicle would produce a fully repaired spike when breaking off. What if by damaged, the spike is bent to one side because you hit a building, it shouldn't automatically straighten when broken off.

**Comment by kevingranade** [comment]
I think the assumption is that the breakage is just the connection of the
spike to the vehicle.

Probably the best behavior would be to apply random damage to the dropped
item, but I'd want to make sure that doesn't have unintended consequences.

**Comment by Asmageddon** [comment]
Since all other parts break apart when destroyed, I think it'd make sense for spikes to do the same, I don't really see any alternative solutions.
