### ISSUE TITLE
Adding zones not working

### ISSUE THREAD

**Issue by gcaliber** [CleverRaven/Cataclysm-DDA#19876]
Trying to add a zone will sometimes add it near the location I have done so, but usually it can't even be seen on the map. Also verified that it is not just visual, it also has no effect in the area I designated for it. As a test I added the zone in as large an area as I could and it covers about half of that area and is off center and not square.

**Comment by Leland** [comment]
Note to self: check how this behaves when circular distances are on/off. Have a hunch something ala #20020 is going on

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed.
