### ISSUE TITLE
Warn player when distancing from an allied NPC.

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#19873]
Too often I find I have left an NPC asleep or stuck in a basement somewhere and I have wandered a very good distance away before I realize they were left behind many screens back, and sometimes I'm not even sure where... It would be nice to be warned with a text box of something like "You are about to leave foo behind, would you like to mark on your map where you have left him/her? (Y/N)" after you get a certain number of tiles away.

**Comment by Night-Pryanik** [comment]
No discussion in a very long time, closing.
