### ISSUE TITLE
Motorcycle engines lack kick/pull start

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#19872]
I took an engine from a lawnmower and put it into a wooden frame with vehicle controls, but I can't kick (pull) start it.  Given that disassembling the lawnmower didn't give a battery it's illogical to imply the motor was an electric ignition only engine.

Even given the game concession of it becoming a "motorcycle engine" as it's listed, I think irl most motorcycles still allow manual starts (even the ones that also allow electric ignition).

Is manual start on motorcycles left out for a reason?
Is this a known issue that's just low priority?

I searched for kickstart but didn't find anything

**Comment by WizardOfOoo** [comment]
It's not in the game, but now that you bring it up. I think it should be!  I'd also like to see some hand crank starters.

**Comment by WizardOfOoo** [comment]
Maybe allow some small engines to be started if foot pedals are installed?

**Comment by Greiger** [comment]
I might be thinking incorrectly but I think there are some engines now that don't require any electric charge to start and are flagged for it to be impossible for them to have a faulty starter motor.  I kinda figured those implied that they are kick start engines.

I don't recall off the top of my head if the motorbike engine is one of them though.

**Comment by Barhandar** [comment]
1-cylinder engines have 0 epower, meaning they won't drain the battery to start (and keep running). Not sure if there is any code to handle kickstart, though.

**Comment by Leland** [comment]
Closing due to lapse in the discussion. Feel free to ping me to reopen if there's still interest in discussion/developing this!
