### ISSUE TITLE
Metabolic Interchange appears to be broken.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19870]
My case was Helicopter Crash scenario, Bionic Soldier class, and attempting to use metabolic interchange with night vision. According to the description, it should proceed to drain hunger instead of batteries, but that is not the case.

**Comment by Aivean** [comment]
It should recharge your bionic pool increasing your hunger. I assume you haven't installed any Power Storage CBMs?

**Comment by 1skandar** [comment]
Or it was draining faster than the pool recharged. Worth checking.

**Comment by Asmageddon** [comment]
Bionic soldier starts with power storage installed, and I don't think it recharged it. Either way, even if it does that, that's a description mismatch.

**Comment by 1skandar** [comment]
I think that is working as intended. A metabolic interchange provides, at most, 5 power a turn. Night vision consumes 5 power a turn. If you had any other bionics running it wouldn't have been able to keep up.

**Comment by keyspace** [comment]
@1skandar described it well. PR above takes the easy-fix approach and edits the CBM description.
