### ISSUE TITLE
Being able to get NPCs to craft recipes

### ISSUE THREAD

**Issue by Nymall** [CleverRaven/Cataclysm-DDA#19883]
I would love to see some rudimentary setup for having NPCs being able to craft a recipe requested by the character. Something where you could set up a assembly line of crafters who would work when they are not travelling with your character.

- The player should be able to define a tile or storage to pull raw materials from.

- The player should be able to define furniture that acts as liquid storage as a possible origin tile.

- The player should be able to define a output tile to store finished goods.

- The NPC should be able to be given a rechargable tool(like a hotplate) to use for the recipe. NPC should be able to charge the tool from batteries or plutonium in crafting source tile to recharge the device.

- The NPC should be able to grab and use any chargeless tools from the crafting source tile and put them back once done.

- This should be a lowest priority job. NPC should do this at their discretion.

**Comment by hawkwinghasseler** [comment]
As an alternative for what sounds like a complex solution, why not just have NPCs be able to 'assist' the player in crafting/construction? NPC skills could substitute player skills if the player doesn't have high enough skills to perform a task, and tasks could take less time depending on the number of nearby characters with the skills to assist.

Characters without the skill to take part could follow along and learn instead.

**Comment by Coolthulhu** [comment]
It's "planned" as in "it would be cool to have someday".

Still, it is a pretty complex thing to set up.

**Comment by Nymall** [comment]
NPCs can already assist with crafting, but it's very fiddly to set up(they need to be 1 tile from the character, sometimes it does not work) Having three NPCs that have cooking 4 helping me do a stack of 20 dehydrated food may knock 20 minutes off.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
