### ISSUE TITLE
can't read kompot recipe

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#19887]
The KOMPOT recipe is longer than the default screen can display, and the pgup and pgdn only works for the item info no the recipe making it possible to be missing ingredients and not know what you actually need.

I've also tried up, down, left, and right but none seem to scroll the recipe page

**Comment by AMurkin** [comment]
Key m, pressed few times, do something like page down. But way to scroll the recipe would be better, of course.

**Comment by Xpyder** [comment]
For those who don't know, "M" cycles the display mode, basically hiding the tools and stuff at the top of the recipe

**Comment by DaliTimelord** [comment]
A screenshot would be helpful here.

**Comment by Xpyder** [comment]
![image](https://cloud.githubusercontent.com/assets/12039454/22162599/3b04304c-df04-11e6-8a50-9471583202c4.png)

**Comment by Xpyder** [comment]
Sugar is the component that's missing.
Also I have my screen much larger than default, a default setup would show even less.

**Comment by Zireael07** [comment]
Kompot is the prime example of a recipe that needs flags or some other way of trimming down the excessive list of ingredients.

**Comment by Night-Pryanik** [comment]
The components list needs a scrollbar for this, closing in favor of #22337.
