### ISSUE TITLE
Recipe: Gas Mask uses wrong goggles

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#19884]
A minor issue

Gas Mask currently takes Ski Mask (which gives glare protection 1) but doesn't itself give glare protection
This should probably be changed to Safety Glasses

Also not sure why it would require 2 pairs of swimming goggles instead of just 1

**Comment by Rivet-the-Zombie** [comment]
>Also not sure why it would require 2 pairs of swimming goggles instead of just 1

Maybe it needs some extra parts from the second one?

**Comment by Xpyder** [comment]
I presume the reason for them is to protect your eyes, and I don't know how 2 (or any additional parts from a second pair) would protect them any better than 1 pair.

As for the Ski Mask it's possibly the reason is to prevent using only player made items for construction, so possibly some other version of safety goggles if there is one.  It just seems weird for the glare protection to just disappear.

**Comment by kevingranade** [comment]
Ski masks and gas masks seal, safety goggles do not. Also safety goggles
are rather flimsy in comparison to the other two.
On the other hand I wouldn't be opposed to adding glare protection to the
gas mask.

**Comment by Barhandar** [comment]
The only way a gasmask is going to give glare protection is the same way a brimmed hat will, namely by limiting your field of view up. Which it _does_.

**Comment by Xpyder** [comment]
IRL Ski Masks don't actually seal.  They're designed to vent (albeit slowly) to help reduce steam buildup

**Comment by Xpyder** [comment]
As I look more into this I've uncovered a couple more inconsistencies, like swim goggles being able to be made from welding goggles.

Given that this isn't a one-off, that there isn't a trivial alternative we can swap out, and that there are more important issues to focus on presently I'll let this go for now.

It might be worth changing at some point if a better alternative is offered, but not worth pushing at the moment.
