### ISSUE TITLE
Storage Battery Assembly/Disassembly Charge States

### ISSUE THREAD

**Issue by malcolmputer** [CleverRaven/Cataclysm-DDA#19889]
- OS: Linux (Gentoo)

- Version: 0.C-20361-g2853adf-dirty

- Disassemble a Storage battery in 100% charge into Medium Storage batteries.  Charge is now 0%.  Assemble fully charged Medium Storage batteries into a Storage Battery.  Charge is now 0%.  This applies to Small Storage batteries as well.  

Charge should be a evenly distributed from the higher battery tier to all smaller batteries when disassembled, for example, if I disassemble a Medium Storage battery with 3500/7000 charge, I should get 8 Storage Batteries each at 250/500 charge.  

In reverse, if I have 4 Medium Storage Batteries, one at 7000/7000, one at 3500/7000, one at 0/7000, and another at 1750/7000, I should receive a Storage Battery at (0.25 + 0.125 + 0 + 0.0625 = 0.4375 * 40000) 17500/40000 charge.

**Comment by Aivean** [comment]
While the idea of preserving the charge when assembling/disassembling the battery may be viable, the suggested implementation is wrong in my opinion. 

In your second example (assembling the storage battery) you get extra charge out of nothing (initially you had 7000 + 3500 + 1750 = 12250, which is less than 17500), which should not happen. Charge can only decrease during assembling/disassembling.

**Comment by malcolmputer** [comment]
I disagree with you.  The batteries themselves have a different storage capacity pre and post disassemble.  In my example, you could take them apart and put them back together and you would have the same charge.

As far as why cdda allows less or more charge to be stored, that isn't an issue with the idea of preserving charge, but a balance or recipe problem. 

If you need a role playing reason for why charge can "increase" during assembly, that's because the UVLO of the devices is at the same drop out voltage, but the total pack voltage is higher.
