### ISSUE TITLE
NPC's abandon safe tiles (vehicle tiles) and jump into harmful effects.

### ISSUE THREAD

**Issue by TheSadFox** [CleverRaven/Cataclysm-DDA#19895]
When NPC is standing on a vehicle tile (in my case, a cart made of wooden boxes), and the tile is "hit" by a special zombie like spitter or smokers smoke, even tho vehicles offer protection from such effects, and the acid/smoke is not created on its tile, the NPC will jump off the vehicle and try to escape the acid puddle/smoke cloud, going out of position or further harming themselves.

**Comment by Night-Pryanik** [comment]
Should be fixed by #23592.
