### ISSUE TITLE
0.C-20368-g28fa326 / 0.C-6093 examine pile/inventory with certain items -> crash

### ISSUE THREAD

**Issue by jepeman** [CleverRaven/Cataclysm-DDA#19894]
Title screen version: 0.C-20368-g28fa326
Launcher/download name: cataclysmdda-0.C-6093
Windows Graphical version via: http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/cataclysmdda-0.C-6093.zip
OS: Win 10 64bit

Version 0.C-6093 seem to have created a weird bug. Opening inventory (with i) or examining (with e) a container/pile with some specific items causes a crash. Using advanced inventory management (the / command) doesn't cause a crash even when looking at the crash inducing container/inventory.

With some testing, found one way to always cause crash: having more than one plastic bag.

One plastic bag in inventory or container is fine, but if there are 2 or more in the container/inventory, crash.
There are certainly other items that causes the crash too, since just examining some of my other containers without plastic bags, also causes crash, unfortunately they have a LOT of different stuff, so hard to isolate. However, not every stash or pile causes a crash.

Even tried starting a new world and new character without mods and using debug command to spawn in plastic bags.
1 plastic bag in inventory, open inventory with i, no problem.
2 plastic bags in inventory, open inventory with i, crash.

As added fun, having 2 plastic bags in inventory, that causes the crash when opening inventory, you can activate advanced inventory management and move 1 bag to ground. Resulting in it being safe to open your inventory or examining the 1 bag on the ground. However combine those bags in a single pile and examine it, you crash.

Version 0.C-6093 patch notes that is the possible culprit:
http://ci.narc.ro/view/Cataclysm-DDA/job/Cataclysm-Matrix/6093/changes

Also crashes in 0.C-20370-g11892bf / 0.C-6094

**Comment by BrettDong** [comment]
I don't have the issue. Compiled with MSVC, Windows 10, x64.

**Comment by FullOfSpiders** [comment]
I have the same issue using the jenkins build 0.C-6094 and 0.C-6097. Windows 8, x64.

(e)xamining or opening the (i)nventory with multiple nails or fishing hooks causes a crash.

Beware the stackables, they now seek their revenge!

**Comment by BrettDong** [comment]
![Screenshot](https://cloud.githubusercontent.com/assets/21075502/21579844/61804196-d001-11e6-927c-35e84d84595e.png)

@FullOfSpiders Do you mean viewing items in inventory as above causes a crash? No crash occurred with MSVC compiled binary, so it might be a MinGW or Windows related issue?

**Comment by BrettDong** [comment]
![Screenshot](https://cloud.githubusercontent.com/assets/21075502/21579865/8d937130-d002-11e6-8815-eeb324ba77fd.png)

@1skandar You saw something like "EXP(zu)" instead of "EXP(1)" in the screenshot above? It sounds like a regression of #19488 , but I didn't encounter the problem.

**Comment by 1skandar** [comment]
That is correct, this is the build pulled off the Jenkins, not built myself. It is almost certainly Windows specific. They were talking about holding off on pushing that commit until they fixed the Windows build environment and I'm guessing they never did.

**Comment by BrettDong** [comment]
After some googling, I saw some people complaining that `%zu` doesn't work for some reason in MinGW.
[https://www.reddit.com/r/C_Programming/comments/38ua56/zu_and_windows_and_other_woes/](https://www.reddit.com/r/C_Programming/comments/38ua56/zu_and_windows_and_other_woes/)
[https://lists.gnu.org/archive/html/bug-gnulib/2014-09/msg00050.html](https://lists.gnu.org/archive/html/bug-gnulib/2014-09/msg00050.html)

**Comment by BrettDong** [comment]
Just downloaded Jenkins 6097 build, confirmed crash!

**Comment by BrettDong** [comment]
![default](https://cloud.githubusercontent.com/assets/21075502/21579908/1fcac33e-d006-11e6-8ef1-0af38f76689b.png)
Damn, debug symbols are stripped, I can't see the backtrace.

**Comment by BrettDong** [comment]
Figured out the explanation: MinGW generated binaries are just calling `msvcrt.dll` for C runtime functions, but `msvcrt.dll` doesn't support any C99 feature (`%zu` is a C99 feature), then BOOM. `%zu` is only supported in later MS C runtime libraries which MSVC is using (eg. `msvcp140.dll`), so my MSVC built CDDA works fine.

**Comment by 1skandar** [comment]
Well, that's a step in the right direction.  What's the fix?

**Comment by kevingranade** [comment]
The immediate fix is reverting the pr, it doesn't fix any outstanding bugs
so that's the lesser evil.

**Comment by narc0tiq** [comment]
The real fix is to get the new build environment at <http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/> working, so we can switch the experimentals to it. Reference: #19339.

**Comment by 1skandar** [comment]
The revert does appear to have fixed this crash, this issue can likely be closed.
