### ISSUE TITLE
Folding stock reduced wield time by ~50%

### ISSUE THREAD

**Issue by dreyskiy** [CleverRaven/Cataclysm-DDA#19892]
Folding stock description says it will increase the wield time in exchange for lowering the volume.  After installing a folding stock on my A7 rifle the volume goes down to 1.5 from 3, and the time to wield goes from 810 to 578 to equip and from 810 to 450 unequip to inv.

I can attach a savefile if necessary.

**Comment by ZenZen2** [comment]
shhhhh dont tell anyone :p

**Comment by WizardOfOoo** [comment]
Can confirm.  A7 With folding stock wields from inventory in 18 seconds.  With no stock it's 44 seconds.

**Comment by WizardOfOoo** [comment]
I think the slow_wield tag might be broken.

Guns with bipods deploy only slightly slower.

**Comment by keyspace** [comment]
It's not exactly "broken", but there's [a lot of scaling going on](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L2105). Wield time for `SLOW_WIELD` weapons (both guns and melee) depends on player skill.

Note how the calculation for `COLLAPSIBLE_STOCK` [is done, also with scaling](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L2578).

In a quick test, AK-74M (without mod in question) and AK-74M+ (with mod) get wielded in about the same time by a 0-skilled character.

This is all very dependent on specific weapons, their volumes, and the scaling factors being used for both (1) `SLOW_WIELD` and (2) `COLLAPSIBLE_STOCK`. Changing these factors would probably require extensive tests with (3) various-size items wielded by (4) varying-skill characters.

The charts to visualise this would be at least 4-dimensional, assuming (1) was not a matrix as it is now. Reasoning in these conditions might be problematic.

-----

How about adding "it gets better with practice" to the folding stock's description instead?..

**Comment by keyspace** [comment]
> Can confirm. A7 With folding stock wields in 18 seconds. Plain gun is 42 seconds.

OTOH, taking this into consideration, the above solution wouldn't work. :/

**Comment by WizardOfOoo** [comment]
Just did it again on a brand new PC, only skill is rifles 3 (needed to attach folding stock)

42 seconds for the plain gun
24 seconds for the modded one
