### ISSUE TITLE
Crash on examining items

### ISSUE THREAD

**Issue by Meeshoo** [CleverRaven/Cataclysm-DDA#19897]
On spawn I smash the bench immediately to the left, on examining the pile of things it drops my game immediately crashes. On the same save the game will crash every time I kill an enemy.

Running on an AMD Radeon HD7950 and i5 3770 with 8GB of RAM.

[Swandale.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/679783/Swandale.zip)

**Comment by BrettDong** [comment]
Looks like the same problem with other crashes reported this morning.

**Comment by keyspace** [comment]
Brett is referring to #19894 I assume.

@Meeshoo, try a build after the revert above if you're running on Windows.
