### ISSUE TITLE
improvized first aid kit can't clean wound at full health

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#19890]
The improvised first aid kit can't be used to clean a bite wound if the limb is at full health

This is in contrast to cauterizing it or using a first aid kit, so it's probably just an accidental omission in the implementation

**Comment by keyspace** [comment]
`1st_aid_survivor` does not have `bite` and `infect` in its `use_action` (intentionally).

It was added in e55ce917 (PR #17492). See #16017 for overarching discussion.

**Comment by keyspace** [comment]
The confusion arises from it being called a "first aid kit", although it's more of a bandage. This was discussed in #17492.
