### ISSUE TITLE
No longer able to add Mudane or Slow Zombies to New Worlds?

### ISSUE THREAD

**Issue by MedievalNerd** [CleverRaven/Cataclysm-DDA#19900]
Setup: CDDA Launcher with build # 6907, Windows 10, x64 & Tiles

When I create a new world, the mods for Mundane Zombies and Slow Zombies are not available.

Have they been removed? I've been away for a few months, I can't seem to find any info on their removal.

**Comment by Hellrazor236** [comment]
Slow zombies are worldgen options now.

**Comment by MedievalNerd** [comment]
That's unfortunate. From what I see that option, if you are speaking about 'Monster Speed', seems to be for ALL monsters. Not just zombies.

And what happened to mundane zombies though? Would you know whether it got removed?

**Comment by Barhandar** [comment]
It was marked as obsolete (you can unmark it in the mods' modinfo.json) because it's orphaned and too much of a distraction to maintain.
