### ISSUE TITLE
NPC Talk logic causes segfault.

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#1990]
Version 0.6-345-g13b3711

Prerequisite: have really high skills. (Not sure if strictly necessary, but see step 4.)

1. Accept "Kill Zombie Mom" mission.
2. Lie about success immediately after, succeed on the lie.
3. Ask for training as a reward.
4. NPC can't train any skills.
5. Okay, then.
6. Segfault.

I don't really understand the layout of the NPC talk logic, so I don't know how to actually *fix* this problem; however, a temporary band-aid exists in the form of ensuring that variable "miss" isn't null before dereferencing it in calculations (e.g. on npctalk.cpp:616, miss->value).

**Comment by mugling** [comment]
I've tested this in `master` and cannot reproduce it. There have been considerable code changes since this issue was reported so presumably given the recent work on NPC's this has been resolved.
