### ISSUE TITLE
Vending machines don't respect the item spawn scaling worldgen setting

### ISSUE THREAD

**Issue by TheSadFox** [CleverRaven/Cataclysm-DDA#19906]
Basically what it says on the tin. Playing on a greatly reduced item spawn, and stumbling upon stuff like this http://prntscr.com/dqg84j (these are contents of an already half looted vending machine in a hospital) every  other gas station or subway is kinda meh.

**Comment by RogueYun** [comment]
I think there might be a couple of other resource locations that might be better off linked to the item spawn ratio as well.

- Items in cars/vehicles (lots of fully stocked fire trucks about).
- The amount of useful clothes/items dropped by zombies.

I get the feeling there are others but I can't think of them off the top of my head.

**Comment by WizardOfOoo** [comment]
Several set pieces would fall into this category.

**Comment by Vidiveni** [comment]
Which version are you using? In latest versions it's impossible for me to create a world using custom item spawn settings.

**Comment by sniperm13** [comment]
Those fire trucks. Sickeningly awesome source of kevlar. Game breaking even. That, you can nerf. XD

**Comment by TheSadFox** [comment]
>Which version are you using? In latest versions it's impossible for me to create a world using custom item spawn settings.

0.C-6085

**Comment by codemime** [comment]
Presumably causes #15458.

**Comment by Night-Pryanik** [comment]
That's not a bug IMO.

**Comment by Night-Pryanik** [comment]
Tested on latest experimental as of 06 April 2019. Vending machines do respect global item spawning setting.

1.00 item spawning setting, average amount of loot from vending machines
![изображение](https://user-images.githubusercontent.com/11132525/55670040-579db900-5890-11e9-9d61-6dc6fab8ee9d.png)

10.0 item spawning setting, lots of loot from vending machine in the motel
![изображение](https://user-images.githubusercontent.com/11132525/55670013-cfb7af00-588f-11e9-9dbf-942126576729.png)

0.01 item spawning setting, all I got is empty vending machines
![изображение](https://user-images.githubusercontent.com/11132525/55670047-74d28780-5890-11e9-830f-879e0b8c5682.png)
