### ISSUE TITLE
"Huge vehicle mod" provides no indication of what it actually does

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19902]
Maybe the description part should be modified to say it triples fuel potency, or something?

**Comment by WizardOfOoo** [comment]
Is that the only thing it does?

**Comment by keyspace** [comment]
Note: mod id `megaveh`, on git master ATM (`0.C-20421-gd55baf1`) indeed increases `diesel` and `gasoline` fuel `energy` 3 times (75 and 50 respectively in core pack, 225 and 150 in `megaveh`).

`battery` does not yet have an `energy` value ([see def](https://github.com/CleverRaven/Cataclysm-DDA/blog/master/data/json/items/ammo.json)), so moot.

**Comment by Regularitee** [comment]
Proposed changes submitted here. Please let me know if there are any objections. 

https://github.com/CleverRaven/Cataclysm-DDA/pull/19919

**Comment by kevingranade** [comment]
Addressed by #19919
