### ISSUE TITLE
Base vehicles need a bit of a rework/

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#19911]
Ran across a working semi today and noticed it had a max speed of 21 mph. After a bit of poking I discovered that it was using a V6 diesel engine which is a wee bit underpowered. Several other vehicles are in similar boats, notably the RV and the ambulance are both much, much slower than they have any right to be. With the vehicle speed rebalance it might be a good idea to look at the included vehicles and upgrade their engines as appropriate so you don't have semis doing 20 or ambulances doing 50 ot RVs doing 40.

**Comment by kevingranade** [comment]
Just rescaled the reported vehicle speeds to be closer to the actual
speeds, vehicles for the most part need to have their speeds increased a
great deal.

**Comment by 1skandar** [comment]
Yeah, but beyond that several of the vehicles have engines that are a tad underpowered for what they are. A hatchback and a SUV doing 60 to 70 mph is fine, an ambulance doing 50 is less so, all three are using the same engine, a gasoline v6. The ambulance should likely be moved to a v8 to account for its greater weight. And a semi with a v6 diesel is 

That said, I have noticed that speed drops wayyyyy to quickly as weight gets added, and diesels suffer from this the most. For truck semi, and other big vehicle engines, a diesel engine should be relatively slower than a comparable gasoline engine, but suffer less drop off under added weight.

**Comment by keyspace** [comment]
There are 76 vehicles in `data/json/vehicles/*`. How to review wholesale? A table with id/engine(s)/speeds?..

Tangently related: #19761 (diesel engines not exceeding 3rd gear)

**Comment by 1skandar** [comment]
Yeah. There is a command line dump but my system is currently hating on it.  It will also act as a way to make sure the vehicle rework is outputting reasonable speeds.

**Comment by keyspace** [comment]
@1skandar do you mean `tools/json_tools/pluck.py`? I've got a git stash with a "port" to Python 3.6 that _almost_ retains compatibility with Python 2. Can share if needed.

A proper review, however, would probably require a unit test with safe/optimal/max speed dumps. Could attempt, no ETA.

**Comment by 1skandar** [comment]
--dump-stats VEHICLE at the command line *should* do exactly what it says, but for me isn't is what I mean.

**Comment by keyspace** [comment]
Ah, OK. JIC, [here it is](https://gist.github.com/keyspace/049a38eb437706ef9cc6067579113001) at current master.

**Comment by 1skandar** [comment]
Thanks for that.

Yeah, that makes things much clearer. Weight is impacting top speed much more than it should, especially for diesel powered vehicles. For most of the lighter vehicles the top speed is right around where you'd want it to be, upper 6s to lowers 7s, but the heavier vehicles have ended up too slow in the process. There is some balancing that needs to be done here, and I think at least part of it is that diesel engines have ended up underpowered for whatever reason.

**Comment by keyspace** [comment]
Revert of #19275 (Vehicle propulsion overhaul) might have made this obsolete.

The dump posted above is no longer actual.

**Comment by keyspace** [comment]
[Here it is](https://gist.github.com/keyspace/675c930d94e2999b12d4df9b8b675abc) again, after the revert.

**Comment by 1skandar** [comment]
Huh, that's revealing. 

Yeah, ok I see a few problems here. Max speeds per engine being too high we  knew about. Honestly, if those weren't exposed to the public and vehicles were locked to their safe speed that'd fix that nicely. You'd likely have to adjust that up or down a tad to zero things in a bit, but meh.

It also looks like there is little to no difference made between diesel and gas engines. A V8 is a V8, more or less. From a realistic standpoint, ok, yeah, sort of. Kinda. From an in-game POV, though, that needs changing. If it was me I'd give diesel engines less max potential speed, but a better power to weight curve. 

And that is the really big problem I'm seeing here, the power to weight curve is effed up. Look at the Fire Engine versus the Fire Truck, Same engine in both, but the Fire Truck is over double the weight but loses only 20 mph off its safe speed. I'd have to look at the code but I'd say the power to weight curve flattens too fast on bigger engines, you get to the point where extra weight added makes little difference in safe speed too quickly. Again, something that can likely be tweaked until it feels better. 

Lastly, there should be a penalty for putting an outsize engine on something. While a player should be allowed to put a V12 on a wheelchair, he should also should be penalized for doing so. I'm thinking that the higher up the power to weight curve you are the higher your driving skill should have to be to keep control of the vehicle. A driving skill 0 player who builds the aforementioned V12 wheelchair should have very little control on where it goes, nor how fast. Combine that with the lack of traction such a vehicle would have, well, a player could still have his fun but a practical vehicle it certainly would not be.

**Comment by Zireael07** [comment]
@1skandar: Mugling's overhaul attempted to fix the issues you're pointing out, but it introduced its own problems.

**Comment by 1skandar** [comment]
@Zireael07 I'm well aware of that. I'm considering what I want to do here. Now that I can see the problem a bit more clearly I might poke this myself. I a bit of a hack programmer, but I bet I could scootch the current system around a bit to fix the more egregious faults. I need a project, anyway.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
