### ISSUE TITLE
Science Card Readers remove turrets on different Z-levels

### ISSUE THREAD

**Issue by Nioca** [CleverRaven/Cataclysm-DDA#19917]
`Experimental Version Build 6049 Windows 7 Console`

Was poking around to see if Science Labs and Bunkers could be JSONized or have JSON counterparts, and noticed what looked like unintended behavior with Z-Levels turned on. If you swipe a Science ID card at a lab's card reader, it removes not only turrets on the Z-Level the card reader is on, but also all turrets that are above and below the card reader's Z-level. Basically, every turret in the reality cylinder gets poofed into thin air.

This was tested with regular and milspec turrets (not laser or antimateriel), and both exhibited the same behavior. I haven't had a chance to test the military bunker's card reader yet, but I'd expect the same kind of behavior from them.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.C-7145, Windows XP SP3 x86.
