### ISSUE TITLE
World gen scaling factors rounded to close integer

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#19921]
Sry for my english..

I use latest game from Index of /cataclysm/jenkins-latest/Windows_x64/Tiles
I try to make Item spawn scaling factor 0,1 or 0,01 but i find there are no difference in game compare to 1.
NPC spawn rate scaling factor 0,1 works the same as 0.00 
Looks like game round this factors to close integer. As item spawn cant be 0, it is rounded to 1. 
And npc spawn factor is rounded to 0..

**Comment by ZenZen2** [comment]
i have to confirm this with item spawn rate. I dont see any difference playing with 1.0 or 0.4 (different new worlds, no ingame changing) but there is a difference if i set it to 4.0
Didnt check NPC spawn and monster spawn rate.

**Comment by codemime** [comment]
I suppose this is related to #9564.

**Comment by ZenZen2** [comment]
I think this is fixed with #20222 and can be closed.
