### ISSUE TITLE
Allow fitting of some clothing without tools.

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#19928]
This is more of a suggestion then a bug, close it if you don't like it, won't hurt my feelings.

If I have non mutated anatomy I should be able to use the straps and other adjustments to size an item like a MBR vest, Kevlar vest, utility vest, backpack or other such item to fit without tools or skills.

Code wise, maybe in the same way that we allow things like ski masks and scarves to be transformed into different items we could cause the item to transform to the "fits" version upon activation.

Would close [#9605](http://github.com/CleverRaven/Cataclysm-DDA/issues/9605)

**Comment by Coolthulhu** [comment]
If they are supposed to be fittable in no time, there is no reason to ever treat them as not fitted.

**Comment by WizardOfOoo** [comment]
I did a quick pass of items with the VARSIZE tag.

Most if not all masks, belts, wraps, quivers, Tactical vests, rigs, harnesses, bandoliers.  Also, the fanny pack, headgear, Turban, elbow pads, and knee pads, and arm guards, are adjustable IRL.

**Comment by Coolthulhu** [comment]
So in the game they should have stats of a fitted item and no ability to fit them again.
And if they don't have VARSIZE, it means they are refittable without tools already and nothing needs to be changed.

**Comment by Zireael07** [comment]
@Coolthulhu's solution is one, I have a slightly different idea - you can make VARSIZE items fit without tools but it takes 10 minutes. Or maybe 20. I only have experience with backpacks, what about the other stuff?

**Comment by natsirt721** [comment]
Seems like extra work for no real gain. If there are any items that don't have VARSIZE but an unreasonably high encumbrance it would be far easier to balance the offending items rather than rework the mechanic.

**Comment by Reclusive-reptile** [comment]
I agree with @Coolthulhu. One size fits all items shouldn't have VARSIZE and just have the best encumbrance values out of the box.

**Comment by WizardOfOoo** [comment]
>So in the game they should have stats of a fitted item and no ability to fit them again.
And if they don't have VARSIZE, it means they are refittable without tools already and nothing needs to be changed.

So I could just remove 'varsize' from them and half the encumbrance?  If it's just JSON stuff i can handle it.  What is the rule the code uses for halfing?

**Comment by keyspace** [comment]
> What is the rule the code uses for fitting, (what is the rule for halving encomberance, or ist it even half)?

It's calculated in [`item::get_encumber()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L2911). For `FIT` items it's [this line](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L2930):

```
encumber = std::max( encumber / 2, encumber - 10 );
```

So the larger of either "half" or "ten less". For generic items up to 20 encumbrance a fit item will have half, for items 21 and above it will have ten less.
