### ISSUE TITLE
Assorted crafting-related balance problems

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19929]
- EMP grenade is crazy cheap, requires no energy source of any kind, not even batteries

- Laser sights: 100 batteries or 1 plutonium cell... what?

- Can sealer appears to be unobtainable

- Hacks.. 1 power converter or 1 plutonium cell, what?

- Grenade can be made with gasoline, in fact less(200) than a molotov(500), what?

- There should be a clean water recipe using a purifier

- Scrap suit requires no tool and conspiciously few materials

- (Construction) Why is wooden keg a higher level recipe than a fermenting vat?

- (Vehicle) Internal door is essentially identical to opaque door, does it need to be in the game?

- (Bug) It's possible to learn a recipe twice by learning from book, then by disassembling

- 60L Tank should definitely take more than 2 minutes to craft.

- Rope from rags and disassembling into thread should probably take a bit less time than a full hour.

- Sewer brew cannot use strong mixed alcohol in its recipe

- Pro fishing rod can be only made using bismuth, but not lead, gold, silver, copper.

- Radio Activation Mod makes training electronics from 4 to 5 trivial.

- Plow, Scoop, Reaper, Seed Drill recipes have no books/autolearn

- (Bug) Sheets of reinforced glass made from /panes/ of glass?

- (Bug) Winter survivor mask(s) lack glare protection

- (Bug) XL gas mask can only use ski/swim goggles

- Why is steel jerrycan crafted from a 60L tank, and why does it need a string?

- Cargo carrier has no disassembly recipe

- Shouldn't bandage be made from rags instead of duct tape?

- Kilns are (much) smaller than the jerrycan it takes to make them

- Shouldn't medium/large electric motors be craftable?

- Welding tank exists only as a component of the welder, should it be removed in favor of using another tank?

**Comment by natsirt721** [comment]
- Plut cells are pretty useless unless one has a high electronics skill or a minireactor.  Allowing them to be used singly in simple recipes is probably not a huge deal.

-  If you consider the amount of volume in a glass bottle versus a grenade, I think you'll see why a Molotov takes 2.5 times as much fluid as the grenade.  However, liquid fuel grenades do seem a little silly.

- A recipe for clean water, using a water purifier (charcoal or electric) as a tool? What would be the advantage over just (a)pplying the purifier?

- Pro fishing rod recipe is a modded recipe I think - it doesn't show up on the item browser.  Bismuth is used presumably as an alternative to lead fishing weights but seeing as how the world has ended I don't think the EPA is going to get on any anglers over lead contamination. 

- I think the steel jerrycan recipe was from before the vehicle rework, but it does seem silly to require a 60L tank to create a 10L container. Perhaps a recipe involving sheet metal or a bucket would be more correct? The string may be to attach the cap to the can so it doesn't get lost, or as a primitive gasket between the cap and the container?

- The tractor attachments should be book learned but probably not autolearned.  Perhaps a book on the history of agricultural machinery?

- If anything bandages should require both tape and rags, but especially tape to secure the bandage in place.

**Comment by Asmageddon** [comment]
> A recipe for clean water, using a water purifier (charcoal or electric) as a tool? What would be the advantage over just (a)pplying the purifier?

Being able to put it in a separate vehicle tank for starters.

> Pro fishing rod recipe is a modded recipe I think - it doesn't show up on the item browser. Bismuth is used presumably as an alternative to lead fishing weights but seeing as how the world has ended I don't think the EPA is going to get on any anglers over lead contamination.

Oh, possibly.

> I think the steel jerrycan recipe was from before the vehicle rework, but it does seem silly to require a 60L tank to create a 10L container. Perhaps a recipe involving sheet metal or a bucket would be more correct? The string may be to attach the cap to the can so it doesn't get lost, or as a primitive gasket between the cap and the container?

Well, the problem I have with strings is that they're crazy hard to stockpile. The only reasonable source is long strings from curtains, crafting them by hand takes, what, 6h per long string? And that's not counting the rag disassembly, if that's what you're doing.

> The tractor attachments should be book learned but probably not autolearned. Perhaps a book on the history of agricultural machinery?

I very much so dig the idea. Wouldn't mind making them a bit more common so they can be learned by disassembly. Speaking of that, the game absolutely needs to let us write down recipes - because otherwise, learning via disassembly is 100% wasted if the char dies.

> If anything bandages should require both tape and rags, but especially tape to secure the bandage in place.

Nah, you can totally tie them off.

**Comment by Cyrano7** [comment]
It seems some of these have been fixed now like with the winter survivor mask not having glare protection via https://github.com/CleverRaven/Cataclysm-DDA/pull/20720 or are not valid like can sealer not spawning or XL gas mask taking only limited ingredients. The can sealer is in a few item groups and is just rare. There are two XL gas mask recipes, one with ski and swim goggles and one using a existing gas mask.

@Asmageddon With such sweeping lists it's hard to tell what is still valid and needs to be fixed. You can always resubmit a lot of these individually.

**Comment by Asmageddon** [comment]
Sorry x.x I might do that when I play the game again, but it might be a while before that happens.

**Comment by Leland** [comment]
Started cleaning this up and finding which are still issues. May port some to proper issues.
