### ISSUE TITLE
It's possible to exceed maximum allowed head encumbrance by modifying worn headgear

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19939]

**Comment by Regularitee** [comment]
Well, it doesn't really matter since head encumbrance has no penalty. 

Though that reminds me, https://github.com/CleverRaven/Cataclysm-DDA/issues/18874 still needs to be addressed.

**Comment by Asmageddon** [comment]
Ah, crap. Personally I don't really mind there being no penalty that much. I feel like the penalties system right now is a bit wobbly overall. With how hard the stuff you really need to be on lookout against, high torso encumbrance is unavoidable, and the situation is identical with the head.

**Comment by Leland** [comment]
Duplicate of #12897
