### ISSUE TITLE
Vehicle scoop makes any vehicle part with storage under 100L obsolete.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19933]
Because you can just mount it under an aisle/wall/whatever, and it'll give you 100L storage. Being rare isn't really that much of a solution. I propose it to have no storage of its own, and instead need being mounted under other cargo stuff.

**Comment by WizardOfOoo** [comment]
What about modifying it so that it takes up space like a quarter panel?

**Comment by Asmageddon** [comment]
If anything, it'd make more sense for it to be a "frame" like the reaper or spike. Though I think it'd make more sense for it to scoop up into a separate cargo unit.

**Comment by keyspace** [comment]
To clarify: `spike` and `reaper` vehicle parts are `PROTRUSION`s (`data/json/vehicle_parts.json`). There are quite a few of these. As such, they're handled a bit differently than frames.

`vehicle_scoop` is a special `SCOOP`, the only one in base `dda`. There are three more in `blazemod` (`data/mods/blazemod/blaze_blob_parts.json`).

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
