### ISSUE TITLE
Fungal tower corpse yields absolutely nothing upon butchering.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19937]
A bit odd for a 1.2 ton creature, if I can say so.

**Comment by CoroNaut** [comment]
Perhaps it should just be made into a map tile, and some dungeon similar to the triffids could be put in place.

**Comment by Asmageddon** [comment]
That would definitely be a great thing to eventually have. I think that for now making it yield... hard to say what, exactly, could be nice.

**Comment by Zireael07** [comment]
Lots of tainted meat/tainted veggy (forgot which one it should be)?

**Comment by Asmageddon** [comment]
What about a heckton of wood, too? Tbh, I feel like the fungal stuff is overall not very fleshed out - it'd be nice to have fungal wood+bone replacement, tainted shrooms, a few more mid-higher level fungal mobs, etc.

**Comment by kevingranade** [comment]
Since it's a corpse, I'm pretty sure it just needs some flags similar to other fungal creatures to enable butchery results, sounds reasonable to me.
