### ISSUE TITLE
Mutation balance and ideas.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19931]
- It should be possible to purify/lose genetic chaos, since it's possible to lose robust genetics.

- (Idea) Post-treshold fish mutation that allows eating plankton

- (Idea) Post-treshold plant mutation that allows overeating and producing excess calories as fruit.

- Medical category, too many, too likely, negatives?

- Fish, too few negatives?

- Cephalopod, not enough positives to go for it?

- Carnivore/herbivore: Increase nutrition obtained from said sources a bit?

- Plant: Should extremely ponderous be post-tresh downside instead? It's kinda brutal.

- Bird: Bad back + hollow bones makes wearing/carrying any meaningful amount of gear impossible, it makes the category 100% unviable.

- Make mutations damage and unequip gear instead of destroying it outright. It makes armor use virtually infeasible.

- IMO, reduce or remove base 33% chance for negative mutations. It makes mutating without robust genetics a horrible idea.

Sorry for not going into too much detail, I didn't play with mutations that much, just wanted to share my thoughts.

**Comment by Aivean** [comment]
> Bird: Bad back + hollow bones makes wearing/carrying any meaningful amount of gear impossible, it makes the category 100% unviable.

I'd argue that it's just niche (like many other categories).  Trading storage capacity for speed and perception is viable in the end game, when you don't really need to carry loot. Also when you're making your mutant build it doesn't necessarily mean that you end up having ALL negative mutations in the end. If you do you can purify and try again.
&nbsp;
> Make mutations damage and unequip gear instead of destroying it outright. It makes armor use virtually infeasible.

Strongly agree. There is not real need to destroy gear in terms of balance. It only gives players with out-of-character knowledge unwarranted advantage.
&nbsp;
> IMO, reduce or remove base 33% chance for negative mutations. It makes mutating without robust genetics a horrible idea.

If description on [the wiki](http://web.archive.org/web/20150911013439/http://www.wiki.cataclysmdda.com/index.php?title=Mutation) is correct, currently you have only 33% chance of good mutation. With robust genetics chance is 66%.  

I think base chance should be 50%. And maybe bump Robust Genetics cost (2 points is too low for such advantage)?

**Comment by Asmageddon** [comment]
> There is 2/3 chance to have any mutation and 1/3 chance to have only a "bad" mutation, though not all "bad" mutations are really bad ones and not all "good" mutations are equally desirable.

\^ From the wiki. Robust Genetics flips that from 33% bad, 66% any into 33% good, 66% any, which means that while good/neutral/negative don't have equal chances, it flips it from 22%/55% for good/bad, into 55%/22% good/bad. That's a 2.5x improvement. Also, it costs 3 points, which isn't that bad, but eh, it's too mandatory. 

> I'd argue that it's just niche (like many other categories). Trading storage capacity for speed and perception is viable in the end game, when you don't really need to carry loot.

I had a high strength character(means i had some carry weight left), and with both hollow bones and bad back, I felt utterly crippled. Carrying loot out of labs took 10x as long. Butchering animals took ages because I was constantly overburdened. I had to get rid of armor because it was too heavy. I couldn't carry a firearm because it was too heavy. I had to use a tool as a weapon because that's just how short I was on carrying capacity. It's most definitely utterly crippling.

**Comment by Nacarbac** [comment]
>And maybe bump Robust Genetics cost (2 points is too low for such advantage)?

Given that Robust Genetics is mandatory for any character intending to mutate, I think that'd be an unfair cost of entry. The mutation system needs an overhaul (and partial merge with cbms) in general, and RG is the flimsy patch that makes it somewhat bearable.

**Comment by Asmageddon** [comment]
Yeah. Another discrepancy is that Robust Genetics can be purified/mutated away, while Genetic Chaos cannot.

**Comment by Leland** [comment]
Closing due to lack of recent discussion.
