### ISSUE TITLE
Removing broken vehicle parts should require no skill and tools

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19935]
Since it's essentially equivalent to smashing the part in a slightly more targeted fashion.

**Comment by RogueYun** [comment]
Smashing some parts could potentially damage others... I tried to help a guy fix his car once, he was so impatient to get the job done he really did some damage. Something to do with the rotor screws iirc :/ He should never have taken a hammer to it. Smashing parts off a car doesn't seem like a good idea.

**Comment by Asmageddon** [comment]
It actually often is, in the game, right now. But destroyed parts serve no purpose, and it'd be nice to be able to remove them more easily.

**Comment by natsirt721** [comment]
Removing a destroyed tire should not require a jack? That seems pretty wrong... A similar argument could be made for removing a destroyed engine. There's a lot of mechanical stuff to deal with for installing an engine - you would most certainly NOT want to just cut hoses willy-nilly.

**Comment by keyspace** [comment]
> smashing the part in a slightly more targeted fashion.

The "targeting" is done with skills and tools.

**Comment by Xpyder** [comment]
> Removing a destroyed tire should not require a jack?

This is actually spurious as the issue in that example isn't removing the tire, but the fact that currently tires and tire mounts are completely integrated (they should be separate parts like swappable storage batteries)

In this example you're not removing a tire, you have essentially the entire tire attachment mechanism (including the brakes and axle) snapped off already, beyond repair (remember you have to replace the part you can't repair it)

**Comment by Xpyder** [comment]
> ... and it'd be nice to be able to remove them more easily.

I think this is really the key point in this request.  One thing we were discussing in another thread was the idea of having alternate tools for destructively removing a part.  Just because you can unscrew a seatbelt to remove it intact doesn't mean you shouldn't be able to cut it free.

**Comment by kevingranade** [comment]
On Jan 3, 2017 9:06 PM, "Xpyder" <notifications@github.com> wrote:

... and it'd be nice to be able to remove them more easily.

I think this is really the key point in this request. One thing we were
discussing in another thread was the idea of having alternate tools for
destructively removing a part. Just because you can unscrew a seatbelt to
remove it intact doesn't mean you shouldn't be able to cut it free.

This would harvest some "rope" (actually a woven fabric belt, whatever),
but not free up the spot the belt was mounted in, I'd expect it would leave
a "totally broken belt" mounted there, which would interfere with
installing something new there.
Similarly, smashing a wheel wouldn't leave that space in any shape to mount
a new wheel.

**Comment by Asmageddon** [comment]
I see where that idea is coming from, but I feel like it might end up being poorly-targeted complexity. I'd much rather see having steering axles and transmission/wiring as actual parts.

Also, since I don't want to open yet another issue and have your attention, I think that it would make a lot of sense to separate vehicle examining from the "examine" options, and (re)using it for the build menu as well(and making furniture "vehicles"), so that vehicles could be less broken, but still require effort to fix, since you'd now have to manually inspect all the parts, figure out what's broken, etc. I think that the mending approach is already in a way a solid step in the right direction, just really crappy in the state it's in right now.

**Comment by kevingranade** [comment]
> Similarly, smashing a wheel wouldn't leave that space in any shape to mount a new wheel.

> I'd much rather see having steering axles and transmission/wiring as actual parts.

These two concepts have almost nothing to do with each other.  Even if we have distinct axle/wheel parts, using a sledgehammer and a chisel to remove a wheel isn't going to leave the axle in any condition to install a new wheel.  The whole point of "rip parts off without appropriate tools" would be to harvest parts, the cost of doing it this way is breaking things.

> Also, since I don't want to open yet another issue and have your attention,

Open another issue, issues aren't about getting attention, they're about tracking issues so we don't lose track of them.

**Comment by Asmageddon** [comment]
True, they don't, hmm. What if you were to have "broken" parts stay there, grayed out, possibly transformed into something like "destroyed wheel", and dropping debris in the transition between "heavily damaged" and "grayed out"? In case of destroying frames, I honestly wouldn't mind vehicles being broken apart. It's sort of necessary if we're to have "merging" vehicles, which I think is a far simpler and every bit as useful of an idea as towing.

**Comment by Xpyder** [comment]
> but not free up the spot the belt was mounted in, I'd expect it would leave a "totally broken belt" mounted there, which would interfere with installing something new there.

You're right, I guess that doesn't really meet OP's request.

I guess what they're looking for is more like if you have the tools to install a particular part from scratch, but not the tools to remove the existing part how can you make space for the new part?

**Comment by WizardOfOoo** [comment]
Cars are not made off legos.  Vehicles parts nest inside each other and interconnect to things around them.  If you don't have the right tools, removing a given car part with brute force is going to break stuff around it.  Very similar to our current smashing system.

**Comment by Leland** [comment]
Discussion's been silent on this one for 4 months now, closing. Not why I'm closing, but it does look like the general consensus is that removing vehicle parts – even broken ones – should require some mechanical/technical know-how.
