### ISSUE TITLE
Pneumatic weapons should have a tank mod slot as a way of increasing the reload times and balancing it out.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19938]
Basically, without it they can't fire, and multiple tanks can be crafted, including hand-crank ones, and higher pressure ones. I think it'd help allow making pneumatic weapons strong again without creating major balance problems, in a way that would make sense.

**Comment by keyspace** [comment]
Previously discussed in #11166.

**Comment by Asmageddon** [comment]
Ah, crap. Personally I don't really mind there being no penalty that much. I feel like the penalties system right now is a bit wobbly overall. With how hard the stuff you really need to be on lookout against, high torso encumbrance is unavoidable, and the situation is identical with the head.

**Comment by Xpyder** [comment]
That discussion was heavily focused on UPS or gunpowder because it happened at a time when guns couldn't consume multiple ammo types simultaneously (I think that has been added iirc) 

Assuming we can now have them consume both ammo and charges, that would re-open this as a viable discussion

**Comment by Asmageddon** [comment]
Well, this is mostly an idea because I'd really like to have the ability to have pneumatic weapons pack a good punch, which right now they don't(but for some reason have automatic fire, go figure), as well as increase reload times, because they really need to be high.

**Comment by BorkBorkGoesTheCode** [comment]
Ammo and ups charges are supported but not two different ammo types; that is a future plan.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
