### ISSUE TITLE
Wooden barrel should not require a welder/goggles to craft

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#19948]
Current recipe calls for
-hammering 2
-wood sawing 2
-glare protection 2
-welder/makeshift welder/integrated toolset
-fire
And requires:
30 2x4s
6 scrap metal

Humans have been making wooden barrels for centuries without welders and I don't see any need to include the welder and goggles as necessary tools for crafting them.  Changing the recipe to require a forge (and forge tools) rather than a welder would be much better imo.

**Comment by RogueYun** [comment]
I just watched a cooper make a bucket on youtube... he seems to have made the bucket with some wood, an anvil, some scraps of metal, a blunt chisel, a hammer, and some rivets. He had some wood shaping tools but I don't think we have those in game. As far as I can tell you can probably cold forge a barrel if you know what you are doing. I'd say the recipe could be something like:

- Hammer 2
- Wood saw 2
- Anvil
- 30 2x4
- 6 scrap metal

I'll try to create a PR for this...

**Comment by Xpyder** [comment]
Wood shaping tools could fit into the game (like blacksmithing tools), but it's probably unecessary complexity.  If someone was interested I think it would basically be a hatchet, saw, chisel, planer, hand drill (simpler than you're probably imagining), flat knife, curved knife, and smoother.  About half of these are already implemented.

**Comment by keyspace** [comment]
Tend to agree with OP after @RogueYun's explanation in PR above.

For reference, the item started out in PR #4373 (commit 90823e178f0), somewhere before release 0.A. @Mattamue, care to chime in?..
