### ISSUE TITLE
Plural form of "battery" displayed as "batterys" in crafting menu

### ISSUE THREAD

**Issue by keyspace** [CleverRaven/Cataclysm-DDA#19944]
Most probably fallout from #19780. Ping @BrettDong

**Comment by BrettDong** [comment]
The solution might be display stacked items as `battery (125)` in the list of components required in the crafting menu. This doesn't only fix this issue but also keeps the consistency of the displaying style between the item menu (currently being `battery (500)`) and the crafting menu (inconsistent `500 batteries` before #19780 and currently problematic `500 batterys`).

**Comment by Fixer-007** [comment]
Still not fixed in newest git? https://i.imgur.com/lPv6xnL.png

**Comment by keyspace** [comment]
@Fixer-007 Shows correctly as `battery (100)`, not `batterys (100)`.

The latter is shown somewhere else still, though - I think advanced inventory upon item examination, in "charges", but don't remember ATM. Anyway, this would be a separate issue.

**Comment by Fixer-007** [comment]
@keyspace Actually look bottom right in messages window for batterys. Message was "picked up batterys (100) [r] and something above too.
