### ISSUE TITLE
Game should have door and seat variants that don't impose movement penalties.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19942]
Dunno about the seat, but I feel like it would make sense to have larger doors that, if open, don't slow movement through them.

P.S.: I am extremely sorry about the amount of issues I am creating, I've just been noting stuff down for the past two weeks and didn't want to leave it sitting there like I always do with everything. I hope it's not a huge bother.

**Comment by keyspace** [comment]
"No purpose" - they do: run away from a pack of shrieklings through a school bus.

Sliding doors _could_ get an `AISLE` flag (haven't tested).

> P.S.:

Be advised of #19197.

**Comment by Asmageddon** [comment]
Yeah. I would actually like to go through many of the minor issues, I just want to know what would or wouldn't get the go-ahead from the maintainer(s). And besides, I have so many issues. I've been in the middle of migrating vehicle parts to the requirements system for the past week. I did the nailable and screwdriver parts but ugh, getting this stupid weird anxiety even though I have the rest worked out and it's simple data entry from now on :(

**Comment by kevingranade** [comment]
So for example schoolbus doors wouldn't slow movment while moving through them, that sounds reasonable.
I'm not sure about a RL example of a easy-to-move-past seat, a jump seat in a military vehicle perhaps?  Not sure if that one is worth messing with since there's be weirdness about whether it's folded or not.

**Comment by Coolthulhu** [comment]
It doesn't really make sense to add fast-move doors if the only penalties they'd have over regular doors would be less hp, extra weight or slightly less common components.

We'd need something like another degree of aerodynamics (for tall vehicles one can stand in), so that it makes sense for obstructive (to movement, but not aerodynamics) doors to exist.

**Comment by kevingranade** [comment]
You can say the same about aisles, but there they are.  Not having a
drawback isn't a sufficient reason to not have certain vehicle types, like
busses.
However there are drawbacks we could add that would at least keep them from
dominating everything else, for instance presence of an aisle could prevent
installation of any other (non frame) parts in that square.

**Comment by Asmageddon** [comment]
Aerodynamics penalties are already stupidly brutal in the game right now, to a point where a 5 tile wide vehicle sits at barely above 50%, and in the current state of the system we don't need more.

**Comment by pisskop** [comment]
The aisles and floor trunks allow you to move onto a vehicle without penalty.  This also allows you to cheese acid attacks and fire damage.  And it allows you to theoretically make a large raiding vehicle with an external seat to drive away in.  The mobility inside a vehicle large enough to use it is appreciable.

**Comment by Asmageddon** [comment]
Yeah, but exposed exterior isn't very useful, and the seat still incurs the speed penalty. I'd really like to see bus/truck doors, and as for seat, maybe if it incurred extra penalty when sitting down to drive, rather than every time you move past it?

**Comment by Coolthulhu** [comment]
The issue as stated is just plain not true - floor trunks are perfectly usable with open vehicles.
Just because they aren't usable in every kind of vehicle doesn't mean they don't serve a purpose, which they do.

**Comment by kevingranade** [comment]
Rewrote the title to avoid hyperbole.

**Comment by Rivet-the-Zombie** [comment]
Here's an experiment we can all try at home:

Open the front doors of your car and then see how quickly you can crawl in one side and out the other. Is it the same speed as walking that same distance on open terrain?

**Comment by pisskop** [comment]
Foldable seats dont count as obstructing and can be installed onto aisles, correct?
And then you can put control on top of that, yes?

: O

**Comment by Asmageddon** [comment]
@Rivet-the-Zombie: This is why bus doors have been brought up, and why aisles were mentioned. If my car had just one seat and aisle around it, I could hop over it with minimum effort. And if the doors/ceiling were bus-height, I could move through it barely slowing down from a run(and I believe typical movement is more of a jog in C:DDA).

@pisskop I might be wrong, but I believe they do slow your movement down.

**Comment by kevingranade** [comment]
> Open the front doors of your car and then see how quickly you can crawl in one side and out the other. Is it the same speed as walking that same distance on open terrain?

Regular car doors should impose a movement penalty, the suggestion is for e.g. bus or rv doors that are more person-sized.

**Comment by Leland** [comment]
No movement in > 6 months, closing. Feel free to ping me here to reopen if there's a desire for continued discussion/development.
