### ISSUE TITLE
Walking through shallow water should get you wet.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19940]

**Comment by sethsimon** [comment]
I can't reproduce this. I got wet when I was wearing winter boots (they "won't let water through. Unless you jump in the river or something like that.") and stepped into shallow water by the river.  Did you have the Debug HVAC mutation? Are you talking about free water on the ground (ie what you get when you unload a container)?

**Comment by Asmageddon** [comment]
Nope, I was playing a version from around 3-4 weeks ago, and noticed it with a freshly spawned character on a swamp. It's not impossible that I was wearing wet-proof boots/pants, though. I should put more effort into reporting stuff.
