### ISSUE TITLE
Road making inconsistency

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#19953]
The road is connected on the map, but for some reason there is a cut between them with no buildings indicating they might be the end of the road (like a bunker/lab). So I believe this may be a bug,
![capture](https://cloud.githubusercontent.com/assets/24307650/21713759/86df26b6-d3c9-11e6-88b4-62eee5d677f5.PNG)
![capture2](https://cloud.githubusercontent.com/assets/24307650/21713763/8c151172-d3c9-11e6-9ec8-648219e91449.PNG)
I moved out of the way on the map and circled the two map tiles that show they are connected but really aren't.

**Comment by keyspace** [comment]
Looks more like two road terminations to me.

Guess: are they by chance on the border between two overmaps?.. What are their coordinates?

Could you upload a full savefile (ZIP)?

**Comment by codemime** [comment]
@keyspace All your guesses are correct. There's no need for the savefile: I could reproduce the bug.

**Comment by CoroNaut** [comment]
Every road termination comes with a building though, and unless they overwrote each other, i don't really see how this is possible. I don't know what you mean by two overmaps, The game is only on 1 version and so I didn't believe it could be from differing versions messing with mapgen.

**Comment by CoroNaut** [comment]
To further onto this issue, I found that the forest may be affected by the same chunk issue. The forest edge is at 179 and the plains edge is at 0 in the next chunk.
![capture](https://cloud.githubusercontent.com/assets/24307650/21755281/834267d0-d5df-11e6-919b-c2545ace30b3.PNG)

**Comment by keyspace** [comment]
Seen the latter for a while. Is it like this in 0.C?

**Comment by codemime** [comment]
@CoroNaut What you found is #7503.
