### ISSUE TITLE
Corpse spawned inside lab wall

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#19957]
------------------------>
![capture](https://cloud.githubusercontent.com/assets/24307650/21722017/cf454c4e-d3f8-11e6-8409-5191d74f75db.PNG)

**Comment by BrettDong** [comment]
Was it spawned at mapgen, or you killed it?

**Comment by Coolthulhu** [comment]
It should only be possible if the corpse was created before the wall.

**Comment by CoroNaut** [comment]
It's one of the normal corpse spawns, nothing on the body, just corpse. Even if I did kill a zombie, I couldn't place him in the wall like that.

**Comment by ZenZen2** [comment]
those are generated human corpses, not killed by the player. I have this problem too. Playing with Pk mod.

**Comment by Vidiveni** [comment]
Once I had the artifact that lets me see through walls. The lab walls had plenty of corpses in them, even deeper inside the concrete.

**Comment by codemime** [comment]
Those are scientists who knew too much.

**Comment by CoroNaut** [comment]
I had no mods that would have affected the generation of corpses at all if that helps.

**Comment by mrZalli** [comment]
Unsuccesful teleporter experiment subjects

**Comment by Leland** [comment]
Combined with #19957.

**Comment by ZenZen2** [comment]
@Leland i think you made a small error and took the wrong number, you combined this issue with the same issue's number, or do i miss somthing ?

**Comment by Leland** [comment]
@ZenZen2 fixed, thanks. That happens more often than I care to admit
