### ISSUE TITLE
Corpses are moved behind walls and other impassable terrain when there is too many items on the ground.

### ISSUE THREAD

**Issue by TheSadFox** [CleverRaven/Cataclysm-DDA#19969]
Been clearing out the mall by killing zombies in a door way. Once there was not enough space in the doorway, the corpses started being moved to nearby tiles, which is fine and intended i guess. What was not fine is that some corpses started being moved behind walls adjacent to where the fightning took place, resulting in making it unable for me to pulp them and forced me to fight them once more after i was done killing the horde.

**Comment by codemime** [comment]
I guess that's the consequence that was discussed in #18997.
