### ISSUE TITLE
Any thoughts on updating the mshock32 tileset?

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19960]
There's a neat little mod called "ottoplus" ( http://smf.cataclysmdda.com/index.php?topic=12029.30 ) which is pretty identical to the mshock32 tileset, but adds very high detail character sprites (individual mutations and gear are visible). Another forum member and I also creating a compatibility patch for mshock32 to add mobs from the PK's rebalancing mob.

These are all improvements which don't remove anything, so should be okay. But I wanted to inform folks and give a chance to lodge concerns or objections before I went ahead and changed it without warning. I wasn't sure how people would feel about mucking about in the tilesets.

**Comment by DangerNoodle** [comment]
Having someone to maintain the tile set would also be desirable, as it is one I prefer (I have found that the set @Chezzo made tends to be much less consistent in art style between the player, monsters, and terrain, despite being well-made).

**Comment by Regularitee** [comment]
To whom it may concern: I found out I need permission to upload files (push access) to upload the expanded "tiles.png". Can I get that, even if only for a single day?

**Comment by Regularitee** [comment]
Actually, I realized I could just upload files into comments. Can someone with the relevant powers use this to replace the "/gfx/Mshock32Modded/tiles.png"?

![tiles](https://cloud.githubusercontent.com/assets/8593513/21745399/3c38bd28-d4e8-11e6-8f6d-512bf12daa48.png)

**Comment by BorkBorkGoesTheCode** [comment]
That would revert #18380. Also, are you going to keep the boba fett helmet and fallout mininuke launcher?

**Comment by DangerNoodle** [comment]
Small problem. I would greatly prefer if the 24x24 version is also maintained.

**Comment by Regularitee** [comment]
@BorkBorkGoesTheCode I hate to ask, but would it be too much to ask you to splice your modifications onto that tileset image I just posted? I figure that you probably know off by heart what was modified so it'd be much faster, at least compared to me (whom isn't familiar with the changes) to compare each and every sprite between the two versions.

**Comment by kevingranade** [comment]
The work flow is you fork the repository, make changes in a branch, then
make a pull request based on that branch.  Help.github.com is a great
resource for detailed instructions.

**Comment by Regularitee** [comment]
@Kevingranade Yeah, sorry, I'm a bit new when it comes to github. Lots of experience with debugging, but never really had to use it. Thanks for the info though.

@DangerNoodle It's far easier to maintain one tileset than two (particularly if the second one requires re-sizing or re-drawing assets). From what I've seen of the tile_config.json, the MShock24 tileset is significantly smaller, so has been neglected for a while, and would require a *massive* amount of work to update. I'd recommend just using the MShock32 and using the zoom out feature in-game, which for most intents and purposes produces a result near identical to using MShock24.

But back on topic, I'd like to push my changes through until I can either get BorkBork's help or play spot-the-difference with the few thousand icons in the tileset to find all his modifications, since it doesn't seem prudent to hold up a fairly large compatibility patch (I think it doubled the size of the tileset_config.json) and 50+ new sprites for the sake of preserving three sprites plus minor tweaks. 

I do fully intend to merge the two and re-add borkbork's stuff, once I can figure out where and what all the changes were.

**Comment by kevingranade** [comment]
NP with being new, we all were at some point.

**Comment by DangerNoodle** [comment]
I still would prefer the 24 version to be updated as well. The view zoom option does not actually suffice. At default zoom in the 32 version you do not get much of a view beyond your immediate area, but zooming out even one step loses a lot of detail. The default zoom level with the 24x24 version is at the ideal ratio of detail to vision range in my opinion, at least when the window is set to approximate 800x600 resolution.

And at present, I cannot actually increase display height beyond around 45 or so without the window intruding into the start bar. This increases resolution to mimic 960x720, but still has minimal effect on visibility gained with this version of the tileset.
