### ISSUE TITLE
Lab spawn on its own?

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#19973]
I don't know if this is a new feature or not, I found this lab just sitting facing towards the river in this shot. (left of my character)
![capture](https://cloud.githubusercontent.com/assets/24307650/21746367/46bfe384-d510-11e6-9957-5415e867e3e4.PNG)

**Comment by hurston1** [comment]
I'm having the opposite problem. The last couple of games I've played, I haven't found a single lab, just about 25 bunkers. I'm not sure if that is just bad luck though.

**Comment by CoroNaut** [comment]
The rarity of labs has gone up it feels like, I know what you mean by finding a load more bunkers. :D

**Comment by Leland** [comment]
Closing in favor of #20386
