### ISSUE TITLE
Folding stock will not re-fold on unwield or stash.

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19971]
I've been told that the folding stock is supposed to unfold automatically when unwielded: It isn't doing so now. It starts folded, unfolds as it is wielded, then remains unfolded when unwielded.

**Comment by keyspace** [comment]
I'm confused. The `folding_stock` item I've tested has no fold/unfold, it just modifies the "parent" item's attributes, which remain the same whether the item is in inventory or wielded. Tested in recent git master (`0.C-20478-gce5e82508e`), with `dda` and `no_npc_food` mods only.

**Comment by BorkBorkGoesTheCode** [comment]
Then I've come across a possible bug: one of the folding stock-equipped firearms I've encountered gains size when wielded. I cannot replicate the behavior with a debug item.

**Comment by keyspace** [comment]
Is this a new game or?.. Not sure if/how, but a full save (ZIP) could be useful.

BTW, what's the origin of the item(s)?

**Comment by BorkBorkGoesTheCode** [comment]
I can't reproduce the bug using the latest experimentals, and I don't remember the provenance of the bugged rifle, so I'm closing this.
