### ISSUE TITLE
You can crash into hallucinations with a vehicle.

### ISSUE THREAD

**Issue by TheSadFox** [CleverRaven/Cataclysm-DDA#19970]
Been trying to back up my APC, before i managed to get it to move, a hallucination of a racoon appeared behind it. The APC wouldn't gain any speed untill the hallucination dissapeared due to ramming into it.

**Comment by codemime** [comment]
We have a bunch of hallucination-related issues. Maybe yet another label :)?

**Comment by keyspace** [comment]
`is_body_collision` section in `vehicle::part_collision()` doesn't check if the creature is a hallucination. Seems to fit logically here, but perhaps it can be done earlier? Maybe it is, but fails?..

@TheSadFox - which version are you running?

**Comment by TheSadFox** [comment]
Build 6106.
