### ISSUE TITLE
Phonebook suggestion

### ISSUE THREAD

**Issue by Cynthius** [CleverRaven/Cataclysm-DDA#19976]
The phonebook in-game mentions that it is a directory of phone numbers and addresses of the local area. Now, I know it also says it's "pretty useless" now, but the fact that it says it has addresses of local businesses suggests that it could logically be used to reveal locations on the map. I'm not sure how one would work this, whether it would be a single random tile revealed each read, but with limited uses, or what. It could cause problems with realism if the phonebook had too few uses, or didn't reveal very much.

I'm just putting this out there because it seems to be an inconsistency in logic. Whether this is fixed by making the phonebook a useable item or just changing the description to explain why you can't is up to you guys. What do you think?

**Comment by Totentag** [comment]
When you brought up the idea, I was mostly indifferent, but your "random tile" suggestion sounds like a good one. A reasonable sort of short-order balancing to keep it from being quite as great as survivor maps and other map-items. Perhaps to add onto the idea, a relatively brutal short-term morale hit thanks to how incredibly boring a "chapter" would be to read.

**Comment by sniperm13** [comment]
I actually 'read' the phone book in one game i had where i was having trouble finding maps (on .2 item spawn). I had the same logic where it 'might' reveal some tiles but had no effect instead. I think 'logically' it should as a real phone book even has a local streetmap in it.

**Comment by natsirt721** [comment]
I followed a similar line of thinking after reading a phone book in a game of mine, however consider this. Phonebooks don't have maps - it's a list of names, numbers, and addresses. Without prior knowledge of the area the addresses aren't going to mean jack.  There may be a handful of small maps in the businesses section but I doubt the ability of one to glean a significant amount of information from a phonebook.

**Comment by sniperm13** [comment]
True that. But as you say, the business section has a redimentary map, usually the yellow pages. Perhaps, not as efficient as an actual 'map' in game but having either random tile revelation or a small radii reveal would be appropriate, unless it's too much of a hassle to code in. As it stands, its only good for rolling papers for pot as is. XD

**Comment by Aivean** [comment]
Sometimes you have roads revealed on the map (like the way to refugee center). Could this mean that you know addresses along such roads? Maybe it will be sensible to reveal buildings near such roads when reading phonebook?

**Comment by natsirt721** [comment]
Seems like a fringe case to me.  I think the best solution would be that phonebooks reveal a single building and few adjacent road tiles, as well as incurring a morale penalty per read. Maybe the charges, penalty, and read time need tweaking, maybe not - for now they should be fine.  Presumably it would only reveal unknown locations, and probably only civil buildings (not bunkers, silos, outposts, sarcophagi, transformers, etc. - mines and sewage plants could go either way).  Only difficulty I see here is the location choosing algorithm, and even that is fairly straightforward: build a list of all buildings ajdacent to road tiles in a given radius, remove the known and military ones, and pick one of the remainders at random. If the list is empty, alert the play that "You already know all the addresses in here." or something and don't use a charge.

**Comment by Leland** [comment]
Alternatively, we could just remove the phonebook description's mention of it containing addresses.

**Comment by WizardOfOoo** [comment]
I could code this like a map.  Essentially it would be a one-time use item that reveals map details in circular radius based on the location of the reader.   All I would need to know is which buildings would be revealed.    

The city section would be useful, and the yellow pages might have a few small in advertising blocks.

I could see subways, hospitals, police, fire, and whoever would have the more expensive advertizing in the yellow pages.

**Comment by WizardOfOoo** [comment]
> Alternatively, we could just remove the phonebook description's mention of it containing addresses.

I think I am going to do just that.

**Comment by Luca-spopo** [comment]
I encountered this item for the first time today and even with the new description (which doesn't mention addresses), I was still expecting that reading the phone book would reward me in some way, and I was thinking it would reveal some map area (Crazy that we thought the same thing).

I think the words that led me into that direction of thought was the description mentioning "in the nearby area"
If you want the player not to think like this at all, then maybe we should also remove "in the nearby area" from the description
