### ISSUE TITLE
Cannot create maps with Chinese name

### ISSUE THREAD

**Issue by fk1995** [CleverRaven/Cataclysm-DDA#19994]
Using Win 10 64bit Tiled version, system language is Chinese.

After trying to create a map with any default map name(already translated in Chinese), the game prompts:
failed to write data into "./save/mapname(Chinese here)/gameoptions.json":opening file failed

**Comment by kevingranade** [comment]
This is why we used to base64 encode those filenames, I figured it would
eventually bite us :/

Please provide your OS and game versions.

**Comment by fk1995** [comment]
OS: Win 10 64bit
build:#6129, should be the newest

**Comment by BrettDong** [comment]
It's a UTF-8/GB18030 encoding issue. Both *nix(Linux, FreeBSD, macOS, eg.) and CDDA itself are using UTF-8 encoding for all characters, but only Windows is using GB18030 encoding for Chinese characters due to historical reasons.

**Comment by fk1995** [comment]
Seems to be a recently introduced bug.
I used to create maps with Chinese names and everything is fine. That build was about #5000 or so.

**Comment by BrettDong** [comment]
I'll fix this soon.

**Comment by keyspace** [comment]
@fk1995 Why'd you close this?..

**Comment by fk1995** [comment]
Seems on the newest version this issue still persists... @BrettDong

**Comment by BrettDong** [comment]
> Seems on the newest version this issue still persists...
>
Go to game options, turn on "Experimental path encoding conversion" in
debug tab.
