### ISSUE TITLE
Overmap map loading is progressive and gets very, very slow in big worlds, which causes problems.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19997]
In my current savegame, it can take up to 20 seconds the first time I open the map, and then 5-10s each time I scroll to the edge. Also, the search functionality only searches through loaded bits, which essentially negates its entire purpose, which is avoiding manually scrolling around.

It seems to me as if something needs fixing here.

**Comment by CoroNaut** [comment]
My map is 90GB currently and takes 10 seconds to initially load. I also noticed that when searching, it only searches in the 180-180 chunk that you searched in. I don't have any scroll issues even though my map is about 250 map tiles vertically.

**Comment by Asmageddon** [comment]
Do you have an SSD? For me it's 10s every time I scroll or worse.

**Comment by CoroNaut** [comment]
No, I don't have a SSD. I still want the initial map loading time to be fixed, it really shouldn't take the amount of time it does.

**Comment by Coolthulhu** [comment]
Need update on this one.
Overmap size dropped to 10% of the value at the time this issue was opened. Does the problem still persist?

**Comment by Asmageddon** [comment]
I don't assume it's possible to migrate an old world of mine to the new version and take advantage of said improvement?

**Comment by Coolthulhu** [comment]
Pretty sure it should work, but might have some hard errors (missing objects). Will certainly have harmless warnings that can be skipped.
I tested it when merging a 0.C migration PR.

One thing that is risky is missions: some older missions made after 0.C but before mission ID rework have the invalid enum IDs which will not load in current version.

**Comment by kevingranade** [comment]
This was potentially fixed, need confirmation of either a fix or that it still occurs.

**Comment by Leland** [comment]
@kevingranade can you link the PR # that may have fixed this? That way we can do a comparison before and after that hash.

**Comment by kevingranade** [comment]
I think this one: #20315

**Comment by Leland** [comment]
Cannot reproduce. Teleported to and revealed 20 different overmaps; opening the map is instant and scrolling across overmaps is snappy.

There _is_ a problem with searching, which I've created https://github.com/CleverRaven/Cataclysm-DDA/issues/21686 for.
