### ISSUE TITLE
Duplicate vehicle parts need a way to be differentiated

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#20002]
One of the biggest issues with the notion of swappable storage batteries is the lack of ability to identify which battery is which; you can't tell the difference between a full or empty one using the vehicle examination interface, so it becomes a game of trial-and-error. To a lesser extent this is also an issue with liquid tanks, though admittedly they're not supposed to be designed for swapping.

I think that -- if it's feasible in terms of code -- a good solution would be to have the parts list show the contents of each non-cargo container (power for batteries, liquids for tanks), like so:

>[frame]
(steel armor)
-vehicle tank (60L)-
---gasoline (15.7L)---

Or if that's not possible, at least assign parts some sort of identifier (like "Storage Battery A," "Storage Battery B," etc) so that they can be differentiated when removing parts.

**Comment by CoroNaut** [comment]
It is most definitely possible and should be relatively simple because the game already knows what batteries are available for installation when you select the part to install. This is a similar feature to #19735 where I talk about making a menu for exactly the same thing, but for wheels.
