### ISSUE TITLE
Irreparable armor repairable.

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#20011]
Dragon skin vests, which the description clearly states "... make it impossible to repair, only to replace," can be repaired. Arguably this issue extends to all kevlar-based armour, which is similarly impossible to restore the integrity of, once damaged (in reality, at least).

So, I'm not sure if someone wants to omit the "impossible to repair" part of the description, or if we should consider making all kevlar armour should be irreparable, or something.

**Comment by Rivet-the-Zombie** [comment]
I'd rather we buff the dragonskin and drop the part about it being impossible to repair. It's already pretty rare; there's no reason for it to suck too.

**Comment by Coolthulhu** [comment]
Maybe instead of having it impossible to repair, make it impossible to damage in combat and handwave it as some self-repairing material.

**Comment by DangerNoodle** [comment]
I think the text is referring to a defunct feature. For now the ideal solution would be remove the text mentioning this, and save any further balancing for afterward.

**Comment by keyspace** [comment]
Why not add a `NO_REPAIR` flag instead?..

Just tested, it works. 

Tangent: it's still presented in the "select item" menu when using a soldering iron, but properly gives "You cannot repair this type of item".

**Comment by Coolthulhu** [comment]
Damaged armors provide less protection, which makes rare, good, irreparable armors pointless (unless they had stupidly high stats).
For irreparable armors to work, they'd either need to be semi-common, good, but easy to damage (like budget steel items) or be unaffected by the protection decrease. Or both.

**Comment by Regularitee** [comment]
What would probably be better is if those MBR vests (or maybe all kevlar armor) could have swappable insert plates that take damage, and need to be replaced. That would be the best compromise between realism (irreparable nature of kevlar) and game balance (having an modern armor that's repairable).

Of course, creating something like that would probably be a pain to code and debug for, so I doubt we'll see anything like that.
