### ISSUE TITLE
Vehicle wheels don't crush flowers

### ISSUE THREAD

**Issue by keyspace** [CleverRaven/Cataclysm-DDA#20017]
This is convoluted, so bear with me.

1. f890a25e29710a34be53bb328b5002f0eb5cb2d0 (PR #10062) removed `move_cost_mod` from flowers. Probably not the origin, though, as the `if`-blob in `vehicle::part_collision()` (see (2)) has changed many times since then.
2. Move cost is checked [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/503c0ccd7a/src/vehicle.cpp#L4361) for vehicle collisions. If it's "default terrain" (i.e. 2), the code a few lines later (checking furniture with `TINY`) is not triggered. For game purposes, flowers are considered furniture on terrain, and they have `TINY`.
3. In addition, the return value of `part_with_feature(ret.part, VPFLAG_WHEEL)` is not used, resulting in the base part (frame) colliding with the flower if the code is modified to trigger anyway, e.g. by removing the move cost check described in (2).
4. I've done (3) for debug purposes only, and don't recommend it, since it could impact performance negatively: `vehicle::part_collision()` is called every turn, for every vehicle tile, and is only kept at bay by [an early exit](https://github.com/CleverRaven/Cataclysm-DDA/blob/503c0ccd7a/src/vehicle.cpp#L4384). This particular `if`-blob is kept at bay by the "default terrain" check.
5. The speed drop for a car-brand-car upon colliding with a flower is non-negligible, to the point of getting stuck if moving at, say, 3 km/h. (Wouldn't want a repetition of #19571.) Tested if still true on top of #19974, the issue can be alleviated (in some cases).

-----

EDIT: numbered list, add (5)
EDIT: removed in-text EDIT notes to improve readability

**Comment by keyspace** [comment]
Best idea I've come up with so far is splitting that `if`-blob into even more `else if`s that would check various flags (wheel, track, protrusion...), and some lousy code repetition. :/

**Comment by Coolthulhu** [comment]
Could be sped up by creating a new cached (enum, not just string) flag for all the special vehicle checks, then checking that before anything else related to terrain.
That flag would then be assigned in finalization based on all the vehicle flags that need to be handled and move cost (that is, if it can affect vehicle, it gets the flag).

This would be faster than what we have now in vast majority of cases.

**Comment by keyspace** [comment]
Sounds reasonable for a rewrite. Was thinking of addressing this earlier, though. There is a limit, of course, how long this can be delayed, but I was thinking _after_ a stable release.

Note: it might seem backward to check for flower collisions before zombie/tree ones, but I have a hunch the former are much more common than the latter during normal play.

**Comment by Coolthulhu** [comment]
Don't wait for stable with minor fixes (anything less than rework or a totally new feature). There is still no set date and there is a large backlog of critical issues that need to be fixed before stable.

**Comment by keyspace** [comment]
Whipped up a naive implementation (see above, PR demo to my own repo), just splitting the if-clause as mentioned in comment 2. Can submit a [WIP] PR here, but feel that some "normal" game testing is warranted even before that. I just rode around a field a little so far - no mines, no creatures, etc.

Reasonably sure I don't have enough skill to do a caching implementation.

**Comment by CoroNaut** [comment]
I caution about using too many if-else combos as it can really slow down performance.

**Comment by TheWebfrog** [comment]
Im not completely sure, but could any of this be affected by future vehicle reworks, similar to the movement calculation and simulation made recently?

**Comment by keyspace** [comment]
Quite possible. Vehicle collisions are finicky - many inputs to the calculation.

**Comment by Leland** [comment]
#26792 means the flowers won't be collided with at all anymore. Having them be crushed is an even better proposition, but this issue hasn't seen real action in > 1 year, so closing. If there's interest in reviving development, please ping me to reopen :)
