### ISSUE TITLE
Get rid of material restrictions for inscribing

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#20025]
Inscribing allows you to rename items and equipment which is incredibly helpful when you're dealing with a ton of different equipment. For example, I typically rename equipment to confer their specific context. I will add an [*] to equipment I always wear, and a [w] to warm layers, and [X] to unusually specific equipment (e.g. hazmat suits). I also group different medications so they're near each other. E.g. [P1] for aspirin, [P2] for codeine, etc in order to remember what I have and prioritize accordingly.

This confers no in-game benefits whatsoever but it does significantly improve usability by allowing easier browsing of usually long item lists. However, the only way to inscribe on anything "soft" is to be lucky enough to find either a permanent marker or coal to make a survival marker. I'm a year into my current character and have not found either thanks to RNGesus.

The restriction on materials for inscribing is completely arbitrary, not fun, and is not even realistic. Pens and markers are one of the most abundant items in the world but that isn't reflected in the game. Even so, a sharp knife should be be enough to inscribe on any clothing that is leather and above. There's no gameplay reason to gate a quality-of-life UI improvement behind the RNG.

It looks like the change is a simple one under class inscribe_actor. My apologies but I have no idea how to make formal requests on changes (I'm not a programmer).
https://github.com/CleverRaven/Cataclysm-DDA/blob/3b32c42607e514d8bc6461a39a9a9dcbdf584af8/src/iuse_actor.h

**Comment by HotSake** [comment]
Agree, this is pure QoL. The inscription doesn't need to be treated as having any physical action. It can be thought of as the survivor making a mental note: this is my favorite gun, this is my winter coat, etc.

If markers have no other use, they can also be removed to clean up the item list.

**Comment by kevingranade** [comment]
Sounds good, but I'd prefer to change it to "rename" in that case and
completely drop the "inscription" rigamarole.

Inscription was added as a joke that turned out to be useful.

**Comment by Coolthulhu** [comment]
Would be very useful if we could have Angband-style inscriptions for things like throwing and bows.

**Comment by kevingranade** [comment]
On Jan 13, 2017 6:43 PM, "Coolthulhu" <notifications@github.com> wrote:

Would be very useful if we could have Angband-style inscriptions for things
like throwing and bows.

Why would we use angband style inscriptions when we can set actual flags on
the objects?  Stashing data in the name is gross.
Maybe you just mean the functionality instead of actually storing it in the
name?  In that case yea, that kind of thing is really convinient.

**Comment by bouchacha** [comment]
So no one disagrees? What's the next step for implementing this? To my layman eyes the code change seems very simple but I don't want to break anything. I suggest retaining the tie between item use and 'inscribe' and getting rid of survival markers and permanent markers since you can just use knives, tailor kit, and other sharp implements. That seems to be the easiest implementation.

**Comment by HotSake** [comment]
I agree with @kevingranade that we should drop the "inscription" conceit and tool requirements entirely. Just call it "rename", and let it happen freely. Implementing Angband style inscription functionality should be put off to a separate change.

**Comment by bouchacha** [comment]
So would it be an action under the 'a' menu that you can always make or a new keybinding entirely?

**Comment by HotSake** [comment]
I guess I envision it as another action in whatever you call that menu when you select an item from your inventory, and it displays the details and interaction options.

**Comment by bouchacha** [comment]
I think that's a lovely solution

**Comment by kevingranade** [comment]
Yes, transplanting some of the code from the inscribe I use to the item
interaction menu sounds great.

I'd prefer to leave the associated items around though, at the very least
remove them in a separate PR.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
