### ISSUE TITLE
Jackhammer destroys wall on the turn used instead of after time elapsed

### ISSUE THREAD

**Issue by HotSake** [CleverRaven/Cataclysm-DDA#20023]
Just like the old problem with winches, if you jackhammer a wall down, the wall opens immediately, but the player is stuck for multiple turns while the action "happens". Probably has the same fix - make it an activity (whatever that means, not familiar with the code).

I noticed it on the bottom floor of a lab, when I used a jackhammer to open a 1x1 cell containing a demon I wanted to kill, and it got multiple turns worth of attacks on me before I regained control of my character. I submit that the actual crumbling of the wall is the result of progressive damage from the jackhammer and should definitely be the culmination of the action.

**Comment by ReservoirHeadcrab** [comment]
Also happens with hacksaws and cutting metal bars.

**Comment by Regularitee** [comment]
And I believe the same issue with hacking robots via control laptop. They seem to stop hitting you the moment you start the hack, at least.

**Comment by TheWebfrog** [comment]
> `Regularitee "I believe the same issue with hacking robots via control laptop ... They seem to stop hitting you ... the moment you start the hack.

Yeah, I'm not computer expert ( well kinda ) but when executing code, the absolute last thing that happens **IS`** the execution of the code. so yeah, in a sense it should be in the exact same group as the winch and im guess now the cutting and jackhammering bug(s).

Other times that this happens are often occuring when the action is submitted from the construction menu, or a pre-determined dialouge. so it may be worthy to seek and destroy these occurances,

**Comment by Headjack** [comment]
#8231

**Comment by Leland** [comment]
From #8231:

> Last I checked, jackhammering took one turn, if that. By rights it ought to be a `long_action`

**Comment by Night-Pryanik** [comment]
Closed by #22911.
