### ISSUE TITLE
[Bug] Enemies have LOS to player through player's vehicle security camera

### ISSUE THREAD

**Issue by HotSake** [CleverRaven/Cataclysm-DDA#20024]
At least in one instance it certainly behaved that way. I installed camera controls on the space containing the bed in the corner of my RV so that I could see what was around the vehicle as I was going to sleep or waking up. The surrounding frames all had opaque boards, an opaque door, or a door with the curtains drawn. There was no external LOS to the bed. I was awoken to multiple messages in the log about a camera drone taking my picture. It had apparently spotted me and snapped my pic while I was asleep multiple times, leading multiple police drones to converge on the vehicle and start attacking it. After removing the camera controls, it never happened again.

I'll test different scenarios tomorrow to confirm, but some kind of reciprocal LOS through the camera is the only explanation I can see.

edit: Just remembered: after installing cameras on the rear, but not installing any camera controls, I was able to back my RV up to a roadblock turret without getting attacked, presumably because it couldn't see me. I was then able to climb into the back to get in range to use a control laptop on it safely. The second time I tried that trick, I had installed camera controls in the driver's seat, and the turret opened fire as soon as I got in range, despite having all opaque vehicle parts between me and it. Supports the reciprocal LOS through cameras idea.

**Comment by Zireael07** [comment]
I believe the LOS is indeed reciprocal in the whole game (if you can see it, it can see you) and I believe there is already an issue for that.

Can anyone help me find the original issue?

**Comment by ZenZen2** [comment]
i have to confirm this bug, once i step to the tile where my camera controls are, the zombies outside start to react and attack the car.
