### ISSUE TITLE
Marloss bliss morale buff seems too strong.

### ISSUE THREAD

**Issue by TheSadFox** [CleverRaven/Cataclysm-DDA#20036]
![marloss](https://cloud.githubusercontent.com/assets/10717398/21982798/5c70d316-dbee-11e6-9313-a3074e5d0f65.png)
![marloss2](https://cloud.githubusercontent.com/assets/10717398/21982886/aedb1670-dbee-11e6-908a-4df6835a12da.png)

Berries already serve as infinite food source, the morale buff from just one portion of berries is also very strong. Being able to stack the buff so high just seems very wrong, given that (at least in the 16 days long playthrough of my berry abusing character) the disadvantages of abusing berries are extremely minor, and the buff can be kept active almost indefinitely.

**Comment by Aivean** [comment]
[Another way to get 1000+ morale](https://www.reddit.com/r/cataclysmdda/comments/5o2ccr/i_have_ascended/).

**Comment by Leland** [comment]
Closing due to lack of recent discussion. Feel free to ping me here to reopen if there's interest in continued discussion/development.
