### ISSUE TITLE
[SDL] The menu disappears after mouse moved (regression from #19961)

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#20037]
After a long and painful bisect process, I confirmed the problem was introduced in #19961 . 

1. Open a menu, eg. debug menu, or view an item description through (i) and hit an item letter
2. Move your mouse
3. The menu disappears

The problem is pretty annoying. Hope to have a fix soon.

**Comment by BrettDong** [comment]
Pinging @BevapDin

**Comment by keyspace** [comment]
OT: was the "long and painful" part due to many revert commits? If so, can `git bisect skip`, or check two before/after commits for good/bad/new/old.
