### ISSUE TITLE
Companion NPCs jump off ledges to their deaths

### ISSUE THREAD

**Issue by Taberone** [CleverRaven/Cataclysm-DDA#20035]
0.C-20697-gd1a5eda9cb (tiles)
Build 6148
Experimental Z-Levels disabled, but still playing with Z-level buildings (Ex. 2-story Motels). Not sure if this happens with Experimental Z-Levels enabled.

Another issues that has been here for a while. Finally remembered that it existed after I foolishly visited the upper floors of a 2-story motel and saw all my work building up a team full of badasses go to waste.

<a href="http://imgur.com/Gd7avn1"><img src="http://i.imgur.com/Gd7avn1.png" title="source: imgur.com" /></a>.

Go up a Z-level and find a tight space with a ledge nearby, like the upper floors of a 2-story motel. Bring several companion NPCs with you, or just spawn several NPCs and give yourself Debug Mind Control through the mutation menu. Walk around for a little bit and your NPCs will start falling to their deaths.

<a href="http://imgur.com/FIhfIFh"><img src="http://i.imgur.com/FIhfIFh.png" title="source: imgur.com" /></a>

This is what the upper floor of the 2-story motel looks like. You'll need a minimum of three NPCs for them to start dying. If you bring a single NPC or two with you, they won't fall to their deaths.

<a href="http://imgur.com/AVdrBEm"><img src="http://i.imgur.com/AVdrBEm.png" title="source: imgur.com" /></a>
(Pictured above: formation)

Another interesting thing to note (and a possible explanation for this) is that NPCs tend to follow you in formation. It seems like they insist on walking in this formation even when there is a ledge in the way.

**Comment by Coolthulhu** [comment]
They might be pushing each other off. The formation is implicit: they arrange into it by pushing each other until every single one of them is within set distance from the player.

Could be helped by disallowing NPCs getting pushed into dangerous (ie. not funnels, cots etc.) traps. This "pushing" is actually voluntary movement and so should not move NPCs into traps.

**Comment by CoroNaut** [comment]
Your companions are cutthroat. They look to you and say sorry but then they turn around and snicker... "They deserved it." lol
