### ISSUE TITLE
tools/json_tools update to Python 3.3+: should compatibility with Python 2 remain?

### ISSUE THREAD

**Issue by keyspace** [CleverRaven/Cataclysm-DDA#20045]
Certain tropes suggest Python 2 is assumed, and it didn't work for me with Python 3.6, so revised - mostly `util.py`, which is included in the "main" scripts.

It's sitting in a stash ATM, would like to submit a PR, but wanted to make sure Python 2 backwards compatibility is _really_ necessary, and why if so. Changes would be cleaner if not.

Note: current has a commit from PR #9087 as [latest change for most files](https://github.com/CleverRaven/Cataclysm-DDA/tree/3033633b5de586aa8ad1e68a53a85dc252226c77/tools/json_tools).

**Comment by kevingranade** [comment]
This sort of thing requires a survey of systems the scripts need to run on, if they all have python 3.3+ we can break backwards compatibility, but that's tricky to determine.  The safest thing to so is to maintain compat.

**Comment by keyspace** [comment]
I won't be able to follow-up on this, so closing.

Just in case, I've put the mentioned stash as-is in [a commit](https://github.com/keyspace/Cataclysm-DDA/commit/62f0156b88e7c8dcb5856b201d01e815b13c7357) and pushed to [this branch, `json-tools-python-2-3-compat`](https://github.com/keyspace/Cataclysm-DDA/tree/json-tools-python-2-3-compat).
