### ISSUE TITLE
Should we be able to connect a jumper cable to a car battery on the floor?

### ISSUE THREAD

**Issue by Johnblubber** [CleverRaven/Cataclysm-DDA#20043]
It seems logical to be able to but when you try it. The game only allows you to attach the jumper cable to a vehicle

**Comment by Asmageddon** [comment]
It would definitely be a nice thing to have,

**Comment by Coolthulhu** [comment]
That would be a big technical problem. We can't properly refer to items for longer than one "instant action". Hacks like inventory positions are enough for items carried by the player and used for long actions, but it would be pretty annoying in case of map items.

The cable would disconnect if the battery was moved, an item was moved from under the battery or anything else happened to the battery.
Also, it would need to be done carefully to prevent cable duplication.

It's doable, but not all that easy.

**Comment by Leland** [comment]
Closing due to lack of discussion.
