### ISSUE TITLE
Installed solar panels repairable, but not while in inventory

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#20046]
Solar panels cannot be repaired as an inventory item, but can be repaired while installed.

Swappable storage batteries cannot be repaired while installed, but can be repaired as an inventory item.

**Comment by keyspace** [comment]
Batteries in particular are covered in #19451.

**Comment by CoroNaut** [comment]
I also believe they should all be able to be repaired, it was changed from being able to be repaired not long ago. 

It is intended that in the long run, batteries won't be repairable at all. (don't quote me on that, I remember seeing it but can't find it)

**Comment by bdgackle** [comment]
If we can craft lead acid batteries then we should be able to repair them.  This is 19th century technology.

Faiure modes of a lead-acid car battery are cracking of the plastic case, subsequent loss of electrolyte, sulfur migration from electrolyte to plates, shorting between plates, and disintegration of plates as they change to various lead salts and oxides.

Sealing up a plastic case is a no-brainer.  Electrolyte replacement is a common home repair.  Finding shorted plates and fixing would be easy with a hacksaw and patience, plus something hot to reseal the plastic case.  You could presumably distill the sulfuric acid back from contaminated electrolyte with a glass or stainless container and a rubber hose.

Recovery the various oxides and smelting them is also backyard chemistry.  Melting down the lead plates and oxides, followed by adding something like sawdust as a sacrificial oxidant should get you back to pure lead using campfire temperatures.

Safety note: NEVER try to melt down actual car batteries in real life.  The combination of calcium and sulfuric acid at high temperatures can catalyze the formation of arsine and stibine from the antimony and arsenic used to harden the plates.  These are WWII era nerve agents, and can kill you at very low concentrations.  Probability is low enough to ignore for game purposes, but too dangerous where real human safety is a factor (for context, I melt down a lot of lead for various hobbies, and have done fun things with concentrated sulfuric acid.  I am not chemical-phobic.  I still won't mess with car batteries at high temps).  I know that is off-topic, but I don't want to contribute to anyone's death...

**Comment by Leland** [comment]
#19451 is the issue for repairable batteries, this issue will be regarding the solar panel part of OP's description

**Comment by kevingranade** [comment]
Is this still the case?

**Comment by 81Denton** [comment]
@kevingranade This is still the case on build 9084. The solar panel item is designated as not repairable, but it can be repaired once installed into a vehicle.
