### ISSUE TITLE
Limited use of charges in pseudo-item furniture

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#20049]
Pseudo-item furniture that are loaded with charges (rock forge, smoking rack etc.) can only use as many charges as the item they inherit from. 

e.g. you have a smoking rack, which inherits from the charcoal smoker. Charcoal smokers have a maximum of 200 charges, but your rack can hold much more. You place 300 charcoal in your rack and attempt to batch 20x smoked meat (requiring 300 charges), but can only do 13x (195 charges)

**Comment by Asmageddon** [comment]
Ah, I noticed the same with FOODCO dehydrator, and I think that the vehicle kitchen's hotplate suffers from the same problem, although not sure.

**Comment by Coolthulhu** [comment]
Could be worked around by creating new items for vehicle tools and furniture.
They could even be just copies of the usual items, with new names and capacities.

It would have the additional advantage of clearly referring to them when selecting tools. So no "hotplate (vehicle)", but "kitchen unit (vehicle)".

**Comment by Asmageddon** [comment]
Do vehicle crafting things like this even use its battery, out of curiosity? How do they exactly work?

**Comment by Coolthulhu** [comment]
* Spawn tool
* Drain as much battery power from vehicle as you need to fill the tool (or less, if it isn't available)
* Charge the tool with the drained power
* Do what you need with the tool
* Return remaining power to vehicle

**Comment by sick-trigger** [comment]
why is the player limited by the max number of charges of a tool in the first place? Are there any other instances where a tool can be loaded past its limit?

**Comment by Coolthulhu** [comment]
> why is the player limited by the max number of charges of a tool in the first place?

The loading function prevents overloading. Tools don't support directly drawing power from vehicle.

**Comment by WizardOfOoo** [comment]
Verified.

**Comment by WizardOfOoo** [comment]
Closed via 20746
