### ISSUE TITLE
After world loads the map changes

### ISSUE THREAD

**Issue by SnakeWings** [CleverRaven/Cataclysm-DDA#20042]
Hello

When i was loading my game several bugs popped out (skipped by pressing space) then game loaded but generated completly new other lab, different from that where i saved. I quitted the game with Alt+F4 and every time I was trying to load the game new labs were generated again and again.

Version: 0.C-20486-g3d469f9

P.S. Save file: https://drive.google.com/open?id=0Bzsom_IxdixkRDhOSExtUHZoek0

![image](https://cloud.githubusercontent.com/assets/25185514/22040405/c4ec4102-dd13-11e6-9a58-4f1b4c23745e.png)

![image](https://cloud.githubusercontent.com/assets/25185514/22040303/7be4545e-dd13-11e6-99b1-d82b0b998055.png)

**Comment by CoroNaut** [comment]
If you go into that map file and can find the symbol that was found, you can probably replace it with the correct information. If the map file doesn't look like a newly generated one then it may be corrupt. The lab would generate over and over if you keep closing the program without saving because it goes through the same error process every time. Perhaps saving it will remove these errors.

**Comment by keyspace** [comment]
Did you update from a previous version?

If so, which one?

**Comment by BrettDong** [comment]
Could you please upload `./save/Sawgrass/maps/1.0.0/58.4.0.map`?

**Comment by SnakeWings** [comment]
@keyspace Actually i didn't, at least manually

**Comment by SnakeWings** [comment]
@BrettDong https://drive.google.com/open?id=0Bzsom_IxdixkRDhOSExtUHZoek0

**Comment by mutability** [comment]
`58.4.0.map` is nothing but NUL characters; this is probably filesystem corruption; you have lost that submap irretrievably.

**Comment by mutability** [comment]
o.0.0 is truncated with some trailing NULs, looks like more filesystem corruption there.

I would guess you had a power failure or a crash mid-save at some point.

**Comment by Leland** [comment]
Closing, because it would appear this is a computer-dependent issue. If OP or anyone else runs into this issue again, please comment here or make a new issue – this is a pretty crazy result.
