### ISSUE TITLE
Clothing

### ISSUE THREAD

**Issue by Rajnice** [CleverRaven/Cataclysm-DDA#20059]
hi. sorry for oftop but i know what in game has clothing big and normal size. how about small? it's strange kill zombie-kid and get clothing how zombie-halk's, huh. will be in game small size or will remain as is it?

**Comment by DaliTimelord** [comment]
What I know is that clothing kits, like the sewing kit and the tailor's kit, are able to improve clothes by having them fit you. That being said, I don't believe the game makes a difference in clothing size other than the fact that there is specific XL versions of clothes that allow mutations. It's either clothing fits you or it does not, with the only difference being encumbrance. 

Besides that, I have no idea what you're saying.

**Comment by Rajnice** [comment]
S or L. Not XL and large

**Comment by Leland** [comment]
Closing due to lack of information.
