### ISSUE TITLE
Would a supernatural themed dungeon get merged into the vanilla game?

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#20050]
I would like to work on a more supernaturally themed dungeon, namely a ruined structure inside a cavern, comparable in size to the vault. A  gigantic version of our current temples, basically.

I planned to have it inhabited by shadow type enemies. With rewards being several randomly generated artifacts, same as our current temples or maybe some vaguely "magical" items and consumables.

I just wanted to ask if a dungeon like this fit the rest of the game? and if yes: What are the limits to extra-dimensional "magic" for the vanilla game?

**Comment by DangerNoodle** [comment]
Desirable, but see Arcana and Magical Items mod. Mutual hostility between the mod author and @mugling, along with insufficient people willing and able to continue maintenance, led to the mod being obsoleted. Anything too anomalous might be declared desirable only in mods, and become subject to the same difficulty of maintenance.

However, the mod author has retained the mod and is continuing development to the best of their ability, in their repository. https://github.com/chaosvolt/cdda-arcana-mod

**Comment by kevingranade** [comment]
A good rule of thumb for inclusion of magical items in vanilla is whether
they are part of a magic system the player interacts with.  As long as the
individual magic items stand alone, it's most likely fine.
I don't see any problems with the rest of what you described about the
dungeon either.

**Comment by CoroNaut** [comment]
I would love more dungeons in general, especially the spooky ones! Perhaps this could enable the portals to actually spawn entities and for there to be some way to get rid of them.

**Comment by John-Candlebury** [comment]
Alright! Thanks for the answer Kevin! 
Will start working on it.

--
I'll close this issue and reopen if I have more questions or need feedback for the "magical" stuff.

**Comment by keyspace** [comment]
Note that some recent improvements to map JSON don't have many examples yet. E.g., the change in PR #19793 allows defining `place_loot` spawn tiles by referencing a tile's symbol, just as `place_items`. The difference between the two is described in issue #19941.

Push a work branch to your own repo early, and mention @keyspace there if you need an example.
