### ISSUE TITLE
Trading NPCs a debug cube results in them attempting to path onto your curent tile

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#20079]
Is this intentional?

its a debug cube of allseeing, but i wonder if it wouldnt happen with all seeing artifacts

**Comment by kevingranade** [comment]
Not intentional, but also an incredibly obscure bug, I'm not at all sure
it's worth overhauling NPC pathfinding just to support the off chance that
they have clairvoyance.

**Comment by Coolthulhu** [comment]
The bug itself is incredibly minor, true, but it may be a symptom of something worse.

What do you mean "attempting to path onto your curent tile"? Trying to get where you stand and whining at you because you are there?

**Comment by pisskop** [comment]
yes.  constantly pathing to your tile, even as you move.

your position is their target waypoint

**Comment by kevingranade** [comment]
Oh, for this specific case you can probably just remove that last square
from the path when it's generated.

**Comment by Leland** [comment]
@pisskop this _is_ a genuine bug, but it's also insanely minor and obscure. I'm closing this for now unless you have objections.
