### ISSUE TITLE
Quests incompletable if the questgiver joins player after accepting

### ISSUE THREAD

**Issue by Cynthius** [CleverRaven/Cataclysm-DDA#20089]
So, I had an NPC who asked for an inhaler. After accepting the quest, I asked him to join me, and he agreed, but once I found an inhaler for him, there was no option to complete the quest. I tried dismissing him as a follower afterwards, and then turning in the quest, but he no longer seemed to have the quest for me, though it was still active in my quest log. At the end of the quest's allotted time, he spontaneously died while following me.

**Comment by Leland** [comment]
I've seen both sides of this: followers who accept completed quests as well as followers who don't, as you described. I have a hunch that the behavior depends on the specific quest given.

The most recent instance that succeeded despite the quest giver joining my party was the software download one.

**Comment by Asmageddon** [comment]
I've had the same happen - had to remove the quest from one of the files in the save folder manually to prevent the follower's death.

**Comment by mlangsdorf** [comment]
I tried reproducing this with the patient transcripts, inhaler, and software missions, and all of them completed just fine after the NPC joined my group.

I'm closing this.  Someone can reopen it with verifiable methods to reproduce it.
