### ISSUE TITLE
Debugmsgs on game start do not show, but still require a space/i to clear

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20107]
If a mod causes a debugmsg on load, it will not show the message, just keep the old window ("loading", "generating world" etc.).

**Comment by BorkBorkGoesTheCode** [comment]
I am experiencing the same in a legacy game, with one message occurring after rl_classes. #20061

**Comment by hardestniggasinthehood** [comment]
For me it happens when I load an existing save. It loads for a little bit and then freezes on the finalizing stage, and I have to press "i" to get it running again..

**Comment by BorkBorkGoesTheCode** [comment]
@Coolthulhu This doesn't happen if I start a game in a world with only default mods.

**Comment by Coolthulhu** [comment]
Updated title and OP message.

**Comment by keyspace** [comment]
Don't have a Windows machine, but maybe 29eda1e (part of PR #19951)?

Do they at least blink after `space`/`i`?..

Indeed seems a duplicate of #20061.

Have also noticed [on forums](http://smf.cataclysmdda.com/index.php?topic=14017.0).

**Comment by Leland** [comment]
Closing in favor of #20061
