### ISSUE TITLE
PDA still showing as missing

### ISSUE THREAD

**Issue by TheWebfrog** [CleverRaven/Cataclysm-DDA#20114]
Title, the recently removed PDA item still shows as missing in world gen.

**Comment by ZhilkinSerg** [comment]
Do you have any mods enabled? I cannot reproduce it with 6171 and vanilla dda.

**Comment by TheWebfrog** [comment]
Only the vehicle addition mods, but if you cannot reproduce it then I guess it's fixed :)

**Comment by Night-Pryanik** [comment]
Should be closed?

**Comment by Cyrano7** [comment]
If this can't be reproduced then it should be closed.
