### ISSUE TITLE
Two Containers, One Problem

### ISSUE THREAD

**Issue by TheWebfrog** [CleverRaven/Cataclysm-DDA#20115]

**Comment by Zireael07** [comment]
You forgot to mention what the problem is.

**Comment by DangerNoodle** [comment]
With no context to go on, I can only assume the problem is that the original poster attempted to re-enact "Two Girls, One Cup" in post-apocalyptic format, and got it backwards.

**Comment by ZhilkinSerg** [comment]
My guess is:

Player has difficulties when having two containers of the same type with same contents and trying to unload contents of one of the containers to another container (basically merging contents into one container).

**Comment by kevingranade** [comment]
Feel free to reopen with a problem description.
