### ISSUE TITLE
Natural Time-Telling underground

### ISSUE THREAD

**Issue by Gaunah** [CleverRaven/Cataclysm-DDA#20117]
ATM the natural time-telling also works underground. Which I think should not be possible.

Taken from the Wiki:
"As long as the character can see the sky (e.g. is not underground) they will see a small sundial pictograph in their UI display. This picture will change throughout the day and night and corresponds to the hour of the day. It is impossible to tell the exact time without a device. If the character is underground (e.g. in a basement, etc.) the sundial will be replaced with the grey-tinted message "underground." This limits natural time telling to above-ground use."

to reproduce: start Prison Break scenario

**Comment by Zireael07** [comment]
Wiki is outdated. Also does prison count as underground? I thought it was only caves...

**Comment by Gaunah** [comment]
I see the underground tag there.
I thought, even if the wiki is outdated, that time-telling via sun shouldn't be possible underground/caves.
