### ISSUE TITLE
Vehicle collisions overview, thoughts on rework, and APC-vs-shrubbery post-mortem

### ISSUE THREAD

**Issue by keyspace** [CleverRaven/Cataclysm-DDA#20111]
The recent (reverted) vehicle propulsion overhaul has uncovered some serious issues in the current vehicle collision implementation. Prominently shown in #19571 and #19854 - slow-moving vehicles, even if massive, may fail to overcome furniture obstacles (such as shrubs and flowers).

The details on current implementation and cause for the above are presented in preamble to PR #19974 (just closed - no longer a hotfix for anything, after VPO revert).

Several issues can be discerned from there. Please read to understand the scale! In short:

* loops throughout, and relying on early exits;
* scalars instead of vectors, and confused terminology;
* geometric progression down-scaling.

Also has links to relevant code parts (at commit 32ebedc26456275e98c6c2db5621dea6d58c5882).

Collision code is fragile due to the number of inputs to the calculation - and this cannot be worked around. Collisions are hard (except when they're elastic).

-----

Re-implementing this would be a massive undertaking. Whether attempted or not, we _must_ start with automated tests, to gauge the current state. Manual testing, like done in PR #19974 ([here](https://github.com/CleverRaven/Cataclysm-DDA/pull/19974#issuecomment-272746901)), is insufficient, error-prone, and near-impossible to verify. If nothing else, that one's food for thought.

Some refactoring might be needed regardless, to clearly separate what's currently taken into account. See #20017 for an example of something that "should" be, but isn't.

-----

As discussed throughout the issue tracker recently, re-implementation attempts, if undertaken, are well-suited for a feature branch, and shouldn't be rushed.

Already mentioned:

* [CR] [WIP] vehicle: more iterations for part collision loop (hotfix for APC-vs-shrubbery) #19974
* Greenery a little too durable? #19571
* Vehicle mass is apparently ignored #19854
* Vehicle wheels don't crush flowers #20017

Should definitely consider:

* Hulk car shoving. #1003
* New car part: tow hitch #3699
* Allow vehicles to carry other vehicles #11668

Tangentially related:

* Rework vehicle out-of-control behavior. #1807
* How can we fix vehicle tile teleporation but keep vehicle rotation pretty? #11857
* Weird skidding behaviors (intended?) #13307

-----

Proposed tags:

* Suggestion (Discuss)
* Long-term
* Mechanics Change
* Vehicle
* Collisions?

**Comment by Aivean** [comment]
Loosely related: [my proposition for dragging model](https://github.com/CleverRaven/Cataclysm-DDA/issues/19934#issuecomment-271137471) (#19934).

**Comment by kevingranade** [comment]
Stale as heck
