### ISSUE TITLE
Lupine mutant howling should terrify NPCs.

### ISSUE THREAD

**Issue by Xenomorph-III** [CleverRaven/Cataclysm-DDA#20131]
The Howler mutation gives a sound of 133 if "Yell" is selected. I'm sure that anyone hearing that sort of piercing sound would be visibly terrified just by hearing it.

Maybe make it reduce trust and increase Fear.

**Comment by keyspace** [comment]
Then NPC mutants with this mutation should "reduce trust and increase fear" in the player character, no?.. I mean, making it one-way would be lop-sided.

Relevant: #18957

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
