### ISSUE TITLE
Item description for jacks does not respect user-selected unit for mass (lbs/kg)

### ISSUE THREAD

**Issue by CMDadabo** [CleverRaven/Cataclysm-DDA#20140]
The descriptions for jacks always list their weight rating in kg, even if the user has selected lbs as his preferred display unit for mass. Is this the intended behavior?

**Comment by bdgackle** [comment]
Looks like it is hard coded to work that way (though I agree, it doesn't sound like the original intent).

It looks like there is a convert_weight() and weight_units() function that need to be called to display the strings correctly (located in src/cata_utility.c).  An example of these being used correctly is up at the top of item::info(), around line 722.

The line that would need to change is in src/item.cpp, around line 1481.  Value printed is currently:
    q.second * TOOL_LIFT_FACTOR / 1000

convert_weight() already divides by 1000 to get kg, so this would probably need to be replaced with:
convert_weight(q.second * TOOL_LIFT_FACTOR)

Then add a string field to the string_format call, call weight_units() to get the right string, and replace the hard coded kg.

I'm happy to do the fix when I get around to it, but if anyone wants to use that as a starting point, then great.  (I haven't contributed to CDDA before, so I need to go read the workflow documentation before I submit any pull requests... realistically, not going to happen before the weekend).
