### ISSUE TITLE
No special input in debug/cheat sub-menus (regression)

### ISSUE THREAD

**Issue by keyspace** [CleverRaven/Cataclysm-DDA#20147]
Fallout from PR #20041.

Certain sub-menus of the cheat menu, e.g. "Wish for an item" or "Spawn monster", rely on special key bindings, such as `f` for "contained item" or "friendly monster", `i`/`d` for group size change, etc.

Seems that key presses are no longer passed to the `key()` method of the relevant `*_callback` classes. The "global context" move up/down, ENTER, etc. do work.

Originally mentioned in #20065.

**Comment by WizardOfOoo** [comment]
I can verify.

pressing "f" to get a wished for item in a container instead goes back to the search.
