### ISSUE TITLE
Muffler is too effective; all noise is muted

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#20141]
I am unsure if this is a bug or a missing feature, but after I crank engine, no noise is displayed. The engine does make starting noise

EDITEDIT: Aha, it seems the muffler is a little TOO effective. It totally muffles all noise.

**Comment by keyspace** [comment]
I think vehicle-made noise is simply not displayed in the player UI.

This was mentioned in PR #19629 (Drop conversion factors from vehicle code, closed unmerged after VPO revert) as a "next step".

**Comment by CoroNaut** [comment]
The noise level displayed is how much noise the character themselves make. There is no way currently to display any other noise types other than the little feet that pop up when another entity makes a noise. This was an issue before.
