### ISSUE TITLE
Being able to scale the right side of the GUI + font size

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#20144]
Im playing the game on a 27" screen. Im using windowed fullscreen mode so i can easily tab in and out.
However, after playing the game for some time, my eyes hurt because the font size is so tiny and it cant be scaled up any way.
Are there plans to make the very right frame of the game somehow scalable and / or alter the font size ?

**Comment by BrettDong** [comment]
Currently you could manually edit `config/fonts.json` and increase `fontwidth`, `fontheight` and `fontsize`.

**Comment by AncientSion** [comment]
wow, ok. Thats already a good start. Thanks for the advice.

**Comment by kevingranade** [comment]
Feature exists but could stand to be more visible.
