### ISSUE TITLE
Use BugTrap to catch crashes in Windows builds

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#20163]
[https://www.codeproject.com/articles/14618/catch-all-bugs-with-bugtrap](https://www.codeproject.com/articles/14618/catch-all-bugs-with-bugtrap)

![Screenshot2](https://www.codeproject.com/KB/applications/BugTrap/Screenshot2.png)
![Screenshot3](https://www.codeproject.com/KB/applications/BugTrap/Screenshot3.png)
![Screenshot4](https://www.codeproject.com/KB/applications/BugTrap/Screenshot4.png)

**Comment by kevingranade** [comment]
Feel free to integrate, but the integration code should probe for the
appropriate dll and the game should continue if it is not present.  I.e. it
shouldn't be a hard dependency of the game.

**Comment by sethsimon** [comment]
I love the idea of every crash report being accompanied by a backtrace, given that the experimentals come with debugging symbols. Similar issue: #2168.

**Comment by Leland** [comment]
Closing – this is an obvious win, and we're 3 months past the last discussion. If anyone wants to add this to the game, feel free to open up a PR (with the considerations that @kevingranade mentioned). Should there still be a need for discussion around the exact implementation of this, ping me here and I'll reopen; or just create a new issue regarding it.
