### ISSUE TITLE
Some professions still lack appropriately warm clothes for the current spring temperatures

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#20169]
For example, hobo. [This](https://upload.wikimedia.org/wikipedia/commons/7/7d/Chicago_Hobo.jpg) is roughly how an average hobo looks like - note two separate jackets over a hoodie and presumably also clothes underneath, because hobos wear all their clothes on themselves regardless of seasons. Meanwhile in CDDA hobos start with just an undershirt and a single knit scarf, which is woefully insufficient. 

Other under-equipped professions: police officer, used car salesman, handy man, backpacker, fast food cook, electrician, computer hacker, student, biker, otaku, etc.

No, I don't consider "they didn't have the time to grab their outside clothes" to be an answer. Either they did have time and did grab, or the clothesracks need to be added to all workplaces and houses, with warm clothes included, or the descriptions need to be amended similarly to shower victim and blacksmith.

**Comment by Leland** [comment]
From a game mechanics perspective, I feel like _finding_ appropriate warm clothing is part and parcel of the beginning of a CDDA game.

**Comment by 1skandar** [comment]
> From a game mechanics perspective, I feel like finding/crafting appropriate warm clothing is part and parcel of the beginning of a CDDA game.

Which is good and all for the starts where that is possible. But for something like Wildeness backpackers get kinda boned.

**Comment by Shadefang** [comment]
While I understand the game mechanics side of things, there are some where the starting equipment either makes no sense (as in the hobo example) or where the fact that they have the rest of their kit means they would've grabbed proper clothes too (backpacker, biker, police officer)
But I'd personally say that the the ones where it would somewhat make sense should probably be kept with limited starting gear (fast food cook, hacker, otaku, etc. mostly those who wouldn't have stuff ready to go, or already be out and about)

**Comment by Leland** [comment]
Closing due to lack of recent discussion. Feel free to ping me to reopen if there's still interest.
