### ISSUE TITLE
"Parasite Immune" doesn't protect against Fungal parasites

### ISSUE THREAD

**Issue by Taberone** [CleverRaven/Cataclysm-DDA#20164]
Build 6183

<a href="http://imgur.com/jRW7yF8"><img src="http://i.imgur.com/jRW7yF8.png" title="source: imgur.com" /></a>

Step 1: Debug yourself the "Parasite Immune" mutation.
Step 2: Spawn fungal monsters and start frolicking.
Step 3: Get infected by fungal parasites anyways.

**Comment by Zireael07** [comment]
Parasite Immune mutation applies only to the parasites that you can get through eating meat.

**Comment by Barhandar** [comment]
Then it's currently misnamed/misdescribed, and fungal parasites aren't described that they're external.

**Comment by Night-Pryanik** [comment]
But the effect is "Fungal infection", not "Fungal parasites".

**Comment by DaliTimelord** [comment]
Fungi are in a completely different animal kingdom to parasites.
This is equal to saying that your antibiotics did not work against a virus infection: That's not what its made for.
What you'd need is anti-fungal medication, namely 'antifungal drug' in game.

**Comment by Barhandar** [comment]
>Fungi are in a completely different animal kingdom compared to parasites.

Parasites aren't an animal kingdom.

**Comment by Night-Pryanik** [comment]
FTGJ, blood analysis cbm still shows "Fungal parasite" when fungal infection is present. I think we should change only description of cbm to "Fungal infection".
