### ISSUE TITLE
Apple orchard monster spawns are insane when one uses non default spawn multiplier.

### ISSUE THREAD

**Issue by TheSadFox** [CleverRaven/Cataclysm-DDA#20177]
Monsters in the orchard upon entering it with default 1.00 monster spawn multiplier, theres just a few dogs, maybe a sheep, thats it.

Multiplier of 2.00:
http://prntscr.com/e36gzr

Multiplier of 4.00:
http://prntscr.com/e36j8d

Multiplier of 7.00:
http://prnt.sc/e36e0m

Game version:
http://prnt.sc/e35tc9

No mods at all when testing, just C:DDA module.

How to replicate: Start a new world, set multiplier you want, teleport to the nearest orchard. Change multiplier again, teleport to another orchard. Get confused as to why does this place look like a battlefield on higher multipliers.

**Comment by codemime** [comment]
Please don't use third-party file servers to host your screenshots. Post them directly using the git-hub file colud.

**Comment by kevingranade** [comment]
On Feb 12, 2017 8:10 AM, "codemime" <notifications@github.com> wrote:

Please don't use third-party file servers to host your screenshots. Post
them directly using the git-hub file colud.

Is that so GitHub inlines them?

**Comment by Xpyder** [comment]
While I'm not categorically opposed to third party image hosting, That one is throwing massive script errors that freeze my browser.  Thankfully I'm using firefox which prompts me to kill the script so I can recover my session.  And on imgur you can run into bandwidth issues that make the images unaccessable when trying to diagnose.

If we could link the images inline from a third party site, and we could find a site that didn't have any issues it would be fine, but the one's I've encountered all have their own problems presently.

**Comment by Coolthulhu** [comment]
Monster spawn density code is terrible:
* Numbers are heavily truncated, in typical case it's `one_in( (int)(2/spawn_multiplier) )`
* Spawn multiplier result is not linear, it modifies both chance and count separately and independently

It's a similar issue to one with items and could be fixed in the same way.
