### ISSUE TITLE
Martial Arts Style GUI a bit broken

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#20175]
You know the prompt at the top of the windows "Choose a style (press ? for more info)" ? Yeah, hitting ? fails to give you more info, it just closes the window. More than a bit irritating when you're trying to check which weapons a melee weapon style covers.

(Windows tiles and the last few experimentals, btw)

**Comment by keyspace** [comment]
Possibly same as #20065, or one of issue linked therein?..

**Comment by keyspace** [comment]
Tested on f136e3d (merge commit previous to #20041), issue not present.

**Comment by kolsurma** [comment]
This should be fixed now.

**Comment by kevingranade** [comment]
Yep, fixed now, thanks for reporting.
