### ISSUE TITLE
Examing NPC health does not reveal infections

### ISSUE THREAD

**Issue by DaliTimelord** [CleverRaven/Cataclysm-DDA#20180]
While I was in my campaign, I was attempting to troubleshoot one of my NPCs dying at full health and in a car. I was crossing my fingers that my specific NPC, Ben McClure, was not undergoing a buggy and suicidal process.

Thankfully, that was not the case. I had the luck of both displaying his health as well as his NPC message of infection, but his health screen does not show infections. Showing infections via the health screen is important, especially if I don't receive his infection message in time to save him. In fact, he is literally a few ticks away from dying.

![image](https://cloud.githubusercontent.com/assets/20878878/22535214/840d6ee4-e8c7-11e6-8e84-d78f381b4734.png)

**Comment by BorkBorkGoesTheCode** [comment]
I think the infection color is identical to the fully healed color. I used to be able to see the numbers turn blue when an NPC received a deep wound.

**Comment by DaliTimelord** [comment]
I found this to be particularly strange since NPC health does change color when they are bleeding from a body part.

**Comment by Coolthulhu** [comment]
It's because infection is colored green. Like fully healthy parts...

**Comment by Zireael07** [comment]
Infection might be blue, like turning blue because of lack of oxygen? Or blue like bruises?

**Comment by Coolthulhu** [comment]
Blue is bite.

**Comment by BorkBorkGoesTheCode** [comment]
What about hideous purple?

Pink could be used for bites in future, with blue for infection.

**Comment by Coolthulhu** [comment]
Purple is bleed+bite.

What we need here is part name losing the green coloration, except when infected.

**Comment by codemime** [comment]
> What we need here is part name losing the green coloration, except when infected.

Agreed. Also, `Exit` is not a body part (I mean, I'd drop it).
