### ISSUE TITLE
NPCs will follow you forever if you place a brazier inside a dark building

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#20189]
0.C 20979

If you activate a brazier and place it inside a lightless building when NPC followers are present, they will try to enter your square forever. This can be prevented by activating a flashlight or some other light source.

**Comment by CoroNaut** [comment]
#19977 demonstrates that the NPC has the ability to locate the player at all times when in complete darkness.

**Comment by BorkBorkGoesTheCode** [comment]
It may be related, but the fact that NPCs follow in darkness isn't the problem.

It first started when I tried to set up a brazier inside a strange temple; as soon as I placed the brazier, my follower rushed to my side and demanded that I get out of their way.

**Comment by BorkBorkGoesTheCode** [comment]
Looks like its fixed.
