### ISSUE TITLE
Create magazine types instead of assigning individual magazines to guns.

### ISSUE THREAD

**Issue by Maddremor** [CleverRaven/Cataclysm-DDA#20192]
Currently, the magazines compatible with a given gun is assigned individualy, the M4A1 below as an example.
`"magazines": [`
      `[ "223", [ "stanag30", "stanag10", "survivor223mag" ] ],`
      `[ "22", [ "ruger1022bigmag", "ruger1022mag" ] ],`
      `[ "308", [ "g3mag", "g3bigmag" ] ]`
`]`

If I as a modder were to introduce a custom STANAG magazine, I would need to edit every STANAG compatible weapon and it would still be incompatible with any mod added weapon, requiering compatibility patches. 

I suggest to (if possible) introduce something akin to `"magazine_type":` to guns so STANAG weapons have  `"magazine_type": ["stanag"]` and `"magazine_type": ["stanag", "survivormag" ]` for the M4A1. Given several given magazine types, a gun would require 1) that a magazine corresponded to at least onte type 2) that the magazine contained the right calibre munition. 

Some magazine types , like `"nailmag"` could and should be gun specific, but `"stanag", "leadworks", "glock", "rivtech", "belt", "survivormag"` could be categories. 

The Leadworks magazine adaptor would, for example, set the affected guns magazien type to `"magazine_type": ["leadworks"]`

Additionally, it would provide a default for calibre conversons where no magazine for the cailbre is specified in the guns entry. If a Leadworks gun was converted, as long as there a Leadworks magazine capable of holding the right ammo, it would be usable. 

If there is some reason this can or should not be implemented (possibly within the to me opaque C code) just ignore me.

**Comment by bdgackle** [comment]
This is an interesting notion.  I supposed it would be a better model of real life to have enumerated magazie 'standards' to serve as the interface between guns and magazines, where guns require a mag of a certain type, and magazines implement that type.

As a modder, what sort of properties would you want to manipulate?  I can see where unifying the STANAG magazines would allow capacity to be arbitrary, but are there any other properties of a magazine that a modder might want to manipulate?  Or is this purely to allow for different capacities.

It seems that splitting out 'type' and 'caliber' might be redundant.  Since a weapon would require both fields to match, the fields would effectively form a single unique identifier.  Am I wrong about this?  I might be misunderstanding what would be useful to you.

I think this would be possible to do in C, and I'm willing to give that a try.  I'm just trying to understand the requirements a little better.

**Comment by Maddremor** [comment]
To be frank, have just started modding CDDA, so I can't give a comprehensive description of the the optimal magazine framework. My general idea with this suggestion is to make weapon mods more modular and reduce the need for compatibility patches. 

To provide a real life example: In [BorkBorkGoesTheCodes fork of Modern-Weapons-Pack-Expanded
](Modern-Weapons-Pack-Expanded/modern_extras/overrides_gun.json), the Translucent STANAG magazine `transmag`, (and other magazines) are added to several vanilla guns (see: `ar15`). This is a bit convoluted in my view, and should any other mod add a STANAG rifle, it would require a compatibility patch for it to accept MWPEs `transmag`.

Regarding moddable properties: Besides the attributes currently avaliable when designing magazines (capacity, weight, volume, price, accepted ammo, reliablility, assorted tags) the only property i can think of besides the proposed `magazine_type`, is to allow a magazine to accept several types of magazines. It could allow creating some kind of high-tech magazine compatible with several weapons of different calibers. This is just a side note though.

The reason i proposed type and caliber as separate is twofold. One is to allow caliber converted guns to default to a magazine type from the same manufacturer if magazines for that caliber is not designated. For example: if I convert the .40 Glock 22 to 9mm, it refers to the specific entry for 9mm in its [JSON-entry](Cataclysm-DDA/data/json/items/gun/40.json) and thus accepts `glockmag` and `glockbigmag`. This makes sense considering both Glock calibers probably share a very similar design. But if I were to add a 11mm Glock (for some reason), 11mm Glock magazines, and a 11mm conversion kit, the 11mm Glock would not automatically be compatible with pre-existing Glock magazines if converted to 9mm or .40 unless I specified it. Additionally both the 9mm and .40 Glock variants would need to be modded to accept the new 11mm magazines with the added 11mm conversion kit. If they all shared the `"magazine_type": ["glock"]`, far less tweaking would be neccesary and there would be no need for me to edit any vanilla records. This would apply to the same-manufacturer-different-calibers magazines such as Glock, Leadworks, and Rivtech, plus any mod added manufacturers.

This type/caliber division would also serve less conventional ammunition. You could have a flamethrower use the "magazine" `"magazine_type": "pressurized_tank"` with `"ammo": [ "gasoline", "napalm" ]`, and have a water canon use `"magazine_type": "pressurized_tank"` with `"ammo": "water"`.

Hopefully this clarifies things somewhat. It would be useful if other modders could chime in to provide a second opinion. Also, given that I'm in UTC+1, I might not be able to provide quick responses in this conversation.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
