### ISSUE TITLE
cursesport.cpp performance is very bad

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20190]
See #19304

On any but the smallest viewport, draw time quickly dominates the total execution time.
In my tests with 160x80 viewport, Windows tiles-less build had just 5 fps, compared to Cygwin (MSYS2) build which got 45.
This isn't just a console issue, as all tiles builds (including non-Windows) use the cursesport.cpp, plus the SDL window (as in, screen window) drawing function is pretty much a copy of the Windows drawing function.

Would be great to have that 0.D have manageable drawing code, without it taking roughly the same time to draw 1600 tiles as it takes to execute all the game logic.

**Comment by Coolthulhu** [comment]
I can't locate the slowdown in cursesport, but I'm getting very good results from skipping actual drawing of the fonts.
Could be that I misplaced the bottleneck. Or just that font drawing is significantly slower than everything cursesport does.

**Comment by Coolthulhu** [comment]
OK, it seems that it isn't the cursesport.cpp, but rather texture blitting done in software.
Fixing this would probably require either that SDL_gpu thing or reinventing it using base SDL OpenGL context.

**Comment by kevingranade** [comment]
On Feb 26, 2017 11:02 PM, "Coolthulhu" <notifications@github.com> wrote:

OK, it seems that it isn't the cursesport.cpp, but rather texture blitting
done in software.
Fixing this would probably require either that SDL_gpu thing or reinventing
it using base SDL OpenGL context.

Just in case this gives someone ideas, this wouldn't actually solve the
problem as we have many users that can't use gpu acceleration for one
reason or another.

**Comment by Coolthulhu** [comment]
Do we use alpha blending?
I recall SDL having horribly slow software alpha blending compared to color keying and masks.

I don't know if there is a way to fix it on wincurses. It may be entirely possible that directdraw is the only non-accelerated option there.
