### ISSUE TITLE
Cancel hotkey doesn't work on repairing dialog

### ISSUE THREAD

**Issue by rm-code** [CleverRaven/Cataclysm-DDA#20212]
I just used my sewing kit, opened the "Repair what?" dialog and selected the wrong item.

On the next dialog that pops up I get the following options:
1. Repeat once
2. Repeat as long as you can 
3. ...
4. ...
q. Cancel

Pressing 'q' however doesn't quit the dialog. You have to manually select the entry and confirm with enter.

**Comment by keyspace** [comment]
Duplicate of: #20065.

**Comment by rm-code** [comment]
@keyspace Thanks!
