### ISSUE TITLE
DEBUG: Lost tool used for long repair

### ISSUE THREAD

**Issue by rm-code** [CleverRaven/Cataclysm-DDA#20213]
https://github.com/CleverRaven/Cataclysm-DDA/blob/c2e7fc915e6b2964b1397a29d52fdcfe0baa225d/src/activity_handlers.cpp#L1614

The debug message pointed to the above line. It popped up when a candle winked out while I was repairing my clothes.

I wasn't sure if I'm supposed to report messages like these?

**Comment by Coolthulhu** [comment]
If the candle itself was used to repair (mods?), then it is not a bug and has to work like that.
If the candle was only there for light, it is a bug.

Was any of the clothing items destroyed in the repairs?

**Comment by rm-code** [comment]
No, I used a sewing kit for the repairs, but the candle was burning so I could see in the dark.
My best guess is that once it burned out, it became too dark for my character to see / craft.

> Was any of the clothing items destroyed in the repairs?

Nope.

**Comment by rm-code** [comment]
@Coolthulhu I am closing this as it is impossible to reproduce without the savegame and the little information I provided.
