### ISSUE TITLE
Broken driving car bug

### ISSUE THREAD

**Issue by NEONZARIN** [CleverRaven/Cataclysm-DDA#20223]
In the latest builds a very serious issue with driving a car. At speed +16 km / h drive the car becomes mission impossible! In one move, the car was moving well, very quickly. When this terrible bug will be fixed ?! Please do not ignore this message. And for the opportunity to explain where did this bug? This bug did not I have one, from other players, he also available. This bug appeared after allegedly build 6033. This bug disgusting - very strongly interferes with the play. When writing this text to use online translator - if that is not offended because of bad translation. I tried as much as possible accurately convey the meaning of the bug.

**Comment by NEONZARIN** [comment]
http://dev.narc.ro/cataclysm/jenkins-latest/Windows/ <<<<this brunch

**Comment by Firestorm01X2** [comment]
Probably he means something about car handling. As far as remember a month ago car handels a lot more smoothly.

Probably it is related with revert of: https://github.com/CleverRaven/Cataclysm-DDA/pull/19275

**Comment by Zireael07** [comment]
I think he means the lack of refresh, actually, which does give the feeling of the car moving quickly.

**Comment by ZenZen2** [comment]
I think this will be fixed with #20218
