### ISSUE TITLE
Update required astyle version

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20225]
As in #20224

Current "official" astyle does an indent after forward declaring an enum, which is ugly and unintuitive.

**Comment by keyspace** [comment]
Currently `2.05.1` is used. `2.06` has been released in December 2016. It has a [different bug](https://github.com/CleverRaven/Cataclysm-DDA/pull/20211#pullrequestreview-20392033), which is arguably less ugly.

**Comment by Leland** [comment]
`3.0` [dropped last month](http://astyle.sourceforge.net/notes.html) – haven't had a chance to try it out yet, but it may fix that issue.

**Comment by lucianposton** [comment]
I'm moving forward with the following plan to complete this issue.

- [ ] 1. https://github.com/CleverRaven/Cataclysm-DDA/pull/21930 will modify Makefile to prefer the `astyle3` binary installed at /usr/local/bin/astyle3 on the CI machine and fallback to `astyle` if `astyle3` doesn't exist. It also reformats files to pass astyle 3.
- [ ] 2. @narc0tiq will update the system install of astyle to version 3.
- [ ] 3. Merge a second PR, https://github.com/CleverRaven/Cataclysm-DDA/pull/21958 , to revert the Makefile change introduced in step 1 above.

**Comment by narc0tiq** [comment]
(I just ticked the box next to 2., as the system-wide `astyle` should now be coming from Astyle 3.0)
