### ISSUE TITLE
Vehicle turrets auto firing even when set on manual

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#20245]
Heard some gunfire and saw a Hum-vee firing on a pack of zeds. "Odd" i thought, "Don't vehicles spawn with their turrets set to manual?" Wander over, and sure enough, its turret *was* set to manual. I then went and grabbed my vehicle and as I drove past the pack of zeds *its* turret started firing...despite being in manual mode also.

**Comment by keyspace** [comment]
Which version? Any mods, `blazemod` in particular?

**Comment by 1skandar** [comment]
Latest experimental. And yes, blazemod is installed. Things were working as of the latest 2 days ago (6208) , but the latest last night (6225) was causing the issue.

**Comment by 1skandar** [comment]
This commit, maybe? https://github.com/CleverRaven/Cataclysm-DDA/commit/268d38ec9806d4532cf64645f21dd3cbc8ba53b1

**Comment by EyesNoEyes** [comment]
I'm getting this on 6227 as well.

**Comment by QuDu43bChhiONNVlgkoy** [comment]
Same issues on 6228, also have blazemod installed. Was working very recently.

**Comment by 1skandar** [comment]
Ok, as an update it appears that this appears to only happen to turrets set to auto fire versus single shot. The tank I walked by, thankfully, DID not shell the zombies behind me.

**Comment by kevingranade** [comment]
Should be fixed by #20287
