### ISSUE TITLE
Reach attacks non functional

### ISSUE THREAD

**Issue by EyesNoEyes** [CleverRaven/Cataclysm-DDA#20242]
Using the Qiang and Knife Spear, you cannot attack enemies at a distance.

**Comment by keyspace** [comment]
Tried knife spear - works just fine.

Do you have circular distances on?

Do provide [bug report info](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/ISSUES.md#bug-reports).

**Comment by EyesNoEyes** [comment]
Build 6225 on Windows 10

Circular distances off.

**Comment by Leland** [comment]
What exactly happens when you use the <kbd>f</kbd> key to do reach attacks?

**Comment by bdgackle** [comment]
Also, have you done successful reach attacks with any other weapons?  Trying to determine if issue is specific to those two, or if those are just the only observed examples.

**Comment by EyesNoEyes** [comment]
Welp, I know what the problem is now. Thank you. The way reach attacks work changed since last i played. It did it automatically. Sorry.

**Comment by Coolthulhu** [comment]
It never changed - it was always 'f'. There is also the tab option.
