### ISSUE TITLE
Wander Spawns / Static spawns are confusing to new players.

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#20255]
I get the "what are wander/static spawns": question a lot on Reddit.  It might be worth it to expand or change the existing explanation.

**Comment by Night-Pryanik** [comment]
"Static spawn" -> "Spawn zombies at start", and "Wander spawn" -> "Zombie hordes"?
P.S. change "Wonder" in title to "Wander".

**Comment by Coolthulhu** [comment]
Weren't we supposed to obsolete non-static spawns?
As far as I know, they don't work.

Unless some people are using them as a way to prevent static spawns altogether.

**Comment by WizardOfOoo** [comment]
The settings for both are still in the menu.  
![image](https://cloud.githubusercontent.com/assets/17521661/22851891/89739f40-eff5-11e6-8b3c-a574fe9117e5.png)

**Comment by WizardOfOoo** [comment]
If one of them is obsolete then I think they both could be removed.  Can't think of a reason why you would want to turn both off.

**Comment by Zireael07** [comment]
The setting for dynamic/static is there still even though word is dynamic is obsolete...

**Comment by WizardOfOoo** [comment]
Ah so if you turn off static you get the old dynamic spawning?

**Comment by kevingranade** [comment]
The static spawn option should definitely go, it's been the only supported mode for a long time now.
Wander spawns is different, it is a hacky stopgap for having hordes move arund at a larger scale, it still has a niche.  Could probably use a different description.

**Comment by NickGrease** [comment]
I'm sorry I'm a bit out of the loop here; but is there a reason we can't have a happy medium between static and hoard spawns? Clearing a town of static spawns feels... boring, but having hoards spawn on top of you all the time feels...cheap. Is just spawning in a few mobs every now and then really that hard? I don't want a town to ever be 'cleared', but at the same time, unless it's infrequent, I don't want a town I've cleared to be constantly overrun with mobs either.

**Comment by keyspace** [comment]
> ... can't have a happy medium between static and hoard spawns?

> Is just spawning in a few mobs every now and then really that hard?

This is an example of "confusing". What you are comparing is "static vs. non-static", not "wander vs. non-wander".

-----

How about:

> Wandering monster groups
> 
> Emulates migration of monsters based on light, sound, and smell, even those very far from the player. Currently works for zombies only.

Not sure about the smell part.

**Comment by Moumix3** [comment]
"Static spawn" option is gone after this commit: https://github.com/CleverRaven/Cataclysm-DDA/commit/0a2233b14eb605a9767ed7859715c9b8434ac03f

Should this issue be closed?

**Comment by WizardOfOoo** [comment]
yea, thanks.
