### ISSUE TITLE
[Proposal] Revert last month's input context handling changes

### ISSUE THREAD

**Issue by keyspace** [CleverRaven/Cataclysm-DDA#20251]
Ping @BevapDin as it's their work directly influenced.

As discussed in #20065, the recent input handling changes have introduced numerous regressions, touching both of:

* normal play - such as hotkeys becoming unavailable or, worse, giving unexpected results;
* debugging issues - removing hotkeys that can't be assigned manually, or, worse, making actions unavailable.

The _initial_ issue with input handling was, as mentioned in PR #19961:

> It also makes input_manager::get_input_event simpler: instead of one implementation for all platforms, it is split into several implementations, one for each platform.

The _current_ issue is that "incremental refactor by successive PRs" done so far did not swap one system with another completely. Essentially, we now have two systems that "compete for user input", and that doesn't go well for UX.

Input is such a huge system that it's probably best to develop in a feature branch. :/

-----

I propose to revert PRs listed below:

* PR #19961 - replace `getch` with input manager
  * #20037 - menu disappears after mouse moved
    * PR #20041 - allow scrolling, use `input_event`
      * #20065 - prompt/query hotkeys unavailable
        * PR #20072 - `q` hotkey becomes available, others not (not yet merged)
      * #20091 - debug menu skips mappings
      * #20147 - special input unavailable in cheat sub-menus
      * #20175 - `?` exits martial arts menu
  * #20047 - CTRL+C bypassable, breaks screen refreshing
    * PR #20063 - fix that

The above would also require reverting dependent:

* PR #20033 - `string_input_popup` factored out into a separate class
  * #20234 - a few small regressions
* possibly more!

**Comment by keyspace** [comment]
The "stage as feature branch" proposal was snipped prior to posting - separate issue, not sure if anyone available/interested to do it.

**Comment by kevingranade** [comment]
I think you might be casting too wide a net, #19961 caused #20037, but that was fixed by #20041.
It looks like reverting the final commit of #20041 will prevent the keybinding issues we've been dealing with, leaving us in a pretty good state.

In other words counterproposal is to revert
* Last commit of #20041 
... Actually that's it, what state would that leave us in?
I'm going to try it and see...

**Comment by kevingranade** [comment]
Ok tested, then was reading and ran across #20072 again, I see that won't do it.
I'm not clear on the mechanism that causes #19961 to trigger any of this breakage, it looks like #20041 is mostly to blame?  Anyway, I'll see what we get by rolling back all of #20041 except the mouse action fix.

**Comment by kevingranade** [comment]
I haven't had a chance to look into this, but I'm stating to think you're right and we'll need to revert the whole thing.
I'm definitely not interested in pushing forward unless there's a clear explanation of what went wrong and exactly how many things need to be fixed to get it back to normal.
Just to be clear, having the menus skip entries for no apparent reason isn't a solution.

**Comment by kevingranade** [comment]
Reverting #20041 conflicted rather heavily with #20033, I'll take another stab at it, because I still think we can at least save #19961 and #20033, but if I can't make that work, yea we'll have to pull the whole thing out.

**Comment by keyspace** [comment]
PR #20347 (in tandem with PR #20174) seems to address all issues listed above ATM. It does uncover another issue, which may be pre-existing  - see discussion in PR #20347.

It is reasonably close to a solution that will make a revert unnecessary. It limits the (so-far discovered) weird behaviour to a specific menu (the `%` action menu). Barring more bugs uncovered, that would be preferable IMO.

**Comment by kolsurma** [comment]
@keyspace, other than `q` not exiting all menus equally, only those that explicitly add it, does the merging of #20347 et al. fix the discovered issues?

**Comment by keyspace** [comment]
@kolsurma, tried current git master (`0.C-21530-gaa8c84cd60`), wasn't extremely thorough, but yes, it seems that the issues are addressed.

IMO proposal no longer valid, so closing.

**Comment by kevingranade** [comment]
This is belated, but I wanted to thank @keyspace for the very thorough investigation, it was instrumental in resolving the issue.

**Comment by keyspace** [comment]
Heh, thanks to you and @kolsurma for not giving in to a revert. It's brought the UI slightly closer to unification.
