### ISSUE TITLE
Fried dandelions, vending machine items, shoveling wreckage and vitamins.

### ISSUE THREAD

**Issue by Grelko** [CleverRaven/Cataclysm-DDA#20257]
6175 Cataclysm Tiles version 0.C-20896-gcaf6938fec . Fried dandelions have Tallow or Lard as "tools" instead of components. Also, it doesn't ask which of them to use and doesn't even use either of them when you make the recipe.

A lot of the items in vending machines show up as costing $0.00, so they are free to purchase.

Certain items "wild herbs, etc" having vitamins listed, but herbal tea doesn't, so I'm not sure if it helps your vitamin needs.

Shoveling wreckage uses A LOT more energy than I thought it would, like every 7th time in a row, I'm almost dehydrated and after I think it was 12 I'm famished.

**Comment by Grelko** [comment]
Please disregard the part about shoveling wreckage. It is the same as issue #19114.

**Comment by WizardOfOoo** [comment]
Think if you update to current experimental it's fixed.

**Comment by Rivet-the-Zombie** [comment]
>Fried dandelions have Tallow or Lard as "tools" instead of components. Also, it doesn't ask which of them to use and doesn't even use either of them when you make the recipe.

You can still reuse the grease after frying stuff in it.

**Comment by WizardOfOoo** [comment]
> Certain items "wild herbs, etc" having vitamins listed, but herbal tea doesn't, so I'm not sure if it helps your vitamin needs.

Wild herbs have vitamins, the tea does not.  It's in the description.  For vitamin purposes, making a tea is not as good as eating the plant whole.

**Comment by WizardOfOoo** [comment]
Does that clear this up @Grelko ?

**Comment by Grelko** [comment]
Thanks for the quick replies,

I'm downloading the newest version as I type this, I'll be sure to check the vending machines.

I thought the wild herbs would still have vitamins in it as tea, just a lower amount. Possibly 4% vitamin C, since it's water soluble, but you're right. Even though they have 20% vitamin C, the amount actually transfered over to the tea would be so diluted by water, that it would be negligible unless you made mass quantities and evaporated most of it.

To Rivet-The-Zombie,
I forgot about reusing the grease. At the time, I was thinking that you would have less, since some of it is being soaked up by the dandelions and flour, which would have made it a "component" instead of "tool", but this is fine the way it is also. Thanks for clearing it up. 

Thank you for the assistance.
