### ISSUE TITLE
Number query inputs include the query text in return value

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20264]
* Spawn c-4
* Activate it
* Set to some number
* It is ignored because the window tries to parse the entire string rather than just the number you input
* Thankfully it is special-cased to ignore 0 time setting rather than exploding in your face
* Activate it again
* This time backspace all the way to the left
* Input 1
* Die, as expected

**Comment by WizardOfOoo** [comment]
Same thing happens when trying to edit your stats with the debug menu.
