### ISSUE TITLE
Can't pick up gear (Wear or wield) in a vehicle

### ISSUE THREAD

**Issue by zapa1928** [CleverRaven/Cataclysm-DDA#20269]
Windows 7 CDDA 6235 build

To reproduce
- Start new character and go to the first car you'll find
- Drop all your clothes on a seat (you'll drop rest of your inventory as a result)
- Try to pick up any gear -> Message Log says in this case "Never mind"

You can't pick up anything cause you don't have space in inventory but for some reason you also can't wield anything or wear (in case of wearable items).

The problem doesn't occur outside of car.

If you try to pick sth up (outside of a car) but you'll cancel, you are able to pick up (wield) one thing from a car.

**Comment by Night-Pryanik** [comment]
Can't reproduce it. Was able to wear clothing lying on a seat that I previously dropped there.

**Comment by zapa1928** [comment]
Did you drop all your clothing?

**Comment by Night-Pryanik** [comment]
> Did you drop all your clothing?

Yes, I dropped all clothing and items worn by my character.

**Comment by kolsurma** [comment]
@zapa1928 how are you trying to pick up the items? 

If you try "W"earing them and the item is not in your inventory it will display "You don't have any items to wear." and cancel the action. The wear code doesn't look into neighboring tiles for potential wearable items.

If you use the "/" advanced item management you can press "w" to wear items directly.

If you use the "g"et or "e"xamine it will allow you the option to wield or wear the item if you don't have enough capacity.

**Comment by zapa1928** [comment]
i am using g to get but the option to wield or wear is not showing in cars.

**Comment by kolsurma** [comment]
The option comes after trying to pick up something you don't have capacity for. Try picking it up and it _should_ open a new prompt with wear or wield being the options

![capture](https://cloud.githubusercontent.com/assets/10261427/22956107/98492588-f2e5-11e6-81f4-a7d9c7e4ac60.PNG)

I can't seem to reproduce the error with the steps you list.

**Comment by WizardOfOoo** [comment]
might be easier to repro if you uploaded a save somewhere.

**Comment by zapa1928** [comment]
Ok, no bug. Keyboard mishaps.
