### ISSUE TITLE
soundset.json not used if not in data/json

### ISSUE THREAD

**Issue by junkdeck** [CleverRaven/Cataclysm-DDA#20263]
If I put a soundset.json inside Chesthole's soundpack, no sounds plays. If I put the same soundset.json directly into data/json, sound plays.

Weirdly enough, if I remove the soundset.json from Basic and put it in data/json, that _doesn't_ work. What's up with that?

**Comment by remyroy** [comment]
What exactly is your issue? Are you trying to create a soundpack?

**Comment by junkdeck** [comment]
My issue is that soundset.json's apparently aren't read from the soundpack folders, only the global json folder, but only in some cases. I'm just using Chesthole's soundpack and noticed this behaviour.

**Comment by AMurkin** [comment]
Simple way: if you play experimental builds: use remroy's launcher and it's built in functionallity.
Hard way: you need to put soundpack's folder into data/sound and go to ingame options (bottom of first tab) to choose that soundpack.

**Comment by junkdeck** [comment]
That's the thing, though. Some times, the soundset.json inside data/sound/pack isn't read. I already have sounds working, that's not the issue, but the way soundset.json is dealt with is inconsistent.

**Comment by Leland** [comment]
@junkdeck can you provide a set of steps to replicate this behavior?

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed for a very long time.
