### ISSUE TITLE
Terrain types for building internals have no roofs

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20283]
Some terrain types have no roofs and thus rely on the "impassable terrain is walkable from above" rule. This rule should be avoided because it is slow to compute and uncached.

Those are:
* Reinforced glass
* Consoles
* Card readers
* Doors (not all?)

Trees are an edge case. They could get roofs to make them more complex, but the roof rules could possibly be a bit too building-specific for trees.

Related to #20282

**Comment by SgtMustang** [comment]
Hi Coolthulu,

I was experimenting on my end with a rewrite of the ingame names and descriptions for all of the terrain floors and wanted to get some more background on it to see if what I'm doing has soemthing to do with what you've mentioned here. 

For example:

```
 {
    "type": "terrain",
    "id": "t_floor_blue",
    "name": "blue floor",
    "description": "An open-air section of blue flooring.",
    "symbol": ".",
    "color": "blue",
    "move_cost": 2,
    "flags": [ "TRANSPARENT", "FLAT" ]
  },
```

Blue floor is currently in the terrain_indoors json, but it doesn't carry the "INDOORS" flag. Doing a search for t_floor_blue only returns references to mapgen and, specifically, labs. I wasn't sure if I'm describing the same issue as you are here, what do you think?

I'm also somewhat confused about what property makes a tile weatherproof or not. t_floor_blue doesn't have the indoors property, but presumably it isn't raining underground. If I read your post correctly, does the game check if the tile above is walkable and then determine if it is "indoors" or not? Would it be better to add the "indoors" tag for tiles such as t_floor_blue?

**Comment by I-am-Erk** [comment]
Resolved by the manual roof project, mainly.
