### ISSUE TITLE
Roof parameters are not verified, allowing invalid definitions

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20282]
Currently INDOOR tiles are at the same time both floors and parts of roofs.
Because of that, a roof tile that is destroyed must destroy the floor tile below. Otherwise the roof tile will be recreated on next load.
But we don't want weak roofs to collapse strong walls below them, so we can't keep destroying just like that.
Therefore to work properly, the roofs need to be as strong or stronger than terrain below and this should be verified.

Non-INDOOR, non-SUPPORTS_ROOF tiles should not have roofs, except when they are impassable. Impassable tiles should have roofs if they are parts of a building. Otherwise it's an open question (tree "roofs" could be helpful to make climbing better).

**Comment by DangerNoodle** [comment]
If possible, one solution would be for a terrain entry that has an associated roof to only create that roof when first generated or constructed, and possibly add ways for construction recipes to check for the presence of a roof above the space being considered.

This would allow for a third solution to this consideration, and enable things like players, NPCs, or monsters breaching a building from above.
