### ISSUE TITLE
Base "Human" trait

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20281]
Base traits of a baseline Joe Average human should be a trait on their own.
This trait would then define values of an average human:
* Hunger/thirst/tiredness rate
* Base temperature
* Blood field type, meat chunk type
* Body size, dodge modifier from size
* (Later on) Thresholds for temperatures (freezing, cold, comfortable etc.)
* (Much later on) Body parts, movement modes

That wouldn't mean much for the (current) core game, but would enable:
* Mods to change the effects
* Non-human characters too mutated (or just alien) for the human baseline to be the best fit
* Less hardcoded handling of many stats: instead of `value = base + sum(effects)`, just `value = sum(effects)`. This is important for things like body parts, where we'd want to be able to lose them, install new ones etc.
* Understanding (and correcting) the game from jsons alone, without having to dig into hardcode

**Comment by roushguy** [comment]
This would also be useful for certain threshold categories too, would it not, without necessitating giving the stat bonus mutations to specific categories?

**Comment by kolsurma** [comment]
For the hunger/thirst/tiredness/temperature, would you also have the minimum/maximum along with the average? This would allow some randomness (for NPCs) to be applied while still having a 'baseline' human.

Would a json defining allowable sizes and their stats be preferable to defining it per creature type?

Temperature threshold could probably be tied to base temperature, with modifiers from other traits (fur, thick hide) acting on it.

Categories should probably not contain the body parts directly. Which category would apply if a creature had different mutated body parts? If, for example, you had the cephalopod threshold mutation, do your human body parts fall off and cephalopod body parts replace them?

**Comment by kevingranade** [comment]
Great idea in general, I'm a little concerned about what things look like
once limbs are factored out, but hopeful that it's not as big a mess as I
fear.

**Comment by Coolthulhu** [comment]
I'm still not sure whether limbs should be overrides, offsets, multipliers or something else altogether (formulas?).
For example, if someone picks a child base instead of human base (just an example, child doesn't need to be a base trait), we'd want the tail to share the HP decreases from the base trait.
At the moment the best idea for this I have would be to define new parts using existing ones - for example, "tail has 80% hp of torso and 10% of its hit size in melee".

**Comment by Coolthulhu** [comment]
I actually tried implementing it and got most of it, but one thing was a problem:
Should the trait be actually visible to the players? If everyone has it and it is only useful for code clarity and mods, displaying it sounds like a bad idea. But if other traits may override it (say, "Child"), it would be useful to have it visible.

**Comment by Zireael07** [comment]
Are we going to have overriding traits, then, such as child?

**Comment by ZhilkinSerg** [comment]
> Are we going to have overriding traits, then, such as child?

Why don't we have character age, btw?

**Comment by kevingranade** [comment]
From a trait point of view, age conflates a lot of different things, so it
is a really messy thing to track.  It's better to track individual traits
like size, strength, intellect, fitness, toughness, etc.

From a game progression point of view, we have no plans to track aging for
long enough for it to have an impact, so it's not worth tracking at all.

**Comment by kevingranade** [comment]
Not against the concept in principle, but no need to leave the issue open.
