### ISSUE TITLE
Drying Pans

### ISSUE THREAD

**Issue by 2birdie** [CleverRaven/Cataclysm-DDA#20297]
When wielded, allow a frying pan to be able to block rain, much like an umbrella!
Inspired by a friend!

**Comment by DaliTimelord** [comment]
Oh?
![image](http://i.imgur.com/Ecw8Gy5.gif)

**Comment by CoroNaut** [comment]
this **does** leave the rest of your body to get wet except your hair and maybe face, so you would still need rain protection. Also, wouldn't you have to be wielding it?

**Comment by DangerNoodle** [comment]
If the `RAINPROOF` flag was body part specific, it might be interesting. Having rain hoods actually protect the head from rain for example, and to make the survivor cargo pants less odd.

Having a similar effect for wielded objects would be more complex, and might require umbrella effects to be converted to work via a JSON flag first,
