### ISSUE TITLE
Mod returning an error for having an emtpy terrain set but also for not defining a set

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#20296]
It appears I literally have to define scrap, unused terrain in order to not return an error on maploading when using an empty, single-terrain maptile.

Example:

- The first error complained of here:
http://smf.cataclysmdda.com/index.php?topic=12051.msg295688#msg295688

- Source
https://github.com/pisskop/PKs_Rebalancing/blob/master/locations/doomcastle.json#L885

* This particular area is a blank area of rocks.
Errors also return for a * blank area is a single terrain tile with furniture, traps, and terrain added by random generation.  The error has recently appeared in the newest updates.

This is perhaps asking to both have and eat cake, since the only way to remove the error (and thus keep the mod presentable) is to add junk lines.

**Comment by Coolthulhu** [comment]
Not sure what do you mean. You want to define terrain that has no `rows` field and only `fill_ter`?

**Comment by pisskop** [comment]
when there is no {terrain} in the rows bracket it returns an error.  thats happened for as long as ive known the mod.

in the most recent expies, having an empty {terrain} bracket in row returns an error.  likely due to linting.


having fill_ter (in this case set to t_rock to simulate a solid rock fill) returns an error.  i had to put in a single definition ( " ": "t_rock") in order to remove the error.

its forcing unused lines into terrain.
