### ISSUE TITLE
Construction scaling option doesn't work like its description

### ISSUE THREAD

**Issue by Moumix3** [CleverRaven/Cataclysm-DDA#20291]
The description for the world option "Construction scaling" says: _**"Multiplies the speed of construction by the given percentage"**_

With that description, I would expect a setting of 50 to double the construction speed, (eg: Construction speed 1h x 50% => 30 minutes), but the opposite happens, it doubles the construction time instead.

A fix for this would either be to change the description, or swap the calculation in construction::time_scale() in construction.cpp, like this:

```
float construction::time_scale() const
{
    //incorporate construction time scaling
    if( get_world_option<int>( "CONSTRUCTION_SCALING" ) == 0 ) {
        return calendar::season_ratio();
    } else {
        return get_world_option<int>( "CONSTRUCTION_SCALING" ) / 100.0;
    }
}
```

Please note I didn't check what "calendar::season_ratio" returns, but I assume this is correct.

**Comment by Rivet-the-Zombie** [comment]
It should probably say "Multiplies the **time** of construction by the given percentage" instead.

**Comment by ryvn** [comment]
The current phrasing is correct, though. If you multiply construction *speed* by 50%, you are constructing *half as fast*, which means it takes *twice as long* to construct anything. "Speed" of work is work/hour, not hours taken to complete (which would just be construction "time").
