### ISSUE TITLE
Smoking rack to work like the charcoal kiln

### ISSUE THREAD

**Issue by Veraghin** [CleverRaven/Cataclysm-DDA#20300]
Currently, you have to have a charcoal filled smoking rack nearby to be able to make smoked meat, which takes an hour of crafting time. I'm proposing to change the rack to work like the kiln, fill a rack with charcoal and meat chunks and leave it for an hour or so and come back to collect the smoked meat.
I'm not sure if this would unbalance food, as rows of racks could be used to manufacture large amounts of non perishable smoked meat, although you'd need to have charcoal production up and running for that to be effective.

**Comment by Leland** [comment]
Closing due to lack of discussion. Feel free to ping me to reopen if there's still interest.

**Comment by Amariithynar** [comment]
@Leland Pinging you as you requested for https://github.com/CleverRaven/Cataclysm-DDA/issues/20300 "Smoking rack to work like the charcoal kiln"

It really should operate properly like a smoking rack where you activate it and leave it to do its job, like the kiln or the brewing keg.

**Comment by Veraghin** [comment]
I was going for a bit more ambitious project with this, I wanted to make it so that you could have a general framework for machines to work like you just described, from the smoking rack, to possibly high tech manufacturing. Reason being that the iexamine.cpp code was getting a tad bit too cluttered. There is #20515 with most of the code in it and some discussion on the subject.

**Comment by Brambor** [comment]
Should be closed according to #24307
