### ISSUE TITLE
Dynamic NPC spawn rate do not get default values in world gen options

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#20318]
Version 21220. Tiles, Win64
To reproduce:
1) Start creating new world
2) Go to world generation options
3) Look at dynamic NPC spawn rate

Expected:
Dynamic NPC spawn rate set to 0,01 by default

Actual:
Dynamic NPC spawn rate set to 0,00 by default

**Comment by Night-Pryanik** [comment]
Can't reproduce on 0.C-6368, Win 10 x64, tiles.

**Comment by Zireael07** [comment]
That issue had a duplicate, was essentially related to locale settings (comma vs dot used as decimal separator) and was fixed.

**Comment by Night-Pryanik** [comment]
Should be closed then.
