### ISSUE TITLE
Explosives Have Wildly Variant Sound Volumes

### ISSUE THREAD

**Issue by Nioca** [CleverRaven/Cataclysm-DDA#20324]
`Experimental Build 0.C-6235 Windows 7 SDL`

A select few explosives seem to have unusually low or off sound levels when detonated. Flashbangs in particular stand out, as IRL Flashbangs generate ~170dB of sound. Here, they create a volume 12 sound (About the sound level of a clumsy footstep). While Flashbangs still achieve a blinding effect against characters and a stunning effect against monsters, they actually produce almost no noise and are incapable of impeding player/NPC hearing. Likewise, certain rockets seem to have particularly unusual values; an M202 Flash's massive death fireball produces a 47 volume sound. Meanwhile, while the LAW rocket produces only 239 volume in noise, the RPG-7's PG-7VL produces 7620 volume (approaching twice that of a mininuke!) for only 500 damage more.

I compiled a list down below, which includes a 9mm Gunshot for comparison purposes. Sounds marked with an asterisk (*) are ones that were tested adjacent to epicenter (since the aiming menu doesn't allow you to shoot yourself or your own feet).

Explosive | Sound at Epicenter
--------- | -------------------
40mm Frag Grenade | 9*
Flashbang (40mm & Regular) | 12
Incendiary Grenade | 16
M235 TPA | 47*
_9mm Gunshot_ | _80_
Most Lightweight Handheld/Thrown Bombs (Pipe Bombs, Grenades, etc.) | 110-140
40mm Concussive | 239*
LAW Rocket | 239*
Match Head Bomb | 240
Fertilizer Bomb | 350
Homemade Incendiary Rocket | 356*
M3 84mm Rockets | 399*
Dynamite | 500
Black Gunpowder Charge | 600
C-4 | 650
Explosive Homemade Rocket | 1496*
ANFO Charge | 4000
Mininuke | 4500
PG-7VL Rocket | 7620*
RDX Charge | 8000

**Comment by Coolthulhu** [comment]
Sounds like we need a non-linear scale here.

**Comment by kolsurma** [comment]
like maybe decibels?

**Comment by Coolthulhu** [comment]
I mean just for the explosives for now. Changing the entire volume system to a non-linear scale would take a while.

**Comment by Mooses2k** [comment]
Looking at Good First Issues. Does noise need to be decoupled from explosion power? Is that the desired solution? Making a specific variable for noise to deal with situations like low blast, high shrapnel things that should still be loud?

**Comment by kevingranade** [comment]
I don't think it needs to be decoupled per se as much as having the formula
adjusted to reflect the noise these items generate IRL.

The flashbang would still be a small explosion, but even small explosions
make a LOT of noise.
