### ISSUE TITLE
[Folding Parts Mod] Solar Panels Charge while Folded

### ISSUE THREAD

**Issue by Nioca** [CleverRaven/Cataclysm-DDA#20322]
`Experimental Build 0.C-6235 Windows 7 SDL`

Very minor mod bug here. If a vehicle with solar panels and a folding battery is folded, it will continue to charge while folded. Presumably whatever timer is checked when the vehicle is outside the reality bubble (in this case, by being folded) isn't being reset when the vehicle is unfolded, which causes the vehicle to act like you were simply away from it for a length of time and left to charge, rather than the vehicle actively being packed up. Note that this doesn't apply to engines in general; folding the vehicle turns the engine off, so you can't turn a folding vehicle with an engine on, then fold it back up and wait for it to charge.

**Comment by kevingranade** [comment]
Please take this up with the folding parts mod author, we don't support turning arbitrary vehicle parts into folding parts.
