### ISSUE TITLE
Explosive Charges Take Too Long to Activate

### ISSUE THREAD

**Issue by Nioca** [CleverRaven/Cataclysm-DDA#20325]
`Experimental Build 0.C-6235 Windows 7 SDL`

Activating explosive charges (Black Gunpowder Charge, ANFO Charge, RDX Charge) were apparently converted into a long action, but the explosives are activated and start counting down _at the beginning_ of the long action. The result is that Black Gunpowder and ANFO charges will actually go off in your face before you finish activating them, while RDX charges leave you a itty-bitty 4 turn grace period to get out of the blast radius. Suffice it to say, this turns using any of these explosive charges into an elaborate (and admittedly rather spectacular) way to commit suicide

**Comment by CoroNaut** [comment]
Roll: 0. While setting the time for the bomb, you accidentally press the red button.

**Comment by Coolthulhu** [comment]
Doesn't happen in current master.
