### ISSUE TITLE
Shouter/Screamer/Howler Insanely Loud, Deafens Player

### ISSUE THREAD

**Issue by Nioca** [CleverRaven/Cataclysm-DDA#20323]
`Experimental Build 0.C-6235 Windows 7 SDL`

Pretty much what it says on the tin. The Howler line of mutations produces sound volumes that are extremely excessive (Volumes 2000-4000, depending on how far along you are). When any one of these mutations activates, it'll actually deafen a player without hearing protection for a little under an hour; Howler in particular produces a blast of sound that rivals a mininuke going off. I've included a short list of comparison sounds below, although pretty much every sound I tried couldn't even compare to how loud these mutations are. Notably, there does seem to be a few points of variance when these mutations activate, but it's usually within about 10 points of the listed value.

Sound | Volume
----- | ------
9mm Gunshot (USP 9mm) | 80
Screecher Zombie | 119
.50BMG Gunshot (Barret M107A1) | 268
C-4 (Epicenter) | 650
Explosive Homemade Rocket (Epicenter) | 1496
Shouter | 2004
Screamer | 3006
ANFO Charge (Epicenter) | 4000
Howler | 4047
Mininuke (Epicenter) | 4500

**Comment by Coolthulhu** [comment]
Shouter doesn't actually increase noise - it only makes you shout occasionally.
Sounds like you tested it on a debug character with 1000 strength.

**Comment by Nioca** [comment]
That I was; I was running vehicle tests. Doing a very quick retest confirms that the problem was debug-based, and that at normal playing strength values, this isn't an issue (Worst case involves Howler rivaling a .50BMG shot, but that requires it triggering while Hydraulic Muscles is on).

At any rate, whoops. Didn't know that was strength based; sorry about that.
