### ISSUE TITLE
Minor bugs. Trees, jam sandwich, sock mitts.

### ISSUE THREAD

**Issue by Grelko** [CleverRaven/Cataclysm-DDA#20334]
Plum and Apricot trees show the fruit in summer, but you can't pick any. 

I wasn't sure if you should be able to harvest in summer, or if they shouldn't show fruit until Autumn.

Version 0C-21246-g07f24ad6cf

**Comment by Grelko** [comment]
Fruit jam shows "strawberry jam" or "blueberry jam" as components, All see is a recipe for "fruit jam" in general, not specific types. Unless it's possible to find specific types in stores?

If you make/have multiple pairs of socks, put one of them on and make "sock mitts",  the recipe uses the pair that you are wearing first, instead of any other pairs in your inventory.

**Comment by kolsurma** [comment]
>Fruit jam shows "strawberry jam" or "blueberry jam" as components, All see is a recipe for "fruit jam" in general, not specific types. Unless it's possible to find specific types in stores?

All the recipes I can that require a jam use fruit jam as an ingredient. 

>If you make/have multiple pairs of socks, put one of them on and make "sock mitts", the recipe uses the pair that you are wearing first, instead of any other pairs in your inventory.
>Edit - The same thing happens with "makeshift sling" and "rioter mask". There might be others that do this. Possibly making sleeveless items, shorts, etc.

Confirmed, good catch.

**Comment by Grelko** [comment]
Download 6254
Tiles
**Version 0.C-21246-g07f24ad6cf**  Just incase you didn't see it up top.

Windows XP SP3   <---  :)

I hope this explains it a bit better.

The actual recipe for "jam sandwich" shows the components "fruit jam, or strawberry jam or blueberry jam". I wondering if it's possible to specifically make strawberry or blueberry jam, since I didn't see either of them in the recipe book (My character has cooking 7). Or, are you able to find them in a grocery store etc?

If you aren't able to make "strawberry or blueberry jam" themselves, then those particular words in the recipe component list wouldn't need to be there, just "fruit jam".

It's no problem, I can post them separately next time. I just thought that if I had multiple small issues or bugs, that I could post them all in a group to save time and space on the forum. "if this is a forum?"

**Comment by keyspace** [comment]
`data/json/recipes/recipe_food.json` has `jam_(straw|blue)berries` listed as ingredients, but there is no crafting recipe for them.

`g -Er "jam_(straw|blue)berries" data` shows these specific items are still present in mapgen, item groups, etc.

Generic jam was added in commit 505ebf4708c1a55eb115ec48e442cd75ba9b3dea (part of PR #3521). The PR is huge (+1,039 −54).

Specific jam recipes were removed in bde1d9fa6885819c399b1219bcb6c755fb87a13f (part of PR  #11507). The items themselves were not removed since that would have "broken" save games - obsoletion was not imlemented yet AFAIK.

It is now.

**Comment by Grelko** [comment]
Thank you, that explains the jam sandwich recipe.
