### ISSUE TITLE
Electric scooter runs out of battery very fast

### ISSUE THREAD

**Issue by keyspace** [CleverRaven/Cataclysm-DDA#20339]
This is due to it having a `battery_motorbike`, which only has a `capacity` of `500`. `engine_electric` eats through that in no time.

A `medium_storage_battery` could be given to it instead. (EDIT: That has a `capacity` of 7000 - 14 times more.) However, it has a `weight` of `31000` (31 kg) - compare to `4000` (4 kg) of `battery_motorbike`. A 7.75 times increase.

The total for `scooter_electric` ATM without any battery is 30 kg, so replacing the battery like that will increase the mass twice.

With the current thrust system, that would have next to no effect: top speed falls from 97 km/h to 96 km/h, acceleration remains at 9 km/h/t.

On a fully-charged medium storage battery, the scooter would be able to make a trip of ~20-40 overmap tiles. Eventually, this should be tested as in #20007 - seemingly can't be applied ATM to electric vehicles.

Overarching issue: #17037

**Comment by 1skandar** [comment]
Hmm, as an alternative does downgrading to a small electric motor, or even two of them, give it any reasonable speed? That would also significantly reduce its weight. I mean, for an electric scooter even 20 or 30 mph would be reasonable.

**Comment by keyspace** [comment]
The issue is not power usage, it's low storage capacity. One small electric motor still drains a motorbike battery in two overmap tiles.

One small electric motor would give a safe/top speed of 19/25 km/h respectively, and acceleration of 1 km/h/t. Two - 29/41 km/h, and acceleration of 2 km/h/t. Mass is appropriately 26 and 28 kg.

Relying on a vehicle having two engines can also backfire: multiple engines are handled differently.

To be honest, an electric vehicle being "mostly battery" is not far-fetched.

Also, electric bicycle has a medium storage battery, and a small electric motor.

**Comment by 1skandar** [comment]
I'm thinking the power draw of electric motors might need to be adjusted. Test an electric car to see what I mean, even with 4 solar panels it still runs drains the battery at a crazy rate. I think the revert to the vehicle rebalance broke something.

**Comment by kevingranade** [comment]
No actual goal, if you have a criteria for correct behvior please feel free to supply it and re-open, but as it is there is no way to address this issue as there is no definition of "very fast".
