### ISSUE TITLE
Binding selected menu actions in global context

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20336]
For example, binding item action menu options for use without first opening the menu.
This could allow, for example:
* Binding a key to a specific martial art, so that you can instantly go judo to avoid getting tripped, then go back to krav maga next turn to fight back
* Binding bionic claws to one key instead of having to use 3 (menu->bionic->close)
* Binding "sew" item action as if it was a real action
* (If we get item IDs) Binding "wield that specific AK-74", "drink from that specific bottle" etc.

This would achieve the same goal as macros, but with own pros and cons.
Macros are "dumb" and require some skill to set up, but are more versatile.
Out-of-context binds would (ironically) be more context-aware (understand type IDs, renaming) and simple to set up, but limited to hardcoded behaviors.

But I'm not sure if it's worth the trouble, considering that:
* Most keys are used already. We'd have to enable F1-F12, alt-key combos and so on. I'm not sure if it's as simple as "just" enabling them.
* Each menu supported would have to be rewritten to consist of "context-bringing" function and on-select function.
* Per-character keybinds would have to be supported, because binding a key to a specific martial art or bionic type would most likely not be useful on a different character.

**Comment by bdgackle** [comment]
From the player's perspective, I like this idea.  It would be nice to bind sub-menu selections, and I think the subset of users that would make use of that is larger than the subset that would use macros.

I wonder, though, if we could avoid additional code complexity by using a macro system to simulate this idea.  In other words, when the player selects a sub-menu item to bind, we could auto-generate a macro that accomplishes this binding.  Then, we could still support more complex macros, but everything would share common code.

**Comment by kolsurma** [comment]
This should definitely wait till something is decided with #20251. There's too many issues with the current keymappings to introduce something new.

I, personally, would like to see this implemented and can see the use for these 'macro-lite' options. Having an offhand weapon that I could switch to without having to go through the wield (or inventory, or w/e) menu would be just lovely. Or a mapped 'grenade' button.

**Comment by Coolthulhu** [comment]
> I wonder, though, if we could avoid additional code complexity by using a macro system to simulate this idea.

The macro would have to be a "command macro" rather than "key macro" for this to actually be useful.
Say, instead of recording the macro as `std::string("E1")`, it would need to be `std::vector<macro_element>( { macro_element::action("ACTION_EAT"), macro_element::inventory::select(location::vehicle, 1) } )`.
Otherwise, if it only remembered the keys, it would be just a macro system and nothing else. That wouldn't be too useful in a game where a lot of keybinds are generated as game progresses.

**Comment by CoroNaut** [comment]
I like the idea of making it a macro. I know I would use it for taking a multivitamin every day. Instead of going into my inventory or going over to a pile of drugs to take a pill, perhaps the press of a key could tell me if I was able to eat it or if it was not in range (not in inventory or in 3x3). The use of macros could open up wider possibilities than direct keys.

**Comment by Coolthulhu** [comment]
> I know I would use it for taking a multivitamin every day.

That's doable without a giant macro system. Just create a named item action for it.
