### ISSUE TITLE
Suggestion: Some quick link in the vehicle gui for important parts

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#20348]
Right now when you pull up the vehicle gui it lists the critical information for the vehicle, how many tanks, what kind and how many batteries, the engine type. However, it doesn't tell you *where* those components are (nor, for that matter, what shape they are in, beyond (faulty) for engines).  It would be nice if one of those parts were selected it would take you to where on the vehicle it was located.

**Comment by Night-Pryanik** [comment]
Closing because of no discussion for a long time.
