### ISSUE TITLE
Game is advancing even if no action is chosen when activating items

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#20349]
- Get some activable item (knife, for example);
- Press 'A' to open the use menu;
- Choose your knife;
- In the next menu don't choose anything, press Esc;
- One turn passed.

Note that when trying to do the same trick using the action menu on %, time is not advancing.

Windows XP SP3, tiles, 0.C-6260.

**Comment by Grelko** [comment]
I've comfirmed different items doing this by activating, then hitting ESC (six times hitting each button, activate, ESC, activate, ESC...) to see how the game time passes.

I'm testing this as I type this out. (I'm a good hour "real time" from my camp, so I only have certain items that I can test until I get back.)

Suprisingly, same computer and version Win XP, SP3, tiles, download 6260 version **0.C-21270-gd34c7b510b**

6 seconds = 1 turn
Tested items

camp fire drill - turns = 3,3,3,3,3,3
frying pan - "heat up food" but having no food to heat - turns = 2,2,3,2,3,2
improvised lockpicks - no turns
lighter - no turns
crowbar - turns = 2,2,3,2,3,2
toolbox - turns = 6,6,6,6,6,6
back holster "no item on hand" - turns = 3,3,3,3,3,3
large quiver - turns = 3,4,3,4,4,3
binoculars "no sunlight" - turns = 1,1,1,1,1,1
hemostatic powder - no turns
first aid kit - turns = 0,1,0,1,1,0
bandage - no turns
steak knife - turns = 0,1,1,0,1,0

**Comment by Coolthulhu** [comment]
Found the reason:
`game::use` uses `item_location::obtain`, which uses moves. This is obviously incorrect, as the move cost should only be deducted in `invoke_item` (if at all). Otherwise only this very specific use will consume moves.
