### ISSUE TITLE
Sloppy joe recipe

### ISSUE THREAD

**Issue by Grelko** [CleverRaven/Cataclysm-DDA#20353]
Sloppy joe recipe says that you can use canned chicken "works properly". 

The flavor text says "ground beef" and "onion", but nothing about chicken.

There is no onion in the component list.

**Comment by WizardOfOoo** [comment]
Would changing the description to include chicken work?

Maybe something like
`A sandwich, consisting ground or shredded meat and tomato sauce served on a hamburger bun.`

**Comment by Grelko** [comment]
I was thinking that a sloppy joe is basically groud meat, sauce and seasoning. You wouldn't actually need the onion, since it could be hard to find, but perhaps "seasoned salt" for the flavoring.

You could switch the flavor text to - A sandwich, consisting of "ground meat", tomato sauce and flavoring, on a hamburger bun.

Doing it that way, would include chicken, since it doesn't specify which type of meat is used. The "seasoned salt" would imply flavoring, without the need for onions.

If you went the route of "shredded meat", you always add more recipes like "pulled pork" or "ham barbeque" sandwiches also, using "ham or pork sticks" for the meat. You would need to add a separate recipe to actually make the pork sticks. As for getting the pork itself, I'm not sure, maybe  "canned ham"?
