### ISSUE TITLE
Tailoring now wants thread to be in inventory, not loaded into needle

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#20358]
As of the last build: http://ci.narc.ro/view/Cataclysm-DDA/job/Cataclysm-Matrix/6263/changes , tailoring recipes seem to expect the thread to be in inventory, not loaded into the needle.

**Comment by DangerNoodle** [comment]
This was result of pull request https://github.com/CleverRaven/Cataclysm-DDA/pull/20270, an imcomplete rework of sewing kit behavior.

It would have been more desirable for the recipe change to acknowledge charges of the sewing tool as an alternative to having thread as a component, but the recipe framework offers no easy way to make "charges of tool *or* component" a valid option.

I assume that the unlikely event of completing this change by allowing repairs to also use thread in inventory would obsolete this issue, but I can not see this being easily to implement.

**Comment by Coolthulhu** [comment]
> I assume that the unlikely event of completing this change by allowing repairs to also use thread in inventory would obsolete this issue, but I can not see this being easily to implement.

It's not actually that hard, but would be slow with current system.

**Comment by ZhilkinSerg** [comment]
I'm slowly working on changing thread requirement for textile repair and modification. There are will be no charges in sewing tools - threads from inventory will be used instead.

**Comment by Grelko** [comment]
@ **ZhilkinSerg**

_There are will be no charges in sewing tools_

I like this idea. It's not a "sewing machine", so you don't actually need to load any bobbins with thread before sewing an item. Just get the needle & thread and go for it. Same with knitting needles etc.

**Comment by kevingranade** [comment]
AFAICT there's no issue here, this is working as intended, just a change.
