### ISSUE TITLE
semiautomatic pistol "out of ammo"

### ISSUE THREAD

**Issue by Grelko** [CleverRaven/Cataclysm-DDA#20352]
If you have a semiautomatic pistol, with a full "15" magazine in it and try to "reload", it says you are out of ammo! I have plenty that will fit in the gun.

If you have another magazine "of the proper type" nearby, it will let you choose that even if it's empty. "works correctly"

**Comment by kolsurma** [comment]
That happens with many ranged weapons currently, probably a bad check somewhere in the reload code.

**Comment by HotSake** [comment]
Could be a generic failure to reload message caused by the magazine already being full. Because you can't reload the magazine itself, and can't reload the gun with another magazine, the reload action fails with an overly specific default message.

**Comment by kevingranade** [comment]
Maybe we can add what the system is trying to do to the error message.

"Tried to load 9mm rounds into a spare magazine, but couldn't find any
rounds."

**Comment by kolsurma** [comment]
> "Tried to load 9mm rounds into a spare magazine, but couldn't find any
rounds."

Unfortunately what it's doing now is:

- you have no magazines in your inventory 
- magazine loaded into the weapon
  - it's fully loaded
- Fail to find ammo for non-existent magazine.

So it's more like "Could not find spare magazine to load %s into."

**Comment by kevingranade** [comment]
In that case it should just say something like, "nothing to reload".

**Comment by Grelko** [comment]
What about "extra magazine not found" or "Cannot reload magazine, while still inside gun."

**Comment by Grelko** [comment]
Semiautomatic pistol - 15 bullet "pistol magazine" not the extended one.

It takes 0-6 seconds to remove a magazine from the gun.
It takes either 1:18 or, 1:24 to reload a magazine with bullets.
It takes 6-12 seconds to place a magazine into the gun if it has no magazine to begin with.

It takes 1:24 to reload bullets into the magazine, while it is still inside the gun.

It takes 6 seconds to switch to a different magazine. (dropping the first clip on the floor is 0 moves)

You cannot place bullets directly into this particular gun, if it has no magazine in it.


I'm not sure why it takes "this or that" amount of time to do certain things. It might deal with the issue about "activating" items and hitting ESC to cancel it? Issue #20349

Unless it could also be caused by your character being full, hungry, starving, tired etc.
