### ISSUE TITLE
Filthy ingredients combine to form clean cloths 

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#20356]
Now that there is a new feature that has filthy clothes dissemble into filthy rags/patches/etc, it would seem to make sense that creating cloths from those ingredients would create filthy clothing, but it doesn't

**Comment by Night-Pryanik** [comment]
It doesn't implemented yet.

**Comment by DangerNoodle** [comment]
Tested with or without the filthy clothing mod enabled? This is indicative of the fact that items are better off not displaying as filthy without the feature enabled.
