### ISSUE TITLE
Pocket watch materials

### ISSUE THREAD

**Issue by Grelko** [CleverRaven/Cataclysm-DDA#20354]
Pocket watch materials show Glass and Gold.

Where's the glass and gold?

When you examine the watch, it shows Scrap metal (2) and 1 clockworks if you dissassemble it, but nothing about glass or gold.

Edit - reworded the sentence.

**Comment by Night-Pryanik** [comment]
Both glass and gold are too small to be salvaged with disassemble.

**Comment by Eddyskingdom** [comment]
den ad in scrap gold and broken glass to it if you dissassemble it

**Comment by Night-Pryanik** [comment]
We don't have scrap gold item. And you don't necessarily break glass when disassembling it, and we don't have "small round glass" item either.

**Comment by Reclusive-reptile** [comment]
We do, however, have a highly granular gold_small item that is counted by charges of ~5 grams. Adding a few charges of gold to the deconstruction recipe would be trivial, although it would also be trifling.

**Comment by WizardOfOoo** [comment]
Modern gold pocket watches don't have a lot of gold in them.  Vintage gold watches might be solid gold.  It's a big difference in gold amount.  Vintage watches are in short supply with gold prices being so high the last few years.

**Comment by Grelko** [comment]
There's actually quite a lot of items like this. Solar panels for example, say "material - Glass" but you can't recover any.

The flavor text "old fashioned" doesn't tell you if the watch is actually old or new.

What about - An old fashioned pocket watch. This one tells you the time and looks good doing it, too bad the gold isn't real. 

Maybe this watch is a cheap knock off, just like the flavor text for the "fake" cutlass.

It could "say" that it's gold but you wouldn't get any from it. Or, you could have it give 1-5 gold from dissassembling it, but I don't how hard that would be to add.

Switch the dissassembled items to 1 "scrap glass", 1 scrap metal and 1 clockwork? 

As for the small piece of glass, if you switched "broken glass" to "scrap glass", it doesn't specify if a particular piece of glass is broken or not, even if it is a small piece from a broken window, glass bowl, watch etc.

**Comment by kevingranade** [comment]
This is a non-issue, the referenced materials are unrecoverable, and intended to be unrecoverable.
