### ISSUE TITLE
"Loaded bad ter! ter school_x" bug

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#20355]
Version: 0.C-21360-gce2f17364f (tiles)
Build: 6263
OS: Windows 7 Professional x64 SP1
Save file: https://mega.nz/#!tpIh1bLR!TQ_c76iUW13wbt2-RrkRgtu6Vrqvi-gkuunr5w2Fbv4

Loaded bad ter! ter school_x
x = 1-9
I get a debug screen for 1 through 9.

I'm guessing 1 to 9 represent the map tiles of a 3x3 school.
School map "tiles" characters are all now switched to "%" and when selected their description is "% nothing".

I get the debug screen while loading the game and the first time I open the map in-game.
As far as I know this bug started with build 6263 to 6261.

<a href='https://postimg.org/image/pd9pm7kpp/' target='_blank'><img src='https://s6.postimg.org/7zzf7cpep/Loaded_bad_ter_debug.jpg' border='0' alt="Loaded bad ter! debug"/></a><br/><br/>
<a href='https://postimg.org/image/hykdttyu5/' target='_blank'><img src='https://s6.postimg.org/819d0rr8h/Loaded_bad_ter.jpg' border='0' alt="Loaded bad ter!"/></a><br/><br/>

**Comment by ZhilkinSerg** [comment]
I guess that is due to bad compatibility code in savegame.cpp in #20304.

Can you please provide a save game?

**Comment by Nhatorama** [comment]
Just uploaded the save game

**Comment by AMurkin** [comment]
Same messages after update from 6260 to 6263.

**Comment by Coolthulhu** [comment]
Reverted at the moment.
