### ISSUE TITLE
old geard mission finding the traider fond him all NPC of the old geard go hostile to player

### ISSUE THREAD

**Issue by Eddyskingdom** [CleverRaven/Cataclysm-DDA#20369]
i was doing one of the mission of the old geard to find the traider i fond him and i treatend him to say dat he is a traider only wen he sayd dat he was all NPC wen't hostile and ending me

**Comment by Taberone** [comment]
Doing the Old Guard mission to find the traitor will result in the entire Refugee Center turning hostile and gunning you down in the blink of an eye if you talk to the traitor (It's always the new guy that spawns in the room full of storage racks) and pick "Got something to hide" or "Get bent, traitor!" as a dialogue option too many times.
