### ISSUE TITLE
Horde movement broken, way too slow and can't properly move into bubble

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20363]
Hordes will set interest properly, but then pretty much ignore it.
Their movement seems incredibly slow, as if only some hordes were capable of movement at all (not related to interest).
Hordes that should enter bubble either disappear or are somehow prevented from spawning. No messages on debug screen.

Log file is filled with
```
GROUP_ZOMBIE: invalid population here: -1.11665e-016
```

Though the above log spam seems to be safe, as it looks like it should happen at edges of a diffuse monster group and have no ill effects (it is later clamped to 0).

**Comment by RenechCDDA** [comment]
Sometime in the last 7 years these have been resolved. Likely due to hordes being completely overhauled between then and now.
