### ISSUE TITLE
Boiled stomach (old)

### ISSUE THREAD

**Issue by Grelko** [CleverRaven/Cataclysm-DDA#20365]
I had a stomach (not fresh, just normal) and a stomach "old". Batch cooked them, and ended up with 2 boiled stomach (hot).

I kept them in a "turned on" minifridge for approximately 7 hours while my character slept, if that would matter.

It shouldn't be hard to re-test this, but I don't have anymore stomachs to cook at the moment. I will update this in a few minutes.

**Comment by Night-Pryanik** [comment]
And what is the issue?

**Comment by Coolthulhu** [comment]
I think the bug is supposed to be that averaging food rot age can un-rot food items.

**Comment by Night-Pryanik** [comment]
I suppose author wanted to say 
> and ended up with 2 boiled stomach (old)

instead of 

> and ended up with 2 boiled stomach (hot).

**Comment by Grelko** [comment]
Sorry it took a while for me to write back.

It wasn't 2 boiled stomach (old), I ended up with 2 boiled stomach (hot). I haven't been able to play lately, so I wasn't able to see if I could reproduce this as of yet.

Yes, it would be averaging food un-rot for batch cooking.

As soon as I'm able to retest this, I'll have an update.

**Comment by kevingranade** [comment]
Not a bug, if you cook old ingredients, the result is still fresh.
