### ISSUE TITLE
Vehicle Cache error

### ISSUE THREAD

**Issue by Reclusive-reptile** [CleverRaven/Cataclysm-DDA#20374]
![veh_error](https://cloud.githubusercontent.com/assets/20874173/23324112/ef2e6dc8-fab9-11e6-92d5-10a3cf96fa83.png)

cataclysmdda-0.C-6264 (tiles)
windows 10 64-bit
Seems to happen when ever a vehicle enters the reality bubble.

**Comment by Coolthulhu** [comment]
Can't reproduce, need more details.

**Comment by Reclusive-reptile** [comment]
If I am dragging a vehicle such as a shopping cart or swivel chair and attempt to craft or perform a long action like searching under brush I get the above error. The tripoint seems to be random (it will loop through several different numbers) and the error is one of those annoying inconsistent ones that are always hard to debug/recreate.

**Comment by Coolthulhu** [comment]
Had this happen in a game.
I noticed that the tripoint isn't exactly random - what is important is that it is an out of bounds one.
`vehicle_at_internal` should not be called with an out of bounds argument.

I didn't debug it, but I suspect `valid_move` - it assumes that we're moving from a valid, inbounds tile.
If this is the case, it means we have a bigger problem - it would imply that out of bounds creatures not just exist, but try to act and move.

**Comment by BevapDin** [comment]
For some reason the loop in `game::monmove` (that calls `despawn_monster` when they are out of bounds) uses a different out-of-bounds check:
```C++
        if( critter.posx() < 0 - ( SEEX * MAPSIZE ) / 6 ||
            critter.posy() < 0 - ( SEEY * MAPSIZE ) / 6 ||
            critter.posx() > ( SEEX * MAPSIZE * 7 ) / 6 ||
            critter.posy() > ( SEEY * MAPSIZE * 7 ) / 6 ) {
            despawn_monster( i );
```
This keeps monsters with `posx() == -1` active. This can be tracked back to first commit.

The check after shifting npcs seems to have the same flaw.
