### ISSUE TITLE
为什么薄钢板无法制作了？测试版的漏洞吗？

### ISSUE THREAD

**Issue by guangyuanxing** [CleverRaven/Cataclysm-DDA#20378]
我在测试版开了个满技能的号，然后在制作列表搜索了薄钢板的制作，结果只有什么接线薄钢板的制作项目，薄钢板的制作选项完全没有。（近期下载的5个测试版都是这样）
有没有国人或者懂中文的友人能解答下？谢谢了！（最好能通知下作者！！！）

**Comment by Zireael07** [comment]
Please use English in this repo.

That said, summoning @BrettDong for help

**Comment by kevingranade** [comment]
Google translate says:
> I opened a full number of skills in the beta version, and then in the
production of a list of the production of thin steel plate, the results
only what the production of thin wire plate production projects, thin steel
production options completely. (The recent download of the five test
versions are like this) There are no people or Chinese friends can
understand the next? Thank you! (It is best to inform the next author !!!)

Which is something about requirements of crafting steel plate, not enough
detail to work on though.

**Comment by BrettDong** [comment]
@guangyuanxing 这里大多是外国人，有美国人，有波兰人，有英国人，有德国人，为了交流顺畅最好还是用英语发帖。

> 我在测试版开了个满技能的号，然后在制作列表搜索了薄钢板的制作，结果只有什么接线薄钢板的制作项目，薄钢板的制作选项完全没有。（近期下载的5个测试版都是这样）
有没有国人或者懂中文的友人能解答下？谢谢了！（最好能通知下作者！！！）

> I created a new character with full skills in the experimental version, and searched "sheet metal" in the crafting menu, but there was only "wired sheet metal".

The recipe for "sheet metal" has been removed a long time ago. This issue can be closed.

**Comment by guangyuanxing** [comment]
I See,My English is not so good ， thank you!

**Comment by guangyuanxing** [comment]
我只是无聊下开了个零城镇零丧尸的野外生活模式，结果发现做不出薄钢板。。。所以才跑这边来问问。至于英文。。。表示现在就是小学的英语试卷摆在我面前，都不一定能拿到及格分了 ┭┮﹏┭┮不过还是谢谢你的回答了 @BrettDong

**Comment by BrettDong** [comment]
@guangyuanxing 这个地方最好用英语，如果要用中文问问题，可以去[百度贴吧](tieba.baidu.com/cataclysmdda)、[3DM论坛](http://bbs.3dmgame.com/forum-1161-1.html)或者QQ群183821419、227053480。其他人如果想要阅读你的问题，只能用谷歌翻译Google Translate看，翻译出来的东西都走样了。

**Comment by guangyuanxing** [comment]
明白了，群已加，无限感激！！！@BrettDong
