### ISSUE TITLE
Debug msg: assignment does not update value

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#20388]
updated 6272 -> 6275
on world load (even after 'save and exit' and load again)
![-1](https://cloud.githubusercontent.com/assets/1931904/23341705/a4cb6f9c-fc5d-11e6-840a-7d06a45a49a2.png)
![-2](https://cloud.githubusercontent.com/assets/1931904/23341706/a650fbb6-fc5d-11e6-8636-b7aa547be33e.png)
![-3](https://cloud.githubusercontent.com/assets/1931904/23341707/a77ef894-fc5d-11e6-9f49-8278e287a0f3.png)

**Comment by codemime** [comment]
Those are obsolete items.
