### ISSUE TITLE
Forbid direct installation of moster-dropped CBMs and add install kits for them

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#20383]
As far as I can see, CBMs are a _kits_ with all that one might need to do surgery and install bionics into its own body (tools, antiseptics, maybe manuals). It seems that these kits are so advanced and complicated that allow for installation of bionics for even a complete noob in anatomy, surgery and so on (with a huge chance to fail, but nevertheless).
On the other hand, bionics that one can salvage from monsters are just _pieces of electronics_ that one have separated from monster's body. I have big doubt that one can install these bionics without proper tools from a kit.
Maybe make all these monster-drop-bionics uninstallable like burnt-out bionics, and one need to do some high-tech magic through crafting to make them installable again?

**Comment by Coolthulhu** [comment]
Bionics are a pretty important part of the game. Just disabling the drops like that would rid the game of an important part of it. Especially if they were only unlocked by late-game crafting, which handles mutagens.

Would be better if installation kits for them weren't craftable, but were semi-common. For example, expected count of 5 kits per hospital, 2 per clinic and 1 per electronic shop etc.
Or were craftable, but expensive and still better acquired through drops.

Some bionics could come with integrated kits that can't be used for anything else. For example, the useless crap like integrated clock. Otherwise no one would waste a kit on those.
Alternatively, big bionics could require more than one kit to install.

Regardless, this change shouldn't land before 0.D. It would be a major change that we wouldn't have the time to test it correctly.

**Comment by Night-Pryanik** [comment]
> Especially if they were only unlocked by late-game crafting, which handles mutagens.

Not only crafting.

> Would be better if installation kits for them weren't craftable, but were semi-common.

Even now they can be found in labs and electronic shops.

>Regardless, this change shouldn't land before 0.D. 

Fully agree, just wanted to know opinions.

**Comment by Coolthulhu** [comment]
> Even now they can be found in labs and electronic shops.

I mean the kits to turn extracted bionics into installable ones.

**Comment by DangerNoodle** [comment]
My assumption was there is a good reason why burnt-out bionics are an important part of crafting new CBMs It would be reasonable to assume that at least some of the tools need to implant them are integral to the bionic itself. The same reason why they can be removed using the same skill set as installation, with only the addition of a cutting tool and a first aid kit.

Or it could be purely an abstraction for gameplay reasons, which is fine. We do not need dropped bionics being removed for pointless realism when one can think up flavor explanations for it, nor do we need it when removing them adds nothing of value to gameplay.

**Comment by Night-Pryanik** [comment]
> We do not need dropped bionics being removed for pointless realism when one can think up flavor explanations for it

Speak for yourself. Maybe it's only you who consider this kind of realism "pointless".

**Comment by kevingranade** [comment]
There has been discussion of requiring install kits for harvested cbms,
which is a great idea. That requires deciding where to spawn the
installation kits and perhaps making a crafting recipe for them, basically
some medical gear.

We'd probably treat dropped cbms more or less the same as harvested ones.
Only the ones in labs or vaults would cone with installation kits.

**Comment by Noctifer-de-Mortem** [comment]
I think having a crafting recipe with an installation kit to create the cmb. Example, You butcher a zombie for a Integrated Toolset bionic, now once you find the installation kit you craft the Integrated Toolset CMB ready for install.

This way you simply need to a add a harvested bionic item for each cbm and installation kit item, make monsters drop the bionic instead of cmbs when butchered and then make crafting recipes for the bionic+installation kit. This can be mostly done by pure json edits. The only changes to code would the the bionic monster flags to drop the bionics instead of the cbms. Am I correct with this?

Things like power storage should not need a kit and should be able to be installed after being butcher.

Bonus: How about butchered bionics be dirty if using the filthy mod? This would require the bionics to be disinfected before installing the kit.

**Comment by DangerNoodle** [comment]
I was almost going to suggest, jokingly, that bionics harvested from enemies should be filthy.

> Speak for yourself. Maybe it's only you who consider this kind of realism "pointless".

You do not need to be so rude in response to that. I do at least agree that if the feature is implemented, having separate installation systems used to produce bionics might at least contribute more to game balance than completing removing the bionic harvesting.

**Comment by kevingranade** [comment]
> I think having a crafting recipe with an installation kit to create the cmb. Example, You butcher a zombie for a Integrated Toolset bionic, now once you find the installation kit you craft the Integrated Toolset CMB ready for install.

It would be FAR simpler to add an installation kit requirement to the action of installing a CBM than to create ~100 new items and crafting recipes, and to require every contributor that adds new CBMs to also create an essentially identical install kit and crafting recipe.

The only way this makes sense is if every CBM had different requirements for installation, and even then it would be simpler to create a number (almost certainly far less than the number of CBMs) of install kits and annotate the CBMs with which one it requires.

> This way you simply need to a add a harvested bionic item for each cbm and installation kit item, make monsters drop the bionic instead of cmbs when butchered and then make crafting recipes for the bionic+installation kit. This can be mostly done by pure json edits. The only changes to code would the the bionic monster flags to drop the bionics instead of the cbms. Am I correct with this?

This would work, but that's about 100x as much work as just adding the install kit, crafting recipe for the install kit, and code to make it happen.

> Things like power storage should not need a kit and should be able to be installed after being butcher.

Why make exceptions? What's the benefit?

> Bonus: How about butchered bionics be dirty if using the filthy mod? This would require the bionics to be disinfected before installing the kit.

Meh, don't care one way or the other, could easily be abstracted away by saying the install kit has the necessary antiseptics.

**Comment by Noctifer-de-Mortem** [comment]
> Why make exceptions? What's the benefit?

I think coolthulhu put it best:

> Some bionics could come with integrated kits that can't be used for anything else. For example, the useless crap like integrated clock. Otherwise no one would waste a kit on those.

I also think power storage should have its integrated installation kit since it is like plugging in a battery.

**Comment by Coolthulhu** [comment]
> Why make exceptions? What's the benefit?

For balance reasons.
But we could explain it with "realism" as the fact that they have different sizes and complexities and replacing an arm with megaman cannon is not the same thing as planting an armor plate under skin of a limb.

Whatever reason we use, it's best to avoid having any useless crap bloating the lists but not being installed ever.

I wouldn't give power storage the free install, though. I'd rather see it as the primary consumer of kits, at least until we actually figure out how to limit the infinite bionic power bullshit.

**Comment by Night-Pryanik** [comment]
> You do not need to be so rude in response to that. I do at least agree that if the feature is implemented, having separate installation systems used to produce bionics might at least contribute more to game balance than completing removing the bionic harvesting.

What was rude in my words? 

And in case you didn't noticed, I suggested alternative to complete removing of harvested cbms too. The last paragraph of the post. Maybe I should change the title of the post to reflect that.

**Comment by kevingranade** [comment]
No matter the functionality, all cbms are surgically implanted.  If we're
rationalizing their drops by effectively removing the surgical installation
kit from the harvested version, there is no sensical rationale for not
applying that to all if them.  If it means that in practice certain cbms
are "never" installed, that's perfectly fine. They still wouldn't be
"useless", since they would be a source of high tech parts.

**Comment by Zireael07** [comment]
1) IIRC we already had this discussion more than once?
2) Maybe it's better to move this discussion to the forums?

**Comment by glenmack** [comment]
As a player i'm not opposed to CBM install kits, they make sense and as Kevin said, it would be easier to add the requirement for one, than hundreds of recipes.

Having said that, the implementation of 2 or 3 kits, that are tools and do not get used up in the installation process, that need to be charges seem like a better idea.

The kits could be tied to difficulty of CBM installation, simple/intermediate/advanced, be progressively rarer and be charged with increasingly difficult stuff, asprin/disinfectant/hemostatic powder?

**Comment by kevingranade** [comment]
Installaton kits that aren't consumable are pretty pointless, they would just act as a barriers to installation until you found one, then wouldn't discourage further installations at all.

**Comment by glenmack** [comment]
> Installaton kits that aren't consumable are pretty pointless, they would just act as a barriers to installation until you found one, then wouldn't discourage further installations at all.

To be fair, we already have the incoming slot limit, the risk of severe injury and the high bar of Int. and skills as a barrier to discourage installation. While installation kits that aren't consumables may seem "pointless" from a game-play perspective, a bunch of generic (because you want only 1 type of installation kit) surgical tools that cannot be re-used make no sense in a world where scalpels are still made out of steel.

**Comment by DangerNoodle** [comment]
That would rather obviously make sense from a realism standpoint as well. What could feasibly even be in an installation kit that would be single-use? Tools can be sterilized, local anesthetics and sutures can be replaced.

The only justification would be if the kit itself had some form of malicious design built in either via software (ZAPM-style digitial rights management, as used in the game equivalent of scrolls?) or via batteries designed to not be replaceable.

**Comment by glenmack** [comment]
> The only justification would be if the kit itself had some form of malicious design built in either via software (ZAPM-style digitial rights management, as used in the game equivalent of scrolls?) or via batteries designed to not be replaceable.

Or instead of installation kits, there was a CVD style machine, maybe in labs and hospitals, expressly used for the installation of CBMs?

**Comment by DangerNoodle** [comment]
That would make bionic installation a very fragile state, just as with crafting diamond weapons.

It might be better if installation kits were simply reusable but consumed some resource that is uncommon but doe not require combing specific individual locations for it, such as plutonium cells. A few of the bionics require those to craft already, establishing the cells as the preferred form of power for long-term use.

**Comment by glenmack** [comment]
> It might be better if installation kits were simply reusable but consumed some resource that is uncommon but doe not require combing specific individual locations for it, such as plutonium cells. A few of the bionics require those to craft already, establishing the cells as the preferred form of power for long-term use.

Makes a lot of sense. Keeps thing in theme, I like it.

**Comment by Coolthulhu** [comment]
> What could feasibly even be in an installation kit that would be single-use?

Nanomachines
Would explain why is this stuff so easy to install

**Comment by glenmack** [comment]
> Nanomachines
Would explain why is this stuff so easy to install

Would that make the the Repair Nanobots CBM replace the need for an installation kit?

**Comment by Coolthulhu** [comment]
No, because repair machines repair human body and aren't programmed to install CBMs.

**Comment by DangerNoodle** [comment]
> Nanomachines
> Would explain why is this stuff so easy to install

That might explain it, though I had assumed that nanomachines were limited in application to the repair CBM at present, given no other mention I am aware of in the lore or in-game.

I also found it hard not to think of the "Nanomachines, son." meme when I read that.

**Comment by Coolthulhu** [comment]
> I had assumed that nanomachines were limited in application to the repair CBM at present, given no other mention I am aware of in the lore or in-game.

They aren't mentioned in the lore yet, but neither is a CBM install kit.
> I also found it hard not to think of the "Nanomachines, son." meme when I read that.

It was meant mostly as in Kojima's brand of handwave.
Basically, magic and weird shit is happening? It's nanomachines, I ain't gotta explain shit.

**Comment by DangerNoodle** [comment]
> It was meant mostly as in Kojima's brand of handwave.

That would however be the most notable example of such, which did provoke amusement when I read that.

Regardless, it is understandable. I am however wondering about the relative merits of disposable installation kits versus reusable ones that require plutonium cells.

**Comment by glenmack** [comment]
> I am however wondering about the relative merits of disposable installation kits versus reusable ones that require plutonium cells.

Here's how I would frame it.

CBM installation kit:
A self contained device, powered by plutonium cells. Requires you to insert the CBM you wish to install, where it will scan it and determine the correct routine to perform the installation. Completely expanded, it provides a large enough surface for you to lie down on, and uses the power and radiation from it's plutonium batteries to sterilise and clean its many dangerous cutting implements, as well as power several golf ball sized robots that perform various tasks.

Would also justify making it a very big and bulky object, meaning no more popping in CBM's on the go as you find them.

**Comment by Coolthulhu** [comment]
> Would also justify making it a very big and bulky object, meaning no more popping in CBM's on the go as you find them.

No reason to require hauling CBMs back to base. If we need a downside to installation, it would be better to have it take time, not hauling. Hauling is already tedious enough as it is.

**Comment by kolsurma** [comment]
Question: are these kits going to change the percentage change of install failure?

What could be done is if you use the kit you have a near 100% chance of success not using the kit would dramatically lower (but not prevent) success. 

If they're a requirement to install CBMs will be gated off until you find one.

**Comment by Coolthulhu** [comment]
> If they're a requirement to install CBMs will be gated off until you find one.

That's a pretty important argument for disposable kits as opposed to reusable.
We could have both, but then the refillable ones would defeat the whole point, unless the cost of using them was so high that it would often be better to burn a disposable one instead of the fuel for reusable.

**Comment by kevingranade** [comment]
The kit I was envisioning:
CBM programmer: not consumed, might require finding in labs or other CBM
drop locations, might have multiple versions or quality levels.

Surgical tools: standard tools, findable in various locations, require
sterilization, dirtied by use.

Surgical consumables: a laundry list of single use items for surgery;
gauze, antibiotics, painkillers, antiseptics, dropcloths.

The first item presents a single-time gate, once you have one you're done.
The second group requires some sophisticated tooling OR finding fresh kits,
so early game it's scavenging based, later it would become unlimited. The
consumables represent a fixed cost each time you install or remove a CBM,
no matter how late game you are.

**Comment by Adevald** [comment]
There is some idea about how bionic can be ejected from a zombie. We can create some universal components (like piles of nanowires, carbon details) some new tools and structures in science labs and research centers (just add new tool properties like 3d printing or micromanipulators) and for every bionic (with some excepions) raw components. Its just some bionics that you can eject without break it.

 there is some examples (CBM -  raw component):

Battery System CBM - force battery unload unit
Anti-Glare Compensators CBM - active lenses kit
Alloy Plating(all parts) - alloy plates set
Air Filtration System CBM - internal bionic air filters
All neural processors(like. Active Defense System, Cerebral Booster, Remote Controller and etc.) will be use same part, like bionic cerebral micropocessor. Also for crafting we need USB flash drive with nessesary software.

Im really interested in realization, and can help with jsonizing of raw components, if this idea make sense

**Comment by kevingranade** [comment]
I'm not understanding what you're suggesting, but I'm pretty sure it's not what was being discussed in this issue.
If you are suggesting making CBMs craftable, forget about it, that's not returning.
If your idea is something else, please explain it in a new issue.

**Comment by Adevald** [comment]
@kevingranade sorry for dumb explaining. I try to do it again.
TECHNICALLY its crafting. but on the part of logic you just eject already installed bionic from the zombie, prepare it for installing (using some advaned machines) and pack it into ready-to-use standart CBM. I understand that creating something complex like bionics in hand-craft condition its really unrealistic, but if you have some big knowledge and skills, you can extract bionics from dead corpses, and turn it from own use.

If you think that idea is crafting in your opinion to, i forget about it. But if not, im create new issue, and try to explain it more in detail.

**Comment by kevingranade** [comment]
I see, you're suggesting we have a way to craft the installation packaging since we now have almost all CBMs installed via autodoc.

That's fine, but I think it needs to be in a new issue, the concept has drifted pretty far away from this one.

**Comment by kevingranade** [comment]
This has been supplanted by using autodocs for installation.

**Comment by Night-Pryanik** [comment]
In fact, it's not. We still can cut CBMs out of zombies and install them right away without any sterilization or any other necessary preparatory operations.

**Comment by kevingranade** [comment]
That's what I mean by supplanted, you presumably just feed it to the autodocvand it handles the rest.
If you're still interested in following up on this I'm fine to reopen it, though I think things have shifted slightly since the ad autodoc addition.

**Comment by Night-Pryanik** [comment]
> you presumably just feed it to the autodoc and it handles the rest.

I'm fine with this, but I think we just need to supply autodoc with some serious disinfectants first.

Also I believe it's not always possible to cut bionics out of the corpse in state that allows it to be re-installed in someone else, but I'm not sure if it's belong to this issue.
