### ISSUE TITLE
Using towels to clean up boomer bile does not create a filthy towel

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#20392]
The resulting towel is not even considered wet, let alone unusable.

**Comment by Night-Pryanik** [comment]
Should be reopened?

**Comment by Night-Pryanik** [comment]
We can either close this issue, as soiled is analog to filthy and working in both clean and filthy worlds,
or we can revert reverting #20634 and force to show `(filthy)` for towels even in clean worlds, as, again, soiled is analog to filthy.

**Comment by Coolthulhu** [comment]
> revert reverting #20546 and force to show (filthy) for towels even in clean worlds, as, again, soiled is analog to filthy

Re-PR it with the fixes or PR the fixes first.
The force-show should not depend on id, though. Should be a flag like "ALWAYS_SHOW_FILTHY" or some other generic solution that will also be usable for any future kinds of dirt (for example, not allowing filthy rags for bleeding).

**Comment by Night-Pryanik** [comment]
Now that I thought about it, there is something incorrect in having filthy items in clean worlds. It's half-measures. I foresee posts like "I turned off filthy mod in my world, but there are filthy items anyway!"
