### ISSUE TITLE
Add in game support to save at any moment and reload any given save file (save scumming)

### ISSUE THREAD

**Issue by cirosantilli** [CleverRaven/Cataclysm-DDA#20405]
This game is great, but I also have a life :-)

**Comment by kolsurma** [comment]
You can already. Quicksave and backup your save file.

**Comment by HotSake** [comment]
> You can already. Quicksave and backup your save file.

Not the same thing. That requires switching away from the game after every save, locating the save file, and copying it somewhere so it isn't deleted on death. OP is asking for a standard save system like any other modern game. Multiple save slots per character, saves persist on death, UI support for saving/loading anywhere/any time.

**Comment by DangerNoodle** [comment]
Is it that complicated to simply close the game while at the "do you wish to see your last moments" screen? It causes far less anomalies than earlier versions, when the game lacked that prompt.

**Comment by HotSake** [comment]
*shrug* I dunno, just clarifying what I believe the OP is looking for. Personally, I use [the launcher](https://github.com/remyroy/CDDA-Game-Launcher/releases), so save scumming is sort of built in with the automatic backup system.

**Comment by Moumix3** [comment]
According to [this post from December 2016](http://smf.cataclysmdda.com/index.php?topic=10444.msg244402#msg244402), savescumming is not something they want to facilitate.

> 'Fixing' savescumming (in either direction): no.
> People periodically point out places where savescumming breaks some part of the game, and likewise people point out "savescumming features" they want in the game.  The answer to both is no.
> If you encounter a bug while savescumming, you need to reproduce it without the savescumming.
> Savescumming is not a normal part of the game, and I have no intention of ever adding features that facilitate it, like auto-backup of saves, tracking multiple saves, or the like.
