### ISSUE TITLE
boarding up half-smashed window results in fixed window instead of boarded up

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#20400]
Via email:
> If you board up a window that is only half smashed you don't get the boarded up graphic once you're done, the window just appears to be fixed with no boards, still blocks out light and such though.

Sounds like one of the recipes that did weird things with the prerequisite being a window.

**Comment by kolsurma** [comment]
![boarded-windows](https://cloud.githubusercontent.com/assets/10261427/23381972/2140adf0-fd06-11e6-9025-059a49bc6532.png)
left and middle are replicating the issue. Right is a functional window, right bottom is a normal boarded window. the standalone boarded-up window graphic get weird when replicating the bug.

**Comment by Toothspit** [comment]
There seems to be some nonsense with BARRICADABLE_ in `construction.json`. Unopened non-taped and opened-but-taped window frames seem eligible for one type of reinforcement, and empty window frames are eligible for another. Unifying the different types of window is a big problem, but making all of them eligible to be turned into a single type of closed and boarded window seems trivial and what the player wants anyway. I can pursue the latter, if that's the solution we want?

/data/json/terrain.json: L2275-2600

**Comment by kevingranade** [comment]
I think the only issue with that is some materials evaporating, e.g.
curtains which are surprisingly valuable early game.

Other than that, yes promoting all windows to the same type sounds good.

Side note, I don't recall where the enhanced and armored windows came from,
need to look into that.

**Comment by Toothspit** [comment]
I was way off in my comment above, this appears to be Working As Intended game-side, but `CONNECT_TO_WALL` is blowing up the tile.

![chezzo_windows](https://cloud.githubusercontent.com/assets/18541270/26030630/c27ebf16-381d-11e7-8b13-c11eda8daa34.png)

Above is on Chesthole. Blockhead's broke on both, Chesthole16 and Chesthole32 only blew up on t_window_boarded, _iso is fine, Deon's both bad, Hitbutton_iso is fine, Hoder's both bad, MShock24Modded and MShock32Modded both bad, RetroAscii is fine, RetroDays10px and RetroDays20px both bad, Thuztor'@ both bad, Tsu's doesn't even have a tile for _boarded_noglass but is also broke on both.

I can't into tilesets, this a problem with multitile in the tile_config?
