### ISSUE TITLE
Anthills generate huge and disconnected

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20417]
http://smf.cataclysmdda.com/index.php?topic=14219.0

Do anthills have enough data to make connections?
Labs don't, but labs are always connected with all neighbors, so anthills should probably do something similar.

**Comment by TheWebfrog** [comment]
The thing about ants is that there is normally more than one colony in one area. So maybe that was the intended affect?

**Comment by Leland** [comment]
@pisskop validated this in #20455.

> recent ant hives have made secluded, inaccessible chambers any where two chambers adjoin one another without a tunnel
>
> <a href='http://i.imgur.com/jBhbhaP' title=''><img src='http://i.imgur.com/jBhbhaP.jpg' alt='' title='Hosted by imgur.com' /></a>

For future devs taking a look at this, note that @SunshineDistillery noticed in that same closed issue that "subways are also disconnected in places."

**Comment by Leland** [comment]
Just teleported around to anthills - looks like they're always disconnected. To the player, an anthill is just a small underground room.

<img width="1280" alt="screen shot 2017-05-29 at 10 01 24 pm" src="https://cloud.githubusercontent.com/assets/714017/26565603/86043b8e-44ba-11e7-9017-74269d7ec2fb.png">
