### ISSUE TITLE
Giving bridge railings (and other terrain) ability to block movement

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#20427]
An idea I was considering making a pull request for, but hoped to gain feedback on beforehand. The idea would be for certain terrain to be changed from slowing players and monsters down to blocking movement, while still permitting them to be climbed in the same manner as chain link fences.

The main terrain I had in mind for this would be the railings on bridges, as climbing onto them from underwater would logically be a difficult feat. This would additionally give bridges some value as natural chokepoints, up until underwater zombies smash the railing. The effect on player annoyance would hopefully be low as players are not likely to want to jump into the water, whereas other terrain changes might be common enough that they add more annoyance than they gain.

For example, picket fences might be useful for more than decoration if undead were forced to smash through them, but they are common enough that it would add situations where the extra keypress is not worth the utility gained. Additionally, the implied height of fences are not clearly defined. They could be high enough that a zombie might be more likely to barrel into instead of stumbling over, or they could be the archetypical waist-height fence where actually deterring a monster is not logical.

If there are any other instances of mobility-impairing terrain that might be more useful if they blocked movement (while still permitting climbing), I could implement that in a future pull request.

A related idea would be extending the climbing action to other terrain that already blocks movement, such as palisade fences or gates. This would depend on how tall they are implied to be.

**Comment by TheWebfrog** [comment]
I'm not sure what it is, but the same tag that's used for Chain Link Fences... probably "climb_prompt" or something like that.

That would make it impassible but still allow movement if you want to jump into the water

**Comment by DangerNoodle** [comment]
That is what I was thinking about using, That would be the examine action, if I recall.

**Comment by kolsurma** [comment]
>That is what I was thinking about using, That would be the examine action, if I recall.

It is, but unless you know to do it 'e'xamining the fence is not terribly intuitive. It should probably be more like doors, where the option to open them still exists but just trying to move into the same square accomplishes the same thing.

**Comment by DangerNoodle** [comment]
That would be a useful function to add to the game. The lack of such a feature is why I would only suggest extending the "blocks movement but can be climbed over" behavior to railings, because they are mostly limited to bridges.

**Comment by Coolthulhu** [comment]
The problem with auto-climb is that it takes a long time.
The perfect solution would be a movement mode kind of a thing that turns autoclimb on and off. If the menu was handled nicely, it could also include settings for autoopen (doors), autoswap (with npcs), auto-enter-hard-terrain (so that you can avoid blundering into 400 move cost rubble) etc.

**Comment by DangerNoodle** [comment]
Understandable. What would you recommend regarding the idea of making some terrain behave like chain-link fences? Are there any other terrain items that would warrant making them behave the same?

**Comment by Eddyskingdom** [comment]
i think traps dat you have seen ask you if you wan't to walk over the trap YES or NO is dat possible to do

**Comment by kolsurma** [comment]
>The problem with auto-climb is that it takes a long time.

I was thinking more along the lines of: if you move into the same square as the fence it queries the user if they want to climb it <Y/N>, like examining it now does.

**Comment by Coolthulhu** [comment]
Prompts like that are pretty annoying because they force you to move the hand away from keypad to esc/enter. They are better avoided except when actually needed.
It would be better to have a prompt-less climb on examine than prompt on walk-on.

**Comment by Leland** [comment]
Closing due to lack of recent discussion; feel free to ping me here to reopen if there's still interest.
