### ISSUE TITLE
Half Russian

### ISSUE THREAD

**Issue by Honcharuk** [CleverRaven/Cataclysm-DDA#20422]
# How did this happen?

On the virtual machine Windows 7 these files show all in Russian.
Screenshots from Windows 10

![123](https://cloud.githubusercontent.com/assets/15582553/23482747/e0e09e08-fed8-11e6-9d12-9789b9cc136e.png)
![1234](https://cloud.githubusercontent.com/assets/15582553/23482746/e0dece7a-fed8-11e6-8a28-ca34621b12e8.png)

**Comment by AMurkin** [comment]
Win 10, not reproduced, at least on current build. Maybe make clean install.
Russian: Не наблюдается такой проблемы. Может переустановить?

**Comment by BrettDong** [comment]
Check if the file `lang/mo/ru/LC_MESSAGES/cataclysm-dda.mo` exists.

**Comment by Honcharuk** [comment]
>

**Comment by Honcharuk** [comment]
Переустановка не помогла.
