### ISSUE TITLE
Advanced Inventory- when it's moving items to inventory without enough volume (Crash)

### ISSUE THREAD

**Issue by Samait** [CleverRaven/Cataclysm-DDA#20426]
when it's moving items to inventory without enough volume. Like:

moving scrap metal (8) from the floor to player character with 3,34/3,50 vol.

> 
> [ Microsoft Visual C++ Runtime Library]
> _This application has requested the runtime to terminate it ....._
> 

Same happens when it's moving to others types of containers.

Version:
cataclysmdda-0.C-6289

tested in diferents worlds with and without mods

EDIT:
problem solve changing interface language to english.

**Comment by kolsurma** [comment]
What language were you using previously?

**Comment by Samait** [comment]
Spanish (Argentinian).   Win Version.

**Comment by Zireael07** [comment]
Does Spanish use a dot or a comma as decimal separator?

**Comment by kolsurma** [comment]
Error seems to occur when this line is called:
```json
#: src/advanced_inv.cpp
#, c-format
msgid "Destination can only hold %d! Move how many? [Have %d] (0 to cancel)"
msgstr "¡El destino solo puede contener %d! ¿Cuántos querés mover? [Tenés %d] (0 para cancelar)"
```
I can't get my debugger to connect to the release version, and my locally compiled version doesn't want to change languages (visual studio issues)
