### ISSUE TITLE
Base item inventory letters on roles, not pickup order

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20423]
This could also be implemented as an option, but I think it's good enough to be the default.

Basically:
Inventory letters sharing binds with some common actions would be reserved.
Those actions would be:
* Wield
* Eat
* Apply
* Wear

And so on.

When one of the special actions was executed on an item, it would get invlet corresponding to said action. For example, if you 'E'at a piece of popcorn, that popcorn stack now receives the letter 'E', as long as there is no hard-assigned item with invlet 'E' and said popcorn stack has no hard-assigned invlet.

That way you could E->select a stack->enter->E->E->E to eat from one stack 4 times.

Also all 'E' invlets would be cleared from any items listed in 'E'at action. This would be to allow "invlet id" hack to do even more: to allow integrating invlets for items on the ground. That way if you 'E'at a piece of popcorn on the table, it gets the invlet despite not being in inventory and you can keep 'E'ating.

In this system, free invlets would not be soft-assigned to anything, but rather depend on position in current menu. That is, if you pick up an item, it has no invlet, when you open inventory it has one, but when you close the inventory the item loses said invlet. This would be so that multi-page inventories would not require manually scrolling to an item if it lacks an invlet.

Worth implementing? Of course it's just a hack imitating a proper item selection history, but the history would require more complex hacks or item ids and item ids require first implementing the atomic id system.

**Comment by Mecares** [comment]
Yeah that would be quite nice, i often do that with e.g. throwing weapons manually.

**Comment by kevingranade** [comment]
This part is fine:
> Inventory letters sharing binds with some common actions would be reserved.

This part not so much:
> In this system, free invlets would not be soft-assigned to anything, but rather depend on position in current menu

This discards persistent invlets, which is the single most important property of invlets.  If we didn't want that feature we'd just discard invlets entirely and have them be menu shortcuts.

I'm not how sure this part works either:
> This would be so that multi-page inventories would not require manually scrolling to an item if it lacks an invlet.

If they don't have persistent invlets and they aren't shown on the current page, how could you possibly trigger them?

**Comment by Coolthulhu** [comment]
> This discards persistent invlets, which is the single most important property of invlets.

Hard-assigned (manually) invlets would still be persistent.

> If they don't have persistent invlets and they aren't shown on the current page, how could you possibly trigger them?

Consider situation where a hoarder player has 300 items.

Current model:
* 70+ items have invlets and can be accessed
* Other items can be only accessed by scrolling to them

Position-based:
* `n` items have assigned invlets
* `70-n` invlets are free
* Scrolling with page down always shows a page with at least `70-n` items with invlets on it, permitting  quick access to items which weren't manually assigned

The current invlet system does very poorly for full inventories of items, but current inventory model favors full inventories. For example, it's a good idea to hold 1-3 pills of each possible type in the inventory, but when you do that, selecting one of 5 painkillers is a pain.

**Comment by kevingranade** [comment]
If you want to completely overhaul how invlets work, which is what this proposes, you need a much more comprehensive system than this.  As stated, this discards a hell of a lot of how the system currently works with no compelling replacement functionality.

It's absurd to propose this "as an option", adding this would make the inventory handling even more convoluted than it is right now, I wouldn't be remotely ok with merging the code to support this on top of the existing code, which is nearly impossible to work with already.
