### ISSUE TITLE
Steel plating vs Hard plating

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#20425]
Version: 0.C-21474-g6a86c7860b (tiles)
Build: 6289
OS: Windows 7 Professional x64 SP1

Steel plating (1000) has the same durability as hard plating when installing it on a vehicle. Not sure what was the original value for hard plating or if it has always been this way.
My guess is that it should be between 1000 and 2000 (military composite armor durability value).

**Comment by Coolthulhu** [comment]
Hard plating has higher damage reduction, it's just that it isn't shown.

**Comment by Leland** [comment]
@Nhatorama closing this as @Coolthulhu appears to have answered it. Feel free to reopen if you think this is still an issue.
