### ISSUE TITLE
JSONify mapgen is breaking scenarios

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#20439]
Or, at least, I *think* that is what is going on. I'm still testing, but at the very least the School scenario cannot start because it can't find a suitable start.

**Comment by Eddyskingdom** [comment]
dide you remove all the mods and den try it also make a new world?

**Comment by 1skandar** [comment]
Yes, this is clean of all mods, new world. It looks like something in the ongoing project that is moving mapgen to JSON has broken whatever that scenario, and probably others, are using to identify a suitable starting location.

**Comment by ZhilkinSerg** [comment]
School start should be fixed now.
