### ISSUE TITLE
Non-'hardcleared' overmap terrains cannot be included into rotating overmap specials

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#20436]
Since, #20003, all rotating overmap specials have had to be explicitly cleared by the game's hard coding.

I cant speak for other modders, but the impact upon my mapgen meant a large amount of the structures Ive defined had to be swapped over.

Terrains such as fields, forests, parking lots, and _any_ custom-made terrain set cannot be included into rotatable overmap specials,  because the game cannot find exceptions and they require a tag that explicitly excludes them from rotating specials, which refuse to load if one of their constituent terrains lack this clearance.

This will restrict new coregame specials that can be added, and for modders removes the ability to add in terrain that ca rotate to meet the roadways or city streets.  We're at "house_east" and "road_west" for modders, whereas before this was never the problem.

The obvious workaround solution is to add in more code and mentally manipulate the overmaps to add more redundant specials, which raises its own problems like necessitating that several or none of the special spawn.  There is no in-between for modders - now.

This causes issues such as

- crippling large specials that require specific conditions to spawn (say a cemetery that spawns far from a city in a swamp by a road)
- reducing the dressing that hides the modular nature of the game, breaking immersion (say every single public works in the game spawns facing south-north, and only north of roadways)
- Eliminating modders 'diversifying' pre-existing structures (adding fields to apartment buildings or a subway to a mall)
- Ugly modded-in custom buildings (such as custom houses) genning in the city.

**Comment by pisskop** [comment]
For a source, this commit holds all (and mostly, only) the changes required to bring the mod into compliance with the linting and create a much more static mapgen.

**Comment by Coolthulhu** [comment]
A json example would be useful. How are the entries nested (which one is roatable, which isn't), how did it look before, what is the error, how do you hack around the restriction (last one optional).

Solving it may be as simple as creating a fallback function when a rotated id can't be found, but it depends on what exactly (exactly) is the problem.

**Comment by Coolthulhu** [comment]
Wait, does it actually not work or only warn but then does work?
Removing the warning would be much faster, actually finding a bug here will take more time and require an example, since the code looks like it should work.

**Comment by ZhilkinSerg** [comment]
I've seen strangely connected `public works` recently - road connection to it was mirrored:

<img width="730" alt="public_works_1" src="https://cloud.githubusercontent.com/assets/16213433/23573705/1d100a88-0089-11e7-8dea-0853eeb6a81a.png">
<img width="730" alt="public_works_2" src="https://cloud.githubusercontent.com/assets/16213433/23573706/1d4b39d2-0089-11e7-817f-d1af784eb3cc.png">
.

**Comment by Coolthulhu** [comment]
I was able to reproduce the debugmsg, but it seems that it is only a debugmsg - the mapgen worked just fine. Pinging @codemime

**Comment by codemime** [comment]
Yes, it's only a debugmsg. My concern was to prevent some ugly cases from happening. For example, the shipwreck was rotating like this:

![shipwreck](https://cloud.githubusercontent.com/assets/11905613/23582854/9926edb6-014d-11e7-8995-b7e0f4a5d22a.png)


Although, I agree that the check is too restrictive, so that it prohibits even the valid cases (however, there were none in the vanilla). In summary, I don't mind if we remove the check completely.
