### ISSUE TITLE
NPC burning ter home down wen a enemy comes to dem only if the NPC hase something to put on fire or something dat you can start a fire with

### ISSUE THREAD

**Issue by Eddyskingdom** [CleverRaven/Cataclysm-DDA#20433]
NPC of the old guard and the free Merchants will burn down ter own house and ter selfs to kill the enemy.
dis is a realy easy to fix ( i wan't to do it only i don't know how the GitHub flow works )

**Comment by DangerNoodle** [comment]
This was a bit headache inducing to read, but issue is long-standing and affects any NPC given access to incediary weaponry.

See issue: https://github.com/CleverRaven/Cataclysm-DDA/issues/20256

**Comment by Eddyskingdom** [comment]
Leave a comment
