### ISSUE TITLE
suggestion to add stealth to the game 

### ISSUE THREAD

**Issue by Eddyskingdom** [CleverRaven/Cataclysm-DDA#20431]
stealth need to be a skill and with it a profession like a thief or a ninja what i em trying to say is: stealth in the game will give you less chance to get woundet or kill by monster, NPC and so on and because you guys already have sound, traits voor it, smoke and distractions voor the monster dat make sound, like firecrackers or a airhorn. 

the way to lvl up is by being stealth around monster and pickpocketing vrom NPC or killing dem
and the option to go stealh needs to be in styles and wen it's turnd ON it need to let the player show wher the monster is looking at if the player is out of dat range you can passe him or stealh kill him and how higher the skill is how easier it is to not get seen or heard and also a chance to pickpockt and not geting noticed by the NPC and also dat if your trying to snap it's neck or knock ( only NPC ) him out and also if you ar bashing him with something it will make some sound and will do 2X the damge den nomal and your more guaranteed to kill it den snapping his or hers neck

**Comment by Eddyskingdom** [comment]
and i forgot to say dat if your in the bushes and a your steathing you will hide in the bush and if a your in the enemys view you won't get seen only if the enemy is close or you moved out of it and if you wan't to get close and not get seen you need a high skill.
also it,s the same as all the opjects in the only one hase more cover den the other den you will hide better and any thing with sensors or dat it can hunt you with smell will give you away also if you sneak in the night and ter is something with night vision you will get spoted also it need to say wen you ar spotted

**Comment by 1skandar** [comment]
Stealth as a separate skill is likely unnecessary. That said, having it be based off of your survival skill would possibly be a good idea. And having a stealth mode you could toggle into, like adding it to the " key so you'd toggle between walk/run/stealth. 

Stealth would cause you to move at a fraction of your walk speed (what fraction determined by survival skill, maybe?) In return you'd make less sound when moving and be less visible a long as you weren't om flat open terrain or in bright sunshine(again, maybe sound/visibility mitigation based on survival skill?)

**Comment by Eddyskingdom** [comment]
exactly

**Comment by Tharn** [comment]
For me this boils down to adding a third walk speed. 50%ish speed for crouched walk. Less noise, less visibility. That's a good idea. All that other stuff sounds like complexity giving little more in actual gameplay.

You're not going to sneak-attack a walking corpse for more damage than what you would do anyway with a well-aimed strike. You aren't magically stronger or anything, and AFAIK zombies don't have much in the way of a defensive instinct.

**Comment by mutt3x** [comment]
>if your in the bushes and a your steathing you will hide in the bush and if a your in the enemys view you won't get seen

You are forgeting the scent factor, they can still smell you.

Stealth is useles agains zombies, i mean its good for starting characters when you are weak but generally its useless. So when there are dozens of zombies on a road your best stealth is to avoid them or to trow a nuke and never see them again. I dont think i would hide in a bush or anywhere for that matter.

The whole thing with the sneak damage is unrealistic, so i hit a zombie with my bat and do dmg but when i hit him in sneak mode with the same power and same bat i do more damage? A zombie is just a picece of walking flesh i dont think it cares when and how you hit him. A human might but not a zombie.

That being said stealth might be good against human NPCs. Hide in a car, in a houes if you are chased...

**Comment by 1skandar** [comment]
Well, yes, scent is a thing, but it is fairly short range. Stealth shouldn't be total LOS mitigation, anyway. You wouldn't be sneaking up on a group of zombies, more like shrinking the detection radius by something like 1/2 or so. Stealth shouldn't be used as an attack skill, more like flattening yourself down into the tall grass to sneak past a group of zombies just over there, or trying to blend into the bushes after getting a bit of distance when being chased. A defensive skill instead of offensive.

**Comment by kevingranade** [comment]
Stealth is something we want to do, but almost certainly not direct damage
boosts for it.

**Comment by Eddyskingdom** [comment]
and hoe is working on dis, just asking

**Comment by kevingranade** [comment]
Nobody at the moment, just because you open an issue doesn't mean someone
will start working on it.

**Comment by Eddyskingdom** [comment]
After 10 months you Guys are finely make it true

**Comment by Vzor-** [comment]
When I was new to the game, I thought walking then waiting caused less noise. It doesn't, but it could be a way to add 'sneak' without adding a new mechanic/key. (like right-arrow, period, right-arrow, period ect) Just an idea.
