### ISSUE TITLE
Some vehicle parts drain way too much power

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#20443]
First off, floodlights. They drain 2000 power versus a headlight's 187. While they are, indeed, better than a headlight I'd hesitate to call them 10x as good.  I'm not calling for a return to the old value, I'm just saying that the bar was placed a bit too high. Floodlights may light a circle, but IIRC a headlight's cone has a longer range. I'd say having or quartering the drain may be appropriate here. 

And, not to touch on a sore subject, but, again, the power drain on a stereo needs to be lowered. 700 power for a moderate mood buff and (very) situational auditory distraction is really too high. Turning on  the stereo will immediately put a vehicle into negative power usage just with it and the engine running. If nothing else, that's highly unintuitive.

**Comment by Coolthulhu** [comment]
Currently the floodlights turn the night into day. Their light range is barely below bubble radius.
If we're cutting their input, their output should be cut as well.
Going by pure output, that 2000 power is lower than it should: floodlight lights up more tiles than 12 headlights and with more light on near tiles.

The balance of stereo is perfectly fine - we don't have good electricity sinks other than electric engines, so at this point it's +5 morale (over mp3) for a lot of electricity or nothing for free.
The unintuitiveness is subjective, but I can buy that one.

I don't have a good plan for floodlight. That would require use cases where using headlights is better even on a vehicle that has a lot of power production.
For stereo, I'm thinking 400 - double the headlight and low enough to put it below all alternators.

**Comment by 1skandar** [comment]
The thing with floodlights and "more light on near tiles" is, well, what does it matter? Not being sarcastic but, AFAIK,, there are three light states that matter, dark, dim, and bright enough to see/craft. The level of that last one seems to be irrelevant. And no, a floodlight doesn't have more light than 12 headlights, exactly, as a headlight outranges it by a bit. While a floodlight might be *technically* better, at its current cost I could get a "good enough" solution out of a few headlights where I wouldn't bother trying to deal with the extra power drain. Quite frankly, the amount of times I need a "pool of light yea big" versus "specific light along this line" is limited to begin with.

As for the stereo I'd argue that the morale effect isn't worth it to budget that much power. I know for me, at least, and I'd bet I'm not alone, that if the stereo cost enough power where I had to design around it it would be a simple choice just to bin it as the benefits just aren't *that* compelling.

**Comment by Coolthulhu** [comment]
> Quite frankly, the amount of times I need a "pool of light yea big" versus "specific light along this line" is limited to begin with.

I had the opposite experience: driving through zombified cities, fighting hordes etc.
The only real weakness of floodlight I see is that it reveals you, while headlights don't because zombies don't see cars (though they totally should aggro on moving cars).

> As for the stereo I'd argue that the morale effect isn't worth it to budget that much power.

Translated to fuel, it isn't really that much.

**Comment by 1skandar** [comment]
Fuel, maybe. But versus a solar cell's 50 output it kinda is. You'd never want to run one on an all electric vehicle because of this, and even on gas powered ones it would be the first to go if the battery started dropping even with the engine on. The effect just isn't obvious and compelling enough for the player to make that choice.  Which, really, probably says a few things about the morale system in general really but that isn't here nor there in this discussion.

And that is kinda the same argument I have with the floodlight, its benefits are there, but not really compelling enough at its cost. I might be tempted to mount one at 500 power or 1000 power, but at 2000 I'm more likely to just jury rig something that, sure, won't be as good but will be a lot less hassle to upkeep.

**Comment by kevingranade** [comment]
Floodlights are doing more than 8x as much work as headlights, so that ratio at least is appropriate (I checked, headlights do not have longer range, it's just that there are two of them pointing in the same direction). You could literally install 8 headlights pointing in all directions and get the same effect,
As for the stereo, I'm dropping the ower consumption significantly, it's just dumb hving it set where it is.

**Comment by 1skandar** [comment]
Good enough. Stereos really were my biggest issue. Having them drain more power than the car's engine was kinda nuts. Thanks.
