### ISSUE TITLE
Keybinding modifiers (ex. diagonal movements via SHIFT+arrow keys)

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#20447]
Is it possible to map diagonal movements via SHIFT+arrow key?

Shift + Arrow Up = NE
Shift + Arrow Right = SE
Shift + Arrow Down= SW
Shift + Arrow Left = NW

That will easen playing on laptop keyboards without numpad.

**Comment by Coolthulhu** [comment]
Do we still have anyone who understands how does our input system really work?

**Comment by kevingranade** [comment]
This particular thing actually bypasses our input system and dives into the
underlying libraries, we call a function that returns a distinct keycode,
I'm not sure such a code exists for SHIFT + UP.  If it does, this will just
work, if it doesn't, it's impossible without reimplimenting the lowest
layer of input handling.

**Comment by Coolthulhu** [comment]
How about alt keys? Can we bind anything to alt+key or ctrl+key?
If not, we could try hacking around with manual modifier key state checks.

Ctrl+key would be pretty useful for some weird actions. All keys are assigned, having ctrl+key do something similar to key or shift+key would be intuitive and helpful.

**Comment by somot** [comment]
The game already has got SHIFT + KEY key binds, e.g SHIFT + W opens 'W'ear menu, while "w" alone opens 'w'ield menu.

**Comment by kevingranade** [comment]
> How about alt keys? Can we bind anything to alt+key or ctrl+key?
If not, we could try hacking around with manual modifier key state checks.

Boils down to the same thing, right now we get the already decoded keycodes, if there's a keycode for alt+key it'll just work, if not, we can't do it in the current code.
Note that "reimplimenting the lowest layer of input handling" isn't the end of the world, it's probably well under 1,000 loc.  It does however require an input loop and related nastiness, which sucks quite a lot.
There might be a way to do the same thing without resorting to direct keypresses handling, in which case it might be fairly easy.

**Comment by kolsurma** [comment]
[From what I can ncurses doesn't support shift (ctrl, alt) + arrow key by default. The functionality would have to be programmed in. ](http://invisible-island.net/ncurses/ncurses.faq.html#modified_keys)

**Comment by BevapDin** [comment]
@ZhilkinSerg  Have you tried it out? It works on my ncurses build, the menu calls it "Unknown key 336" and so on, but they work as expected.

**Comment by pabrams** [comment]
Shouldn't this be merged into a bigger issue to allow modifiers for the keybindings? (and then maybe smaller issues if needed to add/change default keybindings)

Also, Is this really a good idea if you have to bypass the input system?  Doesn't that mean it won't appear in the keybindings? 

I was just lamenting the slow panning on the map screen, and was thinking about opening an Issue to add  a shift modifier for faster panning (ala Dwarf Fortress), but after finding this Issue, I think what's really needed is the ability to have shift/alt/ctrl keybinding modifiers.

**Comment by Leland** [comment]
@pabrams done, floor's all yours.

**Comment by kevingranade** [comment]
In order to support that we'd need a low-level keyboard driver.  We can definitely do that in SDL builds, but I don't know if it's possible in curses.

**Comment by ZhilkinSerg** [comment]
> @ZhilkinSerg Have you tried it out? It works on my ncurses build, the menu calls it "Unknown key 336" and so on, but they work as expected.

Sorry for the late answer. Yes, I've tried it and it didn't work on my laptops. It is likely depends on envrionment (operating system, keyboard driver, etc).

**Comment by Night-Pryanik** [comment]
Closed by #22690, I think.

**Comment by ZhilkinSerg** [comment]
> Closed by #22690, I think.

Thanks! I forgot to add this issue to PR comments.
