### ISSUE TITLE
rotating overmap and symbols

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#20441]
Right now symbol rotation and maptile rotation are connected when they probably shouldn't be. 
If, say, I wanted to make a building represented by a V, or make a large overmap special with < and > to represent the locations of stairs, those characters would rotate along with building whether I want them to or not. There should be two separate options, or some kind flag to fix the symbol in place.

**Comment by codemime** [comment]
Adding a flag for that would be a fairly trivial task, but do we really need it? I mean, you describe a pretty hypothetical case.

**Comment by SunshineDistillery** [comment]
Well I need it. I use a custom mapkey that replaces all the ^<>^ confetti with letters. And using V for  vet clinic doesn't work.

**Comment by Leland** [comment]
Closing due to lack of recent discussion. Feel free to reopen if there's still interest in development.
