### ISSUE TITLE
Reproducable crash in "List all items around the player"

### ISSUE THREAD

**Issue by DeionSi** [CleverRaven/Cataclysm-DDA#20449]
OS: Windows 10 x64
Version: Tiles, 0.C-21504-g046010ec95 via cdda-launcher
Save: https://www.dropbox.com/s/6jy08qkax3hz7a1/save.zip?dl=0

Reproduce:
Load the save game
Take two steps to the left (H)
Open List all items around the player (V)
Switch to the item view (TAB)
Go to the next item (RIGHT)

I believe the problem happens when you try to go to the next item but there are no items to go to. "List all items around the player" doesn't open if there aren't any items or monsters nearby. In this case there are monsters but no items. Interestingly trying to go to the previous item (LEFT) doesn't not crash.

**Comment by DeionSi** [comment]
Additional note: I just noticed there is a filter applied in the "List all items around the player" item list. Nevertheless the report is still valid.

**Comment by AMurkin** [comment]
I've found the reason. activeItem initially NULL has low chances to be assigned here [game.cpp#L9302](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/game.cpp#L9302).
Especially when filter applyed.
So it stays NULL at `( int )activeItem->vIG.size()` in [game.cpp#L9250](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/game.cpp#L9250) and crashes.
ping @codemime

**Comment by kolsurma** [comment]
It's an odd bit of code, it checks a potentially null variable before checking to see if there's anything in the filtered items list.

Two ways to fix: check `!filtered_items.empty()` first and check `activeItem == NULL`. I prefer the former.
