### ISSUE TITLE
Sheath should hold survival knife

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#20457]
In Sheath description "can contain items up to 1 L".
And in English "up to" means less than or equal to, not just less.  I just checked it, because it's not my native :)
Survival knife volume is 1L, but I can't put Surv knife in Sheath

Looks like there is "< 1L" but should be "<= 1L" in Sheath parameters. 

Or, if it works as intended, could you please change description.

**Comment by kolsurma** [comment]
It appears to be a limitation of the description, it's rounding up to 1 liter instead of showing it at 0.75 liters.
