### ISSUE TITLE
Ant Hives produce inaccessible chambers

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#20455]
recent ant hives have made secluded, inaccessible chambers any where two chambers adjoin one another without a tunnel

<a href='http://i.imgur.com/jBhbhaP' title=''><img src='http://i.imgur.com/jBhbhaP.jpg' alt='' title='Hosted by imgur.com' /></a>

**Comment by kolsurma** [comment]
looks to be related to #20417

**Comment by SunshineDistillery** [comment]
I noticed that subways are also disconnected in places.

**Comment by Leland** [comment]
Closing in favor of #20417
