### ISSUE TITLE
Character statistics screen incorrectly reporting cost/skill values

### ISSUE THREAD

**Issue by Zethnet** [CleverRaven/Cataclysm-DDA#20452]
Version: Experimental Build - Tiles **0.C-21474-g6a86c7860b** with **Disable NPC Needs** mod
OS: Windows 10 x64
Save: [save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/818896/save.zip)

On the character statistics screen (Shift+2) under 'Encumbrance and Warmth', when using the keyboard to scroll up and down between 'Hands/Legs/Feet' the reported statistics for 'Legs' changes depending on the direction it was navigated to from (i.e. pressing up to go from 'Feet' to 'Legs' reports different 'Leg' costs and skill amounts than going from 'Hands' to 'Legs').

This persists after saving/reloading/restarting and doesn't seem to affect the other body parts statistics. Though this may be misleading as 'Eyes' and 'Hands' are zeros and 'Body' and 'Head' are at the top and bottom of the list so I can't navigate to them from another direction.

Attached Images:
H2L.png (Scrolling from 'Hands' to 'Legs') - Shows running costs, swimming costs and dodge skill to be +6, +92 and -1.1 respectively.
F2L.png (Scrolling from 'Feet' to 'Legs') - Shows running costs, swimming costs and dodge skill to be +3, +46 and -0.6 respectively.

![h2l](https://cloud.githubusercontent.com/assets/26190024/23581755/c810741e-0155-11e7-9416-f4216b9946a5.png)
![f2l](https://cloud.githubusercontent.com/assets/26190024/23581756/c812a8ba-0155-11e7-8a08-c14a64e22cd5.png)

**Comment by Coolthulhu** [comment]
Probably related to paired body parts.
Body part pairing was a giant hack last time I checked and I didn't fix all of it, I guess.

**Comment by kolsurma** [comment]
parts set:
from hands: 0,1,2,3,5,7,8,10
from feet: 0,1,2,3,5,7,9,10
