### ISSUE TITLE
Being attacked while washing filthy clothes

### ISSUE THREAD

**Issue by AdonaiJr** [CleverRaven/Cataclysm-DDA#20468]
So, I almost died while I was near a swamp, washing a Military rucksack (or so). I was attacked by a pack of dogs, and heard a strike or two of a nearby shocker zombie.

I guess it was possible to stop the activity by hitting ".", but it was so quick, I couldn't do anything.

Just like butchering, it could use a warning like "you see _monster_ aproaching".

**Comment by DangerNoodle** [comment]
With or without Filthy Clothing mod enabled?

**Comment by Coolthulhu** [comment]
Washing works the same regardless of mod.

**Comment by DangerNoodle** [comment]
Hmm. Makes sense.

**Comment by kevingranade** [comment]
#21089 adressed this.
