### ISSUE TITLE
Should sheathes / holsters show exact storage volume?

### ISSUE THREAD

**Issue by kolsurma** [CleverRaven/Cataclysm-DDA#20464]
#20457 demonstrates this perfectly, there's a disconnect between the displayed volume a sheath / holster can hold and what they can actually hold.

Is there any reason not to show the player the exact volume these items can hold?

**Comment by glenmack** [comment]
It's an either or situation. We currently have two good options.

It should either be exact volume, the rounding up is crazy,
Or,
display nothing on the sheathes and display can be held by "this, this, this, etc." on the weapons themselves.
