### ISSUE TITLE
unstoppable NPC item groups

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#20461]
NPCs get equipment from their character class list and a common list of NPC stuff. This is unnecessary as the specific item groups for each class could contain a reference to a common list.  That would do the same thing, but would be easier to work with in the jsons.  The problem is that there might be stuff on that common list you don't want a class of NPCs to have at all, and there's no _good_ way to stop it. 

There is a way to override this, which is used for the Apis class, but it's weird and hacky. The Apis is a good example of the problem too. To make a mutant NPC with no clothing or stuff, there has to be this special override function or else she'll spawn with sunglasses and cookbooks and whatever other things a mutant insect shouldn't have. Really the class should just have empty item groups. 

You might be able to sidestep this with just an edit to the jsons.   If you renamed the groups like npc_misc to something else and then re-included them in the class specific lists, it might work. I haven't tested that though.

**Comment by SunshineDistillery** [comment]
> Well, this is exactly what is happening.
It's not though. Look in data/json/npc/classes.json
The apis class has :
"worn_override": "EMPTY_GROUP", 
"carry_override": "EMPTY_GROUP", 
"weapon_override": "EMPTY_GROUP",

Having an empty item group should be enough, but it needs this extra thing to override the common npc items. The debug dude has a similar override. 

What I was trying to do was make a mutant that was freakishly large, so I want an item group of just oversized clothing. I can't just make the group and be done with it. I have to mess with these overrides. Or I have to make an item group with insanely high weights, but that doesn't seem to work with null.  So it will spawn these hulking brutes in fur loin cloths and foot wraps but wearing cowboy hats and Linux t-shirts.

**Comment by Coolthulhu** [comment]
I still don't see the problem here. How do you imagine it being solved "properly"?
You want the default to be empty instead of defaulting to "CLASSNAME_gloves" etc.?
Or to have a specific NPC class have no fallback equipment but somehow without declaring said lack of fallback?

**Comment by SunshineDistillery** [comment]
> I still don't see the problem here

It causes several weird little problems:
I can't make an NPC that doesn't wear a hat. 
I can't have a gun spawn with an extra clip or two. 
I can't have damaged items/clothing.
I can't have an NPC that doesn't spawn without a full stack of ammo.
I can't have an NPC spawn with a backup weapon plus other ammo type.
I can't prevent a lighter from showing up (very minor problem that).
I can't have an NPC that wears underwear and pants OR I can't have an NPC that wears underwear and pants while still distinguishing between male and female clothes. 
I can't have an NPC that wears socks and shoes. 
To hack around these I have to add overrides in the class definition, which modders won't expect and might not notice. 
Using class overrides kills some of the built-in functionality, like adding weapon+ammo.

Most of these aren't problems if you're trying to make a generic survivor guy, but if you step outside that, like making a large mutant, you get headaches. 

> You want the default to be empty instead of defaulting to "CLASSNAME_gloves" etc.?

I want the game to ONLY check the NC_CLASSNAME file. Without looking at the item groups in the generic_items file at all. If you wanted a class to default to a generic group, you would need to have a json entry where you explicitly set CLASSNAME_gloves = { "group": "npc_gloves"} . 

>How do you imagine it being solved "properly"?

Easy version with just .json changes would just be to remove/rename the npc_stuff groups and re-add them in the NC_CLASS files where needed. That would side-step a few of these problems without any code changes. 

In a "Proper" version, the game would do something more like: 
Check if NPC is male/female
   If male, wear items from CLASSNAME_clothing_male 
   If female, apply CLASSNAME_clothing_female 
Check for highest weapon skill and use item group CLASSNAME_skill  
  Have NPC wield weapon (or first item in the collection if that's easier)
  Put other stuff (clips/ammo/UPS) into inventory
Put CLASSNAME_misc into inventory (just one time)
Check if NPC is "trader", 
  if yes add appropriate trader_items to inventory. 
Last you might want some kind of storage volume check, or you could just rely on making item groups without bulky stuff. 

Everything else would be handled by making nested item groups in json and mixing collections and distributions.  Basically, look at the drops for zombie soldiers in monster_drops. It has really good set of items that are varied and logical. I want that for NPCs.

**Comment by Coolthulhu** [comment]
So basically, you want:
* The NPC group to have a "root node" (only branching at gender) that then branches into individual parts (hats, gloves etc.) instead of starting at the individual part level
* Weapon groups to be able to specify ammo too
* `_misc` groups to get similar treatment to worn groups, in that their quantity stops being hardcoded

Right?

**Comment by SunshineDistillery** [comment]
>Right?

That would be my suggestion, yeah, although I'm sure people could come up with better ways to do it. And there might also be other issues, like if you want to jsonify body parts, there might be checks to see if a person has the necessary parts or the wrong parts or extra parts. Or other problems that it make it not so simple. 

But as long as there are good ways to modify things in the jsons, I'd be happy with whatever.

**Comment by DangerNoodle** [comment]
Does override even work? Recently was informed of a possible problem with overrides not working if new ones are introduced. Will open a separate issue if requested.
