### ISSUE TITLE
The key 'q' for the menu of "Repairing or Reinforcing clothes" does not run

### ISSUE THREAD

**Issue by mdtrooper** [CleverRaven/Cataclysm-DDA#20463]
Hi.

I find this tiny bug, that the key 'q' for to cancel in the menu of repairing clothes does not run.

![screenshot at 2017-03-06 02 08 13](https://cloud.githubusercontent.com/assets/1285451/23593641/f6106b00-0211-11e7-989c-9e7490b4ec81.jpg)

Well, I want to help but I don't know the source code. Somebody helps me to learn the source code of CDDA.

Bye.

**Comment by mdtrooper** [comment]
It is in somewhere in this part of source code:

src/activity_handlers.cpp:1530
```
repeat_type repeat_menu( const std::string &title, repeat_type last_selection )
{
    uimenu rmenu;
    rmenu.text = title;
    rmenu.addentry( REPEAT_ONCE, true, '1', _("Repeat once") );
    rmenu.addentry( REPEAT_FOREVER, true, '2', _("Repeat as long as you can") );
    rmenu.addentry( REPEAT_FULL, true, '3', _("Repeat until fully repaired, but don't reinforce") );
    rmenu.addentry( REPEAT_EVENT, true, '4', _("Repeat until success/failure/level up") );
    rmenu.addentry( REPEAT_CANCEL, true, 'q', _("Cancel") );
    rmenu.selected = last_selection;

    rmenu.query();
    if( rmenu.ret >= REPEAT_ONCE && rmenu.ret <= REPEAT_EVENT ) {
        return ( repeat_type )rmenu.ret;
    }

    return REPEAT_CANCEL;
}
```

The rmenu.query(); never stops with 'q' key.

And in the file src/ui.cpp:808

```
hotkeys = ctxt.get_available_single_char_hotkeys( hotkeys );
```

I commented this line beacuse delete the q in the list of hotkeys. But it still does not run.

**Comment by kolsurma** [comment]
[It's a known issue](https://github.com/CleverRaven/Cataclysm-DDA/projects/4), part of #20065 et al.

**Comment by mdtrooper** [comment]
Well, I am sorry, I am going to close this bug.

**Comment by kolsurma** [comment]
No need to be sorry! Just letting you know.
