### ISSUE TITLE
Bug: examine of tree_maple not show expected messages

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#20475]
These:
You need a tool to drill the crust to tap this maple tree.
You need a tool to hammer the spile into the crust to tap this maple tree.
And not showing them as long as i play 0.C.
win x64 tiles

**Comment by remyroy** [comment]
You cannot tap a maple tree in 0.C. This is not a bug.

**Comment by AMurkin** [comment]
Fine (actually sad), but message displayed on examine does not helps to figure that out.
Maybe that is a bug?

**Comment by remyroy** [comment]
No, it's not a bug. Please close this issue.

**Comment by kevingranade** [comment]
This feature was not written yet when 0.C was released.
