### ISSUE TITLE
Tents becomes damaged upon being taken down. 

### ISSUE THREAD

**Issue by AdonaiJr** [CleverRaven/Cataclysm-DDA#20471]
I found a Large Tent in a Sports Store. Upon using it, it instantly became damaged.

Also, found a campsite. Took down every single tent, all of them became damaged as well.

![tent bug](https://cloud.githubusercontent.com/assets/5797420/23630228/14d615e4-0299-11e7-8f74-e413f56a27f9.png)

Related? #20157

**Comment by AMurkin** [comment]
Related. Intended behaviour.

**Comment by Coolthulhu** [comment]
IT should only become damaged if it was damaged before being taken down or was generated damaged.

**Comment by AdonaiJr** [comment]
Tent I found on Sports Store was intact before setting up. I found yet **another** campsite, again every tent damaged as well. Are tents in those campsites always generated damaged, or should be a chance of being created intact?

**Comment by BrettDong** [comment]
How could this happen? I did some testing on my #20157 . Set up a tent and then take it down yields a normal tent. Getting a damaged tent only happens when you are recovering an incomplete tent.

**Comment by BrettDong** [comment]
Incorrect behavior might happen if the layout of tents generated by mapgen is inconsistent with the ones you set up by hand in the game. I don't have time to check it now, it's my guess.

**Comment by Coolthulhu** [comment]
Oh, I found it:
One of the campsite mapgens uses terrain for large tent, but not enough of it to form a complete large tent.
So when taking down the tent, the game thinks it's dealing with a damaged large tent rather than intact regular tent.

**Comment by l29ah** [comment]
Looks like still an issue: i've generated a fresh world and experience the same problem with a campsite // also there are two "canvas wall" tiles remaining after taking down all the tents.

**Comment by kevingranade** [comment]
Can you be more specific about which campsite you're talking about?
Some of them intentionally spawn with damaged tents.
