### ISSUE TITLE
Extract clay/sand mound. Wrong check of construction reqirements?

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#20478]
Here i can (active construction menu item) extract clay/sand mound:
![can](https://cloud.githubusercontent.com/assets/1931904/23662569/1913615c-0361-11e7-845d-5067753648a8.png)
And here i cannot (inactive):
![cannot](https://cloud.githubusercontent.com/assets/1931904/23662568/1913433e-0361-11e7-989b-98cdb869046e.png)
Descriptions of tiles above the player are the same: shallow water.
And in other strange combinations construction can be available or not.

**Comment by Coolthulhu** [comment]
Probably caused by salty shallow water having different ID and not being handled.
