### ISSUE TITLE
Inconsequent clothing coverage.

### ISSUE THREAD

**Issue by somot** [CleverRaven/Cataclysm-DDA#20482]
The current system for clothing coverage is quite wonky, because it applies the .json coverage value to ALL body parts it covers. It can lead to weird situations, such as a cloak covering 65% of legs, torso and arms. I suggest that instead of: "coverage": 65,", it should be: "coverage": 95/95/65 (for torso, arms and legs, respectively).

Sorry for my grammar, I'm from Poland.

**Comment by hatcher36** [comment]
Yeah, this is a problem, but, probably it can't be fixed that easy.

**Comment by kevingranade** [comment]
Pass, this implies updating and maintaining a huge amount of additional data for a very minor distinction.
