### ISSUE TITLE
Bone needle works only without charges 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#20499]
Just found that threads charged in bone needle do not count for crafting. 
Currently, threads must be in inventory or somewhere esle, but not "inside" bone needle. 
Using one of the latest experimental, probably one from 05 march. 

sry for my English

**Comment by ZhilkinSerg** [comment]
All sewing tools should work that way - if you have threads loaded into any type of needle or sewing/tailoring kit these threads won't be counted as available for crafting.

**Comment by DangerNoodle** [comment]
Second issue reporting this, inconsistency caused by the pull request author having yet to devise a way to implement repairs using thread in inventory.

**Comment by ynemo** [comment]
how can I close this issue?
I am pretty sure there are much more important things to do, and dont want to bother no one.
