### ISSUE TITLE
'm' key non-functional in debug map editing dialog.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#20492]
Reported on the forums at http://smf.cataclysmdda.com/index.php?topic=14243.0

> When you try to use the mapgen/map editor to spawn a house or something, you can't press m to move around.

**Comment by kolsurma** [comment]
Can confirm. `q` doesn't quit either, ongoing issue I suppose.

**Comment by Zireael07** [comment]
What build? I recall we recently merged a couple fixes by @kolsurma ...

**Comment by kolsurma** [comment]
build 6303, #20072 has 2 commits, 4c86f26 causes the issue.

This can be fixed by creating a `uimenu_callback` with a entry for the key in question. It's likely there are other menus which were affected by the commit though.

**Comment by kolsurma** [comment]
This is not specific to this issue, but what should be done about the `q`uit key? Do we stick with using `esc` only and change references to `q`? `[ESC] exit` in the various menus that have on screen help?
