### ISSUE TITLE
Two storage batteries in single vehicle tile

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#20505]
It is possible to put `storage battery` to vehicle tile with installed `swappable storage battery` if `swappable storage battery case` is destroyed in this tile.

**Comment by kevingranade** [comment]
Interesting, the swappable battery should fall out if the case is destroyed.

**Comment by Coolthulhu** [comment]
It doesn't look like "chained" destruction is implemented.
It's only implemented for removal and even then only hardcoded for seatbelts and window-covering parts (curtains and lights).

Would probably be cleanest to rewrite the "can install" function into "can be here", then check that for all parts on a tile whenever any part breaks off.

**Comment by Coolthulhu** [comment]
Oh, except frames. Those are an exception.
We basically need to change the rules from "if frame destroyed, spill all stuff" to "if part destroyed, spill all stuff that no longer fits".
