### ISSUE TITLE
Start Vehicle construction doesn't require anthing, or do anything : cataclysmdda-0.C-6313 (Linux Curses)

### ISSUE THREAD

**Issue by brian-stovall** [CleverRaven/Cataclysm-DDA#20504]
No equipment (or frame) is required to "start vehicle construction". The new vehicle name dialog comes up and 10 minutes is used, but no other result happens. Being near a frame, or having one in inventory makes no difference.

**Comment by Samait** [comment]
That has been happening since about #6300.

**Comment by ynemo** [comment]
same here with new versions.
And if u "pull" other vehicle over the place where you was trying to build bugged one, u would receive message like "no vehicle found" or smthing like this. I dont remember exact message, but it didnt allow to pull other vehicles over bugged construction place.

**Comment by ynemo** [comment]
version 0632

![image](https://cloud.githubusercontent.com/assets/24881844/23968846/812daeda-09d5-11e7-9b5a-6677b9dd2abb.png)

it creates nothing
