### ISSUE TITLE
Choosing a facing direction for the new headlight very unintuitive

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#20512]
Windows, both tiles and console build 6315
Now the player needs to press spacebar after popup is drawn.
No interaction until that.

**Comment by AncientSion** [comment]
I agree 100 % with this. I dont even know what im supposed to do here at all.

**Comment by spacenookie** [comment]
what if popup, message "Choose a facing direction for the new headlight."
is replaced with query_yn("Aim the new headlight? otherwise it will shine forward.")

**Comment by AMurkin** [comment]
Issue is about game "stuck" until sacebar pressed and no information for player about that.

**Comment by spacenookie** [comment]
how about if the popup message "Choose a facing direction for the new headlight." is changed to "Choose a facing direction for the new headlight. Press space to continue"

**Comment by AMurkin** [comment]
It's ok as lame-fix. But i'm sure that annoying keypress wating introduced not many builds ago. Will try to find that build.

**Comment by AMurkin** [comment]
I can not compile source. And I do not know where to find old versions. Can someone else find the version when the change occurred?

**Comment by Leland** [comment]
@AMurkin #2112 was what first introduced rotatable headlights, and #2193 moved it to that interface. Happened about 3 years ago.

**Comment by AMurkin** [comment]
Thanks. Well, now i think @spacenookie suggestion is fine to fix this issue.
