### ISSUE TITLE
Crafting UI don't see the liquids inside of vehicle (tanks)

### ISSUE THREAD

**Issue by Samait** [CleverRaven/Cataclysm-DDA#20511]
Contained liquids in vehicle tanks can't be seen in the crafting UI. 

This start at version cataclysmdda-0.C-6313
in the version cataclysmdda-0.C-6315 continue happening.

In the version cataclysmdda-0.C-6311 the player can use liquids in vehicle tanks in the crafting UI.

(google translate help)

EDIT:
still not fixed in: cataclysmdda-0.C-6328

**Comment by gcaliber** [comment]
Is it a specific tank or liquid? I am using small 10L tanks with water in them currently and don't have any problem with that.

**Comment by Toothspit** [comment]
It's all liquids except 'water' and 'clean water'.

**Comment by Samait** [comment]
first: thanks for mark the issue.
second:
        I use 60L tanks with: salt water , bleach , ammonia , mutagen ...

**Comment by kolsurma** [comment]
Water and Clean Water are special cases: if there's a Faucet or a RV Kitchen in crafting range it will attempt to find the water/clean water from there.

IMO this is not technically a bug, just a limitation.

**Comment by l29ah** [comment]
I think faucet's function should extend to other liquids.

**Comment by i2amroy** [comment]
Appears to work fine now, closing.
