### ISSUE TITLE
Reinforced vehicle parts

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20520]
Vehicle parts now take their HP percentage directly from the item used. This item can be reinforced, which results in reinforced vehicle parts.

This is a pretty horrible mechanic since it means tedious reinforcing of the entire vehicle from the mint condition to mint+1 is a thing.
If unreinforced parts are too weak, we should buff those and get rid of reinforcing. If they aren't, we should get rid of reinforcing without buffing parts.
The only kind of reinforcing that makes sense is accurizing guns, since otherwise the installed guns are naturally less accurate than wielded ones.

But how to get rid of reinforced parts? Un-reinforce all items installed? Un-reinforce the items before dealing damage to them?

**Comment by kevingranade** [comment]
You're not being clear whether you want to get rid of all reinforcement, or
just reinforcement of vehicle parts.  If it's the latter I'd say just cap
vehicle part hp at the level provided by un-reinforced components.
