### ISSUE TITLE
Stuck on map generation if "allow invalid overmaps" set to "any"

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#20533]
It doesnt matter if i set "Overmap generation attempt count" to 1, 2 or 20.
I get stuck on map generation for ever if i set "allow invalid overmaps" to "any"
used city size is 4 and distance 6.
Game 6323

Thank you all devs and mod makers for working on this wonderfull game.

**Comment by Coolthulhu** [comment]
What do you mean by "stuck"? Does the generation go on forever? Is CPU usage by the process always high above 0%?
Does it show the "could not generate" menu once in a while?

It can be either a generation bug (unlikely) or a display bug (this one more likely).

**Comment by ZenZen2** [comment]
It loaded successfuly now but it took a very long time to load (2-5 minutes).
"Overmap generation attempt count" set to 2 and "allow invalid overmaps" set to "any", default mods.
The generation goes almost forever. Stuck at black sreen with the text "please wait as we build your world", cpu usage at 50% (dual core).
Adding pk mod into it, then it seem to never finish loading.

Is it possible that with the option "any" it will keep trying until it get an vaild map ? thats what it seems to me, because setting  "allow invalid overmaps" to default it takes just a few seconds until i get that window to chose unlimited current map for example, and then its a second to play.

**Comment by Coolthulhu** [comment]
Setting it to "any" will make it try up to the generation count.

**Comment by ZenZen2** [comment]
It is possible that the long loading time is a problem of my machine. Im closing this in 2-3 days if nobody else report extreme loading times on "any" setting.

**Comment by Murumuru** [comment]
I have the same issue.
I have tried it and it takes some time. 
I have left it running for around six hours and it still was not generated after all that time. It did load CPU though.

**Comment by ZenZen2** [comment]
In this case im reopening this issue. It seems this problem doesnt apply to many players, else there would be more reports.

**Comment by ZenZen2** [comment]
I see i just caused a duplicate of #20636
closing this again.
