### ISSUE TITLE
Suggestion:  Finite Numbers of Hordes.

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#20534]
Hordes have, it seems to me, waxed and waned in strength and ability over the experimentals since the omnipresent nature in 0.C.

At the moment, it appears they can be quite vast and numerous, easily taking up over 8 hours of a modestly skilled combatant's time.
http://smf.cataclysmdda.com/index.php?topic=19.msg297068#msg297068

This is somewhat disheartening, since I can often see them spawn in the broad daylight.

Finite numbers of hordes that then walk around would allow the player some relief the from crushing weight of hordes, and the cumulative effect of sustained combat noise and zombies car-wrecking.  perhaps even a population that the hordes draw from, and that can replenish over time?

**Comment by Coolthulhu** [comment]
I'd move the discussion to forum. There isn't an obvious solution here (how many hordes? how realized? where should they spawn from? hardcoded numbers, configurable ones, time-based or what?) and most of the issues are game design related rather than technical.

**Comment by kevingranade** [comment]
The hordes are finite, just extremely large.  The problem is since they
draw from an arbitrary population pool and don't all spawn at once, they
help appearing until they suddenly stop, so they very much seem like
they're unlimited.

I've been working on a replacement for this for a while, but progress has
been extremely slow, see
https://github.com/CleverRaven/Cataclysm-DDA/projects/3

**Comment by pisskop** [comment]
Their omnipotence to local sounds means you can never outrun them.  Atm theyre very aware of noises within the bubble, and since the bubble follows you they effectively can home in on you.

**Comment by kevingranade** [comment]
Both true, but as @Coolthulu pointed out, you need more concrete details
about what you want to change.

I was pointing out that I'm planning on entirely replacing the existing
system, I consider it unworkable to use it as a starting point for a
permanent feature.
