### ISSUE TITLE
No more single point pool?

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#20537]
as the title says, was it removed? i can't find it in the options anymore.

**Comment by Rivet-the-Zombie** [comment]
You choose which pool type you're going to use on a per-character basis. It's not in the options menu any more.

**Comment by 321nick** [comment]
ahh, ok. couldnt you have, however, choosen the default?

**Comment by Coolthulhu** [comment]
That's just one keypress away.
We went with that option because having it in game/world options was considered too hidden and having it both in options and menu would be an overkill.
