### ISSUE TITLE
Make NPC able to wear guns with shoulder strap

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#20540]
If gun has shoulder strap installed, then NPC must wear this gun when "% puts away the *gun"

And it would be good idea if he don't forget to wield it if needed ;)

**Comment by ynemo** [comment]
ah, it's too minor

**Comment by Taberone** [comment]
Its not that minor.

**Comment by ynemo** [comment]
There are so many things need to be done with NPC, so this one as i suppose is not important. 

NPC must close chat after receiving "Guard this place" command, same with "i need u to come with me"
NPC must follow engagement and other rules when Guarding (currently, they use any weapon including loud no matter what u told them before) 
NPC command must be on same keys as always even when they are in "base area" and they could receive command "stay on that base" which brakes all default keybindings. 
And more, more, more

**Comment by Night-Pryanik** [comment]
Need in other things is not the reason for not adding this one in question.

**Comment by ynemo** [comment]
I dont want to spam with such minor issues, when it's needed to make complex work on NPC. And looks like developers busy with more important and global parts of the game. That's why i decided to close this issue, which i started. But it's okey if they implement it ))

**Comment by ynemo** [comment]
+ NPC must drink liquids / eat soups from stationary kegs if they want to eat drink and area is not forbiden for npc pickups.
