### ISSUE TITLE
Suggestion: make blade from any swords or big knifes.. 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#20542]
Currently, we can make blades from broadsword or machete.
Why not to add in Blade recipe a lot of other swords and etc. ? 
Probably its not a lot of time to copy-paste names of swords in code... i hope so ;)

**Comment by Mecares** [comment]
Well if you provide a list of items you would like to suggest, the chances that somebody does implement  it would increase significantly.

**Comment by DangerNoodle** [comment]
Obvious examples include arming sword (comparable in blade size to some broadswords), possibly survival knives, glaives, 

The main problem with this recipe is that most things you can make with a blade are inferior to what you can dismantle to obtain one. I can think of no sane reason to dismantle a functional machete only to make a makeshift one.

What might improve the utility of this recipe is if the low-quality steel versions of broadsword, arming sword, etc can also be broken down for blades. Most of these are implied to primarily have fit-and-finish issues, and a makeshift machete is not a significant step up from a mostly functional sword that is merely probe to breaking.

**Comment by ynemo** [comment]
Playing ranged I had a lot of swords in my stock. Probably I could make vehicle blades from them. But I am not sure is vehicle blade better than spike? 


Here is list of weapons, that could be used to make blade
thats include all _inferior and _fake variants of:

//swords and some polearms 
"broadsword",
"arming_sword",
"longsword",
"jian",
"scimitar",
"katana",
"kris",
"estoc",
"zweihander",
"nodachi",
"wakizashi",
"nodachi",
"scythe_war",
"scythe",
"glaive",
"naginata",
"qiang",
"lajatang"   
"rapier" ? it probably to narrow to be blade

//knifes
"machete"
"kukri",
"knife_rambo",
"knife_rm42",
"kris"
"makeshift_machete",
"knife_combat" i am not sure is it big enough 

//other
"sickle" why not?

**Comment by ynemo** [comment]
btw could someone give advice? How can I find vehicle blade code, and recipes of cutting/piercing weapons? I can't find them in Cataclysm-DDA/data/json/

and looks like all weapons have the same durability? it's sad (

**Comment by Rivet-the-Zombie** [comment]
>and looks like all weapons have the same durability? it's sad (

Melee weapon durability is derived from a combination of the item's materials and whether or not it possesses certain item flags.

**Comment by DangerNoodle** [comment]
I would recommend allowing the inferior versions, but not the fake versions. The fake weapons are made ouyt of aluminum rather than low-quality steel.

**Comment by ynemo** [comment]
looks like it's too minor, and I can test it by myself before suggesting.
