### ISSUE TITLE
Getting training from an NPC advances Quest

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#20548]
If you get a quest from an NPC, and then ask for training, and succeed, you get an error message, and then when you ask the NPC about the job, you get a new job. The quest remains in the quest list, but can't be completed.

**Comment by ynemo** [comment]
same here

**Comment by Lazasar** [comment]
Error message has gone away, but the behavior remains

**Comment by ZenZen2** [comment]
Duplicate of #21027 , the other one has more information.
