### ISSUE TITLE
debug: wacky body part hurt

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#20555]
after a mele combat, each time i bleed this debugg pops up.
cant heal it with a rag. After strong bleeding it turned into normal bleeding and then it stoped by itself.
Using pk mod.

FUNKTION : virtual void player::apply_damage(Creature*, body_part, int)
FILE : src/player.cpp
LINE : 3919

**Comment by Coolthulhu** [comment]
Caused by mod badly specifying bleeding part.
Is this PK mod in core or the one in PK's repo? If the latter, you should report it there since we can't do anything about it from our side.

**Comment by ZenZen2** [comment]
Its PK's repo. I will report it to him. Thanks.
