### ISSUE TITLE
json map for specials

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#20554]
Entries for overmap specials should have something akin to what mapgen files have: some kind of map of rows and columns, followed by a key matching a letter to a thing. Or like what vehicles have, a reference map so you can tell what a car will look like and where parts are installed. It's not hard entering a long list of XYZ values to place maptiles, but it does make it very hard to visualize what the finished product will actually look like.  Especially if you start reusing and rotating tiles. 

Ease of use would be better, but, maybe more importantly, it would make it easier for others/modders to interpret what exists. There are only a few giant structures in the game now that would benefit from this kind of thing--the necropolis and the mall--but those are pretty intimidating to decipher and don't make very good examples or templates for people who want to make new stuff.

**Comment by ZhilkinSerg** [comment]
Will it really help? Most of the overmaps specials are up to 3x3 in size.

**Comment by Coolthulhu** [comment]
And they also don't repeat much, so you'd have blocks like
```
ABCD
EFGH
IJKL
```

which wouldn't really improve much.

Do you have any examples where it would actually improve things?

**Comment by pisskop** [comment]
i try to use their relative coordinates in their name.


e.g.

floor_b1_01 is coordinate (0,1,-1)

**Comment by Leland** [comment]
Closing due to lack of recent discussion. Feel free to reopen if there's still interest in development.
