### ISSUE TITLE
`amount_of` for stackable items

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#20565]
Why does `amount_of` function returns 1 for stackable item?

I have made generic `thread` with `"stackable": true` and generic `sinew` with `"stackable": false`.

Player has `6 sinews` and `thread (13)` in inventory.

Function `amount_of` returns 6 for `sinew` (which is expected) and 1 for `thread` (which is unexpected). Is it intentional?

**Comment by kevingranade** [comment]
Please post the full definition of the items, this behavior is based on the
presence of a charges field IIRC.

**Comment by ZhilkinSerg** [comment]
```json
[
  {
    "id": "thread",
    "type": "GENERIC",
    "category": "spare_parts",
    "name": "thread",
    "description": "A small quantity of thread that could be used when sewing.",
    "weight": 1,
    "volume": 1,
    "stackable": true,
    "price": 5000,
    "material": "cotton",
    "symbol": "=",
    "color": "light_gray",
    "count": 50,
    "stack_size": 200,
    "flags": [ "NO_SALVAGE" ]
  },
  {
    "id": "sinew",
    "type": "GENERIC",
    "category": "spare_parts",
    "name": "sinew",
    "description": "A tough sinew cut from a corpse, usable as thread.",
    "weight": 1,
    "volume": 1,
    "price": 0,
    "material": "flesh",
    "symbol": "=",
    "color": "light_red",
    "count": 10,
    "stack_size": 200
  },
  {
    "id": "plant_fibre",
    "type": "GENERIC",
    "category": "spare_parts",
    "name": "plant fiber",
    "description": "Tough thin fiber, taken from a plant.  Can be used as thread.",
    "weight": 1,
    "volume": 1,
    "price": 0,
    "material": "veggy",
    "symbol": "=",
    "color": "light_green",
    "count": 10,
    "stack_size": 200
  },
  {
    "id": "yarn",
    "type": "GENERIC",
    "category": "spare_parts",
    "name": "yarn",
    "description": "Wool yarn, could be used to knit wool clothing.  Also usable as thread.",
    "weight": 1,
    "volume": 1,
    "price": 0,
    "material": "wool",
    "symbol": "=",
    "color": "white",
    "count": 10,
    "stack_size": 200
  }
]
```

**Comment by Coolthulhu** [comment]
`amount_of` returns full stacks, `charges_of` returns charges.
While that isn't very intuitive, the alternative of having `amount_of` count each charge of stackable item as a separate item would be a special case that wouldn't be all that intuitive either but would also be inconsistent.
`amount_of` must not return charges for non-stackable, charged items (such as soldering irons).

Charges aren't a perfect solution, but getting rid of them is a hard design problem so they're the lesser evil right now.

**Comment by ZhilkinSerg** [comment]
Thanks, @Coolthulhu! `charges_of` works fine.

**Comment by ZhilkinSerg** [comment]
See horrible stuff in #20569
