### ISSUE TITLE
church didn't spawn a bible (vs motels Gideon bible spawn)

### ISSUE THREAD

**Issue by MagicalCube** [CleverRaven/Cataclysm-DDA#20574]
I would list the books that i got but it don't know if that would seem useful because they seem to be random(unlike motel which always have Gideon Bibles and phone books), I did however get a religious book "The Four Vedas"(description: old scriptures of Hinduism), don't know if that's supposed to be there?

Also on a side note no bread or wine was found 
what i meant was shouldn't churches have a 100% chance to spawn a lot of religious stuff (that's related to it)

**Comment by MagicalCube** [comment]
i don't know if i should open a new issue for this or not but here it is
I bumped into a motel area (it was labeled as "m" on the map, doesn't have a 2nd floor, spawned in town) it didn't have any curtains on its bed room windows

**Comment by DangerNoodle** [comment]
Intentional, churches are currently meant to generically stand in for other buildings, hence use of randomized books.

Implementing versions with more variety of architecture to mimic other religious such as mosques or synagogues has been discussed, but discussion has not gone anywhere as far as I am aware.

**Comment by kevingranade** [comment]
Yep, also there's no need to make our alternate universe us precisely match the actual us.

**Comment by MagicalCube** [comment]
oh okay i understand now @DangerNoodle, so churches are supposed to be interpreted as other buildings not just religious ones, cuz one of the things that threw me off was an FM 23-16 army marksmanship Manuel

but i guess like @kevingranade said it doesn't have to be exactly like real life it could simulate a different kind of church like the warhammer 40k churches (if of course the church was interpreted as a religious building)

thanks for clearing it up ^-^ 

what about the motel area with no curtains, is it ........ insignificant ?! :(  and i don't know if thats really editable mapgen json files (it seems all windows are "windows domestic" which i assume would have curtains)
