### ISSUE TITLE
Maybe it's good be able to use the car battery to power appliances and tools?

### ISSUE THREAD

**Issue by mdonline2** [CleverRaven/Cataclysm-DDA#20570]
Maybe it's good be able to use the car battery to power appliances and tools?
it seems get a plug?

**Comment by kolsurma** [comment]
Take a look at the UPS, UPS-compatible recharging station, & UPS conversion mod for items.

**Comment by mdonline2** [comment]
But it's need a cruve to use the power, why not just use with plug?

**Comment by ynemo** [comment]
Try **battery compartment mod**. I can't test it now by myself, but looks like it should work as u described.

**Comment by niglow** [comment]
the **battery compartment mod** works exactly that way, I'm using it all the time.

**Comment by mdonline2** [comment]
ok...it still need to reload the big battery...i just curiosity maybe i can stand near the car and use the hotplate to boiled eggs.

**Comment by ynemo** [comment]
u could use special kitchen car part for this.
