### ISSUE TITLE
Cured hide and pelt from rotten ingredients 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#20572]
Just curious, why we can craft cured hides and pelts from rotten? Is it hardcoded or it's made for game balance reasons? 

And how can I change it in my local game? give me some programming tips please.

**Comment by Zireael07** [comment]
@ynemo: Being able to craft stuff from rotten ingredients is a long standing bug of the whole crafting system. Fixing it would require overhauling the whole crafting system. That's why it hasn't been fixed yet although it's a known bug.

**Comment by ynemo** [comment]
Tainted tallow recipe works as intended, it doesn't allow someone to use rotten fat zombie fat. 
Also, crafting dishes from rotten food is sometimes good for special mutants and all such staff. 

I am asking only about leatherworking from rotten hides, in context with making tallow from fresh fat.

**Comment by DangerNoodle** [comment]
Handling the situation of what to do if the player has a mix of rotten and unrotten ingredients has also been a hindrance to this, though there is a precedent in that rotten perishable items can be made if rotten ingredients are used.
