### ISSUE TITLE
The file about mutation

### ISSUE THREAD

**Issue by a710594** [CleverRaven/Cataclysm-DDA#20576]
I found there are 3 files related to mutation(mutations, mutation_category,, mutation_ordering),
but some data isn't enough?
For example, there  is some description about the mutation "Good Hearing" in the file "mutations",
but there is no actual data to describe its effect.
So I guess there may be other files related to mutations,
or it is a mutation without effect?

**Comment by ZhilkinSerg** [comment]
Mutation effects are hardcoded - see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mutation.cpp.

**Comment by a710594** [comment]
Can I make a mod to fix the effect of mutation?

**Comment by ZhilkinSerg** [comment]
It will be hardly possible, what mutation effect did you want to change?
