### ISSUE TITLE
GitHub branch protection

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#20578]
I ran across this concept: https://help.github.com/articles/about-protected-branches/

Seems like something we want to enable for master, in particular these:
* Disables force-pushes to this branch and prevents it from being deleted.
* Require status checks to pass before merging.
Seem totally uncontroversial to me, and I've enabled them, Let me know if I missed something and if there's a problem we can just change it back.

I'm also in favour of enabling:
* Require pull request reviews before merging.
since that's already the policy, though it will eliminate the "except for trivial buildfixes" caveat we allow.

Finally, it looks like the last protection:
* Restrict who can push to this branch.
Would allow us to do things like hand out permissions to write to the github wiki without ALSO handing out permissions tto push to the mainline branch.

P.S. might as well hit up the release branches with the same protections.

**Comment by kolsurma** [comment]
I truly wish github rebased onto the master instead of needing to merge into it with the button.. I suppose I understand why, but it makes the history so messy.

On the note of the release branches: is there a reason we still have branches that haven't been updated in 3 years?

**Comment by kevingranade** [comment]
> I truly wish github rebased onto the master instead of needing to merge into it with the button.

It can...

> is there a reason we still have branches that haven't been updated in 3 years?

Historical interest?  It's not like they cost anything to keep around.

**Comment by kolsurma** [comment]
>It can...

Okay, how? Every button I can find on the website seems to merge instead of rebase. Right now I use git locally to rebase then push that to github.

**Comment by kevingranade** [comment]
* Require status checks to pass before merging.
Has an unexpected issue, it breaks the multi-pull -> build -> test -> push workflow that several of us use.  I'm turning that back off for now at least.

**Comment by kevingranade** [comment]
It would still be usable, but you'd have to re-push any such merges to a branch, wait for a jenkins build, then merge/push.  It would in fact prevent the embarassing instance where one of us does a "trivial" fix that breaks the build.  I'm on the fence about whether it's worth the extra steps.

> Okay, how?

If I open a PR there's a bigass green button right above the comment widget that says "rebase and merge"... oh wait, you mean the update button, IDK, it seems like that should be doable too :/

**Comment by kevingranade** [comment]
No discussion happening, so pointless issue.
