### ISSUE TITLE
Kel-Tec KSG Stats are different when using second magazine.

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#20583]
V 0.C-21676-gff203dbfe5 (tiles) Windows x64  (Current as of a couple hours ago, Jenkins Build 6335)

These are two stock KSGs loaded with 00 shot.  The longer reload time makes sense, but the rest should be identical.  Also, it appears that effects from gun mods also do not apply.

![image](https://cloud.githubusercontent.com/assets/17521661/24069540/6b9837d0-0b78-11e7-8c39-5de01cb75804.png)

**Comment by kolsurma** [comment]
It's because the KSG mod has no inherent weight. I'm messing about with it but it's going to be heavier than it was before, the primary barrel's not going to have as good of a recoil either.

I've got a fix, PR soon.
