### ISSUE TITLE
[Bug] Steel frames from raindrops and morning dew

### ISSUE THREAD

**Issue by Salganos** [CleverRaven/Cataclysm-DDA#20581]
Version 0.c-21672-g 200db7f 390 (edit: on Windows 10)

When starting vehicle construction, regardless of the presence of steel frames, I found myself consistently getting this error message:
```
DEBUG    : item water used by construction is not base item of any vehicle part!

FUNCTION : vpart_id vpart_from_item(const string&)
FILE     : src/construction.cpp
LINE     : 903
```
Ignoring it would cause a vehicle tile to be placed down, which could be disassembled into a free steel frame (there is now a small pile of them in my house and a larger one down the road).  The weather or the fullness of my canteen appeared to have no effect (though it _was_ raining when it first started happening).

Saving, exiting, and loading the game has now instead left me with a slightly different problem, where starting vehicle construction now never does anything, again regardless of the presence of steel frames (or the weather).  It's quite confusing.  (To clarify: frames are not consumed and no vehicle tile is placed.)

I have included the save file, in case that helps.
[Hymera.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/852181/Hymera.zip)

Edit:  A helpful comment has revealed that the initial bug occurs after a material is used in crafting, such as boiling water to make clean water.  This then allows the error message to occur with the used ingredient (water, in this case) as the erroneous base item (as opposed to crafting no vehicle parts out of nothing at all).

**Comment by Coolthulhu** [comment]
Can't reproduce with the save.

**Comment by Salganos** [comment]
Can you actually create a vehicle tile from those frames?

**Comment by Salganos** [comment]
Updating to 0.C-21676-g ff203db fe5 does not change my newfound inability to start a vehicle.

**Comment by ynemo** [comment]
well, i hade same issue. I craft something, then start vehicle construction, and one of ingredients used for previous crafting was showing in debug as starting part of vehicle. 

Basically, to make this bug appear just try to craft anything, and then start vehicle construction

**Comment by Salganos** [comment]
Or try to repair something with a soldering iron too, it seems.  I repaired my arm-guards and now I have made a steel frame out of conjured plastic.  (No chunks were actually consumed.)

**Comment by Salganos** [comment]
Turns out the problem is in the json file for constructions.  Working on adding the ingredient requirements back onto entry.

**Comment by Salganos** [comment]
Nevermind, looks like the line " "vehicle_start" : true " was added between the latest downloadable windows build and now, which covers the requirements automatically.  Further action unnecessary.

**Comment by Salganos** [comment]
... And it looks like that line had been re-added 5 days ago, before somehow getting lost until re-merged 5 hours ago.  Sadly, I am not wise enough in the ways of git to understand why.
