### ISSUE TITLE
Github Sites

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#20580]
Neglected to mention the rationale at first, en.cataclysmdda.com is down and is not coming back up on its original host.  Similarly I don't know either Heroku or Ruby and have no interest in learning them, so even with a dump of the site contents, I'm not particularly interested in trying to stand it back up on a new host.

GitHub sites seems like an outstanding alternative:
* It's dead simple to set up (in fact already done http://cleverraven.github.io/Cataclysm-DDA/ )
* Pushing updates is a simple as committing changes to GitHub.
*  No permissions management required.
* hosting handled by GitHub, they're about 1000x better than us at running websites :D

There are two major options for setup, one is to have github pull the site definition from a docs/ folder in the master branch, and the other is to have a separate branch named gh-sites with just the page definition in it.  You can also set up a different repository, but I can't see a good reason to take that route.

The main reason to go with the gh-sites route is to keep the stream of commits separate, which is a decent idea.

I had an idea about what we can do if they're mixed though, when merging changes, all we have to do to push the changelog to the site is make a file in the docs directory and type a description of what's being merged, and we end up with a changelog.

Github's Jekyll engine is pretty flexible too, so we can actually do a lot of stuff with it.

**Comment by Zireael07** [comment]
I set up a GitHub site recently too, and gh-pages (as a separate branch) is definitely the way to go.

Jekyll is flexible indeed, but a PITA to get working on Windows.

You should be able to do changelogs in a gh-pages subfolder, too? Like a series of blog entries?

**Comment by BorkBorkGoesTheCode** [comment]
Might want to leave a note saying that the forums are in transition.

**Comment by kevingranade** [comment]
> You should be able to do changelogs in a gh-pages subfolder, too?

You can, but that requires mergers to always maintain two local repositories, which makes it less likely that it happens.

Another option is to do some kind of nested repository shenanigans, not sure what that would look like.

> Note about forums.

That's totally out of scope for this issue, we can certainly add a note once we actually put up a site (what's up right now is the Jekyll-ification of the README.md), but this issue is for discussing the site idea.

**Comment by BorkBorkGoesTheCode** [comment]
I was referring to the forum address mentioned on the new page being non-functional. If anybody searched it they would get sent to the broken smf website:


>Community
Cataclysm: Dark Days Ahead main site, includes links to forum, wiki, and GitHub repo: http://en.cataclysmdda.com/
**Forums: http://smf.cataclysmdda.com**
Wiki: http://tools.cataclysmdda.com/wiki
GitHub repo: https://github.com/CleverRaven/Cataclysm-DDA
IRC: irc.freenode.net ; #CataclysmDDA http://webchat.freenode.net/?channels=#CataclysmDDA

**Comment by kevingranade** [comment]
> this issue is for discussing the site idea.

**Comment by BorkBorkGoesTheCode** [comment]
It's a great idea.

**Comment by Leland** [comment]
Wouldn't the homepage of http://en.cataclysmdda.com/ ideally serve the same purpose?

**Comment by kevingranade** [comment]
If you try to follow that link you'll find that it no longer exists, this is a proposal for a replacement for the current en.cataclysmdda.com that allows us to use the existing GitHub mechanisms to manage the site instead of having to build them from scratch.  Once we're set up we could point the distance entries at the GitHub site, we wouldn't stop using that url.

**Comment by Leland** [comment]
Ah, in that case - completely for this. It's open sourced, modern and reliably hosted. I'm a front end developer so I'll absolutely help with a design and layout once this gets going 👍 been waiting for a chance to contribute my skill set to this project in some meaningful way. 

In terms of branching vs a folder, I strongly support going the `gh-pages` route. Less clutter in the main repo code.

**Comment by Zireael07** [comment]
Having the site in a separate branch ensures that someone who makes changes to the game's code only can't accidentally wreck the site's code.

Also less clutter and you don't have to think whether that commit is something important for the game or just a site update.

**Comment by kevingranade** [comment]
I've been going back and forth on this, then realized some things in addition to the clutter issue:
1. A separate branch makes it easier to separate permissions.
2. A separate branch avoids kicking Jenkins every time we push a site update.
3. A separate branch would have a different push model, probably we don't want to require a PR and merge for each site change.

Thanks for weighing in @Zireael07 and @Leland, I was probably going to go with the other route but you made me stop and think about it some more.

**Comment by kevingranade** [comment]
Implemented as a seperate branch.
