### ISSUE TITLE
A case of JSON entry duplication in a game save

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#20593]
This weird issue was encountered by a player.

![game](https://cloud.githubusercontent.com/assets/21075502/24073477/0575b1c4-0c33-11e7-80b0-b674ffbaf27f.png)

Red debug message jumped out every time when he tried to load the game. He sent me the game save, and I confirmed that as the debug message said, `dying` occurred twice in JSON file `o.0.-3`:

```json
[{"type":"GROUP_FUNGI","dying":true,"dying":true},
```

The game save loads perfectly after removing one of the two duplicated `"dying": true`.

He is using Windows 10 Pro 14393 x64 and playing 0.C-21576-g30340ccc00 Tiles.

It's a pretty weird and interesting issue. I'm tracking the issue and any further information will be posted here when it is available.

**Comment by Coolthulhu** [comment]
savegame.cpp:1182 - duplicated line
I probably misclicked something

**Comment by BrettDong** [comment]
Hopeful:
The "duplicated" saving is reproducible. Remove one `"dying": true`, load the game successfully and save it, then two duplicated `"dying": true` occurs again!

**Comment by BrettDong** [comment]
> savegame.cpp:1182 - duplicated line
> I probably misclicked something

What?

**Comment by BrettDong** [comment]
Oops... I thought this was a tough issue...
