### ISSUE TITLE
Debag error when using tool with USP charges 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#20591]
![image](https://cloud.githubusercontent.com/assets/24881844/24073134/a3b5f3b0-0c03-11e7-9820-bff74bc42ae4.png)

I play latest experimental windows

**Comment by ZenZen2** [comment]
Can not confirm. In my game 6342, soldering iton+ (UPS) works fine, it recharges, repairs a car or build new parts into a car. No debug.

What did you do when the debug window appear ?

**Comment by ynemo** [comment]
looks like it solved
