### ISSUE TITLE
Compile failure with GCC 5 and clang 4

### ISSUE THREAD

**Issue by Muffindrake** [CleverRaven/Cataclysm-DDA#20607]
GCC version tested: `gcc (Gentoo 5.4.0-r3 p1.3, pie-0.6.5) 5.4.0`

[build.log](https://gist.githubusercontent.com/Muffindrake/4e5c53cec92e4a76c7ea347e1e86c0d6/raw/e48428b75760da4ce79c7b4e99b652265d679466/gcc540ncurses.log)

clang version tested: `clang version 4.0.0 (tags/RELEASE_400/final)`

[build.log](https://gist.githubusercontent.com/Muffindrake/4e5c53cec92e4a76c7ea347e1e86c0d6/raw/e48428b75760da4ce79c7b4e99b652265d679466/clang400ncurses.log)

`gcc (Gentoo 6.3.0 p1.0) 6.3.0` doesn't generate any such errors - the build fails only because `astyle` said so, which is unrelated to this issue (compiles fine). Both ncurses and tiles don't build on the above.

Suggestions (pick any):

- remove claims of non-existent clang support in COMPILING.md
- resolve build failures on these compiler versions
- ~~make it abundantly clear that only GCC 6 will compile successfully~~

OS: Gentoo, Linux 4.9.16, x86_64

Commit tested: https://github.com/CleverRaven/Cataclysm-DDA/tree/0d7bf2c07297d3f120217ae1c99ead3083090bc2

**Comment by spacenookie** [comment]
I have gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) and game compiles + runs fine.

looks like you have library problems with std::round, according to gentoo forums you must rebuild libstdc++ after upgrading to gcc 5.3.0? (revdep-rebuild -pv --library 'libstdc++.so.6' -- --exclude gcc)

**Comment by BrettDong** [comment]
I have a machine running Debian Jessie with GCC 4.9 building CDDA without problem.

**Comment by Muffindrake** [comment]
@spacenookie If that were the case, I'd have serious issues compiling other large software such as chromium or firefox, but no such problems presented themselves after the time I upgraded GCC to 5.4.0 and rebuild all libraries depending on libstdc++ as per the wiki entry (that's what that command does - it doesn't rebuild libstdc++ itself) :)

**Comment by Muffindrake** [comment]
I tested compiling with GCC 4.9.4 as well - it seems to compile with no issues like 6.3.0. Hence the title change - if you're running GCC 5, please step up.

**Comment by Muffindrake** [comment]
PR #20610 fixes the compile failure on my machine.

**Comment by kevingranade** [comment]
Appreciate the report, but we rarely compile with GCC 6+ (4.8.4 is
typical), and I don't have the clang versions offhand, but the situation is
similar.  You have a problem on your system.

**Comment by Muffindrake** [comment]
@kevingranade The compile failure with GCC 5 is fixed - clang 4 catches the same error without that patch, but that doesn't affect the other errors. You personally didn't seem to come across that issue with gcc, because you're using only a specific older version. Simple as that.

>You have a problem on your system.

Perhaps you should try to compile it with clang 4.0.0 before you suggest that my system is broken. Compilers are software that changes - which may include additional warnings in newer versions that are incidentally treated as errors. 

COMPILING.md doesn't suggest to use only specific versions of clang, therefore I expect either that file to be changed or the compiling problems fixed. Unless of course you can demonstrate that my system is broken beyond belief.

**Comment by wcjones** [comment]
I pulled the latest code and was able to compile with both gcc and clang without needing to change any code.

gcc version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
clang version: clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)

**Comment by feinorgh** [comment]
I have some findings. gcc-5.4.0 displays the same behavior re: 'std::round' on every platform; it requires cmath to be included. In the other translation units cmath is either implicitly or explicitly included via other header files, but src/harvest.cpp seems to be the only exception currently, as far as I could see.

With the suggested minimal change to `#include <cmath>`, compilation and execution is successful on:
* gcc-4.9.4 (native build on Linux)
* clang-3.7 (native build on Linux)
* gcc-5.4.0 (MXE cross compile from Linux to Windows)
* gcc-5.4.0 (Cygwin "native" build)

All versions of gcc-5.4.0 breaks on the missing definition of std::round if it does not include cmath.

clang-3.9 under Cygwin seems to be broken in other ways (at least regarding STL) at the moment, so could not try it out.

I feel quite confident that clang-4.0.0 will be able to compile it just fine too, but trying out every version of every compiler under every system out there is practically unfeasible. The current instructions are fine, in my opinion. If you compile software under heavy development, you can expect things to break from time to time.
