### ISSUE TITLE
Get SMF database migrated to new host

### ISSUE THREAD

**Issue by GlyphGryph** [CleverRaven/Cataclysm-DDA#20614]
Creating this ticket because I'm assuming we *don't* want the forums to go down again in the future, so switching a different host is probably a good idea. It's no longer a rush job though so @kevingranade tell me when you have time and who I should send the db dump too.

Sorry again for letting things go down without making sure this was done first.

**Comment by kevingranade** [comment]
Again, that is my fault, I got the message but didn't understand it or
follow up properly.

I'm waiting to hear back from discourse, if that doesn't happen the most
likely candidates is @rtisdale, they seemed to indicate they just had a
host handy they could use.

**Comment by kevingranade** [comment]
Update, Discourse will accept us under their open source plan (that means Discourse provides hosting gratis).  I'm going to kick off a forum thread to discuss it and get started installing a local Discourse instance to manage the migration.

At some point (if the community doesn't totally hate discourse for some reason), we'll want to do the post-migration-stickies, set-forums-readonly, get-db-dump, import-data, flip-dns thing, next weekend at the earliest, more likely weekend after that.

**Comment by Leland** [comment]
@kevingranade seems like we can close this per your last comment. 

Future reference, here's the link to that forum thread: http://smf.cataclysmdda.com/index.php?topic=14280.0
