### ISSUE TITLE
32bit and 64bit download confusion

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#20619]
On Wiki:
http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Download
you can chose between a 32 and 64 bit version of the Game

On main cataclysm site:
http://en.cataclysmdda.com/
looks like only 32bit version.

Why is there no 64bit version on the main Cataclysm site. Is the 64bit version running better on a 64bit system?

**Comment by kevingranade** [comment]
There's no significant difference other than what dependencies you need to
have installed.
