### ISSUE TITLE
Add item description in consume (shift+e) menu 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#20617]
It would be very practical to see item description in similar way as it is realized in shift+v menu.

**Comment by CoroNaut** [comment]
When I was new to the game, I was constantly drinking drinks from the alcohol store not knowing they were alcohol. This would be something to let players know exactly what they eat before they ingest it for good. I like the idea.

**Comment by Leland** [comment]
It'd likely be difficult to cram that information in there. But I do know @codemime's been working on the consume menu in #20676

**Comment by Leland** [comment]
Closing due to lack of recent discussion. Feel free to reopen if there's still interest in development.
