### ISSUE TITLE
Failed intimidation when convincing NPC to join you doesn't anger them

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20623]
"I'll kill you if you don't join me"
"Yeah, no"

Now, it could be acceptable for a NPC to be badass enough to shrug death threats like that, but the UI explicitly warns of retribution so it must be a bug.

**Comment by Night-Pryanik** [comment]
The message on the intimidation trials is `You may be attacked! Proceed?` Maybe != certain.

**Comment by Coolthulhu** [comment]
But you will never be attacked this way, so it is not correct.

**Comment by Night-Pryanik** [comment]
I'm working right now on adding 50% chance to NPCs become hostile on ALL intimidation attempts. Is this good?

**Comment by raymoo** [comment]
Maybe if you fail the check badly enough the NPC should laugh it off.
