### ISSUE TITLE
Crash when setting an option with query in MSYS2 builds

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20624]
* Load a game
* Open world options
* Select NPC spawn rate
* Type in `100`
* Confirm with enter
* Crash

**Comment by AMurkin** [comment]
Can't reproduce. win x64 build 6347

**Comment by Toothspit** [comment]
Can't reproduce on Linux x64 tiles 0.C-21756-gc7f65b7532, either.

**Comment by Coolthulhu** [comment]
Could be compiler dependent then. I'll change the description.

**Comment by Leland** [comment]
Seems to be a duplicate of #20927, which was fixed by #21742

Closing, but @Coolthulhu obviously feel free to reopen if this is still an issue on your env
