### ISSUE TITLE
Overmap Generation issue

### ISSUE THREAD

**Issue by Murumuru** [CleverRaven/Cataclysm-DDA#20636]
On the latest experimental overmap generation seems to fail almost every time for my on Cities: 8 with Spacing: 4, and fail every time when spacing is more than 4.
Generation also seems to fail every time when I am trying to use mod like PK's Rebalance.

**Comment by BorkBorkGoesTheCode** [comment]
How many mods are installed? There's an issue with mods adding more than a certain number of mandatory locations.

**Comment by Murumuru** [comment]
@BorkBorkGoesTheCode 
It happens even without any mods, if I have City Spacing value bigger than default one.
If I turn mod like PK's Rebalance - then generation fails every time, no matter what values I set in Cities and City Spacing.

**Comment by Leland** [comment]
A dupe of #8649 and, like that issue, fixed by #21212. Can confirm that with OP's "Cities: 8 with Spacing: 4" I can still start.

Another 0.D issue down @kevingranade 👏
