### ISSUE TITLE
Filthy towels require filthy clothing mod to be visibly filthy

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20630]
Introduced in #20546

The only way to check filthiness status of a towel in non-filthy world is trying to use it.

Towels should be a special case for filthy display since they are effectively filthy even in clean worlds.

**Comment by Night-Pryanik** [comment]
With removing soiled variant, we now have no filthy/soiled towels in clean worlds.

**Comment by Coolthulhu** [comment]
Having duplicate mechanic handle the same thing in different worlds slightly differently sounds like an easy way to run into problems.
I'll revert for now since I don't have a good idea on how to fix it.

**Comment by Night-Pryanik** [comment]
`Soiled towel` and `soiled towel (filthy)`?

**Comment by Coolthulhu** [comment]
But then you have the soiled->unsoiled crafting option either only solve one kind of dirt or solve both and be a special case just for towels.

**Comment by kevingranade** [comment]
If you want a magical fantasy world where clothes stripped off of rotting
corpses are clean, why not apply the same lack of logic to towels?  You
haven't made a case for why it should be treated differently, just asserted
it.

**Comment by Coolthulhu** [comment]
> If you want a magical fantasy world where clothes stripped off of rotting corpses are clean, why not apply the same lack of logic to towels?

Because totally subjective perception of "logic" (which has nothing to do with the logic we use in math) should not be used to meme away features pretty much everyone agrees with.
Such as: "Towels filthy enough not to be usable for their in-game purpose should be marked as such in a way that is visible to the player"
