### ISSUE TITLE
Knit Hat should be disassembleable

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#20631]
Knit Hat should be disassembleable like the knit scarf.

**Comment by Xpyder** [comment]
A PR since it's a single line
 #20635

**Comment by Chezzo** [comment]
Whoa, who knew long knit scarfs were walking around with 900 thread for no volume? And why can't ANY of this be made like you would actually do it in real life, with yarn?

Also, you can make all of this stuff out of sinew!? The only source of sinew is to rip it from the steaming fresh hot corpses of your enemies, maybe this could be dropped.

OR! Make NPCs who see you with it not like you, like how some mutations work, or maybe have wearing it nerf your morale.  And if you have the Psychopath trait, it could give you a bonus! Oh yeah, Stylish for Psychopaths. And then we could have shrunken heads, and ear totems, and scalp cloaks, and...

Or just replacing sinew with yarn would prolly work, yeah.

**Comment by Xpyder** [comment]
yeah, they should probably be yarn.  I thought they were, I just saw you could disassemble one and not the other.

**Comment by Coolthulhu** [comment]
Dropping sinew makes sense, but yarn is wool, so it should not be used in cotton recipes.

**Comment by Xpyder** [comment]
Knit anything is made from yarn, so if yarn is wool the items should be wool.

**Comment by Xpyder** [comment]
for those who care IRL yarn can be several different types of materials, but I think it's just wool in game so I'll look into adding those changes.

So far we have:
 - Setting knit hat+scarf to wool 
 - Updating their recipes to take yarn (do I need to change qty or is 1 yarn equivalent to 1 thread?)

**Comment by Coolthulhu** [comment]
> Setting knit hat+scarf to wool

Wool hat and wool scarf already exist.

**Comment by Xpyder** [comment]
That may be, but a Wool hat made from felt and a Knit Hat made from wool yarn are very different.  It would be like the difference between a knit blanket made from wool and a felt blanket made from wool.  They're very different.

The reality is neither version is going to be perfect, but you knit with yarn not thread, and until Yarn can be made from different materials in the game, the knit objects need to match the yarn material type.

Or you could just remove them entirely, but I suspect more people would complain about that than they would about fixing the recipe

**Comment by Xpyder** [comment]
Since the disassemble pr has already been accepted I'm moving the scarf discussion to it's own issue:  #20698
