### ISSUE TITLE
Thyme oil do not spend using on NPC 

### ISSUE THREAD

**Issue by StopGamer** [CleverRaven/Cataclysm-DDA#20638]
I have ++large waterskin with Thyme Oil (4). 
Two of my NPC got bleeding. I used on both of them thyme oil (through "i use item" menu) 5 times each.

- They got healed (to max hp).
- Bleeding wont stop(intended, because description of oil doesnt say that it can heal bleeding)
- I still have 4 Thyme Oil in inventory.

I will try to create save file next time they get bleeding

**Comment by Coolthulhu** [comment]
Seems that contained items aren't used when healing NPCs.
This is a regression from one of the relatively recent med updates.

I think it should be fixed before 0.D.
