### ISSUE TITLE
Unlimited Map choice on Overmap Error Screen lacks explanation

### ISSUE THREAD

**Issue by Murumuru** [CleverRaven/Cataclysm-DDA#20639]
What does "Unlimited Map" do?
I get it as one of the choices once mapgen can't generate overmap and I can choose it, however, I have no idea what it does. 
Is there any explanation?

**Comment by Night-Pryanik** [comment]
Explanation is in #20232.

**Comment by Murumuru** [comment]
Yes, I understand it now, but I think there should be a description in-game also.

**Comment by kevingranade** [comment]
This option shouldn't even be present, we're asking the player to tell us to give up on creating a valid game world.

**Comment by Coolthulhu** [comment]
The only way to guarantee that a world will always be valid is to disable all specials or to forcefully drop them on terrain they do not accept (say, forest cabin in the middle of a desert).
Sectorless overmap generation would be a 90% measure, but there are still edge cases that even sectorless can't cover.

**Comment by kevingranade** [comment]
No, it's not.  As we've discussed before it can be supported by spreading essential specials across different overmaps.  Just because you don't like that option doesn't mean it doesn't exist.
Regardless of the mechanism, having mapgen fail to create a valid map is unacceptable.

**Comment by Coolthulhu** [comment]
> Just because you don't like that option doesn't mean it doesn't exist.

It's not that I don't like it, it's that it simply doesn't fix the problem at hand for most possible settings.

**Comment by kevingranade** [comment]
Obsoleted by #21212, which removed this failure mode.
