### ISSUE TITLE
CBM Weather Reader "feels like" can give odd results

### ISSUE THREAD

**Issue by gcaliber** [CleverRaven/Cataclysm-DDA#20646]
Temperature: 63F
Relative Humidity: 100%
Pressure: 98 kPa
Wind Speed: 36.0 mph
**Feels Like: -1966F**

**Comment by BrettDong** [comment]
Is your character frozen?

**Comment by gcaliber** [comment]
My character is fine, its just the output of the weather reader CBM that is wrong.

**Comment by Toothspit** [comment]
I'm having trouble reproducing this, can you give an exact description of what's going on when it reads that?

**Comment by kolsurma** [comment]
@gcaliber Version, OS, copy of the save?

**Comment by gcaliber** [comment]
I'll get a copy of the save if it happens again. I can't recreate it now.

**Comment by somot** [comment]
Yeah, temperature below the absolute zero (0K, -273.15 C, ~-460 F) is DEFINITELY wrong and physically impossible. Unless this game already violates the laws of physics by having clothing magically increasing your body part temperature by x units, instead of proper insulation calculation.

**Comment by Coolthulhu** [comment]
> Unless this game already violates the laws of physics by having clothing magically increasing your body part temperature by x units, instead of proper insulation calculation.

This is exactly what is happening.

**Comment by Leland** [comment]
Still happening, see https://github.com/CleverRaven/Cataclysm-DDA/issues/21227 for confirmation

**Comment by CoroNaut** [comment]
Figured I would post another picture to show that this is still an issue:
![capture](https://user-images.githubusercontent.com/24307650/50459817-43672900-093d-11e9-8651-d799fdd51ba7.PNG)

**Comment by Fris0uman** [comment]
Debug jump to winter
Drop cloth
Jump in river
Activate weather reader:
![image](https://user-images.githubusercontent.com/41293484/68164413-07d5bc00-ff5d-11e9-8373-54193a9977db.png)

Is someone able to reproduce the bug? Or is it fixed somehow?

**Comment by Night-Pryanik** [comment]
Closing as non-confirmed for half a year.
