### ISSUE TITLE
Suggestion: Add a "please do" or "resources needed" type tag to the issue list

### ISSUE THREAD

**Issue by bdgackle** [CleverRaven/Cataclysm-DDA#20647]
It would be cool if we had a tag that core developers could add to an issue that basically means "yes we are aware of this issue/feature, we want this fixed/implemented from a game design standpoint, but don't have time to actively work it right now".  This would also be a way to mark annoying small bugs that aren't worth the core developers' time, but that they'd like to see fixed.

This already happens informally in the comments, but the issue list is long and it is hard to tell what is still current.  It would be very cool to just search on a tag and get the core developers' wishlist for things that community members would tackle.

Looking through the issues here, there are a lot of balance, interface, and feature requests that I would personally refrain from touching because I am not equipped to make core game design decisions.  There are also bugs that are known issues in systems that are under rapid development/refactor, and are best left alone by people not involved in that.

I assume I am not alone in being someone who would like to help, but is too new or else doesn't have enough consistent time available to become one of the main developers on this project.  I also get the sense that the core devs are feeling a little overwhelmed at times by the volume of issues coming in.  I'm sometimes afraid to jump in, though, because an unneeded pull request would just waste resources required to review and reject it (or worse, even more resources in an attempt to compromise on a change that should be rejected outright).

The resources don't exist to truly prioritize and clean up a 1000-issue long list, but a little gentle and low-effort delegation might allow people on the fringes of the community (people like me...) to provide more effective assistance, at minimal cost to the core dev team.

**Comment by kevingranade** [comment]
What you're asking for is provided by the 'easy fix' tag.
