### ISSUE TITLE
Cleaning Filthy Clothing doesn't stop for anything

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#20657]
Not
Anything

<a href="http://imgur.com/rRf6e5N"><img src="http://i.imgur.com/rRf6e5N.png?1" title="source: imgur.com" /></a>

Not even being eaten alive

**Comment by ZhilkinSerg** [comment]
It seem your player character really loves washing dirty clothes till he dies.

**Comment by Night-Pryanik** [comment]
Same cause as in #20468: washing isn't a long activity.
