### ISSUE TITLE
[Bug] Can't pick up stacks of meat/fat/possibly other items, only does one at a time

### ISSUE THREAD

**Issue by zeropoint101** [CleverRaven/Cataclysm-DDA#20652]
First time posting here. Apologies if I'm doing something wrong. 

When picking up certain items that are stacked with the number in front of the stack like "3 chunks of meat" as opposed to "throwing stick(12)", I can only pick up one at a time. I have to press the right arrow key or "numpad 6", a plus sign shows up next to the stack, it picks up one of the stack and I have to repeat that for however many are in the stack. Manually typing in the number before hand as in other inventory functions doesn't fix the problem either. The only ones I can be sure of are chunks of different kinds of meat and fat. It definitely happens with these, but it definitely does not happen with most other items. 

Version: 0.C-21813-g0dd7fffcc1 (tiles)

Build: 6353

**Comment by ZhilkinSerg** [comment]
Reproduced this.

**Comment by nshcat** [comment]
I can reproduce this, bird eggs are also affected by this.

**Comment by zeropoint101** [comment]
Something I thought I remembered and have confirmed by looking at older Let's Plays... chunks of meat, fat, bird eggs, and other things like this always used to show individually when you first picked them up and never as stacks. Each chunk/egg would be a separate line item. I assume this was had something to do with them being perishable, although I think if you put the same bunch in your inventory at the same time, they would stack in your inventory. I've noticed they are no longer separate line items. I'm guessing this relates to the problem and just thought I'd add this here.

**Comment by RobertoVGoulart** [comment]
I can confirm, this happens all the time with mestre, eggs and fruits. I think It has something to do with the decay system, we can confirm If that's right by pick up the same stack on low temperatures.

**Comment by Coolthulhu** [comment]
Can't reproduce. Need more details.

**Comment by Coolthulhu** [comment]
Could be related to a bug with butchery/harvest that created the items as separate stacks, but that has been fixed pretty long ago.

I'll need a save or methods to reproduce to fix it.

**Comment by nshcat** [comment]
The easiest way to reproduce it seems to be to find a stack of bird eggs. For me, they always show this buggy behaviour. I will try to create save where to stand right in front of such a stack if that is what you need.

**Comment by bdgackle** [comment]
I've seen this too.  Most often with stacks of not-fresh meat.

This has popped up a couple of times on the subreddit as well, so people are seeing it.

**Comment by nshcat** [comment]
I managed to find an example of the bug in my current experimental world.

The character in this save file is located directly next to a fridge which contains **21 Bird Eggs** that show the buggy behaviour when you try to get more than one of them at a time:

https://www.dropbox.com/s/quki8wjond76cld/bug.7z?dl=0

I am using this world in experimental, own binary created from current master branch yesterday evening.

I hope this helps.

**Comment by Coolthulhu** [comment]
Save was helpful, I think I got the bug located.
It happens because the item is count-by-charges, but also stacked. Not sure if this can happen in more recent games, but it's hard to fix "retroactively", so I'll try to fix it in a slower but more resistant way.
