### ISSUE TITLE
[Suggestion] Cooked/raw offal into sausages

### ISSUE THREAD

**Issue by slawr34** [CleverRaven/Cataclysm-DDA#20659]
Another way of using offal late(r) game apart from canning/pickling it or turning it into haggis. Also seems quite realistic. 

Maybe even using the same proportions of offal:sausages as meat:sausages in the recipe currently, as offal drops in smaller amounts - also because the point of sausages were/are for making offal more palatable.

**Comment by kevingranade** [comment]
Please make a recipe pr if you're interested, we have too many open issues to keep suggestions for individual items or recipes around.
