### ISSUE TITLE
MSVC build errors

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#20656]
First time trying to compile CDDA.
Got errors: `..\src\visitable.cpp(839): error C2668: 'visitable<Character>::visit_items': ambiguous call to overloaded function`
On win 10 x64 MSVS 2015.
What am i doing wrong?

**Comment by ZhilkinSerg** [comment]
Are you trying to compile intact source or have you changed anything in the source code?

**Comment by AMurkin** [comment]
Downloaded zip from github and removed LOCALIZE from build flags. That's all.24.03.2017, 23:55, "ZhilkinSerg" <notifications@github.com>:Are you trying to compile intact source or have you changed anything in the source code?

**Comment by AMurkin** [comment]
Actually i have some problems with installing winsdk and retargeted solution version. Without that i've got thousands errors about missing header files. I'll deal with this first.

**Comment by Alien-AV** [comment]
I had a similar issue - there was also an internal compiler error in the mix.

I resolved it by updating my MSVS installation to "Update 3".
