### ISSUE TITLE
NPCs are placed on wrong tiles.

### ISSUE THREAD

**Issue by Reknot** [CleverRaven/Cataclysm-DDA#20654]
I encountered a problem with the refugee centers NPCs, maybe others but they are the ones I noticed. 
They are all spawning in the right relative place, but on the wrong overmap tiles. 
They are always shifted North-West by a few tiles from the entrance if that makes sense?

Some more reports on same issue:
https://www.reddit.com/r/cataclysmdda/comments/60t8h4/static_npc_not_working/
 
Searches on open bugs did not return any hits on this issue so i thought Id throw it in here for someone to maybe look at.

**Comment by Mcrone617** [comment]
I can second this, as the Reddit thread says, this problem also applies to the static NPC's at the commune (either that or they run away quickly when the player approaches.  Probably applies elsewhere also.

**Comment by Reknot** [comment]
Awesome work! Thanks for everything, <3
