### ISSUE TITLE
[bug?]Advanced Inventory management take more time than just take item.

### ISSUE THREAD

**Issue by mdonline2** [CleverRaven/Cataclysm-DDA#20667]
If i want to take item with AIM
I need use 200 ap than just use"g" or "e"
maybe it is a bug?
vision6356

and if i need to "W"ear something with AIM, i can take less ap (normal use "W"ear 1000 and AIM 350)

**Comment by WizardOfOoo** [comment]
I can verify this, the two inventory system take different times to do the same things.

**Comment by Leland** [comment]
Duplicate of #19850
