### ISSUE TITLE
"Low quality" field decay calculations

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20675]
Fields decay when:
```
dice( 2, cur->getFieldAge() ) > fdata.halflife
```

This has the following downsides:
* It is impossible to create "sparks" of fire - all fire must be created with age lower than `halflife/2` or it could annoyingly despawn on the next turn. This makes it impossible to cleanly get rid of the "drop thread, lit it on fire" tactic
* It is relatively expensive for large numbers of fields. For example, a patch of blood. If we ever wanted to have snow as a field, this would prevent that
* The name "halflife" is a misnomer - for large values, the field is likely to decay before it

Instead, it could be solved as follows:
* On field creation (and possibly when its density changes), calculating a decay age for the field
* Storing the field decay age per field instance
* Each turn only 2 `int`s would be compared

**Comment by kevingranade** [comment]
Re: issue #1 I had previously proposed creating a "kindling fire" field
that represented the process of starting a fire.

Not that I disagree with your overall idea, just that it's a much simpler
solution to that particular problem.
