### ISSUE TITLE
Not healing while sleeping, instead healing while awake

### ISSUE THREAD

**Issue by Tyralocus** [CleverRaven/Cataclysm-DDA#20681]
Since updating to the latest Windows Tiles build, my character no longer heals while sleeping (no visible healing after 10 hours of sleep). However, he is now 'rapidly' healing while passing time awake (i.e. while reading, going from half-dead to fully healthy over several hours). My character has no regenerative mutations or abilities as far as I am aware, and this did not happen while playing yesterday, so I figure it might be related to a recent update?

**Comment by Coolthulhu** [comment]
That sounds serious, I'm on it right now.
Any mods?

**Comment by Wad67** [comment]
Can confirm this, just tested on 6359(Curses).

**Comment by AMurkin** [comment]
Me too. No mods.

**Comment by Tyralocus** [comment]
No healing related traits.

I'm running the following mods (all integrated in the game, no additional external mods):
[  "dda",  "filthy_morale",  "no_npc_food",  "novitamins",  "FIC_Weapons",  "realguns",  "ew_pack",  "Medieval_Stuff",  "makeshift",  "More_Survival_Tools",  "nw_pack",  "Experimental-Z-Level",  "no_religious_Texts",  "no_reviving_zombies",  "StatsThroughSkills" ]

The first 4 of those being suggested as default by the game.

**Comment by Coolthulhu** [comment]
I can reproduce the awake healing and I'm about to PR a fix, but I can't get the lack of sleep healing to happen.
