### ISSUE TITLE
Vehicle lights sometimes not working

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#20680]
This seems to happen more at night with freshly-spawned non-debugged vehicles, though I dont know how to reproduce it faithfully, I have a save where it is present.

The lights, headlights and dome lights, usually will begin to work after a time, but whether it is the light level or a overmap-tile distance or a refreshing of vehicle gibblies  I dont know.

Could this be related to when vehicles would refuse to turn off their engines and then a player would be unable to interact with said engine?

Save folder is here:
- https://www.dropbox.com/s/y4rl78p332uf0ff/save.zip?dl=0

This save does use my own Pk Rebalancing Mod:
https://github.com/pisskop/PKs_Rebalancing

**Comment by Coolthulhu** [comment]
Are the lights weak or strong?
Could it be related to weather? For example, snowstorm or something like that totally killing the light output due to flat effect on it.

**Comment by pisskop** [comment]
hunh.  i didnt check.  the lights are listed on the control menu but cannot be activated.

**Comment by Coolthulhu** [comment]
"Cannot be activated" as in activating them does nothing (not even on the menu), activates them but produces no light or something else?

Does the vehicle have enough battery power for them?

**Comment by Coolthulhu** [comment]
Got it

It's overly restrictive power check. You need `epower` in stored battery power to enable things, but `epower` is just `1/373` of a power unit. Meaning that you need 200 battery power stored just to enable headlights.

I'll just remove that.
