### ISSUE TITLE
Current master (caf3ab4) release build fails due to astyle regressions

### ISSUE THREAD

**Issue by bdgackle** [CleverRaven/Cataclysm-DDA#20686]
Building release build on current master (at commit caf3ab4) fails with an error message about astyle regressions.  Files mentioned as regressions are:
1. action.cpp
2. fault.cpp
3. morale.cpp
4. profession.cpp
5. addiction.h
6. bonuses.h
7. cata_tiles.h
8. damage.h
9. editmap.h
10. profession.h

Non-release builds work as expected.  Release builds complete as expected if I comment out the following Makefile line:
````
CHECKS = astyle-check lint-check
````

Exact build command that failed:
````
make clean && make RELEASE=1 TILES=1 -j9
````

Exact build command that worked:
````
make clean && make TILES=1 -j9
````

Exact error message
````
astyle regressions found.
Formatted  src/action.cpp Formatted  src/fault.cpp Formatted  src/morale.cpp Formatted  src/profession.cpp Formatted  src/addiction.h Formatted  src/bonuses.h Formatted  src/cata_tiles.h Formatted  src/damage.h Formatted  src/editmap.h Formatted  src/profession.h
make: *** [Makefile:933: astyle-check] Error 1
````

Building with gcc under Arch Linux, tool versions:
make 4.2.1
gcc 6.3.1
astyle 2.06

**Comment by bdgackle** [comment]
On further investigation, these are all trivial issues.  I will be submitting a pull request to fix.  The bigger issue is the fact that automated checks didn't catch this.  Isn't that supposed to happen in theory?

**Comment by bdgackle** [comment]
Submitted PR to address this by removing the affected files.  This seems to be per Kevin's suggestion in #20211 and #20225.  Leaving this PR as CR/WIP until I get some confirmation, though, as this really isn't my call to make.

**Comment by Coolthulhu** [comment]
> Looks like this might be related to issue #20225. (Are we still using 2.0.5 as 'official')?

Yes.

I'd say it would be better to re-astyle those files under the new astyle.
The more we delay it, the harder it will be (due to more changes).

**Comment by bdgackle** [comment]
I'd submit a PR for this, but it would break the automated build as long as it uses astyle 2.05.

Also, the new astyle bug with respect to bracket placement in if/else means that a few of these files need to temporarily drop off the whitelist once we make the switch (or we break our own standard to make astyle happy).

Maybe I should be over at the astyle repo looking at THAT bug.  :-)

**Comment by Coolthulhu** [comment]
> I'd submit a PR for this, but it would break the automated build as long as it uses astyle 2.05.

Yeah, it needs to be done in one go.

But if there is a huge bug with astyle, we may need to skip a version.
How does the bug look like?

**Comment by bdgackle** [comment]
Basically, in an if/else block, the curly brace following the else is getting moved to the next line.

There is a an example of it in #20211 (complete with code... so I'm being lazy and not repeating it here).

**Comment by bdgackle** [comment]
It looks like my PR that removes these files from the whitelist got merged.  That fixes the specific issue of building with astyle 2.06 that this issue was intended to address.

This doesn't solve the larger questions surrounding astyle updates, but I think that is adequately documented elsewhere, so I'm going to close this issue.  It seems to just be adding noise at this point.
