### ISSUE TITLE
suggestion: gun show thier range if they have been loaded before and are now empty

### ISSUE THREAD

**Issue by MagicalCube** [CleverRaven/Cataclysm-DDA#20692]
makes hoarding them a bit easier

**Comment by Toothspit** [comment]
Range can change with different ammo types though -- this could be confusing if you load a gun and its range drops mysteriously.

**Comment by kolsurma** [comment]
It could show the theoretical maximum range by showing the lowest to highest maximum range when unloaded. For example, Ruger 10/22 (unloaded) would have `Maximum range: 7-13` or similar. 

Of course you could then have theoretical damage, AP, dispersion... so maybe not.

**Comment by 1skandar** [comment]
Yeah, range comes from the ammunition, not the weapon that fires it, though the weapon can modify that range slightly. There isn't a good solution to that, really.

**Comment by Zireael07** [comment]
Hmm, the gun should know what ammo types it can take?
Then you could sort the ammo types depending on their range and just display the first and last entry's range...

ammo bla (range 10)
ammo x (range 13)
ammo op (range 15)

would then give range (10-15)

**Comment by kevingranade** [comment]
This isn't practical due to the model the game uses for calculating range, and breaking from the pattern of showing only the actual stats if the item would make the ui confusing.
