### ISSUE TITLE
Ranked up skill in 'nothing' while firing charcoal kiln (Build 6358)

### ISSUE THREAD

**Issue by MisterFox** [CleverRaven/Cataclysm-DDA#20699]
I threw 500 splintered wood into my charcoal kiln and fired it up, increasing my skill in 'nothing' to 1.

https://d1.dropfile.to/img/2f8148695b4c1ed14b3d2320b81c1eea.png

This was the second time I fired the charcoal kiln on this character. Both times, I used 500 splintered wood. The build number is 6358.

**Comment by Coolthulhu** [comment]
Master it and you'll become the jack of all trades.

It's my fault, I forgot to purge "carpentry" skill uses from some files.

**Comment by ZhilkinSerg** [comment]
Burning wooden things trains `carpentry`? Hmm... Should try burning some textbooks.
