### ISSUE TITLE
crafting bug: can't use more than 200 coal charges with smoking rack 

### ISSUE THREAD

**Issue by MagicalCube** [CleverRaven/Cataclysm-DDA#20693]
it happen when crafting dehydrated meat ,veggies and smoked meat

**Comment by spacenookie** [comment]
limited to 200 charges (x8 batch) when using FOODCO to dehydrate tainted meat as well

**Comment by WizardOfOoo** [comment]
Duplicate of #20049

**Comment by WizardOfOoo** [comment]
Closed via 20746
