### ISSUE TITLE
Bug localization or the game itself

### ISSUE THREAD

**Issue by Honcharuk** [CleverRaven/Cataclysm-DDA#20697]
Win 10 
![screenshot_1](https://cloud.githubusercontent.com/assets/15582553/24365537/f0581294-131e-11e7-8892-db4ce53f17c4.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/15582553/24365650/6627b77c-131f-11e7-8673-e6389d8694f2.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/15582553/24365658/69bbdfbc-131f-11e7-98af-418422590143.png)

**Comment by BrettDong** [comment]
Does `Cataclysm-DDA\lang\mo\ru\LC_MESSAGES\cataclysm-dda.mo` exist?

**Comment by Honcharuk** [comment]
Yes, of course
![screenshot_5](https://cloud.githubusercontent.com/assets/15582553/24414318/ba22ba1c-13e6-11e7-87be-acf3f13e1436.png)

**Comment by Honcharuk** [comment]
Any other language does not change the interface, even after restarting the app.

![screenshot_6](https://cloud.githubusercontent.com/assets/15582553/24418251/1dc5b59e-13f4-11e7-9b0e-6f2e39128f58.png)

![screenshot_7](https://cloud.githubusercontent.com/assets/15582553/24418252/1dc767c2-13f4-11e7-8981-6ff821a5bf78.png)

**Comment by BrettDong** [comment]
Did you download the game from ci.narc.ro? What's your system language?

**Comment by Honcharuk** [comment]
downloaded from http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/?C=M;O=A

![screenshot_10](https://cloud.githubusercontent.com/assets/15582553/24458893/e5b49314-14a2-11e7-8c40-2209023291b9.png)

**Comment by BrettDong** [comment]
I downloaded the latest Windows Tiles x64 build 6367. Everything is
working fine. The game shows localized interface, and I can change the
game language without any problem.

OS: Windows 10 b14393 x64

**Comment by Honcharuk** [comment]
What's wrong with my windows 10?

**Comment by Honcharuk** [comment]
The problem is solved. Helped to reinstall Windows 10 EN on the Russian.
