### ISSUE TITLE
Cannot target enemies past 30 range

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#20708]
Windows experimental console 0.C-21860

I have tried out the new soft cap for ranged weapons, and something isn't working right. I still cannot target enemies using guns like the M2010, which has range 65.

**Comment by BorkBorkGoesTheCode** [comment]
The maximum range stat still tops out at 30 in the gun screen.

**Comment by DangerNoodle** [comment]
Pinging @Coolthulhu due to https://github.com/CleverRaven/Cataclysm-DDA/pull/20535 being incomplete implementation.

**Comment by BorkBorkGoesTheCode** [comment]
Aha, I didn't remember that maximum range is dynamic now. The player must now have maxed out marksmanship, no dispersion, and high perception to achieve maximum range.
