### ISSUE TITLE
Port mods dependent on LUA

### ISSUE THREAD

**Issue by Wad67** [CleverRaven/Cataclysm-DDA#20712]
If LUA support is going to be axed, I'd recommend porting the 3 mods that currently use it.
Prevent Zombie Revivification is the biggest one for me as I would not play without it.
Plus StatsThroughSkills & Zombie Nightvision, providing people still use those as well.

**Comment by Zireael07** [comment]
StatsThroughSkills is probably even more used than prevent revivification.

**Comment by kevingranade** [comment]
That's the plan, but we don't need an issue to track it :/
