### ISSUE TITLE
Title, MOTD, credits, etc. are in English on a fresh downloaded game on Windows

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#20713]
The default option for language is _System default_. So our program has to figure out which language is to be displayed. GNU gettext is able to auto-detect the system language and load the correct translations, while when loading the title ASCII art, MOTD, credits, and name generator data, the system language detection is done here in `path_info.cpp`:

```C++
std::string PATH_INFO::find_translated_file( const std::string &pathid,
        const std::string &extension, const std::string &fallbackid )
{
    const std::string base_path = FILENAMES[pathid];

#if defined LOCALIZE && ! defined __CYGWIN__
    std::string local_path_1; // complete locale: en_NZ
    std::string local_path_2; // only the first part: en
    std::string loc_name;
    if( get_option<std::string>( "USE_LANG" ).empty() ) {
        const char *v = setlocale( LC_ALL, NULL );
        if( v != NULL ) {
            loc_name = v;
        }
    } else {
        loc_name = get_option<std::string>( "USE_LANG" );
    }
    if( loc_name == "C" ) {
        loc_name = "en";
    }
    if( !loc_name.empty() ) {
        const size_t dotpos = loc_name.find( '.' );
        if( dotpos != std::string::npos ) {
            loc_name.erase( dotpos );
        }
        const std::string local_path_1 = base_path + loc_name + extension;
        if( file_exist( local_path_1 ) ) {
            return local_path_1;
        }
        const size_t p = loc_name.find( '_' );
        if( p != std::string::npos ) {
            const std::string local_path_2 = base_path + loc_name.substr( 0, p ) + extension;
            if( file_exist( local_path_2 ) ) {
                return local_path_2;
            }
        }
    }
```

This works fine in *nix systems. On a Simplified Chinese Linux, `setlocale()` returns `zh_CN`, the game attempts to read `"data/names/"+"zh_CN"+".json"`, succeeds!

However, on a Simplified Chinese edition of Windows, `setlocale()` doesn't return `zh_CN`. It seems Microsoft [has their own locale names](http://msdn.microsoft.com/en-us/library/x99tb11d.aspx). What it returns is `"Chinese (Simplified)_China.1252"`. The following file read fails of course. There is no `data/names/Chinese (Simplified)_China.1252.json`!

This blog describes the same problem: [http://www.g-loaded.eu/2011/02/27/locale-windows/](http://www.g-loaded.eu/2011/02/27/locale-windows/)

Two probable solutions I see:

* Overcome the Microsoft-flavored locale names issue. Write a list of mapping rules from 'Microsoft flavored locale names' to '*nix flavored locale names', and convert the names in order to load the correct translated assets.

* Pop up a language selection window at the first run of the game before the main menu shows, demands the player to specify the option.

**Comment by kevingranade** [comment]
Foolproof but incredibly annoying :/

**Comment by Leland** [comment]
Note #20665 – on macOS the game will start in the secondary, rather than primary, language set.

Maybe that detection doesn't work so well on *nix systems after all?

E.g given
<img width="219" alt="screen shot 2017-08-23 at 8 01 19 pm" src="https://user-images.githubusercontent.com/714017/29643652-6bf8a280-883e-11e7-97bc-7c6a0af3774f.png">

I'm presented with:

<img width="1274" alt="screen shot 2017-08-23 at 8 06 08 pm" src="https://user-images.githubusercontent.com/714017/29643661-82e73af6-883e-11e7-86a3-bd22b2f48f60.png">
