### ISSUE TITLE
Excessive waste when chopping trees or logs to planks.

### ISSUE THREAD

**Issue by FenodyreeAv** [CleverRaven/Cataclysm-DDA#20718]
When cutting trees into planks it's not uncommon to only receive three or four two by fours.
Cutting a log usually results in receiving only one plank and a lot of splinted wood.

I seem to remember it not always being this bad with proper tools.

This might be because of the removal of construction as a skill, and the function that works out the amount of waste does not check fabrication?

**Comment by Reclusive-reptile** [comment]
See #20701 For pending fix.

**Comment by kevingranade** [comment]
This is reversed now, planing a single tree section yields 70 2x4s, AFAICT the maximum yield should be more like 30, and that's with a sawmill, with an axe there would be significantly more waste.

**Comment by Coolthulhu** [comment]
Maximum number of 2x4s never changed: it was always hardcoded as 12 per log.
The only thing that changed is that the used skill is more likely to be leveled up high. It maxes out at 6 skill, when it guarantees 12 per log.

**Comment by kevingranade** [comment]
The 70 is per tree section, which is still excessive.
