### ISSUE TITLE
Debug: Zombie was not found in the tracker

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#20721]
debug: das Zombie was not found in the tracker

function : int_game::mon_info(WINDOW*)
file: src/game.cpp
line: 5707

game: 6343
pk mod latest

got around 10 of this debug windows in a row. Was driving a bus and killing some zombies with it. It didnt crash the game.

**Comment by Leland** [comment]
@ZenZen2 do you feel that this is worth keeping open? Without a savefile there isn't too much information to go off of here.

**Comment by ZenZen2** [comment]
@Leland you are right, im closing this.
