### ISSUE TITLE
Suggestion: Force/Persuade NPC to wear a gear from their item lists

### ISSUE THREAD

**Issue by nizhuan-jjr** [CleverRaven/Cataclysm-DDA#20726]
We can make NPC to take off clothes in the clothing management system, but we can't make them to wear clothes from their item lists under the system!
It pops out my item list(**not theirs**) when I tried to manage NPC's clothes and pressed e, so I can't force them to put on an gear, even though the gear could be essential to their survival.
They won't put on the gear either if I just give to them or let them to use the gear(since it's only wearable not usable).
So my suggestion is that maybe the clothing management system for NPCs needs to be tweaked a bit to allow players selecting the clothes from NPCs' item lists by pressing e.

**Comment by jzambo** [comment]
My workaround is to drop item(s) and open advanced inventory on NPC: https://github.com/CleverRaven/Cataclysm-DDA/issues/21347

**Comment by Coolthulhu** [comment]
It was because originally I intended to preserve the barebones "ownership" system NPCs had at that time.
Same for NPCs trying to limit their encumbrance.
It's fine to get rid of both those behaviors - NPCs need babysitting and shouldn't pretend otherwise.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
