### ISSUE TITLE
Suggestion: Lighters being able to be used as a light source

### ISSUE THREAD

**Issue by A1300L** [CleverRaven/Cataclysm-DDA#20722]
Like the title says much like in real life if you activate a lighter while the flame is lit it isn't much but you can still see very little in front of you (especially in a confined space). For example lets say its night time and your in a science lab and you happen to find a lighter and you need to craft something but o whelp no light cant see to craft, but if you could activate the lighter just to see a little bit the lighter could only light the tile that your in kinda like how the flashlight app lights up all the tiles around you I feel like since its just the lighter the drawback of using it means you can still craft in the dark but it uses the charges also only lights the tile that your in, also being able to read with the lighter in the dark should be allowed
Thanks for reading just a suggestion <3

**Comment by DangerNoodle** [comment]
Refillable lighters can do so already. That said, it does cause some problems. You need to keep the lighter depressed to keep it lit, unlike a Zippo-style lighter. Additionally, I can confirm from personal experience that keeping a lighter lit for longer than 10 to 15 seconds is a terrible idea if you intend to light anything else shortly afterward, as the sparker wheel will heat up. Keep it lit long enough and the plastic will melt, generally rendering it unusable, and possibly causing a fire and/or fuel leak if left on long enough.

**Comment by kevingranade** [comment]
Agree with @DangerNoodle, non-zippos don't actually work this way.
