### ISSUE TITLE
Smoking rack is ~treated~ as a charcoal smoker

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#20736]
Version: 0.C-21914-g44ff41e1c6 (tiles)
Build: 6368
OS: Windows 7 Professional x64 SP1

I have a smoking rack loaded with more than a thousand charges of charcoal, but I'm only able to batch craft using up to 200 charges (the limit of a charcoal smoker).

**Comment by AMurkin** [comment]
Duplicate of #20049

**Comment by WizardOfOoo** [comment]
Cloves via #20746
