### ISSUE TITLE
Altenator should produce power based on the engine they are attached to.

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#20732]
Nothing too complex, but there should be some sort of minimum engine size for each altenator. A V4 gas engine should have a tough time getting full power from a truck altenator, a motorcycle engine the same from a car altenator and should get very little power from a truck altenator. And foot pedals should get next to no power from anything but a motorcycle altenator, and not a lot of power from that. 

Alternatively (hah) each engine could have a max power they can generate, and have that power capped by the altenator attached. That should be a simpler solution, something like power_produced = lowest (engine, altenator) or  0 if no altenator attached. Which would also eliminate the current bug of attaching a truck, car, and motorcycle altenator to one engine. 

A generator type altenator, like the 7.5 kw or whatever it is, could be special cased to double (or something) the power an engine can produce at a significant penalty to motive force (as in an engine hooked up to a generator versus an altenator would trade electrical power produced for engine power produced).

**Comment by Toothspit** [comment]
Alternator load on a real engine is generally negligible.. even a 7.5kW. There is currently a flat engine power penalty when using an alternator, larger penalty for larger alternators, and this is fairly close to real life, with engine power output having less of an effect on alternator power output than raw engine speed. A 7.5kW 'aternator' is run on an engine small enough to be person-portable, and car/truck alternators have outputs in hundreds of watts relative to the engines' hundred-ish kW output. The alternator should fail much sooner than even small engines will have trouble powering the load.

I'm not totally clear on the epower->battery conversion ratios, but it seems to model real engines decently enough. Am I missing something?

**Comment by 1skandar** [comment]
Eh, that said alternators are sized and fitted to the engine they run on. No way you are fitting an alternator from a semi on a motorcycle engine, as an example.. And the less said about the ridiculousness that are pedal powered alternators the better. And, well, trying to interchange alternators between any two vehicles picked at random usually won't work, without major tinkering as they are fitted to the model of the engine. My suggestion may not be realistic,  but it does somewhat model the difficulties of installing an alternator on an engine that it wasn't designed for, And it limits the excess epower that an engine can produce, something that is important for game balance.

And the 7.5 kw generator is 100 pounds just by itself, technically man-portable but just barely. And, well, a generator is quite different anyway. Instead of being belt driven like a vehicular alternator, the electrical generator tends to be driven directly via flywheel and it is designed with different goals in mind than a vehicular engine, steady rpm and fuel efficiency versus higher torque and performance. Converting a vehicle engine to a generator is difficult and inefficient and I haven't heard of a case where the engine was still driveable afterwards. Modeling that conversion is beyond the scope of the game, but I'd say it is reasonable that a vehicular engine tuned to act as a generator would lose a lot of usefulness as a means of propulsion.

**Comment by Coolthulhu** [comment]
That sounds relatively simple, though I'm not sure if it's not a bit too restrictive.
We'd need to inform the players about the limits somehow.

Also, I'm not sure if the engine system is ready for that. At the moment, there is no penalty for running an alternator on most engines.
Maybe we should start by bumping the load alternator causes on engine first?

I think it could be relatively simple to have the alternator disengage when batteries are full. I'm not sure of it because that section of code was tinkered with quite a bit, reverted and is a mess in general, but it should be doable.

**Comment by 1skandar** [comment]
Looking at the numbers I think part of it is that combustion engines are drawing way too little power. In real life an alternator produces enough electrical power to run the engine and the accessories and then a little left over to charge the battery. However in game a truck alternator produces enough epower to run 3 of the largest engines. 

Part of it is the fact that we only have 3 alternators where we should really have one alternator per engine.  Since I know that isn't practical, perhaps a rebalancing and renaming could be done? Instead of car and truck alternators, renaming them small and large alternator and adding to the description "Suitable for 6 cylinder and smaller engines" and "suitable for 8 cylinder and larger engines" and restricting them thusly would be clear enough, I think. And restricting motorcycle alternators to motorcycle engines should be clear enough as it is.

And then balance the epower produced by the alternators to be 250 over engine drain for the smallest engine that they can be fitted on and roughly 150 for the largest. Enough to run the engine and headlights and charge the batteries slowly.

As for the generator it really should restrict or remove the ability for the attached engine to propel a car. And changing its description to note this would be clear enough.

Oh, and just flat out disallow foot pedals to run an alternator because that is beyond silly. Perhaps adding a tiny alternator specifically for that purpose that produces only 50 to 100 epower. much like a solar panel or two.

**Comment by kevingranade** [comment]
Suggestions here are:
> minimum engine size for each alternator

As you point out, this is arbitrary and makes no sense, let's drop it.
> base alternator output on engine type it is attached to

Again, making things not work like they work irl is a very hard sell.
> rebalance alternator output and/or engine energy drain so that alternators barely cover the engines they spawn with.

This is fine.  I dont know why you think we can't have more alternators, we definitely can.  If we did go with one alternator per engine, we would have the engine definition also create the attached alternator, so the stats would match automatically.  I'd like to see sources for your statement that Alternators only barely exceed the energy requirements of the attached engines.

> make generator disable driving with the attached engine.

I don't buy this one, the transmission required to make it happen is complex, but exists irl, and we currently allow vehicle layouts that have the same requirements.  We can revisit this if we overhaul the vehicle system to require transmissions to link power sources and sinks, but until then this would be an arbitrary exception to the existing system.
> disallow foot pedals from running alternators

I see no reason to do this categorically, there's no reason you couldn't make this work with the addition of a simple flywheel (as you point out, the problem isn't total power output, but consistent rpm).

Feel free to open an issue to flesh out an alternator rebalance, possibly increasing the variety of Alternators, but the rest of the issues are non-starters.
