### ISSUE TITLE
Wheel installation/repair skill requirement probably too high and needs to be double checked for logic and balance

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#20738]
Currently wheel installing and reparing require mechanics up to 4. But at the same time messing with car batteries reqirerment is mechanis 2 mostly.

Wheel installing/reparing  requirment  needs to be double checked  before 0.D for logic and balance.

**Comment by Coolthulhu** [comment]
"Logic" in the sense of "realism" (this is a misuse of the word "logic", by the way) is not a problem here.
In fact, welding a damaged wheel into perfect shape should require more than just 4 mechanics.
Same for installing a wheel: you aren't just placing the wheel on a ready axle, but fabricating the axle (and often the transmission for it) first.
Changing a wheel can be done at 0 skill, by using the "change wheel" command.

Now that we got realism handled, the only question left is balance.

**Comment by Firestorm01X2** [comment]
>Changing a wheel can be done at 0 skill, by using the "change wheel" command.
Ok. Problem solved. 
I guess I should at interface better.
