### ISSUE TITLE
"Realistic" antibiotics/infections

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20742]
Antibiotics cure infection instantly by turning it into "recovering from infection".
A more realistic approach would be to simply make them prevent infection from advancing (or slow it down).
Then the infection would start timing out as usual for effects, but if it didn't start recovering, it would lapse back to progressing infection once antibiotics timed out.

This effect could have multiple strength ratings, so that you could try to save antibiotics by taking them less often than necessary (let's disregard antibiotic resistant diseases here) and hoping immune system will kick in.

End result would be that antibiotics would be less of a "beat infection instantly and forever" thing - a stack of 15 antibiotics is generally enough for life. But mostly just flavor.

Marking as long term because even though it is trivial, it would be rather tedious without autoeat. Also because it conflicts with the hardcoded effect refactor.
On an unrelated note, we could use a "Bloat" tag, for suggestion that exist mostly for flavor.

**Comment by Toothspit** [comment]
How would you suggest making this transparent to the player? I can't make an informed decision about rationing my antibiotics without knowing how long they're effective for -- is that, like hiding health, part of the flavor?

**Comment by Coolthulhu** [comment]
> How would you suggest making this transparent to the player?

First off, displaying usage notes in item description. "Take one every x hours", with x being the time around which antibiotics started wearing off, but their effect is still strong enough that it's safe.

Then:

Variant 1:
Displaying the "Took antibiotics" effect in effect list and giving messages in handhold-y fashion, like "Remember to reload mr. Freeman" except with antibiotics instead of ammo and mouth instead of gun.
Mildly immersion-breaking, but painless for the player.

Variant 2:
Spamming player with "your infected wound is festering" when an unmedicated infected wound exists. This would be used to tell apart medicated wounds (just painful) from unmedicated (festering and growing worse).

**Comment by Noctifer-de-Mortem** [comment]
We can have antibiotic tablets that would affect all infected wounds but be slower and antibiotic ointment that is faster but affects only one wound.

**Comment by Tharn** [comment]
Not to sound like a hippie, but there are also a number of natural antibiotics that exist in-game already. Honey, garlic, onions and thyme oil for example. A character could eat one of these or apply honey as a wound dressing. It was done historically.

Generally yes - you should have to handle infection over a number of days. But antibiotics and antibiotic pills should not turn into the be-all. Other things influence how well the body handles infection. Vitamins and a healthy and diverse diet play into this. Cleanliness. Rest.

**Comment by kevingranade** [comment]
This has been implemented.
