### ISSUE TITLE
"Force Y/N in prompts" setting not working as expected.

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#20741]
Expected behavior: The Y/N prompt can only be answered by pressing 'Y' or 'N'.

Actual behavior: Pressing any key or moving the mouse cycles the selected (highlighted in white) option between Y and N.  If you then hit enter you can select between Y or N without ever pressing 'Y' or 'N'.

Windows x64 0.C-21914-g44ff41e1c6 (tiles)
Jenkins Build 6368
Default mods

**Comment by WizardOfOoo** [comment]
Basically, I can select Y/N with the arrow key and hit Enter.  
The setting doesn't do what it says it does, IE force me to hit Y or N

**Comment by kolsurma** [comment]
Other than the mouse movement cycling at 200mph, I find it rather useful that it alternates the choice. And it DOES force you to choose between Yes or No, not just by pressing Y or N. 

If pressing Y or N doesn't choose the correct option, that's a bug.

**Comment by WizardOfOoo** [comment]
It says:

![image](https://cloud.githubusercontent.com/assets/17521661/24558631/6e801592-1601-11e7-825a-244764cffaff.png)

If the "Actual behavior" is not a bug then why have the setting in the first place?  What is it's purpose?  Why would not accepting y or n matter?

**Comment by kolsurma** [comment]
I didn't say it wasn't a bug, just that it was useful.

Hm, for that particular option my guess is that it's to force the user to read the prompt and not automatically continue on. I don't particularly agree with that logic (if that's the actual intention). IMO the certain important actions (like committing suicide) should always be case-sensitive regardless of the option.

**Comment by kevingranade** [comment]
Yea the capital Y/N thing is effectively a speed bump, I don't think it's a
good idea, but some people really want it.

**Comment by WizardOfOoo** [comment]
I think I just misjudged the intention behind the setting.

Thanks for the feedback!  (Love this game)
