### ISSUE TITLE
Parts continue to operate on dead or missing battery

### ISSUE THREAD

**Issue by Toothspit** [CleverRaven/Cataclysm-DDA#20745]
Linux gcc x64 0.C-21907-g2499660820 tiles

[This line](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/vehicle.cpp#L3574) is supposed to kill the alarm the moment there's not enough power (from what I can tell). Removing all batteries does not stop the alarm, however.

Removing a battery while a scoop is powered seems to stop the scoop from hoovering up items, but does not stop it from making noise.

I'd fix it, but there's something else going on beyond my ken. A save/reload makes the alarm stop, but the scoop turns off only after some turns have passed. [Here's a save](https://github.com/CleverRaven/Cataclysm-DDA/files/884516/BatteryTroubleshooting.zip) and repro steps:

A.1. The vehicle to your west has no battery. Attempt to hotwire it, fail, and set off the alarm. Nothing is powering the alarm.
A.2. Turn on the scoop on the bike to your east (do a loop to verify it's working), remove the battery, do a loop to verify the scoop is in a weird voodoo state.
A.3. Save&quit, reload.
B.1. The alarm is no longer on. You may re-fail hotwiring it to set the alarm off again.
B.2. The scoop is still on momentarily, do a loop to verify.
C.1. Eventually the scoop will no longer make noise when the bike is ridden. I can't pinpoint exactly how long this takes.

This looks like a hard problem, so any suggestions on a fix are definitely welcome. The easy way (it seems to me) is to add a check for battery power to each of scoops', alarms', etc.'s existing functions, but the voodoo going on with the scoops makes me think I'm missing something here.

Thanks to muffindrake in IRC for pointing this out.

**Comment by AMurkin** [comment]
Perhaps, it is implied that a separate battery for alarm is not displayed in the interface. It is difficult to detect and remove, and it discharges approximately simultaneously with the main battery.

**Comment by Toothspit** [comment]
I thought that might be the case, but there's existing code that's supposed to shut off the alarm the moment there's a deficit of battery power. If a separate battery were implied, that code wouldn't be there. If it *should* have a separate battery, we should remove the bit that turns it off. If not, we have code that's not working as it should be.

**Comment by l29ah** [comment]
I've just removed the car battery and triggered the alarm afterwards on master.
