### ISSUE TITLE
Stims and depressants aren't deadly

### ISSUE THREAD

**Issue by Toothspit** [CleverRaven/Cataclysm-DDA#20757]
Linux x64 gcc 0.C-21916-g18a9e4dd43 tiles

Crack has a "stim" value of [40](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/comestibles/med.json#L481), tainted tornado has a "stim" value of [-60](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/comestibles.json#L7883); these are the two extremes I found. You can consume both of them indefinitely (as long as you drink water and smoke pot to combat nausea) without dying, but [this bit](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/player.cpp#L4405) is supposed to kill you much more quickly than thirst.

Repro ([here's a save](https://github.com/CleverRaven/Cataclysm-DDA/files/887394/CrackTornado.zip) already set up):

- Obtain gobs of crack, tainted tornado, and optionally water/marijuana.
- Smoke a few grams, drink some water, smoke a bowl, repeat. No heartsplosion.
- Slam a few tornados, drink some water, smoke a bowl, repeat. You may need painkillers or food. No vegetablitis.
- Shoot ~3g of heroin (wait a few minutes), finally die.

LD50 for crack is <10g, but smoking a kilo is non-lethal in current build. LD50 for heroin is <5g, but drinking gallons of a ~twice-as-powerful depressant is non-lethal in current build. Heroin *does* kill (via the painkiller check?), so this issue specifically regards +/-"stim"s from where I'm sitting.

**Comment by Coolthulhu** [comment]
It's because stim/pkill death is delayed to the next full 5 minute tick.
2 heroin uses in a row are enough to kill a non-addicted character.

**Comment by Toothspit** [comment]
I can't reproduce that. You can kill the character in the save above with just 2 heroin uses? I can literally smoke crack for a full day, pausing only for water and to vomit.

**Comment by Coolthulhu** [comment]
It seems not to be guaranteed with 2, but is with 3.

Looks like `stim` effect is capped at `3 * stim` of the food. And it needs to reach +/-200 (or 250?) to kill.

We can either increase the cap or invent some other kind of cap. Increasing has the problem of allowing stacking plain coffee for really strong effect.
We could have a witcher-ish system where each substance has "toxicity" that causes scaling penalties (up to constant damage) above certain point.

**Comment by Toothspit** [comment]
The witcherish method seems like the cleanest way to handle this, but there's still the problem of not blacking out from too much negative stim. Maybe pkill could add large negative stim as well, and not handle it separately when determining the cap?

Researching now, will post a table of suggested toxicity values once complete. I'll leave the coding to those who know what they're doing.

**Comment by Toothspit** [comment]
[Here's the promised spreadsheet](https://github.com/CleverRaven/Cataclysm-DDA/files/888167/toxicity_chart.xlsx), the 'friendly' page is for exporting, the 'working' page shows my scribblework/explanations.

The toxicity_per_use column is the more useful one for this issue and is based on the dosage we currently use; the _per_mass one is just the substance's raw lethality without taking our dose sizes into account, scaled 0-100 nontoxic-poisonshroom.

**Comment by Coolthulhu** [comment]
Overall good for a start, though they do fray at the details:
* Anything with value below 5% is effectively non-toxic
* Alcohol is calculated by mass, while the in-game one is more "quantified" - there is weak (beer), medium (wines and liquor) and strong (just moonshine)
* Wild apple is just 1 charge of liquor and 1 of juice (the in-game "cider" isn't really cider), meaning it is as toxic as 1 dose of liquor, but on the chart it got 4 times as much (similar for other mixed drinks)
* Drying shrooms causes them to lose potency linearly with water mass
* Water poisoning is negligible, caffeine could easily score a point or half on the scale

LD50 is not a good measure of overall toxicity, though if we only want this to handle death from overdose, it could work.
