### ISSUE TITLE
Inconsistency for "reversible:true" in armor recipes.

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#20754]
For example, pants_cargo & tshirt could be dissembled while others shirts & pants dont.

Here is a long list of all armor item and its reversible stats.

FILE | item | reversible
------------- | ------------- | ------------------
arms.json       |               2byarm_guard                            |       true                                               
arms.json       |               arm_warmers                             |       
arms.json       |               armguard_bone                           |       
arms.json       |               armguard_chitin                         |       
arms.json       |               armguard_hard                           |       
arms.json       |               armguard_larmor                         |       
arms.json       |               armguard_lightplate                     |       
arms.json       |               armguard_metal                          |       
arms.json       |               armguard_paper                          |       
arms.json       |               armguard_soft                           |       
arms.json       |               elbow_pads                              |       
arms.json       |               stockings_tent_arms                     |       
arms.json       |               stockings_tent_arms                     |       
arms.json       |               vambrace_larmor                         |       
feet.json       |               bastsandals                             |       
feet.json       |               boots                                   |       
feet.json       |               boots_bone                              |       
feet.json       |               boots_chitin                            |       
feet.json       |               boots_fsurvivor                         |       
feet.json       |               boots_fur                               |       
feet.json       |               boots_h20survivor                       |       
feet.json       |               boots_hsurvivor                         |       
feet.json       |               boots_larmor                            |       
feet.json       |               boots_lsurvivor                         |       
feet.json       |               boots_plate                             |       
feet.json       |               boots_survivor                          |       
feet.json       |               boots_western                           |       
feet.json       |               boots_winter                            |       
feet.json       |               boots_wsurvivor                         |       
feet.json       |               boots_xlsurvivor                        |       
feet.json       |               clogs                                   |       
feet.json       |               footrags                                |       true                                               
feet.json       |               footrags_fur                            |       true                                               
feet.json       |               footrags_leather                        |       true                                               
feet.json       |               footrags_wool                           |       true                                               
feet.json       |               leathersandals                          |       
feet.json       |               mocassins                               |       
feet.json       |               nomex_socks                             |       
feet.json       |               shoes_birchbark                         |       
feet.json       |               socks                                   |       
feet.json       |               socks_bag                               |       
feet.json       |               socks_wool                              |       
feet.json       |               stockings                               |       
feet.json       |               straw_sandals                           |       
feet.json       |               swim_fins                               |       
feet.json       |               thermal_socks                           |       
feet.json       |               wetsuit_booties                         |       
hands.json      |                gauntlets_bone                         |       
hands.json      |                gauntlets_chitin                       |       
hands.json      |                gauntlets_larmor                       |       
hands.json      |                gloves_bag                             |       
hands.json      |                gloves_fingerless                      |       
hands.json      |                gloves_fingerless                      |       
hands.json      |                gloves_fingerless_mod                  |       
hands.json      |                gloves_fsurvivor                       |       
hands.json      |                gloves_fur                             |       
hands.json      |                gloves_h20survivor                     |       
hands.json      |                gloves_hsurvivor                       |       
hands.json      |                gloves_leather                         |       
hands.json      |                gloves_light                           |       
hands.json      |                gloves_liner                           |       
hands.json      |                gloves_lsurvivor                       |       
hands.json      |                gloves_plate                           |       
hands.json      |                gloves_survivor                        |       
hands.json      |                gloves_wool                            |       
hands.json      |                gloves_work                            |       
hands.json      |                gloves_wraps                           |       true                                              
hands.json      |                gloves_wraps_fur                       |       true                                              
hands.json      |                gloves_wraps_leather                   |       true                                              
hands.json      |                gloves_wraps_wool                      |       true                                              
hands.json      |                gloves_wsurvivor                       |       
hands.json      |                gloves_xlsurvivor                      |       
hands.json      |                mittens                                |       
hands.json      |                nomex_gloves                           |       
hands.json      |                sockmitts                              |       
hands.json      |                thermal_gloves                         |       
hands.json      |                wetsuit_gloves                         |       
head.json       |               balclava                                |       
head.json       |               bandana                                 |       true                                               
head.json       |               beret_wool                              |       
head.json       |               blindfold                               |       true                                               
head.json       |               blindfold                               |       true                                               
head.json       |               cowboy_hat                              |       
head.json       |               cowl_wool                               |       
head.json       |               fur_cat_ears                            |       
head.json       |               glasses_safety                          |       
head.json       |               goggles_ir                              |       true                                               
head.json       |               goggles_nv                              |       true                                               
head.json       |               goggles_swim                            |       
head.json       |               goggles_welding                         |       
head.json       |               hat_boonie                              |       
head.json       |               hat_cotton                              |       
head.json       |               hat_fur                                 |       
head.json       |               hat_hard                                |       
head.json       |               hat_hard_hooded                         |       true                                               
head.json       |               hat_hunting                             |       
head.json       |               hat_knit                                |       true                                               
head.json       |               hat_noise_cancelling                    |       true                                               
head.json       |               helmet_barbute                          |       
head.json       |               helmet_bone                             |       
head.json       |               helmet_chitin                           |       
head.json       |               helmet_hsurvivor                        |       
head.json       |               helmet_kabuto                           |       
head.json       |               helmet_larmor                           |       
head.json       |               helmet_nomad                            |       
head.json       |               helmet_plate                            |       
head.json       |               helmet_scavenger                        |       
head.json       |               helmet_survivor                         |       
head.json       |               helmet_xlsurvivor                       |       
head.json       |               hood_fsurvivor                          |       
head.json       |               hood_h20survivor                        |       
head.json       |               hood_lsurvivor                          |       
head.json       |               hood_rain                               |       
head.json       |               hood_survivor                           |       
head.json       |               hood_wsurvivor                          |       
head.json       |               hood_xlsurvivor                         |       
head.json       |               keffiyeh                                |       true                                               
head.json       |               knit_scarf                              |       true                                               
head.json       |               leather_cat_ears                        |       
head.json       |               long_knit_scarf                         |       true                                               
head.json       |               long_patchwork_scarf                    |       true                                               
head.json       |               mask_filter                             |       true                                               
head.json       |               mask_fsurvivor                          |       
head.json       |               mask_fsurvivorxl                        |       
head.json       |               mask_gas                                |       
head.json       |               mask_gas_xl                             |       
head.json       |               mask_gas_xl                             |       
head.json       |               mask_h20survivor                        |       
head.json       |               mask_h20survivorxl                      |       
head.json       |               mask_hsurvivor                          |       
head.json       |               mask_lsurvivor                          |       
head.json       |               mask_rioter                             |       true                                               
head.json       |               mask_ski                                |       
head.json       |               mask_survivor                           |       
head.json       |               mask_survivorxl                         |       
head.json       |               mask_wsurvivor                          |       
head.json       |               mask_wsurvivorxl                        |       
head.json       |               miner_hat                               |       
head.json       |               nomex_hood                              |       
head.json       |               patchwork_scarf                         |       true                                               
head.json       |               pot_helmet                              |       true                                               
head.json       |               rebreather                              |       
head.json       |               rebreather_xl                           |       
head.json       |               rebreather_xl                           |       
head.json       |               scarf                                   |       
head.json       |               scarf_fur                               |       true                                               
head.json       |               scarf_fur_long                          |       true                                               
head.json       |               scarf_fur_long                          |       true                                               
head.json       |               scarf_long                              |       
head.json       |               straw_fedora                            |       
head.json       |               straw_hat                               |       
head.json       |               survivor_goggles                        |       
head.json       |               thermal_mask                            |       
head.json       |               tinfoil_hat                             |       
head.json       |               tricorne                                |       
head.json       |               turban                                  |       true                                               
head.json       |               wetsuit_hood                            |       
legs.json       |               2byshin_guard                           |       true                                               
legs.json       |               bikini_bottom                           |       
legs.json       |               boxer_briefs                            |       
legs.json       |               boxer_shorts                            |       
legs.json       |               briefs                                  |       
legs.json       |               chaps_leather                           |       
legs.json       |               hot_pants                               |       
legs.json       |               hot_pants_fur                           |       
legs.json       |               hot_pants_leather                       |       
legs.json       |               jeans                                   |       
legs.json       |               kilt                                    |       
legs.json       |               knee_pads                               |       
legs.json       |               leg_warmers                             |       
legs.json       |               leg_warmers_xl                          |       
legs.json       |               leg_warmers_xlf                         |       
legs.json       |               legguard_hard                           |       
legs.json       |               legguard_lightplate                     |       
legs.json       |               legguard_metal                          |       
legs.json       |               legguard_paper                          |       
legs.json       |               loincloth                               |       
legs.json       |               loincloth_fur                           |       
legs.json       |               loincloth_leather                       |       
legs.json       |               loincloth_wool                          |       
legs.json       |               long_underpants                         |       
legs.json       |               lsurvivor_pants                         |       
legs.json       |               panties                                 |       
legs.json       |               pants_cargo                             |       true                                               
legs.json       |               pants_fur                               |       
legs.json       |               pants_leather                           |       
legs.json       |               pants_survivor                          |       
legs.json       |               shorts                                  |       
legs.json       |               shorts_cargo                            |       
legs.json       |               shorts_cargo                            |       
legs.json       |               shorts_denim                            |       
legs.json       |               shorts_denim                            |       
legs.json       |               stockings_tent_legs                     |       
legs.json       |               stockings_tent_legs                     |       
other.json      |                blanket                                |       true                                              
other.json      |                down_blanket                           |       true                                              
other.json      |                fur_blanket                            |       true                                              
other.json      |                fur_cat_tail                           |       
other.json      |                fur_collar                             |       
other.json      |                leather_cat_tail                       |       
other.json      |                leather_collar                         |       
other.json      |                rebreather_filter                      |       true                                              
other.json      |                sleeping_bag                           |       true                                              
other.json      |                sleeping_bag_fur                       |       true                                              
other.json      |                survivor_belt                          |       true                                              
other.json      |                survivor_belt_notools                  |       
other.json      |                towel                                  |       
storage.json    |                  XL_holster                           |       
storage.json    |                  ammo_satchel                         |       
storage.json    |                  back_holster                         |       
storage.json    |                  backpack                             |       
storage.json    |                  backpack_leather                     |       
storage.json    |                  baldric                              |       
storage.json    |                  bandolier_pistol                     |       
storage.json    |                  bandolier_rifle                      |       
storage.json    |                  bandolier_shotgun                    |       
storage.json    |                  bandolier_wrist                      |       
storage.json    |                  bindle                               |       true                                            
storage.json    |                  bootsheath                           |       
storage.json    |                  bootstrap                            |       
storage.json    |                  bscabbard                            |       
storage.json    |                  chestpouch                           |       
storage.json    |                  chestrig                             |       
storage.json    |                  duffelbag                            |       
storage.json    |                  flintlock_pouch                      |       
storage.json    |                  grenade_pouch                        |       
storage.json    |                  holster                              |       
storage.json    |                  jerrypack                            |       
storage.json    |                  leather_belt                         |       
storage.json    |                  leather_pouch                        |       
storage.json    |                  legpouch                             |       
storage.json    |                  legpouch_large                       |       
storage.json    |                  legrig                               |       
storage.json    |                  makeshift_knapsack                   |       true                                            
storage.json    |                  makeshift_sling                      |       true                                            
storage.json    |                  plastic_shopping_bag                 |       
storage.json    |                  quiver                               |       true                                            
storage.json    |                  quiver_birchbark                     |       true                                            
storage.json    |                  quiver_large                         |       true                                            
storage.json    |                  quiver_large_birchbark               |       true                                            
storage.json    |                  ragpouch                             |       
storage.json    |                  scabbard                             |       
storage.json    |                  sheath                               |       
storage.json    |                  sholster                             |       
storage.json    |                  straw_basket                         |       
storage.json    |                  survivor_duffel_bag                  |       
storage.json    |                  survivor_pack                        |       
storage.json    |                  survivor_rucksack                    |       
storage.json    |                  survivor_runner_pack                 |       
storage.json    |                  survivor_vest                        |       
storage.json    |                  swag_bag                             |       true                                            
storage.json    |                  tool_belt                            |       
suit.json       |               aep_suit                                |       
suit.json       |               anbc_suit                               |       
suit.json       |               armor_blarmor                           |       
suit.json       |               armor_bone                              |       
suit.json       |               armor_chitin                            |       
suit.json       |               armor_farmor                            |       
suit.json       |               armor_larmor                            |       
suit.json       |               armor_lightplate                        |       
suit.json       |               armor_lightplate                        |       true                                               
suit.json       |               armor_nomad                             |       
suit.json       |               armor_plarmor                           |       
suit.json       |               armor_plate                             |       
suit.json       |               armor_samurai                           |       
suit.json       |               armor_scavenger                         |       
suit.json       |               armor_scrapsuit                         |       true                                               
suit.json       |               chainmail_suit                          |       true                                               
suit.json       |               cloak                                   |       true                                               
suit.json       |               cloak_fur                               |       true                                               
suit.json       |               cloak_leather                           |       true                                               
suit.json       |               cloak_wool                              |       true                                               
suit.json       |               entry_suit                              |       
suit.json       |               fsurvivor_suit                          |       
suit.json       |               gambeson                                |       
suit.json       |               h20survivor_suit                        |       
suit.json       |               hsurvivor_suit                          |       
suit.json       |               jumpsuit_xl                             |       
suit.json       |               jumpsuit_xl                             |       
suit.json       |               lsurvivor_suit                          |       
suit.json       |               nomex_suit                              |       
suit.json       |               shark_suit_faraday                      |       true                                               
suit.json       |               survivor_suit                           |       
suit.json       |               thermal_outfit                          |       
suit.json       |               thermal_outfit                          |       
suit.json       |               thermal_suit                            |       
suit.json       |               tunic_rag                               |       true                                               
suit.json       |               union_suit                              |       true                                               
suit.json       |               wetsuit                                 |       
suit.json       |               wetsuit_spring                          |       
suit.json       |               wool_suit                               |       
suit.json       |               wsurvivor_suit                          |       
suit.json       |               xlsurvivor_suit                         |       
torso.json      |                apron_leather                          |       
torso.json      |                bikini_top                             |       
torso.json      |                bikini_top_fur                         |       
torso.json      |                bikini_top_leather                     |       
torso.json      |                blazer                                 |       
torso.json      |                bookplate                              |       
torso.json      |                bra                                    |       
torso.json      |                chestwrap                              |       true                                              
torso.json      |                chestwrap_fur                          |       true                                              
torso.json      |                chestwrap_leather                      |       true                                              
torso.json      |                chestwrap_wool                         |       true                                              
torso.json      |                coat_fur                               |       
torso.json      |                coat_rain                              |       
torso.json      |                cuirass_lightplate                     |       
torso.json      |                duster                                 |       
torso.json      |                duster_fur                             |       
torso.json      |                duster_leather                         |       
torso.json      |                duster_survivor                        |       
torso.json      |                greatcoat                              |       
torso.json      |                hoodie                                 |       
torso.json      |                house_coat                             |       true                                              
torso.json      |                jacket_leather                         |       
torso.json      |                jacket_leather_mod                     |       
torso.json      |                long_undertop                          |       
torso.json      |                longshirt                              |       
torso.json      |                lsurvivor_armor                        |       
torso.json      |                modularvest                            |       true                                              
torso.json      |                modularvestceramic                     |       true                                              
torso.json      |                modularvesthard                        |       true                                              
torso.json      |                modularvestkevlar                      |       true                                              
torso.json      |                modularveststeel                       |       true                                              
torso.json      |                modularvestsuper                       |       true                                              
torso.json      |                peacoat                                |       
torso.json      |                poncho                                 |       
torso.json      |                poncho                                 |       
torso.json      |                sleeveless_duster                      |       
torso.json      |                sleeveless_duster                      |       
torso.json      |                sleeveless_duster_fur                  |       
torso.json      |                sleeveless_duster_fur                  |       
torso.json      |                sleeveless_duster_leather              |       
torso.json      |                sleeveless_duster_leather              |       
torso.json      |                sleeveless_duster_survivor             |       
torso.json      |                sleeveless_duster_survivor             |       
torso.json      |                sleeveless_trenchcoat                  |       
torso.json      |                sleeveless_trenchcoat                  |       
torso.json      |                sleeveless_trenchcoat_fur              |       
torso.json      |                sleeveless_trenchcoat_fur              |       
torso.json      |                sleeveless_trenchcoat_leather          |       
torso.json      |                sleeveless_trenchcoat_leather          |       
torso.json      |                sleeveless_trenchcoat_survivor         |       
torso.json      |                sleeveless_trenchcoat_survivor         |       
torso.json      |                sleeveless_tunic                       |       
torso.json      |                sleeveless_tunic                       |       
torso.json      |                sundress                               |       
torso.json      |                sweater                                |       
torso.json      |                tank_top                               |       
torso.json      |                trenchcoat                             |       
torso.json      |                trenchcoat_fur                         |       
torso.json      |                trenchcoat_leather                     |       
torso.json      |                trenchcoat_survivor                    |       
torso.json      |                tshirt                                 |       true                                              
torso.json      |                tunic                                  |              
torso.json      |                undershirt                             |              
torso.json      |                vest_leather                           |              
torso.json      |                vest_leather                           |              
torso.json      |                vest_leather_mod                       |              
torso.json      |                wool_hoodie                            |

**Comment by kevingranade** [comment]
Need a direction for this, simply stating there's an inconsistency and listing the existing state of the items is insufficient.  Reopen if you have that direction.
