### ISSUE TITLE
Action "Cut up items" cannot cut up items on the ground.

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#20755]
Only inventory & worn item get listed, which make it a lot of pain (pick up -> activate scissors -> chose "cut up a item" -> chose items) to cut up dress in bulk.

![image](https://cloud.githubusercontent.com/assets/4143592/24575284/2747ef32-16d4-11e7-891a-148d6a376cf0.png)

![image](https://cloud.githubusercontent.com/assets/4143592/24575285/2cb6eef0-16d4-11e7-9421-bde7bdd171c5.png)

**Comment by AMurkin** [comment]
Use `B` key - Butcher, while standing on items.

**Comment by AMurkin** [comment]
Can be closed?
