### ISSUE TITLE
Old Guard quest, accepting 3rd mission freezes game

### ISSUE THREAD

**Issue by LastRagnarokkr** [CleverRaven/Cataclysm-DDA#20758]
Quest is from Old Guard Representative at the refugee center. 
This seems like the standard "Kill Bandit Leader" mission. Agreeing to the mission requires becoming US marshal, according to the dialogue.
 Its possible to back out at the last minute without freeze, but accepting the mission results in the game _completely_ locking up. 
First noticed a month or so ago, nightly updates have not worked thus far.

Windows 7 Ultimate
version 0.C-21941-g4c8f943a11 (build 6372), Curses, experimental

**latest save file:** https://drive.google.com/file/d/0B8rdwbwOy7b-TE8ydGE2WG50ZWs/view?usp=sharing

**Comment by Coolthulhu** [comment]
Most likely just the game taking trillion years to find a location that doesn't exist due to world settings or something like that.
Overmap iteration is incredibly slow and invokes overmapgen the first time it scans the area.

**Comment by sxmichaels** [comment]
I just tested accepting this mission on the latest version (`4f691a95a3`) several times and it works for me without issue — the bandits are spawned in the right place and there is no noticeable lag. It does still occur with your save file, but that may be an artifact of map/mission generation from an older version. Maybe this issue should be closed, unless we have save files from recent versions showing it still exists?

**Comment by Night-Pryanik** [comment]
Closing for now. If this issue still occurs, feel free to ping me so I reopen it.
