### ISSUE TITLE
Confirm integer-only promts only if Enter is pressed

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#20756]
Now they are confirmed if any key is pressed.

**Comment by kolsurma** [comment]
Does this happen with other integer only prompts?

**Comment by Night-Pryanik** [comment]
It seems so. Causing pain, for example, acts in the same manner.

**Comment by kevingranade** [comment]
I'm guessing the answer is yes, but are there non-debug commands that are suffering from this?  Jst checking for prioritization.

**Comment by Coolthulhu** [comment]
Pretty sure it's even more important in non-debug commands. Otherwise it is possible to activate a mininuke with low time or something like that.
I can't think of a single situation where confirming with non-enter key would be desired.
