### ISSUE TITLE
Utilize GPU core for more performance

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#20775]
Currently the game is solely CPU bassed, that's all fine and dandy, but it would be neat if some aspects of the game could utilize the unused GPU cores. Maybe a long term goal down the road.

**Comment by codemime** [comment]
This was already discussed in #19071 and even partially implemented in #19412 (along with more extensive discussion). Seems like it's not going to happen in foreseeable future.

**Comment by Unrepentant-Atheist** [comment]
I was thinking way more than just rendering done by GPU. Nowadays GPU can do so much more. I'm not sure how complex such an undertaking would be, but I'm sure the game could only profit from it. Like parallel processing maybe? Whatever is available. But hey, nice to see it was partialy implemented already!

**Comment by ZhilkinSerg** [comment]
1. Drawing takes the most CPU time.
2. Compatibility.

**Comment by Coolthulhu** [comment]
A lot of what GPU would do would need background processing.
Background processing would solve most of the performance problems other than drawing.

GPGPU support would require OpenCL as a hard dependency or maintaining compile time switches for a separate version of the game.
The latter is out - too much work and too many problems. Unless someone steps out as a volunteer maintainer and sticks with us long enough to make it a thing, but I wouldn't expect that.
The former is also out, unless there are small, easy to use OpenCL bindings under compatible license somewhere.

Then there is the problem of lack of need:
We simply don't have any calculations that would benefit from GPU much. Sure we could bloat the game with temperature flows and whatnot, but that would kill the performance on toasters, which the game is still supposed to support.

**Comment by kevingranade** [comment]
In short, it has the same problem as multithreading, it makes fast systems faster, and widens the gap between fast systems and slow systems.  Implementing something like this would have an almost unnoticeable impact on said fast systems, and make the game literally unplayable on slow systems.
