### ISSUE TITLE
DEBUG_STORAGE doesn't work in the advanced inventory

### ISSUE THREAD

**Issue by hagamablabla** [CleverRaven/Cataclysm-DDA#20777]
The debug command does increase maximum weight and volume and allows you to pick things up off the floor normally. However, if you try to transfer items to your inventory using the advanced inventory, it will always say the item is too heavy.

**Comment by BrettDong** [comment]
There may be some overflow.

**Comment by Coolthulhu** [comment]
Advanced inventory multiplies weight capacity by 4 to allow overloading self. Since capacity is `INT_MAX/2` and signed, this wraps around to 0.
Ironically advanced inventory casts the result to `long`, but does so after the overflow, so it doesn't help.
