### ISSUE TITLE
NPCs "waiting at base/home" should help with/watch the crafting process

### ISSUE THREAD

**Issue by MagicalCube** [CleverRaven/Cataclysm-DDA#20789]
it makes sense that npcs "on guard" wouldn't help the player since they are "too focused on detecting"any trouble nearby, but npcs "waiting" at base should probably be doing "helpful" things like for a start, helping the player if they are nearby and trying to craft something

this is just to reduces the "npc quits faction if told to wait at base" bug(if its that hard to fix) and also the player won't have to keep telling 7 npcs to guard(wait at base)/follow them when ever they want to either craft or go city raiding 
also telling them to guard this area appears to lower the chance of them teaching the player any skills they know don't know if that intentional

**Comment by MagicalCube** [comment]
this suggestion is obviously superseded by suggestion  #19883 but until its implemented(if its still to "far" into the future) i think it would be a good idea to look into this suggestion

**Comment by kevingranade** [comment]
It's not clear what you're asking for, you mention several potential bugs and several different behaviors you want, please clearly state the problem and your proposed solution.

**Comment by Coolthulhu** [comment]
Pretty sure it's about NPCs who are on guard duty not being able to count as crafters.

Currently crafters have to be followers. Not intentionally, they were just implemented like that first.

Could be useful for NPCs who are resting in base (healing broken limbs and so on), who must be on guard duty or they will follow the player into danger.
Or just surplus NPCs who aren't good enough to take with player to fight things.

**Comment by MagicalCube** [comment]
@kevingranade sorry for making things complicated, I am kinda new to the whole bug reporting/suggestions thing

**Comment by Nhatorama** [comment]
Currently if I have my 5 NPCs follow me to help me craft or for me to read to them (skill up through books), time advances much more slowly, even though they are just sitting inside my in-house vehicle and there are no distractions in my reality bubble.
On the other hand if I have them stand guard or at base, time advances as fast as usual while it's just me crafting/reading.

+1 for the above, and if NPCs can listen to me while I'm reading a book and they are at base/guarding that would be a plus.

**Comment by Leland** [comment]
I think the best/most obvious way to approach this would be that any NPC follower or guard present in your homebase will assist with any crafting done in that homebase, regardless of proximity.

**Comment by pabrams** [comment]
@Leland Well, I personally agree with MagicalCube that guards should **not** help with crafting - then they wouldn't be guarding anymore.  I think this issue is about **waiting** NPCs.

**Comment by Coolthulhu** [comment]
The "guard" command doesn't mean "stand around and only watch", it means "stay here, but defend yourself if you need to".

There are no wandering threats that the NPC could guard the place from.

**Comment by Night-Pryanik** [comment]
Closed by #28517.
