### ISSUE TITLE
NPCs shoot targets on Z-levels they aren't able to see

### ISSUE THREAD

**Issue by Taberone** [CleverRaven/Cataclysm-DDA#20785]
0.C-21941-g4c8f943a11 (tiles), Build 6372

Step 1: Enable Z-Levels and Experimental 3D Vision.
Step 2: Get yourself a NPC buddy (with a gun) and a hostile creature on a z-level above or below you, and make sure that you're in a situation where the NPC couldn't possibly see the creature. For example, go into the subway tunnels while zombies are walking around above you, or go above the subway tunnels while sewer rats are running around below you.
Step 3: Watch the NPC empty his gun into (presumably) the ceiling or the floor trying to kill the hostile.

Ran into this today while running around in the subway tunnels with a NPC companion. He started shooting randomly, and I eventually turned off 3D Vision. He stopped shooting. I turn 3D Vision on again, and he starts shooting again. The entire time, there were zombies above the subway tunnels lumbering around.

**Comment by Human-Shield** [comment]
Can confirm and it is even worse. Zombies that shot (boomer, shocker) can hit players in the sewers and the Tab key (attack adjacent) can be used by the player to melee zombies and kill them on the street without getting hit. 

Reveal map and teleport between any street and sewer level and add shockers and hit tab. 
![catasewers](https://user-images.githubusercontent.com/35199487/35715397-14a3f64c-07a0-11e8-8f56-b48822159f11.JPG)

**Comment by Human-Shield** [comment]
Also any monsters with ranged spear attacks. Can attack from the sewer to the street. PK mod's turtle man killed a bunch of street zombies and then attacked me. 
![sewer enemy](https://user-images.githubusercontent.com/35199487/35889096-1af236c8-0b68-11e8-9b84-9082747d3e47.JPG)

**Comment by kevingranade** [comment]
This should be fixed.
