### ISSUE TITLE
NPCs don't hit and run when meleeing zombies

### ISSUE THREAD

**Issue by Taberone** [CleverRaven/Cataclysm-DDA#20782]
Version 0.C-21941-g4c8f943a11 (tiles), Build 6372 and pretty much every single version before it

Step 1: Get yourself a NPC buddy.
Step 2: Find a zombie.
Step 3: Watch your NPC companion run up to the zombie, get up in it's face, stay as still as a rock, and exchange blows with the zombie like a true gentleman. Bonus points if he gets mobbed by zombies afterwards, or if he's fighting a single Zombie Hulk mano-a-mano like a gentleman and getting punted around like a football every time the Hulk smacks him.
Step 4: Assuming he survived the entire ordeal, listen to your NPC complain about every single body part of his having bite wounds being pretty bad, since he will inevitably get bitten several times.
Step 5: Use up a bunch of disinfectant for the bite wounds, if you have any.

The player of capable of intelligently smacking zombies and taking a step back to avoid getting hit in melee (especially if a Zombie Brute/Hulk is around), but NPCs aren't. This frequently leads to bite wounds, shredded or destroyed clothing, massive damage taken (both arms or both legs being broken isn't uncommon), or even death. Making NPC AI capable of hit and run attacks would be a welcome improvement.

**Comment by Leland** [comment]
Love this idea. Merging with #19867.
