### ISSUE TITLE
telling npcs to wait at base causes them to leave the player :(

### ISSUE THREAD

**Issue by MagicalCube** [CleverRaven/Cataclysm-DDA#20788]
they give the same message as npcs that do actually wait at base which is for ex: "Luz Watt waits at home" however some quit the faction doesn't matter your relationship with them

**Comment by Lord-Helmchen** [comment]
partial confirm here (0.C-22249). some waited as instructed, one went his own way. perhaps connected to number of NPCs already waiting at the base?

**Comment by Leland** [comment]
Note #19873 as well.

**Comment by KorGgenT** [comment]
base command has been removed pending re-integration into new basecamp says @davidpwbrown
