### ISSUE TITLE
Investigate strange bug: Taking damage while sleeping

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#20792]
I wrote in the IRC and Discord, nobody knows what's going on. I uploaded my game including mods and save for everybody to debug: https://www.dropbox.com/s/9bgnugr1wj6h06p/CatalysmDDA.7z?dl=0

The problem is: I'm taking damage while sleeping, BUT

a) No mutations that harm me
b) No radiation damage
c) No bionics that harm me

I can only survive with nano repair robots turned on during my sleep.

**Comment by Coolthulhu** [comment]
I bet I fucked up something like uninitialized value somewhere.

**Comment by Coolthulhu** [comment]
Oh it's your health: it got below the low cap of -200.
This can't happen in unmodded game, but the cap not being enforced properly is a bug.

**Comment by ZhilkinSerg** [comment]
So, that's what the old age is like.

**Comment by DangerNoodle** [comment]
How is it even possible to hit that low health?

**Comment by ZhilkinSerg** [comment]
Bleach. This looks unhealthy, sure you want to drink it?

**Comment by WizardOfOoo** [comment]
Current jenkins build, Winx64 Tiles

Debugged:
Health to: -199
Heal mod: -199

Washed down five Ambien with a large bleach and then took a nap.

![image](https://cloud.githubusercontent.com/assets/17521661/24835139/43177eae-1cbe-11e7-82bd-6c37bf50ec82.png)

**Comment by WizardOfOoo** [comment]
Bro your health is -700
What have you been eating?
