### ISSUE TITLE
Cannot transfer water into sealed stomach or large sealed stomach

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#20799]
Version: 0.C-21989-g20802dcfbc (tiles)
Build: 6379
OS: Windows 7 Professional x64 SP1

Just like the title says I can't transfer liquids from the vehicle I built from scratch into a different container. I am able to fill the vehicle with any liquid and drink from the water faucet. The pre-existing vehicle I have works fine and I can transfer any liquid to/from it.

This shows up when I try to remove liquids either by siphoning them or using the water faucet (transfer clean water):
<a href='https://postimg.org/image/3w3jzic9p/' target='_blank'><img src='https://s6.postimg.org/3w3jzic9p/Can_drink_but_can_t_fill_from_vehicle_tank.jpg' border='0' alt='postimage'/></a>

[Save file](https://mega.nz/#!gsJUTahZ!h9ouHuQ91WCJFx2zoyQ4Qb6T0CRByGICw5iLRHlHhgw)

UPDATE:
I have 1 wooden barrel installed in my vehicle that's almost full of clean water. I can transfer the clean water to and from a spare wooden barrel, but the bug screen comes up if I try to pour the vehicle's clean water  into any container that's not a wooden barrel.

**Comment by Nhatorama** [comment]
Looks like the recent update fixed most of the problems, but sealed stomach and large sealed stomach cannot be filled through siphoning or the water faucet.

**Comment by kevingranade** [comment]
Wild-ass guess is that this will be fixed by re-merging this: https://github.com/CleverRaven/Cataclysm-DDA/pull/18719/files and/or this: https://github.com/CleverRaven/Cataclysm-DDA/commit/f50eda88d412f383e7fd13da3324d5f408d561db and possibly this: https://github.com/CleverRaven/Cataclysm-DDA/commit/b899bf05bd86359727577165c1cf2911ba7be6d6

**Comment by Leland** [comment]
Looks like this is more than just a vehicle problem.

From @Treah, https://github.com/CleverRaven/Cataclysm-DDA/issues/20974#issue-227112022:

>You are unable to pour water into a sealed stomach. However pouring other liquids into them seams to work just fine. I tried moving contents from another container ( clean water ) into a stomach and not getting the option to move it to the stomach. Also unable to from world source. However when I tried with Vodka it gave me the option to move it to the sealed stomach when choosing container.

**Comment by Treah** [comment]
Ohh thank you for combining this Leland. 

Another update is that if the sealed stomach is NOT in your inventory and your doing something like cleaning water then it DOES show up as a valid container...

**Comment by Night-Pryanik** [comment]
Tested right now on latest experimental. I was able to transfer water to vehicle tank from my containers, and from vehicle tank into my containers, including sealed stomach and large sealed stomach.
I have a assumption, though. Sealed stomachs (and other non-rigid containers like waterskin) won't show as a valid container if your available volume is near the limit, as filling them will exceed your available volume.
@Treah, @Nhatorama or anyone else, could you test this with a lots of available volume?

**Comment by Nhatorama** [comment]
Tested it and it seems the issue has been fixed.
