### ISSUE TITLE
Can't Build Vehicles

### ISSUE THREAD

**Issue by Taichi22** [CleverRaven/Cataclysm-DDA#20797]
Can't build a vehicle in my most recent save, despite having the required parts.
To reproduce, initiate a vehicle build with a steel frame using the uploaded save; it should tell you that required parts are not available, despite having/wielding/being near to a frame.
[Save1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/901144/Save1.zip)

**Comment by Taichi22** [comment]
![2017-04-05 1](https://cloud.githubusercontent.com/assets/1211989/24732818/7083906e-1a41-11e7-99d3-3a6f93376d9d.png)
![2017-04-05 2](https://cloud.githubusercontent.com/assets/1211989/24732819/7086d058-1a41-11e7-9cd6-98e5c363be7b.png)
![2017-04-05 3](https://cloud.githubusercontent.com/assets/1211989/24732817/70835bb2-1a41-11e7-9d9f-d97e289296ca.png)
![2017-04-05](https://cloud.githubusercontent.com/assets/1211989/24732820/708822b4-1a41-11e7-92b7-a20dfb9e5903.png)
Files of process uploaded.

**Comment by BorkBorkGoesTheCode** [comment]
The vehicle requirements are only supposed to have one frame entry. Have you tried to overwrite an old Vehicle Additions Pack at any time in the past?

**Comment by Leland** [comment]
Thanks for providing a save file!

**Comment by Leland** [comment]
@Taichi22 can you reproduce this still?

**Comment by Taichi22** [comment]
Have fixed it, thanks for following up. 
I believe it was an older issue with the vehicle additions package, which implemented its own set of requirements for building vehicles, which didn't overwrite the base module's requirements, but doubled up on them.
Two ways around it -- either have 2 vehicle parts, or edit the BlazeMod file to remove the additional requirements, which are fairly prominent.
