### ISSUE TITLE
Bear won't attack me?

### ISSUE THREAD

**Issue by lcy03406** [CleverRaven/Cataclysm-DDA#20791]
A wild bear approached my base, but it didn't attack me, even if I attack it.
I saved before fighting the bear, I didn't check if it was hostile before saving, but it came straight at me I thought it would like to kill me. 

The version is 0.C-6372. I have the save file, but don't know how to submit it.

**Comment by lcy03406** [comment]
No. Good to know fire can keep wild lives away. 
The bear was half wounded before reaching me, not by me, my javelins were bounced off its hard skin.
But why did it charged at me only to wound deeper and flee away?

**Comment by kevingranade** [comment]
Most creatures have their agression level reduced if they are low on health, it might have just wandered close to you without thinking of you as an enemy, then when you attacked it spooked and ran away.
Sounds like it's working as intended.
