### ISSUE TITLE
Itemspawnrate doesnt affect Zombie item drops

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#20793]
Tested itemspawnrate with 2.0 and 0.2, in both cases Zombies were droping same amount of loot.
If a Player sets a low itemspawnrate and a high zombie spawnrate, the zombies will turn into the main loot source. Shouldnt itemspawnrate also affect Zombie drops?

**Comment by kevingranade** [comment]
Monster drops frequently don't have a rate attached to them, they just have gear it's reasonable for them to have, so no, it's not particularly meaningful to have item spawn rate affect monster drops.  It's a given that if you change options you're adjusting game balance.

If you want extremely low item availability where things stay consistent, you need a mod that tweaks the various sources of items to some new balance.
