### ISSUE TITLE
Should cautrizing wounds cause immediate infection on fail?

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#20805]
Currently it does. I can understand how infection might become more likely after cauterizing... it just seems odd that after burning yourself with a hot iron it becomes immediately infected.

**Comment by AMurkin** [comment]
#20742 related?

**Comment by kevingranade** [comment]
You get the initial stage of infection, the same as if you were bitten, so it's a matter of how quickly infection proceeds.
