### ISSUE TITLE
After discoloring actions log miss some letters.

### ISSUE THREAD

**Issue by kimesik** [CleverRaven/Cataclysm-DDA#20802]
![image](https://cloud.githubusercontent.com/assets/19290819/24804454/d4e9d552-1bf1-11e7-9b72-fe33d10d0371.png)
Also
![image](https://cloud.githubusercontent.com/assets/19290819/24804646/722fb516-1bf2-11e7-8f1d-8421b6fc0cbe.png)

Font: Ubuntu Monospace Bold

**Comment by Leland** [comment]
@kimesik can you provide some detail on what's going on here?

**Comment by Zireael07** [comment]
Looks like some parts of the screen aren't redrawn correctly.

@kimesik: Is that the default font? I'm not too sure...

**Comment by AMurkin** [comment]
A font itself is ok. Have tried that on win x86 tiles build 6415.

**Comment by Leland** [comment]
Closing due to lack of information.
