### ISSUE TITLE
Survival Tips info on encumberance is incorrect or defect exists

### ISSUE THREAD

**Issue by dreyskiy** [CleverRaven/Cataclysm-DDA#20800]
Game help indicates that there is no penalty for wearing a 0 encumbrance item that has also been fitted.  However, the real penalty is +2.

For example: Kevlar Vest (5) + compression top -fits- (0) = 5 + 2
Based on the below the expectation is to have 5 + 0 for the first compression top, and +2 or more for the second.

I'm guessing this text is outdated consider the reference to '10 point'.

See 
> 
>    
> Your clothing can sit in one of four layers on your body: next-to-skin, standard, over, and belted. \
> You can wear one item from each layer on a body part without incurring an encumbrance penalty for \
> too many worn items. Any items beyond the first on each layer add an **additional 10 points** to the body \
> part's encumbrance. (However, you can wear one additional item that would be encumbrance 0 before \
> fitting, and is fitted anyway, without incurring that penalty.)" ) );
> 
>     
> For example, on her torso, a character might wear a leather corset (next-to-skin), a leather touring \
> suit (standard), a trenchcoat (over), and a survivor's runner pack (belted). Her encumbrance penalty \
> is 0. **She could also wear one encumbrance 0 fitted item on any layer without triggering the penalty**: \
> for example, a tank top (next-to-skin) or a t-shirt (standard). If she put on a tank top AND a \
> t-shirt, one of them would be penalized, bringing her encumbrance to 1." ) );

https://github.com/CleverRaven/Cataclysm-DDA/blob/54caf20a80562eee9df471b78970a8c9e37c08bc/src/help.cpp

**Comment by kevingranade** [comment]
Thanks for pointing this out, all references to fitted 0-encumbrance
clothing having special treatment are incorrect.
