### ISSUE TITLE
Attempting to fire an underslung shotgun without attaching as gunmod causes a crash

### ISSUE THREAD

**Issue by Taberone** [CleverRaven/Cataclysm-DDA#20812]
Version 0.C-22030-g1217df8288 (tiles), Build 6384

Wielding and firing an underslung shotgun without attaching it to a gun for whatever reason (desperation, not being skilled enough in shotguns to attach it to another gun, etc) causes a crash. Doesn't matter if the underslung shotgun is loaded or not, attempting to fire it WITHOUT attaching it to another gun first will cause a crash.

**Comment by Night-Pryanik** [comment]
Could be related to #20776?

**Comment by WizardOfOoo** [comment]
Verified.

**Comment by WizardOfOoo** [comment]
@Night-Pryanik > Could be related to #20776?
Nope, still crashes in jenkins build 6383

**Comment by ZenZen2** [comment]
confirmed

**Comment by WizardOfOoo** [comment]
Should these be fireable without attaching them?

I know the flamethrower says it in the description...

**Comment by kevingranade** [comment]
No, I'd consider firing the underling shotgun when not attached to a gun to
be a bug.

**Comment by Unrepentant-Atheist** [comment]
@kevingranade I don't. https://imgur.com/a/eayWg . Might be strange to fire it without being attached to a gun, but is doable.

**Comment by kevingranade** [comment]
Is that a joke? There's a trigger there, but you're going to break a finger
or something firing it.

**Comment by WizardOfOoo** [comment]
The grenade launcher maybe, but not the shotgun.

**Comment by HotSake** [comment]
Actually the grenade launcher is a relatively low pressure, low velocity round. I'd be more worried a about firing the shotgun.

**Comment by kevingranade** [comment]
The grenade launcher is low pressure and velocity because the projectile is
so heavy, the recoil is significantly higher than a shotgun.

**Comment by HotSake** [comment]
Either way, if I had some thick padding like an MBR vest, I'd be comfortable bracing the end of those against my center of mass in an emergency. Way too awkward and short to shoulder, but I bet I could at least get the end pointed downrange and fire it without breaking anything.

**Comment by kevingranade** [comment]
Feel free to PR a system for handling firing some of them separately at
severely reduced accuracy and firing rate, but I consider preventing them
from being fired to be a solution to this problem.
