### ISSUE TITLE
Some missions are identified by name, which is translated

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20818]
Found it when describing computer effects.
Found the following examples:

- [x] Repeater mod mission compares mission name with an untranslated, hardcoded string, meaning it will always fail if the mission name is translated (fixed by #20959)
- [ ] Complete mission computer effect compares translated mission name to translated computer name, meaning it will not work if those two are translated differently (including ALLCAPS or something like that)

Edit by @Leland: moved to checklist

**Comment by Toothspit** [comment]
@kevingranade @BrettDong @Coolthulhu This wasn't closed, looks fixed?

**Comment by BrettDong** [comment]
The first problem is fixed but the second is not.
