### ISSUE TITLE
Changing in-game language not affect some strings

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#20829]
Playing with language setting.

- **Major:** World created when language set to English. Some strings (marked blue) have been serialized to json as English version. They will remain untranslated, but re-readed from json.
- Minor: Then i change language to Japanese, quit game and again change language to Russian. Here other strings (marked orange) remain in Japanese until next launch.

![cdda i18n settings](https://cloud.githubusercontent.com/assets/1931904/24897149/7e88ddc8-1ea0-11e7-9139-a700e16ce552.png)
Another example as in evac shelter computer menu.
![cdda i18n evac terminal](https://cloud.githubusercontent.com/assets/1931904/24897811/f6c01372-1ea2-11e7-866a-687281423d45.png)

**Comment by ZenZen2** [comment]
There is also some translation lost compared to old versions (few month). For example cookies are not translated in german anymore.

**Comment by BrettDong** [comment]
> There is also some translation lost compared to old versions (few month). For example cookies are not translated in german anymore.

Translations on [Transifex](https://transifex.com/cataclysm-dda-translators/) need to be updated according to the changes on translation template occurred in past few months.

**Comment by ZenZen2** [comment]
I didnt know anything about Transifex, thanks for pointing me to it.

**Comment by kevingranade** [comment]
Are you sure this isn't just missing translations from Japanese? As far as
I know we never save translated strings and then load them.

**Comment by AMurkin** [comment]
It seems I was wrong at the expense of rereading from json for lines in options. These lines in the world settings are initially displayed in English.
The error was that in the source code they are enclosed in _(), and in the .mo file there is a translation.
Apparently the same happens with the description of the line "eyes" in "encumbrance and warmth".
But in evac shelter computer menu lines remain in language which was set while world has been generated.
![cdda terminal](https://cloud.githubusercontent.com/assets/1931904/25035267/36ac706c-20f5-11e7-8ea3-a150e0197857.png)

**Comment by BrettDong** [comment]
> Are you sure this isn't just missing translations from Japanese? As far as I know we never save translated strings and then load them.

Unfortunately, there are a lot of instances of the said situation, probably newly added to the code.

**Comment by AMurkin** [comment]
What .map-file contains for shelter map tile:
`"computers":"Компьютер_убежища 0 -1 3 Экстренное_сообщение 27 0 Отключить_внешний_источник_энергии 20 0 Свяжитесь_с_нами 28 0 0 "`
It's localized space-replaced strings.
I'm trying to understand the whole process, but don't find all the details.

**Comment by codemime** [comment]
The source of the evil are lines like:
https://github.com/CleverRaven/Cataclysm-DDA/blob/e66156350586d2bda30def574eb66a1413329307/src/mapgen_functions.cpp#L3893-L3894
They shouldn't be translated at this point, but they are. They get saved and then, after loading them back, there's nothing to be done about them. The proper fix would be in storing untranslated strings and translating them only upon displaying.

**Comment by AMurkin** [comment]
Closing in favor of #23555 and others more specific issues.
