### ISSUE TITLE
Can't delete search/filter terms in advanced inventory

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#20822]
Version: 0.C-22054-gfee38d4441 (tiles)
Build: 6388
OS: Windows 7 Professional x64 SP1

I think it's been a bug since build 6370ish.

**Comment by WizardOfOoo** [comment]
I'm confused. How do you reproduce this?

**Comment by Nhatorama** [comment]
In advanced inventory press "f", type something, use the backspace key. In my game the backspace key does nothing and I have to press the Escape key to clear the search term.

**Comment by WizardOfOoo** [comment]
Backspace works for me.  Try renaming your keybindings.json file to .bak and reloading the game.

**Comment by Nhatorama** [comment]
Just changed it to a .bak and it seems to have resolved both the backspace problem and the overall lag that I was having while my 5 NPCs followed me.

In my keybindings I had removed ` as the debug key and assigned it to open the autopickup manager. I'm not sure if that might have been the problem.

Is keybindings not supposed to be a .json?

**Comment by WizardOfOoo** [comment]
I had a hunch your keybindings might be off.  

No, Keybindings is supposed to be .json.
When I had you rename it, the game saw that it didn't have one and created a fresh one.
Redo your key binds and see if that helps.  If binding a certain key breaks the backspace in advanced inventory, that's a bug and I'd appreciate your help in finding it.  Either way, I'm glad I could help.

**Comment by kevingranade** [comment]
Please post your old keybind file, it will be much easier to find the issue
if we have that.

**Comment by Nhatorama** [comment]
@WizardOfOoo @kevingranade 

I know how to reproduce it now. The bug persisted whether I had my keybindings file as .json or .bak.
I'll include my [save file](https://mega.nz/#!wpoUwYYb!mVEvCLsi2qdWPE0JTI6sBZg2PYgaWJis-U1g3PNkjAg) even though I don't think it's the problem.

Here are the steps to make the backspace key to stop working:

1. Open the advanced inventory

**Comment by ZenZen2** [comment]
confirming.

**Comment by ZenZen2** [comment]
The bug doesnt presist unil you restart the game, just move an item in the Adv inventory and you can use backspace there again.
