### ISSUE TITLE
Crach when going crafting menu

### ISSUE THREAD

**Issue by Dosbally** [CleverRaven/Cataclysm-DDA#20821]
Version 0.C-22047-g88874d50db (tiles), Build 6388 

- Load a game
- Open world options
-  Confirm with enter
- Go to Crafting Menu ("&")
-   Crash

**Comment by AMurkin** [comment]
What OS? What language set in game?
Can you describe in detail second and third steps?
> Confirm with enter
For me (win 10, game is x86) opening options, going to world options, changing something, saving changes and pressing `&` opens craft UI.

**Comment by Dosbally** [comment]
Sure.

- OS…Windows 7 (x64)
- Language... Japanese
- Mods... Dark days ahead & Bright Nights
- changing presses for opens craft UI... None

**Comment by ZenZen2** [comment]
can not reproduce, even after switching ingame to japanese language. Game 6389.

**Comment by AMurkin** [comment]
Me too. Neither 6389, nor 6388. Tried both x86 ang x64.

**Comment by Coolthulhu** [comment]
Could be mods

**Comment by AMurkin** [comment]
Tried with mentioned Bright Nights (and mod required by it).

**Comment by kevingranade** [comment]
Multiple attempts to reproduce issue failed.
