### ISSUE TITLE
Mistagged Material for Heavy Survivor Armor (Armor.json File) - Honestly Low Priority, easy fix.

### ISSUE THREAD

**Issue by Kevak** [CleverRaven/Cataclysm-DDA#20823]
Despite the description explicitly stating that Heavy Survivor Armor is composed of leather, steel, and kevlar, as materials, HSA is only tagged with steel and kevlar, which results in tailed mutants being unable to utilize what by all means should be entirely usable for them (Due to the mutation set preventing use of nonfabric/leather pants.)

This is easily fixable and can be solved with a single word and a bit of punctuation to the armor.json file in maindirectory>data>json>items>

The main issue here is consistency and common sense. Something you build outta leather is gonna have leather as a component. Similarly, something a person explicitly designs and builds for themselves is gonna account for minor changes in anatomy.

**Comment by WizardOfOoo** [comment]
Do you mean heavy survivor suit?

**Comment by Kevak** [comment]
Correct.

**Comment by DangerNoodle** [comment]
This additionally affects heavy survivor helmets in the case of Pointed Horns, Antlers, Antennae, and related traits. Regular survivor helmets meanwhile do have leather on the material list.

I will work on a fix, and test how adding leather to material list affects the protection of heavy survivor gear.

**Comment by Coolthulhu** [comment]
Adding materials to armor just to fix a rare mutation interaction is not the right way to go.
It should be a flag that is by default set from materials.

**Comment by DangerNoodle** [comment]
That would be a complex solution, and I am unsure of the correct implementation. Note also that, as original post states, adding leather to the material list of heavy survivor suit additionally reflects the crafting recipe.

So far I have already tested and found that the addition of one `material_layer` partially mitigates the loss in protection from adding leather to the material list, with the only loss being 2 cut protection. Note that heavy survivor armor is non-standardized and thus protection values already vary wildly among each piece of the set.

**Comment by kevingranade** [comment]
> Adding materials to armor just to fix a rare mutation interaction is not the right way to go.

I agree with @DangerNoodle, this is a fix to the material that also addresses the mutation thing.

**Comment by DangerNoodle** [comment]
> I agree with @DangerNoodle, this is a fix to the material that also addresses the mutation thing.

Will work on the pull request then, and apologies for that.

**Comment by WizardOfOoo** [comment]
Should these be fireable without attaching them?

**Comment by DangerNoodle** [comment]
> Should these be fireable without attaching them?

I beg your pardon?

**Comment by WizardOfOoo** [comment]
Derp, Wrong page, sorry.
