### ISSUE TITLE
Water temperature calculations are unrelated to air temperature

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20831]
Can't really say it's a bug because realism isn't a feature, but it's certainly "off" and unintended.

Water temperature only depends on time of the year and time of the day. It never goes below what is called 31.8 Fahrenheit, but the temperature units are only called Fahrenheit there and only loosely correlates with that scale.

The result is that you can warm yourself up by swimming in ice-cold water.
I just tested it to check how much:
Naked swim in the middle of a winter night only goes down to "chilly". Wool hoodie on top of that brought me to "comfortable" on affected parts.

**Comment by Mecares** [comment]
Well water obviously does not  cool  below the freezing point under most condtions (no or low salitnity, pressure around atmospheric pressure), which makes  31.8°F or 0°C a reasonable water temperature during coldest winter. Problematic is more how body heat loss by the player is simulated. Maybe make water ignore the warmth provided by most clothing except neoprene clothing?

**Comment by Coolthulhu** [comment]
> Well water obviously does not cool below the freezing point under most condtions

It would be a much smaller problem to have water below freezing temperature than having water be just cold while the surrounding air should be liquid due to its temperature (happens in ice labs).
IRL water is not something that can't physically be cooled below its freezing temperature.

**Comment by Mecares** [comment]
Well considering that Water ingame can not freeze at the moment, one could expect it to have roughly air temperature unless we talk about big bodies of water.

**Comment by DangerNoodle** [comment]
Complicating this is no current way to implement freezing of water, other than hacks such as simply changing terrain flags in winter. Doing so seems rather low-priority though.

**Comment by 1skandar** [comment]
Actually, as a slightly bigger problem water is a better conductor of heat than air. That means water should have a greater effect on how cold you get than ambient air, to the tune of 25 times as much or so. This is why a 60 F degree day is comfortable or maybe slightly cool, but 60 F water will straight up *kill you* thanks to hypothermia. Survival time in 32 F water can be measured in *minutes*, with unconsciousness happening in 15 minutes or so.

As a work around, it would be fairly transparent to give a hypothermia debuff when entering water if the ambient air is cold, with a strong damage over time effect, much like poison. 

Oh, and you can absolutely liquid water below its freezing point, this is known as "super cooling". The physics behind it are interesting, and if you want to see it in action take bottled water (needs to be reasonably free of impurities) at refrigerator temps and put it in the freezer. After a few hours, open the freezer and the water is still likely going to be liquid. However, if you tap it hard it will freeze solid in seconds.
