### ISSUE TITLE
Add indicator to installed batteries how full they are. 

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#20839]
Speaking of this: https://imgur.com/a/Yau9I

There's no way to know which of these 7000 batteries are 100% and which one's are not by going over the vehicle. Would be nice to have these % attached in the batteries.

**Comment by AMurkin** [comment]
I was thinking about indices near parts with the same names. In parts list under vehicle scheme and in central window (where listed accumulators, tanks and turrets).

**Comment by illi-kun** [comment]
Closed by #21790.
