### ISSUE TITLE
Make glass-made container sealed.

### ISSUE THREAD

**Issue by mdonline2** [CleverRaven/Cataclysm-DDA#20838]
Something like Gin, Brandy and peanuts butter or pesto was not put in sealed glass jar.

it seems like someone was too bored to open them all and leave those food behind....

also maybe sealed plastic bottle can be add in game and make oj or cider not rot so fast?

**Comment by Coolthulhu** [comment]
Gin and brandy don't rot.
As for the rest: currently sealing implies that the product is more or less sterile. That is, if it is sealed, it should stay edible for at least a year if it isn't opened during that time.

The way sealing works in the game is preventing all rot.

**Comment by mdonline2** [comment]
bah~i juts think it may be better to make all container sealed.
cause those item seems made to prevert rot and........NORMALY they will be sealed

In my country...almost all food made by factory are sealed.

**Comment by WizardOfOoo** [comment]
Even a sealed container of OJ is going to rot in a few days.

**Comment by mdonline2** [comment]
So it will never do a sealed plastic bottle?

**Comment by WizardOfOoo** [comment]
What would you gain from that?

**Comment by Leland** [comment]
Closing - insufficient information.
