### ISSUE TITLE
No recipe for "Can Sealer."

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#20837]
Also the material is aluminum?  The one I have in my house is steel.

**Comment by WizardOfOoo** [comment]
http://cdda-trunk.estilofusion.com/can_sealer

Also I debug learned all the recipes and I don't have it.

**Comment by WizardOfOoo** [comment]
I'd make one but I'm not 100% on how to make a tool.

**Comment by BorkBorkGoesTheCode** [comment]
Try adding it to textbook_mechanics using     `"book_learn": [ [ "textbook_mechanics", 3 ] ],
`

**Comment by ZhilkinSerg** [comment]
Can sealer has pretty high number of parts in it: https://www.youtube.com/watch?v=nzape-rNQ5Q

**Comment by kevingranade** [comment]
That head part is cast metal with lots of detail, doesn't seem like something you can make with a forge.

**Comment by AMurkin** [comment]
![28461b](https://cloud.githubusercontent.com/assets/1931904/25014664/5b8b8a7c-2081-11e7-9ef2-6e48b13d23f8.jpg)

**Comment by WizardOfOoo** [comment]
Considering the things that we can already make with fabrication, I don't think it presents a problem.

**Comment by kevingranade** [comment]
Hmm, given the second example, nevermind, it looked like it needed to apply
vacuum while it was sealing or something, if it's just crimping the can it
seems reasonable.

**Comment by 1skandar** [comment]
Hmm, as far as I can tell, canning with actual tin cans isn't typically done in home canning, mostly being glass jars. That said, sealing a tin can is mostly just crimping a slightly wider circle of metal over the open end of the can. It is *slightly* more complicated than that, and I imagine a DIY variant wouldn't be as good as a commercial grade machine. That said, I imagine that even the DIY version should be able to achieve the "prevents spoilage for at least 1 year" criteria.

**Comment by ZhilkinSerg** [comment]
You add anti-rotting agent (like sugar or salt), boil it, make vacuum and seal the container. Pickles or jam will most probably last unspoiled for at least a year.

**Comment by Night-Pryanik** [comment]
Closed by #23581.
