### ISSUE TITLE
Advanced electronic cigarette is much worse than its ordinary variant

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#20830]
First of all, advanced ecig doesn't cope with nicotine withdrawal at all.
Then, it doesn't have neither `fun` nor `stim` value. And at last, while its description states that it is still addictive, it doesn't have `addiction_type` and `addiction_potential`.

**Comment by ZhilkinSerg** [comment]
You can remove batteries from it though

**Comment by Schmel924** [comment]
To be honest: i do not see a problem here. Game is just mirroring real world.

**Comment by Toothspit** [comment]
@Schmel924 I was under the impression they were supposed to be like crappy [Blu-styles](http://www.mysmokeshop.net/img/products/1/bl5.jpg) vs. [fancy mods](http://www.3fvape.com/8627-thickbox_default/itaste-134-mini-advanced-personal-vaporizer-black.jpg).

**Comment by Leland** [comment]
No movement in nearing a full year – closing. If there's still an interest in discussion, ping me to reopen, or just create a new issue for sake of visibility.
