### ISSUE TITLE
Partial reloading isn't working

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#20843]
Pressing left or right in reload menu doesn't do anything.

Windows XP SP3, curses, 0.C-6393.

**Comment by Night-Pryanik** [comment]
The situation worsens. As for 0.C-6817 trying to press right on reload menu for empty revolver causes the game to crash.

**Comment by Divreus** [comment]
Currently getting a crash when accidentally hitting left or right while choosing whether to reload a crossbow with steel or metal crossbow bolts.
Was also getting a crash pressing left or right while trying to partial reload a UPS a few builds ago.

Windows 7 SP1, 0.C-6851

**Comment by Hugna** [comment]
Tested it on current build version. Windows 7 (SP1?) At build 0.C-6875, using the CDDA GL to test the version. Pushing the left and right while in the reload screen does indeed cause a crash/freeze.
