### ISSUE TITLE
Vehicle tanks un-rot milk.

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#20844]
How to Reproduce: 

- Debug Spawn a RV, some milk, and a rubber hose.
- Empty one of the RV tanks
- wait for the milk to spoil (debug switching to summer speeds this up)
- fill empty tank with the rotten milk
- siphon the milk out
- you now have fresh milk

Latest jenkins 6393
Windows x64 0.C-22067-gd8be874acf (tiles)
Default everything.

**Comment by pisskop** [comment]
: _o_

**Comment by WizardOfOoo** [comment]
Works with several rotten liquids.

**Comment by kevingranade** [comment]
Likely the same thing that was happening with kegs, something in the
handling code is resetting the age of the items.

**Comment by mdonline2** [comment]
Seems like too hard to fix this
How about just stop fill tank with rotable liquid?

**Comment by fengor** [comment]
according to https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/vehicle.cpp#L6234-L6236 you shouldnt even be able to fill the tank with milk.

**Comment by fengor** [comment]
Hmm seems rotten isn't exposed. will check and correct the fix over the weekend

**Comment by AMurkin** [comment]
may be related #20807
