### ISSUE TITLE
Rough rubble, sharp metal debris, and pointy items do not damage tires or vehicles in general

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#20847]
As pointed out, vehicle tires are pretty all-terrain.

**Comment by DangerNoodle** [comment]
I am reasonably certain that rubble counts as a collision-inducing obstacle if hit by tires at a bare minimum, which should cause some damage depending on vehicle speed and wheel durability.

Are you certain that you are running over the rubble directly? Some terrain like shrubs will trigger a collision no matter what vehicle part hits it, while others only count if a wheel hits it.

**Comment by dreyskiy** [comment]
I can second that issue.  My vehicle with armored tires can drive right over craters, helicopter crashes, etc without penalty.
