### ISSUE TITLE
Inconsistent container behavior; Crash. (Non-crash part solved.)

### ISSUE THREAD

**Issue by l-Ashery-l** [CleverRaven/Cataclysm-DDA#20850]
[Save available](https://www.dropbox.com/pri/get/Public/Rosa%20Sanchez.zip?_subject_uid=64891163&w=AAAATtK1ITsQY4NoLlXx3-L3ueNpBz5lWlCRo2itV1g1AA). Using the latest experimental (0.C-22069-g491bcd9bec (tiles)) on Win7.

So, having only a single portion of kompot left, I decided to unload it into another container and make a fresh batch of (3) kompot in the remaining time before bed. I fill up the first two sealed large stomachs just fine, but the third only fills to 6/12 and I get prompted to store the remainder in another container (I use a gallon jug). That's the first issue. The second is when I attempt to recombine the remaining kompot in a single container. When I try to unload the partially filled stomach, the gallon jug with the other 6/12 from the batch is listed as a valid option, but choosing it will cause a crash.

I've since recreated the crash several times, including from the .zip file linked.

Edit: The same inconsistent behavior can also be seen when unloading the keg of clean water two tiles south of where the character starts in the save file. The first two stomachs, again, fill to 12/12, but the third only goes to 6/12. No crash, however, is caused by unloading the water back into the keg.

None of the stomachs display damage, but I *did* have a spitter zombie wander by while I was cooking over the chasm to the E one night and it landed a blob of acid right on my doorstep (Hence the three piles of liquid and boxless toast-ems on my junk pile two tiles to the east). It's quite possible the stomach got damaged somehow, but I would have expected that information to be displayed somehow instead of just going unstated.

Edit 2: Now *that's* bizarre. I make two batches of kompot to fill the "good" stomachs up, and, as expected, when I fill the third one up with water, it fills to 6 only. So I unload it, and decide to debug in another sealed large stomach. This time, I only am able to fill the stomach to 4, but not only that, the *game doesn't even recognize that I have another empty container on me.* The only containers it shows as being valid are those lying on the ground.

Edit 3: Wishing in another large sealed stomach after unloading the water and I'm only able to fill to 2. Unloading and wishing in yet another, and the game fails to recognize that I have any valid containers at all.

Edit 4: Solved it: The game enforces a hard limit on volume with *no* feedback to the player as to why things are failing. Thinking that there's somehow an item overflow issue (Possible, but unlikely, as while I've got too much junk, it's nothing *that* excessive), I dropped my filled kompot stomachs and moved some plastic bottles of clear water away from my main stash. When I got back, two of the stomachs filled to 12, the third to 4, and the last wasn't recognized at all. That's when I noticed my volume being just shy of the limit.

Final edit: The crashing issue definitely still needs to be addressed, but I I'm not sure if that's been posted about elsewhere. Sidestepping the whole inventory issue I caused a crash by making one batch of kompot and putting the first three portions in a glass bottle and the remainder in a gallon jug. Pouring the bottle into the jug, as expected, caused another crash.

**Comment by Coolthulhu** [comment]
The restriction on volume depends on player's storage volume. That is, you can only fill a container as much as your inventory allows to without it falling out of it. Unless you hold it or put it on the ground first.

I'm not sure if I understand how is the crash working. The link to save is private or otherwise restricted and I can't get it to reproduce otherwise.

**Comment by l-Ashery-l** [comment]
Yea, I figured the volume thing out on the fourth edit, :D

The thing is, the game provides no feedback to the player when this happens, which may lead others to think it's a bug just as I originally did. There's no "You've reached your volume carrying limit. Choose another item to pour the liquid in." But even that would be considered bare bones, as the ideal would be to allow the player to drop a container to fill it. Wasn't much of an issue when I was in my base and had amble containers to pour into (Save for the crashing issue), but it'd be frustrating to lose a bunch when you're on the road.

Was able to recreate the crash on a brand new character. Bumped all skills to five, give mayself the necessary material to make some kompot, and a glass bottle and gallon jug to store it in. Made the kompot and poured the first three units into the glass bottle, with the remainder going into the jug. 'U'nloaded the bottle into the jug and got a crash.

[Does this link work?](https://www.dropbox.com/s/qqcscs4bpsh4ywb/Rosa%20Sanchez.zip?dl=0) First time using Dropbox to share stuff, so I guess I just didn't quite do enough to make the file publicly available.

**Comment by kevingranade** [comment]
Thanks for the repoduction, I was able to make it happen here.

**Comment by kevingranade** [comment]
hmm, it's in the item processing code, that's unexpected.  That means it wouldn't happen with non spoiling liquids.

**Comment by kevingranade** [comment]
I have a theory, the item ay be getting added to the active item list twice, then it'll be invalidated after te first time its processed.

**Comment by kevingranade** [comment]
Confirmed with gdb, as of when the crash happens, active_items has two copies of an item, one in the one-turn map, and the other in the 600-turn map.
