### ISSUE TITLE
Dodging while immune to damage levels dodge

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#20851]
while spending an hour and a half cooking meat i was attacked by a weak critter.  i was wearing an entry suit and was impervious to it.  additionally, my focus was at 20 whe  this stated.

i gained 3 levels of dodge while cooking meat on a stick with no focus and no danger.

maybe dodge leveling should compare atk skill or damage to your current level?  or something?

**Comment by Coolthulhu** [comment]
I proposed a similar idea earlier, but it was shot down for being unrealistic.
But honestly, it is an inherent problem with the dumb "learn by doing" skill system that isn't fully fixable without reworking skill gain to drop "learning by doing".

**Comment by kevingranade** [comment]
Yep, it's nonsense to adjust dodge learning based on damage, though basing it on relative ATK is fine (though I thought that was already happening).

**Comment by Coolthulhu** [comment]
> though basing it on relative ATK is fine

It is happening, it just does nothing to help with the problem.
