### ISSUE TITLE
Frostbite not applied properly

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20857]
Frostbite code is a mess that is hard to review due to horrible practices, so it's no wonder that it not working went under the radar. It is also a mess when it comes to game design, so no wonder no one could (or wanted to) tell it isn't actually working.

* Frostbite lacks a `max_intensity` field, meaning it is impossible to get frostbite, only frostnip
* Risk zones are applied in inverted order - ascending. As a result, howling snowstorm will not apply frostbite (only frostnip) if air temperature is above freezing

**Comment by kevingranade** [comment]
Please open an actual bug report instead of trash talking the code.

**Comment by Coolthulhu** [comment]
It's fine - it's better off not working anyway.
