### ISSUE TITLE
Some random npcs are causing problems.

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#20865]
Some of them come to me and start directly with a quest offer, not the usual 'are you friendly?' talk.
When declining the quest they leave, but the problem here is that when they decide to start taking your items in your Base/Car, you can not stop this, for example by telling them to go away or die. Starting to talk again will lead to quest talk only. No way around it. Only way i found was to kill them and take the morale penality.
I think this should be changed, it should be possible to continue to talk about the usual things after refusing to do the quest.

**Comment by dreyskiy** [comment]
I've had this happen on multiple occasions.  It would force me to run away with my shopping cart as they chase me down to try and rob me.  Have had to kill on several occasions.  Taking my stuff should at the very least flag them as not being innocent.

**Comment by ZenZen2** [comment]
duplicate of #19318
