### ISSUE TITLE
UPS-compatible recharging stations no longer present in the game?

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#20863]
Version 0.C-21751-g0d7bf2c072 is the version I'm using

All UPS items themselves are in the game, as well as other items that use UPS power to charge themselves, but the recharging station is not present in both the vehicle construction menu or the debug menu to spawn it in. I am not sure if this is intentional.

**Comment by Coolthulhu** [comment]
Not intentional

**Comment by MisterFox** [comment]
I am on build 6396 (0.C-22072-g5a7a105a22) and the recharging station appears in debug menu (http://i.imgur.com/4aGggiT.png) and in the vehicle construction menu (http://i.imgur.com/LXAmvot.png).

I assume 21751 is an older version but I'm not sure. Current experimental is 6397.

**Comment by Zilenan91** [comment]
It's only a couple weeks old at the most, but I'll get and post screenshots.

Though is it possible that a mod is causing this? I'm only using mainlined mods so nothing that should be super broken.

**Comment by Zilenan91** [comment]
https://cdn.discordapp.com/attachments/304019679457050645/304019765289287693/Untitled35.PNG Vehicle Menu

https://cdn.discordapp.com/attachments/304019679457050645/304019744518832159/Untitled36.PNG
Debug Menu

Going to update my game and see if the issue is fixed, if not it's most likely outdated mods and I will list which ones I am running.

**Comment by Zilenan91** [comment]
The issue persists. The mods I'm running are:

Medieval and Historic Content
More Craftables
More Survival Tools
Folding Parts Pack
Vehicle Additions Pack
Tanks and Other Vehicles
Disable Religious Texts
No Explosive Zombies
Classes and Scenarios Mod
Prevent Zombie Revivication

**Comment by Zilenan91** [comment]
I've already found results with Bright Nights and Craftable Gun Pack enabled.


Bright Nights is likely the mod that's causing the issue @Coolthulhu

**Comment by Zilenan91** [comment]
This is false

In the base game the UPS-Compatible Recharging Station is known as exactly that, but in Bright Nights it is renamed to "battery charger" for some reason and is still actually present in the game.
