### ISSUE TITLE
Volunteer Mutant and Unwilling Mutant should have mutations on game start

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#20861]
According to professions' name.

Is it oversight? Or adding mutations on game start is unimplemented feature?

**Comment by Zireael07** [comment]
IIRC those two professions have a slightly expanded set of starting traits, that does include some low-level mutations.

**Comment by DangerNoodle** [comment]
You can select additional mutations in the scenarios that these profesions occur, what mutations are up to the player, Not an issue.

**Comment by pisskop** [comment]
A random trait or two might spice up a playthrough ...

**Comment by Night-Pryanik** [comment]
> A (forced) random trait or two might spice up a playthrough.

That's exactly what I had in mind.

**Comment by Night-Pryanik** [comment]
Though additional traits are also available to all professions in this scenarios, like the Lab Technician, to which these traits (i.e. mutations) ain't a natural choice.

**Comment by DangerNoodle** [comment]
It would be reasonable to allow the player to roleplay as a scientist that engaged in some degree of self-experimentation. That is a rather common mad scientist trope.

Additionally, mutation is a possible side effect of failed bionic installation, and combining bionics with mutagen might be worth studying from a lore perspective, so it makes sense for the broken cyborg profession as well.

The only anomaly here is that mutant players have the option of not picking any mutations during character creation, but this can be abstracted away entirely if one assumes they were going to be subjected to mutation experiments, but the procedure was interrupted by the Cataclysm.

If said abstraction still seems abnormal, just renaming "Mutant" to "Experiment" removes the entire impetus for questioning potential player choices.
