### ISSUE TITLE
Temperature underground should deviate toward 10°C

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#20866]
It looks like it should be quite easy to implement and it'll be more realistic. This way root cellars for summer food storage should be possible. Obviously, this deviation should depend on depth also.

**Comment by DangerNoodle** [comment]
Would be interesting for a consistent temperature for comfort, but I can not recall whether or not temperatures above freezing have any effect on spoilage.

**Comment by kevingranade** [comment]
They do, this would make cellars at least partially useful.

**Comment by int-ua** [comment]
It's in Fahrenheit in the code :(

Looks like the place to add it is `src/weather_gen.cpp:weather_generator::get_weather`

**Comment by DangerNoodle** [comment]
> It's in Fahrenheit in the code :(

10 degrees Celsius would be 50 degrees Fahrenheit.

**Comment by int-ua** [comment]
Thank you, I can convert it, it's just causing discomfort and irritation :)

**Comment by Night-Pryanik** [comment]
Resolved by #24073.
