### ISSUE TITLE
Sudden decrease in building item count

### ISSUE THREAD

**Issue by bdgackle** [CleverRaven/Cataclysm-DDA#20860]
Using current master (commit 18a707), Linux, Tiles, Release build

Sometime in the last three or four weeks, the number items found in the shelters in the "sheltered" scenario seem to have dropped by about 75%.

It is possible that this was an intentional change, but I'm not seeing anything in the git logs that would indicate that someone did this on purpose.  If this was an intentional change for balance, then please disregard this report.

This is actually an interesting change (it certainly makes "sheltered" starts a lot more challenging), but if it was done accidentally then whatever changed might be causing wider ranging map generation effects.

**Comment by pisskop** [comment]
item spawning rules changed

**Comment by Vidiveni** [comment]
Can kinda confirm. 0.20 spawn rate now feels like 0.05 spawn rate. Problem easily bypassed by simply changing it in the options though.

**Comment by ZenZen2** [comment]
Its not a bug, item calculation is different now, as far as i can tell its more accurate now. Set it up to around 4.0 to have the same drop rate as the old 1.0 one. It is possible to set stable low item spawns now. Befor the change it was very random and somtimes there were way to many items.

**Comment by Vidiveni** [comment]
I'm fine with the change. Items tended to spawn in big piles even on low spawn rate before. Just fewer piles.

**Comment by bdgackle** [comment]
Okay, if it is intentional then not a bug; I'll close.

I don't have a problem with the new spawn rate per se.  Just wanted to make sure it was intentional.  It was a little rich before.
