### ISSUE TITLE
Crafted light amp goggles with atomic battery mod can not be (r)eloaded with plutonium cells

### ISSUE THREAD

**Issue by Vidiveni** [CleverRaven/Cataclysm-DDA#20878]
Trying will just print the "Out of battery!" message. The other devices I've tried work fine with the atomic mod (Heavy duty flashlight, Noise emitter, Makeshift welder). 

Windows x64 tiles build 6403.

**Comment by AMurkin** [comment]
Are you sure that was atomic battery mod? Maybe battery compartment mod?

**Comment by Coolthulhu** [comment]
Could be related to it being an armor. Does it reproduce with NV goggles?

**Comment by AMurkin** [comment]
Yeah, you mean infrared. Both is not an armor.

**Comment by Vidiveni** [comment]
No, I mean the atomic mod on the amp goggles. Not the battery compartment mod or the infrared goggles. Haven't tested infrared yet. I could try to upload a save.

**Comment by Vidiveni** [comment]
I can't reproduce either if using debug in a new game, but on my save they still don't work:

[CDDA Broken atomic mod on goggles save 170422.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/948800/CDDA.Broken.atomic.mod.on.goggles.save.170422.zip)

This is the folder with the name of the bugged world from inside the \save folder. Build 6404.

**Comment by Ishindri** [comment]
Can confirm, was able to reproduce on build 6416, Win 7 x64 w/tiles.

**Comment by AMurkin** [comment]
Can confirm too. Screenshot and part of savefile:

o ++ - is wished, z || - is crafted
![image](https://cloud.githubusercontent.com/assets/1931904/25649004/6791844e-2fda-11e7-8a08-8c225bd611eb.png)


bottom - is wished, top - is crafted
```
{
  "typeid": "goggles_nv",
  "bday": 1164841,
  "invlet": 122,
  "contents": [
    {
      "typeid": "battery_atomic",
      "bday": 1164874,
      "invlet": 73
    }
  ],
  "components": [
    {
      "typeid": "goggles_welding",
      "invlet": 65
    },
    {
      "typeid": "power_supply",
      "bday": 1164422,
      "invlet": 122
    },
    {
      "typeid": "amplifier",
      "invlet": 65
    },
    {
      "typeid": "amplifier",
      "invlet": 65
    },
    {
      "typeid": "amplifier",
      "bday": 415780,
      "invlet": 72
    },
    {
      "typeid": "scrap",
      "charges": 5,
      "bday": 633760,
      "invlet": 75
    }
  ],
  "curammo": "battery"
},
{
  "typeid": "goggles_nv",
  "charges": 5000,
  "bday": 1163440,
  "invlet": 111,
  "damage": -1.000000,
  "contents": [
    {
      "typeid": "battery_atomic",
      "bday": 1164874,
      "invlet": 73
    }
  ],
  "curammo": "plut_cell"
}
```

**Comment by Zireael07** [comment]
Crafted version doesn't have curammo set. Wonder why? @Coolthulhu

**Comment by Mooses2k** [comment]
In the spirit of the 'no making laser sights', and the spirit of balance, and lastly the spirit of having the scavenge rather than craft high-end gear, let's remove crafting on IR and NV googles.

**Comment by kevingranade** [comment]
Yes, this is not a reasonable thing to craft.
