### ISSUE TITLE
Used jumper cables (usually) won't stack

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#20871]
I'm just writing this down as a reminder, but if someone feels like fixing it, go right ahead:

From examining a savegame json, it looks like the jumper cables keep their `source_{x,y,z}` members when going into the `attach_first` state:
```json
 {
   "typeid": "jumper_cable",
   "charges": 3,
   "bday": 25122,
   "item_vars": {
     "source_x": "5045",
     "source_y": "7595",
     "source_z": "0",
     "state": "attach_first"
   },
   "invlet": 110
 },
 {
   "typeid": "jumper_cable",
   "charges": 3,
   "bday": 49871,
   "item_vars": {
     "source_x": "5047",
     "source_y": "7598",
     "source_z": "0",
     "state": "attach_first"
   },
   "invlet": 113
 },
```

Since the only place where the state is reset is in `item::reset_cable`, this would be the logical place to call `erase_var("source_x")` and friends.

**Comment by AMurkin** [comment]
same for misc parts
![cdda parts wont stack](https://cloud.githubusercontent.com/assets/1931904/25226805/e24b93ac-25ce-11e7-82fe-7708dce8da76.png)

**Comment by narc0tiq** [comment]
If they're damaged, then they're not the same item and shouldn't stack. So far, I only know of jumper cables that *should* stack, but don't.
