### ISSUE TITLE
Aspic can't take canned meat/fish in it's recipe

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#20873]

**Comment by Leland** [comment]
Code in question can be [found here](https://github.com/CleverRaven/Cataclysm-DDA/blob/491bcd9becfcae6d7fe9c7a805be8fc46c7268e3/data/json/recipes/recipe_food.json#L2410-L2442)

**Comment by Chezzo** [comment]
The recipe for vegetable aspic doesn't contain bones for making the gelatin.

**Comment by Dracace** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/21022

Can be a solution?

**Comment by DangerNoodle** [comment]
> The recipe for vegetable aspic doesn't contain bones for making the gelatin.

Read recipe comment. It explicitly states the difficulty is higher because the vegetable matter is being used to make pectin.

**Comment by Dracace** [comment]
#21022 merged, i think we can close here.
