### ISSUE TITLE
Plate armor is extremely unencumbering

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#20885]
What the title says. Plate armor (suit) and it's sub-components, cuirass (torso), pair of steel arm guards (arms), and pair of steel leg guards (legs) seem to far outperform anything else -- both medieval and modern composite armors -- in terms of it's defense-to-encumbrance ratio. It possesses a mere encumbrance of 10, but provides 24 points of bash and cut resist. All with 95% coverage. 

For reference, here's some other armor stacked up against Plate Armor:

Armor Name   | Encumbrance | Bash Resist | Cut Resist
------------ | ----------- | ----------- | ----------
Chainmail Armor | 10 | 18 | 18
Boiled Leather Armor | 12 | 15 | 15
Survivor Suit | 15 | 12 | 18
O-yoroi | 15 | 18 | 18
SWAT Armor | 25 | 14 | 23
Ornamental Plate Armor | 35 | 30 | 30
**Plate Armor** | 10 | 24 | 24

So I'd like to put forward a motion to significantly up the encumbrance of this steel plate set, as no other suit comes anywhere near having plate armor's 2.4:1 defense-to-encumbrance ratio. The only thing that really comes close is power armor (basic has a 2:1 defense-to-encumbrance ratio, while heavy has closer to a 2.5:1). If no one objects, I'd also like to tweak some of the other armors 

Edit by @Leland: moved to tabular data

**Comment by Chezzo** [comment]
It's 20, isn't it?

http://cdda-trunk.chezzo.com/armor_lightplate

**Comment by Regularitee** [comment]
20 before it's tailored so it **(fits)**. 10 after.

**Comment by DangerNoodle** [comment]
Are all the values for other armor also post-fitting?

**Comment by Chezzo** [comment]
Yeah, @Regularitee is totally right with all of it. My bad.

**Comment by Regularitee** [comment]
@DangerNoodle 
Yes, except SWAT armor, which cannot be fitted. All the others are fitted values.

**Comment by kevingranade** [comment]
Go ahead, I agree that sounds way too low.

**Comment by DangerNoodle** [comment]
In that case, a final encumbrance in between that of the o-yoroi and the ornamental plate armor might be best, as the armor values are in between those.

**Comment by Coolthulhu** [comment]
Keep in mind that straight `armor / encumbrance` is totally not enough for balancing and only good for gauging if it may need balancing.
https://github.com/CleverRaven/Cataclysm-DDA/wiki/Armor-balance

**Comment by DangerNoodle** [comment]
Under the simple value indicators, this suggests that a minor nerf to light plate armor would be acceptable, but ornamental plate armor and most of the MBR vests additionally could afford a buff.

According to this math (if I am correct), increasing post-refit encumbrance to 15 reduces the value to 1.2, worse than chainmail armor.

**Comment by Zireael07** [comment]
A final encumbrance between o-yoroi and ornamental armor would be spot on in terms of realism.

**Comment by Solusphere** [comment]
While it should probably be more encumbering than it is, I feel I should note that from a realism standpoint, non-ornamental plate should be less encumbering than chainmail. Chain has substantially more mass and a propensity to dangle.

**Comment by Regularitee** [comment]
@Solusphere That was my thinking as well. Ornamental plate is purely for looks, not protection, so would likely be thinner -- it's effectively a costume, and not meant to actually protect. The fact it has a [Fancy] tag adds to the idea it's not necessarily meant with warfare in mind.

So anyway, my proposed changes. I've nerfed cut resist across the board to prevent medieval armor from equaling or even surpassing modern bulletproof vests' ability to stop modern bullets. Instead, they will be more melee-focused, as they are intended; this will allow them to have a different niche than modern body armor, rather than directly competing to serve the same role.

- Chainmail Armor (old): 10 encumbrance, 18 bash resist, 18 cut resist
- Chainmail Armor (new): 14 encumbrance, 20 bash resist, 16 cut resist
Chainmail was currently equal to or lighter than leather armor, so increased the weight a bit. 

- O-Yoroi (old): 15 encumbrance, 18 bash resist, 18 cut resist
- O-Yoroi (new): 16 encumbrance, 18 bash resist, 15 cut resist

- Ornamental Plate Armor (old): 35 encumbrance, 30 bash resist, 30 cut resist
- Ornamental Plate Armor (new): 22 encumbrance, 21 bash resist, 16 cut resist
Significant nerf to ornamental plate, since medieval armor -- particularly decorative armor -- shouldn't be outperforming modern materials in terms of total defense.

- Plate Armor (old): 10 encumbrance, 24 bash resist, 24 cut resist
- Plate Armor (new): 25 encumbrance, 29 bash resist, 20 cut resist
Obviously increased weight, and shifted the focus to melee resistance.

- Scrap Suit (old): 15 encumbrance, 27 bash resist, 27 cut resist
- Scrap Suit (new): 35 encumbrance, 20 bash resist, 27 cut resist
The description suggests it's a highly "junk" like suit, so shouldn't really be so easy to wear, nor as well-designed as dedicated armor. 

And to satisfy those heavy metal enthusiasts who might be upset at the loss of their super-medieval armor, I'll probably throw in some early 20th century (WW1 and WW2) plate metal bulletproof armor, though these will be torso-only protection (possibly also head, since helmets were already universally used at the time, and no one would possibly issue body armor without also giving someone a helmet). These are not as light as the kevlar-type vests, but have a better weight-to-defense ratio than medieval armor.

- Lobster Armor (new): 15 encumbrance, 18 bash resist, 20 cut resist
Based off the WW1 German armor issued to officers and static defenders.

- Steel Bib (new): 13 encumbrance, 16 bash resist, 20 cut resist
Based off the assorted Soviet SN-series body armor used during WW2. 

Also maybe throw in some fictional, "survivor" variants for those still craving full body protection. Like the (entirely fictional, but admittedly cool-looking) pseudo-full plate from Battlefield 1. Basically taking the "Scrap Suit" concept already in game, and imagining a much more carefully designed and custom-built version.

- Survivor Plate Armor (new): 17 encumbrance, 29 bash resist, 26 cut resist
Covers all major parts of the body. Similar to plate armor, but revised to take advantage of modern metallurgy and composite materials.

I'll await feedback before implementing any of these new armors.

**Comment by DangerNoodle** [comment]
> That was my thinking as well. Ornamental plate is purely for looks, not protection, so would likely be thinner -- it's effectively a costume, and not meant to actually protect. The fact it has a [Fancy] tag adds to the idea it's not necessarily meant with warfare in mind.

The idea seems to be that it is possibly Maximmilian, White Italian, or some other late medieval or early Renaissance armor. These armors were often ornate even when functional, especially as fluting has both artistic and structural value. This would likely be armor from a period when being able to protect from musket fire was still an important consideration, though the light plate armor, being described as Gothic, would also logically date to a time period when resistance to firearms of the time period was an important consideration. See etymology of the term "bulletproof" for example.

**Comment by Chezzo** [comment]
Plate mail manufacturers would have their armor get shot with a gun at point blank range. They would then circle the dent from the bullet, as proof that you can get shot wearing them. It was the bullet proof.

http://www.throughouthistory.com/?p=880

**Comment by Zireael07** [comment]
@Regularitee: Medieval buff approves :P

**Comment by DangerNoodle** [comment]
>        O-Yoroi (old): 15 encumbrance, 18 bash resist, 18 cut resist
>       O-Yoroi (new): 16 encumbrance, 18 bash resist, 15 cut resist

I object. O-yoroi is already way worse than any of the other iron/leather armor in gameplay terms.

**Comment by Coolthulhu** [comment]
> So anyway, my proposed changes.

What are the new scaled values with the formula in the wiki link I posted?

Also, it would be much more readable if you tabled it:
```
A | B
--- | ---
C | D
```
becomes:

A | B
--- | ---
C | D

**Comment by Regularitee** [comment]
@Chezzo Yeah, but those were huge, round shots. As such, despite their high power, they had relatively poor penetration compared to modern bullets due to their lack of force concentration. Think of it like stabbing something with a needle versus stabbing something with a coin. The needle, despite being much smaller and more fragile, penetrates much better because all its energy is focused on a pinhead.

@DangerNoodle I read a bit more about it to respond to this comment. According to Wikipedia, the O-Yoroi used iron rather than tempered steel like the European full plate. As a consequence of using iron, the O-Yoroi's armor plating would be much heavier for the same level of protection, and as a result it only has partial coverage (non-vital parts of the armor are only leather). Wikipedia states that steel plate suits weighed 15-25 kg, while the O-Yoroi weighed 30kg. So given all this, the O-Yoroi should realistically be heavier than full plate, but have lower overall defense. 

@Coolthulhu I haven't run the numbers over there yet. Firstly because I was thinking of only tweaking the protection values for now. The one-sentence in-game descriptions of armors are too vague for me to imagine how much coverage each armor should have... so I haven't really considered any changes to coverage.

My intention is to do things incrementally. Right now full plate (and a lot of medieval armor, actually) is ZOMGSUPER overpowered in its performance. I'm trying to bring it back down to just plain old pretty powerful, and listen to feedback first before making a second round of balancing tweaks. As such I don't expect it will properly fit the armor balance plan you linked yet -- but I do know it'll be much closer to fitting it than it currently is right now.

**Comment by DangerNoodle** [comment]
> I read a bit more about it to respond to this comment. According to Wikipedia, the O-Yoroi used iron rather than tempered steel like the European full plate. As a consequence of using iron, the O-Yoroi's armor plating would be much heavier for the same level of protection, and as a result it only has partial coverage (non-vital parts of the armor are only leather). Wikipedia states that steel plate suits weighed 15-25 kg, while the O-Yoroi weighed 30kg. So given all this, the O-Yoroi should realistically be heavier than full plate, but have lower overall defense.

You are reading what I said incorrectly. I said that it is already inferior to the other iron armor, and that your solution will worsen that. Plated leather armor, chainmail, lorica segmentata (in Medieval and Historic Content), and other examples.

**Comment by Regularitee** [comment]
@DangerNoodle Any suggested values then? It probably should be inferior to iron-only armors in terms of protection, as it has leather-only coverage on many parts of the suit. I guess the question is just _how_ inferior it should be..

**Comment by DangerNoodle** [comment]
At a bare minimum it should likely not have worse coverage than plated leather armor. In gameplay terms, plated leather armor is far easier to make. The material usage is far higher for the o-yoroi if I recall.

In realism terms, you have a form of lamellar armor using iron plates and scales, versus that I assume is an up-armored leather armor. How much metal an o-yoroi has would likely vary though, but it is reasonable to assume that the player-made version is modeled after a higher-end version, as these seem to make up the majority of existing examples, as far as I am aware of.

**Comment by Regularitee** [comment]
I started editing the game files and realized the armor.json doesn't actually set specific resists on a per item basis (at least, not that I know of). Instead all bash and cut resists are just derived indirectly from the material and material thickness.

So I figure my options are to:
- Ask more veteran contributors and hope there's some way to manually set armor resists that I just don't know about yet
- Only tweak encumbrance and material thickness to rebalance armor (does thickness actually affect resists, or just the probability of the armor being damaged on impact?)
- Create a custom material with the desired high bash resist and low cut resist, for use in medieval armor
- Modify existing iron/steel to have higher bash resist, low cut resist, to better fit the melee-centric role of medieval armor

**Comment by DangerNoodle** [comment]
> Modify existing iron/steel to have higher bash resist, low cut resist, to better fit the melee-centric role of medieval armor

That would be completely the opposite of how you defeat medieval armor. You use a mace or warhammer. Blunt impact is capable of denting the steel and transferring the impact to the wearer, whereas even with half-swording, thrusting through the cuirass is less likely than using said method to more accurately target the joints of the armor, and cutting through it is less likely without a more point-heavy weapon.

**Comment by Coolthulhu** [comment]
> Only tweak encumbrance and material thickness to rebalance armor

This one.

**Comment by Regularitee** [comment]
@DangerNoodle 
You're forgetting that in this game, almost all cut damage is bullet damage, and almost all bash damage is zombie melee damage. 

You're right about it being unrealistic, but that's the fault of the game engine for not discerning between slashing damage (swords) and piercing damage (bullets). Not a fault of the armor itself.

I think it'd be more unrealistic to have medieval plate armor deflecting military-grade rifle bullets (higher cut resist) than for swords and knives to overperform against medieval armor (lower cut resist).

**Comment by DangerNoodle** [comment]
> You're forgetting that in this game, almost all cut damage is bullet damage, and almost all bash damage is zombie melee damage.

True. That would ideally require a more advanced solution, however. A rough start would be giving a higher pierce to bullets in general, and balancing them with the expectation that plate armor is meant to handle musket fire, not modern rifle round. But this would backfire unless it also heavily affects damage to monsters, as then turrets and NPCs would be even more dangerous.

**Comment by terribleperson** [comment]
Just to provide some reference materials for the encumbrance of plate armor, if you search "Armour aerobics" you will get a video that includes a guy doing a cartwheel in plate armor. There's also a video of a guy climbing a climbing wall in a set.

While articulated plate armor certainly isn't jeans and a t-shirt it may very well be less encumbering than modern body armor. The reality of armor that works against modern rifles is that you universally need thick and heavy material with padding behind it. A fully filled plate carrier can weigh more than half of a set of plate armor. 

It's certainly not something that should even be thought about for 0.D, but the bash/cut/pierce damage system might need a revamp. Even a suit of plate armor made in a time when firearms were a concern on the battlefield isn't going to stop modern rifle rounds (AP or not), but it'll do an absolutely wonderful job of keeping zombies off of you and it works just fine against swords. On a similar note but in a different direction, Kevlar and other aramids in the configurations seen in vests do very little to protect you against stabbing implements and won't stop a rifle round. They also provide little protection against large impacts. On the other hand, they stop pistol rounds very well and do provide protection against cutting damage. Even in other uses, aramids tend to be difficult to cut.

**Comment by DangerNoodle** [comment]
Ideally armor balanced against melee and musket fire needs some way to be more severely affect by modern ammunition. Conversely, ballistic armor would need some additional factor that makes them more effective against ranged attacks.

I can see a way to implement this though. The first is for bullets in general, modern ones moreso, to have greatly increased piercing. The second would be for armor, or at least materials, to have an additional properly that specifically lowers the effective pierce value of rounds hitting it.

A second method would be for ballistic damage to be made an entirely different damage type, allowing for leather to have an extremely low ballistic resistance, steel to have enough that an MBR vest will protect more than steel plate armor, and for kevlar to have a modest protection that is not high enough to shrug off rifle rounds.

Both methods will also potentially require MBR vests to have greater material thickness. But realistically, while a spear will get through kevlar, a steel SAPI plate will handle a spear even better than plate armor, being harder and thicker. The coverage and not being designed for melee combat is the primary concern.

**Comment by DangerNoodle** [comment]
Regardless, I agree this should be a long term issue, for after 0.D.

**Comment by AlecWhite** [comment]
>Regardless, I agree this should be a long term issue, for after 0.D.

Do you mean being able to tweak damage defense for each armor instead of the general one we have now?

**Comment by DangerNoodle** [comment]
I mean adding primarily adding an additional damage type for ballistic weapons to use, then adding differing resistances to them at the material level.

**Comment by elricsfate** [comment]
@terribleperson 

>While articulated plate armor certainly isn't jeans and a t-shirt it may very well be less encumbering than some body armor.

Unless I'm understanding your meaning, I believe you're incorrect in your assertion.

Modern body armor with ceramic plates are going to less encumbering than plate mail. They are certainly "cooler" (in regards to temp) as opposed to plate armor.

To use an example

https://en.wikipedia.org/wiki/Interceptor_body_armor

The **Interceptor Body Armor** (previously used by the US Army) fitted with SAPI ceramic plates will weight around **16lbs**. 

A suit of plate armor will weigh around **15-25kg** or **~33-55lbs** when made out of well tempered steel. 

The Interceptor Body Armor was replaced with with the **Improved Outer Tactical Vest**. 

https://en.wikipedia.org/wiki/Improved_Outer_Tactical_Vest

The IOTV outfitted with improved ESAPI plates will weight **~33 lbs** which is at the lower end of what Plate Armor might weigh. 

>I have no idea if you can shoulder a rifle in it, though. I'd think at the very least it'd be difficult to find a spot to seat it unless you have a rubber buttstock pad.

Is it possible? Probably. Would it in anyway be feasible in a combat situation requiring quick reactions and effective aiming? Almost certainly not. 

@Regularitee 

Regarding the WW1 and WW2 era armor: 

These suits of armor provided very little defense against gunfire. Their primary objective was protecting against shrapnel. 

Using the "Steel Bib" example: this armor was meant to protect against 9mm bullets at a range of ~100-150 meters. It was sometimes able to protect against 7.62 mauser rounder assuming these rounds struck at an angle. 

https://en.wikipedia.org/wiki/Steel_Bib

This is ~ equivalent to a Class 2 vest by today's standards.

https://en.wikipedia.org/wiki/Bulletproof_vest#Performance_standards
https://www.globalsecurity.org/military/systems/ground/body-armor1.htm

@kevingranade 
@Regularitee 
@terribleperson 

If it has not already been done, it would likely be prudent to create a firearm/ammo/armor system where certain calibers/rounds completely or almost completely bypass worn armor. 

For example, plate armor would not withstand a shot from a modern steel core rifle round. This is before we even talk about armor piercing rounds. 

A Class 2 vest (for example) should not provide protection against rifle rounds. Only a modern ceramic based armor (or a metal of sufficient thickness) should be able to do this.

**Comment by smolbird** [comment]
> Modern body armor with ceramic plates are going to less encumbering than plate mail. They are certainly "cooler" (in regards to temp) as opposed to plate armor.

Slight flaw in this assertion. Hint: It starts with the fact that a plate armor cuirass generally wasn't a solid slab of metal (separate breastplate and plackart), allowing more articulation than a solid SAPI plate.

**Comment by kevingranade** [comment]
Closing due to lack of progress.
