### ISSUE TITLE
Poison gas dissipation

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#20883]
I've noticed that poison gas from boomers tends to linger much longer indoors than outdoors. Even when the gas is in immediate proximity to open windows, doors, or even huge chunks of missing walls.

I know actually simulating airflow isn't a viable option because it would be a huge CPU load. But anyone have any good suggestions on alternatives to handle indoor gas?

One possibility I'm thinking is having the game use the mechanism used to calculate where sunlight illuminates the inside of a building. Since sunlight appears indoors in proximity to windows, doors, and openings in the building, you could simply have a gas-filled tile check for if that tile normally has sunlight, and accelerate it's dissipation accordingly. 

It's imperfect (doesn't account for closed windows or glass doors), but it's more accurate than the current system. Though I don't know how difficult it would be to implement, in terms of code.

**Comment by pisskop** [comment]
boomers dont emit gas i  coregame.

the huge ones do in pks rebalancing mod.

the gas is not poison, but radioactive gas, which has a longer half-life, ironically enough

**Comment by kevingranade** [comment]
The code that handles shining light through windows into interiours finds borders between "inside" and "outside" areas, and projects a cone of light into the "inside" area.  It doesn't make any sense to apply this system to gasses or smoke.
Other than better modelling gas dispersion (which we do for scent, but it's really expensive), I don't have any ideas.
Pleas open this on the forums if you want to keep discussing it, the issue tracker is for concrete bug reports nd feature requests, not speculative ones.
