### ISSUE TITLE
Police Bots and Riot Control Bots attack SWAT Officers/people wearing the SWAT ID

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#20902]
I tested around with eyebots for a bit on a freshly created world after getting an idea that if I took off my SWAT ID and walked over to one, then put my SWAT ID back on after it scanned me, I could possibly summon in non-hostile Riot Control Bots to clear out some swarms. Did not turn out very well, as while the Riot Control Bot repeatedly scanned me it still vented gas on me constantly and the police bot tased me over and over again after I put the ID back on.

This could also create problems if NPCs trigger eyebots as well, as once the bots kill the NPC they might come for you afterwards even if you're part of SWAT and I don't think such a situation should happen.

**Comment by kevingranade** [comment]
The override for police only exists for eyebots, specifically to prevent what you were trying to do from happening.
