### ISSUE TITLE
Cold effect painkiller discrepancies

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20904]
Cold effect causes a relatively strong `pkill` - 30 for cold, 60 for freezing.

I assume this is supposed to represent the numbness caused by the cold. But then, there are multiple problems with that:
* `pkill` affects the entire body - frozen foot will prevent pain from a broken arm
* It stacks with (some) other painkillers, so that same dosage of opiates may kill you if your foot is frozen
* Body parts that are the most likely to be freezing (feet, mouth) are the ones that are the least likely to take hits
* Freezing torso or head should not get numb - they are still much warmer than a chilly hand or foot
* We don't simulate local numbing for other effects, so this is out of place

So if the rationale for this `pkill` effect of cold is representing reality, it should probably be dropped.
If it is an UI/gameplay thing, it could be lowered to 10 or so - damage from cold ticks long enough that it's not very likely one will experience a lot of pain from it.

On a side note, effects of cold are all scaling the chances, but not using floor chances. As a result damage and stamina drain from freezing does not happen any faster than from cold, because the chance is halved. Same for `pkill` ticks - those are doubled so the `pkill` accumulates as fast as before.
This is obviously unintended because the magnitude of damage, stamina drain and `pkill` is increased, implying that the author wanted it to happen twice at fast (it is incredibly unlikely that author wanted it to happen in "bursts").

**Comment by Night-Pryanik** [comment]
I'm in favor of removing painkiller effect  as a substitute for the numbness due to the frozing.
