### ISSUE TITLE
Disproportionate tracer-variant ammo spawning in lab armouries?

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#20907]
Now I'd like it if someone could back this up for me, but in my current game I've raided over ten armoury rooms across multiple labs, and have so far racked up over 500 rounds of 5.56 tracer ammo, and 200 rounds of 7.62 tracer. I have yet to encounter any other variant of either. Something seems screwy, though it could just be random chance. Can anyone else corroborate this?

**Comment by kevingranade** [comment]
What is the desired ratio of tracers to non-tracers?

**Comment by Solusphere** [comment]
Assuming you're asking me, my main concern was just that it appeared that tracer might be the ONLY variant that's spawning. If you're looking for ideas to fine tune the balance though, IIRC tracers are rarely used as the only ammo type in a magazine, instead being used for every fourth or fifth bullet, which is enough to help with aiming. So based on that, and mixed ammo loads notwithstanding, a 20% chance of a given ammo spawn being tracer seems pretty reasonable to me.

**Comment by DangerNoodle** [comment]
> If you're looking for ideas to fine tune the balance though, IIRC tracers are rarely used as the only ammo type in a magazine, instead being used for every fourth or fifth bullet, which is enough to help with aiming. So based on that, and mixed ammo loads notwithstanding, a 20% chance of a given ammo spawn being tracer seems pretty reasonable to me.

If I recall, the description of tracer ammunition refers to it as a 4-to-1 mix, as a workaround to being unable to mix differing ammunition. In code terms however, every shot fired acts as if it is a tracer.

**Comment by kevingranade** [comment]
> Assuming you're asking me

Yes I'm asking you wat the ratio should be, if you don't have a desired spawn rate, the issue isn't valid.  If there's a target ratio the fix is trivial.

**Comment by DangerNoodle** [comment]
What is the proportion of light machine guns to other 5.56x45mm and 7.62x51mm firearms, in lab armories? That would be a good baseline for desired ratio of tracer mix to standard and steel-core ammunition, if no other recommended ratio can be provided.

**Comment by Solusphere** [comment]
> Yes I'm asking you wat the ratio should be, if you don't have a desired spawn rate, the issue isn't valid. If there's a target ratio the fix is trivial.

No worries, I was just surprised you were asking me for game balance ideas seeing as I was initially just treating it as a bug report. Given that you're overwhelmed with low-priority issues right now, feel free to put this on the backburner, but if/when it does become worthwhile to fix, here's my research on the issue:

Here's a screenshot of my total ammo stockpile. Due to the specifics of my mapgen, there are no towns in the vicinity, and this ammo is 95% from labs, of which I've completely raided five so far.

![ammo totals](https://cloud.githubusercontent.com/assets/19789267/25572995/85a25d36-2e73-11e7-8760-2e789c66450c.png)

As you can see, 5.56 tracer is the most common ammo type, with regular 5.56 not making an appearance at all. (.223 appears in limited quantities inside, which makes sense seeing as it's not generally used by the US military).

I found a total of one M249 in the five labs, which is the only weapon I've found there which would realistically make use of 5.56 tracer ammo. I have however found dozens of 5.56-using battle rifles and assault rifles such as SCAR-Ls, L52B-MBRs and M27-IARs.

So my suggestion would be to make 5.56 NATO M855A1 five times more likely to spawn than Tracer, which still provides tracer in usable amounts without making it the only type to appear.
