### ISSUE TITLE
Invincible Sludge Crawler

### ISSUE THREAD

**Issue by TheLyca0n** [CleverRaven/Cataclysm-DDA#20905]
Unfortunately the sludge crawler appears to have the hitpoints/healing ability of zombie hulk wolverine that is addicted to stimpacks (discovered after it taking 20 .762 rounds and 3 pipe bombs)

**Comment by kevingranade** [comment]
Working as intended.

**Comment by TheLyca0n** [comment]
Wait really ???, Why are they invincible ? as I found fuck all about them on the wiki or otherwise and I just thought it was a bug as nearly every other creature in the game is kill able through some means as far as I am aware.

**Comment by TheLyca0n** [comment]
Sorry btw as I genuinely wasn't aware that there was a reasoning for this x)

**Comment by kevingranade** [comment]
You can definitely kill them, it's just really hard and you have to work at
it.  It's also completely not worth it to kill them in general, so just
avoid them.
To turn this around, why *must* everything be killable?

**Comment by TheLyca0n** [comment]
A better question is....why is this "Slug" unkillable yet many other eldritch horrors are beyond killable with the same method or what gives them this near immunity to bullets (as I doubt they would survive long in our reality with that sort of metabolism)

I would understand larger blobs having this ability beside portals because from a lore perspective the blob are interdimensional bullshit that is close to unkillable near there anyway or even a eldritch god doing similar to that, but I find these things in fucking sewers and basements with no justification as to why resurrect like jesus on crack
