### ISSUE TITLE
If a turret with a disintegrating ammo belt fires, it does not drop ammo belt linkages

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#20908]
This means that anything mounted on a vehicle using ammo belts for ammo cannot refill their ammo unless you find more ammo belts for them.

**Comment by ZenZen2** [comment]
Confirming that somthing doesnt work with some linkages.
Tested this with armoured car. Car spawned with 2x 249 loaded with the same ammo. The front weapon drops casings and linkages to the seat below it, the gun on the back of the car droped only casings to the door container below it, no linkages.

Looks like the error comes from the ammo belt.
Unloading the weapon that doesnt drop linkages and loading a different 249 that is used by the survivor himself (not as a turret) and shoting, still no linkages. But taking the ammo belt that comes from the front gun and loading the same 249 with it, produces linkages.

**Comment by ZenZen2** [comment]
I just deleted my last post here because i was wrong.

I can not confirm this bug.
From my testings everything works as intended.
Default Mods, 6411.
Some turrents doesnt drop linkages because they are not spawned with ammo belt, istead they are loaded with normal Magazines and those do not drop linkages.

**Comment by DangerNoodle** [comment]
Observed the same thing in a recent build, 6410. Encountered a humvee with a loaded M240, which had an ammuniton belt loaded. Firing it littered the ground around it with 7.62x51mm cases and ammo belt links.

**Comment by Zilenan91** [comment]
Tested with an M249, the M249 dropped ammo belt linkages if it was mounted above a storage compartment such as a trunk or chair, but if not placed on one of these instead dropped no linkages

**Comment by DangerNoodle** [comment]
Strange.

**Comment by ZenZen2** [comment]
Still, i can not reproduce your Bug. Tested M249 with ammobelt, mounted it on a spot with no container. casings and linkages droped below the car.

**Comment by Zilenan91** [comment]
I'll just close this then
