### ISSUE TITLE
Removing a turret from a vehicle deletes the ammo if it has not been removed already

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#20906]
Tested with an M249 using a 5.56 ammo belt

**Comment by DangerNoodle** [comment]
The latter is additionally important enough to potentially warrant a separate issue. This effectively breaks the intended long-term usage of the heavier weapons such as the M2 Browning, Mark 19, M134D-H, and the 30mm autocannon.

**Comment by Zilenan91** [comment]
I'll remove the description and make the second issue then

**Comment by ZenZen2** [comment]
Can not confirm. Weapon still loaded after removeage.
Default mods 6411.

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed for more than half a year.
