### ISSUE TITLE
Request for help with issue triage.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#20913]
As previously outlined in #19197 we are currently suffering under a large number of issues, but some relatively recent improvements to the github permissions model offers a solution.

I'm working on some guidelines for issue triage, but in order for it to be effective, we need people to implement the new guidelines.  As such I'm asking for volunteers to join the new @CleverRaven/maintainers team.  If you've ever wanted to pitch in and help the project, but aren't interested in and/or able to code or edit json, this is an *extremely* helpful task you can take on.

If you're interested, just reply to this issue and I'll add you to the team.

**Comment by Night-Pryanik** [comment]
I'm curious, what sort of work these maintainers will do?

**Comment by kevingranade** [comment]
The main thing we need help with is examining the backlog of issues and
labelling them as appropriate, and in some cases closing them.

You'd also have permission to update the attached wiki.

**Comment by Night-Pryanik** [comment]
I'm interested, count me in.

**Comment by Zireael07** [comment]
Count me in - I've been commenting on issues a lot as it stands.

**Comment by bdgackle** [comment]
I'd be willing to help.

**Comment by ituluwituluwzev** [comment]
I'm &sect k on the forum, and I think I can help. Once I binge-read all open issues last winter. Are the 903 open issues the things we're going to tag? If 9 out of 10 of them need 5 minutes each,  and 1 needs 10 minutes, then 10 issues can be tagged in 1 hour, which means 90 hours for all of them, which seems a feasible task.

**Comment by ZenZen2** [comment]
Im interested in helping with this.

**Comment by Cyrano7** [comment]
I'd be interested.

**Comment by Leland** [comment]
👍 definitely interested.

**Comment by kevingranade** [comment]
Thaks for the interest! I've jotted down some notes in the "Issue Triage" section of http://cleverraven.github.io/Cataclysm-DDA/pages/issues.html to get started, we need some more complete instructions before we can really get started, I'll try to have that up soon.

Anyone else that's interested, I believe you can visit https://github.com/orgs/CleverRaven/teams/maintainers and request an invite.

I'll close this issue for now to avoid contributing to the problem ;)

**Comment by Cyrano7** [comment]
@kevingranade the link is not working on my end. "Page not found".

**Comment by Zireael07** [comment]
"Page not found" when clicking the link :(

**Comment by kevingranade** [comment]
Weird, I can visit it, but I think that's because I'm an admin :/

**Comment by Cyrano7** [comment]
@kevingranade so once I joined the group I could see the page. But I still can't add tags to or close issues.

**Comment by kevingranade** [comment]
I'll see what I can find, I probably missed some option.

**Comment by kevingranade** [comment]
I had to both set up the team and add it to the repository, missed the
second part.  Can someone that accepted the invite try and change some tags
and/or toggle some issues open/closed?

**Comment by Night-Pryanik** [comment]
Working.

**Comment by Night-Pryanik** [comment]
Adding and removing labels is working too.

**Comment by Cyrano7** [comment]
@kevingranade So besides opening/closing issues and adding/removing labels. The maintainers have access to modding the wiki, creating/modifying/deleting labels, locking conversations, renaming PRs and issues, opening/closing PRs, starting/deleting/modifying projects, and adding/removing/creating milestones. IDK how much access was originally intended but it seems pretty liberal.

**Comment by kevingranade** [comment]
Thanks for catching that.
@Cyrano7 you missed creating and pushing to new branches ;) (The "main" branches are locked down).
Github has very... sparse permission support,  so this very liberal set of permissions is literally the least permissions you can grant.   To directly answer your question, yes I was aware it was going to grant all of those permissions. 
On that note, I can't think of a good reason for someone else to edit milestones, but if you want to edit or create new projects, feel free.
I discourage locking conversations outside of actual abuse (mostly spam, including unproductive "me too" type posts), even closed issues should generally stay open for comment.

Thanks for piling onto the issues, if you're subscribed to issue notifications you know there's been a huge wave of issue review.  I hope no one is offended at the I think two issues I re-opened, it's not that you did anything wrong, there are just some issues I'd prefer to keep open so I keep any eye out for certain things.

**Comment by Leland** [comment]
@kevingranade definitely not offended - you know better than the rest of us what to keep open.

The way I see it, closing an issue isn't a destructive action. They're still searchable and easily reopened if the ticket creator (or another CDDA user) wants it.

A status update: all issues [are now labeled](https://github.com/CleverRaven/Cataclysm-DDA/issues?q=is%3Aopen+is%3Aissue+no%3Alabel), and we've cleared off around 130 of them so far. I'm going to be continuing to go through [old, stale suggestions](https://github.com/CleverRaven/Cataclysm-DDA/issues?q=is%3Aopen+label%3A%22Suggestion+%28Discuss%29%22+sort%3Aupdated-asc) and [enhancements](https://github.com/CleverRaven/Cataclysm-DDA/issues?q=is%3Aopen+label%3AEnhancement+sort%3Aupdated-asc) today.

There's a bunch of [JSON](https://github.com/CleverRaven/Cataclysm-DDA/labels/JSON) and [easy-fix](https://github.com/CleverRaven/Cataclysm-DDA/labels/Easy-fix) issues/suggestions that just about anyone could take care of in a few minutes if they so wished via a PR.

Finally, I'll be opening a PR with an [Issue template](https://github.com/CleverRaven/Cataclysm-DDA/issues/20934) at some point this week which should help a bit with future issues.

**Comment by Leland** [comment]
Alright, we're at ~750 issues now, down from around 1000 a month ago.

There are [168 issues](https://github.com/CleverRaven/Cataclysm-DDA/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20created%3A%3C2016-09-01%20sort%3Aupdated-asc%20%20-label%3Abug%20-label%3Acrash%20) remaining that A. aren't bugs or crashes and B. were created before September 2016.

It's increasingly slim pickings in there, but it is where I'd recommend the other members focus their efforts – they're certainly the easiest to close.

**Comment by Night-Pryanik** [comment]
Sorry for necroposting. 
@kevingranade just want to be sure - there is no way to forbid creating branches for me while still permit labelling and opening/closing issues, right?

**Comment by kevingranade** [comment]
Not that I can see, the actual permissions setup is you have write access to the repository, but the existing branches are configured to not allow pushes unless you have an additional permission flag.

In other words, the same permission required to let you write to issues also lets you push branches.

You might be able to configure your git client to enforce this.  You used to be able to clone using a read-only url, but that doesn't seem to be an option anymore.

**Comment by Night-Pryanik** [comment]
OK, thanks.
