### ISSUE TITLE
Keybindings for zoom are backwards

### ISSUE THREAD

**Issue by RevEng** [CleverRaven/Cataclysm-DDA#20918]
I believe the Zoom In and Zoom Out keybindings have been mapped to the opposite functions. I currently have Zoom Out mapped to "z" and Zoom In mapped to "Z". When I press "z", it zooms in -- I have a narrower field of view and each tile is larger. Conversely, when I press "Z", it zooms out -- I have a wider field of view and everything tile is smaller.

**Comment by Rod-Serling** [comment]
Looks like the logical functions of game::zoom_in and game::zoom_out are opposite of what they should be, and have been since the original implementation (#6037) Should be able to just switch them around.
