### ISSUE TITLE
Riot Control Bot Sedative Gas Gun Aiming Loop/Hang

### ISSUE THREAD

**Issue by ZChris13** [CleverRaven/Cataclysm-DDA#20923]
If you attempt to aim a ranged weapon (in my case a crossbow) while under the effect of the sedative/pacifier/relaxation gas from a Riot Control bot using the 'p' "precise aim" command you will be trapped in a loop for in-game hours as you attempt to take aim with your gun at the robot but are continually sedated. My character was only freed from this loop due to a Hazmat zombie who happened to wander near.

**Comment by somot** [comment]
Do any prompts appear?

**Comment by ZChris13** [comment]
The only prompts you'll get is if a new enemy appears in your LOS which was how I got out of it, several in-game hours later.
Coincidentally, there should probably be a cap on the relaxation gas effect. I had to wait something like 14 in-game hours for it to wear off. 9 am - ~11 pm

**Comment by somot** [comment]
Did you try to press (.)? That's a key for interrupting activities and aiming.

**Comment by ZChris13** [comment]
Yes! I tried pressing . and 5 and enter and Esc, nothing works. It did not interrupt until a new enemy entered vision/approached/I was attacked.
I highly recommend you try it, it's very simple to reproduce using debug. Simply spawn a riot control bot and a crossbow with a bolt, press f to aim it at him, then press p. If he hits you with the happy gas, you'll be trapped there until a zombie or hostile critter wanders along or potentially you get tired/hungry/thirsty?
If it makes a diffference, I'm using the experimental build 6411 x64 version.

**Comment by spacenookie** [comment]
if you get attacked you get a chance to cancel your action in player::do_hurt. if you instead stand in a relax gas field you get an environmental effect (effect_relax_gas), which currently doesn't trigger a chance to cancel. looks like this applies to all fields/environmental effects.

each turn you stand in the relax gas you get 3 more turns of env effect with no maximum currently defined. max would be defined in data/json/effects.json with tag "max_duration"

**Comment by spacenookie** [comment]
did you get arrested? looks like there is a path where game swaps your weapon for handcuffs (without interrupting your aim action) and then you can never steady your handcuffs well enough to reach the threshold to actually fire.

game should probably cancel your action when you get handcuffed.

**Comment by Night-Pryanik** [comment]
Closed by #20923.
