### ISSUE TITLE
Crash on setting floating point options

### ISSUE THREAD

**Issue by ifreund** [CleverRaven/Cataclysm-DDA#20927]
If you press enter in the options menu to input floating point values directly the game crashes.  This crash does not occur if you do not modify the value.  Using arrow keys to change the value works fine.
Error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Abort trap: 6
```

**Comment by AMurkin** [comment]
What version? Custom build?
Can't reproduce.
May be related #19720.

**Comment by ifreund** [comment]
Hmm I've rebuilt since experiencing this problem and I can't reproduce.  I'll try to recreate the situation.  If I get this to happen again I'll post here

**Comment by AMurkin** [comment]
Or #20624 may be related.

**Comment by ifreund** [comment]
Ok, I can reproduce it now.  This crash occurs when I compile with gcc 6.3.0 but not when I compile with clang.  I'm compiling on macOS 10.12.  Crash occurs both with and without tiles.

>Or #20624 may be related.

This seems most likely to me.  @Coolthulhu is this crash still happening for you? Does it crash for all floating point options?

**Comment by BrettDong** [comment]
Type `locale` in the shell and what's the output?

**Comment by ifreund** [comment]
```
ifreund$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by Night-Pryanik** [comment]
#21927 fixed this?

**Comment by kevingranade** [comment]
@ifreund does this still happen?

**Comment by ifreund** [comment]
Just checked on the latest build, could not reproduce anymore.
