### ISSUE TITLE
Error on compiling with LUA support.

### ISSUE THREAD

**Issue by Wad67** [CleverRaven/Cataclysm-DDA#20926]
I have liblua5.2-0:amd64 & liblua5.2-dev:amd64, forgive me if that is the incorrect version. 
Attempting to compile with:

`make -j6 RELEASE=1 LUA=1`

Results in:
```
/bin/sh: 1: astyle: not found
cd src/lua && lua generate_bindings.lua
lua: ../../lua/class_definitions.lua:2157: unexpected symbol near `#'
stack traceback:
	[C]: in function `dofile'
	generate_bindings.lua:435: in main chunk
	[C]: ?
Makefile:697: recipe for target 'src/lua/catabindings.cpp' failed
make: *** [src/lua/catabindings.cpp] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by ifreund** [comment]
I have no problems using lua 5.2.4, so I assume that the version is not the issue.  Could you provide more details? What operating system? Has it worked for you in the past?

On a side note, when you paste in a multiline of code like that to github, its better to use three graves (\`\`\`) before and after. It'll look nicer, like this:

```
line 1
line 2
line 3
```

**Comment by Wad67** [comment]
Running Ubuntu 17.04 x64
It has worked previously, however this is a fresh install. 
Compiling without the LUA flag works fine.
Unable to test on Windows as I'm not interested in hunting down the deps for that. 

'''
thanks
for the
info 
'''

**Comment by kevingranade** [comment]
The game requires liblua, the build process also requires the lua binary.
Both of these dependencies will be disappearing after 0.D ( see #20819 )
