### ISSUE TITLE
long item descriptions does not show fully

### ISSUE THREAD

**Issue by Tsunder** [CleverRaven/Cataclysm-DDA#20929]
an item with an extensive description (i.e., a weapon with several mods) seems to cut off.

example:
http://i.imgur.com/pT70HVX.png

**Comment by somot** [comment]
Use Page Up/Down to scroll.

**Comment by Toothspit** [comment]
The mod description is cut off, only 3 lines are shown, scrolling won't reveal the rest.

**Comment by Tsunder** [comment]
example: 
![image](https://cloud.githubusercontent.com/assets/5103517/25608536/37eb33f8-2ee9-11e7-9075-0b6848f7ae5b.png)

world: [Ravenden.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/969726/Ravenden.zip)

**Comment by Leland** [comment]
Duplicate of #19622
