### ISSUE TITLE
RM451 Flamethrower is so rare it might as well not exist

### ISSUE THREAD

**Issue by Aranzada** [CleverRaven/Cataclysm-DDA#20931]
I challenged myself with a character that can only kill enemies with fire and explosions, so I was looking for the RM451 flamethrower and after a (long) while I got frustrated and started savescumming a bunker... still havent found it after 150+ tries (yes I know about the debug menu but I want to do it this way).

I checked the code and I found out it can only appear in two places, so I calculated the chances of finding it:

Around 1 in 250 Military Bunkers (5/408/14x6x0.8)
Around 1 in 25 thousand Survivor zombies (5/408/218)

I know it's a powerful weapon but imho it's wayyy too rare, (who checks 250 bunkers?) It's a lot rarer than all the other powerful stuff.

My suggestion is to simply change the weapon probability in the mil_hw item group from 5 to 25, so it's 1 in 50 bunkers, still rare but not insane.

On a side note I would really really like if there was a recipe to reload 40mm grenades frag or concussive, as it is now you can only reload 40mm flechette and buckshot which completely defeats the purpose of using a grenade launcher.

**Comment by Leland** [comment]
How good of a weapon is it? Is there a reason it's so insanely rare?

**Comment by Aranzada** [comment]
It's very good for fuel efficiency: 
Regular flamethrower consumes 100 units of gasoline and at best it can create a 8 tile long line of fire
RM451 consumes 20 units to lit 16 tiles
So it's 10 times more efficient and it can shoot 100 times before having to reload vs the 30 of the regular one.
That said it's not that great because you are playing with fire so you can't use it inside buildings/labs.

**Comment by Leland** [comment]
Sounds like a no-brainer then. Feel free to open a pull request if you're comfortable with code.

**Comment by Aranzada** [comment]
Not that comfortable with how github works, so could you or someone do it for me?

Inside item_groups.json change  ["rm451_flamethrower", 5], to  ["rm451_flamethrower", 25], is my suggestion.

**Comment by Aranzada** [comment]
Nice thank you!

Regarding the 40mm recipes, should I open a new issue?

**Comment by kevingranade** [comment]
> Regarding the 40mm recipes, should I open a new issue?

You can, but briefly, it's working as intended.  If you look into how grenade launchers work, the propellant charges for actual grenade loads are extremely complex, totally different from regular firearm loads.  As such they are treated as uncraftable.
