### ISSUE TITLE
Enable playermade amphibious vehicles

### ISSUE THREAD

**Issue by Maddremor** [CleverRaven/Cataclysm-DDA#20933]
Currently a vehicle is exclusivly landborne or waterborn, and amphibious crafts cannot be built or modded as "is boat" and "is not car" are hardcoded. I suggest that either restrictions on driving be removed and/or that `FLOATS` is divided up into `FLOATS` and (somethng like) `NOLAND`.

I think that @Coolthulhu was the last person working with the related code in #17687?

**Comment by Night-Pryanik** [comment]
Closing because of no discussion in more than a 6 months.

**Comment by mlangsdorf** [comment]
Only took 18 months.
