### ISSUE TITLE
NPC in prision escape

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#20945]
When you have the static NPC option selected you now get a friendly NPC with the prison escape scenario.  This was not the case before so I am unsure what changed with the most recent revisions that is spawning them now. As you can imagine it makes the start in this particular start a lot easier.

**Comment by DangerNoodle** [comment]
Only makes it easier if you neglect adequate starting skills, especially if they start with a firearm. Even then, their main utility is against the security bots.

Being able to theme starting NPCs so that they make sense in a given scenario would be a desirable feature. Ideally their access to firearms should be limited to what the guards would have available.

**Comment by Rod-Serling** [comment]
> When you have the static NPC option selected you now get a friendly NPC with the prison escape scenario. This was not the case before

When I created the prison escape start, I made no exceptions for NPCs, it's all simply JSON. I've seen friendly NPC's spawn with me several times (even during initial testing of the scenario), often though they get stuck in a cell or beaten to death before you encounter them.

**Comment by Treah** [comment]
Lol Rod thats kinda funny I never thought to go looking for them. It just came off odd as I dont remember seeing them.

**Comment by ZenZen2** [comment]
Some time ago i suggested to remove the starting NPC from static NPC. #18319

**Comment by DangerNoodle** [comment]
And doing that is not the right way to handle it.

**Comment by pisskop** [comment]
5 days is enough time to break into jail or be a guard or w.e.

the real problem with the scenerio is that prisoners drop standard loot and youll find shotguns on zeds

**Comment by Treah** [comment]
Since this is related to just spawning static NPC's should I close this issue? Anyone have any objections for me to close it?
