### ISSUE TITLE
Accessibility: Textual Vehicle Direction Indicator

### ISSUE THREAD

**Issue by BlindGuyNW** [CleverRaven/Cataclysm-DDA#20951]
Per discussion in [this Reddit thread](https://www.reddit.com/r/cataclysmdda/comments/686yf0/accessible_vehicles/), some kind of text-based indicator of which direction a vehicle is facing would improve accessibility a lot. Something like "Facing: 200 degrees," somewhere on the sidebar might help. Perhaps it could be a toggle option, much like the way gun targeting percentages are displayed.

**Comment by ZChris13** [comment]
Vehicles have directional facing indicators in console while you're using them

**Comment by Treah** [comment]
I like this idea sometimes its hard to tell which way a car is facing unless your very familiar with their layouts. I still get turned around with the bug for example and some of the cars since they don't have obvious back ends.
