### ISSUE TITLE
You can trade a active nail bomb with NPCs

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#20966]
It looks like the nail bomb does not have a separate json entry for the active version with a trader avoid flag or has it applied automatically in item_factory.cpp.

**Comment by Leland** [comment]
Like @Cyrano7 mentioned, the way we prevent a Shady Sands Shuffle is by adding a `TRADER_AVOID` flag to the active form of grenades. Basically, grenades "transform" into new items when activated, which have that avoid flag.

However, @mugling, in #17425, added an example of a simplified grenade that didn't need that transformation: the nailbomb. You can see that here: 96717d6e95bdf919a976a300ffa7bb9d5da57342. That simplified version never got the flag added to it. We need to either:

1. Revert that simplified grenade
2. Figure out a way to add a flag to a simplified grenade when activated

**Comment by kevingranade** [comment]
3. Disallow the passive form of that grenade.

But, I think 2 is the most promising, we might be able to have an, "avoid
when active" flag that does the right thing.
