### ISSUE TITLE
Dielectric Capacitance System CBM – game shows "You were hurt!" when hit with electricity despite not taking damage

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#20963]

**Comment by Zireael07** [comment]
Uh, I suggest shortening the title?

"Dialectric Capacitance System CBM message bug"

And then provide the details below.

**Comment by Night-Pryanik** [comment]
Hmm, can't confirm on 0.C-6421, Windows XP SP3 x86, curses.
![111](https://cloud.githubusercontent.com/assets/11132525/25780903/136bfe96-3339-11e7-9ae1-8398497fe1b4.PNG)

**Comment by Zilenan91** [comment]
Oh shoot sorry left it out, this message only shows when doing stuff like aiming

**Comment by spacenookie** [comment]
could you provide exact text in the error message? I don't see a message "You Are Hurt" in the source to the current experimental

**Comment by spacenookie** [comment]
there is "You were hurt!" in player::on_hurt, asks you to cancel activity if you were attacked by something other than a monster

**Comment by 1skandar** [comment]
Ah, I bet that's it. Getting shocked probably still prompts you to stop aiming even though it does nothing. A bug, I guess, but fairly harmless *if* your aim isn't actually affected.

**Comment by Night-Pryanik** [comment]
That's quite inconvenient when reloading firearms, for example, - you have to say "No" multiple times in order to successfully reload.
