### ISSUE TITLE
Fire immunity inconstistency?

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#20973]
`player::is_immune_damage()`

```
...
case DT_HEAT:
            return has_trait( "M_SKIN2" ); 
...
```

but

`player::immune_to()`
```
if( dam.type == DT_HEAT ) {
        return false; // No one is immune to fire 
```

Which one is correct?

**Comment by Coolthulhu** [comment]
Sounds like one is for "UI" immunity and other for actual damage immunity.
Still, the latter should probably be removed and just reimplemented in UI. Player is immune to fire, it's only clothing that burns.

**Comment by Leland** [comment]
@Night-Pryanik you want this kept open? Might also be a good question for the forum.

**Comment by Night-Pryanik** [comment]
Nah, this isn't a bug or something, so closing.
