### ISSUE TITLE
Reptile eggs are far too rare

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#20977]
They're far too uncommon in bushes to make lizard mutation not a several-season effort. After two full days (minus nights) of doing nothing but looking through bushes I found three reptile eggs, all in one singular bush. They should either be found more commonly or spawn in other places such as grocery stores like bird eggs do.

**Comment by Solusphere** [comment]
Which season were you trying it in? You can only find eggs through foraging in spring, or very rarely in summer.

**Comment by Zilenan91** [comment]
Spring, I made sure it was the right season

**Comment by ZenZen2** [comment]
I agree, they are to rare.

**Comment by Mecares** [comment]
Maybe add a chance to drop them when smashing cloning vats? Dinosaur cloning scientists seem more plausible than reptile eggs selling grocery stores.

**Comment by Zilenan91** [comment]
I don't think I've ever seen anything drop from smashing a cloning vat come to think of it.

**Comment by Solusphere** [comment]
So I did a bit of foraging in my current game, and honestly I suspect you might just have insufficient survival skill to effectively forage for reptile eggs. Here's what I found in a little over 3 ingame hours of foraging during early spring. My survival skill is 8.

![spring foraging](https://cloud.githubusercontent.com/assets/19789267/25884616/31734a80-3586-11e7-877b-b76fc6c5f607.png)

That said, having some sources of eggs outside of spring/summer would definitely be welcome.

**Comment by Zilenan91** [comment]
That's very strange. I had 10 survival skill and searched for several days in-game and found almost no reptile eggs.

In the past when I've have similarly high survival skill I haven't found nearly that many reptile eggs before (though about that number of wild vegetables) and that makes me wonder if I've just had consistently bad luck for real life months or if a mod is doing something weird. I'm going to go with bad luck personally, but still think that there should be some other way of getting reptile eggs or lizard mutations.

**Comment by Solusphere** [comment]
Hmm, not sure then. I found another four reptile eggs just checking the bushes on the way back to my car. If I am just lucky, it's pretty consistent.

**Comment by ituluwituluwzev** [comment]
Perception helps foraging. 14 is  superhumanly perceptive.

**Comment by kevingranade** [comment]
The rarity thing seems iffy, but it regardless of that, I'd be fine with
reptile eggs (or any other mutagen ingredients) spawning in various lab
locations.

**Comment by Fourtyto** [comment]
I heard having too much survival skill lowers the chances of finding certain objects. Not sure if applicable here.

**Comment by Treah** [comment]
I also have found quite a bit of reptile eggs when foraging in the wilderness. This was always early spring however.

**Comment by Leland** [comment]
Closing due to lack of recent discussion. Feel free to ping me here to reopen if there's interest in continued discussion/development.
