### ISSUE TITLE
Classic Roguelike Classes - Monk crash

### ISSUE THREAD

**Issue by Graywolfe813** [CleverRaven/Cataclysm-DDA#20978]
OS: Android, Linux
Tested against 0.C-22236- 867fcd335463ab185f07e8974558bb5d16268f4f

This one came in from an Android user. Highlighting Monk during character creation causes the game to crash. May be specific to ARM, I have no means to test on x86.

**Comment by ifreund** [comment]
Can confirm on current master.

macOS
x86_64-apple-darwin16
crashed when compiled with both gcc and clang
