### ISSUE TITLE
Skill reward from quests - inconvinient

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#20970]
If I am doing quests for NPCs that are not a party member, and I want a skill reward, there is no convenient way to do that unless I happen to find the NPC in a very safe location... otherwise, I am likely to get smashed to bits by wandering mobs.

Also, by the time I am done learning, the NPC can be a mile away, making it hard to then invite him to my group,

Basically, a way of deferring the reward while still improving my status with the NPC seems like a good solution.

**Comment by pisskop** [comment]
additionally, the skill might be worthless, as in you might get smg_10 or you might have to settle for bartering_2.

there is no way outside of debugging to know what skills they can or will teach

**Comment by angoddu** [comment]
I hate it when I've finished a quest and I then need to chase down the NPC just to finish the quest.
