### ISSUE TITLE
Unable to pour water into sealed stomach

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#20974]
You are unable to pour water into a sealed stomach. However pouring other liquids into them seams to work just fine. I tried moving contents from another container ( clean water ) into a stomach and not getting the option to move it to the stomach. Also unable to from world source.  However when I tried with Vodka it gave me the option to move it to the sealed stomach when choosing container.

**Comment by Leland** [comment]
Merging with #20799
