### ISSUE TITLE
Car exteriors not recognized by Parkour Expert

### ISSUE THREAD

**Issue by Dalenacio** [CleverRaven/Cataclysm-DDA#20981]
Since open windows are recognized, I assume this is just a small oversight.

While we're on the topic of Parkour Master, it would be nice if it could be used to vault over cars easier, maybe only over the exterior.

**Comment by kevingranade** [comment]
Hah, yea both of those (windowfeame and car exteriors) are legit, though
idk if we can detect the car thing.

**Comment by Night-Pryanik** [comment]
Tested it right now, Parkour Expert actually do reduce move cost. 

Without PE.
![123](https://cloud.githubusercontent.com/assets/11132525/25943506/c0cfeba8-3648-11e7-939a-ee43054c0cb7.PNG)
With PE.
![234](https://cloud.githubusercontent.com/assets/11132525/25943515/c515133c-3648-11e7-8bd3-fb75dc5710d8.PNG)

**Comment by Toothspit** [comment]
| Terrain type | Move cost |
| --------------- | ------------- |
| t_window_no_curtains_open | 4 |
| t_window_open | 4 |
| t_window_empty | 8 |
| t_window_frame | 8 |

Parkour Expert is working correctly given these probably-incorrect move costs, at least.

**Comment by Leland** [comment]
Updated the title of the issue, as open windows appear to be functioning normally.
