### ISSUE TITLE
Zombie soldier cannot walk over the sink

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#20982]
...instead, he regularly picks through the doorframe. Save file: http://dump.bitcheese.net/files/rerumop/save.zip/preview
Just stay and wait a bit.
Is it a bug? Other zombies were able to get over the sink in the past.

**Comment by DangerNoodle** [comment]
Most likely due to pathing code, zombie soldiers likely use one of the flags to make them find paths to some extent due to their being implied to be more intelligent than common undead.

**Comment by Leland** [comment]
Haven't checked the savefile yet, but perhaps try debugging yourself into a 1 tile width corridor with a sink separating you from the zombie. Would prove definitively if they can path through sinks.

**Comment by DangerNoodle** [comment]
That would leave the only valid path being through sinks, which would confirm my suspicion that this is a path finding issue.

**Comment by Toothspit** [comment]
Can't confirm. Just made a maze of sinks, zoldier walked right over them instead of using the snake-path.

[sink_maze.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/999078/sink_maze.zip)

**Comment by Leland** [comment]
Closing per above. Was likewise unable to confirm – probably just a minor edgecase. @tsulh of course do let me know if you'd like this kept open.
