### ISSUE TITLE
Pistol autofire mechanism is broken once more

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#20980]
Windows curses 0.C-22236-g867fcd3354

Similar bug to #19492 : When the player switches to the new mode, the gunmod name appears next to (0/0).

**Comment by BorkBorkGoesTheCode** [comment]
No debug message appeared.

**Comment by kevingranade** [comment]
Debug message appears if you attempt to fire the weapon when it's displaying the gunmod name.

Frankly a generic autofire mechanism that works on any pistol is looney, I would accept removing the mod as an acceptable fix for 0.D.
