### ISSUE TITLE
Tailoring wont use thread loaded in needle. 

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#20983]
If a recipe requires thread then the thread has to be in your inventory or on the ground to register as having the requirements. If its loaded into a needle then it becomes unseen by the recipe and you are barred from making it. This was not the case in previous versions and makes no sense that it would become unusable just cause its wrapped around the needle.

**Comment by ituluwituluwzev** [comment]
It's intended and WIP. issue#20358 pull request#20569

**Comment by DangerNoodle** [comment]
Incomplete implementation, which is one reason I was concerned about the pull request that changed recipes.

**Comment by Treah** [comment]
By intended do you mean its supposed to be this way or that its only this way cause things are changed. Cause intended by its supposed to be this way is all kinds of stupid.

**Comment by DangerNoodle** [comment]
> By intended do you mean its supposed to be this way or that its only this way cause things are changed. Cause intended by its supposed to be this way is all kinds of stupid.

It is intended that crafting uses thread in inventory now. What is not intended was for https://github.com/CleverRaven/Cataclysm-DDA/pull/20569 to stall due to code difficulties.

**Comment by ZenZen2** [comment]
As @DangerNoodle said it is intended and not a bug.

**Comment by DangerNoodle** [comment]
Regardless, @ZhilkinSerg should resume work on the pull request in a timely manner, if they are able to.

**Comment by Leland** [comment]
It's been a month and a half since they made a commit – someone may want to just fork the PR and submit it themselves.

**Comment by DangerNoodle** [comment]
I will look into their changes and attempt it myself later on, if I can. But if anyone wishes to as well, please do so.

**Comment by DangerNoodle** [comment]
I am seeing a problem with this code. It appears that they set it to query player every repair tick to work around other bugs, but this is an utterly terrible practice.

Any suggestions, @Leland?

**Comment by Leland** [comment]
@DangerNoodle I'll try to take a look tonight – I may have to wait till the weekend to work on it. Good lord though, that would be so annoying.

**Comment by DangerNoodle** [comment]
My objective would be for it to query for thread only after selecting duration of repair, and automatically query when the player depletes the type of thread they are currently using, but I would have difficulty implementing it if there are more severe issues occurring.

**Comment by Treah** [comment]
Well you cant use thread in the inventory to repair or reinforce items so its just confusing for the player now as they need to carry thread in inventory for recipes and also thread loaded in the needle to do repairs. However having thread in the needle prevents its use in recipes causing confusion. I assume the PR is supposed to normalize this from this discussion and if that is the case I would agree this issue is closed. However closing it without the merge makes it seam as if the issue is not present or has been resolved, and it is not from a game play perspective no matter where the code is in development.

**Comment by DangerNoodle** [comment]
I am having no progress so far with figuring this out.

**Comment by ZenZen2** [comment]
@Treah i think you are right, i am sorry for closing this to early.
