### ISSUE TITLE
'Curry' vs 'curry with meat' nutrition

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#20998]
Curry with meat recepie has all the curry components + 1 meat chunk. Curry gives 40x2 nutrition, while curry with meat gives 45x2 nutrition. Seems wrong that so much meat is wasted. I'd suggest to change the nutrition values somehow, but I don't have enough expertise to suggest a good option.

**Comment by Night-Pryanik** [comment]
Cooked meat is 28 nutrition, round to 30. 
I'd lower curry nutrition to 35x2=70 and raise curry with meat to 50x2=100.

**Comment by Xpyder** [comment]
sounds reasonable to me

**Comment by Leland** [comment]
@Night-Pryanik you should open a PR, those changes make sense
