### ISSUE TITLE
rm121aux unuseable

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#20999]
It can not be reloaded when attached to m4a1. Game only shows option to reload the main weapon, not the underbarrel shotgun. Possibly due to it being a magazine fed underbarrel weapon on a magazine fed main weapon.

simply changing it to RELOAD_ONE weapon fixes it, but there might be balance issues.

**Comment by AMurkin** [comment]
You need to wield it and hit F to 'Toggle attack mode of Wielded item'.

**Comment by aierce** [comment]
I am actually very familiar with the game and know how to reload under-barrel weapons. Toggling attack mode to the underbarrel weapon doesn't help.

**Comment by AMurkin** [comment]
Yeah, i've edited my comment.
It's possible to unload magazine loaded in attached shotgun, reload it, and load it back to shotgun, but..
Confirm bug when not full magazine loaded in attached shotgun.

**Comment by BorkBorkGoesTheCode** [comment]
A (---) appears next to any weapon name in the wielded weapon screen when wielding an M4 with RM121 auxiliary shotgun
