### ISSUE TITLE
Electric fire starter can't start oil lamp

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#21005]
You can't light an oil lamp while holding an electric fire starter, without lighting something else first.

**Comment by Leland** [comment]
Oil lamps don't require a fire source to be lit – they're <kbd>a</kbd>ctivated.

**Comment by Leland** [comment]
Spoke too soon! You do need a fire source. Can confirm this.

**Comment by Leland** [comment]
Oh my god you guys, we just have a giant if/else set for a list of things that can produce fire.
https://github.com/CleverRaven/Cataclysm-DDA/blob/54f5d76248947fe672c9f614b0637be91ed007b6/src/player.cpp#L6651-L6702

So, hotfix would be to just add in `crude_firestarter` to that list. But we have a whole bunch of flags now that we should be able to use to check – I'll see what I can do.

**Comment by DangerNoodle** [comment]
I was about to say, were you thinking of oil lamp cookers?

**Comment by Xpyder** [comment]
@DangerNoodle  Nope, I mean an actual oil lamp (the thing you probably just immediately use as a part to make a cooker)

**Comment by DangerNoodle** [comment]
I was asking @Leland that, actually.

**Comment by Treah** [comment]
I don't think you wanna use add crude_firestarter to that as that would include the firedrills and camp fire drills which do not make an open flame and would not be practical for lighting a oil lamp with.

**Comment by Xpyder** [comment]
While I could make a case for using the the ember you get from a fire drill being able to start an oil lamp, I think someone should double check the code used to check for cauterizing wounds and make sure it doesn't use "player::has_fire", unless we want the electric firestarter to count as enough heat to cauterize

**Comment by Treah** [comment]
@Xpyder  From what I gather in the code it only searches for things with flame. below is an excerpt of code. 
This is in iuse_actor.cpp
`1422 void cauterize_actor::load( JsonObject &obj )
1423 {
1424     assign( obj, "cost", cost );
1425     assign( obj, "flame", flame );
1426 }
`

**Comment by ZhilkinSerg** [comment]
`ref_lighter_on` = `refillable lighter (lit)` does not provide fire for cigarettes. You can check this in LUA console by this command:

````LUA
game.add_msg(tostring(player:has_charges("fire",1)))
````

**Comment by pisskop** [comment]
custom firestarters with reasonable movecosts also cannot activate items that require fire.
