### ISSUE TITLE
Auto lettering duplicating assignments

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#21003]
In this case 3 are assigned to "h"
 - long underwear bottom
 - Karate gi
 - 2-by-arm guards

This has happened other times, but not sure how to reliably reproduce

![image](https://cloud.githubusercontent.com/assets/12039454/26013872/1213d06c-370f-11e7-9257-a5b4aecbc43f.png)

Build: 0.c-22236-g867fcd3354
build date: 2017-05-09

**Comment by Qrox** [comment]
I can't seem to reproduce this, but this might be related to one of my PRs somedays ago. What happens if you drop these three items and pick them up?

**Comment by Xpyder** [comment]
Not sure, I already moved on from them, but it's been something that crops up from time to time that we've had trouble reproducing reliably.  I'll post again if I find a way to reproduce or locate anything relevant

**Comment by Xpyder** [comment]
Happened again, notice all the "b" items I'm wearing.  I tried dropping and putting them back on using the advanced inventory menu, but the lettering preserves 

But if I drop them and pick them back up into inventory using the "," menu the lettering fixes

![image](https://cloud.githubusercontent.com/assets/12039454/26260160/13fb5752-3c81-11e7-97f4-de11f03a138a.png)
Build: 0.c-22236-g867fcd3354
build date: 2017-05-09

**Comment by Qrox** [comment]
Related to #13368 perhaps? I will look into this when I have time.
