### ISSUE TITLE
Lit oil lamp doesn't count as fire source

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#21004]
Using a rock charcoal kiln
says I don't have a fire source
I'm carrying a filled electric lighter and a lit oil lamp, both of which should count
(One could argue the lighter should only count with tinder, but our fire isn't that advanced yet)

![image](https://cloud.githubusercontent.com/assets/12039454/26017348/f42c2c2a-371d-11e7-885f-151a4912ad98.png)

Build: 0.c-22236-g867fcd3354
build date: 2017-05-09

**Comment by Leland** [comment]
`oil_lamp_on` is missing a `FIRE` flag.

https://github.com/CleverRaven/Cataclysm-DDA/blob/dfe12f4099c67babaf42336e5421683900a36fca/data/json/items/tools.json#L5151
