### ISSUE TITLE
Ammonia using old crafting tools

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#21010]
Ammonia still explicitly requires a chemistry set rather than a hotplate and chemical making 2

There might be other chemicals with the legacy setup also

**Comment by Xpyder** [comment]
Also found these 
Acid water (should be chemical 1 probably)
Bleach

Also this should probably require chemical making 1
zombie pheromone

**Comment by DangerNoodle** [comment]
Legacy setup is retained for recipes that would (in reality) require electrolysis. Unless you are suggesting that fire can be used to separate hydrogen from water?

Recipes that use explicit charges from chemistry sets for this reason need to have comments set to explain why they retain the legacy tool usage.

**Comment by Xpyder** [comment]
Interesting, that's fine with me.

Though I don't see why electrolysis wouldn't just be rolled into a chemical making 3 with notes that anything with that tag needs to utilize electricity?
