### ISSUE TITLE
Ranch: Crop Overseer dialog tree broken

### ISSUE THREAD

**Issue by Lord-Helmchen** [CleverRaven/Cataclysm-DDA#21019]
0.C-22249
When asking the Crop Overseer on the Ranch "I want to invest in agriculture", it opens the Foreman's Caravan menu instead.

**Comment by Lord-Helmchen** [comment]
just saw this partially duplicates #20862 ,sorry. At least it's a confirmation.

**Comment by Leland** [comment]
@Lord-Helmchen if you could provide a savefile or screenshots in that thread it would be very appreciated!
