### ISSUE TITLE
Persuading an NPC to train you breaks their active mission

### ISSUE THREAD

**Issue by RWJMurphy** [CleverRaven/Cataclysm-DDA#21027]
If you have an active mission with an NPC, and convince them to teach you something, it breaks the active mission. It still shows up in your Active Missions, but the NPC no longer asks about it (so you can't complete it), and will give you the next mission in the line, if any.

OS: OS X 10.11.3
Tiles: Yes
Version: `0.C-22337-g54e8448`
Git Revision: `54e8448fc86cf71a8f4e56d40c6853b10debbea6`
Mods:
* `dda`

Steps to reproduce:
* Talk to NPC, take job
* Convince NPC to come with you
* Convince NPC to teach you something
* Talk to NPC again

Expected Results:
* NPC asks about mission
* Completing the mission allows you to claim a reward from the NPC

Actual Results:
* Normal NPC talk screen is shown
* Unable to turn in completed mission for reward
* Asking about jobs gives you the next mission in the line, if any

**Comment by Taberone** [comment]
Can confirm. Had this happen earlier when I had a NPC ask me to find a corporate accounting ledger during the freaking apocalypse, and then I asked him to train me. After talking to him again, he skipped over to wanting me to break into the bank, which was the next step of the questline.

**Comment by RWJMurphy** [comment]
It looks like both "training as mission reward" and "training by persuasion" use the same `topic` of `"TALK_TRAIN"` in `npctalk.cpp`. [NPC friend persuasion](https://github.com/CleverRaven/Cataclysm-DDA/blob/54e8448fc86cf71a8f4e56d40c6853b10debbea6/src/npctalk.cpp#L2229-L2235):

```c++
                RESPONSE(_("Can you teach me anything?"));
                int commitment = 3 * p->op_of_u.trust + 1 * p->op_of_u.value -
                                 3 * p->op_of_u.anger;
                TRIAL(TALK_TRIAL_PERSUADE, commitment * 2);
                    SUCCESS("TALK_TRAIN");
                    FAILURE("TALK_DENY_PERSONAL");
                        FAILURE_ACTION(&talk_function::deny_train);
```

[Mission reward](https://github.com/CleverRaven/Cataclysm-DDA/blob/54e8448fc86cf71a8f4e56d40c6853b10debbea6/src/npctalk.cpp#L1595-L1597):

```c++
        if( !p->skills_offered_to(g->u).empty() || !p->styles_offered_to(g->u).empty() ) {
            RESPONSE(_("Maybe you can teach me something as payment."));
                SUCCESS("TALK_TRAIN");
```

`"TALK_TRAIN"` leads to `"TALK_TRAIN_START"`, which calls `talk_function::start_training`.

The mission clearing happens when [`start_training` unconditionally calls `talk_function::clear_mission` on `p.chatbin.mission_selected`](https://github.com/CleverRaven/Cataclysm-DDA/blob/54e8448fc86cf71a8f4e56d40c6853b10debbea6/src/npctalk.cpp#L3152-L3154).

**Comment by Lazasar** [comment]
yeah, I logged this one as well: https://github.com/CleverRaven/Cataclysm-DDA/issues/20548
