### ISSUE TITLE
Mutagen Addiction should happen to everyone

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#21023]
https://github.com/CleverRaven/Cataclysm-DDA/blob/078b9ef217cc7fdb6f26b295e089c0435c09c5ae/data/json/items/comestibles/mutagen.json

Mutagen has an addiction potential but no type, so addiction never occurs.

**Comment by Leland** [comment]
Looks like the mutagens in that JSON file copy from `mutagen`, [present here](https://github.com/CleverRaven/Cataclysm-DDA/blob/078b9ef217cc7fdb6f26b295e089c0435c09c5ae/data/json/items/comestibles/mutagen.json#L218-L233), which does have an `addiction_type`.

**Comment by pisskop** [comment]
Aye.  Youre correct.

Perhaps the more succinct title and issue is that I think mutagen addiction should be a natural side effect of injecting mutagen or eating fetuses instead of locked behind a trait that is fairly rare.

**Comment by kevingranade** [comment]
Did I mention that copy-from was a bad idea? Pretty sure I did, and it still is.

@pisskop, this needs a much better description.  It needs more precision about the problem, and some support for why it needs to change.

**Comment by pisskop** [comment]
Mutagen is viewed as something to be purified away in the game.
Players that seek it do so with limited risk of addiction unless they choose one of the two existing addictive traits.
Much like the traits to cause mutagen or marloss revulsion, the addiction traits are so rare that I personally have never had them.  finding several mutagen in a lab with purifier means, to me, that its time to take some mutation before I go to sleep, and purify it away should it be negative.

The game specifies this addiction, but how many people have actually experienced this?  We already have an addictive trait, so making a trait to increase the addictive properties of substances is possible.

Making the mutation process addictive justifies having mutates in the wasteland beyond 'radiation, im a freak' and allows for the addiction to exist within the games liberal drug structure.

Assuming that one day we will make the random wandering custom NPCs with mutations work, and flesh out npc interactions, this paves the way to trading mutagen, being robbed for mutagen, hiring people to make it, or any number of other dialogues possible.

The trait is needlessly restrictive; it being a thrill and chemically habit forming to everyone is not only a fairly common trope, but quite easy to imagine since you are injecting a physically exhausting chemical into your body.

Although addiction is somewhat safe to ignore as it stands right now, its addition to the myriad of common addictions adds some role play value too.

**Comment by MxTurner** [comment]
I have had mutagen addiction from pounding Medical Mutagen.
