### ISSUE TITLE
Cattails are too good

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#21026]
You get 400 food units worth of flatbread from one cattail (that are omnipresent in swamps) using easily obtainable tools.

**Comment by Treah** [comment]
They are also non-renewable and cannot be grown. They also require you to have some cooking skill along with survival to even be able to convert them into flour and then flatbread.  This is a non issue IMOO

**Comment by pisskop** [comment]
400 flour?
thats a lot.

doesnt flour come in a small box of (28)?

**Comment by Chezzo** [comment]
While I don't think cattails need a nerf, (google "supermarket of swamps"), I think the starch recipe is a bit out of touch with reality. How do you turn starch into flour? 

You can cut your flour with starch, and you can cut your flour with cattail pollen, but you can't straight up make flour with those. 

I could see it making more sense if starch was removed from the recipe for flour, and a new recipe was made with: 

`>` 1x wheat OR 1x buckwheat OR 1x barley OR 1x cooked acorn meal OR 1x oats OR 3x dried rice
AND
> 1x starch OR 1x cattail rhizome

(One cool trick with cattails is, if you ever go to a swamp and need fresh water, cattails only grow in fresh water.)

**Comment by Treah** [comment]
You can make flour from cattails acording to the USDA PDF. 
https://www.plants.usda.gov/plantguide/pdf/cs_tyla.pdf

**Comment by Zilenan91** [comment]
Swamps are insane for food in general https://i.redd.it/b8r8m6hlezvy.png https://cdn.discordapp.com/attachments/304019679457050645/310589961160228874/Untitled54.PNG

Also you can make the cattails into starch then the starch into flour, usually you can get quite a bit very quickly but this also does take quite a bit of time. It's fine imo. Same for the monster spawns in them, they make them quite hectic and interesting.

**Comment by ZenZen2** [comment]
i agree with @Zilenan91, the monsters usualy give more than enough food. And to make 10 flour you have to invest a lot of time.

**Comment by l29ah** [comment]
Meat and meat-based products either spoil readily or (aren't especially nutritious and require much time too).

**Comment by Tharn** [comment]
Cattails are good, but they're also gone quick if you rely on them to get through a winter (but I do play with 60 day winters.. so). Unless you live between several swamps, you still have to move to make ends meet. As with the other methods of food gathering.

**Comment by pisskop** [comment]
Food is incredibly easy to produce.  An argument about their non-renewability is offset by the sheer number of swamps in the game.  They are in fact renewable via mapgenning.

What this should be a bout is establishing just how big 'a cattails' is and making its yield fair in comparison to the difficulty of producing it.

**Comment by Leland** [comment]
No movement in nearing a full year – closing. If there's still an interest in discussion, ping me to reopen!
