### ISSUE TITLE
Crafting clean water from Wooden Keg uses charges but doesn't give water

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#21033]
Testing steps: 
build wooden keg [furniture], load it with some [dirty] water (standing tank untested)
give yourself a a container, load it with some [dirty] water and hold it in inventory
spawn a coffee maker, and load it with batteries
craft 1 clean water  from water (nearby) [this is from the keg]
notice you don't get anything afterward, though charges are used from the coffee maker
also notice it didn't consume any of the water from the keg
craft 1 clean water  from water [this is from the water on your person]
notice you get the prompt for what to do with your new clean water

Build: 0.C-22236-g867fcd3354
Build date: 2017-05-09

**Comment by Leland** [comment]
Duplicate of #19483

**Comment by Xpyder** [comment]
I recall a similar bug, but that was caused by an overflow when too many available charges were nearby (specifically when you had an infinite water source and also a container with water on the ground)

**Comment by Leland** [comment]
@Xpyder ha, may have closed too early – is #19483 a separate issue? If so, I'll reopen.

**Comment by Xpyder** [comment]
nope, same issue.

I thought that was fixed, didn't realize that other ticket was still open (I did search) and thought I was conflating the memories.

Thanks for finding it, I'll add in that it does indeed consume charges
