### ISSUE TITLE
Crash on world load with Blaze mod enabled

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#21039]
Something in the last few experimentals has broken the vehicle parts mod to the point the game crashes after character creation if it is enabled.

**Comment by BorkBorkGoesTheCode** [comment]
Cannot confirm crash, but debug message appears using windows console.

**Comment by 1skandar** [comment]
Yeah, I did a lab start and I got the warning. Trying to actually start the game just crashed.

**Comment by DangerNoodle** [comment]
Warnings for type bfeedfuel: must define at least one ammo type.

Is this the debug message you are referring to?

**Comment by 1skandar** [comment]
That's the one.
