### ISSUE TITLE
Welding rig is magic

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#21048]
You make your grenade extra sturdy.
You make your cash card extra sturdy.
You make your plastic bag with crack extra sturdy.
You make your zombie pheromone extra sturdy.

**Comment by Night-Pryanik** [comment]
Limitations of game engine, what else to say.

**Comment by Xpyder** [comment]
Grenade, Cash Card, and Plastic Bag all make sense (for example you could reinforce the metal shell of a grenade to reduce the chance a stray bullet or acid spray would compromise it's abililty to detonate, or reinforce the straps and bottom of a bag to make it more sturdy)

Zombie Pheromone not so much.  can someone check the material type flags on the pheromone?

**Comment by Toothspit** [comment]
> someone

Reporting for duty. `"material": [ "flesh", "plastic" ],`. Recipe is [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/recipes/recipe_medsandchemicals.json#L1828) and doesn't have plastics, but I have no clue what the finished product even *looks like*, much less whether it should be plastic.

**Comment by Xpyder** [comment]
It sounds like a "perfume", presumably in a bottle of some kind, but baring a larger rework of that item into a liquid that has to be stored in a container plastic should probably be removed from it to prevent weirdness like being able to reinforce it with soldering irons (and by extension welding rigs)

**Comment by Night-Pryanik** [comment]
I always thought that it looks like a lump of intestines, similar to the one that Gordon Freeman squeezed in HL2.

**Comment by Xpyder** [comment]
>This is some kind of disgusting ball of rotting meat

You sir, appear to be correct.  Plastic should be removed from material unless anyone else objects

**Comment by Solusphere** [comment]
I'll leave this here for reference purposes, seeing as it's very likely what this is based off:

http://half-life.wikia.com/wiki/Pheropods

**Comment by AlecWhite** [comment]
I always thought it would be like the ones in l4d https://i.ytimg.com/vi/-F5JJ98FuG4/maxresdefault.jpg

**Comment by Zilenan91** [comment]
If it's like Boomer Bile from L4D it should be listed as something like "Canister of Zombie Pheromones"

**Comment by Xpyder** [comment]
> This is some kind of disgusting ball of rotting meat

This is a direct quote from the in game item.  I think it's pretty clear @Night-Pryanik has it right

**Comment by pisskop** [comment]
the issue _is_ that the game lacks a synthetic, not-plastic material.

bleach and ammonia fall into this plastic category, and making them nylon would be no better.

perhaps a new material, hypothetically called unobtainium for now, is the best option.

truthfully, we also lack liquid explosives.  we use 'powder' right now.
