### ISSUE TITLE
Impossible to stop washing stuff on the washboard

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#21047]
I was standing and washing my rucksack on a washing board. A zombie came to me and almost killed me and destroyed my rucksack while i was washing it, and i was unable to stop washing it.

**Comment by Leland** [comment]
Duplicate of #21047 – agreed, this needs to change.

**Comment by l29ah** [comment]
Yay a duplicate of itself!

**Comment by Leland** [comment]
@l29ah ugh, fixed. Haha
