### ISSUE TITLE
Debug messages about harvest and eximine

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#21040]
win tiles as on screenshots and win console with invisible messages
6447 - affected
6446 - not affected

![image](https://cloud.githubusercontent.com/assets/1931904/26150505/4bc93562-3b07-11e7-92bd-3ed513ee65eb.png)
![image](https://cloud.githubusercontent.com/assets/1931904/26150521/5e0c119a-3b07-11e7-98e0-ff1abaa4af93.png)

Is it correct now after #20946?
```
    std::array<harvest_id, SEASONS_PER_YEAR> harvest_by_season = {{
        harvest_id( "null" ), harvest_id( "null" ), harvest_id( "null" ), harvest_id( "null" )
    }};
```
mapdata.h#231

Tested here: #21041

**Comment by Sonins** [comment]
To me, yes. It corrects that problem.
