### ISSUE TITLE
World Gen Menu

### ISSUE THREAD

**Issue by ZeGentzy** [CleverRaven/Cataclysm-DDA#21068]

**Comment by DangerNoodle** [comment]
Elaborate desired changes in description of first post. You have opened several descriptionless issues with exceedingly brief titles, which amount to effectively spamming the issue page with unhelpful issues.

**Comment by Cyrano7** [comment]
@ZeGentzy This issue is completely empty. If you are using this as a placeholder in your project make a note card instead. You can reopen once you have something here. I'm closing for now.
