### ISSUE TITLE
Autopickup Menu And Safemode Menu

### ISSUE THREAD

**Issue by ZeGentzy** [CleverRaven/Cataclysm-DDA#21071]
Will Become:
 - Split Panel (stacked)
    - Text panel (instructions)
    - Split Panel (side-by-side) (bordered)
       - Split Panel (stacked) (scroll able) (binded (a))
           - Multiple text panels
       - Split Panel (stacked) (scroll able) (binded (a))
           - Multiple text panels
       - Split Panel (stacked) (scroll able) (binded (a))
           - Multiple text panels
       - Split Panel (stacked) (scroll able) (binded (a))
           - Multiple text panels
        - Split Panel (stacked) (scroll able) (binded (a)) (if safemode Menu)
           - Multiple text panels (if safemode Menu)

**Comment by DangerNoodle** [comment]
Elaborate desired changes in description of first post. You have opened several descriptionless issues with exceedingly brief titles, which amount to effectively spamming the issue page with unhelpful issues.
