### ISSUE TITLE
Yes/No Querys

### ISSUE THREAD

**Issue by ZeGentzy** [CleverRaven/Cataclysm-DDA#21073]
Should allow custom amount of responses (not just yes/no)

Should become:
 - Split Panel (stacked)
    - Text panel (message)
    - Header Panel (No child, no border) (buttons)

**Comment by DangerNoodle** [comment]
Elaborate desired changes in description of first post. You have opened several descriptionless issues with exceedingly brief titles, which amount to effectively spamming the issue page with unhelpful issues.
