### ISSUE TITLE
Keybinding Menu

### ISSUE THREAD

**Issue by ZeGentzy** [CleverRaven/Cataclysm-DDA#21070]
Will Become:
 - Split Panel (stacked)
    - Text Panel (instructions)
    - Text Panel (modifiable)
    - Split Panel (stacked) (scroll able)
        - Multiple text panels.

**Comment by DangerNoodle** [comment]
Elaborate desired changes in description of first post. You have opened several descriptionless issues with exceedingly brief titles, which amount to effectively spamming the issue page with unhelpful issues.
