### ISSUE TITLE
Bionics Menu

### ISSUE THREAD

**Issue by ZeGentzy** [CleverRaven/Cataclysm-DDA#21072]
Should become:
 - Split Panel (stacked) (bordered)
    - Text Panel (for instructions)
    - Split Panel (Side by side)
       - Tab Panel
         - Split Panel (stacked) (scroll able) (binded (a))
            - Multiple Text Panels
         - Split Panel (stacked) (scroll able) (binded (a))
            - Multiple Text Panels
       - Text Panel (slots used)

**Comment by DangerNoodle** [comment]
Elaborate desired changes in description of first post. You have opened several descriptionless issues with exceedingly brief titles, which amount to effectively spamming the issue page with unhelpful issues.
