### ISSUE TITLE
Colors Menu

### ISSUE THREAD

**Issue by ZeGentzy** [CleverRaven/Cataclysm-DDA#21075]
Color menu should become:
 - Split Panel (stacked) 
    - Text Panel (for instructions)
    - Split Panel (Side by side) 
        - Split Panel (Stacked) (scroll able) (binded (a))
            - Multiple Text Panels (color label)
        - Split Panel (Stacked) (scroll able) (binded (a))
            - Multiple Text Panels (color)
        - Split Panel (Stacked) (bordered) (scroll able) (binded (a))
            - Multiple Text Panels (color invert)

**Comment by DangerNoodle** [comment]
Elaborate desired changes in description of first post. You have opened several descriptionless issues with exceedingly brief titles, which amount to effectively spamming the issue page with unhelpful issues.

**Comment by JohnDvorak** [comment]
These seem to be specifically for a Github project: https://github.com/CleverRaven/Cataclysm-DDA/projects/9

@ZeGentzy just a note in case you didn't know, you can create "notes" that exist within projects without exporting them as tickets in the issue tracker. That way they're not competing with bugs and feature requests. That might be your intention, just letting you know!

Info here: https://help.github.com/articles/adding-notes-to-a-project-board/

**Comment by ZeGentzy** [comment]
I didn't notice the notes until I created them. I'll be closing them all (they don't need to be open, I can just add a fixed issues column.)
