### ISSUE TITLE
Lost Submissive profession starts with two bondage masks

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#21083]
Applies to both male and female.

**Comment by Cyrano7** [comment]
Can't reproduce, male or female, or with different starts.

**Comment by Solusphere** [comment]
Apologies, I thought I'd updated to the latest version, but my launcher had apparently networking issues when checking for versions and I failed to notice. Issue appears to not occur with the actual latest version. Sorry for wasting your time.
