### ISSUE TITLE
Can't draw liquids from non-standard containers without a siphon attempt

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#21086]
If you store something such as bleach or ammonia in a vehicle storage tank you cannot use it for crafting without first siphoning it from the tank.

Encountered it in version 0.c 22223-gdfe12f4099

**Comment by AMurkin** [comment]
Duplicate of #20511

**Comment by EkarusRyndren** [comment]
Whoops... Checked the first one I sent and not for the second, my bad.
