### ISSUE TITLE
Aiming a gun have lost its range check

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#21099]
So now it lets the user to shoot up to 60 squares far. The actual bullets won't fly that far tho. Bisecting it now.

**Comment by l29ah** [comment]
5bde341e512367e6bc3650337c29c59500e94546
@kevingranade why did you do this?

**Comment by 1skandar** [comment]
Worse, loaded firearms have lost the listing of their effective range in their description.

**Comment by kevingranade** [comment]
There was a giant aiming overhaul that broke a lot of the system, as part of that it replaced explicit gun ranges with an odd system for determining range based on dispersion.  When backing that whole mess out in #20941 
At the time it looked like it had actually dismantled the explicit range values, but instead it may have just removed a number of values?

**Comment by DangerNoodle** [comment]
Was the reversion of said overhaul compile tested?
