### ISSUE TITLE
Vehicle mounted funnel collects water slower than a non-vehicle funnel

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#21094]
Just tested this. Put a funnel on a 60l tank sitting on the ground, and installed a funnel over a empty 60l tank on a vehicle. In the same amount of time the tank on the ground accumulated 2.5 liters the vehicle only accumulated 1 liter. Is this intended behavior?

This is a big issue in summer as it highly unlikely that vehicle mounted funnel will get enough rain to actually fill at all, as any amount under 0.25 liter is ignored.

**Comment by Leland** [comment]
Duplicate of #14063, it's an old issue.
