### ISSUE TITLE
Projectiles only miss in one direction

### ISSUE THREAD

**Issue by Toothspit** [CleverRaven/Cataclysm-DDA#21104]
Linux x64 gcc 0.C-22428-gae504cc9a4 https://github.com/CleverRaven/Cataclysm-DDA/commit/ae504cc9a477c2762e7f274f5584eb7f5d631b7a 

When you miss, you always miss to the firer's right side, target's left. [Clip](https://asciinema.org/a/d42nclxmowddmus7a8bzgzwu9) of a minigun missing a skeletal dog 100 times; target is straight north, all misses are E of north (looks like <= pi/12). [Save](https://github.com/CleverRaven/Cataclysm-DDA/files/1024321/miss_save.zip); I'ma dig into ballistics, but figured I'd post an issue in case someone can first-glance this one.

Edit: This one is beyond my abilities. There's [cosines of arctans](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/ballistics.cpp#L216), and I don't even know what that is supposed to look like.

**Comment by AMurkin** [comment]
I think aim.dispersion always greater than 0.
And [line](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/ballistics.cpp#L207)
`rad += std::max( std::min( ARCMIN( aim.dispersion ), DEGREES( 30 ) ), DEGREES( -30 ) );`
equals
`rad += std::min( ARCMIN( aim.dispersion ), DEGREES( 30 ) );`

**Comment by kevingranade** [comment]
Actual dispersion was changed to be a signed value rather than an absolute
value, I backed this out as unhelpful but missed the code that determines
the trajectory of a missed shot.
