### ISSUE TITLE
weird subway tile spawn

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#21116]
All 4 staircases go up, and this doesn't go anywhere.  It's more of a bomb shelter than a subway station

At first I thought it might have been closed off by a cave in, but all the walls are smooth and there's no rubble.

![image](https://cloud.githubusercontent.com/assets/12039454/26459863/bdc0e932-412c-11e7-8962-fd91f94c0b18.png)

**Comment by pisskop** [comment]
Mods?

**Comment by Xpyder** [comment]
I think it's mostly vanilla, but how do I double check after world creation?

**Comment by pisskop** [comment]
Its likely vanilla, but I wanted to make sure it was a problem with the vanilla mapgen rather than my own mod, which specifies subways spawning with an underground terminal and connections.

the difference being that my mod requests a connection for some structures, via json, and the vanilla does not ...

**Comment by Xpyder** [comment]
what's the name of your mod?

**Comment by pisskop** [comment]
pks_rebalancing

**Comment by jtgibson01** [comment]
I've had this issue as well, without PK's Rebalance running.  Using the debug actions to reveal the whole map, I confirmed it was a west end-of-line for a subway system.  There was a three-tile-thick wall separating the "platform" from the "tunnel".

**Comment by angoddu** [comment]
Is it possible to get this subway fix without everything else in pks_rebalancing?

**Comment by Leland** [comment]
Can confirm this is still in as recent as 1faea901ef543bec7c0a116f8b076861067056c6.

<img width="1280" alt="screen shot 2017-08-15 at 8 21 11 pm" src="https://user-images.githubusercontent.com/714017/29342189-5596abe2-81f7-11e7-997d-fb7715fa5ebb.png">

**Comment by ZhilkinSerg** [comment]
Is it reprodicible with updated subway?

**Comment by Cosmitz** [comment]
As of 7153 this is what subways look like when going down, tested with 10 of them:

![image](https://user-images.githubusercontent.com/7086599/36631366-463a7cd0-197f-11e8-91b3-11935416f3e5.png)

**Comment by ZhilkinSerg** [comment]
Just go further down. It is -1 Z-level which contains sewers and basements.

**Comment by Cosmitz** [comment]
Yep, it's fine. Was confirming this bug was solved. :)
