### ISSUE TITLE
Fast Reader trait is applied inconsistently

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#21124]
In the message "A chapter of this book takes N minutes to read." the unmodified number is written while in the reading dialog it's modified (smaller). Say, for 101 Wrestling Moves with Int 8 i see 15 and 12.

**Comment by Night-Pryanik** [comment]
Can you provide a screenshot or two for this issue?

**Comment by laeaton2001** [comment]
Basic issue here is the item description shows the time from the item json (how long it would normally take to read a chapter in good conditions).
However the reading dialog takes into account the players int, traits & location to show how long a given chapter will take to complete at that point in time.
I don't this is an issue really. Maybe we could change the item description to be "A chapter of this book typically takes N minutes to read"?

**Comment by Night-Pryanik** [comment]
> Maybe we could change the item description to be "A chapter of this book typically takes N minutes to read"?

Or just "A chapter of this book takes _up to_ N minutes to read"? 
Btw can actual reading time be larger than the value in json?

**Comment by laeaton2001** [comment]
The reading time can be longer if your int is too low, the lighting isn't good & maybe some other factors I don't know about.

**Comment by Coolthulhu** [comment]
> Maybe we could change the item description to be "A chapter of this book typically takes N minutes to read"?

As long as the player can see the actual time somewhere else.
