### ISSUE TITLE
Debug message add_zombie at creature_tracker

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#21130]
tiles, build 6476, win x86
![spawn](https://cloud.githubusercontent.com/assets/1931904/26524519/9f44d1f4-433d-11e7-9a20-043d30379085.png)
[add_zombie: there's already a monster at](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/creature_tracker.cpp#L71)
Creature_tracker::add(monster&)

I bet it's
[EVENT_ROBOT_ATTACK](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/monattack.cpp#L2678) in bool mattack::photograph(monster *z)
[summon_mon](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/event.cpp#L51) in void event::actualize()
[critter_tracker->add(critter)](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/game.cpp#L6670) in bool game::add_zombie(monster &critter, bool pin_upgrade)

**Comment by Tharn** [comment]
Having the same issue in a new world, started 6470ish. Static & wander spawns are on.

**Comment by Night-Pryanik** [comment]
Is this still an issue?

**Comment by KurzedMetal** [comment]
I got this error too multiples times with multiples Experimental version in the last few weeks while playing 2-3 different characters. I think it being close to an area with lots of zombies helps to reproduce this (I got close to a Mall fill with Zs and got this error twice in 15mins)
