### ISSUE TITLE
Farm not generating

### ISSUE THREAD

**Issue by mouseturd** [CleverRaven/Cataclysm-DDA#21135]
Using the "Out of Town" scenario, with default world gen settings and no mods, I cannot generate a world with the Farm start.

Getting error that the game cannot create a world with a suitable starting location.

Build 6475

Edit: Tried 200 times in a row, no luck

**Comment by Leland** [comment]
Can confirm, although I seem to be able to generate one after about 5-10 tries.

**Comment by DangerNoodle** [comment]
I have been unable to get any of the locations except swamp shacks and campsites to generate. Cabins and farms are both non functional.

**Comment by DangerNoodle** [comment]
Possible solutions:

First, regular cabins could be allowed to spawn in fields rather than only forests. Minimum and maximum city sizes may also be too restrictive.

Second, farms may also be subject to a too restrictive range of city sizes. Both use 4 to 12, when 1 to 20 might be a more usable range.

**Comment by Leland** [comment]
Oddly, I can reliably reproduce each scenario only spawning with the first location in its definition. For [Out of Town](https://github.com/CleverRaven/Cataclysm-DDA/blob/302670f09f479b5434ce9de0d7008044f5d28f9a/data/json/scenarios/scenarios.json#L221), that's the Swamp Shack. Each successful start I've had so far has been at the Swamp Shack. Removing Swamp Shack from that file makes `campground` the first location in the array, and that then becomes the location of every successful start.

Then, I tried out Fled the Riots, whose first location is `s_bookstore`. And, yeah, across 5 starts each were at the bookstore.

**Comment by DangerNoodle** [comment]
I do not think you did this correctly. Try additionally taking campgrounds out of that scenario.

**Comment by DangerNoodle** [comment]
Note that the Ambush scenario, which defaults to cabins, almost never works.

**Comment by Leland** [comment]
@DangerNoodle the list I used to test whether the first item matters or not was a follows:

`"survivalist_farm", "shelter", "cabin_woods", "s_bookstore", "s_grocery", "police", "s_garage", "house", "s_grocery", "s_gun", "s_garage", "pawn", "bank", "mil_surplus", "furniture", "s_library", "s_bookstore", "boarded_house" `

Even with all of those options, I still was unable to generate a starting location.

**Comment by DangerNoodle** [comment]
I am unsure what to make of this. That said, I am currently testing versions of Out of Town with both the survivalist farm as the first entry, and cabin as the first entry.

**Comment by DangerNoodle** [comment]
![generation failure](https://cloud.githubusercontent.com/assets/22048567/26530834/394313e2-43a2-11e7-99f7-681201e9a30e.png)

While this is an older build, this was the very first test with survivalist farms as the first entry.

**Comment by DangerNoodle** [comment]
Test repeated with cabins moved to first entry in scenario, after resetting world again. Same error occurred on first attempt.

While I do not know whether I will have the same results on the most recent build, I do believe that some alterations can make these occurrences less likely.

**Comment by mouseturd** [comment]
Debugging map reveal, moving to several different regions, I can't get a single farm to spawn.

**Comment by DangerNoodle** [comment]
I am sucessfully testing changes that are correcting this, I will have a pull request soon.

**Comment by ZenZen2** [comment]
I can not get Shipwreck to spawn. Default Mods.
changing occurrences to [1, 1] result in endless retrys.

Can someone explain how city_distance is read? LMOE for example has city_distance [20, -1], i dont understand the minus 1 here.

**Comment by DangerNoodle** [comment]
If I recall, minus one is effectively infinite. So it should be read as demanding it stay at least twenty units away from cities, with no restriction on maximum distance from cities.

I will look into getting shipwrecks to spawn, then.

**Comment by DangerNoodle** [comment]
Testing with latest available build, unable to find any instances of shipwrecks so far. This may be due to the location being in water, which restricts shipwrecks to specific areas.

**Comment by ZenZen2** [comment]
thanks

**Comment by DangerNoodle** [comment]
Uncertain if this is due to any possible hard coded probelm with water spawns, or if this is a natural result of water spawns being so restrictive.

**Comment by mouseturd** [comment]
It seems like a lot of oh of town building aren't spawning anymore. Cabins,
lmoe,  shipwrecks, farms off the top of my head

**Comment by mouseturd** [comment]
*out of town

**Comment by DangerNoodle** [comment]
As already noted. I have not yet had an issue with LMOE shelters so far though. But cabins, shipwrecks, and farms have been consistently problematic.

**Comment by notafed** [comment]
I noticed this as well, so I took a look through the **overmap_specials.json** file and noticed a pattern with all of these locations:

Every location with `"locations" : [ "forest" ],"`, such as farms, cabins, bandit camps, campsites, etc, won't spawn on the overmap; however, replacing "forest" with "wilderness" in the json returns them to their proper overmap behavior!

**Comment by Leland** [comment]
@pisskop [once said](https://www.reddit.com/r/cataclysmdda/comments/69qzwd/weekly_questions_thread_may_07_2017/dha84i9/?context=3) this about that issue:

> the issue is beehives are 3x3 forest only tiles, and mapgen doesnt respect the forest req when trying to lay out a map. it places the hive, then checks the forest req. when the hive fails that check the game despawns it and doesnt place a new one

**Comment by notafed** [comment]
And beehives also happen to have the `"locations" : [ "forest" ],` flag, along with "spider pit" and "triffid grove".

**Comment by pisskop** [comment]
@Coolthulhu wanted to revamp mapgen; I think the idea was to solve this

**Comment by DangerNoodle** [comment]
Current pull request should resolve cabins, farms, bee hives, and anthills without needing to overhaul generation code.

Bandit cabins and camps are problematic because they are meant to be concealed from the player. Making them unconcealed will allow placing them in fields, allowing them to spawn more reliably through JSON changes alone.

**Comment by ZenZen2** [comment]
@notafed you are wrong. Campsite is mandatory and it spawns each map without any problems.
I made some tests with the Farm (its wilderness by default). Changed it to forest and made it mandatory. It is 3x3 spawn and it spawned on 3rd map. That is without unlimited map generation.
