### ISSUE TITLE
Migrating building-utility to it's own repo

### ISSUE THREAD

**Issue by Leland** [CleverRaven/Cataclysm-DDA#21148]
The CDDA repo's top-level folder [`utilities`](https://github.com/CleverRaven/Cataclysm-DDA/tree/master/utilities/) contains only one thing: a Python script that helps generate building JSON files.

This is a tool that's seen good use and was utilized as recently as November 2016 by @acidia in https://github.com/CleverRaven/Cataclysm-DDA/pull/19257. However, it also does not necessarily need to be in this repo itself.

What I'm proposing is that the `utilities` folder be deleted, and @kevingranade migrate the `building-utility` folder to a new CleverRaven repository. This separation will allow for development and issue tracking of the tool to happen separately from this main repo, and, of course, de-clutter this repo.

(Plus, perhaps, this separation will bring greater attention to the tool and encourage development and usage of it).

Note that the script was written by @acidia and @wormingdead and could be migrated to a repo under either of them, but both have been inactive for some time, and the code _was_ contributed to this project.

**Comment by kevingranade** [comment]
What's the payoff here? It seems like were going to do a one-time migration and risk losing track of this code for no benefit.
If there were a large number of building-utility issues I could definitely see a benefit, but do we have any of those?
As for visibility, we can add references to the tool in a number of places to let people know about it without moving to another repo.
I'm not hostile to the concept in general, but I'm not seeing the upside.

**Comment by wormingdead** [comment]
Transferring the repo to my account would not work as I am not active on
GitHub at all.

Also, if you follow #19257 to #19572, the tool apparently outputs json
files too large to accept. Is it really productive to use it?

**Comment by kevingranade** [comment]
Thanks for pointing that out, I need to make a note to test and merge that, because mugling was way out of line closing that PR.
