### ISSUE TITLE
Vehicle battery charge balancing?

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#21140]
In real world when you connect several batteries in parallel they will even out the voltage among them, dividing the charge proportional to their capacity. This should be the case for cataclysm, as now i, say, can't neither charge a battery using another battery nor prefer the newly installed battery over an old one to receive energy from generator/solar panel, that is quite troublesome in the early game given the usual lack of energy in the car batteries.

**Comment by Qrox** [comment]
I actually wrote code to do vehicle battery charge balancing some time ago. My thought was that it does not significantly impact the game experience so I did not PR that change. After all, why we do charge balancing in real life is that batteries tend to perform poorly if not properly balanced, which is of course not the case in CDDA.

**Comment by Maddremor** [comment]
Balancing would allow the player to charge an electric vehicle by temporarly inserting a battery and letting it balance out among the preexisting batteries. Perfect for the swappable storage battery.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
