### ISSUE TITLE
Killed zlaves should not be able to attack you after reanimation

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#21149]
Zombies' corpses are dismembered and pacified (no-arms and no-teeth TWD-style?) to prevent them from attacking the player, but after becoming zlaves, being killed and then reanimated they again have fully working arms and teeth.

**Comment by DangerNoodle** [comment]
> and an acidic impossible.

Mouthful of baking soda, I suppose.

Regarding this, this might affect zombies spawned friendly, which is a minor concern outside of the necromancy mod.

**Comment by kevingranade** [comment]
This came up during the addition of zlaves, the rationale is that they undergo a burst of regeneration that is capable of reversing the damage from being dismembered, practice and experimentation can prevent this from happening once, but the process isnt capable of guaranteeing that the adjustments will never be reversed.

**Comment by DangerNoodle** [comment]
I see. Potentially peculiar. However, the methods needed to fix this would also be used for fixing friendly creatures respawning hostile, or would they rely on separate code?

If the former, then applying such code to both cases might be warranted depending on how hard the functions are to separate. If the latter, then implementing similar code for enzlaved undead can be considered separately.
