### ISSUE TITLE
Remove quern or mortar

### ISSUE THREAD

**Issue by Maddremor** [CleverRaven/Cataclysm-DDA#21143]
With the merge of #20937 we now have 3 different tools to grind flour/cormeal/oatmeal. To avoid cluttering the crafting menu, I suggest removing either the quern or the mortar and petsel. They are both stone based, manual, muscle powered tools for grinding, and with the addition of the electric food proccessor, the distinction feels less relevant.

**Comment by Mecares** [comment]
Mortar and pestle are Mod content from the More_survival_tools mod. Mods adding redundant content does not seem like a problem to me as long the core game remains relatively streamlined.

**Comment by Maddremor** [comment]
Huh, TIL. Closing this issue then.
