### ISSUE TITLE
Impassable vehicle door

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#21156]
The door to the north of me is the culprit. I can see through it, but can't actually go through it. The only thing there is a curtain (damaged) a door and the frame. Removing and remounting the door fixed it.

![image](https://cloud.githubusercontent.com/assets/4127779/26620360/88c70904-45b0-11e7-9654-27123b767a06.png)

**Comment by ChronicDankDisasterAlgorithm** [comment]
I had this problem as well, a few days back. Removing and remounting also fixed it for me.

**Comment by Leland** [comment]
To anyone encountering this issue: a savefile exhibiting this behavior would be much appreciated.

**Comment by sxmichaels** [comment]
This bug has remained unconfirmed for about half a year; should we close it? @1skandar or @ChronicDankDisasterAlgorithm, do you still have save files to confirm?

**Comment by Leland** [comment]
Closing due to lack of confirmation.

If encountered again on a recent version, ping me here to reopen. And please (please) make a copy of your save file so we can test!
