### ISSUE TITLE
Vegetable aspic doesn't require bones

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#21152]
While irl it requires some source of gelatin that can't be obtained from vegetables.

**Comment by Leland** [comment]
From the [recipe JSON](https://github.com/CleverRaven/Cataclysm-DDA/blob/7d39c06901b8fc5457bbe27d430a2975dc1db26e/data/json/recipes/recipe_food.json#L2450):

> Gelatin from bones is just boiling them long enough.  Gelatin from pectin is harder.

**Comment by l29ah** [comment]
Wow, didn't notice this comment; makes sense, thanks. OTOH, it seems like a lot more complex operation requiring several tools and consumables: https://en.wikipedia.org/wiki/Pectin#Sources_and_production

**Comment by DangerNoodle** [comment]
This is the second person to make this mistake.

**Comment by ituluwituluwzev** [comment]
https://en.wikipedia.org/wiki/Quince_cheese
It requires no factory-manufactured tool. Possibly more difficult than gelatin-based aspic.
