### ISSUE TITLE
Expandable baton fix

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#21157]
There's two batons in the game, the generic 'expandable baton' and the 'PR-24 baton'. The former when collapsed shows in the OTHER category, and should be fixed to be listed under WEAPONS instead, possibly appended with the '(retracted)' info to bring it in line with the other one. PR-24 baton has WBLOCK_2 and RAPID, the expandable baton only has WBLOCK_1 (probably since it has no handle for arm blocks). It would make sense to add RAPID, though.

**Comment by Night-Pryanik** [comment]
@BorkBorkGoesTheCode would you like to propose to merge the changes you made in your fork into this master?
