### ISSUE TITLE
Create prompt to "Take Off Shoes/Helmet" when already using one and trying to wear another.

### ISSUE THREAD

**Issue by RobertoVGoulart** [CleverRaven/Cataclysm-DDA#21150]
Instead of just saying that the player is already using a shoe/helmet on the log, create a prompt asking if he wants to change X for Y.

That would reduce the time needed to change into pieces of clothing that you can only use one of and are useful on just some occasions (Rollerblades/Hazmat Suit/Swim Fins).

**Comment by pisskop** [comment]
Im actually against this.

In combat, or when performing actions within enemy sight, this could lead to issues.

**Comment by RobertoVGoulart** [comment]
Doesn't the game already have prompts for that, confirming if you want to do something with enemies close?

**Comment by pisskop** [comment]
yup.

And its obnoxious enough as it is.

Adding MORE prompts to the game, ones which take several turns and alter your armor resistance, foot encumbrance and run speed, and acid resistance is not going to make it any better.

**Comment by Shadefang** [comment]
I can't say from a programming standpoint, but from a player's point of view I have to disagree.  This would cut out half the menu navigation (2/3 if you were checking if you had the item before taking the item off) in exchange for not being able to double check your surroundings between two actions that already cause prompts on enemy action,and are almost always taken one after the other.  If you really need the break in the middle, i see no reason you couldn't just use the old method.

**Comment by pisskop** [comment]
the difference being that 99/100 times you _dont_ want to change shoes.

advanced inventory management, autopickup, or even just picking up boots, the easiest source of leather.

all negatively affected by the suggestion here.  no reason to implement a potentially dangerous auto action for an edge case

**Comment by RobertoVGoulart** [comment]
Why would it be an auto action? 
My suggestion was to make it only when the player tries to "w"ear boots/helmet why already wearing one, not when picking it.

**Comment by Night-Pryanik** [comment]
Almost a year with no discussion, closing. If there's still interest in this, ping me.
