### ISSUE TITLE
Potential weirdness with health?

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#21155]
Ok, either I'm missing something or there is something wrong. My health is consistently dropping. I'm not eating junk, I'm not staying up too long, I'm not irradiated, I'm not cold, and I'm wearing waterproof clothing, enough to not be getting wet penalties. Despite that my health is dropping a point of two a day. Am I missing something that could be impact my health?

**Comment by Leland** [comment]
This is probably better suited to [the forums](http://smf.cataclysmdda.com/). Github issues are for bug reports and suggestions.

**Comment by 1skandar** [comment]
That's what I'm trying to ascertain.  As far as I'm aware nothing should be impacting my health, and yet my health is going down. Either I've missed something or this is a bug.

**Comment by DangerNoodle** [comment]
Have you been having to take painkillers, such as aspirin? Some non junk food also carries a small health malus.

**Comment by 1skandar** [comment]
Aspirin? Hm, that's a possibility, although I'd swear I've been careful there, and I know I haven't taken enough to drive it as low as it is getting. Food is a distinct no, I'm careful overall and I've been extra vigilant lately.

It's not a huge problem, it's a slow loss and it seems to normalize at -10 or so. That said, it seems to be occurring across several games and I'm not sure why. I've been using debug to watch my health mod, and I'm not seeing any massive negative spikes. Since I'm  not set up to be eating 100% healthy, it normally hovers from -1 to about 4 or 5. Despite that, my health is dropping a point here, a point there and not actually going up and none of the mechanics I know about tell me why.

**Comment by ituluwituluwzev** [comment]
Is it vanilla or with mod?

**Comment by 1skandar** [comment]
Several mods, but none that should be effecting the player. I'm beginning to suspect that there is something that is changing health directly instead of changing the health mod. 

Spent a few days tinkering with an RV, no combat no nothing but vehicle work for three days. Eating vegetarian beans and rice, drinking clean water. Health dropped from -9 to -12, with a health mod of 6 to 8 pretty much all the time. Not cold, wet, or tired. Not irradiated. Poked the save file to make sure there wasn't anything effecting me that wasn't showing up in the @ menu. Something is borked, but damn if I know where to find it.

**Comment by Leland** [comment]
Can you post the savefile here

**Comment by DangerNoodle** [comment]
Since all varieties of beans and rice have a health value of 1, that definitely eliminates food as a cause. If anything that seems to suggest that health mod is no longer correctly changing health.

**Comment by 1skandar** [comment]
https://dl.dropboxusercontent.com/u/46780505/Solomons.zip 
Oh, and I'm using a Japanese mod, Grim Reaper. Doesn't touch player health, but if you want to avoid the save complaining of a missing mod:
https://dl.dropboxusercontent.com/u/46780505/GReaper.zip

**Comment by DangerNoodle** [comment]
Mod appears to only have a selection of different scythes. Only potential oddity is one item, Vanitas Vanitatum, with the sap life artifact property. But unless that is bugged, it would exclusively restore your hit points when dealing melee damage, not affect the health stat.

Have you been handling any artifacts? What about content from other mods?

**Comment by 1skandar** [comment]
No. Still very early game. About the only thing I got going on is a few mutations, and none of those should effect health. And, again, this is something I've noticed across a lot of saves recently, where I'd be eating healthy and taking care of my character and yet not get the positive health messages. So I began to keep an eye on the health mod and the health stat the last few games and, well, this is what I'm seeing. My health mod will be pretty much positive, albeit usually only single digits, and yet my actual health will be negative. I've been trying to understand how the health system works and the more I look into it, the more confused I am getting. 

While i'm not expecting my health to be wildly positive, with my playstyle my health should be a few points positive, minus a bit of time spent in the rain or cold. Instead I'm seeing a health mod that ranges up to around 10 to 12 if I work at it....and yet a health that tends to be -5 and lower and simply won't budge despite spending a day or two indoors just hanging out and not doing anything strenuous. 

I know this kind of bug report is frustrating. I don't have anything concrete, I can't actually *prove* any of this, my understanding of how things work is most likely incomplete, and lord knows I may simply be overlooking something obvious. But it finally got to be enough where I'm here trying to get clarification. This looks *wrong*, it doesn't match expected behavior nor does it follow what the wiki would have me believe, and I can't correlate anything that I may be doing with what is happening.

**Comment by DangerNoodle** [comment]
I have noticed lately that even taking a vitamin every day, with Simplified Nutrition on, health appears to stay at the "no wakeup message" level when it used to start reporting positive roughly a week or two after beginning the vitamin regiment.

Something almost certainly is acting abnormally.

**Comment by 1skandar** [comment]
That....is something in common. I'm using Simplified Nutrition as well. Perhaps something in the code that removes vitamin needs is also short circuiting the way health is handled? 

There might be a correlation here. I think my problems started right around the time Simplified Nutrition became a default mod. Easy enough to test, remove mod, play, report back.

**Comment by Zilenan91** [comment]
Cooked Offal raises health mod directly if it helps.

**Comment by DangerNoodle** [comment]
If there is a connection, it might simply be from the series of changes to nutrition behavior in general. It would be hard to test this without simplified nutrition unless one vitamin a day does not trigger any effects from excess intake.

**Comment by Coolthulhu** [comment]
Health mod to health is heavily random: every time the check is made, effectively `rng(-100,100)` is added to your health mod for this check.
I couldn't get a good math source for this, so I brute forced it and found that there is ~5% chance for health to deviate by 10 points or more from health mod within first 30 checks (7.5 days). This chance increases to ~15% around 100 checks (25 days).

It could be a bug, but it's perfectly feasible that it's just rng having much stronger effect than health mod from regular food.

**Comment by DangerNoodle** [comment]
Even when taking vitamins once a day?

**Comment by 1skandar** [comment]
Regardless, this looks to be a bug. This is across several playthroughs over about a month or so. I can't nail it down 100%, but health appears to drop, and stay, around -5 to -10 regardless of best efforts. In fact, the harder I try to maintain a healthy lifestyle, the less impact that lifestyle has on my overall health.

**Comment by Xpyder** [comment]
@1skandar 
Firstly try to make sure you don't have a parasite or other hidden infection
Secondly see if you can enable the debugging messaging, that might give hints as to what might be affecting health
Thirdly what is the build date you're using? (*like 05/29/2017, you can check this on windows by checking the dates inside of the zip file you downloaded, or the modified date of the cataclysm.exe or cataclysm-tiles.exe file)

Also can you confirm that you don't have any unusual traits, mutations, bionics, or addictions, and that you're sleeping in a healthy environment (inside, no dirty clothes or rotting food nearby, etc)

**Comment by 1skandar** [comment]
I've checked my save for hidden effects. Debug messaging I'll check. And I update the game to the latest before playing. And I wasn't aware that just walking around in the open was a problem. Wasn't before, at least.

 My play style is to be very health conscious. About a month ago (ish? not sure when I noticed) any character that made it day 15 or 20 ish would start getting good health messages, now I've got characters surpassing day 30 or 40 at negative health pr single digits at best, consistently. Something is amiss. 

I guess I should go diving into the commits to figure out if anything has touched health recently. I know enough C++ to read the code.

**Comment by Xpyder** [comment]
I downloaded your save and it does seem strange.

I dropped the old food, went to one of the houses to the south, removed the corpse from the bedroom, spawned a filter mask, mineral water, woods soup, dehydrated fruit, multi-vitamin, antifungal drugs, antiparasitic drugs, antibiotics, and spent a couple days eating, sleeping, and waiting, and my health is still around -10

I would normally expect to be around +10 with this lifestyle

At first I thought it was from your mutations, but I removed them all and gave myself some immunities for debugging purposes and I don't see why your health keeps dropping.

![image](https://cloud.githubusercontent.com/assets/12039454/26748859/dd8ae8c2-47b6-11e7-9b19-7840f4a60cec.png)

**Comment by Xpyder** [comment]
for ease of access here's his bionics
![image](https://cloud.githubusercontent.com/assets/12039454/26748903/773d8916-47b7-11e7-88d0-f7c06fa605d2.png)
![image](https://cloud.githubusercontent.com/assets/12039454/26748905/79e29468-47b7-11e7-917b-f48d8272288d.png)

**Comment by 1skandar** [comment]
Hmm, mind repeating that with a fresh character? If health doesn't rise it isn't just me.

**Comment by Xpyder** [comment]
With my build I have a character who's at +10 health in year 2 so I doubt it's everyone, there's probably just something behind the scenes I can't find.

it's not the bionics or the exercise.  I tried removing all the bionics and walking for an entire day and my health got worse (-13) so if we get other reports too someone might need to dig into the actual save file to try and figure out what's going on.

![image](https://cloud.githubusercontent.com/assets/12039454/26749160/cef4f588-47ba-11e7-9fbc-20f8dafba9d0.png)

**Comment by Coolthulhu** [comment]
I just tested the save by waiting for quite a long time and despite no healthy food, character's health rose to -5 after a (longer) while.
Sounds like just RNG being RNG. Health mod isn't inverted in case anyone suspects that - setting it very high will properly cause health to rise every time.

**Comment by 1skandar** [comment]
Yes, but your testing doesn't match the way I play. I *do* eat (and live) healthy, and health steadily drops, whereas in your test health mod would be 0, or even slightly negative depending on external factors. Try keeping the health mod at 10 ish for a while and see what happens.

**Comment by DangerNoodle** [comment]
That does seem extremely odd. If it is random, why is it trending up for one player doing nothing healthy or unhealthy, but trending down for another player actively trying to stay healthy?

**Comment by 1skandar** [comment]
Ok, after a semi-thorough look at the source, I can't fid anything out of place, or any sign anything has been changed recently. I'm beginning to suspect a RNG failure, really, and that isn't something that can be easily diagnosed and may be computer specific. 

Sigh. It's frustrating, I've torn things apart and I can *see* that things aren't right, and haven't been for a while, but damn if I can spot exactly why or point to any specifics. I'll leave this open for another day and close it if no one can offer anything more concrete.

**Comment by Coolthulhu** [comment]
I said it already: the effect of the healthy mod is relatively weak here. The random factor is significantly stronger than any health mod value you could feasibly have by eating "realistic" food.
Whether that means binging on junk food or health food is irrelevant here.

> I'm beginning to suspect a RNG failure, really

No need for that. I have provided the math above.
It's perfectly feasible for you to have 10 health less than your health mod at times.
Even at constant 10 health mod - which you most certainly do not keep at all 4 of the tests during the day, meaning that 5 is a much safer bet here - health will occasionally dip into -10 or so.

You expect much more consistency from the RNG than it can logically provide.

**Comment by DangerNoodle** [comment]
That suggests the effect of randomness on health needs to be toned down, then.

**Comment by 1skandar** [comment]
Yes, but this isn't a one off situation. This is one of several characters who have gone 20 days or so with health ranging in the negative up to 3 ish positive. This is the first one I've sat down and watched for like a week or more and absolutely concentrated on being as healthy as I could, to the same effect.

And yes, if health is *supposed* to trend towards health mod and, after 20+ days it is 15 to 20 *below* the health mod, and the health mod has been consistently 5 or higher, I'd say the RNG needs toning down a bit. It's already hard as heck to push your health much above 10, for that mostly to not matter thanks to RNG, well, I'd say something is off.

**Comment by Coolthulhu** [comment]
> It's already hard as heck to push your health much above 10, for that mostly to not matter thanks to RNG, well, I'd say something is off.

To my knowledge, the basic health mechanics (healthy mod to health conversion) haven't been touched for at least 2 years. There's a very high chance they were never fully completed and their incompleteness was hidden by lack of feedback (health messages are relatively recent).

This issue can probably be closed.
The issue of health being unbalanced is a separate one that can't be easily solved without a good idea of where should it end up.
I made a thread on forums: http://smf.cataclysmdda.com/index.php?topic=14568.0
