### ISSUE TITLE
Automatic fire, perfect target switching

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#21158]
An A7 laser rifle on automatic fire will do a 5-round burst, but I've now noticed several times that when it takes less rounds to kill an enemy, the character may change its target on the fly and fire the remaining rounds with perfect accuracy at another target, even if aiming direction differs by 30° or more.

This is not how auto-fire works, especially not if you use careful or precise aim. There should be no target switching in the middle of a burst.
![untitled](https://cloud.githubusercontent.com/assets/13466852/26644809/4a0143ac-4636-11e7-98a0-409d26f3dc89.png)

**Comment by Zilenan91** [comment]
It used to be where if you shot something with Full Auto, you would kill it with the first couple bullets then waste the rest of the bullets shooting it's corpse.

A way to fix would be to make full auto only shoot bullets until the target dies, though this could break things like miniguns which are basically designed to miss a lot and mow down whole hordes from the missed bullets.

**Comment by kevingranade** [comment]
Perfect target switching shouldn't happen, IIRC it should spray a few
rounds in the intervening space between targets every time it switches.
Ifvthe accuracy is too high on subsequent targets, it perhaps should jyst
aim at the target square and not the creature itself, there's a small
distinction there that would effectively lower the accuracy.

**Comment by Tharn** [comment]
Yeah, pulling the aim from a killed target toward the next target would be fine and it'd make sense. It's just the machine-like accuracy that I saw with my character that bothered me. It could be a compound result of a 0 recoil gun, decently high skills, Targeting System and Telescopic Eyes. Might have to test this with a blank character.

**Comment by Leland** [comment]
@sbombay had this to say in duplicate issue #21243:

> Upon killing the last enemy I automatically switch my fire to any friendly (NPC or my turrets) even if they are far behind me in the exact opposite direction I was firing.

They also recorded a GIF of this happening in a particularly egregious example, in which the enemy they're targeting is directly in front, and the final round hits the friendly turret they're standing next to : http://recordit.co/iTPJNFPReH
