### ISSUE TITLE
Static NPCs with custom NPC classes spawn errors at character creation.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#21159]
If you make a mod with custom NPC classes and define a static NPC to have said class it will throw an error before character creation saying said class is invalid but everything works as intended. After testing can confirm the following:

-If no static NPCs are define with custom classes there are no errors.
-Only affects static NPCs as spawning an NPC with the debug menu will occasionally spawn one with a custom class with no errors.
-The existence of the custom class is not the issue since if static NPCs in a mod are define by default classes then there is no error.

**Comment by DangerNoodle** [comment]
According to @chaosvolt custom NPC classes are not functional for the starting NPC, nor for dynamic NPCs or ones spawned in debug. Evidently only versions placed in mapgen will work without issue.

I was alerted to this by a mention in the following issue: https://github.com/chaosvolt/cdda-arcana-mod/issues/2

**Comment by Noctifer-de-Mortem** [comment]
So a little bit of context. I created an NPC class called `Bio_Weapons` to give to specific static NPCs who spawn in a custom building. If you take off the NPCs from the mod then there is no problem but when defined to spawn it says that the class is invalid. If you get that same NPC and define them with a default class (say `NC_Scavengers`) instead then there is no problem, only classes defined by mods. Also dynamic NPCs are able to spawn with the class with no issue.

**Comment by DangerNoodle** [comment]
Peculiar. I have not attempted this myself, and do not know the full extent of what Chaosvolt has done in testing this.

**Comment by Coolthulhu** [comment]
Is the class called "invalid" or "unknown"?
It's important because "invalid" is for load failure and the result is defaulting to no class (obvious bug here), while "unknown" is a warning mapgen spews and this one can be premature.

**Comment by Noctifer-de-Mortem** [comment]
It says invalid.


![invalid_classes](https://cloud.githubusercontent.com/assets/16777044/26701679/b0e65fb0-46e7-11e7-9866-27912553f7e0.png)

**Comment by TheMrBakit** [comment]
Isn't bio weapon zombies came form Pk's mod?

**Comment by Noctifer-de-Mortem** [comment]
They are from the cataclysm++ mod.
