### ISSUE TITLE
Distinguishing harvestable trees

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#21160]
What do you think about making all trees that don't give anything except wood more different from others? For example, I've tried making them less colorful and it helped a lot. Forest no longer green? I couldn't care less.

![2017-05-30-074122_1366x768_scrot](https://cloud.githubusercontent.com/assets/1585431/26653796/fe6a8468-465c-11e7-8c1a-f4bf861dcb13.png)

**Comment by ZChris13** [comment]
ASCII suffers similar problems, exaggerated at night due to no colors. Impossible to distinguish pine trees (green 4) from useless regular trees (green 7) with useless dead pine trees (brown 4) and tanbark-giving blackjack oaks (brown 7) sharing a color.

**Comment by Mecares** [comment]
Maybe add a third look around option to also be able check your surroundings for specific tiles and not only items and monsters?

**Comment by kevingranade** [comment]
What's the basis for this being marked as Accessibility? That is a specific tag for (mostly visually) impaired users being able to use the game, and this doesn't seem to qualify as it impacts non-impaired users the same.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.

**Comment by Zireael07** [comment]
It doesn't qualify for accessibility tag as such, but I believe it's still valid. Telling harvestable trees at a glance would be a great quality of life feature.
