### ISSUE TITLE
gcc7 build failure

### ISSUE THREAD

**Issue by Toothspit** [CleverRaven/Cataclysm-DDA#21165]
Linux x64 gcc7.1.1 e61a2b0

The new warnings in -Wall and -Wextra with gcc7 fail the build with RELEASE, specifically `-Wint-in-bool-context` and `-Wimplicit-fallthrough`. [Here](https://ptpb.pw/6oaS/make)'s a non-RELEASE build log so we can see all of them.

I could fixup the switches ezpz, but specifically the [assign.h:51](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/assign.h#L51) one is a little beyond my ken, since the type for `val` in that is apparently okay with being a bool (?) and I have a <1% understanding of it. Is it safe to pretend `val`'s a float or something?

The easy fix would be to check gcc version in the Makefile and make some exceptions until we figure this out, but that's hacky and bad. A PR fixing this would need to add an attribute `[[fallthrough]];` (or just a comment like `// fallthrough` [apparently](https://gcc.gnu.org/onlinedocs/gcc-7.1.0/gcc/Warning-Options.html#Warning-Options)) to our intentionally-falling-through case labels and figure out that `val` multiplication; all need-to-fixes are in the [build log](https://ptpb.pw/6oaS/make).

(Also, unsure if separate issue, but somewhere between 4 and 7 `gcc --version` may have changed format, now [this bit](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/Makefile#L159) just returns a [build date](https://cloud.githubusercontent.com/assets/18541270/26711616/35f657a2-4727-11e7-8586-938eca8ae01c.png) rather than the [version](https://cloud.githubusercontent.com/assets/18541270/26711647/7bb069cc-4727-11e7-8c3e-94e0bd3845ed.png) from `gcc -dumpversion`, at least on Arch)

**Comment by kevingranade** [comment]
Oh god, it finally happened, int in bool context warns.
Also, what the actual shit, both std::is_arithmetic<bool> and std::is_integral<bool> evaluate to true, do we have to check specifically for bool to avoid this?

When you say c++17, do you mean gcc version 7+, or --std=c++17?
If the latter, that's a bit premature, c++11 is barely mature enough to use, its going to be a year or more before we flip to c++17.
If it's the former, I'll take a look next time I have a chance, but I'd rather just not build on gcc 7+ than start hacking up the makefile with special casing for versions.

**Comment by Toothspit** [comment]
> When you say c++17, do you mean gcc version 7+, or --std=c++17?

Gcc version 7, my head was filled with gnu and forgot to clarify.
