### ISSUE TITLE
Advanced Inventory: Can't move items to inventory

### ISSUE THREAD

**Issue by huggablemonad** [CleverRaven/Cataclysm-DDA#21167]
OS: Linux
UI: Curses
Version string: 0.C-22596-g08adde5a8a
Description: I'm unable to move items to my inventory when using advanced inventory management. The message "This is too heavy!." is shown.

![cdda-advanced-inventory-bug](https://cloud.githubusercontent.com/assets/17948023/26715701/b42d8b3c-4744-11e7-9415-b41614650996.png)

```
0361eec0c6f1bed298cbe2901aaa00d064e9aa4e is the first bad commit
commit 0361eec0c6f1bed298cbe2901aaa00d064e9aa4e
Author: AMurkin <amurkin1988@yandex.ru>
Date:   Sat May 27 12:12:06 2017 +0300

    fix to the debug storage's bug
```

**Comment by AMurkin** [comment]
pinging @BrettDong and @Qrox 
What if return true when g->u.has_trait("DEBUG_STORAGE") [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/advanced_inv.cpp#L2114)?

**Comment by Qrox** [comment]
I'd say the version before #21115 is good enough. I think returning true will not work since there are code handling `amount` later in the code. Could just skip the check if the player has debug storage though.

**Comment by BrettDong** [comment]
@Qrox Would you like to propose a fix? I don't have the free time to spend on GitHub as before in recent days. I'm sorry I wrote a piece of problematic code, but I'm unable providethe fix soon.

**Comment by Qrox** [comment]
Ok, I'll see what I can do.

**Comment by Tharn** [comment]
Can we have it merged please? AI is near unusable without this fix and it's tiny.
