### ISSUE TITLE
[ChestHole Tileset] Metal door from Fire Station appears as wooden doors on latest version.

### ISSUE THREAD

**Issue by RobertoVGoulart** [CleverRaven/Cataclysm-DDA#21177]
The winch still works, and examination still show it as a metal door, so i think it's just a Tileset problem.

On version 0.C-22539-g6c1bedc and older it was shown as normal, upon update to 0.C-22600-g13ff12c this happened.

**Comment by RobertoVGoulart** [comment]
![0 c-22600-g13ff12c](https://cloud.githubusercontent.com/assets/20757625/26754415/e8aa40dc-4850-11e7-835c-f0587b628fa7.jpg)

**Comment by Leland** [comment]
I have a feeling the metal doors got reskinned. You can see I generated a wooden door for comparison.

Paging @Chezzo 

<img width="1280" alt="screen shot 2017-06-03 at 11 39 51 am" src="https://cloud.githubusercontent.com/assets/714017/26754916/6a595b2c-4851-11e7-8d5c-1e483777d9af.png">

**Comment by DangerNoodle** [comment]
The tile set uses three different sets ior sprites. One being the observed recolored wooden doors, one using an abnormal top-down perspective, and the older metal door sprite used by several other tile sets.

Use of strictly the older, more expected sprite might be best.

**Comment by Chezzo** [comment]
How's this? 

![image](https://cloud.githubusercontent.com/assets/2432177/26755222/26b5c184-4857-11e7-8257-228393ddf360.png)

**Comment by DangerNoodle** [comment]
Potentially interesting. Is there a way to use that for versions you can open freely or pick, and use the older shutter sprite for versions meant to be opened by a lever?

**Comment by Chezzo** [comment]
Yes, got it now, thanks. Will do all those things you said @DangerNoodle.

**Comment by ZenZen2** [comment]
@Chezzo may i ask if there is any eta for a new update ? :)

**Comment by Chezzo** [comment]
I have been working on glasses for the 24 tileset for much longer than I should have, so when I get them and railings done.

When I move them one pixel up, they look like sunglasses because they are filled with the dark eye color. One pixel down, and it looks like they are playing naughty librarian dress up.

![Are you looking at me?](http://i.imgur.com/U2XMmNA.gifv)

**Comment by ZenZen2** [comment]
After some testing it looks like #23203 fixed the door bugs.
