### ISSUE TITLE
Power armor no longer restricts clothing choice

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#21174]
Power armor no longer restricts clothing choice.

![image](https://cloud.githubusercontent.com/assets/2432177/26752169/fa1a0890-4817-11e7-87bd-e1fbe766d5cb.png)
That is me wearing boxer shorts and a back scabbard over my power armor.

To reproduce, wish for power armor, put it on, then put on any item of clothing. Putting on a power armor helmet seems to make power armor restrict clothing like it did in the past.

**Comment by BrettDong** [comment]
Can confirm. Put on a power armor first, then put on a backpack, and next put on a power armor helmet, you get power armor + backpack + power armor helmet. But if you wear power armor and helmet first, then you are unable to put on a backpack.
