### ISSUE TITLE
Select Cash Card is always visible behind vending UI.

### ISSUE THREAD

**Issue by PlasmaChroma** [CleverRaven/Cataclysm-DDA#21178]
This could perhaps be the intended behavior but it looks bad and doesn't help the user in any meaningful way.

Inserting cash card with limited number of cards, looks like a confusing middle column here:
![cash_card_few](https://cloud.githubusercontent.com/assets/7933452/26754588/69efcd02-484b-11e7-84a6-0c1f2ed26e3f.png)

Inserting with LOTS of cards:
![cash_card_lots](https://cloud.githubusercontent.com/assets/7933452/26754591/7106e22e-484b-11e7-888f-1f57d3620f4e.png)

**Comment by ZhilkinSerg** [comment]
This probably happens with any overlapping menus.

**Comment by Tharn** [comment]
It also happens in the ATM menu. You select an option (withdrawal, deposit) and even if the cash card selection menu is exited or you selected a card that isn't applicable, the card menu remains in the background while the small main ATM menu pops up again. It would be easier to navigate if only one menu was left visible.
