### ISSUE TITLE
Circular saw doesn't use charges like the other power tools do

### ISSUE THREAD

**Issue by SuperAppleDan64** [CleverRaven/Cataclysm-DDA#21176]
Instead it stays (on) while you are crafting, this uses up its batteries way too fast for single tasks. The toolbox has the same amount of Metal and Wood Sawing that the circular saw has and doesn't need batteries to be used. Using power tools should save you more time compared to manual tools, not be more of a hassle to use.

**Comment by Night-Pryanik** [comment]
#21628 will make first steps in resolving issues like this if/when it will be merged. It would be needed to make recipes understand use of "tools OR qualities" (not only "tools AND qualities", as for now), though.
