### ISSUE TITLE
Web linter doesn't support new lint rules

### ISSUE THREAD

**Issue by Toothspit** [CleverRaven/Cataclysm-DDA#21181]
> Narc0tiq: Oh, huh. Actually, the web linter can get out of sync with the live one now - someone please make an issue and @mention me, because I need to move the web linter to gorgon, but I'm not near a computer now and I'll forget by the time I get back  tomorrow. 

>> Toothspit: I'll do so, but have 0% of an idea what you're talking about 

> Narc0tiq: Either move it to gorgon or make sure it's updated whenever a build is made. Dev is the same machine as ci.narc.ro, but I've turned that one off, and the web linter just references the Jenkins build workspace... Which isn't getting updated anymore, because the job is disabled.

> Narc0tiq: So if the linting rules change, the web linter won't reflect that.              

@narc0tiq This is your own doing. Edit: 2017-06-04 06:23:54 UTC if you're looking at your IRC log.

**Comment by narc0tiq** [comment]
Weird, I didn't get an email from this one. Regardless, it needs fixing.

**Comment by DangerNoodle** [comment]
I have already stated previous annoyance at the web linter missing contexts, and expressed worry that the repository checker might generate failures for files that cannot yet be lintfixed.

**Comment by narc0tiq** [comment]
You *can* run the linter yourself on a machine with Perl and jq, but the web interface is certainly more convenient. The goal is that both web linter and build process must show the same errors (and normally, they should be the literal same script - thus, this issue).

**Comment by narc0tiq** [comment]
> web linter missing contexts

Are you sure it's not just the linter in general? According to #21153, the same "unmatched contex" (sic) happens when Jenkins runs the linter, and Jenkins just runs whatever's in the repo right now. This issue refers to me making sure the Web linter at <http://dev.narc.ro/cataclysm/format.html> remains up to date with what Jenkins uses.

**Comment by narc0tiq** [comment]
Ok, the web linter should be fine now -- I've configured [the Doxygen builder](http://gorgon.narc.ro:8080/job/Cataclysm-Doxygen/) to also republish the web linter, and tested http://dev.narc.ro/cataclysm/format.html using the JSON in #21153 to ensure it's correctly raising the same error the regular linter does.

It should automatically remain up to date for the foreseeable future.

**Comment by Leland** [comment]
@narc0tiq any chance you can throw the web linter into a git repo? I'd like to add some CSS styling and tutorial/text to it.

**Comment by narc0tiq** [comment]
I have good news: it's already in a repo -- this one! It's [tools/format/format.html](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/tools/format/format.html), and it uses [tools/format/format.pl](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/tools/format/format.pl) for the actual linting part (with some symlink magic on my web server, but that shouldn't matter).

Keep the XHR's POST endpoint to where it is and you're cleared to make any changes you like.
