### ISSUE TITLE
Repairing of some vehicle parts is broken

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#21187]
Seems like #20550 has broken repairing of vehicle tracker, saddle, foldable seat, seatbelt, 5-point harness, vehicle curtain, aisle curtain, water faucet, bicycle horn, car horn, truck horn, back-up beeper, wing mirror, inboard mirror, aisle lights, atomic lamp, floodlight, car headlight, reinforced headlight.

**Comment by 1skandar** [comment]
As a note, all of these can still be repaired if removed from the vehicle first. Which makes repairing headlights, which get damaged often, a right pain in the ass due to having to have to re-aim them all the time.
