### ISSUE TITLE
Error when persuading companion to train you.

### ISSUE THREAD

**Issue by RobertoVGoulart** [CleverRaven/Cataclysm-DDA#21184]
After asking successfully for training and choosing the topic, a error message is shown.
After that training proceeds as normal.

![npc training](https://cloud.githubusercontent.com/assets/20757625/26766170/67e51cd4-4962-11e7-8276-a8f799f7307e.jpg)

**Comment by RobertoVGoulart** [comment]
My save file: 
https://drive.google.com/file/d/0B7wK1ucc9teYQzJPdG94Rmc2dWc

**Comment by DangerNoodle** [comment]
Also found this occur. In my case it assigned the dummy null mission afterward.

**Comment by notafed** [comment]
Could this be the same as, or related to, #21027?
