### ISSUE TITLE
Linting web tool out of sync with gorgon

### ISSUE THREAD

**Issue by AlecWhite** [CleverRaven/Cataclysm-DDA#21182]
http://dev.narc.ro/cataclysm/format.html seems to be out of sync with gorgon. @narc0tiq.

`<Narc0tiq> Oh, huh. Actually, the web linter can get out of sync with the live one now - someone please make an issue and @mention me, because I need to move the web linter to gorgon, but I'm not near a computer now and I'll forget by the time I get back tomorrow.`

**Comment by narc0tiq** [comment]
To be fair, it might currently not be out of sync, but it will be when the
rules change. Best get this fixed now.

**Comment by AlecWhite** [comment]
By the way, closed this one due to https://github.com/CleverRaven/Cataclysm-DDA/issues/21181 being already there.
