### ISSUE TITLE
Minimum volume of knives in sheathes and guns in holsters.

### ISSUE THREAD

**Issue by Shadefang** [CleverRaven/Cataclysm-DDA#21185]
I found that you cannot use a survivor belt's holster action to sheathe a hunting knife.  After some testing I discovered that a "max volume" of 4 or more on a sheath disallowed any knife of volume 1 (0.25 L) from being sheathed, and that no sheath in the game will accept a dive knife, despite the SHEATH_KNIFE flag. This also affects some of the smaller guns, (Makarov PM, Walther PPK, and several others) meaning they can only be put in an ankle holster or shoved in a belt.

At least from my perspective it seems somewhat confusing, as in game there is only a displayed maximum volume, and the failure message when you attempt to use a sheath/holster that is too big for your item gives no indication of why it failed (You don't have the necessary item at hand.)

This appears to be the same issue as #19641 which was reported fixed in #19765

The applicable code is:
```c++
    void holster_actor::load( JsonObject &obj )
    {
    holster_prompt = obj.get_string( "holster_prompt", "" );
    holster_msg = obj.get_string( "holster_msg", "" );
    assign( obj, "max_volume", max_volume );
    if( !assign( obj, "min_volume", min_volume ) ) {
        min_volume = max_volume / 3;
    }
```
https://github.com/CleverRaven/Cataclysm-DDA/blob/4bcc67a9d0b5dc3d2b8844fb3705e4b524fdcb23/src/iuse_actor.cpp#L1906

So I end up with several questions here.
1) Given that the maximum volume for a sheath/holster is displayed, should the minimum be as well?
2) Given the points brought up in #19765 should line 1907 be changed to  "min_volume = max_volume / 4;" ?
3) Should this be how sheathes/holsters with no stated minimum volume be handled?
4) Should the holster and/or quick draw holster be modified so it's possible to carry smaller guns on your hip?
4) Should the dive knife, sheath, and/or ankle sheath be modified to work better together?
5) For the specific instance of the survivor belt, is it intended for knives, small swords or both? It is described as carrying a smaller blade, the sheath volume is slightly larger than the sheath it's made from, and it has both the "SHEATH_KNIFE" and "SHEATH_ SWORD" flags. Given the sheath volume, I think the sword flag only allows the survival knife, kris, machete, and survivor machete; The increased minimum volume restricts it to mostly combat knives (kukri, tanto, punch dagger and butcher/combat/RM42/trench/makeshift knives)

Apologies if this should've been broken up into multiple issues, but it all seemed related.

**Comment by notafed** [comment]
Can confirm this is still an issue, and caused me some confusion regarding the survivor belt as well.

**Comment by Akhier** [comment]
New here but this seems like something I might be able to do.
When it comes to if the minimum should be displayed the problem isn't if it should be displayed but whether you should display it if there is none. Not knowing you might not be able to stick your new gun in your holsters is a bad thing. Either way is easy enough to do though. For the moment I will figure out having it always show.

As for the other things I do think it should be broken up into other issues if only because besides the first which is an interface issue they are mostly balance related. I am sure each of them deserve a couple people hashing it out and by having them all in one issue the discussion would be harder to have.

**Comment by kevingranade** [comment]
Interface updated by @Akhier
