### ISSUE TITLE
Game hangs when approaching NPC-filled refugee center

### ISSUE THREAD

**Issue by jriesen** [CleverRaven/Cataclysm-DDA#21191]
Pulled down an experimental version Windows Console 0.C-6498 (commit gfc35f9b), tried to walk to a refugee center and it hangs when I get too close.  It's not a hard loop, i.e. the app is still responsive and not frozen, but the snow no longer animates and the game does not respond to any keypresses.  I have to hit 'X' on the window to close it out.

Attached is the zip of my save folder.  Load it up and try walking southwest a couple of steps.  I tried turning on debug mode and the error occurs right after all the NPCs load up and dump their debug messages, but there's nothing insightful there for me.  Note that I've played a few other characters in this world (all dead except for the active char), not sure if that matters.

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1056198/save.zip)

**Comment by jriesen** [comment]
Also:  I had both static and random NPCs enabled in this world, and I _disabled_ the on-by-default "Disable NPC Needs" mod.  Not sure if this is relevant, or will help anyone with reproducing the bug.

**Comment by ZenZen2** [comment]
Look like a mission is crashing you. On 6459 it doesnt crash but throws debug messages.

**Comment by ZenZen2** [comment]
Again, this debugs are from a different version (6459)

![mission](https://user-images.githubusercontent.com/20055252/26957199-b173d7b4-4cc3-11e7-80c2-7ac750c5d309.jpg)

**Comment by sxmichaels** [comment]
@jriesen Has anyone else encountered this bug, or is this a one-off thing as far as you know? I looked at your save, and my guess at what's happening is that there are somehow _two_ `Reach Refugee Center` quests assigned to you, one of which has the correct player ID (7) and another of which is wrong (-1), and the latter doesn't show up in the quest menu as a result — a manual review of `master.gsav` confirms this. When you reach the center, it tries to wrap up both of those missions and fails on the one with the wrong ID. You can then see that the mission then completes twice and shows up twice in the missions menu.

Just now I initiated and complete the `Reach Refugee Center` mission on several different newly-generated maps on the latest version (`4f691a95a3`), and none of them produced this error. Maybe we should close this issue if there's no other evidence of it still existing in the current version?

**Comment by Night-Pryanik** [comment]
No confirmation in almost half a year, closing.
