### ISSUE TITLE
Too Many Vault Irradiated Wanderers

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#21197]
[Build 6504] These irradiated wanderers spawn in massive packs of of anywhere between 30 and 60 enemies at a time and even larger when spawning inside larger rooms inside the vault. I have two pictures that shows just how insane this number has become:
First picture showing very large packs of enemies on minimap (not showing the 200 or so I killed in the library section just above this):
![capture](https://user-images.githubusercontent.com/24307650/26882942-cc91dd08-4b69-11e7-9ffd-d70bc11f8bf4.PNG)

Second picture showing the total kills for irradiated wanderers being 4423 so far. This is my second vault expedition also noting that I got maybe a quarter of the way through the first vault.
![capture2](https://user-images.githubusercontent.com/24307650/26882824-7a2b6764-4b69-11e7-8d97-70b33d00067b.PNG)

I would like confirmation on whether this is a bug or if this many irradiated wanderers should actually be here. Each wanderer takes about 2 hits and as soon as they surround you then you die unless you have extreme CBM power to keep repair nanobots CBM on constantly. Also, the wanderers themselves sometimes explode when inside fire and its quite interesting, I make fire walls with the mini-flamethrower CBM to damage them enough for one-hit kills . I understand that the vault would want to take in as many people as possible, but the amount of oxygen down there has got to be limited lol.

**Comment by CoroNaut** [comment]
Another picture just because I find this one hilarious :1st_place_medal: 
![capture3](https://user-images.githubusercontent.com/24307650/26895718-79d8e53a-4b90-11e7-8f74-1085e55e171f.PNG)

**Comment by kevingranade** [comment]
> but the amount of oxygen down there has got to be limited lol.

Who says they breathe? Also... you'll probably regret reminding me that dead air is a thing...

**Comment by Chezzo** [comment]
There are three irradiated wanderers in code for tile_ids, perhaps for this reason. 

I should use them.

**Comment by CoroNaut** [comment]
I did notice several different irradiated wanderers on the cdda item browser, some are tougher and some are weaker but all have the same name,

**Comment by Zilenan91** [comment]
Point being there's too many irradiated wanderers

I remember reading a reddit post about someone who cleared a vault of them, and in one vault he killed 12,000 Irradiated Wanderers on 5x spawnrate. A bit silly to have that many enemies in one place. Took him several in-game days, possibly weeks.

**Comment by CoroNaut** [comment]
What I did for most of them is I would let a massive group spot me enough for them to all target and chase after me, then I would huddle myself inside a 1-wide or 2-wide doorway and mow them all down. Any more than 3 right next to you and you start taking enough damage for it to matter, and they also pushed me over constantly which made it 100% more difficult. My games are  1.8 spawn scaling factor with 1.2 item spawn and 12.0 monster evolution currently. Same with this current map, If my character finds a massive horde of 100 regular plain-old zombies, they are all mowed down easily 1 hit for most of them if not all of them, but the irradiated wanderers take at least 3 turns if fighting them in bulk. They push your character down also which gives them many hits on you as well. Note that my character only has light armor and frail and glass jaw traits so it was definitely a challenge to not get hurt.

**Comment by aka-azrad** [comment]
> Point being there's too many irradiated wanderers

> I remember reading a reddit post about someone who cleared a vault of them, and in one vault he killed 12,000 Irradiated Wanderers on 5x spawnrate. A bit silly to have that many enemies in one place. Took him several in-game days, possibly weeks, of non-stop atomic coffee-fueled fighting.

That was me. The game had amazing amounts of lag during maybe more than 50% of my time there, due to how many enemies there were.

Somehow ended up trying to clear out a second necropolis, and so far it's been worse than before, as being too deep in some areas of the vault crash the game due to so many enemies present on the current floor and the floor below that.

**Comment by aka-azrad** [comment]
![cata1](https://user-images.githubusercontent.com/30348690/28468396-70147724-6e65-11e7-9fcd-adf0da1f1d3d.png)

Seriously, too freaking many of them in one room. Can't help but imagine how the vault expected to survive the apocalypse when it seems like its standing room only throughout the entire vault.

And that's just the first level. As I remember, the second level is far worse since there's less wide corridors and more rooms.

**Comment by Taberone** [comment]
How many wanderers are there on normal spawnrates?

**Comment by Night-Pryanik** [comment]
Should be closed by #23741?

**Comment by BorkBorkGoesTheCode** [comment]
@CoroNaut please generate a new world and see if this issue persists

**Comment by CoroNaut** [comment]
I finally found a shelter and it seems like the number of irradiated wanderers is lower than the issue, perhaps about 1/2 to 3/5 as much as from this issue. Thanks :D
