### ISSUE TITLE
Recipe not showing up

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#21209]
Trying to make a vehicle forge rig and the recipe isn't available. I double checked the appropriate JSON and the requirements are Fabrication 4 and Electronics 4 (I have 5 in each) plus a book. In this case the DIY Compendium is what I have and, per it's description, that recipe is in there. Oh, and the book is in my inventory. 

[Here](https://dl.dropboxusercontent.com/u/46780505/Solomons.zip) is my save, if anyone is interested.

**Comment by DangerNoodle** [comment]
Have you already skimmed the book in question?

**Comment by 1skandar** [comment]
Yes. That is the only way the list of recipes it contains shows up in the description. In fact, if you look at the save, I have another book on the bookshelf (electronic circuit theory)  also read that contains the same recipe. 

I edited my save and added it to my memorized recipes list and it is indeed fabrication and electronics 4, and I met those easily. With the book in my inventory it can't even be a line of sight issue,  Soon as I get a chance I'll check to see if any other recipes are impacted

**Comment by DangerNoodle** [comment]
My apologies. That does seem to be peculiar. If there are other recipes affected by this, finding them would be desirable.

**Comment by 1skandar** [comment]
no worries, you gotta ask. Soon as my twins fall asleep and i get my arms back I'll check.

**Comment by Chezzo** [comment]
I think it is that the book doesn't teach you the recipe until you are at the level next to where the book is here:

http://cdda-trunk.chezzo.com/forgerig/craft

Loading the save and raising your fabrication to 8 shows the recipe.

**Comment by 1skandar** [comment]
Ok, I'm going to call that either a bug or oversight, if that's the way it works. A quick rundown of the recipes in the data folder shows that pretty much all other recipes unlock at either the level of or at most one level above/below. 

A book that *teaches* fabrication having a recipe that *uses* fabrication 4 that needs level 8 fabrication to unlock is, yeah, I think broken is the best word. I can't think of a logical reason why you'd need more skill to use a recipe than it would take to *craft* the recipe.

I suspect this is a holdover from when the only way to learn a recipe was to read the book. In which case those limits were the level at which you could *memorize* the recipe, not *use* it. That, at least, makes sense.

**Comment by DangerNoodle** [comment]
Some books do teach non-autolearn recipes at higher levels than others. This is potentially annoying, but intentional. It is only a bug outright when the recipe is autolearned, and the book level is higher than when you would learn it on your own.

**Comment by ZenZen2** [comment]
from ingame testing with "welding and metallurgy" book:
vehicle forge rig appeared to me with electonics 4 and Fabrication 5
vehicle welding rig Mech 5 and Fabrication 4

loaded your save and vehicle forge rig appears craftable to me.
Used around 2 weeks old version 6459. Also had some debug messages on loading your save.

**Comment by 1skandar** [comment]
Again, what is the point of that? If I can't use a recipe until level 8 (pr, it looks like level 5 with another book)  why bother making it a level 4 recipe? I mean, I've got the book as reference helping me out. Now, I get it if I can't *memorize* the recipe until level 8, but *use* it? That's...illogical is the kindest thing I can say about that mechanic. 

@ZenZen2 You're missing a few mods, that's all.

**Comment by DangerNoodle** [comment]
> Again, what is the point of that? If I can't use a recipe until level 8 (pr, it looks like level 5 with another book) why bother making it a level 4 recipe? I mean, I've got the book as reference helping me out. Now, I get it if I can't memorize the recipe until level 8, but use it? That's...illogical is the kindest thing I can say about that mechanic.

You can not learn the recipe from that specific book until level 8, is the problem. The idea is that other books are easier to learn it from.

Making the recipe as high as level 8 may be excessive though.

**Comment by Coolthulhu** [comment]
Yeah, this booklearn recipe discrepancy is a pain and I'm pretty sure it was commonly agreed that it's worth scrapping.

**Comment by ZenZen2** [comment]
Ops!...Vehicle forge rig doesnt appear craftable in your save, i accidently mixed it with welding rig. Chezzo is right.

**Comment by 1skandar** [comment]
@Coolthulhu Thank you. To be fair, it is mostly not a problem. Most recipes have a book that unlocks either at or one level below the crafting skill requirement and any other books that tech the recipe within a level after that.  And then you have the 0.1% that pull this weirdness. Would an acceptable solution for the moment be changing the JSON to pull the outliers into line?

**Comment by kevingranade** [comment]
It depends on the details, if it's something like a textbook that isnt explicitly trying to teach the recipe, id say its totally working as intended.

**Comment by ZenZen2** [comment]
Its a textbook
```
"book_learn": [["textbook_mechanics", 6] , ["textbook_electronics", 8] , ["textbook_fabrication", 8] , ["welding_book", 5]],
```

**Comment by DangerNoodle** [comment]
Those numbers are still at least 1 level off, if only for the sake of consistency. With most recipes, the "worst case scenario" recipe book is still no more than 1 level above the next better option.

**Comment by 1skandar** [comment]
Yeah, considering the book in question is named a DIY compendium I'd say it *not* teaching the recipe sooner than it does is a bit silly.

**Comment by kevingranade** [comment]
This is working as intended and no compelling case has been made for why it's a problem.
The real issue seems to be you expected some kind of formulaic consistency to levels at which recipes are learnable, but the game intentionally is not consistent in that way.
