### ISSUE TITLE
Inconsistent Use of Mini-Flamethrower CBM

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#21206]
**[Build 6504]** If you select the Mini-Flamethrower CBM and use it on a tile next to you, the CBM window pops back up, and if you select the Mini-Flamethrower a second time and use it on another tile, the CBM window doesn't pop back up.

Steps:
1. Open CBM window
2. Use Mini-Flamethrower on some tile (CBM window will re-appear)
3. Re-use Mini-Flamethrower on some tile (CBM window **will not** re-appear)

**Comment by CoroNaut** [comment]
I'm closing this because I am using the mini-flamethrower now and it isn't happening.

**Comment by CoroNaut** [comment]
It happened again so it much be inconsistent, same steps as before.

**Comment by Toothspit** [comment]
Has to do with the time it takes to use the CBM (100 moves). At a 'current speed' of 143, I was able to use it twice per turn every 2-3 turns. At a 'current speed' of 25, I was not able to use it twice per turn at all. The menu pops back up only if you didn't spend the full turn, looks like.

**Comment by CoroNaut** [comment]
I will assume that by how the game handles "moves", that this is intended behavior.
