### ISSUE TITLE
JSONifying mapgen & Bountysource

### ISSUE THREAD

**Issue by Toothspit** [CleverRaven/Cataclysm-DDA#21207]
[Came up in IRC](http://i.imgur.com/rcYYSl4.png), probably not the first time. We want to post a big ol' fat bounty on JSONifying some of mapgen_functions, but aren't sure on the best way to go about it. There also aren't, to my knowledge, any issues for a JSONification PR to close. And if I can be real for second, those mapgen functions are godawful to read when you're trying to do something like #21192.

This issue is merely to establish consensus on how to handle bounties for projects like this: since Bountysource doesn't appear to support Github's `-[ ]` task lists nor Projects, we would have to make a separate issue for each mapgen function to be JSONified to preserve credit for the bounty. Is this acceptable, or is there a better method we didn't know about?

**Comment by 1skandar** [comment]
I'm working on it. I'm kinda waiting for my first PR to be merged before moving on to the rest. Now I know what I'm doing, more or less, single tile buildings won't take more than 2 or 3 hours each.

**Comment by ZhilkinSerg** [comment]
The major PITA is multiple tile overmaps and its savegame compatibility.

**Comment by Coolthulhu** [comment]
> we would have to make a separate issue for each mapgen function to be JSONified to preserve credit for the bounty

Sounds fine to me. Those specials are huge - for example, prison is over 1k lines.

**Comment by Leland** [comment]
Yup, multiple issues and then probably a project to associate them all. It's the same thing that was done for the  Z-index feature.

**Comment by ZhilkinSerg** [comment]
There are only 16 buildings left in the [mapgen_functions.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mapgen_functions.cpp) save for specials like sewer, roads, subways, rivers, caves, etc.

* parking_lot
* s_gas
* church_new_england
* church_gothic
* s_pharm
* s_sports
* shelter - #20770
* shelter_under
* lmoe
* office_doctor
* sub_station
* s_garage - #21138
* police
* bank
* pawn
* mil_surplus

More is in [mapgen.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mapgen.cpp): 

* office_tower_1_entrance
* office_tower_1
* office_tower_b_entrance
* office_tower_b
* lab
* lab_stairs
* lab_core
* ice_lab
* ice_lab_stairs
* ice_lab_core
* lab_finale
* ice_lab_finale
* outpost
* silo
* silo_finale
* temple
* temple_stairs
* temple_finale
* sewage_treatment
* sewage_treatment_hub
* sewage_treatment_under
* mine_entrance
* mine_shaft
* mine
* mine_down
* mine_finale
* spiral_hub
* spiral
* radio_tower
* station_radio_east
* station_radio_north
* station_radio_west
* prison_1 - #20408
* prison_2 - #20408
* prison_3 - #20408
* prison_4 - #20408
* prison_5 - #20408
* prison_6 - #20408
* prison_7 - #20408
* prison_8 - #20408
* prison_9 - #20408
* prison_b_entrance - #20408
* prison_b - #20408
* office_doctor_east
* office_doctor_north
* office_doctor_west
* toxic_dump
* haz_sar_entrance
* haz_sar
* haz_sar_entrance_b1
* haz_sar_b1
* megastore_entrance
* megastore
* hospital_entrance
* hospital
* mansion_entrance - http://smf.cataclysmdda.com/index.php?topic=13630.0
* mansion - http://smf.cataclysmdda.com/index.php?topic=13630.0
* fema_entrance
* fema

**Comment by ZhilkinSerg** [comment]
There are only 16 buildings left in the [mapgen_functions.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mapgen_functions.cpp) save for specials like sewer, roads, subways, rivers, caves, etc.

* parking_lot
* s_gas
* church_new_england - https://www.dropbox.com/s/6p1zt8ifstrzsve/mapgen_church%26office_doctor.zip?dl=0
* church_gothic - https://www.dropbox.com/s/6p1zt8ifstrzsve/mapgen_church%26office_doctor.zip?dl=0
* s_pharm
* s_sports
* shelter - #20770
* shelter_under
* lmoe
* office_doctor - https://www.dropbox.com/s/6p1zt8ifstrzsve/mapgen_church%26office_doctor.zip?dl=0
* sub_station
* s_garage - #21138
* police
* bank
* pawn
* mil_surplus

More is in [mapgen.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mapgen.cpp): 

* office_tower_1_entrance
* office_tower_1
* office_tower_b_entrance
* office_tower_b
* lab
* lab_stairs
* lab_core
* ice_lab
* ice_lab_stairs
* ice_lab_core
* lab_finale
* ice_lab_finale
* outpost
* silo
* silo_finale
* temple
* temple_stairs
* temple_finale
* sewage_treatment
* sewage_treatment_hub
* sewage_treatment_under
* mine_entrance
* mine_shaft
* mine
* mine_down
* mine_finale
* spiral_hub
* spiral
* radio_tower
* station_radio_east
* station_radio_north
* station_radio_west
* prison_1 - #20408
* prison_2 - #20408
* prison_3 - #20408
* prison_4 - #20408
* prison_5 - #20408
* prison_6 - #20408
* prison_7 - #20408
* prison_8 - #20408
* prison_9 - #20408
* prison_b_entrance - #20408
* prison_b - #20408
* office_doctor - https://www.dropbox.com/s/6p1zt8ifstrzsve/mapgen_church%26office_doctor.zip?dl=0
* office_doctor_east - https://www.dropbox.com/s/6p1zt8ifstrzsve/mapgen_church%26office_doctor.zip?dl=0
* office_doctor_north - https://www.dropbox.com/s/6p1zt8ifstrzsve/mapgen_church%26office_doctor.zip?dl=0
* office_doctor_west - https://www.dropbox.com/s/6p1zt8ifstrzsve/mapgen_church%26office_doctor.zip?dl=0
* toxic_dump
* haz_sar_entrance
* haz_sar
* haz_sar_entrance_b1
* haz_sar_b1
* megastore_entrance
* megastore
* hospital_entrance
* hospital
* mansion_entrance - http://smf.cataclysmdda.com/index.php?topic=13630.0
* mansion - http://smf.cataclysmdda.com/index.php?topic=13630.0
* fema_entrance
* fema

**Comment by ZhilkinSerg** [comment]
Buildings with computers cannot be jsonized until #20770 will be merged.

**Comment by ZhilkinSerg** [comment]
Some of the buildings (like `mil_surplus`) are generated in random sizes - it is not possible to reimplement in json now.

**Comment by Leland** [comment]
@ZhilkinSerg yeah, I'd noticed that! Do we feel that it's good to keep those randomly generated buildings, or should we transition them to static JSON structures?

Doing so _would_ mean we lose out on the dynamic nature that the current hardcoded implementation brings, but we'd have a much more manageable (and standardized) codebase as a result.

**Comment by 1skandar** [comment]
The big one is going to be the lab. Individual rooms won't be hard, but I'm not even sure how, or even if, the current JSON format can put it together correctly.

**Comment by ZhilkinSerg** [comment]
Example of lua mapgen (): https://www.dropbox.com/s/pm8rpd1bhkhu9f5/cdda_lua_mapgen_example.zip?dl=0

Replaces `dojo` building with lua-generated house.

Also see http://smf.cataclysmdda.com/index.php?topic=14258.0.

**Comment by Leland** [comment]
Do note https://github.com/CleverRaven/Cataclysm-DDA/issues/20819, though.

We probably won't want to move map generation to be dependent on tech that's being sunsetted.

**Comment by ZhilkinSerg** [comment]
I guess, LUA won't be removed if it will be actually used.

**Comment by ZhilkinSerg** [comment]
`mil_surplus` mapgen in LUA: https://www.dropbox.com/s/3gn2p4sgmt5gdmz/cdda_mapgen_mil_surplus.zip?dl=0

Please don't afraid excess amount of loot - i didn't add check for loot spawn chances yet.

**Comment by kevingranade** [comment]
> I guess LUA won't be removed if it will be actually used.

Incorrect, there is still not a compelling case for LUA, and I don't intend to accept any new LUA functionality.

A note on the mapgen/bountysource issue.
One, you probably do need to post separate bounties on separate chunks of mapgen.
* First, if you post one for "convert all of mapgen", it would be almost impossible to allocate the bounty since bountysource won't split it for you.
* Second, it would never be claimable, since there are pieces of mapgen that will remain defined in C++ indefinitely (and that's ok).
Two, you should post the issues and wait for confirmation before backing them with cash, if for example someone posted a bounty for moving lab generation to either JSON (which would remove much of the dynamic generation features of labs) or LUA (which will not be merged), they would probably be rather disappointed to find out that it will never be claimed.  Similarly houses are almost certainly not going to be converted.

**Comment by ZhilkinSerg** [comment]
Four overmaps converted to LUA - https://www.dropbox.com/s/rlgitvrk9hoo49r/cdda_lua_mapgen_v2.zip?dl=0:

- `s_pharm`
- `s_sports`
- `mil_surplus`
- `sub_station`

**Comment by ZhilkinSerg** [comment]
LUA mapgen has major drawback - it seems that lua-generated buildings aren't automatically rotated. There is possibly a workaround with using `overmap_specials.json`, but I didn't find it yet.

**Comment by kevingranade** [comment]
Question seems to have been answered, closing.
