### ISSUE TITLE
Noise level caused by collision of vehicle board

### ISSUE THREAD

**Issue by Anongh** [CleverRaven/Cataclysm-DDA#21213]
I accidentally threw a cigarette butt in the car and crashed to the heavy duty board and this noise level was 17.  The cabbage seed also produced the same result. It was also 17 when it hit my broadsword.

The cigarette butt did not make any noise on the windshield, quarterpanel and the door.

**Comment by TealcOneill** [comment]
I've just tested this out on 0.F-2 and it no longer makes a noise but it does give the "You hear crash!" text in the log.

**Comment by I-am-Erk** [comment]
Per above comment this seems resolved, please let me know if it is still valid and I will reopen
