### ISSUE TITLE
Anthills generate unexpected straight edges

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#21222]
[Build 6504] Similar issue to #20417. In the following picture, I came across an anthill and decided I would explore it to see if it can find the queens chamber or other interesting items, I came across this strange flat edge where my character is and found a single subway tile, so I figured it was just right up against a subway. I found it odd that one subway tile was accessible via the anthill and the rest were as they should be. I decided to reveal the map to see if the flat edge problem was happening to the nest north of the current one that I found, and indeed, there are tons of nests all showing this strange straight edge and vertical line formation. 

![capture](https://user-images.githubusercontent.com/24307650/27037797-03ce337a-4f57-11e7-9ecb-009cc6f37769.PNG)

Strange subway picture where my character is in the picture above (southern most nest):

![capture2](https://user-images.githubusercontent.com/24307650/27037851-39ed5896-4f57-11e7-8556-f7b9b31f685b.PNG)

**Comment by kevingranade** [comment]
The flat edge is certainly a symptom, but if you look st the rest of the anthills you've revealed, they all have a similar strange shape, something about their generation is seriously messed up.

**Comment by CoroNaut** [comment]
Maybe it will help in diagnosing the problem: the entrance to all the anthills were exactly in the center of that + shape that you see within each anthill. I previously marked one with the green "<" to the next of the map selection marker.

**Comment by kevingranade** [comment]
Thanks for the confirmation, that's what I expected, that + marks the origin of the hill, it should be spreading out equally in all directions, but isn't.

**Comment by DangerNoodle** [comment]
Increase in anthill spawning due to https://github.com/CleverRaven/Cataclysm-DDA/pull/21136 would explain why this issue has become more visible, but I would hope that increased spawns did not create or worsen this?

Either way, your screenshots indicate to me that I have severely neglected to consider how large the underground tunnels are. A maximum of ten may now be far too many due to their resulting density, five might be better. At least, now that they spawn reliably.

**Comment by CoroNaut** [comment]
[Build 6521] Recently found this. This kind of antill generate a massive scale network (way too big by the way) but generates them all completely unconnected (2nd picture):
![capture](https://user-images.githubusercontent.com/24307650/27317745-72a5dd84-5556-11e7-896b-7c2838361699.PNG)
![capture](https://user-images.githubusercontent.com/24307650/27317779-bcb17a1e-5556-11e7-8e40-9f5ee08e9824.PNG)
