### ISSUE TITLE
Too Many Beehives Spawning

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#21240]
[Build 6504] I don't know if this is intentional but there are really a lot of beehives:
![capture](https://user-images.githubusercontent.com/24307650/27144294-3f2e4cf8-50ff-11e7-80cc-c35eb13e895c.PNG)

**Comment by Leland** [comment]
Pinging @DangerNoodle, who adjusted their spawning.

**Comment by ZenZen2** [comment]
Do you use any mods that alter overmap specials?

**Comment by DangerNoodle** [comment]
Problem is likely same as with anthills. I lowered the maximum allowed spawns for these from what was originally a massive number, but even afterward it appears that the maximum is very easily filled.

**Comment by DangerNoodle** [comment]
Correction, I will have to set this up later on, as something came up.

**Comment by CoroNaut** [comment]
No mods except from no religious texts and no old guns.
