### ISSUE TITLE
Sorting rules in "wish for an item" debug menu are weird.

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#21245]
They look like a totally disorganized jumble. Why is the L39B-45 even at the top?

**Comment by kevingranade** [comment]
It's probably by item id, not name.
I'm closing as this doesn't report a big, this sort of thing is more suited to the forums.

**Comment by BorkBorkGoesTheCode** [comment]
@kevingranade if by item id you mean "id": "l_mp_45" they aren't sorted that way either.

First few IDs:

l_mp_45
20x66_bootleg_flechette
small_storage_battery
medium_storage_battery
offset_sights
riv_suppressor
pipe_double_shotgun
carbine_flintlock_double
l_mp_9mm
mosin44
m14ebr
ruger_lcr_22
iv_mutagen_ursine   . . .  (some other serums follow this)
human_cooked
human_flesh
hstomach_large
mag_animecon

Each ID has a number prepended to it with a value from 0 to apparent infinity.
