### ISSUE TITLE
Can't fill vehicle tanks with cold water

### ISSUE THREAD

**Issue by hagamablabla** [CleverRaven/Cataclysm-DDA#21246]
When I have a bottle of cold water, I can't fill any storage tank with it, whether it's empty or has water in it. I've tried this on multiple vehicle storage tanks, and I made sure the tank could hold normal water before trying it with cold water.

**Comment by ZenZen2** [comment]
I think you are the first person that ever attempted to do that :p
Correct me if im wrong, but i think this isnt supported yet.

**Comment by hagamablabla** [comment]
Well, it's not too big a deal anyways, since you can just leave it out for an hour or two.

**Comment by Graywolfe813** [comment]
I recall someone speaking about this happening with hot liquids as well.

**Comment by kolsurma** [comment]
The ideal change to liquids would be to track their temperature, currently it's a tag that's set meaning there's no real way to average their temperatures together.

**Comment by CoroNaut** [comment]
The cold water would always default to the outside temperature unless you had it insulated and properly heated/cooled like a house hot water tank.

**Comment by PlasmaChroma** [comment]
I had a lot of problems adding hot coffee to a vehicle tank.  This one is quite annoying as the time it takes to cool sufficiently is significantly longer than the coffee simply losing the (hot) text.  Even after the text is gone apparently the temperature hasn't normalized to whatever "standard" is.

**Comment by Night-Pryanik** [comment]
It seems that active liquids (including hot and cold) are deliberately forbidden for filling the tanks:
https://github.com/CleverRaven/Cataclysm-DDA/blob/1bd9a87f2ea75976634e7fc33158575cb08519b6/src/game.cpp#L9859-L9860
As stated by @kevingranade in #18570, the reason for this restriction is invalid. Should the check for active liquids be removed then?
