### ISSUE TITLE
10" small wheels could use and adjustment

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#21256]
I think 10" small wheels should be either foldable or take only a few minutes to install/remove.

Specifically I like to make a foldable backup vehicle I can throw in the trunk of an exploration motorbike in case it runs into trouble, but bicycle tires are extraordinarily rare (1 or 2 per large city at most in my experience).  Looking for a more common alternative (something small enough to cart around and easy enough to put on if you need a quick escape after crashing) the small wheels are almost a good fit, except they take almost an hour to install a pair which seems excessive.

Given that they're the size of tire you'd find on a wheelbarrow I don't see why they can't be considered foldable, but if we aren't ready to add that, then IRL I'm pretty sure it wouldn't take someone with mechanics 6 an hour to install a pair of them.

**Comment by CoroNaut** [comment]
My world is 200MB right now and I have not found a single bicycle. I am in the same boat. I fully agree that there should be more options for this type of travel and perhaps for the foldable parts to get an official upgrade into cata. Only time will tell.

**Comment by Xpyder** [comment]
Initially I was hoping that too, but I think foldable parts requires vehicle additions which was outdated last I checked.  It did add a lot of sensible changes so hopefully someone can eliminate the dependency or update v-add

**Comment by Graywolfe813** [comment]
Folding parts has no dependencies, and small wheels are inckuded in it's list of foldables.

**Comment by Mecares** [comment]
A bike shop would be a nice addition to the game

**Comment by kevingranade** [comment]
Considering your goal, its a LOT more reasonable to just up the spawn rate of bicycles.

**Comment by Xpyder** [comment]
>Considering your goal, its a LOT more reasonable to just up the spawn rate of bicycles.

That would work for me, and likely be preferential; although the balancing for that seems like more work than adjusting down the install time of small wheels (unless that timing is determined by some of the older code that's hard to dig through)

**Comment by kevingranade** [comment]
We really don't have any balance around vehicle spawn rates, just spawn a
bunch of bikes scattered around towns using the usual vehicle spawn method
(insures a lot of them are broken) and call it a day.
