### ISSUE TITLE
Electromagnetic Unit CBM is a great way to die

### ISSUE THREAD

**Issue by Graywolfe813** [CleverRaven/Cataclysm-DDA#21252]
Using the electromagnet cbm causes objects to strike the player in the head. Not exactly pretty if you use it to recover a large stack of throwing knives.

I'm assuming this isn't intended behavior, since the description states the device is implanted in the hand.

**Comment by CoroNaut** [comment]
I came across this as well, i accidentally pressed the button in the middle of my base and every metal thing in there just went flying towards my characters body.

**Comment by TheCatWizard** [comment]
I agree that this is not how it should be; no reasonable individual would ever manufacture this bionic to begin with if it was so masochistic in design.

**Comment by Treah** [comment]
@TheCatWizard Don't be so sure...... There are portable water heaters that are sold that plug into a wall and screw into a showerhead.....

**Comment by Coolthulhu** [comment]
I think at the point this CBM was last changed, it was impossible to hit self with a ranged attack. That later changed.

**Comment by flitvious** [comment]
Maybe the attack should target the tile next to player instead of the tile the player is actually standing on?
