### ISSUE TITLE
PARTIAL_DEAF flag broken

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#21267]
0.C 22346 windows console and beyond.

The PARTIAL_DEAF flag no longer has any visible effect on noise. Firing an M4 is just as loud with a power armor helmet as without.

**Comment by DangerNoodle** [comment]
Does deafness occur, or does this only affect reported noise?

**Comment by BorkBorkGoesTheCode** [comment]
Reported noise.

**Comment by BorkBorkGoesTheCode** [comment]
I'm going to close this in favor of creating a discussion thread to discuss the game's current sound display.
