### ISSUE TITLE
tools and UPS conversion mods

### ISSUE THREAD

**Issue by Tsunder** [CleverRaven/Cataclysm-DDA#21260]
not sure how else to put this
1. attach ups conversion mod to a tool (e.g., tazer)
2. recharge ups'd tool (amount doesn't matter)
3. % -> attach as toolmod and select another tool (e.g., electric jackhammer)
4. an error occurs*
5. original tool's now has normal battery charges, and second tool now has ups mod and both can be used as normal
6. profit!

this cannot be done with % remove tool mod because the ups conversion mod cannot be removed whilst it still has charges. (in game message "can't unload a rechargable $tool+ (UPS)!")

* "tried to consume charges for non-tool, non-food, non-med item" , player::consume_charges player.cpp, line 8708

**Comment by Tsunder** [comment]
removing a UPS from a tool should probably be allowable, and set the battery level to zero (or make the battery level follow the the ups conversion mod), as otherwise getting the battery level of the tool to zero may take a while

**Comment by CoroNaut** [comment]
A ups conversion mod runs off of battery power supplied by your internal bionic power supply or a standard UPS or advanced UPS. They simply allow all tools with the conversion mod to run off of a single power source for more convenient management. UPS stands for Universal Power Supply.

**Comment by Graywolfe813** [comment]
So, a simple question, then. What is storing the power in a UPS modded device? The original battery supply, or the UPS mod?

If the former, then there is no reason to restrict removing the mod, AND the power supply should remain at whatever level it was at upon removal. 

if the latter, then it would make more sense for UPS mods to provide the power cap, and carry the charges when removed if possible.

Or maybe just remove storage on UPS tools altogether and require a UPS, and be consistent with devices that run off UPS by default?

**Comment by Coolthulhu** [comment]
Currently the UPS mod uses tool's own capacity.
Honestly it is rather inconsistent. It essentially provides an arbitrarily large rechargable battery.

The problem is, the crafting system does not support "translating" UPS modded tool charges into UPS charges directly. And it's not as simple as converting one to the other, at least not without handling a bunch of edge cases.

**Comment by Graywolfe813** [comment]
Ah, I was more asking along of what the UPS mod really is and does, in terms of the game world. Is it a battery device, or just an adapter?

**Comment by Coolthulhu** [comment]
Currently both.
Ideally it would only be an adapter.
