### ISSUE TITLE
Json mapgen caused crash

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#21266]
The lines

```
"place_loot": {
    "#": { "item": "existing_item_id" }
}
```

Don't trigger a debug error when the game loads but will cause a crash when the player approaches the offending map.

**Comment by ZhilkinSerg** [comment]
As far as I know it should be like this:

````
"place_loot": {
    "#": { "item": "existing_group_item_id" }
}
````
