### ISSUE TITLE
Crash in advanced inventory

### ISSUE THREAD

**Issue by Aivean** [CleverRaven/Cataclysm-DDA#21270]
I'm getting a crash using advanced inventory in the latest experimental (tiles build, downloaded from dev.narc.ro/cataclysm/jenkins-latest/OSX/Tiles/).

I've spent some time trying to find exact steps to reproduce, but it seems that bug has a bit of floating nature to it.

Here are some vague instructions of how to reproduce the crash:
* open advanced inventory
* select `I`/`W`/`A` in both tabs
* use `f`ilter  for one of the tabs  (important!)
* start switching `I`/`W`/`A`
* after several switches game crashes

![cata_bug](https://user-images.githubusercontent.com/2865203/27258771-4d3cde2a-53b8-11e7-94d7-d3fb83bb23b9.gif)

[crash dump](https://gist.github.com/anonymous/34379d2b1ca0ed72be9a73518111ec13)

This bug is not related to any particular item or world, I reproduced it on freshly created world.

---

I would be happy to try and fix it, but I lack C++ skills for debugging crashes. If someone can understand what's going on and give me a hint where to look at I certainly can try submitting pull request.

**Comment by ZeGentzy** [comment]
I can't reproduce one Arch Linux.  Could you try recompiling CDDA with debug enabled and re uploading the crash dump, that will help us know where it crashed.

**Comment by Aivean** [comment]
@ZeGentzy will do tomorrow. Thanks!

**Comment by Aivean** [comment]
@ZeGentzy strangely enough I can't reproduce it either on the self-compiled version. I guess issue can be closed then.
