### ISSUE TITLE
Thread only available for crafting if not loaded in needle (exp 0.C-6488)

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#21276]

**Comment by DangerNoodle** [comment]
See pull request https://github.com/CleverRaven/Cataclysm-DDA/pull/20569, pinging @ZhilkinSerg due to yet another issue opened concerning the problem they have been unable to fix for roughly four months.

Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/20983
