### ISSUE TITLE
Ammo belt links missing from survivor last stand basement

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#21273]
Why shouldn't there be any .308 ammolinks sitting alongside the 308 casings?

**Comment by Night-Pryanik** [comment]
By "survivor last stand basement" you mean LMOE?

**Comment by BorkBorkGoesTheCode** [comment]
Nope. basement_survival is what I mean't

**Comment by Taberone** [comment]
BorkBork means the basement with this very specific layout every time: Two stairs, a bunch of crates and water, a corpse, a damaged M60, rack full of handloaded ammo in the back.  It randomly spawns below regular houses.
