### ISSUE TITLE
[Chesthole tileset] 43 Standing mirror and 44 broken standing mirror are swapped

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#21279]
![chesthole_mirror](https://user-images.githubusercontent.com/1931904/27295496-d738c42c-5525-11e7-8448-694c7231f819.png)

**Comment by DangerNoodle** [comment]
Also observed: vehicle part `hdhatch` uses sprites for a broken glass-paneled hatch of some sort when closed, and the open variant of the same when opened. I have not yet examined what broken variants appear as.

**Comment by Chezzo** [comment]
Thanks for letting me know, @DangerNoodle. 

There is a multitile for open with vehicle parts, and a different one for broken, so the json looks like this:

          "id": "vp_hdhatch",
          "fg": 2719,
          "rotates": true,
          "multitile": true,
          "additional_tiles": [
            {
              "id": "broken",
              "fg": 2720
            },
            {
              "id": "open",
              "fg": 2721
            }

**Comment by DangerNoodle** [comment]
I see. Regardless, if I could recall the exact sprite used for `hdhatch` in other tile sets that use the same style for vehicles, I would advocate that.

**Comment by AMurkin** [comment]
#18533 partially fixed it - in iso tileset only.
ping @Chezzo
