### ISSUE TITLE
Frostbite causing numbness in hands should affect dexterity (exp 0.C-6488)

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#21275]

**Comment by 11132113** [comment]
Dexterity reflects more than the character ability to use his hands (dexterity affects dodge rolls for example).
Wouldn't a malus to hand encumbrance and/or unability to craft be more suited ?

**Comment by kevingranade** [comment]
Extra hand encumbrance sounds perfect imo.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
