### ISSUE TITLE
moving a wood stove with a fire on the tile does not move the fire

### ISSUE THREAD

**Issue by Tsunder** [CleverRaven/Cataclysm-DDA#21283]
while not exactly a bright idea, it should be possible to move a lit wood stove/brazier without burning the rest of the building down

supposedly this means that the fire is burning in the same tile but not on the fire ring/stone fireplace or whatever

![image](https://user-images.githubusercontent.com/5103517/27313088-1087cd04-553a-11e7-952a-806afcd3aa94.png)

**Comment by ZeGentzy** [comment]
You cant grab (Shift-G) a brazier, the only thing I'm aware of which you can grab and slide is the wood stove.

Also congrats on reporting the bug, I swear I was going to report it myself eventually. :)

**Comment by ZhilkinSerg** [comment]
You could move the stove back to its place ...

**Comment by pabrams** [comment]
Why isn't brazier movable?  Is it because it's a tool? Why does it get 'placed securely' - the braziers I know about in real life don't have any way to be 'securely' placed - they just stand there and you can move them around (carefully).

**Comment by ZhilkinSerg** [comment]
Actually brazier is a trap codewise and traps cannot be moved - only disassembled.

**Comment by pabrams** [comment]
Okay, so is there a reason why it's an unmoveable trap instead of moveable furniture?  Is this a variety of brazier that gets bolted to the floor?

**Comment by Coolthulhu** [comment]
It's probably a leftover from some old system where traps couldn't be deployed. Could be safely converted to furniture.

Nowadays the only reason to keep some not-actually-traps as traps and some as furniture would be to allow them to share a tile. But brazier should not share tiles with chairs and tables.

**Comment by Night-Pryanik** [comment]
I almost solved this issue (kinda). I managed to make fire inside ovens move with them. Pushing and shifting furniture with contained fire works just fine. Pulling it works too, but the character gets ablazed first for some reason.

The question is: should I open my not-so-perfect-working-PR? I would greatly appreciate if someone helps me with my trouble.

**Comment by Coolthulhu** [comment]
> The question is: should I open my not-so-perfect-working-PR? I would greatly appreciate if someone helps me with my trouble.

Go for it.
I think I know why you're getting ablaze here - you move the fire before/after the move. What you need to do is either change the time you move fire depending on direction (ugly) or move the fire by remembering it, removing it, and then placing it back in the new spot (more code, but safer).

Remember to move the fire age too, and not just intensity. Otherwise moving the fire will make it last longer.

**Comment by Night-Pryanik** [comment]
> move the fire by remembering it, removing it, and then placing it back in the new spot (more code, but safer).

That's the way I tried. My attempt is at #21338.

**Comment by RogueYun** [comment]
> You could move the stove back to its place ...

You can actually do this, but with the brazier...

You gotta move all the firewood that was also left behind out of the way first. Not sure if that was an intentional difference with the brazier vs the wood stove, but it is a difference between the two.
