### ISSUE TITLE
GCC 5.4.0 doesn't like src/iexamine.cpp

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#21285]
As seen in, e.g., <http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/Graphics=Tiles,Platform=Windows_x64/6525/console>:
```
08:36:50 ccache /home/narc/mxe/usr/bin/x86_64-w64-mingw32.static-g++  -DRELEASE -DCROSS_LINUX -DGIT_VERSION -DTILES -DLOCALIZE -ffast-math -O3 -Wall -Wextra -fsigned-char -Werror -std=c++11 -MMD -m64 -I/home/narc/src/mxe/usr/x86_64-w64-mingw32.static/include/SDL2 -I/home/narc/src/mxe/usr/x86_64-w64-mingw32.static/include -DSDL_SOUND -DLUA -I/home/narc/src/mxe/usr/x86_64-w64-mingw32.static/include/SDL2 -I/home/narc/src/mxe/usr/x86_64-w64-mingw32.static/include/SDL2 -I/home/narc/src/mxe/usr/x86_64-w64-mingw32.static/include/libpng16 -I/home/narc/src/mxe/usr/x86_64-w64-mingw32.static/include -I/home/narc/src/mxe/usr/x86_64-w64-mingw32.static/include/SDL2 -I/home/narc/src/mxe/usr/x86_64-w64-mingw32.static/include/freetype2 -I/home/narc/src/mxe/usr/x86_64-w64-mingw32.static/include -c src/iexamine.cpp -o objwin/tiles/iexamine.o
[...]
08:37:03 src/iexamine.cpp: In function 'void iexamine::fswitch(player&, const tripoint&)':
08:37:03 src/iexamine.cpp:1298:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
08:37:03  void iexamine::fswitch(player &p, const tripoint &examp)
08:37:03       ^
08:37:03 cc1plus: all warnings being treated as errors
```

For reference, #21255 disables this specific warning in mingw builds, but gcc 5.4.0 is not exactly old (dated 2016-06-03 per <https://ftp.gnu.org/gnu/gcc/gcc-5.4.0/>) and we should consider refactoring the code that's getting inlined so it doesn't trigger a "might overflow signed int" situation.

I'm also not at all convinced it's mingw specific (unlike the internal compiler error worked around by #15066, updated in #19440, that resulted in <https://github.com/CleverRaven/Cataclysm-DDA/blob/master/Makefile#L191-L197>).

Notably, the same compiler doing a 32-bit build is unaffected by this (see <http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/Graphics=Tiles,Platform=Windows/6525/console>), so it's probably a 64-bit optimization going awry.

**Comment by kevingranade** [comment]
We certainly claim support for MinGW 4.9.0+ https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILER_SUPPORT.md

Weird error message, it can't find the line where it's happening?

**Comment by kevingranade** [comment]
Looks like #21286 does the trick.  This is a bit concerning because it implies that the following:
```
tripoint tmp = examp; // examp is also a tripoint
```
results in tmp being an alias of examp, or at least some compiler versions thinking it is.  A quick glance at enums.h (where tripoint is defined) indicates that it declares default reference and move constructors, but no copy constructor.  I would have *thought* this would dispatch to the (still implicitly created) copy constructor, but if this isn't happening we potentially have broken code scattered around due to this kind of construct unexpectedly creating references instead of copies.

**Comment by kevingranade** [comment]
After rummaging around a bit more, tripoint tmp = examp; DEFINITELY does not overload to the move constructor, since examp is not an xvalue (see https://stackoverflow.com/questions/9152798/c11-move-copy-construction-ambiguity).
As such, I'm inclined to believe this is actually a bug in mingw.

**Comment by narc0tiq** [comment]
I'm pretty sure this is all unrelated to the %zu change, since that was reverted ages ago.

I'm willing to call it a bug, yes, but I'd like to try it on a native g++ 5.4.0, too.

**Comment by narc0tiq** [comment]
So I picked up a g++ 5.4.0 (specifically `g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609`) to do a 64-bit build and... not really a problem. Must be a MinGW issue. Wouldn't be the first one.
