### ISSUE TITLE
RC car+atomic mod bug

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#21284]
1. Wish for RC car
2. Wish for atomic battery mod
3. Attach atomic battery mod to RC car (doesnt need plutonium)
4. Turn on RC car (whether it has a charge or not- it still bugs out)
After the fourth step you will notice the RC car will have 2 plus signs next to it indicating 2 attached mods.
5. Place RC car on ground (turn if off, etc)
Pick it back up and you will now notice it has 3 plus signs and have the effective plutonium capacity of 50 million charges. Trying to activate the RC car again will do... nothing, no debug message or anything.

I found this out when... testing (not playing with :D) the RC car. If you get my drift :D

**Comment by raymoo** [comment]
>If you get my *drift*

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed.

**Comment by CoroNaut** [comment]
@Night-Pryanik This is still a bug and still completely reproducible using my steps as of 0.c-31146-g4dd8ad1 the latest release.

**Comment by Night-Pryanik** [comment]
No longer an issue after #30192.
