### ISSUE TITLE
Debug Life Support does not fully hold hunger/thirst/tiredness steady 

### ISSUE THREAD

**Issue by TheCatWizard** [CleverRaven/Cataclysm-DDA#21291]
I don't know if this is intentional or not, but Debug Life support only stops the normal hunger/thirst/sleep clock, and doesn't prevent things like illness or heat or radiation from affecting these values.

**Comment by Coolthulhu** [comment]
I'd say intended.
This allows measuring those changes precisely.

The only thing I'd change here would be having it also prevent hunger/thirst death.

**Comment by DangerNoodle** [comment]
If such a change is made, maybe it should at least print a "you should be dead by now" message so that the tester will know when that point is reached, if non-timer hunger/thirst changes are retained for informational purposes.

**Comment by TheCatWizard** [comment]
Could always make a second debug mutation that just sets them to full every hour or something, but I don't know how hard that would be.

**Comment by kevingranade** [comment]
We have waaaay too many feature requests and bug reports to entertain issues about debug features.
