### ISSUE TITLE
Estoc listed incorrectly on crafting menu

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#21307]
Version: 0.C-22732-g758fd33 (tiles)
Build: 6537
On the crafting menu the estoc is on the cutting weapons category despite being a piercing weapon.

On another note, I'm not sure if this is a bug in the game, but to control vehicles I need to press ^ twice, I changed to another key (page down) and it works fine, I remember the ^ working fine since I last played (that was 7 - 9 months ago)

**Comment by DangerNoodle** [comment]
It would be prudent to open a separate issue for the latter.
