### ISSUE TITLE
Write better documentation for translators

### ISSUE THREAD

**Issue by franzzapata** [CleverRaven/Cataclysm-DDA#21308]
Since there's a web translation system in place, `CONTRIBUTING.md` should be updated with links to the translation project and to the `TRANSLATING.md` document. Also, the latter should contain a guide for translators and, in general, be updated with current information.

Original text:
> Hello, I've noticed that most (if not all) of the translation work is done by a couple of people, and, not to diminish their work, but I think using a web translation tool would attract more contributors to the translation effort, or at least make the current translators' work easier.
>
> These sort of tools would allow people who are not comfortable using `git` and `gettext` directly to suggest and review translations using a web interface, without having to partake into the black magic of the translation scripts.
>
> I know two platforms which provide free hosting for open source projects:
>
> * [Weblate](https://weblate.org/)
> * [Transifex](https://www.transifex.com/)
>
> Out of these, I would prefer Weblate, since their offer for open source projects is more explicit, and I know Minetest, other free game using `gettext`, is using it succesfully.

**Comment by BorkBorkGoesTheCode** [comment]
There is already a Cataclysm translation group using Transifex.

@BrettDong could you explain?

**Comment by franzzapata** [comment]
I see, my bad. Still, this ought to be documented, no?

I posted this issue because I was under the impression there wasn't any translation solution in place, since the `CONTRIBUTING.md` document only mentions the manual way of translating.

I'd be glad to add information about this to the document, but I don't know where or how the translation work is happening.

**Comment by kevingranade** [comment]
Thanks for bringing this up, it does need to be documented.
https://www.transifex.com/cataclysm-dda-translators/cataclysm-dda/ is the tx project.
I don't actually have a good overview of the process myself other than import and export.

**Comment by franzzapata** [comment]
Nice! I'll add a link to `CONTRIBUTING.md` document.

Also, I just noticed there already is a `TRANSLATING.md`, but I think it still could use some touch ups, like a small "Translator's guide", and removing the references to Launchpad since, for all I can tell, that project hasn't seen an update in years

I'll open a PR later. Also, I'm going to change the issue title to something more pertinent.
