### ISSUE TITLE
Replace press and die set with food processor in FOODCO unit

### ISSUE THREAD

**Issue by Maddremor** [CleverRaven/Cataclysm-DDA#21312]
Since the die and press set no longer have an internal battery supply, it's inclusion in the FOODCO unit seems redundant. I suggest replacing it with the food processor, which also makes more sense to have in a kitchen accessory.

**Comment by DangerNoodle** [comment]
Though the claim that it can also handle handloading, which the item description notes is "for some insane reason," seems to be part of the item flavor. It is presumably meant to be a humorous addition.

**Comment by Maddremor** [comment]
I get the joke and has nothing against it. I'm rather coming from a gameplay viewpoint.

**Comment by AlecWhite** [comment]
>I'm rather coming from a gameplay viewpoint.

If it's for that you could just add the food processor and leave the press and die set as it is.

**Comment by Maddremor** [comment]
> If it's for that you could just add the food processor and leave the press and die set as it is.

True, I guess. But consider the fact that with soley the FOODCO, you can't actually handload bullets as it lacks a heat source. There is no mechanical difference between the current FOODCO and a die and press set laying in a trunk when it comes to handloading. I would rather have a separate rig consisting of a press and die set, a bullet puller, a hotplate, and a gunsmith repair kit.

**Comment by Maddremor** [comment]
Come to think about it, if you want the "guns in the kitchen" joke, while still being useful, you could replace the press with a firearm repair kit as it is battery powered and has no way besides UPS to charge from a vehicle.

**Comment by DangerNoodle** [comment]
The fact that it needs a separate kitchen unit is also overtly stated. Replacing it with a firearm repair kit might be more beneficial to players though. That would also expand upon both flavor details by making it more capable (as-is) as a firearm maintenance tool than as a kitchen tool.

**Comment by Tharn** [comment]
There's also already some overlap in usability between the onboard chemistry lab and the kitchen buddy. I'd rather not see yet another piece of rig that takes up another vehicle slot.  IMO:

Remove the ammo stuff from the kitchen buddy and replace them with sensible kitchen alternatives, such as a food processor. Add ammo stuff to chemistry lab since it doesn't really have a lot of utility right now.

**Comment by Cyrano7** [comment]
Food possessor added to FOODCO kitchen buddy recipe in https://github.com/CleverRaven/Cataclysm-DDA/pull/21450
