### ISSUE TITLE
targetted reach attacks cannot be made with weapons with ammo

### ISSUE THREAD

**Issue by Tsunder** [CleverRaven/Cataclysm-DDA#21328]
or rather, guns with reach techniques.
example weapon (qiang from medieval stuff mod):
![qiang_from_medieval_stuff_mod](https://user-images.githubusercontent.com/5103517/27671202-43689abe-5c60-11e7-9278-fb97f40cb39d.png)

using autoattack melee works for reach, but [f]ire only uses the shot, and if it's unloaded, prompts for reloading. Shift+F does nothing

ideally i think shift+F would switch the attack to reach instead of the ammo

**Comment by DangerNoodle** [comment]
That is a regression, not a feature request. Weapons with bayonets or other instances of the reach attack on ranged weapons used to have the option to switch to using the reach attack via firing.

I was going to link to an existing issue, but I am surprised that a bug this old has not been reported.

In addition, pinging @Night-Pryanik to correct tagging.

**Comment by BorkBorkGoesTheCode** [comment]
Have you tried changing firing modes using a Mosin EBR rifle with attached bayonet? What happened?

**Comment by lancewf** [comment]
I have a solution to fix this problem in this PR #26530
