### ISSUE TITLE
Compiling on Windows - DLLs not copied by distribute.bat

### ISSUE THREAD

**Issue by WraithCadmus** [CleverRaven/Cataclysm-DDA#21330]
It seems there's a step or two missing in the compiling instructions on Windows, but as one of the involved elements isn't in the repository I don't want to tread on any toes.

When you download the WinDepend folder there's an (unmentioned) batch file that puts all the DLLs together in `$PROJECT/WinDepend/bin/{x86,x64}/`.

However distribute.bat expects them to be in `$PROJECT/msvc-full-features/dll/`

Seems that the right solution would be to populate `$PROJECT/msvc-full-features/dll/` based on the architecture you just built for with a post-build-step of some sort.

Many thanks to @AlecWhite on the Discord channel for bearing with me.

**Comment by Alien-AV** [comment]
Why does the VS version require dlls, while "official" (I'm assuming cross-compiled) version doesn't?
Maybe this should be addressed instead? Are the dependencies compiled in statically in the "official" version?

At the same time the file size (at least in my attempt) of resulting .exe in VS is larger than the downloaded one (despite requiring more dlls to run).

**Comment by Alien-AV** [comment]
Apparently, static version of SDL and gettext should be compiled for this.
There's a tutorial regarding compiling SDL statically:
http://www.glusoft.com/tuto/SDL2-static-visual-studio.php

I didn't test whether it'll work yet.

**Comment by ZhilkinSerg** [comment]
You can now use `vcpkg` and [corresponding solution](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/msvc-full-features/Cataclysm-vcpkg.sln) to manage dependencies (see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING-VS-VCPKG.md).

Existing Visual Studio solution will be obsoleted in the future.
