### ISSUE TITLE
Random scenario on "Play Now!" to explore the game

### ISSUE THREAD

**Issue by jzambo** [CleverRaven/Cataclysm-DDA#21348]
With this simple change, new players will easier appreciate depth of the game with no-questions-asked "Play Now!" option. Yesterday you barely survived a helicopter crash as a bionic soldier, today you are a shower victim when there is freezing cold outside. 

Better than tearing courtains from shelter windows every time.

**Comment by Night-Pryanik** [comment]
@kevingranade said in #15757 that Play Now! shouldn't be fully random.

**Comment by DangerNoodle** [comment]
Do you not get higher randomness when selecting the "random character" option instead?

**Comment by ituluwituluwzev** [comment]
"Play Now!" is for one who tries the game for the first time, and doesn't want to spend 10 minutes to read document and gen a character, only to find out he doesn't like the game. So the game is presented in the most archetypal way: if you want to play this, you probably want to play the rest of the game.

There is also the "random character" option.

Feel free to reopen if there is new idea.

**Comment by kevingranade** [comment]
Agree with the feedback, play now is for beginners who want to try out core gameplay, not veterans looking for a new challenge.
That having been said, there could be a separate mode to quick start a more advanced game, like "challenge mode".  The idea in both cases is to provide a fairly consistent start, but with some variation for repeatability.  If we need to chose between repeatability and consistency though, consistency wins.
