### ISSUE TITLE
App not always starting on macOS 10.11

### ISSUE THREAD

**Issue by openmedi** [CleverRaven/Cataclysm-DDA#21345]
OS: 10.11.6
Affects: recent experimentals

### Expected Behavior

When clicking on the cataclysm app, the game should start.

### Actual behavior

This is not always so. Sometimes the app seemingly does nothing and is just bouncing in the dock.

### Steps to reproduce the behavior

Restart the app multiple times, until the buggy behaviour is shown.

EDIT: I should've added that, when executing the bash script inside the application package the game starts just fine.

**Comment by Leland** [comment]
Cannot reproduce, either in a self-compiled or downloaded version. There are quite a few active Mac users as well who have not been noticing this. Closing – @openmedi if you're still experiencing this, do reopen.

**Comment by PeterB789** [comment]
Exactly the same issue openmedi described. (Latest experimental)

OS 10.11.6
App won't open after clicking on the symbol. Only thing helping is a restart. 

When I execute the cataclysm tiles inside the app it shows me the following (if this might help):

Last login: Tue Oct 17 12:22:59 on ttys000
Apfelkiste:~ peterbischofberger$ /Applications/Cataclysm.app/Contents/Resources/cataclysm-tiles ; exit;
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Applications/Cataclysm.app/Contents/Resources/cataclysm-tiles
  Reason: image not found
Trace/BPT trap: 5
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by cavitas** [comment]
OS: 10.11.6
The same problem starts only first time, all next stuck on loading. 
Help only reinstall fresh ".app". 
Work only from bash file. 
Try start old version 0с.18352 work perfect

**Comment by LyleSY** [comment]
Can't reproduce on 10.13.2. 10.11 should be losing Apple security updates in Fall 2018. Not sure how long we want to support it.

**Comment by Leland** [comment]
@kevingranade thoughts on the above? What's our support for older macOS versions?

**Comment by kevingranade** [comment]
That's dominated by the amount of interest mac devs in the project have in supporting it, I don't have a Mac to build on, so I can't really contribute in that area.

**Comment by Leland** [comment]
Unfortunately, to my knowledge, we have no devs on 10.11. Closing – if any Mac devs running 10.11 want to take a crack, PRs are always welcome
