### ISSUE TITLE
Easily enable persistent debug logs

### ISSUE THREAD

**Issue by jzambo** [CleverRaven/Cataclysm-DDA#21349]
Tiny debug window has limited usefullness for troubleshooting. Is there a way to enable verbose logging to file?

Knowing of no better approach I'm littering the code with:

`DebugLog( D_INFO, DC_ALL ) << string_format("challenge result: %d", result);`

and the like so that I least I can review config/debug.log file.

**Comment by Coolthulhu** [comment]
Currently the debug log settings are compile time hardcoded with defines. That makes it incredibly clunky to use.
It would probably be relatively easy to make it read options instead of being hardcoded. Possibly cached options defaulting to true or something like that.

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
