### ISSUE TITLE
Decouple advanced inventory from the player

### ISSUE THREAD

**Issue by jzambo** [CleverRaven/Cataclysm-DDA#21347]
It's possible to pass any player to advanced inventory code with some additional tweaks (like who's moves we take).

This would solve https://github.com/CleverRaven/Cataclysm-DDA/issues/20726 and open new possibilities. 

For example, I'm using this for managing friendly NPC armor and robbing unconscious NPCs without killing them as killing causes severe morale penatlies for non-psychopathic characters.

**Comment by Coolthulhu** [comment]
Be careful with AIM code - it's a mess that should be untangled, not piled on.
If it was as simple as having a player pointer for wear and inventory panes, it would be fine. But it was to include more layers of abstraction, it should be refactored.

**Comment by kevingranade** [comment]
Please don't open issues to suggest implimentation details for other issues, just comment in the issue it will fix.
