### ISSUE TITLE
Empty guns with mods always appear in unload menu selection

### ISSUE THREAD

**Issue by PapaPetro** [CleverRaven/Cataclysm-DDA#21357]
Typically, if a gun is empty of bullets/mags, it will not appear in the unload menu selection. However, guns that have mods (both integrated and attached) will always appear in this menu even if they have no bullets/magazines in them.

Here's a screenshot for clarification of what I'm describing:
http://i.imgur.com/aisKXTd.png

So an empty M60 with an integrated bipod will always appear in the unload menu. If you have a shoulder strap added on an empty RM51 Assault Rifle, it will appear in the unload menu until you remove the shoulder strap mod.

To reproduce is simple, just add a mod to an empty gun and hit the U key, and try to unload the empty weapon. You should get a response that the weapon is already empty.

It looks like the code is reading the mods as a sort magazine that can't be unloaded through this command. Ideally, the 'U'nload menu should only contain items/weapons that can be unloaded.

**Comment by DangerNoodle** [comment]
Was it formerly possible to remove gun mods via the unload function?

**Comment by PapaPetro** [comment]
Yes. I ran an old build from 2015 (d8f0546), which was before magazines were implemented, and the unload function would unload the bullets and a second call would unload the mods.

**Comment by falldj** [comment]
so some gun mods can be loaded/unloaded. i guess...do we want to be able to remove mods through the 'U'nload menu? if not, can't we mark bipods as not unloadable somehow?
I hope i'm not coming off as too much of an idiot, i am still learning the code and it's late here.

**Comment by kevingranade** [comment]
What do we do now, activate the gun to remove mods? I honestly cn't remember.  If so, that's better than overloading unload.

**Comment by BorkBorkGoesTheCode** [comment]
>What do we do now, activate the gun to remove mods?

Yes.
