### ISSUE TITLE
Bayonets train the wrong skill

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#21361]
### Expected Behavior
Bayonets raise piercing when used
### Actual behavior
They raise bashing skill instead
### Steps to reproduce the behavior
Attack an enemy using a gun with combat knife attached.

I'm pretty sure someone mentioned this elsewhere.

**Comment by Coolthulhu** [comment]
Correction:
Expected behavior is training both bashing and piercing.

**Comment by AlexMooney** [comment]
I've tracked the training code down to this spot: [`static void melee_train`](https://github.com/CleverRaven/Cataclysm-DDA/blob/b88836e94fa424180fb9d8a1ac32543b6608b8d1/src/melee.cpp#L284-L300).

I added some output to test what the game thought was going on with the bayonet:
```diff
diff --git a/src/melee.cpp b/src/melee.cpp
index f190e81..833dfe6 100644
--- a/src/melee.cpp
+++ b/src/melee.cpp
@@ -289,6 +289,7 @@ static void melee_train( player &p, int lo, int hi ) {
     int cut  = p.weapon.damage_melee( DT_CUT );
     int stab = p.weapon.damage_melee( DT_STAB );
     int bash = p.weapon.damage_melee( DT_BASH ) + ( !p.is_armed() ? 1 : 0 );
+    add_msg( "%s (%d cut, %d stab, %d bash)", p.weapon.tname().c_str(), cut, stab, bash );
 
     float total = std::max( cut + stab + bash, 1 );
     p.practice( skill_cutting,  ceil( cut  / total * rng( lo, hi ) ), hi );
```

I tested using an AK-47 with and without a combat knife attached and got this output:
```text
# without
AK-47M (0 cut, 0 stab, 11 bash)
# with
AK-47M+ (0 cut, 18 stab, 11 bash)
```

I also note that I was given piercing training by using it in melee.  Seems to work correctly to me.

**Comment by 1skandar** [comment]
Uh, hmm, it looks like it is *adding* the bayonets damage to the melee damage you'd get just from the gun. While correct in the way the code is written, I dare say that is incorrect in the way it should be handled. You are no longer bashing them with the gun, you're stabbing them with the bayonet.

**Comment by Coolthulhu** [comment]
You are in superstate of stabbing them with the bayonet and bashing them with the stock.
All weapons with multiple damage types are handled this way.

**Comment by 1skandar** [comment]
Yeah...and that then raises the question of what happens to the melee speed when the bayonet is attached? If you are adding an attack it should go up. If it currently does not, or goes down, um, that may need looked at.

I get that from a code standpoint it may be correct, but from a real world standpoint less so. And gun mods are kind of a special case, in that you're modifying the damage of a melee weapon, which isn't otherwise possible. 

A bit nitpicky, I know.

**Comment by BorkBorkGoesTheCode** [comment]
Cannot reproduce this.
