### ISSUE TITLE
Incorrectly categorized weapons on crafting menu

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#21369]
Version:0.C-22779-g3510ea2 (tiles) Build:6560
The following weapons are listed on the crafting menu as cutting weapons:

Steak knife, survival knife, combat knife, trench knife, survivor naginata, ceramic rapier, ceramic knife.

All of the above are piercing weapons, but shouldn't the survival naginata be a cutting weapon?, it IS a blade on a stick after all.

**Comment by DemAvalon** [comment]
Furthermore the following makeshift magazines only appear on the crafting list if you look at the 
**AMMO** tab in the **ALL** category:  makeshift STEN magazine, makeshift 223 magazine.
And the following are in the **OTHER** category: Pipe SMG : .22 magazine, .38 magazine , 9mm magazine , .40 magazine, 45 magazine.
There is an oddly vacant **MAGAZINE** category on the weapons tab.

**Comment by LiGIAOTPA** [comment]
i got this

**Comment by Reclusive-reptile** [comment]
Ceramic bayonets aren't vanilla. What mods are you using?

**Comment by DemAvalon** [comment]
@Reclusive-reptile It seems that Ceramic weapons were added by ZSFIXED_C: DDA Extra Professions And Gears, I thought that was just a fix for extra professions and gears since I was getting an error when trying to create a character in a world with this mod sorry, I thought Ceramic weapons where a vanilla thing that was added since I had not played for a few months ^^;
