### ISSUE TITLE
NPCs are not listed in kill counts

### ISSUE THREAD

**Issue by Taberone** [CleverRaven/Cataclysm-DDA#21367]
### Expected Behavior
Killing a NPC adds them to the player's kill count, since the kill count tracks every single kill made by the player.
### Actual behavior
Killing a NPC does not add them to the player's kill count.
### Steps to reproduce the behavior

<a href="http://imgur.com/5YT9869"><img src="http://i.imgur.com/5YT9869.png" title="source: imgur.com" /></a>
1. Murder a NPC.

<a href="http://imgur.com/zS5BN4H"><img src="http://i.imgur.com/zS5BN4H.png" title="source: imgur.com" /></a>

2. Check your kill count, either by killing yourself or hitting ")". Notice how other survivors killed are not counted.

**Comment by BrettDong** [comment]
The kill count table is recorded as the pairs of a monster type and an integer value representing the kills to that monster. However NPCs do not have their _'monster type'_.
