### ISSUE TITLE
Pack of firecrackers can't be disassembled

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#21370]
### Expected Behavior

Picking up a 'pack of firecrackers (25)' and (D)isassembling it should produce 25 firecrackers, 5 paper, 1 small string as per recipe. See: https://github.com/CleverRaven/Cataclysm-DDA/issues/56

### Actual behavior

"You can't unload a pack of firecrackers! You cannot disassemble this." They can however be assembled. As one of the few resources of gunpowder besides ammo itself, it'd make sense for a survivor to want to disassemble these and use the powder for handloading.

### Steps to reproduce the behavior

Put a pack of firecrackers on the table and karate-chop them as hard as you can. Repeat.

**Comment by DangerNoodle** [comment]
Problem, however. You can cause firecrackers to have less than the full 25 charges via the use_action allowing you to not light off the entire pack.

**Comment by Tharn** [comment]
In that case I'd prefer if it always used the entire pack, if that's what's preventing them from being disassembled. If you want to use single firecrackers, you can disassemble, then light the single ones. That's my reasoning, anyway. I don't see much use for anything between "I want tons of noise" (light all 25) or "I just want noise" (light one).

**Comment by DangerNoodle** [comment]
Since that is likely the problem behind this, it might be viable to do so. In addition, most real life packs of firecrackers that I know of are linked by the fuses, and it is expected that the user will light them all off in sequence.
