### ISSUE TITLE
Crafting from vehicle tanks doesn't consume liquids

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#21389]
### Expected Behavior

When crafting a batch of 20 diesel, it correctly recognizes a vehicle with a faucet and the denatured alcohol / cooking oil as the only source. It should subtract from these two tanks.

### Actual behavior

You can craft the batch of diesel, but the amount of oil and denatured alcohol stored never decreases. You get the diesel for free, essentially. The only liquid it does decrease is water from a vehicle tank.

### Steps to reproduce the behavior

Have a vehicle with tanks filled with cooking oil and ethanol / denatured alcohol as well as a faucet in range. Make sure it's the only source.

Possibly to do with https://github.com/CleverRaven/Cataclysm-DDA/issues/21102

**Comment by Night-Pryanik** [comment]
The bug is here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/a09391dba7e6a0605012b9f8e26e41dc85a330c1/src/map.cpp#L5060-L5071

It drains only the hardcoded water, clean water and batteries.
