### ISSUE TITLE
Vitamin/allergy sets to replace materials for food

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#21395]
# Rationale (skip if tl;dr):

Material components carry implications that aren't well suited to food: resistance to damage, fuel data, density.
Unfortunately, at the moment materials also have the `edible` flag and vitamin data.

This will necessarily result in some pigeonholing, as materials in tools aren't used in the same way as materials in food.
For example, a powdered egg has much more "egg" in it than pure egg, but this can't be adequately expressed in materials right now. Making each egg-proper made of egg and water will not solve the problem either: 75% of egg is water, while adding water material would only handle 50%.
Even worse for allergens: with materials, you can't mark something as containing an egg in it without making it edible by carnivores.

To handle food data with materials, either everything would have to be pigeonholed, or materials would have to be multiplied to handle cases like adding small bits of material.

___

# Idea

* Edible items only use materials for structure
* There is a second set of data, used only by edible items, containing data about vitamins and allergens (and possibly nutrition)
* Each edible item specifies how much of the "nutrition materials" it contains
* The above could be even specified in percentage of mass, for the realism freaks who would otherwise be forced to compare things to each other to figure out some sort of order (which generally isn't there and is just arbitrary)

For example:
```
"type": "ITEM",
"id": "bread",
"nutrition_data": [
    "wheat": 0.9,
    "yeast": 0.1,
    "salt": 0.0 // Trace amounts, just for allergen-type reactions
],
"materials": [ "veggy" ], // Not "wheat", because wheat and veggy are physically similar enough
...
"type": "nutrition_data",
"id": "wheat",
"copy-from": "starch",
"allergens": [ "wheat" ],
"vitamins": [ "uranium": 100 ]
...
"type": "nutrition_data",
"id": "starch",
"kcal_per_kg": 4000
```

# Alternative

If we want simplicity instead of complexity and depth, we could just go with those crude materials. But then we need some sort of standard for them, which we currently lack.
* Who is responsible for allergies? Mutations or materials?
* How to handle trace amounts of allergen? Just by flag or full material inclusion?
* How to handle multi-material things? When does one material end and two begin?

**Comment by LiGIAOTPA** [comment]
Good idea. I also consider these thing recently, My idea is very similar to yours, but I am really not good at program things, I don't know if I have the ability to solve these problem, so I choose add a new material to solve Calcium supplementation. 
I think vitamin system itself is rough and unrealistic now(although it curbed player only eat same food that easily to get ),  each vitamin's rate of loss is the same ,and obvious it's too fast, consummate vitamin system itself is also pretty important, and classify food and allergic in detail is also necessary.
ps: In view of my poor English, There may be wrong understanding and expression
pss:Have a nice day

**Comment by kevingranade** [comment]
Obsoleted by https://github.com/CleverRaven/Cataclysm-DDA/pull/27252 and related changes.
