### ISSUE TITLE
Aerodynamic vehicles experience more slowdown than bricks on wheels

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#21405]
My attempt at fixing this: #21380

### Expected Behavior
The slowdown a vehicle experiences correlates with how much air resistance it experiences, and with how well it handles its weight.
### Actual behavior
The slowdown a vehicle experiences correlates positively with how well it spreads its weight on the wheels, but negatively with how much air resistance it experiences.
### Steps to reproduce the behavior
* Accelerate an aerodynamic vehicle (motorcycle) to some set velocity
* Kill the engine
* Note the distance it covered
* Repeat the above with a non-aerodynamic vehicle (road roller)
* Compare the numbers

**Comment by kevingranade** [comment]
Addressed by #21380 
Further balancing would require more detailed success criteria.
