### ISSUE TITLE
Telescopic Eyes don't affect nearsightness if installed prior to that mutation

### ISSUE THREAD

**Issue by Aivean** [CleverRaven/Cataclysm-DDA#21407]
Also may be related to #15211.

Currently, as Telescopic Eyes fix vision problems upon installation, it's possible to be near/far-sighted and have Telescopic eyes at the same time, if you first install Telescopic Eyes and then manage to roll Nearsighted mutation.

I think it's inconsistent with the lore, as Telescopic Eyes are supposed to replace your eyes completely. Additionally, they are impossible to remove, so you can't just reinstall them to fix the problem.

Build: 
![image](https://user-images.githubusercontent.com/2865203/28005003-0eb3c442-64fd-11e7-9920-33e8f83ae5d6.png) 
but I think it affects all versions.

**Comment by LordZanos** [comment]
If telescopic eyes completely replace your eyes then they should probably remove and block all eye mutations or traits.

**Comment by Aivean** [comment]
Just found out that reentering the game fixes the problem  (in `player::load`:

      // Fixes bugged characters for telescopic eyes CBM.
      if( has_bionic( bionic_id( "bio_eye_optic" ) ) && has_trait( trait_HYPEROPIC ) ) {
          remove_mutation( trait_HYPEROPIC );
      }
)

Probably not a best fix, but still a decent workaround.
