### ISSUE TITLE
JSONization of mission properties: reveal-and-mark overmap

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#21413]
Certain mission properties presently remain hardcoded. Some of them might be valid for conversion to JSON format (to cite in missiondef entries), but my efforts so far have been unsuccessful. There are several useful properties that could be converted with little effort for someone more experienced than me, but (as per Kevin's request) I will suggest the most useful overall.

The most widely-used property that could be converted to JSON is the very common application of marking a specific mapgen on the map, such as the closest thick forest (jabberwock quest), nearest cathedral (relic quest), among many other examples. Common as this property is, and as useful as it would be for modders who want to add their own missions directing players to specific locations, this would be extremely useful to move to JSON format.

Other useful functions were previously brought up (the "kill X of this monster" being the easiest among those) but these can be discussed another day, in order to narrow the focus of this issue.

**Comment by kevingranade** [comment]
This issue is entirely too wide-ranging, trim it down to one of the topics.

**Comment by DangerNoodle** [comment]
Understood. Conversion of `MGOAL_KILL_MONSTER_TYPE` mission starts would be the easiest to attempt first, given it was what I initially attempted to look into.

However, reveal of nearest mapgen and marking it as the quest location would be more generally useful, as it is used by the most missions. I would advocate conversion of that to JSON first. It would not be the low hanging fruit like "kill X of this monster" would be, but it would be the more desirable property to have in JSON.

**Comment by Night-Pryanik** [comment]
No discussion in more than a year, closing.
