### ISSUE TITLE
Debug Life Support Does Not Work With Mutagenic Serums.

### ISSUE THREAD

**Issue by Happydacat** [CleverRaven/Cataclysm-DDA#21416]
I noticed that Debug Life Support does not disable the costs of gaining mutations, like you would expect. To reproduce this issue, activate debug life support, and inject yourself with a mutagenic serum.

**Comment by kevingranade** [comment]
What testing is this preventing you from doing?

**Comment by Happydacat** [comment]
Nothing right this second, other than messing around with mutagens. It's not a big issue, but it does seem like an oversight, so I figured I would create an issue, so that it's known.

**Comment by kevingranade** [comment]
We have too many issues open to accept speculative feature requests for debug features.
