### ISSUE TITLE
Keybindings Don't Register All Shift, Alt and Control + Key Combinations

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#21412]
### Expected Behavior
Be able to bind 'Shift + Left Arrow Key' to command 'Move Northwest'.
### Actual behavior
Program doesn't seem to distinguish between Shift + Left Arrow and just Left Arrow, but it can distinguish between 'a' and 'A'.
### Steps to reproduce the behavior
Open menu, select Keybindings, choose a binding and try and add a command with Shift + a non-letter.

It would be really great to be able to bind Arrow keys plus Shift and Control or Alt so that I can play this great Roguelike easily on a laptop with no numeric keypad.

**Comment by Night-Pryanik** [comment]
Duplicate of #20447.
