### ISSUE TITLE
CBM not working as intended

### ISSUE THREAD

**Issue by JunoJeuco** [CleverRaven/Cataclysm-DDA#21426]
### Expected Behavior
i expect to not have to overdose on pain PILLS (wtf??) and inject adrenaline
### Actual behavior
it works as good as a mexican gardener with no arms watering your plants with his saliva while he fantasizes about churros (intended?)
### Steps to reproduce the behavior
install a cbm

**Comment by Happydacat** [comment]
"Working as intended." --Someone who think's hes a good game designer, but really isn't.
