### ISSUE TITLE
Crash with e while x

### ISSUE THREAD

**Issue by pierredavidbelanger** [CleverRaven/Cataclysm-DDA#21422]
### Steps to reproduce the behavior

I e`x`amined a car, then wanted `e`xtended description:

![cataclysm__dark_days_ahead_-_0_c-22738-gbe686a5](https://user-images.githubusercontent.com/1076726/28235772-2af6c098-68e3-11e7-8ecc-032ec4dea134.png)

Then I get this message:

![cataclysm__dark_days_ahead_-_0_c-22738-gbe686a5](https://user-images.githubusercontent.com/1076726/28235778-4792c49a-68e3-11e7-90ce-022323340d3e.png)

**Comment by Night-Pryanik** [comment]
The game actually crashes, or you can still play if you press spacebar?

**Comment by pierredavidbelanger** [comment]
@Night-Pryanik oh, sorry, no crash, but no play either :) It actually kind of hang with the window open, half rendered, CPU at 100%.

**Comment by Coolthulhu** [comment]
Can't reproduce, need more data.
Is this the newest version of the game? I fixed one instance of the harvest list bug recently.

**Comment by AMurkin** [comment]
Issue #21196. PR #21360.

**Comment by pierredavidbelanger** [comment]
Oh, indeed this is probably fixed.
I just found that I am using a two weeks old custom build that merges d9eb186ce8 and https://github.com/Chezzo/Cataclysm-DDA/tree/ChezzoSounds
