### ISSUE TITLE
Brick walls drop rocks when they are destroyed

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#21431]
### Expected Behavior
Brick walls drop bricks after they are destroyed.
### Actual behavior
Brick walls drop rocks when they are destroyed, even though the recipe doesn't include rocks.
### Steps to reproduce the behavior
Break a brick wall.

**Comment by CoroNaut** [comment]
The rocks are assumed to be chunks and fragments of bricks and mortar since you had destroyed the wall from brute force.

**Comment by BorkBorkGoesTheCode** [comment]
It still feels weird for the brick wall to drop rocks otherwise indistinguishable from any other rock found in a field or underground.

**Comment by kevingranade** [comment]
Adding "masonry chunks" with rock-like stats for this would be fine. That
does require some thought about what rock-accepting recipes they should be
added to, so it has more impact than it seems.

**Comment by Akhier** [comment]
Maybe you should get a couple of bricks and the rest as rocks. After all when you smash down a wood wall you don't just get splinters but 2x4s as well

**Comment by ArikVhedrovix** [comment]
I like the idea of "masonry chunks". Maybe we could get some of those in the rubble spots to add more flavor. Also there could be a few usable bricks left in rubble. Making walls drop a few bricks too doesn't seem unbalancing to me. I would look at existing walls as the best source of bricks in real life rather than trying to form, dry and cook them myself if I was surviving alone.

**Comment by Podesta** [comment]
I'm going over the code now to add the mineable tag to a lot of items that should have them. Would you guys be ok with brick walls leaving at least a few bricks when destroyed? I find hard to believe the player couldn't salvage a single brick from the bunch. Bricks are fairly easy to reuse. People have always salvaged bricks from toppled buildings.

**Comment by Night-Pryanik** [comment]
Yes, that would be Ok.
