### ISSUE TITLE
Potential major discrepancy in monster stumbling in Windows MXE builds

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#21437]
Discovered while testing #21436

When testing MXE-built Windows builds (with Wine), monster_test.cpp fails a lot, with typical failure looking like this:
```
monster_test.cpp:265: FAILED:
  CHECK( stat_pair.second.avg() == Approx(100.0).epsilon(0.1) )
with expansion:
  125.5f == Approx( 100.0 )
with message:
  Monster:mon_zombie_dog Angle: 103 moves: 125.5 types: 4 samples: 111, 139,
  119, 121, 127, 119, 121, 137, 125, 127, 141, 125, 113, 129, 129, 135, 133,
  121, 123, 115, 
```

This could be a major concern if the distributed Jenkins builds are also affected by this bug.

**Comment by kevingranade** [comment]
This is one of those places where 'real' unit testing of e.g. just
trig_dist() and friends might be helpful.
