### ISSUE TITLE
NPC followers dropping items message log peculiarity

### ISSUE THREAD

**Issue by username-isAlready-taken** [CleverRaven/Cataclysm-DDA#21444]
### Expected Behavior

*NPC* drops his *item* on the sidewalk

### Actual behavior

*you* drop your *item* on the sidewalk

![untitled](https://user-images.githubusercontent.com/24560047/28327856-f0f63324-6be4-11e7-9a87-418212198517.png)

### Steps to reproduce the behavior

Give a follower a better piece of armor than what they're currently wearing.

**Comment by codemime** [comment]
The issue is known (see #16766 where I've promised to fix it). Though with the long delay, I'm fixing it now.
