### ISSUE TITLE
Cease and Desist using Vacutainer

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#21459]
I got a cease and desist letter about the wiki using the term Vacutainer, so it should probably be changed in the game too.

Here's the letter:

> BD VACUTAINER: Notice of   Trademark Infringement: chezzo.com
> 
> 
> Dear Respected Author/Publishing Institution,
> 
> Please be advised that Vacutainer® and Microtainer® are federally and internationally registered trademarks owned by BD (Becton, Dickinson and Company) that are used in connection with a complete system of tubes, lancets, needles and needle holders, sharps collectors, and safety devices.
> 
> Among its 121 registrations throughout the world, BD holds a trademark registration for Vacutainer® in the EU under Registration No. 876201, in the US under Registration No. 0424957, as well as an International Registration for BD Vacutainer with Design under Application No. 824745, which extends to Asia-Pacific countries. Among its 56 registrations throughout the world, BD holds a trademark registration for Microtainer® in the US under Registration No. 1042544, in China under Registration No. 279170 and in India under Registration No. 708400.
> 
> It has come to our attention that BD's trademarks Vacutainer® and/or Microtainer® are being used improperly on your website at the URL(s) found at:chezzo.com
> The content in question can be found at the following URL(s):
> http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Vacutainer
> 
> While we can appreciate that it may not be feasible to amend an already published work, we are hoping we can depend on you to adhere to the following usage guidelines when referencing the Vacutainer® and Microtainer® trademarks in all future publications, and that you will amend what can be easily amended online to conform to these usage guidelines:
> 
> - Vacutainer® and Microtainer® should always be distinguished as a trademark by using it in all capital letters or with a capital "V" for Vacutainer® or capital "M" for Microtainer®;
> 
> - Do not use Vacutainer® or Microtainer® in the plural form;
> 
> - The Vacutainer® and Microtainer® trademarks should be used at all times as an adjective modifying a noun, e.g. "Vacutainer tube";
> 
> - Proper acknowledgement of BD's rights should be given whenever Vacutainer® or Microtainer® is used through (1) use of the ® trademark notice each time the trademark appears; and (2) use of the legend "Vacutainer® (and/or Microtainer®) is a registered trademark of Becton, Dickinson and Company" at least once in all materials in which the trademark is referenced.
> 
> We thank you in advance for your cooperation and look forward to receiving confirmation by return e-mail that you will comply with our request.
> 
> We appreciate your assistance in helping us preserve the value and integrity of BD's trademark assets.
>

**Comment by Rivet-the-Zombie** [comment]
We're a non-commercial work of fiction; I'm pretty sure we're in fair use territory here.

**Comment by DangerNoodle** [comment]
I find it highly amusing that they directed this C&D at your site, and not at the Cataclysm DDA site.

**Comment by kevingranade** [comment]
Actually they're asking for attribution and annotation, which AFAIK IS
reasonable and mandatory even for fair use.

**Comment by Cyrano7** [comment]
@Chezzo Maybe we should just delete that page from the wiki? I doubt they even know the context, they are just getting the web result.

**Comment by Mecares** [comment]
I like the name change suggestion that has been made on Reddit. In my case as a person without english as a first language I had no idea what a vacutainer is supposed to be, but a blood drawing kit is pretty obvious to me.

**Comment by kevingranade** [comment]
Actually I double checked, and I had misremembeted the requirements, you are prohibited from using it unless it's actually a registered trademark, but no one is ever required to use it.  The rest of the demands are likewise baseless.

**Comment by Leland** [comment]
Closed in #21486
