### ISSUE TITLE
Game crashing due to NPC bug in vehicle in build 6603

### ISSUE THREAD

**Issue by Zetsukaze** [CleverRaven/Cataclysm-DDA#21455]
Game crashes on load, some error message pops up about NPC already being there.
[Thrix.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1163431/Thrix.zip)

**Comment by AMurkin** [comment]
Seems only tiles version segfaults.

**Comment by Zetsukaze** [comment]
I notice that NPCs refuse to board the vehicle when there is exhaust smoke in the way of the door.

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed.
