### ISSUE TITLE
NPC's Throw their weapons for seemingly no reason

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#21461]
Version: 0.C-22899-g34d73e9 (tiles) Build: 6603 
### Expected Behavior
NPCs without throwing skill don't throw their weapons at zombies, especially if they don't have a backup.
### Actual behavior
NPCs throws their melee weapon then go on to fight unarmed (of which the offending NPC is not proficient at)
### Steps to reproduce the behavior
I'm not sure how, it's something I noticed happening sporadically, in my current save the NPC has a combat knife and sometimes they throw it, if I give them the knife back they throw it again, but not throwing knifes those she uses on melee. (note: on the version I currently play has a problem where NPCs don't use ranged weapons at range, only point blank, bows, guns, and such, when throwing they do it at range for some reason)

**Comment by DemAvalon** [comment]
This is my save, the combat knife that the NPC just threw is next to the zombie, if I walk over there, pick up the knife and give it to her, she **immediately** throws it at the zombie (which should be on melee range now).
[Magnolia Hills.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1166826/Magnolia.Hills.zip)

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed.

**Comment by Foxtrot-Uniform42** [comment]
Happens to me as well. Bandits throwing their weapons at me (pistols/shotguns, but not crossbow). After that, they start throwing something infinite at me without damage. I am using No hope mod, will post a save once I'm able to repeat this.

**Comment by Xenoamor** [comment]
Just had the same happen:
![image](https://user-images.githubusercontent.com/7109951/151456475-100fc551-851e-4f9c-9d7f-4737fe6df9b1.png)
![image](https://user-images.githubusercontent.com/7109951/151456486-a0bf6334-3066-4f2f-96a1-9a3c16e60be0.png)
