### ISSUE TITLE
Ram a vehicle and it will move in the direction that it is facing.

### ISSUE THREAD

**Issue by Zetsukaze** [CleverRaven/Cataclysm-DDA#21469]
Hit any vehicle with your own one and watch as it accelerates in the direction that it faces, not the direction that you hit it from. Easiest to see when ramming wing mirrors of vehicles facing you.

                <--- Your vehicle direction
---> Vehicle getting rammed

As shown above, the rammed vehicle will move right instead of left.

**Comment by Leland** [comment]
![screen recording 2017-08-23 at 07 39 pm](https://user-images.githubusercontent.com/714017/29643111-d7514c66-883a-11e7-8c3b-37e850abd3e0.gif)
![screen recording 2017-08-23 at 07 33 pm](https://user-images.githubusercontent.com/714017/29643119-ec2c4c80-883a-11e7-93ed-c0fbe8cd3afb.gif)

**Comment by Leland** [comment]
Closing per above; feel free to ping me here with a set of steps to reproduce and I'll reopen.
