### ISSUE TITLE
Fullscreen In OSX ignores switching Desktops/Apps

### ISSUE THREAD

**Issue by EricFedrowisch** [CleverRaven/Cataclysm-DDA#21471]
### Expected Behavior
For other Fullscreen OSX Apps, pressing Ctrl + Direction Arrow moves to next Desktop or Fullscreen App. Alternatively, Command + Tab shows and cycles through active Apps similar to Alt + Tab on Windows.
### Actual behavior
Fullscreen Cataclysm-DDA doesn't do anything when these buttons are pressed, so you have to quit the App completely to look at the desktop or any other App.
### Steps to reproduce the behavior
Set game to Fullscreen in options in OSX. Try pressing Ctrl + Arrow or CMD + Tab. Nothing happens atm.

**Comment by Leland** [comment]
@EricFedrowisch the "Full Screen" graphics option on Mac really sucks – do borderless window and go full screen with it.

Not a solution to this issue (ideally both the "full screen" option and the process I described above would be functionally identical) but should at least make your life a little easier.

**Comment by Leland** [comment]
Closing per above – the solution is borderless window
