### ISSUE TITLE
Feeding unopened cans of food to NPCs feeds them the contents, but keeps the can sealed

### ISSUE THREAD

**Issue by aka-azrad** [CleverRaven/Cataclysm-DDA#21475]
So, feeding NPC companions meat soup from an unopened can. They eat portions of it, but the can remains unopened in the process. If give all the contents of the can without opening it, once it's empty the can becomes just a tin can. Still unopened, and unlike open/empty tin cans they can't be used for crafting.

Not sure if sealed glass jars have the same effect.

**Comment by AMurkin** [comment]
PR #18927 seems to be related

**Comment by Treah** [comment]
Can you give details on how you performed these actions? Did you trade the can and the NPC ate it or did you hand feed it to them? Also what version of the game are you running as the last time I attempted to reproduce this bug I was unable to..

**Comment by aka-azrad** [comment]
Upon checking, feeding them using the use this item command makes them consume it without opening the can. Trading them the can makes them open it, as it turns out.

Experimental version I'm running right now is 0.C-6567, though I noticed this several experimental versions ago.
