### ISSUE TITLE
Updating from Build 6605 to Build 6609 and above has an error

### ISSUE THREAD

**Issue by Zetsukaze** [CleverRaven/Cataclysm-DDA#21481]
![bug](https://user-images.githubusercontent.com/1698993/28521360-dddb7c16-70a5-11e7-8fe1-624b28b03f9b.PNG)

Mods active: 
DDA, Craftable Gun Pack, DeadLeaves' Fictional Guns, Extended Realistic Guns, Icecoon's Arsenal, Makeshift Items Mod, Medival and Historic Content, More Survival Tools, Mythological Replicas, PK's Rebalancing, Boats, Folding Parts pack, Tanks and Other Vehicles, Vehicle Additions Pack, Necromancy, Cataclysm++, Classes and Scenarios Mod, Classic Roguelike Classes, Disable NPC Needs, Filthy Clothing, StatsThroughSkills IV

**Comment by DangerNoodle** [comment]
Can you replicate this error without any mods? And additionally without any of the third-party mods?

**Comment by Zetsukaze** [comment]
Tested it, removing PK's Rebalancing fixes it.

**Comment by DangerNoodle** [comment]
The version in this repository, or the third-party version maintained by @pisskop?

**Comment by Zetsukaze** [comment]
Erm, the one that comes when you do the update from the launcher. Unsure which one it is.

**Comment by pisskop** [comment]
Sorry.  Im having no issues on my end.  Ill do a clean pull and see.

**Comment by DangerNoodle** [comment]
It could be the repository version then, the launcher is notorious for overriding third party mods with the obsolete ones in the repository. If so, apologies for the ping.

**Comment by Zetsukaze** [comment]
I just tried an update, failed again with the same error

**Comment by pisskop** [comment]
https://github.com/pisskop/PKs_Rebalancing

Try getting the mod from the above link?  Ive notified iamroy about the change, but if he has to integrate it on his end it may not happen until he has free time.

**Comment by Zetsukaze** [comment]
It works from the launcher when I delete the one they install after the update and reinstall it from the mods tab

**Comment by Zireael07** [comment]
I recommend closing this issue and reopening on the launcher's repo if there are problems still.
