### ISSUE TITLE
char_validity_check failing

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#21496]
```
char_validity_check_test.cpp:7: FAILED:
  CHECK( is_char_allowed( '\t' ) == false )
with expansion:
  true == false

char_validity_check_test.cpp:10: FAILED:
  CHECK( is_char_allowed( '\xa0' ) == false )
with expansion:
  true == false
```

Built with:
```
make TILES=1 RELEASE=1 LUA=1 LOCALIZE=0

g++.exe (Rev1, Built by MSYS2 project) 6.3.0
```

**Comment by BrettDong** [comment]
The second case `\xa0` is locale-dependent, and I'll fix it later.

But the first one doesn't seem right. According to the standard, tab character isn't printable and the function should always return false.

**Comment by Qrox** [comment]
I think the problem with `\xa0` is that it can be negative if `char` is signed, so the check `ch <= 127` actually passes for it. (And note that calling `isprint` with a negative value other than EOF is [undefined behavior](http://en.cppreference.com/w/cpp/string/byte/isprint))

The first case instead seems to be locale-dependent. When running the full test on my Windows, the test for `\t` fails, and the locale (got by calling `setlocale(LC_ALL, nullptr)`) is `Chinese (Simplified)_People's Republic of China.936`. When running only this specific test, it succeeds, and the locale is `C`. So some previous test might have changed the locale.

**Comment by Night-Pryanik** [comment]
Is this still an issue?

**Comment by Mark-Hillesheim** [comment]
As of right now, the test still fails in the \t case.

**Comment by xiaohuynh** [comment]
I'm also getting this issue when trying to run unit tests on Windows. 
Here's my [WIP pull request](https://github.com/CleverRaven/Cataclysm-DDA/pull/29751) where I have the issue.

**Comment by I-am-Erk** [comment]
Closed by https://github.com/CleverRaven/Cataclysm-DDA/pull/57382
