### ISSUE TITLE
Training with an NPC, Tailoring 4 -> 5 froze the game

### ISSUE THREAD

**Issue by RinneHellscythe** [CleverRaven/Cataclysm-DDA#21491]
This isn't exactly what I did, but basically:
> Finished the NPC's quest
> Collected rocks for a stone fireplace
> Cooked food, ate, drank and slept
> I tried trading with him, I selected something on his side and pressed enter (didn't know how to trade)
> I was brought back to the conversation menu
> I saw that I can get training again (I took Tailoring 3 -> 4 a day before)
> Seleced Tailoring 3 -> 4
> Game froze
![image](https://user-images.githubusercontent.com/20390505/28608322-84c9c66e-7212-11e7-8b87-3414d75c3762.png)

**Comment by ituluwituluwzev** [comment]
Every time my NPC trains me, the game halts here, but it resumes when I press SPACE. Have you tried SPACE?

**Comment by BrettDong** [comment]
If the game resumes after hitting SPACE, there might be an invisible debug message.
