### ISSUE TITLE
Alarm event spawning eyebots around player regardless of distance

### ISSUE THREAD

**Issue by tasetase** [CleverRaven/Cataclysm-DDA#215]
When you smash in a window of a pawn shop, it triggers the alarm, then you'll usually run away to escape the eyebots. But regardless of the distance you put between you and the shop, eyebots will swoop down near you.

I was in the forest and eyebots where swooping down, and I had not gotten my picture taken or anything.

**Comment by drbig** [comment]
I'm being annoyed by this to the extent I'm adding this to my todo list to fix. If this doesn't involve any major overhauls I'll probably actually stick to that todo.

**Comment by KA101** [comment]
With critters triggering alarms now, it makes no sense to spawn eyebots at the player.  One bot at the map tile where the alarm triggered should suffice.

I may take a look at this too.
