### ISSUE TITLE
Players with albino followers receive messages about effects

### ISSUE THREAD

**Issue by NeoNX01** [CleverRaven/Cataclysm-DDA#21509]
... Even if the player does not have either traits. Only the followers get the effects though.
![follower](https://user-images.githubusercontent.com/3479728/28746537-f76e289e-748e-11e7-842b-0095f7d8dadb.PNG)
![player](https://user-images.githubusercontent.com/3479728/28746539-f79de9ee-748e-11e7-9636-2094872dacee.PNG)
![messages](https://user-images.githubusercontent.com/3479728/28746538-f79a4398-748e-11e7-85c7-e47599d900c8.PNG)

Steps to reproduce:

- Create a world with static NPCs
- Create a char
- Persuade the starting NPC to follow you
- Use the debug mode to add the albino trait, as well as change the weather to sunny
- Step outside with your follower

**Comment by Leland** [comment]
Is present as of 5b04c66.

Savefile: [Melody Hill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1237384/Melody.Hill.zip)
