### ISSUE TITLE
Medieval swordsmanship moves with incompatible weapons

### ISSUE THREAD

**Issue by aka-azrad** [CleverRaven/Cataclysm-DDA#21501]
Not sure if this is a bug or intended. Wielding incompatible weapons, like a rifle with a bayonet or a battle axe, while using medieval swordsmanship still triggers certain moves of that melee style, mainly grab and displace and counter. None of the other melee styles seem to do that.

**Comment by DangerNoodle** [comment]
Grab and grab break possibly make sense for this, but it applying to displace does not. It might be due to presence of `melee_allowed` which is not applied to the comparable techniques in fencing. Possibly a result of older handling of weapon based techniques?
