### ISSUE TITLE
No way to blacklist everything for total conversion mods

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#21517]
When you put every single monster and item into a blacklist, the monsters work fine, but the items throw a ton of errors. 

![Can't have a zombiepocalypse without onion rings?!?](http://i.imgur.com/l4RTGnq.png?1)

And to get around those errors, you have to add items that make recipes, and I don't want the characters in my total conversion mod to have any of those recipes.

It would be really nice if you could blacklist everything by saying "type": "ALL_ITEM_BLACKLIST", and "ALL_MONSTER_BLACKLIST" or something of that sort. Or having an empty whitelist.

**Comment by ZhilkinSerg** [comment]
You probably need to remove inline requirements, that use items

**Comment by DangerNoodle** [comment]
> You can also try to change recipes in such way it won't be possible to learn them for player characters via skill progress or from books.

Problem is that that overriding recipes requires a strict full override, which is not at all future-proof. Copy from is the only feasible way a recipe changing mod of this sort could be at all feasible, and that does not work with recipes last I attempted it.

Likewise, if it was possible to flag a recipe as invalid (and thus impossible to learn) that would allow mod restriction of recipes without blacklisting the items.

**Comment by kevingranade** [comment]
What happens if you instead remove the dda mod and replace it with a mod
with a handful of items in it?

**Comment by Chezzo** [comment]
I'm not sure I understand correctly, but I gave it a try. I made my mod with the blacklist, Bright Nights, and craftable gunpowder all not dependent on DDA. 

Then I started a game with those mods on, and I still got the same errors. Also, there are still recipes for short rope because I unblacklisted strings and rope to try and get past the cordage error.

**Comment by ZhilkinSerg** [comment]
> What happens if you instead remove the dda mod and replace it with a mod with a handful of items in it?

I believe that won't be possible. Removing the `dda` mod will cause errors when starting game due to all hard-coded dependencies to various monsters, monster groups, items, etc in the source code.

**Comment by AMurkin** [comment]
I think it works after #20709.
