### ISSUE TITLE
Cannot push code to a custom branch

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#21513]
I would like to start working on a potential new feature of the game. I downloaded a git management tool called SourceTree. I used it to create a branch but now I can commit to that branch but not push to it. Are there some sore of permissions issue that is stopping me from doing this? Once I have things coded up I plan on making a pull request for it.

**Comment by angoddu** [comment]
I can't label this as a question for some reason either

**Comment by Coolthulhu** [comment]
You're supposed to push to own fork

**Comment by angoddu** [comment]
Whats the difference between a fork and a branch?

**Comment by Coolthulhu** [comment]
Forks have branches, branches belong to forks.
Forks have their own access rights and you can't generally push directly to someone's fork. But you can create a new branch on own fork and then PR that branch to the repo you forked from.

**Comment by angoddu** [comment]
Ok. I will try that. Thank you. I will close this issue if I get it to work
