### ISSUE TITLE
Charcoal Kiln cannot be lit by fire drill

### ISSUE THREAD

**Issue by notQueen** [CleverRaven/Cataclysm-DDA#21519]
### Expected Behavior
Charcoal kiln should be able to be lit by a normal lighter, a matchbook, a fire drill, or any other fire-starter.
### Actual behavior
If the player character has only a fire drill in their inventory after putting wood into the kiln, the kiln's inventory is opened in stead of prompting to light the kiln.
### Steps to reproduce the behavior
1. Make sure player character only has fire drill in inventory
2. Put fuel in kiln (in my example, planks)
3. Press E and target the kiln

**Comment by DangerNoodle** [comment]
Current method to light a kiln with no lighter is to have a fire pit of some sort in reach, light that using the fire drill, then examine the kiln.

**Comment by Nhatorama** [comment]
In case you haven't tried using a campfire drill, it does work on the kiln with the steps you listed.

**Comment by Treah** [comment]
This is not a bug and should be closed. This is intended behavior and the workaround is not hard and there is no interest in fixing it. 
This was opened in may of 2015 and no one bothered to want to fix it. 
#13211

**Comment by Marrim** [comment]
What about flint and steel?
I was surprised to find that you can't use it to light a kiln, a dynamite stick, or really anything else than terrain.

**Comment by Treah** [comment]
@Marrim 
It makes sense that you cannot when you know what it is IRL. Its a bow and a stick along with something to rotate in to hold onto. 
https://en.wikipedia.org/wiki/Bow_drill

**Comment by kevingranade** [comment]
I agree with @Treah, this is intended.  Not all firestarters are created equal.
If someone is interested in adjusting the firestarters descriptions to head off this confusion, something like, " can start a small fire with some work, but too awkward for a lot if situations", that would help I think.
