### ISSUE TITLE
Mapgen item mapping question/bug report/enhancement?

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#21525]
I have either a question or a bug report, not sure which because I havent been traking changes.

When mapping an item group spawn to a symbol like this:
```
"items": {
    "f": {  "item": "fridgesnacks", "chance": 100 }
}
```
Spawns a random item from `fridgesnacks` list in every `f` tile.

.Now my question is: How do I make it so that more than a single item from `fridge snacks` can spawn on every tile?

I think that this was once possible by adding using the `"repeat"` field, but now that does nothing. Was the way of doing this changed or lost or maybe it never existed?

**Comment by Coolthulhu** [comment]
You could try making it an item group.

**Comment by ZhilkinSerg** [comment]
Docs say that `repeat` only works for random coordinates - see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MAPGEN.md#2403-repeat.

Also there are different types of item-groups: `collection` and `distirbution`. I believe the latter has 0% chance that both items from the group will be spawned - see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/ITEM_SPAWN.md.

You can also try using `lua` to spawn items - see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MAPGEN.md#25-lua

**Comment by ZhilkinSerg** [comment]
Example of `lua` inline mapgen: is in the attachment: [dojo-lua-mapgen.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1186939/dojo-lua-mapgen.zip).

It will add LAVA to DOJO building in runtime via lua-script.

Unpack archive to cdda folder replacing files (only dojo building will be changed), create new world without any mods (save for `dda`), reveal map, find `dojo` and teleport to it.

Lua script `lua-mapgen.lua` will be run, which will add lava to `dojo` building creating log file `lua-mapgen.log` in the process.

**Comment by ZhilkinSerg** [comment]
Lua-mapgen mod "Degrade Buildings" is on the forums: http://smf.cataclysmdda.com/index.php?topic=14825.0
