### ISSUE TITLE
[interface] Make a way easier to create a charactor.

### ISSUE THREAD

**Issue by TheMrBakit** [CleverRaven/Cataclysm-DDA#21535]
I'm looking about making an easier ways to find a profession.
1st idea - Set some filter skill wise.
2nd idea - Categories with the number of points you have left. _(that mean putting the Traits/jobs in gray at bottom of the list)_

_### edit for a better understanding###_

**Comment by Vlad-dos** [comment]
Did not get the 2nd one, but adding some filters is definitely a great idea.

**Comment by TheMrBakit** [comment]
It could gray out some traits or profession so you know you miss some point to take it

**Comment by Leland** [comment]
Without a clearer idea of what you're proposing here, there's very little to go on. Closing for now – this is not a slight against you, however. Please create a new issue with a more fleshed out picture of your proposal to encourage discussion.
