### ISSUE TITLE
Vehicles ignore lava tiles

### ISSUE THREAD

**Issue by aka-azrad** [CleverRaven/Cataclysm-DDA#21543]
Driving over lava, such as the ones in rifts, or those small lines of lava that sometimes pop up in the surface, does not affect the vehicles. No damage taken (probably even if the vehicle is made out of wood). 'course, player characters will get damaged by the intense heat, especially in a rift.

On the other hand, fires, such as ones from a molotov, will damage cars.
![cata1](https://user-images.githubusercontent.com/30348690/28877220-4a9126c4-77ce-11e7-81b7-9a047339dd6d.png)

**Comment by BorkBorkGoesTheCode** [comment]
Just when I thought it was safe to compare water tiles to lava....

**Comment by cainiaowu** [comment]
Dwarven magic.
