### ISSUE TITLE
Filthy thread can be used for repairing clothes

### ISSUE THREAD

**Issue by harakka** [CleverRaven/Cataclysm-DDA#21551]
Using latest nightly, tailor/sewing kit can be loaded with filthy thread and then used to repair clothes, even though general clothes crafting with filthy components is now forbidden. This seems like inconsistent behavior.

**Comment by Akhier** [comment]
Having taken a look at it this in-game it goes farther then just allowing filthy thread to be used for repairing. If you load filthy thread into a kit then unload it you get back regular thread instead of filthy thread.

**Comment by somot** [comment]
That violates the laws of logic and SCIENCE!
