### ISSUE TITLE
Copy-from non-functional for mutations

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#21557]
### Expected Behavior
The `copy-from` function works for the majority of JSON items in the code, allowing mods to edit mod things in a way that has mininal interaction with other mods. Editing mutations in this way, changing categories or re-balancing would thus work.

### Actual behavior
Making an attempt to edit mutations via copy from causes the game to hang up and never finish loading when it reaches the mod that attempts this.

### Steps to reproduce the behavior
Create a mod attempting to edit a mutation. I will provide one example below:
```
  {
    "id": "FLEET",
    "copy-from": "FLEET",
    "type": "mutation",
    "name": "Fleet-Footed",
    "extend": { "category": [ "MUTCAT_RAPTOR", "MUTCAT_BEAST" ] }
  }
```

I discovered this while attempting to make the mutation overrides in PK Rebalance less clunky and more futureproof, for @pisskop.

**Comment by Night-Pryanik** [comment]
AFAIK this works in slightly different way. Try using new `"id"` and `"name"` fields for your new mutation.

**Comment by DangerNoodle** [comment]
It will not retain any hardcoded properties that cite mutations by ID, so that is not the solution until all properties that are useful are in JSON format.

**Comment by Night-Pryanik** [comment]
I always thought that copy-from mechanics is used to create new things, not to edit existing ones.

**Comment by DangerNoodle** [comment]
You can do both. See the `realguns` mod for examples that edit ammunition that is in the game. It seems to function on a lot of abnormal things, including martial arts, a property I discovered and provided for the benefit of @chaosvolt since their Arcana and Magic Items repository includes martial arts changes.

This far, mutations and recipes are the only major things you can not edit in this manner that I know of..

**Comment by uvanima** [comment]
Bionics can't be edited this way either.
