### ISSUE TITLE
NPCs won't drink tea.

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#21558]
### Expected Behavior
offer some tea to a companion, they drink it.
### Actual behavior
Npc refuses tea, saying that "it doesn't seem like a good idea".
### Steps to reproduce the behavior
get a companion, get tea (any tea does this) tell Npc to use tea.

I know that the game is set in the U.S and that they prefer to throw their tea out of their harbors, but I thought that might change after the apocalypse

**Comment by ituluwituluwzev** [comment]
They don't drink cola, either. They don't consume anything that has any effect other than quenching and satiating.

**Comment by DemAvalon** [comment]
They do drink alcoholic drinks though.

**Comment by ituluwituluwzev** [comment]
Indeed. Then I do not know why they don't drink tea.

**Comment by DangerNoodle** [comment]
Not even iced, I suspect. How sad.

**Comment by DemAvalon** [comment]
Odd that they will drink mutagens though.
Hey buddy, wanna drink this weird liquid I found on that secret lab?, NPC: Sure sounds great!
*NPC gains a mutation called Cephalopod Gills!*
Want some tea to wash it down?, NPC: HELL NO!, that's nasty.

**Comment by Leland** [comment]
#21558 may have fixed this

**Comment by Night-Pryanik** [comment]
NPCs drink almost all kind of teas (`tea`, `milk tea`, `Long Island iced tea`, `dandelion tea`, `chai tea`, `herbal tea`, `bee balm tea`, `pine needle tea`). They don't drink `bark tea` because it has negative enjoyability, and don't drink `dandelion tea` because it has `CAFF` use_action.
