### ISSUE TITLE
Corpses pulped by attacks still get revived by necromancers

### ISSUE THREAD

**Issue by aka-azrad** [CleverRaven/Cataclysm-DDA#21554]
Unsure if intended. If zombie corpses get pulped via attacks, like getting blasted by a shotgun, they can still be revived by necromancers unlike getting them pulped via smashing the corpse. The corpses in this state are still highlighted yellow, and since they're already pulped you can't smash the corpse anymore.

This can be rather problematic in a fight since a necromancer can revive them again.

**Comment by ituluwituluwzev** [comment]
I never get pulped corpse via attack. The attack can damage, mangle, or blast zombie into chunks of tainted meat. Do you mean mangled corpse?

**Comment by aka-azrad** [comment]
You can pulp a corpse if the damage is strong enough, like a shotgun blast or a sufficiently powerful melee hit. Hit hard enough and bodies explode into bits of meat.

**Comment by Cosmitz** [comment]
Tested in 7153. This behaivour cannot be replicated. Simply killed zombies are resurrected, pulped by a strong damage/blow, not resurrected.

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed. Is this is reproducible, ping me.
