### ISSUE TITLE
Npcs won't fire guns with bayonets

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#21564]
### Expected Behavior
Npcs shoot guns at range and when enemies get close or they run out of ammo they use the bayonet.
### Actual behavior
they only use the gun as a spear.
### Steps to reproduce the behavior
get a gun, put a bayonet on it, give the gun to companion, have companion fight something.

Npcs only use ranged weapons at point blank due to #19798 
so I'm unsure if under normal conditions they would use bayonets appropriately.

**Comment by Leland** [comment]
Cannot reproduce.

<img width="607" alt="screen shot 2017-08-22 at 9 37 07 pm" src="https://user-images.githubusercontent.com/714017/29594885-1905c614-8782-11e7-873b-253ab70b6208.png">

Here's a save with an NPC who has equipped an M9 with a pistol bayonet attached. Spawn a debug monster a bit up and the NPC will close to target (per #19798), fire till empty and then start using the bayonet.  [Bryants Store.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1243871/Bryants.Store.zip)

**Comment by Coolthulhu** [comment]
Pistol bayonets don't have reach attacks.

**Comment by Leland** [comment]
Aha, can confirm. Wonder if related to #21328.
