### ISSUE TITLE
Adding more linting rules

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#21572]
I want to add more linting rules to cover all types of json objects in `/data/json` folder. The change will be rather big. Should I split it to multiple PRs?

Updated WIP linting configuration is here now: https://github.com/ZhilkinSerg/Cataclysm-DDA/blob/lint-more-rules/tools/format/format.conf

**Comment by DangerNoodle** [comment]
Will this update the online linting tool @narc0tiq has set up as well? If not, pinging them just in case.

**Comment by DangerNoodle** [comment]
My apologies, I was browsing both issues and pull request, and got this mixed up.

**Comment by Leland** [comment]
Woah, nice work. Did you write all this manually?

RE: making this multiple PRs: most likely. Additionally, [this big one needs](https://github.com/ZhilkinSerg/Cataclysm-DDA/commit/6fa29463df8890ba11565ae292967218127b86b0) to be multiple _commits_. That's >900 lines changed without a commit description of what's been changed and why. Breaking that out and adding some insight will help review and help future devs doing git blame.

**Comment by ZhilkinSerg** [comment]
> Woah, nice work. Did you write all this manually?

Yes,manually. That was copy-paste most of the time.

I believe it will be possible to reduce rules even more, so final changes will be smaller.

**Comment by ZhilkinSerg** [comment]
Firts part is here - #21585

**Comment by kevingranade** [comment]
No need for this issue, can be tracked in individual PRs.
