### ISSUE TITLE
Engines won't turn off

### ISSUE THREAD

**Issue by wilsonns** [CleverRaven/Cataclysm-DDA#21582]
The engines of any vehicle I get or spawn on the world won't stop no matter what. It keeps running until the gas/diesel is depleted and the Vehicle Design screen still shows the engine is on even without fuel. When out of fuel, the game displays that the vehicle got not enough engines to move.

Any clue on what to do? It's the first time I got something done in this game without cheating. I'd hate to have to start it over.

**Comment by wilsonns** [comment]
Edit: I'm playing on android

**Comment by kevingranade** [comment]
If you were driving around, its possible an impact damaged the control
linkages.

**Comment by wilsonns** [comment]
@kevingranade It happens to intact spawned vehicles.

**Comment by Cosmitz** [comment]
Tested with an intact, spawned, Security Van, while the diesel engines didn't lose fuel, the batteries themselves did lose charge. That's with it inside my view/reality bubble.

**Comment by Leland** [comment]
@wilsonns this appears to be fixed in the more up to date PC versions. I'd recommend double-checking yourself.

You may want to open an issue on the Android repo. I believe it's this one:  https://github.com/a1studmuffin/Cataclysm-DDA-Android

Closing for now.
