### ISSUE TITLE
What are the dimensions of tile?

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#21599]
Some [old topic on official forums](http://smf.cataclysmdda.com/index.php?topic=4500) suggests tile size is 1 square meter (4 square feet).

Player character with speed 100 travels approximately 8 tiles per minute when walking. This gives speed of approximately 0,5 km/h which is one magnitude lower than walking speed of average human (5 km/h).

So what the dimensions are like?

**Comment by angoddu** [comment]
It seems reasonable to have players move slower because the years are so much shorter than real years. They may have done that to balance out the movement rules

**Comment by Night-Pryanik** [comment]
I suspect that dimensions are non-linear and vary in terms of cars, buildings, monsters and other.

**Comment by BevapDin** [comment]
Tiles are an abstraction. They are as big and as small as they need to be. They are as small as a rat (which occupies a whole tile), they are as big as a brute (which also occupies a whole tile).

Use whatever size has been established *in a specific context*.

Compare for example simple cars that are 4 tiles width (cars usually are about 2m width). You can put items with a volume of up to 1000l (1m³) in a tile (and on some tiles even more). Roads (two lanes) are 16 tiles width. And so on.

Nothing good ever comes out of this question.

**Comment by AlecWhite** [comment]
As with any other rogue-like, or tile-based game. A tile is a big as it needs to be.

**Comment by CoroNaut** [comment]
There is no all-encompassing unit of length in the game. Trying to give anything a size or length will conflict it with various other elements of the game. In other words, this is a world that stretches and contracts depending on what your individual use for the length/size is.

**Comment by ZhilkinSerg** [comment]
Thanks, guys. I've tried to figure out dimensions to balance practicing of `athletics` skill in [my `dda-lua-skills` mod](http://smf.cataclysmdda.com/index.php?topic=14861.0). I guess I will try to balance it depending on players feedback.
