### ISSUE TITLE
Dynamic NPCs don't follow No NPC pickup zones

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#21590]
Wandering NPCs ignore my zones. This is very annoying because when they steal my stuff, I have to kill them to get it back which makes my character depressed. I end up having to debug myself the psychopath mutation to kill them then set it back after.

### Expected Behavior
Random NPCs leave stuff in No NPC pickup alone
### Actual behavior
NPCs steal my stuff
### Steps to reproduce the behavior
Set up No NPC pickup zone
Drop valuable items in zone
Spawn NPC
Exit initial conversation
Watch as they walk right up to your stuff and take it

**Comment by ituluwituluwzev** [comment]
When they are not your companions, they are strangers who naturally do not respect your zone. This works as intended.

Killing thief NPC giving hefty morale penulty is counter-intuitive, but there are ways to work-around.

**Comment by angoddu** [comment]
Could there be a way to decrease the morale penalty based on the value of the stuff stolen?

**Comment by DangerNoodle** [comment]
It is however infamous for this behavior occurring after the NPC in question spawns inside your house.

**Comment by angoddu** [comment]
They even steal out of the shopping cart that I am actively dragging. It ends up being that I have to kill all NPCs that I don't immediately recruit

**Comment by Chezzo** [comment]
I think it is only NPCs who are on your team who are affected by the no pickup rule and not random NPCs.

**Comment by angoddu** [comment]
It would be nice if there was a system so NPCs wouldn't pass through doors marked with a "Do not enter" sign (or some similar mechanic) and wouldn't steal from a cart that I am actively dragging. Or maybe add a lock item to lock doors and such where you have the key

**Comment by DangerNoodle** [comment]
Or if there was a way to mark territory and ensure that only NPCs who are aggressive enough to trespass would do so, and in particular if this flags them as acceptable to attack. NPCs attacking the player for trespassing and stealing is common in video games, allowing the player to do so without a morale penalty would avoid part of the player annoyance of this.

Likewise, the stereotypical dynamic NPC that walks up to you only to say "this is my territory" deserves to be flagged as acceptable to kill, or at least as a smaller penalty than killing a complete innocent. Legally this would be excessive in most states, but this is both post-apocalypse and a video game.

**Comment by angoddu** [comment]
I 100% agree with DangerNoodle's idea. I could totally see there being signs up that warn people about trespassing. 

Likewise, the other NPC that shows up and says "Put your hands up" should also have no penalty/less of a penalty to kill on the spot.

**Comment by kevingranade** [comment]
As far as the op, this is working as intended, random NPCs don't know or care about your no pick up zone.
If you want to brainstorm potential NPC features, please use the forums.  Also please use the search function both here and there, as this has already been discussed extensively.
