### ISSUE TITLE
Compilation issue on OSX (clang)

### ISSUE THREAD

**Issue by pierredavidbelanger** [CleverRaven/Cataclysm-DDA#21595]
Since this commit 02c8182597c4932517e1432d494d963c91c11ea7 I guess, I now need to specify `CLANG=clang++` instead of what the doc says (`CLANG=1`) to compile on OSX, or else I get this error:

```
$ make RELEASE=1 LTO=1 TILES=1 SOUND=1 LOCALIZE=0 CLANG=1
1  -DRELEASE -DGIT_VERSION -DTILES -ffast-math -O3 -flto -Wall -Wextra -fsigned-char -Werror -std=c++11 -MMD -MP -D_THREAD_SAFE -I/usr/local/include/SDL2 -DSDL_SOUND -I/opt/local/include/SDL2 -D_THREAD_SAFE -D_THREAD_SAFE -I/usr/local/include/SDL2 -D_THREAD_SAFE -I/usr/local/include/SDL2 -c src/action.cpp -o obj/tiles/action.o
make: 1: No such file or directory
make: *** [obj/tiles/action.o] Error 1
```

It seems the Makefile is using the CLANG variable value as is.

**Comment by CaptManiac** [comment]
This also happens on both x64 Ubuntu 16.04.3 and ARM raspbian OS's. Started with Build #6665.

**Comment by Treah** [comment]
This PR is set to resolve this problem. 
#21587
