### ISSUE TITLE
Lit flaming arrows (from flammable) can sit in inventory forever without consequence

### ISSUE THREAD

**Issue by Cosmitz** [CleverRaven/Cataclysm-DDA#21608]
This is a remnant of the time where you could pre-nock an arrow and keep it in your bow ready to fire. Given 'new' mechanics, the arrow should be allowed to burn out from from the inventory after a certain period of time. Burnt arrows aren't much use, either disappear completely or leave behind 'burnt pointy stick' or something akin.

**Comment by Theundyingcode** [comment]
How about adding a charges transform like how glowsticks die? Say, after 5 or 10 turns it becomes a burnt-out arrow.  Which has no use other than it's made of wood.

**Comment by wapcaplet** [comment]
Still reproducible in 0.E-9737-g511ddcb179
