### ISSUE TITLE
Display sequence issue with bullets passing through?

### ISSUE THREAD

**Issue by Cosmitz** [CleverRaven/Cataclysm-DDA#21602]
[This](https://user-images.githubusercontent.com/7086599/29190426-c684f792-7e22-11e7-8d42-988745e9942d.png)

Shotgun slug passed through the skeletal dog but didn't? Headshot info issued after the other effect issue? I'm confused.

**Comment by Leland** [comment]
Difficult to debug without a savefile or steps to reproduce.

**Comment by Cosmitz** [comment]
Sorry, it was on a quick trial run of something different and it wasn't saved. Minus spawning a lot of zombies and shooting at them with a car full of tanks as backdrop i can't think of a proper way to reproduce this.

**Comment by Leland** [comment]
Closing due as unreproducible. If OP or anyone else either encounters this again or can reproduce please ping me here to reopen.

**Comment by Leland** [comment]
Ahh, retribution. Existing issue in #7533.

**Comment by Cosmitz** [comment]
That's a fantastic catch. That's exactly it. Nice one.
