### ISSUE TITLE
Ally NPC VS. Hostile NPC in-fighting not occurring

### ISSUE THREAD

**Issue by SlumberKnight-Studios** [CleverRaven/Cataclysm-DDA#21614]
0.C-23349-g30854fe
SDL
Windows 7

When encountering NPC's that turn hostile after dialogue; i.e: failing to persuade them you mean no harm, Allies fail to attack them.
They also decide to attack naturally occurring hostile NPC's last second.

**Comment by Night-Pryanik** [comment]
Friendly NPCs don't attack hostile NPCs at all, or only fire at them at point-plank range, as described in #19798?

**Comment by SlumberKnight-Studios** [comment]
none at all, they don't even try and get within point blank range.

**Comment by SlumberKnight-Studios** [comment]
although if they were in point blank range, I believe they would attack, so after reading that post, yes, it is a similar problem.

**Comment by Leland** [comment]
@SlumberKnight-Studios try giving your NPCs melee weapons. If they close to the hostile NPC and engage, this is a duplicate issue and can be merged with #19798.

**Comment by kevingranade** [comment]
Assuming this is the same, closing in favor of the other issue.
