### ISSUE TITLE
In square distance mode, creatures can take 100+ turns

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#21615]
The behavior existed "in design" for quite a while, but I "unmasked" it (at least on Windows, it might have never been masked on Linux) in #21462 by removing the bug that prevented this current bug from happening.

To reproduce:
* Set square distance
* Spawn a copbot or other monster smart enough not to bash if it can go around
* Spawn a wall of reinforced glass around self. Doesn't need to be reinforced glass - can be any obstacle that is too tough for the smart critter to consider bashing
* Have the copbot reach the wall and let it keep trying to attack

The copbot will take around 100 turns per game turn. Copbot is best for it because it has a 0 cooldown ability to spam sounds, so it clearly shows that it's not just random lag.

This happens because:
* Cost to move from point `p1` to `p2` while trying to reach point `p3` is scaled by how close it brings the critter to point `p3`
* Moving orthogonally to direction from `p1` to `p3` in square distance almost always covers 0 distance, meaning low cap of 1 move is used instead of proper cost
* The critter then has no other choice but to keep repeating orthogonal movements

The simplest fix would be to low cap the move cost at something higher than 1 moves. It can't be higher than `original_cost / sqrt(2)`, otherwise it will break the parity between square and euclidean distance. Low cap of 50%?

**Comment by TheWebfrog** [comment]
Nice find!

**Comment by ZhilkinSerg** [comment]
I've possibly had similar issue wtih circular distances in #21803.

**Comment by DanmakuDan** [comment]
I think the cost for moving from `p1` to `p2` should calculate the difference in distance from `p3` using both square and circular distances. If both are zero, then the move scaling should default to 100% instead of using the minimum 1 move point. It indicates the move would have been a lag issue for both types of distance modes.

**Comment by Mooses2k** [comment]
Close this if we're deprecating square distance?

**Comment by kevingranade** [comment]
We're not deprecating it, just changing the default.
