### ISSUE TITLE
[6679] Game freezes when moving onto corpse drop piles

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#21622]
### Expected behavior
Normal navigation.

### Actual behavior
When attempting to move onto the tile on which a zed has been killed, the game will print the abbreviated item list as normal, but the game will hang before the player is actually moved. This will occur regardless of the turn gap and requires a game restart.

### Steps to reproduce the behavior
Using E or the AIM to move items off the tile will work as normal most of the time, but will occasionally result in a freeze, as well. I have been unable to consistently reproduce this latter instance of the bug. Moving the corpse does not prevent the bug from occurring, though moving the whole pile does seem to do so.

**Comment by sick-trigger** [comment]
i was experiencing this on a recent build around the time it was reported, but no longer am on the current build (6688). might have been inadvertently fixed.

**Comment by railmonkey** [comment]
The issue does seem to have been inadvertently fixed, yes, though I couldn't say why. I suspect it has something to do with the new hourglass animation. Further investigation showed that the game did not actually hang, but seemed to stop automatically redrawing. Normal command keys would do nothing, but pressing spacebar could redraw and occasionally break the game loose.  This also occasionally happened after killing a zed.
