### ISSUE TITLE
Is it possible to dynamically set flags?

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#21632]
I wasn't sure where else to post this. If there is a better place to put this please let me know. 

I'm trying to implement a change where players can add a lock to doors and windows so that NPCs can't use them but the player can. Is it possible to add a flag to pre-established terrain or would you need to create duplicate terrain tiles to add a flag to it? I was debating between two different ways to do this: the player uses the lock on a door/window to set that flag or have them use the construction menu to build a locked door with the pre-terrain as a door. The prior would be my preferred method of doing this but I could do the latter of the dynamic tag setting isn't a possibility.

**Comment by Coolthulhu** [comment]
No, terrain cannot store any information right now.

The variant with construction menu is unacceptably clunky. Instead it could be accessed by double-closing the door - ie. closing a closed door would attempt to lock it.

But then, locked doors are hardcoded to only be locked from the outside. Any inside tile can open locked doors and there are no keys that can open doors from the outside without picking. And since you can't store information in terrain, there can't be per-door keys until that is somehow solved.

**Comment by angoddu** [comment]
> Any inside tile can open locked doors
I have found that some doors can not be opened from the inside. Yesterday I was in a museum and after I got in one of the doors the other wouldn't open from the inside. But that isn't what this issue is about.

> The variant with construction menu is unacceptably clunky
I 100% agree. It would require at least 6 new terrain tiles and construction options and that is just for the doors that I know of. 

>  Instead it could be accessed by double-closing the door
That would be a nice and clean solution if the locks were bidirectional. I created a "padlock" item that I was planning on using for the locking feature but since terrain can't store data then that also wouldn't work.

I could look into how the terrain is loaded to make it capable of storing data but that may be a bit beyond my current understanding of how the code functions.

**Comment by ZhilkinSerg** [comment]
I believe it can be done with lua - something like changing terrain on selected tile for locking/unlocking.

**Comment by angoddu** [comment]
But once the tile is unloaded, like you walking too far away, then the terrain would reset back to it's original state. I could possible add a field in the player object to hold this info but then that might break things when a different character comes around.

**Comment by ZhilkinSerg** [comment]
> But once the tile is unloaded, like you walking too far away, then the terrain would reset back to it's original state. I could possible add a field in the player object to hold this info but then that might break things when a different character comes around.

Nope, the tile won't be changed when the character goes away.

**Comment by angoddu** [comment]
What about when the game reloads? Where would the locked data get saved? 

> changing terrain on selected tile for locking/unlocking.

And would this mean We would need to make a new terrain object for the locked variants?

**Comment by ZhilkinSerg** [comment]
> And would this mean We would need to make a new terrain object for the locked variants?

Yes and no. Technically you can use some existing terrain, but you can also add some new terrain.

**Comment by BevapDin** [comment]
@ZhilkinSerg you probably talk about changing a terrain **type**. But that change applies to all terrain tiles of that type. If you add a flag X to the terrain type "dirt", all tiles of that dirt type will have that flag.

**Comment by ZhilkinSerg** [comment]
> @ZhilkinSerg you probably talk about changing a terrain type. But that change applies to all terrain tiles of that type. If you add a flag X to the terrain type "dirt", all tiles of that dirt type will have that flag.

I am talking about changing certain map tiles.

Player activates some item with iuse function coded in lua. This function checks terrain type in some radius (remote lock) or in nearby tiles (suggesting you are standing near the door which you want to close). The function then displays menu showing info about the terrain tiles of the certain type (like door/window) - something which was done in `entity_scanner` in the [dda-lua-items](https://github.com/ZhilkinSerg/Cataclysm-DDA-LUA/blob/master/dda-lua-items/preload.lua) or directly changes these tile to some `locked` variant.

**Comment by angoddu** [comment]
I just looked at the raw map file with the data, it could be possible to add a flag to that file to indicate where the locked tiles are. I would need to do more digging to find the code that loads and saves the map tiles but I think it could be done

**Comment by ZhilkinSerg** [comment]
Attached mod ([dda-lua-keyring.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1223504/dda-lua-keyring.zip)) adds `keyring item` with lua-iuse function. It is possible to `lock` or `unlock` nearby eight tiles around player character. When locked the terrain will be changed from `t_door_o` to `t_wall_metal` and vice versa.

The code is rather ugly as I have to compare terrain names, not ids.

**Comment by angoddu** [comment]
I think I figured out how to do what I need to for this to work. Thanks for all the feedback
