### ISSUE TITLE
7.62x51mm ammo comes out as 308 casings

### ISSUE THREAD

**Issue by Cosmitz** [CleverRaven/Cataclysm-DDA#21633]
It's technically correct gun-wise, and code wise is fine, but the naming scheme could be reworked for this class, like..

".308 7.62x51mm M80" instead of "7.62x51mm M80". It makes a bit of a contradiction but a lot more sense to the player when he sees .308 casings coming out of something called a .308 ammo. Just visual/informative.

**Comment by illi-kun** [comment]
Maybe it's better to add a note about compatibility with .308 to ammo description instead of name?

**Comment by kevingranade** [comment]
It should not be compatible unless we have a mechanism to make it less
reliable when fired in the opposing chamber, they are not the same casing.

**Comment by Cosmitz** [comment]
While the real world considerations are a matter of reliability, not incompatibility, the messier issue here is just one of the game producing an unexpected result out of a casing which then can't be reloaded back to its parent. A few guns use both .308 and M80 but there isn't a direct way of working with both of the ammo.

**Comment by kevingranade** [comment]
That shouldn't be a problem, look at cycle_weapon() in
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/ranged.cpp
It just spawns whatever the item type the ammo item says to, so 7.62x51mm
just needs to be updated to be crafted from and drop 7.62x51mm casings.

**Comment by lancewf** [comment]
@Cosmitz you can create reloaded_762_51 ammo from .308 casings? So, then you can use the casing from 7.62x51mm ammo to recreate ammo for the same gun. 

If the main propose of this issue is to avoid the confusion of .308 casing coming from 7.62x51mm ammo then we can merge this PR https://github.com/CleverRaven/Cataclysm-DDA/pull/24811.
