### ISSUE TITLE
Game doesn't check for jack LIFT quality when removing parts, only uses strenght

### ISSUE THREAD

**Issue by Cosmitz** [CleverRaven/Cataclysm-DDA#21639]
![This](https://user-images.githubusercontent.com/7086599/29335381-1a16ab0a-8213-11e7-809b-371e976e8508.png)

While usually i had enough strenght to just remove them, i have a cold now dropping my STR to 2, 1 under the required 3, and even though i have a scissors jack, i can't remove the swappable cell. Though to be fair, i wonder why there are even requirements given it's supposed to be easily swappable.

PS: Proof of scissors and STR

![image](https://user-images.githubusercontent.com/7086599/29335424-4948a16c-8213-11e7-9810-2f867065d139.png)

Possibly linked to #21605 - Wheels need Jacking, but the rest of the equipment checks for mass limits, and the mass limits may not be used.

**Comment by Cosmitz** [comment]
Did further testing and indeed, the core issue is that the game ignores the mass limits check of jacks and relies on strenght alone to remove parts. Given that it's usually not an issue, strenght 1-3, it can go unnoticed, but the linked issue in #21605 requires strenght 7.

**Comment by atlaua** [comment]
Just for future reference: As I told the OP on IRC, this has simply been a mixup of the LIFT and JACK qualities. No bug, just a misunderstanding.
