### ISSUE TITLE
Ursine serum recipe should use both components

### ISSUE THREAD

**Issue by ampnaman** [CleverRaven/Cataclysm-DDA#21643]
![ursine](https://user-images.githubusercontent.com/30443081/29361378-fbe57560-82b9-11e7-9009-d80a8c34512f.png)

Build 6683
Just noticed this, currently withholding myself from turning super bear. A simple change from 'OR' to 'AND' should suffice to fix the recipe code.

### Expected Behavior
Ursine serum recipe should use both components, similar to other serum types

### Actual behavior
Currently can make with ursine mutagen 'OR' just blob glob

### Steps to reproduce the behavior
Load up the latest and check the recipe

**Comment by Cyrano7** [comment]
@ampnaman So the recipe is showing up as just 2 ursine mutagen in my new vanilla game and in the json recipe file. Maybe you are you using a mod that changes that?

**Comment by ampnaman** [comment]
@Cyrano7 Yeah, on testing I found that PK's rebalancing did add that blob glob line. Issue is with PK mod.

**Comment by Leland** [comment]
@pisskop see above – don't strictly need to keep this issue open; just thought you might want to be aware.
