### ISSUE TITLE
Blindfolded NPC can read book.

### ISSUE THREAD

**Issue by ituluwituluwzev** [CleverRaven/Cataclysm-DDA#21642]
### Expected Behavior
Blindfolded NPC cannot read book.
### Actual behavior
They can.
### Steps to reproduce the behavior
Blindfold an NPC and read book with them. In fact, they can follow you, find enemy, smash corpse, as if they can see at all. It's difficult to tell if their melee is affected.

**Comment by baraba3** [comment]
you read book to npc.I think message goes you read out loud...

**Comment by ituluwituluwzev** [comment]
I have NPC read for me because I am illiterate. They also do other things implying that they are not affected by blindfold.

**Comment by Ramza13** [comment]
Just tested quickly and blindfolded NPC did not smash corpse but did read to me.
