### ISSUE TITLE
No way to see World Mod Settings after it's made

### ISSUE THREAD

**Issue by EricFedrowisch** [CleverRaven/Cataclysm-DDA#21658]
### Expected Behavior
In the title screen World menu, it would be nice if there were an option to see what the world settings and mods are for a given world. While you can see many of the world setting in the options menu once in game, this doesn't include mods.

**Comment by ChronicDankDisasterAlgorithm** [comment]
I too have wondered if there was a way to view this in game, and is a feature I would use/like to see.
