### ISSUE TITLE
Bandoliers no quicker than reloading from inventory

### ISSUE THREAD

**Issue by EricFedrowisch** [CleverRaven/Cataclysm-DDA#21660]
### Expected Behavior
According to their description, reloading from a rifle, wrist or shotgun bandolier should be faster than normal reloading from inventory. 

Here we see using various clip holders seems to work as expected in that it is faster than reloading from the inventory. It takes approximately 66% of the normal time to reload from an ammo pouch than it does from inventory. Expected behavior is that reloading from a bandolier should be faster, probably comparable to the 66% normal time as for clips.

<img width="1552" alt="screen shot 2017-08-18 at 10 03 29 am" src="https://user-images.githubusercontent.com/5952322/29465027-6b5f8ab8-83fd-11e7-92a5-e5b126828f5a.png">

### Actual behavior

However, for both rifle and shotguns, the speed of reload from bandolier and from inventory is exactly the same.
<img width="1552" alt="screen shot 2017-08-18 at 10 00 03 am" src="https://user-images.githubusercontent.com/5952322/29464978-474ca7d2-83fd-11e7-90bf-203c5af5d1ae.png">

<img width="1552" alt="screen shot 2017-08-18 at 10 07 36 am" src="https://user-images.githubusercontent.com/5952322/29465013-5e04e35e-83fd-11e7-85dd-fc0ff9ca5e76.png">

### Steps to reproduce the behavior
Wish up rifle or shotgun, ammo and bandoliers. Wear bandoliers and wield weapon. Reload shotgun/rifle. Compare the charts.

**Comment by BorkBorkGoesTheCode** [comment]
So wielding from inventory isn't penalized anymore?

**Comment by EricFedrowisch** [comment]
Reloading doesn't seem to be any faster from bandoliers than from inventory, which is bad bc wearing them costs some encumbrance. So right now they are broken and only have negatives with no upside.
