### ISSUE TITLE
The golden violin doesn't spawn

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#21666]
ChaosVolt noted that the golden violin has a spawn in the music store, but the spawn doesn't seem to work under any settings.

**Comment by codemime** [comment]
The chance is fairly small, only 5%. You probably weren't lucky enough.

**Comment by BorkBorkGoesTheCode** [comment]
Just set it to 80 and generated a new world, debugged map visibility and teleported to every music store: nothing. I did get it to spawn by setting it to 1.

**Comment by BorkBorkGoesTheCode** [comment]
Set it to 20 and still got nothing.

**Comment by Noctifer-de-Mortem** [comment]
The issue is that`add` no longer works. 

````
      "add": [
        { "item": "violin_golden", "x": 21, "y": 8, "chance": 95 }
      ]
````

The definition is not correct.

**Comment by Cosmitz** [comment]
@Noctifer-de-Mortem "Add" works as it does have a compatibility added in the codebase. Did extensive testing and it's just a matter of it being fantastically rare.

At 95, you have a one in 95 chance of it spawning for each music store. I debug-spawned around 30-40 stores before it spawned in one. 

Now, the matter of even having that rare of a spawn for such a trivial item... that's another discussion.

**Comment by Leland** [comment]
Closing per notes above. @BorkBorkGoesTheCode feel free to submit a PR bumping up the chance of this spawning, definitely does not need to be so rare.
