### ISSUE TITLE
Starting in city location with City Size at 0 freezes game

### ISSUE THREAD

**Issue by Leland** [CleverRaven/Cataclysm-DDA#21667]
### Steps to reproduce the behavior

1. In world creation, set "Size of cities" to 0.
    The help text notes that this disables cities entirely.
2. Create a character in a scenario that only has city-based starting locations. An example is the "missed" scenario.
3. Finish character creation. The game will display a dialog, "Please wait as we build your world," as the game steadily takes up more memory.

I have a hunch that what's going on behind the scenes is, with #21212, the game is generating more and more overmaps to find a suitable location for a starting location special. That will never happen, however, as no spawn locations have suitable areas for placement.

**Comment by laeaton2001** [comment]
I could add a flag to the scenarios JSON to mark scenarios as a city start & then add a check in newcharacter.cpp to filter out city starts when the active world options have city size set to 0.
My only concern is this will hide scenarios from the player with no feedback as to why.

**Comment by Night-Pryanik** [comment]
And add a remark to the options description, like "This disables cities and all the scenarios with city start".

**Comment by Coolthulhu** [comment]
Color the scenarios dark gray, sort them to the last on the list, then in their description prepend "This scenario is not available in this world due to city size settings".
