### ISSUE TITLE
NPC Enters Infinite Loop While Wielding A Ranged Weapon

### ISSUE THREAD

**Issue by JamesStrife** [CleverRaven/Cataclysm-DDA#21670]
Version - 0.C-23495-ge3d4189
Build - 6693(Tiles)
WIN 10 1703 15063.540
Save: https://www.dropbox.com/s/ixdkwhqbomhk4db/backup_witherror.zip?dl=0

### Expected Behavior
NPC Moves to be used or otherwise completed while holding ranged weapon

### Actual behavior
NPC enters Infinite loop while holding ranged weapon

### Steps to reproduce the behavior
NPC with ranged weapon equipped will eventually enter loop

Can confirm NPC does not have to be friendly.
Can confirm that debug equipping the NPC with a melee weapon seems to prevent the loop.

![image](https://user-images.githubusercontent.com/24858167/29482761-a559b83e-8465-11e7-8c01-3b88f7c140ab.png)

**Comment by Leland** [comment]
Can confirm.

**Comment by smokeyphil** [comment]
I too can confirm that this happens. I can also cause it to happen on a clean install with the launcher. 

![Uploading image.png…]()

**Comment by Vidiveni** [comment]
Is there a way to turn off debug mode after this happens?

**Comment by JamesStrife** [comment]
Further testing on my install confirms this loop appears in build 6690.
Build 6689 shows no signs.
[http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/6690/changes](url)

**Comment by JamesStrife** [comment]
Yes. There is a "toggle debug mode" keybind that can be set.

**Comment by AMurkin** [comment]
Possibly caused by that [change](https://github.com/CleverRaven/Cataclysm-DDA/commit/4258cdfef2f439899be96d93cb9bf97496813d29#diff-33ebc80f8d3736e82052b90144238cc0R1685). I've not test it.

**Comment by Leland** [comment]
Intriguingly, my NPCs' heads have occasionally been exploding following those debug notices.

See, too: http://smf.cataclysmdda.com/index.php?topic=14891.0

And: http://imgur.com/a/knPjb

![](https://i.imgur.com/KQYV2i1.png)
