### ISSUE TITLE
Map font too small

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#21697]
Since jenkins build 6699 the font in map is so small it's barely readable.

![image](https://user-images.githubusercontent.com/19891532/29582865-9147ca04-877e-11e7-91d6-d2be63e2b051.png)

**Comment by Noctifer-de-Mortem** [comment]
https://discordapp.com/channels/@me/290267442125602816

Build 6738 still show small fount.

**Comment by Noctifer-de-Mortem** [comment]
https://cdn.discordapp.com/attachments/290267442125602816/354786149161631765/image.png

Build 6738 still shows small font.

**Comment by AMurkin** [comment]
Probably settings were saved in bugged build. If so - edit `config/fonts.json`.

**Comment by Noctifer-de-Mortem** [comment]
Fonts.json wasn't moved to a new build, only options.json.
