### ISSUE TITLE
Cannot create ANY new vehicle from scratch

### ISSUE THREAD

**Issue by Sagan-Ro** [CleverRaven/Cataclysm-DDA#21695]
### Expected Behavior
Using Construction Menu (*) to Start New Vehicle from scratch with a constructed frame in inventory should go to the vehicle construction menu.

### Actual Behavior
After asking for a vehicle name, nothing happens.  No new vehicle is constructed, no menu(s) open, no debug messages/crashes/errors.

### Steps to reproduce the behavior
Construct or Debug Wish for a vehicle frame, then try to construct a vehicle from scratch with the Construction Menu (*).  Using Vehicle Additions Pack included with CDDA Experimental (Graphical/Tiles) from November 2016 to August 2017 (including current).  64-Bit Windows 10, 32-bit Windows 7, 32-bit Windows XP.  Error occurs with 32- and 64-bit versions of CDDA.

ADDITIONAL PROBLEM: Vehicle Additions Pack is outdated, and has been for months.  Please review and implement the updated fixes (like Vortex Engine/Vortex Generator actually working again) from:

http://smf.cataclysmdda.com/index.php?topic=8060.0
https://github.com/Maddremor/cdda-Blazemod

**Comment by Zireael07** [comment]
Does this happen if you are NOT using VAP?

**Comment by BorkBorkGoesTheCode** [comment]
@Sagan-Ro can you make a vehicle by using two identical frames instead of one?

**Comment by Sagan-Ro** [comment]
Zireael07:
I don't know, I haven't tried.  I want the extra stuff in the VAP, but it has been broken for a long time, and I signed up for GitHub and opened this issue because I'm sick of waiting.  Not trying to be rude, but if something is an option included as part of the base package, then it should work when used exclusively with the base package.  Right?

Bork:
I have not attempted it with two frames yet.  I only heard of that as a possible work-around today, from:
https://www.reddit.com/r/cataclysmdda/comments/5as4s3/cant_place_vehicle_frames_error/

Still, if this problem has been present long enough for users to come up with workarounds (Reddit OP was 9 months ago), why has it not been fixed?  I am assuming the problem must be more complicated than an off-by-1 error or extra line of code someone forgot to delete.  I certainly hope something so basic and annoying hasn't just "fallen through the cracks".  Vehicles are central to this game, and not being able to make them without stumbling on an obtuse workaround is pretty serious, in my opinion.  I've been aware of this problem for months, just not the workaround.

**Comment by BorkBorkGoesTheCode** [comment]
I implemented a fix for it in master last year: https://github.com/CleverRaven/Cataclysm-DDA/commit/ecb0fadc0bd3570cffd595c922f6bb090fcddaf2
USSDefiant proposed the fix here:
Unless you're using an exp. from before then or the other Blazemod without this fix, I have no idea what is going on.

**Comment by Sagan-Ro** [comment]
No sir, I am using the experimental from last week, and the included VAP.  I don't use the external CDDA launcher, just what's in the .ZIP file from:

http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/
or
http://dev.narc.ro/cataclysm/jenkins-latest/Windows_x64/Tiles/

I have been thinking, and I actually may have used the "2 frames makes it work" approach without knowing it.  I was trying everything, attempted to construct a vehicle about 20 times during a irritating day back in July, and I only got a single attempt to work.  I am uncertain, but I think that time I had 5 diamond frames in my inventory and laying around (I had cheat-spawned some vehicles and disassembled them so I could GET a vehicle to work with.)

I am pretty new to CDDA, so I went through the new Wiki's advice on how to create a vehicle from scratch (have all proper tools like hacksaw, welder, and integrated toolset, vehicle frame, then use the Construction Menu, and it *should* have worked).  I didn't even know about the Hammerspace debug mutation at that point, so I should have had all necessary items since I could work on vehicles that already existed.  But it's getting really old spending a couple of days of in-game time just stripping a vehicle so I can rebuild it, then dealing with the hunger, thirst, and fatigue.  I'm also really hating all the hoops I'm having to jump through just to get this stupid game to function, merely because documentation is nil and bugs keep popping up.

Example: I spent 3 weeks not being able to turn my headlights on because I had installed "drive by wire controls" instead of the "controls" item.  But the headlights, dome lights, stereo, etc. don't appear in the ^ menu unless "controls" are installed ON TOP OF the "drive by wire controls".  I still don't know if THAT's a glitch or the result of some obtuse reasoning on the part of a coder.

**Comment by Cosmitz** [comment]
I made a world with the latest experimental and the bundled VAP.

I could start a construction with a variety of frames, and to boot, no tools, just a fresh character, which is what you need to be able to start up a vehicle construction.

![image](https://user-images.githubusercontent.com/7086599/29581186-3e24af6a-8781-11e7-82f0-6220ae601c61.png)

So it definitely is something else.

**Comment by Sagan-Ro** [comment]
Typical, I seem to attract rare and strange bugs.  :P

I have deleted CDDA and recreated players from scratch 3 times.  I don't know why things work for you and not for me.  If I can't figure it out and it keeps happening, then I will just .ZIP my save up and post it on Dropbox.  Or who knows, maybe everything will work... *gasp* like MAGIC!

Don't I wish...

Still, that brings us to the other issue: when will the updates to the VAP be merged into CDDA?  The vortex stuff (engine/generator) is definitely broken with the bundled VAP.  Unless you are annoyingly fortunate with that issue as well.  ;)  But they work in the updated fork at https://github.com/Maddremor/cdda-Blazemod, albeit resulting in instant deafness and "safe" vehicle speed approaching that of light.

**Comment by Sagan-Ro** [comment]
I'll be darned... it IS working now!  And it doesn't need 2 frames, just one!  WOOHOO!

But dang it, now my font is all screwed up, and it's more like size 5 instead of 10.  Bugs are like hydras, deal with one and hold on.  AGH.

**Comment by Leland** [comment]
@Sagan-Ro glad it's working now – closing issue accordingly.
