### ISSUE TITLE
Wearing non-WATERPROOF gear over WATERPROOF ones makes character loses their waterproofing

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#21693]
Wearing duffel back over nomad gear shouldn't make character wet under the rain.

0.C-6700, Windows XP SP3, curses.

**Comment by Cosmitz** [comment]
Is it possible this also applies to any other tags? Like Water-friendly? I'm pretty sure i wasn't getting the proper water-friendly morale bonus multiple times.

**Comment by Coolthulhu** [comment]
Waterproofing is calculated with outermost items.
Water friendliness is exclusive: only water-friendly items on the part or it's not water-friendly.

**Comment by Night-Pryanik** [comment]
> Waterproofing is calculated with outermost items.

Maybe items with BELTED or WAIST flag should be excluded from the calculations?

**Comment by mrkybe** [comment]
Or backpacks like duffel bag should be made water-proof.  This is reasonable behavior imo.

**Comment by Theundyingcode** [comment]
Yeah but things like elbow-pads aren't waterproof but wearing them over a raincoat shouldn't make you wet. IRL i doubt you'd even notice they were wet.

**Comment by mrkybe** [comment]
Wearing a rifle with a sling shouldn't make me wet.  The extra insult to injury here is that I installed weapon waterproofing to the rifle.
