### ISSUE TITLE
Automate compression of tile images

### ISSUE THREAD

**Issue by Leland** [CleverRaven/Cataclysm-DDA#21690]
See notes and discussion over yonder: https://github.com/CleverRaven/Cataclysm-DDA/pull/21685#issuecomment-323845464

**Comment by Coolthulhu** [comment]
My take:
* Add compression as a makefile option, only used for `make bindist`
* Default to yes if relevant utils are detected
* Compare compressed/uncompressed images and issue a warning if they differ (optionally: have that be an error instead)
* Always pack the compressed files

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
