### ISSUE TITLE
Wiki Link Broken

### ISSUE THREAD

**Issue by Taichi22** [CleverRaven/Cataclysm-DDA#21708]
### Expected Behavior
Wiki 'This' hypertext opens 'Contributing.md'
### Actual behavior
Wiki 'This' hypertext opens 404.
### Steps to reproduce the behavior
Open the 'Wiki' tab, then click on 'This' hyperlink.

I was poking around and figured I'd try to contribute to the code.
Someone should go fix the link on the wiki page, I don't have the rights to do so, but it's just a hyperlink issue.
Right now it links to: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/CONTRIBUTING.md
While it should link to: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CONTRIBUTING.md

Might help get more contributors, it's a a really quick fix.

**Comment by Night-Pryanik** [comment]
I fixed this, thanks for good catch!
