### ISSUE TITLE
Crash when opening (E)at menu with no edible items.

### ISSUE THREAD

**Issue by chris-statzer** [CleverRaven/Cataclysm-DDA#21707]
### Expected Behavior
Pressing 'E' and seeing a 'there is nothing to consume' popup.
### Actual behavior
When the inventory is out of items and 'E' is pressed the program segfaults.
### Steps to reproduce the behavior
Using the 'E' menu when the inventory is free of edible items.

GDB Backtrace: https://gist.github.com/chris-statzer/a470716d4d86f1a5920799c5b318cf72

**Comment by chris-statzer** [comment]
Looks like its in the 'food_hint_provider' function. I don't know how to get a more meaningful picture of this like figuring out what item is doing it. Lemme see if I'm smart enough to place some debug prints in there...

**Comment by Night-Pryanik** [comment]
Possibly related to #21508?

**Comment by chris-statzer** [comment]
Seems likely, I'm seeing if I can track it down now, but my C++ skills are middling.

**Comment by chris-statzer** [comment]
I would like to be able to tell you exactly what kind of item and quantity is being hit when this happens, but I don't understand the encoding of these strings. Can I get some help with logging these? I'm just not sure how you guys are handing it, but display_name() and info() return weird encodings I can't use.

**Comment by chris-statzer** [comment]
Ah forgot about c_str()... I'm pretty sure it has to do with fluids on the ground. I can reproduce this reliably with 'clean water (1)' on the ground in range of the character when pressing 'E' for the consumables list. You can wish for clean water, drop it, press E and crash.

**Comment by chris-statzer** [comment]
I actually don't even understand what player::nutrition_for does.... returning an early 0 still shows nutrition info and does not crash at that point..... food_hint_provider seems to work just fine without that call unless I am missing something......

![2017-08-25-000325_642x283_scrot](https://user-images.githubusercontent.com/1041549/29675812-e10a1078-8928-11e7-990f-a721ea6f6241.png)

**Comment by chris-statzer** [comment]
I'm feeling like a simple null check on item_type::comestible should be a solution to this. I'm more than happy to make that change but would like someone to weigh in and tell me if this is correct?

if( !it.type->comestible ) return 0;

or something like that should prevent this?

**Comment by Coolthulhu** [comment]
```
if( !it.type->comestible ) return 0;
```

The `type` field is supposed to be (slowly) turned into a properly encapsulated member.
Use:
```
if( !it.is_comestible() ) return 0;
```
