### ISSUE TITLE
Skill Training with NPC while in a moving vehicle

### ISSUE THREAD

**Issue by mrkybe** [CleverRaven/Cataclysm-DDA#21712]
### Expected Behavior
Not allowed to talk to an NPC to complete a quest while in a moving vehicle, especially not allowed to do skill training by the NPC while in a moving vehicle.

### Actual behavior
Vehicle continues forward into lake until training is complete without any way to cancel the skill training ahead of time.  NPC teleports to correct relative position to player once in the lake, which is kind of weird.

### Steps to reproduce the behavior
Drive a vehicle on cruise control past an NPC and complete a quest with skill training as your reward.

Honestly I should have expected this.  RIP Safety Van.

**Comment by PlasmaChroma** [comment]
Once you are out of range and cannot listen to the NPC talk then there is no way for them to continue training you and the training should then abort.

**Comment by kevingranade** [comment]
Preventing training while the player is driving would be the simplest solution.

**Comment by l29ah** [comment]
I even succeeded to run over the NPC and the training continued after that.
