### ISSUE TITLE
Issues with "Icecoon's Arsenal" mod enabled together with "Generic Guns" mod

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#21728]
### Expected Behavior
Mods "Icecoon's Arsenal" and "Generic Guns" are expected to work together without debug warning messages.

### Actual behavior
Debug warning messages when both mods "Icecoon's Arsenal" and "Generic Guns"  are enabled in a world:

     DEBUG    : warnings for type "cw-24k":
    magazine "akmbigmag" holds incomaptible ammo ("308" instead of "762")
    magazine "akmmag" holds incomaptible ammo ("308" instead of "762")

     FUNCTION : void Item_factory::check_definitions() const
     FILE     : src/item_factory.cpp
     LINE     : 920

Same message for `cw-24k`, `cw-24`, `svs-24`, `cw-24m`, `cw-24m_hack`, `svs-24c` and `cw-24hack`.

### Steps to reproduce the behavior
1. Create new world in latest experimental (6719) with following mods:

- Dark Days Ahead;
- Icecoon's Arsenal;
- Generic Guns.

2. Create new player in this world.
3. Get debug warning messages.

**Comment by BorkBorkGoesTheCode** [comment]
Generic guns can't handle 7.62x39mm ammo_type. All the rifles mentioned refer to akmmags as 7.62x39 magazines instead of 308
