### ISSUE TITLE
Game crashes on startup on Linux 64bit

### ISSUE THREAD

**Issue by nshcat** [CleverRaven/Cataclysm-DDA#21729]
I'm trying to compile the **master branch** on ArchLinux 64bit, my system is up-to-date. I enabled both tiles and sound.

My System is a 2016 ThinkPad with integrated Intel graphics.

### Expected Behavior
Game starts up normally.

### Actual behavior
Game tries to start up, but immediately crashes with the following messages printed to the console:

```
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
*** Error in `./cataclysm-tiles': double free or corruption (fasttop): 0x0000006a08577140 ***
[1]    4821 abort (core dumped)  ./cataclysm-tiles
```

### Steps to reproduce the behavior

I compiled the game with:
`make PREFIX=/home/kitty/cdda-git RELEASE=1 ZLEVELS=1 USE_HOME_DIR=0 LUA=1 TILES=1 SOUND=1 -j4 install`

### System information
OS: ArchLinux 64bit, completely up-to-date
Compiler: GCC 7.1.1
**Previous git-versions work without problems, all compiled in the same way by myself.**

**Comment by Zireael07** [comment]
I believe this issue was already reported. Are you on an Intel Skylake GPU by any chance?

**Comment by nshcat** [comment]
Yes I am. I am so sorry if this is a duplicated issue, I couldn't find a related issue. Maybe I was just blind.

**Comment by Night-Pryanik** [comment]
It's here - #21317.
