### ISSUE TITLE
Choosing to wear a wielded item when wielding something else will reset its inventory letter

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#21736]
### Expected Behavior
Item is worn and retains its letter
### Actual behavior
Item is worn but its letter is reset
### Steps to reproduce the behavior
* Assign an inventory letter to an item of clothing or other wearable item (ie. a gun with a shoulder strap)
* Wield item
* Try to wield a different item
* Choose to wear the first item
* Assigned inventory letter is gone/replaced with a different letter

won't occur if you choose to drop or store the item in your inventory

**Comment by angoddu** [comment]
I have a similar issue with weapons and it's charges left. I assign a letter to my fully loaded weapon with a shoulder strap. Fire a few rounds and wear it and the letter had changed.

**Comment by ChronicDankDisasterAlgorithm** [comment]
Yes same here with the crossbow+(with shoulder strap). For example I shoot at a enemy coming at me, and activate my sheath to engage with my machete once they get close. If I wear the crossbow by pressing 3, it gets rid of the inventory letter(I have auto inventory letters off, but it would just change it to a not used one; or to no letter if none are left available.. if I had that option on). If I chose any other option besides "3.wear the item", it seems to want to keep the hotkey, either by dropping on the ground or just placing in inventory . Sometimes after wearing it and placing it back into your inventory, the hotkey comes back while it's not worn and goes away again while worn. Would be great if there was a fix to have it keep the hotkey.
