### ISSUE TITLE
Troubles with generating lua bindings in Code::Blocks on Windows 8

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#21745]
I'm building with `MSYS2 (64 bit)` from `Code::Blocks` on `Windows 8`.

`LUA=1`, but `catabindings.cpp` isn't generated and Windows asking for application to open files with type `.1` until I change `lua5.1` to `lua5.1.exe` in `Build options` menu.

Does anyone having this error too?

Should I update `CataclysmWin.cbp` in the repository to address the issue or it is only me having it?

**Comment by DanmakuDan** [comment]
I think my MSYS2 had a Lua.exe from building/installing Lua 5.3, I made a (sym?)link in Windows that maps lua.exe to lua5.1.exe, which works for me.

**Comment by ZhilkinSerg** [comment]
> I think my MSYS2 had a Lua.exe from building/installing Lua 5.3, I made a (sym?)link in Windows that maps lua.exe to lua5.1.exe, which works for me.

I've explicitly installed lua of version 5.1 in MSYS2 shell (`pacman -S mingw-w64-x86_64-lua51`) and it appears in install location (`C:\msys64\mingw64\bin`).

I've just realised that there is also file `lua5.1` with following content:

````
#!/usr/bin/env bash
/usr/bin/winpty "$( dirname ${BASH_SOURCE[0]} )/lua5.1.exe" "$@"
````

Probably Windows tried to run it, instead of exe.
