### ISSUE TITLE
Add stripper clips for old bolt action rifles to speed up reload

### ISSUE THREAD

**Issue by nshcat** [CleverRaven/Cataclysm-DDA#21749]
In the real world, old bolt action rifles (that don't feature detachable magazines) are commonly reloaded with so called "stripper clips", which are a type of speedloader that allow loading of multiple cartridges in one go. The strip does not stay in the rifle like a magazine, it only acts as a "guide path" for the cartridges and is discarded after reload is complete.
 (consider [this picture on Wikipedia.](https://en.wikipedia.org/wiki/Stripper_clip#/media/File:K98kclip.jpg))

I think this would be a nice addition to the game, because it would cut down on time spent reloading if you are careful to prepare before a fight. We already have craftable clips that are quite similar (the 8-round "enbloc"-clips of the M1-Garand, which do stay in the rifle), so the concept as-is is not new to the game.

What do you folks think about the idea? I'm quite interested in implementing this.

**Comment by kevingranade** [comment]
I'd love to have stripper clips and speedloaders in general in the game.

Keep in mind that the existing reload times are (at least the last time I
checked) adjusted down to make semi-tactical reloading achievable, if we
have a speedloader option, we will likely want to adjust reload times to
reflect this, making speedloaders mandatory for fast reloads.  Well, either
speedloaders or spare magazines.

>

**Comment by elricsfate** [comment]
Stripper clips can be added for both rifles and actual magazines. Many magazines are also compatible with  stripper clips, I know for a fact M16 series magazines are. 

I'm guessing the best way to implement this would be to implement a "can_use_clip" flag or similar on firearms and magazines that are compatible with this and then implement a "is_clip" flag for clips themselves. 

Where would be a good place to start looking for this code? 

@kevingranade @nshcat 

If I have an idea of where to look I think I should be able to implement this.

**Comment by nshcat** [comment]
@elricsfate I spent the last few weeks going through the source code to analyze how to implement this (using Sourcetrail), and I think I have a reasonable approach that I am working on right now.
Basically, I am implementing **speedloaders** as a new "umbrella term", not just stripper clips, since they share common code and thus should be handled the same (imagine a speedloader for a revolver vs. one for a rifle, they are bascially equivalent when it comes to the underlying code).
As it stands, magazines and weapons with internal magazines can be marked with a special flag to indicate whether they accept speed loaders or not.

**Comment by elricsfate** [comment]
@nshcat 

Not at all, I'm a complete novice at coding and C++ coding especially. 

The method you're suggesting is essentially what I had envisioned but you put it much more succinctly (and will likely implement in a far better manner lol) 

Look forward to seeing the completed work. This will be a great feature.

**Comment by Cyrano7** [comment]
Resolved via https://github.com/CleverRaven/Cataclysm-DDA/pull/23447 and https://github.com/CleverRaven/Cataclysm-DDA/pull/23684

**Comment by BorkBorkGoesTheCode** [comment]
Both rest upon https://github.com/CleverRaven/Cataclysm-DDA/pull/23103
