### ISSUE TITLE
Able to open/close windows from outside at the dairy farm.

### ISSUE THREAD

**Issue by OzoneH3** [CleverRaven/Cataclysm-DDA#21751]
The ground beneath the dumpster and the crates is considered inside floor.
The is inside check seems to fail even though I'm standing on grass.

Building a crate next to a windows still has grass flooring, so it's probably a mapgen/json thing.

![](https://user-images.githubusercontent.com/3514404/29894592-22ab6174-8dd6-11e7-8604-937974822f76.png)

**Comment by BorkBorkGoesTheCode** [comment]
Inserting
`        "X": "t_dirt",`
into "terrain": might work.

It also looks like there's no way to open the dairy fence gate.
