### ISSUE TITLE
9mm Cartridges can be disassembled without a bullet puller

### ISSUE THREAD

**Issue by Reclusive-reptile** [CleverRaven/Cataclysm-DDA#21759]
### Expected Behavior
   9mm cartridges should require a bullet puller to disassemble.
### Actual behavior
  9mm cartridges require no tools to disassemble.
### Steps to reproduce the behavior
![9mmbug](https://user-images.githubusercontent.com/20874173/29942317-7a72f0e2-8e63-11e7-9c59-c0efb13a3ffd.png)

**Comment by Reclusive-reptile** [comment]
This also affect 7.62x25 cartridges. I suspect that the uncraft recipes are not properly inheriting required tool qualities from their abstracts.

**Comment by Cyrano7** [comment]
@Reclusive-reptile It looks like not inheriting tool qualities from abstracts is a problem here as you said but that can be its own issue.
