### ISSUE TITLE
Add "setup vehicle" menu to vehicle controls along with "control vehicle"

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#21750]
I'd like to see additional menu choice in vehicle controls along with "control vehicle".
"setup vehicle" or any similar name, which is completely the same as "control vehicle" but does not close itself after you select an option. 

Useful in situation like: Stop driving at night, turn off engine, turn off headlights, turn on aisle lights to do some stuff before going to sleep. Right now we have to access controls multiple times to achieve all this.

**Comment by Coolthulhu** [comment]
I think it sounds reasonable to just make vehicle menu not close until player presses "escape".

**Comment by kevingranade** [comment]
Yea, that sounds like a better default.

I could see a strong expectation that e.g. taking control of the vehicle is
followed by wanting to just start driving, but that might not be worth
having the menu be inconsistent.

**Comment by tinukedaya** [comment]
Yeah, that might indeed be a little better solution. Seeing as when you start driving you usually don't go thru the control menu but just take control and start engine with the ^, it should be fine if in general it's just changed not to close itself.
