### ISSUE TITLE
Disambiguation of "Smoke"

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#21760]
- Smoke as an effect;
- Smoke as an action;
- Smoke as a faction element (?).

The first two are in jsons. Is there some method like pgettext for jsons?

**Comment by Coolthulhu** [comment]
It would probably have to be specified in the translation extraction script and whenever the string is printed.
Maybe we should have a translated string container somewhere, to carry all the context?
