### ISSUE TITLE
Sawing down metal bars takes no time at all

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#21771]
### Expected Behavior
Activating a metalsaw or a toolbox brings up the option to saw down metals bars from windows, or the floor (i.e.gunshops, prison cells).
*in my opinion*, manually sawing down metal bars from a window should take a *long time*, maybe one hour per window tile. Possibly even longer. More so (maybe) if the metals are from the ground up.

### Actual behavior
The process finished immediatly as opposed to taking a certain amounot of time.

### Steps to reproduce the behavior
Activate a metal saw / toolbox near metal bars

### Solution
a) Either add increase the time need to the above action, or b) move the whole process to the construct  / deconstruct futniture menu. I.e. similar to "Clean broken shards from window".

Advantage for b) Player could see the time need before actually picking the option as opposed to right now where the player makes a decision without seeing the actual requirements in time (and tools).

**Comment by Coolthulhu** [comment]
Construction menu sounds best, I think. Cleanly presented with all the requirements, no need for a new action that duplicates existing functionality.
A saw/toolbox could have a shortcut to the construction, if desired.

**Comment by AncientSion** [comment]
For the record, the ability to "construct metal bars" is actually to be found in the world crafting menu, so thats another reason to possibly move the "unconstruct metal bars" to the same menu.

**Comment by AncientSion** [comment]
Unfortunally my suggestion did fall on deaf hears.
So, for now, can be please just VASTLY increase the time need ?
I delved into the code

https://github.com/CleverRaven/Cataclysm-DDA/blob/66ff2f96985e17172bfe75758325fede9f96a0cf/src/iuse.cpp#L4500

If someone would kindly just increase the moves from 500 to say 20000, or some meaningful value, i would think it would be very reasonable. for such an action.
Unfortunally i dont have a compiler installed so i cant do it on my own.

**Comment by Zireael07** [comment]
Very many moves means you're effectively frozen for the time, so it should be a long action.

**Comment by kevingranade** [comment]
> Unfortunally my suggestion did fall on deaf hears.

I'm sorry you got that impression, this is a valid issue that needs to be corrected, but we have several hundred other valid issues that also need to be addressed, so it can take a while to get to any particular issue.

**Comment by AncientSion** [comment]
Oh, sorry @kevingranade. I suppose my remark did sound a bit offensive, i didnt mean it that way. I was just sad to dont see any feedback. Your latest comment fixed that. It is fine if it takes a while and im ok now that it is acknowledged. thanks.

**Comment by kevingranade** [comment]
You weren't offensive at all, by "I'm sorry you got that impression" I mean, "I apologize that your issue wasn't acknowledged sooner".
