### ISSUE TITLE
Add a direction to minefield signs

### ISSUE THREAD

**Issue by Leland** [CleverRaven/Cataclysm-DDA#21773]
The reason minefield warning signs exist is so that players know they need to leave the area. Unfortunately, without a direction provided on the sign, the best route to leave is not known.

Changing minefield signs to read, ex. "DANGER! MINEFIELD TO THE NORTH!" would be of great benefit, I believe.

**Comment by Mecares** [comment]
I am pretty sure people would use an arrow or something to show the direction, so it is not useless for people without a compass.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
