### ISSUE TITLE
Travis is not working good

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#21789]
Something is wrong with Travis. See https://travis-ci.org/CleverRaven/Cataclysm-DDA/jobs/271632564 or https://travis-ci.org/CleverRaven/Cataclysm-DDA/jobs/271672634.

Job #9 always fails, even when other jobs are successful:

![default](https://user-images.githubusercontent.com/16213433/30034338-652e15f6-91a9-11e7-846e-f443cc39e073.png)

![default](https://user-images.githubusercontent.com/16213433/30034356-7ad675ba-91a9-11e7-953f-b45496a4060b.png)

**Comment by kevingranade** [comment]
Thanks for pointing this out, there are a couple of candidates for why this is happening, including poor interaction with the clang release process and an issue on the travis backend.
I'm looking into it now.

**Comment by kevingranade** [comment]
Looks like it was transient? :P
Builds are succeeding now so...

**Comment by ZhilkinSerg** [comment]
Great. Maybe that was some issue with access to remote repository or something?

**Comment by kevingranade** [comment]
Pretty sure that's what was happening yes.
