### ISSUE TITLE
Vehicle funnel not filling modded tanks in non-standard install locations

### ISSUE THREAD

**Issue by Maddremor** [CleverRaven/Cataclysm-DDA#21787]
### Expected Behavior
Funnel would fill a water tank (during rain) as long as the tank was installed on the same vehicle tile. 
### Actual behavior
The vehicle mounted funnel seems to not fill tanks without `location": "fuel_source"`
### Steps to reproduce the behavior
This was observed upon modding in a variant 2L tank that ommited a vehicle install location as to be installed along other tanks/batteries. When installed as the only vehicle liquid container on the tile, the funnel did not fill it with water during rain.

Is the funnel restricted to working with tanks installed on  `location": "fuel_source"`?

**Comment by Night-Pryanik** [comment]
Closing in favor of #22985.
