### ISSUE TITLE
Container should be able to hold powder.

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#21784]
### Expected Behavior
When selecting a container in the [C] section of the AIM menu you should be able to store stuff in there. 

### Actual behavior
Always get an error saying "Source must be a container."

### Steps to reproduce the behavior

1. Get a small plastic bottle of powdered eggs or something similar.
2. Unload the eggs into your inventory
3. Open AIM
4. Select the now empty small plastic bottle and press 'c' or 'C'
5. Select the loose powdered eggs and try to move them

I can see that the existing system only allows container to container transfer but that seems odd. I haven't really looked at the code for this but I think it should be fixable. That way all those plastic bags and paper wrappers can have some use again

**Comment by ituluwituluwzev** [comment]
One can store liquid but not powder in container.

**Comment by angoddu** [comment]
Then why did I find a small plastic bottle of powdered eggs?

**Comment by Night-Pryanik** [comment]
That's just a limitation of game engine.

**Comment by angoddu** [comment]
Couldn't a flag get added for something like this?

**Comment by CoroNaut** [comment]
I literally just empty any container without a liquid because you can literally just throw the powder in your backpack with everything else and still manage to scrape it all up when taking it out of the bag. Getting rid of the containers is lighter and so its more convenient, but breaks immersion.

**Comment by Coolthulhu** [comment]
I had an idea regarding this before: powders could be treated like liquids in player's inventory, but like solids outside.
That is, an uncontained powder could be picked up, but only into a container. Losing the container would cause the powder to spill on the ground.

Pills and similar almost-powders would be treated the same way. This would prevent the one pill storage bullshit.

**Comment by angoddu** [comment]
I really like Coolthulhu's idea. 

> That is, an uncontained powder could be picked up, but only into a container. Losing the container would cause the powder to spill on the ground.

Powders should be treated just like liquids but I am a but confused how you would pick up a powder after it falls on the ground. I think it should act just like a liquid except it needs a broom to clean the mess when it spills.

> Pills and similar almost-powders would be treated the same way. This would prevent the one pill storage bullshit.

I like the idea of having pill bottles instead of having them just loose in your pockets. I am unsure what the "one pill storage bullshit" you are talking about. Is it that one pill is the same volume as 100 pills?

We could add an new container called "pill bottle" that only holds 0.1L or 0.05L that pills will be contained in by default. 

What almost-powders are you thinking of? Sand is the only thing I can think of off the top of my head

**Comment by Coolthulhu** [comment]
> I think it should act just like a liquid except it needs a broom to clean the mess when it spills.

A desperate survivor could just pick up flour by hand. Plus, broom would also make some cases look worse: salt spilled on table etc.

> I am unsure what the "one pill storage bullshit" you are talking about. Is it that one pill is the same volume as 100 pills?

No, it's that one pill is volume of one pill and can be stored uncontained in the inventory just fine, picked from a pile of identically sized pills, doesn't fall out and so on. If it had the volume of 100 pills, it could be considered an abstraction similar to batteries. But it has volume of one pill, meaning it can't be an abstraction, hence the next closest word: bullshit.

**Comment by angoddu** [comment]
> A desperate survivor could just pick up flour by hand

That is a good point. Now I understand what you meant by it acting like a liquid in the inventory but a solid on the ground

The pill issue could be solved with the pill bottle idea that I proposed. A 0.1L bottle would allow for 100 pills to be in a single bottle, which seems reasonable

**Comment by logistictangent** [comment]
I worked in a pharmacy for a bit and the size of the pill changed the size
of the container that we used. An example being that we had some
medications like dextroamphetamine salts that were a quarter of the size of
a pencil eraser that we could fit one hundred into a ten dram (standard
size) bottle and still have room for forty more easily. And other
medications that were an inch long and a quarter of an inch wide that we
could only fit thirty to a ten dram bottle.

I feel it might be better (subjectively) to give each type of pill a volume
per pill and allow it to stack and be put into containers.

**Comment by angoddu** [comment]
I really like this idea. Where would someone look to figure out the size of the average Aspirin or Ambien?

**Comment by i2amroy** [comment]
As the person who initially increased weight granularity back when weight moved from .25lbs to 1 gram, you spend hours and hours and hours googling things and measuring them yourself.

(So to answer the question, I'd pull out my ruler and take a look into my medicine cabinet).

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
