### ISSUE TITLE
Generic resource conversions in vehicles

### ISSUE THREAD

**Issue by Maddremor** [CleverRaven/Cataclysm-DDA#21796]
As recently mentioned be Coolthulhu in #21735 (and probably in other instances previously) is the idea of having vehicle parts being able to continuously convert between one resource to another via defenitions in JSON.

As of now, we have several conversions:

| Input       | Output                      |
|-------------|------------------------------|
| gasoline    | propulsion                   |
| diesel      | propulsion                   |
| electricity | propulsion                   |
| gasoline    | electricity (via alternator) |
| diesel      | electricity (via alternator) |
| plutonium   | electricity                  |

However, there are more potentially interesting use cases that are not yet covered:

| Input                    | Output                                                                     |
|--------------------------|----------------------------------------------------------------------------|
| water + electricity      | clean water (water purifier)                                               |
| wood                     | steam (steam boiler)                                                       |
| steam                    | electricity (steam turbine)                                                |
| wood                     | propulsion (wood gasifier engine conversion)                               |
| salt water + electricity | salt                                                                       |
| salt water + electricity | acid water (dedicated chemical apparatus)                                  |
| acid water + electricity | concestrated acid (dedicated chemical apparatus)                           |
| meat or blob             | propulsion (currently hacked in Blazemod)                                  |
| nothing                  | electricity (magic unbalanced non.mainline generator)                      |
| wheat + electricity      | flour (electric quern with hopper, should apply to most grinding recepies) |

There are probably more possibilities that I have not considered. I create this issue with the intent of it being a central point of disussion of related issues or PRs.

To start off: Currently, liquids can be consumed from tanks using the generic tank system, but solids must be loaded into a dedicated storage (see: plutionum in minireactor). Should and could we have parts consume or create items in specified storage areas?

**Comment by Coolthulhu** [comment]
Conversions to "propulsion" would not run on the converter code. They need dedicated hardcoded handling.
Electricity would also benefit from hardcoded handling, as it already has hardcoded consumption. It could still be produced in a different way, but the hardcoded part will most likely stay.

The other conversions are good examples.

Basically, the converter would be a part that would have a set of pseudo-recipes specified, each with following elements:
* Inputs
  * Selector - what is the item we're using? Typically just item type, but for steam and gassification we'd want it to be "is made of wood" instead
  * Source - only the converter or "drain" (all batteries and tanks on vehicle)
* Outputs
  * Result - item type, item count. Special case for item count: if set to some special value, we'd want to match input volume.
  * Destination - only the converter or first valid part with some specific flag (or set of flags)
* Time to process

For example, a boiler could be implemented as two of the above recipes:
* Reduce all wooden items into matching volume of splintered wood (or generic "burning fuel" item, to cover coal) in 0 time
* Burn each fuel item to produce x steam, in some specific time

While this would complicate steam power a bit, it would allow implementing all those extra recipes with minimal effort.

**Comment by Maddremor** [comment]
In making this suggestion, I personally had envisioned the conversion process being continous as opposed to a descrete timed process. If wooden items were defined as fuel, the gasifier would then pick a random wooden item in the storage in the same vehicle tile to produce steam. However, I guess this could be harder to implement.

**Comment by kevingranade** [comment]
Making it continuous is tricky, then you need to have the part "claim"*
items being processed, then track the process of consuming them in addition
to periodically producing the outputs.

That's a more robust system overall, so I wouldn't be totally opposed to
it, but it's much more difficult to implement.

*claiming could take many forms, it could stash the actual item somewhere,
such as in the reactor, or it could immediately convert it to its outputs,
but only release them over time.

**Comment by mlangsdorf** [comment]
I'm going to enable vehicle fuel defined in JSON and multiple fuel types per engine, but though this is a clever abstract approach to unifying how CDDA handles a lot of stuff, it doesn't help the short term of goal of making steam engines.

**Comment by mlangsdorf** [comment]
Closing.  We have steam engines and multifuel engines and grain mills without doing generic resource converters.
