### ISSUE TITLE
Vending machines have a disproportionately low number of items

### ISSUE THREAD

**Issue by DarklordMogrithe** [CleverRaven/Cataclysm-DDA#21794]
* Windows 10, 64-bit
* 0.C-23730-g4b6197d (6736)
* Tiles

### Expected behavior

Vending machines should have a variable number of items in them.

### Actual behavior

Vending machines have exactly one item in them (at least normal, food-vending ones).

### Steps to reproduce the behavior

1. Go to any area with a vending machine (parks, subway stations, etc.).
2. Wish for a cash card.
3. Examine the vending machine and select the cash card.

**Comment by BorkBorkGoesTheCode** [comment]
Have you tried to bump up item spawns to +2.0?

**Comment by ChronicDankDisasterAlgorithm** [comment]
I've read the spawn rate was reduced around the time I started playing, if you want the vending machines to have more items just bump up the item spawn rate like BBGtC said. I heard that 4.0 is what would be the closest to what it used to be. Unless you are saying that even then there is only one item, then disregard. 

I've only ever seen more than one item in the ammo machines and in my first couple games when the spawn rate was set by me to 1.5 or 2.0.

**Comment by DarklordMogrithe** [comment]
> Have you tried to bump up item spawns to +2.0?

Tested now with a 2.0 scaling factor and there are usually 2 items in vending machines, although a few have 1 item. It seems that there is some variation programmed in, though the amount of items that is set to generate is around 1. When compared to other sources of food at the same scaling factor, vending machines seem to be severely lacking in loot.

Since there is a definite correlation between item scaling factor and number of items in vending machines, #19906 ought to be closed or reworded and tested.

**Comment by cainiaowu** [comment]
The old formula will keep spawning item if it is not 100% as described in doc/MAPGEN.md.
New formula will stop trying.

2.6.6 "items"

Places items from an item group. Values:

"item": (required, string) the item group to use.
"chance": (optional, integer or min/max array) x in 100 chance that a loop will continue to spawn items from the group (which itself may spawn multiple items or not depending on its type, see ITEM_SPAWN.md), unless the chance is 100, in which case it will trigger the item group spawn exactly 1 time (see map::place_items).

**Comment by DarklordMogrithe** [comment]
Looks like this isn't a bug, then. Still, as an unintentional side-effect of that PR, I think the spawn rates of vending machine items should be rebalanced. I unfortunately have no experience with the code, so it is unlikely that I will make a PR.
