### ISSUE TITLE
Major slowdown when moving player character

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#21803]
Major slowdown when moving player character in [attached save](https://github.com/CleverRaven/Cataclysm-DDA/files/1281699/Gray.Court.zip).

Slowdown disappeared when I moved player character maybe a dozen tiles away west from initial position.

There is no slowdown after returning to initial position.

Game version: *0.C-23730-g4b6197d (tiles)*
Operating system: *Windows 8*
Tiles or curses: *tiles*
Mods active:
```JSON
[
  "dda",
  "Urban_Development",
  "ZSFIXED_cddaxp",
  "StatsThroughSkills",
  "national_guard_camp"
]
````

**Comment by DanmakuDan** [comment]
There are a deer and a turkey near the right edge of the screen that are stuck in a performance-eating pattern explained by #21615. When you move west and back, the creatures are unloaded and reloaded. Their movement plan doesn't get stuck in the same loop again.
