### ISSUE TITLE
Chain Lightning targets enemies on different Z-Levels

### ISSUE THREAD

**Issue by Furbeh** [CleverRaven/Cataclysm-DDA#21801]
Game version:0.C-23730-g4b6197d

Operating system: Windows 10 64 bit

Tiles or curses: Tiles

Mods active: Disable NPC Needs and Simplified Nutrition

### Expected behavior
When Chain lightning jumps to additional enemies within 4 tiles, it should only target ones on the same z-level.

### Actual behavior
Chain lightning's jumps can target enemies on different z-levels, being unable to hit them due to them being on a different z-level

### Steps to reproduce the behavior
Go to the necropolis and try to use chain lightning on the surface on an enemy. It will generally jump off and seemingly hit 10+ irradiated wanderers

**Comment by Mooses2k** [comment]
To clarify, I think it should hit different z-levels, just not through floors etc.

**Comment by kevingranade** [comment]
This might have been fixed when I fixed targeting for shocker zombies.

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.
