### ISSUE TITLE
NPCs moving inside a vehicle causes skidding

### ISSUE THREAD

**Issue by jeremyshannon** [CleverRaven/Cataclysm-DDA#21811]
Game version:
Current experimental

Operating system:
Linux

Tiles or curses:
Curses

Mods active:
None

### Expected behavior
Normal driving?

### Actual behavior
When an NPC repositions himself in a moving vehicle, the vehicle begins skidding.

### Steps to reproduce the behavior
Get a friendly NPC into an RV, begin driving, and edit them to set their fatigue high enough that they leave their seat and move to the bed. Alternately, yell at them to wake up, and they'll go back the other way.

Here's a save which reproduces the problem. Just chat with the NPC and tell her to sleep when tired, observe how the vehicle begins skidding as a result. (External link since the attachment thing doesn't like my zip file.)

https://mega.nz/#!cUlGECDK!h8HVpPFEA5D8rWx5OS03hP3-iksxw8uGOmoHmFNbadI

**Comment by BrokenAdmin** [comment]
It's not a bug, it's a feature.

**Comment by raymoo** [comment]
Is this a form of weight transfer drift?

**Comment by jeremyshannon** [comment]
If it is, it's ridiculously exaggerated. Weight transfer drift should affect you when turning,  and proportionate to the amount of weight moving versus that of the vehicle. It should not have this much effect when traveling steadily in a straight line.
.I've swapped seats in a moving five-seat hatchback (teenage hijinks) without the driver losing control and nearly spinning out off the road, a 14,000 pound (small) RV shouldn't be noticeably bothered by a 150 pound person moving from one seat to another.
