### ISSUE TITLE
Multitile shops/parks/houses in city mapgen

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#21812]
Is it possible to spawn multi-tile building via `region_settings` file? Say, I have 2x2 `overmap_special` which I want it to be a shop.

**Comment by Coolthulhu** [comment]
Currently no.
Once #21527 is in, same principle could be used to have wider buildings, but for now it's impossible for a shop or house to be anything but 1x1.

**Comment by ZhilkinSerg** [comment]
Thanks, I'll wait for the changes.
