### ISSUE TITLE
Windows 64 Build

### ISSUE THREAD

**Issue by SirClarke** [CleverRaven/Cataclysm-DDA#21825]
Game version:
6736(last one to work)
Operating system:
Windows 10
Tiles or curses:
Tiles
Mods active:
Not sure
### Expected behavior
For the game to update
### Actual behavior
Its stuck on a four day old build
### Steps to reproduce the behavior
I'm not sure what to do really i'm not sure i filled this out right just hoping to get some help really.
(I think its just not updating)

**Comment by Leland** [comment]
Issue is being tracked in #21802
