### ISSUE TITLE
Character generation menu is too small on modern displays

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#21828]
Character generation menu was written with interface around 80x25 in mind. Anything above that gets a tiny centered 80x25 menu, forcing scrolling.

A full-sized menu, like the crafting or item wish menu, would be much more readable and would have enough space to display all the items and long descriptions without unnecessary scrolling.

**Comment by Night-Pryanik** [comment]
This issue was already reported in #7103, #16038 (maybe some other), both are closed, though.

**Comment by kevingranade** [comment]
We have way too many ui shortcomings to document them all as "wishlist" issues, please only open issues like this if you have a plan to address them immediately or want feedback on an approach.
