### ISSUE TITLE
Weird river (lake?) mapgen

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#21833]
![11111](https://user-images.githubusercontent.com/11132525/30247194-fde55004-9616-11e7-8972-b0b628361c3c.PNG)
![2222](https://user-images.githubusercontent.com/11132525/30247196-00729412-9617-11e7-8f7c-ec552ac4a557.PNG)

Even this piece of mapgen may count as a lake, I find it strange that it got straight east and north edges with no shallow water.

**Comment by Leland** [comment]
Weird shape, but the lack of shallow water is #18583

**Comment by Leland** [comment]
Closing in favor of #18583; added your screenshots to that discussion as well.
