### ISSUE TITLE
Compilation failure with VS

### ISSUE THREAD

**Issue by Maddremor** [CleverRaven/Cataclysm-DDA#21837]
Game version: Last commit 42c4c764

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: N/A

### Expected behavior
The game compiles without failure with Visual Studio.
### Actual behavior
The compilation fails with error
```
'p': redefinition; previous definition was 'data variable'	Cataclysm	D:\Program Files Installess\Games\Roguelike\Cataclysm\cdda_play\src\mapgen.cpp	188	
'p' cannot be implicitly captured because no default capture mode has been specified	Cataclysm	D:\Program Files Installess\Games\Roguelike\Cataclysm\cdda_play\src\mapgen.cpp	188	
```

**Comment by ZhilkinSerg** [comment]
Which VS version did you use?

What configuration did you select? Debug or Release? x86 or x64?
