### ISSUE TITLE
AIM > Vehicle screen refresh issue

### ISSUE THREAD

**Issue by Shukka** [CleverRaven/Cataclysm-DDA#21843]
Game version:
latest experimental build as of 9/9/2017

Operating system:
win10x64
Tiles or curses:
Tiles
Mods active:
None
### Expected behavior
"No vehicle there!" text box removed and screen refreshed
### Actual behavior
"No vehicle there!" text box turns to black space
### Steps to reproduce the behavior
Pressing '/'  then 'v' then 'Esc'
I should have pressed (e)xamine item not (v)iew item, which is my common mistake as only relevant with vehicle present.

**Comment by Leland** [comment]
Can confirm.
