### ISSUE TITLE
Version field in modinfo.json

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#21846]
Should we have some additional field showing mod version in `modinfo.json`?

**Comment by BrokenAdmin** [comment]
Pretty sure if a dev felt lile it they could do. "//", put it in the desc or title

**Comment by kevingranade** [comment]
What does the version mean? Is it just something for people to add when they report issues?

**Comment by BrokenAdmin** [comment]
I'd suppose.

**Comment by ZhilkinSerg** [comment]
> What does the version mean? Is it just something for people to add when they report issues?

Correct.

**Comment by BrokenAdmin** [comment]
Well, can't we just use the `"//"`, as this issue has been open and either never got closed or hasn't been discussed over completely.

**Comment by Broken-Admin** [comment]
@kevingranade Is this issue closed, should I make an attempt to add this? What's our verdict?

**Comment by kevingranade** [comment]
It needs a field in modinfo files, adjustment for the associated reader, and an extension to the user interface to make the versions of mods in the current game visible to players.
Specifically, no a comment field would not work because no one would see it.
