### ISSUE TITLE
List of unmatched contexts to be added to `format.conf`

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#21848]
There are a lot of unmatched JSON-contexts which should be added to `format.conf`:

- `COMESTIBLE<COMESTIBLE>:fun_comment`;
- `GENERIC<GENERIC>:ammo_type`;
- `GENERIC<GENERIC>:count`;
- `MIGRATION`;
- `MONSTER_FACTION`;
- `SPECIES`;
- `TOOL<TOOL>:rarity`;
- `construction<construction>:required_skills`;
- `dream`;
- `epilogue`;
- `faction`;
- `fault`;
- `item_action`;
- `martial_art`;
- `monster_attack`;
- `mutation<mutation>:spawn_item`;
- `npc_class`;
- `npc`;
- `overmap_connection`;
- `overmap_location`;
- `profession_item_substitutions`;
- `recipe_category`;
- `region_settings`;
- `region_settings`;
- `start_location`;
- `technique`;
- `tool_quality`;
- `tutorial_messages`;
- `vehicle_placement`;
- `vitamin`.

Some of the missing contexts will be added in #21847. Following contexts will still be missing after this PR is merged:

- `COMESTIBLE<COMESTIBLE>:fun_comment`;
- `GENERIC<GENERIC>:ammo_type`;
- `GENERIC<GENERIC>:effects`;
- `TOOL<TOOL>:rarity`;
- `construction<construction>:pre_note`;
- `fault<fault>:requirements<>:qualities:@:@`;
- `mutation<mutation>:spawn_item`;
- `npc_class<npc_class>:skills:@:@<>:level<>:mul`;
- `overmap_connection`;
- `overmap_location`.

**Comment by kevingranade** [comment]
Just a reminder, this entire system will be obsoleted by #21612

**Comment by Coolthulhu** [comment]
That's not a certain, though. There are edge cases it may be unable to handle correctly.

**Comment by ZhilkinSerg** [comment]
>Just a reminder, this entire system will be obsoleted by #21612

Yes, I'm aware of that PR, but still hope implementing rules will still be useful - at least for local testing.

**Comment by kevingranade** [comment]
By obsoleted I mean, "I'm planning on deleting this whole system".

**Comment by kevingranade** [comment]
System is obsoleted, linter and minting contexts no longer exist.
