### ISSUE TITLE
Negative healthy effects aren't actually applied

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#21844]
Game version:
latest experimentals
Operating system:
windows
Tiles or curses:
both
Mods active:
default mods

### Expected behavior
sewer brew/methamphetamines/candy to negatively affect health modifier
### Actual behavior
they don't do that
### Steps to reproduce the behavior
1. make new default character in new default world
2. debug spawn some bad food and eat it
3. check char's health, everything is at 0

if you have some positive healthy mod it wont affect that either

**Comment by Barhandar** [comment]
"Healthy" is vitamins, it doesn't, shouldn't, and never did affect "health" directly, they're unrelated attributes.

**Comment by sick-trigger** [comment]
i'm talking about the hidden health stat, not hit points or w/e

**Comment by kevingranade** [comment]
Did you wait for a while for a health tick to happen?

**Comment by sick-trigger** [comment]
yes

positive healthy effects are applied immediately, i assume that negative changes are supposed to be the same

**Comment by sick-trigger** [comment]
it also seems like health mod will never drop itself below 10? anything above 10 and it will slowly decrease as intended, but it stops at 10

eat two blackberries at game start, then subsist on nothing but sewer brew and french fries and your healthy stat will never drop below 10

**Comment by Coolthulhu** [comment]
> positive healthy effects are applied immediately, i assume that negative changes are supposed to be the same

You mean effects to `healthy` or `healthy_mod`?

**Comment by sick-trigger** [comment]
healthy_mod

**Comment by Coolthulhu** [comment]
Fixed in #21849
