### ISSUE TITLE
Crafting certain recipes using liquid nearby will empty can inside player's inventory

### ISSUE THREAD

**Issue by lonelychaser** [CleverRaven/Cataclysm-DDA#21850]
Game version: 0.C-23389-gd993d6c

Operating system: Windows 10

Tiles or curses: tiles

### Expected behavior

Crafting a recipe that uses liquid nearby should not empty the can of soup inside player's inventory

### Actual behavior

When crafting a recipe that uses liquid nearby, the can of soup inside the inventory will be emptied

### Steps to reproduce the behavior

- open a can of soup in player's inventory (must be in inventory, not wielding it)
- craft a recipe that requires liquid and other ingredients and use liquid nearby
- after crafting is finished, a prompt will appear asking what to do with the soup

as far as I have tested, tainted tallow, cat food and tainted tornado will cause this bug to happen, I don't think the can should be involved in the crafting so I think this should be a bug.

EDIT as of 19/9/2017: I tested a bit more and I still don't understand the bug. I made a fresh world and character with default setting. Wished for just enough ingredients and opened a can of soup, then I tried to make a cooked mushroom under different conditions ([because the recipe is very simple](http://cdda-trunk.chezzo.com/morel_cooked/craft)) and all the them make me empty the can of soup somehow:

| water source | tools |
| --- | --- |
| plastic bottle of water in inventory | mess kit |
| plastic bottle of water in inventory | fire and pointy stick |
| plastic bottle of water nearby | mess kit |
| plastic bottle of water nearby | fire and pointy stick |
| water from a pond | mess kit |
| water from a pond | fire and pointy stick |

At this stage, I think looking into the code is better than me (who have no programming experience) slowly testing out what is the problem here.

**Comment by BrokenAdmin** [comment]
Pease check if the recipe requires a item with boiling or another property possessed by a tin can. Please contact me on discord *KillswitchZer0#4243*

**Comment by BrokenAdmin** [comment]
If you need help that is.

**Comment by atealein** [comment]
I can confirm this bug is still in play and it is activated not only when crafting things that require boiling, but also when making something as simple as fixing few gallon jugs into a plastic jerrycan. I originally thought it happens only when in vehicle, but now can confirm it happens also outside of vehicle. Sometimes it is triggered not by crafting but by repairing vehicles too.

**Comment by lancewf** [comment]
I don't think this bug is possible any longer. You can not have an open can of soup in the player's inventory. One can only wield an open can of soup. I can not repeat the bug. 

@lonelychaser can you try to repeat the bug with the latest code?

**Comment by ifreund** [comment]
Immediately consuming components should fix these issues, if they even still exist

**Comment by Night-Pryanik** [comment]
Closing until confirmed.
