### ISSUE TITLE
Auto Save "Last Used" character template

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#21862]
Thought I'd try something different but got off to a really bad start and wanted to start over but didn't save a template as I wasn't expecting to go back to it.  Would have made my life easier if the game remembered my last character.

Should be a simple matter of calling the save character template method at game start and using "Last Used" for the name.  However, I haven't spent any time familiarizing myself with that section of code yet.

**Comment by OzoneH3** [comment]
I like the idea, PR is up.
