### ISSUE TITLE
Player can consume liquid without container by selecting it from inventory, but not on the [E]at screen

### ISSUE THREAD

**Issue by lonelychaser** [CleverRaven/Cataclysm-DDA#21869]
Game version: 0.C-23389-gd993d6c

Operating system: Windows 10

Tiles or curses: Tiles

### Expected behavior
Player should be able to consume liquid without container in both [E]at screen and in [I]nventory
### Actual behavior
Player can't consume liquid without container in [E]at screen
### Steps to reproduce the behavior
- Wish for a liquid without using [f] to hold it in a container
- Player can't consume the liquid on the [E]at screen as it will say "Can't drink spilt liquids"
- Open [I]nventory, choose the liquid and [E]at it
- The liquid will be consumed

**Comment by kevingranade** [comment]
Unless you can provide a way to get uncontained liquids in your inventory without using the debug menu, this isn't a bug.

**Comment by CoroNaut** [comment]
I understand were he is getting, instead of selecting each individual bottle of liquid, you can just select what you want to drink and it will take a charge away from that liquid type. It would be more simple and the hotkeys will always stay the same.

**Comment by angoddu** [comment]
So maybe a real in-game test of this could be to dump liquid on the floor and try it activate it through the (a) key

**Comment by PlasmaChroma** [comment]
A while ago I think I found a way to get an un-contained liquid in inventory by having a hydration pack destroyed while wearing it and the water was still "held".

This may have been fixed though, I haven't had this happen recently.

**Comment by ituluwituluwzev** [comment]
Issue #12607 provides so far the only known way to get liquid in inventory without debugging. It is already fixed. Closing for now.
