### ISSUE TITLE
Game crashes when trying to read new book

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#21868]
Game version: 0.C-6764

Operating system: Windows XP SP3 x86

Tiles or curses: tiles

Mods active: default only

### Expected behavior
Player should be able to read new books.
### Actual behavior
Game crashes when trying to read new books.
### Steps to reproduce the behavior
Wish a new book and try to read it.

**Comment by Night-Pryanik** [comment]
I need to say that it seems to happen with only a number of books. `Autobiography of a Mountain Man` crashes for sure.

**Comment by Night-Pryanik** [comment]
It seems that it happen only on localized version. I was able successfully read `Autobiography of a Mountain Man` with English interface, but the game crashed when I tried to do this on Russian.

**Comment by AMurkin** [comment]
Это из-за строки "Requires %s level %d to understand.". Из-за того, что в переводе %s и %d поменялись местами. Проверил локально. Я сохранил как предложение варианта перевода строку, в которой они в том же порядке.

**Comment by Night-Pryanik** [comment]
Ok, changed translated string in Transifex, waiting for update of the translation.
