### ISSUE TITLE
Add Wide-angle headlights and directed floodlights as vehicle parts.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#21874]
It seems that something that would satisfy the request in #21852 better than dropping floodlight power consumption is a "vehicle floodlight with 90deg or 180deg range and reasonable power consumption".

As such I propose adding a "Wide-angle Headlight" (with a 90 degree arc and -375 epower) and a "Directional Floodlight" (with a 180 degree arc and -750 epower) as vehicle parts.

The light cones are applied here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/lightmap.cpp#L338

The locations where CONE_LIGHT are referenced: https://github.com/CleverRaven/Cataclysm-DDA/search?utf8=%E2%9C%93&q=CONE_LIGHT need to be updated, either by adding variants of VPART_CONE_LIGHT or by making the light cone flag include a variable indicating the angle that the light illuminates.

Also it requires the vehicle parts, related items and crafting recipes for them, which are going to be nearly identical to the existing headlight items.

**Comment by AncientSion** [comment]
I like this, A lot in fact.
If i may be so bold, i would suggest going with your second suggestion (a variable indicating the angle)  as opposed to having only static angles. It will be more future proof and might be useful for modding or something at some point.

**Comment by BrokenAdmin** [comment]
I like the idea! I've always thought that the headlights were a bit clunky in general.

**Comment by CoroNaut** [comment]
Its about time; been waiting for this. :D

**Comment by Marrim** [comment]
Will there be reinforced versions?

**Comment by Broken-Admin** [comment]
Shall this ever happen? I forgot I posted here.

**Comment by mlangsdorf** [comment]
It's not exactly anyone's priority. You're welcome to contribute.

**Comment by Broken-Admin** [comment]
I'll attempt to make a mod and then PR the changes.
