### ISSUE TITLE
Metal wreckage located on a young tree does not yield metal after clearing it.

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#21878]
Game version:
0.C-23902-g0422836 (tiles)
Operating system:
Windows 7 Professional x64 SP1
Tiles or curses:
Tiles
Mods active:
  "type": "MOD_INFO",
  "ident": "user:default",
  "dependencies": [
    "dda",
    "Experimental-Z-Level",
    "Medieval_Stuff",
    "More_Survival_Tools",
    "No_Fungi",
    "StatsThroughSkills",
    "blazemod",
    "Tanks",
    "boats",
    "deoxymod",
    "filthy_morale",
    "makeshift",
    "more_classes_scenarios",
    "more_locations",
    "national_guard_camp",
    "no_npc_food",
    "no_rivtech_guns",
    "novitamins",
    "realguns"
### Expected behavior
Metal wreckage located on a young tree yields metal after clearing it.
### Actual behavior
Metal wreckage located on a young tree does not yield metal after clearing it.
### Steps to reproduce the behavior
Case1
Clear metal wreckage on the young tree. No metal/items.
Case2
Destroy the young tree and then clear metal wreckage. Change to get heavy stick/s. No metal/items.
Case3
Burn the young tree and wait for it to burn down. While the tree is burning the metal wreckage disappears. After the fire dies down, only ash remains.

I haven't seen rock rubble on top of a young tree, so I don't know if it would behave like metal wreckage does.

**Comment by kevingranade** [comment]
My guess would be that the wreckage placement code isn't allowed to place items in the tile with the tree.
The most obvious fixes are to either refuse to place item-hiding entities like wreckage on squares that have the NOITEM flag, or to have the wreckage placement code destroy the tree.

**Comment by Coolthulhu** [comment]
Wreckages are solved with a hack - they hide items instead of being "made" of them.
It could be relatively easy to treat wreckage removal as a special kind of deconstruction - then wreckage removal could actually create items instead of just uncovering them.

**Comment by kevingranade** [comment]
Where do those items go?  If they drop on the ground they'll get bumped off of the tree since it's NOITEM, then they'll try to drop on adjacent tiles, which can result in them either ending up buried under wreckage or walking to the edge of the wreckage area, neither is a good outcome.
Also that means mapgen can't place special items under the wreckage.
