### ISSUE TITLE
Radio tower hardcoded function not removed correctly

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#21880]
`./cataclysm --check-mods` says:
> src/overmap.cpp:669 [void overmap_terrains::check_consistency()] Mapgen terrain "radio_tower" exists in both JSON and a hardcoded function. Consider removing the latter.

**Comment by ZhilkinSerg** [comment]
Hmm. I was sure I've removed it. Will check and fix it tonight.

**Comment by ZhilkinSerg** [comment]
#21834
