### ISSUE TITLE
Can't Craft Small Storage Battery

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#21886]
Game version:6771

### Expected behavior
Item browser lists recipe for small storage battery as being in "Under the Hood." So, it should appear as a recipe in game.

### Actual behavior
No small storage battery recipe listed for "Under the Hood" furthermore, could not find recipe in 15 min. of looking at source code.  This leaves storage batteries uncraftable  as their required components cannot be made.

**Comment by Theundyingcode** [comment]
I can just add the recipe in the Item browser once I figure out how to actually do pull requests...

**Comment by CoroNaut** [comment]
It was removed: #19450

**Comment by Theundyingcode** [comment]
> It was removed: #19450

Discussion kinda trails off making it seem like that having no recipe was a conscious choice. I went immediately to this is a bug rather than I'm not going to be able to craft this.  I can disassemble them and I can make other batteries so not being able to make these just doesn't seem correct.

**Comment by kevingranade** [comment]
Repeating from the PR, Small storage batteries are not lead-acid batteries, and they are intentionally uncraftable.

**Comment by Theundyingcode** [comment]
> Small storage batteries are not lead-acid batteries, and they are intentionally uncraftable.

Then how do you get them besides getting lucky and finding an RV to pull the storage battery from? While agree that there should be things the survivor cannot craft, I find this being one ridiculous.  

I raised this after looking to craft a UPS with an early mid-game character and found I couldn't.  Looking at the 6 other types of batteries I could make made me skip "OH, maybe they're like engines and I have to find them." and go straight to annoyed because the game was bugged.

Leaving these uncraftable now is equivalent to saying you can make an 8 ft. or a 10 ft. ladder but 6 ft. ones are outside of your abilities.   Either these need to be craftable or storage batteries and medium storage batteries made uncraftable to create some consistency with the survivor's ability. Anyways, if you have to scavenge them from things I see no reason to bother keeping the medium and regular crafting recipes. 

If you can come up with a more creative name change to make it seem more reasonable like small storage batteries -> lithium-ion batteries and then medium bundle of... that could also work. (calling them lithium-ion would cause problems because of want to use them as explosives though)

**Comment by Zireael07** [comment]
I support renaming the small batteries to lithium-ion.
