### ISSUE TITLE
Cauterizing requires direct contact with fire

### ISSUE THREAD

**Issue by Vzor-** [CleverRaven/Cataclysm-DDA#21891]
Game version:
0.C-23928-g3505803

When cauterizing a wound with a fire as a heat source, you would expect it to require crafting distance to work. This is not the case, it requires you to stand directly next to a fire in order for the option to come up. This is especially risky now that fires spread.

**Comment by ituluwituluwzev** [comment]
I test with a debugged masochist character. They can cauterize from several tiles away from a burning bush.

**Comment by Vzor-** [comment]
@ituluwituluwzev Are you sure that you removed the lighter from your inventory?

**Comment by ituluwituluwzev** [comment]
I throw away the lighter and can't cauterize from several tiles away from fire.

**Comment by BrokenAdmin** [comment]
It's meant to make you heat up the knife, to make it more realistic. It's more of a feature.

**Comment by ituluwituluwzev** [comment]
This is inconsistent, however. Crafting, constructing, vehicle building do not require components being adjacent to player, while realistically components need to be adjacent. Player walking to get nearby component is abstracted.

**Comment by BrokenAdmin** [comment]
It's ignored I'd suppose because the way the movement system is done. I say having to be by the fire makes sense.

**Comment by Vzor-** [comment]
@BrokenAdmin  It does not make sense. The reason it is like that is because it is legacy code. I have come to expect everything to use crafting range. Why change it for this one thing and give the player zero feedback on why he/she can't cauterize.

**Comment by kevingranade** [comment]
Working as intended, crafting doesn't work the same as other actions.

**Comment by Broken-Admin** [comment]
Thanks KF

**Comment by Vzor-** [comment]
May I suggest some feedback to the player then? There are many reasons that the player can't cauterize, I found it very confusing. This is just yet another non-obvious reason that cauterizing won't work. I've seen someone on a livestream fall for this gotcha as well.

**Comment by Broken-Admin** [comment]
You've gotta be by the fire to heat up the knife logically.

**Comment by Vzor-** [comment]
You would think you have to be in usage range. It is the only thing I know of that requires physical contact with the fire (I'm sure there are more I am unaware of).
