### ISSUE TITLE
Cannot repair batteries in vehicle repair menu

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#21897]
Game version: Build 6773

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: Shouldn't matter

### Expected behavior
Hit (r) to repair battery

### Actual behavior
Have to remove the battery to repair it through a welder's activation menu

### Steps to reproduce the behavior
Find vehicle with damaged battery/damage a battery
Examine vehicle
Press (r) on the tile with the battery
You will not be able to select the battery

**Comment by Leland** [comment]
Duplicate of #19451
