### ISSUE TITLE
Add "Play Now (challenge)" menu item for fully random quick starts.

### ISSUE THREAD

**Issue by Kiel97** [CleverRaven/Cataclysm-DDA#21895]
Using "Play Now!" option for starting game selects random profession, gender and name, but not starting place and scenario. This option should vary them as well.

**Comment by BevapDin** [comment]
This was shut down in #21348, now it's an enhancement?

**Comment by Leland** [comment]
My first reaction to this was, "hell yeah," but reading those other issues I do see their point. There are many scenarios that would almost instantly kill new players, and Play Now! is definitely something I see as appealing to newbies.

**Comment by Kiel97** [comment]
Now I understand why it works in this way. I will stick to Random Character option then.

**Comment by Leland** [comment]
Closing.

**Comment by ZhilkinSerg** [comment]
We could add second `Play now!` option colored in `red`?

**Comment by Night-Pryanik** [comment]
I feel that this should be reopened as a lot of players constantly asking for this, and the issue should be resolved in adding of something like `Fully Random Play Now!` form, not in modifying existing `Play Now!`.

**Comment by CHmSID** [comment]
Random Character option always picks the Evacuee scenario. Changing the scenario resets profession, traits, stats and skills, making the random character option basically useless if you want to try a different scenario with a random character.
