### ISSUE TITLE
No recipe for "sheet metal"

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#21896]
Game version:
0.C-23932-g9ab5c97 (tiles)
Operating system:
Windows 7 Professional x64 SP1
Tiles or curses:
Tiles
Mods active:
"type": "MOD_INFO",
  "ident": "user:default",
  "dependencies": [
    "dda",
    "Experimental-Z-Level",
    "Medieval_Stuff",
    "More_Survival_Tools",
    "No_Fungi",
    "StatsThroughSkills",
    "blazemod",
    "Tanks",
    "boats",
    "deoxymod",
    "filthy_morale",
    "makeshift",
    "more_classes_scenarios",
    "more_locations",
    "national_guard_camp",
    "no_npc_food",
    "no_rivtech_guns",
    "novitamins",
    "realguns"

AFAIK the only way to get sheet metal is by disassembling/uninstalling items.

I would like to see a recipe made for it, unless there's a very good reason why it's been omitted (gameplay/balance?).

Currently I'm playing a wilderness start and although I probably still wouldn't be able to craft sheet metal if a recipe existed for it (can't make a clay crucible), I literally have to rely on RNG spawning sheet metal at a metal wreckage site to find any ( haven't found any yet).

The sheet of glass recipe would be a good template to start with.
Tools required: Electric or charcoal forge, crucible/clay_crucible, clay mold (doesn't exist, but I guess just water and clay would be enough for the recipe. Re-usable tool).
Materials: 2 scrap metals (A 2L metal tank requires either a sheet metal or 2 scrap metals to make.)

I hope #20420 is still being worked on.

**Comment by kevingranade** [comment]
We need a workable IRL process for making sheet metal using the tools the survivor has available, I'm not aware of such a process, sheet metal is created with large-scale milling processes in the modern world.

**Comment by Theundyingcode** [comment]
> We need a workable IRL process for making sheet metal using the tools the survivor has available, I'm not aware of such a process, sheet metal is created with large-scale milling processes in the modern world.

That's because it's done on such a large scale.  To make a reasonable sized piece a survivor needs to make a large shallow tray and a lid or something else flat out of heat resistant material.   Then, they can just pour molten metal into the tray, put the lid on it and then jump on it a couple times preferably while wearing something heavy.   It won't exactly be efficient for making large amounts of it but it should work fine.  You could make turn out boots and gloves a requirement... actually why aren't gloves a requirement for forging?

**Comment by Barhandar** [comment]
>It won't exactly be efficient for making large amounts of it but it should work fine

It won't work fine for steel. The whole schtick of steel, as opposed to cast iron, is that it cannot be cast under its own pressure, it's not fluid enough.
>We need a workable IRL process for making sheet metal using the tools the survivor has available, I'm not aware of such a process, sheet metal is created with large-scale milling processes in the modern world.

The survivor can simply beat hot piece of metal into roughly sheet shape - it won't be as nice as factory-made, but it will do the job. Same way platesmiths of old did the sheets they made the platemail out of.  
Also, factory-made sheet metal is rolled, either hot-rolled (much faster and cheaper, but uneven) or cold-rolled (requires pre-treating, costly, but better properties and flat) through series of roll stands with progressively smaller gap, said roll stands being nothing more but pairs of (optionally grooved) heavy metal cylinders, which were invented and used _significantly_ before electricity.  
Not quite something you can carry around, but certainly something someone who welds deathmobiles from scrap can build to manufacture low-quantity sheet metal. Two bunches of steel for the rollers, some metal for the framework and the mechanical linkage, optionally electric motor, and a bottle jack or two for adjusting distance between rollers (=sheet thickness).

**Comment by Nhatorama** [comment]
I just remembered reading [Steel compactor](http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Steel_compactor) a long time ago, but had never needed to use one until now. Although I probably won't find a town/city that has one any time soon (wilderness start), even if I find one I probably won't need to use it since there will be cars I can part out for sheet metal.

The wiki page says the recycler can make sheet metal, but in the [CDDA Raw JSON Browser](http://46.101.143.62:8102/) and my local terrain.json only has: steel lump/chunk and scrap metal under t_recycler.

From closest to farthest of IRL processes:
1. The t_recycler should be allowed to craft sheet metal again.
2. Make the t_recycler into a vehicle rig (recipe or no recipe (take the one from the hardware store)?).
3. A new piece of furniture, rig, or just items necessary. According to [A short sheet metal history](http://www.metalworkingworldmagazine.com/a-short-sheet-metal-history/)
> At the beginning of the nineteenth century the rolling mill structure was essentially the current one: a sturdy cast iron cage with two steel cylinders and the possibility of adjusting, through a screw, the roller distance (Figure 5).

So 1 to 6 steel frame/s, 2 to 3 steel drum/keg, enough scrap metal to fill the drums/kegs, 1 to 3 steel chains at a minimum.
For an electric powered one (rig) add most of the component required to craft a chainswaw: 1x small electric motor, 12x copper wire.
For a muscle powered one (furniture), add a foot crank.

**Comment by Vzor-** [comment]
> We need a workable IRL process for making sheet metal using the tools the survivor has available

IIRC the Romans made segmented metal armor because they were incapable of producing sheet metal in the quality and quantity needed. making strips was much easier. I bet with a hammer and anvil you could make those strips and then weld (maybe even fuse weld) them together to get ghetto steel sheet metal. If you want proper sheet metal you need a roller. For reference this is a Da vinci roller mill http://www.espimetals.com/images/image/da_vinci_rolling_mill.jpg

**Comment by kevingranade** [comment]
> The survivor can simply beat hot piece of metal into roughly sheet shape - it won't be as nice as factory-made, but it will do the job.

I stand corrected, I wasn't thinking of forging, that would be workable.

> Make the t_recycler into a vehicle rig

Too heavy :/

> 2 to 3 steel drum/keg, enough scrap metal to fill the drums/kegs,

Rollers are solid cast iron, that's not the same as filling them with scrap.

**Comment by Mecares** [comment]
Filling drums with concrete could work.

**Comment by Barhandar** [comment]
Drums are too large. The rollers need to be heavy, not wide. As such pretending you're making cast iron (crucible + charcoal in the recipe to carbonize scraps) with two pipes as the molds might work.

**Comment by Theundyingcode** [comment]
What about turning the telescopic cantilever into a crane/wrecking ball and using it as a giant hammer? (I've never actually used it...) You could pull a multi-ton winch off a jeep, fire truck or other heavy vehicle and make a hammer out heavy-duty frame(s), armor plating and maybe a really big engine block.  Then you just raise it up and drop it a bunch of times on heated metal.

**Comment by Treah** [comment]
I think a recipe requiring a hammer and anvil along with forge and charges and metal and make it take a very long time should be sufficient. 

Something like the below 
* 5 hour crafting time. 
* Hammer or sledge hammer 
* Scrap metal or steel or frame 
* Forge with charges 20 maybe... 
* anvil

**Comment by jeremyshannon** [comment]
[https://history.stackexchange.com/questions/20833/how-long-does-it-take-to-craft-the-kinds-of-armour-worn-by-typical-medieval-warr](url)
This guy says that drawing a plate (to make a breastplate) from a steel ingot doesn't take much longer than cutting a sheet out of leather. He then says you could turn out a finished breastplate from the plate of steel in 2 days.
 I don't know that 5 hours just to make a flat piece of metal (the first step in that breastplate) is right, especially once you factor in the time compression -- swords should take several days to make IRL, but they take an afternoon in game, which makes sense when a three month season passes in just 15 days.

**Comment by illi-kun** [comment]
Closing with assumption that sheet metal available in the game is a industry-grade production.

**Comment by kevingranade** [comment]
Whether the output is "sheet_metal" or "crude_sheet_metal", it seems reasonable to hammer it out.

**Comment by Night-Pryanik** [comment]
Closed after #25210.
