### ISSUE TITLE
Mutation category strength calculation is weird

### ISSUE THREAD

**Issue by RadHazard** [CleverRaven/Cataclysm-DDA#21909]
Game Version: 0.C-23936-g42e6718

### Issue

I was digging through the code on mutations and noticed that the mutation category formula is rather weird.  The current formula for calculating strength is here: https://github.com/CleverRaven/Cataclysm-DDA/blob/ae7753da6eec384ff71aa71045e157edd89765db/src/player.cpp#L3048-L3074

For each mutation the player has, it first adds 8 points to each category then recursively traverses the prerequisite list and adds 8 more points for each prereq's category.  On the surface this seems like an okay formula, but after playing around with it I noticed it results in some strange strength levels for certain mutations.

One of the worst ones is the Bear-only Fat Deposits mutation.  It has the prerequisite list ["STR_UP", "STR_UP_2", "STR_UP_3", "STR_UP_4"], which is all of the strength mutations.  Compare the category strengths for a character with just Strong versus Strong + Fat Deposits:

![Strong vs Strong + Fat Deposits](https://i.imgur.com/fZKI3ew.png)

Having Fat Deposits increases your Elf-A, Insect, and Raptor category strengths twice as much as the Ursine category.  This is because those three categories are associated with the Strong (STR_UP) mutation, which gets hit four times by the prereq recursion.  Meanwhile, Ursine is associated with Insanely Strong (STR_UP_4), which only gets hit once by the recursion (plus 8 more points the Fat Deposit mutation itself)

Another odd effect is that the closer you get to a post-threshold mutation, the harder it gets to actually cross that particular threshold.  For example, mutating from Very Strong to Extremely Strong actually makes it harder to cross a threshold that gives Insanely Strong (Ursine and Beast), as Extremely Strong gives more off-category strength than Very strong does.

![Very Strong vs Insanely Strong](https://i.imgur.com/oBoReG3.png)

### Suggestions

The biggest problem is the recursive code can count the same prerequisite mutation multiple times.  As seen in the Fat Deposits example, having all four strength mutations in the prereq list results in Strong being counted four times.  This should probably be changed so that it only counts each unique mutation once.

The second issue is that a mutation which is itself a prerequisite does not count toward any of the categories of the mutations it can change into, which is what causes the second problem.  This would be easy to fix by traversing the "changes_to" list the same way the prerequisite lists are currently traversed.

Finally, mutations with deeper prerequisite trees will naturally accumulate more and more off-category points just because of how many more prerequisites they have.  This could be fixed by adding some kind of decay parameter so that more distant prereqs count for less than closer ones.  I'd suggest halving the bonus each time it recurses, but any kind of decay would be better than nothing.

**Comment by RadHazard** [comment]
I wrote up a quick script to compare the current algorithm vs my suggested one.  Here's what the categories look like for a character with only Ursine mutations (as that tree was probably the worst affected).  The ratios definitely look much better to me, though the exact values are a lot lower.

#### Ursine (character with all pre-threshold mutations)
| Category | Old Strength | New Strength |
| --- | --- | --- |
| MUTCAT_URSINE | 208 | 137 |
| MUTCAT_BEAST | 104 | 59 |
| MUTCAT_FELINE | 56 | 42 |
| MUTCAT_LUPINE | 128 | 40 |
| MUTCAT_RAT | 56 | 40 |
| MUTCAT_CHIMERA | 104 | 36 |
| MUTCAT_CATTLE | 152 | 35 |
| MUTCAT_LIZARD | 152 | 25 |
| MUTCAT_RAPTOR | 184 | 18 |
| MUTCAT_FISH | 16 | 16 |
| MUTCAT_INSECT | 152 | 15 |
| MUTCAT_PLANT | 120 | 14 |
| MUTCAT_SLIME | 8 | 12 |
| MUTCAT_SPIDER | 8 | 8 |
| MUTCAT_BIRD | 0 | 7 |
| MUTCAT_ELFA | 144 | 7 |
| MUTCAT_CEPHALOPOD | 8 | 6 |
| MUTCAT_ALPHA | 112 | 4 |
| MUTCAT_TROGLOBITE | 80 | 3 |

#### Ursine (character with all pre- and post-threshold mutations)
Note that with the old algorithm, the character actually has a higher value in the Raptor and Lizard categories

| Category | Old Strength | New Strength |
| --- | --- | --- |
| MUTCAT_URSINE | 496 | 204 |
| MUTCAT_BEAST | 400 | 115 |
| MUTCAT_CHIMERA | 480 | 88 |
| MUTCAT_LUPINE | 376 | 64 |
| MUTCAT_FELINE | 224 | 64 |
| MUTCAT_RAPTOR | 640 | 60 |
| MUTCAT_LIZARD | 592 | 58 |
| MUTCAT_CATTLE | 456 | 51 |
| MUTCAT_RAT | 56 | 40 |
| MUTCAT_SPIDER | 184 | 38 |
| MUTCAT_INSECT | 424 | 19 |
| MUTCAT_PLANT | 344 | 19 |
| MUTCAT_FISH | 16 | 16 |
| MUTCAT_SLIME | 8 | 12 |
| MUTCAT_MEDICAL | 56 | 9 |
| MUTCAT_TROGLOBITE | 248 | 9 |
| MUTCAT_ELFA | 408 | 9 |
| MUTCAT_ALPHA | 328 | 8 |
| MUTCAT_BIRD | 0 | 7 |
| MUTCAT_CEPHALOPOD | 8 | 6 |

And here's a chart comparing the difference in the threshold breaching chance (highest category / total strength), assuming a character with all pre-threshold mutations for that category.  Most categories stayed fairly close to the same.  Ursine doubled, bringing it more in line with most other categories.  Raptor and Alpha dropped a fair bit, while Cattle and Trogolobite got a bump up.  Despite that, none of the new ratios look out of line to me.

| Category | Old Chance | New Chance | Change |
| --- | --- | --- | --- |
| ALPHA | 0.33 | 0.28 | -0.05 |
| BEAST | 0.23 | 0.24 | +0.01 |
| BIRD | 0.30 | 0.29 | -0.01 |
| CATTLE | 0.16 | 0.24 | +0.08 |
| CEPHALOPOD | 0.38 | 0.36 | -0.02 |
| CHIMERA | 0.22 | 0.24 | +0.02 |
| ELFA | 0.30 | 0.29 | -0.01 |
| FELINE | 0.26 | 0.26 | +/-0 |
| FISH | 0.23 | 0.23 | +/-0  |
| INSECT | 0.24 | 0.23 | -0.01 |
| LUPINE | 0.21 | 0.22 | +0.01 |
| RAPTOR | 0.32 | 0.26 | -0.05 |
| RAT | 0.23 | 0.24 | +0.01 |
| URSINE | 0.12 | 0.26 | +0.15 |
| LIZARD | 0.23 | 0.25 | +0.02 |
| MEDICAL | 0.39 | 0.34 | -0.05 |
| PLANT | 0.41 | 0.38 | -0.03 |
| SLIME | 0.23 | 0.26 | +0.03 |
| MUTCAT_SPIDER | 0.25 | 0.28 | +0.03 |
| MUTCAT_TROGLOBITE | 0.15 | 0.23 | +0.08 |

**Comment by AncientSion** [comment]
I have no experience with mutations, bit when i look at those numbers it seems to be that currently strength seems to be waaaaay to high even for powerful traits like Ursine, Beast etc.
If STR scales linearly, it would mean some of those mutant strains would make you 10 times as powerful as a normal human being.

For refernece, a male Gorilla (which is REALLY strong), is about 6x times as strong as male Human.

Standard STR for a Human would be 8, which equals a carry weight of 45kg.
Double STR (16) results in carry weight 77kg, so STR progression does not seem to be linear.
Going by that, a Human as STR 8. Going by 6x as strong (by carry weight), a Male grown Gorilla would have something like 50 Strenth. And Gorillas are MASSIVE. I would find it very curious to encounter mutations (on a human !), that would make said Demihuman 2 or 3 times as strong as said Gorilla.

For further reverence, a BEAR is (very likely) far less strong than a Gorilla. Of course the Bear seems more dangerious because of its claws, but really, a Gorilla as more strength, by far.

This means something like a STR of 100 or more is absolutly unreal and i would wager a guess that the human body would not be able to support such mutation, because the base strength is just too low.

So alone the fact that your suggestion scales the STR down a lot, would make a great deal of sense to me, even without considering the potentially bug-riddles algo that results in those high STR values in the first place.

**Comment by RadHazard** [comment]
These numbers are for mutation category strength (a measure of how "wolf-like"/"bear-like"/"cat-like"/etc. your character is), not the STR stat.  The value has a few effects:

* Once your strongest mutation category reaches a particular value, you'll start having mutation dreams.  The values are 20 - 35 for 1st tier dreams, 35 - 50 for 2nd tier dreams, and 50+ for 3rd tier dreams.
* When injecting a serum, in order to cross the threshold three things need to be true:
    - you need a minimum of 50 category strength in the serum's category (equal to 3rd-tier dreams, ~5 mutations in that category)
    - that category has to have the highest category strength value out of all mutation categories
    - and finally a random roll has to succeed, with a success chance equal to (strength in that category / sum of all mutation category strengths)

My suggested change fixes a few issues related to that:

* A character with every Ursine mutation (so as bear-like as possible) will have Raptor dreams because the game thinks they're more raptor than bear
* You currently need to inject a gallon or two of Ursine serum on average before you'll cross the Ursine threshold because Ursine mutations give a disproportionately large amount of strength in the Raptor and Lizard categories

Ursine is by far the worst category, but there are a few others that are also iffy.  My post-threshold wolf character is currently having Beast dreams because she has a single Beast mutation from a while back

**Comment by Night-Pryanik** [comment]
Closed by #21911.
