### ISSUE TITLE
Setting corpses on fire should deny resurrection

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#21916]
In my opinion, an alternative to smashing or butchering corpses would be to set said corpses on fire. That is to say, a "burnt" corpse should be considered destroyed and should disable that zombies ability to resurrect.

It would be quicker than pulping zombies, but it would require a fire charge. It would also make sense that a burned to cinders corpse would be "done for".
If necesarry, it could be make a mandatory requirement to have Gasoline within the tile in question, as to make sure the corpses burn to cinsider, as opposed to just having a upper layer burn mark.

**Comment by Coolthulhu** [comment]
It already is the case, although currently it requires a medium fire.

**Comment by AncientSion** [comment]
@Coolthulhu 
Oh, sorry.
How exactly can i spawn a medium fire as opposed to a "small fire" ?
Just put more stuff that burns (clothing, wood?) onto the tile in question ?

Issue can be closed.

**Comment by Coolthulhu** [comment]
Spawn a small fire and let it burn some good fuel, such as gasoline or lots of wood.
Though currently the mechanic is rather weak: you'd need a flamethrower to stop resurrection by necros.
