### ISSUE TITLE
Drop items after use when used from ground.

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#21918]
When using a towel to dry yourself, the used "towel (wet)" always ends up in the player inventory, regardless if if what used from the ground up or not.
I would very much love it when the towel ends up on the ground after use. I think this could be the standard behavior for everytime you use a towel.

**Comment by Nhatorama** [comment]
I would prefer if it behaved like how food and drinks work.

When drinking from a small bottle that's on the ground, you leave the empty bottle on the ground.
When drinking from a small bottle that's in your inventory, you place the empty bottle in your inventory.

**Comment by AncientSion** [comment]
Works for me, i pick up the towel from the ground anyway, i just dont want to have to manually drop it every rainy day.

**Comment by angoddu** [comment]
I usually carry my towel around with me so I like how the wet towel stays in my inventory. It makes it much easier for me.

**Comment by Papaya-Plan** [comment]
This could apply to other tools as well. I like to leave a camp fire drill by my brazier/fireplace/stove, and it gets automatically picked up just like a towel, and then I have to manually drop it again.

**Comment by kevingranade** [comment]
I'm totally on board with use of items from ground not leaving them in the player inventory.

**Comment by Sammmmm** [comment]
Just adding my two cents, I came here to submit this issue (or take a peak at the code when I have time).  I would like the option to leave my washboard and soap by the pool and use them from the ground.  Using a first aid kit from the ground actually throws the debug exception text in my current build.

**Comment by Night-Pryanik** [comment]
Good suggestion, but closing per lack of discussion for a long time and to clean up the issues list.
