### ISSUE TITLE
Add Crafting Result Amounts

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#21923]
Would it be possible to add resulting amounts to the crafting menu?  I keep ending up guessing batch sizes when making supplies for stuff.

### Expected behavior
Food tells you how many portions it makes:
![cookie](https://user-images.githubusercontent.com/15700895/30524859-0d4adf28-9bc1-11e7-9663-b6654e34e615.PNG)
I want other things to do the same. Example:
![bat](https://user-images.githubusercontent.com/15700895/30524865-318c4980-9bc1-11e7-93ff-4da8f74d3713.PNG)

### Actual behavior
No indication of created amounts:
![image](https://user-images.githubusercontent.com/15700895/30524876-607a4ed6-9bc1-11e7-9372-ffdd88465b57.png)
Batteries I know are 100 but there are a lot of things I don't regularly craft.

**Comment by angoddu** [comment]
Please please please have this get implemented. I'm still learning the system so I don't think I could do this but this would be extremely helpful.
