### ISSUE TITLE
Explorable fog of war

### ISSUE THREAD

**Issue by JohnMeadow1** [CleverRaven/Cataclysm-DDA#21928]
It would be magnificent if we could see regions of the play area that has already been revealed. E.g. terrain, buildings layouts, furniture, vehicles. No items and no enemies. 
This would be huge quality of life improvement.
The huge black spots are annoying.

This is basically the same mechanic that is used on global world map.
I believe it would require making secondary tile map with binary information (revealed, hidden). This will increase memory requirements and possibly save size.

This could be restricted to limited area around the player, and vision data could be forgotten on save. 
I believe it would be great feature.

I believe Issue #19053 has similar idea. 

Example:
![fog_of_war](https://user-images.githubusercontent.com/23294139/30564274-cb01b16e-9cc4-11e7-844e-7ac86bd37e8e.jpg)

**Comment by Leland** [comment]
This actually is just a different angle to the discussion in #19053. I recommend you close this one and post all this as a comment over on that issue. Be sure to check out #17766 as well, which prompted #19053.

**Comment by cainiaowu** [comment]
There was a PR with similar feature (#11808).

But it got closed.

**Comment by kevingranade** [comment]
#11808 wasn't a problem conceptually, just the implementation.

**Comment by JohnMeadow1** [comment]
I'll keep this issue opened for now, and see where #19053 goes.
I was thinking.
We have mechanics for regions with low light.  How hard would it be to turn it on for entire view area?
It would make exploration too easy, but as option, or trait to try it out.
I really think that it is visually boring if you have 90% od your screen black.

**Comment by kevingranade** [comment]
> I believe it would require making secondary tile map with binary information (revealed, hidden). This will increase memory requirements and possibly save size.

Isn't enough, since monsters, NPCs, and potentially other players can modify the map when you aren't there, so a binary "seen" map would result in revealing information to the player they should not have.

However, I do think it could be limited to just terrain and furniture, which is tiny.

**Comment by JohnMeadow1** [comment]
Ah, I haven't thought of that. 
Well players could live with knowing if wall have collapsed out of their vision, But I can see the implementation problem. It would create allot of redundancy code/memory wise,
Still I'll argue that seeing where a player have already been makes game play better vs reveling NPCs map modification. 
!st it would make the game less claustrophobic.
2nd it would reduce backtracking in places like laboratories.

**Comment by JohnMeadow1** [comment]
I have another idea. Maybe this fog of war be limited to minimap only ?
That would help as well. Still it would leave a lot of black screen in the view, but could be easier to implement.

**Comment by lucianposton** [comment]
I seem to be in the minority, but I prefer the darkness. It thematically fits the atmosphere of the game as I imagine it.

If such a fog of war feature were added, I'd encourage the developer to make it an optional feature.

> I have another idea. Maybe this fog of war be limited to minimap only ?

I rather like this idea as the minimap (by definition) keeps the revealed fog of war at a lower resolution.

**Comment by AMurkin** [comment]
One problem here: minimap belongs to tiles only.

**Comment by JohnMeadow1** [comment]
> I seem to be in the minority, but I prefer the darkness. It thematically fits the atmosphere of the game as I imagine it.
Well it does create unique atmosphere of constant uncertainty. I agree it would be best to have this as an option in menu.
On the other hand this constant claustrophobic darkness surrounding the player is off-putting to part of player base.
> One problem here: minimap belongs to tiles only.
What do you mean by that?

**Comment by AMurkin** [comment]
If fog of war will be applied to minimap, than difference between console- and tiles-version will be increased.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
