### ISSUE TITLE
Too many mandatory overmap specials warning

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#21931]
Game version: master branch, 8a96896720

Mods active:
* More Locations
* Tall Buildings
* Urban Development

### Expected behavior
Some ideas:
* Warn the user while he is adding mods that the selected mods have an issue. A normal user won't understand the debug warning.
* Remove the overmap special limit ?

### Actual behavior
![debug warning](https://i.imgur.com/L0LFzOF.png)

### Steps to reproduce the behavior
* Create a world with > 72 overmap specials
* Create a character to trigger overmap special verification

**Comment by kevingranade** [comment]
in theory we can make that assertion when you add the module instead of when you load the game, though that could have some serious performance impact.

**Comment by kevingranade** [comment]
There's another rather good option, which is to remove the ability for mods to set mandatory specials at all.  Instead missions and scenarios that declare them as a target would set them as mandatory, which are the only pressing reason to have a special be mandatory in the first place.

**Comment by Maleclypse** [comment]
@Venera3  I would consider your work on mapgen to probably be the closing PR for this issue.   Please let me know if this shouldn't be closed.

**Comment by Venera3** [comment]
Yes, #47071 fixed this check to ignore unique specials.
