### ISSUE TITLE
Running is Hard-coded to PC. Should be modularized for use by NPCs

### ISSUE THREAD

**Issue by rtizzy** [CleverRaven/Cataclysm-DDA#21937]
As explained in title, running is currently hardcoded to PC characters. 

Making this modular would allow for solving issues such as those below. 

https://github.com/cataclysmbnteam/Cataclysm-BN/issues/15

**Comment by Leland** [comment]
No movement in several years - closing! If there's still interest, ping me and we can reopen :)
