### ISSUE TITLE
Get Debug Warning on Game Start

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#21945]
Game version:6784 

Operating system:windows

Tiles or curses:Tiles

Mods active:[
  "dda",
  "filthy_morale",
  "no_npc_food",
  "craftgp",
  "brightnights",
  "FIC_Weapons",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "DinoMod",
  "crazy_cataclysm",
  "national_guard_camp",
  "more_locations",
  "Experimental-Z-Level",
  "Urban_Development",
  "blazemod",
  "Tanks",
  "jury_rigged_robots",
  "nm_wpns",
  "boats",
  "No_Acid_Zombies",
  "more_classes_scenarios",
  "StatsThroughSkills"
]

### Expected behavior
Load with no errors. 

### Actual behavior
![image](https://user-images.githubusercontent.com/15700895/30670064-75d30f22-9e26-11e7-9fe2-b3e2bac78f8c.png)

First time trying tiles and this pops up every time a world gens.  I feel like I got this with tiles just not the actual text as I had to hit space-bar to move on from a black screen.
### Steps to reproduce the behavior
Just make a new world/reset it and try and start a new game.

**Comment by lucianposton** [comment]
dup of #21931.

fyi, if you remove "Experimental-Z-Level" aka "Tall Buildings" and "national_guard_camp" aka "Beta National Guard Camp", that'll fix the issue. That should reduce the number of overmap specials to exactly 72.
