### ISSUE TITLE
Interface issues

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#21943]
- [x] If holster has limit only on volume, everything is fine. If holster has limit also on weight, the line "Up to X L or Y kg" is suddenly goes up.
    ![234](https://user-images.githubusercontent.com/11132525/30663212-8de49712-9e52-11e7-976e-377fe89c7871.PNG)
- [x] Tool requirement in vehicle interaction menu sometimes moves lines in a strange manner.
    ![123](https://user-images.githubusercontent.com/11132525/30663772-6f7d1bd0-9e54-11e7-84fd-f340ed865b23.PNG)

- [ ] On the second pic the fuels section and the offroad % are displaced. 
    ![567](https://user-images.githubusercontent.com/11132525/30663701-2cd6472a-9e54-11e7-8c6b-70eab2dda580.PNG)

- [x] Ammo type display is broken.
    ![789](https://user-images.githubusercontent.com/11132525/30664295-dcf0f942-9e55-11e7-9c2e-65a68eaffc75.PNG)

----

Edit by @Leland: moved to checkboxes

**Comment by AMurkin** [comment]
> Ammo type display is broken.

What's that screen? And window width.

**Comment by Night-Pryanik** [comment]
> What's that screen? And window width.

That's craft screen, info on the right side. Window width is 130, but I think it doesn't matter.

**Comment by AMurkin** [comment]
My try to reproduce number 4:
![image](https://user-images.githubusercontent.com/1931904/30709521-26a3d3a6-9f0b-11e7-8e41-1eb9e1d715bc.png)

**Comment by Night-Pryanik** [comment]
Hmmm, I don't know. Downloaded the latest version now, checked - the issue is still here.
Can anyone else confirm this?

**Comment by Theundyingcode** [comment]
Looks just fine to me (fully spelled out). My window width is 144.

**Comment by AMurkin** [comment]
So 1 and 2 fixed. 4 in question. 3 - nightmare code (for me).

**Comment by AMurkin** [comment]
Did you used server-compiled build or compile it by yourself?

**Comment by Night-Pryanik** [comment]
>Did you used server-compiled build or compile it by yourself?

Pre-compiled.

**Comment by Night-Pryanik** [comment]
Can't reproduce fourth issue in the latest experimental.

**Comment by OzoneH3** [comment]
The vehicle UI needs a total rework at this point. On 80x24 it's barely readable at all.
