### ISSUE TITLE
Acquiring missions momentarily freezes the game or fails mission initialization, depending on world options for city

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#21950]
Game version: 8a96896720

Operating system: linux

Tiles or curses: tiles

Mods active: 
1   "dda",                                                                        
2   "More_Survival_Tools",                                                        
3   "Urban_Development",                                                          
4   "boats",                                                                      
5   "filthy_morale",                                                              
6   "more_locations",                                                             
7   "no_npc_food",                                                                
8   "novitamins",                                                                 
9   "realguns"                                                                    

### Expected behavior

Either a notification that the mission is being generated or don't hang.

### Actual behavior

Hangs at 100% cpu usage for a variable amount of time on my desktop with i7 @ 4GHz. Sometimes it will hang for 3 seconds. Other times, it hangs for nearly a full minute and "Unable to place all configured specials, some missions may fail to initialize." is added to the message log. See https://github.com/CleverRaven/Cataclysm-DDA/blob/dbc349eff413dad464dccf0384a5df21d243fe1d/src/overmap.cpp#L4377

### Steps to reproduce the behavior
- Create new character in shelter
- Increasing "Size of cities" and "City spacing" world options seems to exacerbate the issue to the point that missions consistently fail to initialize.
- Accept mission from terminal in shelter

**Comment by kevingranade** [comment]
The mission in question is probably important, some missions kick off a search for a building, which is probably what is causing the delay.

**Comment by lucianposton** [comment]
I started a new character in a new world and picked up the terminal mission. This time is hung for nearly a full minute.

For this world, the Size of cities was 8 and City spacing was 8. Perhaps that makes it more difficult to find a suitable location to place the mission.

**Comment by Night-Pryanik** [comment]
Should this be closed after #28959?
