### ISSUE TITLE
[Sugesstion]Drop the obsolete PK_REBALANCE mod in current master

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#21952]
The mod is maintained in another repo.

I sugesst we drop the outdated one in the current master so that cdda-launcher wont try to overwrite the uptodate version with an obsolete one when updating the core game.

See issue https://github.com/pisskop/PKs_Rebalancing/issues/30.

**Comment by ZhilkinSerg** [comment]
Pisskop just should've changed `ident` of the mod when it was moved to separate repository.

**Comment by Leland** [comment]
Duplicate of #20326
