### ISSUE TITLE
Character font inside overmap printing half normal size

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#21957]
Game version: 8a96896720f46d516190bc3887440ad2b0cd0dc9, but this happens on versions of the game back 1.5 years ago when I'm certain I didn't have this issue, namely e592b36cc3. I'm wondering if it might be due to a font library I've since updated e.g. freetype, which had a massive update earlier this year that had significant changes to its rendering.

Operating system: linux x86_64

Tiles or curses: tiles

### Expected behavior

Fonts should be same height as other fonts used elsewhere.

### Actual behavior

Notice how the 'F' character in Forest in the image below is double the height of the F's inside the overmap.

![](https://i.imgur.com/DRs7qNQ.png)

### Steps to reproduce the behavior
- Open overmap

**Comment by lucianposton** [comment]
fyi versions of all libs dynamically linked to cataclysm-tiles

app-arch/bzip2-1.0.6-r8
dev-lang/lua-5.1.5-r4
dev-libs/libbsd-0.8.3
media-libs/alsa-lib-1.1.2
media-libs/flac-1.3.2-r1
media-libs/freetype-2.8
media-libs/libjpeg-turbo-1.5.1
media-libs/libmad-0.15.1b-r8
media-libs/libogg-1.3.2
media-libs/libpng-1.6.29
media-libs/libsdl2-2.0.4
media-libs/libsndfile-1.0.28-r1
media-libs/libvorbis-1.3.5
media-libs/sdl2-image-2.0.1
media-libs/sdl2-mixer-2.0.1
media-libs/sdl2-ttf-2.0.14
media-libs/tiff-4.0.8
media-libs/tremor-0_pre20130223-r1
media-sound/pulseaudio-10.0
net-libs/libasyncns-0.8-r3
sys-apps/dbus-1.10.18
sys-apps/tcp-wrappers-7.6.22-r1
sys-apps/util-linux-2.28.2
sys-devel/gcc-5.4.0-r3
sys-libs/glibc-2.23-r4
sys-libs/zlib-1.2.11
x11-libs/libICE-1.0.9-r1
x11-libs/libSM-1.2.2-r1
x11-libs/libX11-1.6.5
x11-libs/libXau-1.0.8
x11-libs/libXcursor-1.1.14
x11-libs/libXdmcp-1.1.2-r1
x11-libs/libXext-1.3.3
x11-libs/libXfixes-5.0.3
x11-libs/libXi-1.7.9
x11-libs/libXinerama-1.1.3
x11-libs/libXrandr-1.5.1
x11-libs/libXrender-0.9.10
x11-libs/libXtst-1.2.3
x11-libs/libXxf86vm-1.1.4
x11-libs/libxcb-1.12-r2

**Comment by DanmakuDan** [comment]
#21902 is still waiting to be merged, you will also have to update your config/fonts.json file so that the overmap font values are the correct size:

```
  "overmap_fontwidth": 8,
  "overmap_fontheight": 16,
  "overmap_fontsize": 16,
```

**Comment by lucianposton** [comment]
Changing 

`"overmap_fontsize": 8,`

to 

`"overmap_fontsize": 16,`

fixed the issue. Thanks

**Comment by BevapDin** [comment]
Please check/post your settings in "config/fonts.json" - there was a bug recently that caused the file to contain wrong values.
