### ISSUE TITLE
Disassemble item menu doesn't take lightning level into account when determining if it is possible to disassemble

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#21955]
Game version: 0.C-6786

Operating system: Windows XP SP3 x86

Tiles or curses: tiles

Mods active: default only

### Expected behavior
Disassemble item menu shows reasons for why it isn't possible to disassemble item with every lightning level.
### Actual behavior
Disassemble item menu shows reasons for why it isn't possible to disassemble item only if the lightning level is enough for disassemble.
### Steps to reproduce the behavior
Try to disassemble item through the disassemble item menu with very dark lightning level.
![default](https://user-images.githubusercontent.com/11132525/30710761-3b22de2c-9f0f-11e7-97f3-2a5050bf3556.png)
![default](https://user-images.githubusercontent.com/11132525/30710726-2a83b212-9f0f-11e7-8586-b184572f5551.png)

The first pic is with very dark lightning level, the second pic is with bright lightning level. Look at the down-filled blanket.

**Comment by AMurkin** [comment]
Could be fixed by implementing @Coolthulhu 's suggestion in #19952:

> Minor: picking up the object should not be required. Objects directly under the player can be disassembled without picking them up, extending that to nearby ones wouldn't be hard.

Delete 4 lines in [pickup_inventory_preset.get_denial](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/game_inventory.cpp#L188:L191):
```
                } else if( !p.can_pickVolume( *loc ) ) {
                    return _( "Too big to pick up" );
                } else if( !p.can_pickWeight( *loc ) ) {
                    return _( "Too heavy to pick up" );
```

**Comment by Night-Pryanik** [comment]
No, picking up heavy or big items is not an issue. Not showing why I can't disassemble items with very dark lightning is the issue.

**Comment by AMurkin** [comment]
Build 6790

**Comment by Night-Pryanik** [comment]
Hmm, 0.C-6790, the problem is no longer here.
