### ISSUE TITLE
Can't craft gunpowder

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#21962]
I would like a recipe to be added for normal gunpowder. Right now you can only get gunpowder from a gun store back room and from disassembling other ammo.

**Comment by Zireael07** [comment]
I believe this is intended, unless you know a DIY way to get gunpowder?

**Comment by lucianposton** [comment]
1. extract saltpeter from zombie poo
2. grind with sulfur in mortar
3. ??
4. profit

**Comment by SaltatorMortis** [comment]
isnt that simple?
75:15:10 ratio of potassium nitrate:charcoal powder:sulfur
the diy method:
for potassium nitrate: Manure is mixed with ashes, straw, and urine
for sulfur in the vulcanic regions
and dont forget the scale XXD... and a lot of time namly months

**Comment by Cyrano7** [comment]
@angoddu You can craft black powder though. I believe it was intentional that the industrial grade gunpowder was left uncraftable and that you would have to salvage for it instead. I'll look for that thread when I get the chance.

**Comment by lucianposton** [comment]
I think he was referring to gunpowder (not smokeless powder) for ammo for 1800s guns, like early gen colt 45s.

**Comment by angoddu** [comment]
I'm talking about the gunpowder item that is used to reload a 9mm bullet

**Comment by lucianposton** [comment]
> I'm talking about the gunpowder item that is used to reload a 9mm bullet

Oh. If it's called "gunpowder", that name is a mistake. It should be smokeless powder, not gunpowder. You wouldn't put gunpowder in a 9mm cartridge, unless you want to badly gunk up your gun.

**Comment by BevapDin** [comment]
We had this discussion (in #12655) - the simple recipe for gunpowder was actually *remove* on purpose.

**Comment by kevingranade** [comment]
Yes, this is working as intended, I believe there are mods floating around if you want magic smokeless powder crafting, but the main game isn't going to have this kind of recipe.
