### ISSUE TITLE
Able to cauterize wounds with just scissors

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#21969]
Game version: cbad6e7c71

Operating system: linux

Tiles or curses: tiles

Mods active:[
  "dda",
  "More_Survival_Tools",
  "realguns",
  "Urban_Development",
  "more_locations",
  "boats",
  "filthy_morale",
  "no_npc_food"
]

### Expected behavior

I'd expect some heat or electricity required to cauterize a wound.

### Actual behavior

![](https://i.imgur.com/98yOV5n.png)

### Steps to reproduce the behavior

1. pick up pair of scissors
2. acquire bleeding wound
3. open item action menu

**Comment by Night-Pryanik** [comment]
Are you sure you don't have any lighter, or hotplate, or similar in your inventory and vicinity?

**Comment by lucianposton** [comment]
Don't believe so, but I didn't double check my inventory. I should have made a copy of that save game. I'll see if I can repro it again later.
