### ISSUE TITLE
crash on char generation

### ISSUE THREAD

**Issue by SaltatorMortis** [CleverRaven/Cataclysm-DDA#21960]
Game version:
6790 (server & self build)
Operating system:
win10
Tiles or curses:
curses

when you generate a character and are on the skills and when you scroll beyond to speaking or scroll once up the game crashes.

**Comment by SimonVanGerwen** [comment]
Exact same issue, scrolling beneath submachine guns [unto survival] to be exact.
Clean install.

  Application Name:	cataclysm-tiles.exe
  Application Version:	0.0.0.0
  Application Timestamp:	afa0af98
  Fault Module Name:	cataclysm-tiles.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	afa0af98
  Exception Code:	c0000005
  Exception Offset:	0000000000d01d86
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1043
  Additional Information 1:	d786
  Additional Information 2:	d7862118a5399fb3fa6c955579f12b1d
  Additional Information 3:	e988
  Additional Information 4:	e988f0f93b021b15bad0d4cf89809e98

**Comment by lucianposton** [comment]
Someone in irc said he's crashed 4 of 4 times when scrolling down to unarmed combat.

**Comment by CallidusD** [comment]
I am that someone in irc. Tested another 4 times. generated new world without mods, created custom characters and was able to scroll freely up and down through the skills menu down to throwing. Attempting to go below that to trapping crashed each time.

**Comment by lucianposton** [comment]
windows dump file of crash

 https://drive.google.com/open?id=0ByvvtLpeIpshVzlpQjhPNlI5SXM

**Comment by SaltatorMortis** [comment]
ps i rolled back to 6788 and it works
