### ISSUE TITLE
NPC says "Someone forgot to code this message id"

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#21970]
Game version: cbad6e7

Operating system: linux

Tiles or curses: tile

Mods active:[
"dda",
"More_Survival_Tools",
"realguns",
"Urban_Development",
"more_locations",
"boats",
"filthy_morale",
"no_npc_food"
]

### Expected behavior

I expected someone to code that message id! (or use a valid id)

### Actual behavior

![](https://user-images.githubusercontent.com/646121/30769914-b4a031a0-9fd7-11e7-9f4b-cd183d19fc29.png)

### Steps to reproduce the behavior

Load [save game](https://github.com/CleverRaven/Cataclysm-DDA/files/1326266/gore.zip) and talk to nearby npc. This occurred when I asked for another mission after having just completed the first.

**Comment by cainiaowu** [comment]
this bug will always happen when you finished last quest in the quest line and request a new mission.

**Comment by ituluwituluwzev** [comment]
Duplicate #21097
