### ISSUE TITLE
Suggestion: Rename Storage Batteries as Li-Ion 

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#21975]
I previously opened #21886 and subsequent PR #21887 because I assumed while playing that the inability to craft small storage batteries was a bug while it was intentional.

I believe the reason for my assumption is that unlike engines which the player can craft none of, the crafting menu has a lot of things with "battery" in the name creating a feeling of incompleteness.  Changing the names from "X storage battery"  would create some separation, reducing this issue.

My proposed changes are:

- small storage battery -> li-ion power cell "A small battery made using pre-Cataclysm lithium ion technology. Useful for crafting."

- medium storage battery -> small li-ion battery array "A small storage battery comprised of smaller lithium ion power cells"

- storage battery ->li-ion battery array "A large storage battery comprised of many lithium ion power cells.  Could be installed into a storage battery case for easy removal from a vehicle, or just welded straight in."

Additionally, make them explode in fire as Li-Ion batteries are basically incendiaries IRL. 
li-ion power cell: power:1 distance factor: 0.2 fire: true
small array: power 6 (8x li-ion cells -20% for conflicting power)
battery array: power 20 (4x small array -20% =19.6 rounded to 20)

I should have no problems making these  changes myself however, doing so requires changing multiple files and is tedious so I wanted to make sure this is acceptable first.

**Comment by DemAvalon** [comment]
Batteries are easily understandable as a non native English speaker, while I never heard of Li-ion anything.

**Comment by BorkBorkGoesTheCode** [comment]
Li-ion is a contraction of lithium ion.

**Comment by Theundyingcode** [comment]
Didn't really consider the translation part.  I was worrying about having a super long unwieldy name. "Li-Ion  Battery" is their semi-official shortened name while in my circle of engineering friends we use "Li+ Battery."  I made sure to spell it out all the way in the description though.

OK, the name needs revising but is the general idea OK?

**Comment by AlecWhite** [comment]
Why not use "Li-Ion Battery" as name and then explain in the description what li-ion stands for?
I mean, aren't descriptions to describe the item? Let's use it for it.

**Comment by Coolthulhu** [comment]
Exploding batteries don't really sound fun. And having them only explode as items (not as vehicle mounted parts) would be a rather major discrepancy, considering most vehicle batteries will be installed and not just lying around.

As for naming: if the clarification is needed, I'd keep it to description. As in, have "storage battery" in name, but then description would clarify it's a Li-Ion battery/power cell, to explain why you can't craft it.

**Comment by Theundyingcode** [comment]
OK changing just the description would be less work anyways...

I'm assuming that @Coolthulhu 's comment implies that making vehicle batteries burn up is a harder feat to accomplish... Still battery fires would be really fun; crafting a delayed action incendiary would be super easy even at low skill levels.

[http://www.sandraandwoo.com/2016/11/13/0837-the-divine-comedy-page-34-part-4/](url)

**Comment by Coolthulhu** [comment]
> Still battery fires would be really fun

They wouldn't, molotovs do that job for a cheaper price. And currently they are quite weak due to fire mechanics, so that would have to be changed first for battery fires to be fun.

**Comment by Theundyingcode** [comment]
I'll go and just change the descriptions then.
