### ISSUE TITLE
Fire Axe too strong

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#21981]
### Expected behavior
Bash 8
Cut 18
Hit +1
Moves 139

### Actual behavior
Bash 20
Cut 20
Hit +1
Moves 139

### Reason
Fire Axe is OP. Especially the insane BASH makes no sense to me. It regulary comes up as the "i found a fire axe, yay i dont have to worry about thingy anymore" in various online conversations.

**Comment by awesine** [comment]
Gonna have to nerf a lot of other weapons too, then.

**Comment by AncientSion** [comment]
Like which ? From my experience (not 100s of hours), Fire Axe for a random loot definitly stands out.
I think spears in general are too strong, too, but Fire Axe is on another level and its problem stems from its inherit damage stats, as opposed to the greater balancing problem of spears, which is ability to kite by running.

**Comment by Coolthulhu** [comment]
It is rather good, but your nerf would drop it below knife spear.
It has raw modified DPT (calculated as `(bash+cut)*100/moves*(100%+to-hit*10%)`) of 31.7.
Some comparable numbers:

Weapon | DPT (no techniques) | DPT (rapid)
---|---|---
Fire axe | 31.7 | N/A
Sword bayonet (not attached) | 33.6 | N/A
Machete | 35.1 | N/A
Barbed wire bat | 28.2 | N/A
Combat knife | 26.8 | 35.3
Katana | 25.8 | 34.1

Raw DPT isn't a perfect measure, but it actually overrates multi-typed weapons like the fire axe. Machete is even better than it looks from the numbers here.

**Comment by Tsunder** [comment]
the fire axe's high bash damage is fine, it is IRL used to bash down doors windows etc (in case of emergency, such as fire) and it should be reflected in game.

the fire axe only has one techinque, brutal, no blocking

suggest instead reducing both bash and cut by a few points. or even raising its moderately high move cost per attack

**Comment by AncientSion** [comment]
I did look into increasing the moves per attack, which is a fair suggestion. However, its hardcoded and based upon item weight/volume. So the only way ( i see ) of nerving it via moves per attack (if nerf is necesarry), would to be make it more clunky.

@Coolthulhu thank you for the detailed DPS sheet.

**Comment by Theundyingcode** [comment]
I would lean more towards reducing the cut than the bash if you're going to nerd it. Axes in general aren't particularly sharp and they don't cut in the traditional sense. Instead they focus blunt trauma into a small area. Chopping down a tree or dooris not like cutting it down, you're essentially just bashing it repeatedly while the axe's "blade"focuses your force enough to overcome the wood's hardness.  It's why a golf club is so much more damaging than a baseball bat IRL. 

You can cut much farther into a tree with a katana than an axe however, you'd never be able to split logs with one. The axe makes grain split with a sudden massive shock no different than a Zed's face being smashed in by a sledgehammer.

If it's got a much higher cut than other axes, bringing it inline with them would probably be the best approach IMHO.

**Comment by AncientSion** [comment]
Sounds reasonable. What Cut / Bash would be your sugggestion, @Theundyingcode ?

**Comment by kevingranade** [comment]
Basically, you can't balance items in isolation, finding the right damage for the fire axe requires an outline of how balance works for melee weapons in general, or alternately a rationale for determinining stats based on the properties of the item.

There has been a lot of discussion about both of these approaches, so if an existing system appeals to you, you can base your rationale on one of them and just outline how that system leads to your conclusion, but simply stating that the stats for a weapon "make no sense" doesn't give us anything to go on.

**Comment by Theundyingcode** [comment]
> Sounds reasonable. What Cut / Bash would be your sugggestion, @Theundyingcode ?

While I used to hold a big interest in old weapons, axes were never really my thing and I don't feel inclined to do research on this as my last character used a fire axe. That said, to my understanding:

- General purposes axes (wood axe) are designed to be rugged and durable.  Their owners want to be able to use them for decades with little to no maintenance. They are pretty unsuited for combat though as the axe head is relatively small (6-10in or so) compared to the shaft and they rely on large powerful swings to drive the weight of their head into something.

- Fire Axes trade some of this durability for a sharper edge and better preference.  After all, they are made for "emergency use." So basically think of them as a leveled up wood axe.  They will probably have a slightly larger, slightly curved blade and a pick on the other side. (possible auxiliary piercing attack?).  Usually painted in bright colors (no hiding) and still pretty unwieldy for actual combat. (probably not as much though)

- Combat oriented axes focus more on wield-ability. Their edge is going to have a similar sharpness but more gradual taper (not as fat).  The edge will be longer to increase the "damage doing" making hitting easier and less likely to get stuck in something.  Their blades will have a greater curve to avoid spreading out their force thereby improving cutting.  They're actually more like armour piercing swords than axes as you normally think of them.  They are going to require orders of magnitude more maintenance than fire or wood axes.  They will create large gashes in opponents opposed to the other's smaller area of deep heavy trauma; potentially doing more dmg but requiring significantly more force to overcome armour.

Soooo.... for similarly sized axes, a fire axe should have:

Cutting significantly greater than a wood axe and somewhat below a combat axe.
Bashing significantly higher than a combat axe and about the same as a wood axe.
To-Hit slightly higher than a wood axe and massively below a combat axe. (moves to attack as well but that's hard to change... new flag?)
less durability than a wood axe but still above most weapons and in another league from combat axes.

**Comment by Coolthulhu** [comment]
> To-Hit slightly higher than a wood axe and massively below a combat axe.

It's only doable with current to-hit comparisons if by "slightly" you mean "not at all" and by "massively" you mean "one point difference".
"Wieldability" is better represented by faster attack speed, as battle axes were relatively light compared to axes designed to split hard materials.

**Comment by Theundyingcode** [comment]
> It's only doable with current to-hit comparisons if by "slightly" you mean "not at all" and by "massively" you mean "one point difference".

Hence my rather length detailing of properties rather than guessing actual stats. Still, wood and fire axe's blades are going generally be <1ft long while a combat axe's is going to be more like 2-3.  Accurately hitting something moving with a small blade at the end of a stick your swinging with all your might is not trivial.

> "Wieldability" is better represented by faster attack speed, as battle axes were relatively light compared to axes designed to split hard materials.

I don't know anything about weights but I expect they'd be the same-ish but yes, fire axes should be slightly faster than wood axes and much slower than combat ones.

**Comment by aeoo** [comment]
>Fire Axes trade some of this durability for a sharper edge and better preference. After all, they are made for "emergency use."

Maybe I am confused, but I always thought "a fire axe" is the other part of "the irons" next to a Halligan Bar.  Halligan Bar is mated to an axe, and if you watch videos of those axes, they're stupid durable, as in, nigh indestructible, and huge, and look like they would do insane damage too in terms of realism.

I don't have any idea with regard to actual numbers but in conceptual terms what balances the fire axe as I have conceived of it before (as a mate to a Halligan Bar in the irons), is that it's heavy, hard to swing without getting tired (unless well trained), maybe hard to make a precise strike with it, and it looks like it might occasionally get stuck in a Zed and be hard to pull out.  Another thing is, maybe they are easier to disarm than something like a katana.

But basically those giant indestructible entry axes are insane.  They're not tiny emergency axes that are "stapled" to walls for use in emergencies.  At least not as I have always thought of them in-game.

**Comment by Theundyingcode** [comment]
@aapo- your correct about the fire axe and the Halligan Bar make up "the irons."  And yes, they are extremely durable.  I did not mean to imply that they aren't  however, compared to the ridiculousness that is a modern large general purpose axe, their cost of production and maintenance requirements are much greater mainly doe to having a sharper edge.  Compared to a katana and the like, they are basically maintenance free. 

The trouble with fire axes and the like is you really can't do any damage without performing a "heavy" attack.  IRL, with fists, you have the option of doing a quick jab or a windup punch.  Likewise, with a short spear, you can make quick pokes, powerful thrusts, wack them with a quick swing or throwing all of your weight into an overhead smash.  However, with a fire axe, your options are swing it hard or swing it very hard; anything else and you might as well just be hitting them with your water bottle. 

To this end, I propose the idea of a [HEAVY_MELEE] flag being added to fire/wood axes, sledgehammers and the like.  Things with this flag would use a different calculation giving them a slower attacks than their size/weight would normally dictate.  To make up for the nerf, they would receive more bonus from a characters strength.

**Comment by kevingranade** [comment]
No rationale provided for the change, closing.

**Comment by AapO-** [comment]
Greetings,

I think i have been involved in some git hub game development discussion :P
i don't know any of this really i think you might have the wrong guy :o
though i am a developer you need some help on something ?

Best regards,

AapO-

2017-10-04 21:10 GMT+02:00 Kevin Granade <notifications@github.com>:

**Comment by kevingranade** [comment]
@Theundyingcode It looks like you may have accidentally pinged the wrong account, possibly via autocorrect?
@AapO- looks like it was a typo, sorry to bother you.
If someone wants to follow up on this issue, please open a new issue, I'm locking this thread to avoid spamming @AapO-
