### ISSUE TITLE
Allow ammo types in grenade recipe

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#21980]
Currently the grenade recipe requires (among other things) either 100 BBs or 30 nails. I would like be able to use any item classified as a BB (i.e. metal fragments) or nail (i.e flechettes) to craft grenades. 

I believe this would be an easy fix but I'm not sure if it would break the game balance.

**Comment by Coolthulhu** [comment]
Scrap is too easy to get, pretty much free. Flechettes are nails+1, so fine here.

**Comment by kevingranade** [comment]
Don't worry about balance here, it's the explosives that should be the
limiting factor, not the shrapnel.

**Comment by angoddu** [comment]
So I can't figure out how to add an ammo type to a recipe. I tried adding in the ammo type's id but it errors out. Since metal fragments are a mod item, I can't hard code them into the recipe. Am I missing something in the recipe syntax or is this actually not possible?

**Comment by BevapDin** [comment]
>  is this actually not possible?
Yes.

**Comment by Zireael07** [comment]
Yes, possible or yes, not possible?

**Comment by CoroNaut** [comment]
Nothing is not possible in coding. There are always ways around the problem. (Just some friendly encouragement :D)

**Comment by angoddu** [comment]
That's disappointing. I'm going to then just allow flechettes in the recipe with half the count. Flechettes are 3 times as powerful as nails so half the count seems like a good trade off to me.

> Nothing is not possible in coding

Truer words were never told but I believe that would require modification to the JSON parsing and I don't even know where to start looking for that.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
