### ISSUE TITLE
Dexterity is strictly better than perception in ranged weapon use

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#21998]
Added in #21468

Dexterity is more important for sniping due to its reliability, but also more important for quick shots due to the fact that it affects dispersion directly rather than only affecting minimum achievable recoil.
Dexterity is more reliable because it has a separate roll on its own, while perception shares its roll with sight and eye encumbrance, like this:
```
dispersion = rng(dex_penalty) + rng(per_penalty + eye_penalty + sight_penalty) + other rolls
```

This means that dexterity affects the median noticeably more than perception, meaning it is more useful for sniping.

**Comment by kevingranade** [comment]
Having stats be roughly similar in utility is a valid goal, but we have no principle that states they must have some particular relationship within a given feature.
