### ISSUE TITLE
UI modal for saving character template doesn't disappear

### ISSUE THREAD

**Issue by rm-code** [CleverRaven/Cataclysm-DDA#21990]
Game version:
0.C-24101-g601990f (tiles) (build 6803)

Operating system:
Windows 10

Mods active:
Only default mods.

### Expected behavior
The modal should be closed (with a note that the template was saved correctly).

### Actual behavior
The modal stays on the screen / isn't cleared correctly. ~~Not sure if the template saving did work, will update once I can check.~~ Update: Template was created normally,

![1](https://user-images.githubusercontent.com/11627131/30829728-ea04caf6-a241-11e7-9bae-11a6d82bd7e5.PNG)

Here you can see parts of the modal are still on the screen:
![2](https://user-images.githubusercontent.com/11627131/30829732-eb7abe5e-a241-11e7-8ee2-9efc7c3c9f43.PNG)

### Steps to reproduce the behavior
1. Create a new character
2. Try to save it as a template

**Comment by Night-Pryanik** [comment]
Strange split of the string here too...
