### ISSUE TITLE
Game error crash when try to throwing

### ISSUE THREAD

**Issue by NEONZARIN** [CleverRaven/Cataclysm-DDA#22001]
Game version:
#6806 (27.09.2017 8:27:10)
Operating system:
Windows 7 x64
Tiles or curses:
Tiles
Mods active:
[
  "dda",
  "Cata++",
  "Experimental-Z-Level",
  "FIC_Weapons",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "PK_REBALANCE",
  "PK_No_Doom",
  "RL_Classes",
  "blazemod",
  "Tanks",
  "Urban_Development",
  "boats",
  "craftgp",
  "brightnights",
  "crazy_cataclysm",
  "deoxymod",
  "ew_pack",
  "filthy_morale",
  "makeshift",
  "more_classes_scenarios",
  "more_locations",
  "national_guard_camp",
  "necromancy",
  "noctpk",
  "nw_pack",
  "realguns"
]

![default](https://user-images.githubusercontent.com/16442992/30898821-e45ebbf0-a365-11e7-98ad-2b669a0f9053.PNG)
![15064903575690](https://user-images.githubusercontent.com/16442992/30898841-fcdc6f74-a365-11e7-96fc-726548b226a8.jpg)
My screenshot and other man with a similar error. When you try to throw any object.

**Comment by sick-trigger** [comment]
yep getting this as well, default settings on curses. Crash occurs immediately after selecting an object to throw

**Comment by Firestorm01X2** [comment]
Next thing player shold see in this case is targeting screen. So it is likely related to: https://github.com/CleverRaven/Cataclysm-DDA/pull/21468

**Comment by Firestorm01X2** [comment]
**DanmakuDan** found soource of problem. Look for https://github.com/CleverRaven/Cataclysm-DDA/pull/21468#issuecomment-332545956
