### ISSUE TITLE
Last batch of clean water from toilets disappears.

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#22019]
Windows tiles, latest experimental

If you drink from a toilet 4 times, and then batch craft all 20 remaining units of toilet water, then put it in a container, it will seem like you have succeeded, but the water will never show up in the container.

If you drink from a toilet 3 times, and then batch craft 20 units, this does not happen.

This, and other testing, shows the last batch of clean water crafted from toilet water never actually appears in your inventory.

Thanks for pointing this out, Kanoot on Discord.

**Comment by AdonaiJr** [comment]
Idk if its related but a couple of days ago I had a sealed stomach that would only hold 1 unit of water.

I'll try to do more tests and report it back.

**Comment by Treah** [comment]
AdonaiJr 
Stomachs expand in  your inventory when you add stuff to them. You probably only had space for one unit of water in your main inventory.

**Comment by AdonaiJr** [comment]
Treah, oh, you are probably right! I know that stomachs work like that (expanding volume) but never ocurred to me that it could do this as a side effect of limiting inventory space.

Sorry for reporting a know issue.

**Comment by DanmakuDan** [comment]
I found a bug where finishing the water supply from the toilet will prevent the water amount from being reported correctly to the crafting action, causing a silent failure at the end of the craft action.
