### ISSUE TITLE
Basements are spawning without connecting stairs when stair-alignment is enabled

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#22010]
Game version: 6806

Operating system: Windows

Tiles or curses: Tiles

Mods active: Non

### Expected behavior
Stairs that lead down take you to the underground stairs and vice versa

### Actual behavior
Basements cannot be accessed without digging, in spite of an upstairs tile. Players are teleported upstairs through the roof if they try to ascend the stairs from the basement.

### Steps to reproduce the behavior
Reach a basement type building when stair-alignment world option is enabled, there is an absence of stairs that lead down and you have to find another way down. When going up, you just teleport through the roof.

**Comment by Coolthulhu** [comment]
Need examples of mods

**Comment by zakhad** [comment]
might be a long shot but is this related? 
![bug](https://user-images.githubusercontent.com/5264667/30951197-847b42a8-a419-11e7-9fae-b6765db2af64.jpg)

That uses parks and rec buildings pack

I wrote about this in discord a quote from myself 

"I updated from 6781 to 6782, I'm not sure if this old mod is a lost cause, been using it for a while, is trying to use this old mod a lost cause? or is it something i can retrofix by editing an XML."


That is when I suspected the change happened that might cause this, the screenshot does mention basements/modded, i'm no expert, anyways maybe it'll help maybe it wont :S

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed.
