### ISSUE TITLE
Landmines feature torso homing shrapnel

### ISSUE THREAD

**Issue by Alkheemist** [CleverRaven/Cataclysm-DDA#22025]
**Game version:** 0.C-23730-g4b6197d

**Operating system:** Windows

**Tiles or curses:** Tiles

**Mods active:** DDA, Filthy Clothing, Disable NPC Needs, Simplified Nutrition

### Expected behavior
Landmines detonating will damage all parts of the body roughly equally, proportional to distance. Damage from landmine explosions appear on the message log.

### Actual behavior
Being anywhere within the blast radius of a detonating landmine results in immediately dying from torso damage. Damage to other parts of the body is rare, and no messages are created.

### Steps to reproduce the behavior
Place a landmine. While standing about 3 or 4 tiles away from the landmine, lure zombie onto the landmine. (sometimes) die horribly with no clear indication.

My guess is that landmines have shrapnel which is VERY effective, and does more damage than regular survivors have health. If this is the case then the message log should probably indicate that you were hit by shrapnel. As it stands, a landmine will detonate nearby and then you get the "watch the last moments of your life?" prompt. The damage doesn't appear on the message log and you simply see that all your torso health is gone.

![nolog](https://user-images.githubusercontent.com/7487313/31012105-f186d3a4-a553-11e7-86be-663d016b08a6.PNG)
This is the message log of a test character. This particular one survived 5 landmines before dying, indicating that this is most likely shrapnel. But without any messages, I'm not sure if something else is afoot.

**Comment by Alkheemist** [comment]
![nolog2](https://user-images.githubusercontent.com/7487313/31012489-5b6e25aa-a555-11e7-83a7-7556ed0919c2.PNG)
Another image of the message log for a different character. I think this is actually a shrapnel related message log bug, since further testing resulted in a character which did get a damage message, although on a limb. Perhaps if a fatal shrapnel blow is dealt it never appears on the log?

**Comment by greenman74** [comment]
I have noticed the same issue, as of version cataclysmdda-0.C-6981.  I was had full HP, with the tough trait with 20% extra hit points and my armor in full repair.  I wore a bone suit, bone helmet, bone gloves, and bone boots.  I also wore a O-yoroi suit on top of that.  I think some enemy triggered a land mine, and I was killed in one turn from the explosion.
![landmines](https://user-images.githubusercontent.com/34298677/33649793-1dbc968a-da14-11e7-9c37-9d7c45a0b97f.JPG)

**Comment by greenman74** [comment]
Using the debug menu, and walking into unseen buried land mines a few times, it seems clear that the message log with the display of torso damage is off.  With a fresh character, using the map editor to walk into land mines, this full HP character took 33 torso damage, yet his torso is almost gone.  Other body parts (except for his left arm) have taken worse damage, yet they remain completely intact.
![debug](https://user-images.githubusercontent.com/34298677/33668330-4c4247d0-da54-11e7-9f01-10ce85772559.JPG)

**Comment by kevingranade** [comment]
Due to phrasing in the messages, we can tell where the damage came from.
"Your <bodypart> was hit" is from the blast.
"You were hit in the <bodypart>" is from bomb fragments.

It does look like death from bomb fragments isn't being reported, but I don't have any guesses why it's happening from reading the code.

I'm actually in the middle of overhauling this code, replacing the random samples of fragment paths with a more field-like system where roughly everything in range is hit unless something (i.e. a wall) blocks the path.  I'll be dropping the damage some too, but expect fragmentation bombs to continue to be quite deadly at close range.

**Comment by Alkheemist** [comment]
For path blocking, will you include vehicles? The first time I encountered this bug my character was killed by shrapnel while wearing heavy survivor armour and driving a tank. I feel like shrapnel should not be able to penetrate tank armour, let alone defeat some of the most effective armour in the game outright from it's maximum range.

**Comment by kevingranade** [comment]
Theres an issue with vehicle interactions that might be problematic to deal
with.  I'll see what I can do.

Basically we don't represent the difference between the ground and the
floor of a vehicle in any significant way, so as far as the code is
concerned, when you drive over a mine, it explodes inside the vehicle with
you.

I might be able to sort something out, but I'm not certain of it.

**Comment by kevingranade** [comment]
This was fixed by #24171, individual bomb fragments deal less damage, they chose body parts to target at random, and the damage from fragments is reported.
