### ISSUE TITLE
6815 cataclysm-tiles.exe crashes when executed

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#22026]
Game version tested: 6820, 6815 and 6799 
Operating system: Windows 8.1 x64
Tiles or curses: Tiles and curses, x64 and x86

### Expected behavior
The game starts normally.

### Actual behavior
Microsoft Visual C++ Runtime Library
Runtime Error!
This application has requested the Runtime to terminate it in an unusual way.
```
Version=1
EventType=APPCRASH
EventTime=131511750870887863
ReportType=2
Consent=1
ReportIdentifier=d819811d-a530-11e7-832e-00248c414a93
IntegratorReportIdentifier=d819811c-a530-11e7-832e-00248c414a93
NsAppName=cataclysm-tiles.exe
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=cataclysm-tiles.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=afe0afd8
Sig[3].Name=Fault Module Name
Sig[3].Value=cataclysm-tiles.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=afe0afd8
Sig[6].Name=Exception Code
Sig[6].Value=40000015
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000b0bada
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.3.9600.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=e751
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=e75190eaea645f978bbbf35f1c0aed3a
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=7670
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=7670b85237294a18e53c3c95adf01d26
UI[2]=E:\Cataclysm\cataclysm-tiles.exe
UI[3]=cataclysm-tiles.exe has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=E:\Cataclysm\cataclysm-tiles.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[5]=C:\Windows\system32\GDI32.dll
LoadedModule[6]=C:\Windows\system32\IMM32.dll
LoadedModule[7]=C:\Windows\system32\msvcrt.dll
LoadedModule[8]=C:\Windows\system32\ole32.dll
LoadedModule[9]=C:\Windows\system32\OLEAUT32.dll
LoadedModule[10]=C:\Windows\system32\SHELL32.dll
LoadedModule[11]=C:\Windows\system32\USER32.dll
LoadedModule[12]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[13]=C:\Windows\SYSTEM32\WINMM.dll
LoadedModule[14]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[15]=C:\Windows\system32\RPCRT4.dll
LoadedModule[16]=C:\Windows\system32\MSCTF.dll
LoadedModule[17]=C:\Windows\SYSTEM32\combase.dll
LoadedModule[18]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[19]=C:\Windows\SYSTEM32\WINMMBASE.dll
LoadedModule[20]=C:\Windows\system32\SspiCli.dll
LoadedModule[21]=C:\Windows\SYSTEM32\cfgmgr32.dll
LoadedModule[22]=C:\Windows\SYSTEM32\DEVOBJ.dll
LoadedModule[23]=C:\Windows\system32\uxtheme.dll
LoadedModule[24]=C:\Windows\system32\dwmapi.dll
LoadedModule[25]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[26]=C:\Windows\SYSTEM32\CRYPTBASE.dll
LoadedModule[27]=C:\Windows\SYSTEM32\bcryptPrimitives.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=cataclysm-tiles.exe
AppPath=E:\Cataclysm\cataclysm-tiles.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=1AB0A8D74BC87715B29E9A73E6741DF7
```

**Comment by Zireael07** [comment]
Your hardware specs?

**Comment by kevingranade** [comment]
Unfortunately there's no usable information in that message, so we're very unlikely to be able to find the problem you encountered.  Does this happen every game start or intermittently?

**Comment by Tharn** [comment]
It's an install that I've kept up to date with CDDA Launcher. These last two updates I made (6799, 6815) produced a crash immediately upon starting the game, and this happens everytime. No intermediate crashes. Before this, the game had been running fine through dozens of older dev version updates. No software changes on my end as far as I'm aware.

Asus P5Q Pro
Core2Quad Q9550
4x2GB RAM
R9 270X

**Comment by Tharn** [comment]
The plot thickens: Same exact thing happens on my Thinkpad X200.

**Comment by DanmakuDan** [comment]
If you have the same installation setup on both machines, have you tried moving the config folder out of the game installation and letting it set up new config files?

**Comment by Tharn** [comment]
I have actually downloaded the various experimental builds from the Cataclysm homepage to verify this. It's not my setup or any of my changed settings.

**Comment by DanmakuDan** [comment]
Do you know if debug.log in the config folder contains any information?

Otherwise, you could try downloading this options file and extracting it to your tiles version config folder
[options.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1346603/options.zip). It will try setting rendering mode to software and use a smaller default tileset.

**Comment by Tharn** [comment]
The debug.log is empty unfortunately. Using the options.json you supplied doesn't change anything.
It also throws up the runtime error *immediately* after clicking the executable, even on my slowest harddrive. It can't be running a lot of code. Compiler issue with instruction sets or something similar?

**Comment by DanmakuDan** [comment]
I have a download of x64 Windows Tiles at http://danmakudan.com/cataclysmdda-0.C-6764.zip, but otherwise old releases would have to be provided by users that kept the old ones. I don't have a setup like Narcotiq's MXE compiler that generates the builds that you can download. 

There are crashes from SDL2 for users with processors that don't have SSE/SSE2 when SDL moved to version 2.02, but I think we are currently on 2.03 or 04 for a while now. Checking your CPU with Google shows that it should have up to SSE4.1.

**Comment by Tharn** [comment]
The 6764 build loads fine, with ChestHole and everything. Some change between 6764 and 6799 broke the game for me.

Thanks for the zip!

**Comment by DanmakuDan** [comment]
Another idea, do you have any antivirus programs that do "new" app scanning, like avast? In earlier cases, it would see that the latest experimental would have a different checksum/signature than the ones it has seen earlier, and submit it for evaluation, while blocking the execution and leaving a small nonworking process behind.

**Comment by nekoworkshop** [comment]
I'm experiencing a similar problem after I have updated to the latest nightly build. Same error message. No debug.log output.

Versions I have tried: 6817,6816 and 6808

Interestingly, I found this string popped up in the register when I'm tracing back to find the cause of the crash in a debugger:

> locale::facet::_S_create_c_locale name not valid

Looking furthur *back* I found this:

![image](https://user-images.githubusercontent.com/1346257/31057102-0a604024-a6ab-11e7-8d7e-3dc77f589bf8.png)

My system locale is indeed `ja-JP`, as reported by Windows. So I'm assuming this is something related to locale?

@Tharn what's your system locale?

**Comment by nekoworkshop** [comment]
I tried to launch the game in English locale with AppLocale, it worked. The funny thing is since that I can run the game in my original environment (ja-JP) without any problem.

In other words, the problem disappeared after I have run the game in English locale for once. I don't know how that happened but at least I can play it now :P

**Comment by Tharn** [comment]
I run a pretty minimal system with no antivirus. My locale is en-us for display language, german for keyboard and the various number formats.

**Comment by DanmakuDan** [comment]
I am guessing that means the number format choice is related to the crashing. This issue #20927 led to this PR #21927 (10 days ago), which could be pretty close to the time the builds stopped working for you. The options file that would get generated at first startup could be having issues with the different decimal format.

**Comment by Tharn** [comment]
I changed all locale settings to en-us and it's still crashing for me, unfortunately. Tested this with a fresh install of build 6820. It didn't even get to generating a /config folder.

**Comment by DanmakuDan** [comment]
Do you have a list of what locale settings you have different from the US defaults? I would like to try reproducing the crash on my side.

**Comment by Tharn** [comment]
I'm not convinced it is a locale issue, as I tried that already. By default it's en-us for display language. Keyboard layout, date/time/numbers in german. Setting everything to en-us (and to automatic where it was previously on override), restarting and then running a fresh install off the Cataclysm website produced the same crash.

**Comment by DanmakuDan** [comment]
In that case, we could try checking individual release files that I can try rebuilding, but we would have to check that they can work on your computer. Can you download http://danmakudan.com/Cataclysm-Tiles_6764.zip and see if you can replace the .exe file in a fresh install of the latest release and see if that starts up?

**Comment by Tharn** [comment]
Tried it just now. It crashes.

**Comment by DanmakuDan** [comment]
Can you add these SDL dll files http://danmakudan.com/binfiles.zip and see if it doesn't crash with them?

**Comment by Tharn** [comment]
Crashes, too. Using build 6764 with the .exe from 6815 produces a slightly different offset value than in the OP. This goes for both using the .dlls and without. Exception Offset: 0000000000b0e77a

**Comment by DanmakuDan** [comment]
I'm working on the build configuration so that it doesn't require DLLs, this may take a while.

**Comment by DanmakuDan** [comment]
I was actually able to build a zip using the Makefile, so you can try http://danmakudan.com/cataclysmdda-0.C_6764_dan.zip and http://danmakudan.com/cataclysmdda-0.C_6820_dan.zip and confirm if one or both crashes.

**Comment by Tharn** [comment]
Your 6764 build loads fine and only hangs when quitting (probably unrelated). Your 6820 build crashes when executed.

**Comment by DanmakuDan** [comment]
Some more builds I uploaded:
http://danmakudan.com/cataclysmdda-0.C_6770_dan.zip
http://danmakudan.com/cataclysmdda-0.C_6780_dan.zip
http://danmakudan.com/cataclysmdda-0.C_6790_dan.zip
http://danmakudan.com/cataclysmdda-0.C_6799_dan.zip

**Comment by Tharn** [comment]
6770 & 6780: Works
6790 & 6799: Crashes

**Comment by DanmakuDan** [comment]
Narrowing it down more:
http://danmakudan.com/cataclysmdda-0.C_6782_dan.zip
http://danmakudan.com/cataclysmdda-0.C_6784_dan.zip
http://danmakudan.com/cataclysmdda-0.C_6786_dan.zip
http://danmakudan.com/cataclysmdda-0.C_6788_dan.zip

**Comment by Tharn** [comment]
They all work! That leaves 6789 and 6790 as the culprit.

**Comment by DanmakuDan** [comment]
http://danmakudan.com/cataclysmdda-0.C_6789_dan.zip

I am guessing 6790 contains the issue, since it does change some logic at startup.

**Comment by Tharn** [comment]
You're right, 6789 loads fine as well.
Really appreciate your help with this one.

**Comment by DanmakuDan** [comment]
Here is a modified version of the latest (6826) build to try:
http://danmakudan.com/cataclysmdda-0.C_6826_dan.zip

**Comment by Tharn** [comment]
This one works!
