### ISSUE TITLE
NPC embedding into monster's corpse

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#22036]
Game version: 0.C-6812

Operating system: Windows XP SP3 x86

Tiles or curses: tiles

Mods active: default only

### Expected behavior
Non-container should not be able to hold something.
### Actual behavior
Zombie corpse (and previously "live" zombie) is able to "hold" NPC. 
### Steps to reproduce the behavior
![default](https://user-images.githubusercontent.com/11132525/31044567-7b3b252e-a5da-11e7-8620-eebe846cebbf.png)
I doubt this is reproducible, and unfortunately I didn't track how it happened (I was in the middle of life-or-death battle), but I can suggest it has something to do with poor Sean being zombie through the first quest of refugee center.

**Comment by Coolthulhu** [comment]
It's not embedding, the zombie just has a name. This happens in evac center mission 1 where you have to eliminate a specific zed.

**Comment by Night-Pryanik** [comment]
Oh, so that's intended? Ok, closing.
