### ISSUE TITLE
Homemade Suppressor's DISABLE_SIGHTS flag not conveyed to players

### ISSUE THREAD

**Issue by TheFreckle** [CleverRaven/Cataclysm-DDA#22031]
Game Version: 6815

Build: 0.C-24910-ga866f7a

Operating system: Windows

Tiles or curses: Tiles

Mods active: none

### Expected behavior
the Homemade Suppressor should:
Increase dispersion by +15
Increase handling by +1
Decrease damage by -5
Reduce sound signature of the weapon
### Actual behavior
causes significant drop in hit chance, cannot steady weapon.
### Steps to reproduce the behavior
1: get any firearm that can accept a muzzle mod
2: check aim without homemade suppressor attached
3: attach homemade suppressor
4: check new aim of firearm

The following images are from a debug character with a 10 in every skill and a stat spread of 10 strength, 10 dexterity, 12 intelligence, 10 perception

AR-15 weapon information with no mods attached
![debug_ar15-nomod](https://user-images.githubusercontent.com/31813872/31043343-cf468f4e-a56e-11e7-887b-bf59fcf6c978.png)

AR-15 weapon aim at regular aim delay against a target 3 tiles away with no mods attached
![debug_ar15_aim-nomod](https://user-images.githubusercontent.com/31813872/31043345-d66ee406-a56e-11e7-9674-b5946f81b368.png)

AR-15 weapon information with homemade suppressor attached
![debug_ar15-homemadesuppressor](https://user-images.githubusercontent.com/31813872/31043353-e0cbe70a-a56e-11e7-9a33-90125b861f46.png)

AR-15 weapon aim at regular aim delay against a target 3 tiles away with homemade suppressor attached
![debug_ar15_aim-homemadesuppresor](https://user-images.githubusercontent.com/31813872/31043356-e4ea3ad0-a56e-11e7-91e0-0483ffd2f75f.png)

I originally discovered this bug on a character in a modded world on a H&K MP5. I assume this bug applies for all firearms with a homemade suppressor attached. The regular suppressor does not have this issue, its calculations are normal.

**Comment by cainiaowu** [comment]
that 3000 sight dispersion looks weird.

**Comment by TheFreckle** [comment]
I started to look into the issue, this is where the 3000 sight dispersion is coming from:

https://github.com/CleverRaven/Cataclysm-DDA/blob/44963bc2bad26132b91d299350c4a1986a9f2a73/src/item.cpp#L3995

**Comment by cainiaowu** [comment]
So I guess it is working as intended? 
Giant handcrafted suppressor blocks off your sight so you cant see your target. 
You can attach some sight mod to see if it gets better.

**Comment by TheFreckle** [comment]
For all intents and purposes it does seem that the homemade suppressor is working as intended. If you install any sight mod to the weapon you can aim with the weapon again. I just find it odd that you cannot steady the weapon without sights.

**Comment by Leland** [comment]
Changed the issue title to reflect the situation.

>find it odd that you cannot steady the weapon without sights

Might be intentional; could be worth opening a new issue for it. @kevingranade thoughts

**Comment by kevingranade** [comment]
It's partially intentional in that it obscures the sights, but it shouldn't drop aiming all the way to 0.
