### ISSUE TITLE
Elbow Pads vs Metal Arm Guards - Elbow Pads imbalanced - zero ENC

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#22034]
https://i.imgur.com/aM5PDWm.png

Basicly, both are for the Arms and both are strapped. 
Metal Guards have far more coverage, however, both ENC and PROT seems off for the Elbow Pads. 

Having 0 ENC is probably an oversight, but even the PROT of 8 seems to high for Plastik, if Metal is supposed to offer 12.

Assuming Metal Arm Guards are fairly balanced (which if feel they are) i suggest Elbow Pads to have

ENC from 0 to (4-6)
PROT from 8 to (6 at best)

**Comment by Coolthulhu** [comment]
Elbow pads have coverage of 30%, they're certainly not worth more than 3 points of encumbrance.

**Comment by AncientSion** [comment]
I feel 3 is too low, hence im suggesting 4 to 6. However, we can agree that 0 ENC is too low, so i would be with 3.

**Comment by Nhatorama** [comment]
I think the elbow pads are fine as is.
Being protected by the elbow pads 30% of the time or being directly hit 70% of the time seems fine for 0 encumbrance.

On the other hand I do think the encumbrance values for arm armor should be toned down or be allowed to be fitted.
I usually deck out my NPCs with suits of plate armor (outer) and plated leather armor (normal).
Plated leather armor requires leather body armor and a pair of leather arm guards. The encumbrance of a suit of plated leather armor (fits) is 14, but the encumbrance of a pair of leather arm guards is 16.

**Comment by kevingranade** [comment]
There's no rationale here other than opinion, if you want to fine-tune balance you're going to need to provide a convincing argument for why it needs to be adjusting, ideally based on the properties of the item itself, not based on some other item.
From a balance point of view there's no argument to be made, 30% coverage is basically worthless, no matter how high the armor value is.
