### ISSUE TITLE
Expand Crafting Menu search to search by skill LEVEL

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#22053]
I regulary use the crafting menu search to search for Items by skill type.
I then want only the "highest" items of that level in order to grind my skills. The result list is ordered by item req level, but its again divided by "craftable" and not "craftable", messing up data for me.

I would like to be able to refine the search skill, adding level on top.

Like this

![image](https://user-images.githubusercontent.com/4209179/31057889-7e27035a-a6ea-11e7-8207-fe209371aa05.png)

Result: Show ONLY items with prerequisite Survival == 3

Also i think it would make a ton of sense to limit the search based on results of items with primary skill.
Currently i would search by "Survival" and items with "Survival" as the supplemental skill show up, which doesnt help at all.

**Comment by Shoes01** [comment]
There used to be functionality for filtering via primary skill, but that was removed it seems. I can't seem to locate exactly when it happened, but @mugling did a lot of working improving the crafting GUI and stuff; maybe it was cut for a reason, or maybe it got lost in the shuffle.

Searching for a specific skill number would require new code and an explanation to the user of how to use it. Something like "s:survival=3" might be the best way to do it: just like the colon is used to denote a prefix, the equal could denote a suffix.

**Comment by AMurkin** [comment]
Search happens [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/92a1d9e52d1815504d6100a67bf332dba8457cfd/src/recipe_dictionary.cpp#L84).

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
