### ISSUE TITLE
Vehicle components turn selves off 

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#22077]
Game version: Current experimental

Operating system: Windows

Tiles or curses: Tiles

Mods active:  Tanks + other vehicles

### Expected behavior

When I turn things on it should stay on and run so long as there is power.  Preferably should automatically restart as soon as power becomes available,

### Actual behavior

The fridge and electronic control's dome light in my vehicle keep turning off without me knowing.  The vehicle has solar panels, 2 engines that I haven't been running and a full set of crafting rigs.

### Steps to reproduce the behavior

Build a solar powered death mobile and put a fridge, electronic controls and other stuff in it, turn them on and hang out and craft stuff for a while and find the fridge is turned off and stuff is spoiling.

**Comment by Zireael07** [comment]
Maybe the solars aren't enough to power the stuff? How big is your battery?

**Comment by Coolthulhu** [comment]
Pretty sure fridges are only powered when in the bubble. Outside bubble, they are still turned on, but consume no power.

**Comment by Theundyingcode** [comment]
> Maybe the solars aren't enough to power the stuff? How big is your battery?

It's a still in construction vehicle so i'm defiantly running it on low power but my fridge still turned itself off sometime while I was away foraging.

> Pretty sure fridges are only powered when in the bubble. Outside bubble, they are still turned on, but consume no power.

The vehicle has been sitting in front of my base for more than 2 in-game weeks now.  The only times I have left are for 2 parts stripping trips and 1 day of foraging. However, the dome light hasn't stayed on from one night to the next and I have turned on my fridge 8 times now. 

At I would like for at-least the fridge control to stay on until I turn it off.  Obviously, if there is no power it should stop running however, it should resume as soon as power is restored.  This is how it would work IRL.  Even if this behavior was realistic, finding your food spoiled because last week your welder/Tesla cannon drained your battery causing the fridge to turn off without your knowledge violates the rule of fun imho.

**Comment by Coolthulhu** [comment]
> At I would like for at-least the fridge control to stay on until I turn it off.

I'd allow it, provided someone invented a good UI for this. Something that wouldn't require cycling modes and would inform the player what is happening.

**Comment by Theundyingcode** [comment]
I haven't looked at vehicle implementations but, modeling its implementation off of light strips should work conceptually. 

Switch | Power | State
------- | ------ | --------------------
Off | Either | Fridge (off)
On | Yes | Fridge (on)
On | No | Fridge (unpowered)

Then wherever the code for the actual consumption of power is insert
`if (vehicle.has_power())`
`   fridge(unpowered) becomes fridge(on);`
`else if (fridge(on))`
`   fridge(on) becomes fridge(unpowered);`

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed.
