### ISSUE TITLE
Add page outlining how to interact with CI to contributing.md

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#22073]
I just realized we don't have an outline anywhere of how our CI builds work or how to interact with them.

Sketch out a sub-page of the site outlining the features of each and how to determine what went wrong on a failed build.

**Comment by Treah** [comment]
This would be welcome as I have had Travis fail on me before for seemingly no reason other then apt-get command.

**Comment by ZhilkinSerg** [comment]
Please explain Codecov too - it is now commenting json-only changes (#22075).

**Comment by kevingranade** [comment]
Yea I just added that and didn't realize it would spam every PR, I'll turn that off.

**Comment by kevingranade** [comment]
Tracked the setting down and applied it, well see if that does it.

**Comment by kevingranade** [comment]
Looks like we have no reports as of #22081

**Comment by kevingranade** [comment]
Tracked the setting down and applied it, well see if that does it.

**Comment by ZhilkinSerg** [comment]
Codecov reports changes in CPP files that were unchanged in PR in the report - see example in https://codecov.io/gh/CleverRaven/Cataclysm-DDA/pull/22080/changes

Does it compare source with some invalid base or what?

**Comment by kevingranade** [comment]
You're seeing test coverage changes because the tests have RNG in them.
