### ISSUE TITLE
NPC teaching hang

### ISSUE THREAD

**Issue by TTTime** [CleverRaven/Cataclysm-DDA#22079]
g7a11edc
Win 10
Curses

More Survival Tools | StatsThroughSkills | Vehicle Additions Pack | Tanks and Other Vehicles | Boats | Folding Parts pack | Filthy Clothing | Makeshift Items Mod | Disable NPC Needs | Simplified Nutrition | Mythological Replicas

NPC teaching causes hang. I've tried four different NPCs, one in the underground lab (at start) and other scattered NPCs. No obvious cause. Tested Melee, Marksmanship, Bartering.

**Comment by TTTime** [comment]
I think this is to do with PKR, or... I don't even know anymore. PKR disappeared from the mod list, modinfo has obsolete set to true. My world no longer loads, whether or not its set to false, and I can't gen a world using it. The most recent experimental also has it listed as obsolete now. Either way, the bug isn't reproducing without it.

**Comment by TTTime** [comment]
Alright, I reproduced it. It's something to do with abandoned lab starts I reckon. Just do abandoned lab and chat with the NPC, recruit them then get training.

**Comment by Treah** [comment]
#22167 Might be related.
