### ISSUE TITLE
Stop providing the windows "curses" builds

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#22087]
Windows pseudo-curses builds have very low performance and have their own problems that don't happen in tiles builds. They actually set some of the tiles flags, because they aren't actually curses builds.
Proper tiles builds have up to 10 times faster drawing than pseudo-curses, as they cache drawn surfaces. Pseudo-curses achieve the same effect with Windows string drawing functions, which are pretty unsuited to drawing one character at a time.

The code for them could remain for testing, as it is quite useful not to have to supply whole SDL just to compile the game in codeblocks, but those builds are low quality and should not be provided to end users who want to play the game rather than just testing things.

This only affects windows pseudo-curses builds. *nix ones are fine.

**Comment by AMurkin** [comment]
Note: but now only curses compiles.
Please see my comment in #21867.

**Comment by i2amroy** [comment]
>Note: but now only curses compiles.

Strange, I'm literally running a windows 64 SDL build for my development stuff right now (Seeing as how the curses has the problem displaying errors at the moment) and it's compiling just fine.

**Comment by Coolthulhu** [comment]
It's related to SOUND=1, I'll get on it after I finish this merge run. Either way, it's unrelated to the issue here.

**Comment by kevingranade** [comment]
> The code for them could remain for testing,

If you're not proposing we get rid of the code and build support, what are you proposing we get rid of?
My best guess is removing links to it from cataclysmdda.org and narc.ro, and perhaps make an announcement somewhere.

**Comment by CoroNaut** [comment]
Could you make a tileset that makes the game look like curses?

**Comment by Coolthulhu** [comment]
> If you're not proposing we get rid of the code and build support, what are you proposing we get rid of?

Ready builds for end users.
> My best guess is removing links to it from cataclysmdda.org and narc.ro, and perhaps make an announcement somewhere.

Yeah, something like this.

> Could you make a tileset that makes the game look like curses?

Already available. Turn off tileset in options and you get something that looks like ASCII build, but with faster rendering and option to turn on minimap. And sound support, if you want that.

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
