### ISSUE TITLE
food items not stacking correctly in item container after cooling down

### ISSUE THREAD

**Issue by lonelychaser** [CleverRaven/Cataclysm-DDA#22094]
Game version: 0.C-23389-gd993d6c

Operating system: Windows 10

Tiles or curses: Tiles

### Expected behavior
Same food items with different portions should either be in the same stack after adding up all of the portions, or in separate stacks after they are cooled down.
### Actual behavior
When player puts a hot food into a container that have the same food without (hot) status, they will stack together after the hot food has been cooled down but it will be "(2 or more) food (largest portion of food before adding them together)", and the weight and volume of the food stack will be multiples of the largest portion of food.

For example, if player puts a smoked meat (hot)(3) into a container with smoked meat (20) inside, after the meat has been cooled down, the stack of meat will be 2 smoked meat (20) instead of smoked meat (23) or smoked meat (20) and (3), .
### Steps to reproduce the behavior
- put a food item that can be heated inside a container
- get the same food item from other places and heat it
- put the heated food inside the same container and wait for it to cool down

I haven't tested if the fake volume increase will actually fill up the container but it is annoying when I can't see the exact portions of food I have inside a container.

**Comment by Coolthulhu** [comment]
Is it some weird source patch or lua script?
How do you put non-liquids inside a container?

**Comment by Night-Pryanik** [comment]
Maybe by "container" @lonelychaser meant some vehicle container, like a trunk?

**Comment by ituluwituluwzev** [comment]
It is an interface issue. It shows 2 stack, and the uppermost one is 23. The volume and weight are right.

**Comment by ZhilkinSerg** [comment]
> Is it some weird source patch or lua script?
> How do you put non-liquids inside a container?

I believe it is about vehicle cargo containers.

**Comment by chriseich21** [comment]
I haven't attempted to reproduce, but you can drop anything with D into adjacent tiles to store in a container, such as a display rack. Seems more likely it would be that

**Comment by Broken-Admin** [comment]
They have different spoil values most likely.

**Comment by jeremyshannon** [comment]
It's nothing to do with spoil values, it affects food without them. I've seen this bug too, and just managed to do it in my test world. It's tricky and seems to happen very intermittently with only 2 stacks. 3 stacks makes it happen reliably. Steps to reproduce:
Wish up an RV and 3 stacks of sausage. Drop 6 of the sausage in the trunk, 6 on the floor. 
Heat the other 6 up, drop it in the trunk, and wait an hour. The trunk now holds "sausage (6)" listed twice.
 Pick up the remaining pile of sausage, heat it, place it in the trunk and wait an hour. Now you have "2 sausages (6)" and "sausage (6)"
