### ISSUE TITLE
Debug message : warnings for type lmg_handle

### ISSUE THREAD

**Issue by deanec64** [CleverRaven/Cataclysm-DDA#22096]
Game version: 0.C-24340-g6a17b93

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: Dark days Ahead, Filthy clothing, Disable NPC Needs, Simplified Nutrition, Craftable Gun Pack, Extended Reaistic Guns, Generic Guns, Makeshift Items mod, More Survival Tools, Mythological Replicas, Cataclysm++, Mining mod, Tall Buildings, Urban Development, Boats, Folding Parts Pack, Necromancy, Prevent Zombie Revivication, StatsThroughSkills.

### Expected behavior:
startup, no errors.

### Actual behavior:
as shown

### Steps to reproduce the behavior:
its a startup problem

![debug](https://user-images.githubusercontent.com/9217008/31306126-57a20442-ab17-11e7-82c1-fa2d7970643d.png)

![map debug](https://user-images.githubusercontent.com/9217008/31306148-c6d230ee-ab17-11e7-8fe9-08eb2310765e.png)

**Comment by Night-Pryanik** [comment]
That's definitely a mods problem.

**Comment by deanec64** [comment]
howto find what mod's are causing it?

**Comment by Coolthulhu** [comment]
It's not a core mod problem for sure. Looks like cataclysm++ issue, since it seems to be the only non-core here.

**Comment by deanec64** [comment]
thanks for the help, will post in Forums then. :)
