### ISSUE TITLE
Unboard_Vehicle: vehicle not found

### ISSUE THREAD

**Issue by Bobondacob** [CleverRaven/Cataclysm-DDA#22122]
Game version: 0.C-24379-gd2eb25e (tiles)

Operating system: Windows 10 Professional

Tiles or curses: Chesthole 64

Mods active: All vehicle additions mods, though the vehicle in question is vanilla

### Expected behavior 
Vehicle doesn't disappear out of nowhere

### Actual behavior
Vehicle disappears out of nowhere

### Steps to reproduce the behavior
???

The vehicle attached is a stock armored bank truck, completely unmodified. I picked it up as an errands vehicle. I quicksaved, knowing my driving ability is shoddy at best, right before I crossed a bridge with two thread the needle vehicles blocking the way. I, as expected, crashed thru the barrier and drowned in my plate armor. 

I may or may not have save scummed after I drowned, and then when I loaded in, I got the error below. The vehicle and its considerable contents are gone. Any idea what's going on? 
![image](https://user-images.githubusercontent.com/19233143/31475873-3f1daa8a-aed1-11e7-946e-65c0b46cc6bc.png)

**Comment by kevingranade** [comment]
I'm guessing you just restored your player save file, which doesn't include
the vehicle.  If you're going to savescum you need to backup the world
folder.

**Comment by Treah** [comment]
What Kevin said is most likely right. I have done something similar to this and got some really weird / amusing results. I have never had a vehicle disappear like this. If someone can reproduce I would say its worth investigating further even if its a problem with the mod.

**Comment by Bobondacob** [comment]
I died, X'd out of the game, and then reloaded from the last save.

**Comment by CoroNaut** [comment]
Yes, you can only properly save scum by backing up the entire world save file, the ingame save only saves the player state, and the game world updates every tick regardless. So if you goto a lab, die, and try to savescum, your character will be wherever you last saved, while your car and your body will be at the lab. So this is not a bug. It is intended behavior for the game.

**Comment by kevingranade** [comment]
As expected, not a bug.
