### ISSUE TITLE
Tank drones possibly too weak to vehicles

### ISSUE THREAD

**Issue by Bobondacob** [CleverRaven/Cataclysm-DDA#22136]
Game version:#6850

Operating system: Win 10 Pro
![image](https://user-images.githubusercontent.com/19233143/31526316-0c2bec2c-af94-11e7-812f-3847ae6949e3.png)

### Expected behavior
Tank drones would react to vehicles and resist vehicular damage, because, you know, it's a super advanced multi ton tank.
### Actual behavior
Ramming a vehicle with even basic rams at a moderate to high speed kills the tank on contact, rendering one of the most challenging above land vehicles to a free gun platform. Perhaps a change is needed? Perhaps some TD rebalance? Maybe?? Still gonna use this one gun without remorse, tho.

(edit) found this sucker on the forums
![image](https://user-images.githubusercontent.com/19233143/31526467-f7cf49a8-af94-11e7-856c-aaf2e887a23e.png)

**Comment by Leland** [comment]
No movement in over 5 months - closing. If there's still an interest in discussion and development, ping me and will reopen.
