### ISSUE TITLE
Pools of water replaced with bottles of water

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#22139]
This one was pretty old (8 months+) but I guess no one ever reported or fixed it, since it was still here when I picked up cdda again.

There's a specific type of basement spawn that always has an corpse with an M60 and sandbags behind a corridor of wooden crates. Previously, you would pass two puddles of water on the way down this corridor. Then one day, a patch turned these puddles into bottles of water.

I don't believe this is intentional, since literally every other bottle of water I've seen in the game is purified or mineral water. Not to mention normally fixed item spawns of drinks usually appear in proper locations (shelves, fridges) rather than in the hallway.

**Comment by cainiaowu** [comment]
It is actually a part of 0.D millstone.

See https://github.com/CleverRaven/Cataclysm-DDA/issues/21700

**Comment by Regularitee** [comment]
Right, it's a duplicate so I'll close it.
