### ISSUE TITLE
City name display spoils vault special

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#22154]
The vault special pretends to be a city on the surface, but it isn't one. As a result it doesn't have a name and isn't displayed on map as a city.

**Comment by ZenZen2** [comment]
It also doesnt have wandering zombies.
But i am not sure if fixing this is worth the work, after some playing time everyone knows how the city looks like on map.

**Comment by NetSysFire** [comment]
It has been three years, but there are wandering zombies now.

**Comment by I-am-Erk** [comment]
vault special is presently disabled until it can be rebuilt to modern spec, no longer valid.
