### ISSUE TITLE
Giant Rattlesnake ignored by Zs

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#22153]
latest version

### Expected behavior
Giant Rattlesnakes triggers Zombies to follow and attack, like for any other animal

### Actual behavior
Giant Rattlesnakes do not trigger Z aggro at all. In fact, even a Giant Rattlesnake attacking a Zombie will not force the zombie to retaliate against the attacking Giant Rattlesnake

**Comment by Night-Pryanik** [comment]
Giant rattlesnake is in `small_animal` monster faction. Zombies are neutral towards them, so working as intended.

**Comment by AncientSion** [comment]
oh, sorry. thanks tho @Night-Pryanik

**Comment by Coolthulhu** [comment]
That `small_animal` may be considered a bug, though.
Giant rattlesnake is medium, meaning it is larger than a dog (which is small). `small_animal` is supposed to be the faction containing anything too small to interest zeds.
