### ISSUE TITLE
Npc's mom did not exist.

### ISSUE THREAD

**Issue by lcy03406** [CleverRaven/Cataclysm-DDA#22155]
Game version:6851

Operating system:Win8.1

Tiles or curses:Tile

Mods active:  "dda", "Medieval_Stuff", "StatsThroughSkills", "boats", "filthy_morale"

### Expected behavior
If NPC wants me to kill his mom, he should have a mom. 

### Actual behavior
But when I got the position of the quest marker, I saw no one.

I met the NPC at the northwest of my house, and when I accepted the mission, his mon's marker was exactly in my house. I entered the house and saw no one there. I wait a while until the marker moved a bit, and I caught up with it, in an open ground, still I saw no one.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1385128/save.zip)

### Steps to reproduce the behavior
I have no idea if it can be reproduced.

**Comment by ituluwituluwzev** [comment]
When I load the two saves both are black without anything...

Their "mom" is a zombie. The quest marker only marks the location, but does not keep track of the target. The marker shouldn't move.

**Comment by Broken-Admin** [comment]
>The marker shouldn't move.
This is true it happens with the "*Find My Dog*" quest also.

**Comment by kevingranade** [comment]
I received another similar report of this issue via email and have some thoughts for adressing the issue.
1. Adjust the NPC dialogue to describe the zombie, and mention they locked the mother in a basement.
2. Adjust the mission spawn code to find a basement, spawn the mom zombie there, and insure the entrance is blocked somehow.

**Comment by ZhilkinSerg** [comment]
> Adjust the mission spawn code to find a basement, spawn the mom zombie there, and insure the entrance is blocked somehow.

Zombie mom should be spawned already, but not in the basement:

https://github.com/CleverRaven/Cataclysm-DDA/blob/b7bd913415a51c26b3b2bbec2debb55878b9181b/src/mission_start.cpp#L212-L224

There is `board_up` function - we can use it:

https://github.com/CleverRaven/Cataclysm-DDA/blob/1116ab950fdcdd905a4481369b4440d5e9a66ae1/src/start_location.cpp#L111-L188
