### ISSUE TITLE
Debug message upon NPC skill training 

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#22167]
Game version: 0.C-24373-gfface81da0

Operating system: Linux

Tiles or curses: Curses

Mods active: Boats

### Expected behavior
Traning without debug message. 

### Actual behavior
Training occurs but only after debug message appears and has to be continued. 

### Steps to reproduce the behavior
Have NPC that you currently have with no active mission train you. 

Previous bug report that needed confirmation. 
Issue #18782

![nullmisson](https://user-images.githubusercontent.com/12091471/31628592-01ba8224-b266-11e7-828d-d17bf573a807.png)

**Comment by atealein** [comment]
The same message appears on 
Game version:
O.C-24382-g55c2ef5
Operating system:
OSX 10.11.6
Tiles or curses:
Curses
Mods active:
Disable NPC needs, Folding Parts pack, Vehicle Additions pack, Tanks and Other Vehicles, Disable Religious Texts, No Antique Firearms

**Comment by NoCreativeNames** [comment]
This is the same bug that causes receiving free training from an NPC to make them act like you completed their mission for them. The game seems to check how much you owe an NPC for training, and if you don't owe them anything, it clears the mission assuming you must be receiving it as a mission reward.

**Comment by atealein** [comment]
I confirm, I have several missions now to which no NPCs respond because they consider them somehow done.
