### ISSUE TITLE
Taekwondo forces unarmed attacks while using a reach weapon

### ISSUE THREAD

**Issue by Kazamar** [CleverRaven/Cataclysm-DDA#22161]
Game version: 6851

Operating system: Windows 10 64-bit

Tiles or curses: Tiles

Mods active: DDA, Cataclysm++, DinoMod, Deadleaves' Fictional Guns, Medieval Content, Mining Mod, More Survival Tools, No Explosive Zombies, Parks and Rec Buildings, PKs Rebalancing, Packaging, Classic Roguelike Classes, StatsThroughSkills, Tanks and Other Vehicles, ZSFIXED Extra Proffesions, Boats, Crazy Cataclysm, Icecoons Arsenal, Filthy Clothes, Makeshift Items, Classes and Scenerios, Necromancy, Disable NPC Needs, Simple nutrition, Extendfed Realistic Guns

### Expected behavior
While wielding a knife spear I would assume that the reach attack would use the spear, training piercing and melee, While attacking an adjacent enemy would use the forced unarmed attack from Taekwondo, training unarmed and melee.

### Actual behavior
All melee attacks, including reach attacks, are treated as unarmed for damage and skill training while in Taekwondo stance.  Only tested with a knife spear.

### Steps to reproduce the behavior
Equip a reach weapon, only tested knife spear, while using the Taekwondo style. Hit somebody with a reach attack.

**Comment by Night-Pryanik** [comment]
Closed by #23410.
