### ISSUE TITLE
Same letters on all items in inventory

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#22180]
Game version: 0.С-6863

Operating system: Windows XP SP3 x86

Tiles or curses: tiles

Mods active: default only

### Expected behavior
All items in inventory of a newly created character have different letters.

### Actual behavior
All items in inventory of a newly created character have the same letters.

### Steps to reproduce the behavior
Start a new game and look at the inventory.
![default](https://user-images.githubusercontent.com/11132525/31680520-36e5f5ce-b37d-11e7-8035-0734f52b9c99.png)

I suspect this has something to do with #22162?

**Comment by OzoneH3** [comment]
Working on it.

**Comment by angoddu** [comment]
I'm also getting this bug

**Comment by Shinino** [comment]
As a side-note on this one:  I've also seen where letters will change.  Like a hammer will be 'x' and after using it, it'll be 'c'.  I'm sure it's tied into the same issue.

**Comment by Treah** [comment]
> As a side-note on this one: I've also seen where letters will change. Like a hammer will be 'x' and after using it, it'll be 'c'. I'm sure it's tied into the same issue.

Did you assign it a specific letter or using the one auto assigned? Also does it go away when you do assign it a locked letter?

**Comment by Shinino** [comment]
It was auto-assigned in each case.
