### ISSUE TITLE
Cannot hold down arrow keys to move

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#22182]
Game version: Build 6863

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: None

### Expected behavior
While in a menu if I hold down the up/down arrow key it will quickly scroll through the different options.

### Actual behavior
Holding down the arrow keys does nothing. The initial press moves it down one but holding it does nothing

### Steps to reproduce the behavior
Spawn in
Open debug menu
Hold down an arrow key

Before you ask, yes my keyboard is working. I can hold down the arrow keys in other applications with the expected result.

**Comment by nocico** [comment]
I broke it yesterday with https://github.com/CleverRaven/Cataclysm-DDA/pull/22171 :D https://github.com/CleverRaven/Cataclysm-DDA/pull/22183 should fix windows.

(8/2 and j/k should still repeat if you need to scroll something right now)
