### ISSUE TITLE
Fresh milk becomes rotten in eight hours?

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#22187]
Pasteurized milk can last at least a day or two with no significant change; I know, I've accidentally left a glass or two out on the table overnight. 

Raw milk turns into yogurt which turns into heavier products like cheese. It doesn't really rot when left refrigerated... and even it does sour, you can just scrape off the top layer to restore much of the original taste.

Unless you're using a trash bin as a milk bucket, I really can't come up with any reasonable explanation for the extremely short 8-hour expiration window on raw milk -- let alone on pasteurized packaged milk.

**Comment by kevingranade** [comment]
Provide some sources for milk spoilage rates, or open a PR that changes to
a better value and be prepared to justify it.

Keep in mind that all the milk in the game is either:
Not fresh.  I.e. spawned at the start of the game, and has been sitting
un-refrigerated for a day or more, and has been sitting refrigerated for an
unknown amount of time before then.
Not pasteurized. I.e. produced directly via milking a cow.

So regardless of how it's adjusted, you'll never see milk achieve the
expected shelf life of modern commercially produced milk.

**Comment by Coolthulhu** [comment]
The game starts 5 days and 8 hours after "hour zero".

**Comment by Tsunder** [comment]
> Not fresh.  I.e. spawned at the start of the game, and has been sitting
un-refrigerated for a day or more, and has been sitting refrigerated for an
unknown amount of time before then.
>The game starts 5 days and 8 hours after "hour zero".

most food should be old or rotten by then, the player should not be able to find fresh food... anywhere but the ground really. 

the player starts in spring, where the temperatures are near freezing for the most part of the day cycle. (this would not apply in a non-spring start) (plus electrical stuff would run on automated for potentially days or weeks w/o human organization, unless people turned it off.)

at any rate, a cursory websearch landed me at: https://cooking.stackexchange.com/questions/25583/how-long-does-it-take-for-milk-to-spoil-unrefrigerated

which suggests 2-3 days.

**Comment by Regularitee** [comment]
Don't forget cows milking was just implemented, so fresh milk is also available now...
