### ISSUE TITLE
clothing with 0% or no part coverage should not generate damaged

### ISSUE THREAD

**Issue by Tsunder** [CleverRaven/Cataclysm-DDA#22189]
items like barretes or other cosmetic articles of clothing that have 0% coverage or don't cover anything  should generally generate in undamaged condition, as they would never get damaged in normal wear.

**Comment by TeMPOraL** [comment]
Can't the item damaging code in case of explosion damage those items too?

Note that some items might have other sources of damage. A hairpin, for example, can become damaged when used for lockpicking.

**Comment by kevingranade** [comment]
What's the impact here?
If it's totally cosmetic, I don't see adding special code just for these
items.

**Comment by Tsunder** [comment]
> Can't the item damaging code in case of explosion damage those items too?

not sure about when worn, but as an item on the ground it'd be no different than any other item. 

>What's the impact here?
in-game consistency between what the player and npcs experience, if an item cannot be damaged through the players lifespan, it shouldn't be either on npcs/mobs.

**Comment by Coolthulhu** [comment]
Having them just break apart completely when damaged, like `count_by_charges` items, would not be a lot of extra code.
Though it could be a better way to specify it for 0 volume items rather than 0% coverage ones.

**Comment by Tsunder** [comment]
there are some items with volume zero that have coverage, suprisingly. medical gloves, dust masks, protective mouthpieces, bikini pieces all have 0 volume but some amount of coverage

a further out idea could be an additional layer in which multiple items worn won't affect encumberance and have all clothing have a non-zero coverage, but I think filtering items from being spawned damaged would be sufficient for now

**Comment by ituluwituluwzev** [comment]
Car running over damages the item.

**Comment by Broken-Admin** [comment]
That seems quite logical.

**Comment by kevingranade** [comment]
> in-game consistency between what the player and npcs experience

I have no idea what this means.

**Comment by kevingranade** [comment]
I'm still seeing, "this is totally cosmetic", and a bunch of counter-examples.  Need a meaningful ratonale for doing this, otherwise I'm closing it.
