### ISSUE TITLE
Bright Nights Mod Causes Game Loading Issue

### ISSUE THREAD

**Issue by Shinino** [CleverRaven/Cataclysm-DDA#22198]
Game version: 6870

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Dark Days Ahead, Bright Nights, Filthy Clothing, Disable NPC Needs, Simplified Nutrition, Craftable Gun Pack, Bionic Systems Mod, Extended Realistic Guns, Makeshift Items Pack, More Survival Tools, Cataclysm++, More Buildings, More Locations, Beta National Guard Camp, Urban Development, Boats, Folding Parts, Vehicle Additions, EXTENDED_BUILDINGS, Classes and Scenarios, Stats Through Skills IV, ZSFIXED_C:DDA Extra Professions

### Expected behavior
Game should load when loading save or creating new character

### Actual behavior
Error upon either loading save or creating new character (even in a new world).  Screenshot will be attached showing error.

### Steps to reproduce the behavior
Install mods, attempt to load/create game.
![screen shot 2017-10-19 at 9 26 20 am](https://user-images.githubusercontent.com/32268608/31783593-61f1bed6-b4c4-11e7-952c-89920eef2dd3.png)

**Comment by Shinino** [comment]
Okay.  So this apparently affects any mod that hasn't updated regional_map_settings.json to include 'Houses'.  

On the left is that file from Bright Nights -- on the right is the same file from the base game.    My guess is that if the following is added in Bright Nights (and any other mod with the same issue)

"houses": {
              "house_two_story_basement": 1,
              "house": 1000,
              "house_base": 333
},

that it should resolve the issue.   I've tested it locally and it does work.


![screen shot 2017-10-19 at 12 14 36 pm](https://user-images.githubusercontent.com/32268608/31784431-459aef34-b4c7-11e7-92ac-9c7dca0311ea.png)

**Comment by Coolthulhu** [comment]
Should be fixed now
