### ISSUE TITLE
Item browser only working on phone

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#22190]
I'm not sure if the [item browser](http://cdda-trunk.estilofusion.com/) is something that is maintained here but I can only view crafting recipes and such in the item browser when I access it on my phone. I always get errors when I use the desktop version.

**Comment by ZhilkinSerg** [comment]
Github repo of item browser: https://github.com/Sheco/cdda-itembrowser

**Comment by Tsunder** [comment]
use this isntead, https://cdda-trunk.chezzo.com

**Comment by Treah** [comment]
@Night-Pryanik 
This is not maintained here this should be closed so the issue can be raised on the correct project.
