### ISSUE TITLE
Installing minireactor into vehicle while charge is less than 500 produces an undroppable plutonium cell that dupes into 5 cells upon save/load

### ISSUE THREAD

**Issue by danthesane** [CleverRaven/Cataclysm-DDA#22191]
Game version: 0.C -24337-gec6b15f

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Dark Days Ahead, Filthy Clothing, Disable NPC Needs, Simplified Nutrition, Folding Parts pack, StatsThroughSkills

### Expected behavior
When minireactor is installed with a charge and the charge is less than 500, no cell would drop at all.

### Actual behavior
When minireactor is installed with a charge less than 500, a plutonium cell is placed in the player's inventory that is undroppable. Upon save and load, this 'phantom' cell becomes 5 standard plutonium cells.

### Steps to reproduce the behavior
-Have minireactor installed in vehicle
-Have less than 500 charge in minireactor with minireactor inactive.
-Uninstall minireactor from vehicle (should produce "minireactor(499)" or whatever)
-Reinstall minireactor into vehicle
-Reactor in vehicle is empty, players inventory contains phantom cell - try to do something with it!
-To dupe, save then load your game. It becomes 5 cells worth 2500.

**Comment by Cosmitz** [comment]
Can confirm. Reproduced steps, have one plutonium cell, can't load to refill minireactor. 

>Debug; Tried to reload zero or less charges. // bool item::reaload(player&, item_location, long int) // serc/item.cpp 4791

Saved/load, became 5 cells, loaded successfully 2500 charges.

**Comment by Nerezza** [comment]
Confirming this is still a problem in the latest experimental, this bug is now over 2 years old!

Basically, installing a microreactor into a car ejects the plutonium cells inside. Here's the kicker: Plutonium cell charge is 1 plutonium charge per 500 power charge... Because of this I would argue that plutonium cells needed to be magazine-ized more than batteries needed to.

**Comment by I-am-Erk** [comment]
minireactors no longer exist
