### ISSUE TITLE
all characters gets nausious and starts coughing heavely and vomiting when any effect triggers

### ISSUE THREAD

**Issue by Tonami90** [CleverRaven/Cataclysm-DDA#22196]
Game version: 0.C-24584-g5a01faf

Operating system: Win10

Tiles or curses: Tiles

Mods active: Dark Days Ahead - Filthy clothing - Disable NPC needs - Simplified Nutrition

### Expected behavior
Not getting sick on any random character within the first 12 hours of ingame time while staying in the evac shelter.

### Actual behavior
getting sick on any random character within the first 12 hours of ingame time while staying in the evac shelter.

### Steps to reproduce the behavior
-use experimental build 6869
-make random character in standard world with standard mods
-wait until midnight
tested this several times with no changes.

**Comment by Zireael07** [comment]
You just wait? Not eating or drinking? Just curious.

**Comment by Tonami90** [comment]
nothing. not even moving

**Comment by OzoneH3** [comment]
Can confirm. Default character in a default world wait for some time.
My test characters started feeling nauseaus and start retching around noon.

**Comment by ituluwituluwzev** [comment]
The symptom smells like mushroom.

**Comment by kevingranade** [comment]
Looks like effect::activated() was supposed to be that safeguard, but did not work as expected due to special handling for vomiting and coughing.

**Comment by ZhilkinSerg** [comment]
Major decease. Should be in Theme Hospital.

**Comment by bl34k** [comment]
At least for me, it also seems to skip several turns when it gives me the coughing message. Not sure if it's a different bug altogether or if I just spend several turns coughing.
