### ISSUE TITLE
Keybinding to repeat action specified number of times

### ISSUE THREAD

**Issue by NoCreativeNames** [CleverRaven/Cataclysm-DDA#22208]
Keybinding should be added to allow player to repeat a specified action for a specified number of times or until interrupted.
Usage example:
Player attempting to smash object northeast of them, rather than pressing s then 9, presses a hotkey that brings up a prompt for a number, and submits a number. The character then proceeds to smash northeast the specified number of times, or until the item is smashed, or until it is made clear that no damage is being done.

Repeating actions should be interruptible by the same things that long actions are interruptible by as well as some other things potentially dependent on the action e.g. smashing being interrupted by the object being smashed or being told that no damage is being done, or lockpicking being interrupted by the tool being damaged/destroyed or the door being unlocked successfully.

Repetition should support most if not all actions in the game including for example "drink clean water from plastic jerrycan" or "move west."

This will reduce need for repetitive keystrokes for simple actions like lockpicking, prying, eating, or smashing, improving user experience without affecting gameplay.

**Comment by TeMPOraL** [comment]
Emacs-style numeric arguments, maybe?

In [Emacs](https://www.gnu.org/software/emacs/), you can hold Alt and type a number (or press Ctrl+U and type a number), and then follow that with any shortcut or command you'd ordinarily use. This sends that number as "numeric argument" to the command, which for most commands means they get repeated that number of times. So, for instance, if Ctrl+N moves down a line, Alt+50 Ctrl+N moves down 50 lines. (For commands where repeating doesn't make sense, the numeric argument usually gains a special meaning.)

We have a precedent for such a solution, in a way - grabbing/dropping actions can be prefixed with a number to select how many pieces of an item you want to grab/drop. So it technically works as a numeric argument to "get" / "drop" UI action, albeit without a prefix key.

**Comment by BevapDin** [comment]
This was discussed in #574, and in #7278 (which was closed because it's old). Maybe we should keep at least on of those issues open.

**Comment by OzoneH3** [comment]
@BevapDin Wouldn't this be something the macro system you proposed in #19961 would be able to accomplish? I'd really like macros to be a thing at some point.

**Comment by TeMPOraL** [comment]
Having today manually planted, fertilized and collected a few dozen plants, I strongly second the idea of a macro system. The simplest one would be enough - press F2 (or whatever) to start recording, perform your actions, press F3 to stop recording, use F3 to repeat. Or, Emacs-style, Ctrl+U 20 F3 to repeat 20 times ;). And/or maybe Shift+F3 to execute as much as possible.

Macro execution should naturally be stoppable the way e.g. reading is, and should automatically end on action error - e.g. stepping into a wall, (a)pplying things with no charges, getting a "you're tired" popup, etc.

**Comment by kevingranade** [comment]
To repeat the pertinent point, the problem here isn't simple willingness to
add the feature, this requires overhauling how most actions are handled to
capture their inputs in a repeatable fashion.

**Comment by kevingranade** [comment]
As for things like mass planting, that is much better handled by an actual
mass planting system where you designate where to plant.

Macro systems are fairly hostile to users, requiring every user to figure
out automation for repetitive tasks.

**Comment by NoCreativeNames** [comment]
Note that my proposal wasn't a system for making complex macros but for repeating a single action many times consecutively where conditions are unlikely to change, so rather than storing keystrokes it would store the action itself, such as "eat this item from this tile"

which might actually be more complicated so thats probably a bad idea

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.

**Comment by Zireael07** [comment]
I believe this would be a useful quality of life addition, if not obviated by the batch crafting.

**Comment by l29ah** [comment]
> Pick up nearby tool, activate it, use it with food, eat food x4, drop tool

> pick up rucksack, wear it, pick up welder, unload it, install its battery to the car, remove another battery from the car, put it into the welder, drop the welder into the cargo space, take off the rucksack and put it into the cargo space

> do { uninstall seatbelt; install seatbelt; } until mech < 2

> do { pick lock } until out of lockpicks

> cut up { acid-filled zombies; } until acid-filled zombies; smash zombies
