### ISSUE TITLE
PK-rebalancing (Latest not old) unable to create character see error.

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#22201]
Game version:
0.C-24600-g77ee89d   //  Jenkin's build number: 6870

Operating system: Win7 64bit 

Tiles or curses: Tiles

Mods active: DDA, PK's Rebalancing (Latest)

### Expected behavior
The mod to work? It's on the launcher idk what else to write here :P

### Actual behavior
Unable to use this mod
![error](https://user-images.githubusercontent.com/5264667/31794201-53f75b88-b519-11e7-87d6-41594a750d11.jpg)

### Steps to reproduce the behavior
I haven't played in 2 weeks, So I updated, read through the changelog and noticed that this change 
"Remove obsolete mods which are maintained in other repos  (#22125)"
which effected me. As I used the old version of PK-re-balancing which as far i knew was working but I'm no modder :P which was 2 weeks ago when I last played.

So I looked at the launcher and noticed that there was a more up to date version of it listed, so I installed that and got this error, when trying to create a character. 

(I've deleted the old PK folder in mods prior to installing the newer version is there another folder perhaps aside from the one in the mods I need to delete that i overlooked or something?)

**Comment by zakhad** [comment]
Adding 

"houses": {
"house_two_story_basement": 1,
"house": 1000,
"house_base": 333
},

which was mentioned in https://github.com/CleverRaven/Cataclysm-DDA/issues/22198 fixed it.

**Comment by pisskop** [comment]
Aye.  Thank you for the update.  Should be fixxed now.
