### ISSUE TITLE
[Ranged balance - STEP 1] Ranged design was not approved officially by lead developers.

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#22214]
Current ranged tests doesn't satisfy balance design outlined in:
https://github.com/CleverRaven/Cataclysm-DDA/issues/21244#issuecomment-310013403
But it was not approved officaly.

It must be discussed and approved by lead developers.

Recommended actions:
1) Discuss and approve ranged design
2) Go for that issue: https://github.com/CleverRaven/Cataclysm-DDA/issues/22211

**Comment by Firestorm01X2** [comment]
Probably if Kevin just write here:
"We are going for that: https://github.com/CleverRaven/Cataclysm-DDA/issues/21244#issuecomment-310013403" it would be enough to close that issue.

**Comment by kevingranade** [comment]
I approved it, you're out of line dude.
