### ISSUE TITLE
Replace usage of long with int  

### ISSUE THREAD

**Issue by BevapDin** [CleverRaven/Cataclysm-DDA#22217]
We support at least one platform (Windows) where `long` is effectively the same as `int` (see https://msdn.microsoft.com/en-us/library/s3f49ktz.aspx). Using it gives us no advantage. It only causes pain because of redundant manual type conversions (which are apparently done for type safety) and additional overloads. And it can cause trouble if somebody incorrectly assumes `long` is 64 bit because it's that way on *their* development platform.

I therefor opt for replacing all usage of `long` (signed/unsigned) with `int` (signed/unsigned). (Except for code that needs to interact with external code).

**Comment by TeMPOraL** [comment]
Since the game is targeting multiple platforms, why not go all the way in and replace *all* use of those base types with platform-independent ones? Having `i32` instead of `int` and `i64` instead of `long` (Linux 64bit) or `long long` (Windows 64bit) would solve this issue, as well as future portability problems.

**Comment by nshcat** [comment]
But then use the standard types defined in `<cstdint>`, like `::std::uint32_t`, and not custom typedefs.

**Comment by kevingranade** [comment]
I'm not sure the verbosity of the alternatives is worth the additional
precision of the types, particularly since we rarely if ever have any
particular range requirements.

**Comment by lcy03406** [comment]
I prefer int.
`long` is a source of chaos and should be avoided in any case.
`int` means just an integer and no special requirements.
`long long` means something may overflow int, maybe a temporary of the product of two ints.
`i32` or `::std::int32_t` indicates that I want this field to have a specific range(32 bits), usually implies that this field may be stored into a binary file as is.
`::std::int64_t` is basically the same as `long long` but emphasizes the excact range is 64 bits and cannot be 128 bits or else.

**Comment by kevingranade** [comment]
Feel free to nuke long whenever you can, unless you find something that actually needs to be 64-bit, then replace with [u]int_fast64_t or [u]int_least64_t.
