### ISSUE TITLE
9mm turrets don't accept all factory-loaded 9mm ammo as the description indicates

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#22219]
Game version:
O.C-24382-g55c2ef5
Operating system:
OSX 10.11.6
Tiles or curses:
Curses
Mods active:
Disable NPC needs, Folding Parts pack, Vehicle Additions pack, Tanks and Other Vehicles, Disable Religious Texts, No Antique Firearms, Food Preservation via Ionizing Radiation

### Expected behavior
<img width="348" alt="screen shot 2017-10-21 at 16 29 34" src="https://user-images.githubusercontent.com/25322782/31853784-10703624-b68f-11e7-9bd4-b87e2eb1cce5.png">

Turret description states that any factory-loaded 9mm ammo would do.

### Actual behavior
<img width="324" alt="screen shot 2017-10-21 at 18 33 04" src="https://user-images.githubusercontent.com/25322782/31853794-3a1e1392-b68f-11e7-9cf5-d5718bbb5d26.png">

On the contrary, only one of the four types of factory-loaded ammo works. 

### Steps to reproduce the behavior

Have only FMJ or other non-JHP 9mm ammo in your inventory when activating the turret.

My guess the easy fix to this would be to correct the description, although why a turret that can use factory-loaded JHP wouldn't be able to use the other factory-loaded 9mm ammo is beyond my knowledge.

**Comment by kevingranade** [comment]
> why a turret that can use factory-loaded JHP wouldn't be able to use the other factory-loaded 9mm ammo is beyond my knowledge.

I suspect this is an issue with the code involved only accepting one type of ammo.  If so, another fix is having the prompt supply the name of the item it will accept.

**Comment by Maleclypse** [comment]
Since we don't have 9mm turrets in repo anymore should this be closed or examined to see if it impacts turrets that do remain?
