### ISSUE TITLE
Suggestion: format cash cards to display dollar amount rather than raw cent charges

### ISSUE THREAD

**Issue by sctjkc01** [CleverRaven/Cataclysm-DDA#22216]
Per a [recent suggestion in a YouTube comment thread](https://www.youtube.com/watch?v=UCVHXL41hBI&lc=z22sxvfagkilyzoip04t1aokghcuuiqtgvznflvwxsfkrk0h00410.1508553298169975) there was a small request to format the charges of a cash card to a proper dollars-and-cents display rather than just displaying the raw cent count.

While I am by no means going to imply that such a small change would have no effect to stability of the game at large, I'd imagine adding an extra cutout [here-ish (item.cpp:2382)](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L2382) checking if the item in question is a cash card and then formatting it per local locale would probably be enough to implement this request.

**Comment by TeMPOraL** [comment]
I second the idea, though may I suggest a more general implementation? Let's add the concepts of "charge type" which would define the unit, divisor and formatting of a charge. You could then have something like following:

Charge type | Format string | Formatted value | Note
-|-|-|-
`UNIT` | ` (%i)` | `amount` | The default, would work for battery, book chapters, ammo, etc.
`CURRENCY` | ` (%.2f$)` | `amount / 100.0f` | The money display.
`PERCENTAGE` | ` (%i%%)` | `amount / 100u` | Percentage display.
`TIME` | `( %is)` | `amount` | For countdowns implemented as charges.

This would let us push the charge type out to JSON.

We could also generalize it by defining the concepts of `divisor` and `unit`, leading to the format string ` (%.*f%s)` being used with `amount/divisor, (int) log10(divisor), unit`. The previous examples would then go like this:

Charge type | `divisor` | `unit`
-|-|-
`UNIT` | `1` | `""`
`CURRENCY` | `100` | `"$"`
`PERCENTAGE` | `1` | `"%"`
`TIME` | `1` | `"s"`

and it would also allow to add new interpretations of charges in JSON, too.

---

Now I know I might be overcomplicating here - [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) and all, but I've seen plenty of stuff done through charges already - ammo count, countdowns, money, actual charge, book chapters, etc. Maybe there are even more. I'd love to know what people more familiar with the codebase think.

**Comment by Treah** [comment]
I am not sure formatting it to local currency would be required. The game is supposed to be taking place in new England where the dollar is used. Wouldn't make much sense to convert it to a local currency.

**Comment by Zireael07** [comment]
I think they meant . Vs , when mentioning formatting according to locale

**Comment by TeMPOraL** [comment]
Who meant that? I see the topic being purely about rendering cash cards as e.g. `$123.45` instead of `12345` as it is now.

**Comment by Treah** [comment]
@Zireael07  Ahh that makes more sense then. 
@TeMPOraL  The original author advised formating to locale which I interpreted changing the dollar to other currency symbols.

**Comment by TeMPOraL** [comment]
You're right; my mistake.

**Comment by lcy03406** [comment]
I thought we were using integeral credit points in the cataclysm rather then the ancent dollors so that cash format is not a bug but a feature.

**Comment by TeMPOraL** [comment]
Trading and vending machines seem to use dollars and cents, so either there's a "credit points" currency in the lore that happens to be fixed at 100:1 ratio to USD, or this is a display issue :).
