### ISSUE TITLE
Can't compile game under Linux with disabled localization

### ISSUE THREAD

**Issue by nshcat** [CleverRaven/Cataclysm-DDA#22220]
Game version:
Current master branch

Operating system:
Arch Linux x64, up-to-date

Tiles or curses:
Tiles

Mods active:
None

### Expected behavior
Game compiles and installs using the command:
`make PREFIX=/home/kitty/cdda_git USE_HOME_DIR=0 RELEASE=1 LTO=1 CLANG=1 LUA=1 TILES=1 SOUND=1 LOCALIZE=0 -j8 install`

### Actual behavior
Linking fails with the error message:
`/tmp/lto-llvm-db8bbe.o:ld-temp.o:function player::sort_armor(): error: undefined reference to 'strip_positional_formatting(char const*)'`

### Steps to reproduce the behavior
Clone repo, use given command to compile.

**Comment by Night-Pryanik** [comment]
Is this still an issue?

**Comment by Leland** [comment]
Closing due to lack of info.

Please reopen if there is additional information to be provided!
