### ISSUE TITLE
Vending Items Spawn Location in Hotel error

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#22228]
Vending machines in the hotel will spawn their loot several tiles west of where they should be.  OR rather several tiles to the Xaxis.

<a href="https://imgur.com/gcngZU1"><img src="https://i.imgur.com/gcngZU1.png?1" title="source: imgur.com" /></a>

This error has been persistent since the changes to vending machine item lists.

**Comment by Treah** [comment]
I have seen this occur in mansions too and another location where I don't think there is vending machines even at...
