### ISSUE TITLE
ANFO charge recipe has insane components

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#22226]
1 ANFO charge recipe requires 700 units of ANFO and takes 2 hours to complete (and some other things that are not relevant for this issue).
However, the recipe for ANFO creates only 5 units at a time, requires 3 hours to complete and 500 gasoline and 90 ammonium nitrate (which requires on it's own 9 nitric acid and 9 ammonia and some minutes).
So to sum it up, creating all the ANFO units required to make a single ANFO charge would require:
70 000 gasoline 
1260 ammonia
1260 nitric acid 
420 hours of crafting (if you have all the ingredients ready)

Lets split it up:
----
> The ammonia is relatively easy - we find gallon jugs with 30 units of it all over the place and one can craft a lot with just a charcoal kiln, charcoal smoker, a swamp tile and some scrap metal. It does take 36 minutes to craft only 2 and this recipe time does not go down with batch either, so it will be worth your time to just run around and gather 42 gallon jugs of it instead.

> The gasoline seems excessive, but it is again doable if you are near a big town you can find few gasoline stations that could have more than 20 000 at a time. 

> The tricky part is the nitric acid. You can find bottles of 3 of it in labs (you'll need 420 of them) or craft it from sulfuric acid and to craft that one you require hydrogen peroxide (concentrated) which is not really craftable (one can craft the dilluted version from concentrated and vice versa, but neither is craftable by other means) and can again be found from labs in bottles of 3. So that would mean 420 bottles of either nitric acid or hydrogen peroxide and if it is the latter - add 25 minutes crafting time per unit you need to make into nitric acid.

> Raw crafting time, assuming you have ALL the ingredients ready is 420 hours. If we approximate that we will find the 1:1 nitric acid and hydrogen peroxide from labs, that will add some extra 262.5 hours of crafting time. 

I can throw some more numbers and calculations to why this might be making this recipe practically implausible to be made (unless you are insane person that wants to memorize all recipes without cheating like me), but I wonder if the simple explanation might be that the original ANFO recipe should be crafting maybe 50 instead of 5 units of ANFO for the amount of ingredients needed?

**Comment by Coolthulhu** [comment]
#18337 changed the stack size, but failed to adjust the crafting recipes.

**Comment by Leland** [comment]
Charge JSON is over yonder:

https://github.com/CleverRaven/Cataclysm-DDA/blob/893c72fb2ad5e45eaf2034fde2a161bab385b88d/data/json/recipes/weapon/explosive.json#L295-L308

Since #18337 dropped ANFO stack size by a factor of 10, that 700 probably just needs to get dropped to 70
