### ISSUE TITLE
"More locations" mod adds a building with unsupported tiles

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#22225]
Running `cataclysm --check-mods` results in:
```
src/overmap.cpp:4814 [void building_bin::finalize()] Tried to add city building small_storage_units, but it has a part with non-zero x or y coords (not supported yet)
```

The building is then silently dropped, so it has no in-game effects.

**Comment by ZhilkinSerg** [comment]
There is `small_storage_units` overmap special in "More buildings" and `small_storage_units` overmap terrain (city shop) in the `data\json\mapgen\parks_recreation`.

Which one is affected?

**Comment by Coolthulhu** [comment]
The city shop.
Houses, shops and parks must be 1x1 in x/y for now. They can be more than 1 z, though.
