### ISSUE TITLE
Can't place Brazier

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#22227]
Game version: 6877

Operating system: Win 7

Tiles or curses: Tiles

Mods active: dda

### Expected behavior
Activating a brazier will let me place it on the ground

### Actual behavior
Gives the message saying "You can't do anything interesting with your brazier

### Steps to reproduce the behavior
Spawn in a brazier. Press a to view activate-able items. Notice brazier isn't there. Go to your inventory. Select your brazier. Notice that the activate text is green meaning you can activate it. Activate brazier. Get the above message.

You also can't see the item in the % menu either

**Comment by Chezzo** [comment]
Looks like braziers got made into furniture and you set them up with the construction menu as of #21321.
