### ISSUE TITLE
Add some of the Wooden Keg functionality to the Fermenting Vat

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#22231]
Currently if you examine a wooden keg tile you get prompt with a dialogue option asking you to:
1. Fill a container with whatever is in the keg
2. Have a drink (if drinkable liquid)
3. Refill (the keg with some extra liquid)
4. Examine (provides a status that looks for example like this : " This is a wooden keg. It contains clean water (491), 98% full" ) 
5. Cancel

With fermenting vat situation is a bit more obscure. If the vat is empty and you are carrying a liquid that can ferment it will prompt you to pour it in on examine and if you want to start the fermenting process. As this takes a bit of time you might want to fill the vat first before initializing it. However, there is no way to know how full a vat is unless it is entirely full. Viewing the tile will erroneously report the fermenting vat as empty and there is no way of knowing what liquid is in there unless you have some of it in your inventory and are prompted to pour it in. 

I suggest that the very least a proper examine function is added to the menu options of the fermenting vat or entirely similar to the wooden keg menu is made that will for example:
1. Pour fermentable liquid in
2. Pour whatever is in out in a conteiner
3. Start the fermenting cycle
4. Examine
5. Cancel
The examine option will provide information on what is in the vat, how full it is and how long the fermenting cycle will last (if not started yet) and how much is left (if already started).

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
