### ISSUE TITLE
0 City size issue on character creation

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#22241]
Game version: 6882

Operating system: Win 7

Tiles or curses: Tiles

Mods active: none

### Expected behavior
When selecting a scenario for a world with city size 0, you have the appropriate pool points

### Actual behavior
You are given no additional points for the default scenario. If you change it then re-select it you get the correct points

### Steps to reproduce the behavior
Make a world with city size 0
Make a character
The pool points will not be accurate

**Comment by laeaton2001** [comment]
This will be from #22224. Will look at it today.
