### ISSUE TITLE
Incomplete JSON_INFO doc

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#22240]
I was unable to find any documentation an how the "location" value in the vehicle parts section. Would someone be able to update that doc please? I don't know what are valid locations other than looking at other parts and seeing what they have.

**Comment by Treah** [comment]
Also might be helpful to have what weight does and what values are greater and lower. Also weight is used differently in json files. Sometimes its chance weights and sometimes its traditional weight as in how much it weighs. 
Chance weights are also all over the place sometimes its 1 - 100 sometimes 1 - 10 its a lot of guess work unraveling this.

**Comment by angoddu** [comment]
Yah. I find myself doing trial and error a lot when working on this code. It is bound to happen with open source code so it is understandable

**Comment by Coolthulhu** [comment]
Writing the docs separately from code is extra work that is easy to forget about. I checked the doxygen results, but they are extra work for the reader.
Not sure what to do here. Maybe there is some brilliant format specification format that allows solving this issue.

That `chance` thing is terrible, but the problem with fixing it is that there are tons of mapgen entries that use it, then tons of mods that we can't update from our side but still do support. And no versioning support for mods, so we can't do conditionals.
I see the following options:
* We make it use floating point. This is a clear sign that we want to use the chance directly, not as percentage or `one_in`. Both `one_in` and percentage can be transformed into floating point chances easily. Drawback: percentage chances may sometimes want to use exactly 1%, which would need to be expressed as 1.0 in floats.
* We change it into `"percentage"` and `"one_in"`. Old `"chance"` support gets dropped after 0.D. Drawback: naming doesn't clearly mention chance ("chance_percentage" would be too long, so no better).

**Comment by angoddu** [comment]
What about the vehicle part location field? I looked in the doxygen_doc and didn't find what I was looking for.

**Comment by Coolthulhu** [comment]
It doesn't seem to be documented at all, not even in the comments.
Basically, it determines what "slot" it occupies: whether it is a frame ("structure"), directly on a frame, on some specific part. Locations can only be occupied once per tile, except for location-less parts.
It affects display order (both in menu and draw order), damaged part selection, and whether the part is a frame.

**Comment by kevingranade** [comment]
> We make it use floating point. 

This would be unclear and fragile. Changing the label is the only reasonable option.

**Comment by kevingranade** [comment]
Closing as the initial question was answered.
