### ISSUE TITLE
Remove or expand "no religious texts" mod

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#22259]
Out of all the "no x" mods, this one is the least explainable:
* It doesn't remove churches and cathedrals, so it can't be explained with "religion offends me" or "religion is a sensitive topic"
* It doesn't remove all just-for-morale books, so no real gameplay role
* It doesn't remove a lot, so it's not good for debloating
* The overlap of those books with skillbooks in item groups is very low, so it can't be explained with "it makes better books drop more often"
* It doesn't remove sci-fi stuff that doesn't fit in a gritty zombie apocalypse

The only thing it really does is taking a slot in the mod list, which got pretty fat again.
It was added in #8009 with rationale consisting literally just of "but it has a theme unlike the no silly items mod". But this rationale was never valid, because church mapgen is older than this mod.

**Comment by atealein** [comment]
Unlike church buildings and cathedrals, which I can choose to ignore and not go into, religious books of all kinds are spawning as loot all over the place in great variance (kudos) and quantities. I personally use this mod and find it very helpful (even if the bug that the "patriot" house still spawns "King James Bible" even if the no-religious text mod is activated, as mentioned in this issue, which btw is not yet resolved... #19736 ).

**Comment by tinukedaya** [comment]
What @atealein said. I'm using it for the same reason. And because I think it's sensitive or that it would offend me. It's just the quantities. 

I'd say it's ok to remove the mod, if the drop rate of those books would be toned down quite a bit.

**Comment by kevingranade** [comment]
Go ahead and nuke it, it was pretty much a forum politics thing.

**Comment by Treah** [comment]
I agree I don't think this necessitates a mod really. If someone is annoyed enough by this they can mod out the books in the json file. Or they can maintain it as an external mod instead of it being maintained in mainline.

**Comment by ManOfHonor** [comment]
I always use it because the religious texts are flavor but basically useless. They might as well be another time magazine or whatever.

**Comment by CoroNaut** [comment]
If you have no other objective from removing the mod than just freeing a mod slot, then just keep it. Unless it gets in the way of a more encompassing mod or game feature, then it is literally just a mod. 

You or the players only gain a disadvantage when you remove the mod in this case.
If you keep the mod, it will still not affect anything and remain as a mod to remove unnecessary items that are themselves unnecessary to begin with.

**Comment by Theundyingcode** [comment]
IMHO it should either be nuked or expanded into a "SFW" mod.  Personally I'm not bothered either way but I can definitely picture a SFW mod being a major boon for someone with little siblings or hovering parents.

**Comment by gcaliber** [comment]
I never liked that religious books were added in the first place and have always appreciated this mod.

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
