### ISSUE TITLE
Portuguese language spelled incorrectly on the website

### ISSUE THREAD

**Issue by gcmartinelli** [CleverRaven/Cataclysm-DDA#22257]
Top right corner of the homepage. Should read "**Português**" and not "Portuguesa"

**Comment by Treah** [comment]
How does this relate to this project? The web page is not maintained on this github repo. Address this on the forums.

**Comment by gcmartinelli** [comment]
I was advised by an admin on IRC to post this here...

**Comment by Treah** [comment]
Odd im not sure why they would direct you to the github.. Maybe they misunderstood. Sorry if my response sounded harsh I did not intend it to be :(
