### ISSUE TITLE
It's possible to boil water with sealed tin can of ravioli

### ISSUE THREAD

**Issue by tvm1** [CleverRaven/Cataclysm-DDA#22255]
Game version: Build from today 
Mods active: Standard

### Expected behavior
It shouldn't be possible to boil water with tin can of ravioli (fresh). As it's watertight and preserves spoiling.

### Actual behavior
It's possible to boil water with tin can of ravioli (fresh) without opening it apparently. It will still be watertight and preserve spoiling.

**Comment by ituluwituluwzev** [comment]
Duplicates #20784
