### ISSUE TITLE
Mutagen no longer seems to have an effect

### ISSUE THREAD

**Issue by Rightfulnoah** [CleverRaven/Cataclysm-DDA#22265]
Game version: Build 6891

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Disable NPC needs, simplified nutrition, craftable gun pack, more survival tools, makeshift items mod, boats, folding parts pack, vehicle additions pack, tanks and other vehicles, prevent zombie revive, stats through skills

### Expected behavior
Mutagen mutates the user

### Actual behavior
Nothing happens aside from an occasional you feel dizzy and fall to the ground

### Steps to reproduce the behavior
Consume mutagen

**Comment by kevingranade** [comment]
Looks like there's a mixup between "MUTCAT_" and "MUTAGEN_".
This line: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iuse.cpp#L1115
should be referencing mutation_category_trait::mutagen_flag instead of mutation_category_trait::category_full
