### ISSUE TITLE
Can't use vehicle-stored items for crafting when vehicle is above ash

### ISSUE THREAD

**Issue by CameronFc** [CleverRaven/Cataclysm-DDA#22277]
Game version: 0.C-24379-gd2eb25e

Operating system: Ubuntu 16.04

Tiles or curses: Curses

Mods active: DDA + filthy clothing + disable NPC needs + simplified nutrition

### Expected behavior
Items inside of vehicle storage (trunks, stowboards, utilites, etc.) should be usable for crafting if they are nearby. It should not matter if the vehicle is parked over ash.

### Actual behavior
None of the items stored in the vehicle are usable as components, tools, or recipe books when the vehicle is parked over ash. This only happens for vehicle storage tiles that are directly over ash.

Driving the vehicle off the ash-covered tiles solves the issue.

### Steps to reproduce the behavior
- Burn down a forest because you are sick and tired of a nearby fungal bloom
- Park your mobile base over the resulting landscape of ash
- Notice that you can't craft anything unless you have the recipe memorized and the components in-hand.

**Comment by Night-Pryanik** [comment]
I suspect that's because pile of ash now is a container.
