### ISSUE TITLE
StatsThroughSkills damage

### ISSUE THREAD

**Issue by Weyrling** [CleverRaven/Cataclysm-DDA#22274]
Game version: 6886
Mods active: StatsThroughSkills
Severity: Minor

### Expected behavior
No change to current HP
### Actual behavior
Current HP on head, torso, arms, and/or legs goes down every time the game checks for a stat increase.
Depending on how much bonus Str you have from the mod starting from the head (related to body part HP weighting, I assume).
### Steps to reproduce the behavior
Have StatsThroughSkills enabled and perform a task that will cause a skill increase check.
Such tasks involve fighting, crafting, or reading books that will cause a skill increase.
### Miscellaneous
This happens because of the relationship between current HP and maximum HP when losing and gaining Strength and the fact that STS resets all bonus stats every time it checks for changes.

When you lose Strength, your current HP will reduce to be the same percentage of your max HP it was before.
When you gain Strength, your current HP will gain the flat bonus each Str point adds to max HP modified by your current HP percentage.
Repeatedly losing and gaining Strength will therefore constantly reduce your HP, potentially until you literally die from learning too much.

**Comment by kevingranade** [comment]
Workaround: don't use statsthroughskills :/
It's a barely-functional hack.

**Comment by ZhilkinSerg** [comment]
Please test provided fix.

**Comment by Weyrling** [comment]
The provided fix works fine normally, but if a player has HP modifying traits like Fragile/Glass Jaw there's a momentary change in current HP in the first check.
However it does not continue to degrade after that, so I figure it's a rounding error due to different variable types or something.
Still better than slowly dying, but not perfect.

**Comment by ZhilkinSerg** [comment]
> The provided fix works fine normally, but if a player has HP modifying traits like Fragile/Glass Jaw there's a momentary change in current HP in the first check.
However it does not continue to degrade after that, so I figure it's a rounding error due to different variable types or something.
Still better than slowly dying, but not perfect.

What do you mean? Fragile/Glass Jaw traits reduce max hp, but current hp is not affected. Did you experience hp drop on new game start?
