### ISSUE TITLE
Gorgon locked up

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#22282]
Gorgon seems to be unable to finish any of the jobs.
Displays just
```
gorgon-ghprb — Build triggered. sha1 is merged. 
```
@narc0tiq

**Comment by narc0tiq** [comment]
I see it, it looks like the disk is full. I'll go figure out why, and clean some of it out.

**Comment by narc0tiq** [comment]
So, the immediate issue seems resolved, but I'm still low on disk space. I'll keep monitoring.

In the meantime, maybe someone could fix the broken win32-tiles build? It's really not helping me monitor when I have to ignore build failures because of a known compile error.
