### ISSUE TITLE
"Can be stored in" info should respect blacklisted items from mods

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#22294]
So blacklisted survivor harness with active "No Survivor Armor" mod, for example, shouldn't appear as a viable storage for guns and thus confuse players, as there are no such items in their world.

**Comment by I-am-Erk** [comment]
Have nested containers killed this?

**Comment by Night-Pryanik** [comment]
Nope, it's still here.

**Comment by Night-Pryanik** [comment]
Adding a way to reproduce:

1. Spawn/find M4 carbine and look at its description

![изображение](https://user-images.githubusercontent.com/11132525/180401145-b6919611-ca30-4580-84ab-2d8dccc71089.png)
2. Create/find a mod that blacklists XL survivor harness, like this:

````
[
  {
    "type": "ITEM_BLACKLIST",
    "whitelist": false,
    "items": [ "xl_survivor_vest" ]
  }
]
````
3. Create a world with this mod.
4. In this new world spawn/find M4 carbine and look at its description

![изображение](https://user-images.githubusercontent.com/11132525/180401181-81cafceb-05ce-4b21-896e-ed406a36bfb7.png)
