### ISSUE TITLE
Bright lighting level in a fully closed car

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#22295]
Game version: 0.C-6872

Operating system: Windows XP SP3 x86

Tiles or curses: tiles

Mods active:default only

### Expected behavior
Closing all the doors and windows in the car, with fully repaired roof, should make lighting level very dark.

### Actual behavior
It is still bright even in a fully closed car.

### Steps to reproduce the behavior
Find or spawn a car (meth lab, for example), go into enclosed area, look at the lighting level.

![default](https://user-images.githubusercontent.com/11132525/32140542-121c6f82-bc76-11e7-8416-ba34bb551f94.png)

**Comment by cainiaowu** [comment]
from vehicle lighting maybe? have you turn off the lighting?

**Comment by Night-Pryanik** [comment]
Yes, I double checked that.

**Comment by Coolthulhu** [comment]
I think it could be because while vehicle internals are inside, the vehicle walls are still outside and as such become light sources as most outside tiles.

**Comment by Aivean** [comment]
Here is a bunch of relevant tickets:
#11621, #14329, #17561

**Comment by Leland** [comment]
Closing in favor of #11621 (which I've moved to a more generic ticket)
