### ISSUE TITLE
Add record to log when construction finishes

### ISSUE THREAD

**Issue by Leland** [CleverRaven/Cataclysm-DDA#22292]
A minor thing: would be nice to record in the activity log when construction finishes.

We add a record log for most other player actions ("You drop your matchbook on the grass."). Having a recorded instance of you finishing construction would be a nice QoL addition. At the very least, helps with understanding what's happened since that single instance.

A good beginning might simply be "You finish your construction," since the verbs relating to each of the individual constructions are varied ("you finish digging the pit," "you finish boarding up the window", etc).

Idea from @Asmageddon in #19930

**Comment by laeaton2001** [comment]
Any issue adding the verb to the construction json? Then just produce the message at the end of complete_construction()? Something like `add_msg(m_info, _("You finish %s"), built->verb);`

**Comment by Leland** [comment]
Nice, that sounds reasonable.
