### ISSUE TITLE
Map class refactor - splitting off functionality

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#22300]
I started some map refactoring. So far my idea for the split looks like this:
* `map_base` - defines a structure that wraps around a set of submaps
* `map_readable` - implements basic getters such as `get_ter`, but nothing like `sees` or `veh_at`
* `map_writable` - basic setters such as `set_ter`, but still no vehicles
* `vehicle_cache` - an adapter for `map_readable` that caches vehicles
* `map_editable` - everything that mapgen needs. Contains a `vehicle_cache`. This is the first option that can create vehicles (we need a cache for them)
* `cache_map` - an adapter for `map_readable` that caches everything (that needs caching) other than vehicles
* `viewer_map` - an adapter for `map_readable` that includes a `cache_map` and implements all sorts of complex behaviors that do not affect the map itself (but can affect the cache). Basically, everything you need to look at the map and see stuff on it.
* `map_caching` - what `map` is right now. Built on top of `map_editable` (or better: `map_writable`), includes a `viewer_map`. Keeps all the fat guts like active item processing, field processing, vehicle processing and so on

I could use help with the following questions:
* Which one of the above should exist (as separate entities)?
* Any way around `viewer_map` being an adapter, other than multiple inheritance in `map_caching` or having instead be a `map_viewable` that inherits `map_editable`? It could be cleaner if mapgen could be kept away from a class that is supposed not to provide editing capabilities. That's just hygiene, though.
* How to actually name those?

**Comment by kevingranade** [comment]
> Which one of the above should exist (as separate entities)?
> How to actually name those?

map_base + map_readable + map_writable => map_segment or map_area
If you need a read-only version of one of these, just make it const. I don't see a reason to split it into a reader and writer, and having a base struct with public or friend-accessable data members is an antipattern.
Also, this is the object where serialization would live.

I'm not convinced that mapgen needs vehicle caching, the primary driver of vehicle caches is "is there a vehicle at tripoint", and mapgen shouldn't need to do that often.

I'm also not clear what mapgen needs other than the getters and setters to the underlying data.

vehicle_cache + cache_map + viewer_map => map_cache
As I said I'm not convinced there's a need for a seperate vehicle cache, and I don't understand the cache_map vs viewer_map distinction, it looks like it seperates the cache data from the cache update logic, but that's the last thing we want to do.

map_caching => game_map "The map thaat represents the visible game state".

**Comment by Coolthulhu** [comment]
> I'm not convinced that mapgen needs vehicle caching, the primary driver of vehicle caches is "is there a vehicle at tripoint", and mapgen shouldn't need to do that often.

Vehicle pileup building, which is checked every time a new vehicle is added, checks `veh_at` ~O(`veh.parts.size()`) times. This is comparable to creating and then discarding the vehicle cache once per part of the vehicle current vehicle.
There was a time when vehicle pileups caused considerable lag during mapgen (now there is a hard limit on pileup size), so I'd be wary of doing it uncached.

> I'm also not clear what mapgen needs other than the getters and setters to the underlying data.

Currently (not ideally) it requires some behaviors which could be replicated with public setters alone.
For example, `place_vending`, `make_rubble`, `place_toilet`, `place_gas_pump`.
Those are useless outside mapgen.

> I don't understand the cache_map vs viewer_map distinction, it looks like it seperates the cache data from the cache update logic, but that's the last thing we want to do.

The idea was that `cache_map` does the caching (and answers queries about caches), while `viewer_map` can handle things like dirtying the cache because the view moved or because someone requested a redraw.
`cache_map` by itself would not implement any behavior that doesn't relate purely to cache creation, getting the cache, or dirtying the cache.
`viewer_map` could draw things on the screen (possibly things not cached yet, triggering calculation), request vision data, supply vision arguments (boomered player, weather) etc. Looking through binoculars and map memory could use that.

It's not necessary, I just think that the idea of having a separate structure to handle cache building, but without any behaviors not directly related to cache itself, would be more hygienic.

**Comment by kevingranade** [comment]
> This is comparable to creating and then discarding the vehicle cache once per part of the vehicle current vehicle

I'm deeply skeptical that building the vehicle cache is remotely similar in cost to doing a single uncached vehicle lookup. 
A typical map area doesn't have any vehicles, so it's free. A map area that contains vehicles and only places one vehicle will still not invoke any overhead due to the check being O(1) (short-circuit upon noticing that the vehicle list is empty).  Yes its expensive to place a second and subsequent vehicle, but it's unclear it's expensive enough to outweigh the majority of cases, which become more expensive if you do add caching.
Most importantly, this is textbook premature optimization, *you are adding complexity to your design based on speculation about code behavior*.

> Currently (not ideally) it requires some behaviors which could be replicated with public setters alone.

This doesn't scan, did you mean behaviors which *cannot be replicated with public setters? In which case, add the setters, that's far more straightforward than a specialized map subclass that embeds mapgen logic.

> viewer_map can handle things like dirtying the cache because the view moved or because someone requested a redraw.

I think I follow now, this is a proper view object into the underlying data, sounds reasonable. With this behavior being split into it's own class, it becomes possible to make a curses and SDL specific version, which could have good effects on draw performance.

**Comment by Coolthulhu** [comment]
> Most importantly, this is textbook premature optimization, you are adding complexity to your design based on speculation about code behavior.

The example with expensive wreckage building is pretty comparable to this. I could chalk up an example of "brute force `veh_at`" to show it if necessary (I might just be wrong, but I doubt it), but I'm pretty sure it would show a few second chug when generating big pileups.

> This doesn't scan, did you mean behaviors which cannot be replicated with public setters?

No, I mean mapgen logic currently embedded in map class. I want the basic map writer not to have that, to make `game_map` lighter.
For example, you can place a gas pump like this:
```
map.place_gas_pump( x, y, charges );
```
Or like this:
```
item gas("gasoline", 0);
gas.charges = charges;
map.add_item(x, y, gas);
map.ter_set(x, y, t_gas_pump);
```
Both of those methods use only public methods of `map` class and so could be moved to a non-member function, just that a new class would be less effort up front, while not actually blocking migration to non-member function.

**Comment by BevapDin** [comment]
> There was a time when vehicle pileups caused considerable lag during mapgen (now there is a hard limit on pileup size), so I'd be wary of doing it uncached.

Pileup doesn't use the vehicle cache much. The pileup that caused the lag simply created and merged several vehicles together, including calls to `vehicle::install_part` (which calls `vehicle::refresh` each time). Merging vehicles is probably the inefficient part. 

`map::add_vehicle_to_map` does one call to `veh_at` for each part of the newly added vehicle, *until* it encounters a part that overlaps with another vehicle. Than it just merges the two vehicles without any further map lookup.

> For example,  place_vending ,  make_rubble ,  place_toilet ,  place_gas_pump .

Those can all be implemented as free functions in mapgen.cpp or mapgen_functions.cpp. They don't need to be in any map class.

> I mean mapgen logic currently embedded in map class.

Move it into free functions. There is no need to make those class members (of any specific class). There are already free functions like that at the end of "mapgen.cpp" and "mapgen_functions.cpp".

**Comment by kevingranade** [comment]
Refactor as a whole seems to be stalked.
