### ISSUE TITLE
Add local anesthetics

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#22301]
Greetings dear survivors,
I am a doctor, which does not much to the whole point but my idea comes from the workfield itself (my English is not the best, so bear with me). Since CBMs now need proper painkilling, it would be a good idea to add local anesthetic like the -caine group (Lidocaine, Procaine, [Cocaine]). Which can be applied via syrringe into the bodypart of your choice (hand, arm, leg, foot, head, torso), which makes it "numb" [effects viawable via @ menu?]. So you can install those CBMs without overdosing on those full body painkillers.

MD or first aid (2 or 3?) should be needed, so you have an idea on how to apply it under your skin.

What do you think about it? (This is my first "idea" hear on github, so also bear that in mind).

**Comment by Theundyingcode** [comment]
I really like the idea.  Implementing it would be fairly complicated though. Adding the actual items is easy but the pain and probably some other mechanics would have to be completely re-written.

Some thoughts that came to mind:

- How would the pain level be affected by -caineing a injured limb? Speed of pain relief? Effect of injecting foot vs. leg? What about pain once the drug wears off?

- Dex penalty for injecting hands? I guess having numbness increase encumbrance would actually work pretty well to simulate the effects of not feeling.

- If you injected your foot and stood in acid would you notice? What about getting shot in a numb part?  numbing the part should blank out its health indicator.

- Some actions require feeling to do for example, lockpicking is a completely tactile exercise.  Logically you shouldn't be able to do it with numb hands.

- What about a partial implementation? Having them would meet the painkiller requirement for CBM installation but they are unusable outside surgery.  This addresses the ODing on painkillers point and eliminates the need to rewrite tons of mechanics.  Perhaps adding them as some form of surgery kit containing a complete set of surgeon's instruments and loaded with charges of anesthetic?

**Comment by Lamandus** [comment]
- Usually injured limbs are not that affected by local anesthetics, since they only affect a very narrow spot and very superficial at that. Pain ingame is the sum of all parts. So I would leave the actual painsystem as it is for now.
- injecting those into your hand, usually is not adviced, and you have to put some in every finger. This should be neglectible. As I said, LAs are injected superficially, deep sensory feelings (vibration, temperature, "rough feeling") are still active. IF some debuffs are wished, those for frostbites can be used actually
- As above. LAs only on skin or upper muscular parts, you still feel the bullet it. Acid however, depends on how global you inject yourself, and how "deep" this acid can go.
- as above.
- this is not a bad idea at all. 

Plus: LAs can be used to cauterise a wound painlessly. Maybe over a new menupoint for the knife: "numb and cauterise" where you loose one "shot" of anasthetics. It takes about 4-5 min until it has its full potential, but we can neglet it.

**Comment by Coolthulhu** [comment]
Current pain implementation system does not understand pain per body part (all pain is identical), so the partial implementation is the only one that would work well here.

**Comment by Lamandus** [comment]
> Current pain implementation system does not understand pain per body part (all pain is identical), so the partial implementation is the only one that would work well here.

I wouldn't mind it at all, since I would use the system just for CBMs or cauterising. By negating the pain effect of cauterising and removing the threshold for CBM installations.

**Comment by Theundyingcode** [comment]
Didn't think about cauterisation... I like the specific use implementation.  We can just say the process of numbing something takes 4 or 5min and add that to the time of cauterization/ installation.

Adding a new numb effect will also be really easy if it's just a case of copy/pasting frostbite and changing the text.  How long do LAs last? (Either as a global average or in reference to a few usage levels (think burn degrees))

**Comment by Lamandus** [comment]
if we averange those and don't take the dose too much into account, it will fade off after 1-3 hours. So if we use 2 hours until it fades off completly is a good compromise. "Feeling" will come back after an hour.

**Comment by kevingranade** [comment]
> "Feeling" will come back after an hour.

At which point the pain will as well, in addition to any immediate effects of LA, we'd need a system for handling deferred pain.

**Comment by Lamandus** [comment]
yes, would work, too. But like I said, if we would make it "my way", I wouldn't even touch the pain system all along, since the area of effect of LAs is relativily small. It would matter in CBMs and cauterisation, maybe if there will be a "stitch up wound" option, as well. But else? neglectable.

**Comment by Coolthulhu** [comment]
Consuming the LA immediately on CBM installation attempt and then applying a mid-term penalty for using them would be both simple and effective.
CBMs don't cause pain on installation, so there is no need to handle pain there.
While it could be expected to use one dose of LA for multiple CBMs, the whole idea of mass-installing CBMs at once is just a technical quirk, not the proper representation.

**Comment by Lamandus** [comment]
> While it could be expected to use one dose of LA for multiple CBMs
well, one dose of LA actually affect a area of around 10x10 cm at best. So it is realistic to use one shot per install.

**Comment by Lamandus** [comment]
I read some medical papers, Lidocain is one of the most used LAs in the US (which is where the game is after all), so we can restrict ourselves to two. Lidocain and Cocaine. Cocaine is a very potent LA but also has mindnumbing effects even as LA (not as strong as snorring, but still strong) and is addictive, while Lidocain is the "safe" bet, with no CNS effects (dangerous only when injected in the blood directly, but that is something we don't need to consider here).

**Comment by kevingranade** [comment]
The basis for this has been removed, there is no generic painkiller requirement for CBM installation.
