### ISSUE TITLE
Re-layer armor/clothing menu item duping/transmutation??

### ISSUE THREAD

**Issue by fizzle7** [CleverRaven/Cataclysm-DDA#22327]
I've just downloaded this game, a few hours ago, so I have no idea how to accurately search for issues. As a result, this might already be posted or I might be explaining it badly so request further information if you need it.
I'm using the CDDA Game Launcher version 1.3.10 

Game version: 0.C-24804-gefa9e57 (tiles)
Build: 6903

Operating system: Win 10

Tiles or curses: No idea how to find this, it came with tiles from the launcher, but I have no idea which tileset.

Mods active: 

- Dark Days Ahead
- Craftable Gun Pack
- Bright Nights
- Bionics Systems Mod
- Extended Realistic Guns
- Makeshift Items Mod
- More Survival Tools
- More Buildings
- More Locations
- Tall Buildings
- Urban Development
- Folding Parts Pack
- Vehicle Additions Pack
- Tanks and Other Vehicles
- Classes and Scenarios Mod
- Classic Roguelike Classes
- StatsThroughSkills

### Expected behavior
In the Re-layer armor/clothing menu with a bindle and fresh spawn Missing scenario clothes. Bindle was crafted from parts around. I had a shirt and a winter coat on me with the bindle on the right arm and I selected the bindle to move it around while focused on the right arm tab. As I moved it to last (lowest in the menu) then pressed down again, it should have rolled back to first I suppose or stayed as last, but it didn't.

### Actual behavior
The bindle began consuming all my clothing on that arm and overwriting it with a copy of itself so I ended up with all bindles on that arm, but it didn't stop there. I kept down arrow pressed and it instantly ate all my clothing in all slots and transmuted it into bindles on that arm. The bindles are fully functional and increase my inventory volume/decrease when removed; can be disassembled allowing you to use the rags to make gloves to then transmute more bindles into existence leaving me with a net heavy stick.

Also works with briefcase, haven't tested more. Not sure about non-container clothing, didn't work for gloves. Doesn't work if you don't have any other clothing, and also doesn't work on itself (rather, it probably does but since it just consumes a bindle to create a new one, I don't see any difference because the bindles are all copies).

*As a side note, for some reason I couldn't equip a briefcase or bindle on the other arm, it doesn't let me wear it, I can only do it on one arm, no matter what is equipped on the other arm's strapped slot. Which I understand is not how it should work but I'm not sure...

**Comment by Chezzo** [comment]
I am having trouble reproducing this. 

I go to the armor layers screen with +, then I scroll to select bindle, and hit c to change sides. Then I hit s to move the armor down, and it goes over the top normally. 

I must be doing something wrong because I don't see the bug.

**Comment by laeaton2001** [comment]
I've been able to recreate this on my local build now.

**Comment by laeaton2001** [comment]
probably came from #22280, only seems to happen in the individual lists & not the all list.

**Comment by fizzle7** [comment]
> I am having trouble reproducing this.
> 
> I go to the armor layers screen with +, then I scroll to select bindle, and hit c to change sides. Then I hit s and scroll to move the armor down, and it goes over the top normally.
> 
> I must be doing something wrong because I don't see the bug.

Not sure. Try with full clothing on then equip the bindle/briefcase and then try s on them and scrolling up and down.
