### ISSUE TITLE
Not quite sure if this is the right place, but here's a Martial Art Suggestion for Medieval Euro-style swords.

### ISSUE THREAD

**Issue by Serialkillerwhale** [CleverRaven/Cataclysm-DDA#22322]
Kunst des Fechtens, the "Art of Fencing" (Note: Not really the modern definition of fencing, it's a style centered around longswords and their use). Is a German style of Swordsmanship originating from the 14th-century Master, Johannes Liechtenauer.

Playstyle: Powerful defenses, high damage output. Primary weaknesses include reliance on having a Broadsword or Zweihander (possibly in addition to a new "Bastard Sword" or "Longsword weapon). Less mobile and slower (in direct comparison with Niten Ichi-Ryu), and of course, not being folded a million times.

Abilities:

Static Buff: Vom Tag: You hold your sword in a proper guard position, increasing the number and effectiveness of your blocks. 

Wrath-hew: A powerful diagonal strike. Slightly slower, but markedly more powerful than a normal attack. Generally 1.2x as much damage as a Flowing Water Cut. (Once it gets nerfed out of ridiculousness that is)

Murder-hew: Grasp your weapon by the blade, slamming the crossguard into your opponent. Stuns them while dealing high damage. Critical Attack that stuns for 3s.

Part-hew: A powerful overhand strike aimed at an oppponent's head. Devastating Critical Attack.

Counter-hew: After blocking, imediately follow up with a quick, effective strike with your blade.

Half-Sword: A quick impaling strike where you hold your sword as a short spear.

Longsword Bind: Disarm your opponent and down them with a rapid attack.

**Comment by Noctifer-de-Mortem** [comment]
There's already a Medieval Swordsmanship style in the Medieval and Historical Content mod.

**Comment by Serialkillerwhale** [comment]
There is? My bad then.

**Comment by Noctifer-de-Mortem** [comment]
It comes with the game. It goes by the name.

**Comment by Serialkillerwhale** [comment]
I don't have it on mine? It says it's an obsolete mod.

**Comment by Night-Pryanik** [comment]
Medieval and Historical Content mod is in Default tab, Item Addition category. Closing.
