### ISSUE TITLE
Recipe for making lye powder from charcoal missing

### ISSUE THREAD

**Issue by Divreus** [CleverRaven/Cataclysm-DDA#22323]
Game version:
6901
Operating system:
Windows 7 SP1 64-bit
Tiles or curses:
Tiles
Mods active:
Filthy Clothing, Disable NPC Needs, Simplified Nutrition
### Expected behavior
With the appropriate cooking skill level and and having read adv_chemistry, textbook_chemistry, or recipe_labchem, a recipe for lye_powder that uses 50 charcoal and 2 water(_clean) should appear in the crafting menu.
### Actual behavior
It does not. The only recipe available is the one added in #22218 that uses 40 lye. The missing recipe is also absent from the books it is supposed to be learned from
### Steps to reproduce the behavior
Meet the requirements for the missing recipe, have one of the three books on hand, and check the crafting menu,
Or just check the descriptions of adv_chemistry, textbook_chemistry, or recipe_labchem.

**Comment by Lorith** [comment]
Looks like it is due to missing an "id_suffix": "something", field leading to one overwriting the other.
