### ISSUE TITLE
Crafting UI ingredient list not scrolling

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#22337]
Game version: 0.C-24656-g4ae21c8

Operating system: Win7 / Win10

Tiles or curses: both

Mods active: no mods

### Expected behavior
Some kind of hotkeys that allow you to scroll ingredient list down and up.

### Actual behavior
Only "v (more)" marker shown at the bottom of incomplete ingredient list, but can't be scrolled down to see more. Tried all keys I can expect for that - < > + - PgUp PgDown Home End [ ], nothing works. And nothing about that found in keybindings menu. Also tried unbinding existing binds for PgUp and PgDown, still no luck.

![image](https://user-images.githubusercontent.com/2535519/32367074-e0ec4b92-c091-11e7-9c00-4d283bd906c7.png)

**Comment by Night-Pryanik** [comment]
m is for more.

**Comment by Xelat84** [comment]
> m is for more.

It's not. [m] for changing display mode, not showing more.

**Comment by Night-Pryanik** [comment]
Pressing m will change what to show and will display other ingredients. Though I must admit that it won't show too big ingredients' list.

**Comment by ituluwituluwzev** [comment]
I suggest it should just display "[m]ore".

**Comment by Xelat84** [comment]
> I suggest it should just display "[m]ore".

Nope.

There need to be implemented some functionality. It's pretty simple, just add two hotkey bindings, and a single variable for scrolling position, few lines of code to apply offset.
I probably will write fix by my own in a few days, if I have time to. But would be appreciated if someone did it earlier.

**Comment by Leland** [comment]
Likely a duplicate of #19685, which (if so), should be moved to a generic issue, rather than a macOS-specific one.
