### ISSUE TITLE
Cannot put out a fire on barriers using water

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#22335]
Game version: master
It says "You can't pour there!" :(

**Comment by Broken-Admin** [comment]
Um. What. Just smash the fence then put water on the ground.

**Comment by l29ah** [comment]
Well, it's the same with building walls that can't be smashed w/o special tools.

**Comment by ituluwituluwzev** [comment]
One can't put out a fire burning a tree, because one can't pour water onto a tree. There seems to be no easy fix, unless liquid is able to occupy the same tile with these terrains.

**Comment by Theundyingcode** [comment]
maybe an `iexamine` function for "splash burning _____ with water?"  (I'm assuming that's where it would go...)  That way you're executing the action "try to put out fire using water." rather than "put water there and it should counter the fire."

**Comment by Night-Pryanik** [comment]
By the way, water poured on the fire isn't extinguishing it. It's just fire itself fades out on tile with water.
