### ISSUE TITLE
Crash after open smart inventory on the same tile where it was

### ISSUE THREAD

**Issue by vabriz** [CleverRaven/Cataclysm-DDA#22348]
Game version:
6907
Operating system:
OSX
Tiles or curses:
Tiles
Mods active:
Dark Days Ahead
Filthy Clothing
Disable NPC Needs
Simplified Nutrition
### Expected behavior
Open selected tile in smart inventory
### Actual behavior
Crashes
### Steps to reproduce the behavior
Open the same tile in smart inventory two times

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.C-7143, Windows XP SP3 x86. Maybe I'm doing something wrong while testing though, as steps to reproduce are very unclear. Closing for now. If this still an issue, ping me.
