### ISSUE TITLE
Tear gas is too lethal.

### ISSUE THREAD

**Issue by Bejofo** [CleverRaven/Cataclysm-DDA#22346]
As the title states, tear gas is too lethal. Prolonged contact with tear gas caused my character to keep coughing long after the actually inhaling it. Despite using an oxygen tank and a first aid kit my character still coughed to death.

**Comment by kevingranade** [comment]
Not enough detail, how much exposure, how damaged were you beforehand, what are you basing your deadlines estimate On?

**Comment by Bejofo** [comment]
Admittedly I inhaled a lot of tear gas. I guess I spent around 12 turns in tear gas. I was at near full health when it happened.  I think tear gas should be cured by using an oxygen tank. I started a new character, debugged spawn a tear gas grenade and stood in it for 12 turns. I started with 84 health and it dropped to 33. I feel like this is a absurd amount of damage. Being blinded and losing stamina is enough of a penalty. I suggest replacing the damage with pain.

**Comment by AncientSion** [comment]
One turn is 6 seconds, so you did breath in tear gas for about a minute. 
I can see how that might hurt, but would is actually "damage" or kill you in real life ?
Tear gas is usually used to immobilize, break down or knock out opposition, but its not deadly (i think).
I feel like tear gas should induce vast amounts of pain over the course of a minute, probably even stun or unconsciousness. But actual health damage ?

**Comment by kevingranade** [comment]
So tons of exposure, so it's not that it's acting way too fast, just that it's causing damage at all.
Tear gas isn't non-lethal, or rather non-leathal as used by the weapons industry doesn't mean what most people think it does.  If you look up lethality reports for tear gas, they tested on animal subjects to the point where the subjects died.  The exposure level for death was high in those tests compared to what's outlined here, so I can see making it take a lot longer for death to occur, but making it truly incapable of killing the player isn't an option.

**Comment by Podesta** [comment]
The problem with teargas is that it is far too deadly right now, while it should be more debilitating instead.  If you stay 10 turn (1 minute) in the smoke you'll be suffering from it for the next 200 turns (20 minutes), and coughing and potentially taking damage every third turn.

To make matters worse, there is no limit to how much teargas effect you can get, so if you are inside a building, blind, and don't find the exit very quickly you'll essentially see your character die in the next couple hours from coughing while you can do absolutely nothing.

What I propose is make the stats effects worse, like seriously debilitating, impose a limit on much teargas effect you can stack, and make the coughing less frequent, so you don't die from it. Essentially, it wouldn't be a nerf, simply a change from deadly to extremely impairing weapon.

**Comment by jeremyshannon** [comment]
This bug is much worse now that healing items no longer add HP back instantly. Getting hit with tear gas from a riot control bot is a death sentence.

**Comment by jeremyshannon** [comment]
It should probably be possible to clear the tear gas effect with an emergency oxygen pack, too, but in debug testing five charges worth had no effect.

**Comment by kevingranade** [comment]
Fixed by #27938
