### ISSUE TITLE
Forums are down

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#22340]
Any attempt to get to a forums page is giving me this:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@smf.cataclysmdda.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by Treah** [comment]
Inform the admin via the email link. This issue tracker is for the game code not the web page unfortunately. Making an issue here wont do much.
