### ISSUE TITLE
Unnatural map gen with buildings in roads and such

### ISSUE THREAD

**Issue by Voqar** [CleverRaven/Cataclysm-DDA#22358]
Game version:
0.C-24831-g6a32f4f
Operating system:
Win10 64
Tiles or curses:
Tiles (MShock32Modded)
Mods active:
Vehicle Addtions Pack, Filthy Clothing, Prevent Zombie Revivication, Simplified Nutrition
### Expected behavior
Map gen was far more natural 1-2 weeks ago and forever before
### Actual behavior
As of week or so ago and continuing in latest build, buildings are unnaturally lumped together at times and/or in the middle of roads, leading to some very odd road networks in cities compared to the past.
### Steps to reproduce the behavior
Create world, load in, view map.  Suicide and repeat a few times to see constency in oddness.

Examples:
![image](https://user-images.githubusercontent.com/33404851/32420761-c746677e-c24c-11e7-953d-2a9f2f01a5ea.png)

**Comment by Leland** [comment]
Can confirm

**Comment by Treah** [comment]
I can also confirm this too. I had a orchard spawn in the middle of a road in a city..

**Comment by Voqar** [comment]
As a dev myself, I suggest some kind of code review to prevent breaking that which has worked for years with new changes.  Seems to be too many contributors here pushing whatever with little quality control or regard to bugs.

**Comment by Treah** [comment]
@Voqar 
In theory that sounds great and even I would recommend it, however since I do contribute here to the code  I can say things like this are going to crop up. Code is reviewed before its merged into the game but some unforeseen things can happen. Some of this has to do with part of the code for things being in json and some of it still hard coded in. Interactions are not always apparent however so it can be almost impossible to know that one thing will cause problems with others.

**Comment by Voqar** [comment]
Is map gen ever going to be fixed?  The map is a core part of the game and having buildings in the middle of roads is kind of a game breaker, for me at least - I can't enjoy cities that are jumbled messes - not when they used to be perfect.  It didn't used to be this way.  I don't get why a change that breaks a core element of the game wasn't removed and/or why it hasn't been fixed in weeks.

I'm a developer myself (just not game and/or c/c++ or I'd take a stab at fixing this) and it's not all that complicated to figure out - hey, code worked here, X was added, and then code stopped working - do something about X.

When I look thru the list of issues a LOT of them are trivial at best and a lot of them aren't even issues.

But I can understand why people would post here since I haven't been able to login to the official forums for a year+ and THAT issue never gets resolved either.

**Comment by Leland** [comment]
> hey, code worked here, X was added, and then code stopped working - do something about X.

Assistance with a git bisect to figure out what X is would be a great way to contribute

> since I haven't been able to login to the official forums for a year+ and THAT issue never gets resolved either.

A new forum was launched, actually: https://discourse.cataclysmdda.org. Give it a shot.

**Comment by Voqar** [comment]
My point is, the whole point of "experimental" is that experiments can fail, and when they do, REMOVE THEM.  I don't do c++ but I do code and generally speaking, in any serious coding environment, you don't let broken code stand.  You either figure out it's broken and remove it or you fix it.  And I already work 50-60 hours a week in a high pressure environment, as much as I'd like to learn enough c++ to fix someone else's map gen bugs that should never have been allowed to stand, it's not happening.

Map gen has been broken for weeks now.  It used to work beautifully.  We didn't used to have buildings in the middle of roads and broken cities.  I start new runs of the latest experimental regularly and while cool stuff gets added constantly, there is nothing so cool that it's worth having broken map gen vs whatever new thing was added.

Whatever broke map gen should've been removed or fixed shortly after it was added, not left to linger for weeks.  Experiment failed.  Experiment removed.

**Comment by kevingranade** [comment]
Most likely candidate is #21527.  The new use of the special placement code
may not be taking roads into account properly.

Re: complaints about experimental status.
It will be fixed when someone gets around to it.

**Comment by codemime** [comment]
> It will be fixed when someone gets around to it.

It turned out to be me: the fix is on the way.
