### ISSUE TITLE
Moving carts between floors suggestion

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#22352]
I want to suggest a relatively simple solution how move carts between floors.
Put cart on a ladder tile, go to other floor, stay beside with ladder tile and then `grab` tile with ladder. Game checks if there is any single-tile cart vehicle on connected ladder tiles on other floors and if so - ask player if he want to pull that cart on current floor (as it will take some move points), and then cart appear on a tile you tried to `grab`. Of course it will check only one floor depth. May be it should require some ropes in player inventory. Also still should check for ability to move that cart depending on player stats (`strength` for example).

It should be not too hard to code. May be one day I will even try to implement it by myself.

What would you say about that idea? Because I think there definitely should be a way to move items in a bunch between floors, as manually moving them through player inventory is too boring and time consuming. And creating new cart on each floor is also seems nonsense.

**Comment by kevingranade** [comment]
That does require the player to be capable of deadlifting the cart and it's contents, seems unlikely in most cases.  In particular seems likely to lead to a lot of complaints about players being unable to do it.

Alternative, buildable dumbwaiter, in essence it's a box suspended from a pulley by a rope with a counterweight.

**Comment by Xelat84** [comment]
> Alternative, buildable dumbwaiter, in essence it's a box suspended from a pulley by a rope with a counterweight.

I like the idea. Even counterweight is not necessary, set of pulleys capable to lift almost any weight (within reasonable limits), just matter of time.
Even better, how about wooden rails that you lay on stairs, along with set of pulleys. No need to exactly lift cargo straight up, you can pull it up by stairs using rails, it's pretty enough.

I will think how exactly implement it.
For now I see that implementation:

- Craftable item `Pulley`.
- You can attach that `Pulley` as a vehicle part to your cart.
- You can construct (from construction menu) a standalone `pulley with rails` near stairs (or exactly on stairs tile). It will require say `4 of 2x4, 20 nails and pulley itself`.
- To pull your cart up/down, you need to keep `long rope` in your inventory and examine (interact with) constructed `pulley with rails`.

So code will check if your cart has that `pulley` vehicle part, and if so allow you to pull that cart.

The only thing left to decide is where exactly to construct `pulley with rails` and where to spawn your cart when you finish. And is it possible to construct things above stairs tiles?

What do you think? May be omit rails, and keep only requirement is to have `pulley` vehicle part attached to cart along with keeping another `pulley` and `long rope` in your inventory? And not constructing anything?

**Comment by Treah** [comment]
Could also add build able ramps that you could dig out of the surface. However that would only work with player built stuff.

**Comment by Night-Pryanik** [comment]
No discussion in more than a year, closing.
