### ISSUE TITLE
Types of town centers

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#22369]
Town centers could be given types or id flags and related spawn lists of buildings/specials. It's sort of like this now for residential neighborhoods and downtowns, but I was thinking of something more generic and JSONized. 

With spawn lists you could have clusters of buildings with a tight theme, like military bases, college campuses, trailer parks, resorts, factories, etc. Some things in the game now--like farms, ranches, and orchards--would be better represented by groups of buildings and fields rather than single large overmap specials.

That might help make overmap tiles less homogenous. Right now specials are added to any/every overmap tile, but with a this they would only appear with the appropriately flagged center. So things like airfields, control towers, and hangars would only spawn in 'airport' flagged center. Then you could adjust the rates of those centers spawning instead of the rates of the specials themselves. They wouldn't compete for space with megastores, hospitals, etc. 

It would take additional mapgen for things like road gates and fences, though.  Also some might be better 'dead ends' with just one connecting road, so you don't have to drive through a restricted military base just to get to the town on the other side.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
