### ISSUE TITLE
smf.cataclysmdda.com is down

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#22365]
Site [http://smf.cataclysmdda.com/](http://smf.cataclysmdda.com/):
```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@smf.cataclysmdda.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by BrettDong** [comment]
Paging @Chezzo

**Comment by DanmakuDan** [comment]
I think Chezzo only has the wiki and item browser. Kevin is supposed to have server access to the forum through GlyphGryph. If he can get access working again, maybe we can migrate the forum to another server?

**Comment by kevingranade** [comment]
I'm looking into it, I currently do not have access.

**Comment by kevingranade** [comment]
Status update:
* GlyphGryph is still the owner of the host (but he doesn't want to be bothered with it, which is fair, he volunteered to maintain the forums for years with basically no recognition for it).
* I have retrieved the login credentials I need to address the issue. (My fault that I didn't have these, not GlyphGryph's).
  *  Plan A: I've secured hosting on discourse, and will try and import the forum history there, it will be migrating to discourse.cataclysmdda.org (note the .org). I have a discourse instance running, I just need to run the import workflow, which is supposedly pretty reliable, but time-consuming.
  *  Plan B: Get smf.cataclysmdda.com running again. (temporary solution, AFAIK this hosting WILL be going away in March of next year)
  *  Plan C: Migrate smf.cataclysmdda.com to a new host. People have randomly offered hosting, might take them up on it, but I'd prefer discourse. 

Another update:
I've poked at the forums and have no idea what's wrong. The database looks healthy, the php code doesn't look corrupt, and there are no strange messages in the error log. I can't read the access logs, so I'm pretty much out of troubleshooting options.

I'm following up on plan A though, migrating to a discourse instance.

**Comment by kevingranade** [comment]
I have the database from the forums imported into a discourse instance and created a backup from it.

I've also secured discourse hosting but now I need to wait for discourse staff to apply the backup to the new instance. http://discourse.cataclysmdda.org is live, but has no contents, and anything added to it will be replaced by the restore process.

**Comment by ituluwituluwzev** [comment]
Does one make a new account or use the old one?

**Comment by RaaaGEE** [comment]
@ituluwituluwzev if discourse stuff make full convert forum database to new forum - you can use old account

**Comment by ituluwituluwzev** [comment]
Thanks! That's good.

**Comment by kevingranade** [comment]
http://discourse.cataclysmdda.org is now live!

Looks like it might not have imported passwords (or ossibly just not in all cases?), but on the other hand the email password reset workflow does work, so you should be able to retrieve your account that way.
