### ISSUE TITLE
(a)ctivate item menu too cluttered books/food

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#22374]
I play with a static base which means everything I loot ends up within a 3x3 tile chunk of floor space (for the most part).  As a result my item activation menu gets pretty cluttered:
![image](https://user-images.githubusercontent.com/15700895/32471710-5590c1d2-c324-11e7-9c9a-2489fc2f39ef.png)
![image](https://user-images.githubusercontent.com/15700895/32471720-60b53eee-c324-11e7-8051-c7b1c971c104.png)
and, that's only day 4.

Books have there own (r)ead menu so they can be cut out of the (a)ctivate menu with no problems.  Similarly,  everything with the "consume" or "drink" action (food and drink) can be cut since there is an (e)at menu.

Medicine/drugs are  kinda wishy-washy on whether they get "used" or "eaten." (their action is "take") so, they should stay at least for now.

**Comment by pisskop** [comment]
Absolutely too cluttered.

And randomly shows what you wear in addition to what you have on your person.
And is generally such a pain in a Late Game car that I actually step outside to eat.

**Comment by Leland** [comment]
Relevant PR: #19367.

One way to look at this is that the <kbd>a</kbd>ctivate/Use Item menu is used as a catch-all for all surrounding items regardless of whether they have their own menus or not. The fact that it's cluttered when triggered in a large stockpile would just come with the territory.

Another thing to note is that there is now a filter (activatable by <kbd>/</kbd>) which landed recently.

**Comment by Theundyingcode** [comment]
> Item menu is used as a catch-all for all surrounding items 

Having a catch-all menu isn't a bad thing however, in that case, I would still want a uncluttered use item menu as well.
