### ISSUE TITLE
Where can I find/make an error log?

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#22371]
### Background
So I am working on an expansion to the current vehicle location restriction. In short I an making anything marked with location "on_mount_point" to look in the square for a part with flag "MOUNT_POINT". I saw this in a TODO while working on PR #22144. 

### What I want
I would like to view a log of all debug messages created in a single execution of the game. I would like the information displayed in the `debugmsg` function to be displayed in said file, even if I click 'I' of 'i' to ignore the popup message displayed in-game. I would be fine if I had to manually reset the log output file to clear away the old logs.

### Question
Does this already exist or would I need to make this myself? If it is the latter then where can I find the implementation of the `debugmsg` so I can make this output file?

**Comment by vache** [comment]
I think there is a debug.log in /config.  Can't confirm at the moment though.

**Comment by angoddu** [comment]
Thank you. This file had the data I was looking for
