### ISSUE TITLE
NPC wears a splint on a wrong arm

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#22370]
Game version: master

I've given one an arm splint via "I want you to use this item" to fix his right arm, but he decided to wear it on his left one as seen in "I'd like to know a bit more".

**Comment by ituluwituluwzev** [comment]
When the player wears a splint, it goes to his left arm, too.

**Comment by angoddu** [comment]
I think it defaults to the left side for everything. From sheaths, to holsters, watches, to splints. I think that if encumbrance is the same I believe it will always default to the left side first. I haven't tested this personally but if I remember correctly I have noticed this on my characters.

**Comment by l29ah** [comment]
Okay it swaps the splint after some time, but if given another splint, it then wears it and swaps too, getting 140 encumbrance on the arm.

**Comment by angoddu** [comment]
Could you give steps to reproduce this error? It would help in the debug process

**Comment by Broken-Admin** [comment]
You can change the side it's worn on through the *Sort Armor* action when you *examine* the npc if I'm correct.
