### ISSUE TITLE
Suggestion about donations

### ISSUE THREAD

**Issue by Neversalimus** [CleverRaven/Cataclysm-DDA#22385]
Good day!

Wanted to know if this is possible to donate to the project, if it is possible than how to?

**Comment by Cyrano7** [comment]
A good way to donate is to put a bounty on fixing a specific issue or adding a certain game mechanic. You can do this at https://www.bountysource.com/teams/cataclysm-dda

**Comment by Neversalimus** [comment]
The suggestion than: add this information to the main pages on github and website. It was not obvious to me how to help the project, I think the same goes for other users.

**Comment by Cyrano7** [comment]
@Neversalimus IDK if we have a official stance on donations you would have to ping @kevingranade for that answer. I don't think the actual cost of things for the game is that high but I also don't know how much of that kickstarter money is left.

My personal suggestion is donating to @Chezzo patreon page https://www.patreon.com/user?u=2899966 He made the chesthole tilesets and hosts some of the sites. He does dam fine work.

**Comment by kevingranade** [comment]
Bountysource links are now present.
