### ISSUE TITLE
Anthills map generation is still broken

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#22393]
Game version:
0.C-24831-g6a32f4f
Operating system:
OSX
Tiles or curses:
curses
Mods active:
DDA, Disable NPC needs, folding parts, vehicle additions, tanks and other vehicles, disable religious texts, no antique firearms, stats thru skills and food preservation through ionizing radiation

Previous PR in June #21438 thought to have fixed anthill map generation so the different chambers (food, eggs, queen) are not disconnected from the tunnels.  Turns out, the problem still persists if a bit of different nature. Now there are always 2-3 tiles of stone between the end of a tunnel (very straight tunnel wall that is recognizable in the otherwise swirling tunnels) and the neighboring chamber. I'm attaching few screenshots of two massive anthills I explored before figuring out that having only tunnels is not the right thing to have. Last screenshot is after I spawned a clairvoyance artifact to check what's behind the tunnel wall. 

<img width="1054" alt="screen shot 2017-11-08 at 23 17 06" src="https://user-images.githubusercontent.com/25322782/32579195-542f3342-c4e0-11e7-96b3-4ca9dd28f272.png">

<img width="1056" alt="screen shot 2017-11-08 at 23 46 11" src="https://user-images.githubusercontent.com/25322782/32579194-5412d094-c4e0-11e7-987a-2c629da217d9.png">

**Comment by MysteriousConman** [comment]
Game version:
0.C-24923-g39ad053 (tiles)
OS: Windows 10
Mods Active: DDA, Vehicle additions; tanks, boats, folding parts

Can confirm, some isolated rooms are connected too.
![cataclysm-tiles_2017-11-08_17-01-24](https://user-images.githubusercontent.com/21067100/32579568-180c4b72-c4a7-11e7-948b-c38dd176a787.png)


(Map image)
![cataclysm-tiles_2017-11-08_17-03-22](https://user-images.githubusercontent.com/21067100/32579571-1b6bab14-c4a7-11e7-8daf-206285721771.png)

**Comment by atealein** [comment]
After walking around the anthill with clairvoyance I also can see pairs of isolated chambers that are connected between them too.

**Comment by BorkBorkGoesTheCode** [comment]
Anthill overmaps appear jittery when the camera moves past them in map mode just like last time.

**Comment by Night-Pryanik** [comment]
Can't confirm. Tested on latest experimental as of 06 April 2019. Visited several anthills (~10), all chambers were correctly connected to the tunnels. Closing until confirmed.
