### ISSUE TITLE
Display container fill level

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#22394]
When you look at a container, it's not obvious how much is actually in it.  Usually I can figure it out since a unit of standard drink is .25L and the waterskin can hold 3L.  However, hard alcohol and other liquids have different  units per volume.  Somewhere in the item examine page can we put something like (2.5/3L)?

![image](https://user-images.githubusercontent.com/15700895/32579546-ff406402-c4a6-11e7-8ec2-fb933dde776d.png)

Looking at it again, the units don't even show up in the detailed examination only in the overview.

**Comment by Treah** [comment]
I'm confused, it shows you the volume of the item in your description along with the potions...

**Comment by Zireael07** [comment]
@Treah: He is not asking the volume of the item, he is asking the volume of liquid that is stored inside.

**Comment by Treah** [comment]
@Zireael07 
Yeah for the water skin its not usefull but for other containers it could be. Thats why i expanded my description.

**Comment by Theundyingcode** [comment]
It's for things like how full is the tank i'm holding?
![image](https://user-images.githubusercontent.com/15700895/32687396-c5d982d0-c680-11e7-9a8c-3988643394d8.png)

**Comment by Karbine** [comment]
1/3rd. Fuel charges are measured in cc's, which translate to 1/1000th of a liter. New players shouldn't be required to know that.

Requiring the players to know the size of 1 portion of every liquid in the game to determine how full a plastic jug is is meta-game knowledge. A survivor should be able to tell roughly how full something is just by looking at a container or picking it up and sloshing it.

Glass Bottle of Clean Water (3/3) and Plastic Bottle of Water (500/500) would be more informative inventory names for containers than what we currently have. They tell the player "this container is full," "half full," etc., which the survivor would know.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
