### ISSUE TITLE
Savegame freezes

### ISSUE THREAD

**Issue by Elirector** [CleverRaven/Cataclysm-DDA#22398]
Game version: 0.C-24824-g2a3206a

Operating system: Windows 10 x64

Tiles or curses: curses

Mods active:  "dda",
  "no_npc_food",
  "novitamins",
  "bio_mod",
  "makeshift",
  "no_religious_Texts",
  "No_Acid_Zombies",
  "No_Fungi",
  "StatsThroughSkills"

### Expected behavior
Moving out of current tile

### Actual behavior
Game freezes on attempt to move in any allowable direction

### Steps to reproduce the behavior
Move to any direction.
[Фус.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1457949/default.zip)

**Comment by Zireael07** [comment]
Nice zip name :P

**Comment by Elirector** [comment]
Russian localization, sorry. Lots of cyrillic strings inside savegame files also.

**Comment by Zireael07** [comment]
I know it's Russian, I was laughing because unless my Cyrilic is way off, it says "fuk".

**Comment by BevapDin** [comment]
Well, it doesn't freeze for (Linux, curses). How did you manage to *embed* the Elirector into the wall? That seems to be a bug. The games apparently thinks your character is still on the seat of that vehicle.

**Comment by Elirector** [comment]
First I've tried to drag vehicle into the building. After collision with wall and door, I've changed my mind. After some time in a building, I tried to go out and that is the moment.

**Comment by codemime** [comment]
> Well, it doesn't freeze for (Linux, curses).

I'm seconding this, it doesn't (Linux, SDL). However, it plonks a debug message:
![debugmsg](https://user-images.githubusercontent.com/11905613/34749791-6d62a182-f5b4-11e7-855e-7331cb4705ad.png)

**Comment by Leland** [comment]
Closing due to lack of repro per above – if you want this kept open just ping me and we'll reopen.
