### ISSUE TITLE
Deployed Bionic Gun?

### ISSUE THREAD

**Issue by Serialkillerwhale** [CleverRaven/Cataclysm-DDA#22404]
As it is currently, ranged bionic weapons such as the Fusion Blaster Arm and Finger Laser are simply "Activate to fire" while melee weapons like the Monomolecular blade are deployed and retracted.

Would it be possible to create a bionic that, when activated, extends say, a shoulder or wrist mounted rocket launcher or some more powerful laser weapon that takes some time to "draw" out?

**Comment by Night-Pryanik** [comment]
No discussion in more than a half-year, closing.
