### ISSUE TITLE
Translation templates don't update on the Transifex

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#22407]
The last two translation template updates made by @BrettDong don't show up on the Transifex.

**Comment by BrettDong** [comment]
![auto-update-resource](https://user-images.githubusercontent.com/21075502/32656488-f37f1544-c64c-11e7-87b8-143fe67da380.png)
'Automatic update of source files' has been always enabled. I have no idea why it stopped working in recent two weeks. Anyway, I'm manually pushing the new template.

**Comment by Night-Pryanik** [comment]
It updated after a while.
