### ISSUE TITLE
2nd floor bedroom not accessible 

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#22409]
Well it is if you climb out the window onto the roof but not normally.  (not sure how to track to  house version)

![image](https://user-images.githubusercontent.com/15700895/32687112-b81ff864-c67a-11e7-8ce2-5bab1dfb26c5.png)

Map Editor View:
![image](https://user-images.githubusercontent.com/15700895/32687141-3e97e85c-c67b-11e7-89f0-a546186bbbfa.png)

First Floor Layout:
![image](https://user-images.githubusercontent.com/15700895/32687149-878c8be4-c67b-11e7-83ff-a55530af8e60.png)

**Comment by Leland** [comment]
@Theundyingcode couple questions: any mods active? Any possible steps to reproduce? And, a bit of a longshot, but any chance you have a save laying around with this issue?

**Comment by Theundyingcode** [comment]
It's actually possible I still have the save simply because I haven't opened cdda since I got back to school beginning of january... anyhow, I usually play with all the core building mods on.  Force matching up/down stares and z-levels always stays on...

don't really have any insights on reproducing, I guess I wrote this thinking that it would just be tracking down the json but 2nd floors are generated aren't they?

**Comment by AMurkin** [comment]
I think your map have generated bugged house, which was fixed in #22062.

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed.
