### ISSUE TITLE
Description for bone meal is misleading. 

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#22401]
The descritpion for bone meal is: 

https://github.com/CleverRaven/Cataclysm-DDA/blob/12f99651d8baeae9def910b6663133634350e8f7/data/json/items/comestibles.json#L6079

This as anyone would wrongly assume makes it sound like it can be used to fertilize plants, but it cannot be. 

It should be changed to something like 
" This bone meal is useful for making fertilizer and some other things." 

----

Edit by @Leland: moved to code embed

**Comment by Leland** [comment]
Note that chitin powder is the same:

https://github.com/CleverRaven/Cataclysm-DDA/blob/12f99651d8baeae9def910b6663133634350e8f7/data/json/items/comestibles.json#L6113

**Comment by rm-code** [comment]
@Treah I'd be up for a PR. What do you think about:
"This bone meal can be used to craft fertilizer and some other things."

**Comment by ituluwituluwzev** [comment]
@Leland The code embed looks good. How did you do that?

**Comment by rm-code** [comment]
@ituluwituluwzev Check https://github.com/blog/2415-introducing-embedded-code-snippets

**Comment by ituluwituluwzev** [comment]
Thanks!
