### ISSUE TITLE
Change Linux download link

### ISSUE THREAD

**Issue by Podesta** [CleverRaven/Cataclysm-DDA#22419]
As have been clarified here: [https://www.reddit.com/r/cataclysmdda/comments/6raijb/dropping_32bit_linux_experimentals/](url) Linux 32 builds are not being automatically being built anymore.

But the download link on the website still links to the 32 bit version. Perhaps it would be best to change the link from [http://dev.narc.ro/cataclysm/jenkins-latest/Linux/Tiles/](url) to [http://dev.narc.ro/cataclysm/jenkins-latest/Linux_x64/Tiles/](url) for both the terminal and tiles version.

**Comment by Soyweiser** [comment]
I saw we still had links to the 32 version on the wiki. No longer. Thanks for opening the issue Podesta.

(Doesn't solve the site issue btw).

**Comment by Leland** [comment]
Huh, didn't autoclose. Weird.
