### ISSUE TITLE
Vomiting and nausia shortly after game start, persisting through the entire game.

### ISSUE THREAD

**Issue by chaoko99** [CleverRaven/Cataclysm-DDA#22418]
Game version: 0.C 2601-gca85a31

Operating system: Windows 10

Tiles or curses: Chesthole (I assume this is tileset?)

Mods active: Medieval (But this occurs in vanilla as well.)

### Expected behavior
For this not to happen.

### Actual behavior
There's vomit everywhere. All day. Everyday.

### Steps to reproduce the behavior
Make a save. 
Do thing for one turn.
**Vomit.**
**Wretch.**
**Wretch.**
**Wretch.**
**Wretch.**

Repeat **literally ad nausium** until you encounter one spitter or any other kind of zombie for that matter, or the game just crashes.

**Comment by Leland** [comment]
Originally reported in #22200, might have been fixed by #22200. Can you try downloading the most recent experimental and see if this still occurs?

**Comment by chaoko99** [comment]
I can't read version numbers, apparently.

**Comment by Leland** [comment]
Big thumbs up for "literally ad nausium," however

**Comment by chaoko99** [comment]
I try my best.
