### ISSUE TITLE
See through all artifact allows me to see rot time of food in crafting menu?

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#22417]
Game version:
0.C-24831-g6a32f4f
Operating system:
OSX
Tiles or curses:
curses
Mods active:
DDA, Disable NPC needs, folding parts, vehicle additions, tanks and other vehicles, disable religious texts, no antique firearms, stats thru skills and food preservation through ionizing radiation

I found an artifact that has a passive "See through everything" effect. When I am in the crafting menu it lists all sort of additional (hidden?) values for food and other recipes. 

<img width="1061" alt="screen shot 2017-11-13 at 13 23 16" src="https://user-images.githubusercontent.com/25322782/32725652-3ae9b86e-c876-11e7-80e8-c4fe62b6e1a4.png">

**Comment by Soyweiser** [comment]
It probably lets you see a lot more. As this artifact is sort of the debug artifact now.

**Comment by atealein** [comment]
This is not a debug artifact, but an artifact looted in a temple and it has all sorts of other activated and wielded effects.

**Comment by Soyweiser** [comment]
Yes, I know, but they probably use the same effect. As in the looted artifact uses the same code as the debug one, which causes the problem. The question is, was this behaviour intentional? Or was it simply something nobody ever thought about because well, people looting temples are rare, and this effect is iirc even rarer. And the rarest of all is people supplying proper bug reports ;). (and of course all three, is rarer still).

**Comment by atealein** [comment]
I believe there was a recent change into the debug artifact actually, can't sure of the PR that made the change, but previously the clairvoyance artifacts spawned by the debug menu had a very specific item id and text. Now they look as any other artifact, except they have only one specific effect on them. And because of that the effect which before might have been a bit different, is the exact same as in the proper artifacts.

**Comment by Leland** [comment]
Perhaps fallout from #22273, which is the most recent PR to affect artifacts.

**Comment by Soyweiser** [comment]
That could very well be atealein, I myself never got a temple artifact. So you are the more experienced on that.

**Comment by atealein** [comment]
I think this type of effect can spawn in any artifact, i just meant to say it that it wasn't obtained through the debug menu, but found in the world.

**Comment by Soyweiser** [comment]
Ow yes, but if you think that you have seen non debug clairvoyance artifacts in the past, and this one you found has debug clairvoyance characteristics that is unexpected. If the debug artifacts have also changed unexpected, that gives a good lead to what the problem might be. But it was clear you found the artifact, and didn't debug it.

**Comment by atealein** [comment]
I've had experience with debug artifacts before, mostly because i kept spawning them in typos :D Recently I decided to clear them from my artifacts.gsav and noticed that the old entries are no longer found (as item id) anywhere in the save, but have been replaced by different type of cube artifacts with same effect [11] if i recall correctly, but those artifacts now had proper item id : 

Here is example how the old debug artifact looked like:

{"type":"artifact_tool","id":"clairvoyance_plus_rod","name":"clairvoyance rod","description":"Item to test aep_clairvoyance_plus flag. If this spawns randomly, then it's a bug.","sym":"v","color":512,"price":5000,"materials":["steel"],"volume":3,"weight":150,"melee_dam":1,"melee_cut":0,"m_to_hit":-1,"item_flags":[],"techniques":[],"ammo":"NULL","max_charges":0,"def_charges":0,"charges_per_use":0,"turns_per_charge":0,"revert_to":"null","charge_type":0,"effects_wielded":[38],"effects_activated":[],"effects_carried":[]}

new ones look like these:

{"type":"artifact_tool","id":"artifact_3450","name":"Cube of Fungal Graves","description":"The architect's cube.","sym":"*","color":2097408,"price":0,"materials":["steel"],"volume":2,"weight":951,"melee_dam":16,"melee_cut":0,"m_to_hit":-2,"item_flags":[],"techniques":[],"ammo":"NULL","max_charges":0,"def_charges":0,"charges_per_use":1,"turns_per_charge":0,"revert_to":"null","charge_type":0,"effects_wielded":[],"effects_activated":[],"effects_carried":[11]}

---- 

The artifact in question i found looks like this:

{"type":"artifact_tool","id":"artifact_3455","name":"Dagger of Shadowy Justice","description":"This is the Dagger of Shadowy Justice.\nIt is the only one of its kind.\nIt may have unknown powers; try activating them.","sym":";","color":2098176,"price":0,"materials":["steel"],"volume":1,"weight":161,"melee_dam":0,"melee_cut":0,"m_to_hit":0,"item_flags":["SHEATH_KNIFE"],"techniques":[],"ammo":"NULL","max_charges":9,"def_charges":9,"charges_per_use":1,"turns_per_charge":0,"revert_to":"null","charge_type":4,"effects_wielded":[15,24,38],"effects_activated":[14,4,25,27],"effects_carried":[11,20]}

so the "effect" [11] is definitely the same in the debug artifacts and in the normal game artifacts. I have no idea if it was like that before the changes, since I didn't have artifacts at that time.
