### ISSUE TITLE
Make website https

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#22424]
Follow guide here: https://www.goyllo.com/cloudflare-ssl-for-github-pages/
to flip github sites page to https.
Might need to register a cert with https://letsencrypt.org/ as part of the workflow.

**Comment by Leland** [comment]
The free CloudFlare SSL certificate is fine for the GitHub sites page as we aren't serving any data that needs encryption. If you're thinking of moving cataclysmdda.com to HTTPS, though, definitely go with a Letsencrypt cert. 

See: https://nickjanetakis.com/blog/lets-encrypt-vs-cloudflare-for-https

**Comment by kevingranade** [comment]
Thanks for the info, cataclysmdda.com is getting redirected to cataclysmdda.org at best, going dark at worst.

**Comment by kevingranade** [comment]
Partially adressed by #23053 
If I did the Cloudflare config correctly, it should flip to https as soon as DNS propogation completes.

**Comment by kevingranade** [comment]
Done woo!
