### ISSUE TITLE
Cotton boll -> cotton balls recipes produce too much cotton seeds

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#22428]
The two recipes (with and without carding paddles) should produce only 2 cotton seeds as by-product and that's what is written in the crafting screen as well. Right now it produces 16. After one season harvest of few cotton plants I now am the proud owner of 3470 cotton seeds..

**Comment by AMurkin** [comment]
Why they should produce only 2 cotton seeds?

**Comment by atealein** [comment]
Because quite literally that's what the crafting menu says they should.
<img width="1061" alt="screen shot 2017-11-15 at 13 21 19" src="https://user-images.githubusercontent.com/25322782/32835860-05d0708a-ca08-11e7-8f84-0f06bd880480.png">

**Comment by AMurkin** [comment]
Well, it's two items with id: "seed_cotton_boll". Which are created by charges equal 8. Set in comestibles.json.

**Comment by atealein** [comment]
Right, however there are few problems here:
1) I am not 100% sure (harvest was long time ago) but did you get seeds also directly from harvesting the cotton plant?
2) You get 16 seeds from 1 cotton boll. I harvested plant usually produces a bunch of those.
3) The only other thing cotton seed is good for except planting more cotton plants, is cooking oil. Current recipe makes cotton seed one of the MOST effective ways to make cooking oil from seeds - whereas you would need 4 pumpkin seeds, 2 sunflower, 4 canola or 6 cannabis seeds for 250 ml of cooking oil, you need only 1 cotton seed. I mean, I don't mind the thing, it just seems like exploding in exponential progression that I am not certain was the intended design.

**Comment by Mecares** [comment]
Those amounts are weirdly low creating 250ml of Oil out of a few grams of seeds seem quite unbalanced.

**Comment by BevapDin** [comment]
That's probably just a display error. In `print_items` in "crafting_gui.cpp", it prints byproducts with count multiplier (2 in this case) and the standard item name (which does not include the default charges). So it displays "2 cotton bolls" (where "cotton bolls" refers to an item with 8 charges).

Later the byproducts are created with their default charges. So this seems to be a display bug.
