### ISSUE TITLE
Migrate forums gracefuly

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#22434]
It turns out that smf.cataclysmdda.com was retrievable after all, so it's currently back up in read-only mode.

Going forward, it will remain in read-only mode indefinitely, and have topics posted redirecting to https://discourse.cataclysmdda.org

The host running smf.cataclysmdda.com (and en.cataclysmdda.com) is going down in March, so that is not a permanent solution.

My best option for a permanent solution is to use this project: https://github.com/pbackx/smfmapper to build a redirect table from the database export, and acquire hosting (VERY tiny hosting) for a Nginx redirect server to keep the smf links live and pointed at the corresponding pages of the discourse instance.  That will require redirecting the cataclysmdda.com domain to point at the redirect server, which probably isn't an issue.

**Comment by kevingranade** [comment]
The host smf.cataclysmdda.com is running on is due to go away next month, and i do not see having time to do this.
Please contact me if you are able to run this export process on a smf database dump (which I can provide).
Otherwise I'll settle for the fallback of redirecting smf.cataclysmdda.com to discourse.cataclysmdda.org.

**Comment by ZhilkinSerg** [comment]
Are we still need to have this issue opened?

smf.cataclysmdda.com is up and data was migrated to discourse.

**Comment by Night-Pryanik** [comment]
Pinging @kevingranade.
