### ISSUE TITLE
Armor damage absorption does not take layering into account

### ISSUE THREAD

**Issue by gcaliber** [CleverRaven/Cataclysm-DDA#22432]
Game version: 6929

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Defaults

### Expected behavior
If I am wearing an item with 100% coverage I expect items beneath it to not be damaged by combat unless the outermost item is also damaged.

### Actual behavior
Items beneath the outermost layer all have the same chance to be damaged. Wearing a 100% coverage survivor suit can still allow items such as boxers or bras to be damaged in combat which really does not make much sense. The way it is right now, undergarments often have a higher chance to be damaged than the items being worn on top of them.

### How to reproduce
Put on a survivor suit and go punch some zombies to death. Eventually items like shirts and boxers will be damaged and destroyed without the suit ever taking any damage.

**Comment by Theundyingcode** [comment]
I agree completely in regards to cutting and piercing dmg.  Bashing dmg should still be able to damage hard or formed items (i.e. the breastplate you're wearing under it) in the same way a sledge hammer can turn a hand into a pulp without destroying their gloves.

**Comment by kevingranade** [comment]
This is partially working as intended.

The problem is this: If the only options were the clothing blocking all
damage or taking damage, your clothing would shred almost immediately.

Instead each layer blocks some of the damage, has a chance to be damaged,
and the remaining damage continues to the next article of clothing.

However I'm getting the feeling this is being brought up because it's more
severe than it used to be.  Do you know when it started getting worse?

**Comment by Barhandar** [comment]
> Instead each layer blocks some of the damage, has a chance to be damaged, and the remaining damage continues to the next article of clothing.

So the chance to be damaged is exactly the same for every item that the damage reaches?

I think it should be diminishing _and_ that it should not roll chance to damage if the topmost item failed its respective roll. Slightly less "realistic" but much better for player experience: if the topmost item did not get torn by the attack (roll fail), don't tear any underlying ones either, while if it did get torn (roll success) have a chance to tear ones under it that diminishes (proportionally to damage transmitted?).

Additionally, agreed with Theundyingcode: damage types should affect this. Chopping and cutting should have diminishing probability and negation. Piercing should have same chance for all damaged items (no diminishing probability). Bashing should have _severely_ reduced chance to damage "soft" items, high chance to damage "hard" items, and no negation.

**Comment by sxmichaels** [comment]
@Barhandar As I recall, what you mention about failed penetration damage being turned into blunt damage is exactly what Dwarf Fortress does. Maybe the [DF weapon damage formulas](http://dwarffortresswiki.org/index.php/DF2014:Weapon#Combat_formulae) would be helpful here?

**Comment by Isaacssv552** [comment]
Failed penetration damage turning into blunt damage sounds awesome, but I'm concerned about conveying this to the player. How can this be displayed in a way that won't lead to even more confusion than the current system?
