### ISSUE TITLE
The recipes in the book are not visible in the production interface

### ISSUE THREAD

**Issue by hunjixin** [CleverRaven/Cataclysm-DDA#22438]
Game version:

Operating system: unubtu 17

Tiles or curses:curses

Mods active:only 

### Expected behavior
recipes in the book should be seen
### Actual behavior

Power Storage CBM MK.2  in the book, Augmentative Tech Review 2041.can not be seen in the ui

**Comment by ituluwituluwzev** [comment]
It is possible that your skill is not enough to craft Power Storage CBM MK.2.

**Comment by AMurkin** [comment]
See #21795
