### ISSUE TITLE
"crude_brick", unfired clay brick, item is obsolete.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#22431]
Game version: 0.C Build 6928

Operating system: Windows

Tiles or curses: Tiles

Mods active: None

### Expected behavior
Obsolete item should be in the obsolete.json file.

### Actual behavior
the unfired clay brick item is still in generic.json item list. There is no way to make this item, or if you have it, no way to use the item. So I think it should be simply be moved to the obsolete.json file.

In the past making bricks was a 2 step process, first make unfired clay bricks from clay, and then fire them. Now this is a simple one step process, just like how fletching used to work.

**Comment by Leland** [comment]
Code is yonder:

https://github.com/CleverRaven/Cataclysm-DDA/blob/f13316093e99caa220a6fe3f7122d88633a58746/data/json/items/generic.json#L1758-L1772

Should also remove the reference in HitButton:

https://github.com/CleverRaven/Cataclysm-DDA/blob/cf1bb9ffae8c0b4d7445e4f09e79451ebc05233c/gfx/HitButton_iso/tile_config.json#L5891

**Comment by Soyweiser** [comment]
Yes, I think the items should just be moved to the obsolete file, which I assume is still loaded. But only for save game purposes. Which could mean we should also create a similar system for images. But not sure.

**Comment by Chezzo** [comment]
If you remove the line from the tileset's tile config, then old saved games won't see the image. I don't think it would hurt things to just leave them alone.
