### ISSUE TITLE
City label editor in debug menu

### ISSUE THREAD

**Issue by GearheadLydia** [CleverRaven/Cataclysm-DDA#22449]
Not really a big deal by any means, but something that could possibly be nice:

Is there any chance of an editing feature in the debug menu - for instance, in the overmap editor - to edit city labels? The city labels are a wonderful feature, but some of them are smashed together super close with city size set too high / spacing set too low, and it'd be nice to be able to merge some of them after the fact.

**Comment by kevingranade** [comment]
That's certainly possible, but it'd be a lot nicer to detect this automatically and have idk, the larger city win.

**Comment by Leland** [comment]
We generally don't keep debug issues open since they're pretty low priority. Obviously, PRs welcome 😄
