### ISSUE TITLE
Look at some Suggestion

### ISSUE THREAD

**Issue by korick** [CleverRaven/Cataclysm-DDA#22447]
hi, ILTG
Look at some identified Bugs and Issues
https://github.com/korick/CDDA/tree/master/pics/...
https://github.com/korick/CDDA/raw/master/eng/08.4_idea_eng.txt
my sincere respect and reverence
Russian-Team

**Comment by AMurkin** [comment]
Perhaps if you or someone put more effort to organize all this information, then it may help much more than now.

**Comment by korick** [comment]
1st of all: look at CDDA\pics\... - simply&clear to understanding
2nd: try modify idea_eng.txt 1st paragraph to clear understanding wtf-the-text-08.3_idea_eng.txt
