### ISSUE TITLE
Changes to config/base_colors.json don't appear in game

### ISSUE THREAD

**Issue by harakka** [CleverRaven/Cataclysm-DDA#22459]
Game version: Latest experimental build (6945)

Operating system: Win10 64bit

Tiles or curses: Tiles

Mods active: default

### Expected behavior
Changes to config/base_colors.json should be visible in game.

### Actual behavior
Changes to config/base_colors.json don't seem to do anything, I have to edit data/raw/colors.json to change game colors.

### Steps to reproduce the behavior
Replace line 4 in config/base_colors.json with
`"BLACK" : [255,0,255],`
Start the game, observe that main menu background is still black.

In contrast, do the same edit to data/raw/colors.json, start the game and observe the hot pink background.

Or, if some part of this is intended behavior and I've misconstrued the function of config/base_colors.json, I didn't find that documented anywhere.

**Comment by DanmakuDan** [comment]
The color loading code is loading default colors after the base_colors file, and the load operation overwrites the colors that were loaded first.
