### ISSUE TITLE
Header link on main Github page is broken

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#22458]
The link at the top of the page at https://github.com/CleverRaven/Cataclysm-DDA is not the right one. http://cataclysm.org/ can't be reached. Should it be http://en.cataclysmdda.com/ or http://cataclysmdda.org/ ?

**Comment by Leland** [comment]
pinging @kevingranade

**Comment by Leland** [comment]
That'd be sweet if we actually landed cataclysm.org though. Just have to pay Blizzard a million bucks

**Comment by kevingranade** [comment]
Whoops, thanks for pointing that out.

Btw, no need to ping me, I read every comment anyway >_<
