### ISSUE TITLE
Radiation from zombie scientist mouth beams penetrates power armor / RM13 combat armor

### ISSUE THREAD

**Issue by POEMisaMisa** [CleverRaven/Cataclysm-DDA#22453]
Game version: 0.C-25056-g54e85a9, build #6940
Operating system: Windows 7
Tiles or curses: tiles
Mods active: https://i.imgur.com/WGkNNUW.png

### Expected behavior
Active power armor / RM13 combat armor gives full protection from radiation, caused by zombie scientist mouth beams.
### Actual behavior
Zombie scientist mouth beams penetrates any kind of environmental protection and gives radiation or mutations.
### Steps to reproduce the behavior
1. Equip RM13 combat armor (or power armor) and activate it - https://i.imgur.com/XPEMuwc.png
2. Wait for zombie scientist to cast a beam, gain mutation - https://i.imgur.com/YdvAJlo.png or radiation - https://i.imgur.com/QXhPx99.png

_Screenshots are made in version #6935, but I tested it again in #6940._

**Comment by Theundyingcode** [comment]
don't you need to wear the helmet as well for it to block radiation?

**Comment by POEMisaMisa** [comment]
@Theundyingcode you need to wear helmet with power armor, not with RM13 combat armor. But it penetrates even active heavy power armor + helmet: https://i.imgur.com/8xRS7Nl.png
