### ISSUE TITLE
Allow [r]eloading of liquid containers.

### ISSUE THREAD

**Issue by ShadowDragon8685** [CleverRaven/Cataclysm-DDA#22463]
Game version: 0.C-6933

Operating system: Win 7 x64

It would be (very very) nice if you could [r]eload liquid containers (e.g. canteen, bottle, etc,) from the reload menu/from Activating the item and pressing [r], searching your character and the tiles around your character for liquids which can be put in.

This way the player could [r]eload my canteen from all the bottles in their lockers quite simply, rather than having to pick up the bottles and [U]nload them into the canteen.

**Comment by Xelat84** [comment]
> rather than having to pick up the bottles and [U]nload them into the canteen.

Actually you at least don't have to pick them up, it's enough to stay close to them. Unloading works with items laying in adjacent tiles.

**Comment by ShadowDragon8685** [comment]
That's... Helpful. At least it lets me use my giant water barrel now. But it still seems that you should be able to reload a liquid-container.

**Comment by Broken-Admin** [comment]
If we did this it would make getting spilled liquids up, which shouldn't be possible.

**Comment by sxmichaels** [comment]
@Broken-Admin Not necessarily, especially if you tweak the already-existing magazine reload to do it! I thought this was a great QoL fix so I had a go at implementing it — check out #22507. (I originally thought it would be a simple addition… little did I know how deeply the reload function's tendrils extend into other parts of the code, ha ha. Not much code, but it took quite a while to figure out where to put it!)

**Comment by boydkr** [comment]
It would appear t his issue can be closed since #22507 is merged
