### ISSUE TITLE
Building fails on Archlinux

### ISSUE THREAD

**Issue by HeyBanditoz** [CleverRaven/Cataclysm-DDA#22468]
Game version: cb572ca62cb6e3ff7df70e3f47c1b8b7ecac597b

Operating system: Archlinux

Tiles or curses: N/A

Mods active: N/A

### Expected behavior
I expected it to compile.
### Actual behavior
It did not compile. [Build Log](https://hastebin.com/raw/ocehafomin)
### Steps to reproduce the behavior
Clone the repository using Archlinux, attempt to build, notice it fails.

**Comment by VZIKL** [comment]
Fixed in #22465 but it has not been merged into master

**Comment by Treah** [comment]
Confirmed after merge of #22465 that this compiles cleanly on archlinux.
