### ISSUE TITLE
Constructed fence posts create "flat roofs" when smashed.

### ISSUE THREAD

**Issue by ShadowDragon8685** [CleverRaven/Cataclysm-DDA#22462]
Game version: 0.C-6933
Operating system: Win7 x64
### Expected behavior
When a constructed Fence is smashed, it leaves behind the ground surface that was there beforehand.
### Actual behavior
When a constructed Fence is smashed, a "flat roof" is left on the ground, which cannot be dug, etc.
### Steps to reproduce the behavior
1] Construct a Fence Post on dirt.
2] Smash the Fence Post you constructed on the dirt.
3] Observe/enjoy your new tile that is effectively sidewalk.

**Comment by Night-Pryanik** [comment]
Cannot confirm on 0.C-7008, Windows XP SP3 x86.
Constructed a fence post on the dirt, then smashed it. Got dirt again.
