### ISSUE TITLE
Can't finish half-built wooden wall next to regular wall.

### ISSUE THREAD

**Issue by junkdeck** [CleverRaven/Cataclysm-DDA#22476]
Game version:
Experimental 6947

Operating system:
Devuan Jessie x64

Tiles or curses:
Tiles

Mods active:
Filthy Clothing
Disable NPC Needs
Simplified Nutrition
Bionics Systems Mod
Extended Realistic Guns
Makeshift Items Mod
More Survival Tools
More Buildings
More Locations
Tall Buildings
Urban Development
Boats
Folding Parts Pack
Vehicle Additions Pack
Tanks and Other Vehicles
Classes and Scenario Mod
Prevent Zombie Revivication
StatsThroughSkills

### Expected behavior
Trying to patch up a broken wall from a Derelict Property. Wall should be constructed following half-built wall and joined to regular wall.

### Actual behavior
Wall construction from half-built wall not allowed. "You can't build there" message, despite having the required components, tools and skills.

### Steps to reproduce the behavior
Remove wall from house, build half-built wall next to existing wall, attempt to finish wall construction.

Screenshot for clarification: 
https://i.imgur.com/qoFN0DM.png

**Comment by Night-Pryanik** [comment]
This half-built wall in Derelict Property is half-built **log** wall. You can successfully finish it if you have all the tools and components for building the log wall.

I'll correct the description of this terrain to avoid confusion, though.
