### ISSUE TITLE
Failing to compile with lua

### ISSUE THREAD

**Issue by Podesta** [CleverRaven/Cataclysm-DDA#22473]
Trying to compile on Xubuntu 16.04. I've got lua5.3 and liblua5.3-dev.
Using
`make TILES=1 SOUND=1 RELEASE=1 LUA=1 USE_HOME_DIR=1 `

I get the following error:
```
Unformatted data/mods/Zombie_Nightvision/modinfo.json
cd src/lua && lua generate_bindings.lua
/bin/sh: 1: lua: not found
Makefile:730: recipe for target 'src/lua/catabindings.cpp' failed
make: *** [src/lua/catabindings.cpp] Error 127
```
Seems similar to #20926, but I have both the binary and the library. And the makefile seems to accept version 5.3 without a problem.

**Comment by Podesta** [comment]
The nice folks at irc managed to help me. Apparently when I installed lua5.3 the symlink got borked somehow. Installing lua5.2 seems to have fixed the link, and the make was able to finish building using the version 5.3 without a problem.

**Comment by ChainsawGarden** [comment]
If anyone's still working on their own Lua-related problems and are still coming across this issue, for ```cd src/lua && lua generate_bindings.lua``` do ```cd src/lua && /usr/bin/lua generate_bindings.lua```.
