### ISSUE TITLE
Correctly retire vehicle curtain item

### ISSUE THREAD

**Issue by rm-code** [CleverRaven/Cataclysm-DDA#22479]
In my first [contribution](https://github.com/CleverRaven/Cataclysm-DDA/pull/22429) to the game I tried to retire the vehicle curtain item by creating a file in the legacy folder.

Apparently that didn't work correctly as one user [reported troubles](https://github.com/CleverRaven/Cataclysm-DDA/pull/22429#commitcomment-25769660) when removing the old vehicle curtains. 

So my question is: what's the right way to retire items, recipes and so on? I'll gladly fix it in a new PR.

**Comment by cainiaowu** [comment]
check my pr for arrowhead
