### ISSUE TITLE
[Question][Coding] Vehicle JSON serialization modification

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#22477]
Where is the code to convert the vehicle part JSON files into the vehicle_part object? Vehicle.h defines the methods but I cannot find the implementation of it. 

I am planning on adding a new field to the JSON object and I need to find a way to have it get loaded into the item's object.

**Comment by angoddu** [comment]
I found the location. It's in the vpart_info::load method in the veh_type.cpp file

**Comment by BevapDin** [comment]
Use the search in all files or similar feature of your IDE / editor. Search for `vehicle::serialize` (or whatever function you need to find).

I usually use this command line:
```
$> grep vehicle::serialize -FR src
src/savegame_json.cpp:void vehicle::serialize(JsonOut &json) const
```

The function is implemented in "savegame_json.cpp".
