### ISSUE TITLE
Density problem with many item

### ISSUE THREAD

**Issue by Xsillione** [CleverRaven/Cataclysm-DDA#22514]
Game version: 0.c-24628-g82d0228

Operating system: Win 7

Tiles or curses: Tiles

Many item has strange density (weight/volume):
Anvil: weight 54 kg, volume: 4 L => 13,5 density (instead of 8 of the iron)
Hard plating: weight 32,6 kg, volume 3 L => 10,9 density (instead of 8 of the iron)

But the engines has even more strange density:
6,5L W8 engine: weight 200 kg, volume 6,25 L => -800 (instead of 8 for iron, 2,7 for alumium or something similar) in thi cae the 6,5L is the intarnal volume of the combution chamber, so the item total volume should be higher than that (much higher), realistic volume for that engine with the weight: 200/8+6,5=31,5

**Comment by illi-kun** [comment]
>  But the engines has even more strange density:

I suppose that high weight of engines was defined due to gameplay balance (to restrict number of engines you able to carry in your backpack).

**Comment by bandti45** [comment]
Most of these items are made of steel, which has a different density than iron (not a big difference but something to consider when changing the value) and somethings need weight and volume adjustment like engines probably (that's outside my knowledge range).

**Comment by kevingranade** [comment]
"Strange density" is not a problem per se unless it impacts the game in some way.
