### ISSUE TITLE
Vehicle turrets fired from controls aim from the wrong tile

### ISSUE THREAD

**Issue by jeremyshannon** [CleverRaven/Cataclysm-DDA#22512]
Game version: 0.c-25163-ga18e4b5f16-dirty (#6961)

Operating system: Linux

Tiles or curses: Curses

Mods active: Base game only

### Expected behavior

Firing a turret should aim from the turret's tile

### Actual behavior

Instead it starts aiming from the seat with the controls, causing problems with range calculations. Firing near maximum range will cause the turret to fail silently. This is most noticeable with short ranged weapons like flamethrowers.

### Steps to reproduce the behavior
Spawn any vehicle in, and weld a flamethrower and a tank of napalm somewhere other than the driver's seat, farther away will make the problem more obvious. Press f, select a target somewhere far from the turret, and nothing happens.
 If you get close to the turret it will work, but this bug dramatically reduces the working range for the turret. If you sit on the turret's own tile, you can fire at tiles that it would fail on were you sitting at the controls.

**Comment by ShadowDragon8685** [comment]
This might be a case where good intentions are colliding with code;
After all, you are _aiming_ the weapon from wherever your controls are. That's where you're sighting from, so the theory may be that aim penalties from distance, obstruction, etc, should be assessed from your location, not from that of the weapon itself.

On the other hand, and as you bring up with the example of hilariously short-ranged weapons, this leads to a problem with long vehicles, where the weapon itself has a hard and short range, which actually *is* within range of the target, but you would not be if you were firing that weapon from the tile you're sitting on.

I think the theory may be that aim penalties for range should be assessed from the player's tile, but dispersion, etc, should be assessed from the weapon's tile.

**Comment by jeremyshannon** [comment]
If you're going to go that route, then it seems to me it'll start to get complicated once you begin taking mirrors and cameras into account. I mean, I've got a camera display and a camera on the back of my vehicle. If I'm looking through the display, shouldn't I be aiming from that tile instead?
