### ISSUE TITLE
NPCs move to avoid exhaust fumes while inside moving vehicle.

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#22517]
Game version: 0.C-25161

Operating system: Windows 10

Tiles or curses: Tiles

### Expected behavior
NPCs remain seated until the vehicle has come to a complete stop.

### Actual behavior
NPCs get out of their seats like complete dumbshits and run madly within and outside the vehicle trying to avoid exhaust fumes, putting themselves in great danger. Makes driving backwards without killing them extremely difficult.

### Steps to reproduce the behavior
Have NPC ride in a vehicle with an ICE. Drive backwards slowly.

**Comment by jeremyshannon** [comment]
This is actually dangerous when it combines with #21811 -- having a smoker or bloated zombie pop out nearby and explode can make your NPC dance around the vehicle, which can make you lose control of it.

**Comment by sxmichaels** [comment]
Really the issue here isn't NPC behavior — smoke and other gases shouldn't be able to get into an enclosed car in the first place. I don't know off the top of my head how those things are stored on map tiles, but maybe we could make it such that if an enclosed vehicle tile is over a map tile, that tile's gases are temporarily canceled out or something like that?

**Comment by Night-Pryanik** [comment]
> Really the issue here isn't NPC behavior — smoke and other gases shouldn't be able to get into an enclosed car in the first place.

Most cars ain't airtight, so gases can permeate the vehicles. I think the NPC behavior do matter here - we should make NPCs ignore the gases (maybe only the first density of them) if they are in the vehicle.

**Comment by ShadowDragon8685** [comment]
Although most cars are not airtight, they do contain a significantly enclosed environment which resists penetration by other gasses to some degree. Whilst it's not absolute, and highly toxic gasses will still poison the hell out of you, cars will definitely keep their passengers from choking on the exhaust while they're driving, either from themselves or, say, a vehicle ahead of them with a diesel in poor maintenance, provided that you don't get stuck behind them for ages.

**Comment by Heaper327** [comment]
Is it possible to introduce air exhaust fan? It should be installed at a engine, and when turned on consumes power to protect the inside of a vehicle from any kind of gases or smoke
