### ISSUE TITLE
Vehicle self-jacking system

### ISSUE THREAD

**Issue by ShadowDragon8685** [CleverRaven/Cataclysm-DDA#22547]
This hit me like a bolt of the "no doy, really?" just now. I have a truck with a couple of boom cranes on it, but it can't jack itself up to, say, change the tires.

That seems reasonable for a boom crane you're using for ordinary things; however, I would suggest the addition of an automotive lift device be craftable/installable on vehicles, that would allow a vehicle to jack itself up, for example, to change a tire.

This is not at all without precedent: https://en.wikipedia.org/wiki/Bowler_Wildcat The Bowler Wildcat had such a device as an option, which came in great handy.

**Comment by kevingranade** [comment]
Makes sense, it's just a fixed component that jacks the vehicle, you can just implement it as a component with the jack quality I think.

**Comment by ShadowDragon8685** [comment]
Isn't that what the Boom Crane has? It can't seem to jack up the vehicle it, itself, is attached to.

**Comment by kevingranade** [comment]
You are correct, it needs a similar flag that only works on the installed
vehicle.

**Comment by Brambor** [comment]
Haye, after lifting was introduced I believe this issue should address lifting itself up as well.
