### ISSUE TITLE
Problems with vehicle diagrams.

### ISSUE THREAD

**Issue by WDevil3221** [CleverRaven/Cataclysm-DDA#22546]
So, after the..latest merge/update happened, (which is 6975 according to the launcher) https://imgur.com/28744eu this happens when you move the cursor away from the diagram itself. https://imgur.com/PZqbx0l This as well, even when you don't move too far. Also, just a tiny UI change..which I think is unintentional would be the crafting menu. https://imgur.com/UWmtoGe I don't think a line is suppose to go through the sub-category.

**Comment by ShadowDragon8685** [comment]
I think the line through the sub-categories is meant to make them look like the seperator tabs on a file folder - the old-fashioned manilla-and-paper kind. The vehicle diagram is definitely messed up, though.

**Comment by kevingranade** [comment]
Bisection says the menu ine thing occurred at 8eb30359feb4f7dfd324c016f2cd9afe618de908
The same commit is responsible for the vehicle alignment thing.
