### ISSUE TITLE
Antibiotics do not mention that they cure infections clearly enough

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#22557]
Game version: 0.C-25103-gb2dc46d

Tiles or curses: Tiles

Mods active: Dark Days Ahead, Disable NPC Needs, Simplified Nutrition

### Actual behavior
Antibiotics, when inspected, present a vaguely worded flavor text, that implies antibiotics being somewhat useful for preventing new infections.
See screenshot
![antibiotics-no-infection](https://user-images.githubusercontent.com/7831163/33548328-aba1ba5e-d89b-11e7-8f80-221b979f5a67.png)

### Expected behavior
Antibiotics, when inspected, mention that they cure infection with 100% reliability in the same way first aid kits do.
I don't want to trust flavor text when making important decisions - because it's mostly for flavor. I want to have some kind of presentation that is _obviously_ synced to the code - be it hard numbers ("Chance to heal (percent): Infection: 100") or qualitative ("Chance to heal: Infection: Very High" or "|||||"). 
To reiterate: I trust the numbers coming from first aid kit. I don't trust antibiotic's description.

### Steps to reproduce the behavior
Read antibiotic's description. Compare it to that of first aid kit. Use either when infected and when about to be infected.

Slightly related (but I don't want to file a separate bug): antibiotics description implies they prevent new infection from forming, but they actually completely inefficient at that (I haven't tested this).

Also related (but is a much bigger issue I'm not yet comfortable filing): the overall drugs system is terribly opaque and fully relies on flavor text to give effects description. This makes it very hard to actually use drugs without consulting spoilers.

**Comment by Leland** [comment]
> the overall drugs system is terribly opaque and fully relies on flavor text to give effects description. This makes it very hard to actually use drugs without consulting spoilers.

I'd encourage you to file this. Alongside #1291, which when resolved will list out drug side effects, it might be wise to add in the actual effects. A cogent list of effects is definitely something one would expect from a pill bottle.

**Comment by Night-Pryanik** [comment]
Antibiotics can't be converted to first-aid-kit-style percentage of chance to heal because otherwise they'll become body-part-targeted - at the moment they work on all infected body parts at once.
We can change the description to describe the antibiotics effect as full as possible. Something like "Antibacterial medication that can heal all your body parts affected by infection and tetanus at once." Will this suffice?

**Comment by kevingranade** [comment]
The description has been long since updated to indicate usage and effectiveness.
