### ISSUE TITLE
Player assigned inventory letters no longer save when exiting game

### ISSUE THREAD

**Issue by greenman74** [CleverRaven/Cataclysm-DDA#22567]
Game version: .O.C-6988 64 bit

Operating system: Win 10

Tiles or curses: Tiles

Mods active: Filthy Clothing, Disable NPC Needs, Simplified Nutrition

### Expected behavior
Custom inventory assignment letters should not change letters when saving and reloading the game.
### Actual behavior
Some time between build 6988 64-bit and build 6981 64-bit, custom assigned inventory letters are no longer saved when saving and exiting the game.  Additionally, in settings, turns to re-enable safe mode can no longer be set above 100.  Previously, it was able to be changed to at least 200 turns.  If turns to re-enable safe mode is set greater than 100, it defaults back to 50.
### Steps to reproduce the behavior
Start a game, press "=" to assign inventory custom letters.  Exit the game and reload the save file.  After loading, at least some of the custom assigned inventory letters will also be different.

**Comment by Voqar** [comment]
I can confirm, this is happening to me as of c-6933 win 64 graphical download from yesterday.  0.C-2539-gce697c6

Set keys, quit game, come back, settings gone.

Downloading experimental is ungodly slow yesterday and today too so I haven't got to check the very latest build to see if it persists.

**Comment by Voqar** [comment]
Still an issue in the latest experimental this morning.

It appears that keys set for worn items and wielded item stay, but everything in your inventory loses their items.
