### ISSUE TITLE
Bug with cash card stacks

### ISSUE THREAD

**Issue by rm-code** [CleverRaven/Cataclysm-DDA#22573]
Game version:
0.C-25351-g5b12192 (tiles)

Operating system:
Windows 10 

Tiles or curses:
Tiles

Mods active:
Only the default ones.

### Expected behavior
The empty card stack should stay at the same position in the inventory.

### Actual behavior
When the second empty card is removed from the stack, the remaining empty cash card switches position with the filled cash card.

![cataclysm_ dark days ahead - 0 c-25351-g5b12192 08 12 2017 18_43_09](https://user-images.githubusercontent.com/11627131/33780711-00868dba-dc52-11e7-959a-6787c2bc8625.png)
![cataclysm_ dark days ahead - 0 c-25351-g5b12192 08 12 2017 18_43_12 2](https://user-images.githubusercontent.com/11627131/33780716-02d3ec16-dc52-11e7-96df-a82397692b03.png)

### Steps to reproduce the behavior
Get two empty cash cards and one with money. See above.

**Comment by CoroNaut** [comment]
Can confirm, this has been a bug for a very long time.
