### ISSUE TITLE
Buildings in the middle of the road, and sideways

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#22597]
O.C-25180-g5077a42
<img width="960" alt="screenshot 432 - copy" src="https://user-images.githubusercontent.com/18560216/33951627-1a0df664-dff5-11e7-99b7-c4bce6eca7e3.png">

**Comment by Leland** [comment]
Dupe of #22358. Been around since Nov 5 at least.
