### ISSUE TITLE
Unbalanced Enjoyability Values for PB&J and Jam Sandwiches (and other jam items)

### ISSUE THREAD

**Issue by sphdj** [CleverRaven/Cataclysm-DDA#22601]
Game version: 0.C-25343-g233d155 (tiles)

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: -Dark Days Ahead -Filthy Clothing -Disable NPC Needs -Simplified Nutrition -Bionics Systems Mod -Icecoon's Arsenal -More Survival Tools -Beta National Guard Camp -More Locations -More Buildings -Vehicle Additions Pack -StatsThroughSkills

PB&J should give a higher enjoyability value than the jam made to create it as well as a jam sandwich

Fruit Jam has an enjoyability value of 30, PB&J has a value of 18, Jam Sandwich has a value of 45. Why would I make a PB&J and waste more materials when I can just make a Jam sandwich? I am guessing this had to do with the values of certain items at the time the sandwich foods were created, and this was never checked. Similar situation with the PB&H, PB&M, and peanut butter sandwiches each at 18, 18 and 9 enjoyability.
* After looking up the value of blueberry and strawberry jams, both apparently have all the same attributes, each with an enjoyability of 10. Fairly certain these are older items. These values along with the sandwiches should be changed in enjoyability value.

Went into crafting menu and looked up "c:jam". Also went to estilofusion.com to look up values for strawberry and blueberry jam.

P.S. Can't seem to add a balance label to this issue :(

EDIT: Apparently all this time I didn't realize the Gourmand trait had tripled some of the enjoyability values. So the values for the strawberry and blueberry jams are accurate in the online finder. All other values are divisible by 3 when applied to characters not having the Gourmand trait. Balance still can be applied however to the  all the PB Sandwiches and Jam Sandwich items

EDIT2: "Honey Sandwich" and "PB&H sandwich" have normal enjoyability values of +10 and +6, respectively. Could also use balance.

**Comment by ZhilkinSerg** [comment]
Not everyone likes honey and PB.

**Comment by sphdj** [comment]
So why even have PB&J? Why even have all the other Sandwich items other than the Jam Sandwich?

**Comment by Zireael07** [comment]
Because variety is the spice of life

**Comment by ZhilkinSerg** [comment]
> So why even have PB&J? Why even have all the other Sandwich items other than the Jam Sandwich?

Roleplay, I dunno.

**Comment by ZhilkinSerg** [comment]
Btw, we could implement system for variable morale boost of various food/beverages

**Comment by sphdj** [comment]
> Btw, we could implement system for variable morale boost of various food/beverages
I think that's best left in a new topic. But unless all the sandwich items were purposely made to be less enjoyable or the jam sandwich was purposely made better as some sort of joke or easter egg, then it would make sense to make PB&J have more enjoyability for it's ingredients or balance out the other jelly items as well as increase enjoyability for the old blueberry and strawberry jams.

 Apart from balance, that isn't a terrible idea though.

**Comment by DracoGriffin** [comment]
>Btw, we could implement system for variable morale boost of various food/beverages

That'd be kinda interesting if character creation had a hidden choice flag that gives preferences to food types with some type of formula to calculate the new morale bonuses. Basically, new character may end up enjoying WHEAT foods more than JUNK foods, or prefer MEAT over FISH, etc. With preferences being weighted towards traits/mutations (so carnivores would generally prefer meat-type foods, and herbivores would prefer non-meat items more, and wheat allergic would not prefer wheat foods as strongly, etc).

**Comment by kevingranade** [comment]
Overly specific ans well as unclear about what the expected result is.
