### ISSUE TITLE
0 cities world leads to crash from unplaceable mission location/items?

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#22608]
**Game version:**
0.C-25482-g836edd1 (tiles)
**Operating system:**
Manjaro Linux
KDE Plasma Version: 5.11.4
KDE Frameworks Version: 5.40.0
QT Version: 5.9.3
Kernel Version: 4.14.3-1-MANJARO
OS Type: 64-bit
**Wine/PlayOnLinux version:**
wine staging 2.21-1 / PlayOnLinux 4.2.12
**Tiles or curses:**
Tiles
**Mods active:**
  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "realguns",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "national_guard_camp",
  "more_buildings",
  "more_locations",
  "Experimental-Z-Level",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "no_rivtech_guns",
  "no_flaming_weapons",
  "No_Fungi",
  "StatsThroughSkills"
### Expected behavior
No increased lag from approaching NPC and no crash after interacting with NPC.
### Actual behavior
Increased lag approaching NPC and crash after interacting with NPC.
### Steps to reproduce the behavior
1. Head to west, sout-west plains that continue south. You'll receive the following message when you are just out of map detection range from the NPC "Ernestina Zepeda", "Unable to place all configured specials, some missions may fail to initialize. x 11"

2. Lag.

3. Talk to NPC "Ernestina Zepeda" and move away from her.

4. Bug screen comes up.

5. Wine/game crashes.

[Save](https://github.com/CleverRaven/Cataclysm-DDA/files/1741892/Jacob.Lake.zip)

![screenshot_20171214_232108](https://user-images.githubusercontent.com/714017/36449071-a8900218-1657-11e8-84f3-1535d98153ad.png)

**Comment by Leland** [comment]
We blacklist certain starting scenarios and professions on citysize = 0 now, perhaps we need to do the same with possible NPC missions

**Comment by Night-Pryanik** [comment]
No confirmation in more than a year, closing.
