### ISSUE TITLE
Woods Soup / Beans Bug

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#22619]
The recipe for Woods Soup does not normally accept "beans" (as come in a can), but the recipe for Woods Soup in a glass jar does accept such beans. Since that kind of bean only comes from cans, and the soup is supposed to be from nature, it should probably be removed from the recipe. Other kinds of beans are alright.

**Comment by Cyrano7** [comment]
Easy fix as in make the recipes consistent with each other one way or another.
