### ISSUE TITLE
mess kits lose their 'boiling' quality after a UPS conversion mod is installed

### ISSUE THREAD

**Issue by aeoo** [CleverRaven/Cataclysm-DDA#22612]
Game version: 0.C-25498-g7ee93bc46d

Operating system: GNU/Linux

Tiles or curses: Tiles

Mods active:

Dark Days Ahead
No Fungal Monsters
Classic Roguelike Classes
StatsThroughSkills
Urban Development
Bionics Systems Mod
Boats
Craftable Gun Pack
Bright Nights
Folding Parts pack
Filthy Clothing
More Buildings
Classes and Scenarios Mod
Disable NPC Needs
Simplified Nutrition
Alternative Map Key

(whew)

### Expected behavior

Wether or not any mod whatsoever is installed on a mess kit, its qualities should always be available unless the mod explicitly and consciously jams a certain quality by design.

### Actual behavior

Without the UPS conversion mod, the mess kit works as one would expect.  Once the mod is installed, the mess kit loses its boiling quality but retains its cooking quality and I assume its containing quality as well (haven't tested that one).

### Steps to reproduce the behavior

These should be obvious.  I just find or spawn a mess kit and UPS conversion kit, try to make clean water without the UPS conversion kit installed to verify that the mess kit is operating normally.  Now install the UPS conversion kit and try to make clean water again.

Speculation time: I've been very loosely following some of the discussions on github and I am vaguely aware that there was a change that made boiling quality unavailable if the container is full.  I am wondering if this isn't the culprit?  I haven't tested this, but I suspect this issue might affect a military mess kit and possibly other boiling devices (like maybe a coffeemaker?) which can accept mods.  It's possible that a number of other mods, besides the UPS conversion mod, might cause this behavior.  /end speculation.

**Comment by kevingranade** [comment]
I'm pretty sure your speculation is correct, that fix checked for item
contents other than the designated ammunition for the tool, it did not also
exclude tool mods.

**Comment by ZhilkinSerg** [comment]
This code should be updated:

https://github.com/CleverRaven/Cataclysm-DDA/blob/a159ebb18e21370aad786426f65e8ac06cae1ae9/src/item.cpp#L3494-L3503
