### ISSUE TITLE
High City Spacing leads to dead-end roads

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#22616]
When playing a world with City Size 16 and City Spacing 8, the two roads leading away from  the starter city both lead to dead ends with irregularly flat map borders nearby. I'm not very confident it generates roads at all. It's possible that the cities are just that far away, but it seems like I've looked farther than "twice the usual distance" as would be implied by using 8 instead of 4, and mostly just wish the roads led from town to town like usual. 

I've uploaded a video, and you can see the flat borders that seem to cut off the roads.
https://vimeo.com/247555359

**Comment by ZenZen2** [comment]
I think this is an old bug.
Is it possible that City Size doesnt end at the border of buildings and wilderness?
Example: Set City Size to 1 and City Spacing to 8 and you will see small space between the citys.
Now increase the City Size and watch how City spacing increases.

**Comment by etmoonshade** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/14362 is where city spacing is explained. If I remember correctly, road generation is based on city locations - if you've only got a single huge city on an overmap, you're not going to have two cities to have roads from/to, so you're just going to get a couple of roads out to labs/power stations/etc. and nothing else.

I admit, I've seen the same thing you have - I like sparse cities, but not quite THAT sparse - I tend to play at 5/8 for spacing/density myself, and that gives a good "road trip" vibe without feeling barren.

Short version of the PR linked above is that city spacing is an average density (or inverse density, I guess?) - whether it's GOOD or not, it looks like the behavior you noticed is as intended.

Suggestion:
It may be worth requiring at least two or three tiny cities/towns/hamlets/houses/whatever per overmap, even at huge spacings, so it always generates SOME roads and non-wilderness specials.

A second option would be an "Always generate X [houses|hamlets|towns|whatever] per overmap" sort of option (probably defaulting to on,) so you force some road generation but also allow people who like the current behavior to keep it.

**Comment by Headjack** [comment]
My core issue is that I think that all roads should lead to the next city, however far away. If you're explaining that it generates a set number of cities, that's news to me since I had believed that the maps generate procedurally, and that distance just determined how far apart they are, as you'd expect. Maybe I'm just unfamiliar with the concept of an overmap. Point being, all cities should have roads leading out of them, and at least one of those roads should lead to another city that has not yet been explored, however far away that is.

**Comment by etmoonshade** [comment]
The overmap is the border shown by those "irregular" edges you were talking about. On my current map, the meeting of four overmap tile corners is really obvious: https://imgur.com/zuNAnRH (see near the cursor/center of the screenshot) The hierarchy is basically that THE overmap is made of overmap tiles, which is made of submaps of 24x24 tiles (which represents a letter on the map screen.)

I'm sure @sparr or someone else can explain better, but (again, I THINK) that getting the problem of roads not crossing overmap borders would require a rewrite or overhaul of the mapgen code. Incidentally, I agree with you - I'd like to be able to drive across overmap tiles on a road - but my understanding is that it's a non-trivial problem to fix.

Note that I'm not really a coder, so I neither know how to fix it or exactly how it works. I'm just the one who opened #14362, so I followed it pretty closely and helped sparr with hammering out some of the details on IRC while he was hacking at it. :)
