### ISSUE TITLE
Blazemod solar arrays can neither be installed nor disassembled.

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#22632]
Game version: 0.C-25504

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Blazemod

After creating one of the the Solar Arrays from the Vehicle Additions Pack AKA Blazemod, I discovered that there was no kind of tile on my vehicle where it could be installed, and no entry for it appeared on the list of parts. It also cannot be disassembled. While I know some are concerned that this component is unbalanced to begin with, Blazemod is still one of the most frequently used mods and a part of the standard distribution, and as it currently stands it simply represents a trap by which uncraftable solar panels are lost forever.

**Comment by ShadowDragon8685** [comment]
IIRC, BlazeMod's "Turreted Solar Panels" require a Storage Battery Case as a turret base; have you tried to see if the Solar Array is the same way?

**Comment by Lorith** [comment]
Solar arrays require the main 'center' location where you would install an aisle/cargo/crafting station/chair, which means you can have a roof with a solar panel above them.  I had issues with this as well until I spent a while trying every possibility.

**Comment by Solusphere** [comment]
Ah, that did it, thanks Lorith!

Ok, so the placement, while fiddly, is functional. A disassembly recipe still seems like a good idea though.
