### ISSUE TITLE
Crash when reloading with 'r' to item in vehicle

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#22635]
Game version: cataclysmdda-0.C-6947

Operating system: win 10

Tiles or curses: tiles

Mods active: DDA /filthy clothing/ more  survival tools

### Expected behavior  

  reload with "r" Battery Compartment Mod for UPS inside vehicle cargo space with car battery without unloading existent car battery, No CTD

### Actual behavior 

CTD

### Steps to reproduce the behavior

cannot reproduce reliably, encountered same bug once before

**Comment by Leland** [comment]
Unfortunately, without steps to reproduce or a savefile exhibiting this behavior, there's little for coders to do here.

Closing – if you discover a reliable means to reproduce this please post here and will reopen.
