### ISSUE TITLE
"Describe creatures" in "extended description" does not show hallucination monsters

### ISSUE THREAD

**Issue by BigBadRobin** [CleverRaven/Cataclysm-DDA#22649]
Game version:7015

Operating system: win7(x64)

Tiles or curses: chesthole

Mods active: any

### Expected behavior
"Describe creatures" in "extended description" should show hallucination description
### Actual behavior
"You do not see any creature here."
### Steps to reproduce the behavior
x -> coursor on hallucination -> e -> c

**Comment by BigBadRobin** [comment]
Maybe should add abuse label? Since that give ability of differing real monsters from hallucination.

**Comment by BigBadRobin** [comment]
Also hallucinations has no indication in "compas" part of mainscreen, I guess by same reasons. 
Screenshot: black rat, raccoon and dog are real.
![cata](https://user-images.githubusercontent.com/18753194/34261651-f1ecd97a-e67a-11e7-88b2-23288a69164b.png)

**Comment by Night-Pryanik** [comment]
> Also hallucinations has no indication in "compas" part of mainscreen, I guess by same reasons.

No, the direction to the creatures isn't showing when the creature is too near. Tested right now - the hallucination monster far enough from me was shown in the compass area.

**Comment by BigBadRobin** [comment]
> No, the direction to the creatures isn't showing when the creature is too near. Tested right now - the hallucination monster far enough from me was shown in the compass area.

My bad.
