### ISSUE TITLE
Frames used in Start Vehicle Construction Change to Default Quality rather than Actual Quality

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#22653]
Game version: Experimental 7004

Operating system: Windows 7 64-bit

Tiles or curses: Tiles

Mods active: Default (Dark Days Ahead, Filthy Clothing, Disable NPC Needs, Simplified Nutrition)

### Expected behavior
Initial vehicle frames utilized in "Start Vehicle Construction" construction option should remain reinforced, even when later removed.
**edit**: Initial vehicle frames utilized in "Start Vehicle Construction" construction option should remain the quality they are when creating a new vehicle, even when later removed.

### Actual behavior
Initial vehicle frames utilized in "Start Vehicle Construction" construction option lose reinforced status, and even when later removed, do not regain the reinforced status (instead produces a non-reinforced frame). Current "work-around" is to use a non-reinforced frame initially, examine vehicle, and install a reinforced frame in an empty adjacent tile.
**edit**: Initial vehicle frames utilized in "Start Vehicle Construction" construction option are changed to default normal quality, rather than the inherent quality of the frame being used. (If a damaged frame is used in the initial construction of a vehicle, it will "magically" be repaired, and when later removed, it will now be a normal quality frame, rather than being damaged, essentially creating a loophole to repairing damaged frames freely and quickly.)

### Steps to reproduce the behavior
Debug wish a type of frame, some type of welder, reinforce frame with appropriate materials, open Construction menu and "Start Vehicle Construction" using the aforementioned reinforced frame, and examine the vehicle. Additionally, remove the frame from vehicle with appropriate tools and item produced will be a non-reinforced version of the item.
**edit**: Damage a frame or remove one from a damaged pre-existing vehicle, open the Construction menu and "Start Vehicle Construction" with damaged frame and it will show the new vehicle with a repaired frame, rather than the damaged state it was acquired. If it later removed, it will remain repaired.

![reinforcedsteelframe](https://user-images.githubusercontent.com/32253888/34272271-dd562904-e64c-11e7-85e7-770c34cb5e4f.png)
![lostreinforcedstatus](https://user-images.githubusercontent.com/32253888/34272286-ed3318dc-e64c-11e7-9848-8e4b7d3fa138.png)
![proofreinforcedframeswork](https://user-images.githubusercontent.com/32253888/34272292-f10794ba-e64c-11e7-9ab2-6bfb5df9e89f.png)

**Comment by Isaacssv552** [comment]
This is probably an issue with the C++ for "done_vehicle" and the "vehicle_start" flag.

**Comment by CoroNaut** [comment]
I know that people had a problem with reinforcing anything like batteries for example, when you werent allowed to reinforce them. I feel like this is the result of an update that makes sure you cant reinforce items before adding them to the vehicle.

**Comment by DracoGriffin** [comment]
You can reinforce any vehicle part and install it and it will be the reinforced quality (aka the dark green).

Additionally to this issue, installing damaged frames also results in a fixed/normal frame (so installing a |. quality frame as the initial vehicle construction frame will result with the bright green quality, instead of the quality/color it should be).
