### ISSUE TITLE
Mycus Fireproofing not fire proofing

### ISSUE THREAD

**Issue by Vetulus949** [CleverRaven/Cataclysm-DDA#22654]
Game version: 
build 7018

Operating system: 
windows 10

Tiles or curses:
Chesthole32

Mods active: 
cata++, mining mod, crazy cataclysm, boats, folding parts, vehicle additions pack, Tanks and other vehicles, urban development, tall buildings, more locations, mythological replicas, more survivor tools, medieval and historic content, makeshift items mod, icecoon's arsenal, extended realistic guns, deadleaves' fictional guns, craftable gun pack, bionics system mod

### Expected behavior
protections from fire

### Actual behavior
standard fire stuff happens instead of any protection; blistering, pain and damage effects

### Steps to reproduce the behavior
give the player the mycus fireproofing mutation and stand near fire

**Comment by Night-Pryanik** [comment]
Can't confirm - got fireproofing, made a raging fire, stood near it, even walked into it - no effects except for rising of temperature.

**Comment by Leland** [comment]
Yeah, can't repro either. @Vetulus949 please check to make sure you're on the most recent experimental and retry this. Closing for now, if you can still reproduce, let me know and we'll reopen.
