### ISSUE TITLE
Lightmap bug

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#22655]
Game version: 0.C-25558, build 7020

Operating system: any

Tiles or curses: any

Mods active: dda

### Expected behavior
Light sources illuminate significant area at basements.

### Actual behavior
Flashlight only illuminates area visible at the dark and unable to illuminate area beyond it.

### Steps to reproduce the behavior
Go into a basement and light a flashlight.

Reverting changes done to src/lightmap.cpp by PR #21840 restores previous state.

**Comment by NEONZARIN** [comment]
I confirm the bug.
I and one other person have the same problem.

**Comment by sphdj** [comment]
I can also confirm. Also I lack seeing anything above one tile away from me using natural night vision ( as a trait plus a perception of 12) in a basement.

**Comment by kevingranade** [comment]
fixed by 47c773f353, a revert of #21840
