### ISSUE TITLE
dropped items fall through z-levels

### ISSUE THREAD

**Issue by Soadreqm** [CleverRaven/Cataclysm-DDA#22661]
Game version: 0.C-25560-g6b3f88d

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: "dda",  "no_npc_food",  "novitamins",  "more_classes_scenarios",  "realguns",  "bio_mod",  "Medieval_Stuff",  "makeshift",  "More_Survival_Tools",  "alt_map_key",  "Experimental-Z-Level",  "deoxymod",  "blazemod",  "Tanks",  "boats",  "no_flaming_weapons",  "no_survivor_armor"
Also had the ALIGN_STAIRS world option on, in case it matters.

### Expected behavior
Dropped items are placed on the floor on the level where they were dropped.

### Actual behavior
Items dropped at Z+1 fall to Z=0. Applies to player-dropped items, enemy death items, and debris from smashed furniture.

### Steps to reproduce the behavior
While at the upper floors of a multi-floor building, drop an item.
Tested at a 2-story motel, both inside floors and the "walkway" terrain outside.

**Comment by grubsteak** [comment]
(https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/changelog.txt#L13)[Perhaps the items you have are unsupported?]

**Comment by kevingranade** [comment]
I strongly suspect https://github.com/CleverRaven/Cataclysm-DDA/pull/21840 is causing this.

**Comment by kevingranade** [comment]
fixed by 47c773f353, a revert of #21840
