### ISSUE TITLE
The freeform pool option doesn't work.

### ISSUE THREAD

**Issue by Nanotwerp** [CleverRaven/Cataclysm-DDA#22667]
Game version: 0.C-25560-g6b3f88d9ba

Operating system: Fedora 27 amd64

Tiles or curses: curses

Mods active: none

### Expected behavior
The freeform pool option should allow for an unlimited amount of available traits, stats, and skills.

### Actual behavior
It's still limited.

### Steps to reproduce the behavior 
Try to create a custom character with the freeform option, and attempt to add more than 12 traits.

**Comment by Nanotwerp** [comment]
Something's implemented incorrectly in _newcharacter.cpp_.

**Comment by Rivet-the-Zombie** [comment]
Have you tried adjusting the _maximum trait points_ under _options>debug_?

**Comment by Leland** [comment]
Looks like the original intent in #15591 is for freeform to disable limits entirely

**Comment by ZhilkinSerg** [comment]
What about challenge starts? Should we disable it for freeform?
