### ISSUE TITLE
"Retire" or become an NPC

### ISSUE THREAD

**Issue by nictaylr** [CleverRaven/Cataclysm-DDA#22678]
In DF you can retire your player-controlled thing to become part of the world

It would be great if you could somehow abandon one of your characters to become an NPC, or maybe even (obviously, according to an option), turn other characters in the same world into NPCs.

This could allow for pseudo-multiplayer play by for example, exporting your character or something?

**Comment by kettleswordfang** [comment]
it would be awesome if the tile you retired on became a little survivor encampment or some such, with that character in it..

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
