### ISSUE TITLE
Luty pattern SMGs

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#22688]
We have frequently discussed the limits of the players ability to craft firearms from scratch.  This gun represents one extreme of those limits, a proven, if suboptimal submachine gun crafted entirely from standard materials with simple tools.

Main site of Luty (archived)
http://thehomegunsmith.com/
Article about the gun
http://armamentresearch.com/pa-luty-9mm-submachine-guns/
Related YouTube video
https://youtu.be/sIhGCRIQnCA
Archive of book in pdf
https://archive.org/stream/Expedient_Homemade_Firearms_9mm_Submachine_Gun_P_A_Luty_Paladin_Press

The drawbacks are clear however, this is a smoothbore gun with no recoil management and an unreliable and low capacity feed mechanism.

Tool requirements:
1. Electric drill and bits
Existing item
2. Hacksaw
Existing item
3. Selection of metal files
Existing item I think
4. Angle grinder
New item
5. Bench grinder
New item
6. Hammer
Existing item
7. Set square
New item
8. Pin reamer
New item
9. Taper cutting tool
???
10. Countersink tool
Either new item or part of the drill bit set.
11. Large vise
New item

Some of these items, such as the reamers and countersink tools, could arguably be included in toolkits, possibly existing ones.
The key new items:
1. Angle grinder, a common handheld powertool. Has MANY other uses.
2. Bench grinder, a common powered bench-top power tool.
3. Set square, a common and easily fabricated hand tool.
4. Large vise, a common and fabricatable bench fixture.
5. Expedient Homemade Firearms, a new book containing the recipe for the expedient smg.

**Comment by ZhilkinSerg** [comment]
Angle grinder looks a lot like circualr saw with different disk.

**Comment by ZhilkinSerg** [comment]
Countersink is just type of cutter head for drills, isn't it?

**Comment by ZhilkinSerg** [comment]
We also need lathe probably - lot of round shaped things can be done with that.

**Comment by Rivet-the-Zombie** [comment]
>Angle grinder looks a lot like circualr saw with different disk.

The handle/motor part is a different shape though, so you can get the abrasive disc into corners and such.

>Countersink is just type of cutter head for drills, isn't it?

They make special bits for it, but you can make countersink holes with a larger size bit and a guide/bit of extra care.

**Comment by kevingranade** [comment]
> Angle grinder looks a lot like circualr saw with different disk.

It's similar, but the differences are pretty critical.
> Countersink is just type of cutter head for drills, isn't it?

Yes, which is why it didn't make it to the final list of 5 new items.
> We also need lathe probably - lot of round shaped things can be done with that.

Please read the book I linked, at least the intro.  The whole point of expedient firearms is to avoid specialised tools like lathes. A lathe is 100x rarer than the rest of the tools combined.

**Comment by ZhilkinSerg** [comment]
> Please read the book I linked, at least the intro. The whole point of expedient firearms is to avoid specialised tools like lathes. A lathe is 100x rarer than the rest of the tools combined.

Sorry, I've skimmed through the book on archive.org, saw mention of lathe and thought that it could be used to create some home-made baseball bats and similiar things. This is unrelated to firearms.

**Comment by Cyrano7** [comment]
Some other homemade guns like the scrap lever-action shotgun could use this sort of treatment too. I have all those pipe and scrap guns blacklisted for my worlds now because the recipes and functionality are quite questionable. I do like the idea of having crafted from scratch guns in the game though.  Lots of youtube and real life examples to go off of.

**Comment by Firestorm01X2** [comment]
1. Why do player need those guns if normal one coulb be eadily found?
2. Probably it is better to finish gun balancing before adding new layer of gun crafting

**Comment by Cyrano7** [comment]
@Firestorm01X2 Well for reason one some ppl may play with no cities enabled or low item spawns which means fewer chances to find firearms.

**Comment by kevingranade** [comment]
1a. The main reason is if the player finds some kind of workshop with the necessary tools before they're capable of entering a city, particularly if they have spawn rate set very high.
1b. Because it's there.
2a. There is no well-defined "finish" for gun balancing to even target.
2b. Different people have different abilities and priorities for developing game features and content, additions are almost never fungible to the point where it makes sense to trade off effort expended on feature A vs effort expended on feature B.
2c. Gun balance is more or less independent of what guns are available, so adding this new gun isn't going to interfere with future balancing effors.  In short they have nothing to do with each other.

**Comment by Firestorm01X2** [comment]
> 2a. There is no well-defined "finish" for gun balancing to even target.
There is.
https://github.com/CleverRaven/Cataclysm-DDA/issues/22211

**Comment by bl34k** [comment]
While we're at it, change the 12 gauge pistol recipe to reflect the one in that same site. Currently you don't even need a spring to make it. Also the pipe rifles. They would certainly need at least a drill. Currently most of those gun recipes are far too easy.

**Comment by Broken-Admin** [comment]
I feel I came late, how are we on items? I'd love to help with this.

**Comment by Night-Pryanik** [comment]
@Broken-Admin you are welcome to try.
