### ISSUE TITLE
Kris knife won't fit into a sheath

### ISSUE THREAD

**Issue by aeoo** [CleverRaven/Cataclysm-DDA#22686]
Game version: 0.C-25592-gb478bedc45

Operating system: Linux

Tiles or curses: Tiles

Mods active: 

DDA  
No Fungal Monsters  
Classic Roguelike Classes  
StatsThroughSkills  
Urban Development  
Bionics Systems Mod  
Boats  
Craftable Gun Pack  
Bright Nights  
Folding Parts Pack  
Filthy Clothing  
More Buildings  
Classes and Scenarios Mod  
Disable NPC Needs  
Simplified Nutrition  
Alternative Map Key  

### Expected behavior

Sheath claims it will accommodate up to 0.75 liters, so it should do just that.  Kris knife is 0.75 liters and a sorcerer class from one of the mods starts with kris sheathed in a 'sheath', which makes sense.

### Actual behavior

Once the sorcerer's kris is unsheathed from its sheath, it can no longer be resheathed, and the description for kris doesn't list 'sheath' as one of its containers.

### Steps to reproduce the behavior

Should be trivial, just start the game with a sorcerer from I believe "classic roguelike classes" mod.  Unsheathe the kris and try to resheathe it.

**Comment by BorkBorkGoesTheCode** [comment]
The ankle holster says it will only accept items with volume 0.66+. I think floating point math may be involved.

**Comment by aeoo** [comment]
I'm talking about sheath, which is a bit larger than the ankle holster.

It occupies 'leg' layer 'waist'.

**Comment by BorkBorkGoesTheCode** [comment]
Sorry for being vague. I was mentioning that the ankle holster has weirdness as well.

**Comment by aeoo** [comment]
Ah, now I get it, thanks.  I looked at JSON and everything is specified in integers in JSON.  For 'sheath' max_volume is 3, and 'kris' is volume 3.

I think I found the problem.  It's in the definition of "kris":

"SHEATH_SWORD"

Kris is not a sword.  I think the problem is in the flag documentation file, where it says something like "knives are 2 or less", which makes no sense.  It should say "knife are 2 or less, with a few exceptions."  It shouldn't cause people to be dogmatic about the number 2, but I think it does.

So either the definition should be relaxed, or kris should be made volume 2, because it is a knife and not a sword.

**Comment by BorkBorkGoesTheCode** [comment]
I just checked the kris entry and it has SHEATH_SWORD, not SHEATH_KNIFE, which means that this isn't a math issue. The kris should be sheathed in a scabbard.

**Comment by aeoo** [comment]
>The kris should be sheathed in a scabbard.

Not so.  Kris is a knife.  It should not be sheathed in a scabbard.  I know thanks to the game definitions it can be, but that's not correct.

https://en.wikipedia.org/wiki/Kris

It's definitely only a knife.

**Comment by BorkBorkGoesTheCode** [comment]
That would make sense and fix the issue.

**Comment by aeoo** [comment]
http://www.baliblog.com/travel-tips/bali-travel/balinese-culture/the-sacred-kris-indonesian-traditional-knife.html

But I also found some slight counter-evidence.  I found a store that sold "kris swords" with 20 inch blades.  Also the blog above says the blade length is "highly variable."

One thing that irks me is that if it's volume 3 and the sheath holds volume 3, but because of a flag it won't work.  I think volume should be enough to determine if something matches or not.

On the other hand, if we want to get technical and talk about shape and other properties, the kris require their own special holsters anyway.

Another way to fix this issue would be to outfit the sorcerer with a scabbard.

Apparently 'sheath' was good enough in the past.  I'm in favor of allowing kris to be considered a knife.  But if the powers that be decide this isn't ideal, then at least the sorcerer class should come with a set of matching equipment.  Right know it comes with kris in a sheath so once unsheathed, you get a useless sheath and kris that cannot be stored on the body. :)

**Comment by kevingranade** [comment]
The criteria for fitting in the knife sheath isn't whether it's considered
a knife by some arbitrary measure, it's whether it can physically fit in
the sheath.
A typical Kris is long and thin enough that it will not fit in the knife
sheath, this is working as intended.

Feel free to fix the profession definition to change the provided sheath to
one that will fit.

There is likely an improvement that can be made to profession consistency
checking to insure that weapons defined as spawning inside a worn container
are capable of doing so.
