### ISSUE TITLE
Debug message when trying to reload liquid container with a liquid from aluminum can

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#22692]
Game version: 0.С-7033

Operating system: Windows XP SP3 x86

Tiles or curses: tiles

Mods active: default only

### Expected behavior
Reloading some bottle with a liquid from aluminum can should be error-free.
### Actual behavior
Debug message appears, bottle isn't filled.
### Steps to reproduce the behavior
Try to reload glass bottle or any other liquid container having only aluminum can of crispy cranberry in inventory.
![default](https://user-images.githubusercontent.com/11132525/34519521-7f177b88-f095-11e7-8b92-bcb8ee81a049.png)
![default](https://user-images.githubusercontent.com/11132525/34519598-d4c56f86-f095-11e7-82de-9e467b5e9963.png)

**Comment by Beetlecat** [comment]
This is now happening when attempting to refill my waterskin after one of the recent builds. I can't say for certain which one, but it may have been 7181.

Previously, It was full/nearly full of clean water. Upon loading the game after the update, the waterskin appears empty (as do a couple outdoor jugs under funnels), and attempting to (r)eload it results in the above messages per every nearby item that would normally contain liquid (beer, lemonade, soup, etc.).

Win64 Tiles -- current build 7183 (still errors) -- I'll have to check my modlist.
