### ISSUE TITLE
More locations mod causing errors complaining about invalid colors

### ISSUE THREAD

**Issue by bl34k** [CleverRaven/Cataclysm-DDA#22709]
Game version: bad2d82b1e76366877440faac30d6aaa92368ea6

Operating system: Arch Linux

Tiles or curses: Curses

Mods active: Defaults + Z-levels, more locations, tall buildings, national guard camp, filthy clothing, some of the included item mods and balancing mods, the glory of cereal 

### Expected behavior
World loads up
### Actual behavior
![screenshot_2018-01-07_15-43-29](https://user-images.githubusercontent.com/30325161/34652256-f4fb4368-f3c2-11e7-87e1-6ca929e27e3c.png)

I don't know a lot about coding, changing the color in the json to another one (I tried light_green) made the error complain about the next time magenta_white shows up
### Steps to reproduce the behavior
Try loading or creating a character in a more locations modded world

**Comment by ZhilkinSerg** [comment]
Some color combinations arent supported.

**Comment by ZhilkinSerg** [comment]
https://discourse.cataclysmdda.org/t/invalid-colour-name/14734

**Comment by illi-kun** [comment]
This issue seems to be fixed some time ago. Mod loads properly, ```magenta_white``` color works fine.

Take a look:
![magenta_white](https://user-images.githubusercontent.com/5421954/36950232-466b0644-2004-11e8-90b9-e0a1e28e9e76.png)
