### ISSUE TITLE
Multi language display unintelligible text when attack and damage in Tiles 

### ISSUE THREAD

**Issue by wszgrcy** [CleverRaven/Cataclysm-DDA#22708]
Game version:7044

Operating system:win7 64

Tiles or curses:Tiles 

Mods active:None

### Expected behavior
In curses.It displays display properly in Games.
![image](https://www.z4a.net/images/2018/01/07/snipaste_20180107_230535.png)
[https://www.z4a.net/images/2018/01/07/snipaste_20180107_230535.png](url)
### Actual behavior
In Tiles : 
![image](https://www.z4a.net/images/2018/01/07/snipaste_20180107_230213.png)
[https://www.z4a.net/images/2018/01/07/snipaste_20180107_230213.png](url)
### Steps to reproduce the behavior
I think the Tiles couldn't support all language but English.(I think its bug with ansi and other language can not find character library)
So I think it can be sovled with using curses in display attack and damage,other with Tiles 
Or open api to allow multi language added.(like fallback.png file in ./gfx/ChestHole16Tileset)
my English is not good enough.If you want to know more infomations,please reply to me
Thanks.

**Comment by kevingranade** [comment]
Thanks for the detailed bug report.
I don't think the problem is as fundamental as you think it is, the SDL text drawing functions (used for text on the sidebar) are capable of drawing characters in the languages we need, something is just going wrong with the way they're being called.

**Comment by BevapDin** [comment]
> I don't think the problem is as fundamental as you think it is, the SDL text drawing functions (used for text on the sidebar) are capable of drawing characters in the languages we need, something is just going wrong with the way they're being called.

Only the curses-emulation (first picture above) does text rendering via SDL-TTF. `cata_tiles` (second image above) uses *only* the tiles loaded from PNG files - it does no text rendering at all.

`cata_tiles` is used to draw the main terrain window when the "Use tiles" option is true. The curses-emulation is used for all other windows - the printing seems to work there (thanks to SDL-TTF). But `cata_tiles` uses a completely different method of drawing - it's copying tile images instead of text rendering.

**Comment by wszgrcy** [comment]
@kevingranade Is it diffficult to add other language char in fallback.png(like ./gfx/ChestHole16Tileset)?
I browse tile_config.json but the character sequence seems to be preseted.
![image](https://www.z4a.net/images/2018/01/08/snipaste_20180108_072359.png)

**Comment by BrettDong** [comment]
It will be a nightmare if we put tens of thousands of Chinese/Japanese/Korean characters in a PNG image. A good solution would be utilizing GNU Unifont in drawing combat popup messages by some means.

**Comment by AMurkin** [comment]
Now drawing handled by `void cata_tiles::draw_sct_frame()`.

**Comment by Night-Pryanik** [comment]
I think this could be closed after implementing of SCT with unicode font.
