### ISSUE TITLE
Friendly NPC vocalizations.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#22712]
Currently NPCs have a small set of events that will cause them to vocalize, mostly reporting to the player that they have some status effect.

### Expected Behavior
NPCs make conversation, at least about tactical issues like losing sight of the player or spotting monsters.
### Actual behavior
NPCs only vocalize when they need something from the player.
### Steps to reproduce the behavior
Acquire a friendly NPC, move out of sight of the NPC.
When out of sight, debug spawn a monster in sight of the NPC.

This is spawned from #21282, which raises valid issues, but is a bit too broad. It was also derailed by an argument about implementation details.

**Comment by mlangsdorf** [comment]
At this point, NPCs could usefully shut up more.  Closing this issue.
