### ISSUE TITLE
NPCs responding to player sounds.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#22711]
Currently NPCs are effectively deaf, they only respond to visible threats or player-initiated speech.

### Expected behavior
NPCs respond to player-made sounds, 
### Actual behavior
NPCs are totally unaware of sounds.
### Steps to reproduce the behavior
(for convinience consider the player clairvoyance with debug menu).
Spawn a NPC near a wall where they cannot see the player.
Spawn one or more hostile zombies on the other side of the wall.
Make noise by walking around, firing guns, or shouting.
Observe the NPC not responding in any way.

This is spawned from #21282, which raises valid issues, but is a bit too broad.  It was also derailed by an argument about implementation details.

This would likely build on #22710, but doesn't strictly depend on it.

**Comment by mlangsdorf** [comment]
closing.  there is more to do but NPCs respond to sounds.  additional improvements should have their own issues.
