### ISSUE TITLE
New -2 z-level subway does not work with big cities

### ISSUE THREAD

**Issue by Syler1984** [CleverRaven/Cataclysm-DDA#22714]
Game version: 7046

Operating system: win10

Tiles or curses: tiles

Mods active: dosen't matter

### Actual behavior
In big cities (city size 13, for example) only 0 and -1 z-level of subway generated.
Small cities on the same map will have correct subway.

**Comment by Syler1984** [comment]
Actually, i just managed to find large city with correct subway.
Maybe this will help: https://www.dropbox.com/s/46irqa17bn7q80t/Fetters%20Hot%20Springs1.rar?dl=0

**Comment by BorkBorkGoesTheCode** [comment]
If it helps, my legacy game didn't spawn subways in overmaps if an old -1 subway entrance was present. Newly discovered overmaps weren't affected.

**Comment by ZhilkinSerg** [comment]
Existing overmaps won't be regenerated on loading of saved game. I really doubt we should provide some kind of migration for this as it can drastically change the world.

**Comment by Syler1984** [comment]
It's still a solid rock instead of subways if majority of big cities. Why was the issue closed?

**Comment by Solusphere** [comment]
According to this forum post this issue is unresolved: https://discourse.cataclysmdda.org/t/new-2-z-level-subway-bug/14774/4

Apparently Syler is experiencing the same problem on new maps as well, though I haven't verified it myself.

**Comment by Syler1984** [comment]
Here is the map with broken subways generated in the 7046 build.
https://www.dropbox.com/s/mq5iej8y38pqv2c/New%20Virginia.rar?dl=0

**Comment by ZhilkinSerg** [comment]
Sorry, I was under an impression that was all about loading of existing savegame. I can confirm that sometimes -2 level is not generated properly, especially in big cities.

**Comment by ZhilkinSerg** [comment]
People, I'm feeling very sorry for introducing this bug. The fix is ready.
