### ISSUE TITLE
Find or create a list of color IDs

### ISSUE THREAD

**Issue by trauerfall** [CleverRaven/Cataclysm-DDA#22728]
[https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MONSTERS.md#symbol-color](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MONSTERS.md#symbol-color)

![sbsck](https://user-images.githubusercontent.com/714017/34839280-12031ad0-f6cf-11e7-9ca3-02c11ee5e483.png)

just a simple asccii color palet becouse some like me dont know stuff about coding

----

Edit by @Leland: inlined image

**Comment by Leland** [comment]
Also note: #14808

**Comment by Night-Pryanik** [comment]
No discussion in almost a year, closing.
