### ISSUE TITLE
can't disassemble alternator with welder

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#22761]
Game version: 0.c-25577

Operating system: windows 7

Tiles or curses: tiles

Mods active: some, none applicable to this issue

Alternators can be repaired with welders, but not disassembled with them.  This creates a chicken and egg problem with soldering irons, it's difficult to get the power converter required to make them without already having a soldering iron.

[edit]
toning down some of the intensity

**Comment by Xpyder** [comment]
here's my mod list in case it comes up


Dark Days ahead
filthy clothing
disable npc needs
simplified nutrition
makeshift items
more survival tools
alternative map key
folding parts pack
vehicle additions pack
tanks and other verhicles

**Comment by Night-Pryanik** [comment]
> it's almost impossible to get the power converter required to make them without already having a soldering iron.

Power converters are easily obtainable by disassembling microwaves, toasters or television sets, and you don't need soldering irons for this.

I presume that your problem is more of a how to get power converter rather than that alternator couldn't be disassembled with welder alone?

**Comment by Xpyder** [comment]
Ok, I'll assume you can probably get one of those by around the time you should be getting a soldering iron.

Do you reliably get the converters from them at low electronics levels (where you would be before you can get a soldering iron)?  I know with some disassembly you lose items if your skill is too low

**Comment by Xpyder** [comment]
This originated because I made a firearms kit that ate my only soldering iron and it wasn't clear how to get the parts to make another.  But that can be reversed now

**Comment by Night-Pryanik** [comment]
> Do you reliably get the converters from them at low electronics levels (where you would be before you can get a soldering iron)?

I didn't test it, but TV sets are ubiquitous, so you have a lots of tries. 
Second, even if alternators were disassemblable with welders, you still could lost power converters from low skill.

**Comment by Xpyder** [comment]
I admit I haven't been watching for TVs, but I don't recall them being ubiquitous.  Do most houses have a console I'm missing or something?

Alternators live in every car, also is there any reason we shouldn't be able to use welders in place of irons to disassemble alternators?
