### ISSUE TITLE
Thick Sludge Trail does not appear when using Look Around hotkey

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#22762]
Game version: Experimental 7028

Operating system: Windows 7 64-bit

Tiles or curses: Tiles

Mods active: Default (Dark Days Ahead, Filthy Clothing, Disable NPC Needs, Simplified Nutrition)

### Expected behavior
Examining tiles with Look Around hotkey (default 'x') should list "thick sludge trail".

### Actual behavior
Examining tiles with Look Around hotkey (default 'x') doesn't list "thick sludge trail".

### Steps to reproduce the behavior
Spawn "Sludge Crawler" monster and there will be two types of sludge trails made: thick sludge trail and sludge trail. Examine with Look Around hotkey.
![sludgetrailasexpected](https://user-images.githubusercontent.com/32253888/34922269-eb1aeb72-f94a-11e7-9808-a4ce6eea149e.png)
![sludgetrailprompt](https://user-images.githubusercontent.com/32253888/34922276-06f40b6c-f94b-11e7-9494-79e588a41560.png)
![thicksludgetrailmissing](https://user-images.githubusercontent.com/32253888/34922336-b35bcb88-f94b-11e7-9b33-df4d6c3506d3.png)
![thicksludgetrailprompt](https://user-images.githubusercontent.com/32253888/34922344-cb7ec148-f94b-11e7-8fd6-4892cd728349.png)

**Comment by Night-Pryanik** [comment]
The text is here, but its color is black, so it is invisible on the black background.
