### ISSUE TITLE
Dead corpse pulped status is not saved.

### ISSUE THREAD

**Issue by raycrasher** [CleverRaven/Cataclysm-DDA#22766]
Game Version: 2960fe33cffd21601f934e76d24781c5aa40f885 (git sha1)
Operating system: Win10 64-bit
Tiles or curses: Tiles
Mods active:
dda, DinoMod, FIC_Weapons, Medieval_Stuff, More_Survival_Tools, RL_Classes, StatsThroughSkills, blazemod, Tanks, alt_map_key, bio_mod, boats, craftgp, brightnights, deoxymod, ew_pack, filthy_morale, makeshift, more_buildings, more_classes_scenarios, more_locations, national_guard_camp, necromancy, nw_pack, realguns

Steps to reproduce:

1. Pulp a corpse by smashing
2. Save game
3. Load game
4. Corpse is not pulped anymore.

**Comment by AMurkin** [comment]
You've missed valuable part of an issue description:

> Game version:
> Operating system:
> Tiles or curses:
> Mods active:

**Comment by raycrasher** [comment]
Sorry, added description.

**Comment by Night-Pryanik** [comment]
Tested right now on latest experimental - pulped state is saved on save-and-load. 
Closing for now, if anyone else encounters this issue, feel free to ping me.

**Comment by raycrasher** [comment]
I resolved the issue, it was compiler related floating point issue.
I was using MSVC 2017, 32-bit, release.
Issue is resolved if compiled in 32-bit debug, or 64-bit release/debug.
