### ISSUE TITLE
wish menu missing

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#22763]
Game version: 0.C-25577

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: 

Dark Days ahead
filthy clothing
disable npc needs
simplified nutrition
makeshift items
more survival tools
alternative map key
folding parts pack
vehicle additions pack
tanks and other verhicles

### Expected behavior
I expected to find Wish for Item under either keybinds, or the ESC menu with DEBUG mode active

### Actual behavior
it's not there

### Steps to reproduce the behavior
start a game, go to keybinds, search for "wish"

**Comment by Night-Pryanik** [comment]
It's called Debug Menu in keybindings.

**Comment by Xpyder** [comment]
Thanks, I figured it had been moved or renamed, but I searched both issues and forums and couldn't find any reference for what it had been moved to.
