### ISSUE TITLE
firearm repair kit unreversable

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#22760]
Game version: 0.c-25577

Operating system: windows 7

Tiles or curses: tiles

Mods active: some, none are applicable to this issue

### 
Firearm repair kit doesn't seem to have any reason to be non-reversible
By itself it's not a big issue, but making this kit consumes a soldering iron which is almost impossible to make without already having one (can't make power converter, nor disassemble an alternator to get a power converter, without already having a soldering iron)

**Comment by Xpyder** [comment]
here's my mod list in case it comes up

Dark Days ahead
filthy clothing
disable npc needs
simplified nutrition
makeshift items
more survival tools
alternative map key
folding parts pack
vehicle additions pack
tanks and other verhicles

**Comment by baraba3** [comment]
power converter isnt that hard to find-try computer consoles-you have two in your starting shelter or dissasemble televison or toaster thoguht i am not sure if sedond need soldiering iron,

i always make my soldiering iron and never had problem with making it.

**Comment by Xpyder** [comment]
Gotcha, didn't realize you could find them inside consoles
