### ISSUE TITLE
Friendly NPCs will walk towards live grenades I throw

### ISSUE THREAD

**Issue by Proxiehunter** [CleverRaven/Cataclysm-DDA#22770]
Game version:
7054
Operating system:
Windows (WINE)
Tiles or curses:
Tiles
Mods active:

### Expected behavior
NPC does not move towards the live grenade I just threw even if there are targets for them to melee, moves away if the blast radius might catch them. Anything intelligent enough to recognize a live grenade or other explosive should begin moving away from the potential blast radius once it's thrown.
### Actual behavior
NPC moves towards the live grenade in order to engage in melee combat with monsters I'm trying to blow up, tries to get blown up along with the monsters.
### Steps to reproduce the behavior
Throw a live grenade at monsters your friendly NPC would advance to fight in melee.

**Comment by Cyrano7** [comment]
Same behavior observed in 0.C-25784-g26f6c2e (tiles) for me.
