### ISSUE TITLE
Batch cleaning of clothes

### ISSUE THREAD

**Issue by DanielPBak** [CleverRaven/Cataclysm-DDA#22776]
It's extremely annoying cleaning a large amount of clothing, requiring a large number of key presses to clean a single item. This is difficult if you are cleaning a large number of clothing, or 10 kevlar patches or something. There should be a way to do this more efficiently.

**Comment by Night-Pryanik** [comment]
#21650 is meant to address this issue..

**Comment by DanielPBak** [comment]
I don't think it addresses it fully... even with a washboard, you shouldn't need to do all of these key pressed and spend all this (real life) time.

**Comment by Night-Pryanik** [comment]
Well, how do you see it working then?

**Comment by DanielPBak** [comment]
I think, rather than selecting a single item and washing it, you should be able to tag multiple items (similarly to how one grabs items off the ground) and wash them in bulk at once.

**Comment by Night-Pryanik** [comment]
Make a PR then.

**Comment by Nhatorama** [comment]
When I played on Windows, I used AutoHotKey for any repetitive things I wanted to do, like:

- tilling(with a hoe)/planting/harvesting vast tracts of land
- unloading containers (usually pickled food)
- making clean water (didn't have water_purifier/FOODCO yet)
- giving follow/guard commands to my NPC followers.
- prior to the nerf, throwing training by throwing bones at the max range

Now that I'm on Linux I use AutoKey.

**Comment by Night-Pryanik** [comment]
@DanielPBak any luck on your plans?

**Comment by DanielPBak** [comment]
I haven't had much time and the cleaning code is more complex than I thought.

**Comment by Night-Pryanik** [comment]
Of course, ask freely!

**Comment by DanielPBak** [comment]
What's the best way to reach you? On here?

**Comment by DanielPBak** [comment]
I have to admit that I'm having a lot of difficulty with this.

So, I basically want to replace the "wash what?" menu, where a single item is selected, with a menu where multiple items are selected, and the required amount of time, water and soap is displayed in the top right corner, out of their maximums.

I don't know how to get started on this. I was thinking I'd be able to use the inventory menu as a template, but I don't know how to get started on that either. I'm sorry that this is such a general question, but what should I be doing or looking into? Is there a function I should know that generates a multiple-tag window, as opposed to a single one?

**Comment by RogueYun** [comment]
I had an idea, but I am not sure of the difficulty to implement. Perhaps it may be an easier alternative to your idea.

A "Wash Basin" something like a brazier in simple structures that can be placed/taken down/replaced.
(Made from a washboard + some large container/bucket?)
- Would have a limited volume but could hold several large clothing items (Say 20-40 liters?).
- Would need a large amount of water nearby.
- Stuff full of filthy laundry.
- One would "apply" soap or detergent to use. (Alternatively maybe a fire nearby so the water/clothes could be sterilized)
- All items in the basin would be washed over an extended period of time.
- The PC would complain about having raisin fingers.

**Comment by Night-Pryanik** [comment]
Closed by #23588.
