### ISSUE TITLE
Random results from crafting

### ISSUE THREAD

**Issue by TinkerWorX** [CleverRaven/Cataclysm-DDA#22786]
This is a simple suggestion that expands recipes to be able to give random results from crafting. The idea came up as means to make a basic research system using the existing crafting system.

Making it backwards compatible should be trivial. If we look at the code below, that's how results are written now. This is basically a 100% chance to get 1 balclava.
```json
{
  "result": "balclava"
}
```
It would be functionally equivalent to the following, where the result is 1/1(100%) chance of getting a balclava.
```json
{
  "result": [
    [ 1, "balclava" ]
  ]
}
```

For advanced uses in line with a research system, here's an example for researching foods in early game.

```json
{
  "result": [
    [ 10, "food_research_note_1" ],
    [ 10, "food_research_note_2" ],
    [ 10, "food_research_note_3" ],
    [ 10, "food_research_note_4" ],
    [  1, "food_research_note_5" ],
  ]
}
```
The above system would have a 10/41(~24%) chance of producing a research note 1, 2, 3 or 4. And a 1/41(~2%) chance of producing research note 5. In this example, each research note would be a book with a single recipe. This method of research could be used to to replace various auto-learn recipes as well to make it a bit more interesting and 

The system can be used for other things as well, and could be expanded to work with byproducts as well, to make things like cattail give a variable amount of plant fiber instead of a fixed amount.

**Comment by TinkerWorX** [comment]
Here's an alternative way to do the weighted results with the same effect.
```json
{
  "result": {
    "food_research_note_1" : 10,
    "food_research_note_2" : 10,
    "food_research_note_3" : 10,
    "food_research_note_4" : 10,
    "food_research_note_5" :  1,
  }
}
```

Might be a little less prone to errors, but it means the same item can't be added multiple times, which might have a use case even if I can't think of one right now.

**Comment by ZhilkinSerg** [comment]
Can you please give usage examples in more details?

Here is the branch which allows to define item group as recipe result - https://github.com/CleverRaven/Cataclysm-DDA/compare/master...ZhilkinSerg:recipe-results?expand=1.

There is some drawback currently - you will see random item from the group as recipe result in crafting menu (it does not show the actual result of the crafting).

Example:

````
  {
    "result": "chestwrap",
    "result_group": "group_recipe_chestwrap",
    "result_label": "chestwrap or bionic toolset",
    "type": "recipe",
    "category": "CC_ARMOR",
    "subcategory": "CSC_ARMOR_TORSO",
    "skill_used": "tailor",
    "time": 1000,
    "reversible": true,
    "autolearn": true,
    "components": [ [ [ "rag", 9 ] ] ],
    "flags": [ "BLIND_HARD" ]
  },{
    "type" : "item_group",
    "id" : "group_recipe_chestwrap",
    "subtype": "distribution",
    "items":[
      ["chestwrap", 10],
      ["bio_tools", 10]
    ]
  }
````

![default](https://user-images.githubusercontent.com/16213433/35197775-e0340a4e-fef5-11e7-9a33-7b11785f777e.png)

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
