### ISSUE TITLE
Vehicle Automatic Water Purifier not working

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#22781]
Game version: 0.C-25577

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: 

Dark Days ahead
filthy clothing
disable npc needs
simplified nutrition
makeshift items
more survival tools
alternative map key
folding parts pack
vehicle additions pack
tanks and other verhicles

### Expected behavior

Vehicle Water Purifier should purify water

### Actual behavior

Turned it on at vehicle controls, waited 1h none of my waters changed

### Notes
Tried with dirty water in tank under purifier, and clean water in another tank
Tried with clean water in tank under purifier, and dirty water in another tank

I can purify the tank by manually activating the purifier

It's possible there's some other way to make it work but if so it's not clear how it's supposed to function?

**Comment by TinkerWorX** [comment]
The purifier isn't automatic. [e]xamine the part it's attached to and select the purify option.

**Comment by Leland** [comment]
Closing per above. @Xpyder let me know if that doesn't resolve it and this can be reopened.

**Comment by Xpyder** [comment]
Purifiers are supposed to be automatic now per #21095 (unless I'm misreading it?)

**Comment by TinkerWorX** [comment]
Did you try with a funnel on it?

**Comment by Xpyder** [comment]
I didn't.  From the way that update was worded it sounded like they will auto-purify water in the tanks they're sitting on?

**Comment by LordZanos** [comment]
It autopurifies water that comes in through funnels. If you want to purify an entire tank, you can just activate the purifier and do it all at once instantly.

**Comment by Xpyder** [comment]
so you're sure that edit wasn't supposed to make it purify water over time?  Because that's listed as a separate bullet point, and listed with an "and" not an "if".  I got the impression it was trying to make steps towards doing away from the instant purification

**Comment by Ishindri** [comment]
When I attempt to activate the water purifier, the 'purify water in carried container' and 'purify water in vehicle tank' options are greyed out. I'm not certain why, I think I have everything set up correctly - tank and purifier installed on the same tile, with plenty of available power.

**Comment by int-ua** [comment]
Please update the description to match current status, preferably adding steps to reproduce.
