### ISSUE TITLE
segfault on saving whilst entering tutorial with soundpack - unreproducible in debug build

### ISSUE THREAD

**Issue by draeath** [CleverRaven/Cataclysm-DDA#22785]
Game version: commit 1e592d76b7
Operating system: debian stretch 64-bit - gcc (Debian 6.3.0-18) 6.3.0 20170516
Tiles or curses: tiles
Mods active: ChestHoleSoundSet.zip retrieved 1/19/2018

Build args:
```
make -j$(nproc) RELEASE=1 TILES=1 SOUND=1 LUA=1 USE_HOME_DIR=1 LTO=1 DYNAMIC_LINKING=1
```

When running `RELEASE=1` and with the ChestHole sound set enabled, I crash immediately upon entering the tutorial, with a segfault. While otherwise useless due to symbol stripping, using gdb allowed me to see the last update to the screen before the crash - it was saving the game.

The crash occurs every time. If I disable the sound pack, it stops crashing.

Now, here's where it gets irritatingly odd: if I remove `RELEASE=1` I cannot reproduce the problem, so I'm unable to provide a useful backtrace or coredump.

**Comment by BrettDong** [comment]
If you add switch `DEBUG_SYMBOLS=1` in the `make` command, the executable will not be stripped.

**Comment by draeath** [comment]
I can no longer replicate the problem, with or without `RELEASE=1`.

Strange, as I've not made any other changes to the system meanwhile.

Oh well. If I see it again and can manage to get some usable debug information, I'll reopen.
