### ISSUE TITLE
Pouring liquid from vehicle's tank causes "could not find source vehicle" error

### ISSUE THREAD

**Issue by Erquint** [CleverRaven/Cataclysm-DDA#22784]
Game version:  
0.C-25599-gf0a1b1f  
Operating system:  
Kubuntu 17.10  
Tiles or curses:  
Tiles  
Mods active:  
Lots of pre-packaged ones — see the list in the attached save file.  

Found, drove, renamed and modified an RV.  
Cut down on size and added lots of 60L tanks to it. Filled those with various liquids.  
When trying to siphon any liquid from the vehicle — I get the usual prompt for target.  
Drinking works. Trying to pour into a container or spill onto the ground tiggers the following exception after choosing a receiving container or a ground tile:  
`could not find source vehicle for liquid transfer`  
**The transfer does not take place.**  
If I insist, ignore the error messages and try again a few times — the game crashes(rate of crashes due to this behaviour seems inconsistent).  

Tried spawning in another RV, fitting 60L tanks onto it and filling them with various liquids, followed by an attempt to siphon from it — no problem there. Which makes me believe a particular vehicle just bugged out. Gonna try building a new one just like it from scratch. More on that later...

Found one report of this issue on Reddit from 7 months ago:  
https://www.reddit.com/r/cataclysmdda/comments/6i719t/cant_transfer_any_liquids_from_vehicle_tank_ver/  

Attached is a backup of the world save. Some bismuth and welding tanks have been cheated in due to mod specifics and accidents, also the monster speed has been tweaked after creation but no further tampering have taken place otherwise IIRC. The main issue should be fully reproducible with this save, but the crashing may be inconsistent.  
[Gaia.9.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/1645395/Gaia.9.tar.gz)

**P.S.**  
The kitchen unit, installed, doesn't provide water faucet options when examined, as well as the dedicated water faucet installed in the same square as the water tank.  
(Looking back, that might've been due to only supporting explicitly clean water, while it was filled with well water)  
**P.P.S.**  
Attempting transfers to other vehicles produces the same error message without transfer taking place before the receiving tank is chosen.  
**P.P.P.S.**  
Built an identical vehicle from scratch — no problem with it.

**Comment by Nhatorama** [comment]
I'm getting something similar when I siphon water from my vehicle's (not built from scratch) 60L tank to another 60L tank on the ground on my Manjaro Linux PC.
I don't get the usual debug pink writing, but instead I crash to desktop and the terminal says:

`terminate called after throwing an instance of 'std::logic_error'`
`what():  basic_string::_M_construct null not valid`
`Aborted (core dumped)`

**Comment by Amariithynar** [comment]
Getting a related error, I think.

Error has occurred!
DEBUG: cannot determine reload cost as bucket of concentrated acid is neither ammo or magazine

FUNCTION: int player::item_reload_cost(const item&, const& item, long int) const
FILE: src/player.cpp
LINE: 7803

Happens when I try to (r)eload a container from another container.
