### ISSUE TITLE
Vehicle Drop Bay

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#22782]
One thing that I'd love to have available ingame is a small vehicle storage area that upon being triggered from the driver's seat, (a)ctivates its contents and drops them on the ground beneath the car. This allows you to create "bomber" vehicles, drop distracting items such as talking dolls/firecrackers, and probably has all sorts of utility I haven't thought of yet.

Ideally this would come with the ability to preset a timer for items that require them, such as mininukes, but that might be too complex to easily implement. Emptying liquid containers to create an acid or gasoline slick might be nice too, especially if it could drop a match or other ignition source to ignite it, but again that's not required. Just allowing items that only require initial activation, such as grenades, would be acceptable and useful.

**Comment by Nhatorama** [comment]
As far as I know this can be done already, although the method is a bit awkward.

The method involves using the advanced inventory management.

1. Activate grenade/nuke/time_delayed_explosive.
2. Bring up the advanced inventory management window.
3. Decide on what tile you want to drop the ordnance in and have both windows point to said tile. One side will look at the ground and the other will look at your seat/container/door/etc tile.
4. On the window showing the vehicle tile, press the `i` key, and transfer the active ordnance to the ground tile.
5. Move away from the location (hopefully you didn't activate the ordnance while you were parked).
6. Boom!

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
