### ISSUE TITLE
Repairing vehicle parts with integrated toolsets lets you use a nonexistent 'nearby' toolset

### ISSUE THREAD

**Issue by Yewmi** [CleverRaven/Cataclysm-DDA#22789]
Game version: **0.C-25863-g33d1893**

Operating system: **Windows 10 (64-bit)**

Tiles or curses: **Tiles**

Mods active: 
- StatsThroughSkills IV
- Filthy Clothing
- Disable NPC Needs
- Simplified Nutrition
- Alternative Map Key

### Expected behavior
Upon repairing a vehicle part with the required bionic charge, after the repairing is finished I expected for the part to be repaired and for my character's power to be consumed

### Actual behavior
Once the repair process is finished, I'm presented with this:
![cataclysm-tiles_2018-01-19_15-03-36](https://user-images.githubusercontent.com/22177874/35172032-b2fe792c-fd2b-11e7-8d45-98e3b6b3f889.png)
Choosing the "nearby" integrated toolset repairs the vehicle without consuming any of my own bionic power. The nearby toolset always has the same charge as my current charge, but is never depleted. Position seems to not matter either; no matter where I'm standing when I do repairs, I'm presented with this option.

### Steps to reproduce the behavior

1. Repair a vehicle part normally while having an Integrated Toolset CBM installed and with enough CBM power to fix the part.
2. Select the "nearby" Integrated Toolset as your repair tool, _not_ the "on person" one.

**Comment by baraba3** [comment]
happens with ordinary tools at least makeshift welder i used.also tool if in inventory doenst seem to lose charge.

**Comment by Syler1984** [comment]
It happens with all car repairs consumables. You can even swap broken tire with non-existing 'nearby' tire (same for broken frames, welder charges etc).

**Comment by pipehat** [comment]
Just observed this with vanilla config (default core mods, none added) - and a normal welder. Two options:
1) welder nearby (100/500 charges)
2) welder on person (100/500 charges)

Selecting option 2 burns down charges as expected and in the future the two options show the updated current charges of the welder, e.g.: 100/400 next time.

Selecting option 1 (nearby) consumes no charges from the welder. Also, there is no other welder nearby.

**Comment by l29ah** [comment]
68d71f36ea21aee85bf8ebe237b08935440b799f is the first bad commit

**Comment by Isaacssv552** [comment]
It looks like a comp_selection<item_comp> with
selected.use_from = usage::use_from_map;
selected.comp = map_has[uselection];
is being sent to who.consume_items and this is somehow failing.

**Comment by illi-kun** [comment]
@Isaacssv552 Please use [keywords](https://help.github.com/articles/closing-issues-using-keywords/) to close the fixed issue automatically.
