### ISSUE TITLE
Lit refillable lighter can't be used to smoke tobacco pipe

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#22797]
Game version: 0.C-25577

Operating system: Windows 7

Tiles or curses: Tiles

Mods active:

Dark Days ahead
filthy clothing
disable npc needs
simplified nutrition
makeshift items
more survival tools
alternative map key
folding parts pack
vehicle additions pack
tanks and other verhicles

### Expected behavior
Should be able to smoke tobacco using a pipe, rolling tobacco, and a refillable lighter

### Actual behavior
doesn't work even with the lighter "lit"
also, seems like I should be able to smoke by activating the pipe, not just the tobacco, it's confusing as is

### Steps to reproduce the behavior
start as a senior citizen
try to smoke

**Comment by Leland** [comment]
Wonder if @ZhilkinSerg's #22703 would fix this

**Comment by ZhilkinSerg** [comment]
> Wonder if @ZhilkinSerg's #22703 would fix this

Starting as senior citizen, having `tobacco pipe` with `refillable lighter` in inventory and activating `plastic bag with rolling tobacco` uses 1 charge of `refillable lighter` and 1 charge of `plastic bag with tobacco` in build with changes from #22703.

![image](https://user-images.githubusercontent.com/16213433/35280639-dbd5576a-0061-11e8-9ce4-7efd62b090e0.png)

**Comment by Leland** [comment]
Nice, thanks for testing that. Make sure to add to your PR so this autocloses! 🍻
