### ISSUE TITLE
First game crash I've experienced.

### ISSUE THREAD

**Issue by redJake11** [CleverRaven/Cataclysm-DDA#22807]
Game version: 0.C-26014-g249d508 or Build 7081

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Dark Days Ahead, Makeshift items mod, More survival tools, More buildings, Tall buildings,
Boats, Folding Parts Pack, Tanks and other vehicles, Classes and scenarios mod, Disable NPC needs,
Filthy clothing, Simplified Nutrition

 I had just begun a new game with a random build, A bionic FIrefighter! Spawned in a building with an NPC, and found no weapons. Firefighter gear apparently makes 7 sound, so zombies broke in through both doors, and I was completely surrounded. The only weapon I had were a pair of combat boots, with Bash 1 and -1 to hit. being completely surrounded, I held TAB to auto-attack enemies. This is when the game crashed.  I have no idea what caused this. The save file of the firefighter is gone as well.

**Comment by Leland** [comment]
Any chance you're able to reproduce this?

**Comment by redJake11** [comment]
Likely not, It was a random character whose stats I can't recall, and the save file is also gone.

**Comment by Night-Pryanik** [comment]
I'm afraid we can't do anything with this non-reproducible issue and with no save file.
