### ISSUE TITLE
IFF transponder for friendly NPCs to keep them from getting shot by player-placed turrets

### ISSUE THREAD

**Issue by gynoidgearhead** [CleverRaven/Cataclysm-DDA#22801]
A suggestion for a new feature: some kind of craftable Identify Friend or Foe (IFF) transponder that you could command your followers to wear, so that they don't get shot if they walk past turrets you've set up. This would presumably solve a lot of NPC deaths that would otherwise require extensive coding in order to make them not walk in front of the turrets.

I suppose this might be a little more complicated than either the code supports or is supposed to be achievable by a survivalist hacking things together. Still, I figure it's worth asking about.

**Comment by Zireael07** [comment]
Might want to add "your" before "turrets", as the whole point of the game-placed turrets is that their IFF went haywire beyond repair. For your own turrets, this is a very reasonable suggestion.

**Comment by GearheadLydia** [comment]
Fixed, thanks.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
