### ISSUE TITLE
Bullets do not pass through metal bars or over display rack.

### ISSUE THREAD

**Issue by Vkotl** [CleverRaven/Cataclysm-DDA#22814]
Game version:
7081

Operating system:
Windows 7 64x

Tiles or curses:
Tiles

Mods active:
Tested without mods at all.

### Expected behavior
Being able to fire bullets through a window frame with metal bars.

### Actual behavior
Bullet doesn't pass through the window frame with metal bars. Neither when pressed right up against it or from a distance. Seems to act as a regular wall.

### Steps to reproduce the behavior
1. Go into a gun store.
2. Break the window.
3. Try to shoot through a window frame that has metal bars.
Assumption - Gun is equipped and loaded.

**Comment by Night-Pryanik** [comment]
The same with chain link fence.

**Comment by ElonSatoshi** [comment]
Should we edit the objects to let bullets through, or edit the bullets to pass through those objects?

**Comment by BorkBorkGoesTheCode** [comment]
Attaching object behavior to bullets will make adding other porous terrains harder. Overpenetration should be a thing, but that is a side issue.
