### ISSUE TITLE
Some UI elements are not drawn

### ISSUE THREAD

**Issue by Soadreqm** [CleverRaven/Cataclysm-DDA#22816]
Game version: 0.C-26019-gee317fe

Operating system: Win 7

Tiles or curses: Tiles version, with tiles disabled

Mods active: "dda",  "filthy_morale",  "no_npc_food",  "novitamins"

Some user interface elements, such as the examine prompt for looking at a closed window, are only displayed the first time you look at them. The second time you look at the interface, it's not shown, unless you've looked at a different interface in the meantime.

It also seems to happen with the activate/eat/read/wear/etc box when looking at some items in inventory, but not all the time. Looking at my briefs works as intended, but looking at my socks doesn't.

The easiest way to see this is to start in a shelter, peek outside by examining a window, and then examine the window again. That seems to reliably fail every time.

**Comment by Night-Pryanik** [comment]
> The easiest way to see this is to start in a shelter, peek outside by examining a window, and then examine the window again. That seems to reliably fail every time.

Tested right now. Examined closed window with curtains, chose "Peek through the curtains", peeked through them. Then examined the same window again. I was able to successfully peek every time I examined the same window, again and again.

**Comment by AMurkin** [comment]
Not sure that is the same issue, but i've recorded mine:

![gif](https://user-images.githubusercontent.com/1931904/35470182-d5911140-0355-11e8-9aa0-4e3cab817fd3.gif)

**Comment by Soadreqm** [comment]
@Night-Pryanik did you have tiles on or off? I tried it a few more times, and it doesn't seem to happen when I turn tiles on. Also doesn't seem to happen when the interface is drawn on top of the sidebar, instead of the main game area.

With "use tiles" set to false, I get this every time:

![2018-01-27 13_06_13](https://user-images.githubusercontent.com/6437763/35471415-4af60f1e-0363-11e8-9e57-bf425b136f5e.png)

**Comment by Night-Pryanik** [comment]
I tried it on one of the latest experimentals, tiles off.

**Comment by Soadreqm** [comment]
Well, I don't know why it would be happening only to me. I do know it was still working in version 0.C-7068, but in versions 0.C-7082 and 0.C-7083, straight out of the zip file, no config changes save for disabling tiles, I get what's in the screenshot I posted. If I increase the window size, the prompt isn't displayed at all.

It still works, I can peek out the window, but the menu is invisible.
