### ISSUE TITLE
Apply electrical damage to electricity-based ranged weapons

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#22817]
Game version: 0.C-7083

Operating system: Windows XP SP3 x86

Tiles or curses: curses

Mods active: default only

### Expected behavior
Electricity-based ranged weapons (such as Chain Lightning CBM or Tesla gun from Blazemod) should hit targets with electricity damage type (`DT_ELECTRIC`). Hitting electricity-immune critters with these weapons shouldn't harm them at all.
### Actual behavior
Firing from Chain Lightning acts much like firing from an ordinary rifle, dealing cutting damage and thus hurting shockers.
### Steps to reproduce the behavior
Try to shoot shocker with Chain Lightning bionic.

**Comment by John-Candlebury** [comment]
Making the other damage types usable would be good too, for example:

-The flamethrower bullets dealing DT_HEAT
-Artifact weapons dealing DT_TRUE would probably make them much more useful.

**Comment by vlad1492** [comment]
Another example: tesla cannon firing from turret chassis.  Bounce hits player with cutting damage, even if player is wearing hazmat / ANBC suit.
