### ISSUE TITLE
Massive increase in time needed to disassemble after upgrading to the latest build

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#22832]
Game version: experimental build 7089

Operating system: linux

Tiles or curses: tiles

Mods active: filthy clothes, no religious texts, no antique firearms, disable npc needs

### Actual behavior
After manual upgrade from build 7079 to 7089 time to disassemble things became approximately one order of magnitude higher. For example, it became 5 hours for chemical set. Season length is 45 days.

**Comment by ZhilkinSerg** [comment]
Could be related to #22818 and/or #22790.

**Comment by AMurkin** [comment]
Time description only changed at the items info, not at the Disassemble item window.
