### ISSUE TITLE
CBM descriptions describe installed bionics not the CBM package.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#22836]
Game version: build 7090

Operating system: Windows

Tiles or curses: Tiles

Mods active: None

### Expected behavior
When you look at a CBM it should describe the bionics that it installs, and what it does when installed. For example, the advanced microreactor CBM installs the 'advanced microreactor system' bionic and the 'plutonium purger' bionic.

### Actual behavior
The description of the CBM is the same as the description of an installed bionic. For example the 'Uncanny Dodge CBM' description is:

'Your nervous system has been augmented with bionic processors, allowing you to dodge attacks beyond normal human capability, including bullets.'

And not something like:
'This bionic when installed, gives you the ability to dodge attacks, and even bullets beyond normal human capacity'

While granted these are minor description errors, there are a few descriptions that don't match up (fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/22835 btw). Some others don't make sense at all, like the advanced microreactor CBM, which doesn't tell you it also installs the plutonium purger bionic, and which has a pretty bad description anyway. So that could be fixed by better CBM item descriptions.

Or, if we consider this to much work, and don't mind the CBM's describing the bionic which it installs, we have the issue of json code duplication, where the description exists in both the 'json/bionics.json' file and the 'json/items/bionics.json' file. One of which should then be deleted, and just use the description of the other imho.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
