### ISSUE TITLE
Screen is being drawn twice per turn on tiles

### ISSUE THREAD

**Issue by Wulfe813** [CleverRaven/Cataclysm-DDA#22839]
Game version: Unknown build between approx. 6350 up to current master

Tiles or curses: Tiles

I'm fairly certain the screen is being refreshed an extra time per turn in the Tiles build. Android port UI elements not being drawn made me suspect this. I disabled the disabled the display buffer and sent all the draws directly to the screen, and took some screenshots that demonstrate the issue. These both come from recent master, ported to Android. The second one is with the display_buffer bypassed, and all drawing going directly to the screen.

Normal:
https://www.dropbox.com/s/krz5gd92nmmls9c/Screenshot_2018-01-31-19-24-32.png?dl=0

No buffer:
https://www.dropbox.com/s/h3uc1czzk6fmqsc/Screenshot_2018-01-31-19-28-57.png?dl=0

With the display buffer bypassed, the shortcut bar magically appears. You can also see a small margin at the bottom that is the result of a resize operation used in the Android port, and is not present in the first screenshot. It seems apparent that the screen is being redrawn from the display buffer sometime after refresh_display() is called. That's not intentional, right? This is also causing a small but significant hit to draw time.

**Comment by Graywolfe813** [comment]
Can't confirm on other platforms, appears to be an Android specific issue.

**Comment by ZhilkinSerg** [comment]
Do we still have an issue after reversal of reversal?

**Comment by kevingranade** [comment]
Yes, it's back to drawing redundantly.
AFAICT the fix is to audit everywhere that calls draw_ter() to insure that it eventually calls wrefresh(wterrain).
