### ISSUE TITLE
Hallucination Attacks Reset Broken Limb Healing Progress

### ISSUE THREAD

**Issue by Curt5** [CleverRaven/Cataclysm-DDA#22849]
Game version: 7093 0.Cooper

Operating system: Windows

Tiles or curses: Tiles

Mods active: Several, none expected to be a cause.

### Expected behavior
Being attacked by hallucinated monsters (via Schizophrenia trait) does not actually damage the player.

### Actual behavior
If attacked by hallucinated monsters and hit in a splinted and healing broken limb, this re-breaks the limb.

### Steps to reproduce the behavior
1: Create character with Schizophrenia trait
2: Break a limb
3: Wait for hallucinations, and be attacked
4: Observe health screen.

**Comment by Night-Pryanik** [comment]
This was addressed by #21359.
