### ISSUE TITLE
Multi-tile travois collides with errors in movement code

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#22853]
Game version: 0.C-26138-gc5ce634 (tiles) [7097]

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Loads

### Expected behavior
Building a multi-tile travois worked fine in previous versions. Typically it's 2 or 3 tiles in a single row.

### Actual behavior
A second wooden frame results in no issues, the travois can be dragged with no problem. The second installed travois produces the error.

### Steps to reproduce the behavior
Build a vehicle from two wooden frames, add one travois and drag. Add a second travois and try dragging; error should result.

**Comment by chrahunt** [comment]
Able to reproduce consistently by doing the following:

Construct a vehicle with 3 light wood frames oriented horizontally (material does not matter, order of part placement does not matter)

```
XXX
@
```

Grab the leftmost segment (starting position doesn't matter) and walk left until the vehicle is oriented vertically.

```
 X
 X
@X
```

or

```
@X
 X
 X
```

If you are closest to the top segment try to go down 2 times, if you are closest to the bottom segment try to go up 2 times.

The second movement will result in the same error as given by @bouchacha.

This doesn't seem to happen when the frames are oriented vertically, the vehicle splits diagonally as-needed when being dragged.

**Comment by chrahunt** [comment]
Related to #20640.

**Comment by Night-Pryanik** [comment]
Closing in favor of #23000.
