### ISSUE TITLE
No option to change morale via debug menu

### ISSUE THREAD

**Issue by chrahunt** [CleverRaven/Cataclysm-DDA#22879]
Game version: ed53328 (git master)

Operating system: Ubuntu 16.04.3

Tiles or curses: Tiles

Mods active: None

### Expected behavior

1. Have low morale, but need to test something requiring higher morale (e.g. construction)
2. Open Debug menu
3. Select option to set morale or Select option to edit NPC, choose self, select option to set morale
4. Set morale

### Actual behavior

1. Have low morale, but need to test something requiring higher morale (e.g. construction)
2. Open Debug menu
3. Spawn mp3 player
4. Activate mp3 player and wait a few minutes for morale to improve

### Steps to reproduce the behavior

N/A

**Comment by ZhilkinSerg** [comment]
I will try to code it.
