### ISSUE TITLE
`Out of  !` message when reloading tools

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#22887]
When you try to reload non-full tool (e.g. `flashlight (49)`) and you have no corresponding ammo you get message: `Out of  !`

Has anyone else seen this?

# Screenshots:

![default](https://user-images.githubusercontent.com/16213433/35808943-974962a8-0a98-11e8-8a63-cd0419e2dea1.png)

**Comment by AMurkin** [comment]
I do. Long enough.

**Comment by BorkBorkGoesTheCode** [comment]
This happened to me when reloading a gun with magazin

**Comment by codemime** [comment]
Here's [the line](https://github.com/CleverRaven/Cataclysm-DDA/pull/22507/files#diff-dc52f162280289dd2d4d97d82658362dR7468) that broke it (no-op, not an assignment). It somehow slipped in unnoticed when I was reviewing that PR.

**Comment by ZhilkinSerg** [comment]
> Here's the line that broke it (no-op, not an assignment). It somehow slipped in unnoticed when I was reviewing that PR.

Thanks!
