### ISSUE TITLE
Dandelions are OP, never spoil

### ISSUE THREAD

**Issue by boydkr** [CleverRaven/Cataclysm-DDA#22890]
Game version: 7105

Operating system: Win10 x64

Tiles or curses: Tiles (both)

Mods active: 

### Expected behavior

"Handful of dandelions" will eventually spoil.  Cooking or preserving should be necessary.

### Actual behavior

I can grow/pick dandelions indefinitely, save the "handfuls" and cook as needed

### Steps to reproduce the behavior

Pick some dandelions

**Comment by Quintovir** [comment]
There's plenty of things that spoil IRL, but don't spoil in-game. My guess behind the unspoilable stuff is to keep spoilage calculations from decimating FPS and to some extent to prevent it being unfun.

Another guess of how unspoilable and spoilable items were determined was to divide them between low water content and high water content respectively.

**Comment by kevingranade** [comment]
Nah, if something spoils irl it should spoil in-game, dandelion permafood is a bug.

**Comment by ZhilkinSerg** [comment]
`spoils_in` node is missing:

https://github.com/CleverRaven/Cataclysm-DDA/blob/2960fe33cffd21601f934e76d24781c5aa40f885/data/json/items/comestibles.json#L2077-L2095

**Comment by BorkBorkGoesTheCode** [comment]
Try 8-hour shelf life for fresh dandelion.
