### ISSUE TITLE
Error with turrets and ammo with Generic Guns mod

### ISSUE THREAD

**Issue by Kelenius** [CleverRaven/Cataclysm-DDA#22903]
Game version: 7112

Operating system: Windows 10

Tiles or curses: Tiles

Mods active:
Dark Days Ahead
More Survival Tools
No Acid Zombies
No Explosive Zombies
No Fungal Monsters
StatsThroughSkills
Vehicle Additions Pack
Tanks and Other Vehicles
Bionics Systems Mod
Boats
Folding Parts pack
Filthy Clothing
Genetic Guns
Makeshift Items Mod
Prevent Zombie Revivification

### Expected behavior
Everything would work.

### Actual behavior
An error appears.

![image](https://user-images.githubusercontent.com/6681708/35972463-00f5178c-0ce3-11e8-90a3-6c2146fa11a9.png)

### Steps to reproduce the behavior
I get this error when wandering around randomly, so I assume it pops up when a car with a turret is spawned.

**Comment by Kodiologist** [comment]
I'm not seeing any error messages now, but `mon_turret_rifle` (M249 autonomous CROWS II) drops no ammo with the Generic Guns mod (its `ammo_type` is `556`, "5.56 NATO M855A1", which is blacklisted), and unloading the turret of an armored car gives me `556` despite the blacklist.

**Comment by Night-Pryanik** [comment]
Can't confirm the bug in the OP and in the comments. Closing until reconfirmed.
