### ISSUE TITLE
Requesting some coding assist

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#22901]
I've made some changes to the code in [my `mapgen-refactor` branch](https://github.com/ZhilkinSerg/Cataclysm-DDA/tree/mapgen-refactor) and started getting following error during compilation in VS:

````
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2036	'item *': unknown size	Cataclysm	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector	1642	
````

As far as I understand I need to move forward declaration with some header include, but I cannot pinpoint where should I do that.

There are few lines with `std::vector<item*>` in changed files, but I didn't touch these in the branch (save for astyling) and the issue appeared before astyling.

Would someone please assist?

P.S.: Sorry for asking here and not on the forums - I suppose more devs are hanging out here.

**Comment by BevapDin** [comment]
If you want qualified help, you should
- post the whole errors message (I don't know VS, but compilers will typically show the files that were included in order to get there, and for template related errors the line that cause the template to be used),
- post the name of the cpp file that you tried to compiled,
- tell which of the several commits of your branch caused the error.

**Comment by ZhilkinSerg** [comment]
> post the whole errors message (I don't know VS, but compilers will typically show the files that were included in order to get there, and for template related errors the line that cause the template to be used),

Unfortunately, that's the whole message. I can click on message error log it points out to some line in `stl_vector.h`. I'm now trying compiling in `Code::Blocks` - hope it will give more meaningful error.

> post the name of the cpp file that you tried to compiled,

VS doesn't show it :(

**Comment by ZhilkinSerg** [comment]
I've found missing header using`Code::Blocks` - adding `item.h` to `monster.h` resolved the issue (though I still don't know why it is required).
