### ISSUE TITLE
StatsThroughSkills still uses calendar::days (game.get_calendar_turn():days())

### ISSUE THREAD

**Issue by dommon** [CleverRaven/Cataclysm-DDA#22914]
Game version: gcf9e053
i reckon any after merge of pr #22818

Operating system:

Tiles or curses:

Mods active: StatsThroughSkills

### Expected behavior
mod working
### Actual behavior
mod failing to do anything other than to display calming 'Calculating..' messages on skillups
### Steps to reproduce the behavior
call calculate_bonuses() from lua console

**Comment by ZhilkinSerg** [comment]
I suggest dropping `handle_previous_version()` or removal of `is_older_than_day` check.
