### ISSUE TITLE
Shotgun trap.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#22925]
Game version:
Tested on build 7090

Operating system:
Windows

Tiles or curses:
Tiles

Mods active:
Fresh install, base mods.

### Expected behavior
Shotgun trap, which is made out of a single barrel shotgun (and not as the description says, a sawed off shotgun), should only fire one round.

### Actual behavior
It activates twice. A shotgun trap that is deconstructed still produces two rounds of shot.

### Steps to reproduce the behavior
Debug a shotgun trap, it says on the description it is made out of a sawn-off shotgun (http://cdda-trunk.chezzo.com/shotgun_trap ) place it, and it will activate twice, for both barrels. But it is made out of only a single shot weapon.

### Suggested fix
Either the trap should be modded to be single shot, or we should change the type of shotgun included in the trap. (Or as a more ambitious project, make a generalized 'weapon trap' that takes a gun with some rounds in it and fires them. (An automatic rifle could be made to simply empty the whole magazine/belt), each second shot should have way less chance to hit of course, due to recoil and simply starting to dodge).

**Comment by LittleBigKid2000** [comment]
Clearly two shells have been put into the one barrel.

**Comment by Night-Pryanik** [comment]
> Clearly two shells have been put into the one barrel, one in front of the other.

No, that's two shells loaded in two barrels.

**Comment by BorkBorkGoesTheCode** [comment]
>Clearly two shells have been put into the one barrel, one in front of the other.

Nope, it's a bug that I didn't know how to fix well.

**Comment by LittleBigKid2000** [comment]
_Just trying to give a humorous explanation_

**Comment by Soyweiser** [comment]
What a silly explanation. Damnit. That simply makes no sense. The additional shot is clearly stored in hammerspace (https://en.wikipedia.org/wiki/Hammerspace).
