### ISSUE TITLE
Installing Travois requires a short rope but doesn't give it back in disassembly

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#22938]
Is this intended? Seems weird that a rope will just disappear. I couldn't find the removal recipe under vehicle_parts.json

**Comment by smolbird** [comment]
Main reason's likely because if you place a frame via construction and dismantle it, you'd generate rope that way.

**Comment by smolbird** [comment]
Er, correction. That's regarding the light frame itself, not the travois. Both require the same part if I recall, and have the same install demands.

**Comment by jeremyshannon** [comment]
Oh hush, stalebot. This bug is still present in current master.

**Comment by anothersimulacrum** [comment]
> Please do not 'bump' or comment on this issue unless you are actively working on it.
It may still be present, but this isn't there for no reason.

**Comment by jeremyshannon** [comment]
Well, okay, "actively" may be a stretch for where I am on this right now. My bad.
