### ISSUE TITLE
Endless bottle of hydrogen peroxide

### ISSUE THREAD

**Issue by sasichkamega** [CleverRaven/Cataclysm-DDA#22943]
Game version: 0.C-26256-g32c7ee3
Operating system: linux mint
Tiles or curses: tiles
Mods active:
[
  "dda",
  "FIC_Weapons",
  "More_Survival_Tools",
  "blazemod",
  "Tanks",
  "Urban_Development",
  "boats",
  "craftgp",
  "brightnights",
  "deoxymod",
  "ew_pack",
  "makeshift",
  "more_buildings",
  "more_locations",
  "realguns",
  "bio_mod",
  "npc_traits"
]

An endless bottle of hydrogen peroxide, when I use it on an NPC, to heal

**Comment by CoroNaut** [comment]
So you are saying that you can tell the NPC to use it and it will never get used? Or are you saying that when you tell the NPC to use it, that it will become infinite for use on yourself as well?

**Comment by MattD94** [comment]
Tried this on  0.C-26193-g452db2d and 0.C-26256-g32c7ee3 can confirm that disinfectant and hydrogen peroxide are not consumed when applying to an NPC via the "use item on" option, regardless of if NPC is following you or has followed you.

**Version:** 0.C-26193-g452db2d and 0.C-26256-g32c7ee3
**OS:** Ubuntu 16.04.3 Via WSL on Windows 10
**Curses/Tiles:** Curses
**Mods:** DDA, Disable NPC Needs, Simplified Nutrition
