### ISSUE TITLE
Flint and Steel cannot be used to Fire Kiln

### ISSUE THREAD

**Issue by helle253** [CleverRaven/Cataclysm-DDA#22944]
Game version: O.C 26144 g4f5a4ba

Operating system: Windows 10

Tiles or curses: Both

Mods active: DDA, Filthy Clothing, Disable NPC Needs, Simplified Nutrition, More Survival Tools, Alternative Map Key, More Buildings, Makeshift Items Mod

### Expected behavior:
Flint and steel should be able to light any object quickly, similar to lighters
### Actual behavior
Having just a flint and steel in my inventory, when attempting to light the charcoal kiln, it acted as if I had no lighting implements in my inventory.
### Steps to reproduce the behavior
Build a charcoal kiln and fill it with wood. With only a flint and steel in inventory, attempt to start the charcoal kiln.

**Comment by Night-Pryanik** [comment]
Will be fixed by #22703.

**Comment by kevingranade** [comment]
Your expected behavior is invalid, flint and steel are neither fast nor reliable.  
It might be reasonable to fire a kiln with one, but it should require kindling to do so, or simply use it to start a small fire first.

**Comment by helle253** [comment]
Should there be some sort of indication for this then?

Currently I know that flint and steel can start a fire, and I know kilns need to be fired. There is no indication as to **why** it cannot occur, which is something the player should receive.
