### ISSUE TITLE
NPCs' martial arts

### ISSUE THREAD

**Issue by SaltGin** [CleverRaven/Cataclysm-DDA#22968]
When I translate the template file, I noticed there are many items that indicates the usage of martial arts by NPCs, but it seems like martial arts part of NPCs is missed in game.
I tried to add new martial arts to NPCs' `ma_styles` list, it actually didn't work even I added `style_selected` item for NPC. (While after martial art added to `ma_styles` , player can learn it from NPC.) 
I was also tracking the update logs of NPCs, but there is nothing about the martial arts part.
Will the NPC martial arts part add in the future?

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
