### ISSUE TITLE
NPC consumes 2 portions of food in once when feed

### ISSUE THREAD

**Issue by xcscsf** [CleverRaven/Cataclysm-DDA#22962]
Game version: cataclysmdda-0.C-7121

Operating system: Windows 10 x64

Tiles or curses: Curses

Mods active:
  "dda",
  "Experimental-Z-Level",
  "More_Survival_Tools",
  "Urban_Development",
  "bio_mod",
  "boats",
  "deoxymod",
  "ew_pack",
  "filthy_morale",
  "makeshift",
  "more_buildings",
  "more_locations",
  "mutant_npcs",
  "national_guard_camp",
  "npc_traits",
  "realguns"

If a NPC was fed by food with container, the NPC will consume 2 portions of food in once.
Although the NPC consumes 2 portions of content in once, only 1 portion of nutrient is added to NPC's need.

**Comment by Night-Pryanik** [comment]
Can't confirm on 7124. Spawned a friendly NPC, debug set his hunger to 1000, fed him with woods soup in a tin can. He consumed 2 portions of the soup and left me with opened tin can of the soup with 2 portions.

**Comment by xcscsf** [comment]
@Night-Pryanik the nutrient of 1 portion of woods soup is 35. So the problem is the NPC consumes 2 portions of food in once, only 1 portion of nutrient gained...
I also tested other food without container, the NPC also consumes 2 portions of food in one time when I feed.
I will change the topic of the issue... Now the issue is that the NPC consumes 2 portions of food in one time and only gains nutrient of 1 portion.
