### ISSUE TITLE
Batch time scaling display for crafting isn't working in the dark

### ISSUE THREAD

**Issue by boydkr** [CleverRaven/Cataclysm-DDA#22984]
Game version: build 7126

Operating system: Win x64

Tiles or curses: both

Mods active:

### Expected behavior

batch recipes shows scaled time with batch size, e.g. clean water, cooked meat, dehydrated vegetables, lye

### Actual behavior

marginal "Time to complete" in crafting menu is static

### Steps to reproduce the behavior

try to craft some clean water in the dark

**Comment by Zireael07** [comment]
Is it only the display which shows wrong, or is the actual time that passes when batch crafting also wrong?

**Comment by boydkr** [comment]
Alright, I think this is a display issue. It definitely happens if it's too dark to craft.

I was crafting at night, and as soon as I light a fire, the time scaling for the recipes shows correctly.

I updated the title/description so as not to be alarmist

**Comment by Night-Pryanik** [comment]
Hmm, can't confirm. 
![default](https://user-images.githubusercontent.com/11132525/36493225-2acd900e-1740-11e8-89b0-4b2709cccb3e.png)

![default](https://user-images.githubusercontent.com/11132525/36493205-1b68ca70-1740-11e8-9fa7-588f870eda8b.png)

**Comment by boydkr** [comment]
That actually confirms the bug.  Here is what the time scaling should be:
![image](https://user-images.githubusercontent.com/5815066/36496200-2d014ade-16fd-11e8-9a2b-3398b8a72f3f.png)

**Comment by Night-Pryanik** [comment]
Okay, I get it. 1 hour and 40 minutes is the time to craft in darkness, because lightning level affects crafting time. `Time to complete` doesn't take possibility to craft into account at all.

**Comment by boydkr** [comment]
Exactly. Are there any cases where the time is different for items that are `dark craftable`?  I guess I just assumed not, but regardless, if an item isn't craftable in the dark, it should show the time to complete as though you could craft it
