### ISSUE TITLE
Weird prozac message.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#22982]
Game version:
Build 7142

Operating system:
Win 7

Tiles or curses:
Tiles

Mods active:
Base install.

### Expected behavior
The game tells you 1 in every 150 times you take prozac: "You suddenly feel hollow inside." Which should have some effect. But apart from the normal prozac effect it does nothing.

### Actual behavior
It is just a random flavor message.

### Steps to reproduce the behavior
Read the code or take a lot of prozac.

Older prozac discussions: #15208 and #11495.

I understand this is a reference to how prozac can make feel people feel empty and blunted. But perhaps it is an idea to add an effect that reduces all positive morale effects by 75% (just as prozac now reduces negative morale by 75%), and to increase the amount of times this effect happens. (As an example of other negative effects caused by meds, thorazine adds 15 fatigue with a 1 in 50 chance)

What do you folks think?

**Comment by AdonaiJr** [comment]
I think it's a good idea. I don't take any drugs myself, but in my wikipedia/foruns excursions I can tell that the effects are just as you said. I think it reflects an actual fact and is an interesting game mechanic.

**Comment by Soyweiser** [comment]
Small note, if you take prozac the bonus you get from the masochist mutation is reduced (see player_morale::update_masochist_bonus() in morale.cpp)
