### ISSUE TITLE
Wood fires should produce wood ash

### ISSUE THREAD

**Issue by boydkr** [CleverRaven/Cataclysm-DDA#22983]
My thought is that either `fire_data` or `mat_burn_data` in 'fire.h' could keep track of the amount of ash to be produced by a given fire when it goes out.

Any thoughts on the mechanics or ideas for implementation?  Does each item material get a json attribute that says how much ash should be produced, or do you calculated based on material and item volume in the code somewhere?

### Expected behavior

Burning a pile of logs and 2x4's produces a pile of wood ash proportional to the amount of wood burned.

### Actual behavior

No ashes

**Comment by kevingranade** [comment]
As long as ash doesn't burn, it's easier to drop it as the items burn, is
there some reason you think it needs to be handled differently?

**Comment by boydkr** [comment]
I was thinking about that, I feel like it might end up with too many items generated of tiny amounts of ash, or way too much ash being generated.

Generating ash after a fire burns out would allow the possibility of only generating an amount of ash past a certain threshold.

I'd be happy to take a stab at either one, but I wasn't able to find where in the code item destruction due to burning occurs.  Could someone point me in the right direction?

**Comment by kevingranade** [comment]
Fire is a field, it's processed in fields.cpp

**Comment by FulcrumA** [comment]
It could be expended (would probably use a separate ticket, but it's conencted to this one): 

In general I was often bothered how a building fire easily burned/crushed all kinds of items, including solid metal ones, into nothing. While high temperature can warp and melt some types of metal, most steel, iron and other relatively-high-melting-point items not in direct contact with fuel for fire or fire itself may get damaged, but not to the point of being unusable - and often, depending on the object, the damage is superficial, none at all or easily repairable.
