### ISSUE TITLE
Smokey Bear miscategorized.

### ISSUE THREAD

**Issue by Chase-san** [CleverRaven/Cataclysm-DDA#22986]
Game version: Build 7126
Operating system: Windows 10 Pro 64 bit
Tiles or curses: Tiles
Mods active: N/A

### Expected
The "mon_bear_smoky" should not be categorized as WILDLIFE.

### Actual
The monster "mon_bear_smoky" is categorized as WILDLIFE.

**Comment by codemime** [comment]
Maybe WILDFIRE instead?

**Comment by ZhilkinSerg** [comment]
Hey, hey, hey, hey
Smokey Bear everyday
