### ISSUE TITLE
Sawdust Generation during Woodworking/Furniture Construction

### ISSUE THREAD

**Issue by helle253** [CleverRaven/Cataclysm-DDA#22993]
Related to #22703 and #22944.

If/when firestarting receives an increase in complexity, and different firestarters require different types of tinder/easily burnable materials, providing source of tinder like this should be considered. There are plenty of existing sources of sawdust during normal play.

**Comment by Soyweiser** [comment]
Sawdust fields? That create piles of sawdust when they dissipate and cause smoke like inhalation when you don't have enough mouth protection?

**Comment by Night-Pryanik** [comment]
Closing for lack of discussion.
