### ISSUE TITLE
CBM installation failure can remove irremovable CBMs

### ISSUE THREAD

**Issue by niglow** [CleverRaven/Cataclysm-DDA#23007]
Game version:  7124

Operating system: MS Windows

Tiles or curses: Tiles

Mods active: none

### Expected behavior
When you fail to install a CBM and lose some already installed CBMs because of that, you shouldn't lose CBMs that leave you crippled like Fusion Arm or Telescopic Eyes.

### Actual behavior
You're able to lose any CBMs, even those that you can't naturally remove.

### Steps to reproduce the behavior
Have some irremovable CBMs installed, try to install a new one, fail, roll "lose CBMs" effect, lose these CBMs.

**Comment by ZhilkinSerg** [comment]
Obsolete after https://github.com/CleverRaven/Cataclysm-DDA/pull/24663.
