### ISSUE TITLE
Linux Build Failure

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#23013]
Game version:
Current Git pull commit: 825d0fed331d6e8e0d1e0ac18a022433342b5cbe
Operating system: Linux, Jenkins reports only windows builds are succeeding.

Tiles or curses:
Both 

Build log from Jenkins. 

10:07:33 src/overmap.cpp: In member function ‘bool overmap::generate_sub(int)’:
10:07:33 src/overmap.cpp:1869:5: error: no return statement in function returning non-void [-Werror=return-type]
10:07:33      }
10:07:33      ^
10:07:33 src/overmap.cpp: At global scope:
10:07:33 src/overmap.cpp:1870:5: error: expected unqualified-id before ‘for’
10:07:33      for (auto &i : ant_points) {
10:07:33      ^
10:07:33 src/overmap.cpp:1874:5: error: expected unqualified-id before ‘for’
10:07:33      for (auto &i : cities) {
10:07:33      ^
10:07:33 cc1plus: all warnings being treated as errors
10:07:33 Makefile:732: recipe for target 'obj/overmap.o' failed
10:07:33 make: *** [obj/overmap.o] Error 1
10:07:33 make: *** Waiting for unfinished jobs....
10:07:40 Build step 'Conditional step (single)' marked build as failure
10:07:40 SSH: Current build result is [FAILURE], not going to run.
10:07:40 Recording fingerprints
10:07:40 IRC notifier plugin: Sending notification to: #CDDA-dev
10:07:40 Finished: FAILURE

**Comment by Treah** [comment]
Reverting to commit 901c5dd5725b6c426f0a985c4882dc8e9dd004fd fixes the compile issue. There was quite a few commits after this in regard to overmap code changes so I suspect the problem is in there.

**Comment by Leland** [comment]
Those overmap changes would be #22864. @kevingranade is doing some refactoring of it in #23012, try checking out f6c39ec and see if it builds

**Comment by Treah** [comment]
@Leland Ahh ok i was a bit confused by your link to a commit there since its not merged with master so Ill just wait and see when it is if it resolved the compile problem.

**Comment by boydkr** [comment]
Should be fixed by #23015

**Comment by kevingranade** [comment]
just waiting for auto-builds to complete.
