### ISSUE TITLE
Balancing alcohol comestibles

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#23011]
I've checked data after seeing https://www.reddit.com/r/cataclysmdda/comments/7zdlk6/why_does_strawberry_surprise_is_a_healthy_3_food/ and there are some comestibles with `alcohol` in `materials` node with zero or positive values of `healthy` node.

There are no health benefits in alcohol consumption, so we should probably make all values negative or remove `alcohol` from `materials` for those comestibles with trace amounts of alcohol.

Also `honey_gold` does not have `alcohol` `addiction_type` attached to it.

There are also possibly inconsistencies in `addiction_potential`.

# Current values:

"id" | "weight" | "volume" | "quench" | "healthy" | "stim" | "addiction_potential" | "nutrition" | "fun" | "use_action" | "container" | "charges" | "stack_size"
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
brandy | 46 | 1 | -5 | -2 | -12 | 5 | 2 | 12 | ALCOHOL | bottle_glass | 7 |  
drink_boozeberry | 36 | 1 | 15 | 1 | -14 | 18 | 30 | -12 | ALCOHOL | bottle_glass | 6 |  
drink_hobo | 249 | 2 | 25 | -2 | -15 | 5 | 6 | 20 | ALCOHOL | bottle_glass |   |  
drink_kalimotxo | 250 | 2 | 25 | -1 | -9 | 5 | 4 | 20 | ALCOHOL | bottle_glass | 2 |  
drink_rumcola | 250 | 1 | 25 | -2 | -4 | 4 | 5 | 20 | ALCOHOL | bottle_glass |   |  
drink_screwdriver | 250 | 1 | 25 | 1 | -12 | 4 | 6 | 20 | ALCOHOL | bottle_glass |   |  
drink_strawberry_surprise | 36 | 1 | 15 | 3 | -14 | 6 | 8 | 8 | ALCOHOL | bottle_glass | 6 |  
drink_wild_apple | 248 | 1 | 25 | 1 | -12 | 4 | 6 | 20 | ALCOHOL | bottle_glass |   |  
drink_wsour | 249 | 2 | 25 | -1 | -12 | 4 | 6 | 20 | ALCOHOL | bottle_glass |   |  
eggnog_spiked | 258 | 1 | 25 | -1 | -10 | 5 | 45 | 20 | ALCOHOL | bottle_glass | 2 |  
gin | 33 | 1 | -10 | -2 | -12 | 5 | 2 | 15 | ALCOHOL | bottle_glass | 7 |  
imperial_stout | 249 | 1 | 8 | -1 | -8 | 4 | 6 | 18 | ALCOHOL | bottle_glass |   |  
irish_coffee | 231 | 1 | 20 | -2 | 12 | 5 | 15 | 20 | ALCOHOL | bottle_glass |   |  
long_island | 42 | 1 | -10 | -2 | -10 | 5 | 2 | 20 | ALCOHOL | bottle_glass |   |  
mead | 46 | 1 | 14 |   | -4 | 2 | 4 | 14 | ALCOHOL | bottle_glass | 7 |  
mixed_alcohol_strong | 46 | 1 | -12 | -4 | -15 | 7 | 2 | 5 | ALCOHOL | jug_plastic |   | 7
pine_wine | 49 | 1 | 2 | 1 | -2 | 1 | 2 | 12 | ALCOHOL | bottle_glass | 7 |  
rum | 33 | 1 | -12 | -2 | -10 | 5 | 2 | 15 | ALCOHOL | bottle_glass | 7 |  
single_malt_whiskey | 33 | 1 | -12 | -2 | -12 | 5 | 4 | 17 | ALCOHOL | wooden_barrel | 7 |  
tequila | 38 | 1 | -12 | -2 | -12 | 6 | 2 | 18 | ALCOHOL | bottle_glass | 7 |  
triple_sec | 33 | 1 | -8 | -2 | -10 | 4 | 2 | 10 | ALCOHOL | bottle_glass | 7 |  
vodka | 33 | 1 | -10 | -2 | -12 | 5 | 2 | 15 | ALCOHOL | bottle_glass | 7 |  
whiskey | 33 | 1 | -12 | -2 | -12 | 5 | 4 | 15 | ALCOHOL | bottle_glass | 7 |  
wine_cabernet | 50 | 1 | 4 |   | -12 | 5 | 4 | 15 | ALCOHOL | bottle_glass | 5 |  
wine_chardonnay | 50 | 1 | 4 |   | -12 | 5 | 4 | 15 | ALCOHOL | bottle_glass | 5 |  
wine_noir | 50 | 1 | 4 |   | -12 | 5 | 4 | 16 | ALCOHOL | bottle_glass | 5 |  
wine_riesling | 50 | 1 | 4 |   | -12 | 5 | 4 | 15 | ALCOHOL | bottle_glass | 5 |  
moonshine | 35 | 1 | -16 | -6 | -18 | 7 | 2 | 12 | ALCOHOL_STRONG | jug_plastic | 7 |  
beer | 249 | 1 | 18 |   | -4 | 2 | 4 | 10 | ALCOHOL_WEAK | can_drink |   |  
belgian_ale | 249 | 1 | 16 | -1 | -4 | 2 | 8 | 14 | ALCOHOL_WEAK | bottle_glass |   |  
bum_wine | 46 | 1 | 6 | -4 | -2 | 7 | 2 | 10 | ALCOHOL_WEAK | jug_plastic | 7 |  
dandelion_wine | 46 | 1 | 10 |   | -2 | 1 | 2 | 16 | ALCOHOL_WEAK | bottle_glass | 7 |  
drink_beeknees | 248 | 2 | 25 |   | -11 | 4 | 7 | 20 | ALCOHOL_WEAK | bottle_glass |   |  
european_pilsner | 249 | 1 | 18 | -1 | -4 | 2 | 4 | 10 | ALCOHOL_WEAK | can_drink |   |  
fruit_wine | 46 | 1 | 10 | -2 | -4 | 3 | 2 | 2 | ALCOHOL_WEAK | bottle_glass | 7 |  
hb_beer | 249 | 1 | 18 |   | -4 | 2 | 4 | 8 | ALCOHOL_WEAK | jug_plastic |   |  
honey_gold | 259 | 2 | 20 | 2 | 1 |   | 40 | 10 | ALCOHOL_WEAK | jug_plastic | 2 |  
india_pale_ale | 249 | 1 | 18 | -1 | -4 | 2 | 4 | 14 | ALCOHOL_WEAK | can_drink |   |  
mixed_alcohol_weak | 249 | 1 | 16 | -2 | -4 | 4 | 4 | 4 | ALCOHOL_WEAK | jug_plastic |   |  
pale_ale | 249 | 1 | 18 | -1 | -4 | 2 | 4 | 14 | ALCOHOL_WEAK | can_drink |   |  
stout | 249 | 1 | 18 | -1 | -4 | 2 | 4 | 14 | ALCOHOL_WEAK | bottle_glass |   |  
drink_sewerbrew | 250 | 2 | 25 | -10 | -20 | 5 | 3 | -15 | MUTAGEN | bottle_glass | 2 |  
taint_tornado | 100 | 1 | -20 | -10 | -60 | 5 | 10 | -40 | MUTAGEN | bottle_glass | 2 |

**Comment by ZhilkinSerg** [comment]
There are multiple sources in the Internet about alcohol nutrition.

# Unit and calorie calculator

https://www.drinkaware.co.uk/understand-your-drinking/unit-calculator

# Alcohol nutrition values

https://www.nhs.uk/Livewell/alcohol/Pages/calories-in-alcohol.aspx

Drink | Calories (kcal) | Food equivalent
-- | -- | --
A standard glass (175ml) of 12% wine | 126kcal | 1 Cadbury Chocolate Mini Roll
A pint of 5% strength beer | 215kcal | 1 packet of McCoy's salted crisps
A glass (50ml) of (17%) cream liqueur | 118kcal | 1 Milky Way bar
A standard bottle (330ml) of 5% alcopop | 237kcal | 3 Lees teacakes
A double measure (50ml) of 17.5% fortified wine | 65kcal | 1 Asda bourbon biscuit

https://www.medicinenet.com/alcohol_and_nutrition/article.htm

Alcoholic drink | Calories
-- | --
Beer, lite, 12 oz. | 100
Beer, regular, 12 oz. | 150
Frozen daiquiri, 4 oz. | 216
Gin, 1.5 oz. | 110
Mai tai, 4 oz. | 310
Margarita, 4 oz. | 270
Rum, 1.5 oz. | 96
Vodka, 1.5 oz. | 96
Whiskey, 1.5 oz. | 105
Wine spritzer, 4 oz. | 49
Wine, dessert, sweet, 4 oz. | 180

**Comment by ZhilkinSerg** [comment]
Btw, why do we use `nutrition`, instead of `calories` in the json?

**Comment by kevingranade** [comment]
Because it was originally an arbitrary unit of nutrition instead of being
linked to a real unit.
It's fine to change it to calories, because that's what it means now, but
that's a lot of changes for not much value.

**Comment by ZhilkinSerg** [comment]
So, `nutrition` is basically multiple of `calorie`?

**Comment by Soyweiser** [comment]
kcal_per_nutr = 2500.0 / ( 12 * 24 ) from itype.h
Each day you need 288 points of nutrition which equals 2500 kcal. So each point of nutrition is 8.7kcal.

**Comment by ZhilkinSerg** [comment]
Calories were already addressed for all foods.
