### ISSUE TITLE
Some items doesn't show on "Use Item" and "Execute which action" GUI's

### ISSUE THREAD

**Issue by AdonaiJr** [CleverRaven/Cataclysm-DDA#23014]
Game version: 0.C-7138
Operating system: Windows
Tiles or curses: Tiles
Mods active: Default

### Expected behavior
As I remember, you could usually have a "bottle of disinfectant" in your inventory, on the ground or generally nearby, them press "a" and have it show up on the "Use Item" GUI, that shows various default options for different tools, foods, etc.

### Actual behavior
As you press "a" and look for the bottle of disinfectant, it isn't there.

You need to open the inventory, choose the bottle and them "apply" for it to work.

### Steps to reproduce the behavior
As described above.

Possibly related to #22943 ?

**Comment by AMurkin** [comment]
And it shows at the eat menu.

**Comment by AdonaiJr** [comment]
Also there are other strange things in the Eat Menu, like "pack with cigarette". IIRC it used to show up on "apply" menu.

Bottle of disinfectant doesn't show up on "% - Execute which action" but,
Pack of cigarette shows properly associated to "Smoke" action.

**Comment by Ramza13** [comment]
Just tested and this appears to work now.  Spawned first aid kit, used it and then opened use item menu. small plastic bottle of antiseptic was present as an option

**Comment by Night-Pryanik** [comment]
Ok, closing until reconfirmed.
