### ISSUE TITLE
Power Armor MK2 Interface CBM nonfunctional

### ISSUE THREAD

**Issue by Curt5** [CleverRaven/Cataclysm-DDA#23047]
Game version: 7153 Experimental

Operating system: Windows

Tiles or curses: Tiles

Mods active: https://puu.sh/zqFWv/e7737e4c4c.png, https://puu.sh/zqFXl/a3a864221d.png, https://puu.sh/zqFXV/c5a1413c28.png

### Expected behavior
When activated, the MK2 Power Armor Interface bionic will reduce the encumbrance of and power MK2 Power Armor, while draining bionic power.

### Actual behavior
The interface neither powers Power Armor nor drains bionic power.
### Steps to reproduce the behavior
Intall MK2 Power Armor Interface CBM. Wear MK2 Light Power Armor. Activate. Watch energy not drain and the armor not work.

**Comment by Night-Pryanik** [comment]
You need to activate your Mk-II Power Armor Interface CBM first, and then activate your Light Power Armor second. Tested right now - all is working as it should.
