### ISSUE TITLE
Placed turrets starting as hostile.

### ISSUE THREAD

**Issue by l-Ashery-l** [CleverRaven/Cataclysm-DDA#23064]
Game version: 
7157

Operating system: 
Win 7, 64bit

Tiles or curses:
Tiles

Mods active: 
Filthy Clothing
Disable NPC needs
No survivor armor
Simplified nutrition

### Expected behavior
Placed turrets always being friendly.

### Actual behavior
Placed turrets have a chance of starting as hostile.

### Steps to reproduce the behavior
Create a new character, wish yourself a turret, and place/pick up until it comes out hostile. It shouldn't take more than a few attempts.

---

Alright, so it appears that this behavior isn't an outright *bug* as per a comment I managed to dig up from '16:

>Was it friendly when you first placed it? IIRC(On the IOS version at least), Turrets have a chance of not recognizing you as friendly when you first place them, which usually results them turning you into a thin red paste soon after.

My issue here is that there is *no* feedback given to the player that indicates there's a chance of the turret coming out as hostile when placed. In many situations, placing a hostile turret would lead to the inevitable death for the player character.

So, my suggestion is to simply increase transparency. At the very least, modify the descriptions of all placed turrets so that they indicate there is a chance that they will not recognize the player as friendly. As it stands, the description for the basic turret indicates the exact opposite, ie that it will always recognize the player as friendly.

My other suggestion was to tie the chance of successfully reprogramming the IFF to various character skills, but it looks like something like that is already in place. After raising all skills to 10, there wasn't a single failure over a couple dozen attempts. I can definitely see the argument for keeping some of the mechanics hidden from view, but there should be some subtle indication that certain skills help when placing turrets. It could be something as simple as adding "Using the item involves reprogramming the IFF,..." to the description of the various turrets.

**Comment by Soyweiser** [comment]
http://cdda-trunk.chezzo.com/bot_turret
"This is an inactive turret. Using this item involves loading the unit with the factory-loaded 9mm rounds in your inventory (if you wish to divide your ammunition, set aside whatever 9mm you do NOT want to give the turret) turning it on, and placing it on the ground, where it will attach itself. **The turret will then identify you as a friendly**, and attack all enemies with a built-in SMG."

This behaviour contradicts the description of the item, and well, imho that is pretty bad.

**Comment by kevingranade** [comment]
Agreed, definitely change the wording to indicate there's a chance of
failure programming the turret.
