### ISSUE TITLE
Fix superglue and replace with other glues.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#23067]
An anonymous source pointed out that superglue is a very specific compound [Cyanoacrylate](https://en.wikipedia.org/wiki/Cyanoacrylate). Also see http://www.compoundchem.com/2015/10/15/superglue/

Proposal:
Remove the superglue recipe until it has a more reasonable definiton.  There's a description of the process [here](http://www.chm.bris.ac.uk/motm/superglue/superglueh.htm), but I'm not knowledgeable enough about organic chemistry to turn that into a recipe.
Make Superglue spoil after a year (365-ish days, not a in-game year) as it's quite volatile.
Add some other glues that are similarly useful, i.e. some of [these](https://snappyliving.com/11-recipes-to-make-your-own-glue/).
Adjust other recipes to use these new glues.
Consider adding superglue as a wound binder.

**Comment by smolbird** [comment]
Is this really needed, especially spoilage? I'm finding it hard to see the gameplay benefits of basically everything except the medical suggestion.

**Comment by kevingranade** [comment]
The current lack of spoilage and ease of crafting (of this as well as many other items) trivializes the availability of many items and recipes, leading to the flat end-game difficulty that is chronic throughout the game.

Ideally, life is very easy immediately after the cataclysm since such a tiny fraction of the population has access to the massive surplus of materials that remain, but life steadily becomes more difficult as time passes and survivors are forced to transition to greater self-sufficiency.

**Comment by smolbird** [comment]
And this would be pointless because a faster-than-real-life spoilage rate would undermine the point (realism for the hell of it), while a realistic rate would make superglue outlast most characters.

**Comment by Rivet-the-Zombie** [comment]
What if we renamed it to 'glue'? It's vague enough that nobody can call it out as a specific compound, yet still gets the point across.

**Comment by Soyweiser** [comment]
"An anonymous source" lol.

Not sure if adding more different glues or glue spoilage rates adds much to the game apart from frustration. We should probably at least increase the difficulty of crafting it. As the low cooking levels are supposed to be for less chemical and more cooking related recipes.

Also, there is this: http://cdda-trunk.chezzo.com/bone_glue/craft

**Comment by John-Candlebury** [comment]
I think we can just rename superglue to generic glue and get away with it. 

The real advantage superglue has over other adhesives is that it dries very fast, we dont strictly need it for any recipe we have in the game. 

---

Superglue around here is sold in sealed plastic ampules. I imagine that if they are kept in the dark and the ampoule is well made the glue inside would never evaporate.

**Comment by smolbird** [comment]
I'm in favor of just renaming superglue to generic glue. It already requires more effort than bone glue to make.

**Comment by boydkr** [comment]
just call it "heavy duty glue" or something like that.  There are tons of recipes for different glues, mostly  using gelatin or some sort of starch.  Enumerating every single one of them for realism would be more like extreme tedium, I think.

You could even leave a `super glue` recipe using blob globs for fun.

**Comment by kevingranade** [comment]
The main issue as far as I can tell is fletchings, none of the other glues
are going to be sufficient by themselves.

Given that, I'd be fine to change it to "heavy glue" and remove it from the
fetching recipes, but I'd rather leave superglue as scavenge only, add the
current recipe as heavy glue, and add heavy glue where applicable.

**Comment by smolbird** [comment]
> The main issue as far as I can tell is fletchings, none of the other glues are going to be sufficient by themselves. Given that, I'd be fine to change it to "heavy glue" and remove it from the fetching recipes, but I'd rather leave superglue as scavenge only, add the current recipe as heavy glue, and add heavy glue where applicable.

Will bone glue still be usable?

**Comment by John-Candlebury** [comment]
>The main issue as far as I can tell is fletchings, none of the other glues
are going to be sufficient by themselves.

I dont see why not.  We didnt had superglue before the 1900s and certainly had high quality arrows and bows. Most likely we used tree resin (pines are great for this) or animal glue (and tried our best to keep arrows dry).

Heres a document detailing medieval glues:
http://www.rocks4brains.com/glue.pdf

Here's a website claiming that early fetching was kept in place with string and tree resin
http://www.fletchers.org.uk/historyofarrowmaking.html

If you search forums for archery you can find people claiming that they used animal glue  too.

So  we can still use bone glue for them, and only a fletcher/ weapon historian would know wheter thas ok or not. Or change the glue to be Rosin, derived from pine resin. 

No superglue would only affect us when i comes to making carbon and metal shafted arrows.  Its alright if we cant make carbon arrows and the metal arrows are so weight/damage inefficient that I dont think anyone will miss them.

---

With all the more exiting things waiting to be coded, why bother with things so specific as properly simulated mechanically different glues?

**Comment by Soyweiser** [comment]
My suggestion just make superglue lootable only, remove bone glue, add craftable glue (make the recipe show up in several books, but not automatically gained).

Combine the old boneglue things into superglue items on a case by case basis.

Add a few more locations where you can find glue/superglue (and prob duct tape), to make up for the fact that making it is harder.

**Comment by smolbird** [comment]
```
My suggestion just make superglue lootable only, remove bone glue, add craftable glue (make the recipe show up in several books, but not automatically gained).

Combine the old boneglue things into superglue items on a case by case basis.
```

That seems like a terrible idea, at least without ensuring SOME form of wilderness-survival glue still exists. If you want a good example, about a couple days ago I found another mod by @chaosvolt that allows the use of pine/birch pitch as an adhesive: https://github.com/chaosvolt/MST_Extra_Mod

**Comment by Soyweiser** [comment]
Why? If we move the bone glue to the survivaltools mod, why do we need wilderness-survival glue?

**Comment by smolbird** [comment]
Is breaking an aspect of vanilla gameplay really a good idea? Doubly so when it's both bad for gameplay AND less realistic? I mean I legit do not see what you seem to believe we're gaining by doing that.

**Comment by Soyweiser** [comment]
How does this break gameplay? In my suggestion you can still make glue.
Bone and superglue appear almost at the same time (both need skill levels of 2) and use similar amounts of ingredients.

See: http://cdda-trunk.chezzo.com/superglue/craft and http://cdda-trunk.chezzo.com/bone_glue/craft what does being able to make bone glue add to the game?

**Comment by smolbird** [comment]
Hmm. That is weird, yes. The only relevant difference is narrower materials list and different requirements. However, the latter does change the implications a fair bit: bone glue can be make with stone pots, makeshift pots, etc. Superglue requires a pot, copper pot, clay pot etc.

I'd recommend making a generic glue recipe that allows the broader range of materials, retains the use of stone pot-level qualities, but has bone glue's current usage range. Then add a more complex glue item that requires either chem one or maybe even two, at a higher level, and have that item fill the roles that superglue is supposed to fill.

This achieves the general desired idea without any disruption to the way crafting advances in a wilderness setting. Because that does not seem to be the focus of the issue, it's the balance of more advanced glues (which logically should affect urban gameplay primarily) that're the likely priority target.

Related, see pull request: https://github.com/CleverRaven/Cataclysm-DDA/pull/22972

**Comment by kevingranade** [comment]
The fletchings change wouldn't be large, it would be adhesive AND filament instead of the current adhesive OR filament.
