### ISSUE TITLE
Wander spawn monsters don't follow evolution rules

### ISSUE THREAD

**Issue by chaoticidealism** [CleverRaven/Cataclysm-DDA#23063]
Game version:0.C-26482-g5d60a3e

Operating system:Windows 7

Tiles or curses:curses

Mods active:Filthy clothing, disable NPC needs, simplified nutrition, generic guns, more survival tools, makeshift items, mining, cataclysm++, stats through skills IV, extra professions, classes and scenarios

### Expected behavior
Wander spawns follow evolution rules so that overpowering monsters don't appear until your evolution rate factor says so

### Actual behavior
Special zombies, especially the bionic zombie supersoldiers, start spawning right away--even when the evolution rate is set slower than normal.

### Steps to reproduce the behavior
Start a game, wander around, wait to be ganked by a Zombie Super BAMRU.

**Comment by Zireael07** [comment]
Wander spawns not following evolution rules is a suuuper old bug in vanilla, just btw.

**Comment by Leland** [comment]
Former issue #13803, now closed. Bizarrely, the PR that fixed it has been deleted? #22969.

Woah. Actually, looks like @Coolthulu is no longer. Wonder what happened.

**Comment by codemime** [comment]
I'm staring at the blank page in disbelief, hoping it's just a temporary github issue.

**Comment by chaoticidealism** [comment]
I hope so; this is a pretty critical bug.

**Comment by Theundyingcode** [comment]
I ran into shocker hulks during day 1 on default settings + horde last week...

**Comment by BorkBorkGoesTheCode** [comment]
Were there any masters nearby?

**Comment by Theundyingcode** [comment]
Idk, I ran right away and then avoided hordes and died before getting a chance to find out.  I have only gotten to like 3 games in the last 6 months...  I know masters, technicians, necromancers and, all other kinds of nope used to spawn day 1 with hordes but, idk if that was after #22969.  (Strangely I don't remember any hulks...)

**Comment by Toybasher** [comment]
Day 1 I have encountered shocker zombies and shady zombies at night, including a necromancer as soon as I stepped out of the shelter. No idea if it's intended. 

I have also encountered smoker zombies and acid zombies day 1. Again no idea if they're "Supposed" to be there with hordes on by design or if the bug hasn't been fixed yet.

**Comment by Toybasher** [comment]
One theory for why this might be happening (No idea exactly how the system works, just something I read somewhere) is that each zombie type has a cap basically, and the default amount of zombies with hordes on is too high, so once it populates the horde with normal zombies, it can't "spend" zombie-points on any more normal zombies, so it spends them on tougher ones until it runs out of points.

**Comment by BevapDin** [comment]
> Day 1 I have encountered shocker zombies and shady zombies at night, including a necromancer as soon as I stepped out of the shelter. No idea if it's intended.

Horde monsters (aka wandering zombies) are spawned via the monster group "GROUP_ZOMBIE", which contains shocker, brute, master, hulk etc. (see "data/json/monstergroups.json").

And the monsters are upgraded normally when spawned.

Maybe the monster group should be changed to not contain advanced monsters? Upgrading the monsters upon spawning them is done for probably all spawning monsters, so changing that would have a larger effect.

**Comment by Firestorm01X2** [comment]
This issue stoll labeled as: "Need confirmation"

Probalby is conrirmation:
https://www.reddit.com/r/cataclysmdda/comments/aefhos/did_the_city_layout_rework_change_the_spawn_or/
