### ISSUE TITLE
Please investigate mapgen issues

### ISSUE THREAD

**Issue by giltheb** [CleverRaven/Cataclysm-DDA#23072]
Game version: 0.C 26212-gfbae814 (7119 ) (recent, the post mi-go apocalypse one)

Operating system: Win7 64bit

Tiles or curses: cataclysm-tiles.exe

Mods active: DDA, Filthy Clothing, Simplified Nutrition, Makeshift Items Mod, More survival Tools, No Fungal Monters, StatsThoughSkills IV

### Expected behavior
I have no clue if it is expected or not.

### Actual behavior
There is 0 to 2 Labs per overmap chunk, which seem a little too few. (you need both a lot of luck and a lot of exploring to find just one lab).

No house basements ... at all.
Other basements are fine (subway, prison, lab, vault, mansions, temple ...)

Way too much crash sites and ambush remains ( I made a new character and scout around a bit, just the first day I found a railgun, 5 plutonium cells, a miltary roadmap, 2 CBM)

### Steps to reproduce the behavior
Create a new world on a recent build  with the default settings (city size:4 city spacing:4,  zlevel:false)

NOTE: it is my first time opening an issue, please tell me if something is wrong (and I dont know how to add a Label)

**Comment by ZhilkinSerg** [comment]
Labels are added by organization members.

**Comment by ZhilkinSerg** [comment]
There was issue with missing basements recently, but it should've been fixed already.

**Comment by giltheb** [comment]
I just update my game, 0.C-26487-gfca10df(tiles) 7159.

It seems the house basements are not back, it is nice it is a known issue.

**Comment by The-Host** [comment]
Although I agree that the ambushes are way too common(Found about 9 or 10 just traveling the roads close by), basements do exist. Found two in a small city right next to each other.

They seem pretty rare though. I've checked somewhere between 40-60 houses on this version of mine(7120) and have only found those two. Not sure if that's the desired result.

**Comment by ZenZen2** [comment]
looking into overmap_specials file i see a problem with Labs. A map with city size 1 will never see a Lab or Ice Lab.
```
"city_sizes" : [4, 12],
```
Older Files used to have mandatory Labs. But i dont think thats a solution.
A solution would be decreasing minimun city size to 0 and decrease the max occurrences from 30 to somthing like 4. That would also fix one of the issues here.

**Comment by ZhilkinSerg** [comment]
Old issue #22921 and fix #22932.

**Comment by ZhilkinSerg** [comment]
> Game version: 0.C 26212-gfbae814 (7119 ) (recent, the post mi-go apocalypse one)

> I just update my game, 0.C-26487-gfca10df - (tiles) - 7159.
>
> It seems the house basements are not back, it is nice it is a known issue.

Basements were missing in build 7119, this was only fixed in build 7121 (http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/7121/changes).

Basements should be generated in normal fashion in build 7159, but if you load existing world from 7119 to 7159 basements won't appear in existing overmaps.

Try new game.

**Comment by giltheb** [comment]
They are indeed some basements in the build 7159, I don't know how I did miss them, and the overmap I just reveal has 4 labs in it so maybe it is not so bad.

**Comment by Soyweiser** [comment]
Here is the reddit thread where OP first talked about this: https://www.reddit.com/r/cataclysmdda/comments/8044ez/weekly_questions_thread_february_25_2018/duu99vg/

And interestingly a differen't thread where somebody is complaining about the labs problem, but he/she has too many of them. https://discourse.cataclysmdda.org/t/bug-with-elated-bonus-and-some-other-feedback/15041/5

**Comment by ZenZen2** [comment]
@giltheb city size 3 in the world options mean you can get citys up to size of 6, check this for more information: https://github.com/CleverRaven/Cataclysm-DDA/pull/14362

@Soyweiser ice lab and normal labs have both:
``` "occurrences" : [0, 30] ```
if you chose a city size of 2 you can get an overmap with all citys of size 4 and the overmap can have up to 60 labs. Very unlickly but possible. While the next overmap can have all Citys with size of 1/2/3 and result in 0 labs.
I dont see any bug in this. This is how it works.
Correct me if im wrong.

**Comment by ZenZen2** [comment]
@giltheb for the future: for each problem please open a new issue, this way its easier to manage and to close when one problem is solved.

**Comment by illi-kun** [comment]
Please modify the name of the issue to make it clear and understandable without reading the description.

**Comment by Zireael07** [comment]
I can edit the issue title. I believe the basements thing was fixed, so: "Too few labs and too many ambushes"?

**Comment by kevingranade** [comment]
Issue is unclear and seems to be out of date.
