### ISSUE TITLE
Crash/Seg Fault using retrodays tilesets on linux 64bit

### ISSUE THREAD

**Issue by matdombrock** [CleverRaven/Cataclysm-DDA#23075]
Game version:
0.C-26487-gfca10df

Operating system:
Linux 64bit - Ubuntu Mate 
4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Tiles or curses:
Tiles

Mods active:
Default Set

### Expected behavior
Play the game with "retrodays10" tileset or "retrodays20" tileset

### Actual behavior
Game crashes to desktop.
Console Output:
Segmentation Fault (Core Dumped)

### Steps to reproduce the behavior
-Start game in tiles mode with default/stock config (I used a fresh install right from the site)
-Select "retrodays10" tileset or "retrodays20" tileset
-Enjoy game

### Other Information
I have fixed this issue by installing an older version of the tilesets
This issue has been happening for me since at least 0.C-7151

**Comment by ZhilkinSerg** [comment]
Have you tried updated version of tileset from here - https://discourse.cataclysmdda.org/t/retrodays-tileset-update-2018/14791?

**Comment by matdombrock** [comment]
The latest version of the tileset is working for. Not seeing any issues with this one. Thank you. 

Is there a reason this isn't included with the builds?

**Comment by illi-kun** [comment]
@night-pryanik
Why closing this? I didn't test it yet but I guess we need to update tileset in the repo for doing that.

**Comment by ZhilkinSerg** [comment]
> Is there a reason this isn't included with the builds?

No one submitted PR yet.

**Comment by matdombrock** [comment]
If it's as simple as forking, adding the tileset then PR, I could do that this evening no problem.

**Comment by matdombrock** [comment]
I've submitted a [PR](https://github.com/CleverRaven/Cataclysm-DDA/pull/23091) to add the new retrodaysJar tileset. 

Just to be clear, this DOES NOT fix the original issue. This has only added a newer and more stable version of the tileset without changing or replacing the old broken ones. 

This issue is still present on the latest update when using the retrodays 10 & 20 tilesets.
