### ISSUE TITLE
Wash clothes by volume

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#23088]
I made a suggestion in #22776 and then thought I'd make it on its own.

I washed clothes by hand for a year and I followed this basic principle.
1.) Add water and soap to a basin
2.) Scrub your whites in soap basin, rinse in clean water, and wring them out.
3.) Scrub your darks in soap basin, rinse in clean water, and wring them out.
4.) hang out to dry

My idea is/was this.

- Create a wash basin/tub that can be placed (like a brazier) that has a limited volume (say 20-40 liters).
- Place near your rain barrel / large body of water.
- Stuff full of filthy laundry.
- "[a]pply" soap or detergent to use. (Alternatively maybe a fire nearby as an alternative sterilizing agent to soap?)
- All items in the basin would be washed over an extended period of time and use a set amount of water and soap (say 15 - 30 units of water and 1 thing of soap).
- The PC would complain about having raisin fingers.

This would resolve any issues with having a stack of filthy rags that will never ever be washed, and give desires to cutting zombie clothes into scrap materials again.

*Edit* This would make way for vehicle/powered washing machines as well as they would work along the same principle.

**Comment by Beetlecat** [comment]
> The PC would complain about having raisin fingers.

Not with rubber gloves, they wouldn't! ;)

I *really* like this idea. A much less ludicrous system than washing a single leather patch at a time with multiple keypresses.

**Comment by RogueYun** [comment]
> I seem to recall seeing exactly this recently -- or was it a placeholder idea?
Just a placeholder as I realized afterwards that the same principle would seem to apply.

**Comment by jarmush** [comment]
OMG yes! The same mechanics as with transport washing machines!
really want it ingame!

**Comment by Beetlecat** [comment]
The vehicle part is sitting in the code, waiting... ;)

`    {
        "type": "GENERIC",
        "id": "washing_machine",
        "name": "washing machine",
        "description": "A very small washing machine designed for use in vehicles.",
        "weight": 31752,
        "to_hit": -8,
        "color": "light_blue",
        "symbol": "]",
        "material": "steel",
        "volume": 20,
        "bashing": 8,
        "category" : "veh_parts",
        "price": 60000
    },`

**Comment by jarmush** [comment]
this vehicle part is already spawning in RVs )
We do need a furniture with same mechanic. How i see it: place a tube through * (building menu) -> drop dirty clothes into the tube -> press "E" on tube, get menu with  'pick up items', 'start washing', 'cancel' actions  -> if you have enough water and detergent nearby - start long action depends on how many clothes need to be cleaned

**Comment by boydkr** [comment]
You could add a hand washbasin that uses the same mechanics as the vehicle mounted washing machine except requires a washboard.  Load it up with clothes (up to a max volume), wash as a long-action.

**Comment by RogueYun** [comment]
I think there was a change somewhere that makes this suggestion now obsolete for me. I'm closing the issue.
