### ISSUE TITLE
NPC missions freeze game upon attempting to get NPCs to return

### ISSUE THREAD

**Issue by chaoticidealism** [CleverRaven/Cataclysm-DDA#23081]
Game version:0.C-26494-g65faca5 (tiles)

Operating system:Win7

### Expected behavior
After NPC missions end, NPCs return from them.

### Actual behavior
Trying to get NPCs to return from their missions causes the game to freeze on this screen, with the skill name displayed and nothing else; game must be restarted to work:
![screenshot_1](https://user-images.githubusercontent.com/7295004/36828834-2bb60ad2-1cea-11e8-94d1-f7fbb60696bc.jpg)

### Steps to reproduce the behavior
Get multiple NPCs (I had five).
Send them all on a mission via the refugee center.
Wait for the mission to end.
Try to get them to come back; the game should freeze.

**Comment by Veraghin** [comment]
Just to confirm, were they sent out on a caravan mission by any chance?

**Comment by chaoticidealism** [comment]
Yes, that's exactly it! Caravan mission. Seeing your "excessive pop-ups" link, I tried it just now, and it turns out that what I thought was freezing was actually so many identical pop-ups that I thought the game had frozen. Pounding on the keyboard for a while got me through the pop-ups and the game started working again. Can an admin update this issue to reflect that? It's not a freeze; it's an interface issue that looks like a freeze.
