### ISSUE TITLE
add a script to check lint whitelisting of new json files

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#23085]
Linting should be enforced on newly added json files to prevent regressions in formatting. This could be achieved by adding a script to run on build that checks for new json files and automatically adds them to whitelist_json. I'm thinking either it could check against a file containing a list of all current jsons or it could check newly tracked files since the last common commit between the local branch and upstream. Maybe something to maintain the alphabetic/directory order of json_whitelist. Should be a pretty easy implementation.

**Comment by kevingranade** [comment]
What I did for astyle enforcement was toggle it to a blacklist so it would be opt-out instead of opt-in, but when I added build tooling for json linting it was an unmanageably large list.
As for maintaining the list, take a look at the bottom of doc/CODE_STYLE.md for some bash hacks I made for astyle.

**Comment by kevingranade** [comment]
looks like we have ~1,700 json files (WTF aaagh) as shown by this [search](https://github.com/CleverRaven/Cataclysm-DDA/search?utf8=%E2%9C%93&q=extension%3Ajson).
The whitelist has 360 files in it, so yea...

Still, it might be better to go ahead and flip to a huge blacklist to prevent regressions.

**Comment by ymber** [comment]
Yeah, blacklisting is probably the way to go. Larger file but it's simpler than continuously updating a whitelist. I'll get on it.

Autolinting the small files like in CODE_STYLE.md might get that ~1340 unformatted files down by a good few. What's the review process for json linting? For massive files too big to go through line by line what would prove that they came out the linter fine?

**Comment by kevingranade** [comment]
Manual, but you can append ```?w=1``` to the end of the diff url to supress whitespace changes, which makes a lot of changes relatively painless to review.
