### ISSUE TITLE
Do you even LIFT? We need makeshift lifts for vehicle maintenance.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#23094]
Game version: 
Since #22980
Operating system:
All
Tiles or curses:
All
Mods active:
N/A
### Expected behavior
Minor alterations to vehicles can be made using readily available tools.
### Actual behavior
Installation or removal of anything but the lightest vehicle parts requires either extreme strength or a tool with LIFT 1, of which there are only two (small or medium crane, defined [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/4024bbe80466ed36beffbcd329c0b6773532ec93/data/json/vehicleparts/engineering.json), and they're quite rare.
### Steps to reproduce the behavior
Have vehicle with removable storage battery (e.g. autotractor).
Try to remove.

Simplest solution is a makeshift lift or winch, like https://www.harborfreight.com/1-ton-chain-hoist-996.html and a way to attach it to a raised object like the side of a building or a tree.
On the even more makeshift side of things, one should be able to throw together a winch by bolting a drum and handle to a vehicle, and then throwing a rope over a tree branch or something.

**Comment by smolbird** [comment]
Small flaw in your example: swappable storage batteries only take 3 strength to install or remove.

**Comment by kevingranade** [comment]
Not since #22980
It's now 15, hence this issue.

**Comment by smolbird** [comment]
That would explain it, wasn't aware of that PR.

**Comment by John-Candlebury** [comment]
Not entirely related to the issue at hand, but needing a crane to change them kind of defeats the purpose of swappable sotrage batteries.

Maybe we should consider making batteries lighter, or making the storage case hold several smaller and hand-swappable batteries

**Comment by smolbird** [comment]
> Not entirely related to the issue at hand, but needing a crane to change them kind of defeats the purpose of swappable sotrage batteries.

That would make sense, yeah.

**Comment by kevingranade** [comment]
Especially since swappable batteries are just an example, yes it's pretty unrelated.  I.e. if someone made that adjustment this issue would just change the vehicle part it used as an example and stay open.
I have no problem with there being a lighter variety of swappable battery, but making batteries lighter isn't really an option (they weigh what they weigh), and I'm not clear how breaking them up would work.  Worst case that would end up requiring a major overhaul of vehicle parts and/OR part installation, since currently both of these assume one item = one vehicle part.

**Comment by Vane79** [comment]
Swappable batteries need to be fixed, since it doesn't matter now whether the battery is in swappable case or not - it all requires 15 str to remove.

**Comment by Nioca** [comment]
Clarification here: how are we defining "readily available tools"? As it stands, the aforementioned small crane can be crafted out of pipe, scrap metal, and wire, using a hacksaw, hammer, wrench, and welder. The hammer and wrench are pretty easy to come across, and the hacksaw and welder are both pretty critical to more extensive vehicle crafting (albeit not NEARLY as much as they used to be).

**Comment by kevingranade** [comment]
Good point.
We don't really have a way to quantify rarity, but there shouldn't be a need for anything of skill 3+, and welders are right out.
This could be rope, pipe, scrap metal, and some bolts.

**Comment by Vane79** [comment]
How do you even imagine that? There you are, driving through the wilderness:"oh my, my batteries died, better prepare that rope and winch to change the battery in the middle of nowhere". Do you imagine it was the case before the cataclysm? What's the point in them, then, if you can't swap them on the go, by hand?

**Comment by kevingranade** [comment]
It's not designed for wilderness emergencies, it's designed to rely on modern infrastructure like this https://www.engadget.com/2017/09/17/tesla-envisions-mobile-ev-battery-swapping-machines/
Or https://www.phoenixcontact.com/assets/downloads_ed/local_gb/web_dwl_promotion/5733e.pdf

The fact that it becomes difficult to deal with when that infrastructure breaks down is the point.

**Comment by Nymall** [comment]
Yeah, but as far as I understood it, the reason they exist as they do in game was to completely bypass the need of building a wiring system. Then batteries could be quickly and easily popped in and out without consuming welder charges or precious duct tape.

Considering I routinely do red-neck fixes to my real world vehicle with block and tackle and I'm sitting about ~8 str, possibly this change was a bit too zealous. Perhaps a block and tackle item only requiring a "roof" tile overhead to function?

**Comment by kevingranade** [comment]
If you read the OP that's exactly what I suggested.

**Comment by baraba3** [comment]
till this thing with storage battery happened i didnt know we had lift equipment at all and i coudlnt get what i need till i read on forums.maybe this shoudl be more clear to player somehow.

telescopic crane can be folded and is easy to use once assembled at least know so i dont see problem but woudl mind easier to make equipment.

**Comment by kevingranade** [comment]
It's a start, but I want something even easier.

**Comment by Granitecosmos** [comment]
How about something like [**this (video link)**](https://www.youtube.com/watch?v=4bRe0cyRdcs)? Four heavy sticks and two long strings, can't get any easier than that. Doesn't even need a roof/wall/tree. [**This one (another video link)**](https://www.youtube.com/watch?v=26pt5WmC16k) does need a tree or some other static heavy object, two heavy sticks and a long rope.

Slap some survival skill level requirements on it and it should be good enough for lifting/moving something like a storage battery.

**Comment by Endovior** [comment]
Relevant to this; Garages should frequently include non-makeshift Lifting equipment. Given the amount of vehicle modifications / repairs that require that ability, one would think that Garages would require that capability about as often as they require a Welder.

**Comment by Epictyphlosion** [comment]
This sounds like a good addition. Something like a block of concrete, or a strong block of wood can keep a car lifted up at least somewhat

**Comment by Night-Pryanik** [comment]
Would a craftable rope and pulley lifter that contains `crafting_pseudo_item: "pulley_lifting"` with `LIFT 1` and `JACK 1` qualities from [this mod](https://github.com/chaosvolt/MST_Extra_Mod/pull/8/) suffice?

**Comment by kevingranade** [comment]
That requires ``"pre_flags": [ "INDOORS", "SUPPORTS_ROOF" ],``, which you don't get with a tree, that's something you can install in a garage, but that's not much more accessible than a crane.

Something similar that can be installed adjacent to a tree or other support would work great though.

**Comment by ParaplegicRacehorse** [comment]
> Relevant to this; Garages should frequently include non-makeshift Lifting equipment. Given the amount of vehicle modifications / repairs that require that ability, one would think that Garages would require that capability about as often as they require a Welder.

As a professional mechanic, I can tell you absolutely that I require lifting assistance FAR more often than I require welding. Garages should include more small lifting equipment - and whole-vehicle lifts - and a whole lot less welding gear. The exception to less "welding" gear would be those small gas-bottle torches. Also, it's completely unreasonable to not ALWAYS find screwdriver-set (and wrench-set, which is not a game item but should be) in a mechanic location such as garage and tire shops.

I agree that smaller lifting gear should be added. The existing cantilever/crane is great but overkill for most lifting needs and is entirely impractical for others. By professional mechanic, I mean an engineer on ships, and I use block-n-tackle a whole lot more than any other lifting/rigging gear, often rigging temporary systems with just rope (no need for the "block" component).

Ratchet-straps are another good source for low-level lifting, given an anchor point.

A "gantry" could be made from a pair of crossed logs, pipes or beams (wood or metal) - possibly even planks - and either lashed or nailed/bolted together. This could eliminate or reduce the need for an overhead roof; also for butchering big critters.

As for this issue being a potential blocker for 0.F - No. I think it's way too big if 0.F is to be released in the next few weeks. It will require creation of several new items, with associated crafting recipes:

* Simple rope tackle. (lifting/pulling 1 ?)
* Ratchet strap (lifting/pulling 1 ?)
* Block-and-Tackle (lifting/pulling 2 ?)
* Chainfalls (lifting/pulling 3-5-ish, depending on how granular the lift/pull mechanic gets)
* makeshift gantry
* ... probably more. Professional rigger could give a better list.

and modifications to other game mechanics. I haven't looked at the code, though, so maybe this is a smaller change than I think. Still, it would be best to undergo a longer period of testing in experimental, so leaving it for 0.G would be better.

Off-topic but related -

On welding: I almost never require welding and I think the whole welding aspect of the game needs an overhaul - perhaps for 0.G. That said, much of the existing mechanics system has more to do with gameplay than it has to do with realistic representation; and making the kind of mods often made in game would, in fact, require extensive metal work in reality so maybe welding requirement should remain. But welding in real life also has expendables depending on welding type in use. Welding rod or wire and shielding gasses, etc.

**Comment by anothersimulacrum** [comment]
> On welding: I almost never require welding and I think the whole welding aspect of the game needs an overhaul 

Do you think welding is overused for things we use it for, or is it just that we model welding all wrong (power costs & methods)?
If it is overused, what do we use it for that we shouldn't and what should be done instead?

**Comment by ParaplegicRacehorse** [comment]
In order to keep this issue on-topic, I opened a welding discussion issue.

Now, back to lifting.

**Comment by actual-nh** [comment]
Block and tackle - I would think that sufficient Mechanic skill would autolearn this, but knowing it from Survival (or Fabrication) would take a recipe. (Currently, I'm guessing this would require multiple recipes?)

**Comment by ParaplegicRacehorse** [comment]
Typically, block-and-tackle refers to an arrangement of two or more pulleys ("blocks" -- a term from sailing) and rope. Passing familiarity with either Fab or Suvival would allow its construction. Blocks can easily be crafted from wood, though metal and plastic, with real bearings, are superior in terms of friction-loss. Someone familiar with knots could fashion a similar arrangement with just rope (say... Survival 2 or 3?), but the friction loss would be considerably higher and breaking point considerably lower.

Automobile mechanics are essentially never taught anything about block-and-tackle. Marine engineers (also mechanics) learn all about them, though.

I think the principal is simple enough to assume crafting auto-learn at Fab 2 or 3; Survival 3 or 4. Advanced materials for low-friction blocks, though, would be of higher order or require Proficiency in the Metals or Plastics group. The Proficiency would not need to be specific.

Block-and-tackle is a component of almost all cranes. Ideally, the engine-crane we all love to hate crafting for vehicle work, would be modified to include at least one block-and-tackle as a component.
