### ISSUE TITLE
Bindable keyboard shortcut for Reread last book

### ISSUE THREAD

**Issue by OliverUv** [CleverRaven/Cataclysm-DDA#23104]
Bindable keyboard shortcut for `Reread last book`, similar to `-` for `Recraft last recipe`.

**Comment by RogueYun** [comment]
Wouldn't mind one for re-drink last liquid type. Or maybe just a shortcut for drink from nearby clean water source.

**Comment by illi-kun** [comment]
Just for the record: we got similar requests previously in #574 & #7278 & #12113.

**Comment by illi-kun** [comment]
Closing as something similar to #22208.
