### ISSUE TITLE
Lint-checker regression: no longer confirms nature of lint failure

### ISSUE THREAD

**Issue by smolbird** [CleverRaven/Cataclysm-DDA#23105]
### Expected behavior
Console output for a failed commit will behave the way it did in the old days, when encountering incorrect linting. Console output for a failed commit will clarify what area of the file had the first lint error encountered, quote the relevant section, and even provide an example of correct formatting.

Moreover, the phrasing of the error message will be, as it evidently used to be, reasonably clear to new contributors unfamiliar with the lint rules.

### Actual behavior
Console output will cite "error 1" in reference to the file the lint failure occurred in, without any further useful information. No indication of what section is causing the problem, and no examples of correct formatting.

Worse, new contributors will be left puzzling over what the hell "error 1" even means.

### Steps to reproduce the behavior
1. Miss a section of changed code when lint-fixing your changes.
2. Commit because you thought
3. Observe your commit was marked a failure.
4. Check console output to confirm that that build bot hasn't broken yet again.

**Comment by kevingranade** [comment]
### Expected behavior
Linter fixes all your style issues for you.
### Actual behavior
Linter fixes all your style issues for you.
### Steps to reproduce behavior
Run linter locally.

**Comment by smolbird** [comment]
That doesn't solve the fact that new contributors will not know what "error 1" even means.

**Comment by smolbird** [comment]
Further points:
1. An error message that conveys nothing useful is not worth coding.
2. Documentation on how to lint-fix locally is either non-existent or not in a sane place (either in tools folder or docs, JSON_STYLE only tells you to use it, not HOW to use it).
