### ISSUE TITLE
Error in checking/reporting first aid/survival requirement for enzlave_actor::can_use

### ISSUE THREAD

**Issue by raeflondon** [CleverRaven/Cataclysm-DDA#23114]
Game version:c00fb6e95b8ded53bcd60fb25ba6b7eee4856d05

Operating system:Linux

Tiles or curses:both

Mods active:

### Expected behavior
Enslaving a zombie either works with first aid and survival of 1 or the message indicates you need at least level 2.
### Actual behavior
With first aid or survival of 1 enzlave fails with message "You need at least first aid 1."
### Steps to reproduce the behavior
Attempt to enzlave a zombie with survival or first aid of level 1.

**Comment by raeflondon** [comment]
@Night-Pryanik -- thanks for the quick PR

**Comment by Night-Pryanik** [comment]
You are welcome.
