### ISSUE TITLE
Evac shelter basements always spawning zombies, items

### ISSUE THREAD

**Issue by Leland** [CleverRaven/Cataclysm-DDA#23128]
Game version:
`master` as of 8b73b34

Operating system:
macOS 10.13.12

Tiles or curses:
Tiles

Mods active:
None

### Expected behavior
Prior CDDA versions had evac shelter basements with some simple items that occasionally spawned. Sometimes there'd be nothing.

Somewhat rarely, you'd encounter zombies down there. It was good that those encounters were rare, because as a starting character you have generally bad weapons and little chance of survival. The payoff with dealing with those zombies were tons of items.

### Actual behavior
All basements contain zombies and lots of items.

This, in essence, removes the ability for (most) starting characters to use items from basements.

This is from #22878. In particular, these lines https://github.com/CleverRaven/Cataclysm-DDA/pull/22878/files#diff-59604ea2f6e3da1d8c5be9188964f1c9L2927

I realize we can't do real conditional logic with JSON templates, and thus can't preserve the old approach of IF zombies THEN items. Perhaps just cut item and zombie spawn?

### Steps to reproduce the behavior
Teleport around the map to different evac shelters

<img width="536" alt="screen shot 2018-03-04 at 8 36 07 pm" src="https://user-images.githubusercontent.com/714017/36953856-d71c0df0-1feb-11e8-91b5-0c4553f17f2d.png">
<img width="616" alt="screen shot 2018-03-04 at 8 36 27 pm" src="https://user-images.githubusercontent.com/714017/36953857-d728ad12-1feb-11e8-86ac-cbb2aa110160.png">
<img width="573" alt="screen shot 2018-03-04 at 8 36 54 pm" src="https://user-images.githubusercontent.com/714017/36953858-d733f2c6-1feb-11e8-9b55-0aec6d25294f.png">

**Comment by ZhilkinSerg** [comment]
We can have two mapgens for shelter overmap terrain with different weights (e.g. 10 and 100): first will have both items and zombies, second - only items.

**Comment by Leland** [comment]
That sounds perfect

**Comment by ZhilkinSerg** [comment]
The fix is in, though item spawn can probably be adjusted a bit.
