### ISSUE TITLE
Allow cranes to install parts on the vehicle the crane is mounted on.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#23134]
Game version:
944cc2b0265d9b5fa4eca332d4073787e4984020
Operating system:
ALL
Tiles or curses:
ALL
Mods active:
NA
### Expected behavior
Player can use a crane mounted on a vehicle to install or remove parts from that same vehicle.
### Actual behavior
Player can NOT use a crane mounted on a vehicle to install or remove parts from that same vehicle.
### Steps to reproduce the behavior
Acquire a vehicle.
Install a crane of some kind on the vehicle.
Remove the engine from the vehicle.

### Problem
The problem seems to be that when lifting ability is cached at https://github.com/CleverRaven/Cataclysm-DDA/blob/f40ab2c5bd37446730a7eac228471e7f2120bb94/src/veh_interact.cpp#L358, a single value is retrieved, which assumes that if a crane is present it will be used to lift the target vehicle.  In order to achieve this, it ignores any lifting items mounted on the vehicle being modified.

### Proposed Solution
Retrieve two values instead of one, vehicle_max_lift and component_max_lift.
The former is the current value that *excludes* cranes installed on the current vehicle, and the latter is a new value that *includes* cranes mounted on the current vehicle.
Then use this new value at https://github.com/CleverRaven/Cataclysm-DDA/blob/f40ab2c5bd37446730a7eac228471e7f2120bb94/src/veh_interact.cpp#L589 and https://github.com/CleverRaven/Cataclysm-DDA/blob/f40ab2c5bd37446730a7eac228471e7f2120bb94/src/veh_interact.cpp#L1286 to determine ability to install or uninstall vehicle parts.

**Comment by New-Writer** [comment]
Smart idea. There’s no reason a crane mounted on the back of a truck couldn’t be used to remove that truck’s engine, or lift a new battery into place.

**Comment by Ramza13** [comment]
Just tested and I was able to use a forklift I installed on a vehicle to remove that vehicle's engine.

**Comment by irwiss** [comment]
Tested on f0d7703 and it still works
