### ISSUE TITLE
Mutations via Debug menu

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#23130]
Started a charakter with no traits/mutation's and i can not mutate (by debug menu) into (ID:)
WEB_SPINNER, WEB_WEAVER and WEB_ROPE. Didnt testmore. Is there somthing wrong with them?

**Comment by Night-Pryanik** [comment]
You need to be post-threshold spider mutant to get these. Debug-mutate to Arachnid (`THRESH_SPIDER`) first.

**Comment by ZenZen2** [comment]
Now i get it. Thanks a lot :)
