### ISSUE TITLE
Taking off armor via the '+ Sort Armor' isn't updated if you don't have inventory space for it.

### ISSUE THREAD

**Issue by mrkybe** [CleverRaven/Cataclysm-DDA#23139]
Game version: 0.C-26600-g944cc2b (tiles)

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: A lot.

### Expected behavior
Refresh the list of things you're currently wearing after taking off a thing and dropping it.

### Actual behavior
List only refreshes after menu is closed and reopened.

### Steps to reproduce the behavior
Try to take off something that you have no room to put in your inventory.
Say 'yes' to dropping it.
Item still appears as worn in the menu.

This doesn't happen if you have enough space in your inventory to store the item you're taking off, it refreshes normally in that case.

**Comment by Pseudo-ku** [comment]
Interestingly I think the list does refresh because it spends an action taking off whatever it is you were wearing. I see it momentarily blink (with the clothing still incorrectly listed).

**Comment by mrkybe** [comment]
@Pseudo-ku So further testing this, the player doesn't actually take off the item until you close the menu.  You also can't remove multiple items because of this through this menu, because, it doesn't actually do the 'player::takeoff' action until you close the menu and apparently you can't queue them up either.

**Comment by Pseudo-ku** [comment]
@mrkybe Interesting insight!

**Comment by mrkybe** [comment]
Ok more testing.  If you remove an item and it does fit in your inventory, its taken off fine.  If you remove a second item, it is also taken off fine, and the menu closes itself.
