### ISSUE TITLE
Character presets no longer save.

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#23135]
Game version: Most recent

Operating system: Linux Mint, and Windows 10

Tiles or curses: Tiles

Mods active: No

### Expected behavior
When you get to the end of the character creation screens, if you push ! and type in a label, it will save the preset for future use.

### Actual behavior
No error, but it does not save the preset. Using the "previous character" option does work, however.

### Steps to reproduce the behavior
Save a preset.

**Comment by mrkybe** [comment]
Yep, happening to me too.
