### ISSUE TITLE
Combine cash cards into a stack that displays their total value and number of cards.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#23136]
Game version:
944cc2b
Operating system:
ALL
Tiles or curses:
ALL
Mods active:
NA
### Expected behavior
Cash cards merge into a single stack that displays the total value.
### Actual behavior
Cash cards each have an inventory entry, obscuring the number and value of cards as well as cluttering the inventory.
### Steps to reproduce the behavior
Get a bunch of cash cards.
Marvel at the spam.

Should be fairly simple, just update
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L497
to make cash cards stack, and update
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L2380
to traverse the stack and print the total value.

**Comment by ManOfHonor** [comment]
Oh god yes.
I know it's a shitpost.
But I have to post it anyway.
ALL OF MY YES I HATE THE CASHCARD SPAM SO MUCH.

**Comment by Beetlecat** [comment]
A very "simple" idea, but the QOL return is high. Our inventory slot/letters will be thankful.

**Comment by RogueYun** [comment]
Why do we have cash cards again? Do they have any other purpose than vending machines? Why do we have vending machines that magically work in a post apocalyptic setting?

Just throwing that out there. Not trying to dis them as they make great fletchings, but I do wonder if they are worth the time/pain to implement.

**Comment by kevingranade** [comment]
Ambiance, and possibly in the future some factions (robots?) that don't understand that cash cards have lost their value.

**Comment by CoroNaut** [comment]
Reading CDDA lore should clear up the questions you have about cash cards. Since they are implemented then you can even come up with your own story of why they work. If you don't want them then you can just remove them from the available items.

**Comment by Veraghin** [comment]
I think #22094 could be related, after looking over the relevant code.
