### ISSUE TITLE
add migo speech generation during gameplay

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#23155]
The speech of Mi-Gos could be generated from what they hear during gameplay. This would give a function to the player shouting a sentence. Also possible would be using a markov chain or similar to generate lines for it based on what it's heard to make it look like it's trying to learn the language it's hearing. None of this would have any significant impact on gameplay but it would be good for atmosphere. Appearing intelligent would thematically distinguish some of the eldritch monsters from blob trash.

**Comment by codemime** [comment]
It implies a shared mind (ideally, a persistent one), otherwise the impact would be rather insignificant.

**Comment by ymber** [comment]
Shared mind would be the best way to handle it. As the game currently is the impact might be pretty insignificant anyway because the player is likely to be the only source of language input.

The idea could be extended by making the migo associate certain sounds and words with certain situations. That would allow it to try to set far more effective lures by making all the sounds of a situation instead of random unrelated noises that are obviously an eldritch monster. It could make different noises in different situations like lures with human speech or explosions and shouting to scare something away.

All that might be better done as a general system for situational behaviors so it could get bolted onto other monster AI.

**Comment by kevingranade** [comment]
I'm not opposed to the concept, but I'm also not interested in implementing it.
This falls into the same category as a generational development system for monsters, it's either grossly unrealistic, (migos have a hive mind, but they only parrot things they've heard the player say), or inconsequential (individual migos parrot things they've heard, but new migos would start fresh).

**Comment by ymber** [comment]
There's some stuff I would really like to do with procedurally generating more things. Hivemind migos could have new speech generated for them at evolution intervals to pretend they're hearing stuff outside the reality bubble.

Implementation for this kind of thing could get really complex. I know how I would implement the initial idea but beyond that is just concept.

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
