### ISSUE TITLE
Add book variations

### ISSUE THREAD

**Issue by Epictyphlosion** [CleverRaven/Cataclysm-DDA#23165]
By that I mean adding books which are the same name (War novel, drama novel, etc), but with different descriptions and slightly changed chapter, time, and fun values

This is to add some variety to the novels in the game. So instead of getting the exact same book each time, you could get a different one. Each one having a different description and different values.

When changing the values, I only mean increasing or decreasing them a little bit, not setting the fun to 99 or anything like that. For example, if one novel has 16 chapters, takes 20 time to read each chapter, and gives 3 fun, then a variation of that book would have 22 chapters, take 18 time to read each, and give 4 fun.

If you're still confused, I can provide screenshots of an example of what I mean.

**Comment by Cyrano7** [comment]
@Epictyphlosion Screenshot examples are always welcome.

**Comment by ZhilkinSerg** [comment]
Good idea for some kind of `more flavor` mod.

**Comment by illi-kun** [comment]
@Epictyphlosion I'm not sure if the issue on my side but I see this by your link:
> 403 Forbidden
nginx

**Comment by Epictyphlosion** [comment]
@illi-kun Try this one: https://postimg.org/image/6yrgpt8bp/

**Comment by illi-kun** [comment]
Yes, this one works fine, thanks.

**Comment by illi-kun** [comment]
@Epictyphlosion will you try to implement this? I see you did it for screenshot example why do not try to wrap it to a PR form?
BTW, you can massively use "copy-from" feature for definition of slightly different things, you can take a look on [seed.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/comestibles/seed.json) as example; "abstract" item contains definitions applicable in most cases and actual items copy it and add only unique changes.

**Comment by Epictyphlosion** [comment]
@illi-kun I can probably do it, but I have no idea how or where to submit a build for review
