### ISSUE TITLE
Crazy prepper's landmine house should NOT be a potential house spawn.

### ISSUE THREAD

**Issue by Pseudo-ku** [CleverRaven/Cataclysm-DDA#23164]
![what](https://user-images.githubusercontent.com/37226874/37230686-796836b6-243c-11e8-92e3-898964f2cc28.png)

Game version: 7190

Mods active: More Survival Tools, No Acid Zombies, Boats, Makeshift Items, Classes and Scenarios Mod, No Flaming Weaps, Disable NPC Needs, No Survivor Armour, Extended Realistic Guns

First time writing an issue so be gentle... someone on reddit told me to make an issue so I did.

----

On opening a scenario (I had this happen to me in Missed) and opting to start in a House, you have a (rare) chance of starting in a house with a lovely, red carpet. Two moves later, and you are DEAD. From two very conveniently placed landmines. Not to mention a bear trap to the south.

Granted this is probably me being a noob at the game, and I likely won't make the same mistake again. *But what would keeping this house spawn in achieve?* It's not unfair to think that the crazy prepper house should be something that characters must work up to, rather than start in.

This was a fresh world, fresh character. Also I have no idea what is actually in the house because this has been my experience with it, so there might be something here I'm missing. Either way, the spawn felt silly and bad. 5 minutes of character creation down the drain.

**Comment by ituluwituluwzev** [comment]
Insta-death on start is actually acceptable because 1, little progress is lost; 2, the player is aware of this type of house so they would be alarmed should they see a red carpet house later.

**Comment by Pseudo-ku** [comment]
True, both of your points are correct. But, my argument still stands.

*What does keeping this house spawn in achieve?*

Nothing of value is lost in removing this possibility from the game. Sure there is a learning experience here, but it almost feels spoiler-y. I didn't know about the red house, I didn't need to know about the red house, and now I know about the red house. Spoiled.

If anything, removing this spawn would add to the secrecy and sacrosanct of the house with the red carpet.

**Comment by Rivet-the-Zombie** [comment]
Yeah I'm going to agree that those pre-trapped houses shouldn't be a valid player spawn point.

**Comment by Pseudo-ku** [comment]
I could understand a little trap like a string tripwire that caves in a different room or a basement or sets off an alarm or something like that. That'd be interesting.

**Comment by smolbird** [comment]
Only issue is it uses the same mapgen ID as all other houses, so a little work would be needed.

**Comment by Zireael07** [comment]
Crazy prepper's house spices up the game a bit (you never know if the house has TRAAAAPS!) but I agree, it definitely shouldn't be a spawn point.
