### ISSUE TITLE
add weapon tripods

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#23169]
Tripods that reduce recoil on machine guns would make it viable to use something larger than an M249 without bolting it to a vehicle. The tripod would be deployed to a tile like a trap where it gives a MOUNTABLE (or new flag) point to fire from. The M192 lightweight ground mount could be used as a reference for stats.

**Comment by kevingranade** [comment]
It'd be just as easy to place as furniture as it is to place as a trap.
AFAIK tripods are generally going to be gun-specific.
Is there a particular reason to not make the whole gun and tripod assembly not be a single item?

**Comment by ymber** [comment]
The M240 and M249 have common mount points for the M192 and the M205 can mount a Mk 19 or an M2. Deploying the tripod separately as furniture is the best way I can see of implementing it without more significant code changes to add item actions from a gunmod.

**Comment by BorkBorkGoesTheCode** [comment]
@ymber do you plan to add tripods a some point?

**Comment by BorkBorkGoesTheCode** [comment]
@ymber I'm in a similar position.

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
