### ISSUE TITLE
Current Speed doesn't affect Base Move Cost

### ISSUE THREAD

**Issue by voch93** [CleverRaven/Cataclysm-DDA#23174]
Game version: 7194

Operating system: Linux (Ubuntu 16.04)

Tiles or curses: both

Mods active: default set

### Expected behavior
Current Speed affects Base Move Cost

### Actual behavior
Current Speed doesn't affect Base Move Cost

### Steps to reproduce the behavior
Expose yourself to damage, cold or heat, speed will decrease but move cost per movement (per step) will remain the same.

**Comment by kevingranade** [comment]
Speed is the number of move points you accrue each turn, not the number of move points you spend to move.

**Comment by voch93** [comment]
Sorry, I was confused by wiki page saying that "Base move cost = Speed + Move modifiers"
