### ISSUE TITLE
deprecate old butchery drop system

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#23170]
The harvest drop system is more versatile and easier to work with than the old system of deriving returns from corpse sizes. All butcherable monsters should have a harvest entry (many monsters could probably share a harvest definition) and the code for hardcoded drops should be removed.

**Comment by kevingranade** [comment]
If you want to make that happen, go ahead, but it's neither a bug nor a feature. I.e. this isn't a valid issue.

In general we have far too many issues open to keep wishlist items like this around.
