### ISSUE TITLE
Crafting failure should have a decent chance to waste only some materials

### ISSUE THREAD

**Issue by boydkr** [CleverRaven/Cataclysm-DDA#23207]
As far as I can tell, if you fail at crafting, it will either waste none of the material, or it will waste _all_ of it.  This is particularly annoying because it forces you to craft items with a minimal amount of input materials, and only crafting them one at a time.

If component destruction happened on an item-by-item basis for crafting failures, a character could spend a lot more time crafting items with real utility while also trying to train skills

**Comment by MattD94** [comment]
I kind of agree. It feels unrealistic that 24 rags would be wasted if I screwed up making a duster - realistically if you mess up part way through only the materials you have used up to that point would be wasted, and even then you should be able to salvage some.

Maybe crafting could fail more often but waste less materials  or crafting failure could produce an "incomplete" or "failed" version of the item that can be disassembled for a chance to get some of the materials back.

**Comment by Night-Pryanik** [comment]
Good suggestion, but still closing per lack of discussion for a long time and to clean up the issues list.
