### ISSUE TITLE
add more focus affecting states

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#23206]
Focus should be affected by things without going through the morale system. The two most obvious things that could change it are some eldritch monsters and drugs affecting executive function. For drugs it would allow for more realistic and interesting gameplay effects and it could be used as another thing to differentiate monsters from each other if there were a handful that could have psychological effects on the player.

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
