### ISSUE TITLE
Broken engines still power alternators.

### ISSUE THREAD

**Issue by Wulfe813** [CleverRaven/Cataclysm-DDA#23202]
Game version: latest

Operating system: any

Tiles or curses: any

Mods active: none

### Expected behavior
Broken engines don't power alternators.

### Actual behavior
Opposite of expected.

### Steps to reproduce the behavior
Break an engine with an alternator attached. It will continue to provide power.

**Comment by Night-Pryanik** [comment]
No need to open issue if you already have a solution for it.

**Comment by Leland** [comment]
Also see #19182
