### ISSUE TITLE
Vehicle parts retain damage fraction, don't stack, can't be repaired

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#23215]
Game version:
0.C-7181
Operating system:
Win 7 64 bit.
Tiles or curses:
Tiles.
Mods active:
  "dda",
  "StatsThroughSkills",
  "blazemod",
  "deoxymod",
  "ew_pack",
  "no_npc_food",
  "no_religious_Texts",
  "no_reviving_zombies",
  "novitamins"
### Expected behavior
Vehicle parts (when not installed) should either be:
a) not damaged, stacking, or
b) damaged, show a damage indicator in inventory, and be repairable.
### Actual behavior
Many vehicle parts have small enough damage to not be considered as having a proper damage level. They show up as white in inventory, cannot be repaired (only reinforced), but they do not stack with truly undamaged items. In save file they are shown having something like 0.334000, 0.583333, 0.666667, 0.668000, or 0.833333 damage. Parts that have the exact same amount of damage stack with each other. It looks like there is a piece of code somewhere that tries to damage parts by a proper amount (1, 2, 3) that then gets divided by some number that shouldn't be there.
### Steps to reproduce the behavior
Find a naturally-generated vehicle and fully disassemble it. You should get multiple non-stacking white parts. Not sure if you can reproduce this by just driving a brand-new car through random bushes of love.

This was mentioned back in #20871, but for some reason it wasn't considered an issue at the time.

**Comment by Leland** [comment]
Save file?

**Comment by Nandorianen** [comment]
Made a fresh character from a fresh install of the 0.C-7214. Walked up to a first car that had three green wheels and one red wheel. Took off the three "undamaged" wheels and got two stacks of items: 2 with no damage, 1 with a fraction.
Also, if I remove the last wheel and repair it, it goes into a third stack with a different fraction of damage.
Here's a save.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1821424/save.zip)
Here's a relevant part of it.
`{ "typeid": "wheel", "invlet": 113, "damage": 0.340000 }, { "typeid": "wheel", "invlet": 115 }, { "typeid": "wheel", "invlet": 115 }`
