### ISSUE TITLE
Alt-tab only works on second attempt

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#23216]
Game version:
0.C-7181
Operating system:
Win 7 64 bit.
Tiles or curses:
Tiles, no graphics.

### Expected behavior
When you alt-tab out of App 1, it switches focus to App 2 and lets go. When you press alt-tab again once, you switch back to App 1 if it wasn't fullscreen. If it was fullscreen, it becomes App 99 and you need to press tab multiple times to switch back to it.
### Actual behavior
With Cata set to windowed borderless mode, when I alt-tab out of it, my taskbar shows up, with App 2 selected there. But the cata window does not let go and stays on my screen, covering everything besides the taskbar. I have to press alt-tab the second time for Cata to let go, and that switches focus to App 3. Pressing alt-tab the third time gets me back into Cata without problems.
The same thing happens when I press win+d. Normally everything should minimize, losing focus and exposing the desktop, but with Cata it can require several attempts.

![image](https://user-images.githubusercontent.com/7211122/37482944-8be47a62-2896-11e8-8c32-8d7af8300128.png)

It's a small issue, but it can be quite annoying depending on how much you like alt-tabing. And depending on anyone besides me having it.

**Comment by Leland** [comment]
We've been plagued by alt-tab issues on Windows before. See: https://github.com/CleverRaven/Cataclysm-DDA/issues?q=is%3Aissue+tab+is%3Aclosed+label%3AWindows

**Comment by Night-Pryanik** [comment]
No confirmation for almost a year, closing.
