### ISSUE TITLE
Welder bug

### ISSUE THREAD

**Issue by Leon9621** [CleverRaven/Cataclysm-DDA#23211]
Game version: 0.C-26655-g8266f3d

Operating system: Windows 8

Tiles or curses: Tiles

Mods active: More Survival Tools, StatsThroughSkills, Vehicle Additions Pack, Tanks And Other Vehicles, Makeshift Items Mod, More Locations, Disable NPC Needs, Prevent Zombie Revivification, Simplified Nutrition

### Steps to reproduce the behavior Place an empty welder into a vehicle storage compartment, in this case a cargo space, press r to reload it from the cargo space, and begin repairing.

**Comment by ZhilkinSerg** [comment]
Duplicate of #22789.
