### ISSUE TITLE
Hard Addictions, quitting is too easy. 

### ISSUE THREAD

**Issue by Metalsoul212** [CleverRaven/Cataclysm-DDA#23232]
### Expected behavior
Characters with addictions to chemically addictive substances should have a very small chance to automatically use dependant substance if it's within reach. Chance should be low enough that it will be extremely rare to happen when walking by, but a good chance if you are sitting next to the substance for an extended amount of time while under the effects of withdrawal or if it's in your inventory. Physical addictions are no joke, anything from nicotine to crack can be incredibly difficult to quit while it's immediately available.

### Actual behavior
Characters can ignore stockpiles of extremely addictive substances while withdrawing from them.

### Steps to reproduce the behavior
Spawn a character with a heroin addiction. Place some heroin in inventory and laying around within reach. Spawn a stockpile of food and water to stay alive while you attempt to quit one the most horrifyingly addictive substances known to man, cold turkey while staring at it.

**Comment by kevingranade** [comment]
I'd be ok with this kind of thing if it's opt in via a trait, possibly "addictive personality".

**Comment by CoroNaut** [comment]
I really like the idea of having a small chance to just use nearby drugs if dependent. This would obviously be your character making a bad but quick decision on whether or not to take it, it isn't rationally thought out by the player. If the character is addicted, then they will not be thinking clearly at all.

Perhaps along with this you could have you character randomly say stuff like "I really a need this pill" or "I need to find some crack right now! AHH!"

Potentially adding in self destructive behaviors when very addicted to strong substances. This would be fantastic in my eyes. Just a suggestion but, what about we have the auto movement system lead our protagonist to the nearest substance. Now this would start making addicted runs more fun for certain.

**Comment by smolbird** [comment]
Having it be mandatory would not be a good idea though.

**Comment by bananaedmonkey** [comment]
It could be a trait, like "weak willpower".

**Comment by Shoes01** [comment]
At the very least, seeing nearby substances could mess with focus.

**Comment by smolbird** [comment]
Potentially an okay system, though I'm not sure if it addiction count should cause you to blow rolls while already under drug effects. In fact no, that's a bad idea. It'll cause addict counter to increase exponentially without micromanagement and cause deaths by drug overdose (which should NOT be beyond the players control regardless of perceived realism).

The check should also ideally factor in whether you can see the item, lest addicted players essentially found a stash by smell or ESP when poking through an area they haven't checked yet. This should also exclude items that are in lockers and related storage you can't actually see. Aside from being the only sane way to avoid "I found your stash via psychic powers" situations, it also gives players a fighting chance at managing their addiction.

Finally, I'm not sure if proximity to the drugs should have much impact on the calculation. At most it'll only have an effect in between "crafting range" (this is when items start being considered as near the player anyway) and "in use_action range" (in inventory, on same tile, or in the surrounding 8 tiles).

**Comment by Shoes01** [comment]
I'm not sure I follow your first paragraph. You're referring to my third bullet point? If so, then I'm fine with scrapping that idea. 

I think the ideal factor for checking is if the character _knows_ there are substances nearby. I hardly doubt there is code in place that has tiles flagged as explored or not, so I will definitely settle for the "out of sight, out of mind" approach. 

Regarding crafting range and use_action range: the focus break could occur at both ranges, but consumption only at crafting range. No extra rolls needed, as the inherent risk of getting high is pressure enough. I'll modify my post to reflect this.

**Comment by smolbird** [comment]
Yeah, was referring to third bullet point.

**Comment by CoroNaut** [comment]
Just a suggestion, what do you think about having the character impulsively pick up the drugs? Then the character puts the drugs they're addicted to into their inventory if they walk past it on a store shelf or in a crate or something? I know this could potentially be quite a computationally-intensive check so I don't think the benefits out weigh that.

**Comment by thethunderhawk** [comment]
Quick heads up: calling that trait “weak willed” or the like WILL upset someone down the line. Addiction is indeed no joke we ought to be sensitive here.

**Comment by bananaedmonkey** [comment]
Perhaps "implosive" then? It would be a negative trait so the name having a negative connotation is inevitable.

**Comment by kevingranade** [comment]
I think you mean, "impulsive"? But hey, if there's a game that can make "implosive" work its cataclysm.

My recommendation would be, "addictive personality".  It's pretty neutral and quite specific.

**Comment by kevingranade** [comment]
No update in over 6 months.
