### ISSUE TITLE
Scenario Idea: Road Accident

### ISSUE THREAD

**Issue by Xenomorph-III** [CleverRaven/Cataclysm-DDA#23237]
I'm u/a_wild_meowstic from [Reddit](https://www.reddit.com/r/cataclysmdda/comments/83sroh/new_scenario_idea_road_accident/)

**Premise:**

The player was one of the survivors who thought that, since the cataclysm was coming, it would be a good idea to escape by car.

The available professions are the same as for the Evacuee Scenario.

**Starting Conditions (1):**

The player spawns on the road, between 2 cities. Beside them is a vehicular wreck, representing their now-ruined vehicle. The wreck will have 1 or 2 zombies nearby, representing the driver/passenger(s) of the other vehicle. A pain modifier, various limb wounds and possible bleeding are applied on starting.

The area around the wreck will be littered with items, representing the supplies the character threw into their car before leaving. Spawned items would include whatever is normally found in cars (food, lighter, and maybe a spare tire/jack) along with standard evac shelter items.

Description: *When you received news of the cataclysm, you decided the best decision would be to escape by car. Your fear and exhaustion caused to to collide with another vehicle. Now, with your car totaled, and the extent of your injuries, what will you do?*

 A variation of this scenario can also be considered:

**Starting conditions (2):**

 The player character was driving out of the cities with the same purpose just after the cataclysm made itself known -- to escape, but their vehicle suffered a sudden collision with a large animal. The engine is ruined, rendering the vehicle inoperable, and the animal lies dead on the road.... until it rises from the dead. 

Similar to (1), the player starts out injured and in pain, on the road connecting 2 cities, spawning in a vehicle of any type, excluding the military and police vehicles (unless it was tied to profession -- say, a Police Officer would spawn in a police car, a Military Recruit/Spec Ops in a military truck/APC, and so on)

The "engine" square of the vehicle will be heavily damaged, with the engine itself highlighted in grey.
A moose/bear/cougar corpse can be seen in front of the vehicle, which will rise as the zombie equivalent. 

Description: As the cataclysm broke out, you decided to escape by car. Driving down a country road, you suddenly collide with a large animal. Your vehicle is inoperable, and you were knocked unconscious by the crash. You awake to the sound of something attacking your vehicle.

A mock-up of one the scenario's starting conditions can be found at the link below.

**Starting Conditions(1): Mock Up:**

![The mock-up for the scenario ](https://user-images.githubusercontent.com/25373560/37561370-ed6a92ae-2ab1-11e8-8eb9-09e8bba6cdc0.PNG)

**Comment by ZhilkinSerg** [comment]
This could be achieved by adding road start location and new mapgen extra for roads.

**Comment by Xenomorph-III** [comment]
@ZhilkinSerg, I'm only familiar with Python and MATLAB.

**Comment by Eddyskingdom** [comment]
i had the same idea

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
