### ISSUE TITLE
Project Suggestion: Item Storage

### ISSUE THREAD

**Issue by Shoes01** [CleverRaven/Cataclysm-DDA#23249]
From past experience while contributing to the game, I know there are firm ideas on what a proper item storage system would look like. I suggest that some one who knows these ideas should add an entry to the Projects tab detailing them.

I like to think item storage is a high-demand feature, but also requires a lot of skill to implement. If it were chunked, then multiple people could chip away at it with little commitment, rather than one person committing a huge amount of time.

**Comment by Leland** [comment]
Saw that you've been a part of past inventory tickets. I'm going to go ahead and close this one – can you actually post this over in #3671, the current "item storage" issue we have open? Check out #10926 for some past thoughts as well.

The first step would be actually coming up with an approach, which of course should be done in that main ticket.
