### ISSUE TITLE
Invisible creatures, zombies using ChestHole32Tileset

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#23245]
7221 64bit tiles 
win 10 64bit

A fair few mods active shall get list if realllyy needed

Expected behavior 
to see a tile icon for monsters,creatures or at least resort to asci fallback icon

Actual behavior
invisable nothing shown at all use shift+V it says a zombie child is there but its invisable

Steps to reproduce the behavior
just play for a bit or even spawn in a zombie child :)

**Comment by ZenZen2** [comment]
ping @Chezzo 
Some id's point to a transparent tile.

**Comment by stk2008** [comment]
That would explain it then :).
Thanks

**Comment by stk2008** [comment]
Shall do some more digging as my bro had the same issue but it was a racoon I think.

BRB let me go spawn in a few things and check :).

**Comment by stk2008** [comment]
https://i.imgur.com/6tsUQlS.png

https://i.imgur.com/Bt7N7hR.png

I am using a fair few mods

Go to debug screen and filter

child

spawn all the entrys in there i see 5

https://i.imgur.com/8NpOkim.png

two of these are invisable as per my screenshots above.

**Comment by Leland** [comment]
Looks like vanilla DDA only has two entries in the spawn menu for "child," and neither spawn invisibly.

One of the active mods you have is likely introducing those.

<img width="286" alt="screen shot 2018-03-18 at 1 32 59 pm" src="https://user-images.githubusercontent.com/714017/37568844-0e8fcfcc-2ab1-11e8-997c-2e7cab98e2ae.png">

**Comment by stk2008** [comment]
yeah assumed it would have been a mod issue but not sure how to fix it DOH LOL.

**Comment by illi-kun** [comment]
Could you at least say name of the mod?

**Comment by stk2008** [comment]
I have no idea what the mod is that is causing it if you are asking what mods I have active I linked it above I think

yep

https://i.imgur.com/mNBCjYJ.png

these are all the mods I have active when this issue happens :).

Again thanks for replying and taking the time to help me realy appriciate it :)

**Comment by Ker-Nes** [comment]
I have been having this behavior with Opossums during spring, and while my game is modded, it's only with mods that come with the game.

**Comment by ZenZen2** [comment]
Does the mod name matter? I see it as a problem of the tileset. Those id's are in the tile_config means there will be no asci fallback.

**Comment by stk2008** [comment]
Just as an FYI im now on IRC and Chesthole has fixed the zombie issue :)
I mentioned about the Opossum so fingers crossed

If any one has any more he said please let him know :)

**Comment by ZenZen2** [comment]
Hello @Chezzo , is it possible to delete all id's that lead to a transparent tile? that would fix this problem. I ask because it seems there are many of them, after a quick check i found these:
```
mon_mi_go_terminal
mon_zombie_master_pk
mon_bear_smoky_pk
mon_zombie_lord
```
mon_zombie_lord id for example is on line 53034 that leads to his proper grafik but gets overwriten on line 57155 that leads to a transparent tile.

**Comment by ZenZen2** [comment]
Just a minor thing: tr_brazier need to be replaced with f_brazier to be visible again.

**Comment by ZenZen2** [comment]
From testing it looks like #23272 fixed all the issues from here. Reopen if i missed somthing.
