### ISSUE TITLE
make volume of items on a tile affect move speed

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#23244]
Moving on a tile with a large volume of items on it would typically take longer than moving on flat ground. Implementing a move penalty that increases linearly with the volume of items on a tile would create new tactical considerations in combat and make aisles a much more attractive option in cargo vehicles. A linear increase would require a realistic cap on max volume on a tile to keep numbers sane.

The biggest impact would be how corpse stacks change battlefields. Bottlenecking zombies in a doorway would create an increasingly large stack of dead zombies in that doorway which further increases your advantage. This could be a balance problem or an opportunity to differentiate mindless monsters from intelligent ones.

**Comment by voch93** [comment]
Current volume cap on a tile is 1000 L, that's only one cubic meter and 16 human corpses.

Most vehicle parts already have the highest 400 movement cost, that's 4 times normal (around 24 seconds I guess) and sounds like a reasonable cap before an obstacle becomes impassible.

I like the idea of volume adding up movement points to terrain up to some reasonable cap, but considering all above, linear growth won't make a big gameplay impact. Dragging 8 corpses to a doorway tile will raise its cost to 250 points. If you are already so good at killing things I doubt you will need such an obstacle.

**Comment by CoroNaut** [comment]
I can see this being a larger than normal consideration for players with less than 2 hours on their character, but for all characters above 2 hours, its going to become a fantastic ally as you cut down zombie after zombie in a single doorway or make a pile around yourself in some direction in an open space. It would allow you to easily get away while the creates have a hard time even getting your past location.

How would a martial artist specializing in movement-type styles fair? Would they have some buff to help them overcome the stacks of bodies? How would this affect vehicles going over say, scrap from multiple nearby vehicles in the street? Would its movement be reduced linearly as well, but within a ratio of its mass to the volume of items below the car? Would these high volume tiles create a barrier that you can hide behind like using cover in a battlefield? If so then you need to damage a random item with weighted chances given by volume in that pile if it strikes the pile before getting to you when behind that cover. Would you be blocked if you tried dragging a cart over one of these high volume tiles? could small motorcycles potentially be stopped if they don't have momentum?

This is a big game play change but I can barely think of how this will affect late game players other than helping them immensely.

**Comment by voch93** [comment]
@CoroNaut that's all separate features, most of what can be implemented without the discussed one, as it all comes from movement points cost of a tile. I'd rather focus on what title says, decide if it's needed and if so how it could be implemented.

**Comment by CoroNaut** [comment]
I was talking about extremes, saying that the tile affects move speed so much so that it is practically impassible and all the details that come with that. Other than that, everything I talked about was about movement speed being affected by volume on the tile. I just gave a list of things to consider if it does become implemented. These things will make it a bigger consideration instead of just a tiny <100 line coding challenge.

**Comment by Tatterdemalian** [comment]
This is a good idea, but should be combined with making movement through a tile that is sufficiently overloaded to obstruct movement have a chance of knocking objects in the tile into adjacent tiles (cascading if this exceeds the volume limit of those tiles) when it's moved into, with zombies having a 100% chance of doing this, as they generally don't care what they have to knock aside to get through. So this wouldn't slow down zombies at all, and might even result in piles of objects getting knocked over onto other zombies and even the player.

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
