### ISSUE TITLE
Attributes are not accessible in Lua in VisualStudio builds

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#23258]
Following Lua code returns `nil` values when I compile in Visual Studio 2015 on Windows:

```LUA
local tp = tripoint( 11, 22, 33 )
print("X:"..tostring(tp.x))
print("Y:"..tostring(tp.y))
print("Z:"..tostring(tp.z))
```

It works fine with downloaded binary or when I compile in Code::Blocks (MSYS) on Windows.

Can someone please confirm the issue exists or is it something in my system?

_Edit (2018-05-10):_ Same issue on fresh Windows 10 with Visual Studio 2017.

**Comment by BevapDin** [comment]
Did you actually compile with Lua support? Does any other Lua code work? Does it work for `point` or for some other value received from the game (e.g. some `item` property)?

**Comment by ZhilkinSerg** [comment]
> Did you actually compile with Lua support? Does any other Lua code work? Does it work for point or for some other value received from the game (e.g. some item property)?

All Visual Studio configurations have SDL and Lua enabled. Lua works (e.g. I can run `print(_VERSION)`, `game.popup("sometext")` or `dofile('./1.lua')` in console), but all attributes (defined in class_definitions.lua) are not accessible.

![image](https://user-images.githubusercontent.com/16213433/40614616-34c30dc2-628c-11e8-9cd1-367a94ff72dd.png)


[1.lua.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/2045044/1.lua.txt)

**Comment by BevapDin** [comment]
Well, the script works here on Linux (Lua 5.3). Did it work previously? Is the file "src/lua/catabindings.cpp" up to date? (Should be about 1 MB large.)

**Comment by ZhilkinSerg** [comment]
> Well, the script works here on Linux (Lua 5.3). Did it work previously? Is the file "src/lua/catabindings.cpp" up to date? (Should be about 1 MB large.)

Yeah, I know it works. It will work fine if I grab pre-compiled version from Jenkins or compile myself on Linux or on Windows via Code::Blocks (MSYS). 

Yes, `src/lua/catabindings.cpp` is up to date and is being regenerated normally (I didn't compare this file generated on different systems, but I believe it will be the same as it is being generated by lua which is the same on different platforms).

I was using Code::Blocks (MSYS) on Windows for building my Lua PRs and found that Lua is partly not working in VS only by chance. I don't know when it stopped worked on VS, but I have probably tested some basic Lua statements in VS builds last year (including `point` attributes).

I will probably need to bisect - though it is PITA on Windows.

**Comment by ZhilkinSerg** [comment]
This one here could be from VS:

https://github.com/CleverRaven/Cataclysm-DDA/issues/22308#issuecomment-340675678

**Comment by ZhilkinSerg** [comment]
So, I've put contents of `/lua/catabindings.cpp` instead of `#include "lua/catabindings.cpp"` in `catalua.cpp`, put a breakpoint inside of `get_tripoint_x` function and now I get this:

![image](https://user-images.githubusercontent.com/16213433/40622342-c002c716-62a9-11e8-9062-2d28b20c9cdc.png)

That is not so good.

**Comment by ZhilkinSerg** [comment]
Hmm... I've added `get_point_x` and `get_point_y` functions as members of `static const struct luaL_Reg gamelib []` and now breakpoints are not optimized away, but I do not hit the breakpoint when I run `print("pX:"..tostring(tp.x))` in Lua.

**Comment by ZhilkinSerg** [comment]
Seems to be resolved when using `vcpkg` and `v141` tools (see https://github.com/ralreegorganon/Cataclysm-DDA/tree/vs-local-mods).
