### ISSUE TITLE
Manhack drops items on death that it wasn't crafted from

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#23251]
Game version: 7222
Operating system: Linux (Ubuntu 16.04)
Tiles or curses: Tiles
Mods active: default set

### Expected behavior
Manhack drops "broken manhack" item on death and nothing more.
Broken manhack can't be activated, but can be disassembled to obtain items it was created from.
Dropped broken manhack varies in degree of damages (so you can't seamlessly recraft every broken one).

### Actual behavior
Manhack drops "broken manhack" item and others as well, that it wasn't created from (Kevlar plate, battery (100), blade, signal receiver, etc.), allowing you to farm items you don't own.
Disassembling broken manhack may result only in few items it was made of.
Every "broken manhack" item drops uninjured.

### Steps to reproduce the behavior
Activate some manhacks and watch them die.

---

PS: I'd also like to share some thoughts about current implementation of "inactive manhack" craft. Maybe someone will pull it into a separate issue if you feel it, or the full manhack remake will make this unnecessary.

So now you basically solder a bunch of electronics in 8 minutes and get friendly flying robot ready to shred your foes. Two things come into mind straight away: it has no sign of a motor, it has no power supply (unless you've used optional plutonium cell). Well okay, intermediate crafting of a motor is boring and may be implicit, but for comparison: time to complete "small electric motor" is 20 minutes and requires additional tools and components. So my suggests are:
* Increase craft time (*as well as* for all "inactive foo hack" items) from 8 minutes to 25.
* Remove optional "plutonium cell" from the recipe and add mandatory "batteries (100)" to it. Disassembling broken manhacks should not result in batteries though, or only in small amount of them.

**Comment by Leland** [comment]
Here:

https://github.com/CleverRaven/Cataclysm-DDA/blob/672a53ded9ef092f4a28910cc48a2c28c4d6e1b1/data/json/item_groups.json#L6749-L6754

Introduced in #17592. Not entirely opposed to keeping it as is - could be seen as parts that fell off the manhack when destroyed.

**Comment by voch93** [comment]
@Leland you may probably have thought that "crafted from" is my assumption on manhack build? Well, it may be acceptable behavior for industrial assembled ones, but I can literally craft one from scrap metal and get Kevlar, that's wrong.

**Comment by Leland** [comment]
My comment was regarding "Manhack drops 'broken manhack' item on death and nothing more"

Kevlar plate is a little weird, yes.
