### ISSUE TITLE
Drinking clean water consumes container when internal furnace is active

### ISSUE THREAD

**Issue by MattD94** [CleverRaven/Cataclysm-DDA#23262]
Game version:
0.C-26851-g935cea8

Operating system:
Ubuntu 16.04.3 via Linux Subsystem for Windows

Tiles or curses:
curses

Mods active:
DDA
Filthy Clothing
Disable NPC Needs
Simplified Nutrition
Vehicle Additions Pack

### Expected behavior
When a player consumes the last charge of a drink/food item in their inventory, the container is not consumed by internal furnace if internal furnace is on.

### Actual behavior
Containers are consumed by internal furnace upon consuming the last charge of their contents and no message is displayed to indicate it was consumed or any power units were gained.

### Steps to reproduce the behavior
1. Install internal furnace CBM or start with player that has it
2. Spawn a bottle of clean water from debug menu
3. Make sure internal furnace CBM is active
4. Drink both charges of the water
5. Plastic bottle is now gone with no indication that it was actually consumed by furnace or any power was gained
6. Repeat with internal furnace off to see that the bottle is not consumed when not active

Also this is unrelated, but does anyone else think the internal furnace message is odd? It says that you "digest" the item, but really you should be "burning" it or something - unless you are actually eating it, but that would be really inefficient, unsatisfying, and in the case of eating filthy items, gross.

I think I'm gonna make small mod that adds calculators to the game to consume by the furnace - it will have the description "It's a calculator. You can eat it to gain its power." And you will be able to eat it without the furnace on, but you will get the message "Uh oh, the calculator is lodged in your colon!" and take torso damage. Maybe I will also change the internal furnace so that when you eat the calculator, it says "Sweet quadratics of fiery mathematics! You recharge X energy!"

**Comment by BorkBorkGoesTheCode** [comment]
Cyberjunkie has an internal furnace, so it can be tested

**Comment by BorkBorkGoesTheCode** [comment]
Cyberjunkies don't consume aluminum cans after drinking pilsner with internal furnace on. Testing glass containers.
