### ISSUE TITLE
mapgen: Bad add_spawn mon_sewer_rat

### ISSUE THREAD

**Issue by LukeMS** [CleverRaven/Cataclysm-DDA#23273]
Game version: 0.C-26878-g46b3fa8 (tiles)

Operating system: win 7 x86

Tiles or curses: tiles

Mods active: "dda", "Medieval_Stuff", "Mining_Mod", "More_Survival_Tools", "StatsThroughSkillsZ"¹,   "YM_classes"¹, "alt_map_key",   "makeshift_tools"¹, "no_npc_food", "novitamins"

¹ mod-mods and custom stuff, but none related to sites and spawns.

### Expected behavior:

spawn mobs (evac shelter basement)

### Actual behavior:

no spawns

### Steps to reproduce the behavior:

new game starting at the evac shelter, went downstairs, error message popped up, no spawns.

DEBUG: Bad add_spawn(mon_sewer_rat, 1, -2, 1)

FUNCTION: void map::add_spawn(const mtype_id&, int, int, int, bool, int, int, std::__cxx11::string)
FILE: src/mapgen.cpp
LINE: 6775

**Comment by ZhilkinSerg** [comment]
Can you please describe reproduce steps in more details? Were you in a evac shelter basement, just move into into it or what?

**Comment by LukeMS** [comment]
Added the steps to reproduce the bug.

**Comment by Leland** [comment]
Can you try downloading the latest experimental version and seeing if this still occurs? https://cataclysmdda.org/#downloads

**Comment by LukeMS** [comment]
After a few attempts with the latest version everything seems to be working perfectly.

**Comment by ZhilkinSerg** [comment]
Closing then.
