### ISSUE TITLE
Condiments/sandwich toppings have disproportional nutritional value

### ISSUE THREAD

**Issue by FluffyRedSheep** [CleverRaven/Cataclysm-DDA#23287]
## Condiments: Mayonnaise, Mustard, Ketchup
**At this point in time,** two condiments in the game (namely *mayonnaise* and *mustard*) posses what could be considered an absurdly high nutritional/quench value:
**item**: nutrition/quench/enjoyability
**mayonnaise**: +15/+15/-5
**mustard**: +10/+10/+0
On the contrary- **ketchup** seems to be a bit more reasonable:
**ketchup**: +3/+0/-1

Drinking an entire bottle of mayonnaise (.5L in size, individual portions being .05L) would give the player **+150 nutrition**, and **+150 quench**- which would be more than a full-course meal.

**I suggest** perhaps dropping the nutritional value way down- bringing each condiment to the same level as ketchup (with perhaps a tiny margin if it's really deemed necessary).

## Sandwich Toppings: Bologna
**A similar issue** arises with the issues of **bags of bologna**.
A bag of bologna, as of right now- contains **40** slices (or **40 portions**), each with an individual nutritional value of **+8**. The bag itself weighs **.88 kilogrammes**. The entire bag has a total nutritional value of **+320**.

A **.88 kilogramme** bag with **40** slices of bologna seemed a bit ridiculous to me, so I took an excursion to the refrigerator.
[A bag of smoked hams, 200 grammes](https://i.imgur.com/yc9iBkJ.jpg)
[A bag of other lunch meats, 150 grammes](https://i.imgur.com/LnZ1GcV.jpg)

While performing this *scientific experiment*, I've been made aware that **1lb** bags of bologna are not uncommon.

If we estimate an individual slice to be around **28 grammes**, then a **1lb** bag would contain about **16 slices**.
A **200 gramme** bag would contain about **7 slices**. 

A meat sandwich requires five slices- and gives 3 portions of lunchmeat sandwich. Each portion has a **+30** nutritional value. That's **+90** nutritional value for the player for 5 slices of bologna with some bread. Whichever bag size of bolognas we should go with depends largely on balance- as a **16-slice** bag could give the player up to **+270** nutritional value granted they can find bread.

As for the nutritional value of a slice of bologna itself- this could be toned down a bit as well- my suggestion is **+4** or **+3** nutrition per slice.

## Recap:
**Mayonnaise:**
 --Nutrition: +15 => +3
 --Quench: +15 => +0
 --Enjoyability: -5 => -1
**Mustard:**
--Nutrition: +10 => +3
--Quench: +10 => +0
--Enjoyability: +0 => -1
**Bolognas:**
--Amount per bag: 40 => (7 or 16)
--Nutrition: +8 => (+4 or +3)

**Comment by Epictyphlosion** [comment]
What we could really use is a crafting recipe for sandwiches. Like, a plain bologna sandwich with no sauce would be okay, but mayo would improve enjoyability. I'm pretty sure anybody who has eaten a bologna sandwich knows this

**Comment by FluffyRedSheep** [comment]
This issue focuses largely on the nutritional value of condiments and sandwich toppings on their own, and how many slices of bologna there should be in single bag. The meat sandwich example was put up as balance consideration for when deciding how many slices of bologna there should be in a bag. Unless someone override me, I don't think this is necessarily relevant to this discussion.

**Comment by Leland** [comment]
Think your reasoning here makes sense, feel free to open a PR with those changes.

**Comment by FluffyRedSheep** [comment]
**I've found the initial reason** for the bologna being this ridiculous- the crafting recipe for bologna essentially cooks it in _bulk_- the crafting recipe for bologna requires **8 chunks of meat** and results in **40 portions**- going from a total nutritional value of **400** to **320**. A side effect of this crafting recipe, however, that bologna found in the wild (supermarkets, houses, etc) also come in 40-packs so to speak.

I'm preparing a pull-request as we speak. This pull request shall not only nerf the earlier described condiments and bolognas- but it shall also modify the bologna crafting recipe from **8 chunks of meat** to only **1 chunk of meat** required for 8 slices of bologna (going from a **400 => 320** net nutrition loss to a **30 => 24** net nutrition loss), along with *halving* the soy-sauce/seasoning/salt requirement (from *10* to *5*).

**Comment by FluffyRedSheep** [comment]
And with that, PR #23292 has been made.

This pull request (and issue) does not cover the crafting requirements and high nutritional value of sandwiches made _with_ bologna (e.g. the Meat Sandwich requires **5** slices of bologna, some bread, and then gives up to **3** portions of **30** nutrition, which is _insane_). I'll probably address that in a future issue.
