### ISSUE TITLE
shelter's basement lowered zombie spawns

### ISSUE THREAD

**Issue by LukeMS** [CleverRaven/Cataclysm-DDA#23286]
Game version: 0.C-26906-g2d088ac (tiles)

Operating system: win 7 x86

Tiles or curses: tiles

Mods active: "dda", "Medieval_Stuff", "Mining_Mod", "More_Survival_Tools", "StatsThroughSkillsZ"¹, "YM_classes"¹, "alt_map_key", "makeshift_tools"¹, "no_npc_food", "novitamins"

¹ mod-mods and custom stuff, but none related to sites and spawns.

### Steps to reproduce the behavior: new game starting at shelter, go down to basement

The latest commit with changes to shelter.json (6084e9a) intentionally lowered item spawns there, but it also lowered zombie spawns.
Currently both items and zombies have 10/110 chance.
Was it intentional? If not the json's first template (the one with weight 100) should also have "place_monsters" on it.
Reducing both item and zombie spawns make the basement pretty much an empty place.
Personally I think that's a waste, and will mod it if remains like that.

**Comment by John-Candlebury** [comment]
That's how the shelter has traditionally worked for a long time.

 The most common shelter is almost empty, with a rare variant that has few zombies and some loot.

**Comment by ZhilkinSerg** [comment]
Below is original algorithm prior to #22878 - there were 1/10 chance to spawn monsters with lot of loot and 9/10 chance to spawn items without monsters.

```CPP
        if( one_in(10) ) {
            // Scatter around lots of items and some zombies.
            for( int x = 0; x < 10; ++x ) {
                m->place_items("shelter", 90, 6, 6, SEEX * 2 - 8, SEEY * 2 - 8, false, 0);
            }
            m->place_spawns( mongroup_id( "GROUP_ZOMBIE" ), 1, 6, 6, SEEX * 2 - 8, SEEY * 2 - 8, 0.2);
        } else {
            // Scatter around some items.
            m->place_items("shelter", 80, 6, 6, SEEX * 2 - 8, SEEY * 2 - 8, false, 0);
        }
```

Current numbers are not exactly the same, but very close to what was earlier.

**Comment by illi-kun** [comment]
I see no isuue here, it's working as intended.

**Comment by Leland** [comment]
Linking #23128 and #23132 for posterity
