### ISSUE TITLE
ChestHole tile for spotted landmine too subtle

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#23296]
Game version: cataclysmdda-0.C-7227

Operating system: windows 7

Tiles or curses: tiles

Mods active: Default ones

### Expected behavior
I walk into a mine and get blown up

### Actual behavior
Game asks me if I want to step onto the mine (that is unrevealed to me)

### Steps to reproduce the behavior
Load the game from attachment try stepping north.
[Merrillville - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1845214/Merrillville.-.Copy.zip)

**Comment by Zireael07** [comment]
This is intended, otherwise there would be many many ragequits.

**Comment by ZenZen2** [comment]
It was unrevealed to you, else you wont get a warning. Tested your save and found one that didnt give me a warning.
Use Debugg and set perception to 1 and run into a minefield = no more warnings.

**Comment by ZenZen2** [comment]
Here you can see that it was revealed to you due to your high perception
![mine](https://user-images.githubusercontent.com/20055252/37877597-c846a97a-305d-11e8-9888-88861acfaf06.jpg)

**Comment by kevingranade** [comment]
Is there no "buried but noticed landmine" tile?
From the screenshot it seems like the landmine is practically invisible,
even though it was detected.

**Comment by ZenZen2** [comment]
``` tr_landmine_buried ``` and ``` tr_landmine_buried_season_winter ``` is used for detected landmines. Chesthole, MShock and MXotto use tiles there with no difference to normal background.

**Comment by DracoGriffin** [comment]
@kevingranade From ChestHole, yes there is. For simplicity, I'm just going to focus on ChestHole's, but I believe MShock and Xotto all follow the same methodology.

ChestHoleTileset\tile_config.json:
```json        {
          "id": "tr_landmine_buried_season_winter",
          "fg": 2587,
          "bg": 2424
        },
        {
          "id": "tr_landmine",
          "bg": 2424,
          "rotates": false
        },
        {
          "id": "tr_landmine_buried",
          "fg": 2586,
          "bg": 2424,
          "rotates": false
        },
```
ChestHole32Tileset_iso\tile_config.json:
```json
        {
          "bg": 2424,
          "fg": 2587,
          "id": "tr_landmine_buried_season_winter"
        },
        {
          "bg": 2424,
          "id": "tr_landmine",
          "rotates": false
        },
        {
          "bg": 2424,
          "fg": 2586,
          "id": "tr_landmine_buried",
          "rotates": false
        },
```
ChestHole32Tileset\tile_config.json:
```json
        {
          "id": "tr_landmine_buried_season_winter",
          "fg": 2587,
          "bg": 2424
        },
        {
          "id": "tr_landmine",
          "bg": 2424,
          "rotates": false
        },
        {
          "id": "tr_landmine_buried",
          "fg": 2586,
          "bg": 2424,
          "rotates": false
        },
```
ChestHole16Tileset\tile_config.json:
```json
        {
          "id": "tr_landmine_buried_season_winter",
          "fg": 2587,
          "bg": 2424
        },
        {
          "id": "tr_landmine",
          "bg": 2424,
          "rotates": false
        },
        {
          "id": "tr_landmine_buried",
          "fg": 2586,
          "bg": 2424,
          "rotates": false
        },
```

What it looks like in tiles.png:
https://cdn.discordapp.com/attachments/365907426270117888/427588511823036416/hiddenburiedlandmine.png
The two terrain tiles above the pit are for buried landmines/bear traps (they share the same foreground tile). The first row along the top is for normal grass (non-winter/winter) terrain.

What is looks like in-game zoomed in (credit to @NoCreativeNames ):
https://cdn.discordapp.com/attachments/365907426270117888/427593311147130900/unknown.png
There are only two buried land mines in this picture (one directly north, and one directly west. The "other" one in the top left corner is NOT a buried land mine).

**Comment by kevingranade** [comment]
Yea  that's like a million times too subtle, it needs to be obvious at a
glance that something's there.

**Comment by Chezzo** [comment]
I'll get it fixed.

**Comment by ZenZen2** [comment]
Another way to get minefields:
open regional_map_settings.json and replace
```
          "field": {
              "chance": 90,                 "//": "one in # chance of spawning an extra",
              "extras": {                   "//": "weighted list",
                  "mx_helicopter": 40,
                  "mx_military": 8,
                  "mx_science": 20,
                  "mx_collegekids": 25,
                  "mx_drugdeal": 20,
                  "mx_supplydrop": 10,
                  "mx_portal": 3,
                  "mx_minefield": 50,
                  "mx_crater": 10,
                  "mx_fumarole": 8,
                  "mx_portal_in": 1,
                  "mx_anomaly": 3
              }
```
with
```
          "field": {
              "chance": 1,
              "extras": {  
                  "mx_minefield": 50
              }
```
now all fields should have minefields. (didnt test it)
