### ISSUE TITLE
Suggestion: Sandwich recipes 

### ISSUE THREAD

**Issue by Epictyphlosion** [CleverRaven/Cataclysm-DDA#23291]
As I mentioned in #23287, we could use some sandwich recipes if they are not in the game already. Such as a bologna sandwich, with optional condiments, roast beef sandwich, and other kinds. What these recipients would do is provide something you can eat which has higher nutrition and enjoyability than the raw ingredients. Or the amount of nutrition and enjoyability of the raw ingredients, but with a boost of enjoyability. Because, let's face it, it's always better to at least put two slices of bread between meat rather than eat it with your bare hands

**Comment by Leland** [comment]
There are heaps of sandwiches in the game – check https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/comestibles.json to see how many.

**Comment by Epictyphlosion** [comment]
*Facepalms so hard my hand goes through the back of my forehead*
