### ISSUE TITLE
Pond city_distance problem

### ISSUE THREAD

**Issue by ZenZen2** [CleverRaven/Cataclysm-DDA#23303]
Game version: 0.C-26922-gd44e02a

Operating system: Win 7

Tiles or curses: Tiles

Mods active: default

### Expected behavior
overmap special Pond should spawn.

### Actual behavior
"Pond" doesnt spawn (default settings)
It has ``` "city_distance" : [-1, -1], ```
Changing it to ``` "city_distance" : [0, -1], ```
result in
![debug](https://user-images.githubusercontent.com/20055252/37949866-b61b7962-3196-11e8-9f8c-34ad769e47ba.jpg)
after SPACE game works and pond is spawning.
Whats the problem here? it should also spawn with ``` [-1, -1] ```
same with basin, didnt test others.

### Steps to reproduce the behavior
Start the game just with default mods and without changing anything in the settings. There will be no Ponds.
Change city distanze to ``` "city_distance" : [0, -1], ``` will result in DEBUG

**Comment by ZhilkinSerg** [comment]
[1,-1] seems to be working though

**Comment by ZenZen2** [comment]
Looks like pond, basin and bog need to be adjusted.
