### ISSUE TITLE
Change link from old to new forums

### ISSUE THREAD

**Issue by RustyPotato** [CleverRaven/Cataclysm-DDA#23305]
Hello all. 

I was wandering through Projects pages, and found a link to the old forums and was wondering who we should call upon in order to update it. 

Specifically, the Practice Makes Perfect project [here](https://github.com/CleverRaven/Cataclysm-DDA/projects) has a link to the old forums. [Here](https://discourse.cataclysmdda.org/t/practice-makes-perfect/3509) is a link to the new forums for the lazy.

**Comment by Leland** [comment]
Done, thanks
