### ISSUE TITLE
Hide or skip crafting submenus if no options available

### ISSUE THREAD

**Issue by Leland** [CleverRaven/Cataclysm-DDA#23314]
Game version:
b87c6d2

Minor UX thing: would be a nice simplification to hide or skip over crafting submenus if the user has no recipes in it yet.

<img width="543" alt="screen shot 2018-03-28 at 8 36 21 pm" src="https://user-images.githubusercontent.com/714017/38063575-daf71dc2-32c7-11e8-8f2f-4507de0ff105.png">

**Comment by mrkybe** [comment]
From a new player perspective, it definitely spoils some stuff.

From a game design perspective, it tells the player that there's something to strive towards, something they haven't found yet.

IIRC there was some study that found that having movies "spoiled" for you actually made people enjoy them more.  My opinion is that the game-design perspective wins out here.

**Comment by Leland** [comment]
Ah, that's interesting. I wasn't recommending this from a spoiler perspective.

My thinking is that having completely empty submenus just impedes a player from actually using the crafting interface: tabbing over to an empty submenu is a wasted movement. From a UX perspective, that's about as bad as it gets.

**Comment by kevingranade** [comment]
Style it to indicate it's unavailable and havevtabbing skip over it?

**Comment by mrkybe** [comment]
@kevingranade That sounds like the best of both worlds.  There's no reason for empty menus to be selectable anyway.

**Comment by PatrikStridvall** [comment]
I have made pull request #23333 that implements what @kevingranade suggested.
