### ISSUE TITLE
Getting weapon with FLAMING tag stuck in enemy should cause large amounts of damage

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#2331]
Was showing my brother the work I'd done on adding a flaming sword to the game (Shishkebab pull request), and he pointed out that currently, getting a weapon with FLAMING stuck in a target has no effect.  Up to now, this hasn't been an issue since very few items have FLAMING, and those that do (lit torches) have little to no chance of getting stuck in a target.  But, I think adding support for this in the code would be helpful, both for artifacts that spawn with FLAMING, and my own mod.  I don't really have the knowledge of coding to make a change like this, but I'm sure plenty of other people working on this game do.  By putting this issue up, I'm hoping someone will pick up the torch (so to speak) and add this in.  C'mon, help a newbie out please :)
##

**Comment by illi-kun** [comment]
We don't have stuck weapon anymore.
