### ISSUE TITLE
the world is a rift (prission break world breaking bug)

### ISSUE THREAD

**Issue by Eddyskingdom** [CleverRaven/Cataclysm-DDA#23341]
Game version: 7248

Operating system: windows 10

Tiles or curses: the standert tiles

Mods active: Dark Days Ahead, Filthy Clothing, Disaable NPC needs, extended Ralistic Guns,
Makeshift Itmes mod, Mtant NPCs, NPC traits, more Buildings, More Locations, Tall Buildings,
Urban Development, Boats, Folding Parts pack, Vehicle Additions Pack, Tanks and Other Vehicles,
EXTEND_BUILDINGS, Remove Nether Creatures, No Fungal Monsters, Classes and Scenarios Mod
Huge Vehicles, StatsThroughSkills.

### Expected behavior. I have playd on the same world with the same stats only what i did is reset the wolrd and removing wandering spawns. after that i made a new charactor in the Scenario Prission Break
and the only thing i gave him was strengt and th rest of the stats to 14. and what i expected to happen is that i will spawn in the world like normal in a prission cell with a NPC.

**Comment by Eddyskingdom** [comment]
![glitch of](https://user-images.githubusercontent.com/25956554/38172005-c3ed61d8-35a4-11e8-842d-fa5c8c40764f.png)

**Comment by Eddyskingdom** [comment]
i also have the world stat op spawn itmes on 5.00 and evoltions of mosnters on 50,00 and also Z-levels ON

**Comment by ZhilkinSerg** [comment]
What happens when you reset world and start again? Are you still spawning in lava rift instead of prison basement?

**Comment by Eddyskingdom** [comment]
i will reset it agian and see what happens

**Comment by Eddyskingdom** [comment]
seem like it went back to normal but why duze dis happen?

**Comment by ZhilkinSerg** [comment]
Lava rifts can be generated anywhere in the world including start locations.

**Comment by Eddyskingdom** [comment]
ok so just bad luck

**Comment by ZhilkinSerg** [comment]
Closing then.
