### ISSUE TITLE
Follower NPCs suffering Schizophrenic Hallucinations Affect PC

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#23346]
Game version: Experimental 7261

Operating system: Windows 7 64-bit

Tiles or curses: Tiles

Mods active: Default (Dark Days Ahead, Filthy Clothing, Disable NPC Needs, Simplified Nutrition)

### Expected behavior

Player's survivor (without Schizophrenia trait) should not see hallucinations or suffer from schizophrenia when a follower NPC with Schizophrenia trait is suffering from a schizophrenic break.

### Actual behavior

Player's survivor (without Schizophrenia trait) can see hallucinations and yell in sleep, as well as some other error (NPC name repeats several times), when a follower NPC with Schizophrenia trait is suffering from a schizophrenic break.

### Steps to reproduce the behavior

Make new character. Debug NPC. Debug NPC with Schizophrenia. Debug Mind Control NPC to be follower. Wait until NPC suffers schizophrenic break (testing seems to be between 2-3 days).

![schizonpc](https://user-images.githubusercontent.com/32253888/38177477-9e475f04-35bf-11e8-8701-74836de79cac.png)
![ohjesusschizoattack](https://user-images.githubusercontent.com/32253888/38177481-a9079e72-35bf-11e8-8363-e41c8f041c07.png)

**Comment by mrkybe** [comment]
Can confirm this happening.
