### ISSUE TITLE
Seg Fault on loading Main Menu 

### ISSUE THREAD

**Issue by Pere5troika** [CleverRaven/Cataclysm-DDA#23358]
Game version:
Cataclysm-0.C-7272

Operating system:
MacOS High Sierra 10.13.3

Tiles or curses:
Curses

Mods active:
None

### Expected behavior
Terminal UI Shows and allows uses of hotkeys to begin the game

### Actual behavior
UI loads but cannot be interacted with. 

### Steps to reproduce the behavior
Download, put in applications folder, run.

### Question:
I am running a zsh shell and i see some exports going on initially. Could this be related to this issue?

<img width="874" alt="screen shot 2018-04-03 at 11 31 24" src="https://user-images.githubusercontent.com/14174629/38259307-a8d98612-3732-11e8-991f-bd17ff7c5549.png">

**Comment by Leland** [comment]
Yeah, unfortunately our compilation process for macOS is broken right now. This is a duplicate of #23171.

I've posted a build I made over in that issue, you can find it here https://mega.nz/#!HRQywJ6a!Jr2sdG7YuGhQSZ6ITp6uSJz4VKvgrBYd8R4r6gRCcLA
