### ISSUE TITLE
Random event as property of tools/weapons

### ISSUE THREAD

**Issue by Heaper327** [CleverRaven/Cataclysm-DDA#23364]
### Expected behavior
Add events that are triggered with certain probability when tool/weapon is activated, such as overheat, leakage would add to the gameplay. Such events should be properties of the tool/weapon that are written in json like this:

```json
"event" : {
  "probability": 20,
  "effect" : {
    "type" : "explode",
    "radius" : 10,
    "power" : 5,
    "message" : "Your railgun short-circuited and explode!"
  }
}
```

This allows add/change random event by modding

**Comment by ZhilkinSerg** [comment]
All these event types should still be coded.

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
