### ISSUE TITLE
Old forum link and broken wiki on homepage

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23369]
The link on <http://en.cataclysmdda.com/> still points to the old forum at <http://smf.cataclysmdda.com/>.
And the wiki link is completely broken.

Please fix the links!

Also, “Portuguesa” should be “Portugues”.

Sorry if this is off-topic but I had no other idea where to complain.

BTW: It looks like the homepage has not seen any updates since ages. Why?

**Comment by kevingranade** [comment]
> It looks like the homepage has not seen any updates since ages. Why?

Because it's a weird custom rails site I don't know how to update, and the owner (GlyphGryph) is not interested in maintaining it.  The new site is cataclysmdda.org

**Comment by Wuzzy2** [comment]
Oh, there's a new homepage?
Can the old homepage be at least shutdown then? It's not good to have an outdated homepage floating around. :(
Or at least put a redirect there.

**Comment by kevingranade** [comment]
I'll see what I can do, redirect is possible.

**Comment by Leland** [comment]
Yup, as a guy that's done a fair share of SEO work, having duplicate URLs is a big issue.

The following subdomains should 301 to cataclysmdda.org:

- http://cataclysmdda.com/
- http://www.cataclysmdda.com/
- http://en.cataclysmdda.com/
- http://pt.cataclysmdda.com/
- http://ru.cataclysmdda.com/
- http://es.cataclysmdda.com/
- http://pl.cataclysmdda.com/
- http://cn.cataclysmdda.com/
- http://fr.cataclysmdda.com/
- http://kr.cataclysmdda.com/

**Comment by Wuzzy2** [comment]
cataclysmdda.com and all its subdomains are now dead (no server). This means the issue can be closed.
