### ISSUE TITLE
It's possible to cook food even with no fire in the oven

### ISSUE THREAD

**Issue by ZNolife** [CleverRaven/Cataclysm-DDA#23377]
Game version: 0c-26918-g031d25c

Operating system: Windows 10 64 bits in French

Tiles or curses: Tiles

Mods active: No acid Z / No explosive Z / classes and scenario mod / statsthoughskill IV / simplified nutrition / filthy closing

### Expected behavior  :

 Not being able to cook food like bread and mc & cheese if there is nothing burning in the oven

### Actual behavior : 

There is nothing burning in the oven but I can cook pretty much everything : I have to say that there is nothing BURNING but I've thrown lots of books in the oven in order to later start a fire but was surprise to see that even without starting the fire I could cook as if I had started one. Also I must say that I did start one several days ago but I don't see the flames anymore but I wonder if a bug wouldn't keep the fire alive but invisible.

### Steps to reproduce the behavior : 
- Get a oven from a nearby house (I also built a cheminee... may be it's the fact to hav both in the same room which create the bug I don't know)
- Create a fire in it and cook some stuff
- Let it die (I've waited several hours before trying again but it's probably the same if I haven't)
- Now try to cook again something which needs heating to be cooked, like bread, and you'll see you can even if the fire in the oven in not here anymore

**Comment by KongMD-Steam** [comment]
I can't reproduce this on Build 7285 with the steps you outlined. Maybe it was a field that stuck around too long, and will go away after reloading your save.

**Comment by BevapDin** [comment]
> Game version: Latest (installed 1 week ago)

Well, if you installed it "1 week ago", it's probably not the latest anymore. Come on, the game version is shown directly in the title screen that appears when you start the game. You don't have to go in some arcane menu or similar, just copy the few characters after "Version: " from there.

**Comment by ZNolife** [comment]
Oh my bad I thought this game was not changing too often.
My version is : 0c-26918-g031d25c

**Comment by l29ah** [comment]
I cannot reproduce it on b3f9612a3a179c30cec87061f1ea810d8ce01db2; are you sure you have the "nearby fire" requirement satisfied (and not some mess kit lying nearby)?

**Comment by ZNolife** [comment]
I'm afraid I can't check that but consider it ok and I'll re-open it if the issue occurs in a futur game.
