### ISSUE TITLE
lab journal-Gustav has no recipies

### ISSUE THREAD

**Issue by Lum4r** [CleverRaven/Cataclysm-DDA#23371]
Game version:
Experimental build 7277

Operating system:
Win 7

Tiles or curses:
Tiles

Mods active:
dda
no_npc_food
novitamins
makeshift
Medieval_Stuff
More_Survival_Tools
crazy_cataclysm
mutant_npcs
npc_traits
boats
deoxymod
blazemod
no_reviving_zombies

### Expected behavior
Recipies

### Actual behavior
No recipies

### Steps to reproduce the behavior
1. Start new game
2. Wish for "lab journal-Gustav"
3. Read it

There are no recipies. In fact, all of the diamond equipment made using the CVD machine seems to be missing from the JSONs.

**Comment by illi-kun** [comment]
The way of obtaining of diamond weapons was modified here: #18627.
So yes, it seems that Gustav journal is now useless.

**Comment by smolbird** [comment]
Is it obtainable in normal gameplay?

**Comment by Lum4r** [comment]
I found one that has naturally spawned in a lab that also contained a CVD machine.

I wasn't clear on the changes to diamond recipies, and finding the depricated lab journal didn't clear much up for me :p

**Comment by BorkBorkGoesTheCode** [comment]
What about moving it to blazemod and adding blazemod's diamond gun recipes to it?

**Comment by Night-Pryanik** [comment]
As stated by Kevin in this https://github.com/CleverRaven/Cataclysm-DDA/pull/28267#issuecomment-465875353, there's nothing wrong with journal with no recipes.
