### ISSUE TITLE
Breaching charges

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#23380]
Idea for explosives use, craft breaching charge item and apply it to a wall.  If applied correctly it would demolish a section of wall and only have a small explosive effect in the other direction.
I think the primary use would be for rapid entry or exit from a building, but probably not mid-combat since it would take a minute or so to apply properly.

**Comment by DegenerateGroundState** [comment]
Smaller and easier to use breaching charges are often used on door hardware.

**Comment by thethunderhawk** [comment]
Very cool. Would be good to put in SWAT vans.
