### ISSUE TITLE
Evac shelter computer: “Contact Us” menu looks like the game is freezing, and other issues

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23396]
Game version:
ae5bdc036830b3c950337526d0870ec45489bd7d

Operating system:
GNU/Linux

Tiles or curses:
curses

Mods active:
Just the default stuff

### Summary
This is about the “Contact Us” menu in the evac shelter computer.

While the game tries to trace the way to the refugee center, it freezes, sometimes very long. There is NOT indication on the screen what is happening. I have Ctrl+C-ed out of the game multiple times because I was convinced the game froze :-(

There are other issues:

* The final sentence in the displayed is not completed, the address name is not written. The name of the city should be included, don't you think?
* The “Reach Refugee Center” mission does not have a mission text.
* The search for a road can sometimes take absurdly long. I hear my CPU spin up! Can you try to make it faster?

Suggestions to fix this:

* When the map starts loading, show in the computer console “Downloading map data, please wait …” or something similar. If it is done, write “Done!”.
* Come up with a fake facilty name which includes the city name to finish the final sentence, also display the coordinates

### Steps to reproduce the behaviour
Start a default game, go to evac shelter computer, use contact option.

Pretend you didn't see this feature before. Get confused why none of the controls work and Ctrl+C in your pretend desparation. xD

**Comment by codemime** [comment]
> The search for a road can sometimes take absurdly long. I hear my CPU spin up! Can you try to make it faster?

This is not solely searching for a road that takes so absurdly long. Primarily, the delay happens because of generating an overmap containing the said road. The refugee center can be several overmaps away. Which means several overmaps have to be generated before the resulting path could be acquired. This takes time. I don't see a clear way of dramatically reducing its amount, except for steadily placing the refugee center nearer.

> Suggestions to fix this:

I like both. Also, the mission text that you've mentioned would be nice to have.

**Comment by Wuzzy2** [comment]
The bigger problem than the long load time is the lack of any UI response during this time. If you can't lower the load time, fix the UI first.

**Comment by Inglonias** [comment]
I'm not noticing nearly as much freezing now, and I didn't even notice the evac center placements were relaxed.

I don't know if that counts as a real fix for the issue, but it certainly does mitigate it. Is that enough to call this "closed" for 0.D? I dunno. It's not up to me. But this issue has been mitigated.

**Comment by kevingranade** [comment]
If we don't see an obvious fix, that will probably be sufficient.

**Comment by mlangsdorf** [comment]
@Wuzzy2 can we close this issue?
