### ISSUE TITLE
Error from loading S&W 619

### ISSUE THREAD

**Issue by Epictyphlosion** [CleverRaven/Cataclysm-DDA#23398]
Game version: Latest experimental, 0.C.7286

Operating system: Windows 7

### Mod:
Extended Realistic Guns

### Expected behavior
World will load normally 

### Actual behavior
Error comes up when verifying items, something along the lines of: "Magazine ammo is not specified"

### Steps to reproduce the behavior
Load or create a world like normal, and the error will appear upon verifying the items

**Comment by illi-kun** [comment]
I've updated the report to state that ```Extended Realistic Guns``` mod should be enabled to see the debug message.

@gbmaster, thanks for the note about that.

**Comment by illi-kun** [comment]
![msg](https://user-images.githubusercontent.com/5421954/38453587-9f910f72-3a60-11e8-9b2b-6a2e3721d6f5.PNG)

**Comment by BorkBorkGoesTheCode** [comment]
Sending a fix now.

**Comment by ChronicDankDisasterAlgorithm** [comment]
I also am getting this same exact error when loading my game. I am using these mods : Mining Mod, More Survival Tools, StatsThroughSkills, Vehicle Additions Pack, Tanks and Other Vehicles, Boats, Folding Parts Pack, Necromancy, Disable NPC Needs, Extended Realistic Guns

Not sure if my comment even helps, but figured it couldn't hurt.

**Comment by illi-kun** [comment]
Closed by #23445.
