### ISSUE TITLE
Tutorial redesign

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23395]
The tutorial is pretty old and sadly also kinda broken. But I also think it has various design flaws.

I propose a complete redesign from scratch of the tutorial. Here are my ideas:

## Technical basics

* Tutorial is played in a special world with the special name “TUTORIAL”
* If you select Tutorial again in the main menu with a “TUTORIAL” savegame already present, ask the player if he/she want to load the saved tutorial, or start over.
* Map generation: Minimalistic. Just field everywhere with the tutorial buildings in the center
* Disable monster spawns, hunger, thirst, tiredness, weather and other dynamic events which would mess with the tutorial. Instead, trigger those by special events
* If player dies, respawn player and remove monsters
* Don't hide the tutorial in a strange menu called “Special”. Give it its own button
* If running the game the first time ever, maybe ask the player to play tutorial?

### Overview
The idea of the lesson is to teach enough of the controls so the player can play. The tutorial should be mostly focused on the getting the controls right. The idea is to answer all questions of the type, “what do I have to press to do XYZ?”.
Thankfully, the item action menu allows it to access and see all possible actions with ease.
Also, basic concepts such as crafting should be shown explicitly.
Very advanced stuff such as mutations or CBMs might be left off entirely.

Tutorial should also be seen as a supplement to the basic in-game help.

Personal side node: The current help and tutorial isn't TOO bad. I used the old tutorial myself to learn the game. I was able to learn the game in a decent way, the only point in which I was completely stumped by the game vehicle usage/repair.

### The house and lesson plan

The player spawns in a tutorial house, a fixed structure.

The tutorial should teach the player enough to understand the basic concepts and controls. It should NOT be required to expose all the things you could do, but it's important for the player what he/she must press to do XYZ (XYZ = attack, repair vehicle, build something, craft, etc.).

I initially made a floor and plan here: http://smf.cataclysmdda.com/index.php?topic=6238.0

I repeat the lesson plan here:

> * basic controls: The student starts here. In this room the most important controls are taught there: Movement, pausing, opening and closing doors, examining, looking around, quitting the game. This room has one door which leads to the lobby and one stairway leading to the “lightning and darkness” room. This is the most important room and must be designed with care, since the rest of the tutorial bases on the lesson taught here. It is suggested that the player visits the “item basics” room next.
> * lobby: This room simply connects most of the other rooms.
> * item basics: Basic item facts are taught here. This includes:: picking up, dropping, examining, inventory, comparing, item list (“V” key), weight, volume. This room contains some example items to play around with. This room also contains shallow water and containers for liquid and teaches how to refill and unload them.
> * obstacles: Contains more walls, fences, wooden doors, metal doors, windows and furniture. Teaches movement cost, movement speed, the little number to the right bottom of the sidebar, smashing, moving furniture, cleaning up windows.
> * books and skills: Has basic books for learning and books for enjoyment, explains their purpose. Teaches how to increase skills (by books and by training).
> * tools: Has some basic tools which can be activated. Also explains more item concepts: reloading, unloading, activating, charges. Has at least flashlight and a lighter.
> * clothing and encumbrance: Contains clothing and at least one backpack. Teaches how to wear and take off clothing. Teaches encumbrance from clothing and from carrying too much. Mentions the clothing sorting menu. Briefly mentions and shows one example of special clothing (i.e. waterproof). Most of this can be carried over from the existing tutorial.
> * construction: This area is outdoors and contains some pre-built furniture and some building materials and tools neccessary to build some example constructions. It is taught how to build stuff in general, and specifically how to deconstruct things.
> * vehicle construction: This outdoor area contains tools and materials to build vehicles. Some vehicle chassis spawn here as well. It is taught how to start a vehicle construction from scratch, how to repair parts and how to take off parts. It is also briefly mentioned which components are neccessar to make a vehicle run.
> * vehicle usage and grabbing: This outdoor areas has some ready-to-drive vehicles, at least one car and one bike. It is taught how to drive, to toggle light, how to use the speedo meter, how to leave a vehicle and how to refuel a vehicle. This area has some gas pumps.
> * crafting: Has many items. Teaches the student how to craft. Teaches how tools and crafting components are used. Shows: Crafting menu, repeat last crafting. This room also has a fireplace. The student is taught here how to start a fire safely, because fire is an important part in many crafting recipes.
> * melee weapons: Has some basic bashing and cutting weapons. Teaches wielding. Teaches how to wield nothing again. Teaches how to wield nothing again. Explains the difference between bashing and cutting damage.
> * ranged weapons: Contains throwable items, some basic throwable explosives (eg. grenades), and some basic firearms and at least one bow. Explains ammo, ammo types, reloading and unloading. Briefly mentions that reloading and unloading are not limited to weapons only. It took me quite some time to figure that out. ;-)
> * shooting gallery: Has some targets to test ranged combat.
> * arena. Some zombies spawn here, to teach combat. Many of existing tutorial texts can be carried over here. The doors are made of steel and the student is warned when entering the arena. The arena may contain some smashable obstacles.
> * first aid: full of bandages and first aid kits. Mainly there to recover from battles in the arena. Briefly explains how to use them and maybe to cure bleedings and infections.
> * tips: The student is taught there other stuff here which isn’t taught in the other areas. Mainly this will just mention misc. controls: morale, message log, help menu, advanced inventory, …. Other places where to seek further help are mentioned here. No gameplay tips, however! This place is really just for stuff which doesn’t fit anywhere else, mostly theoretical stuff.
> * lightning and darkness (basement): Basically just to have something where the stairs of the basic controls room lead to. Maybe use the same behaviour as in the original tutorial. A flashlight can be obtained from the tools room. Maybe there is one interesting item lying around here, but that’s about it.
> * swimming: contains a swimming pool and some basic swimming gear. Teaches how weight can influence the ability to swim and why the student may sink like a rock.
> * traps: How to set traps, how to step in a trap, how to dismantle a trap. Room contains some example traps, placed and unplaced.

But to simplify this, maybe the tutorial could be divided in two parts.

Part 1: Basics. This includes stuff you frequently need to be able to play at all:
* Movement
* How to leave and where to find the help
* Examine
* Examine and use items
* Activate items, use containers and other common item actions
* The action menu (IMO it's too undearappreciated now. It's incredibly useful to learn all the available actions and keybindings!)
* Clothing
* Melee combat
* Ranged combat
* Crafting

Part 2 should cover everything else.

But I no longer think this floorplan I have drawn neccessarily a good idea. There are too many branches, I now think the tutorial must be more linear, at least at the beginning. There MIGHT be branches for the more advanced stuff (such as repairing vehicles), but this should be used sparingly.

The design of the first rooms is the most important so the player knows how to get around and examine the world.

## Messaging

This is important to get right. Current tutorial's messaging system is completely wrong because critical messages disappear forever. Player must be able to re-read everything, especially at the beginning.

My idea is to use terminals to store most tutorial texts, so they can be re-read at any time.

The only exception should be the beginning of the tutorial. Here a few initial windows are still needed to show the movement and examine controls.

## Notes

This design is not final. It's just a rough outine. Feel free to make suggestions.

**Comment by illi-kun** [comment]
Previous discussion about this topic is available here: #17984.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/new-player-feedback-tutorial-and-help/26424/3

**Comment by anothersimulacrum** [comment]
With the improvements in #50991, I don't feel like it's worth keeping around an issue describing another plan for improvement.
