### ISSUE TITLE
The mod load order, after changing it, is not correctly loaded

### ISSUE THREAD

**Issue by gbmaster** [CleverRaven/Cataclysm-DDA#23390]
Game version:
Experimental built on Apr, 1, 2018

Operating system:
Any

Tiles or curses:
Any

Mods active:
Default

### Expected behavior
The mod load order, when a new default is saved, must be kept

### Actual behavior
After closing the application and reopening it, the mod load order is not the same as when I saved it (although in user-default-mods.json the dependencies array is correct)

### Steps to reproduce the behavior
Store a new default mod load order, close the game, start it again check what's the mod load order

**Comment by kevingranade** [comment]
What does this break? 
If mods have dependencies on each other they should be explicit, not based on ordering in a mod list.

**Comment by gbmaster** [comment]
Yes, @kevingranade, you're actually right. The problem for me was that I was receiving an error during the character creation and I thought it was related to this (total mistake). Instead, I was experiencing the bug already described in #23398.

Selecting the "Extended Realistic Guns" mod is enough to trigger the error message during the character creation. I guess we can close this ticket as a dup of #23398.
