### ISSUE TITLE
Simple flamethrower has no craftable magazine

### ISSUE THREAD

**Issue by ZemZamano** [CleverRaven/Cataclysm-DDA#23392]
Game version:
newest
Operating system:
win
Tiles or curses:
both
Mods active:
only standard ones
### Expected behavior
a crude homemade simple flamethrower should have a craftable magazine
### Actual behavior
the magazine spawns only in rarely
### Steps to reproduce the behavior
-

**Comment by ymber** [comment]
The simple flamethrower is a spray can modified to use liquid fuel and allow for refilling and repressurizing it. It should be handled like internal magazine weapons.

**Comment by Wulfe813** [comment]
@ymber 
The simple flamethrower is assembled with a pipe, some hose, a pilot light and some bottles. The recipe is perhaps too simple, but a jury-rigged device like that would likely involve hand pumped pressurization.

The flamethrower you're referring to is the spraycan flamethrower.

**Comment by ymber** [comment]
I cant imagine how you would assemble a working flamethrower from just that, but I think the containers are being used to create a fuel tank attached to the weapon that you refill and manually repressurize. The recipe isn't viable and it needs redoing, especially if the design is meant to take detachable fuel tanks.
