### ISSUE TITLE
Most turrets and bots have "small" size.

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#23408]
Currently  most turrets and bots have small size.
For example:

"id": "mon_laserturret",
"description": "The TX-5LR Cerberus is an upgrade to its predecessors.  It features a state of the art revolving **laser cannon system with three barrels** that charge from solar cells embedded in its hull.",
 **"size": "SMALL",**

"id": "mon_secubot",
"description": "The Northrop Watchman X-1 is a production series of **heavily armored combat robots**.  Initially designed for military patrol and escort service, it rolls on a set of hydraulic treads and is armed with a 9x19mm SMG.",
 **"size": "SMALL",**

Isn't it oversight? Based on its descriptions  that things things should quite bulky. It is not a zombie child size.

There is also balance question.
In fact turrents and bots are usual shooting enemies. At hthe same time marking them small make them hard to hit with ranged weapons. Is it intentional?

**Comment by kevingranade** [comment]
Yes, this is intentional.
