### ISSUE TITLE
#22747 rendered tank guns unusuable, other manual guns no longer manual

### ISSUE THREAD

**Issue by smolbird** [CleverRaven/Cataclysm-DDA#23420]
Game version:
0.C-27251-gef69f3b

Operating system:
Windows 10

Tiles or curses:
Curses (used for quicker testing of latest available version)

Mods active:
  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "blazemod",
  "Tanks",
  "More_Survival_Tools"

### Expected behavior
* Manually firing a tank's main gun is possible, as original behavior.
* Using `e`xamine on a tank's main gun allows reloading or unloading it.
* The mounted M240 and M2 Browning act as manual-only weapons, as before.

### Actual behavior
* Attempting to hit `f` while unarmed fails to accomplish anything.
* Trying to `e`xamine the main gun skips to showing vehicle menu, cargo contents of seat/tile, etc.
* The M240 and M2 Browning can be configured to fire as unmanned weapons.

### Steps to reproduce the behavior
1. Debug in a main battle tank.
2. Attempt to load and/or fire the main gun.

### Additional Information
The mounted M240 and M2 Browning are still functional, but *no longer* behave as though manual. why these are broken in one way yet the tank weapons are broken in another is utterly baffling to me.

Pinging @Night-Pryanik due to this being their concern.

**Comment by ZhilkinSerg** [comment]
Would you please elaborate on M240 and M2?

Firing mode can be changed by `s` key both before and after change:

![default](https://user-images.githubusercontent.com/16213433/38470971-3c10df72-3b73-11e8-9c28-e474428754b3.png)

**Comment by smolbird** [comment]
As in, being able to order them to fire from the vehicle controls menu despite intended use of the `MANUAL` flag. If that predates the PR then it's a separate older bug, but it does bear mentioning for the sake of deciphering the cause.

**Comment by ZhilkinSerg** [comment]
So, I guess `"copy_from"` is not working in mods.

**Comment by ZhilkinSerg** [comment]
> Tested, nothing different.

Yes, it seems there is one more file required - please also unzip attached file to folder `\data\mods\Tanks\parts.json` replacing original file.

[parts.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1887945/parts.zip)

**Comment by smolbird** [comment]
Oh right. Doh.

**Comment by smolbird** [comment]
Tested, it seems to work.
