### ISSUE TITLE
Better display of 'extra' encumbrance 

### ISSUE THREAD

**Issue by DoctorVanGogh** [CleverRaven/Cataclysm-DDA#23425]
You can have additional encumbrance due to use of multiple items in the same 'layer' per part.

The game does a piss poor job of explaining _where exactly_ this extra encumbrance comes from.
There is the `[..]+123` part in the armor layering window per body part, but you're left to poke around on your own to find out _which items exactly_ cause the conflicts.

So... I think this can accommodate some improvement :grin:

Since not everybody is playing in 4K I think using additional screen space is questionable. I've put together a prototype of 85% of what I think could be a usefull solution.

Instead of a plain

![image](https://user-images.githubusercontent.com/324067/38473250-42dfd730-3b8d-11e8-9163-922ea61a3b9b.png)

it colorizes each armor pieces Storage or Encumbrance values to indicate which layer it belongs to. 

![image](https://user-images.githubusercontent.com/324067/38473275-9144055e-3b8d-11e8-8592-06882b9de0c8.png)

Multiple items with the same color per body part are a problem.

What I have no fricken clue how to do (and what would make this 100% functional in my mind) is how to calculate the additional encumbrance penalty by layer, so we could get something like

![image](https://user-images.githubusercontent.com/324067/38473400-cce3cc14-3b8f-11e8-890a-8a882d467592.png)
[Completely mocked those numbers in]

A quick glance at `character.cpp` and it's `encumbrance` related functions show no obvious way of getting those values (apart from duplicating some code in there, but I'm a firm believer in DRY so - not going to start here).

---

I've put up a prototype at https://github.com/DoctorVanGogh/Cataclysm-DDA/commit/dcf9c3a7326d4574343e2ed1721e779b8070024a

What's missing is the per layer calculated and colorized penalties to be inserted [here](https://github.com/DoctorVanGogh/Cataclysm-DDA/blob/colorize-armor-layers/src/armor_layers.cpp#L420).

Obviously the [colors picked](https://github.com/DoctorVanGogh/Cataclysm-DDA/blob/colorize-armor-layers/src/armor_layers.cpp#L80-L98) are completely arbitrary (though I think it'd be a good idea to **not** use colors from the 'health' spectrum). Also - maybe the whole coloring stick deserves to be moved as a member function to `item.h/.cpp` similar to [`item::damage_color()`](https://github.com/DoctorVanGogh/Cataclysm-DDA/blob/colorize-armor-layers/src/item.cpp#L3347-L3371).

Maybe coloring the **background** of the armor item lines would work better?

Also... My C++ is ... not up to par. I'm sure I've forgotten or added a `const`too much somewhere in there..

**Comment by AMurkin** [comment]
Or make it real table with columns, column names. With a scrollbar when not enough width.

**Comment by DoctorVanGogh** [comment]
Good point about the color... I guess we could use a symbol character for each item like everywhere else, but make it a symbol per layer here (and still color _that_ icon). That's like two extra characters needed in the left & right columns... which work fine for _every other_ UI (Eat/activate/...).

I think I'll actually try to implement this. Took another look at the encumbrance code and I think I understand what's going on (though some things seem just _weird_ - need to watch this with a debugger to verify if I got the logic right).

**Comment by DoctorVanGogh** [comment]
Okay, I went ahead and started fiddling around with this. I think I need some feedback on my current approach to a sub-problem:

Basically I've split this up mentally to:
- [ ] Infrastructure
  - [ ] Define colors & symbols per clothing layer
    - [x] create definition
     https://github.com/DoctorVanGogh/Cataclysm-DDA/commit/843e28a3d0268985724dc09f4e385ea8de97290b
    - [ ] add parser for json (see flags.h/.cpp)
  - [ ] Add layer encumbrance information to aggregation routines
  character.cpp,  `layer_item(...)`, L 1492
- [ ] Update UI
    - [ ] Top panel:
    Colorize active body part like category (see mockup)
    - [ ] Left panel:
      - [ ] add colored layer symbols to list
      - [ ] make list look like other menus
      - [ ] use item health symbols instead of color for item status (since line highlight hides color)
    - [ ] Middle panel
      - [ ] reuse item description
        - [ ] **filter item description to relevant parts**
        https://github.com/DoctorVanGogh/Cataclysm-DDA/commit/fd879adb15571e7d2e6d3d9f5c7789f4abb9e9c2
    - [ ] Right panel
      - [ ] colorize body parts like categories
      - [ ] add colored layer symbols to list
      - [ ] add extra emcumbrance per layer to category header lines

---

I'm looking for some dev feedback on the **highlighted** item. There is already code in the game which displays an item's properties, description, etc, and that code does it _well_(*): 

- `item.info` 
https://github.com/CleverRaven/Cataclysm-DDA/blob/9ba31d9e82f81ec13445889489ff957c1dff5709/src/item.h#L372-L383
- `draw_item_info`
https://github.com/CleverRaven/Cataclysm-DDA/blob/9ba31d9e82f81ec13445889489ff957c1dff5709/src/output.cpp#L748-L756

My problem here is the fact that the panel needs **way, way** less than the full output, actually only a small subset.
I'd still like things to be in the exact same format as in other places, because familiarity in UI design is a good thing. To that end I've written a tiny filter which strips the item's info down to the `ARMOR` & `DESCRIPTION` blocks, but this is *still* too much.

https://github.com/DoctorVanGogh/Cataclysm-DDA/blob/fd879adb15571e7d2e6d3d9f5c7789f4abb9e9c2/src/armor_layers.cpp#L25-L43

results in

![image](https://user-images.githubusercontent.com/324067/38789475-ba3bfd38-413a-11e8-86bd-f8c5872c425f.png)

which is too much. _I've marked the parts which I think are superfluous._

To allow querying _subsets_ of item information I've added an extra overload to `item.info`
https://github.com/DoctorVanGogh/Cataclysm-DDA/blob/fd879adb15571e7d2e6d3d9f5c7789f4abb9e9c2/src/item.h#L393-L404
```c++
enum iteminfo_parts {
    TEXT = 0,
    
    // element count tracker
    NUM_VALUES = 1
};
...

std::string info(const std::bitset<iteminfo_parts::NUM_VALUES> &parts, std::vector<iteminfo> &dump, int batch) const;
```
it currently replaces the 'showtext' logic with a test against the bitfield. Plan is to expand the bitfield to allow a much more granular support of which elements to return.

My question now comes down to:
- Is this a tenable design? Does this conflict with other pieces of code?
- If this approach works, redirect existing call via overloads or rather refactor the callers (where possible)?

**Comment by OzoneH3** [comment]
>Does this conflict with other pieces of code?

The only thing the "blocks" (BASE, ARMOR, etc) are used for is the compare feature ```format_item_info()``` which compares based on ```iteminfo.sType and iteminfo.sName```.

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
