### ISSUE TITLE
Show more precise survival time on death

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23435]
Game version: 0.C and later

### Introduction

Surviving the first day is a major milestone for new players. Players will naturally need a lot of tries to manage to do that for the first time.

When you die, your gravestone shows the number of days you survived, but it will just stay at a 0 for a long time, obviously. :-)

### Suggestion

I suggest to make this number more precise by also adding hours. :-)

### Rationale

A more precise number gives the player a sense of progress, especially when you die a lot. Days are just too coarse IMO.

**Comment by illi-kun** [comment]
We can show minutes in case of staying alive less than an hour, hours in case of staying alive less than a day, etc.

No significant difference between 123 days and 3 hrs vs. 123 days 1 hr, but 0 days and 3 hrs vs 0 days and 1hr definetely makes sense.

**Comment by Wuzzy2** [comment]
> No significant difference between 123 days and 3 hrs vs. 123 days 1 hr, but 0 days and 3 hrs vs 0 days and 1hr definetely makes sense.

I don't think many players make it that far. :D

**Comment by EchoingZen** [comment]
If I got two characters who happened to make it to 123 days, I'd be highly curious as to which one lived longer.  I say show the complete time, hours and minutes when you die. After all, it's the last you'll see them.

**Comment by Shoes01** [comment]
Are these deaths logged anywhere? If so, the time could be logged in full detail, while using the conventions listed above for the tombstone.
