### ISSUE TITLE
Screen is not cleaned properly when choosing multiple martial arts in char creation

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23432]
Game version: ae5bdc036830b3c950337526d0870ec45489bd7d

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: Default

### Expected behavior
If you create a character with multiple martial arts-giving traits, there are no visual glitches.

### Actual behavior
If you create a character with multiple martial arts-giving traits, there are visual glitches. Namely, the windows and Y/N questions which query you for martial arts styles will not get cleared properly, leading to ugly overlays.

### Steps to reproduce the behavior
* Create new character
* Freeform mode
* Select all martial arts traits which allow you to select martial arts. Or just select all positive traits :D
* Finalize
* Select all those martial arts styles

**Comment by Leland** [comment]
Can you add screenshots of the visual glitches to your issue description?

**Comment by illi-kun** [comment]
@Wuzzy2 Are you talking about this?

![capture](https://user-images.githubusercontent.com/5421954/38512112-feea971c-3c32-11e8-8094-132ce79b8af2.PNG)

**Comment by Wuzzy2** [comment]
Yes.
