### ISSUE TITLE
Game doesn't let me copy text

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23438]
Game version: ae5bdc036830b3c950337526d0870ec45489bd7d

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: Doesn't matter.

### Expected behavior
My console lets me copy text like every other console program does.

### Actual behavior
It doesn't. This is annoying if I get an error message. I have to type in the exact error message by hand, I can't just copy it into the issue description. :-(

I kinda get why C:DDA prevents selections (because they may look ugly), but at least it should let me copy critical error messages, don't you think? :-)

### Steps to reproduce the behavior
* Run C:DDA in console
* Try to select or copy anything in console to copy some text
* Fail and cry

**Comment by BevapDin** [comment]
This seems to be a ncurses/xterm thing. A quick search yields [this](https://invisible-island.net/ncurses/ncurses.faq.html#xterm_paste), using the shift key (as hinted there) works just fine.

**Comment by Wuzzy2** [comment]
Indeed. Thank you!
