### ISSUE TITLE
Crash after taking gun from vehicle: “attempt to copy-construct an iterator from a singular iterator”

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23449]
Game version: 45b804c42012a3b4c30bfc6771ab6f5540044ae2

GCC version: 7.3.1

Operating system: GNU/Linux

Tiles or curses: Tiles

Mods active: Dark Days Ahead, Filthy Clothing, Disable NPC Needs, Simplified Food

### Crash report

I played a game. Then I got into a fight with 2 mi-gos. I went to my shopping cart to take a gun.
C:DDA crashed.
I believe the crash happened when I tried to take the gun, but I'm not 100% sure. It just happened somehow in that fight. Also, I got this odd console output:

```
$ ./cataclysm-tiles 
/usr/include/c++/7.3.1/debug/safe_iterator.h:149:
Error: attempt to copy-construct an iterator from a singular iterator.

Objects involved in the operation:
    iterator "this" @ 0x0x55cdd18cdff8 {
      type = __gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<item>, std::__debug::list<item, std::allocator<item> > > (mutable iterator);
      state = singular;
    }
    iterator "other" @ 0x0x55cde124b738 {
      type = __gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<item>, std::__debug::list<item, std::allocator<item> > > (mutable iterator);
      state = singular;
      references sequence with type 'std::__debug::list<item, std::allocator<item> >' @ 0x0x55cde3ad9b90
    }
Abgebrochen (Speicherabzug geschrieben)
```

### Steps to reproduce
Unknown. :sob:

**Comment by Leland** [comment]
Closing – unfortunately, there's typically not much to go off of without a means to reliably reproduce.

**Comment by mlangsdorf** [comment]
Duplicated in #25934 which has a better reproducer.
