### ISSUE TITLE
Roots should work with certain items on the feet slot

### ISSUE THREAD

**Issue by MarsM0nd** [CleverRaven/Cataclysm-DDA#23442]
Currently, if you do have anything on your feet, even if it is two ankle sheaths, for example, roots don't get to dig themselves into the ground. It should be considered to change it that you only get the roots blocked if the footwear is either not mutation friendly, or at least not mutation attack friendly, so lacking "OVERSIZE" or "ALLOWS_NATURAL_ATTACKS", or both.

**Comment by Leland** [comment]
Perhaps allow roots through `BELTED` feet items?
