### ISSUE TITLE
Makefile writes “astyle not found”

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23443]
Game version: 45b804c42012a3b4c30bfc6771ab6f5540044ae2

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: N/A

### Summary
If I `make` the game (from a clean repo, no params), at the top I see this:
```
/bin/sh: astyle: Command not found.
```

Not critical, but still a (fixabe?) warning.

**Comment by Leland** [comment]
Just means you don't have astyle installed. Get it installed and the warning should disappear. If you hit issues the [forum](https://discourse.cataclysmdda.org/) or [Discord](https://discordapp.com/invite/DPxUcX7) would be good places to ask for support with your specific system.
