### ISSUE TITLE
Final entry in mutations list is not updated properly if list uses full screen height

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23452]
Game version: 45b804c42012a3b4c30bfc6771ab6f5540044ae2

Operating system: GNU/Linux

Tiles or curses: BOTH

Mods active: Default

### Expected behavior
Mutations list doesn't screw up when using full height and you're scrolling down.

### Actual behavior
Mutations list screws up when using full height and you're scrolling down.

If the list of mutations is so long that the full screen height is used, the final entry at the bottom screws up when you scroll. It is not updated properly.

### Steps to reproduce the behavior
* Have tons of mutations (add them with debug menu if you have to)
* Scroll mutations list down
* Watch last entry at bottom

**Comment by Leland** [comment]
What does "It is not updated properly" mean, exactly? Can you provide screenshots?

Can't reproduce on tiles.
![screen recording 2018-04-10 at 11 24 pm](https://user-images.githubusercontent.com/714017/38594838-5178f544-3d16-11e8-8c06-620a7d16b5c3.gif)

Will note that this was touched recently by #23275.

**Comment by Wuzzy2** [comment]
Apparently the bug only happens if the window is NOT having the default height, it must be larger. Try again.

“Is not updated proprly means” that the lowest visible entry stays the same no matter where you scroll.

Example: If the lowest visible entry is “Mycus” and you scroll down, it stays “Mycus” while you scroll. In other words, the scrolling fails completely here.

**Comment by Leland** [comment]
Looks ok!

<img width="1072" alt="screen shot 2018-04-11 at 7 59 53 pm" src="https://user-images.githubusercontent.com/714017/38649154-fbbc017a-3dc2-11e8-9169-c25b6d6784bc.png">

**Comment by Wuzzy2** [comment]
You don't get it …

Look at this image:
https://lut.im/WzxAs4w5EJ/78uPF7GNbn65bfYw.png

Now I scroll down by 1:
https://lut.im/3ilGFAyYdK/YYxfOLPYEqhrfXuI.png

And another one:
https://lut.im/gjRzuwJNCb/hZMkNuFukMFswKeN.png
