### ISSUE TITLE
Text color scheme in Tiles version is hard on the eyes

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23457]
Game version: 0.C and later

Operating system: GNU/Linux

Tiles or curses: Tiles

Mods active: N/A

### Summary

So, I think the current color scheme of the text in the Tiles version is just ugly. The color contrast is quite bad and the darker colors are hard on the eyes.

This makes it quite hard to look at the map because the dark colors are too dark. Just looking on the map makes me feel sick. These ugly colors are the main reason why I still prefer to play curses version from time to time.

Please fix the colors so they easier on the eyes. This means make the dark colors brighter and tweak the contrast.

IMPORTANT: This has NOTHING to do with the color manager. This is just useful to shuffle existing colors around, you can't change RGB values. I mean the *actual* RGB color of the text, aka the palette.

**Comment by OzoneH3** [comment]
Sounds like this is what you want #19814

```config/base_color.json```

**Comment by Leland** [comment]
Where do those default color values live? I'll get some slightly less aggressive colors in a PR.

**Comment by OzoneH3** [comment]
```data/raw/colors.json``` is the base color file.

**Comment by Wuzzy2** [comment]
Do you agree that the color palette needs fixing?

**Comment by Leland** [comment]
The default color palette could be better, sure. But you can fix your own game's colors to your heart's content in `config/base_color.json`

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
