### ISSUE TITLE
Can read newspapers, flyers, etc. from afar

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23451]
Game version: 0.C

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: Default

### Expected behavior
To read the text on newspapers, flyers, snippets, etc., you have to obtain them.

### Actual behavior
If you use the examine (`e`) or lookaround mode (`V`, `;` or `X` key) to list items around you, you can reveal the written text on newspapers, flyers, text snippts, etc. without actually needing to picking them up, even if you're a very large distance away. All you need to do is to look at the item description.

This is a little silly in my opinion. ;-)
I know most of this is just flavor text but IMO there should be an inventive to actually walk towards the newspaper, not just scan them with `V`.

### Steps to reproduce the behavior
* Find a survivor's note
* Go away from it
* Press `V` and select the survivor's note
* See the text although you're far away

### Suggestion
Hide the text of newspapers, flyers, snippets, etc. if these items are not in your inventory.

Show a dummy text for newspapers, etc. if viewed from `e`xamine or lookaround mode. Something like “This is a newspaper. To read its contents, pick it up first.”.

**Comment by Leland** [comment]
Meh. This is minor enough that if you want to open a PR for it, go ahead, but it's probably not worth keeping an issue around. Newspapers, flyers, and snippets are all flavor text.

**Comment by Wuzzy2** [comment]
:-(

But yeah, I get why it's low priority to you. Note that it's not entirely flavor text as some snippets contain useful hints.
