### ISSUE TITLE
Boots don't have the "OUTER" flag

### ISSUE THREAD

**Issue by Nicals** [CleverRaven/Cataclysm-DDA#23459]
Game version: 0.C-27165-gdf81c49

Operating system: Linux

Tiles or curses: Both

Mods active: Core

### Expected behavior

Boots are usually worn on top of other piece of clothes.
In the [/data/json/items/armor/boots.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/aa8ebe047e294f0c3d2025076e378e08a621636c/data/json/items/armor/boots.json), all boots here do not have the "OUTER" flag.

### Actual behavior

Waring a pair of knee-high boots with some breeches produces excessive encumbrance:
![boots behaviour](https://i.imgur.com/0oUKeU4.png)

Those kind of boots also cover the legs, so it is expected that a character could whear some underlayer and some pants inside those boots.

### Steps to reproduce the behavior

Wear some boots defined in [/data/json/items/armor/boots.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/aa8ebe047e294f0c3d2025076e378e08a621636c/data/json/items/armor/boots.json).

### Comments

I'm just starting picking into the data and code of this project.
I'm not sure if the fact that boots are not defined as "OUTER" is intentional or not.

I think that all boots that cover the legs should have this flag.

If this is confirmed as an issue, I can submit a pull request.

**Comment by smolbird** [comment]
Breeches are a peculiar example. They came from a mod @chaosvolt made (source: https://github.com/CleverRaven/Cataclysm-DDA/pull/21084 only PR mentioning breeches) where they were evidently UNDER items, to avoid this exact issue.

This was vetoed despite it making perfect sense that breeches would fit in either the normal layer or the under layer.

**Comment by Androwski3000** [comment]
There are a few seldom appliances for the outer layer. As the strapped appears to be empty, thoose items could be placed there also. Some examples at the bottom.

The more time I put into thinking about the layers, the more I think that there should be two "Normal" layers. NORMAL INNER and NORMAL OUTER.
As you can´t wear a pullover or sweater and an armor vest without encumberance penalty.
While chainmail armor or SWAT armor are at the normal layer alot of the other armors are on OUTER or the kevlar west is on the SKIN layer which means vests are a mess of themselfes.
With NORMAL INNER and NORMAL OUTER this could be solved.
You could also wear pants with hifgh boots then, where the boots and the pants on the legs are not competing for a layer regarding encumberance penalty.

Theese are like:
-gaiters and
[https://www.google.de/search?q=gaiters&source=lnms&tbm=isch&sa=X&ved=0ahUKEwix5KvcqYjdAhWFb1AKHaVzDf0Q_AUICygC&biw=867&bih=723](url)

-overshoes.
`https://www.google.de/search?q=overshoe&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj84KH_qIjdAhWCKlAKHU7ZADEQ_AUICygC&biw=867&bih=723&dpr=1.25`
[https://www.bw-online-shop.com/bundeswehr-ueberschuhe-gummi-original-gebraucht.html](url)
