### ISSUE TITLE
Map has duplicate icons

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23453]
Game version: 45b804c42012a3b4c30bfc6771ab6f5540044ae2

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: N/A

### Summary
The map icons have become a little messy now.

The map now has identical icons for different things.

* Bakery vs Electronics store
* Post office vs clothing store
* Radio tower vs radio station (ok, shouldn't matter much)
* Bookstore vs furniture store
* Pizza vs fast food
* (probably more, I didn't check everything)

This is annoying because if you see any such ambibious icons on the map, you have to move the cursor there first. Ideally, each tile has its own icon. Very different buildings like bakery and electronics store should never share icons.

END OF ISSUE.

---

THIS IS INVALID, IGNORE:

Then the map now uses blinking icons for some tiles, like megastore entrance or food-courts:

* Megastore entrance, food-court, etc.
* Small storage units
* Dojo
* …

I'm not really happy with that. I find those blinking icons to be irritating and annoying. I don't think this is actually neccessary. IMO no map tiles should blink at all, blinking should be reserved for overlays only. There's no way you used up all possible combinations of letters, colors, background color AND bold/non-bold. ;-)
-)

**Comment by Night-Pryanik** [comment]
> the map now has identical icons for different things.

Sooner or later we'll run out of letters (though we still can use non-letter symbols).

**Comment by ZhilkinSerg** [comment]
> Can't repro at all, have never seen this

This, I believe: https://github.com/CleverRaven/Cataclysm-DDA/issues/22393#issuecomment-35231066

**Comment by BevapDin** [comment]
The blinking might be a feature of your terminal. Please go into the color manager (`Esc` -> `5`) and look at all colors to see if any of them blink there. If they blink there, it is caused by your terminal.

**Comment by Wuzzy2** [comment]
> The blinking might be a feature of your terminal.


Yes, this is indeed the case. Yeah, then it's clearly not a C:DDA, fault. Okay, I remove the “blinking icons” part from the issue.

This issue is no only about the duplicate icons.

> Sooner or later we'll run out of letters (though we still can use non-letter symbols).

I pretty much doubt it. Each letter can have a different color and you can also invert this color. Then as you said, symbols are also available.
With 12 colors and 52 letters (lower and uppercase), there are 52·12·12=6864 possible combinations. If you use all printable ASCII characters as well, the number rises to 96·12·12=13824.

I don't know how many symbols are used already, but my guess it's that's somewhere around 100-200.
