### ISSUE TITLE
Overhaul skeletons to be more in line with the remainder of zombie types

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#23463]
### Expected behaviour
Zombie types resemble each other.
### Actual behaviour
Skeletons are basically fantasy skeletons with a scifi-flavored paint-job.
### Steps to reproduce the behaviour
Look at the mon_skeleton definition.

Skeletons have several qualities:
Bony, HARDTOSHOOT, slashing-based attacks.
Let's keep those, but adjust the description and properties to bring them in line with how we understand the blob to work.

### Description ###
Instead of having no or minimal flesh, have the bones move to an exoskeleton.
In particular, the ribcage fuses into a carapace, organs move into the ribcage, and limb bones enlarge to protect muscles.  Meanwhile muscles become smaller (no free lunch), so they get slower overall.

### Stats ###
Armor goes up, speed goes down, slashing attacks stay the same (hands are replaced with bone spikes?), and HARDTOSHOOT is redefined as "makes creature count as one size smaller for the purpose of shooting" instead of a flat 50% miss chance.

This keeps most of the existing properties of the skeleton, makes them fit in the game world better, and opens a path to making a exoskeleton-based evolution path.  i.e somewhat bony just gives talons and some armor, skeleton has a full carapace, then the size and thickness increase until you have a Skeletal Juggernaut that's 8' tall with 3" thick bone plates covering it.

**Comment by Mecares** [comment]
I  aleays imagined them as something like these:
https://magiccards.info/tp/de/5.html

**Comment by ymber** [comment]
Sounds good. Skeletons with plate armor would be a good reason to choose bashing damage early game and slowing them down makes them more interesting than the status quo of running away until you find a shotgun.

Why would it keep HARDTOSHOOT with this redesign? Growing an exoskeleton wouldn't make it any smaller and it doesn't have gaps in it any more.

**Comment by smolbird** [comment]
> basically fantasy skeletons

I do believe there is a trope for this: http://tvtropes.org/pmwiki/pmwiki.php/Main/MisaimedRealism

**Comment by kevingranade** [comment]
HARDTOSHOOT is justified by the overall body shape of the enemy becoming more streamlined, the limbs become spindly and the torso is all drawn up into the ribcage.

**Comment by FulcrumA** [comment]
Would be good to also change the name of the creature if it's not meant to be just a fantasy skeleton anymore.
