### ISSUE TITLE
Stuck Monomolecular Blade

### ISSUE THREAD

**Issue by chaoticidealism** [CleverRaven/Cataclysm-DDA#23476]
Game version:0.C-27351-g1c706dc

Operating system:Win7

Tiles or curses:Tiles, but using ASCII graphics

Mods active: Filthy clothing, disable NPC needs, simplified nutrition, generic guns, more survival tools, makeshift items, mining, cataclysm++, stats through skills, extra professions, classes and scenarios

### Expected behavior
When a monomolecular blade bionic is uninstalled while it's activated, you can no longer wield the blade. Maybe the blade drops as an item; maybe it just disappears.

### Actual behavior
My Monomolecular Blade bionic is drawn--but in the bionic menu, it's marked "OFF". Whenever I try to withdraw or activate the blade, I get text that says, "You activate your Monomolecular Blade./Deactivate your Monomolecular Blade first." The effect is that I'm stuck holding this blade, which makes a great weapon, sure, but I can't use ranged weapons at all because I can't hold them.

I think it was caused when a botched bionic installation destroyed the monomolecular blade bionic while I had the blade drawn. I spawned in another bionic and installed it, hoping I'd be able to deactivate the blade and uninstall the bionic properly, but no dice. I can't drop it, can't unwield it, can't wield anything else.

### Steps to reproduce the behavior
Install monomolecular blade bionic, activate it, and then botch a bionic installation that destroys the monomolecular blade bionic. I do not know if this also happens with a regular uninstall.

**Comment by SolsticeTheTechMarine** [comment]
![image](https://user-images.githubusercontent.com/38237593/38765659-ef3fc6de-3f7a-11e8-8ac6-47641b91abbf.png)
![image](https://user-images.githubusercontent.com/38237593/38765670-0ae6f0d8-3f7b-11e8-99f3-f121c2e7ddb1.png)
Confirmed.

**Comment by ZhilkinSerg** [comment]
I guess we should destroy items created through bionics when corresponding bionics is destroyed.

**Comment by chaoticidealism** [comment]
Can be fixed using the debug menu--edit yourself to force yourself to wield something else from your inventory, then drop that item.

**Comment by Rivet-the-Zombie** [comment]
A simple `if` query could fix this issue, enabling the bionic to activate if its specific pseudo-item is already in the player's 'hands' slot.

**Comment by ZhilkinSerg** [comment]
> A simple if query could fix this issue, enabling the bionic to activate if its specific pseudo-item is already in the player's 'hands' slot.

You won't be able to hold other items in your hands though, until you install new MMB bionic.

**Comment by Rivet-the-Zombie** [comment]
Good point!

**Comment by Night-Pryanik** [comment]
Fixed by #23582.
