### ISSUE TITLE
Blazemod racks are unreloadable

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [CleverRaven/Cataclysm-DDA#23479]
Game version: 0.C 7305

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Blazemod

### Expected behavior: 
Refill the rack as you would a tank, but with ammunition.

### Actual behavior: 
Incapable of refilling the rack.

### Steps to reproduce the behavior: 
1: Make sure you have the appropriate ammo.
![image](https://user-images.githubusercontent.com/38237593/38764883-2895c4ba-3f6c-11e8-825d-bfcea17621b0.png)
2: Examine a vehicle with a rack.
![image](https://user-images.githubusercontent.com/38237593/38764893-592f488a-3f6c-11e8-941d-82d903bb4176.png)
3: Attempt to refill rack with relevant ammo and fail because it won't highlight.
![image](https://user-images.githubusercontent.com/38237593/38764896-7899dbfe-3f6c-11e8-94f2-219fe8d1f442.png)

**Comment by tyrael93** [comment]
Did it work before? I remember turrets being super buggy in blazemod.

**Comment by SolsticeTheTechMarine** [comment]
From what I have read it did until some update where tanks no longer took specific fuels.

**Comment by mlangsdorf** [comment]
Blazemod ammo racks were obsoleted in #24394 and replaced with adequate ammo sizes. Was that an adequate fix for this issue?

**Comment by DracoGriffin** [comment]
Should be resolved with #24394.

If this is not the case @SolsticeTheTechMarine, please leave a comment here so that it may be re-opened.
