### ISSUE TITLE
Translating faction names is awkward

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23473]
Game version: 1c706dcd242154ba753c8fbeab06931199b0f3ae

Operating system: N/A

Tiles or curses: both

Mods active: N/A

### Problem
Translating the names of factions is pretty awkward and hard in my opinion. Maybe even impossible.

From how I understand this feature, a part of faction name generation involves simply concatenatng a bunch of random syllables. I don't think this is right. This may work just fine in English. But the problem is you can't just translate random English syllables into other languages.
I find myself unable to come up with any sensible translation for those syllables in the German translation and I wanna bet other translators have similar problems.

I think the algorithm which generates faction names is flawed as soon you take translations into account and needs to be replaced.

Any ideas for improvement?

### Some ideas

Here are some simple examples for simple faction names:

1) Pick pre-defined name from a list
2) Similar to artifact name generation (`<adjective> <noun>`), based on words and format strings, e.g. “Raging Scavengers”. Grammar might still be tricky here
3) Simple constructions of the form `<random name or noun> of <city>`, e.g. “Cult of Paris”
4) More ideas welcome!

### Debug?

There there's also apparently any lack of debugging options for now to just randomly generate some factions, so it would be nice to have that, too.

**Comment by kevingranade** [comment]
I'm ok with any of your suggested naming schemes, or simply disabling faction generation until it actually does something.

**Comment by kevingranade** [comment]
This is an essentially unimplemented feature, so translations for it don't matter.  In the maybe near future we will have explicitly defined factions with explicit names.
