### ISSUE TITLE
Mission called “Find 2 55-Gallon Drums”, but no item has this name

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23472]
Game version: 1c706dcd242154ba753c8fbeab06931199b0f3ae

Operating system: GNU/Linux

Tiles or curses: both

Mods active: Default

### The problem

There's a mission with the name “Find 2 55-Gallon Drums”, but there isn't any item in the game with this name.

**Comment by Leland** [comment]
Change happened in #16959. Really just means the mission needs to be changed to `Find 2 steel drums (200L)`. You can see the issue in the current item here:

https://github.com/CleverRaven/Cataclysm-DDA/blob/148a6dec3a77c6b25ea6950581195b7ea62c8a54/data/json/items/containers.json#L66-L83

**Comment by Wuzzy2** [comment]
Ah, that explains it. :+1:

**Comment by Shoes01** [comment]
Would there be a way to link the name of the quest to the name of the item? And if so, would there be a way to create a pool of items that could be used as "fetch quest" items? 

Taking it further, it would be neat for the NPC to have an endgame goal for the quest. As you bring back items, you can see whatever is being built taking shape. Maybe it's a car, maybe a cozy shack.

**Comment by smolbird** [comment]
That seems kinda weird to name the drum in metric when it's supposed to be an explicitly non-metric volume. Like how gallon jugs are explicitly gallon jugs, not 3.79-liter jugs.

**Comment by illi-kun** [comment]
@Shoes01 at first I liked your idea, but then I realized that would be another pain for translators. It's easier to work with entire phrase, with consistent context.

**Comment by Wuzzy2** [comment]
As a translator for German, I fully agree with illi-kun.

**Comment by illi-kun** [comment]
Yeah, I thought exactly about you, Wuzzy  :smile:
