### ISSUE TITLE
Throwing penalty string in player menu is too long

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23487]
Game version: ae5bdc0

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: Default

### The problem
The string for throwing penalty in the Dexteriy trait shown in the player menu is way too long to be readable.

### How to reproduce
1. Open player menu with @
2. Select Dexterity and notice the problem here. The string for throwing penalty is too verbose, even in English

**Comment by Night-Pryanik** [comment]
We can also move all the bonuses described in `STATS` window to the info screen just below, either adding information about bonuses to the description or replacing the description with explicit bonuses info.

**Comment by gastamper** [comment]
Your idea is much better, additionally since nothing actively prints new information outside the info window *except* the stats window, so this additionally adds some standardization to the whole process.  New PR will be done in a few minutes.

**Comment by illi-kun** [comment]
Closed by #23492.
