### ISSUE TITLE
Map screen: Map tile description might overlap with distance to target w/ mission running

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23484]
Game version: ae5bdc0

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: Default

### Expected behavior
This is about the map screen.

No matter how long a map tile description is, there's no overlap between strings.

### Actual behavior
If the map tile description (e.g. “Forest in the North of Some City With An Absurdly Long Name”) requires more than 2 lines and you have a mission with a position goal running, the mission text is replacing the 3rd line of the map tile description.

### Steps to reproduce the behavior
* Spawn new default world w/ scenario Evacuee
* Start the Reach Refugee Center mission in your evav shelter
* Look at map and highlight various map tiles
* Look at the map tile description and “Distance to target”

If the full map tile desciption takes more than 2 lines, there's a overlap.

Easier to reproduce in verbose languages.

**Comment by Wuzzy2** [comment]
Still not fixed in `0.C-37564-g412ee858b5`.

Screenshots:

![2 screenshots demonstrating the bug](https://ptpb.pw/WWLg.png)

The screenshots show the upper left corner in the map screen.
The town's name is “South Portland”. In both cases, you can see a part of the description is overwritten by the “Distance to target: ” thing, which seems to appear always on the third line.


Possible fix: Make sure the “Distance to target” moves dynamically and is always below the location description rather than fixing its position.

**Comment by Wuzzy2** [comment]
Oops. I mean “upper right corner”.

**Comment by Night-Pryanik** [comment]
Closed by #28452.
