### ISSUE TITLE
Cannot drill reinforced glass with a jackhammer

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#23493]
Huh?

**Comment by nexusmrsep** [comment]
Is it confirmed?

**Comment by Theundyingcode** [comment]
tested all the walls types I could place with mapediter in: 0.C-33637-ga697734 (tiles) 8081 (2 days ago)

Could jackhammer through everything except glass wall and the rebar cage left from jackhammering the concrete wall(s)
