### ISSUE TITLE
Starting a character and then cancelling a suicide leaves log window artifacts

### ISSUE THREAD

**Issue by gastamper** [CleverRaven/Cataclysm-DDA#23496]
Game version: 0.C-27388-g5485036-dirty 

Operating system: Ubuntu

Tiles or curses: curses

Mods active: None

### Expected behavior
Log window should be cleared/rewritten even if it is unpopulated.
### Actual behavior
Log window is not rewritten until further input is received:
![log screen issue](https://user-images.githubusercontent.com/20960555/38778809-08aa66fc-408d-11e8-957a-b7680bf07c15.PNG)
### Steps to reproduce the behavior
Start a new character, hit CTRL-C, hit N.

**Comment by illi-kun** [comment]
It's weird but I can't reproduce this on in Windows and Linux builds.

@gastamper could you double check that current version of the game is affected?

**Comment by gastamper** [comment]
Just did a merge and rebuild:
#define VERSION "0.C-27472-gdbf2beb"
... still occurs.  

Also confirmed that it occurs on non-new characters (load an existing character, CTRL-C, N, same thing).
![capture](https://user-images.githubusercontent.com/20960555/39072153-96337ec2-44b7-11e8-9581-c75a19bd8f6d.PNG)

The two screenshots are from separate terminals as well (first one from PuTTY on my desktop, second 'native' from within the VM), both showing the issue.
