### ISSUE TITLE
Ahl pikes have food cooking quality of 1

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23514]
Game version: a98c6b1827773cd0d5a122924da9dae551ca54cb

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: Default

### Bug report

The ahl pike (a weapon item) has a food cooking quality of 1.  :rofl:

**Comment by Leland** [comment]
Not a bug.

The premise is that you can ostensibly skewer things on it and safely cook over a fire

Knife spear
https://github.com/CleverRaven/Cataclysm-DDA/blob/a98c6b1827773cd0d5a122924da9dae551ca54cb/data/json/items/tools.json#L6626

Bayonet
https://github.com/CleverRaven/Cataclysm-DDA/blob/a98c6b1827773cd0d5a122924da9dae551ca54cb/data/json/items/tools.json#L6865
