### ISSUE TITLE
(r)eload uses action point despite whether it is successful or not

### ISSUE THREAD

**Issue by Heaper327** [CleverRaven/Cataclysm-DDA#23516]
Game version:

0.C-27601

Operating system:

Mac OSX 10.12.6

Tiles or curses:

Tiles

Mods active:

None

### Expected behavior

Press reload button doesn't uses action point when there is no ammo available or you canceled reloading

### Actual behavior

Press reload button while wielding a reloadable item always takes action point even if there is no ammo available or reloading is canceled

### Steps to reproduce the behavior

wield a gun with two matching clips in your inventory
stand near a zombie
press reload and cancels reload when you are asked to choose which clip to reload
see the zombie walk up to you

**Comment by Night-Pryanik** [comment]
Any chance #28245 fixed this?
