### ISSUE TITLE
Newspaper pages/flyers create several, random stacks

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23528]
Game version: 0.C-27399-ga98c6b1

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutgens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Dropping multiple "newspaper page" or "flyer" items creates a stack for each type of page depending on its content.

### Actual behavior
Several stacks of items are created, each has several different pages (still stacked, but by dropping them one by one, different articles are shown when the page is examined).

### Steps to reproduce the behavior
Gather bunch of flyers/newspaper pages, drop them in one place

**Comment by BevapDin** [comment]
This is the same as with cash cards. Those items differ and as such they should not stack. Stacked items can not be accessed independently.

This is like #20148, only inverted. There the user complains that items that are not identical (made from different things) do not stack.

----

@all We need to find an exact definition on how to decide whether two items should stack.

**Comment by kevingranade** [comment]
I believe the real failing here is that deduplication is being handled at the inventory level instead of at the UI level.
Stacking should only occur if items are identical in every way, but various menus would be free to consolidate item entries further for display.
