### ISSUE TITLE
Scrambled eggs recipe (regular and deluxe) requires water

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23527]
Game version: 0.C-27399-ga98c6b1

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutgens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
You can craft (cook) scrambled eggs just by having a source of heat, a cooking utensil able to contain eggs like a frying pan and eggs, the way you can easily do so IRL

### Actual behavior
Both deluxe scrambled eggs (regular scrambed eggs + meat) and 'scrambled eggs' require water for crafting.

### Steps to reproduce the behavior
Attempt to craft 'scrambled eggs'.

**Comment by BorkBorkGoesTheCode** [comment]
The water is for the powdered eggs. The recipe looks like it was originally two recipes combined into one to decrease clutter.

Also you don't need to post a text file to share JSON changes; you can post changes with posts using the insert code button:

```

{
  "type" : "recipe",
  "result": "scrambled_eggs",
  "category": "CC_FOOD",
  "subcategory": "CSC_FOOD_OTHER",
  "skill_used": "cooking",
  "difficulty": 1,
  "time": 6000,
  "autolearn": true,
  "qualities":[
    {"id":"COOK","level":2}
  ], "tools": [ [ [ "surface_heat", 2, "LIST" ] ] ],
  "components": [
    [
      [ "powder_eggs", 10 ],
      [ "egg_bird", 2 ],
      [ "egg_reptile", 2 ]
    ]
  ]
},

```
