### ISSUE TITLE
Tinder can be cut into pieces of wood

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23525]
Game version: 0.C-27399-ga98c6b1

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutgens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Tinder cannot be cut through 'B'utchering menu

### Actual behavior
Tinder can be 'B'utchered into pieces of splintered wood

### Steps to reproduce the behavior
'B'utcher tinder

**Comment by Oh-Petya** [comment]
I'm taking a look at this, are we sure this is not intended? 'B'utcher isn't only reserved for butchering corpses, but also to disassemble items on the ground.

For example, if there are sheets on the ground and you 'B'utcher them, it allows you to cut them up.

**Comment by kevingranade** [comment]
This is working as intended, though with the scope creep of 'B'utcher the name has become somewhat confusing.  
When used in the context of items, it disassembles the item forcefully without using the "correct" tools, and the results include broken pieces and not as many intact pieces.

**Comment by FulcrumA** [comment]
It IS a question of design though, not the fact that the action is called "butchering". Tinder is finely cut or otherwise loose material that can be easily set alight. It also functions in such a way in game, being created from various rags, pieces of wood etc. 

Somehow, the butchering action allows one to turn such tinder, through presumably cutting it even finer, into whole pieces of wood. So, opposite of cutting, you somehow glue the tinder into pieces of wood through butchering. The fact that you very well may be performing some magical transmutation at that aside (if you made tinder from rags and then were able to put together those cut apart rags into pieces of wood, something is afoot).

**Comment by 0Petya** [comment]
Yeah, after looking up some pictures of tinder, I am inclined to agree with @FulcrumA here. Tinder seems to be extremely fine, and even straw-like. I think it goes against reason to be able to cut it into splintered wood.

**Comment by ZhilkinSerg** [comment]
> This is working as intended, though with the scope creep of 'B'utcher the name has become somewhat confusing.
When used in the context of items, it disassembles the item forcefully without using the "correct" tools, and the results include broken pieces and not as many intact pieces.

Is `salvage` more correct verb now?

**Comment by FulcrumA** [comment]
If we are to be pedantic name of the feature itself about it, I'd recommend 'disassembly' as 'salvage' often includes taking item whole for the sake of fixing it up and/or repurposing. But I think that's a whole different issue altogether from what I wanted to report and personally, I don't really mind 'butchering'.

**Comment by 0Petya** [comment]
Yeah I think that's a separate issue, and if that's something we want addressed (I agree), we should open up another issue for it.
