### ISSUE TITLE
Thermometers have to be activated

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23529]
Game version: 0.C-27399-ga98c6b1

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutgens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Thermometers show temperature on player's HUD the way diving watch does, as long as the player is near the thermometer or has it in the inventory

### Actual behavior
Thermometers, despite using no power, have to be activated to display the temperature every time the player wants to know what the current temperature is.

### Steps to reproduce the behavior
Get a thermometer

**Comment by Shoes01** [comment]
This item was likely added at the same time as other weather related items, like the barometer, so those items might have the same problem. Although I don't expect pressure to be shown on the UI..
