### ISSUE TITLE
Foraging prevented by items

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23532]
Game version: 0.C-27399-ga98c6b1

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutgens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Upon 'e'xamining underbrush, when one is asked whether they'd like to search it through popup, answering 'Y'es should search the underbrush and then show other items lying in the place for potential pickup

### Actual behavior
Upon answering 'Y'es to the popup, searching is not performed straight away but the 'e'xamination window with the items on the tile is shown. Picking those items prevents foraging. They have to be ignored for foraging to be performed.

### Steps to reproduce the behavior
Search underbrush tile with some item on it.

**Comment by l29ah** [comment]
Couldn't reproduce, 0.D-5829-g4a400484d3-dirty

**Comment by Night-Pryanik** [comment]
Yeah, couldn't reproduce it too.
