### ISSUE TITLE
Unable to choose the tank when siphoning fuel

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23533]
Game version: 0.C-27399-ga98c6b1

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutgens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Upon attempting to siphon the fuel from a vehicle possessing multiple fuel tanks, player chooses which tank they want to siphon the fuel from.

### Actual behavior
Siphoning automatically chooses first available tank

### Steps to reproduce the behavior
Attempt to siphon fuel from a vehicle with several fueled tanks.

**Comment by narc0tiq** [comment]
Looks like this one just got fixed by #25348.

Siphoning from a Fire Truck (2 tanks, both with gasoline), I just got asked which tank to siphon from:
![image](https://user-images.githubusercontent.com/591573/45031235-f6daa380-b056-11e8-9c31-5159eaac4f42.png)

Please reopen if needed!
