### ISSUE TITLE
Drinking your own blood is considered cannibalism and disasterous for morale

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23538]
Game version: 0.C-27430-ge5d2149

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutgens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Drinking one's own blood or blood of willing donor as weird as it may be doesn't lead to any particular issues (provided there are no contaminants and the liquid itself is relatively fresh).

### Actual behavior
Game doesn't track the origin of the blood, even drinking a bit of your own blood is treated as devouring corpse of some person, up to and including causing fear of afterlife punishment in spiritual character.

### Steps to reproduce the behavior
Use blood draw kit on yourself, drink acquired blood.

**Comment by YakumoChen** [comment]
drinking your own blood would be really, really kind of gross, it makes sense it's morale disastrous.

**Comment by smolbird** [comment]
> (and even then, not many of them - I can only think of Jehovah's Witnesses and Church of Christ)

This does mean that the effect of "drink blood with Spiritual but without Cannibal or Psychopath" is still valid. The Spiritual trait is currently generic.

**Comment by FulcrumA** [comment]
Not really a problem there. It should be a low priority since it doesn't really disrupt the game greatly but it is some sort of flaw/issue so I bring it here on the basis of principle.
