### ISSUE TITLE
NPCs teleporting when changing Z-level into cramped space

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23530]
Game version: 0.C-27399-ga98c6b1

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutgens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Upon entering location that has not enough place to contain both player and player's followers, followers that cannot find some free space (spot they can stand at, no matter if webbed, with items etc) for themselves stay on the previous Z-level.

### Actual behavior
NPCs that cannot be spawned next to the player get teleported into nearby free space, even if it's in the next room, behind wall or closed doors.

### Steps to reproduce the behavior
Walk up/down stairs with several NPC companions.

**Comment by FulcrumA** [comment]
Can be tested/confirmed by finding a house with spider-infested basement and entering it with 3+ NPCs in tow (remember they have to stand by the player character as said character descends) . Some of them will forced to appear outside initial 2x2 room characters descend to.

**Comment by kevingranade** [comment]
Only an issue if z-levels are disabled.

**Comment by FulcrumA** [comment]
It has to be mentioned that experimental z-levels are disabled by default as experimental, however, so it is an issue stemming from how "normally" things work.

**Comment by Theundyingcode** [comment]
Not entirely sure if it's the same but, in a recent game w/ z-levels on, zombies following me into my basement wouldn't appear at the stairs but would constantly appear at another spot in the basement.

**Comment by Night-Pryanik** [comment]
Z-levels are now always enabled, so this should no longer be an issue.
