### ISSUE TITLE
If player is pushed/thrown off a ledge, player doesn't fall

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23537]
Game version: a98c6b1827773cd0d5a122924da9dae551ca54cb

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: Dark Days Ahead, Filthy Clothing, Disable NPC Needs, Simplified Nutrition

### Expected behavior
If a throwing monster (e.g. zombie brute) throws you far and you end up in mid-air, you fall.

### Actual behavior
If a throwing monster throws you far and you end up in mid-air, you do not fall until you move. You just float and can wait forever on the spot.

### Steps to reproduce the behavior
* Step on a higher level of a building (e.g. mansion)
* Go close to the ledge
* Spawn a zombie brute
* Let it attack and throw you far
* Wait a few turns

**Comment by kevingranade** [comment]
Should be a simple matter of calling the right check after being flung, either explicitly or by arranging to have it happen at an appropriate point in the game loop.
