### ISSUE TITLE
Subway corners and horizontal straight courses spawn misaligned occasionally

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#23547]
Game version:
0-c-27466
Operating system:
windows 10
Tiles or curses:
tiles
### Expected behavior
Subway tunnels are always aligned.
### Actual behavior
Subway corners occasionally spawn rotated 90 degrees misaligned. Straight courses spawn misaligned every few maps. Horizontal courses are affected.
### Steps to reproduce the behavior
Create a new world in the affected experimental and walk in a subway tunnel.

![screenshot 1054](https://user-images.githubusercontent.com/18560216/39029397-32a3f22e-4421-11e8-9300-9d8f049fb1b0.png)

![screenshot 1056](https://user-images.githubusercontent.com/18560216/39029453-7d7c2532-4421-11e8-987e-460a39e37167.png)

**Comment by ZhilkinSerg** [comment]
This is due to overmap terrains in `subway_tunnels.json` which are placed occasionally, but not being rotated.

Should be fixed in #23069.
