### ISSUE TITLE
Items dropped using "'D'rop to adjacent tile" and the arrow keys are randomly placed one tile clockwise

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#23542]
Game version:
0.C-27430
OS:
Windows 10 tiles
### Expected behavior
Objects are dropped onto an adjacent square of the player's choice whenever the player drops items using the "Drop" command.
### Actual behavior
Items are randomly dropped one square clockwise from the chosen drop tile when the player selects a tile using the arrow keys. The chance of this happening increases if the player quickly types the commands.
### Steps to reproduce the behavior
Drop an item using the "'D'rop item to adjacent tile" command using the arrow keys as quickly as possible.

**Comment by Mecares** [comment]
Might be connected to the change that enabled diagonal movement using shift+arrow keys.

**Comment by ZhilkinSerg** [comment]
Can you please disable option `Diagonal movement with cursor keys and modifiers` in options menu and play without it?

Will you still have same issue when dropping items?

**Comment by BorkBorkGoesTheCode** [comment]
Disabling diagonal movement setting stops the issue.

**Comment by BevapDin** [comment]
> Drop an item using the "'D'rop item to adjacent tile" command using the arrow keys as quickly as possible.

If you do this *as quickly as possible*, it's very likely that you still hold the shift key down (which is probably required to enter the uppercase 'D'). And that means the game receives (rightfully!) an input of SHIFT+direction key.

Please change the "drop item to adjacent tile" to be some key that does *not* require the shift key to be hold down (and enable "Diagonal movement with cursor keys and modifiers" again) and test again.

If the problem does not persist, or can be recreated by other, the issue will be closed.

**Comment by BorkBorkGoesTheCode** [comment]
Reassigning the drop key to lowercase d makes the issue stop.
