### ISSUE TITLE
fire, its not behaving. no reason for PITS catching on fire!

### ISSUE THREAD

**Issue by deanec64** [CleverRaven/Cataclysm-DDA#23545]
Game version: 0.C-27458-g42c278c

Operating system: windows 10

Tiles or curses: tiles

Mods active: [
  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "craftgp",
  "brightnights",
  "AAA",
  "bio_mod",
  "FIC_Weapons",
  "realguns",
  "generic_guns",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "alt_map_key",
  "crazy_cataclysm",
  "mutant_npcs",
  "npc_traits",
  "national_guard_camp",
  "Experimental-Z-Level",
  "trailerpark",
  "Urban_Development",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "necromancy",
  "battle_maid",
  "rf_food_keeper",
  "greaper",
  "hokuto",
  "Make_a_Lot_of_Items_Mod",
  "add_mutant",
  "tekitoumap",
  "Two_handoguns",
  "Useful_Goods",
  "windoor",
  "mori",
  "vorpal_weapons",
  "ATM",
  "more_classes_scenarios",
  "RL_Classes",
  "no_reviving_zombies",
  "StatsThroughSkillsFour",
  "StatsThroughKills"
]

### Expected behavior 
Fire NOT spreading to adjacent PIT tiles.

### Actual behavior 
Fire spreads no matter what.

### Steps to reproduce the behavior 
Start fire in a shallow pit.

**Comment by smolbird** [comment]
Deep pits and fire rings (More Survival Tools) contain fire. Shallow pits don't.

**Comment by kevingranade** [comment]
Yea, this is working as intended, the shallow pit is just a little depression in the ground.
