### ISSUE TITLE
Error when make macOS app with LANGUAGES ("lang/mo" folder not found)

### ISSUE THREAD

**Issue by akirashirosawa** [CleverRaven/Cataclysm-DDA#23551]
Game version:
last (1780644)
Operating system:
macOS 10.13
Tiles or curses:
tiles
Mods active:
none
### Expected behavior
Success compile and create app for MacOS with ru language.
In particular, copy` lang/mo/*` to `Cataclysm.app/Contents/Resources/lang/mo/`
### Actual behavior
```
...
mkdir -p Cataclysm.app/Contents/Resources/lang/mo/
cp -pR lang/mo/* Cataclysm.app/Contents/Resources/lang/mo/
cp: lang/mo/*: No such file or directory
make: *** [app] Error 1
```

### Steps to reproduce the behavior
`make app NATIVE=osx OSX_MIN=10.13 RELEASE=1 TILES=1 CLANG=1 USE_HOME_DIR=1 SOUND=1 LANGUAGES="ru" LUA=1`

### Steps to fix
For fix this bug, I add `lang/compile_mo.sh $(LANGUAGES)` to `Make` file in string `889`. Like in other platforms (because it missing for `$(NATIVE), osx`) section:
```
888 ifdef LANGUAGES
889 lang/compile_mo.sh $(LANGUAGES) # <<<<-- this was missing
890 mkdir -p $(APPRESOURCESDIR)/lang/mo/
891 cp -pR lang/mo/* $(APPRESOURCESDIR)/lang/mo/
892 endif
```
After that, the compilation was successful and I got a working version with ru language.

**Comment by Leland** [comment]
Can confirm.

> For fix this bug, I add lang/compile_mo.sh $(LANGUAGES) to Make file in string 889. Like in other platforms (because it missing for $(NATIVE), osx) section:

Does this actually work for you? This errors out on my system with:

```
$ make app NATIVE=osx OSX_MIN=10.13 RELEASE=1 TILES=1 CLANG=1 USE_HOME_DIR=1 SOUND=1 LANGUAGES="ru" LUA=1
Makefile:889: *** missing separator.  Stop.
```

**Comment by BevapDin** [comment]
> missing separator.  Stop.

This usually means you have not put a tab in front of the recipe. There must be a tab character (not a space) in front of the `lang/compile_mo.sh` line.

**Comment by akirashirosawa** [comment]
> Does this actually work for you?

Yes, it is actually work (with tab in front). I tasted now, and with space I got same error.

> There must be a tab character (not a space) in front of the lang/compile_mo.sh line.

Confirm, actually, I used tab in makefile. Github seems ate tab in inserted code.
