### ISSUE TITLE
Reloading shotguns from the ground with full inventory erases ammo, crashes game.

### ISSUE THREAD

**Issue by notafed** [CleverRaven/Cataclysm-DDA#23552]
v0.C-27430-ge5d2149 - Build 7327
Windows 10 - Tiles

Mods active:
None

### Expected behavior
Reload the shotgun without picking it up. Or require the player to wield it to reload, if their inventory is full.
### Actual behavior
Strange behavior, sometimes reloading, sometimes game eats the ammo, sometimes the game says "Can't reload orange juice (fresh), can't reload cranberry juice (fresh), etc" even though no such items exist on or anywhere near my character, lol. Sometimes it just crashes the game.

![cdda shotgun bug](https://user-images.githubusercontent.com/25914252/39063300-a0c546a0-4498-11e8-87ac-f55811570fe5.png)

### Steps to reproduce the behavior
1. Fill inventory to max.
2. Spawn shotgun and ammo on the ground.
3. (R)eload the shotgun.
4. Try not to crash.

**Comment by notafed** [comment]
Similar results with other guns: AR-15 with 30 round stanag magazine

![cdda reloading bug funny](https://user-images.githubusercontent.com/25914252/39063832-49071324-449a-11e8-81e6-054a3e26aa6a.png)

**Comment by BorkBorkGoesTheCode** [comment]
@notafed Cannot confirm in 0.C 27466. What objects are in your inventory before the crash?

**Comment by notafed** [comment]
I simply filled the rest of my inventory with rags. And I left the empty shotgun and the ammo on the ground next to me. Tried reloading them with (r) and got various different bugs out of it.

**Comment by Night-Pryanik** [comment]
> inventory is full
What do you mean, weight or volume?

**Comment by Night-Pryanik** [comment]
Can confirm on latest experimental. Just got my inventory filled both for weight and for volume and tried to reload gun laying on the floor.
![default](https://user-images.githubusercontent.com/11132525/39081104-5b8622da-454c-11e8-8508-dc123c01ee61.png)

It seems that `reload_finish` activity is trying to get targets for reloading from ether in this case.

**Comment by Isaacssv552** [comment]
I had the same problem trying to reload a welder from ground with full inventory.

**Comment by Night-Pryanik** [comment]
There is a comment in `game.cpp`:
https://github.com/CleverRaven/Cataclysm-DDA/blob/26f02fbbcea0825d2612bf40349e1de582583aa0/src/game.cpp#L9389-L9390
so we might need to explicitly make player to pick up weapon or tool prior to reloading.

**Comment by lucasmr** [comment]
I believe #24413, #24266 and #23735 are related to this. There should be a full rewrite of the reload action, using game_menus::inv. I'll take a look.
