### ISSUE TITLE
Non-conductive unarmed weapons don't prevent zapback

### ISSUE THREAD

**Issue by Siyalatas** [CleverRaven/Cataclysm-DDA#23558]
Some time ago the "cestus" weapon was given the nonconductive flag in order to fill a niche for unarmed weapon users, but due to the way the zapback is coded, unarmed attackers will get zapped regardless of weapon status.

**Comment by kevingranade** [comment]
This is probably an easy fix, but sounds like a great time to add a zapback
unit test.
