### ISSUE TITLE
Crafting interrupted by light going out cannot be resumed

### ISSUE THREAD

**Issue by Siyalatas** [CleverRaven/Cataclysm-DDA#23569]
Game version: f275932 (self-compiled)
Operating system: Manjaro Linux
Tiles or curses: Tiles
Mods active: none

Pull [#23299](https://github.com/CleverRaven/Cataclysm-DDA/pull/23299) made light going out interrupt crafting, however crafting interrupted this way cannot be resumed, only restarted.

To test, I debug wished enough items to make a kabuto (10 hr craft), got debug HVAC and Life Support so morale doesn't fluctuate, started the craft at 14:00h, light went out at 19:50h. Wished an atomic lamp and restarted with "-", crafting didn't finish until 5:50h the next day. Same problem with selecting the recipe again in the crafting menu.

**Comment by l29ah** [comment]
Maybe the interruption should be done like in `game::cancel_activity_query` and not `act->set_to_null()`?
