### ISSUE TITLE
Metabolism extremely fast while undergoing crack cocaine withdrawl

### ISSUE THREAD

**Issue by squidpizza** [CleverRaven/Cataclysm-DDA#23574]
Game version: 0.C-27520-g4f7da1ef4d
Operating system: Linux(ubuntu 17.10) 
Tiles or curses: Curses
Mods active: None

When starting a game as a  crack addict, once withdrawl sets in, metabolism becomes extremely high, particularly on day 1.   

With a new character, no eating or drinking, minimal movement and activity within the evac shelter:
Day 1 9:15 full, slaked, comfortable.  -120 crack cocaine craving.   Effects: depressed, depressants[13], Crack Cocaine Withdrawl.  All stats at 8

Day 1 1:16pm   Famished, dehydrated, tired, comfortable  Morale: Crack cocaine craving -285  Effects: winded, Depressants[151], Depressed, Crack Cocaine Withdrawl. Extreme pain.  All stats at zero.

Death from dehydration and/or starvation at about 4:15pm, Day 1.

Starting a new character with same attributes and wishing in food and water, I consumed approx 200 vegetable aspics(20 nutrition each) and a similar amount of water by the end of Day 2.  The effects seem to taper off after day 1 with occasional spikes.

**Comment by ZhilkinSerg** [comment]
Today we learned that drugs ARE bad, kids.

**Comment by FulcrumA** [comment]
True that, though I'd like to see this balanced as well. Horrible mental and physical health effects, low stamina, shakes and so on as withdrawal symptoms are fine and I wouldn't even mind if they'd be nearly debilitating in case of heavy, prolonged addiction but munchies bordering on deadly is kinda silly.

**Comment by Isaacssv552** [comment]
Maybe reduce the metabolism acceleration and make withdrawal cause 'hallucinatory' type increases in hunger/thirst? It would prevent single day starvation without removing the cravings.

**Comment by l29ah** [comment]
Re: balance: i don't even see any noticeable gain from consuming any drugs stronger than coffee/mild opioids while in pain, as the side effects are devastating. Do i miss any mechanics that could be abused with drugs?
