### ISSUE TITLE
A cell phone should state it works as a clock in the description

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#23577]
Game version: master

Haven't quite figured out how to edit descriptions with regards to all the translations.

**Comment by ZhilkinSerg** [comment]
Isn't it obvious? We all know what cell phones are.

**Comment by l29ah** [comment]
On Sun, Apr 22, 2018 at 10:59:34PM -0700, ZhilkinSerg wrote:
> Isn't it obvious? We all know what cell phones are.

It isn't obvious that i always know the exact time when i have a cell phone buried deep in my rucksack and not consuming any batteries actually.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments
