### ISSUE TITLE
Load Errors. Dose not seem to be a huge problem, but Please help!

### ISSUE THREAD

**Issue by TheGoldenStarOfVerity** [CleverRaven/Cataclysm-DDA#23570]
Game version: 0.C - 27520-g4f7da1w

Operating system: Windows 10

Tiles or curses: Tiles

Mods active:
Dark Days Ahead

Classes and Scenarios Mod
Classic Roguelike Classes
StatsThoughSkills IV
ZSFIXED_C:DDA Extra Professions

Bionics Systems Mod
Craftable Gun Pack
DeadLeaves' Fictional Guns
Extended Realistic Guns
Icecoon's Arsenal
Makeshift Items Mod
Medieval and Historic Content
More Survival Tools
Mythological Replicas
Packaging

DinoMod

More Buildings

Vehicle Additions Pack 
Tanks and Other Vehicles
Folding Parts pack

Necromancy

### Actual behavior
This just happened
![newer issue](https://user-images.githubusercontent.com/37771504/39090819-5ba5292a-45ae-11e8-8286-28c5f824c69e.PNG)

This has been happening
![this has been happening longer](https://user-images.githubusercontent.com/37771504/39090822-657e6fce-45ae-11e8-9e54-89a4756ed518.PNG)

### Steps to reproduce the behavior
I am not sure but I just made a new world with only (Dark Days Ahead) active and the errors did not ocure. So I think it has something to do with the mods, I have no idea really... SO...

**Comment by ZhilkinSerg** [comment]
What's `Golding Parts pack` mod? I am not aware of it - it can cause issues with `pda` item.

**Comment by TheGoldenStarOfVerity** [comment]
I made a typo it should be corrected in the first post.
Sorry about that and Thank you. 
I apologize for my screw up.

**Comment by ZhilkinSerg** [comment]
Makes sense now. Still I cannot see any mods which can cause the issue (unless you have some obsolete mod).

Please download and install Notepad++, then run search for `pda` string all over files in `data` folder as shown below and put results here?

# Search settings

![image](https://user-images.githubusercontent.com/16213433/39092732-27e82906-461d-11e8-9b4f-e215aad11920.png)

# Search results:

![image](https://user-images.githubusercontent.com/16213433/39092727-074402b0-461d-11e8-8571-d905273e5b82.png)

**Comment by TheGoldenStarOfVerity** [comment]
It'll take me a bit, but I'll get to it.
Thanks again.

**Comment by TheGoldenStarOfVerity** [comment]
I think I might have done something wrong but here's an image

This is the top half of the search results
![searchre](https://user-images.githubusercontent.com/37771504/39092979-71c0bdb2-45dd-11e8-8bed-6432f47cd576.PNG)

This is the excluded portion of the top half
![searchresecond-half](https://user-images.githubusercontent.com/37771504/39092982-7f8d0464-45dd-11e8-92fa-7924026fac7f.PNG)

This is the bottom portion of the search results
![searchre1](https://user-images.githubusercontent.com/37771504/39092984-83f84b4e-45dd-11e8-8117-7f1f08cbaea4.PNG)

this is the excluded portion of the bottom portion
![searchre1second-half](https://user-images.githubusercontent.com/37771504/39092985-886fea7e-45dd-11e8-8e9a-06e5e6b69065.PNG)

**Comment by ZhilkinSerg** [comment]
So, it is `Packaging` mod which adds `pda`.

You should click here and when file is opened replace `pda` with `cell_phone`:

![image](https://user-images.githubusercontent.com/16213433/39093100-86c5b60a-4622-11e8-88d2-dff8c03de4d1.png)

**Comment by TheGoldenStarOfVerity** [comment]
I'm really glad someone took the time to learn this stuff, stuff that I have yet to comprehend.
This seems to have worked as the (item id pda is unknown) error no longer occurred.
Thanks...

**Comment by ZhilkinSerg** [comment]
Other error will be fixed when #23572 is merged and you update the game.

**Comment by TheGoldenStarOfVerity** [comment]
Thanks, I already went in and adjusted the recipe and it seems to be working.
