### ISSUE TITLE
Add shortkey to see advanced description

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23585]
Game version: efdda3f6b5a086e0c4935e06a9a1d2a3815f31bc

### Suggestion
I suggest to add a shortkey to access the “advanced description” window for surrounding terrain, furniture and creatures.

Currently, the only way to acces this to go into “look around” mode (`X`, or `;`) and press `e`. This is a bit awkward to use.

I'd like this to work in a similar way like the `e`xamine key (hit examine key then direction).

EDIT:
Additionally, this feature could be put into the action menu under “Look”, for completeness sake.

**Comment by Leland** [comment]
Do you find yourself using the advanced description mode very often? I hardly ever use it in practice

**Comment by Wuzzy2** [comment]
Well, **obviously** you don't use it very often, you're one of the major developers of this game! :D

I use it from time to time for unknown terrain. Especially to read the full enemy description in case it got cut off.
I also believe this screen might become useful in future to put in all sorts of additional information because it uses the entire screen (that's not part of the suggestion, however).
I think of this function of some kind of “advanced examine”.

It doesn't have to have a key assigned in the default config, however. My point is that the current controls just quite awkward to use, it's strange it has been so well hidden.

**Comment by FulcrumA** [comment]
I am not a developer and I am really surprised that you use it often enough to require dedicated key. Especially when x;e sequence isn't really that hard or bothersome. But it's fine either way if someone wants to add it.

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issue list.
