### ISSUE TITLE
Lizard-Kung Fu is “likely to be refactored” since 3 years

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23595]
Game version: 468a1a1307e85b6f15643c2d55db948fc2a3ae29

### Question
The description of Lizard Kung-Fu reads:

> One of the Five Deadly Venoms, and likely to be refactored to a mutation at the next save-compatibility breaker.  Lizard Style focuses on using walls to your advantage.

This description has been like this since version 0.B or earlier. And this kung-fu style has not been removed since then, and I don't think it was refactored to a mutation either. Which is now more than 3 years ago! :wink: 

Does anyone actually plan to change this Kung-Fu style? If not, the description should be changed accordingly.
If yes, I suggest to open an issue about this, discussing your plans with the Lizard.

**Comment by kevingranade** [comment]
The person who made that comment stopped contributing, a PR to remove it would be merged immediately.

**Comment by Wuzzy2** [comment]
No reason to close this issue so quickly then? :O 
Could have at least waited a week or so. PR coming soon. Jeez.
