### ISSUE TITLE
Add default binding for action menu

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23590]
Game version: efdda3f

### Suggestion

I suggest to add a default key binding for the action menu. 

### Rationale

Currently it has none which feels wrong. IMO this is one of the most useful features in the game because it lets you access *everything* with a single control. This should not be hidden like this.
This is great for new players to memorize and learn all the possible “things” you can do in the game, and it should definitely be made more visible.
So the justification to use up another key for this is totally given.

### The key to use

The question is, which key to use?
Looks like the default key config is already very crammed.
The only letter key which seems to be free is “O”.

**Comment by kevingranade** [comment]
Isn't it bound to escape?

**Comment by Zireael07** [comment]
I think the action menu was bound to % at some point.

**Comment by Wuzzy2** [comment]
@Zireal07: No, that's the **item** action menu.

**Comment by RobertoVGoulart** [comment]
I would suggest setting the Enter key as default for the action menu.
New players will make most use of the menu, since they don't know all the keybindings, and by setting it to the Enter key it's very likely that they will find it.

**Comment by Wuzzy2** [comment]
Thanks. :-)
