### ISSUE TITLE
Burning NPCs to death throws Read Access Violation

### ISSUE THREAD

**Issue by NotFuji** [CleverRaven/Cataclysm-DDA#23598]
Game version: 0.C-24399-ga98c6b1827

Operating system: Win 10

Tiles or curses: Tiles

Mods active: DDA

### Notes
Appears to be caused by an attempt to damage the NPC's worn items, presumably after they've already died and thus their inventory no longer exists.

### Steps to reproduce the behavior
Compile a debug build.  Spawn in a shelter.  Burn down the shelter with starter NPC still inside.

**Comment by 0Petya** [comment]
I'd like to take a look at this. I'm pretty new to the game, and I don't see a starter NPC in the shelter. Also what is the easiest way to burn it down?

**Comment by Shoes01** [comment]
You might have to enable NPCs in the options in order for them to spawn. Maybe Static NPCs. Easiest way to burn it down would be to spawn via the debug menu a lighter and a molotove cocktail, or maybe a flamethrower.

**Comment by 0Petya** [comment]
Oh I didn't think of a molotov, that'd probably do it. I tried spawning in a flamethrower and some canisters for it, but the canisters come empty from the debug menu, and I don't know how to fill them with flammable liquid. But I'll try the molotov later today.

**Comment by kevingranade** [comment]
Just fyi since the Molotov are easier.
To spawn gasoline or other liquids from debug, highlight the liquid, hit
'f' to toggle making them contained, and then hit enter and select your
quantity.

**Comment by ZhilkinSerg** [comment]
> Easiest way to burn it down would be to spawn via the debug menu a lighter and a molotove cocktail, or maybe a flamethrower.

You can also try `atomic flamethrower` from my [`dda-lua` mod](https://discourse.cataclysmdda.org/t/cataclysm-dda-lua-updated-on-2017-11-29/14117) - debug spawn it, put in hands, activate (`SHIFT`+`a`) and select direction with cursor keys.

**Comment by ZhilkinSerg** [comment]
Closed in #23983.
