### ISSUE TITLE
Recipe loaded on e-ink tablet screen is not available in crafting menu

### ISSUE THREAD

**Issue by slitherrr** [CleverRaven/Cataclysm-DDA#23606]
Game version:

0.C-27466-gca7d9b3

Operating system:

Windows 10

Tiles or curses:

Tiles

Mods active:

- Dark Days Ahead
- Filthy Clothing
- Disable NPC NEeds
- Simplified Nutrition
- Bionic Systems Mod
- Craftable Gun Pack
- Makeshift Items Mod
- Medieval and Historic Weapons Content
- Beta National Guard Camp
- Vehicle Additions Pack
- Tanks and Other Vehicles
- Boats

### Expected behavior
Recipe loaded on e-ink tablet should show in crafting menu when the tablet meets the other usual circumstances for recipes from books being added to the crafting menu.

### Actual behavior
It does not.

### Steps to reproduce the behavior

0. ensure no book with recipe in range, and that recipe is not already memorized
1. e-ink tablet loaded with recipe (onboard chemistry lab is the recipe in question)
2. ensure skills at high enough level (electronics 3 here, the character in question has 5)
3. activate tablet, make sure recipe is displayed (fourth menu item is "Recipe: onboard chemistry lab")
4. enter crafting menu, search for recipe by name, note no results
5. find a book with the recipe ("What's a Transistor?" and "Under the Hood" were available in my test case), put it in range
6. enter crafting menu, search for recipe by name, note single result

**Comment by ZhilkinSerg** [comment]
Was it even working previously? When you select recipe on the E-Ink it just starts to be displayed on its menu, it is not being added to the list of your known recipes.

**Comment by slitherrr** [comment]
I can't answer to "working previously" because I usually go a while between builds and don't know if this existed before. To the rest, let me respond with this: The expectation I'm referring in the report is that the tablet in range set to "show" the recipe in question would add to the list of craftable recipes the same way that a book in range adds recipes that are not memorized to your list of craftable recipes.

**Comment by kevingranade** [comment]
It was working at some point, this is the intended behaviour for e-ink tablets, and electronic readers in general.

**Comment by kevingranade** [comment]
This seems straightforward-ish, the ereader maintains a string encoding all the recipes it "knows", the crafting code just needs to get at it.  Mechanically that means decoding a comma-seperated string of recipe names and fixing up some other code.  Stylistically that means adding an item::get_recipes() method because the crafting code has no business knowing the internals of how the recipes are stored.

Along with fixing it, I'm going to remove the "display a recipe on the ereader" feature, it's unnecessary.
