### ISSUE TITLE
Default keybinding problems in monster list mode

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23605]
Game version: 460ae4a6101e67078b1e2e2046b6729efdfd5d3a

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: Default

### Introduction
In the `V` mode (look at and list nearby items and monsters), the game shows you how to use certain keys.

### Expected behavior
All keys work as shown.

### Actual behavior
First, the key `A` and `R` keys to add or remove some monster from the blacklist do not work as advertised.

If you go into the key config menu with `?`, you see why: All special keys are unassigned.

There are two special entries `SAFEMODE_BLACKLIST_ADD` and `SAFEMODE_BLACKLIST_REMOVE` with no default bindings.

If you assign the keys, the game still highlights A and R only.

Only the look key seems to be displayed correctly but ONLY if you have assigned it via key config.
Oddly, if no look key is assigned, the text “Try to look around” appears. This is an useless text and should be removed.

https://i.imgur.com/1FDIqs8.png

### Steps to reproduce the behavior
* Reset your config.
* Press `V` in-game, go to monsters mode.
* Try pressing A or R to add or remove something in blacklist.
* Try to look around, don't know how. :D

For more testing:

* Play around with different key configs in this mode and see how it is displayed.

**Comment by Night-Pryanik** [comment]
Cannot confirm on latest experimental as of September 29, 2019. Both adding and removing monsters from safemode blacklist is working as it should.
