### ISSUE TITLE
Bionic Sniper should have a way to recharge

### ISSUE THREAD

**Issue by IronRex** [CleverRaven/Cataclysm-DDA#23612]
Game version: 0C-7349

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Default (none)

### Expected behavior
Bionic Sniper profession used solar panels CBM to recharge bionic power. After solar panels CBM was removed in #23317 Bionic Sniper profession has lost the ability to recharge. Solar panels CBM has been removed in 224d624e928f2a80d7421ee760d97cf7050d68ff but not replaced with a different recharge method.

### Actual behavior
Bionic Sniper can not recharge

### Steps to reproduce the behavior
Start a new game as a Bionic Sniper. Exhaust all bionic power. Wait for sunny or clear weather.

**Comment by ZhilkinSerg** [comment]
1. Remove profession completely.
2. Move profession to Bright Nights mod and add back Solar Panels.
3. Keep profession and add Joint Torsion Ratchet (or some other bionics with `BIONIC_POWER_SOURCE` flag) to it.

**Comment by BorkBorkGoesTheCode** [comment]
This was resolved in #23630

**Comment by smolbird** [comment]
Re-open, pull request was closed due to rebase issues.

**Comment by ZhilkinSerg** [comment]
But, it is empty now.

**Comment by kevingranade** [comment]
@smolbird please slow down and verify your statements before making them, the PR clearly states, "Merged, but a rebase confused github.", and glancing at the modified file or the commit history would have clearly shown that the change had been applied.

**Comment by smolbird** [comment]
Ah shit, that was the one word I missed, yes.
