### ISSUE TITLE
"`v`iew morale" list is too short

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#23617]
Game version: master

When one consumes lots of different yummies (say, after looting a few vending machines), the list doesn't contain all the morale effects from them (as it's apparently limited to 16 entries), leading to, say, an incidental waste of yummies in order to increase morale even further.

**Comment by AMurkin** [comment]
Note: it is scrollable after #22795.

**Comment by l29ah** [comment]
Oh, wow, thanks. I expected it to scroll using Pg{Up,Dn} like `/` does, but no.
