### ISSUE TITLE
Add some hair-related recharging CBM

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#23613]
I was thinking of other ways to provide slight recharging capabilities similar to the solar panels CBM when I came up with this idea: 

**Short version:** Using the hair on our characters body to create energy and therefore removing all hair from our character. This could potentially give our character a slight warmth or charisma penalty or both.

**Long version:** I have found a short passage describing a potential process for energy creation using the cells that are responsible for hair growth and I believe it may be enough energy to be worth consideration.

> Since hair follicle stem cells consume the nutrient glucose — a form of sugar — from the bloodstream, they process the glucose to eventually produce a metabolite called pyruvate. The cells then can either send pyruvate to their mitochondria — the part of the cell that creates energy — or can convert pyruvate into another metabolite called lactate. (1). 

So given that these cells are able to produce several types of resources for our hair to grow, this can be rerouted to our charging CBM. Another idea is that we could require the Metabolic Interchange CBM to at least be installed for this to be a passive energy creating process. Using the Metabolic Interchange CBM, we wouldn't have to worry about the resources being wasted as they would still be "burned" similar to how a stomach works. The user would require no more food or water than usual but the character would be unable to grow any type of hair with it installed. This includes traits like fur that give our character some or lots of hair, and could potentially strengthen our passive CBM to create slightly more power because the body is trying to create 200% or maybe 500% more hair than usual with the same amount of resources.

Overall, with this type of CBM, it would give you a passive charge for your bionics every so often through day and night. What I suggest is a flat 1 charge/50 ticks taking into account all head,arms,torso, and leg hair. What I am unsure about is whether the body actually grows more hair while sleeping, if that is the case, then perhaps it could be 1 charge/50 ticks while sleeping and maybe 1 charge/75 ticks while awake.

(1): (_http://newsroom.ucla.edu/releases/ucla-scientists-identify-a-new-way-to-activate-stem-cells-to-make-hair-grow_)

**Comment by FulcrumA** [comment]
I am not sure if the amount of power generated could believably make noticeable difference for any device short of whatever can run off potato/lemon for a time. I wouldn't mind it to be mostly cosmetic improvement to metabolic interchange (modification? upgrade?) that makes it a few pecent more effective at the tradeoff of suggested penalties, but anything beside it will seem kind of cheaty and immersion-breaking to me. I am not fully against it but I am certainly sure it shouldn't be even nearly powerful enough to run anything on its own.

**Comment by kevingranade** [comment]
I feel like this is just a subset of metabolic interchange, and adding the special effects for missing hair is going to be a lot of work and error prone.

I also agree with @Fulcrum that this doesnt seem like it would generate a significant amount of power.

**Comment by 0Petya** [comment]
All this is saying that hair stem cells can metabolize glucose. The hair itself is not the power source. It's still glucose, what the whole body uses, and is already implemented in the form of the metabolic interchange CBM.

**Comment by CoroNaut** [comment]
Yes these cells produce the energy and resources required to build hair, so the energy could be rerouted to your bionics and those other resources could be burned by the body itself to produce energy from the remnants. As for the significance of the power generated, I figured that since we grow ~150 feet of hair a day across all of the hair that we have that it may provide at least some power.

**Comment by DoctorGoat** [comment]
This actually makes me think that it'd be neat to hook healing with a function and redirect it to CBM energy. The body's using a lot of resources to heal, so maybe a CBM could be made that A) negates healing and B) recharges based on attempted healing.

It'd probably be most similar in functionality to Cable Charger in both speed and in that the only real way to use it would be to sleep with it on.

**Comment by kevingranade** [comment]
Except that's again metabolic exchange plus some side effects.

**Comment by CoroNaut** [comment]
That's why I suggested the dependence on metabolic interchange CBM to begin with, it fits well and there is already a CBM dependence system (the internal reactor cbms). 

I also like the idea of the healing to CBM energy conversion. But with this, I think your body would have to be hurt for your brain to even want to heal you. Perhaps this type of CBM will be useless if you are at full health since the brain doesn't recognize any problem to fix, and to therefore send out little units to repair the damage. When you are almost dead however, it could generate a much larger amount of power, scaled perhaps.

**Comment by DoctorGoat** [comment]
The whole thing separating the healing hijack from metabolics would be the risk/reward since it'd only really do much when you're asleep and hurt, but yeah, it would work well as a cbm dependency. it'd be fun to have more of those.

**Comment by FulcrumA** [comment]
It seems like you want to suggest a different CBM that what this ticket is about. 

As for the idea itself, it's an interesting idea but I am ambivalent toward it fluff-wise. I like the effects but given that metabolism is necessary to just keep the body going, going so far as to completely halt it to generate power would not merely stop the healing but actually work toward body shutdown. In case of just metabolic interchange it's by robbing the body of nutrients already stored in the body reserves (I assume) to maintain cells and allow them to multiply, but since the body can heal, it implies certain amount of nutrition goes to the body. Making it also harder to heal on top of that suggests blocking cells from acquiring any nutrition completely which not only would in reality stop healing, it would likely speed up body deterioration (unless it'd be some regulated and not complete process underlined as such in description - then it could work a bit better).

Anyway, we're really going off the topic now.

**Comment by CoroNaut** [comment]
Closing this due to what reason?

**Comment by kevingranade** [comment]
> I feel like this is just a subset of metabolic interchange, and adding the special effects for missing hair is going to be a lot of work and error prone.

> I also agree with @fulcrum that this doesnt seem like it would generate a significant amount of power.
