### ISSUE TITLE
Can't change font size or tile scaling in or out of game.

### ISSUE THREAD

**Issue by Altreus** [CleverRaven/Cataclysm-DDA#23627]
Game version: 0.C (compiled from master 2018-04-28) (don't have a git SHA, sorry)

Operating system: Debian stretch

Tiles or curses: Tiles

Mods active: Default set

### Expected behavior

* Graphics menu contains scaling options to compensate for QHD or UHD screens
* Ideally, game interrogates OS for DPI settings
* Or SDL respects the DPI settings when rendering fonts (maybe it does, so CDDA should ask it to)
* At least editing some config files should scale the font or increase the font size

### Actual behavior

* There appears to be no way to increase the font size
* Game is basically impossible to play.
* The only way to achieve scaling is to change the desktop resolution

Regarding tiles, while I can `Z`oom the display, this is of course still bounded by what cata thinks the zoom levels are - meaning the minimum zoom is silly tiny, and a sensible zoom level is almost max zoom.

Cata will scale the screen properly if I use fullscreen, but it does this by overriding the desktop resolution. This is not a suitable solution because I play CDDA in the background, often leaving it running for long periods of time while I do something else on another workspace.

This thread no longer seems to apply -> http://smf.cataclysmdda.com/index.php?topic=13100.0

* There is no fontlist.txt
* There is no config directory at all
* Creating config/fonts.json had no effect
* Editing data/fontdata.json had no effect

I also note that the word 'font' only appears in data/fontdata.json.

I observed more things:

* Putting the system font /usr/share/fonts/truetype/freefont/FreeMono.ttf into data/font had no effect
* Changing the scaling mode had no effect
* Windowed Borderless is a fullscreen window that pays no attention to the terminal settings.

Presumably I have missed something - or it simply doesn't work. Either way, these settings should be editable from the graphics menu.

**Comment by Quintovir** [comment]
Here's what I do on Manjaro Linux:

1. Open your file manager.
2. Show hidden files by pressing Alt+. or whatever you have to press/do on Debian.
OR
In the address bar of your file manager paste `/home/USERNAME/.config/cataclysm-dda/` and press enter. Skip to step 5.
3. Open the .config folder that should be showing now.
4. Open the cataclysm-dda folder.
5. Add non-default fonts you plan on using in the fontlist.txt file.
6. Modify fonts.json file to your preference.
7. Paste the font file (i.e. VeraMoBd.ttf) in the /home/USERNAME/Cataclysm-DDA/data/font/ folder.

**Comment by BevapDin** [comment]
Find out where your configuration data resides. There should be a "fonts.json" file there.

After you start and close the game, there should at least be some files in the configuration folder:
- "keybindings.json" (changing a key binding in the game and saving the new bindings will create this file),
- "options.json" (changing options creates this),
- "debug.log" (just starting the program should create this).

> Game version: 0.C (compiled from master 2018-04-28) (don't have a git SHA, sorry)

What command *exactly* did you run? Certain options here can change where the executable is placed and where the configuration folder is supposed to be.

**Comment by kevingranade** [comment]
No confirmation that configuration options are insufficient for correcting issue.
