### ISSUE TITLE
`i`Inventory is very slow to open as opposed to `/`

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#23636]
Game version: master, also tried jumping half a year back through the git history, observe the same behaviour on my current save

I have about 180 "stacks" of items in my inventory (half of those are the cash cards that i'm still yet to find an atm to sort out), and `i` takes about 4 seconds to pop up, while `/` pops up momentarily, but doesn't understand the `=`assigned shortcuts, making actions like consuming a few packs of candies from my pockets really painful.

**Comment by Coolthulhu** [comment]
Most likely a duplicate of #22319

**Comment by l29ah** [comment]
It turned down to ~1s after i've emptied my cash cards.

**Comment by Leland** [comment]
Closing as a dupe
