### ISSUE TITLE
Characters shouldn't be able to dodge and train dodging while sleeping

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#23638]
Game version: 0.C-7353

Operating system: Windows XP SP3 x86

Tiles or curses: curses

Mods active: default only

### Expected behavior

Characters shouldn't be able to dodge and train dodging while sleeping.

### Actual behavior

![123](https://user-images.githubusercontent.com/11132525/39534441-41fd6700-4e3a-11e8-934f-f78622cb795a.PNG)

In my case I lay down to sleep, then giant mosquito attacked me. I was able to dodge him while sleeping, and the mosquito flied away. 30 minutes later it attacked me one more time, and this time it successfully hit me in the right leg, and finally I woke up.
### Steps to reproduce the behavior

Sleep somewhere near the hostile creature and watch the message log. Many tries may be required to reproduce the issue.

I think that because it's a missed attack from a monster, we could simply change the message from "You dodged the _monstername_" to "_Monstername_ missed", but training dodge while sleeping in still incorrect.

By the way, why the messages "You fall asleep" and "You use your pile of clothes" are duplicated?

**Comment by Coolthulhu** [comment]
We could set dodge to some huge negative number while asleep.

**Comment by CoroNaut** [comment]
What about just having the monster attack without going through the dodge check?

**Comment by FulcrumA** [comment]
I half-seriously want just a solid debuff to the skill, if only so there will be a rare chance you'll be able to dodge at dodging 10 even when asleep, to underline how preternaturally able you are at the skill.
