### ISSUE TITLE
Weapons mounted on turrets are invisible in tiles version

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#23646]
0.C 27598
Tiles or curses:
tiles
### Expected behavior
Weapons attached to turret mounts should be displayed if they have sprites associated with them and tile graphics are enabled.
### Actual behavior
Only turret mounts are visible regardless of weapon.
### Steps to reproduce the behavior
Find a vehicle with a turret and look at it from outside.
xotto has noted this as well as others: https://discourse.cataclysmdda.org/t/mshockxotto-tileset-new-thread/15330/8

![screenshot 1074](https://user-images.githubusercontent.com/18560216/39560436-cd43e608-4e63-11e8-9178-c90c72202bea.png)

**Comment by budg3** [comment]
Here's a small mod made from Xotto's instructions in the thread that I think fixes this by removing the "on_roof" setting for the turret_mount and adds it to all turrets in vanilla + Vehicle Additions Pack and Tanks and Other Vehicles. Doesn't seem to cause any issues, but I don't know for sure - can someone confirm this?
[TurretFix](https://drive.google.com/open?id=1D-ZNgPhrDKug6L2rzE7ENwhk5vTLHIWH)

**Comment by BorkBorkGoesTheCode** [comment]
@budg3 have you tried shooting a mounted M60 at a zombie adjacent to the vehicle on which it's mounted?
