### ISSUE TITLE
Inboard mirror is incompatible with a curtain

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#23645]
Game version: master

I can't install both of them on the same windshield at the same time.

**Comment by kevingranade** [comment]
This is working as intended, if you place a mirror on an opaque square it will let you see through the square.

**Comment by l29ah** [comment]
Then it's impossible to have a curtained windshield and decent rear lookout at the same time w/o fragile outboard mirrors :/
