### ISSUE TITLE
Reinforced vending machine breaks into glass instead of armor

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#23651]
The reinforced vending machine only drops glass when broken into; this should be changed to heavy steel armor, concrete debris or reinforced glass debris. It should also have a unique broken form different from the ordinary vending machine.

**Comment by cosmiccoincidence** [comment]
My PR leaves the glass shards as a drop but also adds, reinforced_glass_pane, sheet_metal, and steel_chunk to that list.
