### ISSUE TITLE
Unarmed damage calculation is messed up by previously wielded weapons

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#23665]
Game version: master

### Steps to reproduce the behavior

Create a new game picking the Blackbelt (with Zui Quan and 10 in melee/unarmed/dodging, if it matters), save, get out, kill a zombie with 1-2 hits, load, smash a window, wield a heavy stick, drop/throw the heavy stick from your hands, get out, kill a zombie with over a dozen of hits.

**Comment by BorkBorkGoesTheCode** [comment]
@l29ah did https://github.com/CleverRaven/Cataclysm-DDA/pull/23648 affect this in any way?

**Comment by l29ah** [comment]
Looks good now, thanks!
