### ISSUE TITLE
Action resumption is unpredictable

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#23668]
Game version: master

### Steps to reproduce the behavior

Start adding another chunk of heavy duty frame to your tank or forge a nodachi in a car in some city centre, get interrupted multiple times, waste all the action progress randomly at one of encounters.

**Comment by l29ah** [comment]
It seems like smashing corpses screw up the previous task.

**Comment by ZhilkinSerg** [comment]
The issue is crafting/construction intermediate results are not visible to player and only being kept in memory.

**Comment by DoctorVanGogh** [comment]
It's even a bit weirder.

My understanding of the code is if you stand **in the exact same place** and repeat the task it'll resume the previous progress.

Fun issue: It'll even resume the previous progress _and complete the previous task_ if you're trying to do something different now (observed with vehicles).
Start vehicle construction task X, get interrupted, deal with interruption, position yourself to resume task, start _other_ vehicle task Y, **task X get's completed**. I cannot recall if materials for task X or Y get consumed 😁

**Comment by Night-Pryanik** [comment]
If so, then it's definitely a bug.

**Comment by kevingranade** [comment]
This is the main reason I keep suggesting we create an entity that
represents in-progress crafting that spawns on the map.  Then this entity
can be interacted with to either resume the craft or disassemble it.

The current code is working as intended, but it can only handle trivial
intertuptions, if you move or trigger certain other long actions it will
lose it's state.

**Comment by ZhilkinSerg** [comment]
I believe we should also have single class with common methods which can handle various types of crafting results: items, constructions, vehicles.

Somewhat related issue - #112.

**Comment by l29ah** [comment]
Fixed by the new crafting state mechanics.
