### ISSUE TITLE
[Tools] Better pre commit support for linting, specifically win/vs builds

### ISSUE THREAD

**Issue by DoctorVanGogh** [CleverRaven/Cataclysm-DDA#23672]
I think I've now run into astyle or json linting issues dozens of times.... 

This is wasting a hell of a lot of people's time.

I think this needs better linting support, especially if developing on win/vs2015+. My understanding is that the cmake build process catches all those errors, vs builds *do not*.

So.... "_Need better tools_".

Feel free to assign this to me.

I'm heavily leaning to pre-commit hooks which simply barf on linting issues. A few powershell scripts shouldn't be too much of a hassle.

**Comment by ZhilkinSerg** [comment]
But neither astyle nor linting doesn't prevent/allow compiling. Developers should astyle/lint code they just added/updated leaving unchaged code intact. Why would powershell script be better than some Astyle plugin?

**Comment by DoctorVanGogh** [comment]
You misunderstand.... Build with vs never touches linting - it's the pure compilation.
`make` does linting... So the closest analogue for a win dev would be a script (preferably powershell) which does the same linting as the makefile.

And for convenience sake just put it in as a pre-commit hook, which should prevent you from pushing crappy code. You can still _force_ commit or just not use the hook in your local repo.

**Comment by ZhilkinSerg** [comment]
Yes, there is `make astyle` and other stuff in the `MAKEFILE`, but it is up to developer to run or not to run it. I mean it the same as running astyle in VS - you either astyle your changes or not.

**Comment by Veraghin** [comment]
A problem that I noticed on win/vs2015+ is that the make astyle command ignores the .astyle-blacklist-ed files and formats them anyway
