### ISSUE TITLE
Can't remove storage batteries from vehicle.

### ISSUE THREAD

**Issue by biosilicifiedchitin** [CleverRaven/Cataclysm-DDA#23679]
Game version:#7379

Operating system: I don't know what this is but I'm using a Hp Laptop with windows 7

Tiles or curses: Curses

Mods active: Dark Days Ahead, Filthy Clothing, PKs Rebalancing, NPC traits, Folding Parts pack, Boats & Stats Through Skills.

### Expected behavior 
15 strength character with a hacksaw & mechanics 4 next to a telescoping crane removes storage battery case from electric SUV.

### Actual behavior  
I have everything I need but the part about needing lifting 1 or 15 strength is still gray/red (forgot which color).

### Steps to reproduce the behavior 
Spawn in electric SUV & give required mechanics level & 15 strength, build frame next to it & add telescopic crane then attempt to remove battery storage case.

EDIT: I am an idiot & the frame the crane was on the same vehicle I was trying to remove the battery from, but my 15 strength not allowing me to remove is still a glitch though.

**Comment by YakumoChen** [comment]
Is there even an item with the lifting quality?

**Comment by YakumoChen** [comment]
So spawning in the stuff needed for a telescopic crane on a frame, I was able to get the fabled "Lifting 1" quality.

**Comment by TimeIsEndless** [comment]
Can also confirm that 15 strength does not enable you to lift out the battery without a crane

**Comment by Night-Pryanik** [comment]
> All the jacks have "jacking" quality which don't actually help with lifting vehicles.

Just curious, how could elevating vehicle from the bottom help with the removing heavy batteries?

**Comment by Night-Pryanik** [comment]
Tested right now on latest experimental. Spawned an electric SUV and a hacksaw, debug-gived my character 15 strength. Was able to successfully remove storage battery.

**Comment by Night-Pryanik** [comment]
@biosilicifiedchitin can you still reproduce the issue?

**Comment by Night-Pryanik** [comment]
Closing as non-confirmed. Ping me if this is reproducible.
