### ISSUE TITLE
Cougar leaping outside of your car takes a lot of CPU

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#23686]
Game version: master

### Steps to reproduce the behavior

Sit in a car, read a book, observe a cougar leaping around your car helplessly and time going painfully slow.

Maybe it should be actually able to damage it? Even zombie dogs do (but regular ones don't).

**Comment by l29ah** [comment]
[2019.04.29-4.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3169344/2019.04.29-4.zip)
Try working on the vehicle, for instance.

**Comment by l29ah** [comment]
Tried to sleep in a car near a wolf, and it was horrible.
Save: [2018.05.06.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3404256/2018.05.06.zip)
gprof top:
```
Flat profile:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls   s/call   s/call  name    
 40.81     36.39    36.39   465300     0.00     0.00  map::route(tripoint const&, tripoint const&, pathfinding_settings const&, std::set<tripoint, std::less<tripoint>, std::allocator<tripoint> > const&) const
  8.87     44.30     7.91 511597350     0.00     0.00  pathfinder::add_point(int, int, tripoint const&, tripoint const&)
  8.42     51.81     7.51 997835850     0.00     0.00  pathfinder::get_layer(int)
  7.69     58.67     6.86 996439950     0.00     0.00  void std::__push_heap<__gnu_cxx::__normal_iterator<std::pair<int, tripoint>*, std::vector<std::pair<int, tripoint>, std::allocator<std::pair<int, tripoint> > > >, long, std::pair<int, tripoint>, __gnu_cxx::__ops::_Iter_comp_val<pair_greater_cmp_first> >(__gnu_cxx::__normal_iterator<std::pair<int, tripoint>*, std::vector<std::pair<int, tripoint>, std::allocator<std::pair<int, tripoint> > > >, long, long, std::pair<int, tripoint>, __gnu_cxx::__ops::_Iter_comp_val<pair_greater_cmp_first>&)
  2.31     60.73     2.06 454132800     0.00     0.00  map::get_pathfinding_cache_ref(int) const
  1.75     62.29     1.56 462176723     0.00     0.00  map::get_submap_at(tripoint const&) const
  1.51     63.64     1.35 517405351     0.00     0.00  square_dist(tripoint const&, tripoint const&)
  1.51     64.99     1.35 420675386     0.00     0.00  map::move_cost_internal(furn_t const&, ter_t const&, vehicle const*, int) const
  1.45     66.28     1.29 422125986     0.00     0.00  map::veh_at_internal(tripoint const&, int&) const
  1.23     67.37     1.10 462172887     0.00     0.00  map::get_submap_at(tripoint const&, point&) const
  1.14     68.39     1.02 462423124     0.00     0.00  map::getsubmap(unsigned long) const
```
[prof.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/3404264/prof.txt)

**Comment by l29ah** [comment]
Probably related: https://github.com/CleverRaven/Cataclysm-DDA/issues/31961

**Comment by ZhilkinSerg** [comment]
I confirm the issue. The performance in provided savegame with wolf is pretty bad.

![image](https://user-images.githubusercontent.com/16213433/62767966-76aa9280-ba9e-11e9-9a2c-20d9aa9dae05.png)

**Comment by ZhilkinSerg** [comment]
Performance should be much better now. Here is what I get on current master with wolf-save:

![image](https://user-images.githubusercontent.com/16213433/65076603-026ae500-d9a2-11e9-96e2-62a54d3a8487.png)

Can you confirm please?

**Comment by l29ah** [comment]
Yes, it seems much better now.

**Comment by ZhilkinSerg** [comment]
Thanks. I will close it as resolved now. There are will be more performance optimizations in the future.

**Comment by kevingranade** [comment]
This should have been dealt with in https://github.com/CleverRaven/Cataclysm-DDA/pull/32470
