### ISSUE TITLE
'Reset world after death' setting

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23688]
Game version: Currently 0.C-27741 but applies to all

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

A simple feature request that could be added rather easily. Currently upon character's death there's a setting allowing automated deletion of a world. I'd like to request refurbishing it into an option for the world that allows player to choose whether the world should be deleted or simply reset, prompted or not
The request is caused by the fact that seemingly many people who want to start fresh often have to keep the option off and reset the world manually or, if the world is deleted, they start new one with the previous settings anyway.

**Comment by TechCatOther** [comment]
I agree. Always use reset world, not option to delete it. I thinks that this option is useless. You need to setup world mods and settings again.
