### ISSUE TITLE
Spider poison ignored armor

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23681]
Game version:0.C-27732

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Spiders, when attacking and biting the character, attempt to inject poison on first bite and then only every so often and it's counted as such only if they can penetrate armor and cause direct damage with the bite.

### Actual behavior
Spiders, at least of the basement-dwelling variety seem to be injecting poison with every attack with said poison accumulating even when spiders themselves have hard time penetrating the armor. Which leads to silly situations where character is pain-locked while still alive:
![ouch](https://user-images.githubusercontent.com/38487938/39714042-5aab5050-5218-11e8-8260-54bff68058d2.png)
I think zombies' bites work much better, maybe their code could be somehow repurposed?

### Steps to reproduce the behavior
Attack spiders when armored but not poison-resistant.

**Comment by Night-Pryanik** [comment]
Closed by #23764.

**Comment by FulcrumA** [comment]
@Night-Pryanik I am checking referenced fix and sine it had issues, it was reverted quite a few days ago, as reported in ticket itself. Does it mean that this issue was fixed elsewhere?

**Comment by Night-Pryanik** [comment]
Oh, sorry, my fault.

**Comment by Night-Pryanik** [comment]
I guess think issue could be closed. 
The code explicitly states that monsters can apply their on-hit effects **only** if their attack dealt any damage. Thus spiders that fail to penetrate armor can't poison the player. If the player is poisoned then it's his armor to blame (low values of coverage and/or protection).

**Comment by FulcrumA** [comment]
Was it something that happened since the ticket was made? If it's fixed, it's fixed. I worry though that a player can still be stunlocked despite neglible damage with enemies unable to really kill said player without forcing a long wait. We can always try to trim the issue list for now and have it closed and if this thing happens again to me or someone else, we can bother you to reopen it, I guess?

**Comment by Night-Pryanik** [comment]
> I worry though that a player can still be stunlocked despite neglible damage with enemies unable to really kill said player

That's a balance issue, @jesseclvrt mentioned it in #23764 - maybe we need to increase the minimum damage dealt threshold for poison to be applied, but the issue you raised - "Poison is applied despite there was no armor penetration" - isn't confirmed.

> if this thing happens again to me or someone else, we can bother you to reopen it, I guess?

Yes, of course.

**Comment by FulcrumA** [comment]
Alright then, closing it for now.
