### ISSUE TITLE
Woods Soup contains meat but can be crafted without meat

### ISSUE THREAD

**Issue by JayThirtySeven** [CleverRaven/Cataclysm-DDA#23707]
Game version: Build 7388
Operating system: Windows 10
Tiles or curses: Tiles
Mods active:
[
  "dda",
  "StatsThroughSkills",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "more_classes_scenarios",
  "bio_mod",
  "realguns",
  "More_Survival_Tools",
  "national_guard_camp",
  "more_buildings",
  "more_locations",
  "Experimental-Z-Level",
  "Urban_Development",
  "blazemod",
  "deoxymod",
  "Tanks"
]

### Expected behavior
My character with the Meat Intolerance trait could craft Woods Soup using broth, bird eggs, and wild vegetables and then eat it happily.

### Actual behavior
The crafted soup contains meat and triggers the Meat Intolerance trait even though no meat was used during crafting.

### Steps to reproduce the behavior
Have the Meat Intolerance trait, craft some Woods Soup using broth, eggs, and veggies. Eat the resulting soup and suffer.

### Comments
Ideally a crafted item would "remember" its actual ingredients for situations like this but if I understand the way crafting works that isn't possible. Since woods soup is defined as being made of "Flesh" and "Vegetable Matter" but not "Egg" the recipe should probably be changed to remove egg options so that the soup must always be crafted from the materials it will be composed of. This way there is no surprise for characters with dietary restrictions.

### Bonus Thought
I'm now imagining my character cooks up her Woods Soup using bird eggs and is extremely confused when she discovers fully formed chicken bones at the bottom of the pot.

**Comment by KorGgenT** [comment]
#27252 should fix this

**Comment by KorGgenT** [comment]
this should be fixed due to #27689
