### ISSUE TITLE
Chainsaw and a tree.

### ISSUE THREAD

**Issue by Robik81** [CleverRaven/Cataclysm-DDA#23704]
Game version:
current experimental

### Expected behavior
Cutting a tree with chainsaw should be reasonably quicker than with an axe.

### Actual behavior
It is not. Current formula in source code:

`moves = MINUTES( 70 - p->str_cur ) / it->get_quality( AXE ) * 100;`

So, if we assume 10 STR character, times are:
primitive axe (q1): 60m
wood axe (q2): 30m
chainsaw (q3): 20m

Not worth the gas/batteries, if you ask me. Also, 20 minutes to fell a tree with chainsaw is ridiculous.

### Suggested solution
I just checked the video on YT, and it should be more like
5min flat for safety and cleaning preparations and 20s (for chainsaw) to do the cutting.

Same issue with cutting trunk into the logs.

**Comment by AMurkin** [comment]
See #22659 and a PR, closed it.

**Comment by Robik81** [comment]
I see that is was improved in the past. Good. 

But the formula is IMO still sketchy and does not reflect reality too well, so there is space for improvement.

**Comment by Night-Pryanik** [comment]
The formula could be adjusted like 
`moves = MINUTES( 70 - p->str_cur ) / ( it->get_quality( AXE ) ^2 ) * 100;` (quality gets squared)
so q1 is still 60 mins,
q2 is 15 mins,
q3 is 6,67 mins.

**Comment by Robik81** [comment]
I would go with flat 5 minutes no matter the tool for safety and cleanup preparations.

For the number we want to add to that, i would not stick with trying to find one formula to fit them all.

Either we can go with switch and flat number for every case (something safe for default) or we could make some fitting formula for hand tools (influenced by STR) for qualities < 10 and  formula for powered tools qualities >= 10.

**Comment by Maddremor** [comment]
A little playing around with the formula has given a workable result if the chainsaw was bumped to AXE 4 and time calculated as `(60-Str) / (2^(AXE-1) )` (Values rounded down for readability)

|    | Str 1 | Str 2 | Str 3 | Str 4 | Str 5 | Str 6 | Str 7 | Str 8 | Str 9 | Str 10 | Str 11 | Str 12 | Str 13 | Str 14 | Str 15 | Str 16 | Str 17 | Str 18 | Str 19 | Str 20 |
|:--:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Q1 |   59  |   58  |   57  |   56  |   55  |   54  |   53  |   52  |   51  |   50   |   49   |   48   |   47   |   46   |   45   |   44   |   43   |   42   |   41   |   40   |
| Q2 |   29  |   29  |   28  |   28  |   27  |   27  |   26  |   26  |   25  |   25   |   24   |   24   |   23   |   23   |   22   |   22   |   21   |   21   |   20   |   20   |
| Q3 |   14  |   14  |   14  |   14  |   13  |   13  |   13  |   13  |   12  |   12   |   12   |   12   |   11   |   11   |   11   |   11   |   10   |   10   |   10   |   10   |
| Q4 |   7   |   7   |   7   |   7   |   6   |   6   |   6   |   6   |   6   |    6   |    6   |    6   |    5   |    5   |    5   |    5   |    5   |    5   |    5   |    5   |

**Comment by Night-Pryanik** [comment]
Chainsaws is AXE 4, ok, but what items should have AXE 3 then?

**Comment by cainiaowu** [comment]
There are tools with butcher quality 20 and nothing 19 IIRC. So we might not need to have anything AXE 3

**Comment by Night-Pryanik** [comment]
That's true, but I think it would be better if we adjust formulas according on consequent tiers (or grades, or qualities) of tools, not arbitrarily increasing or decreasing tool qualities to fit numbers we want to achieve.

**Comment by Shoes01** [comment]
I don't think the formula has to change, just what is displayed to the player. Instead of showing the number being used in the hidden formulas, show something else. Could even be a Tier D/C/B/A/S/S+ kind of thing. That way the programmers don't have to do as much mental gymnastics to balance things.

**Comment by RadHazard** [comment]
Wood axes could be bumped back up to AXE 3 (I'm pretty sure they used to be there but were lowered to 2 to make chainsaws better than them).  Right now they have the same woodcutting quality as the makeshift axe and fire axe. which seems wrong to me.  Makeshift axe should probably also be bumped down to 1 IMO, and 2 should be restricted to axes that are proper tools but aren't designed for chopping trees down.
