### ISSUE TITLE
error message when NPC dies in moving car. not game breaking tho

### ISSUE THREAD

**Issue by T3rry45** [CleverRaven/Cataclysm-DDA#23700]
Game version:#7385

Operating system:Windows

Tiles or curses:

Mods active:

### Actual behavior 
Error message shows, has happened with car and van so far

### Steps to reproduce the behavior 
select release consoles while in a moving car with a following npc in seat of the same vehicle, when npc moves out of seat and dies from the moving vehicle aka hit by the car, the error will appear. 
P.S love the game

**Comment by zizdarren** [comment]
Game version:#7604
Operating system: Windows
Tiles or curses:
Mods active: 

additional detail: 
Error occur when either NPC or Player died when driving. (or in the moving car seat)

error message:
23:31:54.58 : src/map.cpp:1216 [void map::unboard_vehicle(const tripoint&)] map::unboard_vehicle: passenger not found
23:32:23.573 : src/map.cpp:1303 [vehicle* map::displace_vehicle(tripoint&, const tripoint&)] Empty passenger part 9 pcoord=61,71,0 u=62,71,0?

**Comment by mlangsdorf** [comment]
NPC death code is apparently not updating the vehicle code that the NPC is no longer on the vehicle.

**Comment by Night-Pryanik** [comment]
Should this be closed after #28420?

**Comment by Mooses2k** [comment]
Should it be closed after #30190?

**Comment by kevingranade** [comment]
Can   no longer reproduce.
