### ISSUE TITLE
Vehicle `Needs repair` advice is not sorted

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#23724]
Game version: ae827586a54d732806bcea110e299b0dc2b02743

Tiles or curses: curses

### Expected behavior
`Needs repair` shows the most damaged part that needs your attention, `r` in a random non-vehicle square in the vehicle window jumps you to that part.

### Actual behavior
`Needs repair` suggests me to fix my yellow heavy duty frame while there is a violet one.

### Steps to reproduce the behavior
Get a humvee, install a welder there, give it some bushing action, go repairing it in the `Needs repair` order.

**Comment by mlangsdorf** [comment]
Assign this to me, please; I'll fix it at some point.

**Comment by Cool3303** [comment]
Because it can get stuck on some compoments I would suggest that it should take you to damaged components that can be repaired with your current gear/skills FIRST, and cycle through until you get to those that can't be repaired afterwards.

**Comment by irwiss** [comment]
On current master it's sorted https://github.com/CleverRaven/Cataclysm-DDA/blob/02a1199903d2fb7e65b73899806b9888c1f66ff6/src/veh_utils.cpp#L93
