### ISSUE TITLE
Bones do not indicate having any calcium

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23734]
Game version: Currently 0.C-27803

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Bones are wonderful source of calcium, providing it in plenty.

### Actual behavior
Bones are edible but there's no indicator they provide any nutrients, including calcium.

### Steps to reproduce the behavior
Examine/consume a bone item.

### Additional notes
In general, current nutrition system is quite questionable - even a person maintaining a relatively balanced diet they'd adhere to IRL is prone to rather quickly develop several noticeable deficiencies as many edibles, be they raw ingredients or cooked dishes do not register token amounts of vitamins/iron/calcium they'd normally have.

**Comment by ZhilkinSerg** [comment]
I have strong suspicion that calcium in bones is in such chemical form which is not ingestible.

**Comment by FulcrumA** [comment]
I am not aware of anything like this. Cursory search for whether the bones are healthy to eat suggests plenty of suggestions that they're an awesome source of calcium. I don't know why calcium in bones wouldn't be digestible - in fast, many predators do eat bones from time to time and humans are known to do so as well, without any ill effects, which suggests that bones digest just fine, at least if properly prepared/well-chewed.

**Comment by kevingranade** [comment]
Please provide your sources if they indicate that humans can meaningfully
digest bones, I haven't run across any sources indicating that they can.
Lots of sources about carnivores digesting bone, nothing about people.

**Comment by Wishbringer** [comment]
That was around two million years ago, when Homo habilis used rudimentary stone tools to strip and smash bones.
https://www.marksdailyapple.com/bone-marrow-recipe/

**Comment by FulcrumA** [comment]
I mean, I even provided a source in the first comment before @kevingranade  answer, as well which also should confirm that eating unprocessed bones while not the easiest is certainly possible, @Wishbringer  . I am pretty sure we're set as far as realism of such goes.
Plus, maybe it's a matter of some mod I am using but bones are already set as edible there, both regular and tainted (though the latter poison the character), the ticket I've made is in regards to nutritional value of those bones as currently the provide nothing, just decrease hunger.

I'd also like to underline the last paragraph - nutrition as it is in game right now is generally quite unbalanced, leading characters on what would be pretty liveable and alright diet IRL to develop quickly debilitating health conditions.

**Comment by Wishbringer** [comment]
Bone meal should at the very least have calcium added to it, as that is obviously accurate.

**Comment by ZhilkinSerg** [comment]
My point is while bones are made of Calcium it is not Calcium vitamin.

**Comment by Wishbringer** [comment]
@ZhilkinSerg 
Are you talking about this?
Calcium/cholecalciferol is a combination of a calcium salt (usually calcium carbonate) and vitamin D3 (cholecalciferol).

**Comment by ZhilkinSerg** [comment]
Yes, when player character has Calcium deficit it is not enough to give them some bones to resolve the condition.

**Comment by Wishbringer** [comment]
It would certainly not be a good short term solution, but still better than nothing, I suppose.
Not sure what the effective time frame differences would be.

**Comment by FulcrumA** [comment]
I need to point out that we don't have any D3 deficiencies (in fact, we lack tracking of most vitamins), in case of bones and in general, I simply assume that when there's calcium deficiency - there's just calcium deficiency - in which case consuming bones should be a considerable help, at least over period of time when there's no other, decent source of calcium.

Also, a good point was raised of short-term and long-term effect of nutrient intake. It is likely stepping outside of the scope of this particular ticket, but if the vitamin/nutrition system will ever undergo balancing (as it seems to be in considerable need of), we could consider making nutrients acquired from food need time before curing certain conditions - ensuring ability to live without reliance on vitamins/calcium pills/iron injections just through normal meals, but also making medication work instantly thus letting it stay valuable and useful.

**Comment by kevingranade** [comment]
I've seen no sources that indicate that humans can eat bones as a dietary supplement, feel free to reopen if you find some.

**Comment by ZhilkinSerg** [comment]
> I simply assume that when there's calcium deficiency - there's just calcium deficiency - in which case consuming bones should be a considerable help, at least over period of time when there's no other, decent source of calcium.

Calcium deficiency is lack of substances which allow absorption of calcium (e.g. D3 vitamin), so eating bones, eggshells, seashells, chalk or whatever really won't help.

**Comment by FulcrumA** [comment]
>I've seen no sources that indicate that humans can eat bones as a dietary supplement, feel free to reopen if you find some.

Usually bones aren't eaten unless smashed apart a bit, but both bone meal and bone marrow are considered healthy, potent supplement used since prehistory.
https://www.urmc.rochester.edu/encyclopedia/content.aspx?contenttypeid=19&contentid=BoneMeal
http://healthlibrary.brighamandwomens.org/Library/Encyclopedia/19,BoneMeal
http://www.dietnutritionadvisor.com/what-are-the-benefits-of-bone-meal-supplements

https://www.westonaprice.org/health-topics/food-features/bone-marrow/
https://drhealthbenefits.com/food-bevarages/food/health-benefits-of-bone-marrow
https://www.livestrong.com/article/539722-nutritional-contents-of-beef-bone-marrow/

While it's hardly an argument quite a few people seemed to have asked similar and receive answer which would prove so:
https://www.quora.com/Can-calcium-be-gotten-from-eating-bones

I remind you, bone meal is regular bones powdered for the ease of consumption. It does not change chemical qualities of the bone itself, merely makes it easier to digest. Bone broth and meal are also already in the game (though possibly due to one of the above mods). Humans can and are certainly able to consume bones without turning them into powder and the bones are digestible (the very first source link but its also rpetty common knowledge as like I've said - in certain parts of the world or among certain groups bones are eaten in general) so they can provide nutrition, even if at the cost of having to work harder to digest the thing.

At the same time, apparently bones are kinda dangerous long-term source of nutrition due to bones accumulating harmful substances like lead (https://en.wikipedia.org/wiki/Bone_meal). But that doesn't rebuke premise of this ticket - that bones are edible and provide nutrition - but merely that they aren't healthy food (should decrease healthiness stat the way junkfood does, possibly).

I am somewhat confused why there is any further push against the idea. Bone meal is confirmed food supplement. Regular bones are edible as confirmed in the first link (of my first comment: https://www.smithsonianmag.com/smart-news/shrew-eating-scientists-show-humans-can-digest-bone-66337580/) and so they also provide the same compounds bone meal does, merely in harder to eat and digest form. Of course, I'd gladly look at any sources claiming that it's the process of making a meal out of bones that is transforming bone physical qualities.

@ZhilkinSerg 
If so, then the whole calcium deficiency is a misnomer and a mistake that needs to be scrapped altogether. Deficiency of calcium and deficiency of D3 provide different symptoms. You're more likely to get lethargic, pained and more susceptible to infection long before lack of D3 will cause significant issues with calcium absorption and lead to weaker bones.

https://www.webmd.com/diet/guide/vitamin-d-deficiency

At this point I also have to point out that quite a healthy amount of vitamin D regular person can acquire through regular outdoor activity without heavy body coverage - a thing that can be easily done in game. Yet still, in game the issue is calcium deficiency called as such and as unlikely as such is IRL, in game it happens because a lot of food that should provide at least token amounts of calcium (which in sum would be enough to keep a person well-supplied in such) - doesn't. But that's a bigger issue related to the whole nutrition system and how unfinished it is, not the fact that bones are indeed both edible and digestible, allowing certain absorption of calcium, among other things.
