### ISSUE TITLE
Pebble-firing weapons capable of firing BB ammunition

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23733]
Game version: not applicable (all relevant to the issue)

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: not applicable unless a mod adds/modifies pebble/BB-firing weapons

### A suggestion
Pebble-firing weaponry should be also capable of firing BB ammo. Whether it's a small pellet or a pebble, as long as its dimensions allow it to be loaded, average airsoft gun, slingshot etc should be able to use it, even if with some additional modifiers.

It's less clear whether BB-firing weapons should allow pebbles - it depends on a weapon, whether it's rifled, what's the fiting mechanism, how strong is the spring etc..

**Comment by kevingranade** [comment]
Yes it would be nice to fire BBs, not to mention other small heavy objects out of slingshots.

Pebbles would never work out of a pneumatic weapon, they're too irregular.

**Comment by l29ah** [comment]
One can already use pebbles to fire from the pneumatic assault rifle.

**Comment by Night-Pryanik** [comment]
No discussion in almost a year, closing.
