### ISSUE TITLE
Cannot construct walls underground.

### ISSUE THREAD

**Issue by drhead** [CleverRaven/Cataclysm-DDA#23740]
Game version: 7384

Currently, it is impossible to dig pits in rock, which makes it impossible to construct most types of walls underground.  Several in-game structures have walls that require pits (LMOE shelters have metal walls, labs have concrete walls) and if these walls break it is impossible to replace them without using the map editor.  Since obviously someone had to build these facilities, it would make sense for there to be a way to build these walls again.

**Comment by FulcrumA** [comment]
Tangentially related - I found no recipe to build default "wall" walls most regular constructions are made out of, a thing that bothers me somewhat.

**Comment by Theundyingcode** [comment]
>  I found no recipe to build default "wall" 

I always assumed that they were the framed drywall type that would simply be impractical in a survival setting.

**Comment by Night-Pryanik** [comment]
@FulcrumA it is indeed drywall, see discussion in #15537.

**Comment by FulcrumA** [comment]
@Night-Pryanik 
From what I read in the discussion, the default wall is a stand-in for inside and outside walls. Including drywall and no-drywall ones. There's simply no differentiation of those in the game, but it is what industrial complexes, regular houses, shops and almost every other kind of building use in CDDA. It is what it is, a generic game wall.

As a generic wall that seems to be useful for all kinds of things, including survival bases @Theundyingcode refers to I'd like to be able to build it. Plus, we already can build all kinds of things, including ones very impractical for survival setting so I don't see why we should disqualify this particular object on such a basis even if for some weird reason it'd become a valid requirement.

**Comment by Theundyingcode** [comment]
I am very much in favor of the idea of replacing the generic wall with actual types.  A script to change the outer walls of buildings to something else would actually be fairly easy so long as there are no courtyards and the like.  The IDs could then be changed using find and replace

I'm thinking types:
- framed brick wall (exterior, nice houses and small stores)
- framed siding wall (exterior, cheap housing and buildings)
- framed concrete (exterior, big box store type wall)
- drywall (interior, all offices, stores and industrial insides)
- plaster (interior nice houses and older buildings)

**Comment by kevingranade** [comment]
> Currently, it is impossible to dig pits in rock, which makes it impossible to construct most types of walls underground. 

This is intentional, if you're going to build a wall in a cave, the construction process is going to be completely different than it is on soil.  In practice a masonry wall can be cemented directly to a rock floor, and a frame wall could be nailed in place.

If you want to make walls constructable underground, adjust the wall recipe re s to make it happen.

>  Since obviously someone had to build these facilities, it would make sense for there to be a way to build these walls again.

This doesn't follow, there are plenty of crafting and construction tasks that aren't possible to replicate after the cataclysm.  I.e. single-pour concrete structures are going to be pretty much impossible due to manpower requirements.

> I found no recipe to build default "wall" walls most regular constructions are made out of, a thing that bothers me somewhat.

Open an issue to discuss it, this issue is about building walls underground.

>  wrote a python script to change the outer walls. I'll test it out and maybe set up a pull request with a start on the conversions by next week.

I'm very much looking forward to that.

**Comment by drhead** [comment]
I do like the idea of having the construction process being different and perhaps more time consuming.  Realistically it makes sense, and gameplay-wise it is a good (though ultimately minor) tradeoff for the added security an underground base can offer.  I'd certainly like to contribute these but I am not sure of how to implement this properly, since adding a separate construction recipe to make the same thing with different initial requirements would seem a bit sloppy.

I've also been told that I should probably mention that what initially made me think of this issue is where a metal wall in my LMOE shelter got destroyed by a tree falling on it aboveground.  I cut down a tree, heard metal screeching northwest and below me, and when I went into my base the metal wall was destroyed.  While this is certainly interesting emergent gameplay, I am not sure if this is a bug.  I'm just operating under the assumption that the LMOE shelter is a makeshift shelter and may not be completely up to code, and that if a tree was growing on top of my house then it might destroy some walls if I cut it down, too.  If that sounds like a bug I'll open it as an issue.

Thinking about the wall recipes logically, I would think most of them would end up being a bit simpler on rock floors, since it should be somewhat easier to get the same amount of stability from bolting things in a solid floor that you would get from burying something in the dirt.  Brick walls, like you said, should probably be able to be bolted directly to the floor.  You could probably nail the two-by-four framing for a concrete wall in place and get okay results.  Reinforced concrete, you could drill holes in the rock floor to put rebar in then pour the concrete and the wall should work fine.  Metal wall, I'm guessing you could bolt one metal plate to the floor and weld the other metal plates to that one.  (I don't know anything about construction in real life, please don't let me build your house).  Basically, I'm thinking that most of the recipes could remain mostly unmodified in terms of requirements and could be built directly on rock floor without the need to have a pit.  If the construction recipes support requiring one type of terrain OR another type of terrain as a precursor (I don't see any recipes like this that exist currently), this could be a fairly easy change.

**Comment by Night-Pryanik** [comment]
> metal wall in my LMOE shelter got destroyed by a tree falling on it aboveground.

Do you have Z-levels enabled? If this is an issue, then I have to reopen #14117.

**Comment by drhead** [comment]
Yes, I have Z-levels enabled on that world.  If it makes any difference I did not enable them on the world initially and enabled them after the fact through the options menu.
