### ISSUE TITLE
JSON defined names for crafting recepies

### ISSUE THREAD

**Issue by Maddremor** [CleverRaven/Cataclysm-DDA#23744]
Currently, recepies are listed in the crafting menu by the end product. If multiple recepies have the same result, they also get the same name. We have the tag "id_suffix” as to not have variant recepies overwrite each other, but this is not visible to the player. Soups are an example of this. The liquid only, the soup in a mason jar, and the soup in a tin can are identically named.

I propose that recepies be given an optional value in JSON giving display names. The format could be something akin to `"name" : "jar of %s"` where %s inserts the crafting product. If no name is given in a recipe, assume `"name" : "%s"` In addition to differentiating variant recepies, this could give some more flavor to recepies, communicating to the player how they are crafting something. For example, “bake flatbread” or “whittle pointy stick”.

**Comment by Broken-Admin** [comment]
Could this also be hard coded? Maybe a C++ tag too?
