### ISSUE TITLE
Debug message using first aid kit

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#23752]
Game version: 27848-g4bcbac0

Operating system: win10

Tiles or curses: curses

Mods active:
  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "craftgp",
  "brightnights",
  "bio_mod",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "crazy_cataclysm",
  "mutant_npcs",
  "npc_traits",
  "national_guard_camp",
  "more_buildings",
  "more_locations",
  "Experimental-Z-Level",
  "Urban_Development",
  "blazemod",
  "Tanks",
  "Mundane_Zombies",
  "more_classes_scenarios"

### Expected behavior
Using first aid kit display rack south of character to heal arm should have healed the arm.

### Actual behavior
Got the following debug message and the first aid kit got put in my inventory.
![cddaerror](https://user-images.githubusercontent.com/15700895/40214579-301232a8-5a21-11e8-9a6e-eaf996a12dc8.PNG)

### Steps to reproduce the behavior

Get injured and use first aid kits from surroundings?... Issue posted as soon as I got the error.

**Comment by Theundyingcode** [comment]
Happened again this time the first aid kit was on the dirt below me.
![image](https://user-images.githubusercontent.com/15700895/40255802-14f95612-5aae-11e8-8b51-c95e478d74c3.png)

I think it's transferring the item and then trying to use it only to find it's no longer there.

**Comment by Nithyi** [comment]
Version: 0.C-28906-g128e0e5 (tiles) 
Build: 7546
Mods: [ "dda", "no_npc_food"]

I am experiencing the same problem when using the action menu (a) to use a first aid kit from the ground. If i pick it up and use it by selecting it in the inventory it works as intended.

![cataclysm dda fak debug error](https://user-images.githubusercontent.com/40969029/42425592-b4b7b560-831f-11e8-89fa-2dc894cd5c7f.png)

**Comment by kevingranade** [comment]
Sounds related to #23552 since it's a symptom of moving the item into inventory and then the code failing to handle it.

**Comment by alanbrady** [comment]
I can no longer repro this issue as reported because of #24389

![screenshot from 2018-08-23 00-10-52](https://user-images.githubusercontent.com/60370/44510422-7c2e8300-a669-11e8-9632-f9e6c9e620e2.png)

'Too big to pick up'

**Comment by alanbrady** [comment]
Oh neat actually I managed to reproduce a flavor of this issue even after #25075

Reproduction steps:
1.  Spawn a first aid kit and a bunch of rags
2.  Drop everything
3.  Pick up as many rags as will fit it inventory
4.  Wield a first aid kit
5.  Activate first aid kit and watch as the game does something weird like disassemble one of the rags, I'm certain this can crash too because this is similar behavior to #23552.

**Comment by alanbrady** [comment]
Some more characterization:

- Wielding and attempting to use a first aid kit in any situation is broken and doesn't do anything.  You get a nice "You resume your task"

- It might try to disassemble some other item in your inventory if you're close to encumbered/overencumbered.

- General bizarre behavior

Sounds like the way first aid kits work is just completely broken, especially after the healing items rework.  Going to keep looking at it.
