### ISSUE TITLE
Objects that are applied a blue highlight  loose their primary color (ASCII)

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#23759]
All furniture that contains items, monsters that are stunned or are friendly,  and anything else that gets a blue highlight dynamically applied will lose its symbol color and turn white on a blue background.

This make entities that share  the same symbol impossible to differentiate at a glance.

**Comment by Theundyingcode** [comment]
I think it's a side effect of the standardization of showing items are on the tile.  While this might be suboptimal, I firmly believe having one standard indicator for the presence of items outranks the ability to glance differentiate furniture.

**Comment by John-Candlebury** [comment]
We only had the blue background before, it achieved both goals.

**Comment by John-Candlebury** [comment]
After playing a bit further, I noticed it affects everything that gets a blue highlight. It also affects stunned and friendly monsters.

So its definitively a bug
