### ISSUE TITLE
"Prepare attack" action (suggestion)

### ISSUE THREAD

**Issue by DanielPBak** [CleverRaven/Cataclysm-DDA#23751]
There are a few times when I'm being chased by something fast and I round the corner and want to guarantee the first hit by preparing a hit. Instead, I have to wait until it occupies the square, and then try to hit it using the full attack time. It'd be nice if I could "get ready" to attack and reduce some portion of my attack time.

There's a classic horror movie scene where somebody is aiming a weapon (usually a gun or an axe) at a spooky doorway, getting ready to kill the first thing that steps through there. So it definitely fits the theme and rewards tactical thought.

One can definitely imagine some tragic or hilarious stories happening if something or someone you don't expect walks through that doorway.

It strikes me that when you're prepared and waiting to hit something, you're able to hit it a lot quicker (depending on the weapon), since a lot of the time spent hitting something is spent winding up, adjusting your aim, bringing your weapon to bare, whatever, and your character can pre-process these steps.

One concern for me is allocating another button - perhaps it should be hidden in the keybindings and automatically disabled, and a player has to manually enable it in order to do this? CDDA already has a ton of complexity up front so it might be nice to make the ramp a little easier.

If I made a PR for this kind of thing, would it be accepted? It's not clear to me what features should be mods and what should be parts of the baseline game.

**Comment by kevingranade** [comment]
How it works now is, if you "pause" on the turn before an enemy steps into
range, your move points for the turn are set to 0, which gives you the
maximum possible move points on the next turn to act.
This already gives you a fairly significant advantage, and I'm a bit
concerned that giving even more if a bonus would just reinforce kiting as
the only effective way to do melee.

Controls-wise, you would probably trigger this behavior by spending several
turns "pausing" which would trigger the behavior youre describing.

**Comment by DanielPBak** [comment]
That's absolutely a fair point.

I think there are two ways to balance this so it's basically only used to advantageously initiate combat, and not just a massive buff to kiting.

One: There is more total "swing time" if you prep a swing - perhaps the "wind up" to attack costs just as much as a regular attack (or double? whatever), and in exchange the actual attack is around halved. This means that kiting using this move is a little harder / impossible, since you're going to spend a lot more total time attacking than if you were just regularly kiting.

This makes some amount of sense in the fiction, winding up to swing a bat takes about as much time as swinging a bat in a smooth motion. And then you also have to swing the thing.

Two: Make it a cooldown? It could even be a cybernetic or something that uses power.

**Comment by kevingranade** [comment]
> This means that kiting using this move is a little harder / impossible, since you're going to spend a lot more total time attacking than if you were just regularly kiting.

Unfortunately that doesn't do it, turns spent not next to an enemy are mostly free (there's no risk), so putting more cost into it doesn't have an impact unless it's an absurdly high cost.
The core concept of kiting is if you can attack and then disengage before your opponent has an opportunity to act, you already spend a large number of turns setting up for each attack, increasing this a little more isn't going to change anything.

> My intention is absolutely for this to be a "surprise attack" or preparing a big swing against a charging zombie, and not a repeatable combat move.

Unless there's a very game-like solution of an extremely long cool down, I don't see a way to make that happen.

**Comment by DanielPBak** [comment]
> turns spent not next to an enemy are mostly free (there's no risk), so putting more cost into it doesn't have an impact unless it's an absurdly high cost.

This isn't for enemies you have to sprint

**Comment by DanielPBak** [comment]
>turns spent not next to an enemy are mostly free (there's no risk), so putting more cost into it doesn't have an impact unless it's an absurdly high cost.

I don't believe this is true, at least against enemies against which you need to sprint to kite.

If there's a long wind up time, that's extra stamina per blow. If the wind up time is sufficiently high, then it's too stamina inefficient

**Comment by DanielPBak** [comment]
I'll try to think of some other solution but I think you're right.

I was thinking that the stamina expenditure associated with that extra kiting might make it too costly, but there are slow enemies and it seems unlikely to strike a balance between realistic-seeming windup and stamina cost.

**Comment by kevingranade** [comment]
No workable suggestions have emerged.
