### ISSUE TITLE
Issues with the new screen resizing

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#23761]
Game version: 0.C-7407

Operating system: Windows XP SP3 x86

Tiles or curses: curses

Mods active: default only

- Minimizing game screen causes CTD;

![default](https://user-images.githubusercontent.com/11132525/40249718-849ac02c-5adc-11e8-82fc-2d809e2ad122.png)

- Resizing game screen to less than 80x24 causes CTD;
- New game screen dimensions ain't saved after resizing, so restarting game requires resize it again.

**Comment by Parahacker** [comment]
#23862 might be related - though I get no notification, the game just vanishes from the taskbar. Might be a Win10 thing. I have no CTD when resizing, but the text doesn't adjust to fit, staying in its corner or disappearing completely. Even menu changes only refresh the portion of the screen that isn't disappeared. Resizing by entering in new numbers in the config screen for height and width do save, but resizing by dragging the border does not. If I maximize the screen through the windows button or right-click, the text does not adjust to fit and the maximize status does not retain once the program is closed.

**Comment by BevapDin** [comment]
What does the debug log ("config/debug.log") contain?

**Comment by Night-Pryanik** [comment]
Nothing important:

```
21:29:24.266 : Starting log.
21:29:27.266 : couldn't parse color: c_black_red
```
