### ISSUE TITLE
WALLS! overhaul plan

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#23777]
Just a notification of intent and opportunity to get some feedback before I got too far.

Per my commitment in #23740, I have begun working on an overhaul to replace the generic "wall" with actual wall types.  I wrote a python script that will look at a building's json file and makes interior and exterior walls different.  My initial plan was to simply add a few new wall types and replace the use of t_wall with them however, I thought of a way to add a lot more variety with relatively little additional work.

Since prefabricated siding comes in all sorts of colors and types, changing the type of walls used is an easy and realistic way of adding more variety to the game.  If in the building's json file a "construction style" field is added, the walls could be id'd as simply "interior" or "exterior."  This way mapgen could pick wall types from the construction style and apply them to the entire building when it gets generated resulting in lots of variety from the same set of json files.

I'm planning to split the overhaul up as follows:

- Part 1: Addition of new wall types based around wood and steel framing construction techniques.

- Part 2: Defining construction styles. (eg. housing_cheap = interiors: drywall exteriors: pink_plastic_siding, dark_gray_plastic_siding, green_aluminum_siding, etc, )

- Part 3: Addition of new construction/disassembly recipes and components for walls added in part 1. (not actually interested in doing this but they will need to get added)

- Part 4: Modification of mapgen to do realtime wall type selection. (might need help here as I have never so much as looked at the mapgen code before)

- Part 5+: Conversion of json building files to new format.

**Comment by John-Candlebury** [comment]
As a map maker, I think this is a lot of unnecessary work. both for you coding it, for future people creating maps. and for tile set makers. I

f it comes to manually adding the wall variants, I probably wont care enough to add extra entries to the pallete I work with, its quite starved for symbols as it is, and searching for wall Id's in "terrain.json" is just to much work for slightly different wall names and colors, especially id Im doing big structures or a big batch of maps.  And I'm not the only one to think like this.  Proof is the general lack of buildings that use painted walls and rugs, we have had those for almost three years and barely any maps use them.

I also doubt most players will notice or care , never seen someone paint their base's walls or install rugs in all the time I've been in the forums.

**Comment by FulcrumA** [comment]
I am all for it, not only because I really hope to be able to build equivalent of current default walls to expand buildings while allowing them to maintain uniform look.

A very important part regarding bulding but which should be a part of the overhaul: currently walls cannot be really deconstructed well without becoming a considerable risk of toppling whole section of the building down. You basically can just bash them and hope for the best. Ability to disassemble parts of the wall and roof without causing such damage (maybe requiring point higher in fabrication?) would solve those issues people are bothered with and which make it harder to build serious stationary bases since a long, long time.

**Comment by acidia** [comment]
I've done a weee bit of construction in game and real life, I'll be the first to admit I wouldn't use custom walls but if the script designated interior from exterior that would be a nice boon.  Less interested in color and more the ability to rearrange interiors.  Generally modern house construction in NE usually only RELIES on exterior wall to be load bearing.  The bigger the house, the less likely this is true.  It would be nice to take a sledge and crowbar to deconstruct all of the interior walls in a house and rearrange them.  Smashing three walls to get material to build one hasty dry wall barricade to seal a hallway is something you could do in an hour in real life if you didn't care what it looked like and had all the walls in the world to smash for material.  5 2x4 and double the dry wall need for a real wall for a quick wall (literally overlap dry wall).  I could see me doing that in game.

Major uses for exterior walls would follow deconstruction methods:
Aluminum Siding (tons in PA) strip that shit off for valuable aluminum leaving plain walls
Asbestos siding (often under modern siding) asbestos is great for forages/metalworking, its fiber/cloth that doesn't burn
Vinyl siding for plastic chunks
Metal frame buildings are obvious but they also often times use blue foam board insulation that is easy to recover and can be implemented if someone get around to expanding temperate mechanics. 

I'd say it wouldn't be a bad project to make construction a bit more interesting.

**Comment by FulcrumA** [comment]
@acidia 
I am fine with the being exterior/interior walls in a way of game deciding which are load-bearing but the thing is that the suggestion seems to be dividing what walls can be constructed as which, with different styles. If game's internal mechanics check the building and define certain walls as load-bearing for itself it's okay, but forcing people to redesign all building 'prefabs' and then make it so only arbitrary choices of walls are allowed under certain circumstances is not a good way to go about it.

So yeah, I agree with you in that it could work if it'd be simply a script dividing which are interior and which exterior, but having simply two different construction types - interior walls and exterior walls that have to be flagged as such in every construction and currently existing build type by hand - is a slightly different thing.

**Comment by Theundyingcode** [comment]
> have to be flagged as such in every construction and currently existing building json by hand

I wrote a script to convert the json files from using "t_wall" to "interior_wall," "exterior_wall" and, add a construction style.  It will still take a while since right now you have to run it only converts 1 file at a time but even then we are talking like ~30 sec a file tops.

**Comment by ZhilkinSerg** [comment]
Why all the complexity? One can simply add necessary `t_wall_interior_exterior_whatever` terrains when creating new overmap terrains and use it in mapgen definition.

**Comment by Theundyingcode** [comment]
> when creating new overmap terrains

So it can be applied to the ones that already exist?

**Comment by ZhilkinSerg** [comment]
> So it can be applied to the ones that already exist?

I don't know... Too much effort with little gain. Even without mods and palettes:

Search "t_wall" (2651 hits in 161 files)
Search "om_terrain" (863 hits in 183 files)

**Comment by ZhilkinSerg** [comment]
It is not about script - it will be neccessary to test all updated mapgens.

**Comment by CoroNaut** [comment]
I hope that the tile sets for the tiles CDDA will be properly made though. Mostly to keep the two versions from diverging in any way.

**Comment by Theundyingcode** [comment]
This is stalled... I need terrain to support JSON inheritance before it can be added in a sane manor. 

I "reopened it" as one of my projects when I got back from school + summer job (camp = not code friendly) and have made three attempts to fix up the `mapdata` file for this.  However, each time I have gotten sidetracked or ended up going in circles and I currently lack the motivation for a fourth attempt.  If someone is willing to get `copy-from` working for terrain, I only need to do some finishing touches/ update docs before testing can begin.
