### ISSUE TITLE
Make money bundles redeemable at ATM for cash card charge.

### ISSUE THREAD

**Issue by drhead** [CleverRaven/Cataclysm-DDA#23778]
I think it would make sense to be able to redeem money bundles for... well, money.  It's clear that in the Cataclysm universe, paper money has been mostly phased out, but without anything saying otherwise I'd assume paper currency still has to be honored at least to the point that you can redeem it for charge on your more useful cash card.

**Comment by Theundyingcode** [comment]
Depending on how phased out  it is, it might be reasonable to make this only work at bank atms

**Comment by kevingranade** [comment]
ATMs can accept deposits, but they are generally manually verified, i.e. they're never going to clear because no one is there to do it.
There's no need to adjust the status quo here.
