### ISSUE TITLE
Issue with zombie technician and compound bow + carbon fiber arrows(?).

### ISSUE THREAD

**Issue by blakewood18** [CleverRaven/Cataclysm-DDA#23793]
### Game version:
0.C ge7cbb32
### Operating system:
Windows 7 - 64 bit
### Tiles or curses:
Curses
### Mods active:
Dark Days Ahead
Stats Through Skills
Simplified Nutrition
Bionics Systems Mod
DeadLeaves' Fictional Guns
Medieval and Historic Content
More Survival Tools
Boats
Folding Parts pack
Vehicle Additions Pack
Tanks and Other Vehicles
### Expected behavior
Aim the bow to damage the zombie technician at least once then get the bow yanked out of my hand proceeding to try finishing it of with the hunting knife.
### Actual behavior
Aim bow till I get a full hit percent bar(?).
Let the Arrow loose.
The Game Freezes then proceeds to crash.
### Steps to reproduce the behavior
Wielding Compound bow maybe using even the carbon fiber arrow.
Aiming till the zombie technician gets to a full hit chance(?) for a level 4 archery skill.
Proceed to fire the bow.
??????
Success?(Freeze + Crash)

**Comment by alanbrady** [comment]
I haven't tried with tip of tree but I've been playing 0.C-7374 and if you are aiming any weapon and the zombie tech tries to pull it away from you while aiming the game will freeze/infinite loop.

**Comment by alanbrady** [comment]
I built master on my linux box (0.C-27923-gf5723a09e7) and I was not able to immediately reproduce.  The issue may already be fixed, but likely requires further testing.

**Comment by StripedMonkey** [comment]
I'm not sure if this is the same issue or not, but I am having the same issue with a crossbow.
![screenshot from 2018-07-03 03-52-11](https://user-images.githubusercontent.com/8009284/42206493-3f9a27e4-7e75-11e8-8126-eb25b9a1d20b.png)
I managed to fire one arrow, I reloaded, aimed, then hit p for precise shot. It immediately froze. It sounds like a similar issue at least.
