### ISSUE TITLE
Advanced Microreactor CBM exhibits the same behavior as the Microreactor Upgrade CBM

### ISSUE THREAD

**Issue by hagamablabla** [CleverRaven/Cataclysm-DDA#23804]
Game version: 7419

Operating system: Windows 10

Tiles or curses:

Mods active: Filthy Clothing, Simplified Nutrition, Disable NPC Needs

### Expected behavior
The Advanced Microreactor CBM should install the Advanced Microreactor, and the Microreactor Upgrade CBM should change an installed Microcreator to an Advanced Microreactor.

### Actual behavior
Both CBMs act like the Microreactor Upgrade CBM and change an installed Microreactor into an Advanced Microreactor.

### Steps to reproduce the behavior
At the start of the game, spawn in the three CBMs (Installed Microreactor, Advanced Microreactor, Microreactor Upgrade) to test their behavior.

**Comment by Veraghin** [comment]
Working as intended. Looking at slot occupancy, you are not supposed to be able to have both installed at the same time.

**Comment by kevingranade** [comment]
In that case you shouldn't be able to install the advanced minireactor if the regular minireactior is already instslled.

**Comment by kevingranade** [comment]
Regards an obsolete bion8c.
