### ISSUE TITLE
Can't occupy the same tile as a shopping cart?

### ISSUE THREAD

**Issue by 1skandar** [CleverRaven/Cataclysm-DDA#23806]
Game version: 7419

Operating system: Win 7

Tiles or curses:

Mods active:

Did something change recently where you aren't allowed to occupy the same tile as some vehicles? I started a new game just now after being away for a few weeks and when I found and then dragged a shopping cart back to my base and then went to stand on it to sort things out of it I couldn't. I can, however, stand in the same tile as a wheelbarrow. Not that I mind if this is an intended change, just it seems odd and it definitely is a recent change, within the last few days.

**Comment by ZhilkinSerg** [comment]
See #22802 and #22791.
