### ISSUE TITLE
Slimesprings Inappropriately Morale Boost and Heal Player when Hostile

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#23810]
Game version: Experimental 7419

Operating system: Windows 7 64-bit

Tiles or curses: Tiles

Mods active: Default (Dark Days Ahead, Filthy Clothing, Disable NPC Needs, Simplified Nutrition)

### Expected behavior
Hostile slimesprings' special attacks (morale boost, heal bite, heal bleed) don't occur and/or don't affect the player.
### Actual behavior
Hostile slimesprings will attack the player and simultaneously heal any bites or bleeds, as well as giving inspirational cheers between attacks.
### Steps to reproduce the behavior
Debug spawn hostile slimespring.

The other issue is I am not sure if there is any non-debug situations wherein slimesprings could be hostile to the player (since they are spawned friendly by a player mutation Omnicellular), so this may be a moot issue. Funny nonetheless.

![codependentslimespring](https://user-images.githubusercontent.com/32253888/40349685-912bfe34-5d64-11e8-9ea4-19fc8b78d246.png)

**Comment by DracoGriffin** [comment]
>NPC mutations are under development so this will become a problem.

Nice job, I totally forgot about that. Time to test that out.

**Comment by DracoGriffin** [comment]
Follow-up on NPC Slimesprings:

Doesn't happen. Created world with default settings and removed Disabled NPC Needs (so they would actually need food/drink).

Debugged a few NPCs and myself with all the requirements for Omnicellular (threshold Aqueous plus the Distributed Neurology and Senses) -- tested that it works for me both as an action (in the mutations menu `[` ) and from overeating/drinking to "assimilate" and spawn slimesprings.

Befriended some NPCs and made others hostile (some angry, some fleeing). Locked all NPCs in a room with debug terrain so they couldn't escape but still path find around. Left food and drink out they would consume and "assimilate" but never generated slimesprings.

Forcefed friendly NPCs with NPC interaction using option `g` - `I want you to use this item` with 10 lasagnes and 10 plastic bottles of herbal tea (for total of 20 drink) -- "assimiliated" all but no slimesprings generated.

So currently, this is not an issue for NPC slimesprings (because they don't spawn for NPCs) -- until such a time that it is fixed (which is probably a bug that needs to be fixed?).

![npcslimespringtest](https://user-images.githubusercontent.com/32253888/40709574-b06ba51a-63b3-11e8-946f-99a305b34eb9.png)

Even tried using debug menu to alter their needs by setting hunger/drink to high levels and that didn't provoke any spawning of slimesprings either.

**Comment by Theundyingcode** [comment]
I'd list it as a bug.  @DracoGriffin do you want to spawn an issue for it as you did the testing? If not I'll do it later.

**Comment by Xhuis** [comment]
Going to pop in here - I just had an NPC slimespring spawn. After she climbed into my car and started looting, I blew her head off with a shotgun, and a slimespring spawned from her as she died. It was friendly, and boosted my morale a few times before running off.
![](https://i.imgur.com/sLQuDbk.png)
