### ISSUE TITLE
Mutants can start the game wearing footwear based on profession

### ISSUE THREAD

**Issue by gboudrias** [CleverRaven/Cataclysm-DDA#23829]
Game version: 0.C-27897-g8ce9ee5

Operating system: Linux (Debian Testing)

Tiles or curses: Tiles

Mods active: None

### Expected behavior

Characters that start off with the Leg Tentacles or Hooves mutation should start off without footwear or socks.

### Actual behavior

Characters with Leg Tentacles or Hooves mutation start off wearing boots and socks if their profession dictates it. The footwear can't be put back on once removed.

### Steps to reproduce the behavior

Select Experiment scenario and a profession that has socks (such as Volunteer Mutant). Select the Leg Tentacles mutation. Start the game. You are wearing boots and socks on your tentacled legs.

**Comment by Ramza13** [comment]
Just tried this and it seems fixed.  Started a character as a volunteer mutant with leg tentacles and spawned not wearing footwear.
