### ISSUE TITLE
Safe mode travel interrupted by tracking squirrel

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#23828]
Game version: 
- 0.C-27943-g56bbaf0 (tiles)

Operating system: 
- Windows 10

Tiles or curses: 
- Tiles

Mods active: (Default)
- DDA
- Filthy Clothing
- Disable NPC Needs

## Expected behavior
AFAIK, squirrels shouldn't interrupt the PC's safe mode.

## Actual behavior
Squirrels that are "Tracking." seem to interrupt the PC's safe mode while he is traveling. Message: "Spotted squirrel--safe mod is on!..."

## Steps to reproduce the behavior
I can't seem to create a scenario where this reproduces easily, but it has happened over time with several characters in several worlds.

**Comment by BorkBorkGoesTheCode** [comment]
You can add an exception to the list of safemode-triggering monsters: press shift+~ then add the monster's name to the list.

**Comment by searker** [comment]
I´d say this is the correct default behaviour. Without configuring special safemode-rules, any creature with the status 'tracking' is triggering the warning.

Since 'tracking' does not differentiate between tracking the player and tracking other creatures, they could possbily track you and therefore pose a threat.

**Comment by RogueYun** [comment]
Why is as squirrel tracking other creatures?

**Comment by kevingranade** [comment]
Aggro isn't nuanced, the only options are fleeing, attacking, or tracking.
Literally everything counts as potentially hostile.
Perhaps we could add a "MOSTLY_HARMLESS" flag that makes safe mode ignore some creatures by default?

**Comment by kevingranade** [comment]
I do consider known harmless creatures triggering safe mode a bug.

**Comment by Night-Pryanik** [comment]
I think this should be resolved by #77704.
