### ISSUE TITLE
Disinfected soaked cotton balls spawn even more cotton balls after being used

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23823]
Game version: Currently 0.C-27943

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
After using disinfectant-soaked cotton ball, it disappears or turns into some "dirty cotton ball" item,

### Actual behavior
Using such cotton ball creates two regular cotton balls. 

### Notes
May be some side-effect of some of recent changes to disinfectant items.

### Steps to reproduce the behavior
Use disinfected-soaked cotton ball on yourself or bitten NPC.

**Comment by ZhilkinSerg** [comment]
It is not possible to add `FILTHY` flag for `used_up_item` - this should be coded in C++.

**Comment by FulcrumA** [comment]
Understandable. Still - at the very least using a cotton ball should make it disappear rather than create two new, just not disinfectant-dipped cotton balls.

**Comment by RogueYun** [comment]
Just did a little test run. Cotton balls are certainly duplicated.

## Steps to quickly reproduce:
- Debug: Damage self
- Debug: Wish for disinfected cotton balls
- Apply disinfected cotton ball

## Result:
- Two regular cotton balls appear out of nowhere

**Comment by Night-Pryanik** [comment]
> Two regular cotton balls appear out of nowhere

Ball spawning upon use is intended, but _two_ balls is definitely incorrect.

**Comment by RogueYun** [comment]
I say keep it simple. Keeping a dirty/filthy cotton ball upon use is a bit much (Do you keep dirty cotton balls after using them to wash in the washing machine?). Why not just let it vanish?

**Comment by RogueYun** [comment]
I'm not a super coder and I run into more errors than I know what to do with whenever I try to compile the game in general, but probably removing , the  "used_up_item" : "cotton_ball" from the med.json should fix this quickly and relatively painlessly.

**Comment by Night-Pryanik** [comment]
>  but probably removing , the "used_up_item" : "cotton_ball" from the med.json should fix this quickly and relatively painlessly.

Yes, you are right. 
By the way, you don't need to compile the game to test json-only changes.

**Comment by RogueYun** [comment]
> By the way, you don't need to compile the game to test json-only changes.
It's more like I need a help and support desk that I can call and have them talk me through how to compile and also how to use git. 

I can make the json changes, and I have in the past, but without a good understanding of compiling/git I really struggle in my ability to support this project as much as my heart yearns to support it.
