### ISSUE TITLE
Attacking NPC Bandits with bionic Electroshock unit turned on causes crash

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#23834]
Game version: 7426

Operating system: Windows 10

Tiles or curses: Tiles

Mods active:
"dda",
"filthy_morale",
"no_npc_food",
"novitamins",
"makeshift",
"Medieval_Stuff",
"More_Survival_Tools",
"nw_pack",
"alt_map_key",
"npc_traits",
"mxocosmetics",
"mutant_npcs",
"national_guard_camp",
"Urban_Development",
"boats",
"deoxymod",
"blazemod",
"No_Fungi",
"more_classes_scenarios",
"no_reviving_zombies",
"StatsThroughSkills"

### Expected behavior
not to crash

### Actual behavior
crashes

### Steps to reproduce the behavior
attack NPC with metal weapon with electroshock unit turned on

**Comment by Night-Pryanik** [comment]
Can't reproduce on 0.C-7433, Windows XP SP3 x86, curses.

![default](https://user-images.githubusercontent.com/11132525/40583534-6a48a428-6199-11e8-8b9d-93f5145a99d2.png)

**Comment by ElonSatoshi** [comment]
What do you mean by 'bandit' NPCs? Does that mean it only crashes if you attack evil NPCs?

**Comment by Leland** [comment]
If it's real bandits, there's a part of a mission that spawns them

**Comment by kevingranade** [comment]
No confirmation after months.
