### ISSUE TITLE
Allow tab key to cause the PC to wait for a monster to come into attack range

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#23830]
Game version: 0.C-27943-g56bbaf0 (tiles)

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: (Default)

### Expected/Suggested behavior
- Option 1 (Suggested)
Why not default the tab key when pressed to just cause the pc to wait till a hostile monster gets in range and then attack?

- Option 2 (Tolerable Alternative)
Use tab to advance player towards a hostile monster and then attack a monster if it is in range.

### Actual behavior
- Tab key hit when a monster is out of range reminds the player the monster is reallio trullio out of range.
- Player feels dumb for hitting tab too early.
- Player holds the wait button till the monster comes in range.
- Player holds the wait button for too long and monsters dominate player.
- Player feels sad :'(

**Comment by FulcrumA** [comment]
I'd claim that's player's fault. I never had a problem with just getting close to the monster and then pressing numepad 5 a few times.

**Comment by RogueYun** [comment]
Though I can see your argument and I may have exaggerated the idea of there being an issue for entertainment purposes, there are other roguelike games (Like ADOM and Dungeon Crawl) that have a similar feature. I also don't have a numpad and find it quite tedious to go between tab, period, and vi keys. It would be nice just to have tab and vi keys without having to add an extra bounce between period.
