### ISSUE TITLE
Single key press to clear search filters

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#23859]
Game version: 0.C-27943-g56bbaf0 (tiles)

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: (Default)

### Expected/Suggested behavior
Pressing backspace once (or maybe using an alternative like the delete key?) to clear a search/filter would be nice. 

#### SideNote: 
Outside CataDDA I usually use Shift + Home > Backspace/Delete to clear a search filter. In game Shift + Home just moves the cursor to the front of the search bar, but Shift + Home adds extra awkward key strokes that I think are unnecessary. Usually when hitting backspace in the search filter in game you aren't trying to correct a mistake but you are trying to clear the filter.

### Why? What's the issue?
- Save the pinky some work!
- There is an large amount of searching done in this game, a lot of time and pinky strength is spent clearing prefilled search filters.
- Often you are searching for more than one component for a craft recipe and one search usually leads to other searches.
- Backspace has an awkward placement on the keyboard as it is generally used only when one makes a mistake when typing.
- Usually search querries in game aren't huge text documents, so clearing the whole filter with backspace (even if not desired) shouldn't be awful. Again though, if backspace is too much of a sacrifice, the delete key is a good viable alternative.

### Why not suggest defaulting to empty search filters?
- I think someone has the search filters filled with last search for a reason. Maybe moving certain volume intensive items with the advanced inventory menu. I don't think it's a good enough reason, but it is still a reason and I'd be more okay with it if I have an alternative way of dealing with the prefilled search bar quickly.

**Comment by vschule** [comment]
Is there a search interface that "r" doesn't reset? Maybe the issue is that "R" isn't that good of a key to reset a search interface.

**Comment by BevapDin** [comment]
Having backspace clear the *whole* input will be very unexpected for almost all users, and it will annoy them to no end.

**Comment by RogueYun** [comment]
> Is there a search interface that "r" doesn't reset? Maybe the issue is that "R" isn't that good of a key to reset a search interface.

Nope, R's fine by me. I just didn't know of it's existence till now. Closing because for me there is no longer an issue.
