### ISSUE TITLE
Professions with pre-defined traits bypass the trait point limit on character creation

### ISSUE THREAD

**Issue by papersplease** [CleverRaven/Cataclysm-DDA#23851]
Game version: 0.C-27955-g7f74413

Operating system: Windows 7

Tiles or curses: tiles

Mods active: none

### Expected behavior
The player should not be allowed to spend more than 12 positive or negative trait points on the character creation screen. (or another value configured in Options/Debug).

### Actual behavior
Switching to professions with pre-defined traits bypasses the limit.

### Steps to reproduce the behavior
On a character creation screen, select your traits to hit the limit of 12 positive trait points, balancing them with negative ones. Switch to a Traceur profession. You now have 14/12 trait points because this profession mandates the Parkour Expert trait which costs 2 points, and the game doesn't check if the limit has been reached.

**Comment by John-Candlebury** [comment]
I think this is intended, and it's the display that needs adjusting

**Comment by papersplease** [comment]
@John-Candlebury When trying to do it the other way around (select a profession first, choose traits afterwards), the game doesn't allow the player to spend more than 12 points, enforcing the limit. Either this behavior is intended or another one, but probably not both I guess.

**Comment by Night-Pryanik** [comment]
Seems like I can't reproduce using your method:
- I spent 12 points on traits;
- got Traceur, got PE, got 14/12 points;
- switched to another profession, removed PE, got 12/12 points.

**Comment by papersplease** [comment]
@Night-Pryanik Yes, you get your 12 points back after removing it, but the overall "Points left:" counter on the top is also increased by 2 points. Voila, you have free 2 points you can spend on anything else.

**Comment by Night-Pryanik** [comment]
I think resetting all traits and recalculating all points left on profession change will solve the issue, but it looks like an overkill.
