### ISSUE TITLE
Feature request - Zoom for text

### ISSUE THREAD

**Issue by Parahacker** [CleverRaven/Cataclysm-DDA#23863]
Game version: experimental 7426

Operating system: Win 10

Tiles or curses: Tiles

Mods active: All of them that are bundled; except Dino mod, generic guns, and the balancing mods except for the default (filthy clothes etc.)

### Feature Request

While 'Fullscreen' has the option to scale everything, windowed does not. On my screen that makes windowed impossible to read; the text is too small, so I have to use fullscreen. That wouldn't be a problem except fullscreen CTD's if I switch to another program or my desktop.

While fixing the CTD would resolve my own problems, having a zoom function for windowed format would be a nice feature in and of itself.

**Comment by Parahacker** [comment]
This has become urgent - there's simply no way for me to be able to read this game on my computer no matter what I do. After a recent Windows update that fussed with display settings, even Fullscreen now no longer zooms in regardless of settings tried. Without a text-zoom (and menu boxes I assume) function of this sort, CDDA is unplayable and it makes me sad :(

**Comment by Parahacker** [comment]
Is there a config file setting or something I can use to do something about this? What's involved in the process of making text/menus big enough to be readable?

**Comment by BevapDin** [comment]
You can edit "config/fonts.json" and change the font size (and width and height) there.

**Comment by Parahacker** [comment]
That worked! So happy, actually I went to IRC and someone told me about this... as a suggestion, add this tip to the help files/tutorials? It's such an easy fix but without knowing how I was about to just chuck the program! Solved :)

**Comment by Night-Pryanik** [comment]
Could be closed then?
