### ISSUE TITLE
Smart camera while moving

### ISSUE THREAD

**Issue by rumly111** [CleverRaven/Cataclysm-DDA#23864]
I recommend implementing a new feature which affects camera focus while moving.
How will it work? In the settings, there will be a new value, let's call it "smart camera threshold", and let's assume it's value is 5. The character starts moving to the left, but while it moves, the camera focus also shifts to the left by 1. After moving to left 4 more times, the camera also shifts left 4 more times (it's the maximum shift). Why? When moving around, I often find myself stopping and shifting around my camera just to explore the surrounding area. Mostly I look for hostile monsters in front of me (In the direction I'm moving), so it's logical if the camera prioritizes the area in front of the character. I can do it manually, of course, but if it was done automatically, it would save a lot of key presses. While looking for zombies "in front of me", it's safe to lessen my attention "behind me", so shifting the camera focus makes perfect sense.

Let's say after moving to the left >=5 times, I want to turn back, because I saw a lot of enemies. I start moving to the right (retreating). This time, the camera focus will also shift to the right by 1, so we can say the camera and character relative position will be (-4, 0). I go to right again - (-3, 0). After 5 turns the camera will be centered. Why this behavior, and not center the camera immediately after changing direction? While you are retreating, don't you want to keep an eye on your enemies? And if you want to center the camera anyway, there is a key control for that.

Let's talk about another scenario. You are moving to left for a while, naturally your camera shift is (-5, 0). Then you change course "north-west" (left and up), the camera shift will become (-5,1), (-5,2), (-5,3), (-5,4) then (-5,5) after each step. What if after moving to left you turn up instead of left+up ? The camera shift will be (-4,1), (-3,2), (-2,3), (-1,4), (0,5).

I hope you grasp the general idea and my reasons behind it. Slowly shifting the relative camera position, depending on the character's movement direction. And if the player wants to manually set the camera position, there are already controls for it in game. If the user wants to disable this behavior, he naturally sets this option to 0.

**Comment by rumly111** [comment]
This option can also be "0.5" etc, meaning the camera shifts every 2 steps.

**Comment by papersplease** [comment]
View shifting is already implemented in the game, it's just velocity-dependent so it only noticeable when driving a car.

> Mostly I look for hostile monsters in front of me (In the direction I'm moving), so it's logical if the camera prioritizes the area in front of the character.
What if you're moving chaotically inside a city, surrounded by zombies from all sides? What does this solve that existing tools (minimap, creature locator, safe mode) can't?

**Comment by rumly111** [comment]
> View shifting is already implemented in the game, it's just velocity-dependent so it's only noticeable when driving a car.
Haha, I actually had no idea, because I never rode a car in the game.

> What if you're moving chaotically inside a city, surrounded by zombies from all sides? What does this solve that existing tools (minimap, creature locator, safe mode) can't?
I was talking more about exploring, when you have to be careful not to jump a horde of zombies. I noticed about 1/3 of my actions are looking around the map. Safe mode is another story, sometimes it annoys me and I turn it off.
So if view shifting is available in cars, that's cool. But I want it while walking. As for the minimap, I don't like staring at it. Instead of colorful dots, I prefer looking at the tiles. Creature locator? I didn't encounter those.

**Comment by FulcrumA** [comment]
I am pretty sure you can adjust such thing manually by having your view move in some direction relative tot he character, though I cannot recall the key shortcut for it right now.
I would be for making velocity tresholds that move the view during movement adjustable so if someone wants to, their view may slightly tilt even when they're on foot but I'd be against making it a default thing as whether it'd help with exploration is a very subjective thing - I, for one, prefer to have my character in the center of the screen at all times when I am on foot, to be able to maintain the same view in every direction when searching for loot or preparing for enemies, using 'x' to see further as necessary.

**Comment by kevingranade** [comment]
Implementation note:
Each time the player moves, insert the new location in a queue.
At the end of a turn when the player did not move, also insert the current location.
If a "shift view while walking" option is enabled, calculate a vector based on the front() vs back() of this vector and apply it as a screen offset.
