### ISSUE TITLE
http://gorgon.narc.ro:8080 is down

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#23865]
Pinging @narc0tiq.

**Comment by narc0tiq** [comment]
I was warned of some upcoming maintenance to the underlying VM host for some bad hardware fixing, but hadn't heard anything further. I'm currently in Austria, well away from any reasonable keyboard, but expect things to start working again soon, no specific time expected.

**Comment by ZhilkinSerg** [comment]
Thanks.

**Comment by BorkBorkGoesTheCode** [comment]
@kevingranade the discourse is in read-only mode for some reason. @narc0tiq how are you?

**Comment by JazzGuru** [comment]
Thanks for getting things back up and running.  Time to PWN some zombies... :dagger:

**Comment by ZhilkinSerg** [comment]
Thanks a lot!

http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/7434/ now has pretty big changelog. :)
