### ISSUE TITLE
Error when I Take off something and it drop to the floor

### ISSUE THREAD

**Issue by pierredavidbelanger** [CleverRaven/Cataclysm-DDA#23866]
### Game version:

Unmodified source code up to [this commit](91a1db0b3205dc4cf5d6d7a76518d9aec4dcb2d1)

### Operating system:

```
$ uname -a
Darwin MacBook-Pro-de-Pierre-David.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
```

### Tiles or curses:

```
$ make app -j4 NATIVE=osx OSX_MIN=10.13 TILES=1 SOUND=0 LOCALIZE=0 RELEASE=1 CLANG=clang++ MACPORTS=1 USE_HOME_DIR=1
```

### Mods active:

None

### Actual behavior

<img width="713" alt="cataclysm__dark_days_ahead_-_0_c-27990-g91a1db0" src="https://user-images.githubusercontent.com/1076726/40587228-562366bc-619a-11e8-8c32-11b5c0c5c41c.png">

### Steps to reproduce the behavior

Fill your inventory and try to `T`ake off something you are wearing so it drop to the floor.

**Comment by budg3** [comment]
Same issue as in #23586
