### ISSUE TITLE
More readable json

### ISSUE THREAD

**Issue by Clyybber** [CleverRaven/Cataclysm-DDA#23869]
The current Json formatting enforced by the formatter/linter collapses some objects and arrays to one liners that are less readable than when expanded to multiple lines.
A good example of this happening is #23774 .
One solution(may be crappy) would be to format those entries depending on the length(as in characters) of its childs.

**Comment by kevingranade** [comment]
It already does format based on child length, if a line would be longer than the configured line size, it unwraps it.
I've been trying to think of a more nuanced approach, but I dont have anything usable.

**Comment by kevingranade** [comment]
Unless theres a concrete suggestion for improving the status quo, theres no value keeping this around.
