### ISSUE TITLE
NPCs store guns in their bellybuttons, attempts to pull out crash the game

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23874]
Game version: 0.C-27987

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Upon running out of ammo, NPCs switch to a better weapon or if they don't have any, use their rifles as clubs, unless their unarmed ability (taking into consideration known martial arts), to-hit and damage is higher. Either way, their guns can be taken from them.

### Actual behavior

![uhoh](https://user-images.githubusercontent.com/38487938/40609283-740f8302-626e-11e8-8739-8072cd60bffe.png)

NPCs running out of ammo and switching to unarmed fighting, even those who have no carrying capacity, will put their guns (even those without straps) in the torso slot. Attempts to make them drop those guns using Sort Armor menu crash the game.

### Steps to reproduce the behavior
Give an NPC a rifle and some ammo, have it use up the latter but still have an enemy to approach to fight in melee. Afterwards, marvel at the NPC's feat of managing to store their rifle in their, presumably, belly button (unless it's the ability of swallowing huge objects whole with no impact on their health or mobility). Attempt to pull the rifle out. Realize that even the game cannot handle sillyness of this proportion.

**Comment by Theundyingcode** [comment]
I see no problem with stashing: [https://www.youtube.com/watch?v=EzPp9Y8Krhg](url)

**Comment by FulcrumA** [comment]
True that, but even if my companions all possess considerable flesh folds for emergency item storage or predilection toward putting of all kinds of things into their other body cavities, their storage capacity is still listed as 0,00 volume on the screen and any attempts to extract, say, machineguns from their various holes crash the game!

**Comment by Theundyingcode** [comment]
> y attempts to extract, say, machineguns from their various holes crash the game!

Yes, crashing is a problem.   0 volume is also correct, folds and holes should work like sheiths holding a specific item or possibly item(s).
