### ISSUE TITLE
World Eating Bug

### ISSUE THREAD

**Issue by Daedracian** [CleverRaven/Cataclysm-DDA#23879]
Game version:  0.C-27947-g08aa094 Build 7426

Operating system:  Windows 10

Tiles or curses:  tiles

Mods active:  these were from the mods file of the world as interpeted by notepad
[  
"dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "bio_mod",
  "FIC_Weapons",
  "realguns",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "npc_traits",
  "deoxymod",
  "blazemod",
  "Tanks"
]

### Expected behavior
continue working
### Actual behavior
stopped working world no longer playable
### Steps to reproduce the behavior
spawn autonomous tank with uranium plating and have it shoot several rounds at zombies
it said something about an artifact when i thought it wasn't eating my world and appaered as a regular bug

also have photos but am uncertain on how to post them

**Comment by Leland** [comment]
> spawn autonomous tank with uranium plating and have it shoot several rounds at zombies

Does the world eating bug happen every time you do this? Have you seen this bug happen more than once?

**Comment by Daedracian** [comment]
No I have a lot of other from what I could tell harmless that may remove an item but never like this I can’t even load the world anymore 
		
		

		Get Outlook for iOS
	




On Mon, May 28, 2018 at 9:34 AM -0600, "Leland Clemmons" <notifications@github.com> wrote:













spawn autonomous tank with uranium plating and have it shoot several rounds at zombies



Does the world eating bug happen every time you do this? Have you seen this bug happen more than once?

**Comment by YakumoChen** [comment]
I had a crash earlier when I was nearby a tank drone, might be related

**Comment by LyleSY** [comment]
I spent some time trying to get a tester together but I'm running into some issues. bio_mod is obsolete now, though I don't see what that would have to do with tanks. I don't see any vehicle or monster called "autonomous tank with uranium plating" with those mods enabled. Any chance this is something custom, or it has another name?

**Comment by kevingranade** [comment]
No ability to reproduce and no ability to get further details about the issue.  Please post here if you have any further information.
