### ISSUE TITLE
Blinking Indicators

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#23888]
Game version: 0.C-27943-g56bbaf0 (tiles)

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: (Default)

### Expected/Suggested behavior
- Convert the R from W/R (Walk/Run indicator) to have a blinking trait. When running changes from the default white "R" to it's inverted form. Though I'd rather it were the whole word, "RUN" as it is (to me) a pretty vital thing to be aware of.
- As mentioned below, an indicator that would blink to inform the player that he is grabbed would be nice.

Possibly some other important indicators (though not as important in my opinion):
- Have blinking "Bitten", "Infected", "Bleeding", etc. indicator on the appropriate body part (eg. HEAD, flashes between red text and red background when bleeding, etc.) 
- Maybe for when you are near to starving/dehydrating yourself to death.
- I also wouldn't mind an indicator that blinked whenever a hostile enemy was in view, but as usually there is a hostile enemy in view... this one might just throw people off (too many squeaky wheels and no one gets the oil, or if everything is blinking it is more likely everything will be ignored).

### Why?
- It's hard to tell if and when you are running. This has killed some of my best characters.
- It would be nice to have a little extra friendly neighborhood player alert system.

**Comment by Theundyingcode** [comment]
I always wanted the sidebar to just tell me my move speed especially since I use skates a lot.

**Comment by RogueYun** [comment]
> This is especially true for "dextrous" melee fighters and the Grabbed effect which is extremely important for dodging

Very true! I forgot about that one, I'll edit the original post.

**Comment by RogueYun** [comment]
@Leland 
>>  I also wouldn't mind an indicator that blinked whenever a hostile enemy was in view
>
> We have the alert system for this, which accomplishes the warning indicator. In addition, the minimap (which does indeed blink) and the color-coded enemy list do the same.

I only brought it up because I would like one. I actually never use the new mini-map so you'll have to beg my pardon if I don't quite follow you. I found that the mini map usually looked pretty much like my game screen anyway and I don't tend to use it. https://i.imgur.com/SkmVeTy.png

I feel like it would divide my eyes between two screens when a blinking indicator in the corner of my eye could tell me everything I needed to know without looking. Yes, I'm _that_ lazy.

Again though, I'd prefer it to be option based just in case. 

Though this is all just a castle in the air for me. I am too doubtful of my skills to make the change myself. I just try to keep devs informed of my thoughts and opinions on what a player that sinks way too many hours into their game thinks. (And hope they don't mind too much).

>> Maybe for when you are near to starving/dehydrating yourself to death.
>
>Now this I could potentially see as being a use case for a blinking alert
>
>> Have blinking "Bitten", "Infected", "Bleeding", etc. indicator on the appropriate body part (eg. HEAD, flashes between red text and red >> background when bleeding, etc.)
>
> We already use color-coded indicators for these, as well as a notice in the log when bitten/infected actions occur. IMO, it's not something that needs a flashing, constant indicator.

I agree! I was just trying to brainstorm.

@Theundyingcode 
> I always wanted the sidebar to just tell me my move speed especially since I use skates a lot. 
I actually did some speed tests with skates and roller skates once. I thought it would be cool if the game had an in game stop watch that could help you determine your speed. Was just a thought though because I finished my tests and didn't care after that.

**Comment by papersplease** [comment]
There are at least two major problems with blinking:

- it's really annoying
- the blinking is either much slower than the turn rate for an experienced player (= easy to miss), or even more annoying 

A different sidebar layout with UI grouped/sorted by immediate importance and indicator sizes scaled accordingly would be much nicer IMO.

Regarding the grab indicator: keep in mind it's just one of the many possible effects; the player can also be downed, poisoned, smoked etc. (although the grabbing is probably both easiest to miss and most immediately important)

**Comment by RogueYun** [comment]
You've got me convinced, but since that would make us in duplication of #20969, I think we better close this one and just suggest the old one be reopened.
