### ISSUE TITLE
Improving Sound Markers

### ISSUE THREAD

**Issue by PipePainter** [CleverRaven/Cataclysm-DDA#23886]
Currently examining a sound marker just tells you 'you heard a noise from here' without telling you what that noise was. Footsteps, zombies bashing on furniture, brushing through trees, hitting vehicles, all yield the same message. Even though they should be much more distinct than that.

There are exceptions, but only for things with associated messages in the text log. Glass breaking, explosions, building collapses, etc. Not being able to recognize more distant, quiet sounds makes a bit more sense, but closer sounds should be identifiable. This could even be tied to traits that improve/weaken hearing, allowing you identify sounds from further way and with greater accuracy.

Secondly, sound markers currently stop appearing when their source is within your view. This is usually fine, but this happens even if you can't see the source. You should be able to get a rough idea of where an invisible enemy is by the sound it generates as it moves, without having to blindfold yourself.

**Comment by Theundyingcode** [comment]
> Secondly, sound markers currently stop appearing when their source is within your view. 

This is a good thing.  The message log should display useful information; if I use a vehicle to filter the horde i'm fighting, the sounds of them smashing through it are just clutter.

**Comment by kevingranade** [comment]
I need you to split this into two issues, each issue needs to address one thing.

**Comment by PipePainter** [comment]
Can do. I'll split one and post it as 'Non-descriptive sound markers' and the over half as 'Invisible creatures don't creature sound markers'
