### ISSUE TITLE
Title UI Interaction

### ISSUE THREAD

**Issue by Daedracian** [CleverRaven/Cataclysm-DDA#23885]
Game version:  0.C-27990-g91a1db0  Build 7433

Operating system: Windows 10

Tiles or curses: tiles

Mods active: not used

### Expected behavior
to interact with title screen
### Actual behavior
interacting with files on desktop
### Steps to reproduce the behavior
Double shortcut for cdda click background of desktop then press arrow keys to interact should cause a description of of the item you have selected to appear click cdda to interact with it

launching with cdda launcher solves issue

i was able to reproduce this 2 more times after it happened the first time to confirm it is reproduce able

**Comment by searker** [comment]
To clarify: You start cdda and afterwards click onto your desktop / outside of the game-window?

If so, the behaviour you describe is normal for Windows.
Once you click outside of a window (not just cdda), it looses focus and the clicked window (or Desktop, if no window was clicked) gains focus. This leads to all further inputs affecting the newly clicked window.

However, i do not understand how the Launcher prevents that on your end. All it basically does (after updating, backing up, etc.) is start cdda in a similar way as if you started it directly.

Can you clarify that clicking outside of cdda once the window appears and was started via the Launcher does NOT prevent you from using the menu (without clicking back into the game-window)?

**Comment by Daedracian** [comment]
I created a shortcut then I double click the shortcut click background to get rid of the shortcut being highlighted cdda starts up fine in full screen but when I use keyboard to interact it interacts with items on desktop if I then click the cdda title screen I can interact with it using the launcher prevents this from happening

**Comment by Zireael07** [comment]
You clicked background, it means cdda doesn't have focus when it starts.

Using the launcher prevents it since obviously it launches the game without you clicking away from it.
