### ISSUE TITLE
Creatures travel up sheer z-levels, regardless of flight or climb ability

### ISSUE THREAD

**Issue by rob-a-bolton** [CleverRaven/Cataclysm-DDA#23883]
**Game version:**
0.C-27992-g00927f2250
**Operating system:**
Linux, amd64 Debian 9
**Tiles or curses:**
Tiles
**Mods active:**
[
"dda",
"filthy_morale",
"no_npc_food",
"novitamins"
]
### Expected behavior
With a z-level enabled world, creatures should not pursue the player up z-levels without using ladders/stairs or being a CLIMB or FLY creature.
### Actual behavior
Creatures ignore z-levels and may move from e.g. sidewalk outside a building directly up onto the roof, or through a window.
### Steps to reproduce the behavior
Create a world with z-level support turned on, find (or spawn) a creature on the ground floor, and climb up onto a roof.

**Comment by BorkBorkGoesTheCode** [comment]
Monsters also see and attack the player using ranged attacks even if they are 1+ below player level and behind a wall.

**Comment by budg3** [comment]
@BorkBorkGoesTheCode 
Isn't that only with 3D vision enabled?
