### ISSUE TITLE
Creating the character from a saved preset prevents re-distributing points properly

### ISSUE THREAD

**Issue by papersplease** [CleverRaven/Cataclysm-DDA#23894]
Game version: 0.C-27990-g91a1db0

Operating system: Windows 7

Tiles or curses: tiles

Mods active: none

### Expected behavior
After loading a previously saved preset into a character creation screen, the player should be able to redistribute any points arbitrarily.

### Actual behavior
If less than maximum trait points are selected in the preset, it's not possible to spend more than this value after loading the preset.

### Steps to reproduce the behavior
- save a preset with less than 12 positive trait points spent
- load it again
- try to enable any new positive trait, balancing it by reducing the skills by its cost

The game won't allow you to do that, displaying the point counter in red, although it's clearly possible when creating a fully custom character instead of a preset-based one.

### Alternative way to reproduce, with stat and skill pool
- make a balanced character
- borrow some points from the stats pool into another pool (exchange one strength point for some trait or a skill, for example)
- save, then load a character preset
- try to undo the borrow in step 2, discarding that trait/skill and reclaiming the strength point.

**Comment by RogueYun** [comment]
I think this is intentional, mine pops up with a warning: https://i.imgur.com/5iIn7Je.png

If you know the point difference you can go to the points tab you can put it on freeform and fix any corrections that you would like to make then save again.

**Comment by papersplease** [comment]
@RogueYun It works as described in the OP even if you spend all the points though, that warning is something unrelated to the bug.

Upon loading a preset, the multi-pool counter on the top shows 0+0+0=0, instead of a proper formula. It probably has something to do with this. (and I keep freeform turned off in world settings anyway, forcing it to multi-pool only)

**Comment by RogueYun** [comment]
Isn't 0+0+0 = 0 the proper formula? Or are you expecting if you put 11 points into STR and then saving > loading preset of getting something like 3+0+2 = 5 ? I think the warning is just telling you that those 5 points won't be saved with the preset template and that you should use them. I "think" that it was on purpose. Maybe so someone can make a custom scenario for a friend? Maybe so that it doesn't conflict with different stat pooling systems? Whatever the purpose, I think it was intentional. I'm cool if someone wants to change it though. It would be nice if presets remembered unspent points.

**Comment by papersplease** [comment]
> Isn't 0+0+0 = 0 the proper formula?
Only if you spend all the points and balance all traits. That's a pool indicator. If you borrow one skill point from the stats pool, it will read 1+0-1=0, for example. Upon loading such preset though, it will be 0+0+0=0 again, losing the information about that borrowing.

>Whatever the purpose, I think it was intentional.
I doubt so because the only difference between being able to redistribute any points you have and not being able to do so, is having the preset loaded. That's just inconsistent behavior I guess, and that would be a bizarre/obscure way to intentionally limit something.
