### ISSUE TITLE
Grabbed effect doesn't get cleared on grabber death

### ISSUE THREAD

**Issue by papersplease** [CleverRaven/Cataclysm-DDA#23899]
Game version: 0.C-27990-g91a1db0

Operating system: Windows 7

Tiles or curses: tiles

Mods active: none

### Expected behavior
The character stops being "grabbed" when the zombie that grabbed him/her has died.

### Actual behavior
If another creature displaces the dead one immediately, the player is still grabbed in the same way as before.

### Steps to reproduce the behavior
- Find a large zombie crowd.
- kite them in a 1 tile wide corridor to make them approach in a queue
- wait for the front one to grab you
- kill it, making the second one fill the place in the same turn
- repeat, as you find yourself grabbed without new zombies really trying to grab you again

(the steps described above are easy to do in a Fled the Riots scenario, starting in a shopping mall - there's plenty of 1-tile back corridors and default zombies)

Here's an illustration: 
![cataclysm-tiles_2018-05-30_01-24-29](https://user-images.githubusercontent.com/791891/40688847-5e0f3bde-63a8-11e8-8f8d-72b6957dc2b4.png)

As you can see, the first zombie grabbed me, then I killed it. A second one replaced it immediately, and I'm somehow instantly grabbed by it despite the first one being dead.

No idea if this is intentional, but I guess the new zombie should pass a new check against the player's dodge to be able to grab him again.

**Comment by RogueYun** [comment]
Is this by chance related to issue #17439?

**Comment by papersplease** [comment]
Yep, looks like a dupe.
