### ISSUE TITLE
Chloromorphosis mutation is not working correctly.

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#23897]
Game version:
0.C-27990-g91a1db0
Operating system:
Windows 10, Windows 7
Tiles or curses:
Tiles
Mods active:
  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "craftgp",
  "brightnights",
  "realguns",
  "More_Survival_Tools",
  "bio_mod",
  "makeshift",
  "Mining_Mod",
  "mutant_npcs",
  "crazy_cataclysm",
  "npc_traits",
  "more_buildings",
  "more_locations",
  "Urban_Development",
  "boats",
  "blazemod",
  "deoxymod",
  "Tanks",
  "more_classes_scenarios",
  "StatsThroughSkills"
### Expected behavior
Character with "Chloromorphosis" mutation satisfies any hunger or thirst he/she might have when sleeping on the diggable terrain.
### Actual behavior
Character with "Chloromorphosis" doesn't replenish quench and nutrition when sleeping despite log message about using roots on the soil. Waiting or reading on the diggable terrain works as intended.
### Steps to reproduce the behavior
Get "Roots", "Leaves", "Saprophage  and "Chloromorphosis" mutations, then try to sleep on the dirt.

**Comment by KorGgenT** [comment]
so here's a proposal for this: when you absorb nutrients from the soil, it acts like "you just ate" but doesn't fill your stomach, so you'd just have to deal with hunger pangs as your stomach still exists.
