### ISSUE TITLE
Time to complete for crafting/construction is always "for ever"

### ISSUE THREAD

**Issue by budg3** [CleverRaven/Cataclysm-DDA#23904]
Game version:
master at  5ec443b (18-05-30)

Operating system:
WinXP

Tiles or curses:
Tiles

Mods active:
Default

### Expected behavior
Shows the actual time to complete crafting/construction
### Actual behavior
![cdda-crafting-bug](https://user-images.githubusercontent.com/15700356/40740096-6de499b6-6437-11e8-953e-2204232fcec0.PNG)
### Steps to reproduce the behavior
Open the crafting or construction menu

**Notes:**
Searching for "for ever" in the source and comparing it with an older version (7426) without this problem leads me to [this](https://github.com/CleverRaven/Cataclysm-DDA/blob/5ec443b94f03f37baacac7c3612f4ea342887c8e/src/calendar.cpp#L327). The actual time to craft the item works as intended though, only the UI says it will take "for ever".

**Comment by DracoGriffin** [comment]
What was your morale at for the screenshot, in consideration of #23299 ?

**Comment by budg3** [comment]
+66 but I also tried it with a new character at the starting morale with the same results.

**Comment by budg3** [comment]
Possible cause: [Change code in to_string(time_duration) to use time_duration functions](https://github.com/CleverRaven/Cataclysm-DDA/commit/5fb154f993b1cb8d79880b7f81daa7c8e1b235cb)

**Comment by AMurkin** [comment]
Probably wrong sign: < instead of >.
