### ISSUE TITLE
Error when aiming a turret via a remote vehicle controller: "Tried to aim turret while outside vehicle"

### ISSUE THREAD

**Issue by ChucklesTheBeard** [CleverRaven/Cataclysm-DDA#23902]
Game version: f4ade2c9098b6067f456a36c7e7def488ed0fc6c

Operating system: Linux

Tiles or curses: Tiles

Mods active:
More Survival Tools
blazemod
Tanks and Other Vehicles
Boats
Folding Parts pack
Disable NPC Needs
Simplified Nutrition

### Expected behavior
Users should be able to remotely aim a turret without errors popping up.

### Actual behavior
This error pops up upon selecting the turret.
https://github.com/CleverRaven/Cataclysm-DDA/blob/f4ade2c9098b6067f456a36c7e7def488ed0fc6c/src/ranged.cpp#L771

Also, there's a minor visual bug in the aiming dialog after the error pops up if the user opts to "continue": https://imgur.com/K9Ctugs This goes away if the user stops aiming and restarts aiming again.

### Steps to reproduce the behavior
1. Build a vehicle with drive by wire controls, a turret mount, and a mounted gun (the specific gun shouldn't matter, tried with M249 and Mark 19 Grenade Launcher).
2. Obtain a remote vehicle controller (or a Remote Controller CBM).
3. Remote control the vehicle.
4. Attempt to manually aim the turret.

Probably related: #22512

**Comment by FulcrumA** [comment]
Possibly it should depend on the turret. There are manual turrets which presumably are non-automized guns requiring someone grabbing onto them with their very hands and which shouldn't function any other way and automatic turrets which should be controllable manually through remote controller.

**Comment by thethunderhawk** [comment]
I observed this too.

@FulcrumA manual turrets can be fired from any tile with vehicle controls, drive by wire controls are described as a set of normal controls with remote operated servos attached, IMO that means from a consistency standpoint you ought to be able to use turrets from outside the vehicle given a remote vehicle controller. 
Especially true since you can already fire the turrets from anywhere inside the vehicle using the RVC, regardless of distance from the controls themselves.

**Comment by swofle** [comment]
FYI, current implementation does not check if player is in the vehicle that the turret is installed in. As long as I am in a vehicle, I can remote control turret of another vehicle just fine. 

>https://github.com/CleverRaven/Cataclysm-DDA/blob/fa768a0c441f497c8b3c6f726c43d8a13fed7a80/src/ranged.cpp#L817-L819

Not sure why we would need to have this check in the first place. Perhaps someone can explain the intended design?

**Comment by swofle** [comment]
FYI, it is possible to workaround this by standing on any other vehicle and fire the turret remotely. The game will not be able to draw the aim line, but you can fire your turret remotely just fine.

**Comment by CoroNaut** [comment]
You can also generate this error just by standing beside the vehicle in question when trying to aim automatic turrets.
