### ISSUE TITLE
Soundpacks Expansion

### ISSUE THREAD

**Issue by budg3** [CleverRaven/Cataclysm-DDA#23909]
Currently the game only supports a limited set of sound effects for soundpacks. I would however like to see the soundpack support become as good as the tileset support.

From what I understand there are currently three methods of playing sounds implemented:
1. Looping music from a playlist.
2. Looping ambient SFX that changes depending on the weather/location etc.
3. SFX that plays once when triggered by some action (also supports positional sounds).

I'm not familiar enough with both C++ and SDL_mixer to implement this, but an expansion of number 3 that allows those sounds to loop as well would be useful for vehicle and fire SFX for example.

At the moment it seems that most SFX are implemented by placing `sfx::play_variant_sound( sfx_id, sfx_variant, sfx::get_heard_volume( pos ) );` at the part of the codebase that controls a specific action. This makes the SFX scattered all over the place and adding support for new sounds requires you to gain arcane knowledge of where every action (that ought to produce sound effects) is located in the codebase.

Another method of easily adding SFX support to existing and possibly future actions, would be preferred. I'm rather new to programming so I'm not sure how to go about this, but perhaps something that checks the message log instead and applies SFX that way. Any other suggestions are welcome.

**Comment by kevingranade** [comment]
There is literally no other way to do it.  No matter what kind of system you add, it boils down to making a function or method call at that point in the code that includes enough information to decide what sound to play with what parameters.

That function can either be sound specific and only change when you want to change how sounds are played, or it can be shoehorned into the message log and get changed based on someone deciding to change something about printing messages.

**Comment by budg3** [comment]
It would be helpful if you guys can help listing things that should be able to play sound effects. I've made a small list so far, that I'll add more to as I notice things that should have SFX.

- Monster special attacks (shrieking, acid spitting, boomer bile etc)
- More monster hurt/death sounds than just generic ones for zombies
- Pulping/butchering
- Vomiting
- Digging
- Vehicle sounds (start, stop, driving loop, doors, honking, stereo etc)
- Fire burning loop
- Mp3 player
- Crafting/construction
- Eating/drinking

**Comment by AMurkin** [comment]
Footsteps on different surfaces.
CBM events.

**Comment by kevingranade** [comment]
Mostly a Q/A issue which has been answered.
