### ISSUE TITLE
Ranged weapon dispersion UI doesn't do math

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#23901]
Game version:
0.C-27987
Operating system:
windows 10
Tiles or curses:
tiles
### Expected behavior
Dispersion 32+60=92
### Actual behavior
Dispersion 32+60=36

Firestorm didn't cause it. It's from the aftermath of the last ranged balance.

**Comment by Brambor** [comment]
Yeah it is wierd and happens not only there but in item description as well. Sometimes there is **60+-12=35** or something  like that...

**Comment by AMurkin** [comment]
Should be closed?

**Comment by DracoGriffin** [comment]
Closing. If the issue still persists after the fix in #24443, we can re-open this issue.
