### ISSUE TITLE
Solar Flashlights are categorized as Artifacts

### ISSUE THREAD

**Issue by PipePainter** [CleverRaven/Cataclysm-DDA#23912]
Game version: 7,644

Operating system: Windows 8

Tiles or curses: Tiles

Mods active: Cataclysm++, Mining Mod, More Survival Tools, Classic Roguelike Classes, StatsThroughSkills, Vehicle Additions Pack, Tanks and Other Vehicles, Urban Development, ZSFIXED_C:DDA Extra Professions, Boats, Folding Parts pack, Extended Buildings, Filthy Clothing, Makeshift items mod, more buildings, Classes and Scenarios mod, prevent zombie revivication, simplified nutrition, extended realistic guns, NPC traits, More Locations, and Tall Buildings.

Expected behavior
For the Solar Flashlight to be classified as a 'Tool'

Actual behavior
The Solar Flashlight is classified as an Artifact.

Steps to reproduce the behavior
Acquire a Solar flashlight, and examine it. In your inventory or otherwise.

**Comment by PipePainter** [comment]
The Solar Torches you can make from blob parts are also classified in this manner. Whether one, or both of them are supposed to be I do not know.

**Comment by NotFuji** [comment]
The Solar Flashlight is from **Cataclysm++**, not mainline.  Probably best to ask about the issue on the Discourse or the mod's git.

https://discourse.cataclysmdda.org/t/cataclysm-mod/10523
https://github.com/Noctifer-de-Mortem/nocts_cata_mod

**Comment by PipePainter** [comment]
Ah, my apologies. With so many items its hard to keep track of which is from what. I'll migrate the ticket to the mod's github in that case.
