### ISSUE TITLE
windows defender (anti-virus) reports latest windows tiles build as containing a trojan

### ISSUE THREAD

**Issue by pipehat** [CleverRaven/Cataclysm-DDA#23913]
Game version:
http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/cataclysmdda-0.C-7433.zip

Operating system:
Windows 10

Tiles or curses:
tiles
http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/cataclysmdda-0.C-7433.zip

Mods active:
n/a

### Expected behavior
no trojan warnings

### Actual behavior
trojan warning
Trojan:Win32/Azden.B!cl
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fAzden.B!cl&threatid=2147723291

### Steps to reproduce the behavior
download build 7433 (link above)
wait a few minutes for Windows Defender scan to pick it up or right-click zip file an initiate manual scan

screenshot of windows defender trojan info warning attached:

![wut](https://user-images.githubusercontent.com/253436/40795770-539ebd26-6503-11e8-9c2c-d3f15c8990ac.png)

**Comment by StripedMonkey** [comment]
Does cdda even contain any networking functions?

**Comment by StripedMonkey** [comment]
It looks like (I'm a Linux guy so I could be wrong) that you are running the executable from the zip file, could you try extracting it and running/scanning the .exe in it's unextracted form?

**Comment by kevingranade** [comment]
Heuristic antivirus has false positives sometimes based on random happenstance, and there's nothing we can do about it.

**Comment by BorkBorkGoesTheCode** [comment]
@pipehat try scanning 7423 and see if there's still a problem

**Comment by pipehat** [comment]
7426, my prev version, is fine

also odd that there don't appear to be new builds for last several days at:
http://dev.narc.ro/cataclysm/jenkins-latest/Windows_x64/Tiles/
