### ISSUE TITLE
Strange messages for musical instruments

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#23915]
Messages from `player_descriptions` node from are displayed when player character plays on musical instruments with `You hear` prefix:

`You hear You play a beautiful piece.`

![image](https://user-images.githubusercontent.com/16213433/40800215-66445264-6518-11e8-9bcb-c3eae9d3ef08.png)

![image](https://user-images.githubusercontent.com/16213433/40800182-5091cc4e-6518-11e8-88cf-6e505149a947.png)

**Comment by Leland** [comment]
Duplicate of #17820

**Comment by ZhilkinSerg** [comment]
Thanks, somehow I didn't find it.
