### ISSUE TITLE
Invisible creatures stop generating sound markers when they enter your view.

### ISSUE THREAD

**Issue by PipePainter** [CleverRaven/Cataclysm-DDA#23910]
Split from issue #23886 
Game version: 7,433
Currently,  sound markers stop appearing when their source is within your view. This is usually fine, but this happens even if you can't see the source. You should be able to get a rough idea of where an invisible enemy is by the sound it generates as it moves, without having to blindfold yourself.

**Comment by Night-Pryanik** [comment]
Can't confirm. Tested on latest experimental as of 06 April 2019. Shady zombie is south-west from me (where the items are), is in my field of view, and is generating sound markers. Closing until confirmed.

![изображение](https://user-images.githubusercontent.com/11132525/55667989-68403600-5874-11e9-8399-50fe9a58304a.png)
