### ISSUE TITLE
Most sound markers lack descriptions

### ISSUE THREAD

**Issue by PipePainter** [CleverRaven/Cataclysm-DDA#23911]
Split from issue #23886 
Game version: 7,433
Currently examining a sound marker just tells you 'you heard a noise from here' without telling you what that noise was. Footsteps, zombies bashing on furniture, brushing through trees, hitting vehicles, all yield the same message. Even though they should be much more distinct than that. Heck, some of these have descriptions in the text log if they happen in your view, which their sound marker lacks.

There are exceptions, but they are few. Glass breaking, explosions, building collapses, etc. Not being able to recognize more distant, quiet sounds makes a bit more sense, but closer sounds should be identifiable.

**Comment by kevingranade** [comment]
I believe this is addressed now.
