### ISSUE TITLE
Bulk trade in refugee center with food broker should give you a price above normal.

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#23919]
Game version:
master
Operating system:
any
Tiles or curses:
any
Mods active:
any
### Expected behavior
Bulk trade should "Pay top dollar for jerky" as it is what the guy said and seems fit for the lore.

### Actual behavior
There are no price modifier in bulk trade, item price is counted as flat base price. 
EVEN your trading skill cant affect this, unlike normal trading screen.

### Steps to reproduce the behavior
Teleport to refugee center.
Teleport to the broker in the back of refugee center behind a broken computer.
Spawn some jerky.
Talk with the broker, to "Delivering jerky".
See that shitty price he gives you.

in src/npctalk.cpp
both bulk_trade_inquire() and bulk_trade_accept() needs to be changed.

**Comment by FulcrumA** [comment]
I must agree, it's easy to get plenty of money but it's still a bug that probably should be fixed, if only for the sake of immersion/RP.

**Comment by Theundyingcode** [comment]
The biggest problem I have is getting there in the first place

**Comment by kevingranade** [comment]
> it is quite easy to farm zombies for cash cards.

If you can sell cash cards to NPCs, that's a bug.

That having been said, the barter system isn't so much imbalanced as it is unimplimented, so it's not going to be particularly productive to fix one off issues.

**Comment by Night-Pryanik** [comment]
> If you can sell cash cards to NPCs, that's a bug.

Yes you can. But why is this a bug? Cash cards are rather valuable, you can buy food, drinks, ammo, gas with them.

**Comment by kevingranade** [comment]
In relatively dangerous areas yes, which are inaccessable to settlement NPCs.
At a minimum they should have a massive discount
  This is just another example of there being no barter system implemented.
