### ISSUE TITLE
OS X build is corrupt but i managed to get a debug build working

### ISSUE THREAD

**Issue by micage** [CleverRaven/Cataclysm-DDA#23927]
Game version: newest, from repository
Operating system: OS X 10.11.6

When i tried to pack it with the dmg... tool, things went south. No success.
And plz i am totally new, just pulled the the rep and tried to make it working.

**Comment by vircung** [comment]
So far experimental builds from [homebrew](https://brew.sh/) are working. You can install it via command `brew install cataclysm --with-tiles --HEAD`
