### ISSUE TITLE
Add ability to pull engine parts from used engines or craft makeshift ones

### ISSUE THREAD

**Issue by Warfoniusz** [CleverRaven/Cataclysm-DDA#23935]
Game version: 0.C-27953

Operating system: Windows 10

### Expected behavior
You should be able to take things like filters and glow plugs from existing engines or even be able to craft them yourself because the fact that you have to mend faulty engines shouldn't be so much of a hassle that you need pristine new parts that you have to look for everywhere.

Basically be able to check engines for their parts and remove them from as needed.

### Actual behavior

You have to find engine parts lying in shops or buildings, which isn't really a realistic way because you should be able to pull them out of existing engines.

### Steps to reproduce the behavior

Try getting engine parts anywhere else than finding them randomly lying around in buildings.

**Comment by CoroNaut** [comment]
I feel like it would just be easier to give engines say 10-15 main parts that can each be repaired or reinforced separately. (Just having a couple replaceable parts would be a hack in my opinion.) The player can assemble them if they have the correct mechanics, electrical, etc knowledge. This would give depth to cars spawning in game with faulty engines. There could also be a function that allows you to overclock your engines if you have all reinforced engine parts. Perhaps there could be a great performance loss from having all damaged parts (not to mention the faulty ones).

**Comment by Nymall** [comment]
Duplicate - Presently being investigated in #18419
