### ISSUE TITLE
Can't deconstruct fences, fence gates, fenceposts

### ISSUE THREAD

**Issue by Altreus** [CleverRaven/Cataclysm-DDA#23934]
Game version: 0.C

Operating system: All

Mods active: Default

### Expected behavior

Game elements created through the `*` construction menu can be taken apart through the `*` construction menu.

If it requires special tools, have a separate deconstruct option. Deconstruct furniture / deconstruct fencing, perhaps.

It seems intuitive for any item made with nails to require a crowbar, and anything made of screws to require a screwdriver. Although IRL I can probably take apart a fence with just a hammer, and my skill in that would determine whether I break any parts.

It would seem sensible that removing the fence post requires a digging tool (I tried `a`pplying a shovel)

### Actual behavior

To take apart a picket fence one must `a`pply a crowbar. There appears to be no way to remove the remaining fence post except to `s`mash it.

There appears to be no way to remove the fence gate at all ("You cannot pry there") except to `s`mash it.

### Steps to reproduce the behavior

* Build or find a picket fence or gate
* Try to find a way to take it apart again

**Comment by DracoGriffin** [comment]
Looks like this may have been related to deconstructing terrain doesn't give back the resources used in its creation (or at least from my research, looking around). So it might've been skipped over for a later time and just forgotten.

Fence posts are listed as using 2 pointy sticks or 2 wooden spears, so if you used 2 pointy sticks to create it, there currently isn't a way to return the input items for the deconstruction output. (Basically there is no reversible tag for constructions like there is for items)

I'll have a fix for this up after testing.
