### ISSUE TITLE
Error while reading consumables.json while loading world

### ISSUE THREAD

**Issue by Blank99** [CleverRaven/Cataclysm-DDA#23938]
Game version:
0.C-28092-gc3ec9527bf (freshly built experimental as of a few minutes ago)

Operating system:
Arch Linux

Tiles or curses:
Tiles

Mods active:
None

### Expected behavior
No errors

### Actual behavior
The following error appears:

```
An Error has occurred! Written below is the error report:
-----------------------------------------------------------
DEBUG	: line 3.334:20: assignment does not update value
	"material": ["wheat","junk"]
	"volume": 1,
	"charges":
	          ^
	            1,
	"fun":30
    },

FUNCTION : void report_strict_violation(JsonObject&, const string &, const string&)
FILE     : Cataclysm-DDA/src/assign.h
LINE     : 25
```
Checking on the only two files modified since I last build the game, the error appears to be in consumables.json, specifically in the definition for smores.
Smores seems no different than any other food definition on the file, the only exception is that it is the only food that defines "charges" : 1.

### Steps to reproduce the behavior
Start a new game

**Comment by Brambor** [comment]
Doesn't need to be a new game, just loaded my save, got this error (OS:Windows 10, version: 0.C-28092-gc3ec952 (tiles))

Is it because 1 charge doesn't make sence?

**Comment by Night-Pryanik** [comment]
Charge 1 is a default, it doesn't need to be stated explicitly.
