### ISSUE TITLE
Set remainder (time note)

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#23936]
### Introduction
It would be great to be able to make notes on WHEN something is happening. Such as when will be fermenting done or when will my sprouts be finished growing.

EDIT: There are map notes already implemented in the game, but these time notes won't be related to space (to map).

As @CoroNaut Suggested, it would be cool to be a PDA (mobile phone) based system.

### Make notes
Through hitting enter entering miscellaneous ability to "Make time note".

Choosing when the note should be reminded (in 23 hours / 13th of Spring) and the note body ("Fermenting is done"/ "Strawberries in field A3 are grown"/whatever - all custom text).

Additionally, when you walk to fermenting machine that says "will finish in 23 hours" having the ability to add a note that auto fills the time and lets the player fill the note's body would be great.

When the time passes, then probably not delete them, but rather set their time in the past either absolute (13nd of Spring 14:20:00)  or relative (6 hours ago) or just state "in past" when displayed.

### Read notes
Ability to view list of notes, when and what is happening, probably sorted by time.

relative time:
23 hours | Fermenting is done
12 days | Strawberries in field A3 are grown

absolute time:
2nd of Spring 15:20:00 | Fermenting is done
13nd of Spring 14:20:00 | Strawberries in field A3 are grown

### Reminder
Your time note "Fermenting is done" just passed

When the time comes write into a log (with some, probably yellow colour) that a time note has passed.

Or make a choice menu (for the note to have a bigger impact and reminder value). If that would be better than the choose menu might as well have options:
1. ok
2. delete note

### Issues
When a player doesn't have watch, then either disable that option (make it gray as well) or make it only possible to remind on dates rather than exact time. All that to make it more realistic and unexplitable.

**Comment by CoroNaut** [comment]
I like the idea, but dislike that it would be a map note. Perhaps you could set the timer on your watch instead and have it go "beep...". Then perhaps the PDA can be remastered to become a device meant to hold your entire schedule and be able to hold a bunch of notes and timers like this. They can have the ability to repeat every X minutes/hours/days, to automatically delete themselves after X date, or however many times you want it to go off, etc.

**Comment by Brambor** [comment]
@CoroNaut It was not supposed to be a map note. I was trying to point out that there are map notes and that this system would be similar yet something of different use. I will edit the Introduction to reflect that.
And your approach seems quite cool, make it all based on PDA :). They would really get some of the modern mobile phone multifunctionality :D.

**Comment by Break-Off** [comment]
What about the reality bubble in different Z-levels? If the passage of time stops when changing Z-levels, then your reminder note will report an event inaccurately. Maybe, if the note was made in certain Z-level, it could pause its countdown when changing Z-levels.

**Comment by Brambor** [comment]
@Break-Off I heard that this was fixed, that all Z-levels have the same time-... well, time-zone.

**Comment by Break-Off** [comment]
@Brambor Is that so? I thought some events don't develop when changing Z-levels. Can you cite a build number? I'm curious of when that change happened.

**Comment by Brambor** [comment]
@Break-Off I cannot, I heard it from Aavak in one of his LP videos, maybe somebody enlightened will come along and tell us.

**Comment by CoroNaut** [comment]
Moving all functionality of timed notes to an item would prevent any time-related problems with the map to interfere with their correctness. This is almost the main reason I suggested to put it into item form. Having supreme functionality in the actual user interface is handy and convenient, but putting functionality into an item makes it more immersive.

**Comment by FulcrumA** [comment]
I'd agree that it should be more of a feature of devices such as phones and e-tablets rather than average watch or the overmap.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
