### ISSUE TITLE
Crafting interruption due to light level disruptive to gameplay

### ISSUE THREAD

**Issue by smolbird** [CleverRaven/Cataclysm-DDA#23944]
### Expected behavior
In the event of requiring a constant source of fire and/or light to craft, player will be given options to sustain a fire or turn on a light source as needed to prevent the crafting attempt from being interrupted.

Alternatively, crafting would not be interrupted by light levels due to factors that should be in the player's control but isn't.

### Actual behavior
Loss of light interrupts crafting, with no ability to prevent this from occurring, causing player activity to be disrupted in a way that is both unrealistic and serves no purpose.

### Steps to reproduce the behavior
1. Light a small fire in dark conditions.
2. Attempt to craft.

**Comment by DracoGriffin** [comment]
Devil's Advocate here:

You can willingly pause crafting (which would be way more useful if controlled fires had a light level indicative of the fuel left -- so paltry dying flames would basically have a `LIGHT_5` compared to well-fed fire with a `LIGHT_500` so you would know when to "take a break" from crafting to stoke the flames), so if you're using an undependable light source, you can prepare another.

Secondly, you can resume any interrupted crafting with the default hotkey `-`. I actually use this method a lot when crafting a lot of the metal items that require hours of crafting time, and with the new morale/focus changes as well, can quickly interrupt crafting. So I will pause crafting, eat/drink/use something to increase morale and focus, resume crafting to avoid the slow down penalties.

**Comment by AMurkin** [comment]
Also see [comment](https://github.com/CleverRaven/Cataclysm-DDA/issues/23668#issuecomment-386972731).

**Comment by Brambor** [comment]
Wait, what? You can stop and resume crafting? I play CDDA for a long time now and I have seen a handful of LP but I have never come across this feature. Could it be documented better?

**Comment by FulcrumA** [comment]
It works as intended and yeah, crafting interrupted by darkness can be resumed if you'll get the light going again, have access to the necessary tools/materials and, say, press the key to repeat crafting of the last recipe.

**Comment by DracoGriffin** [comment]
>Also see comment.
I'll have to see that out AMurkin.

One for crafting, one for construction and one for vehicle construction and see if its still reproducible.

**Comment by kevingranade** [comment]
Way too much attitude here, if someone feels like opening a less snarky version of this they can feel free.

**Comment by FulcrumA** [comment]
@kevingranade 
Was this issue edited or something deleted? It doesn't seem much snarky as I look through all the comments right now.

Still, I am not sure about this - Smolbird mentions no way to prevent interruption of crafting while there are ways to maintain light and he doesn't say whether he factors in resuming of interrupted crafting, a thing that's quite important as both inability to craft due to darkness and ability to resume are relatively recent additions but intentional.

**Comment by smolbird** [comment]
> Way too much attitude here, if someone feels like opening a less snarky version of this they can feel free.

There was no attitude here, at least none intended. I was plain and matter-of-fact about stating what happens versus expectations of how it should be handled, along with laying out two recommended ways to handle the issue.



As for resuming crafting, see comments in https://github.com/CleverRaven/Cataclysm-DDA/issues/23668. Action resumption is not very reliable at present.

As for light management, you don't have *automatic* light management. In the real world, a sane person doesn't leave their light on all day just because they expect it'll get dark later. They turn it on when needed, and ideally this factor be be automated to a limited degree.

For example, consider that the sleep prompt is able to detect active items you can switch of, and the item menu can tell that an item can transform into an active item. One way to handle this would be, instead of interrupting crafting, ask the player if they wish to activate an object that can give off light, then *resume crafting* if they select one. Only make a full interrupt if no options are in reach.

**Comment by Zireael07** [comment]
I see no attitude or snark in this issue either.

**Comment by FulcrumA** [comment]
@smolbird 
I must say I like the idea of being prompted to activate available light sources in a distance of few tiles from the character if crafting gets interrupted due to darkness.

**Comment by Brambor** [comment]
Or it could be at least notified that crafting was interupted due to smthing, BUT you can resume crafting by "resume crafting key" standing on the same tile. I would really like that, let everybody know that it is possible.

**Comment by FulcrumA** [comment]
@kevingranade 
Given there's not much snark among currently visible comments and there are some good ideas in this ticket, would it be possible to reopen it?

**Comment by BorkBorkGoesTheCode** [comment]
The discord and the PM system are the places where snark flourishes it seems.

**Comment by BorkBorkGoesTheCode** [comment]
I remember a few months ago two people opened abuse issues just to post racist cuck insults directed at him.

**Comment by smolbird** [comment]
And I've done no such thing in this issue. All my comments thus far have been neither edited nor deleted. Edit status and edit history would be marked by the word "edited" in the comment block header.

Example:

![image](https://user-images.githubusercontent.com/36311084/41071135-ff3f7000-69bb-11e8-8bad-3d3568a60135.png)
