### ISSUE TITLE
Small storage units gate issue

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23947]
Game version: Currently 0.C-28092

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

A very minor issue:
In default state, 4 gates leading to different compartments are closed. By each one of them there's a winch. 2 of the winches open connected gates as they should, but 2 report that "The gate is closed!" despite it being closed already. Using those winches again, open them correctly.

### Steps to reproduce the behavior
Visit aforementioned storage units, open/close gates.

Pic of location in question:
![storage](https://user-images.githubusercontent.com/38487938/40919383-a6e3c842-6809-11e8-8487-cd218f001ea3.png)

**Comment by cosmiccoincidence** [comment]
My PR moves the bottom 2 winches similar to the top 2 and puts columns in their empty spots similar to the north side of the building.
