### ISSUE TITLE
You can "miss" when dropping items

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23948]
Game version: Currently 0.C-28092

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
When dropping items, they always go to the tile one wants to drop them. Otherwise, information of inability to do so pops up.

### Actual behavior
You can "miss" in that the character puts the item on the tile next to where the player wanted to drop the items.  ̶I̶t̶ ̶c̶a̶n̶ ̶a̶l̶s̶o̶ ̶l̶e̶a̶d̶ ̶t̶o̶,̶ ̶a̶p̶p̶a̶r̶e̶n̶t̶l̶y̶,̶ ̶c̶o̶m̶p̶l̶e̶t̶e̶ ̶l̶o̶s̶s̶ ̶o̶f̶ ̶i̶t̶e̶m̶s̶ ̶w̶i̶t̶h̶o̶u̶t̶ ̶p̶l̶a̶y̶e̶r̶'̶s̶ ̶f̶a̶u̶l̶t̶ (turns out untrue, details in the comment):
![inthewall](https://user-images.githubusercontent.com/38487938/40922507-a3ff8f68-6812-11e8-9ad1-47b5617adc56.png)

### Steps to reproduce the behavior
It's hard to reproduce, sometimes just dropping multiple items around in different tiles, coming from different directions and so on leads to this happening.

**Comment by Zireael07** [comment]
A tile has a max cap on how many items it can hold - maybe you exceeded it.

The real bug is probably the fact that they could go in the wall.

**Comment by FulcrumA** [comment]
It's true that it may be a possible case, but it also happened in situations where there weren't many items and there was no indicator that the tile was full - it just looked like I've chosen to drop items elsewhere, despite being absolutely sure that I pressed the right key of another direction.
Unless the whole "tile full" feature is bugged, because afterwards if I picked those "inaccurately placed" items again, and attempted to drop them where they were meant to go, it usually went without issues.

**Comment by Zireael07** [comment]
Do you have the shift option for diagonals on?

**Comment by FulcrumA** [comment]
I was wondering if I holding ctrl or shift by accident when dropping items and find it very unlikely - I use numpad for all my diagonal movement/dropping items etc.

**Comment by DracoGriffin** [comment]
I couldn't find what # @ZhilkinSerg was referring to, but this may be [similar issue](https://www.reddit.com/r/cataclysmdda/comments/8n5ev8/possible_bug_items_disappearing_when_using/dzxn24a/?context=10000).

Furthermore, are you using regular `d`rop, multi-drop (generally `D` hotkey) or AIM when this issue arises?

**Comment by ZhilkinSerg** [comment]
Dropping items diagonally won't make it possible to drop them to walls - `You can't place items here!` will be in the message log.

https://github.com/CleverRaven/Cataclysm-DDA/blob/4577b0744f050450b83831b8f47231e9b1b24905/src/player.cpp#L7998-L8003

**Comment by ZhilkinSerg** [comment]
So there are three distinct issues:

1. Using `SHIFT`+`D` keystroke for dropping items can cause items to be dropped to unwanted destination when destination keystroke is clicked while `SHIFT` modifier is still down. See #23542.
2. Dropping large amount of items in amounts which exceed single tile capacity can cause items to disappear. This especially affects `AMMO` items (e.g. `thread`, `nail`, `battery`, etc), while other item types are unaffected and distributed to neighboring tiles. This is probably because items of item type `AMMO` cannot be split during the drop. This bug seems to be very old. See https://www.reddit.com/r/cataclysmdda/comments/8n5ev8/possible_bug_items_disappearing_when_using/dzxn24a/?context=10000.
3. Items can be put into impassable tiles. The reason is unknown yet.

**Comment by FulcrumA** [comment]
@ZhilkinSerg 
>Items can be put into impassable tiles. The reason is unknown yet.

I've done some testing and we can at least take this one out of the equation, at least in this case. Earlier claim of items disappearing was false, the items were moved to the other side of the wall, just without notification and not immediately noticeable as the other side was not easily in sight and required additional search.

@DracoGriffin 
>Furthermore, are you using regular drop, multi-drop (generally D hotkey) or AIM when this issue arises?

Frankly, all of the above, depending on circumstances. I will try to make a note to remember which one it was in particular when/if the bug happens again.
