### ISSUE TITLE
can't repair filthy clothes using filthy rags

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#23958]
Game version: 0.C-27990-g91a1db0

Operating system: windows

Tiles or curses: tiles

Mods active: various, issue should exist in vanilla let me know if not and I'll post full list

### Expected behavior
Expect to repair with filthy parts, just forces product to become filthy (with prompt warning of such)
or at very least, for filthy components to work on something that's already filthy

### Actual behavior
Says "Don't have enough rags to do that. Have: 0, Need: 1"

### Steps to reproduce the behavior
steal clothes from some suckas
cut up some of the clothes
wish for needle and thread
try to repair something with filthy rags

**Comment by Night-Pryanik** [comment]
The rationale for not being able to craft something or repair something with filthy components is that while character still tolerates wearing filthy clothes (gaining morale penalty in process), he just can't make himself work with filthy components.

**Comment by Xpyder** [comment]
I don't understand the underlying premise there, why shouldn't you be able to make do with filthy clothes?  If it's an attempt to rebalance there should be some larger penalty because the way it's implemented now is TRES confusing to any new (or returning) player.  It legitimately doesn't make sense.

**Comment by Xpyder** [comment]
To be clear, I'm not saying the availablity of clothing wasn't something that needed to be rebalanced, I'm saying the approach of blocking repairs doesn't make sense.

**Comment by Night-Pryanik** [comment]
As I said, character is refusing to mess with these heinous, repugnant, disgusting, slimy little pieces of fabric (wool, felt etc).

**Comment by kevingranade** [comment]
Agree, working as intended.

**Comment by Xpyder** [comment]
I might believe that, If you took the trait that prevented you from wearing filthy clothing.  But I didn't.

**Comment by Night-Pryanik** [comment]
Wearing filthy clothes is more tolerable - they might even don't come into contact with one's skin (filthy boots over clean socks, for example). Sewing, cutting requires one's bare hands, and it is beyond the threshold one can tolerate.

**Comment by Xpyder** [comment]
No it's not, if you don't believe me go soak your clothes in mud and see for yourself if you'd rather hold them or wear them.

If Kevin's position (as the primary maintainer) is that these should be so gross you don't even want to touch them, then the "Squeamish" trait should be the default state, and you shouldn't be able to repair or cut them up as that's also "refusing to mess with these heinous, repugnant, disgusting, slimy little pieces of fabric "

I don't have a problem with it harder, I have a problem with it being internally inconsistent.

**Comment by Xpyder** [comment]
If you tell me where to find the code for this I'll look into making a PR with those changes (disabling repair of filthy clothes, making Squeamish default, making an inverse trait that would let you wear filthy clothes, and upping the morale penalty)
