### ISSUE TITLE
Onboard chemistry lab recipe expansion

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23951]
Game version: Currently 0.C-28092

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Onboard chemistry lab recipe during vehicle installation can use regular chemistry lab item

### Actual behavior
The recipe calls for onboard chemistry lab only, meaning one cannot just adjust regular lab (a thing that's not hard compared to creation other similar vehicle facilities) but must scavenge whole lab from elsewhere.

### Steps to reproduce the behavior
Attempt to install onboard chemistry lab in a vehicle

**Comment by Zireael07** [comment]
Regular chemistry set is nowhere close to an onboard lab (it's just a bunch of flasks held together in a box, basically)

**Comment by FulcrumA** [comment]
You mean basic chemistry set, not regular one which has similar capabilities to onboard set, except requires batteries. Still, I'm willing to close the ticket for another reason - the fact that indeed that onboard set is already made out of regular one, it just requires prior modification via crafting rather than - somewhat more intuitive given other recipes like aisle lights made out of flashlight and whatnot - being adjusted on the fly.

Though whether that lack of consistency should have its own ticket I am unsure.
