### ISSUE TITLE
Remote control of lab doors as added challenge

### ISSUE THREAD

**Issue by thethunderhawk** [CleverRaven/Cataclysm-DDA#23965]
I suggest that a mechanic be developed which causes most or all of the doors in a lab be locked to an open position (Lorewise, an emergency access protocol for disaster response teams), allowing monsters to roam freely throughout the lab. This mechanic could come into play upon electrohack use, failed hack attempts, etc. Ideally it would make labs more dangerous and unpredictable by preventing the player from avoiding combat. This increases the challenge and reduces the perceived significance of the “open door, turret shoots, dead” situations that constitute a large portion of the danger in labs as it stands now. There are a number of ways that we could take advantage of this mechanic to make labs more interesting.

Various ideas for implementation:
1. Upon science ID card use, a hack attempt is initiated. Upon failure all the doors are locked in an open position. Upon success the doors are usable as normal. In lore terms the open-door scenario is described to the player as “first responder emergency access mode” and the more beneficial standard scenario (upon a successful hack) would be called “containment mode override”. Electrohack use would result in an open-door scenario every time. (This is sort of the crux of what I envision. At high enough computer skill, or with some other prerequisite, most of this suggestion wouldn’t come into play)
2. The door controls could be accessed through turret-room computers and only function on a floor-by-floor basis.
3. The prisoner containment room terminals could have a “security lockdown” function that closes and locks all doors and releases security bots across the entire lab or lab floor. You could turn this off with no hack attempt necessary, but the bots would remain. (I like this one a lot. In exchange for high computer skill it gives the player an opportunity to really change the dynamic of a lab or a lab floor in terms of combatants. It might be too ambitious though.)
4. There could be a new room in labs that functions as a security room, with a terminal with some or all of the above functions, and bots locked in cells that can be released via terminal. 

I’m not married to any of these ideas of course, but I think this could be a fun way to flesh out labs, and I think any enhancements in that area are bound to be a crowd-pleaser.

I appreciate your feedback!

**Comment by CoroNaut** [comment]
I'm against the prisoner containment protocol, it introduces instant death (if these security doors were to be metal like the vault doors in banks) for any character before they've reached late game, especially in a cold lab. I think the science ID card is meant to be an almost-all-access card since there isn't any DNA scanning or fingerprint scanning, etc. So I don't see it as you trying to hack the terminals with the card in hand. As for adding a new room, I like the idea since labs are extremely repetitive. I'm indifferent to all the other ideas.

**Comment by thethunderhawk** [comment]
Re. The science ID card, I get that its meant to be an all access card as it stands now. That does seem a little strange to me though that all it takes is a random ID to open up an advanced research lab. It might be nice to fill out the lore there, no?

As for the prisoner containment thing, it wouldn’t leave you trapped and it wouldn’t be doable on accident.

**Comment by kevingranade** [comment]
I believe the spirit of these requests was satisfied somewhat by @BrianLefler 's lab changes.
