### ISSUE TITLE
Activating folded vehicle on a "forbidden" tile deletes it

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23961]
Game version: Currently 0.C-28092

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Folded vehicle cannot be unfolded on a tile it's forbidden from being on or moved next to it if possible.

### Actual behavior
Moving onto a tile where vehicles cannot be unfolded and activating folded vehicle informs the player on how unfolding was succesful but no vehicle spawns and the folded item disappears

### Steps to reproduce the behavior
Create a vehicle composed of a few frames, move onto it, unfold a vehicle composed of a single frame.

**Comment by AMurkin** [comment]
For me it have placed over 'big' vehicle's tile and still interactive. `e` on that tile opens 'small' vehicle's menu.

**Comment by FulcrumA** [comment]
Hm, understood, it worked now. Would you be kind to also try to verify it with a vehicle with quarterpanels around the tile you activate the smaller vehicle on? I am certain the item disappeared as I dismantled everything around and picked up parts in search of the lost folding one, but maybe I didn't factor something else that led to the bug.

Guess I'll try to fiddle around more with things to reproduce it reliably.
