### ISSUE TITLE
Segmentation fault when NPC (or player) is on fire

### ISSUE THREAD

**Issue by bolodyai** [CleverRaven/Cataclysm-DDA#23962]
Game version: Master

Operating system: Linux

Tiles or curses: Tiles

Mods active: None

Caused by iterator invalidation in player::absorb_hit. It goes like this:
1) - We start to iterate over worn items: https://github.com/CleverRaven/Cataclysm-DDA/blob/1e63ab2ba769834a90057aefc0467aba2384d533/src/player.cpp#L9890
2) - If body part was hit with fire, armor is burned and possibly marked for destruction: https://github.com/CleverRaven/Cataclysm-DDA/blob/1e63ab2ba769834a90057aefc0467aba2384d533/src/player.cpp#L9906
3) - Then fire damage may add effect_onfire (executing its handler immediately): https://github.com/CleverRaven/Cataclysm-DDA/blob/1e63ab2ba769834a90057aefc0467aba2384d533/src/player.cpp#L9909
4) - If armor was marked for destruction, it happens now, invalidating iterator through erase: https://github.com/CleverRaven/Cataclysm-DDA/blob/1e63ab2ba769834a90057aefc0467aba2384d533/src/player.cpp#L9929

Now, let's look what happens during 3) more closely. There is a long call chain:

Character::add_effect -> Creature::add_effect -> player::process_one_effect -> player::hardcoded_effects -> eff_fun_onfire -> player::deal_damage -> Creature::deal_damage -> player::absorb_hit

So ultimately player::absorb_hit is called recursively from within itself. And in this nested call items may be damaged and destroyed too. Now after nested call returns to parent scope, item iterator we had may be already invalid, and we'll get segfault trying to erase it again.

**Comment by NotFuji** [comment]
This is the cause for #23598
