### ISSUE TITLE
"computers" in mapgen json should be treat as a separate entity like terrain and defined in another files. 

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#23966]
Game version:
master
Operating system:
any
Tiles or curses:
any
Mods active:
any
### Expected behavior
Mapgen json should only have mapgen info, detailed computer definition should be put into another json file similar to what terrain and furniture does.
### Actual behavior
They are not.
### Steps to reproduce the behavior
Check https://github.com/CleverRaven/Cataclysm-DDA/wiki/Mapgen:-computers.

**Comment by AMurkin** [comment]
This time it's duplicate of the #23555

**Comment by cainiaowu** [comment]
Emm, you are right. So I will change this issue into something regard of current json structure then.

**Comment by pisskop** [comment]
They could be like mission defines or speech.

**Comment by kevingranade** [comment]
We want this to happen, but the blocker isn't knowing it's desirable but some tricky issues surrounding design and implementation.
