### ISSUE TITLE
Add a prompt to activate a light source in response to light-level crafting interrupt

### ISSUE THREAD

**Issue by smolbird** [CleverRaven/Cataclysm-DDA#23971]
See discussion in https://github.com/CleverRaven/Cataclysm-DDA/issues/23944

To summarize, the code is able to recognize transforming items, and when the player tries to sleep it is also able to prompt the player and warn about active items.

Suggestion is thus: when declining light level leads to a crafting interruption, instead of halting the task and counting on the (bugged, not readily apparent to the player, finicky) resume crafting feature, instead ask the player if they would like to activate a light source.

If so, they pick a valid item (looks for transform and an adequate light output) and continues crafting, If player declines, or if no valid items are in the crafting radius, crafting interrupts as per current behavior.

Reasoning is that the player should not have to turn on a light source when it's bright out just to prevent crafting interruption, instead they should only be prompted to activate a light source when it becomes necessary during the process of crafting.

**Comment by FulcrumA** [comment]
Should search for all light sources in player's close vicinity, like how it is with looking for ingredients for crating. Possibly turn off those light sources after crafting. I'd also expand it to fuel for cooking devices - if someone is using survivor mess kit, for example, and there's lamp oil nearby, a popup asking to fuel the kit with nearby oil and continue cooking would be good (suggesting here since it's something that could use suggested system).

**Comment by Night-Pryanik** [comment]
It would be a big work. What if there is several types of light sources available? Flashlight, oil lamp, electric lamp, dying out bonfire and what else.

**Comment by FulcrumA** [comment]
I think current system could be easily repurposed - attempting to craft a thing lists possible ingredients in the area if there are several alternatives and the fueled devices that can be used to prepare them if there are several eligible.

**Comment by Brambor** [comment]
Bionics should be used as well. There is cardinal flashlight CBM that should be listed in possible light sources. (please)

**Comment by FulcrumA** [comment]
Yeah, cranial flashlight could work too. Cardinal less so, unless you have a clergyman NPC willing to hold it for you.

**Comment by smolbird** [comment]
> Should search for all light sources in player's close vicinity

Agreed, as noted in the OP I did say crafting radius.

> It would be a big work. What if there is several types of light sources available? Flashlight, oil lamp, electric lamp, dying out bonfire and what else.

Prompt should show a list, and activate the one that the player chooses.

**Comment by DracoGriffin** [comment]
>Prompt should show a list, and activate the one that the player chooses.

Should also default to the player's previous selection (instead of the player having to have more keypresses to reach the same option) -- or at least a list prompt with choice hotkeys like rebinding hotkeys and talking to NPCs has.

**Comment by kevingranade** [comment]
Fixed by #24077

**Comment by kevingranade** [comment]
My bad that's wrong, this is a bigger but still valid request.

**Comment by ifreund** [comment]
Due to inactivity and the fact that resuming will be much more reliable after the referenced PR, making this issue mostly void.
