### ISSUE TITLE
Game Crash when using to help with combat NPC at the start of really bad day

### ISSUE THREAD

**Issue by Sammmmm** [CleverRaven/Cataclysm-DDA#23976]
Game version:
7447

Operating system:
Win10

Tiles or curses:
Chesthole tiles

Mods active:
Defaults + statsthroughskills 4

### Steps to reproduce the behavior
I've started about 10 new really bad day/tweaker scenarios today.  The first thing I try to do is convince the NPC to go with me (to get him out of the house).  After that happens we inevitably have to fight some zombies.  About 50% of the time it crashes while we're fighting zombies.  The debug.log has the following lines repeated many times as the final entries:

12:32:24.857 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:24.857 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:26.437 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:26.437 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:26.437 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:26.437 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:26.437 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:26.437 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:26.437 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:26.437 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:26.437 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:26.437 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:26.437 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:26.437 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:30.566 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:33.513 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:33.513 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:33.513 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:33.513 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:33.513 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:33.513 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:33.513 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:33.513 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:33.513 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:33.513 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:33.513 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0
12:32:34.785 GAME : src/npctalk.cpp:2634: called calc_chance with invalid talk_trial value: 0

**Comment by kevingranade** [comment]
Insufficient information to reproduce issue.
