### ISSUE TITLE
Prozac doesn’t function realistically.

### ISSUE THREAD

**Issue by thethunderhawk** [CleverRaven/Cataclysm-DDA#23985]
I take Prozac for depression. It usually takes >10 days to accumulate in your system before you really start to feel the antidepressant effects. Its dangerous interactions with alcohol can start immediately though.

I suggest, if we want to keep Prozac as a usable drug, that it be made into a static morale boost that takes several days of dosing oneself before kicking in. Or, perhaps more realistically, it could reduce morale penalties for “chronic” stressors like wetness, gross food, hunger, withdrawals, etc but NOT acute stressors like guilt or pain.

Really though it’s hard to imagine a little bit of Prozac helping with the horrors of the apocalypse. From experience let me tell you it is NOT a magic happy pill. It’s really meant for dealing with chronic chemical balances in the brain.
In that sense, it could have synergy with a depression style trait (change “bad temper” to “chronic depression”? It might be better for roleplaying purposes anyway).

(Chronic depression could also be a nice, flavorful mutation trait)

If this is discussed elsewhere i haven’t found it, but I’d be interested to get caught up with the conversation. I do understand that Prozac currently has an important role in gameplay, but I think if the game is gonna have “happy pills” they shouldn’t be a drug that people rely on to deal with chronic illnesses IRL.

I appreciate your feedback!

**Comment by DracoGriffin** [comment]
>(Chronic depression could also be a nice, flavorful mutation trait)

There already is `Mood Swings`, `Chemical Imbalance`, and `Bad Temper` -- yes the names aren't explicitly "depressive" but reading the flavor text it can denote bipolar or dysthymia, or other similar depressive disorders.

Unless it's meant to build on top of a previous trait (like making bad temper worse), that I could see working potentially.

**Comment by thethunderhawk** [comment]
>There already is Mood Swings, Chemical Imbalance, and Bad Temper

Good point, though if we intend for antidepressants to treat “bad temper”, that trait might deserve a new name for clarity’s sake

**Comment by kevingranade** [comment]
We have no plans to make medicines work in a way that meaningfully matches their IRL counterparts.
I wouldn't be averse to renaming them to break that connection.

**Comment by thethunderhawk** [comment]
If nothing else maybe the current “Prozac” item could be changed to generic “antidepressants”. There’s not really a reason to give it a specific name, especially since most people have no idea what Fluoxetine is and there are no other antidepressants in the game.

**Comment by kevingranade** [comment]
>
> That's a good idea, especially considering Prozac is a registered
> trademark both in US and the EU.
>

Well that makes me want to keep them around, screw trademark overreach :p

**Comment by thethunderhawk** [comment]
“Wanna sue me? Well jokes on you I have no money.”
I appreciate the feedback you guys. I know it’s a finicky thing, but I think a little extra sensitivity and realism when it comes to things like this will pay off in the long term. Ideally eventually there will be a lot of people playing this game, it definitely has the potential, and if that happens there will be people paying attention to stuff like this.

**Comment by kevingranade** [comment]
No motion in 6 months, and no solid suggestion for a fix.  If someone wants to rename some of the medicines, I'd be onboard with that.
