### ISSUE TITLE
Radio activated bombs give wrong messages when used

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#23989]
Game version:0.C-28152-g5e846a6 (tiles)

Operating system:Windows

### Expected behavior
Activating the right channel detonates the grenades/bombs.

### Actual behavior
Activating the right channel detonates the grenades/bombs but you get the message "You pull the pin on the (whatever)" and then "You already pulled the (whatever)'s pin, try throwing it instead."

### Steps to reproduce the behavior
Give a bomb a radio detonator mod and detonate it.

![image](https://user-images.githubusercontent.com/16110328/41208781-80db19a8-6cdb-11e8-957a-ad7f84722454.png)

**Comment by Leland** [comment]
I've seen this with molotovs before as well
