### ISSUE TITLE
"River bank" name makes searching for "Bank" on map difficult

### ISSUE THREAD

**Issue by papersplease** [CleverRaven/Cataclysm-DDA#23993]
Game version: 0.C-28148-g3b40214

Operating system: Windows 7

Tiles or curses: tiles

Mods active: none

### Expected behavior
Searching for "bank" at the overmap should return a list of bank buildings in cities.

### Actual behavior
The search returns hundreds of useless "river banks", if you've discovered some river tiles previously.

### Steps to reproduce the behavior
Try searching the overmap for banks. Be sure to have some rivers discovered.

### Suggested solution
Either rename the "river bank" overmap tile to just "river", removing the conflict, or make the overmap search line take filtering operators, like the one in Shift+V does. The second variant would be much more useful, because 1. it would allow searching for multiple types of overmap tiles (eg "pharm, doctor, vet" at the start of Infected scenario), and 2. it would avoid similar problems in future and/or with localized versions.

**Comment by WhiteHusky** [comment]
Trying to be coy and attempting to use -_something_ doesn't work.
![cataclysm-tiles_2018-06-17_09-41-03](https://user-images.githubusercontent.com/3196371/41508431-b22455d8-7212-11e8-9357-0df7c3e33c1f.png)
