### ISSUE TITLE
Batch Unload

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#24002]
### General
A system similar to unload, but unloads batch of selected items. As opposed to the current state, you can unload only one item at a time.

### What the player sees
After hitting the Batch Unload key (suggestions on which should it be are welcome, unload uses "U") the player will be able to select which items to unload from a menu. That menu will list everything around a player, as regular unload does, however, more items will be selectable, as it is possible when dropping items.

All selected items that don't require future doings (such as items in plastic bags or chocolate bars) will be unloaded right away.

If any of the items selected contain a liquid, a more delicate system will follow the unload selection menu.
All liquids that require a container to be in will be summed up (for example 5 full plastic bottles of water will result in 10 units of water) and then a list of destinations for the liquid will be provided, the same list as for regular unload. The player will then be asked where to put that liquid until there is no more of that liquid. Then the system will proceed to the next liquid.

Before unloading, the player will be asked whether they want to ignore the containers that are being unloaded. That will result in a clever system that doesn't ask the player whether they want to put that liquid back into the original container or any container emptied while unloading. If it will no longer be possible to unload *with ignored*, the system will stop unloading rather than stop ignoring containers [1].

### What happens
Containers are unloaded one by one, in no particular order.

Therefore, it will not be possible to have two containers (such as a plastic bottle with water and a glass bottle with wine) batch unload them and then switch the contents resulting in wine in a plastic bottle and water in a glass bottle. Cause that's unrealistic.

If there are any warnings the player will be warned at the time the system gets to each and every container (could be changed) (opening sealed cans resulting in the start of spoiling the contents of that can). However, the sum will contain the sum of such containers [2].

### Usage
- unloading a range of water-containing containers from raid into a 60L metal tank of water.
- the same, but for other liquids
- Unloading all cardboard boxes, plastic bags and such
- unload jar of pickled veggies resulting in faster crafting (Idea started here)

### Examples
1. The player unloads 10 plastic bottles of water (2) and one orange soda. Containers available are one 60L metal tank and one bottle. The player chooses to ignore unloaded containers. He unloads the orange soda into the 60L metal tank, now there is not enough space for the water so the system stops unloading. (That would be a mistake or wrong usage of this system.)
2. The player tries to unload 10 sealed cans of wood sup (1). The system will ask the player where they want to put their wood soup (10) and after a container is selected, the player will be asked whether they really want to unseal that can before each and every portion is transferred. On choosing yes, the system will proceed. On choosing no that one container will be skipped. **On choosing "No and skip all"** all such containers will be skipped, but the system of unloading will proceed. **On choosing "Yes for all"** all sealed wood soup will proceed, but any other sealed fresh container needs to be handled separately.

**Comment by Brambor** [comment]
I wouldn't mind implementing that myself, however, I do not know C, I'm primarily a Python programmer, so if any of you redirected me to what I need to know and **what files am I talking about there** it would be appreciated.

**Comment by OzoneH3** [comment]
Shouldn't be too hard.

Take a look at (game_inventory.cpp)
```c++
std::list<std::pair<int, int>> game_menus::inv::multidrop( player &p )
```
to get a selectable list of items.

Called from (game.cpp):
```c++
void game::drop( int pos, const tripoint &where )
```

Only show unloadable items:
```c++
u.rate_action_unload( it ) == HINT_GOOD;
```

Somehow add in items on the ground. Not sure how exactly but it's possible.

After they are selected call (game.cpp)
```c++
void game::unload(int pos)
```
with all the selected items.

**Comment by evankimori** [comment]
Might I ask if there is any progress on this option? I thought about this exact situation yesterday and found this thread.

**Comment by Brambor** [comment]
Well actually, I'm learning C now... so no, there is none on the issue and anybody is free to take it, but I might get to it eventually if nobody does it in like 5 months or so.

Feel free to close.
