### ISSUE TITLE
Solar backpack concept

### ISSUE THREAD

**Issue by nexusmrsep** [CleverRaven/Cataclysm-DDA#24010]
Since #23317 has put solar panels CBM on the road to oblivion, let's discuss @kevingranade idea of a solar backpack as a replacement.

Solar array can be folded like in satelites forming a special backpack. 
It would have no internal storage space other then space for the panels.
It would have (active) and (passive) state.
Passive state = folded panels hidden in bacpack's material. Backpack size, better encumbrance, better durability.
Active state = unfolded panels (butterfly wings style, see idea by @Night-Pryanik : #23317), big encumbrance, low durability

While active it could charge it's user via cable charger CBM or a new dedicated CBM, solar panel interface CBM (?) (somewhat like power armour interface CBM).
In second option this CBM might even come along with the backpack as a set.

It might have a quantum variant too.

Racionale: Backpack has all the pro's of former solar panels CBM without all its con's. Its wearable, its not covered by clothes, it can unfold so it would have decent surface for sun rays collection, it applies penalties from encubrance, weight, it has durability value that can be adjusted acordingly. All in all it would be lot of cons to live by with not so much pros, but it would be a nice replacement, as it would still be an option if one does not have any high end power CBM's at hand.

**Comment by ZhilkinSerg** [comment]
Are you aware that solar panels were simply moved from mainline into Bright Nights mod (see #23365)?

**Comment by nexusmrsep** [comment]
> Are you aware that solar panels were simply moved from mainline into Bright Nights mod (see #23365)?

Solar panels CBM? Yes, I'm aware. I'm trying to think for a viable option that doesn't have to "hide" in a mod. Also, even with the mod enabled the CBM would not collide with the solar-backpack.

**Comment by GroeneAppel** [comment]
This is a good idea and could potentially open the path to similar devices that can be worn and disposed/taken off by the character at will. 

>While active it could charge it's user via cable charger CBM or a new dedicated CBM, solar panel interface CBM (?) (somewhat like power armour interface CBM).
In second option this CBM might even come along with the backpack as a set.

I would recommend an 'interface' CBM that could resemble a set of ports somewhere on the body, alongside a set of controls (touchscreen, buttons etc) that allow the user to change settings/enable/disable the devices plugged in to him. 
This way you allow for future additions that could also interact with the interface and reduce clutter. It would be counterproductive to have a different interface for every little tool/addition. If really needed you could have the player require both the cable charger (set of ports/cables) and the interface (Controls). 

You could further increase the complexity by adding a civilian and a heavier/more advanced military variant. Alternatively you could force the player to first find USB drives or memory cards with the needed software before the devices can be used. 

Think of the interface CBM as a basic operating system that has all the ports you need to connect new tools, but needs additional software before the more advanced tools can be used.
