### ISSUE TITLE
disassembling rag crafted from bloody rag + water reverts into: bloody rag + water!

### ISSUE THREAD

**Issue by pipehat** [CleverRaven/Cataclysm-DDA#24012]
Game version:
cataclysmdda-0.C-7457

Operating system:
windows 10

Tiles or curses:
tiles

Mods active:
defaults

### Expected behavior
rag should always disassemble to thread

### Actual behavior
Dissassembling a rag produced by the bloody rag + water recipe reproduces the source water + bloody rag

### Steps to reproduce the behavior
see above

**Comment by Stone94** [comment]
I can confirm this, latest experimental. I cleaned the rag, disassebled and recieved a bloody rag

**Comment by cosmiccoincidence** [comment]
Can confirm, tested this and result were same as stated in the summary of this issue.
I tried to solve it also but couldn't for the life of me figure WHY it was ignoring the uncraft (disassemble) recipe.

**Comment by Brambor** [comment]
I think it is brilliant and should be left as an easter egg.

**Comment by AMurkin** [comment]
Easter rag. No, please fix it.

**Comment by Stone94** [comment]
Its an issue with the uncraft system, dissassemble returns what was used to craft the item, as such washing the rag is basically using the ingredients to craft a new rag and when you disassemble it, its returning water and bloody cloth because thats what was used to make the new cloth.

**Comment by primuspaul** [comment]
> Can confirm, tested this and result was the same as stated in the summary of this issue.
> I tried to solve it also but couldn't for the life of me figure WHY it was ignoring the uncraft (disassemble) recipe.

I don't see bloody rag in recipe_deconstruction.json. Is the game defaulting to deconstruction to recipe components when it fails to find the deconstruction entry in that file?

**Comment by primuspaul** [comment]
> > Is the game defaulting to deconstruction to recipe components when it fails to find the deconstruction entry in that file?
> 
> It is, but only if the recipe to craft has `"reversible": true` field.

I'm not at my home computer, but has anyone tried adding the correct recipe (resulting only in a rag) to the deconstruction file and, if that doesn't work, adding that reversible: true line to the bloody rag?

**Comment by primuspaul** [comment]
> > I'm not at my home computer, but has anyone tried adding the correct recipe (resulting only in a rag) to the deconstruction file and, if that doesn't work, adding that reversible: true line to the bloody rag?
> 
> You mean adding a deconstruction recipe for bloody rag that magically turns it into a clean rag?

Into filthy thread would make more sense. Whatever a filthy rag deconstructs into.

**Comment by Meuka** [comment]
> Into filthy thread would make more sense. Whatever a filthy rag deconstructs into.

Y'know, after reading this, I think it might be better to get rid of the bloody rag item and the crafting recipe and just start using the FILTHY flag instead.

**Comment by primuspaul** [comment]
> > Into filthy thread would make more sense. Whatever a filthy rag deconstructs into.
> 
> Y'know, after reading this, I think it might be better to get rid of the bloody rag item and the crafting recipe and just start using the FILTHY flag instead.

I suspect it has something to do with using rags to stop bleeding so that when they become "bloody" after use it basically marks it so you can't use it again without cleaning it first. I don't know if the game mechanics will allow you to easily make it so a filthy rag has different uses (meaning it cannot be used to stop bleeding).
