### ISSUE TITLE
Cataclysm Dark Days ahead continuous scrolling

### ISSUE THREAD

**Issue by ErikMalkavian** [CleverRaven/Cataclysm-DDA#24019]
Game version: 7461

Operating system: Windows 7 service pack 1

Tiles or curses: Problem occurs during first startup

Mods active: none

### Steps to reproduce the behavior  Here is a Youtube Video of the problem
https://www.youtube.com/watch?v=1q_wbzJ2Wzo&feature=youtu.be

Steps taken to solve it::

Ensuring Scroll Lock not on

Re-installing 3 times

Selecting Different Build in Launcher

Ended World Generation - On the next startup it stayed on Main Screen but the keys were frozen on "Load" tab

Changing Keyboards
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2107718/debug.log)

**Comment by ErikMalkavian** [comment]
Future troubleshooting attempted:

1. Windows 32-bit (x86)
2. Console build Windows 64 and 32 bit.  

Problem persists.

**Comment by ErikMalkavian** [comment]
Solved!  I re-installed the game to C:/Program Files and its inot doing that anymore.  I had installed it to another drive and I guess it hates that.

**Comment by DracoGriffin** [comment]
Thanks for the updates. Glad to hear you got it to work and enjoy the game.

**Comment by ZhilkinSerg** [comment]
Can you also provide `keybindings.json` and `options.json` from `config` folder from failed installation?

**Comment by lolmmbat** [comment]
Windows 10 64 bit, encountering same problem. I unplugged my mouse and keyboard and the scrolling continued. I also tried the above step to no avail, and ran the program in various compatibility modes. I do not have a keybindings.json file, but here is options. I tried changing software rendering to true with no success and changed it back to false.
[options.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/2238738/options.txt)

**Comment by ZhilkinSerg** [comment]
What is your game version?

**Comment by lolmmbat** [comment]
I tried with the latest release, and a few somewhat older builds. I did not try any really old versions though.

**Comment by lolmmbat** [comment]
Unless you meant tiles/console... it happens with both.

**Comment by ErikMalkavian** [comment]
Solved! I re-installed the game to C:/Program Files and its inot doing that anymore. I had installed it to another drive and I guess it hates that.

**Comment by OrenAudeles** [comment]
While the issues seem resolved, I find it weird that modifying the install directory has the effect it does.
