### ISSUE TITLE
NPC spawn rate scaling factor

### ISSUE THREAD

**Issue by latogato** [CleverRaven/Cataclysm-DDA#24034]
Game version: 0.C-28365 but really it is an old problem, just not well known.
Operating system: Any
Tiles or curses: irrelevant
Mods active: irrelevant

### Actual behavior
The percentage chance to spawn an NPC per hour is NPC_spawn_rate*(0.8 raised to the power of the actual_number_of_NPCs). The default NPC spawn rate of 0.10 that means 0.1% chance for the first NPC. With the maximum spawn rate (100) after 32 NPCs the chance for another NPC is 0.1% too.

### Expected behavior
Instead of the NPC spawn rate scaling factor we need a clear number, because it is confusing to the players, they don't know how this is working and because 100 is thousand times greater than 0.10, they expect a much bigger difference than that +32 NPCs.

**Comment by kevingranade** [comment]
No updates after months and no suggestion for a fix.
