### ISSUE TITLE
Sidebar not fully drawn in Windows Tiles version, since Build #7463

### ISSUE THREAD

**Issue by victorsegall** [CleverRaven/Cataclysm-DDA#24033]
Game version: Build 7463 through 7470

Operating system: Windows 10 Pro 64bit

Tiles or curses: Tiles

Mods active: 

[
  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "bio_mod",
  "craftgp",
  "realguns",
  "ew_pack",
  "makeshift",
  "More_Survival_Tools",
  "alt_map_key",
  "Mining_Mod",
  "mutant_npcs",
  "npc_traits",
  "more_locations",
  "FujiStruct",
  "more_buildings",
  "cityside",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks"
]

### Actual behavior

One of the UI changes in builds 7463 through 7470 has caused the sidebar to misbehave. The misbehavior isn't consistent, but generally its elements aren't being drawn when a turn is taken after saved game load. The newer builds misbehave less, but still refuse to draw portions of the character and environment info areas, tinymap, etc. All builds draw the tiles viewport correctly, and newer builds draw parts of the sidebar, including the event log.

I got no debug log entries from the issue.

**Comment by latogato** [comment]
I can confirm: https://discourse.cataclysmdda.org/t/screen-refreshing-problems-7468/15718/2
Easy to reproduce, zooming clears the sidebar.

**Comment by ZhilkinSerg** [comment]
Please test in upcoming build 7471. Zooming in and out should be good now, but report if something on the screen is still not being updated properly.

**Comment by latogato** [comment]
Tested, looks good! Thank you!

**Comment by victorsegall** [comment]
> Please test in upcoming build 7471. Zooming in and out should be good now, but report if something on the screen is still not being updated properly.

Seems solved. I won't have the reverted commit's artifacts problem, if that came back.
