### ISSUE TITLE
Weird chance of success

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#24048]
Game version: 0.7473

Operating system: Windows XP SP3 x86

Tiles or curses: curses

Mods active: default only

### Expected behavior
Some sensible number when trying to remove the bionic

### Actual behavior

![default](https://user-images.githubusercontent.com/11132525/41586092-8704a38c-73b4-11e8-945c-8483683d1361.png)

### Steps to reproduce the behavior
I debugged myself 10 in all skills and 20 intelligence. Then I tried to uninstall Internal Chronometer CBM and got this number. Seems like an overflow to me.

**Comment by Mooses2k** [comment]
Reproducable how?

**Comment by Night-Pryanik** [comment]
There is a "Steps to reproduce" section above with instructions.

**Comment by Mooses2k** [comment]
Right. Attempted to reproduce and with 200000 INT as well. Could not reproduce. Got a 1 percent chance. Close?

**Comment by Night-Pryanik** [comment]
I'll test it out tomorrow and check if this is still reproducable.

**Comment by Night-Pryanik** [comment]
Yeah, no longer reproducible.
