### ISSUE TITLE
No sound.

### ISSUE THREAD

**Issue by Achaean** [CleverRaven/Cataclysm-DDA#24045]
Game version:
Stable (0.c).
Operating system:
Linux (Debian Jessie (oldstable) x64 KDE).
Tiles or curses:
Tiles.
Mods active:
No.
### Expected behavior
Sound to be enabled.
### Actual behavior
No sound at all (although I compiled it, with sound enabled).
### Steps to reproduce the behavior
Running the game.

**Comment by ZhilkinSerg** [comment]
There are only two sounds included into basegame: one is played when you move cursor in main menu and another one when overmap terrain is searched and  cannot be found on map.

**Comment by Achaean** [comment]
THANKS ZhilkinSerg! :-)

Well...no sound at menus.
(Not an important thing though).

**Comment by ZhilkinSerg** [comment]
Can you try installing experimental version?

**Comment by Achaean** [comment]
Yes of course!
Which one?
Where can I find it?

**Comment by ZhilkinSerg** [comment]
Clone repository (you have probably done that already), checkout `master` branch instead of `0.C` branch and make with sound support as described in https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING.md#linux-native-sdl-builds

**Comment by Achaean** [comment]
Indeed! :-)
Problem has been fixed  at last github (experimental) version.
Keep up the good work!
Bye!

**Comment by ZhilkinSerg** [comment]
That is great.

Do not treat experimental version as something unstable and use it whenever possible (at least until `0.D`) - it was much improved after `0.C` (which is like 3 years old).
