### ISSUE TITLE
Full-screen, only partially visible.

### ISSUE THREAD

**Issue by Achaean** [CleverRaven/Cataclysm-DDA#24044]
Game version: 
Stable (0.c).
Operating system:
Linux (Debian Jessie (oldstable) x64 KDE).
Tiles or curses:
Tiles.
Mods active:
No.
### Expected behavior
To bi visible.
### Actual behavior
Partially off-screen.
### Steps to reproduce the behavior
Switching (at Options) Fullscreen No -> Yes.

1) Switching the software rendering doesn't changes something.

2) Downloading a precompiled binary from [](http://dev.narc.ro/cataclysm/jenkins-latest/Linux_x64/Tiles/), solves the problem, because it has a 3rd option(Windowed border).

I read the documentation, I couldn't find any related reference.

**Comment by latogato** [comment]
I'm just an ordinary cdda player but i suggest to try the experimental version, the stable is more than 3 years old, a lot of things changed in the game, maybe this problem is already fixed.

**Comment by Achaean** [comment]
Indeed! :-)
Problem has been fixed,  at last github (experimental) version.
Bye!
