### ISSUE TITLE
Reactivated manhacks are hostile towards neutrals 

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#24055]
Not sure if this is intended but seems wrong.

Game version: 0.C-28376-g8bf0d6b (tiles)

Operating system:Window 7

Mods active: Core and default

### Expected behavior
Friendly manhacks would follow you and engage hostiles when they see them.

### Actual behavior
Friendly manhacks attack everything that's hostile OR neutral to you. Often flying into the woods after random critters and going out of view.

### Steps to reproduce the behavior
Reactivate a manhack in an area with lots of neutral critters.

**Comment by kevingranade** [comment]
This is intentional.

**Comment by John-Candlebury** [comment]
>This is intentional.

Maybe for manhacks this is OK, but the bug affects every other friendly creature as well. For example, I dont think a dog should naturally behave like this

It is a valid issue.

**Comment by kevingranade** [comment]
This issue is for manhacks, a similar issue for dogs would be valid (including this one if it were edited).  
Cue long discussion about canine aggro AI design.
