### ISSUE TITLE
The impossibly bad day 

### ISSUE THREAD

**Issue by bananaedmonkey** [CleverRaven/Cataclysm-DDA#24054]
The impossibly bad day is meant to be a harder really bad day. With adverse effects that last longer than a day or 2. there is also the option of RBD tweaker, but that comes with the cost of the player not being able to do anything for a couple days, which is very boring. That scenario ends up boiling down to the player being able to find a safe house or dying. Once that is over the player is left with a heavily over-tuned character, free to roam the cataclysm.

The goal of the impossibly bad day is to create a challenge with effects that will persist weeks after the challenge has begun.

Story:

"The world was changing, and you decided you needed to change as well. You found some shady people, they said they could 'update' you. Make you more than human. Now you wake up and wonder if they ever intended to help you at all"

The scenario would take place in a black market installation facility, the one that was recently added and spawns in house basements. (it would be on fire as well)

Here is a sort description of the  scenario:

Limited professions: Broken cyborg, Failed cyborg

Breakdown of ailments:

Drunk, depressed, and sick:

All of the original effects that make a really bad day a great challenge, how could they not be included?

Infected in two places:

In the original really bad day challenge, the player only has one infection. If they take the "infection resistant" perk, the player would have a 15(?) percent change of just walking it off. With two infections, the only path to survival is to find a first aid kit spawn (which spawns two first aid kits) or antibiotics.

Broken arm:

A far more long lasting effect the player has to deal with. Makes the challenge carry over into weeks. The broken cyborg or failed cyborg professions build onto this, creating more problems that cannot be solved in one day.

Other suggested features of this scenario include:

fungal parasite

genetic chaos/ genetic instability (whichever is curable)

broken leg instead of broken arm

(this was posted on Reddit for troubleshooting as well.)

Any other suggestions are also welcome.

Distinctions from a really bad day (because I know how much you guys hate redundant features.):

focuses on a failed/ broken cyborg

starts off in the basement of a burning house.

two infections

broken arm

**Comment by Szara-ManOfHonor** [comment]
I'd so no to fungal parasite, seeing how rare antifungals are going to be for a starting character that is already so disadvantaged, and how they are effectively a rather quick death sentence without a cure.

Painkiller addition would be a good one for the black market bionics route.

**Comment by kevingranade** [comment]
No problem with soneone adding this, but we don't keep content requests around indefinitely.
