### ISSUE TITLE
Slimesprings from Acid Blood/Acidproof characters are vulnerable to acid

### ISSUE THREAD

**Issue by papersplease** [CleverRaven/Cataclysm-DDA#24068]
Game version: 0.C-28457-g98926b6

Operating system: N/A

Tiles or curses: N/A

Mods active: none

### Expected behavior
Slimesprings split from a blob/slime creature should share more or less the same characteristics, at least most basic ones, according to the common sense. They are parts of the creature's body, in the most literal sense!

### Actual behavior
Slimesprings split from a character with Acid Blood/Acidproof mutations are vulnerable to acid attacks, and easily die to spitters, acid and corrosive zombies.

### Steps to reproduce the behavior

- Get the Omnicellular mutation, allowing you to split into parts
- Get the Acidproof and/or Acid Blood mutation(s), making you immune to acid
- Spawn some slimesprings by overeating or overdrinking
- Expose your slimesprings to an acid attack

**Comment by kevingranade** [comment]
Expected behavior is invalid, I have no interest in extending slimesprigs to inherit player trsits.
