### ISSUE TITLE
Unreasonable perception-based dispersion punishment

### ISSUE THREAD

**Issue by Heaper327** [CleverRaven/Cataclysm-DDA#24067]
Game version: 0.C-28368 (latest experimental)

Operating system: Mac OSX 10.13.5

Tiles or curses: Tiles

Mods active: None

### Expected behavior

If the perception of the player is lower than a reasonable value (such as 14 or 16), the player will get additional aiming dispersion when firing a gun, allowing player to get rid of the additional dispersion by mutation/bionics/whatever

### Actual behavior

If the perception of the player is lower than 20 (which is nearly impossible to reach), the player will get 1 additional point of aiming dispersion for each level their perception is lower than 20, while the maximum additional dispersion is 8 points. For instance, a player with perception of 14 will get 6 points of additional perception (20-14=6). These additional perception seems insignificant, but has great impact on long distance shooting. 

### Steps to reproduce the behavior

1. Create a player with perception below 20
2. Get a gun and check out the part of its aiming dispersion to the right of the plus sign

**Comment by kevingranade** [comment]
Theres no rationale for why the values stated in your "expected behavior" are what they are.
If you find such a rationale, we can reopen the issue.
