### ISSUE TITLE
Cows are not tameable with Cattle Fodder

### ISSUE THREAD

**Issue by davidpwbrown** [CleverRaven/Cataclysm-DDA#24075]
Game version: experimental build 7481 

Operating system: WIndows 10 x64

Tiles or curses: tiles

Mods active: Filthy Clothing
Disable NPC Needs
Simplified Nutrition

### Expected behavior

Cattle Fodder used on a cow would tame the cow as per iuse.cpp
```
case CATTLEFODDER:
               if( mon.has_flag( MF_CATTLEFODDER ) ) {
```

etc

### Actual behavior
"there is nothing to be fed there" message and cow is not tamed
the cow does not have MF_CATTLEFODDER flag - I think is the cause in mammal.json
`"flags": [ "SEES", "HEARS", "SMELLS", "ANIMAL", "PATH_AVOID_DANGER_1", "WARM", "MILKABLE", "PET_WONT_FOLLOW" ]`

### Steps to reproduce the behavior
debug in a cow and cattle fodder, use cattle fodder on cow, get the response you'd get if an animal is not tameable with cattle fodder.

**Comment by ZhilkinSerg** [comment]
Thanks for reporting it. We'll need to reimplement json changes fron #24016 after #23930.
