### ISSUE TITLE
Player can step off the ledge in the mine shaft without falling

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#24070]
Game version:
0.C-28457
Operating system:
windows10
Tiles or curses:
tiles
Mods active:

### Expected behavior
Player will fall down a level if they step off the ledge in the mine shaft
### Actual behavior
Player can step off the ledge without warnings and float indefinitely. The ledge acts like solid terrain and costs as many movement points to move across as ordinary floor.

![screenshot 1566](https://user-images.githubusercontent.com/18560216/41806861-1148f7e0-768b-11e8-937d-b0980a540dad.png)

**Comment by Night-Pryanik** [comment]
Z-levels enabled?

**Comment by BorkBorkGoesTheCode** [comment]
Yes.

**Comment by OzoneH3** [comment]
Kinda related #23537

**Comment by ssorpg** [comment]
I think this may have already been fixed. I tried to reproduce this issue and I simply fall through the mine shaft. Is there a save game to replicate this?
