### ISSUE TITLE
Using a container for harvesting maple sap as a container for another maple tree will duplicate the container.

### ISSUE THREAD

**Issue by Lasiace** [CleverRaven/Cataclysm-DDA#24072]
**Game version:**
Build 7480
**Operating system:**
Windows 7
**Tiles or curses:**
Tiles
**Mods active:**
- Vehicle Additions Pack
- Filthy Clothing
- More Buildings
- Disable NPC Needs
- Simplified Nutrition
### Expected behavior
The container being taken from one maple tree should be removed and placed on the other tree
### Actual behavior
The container is from the original tree is not removed, and a duplicate (along with its contents) is placed on the other tree.
### Steps to reproduce the behavior
1. Find two maple trees close to each other
2. Use a tree spile on one tree and place an appropriate container
3. Use a tree spile on the other tree and, when prompted, select the container being used in the first maple tree.

Here is a screenshot of the error in action. ![maple tree bug](https://user-images.githubusercontent.com/24522330/41807213-c83c1eec-76fd-11e8-8daa-fbcb4c2cc38c.PNG)

**Comment by alanbrady** [comment]
I cannot reproduce this issue as of a7b46f9bf6

**Comment by OzoneH3** [comment]
Fixed: Container correctly removed from previous tree.
