### ISSUE TITLE
Blacklisted multivitamins makes "Collect 200 Multivitamin Pills" mission impossible to complete

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#24089]
Game version: 0.C-7486

Operating system: Windows XP SP3 x86

Tiles or curses: curses

Mods active: default only (Simplified Nutrition included)

### Expected behavior
One should be able to complete the "Collect 200 Multivitamin Pills" mission with default mods.

### Actual behavior
Simplified Nutrition mod being the default one, "Collect 200 Multivitamin Pills" mission is impossible to complete as there are no multivitamins in the world

### Steps to reproduce the behavior
Enable Simplified Nutrition mod, get to the "Collect 200 Multivitamin Pills" mission, realize there is no way to complete it.

**Comment by ZhilkinSerg** [comment]
Need to blacklist mission based on item blacklist.

**Comment by kevingranade** [comment]
Fix: disable simplified nutrition mod.

**Comment by Cyrano7** [comment]
@Night-Pryanik Maybe just take the vitamins off the blacklist since they still serve some purpose.

**Comment by Night-Pryanik** [comment]
> Fix: disable simplified nutrition mod.

Simplified Nutrition is a default mod, new players wouldn't have an idea where is the vitamins in the game.
