### ISSUE TITLE
Add quick drop just lifted item

### ISSUE THREAD

**Issue by muravey-omsk** [CleverRaven/Cataclysm-DDA#24099]

**Comment by Night-Pryanik** [comment]
Add some detailed description so we should understand what do you mean.

**Comment by ObsidianBottle** [comment]
I think they meant a "drop last item picked up" command like the one in DCSS for example.

**Comment by muravey-omsk** [comment]
> I think they meant a "drop last item picked up" command like the one in DCSS for example.
yes. Sorry for my english.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
