### ISSUE TITLE
Throwing stuff at shocker zombies will shock you.

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#24092]
Game version: 0.C-28462-gb3d83b6

Operating system: Windows 10

Tiles or curses: Tiles 

Mods active: Filthy Clothing, Disable NPCs Needs, Simplified Nutrition.
### Expected behavior
Throwing weapons at shocker zombies (especially non conductive weapons) does not trigger the "attacking the zombie shocks you" effect
### Actual behavior
Throwing weapons at shockers will zap you regardless of distance and what the weapon is made of.
### Steps to reproduce the behavior
Throw a weapon at a shocker zombie 
tested with: Throwing knives, Throwing axes, rocks, sharp rocks, wooden spear, wood axe, wooden tonfa, wooden arrow, 40mm incendiary, raw lasagne and chocolate waffle.

**Comment by ZhilkinSerg** [comment]
Fixed in #24108.
