### ISSUE TITLE
Add missing 'Dairy' tag to several foods

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#24097]
Game version:
0.C-28499-g744491a

`Cheeseburger, chump cheeseburger, hamburger helper, hobo helper, clam chowder` all are prepared with milk or cheese, but are missing the `dairy` tag.

Then there is the fringe cases of `pancake, fruit pancake, chocolate pancake, waffle, fruit waffle, chocolate waffle, brioche` where the recipe calls for either milk, powdered milk, condensed milk or coconut milk.. making 1 option out of 4 non-dairy. Considering how rare coconut milk is, it might be a good idea to add the `dairy` tag to these anyway.

Of course the best option would be to have the tag be created depending on what you use in a given recipe, as there's plenty of them where you may substitute sugar with milk or vice versa. But this would be a lot of work and I just wanted to highlight some easily fixable mistakes.

**Comment by NotFuji** [comment]
Just to be a stickler for accuracy, cheeses only contain trace amounts of lactose.

But regardless, checking components to decide whether or not a food is "dairy" is certainly possible, but the tag would still have to be added to everything that should use it by default.  World-spawned items aren't made of anything specific.

**Comment by Tharn** [comment]
Good point. Still, I think right now there's a bunch of recipes with cheese (no milk) set as 'dairy', so in the interest of completeness we should either include all of them, or none. Including the cheeses themselves.

**Comment by TechyBen** [comment]
As a RP I can just skip them. But as a game mechanic it would need to be added or tracked.
I'd also like the option for items made with the alternatives to not have dairy added once made.

<- Suffering from that Cheeseburger he had yesterday! (Cheese "trace" amount varies as much as sensitivity)

**Comment by lucasmr** [comment]
For items that have optional diary in the recipe, like if using coconut milk, a different recipe would need to be created. As far as I know, there is currently no way to add material tags in an item after cooking, because all item attributes are hard-coded.

**Comment by TechyBen** [comment]
Ok thanks. If it's not going to clutter the crafting lists, I may go through and do such a thing (milk/grain alternatives).

**Comment by y2s82** [comment]
Shouldn't this issue be closed as PR #24170 fixes it?
