### ISSUE TITLE
Allow weapons from the axe/mace families to be stored in belts.

### ISSUE THREAD

**Issue by Lasiace** [CleverRaven/Cataclysm-DDA#24098]
So after playing the game for a while, I noticed that weapons such as the mace, warhammer, and battleaxe couldn't be sheathed on anything, unlike swords, Obviously, I know why you can sheath swords, and I do also know why this isn't done with spears - one of the things that makes spears impractical IRL is their sheer length, making it difficult to carry, and spears are pretty strong gameplay-wise anyway so it helps balance. However this doesn't really seem to apply as much for weapons in the axe/mace families, since their length is quite similar to swords, along with their weight.

After doing a bit of research, it seems that people do indeed store their axes and maces in their belts, in a sort of "crossdraw". Something like this:

![image](https://user-images.githubusercontent.com/24522330/41888969-9d079622-793a-11e8-841f-586bbf42d9bf.png)
![image](https://user-images.githubusercontent.com/24522330/41888972-a49c75f6-793a-11e8-94c1-d8c6ba69f180.png)
[source](http://myarmoury.com/talk/viewtopic.27524.html)

It also seems that people have also used belt rings for this purpose, but that it proved to be somewhat less practical since the weapon would move around in ways that would slap against the leg.

Axes and maces also don't seem to be any stronger than swords, so I don't think that this should significantly affect balance. Admittedly, this means that things like leather belts might become more valuable to get if this also applied to some of the starting improvised weapons, like the cudgel. I don't think that it would be that big of a deal though, and additionally you could make it so that belts become a bit more encumbering when they are used to carry weapons this way to balance things out.

**Comment by TechyBen** [comment]
It also looks encumbering. Can the game automatically account for this? I know it does for items with straps, but here the axe/mace would not have a strap.

A belt with a small axe would not be as encumbering as one with a large axe, right?

**Comment by Amariithynar** [comment]
Having it stored on your belt would actually be less encumbering in general, as the weight would be distributed over a larger area (that being the belt, in most cases). Same difference between having an carpenter's tool belt versus a toolbox. You have to carry the toolbox around, it's decently hefty on its own, and it typically takes up more space than just the sum of all the tools that it holds. Conversely, having everything in pouches and loops hanging off a heavy leather belt is less cumbersome to carry than the toolbox, but also fairly more involved in picking up and putting down than a toolbox.

**Comment by lancewf** [comment]
I created two possible options to add this feature. #26516 and #26519. 

#26516 - Add a new craftable custom belt that allows war hammers and maces to be attached to it. 
#26519 - Modifies the fireman belt to allow fire axes, war hammers, and maces to attach to it. The belt is not craftable but can be found on fireman zombies.

**Comment by Night-Pryanik** [comment]
I think we can add both of your options, not only one of them.

**Comment by lancewf** [comment]
I have not thought of merging both options. That sounds with me.
