### ISSUE TITLE
Disambiguation of action names

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#24102]
Game version:
0.C-28499

### Expected behavior
Possible to differentiate terms for action names in Keybindings window (set in inventory_selector::inventory_selector) from others.
### Actual behavior
Used actions names 'Home' and 'End' are too general. And cause problems with translations.
### Steps to reproduce the behavior

1. Open eat|read or another inventory selector window
2. Hit `?` to open Keybindings window
3. 'Home' or 'End' actions in list in some translations could be translated to wrong terms

Possible solutions:

- Rename actions
- Set translation context for them ( `translate_marker_context( "action_name", "Home" )` )

Related: #21760

**Comment by nexusmrsep** [comment]
As a seasoned translator for CDDA I can confirm that in some cases translating raw snippets out of context can lead to lot of laughs while playing the translated version.

**Comment by AMurkin** [comment]
I think I should close this, and we will create separate issues for specific strings, if necessary.
