### ISSUE TITLE
Bug Report: Reach Refugee Center Failure

### ISSUE THREAD

**Issue by Soulsphere** [CleverRaven/Cataclysm-DDA#24109]
Game version: 0.C-28254-g63ff4d3

Operating system: Windows 10 Professional

Tiles or curses: Tiles

Mods active: The default Mods (Dark Days Ahead, Filthy Clothing, Disable NPC Needs, and Simplified Nutrition)

### Expected behavior
None

### Actual behavior
Failed "Reach Refugee Center" mission.

### Steps to reproduce the behavior
I have not attempted to reproduce the behaviour. I wouldn't know how.

----------

I fired a Browning M2 from an APC, at a shocker zombie (killing it), and I received a messaged stating that I had failed the "Reach Refugee Center" mission. After exiting the APC, a while later (without moving the APC), I found two dead humans who were apparently killed by a Browning M2. My guess is that these two humans were suppose to be in the refugee centre. Before firing the Browning, I emptied and reloaded it. I also changed some of the options for the weapon (setting it to auto aim and semi-auto firing).

Also, I was nowhere near the refugee centre at the time this bug occurred. The centre is at (-192, 343) and my position during the bug was (31, 86).

Additional Information: The world I'm using has static NPCs on with dynamic NPCs off.

The attached file contains the messages that I received from shortly before the bug to shortly after it. The shocker zombie was fighting a riot bot as the text will show. (And yes, my mounted M2 Browning died twice, which I'm guessing is where the two bodies came from).

![text from cdda reach refugee center bug](https://user-images.githubusercontent.com/5923681/41962197-422bfecc-79a9-11e8-83d8-4edc86c2d44f.jpg)

**Comment by AMurkin** [comment]
Have seen this too with mouted laser rifle.
Best guess from discord: fake turret NPC has died.

**Comment by ZhilkinSerg** [comment]
Fixed in #24108.

**Comment by Soulsphere** [comment]
I have tested this is a later version and it appears to have been fixed.
