### ISSUE TITLE
PK Re-balance error

### ISSUE THREAD

**Issue by dmeaden** [CleverRaven/Cataclysm-DDA#24129]
Game version: newest

Operating system: Windows 10

Tiles or curses: Tiles

Mods active:

### Expected behavior

To create a character.

### Actual behavior

There's an error when I try to create a new character here's the screenshot:
![cata](https://user-images.githubusercontent.com/40705229/42118125-c14cbc36-7bf8-11e8-9444-f4ef87d5b192.png)

I've tried downloading the newest mod and replacing it.
And I've tried adding

"houses": {
"house_two_story_basement": 1,
"house": 1000,
"house_base": 333
},

like the other posts say, but it dosen't work.

### Steps to reproduce the behavior

Use the PK mod with the Launcher.

Thanks for any help.

**Comment by Cyrano7** [comment]
@dmeaden PK's mod actually has it's own repo independent of this one. You can submit an issue there https://github.com/pisskop/PKs_Rebalancing/issues

**Comment by dmeaden** [comment]
Ok, thanks.
