### ISSUE TITLE
LUA does not work with time_duration

### ISSUE THREAD

**Issue by Lorith** [CleverRaven/Cataclysm-DDA#24126]
Game version:
Build 7502
Operating system:
Win7
Tiles or curses:
Tiles
Mods active:
None
### Expected behavior
LUA functions actually work before they are removed
### Actual behavior
player:add_effect and probably add_env_effect spew errors no matter what you do because they no longer accept int for duration and cannot understand X_turns/X_minutes/X_hours after the change to time_duration.
### Steps to reproduce the behavior
Open LUA console, try anything involving player:add_effect, get told "')' expected near '_hours'" or _turns/_minutes.

**Comment by ZhilkinSerg** [comment]
#23544

**Comment by ZhilkinSerg** [comment]
I guess we can fix this.

Dirty branch with some unwanted changes and somewhat strange syntax - https://github.com/CleverRaven/Cataclysm-DDA/compare/master...ZhilkinSerg:msys-lua-time-duration?expand=1

Example code to add effects on that branch:

```lua
local tdX = time_duration(0)
local td4 = time_duration.from_minutes( tdX, 2 )

print ( "time_duration4:"..tostring(td4) )

local nude_effect = efftype_id("nude")
local nude_effect_duration = time_duration.from_minutes( tdX, 10 )

player:add_effect(nude_effect, nude_effect_duration)

local milked_effect = efftype_id("milked")
local milked_effect_duration = time_duration(0):from_minutes( 5 )

player:add_effect(milked_effect, milked_effect_duration)
```

**Comment by ZhilkinSerg** [comment]
You can now create `time_duration` variables like this:

```lua
local td1 = game.get_time_duration( 1234 ) -- 1234_turns
local td2 = TURNS(5)                       -- 5_turns
local td3 = MINUTES(10)                    -- 10_minutes
local td4 = HOURS(3)                       -- 3_hours
local td5 = DAYS(100)                      -- 100_days
````
