### ISSUE TITLE
Using Long Sticks for Curtains.

### ISSUE THREAD

**Issue by Rod995** [CleverRaven/Cataclysm-DDA#24141]
### Expected behavior

Long sticks should be used for curtains.

### Actual behavior

Heavy sticks are used for curtains instead.

### What to change
I say that we should use long sticks instead of heavy sticks for curtain building.

- [ ] Replace Curtain Recipes

**Comment by CoroNaut** [comment]
We might need a better differentiation between heavy sticks and long sticks. If both are refined in some way to be used in construction, then it doesn't make sense that heavy sticks would be found dropping from trees. The other way around however, if heavy sticks are meant to be dropped straight from trees, and not yet refined, then they shouldn't be used in construction. As for very low tech construction, I can see heavy sticks being used, but for actual houses, I doubt it.

Perhaps we should include an extra step: leave heavy sticks alone and instead produce long sticks from planks, this would mean they are definitely in a refined state and worthy of use in construction.

**Comment by TechyBen** [comment]
"heavy" and "long" do not seem to be what most players think they are. The game take no notice of "refined" vs "branch". Just length (AFAIK). A "long" stick is multiple tiles long... thus it won't be on a single tile window. However, some windows in game are generated 2 tiles long (some houses have 1 tile windows, some have 2 side by side).

So either we keep it as is, and assume two 1 tile "heavy sticks" are used on curtain (reasonable as most have a divider in the center). Or we change it so two windows side by side will drop a single "long" stick. However, I've no idea how easy/hard that is to code to prevent it dropping two long sticks. :(

**Comment by Rod995** [comment]
smh

What about a more "refined" one like CoroNaut said.
Just making Rods from long sticks instead of making them from planks.
We could also change windows into two groups.
Makeshift ones made from heavy sticks, glass shards, and some type of adhesive or nails.
And regular ones made from rods, nails, and glass.

**Comment by kevingranade** [comment]
I had thought about refining a long stick into a [pole](https://github.com/CleverRaven/Cataclysm-DDA/issues/24017#issue-332914941), but I've failed to come up with a pressing need to have this intermediate stage, can you think of one?  In reality, you can trim down a branch to a pretty reasonable level with just some elbow grease and a rock, which you need to get one in the first place.
Something like a quarterstaff is a totally different thing and requires a blade of some kind to smooth and taper it properly, but I think all the recipes that imply a finished pole like that also require a blade of some kind, so I'm not clear on what you get out of that extra step.

> As for very low tech construction, I can see heavy sticks being used, but for actual houses, I doubt it.

IIRC most finished construction uses long_stick -> 2x4 as a construction material, I don't think anything uses sticks directly.  In reality 2x4s should be fabricated from logs, but that's a whole 'nother issue.

As @TechyBen points out, the main thing we need for getting long sticks from curtains is a mechanism for distinguishing between two-tile curtains and single-tile curtains.  I haven't looked at that part of the code in a *looong* time, so I don't have any ideas.

**Comment by Rod995** [comment]
Closing because I can.
~~I believe Cake-Pie has solved this.~~

**Comment by Rod995** [comment]
Discussion can still continue though.
