### ISSUE TITLE
Options: terminal resizing not working in-game.

### ISSUE THREAD

**Issue by Kite1024** [CleverRaven/Cataclysm-DDA#24157]
Game version: cataclysmdda-0.C-7517

Operating system: Windows 10 x64 (latest version as of juli '18)

Tiles or curses: curses

Mods active: none

### Expected behavior
When changing the terminal width and height in the options menu - saving afterwards - and restarting the terminal should change size (in this case 80->160 and 24->48 w/h).

### Actual behavior
The terminal does not change size and the setting is reset. Perhaps important to note is that changing the config file _manually_ does change the screen size (but only once, I restarted just now and it's back to 80/24). Of all the other options I changed (mostly other tabs), only the terminal resizing did not seem to work.

### Steps to reproduce the behavior
Change the width/height of the terminal in the options menu.

**Comment by Sthreeve** [comment]
I'm having the same issue.  The only differences are that I'm using game version 0.C-7592 and trying to set my terminal size to 192 wide by 52 high.  Operating system, curses, mods, and the behavior are completely the same.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 07 February 2019 on Windows 10 Pro x64, though I'm testing on tiles version. Can anyone confirm this on curses?

**Comment by ifreund** [comment]
>Can anyone confirm this on curses?

You can't set the terminal from the game in curses,  it just uses whatever size the terminal you start it in was at.
