### ISSUE TITLE
Performance bottleneck in light arc calculation

### ISSUE THREAD

**Issue by CIB** [CleverRaven/Cataclysm-DDA#2415]
Version: 65a20da58e62e5423ffd537e71bdc3d3d75ee5ba
http://i.imgur.com/EhLj3Ut.png

Need to reduce calls to tan.
##

**Comment by illi-kun** [comment]
@kevingranade, how the overhauling of the lighting system done by you affect this issue?

**Comment by kevingranade** [comment]
Most of the sources of this are gone, the only one remaining is the code
that projects directional light, which still uses the old ray tracing code,
everything else uses the shadow casting implementation.

**Comment by Mooses2k** [comment]
Is this still valid after the recently lighting/raytracing work? (I'm looking through the oldest issues)

**Comment by kevingranade** [comment]
Yes, directional light such as vehicle headlights still uses the older and very unpergormant solution.  
We need a wrapper around the shadowcasting functions to have them operate on an arc instead of a whole circle or sphere.
