### ISSUE TITLE
Saber Teeth cancel Mandibles, but not vice versa

### ISSUE THREAD

**Issue by papersplease** [CleverRaven/Cataclysm-DDA#24156]
Game version: 0.C-28739-g966bfea

### Expected behavior
Saber Teeth and Mandibles mutations should be incompatible with each other, because they change the same body part (mouth).

### Actual behavior
It's possible to gain both mutations at the same time by getting Mandibles after Saber Teeth.

**Comment by ZhilkinSerg** [comment]
Closed in #24161.
