### ISSUE TITLE
QoL Change Vehicle controls menu to allow multiple changes before exiting.

### ISSUE THREAD

**Issue by TechyBen** [CleverRaven/Cataclysm-DDA#24166]
Game version: 7520

Operating system: Windows 7 (others not tested)

Tiles or curses: (Tiles)

Mods active:

### Expected behavior
To be able to add multiple "turn off/on" requests to the vehicle control interaction menu (^ or E for examin on controls tile). For example choose to turn off a refrigerator and a recharger at the same time.

### Actual behavior
When using vehicle interaction (^ or E for examin on controls tile) to turn on or off a device, the game applies this instantly and exits the menu. If a player wishes to turn on headlights and ilse lights, or turn off fridge and recharger, they must go back into the menu for each item.

### Steps to reproduce the behavior
Add multiple electronic devices to a vehicle and activate more than one.

Currently it is working as intended, and it would only save a few button clicks, so I guess it would be more a GUI toggle thing. As cars with just headlamps/dome lights won't have long lists of items to turn on and off. But vehicles with lights, recharger, turrets, fridge, stereo etc, can get tedious to turn everything on and off when entering/exiting. So a toggle to auto exit the menu (current) or wait in menu (proposed) between selections would be helpful.

**Comment by tinukedaya** [comment]
I made a similar suggestion about a year ago... Would love to see that happen. #21750

**Comment by mlangsdorf** [comment]
I'm looking at implementing this, and it's not as easy as I would like. I'd really prefer the 21750 approach, but Kevin seems to want to go through the menu repeatedly.
