### ISSUE TITLE
Some items don't use filters for respiratory protection

### ISSUE THREAD

**Issue by papersplease** [CleverRaven/Cataclysm-DDA#24176]
Game version: 0.C-28739-g966bfea

### Expected behavior
Items with high respiratory protection should only work with filters, as of #23662 

### Actual behavior
Neither entry suit nor any type of power armor (RM13, basic/light/heavy) use filters to protect the user from inhaling hazardous gases.

**Comment by Zireael07** [comment]
Filters were implemented only for gas masks.

**Comment by papersplease** [comment]
@Zireael07 Both ANBC and hazmat suits work with filters, for example.

**Comment by ZhilkinSerg** [comment]
As for powered armor it is limitation of current system - items can only have single type of ammo and it is plutonium for power armor.

Entry suit can and should be fixed (similar to ANBC).

**Comment by Rivet-the-Zombie** [comment]
It's probably safe to assume that the powered armor suits utilize self-cleaning air filtration systems.

**Comment by Cyrano7** [comment]
So powered armor suits don't need filters and the entry suit was fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/24181
