### ISSUE TITLE
Acid and fire protection is affected by having a filter ready

### ISSUE THREAD

**Issue by papersplease** [CleverRaven/Cataclysm-DDA#24174]
Game version: 0.C-28739-g966bfea

### Expected behavior
The protective gear should protect from acid and fire at all times, if designed to do so. The filter is needed for respiratory protection. (smoke, gases etc)

### Actual behavior
Acid and fire protection depends on having an active filter. It looks especially bizarre in fully enclosed suits like (A)NBC or the hazmat suit, which only use filters to protect the user from inhaling hazardous substances.

**Comment by Vasyan2006** [comment]
Acid and fire protections are calculated based on enviromental resistance of the item.
This can solved by separating NBC into suit with constant protection (except face) and gas mask with filter. Most real NBC suits uses common gas masks, so this separation should not be a problem.
