### ISSUE TITLE
Furniture that can't be deconstructed gives wrong info to player

### ISSUE THREAD

**Issue by lucasmr** [CleverRaven/Cataclysm-DDA#24177]
### Expected behavior
User tries to deconstruct a sink. Game should warn the player that it is not possible to do that.

### Actual behavior
The game gives a wrong message: "You cannot build there!". I thought this was a bug, but looking at f_sink furniture, there is no "deconstruct" field, because it is porcelain.

### Steps to reproduce the behavior
Try to deconstruct a sink.

**Comment by Amariithynar** [comment]
Same happens with Centrifuges and other uncraftable terrain that you'd normally think you could deconstruct the OTHER components off of, like all the piping off of sinks, for example.
