### ISSUE TITLE
Game wont load after updating(error with PK Rebalancing)

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#24185]
Game version: 7526 (previously 7438)

Operating system: Windows 10

Tiles or curses: Chesthole

Mods active:
PK-Rebalancing
NPC Traits
Filthy Clothes
More Buildings

### Steps to reproduce the behavior Try opening the game
![cddaerror2](https://user-images.githubusercontent.com/40806874/42241981-459e4cbe-7ec1-11e8-82d5-fb77a78774f9.png)
[Grayland.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2160862/Grayland.zip)

**Comment by ZhilkinSerg** [comment]
PK Rebalancing mod was removed from Cataclysm and is maintained in separate repository - https://github.com/pisskop/PKs_Rebalancing. There is an opened and unmerged PR (https://github.com/pisskop/PKs_Rebalancing/pull/49) which addresses this issue. You can take updated file from this PR.
