### ISSUE TITLE
Blazemod json parsing problem

### ISSUE THREAD

**Issue by clarencen** [CleverRaven/Cataclysm-DDA#24182]
Game version: 7525

Operating system: Windows

Tiles or curses: Tiles

Mods active: Blazemod and pretty much everything else

### Expected behavior

Loading happens successfully

### Actual behavior

Error which prevents the loading, in https://github.com/CleverRaven/Cataclysm-DDA/pull/24162/commits/bdcebe854c16160096755b85cfc0e98c1c4dbe8e all changes with "using" have triple square brackets, i guess it's just a typo and 2 brackets needed.

### Steps to reproduce the behavior

Just load any save with BlazeMod active

**Comment by clarencen** [comment]
Sorry if unclear, but the issue is - in the commit above all changes which add the "using", for example:

`"using": [ [ [ "soldering_standard", 10 ], [ "adhesive", 1 ] ] ],`

cause json parsing error. So removing one set of square brackets seems to fix the issue. Seems quite simple.

**Comment by ZhilkinSerg** [comment]
Fixed in #24184.
