### ISSUE TITLE
[Bug] Ember Carrier (More Survival Tools mod) cannot be used to light fuses

### ISSUE THREAD

**Issue by Amariithynar** [CleverRaven/Cataclysm-DDA#24199]
Game version: 0.C-28851-gbd50ba8 (tiles)

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: Tall Buildings, More Survival Tools, StatsThroughSkillsIV, Vehicle Additions Pack, Tanks and Other Vehicles, Alternative Map Keys, Boats, Craftable Gun Pack, Bright Nights, Folding Parts Pack, Makeshift Items Mod, More Buildings, Mutant NPCs, Beta National Guard Camp, Disable NPC Needs, Simplify Nutrition

### Expected behavior
With a lit Ember Carrier, able to ignite fuses on explosives like Match Head Bombs and Dynamite
### Actual behavior
Fuse is not lit; get the message, "You need a source of fire!"
### Steps to reproduce the behavior
Craft a dynamite/match head bomb/other explosive that requires lighting a fuse. Craft an Ember Carrier, fill with Tinder, and light with fire source (burning fire, match, lighter). Discard all other sources of ignition. Attempt to ignite fuse of explosive.

~~~
My first time submitting a bug on CDDA, so please, be gentle.

**Comment by Night-Pryanik** [comment]
The same reason as in #21005.
