### ISSUE TITLE
Git pull request system

### ISSUE THREAD

**Issue by i2amroy** [CleverRaven/Cataclysm-DDA#2419]
I've noticed that recently we've had a bit of problems with things getting pulled in while they are still being worked on. Since we can't flag pull requests, I propose a new system of "tagging" PR names.

If a new pull is still being worked on, please add a [WIP] at the end of the title text. This will tell the reviewers that you still intend to add more to the PR and we don't need to review it yet. When it's ready to be reviewed by a merger just edit the title text to remove the [WIP].

If you are also looking for suggestions then mark it with [CR] - (comments requested).

Hopefully this can help speed up our review process by allowing us to only review the things that are ready for it, and will prevent anything that isn't completely ready from being merged in.

One more thing. When marking for issues please mark as "XXXX #???" Where XXX is on this list:
close
closes
closed
fix
fixes
fixed
resolve
resolves
resolved
And ??? is the number. This automatically closes the issue when the PR is pulled in, and allows mergers to work slightly faster. To close multiple issues format it as "XXXX #???, XXXX#???".

**Comment by kevingranade** [comment]
This is pretty much the standard now, if we want a reminder it needs to go in documentation somewhere, not the issue tracker.

**Comment by KA101** [comment]
>if we want a reminder it needs to go in documentation somewhere, 

Done!
