### ISSUE TITLE
Inconsistent seeding and obtaining of seeds from crops

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#24203]
Game version: O.C-28852

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Issue
Many plants create seeds separately from the fruits upon harvesting, even when it's unnecessary, especially with the recent, very nice, addition of crafting seeds from the wider variety of plants.
Afflicted plants include both berry bushes and crops.

Edit: following part was my mistake/failing to notice acquired seeds
<s>At the same time, there are vegetables one can grow from a seed, but the resulting crop cannot be further reseeded (do not create any seed nor seed can be crafted from the crop itself), even though IRL it is perfectly possible - thinking of vegetables such as onions, carrots, sugar beets here. Pinging @Kelenius as they're the person who made a very nice commit regarding seeds not long ago.</s>

**Comment by nexusmrsep** [comment]
I agree in general, but disagree on the last part. Carrots, sugar beets, onions considered as produce are not reproductory seeds themselves, you don't grow new produce directly from them. You can plant onion for example, but you have too keep it in the ground untill it grows seeds and then plant the seeds.

**Comment by FulcrumA** [comment]
True. What I wanted to underline, as crudely and badly as I may have, is that there's currently no way at all to reproduce those vegetables.

**Comment by Kelenius** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/item_groups.json#L8381
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/mapgen/gardening_store.json

There's a lot of locations where they can spawn, actually.

**Comment by nexusmrsep** [comment]
What do you think about adding onions & carrots at very low chance find in foraging in spring/summer? It seems [wild carrot](https://en.wikipedia.org/wiki/Daucus_carota) is a sub-species of a garden carrot. It also seems that are some [wild onions](https://honest-food.net/how-to-harvest-wild-onions/). This might be a wild shot, so I'm asking for opinions.

**Comment by FulcrumA** [comment]
@nexusmrsep @Kelenius 
My bad. I was sure for some reason that in the past I harvested a vegetable such as carrot without acquiring any seeds. I tried it again right now and I did get seeds, so I suspect that the last time I simply did not notice something. The second part of the ticket then is a mistake.

**Comment by Amariithynar** [comment]
@TechyBen if you plant a carrot root, it will itself grow into an entirely new carrot plant, and can eventually go to seed itself, and then the seeds can be planted and a new crop grown from that.

"Wild Vegetable" works as a generic, since there's plenty of vegetation that we don't domesticate that is still perfectly edible, like nettles for making nettle tea, or dandelions; I'd still like to see wild variants of garlic, carrots, etc. though.

**Comment by Tharn** [comment]
Pumpkins should yield plenty of seeds when used to make food. As it is now I'm having a hard time getting pumpkin seeds at all.
