### ISSUE TITLE
Runtime error crash upon start

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#24215]
Game version: O.C-28852 / build 7540

Operating system: Windows 7 64bit

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
The game starts and works.

### Actual behavior
It doesn't.
Crashes on startup with Microsoft Visual C++ Runtime Library
Error code 40000015 with offset 000000000019f1f7
Last version that worked fine, played yesterday: build 7536

Related to several similar reports in the faraway past happening for all kinds of reasons.

**Comment by ZhilkinSerg** [comment]
Could be https://github.com/CleverRaven/Cataclysm-DDA/pull/24212

**Comment by ZhilkinSerg** [comment]
I cannot reproduce on Windows 10 64 bit. Can you please try running 7536 - is it working now?

**Comment by FulcrumA** [comment]
7536 works as it worked before, had to downgrade to that version though.
Interestingly enough, I've updated the game again a moment later, this time to the build number higher than the one in this ticket - 7541 so I assume whatever was the cause was resolved sometime in the meantime.
Either way, closing this now as resolved. If you did something - thanks :P

**Comment by ZhilkinSerg** [comment]
Didn't do a thing. Maybe that was failed download?

**Comment by FulcrumA** [comment]
I thought about it, but it had to be some consistent network failure since I attempted to reupdate a couple of times. 

I also restarted the PC, since I like to listen to podcasts and audiobooks while playing and between some of the streaming websites and CDDA, my RAM is apparently running out (or so the OS maintains). But restarting had no effect. 
A similar error thrown by different applications I've read about online seemed to have plenty of possible causes: from antivirus acting up to corruption of some system files.

Perhaps you could suggest some debugging/logging soft? If the issue resurfaces, I could try to use that to provide more info of what's going on.
