### ISSUE TITLE
Breaking a long stick needs a cutting tool

### ISSUE THREAD

**Issue by MisterFox** [CleverRaven/Cataclysm-DDA#24217]
I needed a cutting tool. I saw that the long stick can disassemble into 2 heavy sticks. The description of the long stick says 'can be broken into heavy sticks for crafting.' I tried to disassemble it, but I can't disassemble the long stick into a heavy stick without having a cutting tool in the first place.

**Proposal:** Make disassembling a long stick not take any tool requirements. You can just break it over your knee or hit it against a tree or something, right?

**Comment by Rod995** [comment]
Get something sharp, mebbe glass or something.

**Comment by Rod995** [comment]
Also, I think that would more or less result in splinters and two broken sticks.

**Comment by MisterFox** [comment]
Glass shards, glass shivs, and sharp rocks don't have any cutting quality. only butchering.

**Comment by Rod995** [comment]
What a shame.
Mebbe we make [More Cutting Weapon] PR first tho.

**Comment by CoroNaut** [comment]
1 leg hitpoint taken for each stick :D

**Comment by Amariithynar** [comment]
Any recipe using heavy sticks uses a cutting tool as well, far as I know? So I don't see why this one particularly requires one, but it should be relatively simple to make, so unless this is easy to fix, I'd suggest skipping it. A piece of metal scrap and a rag make a makeshift knife, for example. Smashing something metal, like a locker in the survivor shelter to get a pipe to make your first crowbar, will also give you plenty of scrap to use, then you just need tear down a curtain or tear up a piece of clothing.

**Comment by Lasiace** [comment]
To be fair, it does impact wilderness starts and/or playthroughs somewhat significantly, as heavy sticks have suddenly become rare and the only easy way to get a cutting tool is to make a stone knife, which requires having the heavy stick in the first place, making it a chicken-and-egg problem. Things like makeshift knives are out of the question in those cases unless you get lucky.

I mean, surely if you can smash a small tree into long sticks, you should be able to smash said sticks into shorter sticks as well, right?

Other than allowing disassembling long sticks into heavy sticks without a cutting tool, you could also just provide a random distribution of long and heavy sticks whenever you smash a tree, which should get around the problem as well.

**Comment by Amariithynar** [comment]
Oh, I'm not saying it shouldn't be done, just that I think that it's something very minor to deal with. If someone wants to take it upon themselves, though, all the power to them.
