### ISSUE TITLE
Some preserved food recipes do not indicate that in their names

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#24226]
Game version: O.C-28868

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
All recipes using containers for preservation indicate that in the recipe name for ease of searching for the particular recipe, to recognize at the glance the possibility and for the sake of consistency (as most canned/jarred/otherwise preserved items indicate that in their names).

### Actual behavior
Some don't. Seems like an easy fix. Recipes in question are jarred/canned soups (meat, fish, vegetable, mushroom, woods soups), soylent slice, regular and bone broths, V8, kompot.

**Comment by TechyBen** [comment]
As a player, I kept putting my woods soups in the jar version in error, as named, they were identical, and I forgot to check ingredients. Ended up using all my jars. :(

So as a QOL and GUI change, that would really help.

**Comment by Amariithynar** [comment]
Having 3 versions of each soup I have to check when I just want to make the stuff I can pour into a skin and take to drink on the go IS annoying. Seconding this. "canned <type> soup" and "jarred <type> soup" labels would be nice. Then once you open it, (say, by (a)ctivating it?) it reverts to being the soup in the container as per normal, with the usual decay timer, demonstrating that you've popped the seal.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
