### ISSUE TITLE
Some recipes require more than the maximum amount of charges from soldering iron

### ISSUE THREAD

**Issue by svick** [CleverRaven/Cataclysm-DDA#24230]
Game version: 0.C-28870-g2ccd3b8

Some recipes, like [charcoal kiln](http://cdda-trunk.chezzo.com/char_kiln/craft) or [electric forge](http://cdda-trunk.chezzo.com/forge/craft) require more than 200 charges if made by soldering iron. The issue is that soldering iron can only hold 200 charges. That can be changed by using e.g. extra battery mod, so it's not *impossible* to craft such recipes using soldering iron, just fairly hard. Is this intentional?

Especially consider that in the real world, it would be possible to put new set of batteries into a tool in the middle of crafting, so how many charges it can hold probably shouldn't make a big difference.

Maybe when crafting, tools should be able to use nearby charges after charges in the tool are exhausted?

**Comment by TechyBen** [comment]
Soldering iron can take power mods. Or be externally powered (as a vehicle installation as part of the welding rig). So it is working as intended. If it is intended for some recipes to go past the standard battery limit.

**Comment by Amariithynar** [comment]
Yeah I'm pretty sure Ben hit it on the head here. Same with the Makeshift Welder vs. a normal Welder.

**Comment by kevingranade** [comment]
The point about replacing the batteries is valid 5hough, at worst it should
just take longer, in practice it shouldn't matter at all.

**Comment by Amariithynar** [comment]
@kevingranade in that case, is there a way to check "X batteries + welder/soldering iron" or in fact, "x reloading materials + [tool]" in general?

**Comment by kevingranade** [comment]
Unfortunately there is not.   There is some special casing for ups charges,
but nothing for loose batteries.
