### ISSUE TITLE
Hide point counter for effects like rad-poisoning

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#24233]
During discussion at #24145 when idea of non-binary food poisoning was mentioned, I started to think about radioactivity. Given that we currently have in game devices to measure it, I think it's unnecessary and even suspicious to allow characters without any equipment to measure their radioactivity.

This ticket is a suggestion of hiding rad poisoning status the way it is with the telepad disease, possibly adding new text-window "immersion" indicators to alert the player (along the lines headaches, pains, weakness, hair falling out if one didn't shave it all off). People with minimal first aid skill (2 points?) should see generalized status ("rad-poisoning", "heavy rad-poisoning" etc) but should also require actual piece of equipment to determine how many points of radioactivity they actually have. 
It would, IMHO, make good basis for the food poisoning discussed as well, where one may see that they're badly or only slightly poisoned and guess some things on the basis of symptoms, but won't know they have, say, exactly 20 points of food poisoning.

**Comment by nexusmrsep** [comment]
Long time ago I participated in coding an rpg game of a fantasy genre that had a basic principle to convert all in game numerical values to descriptive text, so the player would almost never experience any numbers, yet was able to determine things at gradual level ("FOO is greater than BAR" or "FOO is lesser then BAR"). It worked very nicely. 

As for radiation (and few other effects), I think its a good idea, where discrete numbers could be converted to certain descriptive levels that would cover certain ranges of those values.

Measurement equipment, like geiger counter, should provide numerical info. Unless it's rudimentary equipment like radiation badge.

**Comment by Amariithynar** [comment]
This is basically exactly what I wanted regarding food poisoning (and tweaking rads), so how else can I respond but with an emphatic "yes please!"?
