### ISSUE TITLE
Integral gunmods can be detached by burning the parent gun

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#24242]
Game version: build 7459

Operating system: Windows 10

Tiles or curses: curses

Mods active: none

### Expected behavior
Integral gunmods cannot be detached under any circumstances and should suffer the fate of the parent weapon.

### Actual behavior
Integral gunmods can be detached by destroying the parent gun by burning, then attached to other weapons.

### Steps to reproduce the behavior
Spawn a Kel-Tec KSG and/or Lemat Revolver, drop it along with fuel (e.g. log), set it on fire. The KSG will burn almost instantly because it is made of plastic, but the KSG second magazine will not because it is made only of steel.

![image](https://user-images.githubusercontent.com/4408382/42438899-3cad3710-8316-11e8-86fb-fad0f4f4b335.png)

**Comment by ZhilkinSerg** [comment]
Lol, why would you burn your gun in the first place?

**Comment by ejseto** [comment]
It was the fungus, I tell ya. I have no idea where the gun came from, but the evidence, the detached second magazine, was unmistakable.

**Comment by 0be1isk** [comment]
@ZhilkinSerg to be fair, that's true bug testing at its best lmao
