### ISSUE TITLE
Unsalted and unbuttered popcorn is considered "unhealthy"

### ISSUE THREAD

**Issue by rtizzy** [CleverRaven/Cataclysm-DDA#24244]
Game version:
Latest experimental build

### Expected behavior
That regular popcorn with no butter and salt is not junkfood.

### Actual behavior
Regular popcorn with no butter and salt is junkfood.
### Steps to reproduce the behavior
Have junkfood intolerance. 

Attempt to eat popcorn.

**Comment by rtizzy** [comment]
Popcorn is actually pretty healthy from a nutritional point of view.

It is high in fiber, provides some protein, is high in antioxidants, and it is also low calorie. 

http://www.eatingwell.com/article/287900/is-popcorn-good-for-weight-loss/

Numerous other sources of this can be found. I will submit a pull request shortly.

**Comment by Amariithynar** [comment]
Agreed; popcorn certainly isn't high in vitamins and minerals, but it is still nutritious, being just dry corn kernels that have been fried in oil until they have popped.
