### ISSUE TITLE
Funnel doesn't fill containers that are not sealable

### ISSUE THREAD

**Issue by lucasmr** [CleverRaven/Cataclysm-DDA#24251]
### Expected behavior
After leaving an opened tin can, opened aluminum can or opened plastic cup in the rain with a funnel, there should be collected water after some time.

### Actual behavior
The game doesn't consider these watertight containers as eligible to collect water.

### Steps to reproduce the behavior
Place an opened plastic cup under a funnel in the rain.

**Comment by Amariithynar** [comment]
Additionally, open cups and vehicle-mounted tanks do not count as water storage containers when brewing clean water. Tried to make some clean water and feed it back into my Zombulance's clean water tank, and I couldn't even craft one.

**Comment by Rivet-the-Zombie** [comment]
>After leaving an opened tin can, opened aluminum can or opened plastic cup in the rain with a funnel, there should be collected water after some time.

If we want to get really picky about it, opened soup cans and buckets should slowly fill with rainwater even without a funnel.

**Comment by lucasmr** [comment]
Sure thing, but I'm willing to address this first because sometimes on early game you don't have a proper resealable bottle, only a funnel and open cans. Getting dehydrated while it rains is very sad.

**Comment by Amariithynar** [comment]
Thanks to your reminder, I remember a game where you could (o)pen your tile to open your mouth to the sky and drink your fill, haha. Related note, why is rainwater not considered potable when drank straight from a funneled tank?

**Comment by lucasmr** [comment]
Rainwater could be contaminated from air pollution, also funnel and bottle could be dirty. There's also acid rain in the game, so it's fine in my view.
