### ISSUE TITLE
Liquid/Brewing Funkery: some mixed drinks' proportions seem off by volume & other shenanigans

### ISSUE THREAD

**Issue by Amariithynar** [CleverRaven/Cataclysm-DDA#24265]
Exactly as it says on the tin. I'll outline each drink that I see a problem with individually. Saying this up front: All drinks that are steeped or solids/powders mixed into a liquid that use one liquid portion and only return one liquid portion are fine, as I can see. You don't turn a portion of water into two portions just by putting some tea leaves into it. Anyways, on with the show!

For Fancy Hobo, you use three servings, one of juice and one each of weak and strong alcohols, to make Fancy Hobo. Seems a bit of volume is being deleted, here? I mean, it's not like spirits are hard to come by, but it's surprisingly rare to find hops or the pre-Cataclysm brews. Considering you can drink the three separately for a much bigger boost, I'm wondering what's going on here? Typo in the recipe?

Similarly, Long Island Iced Tea. Dark Cola, Vodka, Gin, Rum, Tequila, Triple Sec go into it, 6 different liquids, two of which can't be crafted, and you get only 1 portion out of it. 
>Related note: Triple Sec is just a triple-distilled liqueur ('sec' comes through French from Latin "siccare", from which English gets "desiccate". The more you know!) made from dried orange peels; it's a variant of curacao. Basically, any citrus fruit should be able to be used to make "Citrus Liqueur" which can be used instead of Triple Sec; a recipe like "# lemons or irradiated lemons or grapefruits or irradiated grapefruits or oranges or irradiated oranges; # vodka; # undistilled citrus liqueur" which then needs to be crafted using a still to make citrus liqueur.

Screwdriver Cocktail and Wild Apple, mixing Vodka with Orange Juice and Apple Cider respectively, only return 1 portion.

Tainted Tornado uses 12 tainted chunks of meat and 1 alcohol, and produces 2 portions. Comparatively, mutagen uses 3 tainted meat and then uses bleach and ammonia to make hydrochloric acid and dissolve the flesh away. Either the volume on mutagen's meat requirement is too low (which I think it is, as it also takes 5 blob globs, and those are made 1:1 from tainted meat), Tainted Tornado uses a few too many pieces of tainted meat or, of couse, it just produces too few portions; that much meat would be a sizable volume.

Rum & Cola: two portions go in, one portion comes out.

Whiskey Sour: Lemonade + Whiskey suffer from the same issue as Rum & Cola: Two in, one out.

Methacola: 4 meth and 2 Dark Cola go in.... and 4 Methacola come out?! This one stands out because it's producing 4 portions of liquid from 2 liquid units, I assume so people don't feel put out by using 4 meth to make it; To that I would suggest adding another liquid, perhaps sweet water? Portions should be matched by liquid content primarily, solid content only in cases of large volume.

Bee's Knees: 1 gin, 1 honey, 1 lemonade, 1 portion. Especially egregious as it counts as a weak alcohol for Fancy Hobo.

Spiced Mead Must uses 1 hops, 1 yeast, and 10 honey/2 honey comb with 3 water; basic honey mead doesn't actually use hops (unless you're a modern microbrewery trying to 'spice' things up, haaaah), and "spiced mead" uses things like cinnamon, nutmeg, and cloves for its spices, added after the fact to the mead because *mead isn't sterile*; there IS a mead-like drink brewed in Ethiopia I know of called Tej, that is brewed with a buckthorn relative that contains a bittering agent like hops does, but that's not "spiced mead". I'd be all for its inclusion as a separate recipe/renaming, though!
>I think that there's a pretty simple solution here; honey and water need to be mixed together to make "Mead Base", which can then be fermented as is to make Honey Mead; have a recipe for Spiced Mead that uses Honey Mead and spices and a heat source to cook them together; a recipe for Unfermented Tej, that just adds hops to the Mead Base, and can then be fermented, and lastly the addition of any of the various fruit juices or fruit pulp to make Fruit Mead. Lastly, unless we're adding some alcohol to the mix, mead doesn't really reach the abv needed to be shelf-stable, lasting a couple years if sealed after decanting, but only a few months if not.

Kompot has no recipes that use it, even though it is effectively just a slightly-more-watery fruit juice, that can be used in all the same sorts of cocktails and mixed drinks that other fruit juices are. Using fruit pulp to make kompot feels a little cheaty, though; I'd rather see kompot use only fresh/dried fruit, and render fruit pulp as a byproduct as well. Traditionally the pulp left over would be used with a little bit of kompot to make kissel with some starch; basically a fruit soup! It'd be nice to see that reflected in-game.

Fruit juice isn't able to be made with dehydrated/rehydrated fruit. They don't lose any of their flavour by being dehydrated, so why can't that be extracted? Also, dehydrated fruit can be pulverized into fruit powder, which can easily be added to water to make fruit juice- and it'll be much more smooth than traditionally squeezed, pulp-in juice is, as it's more uniform pulp particle distribution. Of course you could boil and strain it to extract the pulp, if that's your preference, too.

Lastly, hot chocolate & mexican hot chocolate use 1 whole chocolate bar to one portion of milk. What? It should either use more milk and return more portions per batch, or you should be able to grind it down into chocolate powder (say, 10 portions?) and use that in some factor of portions (for 10, recommend 2) at a time. Considering one bar can fully coat 6 pretzels or 10 coffee beans, 2 seems relatively accurate to a mug of hot cocoa.

Unfermented vinegar uses fruit juice, apple cider, or fruit wine and produces just "vinegar"; however, vinegar is made from ANY alcohol, not just fruit-based alcohols, or fruit-based drinks (when using cider or fruit juices, you need to ferment them into wine first, before you can add yeast (manual addition is faster and more efficient than waiting for it to grow naturally) to ferment the citric acid into acetic acid). Store-bought white vinegar that we're all familiar with pales in comparison to freshly brewed vinegar, as well, which is diluted down to the vinegar we know of to make it food-grade; commercial-grade vinegar sits in the 20-30% acetic acid range. The end product should be "Concentrated Vinegar", not just "Vinegar", and either diluted to "vinegar" which we can use for eating/drinking/pickling (the 2% difference between table vinegar and pickling vinegar is too minute to really make a difference), or concentrated still further by reduction into concentrated acid.

Both forms of Shake (Protein & Soylent) are actually smoothies; they use fruit or vegetables, pureed into a liquid base, and exclude milk. To be a shake, milk products must be used. Furthermore, neither can actually use vegetables.

So, there's my big list of weirdness that I noticed going over the liquids list, as a cook. I didn't touch the recipes for the alcohols themselves (going through the must/wort to the wash to being distilled), because I simply don't know enough about those to comment on any volume issues and they're simple enough that I don't see a problem with the recipes in general, so if someone else finds there's something wonky up with those values, or feels that I missed something, please note them.

**Comment by Zireael07** [comment]
Tainted tornado is meant to be wasteful compared to mutagen (much much more diluted and the effects are weaker)

**Comment by Amariithynar** [comment]
@Zireael07 I can understand it being less efficient/more dilute, but you don't use more of something than you do to distill the concentrate, to make a more dilute, weaker concentration in similar batch size. In other words, if 3 tainted meats contain enough blob essence to act as a mutagen, then pureeing 3 tainted meats into a smoothie and downing it would still contain the same overall amount of mutagenic material. Just like how a pound of protein is a pound of protein, regardless of it it's been refined down to powder or is still just the haunch of an animal.

**Comment by sfsworms** [comment]
Aren't the unit size for hard spirit and for most other drinks different? You can't just add them as if they were the same size.

**Comment by Amariithynar** [comment]
>Aren't the unit size for hard spirit and for most other drinks different? You can't just add them as if they were the same size.

A portion is a portion. You aren't dropping a tall glass of Gin every time you take a swig, obviously, so why would you do that with a Long Island Iced Tea? Furthermore, any alcoholic drink I haven't mentioned here, like boozeberry, already does properly add the total amount of portions together.
