### ISSUE TITLE
Liquid Lye recipe uses too much wood ash/not enough wood ash is produced from burning wood

### ISSUE THREAD

**Issue by Amariithynar** [CleverRaven/Cataclysm-DDA#24267]
As per https://github.com/CleverRaven/Cataclysm-DDA/pull/22427 which references #22406 making liquid Lye either uses WAY too much wood ash per volume, and/or not enough ash is produced by wood being burnt. According to @Atealein (sourced in commit from https://farmingmybackyard.com/homemade-soap-from-ashes/) "It takes 10 cups of ashes and about 2 gallons of water to make a gallon of lye water"; that means 30 units of water (two 1 gallon jugs) and 3.4 kilograms of ash should make 15 units of lye (1 gallon jug). At 50 wood ash, that's 0.05 vol and 0.05 kg, which means 3400 wood ash should be equal to 3.4 kilograms, or 15 units of lye. Instead, it comes out to being not even half, only 40%, at 6 lye (though 100 more ash would bring it up to 7, or 47%). One log burned in a fire produces 163 wood ash. Comparatively, there's a recipe for wood ash where you get 100 ash for every two by four; one log also burns to 80 charcoal in a charcoal kiln, which can convert to lye powder at 50 charcoal to 200 powder, the same amount produced by reducing 6 liquid lye.

**Comment by Rivet-the-Zombie** [comment]
>not enough ash is produced by wood being burnt

This right here. Burning a single log should produce an abundance of wood ash.

**Comment by Amariithynar** [comment]
@Rivet-the-Zombie Not just that, but the recipe is a bit funky on how much lye it produces, too. The proportion of wood ash should be 3.4 kg to 30 units of water to produce 15 units of lye, when in fact you use 1 water and 0.5 kg to make 1 lye.

**Comment by Duhuh123** [comment]
Hi. I have just started playing this a week ago. 

The game allows making weak acid from salt water with just fire.
I don't quite see how that can be done in real life:
https://chemistry.stackexchange.com/questions/8948/how-to-separate-hcl-and-naoh-from-salt-and-water-solution
The chemistry isn't that realistic.

By the way, why do you need so much lye?
I am making lye with wood ash from burning down house.
I use a shovel to clear the debris and get the wood ash.
That is a lot of ash. And now I need tons of water to make all of the ash to lye.

After that, I make sugar with plants from farming and lye powder.
Or just salt from lye.

**Comment by Rivet-the-Zombie** [comment]
>For example, the game allows making weak acid from salt water without electrolysis.

It used to require it. Must've been changed at some point during the requirements overhauls.
