### ISSUE TITLE
A Charcoal Smoker doesn't need to be watched to smoke what is put into it. Lets fix that.

### ISSUE THREAD

**Issue by Amariithynar** [CleverRaven/Cataclysm-DDA#24270]
As per request of @nexusmrsep, opening a new issue for batch charcoal smoking, brought up originally by @GroeneAppel at #24255.

Currently, smoking meat requires the Survivor to sit and watch the meat on a charcoal smoker from start to finish. In reality, smoking meats is a long, time-consuming process that requires little actual personal attention.  As such this issue is being opened to discuss rectifying that problem by making the smoker a standalone unit that you load with meat and ignite the charcoal and leave until it's done, like the charcoal kiln or a fermenting vat.

Sources for times were given by @GroeneAppel as https://www.smoking-meat.com/smoking-times-and-temperatures-chart and http://www.smokymtbarbecue.com/bbq-tools/bbq-smoking-times-temperatures-chart.php; As we don't actually field dress corpses into their carcasses, or cut them down into primals and subprimals, but instead into miscellaneous chunks of meat, we're not going to be looking at the long periods of time like for smoking beef briskets, but rather more for smoking individual steaks or loin cuts. Note as well that while these are individual timers, entire batches cook at the same time without any extra time added, because extra time is dependant on thickness of the cut.

As such, my opening suggestion would be a solid 6 hour smoking period.

I'd also like to ask opinions on introducing wet-curing or dry-curing, with wet-curing being for long-term storage (basically brine-pickling the meat, then salt-packing it after smoking) and dry-curing being relatively shelf-stable, but will rot if left open to the air instead of sealed in a package. Sausages would also be prepared this way, as large links of sausages are hung in smoking racks to prepare them, with an additional drying step if they're going to be preserved for long-term food storage.

**Comment by acidia** [comment]
I think just about everyone agrees with you in principle but its a matter of actually going through and implementing it.  Are you looking for someone to do the coding or are you asking if you made the changes they would get merged?

**Comment by Amariithynar** [comment]
@acidia I was asked to open the issue by @nexusmrsep; I believe that he is planning on working on it.

**Comment by nexusmrsep** [comment]
Yes I'm planning to implement this particular one and asked for opening an issue for the initial discussion.

**Comment by acidia** [comment]
It's cool either way, wasn't trying to judge you if that's the way it seemed.  I know this has been a recurring topic of discussion so you may be able to find some older idea posts.

How general do you think the implementation might be?  I'm looking at smelting for the blacksmith shop but I know people would like other cooking recipes, stills, and more advanced tools to do the same.

**Comment by nexusmrsep** [comment]
> How general do you think the implementation might be?

If I'd had better skills I'd make something along `transform` `iuse_actor` that would use json-ized "recipes" for converting multiple different things into other things, but much of that code is still beyond me. It would be generalized in a sense that it could be used from terrain/furnitures `use_action` and would be independent of it's purpose (blacksmithing/cooking/etc.).

But for now I plan to use something along the lines of a fermenting vat with different conditions on input/output. This approach is not generalized as every items has its similar, but own code. It has advantages, as perhaps not everything can be generalized, but `transform` works fine so perhaps it would too.

**Comment by Amariithynar** [comment]
Same with boiling water to make clean water, really. Fill a container with water, get it stuck in a fire, and it'll boil itself clean easily enough.
