### ISSUE TITLE
Hitting "reload" hotkey is effectively disabled for all tools/other weapons with ammo with a bow out.

### ISSUE THREAD

**Issue by Amariithynar** [CleverRaven/Cataclysm-DDA#24272]
Really tired of trying to reload other weapons/items (including my gas mask!) and getting a, "The [bow type] does not need to be reloaded, it reloads and fires in a single motion." message every time. Just let me have my reload prompt when I hit reload if I can't reload the bow, just like with every other wielded weapon that has been reloaded!

**Comment by lucasmr** [comment]
I'll make a PR shortly.

**Comment by Amariithynar** [comment]
Thank you, @lucasmr!
