### ISSUE TITLE
Implement more diary entries, graffiti and notes for improved lore. 

### ISSUE THREAD

**Issue by rtizzy** [CleverRaven/Cataclysm-DDA#24278]
See:

https://docs.google.com/document/d/1QfmR5Ex6ivgb67u6xealmEUWDABvW8YbWTSsI1D-wQ8/edit#heading=h.wpf2c280jjp3

This was written but never implemented as far as I know. Thanks go to many contributors to helped with that. 

Please assign this issue to me @kevingranade

**Comment by Night-Pryanik** [comment]
@rtizzy any luck on that?

**Comment by rtizzy** [comment]
@Night-Pryanik I haven't made these changes but I am looking for additional help with getting it done. 

Both making the PRs as well as more creative content. Some of it will likely need to be updated due to the retcons.

**Comment by rtizzy** [comment]
The following thread has even more links to everything 

https://discourse.cataclysmdda.org/t/expanding-lore-and-detail-update-8-4-13/334/77

**Comment by Leland** [comment]
Looks like this has been stalled for a while! Closing for now, if anyone is interested in making a PR for this, ping me and I'll reopen.
