### ISSUE TITLE
0.C-29028 - Intact large tent repacks into damaged large tent

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#24289]
Game version: 0.C-29028

Operating system: Windows 10

Tiles or curses:Tiles

Mods active: Medieval content, blazemod.

### Expected behavior
Large Tent item unpacks into a tent. Repacking the item gives you the Large Tent item again.

### Actual behavior
When repacked, Damaged Large Tent item is received.

Note that this was a tent that I received in item form, found in an evac center basement. It wasn't one of the damaged tents from a campsite. I know those are supposed to be damaged. There was no damage to the tent structure, though the door was open when I repacked it. Around 3-4 days of gametime had elapsed between me deploying and repacking the tent, and it had left the reality bubble a few times.

**Comment by Night-Pryanik** [comment]
Ouch, that's a really old version you're using. Have you tried the latest experimentals, something like 0.C-75xx?

**Comment by Solusphere** [comment]
Apologies, I was going off my CDDA directory listing, under the half-baked assumption than the launcher I used was updating it. The actual version I'm using is 0.C-29028, and I've updated the post accordingly.

**Comment by Solusphere** [comment]
I should note that I've done some testing of this, and while I've managed to get it to happen twice now, I can't identify what I'm doing differently in the cases where I've gotten a damaged item from an intact tent.

**Comment by sfsworms** [comment]
Does the door opening or closing change something? Is it consistant?

**Comment by BrettDong** [comment]
How to reproduce this?

**Comment by Solusphere** [comment]
Opening/closing the door doesn't change anything, as far as I can tell. As I've said, I've managed to reproduce it twice, but it seems random as far as I can tell. Should I have held off on reporting it until a reliable way to reproduce it was found?

I will say that in both times that I reproduced the issue, I had left the area the tent was in and returned later, but that alone doesn't reliably cause it to happen.

**Comment by TechyBen** [comment]
Carrion pests spawning nearby?

**Comment by zizdarren** [comment]
Here is another example of mine:

version: 0.C-31661-gc1b3903,       build 0.C-7868   (date: 09/08/2018)

Find a large tent from a corpse item (from map generate event: 7 corpse was generate from map, with 1 amoebi mold, and 1 gacke near by), I deploy the large tent, and then take down the tent, and the item become damage large tent.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.C-8110.

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed.
