### ISSUE TITLE
Player should be able to attack friendly monsters

### ISSUE THREAD

**Issue by Amariithynar** [CleverRaven/Cataclysm-DDA#24297]
You should be able to attack them regardless, regardless of friendly/hostile status. Currently, you cannot, no matter how well you aim, until the effect completely wears off.

**Comment by acidia** [comment]
Poor Aavak :'(
Him and Rycon account for a lot of new traffic...

**Comment by Amariithynar** [comment]
It's not a case of wanting them suggested as targets, but about when you DO target them specifically and deliberately attack them (NPCs too!), it should actually attempt an attack against them instead of whistling right by.

And yes, Aavak is who had this happen that I saw, but that death was entirely his own fault for not running away from the zombie grenadier afterwards :P His interactions just made me note this issue, is all.

**Comment by Lorith** [comment]
This is also an issue for mycus characters, it is quite possible to end up with multiple fungaloids and/or spores inside your base/vehicle with no way to remove them except fire, explosives, or unaimed firing at the square.

**Comment by Night-Pryanik** [comment]
We just need an ability to aim wherever we want, no matter which objects/creatures/what else is located there.
Somewhat related: #21967.

**Comment by baraba3** [comment]
maybe my memery serves me wrong but there at least was similiar issue with infr red googles allowing you to see enemies in night but not shoot on them.dont know if it is still problem.

**Comment by Night-Pryanik** [comment]
Renamed title to more generic issue.
