### ISSUE TITLE
cursesport nc_color is not unique

### ISSUE THREAD

**Issue by svick** [CleverRaven/Cataclysm-DDA#24299]
Game version: 0.C-29034-gf05215284e

Operating system: Windows

Tiles or curses: tiles

### Expected behavior

The function `nc_color::from_color_pair_index` returns a unique result for each used `index`.

### Actual behavior

In https://github.com/CleverRaven/Cataclysm-DDA/pull/23419/commits/7e21da61992641fc7e16822fa12b1169c0c52c11, `A_COLOR` was changed in a way that means that one bit of the index is thrown away for values of 64 and above (values up to 71 are used). Some consequences of this are:

* `color_to_id` does not return the right color. E.g. `id_to_name(color_to_id(c_light_red))` returns `"c_light_red_cyan"`.
* `hilite` doesn't work. E.g. `get_name(hilite(c_light_red))` returns `"h_white"`, instead of `"h_light_red"`

I don't quite understand why the code looks the way it does, so I don't know what would be the right way to fix it.

**Comment by AMurkin** [comment]
Mentioned commit - from the #23419 PR. Just for the record.
