### ISSUE TITLE
Can't unprepare/unactivate a gas mask.

### ISSUE THREAD

**Issue by Shodan14** [CleverRaven/Cataclysm-DDA#24313]
Game version: 0.C-29055-ge1e5d81

Operating system: Win 8.1

Tiles or curses: Tiles

### Expected behavior
You can "unprepare" a gas mask by activating it while it is active.

### Actual behavior
Activating an already active gas mask does nothing. You need to unload it to "unprepare" it.

### Steps to reproduce the behavior
Wish for a gas mask, wear it, activate it, activate it again.

**Comment by Vasyan2006** [comment]
Why would you like to deactivate our gas masks unless you are a fungaloid infiltrator?

**Comment by Shodan14** [comment]
Because alas I don't have infinite gas mask cartridges.

**Comment by Break-Off** [comment]
As far as I know, cartridges are either spent while wearing the mask and/or (not sure) inhaling smoke or other substances that require filtering. So even if it shows in your inventory as (active), it's not depleting its charges.

**Comment by Break-Off** [comment]
I'm not sure, but I think that the change from batteries to cartridges was made to bring the gas mask system a level closer to reality, being one of the goals before using a mask "preparing" it for use. Thus, a survivor with a non-active mask would be an unprepared survivor.

**Comment by Shodan14** [comment]
> I suspect that it's not really simulating a "non-active vs active" state like in electronics, but rather either you have a filter in or don't. Once you have a filter in, its always gonna be active (makes sense). Unloading it is going to make it "Inactive" since you don't have a filter in (also makes sense). The implementer seemed to have the right idea, but the way it's presented to the player is rather confusing. I say it's actually displaying everything correctly.

So as I understand it, it's a quirk of the engine that they need to be "activated" to be used with the cartridges?

The game has just trained me to not have anything active when I'm not actually using it. Will take a bit to readjust.

**Comment by Vasyan2006** [comment]
Gas mask cartridges are absorbed only if PC or NPC wear this gas mask and stay in toxic clouds. So one cartridge will be enought for very long time.

**Comment by nexusmrsep** [comment]
Perhaps an easy solution is to use a word other then (active) perhaps (ready) or (prepared)?

**Comment by Shodan14** [comment]
> Perhaps an easy solution is to use a word other then (active) perhaps (ready) or (prepared)?
Yeah, that would work. I can also see (loaded) as an option.

**Comment by Sintua** [comment]
Honestly, it should probably not need to be activated at all, just loaded or unloaded. If a filter is loaded, it will filter automatically, no activation needed. Removes the confusion of the activation entirely.
