### ISSUE TITLE
Wielding popup has no error message

### ISSUE THREAD

**Issue by lucasmr** [CleverRaven/Cataclysm-DDA#24317]
### Actual behavior
When having a bindle equipped and no other container, try to pick up a log. It will be offered to wield the item instead because there is no space available on the inventory. You will fail because your hands are restricted, but no error message will be given.

### Steps to reproduce the behavior
Wear a bindle, pick a log and accept it to be wielded instead.

**Comment by Break-Off** [comment]
I have also seen this with broken arms or swag bags. The game won't explicitly tell the player unless the player explicitly requests the game to wield the item with 'w'.
