### ISSUE TITLE
Starrting faction base requires two companions

### ISSUE THREAD

**Issue by svick** [CleverRaven/Cataclysm-DDA#24336]
Game version: 0.C-29152-geb24087

### Expected behavior

I can start a faction base just with the starting companion.

### Actual behavior

Starting a faction base requires one companion as the camp manager and another to actually do the work of setting up the camp.

I was not warned about this before setting up the camp and now my one companion is permanently the camp manager, which means they just stand in the middle of a field.

Some ways this could be mitigated:

1. Allow the camp manager to do some work.
2. Allow unassigning the camp manger.
3. Increase the default NPC spawn rate. At the default rate, NPCs are really rare, even getting a second one could be an issue.

**Comment by ZhilkinSerg** [comment]
4. Add some quest to Camp Manager with NPC as a reward.

**Comment by sfsworms** [comment]
Should  you really be able to start a faction with only the starting companion? Two dudes doesn't sound a lot like faction, and making it require 2+ NPC would make a faction something you have to work for a bit, not just something you can do from the starting shelter. 

So maybe prevent you from starting a faction with only one dude, if there is an easy way to do so?

**Comment by acidia** [comment]
Ah, that was more explicit in an older version of the tutorial.  Its super easy to add a talk option to revert the camp manager back to a normal companion.  The problem is the cascade of additional issues that generates.  All companions away on mission will not be returned, there isn't a clear way to re-designate a camp manager in the same camp, and would that mean you should be able to build another camp right next to the existing one?

I'll add it as an option but stick a bunch of warnings to try and convince people its a bad idea...

**Comment by Amariithynar** [comment]
@acidia what about only having the talk option to revert them available if there aren't any NPCs away on missions currently, which covers the edge case of setting up your own base with only one NPC follower (as above) and also prevents losing NPCs that are away on missions?

**Comment by acidia** [comment]
Hmmm... we could but what if a giant swarm of end game monsters or a massive fire engulfed the base?  You'd want to save the manager and cut your losses but you'd still have people in the field.  For now I think it is just easier to let the player abandon a camp when they want, warn them they won't be able to reclaim, and let them deal with accepting that.  No one is opposed to reclaiming it just isn't worth all the work yet.

**Comment by Amariithynar** [comment]
If that's really a concern- why not have pulling the manager off duty also cancel the other follower's work, as well? Don't teleport them to you, but you can still go running and get them and tell them to follow you. Is that doable?

**Comment by acidia** [comment]
Not particularly, that mean coding in an abort mission condition for all of the missions.  A person gathering firewood needs to be dropped in a random woods, a cook needs to be dropped in the kitchen, a scout needs to be dropped somewhere along their movement path.  Where would crafting or construction components be?  Is all progress lost?  Best just not open that can of worms.

**Comment by Amariithynar** [comment]
I'd rather lose all progress and all components used than lose all NPCs without a chance of recovering them. By removing the manager anyways, you're losing all components and completion of those missions those NPCs are on already anyways.

**Comment by kevingranade** [comment]
I'd prefer to not give the option to unassign the camp manager if any NPCs
are out.  It's not reasonable to give the player the option to break game
state.

If we can add in the code to handle placing orphaned npcs later, we can
provide more options.

**Comment by Nymall** [comment]
Could this be a possible use for walkie-talkies? Allow the reclaim options through using the walkie talkie or give a limited "return only" option that pulls back the NPC but does not complete the task?

**Comment by FulcrumA** [comment]
I like the idea of being able to use various radio equipment to directly contact sent-out NPCs - either requiring player to equip NPC with some device like that on their own or making NPCs borrow a radio when being sent on a mission from a designated tool storage.
