### ISSUE TITLE
Folding a Vehicle with solar panel and battery Bugs Electricity (Edit: Or Folding a Vehicle with Funnel and Tank At Rain)

### ISSUE THREAD

**Issue by adamdeno** [CleverRaven/Cataclysm-DDA#24330]
Game version:0.C-29073-g4e3224c (tiles) (Build 7573)

Operating system: windows 10

Tiles or curses: tiles

### Expected behavior
When Folding a Vehicle With solar panel and any battery It should Keep the current electricity value of each battery Edit: Or Funnel And Tank installed Should maintain Tank Value
### Actual behavior
Instead when Folding a vehicle with solar panel and any battery it Bugs it when unpacking gets all battery to 100% electricity Edit: Same
### Steps to reproduce the behavior
Build a vehicle Like This (Look at Time And message Bar)

![pic1](https://user-images.githubusercontent.com/41305926/42779273-2f49da6c-8940-11e8-8eee-29d589bf4154.PNG)

Vehicle Condition (Battery Electricity) Before

![pic2](https://user-images.githubusercontent.com/41305926/42779380-89332182-8940-11e8-9a2f-5eef87ec7cb9.PNG)

Folding Vehicle

![pic3](https://user-images.githubusercontent.com/41305926/42779413-aba84238-8940-11e8-8761-e3268643db90.PNG)

UnPacking

![pic4](https://user-images.githubusercontent.com/41305926/42779452-c3af6bf4-8940-11e8-8eeb-9025e1478cc5.PNG)

Vehicle Condition (Buged Electricity)

![pic5](https://user-images.githubusercontent.com/41305926/42779487-e5f736ce-8940-11e8-9fbe-f4fcad9f0e03.PNG)

**Comment by adamdeno** [comment]
Gonna see if same thing happens when there is a vehicle with Funnel + Metal Tank installed while raining

**Comment by adamdeno** [comment]
Yup It does To A vehicle with Funnel and Tank + Raining

**Comment by adamdeno** [comment]
@Night-Pryanik  The Same Bug to Same Vehicle With Funnel and Tank Folded in rain gives 100%

**Comment by ZhilkinSerg** [comment]
I would say vehicles with tanks and batteries should not be foldable at all.

**Comment by adamdeno** [comment]
If there is a Vehicle with no Tank then What would happen to cars BUT agree On Foldable Vehicles shouldnt have one tho

**Comment by adamdeno** [comment]
Also @ZhilkinSerg It didnt allow me to Fold Same Vehicle with 60L Tank applied Had to lower to 2L Tank

**Comment by Amariithynar** [comment]
Only small tanks (up to plastic jerrycan) are foldable, and small batteries aren't hard to have welded in or even just socketed in, where it remains when it folds up. There's simply no logic in "batteries/tanks shouldn't be foldable" when large tanks/batteries that really can't be, already aren't, and smaller ones that are lashed or welded to the frame can be easily placed to allow such.

**Comment by TechyBen** [comment]
Folding electric/petrol bikes exist... and are also possible/viable in game. Though how this can be tracked in code is obviously going to be difficult?

Could a quick swap battery slot and a quick swap fuel can slot be an option that requires less coding (use existing storage battery code?)?

Then a bike/generator when folded would drop the can/battery (this needs coding), but could be put back in quickly when unfolding.

Other option is the code it so charges are saved somewhere ready for when unfolded again.

**Comment by Amariithynar** [comment]
I like that. If it's really quick and easy to drop in the battery or slot in the tanks into their holders like with the Swappable Storage Battery Case, but the batteries and tanks don't actually fold up with the foldable vehicle, I'm perfectly fine with that.

**Comment by CoroNaut** [comment]
Let's not get off track, this issue is specifically for the bug that doesn't remember how many charges the vehicle battery has. It can be made into another issue if you want to change batteries and small tanks so they drop when the vehicle is folded.

**Comment by TechyBen** [comment]
>Let's not get off track
Yeah, it was just an option of implementation. If they can keep their volume + charges when folded, and this is not a difficulty to program, there is no problem.
