### ISSUE TITLE
"Hide Bag" item no longer wearable, has no volume, and is effectively just food

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#24331]
Game version: 
7570

Operating system: 
Windows 10 LTSB

Tiles or curses: 
Tiles

Mods active:
[
  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "makeshift",
  "More_Survival_Tools",
  "Mining_Mod",
  "more_buildings",
  "more_locations",
  "Experimental-Z-Level",
  "boats",
  "deoxymod",
  "no_scifi",
  "no_reviving_zombies"
]

### Expected behavior
That it should be possible to wear the Hide Bag

### Actual behavior
The Hide bag is not wearable. It's just a food. Has no volume.

### Steps to reproduce the behavior
Create a hide bag, spawn a hide bag, look at a hide bag description in crafting menu

**Comment by mlangsdorf** [comment]
Yeah, I noticed this happened while playing this weekend. Can't see why it's not working but I'll try to fix it this week.

**Comment by mlangsdorf** [comment]
Apparently comestibles do not have storage but can rot, armor has storage and does not rot.
The spoiling code is isolated enough that I can probably add spoiling for non-food items, but it's still going to be a big invasive patch.
I think the best way is going to be add a spoils_in quality, because qualities are optional.

**Comment by mlangsdorf** [comment]
I have something working I think. I'm going to sleep on it and refactor it tomorrow.

**Comment by RadHazard** [comment]
Has there been any discussion about a larger refactor to the item class?  It really bugs me that we've got a six-thousand line class that knows how to do everything from tracking rot to handling inventory volume to reloading guns.

It seems like it would be easier to support unconventional behavior combinarions like this if "container", "food", "rots" and other behaviors were split out into separate behavior classes that items could opt into independently of one another.

**Comment by mlangsdorf** [comment]
I don't feel competent enough in modern C++ idiom to undertake that refactoring at this time.

**Comment by RadHazard** [comment]
Oh, I wasn't suggesting you had to do it as part of this PR.  I was just wondering if this kind of thing had been discussed anywhere yet, since it seems to me like it's pretty badly needed.  I might actually take a crack at it at some point if I ever get in the mood.

**Comment by kevingranade** [comment]
Theres general agreement that it would be a good idea, but no detailed discussion about what path to take for item.

Main offenders:
* game
Simply a large amount of unrelated code jammed into one class.  Largest splits are initialization, game loop, global state accesses, and command handling.
* map
Used for map generation, rendering, state updates. Some previous discussion about splitting it [here](https://github.com/CleverRaven/Cataclysm-DDA/issues/22300) and [here](https://github.com/CleverRaven/Cataclysm-DDA/issues/8683)
* item
Wrapper around the in-game item entity.
Already split into immutable data (itype), data loading (item_factory), and mutable data/instances (item).
* creature/monster/character/npc/player
Already split, but not all data and methods have been moved to the correct level, and more splitting may be called for.
