### ISSUE TITLE
Crafting ammo belt linkages?

### ISSUE THREAD

**Issue by Shodan14** [CleverRaven/Cataclysm-DDA#24338]
Considering all the things you can craft with smelting, welding and smithing, why can't you make your own ammo belt linkages to make ammo belts?

**Comment by sfsworms** [comment]
Well, generally speaking, the player isn't allowed to make gun parts or gun by crafting. For ammo belt linkage, while the piece seems easy enough to manufacture, it's worth keeping in mind that you have to keep your tolerance really tight if you don't want your links to jam your gun. You don't really care if that sword you made is 1 mm wider that what you wanted, but for ammo link, it would be a huge issues (same for gun magazines, another mechanically easy part which is hard to manufacture for a player).

**Comment by Amariithynar** [comment]
Cloth ammo belts exist IRL (http://www.e-sarcoinc.com/images/products/detail/1919A4and1917BrowningClothAmmoBeltA4276.JPG), so why not have those be craftable instead of using metal ammo linkages? Even then, disintegrating ammo belt linkages are basically just rings of metal that have been made to the same size as the bullet casing, with simple curls of metal lining them together; https://www.edwardarms.com/wp-content/uploads/2016/06/IMG_4315.jpg for example. Non-disintegrating metal ammo belt linkages also exist, and they're just connected by little circles of wire (and we can already make steel chain and chainlink fence, and it's really not hard to do; take a rod or pipe of the desired diameter and tightly wrap a wire around it, then snip along one side) like https://upload.wikimedia.org/wikipedia/commons/8/80/PK_machine_gun_non-disintegrating_metal_belt_1.pdf. If we can forge, shape, and sharpen combat knives to military spec (so long as we have the skill and required tools), we can definitely forge ammo belt linkages.

**Comment by Mecares** [comment]
I do not think they would get merged into mainline, but you could make a pull request to add them to the More Craftable Guns Mod.

**Comment by sfsworms** [comment]
Cloth ammot belt would be a thing, but not all machine gun can use them AFAIK. They would make sense as craftable material though.

And I strongly disagree. A combat knife is still good if it's not perfectly up to spec to the millimeter. No one care if your chain or chainlink fence is not 100% standardized. But if your ammo links aren't, you're in for a jammed gun. I could see some "makeshift ammo belt", that have a relatively high chance to jam the gun and needs it to be cleared, but at that point I don't think anyone would bother using them.

**Comment by Lorith** [comment]
There is actually a mod that does this, it just isn't packaged with the game. [Craftable Magazines](https://discourse.cataclysmdda.org/t/craftable-ammunition-magazines/14607)

**Comment by Amariithynar** [comment]
>And I strongly disagree. A combat knife is still good if it's not perfectly up to spec to the millimeter.

Then you don't know knives that well. As a cook, a millimeter difference in a knife blade is going to cause a pretty big difference in how I handle it. Same with the bevel, how bowed the belly of the blade is, if the heel of the knife has a bolster or not, and so on.

Frankly, it's not THAT difficult to make a good knife with hand tools. Nor is it that difficult to make metal loops that have curled folds to connect to each other. Hell, we have craftable firearm repair kits. http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Firearm_repair_kit If we can perform structural maintenance on firearms to render them as good as new (or better!) as well as have the capability to forge our own materials, there's no reason we can't make it to within tolerances. I mean, flatten out some bar stock and then curl it around a rod of the appropriate diameter, making sure the width is within tolerances, and you've already done most of the work. It definitely shouldn't be something you can do off the top of your head, though. Should either require an ammo belt linkage (as a tool, not consumed) as a reference material, or a recipe book to teach it, no learning it off skill alone. I mean, we can already learn how to craft a belt feed adapter http://cdda-trunk.chezzo.com/beltfeed/craft which shows that at a certain point (fab 5 rifles 2, if I'm reading the skill requirements right) we have the capability to craft the framework required to accept ammo belts into the gun and properly eject them as well. If we can craft THAT, we can craft the ammo belt linkages.

**Comment by Shodan14** [comment]
> I mean, we can already learn how to craft a belt feed adapter http://cdda-trunk.chezzo.com/beltfeed/craft which shows that at a certain point (fab 5 rifles 2, if I'm reading the skill requirements right) we have the capability to craft the framework required to accept ammo belts into the gun and properly eject them as well. If we can craft THAT, we can craft the ammo belt linkages.

That was a big reason I asked in the first place. The belt feed adapter is not super useful unless you can make belts.

**Comment by kevingranade** [comment]
Magazine and belt linkage tolerances are too tight as mentioned.

> I mean, we can already learn how to craft a belt feed adapter

That's a mistake that needs fixing.  Both that it's craftable and that it exists at all.

**Comment by Amariithynar** [comment]
No, they really aren't. But you keep on being you and not actually adhering to realism all you want, when it's something that isn't a detriment to the player.
