### ISSUE TITLE
"You don't have any companions ready to return" when NPC base manager claims they are done

### ISSUE THREAD

**Issue by 0be1isk** [CleverRaven/Cataclysm-DDA#24343]
Game version: latest

Operating system:  windows

Tiles or curses: tiles

Mods active:  Filthy clothing, Simplified Nutrition, StatsThroughSkills, More buildings, NPC traits

### Expected behavior
NPC should come back after selecting recover option
### Actual behavior
Base Manager says none are ready to return

### Steps to reproduce the behavior
upgrade base for the second time. When the [done] icon appears on recover ally from upgrading option, select recover ally from base upgrading.

![screenshot 16](https://user-images.githubusercontent.com/40281029/42840503-1319a166-89d5-11e8-8269-90be25be31bb.png)
![screenshot 17](https://user-images.githubusercontent.com/40281029/42840505-171bf5a2-89d5-11e8-8b91-af9d6d48ef25.png)

**Comment by acidia** [comment]
Interesting, could you try again in like 5 in game min?  One of the issues was that the time system was handling time comparisons strangely.  So you may have 0 hrs left and 0 min left but still have 59 seconds left.  If it checks the first two it doesn't notice the last one.  This is most prominent when crafting really quick things like one pointy stick.  Since it takes less than a min.

**Comment by 0be1isk** [comment]
I weighted for some hours to give it the benefit of the doubt, 
still the same result
![screenshot 18](https://user-images.githubusercontent.com/40281029/42841306-9d331772-89d7-11e8-8d72-15a1d1d8c206.png)
![screenshot 19](https://user-images.githubusercontent.com/40281029/42841313-9f5c8ff6-89d7-11e8-8db0-93a3854a5ec9.png)

**Comment by acidia** [comment]
I can't replicate it... did your companion have an infected bite that would have killed them before they returned?

**Comment by 0be1isk** [comment]
No, they were as healthy as could be. on my OM it says she is there, but the manager and the one at my PC base are the only ones actually there
![screenshot 24](https://user-images.githubusercontent.com/40281029/42842058-150e9f6c-89da-11e8-9efb-30ae17f6b595.png)
![screenshot 25](https://user-images.githubusercontent.com/40281029/42842059-1523b492-89da-11e8-9af9-88dc1e4972e7.png)

**Comment by acidia** [comment]
Uhhh, is your recipe deck screwed or are you smashing the furniture to build new stuff?  It doesn't really matter but if you recipes are screwed then the issue lies somewhere else completely.  You have only done two upgrades???

**Comment by 0be1isk** [comment]
I have done only 2 upgrades. It's odd that they require materials for recipes but they don't use the shelter kit that was required, nor the 8 logs and however many straw was needed. That's still in my inventory. The only other thing I can think of that I did was I had a cart in front of the tent. Before upgrading it to the second level, it said that the engine doesn't support building over vehicles. I thought it meant my vehicles a OM tile away. So I moved them further away, and it still gave me an error. I realized it was talking about my cart that was in front of the managers tent. I tried one more time before going o move my cart, but my cart disappeared, the 2nd tent appeared, then my cart reappeared in front of the managers tent. And that's when I couldn't recover my NPC.

**Comment by acidia** [comment]
Ya, that's really important to mention.  So when the mapgen update attempted to update the map it couldn't so it aborted but didn't do so cleanly.

**Comment by 0be1isk** [comment]
I see, I didn't save at all before starting my base, so I can at least revert. I'm assuming because it's a game engine thing, there isn't much of a fix for it?

**Comment by mlangsdorf** [comment]
I probably had a cart, a bicycle, and my van nearby at various points. If that's what's causing the problem, I'll remember that and work around it, but it would also be helpful if the missions could detect the presence of a vehicle nearby and tell you to move them off.

I mean, I pulled the van back, but I don't even think of a cart as a vehicle anymore.

**Comment by 0be1isk** [comment]
I don't think of a cart as a vehicle either, but as far as the game sees it, it's a vehicle

**Comment by acidia** [comment]
#24348 Should fix the source of your problems.  
#24346 Should fix items not being consumed for the upgrades.

To get your NPC back, the best way to do this is go to debug menu -> t Overmap editor -> t Place Overmap Terrain then hit "/" for search, type in "faction" you should see faction_base_camp_0 at the top.  Work your way down that list, update you camp from level 0 to level 8?, each time trying to return your companion.  When everything aligns, if may let you bring back your companion.  Or just removing all the vehicles could work.  Not sure.
