### ISSUE TITLE
The "Has seen faction camp tutorial" trait should not be visible

### ISSUE THREAD

**Issue by svick** [CleverRaven/Cataclysm-DDA#24342]
Game version: 0.C-29152-geb24087

### Expected behavior

Implementation details of the faction camp system are not visible to the player.

### Actual behavior

When a player reads the faction camp tutorial, they receive the "Has seen faction camp tutorial" trait/mutation:

https://github.com/CleverRaven/Cataclysm-DDA/blob/9752dd74f0001724a849b47d97ab52409d307cd7/data/json/mutations.json#L5205-L5211

I understand that this is a way to track this kind of information, but I don't think it's something that should be visible to the player. I think one way to achieve that is to use a permanent effect, whose display name is empty.

**Comment by Night-Pryanik** [comment]
It will be removed in #24339.

**Comment by acidia** [comment]
Already removed the trait in  #24339, there really isn't much use for it.  What if you wanted to see the tutorial again when you started a new camp?  Its a single y/n query so I figured it wasn't worth it.

**Comment by Night-Pryanik** [comment]
Closed by #24339.
