### ISSUE TITLE
Makeshift Crowbar should be dark craftable.

### ISSUE THREAD

**Issue by Amariithynar** [CleverRaven/Cataclysm-DDA#24345]
### Expected behavior
Able to take something that you can hammer with like a chunk of steel or a rock, find the end of the pipe by touch, and then swing the hammering material down enough times to flatten out the end and roughly bend them a bit, even in the dark.
### Actual behavior
It's 'impossible to craft' in the dark.

Unless you get a light source from a zombie, prison start is pretty much screwed, unless you have previous knowledge of the prison layout. Besides, it really isn't hard to roughly hammer something into shape like that.

**Comment by kevingranade** [comment]
I don't buy that you can do metalworking, even crudely, by touch in the dark.
Also your rationale for doing this to address the prison scenario is flawed, the scenarios aren't intended to be 100% survivable, sometimes you're just screwed.

**Comment by Amariithynar** [comment]
You tend not to buy a lot of things that are pretty damn simple reality, you know that Kevin? You raise and lower your hammering tool striking the same spot repeatedly to flatten out the bar end, it's not rocket science, nor is it even precision work; you just need to flatten out the end so you can lever it into a crack and then pry with it. It'll take a hell of a lot longer than it would if you could see, sure, but it's perfectly doable, just like hammering in nails in the dark; that's  a right pain in the ass, but sometimes your power gets interrupted while you're putting up the last few pieces of drywall, and you have to get everything done on time.
