### ISSUE TITLE
Move `remember vehicle position` action outside of control vehicle menu

### ISSUE THREAD

**Issue by Lasiace** [CleverRaven/Cataclysm-DDA#24353]
I created a separate issue so as to not clutter the other one with something only tangentially related, but #24352 made me realize that the `remember vehicle position` menu, which is currently in the `control vehicle` menu doesn't really belong there, since it has nothing to do with controlling it.

This can actually be relevant when trying to remember a vehicle with a working security system, as you wouldn't be able to remember the position without first hotwiring the vehicle and risking the alarm going off, even if you have no intention of using the vehicle at that moment (such as remembering an electric car or RV you want to scavenge for parts later)

If it is actually possible to move some actions outside that menu, it might be worth considering moving this one out of that menu as well.

**Comment by mlangsdorf** [comment]
I think this is pretty straightforward. I'll add it to my to do list.
