### ISSUE TITLE
Upgrade to Electronics Control

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#24352]
Finally got around to play a little and to check the sub-menu added by @mlangsdorf in #24269 

I love it and I only have one little suggestion to make it even better. Currently it's a little buried in between all the other options in the menu when you have a lot of things installed on your vehicle. Would it be possible to also add it as an option to the "action" menu? 

![image](https://user-images.githubusercontent.com/19891532/42878893-f56dee96-8a8e-11e8-85aa-5381af05e5e9.png)

As a third option to the ^^ menu?

Cheers
-T-

**Comment by mlangsdorf** [comment]
The function is nicely encapsulated, so I think this should be possible.
