### ISSUE TITLE
faction camp upgrade missions don't show up in missions list

### ISSUE THREAD

**Issue by mlangsdorf** [CleverRaven/Cataclysm-DDA#24360]
Game version:
0.C-7581

Faction camp upgrade missions don't show up in the missions list. If the player wants to collect additional items to speed up the pace of camp upgrades, there's no easy reference to see what is required.

**Comment by acidia** [comment]
I'm not sure I understand?  You mean like preempt the mission by building a stockpile of goods so you will be ready for the next mission as soon as the last mission finishes construction?

**Comment by mlangsdorf** [comment]
Well, sort of.
I complete faction_base_camp_4, and I want to perform faction_base_camp_5. I can ask my camp manager, and he'll say I need a hammer, 1 large tent or 4 shelter kits, 24 two by fours, 40 pine boughs, 48 nails, 2 sheet metals, and 12 pipes.
I can set an NPC to gather those items, which I presume will take a couple of weeks, or I could go find them myself. But unless I write them down outside of the game, I can't see what I need to get short of going back and asking the camp manager.

There's a building tab under recipes now, but the recipes aren't showing up there. It'd be good to have a way to see what resources I need to go get for the current upgrade.

**Comment by ZhilkinSerg** [comment]
We probably need something like camp/building recipe menu or display of variuos construction steps in construction menu.
