### ISSUE TITLE
Folding Wire Basket should allow Toolbox to be used in the recipe

### ISSUE THREAD

**Issue by DexityCasual** [CleverRaven/Cataclysm-DDA#24361]
### Expected behavior
Toolbox to be allowed in the third portion of the recipe for folding wire basket requiring any of the tools hacksaw, multi-tool, bolt-cutters or integrated toolset.
### Actual behavior
Toolbox is not a valid tool in the third section of the recipe despite having the same quality or a higher value compared to the other tools allowed in this portion of the recipe.

**Comment by Rod995** [comment]
This could be because items can't be used twice for different things, or somethin', IIRC.

**Comment by Rod995** [comment]
https://i.imgur.com/0gGQho1.png

Picture sent by issue maker.

**Comment by ZhilkinSerg** [comment]
Fixed in #24364.
