### ISSUE TITLE
Fullscreen mode causes unexpected ui behavior, input buffering

### ISSUE THREAD

**Issue by Supermichael777** [CleverRaven/Cataclysm-DDA#24363]
Game version: 0.C 7577

Operating system: Win 10 home, up to date

Tiles or curses: Tiles

Mods active: N/A

### Expected behavior
Menu instantly reacts to keystrokes

### Actual behavior
After first time setup and use which had expected behavior subsequently running the game in full screen would cause inputs on any menu but the main menu to seem to buffer.The first keystroke produced no response and each subsequent keystroke preformed the action expected of the previous keystroke.

### Steps to reproduce the behavior
turn on fullscreen, restart game

**Comment by Tharn** [comment]
Possibly related to this https://github.com/CleverRaven/Cataclysm-DDA/issues/22658
