### ISSUE TITLE
Wielding items off the ground dupes the item

### ISSUE THREAD

**Issue by Nerezza** [CleverRaven/Cataclysm-DDA#24374]
Game version:
Build 7584

Operating system:
Windows 10 64-bit

Tiles or curses:
Tiles

Wielding an item off the ground, either through the wield menu or by picking up high-volume items like steel drums, leaves an exact duplicate of the target item on the ground. **Edit:** The item you're wielding **has to** have enough volume to exceed your max inventory volume if you were to pick it up instead of wielding it.

This was probably caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/24318 because this issue wasn't happening in build 7581

**Comment by mlangsdorf** [comment]
I've seen this happen too on recent builds.

**Comment by Nerezza** [comment]
BTW it's definitely something added in the last day or so. I was moving my rainwater jerrycan around yesterday on build 7581 with no problem, but after updating this morning to 7584 (to get the rubble digging fix) I duped said jerrycan a couple times before I realized there was a bug.

**Comment by Nerezza** [comment]
Build 7582 doesn't have the bug

**Comment by HeyBanditoz** [comment]
Cannot reproduce, although I play the game with curses.

Game version:
d31500b00929f3c205a97304b530eff5b6bd3844

Operating system:
Arch Linux x64

Tiles or curses:
Curses

**Comment by Nerezza** [comment]
@HeyBanditoz I figured out why you couldn't reproduce it, it only happens if the item you're wielding would put you over your max inventory volume.

I'm updating the original post with the new details in a minute but basically the new reproduction would be:
1) Fill your inventory until you can't carry any more, volume-wise. << The thing I missed
2) Wield anything that would throw you over the volume limit (if picked up instead of wielded) off the ground through whatever means possible.

This still only dupes in 7584 for me, and does not dupe in 7582.

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/24318/files#r203856699

**Comment by lucasmr** [comment]
Thanks for @ZhilkinSerg for the fast fix.
