### ISSUE TITLE
When reviewing parts to install, storage battery (and possibly other parts) causes CTD

### ISSUE THREAD

**Issue by Sintua** [CleverRaven/Cataclysm-DDA#24373]
Game version:
build #7584
Operating system:
Windows 10
Tiles or curses:
ChestholeCC
Mods active:
Many, ones with potential interactions are the vehicle addition mods included in the game launcher
### Expected behavior
When examining a vehicle, installing a part, looking at the storage battery should just show the battery information.
### Actual behavior
when attempting to install a storage battery, it causes an immediate crash to desktop. 
### Steps to reproduce the behavior
attempt to install a storage battery. This crash may also be caused by other items like a turret mount.

I believe this is most likely related to the recent addition of the (very useful!) item descriptions in the vehicle examine mode.

**Comment by mlangsdorf** [comment]
storage batteries don't have a description.
and the code that prints out the description doesn't confirm that before trying to print.
Should be easy to fix.

**Comment by mlangsdorf** [comment]
Thanks for the bug report. I think the fix I just pushed will solve the issue but please tell me if it doesn't.

**Comment by Sintua** [comment]
Confirmed! Looks like the fix worked. Though now noticing I can't empty water from the vehicle... I'll see if there's a bug report for that, yet.

**Comment by mlangsdorf** [comment]
I know I can empty water from a vehicle in 0.C-7586, because I did that about an hour ago in my current game.
And even if you can't, I don't think the changes I made would have anything to do with the siphoning code.
