### ISSUE TITLE
Player character's "@" dissapears when grabbed

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#24370]
When playing without a tileset, Instead of getting the blue background you used to get to symbolize being grabbed, your sprite simply disappears.

Maybe related to #23759?

**Comment by Night-Pryanik** [comment]
![default](https://user-images.githubusercontent.com/11132525/43283227-00c375de-9121-11e8-88d0-75af2c433e3f.png)

`c_black_cyan` color, which is used for highlighting grabbed effect, is shown as black in Color Manager for whatever reasons. It seems that cyan background isn't working at all.

There are also some other combinations that are shown incorrect, like `c_brown_yellow` is shown as brown.

**Comment by AMurkin** [comment]
The reason is #24299 probably.

**Comment by John-Candlebury** [comment]
Yeah the reason is   #24299 and was caused by  PR #23419.

Setting A_COLOR to the old value of `0x03fe0000` solves the issue with highlights. 

But maybe it breaks something else? For all I know this is pure black magic.
