### ISSUE TITLE
CBM override in Bright Nights Mod doesn't work.

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#24392]
The Bionic added by Bright Night (Solar panel) can actually be installed manually, but vanilla CBMs cannot be installed.

My best guess is that this is an issue with the load order of overrides and the creation of  definitions that use copy-from.

**Comment by l29ah** [comment]
Couldn't reproduce it: installed any bionics manually, including power storages, on 2365f4b02b.

**Comment by John-Candlebury** [comment]
It's been fixed
