### ISSUE TITLE
Food allergies don't prevent you from absorbing all nutrition.

### ISSUE THREAD

**Issue by Amariithynar** [CleverRaven/Cataclysm-DDA#24409]
As per @DracoGriffin's guidance, reposting my point regarding allergens separate from #24335 

Lactose intolerance is where your body can't break down lactose, but there's other nutrients in milk and other dairy that you can still digest. Beef(meat) intolerance (https://www.yorktest.com/can-you-have-a-beef-intolerance/) is moreso that your body recognizes it as a foreign invader and your immune system attacks it; this doesn't prevent it from being digested, though to be fair digestion is disrupted by everything going on due to the intolerance. In short, vitamins/minerals shouldn't be completely blocked, just reduced, to represent digestive issues and how some intolerances are due to inability to digest certain aspects of an ingredient type, and *all* digestion should be impacted when you eat something you're physically intolerant of, because of that, not just the foodstuff that you're intolerant towards. Source: https://www.ncbi.nlm.nih.gov/books/NBK219100/

**Comment by kevingranade** [comment]
This is the kind of issue "expected results/actual results" was made for, please describe how it works in the game and how you think it should work.
