### ISSUE TITLE
Cattail Jelly: antiseptic, styptic, analgesic.

### ISSUE THREAD

**Issue by Amariithynar** [CleverRaven/Cataclysm-DDA#24414]
Near the base of the stalk of cattails, when peeling the inner leaves off to reveal the tender edible shoot inside, there is a sticky layer of cattail jelly between each inner leaf, in a surprisingly copious volume per plant. This substance is well-known amongst survivalists and historically as an antiseptic, strong analgesic, and styptic; applied to wounds directly or ingested. 

Mechanically, I'd say between 0-3 units of cattail jelly should be able to be harvested from cattails, with the chance of getting more increasing with survival skill. By volume it should use alcohol's units, such that 7 units are equivalent to 250ml, and it should be a byproduct of processing cattail stalks. It should be refinable into hemostatic powder, used in crafting bandages, as well as applicable raw as a painkiller; while there are plenty of sources of this clam, none actually note what the active ingredient is, so for game balance I'd err on the side of caution and leave it about the same strength as aspirin.

Sources: https://books.google.ca/books?id=2LB4OQLv-w8C&pg=PA223&lpg=PA223&dq=cattail+jelly+antiseptic&source=bl&ots=5C2CFfAPc-&sig=3ASO-2Yso-1I8P3sKQBm5qf9SXU&hl=en&sa=X&ved=0ahUKEwjE5d3u6rDcAhW-CjQIHfa3D3IQ6AEI3wEwGw#v=onepage&q=cattail%20jelly%20antiseptic&f=false & https://www.youtube.com/watch?v=eBfIORVLNUA amonst others easily available online.

**Comment by vasekhodina** [comment]
Hello, I've taken the liberty of adding this item in #27908.
