### ISSUE TITLE
Discarded empty cans from faction camp are still unopened

### ISSUE THREAD

**Issue by RadHazard** [CleverRaven/Cataclysm-DDA#24424]
Game version: 0.C-29408-gc762328a2b

### Expected behavior
After distributing canned food at a faction camp, the empty opened cans are strewn about the firepit

### Actual behavior
The empty cans are thrown everywhere as expected, but they're still sealed (somehow).  The sealed cans are useless for crafting and can't be opened without any contents in them.

### Steps to reproduce the behavior
Build a camp, spawn a can of beans, distribute the can

**Comment by acidia** [comment]
Just needed to add i.on_contents_changed(); before throwing the empties all over the place.

**Comment by Night-Pryanik** [comment]
Closed by #24427.
