### ISSUE TITLE
Camp Farming returns invalid item ~ canola seed 0, leads to crash

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#24426]
Game version:
#7592
Operating system:
Windows
Tiles or curses:
Tiles
Mods active:

### Expected behavior
Got canola seed(0) from camp farming, had it in my inventory for a while until I tried to put it in cargo space in my car. That crashed the game.
### Actual behavior
No 0 of canola seed
### Steps to reproduce the behavior
I unfortunatelly don't know exact steps. I gave the seed planter blueberry, strawberry and canola seeds, 3 of each. After 25/4 hours I called him back and it was planted as expected. He returned zero canola seed (under me, as everything is got from camps). It was actual zero. I picked it up and later put it into cargo space in car and the game crashed.

**Comment by acidia** [comment]
One line fix, another for redundancy.  Shouldn't be an issue any more.

**Comment by Night-Pryanik** [comment]
Closed by #24427.
