### ISSUE TITLE
Menial Labor in Player/NPC Camps Deletes Items From Your Save

### ISSUE THREAD

**Issue by aman3600** [CleverRaven/Cataclysm-DDA#24425]
Game version: experimental #7591

Operating system: Windows

Tiles or curses:

Mods active:

### Expected behavior
When you ask an NPC to sort items outside of your base, you'd expect them to move things around neatly
### Actual behavior
If your number of items in a category exceeds 1000L, everything else gets deleted. I.E. If you have 200 logs and 400 planks, they'll try to put all of them into one space, and delete everything that doesn't fit
### Steps to reproduce the behavior
Add more than 1000L of volume of a specific category I.E. wood outside of a player run base and ask for menial labor to be done

**Comment by acidia** [comment]
This is strange, if I wish for 1000 logs and drop them, they spill out to all adjacent tiles (which was the expected behavior).  If I sort a 1000 logs it just deletes any overflow.

**Comment by Night-Pryanik** [comment]
Closed by #24427.

**Comment by ATGOct** [comment]
Getting similar behavior.  My (Y) stockpiles outside of the Faction camp have several big piles that simply disappear when the Menial Labor mission returns.
