### ISSUE TITLE
Extract Faction Camp Mission into json

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#24435]
The current stucture of src/mission_companion.cpp is rather "messy" and make translating new content kind of painful.

Mission definition are mostly hardcoded and with manual formatting in between lines.

It would be great to restructure this into common function which load definition/requirement/risk/reward etc from .json and get ride of manual formatting.

**Comment by cainiaowu** [comment]
Also there are a lot of comparing cur_key with various mission NAME string directly, which including various uses of find() function, to determine branching of each mission, which may or may not be a problem when that NAME change in various language by various translator.

**Comment by cainiaowu** [comment]
The latter part is done, now only the first part remains.

**Comment by mlangsdorf** [comment]
I'm cleaning up the code now. Extracting it into JSON isn't particularly hard, but it will be tedious and the pay-off in terms of player experience is pretty low.

**Comment by cainiaowu** [comment]
Close as faction camp recipe somewhat solved this.
