### ISSUE TITLE
Power armor environmental protection needs review

### ISSUE THREAD

**Issue by Nerezza** [CleverRaven/Cataclysm-DDA#24434]
After having an incident of toxic gas exposure in some light power armor, then spending four-ish hours reviewing how the Environmental Protection stat resists various hazards, I wanted to bring some attention to the stats set on power armor at the time of their creation 5 years ago.

First, the my original post made some assumptions about the quality of power armor's protection based on how filter masks, gas masks, and ANBC suits are set up, and then those assumptions were further complicated by the fact that I was using a dice calculator that rounded after the second decimal place.

I've since had some sleep (OP was done at like 2AM) and have reviewed my original findings, and found the following: Heavy Power Armor and RM13 Power Armor are both at the EP threshold of 15 (RM13 has 15 EP, Heavy has 16 EP) for complete protection from heavier hazards. Basic power armor sits just above the EP threshold of 9 (it has 10 EP) for complete protection from moderate hazards. Light Power Armor is just below the above threshold of 9 for complete protection from moderate hazards, at 8 EP.

What does this mean? RM13 and Heavy power armor will NEVER be affected by dense toxic gas (including fungicidal), glowing boomer bile, and acid. Basic power armor has a tiny chance (about 3 in 10,000) of being affected by the above. Light power armor has about a 1 in 80 chance of being affected by the above, _and_ it has a miniscule (less than 1 in 10,000) chance of letting moderate toxic gas, heavy smoke, regular boomer bile, and even fungal spores through.

Basically I've concluded that the power armor EP stats were assigned arbitrarily in an attempt to scale protection according to armor class, and done so seemingly without a full understanding of how EP works. The EP already set on these armors IS fairly adequate (I'd assumed it wasn't when I first opened this issue, though, but have changed my mind) but the stats are spread in a rather sloppy manner, most evident in light power armor since there's still an incredibly rare chance to 'win the fungal spore lottery' and fail the resistance roll against them.

The chances of being covered by fungal spores while wearing Light power armor is small enough that it will almost never occur, but since it CAN happen, it appears to be an oversight. Similarly, you CAN get a lungful of toxic gas through basic power armor, too. Now that I've come to better understand how EP works, and now that I've realized EP has to be set to certain thresholds to fully prevent seemingly bizarre exposures to certain hazards (fungal spores creeping through your sealed suit's seals and onto your skin, boomer bile squirting through your sealed helmet's seals into your eyes), I'm thinking about bringing Basic power armor's EP up to 15 (though probably 16 to match the protection of gas masks) and Heavy up to 20 (since it's supposed to have even better protection than the other models.)

For Light power armor, although I would like to jump it up to 15 EP that would nearly double its EP and power armor balance is a pretty touchy subject judging by the history I've seen for them, so I want to get feedback first. At the least, Light power armor's EP should be bumped up to 9 so that no one will ever win the fungal spores lottery while wearing it, however I'm of the opinion that it should get full protection from heavy hazards too (so the aforementioned 15 EP) since I consider it bizarre that it'd let you have an occasional lungful of toxic gas, or potentially let glowing boomer bile squirt into your eyes.

As a final note I was thinking that power armor should get the GAS_PROOF flag applied, but the flag is meant for full-body suits only and should only be applied to RM13 power armor. This means that fungal-mutated people will NOT have their arms/legs/head/eyes/torso protected against fungicidal burns while wearing other types power armor, but this is a consequence of how fungicidal gas was implemented and the only fix is to remove the GAS_PROOF flag and replace it with full-body EP checks instead.

**Comment by Night-Pryanik** [comment]
> There's no GAS_PROOF flag

There IS a 'GAS_PROOF' flag.

**Comment by Nerezza** [comment]
I mean there isn't one on the power armor.
