### ISSUE TITLE
Need auto forage mode to reduce tedium for foraging

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#24438]
Game version:
master
Operating system:
any
Tiles or curses:
any
Mods active:
any
### Expected behavior
We have auto pickup, auto pulping but no auto forage mode.

When active, auto forage mode should like what auto pulping mode does except foraging nearby trees/underbrush.
### Actual behavior
Many Many Many key press.

### Steps to reproduce the behavior
 Try forage in your nearest forest.

**Comment by CoroNaut** [comment]
I've foraged maybe 2 bushes in my long time playing cdda, but I can see the amazing precision and accuracy of someone pressing 300 keys/sec on their numpad to target all them bushes. Is this really tedium or a fast-typing mini game? :smile:

**Comment by ZehCastro** [comment]
Should this be an extension of the Auto-Pickup system that already exists?
