### ISSUE TITLE
Items become white squares on recent versions

### ISSUE THREAD

**Issue by RafeHaab** [CleverRaven/Cataclysm-DDA#24447]
Game version: 7597 to 7602 (latest)

Operating system: Windows 10

Tiles or curses: Tiles (retrodays. NOT retroascii)

Mods active:
DDA
Filthy clothing
simplified nutrition
generic guns
makeshift items
more survival tools
alternative map key
mining
npc traits
boats
vahicle aditions
tanks
disable mutagens
no sci-fi
stats through skills

### Expected behavior
Items on floor are recognizable by their tiles until v. 7596

### Actual behavior
Items on ground are shown as white squares instead
![cataclysm](https://user-images.githubusercontent.com/13240019/43094934-ade838ec-8e8a-11e8-947f-0ff0d57284c5.png)

### Steps to reproduce the behavior
Generate a world using any version up to 7596, Update to latest version. Do anything with that world, be it either reset the world and use a preset to make a new character, or load a previous save. Items on the ground will be glitched.

**Comment by RafeHaab** [comment]
When I go to the graphics options, it just says "retrodays". It's not retroascii, if that's what you are asking.

I'm sorry I can't help you resolve the bug I'm reporting myself. I'm not knowledgeable enough.

**Comment by Break-Off** [comment]
Can confirm. Item sprite is not shown when there are multiple items on the same floor tile (blue border). Weather animations sprites are also borked.

**Comment by RafeHaab** [comment]
Thank you! That was fast.
