### ISSUE TITLE
Lava on the roof

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#24459]
I just came across this weird thing

![image](https://user-images.githubusercontent.com/19891532/43141591-961d3146-8f56-11e8-9704-588b07c61f54.png)

Lava stripe on the top of Apartment Tower. 

I see no logic in it? Should only be on the ground level?

**Comment by ZhilkinSerg** [comment]
No Z-level check in the code:

https://github.com/CleverRaven/Cataclysm-DDA/blob/f17b5b985ba1e66727be478af2a24b629de1d267/src/map_extras.cpp#L508-L519
