### ISSUE TITLE
Foraging behavior is inconsistent

### ISSUE THREAD

**Issue by Blank99** [CleverRaven/Cataclysm-DDA#24453]
### Expected behavior
If I try to forage something, be it bushes, a tree, or a plant on the ground, I'd expect everything to follow the same behavior. Be it everything dropping the items at the player's feet, or the items appearing on the tile being examined and the game opening the pickup interface for that tile.

### Actual behavior
Some are looted from the tile the examined object is, while others are dropped at the character's feet or on a nearby tile. This makes foraging more annoying than it needs to be.

**Comment by Blank99** [comment]
Nope.
Can't check at the moment, but if you go and pick, say, daturas, poppies, and the other flower/root things I can't recall at the moment, some drop at your feet, but some appear at the spot the plant was and a pickup menu is opened.

**Comment by UncleBenis** [comment]
Can confirm that its pretty annoying that picking flowers works differentely from foraging,

**Comment by Treah** [comment]
I agree this is worthy of being looked into and fixed. this is a long time issue with CDDA tho..

**Comment by lucasmr** [comment]
I'll take a look.

**Comment by lucasmr** [comment]
OK, before I send the PR, let's find all instances where harvesting doesn't drop the items on the player's feet, or where a menu appears after harvesting. I've found 5 cases: poppy flower, dahlia flower, marloss flower, marloss shrub and spider egg sacks. If you find another case, let me know.
