### ISSUE TITLE
NPC Duplicates When Swapped into Inappropriate Player Tile

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#24466]
Game version: Experimental 7602

Operating system: Windows 7 64-bit

Tiles or curses: Tiles

Mods active: (Dark Days Ahead, Filthy Clothing, Disable NPC Needs, Simplified Nutrition, StatsThroughSkills, Vehicle Additions Pack, Tanks and Other Vehicles, Folding Parts Pack, NPC Traits, Mutant NPCs, MXotto+ Cosmetics, [DracoGriffin Mod](https://github.com/CleverRaven/Cataclysm-DDA/files/2226684/DG_Mod.zip), More Survival Tools, Medieval and Historic Content, No Fungal Monsters) -- **Experimental Z-Levels enabled**

### Expected behavior
NPC Follower should be swapped to an adjacent empty tile.

### Actual behavior
NPC Follower swaps to adjacent empty tile but duplicates, turn invisible randomly between movements, teleports around map and has a doppelganger (using debug menu to select NPCs or `C` to talk shows duplicate NPCs).

### Steps to reproduce the behavior
Load save. ![loadsave](https://user-images.githubusercontent.com/32253888/43182584-30ec6ab4-8f9f-11e8-819f-de468eb3c2be.png)

Descend z-level. ![swapnpc](https://user-images.githubusercontent.com/32253888/43182614-4694a660-8f9f-11e8-9fde-a4466f17a2a5.png)

 Swap tile with NPC. ![npcduplicated](https://user-images.githubusercontent.com/32253888/43182623-4dac3ce2-8f9f-11e8-909f-0ee63b2f6880.png)

Discussion:
If you load the save and don't descend and instead move away from the stairs and wait a few turns, the zombie should arrive up the stairs (due to enabled experimental z-levels). So it looks like the timing was just right for my character to descend and share the same tile/space as the zombie and then it goes haywire.

Save game attached for reproducibility.
[Phantom NPC Bug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2226675/Phantom.NPC.Bug.zip)

**Comment by kevingranade** [comment]
Thanks for the amazing reproduction case.
