### ISSUE TITLE
[RFC] NPCs and CBMs: Allies upgrading you

### ISSUE THREAD

**Issue by mlangsdorf** [CleverRaven/Cataclysm-DDA#24475]
If the PC has an NPC ally with superior skills, the player should have the option of asking the NPC to install CBMs through an autodoc.

The iexamine::autodoc function would need to be revised to detect NPCs in the area, calculate their effective skill for installing CBMs, and give the option of letting the NPC do the install instead of the player if the NPC's skill is better.

I intend to implement this sometime in the next few weeks unless someone tells me not to or someone else wants to implement in earlier themselves.

**Comment by DracoGriffin** [comment]
All yours.

**Comment by NubNub69** [comment]
Even if they can install a CBM can they use it thou?

**Comment by mlangsdorf** [comment]
This is for letting a NPC with superior skills install a CBM on you (or another person, because the code path is the same). The question of letting NPCs use CBMs is another issue.
