### ISSUE TITLE
Camp Manager, duplicated, teleporting

### ISSUE THREAD

**Issue by xrandomuserx** [CleverRaven/Cataclysm-DDA#24482]
Game version: 7600
Operating system: XP (ftw)
Tiles or curses: Tiles

Mods active: DDA, Filthy, NPC Traits, Boats, Tanks, Vechile Additions, No flaming weapons, More buildings, urban development.

### Expected behavior
Setup a nice camp and survive the cataclysm

### Actual behavior
Setup camp, near fields and forest as instructed. Camp manager started to disappear when standing one tile away. After being in the nearby forest, two @@ was at camp, thought it was another npc, but was only the camp manager. I closed the camp so I could get the NPC back, started teleporting randomly around, still thinks he was two people (@@)

### Steps to reproduce the behavior
Make your NPC follower a camp manager in 7600 experimental, watch them develop another personality and gain erratic teleportation ability

**Comment by acidia** [comment]
LOL, wut?  I just tried this and everyone was working normally.  Did you give your NPC a relic with tele-sickness or whatever?  If you look at your NPCs stats do they have any nether illnesses?  Can you post a picture or tell me what exactly you did to make your NPC blink/disappear the first time?

**Comment by xrandomuserx** [comment]
no. first day. its a bug with the new camp system.

**Comment by acidia** [comment]
Is it doing it every time you try to build a camp?  I can't replicate it so I need a more information.

**Comment by 0be1isk** [comment]
Reading this, I chuckled at how odd this is, I have not even encountered this oddness in the slightest

**Comment by FulcrumA** [comment]
I am prtty sure I knwo what bug it is, and it's not camo issue. It's an NPC issue. It's an NPC issue since a very long time, possibly feature introduction, but it's helluva hard to pinpoint - NPCs just sometimes at random teleport around or make disappearing clones of themselves. Saving and realoading the game usually fixes it in such cases.

**Comment by DracoGriffin** [comment]
>Setup camp, near fields and forest as instructed. Camp manager started to disappear when standing one tile away. After being in the nearby forest, two @@ was at camp, thought it was another npc, but was only the camp manager. I closed the camp so I could get the NPC back, started teleporting randomly around, still thinks he was two people (@@)

Honestly sounds related to my issue #24466, especially as FulcrumA describes it further.

So potentially somehow OP got his NPC moved into an inappropriate tile and things went haywire.

**Comment by kevingranade** [comment]
OP, had you teleported while bear the NPC?

**Comment by xrandomuserx** [comment]
no, i had just started the game, no teleporting.

I think it may be that npc issue. i did also swap places with the npc, just before making him the camp manager. But I must say the NPC was not duplicate to the point where I could have conversation with two npcs.

I loaded the save just yesterday. 'Larion' still called himself a camp manager, luckily there was a local jabberwock to feed him and myself to, thankfully no one will remember them.

sorry no pics, system setup is on pc away from internet

fyi he didnt go crazy teleporting/duplicate straight away. only after i was foraging in the forest for a while, I may have slept close to him also. cant say i expected this to happen at all.

**Comment by Night-Pryanik** [comment]
No confirmation in over half a year, closing.

**Comment by xrandomuserx** [comment]
I hope this bug does not still linger in the code somewhere. I always play with NPC's and now always play with Z-levels. Will post saves whenever I have an issue with NPC's and their behaviours. I currently avoid the camping system, more due to play style, but also do not wish to break the game.
