### ISSUE TITLE
Two Mutation Suggestions For Bird/Fish Trees

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#24497]
**Countercurrent Circulation** --- Bird/Fish Post-Threshold --- If torso temperature is comfortable, limb (arms/legs) suffer 25%/33%/[X%] less from temperature effects. Likewise, if torso temperature is too cold or hot, limbs suffer 25%/33%/[X%] more from temperature effects. (I believe this is already something that exists in game but not sure where the code is or the values, but this would basically boost that dramatically -- this mechanism is critical for organisms to survive freezing depths/biomes)

[Source](https://en.wikipedia.org/wiki/Countercurrent_exchange#Countercurrent_exchange_of_heat_in_organisms)

**Countercurrent Hydration/Ingestion** --- Bird/Fish Post-Threshold --- Allows survivor to drink salt water with no penalty, but Quench value is dramatically reduced (15 or [X] small amount). Value may be arbitrary since salt water terrain sources are infinite, so it would just result in more keystrokes from player, in which case the Quench value could stay the same.

[Source](https://en.wikipedia.org/wiki/Countercurrent_exchange#Countercurrent_exchange_in_sea_and_desert_birds_to_conserve_water)

**Comment by FulcrumA** [comment]
The latter, rather than by the thirst values, could be balanced by, for example, impact on healthiness or nutrition, suggesting that while it may be beneficial short-term, absorption of certain elements still impacts the body or that the mutations is not completely compatible with the body long-term.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
