### ISSUE TITLE
schizophrenia causing random sleep seems too much

### ISSUE THREAD

**Issue by PrinnyDoodman** [CleverRaven/Cataclysm-DDA#24496]
As the title says, you can randomly attempt to fall asleep at any time. Easily the worst example of this is falling asleep while driving, which is pretty much a guaranteed death.

**Comment by Rod995** [comment]
Think we should make it a separate thingie like someone suggested on the Discord?

**Comment by Mecares** [comment]
Maybe instead sometimes add a random amount of tiredness so you might fall asleep suddenly but only if you were close to become unconscious because of sleep deprivation anyway. Then the effect would be at least a bit more manageable.

**Comment by FulcrumA** [comment]
Yeah, I'd limit schizophrenia to mostly audio-visual hallucinations combined with some involuntary actions or random disruptions of others rather than lasting effects taking any control or ability to mitigate the effects out of player's hands.

**Comment by John-Candlebury** [comment]
In any case narcolepsy doesn't seem to be a symptom of schizophrenia
