### ISSUE TITLE
Human corpses don't spawn in labs & other locations

### ISSUE THREAD

**Issue by niglow** [CleverRaven/Cataclysm-DDA#24514]
Game version: 7619

Operating system: Windows 10 x64

Tiles or curses: Tiles

Mods active: none

### Expected behavior
Labs were guaranteed to have two human corpses in rooms with water & fire axe behind a glass wall.

### Actual behavior
There are no corpses.

### Steps to reproduce the behavior
Start a game, find the room, see for yourself.

This also influences other locations where human corpses should spawn: hospitals, drug deals, survivor basements, etc. This makes aspiring cannibals very sad.
Tested with Windows 8 x64 - no such issue.

**Comment by niglow** [comment]
@BrianLefler, thanks for the tip - I completely forgot that starting season could influence this. The thing is that I always start in winter. Re-checked other seasons - corpses could be found only if you start in spring, starting in any other season will make the corpses disappear.

**Comment by niglow** [comment]
@BrianLefler, thanks for the tip - I completely forgot that starting season and season length could influence this. The thing is that I always start in winter and play with 91 days long seasons. Re-checked other seasons with the same settings - corpses could be found only if you start in spring, starting in any other season will make the corpses disappear.
With default 14 days season length starting in summer makes meat from these corpses rotten, autumn and winter starts make the corpses to rot away.

**Comment by Zireael07** [comment]
I believe we have the bug with stuff rotting in ice labs?

**Comment by niglow** [comment]
@Zireael07, just checked, can confirm - no human corpses in ice labs if started "late".
