### ISSUE TITLE
Makeshift Crossbow in More Survvial tools uses Archery skill to craft

### ISSUE THREAD

**Issue by Xenomorph-III** [CleverRaven/Cataclysm-DDA#24511]
Game version: 0.C-29649-g2b2450e

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Dark Days Ahead, Disable NPC Needs, Prevent Zombie Revivification, Safe Autodoc, More Survival Tools, No Fungal Monsters.

### Expected behavior

The Makeshift Crossbow should only need Fabrication 2 and Survival 1 to craft, in light of #23973, #21630, #21629 and #21545.

![crossbowproposal](https://user-images.githubusercontent.com/25373560/43350482-a9b6c0d4-925b-11e8-8283-b64b570a56e1.PNG)

### Actual behavior

While the Makeshift Crossbow is auto-unlocked at level 2 Fabrication, it still requires Archery 2 to create. This discrepancy is further emphasized by the fact that it uses Rifles as a primary skill instead of Archery.
![crossbow](https://user-images.githubusercontent.com/25373560/43350464-63692342-925b-11e8-8c92-298be37f4868.PNG)

### Steps to reproduce the behavior

Start a new world with the More Survival Tools mod enabled.

Spawn a new character.

Use debug menu to raise Fabrication to 2, Archery to 2 and Survival to 1.

Wonder why Archery is still required to make a crossbow despite the fact it uses "rifles" as a primary skill.

**Comment by Xenomorph-III** [comment]
@DangerNoodle , I would like to ask your opinion on this change before I make it official.

**Comment by DracoGriffin** [comment]
>Also, how do I make a pull request? The "comparison" functionality threw me off.

Sorry, I missed your edit. Here's the step-by-step basically:

![makenewbranch](https://user-images.githubusercontent.com/32253888/43360311-ba34ee44-9270-11e8-8f5a-748be37021fd.png)

First, make your new branch locally on your forked repo. If you don't know how to fork, on the very top right of this page, you should see a "Fork" option. Click that.


In your newly forked branch, make your changes (basically removing that line `, [ "archery", 2 ]`) however you want (through GitHub website, through GitHub Desktop, through Git, and so on). The easiest for this would probably be the website if you don't know or have the other options yet.

![makenewpullrequest](https://user-images.githubusercontent.com/32253888/43360312-ba4b7b0a-9270-11e8-92dc-dae28913a726.png)

With your changes saved, come back to the main CDDA repo and you should see a new banner option to create a Pull Request. Click that and then begin making your title and reasoning for changes (as you detailed above with all the links to changes, I wrote up a sample summary). Double-check your commit changes so it isn't including things it's not supposed to (basically, just make sure only the line you removed in your branch is the only thing here and doesn't have any additional artifacts from other stuff).

![createpullrequest](https://user-images.githubusercontent.com/32253888/43360310-ba1fcd16-9270-11e8-8e81-3d4f8cffc43c.png)

Then click Create Pull Request and then it will go through the approval process and hopefully gets merged. Congrats!
