### ISSUE TITLE
Glare protection on light survival mask does not work.

### ISSUE THREAD

**Issue by TonicArtos** [CleverRaven/Cataclysm-DDA#24510]
Game version: 0.c-29383
Operating system: Linux
Tiles or curses: Tiles
Mods active:
    Medieval and Historic Content
    More Survival Tools
    Boats
    Folding Parts pack
    Vehicle Additions Pack
    Filthy Clothing

### Expected behavior
For the light survival mask to prevent the sunlight from really irritating my eyes as other items with glare protection 1 do.

### Actual behavior
Does not prevent irritation of eyes.

### Steps to reproduce the behavior
Get a light survival mask and walk out into the sun with very light sensitive mutation.

**Comment by Night-Pryanik** [comment]
Should be fixed by #24524.
