### ISSUE TITLE
Metal arrow is better than Sharpen Metal arrow

### ISSUE THREAD

**Issue by Duhuh123** [CleverRaven/Cataclysm-DDA#24523]
Game version:
About two weeks ago from github.
Operating system:
Linux
Tiles or curses:
Tiles
Mods active:
Default.
### Expected behavior
I expect sharpen metal arrow has better stat than metal arrow.
I have been using sharpen metal arrows forever without thinking about metal arrows ...

### Actual behavior
Metal arrow has better stat than sharpen metal arrow, at least in the craft screen.

Metal arrow:

- Damage 14, Armor-pierce 7, Range 10, Dispersion: 60

Sharpen metal arrow:

- Damage 5, Armor-pierce 3, Range 5, Dispersion: 285

### Steps to reproduce the behavior
Check entries at item browser:
http://cdda-trunk.chezzo.com/arrow_metal_sharpened_fletched
http://cdda-trunk.chezzo.com/arrow_metal

**Comment by NotFuji** [comment]
The metal arrow has an actual arrowhead, whereas the sharpened one is just a pointy metal stick.
