### ISSUE TITLE
Firing bows while steering a bike

### ISSUE THREAD

**Issue by Karthas077** [CleverRaven/Cataclysm-DDA#24525]
Currently using game version 0.C-29642-g25997f3, running into some balance weirdness with regards to bows and bicycles. Even putting aside the fact that the game apparently allows you to fire a compound bow backwards while steering a bicycle with your knees, I feel like a character with Archery 3, Driving 4, 11 Str, 11 Dex, and 9 Per should not be able to casually ride an unmodified bike in circles around a Zombie Hulk whilst plinking it with arrows from a compound bow.

For one, it appears that because the vehicle is the thing doing the moving, you still get the reload_and_shoot steadiness compensation. If you were standing on the bed of a moving pickup truck that wouldn't be too weird, but while actively pedaling a bike and still somehow twisting around backwards? Seems iffy.

Secondly, the chance to lose control of a vehicle and skid out doesn't appear to be influenced at all by the player firing a weapon with one or more hands.

**Comment by Karthas077** [comment]
Been doing some more looking into this situation, and it appears like this behavior doesn't happen with things that aren't bikes, because non-tire vehicle parts get in the way. With a bike, you can shoot all around you with no problem because there's no non-tire parts to block the aim.

**Comment by mlangsdorf** [comment]
I don't want to dig into the relevant code right now, but there should probably be a check for vehicle movement when calculating aim and stability, and unless you're aiming a stabilized turret, there should be a limitation to steadiness.
