### ISSUE TITLE
Shouting NPCs will interrupt you with message saying you are shouting yourself.

### ISSUE THREAD

**Issue by MT-Arnoldussen** [CleverRaven/Cataclysm-DDA#24535]
Game version: 0.C-29716-gc6c3ebb (tiles)

Operating system: Windows 10

Tiles or curses: Tiles

Mods active:   "dda",  "filthy_morale",  "novitamins",  "a_mutated_arsenal",  "makeshift",  "More_Survival_Tools",  "alt_map_key",  "mutant_npcs",  "npc_traits", "more_buildings",  "more_locations",   "Experimental-Z-Level",  "Urban_Development",  "boats",  "deoxymod",  "no_religious_Texts",  "more_classes_scenarios",  "no_reviving_zombies",  "StatsThroughSkills"

### Expected behavior

When an NPC with "shouter" shouts while you are reading, the game will ask you to stop because you heard your NPC shout.

### Actual behavior

It will ask you to stop because you heard yourself shout.

### Steps to reproduce the behavior

Start a game with the "npc_traits" default mod, acquire NPCs until you get one with "shouter" trait, and perform long actions until they shout while you are performing the action.

[dropbox link to a .7z file with my save and my mod folder to easily check if it was fixed.](https://www.dropbox.com/s/ubnoxjgpvu23ax7/save.7z?dl=0) There's an NPC with the shouter trait and some books nearby to read.

**Comment by RadHazard** [comment]
This seems to be a bug with the shouting description in general.  You can also see in the log "You hear yourself shout to the north!" If they happen to be standing to the north, for example.  No long action needed.

I can confirm via firsthand experience with a wolf NPC that this same bug also affects the howler mutation.  Presumably screamer is also affected.
