### ISSUE TITLE
Monster warning when opening doors or descending stairs

### ISSUE THREAD

**Issue by happypandaface** [CleverRaven/Cataclysm-DDA#24532]
This is mostly how I get killed is by descending stairs and immediately being torn to pieces by a turret or opening a door to a similar fate. It would make more sense if, while opening doors or descending stairs, a character with high perception would get a warning about new monsters appearing, similar to alerts you get while crafting and seeing new monsters. At this point the character could choose to return up the stairs or stop opening the door, avoiding conflict.

I want to start contributing to this project, so, let me know if this sounds like a decent idea and I'll look into working on it.

Game version:
7204-PLUCK

Operating system:
Ubuntu 16

Tiles or curses:
Curses

Mods active:
None

**Comment by kevingranade** [comment]
I'm generally in favor of this kind of thing, if a player is about to take an action that changes their field of view (and more importantly might change whether monsters can see the player), and they are moving cautiously (not running, safe mode on), they can detect threats as if they had made the move, and new threats trigger safemode, i.e. cancels the action and prompts the player to confirm stepping into Los of an enemy.

**Comment by Endovior** [comment]
Perhaps allow the Peek action to be performed on closed doors or stairways? It seems like that would give the careful player the advantages of your proposal, without requiring too much in the way of extra coding.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
