### ISSUE TITLE
Ballooning log file and numerous crashes

### ISSUE THREAD

**Issue by Lorith** [CleverRaven/Cataclysm-DDA#24547]
Game version:
0.C-7626
Operating system:
Win7
Tiles or curses:
Tiles
Mods active:
Default -- DDA, Filthy Clothing, Disable NPC Needs, Simplified Nutrition
### Expected behavior
Log files don't instantly balloon to huge sizes, lab starts don't crash to desktop without leaving error messages in the log.
### Actual behavior
After making a world and loading a character, the game promptly spews huge amounts of errors into the log regarding negative scientific notation for population of monster groups.

2:21:32.379 : Starting log.
2:21:32.407 INFO : Language is set to: 'en'
2:21:33.973 WARNING : opendir [./mods/] failed with "No such file or directory".
2:21:34.24 SDL : src/sdltiles.cpp:2101: Failed to load audio file data/sound/Basic/Dark_Days_Ahead_demo_2.wav: Couldn't open 'data/sound/Basic/Dark_Days_Ahead_demo_2.wav'
2:21:55.680 WARNING : opendir [./save/Cornettsville/mods] failed with "No such file or directory".
2:22:0.891 INFO : Loaded tileset: ChestHole
2:22:11.317 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.317 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.317 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.317 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.317 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.317 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.317 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.317 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.317 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.317 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.317 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.317 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.318 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.318 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.318 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.318 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.318 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.318 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.318 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.318 GAME : GROUP_GOO: invalid population here: -1.37487e-016
2:22:11.318 GAME : GROUP_GOO: invalid population here: -1.37487e-016

This continues for about 3,000 lines for a evac center spawn, spread across numerous groups.

Additonally, trying to make a lab start, the game crashed 14 times with no clear cause in the logs, and after working the 15th time, resulting debug.log was 4MB.

**Comment by ZhilkinSerg** [comment]
Did you compile by yourself or started downloaded version?

I cannot reproduce crashes wit downloaded version - I've successfully started many times occasionally getting following error:

![image](https://user-images.githubusercontent.com/16213433/43389454-6e2d83f0-93f4-11e8-9d2a-777811545b4c.png)

Even with this error - game is not crashing and player character still starts in Lab.

**Comment by ZhilkinSerg** [comment]
Finally I've reproduced the crash - game segfaulted when trying to start in Lab.

**Comment by nexusmrsep** [comment]
Oh no, not this again. I thought it was fixed recently. Theres got to be some way to check if map exists before adding m.temperature. m.temperature is an ovelay to weather temperatures, and is needed for ice labs to work properly but it seems that map does not exist at the time of chargen.

**Comment by nexusmrsep** [comment]
@ZhilkinSerg, I poked around the 'game.cpp' and might have found a walk-around the part of the problem.
When I tried this:

`int game::get_temperature( const tripoint &location )
{`

    if ( location.z < 0 ) {
        // underground temperature = average New England temperature = 43F/6C rounded to int
        if( new_game ) {
            return 43;
        } else {
            return 43 + m.temperature( location );
        }

    }
    // if not underground use weather determined temperature
        if( new_game ) {
            return temperature;
        } else {
            return temperature + m.temperature( location );
        }
}

I found that compiled version still pushes a `debug_msg`  `"Could not find a good starting place for the character."`, but it does not crash/hang.

Trick here is using the `bool new_game` that shows that the game is on loading phase, so not all things are accessible - it its true `get_temperature()` gets trimmed and brefly does not use `g->m.temperature` overlay that doesn't exist at this starting phase.

If you could confirm it on your side, I'll quickly drop a PR afterwards.

**Comment by ZhilkinSerg** [comment]
I guess we can simplify it to something like this:

```c++
int game::get_temperature( const tripoint &location )
{
    //underground temperature = average New England temperature = 43F/6C rounded to int
    return ( location.z < 0 ? 43 : temperature ) + ( new_game ? 0 : m.temperature( location ) );
}
```

**Comment by nexusmrsep** [comment]
Sure, but will it prevent crashes in chargen? (after few failures on this I start to doubt my own eyes).
