### ISSUE TITLE
Glasses don't help with near/far-sightedness

### ISSUE THREAD

**Issue by niglow** [CleverRaven/Cataclysm-DDA#24549]
Game version: 7627
Operating system: Windows
Tiles or curses: Tiles
Mods active: PKs_Rebalancing

### Expected behavior
Eyeglasses, reading & bifocal glasses should negate near-sighted and/or far-sighted traits effects.

### Actual behavior
They don't.

### Steps to reproduce the behavior
Make a character with any kind of eye problems wear glasses and see that they are not effective anymore. Contact lenses still work.

**Comment by sfsworms** [comment]
Maybe linked to #24527 ?

**Comment by Rail-Runner** [comment]
Well, I did test it before making a pull request, and it was working for me.

**Comment by ZhilkinSerg** [comment]
Can you provide archive with your savegame?

**Comment by niglow** [comment]
My bad - tested with another world that had PKs enabled and PKs doesn't have these new flags yet.

**Comment by ZhilkinSerg** [comment]
Does PK change glasses?

**Comment by niglow** [comment]
Yes, in the file file \PKs_Rebalancing-master\items\armor_override.json the "SKINTIGHT" flag is being added to them

**Comment by niglow** [comment]
Yes, in the file \PKs_Rebalancing-master\items\armor_override.json the "SKINTIGHT" flag is being added to them.

**Comment by Night-Pryanik** [comment]
I guess this issue can be closed then.
