### ISSUE TITLE
Kearny fallout meter

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#24560]
It turns out there is a ridiculously easy to construct radiation meter, though it has a number of drawbacks.

https://en.wikipedia.org/wiki/Kearny_fallout_meter

As far as I can tell, this couldn't be easier to construct, with the only drawbacks being:
Book recipe only. This was designed by a leading nuclear research scientist, it seems unlikely that a player will come up with the same solution from first principles.
Not mobile. The design of the meter means it is unlikely to work properly when in motion.
Requires active monitoring and timekeeping.  The meter works by charging the leaves with static, exposing the meter to a potential radiation source for 15+ seconds, then observing the difference in leaf position to determine the dosage rate.

**Comment by StripedMonkey** [comment]
For those that would like it here's a PDF of its construction (via External links at the bottom of the wiki page)

http://www.abomb1.org/pdf/kfm_inst.pdf

What are you proposing the recipe be?
