### ISSUE TITLE
Add ability to arm explosives as they are thrown (i.e. Grenades).

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#24561]
A standard and very important safety feature on thrown military ordinance (hand grenades) is one where the ordinance does not fully arm itself until thrown.

Currently grenade fuses are set to an extremely long duration to compensate for this (particularly for when the player is slowed for some reason such as pain), but the safety feature is prefferable.

A standard fragmentation grenade has a fuze of 4-5 seconds, i.e. one turn in game turns, but that would be extremely unsafe unless this feature were added.

As a result, grenades are quite difficult to use with any precision since the player must either "wait out" the fuze duration, or give enemies ample time to react to a thrown grenade (though currently almost no enemies do react).

Proposed function of feature:
'a'ctivating a grenade wields it and pulls the pin, which is dropped.
Throwing the grenade (or dropping it, or placing it in inventory, anything that removes it from being wielded) arms the grenade, which has a 4-5s timer.
If the grenade would land somewhere dangerous to the player, which is any time the player is not blind-throwing it, a menu prompts the player to drop prone.  In most circumstances the player will want to do so.
If the grenade is very close to the player, a menu may prompt the player to dive away from the grenade.

This depends on #29695 to add the prone state.

**Comment by Night-Pryanik** [comment]
I suppose we'll need to make player (automatically) wield grenades on arming them (somewhat related to what I proposed in #20312) so this will simulate player is holding the safety lever.

**Comment by FulcrumA** [comment]
Why not to simplify it autoarm grenades upon throwing, with that as an option that'd be toggleable? This way very straightforward grenade use for most situations will be possible (just throw the thing, it goes boom) but current, very situational option of cooking them first a bit will remain.

**Comment by Mecares** [comment]
There may be  situations where a grenade is just thrown without intent of using them as a explosive like tossing them on your pile of explosives while sorting stuff instead of walking over and dropping it. I would like the timed activation to stay and an prompt that asks me when I throw an unactivated grenade whether I want it to be set to explode on impact.

**Comment by John-Candlebury** [comment]
>There may be situations where a grenade is just thrown without intent of using them as a explosive like tossing them on your pile of explosives while sorting stuff instead of walking over and dropping it. 

The new loot sort systems will take care of this, no need to consider this behavior.

**Comment by plazma-rush** [comment]
Activate once to pull the pin, then either throw it or activate again to release the lever? This gives the option to both use a grenade as you would normally in real life, and also to have one go off in your hands on purpose.

**Comment by kevingranade** [comment]
The main reason I dont like throwing a grenade arming it is that its surprising and potentially lethal.

> Activate once to pull the pin, then either throw it or activate again to release the lever?

I like this option.
Another scenario where one might want to arm before throwing is one where arming is more involved, such as an adjustable fuse time, or selecting a timed fuse vs an impact fuse.  In this case it might take a significant fraction of a second to arm, so one might want to arm, do some other things, then throw the bomb.
