### ISSUE TITLE
Shady Basement house lacks downstair

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#24562]
Game version: 0.C-29759

Operating system: Windows 10

Tiles or curses:Tiles

### Expected behavior
Upon exiting the shady basement starting location from the High Tech Low Life scenario, you appear at a set of down stairs inside the house.

### Actual behavior
Refer to screenshot: https://i.imgur.com/DoyOmXN.png

Leaving the basement puts you outside the house, on the pavement east of the front door. There is no downstair anywhere in the house, including under furniture. Adding a stair to the house with the debug menu connects to the basement as expected.

### Steps to reproduce the behavior
I've restarted several times with the same setup and have been unable to reproduce it, though at least one other person on discord has reported having the same issue. It might require a specific house and basement combination that is quite uncommon? I'm posting the issue regardless in the hopes that someone recognizes the house in question from the screenshot.

**Comment by MT-Arnoldussen** [comment]
I can confirm this happening. Don't know if it was the same house though, as I do night starts and I just quit the game every time it happened.

**Comment by curstwist** [comment]
I've had this happen but it was before several autodoc updates.  I exited in the house but had no way back down.

**Comment by ManyNames** [comment]
Can confirm. I do a lot of High Tech, Low Life starts and it's actually a surprise when I take the up stair and have a down stair available. You are able to access the basements normally by mining, It's as if the 'basement' is not matching the 'house' above it. I've often stepped out of the basement into the yard, onto furniture, or even into a wall.
