### ISSUE TITLE
No random tiles for "furniture" and "connected pieces"

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#24564]
For some reason i cant give randomly generated tiles with "weight" parameter to furniture "f_" (in one mod shooting range targets are presented as furniture) and to any piece of connecting tile (for example i want center piece of connected group of tiles to be randomly generated).
If i try to do that it is just taking first tile from the list, or tile what have larger "weight" parameter.

**Comment by cosmiccoincidence** [comment]
So, you're trying place a furniture with other furnitures randomly placing around it?
@SomeDeadGuy

**Comment by SomeDeadGuy** [comment]
No, for example i am trying to place targets furniture on shooting range with "bullseye" and "person" variants. Just like i do zombies now. I have 16 variant for common zombie in my tileset what randomly assign to them then game starts. I can't do this with furniture.
Also, i want to take connected tiles (grass, for example) and give each piece (corner, center, end, unconnected) random tile, so grass will not look the same. I can't do that too.
With zombies i do this

        {
          "id": "mon_zombie",
          "fg": [
                        { "weight":2, "sprite":2666},
                        { "weight":2, "sprite":2667},
			{ "weight":2, "sprite":2668},            
			{ "weight":3, "sprite":11652},
                        { "weight":2, "sprite":11653},
			{ "weight":3, "sprite":11654},            
			{ "weight":2, "sprite":11655},
                        { "weight":3, "sprite":11656},
			{ "weight":3, "sprite":11657},
			{ "weight":3, "sprite":11658},
                        { "weight":3, "sprite":11659},
			{ "weight":2, "sprite":11660},            
			{ "weight":1, "sprite":11661},
                        { "weight":3, "sprite":11662},
			{ "weight":3, "sprite":11663},			
			{ "weight":3, "sprite":11664},            
			{ "weight":3, "sprite":11665},
                        { "weight":1, "sprite":11666},
			{ "weight":1, "sprite":11667}
            ],
          "bg": 967,
          "rotates": false
        },	
with connected piece of any tile or with furniture this do not work, but it should, i think.

**Comment by SomeDeadGuy** [comment]
I can have random tiles for monsters, items, terrain, fields, but not for furniture. And i can't have random tiles to anything if i will give it connection (center, corner, edge, tconnection, unconnected) in tileset config. Just looks like something what was overlooked during development, and left unfinished, and can be easily fixed by someone who know what to do.
If it will be fixed, then tiles in game, especially terrain tiles, can be made to look way more natural.
