### ISSUE TITLE
Game crashes when started without an audio device.

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#24575]
Game version: 0.C-29778-g4f22630

Operating system: Windows 10, 64 ibt

Tiles or curses: Tiles

Mods active: None besides default

### Expected behavior
Game doesn't crash when it is started with a soundpack loaded and all audio devices disabled in windows sound manager.

### Actual behavior
Game will crash

### Steps to reproduce the behavior
Load the game with a soundpack after disabling all audio devices in the windows sound manager.

**Comment by Rod995** [comment]
Confirmed.
