### ISSUE TITLE
Crash sites overhaul

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#24581]
As per discussion on the development channel (and not only), crash sites would use some improvement. Currently they're square space covered with metal scrap. To improve it a bit I've created several dummy heli vehicles that could be - after applying the same damage mechanics that affects wrecks in the city - dropped on crash site's center with additional debris, rather than uniformally covering the location, to loosely concentrate around it.

A few notes:
- The vehicles aren't functional - they're meant to suggest general shape of the craft that crashed, while offering a bit of variation in pieces to scavenge. 
- They're included as jsons in attached archive file.
- The size, armaments, etc are simplified to fit majority of locations well and not be too great of a source of materials.
- All of them lack engines. They're, again, dummy models
- They're in fact designated as type: "shopping_cart". This shouldn't have impact in-game.

Additional ideas worth consideration/discussion include:
- 1 to 2 corpses around/in the vehicle - perhaps whether they'd be military zombies or just dead humans in military gear and/or with military IDs could be randomized. It would allow non-guaranteed threats for non-guaranteed rewards
- black box as actual part of the vehicle, possibly with other new elements, like rotors - current vehicles, being props do not include any special new parts.
- Dividing the crashed vehicles into several parts, strewn around the area to suggest that the aircraft fell apart upon impact.

Edit: I've slightly updated and improved json designs, adding some detail and getting rid of any dependancies on other mods:
[WrecksV2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2268193/WrecksV2.zip)

![heli](https://user-images.githubusercontent.com/38487938/43542179-9e8bf11a-95cc-11e8-8b76-d8da4cbd941d.png)

**Comment by Night-Pryanik** [comment]
I like the idea. 
The other thing that could really help here and add an immersion is an ability to create wrecks at the designated point.

**Comment by mrkybe** [comment]
Code for dropping a vehicle at/near the center of a crash-site seems to work well.  I can replace it with IDs for the vehicles from the JSON.

**Comment by ralreegorganon** [comment]
I've run the extracted vehicles above through [this script](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/tools/vehicleDef.py) (with my changes in #24692)  to turn them into vehicle templates that can be used to spawn vehicles. 

Attached below (actually .json files but GitHub doesn't allow that extension):

[Helicopter wreck.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/2268280/Helicopter.wreck.txt)
[Interceptor wreck.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/2268281/Interceptor.wreck.txt)
[Osprey wreck.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/2268282/Osprey.wreck.txt)

**Comment by mrkybe** [comment]
@ralreegorganon Cool, those work perfectly.

**Comment by FulcrumA** [comment]
Saving first finished and adjusted prototype of vehicles - further improved and refined the original designs above, added loot pool of particular items as well as their chances. First pass at variation of them including corpses. Linted and ran through some validator, then linted again to be extra sure after my manual adjustments. Saving here just in case.

[aircraftproto.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/2279819/aircraftproto.txt)

**Comment by FulcrumA** [comment]
Barring potential rebalancing and errors, we're nearing final update. I've made overhaul of vehicles, they're bigger, come in several variations depending on damage. Need tiny bit adjustment upon implementation to fit with the system @mrkybe prepared.

Vehicles A have no corpses and are in the best shape. B are somewhat damaged and C suffer heavy damage. B and C have corpses, turned into pseudo-butchered state so they fit in the seats.
Interceptors should have the lowest chance of spawn (really, <10%) and if spawned should likely have 1 - 2 zombies.
Ospreys should be after that, can fit the most zombies though there should be RNG here allowing even safe, empty craft.
Regular helicopters may be the most common.

[wrecksV3.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/2284713/wrecksV3.txt)

![heli](https://user-images.githubusercontent.com/38487938/44057703-436ee75e-9f4c-11e8-8051-6132cc94edd0.png)
