### ISSUE TITLE
jenkins-latest OSX Tiles builds do not run

### ISSUE THREAD

**Issue by anseok** [CleverRaven/Cataclysm-DDA#24588]
Game version: Experimental builds 7622, 7630, 7631, 7637

Operating system: MacOS 10.13.5

Tiles or curses: Tiles

Mods active:

### Expected behavior
I expect the game to start.

### Actual behavior
The game does not start.
On Terminal, running:
/Applications/Cataclysm.app/Contents/MacOS/Cataclysm.sh
exits immediately with:
/Applications/Cataclysm.app/Contents/MacOS/Cataclysm.sh: line 22: 23169 Segmentation fault: 11  ./cataclysm-tiles

### Steps to reproduce the behavior
0. To ensure fresh install, open Terminal and run:
rm -r ~/Library/Application\ Support/Cataclysm
1. Download one of above builds from http://dev.narc.ro/cataclysm/jenkins-latest/OSX/Tiles/
2. Mount dmg and install onto /Applications
3. Run from the launch menu.
a. If the OS complains that Cataclysm is downloaded from untrusted source, go to System Preferences » Security & Privacy and allow the app to run. Repeat step 3.
4. To see the error output, open Terminal and run:
/Applications/Cataclysm.app/Contents/MacOS/Cataclysm.sh

### Notes
The last working tiles build I tried is 6656.  It runs properly under the same conditions.

**Comment by vircung** [comment]
So far experimental builds from [homebrew](https://brew.sh/) are working. You can install it via command `brew install cataclysm --with-tiles --HEAD`

**Comment by Leland** [comment]
Known issue, see #23171
