### ISSUE TITLE
Time to preserve food is taken into account when calculating spoil times.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#24580]
This applies to any meat and veggie products that are going to be dehydrated/salted but I will use jerky as an example for simplicity sake. Making meat jerky take 12 hours to prepare adding 12 hour to the calculation of when meat is supposed to rot. However, this is passed down unto the meat jerky itself making the jerky last less than it should despite the meat being used when it was fresh.

The proposed solution is simple: a recipe flag that sets the spoilage time for the output to the start of the last stage passed. Fresh, old, or rotten. This way the crafting is not dependent on the time but on the status of the meat/veggie wen "crafting". At the very least when you start "crafting" food for preservation, take only the time the meat/veggie has been exposed before crafting has begun. If the crafting fails or is can canceled, attempt's it again could use the new time since some time has passed and the ingredients aren't fresh.

**Comment by Robik81** [comment]
Yeah, happened to me in the past that I cooked rotten food from old food - you know, to use it before it is too late - that went rotten while processing. Annoying as hell.

**Comment by kevingranade** [comment]
Maybe linearly increase spoil time as the recipe progresses.  That should
make it never spoil during recipe execution but also not jump straight to
cooked instantly.
