### ISSUE TITLE
Open/Close All Curtains vehicle command does not also open/close Aisle Curtains

### ISSUE THREAD

**Issue by Avatharian** [CleverRaven/Cataclysm-DDA#24599]
O/S: Windows
Version: 0.C-29910-g3870791
Tiles

Open/Close All Curtains command on vehicle console only looks for the basic Curtain object that you install on windows. There are vehicle configuration where it is favorable to also have curtains on Quarterpanels to block line of sight (such as on vehicle corners next to windshields). However, Quarterpanels only allow installation of Aisle Curtains, which the command does not parse as a target.

https://github.com/CleverRaven/Cataclysm-DDA/blob/5226eca2f33979a0685aa10448fdb50451fff0b6/src/vehicle.cpp#L630-L638

**Comment by Avatharian** [comment]
Upon further testing, Aisle Curtains _are_ affected by the Open/Close all **Doors** command. If I am understanding the code correctly, it's because the door commands just open/close everything on the same tile as a Door Motor that doesn't have the CURTAIN flag, which interestingly Aisle Curtains do not.

**Comment by Avatharian** [comment]
For Clarification: basically, there exists no way to open _only_ Aisle Curtains, without also opening **all Doors**, and vice versa. Annoying when your vehicle has 5 doors. Aisle Curtains don't get listed in the menu with all the other curtains and doors and the only reason they are affected by the Open/Close all Doors command _at all_ is that the code works on _everything_ that lacks the `CURTAIN` flag. They're a missed case in the current logic, only caught by coincidence. Aisle Curtains should instead obey the same menu option that affects regular Curtains. This _could_ be done by adding the `CURTAIN` flag to the [vehicle_parts.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/d5a6bf24685046eea32dc1f571ecb8b76a0cb97c/data/json/vehicle_parts.json#L1160)


However I am not familiar enough with the code to know what other effects that might have. I am currently assuming that vehicle part installation location limits are governed by those flags, but I don't know that. I suppose I could just edit the .json and reload my game and see if I can't install the Aisle Curtain over quarterpanels anymore. Regular Curtains can only be installed over doors and windows. Another option could be to add a new flag to both the regular and Aisle curtain, `MOTORCURTAIN` or some such, and have the Vehicle Control menu logic point to that instead of `CURTAIN`

**Comment by mlangsdorf** [comment]
Adding CURTAIN to aisle curtains will prevent them from being installed on non-window tiles.
I think I'd move the CURTAIN flag to all curtains (and then put the standard description in vp_flags.json) and make it mean "this is a curtain". Then add the WINDOW_CURTAIN flag to window curtains with the meaning "most be mounted in a window."
If you don't feel up to coding this, I can try to get it fixed by Tuesday.
Thanks for the well investigated bug report.
