### ISSUE TITLE
Bionic monster skill point cost is too high

### ISSUE THREAD

**Issue by curstwist** [CleverRaven/Cataclysm-DDA#24608]
Game version: 7644

Operating system: Win10

Tiles or curses: Tiles

Mods active:   
  "dda",
  "BIGRIVER",
  "ENTERTAINMENTBUILD",
  "Experimental-Z-Level",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "SEEDYSPOT",
  "blazemod",
  "Tanks",
  "WHALEYCASSETTE",
  "bio_mod",
  "boats",
  "deoxymod",
  "filthy_morale",
  "hacktheplanet",
  "makeshift",
  "more_buildings",
  "more_locations",
  "mutant_npcs",
  "no_npc_food",
  "novitamins",
  "npc_traits",
  "a_mutated_arsenal",
  "No_Fungi",
  "StatsThroughSkills"

### Expected behavior
Using the High Tech, Low Life Scenario.
Bionic monster shouldn't cost 2 points for the pleasure of having the longest list of faulty bionics.  Cyber Junkie costs 0 points and Failed Cyborg earns 2 points.  I checked this on a vanilla world as well and the costs remain the same.

### Actual behavior
Bionic Monster could have 0 cost or perhaps earn 2-4 to keep it inline with other bionic challenge professions.
### Steps to reproduce the behavior
Begin character creation and choose High Tech, Low Life scenario to access professions list.  Compare the starts.

**Comment by MT-Arnoldussen** [comment]
Bionic Monster starts with 11 combined skill points, of which 3 are in dodging. It also starts with 6 functioning bionics. If anything, the profession should cost more than 2 points.

**Comment by Solusphere** [comment]
There was some discussion on this on the discord earlier, and one alternate option which gained a lot of approval is simply removing the leaky bionic from the class. The leaky bionic tanks the BC's hidden health stat over time, and is extremely difficult to counteract through simple healthy living. This means a BCs health regen will eventually fail to compensate for the constant damage accrued by the discharge bionics, requiring constant bandaging to stay alive, which is almost always unsustainable.

Removing the leaky bionic removes what is close to being a soft timer for the cyborg's lifetime. This makes non-lab broken cyborg starts a lot more viable, as it gives you the time you need to skill up, locate an autodoc and address your condition. It preserves the vast majority of the classes flavor, while still easily remaining the hardest profession to survive through to midgame with.
