### ISSUE TITLE
Bright light wakes you up from CBM instaliation and does not use up an anesthetic kit

### ISSUE THREAD

**Issue by Dziugaske** [CleverRaven/Cataclysm-DDA#24606]
Game version:

Operating system:
W10 64bit
Tiles or curses:
Tiles
Mods active:
Medieval and Historic Content
More Survival Tools
Vehicle Additions Pack
Tanks and Other Vehicles
Alternative Map Key
Boats
Folding Parts pack
Icecoon's Arsenal
Filthy Clothing
Makeshift Items Mod
More Buildings
Disable NPC needs
Extended Realistic Guns
### Expected behavior
The CBM operation proceeds normally and uses up an anesthetic kit.
### Actual behavior
The CBM installation takes only 3 minutes of in-game time and does not use up an anesthetic kit.
### Steps to reproduce the behavior
Turn on a flashlight in your inventory. Proceed to install a CBM.
![33](https://user-images.githubusercontent.com/42064096/43638981-5fc3a024-9723-11e8-890a-a592712ddf9c.PNG)

**Comment by Night-Pryanik** [comment]
Hmm, I was sure I handled that case.

**Comment by Night-Pryanik** [comment]
Oh, I think I got it. You have pain immunity trait?

**Comment by Dziugaske** [comment]
I do have Pain Resistant, yes.

**Comment by Dziugaske** [comment]
I also have the Sensory Dulling CBM if that matters, but it wasn't activated during the operation.
