### ISSUE TITLE
Hulb/brutes punching clothes into shreds

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#24610]
A ticket on the basis of discussion on Discord channel. Currently brute/hulk special attack works works as such:
![uhoh](https://user-images.githubusercontent.com/38487938/43649420-6bc0c0ae-973d-11e8-83be-9fc83e97b04a.png)

## # Expected behavior
While the damage i arguably fine and the effect of propelling player character even through different obstacles pretty nice, the attack shouldn't damage flexible clothing offering plenty of give. Denting armors is one thing, but clothes shredding from even pretty strong punch is a stretch.

**Comment by DracoGriffin** [comment]
I've mentally abstracted it as clothing getting caught on things (especially when punched into a vehicle or building) and tearing as you roll around/free yourself.

Whether this is intended or not, I'm not entirely sure. Just my spin on it.

**Comment by FulcrumA** [comment]
That would be certain explanation but sometimes even being punched into nothing particularly dangerous or even hard still has this effect. It's not a big thing either way but assuming it wouldn't be hard to fix is why I bring it.

**Comment by Rivet-the-Zombie** [comment]
I can see how getting punched through a wall could ruin your clothes - that's a lot of nails and splinters coming at you fast - but getting knocked into open space shouldn't really have that same effect.

**Comment by kevingranade** [comment]
Whether you hit a wall or not, you're hitting something, if nothing else
the ground.

Hitting and rolling across the ground at high speed would have a tendency
to destroy clothing in addition to causing damage to the player.

If you have a recommendation for how to moderate this effect, we can look
into it, but eliminating all clothing damage from this attack isn't a
reasonable option IMO.

**Comment by FulcrumA** [comment]
>If you have a recommendation for how to moderate this effect
Perhaps make the damage, including clothing damage, in big part dependant on the type of tile one lands on, with potentially moving the character further from the landing spot in direction of their flight if it's regular floor/road etc surrounded by similar tiles in said direction.

>Hitting and rolling across the ground at high speed would have a tendency to destroy clothing in addition to causing damage to the player.
 The problem is that _not_ always you're hitting someting, including ground and often you're stopped by some hard obstacle rather than rolling on some surface that would lead to shredding - shredding is as likely when you're punched through barbed wire fence as if you land on a bed. There's no real friction taken into account.

**Comment by kevingranade** [comment]
Never had a solid rationale.
