### ISSUE TITLE
Hot/cold consumables should affect the body temperature of your mouth, head and torso

### ISSUE THREAD

**Issue by RosaEscura** [CleverRaven/Cataclysm-DDA#24613]
It'd be cool and more realistic if hot/cold drinks/food would affect not only morale but also body temperature, meaning mouth, head and torso. I think the increase could be small like in real life. And if drinks could have a bigger effect due to their liquidy nature it'd be even better. So I'd request temperature change of 5 from drinks (+5 for hot drinks and -5 for cold) and respectively 3 from food. I suppose this temperature change should be temporary 5-15 in-game minutes lasting effect. And I think it's probably better if it doesn't stack since you can't regulate your body temperature a lot with consumables IRL either. Consuming two hot drinks in sequence would therefore cause the second drink to just reset the timer. When it comes to hot thing consumed first, then cold (or vice versa) it could remove the timer completely resetting the situation to zero basically.

**Comment by OrenAudeles** [comment]
A very short-term high-intensity mouth/head heating/cooling effect, with a longer-term low-intensity torso heating/cooling effect would probably work pretty well. Not sure if there would be much of a lasting gameplay effect from either but that's for testing to figure out.

**Comment by RosaEscura** [comment]
That's also an option! : > The longer term effect should be really low then I think. It could even decrease over time from the initial high-intensity heating effect, first rapidly and then the decrease slows down.

**Comment by CoroNaut** [comment]
As much as I love little changes like this, it needs to be thought out just a little more. Even though its a small change, there will be a large amount of code to change. With that aside, I agree that eating cold meat rather than hot meat would decrease your morale, but I also prefer cold water over hot water any day. The morale change would probably be different for lots of meals. 

The actual changing of the body temperature is a different story, such a small change for a very short period of time would give no significant change to game play. It would also require additional code to stick that heat/cold to the body part regardless of outside temperature which just wouldn't be right.

**Comment by dissociativity** [comment]
The inverse should happen more importantly for gameplay, my water shouldn't freeze if it's on my body and my body is warm for example.

**Comment by Dansiman** [comment]
> you rarely will consume anything hotter than your normal body temperature.

Pretty much any food intended to be served "hot" is going to be pretty "bleh" at body temp. Soup, for example, is best enjoyed at 140-170°F. <sub>([Source](https://cooking.stackexchange.com/a/46428/39093))</sub>

**Comment by SeelenJaegerTee** [comment]
I don't really see why cold food should decrease morale. It may not be as good like if it was hot but if it is "bleh" when being cold that's pretty good indicator that the ingredients were of low quality.
This morning I ate the cold left overs from yesterday: roasted minced meat with egg.
And it was delicious!
You totally can put cold meatballs or schnitzel between two slices of bread and eat it cold. Apply ketchup or mustard to taste for a great light meal between lunch and dinner.
Or the cold pizza from yesterday? Who doesn't like that?
Or meat jerky. I regularly produce my own and when it's fresh from the drying oven it's good but it should age for some days in the cellar or fridge before it becomes best. Now its cold and would this really taste better when warmed up? How would you even warm it up? Microwave? Frying pan? Rice steamer? I'm unconvinced.

>For starters you rarely will consume anything hotter than your normal body temperature. (Coffee's ideal temperature is 91-96°F while normal human body temperature is 97.7–99.5 °F)

The majority of tea I drink is hotter than my body temperature. And most of what I drink is Tea. 
For breakfast I drink about1 L hot tea. It is hot enough that it feels hot in the mouth but doesn't scald me.
I would certainly not enjoy coffee that's below body temperature.
I think you mixed up brewing temperature in °C with drinking temperature in °F. Espresso has an ideal brewing temp of 92-96 **°C**.
There's a [paper by Brown and Diller in Burns 2007](https://www.ncbi.nlm.nih.gov/pubmed/18226454) that states in its abstract:
> The preferred drinking temperature of coffee is specified in the literature as 140+/-15 degrees F (60+/-8.3 degrees C) for a population of 300 subjects.

The authors continue and say that 58°C (136 °F) would be best to reduce scalding risk and increasing customer satisfaction.
That seems about right considering 50°C (131°F) causes scalding after approximately 2 minutes and as soon as the liquid has contact with your body it starts to cool down.

**Comment by RosaEscura** [comment]
Why is everyone talking about the morale aspect when my issue is about consumables affecting body temperature? ._. Different temperature consumables already affect morale, if you don't want it to or there are some issues with it make a separate issue about it. This issue is about body temperature.
