### ISSUE TITLE
Pillows have no features! Please help make them have a reason to exist!

### ISSUE THREAD

**Issue by RosaEscura** [CleverRaven/Cataclysm-DDA#24614]
Pillows and Down-filled pillows could help you fall asleep and stay asleep longer (if still tired?). Would give pillows a meaning!

**Comment by Faalagorn** [comment]
There has been a topic discussing an original idea back in 2015: 
http://smf.cataclysmdda.com/index.php?topic=9826.0

Currently loose clothing and bedding has effects for both trying to sleep and warmth, but counter-intuitively pillows do nothing.

**Comment by FulcrumA** [comment]
>Currently loose clothing and bedding has effects for both trying to sleep and warmth, but counter-intuitively pillows do nothing.

I think it'd be pretty believable and even reasonable to have them help considerably with just the former

**Comment by Faalagorn** [comment]
Actually my bad, loose clothing (incl. blankets since you can wear them) only affects the warmth when you sleep. Chance to sleep is only affected by the tile you sleep at (which also increases warmth).

**Comment by CoroNaut** [comment]
Pillow fights with zombies? Count me in!

**Comment by Faalagorn** [comment]
>Pillow fights with zombies? Count me in!

That's already there, though mind that there's a lot of better items to use as weapon than pillows :)
