### ISSUE TITLE
Descriptions from #24277 are too long on a 1080p monitor

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#24621]
Game version: 0.C-29938-g90f5143

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: N/A

### Expected behavior
I should be able to read the entire description for every monster on a 1080p monitor
### Actual behavior
![image](https://user-images.githubusercontent.com/2125926/43671033-5892ba9a-9761-11e8-94f8-6e00147385ca.png)

I mentioned in the comments for #24277 that these descriptions were too long. I was ignored. I can now no longer read the entire description for this Kreck, rendering the PR worthless. Please alter the descriptions to something shorter.

**Comment by Inglonias** [comment]
Extended descriptions are a thing.

**Comment by DracoGriffin** [comment]
Author is referring to the `x` hotkey to look around, followed by the `e` hotkey which allows further examination of the tile and its content: creature, furniture, terrain.

![extendedtileinfo](https://user-images.githubusercontent.com/32253888/43671111-85a46e94-9751-11e8-8cd9-cebcfd434bc0.png)
