### ISSUE TITLE
Riot helmet visor mobility-suggestion

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#24638]
Considering riot helmets usually have option of raising visor(plastic shield) i thought said option should be added in game-its easy to code in ,just add second model of helmet with removed protection for mouth and eyes and maybe lower overall protection percentage if must and ability of one form  to transform in other.

One of problem of helmets such is motorcycle one,riot helmet,full tactical helm is that they inhibit both breathng and perception  and also have low enviromentnl protection which is objectively ok but make them inferior to those which only protect head as you can by your need use masks and googles-and usually player want good gas or filter mask to protect them from enviromental hazards and as lowest eye encumbrance as they can get.Giving this ability to riot helm and possibly motorcycle helmet (though i think one described in game are not one which can do it) or medieval helmet  woud make them more desirable and is also real.

json example

 "id": "helmet_riot",
    "type": "ARMOR",
    "category": "armor",
    "name": "riot helmet",
    "description": "A helmet with a plastic shield that covers your entire face.",
     "use_action": {  "type": "transform", "target": "helmet_riot_raised", "msg": "You raise your visor." },
    "weight": 2260,
    "volume": 9,
    "price": 22000,
    "to_hit": -1,
    "bashing": 8,
    "material": [ "plastic", "steel" ],
    "symbol": "[",
    "color": "dark_gray",
    "covers": [ "HEAD", "EYES", "MOUTH" ],
    "coverage": 95,
    "encumbrance": 20,
    "warmth": 10,
    "material_thickness": 3,
    "environmental_protection": 2,
    "techniques": [ "WBLOCK_1" ],
    "flags": [ "WATERPROOF", "STURDY" ]
  },
  {
        "id": "helmet_riot_raised",
    "type": "ARMOR",
    "category": "armor",
    "name": "riot helmet(raised visor)",
    "description": "A riot helmet with a plastic shield which is raised up.",
    "use_action": {  "type": "transform", "target": "helmet_riot", "msg": "You put down your visor." },
    "weight": 2260,
    "volume": 9,
    "price": 22000,
    "to_hit": -1,
    "bashing": 8,
    "material": [ "plastic", "steel" ],
    "symbol": "[",
    "color": "dark_gray",
    "covers": [ "HEAD"],
    "coverage": 95,
    "encumbrance": 20,
    "warmth": 10,
    "material_thickness": 3,
    "environmental_protection": 2,
    "techniques": [ "WBLOCK_1" ],
    "flags": [ "WATERPROOF", "STURDY" ]
  },
{

**Comment by Rivet-the-Zombie** [comment]
This would be a good case for using the copy_from function.

**Comment by Broken-Admin** [comment]
Maybe we could add a activate function and a separate item that doesn't cover the eyes and mouth.
@baraba3 if you have made a PR, please mention it, otherwise I may try to create PR to do such change.

**Comment by baraba3** [comment]
i did such myslef when testing in fact i have thsoe "two" items in first
post.I tried than using copy from function other posters mentioned  but
didnt succceded and lost interest as i had trouble with uploading and
making pr.You have my support to finish job yourself.

уто, 2. окт 2018. у 16:43 Aleksander <notifications@github.com> је
написао/ла:

**Comment by Theundyingcode** [comment]
> This would be a good case for using the copy-from function.

adding a use function turns it into tool armor which doesn't support copy-from currently.
