### ISSUE TITLE
Rename "survivor" guns to better reflect their low quality

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#24637]
The survivor guns are inferior to existing guns.  I understand why they are that way and agree with the reasons why.  (They are handmade with crude tools and high tolerances and as a result are not as good as a factory produced firearm) And I definitely don't want to make any changes to survivor armor.  And I CERTAINLY don't want to add "good" survivor guns. This isn't about that at all.

I saw a good discussion on [reddit](Https://www.reddit.com/r/cataclysmdda/comments/94f0f2/what_role_does_survivor_gear_play/) that got me thinking.

The survivor armor is great and something you should work for.  It's custom made to defend against the Post cataclysm world.  I think that players might get confused.  They see the "survivor armor" and see that it's good.  They see a "survivor carbine" and think that it would be great also. (without looking at the stats) make one and then realize that it sucks compared to a factory made carbine.

I'm just want to know if a PR changing them to another name would be welcome.  And if so, what should the new name be?  Crude? Improvised? Cobbled? Forged?

**Comment by DracoGriffin** [comment]
Makeshift may give the wrong impression as other makeshift items (and basically swings the pendulum to the opposite).

Perhaps handmade or handcrafted (`make skillfully by hand.` since the survivor firearms are supposedly some of the best you can make by hand).

**Comment by WizardOfOoo** [comment]
@DracoGriffin how about crude?

**Comment by Inglonias** [comment]
I would call it "Homebrew" or "Homemade" if you want to better clarify things.

**Comment by WizardOfOoo** [comment]
So far I have:

homemade six shooter
homemade double-barrel flintlock
homemade special 700
homemade carbine
homemade rocket launcher

I have to be missing something. Is that all there is?

**Comment by WizardOfOoo** [comment]
Also lever shotgun

**Comment by FulcrumA** [comment]
I think it's not that much of an issue - anyone who just crafts an item without looking at conveniently provided stats and description available in the very window they choose the item to craft is kinda guilty. At the same time, I do agree that it can be easily corrected as well as I agree that it shouldn't merely be 'makeshift' as some survivor wepaons are pretty decent, jut not factory produced. I wouldn't mind underlining that - 'homemade' is good, though I think 'handcrafted' would be better - it may imply all kinds of qualities of the product.

**Comment by DracoGriffin** [comment]
>@DracoGriffin how about crude?

I'd go with handmade for the early survivor guns, and handcrafted for the later more advanced versions. It should then convey more of the ... well, made by hand aspect, as well as the increasingly skilled and better crafted components.

**Comment by WizardOfOoo** [comment]
My problem with handcrafted is that in the real world a "handcrafted" gun would be far superior to a mass-produced one.  But I can go with that.

Which guns are good enough to get that label?

**Comment by DracoGriffin** [comment]
>Which guns are good enough to get that label?

Whatever you think logically fits/works.
