### ISSUE TITLE
JSONize Furniture/Terrain Sleep Comfort and Bedding Warmth Values

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#24636]
@ZhilkinSerg mentioned the need to JSONize these values in #24623.

Increase moddability and more accessible for changes.

Some recent examples: [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/24421) [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/24428) [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/24527) and [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/24570).

**Comment by Night-Pryanik** [comment]
@Coolthulhu described the problem in https://github.com/CleverRaven/Cataclysm-DDA/issues/19653#issuecomment-267739554.

**Comment by Night-Pryanik** [comment]
Closed by #27202.
