### ISSUE TITLE
Severe Temperature Destroys Bandages and Disinfectants

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#24652]
### Expected behavior
Severe temperature shouldn't damage bandages/disinfectants, but should halt the healing process (probably no effect on disinfectant, that might just continue as normal).

### Actual behavior
Severe temperatures destroy bandages and "infect" disinfectants.

![superfreezingdamage](https://user-images.githubusercontent.com/32253888/43696365-e57e3f48-98fa-11e8-8bc6-083e839d17f6.png)
![superhotdamage](https://user-images.githubusercontent.com/32253888/43696366-e58cb6fe-98fa-11e8-97ff-65d3c1406553.png)

**Comment by Rivet-the-Zombie** [comment]
That is weird.

**Comment by Vasyan2006** [comment]
If temperature can damage health skin, why if should be safe for treated wounds?

**Comment by nexusmrsep** [comment]
To put it in other words: External damage might destroy bandages directly (force applied to bandage itself), while internal (temperature) damage might destroy them indirectly via wound excretions. I imagine it like real life bandages that need to be changed frequently when soaked with blood, pus or enything else that can come out of the would. So I imagine that extra damage from temperature does exactly that by irritating existing wounds, making them bleed and soaking the bandage, eventualy rendering it useless. So perhaps it would be better to alter the reason why bandage got destroyed/unusable/spent by changing output texts for internal damage, while keeping the mechanic for such cases?

**Comment by tinukedaya** [comment]
If the bandage gets damaged, all other clothes should as well... which makes no sense. If you want to simulate some of the things @nexusmrsep is talking about, they maybe just wear off the bandage effect faster, healing less damage.

**Comment by nexusmrsep** [comment]
> A patient does not suddenly require dressing changes due to body temperature changes.

Not the temperature change itself, but the resulting damage afterwards, if there is any. First, second, third degree [burns](https://en.wikipedia.org/wiki/Burn), blisters leaking fluid on bandages. And I'm rather saying "standing near the lava" hotness rather then "I'll wear two sweaters in the African jungle". But you might be right about no need of simulating this in any way. It might be just my sentiment to NEO Scavenger bandages getting dirty/bloodied with time and requiring change.

**Comment by kevingranade** [comment]
I think we can come up with some kind of rationale for this happening, but IMO this is an unexpected outcome and it serves no purpose, so I consider it a bug.
