### ISSUE TITLE
Some Life Cycle Animals Give Incorrect Harvest Amount

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#24650]
### Expected behavior
Larval / baby versions of animals should yield appropriate amount of items when harvested.

### Actual behavior
Larval / baby versions of animals yield the same amount of items as adults when harvested.

&nbsp;

Cursory review shows that mammal.json shows "copy-from" utilized on baby versions, but did not specify a new "harvest" type, so reverts to using "animal_large" inappropriately.

**Comment by KorGgenT** [comment]
fixed by #26922
