### ISSUE TITLE
Lab Rock Floor

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#24654]
Should labs have different, more hightec, cool looking floor?
Cause now it using same floor as in caves or mines, and i do not think this is right. 
Sorry if it is not an issue. I just found that to be weird looking, then i changed rock floor tiles in my tileset to look more like a rock in a cave with cracks and dirt, and not black and clean as fresh asphalt.
So now my caves and mines look awesome, but labs look like caves. :\

**Comment by BrianLefler** [comment]
What tilesets do you want this to affect?  Would not be hard to change to concrete floors (t_thconc_floor) but they currently look the same in Chesthole.

**Comment by cosmiccoincidence** [comment]
My PR changes rock floor to concrete floor.

**Comment by SomeDeadGuy** [comment]
BrianLefler i am using my own tileset.
It is on my page.

**Comment by BrianLefler** [comment]
Remaining rock floor should be fixed by #24727
