### ISSUE TITLE
Hallucination believability adjustment

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#24659]
Stemming from the discussion happening currently on discord regarding issues with schizophrenia and its hallucinations, a few suggestions:

- it's still too easy to differentiate between actual creatures and hallucinations. Hallucinations are visible through walls and often include pretty regular creatures clearly not fitting the locale. Perhaps the game could concentrate on spawning hallucinations of creatures believably - even if not necessarily from actual technical standpoint - fitting in the place they appear at? Random eldritch abomination isn't bad from time to time, but it's actual skitterbots coming into view when one's exploring a laboratory that really make one question the reality.

- most hallucinated health issues and conditions are obvious and easily discarded. Still, despite recent overhaul, hallucinated broken limbs, injuries etc are not reflected on the GUI. Perhaps temporary - 20, 30 turns-long - seeming change there could be allowed?

- hallucination should extend not merely to creatures but also items, beside obvious things like inanimate objects talking to the character. Swapping temporarily descriptions of items in the inventory of similar type could work as would randomized prompts when the items are interacted with - fresh edible appearing rotten in the message confirming player eating it, prompt informing the player that the vehicle tank was refilled with fruit juice etc

**Comment by kevingranade** [comment]
Please limit issues to one feature, these three suggestions would be implemented independently of each other, or some may be accepted and others rejected.
