### ISSUE TITLE
Add ages and aging for characters and NPC, both animal and human

### ISSUE THREAD

**Issue by RafeHaab** [CleverRaven/Cataclysm-DDA#24666]
Game version: irrelevant, this is not a bug

Operating system: doesn't matter much for this suggestion

Tiles or curses: both

Mods active: vanilla game

### Expected behavior

Animal and human NPCs have actual, numeric ages, as well as the player character. You can start the game as a 15 years old (justyfing the ammount of free points you get at character creation, which is exactly 15), and get one extra point to assign as you wish each passing year, which would help people who don't want to use "stats thrugh skills" in their games, and also reward players for surviving longer.

Could allow for easier implementing of trees sprouting, growing and dying from various reasons once the forestry project is finished.

### Actual behavior

Ageless, immortal living beings

### Steps to reproduce the behavior

Start a game, play it forevermore. Nothing in your game will die naturally.

**Comment by MT-Arnoldussen** [comment]
I don't see the point of this. How many people are gonna play characters for the decades it would take them to die?

Besides, most if not all age-related effects are already handled in traits, so it wouldn't make much sense to handle age separately from that.

As for your "stats through aging" idea, most professions would presumably start at their prime or past it, so them getting older would just make them weaker/slower/etc.

**Comment by Lorith** [comment]
I'd rather not have my character instantly die when I update.

**Comment by RafeHaab** [comment]
"As for your "stats through aging" idea, most professions would presumably start at their prime or past it, so them getting older would just make them weaker/slower/etc."

That's why you spend points on said professions, leaving you with less point to assign elsewhere.

**Comment by FulcrumA** [comment]
I am not fond of this suggestion. While growth of the trees and whatnot could be implemented, age of characters sould be largely abstract - people usually want to play imagining particular character and how they are no matter how long they play for. In case of majority such feature will be pointless as they simply won't live for long enough. In case of others, to force them to observe their characters and their companion get old and possibly even die of old age will only detract from enjoyment. 

The alternative of characters just turning progressively more powerful with time also doesn't appeal to me. I'd rather have something like Stats Through Skills counterpart in vanilla.

**Comment by DracoGriffin** [comment]
#23833 answers this on a basic level (animals do age from "birth" to "adult"), just more animals need to be added and fixed.

**Comment by kevingranade** [comment]
If we add something as major as aging to the game, it needs to be a lot
more nuanced than adjusting chargen points.

The status quo is that games dont last long enough for in-game aging to
matter, and that if you have some idea of different ages leading to a
different starting condition for your character, you can handle that with
points adjustments and traits.

**Comment by RafeHaab** [comment]
kevingranade, that's not what Lorith implied with her message. She said she has made it for so long that her character would instantly die if this was implemented.
