### ISSUE TITLE
Removing a battery from a item inside a car drops the battery in the ground instead of the cargo space

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#24673]
Game version: 

### Steps to reproduce the behavior
Add Battery Compartment Mod to a Welder
Add a Car Battery to the Welder
Walk to an empty Cargo Space tile inside your Car
Unload the Welder

### Expected behavior
I'd expect the removed car battery to be dropped inside the cargo space, since I'm inside the car.

### Actual behavior
The car battery is dropped in the ground, outside the car.

**Comment by Night-Pryanik** [comment]
Are you sure cargo space wasn't filled to the brim, so battery HAD to drop on the ground?

**Comment by KurzedMetal** [comment]
Happens even on empty Cargo Spaces.
