### ISSUE TITLE
Stacked cash cards do not show correct $ in Adv. Inventory

### ISSUE THREAD

**Issue by Robik81** [CleverRaven/Cataclysm-DDA#24678]
Game version:
7657
Operating system:
Win 7 x64
Tiles or curses:
Tiles
Mods active:
few usual ones

### Expected behavior
stacked cards should show correct money total in Adv. Inventory

### Actual behavior
shows amount of first card on the stack

### Steps to reproduce the behavior
- start a new game
- spam few cards
- put them in one AI pane one by one

![image](https://user-images.githubusercontent.com/6969268/43778976-6c5d9ede-9a57-11e8-87a6-33da857d798b.png)

![image](https://user-images.githubusercontent.com/6969268/43779009-891345ce-9a57-11e8-9313-73a004011174.png)

![image](https://user-images.githubusercontent.com/6969268/43779031-95a146f6-9a57-11e8-914d-d30ea22931e3.png)

**Comment by Robik81** [comment]
The only affected pane is Inventory, other squares seems to be working fine.

**Comment by nornagon** [comment]
This still seems to be the case as of 3efcc3e.

![image](https://user-images.githubusercontent.com/172800/57963756-422f9c00-78de-11e9-9775-a63655510bde.png)
![image](https://user-images.githubusercontent.com/172800/57963761-570c2f80-78de-11e9-9dd8-711b7a976d6b.png)

**Comment by OzoneH3** [comment]
Works in recent build.

![](https://user-images.githubusercontent.com/3514404/66907909-741e6900-f00a-11e9-8eda-6d153b5f4d8a.png)

![](https://user-images.githubusercontent.com/3514404/66907910-754f9600-f00a-11e9-8cf1-699674a2d684.png)
