### ISSUE TITLE
(Bicycle shop's) vehicle placement may damage the building

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#24675]
Game version: O.C-30062

Operating system: Windows 7 

Tiles or curses: Tiles

Mods active: More Survival Tools, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Vehicles in locations like bicycle shop are positioned in a reasonable way that wouldn't be out of place IRL.

### Actual behavior
Vehicles have a chance to channel the Kool-Aid Man:

![uhoh](https://user-images.githubusercontent.com/38487938/43768374-82556c82-9a37-11e8-8b92-871fa5c92745.png)

**Comment by cosmiccoincidence** [comment]
My PR moves this specific bike spawn over (closer to the center of the room) so it no longer spawns in the wall.

**Comment by Shodan14** [comment]
I have also seen an ATV spawn through a mechanics garage door a few builds ago, didn't capture it though.
