### ISSUE TITLE
Activation and Reload of specific items without picking them up

### ISSUE THREAD

**Issue by Robik81** [CleverRaven/Cataclysm-DDA#24686]
I'd like to implement the feature, that would allow activation / reloading of some items from adjacent tiles without picking them up.

![image](https://user-images.githubusercontent.com/6969268/43798620-6c8f1c8c-9a8b-11e8-93f6-ba8a86817941.png)

Like the lantern at the table SE of me.

I am thinking about adding a specific FLAG to lanterns, forges, smokers, kilns and similar items, which would mark such items as activable / reloadable without picking them up.

Is this something people would like to have?

**Comment by DracoGriffin** [comment]
I believe this is something consistently asked for within the community.

Keep in mind, @vschule is doing something similar in #24058.

**Comment by vschule** [comment]
I should probably close that Pull Request for now. I might restart working on it in 2-3 months but right now I can't really commit to it.

**Comment by DracoGriffin** [comment]
Sorry to hear that, @vschule . Hope to have you back soon.

@Robik81 looks like you're in the clear if you'd like to pursue this feature.

**Comment by 0be1isk** [comment]
Lol I was looking into this. I get the sense you've been scavenging suggestions (particularly you might have seen one of mine stating to do this). Shit if you can beat me to it, go for it.

**Comment by Robik81** [comment]
Quite possible, I read plenty of suggestions... I mean, I read the forum, right? But just reading the suggestion is not usually enough for me to start coding, it must be something I'd like to have in the game myself.

Given that I play with my own inventory system, I tend to have smaller inventory than is normal, so picking every tool I just want to turn on / reload gets pretty annoying.

I just read the "The item is too big to pick it up." one too many time. No, I don't want to pick it up, I just want to lit it up, you stupid game! ;-)

**Comment by 0be1isk** [comment]
> I just read the "The item is too big to pick it up." one too many time. No, I don't want to pick it up, I just want to lit it up, you stupid game! ;-)

This. Right. Here. 
The annoyance of having to pick up the lantern, turn it on, drop it, do whatever you wanted to do, pick up the lantern again, turn it off (so not to waste charges) , drop it. and repeat EVER.SINGLE.TIME. was getting absurd.
