### ISSUE TITLE
Creature hallucinations too easy to recognize as such

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#24688]
Divided #24659 as per @kevingranade recommendation:

It's still too easy to differentiate between actual creatures and hallucinations. Hallucinations are visible through walls and often include pretty regular creatures clearly not fitting the locale. Perhaps the game could concentrate on spawning hallucinations of creatures believably - even if not necessarily from actual technical standpoint - fitting in the place they appear at? Random eldritch abomination isn't bad from time to time, but it's actual skitterbots coming into view when one's exploring a laboratory that really make one question the reality.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
