### ISSUE TITLE
0.C-30083 - Explosives damaging vehicles at impossible ranges

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#24683]
Game version: 0.C-30083

Operating system:Windows 10

Tiles or curses: Tiles

### Expected behavior
Landmines do not damage a shopping cart over 40 tiles away.

### Actual behavior
A zombie stepping on a landmine over 40 tiles away will, nearly 100% of the time, cause significant damage to a shopping cart.
![mines](https://user-images.githubusercontent.com/19789267/43790586-972defd0-9aa5-11e8-8feb-f1948e5916c2.png)
^In this picture, a zombie stepped on a mine in the far southeast, near the cluster of zombies (most of which, curiously, survived). My cart's basket went from green to red.
![mines2](https://user-images.githubusercontent.com/19789267/43790749-19fa7adc-9aa6-11e8-951f-68d34ddab044.png)
^In this picture, the bile puddle is where a boomer stepped on one. My cart's basket and wheels both broke.

### Steps to reproduce the behavior
Drag a cart behind you with a minefield and some zombies at the edge of your vision. I'm attaching a save file which is perfect for reproducing the issue.
[Sunbright.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2267336/Sunbright.zip)

**Comment by Robik81** [comment]
Haha, yea.

Some stupid deer stepped on the mine south of my Evac shelter at similar distance, both windows on the south side got shredded to pieces.

**Comment by kevingranade** [comment]
Thanks for the clear reproduction case, I agree that sounds wrong.

**Comment by Rivet-the-Zombie** [comment]
A big explosion should totally be blowing out windows at long ranges - much further than any actual shrapnel travels - due to the force of the shockwave. They shouldn't be shredding cars and stuff at those ranges though.

**Comment by NetSysFire** [comment]
Loaded the save, which still sort-of works but with a lot of errors and the shopping cart was battered and stayed battered during the explosions.

I also tested in a debug world and was at most 20 tiles away from the exploding mine while pushing my shopping cart around. I can not reproduce this anymore, the shopping cart stayed like new.
