### ISSUE TITLE
All volumes are getting +0,01 added to them

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#24703]
Game version: 0.C-30088-g96d52b1f64-dirty

Operating system: Arch Linux

Tiles or curses: Both

Mods active: Dark Days Ahead, Filthy Clothing, Disable NPC Needs, Simplified Nutrition

### Expected behavior
Volumes should match what is in game files.

### Actual behavior
Each volume presented in game is being artificially added +0,01 unit to them, be it liters, quarts or cups.

### Steps to reproduce the behavior
1. Start a new game.
2. Observe item volumes (especially totals when moving items around).

It seems that all the volumes of item – be it a single item, total volume available/carried in inventory or even volume available on the tiles is getting +0,01 unit added. See the screenshot below to hopefully know what I mean. I had this issue for a few builds already and just got used to it. I didn't test if it's there in 0.C version, only playing experimental.

![screenshot from 2018-08-08 12-55-55](https://user-images.githubusercontent.com/4951331/43833324-a80dd60c-9b0a-11e8-805e-c16913340fc1.png)

**Comment by FulcrumA** [comment]
There seems to be a bit of floating there. Same with repairs on the items usually resulting in '++' for fully repaired but not reinforced, rather than default '||'.

**Comment by Faalagorn** [comment]
I was trying if launching the game as `LC_ALL=en_US.UTF-8 cataclysm-tiles` fixes it, in case my locales are messing something, but it seems not. It only changed decimal spots from `,` to `.` but the 0,01 (or 0.01) error was still there for me.

**Comment by woutershep** [comment]
I have the same problem. Thinking back I think it started to occur around the time when i switched to gcc 8. I've just recompiled now with gcc 7 and it is gone. So i think it will only be reproducible with gcc 8.
The gcc versions i used are 7.3.0 and 8.1.0.

Could you confirm this @Faalagorn ?

**Comment by Faalagorn** [comment]
@woutershep Yup, I'm on GCC 8 for a while and I just started the game recently so I experienced this problem all the time, so that's probably it. I didn't ever think this could be the case, nice find!

**Comment by Qrox** [comment]
I can confirm this after switching to MinGW-w64, so I suspect this is caused by the same issue as #19592, see my last comment there:

> in json.cpp, the method JsonIn::get_float() uses i * std::pow(10.0f, e + mod_e) for float deserialization. This of course, depends heavily on the actual implementation of std::pow()

In #19592 item damage values saved as `-1.00000` become something between -1 and 0 after reloading, which is very similar to the situation described here.
