### ISSUE TITLE
New flag for armor allowing to wear them without layering penalty

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#24704]
As discussed in #24677 It would be nice to have ability to assign `covers` region for jewellery/decoration items such as badges, but allow to wear them without inuring layering encumbrance penalty.

The reason for that is that you should be able to wear a badge or a decorative items on a particular body parts, but not incur a penalty for wearing them along with another item on the same layer (alternatively add a new layer for decoration, but still wearing two badges shouldn't incur a penalty). Currently you can wear badges/decoration but they don't have any cover area designated, so wearing them correctly doesn't add any encumbrance no matter how many of them you wear (with the hard limit of 2 items as with other armor). However, due to no region the item belongs to I think coverage value is not applied (since they don't belong in any part then your badge can't stop a hit or a bullet) and probably other flags might have issues too (like `WATER_FRIENDLY`).

[ear_plugs](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/armor.json#L2403) is one of such items that have coverage and flags, but don't cover any part of the body.

**Comment by Solusphere** [comment]
Bras are another item that probably shouldn't have a penalty, seeing as for those that need them wearing one is less "encumbering" than not wearing one. It would also mean that you can, say, wear a bra and a tank top simultaneously without penalties, which isn't currently possible.

**Comment by Faalagorn** [comment]
On the other hand, since there's restrictions you can wear bra as male or remove it as female, so it's up to you to wear them or not. You actually get a slight bonus of playing some female survivors since you get an extra item. But I agree, it should definitely be possible to wear a bra and a tank top without suffering penalties by doing so.

**Comment by Endovior** [comment]
Interesting, but potentially problematic. On the one hand, it makes plenty of sense that you should be able to wear, say, panties and leg warmers at the same time without penalty (the two literally don't overlap). On the other hand, if certain items become immune to the layering penalty while still offering protection, there'd be every reason to wear as much of that as possible, to maximize what minimal protection the extra layers offer. And wearing seven different pairs of underwear, or a ring on each finger, _would_ be somewhat encumbering!

The flag in question, then, shouldn't mean that there are some items that can offer protection with no encumbrance risk, but that the first extra item with that flag in that position can be worn without additional penalty. This would allow assorted underwear or jewellery items to be work together, and offer protection, without much issue (or need to do any silly case-by-case analysis of exactly what items can conveniently be worn together ), while also preventing survivors from piling on huge stacks of extra clothing in a silly way.

**Comment by Faalagorn** [comment]
You can still only wear two items at once though. Originally I just wanted to keep it for the decoration items and add 1% coverage for most of them (if it's sensible), similar how I gave 2% to badges in #24677 so it'd be negligible (you decide if 1% is even worth the tiny increase in weight or is it better to scrap/sell the item for something more useful), so I *guess* it wouldn't have much effect on gameplay, but still could provide the "OMG my holy cross literally saved my life" if it triggers ;).

But true, It'd have to be balanced not to be abused, as there's no limits to items worn (unless someone decide to add a hard limit of 20 items per layer or something like that).

**Comment by Endovior** [comment]
Sure, there's a hard limit of two items of the exact same type... but if all the types of underwear you could wear had no encumbrance and could be layered freely provided you don't double up, why wouldn't you wear a bikini bottom and boxer briefs and boxer shorts and boy shorts and briefs and compression shorts and a loincloth and a fur loincloth and a leather loincloth and a wool loincloth and panties, all at once, all the time, given availability of fabric, thread, and tailoring skill?

That's my entire point, and it can be applied to items in any particular slot and layer, even a hypothetical decoration layer. Just because any given decorative item shouldn't be all that inconvenient on its own doesn't mean that all survivors must bling themselves out as heavily as possible with all the jewelry and decorations they can possibly manage to find. Because making each one offer a tiny incremental defensive bonus with no penalty means that's exactly what happens.

**Comment by Faalagorn** [comment]
That's why I think it should be reserved to decorative items and then *maybe* the bras since we have tank tops and undershirts (then normal shirt, jacket etc.). On the other hand there's also underwear and thighs etc. so maybe it'd be best not to touch underwear at all, for balance reasons. After all the layering penalty is minor for those anyway and normally you'd suppose to wear only one of them (though It'd probably could be reduced to 1 for fitting items, but that's another issue).

I wouldn't have a problem someone wearing 10 badges (we have 5 types), 2 radiation badges and then two of each of the jewelries that give 1%-2% coverage each only. Depending on view, you could actually may not want to wear them all the time at the outer section, as they could theoretically be damaged.

You can wear them like that now (and those with stylish trait probably do), but they can't be damaged as they cover no section. They also have phantom defense values, as If I understand correctly without `covers` they can't utilize those values which kinda makes no sense (you *wear* them after all). 1% is the minimum that can be set, but I think it's already balanced, as even if you could stack 100 of them, it'd stil be worse than one 100% coverage item and at that point the whatever small weight they have adds up anyway, plus they usually have crappy protection values and would cover just one body part. And the weight adds up.

Alternatively, I'm open for some other suggestions, but I think it shouldn't be that much problematic if utilized correctly. We can not touch them (which at the moment stays like that), but I'd really want to see them covering body parts and I'm reluctant to add them now for reasons stated in #24677 before encumbrance skyrockets the same way as stacking jackets!

**Comment by kevingranade** [comment]
Powergaming by wearing 0 encumbrance items with minor bonus are not ok.
Either it has no encumbrance and no coverage, or it has at least some
encumbrance to go with the coverage.  That's a totally fine tradeoff.

Likewise with the very thin clothing, the balance point us that they have
incredibly minimal encumbrance, but not none.  AFAIK you will not get any
penalties from wearing a bra and a tank top, it's only if combined with
other clothing that it will happen.  Please correct me if I'm wrong.

**Comment by Solusphere** [comment]
The penalty is very minor, but it is present:
![penalty2](https://user-images.githubusercontent.com/19789267/43939406-7c17107a-9c9c-11e8-8d97-fe7281301e83.png)
![penalty](https://user-images.githubusercontent.com/19789267/43939411-7fdbb59e-9c9c-11e8-9a47-2547d1380069.png)

**Comment by cainiaowu** [comment]
IIRC the penalty is round down to the nearest 10, so 2 is not that big deal at all.

**Comment by Faalagorn** [comment]
You do get penalty for each point for some stats. Sometimes I'd wish that at least a 1 penalty could be handy though, similar how it's no difference in some clothes whether you wear them fitted or unfitted.
