### ISSUE TITLE
Error on WorldLoad

### ISSUE THREAD

**Issue by xrandomuserx** [CleverRaven/Cataclysm-DDA#24723]
Game version: 0.C 30088 g96d52b1 aka #7658

Operating system: Windows 10

Tiles or curses: Tiles

ERROR on WORLD LOAD (see attached)
Harvest list megabear_head has invalid drop(s): megabear_skull_unclean

![error megabear](https://user-images.githubusercontent.com/41707707/43862806-e04c0c42-9bae-11e8-89a9-836ca492f96f.jpg)

**Comment by ZhilkinSerg** [comment]
That item is probably from some mod  - PKs, Arcana or Ascension.

**Comment by ZhilkinSerg** [comment]
I guess you need to update PKs from its repo. You have probably updated game, but didn't update the mod.

**Comment by xrandomuserx** [comment]
Thanks everyone, I tried disabling various mods to make this go away, but because I pressed ignore I think it went away....

maybe soft_errors such as this could send a report to someone? these kind of things happen lots....
:)

**Comment by ZhilkinSerg** [comment]
It has nothing to do with core data, so I guess you should contact affected mod author.

**Comment by Var446** [comment]
Had this pop up with only Dark days, and Alternate map keys...still testing my mod list, so take it for what you will
