### ISSUE TITLE
Is the game winnable. or is it impossible to win unless you play that way

### ISSUE THREAD

**Issue by tsaber** [CleverRaven/Cataclysm-DDA#24731]
Is the game beatable by at least all of the classes.(what this dude stoohped?) is it balanced.  or is the intended balance just no balance but more like keep you down when you dont know. so nobody can reach this level ever again as long as I have a way to call it beed belence. When they get close. its meh gehm. I am best. If the endpoint for balance is just fucking newbies over or making it unabundandedly clear how easy they make it  I'd like to know. the game could adjust based on characterhealth just by 1 percentiel. so at least once something good happens that isnt over within the next 5 minutes coincidentally with another grab you just couldnt get out of because you dont play the one way of brurt fers and dedleh steks.
and not just bombos based on my skill to do things it would be my sane decision to better not play. or if i had to preconfigure carefully not to step in a monstermouth you cant move and are forever deth

or if those thigns that make it more like "fuck you you die i hate world" would have their authors properly documented. that seems like it's not subconscious but pretty conscious. and that's scary at first but then also seems needy, frantic, driven. like darth gaydar. 
a true believer of "i get skated on street with my face to bus and that's a fun game" woud add his name would he not?

Im troubled by this. I hope you will choose one king and one king only and that the king has meganightvision so he can craft with nightvision.

**Comment by Night-Pryanik** [comment]
Just a mindflow, closing.

**Comment by tsaber** [comment]
I would say how do you know.
