### ISSUE TITLE
Cash card stack: does not use card with highest value when buying from vending machine

### ISSUE THREAD

**Issue by MT-Arnoldussen** [CleverRaven/Cataclysm-DDA#24744]
Game version: 

Operating system: wWndows 10

Tiles or curses: Tiles

Mods active: [  "dda",  "More_Survival_Tools",  "makeshift",  "alt_map_key",  "npc_traits",  "mutant_npcs",  "filthy_morale",  "more_classes_scenarios",  "no_reviving_zombies",  "novitamins",  "more_buildings",  "Urban_Development",  "Experimental-Z-Level",  "more_locations",  "deoxymod",  "boats",  "blazemod",  "Tanks"]

### Expected behavior

When you select your stack of cash cards to use to purchase things from a vending machines, the saldo of then entire stack is used. If this is not possible, the cash card with the highest saldo should be used.

### Actual behavior

A card that does not have the highest saldo is used, leading to the following scenario:

![cash card 1](https://user-images.githubusercontent.com/3521568/43921588-792005aa-9c1c-11e8-8da9-50b0d2259659.PNG)
![cash card 2](https://user-images.githubusercontent.com/3521568/43921590-7939c90e-9c1c-11e8-94d0-134605df816f.PNG)

I assume it's simply the "top" card in your stack, because this behaviour is consistent.

Notice how in the upper left of the second image the total saldo is a lot less than is displayed in the first.

### Steps to reproduce the behavior

Get some cash cards, buy stuff from vending machines, notice how you cannot buy items even though you have thousands of dollars in your stack.

**Comment by KurzedMetal** [comment]
Another acceptable "expected behavior" for this would be letting us pick the specific cash card like it was before, and use the stacked cash card only when listing on inventory.
