### ISSUE TITLE
MacOS HiDPI screen issues (with possible fix)

### ISSUE THREAD

**Issue by kelwyng** [CleverRaven/Cataclysm-DDA#24751]
#Game version: 0.C30226, 0.C-30234

Operating system: MacOS 10.14 Beta

Tiles or curses: Tiles

Mods active: default

### Expected behavior

Game window displays more or less the same on HiDPI / retina internal laptop screen and normal DPI external monitor

### Actual behavior

Weird doubling of window content on HiDPI / retina screen:

![screen shot 2018-08-10 at 11 57 00 am](https://user-images.githubusercontent.com/12590239/43935461-7924ccea-9c97-11e8-924f-1c21f67deb96.png)
![screen shot 2018-08-10 at 11 57 08 am](https://user-images.githubusercontent.com/12590239/43935465-7a59365a-9c97-11e8-844a-c19299372e96.png)

### Steps to reproduce the behavior

Compile either from source or homebrew, drag game window between internal display and external monitor.

### Fix but I don't know how to do it 'properly'

Adding 
`window_flags |= SDL_WINDOW_ALLOW_HIGHDPI;`

to WinCreate() in src/sdltiles.cpp fixes this issue.

**Comment by mlangsdorf** [comment]
commit the change, open a PR.
I've gone ahead and done that but you're more than welcome to take it over.

**Comment by mlangsdorf** [comment]
That was quick, thanks for finding the initial solution.
