### ISSUE TITLE
Autoattack outreaches aimed attacks in circular distance mode with range attack weapon

### ISSUE THREAD

**Issue by kelwyng** [CleverRaven/Cataclysm-DDA#24750]
Game version: 0.C-30226

Operating system: Mac

Tiles or curses: Tiles

Mods active: default

### Expected behaviour

Autoattack (`tab`) can only hit the same enemies targetable with `f`

### Actual behaviour

While welding a range attack melee weapon (eg knife spear), an enemy two diagonal spaces away can be hit with Autoattack (`tab`) but can not targeted manually.

This behaves as expected in non-circular distance mode.

![autoattack](https://user-images.githubusercontent.com/12590239/43932184-e8784d18-9c85-11e8-84a6-5a0df0dc7b78.png)
![aimed](https://user-images.githubusercontent.com/12590239/43932188-ec7a31f6-9c85-11e8-9538-c38f5bba26b8.png)

Note that `REACH3` (awl pike) weapons seem to behave as expected.

### Steps to reproduce the behaviour

Enable circular distances mode, and while holding a knife spear, use an Autoattack (`tab`) when a monster is two diagonal spaces away, compared to targeting them with `f`. 

Credit for discovering to BradaZnanja

**Comment by Inglonias** [comment]
I'm able to confirm this as well. I just didn't have the time to report it. Thanks for doing due diligence, though!
