### ISSUE TITLE
Add "Reload Tileset" Button

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#24757]
While working on my tileset, to check newly created tiles i need to reload tileset. Only way i can do that is to choose another tileset, save settings, then choose my tileset again through options. This is very teidous to do each time i add something, or change something in my tileset.
I suggest adding "reload tileset" button to keybindings, so then i press it, my current tileset will reload, and new tiles what i added or changed will be visible.

**Comment by mlangsdorf** [comment]
That seems like a very specialized keybinding. How about an entry in the debug menu instead?

**Comment by SomeDeadGuy** [comment]
Also will be good, i guess.
It will be like this: Press Debug menu button, press button to reload tileset?

**Comment by mlangsdorf** [comment]
That's how I would implement it.

**Comment by SomeDeadGuy** [comment]
Neat.
