### ISSUE TITLE
Fencing with high skill and high encumbrance may result in counter lock up

### ISSUE THREAD

**Issue by maniak1349** [CleverRaven/Cataclysm-DDA#24753]
Windows, tiles, 0.C-29661-g765578f. (This was true for builds from couple of years ago too.)
Mods: dda, no_npc_food, novitamins

Steps to reproduce:
1. Learn and select Fencing
2. Get your weapon and melee skill high enough (7/7)
3. Wield a fencing-compatible weapon (broadsword)
4. Get your encumbrance in light red/red. I think only torso encumbrance is important here? (survivor suit + survivor backpack + survivor rucksack, or just an unpowered heavy power armor )
5. Get into fight with 2+ agile enemies (zombie child, skeletal dog, giant bee etc.)
6. If you will get your stamina low enough or will not have much to begin with at the start of the fight you will get locked into endless counter/miss/thrown off balance helix until you or most of your enemies are dead. Unpowered power armor + broadsword + 36 giant bees gave me ~300 out of control turns for example.

This will not happen if you have no style selected. Since in theory you can stop countering any time you want this should not result in complete lock up.

(Other styles with similar counter mechanics may be susceptible too?)

**Comment by Break-Off** [comment]
The most elegant solution is applying a encumbrance penalty to the special attack/counterattack a martial art has. You shouldn't have the agility to counter an attack or doing special movements if you're overencumbered.
