### ISSUE TITLE
Error "assignment does not update value" for M24

### ISSUE THREAD

**Issue by svick** [CleverRaven/Cataclysm-DDA#24769]
Game version: 0.C-30307-g151b1e3

When I started my game, I got the following error:

![](https://user-images.githubusercontent.com/287848/43984436-ea882bde-9d00-11e8-8bfc-85a040774f18.png)

As far as I can tell, [that JSON](https://github.com/CleverRaven/Cataclysm-DDA/blob/151b1e3/data/json/items/gun/308.json#L253) was added in the very recently merged https://github.com/CleverRaven/Cataclysm-DDA/pull/24515.

The same error also happens for `"reload_noise_volume": 10`.

**Comment by DracoGriffin** [comment]
Improper usage of "copy-from" flag; potentially tested within a mod where these errors will not appear because mod behavior to override.

Fixed in #24774.
