### ISSUE TITLE
Option to use the same string for multiple ids in item_actions.json

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#24763]
It's a follow up to what's been said by @cainiaowu in #24648

Currently, [item_actions.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/item_actions.json) generally lists a name for each item action, most of which are not unique. It would be nice to have option to designate a name to multiple items. For example "Take" to  all pills, "Inject" to injections, "Smoke" to smokeable items or "Turn off" to items that can be turned off. That way it'd be easier to keep the names unified, especially for translators and possibly make files shorter.

Something like copy-from for descriptions.

**Comment by kevingranade** [comment]
Should any of the strings that are slightly different now be the same string?  Or are all the strings that should be the same already the same?

If it's the latter I dont see this as an actual peoblem.

The way the translation system works, if the strings are the same they only have to be translated once.

**Comment by cainiaowu** [comment]
Well, what I mean is that consume_drug is used by several different types of drugs and each type should have different use action names. Current json structure make the use action can only have same "consume" in activate menu, so they might need to separate into different use action with same "abstract" but different use action name.

**Comment by Faalagorn** [comment]
@kevingranade Seems I was mistaken, I originally thought you have to translate each independent occurence of Take/Smoke/Inject, but now that I finally registered on Transifex, searching for `occurrence:lang/json/item_action_from_json.py` seems it's not the case.

However, I agree with what @cainiaowu said about the each item having unique separate name – which seems to slowly be the case, but some items still use `consume_drug` that should be sometimes Inject, Smoke, Take or entirely something else.

I'll keep this issue open for a while, but feel free to close it if you think it have to be formulated again plus *maybe* I can eventually brew a PR for adding those actions somewhere down the road (unless someone else is up for this task) – that would fix the issue of consuming fedora as well :wink:.

**Comment by Faalagorn** [comment]
Now that I know how translations works (same string won't appear multiple time, I'm closing this, but leaving #24648 open – feel free to discuss it there.
