### ISSUE TITLE
A way to keep previous translations for the new strings

### ISSUE THREAD

**Issue by Faalagorn** [CleverRaven/Cataclysm-DDA#24784]
After being pointed by @cainiaowu and @Night-Pryanik in #24648 and #24761 and figuring out how the translations are performed, it turned out that each ever slightly minor modification to the English string always results in the translation being scrapped and removed.

I know it's partially by design, to let translators know that the string has changed (and update the English string in translations!), and it's a limitation of underlying software (gettext and Transifex), but maybe an exception could be worked out if the string's length doesn't change, or at least it's only the letter casing?

On one hand changes like that could be avoided, and are gracefully pointed by active translators, plus for an active translators team each language could be promptly updated, especially based on the history of translated files in git's .po files (~~sadly no way to see old strings directly in Transifex for experimental CDDA branch from what I know~~ – seems Transifex remembers old strings, as pointed out by @nexusmrsep ).

In reality, however, it may be harder, as sometimes PRs are merged promptly before those are spotted, some languages doesn't get too much attention and a bunch of people are unaware of the issue – in many other, non-gettext projects, translated strings doesn't change when English is changed, as translations are not based on English strings themselves, but rather string placeholders, where English is just one of the languages. It's also crippling to not be able to do a major styling change without break translations of course.

I'm not suggesting to change the way the translations are done, as gettext is de facto standard for terminal apps (which CDDA on its core is), but it would be really nice if there'd be a way to preserve strings and only let developers know that they are changed. It might have been less of an issue if CDDA was based on timed-based releases, so translators could only worry about getting right in time for the translations before each quarterly or whatever release (similar how .C and .B translations are unchanged once made), but with the ever-changing nature of development, it's certainly hard for translators to translate back each minor typo change promptly.

I also volunteered helping fixing those changes manually in Transifex when they appear and I will be doing so for Polish when needed when I'm there, but changing other languages would require me to join the other projects and bring the old translations back (which I don't mind, though might be confusing to other translators as I don't know the languages) and might be a bit on PITA to do each time some slight change is being made.

Any suggestion is welcome. For now guess I'll have to revert the casing changes in #24761 as suggested, as it's a lot of strings and mods also still use the Title Case notation in the construction menu, (but still there'd be a few strings left to re-translate, incl. "Mark Firewood Source"), but would like to keep the recent changes from #24648 if possible.

**Comment by kevingranade** [comment]
You say that you're not suggesting a change to the gettext infrastructure, but as far as translation is concerned, we do nothing but use gettext.

Basically, this is an upstream issue, unless you have a proposal for some kind of workaround, we're not going to be able to take action on it.
