### ISSUE TITLE
Ammunition exploding in fires is too dangerous.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#24788]
Game version:
Since #24171
Operating system:
All
Tiles or curses:
Both
Mods active:
Any
### Expected behavior
Dropping small arms ammunition (pistol, rifle) presents minimal danger, at most the casing ruptures and a small amount of fragments fly in random directions.
### Actual behavior
Burning a large pile of small arms ammunition is quite dangerous, sending large quantities of fragments in all directions.
### Steps to reproduce the behavior
Start a fire.
Drop a big pile of ammunition into it.
Take damage.

**Comment by Shodan14** [comment]
I've found that setting fire to a body with any amount of ammo on it pretty much instant death.

**Comment by FulcrumA** [comment]
Can confirm. It doesn't have to be a large pile of ammunition, either. A handful of low-caliber bullets is enough to - with enough bad luck in damage placement - instantly kill even somewhat armored character.

**Comment by kevingranade** [comment]
That confirms my understanding; it's nice to see some controlled testing that confirms it.

**Comment by kevingranade** [comment]
After a quick skim through the video, I'm tempted to just remove the fragment effect from small arms entirely.
The level of danger presented seems even lower than I expected.

**Comment by kevingranade** [comment]
Marking as easy since you just need to dismantle the ammo explosion feature to adress the issue.

**Comment by aierce** [comment]
heh, I remember this exact issue being discussed before. #11532

**Comment by kevingranade** [comment]
Fixed by #24862
