### ISSUE TITLE
List of typos (August 11, 2018)

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#24791]
Game version: fe7d11d596be92821995d5cadb412dc0123b5737

### Typos
This issue reports a couple of typos I found.

In the top layer of the following bullet point list, I write the errornous string. In the lower layer below, I point out the part that is wrong.

* cannister
    * nn
* Leadworks LLC's bullpup L523 platform utilizes the ubiquitous 5.56 round in multiple applications, and is designed to part-swap quickly, safely, and effectively from one to the next.  The carbine model incorporates Leadworks' proprietary gyro-stabilization technology and includes a read-dot sight and an integral laser sight.  Additionally it comes with underslung shotgun for close range encounters.  Like the rest of the family, doesn't accept third-party modifications.
    * read-dot sight
* A Leadworks built in heavy duty barrel especially designed for prolonged shooting.  Reduce accuracy but increase damage output and weapon range.
    * Reduce accuracy
* Overmap terrain building recipies are not implemented yet!
    * recipies
* Operating Theatre Access Control
    * this is British English
* (Sounds like bullshit, you wander what really happened.)
    * wander
* notices the antlered horror and slips away before if gets too close.
    * if
* (You wander if your companions are fit to work on their own...)
    * wander
* Some simple gluten free and lactose free alternative recipie options. NOT EXHAUSTIVE.
    * recipie
* gluten free and lactose free waffle. It's basically an  pancake in hashtage form.
    * gluten (lower case)
    * hashtage
* lactose free waffle. It's basically a pancake in hashtage form.
    * lactose (lower case)
    * hashtage
* Gluten free waffle. It's basically a pancake in hashtage form.
    * hashtage
* I'm on top of the world, baby!.
    * !.
* Labratory Train Controls
    * Labratory
* You were on your way to another routine job, it might of been a target to kill, an item to steal or intel to gather.  Whatever it was doesn't matter anymore; you did your best to avoid the horde and when you arrive, the place is sorrounded, not by cops as you might expected, but by the dead. Worse, you got a cut somewhere along the way and it's looking infected.
    * sorrounded
* A circular blade, powered by the vehicle's engine.  It will dramatically increased the damage the vehicle delivers in collisisons.  Mount on the edges of the vehicle, preferably the front.
    * collisisons
    * increased
* Pitching a Tents
    * (plural)
* The Eastern cougar, a large feline predator.  Once thought extinct in this region, conservation efforts were successful in restoring a thriving population. Fast and silent, this predator can cover long distances with powerful leaps and pounces, catching its prey with its deadly claws before delivering the finishing blow with its enormous fangs.“
    * runaway quotation mark at end
* When turned on, this devices drains power from the vehicle's batteries.
    * this devices
* yourself roar in agony!!
    * !!
* SCT with unicode font
    * unicode (should be “Unicode”)
* If true, will display scrolling combat text with unicode font.
    * unicode
* We have synchronized our local physiology with that of the Mycus.  Any spores we may encounter will not attempt to germinate inside the local system, and we may traverse Mycus biospheres easily, as native bioforms shift shape to accomodate us.
   * accomodate (should be “accommodate”)
* lan center
   * lan (should be “LAN”)
* Down 1 turns, knockback 1 tile, min 3 unarmed
   * 1 turns

**Comment by Rivet-the-Zombie** [comment]
>an pancake
