### ISSUE TITLE
Bomb fragments deal too much damage to armored targets.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#24796]
Game version:
Since #24171 
Operating system:
All
Tiles or curses:
Both
Mods active:
Any
### Expected behavior
Small fragmentation explosives deal significant damage to unarmored targets, but are easily blocked by armor.
### Actual behavior
Small fragmentation explosives easily penetrate armor.
### Steps to reproduce the behavior
Spawn and wear a full survivor suit.
Spawn, arm and throw a grenade 8 tiles away.
When the grenade goes off, you should survive, but with the current code you frequently die.
(need to double check coverage, if it's simply bypassing the armor due to lack of coverage, it's working as intended.)

Spawn and wear a light power armor and light power armor helmet.
Spawn, arm and throw a grenade 3 squares away.
As above, you should avoid all damage.

Based on a post on discourse: https://discourse.cataclysmdda.org/t/personal-opnion-explosions-are-overbuffed-with-two-examples-updated-see-new-long-post-by-me/16058/24?u=kevin.granade

**Comment by ymber** [comment]
Cant be a coverage issue, you still get torn up pretty bad in power armor.
![Wearing full light power armor with a grenade 3 tiles away](https://user-images.githubusercontent.com/34044886/43999515-7b9f32ac-9e05-11e8-94ea-c38a6d4a74c8.png)
