### ISSUE TITLE
Missing temperature option.

### ISSUE THREAD

**Issue by The-Scout** [CleverRaven/Cataclysm-DDA#24815]
Game version: 7687

Operating system: windows 10 pro 64bit

Mods active: DDA

### Expected behavior
An option to switch between fahrenheit, Celsius, and kelvin 

### Actual behavior
There is no kelvin option for temperature. 

### Steps to reproduce the behavior

Go into the interface settings menu

**Comment by Night-Pryanik** [comment]
Do we really need kelvins here?

**Comment by sfsworms** [comment]
Apart from ice lab, is there any benefit to that? Who uses K in real life?

**Comment by ZhilkinSerg** [comment]
It would be pretty easy to add, but what for?

**Comment by Night-Pryanik** [comment]
That way we'll need to add Rankine, Rømer, Réaumur, Delisle, Newton and all other temperature scales too.
