### ISSUE TITLE
Ant tunnels are buggy

### ISSUE THREAD

**Issue by YakumoChen** [CleverRaven/Cataclysm-DDA#24818]
Game version:
Exper. 7649
Operating system:
Win8
Tiles or curses:
Tiles
Mods active:
Bionic Systems, Makeshift Items, More Survival Tools, More Buildings, More Locations, Folding Parts, Roguelike Classes, Safe Autodoc
### Expected behavior
Anthills are explorable and mappable and you can get loot 
### Actual behavior
Ant tunnels don't appear on the map right, they're bugged out "black squares" the game doesn't know how to label, so when you move the map cursor other tiles "overlap" onto them. Also, the chambers are closed off by rock so you can't explore anywhere but normal tunnels.
### Steps to reproduce the behavior
Anthills, man

Map when M key is pressed
https://cdn.discordapp.com/attachments/252368751016542218/478464622442053632/unknown.png

Moving the cursor around to make it bug out
https://cdn.discordapp.com/attachments/252368751016542218/478464753849860106/unknown.png

**Comment by svick** [comment]
I believe the "black squares" issue happens because ant tunnels are considered ["isolated"](https://github.com/CleverRaven/Cataclysm-DDA/blob/4e21eef/src/overmap.cpp#L92) linear segments, which don't display correctly.

The closed off chambers issue could be related to that.
