### ISSUE TITLE
Winter season tiles broken in many tilesets!

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#24819]
my tileset
![broken](https://user-images.githubusercontent.com/37592026/44036498-9610ffce-9f1a-11e8-86f7-6d0011ca05a2.PNG) 
Xotto+
![brokenxott](https://user-images.githubusercontent.com/37592026/44036511-9d108e8e-9f1a-11e8-8de4-e11dcc8114f7.PNG) 
Chesthole not broken, for some reason.
![brokenchest](https://user-images.githubusercontent.com/37592026/44036517-a03a0824-9f1a-11e8-8b23-c26791813de6.PNG)
Latest version. Something to do with "looks_like" function?

**Comment by mlangsdorf** [comment]
I was passing the id string as an immutable, when it needed to be passed by reference.
![looks_like_fixed2](https://user-images.githubusercontent.com/8007405/44050810-bcdbe49c-9efd-11e8-954b-be9e1c936076.png)
Stock humvee with looks_like for the hddoor tiles and hdtrunk tiles on Xotto+.
