### ISSUE TITLE
Keybindings 

### ISSUE THREAD

**Issue by SirClarke** [CleverRaven/Cataclysm-DDA#24827]
Game version:
7693? hope that's right
Operating system:
Windows 10 Sadly
Tiles or curses:
Tiles
Mods active:
Many but I don't think that's the problem 
### Expected behavior
When I change the keybindings on the main start screen it should
### Actual behavior
It tells me it has a key already when it does not show one all keybinding are default as far as I know
### Steps to reproduce the behavior
simply attempt to change key bindings I've only tried two times as I'm not great at fixing this kind thing lol

**Comment by Night-Pryanik** [comment]
> When I change the keybindings on the main start screen it should

It should what?

**Comment by Zireael07** [comment]
It should change them I guess (his English is not too good)

**Comment by SirClarke** [comment]
yes it should but i seem to have fixed it not sure how as i have tried many things
