### ISSUE TITLE
Marloss flowers in botanical and public gardens

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#24825]
Game version: 0.C-7690

Operating system: Windows XP SP3 x86

Tiles or curses: curses

Mods active: default only

### Expected behavior
Marloss flowers appear in the process of Cataclysm or after of it.
### Actual behavior
Marloss flowers are cultivated in the botanical and public gardens prior to Cataclysm.
### Steps to reproduce the behavior
Enter botanical or public gardens.

I suppose marloss flowers should be removed and replaced with something some mundane. Pinging @cosmiccoincidence.

**Comment by Xenomorph-III** [comment]
Doesn't the game take place 5 days after the Cataclysm? I always thought that was how alien plant life ended up there...

**Comment by cosmiccoincidence** [comment]
Good point. I don't know why I added marloss flower in public gardens but I do remember adding them to the botanical garden in the greenhouse as a result of me simply running out of botanical species to place (hence why mutated cactus is next to the marloss flower in the greenhouse). Iv'e also intended on adding more flowers and grow-able plants into the game but not something Iv'e gotten to yet.

I wont make any changes just yet to see where this discussion goes... Also any suggestions on something to replace it? Like I said, I ran out of species.

**Comment by Night-Pryanik** [comment]
> Doesn't the game take place 5 days after the Cataclysm? I always thought that was how alien plant life ended up there...

Right now marloss flowers are clearly seen to be cultivated: they are growing in distinct order in public garden. I don't mind if they've overtaken the gardens, but in that case they should grow chaotically and probably more rare.

> any suggestions on something to replace it (in the greenhouse of the botanical garden) ? Like I said, I ran out of species.

Use some species twice, there's no criminal in that. Or remove marloss flowers completely.

**Comment by cosmiccoincidence** [comment]
>Use some species twice, there's no criminal in that.

My OCD says otherwise.

**Comment by FulcrumA** [comment]
>My OCD says otherwise.

Botanical gardens usually have more than one specimen of some particular plant so your OCD should have no issue with it.

**Comment by cosmiccoincidence** [comment]
My OCD is bother by the consistency between my botanical garden having one specimen and ones in real life having multiple. It comes from the consistency of that would be the only specimen in my entire garden that has multiples...

How would you guys feel about that plot (and sign) being left blank?

**Comment by Night-Pryanik** [comment]
> How would you guys feel about that plot (and sign) being left blank? As if the garden was still a work in progress..

Good idea.

**Comment by FulcrumA** [comment]
>How would you guys feel about that plot (and sign) being left blank? As if the garden was still a work in progress..
Seems fine to me, as well.

**Comment by cosmiccoincidence** [comment]
So in the botanical garden... I didn't end up leaving the plot empty after removing the marloss flower but instead found another solution that doesn't ache me OCD.

- Removed marloss flower and fungal flower from greenhouse
- Moved strawberry bush and blueberry bush into the greenhouse
- Moved coffee tree (recently added) from over on the side to the middle where the strawberry and blueberry bushes were
- Added a 1/3 chance for the plants inside the greenhouse to grow on any of their plot tiles for added randomness and fullness to the location

![untitled](https://user-images.githubusercontent.com/41941008/44273295-14ada900-a20d-11e8-93e3-1965a5b816fc.png)
