### ISSUE TITLE
Severe morale drop (hates vegetables trait)

### ISSUE THREAD

**Issue by qwizl** [CleverRaven/Cataclysm-DDA#24831]
Game version:

Operating system:

Tiles or curses:

Mods active:

### Steps to reproduce the behavior
Warning before eating vegetables gave a warning around negative 20 but after eating 1 wild veggies it went -700. Morale rose very quickly after and a negative 20 malus remained.

**Comment by Night-Pryanik** [comment]
No confirmation in over half a year, closing.
