### ISSUE TITLE
mapgen: smaller town consumed by larger city

### ISSUE THREAD

**Issue by cake-pie** [CleverRaven/Cataclysm-DDA#24833]
Game version: 0.C-30479-g51ef7e3
Operating system: Windows
Tiles or curses: tiles
Mods active: DDA, Disable NPC Needs, Simplified Nutrition

Worldgen is on default settings.

### Expected behavior
Each town/city should (generally?) be distinct from one another.
If towns/cities are generated near one another, we might be okay allowing them to join/merge together in a city/suburb manner. However, we should not see the following...

### Actual behavior
A larger city generated very close to a smaller town completely eats the town up without a trace.

![mapgen-city-eats-town](https://user-images.githubusercontent.com/28502722/44102267-e10d0ff2-a01b-11e8-95ea-cb169d5ce89b.png)
"Spencer" has been consumed by "Moultenberg", the city label is all that remains.
Everything in the vicinity is <place> <in/on the X outskirts of/X from> Moultenberg.

Can provide save file if desired (is coincidentally a brand new test/debug world)

**Comment by kevingranade** [comment]
I'm not clear that this is a bug, the map reflects the reality that a larger town grew around a smaller town, this is a thing that happens IRL, and people remember the old town.

**Comment by cosmiccoincidence** [comment]
Also larger towns/cities have areas within them that have independent names (ex. Manhattan in New York City).

**Comment by cake-pie** [comment]
Not sure if it's necessary/meaningful for the map to go into city subdivisions -- "small town integrated into larger town" is just one version of this. But then again if I'm not mistaken the city names are mainly just flavor text anyway -- I don't think they have any mechanical / gameplay effect? i.e. Missions don't try to generate objectives in a particular city or such. If so, then yeah, this is at worst just a cosmetic annoyance.

**Comment by CoroNaut** [comment]
Picture example of problem with more pull (from issue I created): 

![](https://user-images.githubusercontent.com/24307650/44299636-2f912380-a2c8-11e8-8643-d9e266496842.PNG)
