### ISSUE TITLE
LoS and fire/craft-pathing are inconsistent

### ISSUE THREAD

**Issue by MT-Arnoldussen** [CleverRaven/Cataclysm-DDA#24837]
Game version: 7694

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: [  "dda",  "makeshift",  "More_Survival_Tools",  "alt_map_key",  "mutant_npcs",  "npc_traits",  "boats",  "deoxymod",  "blazemod",  "Tanks",  "more_classes_scenarios",  "filthy_morale" ]

### Expected behavior

If something is in direct line of sight and within a certain amount of tiles, you can use it to craft with even if it's not adjacent.

### Actual behavior

![capture](https://user-images.githubusercontent.com/3521568/44107628-4eb9d4d2-9ff8-11e8-8efd-8d9c7b691500.PNG)

The highlighted tile is considered within LoS, but you cannot use items on it to craft with, because one of the two tiles inbetween is impassible. 

The tile should either be invisible from the player's location, or the content of it should be usable to craft with.

### Steps to reproduce the behavior

See image.

**Comment by FulcrumA** [comment]
Can confirm. If a line of devices is 12345 then character standing by 2 often has no access to 5 despite it being in line of sight and not far away.

>The tile should either be invisible from the player's location, or the content of it should be usable to craft with.

I'd certainly prefer the second solution - reasonable and quite a QoL improvement without introducing any balance issues.

**Comment by maniak1349** [comment]
Same goes for shooting too - in some cases you can see enemy but can't hit it. For example here you can see turret in both cases but in the second you can't hit it at all - you will be hitting the wall instead.

![cata_aim](https://user-images.githubusercontent.com/2755776/44148564-633d76e4-a088-11e8-99e3-649b15c6094b.png)

Fun fact - if you will switch places with turret in the second case it will be constantly hitting the wall while shooting at you but if you will move one or more tiles down it will hitting you just fine even if it's shooting angle got worse.

**Comment by FulcrumA** [comment]
That's not even just in regards to shooting. If you'd attempt to attack same turret with a ranged melee weapon, it's possible it'd track the attack the same way, thus landing in a wall (not necessarily though, not sure what it's dependant on).

**Comment by anothersimulacrum** [comment]
Fixed after #30444?

**Comment by kevingranade** [comment]
Yep
