### ISSUE TITLE
Overpopulation of Puppies

### ISSUE THREAD

**Issue by ackron99** [CleverRaven/Cataclysm-DDA#24852]
**Describe the bug**  
Baby animals are spawning out of control. I first noticed this with fawns in previous builds but as of build 7696 it has truly gone absolutely insane. I've been playing on my current save for about 60 game days, and the overworld is basically one solid mass of puppies, and they keep growing. At this rate, in another 30 days or so, every single overworld tile will be either a solid obstacle, or a puppy. Talk about apocalypse.

My world is pretty vanilla, I'm not using very many mods. I did change the season length from 14 days to 30 if that makes any difference.

**To Reproduce**  
1. Make a character and find a place to hole up in the overworld, with a dog pack in the reality bubble.
2. Wait.
3. Watch the slow, seething mass of puppies form and grow inexorably.

**Expected behavior**  
Well, presumably there would be a population limit, so that if there are a certain number of puppies on the map, no more spawn. Or something. Same thing for fawns and other baby animals.

**Screenshots**  
https://drive.google.com/open?id=1tWNuMY0zWAKd450DHUXP3dWFn5BOhaFT

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version  0.C-30487-g3499cca]
 - Graphics version [Tiles]
 - Mods loaded DDA, Flithy Clothing, Disable NPC Needs, Simplified Nutrition, Medieval and Historic Content, More Survival Tools, Alternative Map Key, Mutant NPCs, More Buildings, More Locations, Boats

**Additional context**  
Changed season length from 14 to 30.

**Comment by Lorith** [comment]
I believe this one was actually [fixed just a few minutes before](https://github.com/CleverRaven/Cataclysm-DDA/pull/24848) you submitted your issue report.  Try checking with a new updated version once it builds in a few hours?

**Comment by ackron99** [comment]
Awesome, I'll update when it comes out. I figured you guys must know about this one, since it seems so apparent, but I couldn't find an issue report so I figured I'd post it anyway.

**Comment by FulcrumA** [comment]
A fix seems to be already included. Do check if it works though it seems that this ticket can be closed for now.

**Comment by cosmiccoincidence** [comment]
It was fixed in this PR.. #24848

**Comment by nexusmrsep** [comment]
This is fixed AFAIK, so I'm closing it.
