### ISSUE TITLE
The forum on http://smf.cataclysmdda.com/ isnt open for registration or creating threads

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#24869]
How shall we de discuss things in the game without a forum?

Discord is great but a forum thread is there for longer and gives different options to comunicate. Discord only works if the guy with the answer or inspiration is just watching. If he sleeps or is at work....no answer....no inspiration.

Solution: Create a working forum. 

Please.

**Comment by ymber** [comment]
https://discourse.cataclysmdda.org/

**Comment by Night-Pryanik** [comment]
I guess the issue is resolved.
