### ISSUE TITLE
Suggestion: Explosive Ordnance Disposal Suit/Bomb Suit

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#24868]
One thing I've always thought would be both very useful and perfectly at home in cataclysm's setting is a dedicated EOD suit, AKA bomb suit. This is a suit designed for use by ordnance technicians that ideally provides them a chance of surviving the blast of an explosive at extreme close range (albeit not unscathed). Given the recent buff to explosives, this would be more useful than ever to have as an option for disarming landmines and similar situations, while having significant enough downsides that it's combat utility would be limited.

Real-life EOD suits have the following properties:
-A mix of layered Kevlar, Nomex, steel plating and foam padding provide maximum feasible protection from shrapnel, compression and heat waves.
-No incorporated protection for the hands, in order to maximize manual dexterity.
-Extremely encumbering, providing only limited mobility and situational awareness.
-Extremely(!) hot to wear. Some modern, expensive bombsuits incorporate built-in electric cooling, but we'll assume that our post-cataclysmic survivors aren't so lucky, and even then wearing them for an hour at a time is considered an achievement.
-Very heavy. The heavier models appear to weigh around 36kg (81lbs).

Based on this, as an item in CDDA, I suggest giving it the following properties:
Volume: 22 L Weight: 81 lbs/36 kg
Bash: 0 Cut: 0 To-hit bonus: N/A
Moves per attack: 530
Damage per move: 0.00
Materials: Kevlar, Nomex
Flags: WATERPROOF, RAINPROOF, STURDY, OUTER
Can be cut into: 40 Kevlar plates, 40 Nomex patches

Covers: head, mouth, eyes, torso, arms, legs, feet
Coverage: 100%
Encumberment: 50
Protection: Bash: 50 Cut: 60
Acid: 5     Fire: 12
Environmental protection: 10
Warmth: 70
Storage: 4 L

The goal here is to make a suit that gives you an excellent (90%+) chance of surviving a frag grenade or landmine explosion at point blank range, albeit definitely not unscathed (especially on the unarmored hands). It is not intended to be a viable choice for general combat, though it seems perfectly reasonable to me for it to be a good option for taking down low-caliber security turrets, exploring ice labs, or killing zombie grenadiers with moderately less risk than normal. It provides protection only slightly below that of basic power armor, but it has significantly less combat utility than even an unpowered suit outside of very specific circumstances. It also has fire protection on par with the Survivor Firesuit.

While IRL bomb suits have removable helmets, I feel like having the helmet be removable mitigates enough of the suit's downsides to make it potentially a viable and worthwhile general combat suit for a particularly skilled survivor, which goes against the item's intended ingame purpose.

I do not believe it should be craftable. It could be added to most police and military item pools without being too out of place.

Feedback would be appreciated!

**Comment by cainiaowu** [comment]
Looks like an unpowered power armor to me. Why not use them?

**Comment by sfsworms** [comment]
One issue I have is that the EOD suit should be great against explosions, but not necessarily against other damage. It'd be weird if you could just don one and then sit in a school to get insane level of dodge training because none of the critters can go throught the armor.

**Comment by kevingranade** [comment]
Balance note, extremely high ballistic protection is neither required nor
warranted for an EOD AFAIK, bomb fragments are much easier to stop than AP
rifle rounds.  This should be tuned to stop almost all fragments (claymore
point blank? I'm sckeptical), but not rifle rounds.

The real benefit is blast protection, which nothing in the game currently
has AFAIK.

Which is why this would be better than deactivated power armor, in the
latter a point-blank explosion is still going to kill you.

**Comment by Solusphere** [comment]
Oh, I didn't realize that blast protection was actually a thing ingame, hence the high bash/cut protection. If it is, then yeah, the intention is absolutely for it to be armor specifically geared for withstanding explosions, not so much other stuff. I think resistance to small caliber rounds would still be reasonable (it's a heavy kevlar suit after all), and realistically speaking, it's probably among the most bash protective of all modern armor suits IRL, but if the bash and cut protection aren't directly tied to how well it resists explosions, they could be dropped down to 30 or so without sacrificing it's primary function.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
