### ISSUE TITLE
Food rots as fast in -5°C as in 20°C

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#24870]
In a room with 20°C a chunk of minced meat doubles its ammount of bacteria every 20 minutes. So after 200 minutes it has 1024x more bacteria in it.

In the game food spoils as fast at -5°C.

Please integrate temperature based food spoiling.

**Comment by Androwski3000** [comment]
Looks like that is temperature based food spoiling is integrated into the game. I just found this text in the wiki.
It felt different in the game.
Can anybody confirm that temperature based food spoiling is in the game?

**Comment by Lorith** [comment]
It was just added in recently, and has a number of minor bugs with it already identified.  Not certain on the rot timer, though I believe that should work fine as that was the original focus of the change, so it should have been tested, even if the odd interactions were not.

**Comment by sfsworms** [comment]
Yeah, it should work. Are you running the latest experimental?

**Comment by nexusmrsep** [comment]
Leaving aside some bugs that broke the mechanics and were fixed later, food did not rot below freezing temperatures for a long time. Also rot dependency on above freezing temperatures is a very sophisticated mechanism alowing food to rot faster in higher temperatures and slower  in lower temperatures. Derivatives of this system are fridges, freezers and root cellars that maniputae temperature applied to food. So mechanics are in, and we need a confirmation of this bug.

**Comment by CoroNaut** [comment]
I tried using my refrigerator to store food and none of them got the (cold) tag or anything and they rotted at same rate as outside of fridge (turned on and with power of course). This might be another issue though, I don't know.

**Comment by Regularitee** [comment]
I can also confirm the same issue. An active minifridge, despite applying the "frozen" tag to food, seems to have no impact on rotting speed. (i.e., fresh frozen chunks of meat rot after one or two days).

**Comment by nexusmrsep** [comment]
Ok, some comments here: 

@Androwski3000 food does not spoil at all when it's below freezing temperature. Checked that twice. If there was an issue with that between some PRs, its far gone now. Reference: #25166, #24956, #24905 and some others.

@alanbrady that issue is a separate one: #25001, not yet tested by me. You may comment there if needed.

Since the original issue is resolved I'm closing it.
