### ISSUE TITLE
Can't eat food when it's below freezing

### ISSUE THREAD

**Issue by svick** [CleverRaven/Cataclysm-DDA#24875]
**Describe the bug**  

It seems that when the ambient temperature is below freezing (e.g. -6 °C), food freezes so fast it's sometimes impossible to eat it.

**To Reproduce**  

0. I'm in my car with a kitchen unit and some meat in my inventory.
1. I craft cooked meat.
2. Immediately, it becomes inedible "cooked meat (fresh) (hot) (frozen)", which is both nonsensical and way too fast.
3. If I use the kitchen unit as a hotplate, then it stays "cooked meat (fresh) (hot) (frozen)", but becomes edible.

Sometimes food stays inedible even after defrosting it, but I can't reproduce that reliably.

**Expected behavior**  

Food becomes frozen much more slowly, at lest at temperatures near zero. Food can't be both hot and frozen at the same time. Defrosting works reliably.

**Versions and configuration:**
 - Game Version: 0.C-30616-g5d18af2

**Comment by nexusmrsep** [comment]
Problem is known to me and I will be searching for solution ASAP.

**Comment by Rivet-the-Zombie** [comment]
Food in the player's pockets shouldn't be freezing nearly as fast as food left out on the ground, as it's being kept near the player's own body heat - I seem to recall Jack London devoting more than a few pages to the particulars of carrying biscuits and such near one's body for that exact reason.
