### ISSUE TITLE
Animals are generating a bunch of "none" items

### ISSUE THREAD

**Issue by jim-huynh** [CleverRaven/Cataclysm-DDA#24896]
Version 0.C-30641-g9a8bc02

Animals are generating a bunch of "none" items.  I cannot interact with these "none" items, and I cannot burn them.

On further examination, it looks like only the puppies are generating "none" items.  Could it be trying to spawn babies, but returning null items instead?
![none-item](https://user-images.githubusercontent.com/3409545/44271785-e5d50a00-a1ef-11e8-9186-db2e5796b728.png)

![doggies](https://user-images.githubusercontent.com/3409545/44271803-fa190700-a1ef-11e8-91e8-4b1be37fe8f4.png)

**Comment by OzoneH3** [comment]
Can not reproduce this. Puppys and eggs are generating like they should.

**Comment by alanbrady** [comment]
I suspect #25336 resolved this.
