### ISSUE TITLE
Please help me with this mod "Half_Hunger"...

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#24892]
...so that others and I can enjoy parts of the game like exploring and crating more without frequent foraging interuptions.

![1](https://user-images.githubusercontent.com/42423698/44261571-5ee85780-a218-11e8-89bd-2a67b45403f6.jpg)

Hi,
im a mechanical engineer and industrial designer. Even theese simple coding things are kind difficult for me. Please help!

The mod shall reduce all food needed to 50%.

I created a modinfo.json and a mutations.json with the following content:
[
  {
    "type": "MOD_INFO",
    "ident": "HalfHunger",
    "name": "Less hungry",
    "authors": [ "Andruschka" ],
    "description": "Halves hunger rate.",
    "category": "misc_additions",
    "dependencies": [ "dda" ]
  }
]
Theese files ar ein a folder "Half_Hunger" in the mods folder.

Also I integrated the mod into the mods.json of the savegame folder.
[
  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins", "Half_Hunger"
]
But I get an error message saying:  "unkwown content half _hunger".
Notice the space between "half" and "_hunger". I cant locate where thas comes from.

**Comment by Lorith** [comment]
"ident": "HalfHunger",
"Half_Hunger"
-- Here is your problem, you should remove the _ in your mods.json and then it should work fine.

**Comment by stk2008** [comment]
ohhh i like the looks of this mod as I feel hunger is way to frequent in this game shall be looking for this when out :)

**Comment by Lorith** [comment]
Basically you can just copy one of the metabolism mutations, set hunger to 0.5 (or 0.25 for even lower) and then add it to your character after making sure it doesn't cancel anything and has zero cost.  Pretty easy to make your own.

**Comment by Androwski3000** [comment]
This was closed but I´m not finished. Do you prefer to override my needs to just have this closed?
