### ISSUE TITLE
Frozen liquids in containers are impossible to defrost by heating

### ISSUE THREAD

**Issue by jakub-niscior** [CleverRaven/Cataclysm-DDA#24893]
**Describe the bug**  
If you have a frozen liquid in a container there is currently no way to defrost it by heating it up. Even worse early game if you clean up water and pour it into a bottle it will very quickly (immediately?) freeze up in your inventory. Afterwards the game does not give an option when using pots/frying pans to defrost something that is inside a container.

**To Reproduce**  

1. Basic start, spring, low temperature
2. Light a fire near a source of water (toilet), have a few containers on hand
3. Clean up dirty water and pour it into a glass bottle
4. Water will soon freeze in your inventory
5. Attempt to 'a' use a pot or frying pan to heat the frozen clean water - there will be no such option

**Expected behavior**  
You should be able to defrost the liquid contents of containers, otherwise they are unusable.

**Screenshots**  
![zrzut ekranu 2018-08-17 o 13 13 20](https://user-images.githubusercontent.com/7921612/44264851-6ca3da00-a224-11e8-8bef-5b8c6fab8d1e.png)
![zrzut ekranu 2018-08-17 o 13 13 47](https://user-images.githubusercontent.com/7921612/44264866-788f9c00-a224-11e8-9ff0-c838cc84fd4a.png)
![zrzut ekranu 2018-08-17 o 13 13 36](https://user-images.githubusercontent.com/7921612/44264857-70cff780-a224-11e8-91f5-ff2681c71f51.png)

**Additional context**  
You could dump the contents of the container on the floor (clean water on the seconds screenshot) and the game will give you the option to heat it up but it will place it back on the floor from which you have no way to get it back in a container. The fact that you could somehow pick it up to heat it but then you can't get it in a container from the floor doesn't make much sense either, but is out of scope of this issue.

**Comment by dhessels** [comment]
Thanks for working on this. Using 0.D I had a pot of frozen water which I couldn't thaw by using the pot. But I could dump the frozen water on the ground and then use the pot to thaw out the water on the ground (even though you can't pick up water, frozen or otherwise)!
