### ISSUE TITLE
Build #7705: Constant pain (~20 ) does not let the character sleep

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#24903]
**Describe the bug**  
The character constantly wakes up and gets interuptions while sleeping. That was not the case yesterday (RL). All bodyparts are at 100% health for like 2 ingame days.

**To Reproduce**  

Just press $

**Screenshots**  
![5](https://user-images.githubusercontent.com/42423698/44280581-7d207880-a255-11e8-9d6c-1b99bdb69674.jpg)

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Build 7705

**Comment by Night-Pryanik** [comment]
You may got parasites. Did youк character eat raw meat recently?

**Comment by Androwski3000** [comment]
No. If parasites, there is no anouncement?

**Comment by Night-Pryanik** [comment]
Yes, no announcements. One can judge by indirect features, like sudden pain out of nowhere. Maybe you drank some dirty water?

**Comment by Androwski3000** [comment]
Can it be that I used rotten meat in a recipe? The rotten stuff is still available for recipes.

**Comment by Night-Pryanik** [comment]
Probably. In any case just eat antiparasitic drug and see if this pain goes away. If it does, the issue could be closed.

**Comment by Androwski3000** [comment]
I agree. I cant craft this drug and I havent found it yet.
Also i got this log message: "Your muscles feel like knoted and tired."

**Comment by Night-Pryanik** [comment]
> Also i got this log message: "Your muscles feel like knoted and tired."

This message appears on parasites. Take medicine.

**Comment by Androwski3000** [comment]
I cant craft it yet. The only chance I see to blast that door open at that doctors office miles away and hope that medicine is in that room.....

**Comment by Androwski3000** [comment]
I dont have this drug available. The only chance I see is to blast a door in a doctors office to see, if the drug is in that room.
