### ISSUE TITLE
Hand drawn maps NEVER show location of said LAB

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#24900]
**Describe the bug**  
I have found a hand drawn map in a bush I read it and it did say now I know where this lab is but it NEVER shows it on the map.
Even looking around the map edge never shows a RED > to show its off the map some where.

**To Reproduce**  
just get a hand drawn map and read it

**Expected behavior**  
to show me the lab location on the map.or at least a RED > pointing to it if its off the map edge.

Now here is the twist it does say I know the coordinates soooo I would not expect a road or path to show on the map to its location just the lab as one dot on the map

**Screenshots**  

https://cdn.discordapp.com/attachments/252368987210514433/480014532845109269/unknown.png

https://cdn.discordapp.com/attachments/252368987210514433/480018493756932097/unknown.png

https://cdn.discordapp.com/attachments/252368987210514433/480014442437017604/unknown.png

**Versions and configuration(please complete the following information):**
windows 10 64 bit
CDDA tiles 64bit version 7700
mod list is

https://i.imgur.com/zgOnhkj.png

**Additional context**  
N/A

Thank you

**Comment by Lorith** [comment]
This item is from cata++ mod, and it does not show the location directly as it does not interact with the quest system, as far as I know.

**Comment by Night-Pryanik** [comment]
Cata++ mod has its own repository, issues concerning it should be posted there.
