### ISSUE TITLE
On activating tools from via "a" while they are on the ground, they are in inventory afterwards.

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#24908]
"I used the washboard half an hour ago. Now im far out from my base hitting the weight/volume limit. All of a sudden I discover the trusty washboard/welder/soldering iron/ etc in my inventory.

Please make the tools stay where they are, when they got activated, while they where on the ground/in a trunk etc.

**Comment by CoroNaut** [comment]
I activate things on the ground rarely, but when I do, I expect to pick them up and use them multiple times. Perhaps make this an option in settings menu? We could have a "Misc" section for small stuff for this if it gets implemented.

**Comment by Robik81** [comment]
> but when I do, I expect to pick them up and use them multiple times

The fact that you would not pick the item does not prevent you from using it multiple times. Unless you mean use it multiple times in different places.

**Comment by Robik81** [comment]
#24732 

While it does not work with washboard or soldering item, it does work for welder and other tools where is reasonable to expect you want to keep the item in its place.

**Comment by narc0tiq** [comment]
I agree with the issue here, just because I want to use the tool doesn't mean I want to put it in my pocket -- after use, I expect to find it right back where it came from.

**Comment by Androwski3000** [comment]
There could be a whole interface be openened for the washboard/ etc. Where at the ned of usage you decide, if you drop to the ground or keep.

The washboard has the beginning of such an interface already. the one  where you choose what to wash. This could be enhanced.
Also the bug/feature from having to wash items multiple times could be adressed in this interface. If an item gets a counter of how often it has to be washed until clean. -> #24907
