### ISSUE TITLE
(E)at menu does not show that food is "mushy"

### ISSUE THREAD

**Issue by logros13** [CleverRaven/Cataclysm-DDA#24904]
**Describe the bug**  
Most uncooked fruit and vegetable gives negative joy

**To Reproduce**  
1. use debug to spawn some fruits and vegetables e.x grapes and cucumbers
2.  check joy stat (which is -5 in the above exampless)

**Expected behavior**  
While some vegetables like potatoes having negative joy raw makes sense one would expect most these foods to give positive or at least neutral joy

**Screenshots**  
![image](https://user-images.githubusercontent.com/20383070/44280688-bce76000-a255-11e8-8fad-f109228aed64.png)

**Versions and configuration(please complete the following information):**
 - Game Version 0.C-30662-g7bacaf3
 - Graphics version: Tiles
 - Mods loaded: dda, no acid zombies, StatstTroughSkills, Filthy clothing, disable npc needs, disable religious texts, simplified nutrition, alternative map key

**Comment by nexusmrsep** [comment]
@logros13 have you checked their description? Does it says that they were frozen and now are mushy and tasteless?

**Comment by logros13** [comment]
@nexusmrsep it does indeed, while this explains why they have negative joy it raises the issue that there is no way to see this from the (E)at menu. This should probably be visible on the name similar to (rotten) to avoid confusion.

Should i close this and open a new issue for the unclear ui or just leave this here? I am new to github so i am not sure what the proper way to handle this is.

**Comment by nexusmrsep** [comment]
Leave it here, but consider renaming, as now the cause is identified. Also your idea to add mushy flag is not bad, I'm only in doubt that it would bloat the display, like: (old) (mushy) (frozen). Will put that under discussion on the Discord.
