### ISSUE TITLE
Everything seems to have implants

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#24910]
Or at least, I'm getting messages along those lines when butchering. Even things that seem ridiculous, like puppies, raccoons, etc.

It's worth noting I'm using a character with 8 mechanics, electronics, medicine -- so I assume they aren't mistaken, unless skill checks for discerning proper bionics are incredibly high.

**Comment by Night-Pryanik** [comment]
It was a bug, but it should be [fixed](https://github.com/CleverRaven/Cataclysm-DDA/pull/24879) recently. Care to update to the latest experimental and check if this is still an issue?

**Comment by Regularitee** [comment]
Ah, didn't realize a new version was released since I updated yesterday. I was probably mistaken, so I'll close this unless it pops up again.
