### ISSUE TITLE
Cockroaches and zombies not hostile to each other

### ISSUE THREAD

**Issue by logros13** [CleverRaven/Cataclysm-DDA#24911]
**Describe the bug**  
Zombies and cockroaches are not hostile to each other

**To Reproduce**  
1. spawn/find a few cockroaches and zombies close to each other.

**Expected behavior**  
Zombies attacking the cockroaches like they do any other animal.

**Versions and configuration(please complete the following information):**
 - Game Version: 0.C-30662-g7bacaf3
 - Graphics version: Tiles
 - Mods loaded: dda, no acid zombies, StatstTroughSkills, Filthy clothing, disable npc needs, disable religious texts, simplified nutrition, alternative map key

**Comment by Night-Pryanik** [comment]
> Zombies attacking the cockroaches like they do any other animal.

Zombies are neutral to `small_animal` monster faction.

**Comment by kevingranade** [comment]
Seems to be working as intended.
