### ISSUE TITLE
[Experimental #7699 Windows x64 Graphical] A stack of item always invisible to mouse view when placed under the vehicle 

### ISSUE THREAD

**Issue by Edgar-cy-Lee** [CleverRaven/Cataclysm-DDA#24926]
Condition: At least 1 stack of Item is either on pavement under a vehicle. (there could be more condition)

Expected: All items under a vehicle displays properly under the mouse view.

Actual: Single item stack is always missing from the mouse view.

Please refer to the forum post for more details:
https://discourse.cataclysmdda.org/t/experimental-7699-windows-x64-graphical-cannot-see-certain-items-on-the-ground/16275

**Comment by CoroNaut** [comment]
You require xray goggles to see through the bottom of the vehicle. Case closed.

On a more serious note, the issue that should be addressed from the forum is the fact that different people see and don't see different items using mouse view.
