### ISSUE TITLE
Should field dressed zombie carcasses still revive?

### ISSUE THREAD

**Issue by svick** [CleverRaven/Cataclysm-DDA#24920]
As far as I can tell, when I field dress a zombie corpse, the resulting carcass is still capable of reviving itself. Is that the intended behavior?

**Comment by Chezzo** [comment]
They also still revive if you quarter them.

**Comment by jim-huynh** [comment]
If you look to your left, at the marauding zombie hairs, you can see that we are now approaching Dwarf Fortress.

**Comment by tyrael93** [comment]
@Chezzo 
Now that looks like a fine way to get infinite bionics

**Comment by nexusmrsep** [comment]
Wow, now that was utterly unexpected.
