### ISSUE TITLE
Bionics need to be updated to include fine cutting

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#24930]
With the recent update, I think some bionics should include some fine cutting ability.

The monomolecular blade, for example, by its very definition should (fine) cut better than anything else in the game. 

The integrated toolset is missing fine cutting as well (and possibly a crowbar function). S

**Comment by Chezzo** [comment]
Integrated toolset isn't missing prying, it is just in the % menu, I think.

**Comment by CoroNaut** [comment]
If you just examine a closed crate, the cbm when active will automatically pry it for you.

**Comment by KorGgenT** [comment]
I... disagree that they should get fine cutting. Have you ever tried to do anything fine with a sword? 
Also, the integrated toolset probably wouldn't have something like a scalpel, either.
There is however, already a CBM that has fine cutting 5
