### ISSUE TITLE
Hot air from a fire should influence measured temperature and may prevent food from freezing

### ISSUE THREAD

**Issue by nexusmrsep** [CleverRaven/Cataclysm-DDA#24938]
**Is your feature request related to a problem? Please describe.**  
Folks at Reddit expected fire to heat up a room to prevent food from freezing. It's a viable option.

**Describe the solution you'd like**  
A small research shows that it can be possible, as fire emits hot air, but this air is only affecting player, and it should affect measured temperature as well, perhaps preventing freezing when the air will be hot enough to counter outside temperature.

**Describe alternatives you've considered**  
N/A

**Additional context**  
[HERE ](https://www.reddit.com/r/cataclysmdda/comments/984rqz/what_the_fuck_is_the_foos_freezing_mechanic/)is the Reddit post.

**Comment by MT-Arnoldussen** [comment]
lava rifts should do the same

ideally body heat should affect items in your inventory too

**Comment by stk2008** [comment]
Yeah this realy should be in and would be awesome to have :)

**Comment by Lorith** [comment]
I was unaware of hot air existing, perhaps that could be used in powered vehicles too in order to remove the bug of only the player being impacted by vehicle AC.
