### ISSUE TITLE
Whaley's Mods

### ISSUE THREAD

**Issue by cosmiccoincidence** [CleverRaven/Cataclysm-DDA#24932]
All of Whaley's locations have now been added to the game but I will leave this space for people to discuss the possibility of adding his other mods as well, either into the vanilla game or as official mods.
What should and should not be added?

**1. [Whaley's Arts and Crafts](https://www.reddit.com/r/cataclysmdda/comments/8w4qto/whaleys_arts_and_crafts_mod/)** - Allows the player to widdle (carve from wood) several figurines (mostly
    for trading) and smoking pipes (for smoking from).
    Includes...
- 16 craft-able figurines
- 13 craft-able pipes

**2. [Whaley's Cassettes](https://www.reddit.com/r/cataclysmdda/comments/8xdtuv/whaleys_cassettes/)** - Adds audio cassettes and a cassette player. Playing a cassette gives the player an
    audio message (making noise) with similar flavor as survivor notes.
    Includes...
- 72 unique audio messages

**3. [Whaley's Weird World](https://www.reddit.com/r/cataclysmdda/comments/984r3h/whaleys_weird_world_mod_aliens_cryptids_and_govt/)** - Adds weapons, ammo, items, monsters, and locations.
    Includes...
- pink mist (monster - a whirling ball of pink mist with a small solid mass in the center)
- entomber (monster - a constantly changing mass of muscle and flesh, a thick cloud of choking gas surrounds it)
- blood beast (monster - a pulsing blob of flesh, covered in tentacles and holes leaking blood)
- blood worm (monster - a large red blood worm with a gaping maw filled with rows of teeth)
- blood worm mass (monster - a writhing ball of small blood worms)
- grey alien grunt (monster - a short grey alien)
- alien pillar (monster - a strange, sinister pillar)
- reptilian (monster - a humanoid reptile being)
- loch ness monster (monster - a creature of the sea, many thought to be a legend)
- lurker (monster - a fleshy being with a big head and hand-shaped limbs lurking in the waters)
- floating head (monster - a glowing red, metal head statue floating in the air)
- man spider (monster - a man twisted into a shape of a spider, how it's possible you are not sure)
- mothman (monster - a humanoid moth creature)
- jersey devil (monster - a small devil like being with a tail and wings)
- sentinel (monster - a CIA robot designed to guard CIA facilities)
- CIA security (monster - a guard working for the CIA)
- CIA hazmat (monster - a hazmat worker, working for the CIA)
- blood house (location - a house that spawns blood beasts in it)
- ufo crash site (location - the crash site of an alien flying saucer)
- CIA lab (location - a large hidden lab under an old diner out in the middle of no where)
- alien gun & alien ammo (weapon - a phase/energy handgun engineered by grey aliens)
- blood worm eggs (item - an unappetizing food, dont let is spoil or it might hatch into a mass of blood worms)
- CIA documents (item - classified documents with information pertaining to classified projects)
- CIA flashlight (tool - a self powered flashlight)
- alien instrument (artifact (tool) - a musical instrument engineered by grey aliens, emits a calming gas)
- bone violin (artifact (tool) - a sinister musical instrument made of bloody bones and skin, it leaks blood when played and grants the player a strength buff while making them go a bit crazy)
- golden hand (artifact (tool) - an addictive weapon that saps life from enemies you hit and reduces intellect)
- crystal eyeball (artifact (tool) - a radioactive crystal eye that gives clairvoyance (see through walls at short distances) but lowers strength and makes the player glow)
- glowing lighter (artifact (tool) - a lighter with snakes printed on it, it glows but nerfs the players dexterity and speed and has a small chance to spawn an inter-dimensional snake when the player is struck)
- bloody chainsaw (artifact (tool) - an addictive weapon that increases strength while used but makes the player a bit crazy and suffer withdraws after use)
- glass spider (artifact (tool) - a small figure granting the player a speed and dexterity buff, perception nerf and causes the player to make a lot of noise)
- lab coat of holding (artifact (armor) - a lab coat with pockets so large they must be storing their mass in another dimension)
![weirdworld](https://user-images.githubusercontent.com/41941008/44298062-622c2380-a2aa-11e8-8d6d-7b3a0e1d5837.png)

**Comment by Night-Pryanik** [comment]
Could you please describe what are the features of daycare, thrift store and veterans of foreign wars store?

**Comment by stk2008** [comment]
If u merge lets say the boats mod he does what happens to peeps actually running the mod like me.

Will I get a warning of double content or

Thanks. :)

**Comment by Night-Pryanik** [comment]
I'm against adding Weird World neither to vanilla nor the official mods. That's just another content pack that doesn't fits the Cata theme that one can download separately if he is interested.

**Comment by DracoGriffin** [comment]
If anything, a portion (all/most/some) of the "Weird World" could fit right in with Crazy Cataclysm.

**Comment by cosmiccoincidence** [comment]
**[Step 4](https://github.com/CleverRaven/Cataclysm-DDA/pull/24989)** adds a zoo and I think with this new location a good addition would be a zoo keeper profession. It's not something I'm going to work on right now but thought I'd share the idea.

**Comment by AdonaiJr** [comment]
I think it's absolutely great, that we merge and balance map locations and buildings to vanilla. It's terrible confusing, even to the seasoned player, to chose and manually add the various buildings mods like "more locations", "more buildings", etc etc...

I think, if they fit the cata universe, they should just be merged. The more, the better, considering it's well made.

I personally have been trying various mapgen configs and mods to see what the overmap looks like. So this is just my 2 cents.

Unfortunatelly I don't fell confident to mess up with github to contribute to the PR's yet. But I'll keep a close look on all this!

Thank's everybody for the love and work to the game.

**Comment by ZhilkinSerg** [comment]
> If u merge lets say the boats mod he does what happens to peeps actually running the mod like me.

> Will I get a warning of double content or

Should be no issues.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
