### ISSUE TITLE
Two Straw Baskets can't be worn together

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [CleverRaven/Cataclysm-DDA#24933]
**Describe the bug**  
I decided to play some naked and afraid, when I realized while playing that I can't use the second basket I just made to expand my storage volume. I could wield it, but not wear it.

**To Reproduce**  
1: Construct two Straw Baskets
![image](https://user-images.githubusercontent.com/38237593/44296692-427c0780-a278-11e8-838a-82977b7f2088.png)

2: Attempt to wear both Straw Baskets.
![image](https://user-images.githubusercontent.com/38237593/44296704-6ccdc500-a278-11e8-97cb-7e64d1f462b4.png)

![image](https://user-images.githubusercontent.com/38237593/44296720-ba4a3200-a278-11e8-801a-400682a73629.png)

I have also attempted to swap the baskets position in my clothing menu, however this doesn't work. It would appear ONLY the left arm is usable for holding a basket.

**Expected behavior**  
Being that the other arm and hand is actually free, I should be able to pick up the basket, yet the game for whatever reason believes my arm to not be free. 

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-30684-gaca79b3 (tiles)
 - Graphics version: Tiles
 - Mods loaded [
  "dda",
  "More_Survival_Tools",
  "alt_map_key",
  "filthy_morale",
  "novitamins",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "dda-lua",
  "dda-lua-items",
  "dda-lua-skills",
  "dda-lua-traits",
  "Tolerate_This",
  "bio_mod",
  "FIC_Weapons",
  "realguns",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "nw_pack",
  "Mining_Mod",
  "mutant_npcs",
  "npc_traits",
  "national_guard_camp",
  "more_buildings",
  "cityside",
  "more_locations",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "necromancy",
  "StatsThroughSkills"
]

**Comment by Night-Pryanik** [comment]
How are you actually going to wear a two straw baskets?

**Comment by Night-Pryanik** [comment]
Maybe it's not _wearing_ basket, but _wielding_ them instead?

**Comment by SolsticeTheTechMarine** [comment]
The problem with wielding the basket is that it doesn't add to your carry volume. Wearing does however.

**Comment by cake-pie** [comment]
Also affects plastic shopping bag. Also "Covers: Either arm. Either hand." -- which definitely suggests you can equip one on each arm.

After wearing the first one, able to switch it to be worn between left/right sides, but still remain unable to wear a second one regardless.

**Comment by cake-pie** [comment]
From https://github.com/CleverRaven/Cataclysm-DDA/pull/24954#issuecomment-414506133 

> what this *needs* is for the code to track what each hand is occupied with, and various tasks require a different number of hands.
