### ISSUE TITLE
Guilty about killing chihuahua

### ISSUE THREAD

**Issue by Robik81** [CleverRaven/Cataclysm-DDA#24944]
**Is your feature request related to a problem? Please describe.**  
I am not feeling guilty about it. Besides, stupid dog attacked first.

**Describe the solution you'd like**  
Unless you pick trait like dog lover, don't feel guilty when killing dogs - especially in self defense

**Describe alternatives you've considered**  
I have considered feeling good about it, after all, I successfully defended myself from rabid dog attack.

**Comment by MT-Arnoldussen** [comment]
>Lastly, you can overcome the guilty check by killing such targets (including zombie children), from 5 or more tiles away

Is this intended behaviour?

**Comment by DracoGriffin** [comment]
>Is this intended behaviour?

Yes, as seen here in mondeath.cpp:
```cplusplus
void mdeath::guilt( monster &z )
{
const int MAX_GUILT_DISTANCE = 5;
    if( rl_dist( z.pos(), g->u.pos() ) > MAX_GUILT_DISTANCE ) {
        // Too far away, we can deal with it.
return;
```

which has been [around for 5 years](https://github.com/CleverRaven/Cataclysm-DDA/commit/856847b08ff9c223e3668378ce9264726d83e493#diff-8e1fd274b81d6c412036410bb8a4ebe0). One of the earliest versions I could find, anyway.
