### ISSUE TITLE
City names generating too close

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#24941]
**Describe the bug**  
Cities names are generating too close to each other, or perhaps multiple cities are spawning on top of each other. Not sure which.

**To Reproduce**  
1. Hard to say, probably make a new map and reveal lots of area.

**Expected behavior**  
One city name per established city

**Screenshots**  
On the left shows 2 city names for one city (from what it looks like)
On the right shows 3 city names for one city (from what it looks like)
![capture](https://user-images.githubusercontent.com/24307650/44299636-2f912380-a2c8-11e8-8643-d9e266496842.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Win7
 - Game Version: 0.c-30421 -gf615e24
 - Graphics version: tile
 - Mods loaded: none

**Comment by Break-Off** [comment]
Related to https://github.com/CleverRaven/Cataclysm-DDA/issues/24833

**Comment by CoroNaut** [comment]
Woops, I'm gonna close this one and reference it as an example in the first issue.
