### ISSUE TITLE
Unloading some liquids near vehicles does not fill vehicle

### ISSUE THREAD

**Issue by saladasa** [CleverRaven/Cataclysm-DDA#24946]
**Describe the bug**  
Until a very recent update it was possible to unload a liquid-filled container near a vehicle and be given the option to "fill nearby vehicle". The bug seems to only happen to certain liquids (purifier, mutagen, ammonia, bleach). I have several empty 100L barrels installed on my vehicle and several half-full barrels of the liquids in question.

**To Reproduce**  
1. Have a gallon jug of bleach or some other liquid in your inventory.
2. Press 'U' to unload and select your container.
3. ...

**Expected behavior**  
1. Have a gallon jug of bleach or some other liquid in your inventory.
2. Press 'U' to unload and select your container.
3. Select "Fill nearby vehicle..."

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-30684-gaca79b3
 - Tiles

**Comment by Break-Off** [comment]
Related issue. If you have a vehicle with an empty tank that could be filled after crafting a liquid, it isn't taken into account when doing the empty containers available check.
