### ISSUE TITLE
Disallow pickup of items underneath vehicle unless outside vehicle or item is under frame

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#24943]
**Is your feature request related to a problem? Please describe.**  
Idea brought on from #24926

**Describe the solution you'd like**  
Specifically to not allow the player to pickup items through the floor of the vehicle. If you are outside the vehicle, you can conceivably reach 1 tile underneath it from any direction.
If the item is underneath just a frame portion of the vehicle, then you can pick it up through vehicle.

**Describe alternatives you've considered**  
No alternatives.

**Additional context**
Going more indepth, pickup could be allowed if two vehicles are side-by-side to each other and you need to be in one vehicle to reach under the other.

**Comment by Break-Off** [comment]
This issue has been reported multiples times, such as https://github.com/CleverRaven/Cataclysm-DDA/issues/24743

**Comment by CoroNaut** [comment]
Hmm, surprised it hasn't been fixed yet then.

**Comment by Break-Off** [comment]
Because it's hard to fix. Certain parts of the code are an absolute mess, and the inventory one is one of the worst offenders.
