### ISSUE TITLE
Ammonia is able to freeze

### ISSUE THREAD

**Issue by Beanzy** [CleverRaven/Cataclysm-DDA#24955]
**Describe the bug**  
Ammonia in containers can freeze under normal weather conditions

**The freezing point of ammonia solution is around −77 °C**
- https://en.wikipedia.org/wiki/Ammonia
- https://en.wikipedia.org/wiki/Ammonia_solution

**To Reproduce**  
1) Start a new character on the first of Spring
2) Spawn or find a container of ammonia
3) The container of ammonia will eventually freeze

**Expected behavior**  
Ammonia shouldn't freeze under normal Earth weather conditions

**Screenshots**  
![impossible](https://user-images.githubusercontent.com/15885173/44302682-0d18fd80-a2fc-11e8-92e2-a83b6697abbf.PNG)

**Versions and configuration(please complete the following information):**
 - Windows 10 1803 x64
 - Game Version: Build 7714 0.C-30688-gce0effc
 - Graphics version: Tiles x64
 - Mods loaded: Default mod selection

**Comment by nexusmrsep** [comment]
Thanks for posting this issue. Some items will be added to the exclusion list, or will be checked for their freezing point. If you see any other of this kind please note them down here.

**Comment by ZhilkinSerg** [comment]
> or will be checked for their freezing point.

This would be nice.

**Comment by mrkybe** [comment]
@nexusmrsep hard alcohols shouldn't freeze either.

**Comment by communistkiro** [comment]
> Thanks for posting this issue. Some items will be added to the exclusion list, or will be checked for their freezing point. If you see any other of this kind please note them down here.

Don't be too severe if you implement freezing points! Diesel cars have a hard time starting, if at all, in the winter; become like a jell or sludge, and plain gasoline also needs some time to warm up, I believe.
