### ISSUE TITLE
Autodoc CBM installation does not reduce pain

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#24960]
As most here are probably aware, the process of installing a CBM requires an anesthetic kit powerful enough to knock you out, implicitly making it the most powerful single-use painkiller in the game. But in practice it doesn't even reduce pain by 1 point.

**Comment by kevingranade** [comment]
It's not a painkiller, its annanesthetic, those are totally different things.

**Comment by Rod995** [comment]
``Anaesthetic
1.
a substance that induces insensitivity to pain.``


``Painkiller:
a drug or medicine for relieving pain.``

**Comment by Regularitee** [comment]
Furthermore, there is an implicit understanding that it will wear off slowly (else additional painkillers will be administered) after surgery. 

After all, imagine you are cut open. Do you really think the pain only comes from when the knife hits your skin? That after an hour passes, that huge gash in your flesh will no longer give you pain because the knife is no longer there? Yet people can get up and move perfectly fine in game, suggesting that some sort of nerve-dampening is going on there.
