### ISSUE TITLE
The game plays shocker zombie attack SFX even while player is deaf

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#24961]
What it says on the tin. Either a shocker zombie or shocker brute,

**Comment by Night-Pryanik** [comment]
I don't know if it's a bug. After all, it's the player character who is deaf, not the player.

Or we don't play sounds for deaf player character everywhere?

**Comment by kevingranade** [comment]
The player only hears things the player character can hear.  If the player character is deafened, the game should not play any sound effects. (Yes to music though)
