### ISSUE TITLE
Bad vehicle placement at the barricade forcing them to phase-shift

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#24969]
**Describe the bug**  
Barricades allow vehicles to spawn on top of each other (in this case, a military cargo truck and an ambulance). Both seem to be occupying the same space simulatneously, cannot be dislodged due to frame collisions, attempts to uninstall parts of the one "under" uninstalls in turn parts of the other vehicle occupying the same tile. Siphoning of fuel is impossible (all menus appear normal but no actual fuel is transferred).

**Expected behavior**  
Vehicles do not spawn on top of each other and thus not lead to all the other issues

**Screenshots**  
![uhoh](https://user-images.githubusercontent.com/38487938/44307460-3e98d400-a3a3-11e8-9f87-c0c0f64660a9.png)

**Versions and configuration(please complete the following information):**
Game version: 0.C-30694
Operating system: Win7
Tiles or curses: Tiles
Mods active: More Survival Tools, Stats Through Skill, Vehicle Additions Pack, Tanks and Other Vehicles, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits, Extended Realistic Guns.

**Comment by kevingranade** [comment]
Weird, we have code to cause these to spawn as "wreckage" vehicles, no idea why it isn't happening here.

**Comment by Night-Pryanik** [comment]
Barricades (roadblock) mapgen was heavily enhanced and fixed not so long ago (#28278), anyone encountered this ever since?

**Comment by Night-Pryanik** [comment]
Closing as non-confirmed for more than half a year.
