### ISSUE TITLE
Mutated (Huge) anatomy can't wear splints.

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#24963]
The arm and leg splints do not fit huge anatomy.

I propose that we either add [OVERSIZE] to the existing splints or make large splints a separate item.

Personally, I think we don't need to add two more items. I'd rather keep what we have and make them work on large anatomy.

What is the consensus?

**Comment by Endovior** [comment]
I don't personally see a need to make [OVERSIZE] splints either; there's already enough item bloat in that regard.

**Comment by ZhilkinSerg** [comment]
Fixed in #24965
