### ISSUE TITLE
Drugs picked up from zombies have the status activated and stay that way in the  player inventory

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#24976]
**Describe the bug**  

The positive thing is, the drugs stay usable. So it is just a bug in presenting the information. My character is at health ~10. 2-3 asprin help him sleep. 
![3](https://user-images.githubusercontent.com/42423698/44310972-a836d380-a3df-11e8-9b70-278df62f4607.jpg)

**To Reproduce**  
Just kill zombies. Some of them carry theese activated drugs. I have found other drugs with that bug also.

![7](https://user-images.githubusercontent.com/42423698/44311005-2e531a00-a3e0-11e8-974c-4e9de8fbdf73.jpg)

**Versions and configuration(please complete the following information):**
 - OS: Win 7
 - Game Version : most up to date one via CDDA-Launcher
 - Mods loaded [various]

**Comment by nexusmrsep** [comment]
Solved in #24905. Have in mind that items that are already spawned that way will stay that way (with no consequences for the gameplay) till you use them up or replace with new ones. New ones will not get the flag.
