### ISSUE TITLE
Installing CBMs with Sensory Dulling keeps people awake

### ISSUE THREAD

**Issue by mlangsdorf** [CleverRaven/Cataclysm-DDA#24972]
**Describe the bug**  
If the player has the Sensory Dulling CBM and installs another CBM, they get the sleep effect for the duration of the CBM install, but not effect_sedated. If the player is in a bright room and well-rested, they will quickly (within 5 minutes) wake up from sleep and can install another CBM. If this process is repeated, the duration of the sleep effect stacks, but the player is awake. After many CBMs are installed, the player has the sleep effect with a very long duration but is awake, and will not sleep again until the sleep effect expires and they get tired again.

**To Reproduce**  
1. Make a player with First Aid 10, Computers 10, Electronics 10.
2. Debug in an Autodoc next to an autodoc couch.
3. Debug in an anesthesia kit, Sensory dulling CBM, a wrist watch, and 20 Power Storage CBMs.
4. Move player to the autodoc couch, examine the autodoc, and install the Sensory Dulling CBM.
5. Activate the Sensory Dulling CBM, then install the Power Storage CBMs. Notice that after the third or fourth power CBM, you're waking up after 2-5 minutes of sleep and can immediately install the next CBM.
6. Play the game for a few days, observing how long it takes for the player to need to sleep.

**Expected behavior**  
Player is asleep for 20 minutes per power storage CBM and is tired enough to sleep some 12 to 20 hours after installing the last CBM.

**Proposed Solution**
Either:
1. Player gets the sedated effect for the duration of the CBM install, whether or not they use a Sensory Dulling CBM
2. Player goes into a long action while the CBM is installed, to prevent them leaving the autodoc couch during installation. The autodoc might also get an effect (can furniture get effects?) that it is busy doing an install, preventing the player from rapidly installing the CBM.

**Comment by MT-Arnoldussen** [comment]
Can confirm, installed about 20 CBMs with Sensory Dulling, and stayed awake for about a week in-game.

**Comment by kevingranade** [comment]
Seems related to #24606
