### ISSUE TITLE
Make the food more sortable in the "E" menu. The presentation of information in it would benefit from an overhaul.

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#24975]
1.
**Is your feature request related to a problem? Please describe.**
Sometimes food at my food cooking place and even in my TV fridge gets spoiled because I just could no see it well in the huge list. The list gets big when you bring all looted food to one spot over time. It´s frustrating to see 9x or 19x cooked meat or 5x cooked offal go bad.

**Describe the solution you'd like.**
In the advanced inventory "/" items can be sorted by different categories. It would be nice if in the "E" menu food could be sorted by the category "spoils in".

![3](https://user-images.githubusercontent.com/42423698/44310865-aec44b80-a3dd-11e8-9b1d-9ebc848c2033.jpg)

2.
**Is your feature request related to a problem? Please describe.**
Also finding the most common drink -clean water- more visible in the menu is tidious every time when alot of drinks are around, like liqours and canned drinks.

**Describe the solution you'd like.**
A very nice solution could be to put clean water alsways at the bottom of the list.
You press E, to find the sorted food on top and the marked line is the most top line. When you now press UP once, you jump to the bottom of the list and have the clean water marked already. One only may have to choose then from what container the clean water shall be consumed.

Also two sections in the E menu could be interesting like one for eadibles and one for drinkables. Of which both can sorted to differently. Where clean water is as accessible to choose like the first line in the E menu just after opening the E menu. Remember, we use this alot, so make it fast for us. So that we playres can focus on the other great content in this game. [What have you experienced in the first 5 RL days of time in CDDA? -Eating and drinking.] ;-)

3.
**Is your feature request related to a problem? Please describe.**
Also sometimes not so healthy foods are in the list in E, like Lye. This is annoying especially when the player tries to store as much as possible in as few spots as possible.
Like one spot for all non food related items at the console in the evac shelter.
And one food spot at the fire with water access.
 
**Describe the solution you'd like.**
A more advanced E menu which is able to filter and also able to save the filter until changed would be great. Like the "/" menu can save the last choosen options like marked tile, Inventory, sort by category.
Im not so sure how the features could be shaped in detail. The "/" is great for an otherwise textbased game with it´s A, I, 1, 2, 3, 4, .... options. Maybe the same guy can come up with an in detail solution.

![5](https://user-images.githubusercontent.com/42423698/44310883-02cf3000-a3de-11e8-95fb-7c9ecbf0e317.jpg)
Picture 2: I have choosen this place for cooking as the wooden barrel outside has a funnel and the water is always available without walking to pick it up. The pit outside the door was my firepit before. So all the Lye and chemicals which need fire are at the til outside in front of the door. It is the old place from when I used the firepit outside.

![6](https://user-images.githubusercontent.com/42423698/44310918-a28cbe00-a3de-11e8-8107-dc1a579cef2f.jpg)
Picture 3: Clean water is just to far in the list on page 2 of 2. Put clean water always at the bottom, could be a fast solution.
Also Lye is in the list jsut above the clean water.

**Comment by CoroNaut** [comment]
Additionally, if you raid a vending machine full of snacks and unload all the bags of food (can't wait until the bulk unload option gets implemented), they all stack separately and you have to shift-E to eat all of them one by one. If they were to all stack, you could just wield them and activate the stack over and over to eat lots much more conveniently.

**Comment by Break-Off** [comment]
Workarounds found in my runs are sorting consumable items (i.e. drugs and food) far away from each other so they don't stack in the 'E' menu; other one is using AIM sorting function that sorts a tile by spoilage times.

**Comment by Androwski3000** [comment]
@ Break-off: good tip. E is used most of the time for eating and drinking. Keeping the sorting focus based is good to get the list down to the wanted items.
Bandages are in there also because they are classified as drugs.. Which are covered in a for activation menu already.

4.
**Is your feature request related to a problem? Please describe.**
Freshly cooked or warmed up food is in the middle of the list. The item is proced for a reason - Eating/Consuming. Having to fumble around to mark it with the cursor in the middle of the list is annoying, even more if a stack shall be consumed. Most item dont get a number or a letter in front for fast access.

**Describe the solution you'd like.**
Make the menu more accessible by changing the sorting so that faster access is possible. This would mean to put items with the status (HOT), (FRESH), (PLACEHOLDER) on top.
