### ISSUE TITLE
Your bug report has to include: "This data" -> Make it available for Ctrl+C, Ctrl+V

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#24999]
**Is your feature request related to a problem? Please describe.**  
There is a chance to make bug reports more efficient for the reporter.
Motivated to contribute to make the game better and help it growing brings some repeating tasks with it. Providing the following data is a repeating task.

From the ISSUES.MD:

Your bug report has to include:

On what OS did you experience the problem (Windows, Linux, OS X etc.)
What version were you playing:
Tiles or Curses (text-based)
Version string (preferably full version e.g. "0.C-4547-g3f1c109", or Jenkins build number e.g. 3245)
Description of the problem written in a way that enables anyone to try and recreate it

**Please make this as easy for us as possible.**

**Describe the solution you'd like**  
Make a text field within the main menu, which has as much of the requested data available and formated so that we can just click into it to press Ctrl+C to get the data.
The information shoudl be:
-OS (if this isnn´t easy to extract, well for my case WIN7 is typed in fast),
-version (that code in the main menu under the title),
-Jenkins build number,
-tileset.
-list of active mods.

**Describe alternatives you've considered**  
On modern successful games it can be common that they have a "Feedback" Button or a similar function to make give feedback easy for the user/player.

-COSMOTEER has a function, where you can give feedback at any time in the game by pressing "F8"  if I remember right. The developer even answers to you by e-mail.

-GRAVEYARD KEEPER has a "Give Feedback" button in the main menu.

![g1](https://user-images.githubusercontent.com/42423698/44335840-ec74b300-a475-11e8-86a0-7884a70cbc39.jpg)

**Comment by CoroNaut** [comment]
The list of active mods is per world and not for all worlds simultaneously. Would probably work as a debug menu button to output to a file or just overwrite your clipboard. Or just get the list of mods separately in some way.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
