### ISSUE TITLE
Triffid queens produce infinite wood products

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#24996]
**Describe the bug**  
When a triffid queen uses their ability to shape shift the land, they break all their surroundings and pretty much randomly generate a new terrain around them. However, when they do this, everything breaks into sticks and can result in thousands upon thousands being generated.

**To Reproduce**  
1. Goto triffid grove or spawn triffid queen
2. Get mass amounts of wood

**Expected behavior**  
The triffid queen produces some sticks, but the ground doesn't have infinite nutrients to produce infinite trees. Perhaps only allow a small amount of sticks to pile up instead of thousands.

**Versions and configuration(please complete the following information):**
 -OS: Windows 7
 -Game Version 0.C-30421-gf615e24
 -Graphics version tiles
 -Mods loaded none

**Comment by FulcrumA** [comment]
I frankly don't mind nearly infinite growth of trees. What bothers me is that those growing trees are more effective than anti-armor tank shells against vehicles - when set to grow under even an armored car, they will break it in a matter of a few turns. I wouldn't mind fewer trees breaking up into stick when new ones are grown in their place though.

**Comment by CoroNaut** [comment]
I don't care about the infinite growth of trees either, the issue is about the fact that the resources that go into into those trees are just dumped into thousands upon thousands of sticks and the nutrients from the ground are drained pretty much instantly. If the sticks can be limited to a reasonable amount, one would assume that the sticks are morphing into new trees or very rapidly being decomposed.
