### ISSUE TITLE
canned food going rotten as soon as opened

### ISSUE THREAD

**Issue by Taybabie** [CleverRaven/Cataclysm-DDA#25001]
**Describe the bug**  
as of experimental build #7719, after opening a can of food it will rotten. Example: I opened a can of veg soup do to expire 5 days after opening. I ate the first serving of 4. I went to eat the next serving (I was very Hungry), the rest of the can was listed as rotten. This happened with the other 2 cans I opened as well. They were both meat.

**To Reproduce**  
1. Open a can of food, (I am assuming open it awhile after you found the can? I collect everything and keep the can goods until I don't have anything else blue/fresh to eat.)

**Expected behavior**  
I had expect the Items in the can to last the 4 or 5 days as it stated after opening it, not for the food to go rotten after the first bite.

**Screenshots**  
N/A

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version  0.C-30730-g4101dba
 - Graphics version Tiles
 - Mods loaded dda, Filthy Clothing, Disable NPC needs, simplified nutrition, extended realistic guns, Icecoon's arsenal, Medieval and Historic content, More survival tools, alternate map keys, boats, folding parts pack, vehicle additions pack, remove nether creatures, Mundane zombies, no acid zombies, no explosive zombies, no fungal monsters, classes and scenarios mod, prevent zombie resivication, StatsThroughSkills

**Additional context**  
N/A

**Comment by nexusmrsep** [comment]
And it doesn't drop open tin cans after eating.
There must be something specific somewhere, as main spoilage protection code is in place as it were, in `item::process`.

**Comment by FulcrumA** [comment]
Completely a shot in the dark - but is it possible that, since spoilage is tracked on the basis of dates, that the food inside the can is also tracked this way? That'd explain why it's not rotten till the can is opened, adjusting content's spoilage time and turning it instantly spoiled as it gets updated on the basis of the date it was acquired on (as if it'd be opened since then all that time).

**Comment by nexusmrsep** [comment]
> And it doesn't drop open tin cans after eating.
Actually after re-testing this happens to be my error on my testing procedure - I spawned myself a canned meat **without** the can, so no wonder it was rotting. Spawning tin can of canned food, and canned food made be recipes don't follow this pattern - nothing rots unless opened. Opened and not fully consumed leftovers rot properly starting from the time their container was opened.

@FulcrumA have you seen this behavior described in this issue first hand?

**Comment by KorGgenT** [comment]
Spawned a dozen cans of meat, unloaded one of them. Waited until the first one rotted, then unloaded a new can of meat. It was still fresh. Did this for ~95 in game days, cans of meat are still fresh. I'm pretty confident in saying that this is fixed.

**Comment by kevingranade** [comment]
If anyone can reproduce this please reopen, but for now we'll assume it was adressed.
