### ISSUE TITLE
Zeds spawning "outside" on 2nd floor at Mansions and Apparments

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#25006]
**Describe the bug**  
Enemies in higher Z levels (like in mansions / appartments) can spawn "outside" the building, literally in the "air". These enemies instantly die as soon you enter the Z level. Even sound pack generated noise for their deaths.

**To Reproduce**  
1. Go to the second level of a Mansion or Appartment
2. Open Windows and explore outside, sooner or later you'll find corpses and loot "floating" outside the building.

**Expected behavior**  
Make them either not generate if the RNG decided to place them in a tile without floor.
Or alternatively, make them always spawn in a tile with a floor.

**Screenshots**  
![20180820_133103](https://user-images.githubusercontent.com/1426680/44353451-66f50100-a47d-11e8-9c7a-9e0ff31674fb.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-30348-gd15b309
 - Graphics version: Tiles
 - Mods loaded:
[ "dda", "filthy_morale", "no_npc_food", "novitamins", "bio_mod", "ew_pack", "makeshift", "Medieval_Stuff", "More_Survival_Tools", "mutant_npcs", "more_buildings", "more_locations", "boats", "deoxymod", "blazemod", "Tanks", "no_religious_Texts", "more_classes_scenarios" ]

**Comment by Petethegoat** [comment]
Probably fixed by #33244, if it wasn't a different older bug.

**Comment by kevingranade** [comment]
Please comment if you see this again.
