### ISSUE TITLE
Re-Layer Armor/Clothing - "+" menu overhaul

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#25003]
**Is your feature request related to a problem? Please describe.**  
There is a chance of flattening the learning curve of the game regarding clothes management. People like the streamer Vormithrax have 1000h+ in the game. They have worked around the current difficulties by investing ALOT of time. Reoptimizing clothes can take easily 1h ore more for a new player after every some ingame days with new recipes and findings. WTF!!!

Content:
**Stage 1**: Overhaul of presentation of information with focus on the left column (All, Torso, Head, Eyes, etc.)

**Stage 2:** **Linking to:** Inventory, Surounding (3x3 tiles, like in "7" menu or like access for water at cooking is available multiple tiles away, craftables available right now, craftables with missing resources) or  **Let´s talk about that ".".** 

**Stage3: Make the items craftable in the Stage 2 menu right away like as a part of  "&" menu. With option of wearking "W" via Y/N promt right way.**

Not included:
Encumberance, This was covered here already. #23425

**Stage1: Overhaul of presentation of information with focus on the left column (All, Torso, Head, Eyes, etc.)** 
Let´s start with a screenshot:
![re1](https://user-images.githubusercontent.com/42423698/44337806-31034d00-a47c-11e8-8ae3-c3bccede5648.jpg)
Picture1: I use a 19" screen with 1280x1024 resolution.

To find out about layers of clothing is difficult right now. You need to find forum posts, discord, the wiki and do alot of ingame menu crawling to learn about that.

'Next to the Skin'
'Tied around the waist'
'Default'
'Strapped to you'
'Over your other clothes'
[http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Clothing](url)
The data out there is out of date also. The layer 'default' is called 'Normal' right now in game.

My 19" screen is smaller than what most people use nowadays. But there are people who use laptop screens, etc. which are even smaller than what I have. So usage of more screen surface for the overhaul should be prevented.
Also as the << All >> list is very long. The following suggested improvements could clutter the << All >> list. It is right now a "fitting on one screen" solution. Scrolling in this "+" menu with TAB right now is very crude. Experimentation with better scrolling within << All >> with PAGE UP, PAGE DOWN keys could be needed.

So right now I talk about the other 12 sections of this menu, from << Torso >> to << R. Foot >>.

Right now the clothes which have been put on, snap to a position in the list, regarding the order they have been put on (or randonly?).
![re2](https://user-images.githubusercontent.com/42423698/44339086-55f9bf00-a480-11e8-9bca-a477570260d5.jpg)
Picture2: Items snap to wherever they like to.

**The issue:** Make layering here strict or not strict regarding (innermost) - (outermost) layers.
While wearing socks over boots is possible, who does that? On the other hand wearing a raincoat over you MBR vest, keeps everything dry but access to magazines is bad. Wearing the MBR vest over the raincoat gets you wet and uncomfy but access to magazines is faster.

What is the benefit of having the socks outside? Can the player choose that way, what item get´s damaged first on a hit, in the case  or Picture 2 the socks before the shoes?

If mixing clothes from different layers give this (what is damaged first) and other gameplay options, this should be kept.
As a base or rule of thump, clothes on putting them on should always "snap to their layer first" like when used from the inventory screen via W or in wolrd view via W.

The decission here is influential for future gameplay fun. More options are better.

For presentation of information in the left column there should be 2 different options for layering then. **"Strict"** and **"Free mode"**

*The names **"Strict"** and **"Free mode"** are placeholders until better therms become available.

**"Strict"**: Clothes snap to their position,
**"Freemode"**: The player decides per bodypart how the layer should be (Like stockings over the cargo pants).

**Example for  "Strict":**

This is a foot naked:
<< L. Foot >>
(Close to skin)
.
(Tied around the waist)
.
(Normal)
.
(Strapped on to you)
.
(Over your other clothes)
. 

Now a pair of socks is put on from whatever menu. Notice the "." below the pair of socks
<< L. Foot >>
(Close to skin)
Pair of socks
.
(Tied around the waist)
.
(Normal)
.
(Strapped on to you)
.
(Over your other clothes)
. 

The player could now choose this point in the menu to choose another item, like a pair of stockings or a pair of boots.
<< L. Foot >>
(Close to skin)
Pair of socks
Pair of stockings
(.)
(Tied around the waist)
.
(Normal)
Pair of boots
.
(Strapped on to you)
.
(Over your other clothes)
. 

Notice that the **"."** turns into **(.)** when a layer is full. AFAIK 2 items is the limit. **The "." is an indicator for an available slot, which also leads to a menu. A new menu! This is covered in //Stage 2//. See Content above**.
On a 'full' layer the "." turns into a grayed out (.) with a text in the info part saying: "Layer is full", when the player has the cursor over (.). That is actually better for the player as he now knows that the layer is full and do not has to guess  what is happening.
[There is that occurance, when you try to put on a 2nd helmet and it does not work.]

![re5](https://user-images.githubusercontent.com/42423698/44344774-ceb54700-a491-11e8-8a0c-e5dfd023d01d.jpg)
Picture 3: Example - Full layer

![re6](https://user-images.githubusercontent.com/42423698/44345195-e8a35980-a492-11e8-959f-9671617f8dfc.jpg)
Picture 4: Example - Add item

**On << ALL >>:**
Implementation of the layers (Close to skin) into << ALL >> is benefitial I think. As right now the items get sorted by which order they have been put on. The layer names increase clear presentation of info. With good scrolling this will work!

![re7](https://user-images.githubusercontent.com/42423698/44347696-c7456c00-a498-11e8-8580-dfd437467784.jpg)
Picture 4: Addition of layers to << All >>.

**New features in Stage 1:
-Clear listing of layers in "Strict" mode with "." indicating a free slot, -> Impementation in <<Torso>>, <<Head>>, <<Eyes>>,<<Mouth>>,  <<L. Arm>>, <<R. Arm>>, <<L.  Hand>>, <<r. Hand>>, <<L. Leg>>, <<R. Leg>>,<<L. Foot>>, <<R. Foot>>,
-Implementation of scrolling via PAGE UP, PAGE DOWN for <<All>>  for aneasy access to information,
-Addition of layer names to <<All>> like (Close to skin). Within layer sorting from body part head to foot on order of the listing accecible  with LEFT, Right, <, >.
-Freedom of layering per bodypart category (Head, Arms, legs, hands) by player desision; this shall mean the player can switch off "Strict" mode by sorting items like he wants as available right now,
-Clear indication that "Strict" mode was disabled, like [A],  [1-9], [I] in "7" menu.
-The "." leads to a specific new menu.**

**I have no idea how "free mode" could implemented. Maybe with (!) at the front of the item.**

**Stage 2:** **Linking to:** Inventory, Surounding (3x3 tiles, like in "7" menu or like access for water at cooking is availablemultiple tiles away, craftables available right now, craftables with missing resources) or  **Let´s talk about that ".".** 

To find a good and working clothing configuration, it takes a long time. You need to check and compare:
-own inventory,
-different storage spots,
-items available for crafting,
-items not available for crafting, because ingredients are missing,
-missing ingredients
-find out how to get filthy things clean with water source, soap, detergent, washboard etc.

That´s is a alot of effort needed.

Behind "." will be a new menu with already known and common features and new features:

**Content of the menu based of the Bodypart and Layer where you have selected a ".":**

-INVENTORY
-1NE, 1SE, 5SW. --->Surrounding, [like one tile around character with 1NE format
 or when cooking clean water the water barrel with the funnel can be several tiles away, format here maybe 5NE for example],
-CRAFTABLE ITEMS,
-CRAFTABLE ITEMS WITH MISSING RESOURCES,
-[*] NON MEMORIZED RECIPES NOT LISTED - CHECK BOOKS WITH NON MEMORIZED RECIPES ---> This line eleminates player confusion of why an item he has seen before is not listed anymore.

**Example:**
Let´s say you have pressed ENTER with the cursor on "." at:
<<Torso>> (Close to skin)

You get:

INVENTORY
Gambeson

1NE
Chestwrap

CRAFTABLE ITEMS
Chestwrap
Leather Chestwrap
"all the other craftables for <<Torso>> (Close to skin) from "&" menu"

CRAFTABLE ITEMS WITH MISSING RESOURCES
"all the greyed out things from "&" menu"

**New features in Stage 2:
-New menu to fit out "." slots of "+" menu.**

![re8](https://user-images.githubusercontent.com/42423698/44350090-cdd6e200-a49e-11e8-8f36-602609d0029f.jpg)
Picture 5: Example for menu behind ".".

**Stage3: Make the items craftable in the Stage 2 menu right away like in "&" menu. With option of wearking "W" via Y/N promt right way.**

Make the items craftable in the Stage 2 menu right away like in "&" menu. With option of wearking "W" via Y/N promt right way.

**Comment by Human-Shield** [comment]
Optimizing clothes is a big time sink now. Probably why most people play with survivor suits and just shortcut thinking about it. The screen also doesn't explain what the penalties on each body part are, I have to keep a wiki tab open and then I'm still not sure if the system is still in units of 10 (no difference between 10 and 19 encumbrance). New players don't assume that torso effects melee accuracy but that a bindle that puts one arm at 100 doesn't. 

I never understood why layers aren't enforced, there are some gray areas but now there is no penalty to wearing plate armor or a leather chest wrap over a backpack.

Need to move away from suits and towards armor sets.

**Comment by HeadWar** [comment]
The sort order definitely affects in what order items can get hit and damaged. Currently it's pretty much mandatory to move less resilient items such as backpacks to the inner layers, especially when fighting monsters that often damage your clothing. (I'm looking at you, nasty giant cellar spider.)

I am all for forcing the layers to be in a realistic order, no more wearing your duffel bag beneath your skintight kevlar vest, but there might be balance issues that need to be addressed.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
