### ISSUE TITLE
Hemostatic powder is a touch too powerful

### ISSUE THREAD

**Issue by HeadWar** [CleverRaven/Cataclysm-DDA#25016]
Hemostatic powder has a 9000% chance to stop bleeding. Someone obviously wrote 90 instead of 0.9 for "bleed"

Also, it currently has a "disinfectant_power" of 4. I'm not sure if this is intentional, but I can't see why it should have any disinfecting qualities.

 - OS: Windows 10
 - Game Version: 0.C-30694-g828aaad]
 - Tiles

**Comment by Treah** [comment]
I agree I cant find any reference to this type of item IRL that has any disinfecting qualities.
