### ISSUE TITLE
Road maps can be used by illiterate characters

### ISSUE THREAD

**Issue by ianestrachan** [CleverRaven/Cataclysm-DDA#2502]
On the one hand, a map reads differently from a book... on the other hand, an illiterate character wouldn't be able to read any of the names of locations or places of interest on the map. Illiterates probably shouldn't be able to use road maps at all.

**Comment by sparr** [comment]
@ianestrachan I am certain that I could use a chinese road map to find my way around china today as well as I could use an english map to get around the US when I was 10. Which is to say, plenty well enough for finding things after the apocalypse :)
