### ISSUE TITLE
Paper can freeze

### ISSUE THREAD

**Issue by Xhuis** [CleverRaven/Cataclysm-DDA#25023]
**Describe the bug**  
Paper is treated like food in that it is capable of freezing.

**To Reproduce**  
1. Get in a cold place or use a minifreezer.
2. Behold as paper freezes solid.

**Expected behavior**  
Paper does not freeze in real life, and it's silly that it does here.

**Screenshots**  
![](https://i.imgur.com/4yhBhPo.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 7720
 - Graphics version: Terminal, but not relevant
 - Mods loaded: None beyond default

**Comment by Night-Pryanik** [comment]
> Paper does not freeze in real life

All freeze if temperature is low enough.

**Comment by nexusmrsep** [comment]
Solution same as for #24955. I will develop some kind of exclusion check.

**Comment by Rivet-the-Zombie** [comment]
What about freezing temperatures being defined in json for different materials/items?

**Comment by Someoneman** [comment]
For some reason, paper is considered to be food, which is why it's freezing. I'm not sure what the nutrition stats on paper accomplish.

**Comment by communistkiro** [comment]
> Everything freezes if temperature is low enough.

Paper is already a solid phase, in a way, would could call default room-temp/pressure paper frozen.
