### ISSUE TITLE
Minefield can spawn on top of house and will remove part of it

### ISSUE THREAD

**Issue by maniak1349** [CleverRaven/Cataclysm-DDA#25036]
Windows, tiles, 0.C-29661-g765578f.
Mods: dda, no_npc_food, novitamins

Minefield can spawn on top of the house and will remove part of it in process. It's fine to have mined houses but they should not turn into swiss cheese in process.

![cata_mines_house](https://user-images.githubusercontent.com/2755776/44424818-b882b600-a579-11e8-9131-083d33901f4b.PNG)

**Comment by CoroNaut** [comment]
I've seen a minefield on top of an electronics store. Darn shame because I needed batteries :smile:

**Comment by ZhilkinSerg** [comment]
Should be resolved with #28195.
