### ISSUE TITLE
Smoking rack adds wrong raw items

### ISSUE THREAD

**Issue by DarkDaskin** [CleverRaven/Cataclysm-DDA#25040]
**Describe the bug**  
When there are multiple smokable items available, the smoking rack will ask which item to add, but then will sometimes ask for count of a different item. Only then there is only one item type is available, the item will match the choice.
The buggy feature was introduced in #24307.

**To Reproduce**  
1. Build a smoking rack.
2. Place multiple kinds of smokable items to adjacent tiles, e.g. _meat_ and _raw potato_.
3. Select _Insert foods for smoking_.
4. Select the second item from the menu, e.g. _raw potato_.
5. You will be asked how much _meat_ to add, then _meat_ will be added when confirmed.

**Expected behavior**  
The item selected on step 4 should be added to the rack.

**Versions and configuration(please complete the following information):**
 - Windows 10 x64
 - Game Version 0.C-30764-g1bb4be6
 - Graphics version: Tiles
 - Mods loaded `[
  "dda",
  "Experimental-Z-Level",
  "More_Survival_Tools",
  "blazemod",
  "Tanks",
  "Urban_Development",
  "boats",
  "filthy_morale",
  "makeshift",
  "more_buildings",
  "more_locations",
  "mutant_npcs",
  "national_guard_camp",
  "npc_traits",
  "craftgp",
  "brightnights",
  "bio_mod"
]`

**Comment by nexusmrsep** [comment]
In other words you chose **potato** and then it asked you from where to put **meat** in the rack?

**Comment by DarkDaskin** [comment]
Yes. There is no visible pattern in this behavior. Right now I have the following choice -> ask mapping:

- Salad -> salad
- Raw potato -> salad
- Smoked meat -> raw potato
- Fried seeds -> raw potato

Possibly the outcome depends on physical item location, they are scattered all around my base.
