### ISSUE TITLE
Remote vehicle controller does not work with battery compartment mod

### ISSUE THREAD

**Issue by DarkDaskin** [CleverRaven/Cataclysm-DDA#25041]
**Describe the bug**  
Remote vehicle controller reports empty batteries when a battery compartment mod is installed with a charged battery.

**To Reproduce**  
1. Install a battery compartment mod to a remote vehicle controller.
2. Reload with a fully charged car battery.
3. Try to control a remote-controllable vehicle.
4. The remote vehicle controller will consume one charge and then tell that the batteries are out and abort control.

**Expected behavior**  
It should control the vehicle continuously, just like it does with conventional batteries.

**Versions and configuration(please complete the following information):**
 - Windows 10 x64
 - Game Version 0.C-30764-g1bb4be6
 - Graphics version: Tiles
 - Mods loaded `[
  "dda",
  "Experimental-Z-Level",
  "More_Survival_Tools",
  "blazemod",
  "Tanks",
  "Urban_Development",
  "boats",
  "filthy_morale",
  "makeshift",
  "more_buildings",
  "more_locations",
  "mutant_npcs",
  "national_guard_camp",
  "npc_traits",
  "craftgp",
  "brightnights",
  "bio_mod"
]`

**Comment by Marrim** [comment]
It is possible that this bug extends to other tools.
I could not assemble my L523 with a gunsmithing kit until I removed the battery compartment mod from the kit.

**Comment by DarkDaskin** [comment]
@Marrim This did not reproduce for me. Did you have a charged battery installed?
