### ISSUE TITLE
Bismuth needs some love

### ISSUE THREAD

**Issue by cake-pie** [CleverRaven/Cataclysm-DDA#25046]
**Is your feature request related to a problem? Please describe.**  

The item "bismuth" exists:
> `bismuth` in `/items/resources/metals.json`
> "A dense but brittle metal often used as an alternative to lead."

However, it currently does not (yet) serve any meaningful gameplay purpose:
- it only appears in recipes as a 1-for-1 alternative for lead
- there are few sources for it (e.g. disassembly of pro fishing rod and a couple of ammo types)

In contrast, gold and silver, which are also lead-substitutes e.g. in `ammo_bullet` in `/requirements/materials.json`, have a multitude of other sources and uses.

**Describe the solution you'd like**  

Give bismuth more distinctive uses, and maybe add a few more ways to obtain it.
Medical uses might be a good place to start.

**Describe alternatives you've considered**  
https://github.com/CleverRaven/Cataclysm-DDA/issues/24843#issuecomment-414644513 : Considered removing it / merging it into lead if it does not have any distinct recipe use other than as a lead substitute.

-----

## Possible sources

* [ ] pink bismuth (pepto-bismol)
   * chemical extraction ([youtube](https://www.youtube.com/watch?v=grpSfjUImUs))
   * burning at sufficiently high temperature

-----

## Possible uses
Keeping a list to track various options for discussion; checking off when implemented / rejected.

### Medical
Need people with a background in med / pharm / chem to look into these and their recipes.

* [ ] anesthetic: implementation ongoing at #24567

* [ ] This exists: "antiseptic powder" `bfipowder` -- "A powdered form of chemical disinfectant, this bismuth formic iodide cleans wounds quickly and painlessly."
   * need someone knowledgeable to look into adding a bismuth component to the recipe.

* [ ] digestive tract issues
   * needs diseases implemented to justify having the cures.
      * diarrhea: dirty water, uncooked/unheated food
      * indigestion: caused by overeating, eating too quickly, eating high-fat foods, drinking too much alcohol or coffee
      * heartburn (gastroesophageal reflux disease / other gastrointestinal disorder) -- don't really seem suitable for in-game implementation
   * drugs:
      * Pink bismuth (Bismuth subsalicylate aka Pepto-Bismol) is an antacid ...  used to treat diarrhea, indigestion, heartburn and nausea. ([wikipedia](https://en.wikipedia.org/wiki/Bismuth#Medicines))
      * "Milk of bismuth" (an aqueous solution of bismuth hydroxide and bismuth subcarbonate) was marketed as an alimentary cure-all in the early 20th century ([wikipedia](https://en.wikipedia.org/wiki/Bismuth#Medicines))
      * Bismuth carbonate (Bi2(CO3)3) is used to treat diarrhea and gastric ulcers. ([source](https://education.jlab.org/itselemental/ele083.html))
      * Bismuth Subcarbonate (BiO)2-C-O3 : Antacid, antidiarrheal, topical astringent ([source](https://www.drugs.com/international/bismuth-subcarbonate.html))

### Alloys / Metallurgical
Not sure if metallurgy should have a significant place in the game.
Of course, metallurgy -> new materials -> need to find uses for those too!

* [ ] solder -- already exists, could look into making it craftable.

* [bismuth bronze](https://en.wikipedia.org/wiki/Bismuth_bronze) is a suitable "simple" alloy if some basic metallurgy is allowed

* specialty alloys ( [1](https://en.wikipedia.org/wiki/Bismuth#Other_metal_uses_and_specialty_alloys), [2](https://www.livescience.com/39451-bismuth.html) ) unlikely that we're going into that level of detail
   * Bismanol, an alloy of bismuth and manganese, is a permanent magnet of high coercive force (a measure of magnetization) ... It was used in small motors. ([source](https://www.livescience.com/39451-bismuth.html))

### Pigments, cosmetics
I don't think so, unless someone can make a really compelling case.

### Catalyst
Most likely too complex/detailed for inclusion in the game.
* bismuth compounds are used as catalysts in the manufacturing process of synthetic fiber and rubber ([source](https://www.livescience.com/39451-bismuth.html))
* an electrocatalyst in the conversion of CO2 to CO ([wikipedia](https://en.wikipedia.org/wiki/Bismuth#Other_metal_uses_and_specialty_alloys))

**Comment by cake-pie** [comment]
That was my inclination as well, but Kevin https://github.com/CleverRaven/Cataclysm-DDA/issues/24843#issuecomment-414901703 :
> Bismuth is distinct chemically, and is potentially very useful in that role.

So I figured let's give it a chance, see if anyone has ideas for something useful to do with it.

**Comment by cainiaowu** [comment]
Just check the json, I dont think you can current get bismuth item at all, the only way get one spawned is in "npc_misc" itemgroup which I believe is made via some scripting.

Again, we dont need to bloat the json as they are already very bloated.

**Comment by bananaedmonkey** [comment]
As far as I can tell its uses are:

1. Catalysts for rubber and some other synthetic materials
2. Alloys with low melting points
3. Makes fairly powerful magnets
4. replacement for lead


Sources:
https://www.livescience.com/39451-bismuth.html
www.rsc.org/periodic-table/element/83/bismuth

**Comment by kevingranade** [comment]
As it turns out, #24567  uses it.

Generally, "bloat" is not a reason to remove anything.
