### ISSUE TITLE
Taekwondo block bonus applies to weapons.

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#25042]
The block bonus of taekwondo is being applied to melee weapons. Making weapon blocking while having the style taekwondo on very powerful.

**To Reproduce**  
making test character, set all skills to 3 via debug (optionally except dodge to make blocking happen more often), set style to taekwondo, remove all armor, wield a medium blocking capability weapon such as steel spear. go near a normal zombie and wait. You should see the message "blocking most damages", set style to no style, and the message change to "blocking some damages"

I believe this is happening due to the "force_unarmed" flag of the taekwondo style. One possible fix is to add
"strictly_unarmed" : true
to the block buff section, but this nerfs taekwondo unarmed block ability when wielding weapons without weapon blocks, such as ranged weapons

**Comment by aierce** [comment]
so it seems Muay Thai is forced unarmed style too, it's damage buff is likely applied to melee weapons too in theory, but i have not tested this

**Comment by Mooses2k** [comment]
#30668 might fix this. I'll test.

**Comment by Mooses2k** [comment]
Appears to fix it, but I'm not expert enough with stats and the debug mode to tell for certain.
