### ISSUE TITLE
Acid ants still produce too much acid

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#25054]
**Describe the bug**  
Acid ants produce far too much acid despite changes in the past to alleviate it. An average ant is able to produce whole pools worth of stuff on its own, leaking it at the speed and in quantities suggesting eldritch, reality-bending dimensions of the inside of its body.

**To Reproduce**  
1. Find acid ants.
2. Provoke acid ants.

**Expected behavior**  
Acid ants produce acid in very low quantities, comparable to that of acidic zombies.

**Screenshots**  
![too much acid](https://user-images.githubusercontent.com/38487938/44474114-27bbe100-a632-11e8-89e5-6519dacbec34.png)

**Versions and configuration(please complete the following information):**
Operating system: Win7
Game version: 0.C-30780
Tiles or curses: Tiles
Mods active: More Survival Tools, Stats Through Skill, Vehicle Additions Pack, Tanks and Other Vehicles, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits, Extended Realistic Guns.

**Comment by MT-Arnoldussen** [comment]
Is this not intentional? I assumed it was, and think their snail-like behaviour is kind of amusing.

Makes them more than just reskinned Spitter Zombies too, although in the end unless you're purposefully gonna walk in their trail it doesn't really matter I suppose.

**Comment by FulcrumA** [comment]
The feature is intentional, the quantities were already balanced in the past as excessive and they kinda still are. Acid trail here and there is fine. A single ant producing so much acid that it's doubtful it has enough space to store it is a stretch. I can understand, though I still think it needs adjustment, that you have to waddle somewhat through acid in the acid ant hive, but making whole pools of it outside is a stretch.

**Comment by Endovior** [comment]
As a point in the "this is way too much freaking acid" column, cheat yourself up some clairvoyance, and teleport yourself into a position from which you can observe acid ant tunnels. You will find that the acid ants accidentally murder most of their own larvae very quickly, just by wandering around.

I'd support Acid Ants being nerfed to Acidic Zombie status; dangerous up-close, where they offensively drop acid attacks, but not a swarm of trails of destruction.

**Comment by I-am-Erk** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/26896
