### ISSUE TITLE
Crashed Helicopter Vehicles Lack Ejection Seats

### ISSUE THREAD

**Issue by mrkybe** [CleverRaven/Cataclysm-DDA#25052]
**Is your feature request related to a problem? Please describe.**  
Death-mobile hopelessly surrounded?  **NOT A PROBLEM!**
NPCs says mean words to you?  **NOT A PROBLEM!**
Zombie hulk suddenly riding shotgun?  **NOT A PROBLEM!**

**Describe the solution you'd like**  
Pressing a button creates a lot of smoke, noise, fire, and the problem is resolved.

**Describe alternatives you've considered**  
Considered not having ejection seats, found it wanting.

**Additional context**  
In all seriousness, I plan to add these myself, but I want some community input and to collect all of the special cases that'll need to be addressed for them to work well.

**General Plan / Requirements**
- Ejection seats will only be found in the co/pilot seats of crashed helicopters.
- Ejection seats can be salvaged and reinstalled in a vehicle of choice.
- Ejection seats will be activatable from anywhere on the vehicle where you can activate electronics.
- It is recommended that there not be a roof above the ejection seat, though not enforced.
- An ejection hatch will be installable.  It'll require some explosives to do so and will remove any existing roof upon ejection.
- It is recommended that there be a seatbelt/5-point harness, though not enforced.  In such a case, the ejectee must supply their own parachute.
- Ejecting underground/inside a building produces the expected result.
- Ejection seat has a storage compartment that comes with it when you eject.  Includes a survival kit and some MREs by default, player can add/remove stuff prior to use.
- Ejecting from a vehicle creates a new vehicle at your landing site, consisting of a "Used Ejection Seat" that will act as a frame with the aforementioned storage.
- Parachute can be disassembled to get a lot of rope and fabric.
- Ejecting should probably land you at some some minimum distance away from your starting point.
- Ejection Seat should be useable while vehicle is in motion.
- Support for Ejecting NPCs.
- Support for Ejecting monsters.
- Ejection actually checks that each tile along the parabolic trajectory is clear.  Ejecting too close to tall buildings is not recommended.

Video of a Real Helicopter Ejection Seat:
https://www.youtube.com/watch?v=jLhZN7fTwQQ&feature=youtu.be&t=83

**Comment by FulcrumA** [comment]
Hey, I've made the aircraft (to be) in the game and I am willing to work on them but someone else will need to add necessary parts. Also welcome: helicopter rotors, black box as an integrated vehicle part, parachutes to go with the ejection seats.

**Comment by chaisawlajatang** [comment]
> Support for Ejecting monsters.

Whoa, so much opportunity :) Unbelievable Flying Hulk Circus! Fantastic Boomer Sky Show! One day only!

**Comment by l29ah** [comment]
I think only a `cloth roof` should be allowed be above such a seat to avoid awkward situations of having to fly through military armor, wind power plants or machine guns.
