### ISSUE TITLE
Frozen toilet water can be poured into plastic bottles

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#25056]
**Describe the bug**  
You can pour water (frozen) from a toilet into a plastic bottle

**To Reproduce**  
Go to a toilet with a plastic bottle press e to examine it, select pour into a container, select plastic bottle.

**Expected behavior**  
Expected to be told, "You cannot pour a frozen liquid into the *item*". i.e. not allowed

Because you can't pour frozen liquids.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-30780-gf121021
 - Graphics version Tiles

Mods loaded
-------------------
Dark Days Ahead
Filthy Clothing
Disable NPC Needs
Simplified Nutrition
Vehicle Additions Pack
Tanks and Other Vehicles
Extended Realistic Guns
-----------------------------

**Comment by DarkDaskin** [comment]
It is also possible to unload containers with frozen water into different containers. This should probably be disallowed as well.

**Comment by lethargicchii** [comment]
You can also spill them on the ground

**Comment by FantasticFwoosh** [comment]
Spilling them onto the ground won't allow you to typically pick them back up again. For any related problems you might want to refer to #25076 about how gimmicky and inconsistent picking up liquids are (when you have the correct form of re-sealable container)

* I need to check again but i do think plastic bottles are re-sealable, hence they dont need to be wielded 24/7 and can carry liquid and stored in the inventory (even though liquids can be removed straight into inventory anyway by (U)nloading)
