### ISSUE TITLE
Random weather

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#25053]
**Describe the bug**  
Currently the weather is quite unrealistic and even outright silly in it's inconsistency. It's possible to get a switch between rain and a sunny sky several times a day, without warning and with no relation to weather in the past few days, yet alone hours. With such weather, the very changes in atmospheric pressure, wind etc would have to be so drastic that the land would quickly become likely inhospitable.

Only temperature affects the weather in that rain turns into snow if it gets cold enough.

**Expected behavior**  
Weather should change slowly. If there's meant to be rain, it should build over time - sunny weather turning into cloudy, then into a drizzle before becoming an actual rain. Sure, freak weather does happen, but it's called so for a reason and should be a very rare occurrence.

**Versions and configuration(please complete the following information):**
Game version: 0.C-30780
Operating system: Win7
Tiles or curses: Tiles
Mods active: More Survival Tools, Stats Through Skill, Vehicle Additions Pack, Tanks and Other Vehicles, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits, Extended Realistic Guns.

**Additional context**  
Many activities that rely on it cannot be depended on as the weather can change from clear and sunny skies to downpour, in a matter of seconds (and then back again, and then back to rain).
Would also help with other features such as #24291 where one could roughly estimate when they may count for the rain and when they should water plants themselves (though arguably, given overwhelming frequency of rain in the game, it's questionable whether watering should be a thing at all - but that's another matter altogether).

**Comment by FulcrumA** [comment]
@pingpong2011 
Doesn't matter, the weather is wonky no matter the season length (same effect no matter how many days a season has) and flips between different conditions instantly, at random and too often.

**Comment by CoroNaut** [comment]
Just expanding the weather by 2x what we have current will probably suffice. (the display weather debug button is real nice btw :smile:)
