### ISSUE TITLE
Contributors focusing on JSON changes unable to run json linter

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#25057]
**Is your feature request related to a problem? Please describe.**  
Contributors who don't have a build set up are unable to use the native json linter and have to use the web linter, which is error-prone due to copying the text.

**Describe the solution you'd like**  
Bundle a build of the dda json linter with the game release for use by modders.

**Describe alternatives you've considered**  
Status quo is directing users to the web linter.
Maintain a seperate release of the json linter.

**Comment by kevingranade** [comment]
> What can go wrong with copying the web linter output?

Copy/paste is inherently error prone, simple things like cursor placement or a misclick when applying the paste can break whitespace.

> providing a package of ready to run mod tools instead of putting it in the game bindist.

The main reason I don't like this option is it means duplicating some build infrastructure, whereas bundling is incredibly straightforward.  I'll take a look at how big the executable is, it *should* be tiny.  Looks like on linux its 1.4MB

**Comment by vircung** [comment]
We could make travis to automate this. It could run `make style-json` and perform commit on `data` and push back to github. Example [gist](https://gist.github.com/willprice/e07efd73fb7f13f917ea), [other one](https://gist.github.com/mitchellkrogza/a296ab5102d7e7142cc3599fca634203).
