### ISSUE TITLE
Vehicle tanks cannot be filled with water or clean water

### ISSUE THREAD

**Issue by Tygrende** [CleverRaven/Cataclysm-DDA#25060]
**Describe the bug**  
Vehicle tanks cannot be filled with water or clean water.

**To Reproduce**  
1. Carry any container with water or clean water.
2. Try to fill a tank installed on a vehicle.
3. There's no option to fill it with water.

**Expected behavior**  
Vehicle tanks should be able to contain water.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version 0.C-30692-gc9c0232
 - Graphics version Tiles
 - Mods loaded More Survival Tools, Boats

**Additional context**  
I believe this has to do with the new freezing feature and most likely applies to all liquids that can freeze. I can still fill tanks with things like gasoline, disinfectant or cough syrup.

**Comment by alanbrady** [comment]
Duplicate #24991
