### ISSUE TITLE
format string in world names can break character names

### ISSUE THREAD

**Issue by MT-Arnoldussen** [CleverRaven/Cataclysm-DDA#25062]
**Describe the bug**  
% in world names make character names look weird:
The world name is displayed correctly, but the "%"s add a weird line above the character name:
![format](https://user-images.githubusercontent.com/3521568/44489560-15ef3380-a65c-11e8-89d7-76bd801182ef.png)

Another example:
![capture](https://user-images.githubusercontent.com/3521568/44489555-125bac80-a65c-11e8-9606-e680b20ad651.PNG)

**To Reproduce**  
1. Name a world something with % in it (might have to be % with a number after it)
2. Select it in the Load or World menu options

**Expected behavior**  
It should not add weird lines.

**Versions and configuration(please complete the following information):**
 - OS: windows 10
 - Game Version: 7734
 - Graphics version: Tiles
 - Mods loaded: N/A

**Additional context**  
Presumably someone trusted user input somewhere and there's code looking like `$worldname` instead of `format("%s", $worldname)`.

[Probably located here (as pointed out by Kevin)](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/main_menu.cpp#L848)

Did not check, but character names and preset names might have the same issue.

**Comment by CoroNaut** [comment]
Where is the characters name stored in save files? I can't seem to find it.

**Comment by AMurkin** [comment]
Filenames are base64 encoded characters names.
