### ISSUE TITLE
7.5KW Generator has a typo in its description.

### ISSUE THREAD

**Issue by Odieman1** [CleverRaven/Cataclysm-DDA#25066]
**Describe the bug**  
The 7.5kw Generator has a typo.

**To Reproduce**  
Find/Spawn the 7.5kw Generator.  Look at the description.  Try not to wince in horror at the developers poor grammar.

**Expected behavior**  
It should be grammatically correct.  I found one but refused to pick it up until the grammar is fixed.

**Screenshots**  
[Here](https://i.imgur.com/T95uy1W.png)

**Versions and configuration(please complete the following information):**
#7736
(No other information needed)

**Additional context**  
I was joking about not picking it up.  That part was sarcasm.  Of course I picked that thing up.  All info should be presented clearly with no additional information needed.

**Comment by aierce** [comment]
I see the "an" instead "a", anything else?

**Comment by Odieman1** [comment]
That should be it.
