### ISSUE TITLE
Wherever the dedicated thread about the frozen food issue is.....   additional feedback on working/not working conditions in winter time with food freezing

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#25061]
I searched with "frozen food". No result.

Report:
I had a stack of 24 sausages.
When I tried to heat them up with the gasoline cooker, they where frozen after the process was finished. So no hot sausage.
Then I took 20 sausages away, because I only could eat 4.

Heating of 4 sausages was working, placing them nice and hot in the inventory.

So maybe the  longer time needed made the stack of 24 all cool down again.

The issue appears like that to me:

Time needed to heat up x24
---------------------------------------------------------------------------->
x.........................................................................................................................................y

x - the stack gets the status hot
y - time passes till job is finished which turns status back into frozen

Time needed for x4
--------------->
x...........................y.......................x1...................................x2....................................

x - the stack gets the status hot
y - time passes till job is finished
x1 - status (cold) given
x2 - status (frozen) given

The states (cold), (frozen) cant get be assigned, because not enough time has passed for the stack of x4.

**Comment by alanbrady** [comment]
Duplicate #24914
