### ISSUE TITLE
Characters under the effect of Anesthesia are able to dodge.

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#25071]
**Describe the bug**  
Characters using an Autodoc and under the effects of Anesthesia are able to dodge.

**Expected behavior**  
Not being able to dodge, and probably lose partial protection from normal clothing, since the player is defenseless and immobile and Zeds have time to attack/bite on weak spots and uncovered flesh.

**Screenshots**  
https://clips.twitch.tv/SmoothAmazingAlpacaChefFrank

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-30479-g51ef7e3
 - Graphics version: Tiles
 - Mods loaded:
Medieval and Historical content, More survival tools, Vehicle additions pack, Tanks and other vehicles, Bionic systems mod, Boats, Folding Parts Pack, Icecoons Arsenal, Filthy clothing, Makeshift Items mod, More buildings, Classes and Scenarios, More locations, Disable NPC needs, Disable Religious texts, Mutant NPC's, Stats Through Skills, Safe Autodoc.

**Comment by Night-Pryanik** [comment]
Do you have Sensory Dulling CBM or Deadened mutation?

**Comment by KurzedMetal** [comment]
I based this report on the Stream video I linked, I didn't personally reproduce it.

He didn't have either Sensory Dulling CBM (actually when the bug happened was his first batch CBM installation and he didn't have Sensory Dulling in his inventory for installation) or Deadened Mutation.

You can see the list of Traits & CBM in the video too (sorry for the big white letters covering some parts but it is definitely readable): 
![image](https://user-images.githubusercontent.com/1426680/44545891-a07f7380-a6ec-11e8-8ca4-a90dd67705d6.png)

If you want you can check it yourself here is the stats: https://www.twitch.tv/videos/300615992?t=03h52m57s

This is the part that he reproduce the bug (just in case you wanna see something before/after): https://www.twitch.tv/videos/300615992?t=03h27m42s
