### ISSUE TITLE
Some thoughts on recipe learning balance as a result of "learn them all" challenge

### ISSUE THREAD

**Issue by maniak1349** [CleverRaven/Cataclysm-DDA#25074]
Windows, tiles, 0.C-29661-g765578f.
Mods: dda, no_npc_food, novitamins

First of all I want to say that I dislike current recipe learning system. I dislike lugging around excessive amount of stuff in general and books are quite big and heavy. It clashes especially bad with no car/nomad playstyle. The only alternative is to learn recipes you need (or all of them if you so wish) and right now you only can do so by crafting them. It's quite a chore in itself - to find components and craft things you don't even need right now, not to mention that some of those recipes are quite tricky - be it because of share amount of craft time or because some of the ingredients are hard to come by. I'd rather prefer the system where you will be able to learn recipes with books but will have reduced chances of success until you successfully craft it once (or multiple times/fixed amount of time spent).

Since the time books stopped giving you learned recipes I was trying to learn all the recipes I can every playthrough. This time I've decided to embark on the long journey to learn them all. It was quite time consuming but mostly progressed smoothly with some things being harder and some being easier. There were a few exceptions though that I think are quite out of proportion and I will describe those cases here in detail.

## Chance to learn recipe
Some basic numbers first. According to [the source](https://github.com/CleverRaven/Cataclysm-DDA/blob/3af3b2ba640c1e7e7da6313af1528f4b7f453650/src/crafting.cpp#L597-L599) chance to learn recipe each time you craft it is ```craft_time_mp / ( ( 1000 * 8 * diff ^ 4 ) / ( main_skill * int ) )```. So for skill 13 (maximum you can get with books and crafting diff 10 recipes) and int 14 (base 12 + 2 from bionics; not the best but above average) expected time to learn will be ```43.956 * diff ^ 4```. For different recipe difficulty it will be

Req. lvl | Expected time in moves | Expected time in hours
-------- | ---------------------- | ----------------------
10 | 439560 | 7.32 hrs
9 | 288395 | 4.81 hrs
8 | 180044 | 3 hrs
7 | 105538 | 1.76 hrs
6 | 56967 | 0.95 hrs
5 | 27473 | 0.46 hrs
4 | 11253 | 0.19 hrs
3 | 3560 | 0.06 hrs

Numbers don't seem to be off the charts but only until you put them into real use. I will use this numbers in recipe descriptions since that's what my stats were most of the time.

## The recipes (starting from most frustrating ones)

1. **Heroin**
Diff: 6 -> expected time ~57 mins
Craft time: 2 mins
Chance of success per try: 3.51%
Avg. tries to have one success: 28.5

Probably the worst recipe to learn right now. Because of extra short duration it has 3.51% chance to be learned each time you craft it, but the real problem is it's only made from 40x oxycodone and it's a rare drug drop that spawns in bunches of 10. So you will need 4 rare drop rolls for just a single attempt. Still haven't finished this with something like 10 tries.
And from gameplay point of view this recipe is quite useless. If you're an addict your best choice in context of the cataclysm is to get off the needle ASAP. Even if you can't or just need some of the stuff in your veins **RIGHT NOW** you have much better chance of stumbling upon drug dealer bodies with heroin on them then getting a book and enough of oxycodone in time.

2. **Internal Microreactor / Advanced Microreactor (as a bonus - Microreactor Upgrade)**
Diff: 10 / 10 -> expected time 439 mins
Craft time: 50 mins / 5 mins
Chance of success per try: 11.4% / 1.14%
Avg. tries to have one success: 8.78 / 87.8

I think I should put it first in this list but I'm yet to know all the depths of despair with it. Thing is - minireactor you need to craft it is really hard to come by. Two cars that have it are rare, may have it destroyed and you need to be constantly on lookout for them. The only locations that can have it in a form of Plutonium Generator - shipwrecks and military outpost - are a little more often than those cars and much easier to spot. But Plutonium Generator only gives you minireactor with a 25% chance and in outpost it only present in 33% of cases (if not destroyed by overly nimble grenadier). All that on top of 1.14% chance of success is just simply hell.
Microreactor Upgrade (diff 10, time 50 min, chance 11.4%) is not a simplest thing to learn either, but compared to minireactor recipes it looks like a joke. At least after some 600 days I already have 19 of them in wait for their minireactors and already know the recipe while Microreactor was only crafted once during all that time.

That concludes utterly ridiculous stuff - now for hard and tedious.

3. **Rocket fuel**
Diff: 4 -> expected time 11.3 mins
Craft time: 5 mins
Chance of success per try: 44.2%
Avg. tries to have one success: 2.26

Chances to learn are pretty good, the problem is key component - zinc. The only place to find it is chem room in school - both in regular and the one in necropolis. Both are occurring not too often and both usually require a lot of fighting to get in. Neither it is guaranteed that you will find any zinc in first or second school you stumble upon.
To add fuel to the flame of frustration the recipe itself is almost useless. Rocket fuel is only used in home-made rockets - two of them require 50 RF and one - 75. And from a single drop of zinc (100) you will be able to craft 20 of rocket fuel.

4. **Mutagens and serums. The whole lot of them**
Diff: mostly 9 and 10 -> expected time 288 mins / 439 mins
Craft time: mostly 10 to 15 mins (1x 20 mins)
Chance of success per try: 3.47% (d9 t10) to 2.85% (d10 t12.5)
Avg. tries to have one success: 28.8 / 35.2

Almost all the components (except for eggs) are easily available at any time. The main problem here is share amount of recipes. They are not to easy to learn either. I did the math on those, maybe it's somewhat off but for one who did that on practice twice those numbers sound about right.
There's the final numbers: 839 hours of craft time is required in average to learn all the mutagen/serum recipes (49.3 17hr work days). This number includes only time you will need to craft serums, their component mutagens and basic mutagen for those. I.e. ammonia + bleach/oxi is not included. If you was stacking up ammonia and bleach during the time you was looking for mutagen recipes in labs then chances are you will have from about 1/3 to half of required amount by the time you will be ready to produce them. If not - too bad - whole amount of those components will require another 2293 hours (~135 17hr work days).
And that's only craft time itself. Running around the forest in search of eggs in spring and butchering whole towns to farm tainted meat for mutagens is another story.
Another fun number - to craft all the basic mutagen you need you will need to kill and butcher more than 1600 regular zombies.

5. **ANFO charge / RDX charge**
Craft time is irrelevant here since it's disassemblable.
Before fixes #22226 and #22377 amount of required components was simply astronomic. Now it's just somewhat tedious. This one should probably go to honorable mentions category if/when #24698 will be fixed.

For the numbers:
1 ANFO charge <-> 70 ANFO <- 1260 ammonium nitrate <- 126 nitric acid
Nitric acid main source is lab and each spawn is 3 units of NA so 42 bottles. Since it's a huge barrel full of explosives it sounds fair. Usefulness of such an expensive explosive device is another question.
1 RDX charge <-> 60 RDX + 200 HMTD

60 RDX <- 60 nitric acid + 600 hexamine + 24 sulfuric acid (2/gren
200 HMTD <- 500 hexamine + 100 hydrogen peroxide (conc) + 40 acetic acid
Hexamine spawns only in labs and on scientists' bodies, is only 20 per box and is quite rare. (2 boxes from the whole central lab? Come on!) Concentrated hydrogen peroxide is only(?) from labs in 3 unit bottles. Alternatively you can craft it from regular hydrogen peroxide - common medical drop, but it's even worse since it comes in 3 unit bottles too and it's 5 HP -> 1 HPC. I still think it is a leftover from the old bug.
Nitric acid and hexamine amount in RDX is intimidating but is mostly irrelevant since you can get RDX from grenades (2 from grenade so 30 grenades. With lots of grenadiers in lab armories lately it should be easy.)

And that's it for the hard stuff. More of a honorable mentions than of real trouble:

6. **Pro fishing rod**
Craft time is irrelevant here since it's disassemblable.

You need to find one to learn it. Key component - bismuth is not spawning anywhere at all and rod itself is a rare pawn/sporting drop. Or that what I thought at least - it seems from json that you also can find it in camps and with quite a good chance - at the lake, so probably it is less of an issue as I thought. Still it is not very easy to come by. It is also really weird to have an item in the game that is not spawning at all and used in a single disassemblable recipe.

7. **Rice recipes from Sushi Made Easy**
The catch here is rice - it is perishable now yet it is not renewable. So if you will forget about these recipes or will be unlucky with the book search then rice will become hard to come by or completely extinct. When temperature preservation will work properly it will be a little less of an issue - you will be able to stash some rice in a freezer or find some in cold lab if you're really lucky.
Personally I've been playing with an older build where preservation is almost completely broken - it only takes into account seasonal temps and ignores local temps and fridge. I'm yet to find that damn book and all rice I find now is at least "old". Time is running out.

8. **Incendiary / Explosive / Spiked home-made rockets**
Diff: 5 / 4 / 3 -> expected time 27.5 / 11.3 / 3.6 mins
Craft time: 20 / 30 / 8 mins
Chance of success per try: 72.7% / 265% / 222%
Avg. tries to have one success: 1.375 / 1 / 1

Numbers look good, but don't forget that that's at skill level 13. At s.level 8 (relatively easy to obtain without venturing into the lab and crafting mutagens for half a year) they will be 1.625x worse. You will need at least 2 + 2 + 3 = 7 rocket candies so it's 350 of saltpeter (4 drops). You can get saltpeter only in lab and school I think and you're not really swimming in it since you will need to save it up for nitric acid -> ANFO/RDX craft too.

9. **Rare ammo / casings (.300, .454, .44, .500, .700, 7.62x54mmR etc.)**
They are not really that rare but since there is a lot of them getting them all will take some time. Also it is really frustrating to find some rare .700 casings only to fail learning during the craft and realize that you don't have a corresponding gun to turn them back into casings. And that's the only recipe that prevents you from dropping that book.

---

And that's it. I hope you're not bored to death. I don't feel really strong about most of these yet maybe they still require some toning down. Exceptions are the first two - those are completely out of hand.

**Comment by Zireael07** [comment]
Hmm, rice should be farmable IMHO if it isn't now?

**Comment by dissociativity** [comment]
I mean doesn't the e-ink tablet and camera allow you to copy recipes?

**Comment by CoroNaut** [comment]
The way we learn recipes now has been changed not too long ago. It used to be that you learned all the recipes from a book by chance as you gained skills in reading it. It is kind of unreasonable in my opinion to just learn all the recipes in the world this way. After all, your character only has a human brain.

**Comment by maniak1349** [comment]
> I mean doesn't the e-ink tablet and camera allow you to copy recipes?

Is it? If it is I'm yet to figure out how. I know that you can use E-Ink Tablet to read SD cards you find and there can be recipes in them. But those seem to be completely random and not to big in numbers - you will spend years trying to find all the recipes this way. It seems to be broken too - when I select to display a recipe I don't know on the tablet it does not show up in the craft menu.
It will be a nice mechanics though to transfer all the recipes to the tablet and use it as an omnibook. No manual recipe selection will help too.

> It is kind of unreasonable in my opinion to just learn all the recipes in the world this way. After all, your character only has a human brain.

But in the end of the day you will know all the recipes you will just need to craft them couple of times for that. Human brain is quite capable and it's not like there is millions of recipes to learn - couple of hundreds at most and some of those a simple and straightforward.
Again - what if you don't have a human brain? There is Enhanced Memory Banks bionics, there probably some mutations for that (not sure, not big fan of those), you can have Int at 50 if you will disable stat limits - and that is far beyond the human capabilities.

**Comment by mlangsdorf** [comment]
I guess I don't understand why the "learn all recipes" challenge should be anything other than a huge grind of doing unlikely and difficult things. None of the challenges are meant to be easy.

As far as actual fixes to the issues:
* It looks like the recipe for heroin should be updated to include other opiates, especially morphine, as possible ingredients.
* Zinc should spawn in more places. The factory seems like an obvious place, since a large use of zinc in the US is for corrosion resistance of iron parts.
* Pro fishing rod should accept any of lead, bismuth, silver, or gold for the weights. You just want a dense material, it shouldn't have to be bismuth.
* Saltpeter should show up in more places: farms, home improvement megastores, and gardening supply stores look like reasonable places.
* Skilled survivors should be able to set up tabletop Haber and Ostwald processes to manufacture ammonia, nitric acid, and saltpeter out of the air. Production might be a little slow (250 mL of ammonia per 2 hours) but the required pressure and temperature range ( 150 psi, 1100 F) is something that a survivor with pressurized tanks and a forge could provide. Biggest issue would be adding platinum as a material and a recipe for forging a platinum grill, but the process of making a platinum grill for these processes was a problem that was solved in 1902 so I feel a survivor with Fabrication 8+ should be able to handle it.

**Comment by maniak1349** [comment]
Those fixes sound really nice.

What about Advanced Microreactor recipe though? Minireactor availability and recipes difficulty sound about right - those are really high-tech stuff after all. But 5 minutes duration makes Advanced Microreactor almost completely unlearnable. I've just did a quick test - made a character with skills 13 and int 14 wished for components and book and crafted 100 Advanced Microreactors and did not learn a recipe.

Buffing craft duration to 50 minutes (as it is for most of the other CBMs) or even more sounds like a good fix. As a rationale to the new craft time - Microreactor Upgrade and Internal Microreactor a meant to work together but yet are two standalone CBMs that you can install separately. So just slapping them together with duct tape on top will not really work - you will need to use parts of them to assemble a new device.

**Comment by kevingranade** [comment]
> What about Advanced Microreactor recipe though?

Simple, the recipe shouldn't exist.  There should be no crafting of CBMS

**Comment by kevingranade** [comment]
Extracted the specific issues that have/require a fix to their own entries.

**Comment by maniak1349** [comment]
So, it's still a 'no' for the Advanced Microreactor recipe. Does it mean that CBM crafting removal is already scheduled for a near future? Is it tied to that big CBM slot rework I've heard something about?

**Comment by kevingranade** [comment]
#25108

**Comment by maniak1349** [comment]
Oh, I see. Thanks for the clarification.
