### ISSUE TITLE
Minefields spawn superimposed onto buildings

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#25079]
**Describe the bug**  
Minefield spawns in the place of a building, erasing it partially.

**Expected behavior**  
Minefields do not spawn superimposed onto buildings. Booby trapped locations are fine, regular houses, offices etc partially desconstructed to add mounds of dirt and buried mines, surrounded by warning signs are not. Probably such kind of locations shouldn't spawn near non-military buildings at all.

**Screenshots**  
![uhoh](https://user-images.githubusercontent.com/38487938/44520654-c6971a80-a6d0-11e8-9150-5af8aed71361.png)

**Versions and configuration(please complete the following information):**
Versions and configuration(please complete the following information):
Operating system: Win7
Game version: 0.C-30819
Tiles or curses: Tiles
Mods active: More Survival Tools, Stats Through Skill, Vehicle Additions Pack, Tanks and Other Vehicles, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits, Extended Realistic Guns.

**Comment by Zireael07** [comment]
I believe this has recently been reported?

**Comment by Qrox** [comment]
I thought this was a feature...

**Comment by Zireael07** [comment]
Duplicate of #25036

**Comment by FulcrumA** [comment]
>Duplicate of #25036 

Hm, my bad, didn't notice. Closing this ticket as a duplicate then.
