### ISSUE TITLE
Auto pickup based on materials

### ISSUE THREAD

**Issue by logros13** [CleverRaven/Cataclysm-DDA#25086]
**Is your feature request related to a problem? Please describe.**  
Often when you are scavenging items in bulk it not because you want the item itself but rather want to disassemble it for crafting materials, automatically scavenging everything of a material for later disassembly and crafting seems like the kind of thing auto pickup would be great for but this is as far as i can figure out not currently possible.

**Describe the solution you'd like**  
The ability to ad m: rules to auto pickup for example m:kevlar m:nomex etc.

**Comment by CoroNaut** [comment]
I suppose that's one way to do it, but I would still find it easier to just disassemble whatever you want on the ground. Then you can set auto pickup to pickup whatever ingredient you want. Doing it this way will also help your storage volume problem as well.

**Comment by cake-pie** [comment]
@CoroNaut the advantage of what @logros13 proposes is it would enable selectively disassembling only those items that would yield the materials of interest, which takes much less time than indiscriminate disassembly.
