### ISSUE TITLE
Fungus/mycus and its spread is still broken

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#25083]
**Is your feature request related to a problem? Please describe.**  
It's pretty well known in the community at large that fungal spread is still having issues. It spreads way too easily, is not limited by many factors, with time is able to slow down even decent computer as dozens of spores grow, turn into monsters, disappear. Together with fickle weather, even the basic go-to method of fungus spread control, like fire, is unreliable.

Big part of the playerbase has to rely on the mod disabling the feature, many others despite using no such mod and even enjoying fungus while caring about balance advise strongly to avoid fungal areas and new players with low-end hardware have to disable fungus altogether, rendering the feature unstable and unbalanced at best, downright broken and pointless at worst.

Recent breeding mechanics only exacerbated the problem - creatures in the wild are really plentiful now without effective mechanics that'd keep their numbers in check, they keep provoking and scaring fungal creatures making them run around even more spreading spores.

**Describe possible solutions**  
Severely limit spread of fungus. Lore-wise it is a huge issue but gameplay-wise it is less of a threat than a pain in the butt that cannot be resolved without huge investment of time and resources just to avoid resurfacing of the bother later.

- Having spores less likely to create fungal tiles and turn into fungal monsters
- Making fungaloids spread spores only when they're undisturbed ("ignoring" status) and not spread additional spores upon death (or, even better - spread variety of spores that can infect nearby opponents but won't lead to growth of fungal creatures/terrain itself) - likely the most effective method.
- Establishing maximum size for fungus growth in the area after which fungus creates new bloom/tower
- Have the fungal beds slowly being consumed by local flora if they don't grow enough to create dedicated spreading mechanisms (in practice: fungal beds would slowly disappear if there's no fungaloid, spores, fungal tower or other such creature nearby).
- Ensure that fungal growth is localized, rather than spawning dozens of fungaloids appearing in many small patches over a vast overmap area - this one adds a lot to the 'pain in the butt' factor, especially when connected to the above issue of scared fungaloids running around and spreading even more spores.
- Increase flammability of fungus and its creatures, making sure fungal beds will suffer and feed the fire even in a drizzle or light rain, like cobwebs.

**Additional context**
We have to keep in mind that making fungus too ineffective in spreading would be also bad - a fungal tower or bed left alone nearby for considerable time should spread and become increasing threat, but not to the point of destroying performance of the game. Considerably grown fungal patches left undisturbed and allowed to spread should be a challenge even for relatively skilled and well-equipped character.

It's unlikely all of the above solutions would be necessary, unless for the sake of making the whole feature more interesting and ambitious with their values adjusted so each on its own limits fungal spread only somewhat, or so some of those balancing changes would work as fail-safe for others.

I'd like to make fungal growth a basic feature all players can keep turned on as long as they do not oppose it on the grounds of personal preferences regarding aesthetics etc. I understand that the intent was to make it challenging but in practice the implementation fell short, merely making it troublesome enough that even players looking for a challenge decide it's too much of a bother to have at all.

This ticket is made partially due to no similar one currently being open despite well-known fact that the feature lacks polish since its inception long time ago (though some of said polish was provided, just not enough) and by the way of recent series of tests I've performed to verify qualities of fungal spread and its containment.

**Comment by tyrael93** [comment]
The day someone actually fixes blobs and fungaloids spawns not being 100% retarded will be a good day.
