### ISSUE TITLE
Overabundance of smoke generated no matter the source

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#25084]
**Describe the bug**  
Smoke has issus on its own in general. There seems to be no good severity set. A lit cigarette indoors is like an activated smoke grenade and every combustion engine car is leaving huge plum of the smoke behind.

**To Reproduce**  
Smoke a joint/cigarette or drive around in a car with a combustion engine.

**Expected behavior**  
Cigarette/joint and other such items generate a single puff of smoke from time to time that dissipates nearly immediately outdoors and takes some time to accumulate into a cloud indoors. Similarly, cars generate less smoke as well. Potentially things burning ina  fire as well as braziers should generate considerably more of it.

**Screenshots**  
Swiped from #25069:
![obraz](https://user-images.githubusercontent.com/38487938/44529816-459a4c00-a6ed-11e8-8715-6a7e0c6ae456.png)

**Versions and configuration(please complete the following information):**
Operating system: Win7
Game version: 0.C-30819
Tiles or curses: Tiles
Mods active: More Survival Tools, Stats Through Skill, Vehicle Additions Pack, Tanks and Other Vehicles, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits, Extended Realistic Guns.

**Comment by Androwski3000** [comment]
I think there are different kinds of smoke. A car smoke puff gets a Y/N promt if you want to step into that. The same with smoker zombie smoke.

The cigarette smoke, as ingame, represents quite good in my opinion how smoke of a cigarette develops via it´s spread in the area. It is from the space it takes like where you can see and smell it well.
The only thing which might could be done to cigarette smoke is it´s intensity graphics wise.
Also the first time I saw it, I thought it is as hazardous as smoke zombie smoke.
