### ISSUE TITLE
Game crash when you give an NPC follower something to wear.

### ISSUE THREAD

**Issue by mrkybe** [CleverRaven/Cataclysm-DDA#25085]
**Describe the bug**  
The game crashes when you give the NPC the MBR vest to wear.

**To Reproduce**  
1. Download the Save, open Chateau Woods -> Kaede
2. Talk to Adolph Rosario (he's right next to you when you load in)
3. Tell him "Not yet"
4. Tell him "I want you to use this item"
5. Select the "MBR vest (Kevlar plates)
6. Crash

**Expected behavior**  
Not crashing, him wearing the vest, dropping his gambeson.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-30819-g3609b8
 - Graphics version [Tiles]
 - Mods: a lot, but they're all the ones that are included with the launcher.

**Save File**  
[Crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2314861/Crash.zip)

**Comment by mrkybe** [comment]
If you try to sort his armor instead, and press 'u' to take off his gambeson, it says he can't place items there, presumably because he's standing on a bush.  That's probably the cause?

**Comment by FulcrumA** [comment]
@mrkybe 
Has to include what to do after the fix - the NPC unable to drop an item has to know what do to with it now when he also cannot carry it due to lack of storage space. Making the NPC attempt to drop it to the closest free tile or make the game use the "item overflow" code and move the item to the nearest available tile on its own would help here.

**Comment by Qrox** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/10525421b76066756e570d7f7904f9906d000346/src/player.cpp#L8408-L8411

It returns true here whether the drop was successful or not.

https://github.com/CleverRaven/Cataclysm-DDA/blob/10525421b76066756e570d7f7904f9906d000346/src/npc.cpp#L978-L987

So the code here thinks that the take-off was successful and keeps trying taking off more items, while actually nothing is taken off, creating an infinite loop.

The dropping code creates an activity which is handled on-spot for NPCs, but will be handled later for the player, so I'm not sure if it's a good idea to return a bool in that function to indicate success.
