### ISSUE TITLE
Pool of acid spreading by itself around sulfurous anthill

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#25089]
**Describe the bug**  
This pool of acid is just... snaking its way in random directions

**To Reproduce**  
1. I honestly have no clue

**Expected behavior**  
Pools of acid should not be sentient? They shouldn't be...... moving on their own?

**Screenshots**  
![capture](https://user-images.githubusercontent.com/24307650/44541301-871ffc80-a6d7-11e8-85b7-84c8842ee4d4.PNG)
![capture2](https://user-images.githubusercontent.com/24307650/44541321-9606af00-a6d7-11e8-891c-243922f14bcd.PNG)
![capture3](https://user-images.githubusercontent.com/24307650/44541324-97d07280-a6d7-11e8-8cf3-c8995946fb08.PNG)
![capture4](https://user-images.githubusercontent.com/24307650/44541326-999a3600-a6d7-11e8-8129-c1d3ad4f36a2.PNG)
etc....

**Versions and configuration(please complete the following information):**
 - OS: win 7
 - Game Version 0.c-30780-gf121021
 - Graphics version tiles
 - Mods loaded none

**Additional context**  
Even saving, closing and reopening still yields the result, here's the save file:
[Hanksville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2315516/Hanksville.zip)

**Comment by Night-Pryanik** [comment]
I can't seem to reproduce the issue even using your save file. I guess this could be closed until it is confirmed to exist.

**Comment by CoroNaut** [comment]
I'm not sure how to download a copy of cdda as far back as the version provided otherwise I would retest in that version, but in latest I can see the problem is not happening. Thanks for closing.

**Comment by CoroNaut** [comment]
@Night-Pryanik I've loaded up the save in version 0.D-5847-ga4acee2 (tiles) and after skipping all the errors and just standing still and skipping turns, the acid does still spread northwards.

**Comment by Night-Pryanik** [comment]
Ok. I'll reopen. But we still need confirmation on this on a brand new world. Your save is really old, it might be a glitch.

**Comment by ZhilkinSerg** [comment]
It is reproducible in a provided savegame, so I am trying to find out what's wrong and whether it is reproducible in a new world.

**Comment by davidpwbrown** [comment]
The only thing I can think of, is ants on a different z-level, and the acid field is spreading a z-level or something

**Comment by davidpwbrown** [comment]
I can't reproduce on latest master - Im thinking maybe, on a z-level below, if a soldier acidic ant was somehow spawned in a 1x1 tile, surrounded by walls, and when it tried to spit its acid, the only way for it to spread was up? idk.

**Comment by davidpwbrown** [comment]
Ok - tested and there appears to be an invisible acidic ant there. its spreading its acid around, but you cant see the ant. 
When you debug kill all monsters, its corpse appears there where the acid is. I have no idea why this is the case. I can reproduce on current master, but this is a risky thing to assume solved.

**Comment by kevingranade** [comment]
From manually reading the save, it looks like there are a ton of underground ants at this location, so I'm extremely suspicious that this was an instance of the "shoot through z-levels" bug, and when Dwpb did kill all monsters it just hoisted the corpse to the surface.

**Comment by kevingranade** [comment]
Reopen if encountered again, but this instance isn't being productive.
