### ISSUE TITLE
The Book of Dances, missing

### ISSUE THREAD

**Issue by mu3r73** [CleverRaven/Cataclysm-DDA#25082]
After upgrading yesterday to 0.C-7736, my char lost the copy of "The Book of Dances" that he was carrying. Instead, he got this other book, "Break a Leg!"

I checked the json files, and found both books share the same id, in data/json/items/book/dodge.json:

```
    "id": "manual_dodge",
    "name": "The Book of Dances",

    "id": "manual_dodge",
    "name": "Break a Leg!",
```

**Comment by Break-Off** [comment]
For some reason, this pull request (https://github.com/CleverRaven/Cataclysm-DDA/pull/24841) was approved and merged because the author said that it addresses an unrelated bug, when it only adds a tier one dodging book that conflicts with The Book of Dances.

**Comment by FulcrumA** [comment]
@Break-Off 
The merge was a humorous addition, the name of the book is a reference to the issue it claims to address. It's true however that it seems like it was just a quick copypasta of the original book and does cause issues rather than fixing anything.

**Comment by Rivet-the-Zombie** [comment]
That's a weird conflict.

**Comment by cake-pie** [comment]
@FulcrumA not merely copypasta, because it did altered the stats, which look a tad unbalanced: too light, far too cheap, etc

**Comment by fungusakafungus** [comment]
I'm sorry for causing all this trouble, I'll be more careful in the future.
