### ISSUE TITLE
Half worm drops 32 meat

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#25088]
**Describe the bug**  
I killed a worm, it split into two, dropped 32 meat each.

**To Reproduce**  
1. Find or spawn ground wormie
2. Kill the wormie so mercilessly that it explodes and the game throws its body parts everywhere in a 7x7 area.
3. Notice there is 32 meat per wormie.

**Expected behavior**  
A wormie has less meat

**Versions and configuration(please complete the following information):**
 - OS: Win 7
 - Game Version 0.c-30780-gf121021
 - Graphics version Tiles
 - Mods loaded none

**Additional context**  
I used an Awl pike to do 106 and 107 dmg to them.

**Comment by Regularitee** [comment]
This would appear to be a sub-issue of the broader #24909

**Comment by CoroNaut** [comment]
I didn't butcher them, but if the explosion of the creature in question is similar in code to the butcher system, I think you got problems lol.

**Comment by CoroNaut** [comment]
It seems many more animals are doing it, here's 3 coyotes i just killed from range:
![capture](https://user-images.githubusercontent.com/24307650/44605156-477c1200-a7b6-11e8-90ba-9bcbf2cd14d5.PNG)

**Comment by Robik81** [comment]
Hmm, looks like it is much faster than full butchery... I like it.

**Comment by KurzedMetal** [comment]
I just got 64 chunks of meat from 4 Beagles (about 16 chunks per each of them)

This is definitely broken LOL

**Comment by sfsworms** [comment]
How so? A chunk of meat is 200g, so the 32 chunks are about 6.5 kg of meat. That's not ridiculous for a giant worm.

**Comment by CoroNaut** [comment]
Every time I run over an animal, shoot them with range, or slaughter then with a melee attack, they blow up and spew meat everywhere, I am getting so much that I have 2 dehydrators in my vehicle at all times just to keep up with crafting them all before they spoil. Also, if you cook like 10 of them and have metabolic interchange on constantly, the last few cooked meats still go rotten because they fill you so much.

**Comment by sfsworms** [comment]
Well, yeah, if you kill several large animals per day, you should be getting way more meat than you can eat, that's realisitc. The balance issue here is the sheer amount of animals, you shouldn't be seeing several deer, a moose and a bear every time you drive one hour on new england roads.

**Comment by nexusmrsep** [comment]
Problem here is not the quantity of meat in an animal, but the quantity of meat tossed around when overkill happens.

**Comment by kevingranade** [comment]
I think what happened was:
Meat in animal set based on game balance instead of reality.
Drop rate from overkill set with certain expectations of how much meat should drop.
Meat in animal set to real world based value.
Drops from overkill way too high.

The ratio of meat dropped when overfilling definitely needs to drop.

You can certainly recover some meat from roadkill or a small animal hit by a large gun, but the ratio of meat wasted should be very high.
