### ISSUE TITLE
Crash when accepting mission from NPC, invalid map position

### ISSUE THREAD

**Issue by HeadWar** [CleverRaven/Cataclysm-DDA#25097]
An NPC asked for help, with the fluff text that starts "Apparently one of the other survivors picked up on an unusually dense horde of undead moving into the area." When accepting the mission, the game freezes for a bit, and then displays the following error:

DEBUG: Tried to access invalid map position  at grid (0,0,-2147483648)
FUNCTION: size_t map::get_nonant(int, int, int) const
FILE: src/map.cpp
LINE: 7939

It then goes on with 
DEBUG: Tried to access invalid map position  at grid (2, 6 , -2147483648)
FUNCTION: submap* map::get_submap_at(int, int, int) const
FILE: src/map.cpp
LINE: 7875

And then CTD.

 - OS: Windows 10
 - Game Version: 0.C-30823-g1052542 (tiles)

**Comment by Zireael07** [comment]
-2147483648 looks like an overflow of some sort?

**Comment by pikolinianita** [comment]
I had similar event when I accept quest from NPC when we were in the cave, at level -1 or -2.

**Comment by HeadWar** [comment]
Yes, that sounds about right, I was on the first level down in a lab when I got the error.

**Comment by KorGgenT** [comment]
looks like the error is mission_start::place_npc_software in mission_start.cpp 
at line 601 it overflows

**Comment by kevingranade** [comment]
Merged into 0.D and master.
