### ISSUE TITLE
Can we get the bionics and trait lists moved to their own columns in the player info screen?

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25091]
Currently, the bionics list and mutations/traits list (the potentially two longest lists in this window) are stacked on top of one another, which makes no sense from a UI perspective. Especially when you consider that in standard resolutions the game screen is usually much wider than tall, meaning there's a shortage of vertical space but an abundance of unused horizontal space.

![cataclysmui](https://user-images.githubusercontent.com/8593513/44544528-a581fa00-a6cf-11e8-97b0-2cba0d554165.png)

(_Image: The UI layout here causes nearly 1200 pixels to be used vertically, but only 600 or so horizontally, even after collapsing the trait list into only three items long._  )

The player info screen could much more effectively utilize unused space by moving the traits and bionics lists to their own columns, to the right of the existing player info.

**Comment by CoroNaut** [comment]
[Bionics slots](https://github.com/CleverRaven/Cataclysm-DDA/projects/6) will pretty much limit the window to much less than what you see in your image.

**Comment by Pixelmage** [comment]
I'd suggest we make them fixed size and scrollable instead. With Skills - Traits + Bionics - Effects, the horizontal spacing is fine and matches the width of the stats card above.

So, capping the number of lines on all columns to a max equal to the number of skill lines could solve the issue while still allowing any arbitrary number of traits and bionics to fit.

@CoroNaut That is a poor argument. We don't have a due date for that update and this is a problem until it happens; plus, even after bionic slots are implemented, a mod to disable the limit is very likely to be developed and that would reintroduce this issue. Improving the UI is beneficial to everyone.

**Comment by mlangsdorf** [comment]
They're both already scrollable so they'll work on screens with limited real estate. You'd just have to change the definition of max_y in src/player_display.cpp:320 and test it.

Okay, you'd actually want to reorder the code that caps skill_win_size_y so it goes before the code that caps trait_win_size_y and bionics_win_size_y, and then compare to skil_win_size_y instead of maxy.

Still, pretty straightforward.
