### ISSUE TITLE
Dresser spawns on top of 2x2 bed

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#25090]
**Describe the bug**  
Dresser spawning onto and not next to the 2x2 bed

**To Reproduce**  
1. Find a natural occurrence of this

**Expected behavior**  
This doesn't happen

**Screenshots**  
![capture](https://user-images.githubusercontent.com/24307650/44541982-a28c0700-a6d9-11e8-8fc1-b74b099996ca.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Win 7
 - Game Version 0.c-30780-gf121021
 - Graphics version Tiles
 - Mods loaded none

**Comment by kevingranade** [comment]
There's not enough information to go on here to identify an instance if the bug.
