### ISSUE TITLE
Any Safe Mode exclusion made in Safe-Mode Manager breaks Safe Mode completely 

### ISSUE THREAD

**Issue by AbsalomAchitophel526** [CleverRaven/Cataclysm-DDA#25105]
**Describe the bug**  
If a user adds an exclusion to Safe Mode in the SM Manager, accessed through (ESC), ALL monsters will not trigger Safe Mode.  This behavior will persist until ALL rules are deleted, not disabled.  Disabling does nothing.

**To Reproduce**  
1.)  Start new game, default mods and world settings
2.)  Add Safe Mode exclusion for anything, like say Pit Bull Mix or Dog
3.)  Run into nearest enemy with Safe Mode on, oblivious to any danger

**Expected behavior**  
Adding a safe mode exclusion would keep Safe Mode functional while disabling it for non-threatening enemies.

**Screenshots**  
![btfo](https://user-images.githubusercontent.com/33147994/44590893-d589d580-a781-11e8-8408-1b89be1f8554.jpg)

**Versions and configuration(please complete the following information):**
 - OS: Win7
 - Game Version: Experimental #7753, though I tried a previous version and it still occurred.
 - Graphics version: ChestHole tilesets
 - Mods loaded: default

**Comment by alanbrady** [comment]
This is an intentional feature.

The default safe mode rules are `* hostile`.  Which makes all hostile trigger safe mode.  If you add your own rule it overwrites the default behavior.

To fix this, add another rule for `* hostile`.

It could be argued this could be made more user friendly but that is a different issue.

**Comment by AbsalomAchitophel526** [comment]
@alanbrady Even when the rule itself is disabled?

**Comment by alanbrady** [comment]
Adding a rule overwrites the default behavior.

**Comment by AbsalomAchitophel526** [comment]
Rules are, by definition, additions to an already existing system.  It stuns me this is intended, and makes me not want to test this feature further in case there are other quirks not already specified.

**Comment by alanbrady** [comment]
Think of it this way, what if you didn't want the default behavior on top of your own rules?  You couldn't.  The way it currently works you can add it and I'm pretty sure there's even a dialogue asking if you want the default added when you first add a rule.

I'm failing to see why this is world ending for you.

**Comment by Zireael07** [comment]
I believe the default rule should stay, and toggling it off could be a keypress away. But in most cases, players are gonna want it.

**Comment by ennob** [comment]
I was tripped up by this as well a while back (and lost a character). I see the argument for being able to override the default, but maybe the `* hostile` rule could be added and enabled by default, then if you really want to disable it, you can.

**Comment by moll** [comment]
I think this should be better communicated in the UI, too. I was rather puzzled why safe mode broke all of a sudden after adding a single ignore entry to the Safe Mode Manager and only by searching for "no longer works", found this issue with a mention that one needs to add a default manually.
