### ISSUE TITLE
"Modified" mininuke has nonsensical mass

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25100]
So, a regular mini-nuke weighs about **50kg**. There also exists a "modified" version for the nuclear mortar, which replaces the timed fuse with a contact fuse. But this version only weights **3kg**.

Mathematically, plutonium-239 of unrealistically flawless purity has a minimum critical mass of 10kg. Add onto that the weight of the detonators, radiation shielding, and trigger mechanism... and the fact such pure plutonium-239 doesn't exist (thus requiring more fissile fuel to compensate) and, well, 3kg doesn't make any sense from a realism standpoint. It also doesn't make much sense from a game-balance standpoint, because the game's various anti-tank weapons generally also weigh in the <5kg range (but are similarly rare and considerably weaker). Not to mention how it can weigh 3kg when the variant made by the national military weighs 50kg.

**Comment by tyrael93** [comment]
Yes, but due to how code handles projectilez you will literally not be able to shoot a 50 Kg mininuke from a launcher at anything than your feet.
Suck it up.

**Comment by AbsalomAchitophel526** [comment]
As the mini-nuke has an explosive range of around -30 tiles, and the launcher has a (theoretical) max range of 24 tiles, the point is moot.  Even an appropriately buffed end-game character that may survive that will find that the launcher cannot be precisely aimed at terrain, thus meaning that the explosion epicenter will happen where ever the target manages to go. 

As such, the modified mini-nukes only purpose is a trap for the unwary.

**Comment by kevingranade** [comment]
Same change can remove the launcher, simple.

**Comment by AbsalomAchitophel526** [comment]
May as well replace mini nukes with the its component plutonium, then.

Is there any reason that the launcher, described as a "mortar," cannot target terrain?

**Comment by kevingranade** [comment]
The weight for the mininuke item is just for the warhead, attaching it to a projectile will make it strictly heavier.

It does however look like i screwed up the weights, i believe i based the new mininuke weight on the W48 and the yield on the W54 warhead used in the Davy Crockett weapon.

The weight should be about 23kg for the warhead, and it should probably be roughly the same everywhere it is used.

https://en.m.wikipedia.org/wiki/W48
https://en.m.wikipedia.org/wiki/Davy_Crockett_(nuclear_device)

**Comment by sfsworms** [comment]
Would there be a way to have the launcher but still with a timer fuse? That way you could shoot and then use a few turns to run away from the blast radius.
