### ISSUE TITLE
Crane lifting insufficient

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25119]
With the recent #25037 increasing the tonnage of vehicle parts up to 4.5 tons each, at least one player has reported that crane lifting capacity is insufficient to handle these weapons. If this is the case, then adjustments to cranes (or the addition of a new crane type) may be necessary to keep these vehicle parts usable on custom vehicles. Lifting 9 is the minimum required to this end

(As a side note: The item description of the "steel boom" item for the boom crane claims it can lift up to 20 tons, when in-game it only lifts 2 tons. Whoever fixes the cranes might want to tweak that description, too.)

**Comment by Night-Pryanik** [comment]
It seems like there's just a typo in definition of lifting quality in json. Now it says `"LIFT", 4` while it should be `"LIFT", 40`.
