### ISSUE TITLE
Panacea causing error

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25117]
Posting this on behalf of Rosa # 1933 of discord, since I saw they didn't post an issue about it.

![unknown](https://user-images.githubusercontent.com/8593513/44613851-66d76700-a7d7-11e8-9f87-cbc541c647dd.png)

**Comment by alanbrady** [comment]
This is a problem in Rosa's build environment and not a bug in the game.  The PANACEA iuse function definitely exists.

Somehow the build is out of sync with her JSON files where the comestible has it, but the build is missing the code to use it.

Also for future reference, had this been a real issue it would have been nearly impossible to debug without any kind of context as to how it happened other than "I saw it discord".
