### ISSUE TITLE
Electric Jackhammer provides no advantage over Pickaxe 

### ISSUE THREAD

**Issue by vlad1492** [CleverRaven/Cataclysm-DDA#25128]
**Describe the bug**  
Using the Electric Jackhammer to remove pavement takes longer and increases hunger, thirst, and fatigue more than the same job using manual Pickaxe does.  Tested with STR of 8 and again of 20. No change. 

**To Reproduce**  
1. Pick a strip of pavement. Bring a loaded Electric Jackhammer and a Pickaxe. 
2. Open the Debug interface - 'edit player/npc' - 'you' - 'needs' - document current state of needs.
3. Mine a set number of tiles
4. Repeat with other tool. Compare results. 

**Expected behavior**  
Powered tool should do the job faster and with less cost to the body in the form of hunger, thirst, and fatigue.  It currently takes longer and costs a bit more resources.  

This may also be true for the gas powered tool, untested. 

**Versions and configuration(please complete the following information):**
 - OS: Windows 7 
 - Game Version 0.C-30994-g73c0277
 - Graphics version Tiles MXotto+
 - Mods loaded :  
 "dda",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "blazemod",
  "Tanks",
  "alt_map_key",
  "boats",
  "deoxymod",
  "ew_pack",
  "filthy_morale",
  "makeshift",
  "more_buildings",
  "mutant_npcs",
  "no_npc_food",
  "npc_traits",
  "realguns",
  "no_scifi",
  "no_survivor_armor",
  "PK_REBALANCE",
  "jury_rigged_robots"
]

**Comment by lethargicchii** [comment]
I've yet to use the jackhammer in game, but, it should be really loud and require ear protection, and after extended use should technically, if you want to push realism, give some sort of debuff to aiming crafting and such for a short time period. [HAVS](https://www.bcmj.org/worksafebc/hand-arm-vibration-syndrome-havs) these could be used as reasons to give it a large buff over the pickaxe.
