### ISSUE TITLE
Include Filters in Loot Sorting Zones [$20]

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#25134]
**Is your feature request related to a problem? Please describe.**  
I would like to be able to specify a filter similar to how you can filter in the advanced inventory to the loot zones along with all the pre-existing loot zones.

**Describe the solution you'd like**  
If we could add one more zone that will take priority over the others that can contain any amount of filters like the advanced inventory filter. For instance I have leather patches, rags, etc in the spare parts pile, but they are away from my clothing pile and so they are sorted into the wrong place. If we have the filtered loot pile, I can specify I want leather patches, rags, etc near my clothing pile.

**Comment by pjf** [comment]
This is something that I would love, so I've just [posted a bounty](https://www.bountysource.com/issues/62601664-include-filters-in-loot-sorting-zones). :) To make sure this is clearly defined, I'll consider the bounty awardable if:

(

1. A "filter" zone exists which can accept an advanced-inventory style filter, OR
1. Existing zones get a filter option which can accept an advanced-inventory style filter

) AND

1. There exists a way to give a filtering zone priority over regular zones. (Existing zone list ordering is fine.)

Many thanks!

**Comment by pjf** [comment]
[Bounty updated to $100](https://www.bountysource.com/issues/62601664-include-filters-in-loot-sorting-zones), because apparently I can and will spend all my time sorting items by hand. :)
