### ISSUE TITLE
Can't load game with build 7770

### ISSUE THREAD

**Issue by hitmancho** [CleverRaven/Cataclysm-DDA#25135]
I get the following error when trying to load the game with the latest build:

 DEBUG    : Error: data/mods//dda/../../json/mapgen/zoo.json: line 192:20: duplicate entry in json object

        { "chance": 75, "item": "vending_drink", "x": 20, "y": 1 }
      ],
      "place_item":
                   ^
                    [
        { "item": "glass_shard", "repeat": [ 5, 10 ], "x": 10, "y": 22 },
        { "item": "glass_shard", "repeat": [ 5, 10 ], "x": 11, "y": [ 21, 23 ] }

 
 FUNCTION : bool main_menu::load_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 890

I have changed nothing with my build in the past weeks I've been playing on this save game and I've encountered no problems updating the game to the newest build just before 7770. Also, I can't find any mod I have that adds a Zoo building to the game, though I have more_buildings and cityside (More City Locations). Here's a full list of loaded mods on the save:
"dda",
  "Tolerate_This",
  "bio_mod",
  "SD_Magcrafting",
  "craftgp",
  "FIC_Weapons",
  "realguns",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "alt_map_key",
  "Hairs",
  "Mining_Mod",
  "mutant_npcs",
  "npc_traits",
  "national_guard_camp",
  "BIGRIVER",
  "more_locations",
  "FujiStruct",
  "more_buildings",
  "cityside",
  "oa_additional_buildings_mod",
  "Experimental-Z-Level",
  "Urban_Development",
  "boats",
  "deoxymod",
  "ext",
  "SEEDYSPOT",
  "WEIRDWORLD",
  "Arcana_A",
  "PK_REBALANCE_A",
  "blazemod_A",
  "winning_dda",
  "more_classes_scenarios",
  "RL_Classes",
  "filthy_morale",
  "no_reviving_zombies",
  "speedydex",
  "StatsThroughSkills",
  "Tanks"

**Comment by SagitarTSeleth** [comment]
I get a similar error when I try to load my game on #7770 (which causes the load to fail):

 DEBUG    : Error: data/mods//dda/../../json/mapgen/zoo.json: line 192:20: duplicate entry in json object


        { "chance": 75, "item": "vending_drink", "x": 20, "y": 1 }
      ],
      "place_item":
                   ^
                    [
        { "item": "glass_shard", "repeat": [ 5, 10 ], "x": 10, "y": 22 },
        { "item": "glass_shard", "repeat": [ 5, 10 ], "x": 11, "y": [ 21, 23 ] }

 
 FUNCTION : bool main_menu::load_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 890

**Comment by levstk** [comment]
I'm getting the exact same error, it's from the object containing multiple "place_item" lines. There's another instance of the error at line 578.

` DEBUG    : Error: data/mods//dda/../../json/mapgen/zoo.json: line 192:20: duplicate entry in json object


        { "chance": 75, "item": "vending_drink", "x": 20, "y": 1 }
      ],
      "place_item":
                   ^
                    [
        { "item": "glass_shard", "repeat": [ 5, 10 ], "x": 10, "y": 22 },
        { "item": "glass_shard", "repeat": [ 5, 10 ], "x": 11, "y": [ 21, 23 ] }

 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 743
`

` DEBUG    : Error: data/mods//dda/../../json/mapgen/zoo.json: line 578:20: duplicate entry in json object


        { "chance": 55, "item": "trash", "x": 10, "y": 2 }
      ],
      "place_item":
                   ^
                    [
        { "item": "steel_lump", "chance": 25, "x": 7, "y": 16 },
        { "item": "steel_chunk", "repeat": [ 1, 3 ], "x": 7, "y": 16 },

 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 743
`
