### ISSUE TITLE
Cargo space broke on vehicle but didn't drop items until it broke again

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#25147]
**Describe the bug**  
This one is a bit confusing. I drove up the road like usual, came across a tank drone, I was going 60, couldn't turn fast enough, boom. dead. Brought myself back to life to realize that nothing dropped from my vehicle even though the cargo space was clearly 100% broken. I do as I do and remote hack the tank drone, it follows me to my vehicle and protects while shooting tank shells at every unfortunate hostile creature in viewing range. Somehow some zombie got 1 tile from it, the tank drone fired flamer, etc, fired a shell and boom goes me and my vehicle again. dead. Brought myself back to life again and noticed that all the stuff that was in my previously broken cargo space was scattered within a 5x5 around the center of my vehicle.

It's possible the title is wrong and it's something different that I can't quite explain.

**To Reproduce**  
Steps to reproduce the behavior: (I honestly can't say for sure if its reproducible this way, but my description is 100% accurate so maybe follow that exactly for reproduction)
1. Spawn vehicle with cargo space, but lots of stuff inside, it blows up 2 times to become visible.
2. Blow it up (and yourself for the heck of it)
3. Notice nothing dropped after it was 100% destroyed.
4. Blow it up again (and yourself. again.)
5. Stuff is spewed on the ground from cargo space.

**Expected behavior**  
Cargo space drops stuff immediately when broken

**Versions and configuration(please complete the following information):**
 - OS: win 7
 - Game Version 0.c-31146-g4dd8ad1
 - Graphics version tile
 - Mods loaded none

**Comment by kevingranade** [comment]
Needs to be reproduceable without savescumming.
Also theres a difference between broken and destroyed.

**Comment by Qrox** [comment]
What do you mean you brought yourself back to life?

**Comment by CoroNaut** [comment]
Broken=destroyed in my book, I mean broken such that it needs to be replaced by another cargo space. I have my own way to bring myself back. I use the same character to find all the bugs I find because they are around every corner.

**Comment by alanbrady** [comment]
Just to clarify here, you're filing bugs against a build with patches that aren't upstream?  Even if your patches don't touch code your filing bugs against, this needs to be done against a 100% upstream build.

It is 100% valid to use custom patches to debug issues or try to find issues that are upstream.  What I would recommend doing if you want to do something like that is:
1. Put up a PR, saying explicitly not to merge it but just to demonstrate some issue
2. Link it to a filed issue with reproducible steps on the upstream build which demonstrates how the problem manifests to an actual user.

**Comment by CoroNaut** [comment]
Just to be clear, I'm not saying that dying is part of the issue, like kevin said, this would be a pointless bug to put up if your character won't be playing with said bug. 
But anyways, the same exact thing happens if just disallow the game to update your character file, but allow map changes and just reload the save, you instead have to walk all the way back to where you died, but its the same exact thing.
Also I don't know how to do anything git related lol.

**Comment by BevapDin** [comment]
Cargo parts hold their content until they are completely destroyed. They contain their content even when broken (HP == 0, shows as grayed part name).

This is different from seats (which drop their passenger as soon as they are broken) and other parts that loose their function when broken.

it is easy to reproduce: put something into a cargo part, smash it until its broken (but not removed from the vehicle).

This is explicitly handled in the code: code that queries for CARGO parts explicitly allows for broken parts (e.g. calls `part_with_feature( "CARGO", false )` - the `false` indicates the broken status is not checked). But even that is not consistently done everywhere.

----

The question at the end is (@kevingranade): when should cargo parts drop their content: when being broken (grayed out) or when destroyed?

**Comment by kevingranade** [comment]
When destroyed.
