### ISSUE TITLE
Reloading magazines still in guns or underslung barrels causes error message

### ISSUE THREAD

**Issue by Canivir** [CleverRaven/Cataclysm-DDA#25140]
**Describe the bug**  
When trying to reload a gun with a magazine with loose ammo, or reloading a gun with an underslung barrel an error message pops up and no reloading happens. Reloading is still possible if reloading a magazine itself, or single reload guns. Error message is the following:

 DEBUG    : reload target is null, failed to reload
 
 FUNCTION : void activity_handlers::reload_finish(player_activity*, player*)
 FILE     : src/activity_handlers.cpp
 LINE     : 1805

**To Reproduce**  
1. Make a player with a gun, magazine, and some ammo (gun needs to actually use a magazine). Or use a gun with an underslung barrel.
2. Empty the magazine/underslung barrel and load it into the gun.
3. Try to reload the gun/underslung barrel with loose ammo.
4. Error message pops up and gun stays unloaded.

**Expected behavior**  
A reloaded magazine/underbarrel.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.C-31152-g702c7a6 // Jenkins 7771
 - Graphics version: Tiles
 - Mods loaded: Happens even in a world without any mods, DDA or not.

**Comment by alanbrady** [comment]
:( This sounds like it's because of something I added, I will look at it.
