### ISSUE TITLE
bow hunter starting bow unbalanced

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#25144]
**Is your feature request related to a problem? Please describe.**  
the profession bow hunter start with the best bow in game. Compound bow seems to be heavily buffed somewhere along all the updates and bow hunter's starting weapon didn't get adjusted with it.

**Describe the solution you'd like**  
Change the bow to maybe an composite, or reflex bow.

**Describe alternatives you've considered**  
or just massively increase the points bow hunter profession requires, maybe to a 6 or 8.

**Comment by darktoes** [comment]
If you don't want it to be compound, then a recurve or longbow hybrid would be the most realistic option, and neither are too overpowered.

Then again, considering it's only a top tier bow and not something really amazing like a high-end bionic, maybe it could just go up a point or two?

**Comment by aierce** [comment]
22 damage bow, re-usable 16 damage, 8 pierce ammo is really really good. You basically won't have to look for upgrades anymore.
