### ISSUE TITLE
Error on using mouse to move character

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#25153]
**Describe the bug**  
Double-clicking to move causes an error that can be ignored after the character reaches the destination.

 DEBUG    : Tried to get invalid activity_type: ACT_NULL
 
 FUNCTION : const T& string_id<T>::obj() const [with T = activity_type]
 FILE     : src/activity_type.cpp
 LINE     : 20

**To Reproduce**  
Use the mouse to move by double-clicking on a tile.

**Expected behavior**  
Mouse move without error

**Versions and configuration(please complete the following information):**

 Win 10
 0.C-31173-ga58b380 (tiles)
Dark Days Ahead
Disable NPC Needs
Simplified Nutrition
Extended Realistic Guns
DinoMod
Vehicle Additions Pack
Tanks and Other Vehicles
[Save](https://drive.google.com/open?id=1sJCC_vKVMqm6J8t4cZxjg4JBUWFB5MyX)

Edit: Error can be ignored

**Comment by Robik81** [comment]
It is 99% bug introduced by my #25125 PR. I'l check it out.
