### ISSUE TITLE
Intermittent CI build failure: unable to open output file 'obj/bionics_test.o'

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#25150]
**Describe the bug**  
The CI build sometimes fails with error message `error: unable to open output file 'obj/bionics_test.o': 'No such file or directory'`

**To Reproduce**  
1. Make a PR
2. Wait for CI build to finish
3. It may fail with this error.

**Expected behavior**  
No such error happens.

**Comment by ZhilkinSerg** [comment]
Confirmed - see https://travis-ci.org/CleverRaven/Cataclysm-DDA/jobs/420672437
