### ISSUE TITLE
Sprayable fungicide cant be given as "contained" via debug menu

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#25152]
**Describe the bug**  
While clean water can be given bottled, sprayable fungicide can´t be contained. It just comes as a puddle of fluid in the inventory and therefore cant be loaded/reloaded.

**To Reproduce**  
1. Get into debug menu and find sprayable fungicide,
2. Press "f" for contained,
3. Give one or more units,
4. Try to reload a chemical thrower.

**Expected behavior**  
The fluid comes in a suitable container

**Versions and configuration(please complete the following information):**
 - OS: WIN 7
 - Game Version Build 7772
 - Graphics version Chesthole
 - Mods loaded: various

**Comment by Night-Pryanik** [comment]
For further notice: this is a, you know, debug feature, it's unsupported, and we usually don't examine such issues.
