### ISSUE TITLE
Drugs rebalance

### ISSUE THREAD

**Issue by tsaber** [CleverRaven/Cataclysm-DDA#25158]
What bugs me is that a lot of them are made worse than they are in regards to effect and how early you see consequence like long-term negative effects. Meth lasts so long in real life it would be op in game but if it were slightly more suggestive to reality I'd be happy.

 I offer to help or do it myself but I'd need a mentor.

Because sometimes the game seems like an anti-drug campaign to me.
Regardless of one's stance I'd like for it to be neutral in regards to drugs when we shoot and murder and eat the things we eat in game. That seems hypocritical. I'm not going to watch Pablo Escobar. I watched Scarface.

For example:
**Meth** will keep you awake and active more than 24 hours before you crash. In game it lasts but a mere hours and then you have massive penalties.` 

**Cocaine** on the other hands lasts very long while it should be the one to get out of the system and make you feel withdrawal within an hour max.`

**Adderall(or L-amphetamine)**  or **(Dexedrine for R-amphetamine; they work almost the same)** lasts about 3-5 hours and leaves gradually. I think in game it's shorter than that but I never thought of it as disproportionally short.  

I propose them ordered so you'd have cocaine as the most intense immediately and quick decline within an hour. Adderall with a slower onset but a steady effect for about 3 hours before it fades out in 2-3. 

And lastly an improved meth. Maybe it was the trait combo of my character at the time it was a pretty pathetic life of that man to be honest. It ended in frozen butchery of him. 

Oh yes let me not forget you can eat marijuana raw if you have no other option. I needed it and I couldnt use the weed because i had no papes :( and I felt stupid because I have it here and I'm desperate and maybe a little less pain is going to save me.

What do you think?

**Comment by kevingranade** [comment]
If you think dda is unrealistically anti-drug, you're cherry-picking positive effects.

There are any number of negative effects we aren't dealing with, and a huge number of positive effects that the game is simply inventing.

In other words, we arent trying to realistically depict drugs in any way, if we were they would actually be worthless.

**Comment by tsaber** [comment]
I'm not cherry-picking positive effects. That's an insult Kevin. I say give them a realistic picture. Not in any way twisted. Can you put a little more effort into this? I made an effort to write down my idea and you insult me and slay the hammer like the bored judge on a friday? Have some decency.
