### ISSUE TITLE
AI tag Hit By Player

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#25159]
**Describe the bug**  
Hit by player effect is showing.

I don't know if this is apart of this issue, but when I went tabbed back to cdda after reading the hit by player tag, it was completely frozen, no key would do anything. (but disregard this portion for this issue)

**To Reproduce**  
1. Hit an npc following you

**Expected behavior**  
This doesn't show up

**Screenshots**  
![capture](https://user-images.githubusercontent.com/24307650/44631694-9ef8ba00-a93d-11e8-8388-b976ab601486.PNG)

**Versions and configuration(please complete the following information):**
 - OS: win 7
 - Game Version 0.c-31146-g4dd8ad1
 - Graphics version tiles
 - Mods loaded none

**Comment by Night-Pryanik** [comment]
To be clear - are you looking at your player character @-menu, or NPC?

**Comment by CoroNaut** [comment]
I'm looking at the npc.

**Comment by Night-Pryanik** [comment]
> This is a bug if YOU have it

This.

**Comment by CoroNaut** [comment]
Ok, gonna close this issue then. There should probably not be any debug tags like this visible unless an actual bug occurred.
