### ISSUE TITLE
Unknown CTD

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#25163]
**Describe the bug**  
Sudden freeze followed by CTD with no error

**To Reproduce**  
Unsure. Seems to happen when fighting. The last two times it happened I was getting my aim ready while my NPC was engaged with a zombie with her cudgel. I was using a bow.

**Expected behavior**  
No CTD.

**Versions and configuration(please complete the following information):**
Windows 10
0.C-31190-ga8e08d9 (tiles)

Dark Days Ahead
Filthy Clothing
Disable NPC Needs
Simplified Nutrition
Extended Realistic Guns
DinoMod
Vehicle Additions Pack
No Antique Firearms
StatsThoughSkillsIV

**Additional context**
As I have no idea how to read the debug.log I have attached it. Also including a link to save.
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2322144/debug.log)

[Save Folder](https://drive.google.com/drive/folders/12E6MGrhznjx7kFJpB1I7WYZvK_xeKt_8?usp=sharing)

**Comment by Phenomphear** [comment]
It's definitely during fighting. I hit a Zombie with my bow with my NPC next to me and the game froze and CTD while the | bar for damage hovered in the air. Debug.log included. Latest crash is just above the last starting log.
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2322417/debug.log)

**Comment by alanbrady** [comment]
Do you happen to remember if there was a zombie technician in the area?

**Comment by Phenomphear** [comment]
I never saw any

**Comment by WojciechKrysiak** [comment]
It's possible that it's this: https://github.com/CleverRaven/Cataclysm-DDA/pull/25358 unfortunately I lack the skill to fix it without locks, which are not available in mingw.

**Comment by alanbrady** [comment]
@WojciechKrysiak neat, well done tho.  We may not be able to use a mutex but there's other solutions I think and I agree this does *soud* like the problem.

**Comment by kevingranade** [comment]
Fits the profile of the threading issue that was fixed by #25358 or perhaps a follow up PR.
