### ISSUE TITLE
Feces should not be considered food

### ISSUE THREAD

**Issue by svick** [CleverRaven/Cataclysm-DDA#25172]
Right now, all kinds of feces (incl. manure, bird litter and roach dirt) are categorized as "Food". I don't think that makes much sense: even though they have some nutrition, most characters wouldn't want to eat them, just like e.g. tainted meat. I think feces should be categorized as "Other" instead.

**Comment by Brambor** [comment]
Yeah, I encountered that as well and it made me think about scenarios in which it is a viable option.

**Comment by Nightquaker** [comment]
Hey, at least I can literally "eat shit" whenever I want, you know.

**Comment by G3Kappa** [comment]
Or add a coprophagia trait that gives you mood bonuses for it :grinning:

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
