### ISSUE TITLE
Zombies spawn and die in midair, leave hovering corpses.

### ISSUE THREAD

**Issue by Endovior** [CleverRaven/Cataclysm-DDA#25179]
**Describe the bug**  
In some multi z-level buildings, the player can find corpses hovering in open air. This seems likely to be the result of bad spawning behaviour. I've seen this before on a variety of second-floor buildings, but mansions seem _especially_ bad for it, likely as a result of their layout.

**To Reproduce**  
1. Create a new character.
2. Teleport to a mansion.
3. Go upstairs, look out all the windows; you'll probably find one or two.
4. For added fun, spawn a zombie necromancer; watch the hovering corpse rise and instantly die dozens of times without actually falling off the z-level.

**Expected behavior**  
Zombies should not spawn in open air. If they somehow find themselves in open air for whatever reason, they should fall to their deaths. This falling behaviour should be implemented in a way that actually moves the unfortunate zombie and its corpse and all of its possessions down a z-level. This process should emphatically not leave a magical hovering corpse that respawns and dies repeatedly.

**Screenshots**  
https://imgur.com/a/9ZYeqCu

**Versions and configuration:**
 - OS: Windows 10 Home x64
 - Game Version: 0.C-31154-gbed57c4
 - Graphics version: Both
 - Mods loaded: Dark Days Ahead, Filthy Clothing, Disable NPC Needs, Simplified Nutrition

**Comment by alanbrady** [comment]
Seems related to this https://github.com/CleverRaven/Cataclysm-DDA/issues/23537 and this https://github.com/CleverRaven/Cataclysm-DDA/pull/25059

**Comment by ssorpg** [comment]
I think what's happening is that without experimental z-levels enabled, `trapfunc::ledge()` in `trapfunc.cpp` simply does `c->die( nullptr );` for non-player creatures, and it doesn't send them down a level. It might be an engine limitation if the reality bubble only calculates the current z-level without experimental z-levels enabled, I don't really know.

**Comment by kevingranade** [comment]
Fixed by #28545
