### ISSUE TITLE
It says "wasted some materials" but all the materials are wasted

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#25171]
**Describe the bug**
When you screw up the recipe and _waste some materials_ you, in fact, always waste all the materials.
It makes sense that when you screw first rag in a trench coat, then you will not tear up the rest in rage.

**To Reproduce**  
1. Make a player with low skill in electronics.
2. Try to make recipe whose difficulty is higher than your skill and has multiple components that you need more than 1 off.
3. Repeat until you _waste some materials_ and check that you always loose all the materials.

**Expected behavior**
I would expect to lose only fractions of what I have used.
I would expect to actually stop when you screw up. (if not already implemented)

**Expected implementation**
Determine whether a recipe will fail on start of crafting. (if not already implemented)
Fail in X % of the recipe progression which means:
Waste X % of materials (rounded up so you always waste some when you waste them).
Stop at `max( X% of time progression, 1min)` time.

**Versions and configuration:**
 - OS: Windows 10
 - Game Version #7775, but it is happenning for long time
 - Graphics version Tiles
 - Mods loaded dda, StatsThroughSkills

**Comment by Brambor** [comment]
Does it really make sense to loose tin cans and glass jars, when making food into them? You at least seal the tin can but the jar is just closed. Did the PC shattered it? Where are the glass shards?

**Comment by kevingranade** [comment]
Addressed by #28254
