### ISSUE TITLE
Being attacked while heating food does not allow you to cancel heating.

### ISSUE THREAD

**Issue by Sorgklaan** [CleverRaven/Cataclysm-DDA#25183]
Pretty straight forward. If you try to heat any food, and you aggro a hostile, you will continue to heat the food with no option to stop and you will keep doing so until the hostile creatures kills you.

using version 0.C-31229-g5a2fec3

**Comment by Night-Pryanik** [comment]
As always, this process requires to be made long activity.

**Comment by ifreund** [comment]
I plan on fixing this later today if nobody else gets to it first
