### ISSUE TITLE
Crash on ascending stairs

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#25180]
**Describe the bug**  
Game crashes on ascending stairs.

**To Reproduce**
Save file: [Unga.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2324453/Unga.zip)
1. Load save file.
2. Don't stop butchering.
3. Go to evac shelter.
4. Descend and then ascend stairs.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 7780 (last experiental)
 - Graphics version Tiles
 - Mods loaded dda, StatsThroughSkills

**Additional context**
I think it is caused by #24291
```
17:14:12.869 : Starting log.
17:14:12.888 INFO : Language is set to: 'en'
17:14:14.458 WARNING : opendir [./mods/] failed with "No such file or directory".
17:14:14.485 SDL : src/sdltiles.cpp:2212: Failed to load audio file data/sound/Basic/Dark_Days_Ahead_demo_2.wav: Couldn't open 'data/sound/Basic/Dark_Days_Ahead_demo_2.wav'
17:14:17.684 : couldn't parse color: c_gray
17:14:17.843 WARNING : opendir [./save/Unga/mods] failed with "No such file or directory".
17:14:19.897 INFO : Loaded tileset: ChestHole
17:14:29.202 MAP : src/map.cpp:6964: Empty locations for group GROUP_SEWER at uniform submap 7,8,-1 global -29,3680,-1
17:14:29.202 MAP : src/map.cpp:6964: Empty locations for group GROUP_SEWER at uniform submap 8,8,-1 global -28,3680,-1
17:14:29.203 MAP : src/map.cpp:6964: Empty locations for group GROUP_SEWER at uniform submap 6,8,-1 global -18,3680,-1
```

**Comment by saladasa** [comment]
I just experienced this same crash when ascending some stairs. Latest experimental.

**Comment by Vasyan2006** [comment]
>I think it is caused by #24291

It can, but I am not sure.
After ascending the stairs you will reload plants into the buble and recalculate their stats. But if you will just go or teleport away and return (it will be technically the same reloading) plants will stay where they are. Only ascending the stairs will crash the game.

**Comment by Brambor** [comment]
@Vasyan2006
Thanks for the work, I hope it will be resolved soon. I cannot really help as I cannot program in C 😞

**Comment by ZhilkinSerg** [comment]
Callstack

![image](https://user-images.githubusercontent.com/16213433/44679433-a0aca580-aa43-11e8-82f4-e09e4c499b84.png)

**Comment by Vasyan2006** [comment]
>get_crops_grow Line 107
 time_duration seed_age = time_duration::from_turns( seed.get_var( "seed_age", 1 ) );

It will load "seed_age" var or set it to 1 turn for new plants.

>grow_plant Line 6565
const time_duration plantEpoch = seed.get_plant_epoch();

It works the same way as before. Nothing was changed here.

No idea, why these lines are mentioned.
I need computers 2 to understand the jargon.

**Comment by Brambor** [comment]
I didn't see the code.
@Vasyan2006 Maybe order of code? Is it equivalent to Python "undefined variable"? Maybe it gets the age of the seed, but it was just being added and not defined a variable? Or some miss importing?

Sorry for shooting into the blue, I want to continue with my game and there is no way I will be able to solve this.

**Comment by Robik81** [comment]
> I want to continue with my game and there is no way I will be able to solve this.

Just grab older version, no need to wait until it is solved if you want to play the game.

**Comment by Vasyan2006** [comment]
>Maybe order of code? Is it equivalent to Python "undefined variable"?
It will set variable "seed_age" to 1 turn for new plants (i.e. reset plant grow). That is why moving there and back is safe. Lets wait untill someone who can into programming will solve it. Just avoid stairs.

**Comment by saladasa** [comment]
> Only ascending the stairs will crash the game.

> Just grab older version, no need to wait until it is solved if you want to play the game.

> Just avoid stairs.

What if I've already gone down the stairs and can't get back up? Will my savegame still work if I grab an older version? Can I teleport myself and my NPCs out?
