### ISSUE TITLE
Changing window size options results in screwy window until restarting game.

### ISSUE THREAD

**Issue by Lorith** [CleverRaven/Cataclysm-DDA#25186]
**Describe the bug**  
Set new screen size settings in graphics options, save and exit menu, screen tries to display a compressed version in the same window size.

**To Reproduce**  
1: Start game
2: Open settings
3: Tab over to graphics
4: Set new height/width values
5: Hit escape and confirm saving
6: Enjoy your impossible to read menu

**Expected behavior**  
Changing window size settings either changes size of window or does not make any changes to the display until the game is restarted, like it used to.

**Screenshots**  
![image](https://user-images.githubusercontent.com/11392144/44692334-79001200-aa30-11e8-9068-497b5a40be53.png)

**Versions and configuration(please complete the following information):**
Windows 7, tiles, 0.C-31240-gcd18292

**Comment by Night-Pryanik** [comment]
Can't confirm this on latest experimental. @Lorith is this still an issue?

**Comment by Lorith** [comment]
Just tried it again with 8455 aka 0.C-36907-g0d68189 and get the exact same thing occurring as in the image above.  Settings used: 237/60, issue only exists until quit and restart occurs, though ideally it should either do that automatically when you save the config, or not attempt to resize the display.

Purely on guess: I would think that it saves the config and uses that to draw the display rather than storing it as a constant when it first loads?  Not sure if it is able to resize on the fly on another OS, so not sure how the code works for sure.

**Comment by Qrox** [comment]
Should be fixed by #41050.

**Comment by Night-Pryanik** [comment]
Ok, closing until reconfirmed.
