### ISSUE TITLE
[WIP] [CR] Delivery Packages (need C++ help)

### ISSUE THREAD

**Issue by cosmiccoincidence** [CleverRaven/Cataclysm-DDA#25194]
### **SUMMARY**
I'm currently working on making delivery packages a thing.
Upon opening a package you will get one of my predetermined package drops (list of drops below, and would appreciate feedback on said list). These drops will be categorized based on total volume and will come in 1 of 3 sized cardboard boxes... small(1L), medium(8L), or large(20L)... along with some packaging (either bubble wrap or balls of newspaper).

### **WHAT I NEED HELP WITH**
- [ ] The C++ work because I can't code, and even though what I'm asking for is probably pretty simple, I bet I'd still manage to mess it up, and I wouldn't know where to put the code.

More precisely, I need code that when a package is disassembled _or_ activated (your choice Mr. Hackerman) it breaks down into a cardboard box (small, medium or large depending on the package size), the package contents (based on the package size), and packaging materials (amount based on package size).
ZhilkinSerg made a basic example...

        "use_action" : {
          "type" : "unpack",
          "unpack_item_group" : "postcards"
        }

So to summarize it differently, what I want is...

_When a small package gets opened it..._ 
- selects one of my "small_package" item groups and drops said item group,
- drops a small cardboard box,
- and drops a small amount of packaging (randomly chosen between bubble wrap or newspaper balls).

_When a medium package gets opened it..._ 
- selects one of my "medium_package" item groups and drops said item group,
- drops a medium cardboard box,
- and drops a medium amount of packaging (randomly chosen between bubble wrap or newspaper balls).

_When a large package gets opened it..._ 
- selects one of my "large_package" item groups and drops said item group,
- drops a large cardboard box,
- and drops a larger amount of packaging (randomly chosen between bubble wrap or newspaper balls).

I would also like...

_When a newspaper ball gets activated it unfolds into one of the following..._ 
- "many_years_old_newspaper",
- "years_old_newspaper",
- "one_year_old_newspaper",
- "months_old_newspaper",
- or "weeks_old_newspaper".

The reason for the newspaper balls being an alternative to bubble wrap as a packaging material is to make getting bubble wrap (used in noise traps) from packages less common.

### **WHAT I GOT SO FAR**
What I got so far is...
- [x] 3 cardboard boxes of various sizes (one being the pre-existing cardboard box simply renamed to "small cardboard box"). The small has 1L of capacity, the medium has 8L of capacity, and the large has 20L of capacity.
- [x] 3 cardboard packages (similar to the 3 cardboard boxes but different in obvious ways).
- [x] A newspaper ball item (the item is made but it just needs code so it can be unfolded into a normal newspaper page).
- [x] A list of package contents sorted by the package size they will spawn from.
**If you have any suggestions for package contents to add or be removed let me know!**

**SMALL**
- _frying pan_
- _toolbelt_
- _boxer shorts X2_
- _briefs X2_
- _boxer briefs X2_
- _boy shorts X2_
- _panties X2_
- _bra X2_
- _sports bra X2_
- _pair of socks X3_
- _compression shorts, compression top_
- _long underwear bottom, long underwear top_
- _striped shirt_
- _flag shirt_
- _sweater_
- _pair of earmuffs_
- _hunting cap_
- _baseball cap X2_
- _balaclava_
- _bandana X2_
- _wool scarf_
- _bikini bottom, bikini top_
- _pair of mittens, knit hat_
- _pair of work gloves X2_
- _pair of moccasins_
- _pair of slippers_
- _pair of flip flops_
- _pair of heels & pair of stockings_
- _pistol bandolier_
- _holster_
- _ankle holster_
- _ankle shealth_
- _guy fawkes mask_
- _gas mask, gas mask cartridge_
- _pair of safety glasses_
- _pair of bifocal glasses_
- _pair of eye glasses_
- _pair of reading glasses_
- _pair of stylish sunglasses_
- _pair of sunglasses_
- _pair of contact lens, saline eye drops_
- _purse_
- _skinny tie X2_
- _pocket watch, monocle_
- _wrist watch_
- _game watch_
- _fancy watch_
- _gold watch_
- _teddy bear_
- _harmonica with holder_
- _telescopic umbrella_
- _knitting needles, yarn X5 (1 = 10 count), bundle of felt_
- _plastic canteen_
- _mugwort oil X10 (1 = 1 charge)_
- _thyme oil X10 (1 = 1 charge)_
- _cooking oil X5 (1 = 2 charges)_
- _charcoal water purifier_
- _fast noodles X5 (1 = 1 charge)_
- _dried rice (1 = 16 charges)_
- _dried beans X2 (1 = 8 charges)_
- _canned fish X2, canned veggy_
- _canned tuna X2, canned salmon_
- _canned clams X2, canned sardines_
- _canned chicken X2, canned meat_
- _canned tomatoes X2, canned pineapple_
- _canned veggy X2, canned fruit_
- _peanut butter candy X8, chocolate candy X8_
- _chewy candy X8, maple syrup candy X8_
- _powder candy stick X8, candy cigarette X8_
- _gummy vitamins X2 (1 = 10 charges)_
- _multivitamins (1 = 20 charges)_
- _pocket knife_
- _multi-tool_
- _duct tape_
- _permanent marker X4, paper (1 = 50 charges)_
- _coffee maker_
- _thermometer_
- _hotplate_
- _battery X4 (1 = 100 count)_
- _camera, SD-memory card (clean)_
- _transponder, receiver_
- _amplifier X2_
- _circuit X3_
- _power supply_
- _processor X2_
- _small lcd screen X2_
- _USB drive X2_
- _RAM X4_
- _cell phone_
- _cell phone flashlight_
- _mp3 player_
- _flashlight_
- _clock_
- _alarm clock_
- _radio_
- _two way radio X2_
- _soldering iron, solder_
- _101 home repairs (book)_
- _101 crafts for beginners (book)_
- _popular mechanics (book)_
- _dungeon masters guide 6th edition (book)_
- _coffee powder, marijuana (a common way to mail weed across the states is with coffee to hide the smell)_
- _tuned mechanism_
- _match trigger_
- _brass catcher_
- _supressor_
- _compact supressor_
- _acog scope_
- _rifle scope_
- _pistol scope_
- _telescopic sight_
- _red dot sight_
- _rail laser_
- _underbarrel laser_
- _rifled barrel_
- _ported barrel_
- _shortened barrel_
- _barrel extension_
- _lightweight furniture_
- _ergonomic grip_
- _forward grip_
- _adjustable stock_
- _folding stock_
- _recoil stock_
- _glock .40 magazine X2_
- _glock .40 extended magazine X2_
- _sig pro .40 magazine X2_
- _p226 .357 magazine X2_
- _USP 9mm magazine X2_
- _mp5 magazine_
- _mp5 extended magazine_
- _m9 magazine X2_
- _m9 extended magazine X2_
- _USP .45 magazine X2_
- _walther ppk magazine X2_
- _desert eagle magazine X2_
- _FN FAL magazine_
- _FN FAL extended magazine_
- _SCAR magazine_
- _SCAR drum magazine_
- _Ruger .223 magazine_
- _small electric motor X4_
- _solar cell X4_
- _vehicle tracking device_
- _back up beeper X2_
- _antibiotics_
- _weak antibiotics_
- _antifungal drug_
- _antiparastic drug_
- _anti septic drug_
- _aspirin_
- _bandages, disinfectant_
- _medical gauze, disinfectant_
- _caffeine pills, caffeine gum_
- _nicotine gum X2_
- _cigar, refillable lighter_
- _dayquil, cough syrup_
- _potassium iodide_
- _calcium tablet_
- _soap X4_

**MEDIUM**
- _bleach_
- _ammonia_
- _liquid fertilizer_
- _acetone_
- _pot X2_
- _teapot_
- _pewter bowl X4, tin plate X4_
- _ceramic bowl X4, ceramic plate X4_
- _glass bowl X4, glass plate X4_
- _glass cup X8_
- _spoon X8, fork X8_
- _mineral water X10_
- _vegetarian MRE X6_
- _chicken MRE X3, ravioli MRE X3_
- _beef MRE X3, hotdog MRE X3_
- _laptop_
- _briefcase_
- _go bag_
- _leather backpack_
- _emergency blanket X2_
- _sleeping bag, rollmat_
- _american flag_
- _unfolded poncho X2_
- _skirt X2_
- _dress_
- _sundress X2_
- _long-sleeved shirt_
- _hoodie X2_
- _sweatshirt_
- _jumpsuit_
- _house coat_
- _jean jacket_
- _lab jacket_
- _light jacket_
- _leather jacket_
- _flannel jacket_
- _trenchcoat_
- _leather trenchcoat_
- _sports jersey_
- _robe_
- _snuggie_
- _jedi cloak_
- _kimono_
- _pair of rollerblades_
- _pair of rollerskates_
- _pair of hiking boots_
- _pair of golf shoes_
- _pair of lowtop tennis shoes_
- _pair of western boots, cowboy hat_
- _ski pants, ski goggles_
- _bike helmet_
- _dinosaur suit_
- _wolf suit_
- _striped pants, hot pants_
- _pants X2_
- _work pants X2_
- _cargo pants X2_
- _shorts X2_
- _cargo shorts X2_
- _denim shorts X2_
- _dress shirt X2, leather belt_
- _dress shirt, pair of dress shoes_
- _clown suit, pair of clown shoes_
- _chef's jacket, toque_
- _rain coat, rain hood_
- _red leather jacket, white glove_
- _army pants, army jacket_
- _winter army pants, winter army jacket, pair of winter army gloves_
- _beekeeping suit, beekeeping hood, pair of beekeeping gloves_
- _pair of dance shoes, the book of dances (book)_
- _pair of boxing gloves, boxing monthly (magazine)_
- _football, pair of cleats_
- _basketball, basketball shorts_
- _pair of elbow pads, pair of knee pads, bike helmet_
- _dress, bra, beauty magazine_
- _french maid clothes, french maid hat_
- _nano skirt, knee high boots_
- _bondage suit, bondage mask_
- _pair fuzzy cat ears, fuzzy cat tail, vibrator_
- _pair of leather cat ears, leather cat tail, leather corset, blindfold_
- _katana, scabbard, all about swords (book)_
- _tanto, sheath, knife fighter's notes (book)_
- _swiss army knife, water purification tablets, large canteen, outdoor survival guide (book)_
- _first aid kit, pocket guide to first aid (book)_
- _transponder, receiver, circuit X2, amateur home radio for enthusiasts (book)_
- _throwing knife X5_
- _slingshot, marble X20_
- _curved needle, thread (1 = 50 count), sew what? clothing! (book)_
- _vacuum sealer_
- _oil lamp, lamp oil_
- _chemistry set_
- _radio car box_
- _the gun owner's handbook (book), modern riflemen (book)_
- _arms and armor of imperial china (book), the art of japanese armor making (book), swords of the samurai (book)_
- _computer science 101 (book), computer science 301 (book)_
- _cucina italiana (book), sushi made easy (book), bon appetit (book)_
- _the homebrewer's bible (book)_
- _family cookbook (book)_
- _romance novel, erotic novel_
- _sports novel, war novel_
- _drama novel, thriller novel_
- _adventure novel, western novel_
- _crime novel, mystery novel_
- _saxophone_
- _jumper cables_
- _saddle X5_
- _foot crank X5_
- _motorbike battery_
- _motorbike alternator_
- _electronics control X2_
- _electric motor_
- _enhanced electric motor_
- _large electric motor_
- _storage battery case_
- _solar panel X2_
- _emergency vehicle light (blue) X2, emergency vehicle light (red) X2_
- _floodlight X2_
- _stereo system X2_
- _camera display, security camera X2_
- _car headlight X2_
- _1 cylinder engine_
- _small 1 cylinder engine X2_
- _small engine block X2_
- _tiny engine block X5_
- _car battery_
- _medium storage battery X2_
- _small storage battery X5_
- _car alternator_
- _truck alternator_
- _motorcycle kickstand X2_

**LARGE**
- _television_
- _medium suitcase X2_
- _large suitcase_
- _basic fishing rod, fishing hook X10, pair of fishing waders_
- _composite bow, quiver, plastic arrow X8, archery for kids (book)_
- _crossbow, wooden crossbow bolt X8_
- _wet suit, wet suit hood, dive knife, dive bag, diver's watch_
- _motorcycle helmet, motorcycle armor, motorcycle pants, pair of motorcycle boots_
- _hatchet, tent, pitching a tent (book)_
- _violin, violin case, golden fiddle_
- _acoustic guitar_
- _bagpipes, kilt_
- _folding bicycle_
- _foldable light frame, foldable basket_
- _seat X2_
- _muffler_
- _reinforced solar panel X2_
- _upgraded solar panel X2_
- _minifridge_
- _minifreezer_
- _sheet metal X8_
- _wired sheet metal X4_
- _4 cylinder gasoline engine_
- _2 cylinder v-twin engine_
- _6 cylinder gas engine_
- _V6 diesel engine_
- _V8 gas engine_
- _V8 diesel engine_
- _massive engine block_
- _large engine block_
- _medium engine block_
- _small engine block X5_
- _tiny engine block X10_
- _storage battery_
- _simple metal wheel X2_
- _motorbike wheel X2_
- _car wheel X2_
- _bicycle wheel X2_
- _small wheel X4_
- _wide wheel_
- _sheet of glass X2_

### **WHAT I STILL NEED TO DO**
What I still need to make...
- [ ] Item groups from the above package drops list ("small_package_contents_1", "small_package_contents_2", "medium_package_contents_1", "medium_package_contents_2", etc.).
- [ ] A package delivery truck and mail truck
- [ ] A distribution hub location.
- [ ] An item group called "packages", where small packages are most likely to spawn and large packages are least likely to spawn.
- [ ] Add spawns for the item group "packages" to post offices, and delivery trucks, add small packages to "mail" item group to spawn in mailboxes, add spawns for medium and large packages outside the front door of some houses.

**Comment by Regilith** [comment]
It could be fun to add a "Merchandise Distribution Hub" location with a bunch of these packages on conveyor belts, and empty cardboard boxes lying around.

**Comment by cosmiccoincidence** [comment]
@Regilith Not a bad idea. I was thinking of just adding them to the post office. But I like your idea a bit better.
Maybe Ill add the distribution hub which will have all the sizes of packages, but still add just small packages to the post office...

**Comment by Regilith** [comment]
@cosmiccoincidence +1 on the post office, post offices could use some love. Perhaps spawn the boxes inside the safes and back room?

**Comment by Dansiman** [comment]
> unfolded poncho X2

Wouldn't it make more sense for the box to contain folded ponchos? Likewise for the emergency blankets, and anything else that's foldable. Manufacturers _do_ tend to fold things that can be folded, before packaging them up for distribution.
