### ISSUE TITLE
Anthill a little bit to close to evac shelter start.

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#25199]
**Describe the bug**  
I started with evac shelter. There is an anthill in the area. On crafting outside, close to the shelter, like on cars, all to often there comes the message "xy ant spotted. Stop with what you do  Y/N?" 
Also in some rare occasions the ants attacked. While I did my thing.
This is really an annoyance.

**To Reproduce**  
I don´t know how to reproduce that reliably, as this is based on map gen including RNG (I asume).

**Expected behavior**  
The starting location should be a save zone. Like in the good old DOOM 1, DOOM 2 games, a level start was always designed so that nothing aggroed on the player.
As far as I understand, there is a value for how close an anthill is allowed to be to the starting location. This should be a little bit higher, like an increase of 2-3 map tiles.

**Screenshots**  
![evac shelter - anthill](https://user-images.githubusercontent.com/42423698/44718337-0a6a9500-aac0-11e8-831a-e59461f8f433.jpg)
The evac shelter is a the player location "@". The anthill is SSE of that.

**Versions and configuration(please complete the following information):**
 - OS: WIN7
 - Game Version: Dont know the build from when map was generated.
Right now: 0.C-31272-gd4670e3 (tiles) with latest Jenkins Build
 - Graphics version Chesthole
 - various

**Comment by Night-Pryanik** [comment]
> The starting location should be a save zone.

I'd not call this "Expected behavior". This is just another location among the many. The fact that it is a default location for a default scenario doesn't make it special in any way.

**Comment by CoroNaut** [comment]
I usually do a challenge abandoned start with 2.5-3.5x zombies, I go into my games expecting to be staring a zombie in the face as I spawn in :wink:

**Comment by kevingranade** [comment]
> The starting location should be a save zone.

There is no safe zone, if your shelter is overrun at first, you need to move.

**Comment by PenceGL** [comment]
Sometimes this just happens... it's the beauty of procedural generation, in my opinion. Since it's a new character and you haven't invested any time or skills into them, just go ahead and start again. It's part of the fun.

**Comment by Szara-ManOfHonor** [comment]
Hell I'd jump for joy with an ant hill so close by. You'll never have to go looking for food. Just give them some space otherwise.
I haven't seen an anthill in my games in over a year.
