### ISSUE TITLE
Slimespring spawning

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#25192]
**Is your feature request related to a problem? Please describe.**  
It is frustrating when you accidentally create a slime spring, but I love the ability to spawn then. I often accidentally eat too much or drink a bit too much water. It also doesnt make sense that drinking too much can make you go from very hungry to starving by spawning another one. I doubt a starving slime mutant would have the nutrition to create another budding organism. Cells slow down their reproductive cycle when starved and so should a slime mutant.

**Describe the solution you'd like**  
Could we get a warning message when eating/drinking too much will spawn a slime spring like the one you get for overeating with a Y/N option? Also you shouldn't spawn anymore when malnourished or starving.

**Describe alternatives you've considered**  
Maybe we could just make this an activatable mutation and not have it spawn uncontrollably when you overeat?

**Additional context**

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
