### ISSUE TITLE
Heat from fire while reading (IGNORE THIS I WAS WRONG DELETE PLEASE)

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#25205]
**Describe the bug**

@nexusmrsep 

Hi
I have my food near a fire to stop it from freezing been doing this for about 2 ingame days all is fine.
Decided to read a book and when I had finished the food near the fire was FROZEN.

its as if the fire heat output is PAUSED while reading causing the food/water to freeze.

**To Reproduce**  
light wood stove fill with two by fours loads of them so fire wont go out.

place food/water near fire skip time till its not forzen (if it is) etc.

get a book and start to read it till level up.

Check food near fire its now frozen solid.

**Expected behavior**  
For food to remain COLD at least while reading

**Screenshots** 
https://i.imgur.com/DfiX0bA.png

https://i.imgur.com/WrtMbdg.png

https://i.imgur.com/LDnqF2V.png

**Versions and configuration(please complete the following information):**
 - OS: Win 10 64bit
 - Game Version 64bit tiles 7789
 - Graphics version Tiles
 - Mods loaded A lot https://i.imgur.com/fN5J3kD.png

**Additional context**  
Thanks

**Comment by stk2008** [comment]
Hmmmm

OK was trying to do more tests to confirm my findings I aint so sure I am correct now sorry if I am not.
I am finding that at night maybe the temp is dropping so much that not even one fire can prevent stuff from freezing?.

Shall report back once I do more tests :)

**Comment by stk2008** [comment]
Ok even with x2 wood stoves it still freezes in early morning when temp drops.
its even reading -1c where I stand which is also where the food is placed.

https://i.imgur.com/bsgNYzM.png

so not sure whats up.

Thanks again

**Comment by nexusmrsep** [comment]
> Decided to read a book and when I had finished the food near the fire was FROZEN.

Ok, I need more feedback for reproducing - exact day of season, season length, time of day (hour if possible), observed temperatures (if possible) and ambient outside temperature (not affected by fire). Were you reading at night or day? How far was your food located from fire(s)?  Many factors are in play, so there are at least few possible reasons for this behavior **not** being a bug, for example this reason:

> I am finding that at night maybe the temp is dropping so much that not even one fire can prevent stuff from freezing?

Fire does not guarantee that everything near it thaws. It only raises temperature by certain amount, so in **very** cold ambient temperatures it might not be enough. But multiple sources add-up their heat radiation, so two or in extreme cases maybe three fires should work as long as they affect common tile.
You had a thermometer showing -1C on your screenshot and this is temperature affecting food here - my initial evaluation is that outside ambient temperature is very low.

**Comment by stk2008** [comment]
Roger that

I shall get back to u tomorrow with more info
thanks for replying. :)

**Comment by stk2008** [comment]
OK

Killing this PR not sure if its readable after a PR is killed but if it is.

Sorry to Nex I was wrong I should have tested my findings more it had nothing to do with reading books ETC.
Shall open a new PR later on today when I have time to do proper tests :P 

Thanks
