### ISSUE TITLE
Error on preset character creation

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#25203]
**Describe the bug**  
Got an error when using a preset I made for a character

**To Reproduce**  
1. Create the character I have
2. Use the preset menu to generate it

**Expected behavior**  
This doesn't give error

**Screenshots**  
The screenshots go in order, I see the error when its loading and verifying the map, then it brings me to the character creation screen to verify my traits/stats etc.
![capture](https://user-images.githubusercontent.com/24307650/44724581-201c9200-aaa1-11e8-91ee-e9320c996aa5.PNG)
![capture2](https://user-images.githubusercontent.com/24307650/44724586-2448af80-aaa1-11e8-8f17-98281b9bd818.PNG)

**Versions and configuration(please complete the following information):**
 - OS: win 7
 - Game Version 0.C-31236-g981effa
 - Graphics version tile
 - Mods loaded none

**Comment by AMurkin** [comment]
It's obsoleted item.

**Comment by CoroNaut** [comment]
Removed 1st_aid_survivor item from preset template file and it works without error
