### ISSUE TITLE
Awl Pike weight

### ISSUE THREAD

**Issue by Didrigo** [CleverRaven/Cataclysm-DDA#25209]
I am new here, so... Hi. And sorry by the english 

I  came across whitch an real comum problem, weapons weight in games. This time is the awl pike.

![image](https://user-images.githubusercontent.com/42777561/44733788-b4e1b880-aabe-11e8-8a78-507651ef8adf.png)

This is the wrong weight, is more then two time heavier then a real one. I propose a chance to 3-4,5 kg. 

Plus: Is extreme rare a weapon witch more than 4,5 kg 

Here some links to help me.

http://www.higgins-collection.org/artifacts/2870.1

http://myarmoury.com/talk/viewtopic.18651.html

https://en.wikipedia.org/wiki/Pike_(weapon)

Thank you for your attention and if a did some thing wrong, tell me

**Comment by EirenexTheDragon** [comment]
i think it is done on purpose to increase the cost of moves per attack.

**Comment by Regilith** [comment]
[GAME_BALANCE.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GAME_BALANCE.md) states for damage per move values (with +hit and Rapid Strike modifiers buffing the number):

> 26-35 - Good dedicated weapons or the most dangerous of tools. Wood and fire axes, steel spears, electric carvers, kukris, bokken, machetes, barbed wire bats.

> 36-45 - Weapons of war, well designed to kill humans. Wakizashis, katanas, broadswords, zweihanders, combat knifes, battle axes, war hammers, maces, morningstars.

Some comparison item dpms (taken from item browser):
Broadsword: 38.74
Zweihänder: 33.73
Katana: 30.43
Halberd: 29.38
Glaive: 27.14
Steel spear: 24.82

Current awl pike has dpm of 27.15

Awl pike of weight (4.5kg) would have a dpm of 30.61

Awl pike of weight (3.0kg) would have a dpm of 35.09

Current dpm puts it on the "low" end of late-game weaponry. It is the only weapon besides bullwhip with REACH3, which allows a 3 tile reach attack, which is incredibly powerful, arguably the best weapon modifier. Bringing its dpm up to 30-35 would make it the best weapon in the game, bar none.

**Comment by kevingranade** [comment]
Sounds like we could drop the weight and either nerf damage, or apply an "unwieldy" flag to drop attack speed instead of relying on weight.

**Comment by cainiaowu** [comment]
Well, we already have the "to_hit" value, according to GAME_BALANCE.md
The awl pike should be: -2(default) +2(grip) +2(length) -2(striking surface) -2(balance) = -2(total).
So just change the to_hit is enough.

**Comment by Didrigo** [comment]
I would like to show this side effect of excessive weight
![screenshot_5](https://user-images.githubusercontent.com/42777561/44759961-0ddb3c00-ab13-11e8-9e55-9bef465e023d.png)

I can reach 3 holes but can throw just 1?

**Comment by Didrigo** [comment]
> Current dpm puts it on the "low" end of late-game weaponry. It is the only weapon besides bullwhip with REACH3, which allows a 3 tile reach attack, which is incredibly powerful, arguably the best weapon modifier. Bringing its dpm up to 30-35 would make it the best weapon in the game, bar none.

I agree, but the problem with the awl pike not being realistic persists. It's not intended to be used in individual combat, but in battle formations. At the moment, the pike's occupying the place other weapons should. If it is more powerful than others, why not rebalance it in some other way, say, a chance for the wielder to be disarmed or limit its attack to a certain distance only?

**Comment by AdriaanRenting** [comment]
This is Matt Easton from ScholaGlatiatoria, who I consider an absolute expert in the field,  talking about the disadvantages of pole arms.
https://www.youtube.com/watch?v=YpUcsIwW0kQ
It might give some inspiration on how you could balance them, but my general take from it is that they're the ideal weapon for the zombie apocalypse.
- Best against unarmored opponents
- Generally much better in a one-on-one fight than a sword.
- Disadvantage against sword wielders if they specifically target your hands. (not really a Z thing)
- Hard to walk around with in daily life and while working other weapons of war (not the biggest issue in the cataclysm either)
- easier to grab. (maybe an issue with grabber Zs, but not really in the current game mechanics)

Matt has several other videos about pole arms, but this one seemed best suited to inform this conversation.

**Comment by Didrigo** [comment]
> - Best against unarmored opponents
> - Generally much better in a one-on-one fight than a sword.
> - Easy to learn by a inexperienced person.
> - Disadvantage against sword wielders if they specifically target your hands. (not really a Z thing)
>- Hard to walk around with in daily life and while working other weapons of war (not the biggest issue in the cataclysm either)
> - easier to grab. (maybe an issue with grabber Zs, but not really in the current game mechanics),

This is for the most of pole arms, but not for awl pike. The awl pike isn't 1x1 weapon, increasing your pros and cons of an spear


The alw pike is really hard to use in close combate, you can't retract an weapon of 3m or more.

Look to an alw pike
![1024px-rocroi _el_ultimo_tercio _por_augusto_ferrer-dalmau](https://user-images.githubusercontent.com/42777561/44857474-43347680-ac46-11e8-8d57-28d7ce19287e.jpg)

**Comment by JacobKessler** [comment]
It would be cool to see differing grips (fire modes?) for polearms to switch between reach-capable (thrusting) and good defense (more like a pointy quarterstaff and short jabs), and then things like the awl pike could be given a choice of thrusts at range 3 (only) or awkward bashing at range 2 (and nothing at range 1 - if something closes, you would need to drop it and pull a different weapon, which is why in that picture people have swords too)
