### ISSUE TITLE
Game crash when Interacting with Camp Manager

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#25208]
**Describe the bug**  
Game crashes(no error message) when I ask my camp manager what needs to be done (option a)

**To Reproduce**  
Start a NPC base
Talk to camp manager
Press a
game crashes(no error message)

**Expected behavior**  
I expect to get the menu which lets me assign a job to a NPC. Recent versions had this working just fine.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version [from the main menu, e.g. 0.C-31229-g5a2fec3]
 - Graphics version [Tiles]
 - Mods loaded [Filthy clothes, NPC traits, more buildings, PK rebalancing]

**Additional context**

**Comment by Vasyan2006** [comment]
This crash occurs if the camp has farm fields wih planted crops.
It happens on line 3585 in mission_companion.cpp but I cannot find its reason in the code before it.
```
    bay.load( omt_pos.x * 2, omt_pos.y * 2, g->u.posz(), false );
```
Savefile for testing:
[Cologne.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2328897/Cologne.zip)

**Comment by Orange01gaming** [comment]
Weird, so if I remove the crops it should work fine?

**Comment by ZhilkinSerg** [comment]
Callstack is similar to one in #25180:

![image](https://user-images.githubusercontent.com/16213433/44745164-9d7eeb80-ab0f-11e8-883c-d94e6282bc32.png)

**Comment by Regularitee** [comment]
@Orange01gaming 

["NPC fields must be updated to include caring for plants and new crop balance."](https://github.com/CleverRaven/Cataclysm-DDA/pull/24291#issuecomment-410237482)

It looks like Vasayan2006 was already aware that the farming patch would break the NPC camps a month ago, but the PR was implemented without it ever being fixed...?

I'm not sure how it ever got merged, knowing it would break other game systems in advance.

**Comment by ZhilkinSerg** [comment]
> It looks like Vasayan2006 was already aware that the farming patch would break the NPC camps a month ago, but the PR was implemented without it ever being fixed...?

That was comment not about a crash.
