### ISSUE TITLE
Doesn't let me refill tank in a car with water from another tank

### ISSUE THREAD

**Issue by Bsonnete** [CleverRaven/Cataclysm-DDA#25200]
Game version: 7789

Operating system: Windows 7

Tiles or curses: Tiles

Mods active:

### Expected behavior
The tank outside of the car should appear in the list

### Actual behavior
![image](https://user-images.githubusercontent.com/24325818/44718668-29086600-aa97-11e8-9e94-98ef8f65f834.png)

### Steps to reproduce the behavior

1. Install an empty tank in the car
2. Choose Fill and choose said tank
3. Outside tank doesn't appear on the list

**Comment by kwl01skz** [comment]
Duplicate #24991
