### ISSUE TITLE
Crafting plastic chunks from cash cards recipe has two of same tool

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#25216]
**Describe the bug**  
Two integrated sets are included in the crafting tools required

**To Reproduce**  
1. Craft plastic chunk from cash card

**Expected behavior**  
Only one of these should be labeled

**Screenshots**  
![capture](https://user-images.githubusercontent.com/24307650/44751774-1158ce00-aae7-11e8-97e6-14292fd1b066.PNG)

**Versions and configuration(please complete the following information):**
 - OS: win 7
 - Game Version 0.C-31236-g981effa
 - Graphics version tiles
 - Mods loaded none

**Comment by Brambor** [comment]
That could just wait for me to get into tools, which I'm planning to do in the near future.
These are the tools for this recipe:
```"tools": [ [ [ "surface_heat", 6, "LIST" ], [ "soldering_standard", 10, "LIST" ] ] ],```
The problem will be that integrated toolset is in both, `soldering_standard` and `surface_heat`.

I'm planning to work with that as I will attempt to implement #25215, so I might as well make sure that every tool is there only once.

**Comment by Theundyingcode** [comment]
I put that recipe in ~4-6 months ago.  The idea was you could simply melt/heat-press the cards together or optionally, you could use a soldering iron to "weld" the edges of the cards together resulting in a sheet of plastic. 

Simple fix would just be to remove the "welding" option.

**Comment by kevingranade** [comment]
Fixed by #27990
