### ISSUE TITLE
Clean Water not working on Farm Plots

### ISSUE THREAD

**Issue by WMGreywind** [CleverRaven/Cataclysm-DDA#25218]
**Describe the bug**  
Inability to use Clean Water to irrigate farm plots.

**To Reproduce**  
1. Have Clean Water in inventory.
2. Have no other water sources near farm plot to be watered.
3. Attempt to water farm plot.

**Expected behavior**  
Expected that clean water should be applicable in watering plants. If clean water can be used in washing machines, then why can't clean water be used in farm plots.

**Versions and configuration(please complete the following information):**
 - OS: Windows 8
 - Game Version 0.C-31286-gef53413
 - Graphics version [Tiles]

**Comment by alanbrady** [comment]
Just to check, was it cold or frozen clean water by chance?

**Comment by hameleona** [comment]
Can confirm it doesn't work even if it's normal temperature.

**Comment by Kenshkrix** [comment]
Beginning of  iexamine::plant_watering has this:
`
    int water_charges = crafting_inv.charges_of( "water" );
`
Going to want to change this to also check for clean water.

**Comment by alanbrady** [comment]
> Beginning of iexamine::plant_watering has this:
int water_charges = crafting_inv.charges_of( "water" );
Going to want to change this to also check for clean water.

Haven't looked at it myself but that makes sense.

**Comment by ZhilkinSerg** [comment]
Fixed by reversal of #24291.
