### ISSUE TITLE
Plants need weeding literally as soon as you finish weeding on default settings.

### ISSUE THREAD

**Issue by Lorith** [CleverRaven/Cataclysm-DDA#25223]
**Describe the bug**  
Plants need weeding the instant you finish weeding them.

**To Reproduce**  
1. Download game, make world, make character
2. Get dirt mound + seeds (buckwheat used for test) and fertilizer
3. Plant seeds, water, fertilize
4. Stand south of plant
6. Hit e83 to weed plant north of you
6. Goto 4

**Expected behavior**  
Playing on default settings should allow more time between weeds growing than it takes to remove them.

**Screenshots**  
I missed the proper plot twice, but was weeding the same plant for almost four hours before it said I didn't need to weed it.
![image](https://user-images.githubusercontent.com/11392144/44762786-3dd80e80-ab16-11e8-87b0-fb52369f2c52.png)

**Versions and configuration(please complete the following information):**
Windows 7, tiles, 0.C-31240-gcd18292, no mods

**Comment by Lorith** [comment]
Even in that case, it shouldn't need weeding every minute.  And 6x would be much faster than that still.  Apparently there is no sanity cap.
![image](https://user-images.githubusercontent.com/11392144/44763633-2864e380-ab1a-11e8-996d-185f55e40b31.png)
In this case, I did not move, nor did I weed any plot except the one directly north of me.  When I ran out of weeds, I waited one turn and more weeds were there.

**Comment by Lorith** [comment]
And actually, I went ahead and set it to 91 day seasons just to check...
![image](https://user-images.githubusercontent.com/11392144/44763764-a7f2b280-ab1a-11e8-9964-62f23586bdaa.png)
Every 12 seconds there are new weeds on 91 day seasons.

**Comment by Lorith** [comment]
> "weed_susceptibility": 1.0, // (optional, default is 1.0). Multiplier for damage to plants health from weeds. If set to 0.0 weeds will still consume plants water and fertilizer, and therefore damage indirectly. 

No, you still get weeds, and they still use fertilizer and water that the plant needs.

**Comment by tyrael93** [comment]
That's lame.

**Comment by ZhilkinSerg** [comment]
Fixed by reversal of #24291.
