### ISSUE TITLE
Pickaxe and electric jackhammer can no longer drill through solid rock

### ISSUE THREAD

**Issue by saladasa** [CleverRaven/Cataclysm-DDA#25225]
**Describe the bug**  
Applying the pickaxe or electric jackhammer on solid rock results in the following message "You can't dig/drill there."

Likely related to #24787

**To Reproduce**  
1. Spawn a pickaxe or an electric jackhammer.
2. Apply it on a solid rock wall.

**Expected behavior**  
Until a recent update, this action resulted in the 'solid rock' being removed, dropping rocks and limestone. Walking into the 'solid rock' is supposed to work too, if automine is enabled. This does not work either. 

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-31289-gb2ec5b2
 - Tiles
 - Mods: Filthy clothing, Disable NPC needs, Simplified nutrition, Mining mod, Beta National Guard Camp, More buildings

**Comment by ZhilkinSerg** [comment]
What is `solid rock wall`? We have only terrain named `solid rock` in mainline (with id=`t_rock`) and it is perfectly mineable with either jackhammer or pickaxe.

Can you provide more details? Savegame with mentioned terrain which you cannot mine would be very useful.

**Comment by ZhilkinSerg** [comment]
You are using Mining Mod (https://github.com/DangerNoodle/mining-mod) which was not updated to these changes. I've reported issue in mod repository - https://github.com/DangerNoodle/mining-mod/issues/16.
