### ISSUE TITLE
Hard to craft items fixes: ANFO/RDX components

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#25239]
**Describe the bug**  
As originally reported in #25074, some recipes are unnecessarily difficult to craft.

    ANFO charge / RDX charge
    Craft time is irrelevant here since it's disassemblable.
    Before fixes #22226 and #22377 amount of required components was simply astronomic. Now it's just somewhat tedious. This one should probably go to honorable mentions category if/when #24698 will be fixed.

For the numbers:
1 ANFO charge <-> 70 ANFO <- 1260 ammonium nitrate <- 126 nitric acid
Nitric acid main source is lab and each spawn is 3 units of NA so 42 bottles. Since it's a huge barrel full of explosives it sounds fair. Usefulness of such an expensive explosive device is another question.
1 RDX charge <-> 60 RDX + 200 HMTD

60 RDX <- 60 nitric acid + 600 hexamine + 24 sulfuric acid (2/gren
200 HMTD <- 500 hexamine + 100 hydrogen peroxide (conc) + 40 acetic acid
Hexamine spawns only in labs and on scientists' bodies, is only 20 per box and is quite rare. (2 boxes from the whole central lab? Come on!) Concentrated hydrogen peroxide is only(?) from labs in 3 unit bottles. Alternatively you can craft it from regular hydrogen peroxide - common medical drop, but it's even worse since it comes in 3 unit bottles too and it's 5 HP -> 1 HPC. I still think it is a leftover from the old bug.
Nitric acid and hexamine amount in RDX is intimidating but is mostly irrelevant since you can get RDX from grenades (2 from grenade so 30 grenades. With lots of grenadiers in lab armories lately it should be easy.)

**Expected behavior**  
Most recipes are reasonably straightforward to craft.

**Additional context**  
Skilled survivors should be able to set up tabletop Haber and Ostwald processes to manufacture ammonia, nitric acid, and saltpeter out of the air. Production might be a little slow (250 mL of ammonia per 2 hours) but the required pressure and temperature range ( 150 psi, 1100 F) is something that a survivor with pressurized tanks and a forge could provide. Biggest issue would be adding platinum as a material and a recipe for forging a platinum grill, but the process of making a platinum grill for these processes was a problem that was solved in 1902 so I feel a survivor with Fabrication 8+ should be able to handle it.

**Comment by vegarbg** [comment]
Hexamine could also be found in field campsites or on campers' bodies; see [hexamine fuel tablet](https://en.wikipedia.org/wiki/Hexamine_fuel_tablet). Other than that, it seems like something that should be possible to [synthesize from ammonia and formaldehyde](https://en.wikipedia.org/wiki/Hexamethylenetetramine#Synthesis,_structure,_reactivity), which can be [produced from methanol](https://en.wikipedia.org/wiki/Formaldehyde#Industry). I don't know exactly how those are produced, but I'm sure a survivor with Cooking 8 or more could manage.

**Comment by vegarbg** [comment]
I've been thinking about the Haber and Ostwald processes. Since there already is a recipe for ammonia in the game which is pretty straight forward only needing chemical making 2 and a few common ingredients, I don't think it's critical to add the Haber process. But thinking along those lines, do we actually need a special tool for the Ostwald process?

There is an existing recipe for nitric acid which uses sulphuric acid and saltpetre. We could just assume chemical making 2 includes catalysts. Then all we need to do is add another recipe which resembles the Ostwald process, using ammonia and water as ingredients.

**Comment by kevingranade** [comment]
If you want, you can manually do a search for the various precursors in game, try and audit the spawn lists, or write a test that makes assertions about their appearance rate.  AFAIC this issue was about the mechanisms though, meaning it's done.
