### ISSUE TITLE
Hard to craft items fixes: Alternate Heroin ingredients.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#25235]
**Describe the bug**
As originally reported in #25074, some recipes are unnecessarily difficult to craft.

    Heroin
    Diff: 6 -> expected time ~57 mins
    Craft time: 2 mins
    Chance of success per try: 3.51%
    Avg. tries to have one success: 28.5

Probably the worst recipe to learn right now. Because of extra short duration it has 3.51% chance to be learned each time you craft it, but the real problem is it's only made from 40x oxycodone and it's a rare drug drop that spawns in bunches of 10. So you will need 4 rare drop rolls for just a single attempt. Still haven't finished this with something like 10 tries.
And from gameplay point of view this recipe is quite useless. If you're an addict your best choice in context of the cataclysm is to get off the needle ASAP. Even if you can't or just need some of the stuff in your veins RIGHT NOW you have much better chance of stumbling upon drug dealer bodies with heroin on them then getting a book and enough of oxycodone in time.

**Expected behavior**  
Most recipes are reasonably straightforward to craft.

**Additional context**  
It looks like the recipe for heroin should be updated to include other opiates, especially morphine, as possible ingredients.

**Comment by Shinino** [comment]
Alternate take:  Drugs are not easy to make.  Even the 'easy' one, meth, has a tendency to blow things up if you don't do everything right.  They generally require a lab, kitchen et al.  I would say that heroin, cocaine, et al SHOULD be hard to make, if not nearly impossible.  I'd simply argue that not EVERY thing should be able to be recreated, or easily recreated.  This -is- a post-apocalyptic wasteland.

**Comment by mlangsdorf** [comment]
but heroin is basically refined morphine. you should be able to make heroin from morphine and other opiates. It doesn't need to be easy, but if you have the Cooking skills, chem lab set up, and precursor chemicals, it should be possible.

**Comment by Rivet-the-Zombie** [comment]
Maybe we could make it from those mutated poppies that grow all over the place.

**Comment by cosmiccoincidence** [comment]
Dibs on this issue!
I want to add opium...
poppy flowers > opium > heroin
also
morphine > heroin
and
codeine > heroin
