### ISSUE TITLE
Hard to craft items fixes: Saltpeter for misc explosives

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#25238]
**Describe the bug**  
As originally reported in #25074, some recipes are unnecessarily difficult to craft.

    Incendiary / Explosive / Spiked home-made rockets
    Diff: 5 / 4 / 3 -> expected time 27.5 / 11.3 / 3.6 mins
    Craft time: 20 / 30 / 8 mins
    Chance of success per try: 72.7% / 265% / 222%
    Avg. tries to have one success: 1.375 / 1 / 1

Numbers look good, but don't forget that that's at skill level 13. At s.level 8 (relatively easy to obtain without venturing into the lab and crafting mutagens for half a year) they will be 1.625x worse. You will need at least 2 + 2 + 3 = 7 rocket candies so it's 350 of saltpeter (4 drops). You can get saltpeter only in lab and school I think and you're not really swimming in it since you will need to save it up for nitric acid -> ANFO/RDX craft too.

**Expected behavior**  
Most recipes are reasonably straightforward to craft.

**Additional context**
Saltpeter should show up in more places: farms, home improvement megastores, and gardening supply stores look like reasonable places.

**Comment by Shinino** [comment]
Saltpeter should also naturally appear in caves -- anywhere with organic material in caves tends to have it.  Bat guano is a good source.

**Comment by vlad1492** [comment]
Should be able to extract it from bird litter too
