### ISSUE TITLE
Travois don't carry enough volume!

### ISSUE THREAD

**Issue by Ironreaver8** [CleverRaven/Cataclysm-DDA#25244]
During a recent hunting trip in game I managed to nab a coyote and a dachshund. I was carrying a Travois around so I could carry things back, but it struck me as pretty weird that a coyote couldn't fit on the Travois, but something as small as a wiener dog just barely fit, so I went ahead to do some research on Travois in general and saw video evidence repeatedly of people using home made Travois made with thick twigs and string to carry full sized people and deer around.

The Travois should probably at least carry 100 volume, just a little over a deer's volume. They're supposed to do that already, but I understand if that's a little too much volume for something like a Travois--- even if it makes so much noise from use.

Video proof and reference of a Travois being made and being used to carry a person around: https://www.youtube.com/watch?v=vCpo_giGWOM

**Comment by CoroNaut** [comment]
Potentially add heavy travois instead of change current one? I most definitely see your point.

**Comment by Shinino** [comment]
Deer are classified as 'LARGE' creatures.  A dead deer is 92.5L -- changing the capacity of a travois is trivial -- but would have huge changes, as cows are also 'LARGE' creatures, and obviously you wouldn't load a dead cow on a travois.   

One option may be downgrading the size on deer to MEDIUM, which should lower the volume, then slightly adjusting the travois size if needed from there.
