### ISSUE TITLE
Sort items in alphabetic order in inventory

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#25254]
**Is your feature request related to a problem? Please describe.**  
Alphabetic order makes finding things easier.

**Describe the solution you'd like**  
Change the inventory screen "i" so that it sorts items within their category in alphabetic order. IT is way to hard to find that pair of boots under all thoose other pair of xyz items when you have 15-20 items worn.

**Describe alternatives you've considered**  
Using "/" all the time works but appears to be more effort than just snapping with the eyes to the item in the list.

**Comment by Brambor** [comment]
It is sorted in order that it has been put on/worn layers, not sure now. This is useful as well, because you can put the bags down before fighting, they would be top layer/last item worn because of previous fight.

I'm just saying there should be research done from the feature requester, why is the current system like that and what would your request make worse, e.g. what I have just described.

It could also be chosen to be sorted in preferred way (selecting the way in game), I'm not saying it couldn't.

**Comment by Androwski3000** [comment]
So how should I research this? Could you maybe give an example how to research this?

Right now I Wear 32 items of which 1 is a backpack. I dont play the style right now to drop the load bearing bear before fighting and dont like it much anyway. So there is not much advantage having the items sorted in chronological order while I just want to recheck some on the wristwatch/pair of steeltoed boots/pair of elbow pads.

**Comment by Brambor** [comment]
In this case, I'm talking about removing features. When somebody makes it and merges their PR, it would remove the ability I was talking about - see chronological order and remove clothing based on that. Is there another equally convenient way to do what was possible to do before? To be fair, I'm using advanced inventory to drop things right now to make sure I don't waste any moves, as Zs are heading my way. I'm not using the [+], the clothing overlay, as I'm afraid I will lose time putting the things into my inventory and then dropping them, which makes it + 100 moves flat per item.

I said it should be done, maybe it is more like, it is convenient for anyone reading and considering whether they want it or not and making sure, that it doesn't break anything - as making the tactics more tedious to pull off.

What you get from this should be:
1. There was a way to do something that will be invalidated by this idea, however, this can still be done another way, equally convenient and equally efficient - you should propose the new way.
2. Or, when we add in the game mechanics to make the player able to choose how to sort particular inventory, then no feature would be removed.

**Comment by rlsbrowning** [comment]
Perhaps if all items under each category (i.e. "WEAPONS", "TOOLS", etc.) were sorted alphabetically with the exemption being the "ITEMS WORN" category. Assigned keys would not be touched and highlighting may still be used for reassigned, regularly used items.

I am unsure how difficult or resource heavy that would be to code though unfortunately.

**Comment by Brambor** [comment]
@ cainiaow
> Sort items by alphabetic is not good for language that dont have an alphabet, yeah I mean Chinese.

That is actually ok with my intentions, if the items get sorted in English, then it will be sorted in all languages in such order. So in French it will not be sorted alphabetically, but it will preserve order (my intention). Same goes for Chinese.

**Comment by mrkybe** [comment]
@Brambor So you want the unfavorited items also sorted alphabetically?

**Comment by cainiaowu** [comment]
If you want the order stays the same through out languages, you need to sort them by item id.
