### ISSUE TITLE
The game lacks ways of communication regarding health issues

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#25258]
**Is your feature request related to a problem? Please describe.**  
It another game I had parasites for a long time but could not figure that out ingame. Only via using the forum I could find that out.
There where messages: "Your bowels ache", "Your body aches" and the guy could not sleep because of pain.
Having to consult the forums to find that out is bad. There should be a better chance ingame.

On the recent game I ate marlow berries maybe 6 seasons ago. Now there is a marlow related mutation. But to find that out I had to do alot of frustating digging.
The only thing I initially noticed was that my stats, all over 10, dropped to 10, 4, 4, 8.
Now I have no clue how to solve that. This is so frustrating that I don´t even want to start the game up any more.
This happened yesterday in the evening but this lack of info still annoys me that much, I could still use alot of swearwords to describe how this feels. :-/

So I can only ASUME that the stats drop is based on eating a marlow berry. Is it? Or is it still something else?

**Describe the solution you'd like**  
There has to be some kind of health log. Which contains info about health related info. Even the debug menu dont has much to offer regarding this.
The health log should log info about getting a cold, losing a cold, cough, mutations, stats drops, etc.

What other chances do I have to figure out now how to get my stats back? I invested several RL days into that game and the progress feels like mutilated now.

**Comment by PenceGL** [comment]
I definitely agree that being able to search/filter the log would be a huge improvement. There have been so many times when playing that I noticed some kind of thing wrong, mostly with equipment damage or vehicle damage, and had no clue on how to determine the cause. Sometimes important things just get lost in the spam, and the floating HP counters are easy to tune out after playing for a while.

What if the log was categorized into general feedback, combat feedback, and PC feedback, and hitting `TAB` or `<`/`>` could switch between the tabs? But the main game screen log would remain the same, a mix of all messages sort of as a snapshot.

**Comment by CoroNaut** [comment]
If you use the debug menu, you can edit your character and all their mutations to fix your save files. I agree with Brambor and his ideas of having the character gain information by themselves, this could definitely lead to a large AI breakthrough about having the AI reason things better.

**Comment by ZhilkinSerg** [comment]
It is completely normal that player receives feedback about certain effects/conditions affecting their character through certain messages (i.e. "Your bowels ache") and not with clear statement (i.e. `Infected with tape worm`) in status window.

**Comment by ennob** [comment]
I see why you find it frustrating but I look at that as just another way of exploring the game. It is OK to not know exactly why something is happening. In real life you might also feel sick and not know exactly why. After a few marlow berry related deaths, you would "discover" that these are not as wholesome as they look.

**Comment by nexusmrsep** [comment]
While i wholly agree with @ZhilkinSerg, I also think that beyond certain (high) level of first aid skill, there should be a way for some self diagnosis, even if it would require visiting medical facilities for some apparatus (autodoc?).

**Comment by ZhilkinSerg** [comment]
Having high first aid/survival skill, some medical book or advanced diagnostic tool at hand can provide more detailed conditions info.

**Comment by Androwski3000** [comment]
Im just thinking about it from my own experience. Im 37 now. When I was achild we had dogs with parasites in their spines and flea also. I had fleas from our dogs. LOL this is so funny now. Also I had different experience with parasites, not only with dogs. So while not everybody has experience with fleas like I do (LOL) everybody has some awareness and intelligence to come to conclusions.
What Brambor proposed sounds promising for an interesting feature. I´m still new to the game but the First Aid skill appears not much used right now to me. This could be a good reason to skill it now.

**Comment by kevingranade** [comment]
No progress for many months, if someone is interested in making a menu to surface various "feelings" the player has about their own body condition, that can certainly happen, but this issue isn't meaningfully driving that.
