### ISSUE TITLE
Boats do not have enough power to move at default "power": 50,

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#25256]
**Describe the bug**

"power": 50,

is not enough even for a character with a strengh  of 9.
I went into data\mods\Boats

whaleys_boats.json
and
b_inflatable_boat_parts.json

changed

"power": 50,  to 500 and now boat moves at a max speed of 14MPH which is WAY to fast I know.
I read that 3MPH is about the normal speed for a canoe

**To Reproduce**  
Spawn in a canoe and place near water it will say engine is not powerful enough

**Expected behavior**  
To move

**Versions and configuration(please complete the following information):**
 - OS: win 10 64bit
 - Game Version 7802
 - Graphics version tiles
 - Mods loaded DDA,Boats

**Comment by stk2008** [comment]
OK looking at it more

a diesel engine has a power output of 600 so to put paddles at 400 (minimum it starts to move at) is kind of stupid.

So instead I put muscles factor to 50 this works which allows us to keep power at the default 50.

but I am still able to move at 60MPH in a boat using hand paddles not sure how to fix this my self but thought I would have a look at it :).

**Comment by mlangsdorf** [comment]
m2c is the max % of engine power that can be applied at "cruise" speeds without damaging the engine or drawing extra fuel
exclusions is a list of keywords. no additional engine with a matching keyword can be installed. (this is what prevents you from installing a foot crank and hand rims, for instance)
E_STARTS_INSTANTLY means the engine starts instantly, as opposed to a diesel or gasoline engine that needs a few turns to start.
muscle_power_factor is the amount of vpower generated per point of operator strength over or under 8.
all of this is doc'd in doc/JSON_INFO.md

**Comment by Brambor** [comment]
Regarding the form of the issue. You may want to delete Screenshots and Additional context paragraphs.

**Comment by mlangsdorf** [comment]
The items partially duplicated in data/mods/Boats/b_var_wood_veh_parts.json and data/mods/Boats/b_var_veh_parts.json are incorrect, as well as duplicated, and both files should be deleted.

**Comment by AMurkin** [comment]
@stk2008 can you make a PR? If it's working it's better than nothing.
