### ISSUE TITLE
Vehicles should "pulp" zombie corpses

### ISSUE THREAD

**Issue by ennob** [CleverRaven/Cataclysm-DDA#25261]
This is a suggestion that impacts the collision code for
vehicles. That code is already due for refactoring (marked as a "big
TODO" in the code) but I'm still making this a separate issue as I
believe it can be implemented without too much trouble. 

**Is your feature request related to a problem? Please describe.**  

When zombies are run over by a vehicle, even at some speed, they are
left as "un-pulped" corpses. It seems strange that I can crush a zombie
with a tank but it will still get up after a while, whereas if i get
out and smash it with my fists, it is pulped beyond resurrection.

**Describe the solution you'd like**  
I would expect zombies struck by a vehicle at high speed to have a
certain percentage change of being pulped. The chance should increase
as a function of the weight and speed of the vehicle. I would suggest
computing the amount of energy absorbed by the zombie

`E = 1/2 * m * v^2`

This energy could then be multiplied by a modifier to account for
glancing blows or "lucky zombies". I would suggest the modifier take
the players driving skill and the speed (and toughness) of the zombie
into account.

The dead zombie would be pulped if the resulting "modified energy" is
above a suitable threshold.

If people agree that it is a good idea, I might take a stab at
implementing it.

**Comment by Night-Pryanik** [comment]
> just have all vehicles pulp corpses.

This will make corpses pulpable by swivel chairs, shopping carts and all other such lightweight "vehicles".

**Comment by ennob** [comment]
Yeah, a bit of math is definitely called for to make sure you cannot just insta-pulp everything with your shopping cart. The code is already computing vehicle momentum and other physical parameters, so it really isn't a big deal to incorporate enough parameters to make it realistic.

The main open question for me is whether it should be deterministic or if it makes sense to add randomness to account for glancing blows or "lucky zombies".  Other things in the game (e.g., crafting, health, mutations, etc.) have a random component, so I would argue that it is appropriate here as well.

**Comment by Endovior** [comment]
Yeah, some vehicles should be better at pulping zombies than others. I'd suggest that this be based on the colliding part. On the high end, road rollers and tank treads should pretty much auto-pulp whatever they drive over. On the low end, casters would probably just collide with corpses, potentially forcing you to clear a path. Wheels would fall in-between; though you might be able to pulp corpses with them, the process may do some damage to your tires! On the other hand, if you're driving over a zombie corpse, but only your vehicle's frame passes over it, I'd expect nothing to happen; the body is below your vehicle, after all.

If you wanted to specialize in the field, the clever survivor might add special equipment to their vehicle to make it more effective at pulping corpses; something like a [mine flail](https://en.wikipedia.org/wiki/Mine_flail) would probably pulp any zombies unfortunate enough to be in its path.

**Comment by PenceGL** [comment]
Well, right after my comment about all vehicles being able to do it, I did realize there would be restrictions, as with describing how a motorcycle or scooter or similar lightweight vehicle would be handled. Obviously nobody wants a swivel chair or a shopping cart to pulp corpses.

>You seem to be concentrating on premade vehicles one can find. But some math (probably just 'if above x weight = pulp') would be necessary, especially for player made vehicles. Shouldn't be too hard, though.

You're right, I forgot to think of vehicles that people build completely from scratch.

> If you wanted to specialize in the field, the clever survivor might add special equipment to their vehicle to make it more effective at pulping corpses; something like a mine flail would probably pulp any zombies unfortunate enough to be in its path.

This is a cool idea for sure. Looks like mass pulping is gonna get a lot easier soon.

**Comment by Androwski3000** [comment]
There are installable devices which one can put at the front of the vehicle: Spike, Steel ram and others. They should raise the chance for pulping when contact was made.
The roller wheel found on the "roller dozer" should insta pulp, if the rollers overrun a Z.
