### ISSUE TITLE
Please bring back the ability to disassemble Power CBM's

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#25266]
**Is your feature request related to a problem? Please describe.**  
Can we add back the ability to disassemble power CBM and mini nukes? With the removal of CBM recipes I can no longer disassemble Power CBM's for plutonium. This makes my rm13 armor almost worthless, as well as my mini reactor. 

**Describe the solution you'd like**  
Add back the ability to disassemble Power CBM, or make plutonium a much more common loot item in labs, or other locations. If this means we need to have a recipe maybe it could have a very high skill requirement? If I can distill mutagen serums better than the best labs before the apocalypse surely I can handle nuclear materials well enough.

**Describe alternatives you've considered**  
Buff rm13 armor/mini reactor to make up for the extremely rare fuel.

**Comment by vlad1492** [comment]
Suggestion: 
Buff plutonium as energy source by making atomic battery mod a permanent power source and minireactor permanent once fueled.

**Comment by Orange01gaming** [comment]
If we just buffed plutonium we should also make rm 13 have a permanent power source. What if all of these items irradiated the user when on? This could balance them so they are not too OP. We also need some sources of plutonium.

**Comment by vlad1492** [comment]
Always seemed a bit inconsistent to me.  Power CBMs installed produce no power, but act as a rechargeable battery for bionics.  When disassembled the plutonium cells can be used as a consumable fuel in other devices. Huh?  

I'd like to see a bit more uniform treatment.  Treat cells as a small power source.  Maybe have power storage split off as a different bionic from power generation.

**Comment by Orange01gaming** [comment]
Yeah that doesn't make any sense now that I think about it.

**Comment by Orange01gaming** [comment]
So if I'm hearing you correctly you think there should be a nuclear reactor cbm which generates power constanty? If so it would need some irradiation or other drawbacks

**Comment by kevingranade** [comment]
> Always seemed a bit inconsistent to me. Power CBMs installed produce no power, but act as a rechargeable battery for bionics. When disassembled the plutonium cells can be used as a consumable fuel in other devices. Huh?

This just highlights how inconsistent these recipes were in the first place.  I'm totally onboard with restoring disassembly recipes for these, but they need to basically be redone from scratch.

> So if I'm hearing you correctly you think there should be a nuclear reactor cbm which generates power constanty?

That's the request, but please dont do it.  It's been brought up many times and it makes no sense, nuclear material either produces a lot of power and is expended in the process, or produces a tiny trickle of power and lasts a very long time.

**Comment by kevingranade** [comment]
Power supply should yield some kind of ultra-dense battery, possibly a component in high energy weapons like a railgun.

**Comment by vlad1492** [comment]
I may be repeating myself rather than clarifying my argument here.  My cataclysm is out of coffee. 

The current description: "A nuclear powered battery used to charge advanced and rare electronics" suggests these produce a lot of power and are expended.  So why are they a component in rechargeable devices like Power CBMS and Advanced UPS?    

At the same time they *are* a permanent trickle of power for atomic lamps, nightlights, coffeemakers.  Which I love. 

A battery isn't a generator.  Maybe consider splitting into a fairly common ultracapacitor module for storing and releasing energy while plutonium cells become quite rare energy sources.

**Comment by Orange01gaming** [comment]
Seems like we can disassemble these again.
