### ISSUE TITLE
Dying of thirst despite the rain

### ISSUE THREAD

**Issue by lucasmr** [CleverRaven/Cataclysm-DDA#25264]
**Is your feature request related to a problem? Please describe.**  
Mostly early game, you might not have a source of water nearby, nor bottles/funnels. This forces the player to dive into somewhere to drink.

**Describe the solution you'd like**  
Some non-optimal way to gather water, like drinking directly from the pouring rain, puddles of water, or even using trees and bushes to collect some with a plastic bag. 

**Describe alternatives you've considered**  
You could also drink from rain gutters (https://en.wikipedia.org/wiki/Rain_gutter), but that would require that some constructions have it installed. All houses and the survival shelter could have this by default.

**Comment by Night-Pryanik** [comment]
> like drinking directly from [...] puddles of water

I don't know exactly what did you mean by puddles, but you can drink directly from the tile with water simply by examining it and drinking with your only hands.

**Comment by lucasmr** [comment]
That's nice, but the rain isn't forming any puddles by itself. Some random water puddles should be forming when raining and later evaporating.

**Comment by HeadWar** [comment]
Acid rain used to leave puddles of acid, didn't it? Should work for rain too.

Though I don't think you can drink spilled liquids. Maybe that should be possible? Not too proud to lick my spilled drink from the bar top,..

**Comment by lucasmr** [comment]
Yes, any rainwater is not safe for consumption, but should be an option to consume early on when you are avoiding everything and slowly gearing up.

**Comment by latogato** [comment]
I want rain gutters for so long, it would be awesome and really missing from the game.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
