### ISSUE TITLE
Removal of all CBM crafting makes microreactors impossible

### ISSUE THREAD

**Issue by Lorith** [CleverRaven/Cataclysm-DDA#25269]
**Describe the bug**  
The microreactor, adv microreactor, microreactor upgrade kit, and plutonium filter CBMs were designed to be crafted only as makeshift experimental CBMs.  Crafting CBMs was removed, thus they no longer exist outside debug.

**Expected behavior** 
Be able to acquire mentioned CBMs

**Comment by kevingranade** [comment]
Feel free to add drops of these somewhere it makes sense, but this is not a bug.  The CBM definitions were left in place in order to avoid removing players already-installed CBMs, but long term they are just as likely to be removed as to be added to.
