### ISSUE TITLE
Puppy explosions and morale penalties when having to fight them

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#25289]
**Describe the bug**  
Clouds of puppies roam. I don´t know. but so much puppies? I mean ok, packs of grown up labradors have to come somewhere. But puppie clouds? How is the survival rate with theese puppies?

Also the penalty for driving through them can be huge but there is not a penalty every time.
-I ran a group over for fun and had huge morale penalties (the last 3 pictures). Which is justified.
-Then I run another group over but they attacked me first outside of the car (1st picture). there I did not got a penalty.
-Then I had one occasion in a city / village where puppies and labradors attacked me and when I fough back, I got a morale penalty for killing.

Getting a penalty maybe depends on the race of the dogs. But there should not be a difference between dog races regarding that.

**To Reproduce**  
1. Drive across fields or along roads.

**Expected behavior**  
There are RL examples for dogs which have been tamed pets once, which then roamed in packs and even attacked humans. But thoose packs consist more of grown up specimen with a few puppies. Not like theese puppy clouds with a few adult animals.

**Screenshots**  
![puppy explosion](https://user-images.githubusercontent.com/42423698/44940683-3e7cd900-ad92-11e8-90d8-b7b27c51a123.jpg)
Picture 1: No penalty for killing them all by driving them over. This pack attacked me first.

![beagle puppy explosion](https://user-images.githubusercontent.com/42423698/44940693-6704d300-ad92-11e8-97b1-dbee128a3dc3.jpg)
Picture 2: The first time I encountered a puppy cloud. Maybe two weeks ago.

![beagle puppy explosion 2](https://user-images.githubusercontent.com/42423698/44940698-6bc98700-ad92-11e8-9170-6c61752be731.jpg)
Picture 3: Could not resist.

![beagle puppy explosion 3](https://user-images.githubusercontent.com/42423698/44940702-71bf6800-ad92-11e8-82f2-7436b8bfced5.jpg)
Picture 4: High penalty for running them over. I think time it is justified. There was no reason to run them over.

**Comment by cosmiccoincidence** [comment]
Could this issue be solvable  with some sort of population control prior to birth? Maybe we could have an ability to spare and neuter pets (not wild animals)? Or maybe some discreet chance that a dog won't seek mating as often?

**Comment by DracoGriffin** [comment]
This is two issues and isn't really clear on what's happening:

#24848 should have resolved the exponential puppy growth, so you probably need to update. However, any big "herds" will not be destroyed/killed from that fix, they just won't be breeding crazily. So, please post what version/build you're on as otherwise it's more than likely fixed.

Regarding the "second" issue with morale and puppies, that is detailed in #24944, [specifically this post](https://github.com/CleverRaven/Cataclysm-DDA/issues/24944#issuecomment-414069734) which would render this issue duplicate.

**Comment by tyrael93** [comment]
Just blacklist all vermins, all they do is clutter the game.

**Comment by Kevak** [comment]
#24848 definitely did not solve the exponential pupper growth. Been using the most recent build, updated via the launcher. 

![ss 2018-08-29 at 10 06 12](https://user-images.githubusercontent.com/13528006/44948765-57a87880-add8-11e8-940e-2e148424e425.png)

This does not look fixed to me.

**Comment by alanbrady** [comment]
To clarify, @Kevak you updated to latest build, but did you also generate a brand new world or are you still using the same world from before #24848

**Comment by Kevak** [comment]
World was generated after 24848. About 7ish days ago.

**Comment by paulenka-aleh** [comment]
The grows is still exponential. It does make sense in some sort... The problem that wildlife doesn't really tend to die naturally and on the other hand doesn't need any resources except time to breed. As a side note, time to breed doesn't seem to scale with season length which brings really odd feeling with 91-day seasons.

I'd propose these solutions:
1. Cap reproduction (e.g. at 10%?.. I guess it worth testing...) unless wildlife is fed (either by player or by food eating attack). It might be tricky to implement for breeding outside of reality bubble though.
2. Let these puppies horribly starve to death unless they're fed somehow too. At least until they grow up...
3. Scale reproduction and egg hatching time with season length?..

It would allow _occasionally_ see wildlife families. In extremely rare cases they would even grow into larger packs should puppies have some food to eat. It would allow to breed animals at the same time. And would require you to feed them.

**Comment by Androwski3000** [comment]
I think moral penalties are connected to puppy explosion because you have to deal with the explosions. So if puppy explosions shall be like that, then please with a more sophisticated connection to player morale.

**Comment by Androwski3000** [comment]
I think moral penalties are connected to puppy explosion because you have to deal with the explosions. So if puppy explosions shall be like that, then please with a more sophisticated connection to player morale.

**Comment by alanbrady** [comment]
Related https://github.com/CleverRaven/Cataclysm-DDA/issues/25302
