### ISSUE TITLE
The bottle jack is rated at 8 tons but cant be used to change a tire on a 10 ton vehicle.

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#25285]
**Describe the bug**  
As the headline says it. I worked as mechanic in at a John Deere dealership. A 8 ton jack can lift a 10 ton vehicle just fine, as it only has to lift ~50% of the weight on that specific axle. It does not have to lift the complete vehicle into the air LOL.
So if weight distribution between axles is 70% / 30 % that´s 7 tons on the heaviest axle. 7 tons /2 is 3,5t per wheel/side.
If you have bad luck, the weight on the side you want to change that wheel, you have to jack up 5 tons. (Like on a loaded trailer which dug a wheel into mud and then this wheel went flat, while the load like corn or wheat moved to the flat side.)

**To Reproduce**  
1. Get a 10 ton vehicle.
2. Try to change a tire on the vehicle with bottlejack in inventory.

**Expected behavior**  
With the bottlejack to change a tire is just EZ.

**Screenshots**  

![bug with veh tile 2](https://user-images.githubusercontent.com/42423698/44934916-03b57980-ad6f-11e8-8263-2f3ee4e8158d.jpg)
Check the weight at bottom left.

**Comment by Androwski3000** [comment]
This could be made skill based. So a noob mechanic reads the limit on the jack and things: "Now way we gona fix thge tire with that." Whereas the skilled mechanic asks the noob to go aside while he puts his shirt sleeves up.

**Comment by CoroNaut** [comment]
Technically if it has four wheels, you only need to offset <3 tons of weight to make up for the wheel. If it has more wheels, then it needs to offset even less weight.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
