### ISSUE TITLE
Add a poison antidote so that we dont have to pass our time for it to go away

### ISSUE THREAD

**Issue by OtakuSenpai** [CleverRaven/Cataclysm-DDA#25288]
Hello guys,

So, I got bitten by a cellar spider and all I had to do to get my poisoned status away was to wait for a specified period of time.
But instead of this, if we could add an item like "poison antidote" which clears the poison status from all types of animal bites then I think it could be better. The reason is that, suppose your fleeing a 'Z' and a snake comes and bites you out of nowhere and such such.....  :fist_oncoming:
       Also we hav all types of medicines from Xanax to aspirin to diazepin, but no poison antidotes, for which we hav to wait for a specified time. So adding tht item to the game couldnt hurt much.

**Comment by Duhuh123** [comment]
I use the blood filter cbm for this.

**Comment by OtakuSenpai** [comment]
yes but what if i am starting the game or i dont hav any cbms installed(which i was currently in) ?

**Comment by OtakuSenpai** [comment]
I know it can be easily passed off, but seeing the multitude of medical equipments, i dont think it could be a great hassle to add one.

**Comment by Night-Pryanik** [comment]
Well, you know, poisons are different. Snake has one type, spider has another. There is no universal antidote. Each type of poison require specific serum to neutralize.

**Comment by OtakuSenpai** [comment]
I thought the in-game poison were all the same because they show "poisoned" when i press '@'

**Comment by Regilith** [comment]
Night-Pryanik is talking about IRL, where each antidote is made specifically for one type of poison, and there is no catch-all version that exists imo.

In game, we do already have a catch-all antidote in Royal jelly, which instantly heals all poison effects.

It could be hand waved and introduced into the game by having the antidote made from a special monster or made from a futuristic machine. One cool way would be to extract the blood from dead venomous animals and turn it into antidote via recipe. Another is to have antidote machines in vetenarian's clinics and doctor's offices which can turn blood you give it into antidote, which you can consume (could be your blood, then save the antidote for later).

**Comment by kevingranade** [comment]
That's just because theres no reason to describe them differently right now, if we added antivenoms they would need to be specific to the source.
A bigger problem is that antivenoms are rare and unstable, I cant find a direct source on the subject, but iirc most antivenoms will be rendered useless just hours post cataclysm as refrigeration fails.

Generally speaking, you wouldn't even make anbantivenom for the kind if venom we have in the game, because it's not directly life threatening.

https://en.m.wikipedia.org/wiki/Antivenom

**Comment by OtakuSenpai** [comment]
Yeah, but maybe in-game we could just make a simple all-affecting antivenom which stays in effect for 3 seasons in-game time and create a recipe for the anti-venom in lieu of dead coyotes or mooses being injected with maybe blobs(since finding venoms from snakes will be difficult). In real life in India the cows are injected with venoms of rattlesnakes and such and a antivenoms are made from the lymphhatic serum of their bodies(if im stating it correctly).

**Comment by kevingranade** [comment]
If you want an antivenom, it could be farmed from animals the same way it is IRL, either by the player or by NPCs.  This requires capturing both livestock animals and acquiring venom samples.

I'm not interested in adding a super simplified antivenom.

**Comment by pingpong2011** [comment]
Just my own 2 cents - we can't syringe blood from corpses yet can we? Maybe the creature blood + chemicals = antivenom (one syringe), or a rotting "poison gland" from butchering (-enjoyment, poison on eat), or found in sealed jars. I always wanted more uses for syringes.

Maybe the poison could be segmented - one poison for neurotoxins (requiring an immunized animal - causes serum sickness, or another med), one serious for blood (cured by dialysis or something else pretty extreme), one for a basic "woozy/sick" effect. Could be staggered among less/more serious enemies, or one bite causes an annoyance, but repeated bites cause dangerous effects.

**Comment by Night-Pryanik** [comment]
> we can't syringe blood from corpses yet can we?

Actually, we can.

**Comment by kevingranade** [comment]
Closing because this is incredibly low on the list of priorities.

The reason venoms are so weak right now is there are no countermeasures, if we add countermeasures, we're also going to bump up the deadliness of venoms to make them nearly mandatory to obtain if you're going to tangle with venomous creatures.
