### ISSUE TITLE
Display of tile on vehicle as straight "normal" board but was installed as heavy duty corner board

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#25284]
**Describe the bug**  
On installing steel plating as heavy duty board two errors occur. 
1. The tile is shown as straight but was installed as corner.
2. The tile is shown in the colours of "normal" board, not heavy duty board.

**To Reproduce**  
1. Install a heavy duty board as top right corner.
2. As refererence install other heavy duty boards adjacent to it.
3. As refererence install other "normal" boards adjacent to it.

**Expected behavior**  
The tile is shown as corner tile in the little darker red of the heavy duty board.

**Screenshots**  
![bug with veh tile 1](https://user-images.githubusercontent.com/42423698/44934389-e97a9c00-ad6c-11e8-937c-f6c5eb99f54f.jpg)
Picture 1: Tile appears to be wrong.

![bug with veh tile 2](https://user-images.githubusercontent.com/42423698/44934294-9c96c580-ad6c-11e8-8248-050f04b89ed5.jpg)
Picture 2: The tile was installed as corner. See next to blue the cursor.

**Versions and configuration(please complete the following information):**
 - OS: WIN7
 - Game Version 0.C-31393-g0db5290 (tiles)
 - Graphics version CHESTHOLE
 - Mods loaded: various

**Comment by KurzedMetal** [comment]
I have noticed the same error for APC and MBTs for "ChestHole" and "ChestHole32" tilesets. Basically the NE corder for Boards and Heavy Duty Boards isn't working

![image](https://user-images.githubusercontent.com/1426680/46389018-feb55400-c6a5-11e8-88a2-ee70cc0224a8.png)

When I checked `tiles_config.json` and I found that "board_ne" and "board_horizontal" (and their "hd" aka heavy duty versions) were all sharing the same ID:

![image](https://user-images.githubusercontent.com/1426680/46389043-2ad0d500-c6a6-11e8-8bff-5f31838a3900.png)

And even worse, the section in `tile.png` that should have an asset for the "NE board" don't have any for it (it has all other directions, but not for the NE corner).

I marked the tile that has ID 2648 just for reference,
I checked the `tile.png` modification history too and it seems the NE board tile was missing for like 2 years. At some point it was to the right of the one marked in the picture (ID 2649 I guess?) but now there's frame with a hole in it, which doesn't seem to be used in `tiles_config.json`.

IDK, this seem to need the hand of a graphic designer, and I suck at it :P Hope the analysis help tho.

![image](https://user-images.githubusercontent.com/1426680/46389188-ed207c00-c6a6-11e8-8f84-59679a2f54a5.png)
