### ISSUE TITLE
When using vehicle chemistry set or onboard kitchen for heating up food, give it light.

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#25292]
**Is your feature request related to a problem? Please describe.**  
Thoose vehicle rigs are so sophisticated devices. Surely they have a small 12V light bulb or LED light for when heating up food at night. We are not even talking about the complex recipes thoose can do,

**Describe the solution you'd like**  
When at night, trying to heat up food or water inside a vehicle with the devices which have a hotplate in them, override the "is there enough light to craft?" check.

**Describe alternatives you've considered**  
I flicked lights on every time. Or used a gasoline lamp, candle or an oil lamp.
A light aisle could be installed into the car but it has to be switched on every time. This would be even more annoying than having to use one of the carried light sources,

**Additional context**  
 If I would be in the cataclysm (luckily I aren´t) I would wire a relay to the hotplate so that ALWAYS on heating something up, there would be a light ON to do it.
When heating something up, the small ammount of energy used for lighting is such a part compared to the energy used for heating.....when you can afford energy wise to heat 6 units of water  (2.5 L) at night, you also have the energy for a 2W or 5W lightbulb for that time.

**Comment by mrkybe** [comment]
Yeah, this a UI interaction that could and should be automated.  If you're in a vehicle and try to craft, just automatically turn on the aisle-lights at the start and off when finished.

**Comment by Night-Pryanik** [comment]
No discussion in three years, closing.
