### ISSUE TITLE
Mod Inclusion Project: DinoMod

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#25294]
Use the following issue as a space to discuss the inclusion of:

Mod Ident: DinoMod
Name: DinoMod

Your comment should include:

### Suggestions for induction
(what parts of the mod should be included, can be as simple as just an item, a location or the complete inclusion)

### Incompatibilities
(what parts of the mod should not be included, either some objects / items or entire mod is conflicting with DDA theme [ for whatever reason ])

---

edit:

Based on existing lore and [kevin's approval here](https://github.com/CleverRaven/Cataclysm-DDA/issues/25294#issuecomment-417912485), I think induction can work in a narrow/limited fashion.

- [ ] - Add (various or limited) dinosaur species as variants in special locations (e.g., lab specials, or other similar locations)

See discussion for other ideas.

**Comment by DracoGriffin** [comment]
And just to point out to anyone not entirely aware, there is some actual basis/lore for this (although in an extremely narrow/confined manner), found in the [lab notes here](https://github.com/CleverRaven/Cataclysm-DDA/blob/98e5ce33ed82c481ffbb1f20efe62a7323d1567b/data/json/lab_notes.json#L20) (lines 20 & 21). So this could just be another lab variant or even unique location that is extremely unique/rare that explores some "time" portal aspects. Perhaps even [shimmering portals](https://github.com/CleverRaven/Cataclysm-DDA/blob/506e11a8df5502c8fe930bf6790c3d6ffa6bb7d9/data/json/traps.json#L326) could act as extremely rare events with some limited dinosaurs that traveled through.

**Comment by MT-Arnoldussen** [comment]
My first instinct is to think this is a dumb idea, but the more I think about it the more I like the idea of a lab infested with dinosaurs. 

I would suggest never spawning them aboveground though, unless there is a breached lab nearby. The game currently already has an issue where most of the lore is really hard to get to for newer players. Having the origin of dinosaurs be somewhat more accessible would be good, I think.

**Comment by nexusmrsep** [comment]
This one is great as an optional mod imho. Dinosaurs are great, don't get me wrong, but not everyone will find them to their liking in vanilla.

**Comment by Night-Pryanik** [comment]
Lab notes said that all prehistoric fauna was terminated (by the way, "prehistoric fauna" may also be a reference to giant dragonflies, not dinosaurs) and portal destroyed, so I find it very unlikely to see dinosaurs en masse, especially different species of them. Having that in mind, I consider DinoMod just as another content-mod which doesn't fit Cata theme, and as with all such mods, I'd like to remove it from official bundle.

**Comment by Regilith** [comment]
I could see it being included if they spawned inside cages in a lab, and have incubators nearby to signify that the dinosaurs were bred from old DNA Jurassic Park style. The player should have the ability to breed dinosaurs. Eventually, if riding animals is a thing, being able to find, release, tame, and ride a T-Rex into battle against a horde of undead would probably be the coolest thing I'd ever do in a video game.

**Comment by FulcrumA** [comment]
I think dinosaurs in incubators to be bred, tamed and then used as mounts go way not only out of the scope of the mod integration but features and themes of vanilla in general.

**Comment by kevingranade** [comment]
I agree the content can be mainline as long as the dinosaurs are isolated
to special locations.

**Comment by sfsworms** [comment]
As someone who always play with the Dinomod, I strongly support its insertion. 

From a gameplay point of view, the dinomod provides strong, "natural" enemies that make the outside, especially the woods, dangerous from time to time. Once you can beat up a bear, meeting an allosaurus is one of those few "Uh, oh" moments left.

As it has been pointed before, they have some precedent in lore, both in snippets, but also in the raptor mutagen. I know some people dislike what FulcrumA has called the "everything and the kitchen sink" side of Cataclysm, but for me it's actually one of the nice, selling point of the game. In any case, rescucitating dinosaurs sounds like something Cata scientists would do. 

I think the content could be mainlined, and extended a bit (I could give it a go maybe? I've meant to try to contribute for a while):

- Require some dinosaur by-product (eggs maybe?) for raptor mutagen
- Add special dino labs with incubators
- Some of the smaller dinos could be bred like fowl

As for dinosaurs showing up only in labs (or other special locations, I think the mod adds a dino zoo), I think it robs them of a lot of their interests as really dangerous forest critters. Maybe they could show up in nature only after some time, to represent them breaing out after the Cataclysm?

**Comment by MT-Arnoldussen** [comment]
I agree with them not having a place on the overworld. If you want stronger wildlife I think are better solutions like more giant animals, stronger giant animals, and a slow zombie takeover for all wildlife.

**Comment by FulcrumA** [comment]
Yeah, while I am merely ambivalent and not that much for dinos as meat/locked enclosure animals in the lab, I am very strongly against them outside special locations. They wouldn't survive without really handwaved explanation or aforementioned enclosure and they also do add to the kitchen sink issue if more than a curiosity.

**Comment by lcy03406** [comment]
I like dinos. But, what's the unique gameplay they will bring to us? Speaking in game world, what are the doctors experimenting with them? Here is my brainstorm.

+ As flavor species. Then theme is a big problem. We have to write some weird survivor notes to explain it. 

+ As a mutation source. They need to be different with other mutation groups. It's not an easy work. Combat-oriented mutation groups are already complete and powerful.

+ As a source of meat and pet. They should fit the farming system, but need a unique style to cattle or dogs.

+ As vehicle. Every wildness survivor wants one. But we should implement horse first.

+ As enemies. So the question is about the melee combat overhaul. What's the difference of a t.rex to an extremely large naked mole rat?

**Comment by LyleSY** [comment]
I'm a big fan of DinoMod. Long term I would like to see it mature enough for partial inclusion in specials, caves, and sewers, and I'd like see a full DinoLab now that labs are more mod friendly and maybe a quest. I like the mod as a place to pull those ideas together and test them. And DinoMod dinos are warm blooded, though they currently don't spawn in winter.

**Comment by LyleSY** [comment]
@Icy03406 really good points, thank you. You may recognize a lot of the ideas flowing into DinoMod.

I think I've gotten the dino stats to a good place where they are ready to be brought in. I'll leave the egg/hatchling system out for a while to test it out more, though long term I do want to bring it in, if only as specials that can be found in special labs for raptor (other?) mutagen.

So, my big question now is: **what dinos should go in?** I feel like allosaurus, T-Rex, deinonychus for sure. They're interesting high challenge enemies, could be good candidates for raptor mutagen (especially deinos), and have some player familiarity, especially T-Rex and deinos (what Jurassic Park calls "velociraptors"). Past that, what would add value? I like the others for flavor in the DinoMod, but I'm not sure how much value they'd add in a DinoLab special or other special, or in hallucinations. Here is what's in the mod already:

compsognathus ( quick little coastal fish murderer, pet candidate)
gallimimus (I think of them as dino deer, mount candidate)
spinosaurus (giant horrible swamp monsters)
tyrannosaurus (giant horrible plains monsters)
triceratops (cool looking stabby herbivore)
stegosaurus (cool looking herbivore)
ankylosaurus (cool looking mace tailed armored herbivore)
allosaurus (like a smaller t-rex, still dangerous)
eoraptor (turkey sized scavenger, pet candidate)
velociraptor (like a little, fluffier deinonychus, not like Jurassic Park)
deinonychus (terrifying pack hunting Jurassic Park raptors)
utahraptor (deinonychus but bigger and more dangerous)
parasaurolophus (giant swamp herbivore)
dilophosaurus (Jurassic Park style spitter dino, probably not factual, but fun)

Non-dinos (legacy):
titanis (giant murderous dodo)
dimorphodon (little flying predatory lizards)

Some of these have some amazing art in tiles. I'm especially impressed with the large herbivores in MXotto+

**Comment by LyleSY** [comment]
Okay, I've submitted #26582 to address this

**Comment by DracoGriffin** [comment]
@LyleSY It looks like you've only added the json definition but nowhere for them to be spawned. Are you planning on making a unique lab setting with escaped dinosaurs with portals maybe?

**Comment by LyleSY** [comment]
@DracoGriffin I am indeed, trying to figure out how that works. I haven't done any location modding up to now.

**Comment by TechyBen** [comment]
As a special location event, they would add a large enimie challenge. For the smaller ones, a flock/swarm risk. If in a lab setting, it would add variety and, as mentions, different skill sets/approaches to that type of lab (could it be excluded from ice labs?).

I agree that overmap, it would be best for a mod, as while the "everything" style playthrough is valid, it's not to everyone's taste.

**Comment by LyleSY** [comment]
Okay, I've been digging into the new lab JSON system. The way things are coded now, I can create new dino finales using existing code with relatively little effort and space. The Ice Lab appears to still be hardcoded, so I don't think anything I do will affect that to @TechyBen 's point. What I don't like about this approach is it doesn't give a consistent theme. You won't know a Dino Lab from outside, or from any level except the very end, and there just isn't much physical space at the end to tell a story. I was hoping to create a lab with consistent themes and diverse dino encounters and related written content along the way. I see that Lab Escape has been JSONized, so I've tried to create a rudimentary Dino Lab out of that structure, but I'm having trouble spawning one for testing, since it just appears to be a vanilla Lab on the map. What's the right way to proceed here?

**Comment by DracoGriffin** [comment]
I would look into the fungal variants of lab rooms and make instead a "prehistoric" one, maybe with a few giant mosquitos, some trees/plants, and randomized dinosaurs. It would be need to confined to "dino" lab variants, so you don't end up finding these in normal labs (or ice variants).

Take a look at the [Lab Design readme](https://github.com/CleverRaven/Cataclysm-DDA/tree/master/data/json/mapgen/lab).

**Comment by kevingranade** [comment]
This is clearly stale, but it looks like having it in the "mod inclusion project" made the bot ignore it, closing.

Also, upon review, "mainlining the mod" is not ok.  The content needs to be completely overhauled to fit into the main game.  I can see some kind of "the blob triggered dormant DNA and caused animals to mutate back to an old form" justification, but then they would be mutant dinosaurs, not straight copies of dinosaurs.
