### ISSUE TITLE
Can´t build vehicle welding rig with makeshift welder+ powered by car battery and 2x makeshift welder as ingredient

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#25290]
**Describe the bug**  
I have a makeshift welder (MW). I found a mod ("battery  compartment mod") which can be attached to devices, which are powered by batteries. I run a MW now on car batteries the makeshift welder+ (MW+).
When trying to build the vehicle welding rig, it can´t be done with this MW+.
All ingredients are there but in the ingredients list the 2x makeshift welders have a strange colour. Red and green within the craft menu are understandable. But why is there this greyed out colour at the makeshift welders?
I tried it with having the makeshift welders in inventory and also at the tiles around the character with the same result. also I tried in vehicle and outside.

I then put the MW+ away. Far away enough so that it can´t interfere with the recipe. Then I built another MW and loaded it with batteries. With  the normal WM on batteries the recipe can be done.

So there is an issue with the makeshift welder+.

**To Reproduce**  

1. Create a makeshift welder+ with a makeshift welder and "battery  compartment mod".
2. Try to build a vehicle welding rig using 2x makeshift welder as ingredient.

**Expected behavior**  
The recipe can be done with a makeshift welder+ as expspected. This MW+ is my only welder for a long time now and I have used it for man things like Solar panels or the survivor suit. The recipes weren´t stating that a MW+ works for them but still it was working. Make it the same with the vehicle welding rig.

**Screenshots**  
![no welding rig](https://user-images.githubusercontent.com/42423698/44940970-037ca480-ad96-11e8-88f4-8abf9af04477.jpg)

**Comment by Androwski3000** [comment]
I did some more testing. This only happens when 2x makeshift welders are used. When a welder is used for the recipe, it can be done with with a makeshift welder+.

**Comment by kwl01skz** [comment]
Yes, I certify the existence of such a situation.

When I have 2 x makeshift welders and 1 x makeshift welder +（cat batteries）, I can't make vehicle welding rig.

When I remove mod and load standard battery, in other words, I have a 3 x makeshift welder, and one of them has enough batteries , I can use them to make a vehicle welding rig.

**Comment by mrkybe** [comment]
Yep, can also confirm.

**Comment by CoroNaut** [comment]
I remember this was a problem a long time ago, idk if the issue from back then is still open or not though.
