### ISSUE TITLE
Walking on a road while wielding a pickaxe should not destory the road

### ISSUE THREAD

**Issue by svick** [CleverRaven/Cataclysm-DDA#25300]
When you're wielding a pickaxe or a similar tool and you attempt to walk on a road (a pavement tile), you "mine" the tile instead of walking.

What makes this worse is that it also destroys any vehicle tile there. So, instead of opening a car door or getting into a car, you instead destroy the car door if it's on the road and you're wielding a pickaxe.

**To Reproduce**  

0. Make you sure you have automatic mining enabled (it should be on by default).
1. Wish for and wield a pickaxe.
2. Try to walk on a road.

**Expected behavior**  

No roads or vehicles are destroyed by just walking on them.

**Versions and configuration(please complete the following information):**
 - Game Version: 0.C-31400-gdceede2

**Comment by Night-Pryanik** [comment]
> When you're wielding a pickaxe or a similar tool and you attempt to walk on a road (a pavement tile), you "mine" the tile instead of walking.

And what if player wants to actually mine the road using the auto-mining?

**Comment by svick** [comment]
> And what if player wants to actually mine the road using the auto-mining?

I think preventing them from using auto-mining in this specific case is a price worth paying.

Preventing accidents, especially potentially disastrous ones, is much more important than convenience of a relatively rare (I assume) action.

**Comment by vlad1492** [comment]
Having spent a number of in-game weeks mining road... I for one don't need auto mining road. Wielding tool and Shift-A in the preferred direction is plenty fast enough.

**Comment by CoroNaut** [comment]
If auto mining is toggleable, why is this an issue? Just turn off the auto mine and you wont mine the road as you go.

**Comment by svick** [comment]
@CoroNaut The problem is, when you've noticed that this is an issue and assuming you even know that auto-mining can be disabled, your car might already be destroyed beyond repair due to this behavior.

**Comment by kevingranade** [comment]
This shouldn't trigger even once by default, this is definitely a bug.

**Comment by Leland** [comment]
Note, btw, that #26154 moves auto-mining to off by default

**Comment by cake-pie** [comment]
Problem is not actually fixed by #26154.

Automine aside, pickaxe/jackhammer are not intended to destroy vehicles.
This can be deduced by manually mining by activating a pickaxe:
  - vehicle tile on non-mineable terrain: mining not permitted.
  - vehicle tile on mineable terrain: vehicle obliterated

#24787 is responsible for inadvertently changing the behavior; rolling back to a58b380 just before it was merged and trying to mine a vehicle tile on pavement or sidewalk (which are mineable) will fail.
