### ISSUE TITLE
When reheating food, split the stack and only reheat 1 portion

### ISSUE THREAD

**Issue by vlad1492** [CleverRaven/Cataclysm-DDA#25304]
Right now using a pot near a heat source reheats the whole stack, which can take quite a while.  
I'd like to see reheating split the stack and produce a (hot) (1)

**Comment by Androwski3000** [comment]
I´m also for an option to select the heated stack size. From experience you know how much cooked meat / sausage / etc. you need to get get past "hungry" towards "full".

Also when heating food which has low nutrition like below 10 you have to type combinations like the following 15x times when coming from "very hungry":

-"i" inventory,
-"H" or "m" (dedicated letters for "Hobo stove" or "survival mess kit"),
-ENTER for activation,
-select the food in the list for heating, you are lucky if it has a letter or number or use "/" to find that specific food in a long list,
-"E" for consumption menu,
select the food, you are lucky if it has a letter or number or use "/" again to find the food with status "hot."

Stack eating and stack heating would be very benefitial to the game especially with food freezing now.

The only short term solution exists for containers and fluids as a whoel container is heated. That way you can get 6 units of clean water heated in a small sealed stomach or plastic canteen. Which most of the time is enough to get from "very thirsty" to "slacked".
