### ISSUE TITLE
Vehicle engines cannot be uninstalled

### ISSUE THREAD

**Issue by Hugna** [CleverRaven/Cataclysm-DDA#25301]
**Describe the bug**  
No matter what i try, lifting stat objects, strength, i just can't rip this engine out. I even took something that adds lifting on one of my vehicles, almost touched the frame of what i'm trying to scrap, then attempted to lift it using the crane that hits the LIFTING 1 requirement. Not even strength or lifting allows what it's used for, and it's tempting me to just smash the engine to scrap and move on.

**To Reproduce**  
Try to uninstall an engine with appropriate requisites.

**Expected behavior**  
Being able to remove the engine.

**Screenshots**  
https://cdn.discordapp.com/attachments/241324886788669442/485454926856847360/cdda9.png
https://cdn.discordapp.com/attachments/241324886788669442/485454931382501376/cdda10.png

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.C-31301-g687e1e5 (Build 7797)
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Filthy Clothing, Disable NPC Needs, Simplified Nutrition, Disable Religious Texts, No Fungal Monsters, Manual Bionic Installation, StatsThroughSkills, SafeDoc

Despite being build 7797, the builds beyond (update logs) never spoke anything about vehicles, so it's assumed it affects all others beyond.

(Edited September 1st 6:27 PM. Added build number)

**Comment by pingpong2011** [comment]
There were some other requirements, someone else could confirm/refute: the largest boom/crane had to be installed on a nearby vehicle, and nearby had to be adjacent tile to you. Note: the crane itself had to be adjacent I believe not "in the area".

**Comment by Night-Pryanik** [comment]
No confirmation in a long time, closing for now.
