### ISSUE TITLE
Gas v PBA mask balance broken in relatively recent patch

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25305]
The stats for them, for reference:
Gas: 30 Encumb. 4/4/9/1/16 resists. 
PBA: 20 Encumb. 5/5/7/11/16 resists + bonus tags "WATERPROOF", "STURDY", "SUN_GLASSES"

As you can see, the PBA is basically superior in every way. Previously, this was not an issue because it was balanced by the fact the gas mask did not require upkeep, while the PBA did require upkeep (batteries). 

However, not too long ago both were changed to require upkeep (filters), thus eliminating the gas mask's real only advantage. There probably needs to be some tweaking to make the gas mask not entirely useless compared tot he PBA.

**Comment by kevingranade** [comment]
If you have a concrete suggestion for a change, make it, but "x is strictly better than y" is not a bug.
