### ISSUE TITLE
Full Night Vision Should Allow You to Craft Anything in the Dark

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#25310]
**Is your feature request related to a problem? Please describe.**  
Can't craft most things even when you can see very well.

**Describe the solution you'd like**  
Be able to craft anything in dark with full night vision, and some more things with regular night vision

**Describe alternatives you've considered**  
Maybe you can just craft more things.

**Comment by kevingranade** [comment]
Night vision is based on naturally occurring low light vision, which has enhanced ability to operate on minimal light, but is unable to perceive color and detail.

The lack of detail vision prevents crafting.
