### ISSUE TITLE
grab menu - item stacking

### ISSUE THREAD

**Issue by esavier** [CleverRaven/Cataclysm-DDA#2531]
When grabbing something from lets say pile of rag you have to dig through a lot of [rag] entries. If they are similar in quality, damage level and/or charges left they should be displayed not as
"
[rag]---
[rag]---
[rag]---
..."

 but 
"[rag]  [100] "

  both in [g]grab menu and [/]advanced item management, this same goes for other items like, sewing kits, poppy flowers, pipes, scrap metals... ehhh probably every non ammunition types.

**Comment by Zireael07** [comment]
Can something be done about this? We have a recent report...

**Comment by illi-kun** [comment]
#18245 describes the issue better, so I'm going to close this report and keep the new one open.
