### ISSUE TITLE
Improve limb selection menu when bandaging/disinfecting

### ISSUE THREAD

**Issue by nexusmrsep** [CleverRaven/Cataclysm-DDA#25313]
**Is your feature request related to a problem? Please describe.**  
After recent changes in healing process you need/want to bandage and disinfect wounds to get the healing process going. However the limb selection menu was left as it was:
![image](https://user-images.githubusercontent.com/39925111/44954824-28ae0780-aea9-11e8-8e7b-16144b493973.png)
and it does not show you if you have already bandaged or disinfected specific limb, and in what state are those bandages. This leads to bandaging/disinfecting blind, or switching between @ menu and limb selection menu from medical items use action to check that.

**Describe the solution you'd like**  
After (or under) each limb listed in this menu there should be information consistent with what the @ menu provides, so this information:
![image](https://user-images.githubusercontent.com/39925111/44954879-dae5cf00-aea9-11e8-9705-e4f8a50f1599.png)
should be translated in this menu to something like:

### **6: Right Leg:  |||  (bandaged: 8, disinfected: 8)**

**Describe alternatives you've considered**  
alternatives here would be different styles of how this UI could achieved it. For example optional way:
**6: Right Leg:  |||**
**--> bandaged: 8**
**--> disinfected : 8**

**Additional context**  
N/A

**Comment by Androwski3000** [comment]
I agree with you. Such and upgrade would be very benefitial.
