### ISSUE TITLE
Geothermal power

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25320]
So we were talking in discord about how lava now has a use as a passive food defroster, which made me think, "Why can't we use the energy for other stuff"?

Maybe a fire-immune vehicle part which could be used to create a dragable generator, which you can then put over or adjacent to a lava tile?

**Comment by FulcrumA** [comment]
Given the locations of lava pools and how rare they are, unreliably found at random and often inconvenient locations, I am not sure if developing whole new feature for it is worth the effort.

**Comment by Regularitee** [comment]
>Given the locations of lava pools and how rare they are, unreliably found at random and often inconvenient locations, I am not sure if developing whole new feature for it is worth the effort.

That's kind of the point. It's free, 24-hour energy, so it _should_ be rare or highly restrictive. 

I'm not sure how hard it would be code-wise, but we already have fire-immune items. I suspect (or hope) it wouldn't be hard to add that to a specific type of vehicle frame, which also checks for lava tile adjacency (or heat damage) to generate power. But I could be entirely wrong on this account.

>It'd be a rather huge installation not achievable by a survivor in an post-apocalyptic scenario. 

Traditional geothermal plants, yes. But consider they operate using a far less potent heat source (air that has traveled hundreds of meters from a lava source, if even that), and have to generate power on a far larger scale. It would be hardly be unfeasible to generate enough power for a single person using a much more concentrated energy source. In any case, it's not any less feasible than solar arrays moving 20-ton electric vehicles, or micro-nuclear reactors in cars. Never mind bionics or laser guns.

Geothermal power in this case can be as simple as trickling water over lava, and having something catch the rising steam to turn the a turbine. To say nothing of radioisotopic thermoelectric generators (which utilize the ambient heat of decaying radioactivity to produce power). Given how common nuclear power is in the setting, it would not be hard to find convert one of those into utilizing lava heat instead of radioactive heat.

**Comment by alanbrady** [comment]
> It'd be a rather huge installation not achievable by a survivor in an post-apocalyptic scenario. You don't have those portable geothermal plants at your disposal anywhere. There are heat pumps systems but all the can do is add some heat to houses, and nothing usable beyond that. And thet need electricity to run too.

Isn't this just basically a steam engine?  Boil some water and you have steam which you feed to an engine which then generates electricity.  A reasonably knowledgeable survivor I would expect to be able to do.  Lava should definitely be hot enough to boil water, let alone just a campfire.

https://www.youtube.com/watch?v=FWPrHLiR-W8

**Comment by paulenka-aleh** [comment]
Can we have simple devices converting heat into energy even if terribly inefficient? They do exist IRL...

**Comment by FulcrumA** [comment]
@Regularitee 
>That's kind of the point. It's free, 24-hour energy, so it should be rare or highly restrictive.

Does it mean that you're volunteering to add the feature given that most people wouldn't bother given that there rarely would be any possibility to comfortably use it?
That's a big issue of it - adding devices, recipes etc that in case of majority of players will likely just clutter the list, never to be utilized.

Also, I don't mind steam engine though with lava, those engines would have to be well isolated or topped nearly all the time - either you'd have to set elaborate isolation so lava is only heating the canister when you want it to - much harder than even just building a steam engine may be in many cases even if the shielding will be less elaborate - or the engine will be heated all the time, either risking reaching critical mass or running out of water all the time and burning.

Sure, heat pumps exist but they're not connected straight to magma flow.

**Comment by kevingranade** [comment]
A piece of furniture that consumes water (steam engines leak) and produces electricity, and is only installable near a lava tile would be totally fine.  Keep in mind that's a pretty major undertaking to build, but I can certainly see it happening, even within the bounds of what the survivor can make.

Good luck.
