### ISSUE TITLE
whaleys_boats.json double item definition introduces bugs for musclepower boats

### ISSUE THREAD

**Issue by overbo** [CleverRaven/Cataclysm-DDA#25323]
**Describe the bug**  
Every boat powered by hand paddles is too heavy for its engine

**To Reproduce**  
spawn a vehicle that requires hand power
drag it to the water
attempt to accelerate
experience bug

**Expected behavior**  
boat moves in the water

**Screenshots**  
n/a

**Versions and configuration(please complete the following information):**
 - OS: OSX 10.14
 - Game Version: 0.c-31338-g9b124e3da6
 - Graphics version: Tiles
 - Mods loaded: Boats is the only one that matters here.

**Additional context**  
I'd make a pull request for this if I knew how to use github properly, but I don't.  It looks to me like the flags for @mlangsdorf 's new vehicle fixes were put into one of the files in the boats mod, but the redefinition of the parts in whaleys_boats.json overwrote them and have not been updated with the proper flags (I believe that it is "E_STARTS_INSTANTLY" flag that is missing).  Replacing  data/mods/Boats/whaleys_boats.json with the content below fixed the problem for me:

[
  {
    "//": "Place the following vehicles as boat.json in /data/json/vehicles/",
    "type": "vehicle",
    "id": "canoe",
    "name": "canoe",
    "blueprint": [ [ "<OO>" ] ],
    "parts": [
      { "x": 0, "y": 0, "part": "frame_wood_horizontal" },
      { "x": 0, "y": 0, "part": "seat" },
      { "x": 0, "y": 0, "part": "hand_paddles" },
      { "x": 0, "y": 0, "part": "boat_board" },
      { "x": 1, "y": 0, "part": "frame_wood_horizontal" },
      { "x": 1, "y": 0, "part": "boat_board" },
      { "x": 1, "y": 0, "part": "seat" },
      { "x": 2, "y": 0, "part": "frame_wood_horizontal" },
      { "x": 2, "y": 0, "part": "boat_board" },
      { "x": -1, "y": 0, "part": "frame_wood_horizontal" },
      { "x": -1, "y": 0, "part": "boat_board" }
    ]
  },
  {
    "type": "vehicle",
    "id": "raft",
    "name": "raft",
    "blueprint": [ [ "OO" ], [ "OO" ] ],
    "parts": [
      { "x": 0, "y": 0, "part": "frame_wood_cross" },
      { "x": 0, "y": 0, "part": "seat" },
      { "x": 0, "y": 0, "part": "hand_paddles" },
      { "x": 0, "y": 0, "part": "boat_board" },
      { "x": 1, "y": 0, "part": "frame_wood_cross" },
      { "x": 1, "y": 0, "part": "boat_board" },
      { "x": 1, "y": 1, "part": "frame_wood_cross" },
      { "x": 1, "y": 1, "part": "boat_board" },
      { "x": 0, "y": 1, "part": "frame_wood_cross" },
      { "x": 0, "y": 1, "part": "boat_board" }
    ]
  },
  {
    "//": "Place the following in vehicle_groups.json in /data/json/",
    "type": "vehicle_group",
    "id": "boatrent",
    "vehicles": [ [ "canoe", 2000 ], [ "raft", 2000 ] ]
  }
]

**Comment by overbo** [comment]
#24864 @DracoGriffin  FYI — thank you and keep up the fine work of importing mods.

**Comment by mlangsdorf** [comment]
Simple solution: delete b_var_veh_parts.json and b_var_wood_veh_parts.json as being completely rendundant to b_inflatable_boat_parts.json and b_wooden_boat_parts.json.

**Comment by overbo** [comment]
I am not at my computer at the moment but if @mlangsdorf is right, that sounds like the parts are defined three times in the mod.

**Comment by mlangsdorf** [comment]
Closing as duplicate, then.
