### ISSUE TITLE
Error with crushing a hostile NPC with a car

### ISSUE THREAD

**Issue by Trokinos** [CleverRaven/Cataclysm-DDA#25329]
Using recent build cataclysmdda-0.C-7821
on a world created with these mods :
  "dda",
  "no_npc_food",
  "novitamins",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "Mundane_Zombies",
  "safeautodoc",
  "StatsThroughSkills"
I also have the world NPC spawn rate set to 100 (so i can see sometime a random NPC as below that value i nearly never see any random NPC)

A hostile Random NPC murdered 2 friendly Random NPC that were travelling with my character.
I ran away and managed to reach my working car before the NPC figured out i should be next (as there was a zombie closer) .
Getting in the car and driving at high speed to avenge my fallen NPC friends, i rammed the hostile NPC.

It created a error , the last couple of minute of the log :
13:47:58.219 GAME : src/npctalk.cpp:2649: called calc_chance with invalid talk_trial value: 0
13:48:2.31 GAME : src/npctalk.cpp:2649: called calc_chance with invalid talk_trial value: 0
13:50:3.844 : src/overmapbuffer.cpp:752 [std::shared_ptr<npc> overmapbuffer::remove_npc(int)] overmapbuffer::remove_npc: NPC (10) not found.

screenshot of the error :
https://i.imgur.com/lxfS8FD.png

**Comment by Night-Pryanik** [comment]
Such a dramatic story you have here.

**Comment by FulcrumA** [comment]
As a side note, probably the message log could take NPC gender into account to describe it as her/him.

**Comment by Trokinos** [comment]
I do not know if it is related but i ran into another bug related with NPC and a vehicle.
https://i.imgur.com/3rKukZW.jpg

 DEBUG    : map::unboard_vehicle: passenger not found
 
 FUNCTION : void map::unboard_vehicle(const tripoint&)
 FILE     : src/map.cpp
 LINE     : 872

What happened is that a NPC turned hostile and fled from me, i followed him and he entered in a vehicle, moving a few tiles inside, i shot him there and the error happened when he died

**Comment by l29ah** [comment]
Got the same problem. The log says:
```
21:34:00.519 ERROR : (error message will follow backtrace)
	cataclysm(_Z21debug_write_backtraceRSo+0x38) [0x55851d3d0948]
	cataclysm(_Z8DebugLog10DebugLevel10DebugClass+0x23a) [0x55851d3d1e1a]
	cataclysm(_Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x7c) [0x55851d3d295c]
	cataclysm(_ZN13overmapbuffer10remove_npcEi+0x2c3) [0x55851daf17f3]
	cataclysm(_ZN4game12cleanup_deadEv+0x119) [0x55851d4b2c09]
	cataclysm(_ZN4game7monmoveEv+0x2c) [0x55851d50735c]
	cataclysm(_ZN4game7do_turnEv+0x80e) [0x55851d508f8e]
	cataclysm(main+0xd11) [0x55851d1e8551]
	/lib64/libc.so.6(__libc_start_main+0xeb) [0x7f1e838caecb]
	cataclysm(_start+0x2a) [0x55851d2181ca]

	Attempting to repeat stack trace using debug symbols...
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(nm) failed
	backtrace: popen(addr2line) failed
Backtrace emission took 0 seconds.
src/overmapbuffer.cpp:993 [std::shared_ptr<npc> overmapbuffer::remove_npc(int)] overmapbuffer::remove_npc: NPC (3) not found.
```

**Comment by l29ah** [comment]
Got the same problem after ramming in a refugee center:
![](https://pstbin.ru/f/22290/)
