### ISSUE TITLE
map building structure description color problem

### ISSUE THREAD

**Issue by zizdarren** [CleverRaven/Cataclysm-DDA#25325]
**Is your feature request related to a problem? Please describe.**  
Some building structure is hard to read with the map background. Such example is the blue text description of the building and black background of the map.

**Describe the solution you'd like**  
add a toggle button of changing the text description to white color, so it can contrast the black background for player to see the description

**Describe alternatives you've considered**  

**Additional context**

**Comment by Night-Pryanik** [comment]
I believe just changing all of the offending cases are much easier than adding a toggle. Could you list locations' names with hard-to-read colors?
