### ISSUE TITLE
Wooden greatbow strength requirement sometimes broken.

### ISSUE THREAD

**Issue by Szara-ManOfHonor** [CleverRaven/Cataclysm-DDA#25340]
**Describe the bug**  
Can't use wooden greatbow due to low strength. Despite strength still being over 18.

**To Reproduce**  
Have > 18 Str
Have some effect (common cold, lacking sleep, etc) that reduces Str to something still >18
Can't use wooden greatbow due to low strength. Despite strength still being over 18.

**Expected behavior**  
Able to use wooden greatbow until strength is actually below 18

**Screenshots**  
https://gyazo.com/a075311c331099f9cc26e00e59e816db

**Versions and configuration(please complete the following information):**
 - OS: Win10
 - Game Version  0.C-31402-g1a9da5e
 - Graphics version Tiles
 - Mods loaded 

"dda",
  "Arcana_A",
  "Arts' Guns",
  "Cata++",
  "DinoMod",
  "Experimental-Z-Level",
  "FIC_Weapons",
  "Medieval_Stuff",
  "Mining_Mod",
  "More_Survival_Tools",
  "Nonperishable_Overhaul",
  "PK_REBALANCE_A",
  "StatsThroughKills",
  "StatsThroughSkills",
  "Szara_Mods",
  "blazemod",
  "Tanks",
  "Urban_Development",
  "ZSFIXED_cddaxp",
  "a_mutated_arsenal",
  "bio_mod",
  "blazemod_A",
  "bsa_gel_wall",
  "bsam",
  "can_mod",
  "cityside",
  "craftgp",
  "dda-lua",
  "dda-lua-fun",
  "dda-lua-items",
  "dda-lua-skills",
  "dda-lua-traits",
  "deoxymod",
  "ew_pack",
  "filthy_morale",
  "hd_doors",
  "makeshift",
  "mo_insects",
  "mo_monsters",
  "mo_veh",
  "more_char_creation",
  "more_classes_scenarios",
  "more_locations",
  "more_survive_notes",
  "mutant_npcs",
  "national_guard_camp",
  "no_npc_food",
  "no_olg_guns",
  "no_reviving_zombies",
  "novitamins",
  "npc_traits",
  "nw_pack",
  "oa_additional_buildings_mod",
  "powder_disinfectant",
  "pressure_weapon",
  "realguns",
  "rice",
  "sci_turret",
  "speedydex",
  "winning_dda",
  "noctpk"

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.C-7830. Gave my character 22 strength, caused it a lot of pain, strength dropped to 19, was able to successfully fire from the greatbow.
![default](https://user-images.githubusercontent.com/11132525/45026995-d3a8f780-b048-11e8-9032-78deefda9ecf.png)

I fear there's something in your huge pile of mods causing this.

**Comment by tyrael93** [comment]
Damn that's a shitload of mods
Where did you even get half of those

**Comment by Endovior** [comment]
> Where did you even get half of those

Judging by the mod names, it looks to me like OP is using the [launcher](https://github.com/remyroy/CDDA-Game-Launcher), which references its own repository of mods, including many of the mods on the list. I don't recognize all the mods on that list, though; OP may be experimenting with a few older or obscure mods that didn't make the cut.

One of those older mods may well be the source of the problem; were I OP, I'd try disabling mods individually and re-testing to isolate the issue.

**Comment by Night-Pryanik** [comment]
No confirmation in a long time, closing for now.
