### ISSUE TITLE
When reading with an allied NPC with Howler nearby, you will howl instead.

### ISSUE THREAD

**Issue by aoae23** [CleverRaven/Cataclysm-DDA#25342]
**Describe the bug**  
When your NPC ally has the Howler mutation, the game treats it as if you are mutated yourself when reading.

**To Reproduce**  
1. Befriend a NPC with the Howler mutation. I'm not sure if it applies to other noise making mutations if they exist. In my case the NPC was the starter NPC.
2. Try to read a book.

**Expected behavior**  
The NPC howls, instead of you.

**Screenshots**  
![image](https://user-images.githubusercontent.com/42950339/45003869-c71a9580-af9b-11e8-9baa-bc0530a32953.png)
![image](https://user-images.githubusercontent.com/42950339/45003906-36908500-af9c-11e8-9a85-e72527e28661.png)
![image](https://user-images.githubusercontent.com/42950339/45003911-48722800-af9c-11e8-879a-0872b7f3ac7a.png) (the NPC in question)

**Versions and configuration(please complete the following information):**
 - OS: on the SSH server.
 - Game Version: 0.C-30390-g94dfc59-dirty
 - Graphics version: Terminal
 - Mods loaded: 99% sure the relevant mod is Mutant NPCs

**Comment by Zaragata** [comment]
I don't know much, but my guess is: probably the NPC is howling as intended, the problem is the message you're getting wasn't programmed to be used by NPCs.

**Comment by MT-Arnoldussen** [comment]
Same as #24535
