### ISSUE TITLE
Constructing roof is too complicated

### ISSUE THREAD

**Issue by SirDifferential** [CleverRaven/Cataclysm-DDA#2534]
Currently building a roof requires that there is a support on both sides of it. This makes it extremely difficult to build, say, a 5x5 grid of roof tiles. The only way to do this is by making two supports, building one roof tile between them, tearing one support down, and executing this procedure for all the roof tiles.

Maybe support on one side should be enough?

Example case where building roof would not be possible unless supported one tile at a time: http://plantmonster.homeip.net/pics/cataclysm/cataclysm013.png
##

**Comment by kevingranade** [comment]
Should be a trivial fix to add this message now that there's a description field for constructions.
