### ISSUE TITLE
foods on player become frozen even though player is warm (in bed)

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#25357]
Went to sleep under down blankets with honey and flour on me.  Woke up and they are both unusable, 'frozen solid'.  Excepting for a minute that flour can't really freeze, it seems the temperature of items should follow what the temperature of the player is.

 - Windows 7 64 bit
 - Game version 0.C-31274-g928aeef
 - default mods

**Comment by nexusmrsep** [comment]
There is a PR #25242 queued that will add bonus temperature for carried items, but it will be just a bonus. You don't sleep on your food, so tracking body temperature is unrealistic.

**Comment by nexusmrsep** [comment]
PR mentioned above will add 5 degrees  Fahrenheit from body heat to freezing calculations of all items in players inventory. Not much but significant enough. This should address this problem, but even then food will freeze in lower temperatures.
