### ISSUE TITLE
Backtab registers as tab

### ISSUE THREAD

**Issue by TTTime** [CleverRaven/Cataclysm-DDA#25363]
As per title, when using 'shift' + 'tab' it's processed as a straight 'tab'. I've tried builds 7835, 7834 and 7812 and this is repeatable in all. Checked my keyboard settings etc and it's highly unlikely to be an error on my end, works fine in stable. I'm not sure if it's solely at world and char gen, I can't think of any other menus / situations where there would be a noticeable difference. 

To reproduce simply try navigating back a menu in world or character generation.

Using Win 10 Lenovo laptop, builds 7812, 7834, 7835 confirmed presence of bug. Could be linked to #25272.

**Comment by AMurkin** [comment]
Try to rename `config\keybindings.json` to `config\keybindings.json.bak` and check the issue.

**Comment by ZhilkinSerg** [comment]
I cannot reproduce this issue yet - TAB and BACKTAB are working as expected.

**Comment by TTTime** [comment]
Changing extension hasn't fixed the issue. Realised it's probably nothing to do with #25272 after all as I had this exact same issue last year in October on my old laptop. Could be something to do with English laptop keyboard configuration.

**Comment by lucidvizion** [comment]
I have confirmed the issue happens in the Windows Curses build but not Windows Graphical.  Build 7911.

**Comment by ZhilkinSerg** [comment]
@TTTime: Are you using Tiles or Curses version?

**Comment by Vzor-** [comment]
I can also confirm. It occurs on both of my computers running the newest build, but only with curses.

**Comment by catalpapril** [comment]
It happened to me, 'shift' + 'tab' doesn't work, processed as a 'tab'. 
Backtab works fine on my other applications, such as sublime text and chrome.
