### ISSUE TITLE
Waste-to-energy incinerator

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25361]
So, I figure an excellent way to kill two birds with one stone.

As you may know, having dead bodies and items lying everywhere causes save bloating. But if you bother to actually clean up a map by stacking bodies/items and burning them, you're sacrificing in-game resources (time, hunger, thirst, risk) for an entirely out-of-game advantage. Which doesn't make much sense if you're playing a game in-character with the intent to survive.

So enter the waste-to-energy incinerator: 
- It provides incentive to clean up the map, improving game performance without giving the player an in-game penalty for doing so.
- It can fill an otherwise neglected niche: a power source for wilderness survivalists, to generate power via wood burning.

Ideally this would be similar to a brazier or wood stove, where it contains the maximum size of the fire in the tile, and prevents it from spreading. It could then run a check every X seconds/minutes to see if a fire is still present, in which case it generates a a sum of energy to whatever batteries its connected to.

**Comment by kevingranade** [comment]
> As you may know, having dead bodies and items lying everywhere causes save bloating.

Is this actually a problem? If it is there are much more direct ways to fix it than trying to convince the player to deal with it.

**Comment by Regularitee** [comment]
From discord discussions, it seems common enough. Many players will regularly either try to manually edit save files (and hope they don't break anything), or copy-paste character data into a new world, once  a game becomes sufficiently bloated.

I'm not sure if any sort of world cleanup mechanic exists in game, but if it does, it doesn't seem to work effectively or quickly enough to prevent save bloating for some players.

**Comment by Maddremor** [comment]
Am I the only person that piles stuff up in a brazier and set it on fire? That does provide fire for cooking, although no electricity.

**Comment by pingpong2011** [comment]
I often find myself eating waste if I have a metabolic interchange. If not, I shred it for thread or burn it. Incidentally, this could be a niche filled by a steam powered generator. Construct a "vehicle" with a water tank (boiler), "burner" (container with wet/dry fuel, maybe made with an igniter), generaotor/alternator?, battery, and a container+recharger socket, or whatever jumper cables use. If it could all be contained nicely that'd be great. I don't imagine a single-object that could fulfill the roles needed and make sense.

**Comment by paulenka-aleh** [comment]
I second thought on on steam engines + alternators, would be awesome.

Although it worth mentioning compact devices that does already exist: https://www.kickstarter.com/projects/flamestower/flamestower-charge-your-gear-with-fire and https://www.google.by/amp/s/www.engadget.com/amp/2011/06/14/hatsuden-nabe-thermoelectric-cookpot-keeps-your-iphone-battery-c/ (btw, 2nd one specifically mentions zombie apocalypse :D)

Never tested myself, but the game could have inefficient UPS analogs.

P.S. I do clean up cities as I walk though as well unless it's dangerous to stay. I tend to bring all the junk to safehouse, sort it, wash, dissamble, cut, burn, eat or do whatever feasible.

**Comment by mlangsdorf** [comment]
My proposed steam engine (#25245) is a closed cycle engine that currently only burns coal. I plan to add  support for other fuels later.  Burning arbitrary things is a problem because you need an energy density for each fuel.

**Comment by nexusmrsep** [comment]
> My proposed steam engine (#25245) is a closed cycle engine that currently only burns coal. I plan to add support for other fuels later. Burning arbitrary things is a problem because you need an energy density for each fuel.

Isn't there some kind of material to fuel conversion in fire calculation in field.cpp that you could follow @mlangsdorf?

**Comment by kevingranade** [comment]
1. you still haven't outlined how this is a problem, "some people complained about it" isn't an actual problem, people complain about anything and everything.
2. *IF* it's a problem, save compression will almost certainly nail it to the ground, and it's quite easy to do, the only reason we don't have it is there was no evidence that it helped anything.
2.a  If that's insufficient culling unmodified map tiles is going to likewise be incredibly more effective than manual user intervention.
3. Your proposal won't help, at the point when this kind of thing is a problem, there are millions of items that need to be cleaned up, it's completely unreasonable for the player to do that.

**Comment by TechyBen** [comment]
I get around 50% saved "space" from just using NTFS compression on that one folder. No idea if that's a problem for the SSDs though (multiple access attempts per sector or whatever to compress/save/decompress/amend/etc).

But anything helping save folders not creep up to 500mb and above would be welcome. Problem is, any compression is going to prevent notepad editing, right?

**Comment by Zireael07** [comment]
Performance and saves improvement, waste incinerator sounds like a good idea, to eg. get rid of lots of rubbish and/or Z corpses quickly (and get something universally useful out of it unlike butchering)

**Comment by kevingranade** [comment]
The reason for this change is non-existent, closing.

If you have an impact to the player regarding accumulating map data, feel free to open an issue with your info.  
If you want to outline an incinerator item/furniture, feel free to open an issue about that.

**Comment by Regularitee** [comment]
>If you want to outline an incinerator item/furniture, feel free to open an issue about that.

Isn't that what this thread already does? I mean, it's describing an object and its intended purpose. The discussion may have been sidetracked into save file size, but the original post is a discussion about a suggested item/object. Unless you mean something else I don't quite understand.

**Comment by CoroNaut** [comment]
I have to agree with regularitee, the issue was a suggestion specifically for the purpose of implementing something new. It isn't really a change, he simply outlined some problems this new addition would fix or help fix.
