### ISSUE TITLE
Smarter defrosting for comestibles EATEN_COLD

### ISSUE THREAD

**Issue by cake-pie** [CleverRaven/Cataclysm-DDA#25375]
**Current behavior**
- Start with a frozen item that has `EATEN_COLD`, e.g. lemonade (frozen)
- [Spend extra time](https://github.com/nexusmrsep/Cataclysm-DDA/blob/47298ed1dea10582ae57a3decfe548640ac576de/src/iuse.cpp#L4886-L4889) heating it up to hot
- Spend more time (and possibly electricity) to cool it back down to cold
  - possibly worsened by [inflated counter value](https://github.com/nexusmrsep/Cataclysm-DDA/blob/47298ed1dea10582ae57a3decfe548640ac576de/src/iuse.cpp#L4893)
- Finally enjoy cold drink

**Describe the solution you'd like**  
It would make more sense to heat the item only just enough for it to thaw out.
Suggest: change FROZEN flag to COLD, set item_counter to 300 (in between normal and frozen, so it can go either way depending on ambient temperature)

**Comment by nexusmrsep** [comment]
I agree with this logic. Main reason for adding HOT flag was to give some extra time fot he item to freeze, but that time was tweaked later on. By cautiousness and for the same reason I'd rather set that in upper COLD counter levels (500-ish) rather then in the middle. Planned for next week.
