### ISSUE TITLE
Ask NPC about his/her needs.

### ISSUE THREAD

**Issue by nexusmrsep** [CleverRaven/Cataclysm-DDA#25374]
**Is your feature request related to a problem? Please describe.**  
NPC's that need to sleep eat and drink comunicate that fact when need has to be addressed. It would be nice if you could ask NPC about future needs to better plan for the incoming activities.

**Describe the solution you'd like**  
I'd like to ask a friendly NPC about his/her needs and get answers like "I've slept/eaten/ drank somethiing recently and don't need to worry about this for a day." "I'm fine but I'd have a snack in two or three hours", "I'm sleepy now, if I you plan to stay awake I'll find myself a cozy spot in an hour or two."
This can cover needs that already triggered NPC to talk about it by him/herself.

**Describe alternatives you've considered**  
N/A

**Additional context**  
Inspired by #25373

**Comment by mlangsdorf** [comment]
HFS the NPC talk code is a disaster.
Let me JSON'ize that into just a mess and then look at this issue.

**Comment by FulcrumA** [comment]
Doesn't checking information about the NPC/showing character status card drop some information regarding thirst, hunger and sleepiness?

**Comment by mlangsdorf** [comment]
So there's actually a fully functional, JSON'ized, dialogue tree system lurking down there. This maybe easier to do that I thought.

**Comment by mlangsdorf** [comment]
4.5 months to address this.  Not too bad.
