### ISSUE TITLE
Survivor gear has too high encumbrance

### ISSUE THREAD

**Issue by saladasa** [CleverRaven/Cataclysm-DDA#25370]
The heavy survivor helmet now has 90 encumbrance for some reason. OK, maybe someone thought that was reasonable. I guess I'll have to wear a not so heavy helmet.

The regular survivor helmet also has 90 encumbrance. Surely that's a mistake.

**Comment by MT-Arnoldussen** [comment]
should be fixed by #25366

**Comment by saladasa** [comment]
Yep, it's fixed.
