### ISSUE TITLE
Boats cannot be used in sewers (or sewage tiles)

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25388]
The water is deep enough to give the player a major movement penalty, so it strikes me that it should be deep enough to support an inflatable raft.

**Comment by AbsalomAchitophel526** [comment]
Also, if you should try a bicycle upon realizing boats will not work, you will find that the bike not only works but removes sewage tiles it travels over.  Probably a bug, but I thought I should bring it up here.

**Comment by Night-Pryanik** [comment]
> Also, if you should try a bicycle upon realizing boats will not work, you will find that the bike not only works but removes sewage tiles it travels over. Probably a bug, but I thought I should bring it up here.

That's not a bug, that tries to simulate vehicle wheels displacing the liquids (terrain-type) on the ground.

**Comment by latogato** [comment]
> That's not a bug, that tries to simulate vehicle wheels displacing the liquids (terrain-type) on the ground.
Awesome, i will name my next bicycle Moses.
