### ISSUE TITLE
Copy-from not working for deconstruction recipes.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#25384]
**Describe the bug**  
The copy-from field doesn't seem to be working for deconstruction recipes. If you look at "data\json\recipes\recipe_deconstruction.json" the various badges like the deputy_badge have copy-from deconstruction definitions. But ingame they are listed as: http://prntscr.com/kr2ki8

**To Reproduce**  
Create new world, spawn in character, and spawn in a deputy badge, the description will say it can be deconstructed but it will give no result.

**Expected behavior**  
Copy-from says the deputy badge should give the same stuff as the cybercop badge, which is 30 silver.

**Versions and configuration(please complete the following information):**
Windows 7
Release 0.C 7813
Tiles
No mods

**Additional context**  
I didn't test if this also applies for other recipes, or if it only affects deconstruction.

**Comment by cake-pie** [comment]
duplicate/related #24702 #21870

**Comment by Night-Pryanik** [comment]
I'd say it should be closed then.
