### ISSUE TITLE
Explosives destroy other explosives, rather than detonate them

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25396]
You can throw a stick of active dynamite onto a pile of inactive dynamite, and all the inactive explosives are destroyed rather than properly detonated.

**Comment by CoroNaut** [comment]
Now i can chain mininukes together. EXCELLENT!!!

**Comment by FulcrumA** [comment]
To be honest, in case of some explosives that'd be the realistic behavior. Some of them are intentionally made very stable exactly to limit chain reaction and need very specific mechanism working in a very specific way to create the explosion.
Thus, whether chain reaction is possible should depend on what one wants to make react in such a way - and how.

**Comment by Regularitee** [comment]
>To be honest, in case of some explosives that'd be the realistic behavior. 

Very rarely, and not applicable to any in-game, except maybe the mini-nuke.

C-4 is hardened against impact and heat, but is detonated using a shockwave. You know, something explosives generally produce.

Comp-B, used in hand grenades, can be detonated using both impact and heat. Explosives could create sufficient impact force, but not necessarily sufficient heat ignititon (5 seconds @ 260C).

Almost everything else in the game are homebrew improvised explosives, so would likely by far, far less stable than military-grade explosives.

**Comment by kevingranade** [comment]
Explosives in physical contact (or in the same tile) can probably be assumed to detonate each other (nuclear weapons would explode but almost certainly not cause a nuclear reaction).  This includes c4, dynamite, and probably ANFO.

The other question is at what distance explosives will detonate each other, I'd like to defer that sort of thing until I overhaul explosive blasts.  I'm planning on calculating overpressure at all distances from the explosion, which should be a good indicator of whether the explosive should detonate.
