### ISSUE TITLE
Bright Nights name/description possibly confusing new players

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25417]
For the 3rd or 4th time, I've encountered a new player in the discord who thought Bright Nights was a "reduce nighttime darkness" mod. Which probably isn't helped any by its description not really making clear what the mod itself does. (In all fairness, many mods have similarly vague descriptions. Though that's usually okay since their names make it clear what the mod does in most cases.)

Any chance we could get the description, or perhaps even title, updated to make it easier to understand at a glance that it's a total conversion mod? I realize its within the author's right to name and describe their mods however they want, but it'd help avoid some confusion among newer players if there was a bit more clarity.

Even renaming it to "Bright Nights Total Conversion Mod" or the like could help avoid some confusion.

**Comment by cainiaowu** [comment]
I think "Bright Nights Behind" would be clearer.

**Comment by Regularitee** [comment]
@Coolthulhu , isn't this your mod? Your thoughts?

**Comment by Coolthulhu** [comment]
Would be better in "Conversion mod" category.

**Comment by Night-Pryanik** [comment]
Guess this could be closed after absorption by Aftershock.
