### ISSUE TITLE
Naked zombies intentional?

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#25419]
**Versions and configuration:**
All 0.C versions, including current experimentals

**An issue**
Recently, while fixing some loot of pilot corpses/zombies, I've noticed that neither pilots nor other military zombies have their clothes spawn guaranteed. I assume it's to balance some of the good stuff they may drop as per loot, but it also leads to very weird situation where downed zombie soldiers can appear to have no clothes at all. A mental image that only gets even more disturbing/hilarious given that rest of their loot may still spawn, suggesting their very stretchy bodies contain various items tucked questionably into various crevices.

**Expected behavior**  
I wouldn't mind looking through various types of zombies and fixing it up, making their clothes spawn with 100% chance but first I'd like a feedback whether it's intentional, what are the opinions of the community on that etc

**Alternatives**
Guaranteed clothing spawn could be alternatively balanced by making not all items in boundaries of the clothing group guaranteed or/and making them more damaged on average or decreasing slightly chance of non-clothing loot spawn

**Comment by cainiaowu** [comment]
Turn off zombie revivification.

**Comment by cainiaowu** [comment]
Did you turn off the zombie revivification?

**Comment by FulcrumA** [comment]
No. But I don't talk about zombies killed xth time. Even tested freshly spawned zombies which were then killed confirmed what you can check in the lootlists of theirs which have their clothing groups set at about 65% spawn chance.

**Comment by Lazyactor** [comment]
IMO the health state of clothing on zombies is in a good spot. Most of there clothes are gonna be damaged but once in awhile you find a full health backpack or cargo pants. its rare enough to be significant. That being said it isnt out of the realm of possibility for a few zombies not to be wearing there sunday best when it went down. missing shirts here. 1 sock there sorta thing. But i think its more of a touch of detail more than anything else. Zombies spawning naked but still have loot is okay i think.

**Comment by FulcrumA** [comment]
>Zombies spawning naked but still have loot is okay i think.

Thus my comment on them holding a few items in their body orifices as without clothing, even assuming the zombie is grasping the items in their arms, they shouldn't hold much. The issue of it clashing with description of zombies characterized by their clothing and/or equipment is on top of that.

I do not mind some pieces of clothing being missing, it's the fact they're usually coming fully clothed or completely naked that's iffy enough that I made this ticket to discuss it.

**Comment by kevingranade** [comment]
Most zombies should have some kind of clothing spawn yes.
