### ISSUE TITLE
Mini-nuke can no longer be disassembled

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25430]
Talking to Kevin on discord, he mentioned that the removal of the mini-nuke crafting recipe had the unintended side-effect/bug of preventing them from being disassembled for nuclear fuel.

Since this was not intended, I'd recommend a new crafting recipe be added that is functionally a disassembling: a recipe that "consumes" a mininuke to produce nuclear fuel as a result.

**Comment by CoroNaut** [comment]
It will be fun coming up with a process that a civilian could do with knowledge pretty much limited to books or pages from labs. Similarly related: #25266

**Comment by cake-pie** [comment]
Should be `uncraft` recipe accessed via `(` disassemble rather than `&` crafting.

Would be nice if it had a chance of KABOOM depending on player skill, but don't think that's possible with a recipe.

**Comment by FulcrumA** [comment]
Yes, it's weird - I am prety sure thre are items in game specified as butcherable/to be disassembled but cannot be actually crafted (or at least the recipe is not achievable by the player). I am sure mininukes disassembly could be implemented the same way without having to set up some fancy way of making them.

**Comment by cake-pie** [comment]
As I said, `uncraft` recipes.
Examples at `/data/json/recipes/recipe_deconstruction.json` and `/data/json/recipes/engines.json`

**Comment by Regularitee** [comment]
The ability to make nukes was explicitly removed by Kevin. He likely won't allow an overturning of that, even if that was the issue here. But it's not.

The issue here is the disassembly of mininukes for fuel. Kevin mentioned that the ability to disassemble them was unintentional, so therefore it is a bug (at least, until such a time he or others wish it to be intentionally so).

**Comment by AbsalomAchitophel526** [comment]
Considering a mini-nuke cannot be launched, thrown reasonably by anyone, and generally has to be activated then dumped on the ground before use, its "miniaturization" is mostly theoretical on the player end.  Sure, you can dump in a (very large) rucksack... but why?

With the sole exception of the mini-nuke hack, of course.
