### ISSUE TITLE
CTD when removing meat stored in a smoking rack

### ISSUE THREAD

**Issue by DarkRainX** [CleverRaven/Cataclysm-DDA#25437]
**Describe the bug**  
After realising I din't have enough charcoal to use the smoking rack I left the meat (and charcoal) in the rack to see if I could procure more coal (I failed at it), next day I figured I might as well cook some of that meat before it rotted, so I went to the rack and tried to retrieve my meat, the game then froze briefly before crashing to desktop with no error. After deconstructing the rack and trying again, I found the crash only happens once the meat has stayed in the rack past midnight, doesn't matter if it stayed in the rack for 16 hours or 4 minutes, interestingly I can avoid the crash by standing on some meat chunks while unloading the rack.

**To Reproduce**  
1. Build smoking rack.
2. Acquire some meat chunks.
3. Insert the meat chunk into the smoking rack.
4. Wait till midnight.
5. Try to remove the meat chunks from the rack.
6. CTD.

**Expected behavior**  
The game shouldn't crash, I don't know if I'm not supposed to, but I also think it should be possible to remove un-smoked food from the rack, at least before activating it.

**Versions and configuration(please complete the following information):**
 - OS: Gentoo linux.
 - Game Version: 0.C-31579-gf656b8d.
 - Graphics version: Tiles.
 - Mods loaded: DDA, tall buildings, more survival tools, vehicle additions pack, tanks and other vehicles, urban development, alternative key map, boats, folding parts pack, filthy clothing, makeshift items mod, more locations, beta national guard camp.

**Edit**
Attaching saved game: Load it, wait till midnight, CTD.
[Lyme.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/2363784/Lyme.tar.gz)

**Comment by Robik81** [comment]
Yup, I can confirm the crash. In my case, no waiting was not necessary. Right after stuffing the rack, attempt to remove it crashes the game.

Also, if you insert food into the rack multiple times. Info display is messed up.

Added 50 chunks, display is OK
Added another **30** chunks, display shows
-> chunks of meat (50)
-> chunks of meat (50)
