### ISSUE TITLE
Bomb Fragments ignore Walls 

### ISSUE THREAD

**Issue by TheMrMomo** [CleverRaven/Cataclysm-DDA#25443]
**Describe the bug**  
In the recent developmental 7863 Bomb Fragments hit Characters behind Walls.
**To Reproduce**  
1. Make a player with grenades. 
2. Throw active grenade at enemy outside. Close door and get behind wall. 
3. Grenade explodes, Fragments bypass the wall to injure/kill Players and NPCs

**Expected behavior**  
Fragments or Shrapnel should not be able to hit a Character behind a reinforced Concrete Wall or similar. Fragments should be blocked by walls or the walls should be destroyed.

**Versions and configuration(please complete the following information):**0.C Build #25439 
 - OS: Windows 8
 - 0.C-31649-gc0bcd64 (tiles)
 - Tiles
 - Mods loaded: dda, Simplified Nutrition, Disable NPC Needs, Filthy Clothing

**Comment by CoroNaut** [comment]
There was recently a patch to pretty much eliminate a lot of fragmentation and use light raycasting to calculate the shrapnel that does get launched meaning that if this is a bug, it is in clear conflict with #24171

**Comment by kevingranade** [comment]
Need more info, I just attempted to reproduce with a grenade and a house, and took no damage (but was deafened as expected) when a wall was interposed between myself and the grenade.

If you are very close to the bomb but around a corner, the blast *can* propagate around it and still damage you, that is working as expected.

If you are hit by a blast it will say:
You're caught in the explosion!
If fragments hit you it will say:
You are bit by a large number of bomb fragments...

**Comment by TheMrMomo** [comment]
Maybe it doesn't correctly process the blast radius going around corners and defaults back to the Fragmentation. Note that the windows aren't damaged either. 


![screenshot 32](https://user-images.githubusercontent.com/43098058/45261440-dc138080-b402-11e8-9478-02bdaebb0643.png)
![screenshot 33](https://user-images.githubusercontent.com/43098058/45261442-e0d83480-b402-11e8-80a3-97da3479c62d.png)
![screenshot 34](https://user-images.githubusercontent.com/43098058/45261444-e6357f00-b402-11e8-8853-760cb455d7d6.png)

**Comment by kevingranade** [comment]
Can you post screenshots of your options menu or options file?
I positioned myself and the grenade exactly as in your screenshots and took no damage.
Side note, it drew the explosion, which is itself a bug.

**Comment by TheMrMomo** [comment]
![screenshot 35](https://user-images.githubusercontent.com/43098058/45262046-e9366c80-b40e-11e8-852e-8f7c309a9557.png)
![screenshot 36](https://user-images.githubusercontent.com/43098058/45262047-ecc9f380-b40e-11e8-8e46-259091c89831.png)
![screenshot 37](https://user-images.githubusercontent.com/43098058/45262048-f0f61100-b40e-11e8-9b3b-733979cf68e0.png)
![screenshot 38](https://user-images.githubusercontent.com/43098058/45262050-f2bfd480-b40e-11e8-842a-6211c715a417.png)
![screenshot 39](https://user-images.githubusercontent.com/43098058/45262051-f5bac500-b40e-11e8-83ab-b49308615a17.png)
![screenshot 40](https://user-images.githubusercontent.com/43098058/45262052-f81d1f00-b40e-11e8-8571-0093740ed2bc.png)
![screenshot 41](https://user-images.githubusercontent.com/43098058/45262054-fb180f80-b40e-11e8-9eb3-1ec1ea9f90f9.png)
![screenshot 42](https://user-images.githubusercontent.com/43098058/45262056-fe130000-b40e-11e8-8c49-0859a8eed9f4.png)
![screenshot 43](https://user-images.githubusercontent.com/43098058/45262057-00755a00-b40f-11e8-93c7-6eda8c071338.png)
![screenshot 44](https://user-images.githubusercontent.com/43098058/45262062-0408e100-b40f-11e8-839d-05ef55d4f15c.png)
![screenshot 45](https://user-images.githubusercontent.com/43098058/45262065-0834fe80-b40f-11e8-8c6a-95e5747760fd.png)
![screenshot 46](https://user-images.githubusercontent.com/43098058/45262067-09fec200-b40f-11e8-939b-95e9ae3fc0d2.png)


Where is the options file located?

**Comment by CoroNaut** [comment]
Options file is located when you find executable(catacylsm.exe) ->config->options.json

**Comment by Xhuis** [comment]
I can confirm that this is happening with vehicles as well. This happened when I was driving over a minefield.
![cataclysm-tiles_2018-09-12_18-26-54](https://user-images.githubusercontent.com/15898043/45456667-aa780f00-b6b9-11e8-87f1-5e135c3721e1.png)
Here is my vehicle.
![cataclysm-tiles_2018-09-12_18-26-57](https://user-images.githubusercontent.com/15898043/45456671-aea42c80-b6b9-11e8-957e-f7c6ae4ac064.png)

This also occurred when I was attempting to destroy a turret within a lab, and I placed a grenade outside of two metal doors(!) then closed it, and was struck by a lot of shrapnel regardless.
![cataclysm-tiles_2018-09-12_05-44-10](https://user-images.githubusercontent.com/15898043/45456728-dd220780-b6b9-11e8-987b-6c886629c875.png)

**Comment by Zireael07** [comment]
@Xhuis: The original reporter has Z-levels on, do you have them on too?

**Comment by Xhuis** [comment]
Yep.

**Comment by tinukedaya** [comment]
Getting hit by the fragments even behind closed doors... 

Grenadier died in the room to the left. 
![image](https://user-images.githubusercontent.com/19891532/46575710-b6a27400-c9ba-11e8-85bd-faa430b8605d.png)

z-levels are on by me as well...

**Comment by mlangsdorf** [comment]
Just had a zombie grenadier's grenade hack kill my companion and thoroughly wound me, despite having closed the doors between the grenade hack.

Also have z-levels on. It's very noticeable in labs.
