### ISSUE TITLE
Fat Zombies aren't fat enough

### ISSUE THREAD

**Issue by vlad1492** [CleverRaven/Cataclysm-DDA#25445]
Full butchery of example fat zombie results in 128 units (30.46kg) of tainted meat and just 3 units (0.58kg) of tainted fat.  Others are in similar range. 

**To Reproduce**  
Butcher a fat zombie. 

**Expected behavior**  
The creature description suggests an obese or morbidly obese human. Expected >30% fat by mass.

**Comment by Robik81** [comment]
I would say that there is general lack of fat in butchering anything.

**Comment by nexusmrsep** [comment]
This was brought to my attention and i will look into it ASAP.

**Comment by Robik81** [comment]
Please check the bone yield as well, it seems also too small.

Here is butchering result of deer at SURV 4 with stone knife (11 butchering)

- 1 stomach
- 30+ offals
- 120+ meat
- 8 bones
- 0 fat

order of butchering was

- field dress
- split to quarters
- 4x full butchery at rack
