### ISSUE TITLE
Heater part

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#25440]
**Is your feature request related to a problem? Please describe.**  
Given recent discussions about the temperature caused by freezing feature and how, while useful for defrosting of stuff, current hot air creation through fires and whatnot is different from reliable, lasting heating.

**Describe the solution you'd like**  
Heaters of various types are pretty common IRL, including portable ones. Adding a portable, one tile heater vehicle to be found at offices and in houses, consisting of a small battery, wheels and heating unit, working in a way of creating zone of increased, possibly regulated temperature in vicinity when active at the price of the energy stored in the battery would help.

**Describe alternatives you've considered**
Letting people suffer needlessly, against common sense and believability as one should have access and/or ability to build such devices, given that much more advanced ones are possible.

**Additional context**  
The feature would not require much of additional work but would allow quite much more improvement to one's base or vehicle without current hacky way of making temperature more comfortable just because someone sits in a locked car. It would however also use some adjustment of cable spawn for hooking the heater up to stationary generators.

**Comment by FulcrumA** [comment]
>vehicles do not contain heat, so a moving vehicle with an active heater would leave a trail of warm air behind the vehicle while the vehicle mostly remained ambient temperature.
That's exactly why the suggestion making the raise of temeprature an ambient aura automatically increasing temperature in x tiles from the part, rather than the current air heating.

**Comment by nexusmrsep** [comment]
I wonder if a change to gas propagation mechanics would be possible, to include passable, exclude impassable vehicle parts along with vehicle movement to carry the fields around. It would be ideal as then heater part could be adopted to both heat radiation and hot air.

**Comment by Regularitee** [comment]
>Hot vehicle tiles could create hot air which would then spread.

The two games I know that have attempted an ambient air/gas tracking system (SS13, DF) both have ended up dedicating a large portion of their total CPU usage to such a system. So unless CDDA is not only prepared to create such a complex system, and inflict the increased load on its players' computers, we won't be seeing any real hot air/gas tracking in the game any time soon. A fixed "aura" around the source is much less CPU intensive, and is the same system already used in game.

**Comment by nexusmrsep** [comment]
@Regularitee actually smoke, toxic gases, hot air were around for long time and didn't have a huge impact or we would hear about it by now. Im not trying to invent anything new here, but, having some knowledge how fields (of gas) work, im asking myself aloud if there is a way to combine existing systems that were not cross synchronized together.

**Comment by Regularitee** [comment]
Smoke and gas only affect the tiles there in, and only need tracking for those tiles. Same for smell. Every other tile in the game is just considered a void, with no value prescribed.

An full ambient gas temperature system would require each and every tile to have its own air temperature. Every. Single. Tile. That would certainly have some impact on game performance, in save size if nothing else.

**Comment by nexusmrsep** [comment]
Yeah, and as you said it does in both mentioned games. However what I wanted to say here there is no need for such intense simulation, not even on the horizon, as present ones are sufficient. Even wide spread effects like weather can often be simulated cost-effectively. With limits, but thats another story I guess.

**Comment by vlad1492** [comment]
Lamp oil (kerosene) heater. 

Electrically heated vehicle seats.

**Comment by nexusmrsep** [comment]
@CoroNaut do you have any evidence that a working feature is a "hack" and a "scab on the code" or you just have a "feeling"? What stops you from implementing your idea instead of throwing empty slogans?

**Comment by pingpong2011** [comment]
Why not take the system from how fire heat works? Distance-based heating. Maybe for slightly more useful it has a really low drop-off function, or a fixed value over the radius - something enough to warm the player 20-30 clothing units in winter (an option for intensity vs power consumed?). Conversely, this may be adaptable to an air conditioning unit or "inverse" fire, for extra fun fighting certain horrors.

**Comment by nexusmrsep** [comment]
It is being worked on #25509 btw.

**Comment by Night-Pryanik** [comment]
Addressed by #28706.
