### ISSUE TITLE
Mod Inclusion Project: Icecoon's Arsenal

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#25444]
Use the following issue as a space to discuss the inclusion of:

Mod Ident: ew_pack
Name: Icecoon's Arsenal

Your comment should include:

### Suggestions for induction
(what parts of the mod should be included, can be as simple as just an item, a location or the complete inclusion)

### Incompatibilities
(what parts of the mod should not be included, either some objects / items or entire mod is conflicting with DDA theme [ for whatever reason ])

---

edit:

- [ ] - Addition of select firearms as rare, limited-drop locations (for instance, National Guard Camp as prototype weaponry)
- [ ] - Rare "illegal" gun modification book to allow some crude conversion kits (mods / munition type) of advanced firearms at cost of reduced stats.

All the aforementioned are based on suggestions in thread and not necessarily written in stone, but for any contributors that would like to induct the mod in, these are the suggestions to keep in mind at least.

**Comment by Regilith** [comment]
Could probably be merged with extended realistic guns as discussed here #19037

I'm all for adding it into the base game as it wouldn't cause too much maintenance hassle, and would flesh out the futuristic guns we already have in game. But on the flip side, I can definitely relate to arguments that it's needless bloat and would dilute the ammo pool. I'm of the belief that a great many players add the mod to their games anyway, so I think the community response to it would be welcoming

**Comment by FulcrumA** [comment]
I also don't see much of an issue with this. Most of what I recall from this mod seems overall pretty balanced, though rarity of various weapons should be adjusted - and so should their spawn. Some should be restricted to aprticular places (military grade etc).

**Comment by Inglonias** [comment]
> If people don't want a massive plethora of weapons in their games, they can just use generic guns.

That would need to be updated to blacklist the guns from this mod, should it be moved into the base game.

...I think.

**Comment by FulcrumA** [comment]
@Inglonias 
Even if I doubt that should be hard. The same guns that would add the guns to the game could be copied into a blacklist.
That being said I am unsure if the guns should be copied wholesale. Not only there's a matter of ensuring they are balanced, there's also the fact that some of them seem to be unfitting in the locale. Some rare gun is fine from time to time but rare gun that's not even used at all in this part of the world - less so.

**Comment by chaisawlajatang** [comment]
TBH I'm against it. We already have dozens of ammo types and guns differing only slightly.

**Comment by DracoGriffin** [comment]
I apologize for the delay in answering.

I am partial to more "future" weapons, similar to RivTech stuff as long as it's done sparingly. In fact, some of these weapons might be more useful if they were located in the National Guard Camp as some sort of prototype weapons to recover for the Old Guard or just to keep as rewards for the player.

I am not at all knowledgeable with the practicality of the weapon types and munitions but the descriptions have some really neat flavor / background lore.

So tentatively, I believe it can be suitable if placed in very limited locations as rare/unique rarity loot. The Wrist Dread doesn't seem suitable, and crafting the weapons shouldn't be an option. Also, I like the idea of the book; a rare variant in some "undesirables" (similar to the basement autodoc) that could potentially reduce a RivTech/future firearm overall stats but allow for an additional mod or ammo type or something.

**Comment by kevingranade** [comment]
Upon review of the mod, there is literally nothing in it that fits in mainline.  We do not need more fake guns that aren't really any different from real guns.  the rivtech line is at least filling an alternate-history niche of "someone got caseless ammo to work", but these don't fill a new niche, they're simply more guns for the sake of having more guns.
