### ISSUE TITLE
Saltpeter has a circular dependany in crafting. 

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#25505]
**Describe the bug**  
Unable to craft saltpeter unless you already have it.

**To Reproduce**  
Walk the crafting chain for saltpeter and you end up needing it to make it. 

**Expected behavior**  
There should be some way to craft it initially without requiring it. 

**Screenshots**  

**Versions and configuration(please complete the following information):**
All current 

I checked the item browser to make sure there was not some alternate way to make nittric acid which is what requires saltpeter but there appears to not be other way to craft it other then via niter which is uncraftable.  Perhaps Niter is something you can mine but I have yet to find it. 

Salt Peter -> ammonium nitrate -> nitric acid -> saltpeter

**Comment by Mecares** [comment]
Nitric Acid can be found in labs...

**Comment by Night-Pryanik** [comment]
...and on scientists, and in electronic shops.

**Comment by Treah** [comment]
@Night-Pryanik 
Just be cause it can be found does not resolve the problem of Saltpeter requiring itself to craft... Have you checked the Yields you get to ensure your not always having to find something to be able to make it? Otherwise why even have the crafting recipe at all and just have Saltpeter as a drop only? Kinda makes it confusing as to the point.

**Comment by sfsworms** [comment]
You need salt water to make salt, and you need salt to make salt water.... This is common. This "circle" of recipe lets you get to any point of it if you find something on the circle.
