### ISSUE TITLE
Pain information hides hunger level on wide sidebar

### ISSUE THREAD

**Issue by Squishums** [CleverRaven/Cataclysm-DDA#25513]
**Description**
The new pain indicators (#24894) overrun the hunger display when using a wide sidebar. Displays as normal on narrow, or when using the self-aware trait.

**Screenshots**  
Wide. No visible hunger (should be to the left of thirst).
![image](https://user-images.githubusercontent.com/2533896/45265887-569ec900-b420-11e8-9368-bcf5e3e8e0e0.png)

Narrow. Peek-a-boo. Hunger display now visible.
![image](https://user-images.githubusercontent.com/2533896/45265893-7209d400-b420-11e8-8926-6531b471f433.png)

The the tiredness information is to the right of thirst, so it can't just be shunted over.

**Comment by kevingranade** [comment]
Hunger has been moved to be visible in wide mode.
