### ISSUE TITLE
Apply effects in scenarios

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#25522]
**Is your feature request related to a problem? Please describe.**  
There are a few hard-coded challenges that start with effects applied to the player character, like infected or bad day, but no way to alter those in the JSON files. 

**Describe the solution you'd like**  
Have any effect named in a scenario applied to a player at the beginning of a game to better customize challenge starts with wounds, diseases, drugs, hunger, thirst, fatigue, frostbite, or whatever.  A custom effect might be able to apply HP damage to limbs or even break them, but that might need some way to randomize which parts get 'attacked'.  

**Describe alternatives you've considered**  
**Additional context**  
I thought of defining an effect called "Out of Shape", that would slowly wear off over a season or two, but discovered there's no way to apply it to a starting character.

**Comment by lispcoc** [comment]
Currently, I think you can realize your idea by using LUA callback "on_new_player_created". (but it may be axed after 0.D...)
Another way is JSONize player starting condition by implementing in c++, that is a bit difficult to ensure flexibility.
