### ISSUE TITLE
Auto safe mode reactivation considers keystrokes instead of turns

### ISSUE THREAD

**Issue by maniak1349** [CleverRaven/Cataclysm-DDA#25525]
Windows, tiles, 0.C-29661-g765578f.
Mods: dda, no_npc_food, novitamins

In contradiction with it's in-game options tip Auto safe mode reactivation considers keystrokes instead of game turns. As a result thing like changing vehicle speed or direction, (de)activating bionic that does not consume time or even pressing unbound keys will affect safe mode reactivation countdown.

**Comment by int-ua** [comment]
Cannot reproduce on build 11388.
