### ISSUE TITLE
Thermal insulating storage vessels

### ISSUE THREAD

**Issue by clockworkhawk** [CleverRaven/Cataclysm-DDA#25520]
**Is your feature request related to a problem? Please describe.**  
You can't drink frozen liquids, so to quench the thirst in winter you need to defrost liquids every time.

**Describe the solution you'd like**  
Thermos, thermos canteen etc. Some can be electric and maintain the temperature using batteries.

**Comment by cake-pie** [comment]
Duplicate #24882

**Comment by mlangsdorf** [comment]
Closing as duplicate.
