### ISSUE TITLE
Keypresses are spammed endlessly on main menu

### ISSUE THREAD

**Issue by rm-code** [CleverRaven/Cataclysm-DDA#25528]
**Describe the bug**  
When you have a world with no saves and try to load, the game seems to endlessly spam the keypress resulting in the "no save games found" message and a continuous loop of the "failure" sound.

**To Reproduce**  
1. Create a world (but no character)
2. On the main menu press up on the load menu to select the empty world and then press right

**Expected behavior**  
Well ... I expect it to only play the sound once.

**Screenshots**  
Not applicable.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-31878-g02e0a7f
 - Graphics version: Tiles

**Comment by MT-Arnoldussen** [comment]
yes, this is quite annoying
