### ISSUE TITLE
Soap and water should be able to clean bites

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#25558]
**Is your feature request related to a problem? Please describe.**  
It would be nice if we could use good ol' soap and water to clean bites and deep wounds. I don't think it can fix infections, but bites would be neat
**Describe the solution you'd like**  
See above
**Describe alternatives you've considered**  
Not doing this, which is also fine. We have plenty of ways to clean bites already, but we wash our hands with soap IRL, so...
**Additional context**  
Soap kills germs and stuff.

**Comment by sfsworms** [comment]
Soap isn't as effective as disinfectant for killing germ, especially if the wound is deep.

**Comment by Lorith** [comment]
I actually [made a mod for that](https://cdn.discordapp.com/attachments/252368751016542218/489446611559251968/soapywater.7z) a while back, seems I forgot to put it anywhere except discord?

**Comment by Inglonias** [comment]
> Soap isn't as effective as disinfectant for killing germ, especially if the wound is deep.

So? Make it less likely to work than the disinfectant, then.

**Comment by Zireael07** [comment]
Soap isn't enough for many germs irl, actual wounds are very rarely treated with it.

**Comment by MT-Arnoldussen** [comment]
You can already cauterize the wound if you don't have disinfectant. Not sure what this would add to the game.

**Comment by Inglonias** [comment]
Alright. I guess I need to check to see what it is I'm talking about before making suggestions like this. Thanks for the input.

**Comment by Vasyan2006** [comment]
Cleaning the wound with disinfectant is as effective as cauterizing. It can help, but will harm much more.
Initial cleaning must be separated in new action and use clean water or saline solution. Disinfectant must be applied around the wound to prevent further infections.
