### ISSUE TITLE
Animal pounds and pet supply stores share an overmap key with libraries and electronics stores, which are far more valuable

### ISSUE THREAD

**Issue by Xhuis** [CleverRaven/Cataclysm-DDA#25561]
**Is your feature request related to a problem? Please describe.**  
This was an issue with other locations in the past. Libraries and bookstores have an inverted-brown arrow to represent them on the overmap, and are high-value locations due to their book stockpiles. Electronics stores have a yellow arrow and can be invaluable for spare parts.

Animal pounds and pet supply stores, which have far less impact, share these overmap keys, which is misleading and forces the player to scroll over each one to decide if a town is loaded with loot or just a bunch of zombie dogs.

**Describe the solution you'd like**  
Animal pounds and pet supply stores should change their overmap colors or keys to something not yet used or something colored appropriately.

**Describe alternatives you've considered**  
Alternate Overmap Key may not be updated yet. I've also considered making my own mod for it, as I had used that solution for a very long time before porting it to baseline in #24495, but such a solution isn't sustainable long-term and doesn't solve the issue for others.

**Additional context**  
![image](https://user-images.githubusercontent.com/15898043/45449994-ce7d2580-b6a4-11e8-8594-7aea0762703f.png)
![image](https://user-images.githubusercontent.com/15898043/45449998-d210ac80-b6a4-11e8-8dfa-365817fdec6a.png)

___

![image](https://user-images.githubusercontent.com/15898043/45450029-db9a1480-b6a4-11e8-98da-c15128da5ff4.png)
![image](https://user-images.githubusercontent.com/15898043/45450030-df2d9b80-b6a4-11e8-9b59-93c192cabe28.png)

**Comment by MT-Arnoldussen** [comment]
>Alternate Overmap Key may not be updated yet.

It is! And if it's ever not feel free to ping me in the discord or here, and I'll make sure to add it to my to-list.
