### ISSUE TITLE
Crash using EMP grenade on Milspec turret

### ISSUE THREAD

**Issue by runforitkyle** [CleverRaven/Cataclysm-DDA#25579]
**Describe the bug**  
Game crashes to desktop when using EMP grenade on Milspec turret, the crash does not occur when using the EMP grenade on other targets or by its self. Throwing a normal grenade does not cause this crash.

**To Reproduce**  
1. Make a player with an EMP grenade and an electrohack in front of a bunker
2. Hack the panel which opens the doors with the elctrohack
3. Arm and throw an EMP grenade down the hallway. 

**Expected behavior**  
The game not crashing and the turrets being damaged by the grenade.

**Screenshots**  
![image](https://user-images.githubusercontent.com/39907551/45472774-87606480-b778-11e8-9af0-5ebb3588ef25.png)
Location of grenade that causes a crash

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-31982-gda4e596
 - Graphics version: Tiles
 - Mods loaded: DDA, Filthy clothing, Disable NPC Needs, NPC traits, Mutant NPCs, Manual Bionic Installation, Safe Autodoc

**Additional context**  
[Megucaland.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2378103/Megucaland.zip)
The save where the crash is occurring.

**Comment by CoroNaut** [comment]
I had made reloaded and thrown 6 nades to the specified location
first 2 time: no crash, next 3 time: got crash to desktop, last time: got microsoft runtime error "Program terminated in unusual way" then crash to desktop.

**Comment by AMurkin** [comment]
I had unresponsive process and CTD after several seconds when emp grenade should explode near a turret. No related lines in debug.log.

**Comment by Regularitee** [comment]
I can confirm this problem exists. I've had similar crashes using the old fashioned technique of arm grenade, pop around lab corner, toss grenade, and run. Crashed in about 2 of 5 attempts.

**Comment by mrkybe** [comment]
Taking a look at this now.

**Comment by ZhilkinSerg** [comment]
Adding early return to `Creature::has_effect`

```CPP
    if( effects->empty() ) {
        return false;
    }
```

switches crash to

![image](https://user-images.githubusercontent.com/16213433/45547293-fa291880-b828-11e8-8f24-e2efa587f5d1.png)

**Comment by AMurkin** [comment]
May be related: #22071
