### ISSUE TITLE
Lab start player spawn location

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#25585]
**Describe the bug**  
Lab start can spawn the player outside of the lab itself

**To Reproduce**  
1 start a new lab challenge and observe spawning location
2 reset world and restart lab challenge until you are spawned outside of the lab
**Expected behavior**  
Lab start should spawn the player inside the lab

**Screenshots**  

https://cdn.discordapp.com/attachments/252368751016542218/489755503317221376/unknown.png

https://cdn.discordapp.com/attachments/252368751016542218/489755563727519747/unknown.png

edit: added character generation screen, fortunately i posted this too https://cdn.discordapp.com/attachments/252368751016542218/489751889886576640/unknown.png

**Versions and configuration(please complete the following information):**
 - OS: Win 10
 - Game Version  jenkins 7906
 - Graphics version tiles
 - Mods loaded
[
  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "bio_mod",
  "makeshift",
  "More_Survival_Tools",
  "alt_map_key",
  "npc_traits",
  "Hairs",
  "mutant_npcs",
  "more_locations",
  "Experimental-Z-Level",
  "Urban_Development",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "more_classes_scenarios",
  "RL_Classes",
  "manualbionicinstall",
  "safeautodoc",
  "speedydex",
  "StatsThroughKills",
  "StatsThroughSkills"
]

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by MT-Arnoldussen** [comment]
I'm not sure this is an issue only for labs. I've had it happen for the Last Firefigher spawn too (started in a Church instead of a Fire Station), once.

**Comment by Zireael07** [comment]
I think this is a reoccurrence of a known issue, basically you can't guarantee that this special location will exist when spawning? So very rarely there is no lab/firestation, whatever, for you to spawn in.

**Comment by BrianLefler** [comment]
My best guess is that lab_stairs on the surface level is being selected as the overmap tile, then rejected because it is not escapable (lower levels are accepted, because they have a path to stairs up).  In scenarios.json, changing 'lab_stairs' to 'lab' and 'ice_lab_stairs' to 'ice_lab' would address that possibility.

Someone can do a quick patch, or I'd like to revisit lab escape in more detail anyway in the next week or two and can look into this when doing so.
