### ISSUE TITLE
Recovering solder on disassembly should not be possible

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#25614]
**Describe the bug**  
You can recover solder that was used to craft an electronics item.

**To Reproduce**  
1. Get an item whose recipe contains solder, e.g. circular saw
2. Try to disassemble it.
3. There is solder in the disassemble pile.

**Expected behavior**  
Solder should have the unrecoverable tag just like duct tape does.
I don't expect it can be somehow gathered off the soldered connections and made back into a usable spool.

**Screenshots**  
![screenshot_circsaw](https://user-images.githubusercontent.com/11006744/45581679-331ec700-b8d5-11e8-95cf-8ea6030f0104.png)

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu MATE (16.04 LTS)
 - Game Version 0.C-31838-g769f1f6
 - Terminal

**Additional context**  
None

**Comment by CoroNaut** [comment]
Duplicate: #25576

**Comment by Marrim** [comment]
Oh, alright, I close this then.
