### ISSUE TITLE
Plastic bottle of water will not unfreeze near fire

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#25625]
**Describe the bug**  
If I place a bottle of frozen water near a fire it will not unfreeze waited 16+hrs and still frozen.
Did not test other items just the water I started with.

**To Reproduce**  
Start game in doors and place two by fours in the oven.
light fire and place bottle of frozen water on a table next to it.
Skip time and water will not become unfrozen

**Expected behavior**  
For water to become unfroze after XX time

**Screenshots**  
https://i.imgur.com/LGpJULZ.png

**Versions and configuration(please complete the following information):**
 - OS: = Win 10 64bit
 - Game Version = 7917
 - Graphics version = tiles
 - Mods loaded Lots but also tested with NO MODS

**Additional context**  
Thanks again :)

**Comment by alanbrady** [comment]
I believe these two are related #25626
