### ISSUE TITLE
Food not chilling in ice lab

### ISSUE THREAD

**Issue by Asseverater** [CleverRaven/Cataclysm-DDA#25626]
Game version: 0.C-32110-g9b133d9 (latest experimental)

Operating system: Windows 7, 64-bit

Tiles or curses: tiles

Mods active: Dark Days Ahead, Filthy Clothing, Disable NPC Needs, Simplified Nutrition, Alternative Map Key, NPC Traits, Beta National Guard Camp, More Buildings, More Locations, Tall Buildings, Urban Development

**Expected behavior**

Food left in an ice lab on level -1 where temperature is -22C should become (cold) and (frozen) in short order.

**Actual behavior**

Food in an ice lab on level -1, including ordinary water which freezes at 0C does not become (cold) nor (frozen) even after hours of waiting - tested during summer, if that matters. The bug is very fresh - introduced either today or yesterday, likely as a result of merging commits related to PRs #25242 and  #25509.

**Steps to reproduce the bug**

Put a container of water on level -1 ice lab (thermometer showing -22C), wait nearby. Observe no change in the state of water.

**Comment by alanbrady** [comment]
I'm guessing I broke the position index for getting temperature somewhere and it's now pulling the wrong value.  Fire in a brazier isn't warming up nearby food anymore either.  I think the two are the same problem.  Will look.
