### ISSUE TITLE
Add intravenous needletip bionic to bionic surgeon profession.

### ISSUE THREAD

**Issue by Sorgklaan** [CleverRaven/Cataclysm-DDA#25643]
I don't have any specific reason or argument for it, but it's a fairly low power bionic and it fits really well with the theme of the bionic surgeon. I just feel like it's a good thing to add for the sake of thematics without affecting the power level of the profession much.

**Comment by Night-Pryanik** [comment]
Surgeons usually conduct operations on other patients, not on themselves. Intravenous Needletip is designed to administer drugs into oneself, not to other patients. I see no reason to give Needletip to the Bionic Surgeon.

**Comment by nexusmrsep** [comment]
Unless it would be made so that it works both like self-IV and a syringe equivalent for external injections too, what do you think @Xhuis ?

**Comment by Xhuis** [comment]
I'm fine with it either way. It'd definitely fit in Cyberjunkie, if nothing else.
