### ISSUE TITLE
Shopping cart with added frame not moving parallel to movement vector

### ISSUE THREAD

**Issue by communistkiro** [CleverRaven/Cataclysm-DDA#25641]
**Describe the bug**  
Attaching a the 3 elements of a shopping cart, i.e, extra light frame, shopping carts, casters; to an existing one caused me to get a `collides with errors in movement code` when I try and walk over `flashbang` on the ground, though not tear gas or incendiary grenades. 
Additionally, grabbing and dragging any of the two carts result in them moving perpendicular, no parallel, to direction of movement; this however only in the cardinals, they stay like that when moving diagonally as well. Works with 3 carts, could probably make a shopping cart swastika rotate..
_edit:_ swastika didn't work, it's not as rigid as previously thought, though the dragging still isn't would you'd assume given how rotational forces work.

**To Reproduce**  
1. Attach extra-light frame to shopping cart.
2. Grab it.
3. Haul ass with extra drag. (The would-be torque created would be absurd to resist)

**Expected behavior**  
Attacking a frame to another, both having casters (the presence of which should make pulling/dragging easier, yet here the walk move cost w/ a grabbed 3-card w/ 3 casters is the same as that of a 3-cart with one set of casters). Expected behavior is that of a chain, each link following the next til you get to the hand doing the pulling/pushing.

**Versions and configuration(please complete the following information):**
 - OS: win7
 - Game Version [from the main menu, e.g. 0.C-32110-g9b133d9] build from like yesterday?
 - Graphics version tiles
 - Mods loaded -will supplement if need

**Comment by Regularitee** [comment]
I wonder if it's related to how the game treats every row of wheels as its own turning axel? 

Additionally, I can't say if it's related, but I've noticed that unfolding small (2-4 tile long) folded vehicles beneath yourself (and placing a piece of inaccessible vehicle beneath you, like a board or shopping cart), will cause it to get stuck with "Vehicle collides with errors". Regardless of direction or where you are.

It only becomes unstuck when the vehicle is released, and grabbed from another spot.

**Comment by TealcOneill** [comment]
@GuardianDll Can no longer reproduce. Copied this set up and drug it over several flashbangs and dozens of other objects.
- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: cdda-experimental-2024-05-15-1833 7f06e9f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
