### ISSUE TITLE
Telling an NPC to "wait at this base" causes them to leave your party

### ISSUE THREAD

**Issue by belazzz** [CleverRaven/Cataclysm-DDA#25655]
**Describe the bug**  
When you have a camp created via a bulletin board and tell an allied NPC to "wait at this base", they run off as if you had told them you want to part ways. Next time you talk to them, the dialog is the same as before they were recruited by you.

**To Reproduce**  
1. Have an enclosed room with a bulletin board.
2. Have an allied NPC following you.
3. Examine the bulletin board and choose "create camp".
4. Talk to the NPC and choose the option "Wait at this base".

**Expected behavior**  
The NPC stays inside the room.

**Observed behavior**  
The NPC leaves as if you had dismissed them.
_UPD._ Roughly 50% of the time they may stay in place, but will still consider themselves neutral rather than your ally (the dialog will be "Another survivor! We should travel together" and so on).

**Versions and configuration**
Windows 10 x64, game build 7914, Tiles.

**Comment by belazzz** [comment]
Not sure what happened, but after saving and reloading it started working fine. I had also told the NPC to guard a position and then stay at the base again, that may have played a role too. Looks like this is not as reproducible as I thought.

**Comment by belazzz** [comment]
Did some more testing. This abnormal behavior stops as soon as you command the NPC to guard a position at least once. Before that telling them to wait at base causes them to either run off or stay where they are, it roughly 50/50, but in any case they will no longer consider themselves allied with you (the dialog will be "Another survivor! We should travel together" and so on).

**Comment by TechyBen** [comment]
Thanks. Got the "running off" thing too at some point, but thought it was me pressing the wrong button (managed to catch back up with them in a car). But... so... this is a bug then?

IIRC these two have guarded at least once. I have 1 more NPC left (though can spawn more of cause for testing) so will try that too.

**Comment by mlangsdorf** [comment]
Should be an easy fix to assign them to guard the basecamp.

**Comment by mlangsdorf** [comment]
Option to "Wait at this base" was removed some time ago.  Closing.
