### ISSUE TITLE
NPC Brag about Needs when NPC Needs are Disabled!

### ISSUE THREAD

**Issue by adamdeno** [CleverRaven/Cataclysm-DDA#25658]
**Describe the bug**  
The Bug is about NPC requirments (Sleep , hunger , thirst)

**To Reproduce**  
1. Create a World with Both (NPC needs disabled + NPC Traits)   <------- Important
2. Get a Friendly NPC and Play like you would normaly
3. MAKE SURE NPC HAS (Chemical Imbalance) as the bug wont work  <----- Important

**Expected behavior**  
NPC shouldnt Brag about His Needs since NPC needs is disabled

**Observed behavior**
At a random Time due to Trait "Chemical Imbalance" NPC will request  Hunger/Thirst
(P.S Not Sure For hunger as Thirst was Seen In NPC Character Page and Said "My mouse is dry")

**Screenshots**  
(No screen shot avalible as i am Accurate about the bug!)

**Versions and configuration(please complete the following information):**
 - Windows 10
 - Game Version   0.C-32130-ge18aa07
 - Graphics version   Tiles 
 - Mods loaded 
[ DarkDaysAhead , Mining Mod , More Survival Tools , Classic RogueLike Classes  ,  StatsThroughSkills , Vehicle Additions Pack , Tanks and other Vehicles , Bionic System Mod , Boats , Folding Parts Pack , Filthy Clothing , Makeshift Item Mod , Classes And Scenarios Mod , Disable NPC Needs , NPC Traits , Mytholigal Ryplicas]

**Additional context**  
(None Avalible , Since the game Gives the NPC Random Need or not)
(P.S he sleeps everyday (normal?))

**Comment by cake-pie** [comment]
dupe #23715

**Comment by adamdeno** [comment]
oh thanks for telling me that didnt know someone else did that
