### ISSUE TITLE
Increase the Quench displayed value (not the effect)

### ISSUE THREAD

**Issue by hameleona** [CleverRaven/Cataclysm-DDA#25660]
**Is your feature request related to a problem? Please describe.**  
I like the new caloric display for nutrition, but I find myself constantly misjudging the quench value of stuff, because I expect both systems to work on a similar scale. 

**Describe the solution you'd like**  
The displayed Quench values should be increased by the same amount that the nutrition value was when changing to calories. This is not a request to change the effects. 

**Additional context**  
Currently it's just confusing.

**Comment by Marrim** [comment]
Why not make satiation and quench display percentage of healthy daily intake instead of calories or arbitrary units?

**Comment by Theundyingcode** [comment]
> Why not make satiation and quench display percentage of healthy daily intake instead of calories or arbitrary units?

Daily intake required is variable due to traits and effects.  Displaying Kcal is simply a matter of passing the value but, a percent of daily intake would need to be constantly recalculated and the variation would make comparing foods confusing.

**Comment by kevingranade** [comment]
The objective value for quench would be in volume of water, but thsts not related to calories either.

Fundamentally they're not related and we're unlikely to force them to be related.

**Comment by hameleona** [comment]
They are confusing as hell. And that is my only problem, honestly. 3 separate variables with separate scales is confusing as hell.

**Comment by Theundyingcode** [comment]
> They are confusing as hell. And that is my only problem, honestly. 3 separate variables with separate scales is confusing as hell.

Personally they don't confuse me but I second the notion that having large nutrition value and a small quench value can be misleading since it gives the impression that nothing will hydrate you very much.
