### ISSUE TITLE
Tip of the Day: suggestions

### ISSUE THREAD

**Issue by EirenexTheDragon** [CleverRaven/Cataclysm-DDA#25686]
I opened this issue in response to #25560  . this issue here should ideally be a place for other people to leave their suggestions of tips, that would fit greatly to be displayed for the Tip of the Day.
I hope that this way we can perhaps collect a nice amount of tips of the day, and make sure it wont become to stale when some tips repeat themselves.

a very easy and quick template to how to leave your suggestion here is to include it in a "Text", like here:

"The Enemy of your enemy is probably your enemy too."

**Comment by woutershep** [comment]
"Turrets occasionally have nightmares about encroaching bookcases."

**Comment by Rod995** [comment]
"Burning mushrooms is a great way to serve up fungi! The naturally meaty and earthy flavors of mushrooms pair beautifully with the smokey ashes that fire adds to them."

**Comment by Leland** [comment]
Closing – please use the forums for collective discussion like this: https://discourse.cataclysmdda.org/

**Comment by nexusmrsep** [comment]
@Leland  I disagree but its your call.
