### ISSUE TITLE
Experimental. Stimulants can not got above certain number. Build #7930

### ISSUE THREAD

**Issue by WilliamtheCardboardBox** [CleverRaven/Cataclysm-DDA#25684]
**Describe the bug**  
Stimulants such as caffeine, cocaine, and any other drug that increases the stimulant stat do not increase it above 61 stimulated and 31 stimulate overdose.

**To Reproduce**  
1. Mass consume any stimulate inducing drugs or items.
2. Wait any amount of time and the stimulant level will return to 0 as expected

**Expected behavior**  
After sniffing 80 units of cocaine and 120 caffeine pills I expected the stimulant stat to increase to the required number for a heart attack.

**Screenshots**  
![bug](https://user-images.githubusercontent.com/43382886/45700943-dffa7d80-bb3b-11e8-9607-66e91142a621.PNG)
Time is then passed and stimulants reduce as expected. Failed to equip a watch but approximately an hour and thirty minutes was passed by the wait function.

![bug time](https://user-images.githubusercontent.com/43382886/45700999-0ddfc200-bb3c-11e8-87c7-4d7bdd63c78d.PNG)

**Versions and configuration**
 - OS: [Windows 10]
 - Game Version [0.C-32214-g0c28494]
 - Graphics version [Tiles]
 - Mods loaded [No additional mods loaded]

**Additional context**  
This has been reproduced on other builds by other people.

**Comment by wapcaplet** [comment]
Confirmed, still reproducible in 0.E-9681-g2cca4d658c. After consuming 200 caffeine pills and 200 hits of cocaine in a row, effects cap at Stimulants (61) and Stimulant Overdose (31), but it wears off in a few hours with apparently no adverse effects.

**Comment by actual-nh** [comment]
Whenever this gets fixed, this should be made into a test - as a future note (possibly to myself), see iuse_test.cpp.
