### ISSUE TITLE
Fail to run cataclysm-launcher or cataclysm-tiles with the latest stable or demo version

### ISSUE THREAD

**Issue by mudinlove** [CleverRaven/Cataclysm-DDA#25696]
**Describe the bug**  
When run 'cataclysm-launcher' or 'cataclysm-tiles', it returns error messages:
`dbus[4195]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)`

I googled and found it should be an issue of dbus and libsdl2 in Ubuntu (my OS is Ubuntu 18.04). Then I upgraded the libsdl2 to the proposed version like [https://bugs.launchpad.net/ubuntu/+source/libsdl2/+bug/1772471](url)

But I still got the same failure.

Actually, I cloned the latest source codes from git and compiled it myself. But the issue is still there...

**To Reproduce**  
1. Run 'cataclysm-launcher' or 'cataclysm-tiles'
2. It shows error messages and exits.

**Expected behavior**  
The game should be played normally.

**Screenshots**  
(N/A)

**Versions and configuration(please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Game Version [0.C-2834] and [0.C-7811-manual]
 - Graphics version [Tiles]
 - Mods loaded [N/A]

**Additional context**

**Comment by ZhilkinSerg** [comment]
What was compilation command line?

**Comment by ZhilkinSerg** [comment]
Also did you try https://forum.odroid.com/viewtopic.php?p=220443?

**Comment by mudinlove** [comment]
I tried it with:
`make TILES=1 SOUND=1 RELEASE=1 LUA=1 USE_HOME_DIR=1`

Thanks.

**Comment by mudinlove** [comment]
> Also did you try https://forum.odroid.com/viewtopic.php?p=220443?

I did not try this. But I guessed this workaround should be workable because I am using ibus for Chinese Input. Many thanks for your sharing.

Now I got the SDL2 source codes and tried to compile it without dbus support. Hope this can work, too.

**Comment by mudinlove** [comment]
Another easy way to work around this error is:
`export DBUS_FATAL_WARNINGS=0`

Tested and it's workable
