### ISSUE TITLE
[BUG] Hollow/Light Bones mutation not conferring speed advantages.

### ISSUE THREAD

**Issue by Xindii** [CleverRaven/Cataclysm-DDA#25707]
The 'Light Bones' mutation and 'Hollow Bones' mutation advantages +10% speed and +20% speed respectively do not seem to work in conjunction with the 'quick' trait.

**To Reproduce**  
1. Make a player with the traits 'quick'.
2. Use the debug menu to add the bird mutation categories for 'hollow bones'.
3. Character @ only shows and confers the +10% speed bonus from quick, and not the ones from Light or Hollow Bones.

**Expected behavior**  
I expected either the 20% bonus from the hollow bones perk to take priority over quick, or stack, and give me a speed of either 120% if replacing, or 130% if stacking with quick.

**Versions and configuration(please complete the following information):**
 -Windows 7
 - Game Version [0.C-32238-g8f0b634]
 - Graphics version [Tiles]
 - Mods loaded [None]

**Additional context**

**Comment by Regularitee** [comment]
Correct me if I'm wrong here.

The Hollow/Light bones specifically says "...enabling you to move and attack 10/20% faster". Which is not an increase in speed, but rather a decrease in the "moves per attack" and "moves per... movement"

**Comment by kevingranade** [comment]
Mutations are working as intended, they decrease costs, they don't increase move points per turn.
