### ISSUE TITLE
Inconsistency in using pumpkin for broth

### ISSUE THREAD

**Issue by jbytheway** [CleverRaven/Cataclysm-DDA#25709]
**Describe the bug**  
Currently pumpkin and irradiated pumpkin can be used to make sealed glass jars of broth, but not regular broth.  Compare:

https://github.com/CleverRaven/Cataclysm-DDA/blob/6e7b56a97a1b083f9759574f497c7733097ce7e0/data/json/recipes/recipe_food.json#L1801-L1820
https://github.com/CleverRaven/Cataclysm-DDA/blob/6e7b56a97a1b083f9759574f497c7733097ce7e0/data/json/recipes/recipe_food.json#L4279-L4300

**Expected behaviour**  
I would expect the two recipes to be consistent in this respect.  Probably by adding the two pumpkin options to the non-jar version.  Or if there is a reason for the difference for it to be mentioned in the description.

**Versions and configuration(please complete the following information):**
 - OS: Linux
 - Game Version: Observed in 0.C-30027-gb61d8457b9 but still present on master as linked above
 - Graphics version: Tiles

If the obvious fix is the right one then I'm happy to make a pull request.

**Comment by alanbrady** [comment]
Seems like an oversight to me, obvious fix sounds right
