### ISSUE TITLE
Trying to sleep is uninterruptible while zombie bashing your car/allies

### ISSUE THREAD

**Issue by latogato** [CleverRaven/Cataclysm-DDA#25708]
**Describe the bug**  
It is an old but very annoying problem. If your toon try to sleep but can’t, the time passes without interrupt. If this time zombies attack your vehicle, your allies etc. you can’t react to the danger.

Here a lone zombie broke my windshield and fight with a friendly NPC while my toon tried to sleep:
[screenshot](https://discourse-cdn-sjc2.com/standard11/uploads/cataclysmdda/original/2X/0/087075066ec23b64bd4ef3ecfe4eb8b68756b181.png)

**To Reproduce**  
1) Debug a car.
2) Debug a zombie few steps away from the car the way the zombie can see you
3) Try to sleep and watch the spam messages about the zombie bashing your car.

**Expected behavior**  
Trying to sleep should be interruptable like reading, butchering, etc.

**Versions and configuration(please complete the following information):**
 - OS: Win 7 x64
 - Game Version: 0.C-32309-g6e7b56a
 - Graphics version: Tiles
 - Mods loaded: defaults

**Comment by alanbrady** [comment]
I seem to have read your mind already https://github.com/CleverRaven/Cataclysm-DDA/pull/25612

Currently has a bug or two I need to sort but should address this

**Comment by latogato** [comment]
Thank you, i find it really funny i just opened this report about this really old bug and your solution is already ready to merge. :smile:
