### ISSUE TITLE
Trap damage ignores armor

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25713]
In addition to [being invulernable](https://github.com/CleverRaven/Cataclysm-DDA/issues/23540), traps also completely bypass armor when doing damage. This allows otherwise imposing enemies like tank drones or armored zombies to be easily felled by the mightly wood-and-nail nailboard trap.

Obviously, an infinitely re-usable trap that can also fell the most powerful monsters in the game is somewhat of a balancing concern.

**Comment by AbsalomAchitophel526** [comment]
I was just collating all my screenshots and info to make an encompassing issue but alas, I was ninja'd.

In any case, a Chicken Walker dies to 12 nailboard trap hits, a old school Tank Drone with more health but less armor took 25, and they survive nukes of all sizes.  Skeletal Jugg's take far, far more - at least 60 - but are also the easiest/best enemies to use it against, as they are quite slow but have significant health and armor.

For 3 2x4's and 20 nails and Trapping skill 0, they may be humanity's most powerful weapon against the Cataclysm.

**Comment by cavos** [comment]
Hi, can I take this issue?

**Comment by DracoGriffin** [comment]
>Hi, can I take this issue?

@cavos Of course, you can take any issue and submit a PR. Generally assigning individuals is left to larger, encompassing projects as indicating a pseudo-lead on that aspect (to avoid clashing code), with kevin still overseeing the overall project.
