### ISSUE TITLE
Skeletal Juggernaut is incredibly light weight.

### ISSUE THREAD

**Issue by AbsalomAchitophel526** [CleverRaven/Cataclysm-DDA#25714]
**Describe the bug**  
Skeletal Juggernauts are less than a quarter dense as balsa wood.  They are 25 kg at 875 liters.  875 liters is equivalent to .875 of a cubic meter.  Balsa Wood, the lightest material on this chart, http://mojobob.com/roleplay/weight_chart.html, is 125 kg per cubic meter.  Adjusted to 875 liters, or .875 of a cubic meter, Balsa Wood would weigh in at 109 kg at the volume of the displaced by the Skeletal Juggernaut.  This is more than four times as much.

Skeletal Juggernauts in game are lumbering behemoths.

**To Reproduce**  
1. Kill a Juggernaut
2. Check its' weight and volume
3. Scratch head

**Expected behavior**  
For Juggernauts to either have an appropriate density given their behavior, or for their behavior to match their density.

**Comment by nexusmrsep** [comment]
There are some hard-coded weight converters for corpses not made of flesh that will be removed when size/weight/volume Pr will be finished to fix it.

**Comment by Night-Pryanik** [comment]
Should be closed after #25756?

**Comment by codemime** [comment]
Apparently no, it doesn't change its corpse's weight.

**Comment by Night-Pryanik** [comment]
As of latest experimental at September 29, 2019, skeletal juggernaut's corpse weights 200 kg.
![изображение](https://user-images.githubusercontent.com/11132525/65834982-e811ff00-e2f1-11e9-9e9f-e527129dea69.png)
