### ISSUE TITLE
When your sleep is interrupted the screen does not update

### ISSUE THREAD

**Issue by latogato** [CleverRaven/Cataclysm-DDA#25711]
**Describe the bug**  
If you sleeping but a noise wakes you up then the screen shows only the dark screen like you still sleeping until your next move.

**To Reproduce**  
1. Debug a car.
2. Set your fatigue to 500 (d,1,n,f,500)
3. Debug a zombie few steps away from the car the way the zombie can see you
4. Go to sleep and wake up when the zombie starts to bash your car. You will just see some question marks but everything else is dark like when you sleep.

**Expected behavior**  
See your surrounding like when you wake up properly.

**Versions and configuration(please complete the following information):**
 - OS: Win 7 x64
 - Game Version: 0.C-32309-g6e7b56a
 - Graphics version: Tiles
 - Mods loaded: defaults

**Additional context**  
It is not a new bug at least few months old. There was a screen update error in Jun - it was [fixed](https://github.com/CleverRaven/Cataclysm-DDA/pull/24038) - maybe related to it.
[Here](https://discourse.cataclysmdda.org/t/screen-refreshing-problems-7468/15718) is the forum topic about it.

**Comment by alanbrady** [comment]
I don't think I addressed this in https://github.com/CleverRaven/Cataclysm-DDA/pull/25612 but I can look.

**Comment by latogato** [comment]
Thank you, i find it really funny i just opened this report about this really old bug and your solution is already to merge. :smile:

**Comment by alanbrady** [comment]
Indeed funny coincidence :) :+1:
