### ISSUE TITLE
Friendly robot transforms into a friendly blob

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#25726]
**Describe the bug**  
Friendly robot steps into a goo pit and becomes a friendly blob.

**To Reproduce**  
1. Use a control laptop to convert a robot into an ally.
2. Have the robot walk over a goo pit.

**Expected behavior**  
Robot is unaffected by the blob, being inorganic.
In case of organic creatures (dogs?) the resultant blob should probably be hostile.

**Versions and configuration(please complete the following information):**
Windows 10, version 0.C-32309-g6e7b56a (curses), no mods.

**Comment by cake-pie** [comment]
Confirmed.

![25726a](https://user-images.githubusercontent.com/28502722/46330800-64bebe80-c647-11e8-9419-04024b2136a0.png)
![25726b](https://user-images.githubusercontent.com/28502722/46330801-64bebe80-c647-11e8-81b6-da582c6a5241.png)
