### ISSUE TITLE
[Suggestion]Variable volume in smoking racks from JSON

### ISSUE THREAD

**Issue by Maddremor** [CleverRaven/Cataclysm-DDA#25727]
**Is your feature request related to a problem? Please describe.**  
Currently the smoking rack has a hardcoded maximum volume of food that can be loaded in a single session. This is defined as 
```
namespace sm_rack {
    const int MIN_CHARCOAL = 100;
    const int CHARCOAL_PER_LITER = 25;
    const units::volume MAX_FOOD_VOLUME = units::from_liter( 20 );
}
```
When gaining a large amount of meat (say, by killing a moose) I would like to have the ablity to procces said meat on a bigger scale without manually filling, checking and balancing charcoal supply for multiple individual smoking racks.

**Describe the solution you'd like**  
I suggest exposing `MAX_FOOD_VOLUME` to JSON to allow "higher tiers" of smoking racks, with greater material cost and skill requirements since this is best interpeted as the character building a taller or similarly larger rack on a singular tile.

**Describe alternatives you've considered**  
Beside the obvious solution of "it works fine as it is now", some ideas came to me:

- Tie smoking volume to regular terrain/furniture capacity akin to the charcoal kiln.
- Set up a UI solution to manage multiple smoking racks. (See zone designation and farming for conceptual similarity)
- Allow multiple racks across different tiles work together as a single entity when interacted with by the player. (This seems like a big capability to add compared to the payoff)

**Additional context**  
Pinging @nexusmrsep since for being the the person mostly working with this.

**Comment by nexusmrsep** [comment]
Ideally also ingredient to product conversion table should be JSONized but
unfortunately it's far on my TO DO list and lack of time doesn't help.

czw., 20 wrz 2018, 09:26 użytkownik Maddremor <notifications@github.com>
napisał:
