### ISSUE TITLE
Wearable UPS unit

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#25733]
**Is your feature request related to a problem? Please describe.**  
The only viable use for the UPS unit is powering your armor or weapons. Which is all fine and dandy but it does not live up to the name _Unified Power Source_.

Tools such as hotplate, soldering iron, welder and jackhammer can be hooked up to UPS by attaching a mod, but unless you have a UPS bionic or a vehicle-based recharging station, you must recharge the UPS unit with batteries... and in that case you may as well just discard it and keep using batteries everywhere.

If you do have a vehicle-based recharging station, you can recharge all your tools directly from it, bypassing the need for a UPS unit. And the advanced UPS unit is even worse because it does not interact with the recharging station at all, and I don't want to waste plutonium to power my soldering iron and hotplate.

It all boils down to the unit not being terribly space efficient, thus there is a great incentive to skip using any UPS stuff until you can get the bionic.

**Describe the solution you'd like**
Make the UPS unit wearable at the hip, like the plastic canteen or XL holster, thus saving inventory space.
_and/or_
Create a new heavy-duty UPS unit that holds more charge (5-10k), and can be worn as a backpack.
Lore-wise I could see the latter being used by military engineers, and the former by non-powerarmored troops.

**Describe alternatives you've considered**
- Making the advanced UPS chargeable from a solar backpack and from the recharging station, instead of using plutonium.
- Making UPS units more space-efficient in general. The extra battery mod helps somewhat.
- Ability to modify a medium storage battery to serve as an UPS power bank.

**Comment by chaisawlajatang** [comment]
> you can recharge all your tools directly from it, bypassing the need for a UPS unit

Nope. An UPS unit contains 1000 charges, thus it can feed a tool much longer.

**Comment by kevingranade** [comment]
I'm fine with making UPSs wearable.
XL UPS backpack also sounds great.

**Comment by SunshineDistillery** [comment]
If UPS is converted from a hardcoded object into a json flag, you could have as many variations as you wanted.
