### ISSUE TITLE
Fridge/freezer have to fight against their own insulation

### ISSUE THREAD

**Issue by cake-pie** [CleverRaven/Cataclysm-DDA#25746]
**Version**
32342-g48e3967

**Describe the bug**  

Fridge/freezer have to fight against their own insulation.

**To Reproduce**  

Freshly reheated plastic bottle of coffee (hot)
immediately into minifreezer (on) @ 13:17:24
loses hot flag @ 17:56:12 -- more than 4.5h

Freshly reheated plastic bottle of coffee (hot)
immediately into minifreezer (off) @ 13:17:24
loses hot flag @ 17:56:12 -- more than 4.5h

Freshly reheated plastic bottle of coffee (hot)
left at ambient temperature (2~7°C) @ 13:17:24
loses hot flag @ 14:08:24 -- approx 50min

Savescummed tests for consistency; heating was done with pot over fire.

Update: if we edit json to remove insulation from fridge/freezer,
Freshly reheated plastic bottle of coffee (hot)
immediately into minifreezer (on) @ 13:17:24
loses hot flag @ 14:08:24

**Expected behavior**  

Insulation value of fridge/freezer should not thwart its own cooling effect.

**Comment by FulcrumA** [comment]
Can you verify whether it's not just a display issue? I've noticed that items hidden in the basement maintain their (hot) tags sometimes even for days, but get updated almost immediately upon being picked up.

**Comment by cake-pie** [comment]
Freshly reheated plastic bottle of coffee (hot)
immediately into minifreezer (on) @ 13:17:24
taken out @ 15:17:24 -- still hot, replace immediately
taken out @ 16:17:24 -- still hot, replace immediately
taken out @ 17:17:24 -- still hot

Not a display/updating problem.
The important telltale sign to notice here is the identical behavior regardless whether freezer is on or off.

Your issue is different, you should probably file it separately.

**Comment by cake-pie** [comment]
Further testing:

Edit json to remove insulation from fridge/freezer, then try:
Freshly reheated plastic bottle of coffee (hot)
immediately into minifreezer (on) @ 13:17:24
loses hot flag @ 14:08:24

The behavior becomes identical to if it were left outside.

Together with code inspection this confirms that the fridge/freezer has to fight against its own insulation.

It is also a bit disappointing that putting hot item into freezer ([-5°C](https://github.com/CleverRaven/Cataclysm-DDA/blob/df728fdec8d6f9d840b446ae92cac02c7532f828/src/game_constants.h#L83)) does not cool it down any faster than leaving it out in ambient 2~7°C environment -- maybe consider adjusting [`temp_difference_ratio()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/df728fdec8d6f9d840b446ae92cac02c7532f828/src/item.cpp#L5990)

**Comment by alanbrady** [comment]
Just to confirm yes insulation will cause something to cool slower.

Just to throw this out there, when you put something HOT into a colder environment it will cool faster.  The expected behavior here is that because the freezer is colder than outside it should freeze faster.  However, what you're not considering is that the heat from the item has to be displaced somewhere and the freezer has to compensate for that.  So realistically when you put something HOT into a fridge it should not only cool the item but raise the inside temperature of the fridge, thus take longer to cool.  Keeping in mind this is a minifreezer.

The only real solution I see is to actually start modelling the inside temperature of things like a freezer so that it can behave more accurately.  It would also be nice to refactor item temperatures again to use real temperatures and a heat function instead of item counters which is why this is kind of weird to begin with.

**Comment by alanbrady** [comment]
Also just to add to this, you could actually just remove the insulation value from fridge/freezer and that will effectively solve this as well, but that means if you turn off the fridge/freezer, it will not retain an inner temperature which is why I gave them insulation to begin with.

**Comment by cake-pie** [comment]
>  yes insulation will cause something to cool slower.

I do not dispute that the freezer (whether on or off) should insulate the hot coffee from the outside (map) temperature, so it should cool slower.

The problem is that even when on, it seems that the freezer is also insulating the coffee against the freezer's own interior [-5°C](https://github.com/CleverRaven/Cataclysm-DDA/blob/df728fdec8d6f9d840b446ae92cac02c7532f828/src/game_constants.h#L83) which makes no sense at all

**Comment by alanbrady** [comment]
Hrm maybe an another easy fix would be to override the insulation if value is on, might be easy enough.

**Comment by alanbrady** [comment]
> The problem is that even when on, it seems that the freezer is also insulating the coffee against the freezer's own interior -5°C which makes no sense at all

It's technically not -5C once you put something HOT in there since it heats up the inside of the freezer.

**Comment by cake-pie** [comment]
> ... start modelling the inside temperature of things like a freezer so that it can behave more accurately. It would also be nice to refactor item temperatures again to use real temperatures and a heat function instead of item counters which is why this is kind of weird to begin with.

I too have been seriously thinking about this possibility because it would be really helpful for:
- #25330 averaging temperature when mixing liquids
- #25664 average out the temperatures of all the components used to craft the new items
- #25693 needing "normal" range of temp between hot and cold
  - once we're doing that we might as well actually track actual temps rather than counters
- freshly boiled (near 100°C) water should stay hot longer in thermos than, say, reheated tea (60-65°C is "safe to drink" temperature)

Have some ideas, been meaning to find time to write them down properly -- maybe this weekend.

---

> It's technically not -5C once you put something HOT in there since it heats up the inside of the freezer.

Sure, but it's still 0.5L of hot coffee vs 74.5L of cold air.

Related: if we're talking about modeling the fridge interior temp, consider
- freezer (off) containing 10 gallon jugs of tea (hot)
- freezer (off) containing 10 gallon jugs of tea (hot) + 10 gallon jugs of lemonade (cold)
- freezer (off) containing 10 gallon jugs of lemonade (cold)

Would be nice to have heat exchange between hot tea and cold lemonade in the middle scenario, so they lose their hot/cold tags sooner than the other two cases.

**Comment by Zireael07** [comment]
> Sure, but it's still 0.5L of hot coffee vs 74.5L of cold air.

Where does it say the freezer has 75L capacity? Most minifreezers are half this at most.

**Comment by cake-pie** [comment]
> Where does it say the freezer has 75L capacity?

https://github.com/CleverRaven/Cataclysm-DDA/blob/df728fdec8d6f9d840b446ae92cac02c7532f828/data/json/vehicle_parts.json#L721

![frz](https://user-images.githubusercontent.com/28502722/45893949-81fdbc80-bdff-11e8-97e9-2b7dac079060.png)

**Comment by cake-pie** [comment]
Look, it's beside the point to talk about the hot coffee heating up the interior of the freezer, or heat capacity of liquid vs air, etc. None of that behavior is actually modeled in the code; it shouldn't be used to explain unintended outcomes.

The crux of the issue is that fridge/freezer insulation, as currently implemented, inadvertently cripples their own function. This is not specific to hot items only. All fridge cooling is effectively halved; all freezer cooling is reduced to a quarter of what was intended.

**Comment by alanbrady** [comment]
> Look, it's beside the point to talk about the hot coffee heating up the interior of the freezer, or heat capacity of liquid vs air, etc. None of that behavior is actually modeled in the code; it shouldn't be used to explain unintended outcomes.

I'm just saying I'm not convinced the model is wholly inaccurate.  While yes the intricacies are not modeled as you point out, we're using a simplified model so capturing fine details like this not necessary if the end behavior is the same.  Just because the model doesn't explicitly simulate something, if the end behavior is the same, then it works.

Again, I encourage you to take a swing at trying to use real temperatures if you're so inclined, I'm just saying it will be a challenge to get it to work correctly, be performant, and may not actually behave as differently as you imply.

**Comment by Robik81** [comment]
Cooling inside the fridge should not be inhibited by it's own insulation. Insulation is here to prevent heat exchange outside of heat exchanger. And heat exchange between heat exchanger and air around the fridge is outside of insulation.

**Comment by cake-pie** [comment]
>  Then items in inside just grab the current fridge/freezer temp and ignore insulation.

`thermos of coffee` inside the fridge/freezer *should* still use thermos insulation value to throttle heat exchange between coffee and fridge inside temp, regardless of fridge turned on/off.

First instinct might be to dismiss "thermos in fridge" as silly, but this actually makes sense if e.g. a minifreezer (off) is used as passive insulation, stacked with that of the thermos, to maintain item hot/cold for that bit longer without expending electricity.

**Comment by alanbrady** [comment]
> thermos of coffee inside the fridge/freezer should still use thermos insulation value to throttle heat exchange between coffee and fridge inside temp, regardless of fridge turned on/off.

Yeah no worries there, it's easy enough to sidestep the fridge/freezer insulation without affecting things like thermos insulation.  I've been playing with it and it actually looks like just not applying the insulation if the fridge/freezer is on is actually the way to go, but I'm still going to see how hard it is to simulate an inner temperature.
