### ISSUE TITLE
Cold - Water, Clean Water and Food - Freezes after consuming them

### ISSUE THREAD

**Issue by gustavoghe** [CleverRaven/Cataclysm-DDA#25741]
**Describe the bug**  
When i get to my food pile, and press E i see a list of things that are cold (Ie. Clean Water (Cold)), after i consume the item, it instantly becomes frozen. There is no time between consumig, it just instantly becomes frozen.

**To Reproduce**  
1. Mid winter, leave some food in a shelter near the fire.
2. Leave it be, when the food becomes cold, consume it
3. Whatch that same food become frozen

**Expected behavior**  
I beleive, that if in that moment the water is cold, it should take a while to become frozen again.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version [from the main menu, e.g. 0.C-32238-g8f0b634]
 - Graphics version [Tiles]
 - Mods loaded [Medieval Historic Content, Stats through Skills, More Survival Tools, Ninja Mod, Vehicles and Aditions Mod, Tanks, Bionics Systems Mods, Folded Parts, Icecoons Arsenal, Filthy Clothing]

**Additional context**  
https://drive.google.com/file/d/1Men6mLddbjzH3LnTlOwzyot_H5TXYMyO/view?usp=sharing

**Comment by alanbrady** [comment]
So I tried it with your save file and I wasn't able to reproduce.  However I looked at your screenshot you posted in discord again and noticed that your thermometer is saying 0C, which is the temperature at which water freezes.
![image](https://user-images.githubusercontent.com/60370/45857078-fe16d800-bd0b-11e8-9f36-bda3e7f847ce.png)

So yes you're correct that fire should warm up your water, however the actual outside temperature is less than 0C, the thermometer actually reads the exact temperature the item is using at that spot.

My suggestion is to light a second fire to produce more heat and outpace the outside freezing, counter to that, items in your inventory get a +5F boost to temperature (~2.2C).  So if you're by the fire and your thermometer is reading 0C, putting it in your inventory will prevent it from freezing.  Additionally you get a little bit of insulation for items in the inventory meaning they will change temperature slower.

Lastly, items like the "thermos" give a **ton** of insulation which means if you heat up water and put it in the thermos is should say non-frozen for something like 10 hours without any help from a fire.

**Comment by Kelenius** [comment]
I've had the same thing happen as well. There was a pile of cold food/water, and if I tried to eat one of them, the game would say that it's frozen, and it (and only it) would become frozen. I don't have any screenshots or a save file, but it's definitely a bug that happens.

**Comment by alanbrady** [comment]
Ah ok in that case it might be because I forced it to reprocess before eating.  It used to just reprocess rot, but now processing food potentially requires processing temperature.  This may have been a bad idea to change to it reprocess temperature as well in this case since it's creating this weird behavior.  The fix is to change it back to just reprocess rot I guess, but now I'm questioning whether that was correct to do either.
