### ISSUE TITLE
Ropes used to tie animals to a spot do not carry their condition

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#25748]
**Describe the bug**  
Using a damaged rope to tie a friendly animal to a spot and then untying it returns a rope in perfect condition.

**To Reproduce**  
1. Tie a friendly animal (fed livestock, for example) with a short rope
2. Untie the animal

**Expected behavior**  
The rope maintains its previous condition.

**Versions and configuration(please complete the following information):**
- OS: Win7
- Game Version: 0.C-32345
- Graphics version: Tiles
- Mods loaded: DDA, More Survival Tools, StatsThroughSkills, Vehicle Addition Pack, Tanks and Other Vehicles, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable NPC Needs, No Antique Firearms, No Fungal Monsters, No Fictional Guns, NPC Traits, Extended Realistic Guns.

**Comment by Night-Pryanik** [comment]
Adressed by #32068.
