### ISSUE TITLE
Player unable to attack friendly livestock

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#25749]
**Describe the bug**  
#2733 happens again with new domesticated animals - livestock, birds. One cannot attack them directly - no option to do so by melee and upon an attempt to shoot them, character refuses to steady their aim.

**To Reproduce**  
1. Tame an animal such as a bird
2. Attempt to kill said bird through direct, non-environmental means

**Expected behavior**  
Rifle can be steadied and aimed even at friendly creatures. Possibly a new option of manually choosing a target for a forced melee attack (akin to smash) could also be allowed to avoid similar issues in the future and do away with having to add "attack" option to context menu for every friendly creature.

**Versions and configuration(please complete the following information):**
- OS: Win7
- Game Version: 0.C-32345
- Graphics version: Tiles
- Mods loaded: DDA, More Survival Tools, StatsThroughSkills, Vehicle Addition Pack, Tanks and Other Vehicles, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable NPC Needs, No Antique Firearms, No Fungal Monsters, No Fictional Guns, NPC Traits, Extended Realistic Guns.

**Comment by Marrim** [comment]
With high survival there should be an option to "slaughter" the animal if it is restrained, that would bypass any melee checks and just require a tool with cutting 1 or something.

I'm just saying.

**Comment by Night-Pryanik** [comment]
Closing in favor of a more generic issue #24297.
