### ISSUE TITLE
Some photos made by the cameras are not saved

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#25759]
**Describe the bug**  
Camera items do not save pictures of some things you can make a pic of (get a message confirming making a photo and what quality it is). Tested on NPCs but may refer to things beside.

**To Reproduce**  
1. Use a camera item to make a picture of an NPC
2. Check the camera and notice no pictures in the memory

**Expected behavior**  
Camera shooting pictures of whatever saves those pictures.

**Versions and configuration(please complete the following information):**
- OS: Win7
- Game Version: 0.C-32345
- Graphics version: Tiles
- Mods loaded: DDA, More Survival Tools, StatsThroughSkills, Vehicle Addition Pack, Tanks and Other Vehicles, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable NPC Needs, No Antique Firearms, No Fungal Monsters, No Fictional Guns, NPC Traits, Extended Realistic Guns.

**Comment by mlangsdorf** [comment]
The code to save a photo is in src/iuse.cpp, lines 6246-6275. It's essentiallly a function that takes std::string mtype (set to z.type->id.str() on line 6246 while z is a struct monster), checks to see if it's in the camera item's "CAMERA_MONSTER_PHOTOS" variable, and adds or overwrites it as appropriate.

All that code could be moved done to around line 6300, following the end of the if( mon || guy ) scope. std::string mtype would need to be declared before the if( mon || guy ) scope, and would be assigned in each branch: it would continue to be z.type->id.str() for the mon branch, and guy->name for the guy branch.

This is a straightforward code refactor for anyone who wants to start working with the CDDA C++ codebase.

**Comment by fungusakafungus** [comment]
I'll give it a go.
