### ISSUE TITLE
Fish Drops Unbalanced?

### ISSUE THREAD

**Issue by Thegreenestfield** [CleverRaven/Cataclysm-DDA#25751]
Fish, when butchered, produce like one filet while butchered animals produce like 50 meat. Is this balanced?

**Comment by Muffindrake** [comment]
As a comparison point, I can waste time fishing for a corpse that is 30L in size and weighs 5.09kg, but yields only 1 stomach, 1 offal, 1 bone and 1 filet.

Or I can go wring the life out of the nearest border collie with my bare/bear hands (30L, 40.75kg) for full butchery yields of 61 chunks of flesh (that's ~8x as much meat yield if you adjust the border collie weight down to fish levels), 7 chunks of fat, 2 offal and some bones. All of this with `Survival 2` and a `steak knife`.

**Comment by nexusmrsep** [comment]
Nothing can be properly balanced until size / volume / weight rework PR is finished.

**Comment by BevapDin** [comment]
@nexusmrsep What's the other issue that this one is a duplicate of? Please close one of the two issues and like it to the remaining one.

**Comment by anothersimulacrum** [comment]
Resolved by #30896, but not closed.
