### ISSUE TITLE
Exploding grenades can infect your wounds from non-existing filthy clothes

### ISSUE THREAD

**Issue by nexusmrsep** [CleverRaven/Cataclysm-DDA#25769]
**Describe the bug**  
Exploding grenades can infect your wounds saying it's from "filthy clothes" & "bite wound seem realy deep", but character had no filthy clothes and it's a grenade, not a zombie bite..

**To Reproduce**  
1. Wear RM13 armor (active) to prevent death
2. Throw some grenades near you.
3. Inspect your wounds (it's not common, so may need few repetitions)

**Expected behavior**  
If it's intended that a dirty shrapnel can infect you, the message should change.
If its not intended 

**Screenshots**  
![image](https://user-images.githubusercontent.com/39925111/45915293-f6ae1680-be52-11e8-8c35-9796b8f759da.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 
 - Game Version latest experimental
 - Graphics version  Terminal
 - Mods loaded none

**Additional context**  
n/a

**Comment by adamdeno** [comment]
since its a frag grenade
the shattered pieces just fly at you cuasing an open wound which is going to get infected soon if not dealed with


right?

**Comment by Marrim** [comment]
None of the fragments did any damage in the screenshot.
The hurt was caused by the explosion shockwave -- that one should not cause infections at all.

**Comment by nexusmrsep** [comment]
@adamdeno nope, infection is instant, and messages suggest wrong cause. While I can understand that that might be intended, so in rare case a dirty shrapnel infects you, but @Marrim noticed that its from shockwave, and even then messages are misleading.

**Comment by kevingranade** [comment]
It is not intended.
