### ISSUE TITLE
Player faction camp manager menu has empty-labeled items

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#25779]
**Describe the bug**  
Camp manager has "hidden options" (look at screenshots).

**To Reproduce**  
Talk to camp manager and open management dialog.

**Screenshots**  
![camp_broken_1](https://user-images.githubusercontent.com/2535519/45920661-63a3c980-beb0-11e8-8a1d-3a31f34887ee.png)
![camp_broken_2](https://user-images.githubusercontent.com/2535519/45920664-69011400-beb0-11e8-9728-f93202577489.png)
![camp_broken_3](https://user-images.githubusercontent.com/2535519/45920665-6bfc0480-beb0-11e8-895b-0be1225f3160.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 7 x64
 - Game Version: 0.C-32416-gb2440cd
 - Graphics version: Tiles
 - Mods loaded: dda, Experimental-Z-Level, More_Survival_Tools, StatsThroughSkillsFour, blazemod, Tanks, Urban_Development, boats, more_buildings, more_locations, mutant_npcs, national_guard_camp, no_npc_food, no_olg_guns, no_religious_Texts, no_reviving_zombies, novitamins

**Additional context**  
I upgraded my camp about 6-8 times, also made some upgrades to nearby tiles, after making them kitchen, blacksmit and some other, if that matters.

P.S. Sorry, initially messed up a little bit with this issue description and data.

**Comment by mlangsdorf** [comment]
Partially addressed by #26063
