### ISSUE TITLE
Root cellar does not work

### ISSUE THREAD

**Issue by Robik81** [CleverRaven/Cataclysm-DDA#25771]
**Describe the bug**  
Root cellar does not work like an underground storage for food, it does not keep food in a constant low temperature any longer.

**To Reproduce**  
1. Spawn a new character
2. Move time by 20 days (probably not necessary, but that is what I did)
3. Build a root cellar
4. Spawn 3 apples. Put one in the cellar, one outside of the cellar and one underground of EVAC shelter
5. Wait till noon / dusk several times and check the apples

Result: 
- apple in the cellar and outside of it got rotten at the same time ( 23. day 12h )
- apple under the EVAC shelter is still fine

By the way, apple has 6 days rot time in room temperature, I can't imagine how the outside temperature could cause apples to rot twice as fast, given they were ( I checked ) frozen during the nights and early spring temperature should be lower that room temperature even during the day.
 
Conclusion:
- cellars are broken
- <del>rot calculation seems also broken</del>

Rotting caused by freezing and thawing twice.

**Expected behavior**  
Root cellar should behave like the underground does.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: compiled master with last commit 25675, I believe it was broken before, that's why I tested it in the first place
 - Graphics version: Tiles
 - Mods loaded: default

**Comment by alanbrady** [comment]
Definitely possible I broke it, will play with some apples and root cellars and compare notes.

**Comment by alanbrady** [comment]
Just to mention this, you realize apples have the FREEZERBURN flag right?  So if it freezes and thaws it will become mushy, if it freezes and thaws a second time it will turn rotten.  This is probably better to test with an item that is not affected by freezerburn.

**Comment by Robik81** [comment]
Nah, I did not realize that. Not that it is indicated anywhere. Though now that you mention it, I think that I read about it in the PR and then forgot it.

Pretty annoying, if you ask me.

Okay, that we can scratch the second issue, first one still stands, cellar should keep constant temperature.

**Comment by alanbrady** [comment]
You're right on both accounts.  It's not using the AVERAGE_ANNUAL_TEMPERATURE in a root cellar for temperature in this situation which it should, I probably broke that.  Then I also agree the description text for mushy should probably somehow clarify it will rot if it freezes/thaws again.
