### ISSUE TITLE
Cars colliding with little_column terrain type take unusually high damage over time

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#25781]
**Describe the bug**  
While trying to reproduce #25717 I came across this issue. It appears the little_column terrain type does a lot more damage to a car than other common terrain types, and is also invulnerable to being run over by a vehicle
**To Reproduce**  
1. Spawn a car
2. Spawn a little column.
3. Drive into the little column as slowly as possible. (The below screenshot shows the effects of driving cars into various terrain types for 30 in-game minutes)
4. Continue waiting as the car shreds itself

**Expected behavior**  
The car should take similar amounts of damage as the two cars on the right side of the test rig shown in the screenshots.

**Screenshots**  
![after](https://user-images.githubusercontent.com/2125926/45921451-cdf24500-be83-11e8-8a33-4f4aef0ca0a6.png)

The car on the left hit the little column and was shredded. Car 2 hit a guard rail and drove off into the sunset. Cars 3 and 4 hit a willow tree and a concrete wall respectively.

**Versions and configuration(please complete the following information):**
Game version: 0.C-32426-gab2de21 (Tiles)
Windows 10.

**Comment by FulcrumA** [comment]
A interesting theory was brought by @NotFuji suspecting that the car is somehow getting stuck inside the column and exploding. Would also explain how triffid trees sprouting under cars dealing more damage than if the same cars would  be hit with machinegun fire.

**Comment by CoroNaut** [comment]
For reference: #25717

**Comment by TechyBen** [comment]
Not a bug but a feature? XD
Hitting a small but hard surface will do more (piercing?) damage than hitting a larger flat surface.

**Comment by SunshineDistillery** [comment]
It seems to lack "bash" data in the json.

**Comment by Tatterdemalian** [comment]
It's the difference between a car getting hit in its "crumple zone" and getting hit in its more fragile undercarriage. I see no realistic reason why this wouldn't happen, and as far as game balance goes it keeps Triffids able to menace flame-spitting deathmobiles, even in the late game.

**Comment by Inglonias** [comment]
#25845 appears to resolve this issue. Nice work @SunshineDistillery !
