### ISSUE TITLE
NPC Commands ideas

### ISSUE THREAD

**Issue by adamdeno** [CleverRaven/Cataclysm-DDA#25780]
**Describe the idea you'd like**  

(? = a keycode from alphabet)

**Commands** will be seen while talking with NPC
?: go to this location (views map and makes NPC go to selcted map tile)
?: wield this item (select item for him to wield no matter what and store his item he had into backpack)
?: if your health is low...Run (will go to nearest billboard "Camp" if his health is around 25 or less "legs and arms are ignored")
?: Guard "That" Position... (Will Guard a selected Tile instead of him standing still "Good for NPC wars"

**Combat Commands** if Combat commands is selected will show these
?: set a trap in that location.. (will set trap to selected tile "if he has any trap in his bag")
?: Rush And attack Far enemies.../Stay and attack enemies close... (will attack monsters/NPC few maps away within Reality bubble)

**Describe alternatives you've considered**  
i know NPCs need to be modefied/overhauled/looked-at , these ideas is for NPCs you can add them if you want just to add more selections/options to NPCs

**Additional context**  
Make sure to add any more ideas at the comments vvvv

**Comment by FulcrumA** [comment]
>?: wield this item (select item for him to wield no matter what and store his item he had into backpack)

Already covered by telling them to use a particular item and then choosing a weapon as that item.

>?: Guard "That" Position... (Will Guard a selected Tile instead of him standing still "Good for NPC wars"

The NPc standing in that tile depending on its combat settings will attack nearby enemies.

>?: set a trap in that location.. (will set trap to selected tile "if he has any trap in his bag")

May cause issues. Without a lot of work so NPCs know from what side approach the tile etc it may lead to issues like NPC trapping itself with the traps you'll tell it to setup. If you're nearby you could as well do something like that before.

>?: Rush And attack Far enemies.../Stay and attack enemies close... (will attack monsters/NPC few maps away within Reality bubble)

Partially covered already by talking to NPC and setting their combat behavior. I would like t have quick orders under `C` to tell my companions to disengage and run, switch weapons between melee/ranged (provided they have  asecond weapon in the inventory) and to attack particular enemy though,

>i know NPCs need to be modefied/overhauled/looked-at 

>these ideas is for NPCs you can add them if you want just to add more selections/options to NPCs

The first should probably happen before the second can be truly indulged. Which may take a bit.

**Comment by nexusmrsep** [comment]
> I would prefer to have quick orders under C to tell my companions to disengage and run, (...)

Or as a part of "yell sentance" command where you yell something NPCs can understand and comply to.

**Comment by TechyBen** [comment]
Currently I see no option to make the GET OUT OF HERE... can that be added? Like "Get away from the Zeds, run... run now!" command? XD

**Comment by TechyBen** [comment]
Not really. If I say to the NPC "go attack", they go all out and attack, rushing in. There is no "run away" option, just a "stand there" option. :/

**Comment by nexusmrsep** [comment]
What is needed is active combat commands. If you are engaged in fight and you see your NPC friend, lets's call her Angie, being in a tight spot you could yell "Angie run away". If that could be recognized NPC could switch AI pattern on the go and act accordingly. Or: your legs got broken while fighting but Angie keeps her distance because you told her so before. Yell "Angie help, attack, engage." and she comes for help, etc. It could be a branched-out option from `yell`.

**Comment by FulcrumA** [comment]
That'd be pretty useful, yes, especially if it'd be a chosoable option, not only a yell you ahve to type out (a matter of convenience at that point).

**Comment by nexusmrsep** [comment]
Ok, so I've done some code investigation, and did some "live" tests, and it seems that via talk/yell menu you can talk with an NPC follower up to 20+ tiles away, and give him/her combat/engagement commands, so I was talking about something that already exist. For some reason I was thinking that talking to NPC would require much shorter range or face to face interaction. All in all I believe this issue is not valid in this part, perhaps valid in new possible commands, engagement rules, etc.

**Comment by paulenka-aleh** [comment]
I personally always missed these quick orders:
- Attack selected enemy
- Go to selected position and stay there
- Run away from all enemies (and hide?)
- Get on board of our vehicle (even if I'm not there yet and you're under attack)
- Cover me / selected NPC (attack enemies attacking them or closest to them)

My PC would also benefit from comman
- Patrol selected area

There are are behavior options which I miss
- Stay close to me (NPC?) / spread out / keep distance from me / etc...
- Use meds when wounded, bleeding or infected

**Comment by TriffidKing** [comment]
Some commands are more needed than others. In particular, running away to a predetermined location. Also the ability to train NPCs is a must, and not just with books. (which are a poor substitute, especially for combat skills) along that line, sparring practice with NPCs could be a great way to train everyone's melee combat skills over time even if everyone has the same skill level.
