### ISSUE TITLE
Add a JSON specification for armor that must be worn with another piece of armor

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#25797]
**Is your feature request related to a problem? Please describe.**  
There's no way to have a piece of armor have separate material/encumbrance/stats for different body parts covered.  Something like a scuba mask and connected air tank isn't really possible.  I think an OK way handle this would be to make some armors dependent on others.  

**Describe the solution you'd like**
- A dependent armor would have a required 'main' armor in its definition.
- The main armor has to be worn before the dependent armor can be worn.
- Taking off the main armor would auto-remove the dependent piece/pieces first.
- Dependent armor could be flagged to use charges from the main armor, rather than it's own. 

**Describe alternatives you've considered**  
**Additional context**  
This would be a way to handle power armor and frames with less hardcoding.  It could also include additions of modular power armor pieces, related to #24790.  There could either be some kind of 'exclusive' flag to keep people from wearing non-dependent clothes with power armor, or  just have a required type of undersuit.

It would also replace MBR disassembly/crafting recipes with a single type of main vest and dependent armor inserts.

**Comment by SunshineDistillery** [comment]
> The current method of handling MBR vests allows for the player to find different preconfigured variants around the world. Changing it to a single variant that you have to wear extra stuff with would be a step backwards.

You can handle that with item groups. Just have an MBR group with armor+plates and use that in the spawn lists. 

What I don't like about using crafting recipes for simple modular items is that a damaged items can result in components being destroyed or the damaged items being repaired in the process.

**Comment by paulenka-aleh** [comment]
I had quite an extended period in my life, about 3 years when I was drinking 6-12 cups of green tea a day (at work, at lunch, at home in the evening). Besides that I didn't drink anything else, at least not regularely.

**Comment by Night-Pryanik** [comment]
No discussion in three years, closing.
