### ISSUE TITLE
Option to disable starting NPC does not work

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#25793]
**Describe the bug**  

**To Reproduce**  

0. Ensure your default for "Starting NPCs spawn" is set to "Scenario-based"
1. Try to disable starting NPCs with static NPCs set to true
2. Fail

**Expected behavior**  
That I can set Starting NPCs Spawn to "Always" or "Never", away from "Scenario-based"

**Screenshots**  
![image](https://user-images.githubusercontent.com/2125926/45928999-d4cb9700-bf19-11e8-8fda-d577ff1bf254.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-32442-g08a96f1
 - Graphics version Tiles
 - Mods loaded: N/A - World has not started

**Additional context**  
N/A

**Comment by Xion350** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/4a1617542aeb93dd859689b21bb446f009ce99c4/src/options.cpp#L1640-L1656

Line 1651 could probably be removed without causing problems.

**Comment by Night-Pryanik** [comment]
> That I can set Starting NPCs Spawn to false

There is no `False` option available for Starting NPCs spawn. Maybe you meant _Static_ NPCs?

**Comment by Inglonias** [comment]
> > That I can set Starting NPCs Spawn to false
> 
> There is no `False` option available for Starting NPCs spawn. Maybe you meant _Static_ NPCs?

I mean, you're technically correct.
The options are "Scenario-Based", "Never", and "Always". I can't change the option away from "Scenario-Based".

**Comment by Leland** [comment]
Seems like this is an issue with the prerequisite system. Related PRs #24551, #23187.

**Comment by OzoneH3** [comment]
Looks like with the special world options logic it's testing against default values and not world option values .. hmm.
