### ISSUE TITLE
Recognize [ROAD] terrain at night

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#25803]
**Is your feature request related to a problem? Please describe.**  
I am a big fan of rollerblades/roller skates but they are really difficult to use at night because you can't tell where the roads are. (tiles are all white or lt_green symbol on black background depending on whether night vision is in use and, roads share the same symbol as fields)

**Describe the solution you'd like**  
Change the coloring so terrain with the [ROAD] flag has a dark grey background instead of a black one thus creating a visual distinction.

**Describe alternatives you've considered**  
Change the symbols used to be distinguishable but that seems like a rabbit hole.

**Additional context**  
I think that it is quite reasonable for a survivor to be able to distinguish between a road and a field even at night.

I don't use tilesets...

**Comment by Maddremor** [comment]
Another alternative would be for lane markers to be more easily visible than other terrain.

**Comment by CoroNaut** [comment]
Along with making lane markers more visible, perhaps we could introduce raised pavement markers that reflect light. If you shine a light that only goes 10 tiles, then the markers could light up to 20 tiles or so. If something is standing on a marker, don't light the marker. Also if something is between you and the marker, don't light all markers past it and you.
