### ISSUE TITLE
Mod Inclusion Project: DeadLeaves' Fictional Guns

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#25806]
Use the following issue as a space to discuss the inclusion of:

Mod Ident: FictonalWeapons
Name: DeadLeaves' Fictional Guns

Your comment should include:

### Suggestions for induction
(what parts of the mod should be included, can be as simple as just an item, a location or the complete inclusion)

### Incompatibilities
(what parts of the mod should not be included, either some objects / items or entire mod is conflicting with DDA theme [ for whatever reason ])

---

Due to lack of response, going to assume this can be closed as there is no interest in inducting into DDA.

**Comment by DracoGriffin** [comment]
As a brief statement, I believe most of the items would be acceptable in Crazy Cataclysm (especially the gunblade items).

Otherwise, I think one or two could be acceptable as futuristic, rare firearms in special locations. This is assuming that RivTech company has an agreement / contracts with the military / peace keeping forces in the New England region as to their prevalence against potential other firearm producing companies.

Or maybe rarely found in police lock-ups as some sort of illegal firearm confiscation.

**Comment by kevingranade** [comment]
I haven't taken a close look, but gun blades are not ok even in crazy
cataclysm, they need to stay in their own mod.

**Comment by nexusmrsep** [comment]
If futuristic weapons that don't fit the vanilla theme/lore are scattered among at least two mods, then perhaps some merging of mods can by done as a side-process so there would be a mod that would gather them all ("one mode to rule the all, one mod to... ").

**Comment by DracoGriffin** [comment]
Going to close for lack of interest and discussion.
