### ISSUE TITLE
Lots of broken loading of things

### ISSUE THREAD

**Issue by yarbelk** [CleverRaven/Cataclysm-DDA#25826]
**Describe the bug**  

```
A clear and concise description of what the bug is.
 DEBUG    : JSON contains circular dependency. Discarded 2 objects:
{
    "id": "water_clean",
    "copy-from": "water",
    "type": "COMESTIBLE",
    "name": "clean water",
    "name_plural": "clean water",
    "description": "Fresh, clean water.  Truly the best thing to quench your thirst.",
    "color": "light_cyan"
  },{
    "id": "water_mineral",
    "copy-from": "water",
    "type": "COMESTIBLE",
    "name": "mineral water",
    "name_plural": "mineral water",
    "description": "Fancy mineral water, so fancy it makes you feel fancy just holding it.",
    "container": "bottle_plastic",
    "proportional": { "quench": 1.2 },
    "relative": { "fun": 1 }
  }

 
 FUNCTION : void DynamicDataLoader::load_deferred(DynamicDataLoader::deferred_json&)
 FILE     : src/init.cpp
 LINE     : 130
```

annnd

```
 DEBUG    : init_vehicles: tank tank specified invalid fuel in rv
 
 FUNCTION : static void vehicle_prototype::finalize()
 FILE     : src/veh_type.cpp
 LINE     : 911
```

```
 DEBUG    : init_vehicles: tank tank specified invalid fuel in lux_rv
 
 FUNCTION : static void vehicle_prototype::finalize()
 FILE     : src/veh_type.cpp
 LINE     : 911
```

```
 DEBUG    : Tried to get invalid ammunition: water
 
 FUNCTION : const T& string_id<T>::obj() const [with T = ammunition_type]
 FILE     : src/ammo.cpp
 LINE     : 45
```

```
 DEBUG    : Error: line 72:20: no such item type


      },
      "place_liquids": [
        { "liquid":
                   ^
                    "water", "x": [ 4, 15 ], "y": [ 14, 15 ], "repeat": 3 }
      ],
      "place_loot": [

 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 675
```
(keeps on going - some are probably because water doesn't exist because of the first error)

**To Reproduce**  
1. Create World
2. Start Game

**Expected behavior**  
No error

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 17.10
 - Game Version Linux 64 bit git sha 060387c3de
 - Graphics version [Tiles]
 - Mods loaded : `[
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "national_guard_camp",
  "more_locations",
  "Urban_Development",
  "deoxymod",
  "blazemod",
  "Tanks",
  "more_classes_scenarios",
  "StatsThroughSkills"
]`

**Additional context**

**Comment by ZhilkinSerg** [comment]
We had similar issue - see #24050. You have some files/folders missing.

**Comment by yarbelk** [comment]
Thanks: was probably the make install script as well (im writing a launcher in golang that works in linux as well; and was using the install script to move things around)

**Comment by ZhilkinSerg** [comment]
It seems `make install` is rarely used. It can possibly contain errors which prevent `data` folder from copying to install location. We would be grateful if someone would analyze the issue and provide PR with the fix.
