### ISSUE TITLE
Unable to refit reinforced clothing.

### ISSUE THREAD

**Issue by MarsM0nd** [CleverRaven/Cataclysm-DDA#25828]
**Describe the bug**  
If you have clothing that's reinforced, and then needs to be refitted, the game doesn't allow it.

**To Reproduce**  
1. Make a player that can successfully reinforce wearable gear.
2. Reinforce wearable gear
3. Mutate the tiny mutation/loose it if it was active during the reinforce process.
4. The clothing will have the oversized/undersized flag, and is especially encumbring.
5. Try to refit the clothing, be unable to.

**Expected behavior**  
Able to refit clothes even if they are reinforced, which used to mean you actually can't improve the clothing anymore. With the tiny mutation, that's not the case anymore.

**Comment by AMurkin** [comment]
Fixed by #25834? @Xhuis

**Comment by Petethegoat** [comment]
Can't repro on a recent build. Definitely fixed.
