### ISSUE TITLE
Moving items powered by batteries using advanced inventory takes up a ton of time.

### ISSUE THREAD

**Issue by jim-huynh** [CleverRaven/Cataclysm-DDA#25838]
**Describe the bug**  
Moving items using advanced inventory when the item has battery charges takes minutes of time for one item.  Moving one gunsmith repair kit (250 charges) took over 10 minutes for me.

Could it be related to this?
https://github.com/CleverRaven/Cataclysm-DDA/commit/fe7d40b98b187580692872c7d870eddddd73dba5

**To Reproduce**  
1. Player with an item in inventory with battery charges, for example flashlight or gunsmith repair kit
2. Move item using advanced inventory.
3. Hope that there are not monsters around wanting to eat you, or that your item did not have too many charges.

**Expected behavior**  
It shouldn't take 10+ minutes to put my gunsmith repair kit somewhere using advanced inventory.

**Versions and configuration(please complete the following information):**
Broken version: 0.c-32541-gcc9d671

Functioning version: 0.c-32482-gcc350c2

**Comment by cake-pie** [comment]
This affects anything with charges, not just battery charges -- so sewing kits, lighters, inhalers, etc.

**Comment by anonym** [comment]
I introduced this regression and am working on a fix.

**Comment by kevingranade** [comment]
This should have been fixed by #25843 and then hopefully #25852 did not re-introduce it.
Please comment if it is still occurring.
