### ISSUE TITLE
Coffee milk and dandelion wine can be used to maintain hydration better than water

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#25837]
**Describe the bug**  
One portion of coffee syrup and one portion of powdered milk takes a total of 75ml of space, but can be used to craft 250ml of coffee milk which has 40 hydration.

Dandelion wine has hydration of 10, and 250 ml of it fits 7 portions, equalling 70 hydration -- more than 50 from water.

This makes them more efficient than clean water for maintaining hydration.

**To Reproduce**
Stock up on powdered milk and coffee syrup. Enjoy carrying all your hydration needs in a small package, with an added bonus of some nutrition and not having to sleep. Easily achievable by mid-game.

With dandelion wine, it's much more difficult to abuse unless you have some combination of high strength, substance tolerance, addiction resistance and/or blood filter bionic.

**Expected behavior**  
No matter the drawbacks, I expect that no items can give me better hydration than clean water of the same volume. An exception is acceptable for (uncraftable) sports drink but that's it.

**Versions and configuration(please complete the following information):**
Consistent across Windows and Linux, curses and tiles, and various versions up to and including current (build 7972).

**Comment by Endovior** [comment]
The more I look at it, the wonkier that particular recipe for coffee milk looks. You're mixing two concentrated products together, and the extra volume just magically appears. That _particular_ combination really needs some water to make sense.

As for alcohol, the volume of alcohols vs water has been strange for a long time now... for the exact reason that you don't generally _want_ to drink alcohol on a level that'd replace water for your hydration needs. If you do, though, I'd note that Fruit Wine has the same quench value as Dandelion Wine, and that both of them are outliers as compared to the typically-low nutritional stats of alcohols.

**Comment by TechyBen** [comment]
IRL the "hydration" of sports drink is advertising bunk... but in lore/game, it's a "potion" stat booster. ;)

**Comment by Marrim** [comment]
Just remove powdered milk from the recipe and reduce the wines quench from 10 to 4-6 and it'll be fine.
Since milk can be crafted from powdered milk and water, this will ensure craftability with any combination of milk and coffee ingredients but it will no longer be possible to exclude the bulk of the water.

**Comment by str99** [comment]
ironically alcohol and coffee actually _de_hydrate you, caffeine and alcohol muck with your kidneys and cause the body to expel ridiculous amounts of water, dunno why they quench **ANY** thirst. but i guess the character doesnt need to piss or sh*t anyway, oh well.

**Comment by hughesdylan** [comment]
str99 is correct about the diuretic properties of alcohol, but it depends on the proof. Weak beer (1-2%) used to be consumed more than actual water for many generations as a way of preventing water-borne illnesses. Modern beer does dehydrate overall (3-4%), but only after some time has passed,

I think alcohol would work better by giving us hydration up front, but giving a second debuff called Diuretic that caused more loss of water overall. You can temporally hydrate yourself with alcohol after all, it just doesn't work for very long. Sort of like Caffeine and sleep currently.

**Comment by Rivet-the-Zombie** [comment]
I can verify that it's possible to live on coffee and vodka for extended periods of time without becoming dehydrated.

**Comment by str99** [comment]
> I think alcohol would work better by giving us hydration up front, but giving a second debuff called Diuretic that caused more loss of water overall. You can temporally hydrate yourself with alcohol after all, it just doesn't work for very long. Sort of like Caffeine and sleep currently.

I like this idea, should be a suggested feature :)

**Comment by Reclusive-reptile** [comment]
Serving size for most wines is about 150ml, so nerfing wine charges to 2 per 250ml would fix the quench problem.

**Comment by paulenka-aleh** [comment]
I had quite an extended period in my life, about 3 years when I was drinking 6-12 cups of green tea a day (at work, at lunch, at home in the evening). Besides that I didn't drink anything else, at least not regularely.

I didn't die in process due to dehydration even though tea is known to have similar properties to coffee. :)

I did feel a bit better though when I switch to plain water.

Seeing one day my survivor being not able to get any quench from tea & coffee would be quite disapponting so I suggest to research how diuretics work. Quick lookup over the internet is full of shouts that coffee won't dehydrate you unless you're taking too way much and it's too way strong.
