### ISSUE TITLE
Tab switching as tab and shift-tab optional

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#25839]
**Is your feature request related to a problem? Please describe.**  
Like many I find the change quite hard to adjust to and less intuitive, as someone with poor joints in hands/wrists I do not wish to give myself extra RSI pain for consistency's sake and have more wrist movement for no reason.

< and > being right next to arrow keys just make more mechanical sense to myself and others for navigation than having to use the other side of the keyboard because programmers are familiar with doing things a certain way.

**Describe the solution you'd like**  
Option to swap tab/shift tab with < and >

**Describe alternatives you've considered**  
Revert the change entirely, but I'm doubtful that this would happen.

**Additional context**  
I'm not sure what else to say

**Comment by ZhilkinSerg** [comment]
What's the issue? You already can redefine keybindings. Either edit `keybindings.json` or press `?` and edit global keybindings to whatever keys you want (and your system supports).

**Comment by Leland** [comment]
Closing per above, @dissociativity if you have issues with the process, please either ping me here to reopen, or seek support on the official forums https://discourse.cataclysmdda.org/ 😄
