### ISSUE TITLE
Vehicles racked perpendicular to their carrier vehicle have their parts rotated incorrectly.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#25832]
**Describe the bug**  
Vehicles racked perpendicular to their carrier vehicle have their parts rotated incorrectly.

**To Reproduce**  
1. Spawn a vehicle with a rack on the back or front (i.e. the electric SUV with rack)
2. Spawn a rackable vehicle (i.e. a bicycle).
3. Move the rackable vehicle adjacent to the rack, and activate the rack to load the vehicle.

The parts of the racked vehicle are drawn perpendicular to their normal orientation.

**Expected behavior**  
The parts of the racked vehicle face in the direction the racked vehicle faces.

**Screenshots**  
```-#-```
```|#|```

**Versions and configuration(please complete the following information):**
 - OS: All
 - Game Version since 2e596eff46431c3e1a203d6116e2468dfe83be2b
 - Graphics version Both
 - Mods loaded dda

**Comment by CoroNaut** [comment]
I would like to be able to choose which rotation to use but have no idea how to make it easy and concise without popping up another menu or something for it.

**Comment by mlangsdorf** [comment]
The carried vehicle stores its original heading (more or less, skew makes this complicated) in the same structure that stores its name and mount point data. You can choose which rotation to use by aligning the vehicle with carrier in the appropriate direction before racking it.
