### ISSUE TITLE
Skin Blisters From Intense Heat For No Reason

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#25847]
**Describe the bug**  
When I take off my armor I get blisters that quickly damage me and could kill me within a few minutes. 

**To Reproduce**  
Upload save
Take off armor
Blisters all over body

**Expected behavior**  
Take off armor, no blisters.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version [from the main menu, e.g. 0.C-32494-g2e596ef]
 - Graphics version Tiles
- Mods loaded [Filthy Clothes, NPC traits, More Buildings, PK rebalanced]

**Additional context**  
[Grayland-current.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2420070/Grayland-current.zip)

**Comment by Zireael07** [comment]
What is the temperature? Are you irradiated?

**Comment by woutershep** [comment]
"Year 3, Winter, day 9 8:32:06 PM | field | 'Very Light Sensitive' mutation turned into 'Troglobite'"

**Comment by woutershep** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/player.cpp#L1129-L1133
Seems to atleast explain why body armor is involved. As to why it happens i don't know though, the temperature in the save file looks normal enough to me.

**Comment by alanbrady** [comment]
I haven't played with the save or anything but looking at player.cpp:1129, it's possible to trigger heat blisters as low as 111F, that doesn't seem right to me.  I have never suffered a heat blister and I used to live in a climate where in the summer time 115F+ is expected.

**Comment by Tatterdemalian** [comment]
Yeah, seems someone forgot that the human body can thermoregulate. Not that there is anything but kludges in the code for an actual heat transfer model, but this setting is like making body parts start taking heat/cold damage whenever they aren't at exactly 0 comfort.

**Comment by Siyalatas** [comment]
This is most likely an issue with the PK's rebalancing mod. It has a negative "heat" property in the armor value of certain mutations, which makes you cook at room temperature. I have deleted it from the Slimy mutation so far (since it affected me), but I didn't even bother to look at other mutations that might have it. Now that you mentioned this, I took a closer look and it seems like there's plenty of mutations with this value that I'll have to fix.

For what it's worth, the regular PK is very outdated and buggy, and I'm trying what I can to fix stuff in my own fork. I'd appreciate any issue postings.

**Comment by Orange01gaming** [comment]
I've been using @dissociativity version of the PK mod that I downloaded from 9/24. I have a ton of mutations and I bet a couple of them are altered by PK's mod like @Siyalatas suggested.

**Comment by Orange01gaming** [comment]
> What is the temperature? Are you irradiated?
I've tested outside and inside a lab in early spring and both give me blisters.  I am not irradiated currently (Occasionally I get one or two points in irradiated due to food and enemies from PK but I keep it pretty low).

**Comment by tyrael93** [comment]
Oh so THAT was what happened with me last time. Had the same bug.

**Comment by nexusmrsep** [comment]
After a discussion on Discord we came to a conclusion that PK mod introduced negative fire armor values, probably to achieve extra fire damage. This however does not happen, it is not optimal implementation, and in effect messes up calculation of blisters.
Negative fire armor should be removed from PK mod. If fire (or any other damage type) susceptibility is a desired feature it should be implemented via other way that setting negative values to armor.

**Comment by Orange01gaming** [comment]
> After a discussion on Discord we came to a conclusion that PK mod introduced negative fire armor values, probably to achieve extra fire damage. This however does not happen, it is not optimal implementation, and in effect messes up calculation of blisters.
> Negative fire armor should be removed from PK mod. If fire (or any other damage type) susceptibility is a desired feature it should be implemented via other way that setting negative values to armor.

Im not sure that I follow. Would that cause me to get blisters when naked?

**Comment by nexusmrsep** [comment]
If you had mutation that gave you negative fire armor in some situations calculation would be like: 0 blisters - (-5 fire armor) = +5 blisters. It expected positive or zero fire armor values and goes wild with negative.

**Comment by kevingranade** [comment]
It sounds like we should floor effective warmth at 0 to prevent this underflow error.

**Comment by nexusmrsep** [comment]
> It sounds like we should floor effective warmth at 0 to prevent this underflow error.

No problem, I'll do it, but the problem is mainly on PK's mod's side.

**Comment by Orange01gaming** [comment]
Got naked in the latest experimental, and I didn't have blisters. Yay!
