### ISSUE TITLE
Debug message: too much ammo for beagle mini-tank

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#25849]
**Describe the bug**  
 DEBUG    : Generated too much ammo (3000) for Beagle Mini-Tank UGV in mattack::rifle
 
 FUNCTION : void mattack::rifle(monster*, Creature*)
 FILE     : src/monattack.cpp
 LINE     : 2820

**To Reproduce**  
presumably spawn/ find one?

**Expected behavior**  
no debug message

**Versions and configuration(please complete the following information):**
windows 10
tiles
0.c-32482

**Additional context**  
just started a new escape the lab and got this... there was a recent PR to increase ammo in response to loss of unlimited ammo weapons.

**Comment by Muffindrake** [comment]
![1537987329](https://user-images.githubusercontent.com/19580030/46103603-86482200-c1d1-11e8-8da7-f0468abcf17d.png)
![1537987454](https://user-images.githubusercontent.com/19580030/46103618-8c3e0300-c1d1-11e8-9eea-1710aa47024e.png)

**Comment by SunshineDistillery** [comment]
The code says it should have 100/2000 but the json lists 200/3000.  Idk which is the intended amount.

**Comment by cake-pie** [comment]
Resolved by #25853
