### ISSUE TITLE
lasagne does not fall under lactose intolerance

### ISSUE THREAD

**Issue by TheVeon** [CleverRaven/Cataclysm-DDA#25846]
**Describe the bug**  
As a character with lactose intolerance burritos, pizza etc are off-limit due to cheese content but lasagne is not

**To Reproduce**  
1. Pick lactose intolerance
2. Eat lasagna

**Expected behavior**  
Lasagna should fall under lactose intolerance because non-vegan lasagne typically has grated cheese on top. Furthermore it commonly includes a cheese sauce in between the layers.

**Versions and configuration(please complete the following information):**
0.C-32545-gc2d6772

**Comment by TheVeon** [comment]
That makes sense but a core component of real life lasagne is cheese and/or bechamel sauce, both of which are or contain dairy. I can understand a survivor making due with what he or she has but finding a box of lasagne in a grocery store you'd expect it to have cheese.

**Comment by Leland** [comment]
Closing, but anyone should feel free to add dairy in a PR.
