### ISSUE TITLE
Washing something filthy you're wearing causes error, nukes morale bonuses

### ISSUE THREAD

**Issue by alanbrady** [CleverRaven/Cataclysm-DDA#25857]
**Describe the bug**  
If you wash a filthy clothing item while having worn it for some time, you get an error message after washing it and walking away a few steps.  Your morale bonuses get nuked, but the item does get washed successfully.

**To Reproduce**  
1. Wear filthy clothing item long enough to get morale debuff, potentially with other positive/negative debuffs.
2. Use washboard and detergent to wash said clothing item
3. Walk a few steps
4. Get error message, check morale bonuses

**Screenshots**  
![screenshot from 2018-09-26 17-32-48](https://user-images.githubusercontent.com/60370/46116816-b207df80-c1b2-11e8-9eff-aff43b9782fb.png)

**Versions and configuration(please complete the following information):**
- Linux, tiles, commit cc9d67185d

**Comment by fungusakafungus** [comment]
I've seen it happening here: https://youtu.be/kKGRhyk8DP0

Will post exact position later.
