### ISSUE TITLE
German shepherd is too big

### ISSUE THREAD

**Issue by SaltGin** [CleverRaven/Cataclysm-DDA#25858]
**Describe the bug**  
German shepherd has a weight of 180lbs, it's probably heavy as a 6 feet man. and cannot be put into a pet carrier. 

**To Reproduce**  
1. Spawn a german shepherd
2. kill it
3. the corpse weighs about 180lbs

(And I failed to put it into pet carrier)

**Expected behavior**  
An adult german shepherd should have weight 30 to 40kg (66.14 pounds - 88.18 pounds).

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version [0.C-32545-gc2d6772]
 - Graphics version [Terminal]
 - Mods loaded  [
  "dda",
  "Experimental-Z-Level",
  "More_Survival_Tools",
  "Urban_Development",
  "bio_mod",
  "boats",
  "deoxymod",
  "ew_pack",
  "filthy_morale",
  "makeshift",
  "more_classes_scenarios",
  "more_locations",
  "mutant_npcs",
  "national_guard_camp",
  "npc_traits",
  "realguns"
   ]

**Comment by nexusmrsep** [comment]
Duplicate. Size, Volume and Weight granulation PR is under development. A bit of patience please, and every monster will be more susceptible to balancing.

**Comment by Night-Pryanik** [comment]
I believe this was fixed some time ago, as for now it's only 35 kg.
![изображение](https://user-images.githubusercontent.com/11132525/56187378-6bd17b00-6033-11e9-8805-e56a7b519dcc.png)
