### ISSUE TITLE
show/hide removed all crafting items and they won't come back

### ISSUE THREAD

**Issue by Binary-2** [CleverRaven/Cataclysm-DDA#25869]
Game version:

0.C-32555-gfbab919

Operating system:

Windows 10

### Expected behavior

Remove an item in the list for awhile and let the player bring it up through another menu or something of the sort.

### Actual behavior

Removes item forever

### Steps to reproduce the behavior

Hold [s] in the crafting menu.

**Comment by Kelenius** [comment]
Do they show up if you search for `h:yes`?

**Comment by Binary-2** [comment]
I'm not sure, I'll test it soon

**Comment by AMurkin** [comment]
So this is intended behavior. Can be closed now.
