### ISSUE TITLE
Launch issue

### ISSUE THREAD

**Issue by chancexr** [CleverRaven/Cataclysm-DDA#25876]
Game version:

Operating system:android

Tiles or curses:

Mods active:

**Comment by chancexr** [comment]
When i launch the game the z pops up then goes to black screen then i tap the screen and then main menu shows . It makes you think the game crashed

**Comment by AMurkin** [comment]
In #24674 stated:
> No Android-specific welcome screen. In my original port (https://github.com/a1studmuffin/Cataclysm-DDA-Android) I had a welcome screen explaining the Android touch controls. I've removed this to minimize C++ changes, but we may want to add something like this back in.

**Comment by chancexr** [comment]
@AMurkin is https://github.com/a1studmuffin/Cataclysm-DDA-Android were i need to report for android version

**Comment by AMurkin** [comment]
At this point i think our repository are good for this issue. But i recommend you to edit OP. It's empty now.

**Comment by chancexr** [comment]
What is edit op

**Comment by ZhilkinSerg** [comment]
> What is edit op

OP is Original Post (which is your first message). It should contain detailed information about issue you encountered. You can look into other issues - for example, #25875.
