### ISSUE TITLE
5.56 NATO M855A1 is not 5.56mm 

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#25879]
**Describe the bug**  
5.56 NATO M855A1 is not 5.56mm, it's 223 for some reason.  

**To Reproduce**  
1. Start/load a game.
2. Wish for/find some 5.56 NATO M855A1 rounds
3. Inspect said ammo
4. Scratch head

**Expected behavior**  
Ammo to be the correct size especially when the size is part of the name?

**Screenshots**  
![556is223](https://user-images.githubusercontent.com/15700895/46186036-35542e80-c2a2-11e8-96e3-5291e437beed.PNG)

**Additional context**  
Probably just a tyop in the json file.  Can't really complain since my survivor is currently using it as .223 ammo but it's weird and definitely not correct.  It's an easy fix but I won't be able to do it until at least saturday.

**Comment by Marrim** [comment]
5.56 and .223 are different rounds of the same caliber.

**Comment by Theundyingcode** [comment]
Well, today I learned whoever created the naming scheme for ammo deserves to receive some "excited" ones.
