### ISSUE TITLE
Nonsensical Faulty Biotics Effects While Under Anesthesia 

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#25872]
**Describe the bug**  
While knocked out due to an autodoc CMB operation, faulty biotics continued to report effects even when nonsensical.

**To Reproduce**  
1. Start a lab escape with a faulty cyborg.
2. Attempt to remove faulty biotics with an autodoc.
3. Stare in amazement at the messages you receive. 

**Expected behavior**  
Shouldn't feel or otherwise notice anything while knocked out.  Possible exception to give player a notification when faulty biotics cause actual damage.

**Screenshots**  
![questionable](https://user-images.githubusercontent.com/15700895/46161718-e7144080-c24b-11e8-95ca-c972c285f85d.PNG)

**Versions and configuration(please complete the following information):**
 - OS: windows 10
 - Game Version:
 - Graphics version: Tiles
 - Mods loaded: a bunch but Bright Lights, Biotic Systems and, Safe Autodoc are the only ones that possibly matter

**Additional context**  
My newest tactic for lab escape was to be a failed cyborg and use the lab's autodocs to remove the faulty biotics

**Comment by SwagNaut** [comment]
I've had a survivor on meth pull out a tooth while under anestesia.
![unter nakose einen zahn gezogen](https://user-images.githubusercontent.com/33957658/46572746-5811d180-c98b-11e8-927e-6dc2ed46e664.png)
This seems like an issue that affects most things happening while under anestesia.
