### ISSUE TITLE
Sleep deprivation mod: sleep debt stays until save reload

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#25905]
**Describe the bug**  
I cannot seem to get my sleep debt to go below 3, yet when I save and reload it magically goes away and greets me with a message telling me I've slept well

**To Reproduce**  
1: play with sleep deprivation mod in balance section of main game
2: let a few days pass, perhaps don't get a perfect night's sleep the first night or two
3: find a comfy base, build a bed, find a pillow and blanket even
4: still have sleep debt of 3 until saving and loading game

**Expected behavior**  
Sleep debt be restored by sleeping comfortably or sleeping for longer uncomfortably

**Versions and configuration(please complete the following information):**
 - OS: Windows 8.1
 - Game Version: unknown, compiled today as of PR (#25819) add tiny micro motor
 - Graphics version: Tiles
 - Mods loaded: Sleep deprivation, PK Rebalancing

**Additional context**  
Not much to say, seems that the mod acts as if it's supposed to when the game is loaded from a save game, so I'm imagining it's not refreshing properly when I sleep

**Comment by G3Kappa** [comment]
I'll look into it right now.

It might be possible that something got broken during the rebase, or that I accidentally overlooked something during my tests.

**Comment by G3Kappa** [comment]
Opened #25908

**Comment by G3Kappa** [comment]
@dissociativity Could you please check if the reported problems are gone when you have the time?

**Comment by Leland** [comment]
Closing per the PR, can reopen if still around.
