### ISSUE TITLE
Knocked Down While Attempting to Sleep

### ISSUE THREAD

**Issue by sigmareaver** [CleverRaven/Cataclysm-DDA#25909]
**Describe the bug**  
During meth withdrawal, the player will be "knocked down", even while attempting to sleep.

**To Reproduce**  
1. Make a tweaker, really bad day scenario, etc.
2. Wait until withdrawal effects kick in.
3. Attempt to sleep.

**Expected behavior**  
One shouldn't be "knocked down" while attempting to sleep, but the immobility effect can remain, perhaps in the form of an intense dizziness. A better message might be something along the lines of "the world is spinning around you."

**Versions and configuration(please complete the following information):**
 - OS: Win 7 Home Premium SP1 x64
 - Game Build: 7983 x64
 - Graphics Version: Tiles, MSX++Zaraga
 - Mods Loaded: DDA, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Bionics Systems Mod, DeadLeaves' Fictional Guns, Extended Realistic Guns, Medieval and Historical Content, Modular Turrets, Salvaged Robots, Cataclysm++, NPC traits, MXotto+ Cosmetics p10, Mining Mod, Mutant NPCs, More Locations, Fuji's More Buildings, More City Locations, Oa's Additional Buildings mod, Boats, Folding Parts pack, Vehicle Additions Pack, Tanks and Other Vehicles, Arcana and Magic Items, EXTENDED_BUILDINGS, StatsThroughSkills

**Additional context**  
P.S. Sorry if this is duplicate, but I didn't find this issue when I searched.

**Comment by Tatterdemalian** [comment]
Just because there's a bed in the tile doesn't mean you can't fall out of it, especially when having DT seizures.

**Comment by sigmareaver** [comment]
In that case, shouldn't you be moved off the bed tile?

**Comment by Tatterdemalian** [comment]
I'm pretty sure they do already, one of my characters contracted tetanus and had (thankfully rare) issues with suddenly moving entire tiles, on top of falling to the ground. I'm just not so sure having a bed in a tile necessarily means there can be no floor in the same tile to fall upon.
