### ISSUE TITLE
injecting serum from adjacent tile makes flask disappear

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#25900]
**Describe the bug**  
injecting serum from adjacent tile while not having enough storage space for the container makes flask disappear

**To Reproduce**  
1. drop glass flash of serum to adjacent tile
2. make sure you can't store one more glass flask by picking some items
3. inject serum from adjacent tile
4. glass flask disappears!

**Expected behavior**  
4. glass flask should stay in the adjacent tile

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: windows 10
 - Game Version jenkins 7987
 - Graphics version tiles
 - Mods loaded 
[
  "dda",
  "filthy_morale",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "alt_map_key",
  "npc_traits",
  "Hairs",
  "mutant_npcs",
  "more_locations",
  "FujiStruct",
  "Experimental-Z-Level",
  "Urban_Development",
  "boats",
  "cars_to_wrecks",
  "deoxymod",
  "blazemod",
  "Tanks",
  "more_classes_scenarios",
  "RL_Classes",
  "manualbionicinstall",
  "safeautodoc",
  "speedydex",
  "StatsThroughKills"
]

**Comment by Night-Pryanik** [comment]
It doesn't matter if one has a free space in inventory or not. Glass flasks are lost if they were lying on the ground prior to injecting. I suppose that's because serums are consumed and not activated. Might be worth converting serums from comestibles to tools and require activating.

**Comment by Night-Pryanik** [comment]
Cannot confirm on latest experimental as of September 29, 2019. First, serums' container now is test tube, not a glass flask. Second, trying to inject test tube with a serum lying on the ground correctly gives you the test tube.
