### ISSUE TITLE
Mining upstairs does not create a downstairs on the upper floor

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#25910]
**Describe the bug**  
Mining upstairs does not create a downstairs on the upper floor, effectively creating a one-way exit from your current level
**To Reproduce**  
1. mine upstairs
2. ascend stairs
3. observe upper floor
4. cry as you are locked out of your basement with this one-way black hole

**Expected behavior**  
upper floor should have a downstairs in the same tile or the nearest one eligible to have downstairs

**Screenshots**  
https://cdn.discordapp.com/attachments/365907426270117888/496019347920388116/unknown.png

https://cdn.discordapp.com/attachments/252368751016542218/496024583099383812/unknown.png

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version jenkins 7995
 - Graphics version tiles
 - Mods loaded 
[
  "dda",
  "filthy_morale",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "alt_map_key",
  "npc_traits",
  "Hairs",
  "mutant_npcs",
  "more_locations",
  "FujiStruct",
  "Experimental-Z-Level",
  "Urban_Development",
  "boats",
  "cars_to_wrecks",
  "deoxymod",
  "blazemod",
  "Tanks",
  "more_classes_scenarios",
  "RL_Classes",
  "manualbionicinstall",
  "safeautodoc",
  "speedydex",
  "StatsThroughKills"
]

**Comment by Leland** [comment]
See sister issue #18452, "mining downstairs fails to generate matching upstairs"
