### ISSUE TITLE
Vehicle Tank Refill Error (Debug Error: Tried to reload zero or less charges)

### ISSUE THREAD

**Issue by vecagon** [CleverRaven/Cataclysm-DDA#25914]
**Summary**
Vehicle menu's refill function does not work.

**Steps to reproduce the behavior**
1. Make a player with frame, 2 60L tanks, tools for installing vehicle parts
2. Make a source of water, or generate gasoline lamps for gasoline.
3. Create a vehicle construction and install 1 60L tank
4. Use other 60L tank as storage for water or gasoline.
5. Enter the vehicle menu of the new vehicle and use the refill function to fill the installed tank with water or gasoline.
6. Either debug error: "Tried to reload with zero or less charges" appears or the game says "You refuel the Car's vehicle tank (60L)," the vehicle's tank is still empty, and the your storage for water or gasoline is untouched.

**Expected behavior**  
The refill function simply did not transfer the source of liquid to the vehicle's tank. However, other ways of refilling vehicle tanks do work, such as Unload item and Refill nearby vehicle functions.

**Screenshot of first encounter of the issue**
![cataclysm_ dark days ahead - 0 c-32708-gd1849ee 9_30_2018 12_38_04 pm](https://user-images.githubusercontent.com/43731938/46262914-0ebe0f80-c4bd-11e8-9fb5-f7e67f278b8c.png

**Build and OS**
 - OS: Windows 10
 - Game Version: [0.C-32708-gd1849ee (tiles)
 - Graphics version: Tiles
 - Mods loaded:  "dda",
  "no_npc_food",
  "novitamins",
  "filthy_morale",
  "npc_traits",
  "More_Survival_Tools",
  "more_locations",
  "No_Fungi",
  "No_Explosive_Zombies

**Additional context**  
I previously encountered this issue casually and could not fill my workshop's water tanks. However, I noticed the vehicle's tanks can be filled with liquid through the funnel option, and using the Unload option on a storage of any liquid then using the Refill nearby vehicle tank function. This isolated the vague issue from being unable to fill a vehicle tank to the specific issue that the vehicle menu's Refill function does not work.
Since I continuously update my game while playing the same world, I had to recreate this issue in a new world on change #7995 or 0.C-32708-gd1849ee (tiles). Again, I reproduced the same results with a world built on 0.C-32708-gd1849ee (tiles), or change #7995.

**Comment by alanbrady** [comment]
There does seem to be some issue here, will take a shot at it.

**Comment by vecagon** [comment]
I asked a random player on change #7979, and he/she does not have this problem with the Refill function. Perhaps the one or some of the changes between #7979 to 7995 have caused this issue?

**Comment by alanbrady** [comment]
Yup, there was an accidental regression in https://github.com/CleverRaven/Cataclysm-DDA/pull/25851, I've already got a fix for it.

**Comment by vecagon** [comment]
Great! When should I expect the fix? Btw, this is my first issue post of this game and of GitHub. Do I have the sole responsibility to close this issue post? And when should I close it?

**Comment by alanbrady** [comment]
It should be soon.  Once my fix is merged it will auto-close the issue.  So you're set!  Thanks for the report, much appreciated.
