### ISSUE TITLE
fats can be used indefinitely for frying sweetbread

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#25926]
**Describe the bug**  
tallow is used as a tool in sweetbread recipe, this allows indefinitely reusing of the same, stinky, rotten  piece of tallow as frying oil

**Expected behavior**  
tallow should be listed as component for frying recipes

**Screenshots**  
https://cdn.discordapp.com/attachments/252368751016542218/496345138537168905/unknown.png

**Additional context**  
Just a personal tought, reusing oil is fine, but reusing oil "indefinitely" IS NOT, the game can't track degradated oil, and i think this is a bug/oversight

**Comment by KorGgenT** [comment]
i do agree that the average person would throw out the gunk they used for frying, it's pretty gross

**Comment by bandti45** [comment]
A possible solution is to have it as both a component and a tool unless you should only need one tallow or charge of oil if it is reasonable that you would use that much in the recipe. Thus making it used but slower than one for one.

**Comment by kevingranade** [comment]
Options are either make blocks of tallow much smaller so it's reasonable to
consume one per recipe, or make a byproduct thing so the tallow gets
adulterated over time.
