### ISSUE TITLE
Modular Turret mod creating duplicate "electronics" entry in crafting menu

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#25944]
**Describe the bug**  
what title says, I have disabled mods one by one and narrowed it down to Modular Turret.

![image](https://user-images.githubusercontent.com/10649716/46327781-c0923480-c5c0-11e8-9dbc-05513e8832e1.png)

**Versions and configuration(please complete the following information):**
build 8000

**Comment by SunshineDistillery** [comment]
I had not noticed that. 
It looks like mods don't actually overwrite recipe groups, so it's adding a duplicate with the same name.
If there's no way to do that, I may have to move all the recipes from the 'robot' subgroup  to 'other'.
