### ISSUE TITLE
Vehicle mounted minireactors can no longer be loaded while they are installed.

### ISSUE THREAD

**Issue by Xion350** [CleverRaven/Cataclysm-DDA#25946]
**Describe the bug**  
Minireactors no longer accept Plutonium cells while installed and using the re**f**ill command in the Vehicle menu.  They can be uninstalled and refilled by hand, but not while on the vehicle.

**To Reproduce**  
1. Install an empty minireactor onto any vehicle
2. Press f
3. Minireactors are not valid targets to be refilled

**Expected behavior**  
Ideally also describe *why* you expect it to happen.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - 0.C-32785-ga2209cd
 - No mods loaded

![image](https://user-images.githubusercontent.com/13670135/46330612-65b90700-c5d9-11e8-869c-116c4a772b32.png)

**Comment by alanbrady** [comment]
Willing to bet I broke it.  I swear I tested minreactors.  Will fix.
