### ISSUE TITLE
Black screen on start

### ISSUE THREAD

**Issue by svenkeidel** [CleverRaven/Cataclysm-DDA#25953]
**Describe the bug**  
The game worked flawlessly before. But on the newest release I get a black screen when I launch the game. When I press keys nothing happens and there is no menu sound. There is also no console output. The issue first appeared around mid of September.

**To Reproduce**  
1. Start the game.
2. Black screen.

**Expected behavior**  
A playable game.

**Versions and configuration:**
 - OS: linux (nixos)
 - Window Manager: xmonad
 - Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/d1849eed529af07a276b061e2a93b6c8ff70e4ee
 - Graphics version: tiles
 - Compilation flags: `PREFIX=$(out) LUA=1 USE_HOME_DIR=1 LANGUAGES=all RELEASE=1 TILES=1 SOUND=1`
 - Library Versions: SDL2-2.0.8, SDL2_image-2.0.3, SDL2_ttf-2.0.14, SDL2_mixer-2.0.2, lua-5.2.4

**Comment by alanbrady** [comment]
arch linux, i3 WM, 93e49924e8, tiles, no problem here

**Comment by svenkeidel** [comment]
Ok, it works with the newest version of the game and the libraries.

**Comment by svenkeidel** [comment]
It turned out to be an error message which did not appear, because the error occurred right after the start before the first redraw of SDL.
