### ISSUE TITLE
Character templates retain the 6 starting points on loading

### ISSUE THREAD

**Issue by UncleBenis** [CleverRaven/Cataclysm-DDA#25956]
**Describe the bug**  
Loading a character template does not use up stat points during character creation.

**To Reproduce**  
Load in a character template.

**Expected behavior**  
The stat points are supposed to be at 0 after loading a template but they are at 6.

**Versions and configuration:**
 
 - OS: win7
 - Game Version: 0.C-32792-g93e4992
 - Graphics version: Tiles
 - Mods loaded: DDA

**Comment by OzoneH3** [comment]
Did you spend all points before saving the template?
Unspent points are now remembered when saving the template and restored on loading.

Please provide the template file.

**Comment by UncleBenis** [comment]
[Bad Day v3.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2437137/Bad.Day.v3.zip)
I noticed when switching between tabs in character creation the number of points switches between 5 and 6 for no reason.
