### ISSUE TITLE
DEBUG:spear_steel_npc is not a valid recipe on Character Creation

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#26037]
**Describe the bug**  
 DEBUG    : spear_steel_npc is not a valid recipe
 
 FUNCTION : void {anonymous}::recipe_group_data::check() const
 FILE     : src/recipe_groups.cpp
 LINE     : 54

**To Reproduce**  
Fresh install of PR 8007 with Loader added to folder. Created World using mod settings below 
and attempting to Create Character. Error appears when 'Recipe Groups' is being loaded when using Create menu.

**Expected behavior**  
Issue can be (I)gnored and does not return when creating another character in same session but game experiences slowdown when Sleeping or crafting. CTD happens once game freeze happens and .exe remains in system memory until PC restarts. (after force-quit with TaskManager) Memory error?

Error returns when game is Quit and restarted. Error text does not show if creating multiple characters in a single session.

**Screenshots**  

 **Versions and configuration(please complete the following information):**
If any additional information is needed, please request.

**Additional context**  
MOD LIST:
  "dda",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "crazy_cataclysm",
  "alt_map_key",
  "Mining_Mod",
  "boats",
  "deoxymod",
  "necromancy",
  "no_rivtech_guns",
  "no_olg_guns",
  "no_flaming_weapons",
  "no_medieval_items",
  "more_classes_scenarios",
  "manualbionicinstall",
  "sleepdeprivation",
  "StatsThroughSkills"

Savegame included.
[Crazy Test 2.0.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2443633/Crazy.Test.2.0.zip)

**Comment by evankimori** [comment]
Updating. Error appears when trying to load 'Recipe Groups' on creating/loading a character. Screenshot included.

![spear](https://user-images.githubusercontent.com/43046067/47372208-47659900-d6b7-11e8-9afa-a3b995e5f4b6.png)

**Comment by KingOctavious** [comment]
I just encountered this problem as well. After some trial and error, it seems that `no_medieval_items` is what's causing the problem.

**Comment by evankimori** [comment]
Issue seems to have been resolved in a past pull. Cannot locate exact changelog but error has not appeared since then.
