### ISSUE TITLE
DEBUG: warnings for type bio_chest_gun on Character Creation

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#26036]
**Describe the bug**  
DEBUG    : warnings for type bio_chest_gun:
there is no bionic with id bio_chest_gun
 
 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 1055

**To Reproduce**  
Fresh install of PR 8007 with Loader added to folder. Created World using mod settings below 
and attempting to Create Character. Error appears when 'Items' is being loaded when using Create menu.

**Expected behavior**  
Issue can be (I)gnored and does not return when creating another character but game experiences slowdown when Sleeping or crafting. CTD happens once game freeze happens and .exe remains in system memory until PC restarts. (after force-quit with TaskManager) Memory error?

Error returns when game is Quit and restarted. Error text does not show if creating multiple characters in a single session.

**Screenshots**  

**Versions and configuration(please complete the following information):**
If any additional information is needed, please request.

**Additional context**  
MOD LIST:
  "dda",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "crazy_cataclysm",
  "alt_map_key",
  "Mining_Mod",
  "boats",
  "deoxymod",
  "necromancy",
  "no_rivtech_guns",
  "no_olg_guns",
  "no_flaming_weapons",
  "no_medieval_items",
  "more_classes_scenarios",
  "manualbionicinstall",
  "sleepdeprivation",
  "StatsThroughSkills"

Savegame included.
[Crazy Test 2.0.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2443635/Crazy.Test.2.0.zip)

**Comment by Soyweiser** [comment]
Problem is due to crazy_cataclysm not having a bionic type with the bio_chest_gun. (it only has an item, and the fake gun item for the bionic).

**Comment by Theundyingcode** [comment]
It's not on character creation as title implies. I get this every time I load my game.

**Comment by Soyweiser** [comment]
It is caused by #25369 just a small forgotten bionic definition. Will fix it. (have already fixed it locally).
