### ISSUE TITLE
Sugary colas and drinks Kcal not matching real life equivalents

### ISSUE THREAD

**Issue by tyrael93** [CleverRaven/Cataclysm-DDA#26050]
New kcal nutrition change turned the stupid into overdrive for colas and junk food.

A coca cola (DDA variant) described as full of sugar to the brim gives around 20 Kcals for each can, which is between 1/5th to 1/7th of real life value. In a game that revolves around realism, I find this insulting.

I suggest either changing the description and saying that they are artificially sweetened or something, because this is giving me an aneurysm.

**Comment by tyrael93** [comment]
https://imgur.com/a/x8mgo1W

**Comment by TechyBen** [comment]
Sugar tax? It's a thing in the [now] Future.

**Comment by FulcrumA** [comment]
Almost all caloric and nutritional qualities are rough or wrong. The former especially as they're direct translation of arbitrary stomach-feeling value of the past. In reality many food items of mass similar to that of the items in game would have wildly different values. There's some projects regarding improvement of that but any work that happens, if at all, on that front - happens slowly.

**Comment by tyrael93** [comment]
>it's been fixed

We are not worthy.

WE ARE NOT WORTHY
