### ISSUE TITLE
Blackjack oak tree turns in to normal oak tree when harvested

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#26068]
Game version: Latest

### Expected behavior
Blackjack oak trees when harvested should turn in to their harvested variant without the bark
### Actual behavior
They turn in to normal oak trees when stripped of bark
### Steps to reproduce the behavior
Harvest any blackjack oak tree

**Comment by cake-pie** [comment]
Has been the case since added in #10083; perhaps @Rivet-the-Zombie can clarify?

**Comment by Rivet-the-Zombie** [comment]
At the time it was either that or turning it into a dead tree. Trees couldn't be harvested more than once back then.
