### ISSUE TITLE
Fermenting sauerkraut jar has less weight and volume than a sealed jar of sauerkraut.

### ISSUE THREAD

**Issue by pontifexminimus2** [CleverRaven/Cataclysm-DDA#26071]
**Describe the bug**  
Fermenting sauerkraut weights 50 gram. The finished product weights 1750 gram. Also, the glass jar apparently loses half its volume while fermenting

**To Reproduce**  
1. Make some sauerkraut in a glass jar.
2. Ferment it two days long.
3. Watch in awe as it suddenly weights 35 times more than before. You have performed culinary witchcraft and the mutants in the forests will worship and fear your sauerkraut.

**Expected behavior**  
That the fermenting and finished sauerkraut have a very similar weight and volume.

**Screenshots**  
https://puu.sh/BG58I/dee7bf9d97.png
https://puu.sh/BG58v/37b95de471.png

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version [from the main menu, e.g. 0.C-32990-g2d18192
 - Graphics version Terminal

**Comment by SwagNaut** [comment]
I'm currently trying to fix this. It's not that difficult.
A fully fermented jar should be a little heavier than an opened one, but not by 800 grams.
I'm not changing that though, because I'm new and I don't know if you should make many changes at once.

**Comment by SwagNaut** [comment]
Fixed by #26074
