### ISSUE TITLE
Construction is unfeasible

### ISSUE THREAD

**Issue by MarcusAseth** [CleverRaven/Cataclysm-DDA#26076]
Problem:

I've attempted to build a "base" in the game (really just a house), here's an image of how far I got with it https://i.imgur.com/mNw0CaW.jpg

148 reinforced concrete wall, of which the first stage (rebar caging) is visible and complete.
447 concrete roof tiles for the interior (to do).

I did the math, to complete the base the materials required are the following:
148 walls (rebar caging excluded) = (1776 concrete, 1184 water, 3552 two by four)
447 roof  = (3576 rebars, 5364 two by four, 1788 pipes, 1788 concrete, 1788 water)

The main obstacle here is Concrete, the resources needed to make cement plus the other resources needed for 1 unit of concrete sum up to these:
 1 Concrete = (50 limestone, 75 sand, 20 pebble)

Therefore to complete the house in that image, it would require:
Total = 178.200 limestone, 267.300 sand, 71.200 pebbles, 2972 water, 8916 two by four, 1788 pipes, 3576 rebars

Now, I've traveled along a river for a long time, only got 500 sand.
The gunstore with the biggest ammount of sand bags in the shooting range, yelds around 1200 sand.
This means I would have to hit 267 gunstore in order to complete my house (and also luck out and always get the one with the big shooting range). This is just unreasonable and need rebalancing.

Solutions:
I have none. I'm just pointing out a big problem, and hopefully someone will come around to improve the situation, either adding tons of cement in the game, or cutting on the resources requirements.

**Comment by Maddremor** [comment]
That looks more like a large concrete bunker to me. Should it really be reasonable to build that from scratch?

From a strategic standpoint both the roof and inner walls could be from a cheaper material, and the vehicle bay could be downsized or put externally.

**Comment by MarcusAseth** [comment]
If we talk about "in real life", then there are deposits of construction materials, such as sand, that countain more than enough material to produce all the concrete you need for a house that size.
Therefore is not my projection being "too ambitious and unrealistic", it is just the unreasonable rarity of sand in game.

**Comment by Endovior** [comment]
I'd be inclined to suggest that places which would feasibly have construction supplies (hardware stores, construction sites, etc...) should probably have large amounts of those supplies, instead of a few random items. There would have been very large amounts of those supplies present at such locations before the cataclysm, and they would not have been priority targets for looting.

Also, natural deposits of sand and clay should be a lot more extensive than they are. Not necessarily to the level of being infinite like water from a pond, but certainly to the point where digging up _all_ the sand from a riverbank is _weeks_ of work for a lone survivor.

**Comment by CoroNaut** [comment]
That is a pretty large base, the base i built is only about 13x17 and thats more than enough for me even having 20k+ volume of stuff. (with a vehicle extending out the side of it for solar power and machines on the inner portion of the vehicle). But I debugged in metal walls/floor/doors and shredded the metal i thought was appropriate to construct it (because metal walls cant be built). As for the issue at hand, perhaps rivers/lakes could have beaches with lots more sand, but I think so much sand and other resources is unreasonable.

**Comment by LlubNek** [comment]
could add quarries and sand pits.
sand for construction isn't something you'd haul around in your pockets though, or even a pickup truck.  This needs a proper dump truck & excavator.

**Comment by Marrim** [comment]
Heh. My survivor solved that problem by deconstructing sandboxes in several children's parks and carting the sand back to the base.

**Comment by FulcrumA** [comment]
As per discord discussion, certainly there could be more sources fo sand in the game. Some rivers do have beaches - or even sand in some rivers themselves can be hauled out and used. Some spots in the plains which aren't grass or dirt but just sand also don't seem very farfetched and while not really fitting for manual production using querns etc - making a substitute using processed rocks (maybe could be simulated through the recycler in-game?) is a thing that happens IRL.

**Comment by tinukedaya** [comment]
If a construction site just have huge piles of sand it would be both reasonable and realistic. Plus occasional pallet of cement..

**Comment by TechyBen** [comment]
> That looks more like a large concrete bunker to me. Should it really be reasonable to build that from scratch?
I agree. Concerete is MASSIVELY labour and resource intensive, plus you are also using Rebar. LOL.

Building a wood base is rather possible. Log cabin, easy. Wooden house? A 6 month or few years... IRL these timescales carry well. If you want faster building, it can be made in game (season length/build time settings in menu) or it can be modded in (lower construction resources needed, or more resources drop).

Not a problem AFAIK, as you can reclaim and modify the innumerable existing places in game (houses, labs, police/fire stations etc).

**Comment by MarcusAseth** [comment]
I think there is too much stress about this "in real life". A game is supposed to be fun to play first and foremost. If building a house in 6 months was made it a way that stays constantly engaging and fun, then sure. If it is just a grinding chore, then is no batter than your average trash korean grinding mmorpg.
If minecraft required in real life time to build an horrible wood cottage, how many people would you think would be playing it? Probably only masochists. Therefore in my opinion the "in real life" argument carry no weight at all, to me seems more like the lazy excuse of whoever hate changes for wathever reason.

**Comment by kevingranade** [comment]
The realism argument does carry weight with me, the project owner, so you might want to adjust your strategy.

Having said that, my understanding is that building and pouring concrete forms doesn't take an unreasonable amount of time compared to building a wood frame house, and I agree that sand for concrete should be a lot more readily available.

Let's focus the issue on solutions :+1:

**Comment by MarcusAseth** [comment]
One solution might be better vehicle part to take care of he job. From a gameplay point of view makes sense if you have trouble trying to jump all the other material and go straight for the strongest end-game material, but on the other hand later on you should be able to build more advanced tools that makes it feasable. 
So I was thinking maybe just increasing sand and concrete is not the best solution because one might think to go straight for it, ignoring a lot of the construction that comes before (wood, metal).

There could be a "sand pump" kind of thing to be activeted where the vehicle is next to a river, to extract sand out of it over time, also and excavator arm component to be used on a sand terrain, concrete also require cement which require quicklime made from limestone, so a drilling vehicle part would be required for that.
I didn't tried making vehicles underground, but I am assuming it is possible. 
So a drilling head for making tunnels in combo with the scoop vehicle part that collects all the limestone.

Increasing sand and concrete would help, but I don't think that alone is the best solution.

**Comment by TechyBen** [comment]
So, without breaking early game/tech/progression, could a vehicular digger/cement mixer/etc be an option? (With small versions for player built: http://www.doosanequipment.eu/doosanequipment/products/mini-excavators/DX10Z.page )

This would add a multiplier to current sand/clay spots. So digging with a shovel would give the player the current count of sand/clay. Using a vehicular digger/excavator would give X times (like 5 or 10 times) the sand or clay.

That way it would not mess with the current balance, but give a tech/progression option for larger and quicker construction?

**Comment by Theundyingcode** [comment]
The most obvious solution to me is to add some kind of construction depot with piles of gravel, sand and other stuff.  This solves the problem of sourcing for large projects without having to mess around with other stores and is realistic to boot.

Otherwise adding sandbag walls and/or stores at military locations would also work.

**Comment by jeremyshannon** [comment]
Running some numbers,  the simple cement wall requires 400 (8x) cement, 200 sand, 160 pebbles, and 24 two by fours. It has a volume of 50L. 72% of that is wood -- the cement wall takes 24 two by fours, more lumber than the wall made entirely out of them! It weighs 114 lbs, and 63% of that weight is wood.
 A Wood wall for comparison is 30L, and 61lbs.

It also looks like the output of some of the recipes is super small. To make the 17lbs of cement for one square of wall takes 400 acetelyne, 2000 battery, or 2000 charcoal charges! IRL, that 17lb (9kg) sack is the smallest one at the hardware store.
 Google also tells me that a wall six feet high and four inches thick takes about 200lbs of concrete, whereas we're asking for 40lbs.

It looks like the wood requirements are way too high. If the wood is supposed to be for supporting the wall while it dries, perhaps the construction recipe should return the two-by-fours at the end? Or is the lumber just a basic reinforcer to reduce the amount of cement used? That might explain the low concrete requirements.

 From what I can gather, I think the amount of cement/concrete you get from the recipes right now is comically small. This looks like the kind of thing where you should be able to do a small batch or a friggin' huge batch in the same amount of time, sort of like charcoal making. Friggin' huge batches would require more realistic sand availability, of course.

**Comment by EvgenijM86** [comment]
It is possible to recycle concrete: http://www.concretebatchingplants.com/en/concrete-recycling-plants/concrete-recycling-plant

So one possible solution is to add concrete recycle vehicle (most likely without wheels) that can be found at appropriate location and can be turned on if connected to power supply. You just throw stones in it (or whatever is left when crushing concrete) and it gives you some sort of recycled concrete.

**Comment by kevingranade** [comment]
Left open for the sake of discussion, but ability to construct an arbitrary kind of structure isn't a pressing issue.  People are welcome to add more bulk sources of the various construction materials.  The most promising option IMO is extending the hole digging action to situationally produce large volumes of sand and gravel, for example sand banks along rivers.

Limestone could appear in a quarry special or in deposits more or less at random.
