### ISSUE TITLE
The Movespeed option for monsters is implemented as a global speed bonus.

### ISSUE THREAD

**Issue by Xion350** [CleverRaven/Cataclysm-DDA#26089]
Problem:

I was creating a world with zombies at 200% movespeed, trying to simulate zombies that are always at run speed.  I started noticing some problems once they got into melee.  They would get multiple attacks per move, sometimes instantly crippling my new characters.  I tested at 1000% speed and sure enough zombies were getting 8 or more attacks per turn.

![image](https://user-images.githubusercontent.com/13670135/46569753-2b27d500-c91f-11e8-98ba-2c42ad9e5e04.png)

For comparisons' sake the same character with a zombie at 100% speed.

![image](https://user-images.githubusercontent.com/13670135/46569810-e486aa80-c91f-11e8-859a-9d82818b8e14.png)

I haven't tried other enemies like Turrets but I can imagine them running through their entire ammo reserves in a single turn.

Solution:

The option should clearly state it is a bonus to all actions enemies can take.  Or it should ONLY be to moving.  A global speed option could be added alongside movespeed to let people have fast attacking zombies as well.

**Comment by Lorith** [comment]
The fun part: This also includes things like blobs and fungaloids reproducing.  They will reproduce so rapidly you can't keep up with killing them with automatic weapons or car-fu.  When I tested it even explosives couldn't outpace the reproduction at the higher speeds.
