### ISSUE TITLE
Hitting reload while wielding an item that can be reloaded circumvents the reload menu

### ISSUE THREAD

**Issue by TinkerWorX** [CleverRaven/Cataclysm-DDA#26108]
**Describe the bug**  
When wielding a weapon that can be reloaded, the reload menu will not appear when hitting `r` to reload. Instead it will simply attempt to reload the wielded weapon, removing the option to reload items in your inventory.

**To Reproduce**  
1. Make a player with two weapons that needs to be reloaded.
2. Hit `r` to reload, and observe the option to reload both weapons.
3. Wield one of the weapons.
4. Hit `r` to reload, and observe that it doesn't give you a reload menu, and instead only tries to reload the currently wielded weapon.

**Expected behavior**  
The reload menu should show up, so you can reload other weapons and no necessarily reload the one you're holding. The situation that made me make the issue was my character loading up a UPS weapon with batteries, which is an irreversible action, instead of giving me the option to reload my backup weapon in my backpack.

**Versions and configuration:**
 - OS: Windows 10
 - Game Version 0.C-32708-gd1849ee
 - Graphics version Tiles
 - Mods loaded N/A

I assume the system was made to make reloading faster, but it can be detrimental when having multiple weapons. Instead, the system could be changed to do a quick reload when you only have one reload option. So if you have a crossbow and only bolts, it'll keep doing quick reload, but if you have multiple reloadable items, it'll show the menu.

**Comment by rubenpd** [comment]
or add a new keybind for realoading wielded items separating it from the current reload

**Comment by SwagNaut** [comment]
I feel like this is indented behavior, since reloading shotguns or revolvers can be a needlesly long process otherwise.
Maybe it should show the reload menu when wielding weapons that can't be unloaded.
Perhaps the best solution would be to add the possibility to set a hotkey that always opens the reloading menu.

**Comment by KurzedMetal** [comment]
I'd rather want another key for that like rubenpd suggested.
I actually like fast reloading *weapons* by wielding. If I wanted to reload a second weapon or item, I'd wield that one.
I guess it's a bit confusing and unexpected the first time it happens, but it's actually useful in the long run or you'd have to do too many keypresses to reload stuff to max.
Besides, it would only auto-reload if it's not empty. I think it does ask what ammo you want to reload if the weapon is empty.

Now, in the case of the UPS or other items that can't be unloaded, I guess it would be nicer for players that it always ask for the ammo just case. But, please, don't bring this as default for actual weapons.

**Comment by Night-Pryanik** [comment]
This is no longer an issue after #28245?
