### ISSUE TITLE
using color template no_bright_background.json causes errors

### ISSUE THREAD

**Issue by colby-boucher** [CleverRaven/Cataclysm-DDA#26102]
Selecting the color template no_bright_background.json causes the following error report when loading the game:

 ```
DEBUG    : Error: data/mods//dda/../../json/monsters.json: line 15:13: invalid color name


    "material": [ "flesh" ],
    "symbol": "X",
    "color":
            ^
             "white",
    "aggression": 100,
    "morale": 100,

 
 FUNCTION : bool main_menu::opening_screen()
 FILE     : src/main_menu.cpp
 LINE     : 534
```

OS:  Manjaro 17.1 Hakolia
CDDA Version:  0.C-33023-gac2b6b3c17

I assume this has something to do with the change to the names of some colors I read about while searching through the forums about this.

**Comment by int-ua** [comment]
Still relevant on build 11388.

**Comment by actual-nh** [comment]
Should this be labeled as an Accessibility issue?
