### ISSUE TITLE
Mutation visibility and ugliness are ignored

### ISSUE THREAD

**Issue by Lorith** [CleverRaven/Cataclysm-DDA#26105]
**Describe the bug**  
Mutations have values for "visibility" and "ugliness" which are never used, merely stored.  Instead we have a hardcoded list of mutations (pretty, beautiful, beautiful2, beautiful3, ugly, deformed, deformed2, deformed3) that are checked to add fear.  The only one that reduces fear is ugly, all others increase fear.

**To Reproduce**  
1. Open src/npc.cpp
2. Search for `u.has_trait( trait_PRETTY`
3. Search for `ugliness` in whole project, find it doesn't get used anywhere

**Expected behavior**  
1: Ugly to not be positive
2: Pretty and beautiful to not be negative
3: Mutation visibility/ugliness to actually be used

**Comment by FulcrumA** [comment]
In general current qualities affecting NPC interaction - not only mutations/character traits but also stuff like trust or fear are of miniscule effect - aside from initial reaction of the NPC running away and possibly training, they have no bearing on the interactions.

**Comment by mlangsdorf** [comment]
So what should be happening is mutatation_data.ugliness should be adjusting social_modifiers, things like SAPIVORE should have a social_modifiers section to increase their intimidation_modifier, and then teh hardcoded checks in player::talk_skill() and player::intimidation() should drop out.

@Kelenius can you take a look at that during your mutations rework #26199?

**Comment by Kelenius** [comment]
Sure. No guarantees when that happens, though.

**Comment by mlangsdorf** [comment]
Fixed in #27434, at least for ugliness.  Still need to redo visibility.
