### ISSUE TITLE
Unable to quit game via ESC key.

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#26104]
**Describe the bug**  
At the main menu. Quitting game with ESC key no longer works. Pressing ESC brings up this menu
![image](https://user-images.githubusercontent.com/10649716/46576241-5db6e980-c982-11e8-8dc3-c7801e54cf68.png)
But pressing y, Y, or hitting enter on y, all just goes back to main menu without quitting.

The real way of quitting is by pressing q, Q, or hitting the x in the upper right corner.

Version 8023

**Comment by AMurkin** [comment]
Oh yeah, fixed by #26112.
