### ISSUE TITLE
Magazine-containing items show wrong encumbrance values in description

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#26109]
**Describe the bug**  
Items such as "magazine bandolier" or "chest rig" shows encumberance (current) and encumberance when full. But in fact last value doesnt correspond with description.

**To Reproduce**  
1. Chest rig (empty) shows: 2 | 2 (enc. curr | enc. when full)
2. Chest rig (w\4 mags) shows: 6 | 2

**Expected behavior**  
1. Chest rig (empty) shows: 2 | 6 (enc. curr | enc. when full)
2. Chest rig (w\4 mags) shows: 6 | 6

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-3318-gd692d74

**Comment by jbytheway** [comment]
I added the code to show encumbrance when full.  It only handles liquids.  Will look into this case.
