### ISSUE TITLE
Crash on examining vehicle with empty tank

### ISSUE THREAD

**Issue by AbbieFland** [CleverRaven/Cataclysm-DDA#26119]
**Describe the bug**  
When choosing "examine" from the examine menu on a vehicle with an empty tank, I instantly crash. It appears to be trying to check if the first item in the zero-entry list is a frozen liquid.

I suspect there are a couple places with similar checks that can also be triggered, although veh_interact:463 is where this one is.

**To Reproduce**  
1. Approach a car with an empty tank
2. Examine it

**Expected behavior**  
Successful examine

**Screenshots**  
(as is, just prior to crash):
![image](https://user-images.githubusercontent.com/34605836/46587768-2e29df00-ca5f-11e8-8c9d-6369275d54e6.png)

(after adding empty() check on veh_interact.cpp:463):
![image](https://user-images.githubusercontent.com/34605836/46587903-ffad0380-ca60-11e8-94ac-fe5c228f0dcf.png)

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu
 - Version: 0.C-33134-ge246447f92
 - Graphics version: Tiles
 - Mods loaded: Default

**Additional context**  
Debugger output:
```


/usr/include/c++/7/debug/list:340:
Error: attempt to access an element in an empty container.

Objects involved in the operation:
    sequence "this" @ 0x0x5555580d8948 {
      type = std::__debug::list<item, std::allocator<item> >;
    }

Thread 1 "cataclysm-tiles" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6a08f5d in __GI_abort () at abort.c:90
#2  0x00007ffff73d64e3 in __gnu_debug::_Error_formatter::_M_error() const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x000055555568051f in std::__debug::list<item, std::allocator<item> >::front (this=0x5555580d8948)
    at /usr/include/c++/7/debug/list:340
#4  0x000055555664f59b in veh_interact::cant_do (this=this@entry=0x7fffffffb880, mode=mode@entry=115 's')
    at src/veh_interact.cpp:463
#5  0x0000555556650213 in veh_interact::display_mode (this=this@entry=0x7fffffffb880) at src/veh_interact.cpp:2117
#6  0x000055555666efd4 in veh_interact::do_main_loop (this=this@entry=0x7fffffffb880) at src/veh_interact.cpp:296
#7  0x000055555666f5a2 in veh_interact::run (veh=..., x=x@entry=0, y=y@entry=0) at src/veh_interact.cpp:126
#8  0x00005555559abe7c in game::exam_vehicle (this=0x5555578b8790, veh=..., cx=cx@entry=0, cy=cy@entry=0)
    at src/game.cpp:5627
#9  0x000055555634db74 in interact_with_vehicle (veh=<optimized out>, veh@entry=0x555557ca7c10, pos=..., veh_root_part=84)
    at src/pickup.cpp:313
#10 0x000055555634e43b in Pickup::pick_up (pos=..., min=0) at src/pickup.cpp:634
#11 0x0000555555a0b840 in game::examine (this=this@entry=0x5555578b8790, examp=...) at src/game.cpp:6288
#12 0x0000555555a0bee6 in game::examine (this=this@entry=0x5555578b8790) at src/game.cpp:6205
#13 0x0000555555aa857f in game::handle_action (this=this@entry=0x5555578b8790) at src/handle_action.cpp:1408
#14 0x0000555555a08aba in game::do_turn (this=0x5555578b8790) at src/game.cpp:1573
#15 0x0000555555d85030 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:648
(gdb) frame 4
#4  0x000055555664f59b in veh_interact::cant_do (this=this@entry=0x7fffffffb880, mode=mode@entry=115 's')
    at src/veh_interact.cpp:463
463	            if( veh->parts[vp.part_index()].base.contents.front().made_of( LIQUID ) ) {
(gdb) 
```
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by alanbrady** [comment]
Bizarrely this seems to only happen in the DEBUG build.  I don't really understand why RELEASE doesn't also trigger this, but I do see why it's an issue.  Will fix.

**Comment by kevingranade** [comment]
My guess is in the release build it accesses the  element anyway since it
doesn't do the bounds check, but the undefined behavior of accessing a
random swath of memory happens to not cause a crash.

**Comment by alanbrady** [comment]
That makes sense.  Oof.  There were actually only two places I could find that had the issue, but I cleaned it up by abstracting that type of check into a function that also checks for empty first to help avoid this from happening in the future.
