### ISSUE TITLE
Survivor utility belt with holstered item is not considered as a `cutting_wire_standard` in crafting

### ISSUE THREAD

**Issue by Aivean** [CleverRaven/Cataclysm-DDA#26120]
When trying to craft an item that requires   `cutting_wire_standard`, like bike basket, or wire basket, I found that survivor utility belt doesn't satisfy aforementioned requirement. 
It appears that survivor utility belt only works if it doesn't have any item holstered.

**To Reproduce**  
1. Wish for `survivor utility belt` and `butcher knife`
1. Unlock all recipes
1. Open craft menu and search for `wire basket` or `bike basket`
1. Verify that `survivor utility belt` in the requirements list is green
1. Holster `butcher knife` in `survivor utility belt`
1. Open craft menu again and  search for `wire basket` or `bike basket`
1. Verify that `survivor utility belt` in the requirements list is now red

**Expected behavior**  
 `survivor utility belt`  should provide `cutting_wire_standard` capability regardless of whether it contains holstered item or not.

**Screenshots**  
![image](https://user-images.githubusercontent.com/2865203/46588257-18f88480-ca4e-11e8-8303-b90433ef4189.png)

![image](https://user-images.githubusercontent.com/2865203/46588265-42191500-ca4e-11e8-82ad-b66f0036fd26.png)

![image](https://user-images.githubusercontent.com/2865203/46588266-45ac9c00-ca4e-11e8-8af6-12542656a7c6.png)

**Versions and configuration(please complete the following information):**
 - MacOS
 - Game Version [from the main menu, e.g. 0.C-29938-g90f5268437]
![image](https://user-images.githubusercontent.com/2865203/46588273-78ef2b00-ca4e-11e8-9b2e-75302cee9947.png)
 - Graphics version: Tiles
 - Mods loaded:
![image](https://user-images.githubusercontent.com/2865203/46588276-915f4580-ca4e-11e8-8717-0148044f96c5.png)
![image](https://user-images.githubusercontent.com/2865203/46588279-991eea00-ca4e-11e8-8126-ec5f50f49836.png)
![image](https://user-images.githubusercontent.com/2865203/46588282-9f14cb00-ca4e-11e8-946f-fd78bd249295.png)

**Additional context**  
Seems that `cutting_wire_standard` is not a regular item quality, but rather something external, specified in `toolsets.json`. Probably the issue is in the logic that checks the requirements resolved via `toolsets.json`.

**Comment by TechyBen** [comment]
Also, the new mechanics means you have to get out the shovel to use if on a belt. :p 
But I guess that is as intended, where as this is a bug.

**Comment by cake-pie** [comment]
> Seems that cutting_wire_standard is not a regular item quality, but rather something external, specified in toolsets.json. Probably the issue is in the logic that checks the requirements resolved via toolsets.json.

Both `cutting_wire_standard` and `welding_standard` are correctly expanded into qualities and tools, as evidenced by first screenshot of crafting UI; no problem there.

The issue arises due to the check [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/79d9903e17b0ceb9e648f9e6d3fd73a599f3b7fe/src/visitable.cpp#L850) -- with a knife sheathed in it, the belt has [non-empty contents](https://github.com/CleverRaven/Cataclysm-DDA/blob/79d9903e17b0ceb9e648f9e6d3fd73a599f3b7fe/src/item.cpp#L5736) and becomes ineligible for use as a crafting component. (But we're using it as a *tool*.)

Working on a fix.

**Comment by rubenpd** [comment]
it's the folding wire basket that requires specific tools, instead of a tool quality?
