### ISSUE TITLE
Abort when examining vehicle

### ISSUE THREAD

**Issue by mark7** [CleverRaven/Cataclysm-DDA#26136]
**Describe the bug**  
Cataclysm aborts when attempting to examine a vehicle.  I've not investigated further yet.

Stack trace:

    Error: attempt to access an element in an empty container.

    Objects involved in the operation:
        sequence "this" @ 0x0x5555662815f8 {
          type = std::__debug::list<item, std::allocator<item> >;
        }

    Thread 1 "cataclysm-tiles" received signal SIGABRT, Aborted.
    __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
    51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) bt
    #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
    #1  0x00007ffff732d2f1 in __GI_abort () at abort.c:79
    #2  0x00007ffff76f177d in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #3  0x000055555664fbd6 in std::__debug::list<item, std::allocator<item> >::front (this=0x5555662815f8) at /usr/include/c++/8/bits/move.h:47
    #4  veh_interact::cant_do (this=this@entry=0x7fffffffa9e0, mode=mode@entry=115 's') at src/veh_interact.cpp:463
    #5  0x0000555556650acb in veh_interact::display_mode (this=this@entry=0x7fffffffa9e0) at /usr/include/c++/8/ext/new_allocator.h:86
    #6  0x000055555666f9a2 in veh_interact::do_main_loop (this=this@entry=0x7fffffffa9e0) at src/veh_interact.cpp:296
    #7  0x000055555666ff6f in veh_interact::run (veh=..., x=x@entry=0, y=y@entry=0) at src/veh_interact.cpp:126
    #8  0x00005555559b9111 in game::exam_vehicle (this=0x55555c1b9220, veh=..., cx=cx@entry=0, cy=cy@entry=0) at src/game.cpp:5627
    #9  0x00005555563441c1 in interact_with_vehicle (veh=<optimized out>, veh@entry=0x55556623fce0, pos=..., veh_root_part=45) at src/pickup.cpp:313
    #10 0x00005555563449f2 in Pickup::pick_up (pos=..., min=0) at src/vpart_position.h:43
    #11 0x0000555555a18e17 in game::examine (this=this@entry=0x55555c1b9220, examp=...) at src/game.cpp:6288
    #12 0x0000555555a194bb in game::examine (this=this@entry=0x55555c1b9220) at src/game.cpp:6205
    #13 0x0000555555ab220a in game::handle_action (this=this@entry=0x55555c1b9220) at src/handle_action.cpp:1408
    #14 0x0000555555a157bc in game::do_turn (this=0x55555c1b9220) at src/game.cpp:1573
    #15 0x0000555555d87e14 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:648
    (gdb) 

**To Reproduce**  
1. Examine vehicle one tile west of the character.

**Expected behavior**  
Cataclysm not crashing.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Debian Buster
 - Game Version 0.C-33119-gbd4b908efd.  Note that this is a private branch off hashref a36162e6579f463b7f61c4f3ef977daba774ccb8 and should be treated as on that version; the patches are not to game source and are irrelevant to the problem.
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs, Simplified Nutrition, Craftable Gun Pack, Safe Autodoc, Bright Nights, Deadleaves' Fictional Guns, Extended Realistic Guns, Icecoon's Arsenal, Makeshift Items Mod, Medieval and Historic Content, More Survival Tools, Mythological Replicas, Alternative Map Key, Mutant NPCs, NPC traits, More Locations, Fuji's More Buildings, Tall Buildings, Urban Development, Boats, Folding Parts pack, Vehicle Additions Pack, Tanks and Other Vehicles

**Additional context**  
Saved game attached.

[save.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/2459868/save.tar.gz)

**Comment by cake-pie** [comment]
Looks like #26119, fixed by #26122 -- try hashref fda7bb951d01b055d53a34bc4619fa1e0ff71398 or newer.

**Comment by mark7** [comment]
Yup, thanks.
