### ISSUE TITLE
Disappearing letters during worldgen

### ISSUE THREAD

**Issue by hbhollandlive** [CleverRaven/Cataclysm-DDA#26141]
**Describe the bug**  
As I was creating a new world, the letter 'e' disappeared from the world creation menu while I was selecting mods (those listed under Configuration below). Only white lowercase 'e's were affected, leaving blank spaces in the middle of words. I was able to finish creating my world, but when I exited the world creation menu all white lowercase 'e's in the main menu had been replaced with red capital 'B's. 

As it was only a slight inconvenience when it started, I basically ignored it until I returned to the main menu and saw the red 'B's, at which point I thought "Maybe I should report this." So I'm unsure which mod selection triggered the bug, but I remember it happened somewhere during the Building mods. Unfortunately, I haven't been able to reproduce it by selecting mods in the same order as before. 

**To Reproduce**  
Unsure. Picking the same mods in the same order didn't work, and neither did picking and removing a bunch of random mods really fast. 

**Expected behavior**  
Letters don't disappear or get replaced with other letters.

**Screenshots**  
Didn't screenshot it, but [it look d som thing lik  this] (or likB this on thB main mBnu).

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-33136-g79d9903
 - Graphics version: Tiles
 - Mods loaded: Bright Nights, Craftable Guns, Safe Autodoc, Makeshift Items, Medieval/Historic Content, More Survival Tools, DinoMod, Modular Turrets, Salvaged Robots, Crazy Cataclysm, possibly a few building mods

**Additional context**  
Not sure if related, but I think I got a "Failed to write options..." message that acted strangely in the same instance, but prior to the bug. I hit Spacebar to clear the message and the screen behind it turned black, and then the second time I hit Space, it closed and showed the main menu. (I set my options.json to read-only because file permission issues kept changing my settings, that part wasn't a bug.)

**Comment by Leland** [comment]
We'll leave this open for a while to see if anyone else has encountered something similar, but no screenshots or steps to reproduce does make it difficult!

Definitely take some screenshots and leave them here if you hit this again @hbhollandlive

**Comment by Night-Pryanik** [comment]
Closed as unconfirmed. Ping me or any other maintainer if this is still an issue.
