### ISSUE TITLE
Lag during inventory manipulation

### ISSUE THREAD

**Issue by Visette** [CleverRaven/Cataclysm-DDA#26147]
**Describe the bug**  
When manipulating players inventory there is consistient half second lag on all inputs, issue is present in:
- (I)nventory
- Multi(D)rop
- (E)at

Also while opening (E)at menu huge few seconds lag takes place. 

**To Reproduce**  
Try using any of those menus, I am not sure how to reproduce it or if its present only in my games.

**Expected behavior**  
I expect no lag on inputs.

**Versions and configuration(please complete the following information):**
 - OS: Win 7
 - Game Version: 0.C-33158-gd0fe67
 - Graphics version: Tiles
 - Mods loaded: Makeshift Items,  Alternative Map Key,  Boats, Folding Parts,  Vehicle Additions
,  Tanks and Other Vehicles,  Arcana and Magic Items, No Accid Zeds(modified to remove smokers aswell)  No Flaming Weapons,  StatsThroughSkills,  Simplified Nutrition,  Book Scanner,  DeadLeaves' Fictional Guns,  Expanded Archery,  Medieval and Historic Content,  More Survival Tools,  Mythological Replicas, 
 No Freeze,  Modular Turrets,  Manual Bionic Installation,  Safe Autodoc.

**Additional context**  ``
Savefile:
https://drive.google.com/open?id=1EDNORLBhTpk7BLXuVcEAL0JCroqf4RhR

**Comment by Myobu1** [comment]
Created an account just to chime in and say that I too am experiencing this problem. From what I've experienced, the lag isn't present on the creation of a new world. However, after an unknown period of time passes by when playing (exploring, doing what players do, etc) the lag will appear. The game will also take longer to load and seems to linger on the word 'Flags' before finally loading in.

There is also a recent Reddit [thread](https://www.reddit.com/r/cataclysmdda/comments/9lk6cc/cataclysm_slowing_down/) talking about this issue.

Unfortunately my save file was deleted a few days ago, so I can't offer one like the OP. Just wanted to let OP know he wasn't alone in this issue.

**Comment by Xion350** [comment]
This seems to happen on large worlds.  My main world is almost 1 GB in size and doing anything is a colossal pain.  I'm not sure if it's directly related to the world size, but as there are no current plans to introduce optimization for world save files this issue may not be fixed for a long time.

**Comment by Myobu1** [comment]
My world was only 50mb before this happened. Hardly what I would call large.

**Comment by overbo** [comment]
I'm also seeing this, and I'll echo that it spends some time loading flags.  129mb world, up to date experimentals on a mac, xcode is fully patched, brand new macbook pro with i7.

Like the reddit poster, I'm also seeing input lag when I am driving.  My experience is that it's especially bad when there's something going on that engages the 10ms animation delay, such as rain or snow.  Debugging weather to clear seems to improve the situation greatly.

**Comment by kevingranade** [comment]
Please re-test, a change that may have at least partially fixed this issue was just merged as #26272

**Comment by rubenpd** [comment]
Eat and inventory menu are now fine, multiDrop still has lags

**Comment by Trokinos** [comment]
About multidrop ( d or D ) being laggy (still observed in cataclysmdda-0.C-8059) 

It seems all the other interfaces like the (a) Use Item, the (i)nventory the (I) Compare Items and (E)ating (R)eading and etc.. are working good since a few experimental versions i tried.
It looks like the multidrop is the only one that is still very bad.

**Comment by Trokinos** [comment]
As i had disabled filthy cloth, i added "filthy_morale", to my save own mods.json .
Ingame i then made a washboard and added used the soap bars i had around to my inventory.
I was wearing 2 filthy clothes so i (a)ctivated the washboard and the wash menu appeared , and it was as you predicted, very very laggy (despite there were only 2 cloth items there) like the drop menu.

**Comment by jbytheway** [comment]
Thanks.  I'll have a go at fixing these.
