### ISSUE TITLE
Suggestions for reading stuff

### ISSUE THREAD

**Issue by RighteousBacon** [CleverRaven/Cataclysm-DDA#26151]
**Issue:** From my current understanding of the game, there isn't a way to train the speaking skill outside of skill books and NPCs.
**Solution:** Books should train speech skill, proportional to their morale bonus, as a higher bonus would suggest that it is better written, better articulated, more captivating, ect. A book specifically for training the speaking skill should still be better, but perhaps without the morale bonus and taking longer to read (due to the technical jargon).

**Issue:** Reading progress could be a lot cooler.
**Solution:** Have 2 separate progress bars for a book, one for your current read-through and a second for your memorization of the whole book. Here are some applications I can think of:
- Memorize crafting recipes.
- Tying in with the first issue, as memorization progresses the morale bonus and the speaking skill training rate decreases, encouraging you to seek out new text.
- Memorization of holy scriptures for meditation.
- Training NPCs without skill books.
- Do away with the chapter thing (_Pulp Novel (24)_), removing the need to constantly reissue the reading command. On a related note, see final issue below.
+Maybe memorization progress should decay over time, discouraging you from turning used books into fletching or firewood, but only to a certain point (say 75%), it should be easier the second time.

**Issue:** There should be a "Repeat last action" button, for things like sewing, moping, filling bottles, ect. Correct me if I'm wrong but it might be a complicated due to the wide range of differing activities available. No solution for this one.

**Comment by Leland** [comment]
For the third issue, also see old (closed) issues: #574, #7278, #12113, #22208, #23104.
