### ISSUE TITLE
Wireless component to vehicles, enabling camera surveilance around Base 

### ISSUE THREAD

**Issue by MarcusAseth** [CleverRaven/Cataclysm-DDA#26160]
**Problem**  
In game is not possible to monitor the surrounding of your base from within it, by accessing the camera feed from a terminal (or many) inside your base.
Is also not possible to remotely turn on courtyard lights from within the base.
And so on, basically every possible example that require to remotely operate vehicle components you don't see, from within your base.

**Solution**  
Would be cool to have a "wireless" connection component capable of linking 2 or more vehicles togheter, therefore you could have a 1x1 terminal/vehicle inside your base with camera controls on it, and that camera control would consider the 5 or more cameras around your base as part of the vehicle, therefore allowing you to check the perimeters of your base from within it.
This wireless control could also link a 1x1 control pannel inside your base to the multiple perimeter floodlights, so you can turn outside lights on and off from within your base, possibly from within the same "vehicle" tile controlling the cameras.

** Additional comment**
This might not look too relevant right now, but I'm assuming in the future the wander hordes thing will be improved, and so you might end up having a horde visiting your base and making a lot of noise outside of it. 
In that circumstance would be much better to take a look from your surveilance terminal from the safety of your base before deciding on a plan, rather than going open the door and end up face to face with two hulks and god knows what.

**Comment by mlangsdorf** [comment]
Can't you already do this with the existing drive by wire controls and a remote vehicle controller?

**Comment by MarcusAseth** [comment]
> Can't you already do this with the existing drive by wire controls and a remote vehicle controller?

I believe not, because you need a Camera control system to see what's going on, so it was said to me on the discord server by more knowledgeable players.

> demolish wall, then put board with security camera+wiring can work?

The "demolish wall" part is a problem because you're weakeaning your base by not having a reinforced concrete wall where it should be.

**Comment by rubenpd** [comment]
i don't think it can work wireless, due to reality bubble rules one part could be in it and the second part could not, and this could lead to some weird things happening

**Comment by Theundyingcode** [comment]
Logically you should also be able to have a wired system then.  This may actually be simpler to implement if you can steal the jumper cable code to make ethernet or other data cables that link electronic controls and cameras.
