### ISSUE TITLE
Player Should be able to open shutters somehow if pulleys are broken.

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#26171]
**Is your feature request related to a problem? Please describe.**  
https://discourse.cataclysmdda.org/t/is-it-possible-to-break-a-wall-with-a-halligan-bar/16936
This thread, the player with the halligan bar seems to have destroyed or lost the pulley somehow and is stuck in a storage unit

**Describe the solution you'd like**  
Player should be able to attempt to lift, making a lot of noise and taking a lot of time, or perhaps pry shutters upward, or even smash them.

**Describe alternatives you've considered** 
One or more of the above options.
**Additional context**  
It just doesn't seem to make sense that things operated by these easily destroyed pulleys are impossible to otherwise open, close or get around being trapped in, in some situations.

**Comment by Theundyingcode** [comment]
For a while now I have been thinking that garage/shutter doors should be added instead of using generic metal doors for immersion reasons but doing so could facilitate adding additional functionality such as a strength check against the doors weight/counter balance to manually open the door.
