### ISSUE TITLE
Canning glass jars gives water not clean water

### ISSUE THREAD

**Issue by FrozenSnowFox** [CleverRaven/Cataclysm-DDA#26173]
**Describe the bug** 
When canning Woods Soup into Glass Jars you get a byproduct of Normal Water.  According to the description of the Canning Pot the recipe should return Clean Water after canning an item.  Looking at the git code this issue affects other recipes using Glass Jars as well.

"Canning foods with it will require a lot of water, but you'll end up with clean water as a byproduct."

**To Reproduce**
Try to can Woods Soup with a Canning Pot and some Glass Jars.

**Expected behaviour**
As per the description of the Canning Pot canning Woods Soup with Glass Jars should return clean water.  If this is not intended then the description needs updating.

**Additional context**
Checking the code the Woods Soup recipe has the following.
"byproducts": [ [ "water", 10 ] ],
I'm not knowledgeable of the game code but looking at the components it should probably be this.
"byproducts": [ [ "water_clean", 10 ] ],

While looking at the git code I noticed all the recipes which return water return normal water.  I also noticed there's quite a lot of recipes that use glass jars but don't require a canning pot or the water requirement.  I'm not knowledgeable enough about this to say if that's intended behaviour or not.  Someone with knowledge of the process should probably check over all the recipes involving glass jars.

**Comment by FrozenSnowFox** [comment]
I didn't realise Kevin changed it afterwards.  Anyways nice work on the quick fix.

**Comment by kevingranade** [comment]
Sorry I missed the description.
