### ISSUE TITLE
Vacuum Sealer makes rotten things fresh 

### ISSUE THREAD

**Issue by EirenexTheDragon** [CleverRaven/Cataclysm-DDA#26186]
**Describe the bug**  
Using the recipee to make vacuum fruit slices and using rotten fruit as ingredient causes the end product to become a fresh nonrotten product that you can safely eat.

**To Reproduce**  
1. Obtain Vacuum sealer, ingredients for the vacuum products and the rotten fruit
2. craft Vacuum fruit slices
3. activate the vacuumed fruit slices to notice how it is fresh now.

**Expected behavior**  
It should come out as rotten. sucking the air out of things doesnt just removes it from being rotten  

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version O.C-33196-g90d0a9b  (close to most current version in short) 
 - Graphics version does not matter.
 - Mods loaded Statsthroughskills, manual bionic installation, safe autodoc, no fungal mon, boats, folding parts pack, vehicle additions pack, tanks and other vehicles, Fuji's more buildings. more locations, Mutant NPCs, Hair aka rainbow, npc traits, alternative map key, extended realistic guns, more survival tools, medieval and historic content, makeshift items mod, filthy clothing, disable npc needs 

**Additional context**  
This issue would probably affect the vacuum recipes of meat, veggy and fish aswell, but i only tested with rotten fruit.

**Comment by FulcrumA** [comment]
An old bug, already in a number of tickets. It's not even just making things that spoil that refreshes certain ingredients but for example, dehydrated meat is perfectly fine when made from rotten. I think it'd be fine if certain recipes wouldn't care about status of the ingredients, but certainly not all.

**Comment by EirenexTheDragon** [comment]
why not make it work like the canned food recipes? which has a plastic container that actually prevents spoiling? that would solve it and spit it out as rotten if its truly rotten

**Comment by alanbrady** [comment]
Hrm I'm pretty sure there's an easy fix.  

https://github.com/CleverRaven/Cataclysm-DDA/blob/1d576aeec3acc68c29be28278123f295d3949686/src/crafting.cpp#L722

Here we only set relative rot if it goes bad.  I *think* if that changed to `if( newit.is_food() ) {` it'll do the right thing.  I'm not 100% how that will work with items that don't have a spoil timer though, it might just break horribly or it might just work majestically.

**Comment by nexusmrsep** [comment]
>  I'm not 100% how that will work with items that don't have a spoil timer though, it might just break horribly or it might just work majestically.

For what I know it would result in some level of rot (or even complete rot), that would not move forward since the non-perishables still have the rot varibale to work with, but the rot 'tick' is prevented. I think its safe to do it that way.

**Comment by rubenpd** [comment]
tin cans and sealed glass jars of food/drinks has same problem, transforms rotten meat/whatever ingredient from rotten into 100%fresh

**Comment by lancewf** [comment]
With these two PRs #26554 and #26553, this bug should be fixed.

**Comment by DarkRainX** [comment]
#26554 is not yet merged, reopen?

**Comment by lancewf** [comment]
#26554 is merged now 💥
