### ISSUE TITLE
Delay after updating

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#26215]
There's a 3 second delay that i think it happens when a minute passes ingame, This starts to happen after i updated the game to latest build from the launcher as there are no similar issues before updating, 0.C-33303-g9b3eff3 (tiles), 8045

**Comment by ZhilkinSerg** [comment]
How's the performance on latest version?

**Comment by kevingranade** [comment]
Given the proximity to the map memory and backtrace issues that we know have been resolved, I'm going to guess this was related and close.
