### ISSUE TITLE
Stop supporting gcc 4.8

### ISSUE THREAD

**Issue by jbytheway** [CleverRaven/Cataclysm-DDA#26216]
**Problem**  
While working on #26148 I had to add two different workarounds for bugs in gcc 4.8's standard library (specifically: that `list::insert` and `list::splice` don't accept `const_iterator` arguments).  One of those required a `const_cast`.

**Describe the solution you'd like**  
gcc 4.9 [was released in 2014](https://www.gnu.org/software/gcc/releases.html).  Can we cease support for 4.8?  Does the project have a policy on how far back it maintains compiler support?

**Comment by mlangsdorf** [comment]
If we drop support for gcc-4.8, people won't be able to build C:DDA on default Red Hat Enterprise Linux 7 installations.

I don't think that's a good reason.

Ubuntu 14.04 LTS still uses gcc-4.8 and is supported through April 2019.  I don't know if we need to match Ubuntu's LTS policy, but I also think we don't need to support gcc versions that aren't in a current Ubuntu LTS. So even if we decide not to remove gcc-4.8 support now, we should deprecate it and plan to remove it in April 2019.

I also think only supporting 3 or 4 years of gcc is a valid policy. I think 5 years is the maximum reasonable number, but a lower number is acceptable.

**Comment by ZhilkinSerg** [comment]
We aim to support as much compilers as possible to cover multiple rather old systems.

**Comment by jbytheway** [comment]
Cool.  That makes sense.  I'll close this issue for now.

**Comment by jbytheway** [comment]
As of this month:
* Trusty is out of support and Xenial is the Ubuntu LTS, which [defaults to gcc 5.3](https://packages.ubuntu.com/xenial/g++).
* Debian stable is stretch, which [defaults to gcc 6.3](https://packages.debian.org/stretch/g++).
* I'm not sure what you mean by Fedora whatsit, but the oldest supported Fedora version is 28, which appears to be [using gcc 8](https://fedora.pkgs.org/28/fedora-x86_64/gcc-8.0.1-0.20.fc28.i686.rpm.html) (though I'm less certain about Fedora packaging).
* Mingw looks like it was [using gcc 7.3](https://github.com/msys2/msys2/wiki/Packages) as of July 2018.  Again, I'm not certain how mingw packaging works.
* Code::Blocks is [using gcc 5.1](http://www.codeblocks.org/downloads/26).

So, I'm reopening this and proposing we advance to a minimum gcc 5.1 (or maybe 5.3?).  That gives us access to [all of C++14](https://gcc.gnu.org/projects/cxx-status.html) (and in the [library](https://gcc.gnu.org/onlinedocs/gcc-5.1.0/libstdc++/manual/manual/status.html)).  gcc 5.1's C++14 support might be buggy in some corner cases, so that's why I'd prefer 5.3.

**Comment by kevingranade** [comment]
Historically C::B has been the easiest way to get started on windows, so I'm hesitant to move past 5.1, but I'm not totally sure what people are using now, so if that's no longer the case we can step up to 5.3.

**Comment by ZhilkinSerg** [comment]
C::B builds are partially broken now. I think MSYS is the easiest way now.

**Comment by kevingranade** [comment]
Well there you go, if it isn't even a reliable way of getting started, no need to accommodate it, we're good to bump to 5.3.  At the same time, bump clang minimum version to one that supports c++14 at least, looks like 3.4.  The main limiter for clang seems to be the version that Xcode is built on, so it might be reasonable to bump to something later than that, but I have no visibility into Xcode versions.

**Comment by jbytheway** [comment]
Cool.  I'll work on one or more PRs for this.

**Comment by jbytheway** [comment]
When I update the docs about compiler support, is it appropriate to describe our position as:

We aim to support gcc and clang up to the newest stable versions and back to those shipping in any supported version of a popular distribution or relevant development environment, including Ubuntu, Debian, MSYS, and XCode.

**Comment by ZhilkinSerg** [comment]
We don't provide `clang` support in `MSYS` (yet), but it has version 8 by default and default `gcc` version there is either `7.4` or `8.3`.

**Comment by jbytheway** [comment]
@narc0tiq I note that the Linux builds (Tiles and Curses) on the primary build matrix on Jenkins are using `g++-4.8`.  How easy is that to change to something newer?

**Comment by narc0tiq** [comment]
It's almost trivial to change it, I've got it on 4.8 only because it was the bottom of our support.

**Comment by narc0tiq** [comment]
Please note that I've discovered there's no available package for gcc 5.3, so we're moving to 5.5 instead for the Linux 64 builds. At the same time, though, please double-check the Windows and OSX builds, as they tend to be non-trivial to upgrade.

**Comment by jbytheway** [comment]
Thanks!  On Jenkins it looks like Windows is using gcc 5.4 and OS X is using clang 3.8, so I think we're good there.
