### ISSUE TITLE
Category changes for some early game items

### ISSUE THREAD

**Issue by Feuerhai** [CleverRaven/Cataclysm-DDA#26221]
After playing around with the automatic sorting of the new zones, I realized some items have strange categories attached to them. I only checked really early game items.

These are the changes I propose:
Change digging stick from WEAPON to TOOL, since the primary reason for crafting one is digging shallow pits.
Change heavy stick, long stick and rock from WEAPON to SPARE PART, since I and I guess most others mainly use them for crafting. They all have "decent melee weapon" in their description, but so has the pipe, which is a SPARE PART. If they don't change, the pipe has to which is even a "good melee weapon" and in dps better than the rock and heavy stick with a to hit bonus instead of the malus the other items have.

Alternatively it would be nice to change the category myself as a player ingame for individual items (heavy stick as a weapon in the early game and a spare tool later) or even create entire new categories for sorting, but I guess that would be pretty complex.

**Comment by Theundyingcode** [comment]
I noticed this too.  If no one is working on this I can volunteer a quick scan and fix run. (probably tomorrow)

**Comment by Theundyingcode** [comment]
So I went through the first ~1/3 of the debug wish for an item menu and noticed a bunch of problematic trends:

- Lots of tools aren't actually tools. (diamond matrix)
- Inactive _____ tools vs weapons inconsistencies. 
- Inconsistency between spare parts and other (carpet vs. paint)
- Natural groupings appear in things classified as other. (containers)

The true fix here is to add some more categories to allow things to be properly categorized which, is something I neither know how  to do nor have the motivation to learn right now.

I'll go through and fix the nonsensical stuff and then raise a new issue asking for new categories once I'm sure what wants to be added.  Currently, my list is:

Category | Description | Example(s)
-------- | ----------- | ----------
Construction Materials | Things used for building larger stuff | Logs, long stick, sand, cement
Containers | Just change other's container subjection to be its own category | bowls 
Deployables | Anything that gets placed when you use it | inactive __hack, inactive robots
?Time Takers? | Things that take time i.e. fermenting, tanning, etc. or awaiting action | tanning hide, lit/filled/finished charcoal kiln
Salvage | Things that basically exist to be scrapped for parts | Desk fan, broken anything
?Plants/ Harvested? | All the new flowers getting added is causing a lot of clutter so separate | pine bough, flowers
