### ISSUE TITLE
Cleaning using a washboard ignores water frozen status

### ISSUE THREAD

**Issue by metiscus** [CleverRaven/Cataclysm-DDA#26234]
**Describe the bug**  
The user is able to clean clothes etc using a washboard when the only available source of water is in a frozen status. If you can't drink it, you surely can't clean with it. Someone missed adding a status check somewhere.

**To Reproduce**  
1. Stand by a toilet with frozen water in it and the right supplies to clean
2. Use a washboard to clean 
3. Observe that the cleaning operation was successful 

**Expected behavior**  
1. The cleaning operation should fail due to the frozen water being incompatible with cleaning

**Screenshots**  

**Versions and configuration(please complete the following information):**
Running build 8046 on Windows 7

**Comment by metiscus** [comment]
Actually I suspect that this won't fix the use of frozen pond water. Is there a good way to test this?, best I can tell the debug menu doesn't allow you to edit the actual terrain to be a frozen pond.

**Comment by primuspaul** [comment]
Don't know if related, but also you cannot use clean water to clean clothes unless you have regular water nearby. It will say you have none available. However, if you have dirty water nearby, you can then select what kind you want to use (clean or dirty).

**Comment by l29ah** [comment]
Also turns out it can be used in very dark conditions.
