### ISSUE TITLE
My last issue was not responded, So "Delay after a minute" again.

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#26232]
There's a delay when every minute passes, while it does not interrupt my combat or something, it does make sleeping, crafting and butchering longer.

This happened yesterday and it only affected my main world, the rest are unaffected.
Game is 0.C-33330-g5ebab1d (tiles), 8046 build

My save - [Trimega.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2476035/Trimega.zip)
Try to reproduce and fix this problem, thanks

**Comment by kevingranade** [comment]
Dont repeat issues.
