### ISSUE TITLE
Auto-move cancelled by door/window opening

### ISSUE THREAD

**Issue by cake-pie** [CleverRaven/Cataclysm-DDA#26239]
**Describe the bug**  
Auto-move is cancelled when encountering a door/window that has to be opened

**To Reproduce**  
Try to auto-move through a closed door or window (includes vehicle doors)

**Expected behavior**  
Auto-moving to selected destination as indicated by planned route.

**Actual behavior**  
Halt after opening door/window

**Screenshots**  
![door](https://user-images.githubusercontent.com/28502722/46916558-e242e100-cfee-11e8-93b0-4eca59051a99.png)
![window](https://user-images.githubusercontent.com/28502722/46916559-e3740e00-cfee-11e8-945a-e7212b0a444d.png)
![vehicle](https://user-images.githubusercontent.com/28502722/46916560-e4a53b00-cfee-11e8-9802-03ecde3f481e.png)

**Comment by greenlucid** [comment]
There's something to discuss, though. You want the door/window to open automatically and stop moving if there are zombies, but what if you see an item you're interested in and you desire not to waste movement? And there's also the problem of the state of the door/window, is the automove feature supposed to close it after you've passed through it, or leave it open and keep on autowalking?

**Comment by Theundyingcode** [comment]
IMHO auto-move should not take any actions besides moving. (i.e. stop in front of the door and don't open it) 

In dungeon crawlers or other simpler roguelikes, having auto-move walk through doors and such is fine but cataclysm has too many options/ ways to do things and would just cause problems for anyone who doesn't know and/or like whatever the included actions are.  I do see the appeal of having the automove actually go inside but, I firmly believe that players must have full control over the settings regarding what actions the auto-move can/will perform.  While adding these options wouldn't be a huge undertaking, it's not exactly trivial either and I think there are better/ more pressing issues to focus on.
