### ISSUE TITLE
Weird circumstantial error - Tried to get invalid vehicle part: (null)

### ISSUE THREAD

**Issue by Drakasin** [CleverRaven/Cataclysm-DDA#26243]
**Describe the bug**  
The game throws out this error, then when I try "Press space bar to continue the game" the game freezes permanently. (see screenshot)

**To Reproduce**  
Savegame down below.
I don't honestly know, subsequent tries to reproduce it failed, however it seems that around the area (the road above the Mansion and in the Mansion itself) the game has slowed down considerably, and even crashed again without errors.

**Expected behavior**  
No error and game-freeze-crash

**Screenshots**  
https://i.imgur.com/sPWPpZh.png

**Versions and configuration:**
 - OS: W10 64bit
 - Game Version: 0.C-33350-g089bb94
 - Graphics version: Tiles
 - Mods loaded: DDA, simplified nutrition, filthy clothing, NPC mutations, NPC traits, No NPC Needs (I am not using any car mods)

**Additional context**  
Save file (quicksave before this occured, move directly southwest for a short while until you hit the road one square north of the Mansion):
https://drive.google.com/file/d/19LIaH6Q2scgLnmoc6raU8HHpyaTpd8oB/view

**Comment by Drakasin** [comment]
Happened again, version 8059 experimental, exactly same error, line 103 etc. This time I was in a pub, nighttime, low nightvision, I was moving south toward a chair with booze on it.  I couldn't even see the road, nothing. Perhaps it's not about visually seeing something but rather something loading into my reality bubble? Again it froze to dark screen after pressing spacebar and had to restart the game.

This time I was able to reproduce the error. Go west toward the megastestore (blue M), directly south of it is a road, at the easternmost point north one square is a hardware store (don't go south yet!), go into it, explore, etc. Then go directly south about one square south of the road and move a bit west. somewhere around the are south of the hardware store it seems to crash.
save file: https://drive.google.com/file/d/1Dr79AfvGMeg-Oj4N_aHddnrQfSn4RwRb/view

**Comment by Night-Pryanik** [comment]
@Drakasin have you ever encounter this problem on latest experimentals (or at least on 0.D stable)?

**Comment by Drakasin** [comment]
Played only a bit of 0.D and haven't played latest experimentals at all. Didn't encounter it in 0.D in the twenty or so hours I've played of it. Closing.
