### ISSUE TITLE
All drinkables say: You can't do that while underwater

### ISSUE THREAD

**Issue by Achie72** [CleverRaven/Cataclysm-DDA#26244]
**Describe the bug**  
All drinkables say `You can't do that while underwater` using E menu to consume items.
First i thought, it's just the way showing something is frozen (just updated to 8015), but happens with heated up items too.

**To Reproduce**  
1. Make a player on this map.
2. Gather drinkables.
3. Press E. Also works on heated up items.

**Expected behavior**  
I could drink heated up items, and for frozen drinks, just a message: `You cannot drink frozen drinks`, although they should be still eatable, like shaved ice, maybe for less thirst regain.

**Screenshots**  
![image](https://user-images.githubusercontent.com/15895931/46918416-4f944900-cfd2-11e8-9e82-714c14475fbc.png)
![image](https://user-images.githubusercontent.com/15895931/46918419-58851a80-cfd2-11e8-85f7-d2b1c81b9178.png)
![image](https://user-images.githubusercontent.com/15895931/46918421-5d49ce80-cfd2-11e8-8190-12d69a9632fa.png)
![image](https://user-images.githubusercontent.com/15895931/46918423-633faf80-cfd2-11e8-99a4-4ebb2f64548f.png)
With another character on this map:
![image](https://user-images.githubusercontent.com/15895931/46918629-676ccc80-cfd4-11e8-98c5-c6fa92f1ff4f.png)
![image](https://user-images.githubusercontent.com/15895931/46918633-6dfb4400-cfd4-11e8-8075-2b8a85197216.png)

**Versions and configuration(please complete the following information):**
 - Windows 10 
 - Game Version  0.C-32991-g17df28b
 - Graphics version Tiles
 - Mods loaded "dda","no_npc_food","filthy_morale","novitamins",
"makeshift","Medieval_Stuff","More_Survival_Tools","mutant_npcs",
"more_locations","Urban_Development","boats","deoxymod","blazemod",
"Tanks","StatsThroughSkills"

**Additional context**  
Save folder: https://drive.google.com/file/d/1XxClX0cg0kgbUzJbI_p6r_IxbPQSnS3y/view?usp=sharing (i hope this is the way to share it)
Tileset: https://github.com/SomeDeadGuy/Cata-MSX-DeadPeopleTileset

**Comment by Drakasin** [comment]
I don't have that problem on 8048 with DDA, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Mutant NPCs, and NPC Traits

**Comment by Clyybber** [comment]
@Achie72 I guess we can close this then?
