### ISSUE TITLE
Add an option to transfer items to nearby NPC/Shopping carts

### ISSUE THREAD

**Issue by AskaHope** [CleverRaven/Cataclysm-DDA#26253]
On my current playthrough I'm playing as an armoured spearman and my armour is quite encumbering, so I let my NPC slaves carry my stuff/use shopping carts.

Shopping carts are a bit tricky to maneuver around houses, and it's really annoying to ask NPC to hold my junk, I have to ask for each item, and can't even know their current/available volume. (and if I give them any kind of gun, they'll instantly wield it and shoot their way through anything!)

**Describe your suggestion** 
Add an option to transfer items that are too big to pick up to nearby NPCs or shopping carts

Also add an option to give multiple items to NPC, and know their current/available volume.

**Additional context** 
This is my first time on GitHub, I really love the game and you guys are doing a great job. :smile:

**Comment by pjf** [comment]
Can confirm both of these already exist as mentioned in previous comments. The advanced inventory menu even lets you hit `d` to select the currently dragged vehicle, making it super easy to move things in and out. (I was so happy when I discovered that.)

I think we might be able to close this issue. Delighted you're enjoying the game, @Askahope!
