### ISSUE TITLE
narcolepsy problem

### ISSUE THREAD

**Issue by mding9** [CleverRaven/Cataclysm-DDA#26252]
**Describe the bug**  
When narcolepsy activates, you are still able to move, but you are blinded because you are closing your eyes. You can still use the sleeping action if you want to roleplay, though, and can move to a safe place in your memory to sleep. However, there is no way to do away with this effect, so its kind of annoying to be blind for the next few minutes.
**To Reproduce**  
1. Start a player with the narcoleptic trait
2. Run around, preferably with debug traits that will keep you safe
3. You will eventually get the narcolepsy message and will close your eyes.
4. You can still move around

**Expected behavior**  
I guess I should have gotten a picture of the narcolepsy description, but it basically says you lie down to sleep. So I am thinking it would just make you sleep automatically, not allowing you to move.
**Screenshots**  
![thatsaninterestingsleepwalk](https://user-images.githubusercontent.com/42954111/46921539-63d04a00-cfc2-11e8-913b-24c9b50cd222.PNG)
I hope the thin line of discovered land shows that I am still able to move despite being "asleep"

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version [0.C-03333-g5ebab1d]
 - Graphics version [Tiles]
 - Mods loaded [boats, more vehicles, tanks, lots of building mods, arcana and magic items, classes and scenarios]

**Additional context**  
To be honest, I think this is just happening because trying to sleep has become a player action. Maybe narcoleptic wasn't changed to compensate, so now it is acting weird.

**Comment by zacklucky7** [comment]
Issue is still ongoing as of 0.C-37523-g4c3c368 (8529)

**Comment by Night-Pryanik** [comment]
That's the HAND OF MORPHEUS!

**Comment by l29ah** [comment]
YEAH THIS SUCKS
Saved in the sleepwalker mode: 
[#26252.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3127669/26252.zip)

**Comment by BrianLovelace128** [comment]
Just confirming that this is still an issue, as it just happened to me in game and confused the hell out of me for a moment.

**Comment by snipercup** [comment]
I got this issue as well
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-8418-g126c27b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Mining Mod [Mining_Mod],
    Folding Parts pack [deoxymod],
    Simplified Nutrition [novitamins],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    More Locations [more_locations],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Hydroponics [hydroponics],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Bens GF recipes [Tolerate_This],
    Icecoon's Arsenal [ew_pack],
    Cataclysm++ [Cata++],
    Urban Development [Urban_Development],
    Mythological Replicas [nw_pack],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]

using windows 8.1

Getting this:
![image](https://user-images.githubusercontent.com/50166150/66686319-5bffc000-ec7f-11e9-9bea-5c07070b82b3.png)

But i'm not asleep and can move around.

Sometime later I get this:
![image](https://user-images.githubusercontent.com/50166150/66686367-7f2a6f80-ec7f-11e9-9633-36a5182ada9d.png)

and everything is fine.

When i'm 'asleep', I can try to sleep manually:
![image](https://user-images.githubusercontent.com/50166150/66686411-ada84a80-ec7f-11e9-85c3-b274f6a2c9bc.png)


It actually returns to normal after 'you try to sleep but can't'
![image](https://user-images.githubusercontent.com/50166150/66686506-f95af400-ec7f-11e9-9856-9205890e53b0.png)

But you only notice it when choosing 'stop trying to fall asleep and get up' at the 'stop trying to fall asleep' prompt.
