### ISSUE TITLE
Add back <> navigation to crafting menu / other menus

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#26267]
Can we add back the ability to use <> in the menus? Not sure why we changed this to ONLY use TAB with no way to change it in the keybindings. 

Also the action menu is inconsistent. Sometimes 1 is back sometimes its not..

**Comment by ZhilkinSerg** [comment]
Are you sure these are not rebindable? Did you try to press `?` and change keybindings?

![image](https://user-images.githubusercontent.com/16213433/46974630-450aaa00-d0cd-11e8-8a4c-80ad66e7d99b.png)

![image](https://user-images.githubusercontent.com/16213433/46974664-56ec4d00-d0cd-11e8-9655-89390f48a9ed.png)

**Comment by Treah** [comment]
? has not opened the keybindings window for quite some time now.. So whatever version your showing there must be old or its just different in the tiles version of the game.  I have checked though every option and I have nothing that says Go to prev tab?

**Comment by Treah** [comment]
Never mind, I found it... Odd why this is not in the keybindings list tho?
