### ISSUE TITLE
Cant drag motorcycles sometimes

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#26268]
Getting message about STR is not enough when trying to move a motorcycle but my char STR never changed and was able to move it before. After riding it 2 tiles turning off the engine and then trying to move it again can move again? Not sure what check is causing this problem.

**Comment by dsmky117** [comment]
Did you add items to the cargo, thus increasing it's weight beyond your STR limit?

**Comment by Treah** [comment]
No, I was moving it before with what was in the cargo space. I even tried removing the items but still got the message my STR was not enough to move it?

**Comment by Inglonias** [comment]
Probably a dumb question, but did your STR change somehow? Pain is the most likely way for STR to change.

**Comment by jim-huynh** [comment]
Are you dragging it over rough terrain, vs on a flat road?

**Comment by kevingranade** [comment]
Not reproduceable
