### ISSUE TITLE
AEP_Extinguish is broken.

### ISSUE THREAD

**Issue by garlicer** [CleverRaven/Cataclysm-DDA#26277]
**Describe the bug**  
AEP_Extinguish doesn't work.

**To Reproduce**  
1. Make a custom item with "artifact_data" : {"effects_carried":  ["AEP_Extinguish"] }
2. Debug-create item-pick the custom item up
3. Light a fire.
4. Stand adjacent to the fire and press 55555555555555555555555

**Expected behavior**  
Fire must be extinguished.

**Screenshots**  
:$

**Versions and configuration(please complete the following information):**
 - OS: Win10.
 - Game Version: 0.C-33211-g58f0964
 - Graphics version: Mxotto.
 - Mods loaded: dda, Bright nights.

**Comment by garlicer** [comment]
fucking serious? i posted this on 16 Oct and still 'S1 - Need confirmation'? jesus christ
can't you just stop working with fucking mutts & puppies and fix the bug please?

**Comment by kevingranade** [comment]
Yep I've lost what little motivation I had to keep this issue around.

**Comment by bausshf** [comment]
Why not fix it yourself and then make a PR since you're so clever?
