### ISSUE TITLE
(A)pplying a Mop to (*) filled Wooden Kegs destroys contents. (Design suggestions included)

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#26284]
**Describe the bug**  
Using the Apply menu to use a Mop and 'mopping' a built Wooden Keg destroys the filled contents. (e.g. Water, Wine etc)

**To Reproduce**  
Build Mop, use (A)pply on Wooden Kegs built with (*) and contents within are "mopped up" and destroyed. Not sure if the same logic applies to Fermenting Vats and Standing Tanks - cannot test ATM.

**Expected behavior**  
Is this a design feature explicitly to empty large containers of (spoiled/unwanted/unusable) liquids or is this unintended behavior? Because I can understand the ease of usage to "clean up" most unwanted liquids via this sort of deletion mechanic.

Suggestions:
1) Can a confirmation menu be added for when Mop is being used aimed towards constructed containers? Same "deletion" mechanic but a safety mechanism for unwary players. Not sure how difficult that would be to add.

2) Constructed containers via (*) be given an Unload or "Empty to Ground" option to deal with unwanted contents (which can then be Mopped up?) 

**Screenshots**  

**Versions and configuration(please complete the following information):**
Current PR 8055.

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by kevingranade** [comment]
It's unintended, if we want that fast empty ability it should be based on
interacting with the furniture.

**Comment by cake-pie** [comment]
This stems from mop not checking for `LIQUIDCONT`.

> Constructed containers via (*) be given an Unload or "Empty to Ground" option to deal with unwanted contents (which can then be Mopped up?)

Already possible through the "Fill a container with X" option when examined.
It should probably be relabeled "Dispense or dump X".

Fix incoming.
