### ISSUE TITLE
Plastic Canteens item text: reads WAIST yet Encumber a LEG slot?

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#26283]
**Describe the bug**  
Plastic Canteens are worn at the WAIST in item text yet encumber a LEG slot. 

Correction to be made or incorrect classing/text?

**To Reproduce**  
Current item text in PR 8055.

**Expected behavior**  
Ideally also describe *why* you expect it to happen.

**Screenshots**  
![weird2](https://user-images.githubusercontent.com/43046067/47045269-69639680-d160-11e8-88d0-c28a7589257d.png)

**Versions and configuration(please complete the following information):**
PR version 8055.

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by Feuerhai** [comment]
The waist is a layer for clothing like outer or strapped. It only exists as part of the torso or the legs.
As you can see, there is no extra area for waist in the encumbrance table.

**Comment by evankimori** [comment]
Closed this issue since commenters stated that this is not a Bug but is WAI.
