### ISSUE TITLE
Impossible to retrieve a vehicle or its contents after it sinks

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26281]
**To Reproduce**  
1. Get a car.
2. Drop all your possessions in the trunk.
3. Drive into a river.

**Expected behavior**  
Wearing heavy suit i should be able to sink and find the car with all my stuff there.

**Versions and configuration(please complete the following information):**
0.C-33397-g0c4464c32b-dirty
Bright Nights

**Comment by Zireael07** [comment]
Sinking == removing car from map.

At least without Z-levels (I really don't know what the Z-levels do in this case, if anything).

**Comment by kevingranade** [comment]
In order to support this, we need a much more nuanced approach to vehicles interacting with obstacles.

We probably want to replace most if not all instances of sinking with getting stuck instead.  In cases where we do sink a vehicle, it would require sufficient room to place the entire vehicle under water.

**Comment by Inglonias** [comment]
This is actually quite hard to fix. As far as I am aware, vehicles cannot change z levels (unless you collapse them and pick them up first)

**Comment by kevingranade** [comment]
They can, it's actually trivial, the problem is at the point when a vehicle sinks theres nowhere to put the whole vehicle.

**Comment by SirPendrak** [comment]
Rivers and lakes need to be made z-levels deep first.

**Comment by l29ah** [comment]
YOUR SHOPPING CART SANK

**Comment by Zireael07** [comment]
Still a valid issue, though.

**Comment by jfcaron3** [comment]
I accidentally sank my travois in deep water while moving around a swampy area.  I get a warning before *I* jump into deep water, so I feel I should also get a warning if I'm about to send my grabbed item into it.  This is different than driving a car into water, I was just dragging the travois around like a caveperson.
