### ISSUE TITLE
Narcolepsy and new map memory leads to no vision when waking up right after

### ISSUE THREAD

**Issue by derpkerk** [CleverRaven/Cataclysm-DDA#26290]
**Describe the bug**  
When you choose the trait Narcolepsy you fall asleep intermittently. In combat you wake right up when you get hit. The vision then though since the new map memory has been implemented is none. Work around is to go to sleep again and then canceling trying to fall sleep

**To Reproduce**  
Pick narcolepsy, fight zombos

**Expected behavior**  
Vision returning upon being woken

**Versions and configuration(please complete the following information):**
 - OS: Manjaro Linux (removed most Manjaro related scripts so it's mostly ARCH)
 - Game Version 0.C-33379-g629cb06
 - Graphics version Tiles
 - Mods loaded [e.g. [  "dda",  "no_npc_food",  "filthy_morale",  "novitamins",  "craftgp",  "FIC_Weapons",  "ew_pack",  "makeshift",  "Medieval_Stuff",  "More_Survival_Tools",  "nw_pack",  "modular_turrets",  "PK_REBALANCE",  "Salvaged_Robots",  "alt_map_key",  "mutant_npcs",  "npc_traits",  "national_guard_camp",  "more_locations",  "FujiStruct",  "mapgen_demo",  "Experimental-Z-Level",  "Urban_Development",  "boats",  "deoxymod",  "blazemod",  "Tanks",  "more_classes_scenarios",  "RL_Classes",  "manualbionicinstall",  "safeautodoc",  "sleepdeprivation",  "StatsThroughSkills"]]

Makes me wonder whether one could implement moonwalking somehow like this waking up somewhere else ^^

**Comment by Ramza13** [comment]
#36452 should fix this.
