### ISSUE TITLE
NPCs disappear when repeatedly changing z-levels, multiple symptoms.

### ISSUE THREAD

**Issue by Discohydra** [CleverRaven/Cataclysm-DDA#26298]
**Describe the bug**  
 DEBUG    : Failed to place NPC in a valid location near (114,74,-1)
 
 FUNCTION : void npc::place_on_map()
 FILE     : src/npc.cpp
 LINE     : 843

NPC fails to be placed on map after changing z-levels repeatedly. NPC disappears. The above error message happens every time the PC enters the same tile as the NPC disappearance. While producing this bug, they NPC in question may have their name show up in the "C" chat menu multiple times.
**To Reproduce**  
Find any change in z-level while an NPC is following the PC, change z-levels repeatedly, one z-level must have obscured vision of the NPC (Can't see the NPC from the distance that they follow,) then change z-level repeatedly (As if you're unloading a cart full of supplies,) eventually, the NPC will disappear, and will be unable to be placed on the map.

**Expected behavior**  
The NPC should be able to follow the PC up and down through different z-levels without disappearing.

**Screenshots**  
https://puu.sh/BMKdg/19f22e75d7.jpg

**Versions and configuration(please complete the following information):**
 - OS: Win10 x64 Pro
 - Game Version: 0.C-33432-gef7bf77 (tiles)
 - Graphics version: Tiles, x64
 - Mods loaded: [
  "dda",
  "more_locations",
  "more_buildings",
  "Experimental-Z-Level",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "Arts' Guns",
  "craftgp",
  "makeshift",
  "ew_pack",
  "Medieval_Stuff",
  "realguns",
  "SD_Magcrafting_Realguns_Extension",
  "More_Survival_Tools",
  "blazemod",
  "deoxymod",
  "Tanks",
  "boats",
  "modular_turrets",
  "Salvaged_Robots",
  "no_npc_food",
  "StatsThroughSkills",
  "sleepdeprivation",
  "manualbionicinstall"
]

**Additional context**  
The first symptoms of the bug are that the NPC doesn't move and that there are multiple entries of the NPC in the [C] Chat menu. It is possible to save the NPC by saving, quitting, and reloading while this stage of the bug is in effect. Once the NPC disappears, it is no longer possible to recover the NPC through actions that the end user can perform.

**Comment by Discohydra** [comment]
If it helps, it occurred in the holdout basement, with the crates, kitchen, damaged m60, kitchen, reloaded ammo. Great place for a base.

**Comment by FulcrumA** [comment]
Possibly related to #23530?

**Comment by xrandomuserx** [comment]
> While producing this bug, they NPC in question may have their name show up in the "C" chat menu multiple times.

Have experienced this bug multiple times.
