### ISSUE TITLE
Lighting a charcoal kiln while it's on the ground consumes no charges whatsoever.

### ISSUE THREAD

**Issue by RosieMcCattail** [CleverRaven/Cataclysm-DDA#26317]
The bug appears when 'a'ctivating a charcoal kiln lying on the ground. The kiln residing in the inventory consumes lighter charges when using inventory popup menu, but fails to light when having no fire source, despite posessing a Mini-Flamethrower bionic.

1. Fill a kiln, grab it.
2. Put it anywhere you see fit.
3. Press 'a'
4. Kiln is activated - no charges are consumed from any sources.

Kiln activation should consume lighter/matchbook/mini-flamethrower charges.

 - OS: Win7 x64
 - Game Version  0.C-33301-gc9e5e36 (8044, but checked the changelog, doesn't seem to be fixed in the newer ones)
 - Tiles
 - ["dda", "craftgp", "FIC_Weapons", "realguns", "ew_pack", "makeshift", "Medieval_Stuff", "More_Survival_Tools", "nw_pack", "Mining_Mod", "mutant_npcs", "npc_traits", "deoxymod", "blazemod", "Tanks", "No_Fungi", "manualbionicinstall", "no_reviving_zombies", "safeautodoc", "StatsThroughSkills"]

**Comment by Night-Pryanik** [comment]
Tested right now on latest experimental - had a lighter in inventory, dropped filled charcoal kiln right next to my character, activated the kiln - lighter's charge is consumed.

Closing right now, if this is still an issue, ping me.
