### ISSUE TITLE
Cannot remove a storage battery with a pallet lifter

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26320]
**Describe the bug**  
I've installed a pallet lifter to a car and still can't remove a storage battery from another car. It says there's no tool with lifting 1 while in fact i'm standing on the lifter.

**Versions and configuration(please complete the following information):**
 - 0.C-33397-g0c4464c32b-dirty
 - Bright Nights

**Additional context**  
Save: https://dump.bitcheese.net/files/tetotof/18.10.2018.tar.xz

**Comment by l29ah** [comment]
Okay, i had to move the pallet lifter tile to the battery tile for it to work. This is inconsistent with all the other tools that don't care where is the target vehicle tile is located.

**Comment by AskaHope** [comment]
I'm having a similar problem with a 120mm cannon gun in a tank.
The game says I need 7 lifting quality, but doesn't seem to count my adjacent boom crane.
Had no issues removing the tank treads, tough.

**Comment by FulcrumA** [comment]
@AskaHope 
I believe the lifting equipment has to be close to the tile from which the part is to be lifted and it has to be in the direct sight line. Possibly if you'd disassemble/break tiles between the one with the cannon and the crane and make sure the crane is nearby, it will work.

**Comment by RosieMcCattail** [comment]
Yes, that's right. You need the lifting equipment close to the tile in question.
Another issue I've encountered is that sometimes I'm able to remove parts without meeting the needed str/lifting/jacking requirements.
