### ISSUE TITLE
Plows and Rockwheels can be converted into JSON effects

### ISSUE THREAD

**Issue by Xion350** [CleverRaven/Cataclysm-DDA#26324]
As per @mlangsdorf from the Discord.

> So the plow and the rockwheel use copy-pasta of the same code.  It could be generalized to take a JSON configuration, something like "transform_tiles": { "base_flag": "DIGGABLE", "new_terrain": "pit_shallow", "failure_damages": true }.

Having this effect in JSON would be useful as you could create vehicle parts that do more than just till earth.  The original suggestion was from someone who wanted a vehicle part that could create roads.

**Comment by KnightosMaster** [comment]
This functionality now exists in the form of transform_terrain, and should probably be closed. @mlangsdorf

**Comment by ZhilkinSerg** [comment]
It was jsonized in PRs like #31894 and #31913.
