### ISSUE TITLE
Haul up/down Stairs

### ISSUE THREAD

**Issue by Cool3303** [CleverRaven/Cataclysm-DDA#26332]
Moving items up or down stairs is too tedious as it requires manually loading and unloading the inventory everytime.Considering many basements (not to mention labs) have a lot of materials or bulky items, a feature to automatically haul up stairs would be quite helpfull.

I feel conflicted because I don't want to demolish the Overworld buildings, but considering 2x4s and metal scrap can quickly take up multiple m^3 carrying items upstairs becomes tedious.

This could be either be implemented for the default hauling function or the advanced inventory.

**Comment by l29ah** [comment]
i wanna ride labs with my shopping cart like i'm in a wonder mall!

**Comment by kevingranade** [comment]
Implemented by #28365
