### ISSUE TITLE
The vehicle sucked up the sewage from the sewer.

### ISSUE THREAD

**Issue by kwl01skz** [CleverRaven/Cataclysm-DDA#26336]
**Describe the bug**  
The vehicle sucked up the sewage from the sewer.

**To Reproduce**  
1. Entering the sewer.
2. Unfold a folding bike.
3. Ride the bike.
4. It will turn sewage into flat land.

**Expected behavior**  
Nothing happens.

**Screenshots**  

https://discourse.cataclysmdda.org/t/my-bicycle-sucked-up-the-sewage-from-the-sewer/16503

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 
 - Game Version: 0.C-31136-g79d9903
 - Graphics version: Tiles
 - Mods loaded: none

**Comment by Zireael07** [comment]
It's not sucking up, it's to simulate a vehicle displacing liquids (usually water).

**Comment by ZhilkinSerg** [comment]
#25388

**Comment by Night-Pryanik** [comment]
Not a bug, closing.

**Comment by Night-Pryanik** [comment]
The mechanic could get some love, but in general it's WAI.
