### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by micage** [CleverRaven/Cataclysm-DDA#26340]
It's a sudden crash without any reason I know of. It often happens when running into unexplored areas. But not each time.

Since i built a debug version i got a stack trace of the crash:
vehicle.cpp, line 1563, vehicle::part_removal_cleanup(), if( it->removed ) {

I presume it's caused by iterating over an already deleted vehicle_part.

 - OS: OS X 10.11.6
 - Game Version 0.C-33434-g58418b726]
 - Graphics version = Tiles
 
Crash occurs in vanilla and with mods loaded regardless.

Here is my build command: 
cmake ../ -DCMAKE_BUILD_TYPE=release -DTILES=ON -DSOUND=ON -DLUA=ON

Although it says "release" it's not. I can build a release version but it crashes immediately.

**Comment by Inglonias** [comment]
I'm not sure if this is related to my intermittent CTDs that I'm seeing as well, but I am seeing intermittent CTDs. Because I'm not playing the debug build, I don't have a stacktrace, though.

**Comment by eilaattwood** [comment]
Looks like I experienced this bug to. In my case game crashes when trying to visit regional dump full of broken vehicles and a horde smashing them apart. Can upload my save, if needed.

**Comment by jbytheway** [comment]
Possibly related to the vehicle-related crashes here: #26291, #26297, #26315.

**Comment by micage** [comment]
Most certainly there is an invalid vehicle_part in the vehicles vehicle_part list. And as it's occurring when exploring new tiles it could be the vehicles initial state that has a corrupt vehicle_part pointer. In the meantime I wrapped the iteration (-> vehicle::part_removal_cleanup) in a try catch block. I'm new to the codebase so for me it's in the dark where this invalid pointer comes from.
My guess is a smart pointer issue.
From a developers point of view this try-catch is insane, but as a player I want to keep playing without saving every 5 minutes. No new crashes since hours after my dirty fix.

**Comment by micage** [comment]
Here is one crash report (stack-trace): 
Process:               cataclysm-tiles [12676]
Path:                  /Users/USER/*/cataclysm-tiles
Identifier:            cataclysm-tiles
Responsible:           cataclysm-tiles [12676]
0   cataclysm-tiles               	0x0000000111da857a vehicle::part_removal_cleanup() + 474 (vehicle.cpp:1563)
1   cataclysm-tiles               	0x0000000110d2f997 map::vehmove() + 2279 (map.cpp:346)
2   cataclysm-tiles               	0x0000000110551823 game::do_turn() + 2979 (game.cpp:1619)
3   cataclysm-tiles               	0x0000000110cd1646 main + 8790 (main.cpp:649)
       0x10fbd6000 -        0x112183fff +cataclysm-tiles (0) <7BD61DBF-6516-3422-A980-7A44AA7AEAF4> /Users/USER/*/cataclysm-tiles

**Comment by ZhilkinSerg** [comment]
Closed in #26414.
