### ISSUE TITLE
"The calf doesn't want that kind of food" when feeding a calf Cattle Fodder

### ISSUE THREAD

**Issue by YourFirstSim** [CleverRaven/Cataclysm-DDA#26343]
**Describe the bug**  
When attempting to feed a calf Cattle Fodder, it refuses to eat it, giving the message "Calf does not want this type of food", making it impossible to tame them.

**To Reproduce**  
1. Find calf
2. Attempt to feed calf cattle fodder.

**Expected behavior**  
Expected calf to be tamed through use of cattle fodder, the way it works on adults. Feeding bird seed tames young birds, so this does not seem to be intended behavior. If it's the intended behavior for a calf to be untameable due to being too young, the message does not make this clear.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-33477-g5cf860b
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Book Scanner Mod

**Comment by xrandomuserx** [comment]
Calfs probably want to drink milk, this is how they are raised until they can be weaned onto solid foods, like grass. Your could feed them calf meal, but they fatten up with milk and put on weight very quickly. IRL.

**Comment by kevingranade** [comment]
Some animals are tameable, some aren't,  it's not a bug.

**Comment by MrHrulgin** [comment]
At the moment I have a calf wandering around my base, causing my NPC guards to continually leave their posts to check out the footsteps. Without being able to tame calves, I either have to deal with NPC distracting and sleep disturbing footsteps until it is an adult in order to grow my herd, or kill it. Bug or not, being unable to tame calves is not a good player experience.

**Comment by kevingranade** [comment]
I agree there's a *problem*, but the proposed solution isn't valid.  Feel free to open another issue like, "calves are a hassle and I need a way to move them around and contain them"

**Comment by MrHrulgin** [comment]
Will do.

**Comment by MrHrulgin** [comment]
Done; #29343

**Comment by kevingranade** [comment]
Thank you, I know the issue handling might seem arbitrary, but it's
intended to insure we don't lose anything.

**Comment by AMurkin** [comment]
Huh. Current issue id is 26343, and the new one is 29343. The difference exactly 3000.
