### ISSUE TITLE
Honey Sandwiches are better than Peanut Butter and Honey

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#26346]
**Describe the bug**  
Honey sandwiches use less ingredients than a PB&H sandwich and contain more nutrition

**To Reproduce**  
Compare honey sandwiches to peanut butter and honey sandwiches

**Expected behavior**  
PB&H sandwiches should be better in terms of calories than a honey sandwich

**Versions and configuration(please complete the following information):**
 - OS: N/A
 - Game Version 0.C-33469-g72b502c (tiles)
 - Graphics version Tiles
 - Mods loaded **Simplified Nutrition**

**Comment by Regilith** [comment]
I'll take this one up.
On a side note, 2 charges of peanut butter spawn in a 500mL jar, but 1 charge of peanut butter is only 50g and 43 calories. 250mL of peanut butter should weigh 270g and have 1589 calories.
