### ISSUE TITLE
Kevlar/Leather padded containers lose the informations about their contents

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#26347]
**Describe the bug**  
after padding a hydration pack with kevlar it lose the informations about it's content 

**To Reproduce**  
1. spawn a hydration pack + tailor kit + some kevlar and thread
2. pad the hydration pack with kevlar
3. put liquids into hydration pack
4. game shows "Hydration pack+1 (8)"

**Expected behavior**  
The game should show "Hydration pack+1 of water (8)"

**Screenshots**  
https://cdn.discordapp.com/attachments/252368751016542218/503909088573521923/unknown.png

**Versions and configuration(please complete the following information):**
 - OS:  Windows 10
 - Game Version Jenkins 8067
 - Graphics version Tiles 
 - Mods loaded not relevant, hydration pack and all the components are vanilla

**Additional context**  
it is worth mentioning also that items with multiple paddings are shown as +1 as well, instead of +2/+3/+4

**Comment by rubenpd** [comment]
additional screenshots to describe problem, survivor harness loses information about the weapon inside it, and it is displayed +1 regardless of number of tailor kit modifications 

https://media.discordapp.net/attachments/494455674378518529/509028330692149278/unknown.png?width=316&height=676

https://cdn.discordapp.com/attachments/494455674378518529/509028620740591627/unknown.png

**Comment by wapcaplet** [comment]
I could not reproduce the issue in 0.E-9681-g2cca4d658c. Modifying a survivor harness with kevlar panels, and modifying a hydration pack with kevlar panels, both the modified `+1` items continue to correctly show their contents in both the inventory screen and the item description panel:

![image](https://user-images.githubusercontent.com/238395/108132676-7f572e00-7070-11eb-83af-ee359928cafd.png)
