### ISSUE TITLE
Survivalist's modular PDA item idea.

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#26356]
There are a lot of gadgets in the game that bring a lot of useful functions to the character. Smartphones, cameras, E-ink tablets, clocks, Geiger counters, RC (vehicle) controls, control laptops, thermometers, barometers, hygrometers, mp3 players, radios, and others.  It's difficult to bring all of that in the pockets.
So the idea is that skilled survivor can make the pocket computer with the ability to add sensors. hardware and software when necessary component is found. Starting device can handle the same functions that smartphone or e-ink tablet has, and other features can be added later through a menu or (if possible) through crafting.
This is the list of devices that i have in mind:
- wrist watch or Internal Chronometer CBM (adds clock and alarm functions)
- camera (take photoes)
- radio (or 2-way radio)
- Geiger counter or radiation biomonitor or Integrated Dosimeter CBM
- barometer
- hygrometer
- thermometer
- Weather Reader CBM or Doppler Radar Turbo 2000 (adds previous three at once) or diver's watch (just adds temperature indication)
- Alarm System CBM
- electrohack or Fingerhack CBM
- RC control
- remote vehicle controller
- Remote Controller CBM (adds previous two at once)
- hackPRO (adds control laptop capabilities. Need 2-way radio, RC control or remote vehicle control to be installed in order to be functional)
- blood draw kit and MediSoft or Blood Analysis CBM (adds blood Analysis)
- mp3 player
- some games (from misc software or game watch or handheld game system
- working as a cash card (we have NFC in smartphones IRL, so why can't we have that in the game?)
- ATM functions (It's complicated. We know that fixed ATM's are still functional. So It's possible to hack or deconstruct them to steal or copy the chip with bank network access codes and add it to the PDA. Attempting to hack an ATM is risky, ATM is shut down and eyebots are dispatched upon failure)
After installing this module vending machines and everything else that can accept cash cards begin to work with character's bank account directly, and ability to 'consume' found cash cards is added.
- something else that I can't remember now

Installation of new features requires certain skill level and can occasionally fail (like in crafting). Also, it consumes the installed item (optionally leaving leftovers like scrap, plastic and wires). Feel free to balance that behavior.

Yes, I've added CBM's to the list as installation to the gadget is less risky and easier than implanting, so some players can choose that instead.

And another interesting feature request will be the ability to scan (or take photo) not memorized recipes from the books an store them in the memory of the PDA, allowing then to use PDA instead of a book while crafting. Because it seems strange that you need to bring a pile of books with you just to look up single recipe of something. In real life anyone would just take a photo of the needed page or just tear it apart.

**Comment by FulcrumA** [comment]
I don't mind certain items that's player keep since a big part of the game gradually improving them over time but-absolutely-all-in-one device like that seems a bit like stretch to me. Having various portable computers that can be modified a number of times (maybe utilizing firearm modding system where various upgrades use various slots) and differ in terms of other stats could be interesting, however.

**Comment by eilaattwood** [comment]
Well, using firearm modding system in computers is interesting idea too, but it is not common IRL for some reason, so why that should exist among pre-cataclysm tech? And after the cataclysm competent survivors will try to develop the device to cover as much needs as possible.

I'm electronics engineer IRL, so i can say that soldering salvaged somewhere thermal or pressure sensor to the makeshift PDA is not overcomplicated and this is EXACTLY what i will do in such conditions after satisfying my basic survival needs and obtaining basic tools.

Characters are capable of making their own CBMs, after all. So I cannot see the reason why they cannot put together some circuits to make universal PDA needed for surviving.

Well, game balance is serious question, so we have a question - make it balanced, or make it realistic? 

And finally, we have CBMs that can turn survivor into the universal tool, after all. So maybe wide-function PDA is not so imbalancing?

**Comment by denemcam** [comment]
That's cool idea!
Firearm modding system is good, but i'd wish a vehicle modifying system alike - with circuits and stuff, that would'we been neat! Maybe adding different frames with differ bulk, weight (+component weight) and available space for modules.

**Comment by kevingranade** [comment]
Tiny computers are super hard to make by hand, one of the main ways they get really small is by integrating a bunch of different functions onto ICs, which is absolutely not something the player can do, another way is by using custom PCBs, which while not impossible, is extremely impractical.

So IMO a "survivor pda" is right out.

This leaves attaching sensors to existing devices.

A PDA in particular is going to be quite short on busses, so just attaching a bunch of sensors isnt going to fly, hence the, "slots" approach, which sounds reasonable. To be clear this isn't typically going to be "designed for adding perephials" slots, but hardware available to be repurposed.

Phones are ridiculously locked down unless you're using a purpose-built perephial.  I could see jamming a low bandwidth sensor into the audio jack, and on some phones a usb-like thing, but now you're up against signed drivers and modification prevention features.  Let's call that, "spotty".

Laptops are a lot better, you can actually work with the buses, there are more of them and depending on your OS you can maybe even get some custom drivers on there.  Of course that starts cutting into the portable aspect, but that's how it goes.

If you can find something similar to a arduino itll work a lot more like what you're describing, but then you're missing the display, and the integration time is significant.

**Comment by eilaattwood** [comment]
> If you can find something similar to a arduino itll work a lot more like what you're describing, but then you're missing the display, and the integration time is significant.

If a game character can craft handheld game system out of a superglue, processor board, small LCD screen and a RAM, then he/she is definitely capable to craft [this](https://youtu.be/coy26jWnteo).

**Comment by FrozenSnowFox** [comment]
These days a smartphone can do a lot of this stuff.  Clock, camera, light, games and mp3 player are all pretty standard.  I imagine you could get stuff like weather data, temperature ect if you could somehow still access satellites or some sort of network to grab the relevant information.  The two way radio, the remote control stuff and banking might be doable via apps?  As for other stuff that comes down to if you can modify the phone in various ways then again if you're desperate I suppose there's always duct tape.

**Comment by eilaattwood** [comment]
@FrozenSnowFox 
>  As for other stuff that comes down to if you can modify the phone in various ways then again if you're desperate I suppose there's always duct tape.

I really like that some crafting capabilities in Cataclysm are overestimated, when others are underestimated.

"Need a Nuclear Reactor CBM? Just hold my beer, I need to grab my makeshift welder..."
"Attach Geiger counter tube to the tablet with literally two wires and write literally ten lines of code to count pulses? No, that's not possible in the apocalypse. Forbidden magic required."

**Comment by cainiaowu** [comment]
Dont forget the offline map function that any modernmap apps have. It is very strange that you only have paper map in the future.

**Comment by kevingranade** [comment]
> If a game character can craft handheld game system

Feel free to pr a more involved game system recipe, but it's irrelevant to this discussion.

> By the way, IRL arduino is literally no more than a processor board without any kind of OS or any software at all 

Are you joking or serious? That's completely ludicrous.  No, you cannot just harvest a bare CPU board from an arbitrary device and expect to get anywhere reprogramming it.

> These days a smartphone can do a lot of this stuff. 

No objection at all to adding quite a lot of functionality to smartphones.

**Comment by Nymall** [comment]
One of my hobbies is playing with Raspberry Pi's and Arduino's for small integrated projects - these do not just "work". You need custom software, and a workable PC to create the sketches. For the PI's you need the OS.

http://cmuems.com/resources/getting_started_with_arduino.pdf

**Comment by eilaattwood** [comment]
> Are you joking or serious? That's completely ludicrous. No, you cannot just harvest a bare CPU board from an arbitrary device and expect to get anywhere reprogramming it.

That's just in-game convention that every piece of hardware drops the same components. It will be too much if you add CPU's with different architecture, peripherals, buses and ports to the game. So, currently you can disassemble a watch and then assemble an electrohack out of it's components in game. So why can't you assemble a PDA?

**Comment by eilaattwood** [comment]
>You need custom software, and a workable PC to create the sketches.

In-game books on computers explicitly tell us that they teach a character programming. And you actually use a smartphone or tablet to write firmware. And again - game conventions. Nobody asks where the games on makeshift game system are coming from in Cataclysm.

**Comment by kevingranade** [comment]
> So, currently you can disassemble a watch and then assemble an electrohack out of it's components in game.

Again, feel free to PR a change to the electrohack recipe, but it has no bearing on this issue.

There are a lot of bad crafting recipes scattered around, especially ancient ones that haven't been touched in years.  They do not justify adding new recipes that are as bad as they are.

I outlined what will work in my previous reply https://github.com/CleverRaven/Cataclysm-DDA/issues/26356#issuecomment-432080895  

You either need to work within that framework or plan on adding your content as a non-default mod.

**Comment by kevingranade** [comment]
Lots of overreach in what a player-crafted electronics device would accomplish.
