### ISSUE TITLE
DinoMod creatures dont have a texture/text markings

### ISSUE THREAD

**Issue by denemcam** [CleverRaven/Cataclysm-DDA#26364]
**Describe the bug**  
Dinomod creatures, or at least the one that i met, Allosaurus, doesn't have any texture or text markings.

**To Reproduce**<details> 
  <summary>Try to see the dinosaur..? </summary>
  <i>You can't. It's invisible.</i>
</details>
</br>

**Expected behavior**  
I should see what comes next to me before it bites my head off.  :(
 
**Screenshots**  
It's on a puddle of blood, and shown on minimap.
![dino](https://user-images.githubusercontent.com/39668224/47320068-6cc7b800-d661-11e8-9f42-6dfb97144d6f.png)

**Versions and configuration(please complete the following information):**
 - OS: [Win 7]
 - Game Version: [0.C-33469-g72b502c]
 - Graphics version: [Tiles - Default, ChestHole]
 - Mods loaded: ["dda","no_npc_food","filthy_morale","novitamins","craftgp","safeautodoc","brightnights","Tolerate_This","FIC_Weapons","realguns","ew_pack","makeshift","Medieval_Stuff","More_Survival_Tools","nw_pack","**DinoMod**","modular_turrets","Salvaged_Robots","alt_map_key","crazy_cataclysm","mutant_npcs","npc_traits","national_guard_camp","more_locations","FujiStruct","mapgen_demo","Experimental-Z-Level","Urban_Development","boats","deoxymod","blazemod","Tanks","necromancy","more_classes_scenarios","RL_Classes","manualbionicinstall","StatsThroughSkills"];

**Comment by Soyweiser** [comment]
I'm going to assume it has no tile set for the chesthole tileset. Which is odd, you would assume it would default to the symbol D. However, the dino mod has strange color settings, the Allosaurus is brown_white for example. Perhaps this color isn't rendered properly, could you try something? Open data\mods\DinoMod\dinosaur.json and change the color from "brown_white" to "white", and see if it then shows up.

**Comment by LyleSY** [comment]
I saw this too and thought it was an issue with ChestHole. Here is the Allosaurus in MXotto+: 
![screen shot 2018-10-24 at 1 24 57 pm](https://user-images.githubusercontent.com/26608431/47449352-6d12a100-d790-11e8-85ac-25b1ff146289.png)

But sure enough in Chesthole vanilla it's the invisible Allosaurus:
![screen shot 2018-10-24 at 1 27 13 pm](https://user-images.githubusercontent.com/26608431/47449431-9a5f4f00-d790-11e8-862a-1c93e17dceaf.png)

MShock24 fails to a nice orange D:

![screen shot 2018-10-24 at 1 28 30 pm](https://user-images.githubusercontent.com/26608431/47449484-c37fdf80-d790-11e8-8167-018c3b29b533.png)

Chesthole32 nothing:
![image](https://user-images.githubusercontent.com/26608431/47449546-e611f880-d790-11e8-8928-2721360b4d65.png)

The Allosaurus has a symbol and color defined in the code:

"type" : "MONSTER",
        "id" : "mon_allosaurus",
        "name": "Allosaurus",
        "species":"DINOSAUR",
        "default_faction":"allosaurus",
        "symbol":"D",
        "color":"brown_white",
        "size":"LARGE",

I don't think DinoMod is causing this.

**Comment by LyleSY** [comment]
Just confirmed this is still an issue in Chesthole16 
![image](https://user-images.githubusercontent.com/26608431/79046828-16e22980-7be1-11ea-8b5f-d8b444ae1107.png)

**Comment by wapcaplet** [comment]
Still reproducible in 0.E-9681-g2cca4d658c with ChestHole16, and the "Allosaurus" and "Stegosaurus" dinos (possibly others). Other tile sets including MSXOtto+, Ultica/Chibi_Ultica, RetroDays, and BrownLikeBears are fine, and either display a `D` or artwork for the Allosaurus and Stegosaurus.

**Comment by LyleSY** [comment]
Closed by #34196
