### ISSUE TITLE
Duplicate NPC Issue - Two Saves

### ISSUE THREAD

**Issue by xrandomuserx** [CleverRaven/Cataclysm-DDA#26362]
NORTH LILBOURN

"dda",
"filthy_morale",
"mutant_npcs",
"npc_traits",
"Cata++",
"more_locations",
"FujiStruct",
"Experimental-Z-Level",
"boats",
"cars_to_wrecks",
"blazemod",
"Tanks",
"no_flaming_weapons",
"more_classes_scenarios"

Game version: Unknown (7600+)
Operating system: Window 7 x64
Tiles or curses: Tiles

### Expected behavior
Had been playing game for sometime, things were going well.

### Actual behavior
Had been playing game for sometime, my follower become a duplicate, and it broke all immersion.

### Steps to reproduce the behavior
**Bad Luck.** Hard to define cause, usually linked to going up and down stairs. But I note in this experimental build the followers had great stair behaviour since the update.

North Lilbourn (DupeNPC).zip - https://ufile.io/2nrc6

STANWOOD;

"dda",
"filthy_morale",
"Cata++",
"mutant_npcs",
"npc_traits",
"more_locations",
"FujiStruct",
"Experimental-Z-Level",
"Urban_Development",
"boats",
"cars_to_wrecks",
"blazemod",
"Tanks",
"no_flaming_weapons"

Game version: Unknown (7600+)
Operating system: Window 7 x64
Tiles or curses: Tiles

### Expected behavior
Had just started a new game. After several Play Now! fails, found one I enjoyed.

### Actual behavior
During the first day, (pretty sure) the NPC follower became a duplicate. Decided to quit the game for good.

### Steps to reproduce the behavior
**Bad Luck.** Hard to define cause, usually linked to going up and down stairs. Load the save and see.

Stanwood.zip - https://ufile.io/k0zxb

__________

I have had many great time playing DDA, and the game continues in leaps and bounds. But now I will quit this game, because it was adversly effecting me, due to nature and how I let if effect me.

Happy bug hunting!

**Comment by xrandomuserx** [comment]
Experimental Z-Levels were used, perhaps this may cause the issues.

**Comment by Leland** [comment]
@xrandomuserx each of your uploads 404 now, unfortunately. Can you try re-uploading elsewhere, or (if they're small enough), uploading directly as an attachment on your GitHub comment?

Without a save and a method of reproduction, this will likely be closed soon otherwise.

**Comment by xrandomuserx** [comment]
Close this thread. I will upload another save when this issue occurs again. This will be due to Z-levels, in the newer experimentals the NPC wants to stand on my square, because it detects enemies below, also get attacked by shocker zombies through floors.

More people should play with NPC's, use Z-levels, and see if this errors occur for themselves.

This can be closed, as the files are long gone.
