### ISSUE TITLE
Mission state isn't saved on game saving

### ISSUE THREAD

**Issue by Trokinos** [CleverRaven/Cataclysm-DDA#26378]
playing on cataclysmdda-0.C-8069 gd6c01384

The starting shelter NPC asked me to join him and kill 100 zombies to make a "safe place" for people.
Was going to be hard as oddly the heavy majority of zombies i run into are though zombies instead of regular ones so it was more risky to fight them.
But thanks to a lot of crossbow bolts and that NPC surprising great strength and machette skill, we were slowly progressing.

Until we ran into a working military car ( a SWAT Truck actually) that i decided to use as a ram in order to get the zombies kill count faster without so much risks.
We ran into a large eductation center that was filled with zombies insane amount.

But to my surprise the car resisted mostly well enough and the kill count reached very high amount in no time.

So once the situation finally went under control, i stopped the car, we got out and i talked to the NPC and despite the kill count in zombies is way over the 100 required (279 zombies have been killed + 1 rat sewer)
screenshot :
https://i.imgur.com/EEm0rxD.gif

The NPC dialogue does not allow me to tell him the mission is complete.

**Comment by Trokinos** [comment]
Reading the bug report you linked i see my misconception.
It's not 100 zombies in general, it's 100 of an exact and specific "zombie" species (the normal type in that case), meaning that any other kind of zombies do not count despite they much more numerous.

I am playing on eternal summer, so i have no idea if the fact that the heavy majority of zombies are of the "though" type and i see very few normal ones around is linked to that.

**Comment by Night-Pryanik** [comment]
> It's not 100 zombies in general

In fact, it is. _Every_ zombie type (normal, shockers, brutes, hulks, technicians, crawling etc) is from `ZOMBIE` species. So after #23460 you can kill every type of zombies, not just ordinary zombies, to finish this quest.

How many zombies have you killed prior to accepting this quest? Just in case - you have to kill 100 zombies _after_ accepting the quest, total kill count prior to accepting the quest doesn't matter.

**Comment by Trokinos** [comment]
the mission was given before i ran into a working SWAT truck and found a large undead populated (hundred of zombies of many type) education complex, meaning the kill count exploded from then.

I'm then pretty sure the heavy majority of the kill list have been from atfr being given the mission.

So either the mission still require a specific variant of zombie to be killed, or if it takes in account any type of zombie it just does not work.

And now that the whole building is cleared, the total count is even higher :
[img]https://i.imgur.com/yJTp5cf.gif[/img]

With the mission still not acknowledged as completed by the quest giver (that is still fighting along my character)

**Comment by Night-Pryanik** [comment]
Tested right now on the latest experimental.

Modified the "Kill 100 zombies" mission to be "Kill 5 zombies" for testing purposes. Killed 5 different types of zombies.
![default](https://user-images.githubusercontent.com/11132525/47453088-dae4ba00-d7dc-11e8-9f2a-807499794021.png)

The mission is completed.
![default](https://user-images.githubusercontent.com/11132525/47453099-e637e580-d7dc-11e8-9fc7-fb99cd6a454d.png)

The only hypothesis I have is that maybe ramming zombies doesn't count for this case and you have to kill them by your own hand.

**Comment by Trokinos** [comment]
It's a possibility, if it's that case it's probably not the intended behaviour that rammed zombies do not count toward the mission if they're still listed in the kill count.

**Comment by Night-Pryanik** [comment]
Changed title to reflect the underlying issue.
