### ISSUE TITLE
It should be possible to sleep in a tent with a sleeping bag.

### ISSUE THREAD

**Issue by Dalenacio** [CleverRaven/Cataclysm-DDA#26374]
**Is your feature request related to a problem? Please describe.**  
In real life, every actual sleeping bag is insulated to allow users to sleep comfortably in tents. Often, the floor of higher quality tents is itself insulated. The end result is that in any camping scenario it is absolutely possible to sleep comfortably with any tent and sleeping bag.

In Cataclysm however, no such luck. Neither tents nor sleeping bags are insulated, which makes sleeping with them essentially impossible without adding a rollmat on top of all that gear, which feels absurd.

**Describe the solution you'd like**  
making either sleeping bags or tents insulated like in real life. Also, making sleeping bags give "a comfortable place to sleep" when worn or left on the ground.

**Describe alternatives you've considered**  
Adding a separate type of sleeping bag called an "insulated sleeping bag" which spawns instead of sleeping bags in the world (to represent industrial sleeping bags with inbuilt isolation) and behaves as described above, and leave the regular sleeping bag as-is. To add onto this, perhaps allowing the player to craft an insulated sleeping bag by combining a sleeping bag with a rollmat in crafting.

**Comment by FulcrumA** [comment]
@Shoes01 
That'd be interesting feature to have used in general. It would also allow heating of spaces the way it was done in the old times in some places in the world - where people were housing some cattle in their very homes and said cattle gave off heat.

**Comment by nexusmrsep** [comment]
I might work some kind of solution for this issue if you give me a bit of time.

**Comment by Treah** [comment]
yeah this is very frustrating as the game does not see the ground sheet and thinks your trying to sleep on the ground. I can confirm this as when I am trying to sleep it says "Its hard to sleep on this long grass"

**Comment by Night-Pryanik** [comment]
@nexusmrsep any luck on this?

**Comment by nexusmrsep** [comment]
Unfortunately not, the winds of life has blown me some other ways. Not planning to take a bite on this, at least for now.
