### ISSUE TITLE
There should be a way to repair damaged tents, and/or to disassemble/craft them.

### ISSUE THREAD

**Issue by Dalenacio** [CleverRaven/Cataclysm-DDA#26373]
At the moment, damaged tents are nothing more than an absolute dead weight. They are completely useless and can never be used to make anything useful. They can't even be disassembled into useful material. In short, they become garbage and stay that way forever.
![image](https://user-images.githubusercontent.com/12587061/47361130-7c7ee500-d6d1-11e8-8034-35cfd37ca786.png)
![image](https://user-images.githubusercontent.com/12587061/47361143-86084d00-d6d1-11e8-8569-18c59539f28b.png)
However, it should be possible to repair them much in the same way the Shelter Kit can be: just use the crafting recipe (damaged kit, sticks, leather patches, string) and you're good to go. There's no reason why tents shouldn't function the same way, with a recipe to turn a damaged tent into a working one again. 
![image](https://user-images.githubusercontent.com/12587061/47361074-5fe2ad00-d6d1-11e8-8d24-ba02b2dd7900.png)
On the topic of tents, it also makes sense that they should be disassembled into useful materials. An obvious example would be to make one large tent with the materials salvaged from several smaller ones, or something similar to the Tarp rain-catcher from More Survival Tools. After all this would probably be where the materials to repair tents in the first place might come from.
![image](https://user-images.githubusercontent.com/12587061/47361213-a9cb9300-d6d1-11e8-89bf-b5587ae04a88.png)

**Comment by FulcrumA** [comment]
Some simple repairs done in the abovereferenced PR. I also wouldn't mind alternate fixing methods as well as building stuff from scratch with things like tarpaulin, but it would first have to get in as we currently have none such in vanilla and I was somewhat wary about introducing some questionable substitutes for it like plastic bags or rags+plastic chunks+fire.
