### ISSUE TITLE
New item: Hiking Rucksack. Provides a way for the Camper to store his/her default stuff.

### ISSUE THREAD

**Issue by Xenomorph-III** [CleverRaven/Cataclysm-DDA#26371]
**Is your feature request related to a problem? Please describe.**  

I'm frustrated when I play as the Camper. They doesn't have enough room to store his starting inventory. On starting, the sleeping bag is worn. While you can take this off, it results in a "No room in your inventory for the sleeping bag. Drop it? (y/n)" which forces you to wield it. 

Since I am sure the bag is supposed to be in your inventory, the fact that the Camper cannot fit it in their inventory is a concern.

**Describe the solution you'd like**  

I seek to remedy that with a new piece of clothing: the hiking rucksack.

It holds 15.00L of items, between the Military Rucksack and the Backpack, and will have Encumbrance 12. Made of cotton and leather, it will have 4/4 bash/cut protection: slightly less than a leather backpack while being higher than a normal backpack. The volume is 3.00L, in between a normal backpack and the military rucksack.

Description:

>A large hiking backpack made of cotton and leather. Provides a fairly large amount of storage.

This will be given to the Camper and show up in houses, sporting goods shops and military surplus shops.

**Describe alternatives you've considered**  

I've considered giving the Camper a MOLLE Pack, but these and military rucksacks are reserved for the military.

**EDIT**

From [this](https://www.reddit.com/r/cataclysmdda/comments/9qmidh/camper_doesnt_have_enough_space_to_store_his_stuff/) Reddit thread:

 * A rucksack that has the ability to hold a sleeping bag/roll mat (in the same way that sheaths hold weapons, or a toolbelt holds tools)

* The sleeping bag should be activatable to roll it up and make it smaller with low cover, protection and durability and still be wearable. (needs knowledge of item_transform)

* 15 storage for 12 encumberance is too strong, survivor backpacks/rucksacks and such are 3/3 behind 6+ tailoring skill, I would say 17 encumberance for 15 storage sounds ok if you want it that sturdy as a 4/4

**Comment by l29ah** [comment]
Another idea would be to have a blanket that has a packed state that can be worn as strapped to torso.

**Comment by rubenpd** [comment]
@SirPendrak actually leather backpack is 11 encumberance 10 storage 6/6 leather only

**Comment by l29ah** [comment]
On Thu, Oct 25, 2018 at 03:26:13PM -0700, Alan Brady wrote:
> Just to throw this out there, I've been getting super into backcountry backpacking and have actually done some research into this.  There's not a huge difference between a "hiking backpack" and a MOLLE pack.  They're made out of similar materials and they both have internal frames.  The MOLLE pack is likely a bit more durable, but also significantly heavier.
> 
> I can't recall offhand the exact volume numbers for the other bags, but in real life, a 15L backpack will not cut it for an overnight trip.  You need *at least* a 30-35L pack to make an overnight work, and that's if you pack super light with a tarp/bivy bag instead of a tent.

I have a 50L daily backpack that weighs 1.5kg and a 110L backpack for two week long autonomous trips (or just hauling lots of stuff from a supermarket) that is 2kg. The biggest problem is the game balance.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments
