### ISSUE TITLE
Code::Blocks complaints on build

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#26382]
**Describe the bug**  
Code::Blocks complaints on several files on build process:

- https://github.com/CleverRaven/Cataclysm-DDA/blob/3d837de0b5b88e4159c71ddb0864f0343808f185/src/iexamine.cpp#L4128
```
||=== Build: Release in Cataclysm (compiler: GNU GCC Compiler) ===|
|In function 'void iexamine::smoker_options(player&, const tripoint&)':
|error: 'to_string' is not a member of 'std'|
|note: suggested alternative:|
|note:   'to_string'|
```

- https://github.com/CleverRaven/Cataclysm-DDA/blob/3d837de0b5b88e4159c71ddb0864f0343808f185/src/npctalk.cpp#L2004

- https://github.com/CleverRaven/Cataclysm-DDA/blob/3d837de0b5b88e4159c71ddb0864f0343808f185/src/npctalk.cpp#L2025

- https://github.com/CleverRaven/Cataclysm-DDA/blob/3d837de0b5b88e4159c71ddb0864f0343808f185/src/vehicle.cpp#L1618

- https://github.com/CleverRaven/Cataclysm-DDA/blob/3d837de0b5b88e4159c71ddb0864f0343808f185/src/vehicle.cpp#L1641

- https://github.com/CleverRaven/Cataclysm-DDA/blob/3d837de0b5b88e4159c71ddb0864f0343808f185/src/vehicle.cpp#L1643

5 similar errors with 
```
|error: 'stoi' is not a member of 'std'|
```

**To Reproduce**  
Try to build from the newest experimental with the Code::Blocks.

**Expected behavior**  
No errors on build.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 x64
 - Game Version: 0.C-8071
 - Graphics version: curses
 - Mods loaded: default only

**Comment by nexusmrsep** [comment]
With the default project file that comes with Cata?

**Comment by Night-Pryanik** [comment]
> With the default project file that comes with Cata?

Yes.

**Comment by Night-Pryanik** [comment]
You know, I update C::B to the latest version, and the problem is gone.
