### ISSUE TITLE
Request: new/more item categories to allow proper classification

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#26380]
**Is your feature request related to a problem? Please describe.**  
While going through the entire item for #26221 (weird classifications noticed in the wake of auto sort), I noticed some clear problematic trends and inconsistencies with item categories mainly:

- ARMOR vs CLOTHING weirdness (Nothing inherently wrong just a lot of odd classifications) 
- Lots of TOOLS aren't actually tools. (diamond matrix, growing blob parts)
- Inconsistent categorization of  "inactive _____" between TOOLS and WEAPONS
- Natural groupings of items in the OTHER category
- The OTHER category is **VERY** bloated

I believe the underlying issue here is that the OTHER and tools categories are being used as catch alls for things people can't properly classify with the existing item categories.

**Describe the solution you'd like**  
I believe adding the following item categories are necessary in order to allow for proper item classification.  This would be a massive QOL improvement for hoarding survivors not only due to the elimination of classification inconsistencies but also by eliminating the excessive bloat  in the TOOL and OTHER categories:

Category | Description | Reason | Example
---------- | ------------ | -------- | --------
Construction Materials | Larger materials, stuff traditionally used for construction | Reduce bloat + inconsistencies | Logs, 2x4, long stick, sand, cement
CONTAINERS | other's container subjection. Anything you put stuff in that isn't a vehicle part or worn |  Reduce searching (frequently used items). Reduce bloat in OTHER | bowls, open cans, bottles
DEPLOYABLES | Anything that gets placed when you use it | Reduce inconsistencies. Reduce bloat in tools. Eliminate how do I use issues. | inactive __hack, inactive robots, brazier 
PLANTS | Flowers and other traditionally non-food harvested items | Reduce bloat in OTHER.  Recent expansion of plant types creating a lot more plant items | birchbark, flowers
SALVAGE | Things that basically exist to be scrapped for parts | Reduce bloat in OTHER | Desk fan, broken anything
TIMED? | Things that take time (distilling, tanning, etc.) | Reduce inconsistencies. Reduce bloat in TOOLS | lit charcoal kiln, tanning leather hide
UNPROCESSED? | Stuff awaiting the player in order to become useful. (possibly combine with TIMED STUFF) | Reduce inconsistencies. Reduce searching. Reduce bloat in TOOLS | finished charcoal kiln, raw pelt, filled charcoal kiln

Some other categories that I think would be helpful but not required for proper classification:

Category | Description | Reason | Example
---------- | ------------ | -------- | --------
TRASH | stuff that has survivor has absolutely no way to use | Reduce bloat in OTHER.  Facilitate cleaning out useless items from stash | dead glowstick
CRAFTING TOOLS | Tools whos primary use is crafting opposed to say a crowbar | Separate tools with fundamentally different uses.  QOL item management.  Keep stuff only useful outside base separate from stuff that wants to stay in it.  |  Soldering iron, welder, tailors kit
PERISHABLE | Food that rots quickly (say <1 week) | Sort massive food pile. Prioritize use. Addresses #25744 | Milk, cooked creep
DRINKS | "food" that primarily provides hydration (PERISHABLE should be primary unless that is also split) | Sort massive pile of food in base. | Lemonade
BOOZE or ALCOHOL | Alcoholic drinks | Sort food pile.  Usually have negative quench resulting in different use from other food/drinks. | vodka, beer
RAW MATERIALS | CONSTRUCTION MATERIALS for rebar, cement 2x4s etc. SPARE PARTS for parts i.e. made parts you assemble and RAW MATERIALS for the rest | item management | piece of cloth, scrap metal
TRAPS | Thing that place well traps. (Otherwise they would end up in DEPLOYABLES | Item Management | shotgun trap 

**Describe alternatives you've considered**  
Make the rules for categorizing items (more?) clear/ obvious.  -> Wouldn't hurt and might even be called for after addition of new categories but doesn't fix the underlying issue nor does it help the ever expanding item bloat.

**Comment by Rivet-the-Zombie** [comment]
Sorting medical supplies apart from recreational drugs would be a nice change too.

**Comment by Theundyingcode** [comment]
Also: Equipment (wearable tools) like light amp goggles aren't really cloths

**Comment by mlangsdorf** [comment]
Consistently split off VEHICLE PARTS (wheels, floodlights, headlights, etc but probably not frames or sheet metal) from SPARE PARTS.

**Comment by Vzor-** [comment]
Perhaps subcategories could work better. If the catagory name was something like OTHER-SALVAGE then a search of c:OTHER would get a partial match on all categories that start with "other", and as such still yield the legacy results.

**Comment by Theundyingcode** [comment]
>  but probably not frames or sheet metal) from SPARE PARTS.

Sheet metal is currently a VEHICLE PART not a SPARE PART.  I'm currently fixing oddball item categories and it's on my "sketchy ask about" list along with solar cells.

**Comment by curstwist** [comment]
Rotton food pile?  Wouldn't be used in initial sort but could be useful.

**Comment by mlangsdorf** [comment]
Sheet metal has enough general utility to be in SPARE PARTS.  Frames could go either way.  I think frames are either vehicle parts or components of vehicle parts like crafting rigs, but I could be forgetting stuff.

**Comment by mlangsdorf** [comment]
Sheet metal has enough general utility to be in SPARE PARTS.  Frames could go either way.  I think frames are either vehicle parts or components of vehicle parts like crafting rigs, but I could be forgetting stuff.

**Comment by Jalu1** [comment]
So, Someone said that there are maybe 3400 items in the game, and 20 categories currently, so average 170 items per category. To get it to a more reasonable amount, we should make >8 new categories, and resort the items.

**Comment by Theundyingcode** [comment]
> To get it to a more reasonable amount, we should make >8 new categories, and resort the items.

In a nutshell yeah but it's not just about "reasonable amounts" as the  lack of categories is causing items to have inconsistent and/or nonsensical classifications.

**Comment by Jalu1** [comment]
Sorry, that was just some input I had. I think I know how to add the new
categories, but I would need a definite list.

**Comment by Theundyingcode** [comment]
Since I started this whole thing I don't mind making a formal list of item categories.  I'd like to wait another day or two in order to collect input/feedback before finalizing the list though. 

Might as well take this as an opportunity to create an item_catagories.md for the docs and more formally define what goes where.

**Comment by Shoes01** [comment]
Regarding Sheet Metal having two uses, would allowing items to appear in two categories be the opening of a can of worms?

**Comment by Theundyingcode** [comment]
> Regarding Sheet Metal having two uses, would allowing items to appear in two categories be the opening of a can of worms?

It would completely break the whole concept of sorting by item category.

**Comment by SunshineDistillery** [comment]
TIMED/UNPROCESSED. Maybe "transitional" would be a clearer name. 

What will the default symbols for new types be? I would think that having overlap, like using % for different food types, would be totally fine.

**Comment by Theundyingcode** [comment]
I like transitional.

> What will the default symbols for new types be?

To my knowledge symbols are a property of types.  We are not talking about adding new types but categories.

**Comment by Theundyingcode** [comment]
I have created a spreadsheet with the new proposed list of categories and there formal definitions.  Since I found out that categories are made in JSON i've gone ahead and made them and will have the PR up once I  finish the ITEM_CATEGORIZATION.md.

I have no clue what to set the `sort_rank` fields to though.

[item category definitions.xlsx](https://github.com/CleverRaven/Cataclysm-DDA/files/2521417/item.category.definitions.xlsx)

**Comment by TheRealGunShy** [comment]
Just ran into issues with sorting things today. Glad you brought all this up.

My first thought was having a CONTAINERS category. Then possibly subcategories; EMPTY, COOKING, ETC.

Alternatively, keep the TOOLS category as-is, but at subcategories based on qualities (cooking, wood-cutting, etc.)

**Comment by Theundyingcode** [comment]
I'm testing out new categories and how they will affect things... Just got a little distracted after I was given witcher 3.

**Comment by Phenomphear** [comment]
Don't forget corpses! They should have their own category. Much easier to sort and look for pulped and non pulped when "looking" / item list

**Comment by TKTKO** [comment]
Keeping the existing categories and adding new subcategories (FOOD, P.FOOD as example) makes sense.
TOOLS into categories for the kind of work they do? METALWORKING, FOOD PREPARATION, REPAIR?
FOOD separating out (typically) inedible things INGREDIENTS?
CLOTHING/ARMOR into separate layers? OUTERWEAR, MIDDLEWEAR. Or location covered? HEAD contains items that cover Head and Eyes, Mouth? Torso contains items that cover Torso but also additional locations. ARMOR by highest resistance? ENVIRONMENTAL ARMOR, BASHING ARMOR.
WEAPONS/GUNS into BASHING, CUTTING, PIERCING, ONE-HANDED, TWO-HANDED, POWERED.

**Comment by KorGgenT** [comment]
now that loot zones are jsonized, it should be easy to delegate this task. my question is this: what needs to be done still in order to close this issue as a 0.E milestone?

**Comment by TKTKO** [comment]
Is it possible to indicate a subcategory like Clothing and F. Clothing, Food and P. Food?

**Comment by KorGgenT** [comment]
those would require just a tad more C++, but should actually be trivial to implement.

**Comment by SavageBishop** [comment]
Is there a list on what still needs to be added?
