### ISSUE TITLE
"Harvest list mon_zombie_necro has invalid drop(s): necro_head" on Character Creation (PR 8073)

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#26401]
**Describe the bug**  
 DEBUG    : Harvest list mon_zombie_necro has invalid drop(s): necro_head
 
 FUNCTION : static void harvest_list::check_consistency()
 FILE     : src/harvest.cpp
 LINE     : 122

**To Reproduce**  
Error appears when loading "Harvest lists" on creating a character to a newly generated world with parameters configured below. Error does NOT appear on Quit > Restart > Load save.

**Screenshots**  
![mon_zombie_necro](https://user-images.githubusercontent.com/43046067/47510514-49119700-d846-11e8-8b3e-fb0c328edfe2.png)

**Versions and configuration(please complete the following information):**
PR version 8073.

Mod List:
  "dda",
  "craftgp",
  "safeautodoc",
  "makeshift",
  "More_Survival_Tools",
  "crazy_cataclysm",
  "alt_map_key",
  "Mining_Mod",
  "boats",
  "deoxymod",
  "necromancy",
  "no_rivtech_guns",
  "no_olg_guns",
  "no_flaming_weapons",
  "no_medieval_items",
  "more_classes_scenarios",
  "manualbionicinstall",
  "sleepdeprivation",
  "StatsThroughSkills",
  "No_Fungi"

**Additional context**  
Savegame attached: [Booly.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2515610/Booly.zip)

**Comment by ZhilkinSerg** [comment]
`necro_head` comes from `salvaged robots` mod. Did you enable it?

**Comment by SunshineDistillery** [comment]
I figured out how to reproduce this:
1. Create a new world with modular turrets mod
2. Quicksave and use the debug menu to quit to the title screen
3. Create a vanilla world with no mods
4. Try to make a character in the vanilla world

So, something isn't getting cleared from memory properly for the new world. I don't know if there is anything I can do in the mod to fix that.

**Comment by Theundyingcode** [comment]
> Quicksave and use the debug menu to quit to the title screen

Why on earth would you do that?  Use 'S' to save and exit like a normal person.

**Comment by SunshineDistillery** [comment]
I was looking for bugs, not acting like a normal person.

**Comment by Night-Pryanik** [comment]
It clearly states that using the debug menu to quit may cause all kinds of weird issues, so there's no surprise there _is_ bugs.

**Comment by ZhilkinSerg** [comment]
I think I had that issue with other mods several times, though I don't remember using debug menu.

**Comment by Khataro** [comment]
Got the same problem when i was playing around with mods. The problem was that i deactivated the mod "Modular Turrets" and therefore the mod "Salvaged Robots" got deactivated too. Deactivatíng the mod which depends on the other one before solved the problem (1. deactivate Salvaged Robots, 2. deactivate Modular Turrets). Hope that helps and sorry for my bad english ;-)
