### ISSUE TITLE
Redundant Faucet Menus

### ISSUE THREAD

**Issue by hbhollandlive** [CleverRaven/Cataclysm-DDA#26406]
**Describe the bug**  
Small QoL thing, I've noticed that using a faucet to "Fill a container with water" calls up the same menu for examining water sources: "Consume it," "Pour into a container," and "Pour on the ground." But two of those options just repeat the "drink" and "fill container" options from the faucet menu, and I'm guessing (unless I'm playing this game wrong) that most people aren't dumping their potables on the ground very often. Also, in cases where the faucet is part of a kitchen unit inside a vehicle, it doesn't really make sense to be able to dump water on the ground from an interior faucet. 

The "Have a drink" faucet option just lets you drink without a second menu; could the "Fill a container" option be made to take you directly to the list of available containers? 

**To Reproduce**  
1. [I]nstall a tank on a vehicle frame; fill with clean water.
2. [I]nstall a faucet.
3. [E]xamine the frame with the faucet; choose the option "Fill a container with water."
4. See the same option repeated in the next menu.

**Expected behavior**  
It would be nice to only have to choose the option once instead of twice, considering that refilling your canteen is a pretty regular activity.

**Screenshots**  
![faucetmenu](https://user-images.githubusercontent.com/43996249/47567973-d95ee300-d8fd-11e8-9145-9b3c49f35d21.png)

**Versions and configuration(please complete the following information):**
-current as of 8073

**Comment by jbytheway** [comment]
I agree with this annoyance, but I also think it's important to maintain the ability to empty the tank onto the ground; it might be the only way you can get the liquid out if you want to repurpose the tank.

**Comment by rubenpd** [comment]
> I agree with this annoyance, but I also think it's important to maintain the ability to empty the tank onto the ground; it might be the only way you can get the liquid out if you want to repurpose the tank.

the only way is using a rubber hose, since the faucet let's you access clean water only

**Comment by jbytheway** [comment]
> the only way is using a rubber hose, since the faucet let's you access clean water only
Ah yes, good point.

**Comment by jbytheway** [comment]
I looked into this a bit more.  It turns out that there are two other things that second menu can offer, but normally doesn't.  You can fill other vehicle tanks or kegs.
![cata-liquids](https://user-images.githubusercontent.com/52664/47738439-0d723500-dc6b-11e8-8cd0-c9050d63ceaf.png)
I think the right fix is to get those extra options into the first menu, but that will require some careful changes...

**Comment by alanbrady** [comment]
> I think the right fix is to get those extra options into the first menu, but that will require some careful changes...

An easier option may be to change the first menu into one option "Use faucet" and then just have the second menu.
