### ISSUE TITLE
Not displaying recipes that are in books, EVEN if said book(s) are in the inventory.

### ISSUE THREAD

**Issue by UNOwenWasMe** [CleverRaven/Cataclysm-DDA#26404]
Nature of bug: have book with recipes nearby and/or in inventory, yet some of those recipes are not visible or displayed in the list of crafting recipes.

Reproduce:

By reading the book "DIY Compendium", you gain the recipe for the item Telescopic Cantilever (amongst others). If your skill in mechanics is lower than 4, this recipe will not show itself, even though on the recipe itself it only says "Required Skills: fabrication (2)", "Difficulty: 2". Nowhere is the indication that mechanics level 4 is needed, nor is there any way to know before that point.

I expected that the recipe would show itself in the list when the book was nearby or in the inventory. This way we can see what skills and items we have or lack in order to make our crafts.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-33477-g5cf860b
 - Graphics version Tiles
 - Mods loaded:

DDA
Disable NPV Needs
Filthy Clothing
Simplified Nutirtion
Craftable Gun Pack
Makeshift Items Mod
More Survival Tools
Vehicle Additions Pack
Tanks and Other Vehicles
StatsThroughSkills

**Comment by Mecares** [comment]
Working as intended, some books do not contain literal recipes but just some hints that can be used to design the desired recipe if the character is skilled enough.

**Comment by Theundyingcode** [comment]
This is an issue of player feedback.  I have noticed a lot of people being confused by this.

**Comment by FrozenSnowFox** [comment]
The lack of feedback from the game on this is honestly quite annoying.  Despite having the recipe book on hand I've had to look up quite a few recipes on the item browser website to find out why I can't craft them.  Some recipes even vary between skill requirements depending on the book.  For instance the Vehicle Welding Rig is listed as requiring level 5, 6 or 8 mechanics depending on which book has the recipe.  There really needs to be a way to view this information in the game.

**Comment by kevingranade** [comment]
> Working as intended, some books do not contain literal recipes but just some hints that can be used to design the desired recipe if the character is skilled enough.

Correct

**Comment by Zireael07** [comment]
Recipes vs hints needs to be communicated clearly to the player. It isn't and that is the point of this issue.

**Comment by jbytheway** [comment]
An easy change would be to add something to the book description saying e.g. "To access all recipes from this book requires fabrication 4, ...".
Making the recipes appear in the crafting GUI would probably be a much more involved change.

**Comment by kevingranade** [comment]
> "To access all recipes from this book requires fabrication 4, ...".

I would be fully behind a more generic "To access all content from this book requires fabrication 4, ...".

This is butting up against this being intentional, the existence of these recipes is hidden until the player reaches a certain skill level.
