### ISSUE TITLE
Gross asymmetry between Science and Military ID cards?

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#26408]
**Is your feature request related to a problem? Please describe.**  
Science ID cards are plentyful, but have only a single possible use - unlocking lab entrances. Most labs then give you an ID card back. As a result, the player is likely to end up with tens of science ID cards they have no use for.
Military ID cards, on the other hand, are very rare, since the don't spawn in mi-go map specials. At the same time, a single military bunker can ask for as many as 6 cards. As a result, the player is always short on military IDs.

**Describe the solution you'd like**  
In my opinion, science and military IDs should be made more similar. So, either:
1) Science ID cards should spawn a lot less and have more uses (mutagen and bionic vaults inside labs could ask for cards rather than having a console).
or
2) Military ID cards should only be used to enter military bunkers, while the compartments inside are locked behind simple consoles (the way labs work currently).

**Describe alternatives you've considered**  
The issue can be ignored since it doesn't really break anything in the game.

**Additional context**  
![ids](https://user-images.githubusercontent.com/44502845/47573824-7191b200-d968-11e8-8c4c-810d570665b7.png)

**Comment by Lorith** [comment]
I'd suggest going with the first option - I had plans for some similar things myself, but lack of motivation is a horrible thing and has been stopping me.  Another place it could potentially be used would be the containment area, as that could be where the scientists were testing things on people.

**Comment by vache** [comment]
I'm in favor of the first option as well.  I like the idea of having military bunkers be a "choose your reward" type situation, and think that would work well with labs too.

**Comment by Fris0uman** [comment]
Is making both rare but re-usable an option ? It s hard to understand why cards disapear when you use them on card reader.

**Comment by Amoebka** [comment]
I think making them reusable is a bad idea. That way any card you find after the first is completely useless. I quite like their current "prize coupon" function, I just think the numbers should be tweaked and more uses for science IDs implemented. As for why they disappear, single use passwords and such exist.

**Comment by y2s82** [comment]
I think reusable cards has some merit, if we introduce more types of cards.  Military and Science cards may be separated into different security ratings that allows them access to different things.  Lower security cards may be more common but only allows you access to, say, doors to minor labs and not even their internal compartments.  Highest security cards could be extremely rare but allows full access to any corresponding area.  I think this would make more sense to how it works in real life.

Or the first option :)

**Comment by kevingranade** [comment]
The reason the cards disappear is as has been speculated, to keep finding a single card from being the end of looking for cards.  If instead of only having two card varieties, there were a range of permission levels, then it would be reasonable to change them to keep working.

Having said that, please do open-ended discussion like this on the forums at discourse.cataclysmdda.org
