### ISSUE TITLE
Invincible zombie

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#26403]
**Describe the bug**  
Zombie staying in perfect health despite damage.

It is rare but happened to me twice, both with high armor value zombies, once an armored zombie, once a zombie soldier. 
I was shooting at a zombie soldier with my 45 acp rounds, and it is doing damage.
![image](https://user-images.githubusercontent.com/10649716/47534153-87717b00-d873-11e8-8f7a-fa854a796eea.png)
But it just won't die after i emptied clips after clips at it. examining the zombie soldier shows it to be in perfect health.

I spawned a LAW launcher which killed it just fine though.

build 8072

**Comment by Theundyingcode** [comment]
I was thinking earlier that zombie soldiers seemed to be a lot tougher than I remember and that they seem to take a lot of beating before their health drops.  I had dismissed it as just me overthinking things but seeing this issue makes me wonder....

**Comment by Soyweiser** [comment]
Odd, zombie soldiers have 100 hp, so it should be dead. Either the message is wrong (and there is a new damage reduction step later) or you are running mods.

**Comment by aierce** [comment]
The problem is zombie soldier isn't taking ANY damage. It says in perfect health (until I shot it with LAW).

**Comment by Soyweiser** [comment]
Aha, odd, I shot at a zombie solder with an m240 and it did take damage. Wonder what is causing it.

**Comment by aierce** [comment]
Yes. It only happens rarely.

**Comment by kevingranade** [comment]
No way to reproduce or confirm and no reports of similar things happening.
