### ISSUE TITLE
Explosive ammo doing less than 1 damage teleports back to your feet before exploding

### ISSUE THREAD

**Issue by Lorith** [CleverRaven/Cataclysm-DDA#26415]
**Describe the bug**  
Explosive ammo (at least using custom explosion, others untested) will explode on your feet no matter where you shoot if the ammo + gun combo results in 0 direct damage.

**To Reproduce**  
1. Drop attached file into jsons.
2. Open debug wish list, search for test, add all three test guns and a few of each test ammo.
3. Give self debug invincibility, attempt firing each combination of gun and ammo into the distance.

**Expected behavior**  
Even if I shoot a pillow at you, if it has explosives in it, it should explode where I shoot it, not magically teleport back to my feet before exploding.

**Additional context**  
File with test items: https://cdn.discordapp.com/attachments/252368751016542218/505710341049679892/test.json

**Comment by kevingranade** [comment]
"Modding doesnt work tge way I want it to", is not a bug.
