### ISSUE TITLE
Trying to spawn monsters remotely has lots of insanity going on

### ISSUE THREAD

**Issue by Lorith** [CleverRaven/Cataclysm-DDA#26418]
**Describe the bug**  
1. 'place_monster' places monster on top of player, not on top of location it was activated at
2. remotely activated 'place_monster' is prone to spawning monsters forever
3. If not done in a very unexpected way, you get more than one monster even if you avoid continual spawns
4. remotely activated 'place_monster' hits you with the 'moves' timer, which can potentially result in game crashing, and even without that lead to insane swarms before you can stop them.

**To Reproduce**  
1. Place linked file into jsons and use debug wish menu to search for manhack, pick up manhack launcher and one of each packaged manhack.
2. Fire them max range away from yourself, starting with 1, then wtf, then halp.
3. One manhack shows up, then a 'slowly' expanding swarm, then the game locks up on the last one.

**Expected behavior**  
Like a grenade, go to location projectile hits, spawn one monster on that location, without consuming your character's time, then projectile stops existing.

**Screenshots**  
https://cdn.discordapp.com/attachments/484134288942563338/505759608762007573/unknown.png

**Additional context**  
Items used to test: https://cdn.discordapp.com/attachments/484134288942563338/505759737816678400/test.json

**Comment by kevingranade** [comment]
"Modding doesnt work the way I want it to" is not a bug.
