### ISSUE TITLE
Unable to put items with charges into cargo dimension, other items are ok

### ISSUE THREAD

**Issue by Zetsukaze** [CleverRaven/Cataclysm-DDA#26423]
**Describe the bug**  
Moving items into a cargo dimension works, but moving items with charges like ammo/duct tape gets a message stating the destination is full.

**To Reproduce**  
1. Have a cargo dimension on a vehicle
2. Move an item in
3. Move some ammo in

**Expected behavior**  
Both should be able to work if there is enough space in the cargo dimension

**Screenshots**  
Before moving the gun:
![beforemovegun](https://user-images.githubusercontent.com/1698993/47613265-fd215500-dac6-11e8-893b-3afb6b41faf9.PNG)

After moving the gun:
![aftermovegun](https://user-images.githubusercontent.com/1698993/47613269-04e0f980-dac7-11e8-9d74-506b46f5da75.PNG)

Trying to move the ammo:
![tryingtomoveammo](https://user-images.githubusercontent.com/1698993/47613272-0f02f800-dac7-11e8-89aa-cf939e8eca6b.PNG)

**Versions and configuration(please complete the following information):**
- First noticed on build 8080, downgraded to 8078 with the same issue. 8076 has no such issue. Suspect it has to do with PR Fix truncated per-charge volume (#26031) in build 8077.

**Comment by BBlankie** [comment]
It (maybe) rejects items that stacks as amounts like "duct tape (200)", "scrap metal (52)" and "plant fiber (10)", Items that has charges like "soldering iron (20)" or normally stacked like "3 science ID cards" can be stored.

**Comment by jbytheway** [comment]
It's caused by an integer overflow here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/0ab0a2b417df75907fd65cfe3141aa236920c3d1/src/item.cpp#L533-L539
`vol` is 250000000 for an empty cargo dimension and `type->stack_size` is often about 100; anything bigger than 8 causes an overflow here.

**Comment by kevingranade** [comment]
Just cast each of them to a long?
