### ISSUE TITLE
Intravenous Needletip bionic should allow to inject mutagen serums.

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#26426]
So the Intravenous Needletip replaces the syringe for drugs like morphine and other injectable drug, but i can't inject serums.

![image](https://user-images.githubusercontent.com/44106380/47614077-b2a6d500-dad4-11e8-8c48-0a5a30842cc7.png)

![image](https://user-images.githubusercontent.com/44106380/47614082-d36f2a80-dad4-11e8-8c6d-4605596a87f5.png)

Can someone correct this?

**Comment by nexusmrsep** [comment]
@Xhuis just a heads up.

**Comment by Xhuis** [comment]
When did you last update? This was patched a while ago.

**Comment by nexusmrsep** [comment]
I've confirmed it just now on most recent master available. Code looks good at first glance, so I couldn't pinpoint the problem.

**Comment by nexusmrsep** [comment]
What I've spotted: 
I've noticed that if you examine the serum and then activate it it will work. 
Eat menu shows message as above. [A]ctivate doesnt show serum on the list. Even in [e]xamine it looked like it wouldn't work, but it worked.

**Comment by BBlankie** [comment]
Forgot to post the build
![image](https://user-images.githubusercontent.com/44106380/47645452-0cc69980-dbac-11e8-8809-72059a03580f.png)

**Comment by Heaper327** [comment]
@woutershep You can also "E" and select the disinfectant, but it just doesn't appear in the "a"ctive list

**Comment by Pupsi-Mupsi** [comment]
**I need someone to confirm this.**

To me it looks like **line 38** in **data\json\items\comestibles\mutagen.json** should be **"tools_needed": "syringe"**.
![grafik](https://user-images.githubusercontent.com/44737997/50430724-03189400-08c6-11e9-96f9-23e8cefe089d.png)

Why? Well, take a lokk at **\src\iuse_actor.cpp** line 544 f.
![grafik](https://user-images.githubusercontent.com/44737997/50430839-a9649980-08c6-11e9-8051-3deca3a59c50.png)

I've tested the change with my build and it worked fine:
mutagen - new.json (new file)
mutagen - old.json (original file)
[mutagen.json.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2709373/mutagen.json.zip)

Just change the name back to **mutagen.json**.
At least this should fix the mutagen bug.

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> @nexusmrsep I have noticed this before with disinfectant. i have a 'small bottle of disinfectant (5)' when i press 'a' its not in the list. but if i go to it with 'i' and then 'a activate' it does activate and i can select a limb. maybe its related to beeing in a container?

@Heaper327

Would you mind testing the disinfectant issue with the current build.
Seems to work fine (all of the above work fine / 'a', 'E' and inventory -> activation/use).
