### ISSUE TITLE
"Find lost dog" mission dialogue tree is broken

### ISSUE THREAD

**Issue by MrMisterer** [CleverRaven/Cataclysm-DDA#26425]
**Describe the bug**  
When you agree to the mission and fail, the dialogue with the NPC who gave you the mission will be:
a: I'm sorry... I failed.
b: [LIE: x%] Not yet.

Doesn't matter which you choose or the lie percentage, the result is the same, (s)he gets angrier because you failed. However, the next time you talk to the same NPC, the dialogue tree pops up again, and when you say you've failed, (s)he gets even angrier. So you get stuck in a perpetual cycle and eventually, the NPC turns hostile. 

**To Reproduce**  
1. Spawn an NPC
2. Befriend the NPC
3. Give him or her the "Find lost dog" mission using debug
4. Accept the mission
5. Kill the dog or let the dog die.
6. Come back and talk to the NPC and the cycle will start and it will not end until the NPC is hostile.

**Expected behavior**  
Clicking the "I'm sorry... I failed." option should end the mission for good, never repeating the dialog tree again since that should inform the NPC that the dog is dead.
The lying option is the way to try and stall the lost of reputation.

**Screenshots**  
The dialogue:
![image](https://user-images.githubusercontent.com/44541918/47613503-14f6da00-dac3-11e8-97ce-70ab1f7a7a77.png)
No matter whether you choose A or B (even if it was a successful lie), the next time you talk to the NPC, this screen will appear again and you are forced to choose again.

**Versions and configuration**
 - OS: Windows 10 
 - Game Version: 0.C-33639-gd1bba3b
 - Graphics version: Tiles-ChestHole32
 - Mods loaded: None

**Additional context**  
Talk to the NPC, then do it again, and you'll understand

**Comment by xrandomuserx** [comment]
"Some dog owners love their four-legged friends so much that they treat them like they would a child — and sometimes even say they prefer them to some friends and family." Source - [](https://bit.ly/2ESkjx2[](url))

I am not surprised by this, people will not forget that you killed their dog. 
You could always sell them an activated explosive device, so they can forget the problems of their life.

**Comment by Night-Pryanik** [comment]
> You could always sell them an activated explosive device, so they can forget the problems of their life.

Not an option anymore after #22775.

**Comment by mlangsdorf** [comment]
The clear_mission effect wasn't be applied in the failure talk topic. Super simple change.
