### ISSUE TITLE
Sound does not play on macOS Mojave

### ISSUE THREAD

**Issue by perryprog** [CleverRaven/Cataclysm-DDA#26422]
**Describe the bug**  
There is no sound (besides the clicking on the main menu when you switch buttons) in the game, and there is an error in that probably has something to do with entitlements (I think).
```
2018-10-27 23:16:15.800612-0400 cataclysm-tiles[70129:15528946]   saved enable noise cancellation setting is the same as the default (=1)
2018-10-27 23:16:17.247138-0400 cataclysm-tiles[70129:15528946] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=70129
2018-10-27 23:16:17.247280-0400 cataclysm-tiles[70129:15528946] SecTaskCopyDebugDescription: cataclysm-tiles[70129]/0#-1 LF=0
```

**To Reproduce**  
1. Compile last git version of CDDA with `-DTILES=ON -DSOUND=ON`
2. Start
3. Check console for logs, and check for any sound and music

**Expected behavior**  
Sound and music work fine, and there is no errors in the console.

**Versions and configuration:**
 - OS: macOS Mojave, 10.14
 - Game Version: 0.C-33637-ga6977349b3
 - Graphics version: Tiles
 - Mods loaded: Whatever the default is for git

**Additional context**  
I am running this through CLion and CMake, but there are no other issues with the game besides this so I doubt it's related.

**Comment by AMurkin** [comment]
What soundpack did you use?

**Comment by perryprog** [comment]
@AMurkin Basic. It's the only one listed in options for me.

**Comment by AMurkin** [comment]
This is the only sound in that soundpacks and currently CDDA have no another included in base build.
Windows launcher have some links: https://github.com/remyroy/CDDA-Game-Launcher/blob/master/data/soundpacks.json
And probably official forums too.

**Comment by perryprog** [comment]
Alright, I've tried installing RRFSounds from soundpacks.json. I changed the soundpadck CDDA uses in options, but there's still no sound or music.

**Comment by kevingranade** [comment]
User errot
