### ISSUE TITLE
No ovens in the home improvement superstore

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26434]
I came to buy an oven but there were none of them!

**Comment by Theundyingcode** [comment]
Store I worked at had fridges, washers, dryers and, small appliances but they didn't have ovens...  But it was also an electronics store so there's that.

**Comment by Nymall** [comment]
To be fair, there are also no Fridges or other appliances. I know you can easily get ranges and built-in ovens in places like Home Despot and Lowes, so it would stand to reason that these should also be included.
