### ISSUE TITLE
Moving from deep water to bridges needs to be MUCH more difficult

### ISSUE THREAD

**Issue by sigmareaver** [CleverRaven/Cataclysm-DDA#26447]
Zombies can easily get out of deep river water, and onto bridges, even though they sink in water. Maybe make an exception for swimmers if you want, but I want to see this implemented, because I just had a zombie dog (how does a dog even climb up the side of a bridge?) This could be an extension of body parts as well. If a creature doesn't have some sort of grasping body part (hands, tentacles, etc), it should have a lot of trouble climbing.

Implementation shouldn't be too hard I think. It's just checking for a transition from deep water to whatever a bridge is made out of (asphalt, railing, etc). This won't affect shores since they are shallow water.

**Comment by RosieMcCattail** [comment]
That's just a workaround. Real bridges, of course, allow you to swim under them, but you won't get onto them from water, unless your arm tentacles are like 20 feet long.

**Comment by tinukedaya** [comment]
This might be solved by implementing the idea mentioned in the bottom part of the #25372 issue. Dropping the rivers to z-level -1 should make it impossible to simply hop on the bridge, right?
