### ISSUE TITLE
"Salvageable Robots" mod Burning Eye robots don't actually fire

### ISSUE THREAD

**Issue by darktoes** [CleverRaven/Cataclysm-DDA#26448]
**Describe the bug**  
The Burning Eye robot doesn't actually use it's laser weapon. It just runs up to things and sits in front of them, presumably trying to melee attack.

**To Reproduce**  
1. Craft/spawn an Inactive Burning Eye robot.
2. Activate it.
3. Move near some enemies, ensuring it follows you.
4. Watch it run up and try to make friends, be bewildered as you are denied the fiery death beam minion you were promised.

**Expected behavior**  
The robot should fire it's laser, because it says it has a laser, the recipe requires a laser, and it has a laser attack defined in the JSON file.

**Versions and configuration(please complete the following information):**
 - OS: [Windows 7]
 - Game Version: [Valid as of version 8065, but I don't see anything in the changelog to suggest it's been fixed since then]
 - Graphics version: [Tiles]
 - Mods loaded: [ dda, modular_turrets, salvaged_robots. A bunch of others, but they shouldn't affect it.]

**Additional context**  
Adding "PATH_AVOID_DANGER_1" to the flags field, copying the roboguns.json file from Modular Turrets into Salvageable Robots, AND setting the laser attack's cooldown to 4 from 20 fixed the issue. I'm not certain what the actual issue is, but I wasn't able to get it to fire it's weapon at all without all three changes.

**Comment by korick** [comment]
hi need help - Second question for translation
https://github.com/SunshineDistillery
Salvaged Robots - this new mod for robots, which one word use in translation: synonym
salvaged -> saved or captured or trophy or recovered or mined or reconstructed
example:
broken utility robot
"A broken utility robot, now limp and unmoving. Could be gutted for parts or crafted into a salvaged robot."

Also in lines from this mod, how translate: synonym
floating - swimming or soaring or crawling (creeping)
example:
floating lantern
"A salvaged drone repurposed into a mobile lightsource."
floating heater
"A salvaged eyebot repurposed into a floating space heater. It emits a constant jet of warm air to heat an enclosed space."
Rus Team

**Comment by darktoes** [comment]
This is NOT the place for that, but...

In this case, salvaged means you found a broken one and repaired it to working order with non-standard parts. It's not as good as it was, but it works. Probably made out of parts from multiple destroyed/damaged things. Imagine if you took two broken cars and took half the parts from one to repair the other. Your synonym would be recovered or reconstructed.

Floating means flying at a low height in this instance. Like a drone flies along, or some insects. It's maintaining a height above the ground, and not moving around much. Your synonym would be soaring, but at a low height.

**Comment by korick** [comment]
thx for watching

**Comment by SunshineDistillery** [comment]
> Adding "PATH_AVOID_DANGER_1" to the flags field, copying the roboguns.json file from Modular Turrets into Salvageable Robots, AND setting the laser attack's cooldown to 4 from 20 fixed the issue. I'm not certain what the actual issue is, but I wasn't able to get it to fire it's weapon at all without all three changes.
I'll check it out. Probably something in the roboguns.
