### ISSUE TITLE
Game Crash When Driving at Night with Headlights On

### ISSUE THREAD

**Issue by fragsnruins** [CleverRaven/Cataclysm-DDA#26440]
**Describe the bug**  
The game crashes to desktop any time I drive a vehicle with its headlights on at night. It does not happen immediately. I have not been able to drive in this manner for any great length of time without triggering the crash.

**To Reproduce**  

1. Start the game and find/spawn a vehicle that has headlights.
  a. Type of vehicle does not seem to matter, I've had this crash with solar car, pickup truck, and humvee.

2. Wait until night, when visibility is bad and you can't see far.

3. Drive the vehicle around with its headlights on. Bug should occur within 50 turns.
  a. It may be necessary to follow a road a ways so as to activate different parts of the map.
  b. This behavior always occurred on already-generated and uncovered parts of the map.
  c. This behavior seems most likely to happen when driving near forests and swamps.

**Expected behavior**  
I expected to be able to travel at night via vehicle with the aid of its headlights. Driving during the day (with the headlights off--I've never tested headlights on during the day) does not cause this issue.

**Screenshots**  
None.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.C-33651-gbabb58f
 - Graphics version: Tiles version downloaded, but tiles disabled in options.
 - Mods loaded: Dark Days Ahead, Filthy Clothing, Extended Realistic Guns, Icecoon's Arsenal, Makeshift Items Mod, Medieval and Historic Content, More Survival Tools, Modular Turrets, Mutant NPCs, NPC Traits, Vehicle Additions Pack, Classes and Scenarios Mod

**Additional context**  
This crash behavior occurred in two prior versions as well (both released in October), but I do not have their version numbers, unfortunately.

**Comment by mlangsdorf** [comment]
Can't reproduce with a tiles enabled build.  I spawned a vehicle and drove back and forth through a forest for 30 in-game minutes with the headlines on, at night, without a crash.

**Comment by fragsnruins** [comment]
Thanks for checking into this. The problem persists as of version

0.C-35367-g69312c0

within the exact same computer environment. This time, though, I had the presence of mind to package up the save and the latest core dump for your reference in an attachment. Here is a google drive link in case the upload doesn't work for whatever reason:

https://drive.google.com/open?id=1wwpYgb6fWF0Txx-GFGAEiJQmSiroD6bB

To recreate the issue, enable the headlight on the motorcycle you're on/near and drive eastward into the field. The game should CTD with a segfault in a fairly short amount of turns. If you reach the mansion to the east without a crash, then we'll probably have to chalk this up to something entirely on my end.

Thanks again.

**Comment by BrettDong** [comment]
Unable to reproduce on macOS after 10 retries. Tiles version with tileset disabled. Probably it's related to compiler/environment, or I am too lucky?

**Comment by ZhilkinSerg** [comment]
Is it still crashing on latest game version?

**Comment by kevingranade** [comment]
Punting from the release since we don't have a reproduction case.

**Comment by ZhilkinSerg** [comment]
Cannot reproduce on latest master. Please inform us if you still have same issue.
