### ISSUE TITLE
Can't get meat from butchering.

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#26450]
**Describe the bug**  
After one of the last updates my character(survival: 6, using hunting knife in the holster, also have scalpel in the inventory) no longer can yield any meat from butchering animals. Log says that she destroyed all of the meat. Tried it about 10 times with the same result. Pelts, bones and stomacs still drop normally.

**To Reproduce**  
1. Make a player with high enough survival skill and decent butchering tool
2. Butcher an animal (doesn't matter if it is quick butchery or full butchery).

**Expected behavior**  
Get meat from animal.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.C-33750-gdf5335b 
 - Graphics version: Tiles
 - Mods loaded
[
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "realguns",
  "FIC_Weapons",
  "More_Survival_Tools",
  "Medieval_Stuff",
  "makeshift",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "mutant_npcs",
  "Mining_Mod",
  "alt_map_key",
  "npc_traits",
  "more_locations",
  "FujiStruct",
  "cityside",
  "oa_additional_buildings_mod",
  "Urban_Development",
  "boats",
  "blazemod",
  "deoxymod",
  "Tanks",
  "EngineeringEssentials",
  "StatsThroughSkillsFour",
  "more_classes_scenarios",
  "manualbionicinstall",
  "DP_AMAZING_CHEST_INDICATORS"
]

**Comment by Ygdrad** [comment]
Confirm, not getting any meat, flesh is always getting clumsily destroyed. Even the entirety of a hulk's flesh gets destroyed.

**Comment by randomTechneck** [comment]
This issue persists in build 8095, with or without butchering rack, with a hunting knife or even the surgical scalpels. Not all that familiar with how things work on here so I don't know if I should open a new issue or what.

**Comment by ZhilkinSerg** [comment]
It was not fixed in 8095, but in 8096.

**Comment by randomTechneck** [comment]
My bad, didn't realize the latest build wasn't available through the launcher yet and must have overlooked the build number in the change log.

**Comment by ZhilkinSerg** [comment]
8097 should be available soon, please check if everything is fine there (just to make sure).

**Comment by randomTechneck** [comment]
Yep it's working in 8097. Got to make sure I pay more attention next time now that I now the change log in the launcher shows builds that aren't up yet.
