### ISSUE TITLE
Shotguns should be aligned with rifles.

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#26455]
**Is your feature request related to a problem? Please describe.**  
Currently shotgun has somewhat artificial dispersion to reflect its artificial "gamey" close range role. But IRL shotguns can be used to shot birds from the sky.

**Describe the solution you'd like**  
https://discourse.cataclysmdda.org/t/bows-crossbows-and-their-balance/17067/150?

>Also, I like how shotguns STILL have not been merged with rifles. I mean, COME ON. Last time I checked shotguns ARE, in fact, rifles (except for the fact the barrel is not rifled).

**Describe alternatives you've considered**  
We need proper aligment of the shotguns since Cataclysm based on realism approach.
https://github.com/CleverRaven/Cataclysm-DDA/pull/23801

I was the one who aligned shotguns that way. Before my changed shotgun dispersion + slug dispersio was aligned to rifles. Not I understand that.
Instead of what I've done I could just increase maximum shotgun range.

Current ranged balance:
# Current ranged balance:
Characters definition: https://github.com/CleverRaven/Cataclysm-DDA/issues/21244#issuecomment-310013403

Character | >50% good | <10% good
-- | -- | --
Novice pistol | 5 | 15
Novice shotgun | 6 | 16
Novice SMG | 6  | 18
Novice rifle | 9 | 25
Competent pistol | 15 | 33
Competent shotgun | 15 | 33
Competent SMG | 20 | 40
Competent rifle | 24 | 48
God pistol | 20 | 120
God shotgun | 24 | 124
God SMG | 30 | 190
God rifle | 60 | 800

**Comment by kevingranade** [comment]
I think he means skill use, what's your rationale for increasing shotgun range?

**Comment by Firestorm01X2** [comment]
Current shotgun balance based around modern FPS concept of close range weapon. It may be problem.

But there is may be alternative.

**Comment by mlangsdorf** [comment]
Shooting skeet with birdshot, there's nothing unusual about breaking a clay target that's flying past the opposite launching station.  A skeet range is a 21 yard radius half-circle. so that's 35-45 yards away.  Birdshot is tiny compared to buckshot, and loses velocity to air resistance faster, so I'd expect buckshot to have more range.

Converting yards to CDDA tiles is a hazardous exercise, but birdshot being effective to 15 tiles and buckshot to 30 or so isn't crazy.  Upping the accurate ranges of shotguns to match SMGs would make sense to me.

**Comment by Firestorm01X2** [comment]
>Converting yards to CDDA tiles is a hazardous exercise, but birdshot being effective to 15 tiles and buckshot to 30 or so isn't crazy.

30 is likely way too much. Since 30 tiles is shooting range of enemy anti material turret.

**Comment by Firestorm01X2** [comment]
In fact looking on:
https://docs.google.com/spreadsheets/d/1aGH8N2kITxZ_8i1Vyi1G-FIVfQOTL6euvKxZkYOc-FE/edit#gid=0

I see that current range somewhat fits real values:

Remington 870 | 12 ga | 40 m
-- | -- | --

Glock | 9mm | 100 m
-- | -- | --

**Comment by darktoes** [comment]
For the record I'm 90% sure he was just talking about skill use. I don't use/haven't looked at shotguns enough to comment on their range.

**Comment by HotSake** [comment]
Shit, if crossbows use Rifles skill, why not shotguns? They're handled the same way, aimed the same way, fired the same way. At least rifles and shotguns are both firearms!

**Comment by aierce** [comment]
Some realism has to be sacrificed for game-play.

**Comment by Firestorm01X2** [comment]
Looks like buckshot pellets officialy loss lethality after 50 yards. So our current max ranges seems about right in comparsion with pistols. Maybe problem in range distribution around all guns itself. But ingame range hard to de

**Comment by Firestorm01X2** [comment]
Sorry missclicked on the mobile. But still issue likely to be closed.
