### ISSUE TITLE
[CRASH] Empty locations for group GROUP_SEWER 

### ISSUE THREAD

**Issue by Gholdin** [CleverRaven/Cataclysm-DDA#26479]
**Describe the bug**  
Game crashes to desktop when traveling to any building locations located outside of the lab area I spawned from (lab scenario). Also seems to happen when traveling around too fast (holding down the move key at walking speed).
 Debug file reports while traveling:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2537098/debug.log)

Lab spawned with a connected subway system and an ant hill that a few tiles away. The ants have weaved into the lab on level -1. The connected subway is on (I think) -4. 

**To Reproduce**  
1. Start a lab scenario with a connected subway system and anthill (?)
2. Attempt to travel to local city (?)
3. Crash (?)

**Expected behavior**  
No crash.

**Versions and configuration:**
 - OS: Windows 10 64 bit
 - Game Version: Experimental Build 8080
 - Graphics version: Tiles w/ MSX++ Dead People
 - Mods loaded: Standard mods that come with the game launcher. All "disable" X or "No" X mods have been removed except for "No Fungal Monsters".

**Additional context**  
Save game file has been attached to refer to:
[Hampton.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2537122/Hampton.zip)

**Comment by Gholdin** [comment]
Did more testing. Interesting results:
1. Quicksaving while traveling seems to prevent the issue, but would require you to quicksave every 3-4 seconds. May be luck, but the results seem consistent.
2. The "memory" of my surroundings seem to be completely erased after restart from a crash. I have no recollection of how I even got to my current position while traveling. Cue Gandalf meme.
3. Moving quickly seems to be a large factor in the crash. If I linger in a new area (i.e. town or city) before making more movement (i.e. exploring a house very slowly for a period of time), the crash can be avoided. However, if I quickly walk through a new area I've never been, the crash seems to consistently happen.

**Comment by Gholdin** [comment]
Let me know if you guys need more info. I really want to get this problem fixed as it's debilitating to play crashing every couple seconds while traveling..

**Comment by ZhilkinSerg** [comment]
I cannot reproduce it on latest master with provided savegame. Please inform us if you still experience crash.
