### ISSUE TITLE
"unrecognized volumetric unit" error in monsters.json when starting game

### ISSUE THREAD

**Issue by prutschman** [CleverRaven/Cataclysm-DDA#26478]
**Describe the bug**  
When trying to start a game either by loading an old save or by choosing "Play Now!", an error is reported: "unrecognized volumetric unit" in monsters.json when starting game
Acknowledging the error returns me to the main menu.

**To Reproduce**  
1. Start cataclysm
2. [New Game]
3. [Play Now!]

(It seems to affect other scenarios as well)

**Expected behavior**  
I expected the game to finish the loading screen then allow me to play.

**Screenshots**  
```
 DEBUG    : Error: data/mods//dda/../../json/monsters.json: line 10:14: unrecognized volumetric unit


    "species": [ "ZOMBIE" ],
    "diff": 100,
    "volume":
             ^
              "62500 ml",
    "weight": 81500,
    "hp": 10000,

 
 FUNCTION : bool main_menu::load_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 943
```
**Versions and configuration(please complete the following information):**
 - OS: [macos 10.10.5]
 - Game Version [from the main menu, e.g. 0.C-33804-g79f65a7556]
 - Graphics version [Tiles]
 - Mods loaded [DDA, Filthy Clothing, Disable NPC Needs, Simplified Nutrition]

**Comment by prutschman** [comment]
Installation was via `brew install cataclysm --HEAD`. I've tried uninstalling and re-installing, to no effect.

**Comment by prutschman** [comment]
Something goes wrong at src/assign.h:196 ` str >> tmp >> suffix;`

The text of the json value is clearly "62500 ml". `tmp` is equal to 62500 after this line, but `suffix` is an empty string.

Looking at the internals of the istringstream, I see the full expected input string:
```
(gdb) p str.__sb_.eback()
$36 = (std::__1::basic_streambuf<char, std::__1::char_traits<char> >::char_type *) 0x7fff5fbe68c9 "62500 ml"
```
The stringstream appears to be at eof (consistent with not seeing the "syntax error when specifying volume" error):
```
(gdb) p str.peek()
$40 = -1
```
And yet,
```
(gdb) p suffix.length()
$42 = 0
```

This doesn't happen on Linux with the same git revision. My clang on macos is pretty old, though: 
```
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
```

**Comment by Qrox** [comment]
If you change the code from `str >> tmp >> suffix;` to `str >> tmp; str >> suffix`, what is the value of `str.peek()` after `str >> tmp;` and before `str >> suffix`?
