### ISSUE TITLE
Add recipes for Vehicle Minifridge, Minifreezer and Washing Machine

### ISSUE THREAD

**Issue by FrozenSnowFox** [CleverRaven/Cataclysm-DDA#26489]
**Is your feature request related to a problem? Please describe.**  
It's possible to make all sorts of vehicle parts welding rigs, forges, UPS recharging stations, FoodCo's, kitchen units ect.  However no such recipes seem to exist for the Minifridge, Minifreezer and Washing Machine.  Both the Minifreezer and Washing Machine seem to be rather rare which makes it difficult to get them.

**Describe the solution you'd like**  
I would like to see recipes added for the Minifridge, Minifreezer and Washing machine so they can be built from spare parts.

**Describe alternatives you've considered**  
Adding these vehicle parts to RV's and other such vehicles to increase their commonality could make them easier to acquire.

**Additional context**  
From what I understand adding a few recipes should only require some simple JSON editing.  I've played around doing xml editing for Rimworld so I wouldn't be against trying to do this myself and making a pull request.  However I'm not knowledgeable enough to suggest crafting requirements and I have yet to ever use Github in such a capacity.

**Comment by Orange01gaming** [comment]
I think there is a recipe for an ice chest already.

**Comment by FrozenSnowFox** [comment]
> I think there is a recipe for an ice chest already.

There's no Ice Chest as far as I can tell but there is some sort of ice blob component for vehicles that works like a fridge.  That doesn't really solve the issue though.

**Comment by l29ah** [comment]
Fridge/freezer should require some source of refrigerant. I don't remember any suitable items existing in game.
