### ISSUE TITLE
Changing keybinds in aiming menu causes game to crash

### ISSUE THREAD

**Issue by TheRealGunShy** [CleverRaven/Cataclysm-DDA#26494]
**Describe the bug**  
When opening the 'aiming' menu with a firearm (f), and attempting to change the keybinds (?), the game will crash upon exiting the menu and choosing (Y)es from the confirmation menu. The game will then crash upon startup until you replace the keybinds.json file with a backup.

**To Reproduce**  
1. Press the 'fire weapon' key
2. Press ?
3. Alter some key-binds (I specifically altered the keybinds for the aiming settings, aimed through precise).
4. Exit the menu and select (Y)es in the confirmation window.

**Expected behavior**  
I expected to continue the game using my new keybinds.

**Screenshots**  
I can't manage to get screenshots. I've tried fullscreen and windowed borderless modes, and nothing works. Fortunately, I don't think this problem really needs them.

**Versions and configuration(please complete the following information):**
 - OS: [Windows 7]
 - Game Version [0.C-33811-g2f4278f (tiles)]
 - Graphics version [Tiles]
 - Mods loaded [dda, disable npc needs, filthy clothing, simplified nutrition, extended realistic guns, more survival tools, stats through skills, craftable gun pack, safe autodoc, bright nights, no acid zombies, no explosive zombies, Cata++, No Freeze]

**Additional context**  
None I can think of.

Thanks for your time.

**Comment by ZhilkinSerg** [comment]
I've just reproduced the issue in main keybindings menu:

![image](https://user-images.githubusercontent.com/16213433/47922117-5de5ce80-dec7-11e8-98c8-e7521590fdc0.png)

![image](https://user-images.githubusercontent.com/16213433/47922132-65a57300-dec7-11e8-958e-967854c5daca.png)

**Comment by ZhilkinSerg** [comment]
I am pretty sure it was caused by #26125.

# Reproduce steps:

1. Start application.
2. Go to `Settings` - `Keybindings` menu.
3. Remove keybinding for `Move North` action and save changes.

**Comment by TheRealGunShy** [comment]
I tried to figure out what's going on by following the other posts you tagged here, but I don't speak the code language.

Just so you know, I unbound some of the panning directions so I could use 7, 8 and 9 for aiming, but I rebound the panning directions to something else to try and prevent problems.
