### ISSUE TITLE
Currents for water tiles

### ISSUE THREAD

**Issue by saladasa** [CleverRaven/Cataclysm-DDA#26509]
It would be nice if water tiles had currents with variable direction and speed. It would make unpowered boats useful and would increase realism. I was thinking a weak current near a river's shore and a strong current in the middle.

It might eventually wash all the fish away from an area though, so maybe fish could avoid strong currents?

**Comment by kevingranade** [comment]
If someone wants to do this, it can happen, but we can't afford to keep such general feature requests open, were drowning in them.
