### ISSUE TITLE
Overhaul minireactors based on NASA kilopower reactor.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#26513]
**Is your feature request related to a problem? Please describe.**  
Functioning of the in-game minireactor vehicle part is obscure because it's a made up component.  It's far lighter and smaller than any reactor I was previously aware of, so the stats are purely made-up.

**Describe the solution you'd like**  
My proposal is to overhaul the minireactor based on the NASA kilopower prototype.
https://en.wikipedia.org/wiki/Kilopower
Nice details in the wikipedia article, but the vital statistics from our point of view are:
1kW continuous power production (possibly subject to decay, but it's unclear at what rate).
10y lifespan.
~130kg
Non-removable fuel supply.

1kW isn't enough to drive a large electric motor directly, so it would need a battery to store the continuous output and deliver better peak load.

**Describe alternatives you've considered**  
The minireacor isn't *awful*, so leaving it as is is a valid option.
The larger system planned by NASA has even better characteristics, at 10kW production and "only" weights 226 kg, but that seems excessive for a vehicle part, unless it's for a large military application.

**Additional context**  
At first I thought this would make the atomic car just slightly less unrealistic, but still pretty out there, but after running some napkin math it actually makes a good bit of sense.  23Kg of uranium is evidently in the ballpark of $2,000 or so, after refining and manufacturing etc that probably brings the whole system to $10,000-$20,000 or so, which for continuous, no-maintenance power delivery *for 10 years* is pretty *hot*.  If we posit that dda world is just a lot more accepting of nuclear technology, I could see this being produced commercially.

This also provides a power source for isolated locations we want, for story reasons, to have power.
Vending machines, research labs, isolated mansions could have buried (but with work accessible) minireactors following this pattern that provide continuous power.

**Comment by mlangsdorf** [comment]
1kW is 1 battery charge per second.  It's about what a motorcycle alternator produces.  It's enough to power headlights and dome lights, but it won't even manage to feed a floodlight.

I mean, I guess that's as good as 20 basic solar panels, and you get it every second, rain or shine.  but it's still a step down from the current reactors that are ~1.4 MW iirc.

**Comment by kevingranade** [comment]
It does reduce their power level, but it also renders them more usable since they'd no longer be competing with scifi weaponry for relatively scarce plutonium supplies.

1 kW gives you 24kWh per day, which is in the ballpark of the total capacity of many electric cars.  
The larger 10kW unit would be unquestionably superior for very large vehicles and sought-after.

I consider the fact that it doesnt meet all your energy needs a feature rather than a problem.

**Comment by pikolinianita** [comment]
cool idea, but not for vending machines. there should be solar panel + small battery (plus regular power for winter backup - now offline)  (put "vending machine solar power" into google).

10 years is for NASA space reactors. As far as i know greedy car companies, they would make 1-2 year lifetime versions (lighter, about half of NASA reactor) and try to convince us that scrapping almost new car is best thing in the world.
In a game terms, 10 years is infinite time. even if average reactor have half fuel spent. But if there is one year, half fuel burned on average...

**Comment by eilaattwood** [comment]
So we get almost the same characteristics as vortex generator?

**Comment by kevingranade** [comment]
I dont see where you're getting "trashcan sized".  Your source says the pressure vessel is the size of an office desk, which excludes the turbine and pumps and control panel.  Add all that hardware together and were talking car sized.

This is in line with your diagram, which shows the reactor compartment filling the circumference of the ship for a significant length.

> Given the assumed technological progress

Don't assume, just get me a source.  Every source I can find says more efficient reactors are *much* larger.  If you canbfind q source that says otherwise, we can look at that.

**Comment by Beanzy** [comment]
A NASA reactor designed for deep space use is not representative of what a terrestrial reactor of similar size would be capable of. Power output is inherently tied to how efficiently the reactor can shed heat, the temperature differential is what allows the reactor to produce electricity in the first place. And as I stated before, a vacuum is an extremely good insulator.

I didn't see anything on the Kilopower page indicating that it's design was intended for terrestrial use. So I'm simply saying that it may be prudent to find a reactor designed for use on Earth to base the Minireactor off of - as there are obvious inefficiencies in a space borne design (mainly due to heat exchange).

**Comment by kevingranade** [comment]
Its not designed for deep space, its designed for Mars.

Feel free to look for one, but i havent found one that meets our constraints.  Its not a matter of picking kilopower over another option, there is no other option.

**Comment by DavidEdwards** [comment]
> The prototype KRUSTY 1 kWe Kilopower prototype reactor weighs 134 kg and contains 28 kg of 235
U. The space rated 10 kWe Kilopower for Mars is expected to mass 226 kg and contain 43.7 kg of 235
U.

Apparently it will come in 4 different sizes. The largest of which is rated at 10 kW. In case that changes anything.

**Comment by RenechCDDA** [comment]
Minireactors have been removed from vanilla dda and ASRGs have taken their place - is this still a valid issue?

**Comment by TealcOneill** [comment]
Based on Renech's comment and my inability to find minireactors spawning anywhere in the base game I'm going to call this a closed issue.
close-invalid

**Comment by TealcOneill** [comment]
Based on Renech's comment and my inability to find minireactors spawning anywhere in the base game I'm going to call this a closed issue.
/Invalid

**Comment by kevingranade** [comment]
Implemented as #59479
The minireactor was left as a loose end for some reason, cleaning that up soon:tm:
