### ISSUE TITLE
Wind power! 

### ISSUE THREAD

**Issue by denemcam** [CleverRaven/Cataclysm-DDA#26512]
**Is your feature request related to a problem? Please describe.**  
I love the concept of stationary bases out of vehicle parts, and different ways to power them. Tho, there could be more.. We already have solar power, internal combustion engines.. But what about wind power? 

**Describe the solution you'd like**  
There could be several machines and structures to help wilderness and end-game survival. A set of machines that use wind power! From basic medieval windmills, that help grinding reagents and food into dust, to hi-tech combined solar-wind-turbine.

**Describe alternatives you've considered**  
A lot of possibilities that could be done in this way, via wind power:
> Windmill from rags, two-by-fours, some oil, gears and grindstones;
> Wind turbine from metal sheets, pipes, electric components; 
> Combined generator from solar panel and turbine;
> Maybe a separate "mechanical" power system, to use in many designs like fast opening doors, and such.

**Comment by kevingranade** [comment]
If someone wants to do this, it can happen, but we can't afford to keep such general feature requests open, were drowning in them.
