### ISSUE TITLE
NPCs can't distinguish between 'waist' and 'normal' torso armor layers

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#26529]
**Describe the bug**  
I tried to make my NPC equip a quiver for his bow, but he took his shirt off to put the quiver on. It seems like NPCs won't wear two items in the same slot of the same layer (makes sense, but idk if this is the correct behavior) - if this assumption is correct then this issue appears to be the NPC not distinguishing between waist and normal layers on the torso. I tried giving him my sheath with hunting knife to see if it would happen for the leg slot, but he put in on just fine. See below for his clothing list.

**To Reproduce**  
1. Spawn NPC, equip long sleeve shirt (torso - normal), army jacket (torso - outer), and MilRuck (torso - strapped)
2. Tell NPC to use (wear) quiver (torso - waist) via interaction menu "I want you to use this item"

**Expected behavior**  
NPC puts on quiver.

**Observed behavior**
NPC takes off the longsleeve shirt and puts on quiver.

**Versions and configuration:**
 - OS: Win7
 - Game Version: 0.C-34017-gca8a86a (build 8115)
 - Graphics: Tiles (chesthole32)
 - Mods: 
     Extended Realistic Guns, 
     More Survival Tools, 
     Tall Buildings, 
     Boats, 
     Vehicle Additions Pack, 
     Tanks and Other Vehicles

**Additional context**  
The NPC was wearing the following items, from inner to outer as seen in the 'sort armor' screen:
- pair of combat boots
- cargo pants (fits)
- pair of army winter gloves
- bandana
- army helmet (fits)
- pair of ballistic glasses
- ++ long sleeve shirt+1 (fits), with additional kevlar
- army jacket (fits)
- military rucksack

The NPC had very low strength (5).

**Comment by eilaattwood** [comment]
I saw that behavior, but can't it be overall encumbrance, not the layers issue?

**Comment by AskaHope** [comment]
Ive been having a similar problem lately, tried to equip a plate armour and a quiver on an NPC.
As soon as he equipped the armour, he unequipped the quiver.
I've found a solution, tough:
1 - Ask the NPC to equip the armour
2 - Ask the NPC to wield the quiver 
3 - ask the NPC to wield a crossbow (he'll equip the quiver to wield the crossbow)

**Comment by natsirt721** [comment]
I believe this to be a total encumbrance issue, although I'm not sure what the cap is. I've read sources which suggest its 30, but MilRuck +  Army Jacket is already 35. 

IMHO the NPCs should wear whatever you tell them to, since you can already largely control the contents of their inventory and much of their behavior, but that's not exactly the scope of this ticket.

**Comment by Ramza13** [comment]
#37654 should fix this as it cleaned up this dialog and removed the arbitrary encumbrance limits.
