### ISSUE TITLE
Firearms: being able to chamber single rounds for firing w/o magazine

### ISSUE THREAD

**Issue by LieutenantColonelSpider** [CleverRaven/Cataclysm-DDA#26520]
Its quite sad when you get your hands on a gun and its required ammo, yet, both turn out to be 100% useless, only because it has no magazine. Instead of having an empty pistol and some rounds, you could at least have a re-loadable one-shot in your hands if its needed, by chambering a round without a magazine.

Firearms with a closed-bolt configuration (assuming by the function of open-bolt firearms needing a magazine, firing single chambered shots would be difficult) should have the ability to chamber a single round and cycle it, with whatever moderate load time would be appropriate for the firearm.  The casing would eject, and then another round could be tediously or quickly loaded in depending on dexterity/pain/etc.

**Comment by Reclusive-reptile** [comment]
Duplicate #26370
