### ISSUE TITLE
NPC can't drink from worn container.

### ISSUE THREAD

**Issue by DarkRainX** [CleverRaven/Cataclysm-DDA#26533]
**Describe the bug**  
NPC are unable to drink liquids from containers they are wearing, one needs to go to sort their armour and un-equip the container for them to use it.

**To Reproduce**  
Steps to reproduce the behaviour:
1. Enable NPC needs.
2. Acquire NPC and equip it with a canteen (or similar worn container) full of clean water.
3. Pass time until NPC complains from lack of water.
4. Sort NPC's armour and un-equip the container with clean water, watch as NPC starts drinking the very next turn.

**Expected behavior**  
NPC should be able to drink/eat from worn containers just as the player can (they are already able to do so from their inventory).

**Screenshots**  
![captura de pantalla_2018-10-14_18-39-29](https://user-images.githubusercontent.com/8475616/47972822-98856d80-e065-11e8-8380-eda3e6ae9269.png)

**Versions and configuration(please complete the following information):**
 - OS: Gentoo linux
 - Game Version: 0.C-34017-gca8a86a955
 - Graphics version: Tiles
 - Mods loaded:
  "dda",
  "Experimental-Z-Level",
  "More_Survival_Tools",
  "blazemod",
  "Tanks",
  "Urban_Development",
  "alt_map_key",
  "boats",
  "deoxymod",
  "filthy_morale",
  "makeshift",
  "more_locations",
  "national_guard_camp",
  "npc_traits",
  "Hairs",
  "more_locations_hairs"

**Comment by Night-Pryanik** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/f53995c0f89a5ba5c9566c7a28d3489349958fc3/src/npcmove.cpp#L2808-L2813

That's because game checks for containers with food or drinks only in NPC's inventory, and wielded or worn containers ain't counted.

**Comment by aerrant** [comment]
The issue was fixed [some 7 months ago](https://github.com/CleverRaven/Cataclysm-DDA/commit/e2e870d181141697fb84dad1a82046625d8e7a55). I did some manual testing: NPCs now drink their water from worn containers properly.
