### ISSUE TITLE
Quick butcher everything: false advertising

### ISSUE THREAD

**Issue by DarkRainX** [CleverRaven/Cataclysm-DDA#26531]
**Describe the bug**  
#26263 renamed the "butcher everything" option to "quick butcher everything", that was a mistake: I don't know how smart the function tries to be, but at least if the rack+table requirement is met, selecting "quick butcher everything" will actually try to perform full butchery on all the corpses instead (which might fail for large enough corpses if you don't have a saw)
Additionally the time estimate will evidently be way off when the "quick butcher everything" ends doing full butchery instead.

**To Reproduce**  
1. Acquire corpse pile, butchering rack and table.
2. **B**utcher the corpse pile, select Quick **b**utcher everything.
3. Watch as your character tries to do full butchery instead.

**Expected behaviour**  
The description for the butcher everything option should be accurate, failing that, it at least shouldn't be misleading. The time estimate shouldn't be grossly misleading either.

**Screenshots**
(it's hard to tell that I actually chose "quick butcher everything" from just the screenshots but here goes)
Note the 10min estimate, and the previous attempt's failure because of the lack of a saw:
![captura de pantalla_2018-11-04_18-18-59](https://user-images.githubusercontent.com/8475616/47972521-b7cecb80-e062-11e8-92a8-ee5a80b34f6e.png)
"Quick butcher everything" results: note that it took just over one hour and performed full butchery instead.
![captura de pantalla_2018-11-04_18-19-38](https://user-images.githubusercontent.com/8475616/47972587-4e02f180-e063-11e8-9221-8e9ce26d5562.png)

**Versions and configuration:**
 - OS: Gentoo linux
 - Game Version: 0.C-34017-gca8a86a955
 - Graphics version: Tiles
 - Mods loaded:
  "dda",
  "Experimental-Z-Level",
  "More_Survival_Tools",
  "blazemod",
  "Tanks",
  "Urban_Development",
  "alt_map_key",
  "boats",
  "deoxymod",
  "filthy_morale",
  "makeshift",
  "more_locations",
  "national_guard_camp",
  "npc_traits",
  "Hairs",
  "more_locations_hairs"

**Comment by Karthas077** [comment]
I was just mucking about in those files recently, so if my latest PR gets through I'll take a crack at this if no one else has gotten to it.

What are people's thoughts on what would be best: restricting the current menu option to quick butchering, or expanding the menu option to allow for "Butcher all" of every type? ie- Butcher Everything leading to another menu just like the one tied to the single butchery action (except it applies to the entire pile)

**Comment by OzoneH3** [comment]
Fixed in #26531
