### ISSUE TITLE
Make the usage of the cordless drill consistent.

### ISSUE THREAD

**Issue by DarkRainX** [CleverRaven/Cataclysm-DDA#26534]
**Is your feature request related to a problem? Please describe.**  
The cordless drill usage is inconsistent:
Some crafting and building recipes (folding butchering rack and tourist table, peepholes) call for the drill quality, for these the drill doesn't use charges and in fact doesn't even need to be charged.
Some other crafting recipes (the various chainmail items) call for a set amount of cordless drill charges.

**Describe the solution you'd like**  
I think the cordless drill should work like the circular saw: it should have on and off states and it's drilling qualities should be exclusive to the "on" state, recipes calling for a set amount of cordless drill charges should be changed to call for the drill quality, so that all crafting and building recipes call for an adequate drilling quality.

**Describe alternatives you've considered**  
Another option would be to change all crafting and building recipes to call only for drill charges, but that would either make both the hand drill and the drilling quality itself pointless, or require duplication of recipes as is the case for mortar/quern vs food processor.

**Comment by Fris0uman** [comment]
> recipes calling for a set amount of cordless drill charges should be changed to call for the drill quality

But then it won't use any charge, no ?

**Comment by DarkRainX** [comment]
> I think the cordless drill should work like the circular saw: it should have on and off states and it's drilling qualities should be exclusive to the "on" state.

The idea is that the cordless drill would have the drlling quality only when turned on, and it would consume charges for as long as it is "on", just like the circular saw does, so it would use charges not as a function of the recipe direclty, but as a function of the time needed to complete said recipe
