### ISSUE TITLE
'offset' cars cannot be driven straight if repaired

### ISSUE THREAD

**Issue by JacobKessler** [CleverRaven/Cataclysm-DDA#26549]
**Describe the bug**  
Vehicles that are spawned at an offset (such as roadblock police cars, wreckages, and V-22 Ospreys)  have faceDir and turnDir that may not line up to 'straight', and so always drift if repaired

**To Reproduce**  
1. Find a vehicle that has been spawned in a partially-turned state, like a police car at a roadblock.
2. Repair it as needed to get it driveable
3. Attempt to drive straight, note that you always drift left or right

**Expected behavior**  
The character should be able to drive in a straight line in a repaired vehicle, or have some way to correct the drift

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-33849-gcd5965ed4a
 - Graphics version Tiles
 - Mods loaded
    "dda",
    "no_npc_food",
    "novitamins",
    "craftgp",
    "realguns",
    "FPaF",
    "Medieval_Stuff",
    "SM",
    "mutant_npcs",
    "npc_traits",
    "Urban_Development",
    "deoxymod",
    "blazemod",
    "Tanks",
    "Nonperishable_Overhaul",
    "manualbionicinstall",
    "rmod",
    "safeautodoc",
    "StatsThroughSkills"

**Additional context**
Some savegame diving reveals that the vehicle had 
"faceDir":173,"moveDir":158,"turn_dir":173
Changing that to 
"faceDir":180,"moveDir":180,"turn_dir":180
seemed to resolve the issue. 
It seems like there should be a case to round to the closest 'real' direction (potentially on turning) to resolve this

**Comment by kevingranade** [comment]
Woo good triage, that fix sounds like it'll work too.
