### ISSUE TITLE
Butchering a quarter of a corpse takes exactly the same time as a whole corpse

### ISSUE THREAD

**Issue by Jerald-of-Libya** [CleverRaven/Cataclysm-DDA#26545]
**Describe the bug**  
Butchering times for a quarter-corpse is the same as a whole corpse. This effectively multiplies total butchering time by 4 for any corpse you quarter.

**To Reproduce**  
1. Get a sizeable enough corpse that allows quartering.
2. Field dress the corpse.
3. Check the [B]utchering menu to look at the time required for quick/full butcher.
4. Quarter the corpse.
5. Check the [B]utchering menu again, and wonder how each quarter-corpse takes the same amount of time to quick/full butcher as a full corpse.. effectively multiplying the time-to-butcher by 4.

**Expected behavior**  
A quarter of a corpse should take around a quarter of the time to butcher versus a full corpse.. maybe a bit less since you've already performed a couple of huge cuts to quarter the whole thing. (?)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - 0.C-34099-gbd9c3f4
 - Tiles
 - Mods loaded: Filthy Clothing, Simplified Nutrition

**Comment by JeraldOfLibya** [comment]
Ah.. seems simple enough. I think I've got this.

Slapping:
```
if( corpse_item.has_flag( "QUARTERED" ) {
    time_to_cut /= 4;
}
```

on activity_handlers.cpp should do the trick.

**Comment by AMurkin** [comment]
Should it be plain `/4` without any penalties?

**Comment by Shoes01** [comment]
I would think it takes longer to start and stop butchering a corpse 4 times, rather than doing it straight through. Presumably, taking out the butchering tools, and cleaning them a bit before putting them away, all take a bit of time.

**Comment by Jerald-of-Libya** [comment]
@Shoes01 
Startup and cooldown costs aren't a thing even for butchering regular corpses though. Full butchering 2 corpses in quick succession is exactly twice the time to butcher a single corpse.

Also, we aren't talking about making some sort of batch butcher feature here. Just lowering the time cost of butchering a single quarter-corpse.
