### ISSUE TITLE
It would be awesome if you can use alt+ and ctrl+ to your keybinds

### ISSUE THREAD

**Issue by jayWLKRRR** [CleverRaven/Cataclysm-DDA#26550]
I would be awesome and It would open alot of possibilities for someone who keybinds alot like me. 

I think this is just too straightforward without explanation needed. Thank You

**Comment by OzoneH3** [comment]
After investigating a bit this would be possible for SDL versions but there is no consistent way to do this for the console version.

**Comment by Azumgi** [comment]
Having `shift` would be awesome as well. So instead of `A` it would be `shift + a`. No more sudden caps lock interactions. And overall no problems with selected keyboard locale, since in SDL version you could just listen to VK codes. Curse you, curses version!
