### ISSUE TITLE
Replace XL gear variants with Oversized flag

### ISSUE THREAD

**Issue by JacobKessler** [CleverRaven/Cataclysm-DDA#26551]
**Is your feature request related to a problem? Please describe.**  
The current implementation of XL clothing (for extra-large mutants and their anatomy) is inconsistent and needlessly limiting, given that a late-game survivor will often be crafting their own clothing anyway and so wouldn't be bound by 'normal' sizes anway. The Mouse mutation line introduced a new way of handling size differences (undersizing), it seems logical to propagate that in the other direction for large mutants.

**Describe the solution you'd like**  
Similar to the (undersized) tag that lets Tiny mutants wear clothing, provide an (oversize) tag that large and huge mutants can apply to their clothing in the same way. Similar to (undersized), multiply encumbrance penalties for wearing the wrong-sized clothing. As a side note, I think that also solves accidentally hulking out in your plate mail and evaporating it.

**Describe alternatives you've considered**  
The existing system (with XL Survivor suit and friends) works alright, but clutters the crafting menu for non-huge survivors and means that mods have to consider XL versions of any introduced clothing. Also, there are a lot of things that logically should be craftable in large sizes (like chainmail) that simply aren't, likely because nobody has bothered to add them.

**Comment by kevingranade** [comment]
As far as how available oversized clothing is, it's working as intended.

The interactions between various mutations and xl clothing is also intended.
