### ISSUE TITLE
8x40mm Rivtech caseless ammo have suspiciously high dispersion

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#26558]
**Describe the bug**  
Rivtech based its wepons on unique caseless ammunition. It is expected that Rivtech rifle ammohas superior or at least comparable accuracy stats to modern rifle ammuniton.

But in fact it is 2 to 3 times worse. 

For example:
5.56 NATO M855A1 has disperion of 20.
.223 Remington has disperion of 30
7.62x39mm 57-N-231 has disperion of 35
9x19mm JHP has dispersion of 60
**8x40mm caseless has dispersion of 75**

Rivtech:
"Our rifles have superior accuracy but our unique, proprietary and expensive rifle ammunition have worse accuracy than pistol ammo".

**Expected behavior**  
Rivtech 8x40 rifle ammo should have comparable dispersion to modern rifle ammunition. 

Overall Rivtech guns are better beacuse of initial Rivtech gun diispersion really small:<50 dispersion. In  comparsion  .223 rifle has 150 dispersion average .

Is there really explanation to that kind of reverse logic? Is it balance desicion or long forgotten oversight?

**Comment by Rivet-the-Zombie** [comment]
>Is it balance desicion or long forgotten oversight?

Lxikely an oversight.

**Comment by kevingranade** [comment]
> Overall rivtech guns are better beacuse of initial gun rivtech gun diispersion really small:<50 dispersion.

This is the only part that matters, the dispersion of gun or ammo taken in isolation is meaningless.

**Comment by Firestorm01X2** [comment]
Let's compare gun accuracy.
Assault rifle:
Steyr AUG: 150 (base disp.)+30(.223 disp.)=180
RM51 assault rifle:  90(base disp.)+ 75 (8x40mm caseless disp) = 165

Battle rifle:
FN SCAR-H: 150(base disp.)+15(.308 Winchester disp.)=165
RM88 battle rifle:  50 (base) + 75 (8x40mm caseless disp)=125

LMG:
M249: 200(base disp.) 30 (.223 disp)= 230
RM614 LMG: 140 (base) + 75 (8x40mm caseless disp)= 215

HMG:
RM298 HMG: 180(base disp.) + 75 (8x40mm caseless disp)= 255
M240: 200 (base disp) +15(.308 Winchester disp.)= 215
