### ISSUE TITLE
Exoskeletons

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#26568]
There are several types of power armor in the game designed to protect character from being hurt during combat, but we shouldn't forget about it's ancestor - exoskeleton. And I mean mainly utility exoskeleton, not the combat one. Utility exoskeleton, that can help to maintain tasks that require lot of strength. I suggest it to have this features:

- Wear on outer level or even strapped. Add some armor, but low coverage.
- Drain much less power than power armor when activated.
- Add significant encumbrance to torso, arms, legs and feet even when activated.
- Increase strength, but decrease dexterity.
- Simplify tasks/long actions that involve strengts (digging, mining, clearing rubble, building, cutting metal, chopping trees, moving furniture/vehicles, carrying heavy objects, etc.) - reduce time required to complete job, reduce fatigue, hunger and thist gain from such tasks.

It might be good idea to add different classes of exoskeletons, like technician (lot of strength and bonuses for long tasks, but penalties for combat and moving) and military (little bonus for strength and carry weight, but increase moving speed (and decrease fatigue and stamina drain when moving/running), help to maintain recoil and dispersion of guns, etc.). 

Technician exoskeleton may be powered with vehicle or storage battery, while military one require UPS.
And... creating crude makeshift hydraulic exoskeleton powered by gasoline engine would be hilarious.

**Comment by kevingranade** [comment]
Idea dumps are not valid issues.   Youre outlining a number of large changes with insufficient detail for implementation.

This kind of thing is better suited for the forums or the subreddit to drive interest and develop detail.
