### ISSUE TITLE
Micro Motor only found in Food Processor

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#26566]
**Describe the bug**  
The Micro Motor component appears to only be found in Food Processors and RC cars and isn't craftable. Often I find that in order to craft a food processor I need have already found and disassembled a food processor. Not sure if that's intentional, but it kind of defeats the purpose.

**To Reproduce**  
Just try to work your way up to crafting a FOODCO Kitchen Unit and the player tends to bottleneck at the Food Processor (provided he hasn't found one yet).

**Expected behavior**  
It seems that the the Food Processor Micro Motor was getting phased out (maybe?) and getting replaced by another craftable motor? Seems it was used in things like Hedge Trimmers and Hair Trimmers before it was removed from their recipies? At least that's my guess...

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-32545-gc2d6772 (tiles)
 - Graphics version: Tiles
 - Mods loaded: Default
	Dark Days Ahead
	Disable NPC Needs
	Filthy Clothing
	Simplified Nutrition
	StatsThroughSkills
	Alternative Map Key
	NPC Traits
	Disable Religious Texts
	No Explosive Zombies

**Comment by FulcrumA** [comment]
Cannot confirm. Using the newest version - 0.C-34138 (build 8129). Hedge trimmers drop micromotors as expected, item viewer also reports them available (in development version) in food processors, desk fans, microwaves, RC cars, makeshift vacuum sealers and electric hair trimmers.

@RogueYun please ensure that the issue you report is really still happening in newer versions of the game.

**Comment by RogueYun** [comment]
My apologies, from my perspective it wasn't about spawn rate, it looked as though a project was half done, or someone was converting micro motor, possibly into the small electric motor.

Is the Micro Motor still not craftable?

As for having the always having the most recent update, I have a limited data plan and tend to download updates sparingly. :'(

**Comment by FulcrumA** [comment]
>from my perspective it wasn't about spawn rate, it looked as though a project was half done, or someone was converting micro motor, possibly into the small electric motor

Cannot recall, possibly it was so but only because the work on it wasn't finished - till it was finished.

>Is the Micro Motor still not craftable?

Micromotors are craftable, though it's possible that your version is old enough that it doesn't have that either.

>As for having the always having the most recent update, I have a limited data plan and tend to download updates sparingly. :'(

Very understandable, though it also creates the risk of what we have now - reporting bugs that aren't there anymore :P

Either way, thank you for the report but as I've stated - your issue is very likely outdated and not happening in newer development/experimental versions. Rejoice?

**Comment by RogueYun** [comment]
Rejoice!
