### ISSUE TITLE
Steel jerrycans (20L) require a metal tank (60L) to craft.

### ISSUE THREAD

**Issue by preacherpix** [CleverRaven/Cataclysm-DDA#26561]
**Describe the bug**  
Crafting a steel jerrycan requires a 60 litre metal tank, like the ones you get off of vehicles, and there are no substitutes. The jerrycan you create only holds 20 litres.

**To Reproduce**  
1. Create a character with at least fabrication 2.
2. Check crafting list.

**Expected behavior**  
It just seems a bit asinine to require a much larger tank to make one that's smaller. There's no real reason to even want to craft the 20L tank besides ease of carrying it around. It should just cost some scrap metal or maybe 1 sheet metal instead, like the 60L tank, but require less welder charge or less time.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-34104-g40e325c
 - Graphics version Tiles
 - Mods loaded [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

**Comment by Inglonias** [comment]
Could we add some scrap metal as byproducts, enough to make one other jerrycan with a new recipe?

**Comment by rubenpd** [comment]
i think he's asking for a steel jerrycan recipe made from scraps

**Comment by Xion350** [comment]
You can make 60L tanks from scratch, but yeah it is a bit silly.

**Comment by rubenpd** [comment]
using a 60L tank is not crafting it from scrap, it's scrapping a bigger tank to make yours

**Comment by KorGgenT** [comment]
@TheMurderUnicorn 
make a pull request from your fork.
Take a look at the guidelines for summaries and whatnot; plenty of people will be happy to tell you how to get it within guidelines.

**Comment by swofle** [comment]
This issue is resolved by #26961, please close this.
