### ISSUE TITLE
Very hard to read text on high DPI display

### ISSUE THREAD

**Issue by svenstaro** [CleverRaven/Cataclysm-DDA#26579]
**Describe the bug**  
I have a high DPI display and it's very hard to see anything as the text and tiles are drawn so small in comparison to my screen. I [fixed this problem before](https://github.com/CleverRaven/Cataclysm-DDA/pull/13999) but due to more recent changes where resizing the window doesn't resize the contents but the terminal size, my fix was broken.

**To Reproduce**  
Have a high DPI screen. Start Cataclysm. You can't read anything.

**Expected behavior**  
Cataclysm should figure out the display DPI and use that as a base scale factor. The options should further allow you to provide a manual scale factor.

**Screenshots**  
![2018-11-08-120417_3094x2099_scrot](https://user-images.githubusercontent.com/1664/48194858-741fde80-e34e-11e8-9103-a6dd2c26a8ad.png)

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux 
 - Game Version: 86354153ea348058425753cc47aae37ffaa30e23
 - Graphics version: Tiles
 - Mods loaded: N/A

**Additional context**  
I think this could be accomplished by setting the logical render size in SDL to a fraction of the actual render size. This way, SDL will scale up the window contents to match the physical window. A new `scaling factor` setting would allow for manually setting the factor. A scaling factor of 2.0 would be pixel perfect quadruple as large.

**Comment by kwl01skz** [comment]
Now we can edit /config/fonts.json.

**Comment by svenstaro** [comment]
@kwl01skz Using fonts in order to simulate DPI scaling would be a crude workaround at best which we should not settle for I think.

**Comment by aleksfadini** [comment]
Especially when running on i3wm (Linux window manager), changing the terminal width and height resets at each reboot of cataclysm. So one has to go through tiny menus each time to re-configure terminal width and height until text becomes readable

**Comment by Epictyphlosion** [comment]
Adding some code that can double the size of text for higher DPI displays could work, especially if it can be toggled from the options menu (if the resolution is high enough).

**Comment by kevingranade** [comment]
Should be fixed by #28253
