### ISSUE TITLE
COMPILING.md has instruction for outdated Ubuntu 12.10 that reached EOL

### ISSUE THREAD

**Issue by matkoniecz** [CleverRaven/Cataclysm-DDA#26589]
Ubuntu 12.10 reached EOL ( https://endoflife.software/operating-systems/linux/ubuntu )

I think it would be preferable to have instructions for currently supported OS.

EDIT: Edit to self - I thought about making PR for https://github.com/CleverRaven/Cataclysm-DDA/issues/25285 - this is my current blocker

**Comment by matkoniecz** [comment]
Ubuntu 12.10 is still EOL.

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING.md#debian still has Ubuntu 12.10.

**Comment by kevingranade** [comment]
Feel free to change it, but this isn't a bug.
