### ISSUE TITLE
COMPILING.md and CONTRIBUTING.md miss documentation how one may run automated tests

### ISSUE THREAD

**Issue by matkoniecz** [CleverRaven/Cataclysm-DDA#26591]
manual tests are mentioned at https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CONTRIBUTING.md#in-game-testing-test-environment-and-the-debug-menu but I would expect that to be accompanied by running automated tests to avoid regressions

**Comment by kevingranade** [comment]
Instructions added.
