### ISSUE TITLE
dog whistle doesn't produce sound

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26592]
**Describe the bug**  
> Sound 0

**To Reproduce**  
1. Blow the dog's whistle

**Expected behavior**  
See some bigger sound level and zombies coming to check it out.

**Versions and configuration(please complete the following information):**
 - 0.C-34155-g6ddeee0cd9-dirty

**Comment by kevingranade** [comment]
Dog whistles dont make noise audible to humans.
https://en.m.wikipedia.org/wiki/Dog_whistle

**Comment by AskaHope** [comment]
Haha, that was a funny one
