### ISSUE TITLE
Working T-Shirt tiles confusion

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#26599]
So, i discovered what there are 3 colors for working t-shirt in the game, but id for that item is only one, and you can summon from debug menu only one color of this t-shirt - gray.
Question: how do i assign 3 different tiles to theese 3 different items, if they have the same id (for some reason)?

**Comment by Inglonias** [comment]
So... if we can't summon it from the debug menu, and they have the same item id, the most logical thing to do would be to remove the offending t-shirts entirely.

**Comment by gynoidgearhead** [comment]
> and you can summon from debug menu only one color of this t-shirt - gray.

I thought you could summon the other colors by repeatedly hitting the right arrow key while you are hovering over the item?
