### ISSUE TITLE
Multi-tile entities solution suggestion (the glue rule)

### ISSUE THREAD

**Issue by Zaragata** [CleverRaven/Cataclysm-DDA#26609]
_Sorry for the ridiculous title, couldn't think of something better._

**Impasse**
Alright, I'm making this suggestion because I was creating a tileset based on retro-days, but with a hand on overlays and instead of its tiles being 10x10, they'll be something like 8x6 (humans still 10x10, but off-seted). Not isometric, just to simulate a vertical inclination on everything (walls, doors, etc).

Anyway! In the process of trying to think on something useful, I came into this: what can we do to **represent big monsters**, like hulks and juggs, **occupying multiple tiles without having to entirely rewrite the path-finding code** and whatnot. Maybe having to rewrite just those fair-spaced objects classes and some parents.

**Suggested Solution**  
Well, I'm not really good at programming and coding, so bear with me for just a bit more. I took a look on posts about this, tho, so this suggestion is actually based on something you guys sorta already came up with, maybe it's already in the works too, I dunno.

I remember someone mentioning: why not use the vehicle code to make multi-tile enemies? In addition to that, I'd suggest: why not add some lines to the parent class to allow multiple spawns in a pre-determined space and to glue those together? Also, create a child class, _hulk-piece_ with an Enum that decides where the piece's relative position will be. So that if a hulk (4 glued hulk-pieces) stands near another hulk, they wont merge into one 8-tile hulk, because _piece1_ (bottom left) will always have it's sister, _piece2_, on it's right side and it's other sisters above her. Also meaning not every multi-tile thing will be a blob-like, growing and growing (which would be cool for blobs, tho). Plus, we would need to flag it with something like _glue2x2sprite_ so we can add just a single sprite to it's lower-left piece.

About path finding: if the entity is 4 tiles and it's _main piece_ is trying to pass/destroy a 1 tile hallway/door and lacks strength, add something that make the AI stop trying to follow that path and pick another (something like a short-spawn variable to not pass through that tile for some turns?)

Back to the glue, these pieces could also share the same hitpool, stats and everything; if possible. Which would mean increases on some defenses (against any AoE dmg). Also, glue-type monsters wouldn't need the ability to turn. Unless it's something like a moose,

Moreover, if a piece "disconnects", make the entire thing explode in a bloody meat storm. Sorry.

**Alternatives**  
I don't think this suggestion excludes the organic-vehicle one (for mooses and sausage monster alike), which would be very cool too. So, that's that. It could, also, be adapted for blobs. Maybe making a boolean to determine which code will be used to define it's behaviour (blob or not).

**Additional Notes**
I'd like to ask, too (considering all I've said is doable), if it would be possible to extend this behaviour to the player and npc characters. You know, some mutations make your player really big and _clumsy_ (?). Maybe? I know I'd have to make a lot more sprite's for the different size of clothing and whatnot, but it's all for the sake of !FUN!

I dunno, just trying to give some ideas on this topic. Sorry if too delusional haha. What do you ppl think?

**Comment by kevingranade** [comment]
You're trying to solve an easy problem and not addressing the hard problems.

Having 4 monster variants that are, big_mon_quadrant_1 through big_mon_quadrant_4 would be fairly simple, and extending the monster movement code to keep them in a fixed position relative to each other would also be fairly simple.

The hard parts are pathing AI (which we don't have solved for vehicles either) and extending tons of monster interaction code to treat the group of monsters as a single big monster.

**Comment by Zaragata** [comment]
If it isn't too much to ask, would this also mean NPCs being able to drive? Mad-max combat? Would solving the pathing AI allow a relative easier implementation of all these things?

Anyway, thanks for the answer! Was just curious if it was possible and doable.
