### ISSUE TITLE
Crafting solder from tin and lead?

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26601]
I'm considering making such a realistic (https://en.wikipedia.org/wiki/Solder#Lead_solder) recipe, creating solder out of lead and tin cans using a hotplate (lead MP is 327°C, tin is 232°C) and a cooking container, do i need to know any hacky balancing decisions that would make it unsuitable for inclusion?
Also, IRL, pure tin is sometimes used as a solder (with worse mechanical properties, requiring higher temperature to solder and prone to https://en.wikipedia.org/wiki/Tin_pest, but much less toxic), should we have that as well?

**Comment by Zireael07** [comment]
Lead fumes are poisonous, but yes, lead can be melted on a fire (my Dad did it once). It takes a long time though for it to reach the melting point.

**Comment by l29ah** [comment]
> the wire needs to be drawn after casting for use
Disassembling electronics produces solder w/o any such tooling, also solder blobs can be used as is IRL, although it's less usable in many cases.
Lead is dirt cheap: you have a lot of vehicles in game, each containing 5000 lead that is extractable with a hotplate.

**Comment by kevingranade** [comment]
> Disassembling electronics produces solder w/o any such tooling.

So thats a bug to be fixed, theres even an issue open for it.

>  you have a lot of vehicles in game, each containing 5000 lead that is extractable with a hotplate.

The question is whether its reasonable to use that lead to make solder, I don't know the answer,  it's just something I want an answer for.

**Comment by l29ah** [comment]
Okay, tin cans aren't such a good source of tin: https://en.wikipedia.org/wiki/Tin_can#Materials
We have pure tin in game though, it is less accessible requiring cooking 4 and electrolysis kit (50 copper wire and 10 solder), producing 10 tin from a can.

Curiously, my current character crafting screen shows much less tin-consuming recipes in "You could use it to craft:" thing than is present in the recipe list: for instance, there's no firearm ammo whatsoever. WTF?

> The question is whether its reasonable to use that lead to make solder, I don't know the answer, it's just something I want an answer for.

I don't see any problems with it.

**Comment by eilaattwood** [comment]
Oh, I wrote about flux and now remembered a nuance. Modern manufactured solder in form on wire usually has flux core inside of it - the wire is actually thin tube of solder filled with flux. flux core solder can be theoretically used for soldering without additional flux. When using other forms of solder you need to add flux manually. Rosin is widely used as a flux for soldering, but sorts of more advanced liquid flux also exist.

**Comment by l29ah** [comment]
When i was a child, i've successfuly used the pine resin collected from the surface of damaged pine trees as a soldering flux. It makes sense to use pine boughs, but we should explicitly mention that "solder" means "some form of solder and the corresponding amount of flux", and that means "solder" extraction from the existing electronics is going to become tricky.

**Comment by Zireael07** [comment]
Haha I wasn't saying the lead fumes are lethal My Dad's still alive :P

**Comment by Theundyingcode** [comment]
> It needs appropriate tooling, i.e. the wire needs to be drawn after casting for use.

How is wire crafted currently? There isn't a drawing plate (idk what they are actually called) in game but they aren't exactly hard to make.  Basically just a thick-ish steel plate with some various size holes drilled in it.  Ideally the holes are conical shaped for easier use but normal holes can work but are a lot more finicy to use.  Other than that you just need a pair of pliers and some space.  Heat would theoretically make it easier to draw but I have seen unathletic highschool girls draw silver so solder shouldn't be an issue.  Source: Highschool jewelry making class
