### ISSUE TITLE
Faction camp manager doesn't see food

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26604]
**Describe the bug**  
I've put it all over the tent but nope.

**To Reproduce**  
1. Load the save.
2. Talk with the manager about the food.

**Versions and configuration(please complete the following information):**
0.C-34167-ge91cc0338e-dirty

**Additional context**  
[Brightie BNW.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2566738/Brightie.BNW.zip)

**Comment by strife26** [comment]
Did you try resetting the drop points?

**Comment by l29ah** [comment]
Eh, well, if i set the points manually, they're right, but if i ask it to reset, it puts in insane coordinates.

**Comment by mlangsdorf** [comment]
Default sort points are:
food behind the manager
everything else mostly sorted in the crates.

That seems sane to me.

When you reset the sort points, if you're not careful, you can set them all to your current position.  That's not default, that's the result of the user interface being less than clear.

What would you like to see as non-insane default sort points?

**Comment by l29ah** [comment]
Load my save file. All the drop points' default locations are outside and far away from the tent.

**Comment by mlangsdorf** [comment]
Sort point interface was replaced by zone interface.  Closing.
