### ISSUE TITLE
Mini-reactor is always on regardless of setting.

### ISSUE THREAD

**Issue by Xion350** [CleverRaven/Cataclysm-DDA#26617]
**Describe the bug**  
After installation a Mini-reactior will continue to produce power whether it is turned on or off in the vehicle controls.

**To Reproduce**  
1: Install Mini-reactor into a vehicle (Preferably with an empty Storage battery)
2: Fill it
3: Look in Vehicle controls to see it is off
4: It will continue to produce power and drain plutonium cells regardless

**Expected behavior**  
It should respect the setting in Vehicle controls.

**Versions and configuration(please complete the following information):**
 - Windows Tiles Version 0.C-34224-g7b0e7c2
 - Mods loaded: Vehicle Additions Pack, Tanks and other Vehicles

**Comment by dommon** [comment]
Also empty (installed) mini reactor will spam shutdown messages, same issue, noticed that after rebasing yesterday

**Comment by Xion350** [comment]
They're probably related bugs.

**Comment by Josephos** [comment]
Attempted to fix it here: #26622
