### ISSUE TITLE
`Distribute food` faction camp order blackholes items

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26613]
**To Reproduce**  
1. Dump all your possessions into the food pickup point.
2. Order the manager to distribute it.
3. See all of them vanish.

**Expected behavior**  
Only food should've been taken.

**Versions and configuration(please complete the following information):**
 0.C-34167-ge91cc0338e-dirty

**Comment by mlangsdorf** [comment]
Will look into it.

**Comment by mlangsdorf** [comment]
Non-food items get moved to the appropriate sort point.  I've confirmed this in the code and experimentally.

**Comment by l29ah** [comment]
`Distribute food` in this save and observe 99 logs vanishing: 
[Brightie BNW.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2585745/Brightie.BNW.zip)

**Comment by mlangsdorf** [comment]
okay, will test again

**Comment by mlangsdorf** [comment]
This stinks. There's no good way to solve it.
