### ISSUE TITLE
Moving items into a storage with max items has multiple information pop-ups

### ISSUE THREAD

**Issue by Zetsukaze** [CleverRaven/Cataclysm-DDA#26614]
**Describe the bug**  
The dialog `Destination area is full. Remove some items first.` displays once for every item over the limit, and you have to cancel every single one of them before you can do other actions in the game.

**To Reproduce**  
1. Have a storage with remaining volume, but contains items up to the max (2048?)
2. Move a stack of items into the storage
3. Cancel the dialog once for every item attempted to be moved into the storage

**Expected behavior**  
The dialog should appear once, and have to be cancelled once. It should not attempt to move every item and get a warning for every one.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: Build 8140
 - Graphics version Tiles

**Additional context**  
Advanced Inventory Management was used

**Comment by Jerald-of-Libya** [comment]
Hmm. Can't say that I'm able to reproduce this using the base game on build 8142,

Advanced inventory notifies me whenever I try to [m]ove a stack of anything that exceeds the remaining volume for the target space/container. "Destination can only hold 1. Move how many? [Have 5] (0 to cancel)." Here, if I select more than 1, the game just ignores my input and only moves one item from the stack.

If I try to get around this using [,] to move all, it will prompt: "there isn't enough room, do you really want to move all?" If i hit yes, for vehicle containers, the items simply fall to the floor once the container fills up, and for a normal tile, the extra items simply overflow to some other tile.

**Comment by Zetsukaze** [comment]
Erm, do you still have spare volume? I'm trying with more than enough volume to spare (Cargo container) but not enough item count. Yours sounds like it hits the maximum volume.

**Comment by Zireael07** [comment]
Max number of items per tile is 4096 regardless of bitness.

**Comment by Zetsukaze** [comment]
![image](https://user-images.githubusercontent.com/1698993/48306610-9bf18b00-e576-11e8-9136-5f671e4b08f5.png)

As you can see, no limits on how many I want to move. If I select X, I have X amount of warnings appear.

**Comment by Jerald-of-Libya** [comment]
Dang.. I finally got it too appear too. Didn't work the first time because I was grabbed on to the vehicle. Looks like item counts aren't being tracked when you select a vehicle container using the 1-9 directional, but works fine when hitting <D> if you happen to be grabbing it.

Item count on the top is 4096/4096 for <D> on the left, but 0/4096 for the same container using <6> on the right:
![image](https://user-images.githubusercontent.com/44783693/48306829-613e2180-e57b-11e8-9442-ec2909e93f1c.png)

**Comment by int-ua** [comment]
Please verify it's still a problem.

**Comment by OliveChukar** [comment]
Tested in ver 0.E-9072-g1bb53ba-dirty. Put 4096 sd cards in a cargo space then tried to add 4 more by dropping them in and by using advanced inventory both with and without grabbing the vehicle. No messages appeared at any point. The items just fell on the ground under the vehicle.  The display bug that shows 0/4096 item count when the space is full is still there.
