### ISSUE TITLE
Items vanish when dropped on rubble

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26624]
**To Reproduce**  
1. Take an artifact located in the center of a huge pile of rubble.
2. Drop it into one of the pile tiles.
3. Clear rubble with your spade.

**Expected behavior**  
I should've been able to find it underneath!

**Versions and configuration(please complete the following information):**
0.C-34224-g7b0e7c29cf-dirty

**Comment by ZhilkinSerg** [comment]
Duplicate of #8979.
