### ISSUE TITLE
Shaded areas appear red

### ISSUE THREAD

**Issue by Dozed12** [CleverRaven/Cataclysm-DDA#26631]
**Describe the bug**  
Shaded areas appear red

**To Reproduce**  
1. Make a new world
2. Notice how shaded areas look red

**Expected behavior**  
Shaded areas should appear black/dark like they used to

**Screenshots**  
![bug1](https://user-images.githubusercontent.com/10583315/48305992-f7e2f200-e52b-11e8-81e9-c8a84ae24afa.png)

![bug2](https://user-images.githubusercontent.com/10583315/48306017-61fb9700-e52c-11e8-80fe-72fe2a496801.png)

**Versions and configuration**
 - OS: Windows 10
 - Game Version: 0.C-34268-g94a20a2
 - Graphics version: Same result for Tiles and Terminal
 - Mods loaded: Tested with and without mods

**Additional context**  
I tested with a clean game directory without any mods and both with tiles and terminal, same result.

**Comment by Zetsukaze** [comment]
Have the same issue, updated from build 8142 to 8144. 8142 was fine.

**Comment by scanevaro** [comment]
Same as me. From build 8142 to 8144 it's giving me the same.

**Comment by Josephos** [comment]
This might be related to:
https://github.com/CleverRaven/Cataclysm-DDA/pull/26465
