### ISSUE TITLE
Default ammo/ammo source

### ISSUE THREAD

**Issue by Shodan14** [CleverRaven/Cataclysm-DDA#26636]
So every time you reload or shoot a bow you're prompted to choose the ammo type. It's great to have different ammo types, but it gets a bit annoying to have to choose the ammo type each time I shoot my bow and have multiple ammo types in my inventory and/or within reach.

Would it be feasible to either have a separate key to (re)shoot/reload the last used ammo type or even better to designate the default ammo type or source (like a quiver) to use until it's depleted and then prompt the player?

I would love to play an archer with different arrows for different occasions, but having to choose the ammo for each shot makes it really annoying at the moment.

**Comment by l29ah** [comment]
Same thing with slings, except they don't have a quiver.

**Comment by Night-Pryanik** [comment]
Similar to #15702.
