### ISSUE TITLE
NPCs should assist with woodcutting activities.

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#26644]
NPC followers can assist with crafting and construction, but they can't (don't appear to) assist with woodcutting tasks performed via the axe action menu.  While this might not make tons of sense for felling a tree, chopping a downed tree should certainly be an assistable action.  The construction menu still has the trunk > planks action, which the NPC will assist with.  

My ideal solution would be to have nearby (and properly equipped, if that is possible to detect) NPCs assist with all woodcutting tasks.  

Additionally, moving the trunk > planks action out of the construction menu and into appropriate tool action menu would be useful as well - I had forgotten about that action until researching this interaction. It doesn't make sense to have the the NPCs assisting with just that action - woodcutting should be totally assistable or not at all. 

Edit: If NPCs do actually help, there should be some feedback in the log saying so.

**Comment by FulcrumA** [comment]
Extending the scope of this issue but there's quite a few places NPCs could help. Moving items with advanced inventory between tiles or sorting it out could probably also be sped up depending on the number of nearby guard and in-party NPCs.
