### ISSUE TITLE
Map memory only extends as far as the active window can "see".

### ISSUE THREAD

**Issue by Dalenacio** [CleverRaven/Cataclysm-DDA#26646]
**Describe the bug**  
Map memory only "remembers" what is on the active window. That means that if something is visible to the character but outside of the player's active window, it will not be remembered. This is affected among others by "z"ooming in and out, or by looking around (x).

**To Reproduce**  
1. Go in game underground or at night
2. Use light of some sort to illuminate a large area (I used headlights while driving at night)
3. After turning it off and moving, you will only "remember" that which your active window saw

**Expected behavior**  
I'd expect anything the character sees to be remembered, whether I had my active window over it, simply because map memory represents the character's memory, not the player's.

**Screenshots**  
![image](https://user-images.githubusercontent.com/12587061/48318225-2381dd00-e5fd-11e8-8a16-2839ff13860e.png)
(Here I was driving at night with my headlights on. I quickly went to furthest zoom then back to "normal" zoom. I only remember up to what I saw when my zoom was very far.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-34412-gd37cc74
 - Graphics version: Tiles
 - Mods loaded: Disable NPC needs, Filthy Clothing, No Fungal Monsters, More Survival Tools

**Additional context**  
This issue was reproduced by another user on the Discord.

**Comment by Josephos** [comment]
Can reproduce on:
OS: Linux 4.18.16
Game version: 0.C-34436-g003d91bd6b (Current git version)
Graphics version: Tiles
Mods: None
