### ISSUE TITLE
Possible bug related to deafness

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#26645]
**Describe the bug**  
I have a 10+ days long streak of being deaf and people at reddit report going deaf seemingly at random. Possibly related to vehicles.

**To Reproduce**  
I dunno. I tried starting a new game and I wasn't deaf then.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-34433-g1177ccf (and earlier versions. Could have started build 8040?)
 - Graphics version Tiles
 - Mods loaded   "dda",  "no_npc_food",  "filthy_morale",  "novitamins",  "makeshift",  "Medieval_Stuff",  "More_Survival_Tools",  "boats",  "deoxymod",  "blazemod",  "Tanks",  "more_locations",  "FujiStruct",  "national_guard_camp",  "DP_REMIX_INDICATORS",  "no_religious_Texts"

**Additional context**  
Reports from [reddit](https://www.reddit.com/r/cataclysmdda/):

> I can't figure this out. I walk into this uneventful patch of road and suddenly my ears blow out. There's no "ears are ringing!" effect, it just goes straight to "Deaf". There are no NPCs or monsters nearby -- it's the middle of nowhere -- and there's nothing in the log to suggest an explosion occured nearby. I am not mutated or irradiated.
> 
> The only thing of interest is a Waste Sarcophagus one map square south of this position. No spoilers, but could that be the source? Otherwise I'm inclined to think this is some kind of weird bug. I'm still waiting for my character to regain hearing several minutes later.

EDIT: From the same thread:

> The same thing happened to me, on build 8153. Think it might be a bug because I couldn't find anything strange going on either.

Also from the same thread:

> Playing a new game last night my character would lose and regain his hearing for no reason at all.

https://www.reddit.com/r/cataclysmdda/comments/9w467t/character_deafened_in_particular_map_square_for/

> 
> I'm having an issue with random "Your ears ring!" messages and a "Deaf" status being applied. I think the common factor is that I've been pushing either a shopping cart or wheelbarrow every time, but I can't think of any reason why pushing/pulling a cart around would cause deafness.
> 
> Edit: I just had it happen out of nowhere without having a cart, so that rules that out.

https://www.reddit.com/r/cataclysmdda/comments/9uw2xz/new_players_come_here_weekly_questions_and/e9h16pg/

> Can you get permanently deaf? I've been deaf for over a week now in-game time.

https://www.reddit.com/r/cataclysmdda/comments/9uw2xz/new_players_come_here_weekly_questions_and/e9f1yav/

**Comment by Shodan14** [comment]
Have also gone randomly deaf while just running around shooting my bow at zombies. Quite weird.

**Comment by ampersand55** [comment]
Probably unrelated, but my character is also a bow user.

**Comment by ampersand55** [comment]
Is there any way to remove deafness from the .sav-file while I wait for this bug to be resolved? There is an NPCs I would like to talk to. It isn't a status effect, it just says I'm deaf.

**Comment by Inglonias** [comment]
Are Z levels active? It's possible you're standing over a lab or something. The zombies in there can be quite loud.

**Comment by strife26** [comment]
> 
> 
> Is there any way to remove deafness from the .sav-file while I wait for this bug to be resolved? There is an NPCs I would like to talk to. It isn't a status effect, it just says I'm deaf.

Yes, if you look at the .sav file for the character in the world folder, you can search for the "deaf" effect and change its duration.

**Comment by ampersand55** [comment]
> Are Z levels active? It's possible you're standing over a lab or something. The zombies in there can be quite loud.

Not for me.

**Comment by ampersand55** [comment]
> 
> 
> > Is there any way to remove deafness from the .sav-file while I wait for this bug to be resolved? There is an NPCs I would like to talk to. It isn't a status effect, it just says I'm deaf.
> 
> Yes, if you look at the .sav file for the character in the world folder, you can search for the "deaf" effect and change its duration.

Tried that, and didn't find anything. As mentioned, it doesn't show up as a status effect in the character window, it just say "Deaf!" in red letters in the right tab, just under "Lighting: Bright"

**Comment by l29ah** [comment]
I've encountered this as well. Maybe related to ants?

**Comment by Muffindrake** [comment]
I've encountered this routinely, with my character going deaf for several hours at a time, usually when I was about to crack a bank safe (which you can't do while deaf).

I play in a 16 city size, 0 spacing world that has a massive city I'm inside most of the time, so I would start looking there rather than anywhere else. Sadly I can't find the reason to reproduce this bug reliably.

**Comment by gynoidgearhead** [comment]
Is there a lab anywhere nearby when this happens? I've had cave-ins related to giant naked mole rats produce _really_ loud noises that have deafened my character before. It's gotten to the point where I've thought about writing a mod that blacklists giant naked mole rats and other digger monsters.

**Comment by TehBakey** [comment]
I'm having the same issue, was moving a car at low speed in my home base, a pretty quiet area, when I suddenly get the message "Your ears are ringing" and I go deaf. The trait doesn't show up in the Status Screen nor can I find the 'Deaf' tag in my save file. I do have Z-Levels active.

**Comment by GoLoT** [comment]
Did some digging through my backups and found the world where I had this bug happen. I already killed all enemies through the debug menu and left the game in a state where moving around or waiting for a few turns causes the bug to happen. The area where it happens seems to span the road from the point where the character is up until the motel. Since all enemies are dead and it happens constantly in that area it can't be something firing a loud gun or causing a collapse/explosion. I tried teleporting to lower z-levels but I ended up stuck inside rock so I'm guessing it isn't something underground making noise.

Link here: [Savegame](www.dropbox.com/s/vvbx1pszex6e43v/DeafnessBugSave.rar?dl=1)

**Comment by AMurkin** [comment]
This is Hippie Van to the south doing ambient backfire sound "BANG!" with volume 7810.
Debugging this.

**Comment by AMurkin** [comment]
Probably caused by #26353

**Comment by AMurkin** [comment]
Pinging @mlangsdorf 
Shouldn't this be changed to 30 / 373 instead of 12?
![default](https://user-images.githubusercontent.com/1931904/48789240-aa217300-ecfd-11e8-84a9-1b79c3a4a257.png)

**Comment by mlangsdorf** [comment]
30 / 373 = 1 / 12.5
373 * old_power / 12 = 30 * old_power
yeah, I got the math wrong.

new_power = old_power * 373
new_power / 373 = old_power
old_power / 30 = sound
new_power / ( 30 * 373 ) = sound
new_power / 10,000 = sound
