### ISSUE TITLE
Display scenario in message window at the start

### ISSUE THREAD

**Issue by rumly111** [CleverRaven/Cataclysm-DDA#26649]
So the root of the problem is that when I start a random character, I don't know which scenario I'm
 playing. I can only guess based on my location etc.

At the start of the game the scenario story (which I can see in the character creation window), also maybe the character profession description should be dumped to message log.

Alternatively, this information could be seen through some other means, like the menus.

**Comment by kevingranade** [comment]
Why does it matter which scenario it is?

**Comment by Shoes01** [comment]
I could see it being nice having a little blurb at the start of the game sort of explaining what is up. Doesn't Dwarf Fortress do that in Adventure mode? It could also inform the player of a bit of lore.

**Comment by AMurkin** [comment]
Yes, immersion matters. It would be good to have.

**Comment by AMurkin** [comment]
After reading the backstories in #27174 and recalling that the PC can have dreams, I had the idea that the first dream of the PC could have a description of its life before the cataclysm.
Thus revealing the scenario and the profession.
