### ISSUE TITLE
JSON coding style

### ISSUE THREAD

**Issue by i2amroy** [CleverRaven/Cataclysm-DDA#2665]
We need to decide on a standardized JSON style, since they are becoming more and more jumbled as new code is added. I don't know if there are options for jsons similar to what we used for the normal code, but here's my personal votes:

1 space before and after colons
```c++
  "autolearn" : true,
```
no spaces between brackets and flags
```c++
 ["firstaid", 5],
```
No empty line between entries
```c++
    "category" : ["MUTCAT_SPIDER"]
},
{
    "id" : "PARKOUR",
```
Multiple tools/components are placed on separate lines
```c++
[
    [ "screwdriver", -1 ],
    [ "toolset", -1 ]
],
```
And to use 4-space indentation with 1TBS style where needed
```c++
},
{
    "result" : "bio_power_armor_interface",
    "category" : "CC_ELECTRONIC",
    "skill_used" : "electronics",
    "requires_skills" : ["firstaid", 5],
    "difficulty" : 6,
    "time" : 50000,
    "reversible" : true,
    "autolearn" : true,
    "tools": [
        [
            [ "screwdriver", -1 ],
            [ "toolset", -1 ]
        ],
        [
            [ "soldering_iron", 20 ],
            [ "toolset", 2 ]
        ]
    ],
    "components": [
        [
            [ "power_supply", 2 ]
        ],
        [
            [ "amplifier", 2 ]
        ],
        [
            [ "burnt_out_bionic", 1 ],
            [ "processor", 2 ]
        ]
    ]
},
{
```

One question that I'm not sure about is the initial indent. Every json file is contained within a giant set of [], should every single line be indented 4 spaces? Or should that initial indent be dropped?

**Comment by mugling** [comment]
> an we get a pritifier to do that?

We now have a JSON lint tool
