### ISSUE TITLE
fear_paralyze permastun if lower than normal speed

### ISSUE THREAD

**Issue by Lorith** [CleverRaven/Cataclysm-DDA#26663]
**Describe the bug**  
Three of the four monsters with fear_paralyze lack any cooldown, and thus they can permastun you due to giving five turn immunity and taking 400 action points -- if you are slower than normal, you may take more than five turns to produce 400 action points, letting them stun you again, making you require even longer before you can act.

**To Reproduce**  
1. Make a character of any sort with 8 int, apply debug invulnerability and set pain to 100 to drop to 75 speed
2. Spawn one blood sacrifice mob (since it doesn't move and has no ranged attack) and attempt to do any action
3. Sometimes fine, sometimes locked into stun for significant amounts of time
4. Set pain to 500 with debug to drop action points to 50 and try to do anything, get locked into stun until you die, pain goes away, or the game freezes (problematic if the issue is a mutation or artifact that slows you down, or cold, instead of pain, as none of those are going away)

**Expected behavior**  
Lose the same number of turns regardless of action speed, or at least not die/crash due to utter inability to act at all even if the mob is harmless (such as the blood sacrifice at a distance)

**Versions and configuration(please complete the following information):**
 - OS: [Win7]
 - Game Version [8152 (0.C-34440-geca4878)]
 - Graphics version [Tiles]
 - Mods loaded [ "dda", "no_npc_food", "filthy_morale", "novitamins" ]

**Additional context**  
Issue was reported [on reddit](https://www.reddit.com/r/cataclysmdda/comments/9vi2dk/this_was_no_fun/)

**Comment by OrenAudeles** [comment]
This looks suspiciously similar to the "Vomit-loop" issue, with slightly less guaranteed death.

**Comment by Lorith** [comment]
It is basically the exact same thing as both that and the ignored remote monster spawn crash - the game keeps subtracting action points that you don't have, and you have to generate enough to get positive before you can try to act.  But during the time it tries to generate those points, it gets hit with more negative than it generated, leading to an endless cycle of trying to catch up to zero.

Basically numerous spots in the code assume you will always have 100 action points per turn and put their assumptions on that.  Go mycus for -20 speed and carry a speed reducing artifact for another -20 speed and this will happen even when warm and healthy with zero pain, which will result in death unless your int is high enough to beat the check most of the time.  Likewise if you have quick, you gain extra speed, add in some drugs, and you won't be stunned for four turns, because your speed will be well over 100.
