### ISSUE TITLE
Makeshift crowbars lose some of the combat qualities the pipe used to craft it has.

### ISSUE THREAD

**Issue by preacherpix** [CleverRaven/Cataclysm-DDA#26678]
**Describe the bug:**  
Examining a pipe reveals that it has a medium blocking quality, whilst a makeshift crowbar crafted using the same pipe loses that entirely.

**To Reproduce:**  
1. Acquire two pipes.
2. Craft one into a makeshift crowbar, leave the other stock.
3. Compare stats.

**Expected behavior:**  
I'd imagine that, as long as we're only bending the ends of the pipe as the description suggests, there's no real reason for this to lose its blocking quality. In the end, it is still a metal tube, just with different ends. We should still be able to put this between us and any danger attacking us.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10.
 - Game Version: 0.C-34436-g003d91b
 - Graphics version: Tiles.
 - Mods loaded: Base game files.

**Comment by Xion350** [comment]
Bending the ends of a pipe would make it harder to use effectively in that regard.

**Comment by Pupsi-Mupsi** [comment]
since every type of crowbar seems to have the mentioned melee techniques - even the pipe itself has it - and i can't think of a reason not add it.... well, there you go. thanks for contrubuting to the game
