### ISSUE TITLE
Add SomeDeadGuy's Xotto tileset to build

### ISSUE THREAD

**Issue by rainbowjose** [CleverRaven/Cataclysm-DDA#26676]
https://i.imgur.com/PNNQ8T3.png

https://github.com/SomeDeadGuy/Cata-MSX-DeadPeopleTileset

**Comment by Lorith** [comment]
I agree, but it is his choice if he wants to try to have it added or not.  Ask him to put in a pull request and it can be considered by the folks who can merge things.

**Comment by Leland** [comment]
Pinging @SomeDeadGuy

**Comment by rainbowjose** [comment]
Disadvantages for you? I think community can handle maintaining of this tileset, isn't?

**Comment by Lorith** [comment]
Every update would require going through a number of people to verify, have to worry about possible issues with the team over content on multiple levels, slower update speed, and numerous other issues.  He said no, so it probably won't be going in unless he changes his mind.

**Comment by rainbowjose** [comment]
> Every update would require going through a number of people to verify, have to worry about possible issues with the team over content on multiple levels, slower update speed, and numerous other issues. He said no, so it probably won't be going in unless he changes his mind.

But theres so much shitty, outdated tilesets present in build now. And here a really high-quality tileset, which someone will probably support, and the author himself has not yet abandoned him at all, he simply does not like all this red tape.

**Comment by SomeDeadGuy** [comment]
raibowjose you do not have to ask me for permissions, my tileset is free and can be taken by anyone and be edited or added to mainframe if they want it
Just call it something other then MSX_DeadPeople (MSX_AlivePeople?) so people would not confuse the two. Cause my still going to be better. :P

**Comment by rainbowjose** [comment]
> raibowjose you do not have to ask me for permissions, my tileset is free and can be taken by anyone and be edited or added to mainframe if they want it
> Just call it something other then MSX_DeadPeople (MSX_AlivePeople?) so people would not confuse the two. Cause my still going to be better. :P

Okay.

**Comment by ZhilkinSerg** [comment]
We should have some infrastructure to store and retrieve tilesets from some network locations - that would make tileset maintenance easier. It is more a work for a launcher and it is a planned version there https://github.com/remyroy/CDDA-Game-Launcher/blob/master/README.md

**Comment by ZhilkinSerg** [comment]
Also we can have barebone tileset in the main repo with only basic tiles (e.g fallback.png) and all the other tiles bundled through tileset mod which is not in the main repo - 
https://github.com/CleverRaven/Cataclysm-DDA/pull/25633 (which already could be managed by launcher).

**Comment by AMurkin** [comment]
For that we need crossplatform launcher first.

**Comment by Leland** [comment]
Closing – per the author, feel free to open up a PR with the changes
