### ISSUE TITLE
Diamond coated weapons not gaining vorpal flag

### ISSUE THREAD

**Issue by Zetsukaze** [CleverRaven/Cataclysm-DDA#26672]
**Describe the bug**  
Kill a Jabberwock with a diamond coated weapon, do not get the vorpal flag. The killing blow has to push the Jabberwock back one step.

**To Reproduce**  
1. Make a player with a diamond coated weapon
2. Kill a Jabberwock with a blow that sends it reeling
3. Corpse ends up one tile away from you, and you do not get the death message event

**Expected behavior**  
Murder Jabberwock with diamond weapon, get vorpal flag.

**Screenshots**
![image](https://user-images.githubusercontent.com/1698993/48426182-31706300-e7a1-11e8-9299-aec72dbacd3e.png)

**Additional context**  
In mondeath.cpp
```cpp
bool vorpal = ch && ch->is_player() &&
rl_dist( z.pos(), ch->pos() ) <= 1 &&
ch->weapon.has_flag( "DIAMOND" ) &&
ch->weapon.volume() > units::from_milliliter( 750 );
```
As seen above, the vorpal boolean will be false if the the distance between the monster and the player is more than 1, and thus the weapon will not get the vorpal flag.

**Comment by Night-Pryanik** [comment]
There could be a lot of reasons for this. For example, you could deal the damage via your fangs, kill the jabberwork with them, then immediately deal illusionary damage with your diamond-coated to the already-dead jabberwork.

**Comment by Lorith** [comment]
Confirmed in 8152 (0.C-34440-geca4878) with debugged diamond katana and brawling, no mutations, no electroshock.  Killing with a blow that made it go reeling did not result in vorpal being added, but switching off styles and killing another one in melee range did add it.
