### ISSUE TITLE
Impossible to wear a swag bag with a power armor

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26700]
**Describe the bug**  
If i can hold and use various guns and melee weaponry including pistols and knuckles, what's wrong with holding a bag full of goods i've bought at a nearby mall?

**Comment by kevingranade** [comment]
Because youre wearing it instead of wielding it.

**Comment by l29ah** [comment]
But it cannot contain stuff when i'm welding it for some reason.
