### ISSUE TITLE
Jabberwock not spawning from mission

### ISSUE THREAD

**Issue by Trokinos** [CleverRaven/Cataclysm-DDA#26717]
using CDDA experimental build 8166 ( 34487 gd84de37) i have taken several "eater of the dead" type of missions from various NPC that are supposed to spawn a Jabberwock at a given location.

Problem is that no Jabberwock in any of those missions were ever spawned at those given locations (and in all map tiles around them that i explored in any ways) not too far from my several time upgraded Faction Camp (in case it has an importance in this bug).

I suspect the bug may be coming from the fact the world i'm playing with has "Classic Zombies" set to True
When searching around i found this , probably explaining why i am observing this bug
https://github.com/CleverRaven/Cataclysm-DDA/issues/1973
https://github.com/CleverRaven/Cataclysm-DDA/pull/2046

If that's indeed the source of this problem, maybe it is affecting more missions that spawn non-classic monsters too  ?

**Comment by kevingranade** [comment]
The blacklist mods and classic mode provide no guarantee that the game remains consistent when they're enabled.  If you want a more consistent game, play with default settings.

**Comment by Trokinos** [comment]
Maybe it should be mentionned in the description of those blacklist mods (and in the world default too as the Classic mod is a world default option) that they will break those type of missions then instead of monsters generated by those missions being replaced by normal zombies, so people are fully aware what's going to happen.

**Comment by kevingranade** [comment]
This is the case with every option and every mod, we're not going to add a disclaimer to every one.

**Comment by Kelenius** [comment]
If Jabberwock is blacklisted, the mission shouldn't be given.
