### ISSUE TITLE
Inconsistent planks production skill requirement in Construction and hatchet Action

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26729]
One can cut a tree trunk into logs and then into planks using the hatchet's action menu w/o any skills apparently, while using the construction menu requires one to have survival (2).

**Comment by davidpwbrown** [comment]
Currently you can use toolbox to cut down trees, it has AXE:1 quality.
Using a hatchets action menu on a trunk, takes 27 minutes, and produces 10 two by fours and 104 splintered woods, from 3 logs, as much is lost
Using the construction menu, seems to have similar rate/chance of wastage, took 1 hour, and produced 3 two by fours, and 63 splintered woods.
Higher skill requirement, more time, less yield.

Which is preferred, the construction menu method or the use item method?

**Comment by Night-Pryanik** [comment]
> Which is preferred, the construction menu method or the use item method?

Iuse method.

**Comment by I-am-Erk** [comment]
Iuse might be the preferred action, but I got the numbers for the construction action from reading about hewing and crafting lumber. It takes skill and a lot more time than half an hour.

How are you only getting three planks from the recipe? Are you sure that wasn't panels? The recipe should be producing eight planks.
