### ISSUE TITLE
More Locations mod: butcher.json contains bag_meat_vac

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#26749]
**Describe the bug**  
 DEBUG    : item id bag_meat_vac is unknown
 
 FUNCTION : virtual void Single_item_creator::check_consistency() const
 FILE     : src/item_group.cpp
 LINE     : 116

This message is shown when loading a world with More Locations installed. It can be passed through with no problems. Editing butcher.json and replacing bag_meat_vac with meat_salted makes the error go away.

**To Reproduce**  
Create or load a world with More Locations mod installed

**Expected behavior**  
No errors on Load.

**Screenshots**  
butcher.json:
![image](https://user-images.githubusercontent.com/16219776/48668836-fa10f780-eabb-11e8-8ed6-bdb697cf2b21.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.c-34606-g481f164
 - Graphics version [Tiles]
 - Mods loaded [[
  "dda",
  "safeautodoc",
  "craftgp",
  "brightnights",
  "dda-lua",
  "dda-lua-fun",
  "dda-lua-items",
  "dda-lua-skills",
  "dda-lua-traits",
  "StatsThroughKills",
  "speedydex",
  "add_ebook",
  "no_npc_food",
  "filthy_morale",
  "manualbionicinstall",
  "no_reviving_zombies",
  "sleepdeprivation",
  "StatsThroughSkillsThree",
  "DP_XOTTO_INDICATORS",
  "Tolerate_This",
  "Hairs",
  "necromancy",
  "SD_Magcrafting",
  "realguns",
  "SD_Magcrafting_Realguns_Extension",
  "FIC_Weapons",
  "ew_pack",
  "nw_pack",
  "NM_wpns",
  "antifunguskit",
  "Arts' Guns",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "MST_Extra",
  "SD_Winterclothes",
  "SD_Batcon",
  "a_mutated_arsenal",
  "ArmUpSurvEx",
  "ArmUpPAUtil",
  "Airdrops_n_Alchemy",
  "adv_gear",
  "bio_mod_Malkeus",
  "with_extra_mushrooms",
  "WHALEYCRAFTS",
  "Pix's Shit",
  "Mutation_Changes",
  "Nechronica_M",
  "npc_traits",
  "mutant_npcs",
  "more_classes_scenarios",
  "RL_Classes",
  "Urban_Development",
  "Experimental-Z-Level",
  "BIGOLBUILDING",
  "cityside",
  "SEEDYSPOT",
  "more_locations",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "national_guard_camp_M",
  "mapgen_demo_M",
  "Dorf_Life",
  "Mining_Mod",
  "jury_rigged_robots",
  "modular_turrets_M",
  "Salvaged_Robots_M",
  "Bootleg_Walkers",
  "DracoDogMod",
  "DinoMod",
  "GOV_BANDITS",
  "40K",
  "vamp_stuff",
  "porawep",
  "boats",
  "blazemod",
  "Tanks",
  "deoxymod",
  "blaze_extension_M",
  "shardstuff",
  "shardsOtherStuff",
  "Arcana",
  "cddaxp_Malkeus",
  "Maddremor_bundle",
  "Cata++",
  "Cata++hairs",
  "PK_REBALANCE",
  "PK_REBALANCE_hairs",
  "winning_dda",
  "MGCPatch",
  "alt_map_key"
]]

**Additional context**  
Apologies for the blank message...I hit enter at a bad moment.

**Comment by OrenAudeles** [comment]
Please fill in the template with information relating to the issue. The title is not enough to work from.

**Comment by Malkeus** [comment]
Yeah, sorry about that. All done now.
