### ISSUE TITLE
Acid Ant larvae not immune to acid

### ISSUE THREAD

**Issue by JacobKessler** [CleverRaven/Cataclysm-DDA#26743]
**Describe the bug**  
The larvae that appear in sulfurous ant hives aren't immune to acid, and so die rapidly from the acid that ends up covering everything.

**To Reproduce**  
 - Enter a larvae chamber in an acid ant hill
 - Observe all of the larvae die to acid splatter

**Expected behavior**  
Ants shouldn't be murdering their own young with their acid trails

**Versions and configuration(please complete the following information):**
 - O.C-33849-gcd5965ed4a

**Comment by DracoGriffin** [comment]
RL equivalents don't either; the chitin isn't formed well enough and thus susceptible.

However, I think the acid ants could lose the acid_trail (since there isn't a cooldown/setting for the "flow" of leakage) so that would alleviate the issue.

**Comment by FulcrumA** [comment]
Eliminating trails of acid would also help with issues such as #25054

**Comment by I-am-Erk** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/26896
