### ISSUE TITLE
Grabbing a cart into deep water will cause debug message

### ISSUE THREAD

**Issue by 3721assistant** [CleverRaven/Cataclysm-DDA#2674]
You can grab a cart into deep water, and then pull it back, but then it will continuously show the debug message of cant find vehicle or something.
##

**Comment by eliotcougar** [comment]
0.C-19186-g23a9665 (tiles)
Tried pushing cart into deep water and jumping there, pulling it back, every other combination... Trying to dive (>) does not work as expected...
Tried jumping from a vehicle (unicycle) into deep water, and back up no problem... (driving it into deep water actually sank it)... Pushing it there does not sank it, but you cannot drive out of there or dive at that spot... Diving at the spot does not make you board the vehicle... Again, nothing supernatural...
No debug messages...
Issue is probably solved...

**Comment by Oskar636** [comment]
This isn't reproducible. Everything happens just like eliotcougar said. Bbuild 5864 windows 64bit console.

**Comment by Night-Pryanik** [comment]
Should be closed?
