### ISSUE TITLE
Stone spear can't be stored in spear strap

### ISSUE THREAD

**Issue by Centac** [CleverRaven/Cataclysm-DDA#26747]
**Describe the bug**  
The stone spear can't be stored in a spear strap.

**To Reproduce**  
Give yourself a spear strap and a stone spear. Activate the spear strap.

**Expected behavior**  
The spear strap can store knife spears, wooden spears, steel spears, pipe spears, etc. However, the More Survival Tools stone spear can't be stored in spear straps. I can't think of a reason why the stone spear shouldn't be able to be stored while other types of spears can be stored.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-33359-gfbe9044
 - Graphics version: Tiles
 - Mods loaded: More Survival Tools

**Comment by Pupsi-Mupsi** [comment]
Could probably be fixed by adding **SHEATH_SPEAR** flag to:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/More_Survival_Tools/items.json   Line 323.

```
  {
    "id": "spear_stone",
    "type": "GENERIC",
    "name": "stone spear",
    "description": "A stout wooden pole with a sharp stone spearhead.",
    "weight": 1098,
    "volume": 5,
    "price": 1300,
    "to_hit": 1,
    "bashing": 5,
    "cutting": 14,
    "material": [ "wood", "stone" ],
    "symbol": "/",
    "color": "light_gray",
    "techniques": [ "WBLOCK_1" ],
    "qualities": [ [ "COOK", 1 ] ],
    "flags": [ "SPEAR", "REACH_ATTACK", "SHEATH_SPEAR" ]
  },
```
