### ISSUE TITLE
Back and Front Torso Slots

### ISSUE THREAD

**Issue by hyper2snyper** [CleverRaven/Cataclysm-DDA#26754]
Dear CleverRaven
     So, one of my biggest pet peaves in this game is when i have a leather backpack and a chest ammo pouch or two and since they are both "strapped to me" they all give extra encumbrance. My proposal is to make another slot that clothing can be on called "back". Backpacks, runner packs, etc. would go in this slot and thus not give extra encumbrance to ammo pouches worn on your front. Another small idea would be to add a shoulder slot, weapons with slings on them can go on either your back, or a shoulder. This would mean you could wear a backpack without the extra encumbrance of deciding its a great idea to have your gun with a sling worn around your stuffed backpack.
Thanks in advance
               - Hyper

**Comment by kevingranade** [comment]
This is working as intended, the backpack and chest rig straps, along with other parts of the articles overlap each other and would IRL reduce  available range of motion of the wearer.

From a game balance point of view as well, it is intended that these storage articles conpete for the same encumbrance slots.
