### ISSUE TITLE
Eternal season still has changing seasons

### ISSUE THREAD

**Issue by Rolphaline** [CleverRaven/Cataclysm-DDA#26756]
**Describe the bug**  
Im playing with eternal seasons on summer, but the season still changes every 91 days while still saying its summer, and I can tell cause it snows, and everything freezes after the 91 days ticks twice.

**To Reproduce**  
I just let time pass. 

**Expected behavior**  
Ideally also describe *why* you expect it to happen.

Snow every year

**Screenshots**  
![snow](https://user-images.githubusercontent.com/45139839/48670621-431e7700-eacf-11e8-904e-602b539718fb.PNG)

**Versions and configuration(please complete the following information):**
 Windows 10
 0.C-34540-gb6aae03
Chesshole
Dark Days Ahead, Disable NCP Needs, Simplified Nutrition, Craftable Gun Pack, Safe Autodoc, Bright Nights, Extended Realistic Guns, More Survival Tools,Boats, Vehicle Additions Pack, Boats, Tanks And Other Vehicles.

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

I don't know how to link a save

**Comment by FulcrumA** [comment]
>I don't know how to link a save
You can either pack and upload the save somewher eand drop the link or, even better (though a size may sometimes cause issues here) pack it and then use the field in the lower portion of the comment text field where it says "Attach files by dragging & dropping, selecting them, or pasting from the clipboard."

**Comment by TechyBen** [comment]
I don't care what you say about seasons... I see a much bigger thing bugging me there about that screenshot... like... WHAT is that thing you are building?

**Comment by AskaHope** [comment]
I must agree with TechyBen, what the heck is that!?

**Comment by Rolphaline** [comment]
Its My Tank, Home, base, metal gear.... in the works.

**Comment by Rolphaline** [comment]
> > I don't know how to link a save
> 
> You can either pack and upload the save somewher eand drop the link or, even better (though a size may sometimes cause issues here) pack it and then use the field in the lower portion of the comment text field where it says "Attach files by dragging & dropping, selecting them, or pasting from the clipboard."

so drop the world file, in here?

**Comment by Rolphaline** [comment]
I'll Tour it when its done =)

**Comment by FulcrumA** [comment]
@Rolphaline 
>so drop the world file, in here?
That should do, yeah. Make sure the save is just from before the error occurs so it's easy to trigger.

**Comment by Rolphaline** [comment]
> @Rolphaline
> 
> > so drop the world file, in here?
> 
> That should do, yeah. Make sure the save is just from before the error occurs so it's easy to trigger.

The error starts from the very start

**Comment by Rolphaline** [comment]
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2597281/save.zip)

I hope it did that right, anywho it doesnt matter which world, it still happens. just debug a thermometer in and watch it change day after day. FYI the tank is in Boomer

**Comment by GimmeCat** [comment]
Can confirm: My eternal Winter, after a few 'seasons' passed, started giving me daytime temps of 19c and nights around 16c. The ground tiles still look white like snow, but it hasn't snowed for a long time, only rain. My gear hasn't changed and what once barely protected me from frostbite is now making me overheat.

Here's my save: https://www.dropbox.com/s/3inzqysmnh1z8za/East%20Glacier.7z?dl=0

**Comment by fuckthatshit** [comment]
also related to #31015

**Comment by MoogieOuttaMyDepth** [comment]
Could this be the problem? In weather_gen.cpp at line 62:

```
    const double year_fraction( time_past_new_year( t ) /
                                calendar::year_length() ); // [0,1)
    result.cyf = std::cos( tau * ( year_fraction + .125 ) ); // [-1, 1]
```

It seems to assume the seasons will change, applying a variation based on how long through the year it is, but not based on what the actual season is.

Would this work?

```
    if ( calendar::eternal_season() ) {
        result.cyf = 0
    } else {
        result.cyf = std::cos( tau * ( year_fraction + .125 ) ); // [-1, 1]
    }
```

Not knowledgable enough to test this myself, this is just a punt because I've been hangering for a fix to this for a very long time.

**Comment by actual-nh** [comment]
Is this still happening with the latest experimental?

**Comment by MoogieOuttaMyDepth** [comment]
> 
> 
> Is this still happening with the latest experimental?

Probably, I don't see any mention of it being fixed.

**Comment by actual-nh** [comment]
See #48557 (and possibly #48090).

**Comment by MoogieOuttaMyDepth** [comment]
> 
> 
> See #48557 (and possibly #48090).

He didn't test whether the temperatures stayed the same over the passage of time, only that they were appropriate on starting a new game. I'll try to test this myself tomorrow, since I'm still eyeing that bit of code I posted above with more than a little suspicion.

**Comment by actual-nh** [comment]
Ping: @Hirmuolio, @jbytheway?

**Comment by Kozakow** [comment]
> Is this still happening with the latest experimental?

I can confirm that as of 0ad2fdd the bug still persists. After about half a year the temperatures as low as -17 C while it is supposed to be summer. As for the newest (17.12.2021) experimental the situation is the same

**Comment by MoogieOuttaMyDepth** [comment]
I'd legit pay someone to fix this at this point. Tried another fix myself this year (it's become an annual tradition) but I still suck too much at coding, it wouldn't compile. I'm convinced it's that "result.cyf" line in weather_gen.cpp though. Seems like such a simple thing. I just couldn't figure out the correct syntax.

All I want for Christmas 2022 is an eternal winter in Cataclysm.

**Comment by jbytheway** [comment]
Your comment has caught me at an opportune moment when I was searching for something to do, so I shall take a look at this.

**Comment by LeahLuong** [comment]
I think there used to be a bounty system here where you could post a $ amount for solving an issue.

@MoogieOuttaMyDepth If it's still in effect, you should put your $ where your mouth is.
