### ISSUE TITLE
More Clothing Mods

### ISSUE THREAD

**Issue by hyper2snyper** [CleverRaven/Cataclysm-DDA#26762]
The Tailoring kit currently can only pad clothing with kevlar, nomex, and leather. An idea would be to give the option of the adding dump pouches, magazine satchels, bandoleir loops, and tool loops to certain clothing, this would make more storage available for the tradeoff of encumbrance. Perhaps allow clothing to have metal plates inside them, or a grenade pouch attached to your trench coat for the tradeoff of using some of the trenchcoat's available space to change into a grenade pouch.

**Comment by kevingranade** [comment]
This has been proposed before and has been rejected.

See https://github.com/CleverRaven/Cataclysm-DDA/issues/13365 for details.
