### ISSUE TITLE
Radio Pipe Bombs are significantly stronger than their non-radio versions.

### ISSUE THREAD

**Issue by Xion350** [CleverRaven/Cataclysm-DDA#26778]
**Describe the Issue**  
Despite using the same amount of explosives, radio Pipe bombs are set to have absurd amounts of power, range and shrapnel.

**Expected behavior**  
Given that the Radio pipe bomb only adds some electronic bits and a pilot light to ignite, the discrepancy is odd.  They should have the same power and range.  Just a different activation method.  Dynamite and Radio Dynamite have the same power.

**Screenshots**  
Normal Pipe bomb: 
![image](https://user-images.githubusercontent.com/13670135/48768921-fa59f000-ec7f-11e8-91e2-9d645496a4c2.png)

Radio Activated Pipe Bomb: 
![image](https://user-images.githubusercontent.com/13670135/48768806-b8c94500-ec7f-11e8-9e30-a7aca8cdb740.png)

**Comment by ZhilkinSerg** [comment]
Four pipe bomb items are highly inconsistent:

- radio pipe bomb weight is 0.18 kg, while activated radio pipe bomb weights is 1.57 kg (basic 1.30 kg);
- radio pipe bomb volume is 0.25 L, while activated radio pipe bomb weighs 1.00 L (basic 0.50 L);
- radio pipe bomb has no price (basic has price of 15$);
- radio pipe bomb can't be disassembled (basic can);

- iuse action differs between radio pipe bomb

```JSON
    "use_action": {
      "type": "explosion",
      "no_deactivate_msg": "You can't disarm your %s.  Place it, get away, and use the remote control to detonate.",
      "explosion": { "power": 500, "shrapnel": { "casing_mass": 500, "fragment_mass": 1.0 } }
    },
```

and basic pipe bomb (obsolete hardcoded explosion action) :

```JSON
"use_action": "PIPEBOMB_ACT",
```

```CPP
int iuse::pipebomb_act( player *, item *it, bool t, const tripoint &pos )
{
    if( pos.x == -999 || pos.y == -999 ) {
        return 0;
    }
    if( t ) { // Simple timer effects
        //~ the sound of a lit fuse
        sounds::sound( pos, 0, _( "ssss..." ) ); // Vol 0 = only heard if you hold it
    } else if( it->charges > 0 ) {
        add_msg( m_info, _( "You've already lit the %s, try throwing it instead." ), it->tname().c_str() );
        return 0;
    } else { // The timer has run down
        if( one_in( 10 ) ) {
            // Fizzled, but we may not have seen it to know that
            if( g->u.sees( pos ) ) {
                add_msg( _( "The pipe bomb fizzles out." ) );
            }
        } else {
            g->explosion( pos, rng( 10, 24 ), 0.6, false, rng( 0, 4 ) );
        }
    }
    return 0;
}
```
