### ISSUE TITLE
Strength lifting check on vehicle engine removal succeeds when it shouldn't

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26770]
**Describe the bug**  
I have a str14 char yet i can remove the engine from a Road Roller that requires str18.

**To Reproduce**  
Load the save and check it out.

**Versions and configuration(please complete the following information):**
4b82451a955e66a84d4b59943e1ede87150a840b

**Additional context**  
[2018.11.17.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2596501/2018.11.17.zip)

**Comment by l29ah** [comment]
Same thing with swappable storage batteries.

**Comment by Lorith** [comment]
Not a bug, check the description of Strong Back: "You are capable of carrying far more than someone with similar strength could.  Your maximum weight carried is increased by 35%." -- 14*0.35+14=18.9 which is > 18.

**Comment by l29ah** [comment]
Oh.
But lifting ≠ carrying, i think that should be noted somewhere.

**Comment by Night-Pryanik** [comment]
Lifting requirement is based strictly on weight capacity. I think that splitting weight capacity into lifting and carrying might be not worth it as lifting is used only in one place AFAIK.
