### ISSUE TITLE
Game crashing after #8195 update

### ISSUE THREAD

**Issue by GoLoT** [CleverRaven/Cataclysm-DDA#26777]
**Describe the bug**  
Build #8195 seems to be causing crashes when loading both old and new games.

**To Reproduce**  
1. Update to #8195, #8196, #8197 or #8198.
2. Create a new world.
3. Create a new character.
4. Game crashes after character creation.

**Expected behavior**  
The game to load properly.

**Screenshots**  
None.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-34707-gd9fc51f
 - Graphics version: Tiles
 - Mods loaded: Any combination

**Additional context**  
None.

**Comment by Lorith** [comment]
Tested multiple times with build 8198 and default mods.  Certain locations cause crashing by being in reality zone, which naturally includes starting there.

Tested:
Hospital - crash
Middle of town - fine
Wilderness - fine
Bunker - crash
Refugee center - crash
Evac shelter - crash
LMOE - fine
Mansion - fine
Farm - fine
Heli wreck (accidental) - fine
Fungal bloom - fine
Beehive - fine
Field campsite - fine
Pond - fine
Cave - crash
Lab - crash

No idea as to cause of the crash, but that at least should give a starting point for those with more knowledge.

**Comment by ZhilkinSerg** [comment]
#26488 probably

**Comment by ZhilkinSerg** [comment]
It seems Z-levels should be enabled in order to reproduce the bug. Can others confirm if they have Z-levels enabled?

**Comment by ZhilkinSerg** [comment]
![image](https://user-images.githubusercontent.com/16213433/48764556-04501300-ecc1-11e8-9f81-17afe3d9ecdf.png)

**Comment by Lorith** [comment]
I did not have z-levels enabled when I was testing, so it doesn't need the z-levels to crash.

**Comment by GoLoT** [comment]
I do have z-levels enabled.

**Comment by Drakasin** [comment]
Crashing seemingly randomly as well, experimental z-levels disabled

**Comment by Holgg88** [comment]
I crash in LMOE on entering whit Build 8195. But I have a running home network(car system) that are running lights.

**Comment by lgordon85** [comment]
Also crashing in LMOE on 8195, haven't changed much except a fire is currently burning in one of the woodstoves.  Z levels enabled.
