### ISSUE TITLE
Shrubs cant be re-foraged after season change 

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#26783]
**Describe the bug**  
Forest bushes no longer replenish after season change. 

**To Reproduce**  
Forage bush, change season, cant forage bush. 

**Expected behavior**  
Bushes used to replenish and allow to be foraged again after the season changed. Unsure where this functionality was broken but I suspect its when the additional forest things were added in. 

**Versions and configuration(please complete the following information):**
Current GIT pull. 
OS: Arch Linux

**Comment by ralreegorganon** [comment]
This still functions as it did before. You have to leave the map and come back for the game to trigger all the updates [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/map.cpp#L6811).

Using your repro steps, forage the bush, change the season, then move far enough away and back for the actualization code to trigger, and the brush can be foraged again.

**Comment by Treah** [comment]
@ralreegorganon 
Odd I am pretty sure that i was out of the reality bubble from the bushes that I know I was seeing this with. Is it just the reality bubble that you need to leave or a whole map area? If its a whole map area that's a lot of space to have to move out of.
