### ISSUE TITLE
fungal zombies attack fungal blossoms. 

### ISSUE THREAD

**Issue by dogamusprime** [CleverRaven/Cataclysm-DDA#26787]
Fungal zombies attack fungal blossoms almost immediately after they're converted by them. 

Not sure if this is intended. It seems like they consider the fungal blossom's haze as an attack?

0.C-34672-g4b82451

**Comment by kwl01skz** [comment]
I think there is always a hostile relationship between them. Turning a zombie into a fungus doesn't change its relationship, just as you are considered an enemy after being infected with a fungus.

**Comment by kevingranade** [comment]
I do not think this is what we want happening.
