### ISSUE TITLE
Javelin bag won't store javelins when more survival tools is installed

### ISSUE THREAD

**Issue by Centac** [CleverRaven/Cataclysm-DDA#26789]
**Describe the bug**  
Javelin bag won't store javelins when more survival tools is installed

**To Reproduce**  
Give yourself a javelin bag and some type of javelin. Activate the javelin bag

**Expected behavior**  
The javelin bag should store javelins. However, when more survival tools is installed, not only does it not store the extra javelins added by More Survival Tools, it also stops the vanilla javelins from being stored in the javelin bag.

**Versions and configuration(please complete the following information):**
 - OS: Window:s 10
 - Game Version: 0.C-33359-gfbe9044
 - Graphics version: Tiles
 - Mods loaded: More_Survival_Tools

**Comment by mlangsdorf** [comment]
Does adding
```
    "flags": [ "SPEAR", "SHEATH_SPEAR", "JAVELIN" ],
```
to the javelin definitions in data/mods/More_Survival_Tools/items.json solve the problem?

**Comment by mlangsdorf** [comment]
alternately, does making a copy-from of the javelin_bag inside of MST and changing the use action to:
```
    "use_action": {
        "type": "bandolier",
        "capacity": 4,
        "ammo": [ "javelin_stone", "javelin_iron", "javelin_copper", "javelin" ]
        "draw_cost": 30
    }
```
solve the problem?

**Comment by EirenexTheDragon** [comment]
`{
	"id": "javelin_bag",
	"type": "ARMOR",
	"name": "javelin bag",
    "copy-from": "javelin_bag",
	"use_action": {
        "type": "bandolier",
        "capacity": 4,
        "ammo": [ "javelin_stone", "javelin_iron", "javelin_copper", "javelin" ],
        "draw_cost": 30
    }
	}`
this actually lets you store the javelins in the bag and makes it work like its intended, but it still wants to toss errorrs at me for some reason, if anyone can help out perhaps? il insert some screens:
![grafik](https://user-images.githubusercontent.com/41762755/54061560-ad376500-4201-11e9-9b8f-5708d5ad2173.png)
it gives errorr for the copper javelin, the stone and iron javelin aswell, when i look at the Javelin bag. it then has this description 
![grafik](https://user-images.githubusercontent.com/41762755/54061595-dbb54000-4201-11e9-9524-6c1658ca9796.png)

But it lets me store all the javelins as usual. if theres a way to make the error message be ignored, it would even work as intended. i coudlnt find any help sadly so i will be stuck at this point.
