### ISSUE TITLE
"invalid recipe" loading issues (PR 8199) 

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#26784]
**Describe the bug**  
```
 DEBUG    : invalid recipe id "bag_fish_vac"
 
 FUNCTION : const T& string_id<T>::obj() const [with T = recipe]
 FILE     : src/recipe_dictionary.cpp
 LINE     : 50
~
 DEBUG    : invalid recipe id "bag_veggy_vac"
 
 FUNCTION : const T& string_id<T>::obj() const [with T = recipe]
 FILE     : src/recipe_dictionary.cpp
 LINE     : 50
~
 DEBUG    : invalid recipe id "bag_apple_vac"
 
 FUNCTION : const T& string_id<T>::obj() const [with T = recipe]
 FILE     : src/recipe_dictionary.cpp
 LINE     : 50
~
 DEBUG    : invalid recipe id "bag_meat_vac"
 
 FUNCTION : const T& string_id<T>::obj() const [with T = recipe]
 FILE     : src/recipe_dictionary.cpp
 LINE     : 50
~
```
**To Reproduce**  
Mod list below. Loading save after update from PR 8178 to PR 8199. 

Errors can be <kbd>Spacebar</kbd>-continued but will force a crash after last error is <kbd>Spacebar</kbd> or <kbd>i</kbd>gnored. Error happens whens loading 'Flags' module. 

PR 8187 will allow <kbd>i</kbd>gnore of the error and loading of the save without crashing. 8188+ will crash to Desktop when trying to Ignore/Spacebar the errors.

**Versions and configuration(please complete the following information):**
PR 8178 to PR 8199 update causes crash. Stable loading on 8187.

MOD LIST: 

  "dda",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "npc_traits",
  "boats",
  "deoxymod",
  "necromancy",
  "no_mutagen",
  "no_religious_Texts",
  "no_rivtech_guns",
  "no_flaming_weapons",
  "no_scifi",
  "no_survivor_armor",
  "more_classes_scenarios",
  "filthy_morale",
  "manualbionicinstall",
  "sleepdeprivation",
  "StatsThroughSkills"

**Comment by GoLoT** [comment]
Someone mentioned this error in Discord as being a side effect of changing the vacuum sealed recipes and having to update the existing vacuum sealed items in the world. AFAIK you can simply ignore it. Maybe someone has more information or an issue number for reference.

The crashing part could be related to #26777 and not related to the recipes at all.

**Comment by evankimori** [comment]
What were the vacuum changes made? Haven't checked the release notes in a while.

**Comment by GoLoT** [comment]
Could be #26554. Can't say for sure because I only read about it when someone discussed it in Discord.

**Comment by kevingranade** [comment]
Should be an ephemeral non-issue, we want to avoid them, but they aren't bugs per se.
