### ISSUE TITLE
 Mod Inclusion Project: Makeshift Items Mod

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#26809]
Use the following issue as a space to discuss the inclusion of:

Mod Ident: makeshift
Name: Makeshift Items Mod

Your comment should include:

### Suggestions for induction
(what parts of the mod should be included, can be as simple as just an item, a location or the complete inclusion)

### Incompatibilities
(what parts of the mod should not be included, either some objects / items or entire mod is conflicting with DDA theme [ for whatever reason ])

**Comment by DracoGriffin** [comment]
Going to close for lack of interest and discussion.

**Comment by Kelenius** [comment]
I'm interested, please reopen this issue.

This mod adds:

- makeshift Kevlar vest, makeshift pistol bayonet, makeshift sword bayonet;
- crafting recipes for these items;
- crafting recipes for the regular pistol bayonet and the regular sword bayonet;
- sword bayonet and pistol bayonet are added to some item groups.

I think that this mod should be moved to the base game as it is.

**Comment by Cyrano7** [comment]
@Kelenius I'm pretty sure these were in the game and were removed then readded in a mod if I remember correctly.

**Comment by Kelenius** [comment]
Quick search doesn't indicate that to be the case, can you find a link?

**Comment by Cyrano7** [comment]
@Kelenius It's in the first commit in the file history for the mod. This was the PR and the other PR for the bayonets is linked to it https://github.com/CleverRaven/Cataclysm-DDA/pull/18272

**Comment by Kelenius** [comment]
Looking at it, the only item moved was the makeshift kevlar vest, that has been in a game for a long time before that, and I can't find any discussions about why it was removed. The rest was added to the mod after that, and then it all laid untouched for more than two years. I don't see a reason not to merge the mod into the base game.
