### ISSUE TITLE
Palisade wall HP boost

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#26808]
**Is your feature request related to a problem? Please describe.**  
Palisade walls are built using logs and are meant to represent major fortifications, but with 10 min str for the wall itself and 6 for the gate, it is literally possible to ride a bicycle through these log fortifications. These values are equivalent to timber framed drywall walls, a construction literally made from paper and mud, yet are meant to represent enormous logs anchored with earthenworks.

**Describe the solution you'd like**  
Log walls have a min str value of 40. I suggest making palisades somewhere closer to this, perhaps about 30, and raising the gate value to 24. Even this is a little weak, as log walls go through several further stages of deconstruction before being taken down.

**Describe alternatives you've considered**  
If it's a concern about the labour investment in palisades, then while I disagree on principle (these should be fast to erect and sturdy, that's the whole point and why they were historically so common), an alternative option would be a "reinforced palisade" option that increases HP at the cost of more ropes/wires and time. This would differ from the usual half wall / full wall construction in that the initial complete palisade wall should still block LOS and movement. If this were the case, then HP should be similar to log walls and other sturdy constructions; a palisade wall isn't realistically something a regular zombie should be punching its way through.

**New to Github**
I don't know the protocol for this sort of change. It's something I can easily do myself but I don't want to start sticking my fingers into the project without discussion.

**Comment by Night-Pryanik** [comment]
> I don't know the protocol for this sort of change. It's something I can easily do myself but I don't want to start sticking my fingers into the project without discussion.

Actually sticking your fingers into the project and THEN discussing (if discussion is needed at all) if the changes should be merged is the legit way. 
In short: propose your changes in a PR, and most probably they will be merged without a word.
