### ISSUE TITLE
Missing translation data\help\texts.json

### ISSUE THREAD

**Issue by Pupsi-Mupsi** [CleverRaven/Cataclysm-DDA#26816]
**Describe the bug**  
The content of **data\help\texts.json** is being pushed to transifex and has already been translated into proper german but does not apper in the game.

**Comment by AMurkin** [comment]
To fix this `line` should be translated here:

https://github.com/CleverRaven/Cataclysm-DDA/blob/3a795dc1791c9871513f6e0785aca877a43dc930/src/help.cpp#L52

**Comment by AMurkin** [comment]
Actually it's not so simple.

**Comment by AMurkin** [comment]
I'll push PR soon.
