### ISSUE TITLE
Modify gun firing to look for worn items as valid guns.

### ISSUE THREAD

**Issue by Rod995** [CleverRaven/Cataclysm-DDA#26836]
**Is your feature request related to a problem? Please describe.**  
I'd like to be able to fire a weapon without wielding it if it's worn.

**Describe the solution you'd like**  
Maybe a tag or something that could let this be done without breaking the game balance too much.
This could probably open up a few more weapon possibilities, like wrist-worn weaponry, or a gun on a glove.

**Comment by Lamandus** [comment]
Can you give examples of such weaponry? I can't think od weapons you don't need to wield (hold) to fire.

**Comment by Rod995** [comment]
Wrist-mounted weaponry would probably be affected by this.
Crossbows, Darts, ***__Wrist Rockets.__***
Stuff like that, except I'd expect it to be a tag, so you can't fire weaponry worn with a strap.
This could be done by either:
- [ ] Stopping anything worn with a `NO_WIELD_FIRE` tag from firing while worn. (Maybe make the strap give the tag?)
- [ ] Only letting things with a `WIELD_FIRE` tag fire while worn.

**Comment by Rod995** [comment]
Reserved for list of Weapons.

**Comment by kevingranade** [comment]
Nonsense
