### ISSUE TITLE
Mycus Fireproofing turning into Mycogenesis removes half of fire immunity

### ISSUE THREAD

**Issue by Lorith** [CleverRaven/Cataclysm-DDA#26844]
**Describe the bug**  
Mycus Fireproofing removes prompt for walking into fire, as well as making you immune to it.  When it turns into Mycogenesis the prompt reappears and your clothing burns off while you are still fine.

**To Reproduce**  
1. Make a player with a Mycus Fireproofing and some clothing
2. Walk through fire a bit
3. Switch Mycus Fireproofing to Mycogenesis and repeat.

**Expected behavior**  
Remain equally immune to fire when mutation upgrades to be a higher level.

**Versions and configuration(please complete the following information):**
 - OS: [Win7]
 - Game Version [8210 - 0.C-34778-g9f89194]
 - Graphics version [Tiles]
 - Mods loaded [none]

**Comment by kevingranade** [comment]
Thats a pretty serious issue, Mycus Fireproofing shouldn't be protecting your clothes.

**Comment by peperov** [comment]
There is some secondary damage happening when the player goes from 'Scorching Hot!' down towards lower body temperature levels. Is that explicitly intended or a byproduct of the stamina drain that's happening at the same time? Where is it happening, and should the Mycus Mutations prevent this (the body heat, or the damage afterwards)?
