### ISSUE TITLE
Filter/Search doesn't work in construction menu for non-English languages.

### ISSUE THREAD

**Issue by rumly111** [CleverRaven/Cataclysm-DDA#26847]
In the construction menu (*) I press / to filter/search what to build, and it comes up with an empty list when I'm playing Russian. When English everything works fine. Didn't test with other languages.

Windows version, one of the recent builds.

**Comment by AMurkin** [comment]
Are you sure it's not the #26826 issue (fixed in the 8214 build)?

**Comment by rumly111** [comment]
> Are you sure it's not the #26826 issue (fixed in the 8214 build)?

Hmm, that issue is about crafting menu, not construction menu. I had never problems searching in craft menu, only construction menu.  I'm using build 8148.

**Comment by AMurkin** [comment]
I misread, sorry. Search and * caused me to think about that issue.

**Comment by OzoneH3** [comment]
It works with the german localization for me.
If I search for "or" in the russian locale I do get results.
What were you searching for? Meanwhile I'll need to figure out how to get 
cyrillic letters in there to test.

**Comment by rumly111** [comment]
Maybe it's the problem with non-latin characters. I was searching for Fermentation Vat (in Russian), but really nothing else could be found either.

**Comment by AMurkin** [comment]
It filters original non-translated strings.

**Comment by rumly111** [comment]
> It filters original non-translated strings.

By the way, it could be a nice feature if I could search both English and Russian while the game is set to Russian. But I bet this feature wouldn't be that popular.
