### ISSUE TITLE
Advanced Inventory bug in a 45 day game

### ISSUE THREAD

**Issue by obese-pigeon** [CleverRaven/Cataclysm-DDA#26859]
**Describe the bug**  
Advanced inventory screen no longer displays any items. Bug started a couple of days (and versions) ago when I found that looking into my dragged shopping cart would show nothing, or maybe just a few items. Other items on the squares surrounding the player would still be displayed - or sometimes the squares will show no items. No consistency so I did not report. As of today version 8222 it seems that this bug is always there.  This problem does not occur when I start a new game. It only happens in my existing game that has been running for about 45 game days and where I have accumulated a fair amount of loot. I will enclose the save file.

**To Reproduce**  
1. Make a player with a gun, magazine, and some ammo.
2. Try to aim at a wall.
3. There's no way to increase aim level.

**Expected behavior**  
Advanced Inventory should correctly show all the items at the selected sloor location around the player

**Screenshots**  
![image](https://user-images.githubusercontent.com/45394426/49087951-34844c80-f293-11e8-8078-54266a20be04.png)
![image](https://user-images.githubusercontent.com/45394426/49088015-57166580-f293-11e8-8cd3-63dfbb28be5d.png)
contents of grabbed shopping cart
![image](https://user-images.githubusercontent.com/45394426/49088102-80cf8c80-f293-11e8-98c9-b1a299e2a289.png)
In advanced inventory, the shopping cart is only showing as having tainted fat and bone. Note the counter on the NE should have much more items as well.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7 Home Premium Service Pack 1
 - Game Version: 0.C-34838-gf1e1d44
 - Graphics version: Tiles
 - Mods loaded dda, boats, StatsThroughSkills, medieval

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.
[Wernersville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2620371/Wernersville.zip)

**Comment by AMurkin** [comment]
You need to press r in the advanced inventory.

**Comment by HotSake** [comment]
To be clear, you have filters set on both windows. Pressing 'r' will 'r'eset the filter and show all items again.

**Comment by nullinsky** [comment]
Yep,  you have filters on XD

**Comment by kevingranade** [comment]
I was going to say maybe it needs an indicator, but it's there and highlighted, im not sure there's anything else we can do.

**Comment by obese-pigeon** [comment]
Thanks all, I am new to the game and I apologise for a posting a non-bug
