### ISSUE TITLE
Unloading minireactor results in (0) charge plutonium cell

### ISSUE THREAD

**Issue by Poragon** [CleverRaven/Cataclysm-DDA#26854]
**Describe the bug**  
Unloading a minireactor with less than 500 charges via unloa(d) option in vehicle examine menu gives a cursed (0) plutonium cell, which upon moving in advance inventory crashes the game.

**To Reproduce**  
1. Spawn in an atomic sports car.
2. Load mini reactor with a single plutonium cell then expend some plutonium via use till plutonium charges fall below 500.
3. Examine vehicle vehicle and press (d). Have fun with the new cursed (0) plutonium cell in inventory.

**Expected behavior**  
Attempting to unload reactor with less than an entire charge of a plutonium cell in it either returns a failure message to player, or partial cell.

**Screenshots**  

One such applicable vehicle spawned in for testing
![capture](https://user-images.githubusercontent.com/29757881/49063093-4529b980-f1e4-11e8-8434-66e7107d5614.PNG)

Resulting plutonium cell from using the unloa(d) hotkey in previous screenshot
![capturei](https://user-images.githubusercontent.com/29757881/49063133-67233c00-f1e4-11e8-989a-560dccdf1966.PNG)

Crash upon attempting to move cursed plutonium cell via advance inventory
![captureii](https://user-images.githubusercontent.com/29757881/49063174-86ba6480-f1e4-11e8-862a-e46fd65b8ccf.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version 0.C-34778-g9f89194
 - Graphics version Tiles
 - Mods loaded dda

**Additional context**  
Uploaded example save file running only dda with problem setup;
[Cluster Springs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2618625/Cluster.Springs.zip)

**Comment by AMurkin** [comment]
Related #22191
