### ISSUE TITLE
Archery Targets or Pratice Dummies

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#26850]
**Is your feature request related to a problem? Please describe.**  
Practicing on trees or other things causes arrows to land in random locations. 

**Describe the solution you'd like**  
Something you can construct that will allow the player to lock onto it like an enemy and will also collect arrows shot at it. 

**Describe alternatives you've considered**  
Allow arrows to *stick* into trees. 

**Additional context**  
Could be something like the bail of hay or uses pile of hay you get from foraging. Maybe also require some wire or other material to bind it. 
Preferably has a higher chance of preserving arrows fired at it.

**Comment by scanevaro** [comment]
Sounds to me that it should have a limit in the amount of Skill you can get from it. After all, they are not moving targets.

**Comment by Treah** [comment]
@scanevaro 
Sounds good to me, but you already get skill from shooting arrows they just have a tendency to either break or land in random locations from what I assume is bouncing off trees or other obstacles.

**Comment by Night-Pryanik** [comment]
Related: #21967.
