### ISSUE TITLE
control laptop doesn't recharge from internal UPS cbm

### ISSUE THREAD

**Issue by joe9000** [CleverRaven/Cataclysm-DDA#26866]
description: the control laptop says in the description that it can be charged by ups recharging station, i think this should also mean the internal UPS CBM, but currently the CBM does not recharge the control laptop

reproduce:
1 create character with at least one power storage CBM and an internal UPS cbm
2 create control laptop
3 reduce control laptop to less than full charge
4 pass time with control laptop in inventory
5 charge has not increased

expected behavior:
control laptop should recharge while in inventory of a character with available bionic power and an activate internal ups cbm. should behave like this to make it consistent with how other ups-charged items recharge in inventory

os: mac os x
version: 20ded45
gfx: tiles

**Comment by joe9000** [comment]
description: the control laptop says in the description that it can be charged by ups recharging station, i think this should also mean the internal UPS CBM, but currently the CBM does not recharge the control laptop

reproduce:
1 create character with at least one power storage CBM and an internal UPS cbm 
2 create control laptop
3 reduce control laptop to less than full charge
4 pass time with control laptop in inventory
5 charge has not increased

expected behavior:
control laptop should recharge while in inventory of a character with available bionic power and an activate internal ups cbm.  should behave like this to make it consistent with how other ups-charged items recharge in inventory

os: mac os x
version: 20ded45
gfx: tiles

**Comment by AMurkin** [comment]
You should edit your original post and fill it with actual info.

**Comment by CoroNaut** [comment]
I've been using control laptop with ups mod + ups CBM with no problems. Are you sure you have power in your bionics and have the ups CBM turned on?

**Comment by paulenka-aleh** [comment]
> i think this should also mean the internal UPS CBM
It didn't work this way. Some items were immediate between fully UPS and battery-powered, they could be loaded with batteries, recharged on a station but could not be unloaded and could not be xharged via carried or internal UPS. For example tazer is another item behaving this way.

P.S. not sure yet how it works in a world with new battery system, my survivor didn't got any electronics yet. But to me such difficulties don't make sense, at least not anymore.
