### ISSUE TITLE
Drawing of Isometric tiles are broken

### ISSUE THREAD

**Issue by AdonaiJr** [CleverRaven/Cataclysm-DDA#26864]
**Describe the bug**  
Tiles in isometric mode are showing partially. Looks like some change in the the drawing order have caused the issue.

**To Reproduce**  
1. Config the game to Chesthole_ISO or Hitbutton_iso.
2. Note that the Char shows partially. Enter any building and see total misalignment and incorrect drawing order.

**Expected behavior**  
About 20 or 30 buildings ago it was working as intended. I'm sure it was working on 8201.

**Screenshots**  
![screenshot 2018-11-27 22 57 15](https://user-images.githubusercontent.com/5797420/49121711-98f5da80-f298-11e8-9a54-9410339a4809.png)

**Versions and configuration:**
 - OS: Windows 10
 - Game Version [Build 8225]
 - Graphics version [Tiles]
 - Mods loaded [vanilla]

**Comment by OzoneH3** [comment]
Are you using the precompiled jenkins version or did you compile it yourself?

Can't confirm this with self compiled versions for Linux
neither with a cross compiled Windows version.
![](https://user-images.githubusercontent.com/3514404/49141566-2ff17f80-f2f7-11e8-9c39-27f647878622.png)
