### ISSUE TITLE
Unloading ammo belts paralyzes the player and is uninterruptible

### ISSUE THREAD

**Issue by HotSake** [CleverRaven/Cataclysm-DDA#26863]
**Describe the bug**  
Unloading an ammo belt can take a very long time, but does not warn the player of threats during the action or give them an opportunity to stop, as opposed to vehicle part installation for example.

**To Reproduce**  
1. Spawn a 500 round ammo belt
2. Start unloading the belt with enemies around
3. Get swarmed and die while you ignore everything to continue unloading

**Expected behavior**  
Standard safe mode warnings (enemies become visible, enemies approach, enemies attack, damage taken) should all give the player an opportunity to abort unloading. Additionally, the player should be able to self-interrupt by pressing the wait key if they change their mind. An interrupted belt unloading should partially unload the belt and give the appropriate number of linkages based on elapsed time / required time.

**Screenshots**  
Helpfully recorded by Vormithrax here: [https://www.youtube.com/watch?v=sg37Kimcsyw&feature=youtu.be](https://www.youtube.com/watch?v=sg37Kimcsyw) and posted to reddit: [https://www.reddit.com/r/cataclysmdda/comments/a0ey45/cataclysm_quick_slip_1_ammo_ambush/](https://www.reddit.com/r/cataclysmdda/comments/a0ey45/cataclysm_quick_slip_1_ammo_ambush/).

**Versions and configuration(please complete the following information):**
Unknown, presumably latest. Have not attempted to reproduce.

**Comment by AMurkin** [comment]
Duplicate of #23440

**Comment by HotSake** [comment]
Damn, I searched for "ammo belt" instead of "belt".
