### ISSUE TITLE
Several issues with CMake building

### ISSUE THREAD

**Issue by xtsm** [CleverRaven/Cataclysm-DDA#26877]
**First** of all, at least two options (`PREFIX` and `LANGUAGES`) have wrong types (they're boolean while they probably should be string or something), thus making it impossible to use them properly without using command-line CMake.

**Second**, more being personal taste issue than a bug, but still: ccmake shows multiple compilation options (such as `PREFIX`, `CMAKE_INSTALL_PREFIX` and `CMAKE_RUNTIME_OUTPUT_DIRECTORY`, or `CMAKE_BUILD_TYPE` and `RELEASE`) with which it is unclear if they're doing the same thing, and if they do, how do they overlap and which of them have higher usage priority, etc... of course, neither of `COMPILING.md` and `COMPILING-CMAKE.md` contain proper documentation on this: they only contain info about one or two options with conflicting meanings. Even if you deduce their purpose, they still look ugly and unintuitive. I think somebody who has better understanding of what these options do should unify them somehow.

I'm using Linux with CMake 3.12.3.

**Comment by jbytheway** [comment]
I have some local changes that help with some of this (specifically, using just CMAKE_BUILD_TYPE rather than our own RELEASE option, and cleaning up how the compile flags are chosen).  Currently blocked on some other PRs.

My CMake knowledge is not that great either, so I'm not sure how much I can do for the other issues you mention.

**Comment by jbytheway** [comment]
The fixes I had planned are now merged (#27400).  There's probably more worth doing, but I'm not expecting to work on this further, so others should feel free to.
