### ISSUE TITLE
Map memory/ Map Rot causes colossal lag when traversing new terrain

### ISSUE THREAD

**Issue by tyrael93** [CleverRaven/Cataclysm-DDA#26875]
Linux: Curses (and also tiles) issue

Download any version after map memory was released (sept 22). Go outside and walk around the overworld by day.

Game starts stuttering after the first 100 steps and gets progressively worse, to the point it takes 1 second to traverse 1 tile. Tracking back my steps the game runs perfectly smooth (no lag at all) but exploring new terrain repeats the process.
With limited vision (night/near sighted) game runs fine.
Same problems appear both when playing windowed mode and fullscreen.

Current experimentals (up to the oldest available one from the beginning of november) are unplayable, version I still had downloaded from beginning of june works perfectly.
Playing on an average PC, never had this issue before playing DDA.

Is there a way to add an option to simply remove map memory? Because even disabling it visually with { does nothing since the calculations are happening in the background.
Or better yet, fix this mess?

**Comment by kevingranade** [comment]
Should be addressed by #26775

**Comment by tyrael93** [comment]
Nope! Still lags horribly in the same exact way, and just like before: walking in new area = lag, while walking back in the same old area = no lag. 

I have absolutely no idea how or why this is happening on a clean version out of the box without any mods added.
I guess I'll just compile a version without map memory if I want to play DDA again.
