### ISSUE TITLE
Changes to Cordless Dril and Fire Axe

### ISSUE THREAD

**Issue by OptimisticNihlist** [CleverRaven/Cataclysm-DDA#26878]
**Is your feature request related to a problem? Please describe.**  
I noticed that the Cordless Drill has the Drilling quality tag, but not the "screw driving" quality tag.
Since it comes with "...a selection of bits." I think it should be able to do both equally well. Maybe not Fine screw driving, but definitely normal screw driving.

Also, the fire-axe in real life features a long spike opposite the blade
![fireman s axe wood handle](https://user-images.githubusercontent.com/7266560/49227667-37745f80-f3af-11e8-90cb-2052a8df6aea.png)
, which is used to pry open doors and the like. I believe it should have the prying quality added.

**Describe the solution you'd like**  
Add the Screw-driving quality tag to the Cordless Drill, and the prying quality tag to the fire-axe

**Additional context**  
I have done this on my tools.json file and here attached are the relevant entries:

>   {
    "id": "cordless_drill",
    "type": "TOOL",
    "name": "cordless drill",
    "description": "This is a cordless battery-powered drill with a selection of drill bits.",
    "weight": 2721,
    "volume": 3,
    "price": 2000,
    "to_hit": -1,
    "bashing": 3,
    "cutting": 1,
    "material": [ "plastic", "steel" ],
    "symbol": ";",
    "color": "yellow",
    "ammo": "battery",
    "initial_charges": 300,
    "max_charges": 300,
    "qualities": [ [ "DRILL", 3 ], [ "SCREW", 1 ]]
  },
>  {
    "id": "fire_ax",
    "type": "TOOL",
    "name": "fire axe",
    "description": "This is a large, two-handed pickhead axe normally used by firefighters.  It makes a powerful melee weapon, but is a bit slow to recover between swings.",
    "weight": 2520,
    "volume": 8,
    "price": 20000,
    "to_hit": 1,
    "bashing": 20,
    "cutting": 20,
    "material": [ "steel", "wood" ],
    "symbol": "/",
    "color": "light_gray",
    "techniques": [ "WBLOCK_1", "BRUTAL", "SWEEP" ],
    "qualities": [ [ "PRY", 2 ], [ "AXE", 2 ], [ "BUTCHER", -30 ] ],
    "flags": [ "DURABLE_MELEE", "NONCONDUCTIVE" ]
  },

**Comment by AskaHope** [comment]
Why don't you submit a pull request?

**Comment by OptimisticNihlist** [comment]
Sorry @AskaHope I'm not too familiar with github and how all that works. I assumed the set was something more like this
![dewalt-drill-bit-sets-dwa2sls40hp-64_1000](https://user-images.githubusercontent.com/7266560/49185874-a8bcff80-f328-11e8-9e2d-661ed12b51cf.jpg)

**Comment by AskaHope** [comment]
This could be a feature, but would be pretty much useless.

The cordless drill would require charges to operate and spending my precious batteries into a long crafting recipe just for 1 screwdriving quality would be pretty nasty.

The screwdriver is so simple to find/craft that by the time anyone found the cordless drill, it would be pretty much useless.

![img_20181128_204657](https://user-images.githubusercontent.com/43182704/49187870-0a449480-f350-11e8-9c02-36267a2a0e33.jpg)

And as mentioned above, the cordless drill does NOT include screwdriver bits

This could be implemented for the sake of realism, but I really don't see any use.

**Comment by OptimisticNihlist** [comment]
Fair point, just a thought of mine. The fire axe I do still think needs a change.

**Comment by I-am-Erk** [comment]
I think giving the cordless drill a screwdriving quality is a good idea even if it's not something we'd use regularly. If it has a drill bit with it it probably has a driver bit as well, but in the early game if you *need* a driver and it's all you have, it feels arbitrary to not be able to use your drill.

**Comment by I-am-Erk** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/26895

I put fire axe prying at 1, because while it does pry I don't think it's as effective as a crowbar expressly designed for the purpose.

**Comment by OptimisticNihlist** [comment]
> 
> 
> #26895
> 
> I put fire axe prying at 1, because while it does pry I don't think it's as effective as a crowbar expressly designed for the purpose.

Agreed, definitely not as effective but in a pinch, could be used. Thanks!
