### ISSUE TITLE
UPS modified Mess Kit can't be used for boiling

### ISSUE THREAD

**Issue by Ker-Nes** [CleverRaven/Cataclysm-DDA#26883]
**Describe the bug**  
Had a mess kit altered to be UPS powered, and tried to make some tea on the go, with some nearby water. Despite mess kit having the "boiling" tool capacity, the game didn't allow me to do so, complaining that there was nothing to boil it in.

**To Reproduce**  
1. Have ingredients for recipe that require boiling and an UPS modified mess kit.
2. Do not have other boiling capable container on or near you.
3. Check that recipe is unavailable.

**Expected behavior**  
It should serve as a boiling capable tool.

**Versions and configuration(please complete the following information):**
0.C-34863-g9124e70 (tiles)

**Additional context**  
Seems other boil capable tools also fail to serve as such when modified to be UPS powered. And seems to be only boiling that's affected, as cooking still works.

**Comment by Xion350** [comment]
![image](https://user-images.githubusercontent.com/13670135/49250689-12024880-f3e5-11e8-8d08-276b1ced1d6c.png)
Very odd.

**Comment by woutershep** [comment]
I don't think this is too odd, my hunch is that it is an interaction of the implementation detail that mods are contained in items to keep track of them and https://github.com/CleverRaven/Cataclysm-DDA/pull/22530.

**Comment by Xion350** [comment]
> I don't think this is too odd, my hunch is that it is an interaction of the implementation detail that mods are contained in items to keep track of them and #22530.

Good catch.  Maybe it thinks the UPS modification is filling it, thus disallowing the boiling?

**Comment by Night-Pryanik** [comment]
Closed by #28830.
