### ISSUE TITLE
NPCs spam player with warnings for friendly turrets

### ISSUE THREAD

**Issue by anothersimulacrum** [CleverRaven/Cataclysm-DDA#26898]
**Describe the bug**  
NPCs in a base with a turret will constantly spam the player (every ten minutes) with warnings about the friendly turret.  Introduced by the warning feature in #26884.

**To Reproduce**  
1. Get a few NPC friends.
2. Set up a turret in your base.
3. Attempt to craft something or do a task that takes a long time
4. Get alerted several times about the friendly turret.

**Expected behavior**  
Friendly monsters shouldn't trigger the NPC warning the player. 

**Versions and configuration:**
Playing on: Windows 10, 0.C-34877-g7bae86c, with Retrodays tiles, and these mods:
[  "dda",  "Tolerate_This",  "More_Survival_Tools",  "mutant_npcs",  "npc_traits",  "boats",  "deoxymod",  "blazemod",  "Tanks",  "no_religious_Texts",  "No_Fungi",  "no_npc_food",  "filthy_morale",  "StatsThroughSkills"  ]

**Comment by mlangsdorf** [comment]
I did not anticipate that.

**Comment by I-am-Erk** [comment]
That's what makes it so fun!
