### ISSUE TITLE
Some zone-name translations aren't appearing in game

### ISSUE THREAD

**Issue by Pupsi-Mupsi** [CleverRaven/Cataclysm-DDA#26902]
**Describe the bug**  

Some zone-name translations aren't appearing in game, though they have been translated in transifex.

**Farm: Plot**, **Loot: F.Armor**, **Loot: F.Clothing**, **Loot: Magazines**,  **Loot: P.Drink**,   **Loot: P.Food**,   **Loot: S.Parts** and **Loot: V.Parts**

![grafik](https://user-images.githubusercontent.com/44737997/49327407-82ce6f80-f561-11e8-9ab7-0dad87b443e0.png)

![grafik](https://user-images.githubusercontent.com/44737997/49327470-83b3d100-f562-11e8-88f1-0f0aecf1fb1d.png)

![grafik](https://user-images.githubusercontent.com/44737997/49327509-2c623080-f563-11e8-913d-c1b4c4cd2476.png)

**Comment by Karthas077** [comment]
I'm not sure how the translating process works precisely so I don't know how to fix this myself, but the problem is that those entries still have msgctxt lines which have since been removed from clzones.cpp.

**Comment by AMurkin** [comment]
`msgid "Farm: Plot"` did lose `msgctxt "plot_of_land"` after #26900.

**Comment by AMurkin** [comment]
Oh, yeah, that's `cataclysm-dda.pot`, but not `[lang].po` files.

**Comment by Pupsi-Mupsi** [comment]
> 
> 
> `msgid "Farm: Plot"` did lose `msgctxt "plot_of_land"` after #26900.
> 
> ![default](https://user-images.githubusercontent.com/1931904/49339797-e4690980-f647-11e8-9b0c-29edd45c54ad.png)

You are right! But not in https://raw.githubusercontent.com/BrettDong/Cataclysm-DDA/b7bff66032697c21bc56f97b0eb33b4befb807c7/lang/po/de.po

#: src/clzones.cpp
msgctxt "plot_of_land"
msgid "Farm: Plot"
msgstr "Ackerbau: Feld

Do I simply have to wait 'till the next i18n-update?

**Comment by AMurkin** [comment]
I think all existed translations were dropped after they lose their context. Transifex workflow. We should wait it seems.

**Comment by Pupsi-Mupsi** [comment]
Okay. Lets wait then.

**Comment by BrettDong** [comment]
Synchronization between Transifex and GitHub repo is not real-time. Currently, they are synchronized manually per week.

**Comment by Pupsi-Mupsi** [comment]
Thanks for making that clear to me.
