### ISSUE TITLE
High eyes encumbrance doesn't forbid reading/crafting

### ISSUE THREAD

**Issue by niglow** [CleverRaven/Cataclysm-DDA#26910]
**Describe the bug**  
Eyes encumbrance that could be considered "over the top" allows reading and crafting, not to mention that you're still able to spot enemies from afar.

**To Reproduce**  
1. Wish 2 welding goggles & 2 PBA masks & 2 eclipse glasses, put them on, get 180+52 eyes encumbrance.
2. Wish any book and try to read it.
3. Try to craft anything that couldn't be crafted in the darkness, e.g. a fishing hook from a nail or something more complex that requires forging and/or soldering.

**Expected behavior**  
There should be either a considerable decrease of vision range after some eyes encumbrance threshold or a dynamic vision range formula.
Reading & crafting should be impossible after some level of eyes encumbrance which could be considered barely distinguishable from "very dark" lighting.

**Version:**
0.C-34877-g7bae86c

**Comment by Ker-Nes** [comment]
Looks a bit meaningless bookkeeping. Characters aren't really crafting or reading while doing something dangerous, so I'd say it's pretty fair to just abstract it as the character removing the items and then putting them back afterwards, if only to reduce work for players, as well as the reports "Suddenly my character sucks at reading and crafting for no reason" from those this catch them by surprise.

**Comment by niglow** [comment]
> Looks a bit meaningless bookkeeping. 

During night time eyes encumbrance does matter for vision range and during day time it doesn't - that's the point number 1 and it was shown with the OP example. Lighting and mood affect crafting speed but eyes encumbrance doesn't - that's the point number 2.

> Characters aren't really crafting or reading while doing something dangerous

"Something dangerous" comes to players when they are reading/crafting pretty often. World settings and modlist have quite big impact on this, no wonder if someone might think such situations are too rare to account for them.
  
  
> it's pretty fair to just abstract it as the character removing the items and then putting them back afterwards

That's how "glare protection" items are used now but my point wasn't about them - they were just used as an example of insanely high eye encumbrace that ruins some calculations like traps spotting, accuracy, night vision range but does nothig else.
  
Have a look at gas mask, PBA masks & survivor masks, you'll see that their 20-30 eye encumbrace doesn't really encumber players most of the time - they can still spot a tiny animal as if they weren't wearing a gas mask at all, can read & craft without any penalties - are we abstracting taking the mask off to check the surroundings every now and then and then putting it back on? Then traps spotting and NV-range shouldn't be affected too, but they are. So, there's an inconsistency.
  
The game already abstracts taking the mask off while eating/drinking - that's a sane "reduce work for players", but giving players the benefits of gas protection without the corresponding penalties which are implied by "eyes encumbrance" - isn't. Currently the games doesn't have any temporary effects that ecnumber eyes for this to actually matter, but it could potentially have some: like "irritated eyes" from thick smoke and whatever lasting eyes effect from boomers bile - that'd make eye drops more useful for instance: use them and get rid of the penalty, or wait the effect off but see a little worse. Being dead tired could give "red eyes" effect or something like that. "Eye parasites", "Сorneal burn" - why not? Such effects could last for a while and this mechanics is pretty close to vitamins: if you take care of yourself - you don't have any problems, if you are reckless - here's your deserved penalty. Those who are new to the game or just prefer "easy mode" could probably be able to turn this on/off via mod similar to "no vitamins" and "No_items/monsters" mods.

> "Suddenly my character sucks at reading and crafting for no reason" from those this catch them by surprise.

Having your eyes too encumbered isn't "no reason" - the example with 180+52 was an extreme one just to show how far "no penalty" can go, but 30 encumbrance from a gas mask alone isn't something "meaningless bookkeeping" IMO. If you think otherwise and have a chance - try spotting something from afar or reading while wearing a gas mask IRL. My experience tells me that this a pretty good justification to read/craft slower (just like crafting speed penalty from bad mood) and have reduced vision range during day. I'm not saying that the vision penaltly from a regular gas mask should be crippling, even 15-20% vision range decrease would be enough to matter and still be a bearable trade-off. Since the game doesn't allow items to encumber different parts differently the alternative of having gas masks with better visors isn't being taken into account.
As for "caught by surprise", the proposed change would be a perfect tell-tale sign for players that put welding goggles on by accident - I've seen people blindly guessing why they suddenly became bad at ranged combat after that. As an alternative for spotting this particular "I accidentaly put welding goggles on" event - everything could be tinted dark gray similar to green tint from NV-goggles, but that's just a side note. The main point stays the same and has been layed out above.

**Comment by niglow** [comment]
Right, taking torso encumbering items off to get higher dodge in case of an unexpected encounter is so lame, why even this feature in the game? Reading under a dim light is slower - how can one possibly tolerate this? And we have to watch our mood since it can slow down crafting - such nonsense, where's my "insta-win" button? [/s]

Penalty doesn't automatically mean prohibition, which your comment implicitly stated.
