### ISSUE TITLE
Change to fat nutritional value is pure insane

### ISSUE THREAD

**Issue by Muffindrake** [CleverRaven/Cataclysm-DDA#26914]
![capture](https://i.imgur.com/kHjjIj8.png)
#26873 

At this point you might as well throw away the meat and freeze the fat.

Raw fat may or may not have such high nutritional value by itself, but that doesn't matter. This change doesn't help the already unfortunate circumstance in which butchering provides a boundless source of food with little effort necessary in the game.

It was sort of okay prior to this change - preserve/dehydrate/freeze the meat you can before it rots and perhaps process some of the other parts like fat to gain a modicum of value out of them.

Or dispose of all of that - just go kill a deer and eat its fat, it'll sate the character for the next day or two (fat spoils in a week).

As it stands now, meat is a pointless commodity.

**Comment by Treah** [comment]
Why not just make fat give you a negative health modifier like junk food does now? Also Inuits subside on blubber which is just whale fat so a fat only diet is not unheard of IRL. 

Also was there any justification in the PR for the change? I cant seam to find anywhere where it was referenced to IRL values to justify the change in calories. I am unsure how much fat a potion is, if I had that we could do a simple lookup online to see how much it has. But I very much doubt its this high tho considering most hamburger is 20% fat and a pound of hamburger is only about 1040 calories.

**Comment by Treah** [comment]
I just looked it up a pound of fat is about 3500 calories. This value is way off and should be fixed.

**Comment by Treah** [comment]
Found a better source and also found the portion size in the game. 
Portion size in the game is 1/2 a pound. So using that as a base I found the calorie count for 1lb of beef fat and cut it in half. I used 90% lean beef for the meat value. 

Meat: 798 calories
Fat: 1528.5 calories 

Sources
Meat: https://www.fatsecret.com/calories-nutrition/usda/beef-fat?portionid=47377&portionamount=1.000
Fat: https://www.fatsecret.com/calories-nutrition/usda/beef-fat?portionid=47377&portionamount=1.000

**Comment by Treah** [comment]
Created PR #26916 to correct this.

**Comment by mlangsdorf** [comment]
I mildly object to the issue title.  1943 calories for 230-250 g of raw fat may not be entirely correct, but it's fairly close to the actual value.  It's certainly not an insane number.

**Comment by kevingranade** [comment]
Upon review, the number is correct, this is an invalid issue.
