### ISSUE TITLE
recent changes to basecamp causing compile failures?

### ISSUE THREAD

**Issue by overbo** [CleverRaven/Cataclysm-DDA#26918]
**Describe the bug**  
once backtrace is disabled on OSX, recent changes to either basecamp or map cause compile failures with clang as compiler.

**To Reproduce**  
`git pull && make clean & make -j6 NATIVE=osx OSX_MIN=10.14 LUA=1 LOCALIZE=0 CLANG=1 BACKTRACE=0`

**Expected behavior**  
game compiles as normal

**Screenshots**  
```
clang++  -DMACOSX -DGIT_VERSION -ffast-math -Og -Wall -Wextra -D_GLIBCXX_DEBUG -g  -fsigned-char -stdlib=libc++ -std=c++11 -MMD -MP -mmacosx-version-min=10.14 -I/usr/local/include/lua -DLUA -c src/faction.cpp -o obj/faction.o
clang++  -DMACOSX -DGIT_VERSION -ffast-math -Og -Wall -Wextra -D_GLIBCXX_DEBUG -g  -fsigned-char -stdlib=libc++ -std=c++11 -MMD -MP -mmacosx-version-min=10.14 -I/usr/local/include/lua -DLUA -c src/faction_camp.cpp -o obj/faction_camp.o
In file included from src/editmap.cpp:1:
In file included from src/editmap.h:5:
In file included from src/map.h:16:
/Library/Developer/CommandLineTools/usr/include/c++/v1/map:629:15: error: object of type 'std::__1::pair<const std::__1::basic_string<char>, expansion_data>' cannot be assigned because its copy assignment operator is
      implicitly deleted
        {__nc = __v.__cc; return *this;}
              ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__tree:1645:35: note: in instantiation of member function 'std::__1::__value_type<const std::__1::basic_string<char>, expansion_data>::operator=' requested here
                __cache->__value_ = *__first;
                                  ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__tree:1575:9: note: in instantiation of function template specialization 'std::__1::__tree<std::__1::__value_type<const std::__1::basic_string<char>, expansion_data>,
      std::__1::__map_value_compare<const std::__1::basic_string<char>, std::__1::__value_type<const std::__1::basic_string<char>, expansion_data>, std::__1::less<const std::__1::basic_string<char> >, true>,
      std::__1::allocator<std::__1::__value_type<const std::__1::basic_string<char>, expansion_data> > >::__assign_multi<std::__1::__tree_const_iterator<std::__1::__value_type<const std::__1::basic_string<char>,
      expansion_data>, std::__1::__tree_node<std::__1::__value_type<const std::__1::basic_string<char>, expansion_data>, void *> *, long> >' requested here
        __assign_multi(__t.begin(), __t.end());
        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/map:912:21: note: in instantiation of member function 'std::__1::__tree<std::__1::__value_type<const std::__1::basic_string<char>, expansion_data>,
      std::__1::__map_value_compare<const std::__1::basic_string<char>, std::__1::__value_type<const std::__1::basic_string<char>, expansion_data>, std::__1::less<const std::__1::basic_string<char> >, true>,
      std::__1::allocator<std::__1::__value_type<const std::__1::basic_string<char>, expansion_data> > >::operator=' requested here
            __tree_ = __m.__tree_;
                    ^
src/basecamp.h:21:7: note: in instantiation of member function 'std::__1::map<const std::__1::basic_string<char>, expansion_data, std::__1::less<const std::__1::basic_string<char> >,
      std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, expansion_data> > >::operator=' requested here
class basecamp
      ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/utility:325:5: note: copy assignment operator is implicitly deleted because 'pair<const std::__1::basic_string<char>, expansion_data>' has a user-declared move
      constructor
    pair(pair&&) = default;
    ^
1 error generated.
make: *** [obj/editmap.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Versions and configuration(please complete the following information):**
OSX 10.14.1
ncurses, no sound

**Additional context**  
n/a

**Comment by overbo** [comment]
looks like the error is not clang-specific.  similar error with c++ compiler.

c++  -DMACOSX -DGIT_VERSION -ffast-math -Og -Wall -Wextra -D_GLIBCXX_DEBUG -g  -fsigned-char -std=c++11 -MMD -MP -mmacosx-version-min=10.14 -I/usr/local/include/lua -DLUA -c src/faction.cpp -o obj/faction.o
c++  -DMACOSX -DGIT_VERSION -ffast-math -Og -Wall -Wextra -D_GLIBCXX_DEBUG -g  -fsigned-char -std=c++11 -MMD -MP -mmacosx-version-min=10.14 -I/usr/local/include/lua -DLUA -c src/faction_camp.cpp -o obj/faction_camp.o
In file included from src/editmap.cpp:1:
In file included from src/editmap.h:5:
In file included from src/map.h:16:
/Library/Developer/CommandLineTools/usr/include/c++/v1/map:629:15: error: object of type 'std::__1::pair<const std::__1::basic_string<char>, expansion_data>' cannot be assigned because its copy assignment operator is
      implicitly deleted
        {__nc = __v.__cc; return *this;}
              ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__tree:1645:35: note: in instantiation of member function 'std::__1::__value_type<const std::__1::basic_string<char>, expansion_data>::operator=' requested here
                __cache->__value_ = *__first;
                                  ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__tree:1575:9: note: in instantiation of function template specialization 'std::__1::__tree<std::__1::__value_type<const std::__1::basic_string<char>, expansion_data>,
      std::__1::__map_value_compare<const std::__1::basic_string<char>, std::__1::__value_type<const std::__1::basic_string<char>, expansion_data>, std::__1::less<const std::__1::basic_string<char> >, true>,
      std::__1::allocator<std::__1::__value_type<const std::__1::basic_string<char>, expansion_data> > >::__assign_multi<std::__1::__tree_const_iterator<std::__1::__value_type<const std::__1::basic_string<char>,
      expansion_data>, std::__1::__tree_node<std::__1::__value_type<const std::__1::basic_string<char>, expansion_data>, void *> *, long> >' requested here
        __assign_multi(__t.begin(), __t.end());
        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/map:912:21: note: in instantiation of member function 'std::__1::__tree<std::__1::__value_type<const std::__1::basic_string<char>, expansion_data>,
      std::__1::__map_value_compare<const std::__1::basic_string<char>, std::__1::__value_type<const std::__1::basic_string<char>, expansion_data>, std::__1::less<const std::__1::basic_string<char> >, true>,
      std::__1::allocator<std::__1::__value_type<const std::__1::basic_string<char>, expansion_data> > >::operator=' requested here
            __tree_ = __m.__tree_;
                    ^
src/basecamp.h:21:7: note: in instantiation of member function 'std::__1::map<const std::__1::basic_string<char>, expansion_data, std::__1::less<const std::__1::basic_string<char> >,
      std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, expansion_data> > >::operator=' requested here
class basecamp
      ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/utility:325:5: note: copy assignment operator is implicitly deleted because 'pair<const std::__1::basic_string<char>, expansion_data>' has a user-declared move
      constructor
    pair(pair&&) = default;
    ^
1 error generated.
make: *** [obj/editmap.o] Error 1
make: *** Waiting for unfinished jobs....
mike:cdda$

**Comment by ZhilkinSerg** [comment]
We had similar thing previously - https://github.com/CleverRaven/Cataclysm-DDA/pull/26786.

**Comment by Leland** [comment]
Thanks for the report, updated this and your other issue's Markdown so that the code is non-wrapping (and takes up less space)
