### ISSUE TITLE
Twitch Box Art

### ISSUE THREAD

**Issue by ptdel** [CleverRaven/Cataclysm-DDA#26925]
Not really sure if this is the best place for this, but I figure since this is where people working on the game collaborate, I suppose somebody here would be likely considered 'a representative of the game.'  This isn't specifically a technical feature request, I was more so wondering if somebody would be capable of adding the CDDA logo, or some CDDA community-approved Box Art to CDDA's twitch page.  The steps to do so are here:

https://help.twitch.tv/customer/en/portal/articles/2348988-adding-a-game-and-box-art-to-the-directory

It's a small aesthetic thing, but for the people that stream this game, I think it would be a morale boost that the game is getting some attention on Twitch, and for people looking for RL's to watch/stream, having the Box art gives it that official touch.  Small, but nice change if possible :)

**Comment by ZhilkinSerg** [comment]
Take first image from this thread please:

https://discourse.cataclysmdda.org/t/hey-guys-you-have-to-see-this/13459/2

**Comment by kevingranade** [comment]
Twitch made this too much of a hassle for me, I tried a few times and kept encountering issues.
