### ISSUE TITLE
Open crate is firmly sealed

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#26923]
**Describe the bug**  
Examined an open crate and was given the message "The open crate is firmly sealed." Which, is nonsensical

**To Reproduce**  
1. Make a character
2. Find an empty crate/ find and open a create/ debug in an empty crate.
3. Examine said empty crate
4. Profit?

**Expected behavior**  
Things that have "open" in their name to not be "firmly sealed" ... ?

**Screenshots**  
![image](https://user-images.githubusercontent.com/15700895/49351091-67ee1f00-f677-11e8-8be9-e27cf59f998e.png)

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10 ]
 - Game Version [see screenshot]
 - Graphics version [Tiles]
 - Mods loaded [About half the official mod list.  No 3rd party ones]

**Comment by Night-Pryanik** [comment]
Either it's a bug or I don't understand something. According to the code

https://github.com/CleverRaven/Cataclysm-DDA/blob/44809a09d7e1f6d923912bf688320fd7fb20543e/src/game.cpp#L6315-L6320

this message should appear only for furniture with the `SEALED` flag.

But `open crate` doesn't have this flag.

https://github.com/CleverRaven/Cataclysm-DDA/blob/44809a09d7e1f6d923912bf688320fd7fb20543e/data/json/furniture.json#L1442-L1450

**Comment by Treah** [comment]
I am unable to confirm this, I created a new char and had to make a crate as there is no way to spawn one in via the debug menu. I gave char a crowbar and opened the sealed crate and then tried to pry it open again but did not get this message. 
This has to be some mod that is overriding the flags or something

**Comment by Night-Pryanik** [comment]
Half a year without confirmation, closing until confirmed.
