### ISSUE TITLE
Unavailable components (filled containers) in crafting menu.

### ISSUE THREAD

**Issue by Alce00** [CleverRaven/Cataclysm-DDA#26928]
When looking at safety glasses receipt it says that I have plastic bottle and don't have any small plastic bottles, which is accurate. But when making them it gives option to chose between plastic bottle and two small plastic bottles and says that I have 5 of them. All five available small plastic bottles are filled with drugs and chems. Choosing that option creates glasses, but not consume any bottles.

**Comment by Alce00** [comment]
Title screen says O.C-34970-g742ddc. I did update today through CDDA game launcher and it says that it's build #8241

**Comment by ZhilkinSerg** [comment]
Closed as duplicate. Please comment if it i still bugged in most recent version.

**Comment by Alce00** [comment]
O.C-35364-g68f1f45
Bug is still here. And I really not sure it's duplicate of #26673 either. That case is game thinks that you still have that item around. In this case game think that filled containers are empty in the time of making receipt. To chose receipt you still need a viable item though, it's only during making it gives choice to use unavailable item.

For example if you have plastic bottle of water and long string, you can't chose to make safety glasses, but if you have plastic bottle of water, long string and two small plastic bottle, then when you chose to make safety glasses it would give you a choice between using plastic bottle or two small plastic bottles. If you choose former item would be created, but plastic bottle of water wouldn't be spent. Looks like some missing check.
