### ISSUE TITLE
Scrolling doesn't work for the right panel in the vehicle part install window

### ISSUE THREAD

**Issue by rumly111** [CleverRaven/Cataclysm-DDA#26935]
**Describe the bug**  
So I (e)xamine  the vehicle, and in the right column I can see a brief description of each part in the current tile. I can scroll through those descriptions if they don't fit on the screen. But when I try to (i)nstall a new part, the description in the right column cannot be scrolled (keys {, }, <, >, PageUp, PageDown don't work). I tried rebinding local keys, but it still doesn't work.

**To Reproduce**  
1. Examine a vehicle
2. Try installing a vehicle part
3. Try scrolling through part description

**Versions and configuration(please complete the following information):**
Windows (tiles) version, build no.8232

**Comment by mlangsdorf** [comment]
@Qrox Would you be able to take a look at this?  I might be able to hack a solution but you can probably do better if you're inclined to do it.  If not, I'll take a stab at it.

**Comment by Qrox** [comment]
I'm pretty occupied recently, and I'm not that familiar with the vehicle UI code, so please look into it instead.

**Comment by mlangsdorf** [comment]
Fair enough.
