### ISSUE TITLE
Crate an option to reduce NPC spawn each month to simulate extinction.

### ISSUE THREAD

**Issue by AskaHope** [CleverRaven/Cataclysm-DDA#26939]
As mentioned above, I think the game should have an extinction option that reduces the original value of NPCs spawn until it reaches 0.

If you, for example set the NPCs spawn rate to 50.00 and then set the extinction option to reduce this value by 5.00 every in-game month, over the course of the years NPC would become more and more rare, and they would finally become a real necessity on the late game where they could be "Hardened Survivors" with end game gear and often wanting to kill you for loot.

It could also be added a limit to this reduction, for players that don't want an actual extinction.

**Comment by Theundyingcode** [comment]
The glaring obvious problem with this is that the world only gets created as it enters your reality bubble.   Simply changing the spawn rate would result in a lot of npcs around the players starting area and none as they explore more.

**Comment by I-am-Erk** [comment]
That's sort of how it would be, though. You'd run into a lot of people at first, and fewer as time passed.

I wouldn't want to see this implemented unless NPCs also slowly got better starting equipment, skills, and traits as time passed though. if you're going to select out the strongest, then the survivors should be stronger. I think this is a feature that would be cool to see, but should wait for a number of other NPC features first.

it should also go hand-in-hand with having worldgen options that appear later in game, like a survivor camp that only spawns after a year and contains NPCs with their own faction. So you don't see random wandering NPCs as much but you might happen upon a group of three that have fortified a library and have been living there.
