### ISSUE TITLE
Change color of the amount of extra movement points spent instead of spamming messages.

### ISSUE THREAD

**Issue by AskaHope** [CleverRaven/Cataclysm-DDA#26934]
This could reduce significantly the amount of spams in-game. 

Instead of spamming messages, the amount of extra movements spent could be represented by a color, just like the speed modifier.

It could have two distinct colors, yellow and red.

Yellow means the player is currently running, and red means the player spent extra movement points.

**Comment by Night-Pryanik** [comment]
Please don't forget about the colorblind people.

**Comment by I-am-Erk** [comment]
Perhaps there could be a text icon rather than or as well as colour, showing up beside the movement speed?

**Comment by HotSake** [comment]
I can live with the spam if it helps people learn what kind of terrain will slow creatures down. It may be second nature to a veteran, but it's very easy for a new player to not realize that there is a significant penalty for walking through shrubs, tall grass, chairs, etc. The movement speed display is very easy to miss. Message log spam at least alerts you to the fact that you're doing something that could literally get you killed.

**Comment by AskaHope** [comment]
The number of rough terrain spam messages is enormous!

For example, when you walk throught a forest, your log will be pretty much filled with these spams, and this may make you miss other important messages like that *piercing howl* or being badly poisoned. Some players don't even know how they've contracted teleglow!

Have you ever tried to play with genetic chaos? I hardly notice my character's mutations, every time I open the character screen, it has 2-3 new mutations!

**Comment by I-am-Erk** [comment]
I second what askahope is saying.

Another good option, actually, would be to add a timer to the "moving over this is slow" messages, so after getting one such message, you won't see the same message again for time period x (eg real time five minutes or fifty turns). Especially if coupled with a less intrusive movement cost indicator as mentioned in this issue.

Another option would be to make those messages a toggle, so you can choose to turn them off altogether in options.

**Comment by kevingranade** [comment]
Something I've been thinking about is seperating attention-catching alerts from messages that get logged.

Moving over obstacle is slow!
Is an alert, and its importamt that you notice it, but two turns later you don't care that it happened.

The technician zombie pulled your compound crossbow out of your hands!
Is both an alert and something you might need to be reminded of later.

Concretely, the proposal is to:
Mark some high-volume messages as "ephemeral".
Either erase ephemeral messages after the turn when they occur, or display them in a new message window that ONLY displays alerts from the previous turn.

**Comment by I-am-Erk** [comment]
I really like that idea.

Oh.

Maybe there could there be a definitions area, modeled after the safe mode /auto pickup window, where you could blacklist certain words to either never show up, or to vanish after the turn where they appear? So for example I could add the phrase "moving over this", and any message that had those words in it would be hidden after showing up, except possibly in the message log.

**Comment by HotSake** [comment]
I think if only the most recent copy of the ephemeral message was shown, that would eliminate log spam and simultaneously make it hard to miss for unaware players. That would save having to design a separate log UI, as well. The full log ('P' by default) should still show all copies of the message, as it may be necessary to reconstruct what happened.

**Comment by kevingranade** [comment]
Discussion that has run it's course, we are not implementing the suggestion as outlined.
