### ISSUE TITLE
Smartphones still accept UPS conversion mod

### ISSUE THREAD

**Issue by Ker-Nes** [CleverRaven/Cataclysm-DDA#26942]
**Describe the bug**  
Smartphones, which already are charged through UPS, still get listed as a valid target for the UPS conversion mod for tools.

**To Reproduce**  
1. Have a smartphone and an UPS conversion mod.
2. Activate UPS conversion mod.
3. See Smartphone listed.

**Expected behavior**  
Smartphones shouldn't accept UPS conversion mods because they already use UPS to charge.

**Versions and configuration(please complete the following information):**
Windows 7
0.C-34978-g37a3450 (tiles)

**Comment by anothersimulacrum** [comment]
Tazers also use UPS to charge but still accept a UPS conversion mod.
