### ISSUE TITLE
Electric Smoker (better idea then #7142?)

### ISSUE THREAD

**Issue by Admiral-Wily** [CleverRaven/Cataclysm-DDA#26946]
I think there should be a electric smoker in game that uses batteries as fuel and wood chips (splinters?) for the smoke flavor so we can cook various smoked goods as an alternative to charcoal smoking/charcoal production along with a version that can be installed in a vehicle (a vehicle smoker if you will) and appropriate recipes to craft the electric smokers (standalone and vehicle rig version). The idea is not to replace the charcoal smoker but as to whats more convenient for each players differing situation be it charcoal, batteries, or a vehicles power system. Those are my thoughts what do you guys think?

I guess in summary: there is a charcoal forge, electric forge, and a vehicle forge rig why not have a charcoal smoker, electric smoker, and a vehicle smoker rig?

**Comment by I-am-Erk** [comment]
I'm not totally sure what this adds that isn't already in game? The smoker is going to need charcoal or something similar to smoke anyway. Why add the extra requirement of batteries as well?

**Comment by Admiral-Wily** [comment]
well IRL you use wood chips in a electric smoker to impart the smoke flavor and getting wood chips or splinters is much simpler then charcoal production

**Comment by I-am-Erk** [comment]
It's not like charcoal production is a complex multistage process.

Wood chips --> charcoal kiln --> charcoal
Versus just wood chips, but also needing another in game item that will need some unique programming allowing it to use two fuel types.

If you put it in a vehicle rig it's still going to need a secondary resource, it's not going to gain the same benefits as having a battery powered device hooked up to a central power supply.

**Comment by Admiral-Wily** [comment]
Hmm what if it looked for wood chips as ingredient to cook the smoked meat and consume it that way or is this getting unnecessarily complex as well?

**Comment by I-am-Erk** [comment]
You'd have to make separate recipes for everything that you wanted to be able to smoke.

I think you might be happier just making a vehicle rig that could make charcoal and be used as a smoker.
