### ISSUE TITLE
Dodging/Blocking Overhaul

### ISSUE THREAD

**Issue by Karthas077** [CleverRaven/Cataclysm-DDA#26947]
**Is your feature request related to a problem? Please describe.**  
Following numerous discussions on the discord about the current state of dodging and blocking, I have begun the process of re-imagining the structure of the current combat code to allow for both greater control and flexibility.

**Describe the solution you'd like**  
A general overhaul of the how various combat functions are defined and where they are located with the goal of preserving existing balance/mechanics where possible while improving the ability to add new content and modify existing content.

In more detail:
Currently attacking is performed as follows 
1. An attack roll opposed by a flat dodge value (players and NPCs get a slight penalty for additional dodges, but there's no RNG on the dodging side) with a positive number being a hit, and a negative number being a miss.
2. If you hit, you then compare the remainder of your attack roll against their same dodge value again to determine if you crit.
3. If the target is a player or NPC they check if they can block.
4. Then damage is rolled, factoring in if there was a crit and what % was blocked and martial art techniques are applied.
5. If you were blocked, defender has a chance to apply "on blocking" martial art techniques.
6. "On hit" effects are applied such as spraying acid or shocking an attacker with a conductive weapon.

The proposed changes:
The result of the attack vs dodge is used to determine how far off target the attack is.
Dodging has stages, the preemptive movements made to be "difficult to hit", and a reactive movement to shift the attack off target. (Mindless monsters such as zombies don't use reactive dodging)
Sufficiently off target attacks can deal glancing blows and/or hit limbs instead of the torso.
Characters with the ability to actively dodge or block can additionally attempt to shift the attack further off target by interposing a blocking limb/tool. With three "degrees" of blocking corresponding to "Intercept attack", "Deflect blow", and "Absorb hit".
Which type of block you are able to do depends on how much time you have to react and how off target the attack currently is.
After those stages, low off target numbers (or negative ones) can cause additional damage for hitting a particularly vital area.

**Describe alternatives you've considered**  
Leaving the code the way it is, or hacking more complicated blocking/dodging mechanics into the existing infrastructure.

**Additional context**  
Current psuedo-code is located here: https://gist.github.com/Karthas077/42722ea8c3a52c85243945b6b051e242

**Comment by I-am-Erk** [comment]
It's hard to comment on the issue without knowing what changes you're thinking of making though. Without reading through all your pseudo code, what are your general redesign thoughts? I've seen many very disparate suggestions for what changes to make before.

**Comment by Karthas077** [comment]
> It's hard to comment on the issue without knowing what changes you're thinking of making though. Without reading through all your pseudo code, what are your general redesign thoughts? I've seen many very disparate suggestions for what changes to make before.

Added some plain-text summarizing the current state of things as well as some of the discord discussion (and my interpretation of it's implementation)

**Comment by I-am-Erk** [comment]
Your changes sound fairly reasonable, although I'm not sure I understand how deeply they're going to alter play. It sounds like this would create less of a geometric damage falloff as dodge and block improve, and more of a linear one?

A common suggestion that I think could be easily rolled into what you're describing is that dodging should also spend stamina, and I'd suggest that more difficult (reactive) dodges should spend more of it. Blocks should have a risk of taking damage, either to the weapon/shield you're blocking with, or to a limb if unarmed.

**Comment by kevingranade** [comment]
Personal project of an absent contributor.
