### ISSUE TITLE
Commands for hacked robots

### ISSUE THREAD

**Issue by Nameless-Survivor** [CleverRaven/Cataclysm-DDA#26954]
I love being able to hack robots, but not being able to interact with or command them limits their usefulness. Being able to interact more with your robotic minions would give players more reason to use the control laptop, rather than to simply avoid confrontation or use robots as disposable distractions.

The following features would greatly increase their flexibility/usefulness to the players:

1. Ability to deactivate hacked robots for storage.
2. Ability to command hacked robots to stand guard at their current location.
3. Ability to command hacked robots to patrol a defined area.
4. Ability to designate conditions for engaging enemies (similar to NPCs).
5. Ability to assign a hacked robot to act as an bodyguard/escort for an NPC follower during a mission.

Lorith (AKA Shard) has already created a mod to allow players to deactivate robots included in the base game and the National Guard Base. I think this would be worthy of inclusion as part of the base game.
https://github.com/Lorith/Disable-Bots-CDDA-Mod

**Comment by AskaHope** [comment]
Great, now robots will be ways more useful than NPCs. Why até humans so useless?

**Comment by CoroNaut** [comment]
Probably add a charging station construction or something similar, we can say that all un-hacked robots automatically recharge at the place they spawn at until they are hacked, and when hacked, they start losing power.
