### ISSUE TITLE
Craftable utility lights?

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#26955]
Posting this as a suggestion first so we can discuss before I just dive into a pr.

I've been thinking about possibly making t_utility_light, the utility light found in the refugee center, a buildable terrain item. I have two reasons for this:

1. After a certain point in the game, needing light ceases to be a challenge and becomes at most a minor nuisance. Turrets, for example, give off light and are freely available. This would allow having a light source similar to a turret, without the slightly janky problem of putting turrets everywhere.

2. I'd like to add utility lights to base camp upgrades some day, so that they can compete a little better with the refugee camp.

I'd suggest a recipe for this would probably require a plutonium cell, a steel frame, a floodlight, some wires, and some scrap electronics. Alternatively, it could require an atomic lamp instead of a floodlight, but I think the lamp is a bit too restrictive. Short of mods making it easier to get, I think plutonium cells are rare enough that this will still be a mid to late game recipe, where light is more a nuisance than a challenge.

Thoughts?

**Comment by Nameless-Survivor** [comment]
I would make them portable like the butcher rack. Be able to set up lighting anywhere you need it, and then pack it all up and leave. Same goes for the ones in the environment. No reason you shouldn't be able to pick up a utility light and carry it off, they aren't welded to the floor. 

Maybe make them targetable somehow too. Being able to shoot out utility lights in the environment to provide darkness for cover would be nice. I always hated that I couldn't shoot out the lights in the National Guard Base underground so those murderous Wraitheon bots couldn't shoot me from quite so far away.

**Comment by I-am-Erk** [comment]
I don't know how much I love the idea of lower level players stealing all the utility lights from the refugee camp too easily... And atomic lamps already fill the role of easily portable light source in that way.

**Comment by Nameless-Survivor** [comment]
If you pick up the lights at the refugee camp, the guards should do their very best to kill you, because you are stealing.

Atomic lamps are too weak to provide much lighting, at least IMO, I tried using them to light my bunker.  Mounting them on a frame just reduced the lighted radius further for some reason too. 

Also, since you can't set atomic lamps up like the butcher rack, follower NPC's may pick them up and random NPC's can steal them.

**Comment by Nameless-Survivor** [comment]
They don't already shoot you for stealing? 
Come to think of it, I've honestly never tried to steal, I kind of just assumed if you picked up or damaged anything at the refugee center they would try and kill you.

Your idea about a separate, identical item is a good way to get around having to tinker with the AI coding. Though you might make the new dismantleable version of the light replace the current one everywhere else the utility light shows up. I don't think there are very many, so it shouldn't be too easy to get them.

**Comment by chaisawlajatang** [comment]
I'm disagree, to be honest. We already have a craftable atomic lamp with infinite light, requiring a rare recipe book to make it.
Almost infinite light can be obtained by welding floodlight into the frame with a solar panels or engine+car alternator. Or swappable car batteries.

**Comment by Nameless-Survivor** [comment]
Engine+alternator or a generator makes smoke, and you don't want to light up a base by having smoke generating things that have to be regularly refueled everywhere. Especially if you are set up underground or inside a building.

You can't use solar power underground either. Plus, a single solar panel will not produce enough to keep a floodlight running 24/7, so you would have to micromanage every single light "vehicle" scattered around your base, which would be tedious.

As for atomic lamps, see my 2nd post about why they aren't really that great for long term lighting or for a base.

**Comment by I-am-Erk** [comment]
I'd say the atomic light and the engine with a floodlight just illustrate why I think this would be nice. Light itself is easy enough to get by the midgame, but requires a bunch of silly micromanaging of fuel, or has a uselessly tiny radius. Why the fuss? What gameplay does it add to have to keep fueling up an engine and avoiding exhaust smoke?

**Comment by Malkeus** [comment]
https://discourse.cataclysmdda.org/t/craftable-utility-lights/17750
I'll just leave this here...

**Comment by kevingranade** [comment]
I'm pretty much 100% against it as outlined here.
If you want to make a larger scale rtg and lamp, youre going to need a 100kg+ rtg (see https://en.wikipedia.org/wiki/Radioisotope_thermoelectric_generator#Terrestrial ).
We can make installing generator or battery powered lights more convinient, but just giving up on tracking power consumption isn't an option.

Especially in a faction camp you can have someone running around in the background dealing with lighting issues for you. 
Even short of that, it is quite easy to set up permanent lighting for your base, and if there's a need to expand or streamline it, we need to focus on that, not trying to hack around the issue.

As for the argumens you have for doing it this way, it can mostly be summed up as the things you're trying to leverage or compare it to are either bugs or unfinished features.

Turrets *should* run out of power over time unless theyre in a facility and have access to facility power.  The player would also have access to facility power.
t_utility_light is in the same boat, it should either run out of power or have an external supply.
The atomic lamp is specifically intended to be, "this is the best you can get" from a tiny rtg and a light.

**Comment by Inglonias** [comment]
Something something [lamp memes](https://knowyourmeme.com/memes/moth-lamp)

**Comment by Nameless-Survivor** [comment]
An RTG is not the only type of long term nuclear power source. There are also some with MUCH greater energy density and the ability to be miniaturized.

Betavoltaic devices were used to power pacemakers before lithium ion batteries were developed and made them obsolete. A recent one had an energy density of 3.3 KwH/kg, and used an isotope with a half life of 100 years.

For comparison, a lithium ion battery has an energy density of about 11.6 KwH/Kg

https://en.wikipedia.org/wiki/Betavoltaic_device
https://en.wikipedia.org/wiki/Lithium-ion_battery

**Comment by Nameless-Survivor** [comment]
Is there a way to make a furniture item that can be connected to jumper cables? So you would have your portable utility light or something, and have it connected to a frame with an engine/alternator, minireactor, solar array, or battery bank for power.

**Comment by I-am-Erk** [comment]
Based on this and the forum thread it sounds like this is something that the project leads would rather not have. I disagree, but like I said over there, I don't really feel like having a protracted debate about it... I will probably make a smaller scope mod for like minded people and be done with it. Closing this to avoid issue spam, further discussion can continue in the thread.
