### ISSUE TITLE
Hologram Cloak Fitting Issues

### ISSUE THREAD

**Issue by Nameless-Survivor** [CleverRaven/Cataclysm-DDA#26963]
Hologram cloaks always show up as having "poor fit", and since they cannot be repaired, they cannot also be fitted to the player. Being both irreparable/untailorable and having high encumbrance greatly reduces its usefulness. It might be worth reworking the item slightly.

The item is described as being made of superalloy fibers and hexagonal carbide sheets. Such a system would necessitate a degree of modularity for repair and maintenance purposes, otherwise the moment a section of it malfunctioned it would become a very expensive piece of junk. As a result, I was thinking that the best way to address the fit/repair issue would be by making the hologram cloak repairable & refittable, but require you to cannibalize another hologram cloak to do so.  

Some alternative ways to address this would be:
- Always generate the item as being "fitted" or having normal fit.
- Reduce base encumbrance.
- Make item fit adjustable, but without making it repairable.

**Comment by John-Candlebury** [comment]
Spawning it so it always fit or has a normal fit, should be ok I think.

**Comment by Nameless-Survivor** [comment]
Thats fair. On the front end it would suck needing two to fit one. I’m happy with whatever change is decided on as long as the end result is a reasonable amount of encumbrance.
My preference for cannibalizing more damaged cloaks was because it would let you fit them, but also let you get maximum use out of them by using your badly damaged ones to repair/reinforce less damaged ones. 

John, its your item if I’m interpreting Github correctly, so I presume either you or Kevin would be the ultimate decider on this? I’m pretty new here so I don’t really know how you guys decide what changes are made and accepted.
