### ISSUE TITLE
Jenkins-latest Linux 64 Console builds wont start get lib errors. 

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#26964]
**Bug**
Jenkins builds of 64bit Linux tiles do not work on current 64bit Linux

**To Reproduce**  
Download current build and attempt to run it. You will get a lua error first about a missing library even though the lib is installed. Looks like Lua is linking to a lib that is not included in current lua any longer. 
If you resolve this you then get a cascade of other libs that are not installed even though they are. Example of this is wncurses. 

**Expected behavior**  
Should run without errors. 

**Screenshot** 
This is from a user on IRC 
https://i.imgur.com/DItHIW0l.png

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux 64bit
 - Current Jenkins build. 
 - Console

**Additional context**  
Suspect this is a problem with the build environment linking to incorrect libs or some other problem.

**Comment by Treah** [comment]
Example of the Lua error you get. 
`treah@whitedwarf:~/Downloads/cataclysmdda-0.C$ ./cataclysm-launcher 
./cataclysm: error while loading shared libraries: liblua5.3.so.0: cannot open shared object file: No such file or directory
treah@computer:~/Downloads/cataclysmdda-0.C$ ldconfig -p | grep -e liblua
        liblua5.2.so.5.2 (libc6,x86-64) => /usr/lib/liblua5.2.so.5.2
        liblua5.2.so (libc6,x86-64) => /usr/lib/liblua5.2.so
        liblua.so.5.3 (libc6,x86-64) => /usr/lib/liblua.so.5.3
        liblua.so (libc6,x86-64) => /usr/lib/liblua.so
treah@computer:~/Downloads/cataclysmdda-0.C$ 
`

**Comment by Epictyphlosion** [comment]
I think the bigger issue is that the latest Linux builds are outdated compared to the latest Windows builds

**Comment by Treah** [comment]
@Epictyphlosion 
How are they outdated? Do you mean the build environment or the actual builds? Cause the actual builds are done nightly.

**Comment by Treah** [comment]
After reviewing some of this it looks like my issue at least running it is that alot of these libraries are just different. I have ncurses 6 not 5 so that's broken in console. And as for lua its cause my version is newer and no longer has a lib link with that name. That is easy to fix but the other deps are not possible. 
Solution here would be to statically link needed lilbs into the binary files that are built on the page or have the linked to libs included in the game directory.

**Comment by Epictyphlosion** [comment]
> @Epictyphlosion
> How are they outdated? Do you mean the build environment or the actual builds? Cause the actual builds are done nightly.

The latest Linux build is 8104, while the latest Windows build is 8251

**Comment by Treah** [comment]
@Epictyphlosion 
Not sure where your looking. 
http://dev.narc.ro/cataclysm/jenkins-latest/Linux_x64/
They are all 8251 from what I am seeing

**Comment by AMurkin** [comment]
@Epictyphlosion if you are using CDDA launcher than you need do get its last version.

**Comment by ZhilkinSerg** [comment]
Lua was removed and newer builds should be working now.

**Comment by stonelike** [comment]
Hello,

I see this is closed, but since Lua was apparently removed from the game, I am confused as to why I am getting this error when I try to run the latest Stable build (Danny) on Linux;

`/cataclysm-tiles: error while loading shared libraries: liblua5.3.so.0: cannot open shared object file: No such file or directory`

I see no dependency mentioned in the Git readme for lua, I installed all other dependencies as far as I can tell, and I have simply unzipped the game archive into a folder and tried to run it without any other modifications.  Further guidance would be appreciated, thanks in advance.

**Comment by anothersimulacrum** [comment]
LUA support is still in 0.D, but was dropped past that.
