### ISSUE TITLE
Zipping/unzipping coats and jackets

### ISSUE THREAD

**Issue by hyper2snyper** [CleverRaven/Cataclysm-DDA#26968]
I think it would be cool to allow certain coats and jackets the ability to unzip, it would lessen coverage and lower the warmth for summer. If it is zipped it would grant a slight bit more warmth and coverage.

**Comment by I-am-Erk** [comment]
I'm of two minds here. It's a great idea, but it sounds like yet another little detail with only a tiny amount of game impact that we have to tell new players about...

**Comment by hyper2snyper** [comment]
alright, but new players would figure it out quick when they (A)ctivate their coat, and a message appears saying "you unzip your rain coat"

**Comment by kevingranade** [comment]
Not based on activation, but we could have a flag that means the player will automatically do this when it's beneficial for heat management.
