### ISSUE TITLE
"Saw off stock"

### ISSUE THREAD

**Issue by hyper2snyper** [CleverRaven/Cataclysm-DDA#26969]
Currently you can saw down a barrel on a weapon with a hacksaw, i propose the ability to saw off a stock with a hacksaw or would saw. This will decrease volume of weapon and make the weapon slightly easier to aim, the trade of would be it dramatically increases the recoil of firing the weapon.
Example: I have a double barrelled shotgun, I saw off the stock, now it is much smaller and easier to aim with, however after the first shot takes much longer to aim again.

**Comment by mlangsdorf** [comment]
Reduces volume, increases recoil and dispersion.  Makes sense to me.
