### ISSUE TITLE
Dialog Option For NPC Followers To Activate/Deactivate Worn/Carried Equipment

### ISSUE THREAD

**Issue by Nameless-Survivor** [CleverRaven/Cataclysm-DDA#26977]
Presently, if you give NPC's equipment to wear that has a function which can be activated/deactivated, such as night vision goggles or RM-13 Combat armor, there is no way to instruct them when to turn them on or off. As a result, they must either wear it uselessly, or be given it already active, which is a waste of batteries/plutonium cells/etc.

A dialog option to instruct NPC followers to activate both worn or carried equipment would make a large number of equipment viable for NPC usage, and make followers more useful.

**Comment by I-am-Erk** [comment]
Honestly I kind of wish that, while an NPC is using it, those sorts of objects would just activate, and quietly stop draining batteries/power supplies. It's unrealistic but anything else requires so much micromanagement.

**Comment by kevingranade** [comment]
Micromanaging item activations is not an option, and neither is making things magically consume no charges if worn by a npc.
