### ISSUE TITLE
Sling firing

### ISSUE THREAD

**Issue by hyper2snyper** [CleverRaven/Cataclysm-DDA#26970]
Sister suggestion for #26836
Allow to fire weapons on a sling by using the sling to support them,
like the Browning HMG, or even a SCAR
this would mean that having a sling on a gun will allow you to fire it while "wearing it" this would decrease accuracy slightly but would decrease recoil of the weapon and allow to fire larger weapons easier.

**Comment by mlangsdorf** [comment]
My first guess on an implementation would be to make the sling an activated item, and when you activate it, you're wielding the gun with a mild bonus to accuracy/stability.

I am extremely dubious about the ability to hip-fire an M2 by bracing it from a sling, though.

**Comment by hyper2snyper** [comment]
right, i was just using the m2 as an example
