### ISSUE TITLE
Gamma Globulin Shot has less volume than Syringe it's contained in.

### ISSUE THREAD

**Issue by VitreousEyes110** [CleverRaven/Cataclysm-DDA#26971]
**Describe the bug**  
Gamma Globulin Shot has 0.01 volume, Syringe has 0.25. This means when used the item grows to 25x its original size.

**To Reproduce**  
1. Make a player with Gamma Globulin Shot
2. Use Gamma Globulin Shot

**Expected behavior**  
The Gamma Globulin Shot should have equal volume to the syringe it is contained in.

**Screenshots**  
When used the newly grown syringe fills enough volume to push out the pizza.
![confusion](https://user-images.githubusercontent.com/45680256/49630111-bb83a400-f9ba-11e8-9d45-295e98ce8e61.PNG)

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version: [0.C-35001-g3672384]
 - Graphics version: [Tiles]
 - Mods loaded: [DDA, Disable NPC needs, Filthy clothing, Simplified nutrition, Bens GF recipes, Craftable guns pack, Makeshift items mod, Medieval and historical content, More survival tools, alternative map key, Mutant NPCs, NPC traits, More locations, Fuji's more buildings, Boats, Folding parts pack, Vehicle additions pack, Tanks and other vehicles, Classes and scenarios mod, Safe autodoc, Icecoon's Arsenal]

**Additional context**  
N/A

**Comment by I-am-Erk** [comment]
Honestly that's a pretty giant syringe. At a quarter of a volume unit, it's gotta be a 60ml syringe... What are all these horse medicine syringes doing floating around?

Probably both gamma globulin and syringe size should be adjusted to a more realistic number, 0.1 or 0.05 or so

**Comment by Zombiemanpig** [comment]
This should be reopened
