### ISSUE TITLE
Compile error in ranged.cpp

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#26976]
**Describe the bug**  
Error when compiling on 64bit Linux. 

**To Reproduce**  
Git pull current experimental. Attempt to build release version. 

**Expected behavior**  
Compiles. 

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux 64bit
 - Game Version: commit 4957555ea56606cece16765f7c2ca7904283ff56 

**Additional context**  
src/ranged.cpp: In lambda function:
src/ranged.cpp:1077:40: error: ‘class map’ has no member named ‘coord_to_angle’
         const int phi = std::abs( g->m.coord_to_angle( pc.pos().x, pc.pos().y, dst.x, dst.y ) -
                                        ^~~~~~~~~~~~~~
src/ranged.cpp:1078:40: error: ‘class map’ has no member named ‘coord_to_angle’
                                   g->m.coord_to_angle( pc.pos().x, pc.pos().y, recoil_pos.x, recoil_pos.y ) ) % 360;
                                        ^~~~~~~~~~~~~~
make: *** [Makefile:813: obj/tiles/ranged.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by hyper2snyper** [comment]
how do i fix it?

**Comment by Treah** [comment]
You will need to wait for the PR to get merged or checkout the code change and fix it yourself.
