### ISSUE TITLE
Trying to shoot smoker zombies with "precise shot" crashes the game

### ISSUE THREAD

**Issue by Arcade22** [CleverRaven/Cataclysm-DDA#26986]
**Describe the bug**  
Game crashes when i use the "fire with x precision" with a weapon

**To Reproduce**  
1. Make a player with a gun, magazine, and some ammo.
2. Spawn a smoker using the debug menu
3. press the p key to "take precise aim and fire"
4. It crashes

**Expected behavior**  
It doesn't crash and you try to fire (or don't fire if the target is out of sight)

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.C-35027-GBD1E450
 - Graphics version Tiles
 - Mods loaded DDA, Filthy clothing, simplified nutrition, disabled NPC needs

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by Arcade22** [comment]
After some additional testing it  would appear that not just shooting but simply aiming at a smoker and subsequently waiting a turn or "steadying your aim" will cause a crash. Presumably this has something to do with the changes in rev #8255 which "allow aiming anywhere".

**Comment by ViralAnomalyX** [comment]
I have this same problem when pressing 'f' to begin aiming a crossbow shot.

**Comment by AMurkin** [comment]
Probably the same reason as in #26990.
