### ISSUE TITLE
Hacksaws Should Have The Wood Sawing Quality.

### ISSUE THREAD

**Issue by SageB** [CleverRaven/Cataclysm-DDA#26985]
**Is your feature request related to a problem? Please describe.**  
Hacksaws currently lack the wood-sawing quality, despite being functionally similar to a wood saw. This is annoying, because it feels like it should be possible to saw wood using a hacksaw.

**Describe the solution you'd like**  
Hacksaws should be given the wood-sawing quality. 

**Describe alternatives you've considered**  
The alternative is that they don't have the wood-sawing quality. This is how it is now and I think it's bad.

**Comment by I-am-Erk** [comment]
Have you ever tried to cut wood with a hacksaw?

Given that wood sawing can be used to cut down trees, I don't think this is a great idea. While a hacksaw *can* cut wood, and a bow saw is a similar saw with a wood cutting blade, hacksaw blades are fine toothed and very slow for the job, and couldn't do a lot of the things that the wood sawing ability requires.

**Comment by SageB** [comment]
Yes, actually. It works pretty decently.  While it's not the best tool for the job, it doesn't make sense that it can't cut wood at all. It doesn't make sense that a sharp rock on a stick (stone adze) is better than an actual saw for cutting wood.

**Comment by mlangsdorf** [comment]
Woodsaw 1 for a hacksaw would be fine.  They're no worse than a makeshift stone adze for cutting wood.
