### ISSUE TITLE
mark firewood source, made me drop a live tank shell in the fire

### ISSUE THREAD

**Issue by alextandos1980** [CleverRaven/Cataclysm-DDA#26987]
**Describe the bug**  
i had constructed a firewood source over my pile of loot so that it would refresh my fires if they were about to run out however despite the fact i had two by fours the game automatically dropped a fucking live tank shell and other random junk like matches and primer into the fire this resulted in an explosion which caused minor damage. i reloaded the save and did everything the same way without knowing what caused the explosion and it happened again. it appears that the fuel source it chooses is completely random and you should probably look into this because it almost killed me
![image](https://user-images.githubusercontent.com/39634093/49677362-5b523800-fa76-11e8-9fc6-ab37ca5a8e81.png)

**Comment by alextandos1980** [comment]
![image](https://user-images.githubusercontent.com/39634093/49677480-f0edc780-fa76-11e8-91f1-58eabae7185c.png)

**Comment by I-am-Erk** [comment]
I, uh, I don't know if this is a bug. It might not be the greatest idea to declare a giant pile of unsorted goods that includes high explosives "firewood".

This is possibly the hardest I've ever laughed at a bug report. thank you for that.

**Comment by Nameless-Survivor** [comment]
I suspect that is not a bug, I bet its a feature designed to let you use unwanted items and garbage as fuel.

**Comment by kevingranade** [comment]
You labelled your loot pile as fuel, it threw the loot pile in the fire.  Working as intended, PEBCAK
