### ISSUE TITLE
Acidic ant "SHORTACIDTRAIL" flag causes crash to main menu.

### ISSUE THREAD

**Issue by nodatahere** [CleverRaven/Cataclysm-DDA#26997]
**Describe the bug**  
When loading into a new world, warnings appear concerning construction and mapgen. These are followed by the error below:

         DEBUG    : Error: data/mods//dda/../../json/monsters/insect_spider.json: line 845:29: invalid monster flag: "SHORTACIDTRAIL"

    "death_function": [ "ACID", "NORMAL" ],
    "harvest": "acidant_med",
    "flags": [ "ACIDPROOF", "
                            ^
                             SHORTACIDTRAIL", "CLIMBS", "HEARS", "POISON", "SEES", "SMELLS" ]
      },
      {

 
     FUNCTION : bool main_menu::new_character_tab()
     FILE     : src/main_menu.cpp
     LINE     : 694`

After the above error, the game crashes back to main menu.

**To Reproduce**  
1. Pull recent commit.
2. Create any world.
3. Attempt to create a character.
4. Game crashes back to menu with the aforementioned behavior.

**Expected behavior**  
Game would load files and enter character creation screen.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: [Xubuntu 18.04]
 - Game Version [0.C-35060-gbf30dbcb74-dirty]
 - Graphics version [Tiles]
 - Mods loaded [Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition]

**Additional context**  
[Full error list.](https://github.com/CleverRaven/Cataclysm-DDA/files/2659534/CDDA_Errors.txt)
Issue resolved by manually editing [insect_spider.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/monsters/insect_spider.json) to revert `SHORTACIDTRAIL` to `ACIDTRAIL`, resolving all errors and warnings.

**Comment by mlangsdorf** [comment]
Also can't confirm.  I just started a character on that base version with no issues.

**Comment by nodatahere** [comment]
Must be something off about my instance then.
