### ISSUE TITLE
Contact lenses compatible with Protective Lenses CBM

### ISSUE THREAD

**Issue by mikegogulski** [CleverRaven/Cataclysm-DDA#26999]
**Describe the bug**  
Contact lenses can be worn when the Protective Lenses CBM is installed.

The description for the Protective Lenses CBM reads:

`"Your eye sockets have been sealed with highly protective mirrored lenses and your tear ducts have been re-routed to your mouth.  When you cry, you must spit out or swallow your tears."`

Since contact lenses depend on liquid contact with the cornea, and the liquid involved is tears, these two items should be incompatible.

**To Reproduce**  
1. Install Protective Lenses CBM
2. Activate/apply contact lenses
3. "You can see more clearly" (assuming the player has a vision defect)

**Expected behavior**  
"Your eyes are covered with protective lenses which prevent the insertion of the contact lenses."

**Screenshots**  
see video below

**Versions and configuration(please complete the following information):**
 - OS: ?
 - Game Version - unknown, but it's a 2018 build
 - Graphics version - tiles
 - Mods loaded - many

**Additional context**  
Problem observed in a Youtube playthrough: https://youtu.be/YmEA43An9qk?list=PLxIQ9fpV90xMG4FheSs0FGsORme8IayF0&t=3531 sequence begins around 58:51. The CBM was installed earlier.

**Comment by Ker-Nes** [comment]
Maybe the CBM has a compartment for lenses? I mean, despite the name, the contact lenses don't strictly need direct contact with the eye, just to be close enough for it to distort light correctly to compensate for the person's visual deficiency. As such, if the CBM designers thought of the issue, it might have included a bit of a "pouch" or the like to hold a corrective lenses close enough to the correct position.

**Comment by mikegogulski** [comment]
Could be. If that's the intended design, then perhaps this can be solved simply by mentioning that in the CBM's description.

**Comment by HotSake** [comment]
Yeah, I think it would be best to just change the description to mention that the covers can be lifted to access the eyes as needed. Otherwise they should also prohibit installing other eye CBMs afterwards, and I don't think anyone wants that

**Comment by kevingranade** [comment]
You need to overhaul the description entirely if youre going to do that.  Everything about the way it is written now indicates it should conflict with qny other eye prostheses.

**Comment by mikegogulski** [comment]
Perhaps.

Now that I think about it, I'm a bit baffled by the optical bionics in overall terms. A player can have no fewer than 7 eye-slot bionics installed, yet only a single one of those (Telescopic Eyes) can correct a trait vision defect.

"You now have scent vision. You are still astigmatic."
"Your corneas are now made of diamond. Your nearsightedness is unaffected."
"You can now see in the dark, though everything is green. You are still farsighted."
"Your range of vision extends into the infrared, allowing you to see warm-blooded creatures in the dark. Too bad you still have cataracts."

**Comment by HotSake** [comment]
Fine, I can rewrite it to be a rip-off of Adam Jensen's lenses from Deus Ex instead of Molly's from Neuromancer. Basically, retractable instead of fixed. However, it brings to mind another issue which is the uselessness of the Nictitating Membrane CBM. That does nothing but let you see underwater, which these could easily do if they were watertight, basically acting as goggles. Would people be ok with Protective Lenses taking underwater sight, and eventually removing Nictitating Lenses entirely?

**Comment by HotSake** [comment]
@mikegogulski 

I thought Diamond Corneas corrected vision problems? They certainly should. Additionally, Scent Vision and Infrared Vision should ignore, but not correct, Nearsightedness for the range of their effect, if they don't already. They're really additional senses that shouldn't be affected by vision abnormalities.

**Comment by mikegogulski** [comment]
@HotSake : my take on Diamond Corneas (and, in general, on the others) was based on the description on the (grumble grumble) wiki. It seems reasonable that that CBM, too, should correct vision malus traits, but I have not looked at the recent code.

Scent Vision not affecting trait vision makes sense. Extra wiring between nasal receptors and visual cortex, the eyes aren't involved.

Infrared vision (or night vision) could be conferred by replacing the retina, without needing to involve the forward apparatus of the eye. It just seems unlikely that the retina would be replaced without replacing the entire orb.

On the whole I'd be happiest to see a new "bionic eye" system which is better integrated. Perhaps every eye CBM would grant a basic set of attributes (protective lenses plus removal of near/farsightedness). The others could be considered augmentations of the base eye bionics. Some of those might even be delivered in software (USB sticks?) rather than as CBMs, like night vision or infrared vision, or the +2 PER bonus from diamond corneas.

**Comment by HotSake** [comment]
I suppose Night Vision should still be affected by focusing errors, if it's basically just light amplification. It does share the graphics of light amp goggles. In theory, it should fail to work in pitch darkness, unless it integrates short wave, near IR radiation. Infrared Vision, on the other hand, is apparently long wave IR sense, as evidenced by the inability to tell anything about the nature of a heat source. It only shows low res blobs of heat. In that case, corneal abnormalities should be basically irrelevant.

**Comment by HotSake** [comment]
My contention is that the long wave, far IR vision granted by the Infrared Vision CBM is already so low res (see orange blobs) that near/far sightedness is basically irrelevant. The inability to resolve detail that is the relevant impairment to CDDA is already present in the implementation of the CBM (and thermal goggles it emulates).
