### ISSUE TITLE
Linux x32 not supported?

### ISSUE THREAD

**Issue by theanonym** [CleverRaven/Cataclysm-DDA#26995]
http://dev.narc.ro/cataclysm/jenkins-latest/Linux/Tiles/
No new builds since 02.11

**Comment by ZhilkinSerg** [comment]
32-bit Linux builds were dropped starting with #6652. Feedback to [this Reddit thread](https://www.reddit.com/r/cataclysmdda/comments/6raijb/dropping_32bit_linux_experimentals/) – it is no longer possible to resurrect them, but you can vent if you wish.

**Comment by ZhilkinSerg** [comment]
You can still build manually, we just don't provide precompiled binary.
