### ISSUE TITLE
Game crashes when I try to fire the FTK fusion gun

### ISSUE THREAD

**Issue by loveosu** [CleverRaven/Cataclysm-DDA#27003]
I was in a mega city and came across a Z horde. I grabbed my FTK fusion gun and aim at the zombie in the center of the crowd. When I pressed "f" to fire, the game crashes. This repeat again and again, even when I get out of the city.

Window 7 Ultimate
Game version:  0.C-35060-gbf30dbc (tiles)  with 8263 build.
Mods used:  [
  "dda",
  "Cata++",
  "Experimental-Z-Level",
  "more_locations",
  "FujiStruct",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "realguns",
  "SD_Magcrafting_Realguns_Extension",
  "StatsThroughSkills",
  "Tolerate_This",
  "Urban_Development",
  "bio_mod",
  "boats",
  "craftgp",
  "deoxymod",
  "ew_pack",
  "makeshift",
  "more_buildings",
  "more_classes_scenarios",
  "no_religious_Texts",
  "no_reviving_zombies",
  "npc_traits",
  "filthy_morale",
  "modular_turrets",
  "Salvaged_Robots",
  "BIGRIVER",
  "novitamins",
  "adv_gear",
  "blazemod",
  "Tanks"
,  "No_Fungi"
]
   Graphic: Realperson Tileset

CRASH LOG FILE: config/crash.log
VERSION: 0.C-35060-gbf30dbc
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5CDF25[cataclysm-tiles.exe+0x1CDF25]
    @0x5CEAD2[cataclysm-tiles.exe+0x1CEAD2]
    SMPEG_error+0x4B034@0xE4D5B0[cataclysm-tiles.exe+0xA4D5B0]
    _C_specific_handler+0x8C@0x76D47388[ntdll.dll+0x57388]
    _chkstk+0x9D@0x76D5BF7D[ntdll.dll+0x6BF7D]
    RtlInitializeResource+0x53A@0x76D3043A[ntdll.dll+0x4043A]
    KiUserExceptionDispatcher+0x2E@0x76D5B61E[ntdll.dll+0x6B61E]
    SDL_LogCritical+0x12FD6@0xE6DE86[cataclysm-tiles.exe+0xA6DE86]
    IMG_LoadWEBP_RW+0x428CE1@0x1388991[cataclysm-tiles.exe+0xF88991]
    IMG_LoadWEBP_RW+0x1911EE@0x10F0E9E[cataclysm-tiles.exe+0xCF0E9E]
    wcscspn+0xA3@0x7FEFE19908F[msvcrt.dll+0x908F]
    @0x5CEA6C[cataclysm-tiles.exe+0x1CEA6C]
    IMG_LoadWEBP_RW+0x17D718@0x10DD3C8[cataclysm-tiles.exe+0xCDD3C8]
    IMG_LoadWEBP_RW+0x48B883@0x13EB533[cataclysm-tiles.exe+0xFEB533]
    IMG_LoadWEBP_RW+0x4909FE@0x13F06AE[cataclysm-tiles.exe+0xFF06AE]
    IMG_LoadWEBP_RW+0x49014C@0x13EFDFC[cataclysm-tiles.exe+0xFEFDFC]
    @0x887C6E[cataclysm-tiles.exe+0x487C6E]
    @0x89C6D7[cataclysm-tiles.exe+0x49C6D7]
    @0xC0745C[cataclysm-tiles.exe+0x80745C]
    @0xC0BC1C[cataclysm-tiles.exe+0x80BC1C]
    @0x6E6313[cataclysm-tiles.exe+0x2E6313]
    @0x6E6A96[cataclysm-tiles.exe+0x2E6A96]
    @0x7187EB[cataclysm-tiles.exe+0x3187EB]
    @0x6FA3A0[cataclysm-tiles.exe+0x2FA3A0]
    IMG_LoadWEBP_RW+0x4BC189@0x141BE39[cataclysm-tiles.exe+0x101BE39]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0xD@0x76AE59CD[kernel32.dll+0x159CD]
    RtlUserThreadStart+0x1D@0x76D4385D[ntdll.dll+0x5385D]

**Comment by Night-Pryanik** [comment]
Probably the same reason as in #26990.
