### ISSUE TITLE
stats through activities

### ISSUE THREAD

**Issue by Leviathan21** [CleverRaven/Cataclysm-DDA#27000]
**Is your feature request related to a problem? Please describe.**  
just like stats-through-kills/skills, the player character gain stats by activities

**Describe the solution you'd like**  
adds hidden bar, once hidden stat bar is filled player gains stat increase

**Describe alternatives you've considered**  
the hidden bar thing is filled by doing any activity that directly requires stat, like reading books, dodging things, beating things, spotting things etc

**Additional context**  
complex things, like stat rust, ration affects stats, etc

**Comment by nullinsky** [comment]
Huh? This is better off as a mod... and the mod already exists.

Stat rust would be pretty bad, it'll force the player to do meaningless actions to prevent atrophying.
Consumables affecting stats are best limited to drugs/medicine. Dunno how I would react if eating spinach suddenly made me strong.

**Comment by AskaHope** [comment]
Just like exercising skills on Nethack? The player could get 9999 Per for examining nearby dirt.

**Comment by CoroNaut** [comment]
Most of the alternatives you've listed are already accounted for. reading books gives experience in a wide variety of skills which would increase your stats if you have "Stats-through skills" enabled, which I assume you do. dodging is a direct skill, beating things is two skills; melee+unarmed, and spotting things would cause the problem AskaHope said. There is also the question "should spotting a single zombie multiple times give one or more bundles of exp?". So really, the mod stats through skills is all you're looking for from what I can see. This is not even mentioning the skills you get from crafting things.

Now if you are asking for more ways to increase your skills, there would be very few sources to tap into that haven't already been accounted for. Such sources would once again pose the "should it be repetitive?" question or are too rare that you may use the source only once every couple of play through's.

**Comment by kevingranade** [comment]
I'm in favor of doing this sort of thing eventually, but it needs a lot more thought put into it before it merits an issue.
