### ISSUE TITLE
Brave of the King profession starts with a scabbard that can't store its starting weapon.

### ISSUE THREAD

**Issue by Centac** [CleverRaven/Cataclysm-DDA#27018]
**Describe the bug**  
Brave of the king is a profession added by Medieval_Stuff. You start with a khopesh inside of a scabbard. You can take the khopesh out of the scabbard, but once you do you can't put it back inside the scabbard.

**To Reproduce**  
Start new game with Brave of the king profession.
Activate scabbard to take out the khopesh.
Attempt to activate the scabbard again.

**Expected behavior**  
If you start with a khopesh in a scabbard, you should be able to put it back in that same scabbard.
Either the khopesh should be storable in a scabbard, or the profession shouldn't start with a scabbard to begin with.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-33359-gfbe9044
 - Graphics version: Tiles
 - Mods loaded: Medieval_Stuff

**Comment by Pupsi-Mupsi** [comment]
You are right! Hope #27027 will fix it. Thanks for reporting this bug!
