### ISSUE TITLE
Even Battery Charging.

### ISSUE THREAD

**Issue by WDevil3221** [CleverRaven/Cataclysm-DDA#27019]
**Is your feature request related to a problem? Please describe.**  
So, yes, you have TONS of batteries installed on your awesome mobile base. And you want to charge this one car battery/small storage battery you have on your cart/in your hand? Well, you can't..you gotta wait for the **TOP** battery to be done first! And how long will that take..? Oh I don't know, probably a couple of hours in-game..oh look, sun's down.

**Describe the solution you'd like**  
Kevin did mention this before, probably a year ago or so, that he would make batteries charge **evenly**, or rather, charge the lowest first. Shouldn't be too hard...right?

**Describe alternatives you've considered**  
Maybe the ability to rearrange battery slots? Or tank slots? That would be neat too.

**Additional context**  
Thanks again for making the Favorites tab! And again, just like the last suggestion I made, any other sorts of suggestions are more than welcome! Might even motivate devs to pick this suggestion up! c:

**Comment by Night-Pryanik** [comment]
I'm sure this issue was raised several times in the past, though I'm not sure was it on forums only or here on github too.

**Comment by WDevil3221** [comment]
Kevin did mention it would be an easy fix. Though, that might be just my memory failing me.

**Comment by mlangsdorf** [comment]
in src/vehicle.cpp, the charge_battery() function would need to have two loops where it has one: the first one to count all the battery parts, the second to divide the amount among each battery.

ideally, the counting would be moved to vehicle::refresh() (also in src/vehicle.cpp), and a battery cache would be added to src/vehicle.h like the other caches that are updated in refresh().

This is a great first issue for someone with some familiarity with programming who wants to get involved in CDDA's vehicles code.

**Comment by kevingranade** [comment]
The implementation I'd prefer would be to scan the batteries and simply recharge the lowest charged battery for any given charge action.

**Comment by WDevil3221** [comment]
That's what you mentioned before in Discord! It does sound less complicated to charge the lowest first.

**Comment by ZhilkinSerg** [comment]
Should be fixed in #27122.
