### ISSUE TITLE
Hostile NPCs not attacking

### ISSUE THREAD

**Issue by UltimaVirus** [CleverRaven/Cataclysm-DDA#27016]
**Describe the bug**  
Doing missions for the Refugee Center and bandits just stand there and let me poke them to death with my rapier.  This happened on every mission.

**Versions and configuration(please complete the following information):**
0.C-35078-g99ec0d1

**Additional context**  
[before_last_restore.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2660158/before_last_restore.zip)

**Comment by Nameless-Survivor** [comment]
Mlangsdorf mentioned this on the forums the other day, its a bug from an update, they are working on it.

**Comment by Solusphere** [comment]
Myself and Rundown on the discord both ran into this issue. Here's a screenshot for confirmation.
https://cdn.discordapp.com/attachments/252368751016542218/522317105471684613/unknown.png

**Comment by scanevaro** [comment]
Expanding the issue:
I can see the NPCs actually attack my followers but not me. 
Also, enemy NPC is firing an SMG and goes through a reinforced glass. May need to report this on another ticket

**Comment by mlangsdorf** [comment]
the bug is specifically:
in npcmove.cpp, in npc::choose_target(), at the very end, in this code:
```
    } else if( is_enemy() ) {
        if( sees( g->u ) && check_hostile_character( g->u ) ) {
            ai_cache.target = g->shared_from( g->u );
            ai_cache.danger = std::max( 1.0f, ai_cache.danger );
        }
```
the g->u pointer gets set to ai_cache.target if the player is the NPC's target.

then, in npc::move(), at the very start:
```
    const Creature *target = current_target();
    const std::string &target_name = target != nullptr ? target->disp_name() : no_target_str;
```
which invokes this code:
```
const Creature *npc::current_target() const
{
    // TODO: Arguably we should return a shared_ptr to ensure that the returned
    // object stays alive while the caller uses it.  Not doing that for now.
    return ai_cache.target.lock().get();
}
```
and returns a nullptr when `ai_cache.target == g->shared_from( g->u )`, even though it really shouldn't.

I can figure that much out, but I can't figure out why currrent_target isn't returning g->u recast as a Creature * like it is supposed to.

**Comment by jbytheway** [comment]
The cause is the following code in `game`:
https://github.com/CleverRaven/Cataclysm-DDA/blob/ef5932543574de119cab2b585b3e0f581e8955bd/src/game.cpp#L5351-L5354
When asked for a `shared_ptr` to the player It creates a 'fake' `shared_ptr` to the player with a null deleter.  As soon as this `shared_ptr` is cast to a `weak_ptr` the refcount goes to zero and the `weak_ptr` becomes null.

I think the best fix is for `game` to permanently store this fake `shared_ptr` to the player and return a copy of it in this function.  That way the refcount will not go to zero.

(An alternative would be to make the player actually be managed properly by a `shared_ptr`, but that's more invasive and probably not worth the trouble).

That fix is pretty easy; harder is testing it works.  I wouldn't really want to fix it without adding a suitable test, and I'm not sure how to go about that.

**Comment by mlangsdorf** [comment]
Ideally, this code would be a sufficient test case:
```diff
diff --git a/tests/npc_test.cpp b/tests/npc_test.cpp
index 605a710e3d..a1c9fe43eb 100644
--- a/tests/npc_test.cpp
+++ b/tests/npc_test.cpp
@@ -414,3 +414,51 @@ TEST_CASE( "npc-movement" )
         check_npc_movement( origin );
     }
 }
+
+TEST_CASE( "npc_threat" )
+{
+    g->place_player( tripoint( 10, 10, 0 ) );
+
+    // kill npcs before removing vehicles so they are correctly unboarded
+    for( int y = 0; y < height; ++y ) {
+        for( int x = 0; x < width; ++x ) {
+            const tripoint p = g->u.pos() + point( x, y );
+            Creature *cre = g->critter_at( p );
+            if( cre != nullptr && cre != &g->u ) {
+                npc *guy = dynamic_cast<npc *>( cre );
+                cre->die( nullptr );
+                if( guy ) {
+                    overmap_buffer.remove_npc( guy->getID() );
+                }
+            }
+        }
+    }
+    g->unload_npcs();
+
+    const auto spawn_npc = []( int x, int y, npc_class_id npc_class ) {
+        tripoint pos = tripoint( x, y, 0 );
+        std::shared_ptr<npc> guy = std::make_shared<npc>();
+        guy->normalize();
+        guy->randomize( npc_class );
+        guy->spawn_at_precise( { g->get_levx(), g->get_levy() }, pos );
+        overmap_buffer.insert_npc( guy );
+        g->load_npcs();
+        return guy;
+    };
+    std::shared_ptr<npc> friendly = spawn_npc( 10, 11, NC_SHOPKEEP );
+    friendly->set_attitude( NPCATT_FOLLOW );
+    friendly->name = "Ally NPC";
+
+    std::shared_ptr<npc> hostile = spawn_npc( 11, 10, NC_THUG );
+    hostile->set_attitude( NPCATT_KILL );
+    hostile->name = "Enemy NPC";
+
+    REQUIRE( friendly != hostile );
+
+    friendly->regen_ai_cache();
+
+    hostile->regen_ai_cache();
+    REQUIRE( friendly->current_target() != nullptr );
+    REQUIRE( hostile->current_target() != nullptr );
+    CHECK( hostile->current_target()->get_name() != friendly->get_name() );
+}
```
but for some reason, `g->all_npcs()` is returning an empty list inside of regen_ai_cache() so it's not working.

**Comment by kevingranade** [comment]
Actually how about we store the shared_ptr<player> in player?
Then it gets destroyed automatically if the player is destroyed.

Now I'm thinking this would be a good approach for active item lists as well, certainly much more robust than what we have now.

**Comment by mlangsdorf** [comment]
Okay, I have a test case now.  This passes if commit ceab30801f `Avoid circular references between NPCs` is reverted, and fails otherwise.  It could use some elaboration - i would like the friendly NPC to identify the hostile NPC as an enemy as a cross-check - but it captures the key issues.

```diff
index 6029c5a171..67e2c7f3b0 100644
--- a/tests/npc_test.cpp
+++ b/tests/npc_test.cpp
@@ -1,6 +1,7 @@
 #include "catch/catch.hpp"
 
 #include "common_types.h"
+#include "faction.h"
 #include "field.h"
 #include "game.h"
 #include "map.h"
@@ -409,3 +410,54 @@ TEST_CASE( "npc-movement" )
         check_npc_movement( origin );
     }
 }
+
+TEST_CASE( "npc_threat" )
+{
+    g->faction_manager_ptr->create_if_needed();
+
+    g->place_player( tripoint( 10, 10, 0 ) );
+
+    // kill npcs before removing vehicles so they are correctly unboarded
+    for( int y = 0; y < height; ++y ) {
+        for( int x = 0; x < width; ++x ) {
+            const tripoint p = g->u.pos() + point( x, y );
+            Creature *cre = g->critter_at( p );
+            if( cre != nullptr && cre != &g->u ) {
+                npc *guy = dynamic_cast<npc *>( cre );
+                cre->die( nullptr );
+                if( guy ) {
+                    overmap_buffer.remove_npc( guy->getID() );
+                }
+            }
+        }
+    }
+    g->unload_npcs();
+
+    const auto spawn_npc = []( int x, int y, const std::string &npc_class ) {
+        const string_id<npc_template> test_guy( npc_class );
+        int model_id = g->m.place_npc( 10, 10, test_guy, true );
+        g->load_npcs();
+
+        npc *guy = g->find_npc( model_id );
+        REQUIRE( guy != nullptr );
+        guy->setpos( g->u.pos() + point( x, y ) );
+        return guy;
+    };
+    npc *friendly = spawn_npc( 6, 0, "test_talker" );
+    REQUIRE( rl_dist( g->u.pos(), friendly->pos() ) <= 6 );
+    friendly->set_attitude( NPCATT_FOLLOW );
+    friendly->name = "Ally NPC";
+
+    npc *hostile = spawn_npc( 0, 1, "thug" );
+    REQUIRE( rl_dist( g->u.pos(), hostile->pos() ) <= 1 );
+    hostile->set_attitude( NPCATT_KILL );
+    hostile->name = "Enemy NPC";
+
+    REQUIRE( friendly != hostile );
+    hostile->regen_ai_cache();
+    friendly->regen_ai_cache();
+    REQUIRE( hostile->current_target() != nullptr );
+    CHECK( hostile->current_target()->get_name() != friendly->get_name() );
+    CHECK( friendly->current_target() != nullptr );
+
+}
```
