### ISSUE TITLE
"Planting" zone activity temporarily glitches the  planted square if an item had been present

### ISSUE THREAD

**Issue by prutschman** [CleverRaven/Cataclysm-DDA#27013]
**Describe the bug**  

Background:
A tilled but unplanted tile can be planted in by 'e'xamining it. If there are items present in the square, the inventory menu is displayed instead, preventing the planting of seeds in occupied tilled plots. Attempting to drop an item into a planted tile is prohibited in both the simple and advanced inventory menus.

An occupied tilled plot, if marked as a planting zone, is eligible for planting even though they player would not be able to do this manually. Once the tile is planted the items previously there disappear. Attempting to 'e'xamine the newly planted tile results in the following error:
```
 DEBUG    : The seed item wild herbs is not a seed!
 
 FUNCTION : void iexamine::aggie_plant(player &, const tripoint &)
 FILE     : src/iexamine.cpp
 LINE     : 1811
```
Upon saving and reloading, the tile is reset to un-tilled state, and both the planted seed and the non-seed item are present in the square.

**To Reproduce**  
1. Make a player with a digging tool, some seeds, and some other non-seed item.
2. Designate a square for planting
3. Perform zone activity Till
5. 'e'xamine the tile (Prompted for planting. Say "no")
4. Drop the non-seed item on the tilled square
5. 'e'xamine the tile (No option to plant; inventory instead)
5. Perform zone activity Plant
6. 'e'xamine the freshly planted square
7. Observe the error
8. Save game
9. Reload
10. Observe that the planted tile has reverted to un-tilled, and both the seed and the non-seed item are present.

**Expected behavior**  
I expect the tile to not be planted; manual planting would be forbidden, so it should be skipped by the zone activity. Either way, the tile shouldn't glitch.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: macOS 10.10.5
 - Game Version 0.C-35058-gbf30dbcb74
 - Graphics version Tiles
 - Mods loaded [DDA, filthy clothes, disable NPC needs, simplified nutrition, more survival tools, folding parts pack]

**Comment by prutschman** [comment]
A fix might be to add a check to the `cleanup` function in `activity_handlers::plant_plot_do_turn`, throwing out tiles that already have things in them.

**Comment by Night-Pryanik** [comment]
> Upon saving and reloading, the tile is reset to un-tilled state, and both the planted seed and the

Please complete the sentence.

**Comment by prutschman** [comment]
Edited. Sorry about that.
