### ISSUE TITLE
Thigh-high boots and leather skirt share the same layer

### ISSUE THREAD

**Issue by Admiral-Wily** [CleverRaven/Cataclysm-DDA#27059]
![conflict](https://user-images.githubusercontent.com/45573913/49760733-3686dc00-fc93-11e8-81d9-d622980109dd.png)
As you can see they share the same layer and cause extra encumbrance which I don't think makes any sense... Someone suggested moving skirts to "Layer: outer" but I don't know if that would cause other layer conflicts that wouldn't make sense. What are your thoughts?

**Comment by tyrael93** [comment]
Just use the waist tag on skirts like a belt does. The coverage and damage reduction on skirte/miniskirts is negligiblr anyway, they're just roleplay items.

**Comment by Admiral-Wily** [comment]
> 
> 
> Just use the waist tag on skirts like a belt does. The coverage and damage reduction on skirte/miniskirts is negligiblr anyway, they're just roleplay items.

Wouldn't that just cause a conflict with a belt? The point is to avoid layer conflicts that don't make sense... 
![skirt with belt](https://user-images.githubusercontent.com/45573913/49788505-826b6c80-fcf7-11e8-85ca-f61be903c7ac.jpg)
^A skirt with a belt.

**Comment by Night-Pryanik** [comment]
I guess we just need to add another layer to avoid conflicts like these.

**Comment by kevingranade** [comment]
Or recognize that its a limitation of the system and tolerate it.

Moving clothes to new layers arbitrarally to avoid conflicts makes just as little sense as the conflict itself.

If you want to look into having non-overlapping coverage, that is what would address this and reflect what's happening.
