### ISSUE TITLE
Debug error if aim is on same square as charecter.

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#27051]
**Describe the bug**  
When doing a precise aim or possibly other steady aim types and you do not aim at least one square away you will get a debug error. 

**To Reproduce**  
1. Make a player with a gun, magazine, and some ammo.
2. Press p to do a precise aim but don't move the reticle anywhere. 
3. fire and you will get the message. 

**Expected behavior**  
Prevent firing if aim is in same square as the character, remove the debug error and allow it tho this makes little sense. Don't fire and give message in message log tho this is covered up by the aiming interface. Could just exit the interface, don't fire and then give message. 

**Screenshots**  
![image](https://user-images.githubusercontent.com/12091471/49741130-f4d64100-fc52-11e8-8679-a94d0c0c00a3.png)

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux x64 
 - Game Version: 0.C-35104-g2efbc377d
 - Terminal version tested. 
 - Mods loaded: None for test world. 

**Additional context**  
Probably related to  #26881

This is really just error handling type stuff as this type of condition was very rare to occur if not impossible before the change to aiming was made.

**Comment by Treah** [comment]
Possible fix is #27046

**Comment by Epictyphlosion** [comment]
I could totally see this being changed so if you do that, a message pops up saying "Really shoot yourself?" Like a more extreme version of pressing Q, lol

**Comment by OzoneH3** [comment]
Fixed in #27046
