### ISSUE TITLE
Allow the magnifying glass to correct hyperopia.

### ISSUE THREAD

**Issue by kwl01skz** [CleverRaven/Cataclysm-DDA#27056]
**Is your feature request related to a problem? Please describe.**  
My grandmother can use a magnifying glass to correct farsightedness (FIX_FARSIGHT) while reading, but @ can't.

**Describe the solution you'd like**  
When reading and making, if there is a magnifying glass around, it is allowed to use it automatically to correct the hyperopia.
This requires more code to be added.

**Describe alternatives you've considered**  
Give the flag of the magnifying glass FIX_FARSIGHT and make it wearable.
This only needs to modify little json, but it is a bit silly.

**Comment by Epictyphlosion** [comment]
Interesting! I wonder if someone could add a recipe where you can make hyperopia glasses from two magnifying glasses, lol

**Comment by natsirt721** [comment]
This should work, but impose a significant learn speed penalty.
