### ISSUE TITLE
Keep the Player Moving (FTL Style)

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#27061]
I would like to suggest a game mode that would keep the player moving.

One of the great strengths of the game FTL was the aspect that the player couldn't just leisurely explore an area and amass all the resources that they needed and then move on when they wanted to. (There is a certain amount of boredom that constantly amassing resources creates). In FTL the player felt constantly hounded and were eventually punished for staying too long in one spot, forcing the player to make difficult choices and increasing the games excitement.

The idea is that this would encourage players to make critical choices and to pack light and/or to always carry their essential gear on themselves. Dissuading players from becoming hoarders. Keeping players cold, sick, and desperate instead of sitting on a lifetime supply of cough syrup.

Should I take the Hummer or the RV?
Katana or Awl Pike?
Multi-tool or Screwdriver set?

Some examples/ideas of a good motivator might be Blight, Nuclear Winter, Fire, Increased Zombie Presence/Threat, etc. It could also be something like the ghost from Spelunky.

Maybe a combination?

I'm no programmer, I just want to try to share my perspective to see if anyone can make some good of it.

**Comment by Xion350** [comment]
This is an issue more suited for discource, rather than github.

https://discourse.cataclysmdda.org/

**Comment by Treah** [comment]
Interesting suggestion, this can be done by the player themselves instead of something built in tho. Also there is the ability to play with auto turns on so zombies will move to you giving you no time to just wait and figure out what to do next.

**Comment by ZhilkinSerg** [comment]
We do want something similar in pre-game mini-game:

https://discourse.cataclysmdda.org/t/dynamic-start-scenario/17589

**Comment by Leland** [comment]
CDDA's Github is for resolving issues or to discuss implementation details – like what's been mentioned above, I'd encourage you to open up a thread on Discourse to solicit discussion on this! Sounds interesting 😁
