### ISSUE TITLE
Segmentation Fault, unknown cause

### ISSUE THREAD

**Issue by torrasque666** [CleverRaven/Cataclysm-DDA#27060]
Game version: 0.C-35105-g3de7663

Operating system: Windows 10

Tiles or curses: Tiles

Mods active:
Dark Days Ahead
Disable NPC Needs
Simplified Nutrition
Filthy Clothing
Craftable Gun Pack
Safe Autodoc
Bright Nights
Dinomod
Modular Turrets
Salvaged Robots
Mining Mod
Necromancy
Makeshift Items Mod
Medieval and Historic Content
More Survival Tools
StatsThroughSkills

### Expected behavior

Not crashing

### Actual behavior

Segmentation fault

### Steps to reproduce the behavior

Unknown, just happens seemingly randomly

### Crash Log:
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5CDC95[cataclysm-tiles.exe+0x1CDC95]
    @0x5CE842[cataclysm-tiles.exe+0x1CE842]
    SMPEG_error+0x4B034@0xE4F0A0[cataclysm-tiles.exe+0xA4F0A0]
    _C_specific_handler+0x98@0x7FFC2DB27C58[msvcrt.dll+0x27C58]
    _chkstk+0x11D@0x7FFC2E5AED3D[ntdll.dll+0x9ED3D]
    RtlWalkFrameChain+0x13F6@0x7FFC2E516C86[ntdll.dll+0x6C86]
    KiUserExceptionDispatcher+0x2E@0x7FFC2E5ADC6E[ntdll.dll+0x9DC6E]
    memcmp+0x30@0x7FFC2DB5CBF0[msvcrt.dll+0x5CBF0]
    IMG_LoadWEBP_RW+0x2C5E57@0x12275F7[cataclysm-tiles.exe+0xE275F7]
    @0x6D72D9[cataclysm-tiles.exe+0x2D72D9]
    @0x5E7A2A[cataclysm-tiles.exe+0x1E7A2A]
    @0x6F19A0[cataclysm-tiles.exe+0x2F19A0]
    @0x716216[cataclysm-tiles.exe+0x316216]
    @0x6F9FF0[cataclysm-tiles.exe+0x2F9FF0]
    IMG_LoadWEBP_RW+0x4BB959@0x141D0F9[cataclysm-tiles.exe+0x101D0F9]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFC2D703034[KERNEL32.DLL+0x13034]
    RtlUserThreadStart+0x21@0x7FFC2E581471[ntdll.dll+0x71471]

**Comment by Treah** [comment]
Some of your mods listed here are 3rd party and not included in base. There is also no info on how to reproduce the problem. I am unsure if this stack trace is very helpful so someone else might be able to comment on this but with the other info this is going to be hard to impossible to resolve as it stands. 

Perhaps do a bit more testing and see if there is something you can specifically do to trigger the error. Also there is another PR/s to address crashes as well so its possible one of them may fix the problem.

**Comment by ZhilkinSerg** [comment]
Any errors in `debug.log` after crash?

**Comment by torrasque666** [comment]
15:10:47.733 ERROR MAP : (error message will follow backtrace)
	(@0x5e29ae[cataclysm-tiles.exe+0x1e29ae]), 
	(@0x5e2f8a[cataclysm-tiles.exe+0x1e2f8a]), 
	(@0x8ccc1a[cataclysm-tiles.exe+0x4ccc1a]), 
	(@0x8cd12d[cataclysm-tiles.exe+0x4cd12d]), 
	(@0x8cd44e[cataclysm-tiles.exe+0x4cd44e]), 
	(@0x6dc92e[cataclysm-tiles.exe+0x2dc92e]), 
	(@0x5e7b0e[cataclysm-tiles.exe+0x1e7b0e]), 
	(@0x6f1996[cataclysm-tiles.exe+0x2f1996]), 
	(@0x716216[cataclysm-tiles.exe+0x316216]), 
	(@0x6f9ff0[cataclysm-tiles.exe+0x2f9ff0]), 
	(IMG_LoadWEBP_RW+0x4bb959@0x141d0f9[cataclysm-tiles.exe+0x101d0f9]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0x14@0x7ffc2d703034[KERNEL32.DLL+0x13034]), 
	(RtlUserThreadStart+0x21@0x7ffc2e581471[ntdll.dll+0x71471]), 
Backtrace emission took 0 seconds.
src/map.cpp:6955: Empty locations for group GROUP_CHUD at 1,7,-4 global 1477,2131,-4

**Comment by torrasque666** [comment]
Happens shortly after using the teleportation options in the debug menu. Likely also happens when using the teleportation CBMs (untested though)

**Comment by BrettDong** [comment]
Why close?
