### ISSUE TITLE
Subway T-intersection Spawns 1 tile thick wall across tracks.

### ISSUE THREAD

**Issue by mekaerwin** [CleverRaven/Cataclysm-DDA#27073]
When there is a T-intersection in the subway and the center of the T is a station (it has stairs) a one tile wide wall spawns across the passage that would be the leg of the T.

**To Reproduce**  
Not really sure other than going through subway after subway looking for this on the off chance it spawns.

**Expected behavior**  
The T intersection should be open to tracks in all three directions. There shouldn't be a wall across the tracks.

**Screenshots**  
https://www.dropbox.com/s/j07x51nj9kgsvsh/subway.png?dl=0

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version [0.C-35126-g15ef21f]
 - Graphics version [Tiles]
 - Mods loaded [No mods]

**Comment by Night-Pryanik** [comment]
Please replace all the pre-written issue template text with description of _your_ issue.

**Comment by mekaerwin** [comment]
Yeah, sorry, I didn't realize that clicking that button was submitting it all.

**Comment by Night-Pryanik** [comment]
To insert a picture, just copy-paste the link. Github will automatically convert it. (I've made it for you)

**Comment by ZhilkinSerg** [comment]
That's not a T-intersection. This happens when subway track connects to non-rotated subway station from west or east sides.

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/a9bd40d2a53999d1a61e209c4a5174b2baf41f9d/src/mapgen_functions.cpp#L1272-L1297

**Comment by mekaerwin** [comment]
I'm trying to follow you here. I see that there is a t-section setup in the code, but it didn't get used here and it should have? When I say there are tracks to the north, south and west I mean connecting from other cells.  If the station had been rotated it would have been worse because the walls would have been to the north and south blocking the track there.

**Comment by mekaerwin** [comment]
I'm not familiar with the code but do the stations have setups for different intersections (4way, t) or is it only tracks that have those setups?
