### ISSUE TITLE
0.C-35170 - Cooked Brains inflict player with neural parasites

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#27084]
Upon preparing and eating some moose brains, I was immediately inflicted with hallucinations, pain, and severe health problems, which upon consulting the discord I was informed were brain parasites.

![image](https://user-images.githubusercontent.com/19789267/49914515-7dabe180-fecc-11e8-9641-211c7297a2a7.png)

While I can certainly understand contracting such parasites from eating brains raw, as you can see in the screenshot, I clearly got them upon eating cooked brains, which seems unintentional to me.

**Comment by Solusphere** [comment]
If you're cooking it anywhere near properly, 100% of all macroscopic parasites should be killed, as well as the vast majority of harmful microbes.

Prions, such as those that cause Mad Cow Encephalitis, can very rarely persist after cooking by virtue of being inanimate molecules to begin with, but the disease being caused here is explicitly parasitic in nature, and is successfully treated through antiparasitic medication, so we can safely rule out those being responsible.

**Comment by OzoneH3** [comment]
Added by @KorGgenT. It drops from parasites 100 for uncooked to 15 for cooked.
```
{
    "id": "brain_cooked",
    "type": "COMESTIBLE",
    "copy-from": "brain",
    "name": "cooked brains",
    "name_plural": "cooked brains",
    "description": "Now you can emulate those zombies you love so much!",
    "parasites": 15,
    "healthy": -2,
    "fun": -8
  }
```

**Comment by Solusphere** [comment]
If that's how it currently works, then it should absolutely be changed. All that does is make it so a smart player simply never touches the item. Brains take a whopping 45 minutes and double the usual amount of heating charges to cook, and their caloric value is tiny. If, even in the best possible case, they come with a not-insubstantial risk of highly debilitating disease when other, better, easier foods don't, why bother? They have massive amounts of vitamin b12, but that's not hard to source elsewhere. As it is, they're just a newbie trap.

I intensely dislike mechanics that randomly punish you despite playing optimally. Debilitating food-borne diseases should be something there to counterbalance risky, possibly desperate behavior, such as eating raw or possibly tainted food, not a bolt from the blue striking down the unfortunate.

And on top of that, as I highlighted earlier, it's blatantly unrealistic. The chances of receiving a parasite infection from ANYTHING that's been adequately cooked, let alone cooked for 45 minutes, is vanishingly small. We're talking one in a million levels here, not one in 7.

**Comment by SirPendrak** [comment]
Wait, right now every raw brain gives you 100% chance to get infected with parasites? 
Shouldnt it be something like chance of animal being infected x chance of transmission? 
Something like 20% x 50% = 10% of infection, and baisically 0 for cooked. I took the numbers of my ass, but you get the point. 
And are human offals, brains etc now a thing? if yes, they should contain parasites only if host was infected, which game can already track.

**Comment by KorGgenT** [comment]
I have no issue with changing the parasite percentages to the same values as other offal, if that is what is being suggested here.

**Comment by OzoneH3** [comment]
It's actually easier to get parasites from cooked food since its
one_in() chance. So 1 out of 100 vs 1 out of 15 ...

**Comment by Leland** [comment]
Yup, this makes sense. We drop other cooked meats `parasites` to a 0 chance.

If anyone wants to grab, the line in question is here:

https://github.com/CleverRaven/Cataclysm-DDA/blob/22396d2494351e304a351f6345fe35c534ab9dcd/data/json/items/comestibles/carnivore.json#L370
