### ISSUE TITLE
aiming weapon freezes game

### ISSUE THREAD

**Issue by Finnalde** [CleverRaven/Cataclysm-DDA#27080]
pressing F to begin aiming at an enemy results in the game freezing, and locking PC until it is force-restarted. does not seem to occur with all weapons, but what weapons it has occurred with will lock my PC every time.
**To Reproduce**  
attempt to aim at enemy using a weapon. not all weapons have been tested as I quite like my PC not locking every 5 minutes.

**Expected behavior**  
game will get stuck trying to pull up the aiming screen, game will freeze up.

**Versions and configuration(please complete the following information):**
 - OS: Win7
 - 0.c-35045-gbd0f3e1
 - Tiles, Chesthole
 - Mods loaded:dark days ahead, disable NPC needs, filthy clothing, simplified nutrition, Extended Realistic Guns, Makeshift Items Mod, More Survival Tools, More Locations, Fujis More Buildings, Folding Parts Pack, Vehicle Additions Pack, Arcana and Magic Items, Necromancy, Classes and Scenarios Mod, Stats Through Skills

**Additional context**  
including save with the bow noted above in Character's hands.
[BuggyBowInHand.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2673839/BuggyBowInHand.zip)

**Comment by swofle** [comment]
This issue should be fixed in build 8268. Please update and feedback if the newer version works.

**Comment by Finnalde** [comment]
Just came here to update that it does indeed seem to work fine now.
