### ISSUE TITLE
Proportional Ammunition Pierce

### ISSUE THREAD

**Issue by darktoes** [CleverRaven/Cataclysm-DDA#27085]
**Is your feature request related to a problem? Please describe.**  
Part of my archery re-balancing/improvements requires that arrows have proportional damage and piercing values that multiply the existing damage value of the bow they are fired from, with the intent of making archery more practical and realistic.

As it stands, arrows and bows both have flat damage and pierce values. This is unrealistic and leads to inconsistent performance from different bows.
While Knightosmaster was nice enough to add a proportional damage value, I still need a proportional pierce value to make my changes.

**Describe the solution you'd like**  
Any and all "gun" items can have a pierce value applied to them in JSON. This represents the piercing value of a bow (or similar weapon) using a projectile with a terminal ballistic value of 1 (Or possibly 2, then non-bodkin arrows would reduce AP proportionally to bring them to appropriate levels. It depends on whether or not the base AP for the weakest bow is higher than 0).

A "prop_pierce" value would then be needed on the ammunition in use, which multiplies the base pierce value of the bow it's fired from to give a final pierce value based on the input energy from the bow, and the terminal ballistics of the arrow itself.

It's possible that I or others might make a mistake or simply not need to assign a pierce value to a weapon that might use proportional pierce ammo. If no pierce is assigned, the code would need to assume that the value is 0 and act appropriately.

In practice, the idea is that I can have a bow marked with a base pierce value of 8. Firing a normal arrow out of it would apply the base pierce value of 8. A bodkin arrow with a prop_pierce value of 2 would be fired with an applied pierce value of 16. A crude wooden arrow with a prop_pierce value of 0.75 would be fired with an applied pierce value of 6. (Values are examples and not actual values for anything)

**Describe alternatives you've considered**  
It's also possible that the appropriate pierce value could be drawn from the base damage of the weapon, then multiplied, but I feel that would make adding new content more difficult, requiring more math and messing about to get appropriate values.

I could also just ignore proportional pierce entirely, but that leads to the current issue with bows and arrows. Namely, that a weak bow with high-quality arrows does dis-proportionally high damage and pierce.

**Additional context**  
While I've mentioned primarily bows and arrows throughout this request, the same mechanic would obviously be applied to all similar weapons like crossbows, slingshots, and pneumatic weapons, which I also intend to take a stab at.

The recent proportional damage PR from Knightosmaster does something similar, so could be quite helpful for direction. https://github.com/CleverRaven/Cataclysm-DDA/pull/26705

The terminal ballistics and proportional damage values are drawn from Poragon's ranged weapon damage/pierce guideline which I've been working on applying to archery weapons. https://github.com/CleverRaven/Cataclysm-DDA/issues/26183

**Comment by SirPendrak** [comment]
Wouldnt this change be possibly beneficial for firearms rebalance at some point in the future? Right now, differences between ammo types for firearms are very low, and usually you dont even care which type you shoot, unless its 8x40mm HVP vs other 8mm. I am not en expert, but i believe results IRL are larger than ~10% more damage to armored targets with 9mm FMJ and ~10% better results with 9mm JHP to naked targets. 

But, after some thought, maybe priece, and how it works right now may be not enough. What about AP ammo ignoring a% of armor instead of flat ammount?

**Comment by darktoes** [comment]
Bullets don't really need to work this way unless there's a great deal of difference in muzzle velocity between muzzle lengths, and it's made possible for the player to heavily change the length of their gun's barrel. Other than that, bullets are fairly static in their damage and armor piercing capabilities. For the majority of cases they should be fine just having defined values, unless some sort of railgun accelerator gunmod is added.

Not sure about % armor reduction.

**Comment by Poragon** [comment]
Even if the bow overhual for some reason doesn't warrant adding this feature, several base game items would be able to be significantly more realistic and intuitive if this feature could be added. The current ranged weapon .json system was defiantly built with guns in mind, with the model of 'bullet has energy.' 

All the other ranged weapons for which the energy doesn't come from the ammo but the weapon (eg. pneumatic, bow/crossbow, sling, railguns) suffer from the fact that some values just were not made with them in mind. In this particular case of AP, the heavy rail rifle and rebar rifle are perfect examples.

Heavy Rail Rifle fires out a rebar rail with 100 UPS charges / 100kJ. This projectile will hit its target with 110 damage and 25 pierce.

Ferromagnetic Rail Rifle fires out the same rebar rail with 40 UPS charges / 40kJ. This projectile will hit its target with 70 damage and 25 pierce.

Immediately the pierce value comes into question. Despite the heavy rail rifle shooting with over twice the input energy, thus leading to the projectile travelling significantly faster, CDDA assumes in the case of pierce value the exact same situation. Assuming same efficiency between the guns, the means a 250% increase in projectile KE means nothing to the pierce stat in the current system.

**Comment by MetroidHunter** [comment]
I plan to start work on this today or tomorrow @darktoes
