### ISSUE TITLE
 Mod Inclusion Project: Medieval and Historic Content

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#27092]
Use the following issue as a space to discuss the inclusion of:

Mod Ident: Medieval_Stuff
Name: Medieval and Historic Content

Your comment should include:

### Suggestions for induction
(what parts of the mod should be included, can be as simple as just an item, a location or the complete inclusion)

### Incompatibilities
(what parts of the mod should not be included, either some objects / items or entire mod is conflicting with DDA theme [ for whatever reason ])

**Comment by Solusphere** [comment]
I vote that chainmail should be mainlined and autolearned. It's the kind of thing that while difficult to master, is pretty easy to conceive of and develop through practice, especially given that the average survivor will at the very least have seen it depicted in media.

**Comment by Nymall** [comment]
**Suggestions for induction**

Most everything in this mod plays rather nicely, save for the professions - though that could easily be incorperated into Crazy Cataclysm.

**Incompatibilities**

It's not really clear what weapon styles work with what weapons in this mod. Medevil Swordsmanship SHOULD work with most of the swords, but I've found it quite hit and miss. It may need a refactor or reclarification.

**Comment by Mooses2k** [comment]
I'm happy to take this one on, as I know something about the topic. I can migrate weapons in, make the martial art work for similar makeshift and lower quality items, and improve the technique descriptions. Are we intending to make this a mix of Italian, German, and Chinese medieval traditions? Easier version, should this art cover the swords and spears and such of both Europe and China?

We want these to only appear at museums and mansions or anywhere else?

**Comment by DracoGriffin** [comment]
> I'm happy to take this one on, as I know something about the topic. I can migrate weapons in, make the martial art work for similar makeshift and lower quality items, and improve the technique descriptions. Are we intending to make this a mix of Italian, German, and Chinese medieval traditions? Easier version, should this art cover the swords and spears and such of both Europe and China?
> 
> We want these to only appear at museums and mansions or anywhere else?

I'd think rarely in pawn shop types, slightly more frequent in museums, some in blacksmithing places (as more of proof/collections, not really because they are supplying an army [yet?]) and maybe very rarely in curio shops (the type you'd find in very large cities). Maybe even very rare Renaissance Faire/Festivals overmaps (don't think these exist yet), where you'd commonly the weak/fake variants with maybe a rare chance at finding an armored body surrounded by zombies.

**Comment by Mooses2k** [comment]
I kind of just want a nod to go ahead and move everything but classes, touch it up a bit, then turn this mod name into Medieval Classes Mod?

**Comment by kevingranade** [comment]
That's a reasonable plan.
Be aware this content was never seriously evaluated for balance, so it will likely require extensive rework as things are mainlined.
