### ISSUE TITLE
Pit firing for easier clay item production.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#27091]
**Is your feature request related to a problem? Please describe.**  
Initial requirements for firing clay items are too restrictive.  A stone kiln requires significant resources to construct.

**Describe the solution you'd like**  
Add a construction recipe similar to a kiln, but that requires only open ground, a digging tool and a fuel source.  This would create a single-use "pit kiln" that can be used in clay firing recipes.

**Describe alternatives you've considered**  
Additionally it would be nice to batch craft clay items, perhaps with unfired and fired versions of the items to separate the (labor intensive and per-item) process of shaping the item from the (unattended and batched) firing process, but the more immediate issue is the skill and material requirements of the existing kiln items.

**Additional context**  
Source outlining construction and use of a pit kiln: http://ballclaystudio.com/how-to-pit-fire-pottery-without-a-kiln/
Originated in #16333

**Comment by mlangsdorf** [comment]
Making the clay kiln and firing pit work like the smoking rack would be ideal.  Generalizing the smoking rack, fermenting vat, and furniture charcoal kiln code into one common set of routines that take a JSON defined list of input items, some conditions, and spits out some output items after time has passed would be good, too.

**Comment by kevingranade** [comment]
Yea that would be amazing, I'm just outlining the minimal fix.
