### ISSUE TITLE
Generator vehicle doesn't have a strong enough motor to power itself.

### ISSUE THREAD

**Issue by mekaerwin** [CleverRaven/Cataclysm-DDA#27103]
**Describe the bug**  
The premade Portable Generator in the game will not run with the motor size it has. As soon as you start the generator it immediately dies. If you remove the 7.5kW generator from the vehicle it runs fine.

**To Reproduce**  
1. Spawn a generator into the world.
2. Try to start it up.

**Expected behavior**  
The generator should run with the existing configuration.

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version [0.C-35130-ga9bd40d]
 - Graphics version [Tiles]
 - Mods loaded [None]

**Additional context**  
I'm not sure if the motor is too weak or the generator too strong or what really. I just can't run the generators that spawn in the game.

**Comment by Pupsi-Mupsi** [comment]
Thanks a lot for your bug report.
Replaced the engine and tested the upgraded one in game.
Should be fine now.

**Comment by mekaerwin** [comment]
Great!
