### ISSUE TITLE
Filter Mask does not show up in craftable items list despite meeting all requirements

### ISSUE THREAD

**Issue by paradigm369** [CleverRaven/Cataclysm-DDA#27115]
**Describe the bug**  
Filter Mask does not show up in craftable items list despite meeting all requirements

**To Reproduce**  
1. Load the attached saved file
2. Shift 2 to take note that characters skill levels exceed that required to build filter mask (tailoring 2 fabrication 1 required)
3. Go to crafting menu and attempt to look for Filter mask
4. Realise it is not there.

**Expected behavior**  
Filter Mask should be visible in crafting menu

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-35248-gf06dea5
 - Mods loaded [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

**Additional context**  
[Kahakuloa error save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2682645/Kahakuloa.error.save.zip)
.

**Comment by Crafty908** [comment]
The filter mask requires one of the following books to unlock.
A History of Firefighting (level 3)
Survival Under Atomic Attack (level 3)
Advanced Physical Chemistry (level 4)
chemistry textbook (level 4)
Guide to Advanced Emergency Care (level 3)
Art and Science of Chemical Warfare (level 3)
The levels refer to your tailoring reaches the level assigned to that book.

**Comment by paradigm369** [comment]
Okay thanks. So is not a bug
