### ISSUE TITLE
I've been getting lots of these "segmentation fault" crashes

### ISSUE THREAD

**Issue by lardf** [CleverRaven/Cataclysm-DDA#27114]
I don't know much about it but it's been annoying me a lot, here's a screenshot of the report.
![capture22222222222222](https://user-images.githubusercontent.com/45896810/50043051-26e20b80-0076-11e9-9728-9a8b84f3570a.PNG)

here's another segmentation fault thingy I got a little earlier than that one

![capturehelp](https://user-images.githubusercontent.com/45896810/50043063-4aa55180-0076-11e9-9dba-c8e7057fcb8f.PNG)

I haven't been getting these crashes before I updated to like 8280, that might have something to do with it.

EDIT: I've loaded my game up again after the crash, this is where I ended up.
![capturewth](https://user-images.githubusercontent.com/45896810/50043111-3f065a80-0077-11e9-8329-b1d3815a521a.PNG)

I was in an evac shelter before this, by the way.

**Comment by BrettDong** [comment]
Seems relevant to (or perhaps a duplicate of) #27060 .

**Comment by kevingranade** [comment]
No way to reproduce the issue and no usable telemetry from the backtrace.
