### ISSUE TITLE
Rain shouldn't make fire go out faster in a tile with an oven or a wood stove

### ISSUE THREAD

**Issue by RosaEscura** [CleverRaven/Cataclysm-DDA#27128]
**Describe the bug**  
Rain, lightning storm, thunder storm and acid rain weathers make fire go out faster even in tiles with ovens and wood stoves when compared to weathers not including rain. Drizzle or acidic drizzle also had no impact on the speed at which the fire went out.

**To Reproduce**  
1. Take an oven or a wood stove outside.
2. Debug one of the above rainy weathers in.
3. Load with fuel and set on fire.
4. Wait (eg 300 heartbeats)
5. Fire goes out before burning into wood ash

**Expected behavior**  
Rainy weathers are not supposed to affect burning inside a sealed place as it shouldn't in real life either.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-35256-gd9fd2f6
 - Graphics version: Tiles
 - Mods loaded: Only automatically recommended mods

**Additional context**  
I tested each rainy weather (drizzle, acidic drizzle, rain, lightning storm, thunder storm, acid rain) with both an oven (also the snowy weathers which didn't affect fire going out) and a wood stove outside. I used 3 logs for each test to prevent fire going out due to the lack of fuel. Default wait time was 300 heartbeats and that was long enough for the fire to go out during rainy weathers (apart from acid rain, which sometimes took a little longer). After rainy weathers there were 3 burnt logs and/or logs remaining. After drizzles or snowy weather all that remained was wood ash.

**Comment by Epictyphlosion** [comment]
Makes sense. After all, the rain would hit the stove and not the fire, because the fire is within the stove

**Comment by RosaEscura** [comment]
Already talked about this to Kevin too and he confirmed this shouldn't be happening. Would be very happy if someone would take the time to fix this at some point. : >

**Comment by wapcaplet** [comment]
I cannot reproduce this issue in 0.E-5926-g a883429bdd. With a regular kitchen stove outside in the rain, 1 log burned for about 3.5 hours.
