### ISSUE TITLE
missing coverage information 

### ISSUE THREAD

**Issue by Pupsi-Mupsi** [CleverRaven/Cataclysm-DDA#27126]
**Describe the bug**  

Well, this is not a bug report per se. Just a way to bring up a minor issue.
**Pair of ear plugs**, **earrings**, **collars** and such is missing any information considering coverage.
Should they be treated like the **shooter's earmuffs**?

**To Reproduce**  

1. Just take a look at the screenshots below.

**Expected behavior / Solution**  

Either we define a Zone for ears and one for neck or hide "Covers:" if empty or use head or....

**Screenshots**  

![grafik](https://user-images.githubusercontent.com/44737997/50057088-ee215f80-0165-11e9-9435-31331d33b0e3.png)

![grafik](https://user-images.githubusercontent.com/44737997/50056967-76066a00-0164-11e9-83fe-53cc44abd299.png)

![grafik](https://user-images.githubusercontent.com/44737997/50056988-af3eda00-0164-11e9-93f1-ce03d468588a.png)

![grafik](https://user-images.githubusercontent.com/44737997/50057056-9aaf1180-0165-11e9-9419-88a067260527.png)

![grafik](https://user-images.githubusercontent.com/44737997/50057062-a8fd2d80-0165-11e9-8fc5-6effb5f1cc47.png)

Or just use head:

![grafik](https://user-images.githubusercontent.com/44737997/50057083-e19d0700-0165-11e9-9ccb-5c95e246dae6.png)

![grafik](https://user-images.githubusercontent.com/44737997/50056963-65ee8a80-0164-11e9-868a-b5b2602ebd9f.png)

![grafik](https://user-images.githubusercontent.com/44737997/50057072-bdd9c100-0165-11e9-8897-2bcfb23f8668.png)

![grafik](https://user-images.githubusercontent.com/44737997/50057115-3476be80-0166-11e9-9211-01e0de459be5.png)

**Comment by kevingranade** [comment]
These seem totally reasonable to me for having no coverage. 
Two questions:
Do they contribute to warmth?
Do they have a chance of blocking attacks?

IMO the answer is no for both of yhese questions for all of these items.

**Comment by jbytheway** [comment]
I'll take a look at this.
