### ISSUE TITLE
Floor type under furniture often is wrong.

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#27139]
Floor under many furniture items in many locations do not correspond to floor around it. Take Mall for example. Many chairs, tables, arcade machines, potted plants have normal floor under them. But around them can be carpeting, linoleum, or someting else.
With tiles enabled it look really weird.

**Comment by kevingranade** [comment]
This needs to be more specific about which tiles dont match, otherwise its impossible to tell whether the issue is valid or not and whether it has been adressed.

**Comment by SomeDeadGuy** [comment]
In many buildings under furniture there is always normal floor. No matter what floor is around it.
I will post some screenshots later.

**Comment by AMurkin** [comment]
The most noticeable to me is a mix of reinforced concrete and concrete floor in labs.
And a regular floor in this case.
![image](https://user-images.githubusercontent.com/1931904/50077666-75221680-01fe-11e9-8807-f7d2a6ff6e03.png)

**Comment by SomeDeadGuy** [comment]
![frong floor](https://user-images.githubusercontent.com/37592026/50104676-b97fd780-023b-11e9-9219-1b62393dc683.PNG)
As you can see there every piece of furniture in the mall have "floor" under it, even if it should have been carpeting or linoleum.

**Comment by SomeDeadGuy** [comment]
Even all tables under them have wooden floor.
![frong floor tables](https://user-images.githubusercontent.com/37592026/50104943-622e3700-023c-11e9-9471-9e43053cb8a2.PNG)

**Comment by Leland** [comment]
There have been PRs opened to address these in the past. Going to be hard to know when this issue is "closed" without a definitive list, however.

**Comment by I-am-Erk** [comment]
This is really just due to a combination of limitations in how mapping is done, and perhaps a little sloppiness on the part of the mapper. Each piece of furniture on a different terrain type needs a different code. It's a ton of work.

It would be nice if there was a map terrain code to match adjacent terrain somehow. Or if maps supported layers (optionally so that we didn't have to rebuild all old maps)

**Comment by potjeh** [comment]
It's probably only relevant to the tiles version of the game. Let's take doors for example. Every door seems to be its own terrain type so it does not know on what type of floor it was constructed on. As mentioned above, if there was a separate layer for the floor, then maybe each door could (I guess with transparencies)  show up above the floor correctly and it would look nice. Same goes for furniture and basically everything else.

**Comment by sneeze-attack** [comment]
I will try and fix up the lab generation to make it more consistent. Afterwards I can try and do the same for the mall.

**Comment by curstwist** [comment]
I plan on surveying mall floors soon, so I'll take care of the mall then.
