### ISSUE TITLE
Cannot "dig downstairs" or "mine downstairs" (construction) with a filthy long rope

### ISSUE THREAD

**Issue by potjeh** [CleverRaven/Cataclysm-DDA#27138]
Constructing "dig downstair" or "mine downstair" will not accept a filthy long rope as a valid part. Not sure if intended to work like this, if yes... apologies.

1. Acquire all the necessary parts/tools for the construction recipe including only a filthy long rope (instead of a normal/clean one).
2. Try to construct the aforementioned recipe (dig/mine downstairs).

In an unexpected turn of events I had to dig an emergency passage to a few z-levels beneath me and long ropes were quite a commodity at the moment. A monster dropped a filthy long rope and my joy diminshed when I noticed that the game would not accept it as a valid construction part for digging/mining down. At that point I resorted to enabling the debug features to spawn a clean one which kind of puts a bit of a dampener on the mood (not to mention that maybe not all players will know or want to do it). The rope being filthy should not stop it from performing the same function as a clean one (at least in this context).

 - OS: Windows 7
 - Game Version: 0.C-35222-ge5a2860
 - Graphics version: tiles
 - Mods loaded: DDA, Disable NPC Needs, Filthy Clothing, Simplified Nutrition

**Comment by Night-Pryanik** [comment]
At the moment we forbid crafting and constructing with filthy components. This is a limitation and it will be changed in the future.
