### ISSUE TITLE
Battery charge indicator for foot pedal generator not updating

### ISSUE THREAD

**Issue by potjeh** [CleverRaven/Cataclysm-DDA#27140]
After a recent update the indicator no longer updates the charge status of an installed battery.

1. Make a vehicle with a foot pedal, motorcycle alternator and a small battery (saddle also).
2. Try to "ride" it to fill the charge of installed battery.
3. The UI indicator does not update.

The indicator was practical so you know when to stop pedalling without doing keypresses to examine the vehicle and see if the battery is full. I used such one tile foldable vehicles for charging batteries when travelling and now it's a bit of a bother getting down from the bike and examining it to see if the battery is full.

![2018-12-17_062137](https://user-images.githubusercontent.com/36718627/50068169-e80e9b80-01c4-11e9-9f6e-00be81869e41.png)

- OS: Windows 7
- Game Version: 0.C-35222-ge5a2860
- Graphics version: tiles
- Mods loaded: DDA, Disable NPC Needs, Filthy Clothing, Simplified Nutrition

**Comment by mlangsdorf** [comment]
Darn it.  Fix one bug, introduce another.

**Comment by potjeh** [comment]
One other thing... :) I see that you've changed the power values for the engines (the numbers are huge now)... the power requirements for the plow, seed drill, etc. are now a bit obsolete. When I checked the engines had a power value of about tens of tohusands and the plw still required 100 power.
