### ISSUE TITLE
Engine not starting, generator "Like New" no bad parts

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#27146]
**Describe the bug**  
I'm confused why the following happens on a "like new" gasoline generator
- The Generator's engine starts up
- The Generator's engine dies!

The vehicle is "like new" with no problem parts
vehicle has a full motorcycle and storage batter at 100%
No messages indicating that something is wrong
The vehicle started up normally in the summer time
This is the winter time, and I suspect cold weather, but I'm not clear on how to remedy this?
There is no vehicle engine block heater
I moved it indoors where the temp rose to 42F
Still same problem.

**To Reproduce**  
- Don't start small gas generator for six months (during summer/fall months)
- Fill with Gas
- Let temperature get down to 20F
- Try to turn on Generator, can't (I'm guessing?)

**Expected behavior**  
Someway to turn on a gas engine when it's cold?
Provide some info to the user to how to remedy the problem?

**Versions and configuration(please complete the following information):**
- OS: Mac 10.13
- Build: 589c772

**Additional context**  
I found this code:

else {
        if( engine_on && g->u.sees( global_pos3() ) &&
            has_engine_type_not( fuel_type_muscle, true ) ) {
            add_msg( _( "The %s's engine dies!" ), name );

I'm not sure what is happening here?  But, it would be nice to understand better the cold weather mechanics for engine starting. I've tried 50 times and no starting of the engine.

**Comment by woutershep** [comment]
I think this was recently fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/27105 your version appears older.

**Comment by Epictyphlosion** [comment]
Jeez, that generator is really buggy!

**Comment by hmstanley** [comment]
ok, I debugged this some more.. based on @woutershep comments.  You need at least a two-cylinder engine to run the Generator.. sadly, the one in the wasteland that comes "pre-built" is NOT 2-cylinder, it's one.  So, I think either fix the blue-print so people don't go crazy trying to figure out why a perfectly good "green" generator doesn't run, or remove it.. I guess.
