### ISSUE TITLE
Survivor utility belt and firearm repair kit missing quality

### ISSUE THREAD

**Issue by ImmemorConsultrixContrarie** [CleverRaven/Cataclysm-DDA#27151]
**Describe the bug**
Surv. ut. belt miss "1 tree cutting" quality, as toolbox in #27071 
Since #27069 hacksaw got "1 wood sawing" quality. But you can craft firearm rep. kit with hacksaw and f. r. kit should get this quality.
FulcrumA, just check recipes, when you change item quality. In most cases item crafted from a tool with a quality, could be disassembled. That's strange, when you can get a thing back from toolbox, but can't use it while it's in. However, if it can't be disassembled or it's dis. time is more than 5 min, there will be no questions about the lost quality.

**Versions and configuration(please complete the following information):**
OS: Windows 7
Game Version: 0.C-35105-g3de7663
Graphics version: Tiles
Mods loaded: dda

**Comment by Pupsi-Mupsi** [comment]
Thanks a lot for your bug report!

**Comment by Pupsi-Mupsi** [comment]
#27168 -> Add AXE quality to survivor utility belt.
and
#27171 -> Add wood sawing quality to firearm repair kit.

Sorry, but this fix ist incomplete. I really dont mean to be rude or something...
