### ISSUE TITLE
NPC slows down game

### ISSUE THREAD

**Issue by ZemZamano** [CleverRaven/Cataclysm-DDA#27159]
**Describe the bug**  
Ever since an NPC spawned near my base, the game slowed to a crawl

**To Reproduce**  
Load my attached save file.

**Expected behavior**  
game runs normal when NPCs are around

Savegame location:
https://uploadfiles.io/gsdt2

**Comment by ZemZamano** [comment]
forgot to post my mods:
[
  "dda",
  "no_npc_food",
  "filthy_morale",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "DinoMod",
  "mutant_npcs",
  "blazemod",
  "DP_AMAZING_CHEST_INDICATORS",
  "StatsThroughSkills"
]

**Comment by Mooses2k** [comment]
I would assume there's other issues about this, but me too. I had four NPCs traveling in an RV with me until I gave up due to crafting times being slow slowed down. Huge performance hit.

**Comment by ZhilkinSerg** [comment]
Savegame is unavailable now.

**Comment by ZemZamano** [comment]
i still had a copy of the savegame
Here is the reupload:
https://ufile.io/rv7syqke

**Comment by ZhilkinSerg** [comment]
Can you upload save once again?

**Comment by Aivean** [comment]
Should be fixed, see #45497
