### ISSUE TITLE
Loot pile "moved" after saving and reloading.

### ISSUE THREAD

**Issue by AndrXi** [CleverRaven/Cataclysm-DDA#27157]
**Describe the bug**  
Loot that I sorted manually gets placed somewhere else in a nearby area after saving and reloading or quitting to menu through debug.![bug report 1](https://user-images.githubusercontent.com/44873249/50152403-677e9680-02bb-11e9-996c-367c5d892308.png)(The "unsorted" loot)

**To Reproduce**  
I don't know how this came to be ,but after I updated from build 8302 to 8308 (using the CDDA Launcher) this started happening.

**Expected behavior**  
The loot I sorted to remain in its place.

**Versions and configuration(please complete the following information):**
 - OS: Win 7
 - Game Version: 0.C-35312-gf9ef7e2 (tiles).
 - Mods loaded 
["dda", "filthy_morale","ew_pack","makeshift","Medieval_Stuff","More_Survival_Tools", "modular_turrets","Salvaged_Robots","alt_map_key","Mining_Mod","mutant_npcs","npc_traits","zets_hair_extensions","more_locations","zets_hair_ext_more_locations","FujiStruct","boats","deoxymod","blazemod",
  "Tanks","Arcana","DP_REMIX_INDICATORS","StatsThroughSkills","PK_REBALANCE", "zets_hair_ext_pk_rebalance"]

**Additional context**  
This happened consistently through repetition but apparently I managed to revert back to the way I sorted my loot.

**Steps taken to revert it back:**
1-Save and quit **WITHOUT MOVING** to confirm "unsorted" loot
![bug report 1](https://user-images.githubusercontent.com/44873249/50152403-677e9680-02bb-11e9-996c-367c5d892308.png)

2-Move 1 tile in any direction , save and quit.
3-Reload the game , loot shows up where it was meant to be.
![bug report 2](https://user-images.githubusercontent.com/44873249/50152542-c47a4c80-02bb-11e9-9849-cb74ceafdcd1.png)

(When I say sorted , I don't mean using the Loot:Sort Menu)

However after it's "fixed" this way when I continue playing and save, the loot gets unsorted again , forcing me to take the steps above to fix it.

**Comment by Arcade22** [comment]
I'm also using 8308 and items end up moving around, both things that i placed myself and those that i haven't touched. For example in a FEMA camp antibiotics and glass flask ended up in the walls of the lab instead of being placed inside.

**Comment by AndrXi** [comment]
Well , I guess it's reassuring to know this issue isn't mine only.
But yes , I also experienced what Arcade22 has.

**Comment by Arcade22** [comment]
Also it happens after you save. A good way to reproduce this bug is to somewhere where there are lots of items scattered about, walk away so its outside of the "reality bubble", save and then walk back.

**Comment by Zireael07** [comment]
Fix open at #27155
