### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#27163]
I get this about 3 times 
![image](https://user-images.githubusercontent.com/44106380/50161188-0801a480-0316-11e9-87a5-8587e3913524.png)

Can someone explain and how to prevent this in the future?

**Comment by BBlankie** [comment]
I came back and some of the items gone missing or went into the walls.

**Comment by AMurkin** [comment]
> some of the items gone missing or went into the walls.

Fix for this is #27155.

**Comment by BBlankie** [comment]
Reverted my game. anyways i got another segfault after walking about 5 tiles
![image](https://user-images.githubusercontent.com/44106380/50162486-785df500-0319-11e9-8000-1209aa089606.png)

**Comment by Inglonias** [comment]
Posting a save file where this happens would be ideal.

**Comment by MegaGlub** [comment]
I have a save file where this happens. I'm playing with the following mods: [
  "dda",
  "no_npc_food",
  "filthy_morale",
  "safeautodoc",
  "StatsThroughSkills",
  "craftgp",
  "FIC_Weapons",
  "More_Survival_Tools",
  "realguns",
  "makeshift",
  "alt_map_key",
  "more_locations",
  "FujiStruct"
]

Starting here:
![capture](https://user-images.githubusercontent.com/45982508/50189688-898c0f00-02e3-11e9-9057-88a987f7e7b4.PNG)

and my save can be found here:
(sorry for using google, but i didn't care to find another stable site)
https://drive.google.com/drive/folders/1l2V8ko_moQeqbO-7-DhQtREaxd1hjiEk?usp=sharing

**Comment by MegaGlub** [comment]
Is fixed for me on the most recent version (#8313) so this issue can probably be closed if no one else is having trouble

**Comment by ZhilkinSerg** [comment]
Closed by #27155. Please comment if bug is still actual in recent version.
