### ISSUE TITLE
Terrifying tweek

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#27160]
I would like a feature that the Terrifying trait can be nullified by large-coverage face masks or can be toggled, too many npcs i encountered get scared before i even have the chance to talk to them.

**Comment by curstwist** [comment]
I like the idea of having masks/clothing impact NPC opinions, for good or bad.

**Comment by mlangsdorf** [comment]
The Terrifying trait is supposed to scare NPCs.  That's what it's for.

**Comment by nexusmrsep** [comment]
> I like the idea of having masks/clothing impact NPC opinions, for good or bad.

At the cost of complete distrust of said NPC.

**Comment by GearheadLydia** [comment]
> I like the idea of having masks/clothing impact NPC opinions, for good or bad.

We get a little of this with the FANCY clothing tag, but that's about it.

**Comment by kwl01skz** [comment]
If so, I hope I can make a demon mask
