### ISSUE TITLE
Map Extras on higher Z levels

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#27176]
**Describe the bug**  
Got an map extra on floor 2 of a megastore, had a mi-go I couldn't take care of due to the inability to aim on higher Z levels, so constant speech interrupting crafting when it was a temporary base.

**To Reproduce**  
1:start game with Z levels and mods that add Z level buildings
2:have the bad luck of map extra appearing on these higher floors at an inaccessible point
3:have noises constantly interrupt tasks from a mi-go

**Expected behavior**  
This does not happen, or map extras are limited to never appearing on open air, have ability to aim ranged weapon on higher Z levels.

**Versions and configuration(please complete the following information):**
Windows 8.1, latest build compiled with visual studio 2017
Relevant mods: all vanilla buildings mods except urban development, PK rebalancing (my fork)

Please let me know if this may somehow be PK rebalancing's fault and there's a way I can fiddle with overmap settings to prevent this from happening.
I've heard of it happening with lava in the past.

**Comment by ZhilkinSerg** [comment]
For clarity: things that spawn migos are called "map extras", not "overmap specials".
