### ISSUE TITLE
Autofire accuracy too low

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#27182]
**Describe the bug**  
1) Realsticaly shooter can control autofire recoil to cetain degree and able to mainatin target more or less. Game in other hand uses logic- more you shoot- less accurate you become. But IRL shooter can mantain aim while autofiring:
https://youtu.be/kqRNe_qTx7Y?t=908

2) Autofire penalty too hight. After 3-5 shots player start shooting at 45 degree cone. It may be true for completelyy inexpirienced player, but even vehicle mounted turrets do that.

It is competely unrealistic. Yes it is expected that  player lose accuracy while autofiring. But not THAT much.

**To Reproduce**  
Create average player with rifles skills 5:
1. Create average player with rifles skills 5 and arm him with any rifle.
2. Try autofire at any target.

**Expected behavior**  
Player able to hit after 5 shots spontaneously and still able to at least mainaint direction of firing.

**Actual behavior**  
Player starts srpaying wildly in 45 degree cone after 5 shots converting following shots in wasted ammo.

**Additional context**  
After looking to autofire code I've found this:
Cataclysm-DDA\src\ranged.cpp

```
// Temporarily scale by 5x as we adjust MAX_RECOIL.
 recoil += 5.0 * ( qty * ( 1.0 - absorb ) );
```

So we set 5x recoil because we adjusting MAX_RECOIL? But it is constant. And we do not adjust it later. This comment and 5.0 magic number make zero sense.
It looks like oversight.

**Comment by Firestorm01X2** [comment]
Now I have serous doublt that:
```
// Temporarily scale by 5x as we adjust MAX_RECOIL.
 recoil += 5.0 * ( qty * ( 1.0 - absorb ) );
```

is forgottent temporary code that makes recoil 5 times higher. Comment almost literraly says that.

**Comment by Firestorm01X2** [comment]
>you're normally seeing recoil reduction in the 25% range (5 skill), which seems like too little.

Agree. It is good way to at least make current autofire maangeable.

@kevingranade 
How do you think?

**Comment by Firestorm01X2** [comment]
Also:
https://github.com/CleverRaven/Cataclysm-DDA/commit/cfefcbebf2f92193d47caf9facb1317a4f73f7f3#diff-c5873ed460ae46963dac594829494e52

This 5X recoil in fact part of Kevin's old rebalance.

**Comment by kevingranade** [comment]
> It seems like the issue is that there isn't any opportunity for a (skill-based) attempt to re-center aim between shots.

That's not how burst fire works, you do not have time to re-aim while firing, recoil suppression is just exerting force that opposes the force you expect the recoil to produce.  It's a practised motion, not a reactive one.

> I need details.

No, you don't, you need to do some research and figure out how much deflection we can really expect from guns, figure out some maximums and minimums, propose those bounds, add them to the tests, and make the tests pass, exactly like https://github.com/CleverRaven/Cataclysm-DDA/pull/23720

OR

You can drop it and wait for someone else to do it.

**Comment by chaisawlajatang** [comment]
I'm agree that something have to be done with current auto-fire. The machineguns fire on the wide cone, regardless of one's strength or skills, even if the gun is mounted. There could and should be some recoil and loss of accuracy, but for now it looks like shooting in Rambo-style.

**Comment by Firestorm01X2** [comment]
>I need details.
>No, you don't,

Oh no, I am insulted.
