### ISSUE TITLE
MOUSE-LOOK (Edge-scrolling & screen move with special mouse or keyboard button)

### ISSUE THREAD

**Issue by Ixella** [CleverRaven/Cataclysm-DDA#27180]
Why not implement mouse-look by pressing right button in the game? It would be much more convenient than using a list of mobs or scrolling map with arrow keys. Moreover if you do this as an option, those who prefer to use the standard controls will not suffer.

**Comment by NotFuji** [comment]
Mouse look is already implemented, you can hover over any tile to see what is there (might be tiles version only, not sure).  You can even move by right clicking with automatic pathfinding around obstacles.

**Comment by Ixella** [comment]
> 
> 
> Mouse look is already implemented, you can hover over any tile to see what is there (might be tiles version only, not sure). You can even move by right clicking with automatic pathfinding around obstacles.

I meant following the field of view behind the cursor, as is done in many RTS

**Comment by BBlankie** [comment]
Press x to look around.

**Comment by Ixella** [comment]
> Press x to look around.

Screen is NOT following to the mouse cursor. It can be moved only with the keys of the keyboard

**Comment by Ixella** [comment]
![default](https://user-images.githubusercontent.com/45998544/50231956-f88b6580-03c0-11e9-96dd-b2bee02d5dc6.png)

**Comment by BBlankie** [comment]
we don’t have that kind of feature yet as i remember, and this game is for keyboard junkies just like old fashioned roguelikes like nethack

**Comment by Ixella** [comment]
> 
> 
>this game is for keyboard junkies just like old fashioned roguelikes like nethack

Ok, but if you add this feature as an option, "keyboard junkies" will play as they want

**Comment by BBlankie** [comment]
i'm just a person, ask a dev or something but i don't think we need another mouse interaction, spend your time fiddling your keyboard and eventually you can play the game easily.

**Comment by Ixella** [comment]
> 
> 
> i'm just a person, ask a dev or something but i don't think we need another mouse interaction, spend your time fiddling your keyboard and eventually you can play the game easily.

This is just a feature that is very easy to implement, but which will greatly increase the comfort of the game

**Comment by Ixella** [comment]
Edge-scrolling is of course good, but it would be better to also make the screen move while holding down the right mouse (or any other by the choice of the developer) button. It is much more comfortable

**Comment by Ixella** [comment]
For example this feature realized in heroes 5 by the pressing middle button
