### ISSUE TITLE
 broadsword  couldn't be detected when craft blade

### ISSUE THREAD

**Issue by gearforcer** [CleverRaven/Cataclysm-DDA#27181]
**Describe the bug**  
I have a  broadsword in my inventory already,  but it shows lacking of materials.
**Screenshots**  
![t](https://user-images.githubusercontent.com/42244110/50238735-2b524f80-03fb-11e9-8097-d511f960046d.png)
![i](https://user-images.githubusercontent.com/42244110/50238754-36a57b00-03fb-11e9-9920-59ef39e9a62c.png)

**Versions and configuration(please complete the following information):**
 - OS:  Windows 10 64bit
 - Game Version 0.C-35330-g1fe4fbf (tiles)
![mod](https://user-images.githubusercontent.com/42244110/50238792-4755f100-03fb-11e9-9f3b-178616cd3fcd.png)

**Comment by NotFuji** [comment]
What material is the broadsword?  There are three different types.

**Comment by gearforcer** [comment]
>           What material is the broadsword?  There are three different types.
Oh, I got it. My broadsword is made by aluminum, that's why I'm feeling so confused when I search Item Browser seeing that blade is made by steel.
