### ISSUE TITLE
red arrow (refugee center) is not appearing

### ISSUE THREAD

**Issue by nsklaus** [CleverRaven/Cataclysm-DDA#27183]
**Describe the bug**  
starting a new game, after using the terminal, i open map and there is no red arrow pointing to refugee center.

**To Reproduce**  
1. create world, with the following mods: 
  "dda", "no_npc_food", "filthy_morale", "novitamins", "no_rivtech_guns", "no_scifi", "Mundane_Zombies", "no_reviving_zombies"

2. create a new game (custom character) 
points: single pool,
scenario: evacuee
profession: survivor
no traits,
no skill,
stats: strength 10, dexterity 10,  intelligence 10, perception 10 

3. start game, go to terminal, read the messages, close terminal, open map: no red arrow, no refugee center.

**Expected behavior**  
after opening terminal, and then looking at the map, red arrow and refugee center should show up

**Screenshots**  
https://i.imgur.com/Jpu4FI4.png

**Versions and configuration(please complete the following information):**
- OS: kubuntu 18.10 (kernel 4.20rc7)
 - Game Version : 0.C-35313-g59564c6309-dirty
 - Graphics version Tiles
 - Mods loaded [ "dda", "no_npc_food", "filthy_morale", "novitamins", "no_rivtech_guns", "no_scifi", "Mundane_Zombies", "no_reviving_zombies" ]

**Additional context**  
this forum talk looks similar to what i'm seeing:
https://discourse.cataclysmdda.org/t/classic-zombies-and-no-refugee-center/14995/6
link to a savegame : https://ufile.io/t3d3k
also, i tried to manually remove all extra mods, i returned to the terminal from the beginning, but it did not help.

update:
---------
i tried to create a new game, without any mods. i just selected "custom character", i changed monster speed to 30%  resilience to 40% and hunger&thirst 30%, same character creation as above. and i got the same problem. without any mods. no red arrow, no refugee center.
note that if i do a "play now fixed scenario" instead, everything works fine.

**Comment by ZhilkinSerg** [comment]
Probably related to `CLASSIC_ZOMBIES` and lack of `CLASSIC` flag on `evac_center` overmap special.

**Comment by nsklaus** [comment]
> Probably related to `CLASSIC_ZOMBIES` and lack of `CLASSIC` flag on `evac_center` overmap special.

as i said in the end of original post, and after in the update: 
i tried to remove all mods and go back to the term, it didn't help.
i tried also to create a complete new game *without any mods* it didn't help.
if i use a custom character as defined in the update then: no arrow, no refugee center.

**Comment by ZhilkinSerg** [comment]
Classic zombies is world option, not a mod.

**Comment by nsklaus** [comment]
> Classic zombies is world option, not a mod.

yes, i should have expressed this more precisely: that too have been deactivated (set to false)
