### ISSUE TITLE
messenger bag type bags and backpacks take up the same slot

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#27188]
So irl many days I go for groceries with a messenger bag and a backpack, they do not rely on the same parts of my body and offer no comfort issues as a result of the combination.

So it seems silly that Cataclysm thinks I wear any sling type bag like a backpack.

Solution would be creating a seperate layer for this type of bag.

It's not really a bug so much as something that doesn't make sense to me as someone that regularly uses bags in this combination irl.

An idea for this layer is it takes a side, but heavily increases encumbrance if one has a pack on both sides.
I suppose it somewhat decreases leg mobility on one leg more than anything 

This type of layer would interfer with comfortably wearing a sheath or scabbard on the leg.

**Comment by kevingranade** [comment]
Just like with #27059 , it would be fine to add code to represent non-overlapping coverage to represent this kind of thing, but we are not adding ad-hoc layers to accomplish it, as that would be hugely disruptive.
