### ISSUE TITLE
Segmentation fault with bike rack

### ISSUE THREAD

**Issue by hitmancho** [CleverRaven/Cataclysm-DDA#27193]
After updating above 8313 whenever I try to detach my Blob Bike from my car (with 3 bike racks for the 3-tile bike) I get the attached log:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2699231/crash.log)

I have the following mods:
[
  "dda",
  "Tolerate_This",
  "SD_Magcrafting",
  "craftgp",
  "FIC_Weapons",
  "realguns",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "alt_map_key",
  "zets_hair_extensions",
  "zets_hair_ext_more_locations",
  "zets_hair_ext_pk_rebalance",
  "Mining_Mod",
  "mutant_npcs",
  "npc_traits",
  "national_guard_camp",
  "BIGRIVER",
  "more_locations",
  "FujiStruct",
  "more_buildings",
  "cityside",
  "oa_additional_buildings_mod",
  "Experimental-Z-Level",
  "Urban_Development",
  "boats",
  "deoxymod",
  "ext",
  "SEEDYSPOT",
  "WEIRDWORLD",
  "Arcana",
  "PK_REBALANCE",
  "blazemod",
  "winning_dda",
  "more_classes_scenarios",
  "RL_Classes",
  "filthy_morale",
  "no_reviving_zombies",
  "speedydex",
  "StatsThroughSkills",
  "Tanks"
]

**Comment by ZhilkinSerg** [comment]
Can you provide savegame?

**Comment by hitmancho** [comment]
It's a 360+ MB file that i .7z-d: https://we.tl/t-a4uOqiYgnL

**Comment by ZhilkinSerg** [comment]
Thanks. I can confirm there is a reproducible crash:

![image](https://user-images.githubusercontent.com/16213433/50312458-716de880-04b9-11e9-8f26-ae0456b57e84.png)

**Comment by hitmancho** [comment]
Just a heads up - disassembling the bike while it's "on" the car and then reassembling it again made it work without a hitch. I can attach and detach it from the car no problem. But I guess some vehicle commit broke it during that period. I can just fold it but it's very heavy to lug around.

**Comment by kevingranade** [comment]
So there might be something still here, but with the only person reporting the issue successfully applying a workaround I'm not going to add it to the release blockers.

**Comment by ZhilkinSerg** [comment]
Closed in favor of duplicate #28712 (more info there).
