### ISSUE TITLE
Power output from perpetual reactors does not appear on vehicle screen

### ISSUE THREAD

**Issue by anothersimulacrum** [CleverRaven/Cataclysm-DDA#27200]
**Describe the bug**  
When you install a perpetual reactor (such as the vortex generator) on a vehicle, the power output from that reactor is not shown in the in the batteries section. 

**To Reproduce**  
1. Spawn or create a vehicle.
2. Install a vortex generator, battery, dashboard, and headlight into said vehicle (if it does not have those already).
3. Turn on vortex generator.
4. Wait a few turns.
5. Turn on headlight.
6. See that the "Batteries" section in the vehicle menu shows a net negative gain, but the battery is gaining charge.

**Expected behavior**  
The batteries menu shows the power output from the vortex generator. 

**Screenshots**  
Before the reactor is turned on:
![Before Reactor is turned on](https://i.imgur.com/dcqwB6P.png)
With the reactor turned on:
![Reactor on, no floodlight](https://i.imgur.com/BdNzswb.png)
With both the reactor and floodlight turned on:
![Reactor on, floodlight on](https://i.imgur.com/OmEcfjM.png)

**Save**
[PerpetualReactors.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2700531/PerpetualReactors.zip)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-35368-gc2a9362 (build 8318)
 - Graphics version: Tiles 
 - Mods loaded: [ "dda",  "blazemod" ]

**Additional context**  
Probably oversight from when the output display was introduced in #27173

**Comment by mlangsdorf** [comment]
Reactor power is never shown on that screen because it overwhelms your actual power consumption/generation by a factor of 6x or more.

**Comment by anothersimulacrum** [comment]
Could it be displayed in the reactors section at least, just so it is displayed somewhere, or explained somewhere that it is not displayed on the vehicle screen?
