### ISSUE TITLE
Autofire accuracy too low and  recoil is unrealistic

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#27214]
**Describe the bug**  
1) Realsticaly shooter can control autofire recoil to cetain degree and able to mainatin target more or less. Game in other hand uses logic- more you shoot- less accurate you become. But IRL shooter can mantain aim while autofiring:
https://youtu.be/kqRNe_qTx7Y?t=908

2) Autofire penalty too hight. After 3-5 shots player start shooting at 45 degree cone. It may be true for completelyy inexpirienced player, but even vehicle mounted turrets do that.

It is competely unrealistic. Yes it is expected that  player lose accuracy while autofiring. But not THAT much.

**To Reproduce**  
Create average player with rifles skills 5:
1. Create average player with rifles skills 5 and arm him with any rifle.
2. Try autofire at any target.

**Expected behavior**  
Player able to hit after 5 shots spontaneously and still able to at least mainaint direction of firing.

**Actual behavior**  
Player starts srpaying wildly in 45 degree cone after 5 shots converting following shots in wasted ammo.

**Additional context**  
Look for recoil calculation here:
Cataclysm-DDA\src\ranged.cpp

`int player::fire_gun( const tripoint &target, int shots, item &gun )`

```
int qty = gun.gun_recoil( *this, bipod );
delay  += qty * absorb;
// Temporarily scale by 5x as we adjust MAX_RECOIL.
recoil += 5.0 * ( qty * ( 1.0 - absorb ) );
```

1) https://en.wikipedia.org/wiki/Shot_grouping
2) https://nationalinterest.org/blog/the-buzz/the-us-marines-explained-us-when-fully-automatic-fire-23304
>From 5, 30, and 80 meters, Wade and Cpl. Gerald Trado, an infantryman with 3rd Battalion, 6th Marines, take turns sending rounds down range in semi-automatic and fully automatic. In terms of accuracy, the results are mixed.
>While shooting on automatic at the closest distance, the vast majority of rounds fired hit right on target, but as the Marines move further away, their shot placements start to veer off. By the time they’re at 80 meters, just the first two or three rounds are landing center mass, with the remainder trailing up and to the left.

3) http://www.thedrive.com/the-war-zone/20632/leaked-report-points-to-accuracy-reliability-issues-with-the-marine-corps-newest-rifles
>The KAC suppressor, on the other hand, was more user-friendly, but threw off the aim – “point of impact,” or POI – of the weapon by an average of nearly two and half minutes of angle. When it comes to firearms, this unit of measurement, abbreviated MOA, is best understood as a cone with a circle at its base that grows one inch in diameter for every 100 yards. A weapon with a stated accuracy of approximately one MOA can reliably hit within a one-inch diameter circle at 100 yards and an 8-inch diameter one at 800 yards.
4) https://www.military.com/join-armed-forces/army-weapons-qualification-course.html
5) https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/138220/JSP403_Vol2_Chap02_DLRSC.pdf
6) https://www.globalsecurity.org/military/library/policy/army/fm/3-22-9/c07.htm
>A soldier well trained in aimed quick fire can hit an E-type silhouette target at 25 meters, with the shot or burst striking 5 inches from the center of mass. This variance of target hit for this type of engagement reinforces the need for well-aimed shots.
7) https://www.usar.army.mil/Portals/98/Documents/Marksmanship/PMI_M16-M4_TC3-22.9.pdf?ver=2018-11-07-044300-937

8) Probably good book for probability theory of automatic fire:
https://www.twirpx.com/file/1622665/
Uploaded here: 
https://drive.google.com/open?id=13vYxZk96sSFziiGfUc-rW5lnCKrgXNiA

Шерешевский М.С., Гонтарев А.Н., Минаев Ю.В. Эффективность стрельбы из автоматического оружия. 1979

Look for page 127 and around it. Yes it is Russian langunage.
9) But if you have low skill or have not enough Strenght attribute you shoot like this:  https://youtu.be/rg3pkSPkKp0?t=33

**Comment by Firestorm01X2** [comment]
Issue still actual and must stay.

**Comment by Zireael07** [comment]
Kevin, why did you close this with no discussion?

**Comment by AMurkin** [comment]
Previous insulted version: #27182

**Comment by Zireael07** [comment]
Regardless of whether someone overreacted, the guy is right that the issue exists.

**Comment by Firestorm01X2** [comment]
>Previous insulted version: #27182

Sorry but I didn't isulted him. And never tryied in the first place. It was usual miunderstaning. 

But after that... I think we lost Kevin's here. What is he doing  now completely inadequate.

I guess he is going to eplain himself somehow. He definetely should.

**Comment by kevingranade** [comment]
> why did you close this with no discussion?
There was a discussion, but @Firestorm01X2 decided it was more important to continue to be rude than to have it, so I'm not engaging with him on it.

As for the content, it's not an issue, it's an opinion.  An issue requires a description of what the expected outcome is, and "better than it is now" is not a valid expected outcome.  I as usual asked for clarification, and posting a pile of sources with no analysis, while helpful, is insufficient to make it a valid issue.

**Comment by Firestorm01X2** [comment]
>As for the content, it's not an issue, it's an opinion. An issue requires a description of what the expected outcome is, and "better than it is now" is not a valid expected outcome. I as usual asked for clarification, and posting a pile of sources with no analysis, while helpful, is insufficient to make it a valid issue.

Ok. At least something.

> An issue requires a description of what the expected outcome is, and "better than it is now" is not a valid expected outcome

I've bring it.

I've even bring video. I mean- look at it. Shooter dont lost acuracy on autofiring that much as it is ingame now.

**Comment by Firestorm01X2** [comment]
@kevingranade 
>I'm not engaging with him on it.

Ok. Please answer straight, You are not doing this completely? It it is the case then it will lead to all my following PR's being closed. Maybe you should ban me instead? Because it is in fact may lead to unoffical way to end all my contributions.

And take note I am asking as polite as I could now.

**Comment by mlangsdorf** [comment]
You need to specify what the desired outcome is.  "Recoil effects shooters less" is not specific.

"Player with Strength 10, SMGs 5, and an Uzi should be able to aim precisely and then fire a burst at a zombie at 10 tiles and expect to hit with 8 out of 10 shots" is specific, but you'd want a bunch of items like that describing the expected effects of recoil.
