### ISSUE TITLE
Toolbox butchering quality missmatch

### ISSUE THREAD

**Issue by AndrXi** [CleverRaven/Cataclysm-DDA#27220]
**Describe the bug**  
Toolbox recipe asks for a steak knife, pocket knife, switchblade and stone knife (also makeshift knife if you have the mod), but doesn't take on the butcheing quality for the specified knife.
Toolbox has 12 butchering quality no matter what knife was used.

**To Reproduce**  
1. Create any character that can craft the toolbox.
2. Try crafting it with every possible knife variant.

**Expected behavior**  
Toolbox recipe to take on the quality of the used knife.

**Versions and configuration(please complete the following information):**
 - OS: Win 7
 - Game Version : 0.C-35416-gda33751 (tiles)
 - Mods loaded : "dda", "makeshift"

**Possible Solution**  
Have the steak knife removed from the recipe and have it use the other knifes (since they share 11 butchering quality if I remember correctly , toolbox would need to be changed aswell).

**Comment by TheMurderUnicorn** [comment]
Pocket knife, stone knife, makeshift knife = 11, switchblade = 14, steak knife = 20.  You would have to remove both the switchblade and the steak knife to do what you're proposing.  Figured I'd point that out.  

Both stone and makeshift knives are easily accessible so I don't think removing switchblade and steak knife would be all that inconveniencing to the average player.

**Comment by Pupsi-Mupsi** [comment]
Thanks to both of you.
I hope this is the way you would have done it.
#27244
