### ISSUE TITLE
Issue with sounds: no sound description

### ISSUE THREAD

**Issue by paradigm369** [CleverRaven/Cataclysm-DDA#27234]
**Describe the bug**  
No sound description for playing bone flute (other sounds may be affected too)

 DEBUG    : Sound at 64:68 has no description!
 
 FUNCTION : void sounds::sound(const tripoint&, int, sounds::sound_t, std::__cxx11::string, bool, const string&, const string&)
 FILE     : src/sounds.cpp
 LINE     : 100

**To Reproduce**  
1. load attached savegame
2. Pass some time with bone flute activated
3. Error message appears

**Expected behavior**  
There should be a description along the lines of "Your bone flute wails for the fallen"

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-35441-ga7f35af

**Additional context**  
savegame:
[Kahakuloa error save 2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2704846/Kahakuloa.error.save.2.zip)
Debug Log:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2704830/debug.log)

**Comment by paradigm369** [comment]
Hello,

Have downloaded latest experimental build 8329. The error message no longer pops up but is still not a complete fix because the sound description is still missing.

By right there should be a message while the bone flute is playing that says "Your bone flute wails for the fallen"

**Comment by mlangsdorf** [comment]
Still working on it.

**Comment by Night-Pryanik** [comment]
Also shouting now causes the same debug message.

**Comment by mlangsdorf** [comment]
Still not fixed.
