### ISSUE TITLE
When driving at low speed sometimes move two squares at once

### ISSUE THREAD

**Issue by SeelenJaegerTee** [CleverRaven/Cataclysm-DDA#27238]
**Describe the bug**  
When driving at 8 km/h (lowest speed)  the car moves two squares instead of one every fourth movement. (1, 1, 1, 2, 1, 1, 1, 2 squares).

This behaviour makes precision maneuvering really difficult.

**To Reproduce**  
1. Create new world. Create character with max in all stats and max driving skill (to ensure it is not because of poor attributes or skill)
2. Open debug mode, spawn car, get in.
3. Start driving at lowest speed.
4. Observe "skipping" of tiles.

**Expected behavior**  
A couple of versions earlier the lowest speed was 16 km/h (or perhaps 18 I don't really remember) and the car would only move one tile per tick at lowest speed.
Now that minimal speed is half as high I would not expect to move two squares at once.

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu
 - Game Version: 0.V-35451-ge0588e5098
 - Graphics version: Tiles
 - Mods loaded: none

**Comment by Zireael07** [comment]
The tile per kph amount has been recently changed. (Still, moving one or two squares at same speed displayed is inconsistent and a bug)

**Comment by SeelenJaegerTee** [comment]
Yeah. If the new lowest speed is 8 km/h I understand that I may move more then one square when driving at 16 km/h. But the lowest speed should always only move one tile per tick.
In the optimal case it would always move exactly one tile per tick. But sometimes moving no tiles would be tolerable I think (perhaps annoying but safe).
