### ISSUE TITLE
No way to cook raw sausage

### ISSUE THREAD

**Issue by Admiral-Wily** [CleverRaven/Cataclysm-DDA#27240]
I have made raw sausage in game but to my dismay there are no recipes to cook it. (and yes I have a fully loaded charcoal smoker) Am I just missing something here? If I am missing something I think there should be more clarification on how to cook it.

**Comment by Meuka** [comment]
It's supposed to be cooked, yes. You can load it into a smoking rack to finish it if you made the raw version of the recipe. It's supposed to save time when doing big batches of sausage. 

The game could stand to give more feedback about what you can do with certain items, always room for improvement.

**Comment by Admiral-Wily** [comment]
That would have been nice to know beforehand as I have no plans to build a smoking rack as I thought a charcoal smoker would suffice... all that wasted materials...

**Comment by Pupsi-Mupsi** [comment]
Better?

Before:
    "description": "A hefty raw sausage, prepared for smoking.",
After:
    "description": "A hefty raw sausage, prepared for smoking. Needs to loaded into a smoking rack to cook it.",

**Comment by Meuka** [comment]
> "description": "A hefty raw sausage, prepared for smoking. Needs to be loaded into a smoking rack to cook it.",

That ought to help, thank you!

**Comment by Pupsi-Mupsi** [comment]
You're welcome!

**Comment by Pupsi-Mupsi** [comment]
Added a recipe for brats and raw sausage will be cookable without a smoking rack.
#27310

**Comment by AsheTheHellion** [comment]
Not a (pointless) necro: Raw wasteland sausage still has this issue.
