### ISSUE TITLE
i18n - Help needed!

### ISSUE THREAD

**Issue by Pupsi-Mupsi** [CleverRaven/Cataclysm-DDA#27242]
**German Translation**

I've been helping with the german translation for a few months now.
Doing this I came across **two issues** which I can't resolve by myself.
I already tried using suggestions within transifex but since no one else is translating lately - at least the german part of the game - they remained unheard.
I hope to find help by posting this as an issue.

BTW - this (https://github.com/CleverRaven/Cataclysm-DDA/tree/master/lang/notes) has already been considered.

**1. Typos and such**

There are strings that contain typos or things I'd rather change to fit the game as it is right now - _so many things have changed over time and the translation could be a bit more precise_ - but...
...if the string has already been reviewed, then I can't change it.

Here is an example for a minor typo:

**Terminilogie -> should be - >Terminologie**
![grafik](https://user-images.githubusercontent.com/44737997/50375659-6d4ce280-0601-11e9-89d1-0fed17a93040.png)

**2. Same string different meaning**

Here is an example for a string that is as transifex sees it one and the same but has in fact two totally different meanings:

**High** as it occurs in **lang/json/effects_from_json.py:** means something like - well, baked or stoned - and in the newly changed **src/ranged.cpp:** it means big or great.

How should I handle those cases?
Any help or hint is highly appreciated! No pun intended ;-)

![grafik](https://user-images.githubusercontent.com/44737997/50375452-c31f8b80-05fd-11e9-8e19-e42972df8fcb.png)

**Comment by nexusmrsep** [comment]
Ad 1. That is a Transifex issue; perhaps with the review privilege you could edit previously reviewed translations.

Ad. 2 There is a method to add an in-code context to the translation in the comments. Quick code search tells me it this kind of symbol set: //~ followed by the context comment

**Comment by Pupsi-Mupsi** [comment]
Thanks a lot for your answer!

> 
> Ad 1. That is a Transifex issue; perhaps with the review privilege you could edit previously reviewed translations. My guess is: ask for a reviewer status.

- Well, i did not know that would be possible.
Who do i need to aks?

> Ad. 2 There is a method to add an in-code context to the translation in the comments. Quick code search tells me it this kind of symbol set: //~ followed by the context comment. My suggestion is: add such comments in the code wherever needed, and after merging and I guess Transifex update by BrettDong it should be shown under the translation entry window.

**Comment by Pupsi-Mupsi** [comment]
Thanks very much for your reply!

Ad. 1 - Who do i need to ask?

Ad. 2 Will this split up the two strings? I'll try this!

```
More Info
Size
1 word
Occurrences
lang/json/effects_from_json.py:, src/ranged.cpp:
Resource
master-cataclysm-dda
String Hash
7f0e3aa79e23ddbf2291d54fe6f373e4
```

**Comment by Pupsi-Mupsi** [comment]
That's what I came up with  #27274.
I'm not a 100% sure that this will split up the strings but its worth trying.

**Comment by BrettDong** [comment]
@Wuzzy2 is the coordinator of German translation team, whom you may seek assistance from.

**Comment by Wuzzy2** [comment]
I am boycotting Transifex (=non-free software [JavaScript]), so you have to ask the other coordinator to get reviewer status.

In my opinion, reviewer status needs to be given more liberally, because Transifex locks down reviewed strings.
I think every native German speaker should get this automatically, and people who just generally contributed high-quality translations.

> High as it occurs in lang/json/effects_from_json.py: means something like - well, baked or stoned - and in the newly changed src/ranged.cpp: it means big or great.

@programmers: The proper solution is using context. The translator comments alone does NOT fix the issue. Please look up “context” in the Gettext manual.

**Comment by Pupsi-Mupsi** [comment]
Hallo Wuzzy,

vielen Dank für deine Rückmeldung.
Wen kann ich denn sonst noch fragen?
Kannst du mir vielleicht einen Namen nennen?

Das mit dem auftrennen der Strings sollte künftig nicht mehr das Problem sein.
Kann ja mal vorkommen, dass ein Programmierer es vergisst, dann trenne ich die Strings halt einfach selbst (siehe z.B. #27274). 

Ich wünsche dir einen guten Rutsch ins neue Jahr

**Comment by Wuzzy2** [comment]
> Kannst du mir vielleicht einen Namen nennen?

Nein.
