### ISSUE TITLE
Delayed recoil after shot is not multiplies on scaling coefficient as usual recoil

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#27248]
**Describe the bug**  
I have to point to one thing. There is thing in recoil calculation called delayed recoil. It is emulates post firing recoil.
Delayed recoild in the game terms is recoil that aplyed after shot in addition to normal recoil.

Cataclysm-DDA\src\ranged.cpp
```
int player::fire_gun( const tripoint &target, int shots, item &gun )
{
...
// Up to 50% of recoil can be delayed until end of burst dependent upon relevant skill
/** @EFFECT_PISTOL delays effects of recoil during automatic fire */
/** @EFFECT_SMG delays effects of recoil during automatic fire */
/** @EFFECT_RIFLE delays effects of recoil during automatic fire */
/** @EFFECT_SHOTGUN delays effects of recoil during automatic fire */
double absorb = std::min( get_skill_level( gun.gun_skill() ), MAX_SKILL ) / double( MAX_SKILL * 2 );
...
while( curshot != shots ) {
...
int qty = gun.gun_recoil( *this, bipod );
delay  += qty * absorb;
// Temporarily scale by 5x as we adjust MAX_RECOIL.
recoil += 5.0 * ( qty * ( 1.0 - absorb ) );
...
}

// apply delayed recoil
recoil += delay;
// Cap
 recoil = std::min( MAX_RECOIL, recoil );
...
}

```

From Kevin's response we know that 
5.0 coeffecient around 

`recoil += 5.0 * ( qty * ( 1.0 - absorb ) );`

 in just scaling to increase size of aming bar.

https://github.com/CleverRaven/Cataclysm-DDA/pull/27184#issuecomment-448917813
> That adjustment makes recoil the same as it was before rescaling dispersion. It is not an oversight.
If you want to fix it, you need to come up with a per-shot recoil number that makes sense, not just drop it by an arbitrary factor.

BUT delayed recoild after shot is not multiplied on scaling coefficient now.

`delay  += qty * absorb;`

Take note that pre 2017 year rebalnce  (https://github.com/CleverRaven/Cataclysm-DDA/commit/cfefcbebf2f92193d47caf9facb1317a4f73f7f3#diff-c5873ed460ae46963dac594829494e52) this lines were:

```
delay  += qty * absorb;
recoil += qty * ( 1.0 - absorb );
```
So delayed recoil was in line of normal recoil.

This effectively makes game to forget imply part of the recoil.

**To Reproduce**  
1. Make a player with a gun, magazine, and some ammo.
2. Try to aim and shoot at a anything.
3. Debug recoil calculation Cataclysm-DDA\src\ranged.cpp

**Expected behavior**  
How it is supposed to work:
Current recoil + delayed recoil= sum of recoil.

By comments we know that up to 50% can be delayed with skill. Delayed, not lost.

0 skill:
100%+0%=100%
5 skill:
75%+25%=100%
10 skill:
50%+50%=100%

**Actual behavior**  
5.0 coeffiicient missed around delayed recoil.

So it is working now:
0 skill:
100%+0%/5=100%
5 skill:
75%+25%/5=80%
10 skill:
50%+50%/5=60%

/5 we get because of lost x5 coefficient around delayed recoil.

So player just additionally loose recoil while skill progreses.

Comment says directly how it is supposed to work

**Versions and configuration(please complete the following information):**
 Any version after 
https://github.com/CleverRaven/Cataclysm-DDA/commit/cfefcbebf2f92193d47caf9facb1317a4f73f7f3#diff-c5873ed460ae46963dac594829494e52

https://github.com/CleverRaven/Cataclysm-DDA/pull/21468

**Additional context**  
Scaling happens here:
https://github.com/CleverRaven/Cataclysm-DDA/commit/cfefcbebf2f92193d47caf9facb1317a4f73f7f3#diff-c5873ed460ae46963dac594829494e52

**Ways to solve**  
1) Multiply delyaed recoil to 5x to make it in line of "normal" recoil as it should be.
2) Rebalnce recoil calculation completely.

**Comment by Firestorm01X2** [comment]
I almost sure that is definetely oversight. 
But in fact changing make recoild much more noticable.

**Comment by SirPendrak** [comment]
From ballance and gameplay perspective, i think only 2 of ~100 my characters ever used automatic or burst fire, and only point blank vs shaggoth or something like that. Recoli was allways too big problem to risk wasting 10x more ammo. 
From realism perspective, IDK. Full autofire probably should be effective only from specialised, non-mobile gun mounts and heavy weapons on them. Burst fire, according to some videos on Youtube, could be usefull up to some distance with certain type of guns and level of skill. Right now burst is only suefull point blank. And it for sure wont be usable after incrasing recoil x2.

**Comment by Firestorm01X2** [comment]
>And it for sure wont be usable after incrasing recoil x2.

Likely it because recoil based on old gun balance, that based gun usage on very short range.

**Comment by kevingranade** [comment]
If I'm understanding you correctly, the issue is that delayed recoil is too low, so the solution is to either remove it or increase it.  That's completely incoherent.

A valid issue requires *both* a problem that is player visible and an outline of how it's expected to work.  "Lack of internal consistency" is not a valid issue.

**Comment by Firestorm01X2** [comment]
How is is supposed to work:
Current recoil + delayed recoil= sum of recoil.
By comments we know that up to 50% can be delayed with skill.

0 skill:
100%+0%=100%
5 skill:
75%+25%=100%
10 skill:
50%+50=100%

But is working now:
0 skill
100%+0%/5=100%
5 skill:
75%+25%/5=80%
10 skill:
50%+50%/5=60%



So  player just additionally loose recoil while skill progress

**Comment by Firestorm01X2** [comment]
>And it for sure wont be usable after incrasing recoil x2.
I was partially wrong. You've 50% of dispersion only on max skill. On lower skill it is muuch less noticable.

**Comment by Firestorm01X2** [comment]
So, even if I've explained that it is acutally bug it is closed. Ok.
