### ISSUE TITLE
[WinXP] Game fails to start, throws Entry Point Not Found error

### ISSUE THREAD

**Issue by HeShallNot** [CleverRaven/Cataclysm-DDA#27241]
**Describe the bug**  
Game just fails to start in Windows XP Professional SP3.

**To Reproduce**  
Download latest experimental.
Extract and run.
It won't.

**Expected behavior**  
Game starts and I get to play.
Build 0.C-34224-g7b0e7c2 was the last version that worked for me.
But hey, I don't really update that frequently so there maybe later builds that worked just fine.

Updated to this build cataclysmdda-0.C-8326.zip and noticed game is not playable anymore.
Oldest build in jenkins I can get my hands on (cataclysmdda-0.C-8287.zip) also throws same error.

**Screenshots**  
![cdda_bug](https://user-images.githubusercontent.com/46070928/50375899-f5ea7380-063f-11e9-9a0b-6c6ac5e808ec.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows XP Professional SP3
 - Game Version : any experimental build after 0.C-34224-g7b0e7c2
 - Graphics version : Tiles
 - Mods loaded : none yet

**Comment by BrettDong** [comment]
The culprit is #26250 which utilized the function `SetThreadStackGuarantee`.

**Comment by ZhilkinSerg** [comment]
Fixed with #28204.
