### ISSUE TITLE
Yugg Darts Unaffected By Body Armor, Can Penetrate Power Armor

### ISSUE THREAD

**Issue by Nameless-Survivor** [CleverRaven/Cataclysm-DDA#27250]
Even while wearing full power armor, Yugg darts ALWAYS penetrate and cause mutation.

**To Reproduce**  
1. Wear full power armor.
2. Find/spawn in a Yugg.
3. Let Yugg fire darts at you.

**Expected behavior**  
Body armor should provide some degree of protection against Yugg projectiles, just like any other. Especially power armor.

**Versions and configuration(please complete the following information):**
 - OS: Windows 8.1
 - Game Version 0.C-35128-g6838337
 - Graphics version: MSX++ Deadpeople
 - Mods loaded: 
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "FIC_Weapons",
  "ew_pack",
  "modular_turrets",
  "Jury-Rigged Robots"
  "national_guard_camp",
  "more_locations",
  "FujiStruct",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "realguns",
  "add_ebook",
  "shardstuff",
  "disable_bots",
  "disable_bots_natcamp"

**Comment by mlangsdorf** [comment]
Zugg darts don't just penetrate any armor, they cause the player to mutate if the darts hit someone else.  I'm not sure if this is working as designed or some ancient code artifact but I suspect the latter.

**Comment by Night-Pryanik** [comment]
The same problem (armor isn't protecting against special attacks) with the fungal fighter's `para_sting` attack, and with several monsters' `bite` and `impale` attack. Feral predator, for example, successfully bit and impaled my character through the power armor.

**Comment by GoLoT** [comment]
Can confirm that feral predator's special attacks completely bypass armor. I always thought that it was an intended feature to balance the game and keep it challenging though.

**Comment by kevingranade** [comment]
Just to be clear, bypassing armor with a physical attack is definitely not intended in any of these cases.

**Comment by GoLoT** [comment]
Made a quick fix for the Yugg dart attack and also for a paralysis dart attack that had similar code. I'm not sure where it is used.

I tried to reproduce the mutation bug when darts hit other monsters without success. The code checked if the player was in range and always shot the player. The fix should take care of this anyway and it should work on both players and NPCs now.

The impale attack is working as intended and taking armor into account. The damage and penetation values are too high for the attacks to be blocked by any armor but heavy power armor though. It could use a nerf.
