### ISSUE TITLE
Cauterization doesn't work properly on certain body parts

### ISSUE THREAD

**Issue by fluffy-heretic** [CleverRaven/Cataclysm-DDA#27277]
**Describe the bug**  
Currently, deep bites and infections are applied to individual body parts, while healing items are applied to HP parts. This results in unexpected behavior when bites are applied to body parts that don't have a corresponding HP part.
For instance, if the player gets a deep bite on their left **hand**, any cauterization attempts will target the left **arm** instead (at least in some respects. iuse_actor.cpp is weird, and it literally says "TODO: Make this less hacky" in there). While successful attempts will still clear the bite, unsuccessful attempts will not increment the bite timer, which means the player can try and fail as much as they like without repercussions.

**Steps to reproduce the behavior:**
1. Get a deep bite on a hand or foot.
2. Keep attempting to cauterize the wound.

**Expected behavior**  
2 failed cauterization attempts will progress the bite to an infection, the same way it works on arms, legs or the torso.

**Actual behavior**
Keep cauterizing the wound until it works.

**Comment by fluffy-heretic** [comment]
Update: You shouldn't actually be able to get bitten on your hands or feet, since bites to those locations get redirected to the arms/legs instead (bites are main_parts_only).

There are still some cases where failed cauterizations don't advance the bite timer, but now I have no clue how to reproduce that.

**Comment by kevingranade** [comment]
Unreproduceable due to inability to receive bite on hand or foot.
