### ISSUE TITLE
NPC confuses flute for weapon

### ISSUE THREAD

**Issue by SeelenJaegerTee** [CleverRaven/Cataclysm-DDA#27270]
**Describe the bug**  
I just met an NPC. He told me to keep my distance.
I had the option to drop or put down my weapon.
I put down my "weapon" and talked her into joining me. (I was assuming the game was talking about the weapon my character was wearing on his back.)
After the conversation I noticed the message that told me "You need to hold or wear bone flute (active) (1) to play it."
That's when I realised the "weapon" the game was talking about was the bone flute my character was playing.

**To Reproduce**  
1. Play a bone flute
2. walk around until you find a NPC that is worried by you "wielding a wepon"
3. observe available chat options

**Expected behavior**  
While wielding an instrument you have your hands occupied and clearly visible.
Thus playing a musical instrument should make you less scary to NPCs if anything at all.

Carrying items should by default be either considered neutral or less intimidating in most instances.

**Screenshots**  
None because I realised what happened only afterwards.

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 18.04
 - Game Version: 0.C-35451ge0588e5098
 - Graphics version: Tiles
 - Mods loaded: Disable NPC needs, Filthy Clothing, Simplified Nutrition, More survival Tools, Makeshift Items, Tall buildings, Urban development, Boats, Folding Vehicles, Vehicle additions pack, Manual Bionics, Safe Autodoc, Stats through skills

**Comment by mlangsdorf** [comment]
You can bash someone with a bone flute.

**Comment by SeelenJaegerTee** [comment]
Yeah but how paranoid is this kind of reasoning? At that point you could also feel threatened by their bare hands - could be a karate master after all. And then why even approach that person in the first place? If you are so scared, that you feel threatened by a flute you would probably run away and not approach that flute-guy.

Just imagine how threatening you would find someone who is walking around playing a flute?
Or imagine you find someone carrying a heavy 60L tank, would you imagine they want to beat you to death with it or that they were just gathering some stuff?
Especially if they carry a gun on their backs. I mean I would be happy that they have their hands holding something else and will at least take some time to draw their really dangerous weaponry.

I mean just think about the situation.
NPC approaches a perhaps friendly, perhaps hostile survivor.
Then feels threatened by the flute this person is carrying.
Why then approach the person in the first place if you are so terryfied?
Then the flute guy says to you. "Yeah come with me I keep you save!"
"Yay let's go together. I mean you are totally not going to murder me in my sleep or something like that. Although I believed you can do some pretty Riddick-style kind of stuff with that flute now I totally trust you!"

(Earlier I was driving with my Humvee with mounted laser rifle. NPC approaches wants to talk. I exit. NPC threatens me and robs me. He starts walking away, I get in my car and shoot him in the back.
I understand why this is happening. It is really hard to code some kind of context sensitive AI into the NPCs. That's why they behave in a way that is sometimes hilarious.
But I believe with carried items you could at leas flag them as more or less threatening.)

**Comment by paulenka-aleh** [comment]
A while back in a rainy day my blackbelt got mugged by an unlucky NPC with starting dialog: "Drop your freaking telescoping umbrella!"

**Comment by Lamandus** [comment]
> 
> 
> A while back in a rainy day my blackbelt got mugged by an unlucky NPC with starting dialog: "Drop your freaking telescoping umbrella!"

Well, you know those Yakuza...
