### ISSUE TITLE
Play Now gave me an error

### ISSUE THREAD

**Issue by Knight000006** [CleverRaven/Cataclysm-DDA#27271]
Game version: 8330

Operating system: Windows 10 Professional

Tiles or curses: ?

Mods active: All mods that install automatically with CDDA Game Launcher

### Steps to reproduce the behavior Try Play Now

DEBUG : mission::wrap_up called, player -1 was assigned, but current player is 5 FUNCTION : void mission::wrap_up() FILE : src/mission.cpp LINE : 245

Game crashed after alt tabbing to send debug report:

![cataclysm-tiles_2018-12-23_07-22-15](https://user-images.githubusercontent.com/5953004/50384045-64e9bb80-0684-11e9-8852-3792a20b4f7d.png)

**Comment by Toothspit** [comment]
Does this happen every time you try to `Play Now`? Can you upload your /path/to/CDDA/config/crash.log? Does it only happen when using the launcher or the .exe directly as well? Have you been able to launch the game successfully in the past or after updating?

**Comment by Night-Pryanik** [comment]
Can't confirm. I am able to successfully select Play Now! mode on 8500 on Win 10 Professional without any errors.

**Comment by ZhilkinSerg** [comment]
Please inform us if crash is still reproducing.

**Comment by Knight000006** [comment]
Sorry for making this post, I'm not entirely sure what caused the crash nor what mods I had enabled. I posted this before I had much experience in the game and don't think it will be very useful to you. I've not tested this crash further.
