### ISSUE TITLE
Allow picking up recipe components from crafting screen

### ISSUE THREAD

**Issue by Break-Off** [CleverRaven/Cataclysm-DDA#27285]
**Is your feature request related to a problem? Please describe.**  
Often, a player will need to pick up the components needed for a recipe (e.g. to craft in an area with light). Most of the recipes use components from bloated item categories, and thus is tedious to find components in a crowded storage space, even when they belong to the same category.

**Describe the solution you'd like**  
Ideally, a keybinding in the crafting screen that automatically picks up the items needed for the recipe,

**Describe alternatives you've considered**  
Haven't considered any.

**Comment by Karthas077** [comment]
Crafting already checks in a pretty large area around you... Additionally, you can both filter "all visible items" as well as "items in this tile" by name.

**Comment by TechyBen** [comment]
> Crafting already checks in a pretty large area around you... Additionally, you can both filter "all visible items" as well as "items in this tile" by name.

True... But...

I think this is more a "toggle reminder to find these crafting items" suggestion? Some games do this, if you need "wolf pelts" to make "sword ++5" then you go to crafting, click "wolf pelts" and it highlights them somewhere for a reminder to buy/collect.

In CDDA you would click it and it would set it to autopickup I guess. Or we could have a notebook/page/window somewhere where it would say "don't forget to get hotpockets".

**Comment by Karthas077** [comment]
> I think this is more a "toggle reminder to find these crafting items" suggestion? Some games do this, if you need "wolf pelts" to make "sword ++5" then you go to crafting, click "wolf pelts" and it highlights them somewhere for a reminder to buy/collect.
> 
> In CDDA you would click it and it would set it to autopickup I guess. Or we could have a notebook/page/window somewhere where it would say "don't forget to get hotpockets".

This makes so much more sense to me now. When I read "Automatically picks up items" I wasn't thinking of enabling an auto-pickup rule, I thought it meant: "walk to nearest tile containing items for recipe, pick up item, repeat until recipe is craftable" similar to how Loot Zones automate item movement. A hotkey to automatically enable auto-pickup of a recipe's components would probably be pretty useful, as manually entering auto-pickup rules is kind of a pain. It'd be even better if all of the items were held under one rule that could then be toggled on/off and not as a separate rule for each item.

I'll take a look at how complicated this process is and if no one else gets to it first, I'll shove it on my list of things.

**Comment by Inglonias** [comment]
> I'll take a look at how complicated this process is and if no one else gets to it first, I'll shove it on my list of things.

As mentioned above, CDDA already looks for items in a radius around you and automagically uses them if necessary. They don't need to be in your inventory or even the same tile as you. I think the game checks everything visible in a 6 tile radius. I'm a little unclear as to what you intend to do here, but I wish you luck regardless.

**Comment by Karthas077** [comment]
> > I'll take a look at how complicated this process is and if no one else gets to it first, I'll shove it on my list of things.
> 
> As mentioned above, CDDA already looks for items in a radius around you and automagically uses them if necessary. They don't need to be in your inventory or even the same tile as you. I think the game checks everything visible in a 6 tile radius. I'm a little unclear as to what you intend to do here, but I wish you luck regardless.

The "as mentioned above" was me by the way. And if you read my post, you'd know that I intend to add a hotkey to the crafting menu to add auto-pickup rules for all components in the currently selected recipe.

**Comment by HotSake** [comment]
I think the situation he's trying to deal with is needing to pick up items and take them somewhere else with light to craft. The items are not actually in range of the light source to do the usual automagical crafting. He wants a hotkey to be able to open a recipe in a dark area and gather all the components, so they can be carried to a lit space to do the actual crafting. Because finding them through the lookaround menu or advanced inventory is too cumbersome.

I'm not convinced this edge case warrants adding another hotkey, even if someone wants to put in the work. Might confuse new players into thinking they need to use it to gather materials before they can craft.

**Comment by Break-Off** [comment]
> 
> 
> I think the situation he's trying to deal with is needing to pick up items and take them somewhere else with light to craft. The items are not actually in range of the light source to do the usual automagical crafting. He wants a hotkey to be able to open a recipe in a dark area and gather all the components, so they can be carried to a lit space to do the actual crafting. Because finding them through the lookaround menu or advanced inventory is too cumbersome.

That's what I meant but I don't find it such an extraneous situation. Early-to-mid game, and depending on context, a player will often have difficulties getting a source of light. Or maybe you're roleplaying a tidy character that likes to have a storage space separate from their crafting tools.

An usual case is an early-game character storing stuff in a basement and crafting at ground floor when there's daylight. Or having a cargo space full of stuff that would take ages to haul instead of just needing those 2 or 3 components.

I just find it a necessary QoL enhancement, especially when the game favors hoarding and storing items.

**Comment by ifreund** [comment]
Something like this should be easy with #29210 in progress.  Just don't preform any light or other checks before creation of the in progress craft.  That would allow the player to start the craft under any circumstances then carry it wherever they want to work on it.
