### ISSUE TITLE
Ranged options to pulp zombies

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#27286]
There is no easy way for ranged characters to pulp zombies to prevent resurrection. Unlike melee characters who can pulp the corpse immediately after killing a zombie, for ranged players the corpses are too far away to reach safely without aggro-ing more zombies. You have to kill more zombies to reach the previous one you killed.

I propose the "double tap" solution. Simply shoot at a dead body again to pulp it. Possibly only limit this feature to heavy projectiles like shotgun rounds, heavy arrows, ammo that uses "large" primers.

**Comment by I-am-Erk** [comment]
Sounds like you aren't doing enough base damage!

Honestly though, the nature of zombie regeneration is such that most double taps wouldn't be enough to stop it. It'd take lots more than one shot.

**Comment by mlangsdorf** [comment]
So you want the advantage of ranged attacks, that you can kill zombies without risking getting beaten up, but you don't want to deal with the disadvantages.  The melee guy has to pull all those same zombies to get to the same position as the ranged guy, just with a lot more risk of injury.

**Comment by aierce** [comment]
I am just throwing out some ideas. There is no need to be mean.

**Comment by Solusphere** [comment]
Not exactly convenient, but one option is molotovs. They can be handy for burning corpses at a distance in certain situations, for example fighting a large pack of evolved zombies with multiple necromancers nearby. Just make sure you have enough throwing skill that you don't set yourself on fire.

**Comment by LostGoldfish** [comment]
A lot of times in movies if you shoot them or smash their heads, they are down for good, would it not be possible to have a chance of a zombie going to pulped with a head shot as the last attack?

**Comment by Zireael07** [comment]
Down for good doesn't mean pulped, pulped means the body is literally in tiny little pieces that can't resurrect.

**Comment by SirPendrak** [comment]
Most reliable way of ranged pulping are: rocket launchers, .50cal guns, heavy rail rifles. And some guns from mods, if you use them.

**Comment by mlangsdorf** [comment]
I'm sorry if I came off as mean.  I didn't intend that.  In my defense, I didn't say you were a bad person for wanting all the advantages and none of the disadvantages, I just observed that's what you were asking for.

Regardless, one of the reasons that this proposal is going to get pushback is that it makes ranged attacks even more powerful than they already are, while not fitting in very well with the game lore.

**Comment by FrozenSnowFox** [comment]
Having to pulp everything after a firefight has annoyed me for a while.  I don't really know anything about guns but would some sort of explosive round be feasible?  Something that can hit a creature then basically blow them apart enough to pulp them?

**Comment by mlangsdorf** [comment]
There are already explosive crossbow bolts and explosive arrows.  They're not going to auto-pulp but they may do enough damage to gib a zombie.

**Comment by FrozenSnowFox** [comment]
> There are already explosive crossbow bolts and explosive arrows. They're not going to auto-pulp but they may do enough damage to gib a zombie.

I'm aware archery has some explosive rounds however I was referring to guns which as far as I'm aware don't.

**Comment by cainiaowu** [comment]
You can always turn off the zombie reviving with world settings, right?

**Comment by HotSake** [comment]
There's a mod for it. It has the side effect of preventing zombie necromancers from raising them, as well, but that may be a small price to pay to avoid the tedium if that's your jam.

**Comment by kevingranade** [comment]
Initial suggestion is invalid and we haven't come up with an alternative.
