### ISSUE TITLE
Default aim target is bugging out

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#27290]
**Describe the bug**  
The default target when pressing "f" targets random empty ground

![image](https://user-images.githubusercontent.com/10649716/50389653-f50e1c00-06e9-11e9-87f0-b101f916e2b6.png)

**To Reproduce**  
This does not always happen, but it is most frequent with throwing weapons. When using guns it rarely happens. So try it out with throwing

**Expected behavior**  
Default target should be closest enemy.

Windows tiles, build 8329.

**Comment by AMurkin** [comment]
I haven't submitted it, but it bothers me some time already. Experienced it with reach attack weapons, e.g. naginata.
Sometimes after level transitions it places target marker at the previous level!

**Comment by kwl01skz** [comment]
I also encountered this problem when I used bows, spears and laser cannons (on my vehicle).

**Comment by Inglonias** [comment]
Not only have I experienced this issue, I'll do you one better. Many times I have encountered problems where the crosshair and the path leading to it is invisible, meaning if I don't have a target, I have no idea what I'm actually aiming at. This isn't really a problem except when I practice throwing, though.

**Comment by Firestorm01X2** [comment]
Referenced:
https://github.com/CleverRaven/Cataclysm-DDA/pull/27029
https://github.com/CleverRaven/Cataclysm-DDA/pull/26881

**Comment by Firestorm01X2** [comment]
Steps to reproduce.
1) Get spear
2) Spawn debug monster
3) Strike it with spear using reach attack
4) Move back on 5 tiles
5) Try to aim

You targeting will set tostrange position even out of reach of your spear. And you even can strike there, But if you move targeting cursor even once- this fake target will be cleared.

It is definetely involved
`pc.last_target_pos `

**Comment by Firestorm01X2** [comment]
```
 auto update_targets = [&]( int range, std::vector<Creature *> &targets, int &idx, tripoint & dst ) {
        targets = pc.get_targetable_creatures( range );

        targets.erase( std::remove_if( targets.begin(), targets.end(), [&]( const Creature * e ) {
            return pc.attitude_to( *e ) == Creature::Attitude::A_FRIENDLY;
        } ), targets.end() );

        if( targets.empty() ) {
            idx = -1;
            if( pc.last_target_pos ) {
                dst = *pc.last_target_pos;

                if( ( pc.last_target.expired() || !pc.sees( *pc.last_target.lock().get() ) ) && //NEED DISTANCE CHECK HERE
                    pc.has_activity( activity_id( "ACT_AIM" ) ) ) {
                    //We lost our target. Stop auto aiming.
                    pc.cancel_activity();
                }
            } else {
                auto adjacent = closest_tripoints_first( range, dst );
                const auto target_spot = std::find_if( adjacent.begin(), adjacent.end(),
                [&pc]( const tripoint & pt ) {
                    return g->m.tr_at( pt ).id == tr_practice_target && pc.sees( pt );
                } );

                if( target_spot != adjacent.end() ) {
                    dst = *target_spot;
                }
            }
            return;
        }
```

**Comment by Firestorm01X2** [comment]
Probably
```
 if( ( pc.last_target.expired() || !pc.sees( *pc.last_target.lock().get() ) ) && //<<< NEEDED DISTANCE CHECK HERE ?
                    pc.has_activity( activity_id( "ACT_AIM" ) ) ) {


```
Missed range check there.

**Comment by Firestorm01X2** [comment]
Well, not completely wrong. That helps.

```
auto update_targets = [&]( int range, std::vector<Creature *> &targets, int &idx, tripoint & dst ) {
        targets = pc.get_targetable_creatures( range );

        targets.erase( std::remove_if( targets.begin(), targets.end(), [&]( const Creature * e ) {
            return pc.attitude_to( *e ) == Creature::Attitude::A_FRIENDLY;
        } ), targets.end() );

        if( targets.empty() ) {
            idx = -1;
            if( pc.last_target_pos && rl_dist( *pc.last_target_pos, pc.pos() ) <= range ) { //<<<CHECK DISTANCE HERE
                dst = *pc.last_target_pos;

                if( ( pc.last_target.expired() || !pc.sees( *pc.last_target.lock().get() ) ) &&
                    pc.has_activity( activity_id( "ACT_AIM" ) ) ) {
                    //We lost our target. Stop auto aiming.
                    pc.cancel_activity();
                }
            } else {
                auto adjacent = closest_tripoints_first( range, dst );
                const auto target_spot = std::find_if( adjacent.begin(), adjacent.end(),
                [&pc]( const tripoint & pt ) {
                    return g->m.tr_at( pt ).id == tr_practice_target && pc.sees( pt );
                } );

                if( target_spot != adjacent.end() ) {
                    dst = *target_spot;
                }
            }
            return;
        }
```

`   if( pc.last_target_pos && rl_dist( *pc.last_target_pos, pc.pos() ) <= range ) {`

**Comment by Firestorm01X2** [comment]
No it is helping. 
Somewhere `pc.last_target_pos` getting werid postion.

**Comment by Firestorm01X2** [comment]
Looks like it is involved with player.pos(). Whitch is local pos.
It is not always changes smoothly. I mean it could change from 60 , 68 ,0 to 71 ,68, 0 after one move. But `pc.last_target_pos` remain old coordinates.
