### ISSUE TITLE
blazemod: monster mon_gloople has no harvest entry

### ISSUE THREAD

**Issue by SeelenJaegerTee** [CleverRaven/Cataclysm-DDA#27302]
**Describe the bug**  
When loading a game (or starting on a fresh generated world) error occurs:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2708723/debug.log)

**To Reproduce**  
1. Build version 
2. create new world, play now
3. observe the glory of the error message

**Expected behavior**  
no error

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS:  Ubuntu 18.04
 - Game Version:0.C-35808-ga8a6727e23
 - Graphics version: Tiles
 - Mods loaded: disable NPC need, filthy clothing, simplified nutrition, more survival tools, makeshift items mod, tall buildings, urban dev, boats, folding parts pack, vehicle additions pack, manual bionic installation, safe autodoc, stats through skills

**Comment by KorGgenT** [comment]
This error will not negatively impact you playing the game. The only thing I suggest is the author of blazemod to add a harvest entry for gloople.

**Comment by mlangsdorf** [comment]
It's a mainline mod.  I mostly expected you to add harvest entries for mainline mods.
