### ISSUE TITLE
Gunsmith Repair Kit needs full charge for crafting Suppressor and doesn't consume it

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#27303]
**Describe the bug**  
Crafting a Suppressor requires your Gunsmith Repair Kit to have a full charge of 250 battery power, but does not consume any charges at all.

**To Reproduce**  
1. Have a Gunsmith Repair Kit with less than full charge.
2. Try to craft Suppressor.
3. Can't craft Suppressor.

**Expected behavior**  
The Gunsmith Repair Kit should either not be required to have full charge, or consume the charges it is required to have. Considering how important a Suppressor is, and how easy it is to come by battries, my suggestion would be the latter.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.C-35454-ga72a177
 - Graphics version: Live People
 - Mods loaded: Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition. Just Craftable Gunpowder, Makeshift Items Mod, PKs Rebalancing, Alternate Map Key, Mutant NPCs, More Locations, Fuji's More Buildings, Urban Development, PK - No Doom Monsters, Nonperishable Overhaul, StatsThroughSkills

**Comment by HotSake** [comment]
Is the Gunsmith Repair Kit explicitly required or just some tool quality that it has? If the latter, is the bug actually that it doesn't provide said quality unless it's full?

**Comment by Bulletfang** [comment]
It explicitly asks for **Gunsmith Repair Kit (250)**, a **Gunsmith Repair Kit (249)** won't do.

**Comment by Night-Pryanik** [comment]
Cannot confirm on latest experimental as of September 30, 2019. Crafting suppressor correctly drains 250 charges of batteries from large repair kit.
