### ISSUE TITLE
Make player open Wooden Gates instead of jumping over them all the time.

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#27301]
Now player when moving through wooden gates always vaults over them. I think this is not normal human behavior. :)
I suggest making player open wodden gates first, when he moves on to them, and if they closed, or if he chooses to by pressing action key on them, he can vault over them.

**Comment by sniperm13** [comment]
I'm not too sure about your assessment here about 'normal human behavior'.

If your'e being chased by zombies and you run into a wooden gate that can be hopped over, do you take the time to unlatch it and open it to go through knowing full well that it'll make it easy for the zombies going after you?... or just hop over it which is quicker and prolly slow them down.

I'd prolly do the latter. But then again, im not 'normal human' either. XD

**Comment by peperov** [comment]
Could it be reasonable to automatically vault over the wooden gate while running?
Whereas while walking, the player character will open the gate and just like a normal door.
