### ISSUE TITLE
Add different kinds of "butchery refuse" for all kinds of monsters

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#27305]
Right now this item, what i can see as disgusting chunks of flesh fly out  of almost any "monster" you kill (humans, zombies, insects, plants, other creatures). In my opinion it is weird, like triffid can have same parts what zombie, or cocroach have.
I propose adding all kinds of this "butchery refuse" to apporopriate kinds of monsters. Fleshy, tainted, insectoid, vegetable, something like that.

**Comment by KorGgenT** [comment]
They're not the same parts. they're simply the same "class" of parts -- any bits and bobs you can't use left over from butchering, or ruined in some way or another. I do not personally see a point in adding multiple items for this purpose, but given enough support for it and I may consider adding it.

**Comment by I-am-Erk** [comment]
Since it's useless I don't see any reason to have multiple types, but I made the description and appearance of butchery refuse much more "species agnostic" in https://github.com/CleverRaven/Cataclysm-DDA/pull/27343

**Comment by SomeDeadGuy** [comment]
Because it is bloddy, dude!
What the hell am i supposed to make here, huh?
THINK ABOUT THE TILES, DUDE!

**Comment by SomeDeadGuy** [comment]
It is like i need to draw something, what can fly out of any creature in the world when you gib it!
What IN THE WORLD am i suppose to create here!?

**Comment by I-am-Erk** [comment]
I'd make it nondescript brown chunky paste myself.

**Comment by cainiaowu** [comment]
It is like the corpse problem all over again.

**Comment by SomeDeadGuy** [comment]
It will look terrible. It will look wrong.
I can only make this look normal if this item would be different for any type of creature. Or at least for any color of blood.
Red blood has this butchery refuse, white blood has another, yellow blood have 3rd one. Whem maybe it i can draw something.

**Comment by Epictyphlosion** [comment]
While you're at it, I'd recommend making eating butchery refuse cause a huge amount of negative morale, and have a high chance of making you nauseous. It doesn't make much sense for someone to eat zombie hair, skin, puss, etc. and not feel sick
