### ISSUE TITLE
Monster Difficulty Project: Zombies

### ISSUE THREAD

**Issue by mlangsdorf** [CleverRaven/Cataclysm-DDA#27308]
NPCs use monster difficulty ratings to determine how much danger they are, which enemies to prioritize, and whether to warn the player about visible monsters.  Unfortunately, monster difficulty ratings are arbitarily defined in JSON, and may not represent actual monster difficulty.

This is a proposal for calculating monster difficulty, using a formula based on melee skill, damage, HP, special attacks, etc.  For the first pass, I want to focus on zombies.

This is spreadsheet showing monster HP, melee skill, maximum melee damage, dodge skill, sum of cut and bash armor values, number of special attacks, number of emitted fields, HP, speed, attack cost, morale, aggression, and day and night vision.

https://docs.google.com/spreadsheets/d/17dM0GQMVNJCsB_AInjb2xlYtb-rKyfMWoyZRRqRvVD4/edit?usp=sharing
I've marked some monsters with my feeling on their rough difficulty (high, medium, low, or nothing special) and noted those monsters that have calculated difficulty numbers lower than their rough difficulty would suggest.

Current estimate of difficult is a multistep process:
* Offensive Base = ( 1 + melee skill ) * maximum melee damage / 25
* Defense Base = ( 1 + dodge skill ) * ( 2 + sum of bash and cut armor value ) / 25
* Special Base = 1 * number of special attacks + 15 * number of emitted fields + fudge factor
* Morale Modifier = Aggression / 10 + Morale / 1000
* Speed Modifier = ( Moves - Attack Cost ) / 100
* HP Modifier = HP / 100
* Vision Modifier = ( Day Vision + 2 * Night Vision ) / 100
* Fudge factor is 2 for monsters with melee range counterattacks like skitterbots, 5 for short range and low accuracy ranged attacks like acid spit, 10 for dangerous ranged attacks like standard turret's SMG, 20 for very dangerous ranged attacks like a rifle turret or zombie necromaner's special abilities, 30 for fatal even with armor attacks like an anti-material turret
Difficulty = ( Offensive Base + Defense Base + Special Base ) * ( Morale Modifier + Speed Modifier + HP Modifier + Vision Modifier )

The logic being a monster is more difficult as it's melee skill and maximum damage increase, as it is harder to hit and damage, and as it has more special abilities.  More HP, effective speed, aggression and morale, and vision have a multiplicative effect on a dangerous monster, but don't directly contribute a monster's difficulty: a monster with no armor or dodge ability, low melee skill and damage, and no special abilities isn't much of threat, even if it has 10,000 HP.

Suggestions on monsters that have inappropriate rough difficulties, or modifications to the formula to improve the estimate, are appreciated.

**Comment by JacobKessler** [comment]
Possibly an additional modifier for being a threat at range? Spitters, shockers, grenadiers, necromancers, masters, etc. are all more threatening than they might otherwise be because they are a threat while they are over there, potentially behind a bunch of other zombies. That seems to be several of your high-fudge zombies.

**Comment by mlangsdorf** [comment]
Updated to note an explicit fudge factor to account for ranged attacks and other specials, because just counting the number of special attacks was leading to a bunch of inaccuracies, like standard zombies (with 3 lame special attacks) having a much higher threat rating than zombie necromancers (with 1 dangerous special attack).

**Comment by Inglonias** [comment]
To clarify, this isn't about actually changing how hard zombies are, this is about assigning a number that explains to NPCs how difficult they are?
