### ISSUE TITLE
text to speech for illiterate to read.

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#27312]
Ok, the title is a bit confusing, true, but I just had an idea.
There are decives and software for mobile phone, which don't only make pictures to text but also read those texts out loud.

So my idea is, that a illiterate can actually read a book (nearly like the NPC reads for you mechanic) by using a mobile phone. Of course it takes battery and a lot of time to transfer the books to... Well... Podcasts actually. Maybe by this method we are able to transfer books into digital form, so we don't need to carry the books all the time.

(Also we should think about giving more mobile phones to professions at the start, who of us doesn't carry a phone nearly all the time)

**Comment by anothersimulacrum** [comment]
TTS software strikes me as something that would be installed on very few phones, and if it was installed on a phone, not something that many illiterate people could necessarily figure out how to use or that it existed.

**Comment by Lamandus** [comment]
> 
> 
> TTS software strikes me as something that would be installed on very few phones, and if it was installed on a phone, not something that many illiterate people could necessarily figure out how to use or that it existed.

Well illiterate doesn't mean Tech-phobia. There are many phones already comming out with such software right now and, don't forget.

The futuuuuuuure! Where looking at disabled is even more important...
(Why didn't I see a wheelchair ingame till now?)

**Comment by Inglonias** [comment]
Ideas like this have been brought up before. My understanding is that the point of Illiterate is to stop a character from being able to use books and computers. Full stop. It gives you a ton of points for a reason, that reason being that it locks you out of virtually all of the cool stuff you can do in the game.

As far as I'm aware, if you don't want to make a character that cannot read or use computers, don't take this trait. If you feel you don't get enough points, increase the number the game gives you in the debug settings of the options. If you want to discourage the reading of books, that's what the Hates Books trait is for. It gives you a lot less points, but it is an option. (Disclaimer: I am biased because I wrote that trait into the game)

**Comment by Kelenius** [comment]
They can't read signs. And they probably shouldn't be able to use the phones and the MP3 players either.

**Comment by Lamandus** [comment]
Like I said all or nothing. Everything what request reading should not be able to be used (as a tag maybe). A Thermomix also needs reading, actually same as an ATM machine and vendor machine.

**Comment by Kelenius** [comment]
Come to think of it, turning on the light on a phone only requires you to click on some icons. MP3 player would depend on the type. I agree on the ATM machine, but for a vendor you don't need to read, you just need to match the symbols to the buttons. What's Thermomix?

**Comment by Lamandus** [comment]
Okey, the same with TTS Software, Just precesses on some icons. And the TTS software is catered for blind or visibly impaired persons. So the "what to do" commands will be spoken. It is viable.

I think Thermomix ist something like a multicooker. It tells you by text what to do next and cooks stuff on its own.

**Comment by Leland** [comment]
> the same with TTS Software, Just presses on some icons

As someone who works in the accessibility world for software, I'm not familiar with any mobile OS that exposes text-to-speech so easily. iOS, for instance, is: Settings > General > Accessibility > VoiceOver > VoiceOver enable

Even besides getting them started, accessibility mechanisms are complex!

Assuming that a mobile phone that a character would encounter in the game would be essentially random, I can't see an illiterate person figuring out on their own how to both a. enable the setting and b. understand how to use it.

**Comment by kwl01skz** [comment]
Maybe we should allow illiterate people to ask NPC to teach them how to use TTS software. In addition (mentioned long ago), illiterate people can also learn to read, although it is difficult for adults, but it is not impossible.

**Comment by kevingranade** [comment]
Previous feedback is on point, illiterate is intended to be all or nothing.
Additionally, all of the particularly good TTS options use remote resources, so would be non-functional after the cataclysm.
