### ISSUE TITLE
Skeletons seem to be bugged

### ISSUE THREAD

**Issue by MegaGlub** [CleverRaven/Cataclysm-DDA#27320]
Since the new butchering system as of update #8340, skeletons seem to have a few broken features; skeletons now drop two corpses when killed, skeletons "explode" into sinews when killed, skeletons spawn a stack of 70 bones a few tiles to the left when killed. I discovered this while using mods, however I was able to reproduce this bug with an unmodded world.

Create a character with the "bow hunter" profession, mostly just for the compound bow. 
Spawn in metal broadhead arrows
Set all skills to max/just archery
Spawn in skeleton
Take "precise" shots at the skeleton until it dies

While I'm not sure how or why almost any of this happens, the sinew "explosion" is likely because of an incorrect item ID. Also pretty sure that the stack of 70 bones has something to do with the sinews replacing them.

**Comment by KorGgenT** [comment]
#27318

**Comment by MegaGlub** [comment]
Beat me to it by but an hour.
