### ISSUE TITLE
Can not attack friendly units with melee attack

### ISSUE THREAD

**Issue by 3721assistant** [CleverRaven/Cataclysm-DDA#2733]
You can not attack a friendly unit with your melee attack, but you can attack them with your ranged weapon.  Also, with all your heavy melee weapons which are slow but have area effect, you can not swing them unless these zombies are REALLY near you. Ranged weapons can be fired against wall to gain experience, but melee can't, unless you have a real enemy in front of you. All there are because movement and melee attack uses the same direction keys, and you can not perform a melee attack anytime you want. So I think some methods should be added that can make you attack, for example a key command like s, to make your next move an attack, or a lock key which makes all your next direction moves into melee attacks.

**Comment by mugling** [comment]
Fixed in `master`
