### ISSUE TITLE
Error message on loading game: monster xxx has no harvest entry

### ISSUE THREAD

**Issue by paradigm369** [CleverRaven/Cataclysm-DDA#27338]
**Describe the bug**  
When starting the game, 3 error messages appear:

DEBUG    : monster mon_gloople has no harvest entry
 
 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 952

 DEBUG    : monster mon_gray has no harvest entry
 
 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 952

 DEBUG    : monster mon_oozle has no harvest entry
 
 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 952

**To Reproduce**  
1. Load the attached savegame using experimental build 8344
2. Error messages should appear

**Expected behavior**  
Should not have error messages

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version 0.C-35831-gbec1d99 Build 8344 

**Additional context**  
Savegame attached
[Kahakuloa error 3.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2712491/Kahakuloa.error.3.zip)

**Comment by ZhilkinSerg** [comment]
Are you using Blaze mod? Is it version bundled with the game or custom one?
