### ISSUE TITLE
Lower Warmth value of Nomad Gear.

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#27336]
Nomad gear used to be one of my favourite clothing items in the early-to-mid game, due it's it's excellent combination of good storage space and reasonable encumbrance and protection. Unfortunately, back in 2015 Marrim adjusted it, increasing the Warmth rating of the armor to 40, meaning that it's simply too hot to use consistently in the majority of seasons and weather conditions, which in my opinion goes against the entire theme of the item, and makes what was previously a great early game staple irritating to manage. A nomad would not design his primary outerware such that it was unusable for 3/4 of the year. That's what long underwear is for.

I suggest that the item's warmth be reduced to 20, which is the average warmth of the clothing that goes into crafting it.

**Comment by ZhilkinSerg** [comment]
Nomad gear has duster, pants and a lot of leather in recipe. It should be hot wearing it most of the year in New England.

**Comment by Solusphere** [comment]
The duster has a warmth of 15. The hottest variant of pants it uses, army pants, have a warmth of 20. At worst, it should only be 35, and then only on the legs, The arms and the legs tally up to 15 and 20 respectively.

And again, the person designing and using this clothing is FROM New England. They would presumably design a piece of clothing not explicitly for winter scenarios in such a way to allow for maximum usability.

**Comment by ZhilkinSerg** [comment]
Judging on the recipe all of the items had leather padding added to them, so warmth of `LEGS` should be calculated as `20`+`25` (army pants + leather pants), warmth of `TORSO`, `ARMS` and `LEGS` should be `15`+`30` (duster + leather duster), etc. That would sum up to value of `45` for `TORSO` and `ARMS` and `75` for `LEGS`. Obviously some major parts of initial clothes were cut-off in the process of making nomad gear, but still result value of `40` seems about right and even should be bumped up slightly for 95% coverage suit.

You can also just use common sense - it would be unpleasantly hot in two layer leather/cotton full body cover outfits when temperature is above 12-15 C.

**Comment by Solusphere** [comment]
Alright, I concede the point of the current warmth being explainable by the recipe. So if that's the obstacle, let's adjust the recipe.

If you're worried about it being overpowered, I'd be happy for it to be made a little weaker if it means I don't have to take it off every time the sun comes out. I feel like excessive micromanagement isn't a very good balancing mechanism for a strong item anyway. I just want to be able to use the damn thing outside of winter, and there's nothing in the description of the item that remotely suggests I shouldn't be able to.

**Comment by Pupsi-Mupsi** [comment]
A light version could be a thing but with less protection, warmth and storage.

**Comment by kevingranade** [comment]
I think @Pupsi-Mupsi has the right idea, a new "light nomad gear" ensemble of items and recipes would be ideal.

**Comment by Pupsi-Mupsi** [comment]
What about this?
Any thoughts?

![grafik](https://user-images.githubusercontent.com/44737997/50499920-c7a8d180-0a4d-11e9-9c4e-6d92a355be2d.png)

![grafik](https://user-images.githubusercontent.com/44737997/50499922-cc6d8580-0a4d-11e9-82c0-b1c8037ccb22.png)

  {
    "id": "armor_nomad_light",
    "type": "ARMOR",
    "name": "light nomad gear",
    "description": "A light makeshift outfit made from pre-cataclysm clothing designed for long summer travels.  It has less storage space and armor compared to regular nomad gear.",
    "weight": 3750,
    "volume": 26,
    "price": 28500,
    "to_hit": -4,
    "material": [ "cotton" ],
    "looks_like": "armor_nomad",
    "symbol": "[",
    "color": "light_gray",
    "covers": [ "TORSO", "ARMS", "LEGS" ],
    "coverage": 75,
    "encumbrance": 16,
    "storage": 50,
    "warmth": 10,
    "material_thickness": 3,
    "environmental_protection": 1,
    "flags": [ "VARSIZE", "POCKETS", "WATERPROOF" ]
  },

  {
    "result": "armor_nomad_light",
    "type": "recipe",
    "category": "CC_ARMOR",
    "subcategory": "CSC_ARMOR_SUIT",
    "skill_used": "tailor",
    "difficulty": 5,
    "time": 80000,
    "autolearn": true,
    "using": [ [ "sewing_standard", 90 ] ],
    "components": [
      [ [ "tunic", 1 ] ],
      [ [ "vest", 1 ], [ "chestrig", 1 ] ],
      [ [ "ragpouch", 2 ], [ "dump_pouch", 2 ], [ "fanny", 2 ] ],
      [ [ "tool_belt", 1 ], [ "legrig", 1 ] ],
      [ [ "rag", 20 ] ]
    ]
  },

**Comment by Solusphere** [comment]
I'd say leave the coverage at 95%, given that you're reducing the protection values to 3. As it stands it's purely a storage item, with less defensive merit than even normal clothing. Upping the coverage at least makes it on par with wearing a hoodie and a pair of jeans in terms of protection. Otherwise, the description should make clear that it's purely a collection of bags and straps rather than an outfit.

**Comment by Solusphere** [comment]
I actually do appreciate you coming up with these, sorry if I wasn't giving that impression. I like the revised version, I think it's competitive with other available options without being overpowered. It has my approval, for what it's worth.

**Comment by Pupsi-Mupsi** [comment]
Let's wait a little bit to see if there are any other thoughts on this issue, okay?

**Comment by Marrim** [comment]
W.r.t. nomad gear the idea as I understood it (and that set it apart from survivor suits) was:
1) adapting/refitting a set of pre-cataclysm clothing as opposed to crafting an almost entirely new thing
2) aiming for maximum storage as opposed to protection

The high warmth and thickness were to represent compressing many articles of clothing into a single layer. No matter how good of a tailor you are, you can't circumvent the laws of physics.

A suit of gear could be envisioned to provide high storage but be easier to wear--sort of like a full-body variant of utility vest or chest rig. Nearly same storage, but lower thickness / coverage / warmth / encumbrance. But it would no longer be what nomad gear essentially is (a suit made of highly overlapping pieces of clothing). A recipe for such a piece would call for several worn storage items (drop leg pouches + tool belt + chest rig + fanny pack or something like that) but no dusters or army pants.

Personally, I'm a big fan of suit-type items to reduce clothing micromanagement, so I like what @Pupsi-Mupsi offers for that reason as well. Might want to change it away from normal layer, though.

**Comment by Pupsi-Mupsi** [comment]
@Marrim
Thanks for your input.
So would you move both (the old and the new light version) to the outer layer?

**Comment by Marrim** [comment]
The new light version, definitely.
The original, I don't know. It is based on a duster but also includes pants; like I said, compressing a whole lot of clothing into a single layer, and it's not obvious which layer that would be. Would it be easier to imagine it worn over a shirt and a pair of pants, or under a duster (knowing that it is made from a duster AND pants)?

**Comment by GoLoT** [comment]
My thoughts: 

I'm not sure moving it to the outer layer is a good idea. It would allow you to wear both suits (regular and light nomad gear) at the same time while preventing you from using the lighter version with a yoroi or a plate armor. Being less bulkier than the regular nomad gear it wouldn't make much sense. And with this kind of gear you will want to have an extra layer of defense on top.

About raising the coverage value I think it is a double edged sword. Considering it has a very low protection value and it doesn't have the sturdy flag, pretty much any hit will damage it. You wouldn't want it to be hit often, just like any storage items.

**Comment by baraba3** [comment]
my 2 cents
Nomad gear is too protective for basically walking storage item.Gambeson is protecion 5 encumbrance 8 and coverage 80% while being intended combat item while nomad gear is protection 8/8 enumbrance 10 and coverage 95 with insane storage of 20l.

it get even more unblanced  when compared with scavenger gear high end item with tailoring requirment 8  and rare item demand such is tactical dump pouch which is basically sturdy nomad gear with same heat problem and additional 10 encumbrance.

both scavenger gear and nomad gear should be intended for travleing esepcially in summer when people re supposed to move and scavenge and not to give you heatstroke.They shoudl have possiblity to become  more lossened whcih woudl reduce their warmth and coverage.

i think also nomad gear encubmrance is too low and enncumbrance of scavenger gear and nomad gear shoud be swithced or equalised.

**Comment by Marrim** [comment]
Scavenger gear is the reinforced, sturdy variant of nomad gear. It still trades protection for storage but has additional qualities that nomad gear lacks:
1) environmental protection -- 100% coverage is a consequence of a design intended to keep contaminants out (just like the survivor suits and AEP suit).
2) durability. It's not as good against physical damage as the survivor suit of the same encumbrance would be, but it IS designed to be resilient to wear and tear.

Winter and summer versions could be envisioned, but if it loses the full coverage or the sturdy flag, it would not be worth crafting anymore.

**Comment by baraba3** [comment]
1.It has enviromental protecion of 2 lower than rain coat with acid resistance 1 and fire resitance 0.  
http://prntscr.com/m3gilb
Nomad gear has enviromental protection 1. and acid 0.
http://prntscr.com/m3gisb

95 to 100 coverage isnt that drastic improvment when nomad gear and scavenger gear are compared in light of theri respective crafting demands.

2.I know its more durable but considering its highest tailoring item with 20 encumbrance which is additonal 10 encubrance to all body  whcih hinders combat  it doesnt look that appealing.Aso despite that kevlar is used in constucting scavenger gear it only have increased cutting protection whcih is 13 comapred to nomad gear 8 while bashing protecion  is 8 for both of them.

Current stage of items dont justify scavenger gear requirments so it level of tailorign should be lowered to 5 to directly compete with nomad gear as armored version of it for combat or it shoud gain some advantage.

Also while i am at it some can find use in nomad cowl in game cosiderign ti can be gained fairly quickly sacavenger cowl on other hand is prety much useless at levels you can carft him.Another reason to lower tailoring requirements or add additional functions to make item appealing.
scavnger gear
http://prntscr.com/m3gjlw
