### ISSUE TITLE
Readjust intensity of Auto-shifting the view while driving

### ISSUE THREAD

**Issue by Profitablius** [CleverRaven/Cataclysm-DDA#27339]
Spawn a vehicle, activate the option, go with 60 km/h and enjoy not seeing where you are going.
This option was pretty great. After the vehicle rework however, it's not far enough anymore - it should be adjusted to fit the new speed-per-tile.

While zooming works, it's still useful even when zoomed out.

**Comment by CoroNaut** [comment]
Perhaps this could be introduced as an "Auto-shift vehicle view offset" under "Auto-shift the view while driving" option in the interface options menu. It would be nice if it were a decimal with default 1.00, up to maybe 5.00 or something. I would personally like about 1.50x the current offset.

**Comment by SeelenJaegerTee** [comment]
> Perhaps this could be introduced as an "Auto-shift vehicle view offset" under "Auto-shift the view while driving" option in the interface options menu. It would be nice if it were a decimal with default 1.00, up to maybe 5.00 or something. I would personally like about 1.50x the current offset.

Yes I support this idea.
I'd also really appreciate it if I could tell the game to zoom out one level when driving.
