### ISSUE TITLE
Chairs showing up as "no tile" with memory

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#27330]
**Describe the bug**  
The memorized area shows these chairs as unknown (with the yellowish dot)

**To Reproduce**  
1. Turn on map memory
2. look for an instance that this happens

**Expected behavior**  
Chairs don't show up as unknown tile even with other chairs showing up fine

**Versions and configuration(please complete the following information):**
 - OS: Win7
 - Game Version 0.C-35549-g07569da
 - Graphics version Tiles
 - Mods loaded None
With chairs as enemies in memory view:
![capture](https://user-images.githubusercontent.com/24307650/50458347-7ce56780-0930-11e9-992b-28404cc2b880.PNG)
Chairs in clear sight:
![capture2](https://user-images.githubusercontent.com/24307650/50458349-7fe05800-0930-11e9-864b-22fc955defee.PNG)

**Comment by AMurkin** [comment]
Just to clarify. As it says in the image, this is “no tile”, not an enemy. A tileset mapped this tile for unknown objects:
```json
{
  "id": "unknown",
  "fg": 1952,
  "bg": 632,
  "rotates": true
}
```

**Comment by CoroNaut** [comment]
Thought the yellowish dot was strictly enemies, fixed description

**Comment by Inglonias** [comment]
The ChestHole tileset hasn't been updated in quite some time, sadly.

**Comment by Night-Pryanik** [comment]
I guess this is not an issue at all. The "fix" is to update the tileset.

**Comment by AMurkin** [comment]
> I guess this is not an issue at all. The "fix" is to update the tileset.

They are rendered fine when visible for the player. So this is not exactly a tileset issue.
