### ISSUE TITLE
2 issues on chr creation Traits menu

### ISSUE THREAD

**Issue by darth-servo** [CleverRaven/Cataclysm-DDA#2734]
Latest build, downloaded this afternoon:

1st issue: High Adrenaline, Poor Hearing, and Meat Intolerance aren't in their proper positions in the lists, if the lists are meant to be sorted alphabetically.

2nd issue: The negative traits list uses dark gray / dark red as colors when the list is not active, however when the list IS active, the color scheme switches to light gray / pink.  Unfortunately, this color combination happens to be very bad for some red-green colorblind folks (such as myself), and as a result it is extremely difficult to see the highlighted traits when the list is active.

My suggestion is to use the dark red for highlighting in this list whether it has the active focus or not.

**Comment by OzoneH3** [comment]
Configurable color palettes are in #11865.
