### ISSUE TITLE
Marked firewood source not being used while sewing

### ISSUE THREAD

**Issue by Profitablius** [CleverRaven/Cataclysm-DDA#27342]
The marked firewood source is a very handy tool. It's unfortunately not working while sewing, and if I recall correctly reading aswell. If I can throw new wood inside the fire while cooking, I can probably do it while sewing, and especially while reading. Sorry if this is intended.
**To Reproduce**  
Mark a firewood source. Drop wood there. Make a fire. Try sewing, reading.
**Expected behavior**  
Fire being fed automaticly
Win 7, #8345, Tiles, default

**Comment by TheMurderUnicorn** [comment]
Reading does work with firewood source.  At least it did for me in build 8346 (current).

![reading](https://user-images.githubusercontent.com/41651793/50499280-6b768b00-0a16-11e9-860c-e5140b1f62fb.png)

**Comment by Profitablius** [comment]
Guess I remembered wrong. However, it doesn't work during sewing anyways, and I'd like if it did.

**Comment by ZhilkinSerg** [comment]
Do you mean modifying clothing/repairing clothing action? Cause there is no distinct `sewing` action - sewing clothing is just "long craft" action (which is no different from boiling water or welding steel frame in game internals).

![image](https://user-images.githubusercontent.com/16213433/50509754-0ebbb480-0a98-11e9-86bf-530fc23a5db9.png)

**Comment by Profitablius** [comment]
Yes, that's what I was referring to, sorry that wasn't clear.

**Comment by Break-Off** [comment]
Can confirm at build 8349. This bug is also found when doing any other action from tools (e.g. repairing with welder).

**Comment by ZhilkinSerg** [comment]
> 
> 
> Can confirm at build 8349. This bug is also found when doing any other action from tools (e.g. repairing with welder).

Unimplemented features are not bugs.
