### ISSUE TITLE
Keep the other sock when crafting rock in a sock

### ISSUE THREAD

**Issue by Dansiman** [CleverRaven/Cataclysm-DDA#27340]
**Is your feature request related to a problem? Please describe.**  
The rock in a sock description says: "A sock with a rock tied into the end of it." But you have to use a pair of socks to craft it. Where does the other sock go?

**Describe the solution you'd like**  
- [ ] Create a new (single, unmatched) "sock" item
- [ ] Update rock in a sock recipe to use the single "sock" instead of a pair
- [ ] Add disassembly recipe for "pair of socks" that gives two single socks, requires no skill and has no chance of failure. This should also take almost no time, be easily done in the dark, and should ideally give zero skill training XP.
- [ ] Add a crafting recipe for pair of socks (leave the existing tailoring recipe in place) that uses two single socks, again requiring no skill, having no failure chance, taking no (or very little) time, being easily dark-craftable, and providing no skill XP. *(Honestly, this probably shouldn't even count as practice for staving off skill rust.)*
- [ ] Make wearing or taking off a single sock take 1/2 the time of donning/doffing a pair?
- All of the above would need to be done for wool socks as well.

**Describe alternatives you've considered**  
I thought about making the existing rock in a sock recipe give a single sock back as a byproduct (keeping the pair as the component), but this might cause issues with disassembling the rock in a sock - can recipes with byproducts even be disassembled? And what would we give the player when disassembling in this case? Do we give them back one sock and one rock, even though the original component was a pair of socks? Or do we give the player a pair of socks back, and vanish the byproduct sock? But then what if that second sock was used for another recipe, or damaged/destroyed/eaten? Plus, then we'd have to ensure that this byproduct matches the material of the original pair of socks.

I think it's less problematic to simply require the pair of socks be split into two single sock items before crafting the rock in a sock out of one of them.

**Additional context**  
- Will need to ensure that a pair of socks can always be disassembled into two single socks, regardless of whether it was made by the simple "pair up two single socks" recipe, or was crafted from the tailoring recipe.
- Will need to ensure that any "legacy" rock in a sock made from the current recipe still disassembles into a pair socks, so that players with existing rocks in socks don't lose our socks to the sock-eating monsters that live in our dryers.

**Comment by TechyBen** [comment]
In the CDDA backstory, due to budget cuts fighting the BLOB, they make extremely thin socks in New EnglandHamshire. So, you have to double up on the socks when crafting things with them. Double the thickness you see.

Totally legit Lore. I read it on Reddit or something...

**Comment by Pupsi-Mupsi** [comment]
Why not just change the description ;-)

**Old:** A sock with a rock tied into the end of it. A true weapon of desperation.
**New:** A pair of nested socks filled with a stone. A true weapon of despair.
- One could argue that you need a pair to make the weapon more durable.
- Disassembling will still yield a pair of socks, which will be fine after the change.

**Comment by TechyBen** [comment]
> Why not just change the description ;-)
> 
> **Old:** A sock with a rock tied into the end of it. A true weapon of desperation.
> **New:** A pair of nested socks filled with a stone. A true weapon of despair.
> 
> * One could argue that you need a pair to make the weapon more durable.
> * Disassembling will still yield a pair of socks, which will be fine after the change.

Wow, I was like a millisecond from being ninja'd!

**Comment by Pupsi-Mupsi** [comment]
ninjaaaaa

**Comment by Dansiman** [comment]
> Why not just change the description ;-)

Oh, sure, take the easy way. :stuck_out_tongue_closed_eyes:

**Comment by SeelenJaegerTee** [comment]
>Additional context
>- Will need to ensure that a pair of socks can always be disassembled into two single socks, regardless of whether it was made by the simple "pair up two single socks" recipe, or was crafted from the tailoring recipe.
>- Will need to ensure that any "legacy" rock in a sock made from the current recipe still disassembles into a pair socks, so that players with existing rocks in socks don't lose our socks to the sock-eating monsters that live in our dryers.


Also when disassembling a washing machine the result obviously must always include a single sock.
:)

**Comment by Solusphere** [comment]
"You begin washing your (2)Sock"
"Your Sock is now clean!"

**Comment by Pupsi-Mupsi** [comment]
Don't be mean. He did put a lot of thought into it and I admire that. He's trying to improve the and so should we all...
