### ISSUE TITLE
Zone improvements

### ISSUE THREAD

**Issue by SeelenJaegerTee** [CleverRaven/Cataclysm-DDA#27350]
**Is your feature request related to a problem? Please describe.**  
1) Right now zones are displayed with an "!", the same as items. This means when trying to display the zones the player has set up the player is out of luck if they already sorted something in them.

2) Right now the system for sorting loot sorts it into rigid, predefined categories that the player can not change.

**Describe the solution you'd like**  
1) Coloured zone overlay:
Display zones using a coloured overlay instead. Make it so player can assign colours to zones (e.g. like '#ff0000'). Draw this colour on top of the zone with some transparency value.

2) Custom zones:
Specific items, priority of zone, number of each item.

An example how this could work ingame:
Let's assume the player wants to have a stash of tools. He wants to keep two tools of each type (one for usage and one spare). But he wants to disassemble all the others for copper wire.
It would really be great if the player could tell the game:

Zone 1: (here will go 2 of each tool)
-"red"
-"name: Tools"
-"priority: 1st"
-"Include: Tools"
-"Amount: 2"
-"Exclude: none"
Zone 2: (here go specific things the player wants to disassemble)
-"blue"
-"name:Disassemble-ables"
-"priority: 2nd"
-"Include: Flashlight, Soldering Iron, Hotplate, makeshift Welder, Broken Manhack, Broken Eyebot, Car alternator, Truck alternator"
-"Amount: infinite"
-"Exclude: none"
Zone 3: (here go all the tools in excess of 2 copies and not specified in zone 2)
-"#00ffff"
-"name:Excess_tools"
-"priority: 3rd"
-"Include: Tools"
-"Amount: infinite"
-"Exclude: none"

**Describe alternatives you've considered**  
1) Displaying symbols or letters could also work.

2) A less complex system where you can make custom zones that let you only specify items without priorities or max. amounts would still be pretty great.

**Additional context**  
If you have several metric tons of loot it becomes tedious to sift through all your piles for specific stuff.

Image mockups:
Current:
![current](https://user-images.githubusercontent.com/39884350/50516225-e76de300-0aa9-11e9-8dc0-07d2278e16b9.png)

Color Mockup:
![mockup](https://user-images.githubusercontent.com/39884350/50516231-f2c10e80-0aa9-11e9-9bb8-b298a4d1e503.png)

**Comment by Inglonias** [comment]
Remember that any feature like this also has to work in an ASCII terminal with severe color limits (I believe you get sixteen colors)

**Comment by SeelenJaegerTee** [comment]
Could you replicate something like above in ASCII and post a screenshot?
This would make it easier talking about it.
But I'll try addressing the issue "blind".

Solution one:
Fall back to the nearest colour displayable in terminal mode. (If #FF2211 is not available then fall back to #FF0000). Simply draw a square in the fallback colour in ASCII.

Solution two:
Blinking coloured letters. Select from the letters A-Z and form N colours. Alternate between drawing the tile with the loot and the zone indicator (e.g a red B).
For the sake of argument assume we can only select from n=3  (white, blue and red for colourblind friendliness or red, green, blue if we don't care about that)
That would be 26*3=78 possibilities. Even if some were effectively unusable e.g. I and J and U and V being too similar.
Currently there's 21 zone options. So even if you have many farm plots and want each farmplot having a unique indicator there's plenty space with 78+ combinations.
Yeah OK perhaps if you have 5 faction camps, two cars and 3 "inhabited locations" and each has all 21 piles and a lot of farm zones.
But I think at his point it would become acceptable when the colour/letter combination repeat over the different sites. (And at that point your problem is probably finding your zone on the zone-manager list on the right side of the screen and not in the game area).

Also:
I don't know if it works in ASCII but right now it is not really working that great in tiles.
In the above screenshot if I had selected Loot:unsorted a blinking "!" would be drawn on top of the "!" on the tile with the two-by-fours. Which I am unable to distinguish from a "!" without a blinking "!" over it.
That's what I mean once you have two items in a loot pile you can no longer trivially figure out where this pile is. Because the indicator becomes invisible.
![current_problem](https://user-images.githubusercontent.com/39884350/50518032-cb6f3f00-0ab3-11e9-8382-ba8c0dd1eea9.png)

**Comment by Alienmen1** [comment]
This is also a problem I have when using the Retrodays tileset

**Comment by sdvhunter** [comment]
Can relate to sifting through tons of loot. These features will drastically help with that, especially if you aren't using one item pile for everything.
