### ISSUE TITLE
0.C-35840 - Can't unload UPS with Battery Compartment.

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#27351]
After installing a Battery Compartment Mod to a UPS, and loading it with a charged Small Storage Battery (in order to facilitate swapping batteries in the field), I can no longer unload the UPS, nor can I remove the tool mod. Attempting to do either results in a message saying "You can't unload a rechargeable UPS!"

![image](https://user-images.githubusercontent.com/19789267/50518143-1fe3e000-0aef-11e9-810c-1873d4e79b04.png)

**Comment by AMurkin** [comment]
Looks like #18820.

**Comment by ZhilkinSerg** [comment]
Duplicate of #18820.
