### ISSUE TITLE
Reproducible crash in 0.C-35900-g0779cd4

### ISSUE THREAD

**Issue by AlexanderGlasco** [CleverRaven/Cataclysm-DDA#27363]
**Describe the bug**  
CRASH LOG FILE: config/crash.log
VERSION: 0.C-35900-g0779cd4
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5CCBB5[cataclysm-tiles.exe+0x1CCBB5]
    @0x5CD762[cataclysm-tiles.exe+0x1CD762]
    SMPEG_error+0x4B034@0xE5AA80[cataclysm-tiles.exe+0xA5AA80]
    _C_specific_handler+0x98@0x7FFB5BAB7C58[msvcrt.dll+0x27C58]
    _chkstk+0x11D@0x7FFB5E69F7DD[ntdll.dll+0x9F7DD]
    RtlWalkFrameChain+0x13F6@0x7FFB5E60D856[ntdll.dll+0xD856]
    KiUserExceptionDispatcher+0x2E@0x7FFB5E69E70E[ntdll.dll+0x9E70E]
    @0x8B3C06[cataclysm-tiles.exe+0x4B3C06]
    @0x641333[cataclysm-tiles.exe+0x241333]
    @0x648005[cataclysm-tiles.exe+0x248005]
    @0x6485F3[cataclysm-tiles.exe+0x2485F3]
    @0xCD6805[cataclysm-tiles.exe+0x8D6805]
    @0xCCFB35[cataclysm-tiles.exe+0x8CFB35]
    @0x6D3FD5[cataclysm-tiles.exe+0x2D3FD5]
    @0x6FA7CC[cataclysm-tiles.exe+0x2FA7CC]
    @0x6FC7C7[cataclysm-tiles.exe+0x2FC7C7]
    @0x717722[cataclysm-tiles.exe+0x317722]
    @0x6F6E49[cataclysm-tiles.exe+0x2F6E49]
    IMG_LoadWEBP_RW+0x4C8C19@0x1435D99[cataclysm-tiles.exe+0x1035D99]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFB5E413034[KERNEL32.DLL+0x13034]
    RtlUserThreadStart+0x21@0x7FFB5E673691[ntdll.dll+0x73691]
.

**To Reproduce**  
1. Load save file
2. Walk east towards bandit mission
3. Step on landmine outside NW window of bandit cabin
4. Game immediately crashes with above dump

**Screenshots**  

![crash dump](https://user-images.githubusercontent.com/13599306/50534602-eae68600-0b0c-11e9-918b-40de2a275248.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-35900-g0779cd4
 - Graphics version: Tiles
 - Mods loaded: Vanilla (DDA default - no npc needs, simplified nutrition)

**Additional context**  
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2716120/crash.log)
[Crash Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2716121/Crash.Save.zip)

**Comment by BrettDong** [comment]
Unreproducible on macOS. This issue seems to be platform dependent.

**Comment by ZhilkinSerg** [comment]
Cannot reproduce under debugger yet. Do you reproduce it every time on your system?

**Comment by BrettDong** [comment]
I have no idea how `IMG_LoadWEBP_RW` is invoked. On macOS, I set up a symbol breakpoint of this function, but I am unable to trigger it anyway.

**Comment by GoLoT** [comment]
![image](https://user-images.githubusercontent.com/1606943/50780751-076c8600-12a4-11e9-9a0b-f9b2fc6bad7c.png)

- OS: Windows 10
- Version: 0.C-36156-gf336c73
- Graphics: Tiles
- Mods: Those used by the save

It seems to be windows specific, yeah.

**Comment by ZhilkinSerg** [comment]
I cannot reproduce it on latest master with provided savegame. Please inform us if you still experience crash.
