### ISSUE TITLE
Many normal items cannot be disassembled

### ISSUE THREAD

**Issue by Malorn-Des** [CleverRaven/Cataclysm-DDA#27366]
**Describe the bug**  
Many items which would logically be able to be disassembled cannot be. This leads to clutter, confusion, etc.

**To Reproduce**  
Attempt to disassemble any of the following.
1. Firefighter Belt
2. Composite Crossbow
3. Pair of Eyeglasses
4. Dashboard
5. Military Composite Plating

**Expected behavior**  
Many of these items would logically be possible to disassemble. 
A crossbow, for example, can be disassembled, whereas a composite crossbow cannot.
Steel plating can be disassembled, but military composite plating cannot. 
Sunglasses can be disassembled, but eyeglasses cannot.
This is confusing and inconsistent, especially since it is possible to craft several of these items, but then is not possible to disassemble them. I would expect that most items could be broken down, if perhaps for less materials.

**Versions and configuration(please complete the following information):**

    OS: Windows 10
    Game Version 0.C-35934-ge9592ac build 8351
    Tiles version
    Mods loaded: Disable NPC Needs, Simplified Nutrition, Filthy Clothing

**Additional context**  
Perhaps this is not a bug, but rather a feature request. I'm uncertain as to the classification. There is a much longer list of items which cannot be disassembled which logically could be, those five were merely the few that seemed most...obvious.

I would not be against trying to fix the problem myself, if someone could direct me to the proper files? Of course this is something more comprehensive then any one person can easily fix, but 'every brick in the wall' so to speak.

**Comment by kevingranade** [comment]
It's simply a question of what parts it yields when disassembled.  If you have a disassembly recipe to propose, please do so.

**Comment by TechyBen** [comment]
Composite Crossbow for example. Which parts would be salvageable?

**Comment by Malorn-Des** [comment]
In the case of the five examples above, I would be happy to make some suggestions, and indeed, as I said, would be happy to attempt the work as well if someone could point me to the files related.

Starting from the top:

Firefighter Belt - scrap metal and leather patches seem the obvious choice, given the materials it is made of, and both are quite useful. This would probably be a 'cut up' option rather then a true disassemble, as with many clothes.

Composite Crossbow - likely the long string, and then probably some of the wood or bone used to create it.

Pair of Eyeglasses - perhaps a chance of a high-quality lens, and a chunk of plastic? I would use magnifying glass as a template for what is required to disassemble it.

Dashboard - I would suspect an electronics control unit? Equally perhaps an electronics control unit should be an ingredient in something, perhaps a dashboard? The item browser says it's not used in any recipes currently, despite being craft-able. (In turn, it can be disassembled already, thankfully.)

Military Composite Plating - Quite a lot of lumps of steel and plastic chunks, almost certainly. It's one of the best vehicle armors in the game, it should be worthwhile to break down.

:::::

Please understand, I'm not attempting to be confrontational, I just encountered this and it seems likely it was an oversight or error, given how other items that were very similar could be broken down. Perhaps it's just the way I play the game, but I tend to want to break down anything I don't want to use. Of course, that would likely be at a loss of overall resources and utility, but it's better then having items that will never be used again.

If there is a design aspect behind many items being impossible to re-purpose or break down, then I apologize, I was merely unaware of it.
