### ISSUE TITLE
Soda can stove kit cannot use methanol as fuel

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#27369]
**Describe the bug**  
Methanol (modded 'concentrated alcohol' fuel) is unable to be used a fuel in the soda can stove kit.

**To Reproduce**  
1. Craft a single instance of methanol (250mL), pour into a container
2. Acquire a soda can stove kit (note the fuel type)
3. Attempt to reload the soda can stove kit.

Log message: "You don't have any denatured alcohol to reload your soda can stove kit!"

**Expected behavior**  
Methanol, as it is considered a 'concentrated alcohol' ammo type, should be able to be used in all concentrated alcohol stoves.

**Versions and configuration**
 - OS: Win 7
 - Game Version: build 8351
 - Graphics version: Tiles
 - Mods loaded
Extended Realistic Guns,
More Survival Tools,
Tall Buildings,
Boats,
Vehicle Additions Pack,
Tanks and Other Vehicles

**Additional context**  
Similar to #18460
The in-game description says 'concentrated alcohol' as the fuel type, but the [item browser page](https://cdda-trunk.chezzo.com/popcan_stove) specifies 'ethanol' and 'denatured alcohol'.  I suspect the fuel type just needs to be updated under the hood.

**Comment by natsirt721** [comment]
I have a very old world (generated Dec 2016), that might have something to do with it.  Stove was crafted in the build stated - as was the methanol, and stored in an (unsealable) container.  Ill try to duplicate the bug again in my debug character.

**Comment by Pupsi-Mupsi** [comment]
Great. Please let me know if it works in a freshly created new world.

**Comment by natsirt721** [comment]
Seems to work fine in the new world.  Also, I spawned a fresh stove in my old world and it accepted methanol fine (after unloading the denatured alcohol it spawned with).   Renamed the new stove via marker  and it still accepted methanol. I would guess that it has something to do with old crafting materials?? Recommend this ticket be closed.

**Comment by Pupsi-Mupsi** [comment]
**Glad to hear that!** 
Since I don't have the rights to close this ticket myself. Could you close the issue by clicking on:
![grafik](https://user-images.githubusercontent.com/44737997/50623908-df36fd00-0f1a-11e9-9e7b-39653876f115.png)
_At the bottom while being loged-in._
<br>
**Happy zombie hunting!**
