### ISSUE TITLE
Duplicate bug caused by Zone Manager (50 atomic lamp)

### ISSUE THREAD

**Issue by Alienmen1** [CleverRaven/Cataclysm-DDA#27370]
**Describe the bug**  
It appear that having a 5 squares line of Tools with another square of spare parts in the middle of it cause many tools to be duplicated among the 5 squares of tools...

**To Reproduce**  
1. Make a zone of tools with 5 squares
2. Make in the third square a single square of Spare parts
3. I honestly dont know. I went throught the squares picking up duplicate of sewing kit, repair kit etc, unloading them and putting the empty tool in an Ignore zone in the corner of my room. Somehow I ended up with 2 Atomic lamp... and If I look into the other Tool zone, I see other Atomic Lamp... Like as if I had gathered 5 atomic lamp and the zone manager spreaded them out evenly, 1 on each square
4. Take each of the item that appears in each square of the Zone manager, pull them out and leave 1 in the Spare part/tool square. Go drop the Atomic lamps in the unsorted all together, now you end up with double Atomic Lamp

**Expected behavior**  
Not having having the opportunity to get 5 atomic lamp... jesus I managed to end up with 50 atomic lamp
**Screenshots**  
![image](https://user-images.githubusercontent.com/41959522/50543007-ce436000-0b97-11e9-8a2a-c6782e288bf2.png)

**Versions and configuration(please complete the following information):**
 - OS: [r Windows 10]
 - Game Version [0.C-35942-g725458b (tiles)]
 - Graphics version [Retrodays
 - Mods loaded [e.g.dda, disable npc need, simple nutrition, bens GF recipes, craftable gun pack, deadleave fict gun, extended realist gun, icecoon, makeshift, medieval, more survival tool, mythological, more locations, fuji's and Oa' buildings, More city locations, arcana, necromancy, class and scenario mod, classic roguelike class]

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

https://drive.google.com/open?id=1hAvc7QkMFjepU9HygXhuDSYw3Vg0W-lT

**Comment by Inglonias** [comment]
I think I've also managed to duplicate this issue. It has to do with autosorting items from a zone that has more than one space defined to another zone that also has more than one space defined. More testing is required.

**Comment by Inglonias** [comment]
**Reproduction steps below**:
1. Create an unsorted loot area with any number of spaces in it.
2. Create a sorted loot area of any kind that is **MORE THAN ONE TILE LARGE**
3. Place the relevant loot type into the unsorted loot area.
4. Autosort. The item will duplicate N times, where N is the number of tiles in the destination zone.

**Comment by GoLoT** [comment]
I tried to reproduce the issue but I'm getting crashes instead. The cause seems to be the same though, just a different consequence.

It seems that it was caused by #26921 when a `break;` was removed by mistake. Going to do some testing and make a PR.
