### ISSUE TITLE
Performance is very slow in ascii mode

### ISSUE THREAD

**Issue by HeyBanditoz** [CleverRaven/Cataclysm-DDA#27388]
**Describe the bug**  
The game runs very slowly in ascii mode. The more the character can see, the worse it gets (if you're in a room, e.g the evacuation shelter, the game runs normally. If you step outside, it gets gradually slower as visibility increases.) Enabling or disabling map memory (via `{`) does not affect performance.

**To Reproduce**  
1. Make a new world with no mods, evac shelter scenario.
2. Step outside of the evac shelter.

**Expected behavior**  
N/A

**Screenshots**  
Display is very large.
![screenshot_20181231_213637](https://user-images.githubusercontent.com/7574664/50570351-a6aeec00-0d7f-11e9-9d8f-215c903b5b49.png)

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux
 - Game Version: 0.C-35992-g91756ddc04
 - Graphics version: Terminal
 - Mods loaded: dda

**Additional context**  
Compiled from latest git with `make CCACHE=1 USE_HOME_DIR=1 -j24`

**Comment by Muffindrake** [comment]
Please compile with `RELEASE=1 LTO=1` and see if the game is still slow.

Seriously, I'm getting tired of the amount of reports that have issues building the game. Can't we just have `make -j9` do the right thing???

**Comment by ZhilkinSerg** [comment]
> 
> 
> Please compile with `RELEASE=1 LTO=1` and see if the game is still slow.
> 
> Seriously, I'm getting tired of the amount of reports that have issues building the game. Can't we just have `make -j9` do the right thing???

Yeah, someone should update the makefile.

**Comment by ymber** [comment]
I can reproduce this in SDL and curses. Also running Arch, cata version 0.C-35997-g2494eed from narc's builds.

It starts fine as soon as you step outside, then performance rapidly degrades the further you go. Performance is fine if you go into a building.

**Comment by Toothspit** [comment]
- OS: Arch, nvidia blob 415.25-5, kernel 4.20.0-arch1-1-ARCH
- Game Version: 0.C-35997
- Graphics Version: Tested tiles, curses
- Mods loaded: dda, no_npc_food, filthy_morale, novitamins, boats, blazemod, Tanks, DP_REMIX_INDICATORS

make -j4 CCACHE=1 TILES=1 RELEASE=1 SOUND=1 LUA=1 LOCALIZE=0
Cannot reproduce.

make -j4 CCACHE=1 RELEASE=1 LUA=1 LOCALIZE=0
Cannot reproduce.

What makeflags are you using, @HeyBanditoz ?

**Comment by HeyBanditoz** [comment]
Adding `LTO=1` `RELEASE=1` to my existing flags `make CCACHE=1 USE_HOME_DIR=1 -j24` seems to have fixed the issue.

**Comment by Night-Pryanik** [comment]
Should be closed then?

**Comment by HeyBanditoz** [comment]
Right. Another issue should be opened concerning the makefile.
