### ISSUE TITLE
butchery returns seem way off

### ISSUE THREAD

**Issue by SeelenJaegerTee** [CleverRaven/Cataclysm-DDA#27390]
**Describe the bug**  
Butchery results seem way off.
I got onto this when I realized that butchering wolves and coyotes always fails to produce a pelt for me.
(Also Butchering a zombie yields no tainted hide, which I find strange since butchering an NPC gives you a skin but this may be totally unrelated to this).

I played around with debug mode for a bit and found out that bears give you a pelt.
Wolves never give you a pelt as far as I can tell (N=25)
So I am thinking this may have to do with animal size.

**To Reproduce**  
I have spawned 25 wolves.
All were killed by debug command so there should be no damage to the corpse from excess violence.
I then hauled them onto a butchering rack with an adjacent table.
Then I performed full butchery on all of them.
Character has 20 in all skills, a butchers knife, a tool box, a butchering rack and a table next to the rack.
Attached below you find the results of butchering 25 wolves.

**Expected behavior**  
Wolves should give you something to tan.
I suspect this has something to do with animal size and butchery returns as a black bear does yield a pelt.
But if I look at the screenshot there are more returns that seem way of.
For example only one kidney out of 25 wolves for a 20 survival character with essentially best conditions as far as i understand?

Even if the character fails to harvest an intact wolf pelt I think you should get at least a partial hide.
Realistically even rather small animals like rabbits should give you a small hide that you can tan for a leather patch.
Maybe needs introduction of "small hide" and "small fur" items that way small animals can give some hide returns and for big animals the game could downgrade a big hide to several small hides when the retrieving the hide fails.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 18.04
 - Game Version:0.C-35997-g2494eed669 (compiled around 11:00 CET)
 - Graphics version: Tiles
 - Mods loaded: default mods

**Additional context**  
Butchery yields from 25 wolves:
![screenshot from 2019-01-01 14-59-04](https://user-images.githubusercontent.com/39884350/50573560-84948880-0dd6-11e9-9ed5-ffa151be5bb7.png)
![screenshot from 2019-01-01 15-08-59](https://user-images.githubusercontent.com/39884350/50573587-68451b80-0dd7-11e9-802c-8ae749975356.png)

PS: Changing the raw_pelt entry in mammal_fur from 0.02 to 0.202 resulted in 198 raw pelts from 25 wolves. This makes me believe the ratios for medium sized animals are just way off.

**Comment by Mcrone617** [comment]
I also was doing some testing, and it seems the problem also applies to coyotes, which when I debug tested butchering them with 8 skill in survival and medical (the max you can achieve in game easily). I never got specific items, like sweetbread, brains, etc, but I also didn't get pelts, like with wolves. I'm not sure if it affects other animals, but wolves/coyotes are the only animals I've noticed when doing some superficial testing.

**Comment by KorGgenT** [comment]
i'll have to look into this...

**Comment by KorGgenT** [comment]
What was the dexterity of the character you tested this with?

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/50578187-1797e780-0e04-11e9-94bb-e477111ad07f.png)
a quick google search suggests that the weight of the wolf monster can be adjusted to be more realistic.
I am unfortunately quite busy with other projects at the time, but this fix is entirely in JSON, and several fairly simple options exist, but this is my suggestion: adjust wolf weigh (and volume!) to be more realistic. maybe look at other monsters as well.

**Comment by Toothspit** [comment]
I think it would be more suitable to adjust the weight (and quantity) of the yielded items. If butchering a wolf results in no raw fur 100% of the time due to the constraint of the fur item's minimum mass, then everything smaller than a wolf will also never result in a raw fur; adjusting our model of a wolf fixes only one case.

Making the yielded items more granular in mass (and adjusting recipes to match) is a cleaner solution to the problem introduced by moving from quantities to masses. This is a cutoff problem with harvesting yield, not a problem with how we've modeled wolves.
