### ISSUE TITLE
Electroreceptors mutation does not detect shocker zombies or robots

### ISSUE THREAD

**Issue by Hymore246** [CleverRaven/Cataclysm-DDA#27405]
Electroreceptors is pre-threshold fish mutation that allows you to detect any creature that generates electricity (Shocker Zombies, all robots, etc) through walls but you take increased pain if you are ever shocked. However, the mutation doesn't give any indication of creatures out of line of sight.

1. Use debug menu to gain Electroreceptors mutation. 
2. Use debug menu to spawn any shocker zombie or robot creature.
3. Move out of line of sight (or just spawn it out of sight).
4. No mutation specific indication of the creature will be displayed out of sight.

I've tried this on few tilesets such as MSX++LIVE_PEOPLE and RetrolASCII neither displays anything.

I'm using build 0.C-35997-g2494eed right now.

This [link](https://github.com/CleverRaven/Cataclysm-DDA/pull/25855) discussing the improvements to the Fish mutations has example images of how Electroreceptors is supposed to function at the end of the post.

**Comment by anothersimulacrum** [comment]
I just tested a few of the fish mutations, and aqueous repose and freshwater osmosis are also not working.

**Comment by Toothspit** [comment]
Looks like a bad squash at the end of #25855 dropped a lot of code. That would need to be recovered.

@Xhuis I don't want to PR your work, can you see about recovering it? Looks like your branch is deleted, but you could eyeball-diff between commits b8da667 and f72d2ff on that PR to see what's missing.

**Comment by Xhuis** [comment]
I'm no longer an active contributor and I don't have Visual Studio installed. If you want to PR it yourself, it'd be greatly appreciated.

**Comment by Toothspit** [comment]
Will do, and thanks for stopping back in! I'll make some time today or tomorrow to reassemble it.

**Comment by kevingranade** [comment]
Fixed by #27986
