### ISSUE TITLE
transifex review rights

### ISSUE THREAD

**Issue by Pupsi-Mupsi** [CleverRaven/Cataclysm-DDA#27402]
Is there any chance that anyone else would honor me with **transifex review rights**.
Take a look at: #27242

**Comment by Pupsi-Mupsi** [comment]
Thanks. I'll do that.

**Comment by BrettDong** [comment]
Sorry to say that I'm unable to help you on this problem. I only have the permission of pushing/pulling translations on Transifex. For escalating user roles, you may seek VV_Heretic for help.
