### ISSUE TITLE
Removing vehicle parts without skill

### ISSUE THREAD

**Issue by hyper2snyper** [CleverRaven/Cataclysm-DDA#27403]
We talked about this in the discord but I'm going to re say it here. One day i had started a character with only talking skills and turned NPC spawn up, i needed rope. now since i didn't have a a screw driver and didnt have the right mechanics skill anyways, i couldn't just remove seat belts. Later i was thinking, how hard would it be to take a knife and just cut the seat belt out, sure it wouldn't be as good of a rope but i could still see getting strings and other parts from it. If i wanted scrap metal and sisnt want to save the alternator in a car, i could just take a hacksaw and hammer and bash it out.

**Comment by Inglonias** [comment]
You can smash car parts to do this. You can even recover bits of metal by doing so. Not sure this needs its own button.

**Comment by kevingranade** [comment]
The idea is targeted smashing, likw you justcwant tovstrip out the seat belts, or get upholstery from seats,  but you don'tcwant to kake a lot of noise or spend a lot of time doing it.

**Comment by junkyjb** [comment]
> The idea is targeted smashing, like you just want to strip out the seat belts, or get upholstery from seats, but you don't want to make a lot of noise or spend a lot of time doing it.

I agree.

Removing seat belts currently requires a screwdriver, (which is easy to make so not much of a problem), but as all we recover is "short rope" which can be used to re-make what I assume is effectively a makeshift seat belt I would think a knife should also be sufficient.

Seats require bolt turning 2 to remove, which is sensible, as we are recovering the whole seat not just parts.

However, once removed, disassembling the seat calls for fine metal sawing, (not even just metal sawing).
I thought I remembered being able to stand over a removed seat and butcher it for leather with a knife. However either this has been patched out, or I've always had a hacksaw while doing that and not realised it was being used instead.

Maybe something similar to the new butchering system could be used, where a knife gets you a portion of the leather as a quick job, and a metal saw gets you more/all depending on either survival or mechanics skill level?

(Currently smashing a vehicle tile which contains a seat seems to result in the seat either being destroyed leaving no parts, or being torn off and falling to the floor as a damaged seat. Trying to smash the removed seat results in "There is nothing there to smash".)
