### ISSUE TITLE
Finger scalpel missing dissection message.

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#27410]
Unlike using pocket knifes, x-acto knife, or scalpel etc, finger scalpel cbm is missing it's unique message when dissecting a corpse. There is no message at all.

**Comment by aierce** [comment]
I don't really know how to fix it but relevant code is here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/a8a6727e23011583de985f14f2eda0e9338a8f79/src/activity_handlers.cpp#L289

**Comment by ImmemorConsultrixContrarie** [comment]
Simply add "case 5:" (because finger scalpel has 5 fine cutting)

	case 3:
		u.add_msg_if_player( m_info, _( "You dissect the corpse with a trusty scalpel." ) );
		break;
	case 5:
		u.add_msg_if_player( m_info, _( "My precious fingers! It's time to work, muah ha ha!" ) );
		break;

P.S. You could put any message you want.
