### ISSUE TITLE
Keybinding to delete the input from the search field

### ISSUE THREAD

**Issue by DaAngus** [CleverRaven/Cataclysm-DDA#27446]
Every time you search in the various search fields afterwards you have to delete the search term.
It was my first instinct to press control+backspace to delete the last word.
This game probably attracts some heavy keyboard users so I doubt it is just me.
Straight forward:
Search "water" - ctrl+backspace deletes the word
Search "clean water" - ctrl-backspace twice to clear the input field

**Comment by Night-Pryanik** [comment]
Why it's a bug? I'd say it's just quality of life improvement at best.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
