### ISSUE TITLE
Loading Crash

### ISSUE THREAD

**Issue by DragonTamr34** [CleverRaven/Cataclysm-DDA#27450]
**Describe the bug**  
[https://pastebin.com/Gj44ZQLZ](url)

I created a new world and the game crashed while loading the items part of the world creation. I have never had a crash before, only getting kicked to the main menu.
**To Reproduce**  
         Select create custom character and add the mods listed below. Set up the settings and create the world. The game loads all the mods and then crashes at the items loading bit.

**Expected behavior**  
The game creates a new world and opens character creation screen. This is what happened last time I played.
**Screenshots**  
N/A
**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-36156-gf336c73
 - Graphics version: Tiles
 - Mods loaded: [ "dda", "novitamins", "Bootleg_Walkers", "craftgp", "FIC_Weapons", "realguns", "ew_pack","makeshift",  "Medieval_Stuff", "More_Survival_Tools", "nw_pack", "DracoDogMod", "modular_turrets", "PK_REBALANCE", "Salvaged_Robots", "Cata++", "crazy_cataclysm", "Mining_Mod", "mutant_npcs", "Ninja", "cityside", "boats", "deoxymod", "blazemod", "Tanks", "Arcana", "necromancy", "jury_rigged_robots", "ms", "NM_wpns", "StatsThroughSkills", "oa_additional_buildings_mod", "mapgen_demo", "more_locations", "FujiStruct"]
**Additional context**

**Comment by ZhilkinSerg** [comment]
Try creating game without all but third-party mods (e.g. `Bootleg_Walkers`, `PK_REBALANCE` and `Cata++`) and report is crash still occurs.

**Comment by ZhilkinSerg** [comment]
Closing due to no info for several months - please inform if crash still occurs for you on latest version.
