### ISSUE TITLE
QoL improvement - Combat Chainsaw

### ISSUE THREAD

**Issue by Luiizz** [CleverRaven/Cataclysm-DDA#27481]
**Is your feature request related to a problem? Please describe.**  
Removing the combat chainsaw Tree cutting quality would make using them much more practical by getting rid of the menu pop-up every time the player turns them off in order to save fuel/energy.

**Describe alternatives you've considered**  
Making it so the menu won't pop-up but keep their quality, but that probably would be a bit harder I think.

**Additional context**  
If a player can craft a combat chainsaw (witch as far as i know is the only way to get them) they can craft or use the regular chainsaw for tree cutting instead. Their description even says that cafting one makes tree cutting less effective and that combat is their main focus

**Comment by Epictyphlosion** [comment]
Makes sense. If they aren't meant for cutting trees, then they aren't, simple as that

**Comment by Fris0uman** [comment]
The pop-ups of activated item is also a problem for item with SCREW quality
Converting the cordless drill to be activable makes it so it ask for tool mod to remove every turn
