### ISSUE TITLE
Allow starting negative effects in character generation.

### ISSUE THREAD

**Issue by hyper2snyper** [CleverRaven/Cataclysm-DDA#27483]
As the title implies, I think it would be really cool to allow characters to chose starting addictions, limb conditions, and sicknesses thus gaining points for character creation.

**Comment by GoLoT** [comment]
I don't think that's a good idea as those effects are temporary and the extra points would give you permanent effects in exchange. Basically free points once you get past the very early game. Why would anyone want to cripple their characters permanently (i.e. reducing their HP or speed) when they can just pick a trait that will be inconvenient for just a couple of days?

Challenge scenarios have the right idea as they give you extra points but put you in a difficult spot. I wouldn't mind seeing more scenarios being added.

**Comment by hyper2snyper** [comment]
But I want it b make early game harder, especially if you start with a broken leg of arm, or are 20 irradiated. Certain addictions are terrible to get through., maybe they could be permanent addictions?

**Comment by AskaHope** [comment]
I personally like the addiction idea. Choosing addictions could be interesting for roleplaying purposes. The addiction and intensity could be something totally optional and the ability to remove starting addictions doesn't seem all that bad (Why Police Detective is nicotine addict anyway?)

**Comment by GoLoT** [comment]
As a choice/background for a character it sounds OK. As a way to earn extra points at character creation I think it would be unbalanced considering traits are supposed to be permanent perks. From a balance standpoint it wouldn't make sense to make a simple addiction that will last hours/days give the same amount of points as a trait that makes a character unable to eat vegetables for the whole run. Of course this is only my opinion.

**Comment by Achie72** [comment]
Maybe add a special flag to them, so you can't get rid of them? If you want it for the roleplay, you are fine with it sticking with you, and it won't give you free points. And mark them with some extra character on the trait/effects something like `Alcohol addict (Permanent) / (Choosen)`.

**Comment by Fris0uman** [comment]
>As a way to earn extra points at character creation I think it would be unbalanced

You can already chose `free form` and have unlimited point at charactet creation. I don't think "keeping player from cheesing" is a good justifications, points for negative trait could simply be adjusted to be decimal for exemple. This way you'd need a significant amount of them just to get 1 point.

**Comment by GoLoT** [comment]
> You can already chose `free form` and have unlimited point at charactet creation. I don't think "keeping player from cheesing" is a good justification, points for negative trait could simply be adjusted to be decimal for exemple. This way you'd need a significant amount of them just to get 1 point.

That doesn't really make sense. Just because you can "cheat" doesn't mean that balance should be thrown away. The game is balanced around specific settings and it is meant to be played that way. You are free to cheat (either by using the ingame settings or any other means) and save scum if you feel like it, but that shouldn't affect the default experience and balance of the game.

**Comment by Fris0uman** [comment]
Fair enough
But expanding character creation with more options has merit on it's own .Its probabky coded in integer but the code is always evolving so that could change.

**Comment by GoLoT** [comment]
Yeah, I see your point but I still think that traits should stay as permanent effects. Maybe addictions could be added to the traits list with a cost of 0 so you have the choice without being able to abuse the point system. I think that would be a compromise that would allow roleplayers/people looking for a challenge to tweak their character while still maintaining balance.

But I guess we will have to wait and see what the maintainers think.

**Comment by kevingranade** [comment]
Stalled discussion
