### ISSUE TITLE
Rat mutation tree results in carnivore due to requirements

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#27488]
**Describe the bug**  
Intestinal fortitude requires Saprovore, this results in the rat mutation tree getting carnivore.
Rats are omnivores.

**To Reproduce**  
1. Inject Rat Serum
2. repeat
3. get carnivore

**Expected behavior**  
Not getting mutations that aren't in the rat mutation tree.

**Screenshots**  
Unnecessary

**Versions and configuration(please complete the following information):**
 - OS: Windows 8.1
 - Game Version Build from 6/01/2019 (DD/MM/YYYY)
 - Graphics version: Tiles
 - Mods loaded: none, happens regardless

**Additional context**  
not required as this is a simpler issue

**Comment by kevingranade** [comment]
I'm not against changing it, but this isn't a bug per se.  It's intended that you get all kinds of out-of-tree mutations as you mutate.

**Comment by PsyXypher** [comment]
Well, perhaps that doesn't need to be "fixed", but perhaps a change can be made so Carnivore gets cancelled out by another mutation later on (Rapid Metabolism, maybe?). The other "solution" is to make it so you could randomly get Substance Tolerance (I'm not sure if this is already possible or not) which also works as a requirement for Intestinal Fortitude, and would be a suitable replacement.

**Comment by sneeze-attack** [comment]
We could remove the carnivore requirement from saprovore. The other idea is to cancel out carnivore when reaching rat post-thresh.

I'm leaning towards removing the carnivore requirement, but both should be valid solutions. @dissociativity do you think one idea is better than other?

**Comment by kevingranade** [comment]
Fixed by #28176
