### ISSUE TITLE
Problems with character perceiving wall corners consistently

### ISSUE THREAD

**Issue by Mcrone617** [CleverRaven/Cataclysm-DDA#27486]
**Describe the bug**  
The problem appears to be something related to map memory(?) For some reason my characters seem to perceive corner walls in different "states" depending on where they are standing.

**To Reproduce**  
stand near a wall with a corner, and depending on which side you view it it shifts from a straight edge to a corner edge.

**Expected behavior**  
Maybe I'm remembering it wrong but i could have sworn that corners were consistently corners up until the last couple of builds, no matter where you viewed them from.

**Screenshots**  
![strange walls pt1](https://user-images.githubusercontent.com/26668115/50804074-5369fb80-12a1-11e9-8e7a-50b1fe145c8f.PNG)
![strange walls pt2](https://user-images.githubusercontent.com/26668115/50804076-549b2880-12a1-11e9-9085-80db1105442c.PNG)
![strange walls pt3](https://user-images.githubusercontent.com/26668115/50804079-5664ec00-12a1-11e9-9cab-330247079db5.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-36249-g7de8b69]
 - Graphics version: Tiles
 - Mods loaded: irrelevant 

**Additional context**  
This initially showed up in a current game I had, with quite a few mods. However when I tried the game with just the core game and no mods the problem still persisted, that's what the screenshots are from. It's a little disorienting in game, as when you traverse through a house, the corner walls rapidly shift, but the walls themselves seem to maintain their corner properties, it's only my characters perception of them that is wonky.

**Comment by ZhilkinSerg** [comment]
Probably related - https://github.com/CleverRaven/Cataclysm-DDA/pull/26830.

**Comment by jbytheway** [comment]
Almost certainly #26830.  It's intended behaviour that corners don't appear as corners until you know them to be.  However, your map memory in those screenshot ought to be enough to make them render as corners.  It's because you're using the Tiles build but with Tiles disabled; I never tested that combination.  Should be an easy fix.
