### ISSUE TITLE
Refugee Camp bugs

### ISSUE THREAD

**Issue by SeelenJaegerTee** [CleverRaven/Cataclysm-DDA#27480]
**Describe the bug**  
Screenshots are pretty self explanatory.
The first time I arrived at the camp there was an artifact spawned inside it.
![screenshot from 2019-01-07 17-10-55](https://user-images.githubusercontent.com/39884350/50788658-51606680-12ba-11e9-94a7-ea042553d0d5.png)
I killed the process and went there again. Second time no artifact.

I offered the broker 1 can of beer. When I agreed to trade this happened:
![screenshot from 2019-01-07 19-38-09](https://user-images.githubusercontent.com/39884350/50788418-a5b71680-12b9-11e9-88ad-6fa394018bbc.png)

Old guard liaison told me to execute bandits when I accepted I got this:
![screenshot from 2019-01-07 19-41-39](https://user-images.githubusercontent.com/39884350/50788558-13634280-12ba-11e9-9d52-c06461957654.png)

Relevant log for the chat and mission bug:
[log_partial.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/2734049/log_partial.txt)

**Expected behavior**  
Refugee center (and perhaps other special locations) should block the placement of destructive worldgen entities.
Refugee center missions should not throw errors at you.

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 18.04
 - Game Version: 0.C-36052-g5a7796598d
 - Graphics version: Tiles
 - Mods loaded: disable NPC needs, filthy clothing, simplified nutrition, more survival tools, makeshift items mod, tall buildings, urban dev, boats, folding parts pack, vehicle additions pack, manual bionic installation, safe autodoc, stats through skills

**Comment by mlangsdorf** [comment]
@ralreegorganon needs to look at the bandit_cabin bug.

I can confirm the trader dialogue bug and will go resolve it.

I am not convinced the artifact spawning in the refugee center is a bug.

**Comment by SeelenJaegerTee** [comment]
@mlangsdorf 
I think it is a bug, as you can see I've got zapped by the artifact.
If the artifact had spawned at the front door it could have killed story-relevant NPCs.
If the NPCs were smart they would just set up their main door somewhere else, or they would leave the camp and set up shop somewhere else and leave a note on the door ... but I think no one want's to go down the road to code such a thing.
Please consider that this game is not meant to be played with backup saves.
It could easily happen that you save before going through a door and then realize that NPCs for a major game feature have been killed by world-gen. I would be really annoyed if this happened after some major time investment, especially because there's nothing I could have done to prevent this.

**Comment by ralreegorganon** [comment]
re: bandit_cabin bug, do you happen to have a save (preferably from before, but after is ok) you can attach to this issue?

Also, how old, approximately, is the save (in terms of game versions)?

**Comment by SeelenJaegerTee** [comment]
@ralreegorganon
Backup save. Quite a couple of hours before the issue.
[Exira_2019-01-07_16:35.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2734755/Exira_2019-01-07_16.35.zip)

Current save.
When the bug occurred I just killed the program, and replayed from before entering the center. So this save is not "right before the bug" - but the mission has never been attempted.
PS: Just tested it. Bug is reproducible from this, just go inside and talk to the rep and you will get the bug.
[Exira.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2734762/Exira.zip)

If I remember correctly I started this world around 2018-12-24. I believe it shouldn't be older than Dec 5th.

**Comment by kevingranade** [comment]
I think map extras spawning wherever they like isn't in itself a bug, but the fact that the refugee camp inhabitants don't react to the extras is.  "There's a scary artifact in the back room, we don't go there" is totally reasonable, but having NPCs stand right next to it and not mention it is a problem.

Until NPCs can react appropriately, preventing them from spawning there is a reasonable workaround.

**Comment by mlangsdorf** [comment]
@ralreegorganon needs to look at the bandit_cabin bug.

I can confirm the trader dialogue bug and will go resolve it.

I am not convinced the artifact spawning in the refugee center is a bug.

**Comment by mlangsdorf** [comment]
@SeelenJaegerTee would you please test and close the issue if possible?

**Comment by SeelenJaegerTee** [comment]
Downloaded the latest x64 Linux build.
- Mapgen weirdness: can't really test this one on purpose.
- When delivering beer the broker now thanks you properly.
- When accepting the old guard mission it selects a cabin far away (though I wouldn't consider it unrealistically far away from a realism point of view).

To me this issue seems to be fixed.
Many thanks to everyone involved. :+1:
