### ISSUE TITLE
Reproducible CTD with vehicle collision

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#27493]
**Describe the bug**  
Upon colliding with a pair of pregnant cockroaches in my vehicle, the game crashed.

**To Reproduce**  
1. Load the provided save.
2. Without changing course, wait a couple turns.
3. Upon colliding with the cockroaches, the game should crash.

**Expected behavior**  
Strewn cockroach bits, an intact vehicle, and no crash.

**Screenshots**  
![image](https://user-images.githubusercontent.com/19789267/50820203-0d776b00-1367-11e9-8d12-ff228af51ec3.png)
![image](https://user-images.githubusercontent.com/19789267/50820219-15cfa600-1367-11e9-8ef9-4fcf04f61b6a.png)

**Versions and configuration(please complete the following information):**
 - Windows 10 64 bit
0.C-36254, build 8390

[Gearhart.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2735959/Gearhart.zip)

**Comment by ZhilkinSerg** [comment]
![image](https://user-images.githubusercontent.com/16213433/50825898-4bff2c80-134b-11e9-90ee-dc2e9b4332c5.png)

**Comment by ZhilkinSerg** [comment]
Probably need to add `mon_ptr != nullptr` check before doing anything inside of loop:

![image](https://user-images.githubusercontent.com/16213433/50826051-b7e19500-134b-11e9-9efc-ea74f5f43863.png)
