### ISSUE TITLE
NPCs no longer use vehicle beds

### ISSUE THREAD

**Issue by jeremyshannon** [CleverRaven/Cataclysm-DDA#27507]
**Describe the bug**  
Prior to commit 3e0e699db4acff06 (Sleep deprivation added as a mod) npcs would claim nearby beds to sleep in, but afterwards they will just stay in whatever vehicle seat they're in.

**To Reproduce**  
Get a friendly NPC and an RV.
Assign him to the seat in the back, and set his fatigue to 200.
Prior to the commit, he'll move to the bed, afterwards he won't.

**Expected behavior**  
NPCs ought to prefer a bed to a car seat when one's available. I know I would.

**Versions and configuration(please complete the following information):**
 Debian 9 64 bit, using tiles or ascii
 Doesn't seem to matter what mods are loaded. Notably, the Sleep Deprivation mod is NOT loaded.

**Comment by AskaHope** [comment]
Reclining seats counts as beds, so most NPCs won't even bother moving.

**Comment by jeremyshannon** [comment]
This happens with non-reclining seats, though, and the behavior was changed by the merging of the sleep deprivation mod, so I figure it's an unintentional change.
 I'm guessing the new "comfort level" code is making them decide their car seat is good enough. In testing this my NPC wouldn't move a single square to get to a proper bed from a non-reclining seat, though, so it looks like they just won't move anymore.

 On the plus side, this prevents one major trigger for #21811, so yay?
