### ISSUE TITLE
Humble Pie recipe is broken

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#27511]
**Describe the bug**  
You can make this dish even if you have only one of the required offal. 
If you have the required 4 of them, any combination, it will properly consume them duiring crafting. 
But if you have 4 livers/kidneys/lungs and enough flour and water, you can craft it up to 4 times, even if it theroretically requires 16 for that ammount. 
**To Reproduce**  
1. Try to cook Humble pie with only one portion of lung/liver/kidney

**Expected behavior**  
You should,t be able to cook it with only 1/4th of ingridients.

**Screenshots**  
![screen humble pie](https://user-images.githubusercontent.com/43266802/50867772-c0b68300-13ac-11e9-9a38-2c6746f778cb.jpg)

**Versions and configuration:**
 - OS: Windows 10
 - Game Version 0.C-36262-g4a1ab34
 - Graphics version Tiles
 - Mods loaded:

Dark Days Ahead
Disable NPC Needs
Filthy Clothing
Mutant NPCs
Beta National Guard Camp
Sleep Deprivation
Z-levels enabled

**Additional context**  
Any other crafting recipe that uses similar sheme is probably broken too, if there is any.

**Comment by Pupsi-Mupsi** [comment]
I don't know the exact idea behind this recipe and could not find much about it on the internet. Could very well be on purpose.

@KorGgenT
Should the recipe contain all four ingredients or just the right amount?

**Comment by KorGgenT** [comment]
@Pupsi-Mupsi the original idea of it was you could mix and match. this is a very interesting bug that is related to the crafting code, though.

**Comment by ZhilkinSerg** [comment]
Should be fixed with #27952.
