### ISSUE TITLE
Electric Vehicles should display Battery % 

### ISSUE THREAD

**Issue by DaAngus** [CleverRaven/Cataclysm-DDA#27526]
A pure electric Vehicle should display the Battery Charge in percent instead of E....F 
It is much more common right now in EV to show it in percent.

**Comment by Epictyphlosion** [comment]
This sounds more like something that can be added to the options menu, but changing the E...F to a percentage for gas and other tanks as well would be a change I would like, since some cars at least have a "Miles to empty" calculator on the dashboard.

**Comment by Asmageddon** [comment]
As sound as this proposal sounds, it's introducing another extra case into a codebase built of extra cases.

Menu option for bar/percent/mileage sounds pretty nifty though.
