### ISSUE TITLE
Unable to Drop "Butchery refuse" from butchering small animals

### ISSUE THREAD

**Issue by ActualDio** [CleverRaven/Cataclysm-DDA#27532]
**Describe the bug**  
There seems to be a bug where after butchering a small animal corpse I cant drop the butchery refuse that originates from it. I butchered a black rat and saw this happen the first time, but after quitting to the main menu and loading up the save was fine. I saw this a second time after field dressing a dog corpse

**To Reproduce**  
1. Butcher a corpse (Small animals seems to be the cause)
2. Try to drop the butchery refuse that originates with multidrop
3. I cant change the "-" to a "+" and so nothing happens
4. Try to use the inventory and drop it manualy by going into the item description and choosing "drop"
5. The window closes and nothing happens

**Expected behavior**  
I expected it to drop to the floor because it works with animal refuse from deer and and moose and other refuse from the same corpse but from different butchering processes

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-36279-g37f5b05]
 - Graphics version Tiles 
 - Mods loaded: dda, Disable NPC needs, filthy clothing, simplified nutrition, extended realistic guns, makeshift items, medieval and historic content, more survival tools, alternative map keys, more locations, boats, folding parts pack, vehicle additions.

**Comment by jasonmbrown** [comment]
I got this as well, You can get rid of them from inventory but you need to Use the Advanced Inventory System ("/" then move it somewhere else, or Try to Eat it).

 Its a 0 Amount Refuse (There seems to be an issues with the way it determines how much refuse is created, and doesn't work properly on small animals like sewer rats).

You can always debug them away if you don't want them in inventory (Or eat them) Till someone fixes the issue.

**Comment by ign1s-fatuus** [comment]
I am having this bug too. What really sucked is when I tried to remove it via the advanced inventory system and game crashed causing me to loose a good solid of hour of game play.
