### ISSUE TITLE
Large fire extinguisher not working at all. 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#27533]
**Describe the bug**  
Using large fire extinguisher to stop fires does nothing.

**To Reproduce**  
1. Start fire
2.Try to stop fire using extinguisher with "A", or "shift+A" , or "%"

**Expected behavior**  
There should be at least chat message about what is going on.

**Comment by peperov** [comment]
I noticed the same for the small fire extinguisher.
