### ISSUE TITLE
Add ability to set tiles for installed CBMs

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#27548]
Just like with mutations, i want ability to create tiles for bionics when it is installed on player or NPCs.

**Comment by Fris0uman** [comment]
I ve been working on that in the past few days, but it's a slow process since I learn about c++ and CDDA's code as I go. Someone with more experience might pick it up and do it much faster

**Comment by mlangsdorf** [comment]
The relevant logic is [player::get_overlay_ids()](https://github.com/CleverRaven/Cataclysm-DDA/blob/dbc954c9ee9efc2139aea8a45759f15e9c9156a8/src/player.cpp#L11937) .

You'll want to add something like:
```
for( const bionic &bio: *my_bionics ) {
    // this static cast is kind of gross
    const trait_id bio_as_trait( static_cast<trait_id>( bio.id ) );
    auto it = base_mutation_overlay_ordering.find( bio_as_trait );
    auto it2 = tileset_mutation_overlay_ordering.find( bio_as_trait );
    int value = 9999;
    if( it != base_mutation_overlay_ordering.end() ) {
        value = it->second;
    }
    if( it2 != tileset_mutation_overlay_ordering.end() ) {
        value = it2->second;
    }
    mutation_sorting.insert( std::pair<int, std::string>( value, bio_as_trait.str() ) );
}
```
added between the existing get_mutations() for loop and the mutation_sorting for_loop.  Then you'd just need to add the bionic overlays to the tileset data and everything else should fall into place, hopefully.

**Comment by halfahermit** [comment]
@Fris0uman, are you still working on this one? I'm interested in trying it if you're not.

**Comment by Fris0uman** [comment]
Go ahead, sorry for the delay but real life got in the way of my progress
