### ISSUE TITLE
Add bunny death scream

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#27549]
If i recall correctly rabbits and jackrabbits in the real life when they about to die (or really scarred) scream very loud and this sound is horrible.
In the game i didnt noticed it, i didnt think it is happening. I would suggest adding it in the game, so when bunny about to die it screams loudly and attract attention of monsters to the one who killed it.

**Comment by SeelenJaegerTee** [comment]
Sound sample for those interested: https://youtu.be/_xCEMFERDdA?t=65

I'm fine with creatures screaming when they are hit or reaching dangerously low HP.
But what I really hate is for example the grenadier zombie.
Even if you one-shot them with an elephant rifle in the head they somehow manage to activate their on-death effect. Please don't do such monsters.

**Comment by SomeDeadGuy** [comment]
Na-Nah, it is not just in pain, but also when they are scarred. And this scream has less to do with pain, it is more of a warning to other bunnies, so they can run away.
Also i need to post this https://m.youtube.com/watch?v=_WbHjzTmA6o
