### ISSUE TITLE
Canned veggy is only useable in 3 recipes.

### ISSUE THREAD

**Issue by Goran42069** [CleverRaven/Cataclysm-DDA#27556]
I thought canned veggy should be usable in more recipes, currently you can only use it in dudeluxe sandwich, deluxe sandwich and vegetable sandwich. I'd say make it at least on par with pickled veggy. As for balancing i'd say they are close enough ? Canning pots and can sealers are pretty rare i'd say.

**Comment by KorGgenT** [comment]
#27542

**Comment by kevingranade** [comment]
Fixed by #27925
