### ISSUE TITLE
Integrated toolset can not be used for repairs

### ISSUE THREAD

**Issue by logros13** [CleverRaven/Cataclysm-DDA#27562]
**Describe the bug**  
despite containing a welding tool the integrated toolset cannot be used to repair metal/plastic/kevlar objects

**To Reproduce**  
1. spawn a character with an integrated toolset and a damaged metal item.
2. try to repair it with the use % menu.
3. get told that you have no item that can preform that action.

**Expected behavior**  
the bionic welder in the toolset working like any other welder.

**Screenshots**  
![welder exists](https://user-images.githubusercontent.com/20383070/51069888-2c605080-1638-11e9-8818-50210d4fb145.png)

when pressing w
![welder fail](https://user-images.githubusercontent.com/20383070/51069896-4306a780-1638-11e9-9b13-b016e70104f9.png)

**Versions and configuration(please complete the following information):**
- Game Version 0.C-36347-ga6d647a (tiles)

**Comment by Night-Pryanik** [comment]
Duplicate of #19489.
