### ISSUE TITLE
Fires started with an electric firestarter cannot be used as a fire source.

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#27595]
**Describe the bug**  
When I use an electric firestarter to ignite a piece of tinder laying on a brazier, the resulting fire does not count as a fire source to light a kiln or a smoking rack.
All things equal, fires started with: campfire drill, matchbook, lighter, and flint and steel are counted as acceptable fire sources to light a kiln (splintered wood) or a smoking rack (chunks of meat + charcoal).
The electric firestarter I used had a battery compartment mod installed with a charged car battery in it.

**To Reproduce**  
1. Fill kiln and smoking rack with appropriate materials (food+fuel,wood).
1. Place a piece of tinder on a brazier.
2. Light the piece of tinder with an electric firestarter (battery compartment mod + charged car battery).
3. Look (e) at a kiln or a smoking rack and you see a message saying there's nothing to ignite either.

**Expected behavior**  
A fire created with an electric firestarter can be used to ignite a kiln or a smoking rack.
It should not matter how a fire was started when you need a fire source.

**Versions and configuration(please complete the following information):**
 - OS: Manjaro Linux 64-bit
 - Game Version 0.C-36342-g07382221d9-dirty
 - Graphics version Tiles
 - Mods:  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "StatsThroughSkills",
  "more_classes_scenarios",
  "realguns",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "mutant_npcs",
  "npc_traits",
  "more_locations",
  "national_guard_camp",
  "more_buildings",
  "Experimental-Z-Level",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "no_rivtech_guns",
  "modular_turrets",
  "Salvaged_Robots"

**Additional context**  
[Save game](https://www.dropbox.com/s/qgcay6w5ufe720g/Sea%20Bright.zip?dl=0)

**Comment by Night-Pryanik** [comment]
And why do you need an intermediate stuff like fire in the brazier, when you can use electric firestarter directly to fire up the kiln?

Furthermore - tested right now. Got yourself electric firestarter, modded it with battery compartment mod, charged it with a car battery. Debug-wished brazier, filled it with two by four, lighted it up with firestarter. Then dropped firestarter far way from me, had no other sources of fire on me. Got yourself filled charcoal kiln, placed it right next to the brazier. Activated kiln, successfully lighted it up with a fire from brazier.
![default](https://user-images.githubusercontent.com/11132525/51084537-e644e300-1744-11e9-863f-f75088d4ea5c.png)

**Comment by Quintovir** [comment]
Just tested it again and I can use the electric firestarter to light up the smoking rack and kiln. I don't know why it didn't work before.
