### ISSUE TITLE
Disappearing cars 

### ISSUE THREAD

**Issue by LostTombstone** [CleverRaven/Cataclysm-DDA#27606]
**Describe the bug**  
Cars disappear in a area

**To Reproduce**  
1. walk south 
2. cars disappear

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS:  Windows 10 
 - Game Version [from the main menu, e.g. 0.C-36428-g980251]
 - Graphics version [Tiles]
 - Mods loaded [disable npc needs, filthy clothing, simplified nutition, craftable gun pack, deadleaves fictional guns, extended realistic guns, icecoons arsenal, medieval and historic content, more survival tools, mythological replicas, modular turrets, salvaged robots, alt map keys, beta national guard camp, more locations, map gen demo, urban development, vehicle additions pack, tanks and other vehicles
[O'Fallon.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2753839/O.Fallon.zip)
]

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by Solusphere** [comment]
Attaching the screenshots related to this issue posted in Discord:
https://cdn.discordapp.com/attachments/252368987210514433/534182925986430987/unknown.png
https://cdn.discordapp.com/attachments/252368987210514433/534182973424140303/unknown.png

**Comment by kevingranade** [comment]
This is caused by the same issue as the crash in #27600 
If the new map memory cache code writes outside the cache, it can invalidate some of the vehicle cache which causes this issue.
