### ISSUE TITLE
Ether recipe is completely impractical and prohibitive to crafting anesthetic kits

### ISSUE THREAD

**Issue by FoolsGold45** [CleverRaven/Cataclysm-DDA#27603]
**Is your feature request related to a problem? Please describe.**  
Obviously everything related to autodocs and CBMs are still in flux at this point, but there's one part of the puzzle that gets stuck in my craw more than most of them. A player who gets RNG-screwed out of finding anesthetic kits to install CBMs has no choice but to craft them by hand. The recipe for anesthetic kits itself is reasonable (with one exception), but the recipe for the Ether ingredient is absolutely not.

In the math section at the bottom, I've calculated that it takes just shy of twenty hours of straight crafting from common materials to make enough ether for a single anesthetic kit craft, which makes 3 kits. Ridiculously long crafting times for a resource that can be burned through extremely quickly is pure tedium and the reason that constructions like the charcoal kiln were implemented, because the player previously needed to spend hours staring at wood burning while getting nothing else done.

**Describe the solution you'd like**  
The quick and dirty solutions would be to:
a) Decrease the time required for the ether recipe down to something more reasonable. My initial suggestion is to match the ethanol craft recipe, which takes a half hour per for a total of 5 and a half hours for a batch of 11. Still a heavy time investment, but not unreasonably so for a well-stocked survivor. Drawbacks are that the realism of the distilling process may be compromised (I'm no chemist, I don't know how long it takes in real life).

b) Increase the amount of ether received from a recipe, but also proportionally increase the ingredients required, without changing production time. Essentially, increase the input and output of a single craft of the recipe from 250mL to something like 750mL. This would reduce the craft time to roughly 5 and a half hours but let the player make "more at once". Gameplay-wise, there is no reason that anyone would want small amounts of ether - the only recipe it's used for is anesthetic kits where it requires 2700mL. Disadvantages: Again, chemistry knowledge is lacking, but maybe 250mL per 1 and a half hours is just the rate that this happens at, and this would be ruining realism again?

The more involved, but preferable solution would be to treat ether production like alcohol or charcoal creation: get the ingredients, set it up on the ground as a construction or placed item, go off and do other things for 14 hours or however long it takes, and collect the finished batch of ether when it's done, ready to package into anesthetic kits. Times and ingredients may remain the same, but the player is not left standing there, getting nothing done and slowly starving while waiting 2/3rds of a day for the ether distillation to finish.

**Related problem-anesthetic kit volume**
The recipe for 3 anesthetic kits takes 2.7 liters of ether, presumably packaged in the 3L glass jar that the kit recipe also requires (and notably doesn't give back after the kits are used). Three anesthetic kits take up only .25 liters of space despite its ingredients . Additionally, despite the 3L jar theoretically "containing" the liquid anesthetic, the three kits can be stacked and separated into groups not divisible by 3. This makes no rational sense, and this part of the recipe needs to be radically changed as well.

**Math**  
The anesthetic kit (which produces 3 units) takes 5 minutes to craft and requires 2700 units of ether, an item that from my experience does not naturally drop in the game.
Ether is crafted in batches of 250, which means that 11 batch crafts are needed to make enough ether for a single anesthetic kit craft.
The recipe for a single craft of ether is 1 hour and 20 minutes. 

A batch of 11 ether crafts takes 14 hours and 40 minutes straight.

But wait, the ether recipe itself calls for 2700 units of ethanol. This item does spawn in the world, but if we go with a worst-case scenario where the player hasn't found enough of that, we go back into the crafting menu to brew up our own.

A batch of 11 ethanol crafts, using its own recipe and not as a byproduct of methanol for simplicity's sake, takes 5 hours and 30 minutes. The material components also call for 110-154 units of beer or liquor, which could in itself require even more preparation, but we'll stop here for now and assume that the player has raided a bunch of liquor stores and won't need to make those by hand.

Total times: 5 hours 30min to craft ethanol + 14 hours 20min to craft ether + 5min to craft the kit itself = **19 hours and 55 minutes** of the player standing still in the same place and doing very little but staring at chemicals distilling. All for 3 uses of anesthetic kit, which give a chance (a CHANCE) of correctly installing a CBM at an autodoc.

**Comment by Barhandar** [comment]
While the IRL recipes I've searched consistently fail to mention how long it takes total to get ether out of ethanol+acid (acid is also a catalyst), some of them _do_ mention how long specific phases take. Drying ether to anhydrous state takes 24h + distillation time; and reaction itself apparently proceeds at rate of 2 drops per second. No, the recipe doesn't mention how much a drop is.

Ether distillation also happens in the 31-36dC range, as opposed to ethanol which distills on about 78-94dC range, so it's somewhat faster and takes less fuel.

**Comment by Mecares** [comment]
Since Ether is commonly used in chemistry it could be spawning in labs.
It is used as a starting fluid so maybe small bottles of it could be spawning in gas stations.

**Comment by Zireael07** [comment]
Spawning it in labs is a good idea, +1.

**Comment by kevingranade** [comment]
> reaction itself apparently proceeds at rate of 2 drops per second.

My mistake, it's not the distillation gear that would need duplication, but the catalyst and reaction vessel, which is much worse.

Still, the best option for the recipe is making the reaction and distillation an unattended process.

**Comment by thethunderhawk** [comment]
IMO finding it in starting fluid at gas stations is a good idea, though it’s probably not 100% Ether IRL. IIRC that used to be a common thing for making homemade meth, stealing starter fluid from gas stations...

**Comment by KorGgenT** [comment]
just because something is hard to do, does not mean it isn't supposed to be that way.
Ether was originally only supposed to be one way of getting anesthetic kits, and a very resource intensive one, at that. There may yet be other recipes for anesthetic kits that are not ether. However, i see no issue with ether as it is right now.
