### ISSUE TITLE
Segmentation Fault (Tile Related?)

### ISSUE THREAD

**Issue by jasonmbrown** [CleverRaven/Cataclysm-DDA#27600]
**Description**
Segmentation Fault occurs when walking below a certain point on the map

**Reproduce**
1)Load the save file that's included at the bottom of this issue.
2)Walk right to the road
3)Walk down to the shady Zombies
4)Segmentation Fault. (There is a screenshot as well In the Additional Info that shows the Rough location where the Segfault occurs)

**Additional Info**
VERSION: 0.C-36428-g9802051
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5CD6A5[cataclysm-tiles.exe+0x1CD6A5]
    @0x5CE252[cataclysm-tiles.exe+0x1CE252]
    SMPEG_error+0x4B034@0xE666D0[cataclysm-tiles.exe+0xA666D0]
    _C_specific_handler+0x8C@0x77417398[ntdll.dll+0x57398]
    _chkstk+0x9D@0x7742BF9D[ntdll.dll+0x6BF9D]
    RtlInitializeResource+0x53A@0x774004CA[ntdll.dll+0x404CA]
    KiUserExceptionDispatcher+0x2E@0x7742B63E[ntdll.dll+0x6B63E]
    @0xD6E56B[cataclysm-tiles.exe+0x96E56B]
    @0xD6F9AE[cataclysm-tiles.exe+0x96F9AE]
    @0x8B49BE[cataclysm-tiles.exe+0x4B49BE]
    @0x6F4668[cataclysm-tiles.exe+0x2F4668]
    IMG_LoadWEBP_RW+0x4CC7C9@0x1445599[cataclysm-tiles.exe+0x1045599]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0xD@0x771B59CD[kernel32.dll+0x159CD]
    RtlUserThreadStart+0x1D@0x7741383D[ntdll.dll+0x5383D]

**Settings**
Soundpack: 2ch sounpack https://drive.google.com/drive/folders/1e7NAT07njV5TkxnQxpo4nxeI0RfpN25N

Tileset: MSX++DeadPeopleEdition

Version: Windows 7 64-Bit, Tiles

Mods: Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Makshift Items Mod, More Survival Tools, Modular Turrets, Salvaged Robots, Alternative Map Key, Mining Mod, Mutant NPCs, Beta National Gaurd Camp, Big River Building Pack, More Locations, Fuji's More Buildings, Oa's Additional Buildings Mod, Boats, Folding Parts Pack, Vehicle Additions Pack, Tanks and Other Vehicles, Classes and Scenarios Mod, StatsThroughSkills 

Screenshot Of Crash Location: https://i.imgur.com/PJ6AMdK.png
Screenshot Of Vertical Position (crashes if you move south further): https://i.imgur.com/mKvQLDJ.png
Save File: http://www.dropbox.com/s/s47b9lapyo72ufv/Crash.rar?dl=0

**Comment by jasonmbrown** [comment]
Yes It happens every time on my system (reproduced it 5-6 times). If theres any other information I can provide to assist let me know.

**Comment by ZhilkinSerg** [comment]
I can confirm I can reproduce it, but not under debugger yet.

**Comment by nulman** [comment]
i think im having the same issue, do you guys want my save as well?

**Comment by ZhilkinSerg** [comment]
Caused by #27457.

**Comment by ZhilkinSerg** [comment]
> 
> 
> i think im having the same issue, do you guys want my save as well?

Thanks. It is not neccessary right now.

**Comment by DSeyka** [comment]
Was crashing for me with the same stack trace in build 8417, looks like it doesn't with 8149.

**Comment by DSeyka** [comment]
![image](https://user-images.githubusercontent.com/34726992/51107841-28cbf580-1801-11e9-8182-f0e41a88b50c.png)
Nope, still does.

**Comment by settdigger** [comment]
Is there a version where this is less likely to happen?

**Comment by ZhilkinSerg** [comment]
https://ci.narc.ro/job/Cataclysm-Matrix/8416/

**Comment by edusaraiva** [comment]
I think I am having the same problem.

CRASH LOG FILE: config/crash.log
VERSION: 0.C-36451-g391e3a0
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5CD685[cataclysm-tiles.exe+0x1CD685]
    @0x5CE232[cataclysm-tiles.exe+0x1CE232]
    SMPEG_error+0x4B034@0xE66160[cataclysm-tiles.exe+0xA66160]
    _C_specific_handler+0x98@0x7FFC98847C58[msvcrt.dll+0x27C58]
    _chkstk+0x11D@0x7FFC9B45F7DD[ntdll.dll+0x9F7DD]
    RtlWalkFrameChain+0x13F6@0x7FFC9B3CD856[ntdll.dll+0xD856]
    KiUserExceptionDispatcher+0x2E@0x7FFC9B45E70E[ntdll.dll+0x9E70E]
    @0xD6E07B[cataclysm-tiles.exe+0x96E07B]
    @0xD6F4BE[cataclysm-tiles.exe+0x96F4BE]
    @0x8B451E[cataclysm-tiles.exe+0x4B451E]
    @0x6F4398[cataclysm-tiles.exe+0x2F4398]
    IMG_LoadWEBP_RW+0x4CC7C9@0x1445029[cataclysm-tiles.exe+0x1045029]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFC98D33034[KERNEL32.DLL+0x13034]
    RtlUserThreadStart+0x21@0x7FFC9B433691[ntdll.dll+0x73691]

**Comment by Hulkninja** [comment]
I'm having this exact same bug with the latest experimental release. Been having it for a few days now, at least. I can't say for sure, since the first couple of days I was exclusively playing the "lab patient" scenario, so I never travelled far enough to encounter it.
