### ISSUE TITLE
Combustion engine realism (fine tuning)

### ISSUE THREAD

**Issue by GearheadLydia** [CleverRaven/Cataclysm-DDA#27610]
Power figures for combustion engines are, as of a fairly recent version, listed in watts, instead of arbitrary units. This is a completely sensible decision that I am 100% behind.

That said, the newfound legibility of the power outputs makes it more obvious that the existing engines are underpowered. A lot of the engine power measurements look accurate for the early 1980s, not 2018 - much less 2041, unless there has been a serious regression in fuel injection technology or a clamp-down in fuel economy. (But at that point, why are the per-cylinder displacements so high, besides 'Murica?)

In any case, the rated specific output is far lower on any of CDDA's engines than should be suggested by even a stagnation from current trends.

(All engines described are naturally aspirated gasoline engines)

2.5L four-cylinder in 2018: ~185HP (2018 Mazda3 2.5L, 2016 Honda Accord EX-L 4cyl)
2.5L four-cylinder in CDDA: 93 kW, or about 125HP, maximum
CDDA power as a percentage of 2018 power: ~68%

4.0L V6 in 2018: ~300HP ('19 Toyota Tacoma V6: 280HP; 3.7L in '19 Nissan 370Z: 332HP)
4.0L V6 in CDDA: 149kW, or about 200 HP, maximum
CDDA/2018: ~67%

6.5L V8 in 2018: ~420HP ('14 Ford F150 6.2: 411HP, '16 Corvette Z51 6.2: 455HP, '15 Dodge 6.4: 485HP)
6.5L V8 in CDDA: 243kW, or about 325HP, maximum
CDDA/2018: ~77% (better!)

Going to leave out the 12.0L V12, because the only thing close to comparing is the 8.0L Viper V10, or maybe two of the V8s listed above joined together; but either the displacement is enormous (which it is), or 600HP is actually unimpressive out of an engine of that size.

I'm not 100% sure what the correct answer is, here, for balance. We could just as easily reduce the labeled displacements so that the existing engines are commensurate with their existing power output; or we could bump up the power.

I also understand that the vehicle code in the engine is going to need a lot of revisions, so I am concerned while submitting this issue that this is kind of putting the cart before the horse; but I figured I would mention this now, in case the balance discussion ends up mattering later.

**Comment by Epictyphlosion** [comment]
That reminds me, I need to add a V10 and a V10 sports car, lol

**Comment by kevingranade** [comment]
> much less 2041

It's not 2041, it's 2019.  Mundane technologies are modern, not future.

For a quick fix I'd recommend dropping the displacements and keeping power outputs where they are.  There are various reasons power outputs are at the current levels, but displacements AFAIK are completely arbitrary.

**Comment by GearheadLydia** [comment]
> For a quick fix I'd recommend dropping the displacements and keeping power outputs where they are. There are various reasons power outputs are at the current levels, but displacements AFAIK are completely arbitrary.

Makes complete sense. For a quick fix, I'd suggest dropping the I4's displacement to 1.6L, the V6's to 2.7L or 2.8L, and the V8's to 4.0L-5.0L - all common displacements. The V12 should probably be something like 7.0L-8.0L, but the only real points to compare that I have for engines that big are the Lister-Jaguar V12 (7.0L, ~600HP) and, again, the Viper V10.

I actually think it may be a good idea in the long run to reintroduce varying engine displacement, which I remember from some very old version or other. I'd also suggest introducing a "tune" variable, whereby an engine of a given displacement can make more power, at the cost of a greater amount of fuel efficiency and probably also some reliability (are engine breakdowns a thing right now?).

> That reminds me, I need to add a V10 and a V10 sports car, lol

I have for a long time toyed with the idea of making a "variety pack" mod that adds a lot to current vehicle content, including probably rebalancing the existing cars, but at this point I'm thinking I may wait to see where the revisions to the vehicle system go before starting to put anything solid down.

**Comment by GearheadLydia** [comment]
> I don't want to introduce varying engine displacement. [...]

Fair enough; I can respect that. I remember the displacements in the old game being unnecessarily messy and lopsided.

> I don't have a problem with multiple fixed engine sizes: "1.6 i4 engine", "2.0 i4 engine", "2.2 i4 engine", "2.2 i4 turbo-supercharged engine". That gives us precise control over weight, volume, power, and consumption in a way we wouldn't have from varying displacements.

Makes sense -- although I'm a little hesitant to clutter up the vehicle parts menu more than it already is, which is why I was inquiring about doing it as a varying displacement kind of thing.

If there are multiple engines of a type close enough by to install one of them, I feel like it'd make sense to have it ask you which one you want to use when you start installing it, like when you have held and nearby items. (If this would actually be harder to implement than I'm thinking it is, then I retract this element of this suggestion :stuck_out_tongue: )

**Comment by kevingranade** [comment]
Adressed by #29775
