### ISSUE TITLE
Encryption Codes mission creates workstation consoles where they shouldn't be

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [CleverRaven/Cataclysm-DDA#27618]
**To Reproduce**  
0. Observe "By Cycle"
1. Talk to the Doctor
2. Get a mission to get encryption codes from him
3. "By Cycle" dungoofed into a random number of consoles.

**Expected behavior**  
A mission should not take less than 5 seconds to complete.

**Screenshots**  
![Before](https://vgy.me/RO4aFE.png)
![After](https://vgy.me/BJi0Sc.png)

**Versions and configuration(please complete the following information):**
 - OS: Win7
 - Game Version: 8408, 8409, 8419
 - Mods loaded:
```json
[
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "more_classes_scenarios",
  "no_reviving_zombies",
  "DP_XOTTO_INDICATORS",
  "blazemod",
  "Tanks",
  "deoxymod",
  "boats",
  "Urban_Development",
  "oa_additional_buildings_mod",
  "more_locations",
  "FujiStruct",
  "national_guard_camp",
  "alt_map_key",
  "mutant_npcs",
  "modular_turrets",
  "Salvaged_Robots",
  "no_religious_Texts"
]
```

**Additional context**  
Save ZIP: [save.zip](https://mega.nz/#!O010xATb!-y4CMidcJ-VJm88IiU6WBbs40QQpSpF-Hteey25Fp7E)

**Comment by DeltaEpsilon7787** [comment]
UPD: Those consoles are spawned in different places and different quantities each time. This may or may not be a memory issue as such._

**Comment by Zireael07** [comment]
Car getting deleted is another issue, already reported.

**Comment by Qrox** [comment]
I haven't tested it, but this could probably happen if there aren't any research facilities nearby in a given range:

https://github.com/CleverRaven/Cataclysm-DDA/blob/abbd9f7c9509d785dda131e2fd89360c45edd75a/src/mission_start.cpp#L650-L659

At line 655, the range to find lab stairs in is set to '0', meaning a 'whole overmap diameter', as shown here (line 944):

https://github.com/CleverRaven/Cataclysm-DDA/blob/663942f2c56624499bc5742be0ede575b8f08c85/src/overmapbuffer.cpp#L939-L944

The value of OMAPX is 180, defined here:

https://github.com/CleverRaven/Cataclysm-DDA/blob/1a3874731d920a116c065a67edbec79b18aebb14/src/game_constants.h#L48-L51

However, if no lab stairs are found, the return value is instead the current overmap tile the player is in (line 330):

https://github.com/CleverRaven/Cataclysm-DDA/blob/0fdcdc3f824dcd0cb204c9d9be76c5873981560d/src/mission_util.cpp#L321-L331

The following code then searches for labs 2 z-levels beneath the player in a 4-overmap-tile range, which obviously do not exist, so the location of the player is again returned.

https://github.com/CleverRaven/Cataclysm-DDA/blob/abbd9f7c9509d785dda131e2fd89360c45edd75a/src/mission_start.cpp#L612-L618

The end result is that the consoles are placed just nearby the player, as described in the OP.

**Comment by gcaliber** [comment]
The issue appears to be that hidden labs are not spawning/far too rare for one to be found to place the console most of the time.

**Comment by PatrikLundell** [comment]
0.E2 stable: All the doctor lab missions were bugged for me.
- The first one showed a lab location, but the actual console was generated two levels deeper than the level marked, but at the same location. If I remember correctly, two identical consoles were generated next to each other.
- The second one generated a console on the path up to the refugee center, while showing a location down in the central lab. There wasn't any console anywhere in that lab.
- The third one was two tiles north of the location specified, inside a lab my character had visited earlier (in a desperate search for a working centrifuge, as the ones in the hospitals visited seemed to be the first thing zombies smashed). The level was the correct one, though.
- The ice lab one was indeed in an ice lab, at the top lab level where the marker indicated it should be. The quest, however, indicated it would be at level four.
- The rail console was an added function to the rail console in the same lab as the third one, while the marker was higher up and not directly above. No new console spawned at the indicated location.

**Comment by int-ua** [comment]
Please add more context to the description. Steps to reproduce are not clear enough.
