### ISSUE TITLE
bionic sniper starts with incompatible extra magazines

### ISSUE THREAD

**Issue by logros13** [CleverRaven/Cataclysm-DDA#27613]
**Describe the bug**  
The RM11B scout rifle that the bionic sniper starts with uses RMGP10 (which it comes pre loaded with) and 25 magazines but the extra magazines they start with in the chest rig while containing the right ammo are RMGP50 incompatible with the rifle.

**Expected behavior**  
The extra magazines being compatible with the rifle suggestively by making all three magazines RMGP25 magazines, this would bring the total starting ammo down to 75 from 110 but that's a fairly trivial nerf.

**Versions and configuration(please complete the following information):**
 - Game Version 0.C-36419-gd7a0f0c (tiles)

**Comment by Pupsi-Mupsi** [comment]
I'll fix that!
