### ISSUE TITLE
Changing state of worn filthy gear causes error 'Morale "Filthy Gear" is inconsistent.'

### ISSUE THREAD

**Issue by utechenko-v** [CleverRaven/Cataclysm-DDA#27619]
**Describe the bug**  
Error message displayed : Morale "Filthy Gear" is inconsistent. (morale of filthy gear),
Few turns after changing state or waring/taking off filthy gear (e.g. riot helmet)
(in Russian localization - similar error message)

**To Reproduce**  
1. Start a game (build ~ 0.C-8386 win tiles)
2. Wear filthy riot helmet
3. Activate filthy riot helmet to raise visor

**Expected behavior**  
There must be no error messages displayed;
Filthy Clothing morale shall be calculated correctly.

**Screenshots**  
![morale cpp-bug](https://user-images.githubusercontent.com/16246933/51134321-e37ae880-183f-11e9-8c6c-5df3ce05182c.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-36249-g7de8b69
 - Graphics version Tiles
 - Mods loaded: Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition

**Additional context**  
debug.log fragment:
`src/morale.cpp:480 [player_morale::consistent_with(const player_morale&) const::<lambda(const player_morale&, const player_morale&)>] Morale "Грязная одежда" is inconsistent.
00:26:24.053 ERROR : (error message will follow backtrace)
	(@0x5506fc[cataclysm-tiles.exe+0x1506fc]), 
	(@0x550a5e[cataclysm-tiles.exe+0x150a5e]), 
	(@0x5512b3[cataclysm-tiles.exe+0x1512b3]), 
	(IMG_LoadWEBP_RW+0x110f8b@0xd8e44b[cataclysm-tiles.exe+0x98e44b]), 
	(@0x88469d[cataclysm-tiles.exe+0x48469d]), 
	(@0x8847a2[cataclysm-tiles.exe+0x4847a2]), 
	(@0x97de9d[cataclysm-tiles.exe+0x57de9d]), 
	(@0x5f85e9[cataclysm-tiles.exe+0x1f85e9]), 
	(IMG_LoadWEBP_RW+0x47010c@0x10ed5cc[cataclysm-tiles.exe+0xced5cc]), 
	(@0x4013e2[cataclysm-tiles.exe+0x13e2]), 
	(BaseThreadInitThunk+0x24@0x743b8484[KERNEL32.DLL+0x18484]), 
	(RtlAreBitsSet+0x88@0x76ee3ab8[ntdll.dll+0x63ab8]), 
	(RtlAreBitsSet+0x58@0x76ee3a88[ntdll.dll+0x63a88]), 
Backtrace emission took 0 seconds.`

**Comment by Zireael07** [comment]
What does Грязная mean? I know одежда is clothing...

**Comment by DeltaEpsilon7787** [comment]
Dirty clothing.

**Comment by Night-Pryanik** [comment]
More precisely "Filthy Clothing".

**Comment by Night-Pryanik** [comment]
@utechenko-v did you test it in English? Does the game throws the same error in this case?

**Comment by utechenko-v** [comment]
@Night-Pryanik yes, in English for the same saved game bug is reproducible, 
` DEBUG    : Morale "Filthy Gear" is inconsistent.
 
 FUNCTION : player_morale::consistent_with(const player_morale&) const::<lambda(const player_morale&, const player_morale&)>
 FILE     : src/morale.cpp
 LINE     : 480`
![morale cpp-bug-en](https://user-images.githubusercontent.com/16246933/51163311-e73f5700-18a1-11e9-9c99-ae5226d3e99e.png)

**Comment by ZhilkinSerg** [comment]
Old bug - https://discourse.cataclysmdda.org/t/5141-persistent-debug-messages-from-morale-calculations/12121

**Comment by MetroidHunter** [comment]
If no one else gets around to it, I plan to look at this one sometime this week after looking at 27487

**Comment by kevingranade** [comment]
Fixed in #28067
