### ISSUE TITLE
CTD when approaching "Missing Caravan" mission location.

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#27621]
**Describe the bug**  
When I approached the "Missing Caravan" mission location I had a CTD.
**To Reproduce**  
Drive towards the mission location.
**Expected behavior**  
No crashes.
**Screenshots**
![crash when approaching caravan mission](https://user-images.githubusercontent.com/28264543/51180429-eb617980-188d-11e9-99b0-d33bfa54267c.png)

**Versions and configuration:**
 - OS: Manjaro Linux 64-bit
 - Game Version 0.C-36342-g07382221d9-dirty
 - Graphics version Tiles
 - Mods:  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "StatsThroughSkills",
  "more_classes_scenarios",
  "realguns",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "mutant_npcs",
  "npc_traits",
  "more_locations",
  "national_guard_camp",
  "more_buildings",
  "Experimental-Z-Level",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "no_rivtech_guns",
  "modular_turrets",
  "Salvaged_Robots"

**Additional context**  
[Save game](https://www.dropbox.com/s/lanp51ml2c5kx1s/Sea%20Bright.zip?dl=0)
**Crash log**
https://pastebin.com/CsxcABH1

**Comment by ifreund** [comment]
could not reproduce on macOS 10.14.2 with the latest version 0.C-36502-g59a72789a6 built using clang.  What did you use to compile?  What did you change to make your version "dirty?"

**Comment by Quintovir** [comment]
This might answer your question. Here's the script I use to update my game:

```
#!/bin/bash

repo=("/home/user/Cataclysm-DDA")

cd "${repo}"
git pull
make clean
make -j14 RELEASE=1 TILES=1 SOUND=1 LUA=1 USE_XDG_DIR=1
./cataclysm-tiles
```

This is the script I used to make/install the game:
```
#!/bin/bash

repo=("/home/user/Cataclysm-DDA")

git clone --depth 1 git://github.com/CleverRaven/Cataclysm-DDA.git
cd "${repo}"
make -j14 RELEASE=1 TILES=1 SOUND=1 LUA=1 USE_XDG_DIR=1
./cataclysm-tiles
```

> What did you change to make your version "dirty?"

I think it's from my manually putting the soundpacks in the sound folder and/or adding the "VeraMoBd.ttf" font in the font folder.

**Comment by ifreund** [comment]
> I think it's from my manually putting the soundpacks in the sound folder and/or adding the "VeraMoBd.ttf" font in the font folder.
Yep that would do it.

It looks it might be a gcc thing then, I'll try to get my gcc setup again on mac and see if it crashes.  What version of gcc are you using?

**Comment by Quintovir** [comment]
I have these installed:
gcc Version 8.2.1+20181127-1
gcc-libs Version 8.2.1+20181127-1
lib32-gcc-libs Version 8.2.1+20181127-1

**Comment by ifreund** [comment]
Hmm, compiled with gcc 8.2.0 (latest version for mac) and still can't reproduce.  Don't currently have a linux box setup so I guess you're gonna have to wait for someone else.  Last thing I would try is updating your game in case something in the last 3 days fixed the crash.

**Comment by Quintovir** [comment]
> Hmm, compiled with gcc 8.2.0 (latest version for mac) and still can't reproduce. Don't currently have a linux box setup so I guess you're gonna have to wait for someone else. Last thing I would try is updating your game in case something in the last 3 days fixed the crash.

Looks like an update fixed it.
Thanks.
