### ISSUE TITLE
Heatmap for time spent in overmap tiles

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [CleverRaven/Cataclysm-DDA#27634]
**Is your feature request related to a problem? Please describe.**  
Putting down notes on a map is a huge pain in the ass when it comes to more regular notes like marking the buildings you've visited, safe off-road paths and such. Putting notes down should be reserved for uncommon things, like roadblocks on the road, minefields and various other things.

**Describe the solution you'd like**  
There is a debug command, "Display overmap scents" displays visited overmap tiles by the player and even colors them based on the how long ago you were there.
I suggest making an off-shoot of this feature -- a heatmap of time spent spent in overmap tiles.

This will help tracking down your progress massively: not only will you avoid visiting the same place over and over when exploring, but you also may be able to be extensive in your looting.

You need to spend generally more time in an overmap tile if you intend on looting it and this will easily document your progress automatically.

Additionally, a counter for the amount of times you _enter_ or, conversely, exit may also help a lot in tracking safe routes even if you don't spend much time in them, such as the case with using a vehicle.

**Considered alternatives**
Ultimatively, this is nothing more than a QoL feature. There are indeed in-character and in-game ways to do this, but all of them are _very_ tedious for the player to use. Heatmap, while useful, does not provide a lot of context, but most of the time, you can guess the context accurately just by knowing what kind of tile this is and that's all that matters.

Also burning houses down is, while **!!FUN!!**, slows the game down, take quite a bit of in-game time and, unfortunately, you can't leave the reality bubble and expect the building to be burned down.

**Additional context**  
![Rough draft of the feature](https://vgy.me/mHuiWe.png)

It also looks pretty cool, to see the character's story like that.

**Comment by ZhilkinSerg** [comment]
Cataclysm is orginally curses based, so we have only 16 colors, therefore internal visualization would be almost off-limits.

It is possible to get that data for external visualization tool using simple Lua mod without additional code change (save location data using `on_turn_passed` or other time related callback), still you would need to develop external visualizer.

**Comment by DeltaEpsilon7787** [comment]
There is no need for a full scale anyway. A 2D histogram would be just as useful.

**Comment by ZhilkinSerg** [comment]
> In short, 16 ranges is quite enough for all intents and purposes.

Maybe, but that is 16 different colors, not 16 shades of one color. Anyway , that is only true for CURSES build and we can use any colors in TILES/SDL build.

**Comment by DeltaEpsilon7787** [comment]
You don't really several shades of the same color though. Red-orange-yellow-green-cyan-blue-violet is understandable to everybody.

**Comment by Leland** [comment]
This is an interesting concept but I think would probably be better suited for an external program. Covering up paths and buildings with random colors would be really difficult to convey to players as a heatmap.

**Comment by DeltaEpsilon7787** [comment]
>Covering up paths and buildings with random colors would be really difficult to convey to players as a heatmap.

Perhaps it's possible to alleviate this by changing the background color of map characters and using the inverted color as the foreground color?
