### ISSUE TITLE
Sort items slow down. Caused by Full Zone

### ISSUE THREAD

**Issue by jasonmbrown** [CleverRaven/Cataclysm-DDA#27630]
**Describe the bug**  
If you run out of space on a Sorting-Zone, Sorting Items slows to a crawl. (Assume that Its rechecking for Space on Every Single item, Instead of Ignoring them after checking once)

**To Reproduce**  
1. Get a full tile of two by fours (200 or so)
2. Get 2 full tiles of Other Junk
3. Create a zone to sort Wood (For the Two by Fours)
4. Create a Zone to Sort Other Items
5. Sort Items
6. After the "Other" Items zone is full, the sorting of the Two by Fours will slow to a crawl

**Expected behavior**  
Sort should only check items once for space (recheck if the item is smaller then last sorted item to that zone). If no Space then ignore till Next time Sorting is started.
I assume this was simply an oversight on the Zone Sorting.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7 64-Bit
 - VERSION: 0.C-36428-g9802051
 - Graphics version: Tiles 
 - Mods loaded: "dda",  "no_npc_food",  "filthy_morale",  "novitamins",  "makeshift",  "More_Survival_Tools",  "modular_turrets",  "Salvaged_Robots",  "alt_map_key",  "Mining_Mod",  "mutant_npcs",  "national_guard_camp",  "BIGRIVER",  "more_locations",  "FujiStruct",  "oa_additional_buildings_mod",  "boats",  "deoxymod",  "blazemod",  "Tanks",  "more_classes_scenarios",  "StatsThroughSkills"

**Additional context**  
[Savegame](https://www.dropbox.com/s/esezw7eub40zr6z/save.rar?dl=0)
Open Save and Sort Items (The Display rack will fill up and the Two by fours will take a LONG time to sort)

**Comment by ifreund** [comment]
Confirmed on macOS 10.14.2 with version 0.C-36502-g59a72789a6.  Will investigate solution.
