### ISSUE TITLE
cannot resize some items when you are a small mouse

### ISSUE THREAD

**Issue by nulman** [CleverRaven/Cataclysm-DDA#27641]
*SOME* items cannot be downsized (when you are a tiny mouse)
you either get "you wont learn anything form this"  if your skill is high or you will try to resize it forever if you skill is low enough
items tested include: backpacks, scabbard, spear strap, wrist bandolier

**To Reproduce**  
have a small mutation like "unassuming"
obtain a leather backpack
use a sewing kit on it
get sad.

**Expected behavior**  
stuff marked as downsizable in the crafting menu should, in fact, be resizable

**Screenshots**  
![image](https://user-images.githubusercontent.com/7602897/51204106-76348980-190b-11e9-9870-bd6befb222d7.png)

**Versions and configuration(please complete the following information):**
windows 10, 64bit Tiles
build 8421

**Comment by MetroidHunter** [comment]
I plan to look at this later in the week

**Comment by MetroidHunter** [comment]
When we print the information of an item, we assume that if something is wearable then it is refittable which seems counter to the option of VARSIZE that marks things resizable. The `leather backpack` item is in fact not refittable so I am going to refactor how we determine what messages to print on items that fit, dont fit, are oversized, or are undersized. Resizability will then be printed separately in a hope to give the user more accurate information.

**Comment by jbytheway** [comment]
This logic (of determining the size of clothing relative to a player) is duplicated in various places.  I had thought in the past that it would make sense to centralize it in one function that returns an enum of the various possibilities.

**Comment by MetroidHunter** [comment]
> This logic (of determining the size of clothing relative to a player) is duplicated in various places. I had thought in the past that it would make sense to centralize it in one function that returns an enum of the various possibilities.

This is what I have done however, there are discrepancies that I am working through atm around FIT, UNDERSIZED, and OVERSIZED. They are not exactly related owing to how the system has evolved
