### ISSUE TITLE
Items are not consumed in recipes if one of the componets contains something. 

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#27649]
**Describe the bug**  
Crafting items do not consume the item if one of the materials used contains other items. Ex. If you have a cardboard box of something and your making fire hardened arrows you can use the cardboard box but it never gets consumed in the recipe I assume this is because the contained item would change type? 

**To Reproduce**  
1. Make player with items needed to craft fire hardened arrows. One of them being a cardboard box full of something. ( might need to be frozen ) 
2. Make fire 
3. Craft arrows. 

**Expected behavior**  
Either the box needs to not be an option or the box needs to be consumed and the item in the other inventory its pulled from needs to change to the non boxed type. 

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux x64 
 - Game Version: 0.C-36276-g8abfd82651
 - Graphics version: Does not matter
 - Mods loaded: None

**Comment by DracoGriffin** [comment]
Seems related to #26928 but with more information.
