### ISSUE TITLE
Bike Racks remove Vehicle Zones

### ISSUE THREAD

**Issue by MisterWytt** [CleverRaven/Cataclysm-DDA#27645]
**Describe the bug**  
Vehicle Zones get removed whenever it's attached to a bike rack. For example, if I have the Unsorted tag on a shopping cart, and I attach said cart to a Bike Rack, the zone is lost and will need to be re-placed again to make it react to other zones.

**To Reproduce**  
1. Place a Vehicle Zone on your Shopping Cart
2. Attach it to your Vehicle's Bike Rack.
3. Watch as the Zone disappears from said Shopping Cart.

**Expected behavior**  
The Vehicle Zone should be persistent and static and not temporary. It should stay on the Shopping Cart. You should not have to re-add the Vehicle Zone to said cart every time you load or take off a vehicle from a Bike Rack

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 64-bit
 - Game Version 0.C-36419-gd7a0f0c (tiles)
 - Graphics version Tiles
 - Mods loaded DDA

**Comment by MetroidHunter** [comment]
I plan to look into this issue tomorrow

**Comment by kevingranade** [comment]
Fixed by #28054
