### ISSUE TITLE
light eater doesnt cancel rapid metabolism

### ISSUE THREAD

**Issue by nulman** [CleverRaven/Cataclysm-DDA#27647]
as written on the tin.
rapid metabolism cancels light eater, but not the other way around
also the huge line (ursine/bovine) doesn't cancel the tiny(mouse) line
**To Reproduce**  
1: give yourself rapid metabolism
2: give yourself light eater

**Expected behavior**  
rapid metabolism (and the mutations based on it) should be cancelled out first

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 8421 (64 bit)
 - Graphics version Tiles

**Comment by SirPendrak** [comment]
Also, its worth mentioning, since mouse line was added to the game, rapid metabolism was made unpurifable for some reason, wchich makes it only pre-treschold mutation that is unpurifable. But you can get rid of it by getting anny regeneration trait. It makes a complete mess.
