### ISSUE TITLE
Autonotes: add notes to the map automatically based on a set of conditions

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [CleverRaven/Cataclysm-DDA#27646]
**Is your feature request related to a problem? Please describe.**  
As mentioned in #27634, putting down notes regularly is rather tedious. This feature request is aimed at reducing the tedium.

**Describe the solution you'd like**  
There are already automatic notes for stairs, but that seems like a rather limited feature. I suggest expanding it into a full-blown set of triggers that would put down a specific note when activated in the source overmap tile.

A few examples of triggers: certain tiles, certain enemies, certain classes of enemies, certain items, certain classes of items, specific actions, specific vehicles etc.

This would make exploration even more rewarding because there are plenty of things that are not displayed on the map.

**Describe alternatives you've considered**  
N/A

**Additional context**  
Question: What to do if several triggers were activated?

**Comment by cainiaowu** [comment]
If only we could expand our current SAFEMODE manager into something like this...

**Comment by DeltaEpsilon7787** [comment]
>Just list all triggers, like "Hulk, power armor helmet, APC".

The problem lies if you try to use custom color or custom glyph for them. You obviously can't merge them.
