### ISSUE TITLE
Handling Large quantities of items Causes Lots of slowdown

### ISSUE THREAD

**Issue by jasonmbrown** [CleverRaven/Cataclysm-DDA#27651]
**Describe the bug**  
Carrying Massive quantities of items causes slowdown when Trying to Drop things.
[Requires Debug Carry To Notice]

**To Reproduce**  
    1) Add Debug Carry Weight
    2) Pick up a bunch of different Small Volume Items (up to around 2000volume)
    3) Try to drop entire Inventory using Any method (they all slow)
    4) Use Advanced Inventory Drop All (Still Slow)
    5) Use Advanced Inventory To Move Stacks (Goes Regular Speed)
    6) Game Speeds Up as you Drop Items

**Expected behavior**  
Should not take this Long to drop an Item for any reason. (IRL Time)
    
Version: 0.C-36419-gd7a0f0c (Tiles)
Build: 8416 (2 days ago)
OS: Windows 7 - 64Bit
Mods: "dda",  "no_npc_food",  "filthy_morale",  "novitamins",  "makeshift",  "More_Survival_Tools",  "modular_turrets",  "Salvaged_Robots",  "alt_map_key",  "Mining_Mod",  "mutant_npcs",  "national_guard_camp",  "BIGRIVER",  "more_locations",  "FujiStruct",  "oa_additional_buildings_mod",  "boats",  "deoxymod",  "blazemod",  "Tanks",  "more_classes_scenarios",  "StatsThroughSkills"

Video Clip and Save File
https://www.dropbox.com/s/5szrapv7g0a50vs/2019-01-15_16-27-33.mp4?dl=0
https://www.dropbox.com/s/esezw7eub40zr6z/save.rar?dl=0

**Comment by jasonmbrown** [comment]
Only mentioned it because the slow down is so much just from carrying lots of items. (Wouldn't think that dropping them would take as long as picking them up... Its like its recalculating the weight and volume every time the inventory changes. Just saying there seems to be room for improvement on inventory handling.

**Comment by Stone94** [comment]
IIRC Inventory is getting reworked slowly anyway, just everyone is off doing more interesting things right now.

**Comment by AskaHope** [comment]
Usually dropping several rags slow down the game a bit, but not THAT much.

**Comment by kevingranade** [comment]
Outline the reproduction case for that then.

**Comment by Asmageddon** [comment]
Simplest case would be picking up/dropping 200 cash cards through either `[e]` and `[D]`, versus through advanced inventory. In the first case, ingame time advances in 5 minute increments, making the operation take several seconds tops. In the second, the game advances time/renders a frame every item. I suppose the real time slowdown is more noticeable than the time difference(which I should have confirmed, but didn't, I'm sorry)

**Comment by Barhandar** [comment]
Or even simpler: try to move anything around through AIM (i.e. the way to haul before hauling was a thing). It'll take _aaaaaaaages_ to move any stack of small, not-collapsed-into-single-object, but numerous items, like splintered woods.
