### ISSUE TITLE
CBMs are craftable

### ISSUE THREAD

**Issue by DavidEdwards** [CleverRaven/Cataclysm-DDA#27662]
**Describe the bug**  
I can still craft 4 CBMs from the `2XI design binder-CLASSIFIED` book.

The book:

https://github.com/CleverRaven/Cataclysm-DDA/blob/98e5ce33ed82c481ffbb1f20efe62a7323d1567b/data/json/items/book/electronics.json#L134

The CBM:

https://github.com/CleverRaven/Cataclysm-DDA/blob/6850ddd0c144d25f3228b6d9d02054adbde1f2b9/data/json/recipes/recipe_electronics.json#L860

**To Reproduce**  
Acquire the book "2XI design binder-CLASSIFIED" `recipe_mil_augs`.

**Expected behavior**  
I was told that CBMs were removed from crafting.

**Screenshots**  
![image](https://user-images.githubusercontent.com/1585923/51251457-ae82a900-1999-11e9-8185-7790dfe8f87a.png)

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 18.10
 - Game Version (compiled yesterday, so current - you can see in the Github links)
 - Graphics version Tiles
 - Mods loaded Vanilla

**Comment by logros13** [comment]
This was intentional and greenlit by kevin since the alloy plates are fairly simple and don't interface with the nervous system in any way. Went looking for the specific issue/pr where he said it but couldn't find it, but from what i remember that was the reason.

**Comment by kevingranade** [comment]
IDK why it had a burnt out bionic in the recipe, but it's literally a set of metal plates you install under your skin.  Machining metal plates is not beyond the abilities of the survivor.
