### ISSUE TITLE
Acidic Ants kill their own larvas

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#27660]
Acid ants (all kinds) attack and kill acid larvas on sight. Normal ant larvas also gets attacked by them but very rarely. This is clearly not right. Dermatik larvas also gets attacked by them, but this is logical.
Normal ant grunts do not attack any larvas (not even dermatik larvas), but soldier ants attack acid and dermatik larvas. Are acid and normal ants enemies? Should they behave like this?

**Comment by davidpwbrown** [comment]
```"type": "MONSTER_FACTION",
    "name": "insect",
    "neutral": [ "military", "defense_bot", "utility_bot", "zombie" ],
    "by_mood": "insect"

It seems insects base their hostility towards other insects on their mood.... not sure if this is intended or not.
