### ISSUE TITLE
Driving car into a pond soft locks the game

### ISSUE THREAD

**Issue by cheesealmighty** [CleverRaven/Cataclysm-DDA#27679]
**Describe the bug**  
Driving a "hearse"  (from debug menu) into the pond makes the freeze. Menus are accessible. Zombies and time cannot be moved by "."

**To Reproduce**  
1. Spawn a car
2. Drive into a pond

**Expected behavior**  
I'd rather not have it frozen.

**Screenshots**  
https://puu.sh/Cy8d3/8c1a486395.png

**Versions and configuration(please complete the following information):**
 - OS: Win10
 - Game Version https://puu.sh/Cy8eS/e8a0bbaef2.png
 - Graphics version: Tiles
 - Mods loaded: "no_npc_food",  "filthy_morale"

**Additional context**  
Savegame: https://www.dropbox.com/s/1qof3ijob2mwlmx/TEST.7z?dl=0

**Comment by DSeyka** [comment]
You have safe mode enabled, which can be seen in your screenshot as well.
Tested the savegame and it indeed works just fine as soon as I disable it (by pressing "!" once).

**Comment by cheesealmighty** [comment]
That... That is embarrassing. Of course, after you're booted out of the vehicle, the safe mode override is off. _This never happened._

**Comment by DSeyka** [comment]
No problem! The game actually doesn't do that when you're leaving the vehicle normally (which is 99% of use cases), so I can see where the confusion comes from.
