### ISSUE TITLE
Add tiles for states of bionics

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#27677]
I would like to have ability to change tiles of installed bionics depending on state of it, as in activated or diactivated state. It will represent CBMs more correctly.
For example i want deactivated Advanced Defence System to look like this (which is not visible on character)
![ads-off](https://user-images.githubusercontent.com/37592026/51311390-dcc7bd80-1a59-11e9-97cd-9f0b468bc480.png)
and activated ADS to look like this
![ads-on](https://user-images.githubusercontent.com/37592026/51311414-efda8d80-1a59-11e9-8e13-0829c23d4092.png)

**Comment by halfahermit** [comment]
Do you know if this is already possible with mutations?

**Comment by halfahermit** [comment]
It looks like it isn't possible with mutations. I will try to get it working with both.
