### ISSUE TITLE
Acid ant hills full of normal ant larvas, who gets killed immediately. And other ant problems.

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#27676]
Acid ants just can't catch a break!
1. Hills with acid ants always full with normal ant larvas, and they get murdered as soon as they spawn. There are no normal ants in these acid ant hills, so i do not think there should be normal ant larvas.
Also there should be acid ant larvas, who not present almost all the time. Like, there are one acid larva on twenty normal ones in acid anthills.
2. In center of acid ant hill there are no acid ant queen, only normal two normal ant queens, who gets attacked. I do not think this is also right.
3. Normal (not acid) ants (not soldiers) do not attack acid ant larvas for some reason. All types of acid ants kill any larva what is not acidic.

**Comment by DoomAngelBlade** [comment]
Acid ant soldiers also fight with acid ants.
For unknown to me reason

**Comment by kevingranade** [comment]
Afaik this is adressed.
