### ISSUE TITLE
Allow renaming any item.

### ISSUE THREAD

**Issue by AskaHope** [CleverRaven/Cataclysm-DDA#27684]
Title.

**Describe Your Suggestions** . 

Renaming any item including non-physical items such as water.

**Additional Context**.

Renaming items should be just like renaming vehicles, you simply name it.

**Comment by Treah** [comment]
You already can with physical items but like you said not water and such. But why would you want to do this?

**Comment by AskaHope** [comment]
It's more cosmetic than anything. Just for fun.

The carving option could be used to write something on the floor. (~~Elbereth~~)
