### ISSUE TITLE
Sidebar position option doesn't work

### ISSUE THREAD

**Issue by DSeyka** [CleverRaven/Cataclysm-DDA#27687]
Switching sidebar position to the left in the interface options doesn't have an effect; it always stays on the right. Game version is 0.C-36726-gc4294a6 (tiles), OS is Windows 10.
~~I also couldn't notice any difference between the sidebar styles (narrow/wide) just below it. If the option is deprecated, it should be marked as such or removed.~~ Apologies; sidebar style option DOES work, it's just hard to see with lower character constraints. Position still doesn't, no matter the "resolution".

![image](https://user-images.githubusercontent.com/34726992/51353548-0288ad00-1ac2-11e9-881e-eca750a21aab.png)

![image](https://user-images.githubusercontent.com/34726992/51353611-28ae4d00-1ac2-11e9-8712-c88b50a47b59.png)

**Comment by Night-Pryanik** [comment]
Did you notice the `Requires restart` part on the description?

![default](https://user-images.githubusercontent.com/11132525/51367048-44d1de80-1b02-11e9-9aa1-a6f6edd4642d.png)

**Comment by DSeyka** [comment]
Totally didn't see that requirement, sorry.
