### ISSUE TITLE
Npc dialogue in new update breaks world

### ISSUE THREAD

**Issue by Mister-Cultist** [CleverRaven/Cataclysm-DDA#27699]
New update gave me a bug that always throws an error when I load my world and it won't let me use it with either my current character or a new one, it just dumps me back to the homescreen.

 DEBUG    : Error: data/mods//dda/../../json/npcs/Backgrounds/fema_evacuee_1.json: line 70:73: expecting number but found '"'

      {
        "text": "Sorry.  Tell me more about that FEMA camp.",
        "effect": { "npc_add_effect": "player_BGSS_SAIDNO", "duration": "
                                                                        ^
                                                                         600" },
        "topic": "BGSS_FEMA_EVACUEE_1_STORY2"
      },

**Comment by Necrosian** [comment]
![error](https://user-images.githubusercontent.com/26538192/51395297-2fca6f00-1b45-11e9-9bfd-83b8d7d3caf4.PNG)
