### ISSUE TITLE
Ask for confirmation before hiding recipe

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#27715]
A very common question I see on the discord is "How do I show hidden recipes?" While the answer is clearly shown in the list of filter commands (It's Filter>h:yes for anyone curious), it does make clear that it's very easy to accidentally hide your recipes, possibly without even realizing it. Having a simple Yes/No confirmation before setting a recipe to hidden would avoid some cases I've seen where players, while trying to scroll down in the menu due to ingrained WSAD muscle memory, tap the s key repeatedly, without even realizing they've removed a good chunk of their recipe list.

**Comment by Barhandar** [comment]
Having a simple yes/no confirmation would be even more annoying when batch-hiding recipes in the beginning. If added, it definitely should be a config option.

**Comment by jeremyshannon** [comment]
Perhaps "Hide this recipe? (Y)es/(N)o/(D)on't ask this again" would be a decent compromise that would alert newbies to what they just pressed, but allow people who use it a lot to disable the confirmation. (I don't use recipe hiding, so I wouldn't care)

**Comment by kevingranade** [comment]
I think a more complete solution would be to have an out of the way hidden
tab instead of making the recipes vanish entirely.

**Comment by Night-Pryanik** [comment]
> Would adding it as a third subtab under * work? (current: Favorite, Recent; new: Favorite, Recent, Hidden)

I think this is the best way.

**Comment by kevingranade** [comment]
Fixed by #27960
