### ISSUE TITLE
Butchery refuse character glitch

### ISSUE THREAD

**Issue by DavidEdwards** [CleverRaven/Cataclysm-DDA#27710]
**Describe the bug**  
I receive a graphical glitch from the extended ascii character `¨`.

I was originally using pre-built binaries, but after updating my Ubuntu, I couldn't any more. Since the new version uses an updated version of curses. Pre-built is libncurses v5, my system has libncurses v6.

Perhaps that causes issues?

**To Reproduce**  
Butcher a corpse.

**Expected behavior**  
I should see a `¨` character.

**Screenshots**  
![image](https://user-images.githubusercontent.com/1585923/51413880-a16be280-1b70-11e9-927b-4f26ede84e59.png)

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 18.10
 - Game Version (compiled today)
 - Graphics version Curses
 - Mods loaded Vanilla
 - Compiled with `make -j6 NATIVE=linux64 RELEASE=1 LOCALIZE=0 LINTJSON=0`

**Comment by DavidEdwards** [comment]
I noticed a similar glitch just now too here (above stamina):

![image](https://user-images.githubusercontent.com/1585923/51430390-35928400-1c1b-11e9-827a-438b4f3cdec5.png)

**Comment by kevingranade** [comment]
I wonder if you're linking against a non-localized ncurses library.
Can you paste the output of ``ld ./cataclysm``?

**Comment by DavidEdwards** [comment]
Sure, hope this helps.

```
~/games/Cataclysm-DDA$ ldd ./cataclysm
	linux-vdso.so.1 (0x00007ffc1c9f7000)
	libncurses.so.6 => /lib/x86_64-linux-gnu/libncurses.so.6 (0x00007f0d81b02000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f0d818d7000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0d8174d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0d815c0000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0d815a6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0d813bc000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0d813b4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0d82a3d000)
```

**Comment by int-ua** [comment]
Please update the description to better match current status. And the title since it isn't/wasn't limited to one character.

**Comment by int-ua** [comment]
Please comment if you still have this problem and we'll reopen this issue.
