### ISSUE TITLE
Food Portions for various crafted foods now incorrectly set to 1

### ISSUE THREAD

**Issue by paradigm369** [CleverRaven/Cataclysm-DDA#27728]
**Describe the bug**  
A number of craftable food items appear to have their portion sizes incorrectly reduced to 1, while still consuming the same number of components. Some of those I found include Smoked Meat, which still consumes 3 chunks of meat, but only produces 1 smoked meat. Other examples I noticed are all the various soups (meat, vegetable, woods) which now have only one portion.

**To Reproduce**  
1. Run experimental build 8445
2. Go into crafting menu and look up smoked meat.
3. Notice the erroneous portion size.

**Expected behavior**  
Previously the portion sizes made sense ie 3 chunks of meat becomes 3 smoked meat. This should be how it is.

**Screenshots**  
<img width="745" alt="woods soup" src="https://user-images.githubusercontent.com/45728231/51436945-62a16e00-1cd1-11e9-8004-93a8b1ede672.PNG">
<img width="790" alt="meat soup" src="https://user-images.githubusercontent.com/45728231/51436946-633a0480-1cd1-11e9-8154-6e68717a6d53.PNG">
<img width="228" alt="mods" src="https://user-images.githubusercontent.com/45728231/51436947-633a0480-1cd1-11e9-88e9-3973ede625dd.PNG">
<img width="947" alt="smoked meat" src="https://user-images.githubusercontent.com/45728231/51436948-63d29b00-1cd1-11e9-9688-2591a94c2eac.PNG">
<img width="740" alt="vege soup" src="https://user-images.githubusercontent.com/45728231/51436949-63d29b00-1cd1-11e9-95cf-6e62e9e2b162.PNG">

**Versions and configuration(please complete the following information):**
 - OS:  Windows 10
 - Game Version  0.C-36853-g1c2b10d
 - Graphics version 
 - Mods loaded: in Mods screenshot

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by KorGgenT** [comment]
should be most odd recipes like this that get addressed in the above PR

**Comment by paradigm369** [comment]
Smoked meat also has the same issue. Don't think is a matter of nerfing. I believe is an error. Because for all these recipes, due to their portions now being changed to one, have much much lower calorie value than their components... which doesn't really make sense.

**Comment by KorGgenT** [comment]
#27542 was merged, should fix the recipe oddities

**Comment by ynemo** [comment]
could you also check https://github.com/CleverRaven/Cataclysm-DDA/issues/27819 
looks like sausages need 6 quantity instead of 1

**Comment by ynemo** [comment]
so soups now totttaly useless?what the point of mess with them, ufter this nerf?

**Comment by ynemo** [comment]
Befor, u could put  12 soups in thermoss and its was average day norm of calories. Now u can put only 4. And i dont get the reason i should mess with coocking broth and etc. to recieve 4 less soups then befor.
Soups has 8 quench , so 0.25L of soups gave 40 quench wich is compared to water or pine tea, it was nice ballance making soup one of the best dishes. 
I dont get, why they are nerfed now?

**Comment by ynemo** [comment]
i made new open issue https://github.com/CleverRaven/Cataclysm-DDA/issues/27855
