### ISSUE TITLE
Cannot consume large stacks of items with Internal Furnace CBM

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#27729]
**Describe the bug**  
When attempting to eat a large stack of items, such as duct tape or charcoal, they will not be shown as valid options to consume when the Internal Furnace CBM is on.

**To Reproduce**  
1. Make a player with the Internal Furnace CBM and activate it.
2. Spawn a stack of 1000 charcoal and a second stack of 110
3. Press Shift+E to attempt to consume the stacks, only the stack of 110 will show up.
4. Have only the stack of 1000 near you and press Shift+E, you'll get a "You have nothing to consume" message.

**Expected behavior**  
When attempting to eat a stack of 1000, it should eat as much as is allowed by the limit and inform the player of the amount being eaten.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version 0.C-36894-gdbbeb42
 - Graphics version Tiles
 - Mods loaded DDA, Disable NPC Needs, Filthy Clothing, Simplified Nutrition

**Comment by KorGgenT** [comment]
fixed by #28513
