### ISSUE TITLE
Tileset graphics bug with software rendering

### ISSUE THREAD

**Issue by Necrosian** [CleverRaven/Cataclysm-DDA#27731]
Describe the bug
Build : 8451

MSX++LIVE_PEOPLE Tileset graphics bug

![bug](https://user-images.githubusercontent.com/26538192/51441650-350df200-1cdc-11e9-9c51-d1fbe52c2e5a.PNG)

Versions and configuration(please complete the following information):

    OS: [Windows 7 x64]
    Game Version :Build 8451 version: 0.C-36894-gdbbeb42
    Graphics version: Tiles
    Mods loaded : dda, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Remix Indicators, Vehicle Addition Pack, Tanks and Other Vehicles, Folding Parts, Urban Development, More Locations, Fuji's More Buildings,Mutant NPC, More Survival Tools, Medieval and Historic Content,No Fungal monsters, Oa' aAdditional Buldings mod

**Comment by Crafty908** [comment]
Not sure if this helps. But I have the same issue, heres debug info:
18:40:27.478 ERROR : (error message will follow backtrace)
	(@0x5e42be[cataclysm-tiles.exe+0x1e42be]), 
	(@0x5e489a[cataclysm-tiles.exe+0x1e489a]), 
	(@0x5e6533[cataclysm-tiles.exe+0x1e6533]), 
	(@0x7e7f87[cataclysm-tiles.exe+0x3e7f87]), 
	(@0x750736[cataclysm-tiles.exe+0x350736]), 
	(@0x7515a3[cataclysm-tiles.exe+0x3515a3]), 
	(@0x6c7196[cataclysm-tiles.exe+0x2c7196]), 
	(@0x6c7a75[cataclysm-tiles.exe+0x2c7a75]), 
	(@0x8a119b[cataclysm-tiles.exe+0x4a119b]), 
	(@0x8a26ea[cataclysm-tiles.exe+0x4a26ea]), 
	(@0x8963c0[cataclysm-tiles.exe+0x4963c0]), 
	(IMG_LoadWEBP_RW+0x42837@0xfc6e57[cataclysm-tiles.exe+0xbc6e57]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0xd@0x775d59ed[kernel32.dll+0x159ed]), 
	(RtlUserThreadStart+0x21@0x7780b371[ntdll.dll+0x2b371]), 

Same session graphic options bugged out.

src/options.cpp:547 [T options_manager::cOpt::value_as() const [with T = bool]] RENDERER tried to get boolean value from option of type string_select
18:43:02.248 ERROR : src/options.cpp:547 [T options_manager::cOpt::value_as() const [with T = bool]] RENDERER tried to get boolean value from option of type string_select
18:43:09.410 ERROR : src/options.cpp:547 [T options_manager::cOpt::value_as() const [with T = bool]] RENDERER tried to get boolean value from option of type string_select

**Comment by Night-Pryanik** [comment]
I'm pretty sure there is an existing issue with similar problem, but I can't find it.

**Comment by SomeDeadGuy** [comment]
Nope, ut is not a problem with tileset. It is a problem with rendering. Change rendering to direct3d, in my case it fixed that problem.

**Comment by ZhilkinSerg** [comment]
> 
> 
> I'm pretty sure there is an existing issue with similar problem, but I can't find it.

https://github.com/CleverRaven/Cataclysm-DDA/issues/23446

**Comment by Firestorm01X2** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/27644
https://github.com/CleverRaven/Cataclysm-DDA/pull/27644#issuecomment-454703065

I've managed to resolve issue for me.
I've just grab specific (older) version of MXE:
git checkout git rev-list -n 1 --before="2017-09-24 12:00" master``

This version built non bugged version of the game. Graphical isses with tilesets gone away.

But. Watch out! It is probably means that if you will update MXE on build server- then you will get that kind of issues since build server uses old version of MXE.

**Comment by SirPendrak** [comment]
I am getting similar graphical bug with MSXotto tileset

**Comment by Xelat84** [comment]
Those dashes appear because of rotating tiles (may be because of some rounding math in UV).

For workaround just disable rotation of "t_dirt" in tileset_config.json, and all dirt-related dashes disappear.

P.S. Also found "transparent lines" on water tiles, but it's rotates by engine probably, can't find option for rotation right in json. Or it's because it ommited, and should be defined explicitly.

**Comment by SomeDeadGuy** [comment]
Interesting information! I will test it tommorow. I did rotating tiles cause that way they look more natural. If this is not a fixeble problem, i guess i can disable rotation. Black lines are way worse than repetative tiles.

**Comment by SomeDeadGuy** [comment]
@Xelat84 i got the water problem!
It was t_connection piece of the water. For some reason only this piece was not in it's place.
Check tileset on my page, i fixed most of the blacklines thanks to you! :D

**Comment by Night-Pryanik** [comment]
Is issue resolved?

**Comment by SomeDeadGuy** [comment]
Issue itself? No.
I just found a way around the issue.
I guess this can be closed, i dont think someone will fix software rendering problem any time soon.

**Comment by KorGgenT** [comment]
is this issue still valid, now that this tileset is no longer part of the repo?

**Comment by SomeDeadGuy** [comment]
This problem exist in any tileset in software rendering. Title can be changed tho.

**Comment by ZhilkinSerg** [comment]
Yeah, I guess there is some rounding error.
