### ISSUE TITLE
Moral effects last 10x as long as they should

### ISSUE THREAD

**Issue by rselias** [CleverRaven/Cataclysm-DDA#27733]
**Describe the bug**  
Looking in the code, it appears the Killed Innocent debuff is supposed to last 2 days. It lasts about 18 instead. This time does not scale with season length.

Looking at my main save file, the duration of the debuff is correctly set to 28800, which should be 48 hours. However, its age is only 10.48 hours when the debuff has been present for maybe five days - I don't remember exactly when it started. My initial guess was that it's reading the duration as minutes instead of turns, but testing with a debug character had the debuff last 18 days instead of 20, which I would have expected if that were the case.

**To Reproduce**  
1. Make a debug character in a new world
2. Wish for a weapon and timekeeping device
2. Spawn and kill an NPC
3. Repeatedly wait until dawn, checking morale until debuff expires on day 19

**Expected behavior**  
For a murder on day 1, the Killed Innocent morale debuff should expire on day 3.

**Versions and configuration:**
 - OS: Windows 10
 - Game Version: 0.C-36894-gdbbeb42 (but the bug is definitely not just in the latest version)
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs, Filithy Clothing, Simplified Nutrition

**Comment by vpkoskinen** [comment]
In game.cpp starting from line 1681 it reads:
```
    if( calendar::once_every( 1_minutes ) ) {
        u.update_morale();
    }
```
So morale decays by one turn every minute, but there are 10 turns in a minute.
I do not know if this is intended behavior, but removing the conditional gives the expected behavior by rselias.

**Comment by Zireael07** [comment]
If other effects decay properly, maybe whoever wrote the value misunderstood the units it uses?

**Comment by rselias** [comment]
Upon further testing, it's not just the one effect. Every morale effect I checked lasted a bit under 10 times as long as it was supposed to, as is implied by the faulty check vpkoskinen found.

**Comment by tyrael93** [comment]
looks like an easy fix
