### ISSUE TITLE
Odd food properties

### ISSUE THREAD

**Issue by mding9** [CleverRaven/Cataclysm-DDA#27740]
I have seen a few odd food properties with the recent updates:
-crafting woods soup yields 1 portion with 304 Calories, while cooked meat, a possible component, gives 399 Calories. A lot of components are like this as well. Although boiling food reduces the calories in the food, I just thought it should be checked.
-cooking oil is in portions of 240, but the weight of each portion doesn't seem to have changed. For example, a gallon jug of cooking oil weighs about 60 or so lbs.
-dried rice gives 217 Calories per portion while fried rice is 174 calories. Again, I might be wrong since some of the rice might lose Calories due to cooking, but I think it should be looked at.
-dried rice gives 217 Calories per portion and is used in making sushi rice, which yields 4 portions that each give 200 Calories. The other ingredients are water, vinegar, and [salt(5) or seasoned salt(5) or soy sauce(1) or sugar(1)], which I don't think provide a lot more calories.
-Rice also seems to be a bit too small. Setting plastic rice bags to hold 3 units of dried rice seems like a conscious choice to make portions of rice feel larger, but the rice itself is .09L per portion right now. Sushi rice is .07L in comparison even though it is made in groups of 4 with 1 unit of dried rice.
-vegetable pie gives 8 portions with 486 Calories each, while meat pie gives 8 portions with 399 Calories each. In-game, meat has a lot more calories than vegetables, and a large bonus of vitamin B12 which is somehow lost in making the meat pie.
-Pemmican seems to give a small amount of calories in comparison to the things it is made out of including fat based components like tallow and lard.

-One more thing that is unrelated is the volumes of syringes. An empty syringe is .05L, while a syringe of adrenaline is .01L.

Reproduction:
1. Open a world and debug recipes, then use the crafting menu and item list to look at recipes and items.

**Versions and configuration:**
 - OS: [Windows 10]
 - Game Version [0.C-36905-g81e9990]
 - Graphics version [Tiles]
 - Tested in an unmodded world.

I probably haven't gotten all of the strange things, though the people working on this game are probably weeding them out themselves. However, I do hope this provides a bit of useful information in case the devs miss anything.

**Comment by AlexanderGlasco** [comment]
If only the Soviets had known they could ballast their submarines with hyper-dense cooking oil:
![image](https://user-images.githubusercontent.com/13599306/51467248-19d1cf80-1d3a-11e9-9f38-70b89558207b.png)

**Comment by KorGgenT** [comment]
everything except the cooking oil thing (which i'll take a look at in a few) is addressed in #27252

**Comment by gcaliber** [comment]
Can confirm a gallon of cooking oil now weighs 62 lbs.

**Comment by kevingranade** [comment]
Fixed by #27925
