### ISSUE TITLE
Melee attack time is too simplistic, does not account for balance or method of striking

### ISSUE THREAD

**Issue by KITbutler** [CleverRaven/Cataclysm-DDA#27748]
**Is your feature request related to a problem? Please describe.**  
Currently the base "move cost to attack" is automatically scaled with the volume and weight of the item as follows: 65 + volume() / 62.5_ml + weight() / 60_gram

This makes sense for the general case of swinging a vaguely bar-shaped object, an increase in size moves its centre of mass further away from the hand and weight should be self-explanatory. As much as it might reignite previous balance debates this however simply does not apply with the same prefactors to thrusting with a spear: since the centre of mass is aligned with the direction of motion and the shaft is rigid virtually no energy is transmitted into rotation, there is no leverage and short of stabbing someone with an umbrella there is no relevant air resistance to account for an additional volume scaling.

Since damage does *not* seem to receive any such automatic adjustments the current formula also completely ignores the balance of a swung weapon: a hammer or mace deals high bashing damage because the game assumes you are striking the enemy with the heavy head, but a hypothetical copied item with vastly reduced damage due to grabbing that same hammer by the head would currently swing at the same speed despite having vastly less rotational inertia. The issue is not purely hypothetical either: most swords are balanced like upside-down axes/hammers.

**Describe the solution you'd like**  
Implement weapon-specific scaling factors or even base move cost overrides. Make thrusting spears and rapiers significantly faster (set volume scaling to 0), swords slightly faster, hammers and maces significantly slower along with many tools. Adjust their damage values or even the fundamental damage calculations to restore balance as far as the physical reality of the items allows. Do not generalise movement costs to the base damage types as a whole as unconventional outliers do exist (the war hammer deals piercing damage, a war pick would be even more extreme)

**Describe alternatives you've considered**  
Add a few base scaling tags like "THRUST" (no volume scaling, for pure thrusting attacks), "TOP_HEAVY" (increased weight and/or volume scaling, for hammers), "BULKY" (increased volume scaling due to protrusions or air resistance like the aforementioned umbrella) and "WELL_BALANCED" (reduced volume scaling, for well-made swords and combat knives) using the current formula as the default.

Or, you know, "accept it, it's just a video game". _Booooring!_

**Additional context**  
Unfortunately a more realistic formula will make spears ridiculously strong. In part this is justified, after all they _were_ one of the most prevalent melee weapons throughout almost all of history while bladed weapons were often carried as sidearms due to their greater convenience. Since a single high-calibre bullet can drop a zombie we cannot (currently) rely on a need for large-scale physical trauma to justify significantly lower damage values on them either. Making spears overpowered is not my intention however, I mainly noticed this while trying to understand the melee performance of bayonets which (rightfully) suffers as other gunmods add bulk and mass to the weapon. 

The true downsides to these "fast" thrusting weapons would require other game mechanics which also are not in place: low stopping power/debilitating injury potential before death (choppers cannot cause amputation), overpenetration (getting stuck seems to be limited to _low_ strength) and the big one for us: inability to store long/large weapons in pockets, backpacks or bionic sixpacks, forcing the use of an encumbering strap or else dropping the weapon when we need our hands free.

**Comment by Barhandar** [comment]
>(the war hammer deals piercing damage, a war pick would be even more extreme)

War hammer _is_ a war pick, someone ages ago was just really bad at naming. 
>overpenetration (getting stuck seems to be limited to low strength)

It's because the character can't "pull out" as opposed to "getting it stuck too deep".
>and the big one for us: inability to store long/large weapons in pockets, backpacks or bionic sixpacks

Pretty much every single player who doesn't dedicate their gameplay to realism above all else (and those can just use the strap anyway) will be against this, as it invalidates ability to carry _most_ of the larger items around without wielding or dedicated (vehicle parts have dimensional constraints too you know) vehicles. Additionally it requires container rework, which has been stuck in planning stage for _five years_ now.

For spears to not be overpowered, they need polearm-specific mechanics such as having to have tile next to you and opposite from your target free to be able to deal full damage (=simulating full length thrust), not being slower; and dealing reduced damage with adjacent attacks for same reason. I.e. for regular spear to be truly effective you _need_ spacing, that's why sidearms (including shorter spears which'd be unable to do reach attacks, but potentially allow throwing them) were a thing.
>Since a single high-calibre bullet can drop a zombie we cannot (currently) rely on a need for large-scale physical trauma

A high-caliber round _is_ large-scale physical trauma.

**Comment by KITbutler** [comment]
> It's because the character can't "pull out" as opposed to "getting it stuck too deep".

That's my point, "can't pull out" currently exists but "can't pull out *because* it went too deep" does not. Similarly "impaling strike" should not be a pure technique bonus but rather come with a guarantee of getting stuck in the first target unless you are *ridiculously* strong (15+ based on default stats and mutation descriptions)

> Pretty much every single player who doesn't dedicate their gameplay to realism above all else (and those can just use the strap anyway) will be against this, as it invalidates ability to carry most of the larger items around without wielding or dedicated (vehicle parts have dimensional constraints too you know) vehicles. Additionally it requires container rework, which has been stuck in planning stage for five years now.

Yeah, I know. Although honestly packmule'ing kegs into backpacks feels stupid too, for a quick stopgap more strap/sheath/holster slots could be added to belts, coats and backpacks so people can carry their tools around. Or even just a "TOO_LONG" tag explicitly banning spears, greatbows, mounted machine guns etc. to shift all the unrealistic stuff into the same corner.

> A high-caliber round *is* large-scale physical trauma.

I meant *geometrically* large. Sure you can shoot through a body lengthwise but that is not a common attack angle, punching a hole larger than a spearhead probably requires something like .50 BMG or hitting a perfect shot to the middle of the neck. Basically I was thinking of cartoon zombies where even individual *fingers* remain active and the only way to dispatch them is to mess up the body so badly it becomes physically unable to harm you.

**Comment by gcaliber** [comment]
This sounds like a lot of work for very little benefit.

**Comment by Human-Shield** [comment]
Spear trusts will be superior unless limb damage becomes a thing. Pokes wouldn't do as much damage to limbs and be harder to hit limbs compared to swings (melee simulation tabletop games already do this). So applying limb damage effects to monsters (reduced speed / melee damage). I guess this could also give a buff to shotguns versus bullets.
