### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by micage** [CleverRaven/Cataclysm-DDA#27753]
Pulled the latest experimental from github, compiled it using:
make NATIVE=osx OSX_MIN=10.7 RELEASE=1 TILES=1 LOCALIZE=0 CLANG=1

Crash report:
0   cataclysm-tiles               	0x000000010690bce5 player_morale::operator=(player_morale&&) + 261
1   cataclysm-tiles               	0x00000001068e036d player::operator=(player&&) + 2845
2   cataclysm-tiles               	0x0000000106532873 main_menu::opening_screen() + 1731
3   cataclysm-tiles               	0x0000000105f48820 main + 5040
4   libdyld.dylib                 	0x00007fff9bdf95ad start + 1

OS X 11.6, clang 8.0.0

This procedure worked for me before. I'm doing weekly builds of --HEAD.

**Comment by ZhilkinSerg** [comment]
Are you starting a new game or loading existing? Do you use any mods?

**Comment by micage** [comment]
The game crashes before the game menu.

**Comment by micage** [comment]
A week ago everything compiled just fine. It's **not** a duplicate of #23171.

How  can I disable all optimizations? I'm not calling clang directly, instead I'm calling "make ..." like described in compiling instructions.

I also downloaded the latest binary. There are problems with a code signing error of the SDL2 framework which leads to a freeze of the cataclysm app.

**Comment by micage** [comment]
After deleting the SDL2.framework from cataclysm.app and installing a fresh copy 
from: https://www.libsdl.org/release/SDL2-2.0.9.dmg 

I had to erase the quarantine bit (to prevent a very time consuming "unauthorized developer" check) with:
sudo xattr -rc /Applications/Catacylsm.app

Now at least the binary is working. Leaves the question why my copy from github isn't compiling anymore?

**Comment by micage** [comment]
Hey, and not to forget to find and download a working soundpack and copy it into the
/Applications/Catacylsm.app/Contents/Resources/data/sound folder.

This is fun!

**Comment by micage** [comment]
Managed to get it working again:
> brew install astyle
> make TILES=1 SOUND=1 LUA=1 DYNAMIC_LINKING=1 LOCALIZE=0

No localization -> no gettext required.
