### ISSUE TITLE
Biosilicified chitin armor doesn't protect from acid

### ISSUE THREAD

**Issue by DoomAngelBlade** [CleverRaven/Cataclysm-DDA#27758]
8451 is my version.
Biosilicified chitin chunk description:
A lump of exoskeleton that has undergone biosilicification. It is acid-resistand and remarkably sturdy.
Biosilicified chitin boots description:
Boots crafted from carefully cleaned and pruned biosilicified exoskeletons of acidic ants. Acid-resistant and very durable.

Yet:
Walking into acid gives "You're covered in acid", "The acid burns your legs and feet"
Damge received seems to be at default rates, though pain is decreased alot.
My character doesn't have any mutations related to pain, not affected by painkillers(or any other chemicals) and doesn't have any CBMs to suppress them. After losing like 20% of both legs HP i had no pain. After losing for some more I got "Minimal Pain"

**Comment by kevingranade** [comment]
This is working as intended, the chitin itself s acid-resistant-but not tightly sealed.
