### ISSUE TITLE
NPCs in 'Guard' mode do not fight cockroach nymphs0.C-36907-g0d68189 (tiles)

### ISSUE THREAD

**Issue by Zmedaris** [CleverRaven/Cataclysm-DDA#27760]
This is my first issue, so sorry if I flub anything.

**Describe the bug**  
NPCs that are set to 'guard this position' via the dialogue menu will not fight back against giant cockroach nymphs.

This is very specifically 'guarding NPCs' and 'giant cockroach nymphs'. An NPC in guard mode will fight any other monster (including even 'giant cockroaches'), and an NPC that is following the PC will fight giant cockroach nymphs.

**To Reproduce**  
1. Have an NPC set to 'guard this position' via the dialogue menu.
2. Either lure a giant cockroach nymph to the NPC, or spawn one nearby via the debug menu.
3. Use the wait key to pass some turns while the NPC acts as an immobile punching bag.

**Expected behavior**  
NPCs should be fighting and killing cockroach nymphs while in guard mode. A single nymph can literally go through a group NPCs and kill them all given enough time. (Barring complete damage reduction via armor or something.)

**Screenshots**  
![screenshot 681](https://user-images.githubusercontent.com/12032854/51505859-f476ad00-1d9d-11e9-95ee-5b80726c7f74.png)

**Versions and configuration**
 - Windows 10
 - Game Version 0.C-36907-g0d68189 (tiles)

**Mods**
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "realguns",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "alt_map_key",
  "mutant_npcs",
  "national_guard_camp",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "blazemod",
  "Tanks"

**Additional context**  
https://www.dropbox.com/s/hff19h2lwwbvopr/Quakertown.7z?dl=0

A save with an allied NPC in guard mode nearby.

**Comment by Zmedaris** [comment]
So as an update to this issue, it seems like cockroach nymphs in general are bugged. Almost nothing fights back against them, as far as I've noticed, and I've even caught reports in the Discord channel of nymphs successfully taking down bigger and much more dangerous enemies, such as a moose, because the other monster won't fight back.

**Comment by davidpwbrown** [comment]
Something's screwy with danger calculation.
I upped the nymph to a super-nymph HP and melee damage, and suddenly the NPC cared a lot about it being there and shot it.
There must be a cut-off point of sorts where something non-scary means the NPC ( or other creature ) dosn't even fight back against it.
