### ISSUE TITLE
[FR] The ability to create faction camps within existing landmarks.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#27778]
E.g. my dream ever since I first found a mall in CDDA years ago, has been to convert one into a fortress. Now that faction camps have been implemented, I've been looking forward to this really much, but... turns out, it's not possible.

I'm assuming there's reasons behind this, but still, it's something important to me so I have decided to open an issue.

**Comment by I-am-Erk** [comment]
I would say this is already in discussion in https://github.com/CleverRaven/Cataclysm-DDA/issues/24422

It's definitely something under development, although it's stalled out a bit right now as @mlangsdorf has been doing more with dialogue than with camps for the last bit.

**Comment by Night-Pryanik** [comment]
Closing in favor of #24422.
