### ISSUE TITLE
Firefigher robots tend to destroy all furniture on their way (Salvaged robots mod)

### ISSUE THREAD

**Issue by DoomAngelBlade** [CleverRaven/Cataclysm-DDA#27792]
My version:cataclysmdda-0.C-8458 2019-01-22 09:13  

I entered firestation that is filled with firefighter robots and I just seen how one destroys a metal locker.

After watching their behaviour for some time I seen that they mostly wander around aimlessly. 
But if on their way there is furniture of some kind - they may attack it to destroy it.
Effectively ripped on my eyes:
All metal lockers.
Tables, chairs
Doors.

Weird behaviour for a FIREFIGHTING ROBOT to "HULK! CRUSH!"

**Comment by Shodan14** [comment]
Does the mod have it's own github? It's an amazing piece of work and I would love to help make it better (with advice at least).
