### ISSUE TITLE
Add ability to transfer Active state through transformation

### ISSUE THREAD

**Issue by DoomAngelBlade** [CleverRaven/Cataclysm-DDA#27813]
**Is your feature request related to a problem? Please describe.**  
During gameplay I found that I can only WEAR a gas mask. I cannot leave it hanging on my body with straps it has/may have. So I decided to create one. 
After creating "Gas mask with strap", that has funcionality of gas mask but can be left hanging
(Changes encumbrance to like 2, covers torso, around 5% of it, gives no enviormental protection, can be put back on face, etc.), given both of them transform ability (from "hanging" to "on face" and from "on face" to "hanging") I spotted a problem.

If I use the second ability I have added to "gas mask with strap" (transform) it will transform to "gas mask with strap (hanging)". To use gas mask's filter you need to "PREPARE" it. This switches gas mask to gas mask (active) or , in my case, "gas mask with strap" to "gas mask with strap ( active)".

But upon transforming an ACTIVE item it loses it's "ACTIVE" status.
"gas mask with strap (hanging) (active)" transforms into "gas mask with strap"
"has mask with strap (active)" transforms into "gas mask with strap (hanging)".
This is not what I expected to happen.
(Charges are moved perfectly. I had 99 charges, transformed it and had 99 in it)
**Describe the solution you'd like**  
Upon transformation, if item has same ability that is active
(for my case: GASMASK)
ability of item should stay active. 
Or atleast add a possibility for it to carry the active state upon transformation.

**Describe alternatives you've considered**  
Alternatively I could create 4 states of gas mask:
Gas mask with strap 
Gas mask with strap (active)
Gas mask with strap (hanging) 
Gas mask with strap (hanging) (active)

Make active ones consume charges, change amount of turns per charge for each active variant, make active variants protecting ones and make active variants auto transform on lack of charges.
Will make code much more messier and remove need for "GASMASK" ability

**Comment by OrenAudeles** [comment]
Possible solution (untested for syntax or algorithmic validity):

1. In definition of `class iuse_transform` add a boolean to handle ability to transfer active state, default false.
2. In `iuse_transform::load` add optional read to pull in the associated JSON key
3. In `iuse_transform::use` replace `obj->active = active || obj->item_counter;` with 
`obj->active = active || obj->item_counter || (<transfer_active_boolean> && it.active);`
