### ISSUE TITLE
Bratwurst if too effective

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#27819]
Bratwurst recipe gives 10 portions 295 kcal each. 
Sausage gives 1 portion 469 kcal with about x2 ingredients compared to bratwurst. 

Bratwurst is too effective

**Comment by ynemo** [comment]
or maybe sausage should get a boost..

**Comment by Barhandar** [comment]
Sausage before the "calorie overhaul" was giving 6 portions.

**Comment by KorGgenT** [comment]
i don't see an issue. sausage has more calories and bratwurst has less, but you get a different amount of portions from either. as far as the ingredients both, the calculations are correct as of now.

**Comment by ynemo** [comment]
It's ok now, after sausage has 6 portions. thx
