### ISSUE TITLE
CBM install chances using Autodoc must be revised

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#27826]
**Describe the bug**  
CBM install chances using Autodoc must be revised

**To Reproduce**  
1. Try to install various CBMs using Autodoc.

**Actual  behavior**  
![51628507-38acad80-1f56-11e9-876a-d369ab451d4f](https://user-images.githubusercontent.com/17512620/51667496-523f0b00-1fd1-11e9-8c95-6d77dbcfc530.png)

[CBM_chance_Default.xlsx](https://github.com/CleverRaven/Cataclysm-DDA/files/2790940/CBM_chance_Default.xlsx)

DeltaEpsilon graphs:
![bionic_difficulty](https://user-images.githubusercontent.com/17512620/51787274-c1a72d00-2180-11e9-8f70-caa12513955e.png)
>@DeltaEpsilon
>There is a very clear break point in this formula
>For a very specific adjusted skill value
>This doesn't seem intended at all
>The rate grows so fast that even one more additional level increases your chances to install a bionic by a lot.

**Expected behavior**  

https://github.com/CleverRaven/Cataclysm-DDA/issues/27750#issuecomment-457048283
Agreed, no-knowledge chance of successful install is way too high, it needs to be reigned in a great deal, I don't expect anything higher than a 20% success rate there. At the same time, I do think the requirements at the far upper range are a bit much, I'd expect 10 + 8/8/8 or so to be at least reaching 90% for up to difficulty 10 or so, though I'd buy that the operation to install things like wired reflexes should be absolutely ludicrous and not peak over 90% until you're an absolute virtuoso at everything involved.

A thought I had looking at this is giving the stats some context. Medical/first aid is an absolute must, and should maybe just tank your chances if you don't have it, regardless of the rest. Meanwhile computer and electronics can maybe be substituted for with int because there's a certain amount of "you can just figure it out" for programming the machine and setting up the cbm for installation.

So just a sketch, the install success chance is the min of the install chance for the three skills, and they're calculated differently:

 1)   First aid is dominant, it's basically determining your ability to plan the operation, so no matter how good you are at the others, it presents a cap on your chances of success.
 2)   Computers is your ability to actually input your planned operation into the system, if it doesn't meet the requirements, maybe you're a bit prone to mistakes and can't optimize the system as well. The required level is much lower than the nominal First Aid for a procedure, A First Aid 4 procedure might only require Computers 1. It might also contribute by making the manual process of entering the program faster the higher it is. At low levels int might completely stand in for computer success chance, but not speed. i.e. if you take your time you can get it done, but you're going to be slow.
3)  Electronics is your ability to set up the machine and CBM for installation. This is almost routine for easy CBMs, but mistakes are costly in chance of risk. Again, it might only require Electronics 1 for optimal installs until you get to very difficult CBMs.

IDK, I don't think it's necessary to change anything about skill handling, but it's nice to have a mental model of what's happening rather than just numbers.

**Conclusion**  
* Chance to install CBM for no skill player in some cases way too hight.
* Chance to install CBM for max skill player in some cases way too low.
* Chance to install for expect  Intellect 10 + Skills 8/8/8 should be 90% for up to difficulty 10.
* Chance to install CBM for zero skill character should always be 20% or lower even for easiest CBMs. 
* Skill effect on install chance should be checked and revised.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 X64
 - Game Version: 0.C. 8467
 - Graphics version: Tiles
 - Mods loaded: Default

**Additional context**  

For players: Consider using SAFE AUTODOC mod,  CBM Manual Installation Mod or BrightNights mod to bypass the issue.

**Comment by I-am-Erk** [comment]
Why do you figure someone very good at first aid and computers should have a 90% chance of programming an autodoc to do perfect unassisted surgery on their most delicate body parts?

I think your perceived balance here doesn't take into account planned and soon coming directions for the game. The problem is not the autodoc having too low a max success, it's that other more reliable ways to install bionics need to be finished.

**Comment by Firestorm01X2** [comment]
>The problem is not the autodoc having too low a max success, it's that other more reliable ways to install bionics need to be finished.

I am kinda pointed on it there:
https://github.com/CleverRaven/Cataclysm-DDA/issues/27750
In some way.

Proabably you are right.

But what to do then?

**Comment by SourSlime** [comment]
Here’s my proposed changes to install chances for CBMs. It won’t fix the install chances being low, but it should make them more realistic.

CBMs at the moment use a numerical difficulty to determine how hard they are to install. For each CBM, each skill used should be at a certain level depending on the complexity and install location of the CBM. I realise this will take a bit of work, but most CBMs fit into a category for each skill.

FIRST AID
The skill requirement is based on the install location of the CBM:
1 - Skin
2 - Flesh
3 - Muscle
4 - Chest cavity
5 - Any other organ
6 - Heart
7 - Eye
8 - Brain

Additional skill requirement:
If the player is mutated up to threshold dreams, add +1 required first aid. If they crossed a threshold, add an additional +1 required first aid

ELECTRONICS
The skill requirement is based on amount of wiring/usage of the CBM:
1 - No wires
2 - Stores power
3 - Simple power generators
4 - Simple wiring/uses power
5 - Complex wiring

Additional skill requirement:
Add one quarter (rounded up) of the first aid skill required for the CBM as additional electronics skill requirement (e.g: the telescopic eyes CBM would have a 7 electronics requirement)

COMPUTERS
The skill requirement is based on the size/complexity of the CBM:
1 - Small/simple
2 - Medium/basic
3 - Large/advanced
4 - Huge/expert
Whichever of size or complexity is higher is the skill requirement

Additional skill requirement:
Add half (rounded up) of the first aid skill required for the CBM as additional computer skill requirement (e.g: the telescopic eyes CBM would have an 8 computers requirement)

INTELLIGENCE REQUIRED
No intelligence is required, however int should act as a modifier for success chance; 8 gives no benefits, and scores above or below modify success chance on a logarithmic scale. 
The logarithmic scale prevents people from cheating the system by boosting int with drugs.

This represents how intelligent people can perform pattern recognition and reverse-engineer IRL

ADDITIONAL IDEAS
The lore and realism both indicate that if CBMs exist, there should be some kind of instruction manual for installing them. CBMs are commercial items, and they are likely being created or improved all the time. It makes little sense to find databases of instructions for multiple CBM installs in the same place. Also, the autodoc has to be programmed to work on the player’s body, so modules that give a 100% success rate are unrealistic. 
What is realistic, is instructions for a single CBM (it could be any combination of for the autodoc or player, on paper or on a usb). These instructions would increase the success chance for the CBM. They would not be consumed and would halve the necessary first aid/electronics skill (but not computers, the player still has to program the machine)

The MD and autodoc specialist profession traits should also increase success chance.

Failed installations could also give an increased chance for the install to succeed next time (learning from mistakes and all), but that sounds much harder to implement:

**Comment by Firestorm01X2** [comment]
Was issue resolved?

**Comment by Firestorm01X2** [comment]
@kevingranade 
Was issue resolved?

**Comment by Firestorm01X2** [comment]
Issue was not resolved.
I thought there is stale bot for closing old issues.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Issue was not resolved.
> I thought there is stale bot for closing old issues.

Right, but issues can be closed manually too. This issue is pretty old, nobody worked on resolving it (i.e. opened a pr or held a further discussion) - that would be a valid candidate for a stale bot. Also issue can be invalid too and closed because of that.
