### ISSUE TITLE
Speed reduction reason is unclear "Inanition"

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#27835]
**Describe the bug**  
Charecter has some state that is vauge as to why? Causing negitive impact. 

**To Reproduce**  
Unsure?

**Expected behavior**  
States need to be clear as to what they are and what they do. I had to google this word Inanition and got several definitions of it. Some of these were legal documents. We should try and avoid using terms that are not commonly known or clear no matter how clever we think they are. This word can mean lack of wanting to live either via food shortage or just lack of will? Shouldn't have to google terms when a simpler more common term could be used. 

**Screenshots**  
![screenshot_2019-01-24_09-36-47](https://user-images.githubusercontent.com/12091471/51693388-16e61180-1fbc-11e9-85dc-f261f2bb0fff.png)

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux x64
 - Game Version: 0.C-37037-g096dabd9b7
 - Graphics version: Does not matter
 

**Additional context**  
Because this is an ambiguous term there is no way for the player to known exactly what they should do to remedy it.... Should I eat, listen to muisc, read??

**Comment by kevingranade** [comment]
Merged fix
