### ISSUE TITLE
Build 8467 - Martial Arts Selection Disapeared from Character Creation

### ISSUE THREAD

**Issue by Kibawan** [CleverRaven/Cataclysm-DDA#27831]
This is my first time reporting a issue, and english isn't my first or second language, sorry.

After the update to the new build, every time i try start a game with any kind of martial arts (Melee, Defence, Shaolin, etc...) i do **not** receive the pop up that let me **choose** the Style. Defauting to the last in the list.

**Comment by ifreund** [comment]
Can't reproduce this. Could you give some more info please? Any mods loaded? What operating system are you on? Did you try it on a fresh world?  Anything you can think of that might be specific to you're situation really.

>This is my first time reporting a issue, and english isn't my first or second language, sorry.
No worries man, your english is great!

**Comment by Kibawan** [comment]
Ok! I try several worlds and scenarios, the only one's that display the Style Selection Pop Up were the ones with the Martial Artist Trait (Martial Artist, Blackbelt). All the others professions and scenarios don't give the option and jump strait to "Wait while we are building your world" thingy. 

Is a oportunity to tell too that LUA (Fun) is not ever given any itens (xD)

I'm using Windows 7 Ultimate. I Can't think anything specific to the problem, i test the game clean, no mods and works normaly, i even use the nuke option of deleting the game, making a CCleaner pass, and restarting, still after download everything again the game still don't let me choose the Style. My mods are in LOAD ORDER:

CORE CONTENT PACKS

Dark Days Ahead

REVALANCING MODS

Filthy Clothing

ITEM ADITION MODS

Craftable Gun Pack

REBALANCING MODS
 
Safe Autodoc

CORE CONTENT PACKS
Bright Nights
DDA: Lua
DDA: Lua (Fun)
DDA: Lua (Items)
DDA: Lua (Skills)
DDA: Lua (Traits)

ITEM ADITION MODS

Bens GF recipes
Bootleg Walkers
Extended Realistic Guns
Growable Pots
DeadLeaves Fictional Guns
Icecoon's Arsenal
More Survival Tools

VEHICLE MODS
Boats

ITEM ADDITION MODS

MST Extra*
Makeshift Itens MOd
Medieval and Historic Content
Mythological Replicas
Craft Ammo Mags & Belt Links
Craft Ammo Mags - ERG

*MST Extra is Manualy Instal. (Tested with and without it)

CREATURE MODS

DinoMod
Draco's Dog Mod
Modular Turrets
Salvaged Robots

MISC ADDITIONS
Crazy Cataclysm
Mining Mod
Mutant NPCs

BUILDINGS MODS
Beta National Guard
Big River Building Pack
More Locations
Fuji's More Buildings
Mapgen Demo
More City Locations
Oa's Additional Buildings Mod
Urban Development

VEHICLE MODS
Carts to Wrecks
Folding Parts Pack
Vehicle Additions Pack
Tanks and Other Vehicles

NO CATEGORY
(DP_RP) REMIX Indicators
Jury-Rigged Robots
EXTENDED_BUILDINGS

REBALANCING MODS
Classes and Scenarios Mod
Manual Bionic Installation
Sleep Deprivation
StatsThroughSkills

**Comment by ifreund** [comment]
>i test the game clean, no mods and works normally

Sounds like the problem is caused by one or more of the mods then, not a bug in the base game. 

If you can isolate which mods are causing the issue, you may be able to talk to the mod author(s) about fixing it.

**Comment by OhDC** [comment]
I have the same issue and narrowed it down to the "Medieval and Historic Content" mod. 
No idea what the issue is within said mod though.

**Comment by Kibawan** [comment]
I can **confirm** that. it is the **"Medieval and Historic Content"** mod, i also don't know why. Any help with fixes for dummies are appreciate XD.
