### ISSUE TITLE
CBM installation fails with Autodoc should have chance to return CBM back.

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#27837]
**Describe the bug**  
Currently CBM installation fails always consumes CBM itself , no matter seriousness of error.
Realistically it should be able to cancel operation and remove CBM from the player body. It can be skill dependant and rely on type of error during installation.

Reasons:
* Autodoc can remove CBM from player in the workable condition already: https://github.com/CleverRaven/Cataclysm-DDA/pull/24408
* Autodoc realistically should contain algorithms of emergency cancelling operation and removing CBM. Failure may happen on every stage of operation. Autodoc can't just forget about CBM inside. And since it "knows" how to retrive it - it can use that alghoritms.
* Trying to carafully remove CBM in workable condition may help to preserve patient health (or life) during operation. So it is logical choice on failures.  Damaged CBMs may dangerous. We all knows that.
* Econimical note- CBMs costs money, So trying to preserve expensive thing after failures is obvious option.

**To Reproduce**  
1. Try to install CBMs and fail the installation.

**Expected behavior**  
Autdoc has chance dependent on error to retrive CBM. Of course Anashetic kit should be consumed anyway. Installing failed CBM is obvious exception.

If error was serious enough player should get burnt CBM back.

**Actual behavior**  
On any CBM fail (with exception of installing failed CBM) CBM dissapears without any message and explanation. It is just gone. I may have sense during manual installation but not during Autodoc operation.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 X64
 - Game Version: 0.C. 8467
 - Graphics version: Tiles
 - Mods loaded: Default

**Alternative approach**  
Always restore CBM on fails. Installing failure CBM is only exception.

**Comment by kevingranade** [comment]
That's part of the example from the issue template.
