### ISSUE TITLE
Withdrawing cash from ATM to WIELDED card doesn't give money.

### ISSUE THREAD

**Issue by DoomAngelBlade** [CleverRaven/Cataclysm-DDA#27834]
8458 is my version
If you withdraw some cash from ATM while WIELDING a card - withdrawn cash is not added to card
If you put card in inventory and withdraw money form ATM - it all works perfectly.

**Comment by MetroidHunter** [comment]
Ive managed to recrete this locally and will be looking at fixing it soon!

**Comment by kevingranade** [comment]
Fixed by #27942
