### ISSUE TITLE
Soup portions after nutrition update

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#27855]
Base Soups recipes now produce only 1 portion.  Why? I suppose it's mistake. 
Before nutrition update, it was 4 portion per 1 base soup recipe.

**Comment by ynemo** [comment]
just in case, 4 portions of soups = 0.25 L (was before update)

**Comment by KorGgenT** [comment]
https://docs.google.com/spreadsheets/d/1n1roPzIsRvABg3Ry0q7SPxnUK_C0GR9cjK27m4cF9ok/edit#gid=1724068009

Here are sources from the USDA
also: try crafting them. your calories out will equal your calories in.

**Comment by ynemo** [comment]
I dont get it.
I just made 0.25 L ( 1 portion? ) of wood soup. 642 kCal.
but according to recipe, it should be 304 kCal 
why there are different numbers in recipe and in actual product ?

according to google doc, there are should be 4 charges in this particular wood soup, but i see only 1.
![image](https://user-images.githubusercontent.com/24881844/51747487-b38ed900-20ba-11e9-9a13-95fcc71f7400.png)

**Comment by ynemo** [comment]
soups were really comforting food product, U could take 1 thermos with 12 portions of nice hot soup and it was enough for a long day of lonely survival.  If u have some traits which reduce ur nutrition need, having a lot of portions could be useful. Also, 8 quench per portion is 32 quench per 0.25L, so soups were good for ur thirst, So u dont need to take a lot of food with u, just little drinks and container with soup was enough. 

But i dont get, why there are different numbers in recipe page (304 kcal for wood soup), and 642 kcal in plastic bottle?

**Comment by KorGgenT** [comment]
> soups were really comforting food product, U could take 1 thermos with 12 portions of nice hot soup and it was enough for a long day of lonely survival. If u have some traits which reduce ur nutrition need, having a lot of portions could be useful. Also, 8 quench per portion is 32 quench per 0.25L, so soups were good for ur thirst, So u dont need to take a lot of food with u, just little drinks and container with soup was enough.
> 
> But i dont get, why there are different numbers in recipe page (304 kcal for wood soup), and 642 kcal in plastic bottle?

That would be the recent recipe inheritance stuff I put in.
now, whenever you craft a food, it actually gives you the calories based on the ingredients you put in, rather than the direct number in the json.

**Comment by ynemo** [comment]
i see, i suggest give all soups 32 quenching quality.

**Comment by Barhandar** [comment]
>What's the point of having four charges each with 15 kcal? do you really want that?

If it has quench to back it up, yes. And 150-ish kcal per portion of woods soup.

**Comment by KorGgenT** [comment]
> > What's the point of having four charges each with 15 kcal? do you really want that?
> 
> If it has quench to back it up, yes. And 150-ish kcal per portion of woods soup.

you're not gonna get 150 kcal in 1/4 cup of soup.
most soup serving sizes are 1 bowl, which is 2 cups. i'm sorry you have to find out this way, but this is a volume nerf. I agree with reassessing quench values, however.

**Comment by Barhandar** [comment]
>you're not gonna get 150 kcal in 1/4 cup of soup.

And yet woods soup gets 642 kcal in 1 cup of soup, which means 160.5 kcal in 1/4 cup.

This isn't a volume nerf. This is you _blatantly not understanding why the old values were there, yet interfering with them_.

**Comment by ynemo** [comment]
> Who the FUCK eats soup in half a liter volumes?
well, irl soup portion is about 0.3L

**Comment by Barhandar** [comment]
Actual soup _plate_ is 250ml exactly, and I often eat it partially. Also, your argument is erroneous in the first place - that portioning doesn't apply to low-kcal food doesn't mean that it shan't apply to high-kcal food either, i.e. it's perfectly possible to have chicken soup at 1 charge with high quench and all the actual soups at 2-4 charges to maintain approximate 150-200 kcal per portion.

**Comment by int-ua** [comment]
I feel the urge to remind everyone that the nutrition rebalance was quite big change in a big system. Some problems and debatable decisions were almost unavoidable. Being more pollite to people may yield better results in a collaborative project that CDDA is.

**Comment by FuelType-Memes** [comment]
> 
> 
> I feel the urge to remind everyone that the nutrition rebalance was quite big change in a big system. Some problems and debatable decisions were almost unavoidable. Being more pollite and respectful to authors may yield better results in a collaborative project that CDDA is.

Paraphrasing my ex-senior: Big changes in a big system require big testing

@KorGgenT is awesome for even tackling the problem of 10kcal of starting ingredients somehow becoming a 1000kcal dish, but I feel some sympathy for people being frustrated. Old system followed the logic of: "Ahha, the recipe says I will get 4 0.25L portions with 123kcal each", but the new system is obscure so you just don't know what to expect. And in a game where you need to manage limited resources so tightly (esp in the beginning) that's painful

**Comment by kevingranade** [comment]
Fixed by #27925
