### ISSUE TITLE
Mess with Food recipies from flour

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#27852]
1.  Chockolate pancake  2188 kcal from 1 flour
     chockolate waffle 3177 kcal from 1 flour

2.  meat pie requires 30 flour now??? wow, it's a lot. 
     humble pie still requires 2 flour 

3.  fried dandelion has 17???? nutrition, only 17? why not to make 0.17? 
     onion ring has 634 kcal. Great, compared to dandelions. 

4.  total mess with soup recipes. Only 1 flour needed, but we can use macaroni (5 flour)

**Comment by cainiaowu** [comment]
Looks like typo some where, maybe you can pr a fix? They could all be simple json changes.

**Comment by ynemo** [comment]
5. (not flour, but anyway) Raw wasteland sausage now gives only 1 portion (should be 6).

**Comment by ynemo** [comment]
I dont get it.
I just made 0.25 L ( 1 portion? ) of wood soup. 642 kCal.
but according to recipe, it should be 304 kCal 
why there are different numbers in recipe and in actual product ?

according to google doc, there are should be 4 charges in this particular wood soup, but i see only 1.
![image](https://user-images.githubusercontent.com/24881844/51747487-b38ed900-20ba-11e9-9a13-95fcc71f7400.png)

**Comment by ynemo** [comment]
6. Multicooker makes 1 portion of sausage instead of 6 (probably this issue is concerning other recipes cooked by multicooker)

7. Maple sap weights too much.

**Comment by ynemo** [comment]
![image](https://user-images.githubusercontent.com/24881844/51789693-b104b000-219c-11e9-9578-73ad159e5089.png)

I am pretty sure, that "Lard" as a component of Chocolate pancake is used to grease baking sheet so that the cake does not stick.  There is no 0,5 kg Lard inside Chocolate pancake i suppose. So there is no reason to add 1000 kcal to pancake. 
If i made Chocolate pancake with cooking oil, it will be about 600 kcal.

**Comment by hyper2snyper** [comment]
so, you want to change some soup proportions? so that it equates what you put in?

**Comment by kevingranade** [comment]
#27925 fixed most of these issues, if there are any left open a new issue.
