### ISSUE TITLE
Crash when zooming map

### ISSUE THREAD

**Issue by settdigger** [CleverRaven/Cataclysm-DDA#27869]
**Describe the bug**  
Fatal crash when zooming in/ out

**To Reproduce**  
Press Z

**Expected behavior**  
Not crash

**Screenshots**  
![crash log](https://user-images.githubusercontent.com/19501199/51766868-0912b800-20b2-11e9-9eeb-84b6126d54c0.png)

**Versions and configuration(please complete the following information):**
 - OS: win10

 - Game Version :  0.C-37073-g5a18119 
 - Graphics version: Tiles
 - Mods loaded:  NPC needs, filthy clothing

**Additional context**  
Before the attached screenshot, the error message that displays is:

MinGw Runtime Assertion

Assertion failed

Program: F:\Downloads\cataclysm\cataclysm-tiles.exe
File: src/optional.h, Line 45

Expression: full

abort / retry/ fail

**Comment by settdigger** [comment]
Clarification:  the crash happens if you keep pressing Z.  Usually it moves from all zoomed in, to zoomed out if you press Z again from there. Now it crashes if you do that. You can zoom in once, or out once with Shift-Z, with no crash.

**Comment by settdigger** [comment]
The same thing also happens if you try to zoom out past the maximum.

**Comment by GoLoT** [comment]
Likely related to #27871 by comparing the stack traces.
