### ISSUE TITLE
Nutritional values of crafted items get messed up after save-load.

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#27877]
**Describe the bug**  
When you load a save, the nutritional values of the items you've crafted become different from what you've seen before the save.
![cataclysm-tiles_2019-01-25_21-31-48](https://user-images.githubusercontent.com/7831163/51774098-fb2c5980-20e8-11e9-8584-bbec7aa709f2.png)

**To Reproduce**  
- Get bunch of cookware, some flour and some fat
- Craft bread and tallow
- notice its nutrition at 87/piece and 5754/piece respectively
- Exit game, then reopen it and continue from where you've left off
- See that the nutritions are different from before - at 877 and 954 respectively

**Expected behavior**  
The things remain as I've left them :P 

**Versions and configuration(please complete the following information):**
 - Game Version: 0.C-37065-g1aeee0e
 - Mods loaded None

**Comment by KorGgenT** [comment]
So i'm pretty sure I might have a clue as to what's causing it: I added a new variable to the item class ```recipe_charges``` and I don't know if it's being saved. I am unfortunately not clued into the saving code at this time
