### ISSUE TITLE
Morale decays insanely quickly now

### ISSUE THREAD

**Issue by KITbutler** [CleverRaven/Cataclysm-DDA#27875]
**Describe the bug**  
I believe #27803 made some mistake in their adjustments as morale modifiers now decay alarmingly quickly. For example buffs from playing music decay before being reapplied.

**To Reproduce**  
1. Wear and play a tuba
2. Pass an hour
3. Check your morale modifiers and note 0-10 **total** morale from the instrument you are still actively playing!

Alternatively:
1. Cheat a character to 30+INT and Fast Reader
2. Read a nice morale book such as "big book of short stories" (should take about 4min/chapter)
3. **Immediately** check morale (should be +25)
4. Pass 5 minutes, notice morale has decayed to about +4
5. Pass another 5min, notice morale is completely gone!

**Expected behavior**  
Morale effects other than the specific instance described in #27733 should be restored to their former duration and/or vetted for further unit errors.

**Additional context**  
Since no one complained about non-Gourmand morale and other effects seemed fairly reasonable I assume the previous behaviour was closer to the intended balance point. Both examples above are completely ridiculous no matter what the intended balance point for Focus gain is.

EDIT: observed on 0.C-8473 Windows Tiles build.

**Comment by moxian** [comment]
I'll add a personal anecdote: I'm playing a chain-smoker starting character, smoked only once at the start of the game, and I'm yet to see any effect on my morale. I occasionally see something about "you crave for nicotine" in the game log, but by the time I check the `v` menu, there's nothing there.

**Comment by rselias** [comment]
I'm 99% certain this isn't a bug, but a balance issue. I tested more than the initial Killed Innocent morale effect that I had noticed, and every one lasted ten times as long as it was supposed to. #27803 didn't make any mistakes, it's just that you're used to morale effects lasting way longer than they're supposed to, and many effects may have been balanced without paying attention to how much time was actually passing.

The default morale boost length is six minutes, and many morale effects do not define their length. I couldn't find the length of the book buff at a cursory look, but I'm guessing it's one of the undefined ones. So any that were previously defaulting to incorrectly lasting an hour now only last six minutes, like the code says they should. Some effects are clearly _very_ short, like the music buff lasting a grand total of 5 turns.

Nothing should be reverted, but the duration or intensity of some morale effects should be rebalanced. For example, if music is meant to boost your morale only while you're actively listening, it should keep its super short duration, but get a higher bonus so it can stack to the same values it did before.

**Comment by rselias** [comment]
Agreed, though some effects are clearly working better now. Previously, Pyromaniac was not only a free negative, but actually an easy positive trait plus free bonus points, as it didn't lower your morale unless you went 2.5 days without lighting a fire. Now you have to light one every six hours, which I think makes it a much better balanced trait than before. Fire feels like a need, instead of a nice bonus every now and then.

Unfortunately, I left my work laptop in the office and won't have a proper dev environment until Monday, but I can see about setting up a basic environment on this computer and submitting a PR to address at least some of this.

**Comment by davidpwbrown** [comment]
This was a concern when I made the bugfix.
I know that when I made a morale effect, I put in a duration in turns - taking my cue from other morale effects and balancing it against that. I then tested it in-game, ( the game decaying too slow ) and balanced it against that.
I do wonder how many other morale effects were tested and included this way....

**Comment by DracoGriffin** [comment]
> I do wonder how many other morale effects were tested and included this way....

At least mine as I disclosed in Discord; since the arguments weren't looking right when I compared to other values and examples. So like 5%~ making/editing code, 20%~ compiling, and the rest were in-game testing length of effects and proper decay/drop off.

**Comment by I-am-Erk** [comment]
Given how long the morale decay bug was in the game (I believe since morale was introduced?), It's likely that many effects were balanced to the incorrect way. It does have to use the same timer system as everything else, but that means we'll have to track down all the erroneous durations.

**Comment by Night-Pryanik** [comment]
Should be closed after #27890?

**Comment by DracoGriffin** [comment]
I haven't noticed anything too abnormal since that PR, so I think it is safe to close for now. If there any other morale length problems, re-open with specific activities or items.
