### ISSUE TITLE
Police road blockade spawn incorrectly

### ISSUE THREAD

**Issue by DoomAngelBlade** [CleverRaven/Cataclysm-DDA#27879]
Screen explains all.
![image](https://user-images.githubusercontent.com/46872312/51776611-ad244f80-2102-11e9-83f7-7d100dfb29e4.png)
Mods(THIS MIGHT BE NOT MOD RELATED):
![image](https://user-images.githubusercontent.com/46872312/51776695-f5dc0880-2102-11e9-8b12-3b27fce36381.png)

**Comment by sneeze-attack** [comment]
@DoomAngelBlade are you referring to the barriers not being placed in a straight line or that the road barricade event spawned on a road curve?

**Comment by sneeze-attack** [comment]
I can try and rework the code to apply properly to intersections and road curves.

**Comment by ZhilkinSerg** [comment]
Should be resolved with #28195.
