### ISSUE TITLE
Crash (sorry, can't come up with anything more specific)

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#27872]
**Describe the bug**  
Crash. I got a popup saying something about "crash has happened" and "optional.h" and options to Retry/Abort/Ignore. I didn't think to memorize or screenshot it, expecting this info to be in crash.log (it wasn't). I chose Retry, and got presented with another error dialog. Contents being identical (or very similar?) to crash.log (below). Clicking OK made the program exit.

**To Reproduce**  
Unknown.
I was surrounded by zombies, entered a truck, started it up, accelertated forward, let go of the controls, hit zombies around me (still inside the truck), got controls again, changed acceleration to backwards (since I was not making progress due to numerous zombies in front), let go of controls again, continued to chaoutically smash zombies around me. Then crash happened. As far as I can tell, neither I nor my vehicle moved after I took the controls initially.

**Expected behavior**  
No crash.

**Screenshots**  
not applicable

**Versions and configuration(please complete the following information):**
 - OS: Win7
 - Game Version: 0.C-37065-g1aeee0e. Specifically obtained from the daily build just today as [cataclysmdda-0.C-8472](http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/cataclysmdda-0.C-8472.zip)
 - Graphics version Tiles
 - Mods loaded No mods

**Additional context**  
The thing generated crash.log with the following content:

```
CRASH LOG FILE: config/crash.log
VERSION: 0.C-37065-g1aeee0e
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:
    @0x549B38[cataclysm-tiles.exe+0x149B38]
    @0x549ED9[cataclysm-tiles.exe+0x149ED9]
    raise+0x18C@0x77175E8F[msvcrt.dll+0x65E8F]
    abort+0x37@0x77178EA2[msvcrt.dll+0x68EA2]
```

Not long before the crash I encountered #27850 (and chose to ignore it)

Attaching debug.log, but it doesn't seem to be super helpful:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2797633/debug.log)

Given the absolute lack of any kind of meaningful backtrace (unless, of course, those two memory locations are of any use), I won't be upset if this issue gets closed with zero investigation.

Last save happened quite a long time ago. Can provide upon request if needed.

**Comment by GoLoT** [comment]
Is it possible that a zombie or a collision destroyed one of the tiles in your vehicle?

If that's the case this could be related to #27871

**Comment by moxian** [comment]
Very possible, The truck was swarmed with zombies.

**Comment by Zmedaris** [comment]
Yes, it seems this might related to vehicles and stuff on them being destroyed. I just had this error occur while I was kiting soldier zeds through wreckage, and obviously they were tearing apart the crashed heli copter, and that's when the crash occurred.

![screenshot 751](https://user-images.githubusercontent.com/12032854/51775491-c699ad00-20aa-11e9-8b05-c9befca5fae1.png)

![screenshot 752](https://user-images.githubusercontent.com/12032854/51775507-d44f3280-20aa-11e9-939f-111260487733.png)

**Comment by GoLoT** [comment]
It has to do with map memory trying to access a vehicle tile that doesn't exist anymore. More info in #27871
