### ISSUE TITLE
Nutrition of crafted food items should no longer be displayed in the crafting menu.

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#27873]
**Is your feature request related to a problem? Please describe.**  
In the crafting menu, when looking to craft a food item, you can see the nutritional value of the resulting item. Except with the latest food crafting overhaul that value is misleading, and it's more along the lines of "nutrition in = nutrition out" (with the exception of NUTRIENT_OVERRIDE items).
This is misleading, and leads to confusion, since the resulting crafted items most of the time have a totally different nutrition from what is displayed in the crafting menu. See also #27852 #27855 demonstrating user confusion

**Describe the solution you'd like**  
Show "Calories (kcal): sum of its parts" instead of current "Calories (kcal): 1234" for items with no NUTRIENT_OVERRIDE tag. The specific number should probably stay for things which do have the tag (e.g. bone broth)

**Describe alternatives you've considered**  
Uh.. Leave things as is? That's confusing and each player would have to figure it out, and be upset in the meantime.
The "Calories" line can be removed completely instead of showing "sum of its parts" (and still show up for NUTRIENT_OVERRIDE). I'm not sure if this is better or worse.
One can probably make a dialog that would preview the item before actually crafting it, and would show the predicted nutritional value for the ingredients chosen, but that sounds way too complicated to implement, and probably somewhat distracting to play.
I don't feel strongly about the suggested wording - feel free to change to whatever sounds better. 

**Additional context**  
none

cc @KorGgenT

**Comment by ynemo** [comment]
I totally disagree.
First of all, there must be clear explanation how kcal numbers are calculated in recipe page. I suppose 1st product in each row is taken. If it is true, then there is no "user confusion". 
Chocolate pancake 2158 kcal is a mistake in nutrition calculation, caused by taking 1000 kcal from Lard. But lard is used to grease baking sheet so that the cake does not stick, there is no lard inside pancake i hope. 
here is some screens and etc https://github.com/CleverRaven/Cataclysm-DDA/issues/27852#issuecomment-457842852

**Comment by KorGgenT** [comment]
calculating the possible nutrient ranges will be very taxing. I do not think it will even be a good idea to do something like that.

**Comment by ynemo** [comment]
> calculating the possible nutrient ranges will be very taxing. I do not think it will even be a good idea to do something like that.

Is it possible to use flat number of kcal from products, that are used to help with cooking, but are not represented inside of a dish? For example cooking oil, lard, tallow in some particular recipes as cakes?

**Comment by ynemo** [comment]
also, i always play gourmand, so overeating is not a problem for me.
But looks like non-gourmand will barf after eating such chocolate covered lard-pancake

**Comment by moxian** [comment]
> First of all, there must be clear explanation how kcal numbers are calculated in recipe page.
Is "Calories (kcal): sum of ingredients' calories" clear enough explanation? This is how it works currently.


> Chocolate pancake 2158 kcal is a mistake in nutrition calculation, caused by taking 1000 kcal from Lard. But lard is used to grease baking sheet so that the cake does not stick, there is no lard inside pancake i hope.
I personally would agree with moving lard/cooking oil to tools for fried dishes. Maybe a better solution would be to have a tuning knob on what percentage of the ingredient does end up inside the item (vs the part that gets discarded). But that's besides the original point.

**Comment by ynemo** [comment]
> Is "Calories (kcal): sum of ingredients' calories" clear enough explanation? This is how it works currently.

it's not even close clear, results kcal are different from what we see in recipes.

**Comment by kevingranade** [comment]
The range of values should be possible to supply for each recipe.

**Comment by moxian** [comment]
> it's not even close clear, results kcal are different from what we see in recipes.

Correct. This is why i propose to remove the kcal that you see in recipes completely.
I propose to either completely remove the `Calories (kcal): 1234` line or replace it with (literal!) `Calories: sum of the ingredients`.  I.e. instead of 2 words and one number you'll see 5 words and zero numbers.

Range of values sounds good, but I fear players might think it's random and dependent on chance, rather than ingredients. As long as that's cleared out, I'm totally fine.

**Comment by KorGgenT** [comment]
I like the range idea; should also give room to show definite values for the different overrides.

**Comment by ynemo** [comment]
> Correct. This is why i propose to remove the kcal that you see in recipes completely.

Why u dont ask urself, what is this numbers that we see in recipe? How they are calculated? Which ingredient gave this sum of kcal?

**Comment by ynemo** [comment]
min max range kcal would be great

**Comment by FuelType-Memes** [comment]
Maybe display the possible kcal outcome when selecting ingredients?

Otherwise it's just checking all the values yourself, writing them down and calculating the best kcal outcome possible with the stuff you have on hand
