### ISSUE TITLE
New UI: Power numbers are displayed in the incorrect place on the sidebar

### ISSUE THREAD

**Issue by FoolsGold45** [CleverRaven/Cataclysm-DDA#27878]
**Describe the bug**  
In the screenshot below, the numeric value of the bionic power is placed directly to the left of the Power label, as opposed to the right where it presumably should be. Captured in an unmodded world on version 8473

**To Reproduce**  
1. Mutate "debug bionic power" through the debug menu
2. Activate to give bionic power
3. Observe where the numbers appear in the sidebar

**Screenshots**  
![capture](https://user-images.githubusercontent.com/46657256/51776149-1174ee00-20c6-11e9-8469-59e673088848.PNG)

**Comment by nsklaus** [comment]
sorry about that, 
this is fixed already, in [#27809](https://github.com/CleverRaven/Cataclysm-DDA/pull/27809)

**Comment by MetroidHunter** [comment]
Im throwing up a PR to align the power as referenced above since #27809 is a larger refactor and is undergoing some discussion

**Comment by kevingranade** [comment]
Fixed by #27907
