### ISSUE TITLE
Trying to start a vehicle crashes the game

### ISSUE THREAD

**Issue by BoxGod** [CleverRaven/Cataclysm-DDA#27884]
**Describe the bug**  
Trying to start a car started crashing the game. I'm not sure what could be causing it,so I'll add the save and crash log.

**To Reproduce**  
1. Get in a vehicle with NPCs in it
2. Try to start the engine

**Screenshots**

![cataclysm-tiles_2019-01-26_01-24-47](https://user-images.githubusercontent.com/47045912/51779710-422a4700-2109-11e9-802a-b4e7cbdae15c.png)

![2019-01-26_01-26-10](https://user-images.githubusercontent.com/47045912/51779724-66862380-2109-11e9-9eee-3bd54720c733.png)

**Expected behavior**  
The vehicle starts moving.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7 64 bit
 - Game Version: 0.C-37074-g44abf4a
 - Graphics version: Tiles
 - Mods loaded: 
[
  "dda",
  "no_npc_food",
  "novitamins",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "More_Survival_Tools",
  "more_locations",
  "oa_additional_buildings_mod",
  "Urban_Development",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "necromancy",
  "DP_XOTTO_INDICATORS",
  "No_Explosive_Zombies",
  "StatsThroughKills",
  "StatsThroughSkills",
  "manualbionicinstall"
]

**Additional context**  
Crash log: CRASH LOG FILE: config/crash.log
VERSION: 0.C-37074-g44abf4a
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x549B68[cataclysm-tiles.exe+0x149B68]
    @0x549F09[cataclysm-tiles.exe+0x149F09]
    SMPEG_error+0x3DAF3@0xB90E75[cataclysm-tiles.exe+0x790E75]
    @0x6FEC9D3
    CreateProcessAsUserW+0x12E42@0x758803B7[kernel32.dll+0x503B7]
    RtlKnownExceptionFilter+0xB7@0x77A550E7[ntdll.dll+0x750E7]
    RtlInitializeExceptionChain+0x36@0x77A197D5[ntdll.dll+0x397D5]

Save file:
[King.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2798362/King.zip)

**Comment by BoxGod** [comment]
Actually,it doesn't seem to be vehicle related-I generated a new world and working around for a while still caused a crash.

**Comment by GoLoT** [comment]
Likely related to #27871 and fixed by #27883 (launcher version: 8475).

**Comment by kevingranade** [comment]
Most likely map memory issue, please comment or open a new issue if you see this again.
