### ISSUE TITLE
Number of keypresses required by pry-on-examine has increased

### ISSUE THREAD

**Issue by ThinkInvis** [CleverRaven/Cataclysm-DDA#27880]
PR #27553 changed the workflow involved in opening nearby crates/locked objects via examination. Before change: adjacent crate/lock can be opened by `examine > directional key`; after change: adjacent crate/lock can be opened by `examine > directional key > down to select prying tool instead of "do nothing" > enter`. This has basically doubled the number of keystrokes required to pry something without using a specific tool.

PR #27865: While fixing a bug with the pry-on-examine code, I attempted to resolve the present issue by introducing two options (one each for crates and locked objects) to switch between the old and new behaviors. Debate arose as to whether the options should be included, and I decided to separate them into a new issue in order to allow the bugfix easier passage. The aforementioned PR, if passed, will still reduce the process to `examine > directional key > enter`, however...

- Should a new option be added that toggles between 'auto-pry on examine' and 'tool prompt on examine'?
- If not, is there any other way to restore the old prying behavior (optionally or otherwise)?

**Comment by moxian** [comment]
Third option!
I think rearranging the options in the dialog, so that `pry` is the first option would satisfy all the parties. No need for extra config values.

If you're examining because you're unsure what that item is - you would be happy to navigate around the menu when prompted.
Otherwise if you know what you're doing `examine > directional key > enter` seems very unobtrusive to me. It's technically only one keystroke less than the current situation, but needing only a single direction key makes the flow very good in my opinion.


Incidentally, it turns out that in the current game version chosing to "Leave it alone" still makes you open the crate. So you can check this out to see how it feels right now :P

**Comment by ThinkInvis** [comment]
That last thing is what 27865 fixes, and as of right now it also includes the first (setting pry as the first option). Crates and locks are currently auto-opened if you have one, and ONLY one, prying tool at hand. This should still be the case if 27865 is merged; the fix applies to the tool selection prompt being erroneously displayed after the auto-pry has already happened.

I'd be happy to leave it at that (auto-open if only one tool is available)... but what if I'm carrying a hammer around to hammer things, as well as a crowbar to pry things? Hammers now have a Prying quality of 1, so if I try to open a crate by examining it, I'll get the prompt for selecting between the hammer, the crowbar, and doing nothing. If I'm _not_ carrying around a hammer, I won't get a prompt -- the crate will just pop open once I examine it.

The point of this issue is that I don't encounter many situations... or, well, any at all, where I want to examine a crate without opening it; as such, I'm effectively punished for carrying that hammer around. If someone can come up with such a situation, then the current behavior is still a problem for them -- that someone is instead punished for _not_ carrying around multiple prying tools.

**Comment by KITbutler** [comment]
How does the game calculate the actual prying action in detail? Is there any situation where one would *want* to choose a specific *inferior* tool for prying but (a)ctivating it is not feasible?

Otherwise the game should just automatically pick the best tool for the job and only show a choice menu if both prying and picking are an option. And definitely not offer the firefighter belt *holding* my Halligan bar as a separate prying tool then telling me I "cannot get sufficient leverage with that item".

**Comment by ThinkInvis** [comment]
Not at present, but such situations may arise in the future if a state-changing (powered, damaged-on-use, etc.) prying tool is added. If it has a very high prying quality, players may wish to save it (and its associated charges) for prying things that are that difficult.

There IS a lesser version of that issue that may exist ingame right now: time taken. If the player has a crowbar in their backpack and a hammer currently wielded, using the crowbar to pry a crate open _should_ take longer than using the hammer (whether it does right now is another question; if it doesn't, that's a problem). In this case, using the hammer may be desirable: it has a slightly higher chance to fail than the crowbar, and may pry slower, but taking the crowbar out and putting it back after prying will eat up a lot of time on its own.

Adding picking to the lock examine menu is something I'm looking into, but it seems like a hard change to make. I'll be making a new issue about it shortly.

**Comment by CoroNaut** [comment]
I extremely like the option to 'auto-pry on examine'. This gives any player the quality of life improvement and doesn't change the style of the game at all.

**Comment by ThinkInvis** [comment]
A possible solution has been found in the time since this issue was posted; see the PR linked directly above (#27965). Basically, instead of being a config option buried in a menu somewhere, it's an ingame toggled mode similar to Safe Mode. It not only applies to prying things, but also to any number of other cases where the player might want to only _sometimes_ be given a choice/are-you-sure prompt. Another use case that's being considered: instantly heating food up when selected from the (E)at menu, versus getting a prompt as to which heating tool to use.

Safe Mode (for wandering into monsters) already exists, so adding what's basically an Unsafe Mode (for general gameplay) doesn't seem to change the style of the game much. The PR is also marked as [CR], in part so people can discuss exactly that kind of thing. Biggest problem I can see with it, at present, is that the PR is currently affected by the 0.D Feature Freeze. If this issue _really_ needs a fix before the 0.D release -- and I believe it doesn't, it can probably wait -- then a new option is probably the best choice... if options aren't frozen too.
