### ISSUE TITLE
Exclude driven vehicles from map memory feature

### ISSUE THREAD

**Issue by rm-code** [CleverRaven/Cataclysm-DDA#27905]
**Is your feature request related to a problem? Please describe.**  
(I searched for map memory tickets, but haven't found one describing this problem...)

With the new map-memory feature some vehicles like trucks are cut in half when you start driving:
![image](https://user-images.githubusercontent.com/11627131/51790648-7b5dc800-2198-11e9-891f-0fcafde7c8aa.png)

This makes it a lot harder to control bigger vehicles, just feels weird (for a moment I thought my truck broke in half) and is pretty unrealistic IMO - IRL I still have a "feeling" for where the rest of my vehicle is, even if I don't see it.

**Describe the solution you'd like**  
Exclude driven vehicles from map memory feature -> once you enter you "see" all the tiles belonging to the vehicle.

**Alternative**
Remove "remembered" vehicle tiles from map memory while moving - even if you don't see the tiles.

**Comment by GoLoT** [comment]
Ideally this should also apply to (G)rabbed vehicles/furniture, right now they leave a trail at night.

**Comment by kevingranade** [comment]
> Exclude driven vehicles from map memory feature

This is how it's intended to work, I think I might have disrupted that with my caching work.

> IRL I still have a "feeling" for where the rest of my vehicle is, even if I don't see it.

Sure, you just need to develop that same "feeling" in-game. Alternately add some lights so you can see the rear with your side mirrors. 
> once you enter you "see" all the tiles belonging to the vehicle.

That's not the same thing, map memory should only ever show you things you've seen at a location at that same location.

> Remove "remembered" vehicle tiles from map memory while moving - even if you don't see the tiles.

This might be what I do short term, if the last thing you saw at a location was part of a moving vehicle and you move the vehicle, the memory for that area is just erased.  In the above screenshot the "detached" vehicle chunk would be rendered as unexplored space unless it is viewed again.

**Comment by kevingranade** [comment]
> Does "unexplored" mean we'd render them as black squares?
Yes, this is a limitation of the current system, because it can only remember one tile for a given square.  In order to replace the moved vehicle with the tiles under it, we would have to either magically reveal whatever is under the vehicle (including if it's a manhole cover or some other unexpected terrain feature), or add another layer to map memory to remember the ground underneath vehicles in addition to the vehicles themselves.

I might look into doing something about this later, but for now it's a far more involved change than I want to get into.

**Comment by ZhilkinSerg** [comment]
Should be fixed in #28031.
