### ISSUE TITLE
shrub road block

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#27919]
A single shrub can stop my vehicle from moving, my vehicle accelerates 5 mph but it's very very large than the shrub, i can't even ram through it

**Comment by Eliijahh** [comment]
I guess it depends on what kind of shrub is the in-game "shrub". If it is like the following image, then I would say it should stop a slow moving vehicle:
![](https://gogreenlawnservices.com/wp-content/uploads/2018/05/tree-shrub-1.jpg)

**Comment by KITbutler** [comment]
For a stationary vehicle the defining factor is the torque, or in game abstractions the acceleration its engines can provide. A V12 motorbike should happily crush through/smash itself to pieces. Your average loaded diesel truck which can't even maintain speed on a slight incline not so much.

**Comment by kevingranade** [comment]
Redundant with #27283
