### ISSUE TITLE
Rapid Metabolism mutation is unpurifiable 

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#27917]
**Describe the bug**  
Rapid Metabolism is the only pre-treshold mutation that is unpurifiable. Yet there are many mutations that cancel it. It creates a lot of chaos for unaware player. It wasn't allways like this, this change was added together when mouse mut. tree was added, without any explaination.

**To Reproduce**  
1. Be relatively new player that rarerly checks hidden game mechanics on internet, choose robust genetics in order to mutate later.
2. Get some good mutations, when you get anything bad, you use purifier untill all bad mutations are gone, possibly with some good ones.
3. Drink rat/mouse mutagen or fight Ratking, get Rapid metabolism. 
4. Try to get rid of it. Prepare a lot of purifier. Loose all good mutations, but not this one. You expected purifier to work like with every other pre-treshold mutation, but the game did not tell you this information. And you still dont know that to get rid of it, you need to drink a lot of other mutagens, and hope for luck to get some other metabolism mutation.

**Expected behavior**  
Rapid metabolism being purifiable.

**Versions and configuration:**
 - OS: Windows 10
 - Game Version 0.C-37094-g5da8e39
 - Graphics version Tiles
 - Mods loaded:

Dark Days Ahead
Disable NPC Needs
Filthy Clothing
Mutant NPCs
Beta National Guard Camp
Sleep Deprivation
Z-levels enabled

**Comment by KITbutler** [comment]
The premise is not *entirely* true, Genetic Chaos is not purifiable either and has even been noted in the [wiki](http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Genetic_Chaos) as such. That one seems like a more deliberate choice to punish careless spamming though.

**Comment by sneeze-attack** [comment]
I'm in favor of this change.

Maybe the conditions needed for a trait to be unpurifiable need to be defined? Would it be only post-thresh traits with a few sensible exceptions (like @KITbutler mentions above with Genetic Chaos)? It would make sense, but if this change is up for discussion that would likely need to be figured out to proceed.

**Comment by SirPendrak** [comment]
Genetic Chaos is not purifiable, but it requires Metallassomaiphile wchich is post-treschold mutation. So it kinda makes G.Ch. post-tresch too I guess?
