### ISSUE TITLE
Mutation changes is having issues.

### ISSUE THREAD

**Issue by JedasKane** [CleverRaven/Cataclysm-DDA#27929]
Every time I try to start up a world with the mod installed this error pops up.

 DEBUG    : Error: data/mods//Mutation changes//mutation_category.json: line 2:5: member not found: threshold_mut

[
    {
     ^

        "type" : "mutation_category",
        "id" : "mutation_tortoise",

 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 695

**Comment by ZhilkinSerg** [comment]
That is a third party mod we cannot fix in this repo. Please contact mod author or fix mod locally by your self. Example of what you need to do is here -https://github.com/chaosvolt/cdda-arcana-mod/pull/32 (you need to add node named `threshold_mut` with some value).
