### ISSUE TITLE
Character's Sprite flips around when using Arrowkeys but not Numpad

### ISSUE THREAD

**Issue by Substance455** [CleverRaven/Cataclysm-DDA#27926]
**Describe the bug**  
Recently, a update made your character's and monster's sprites face left or right depending on where they moved from. This happens to your character when you move with the arrow keys, but not with the numpad for some reason.

**To Reproduce**  
Try moving with both arrow keys and numpad and see the difference

**Expected behavior**  
I kinda expected the numpad to flip my sprite around, but it doesn't. It really should. 

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-37114-g7e78b20
 - Graphics version: Tiles
 - Mods loaded: Default Mods

This is a pretty sweet feature and I really didn't know this existed for a bit since I use the numpad for moving so much.

**Comment by Inglonias** [comment]
I did notice that this was happening with zombies, and wondered why it didn't happen to me. Using the arrow keys does indeed make this happen, but the numpad does not.
