### ISSUE TITLE
Horizontal Morale meter cut off with narrow sidebar

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#27927]
**Describe the bug**  
Horizontal morale meter is one space too far over to the right, and is cut off when using the narrow sidebar.
**To Reproduce**  
1. Start a game
2. Make sure you're using the narrow sidebar
3. In Options, set "Morale Style" to "Horizontal" in the interface tab.

**Expected behavior**  
I can see all three characters in the morale meter
**Screenshots**  
![image](https://user-images.githubusercontent.com/2125926/51805875-d77c2700-2240-11e9-9500-8a469f9c0fbd.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-37114-g7e78b20
 - Graphics version: Tiles
 - Mods loaded: N/A

**Comment by MetroidHunter** [comment]
I have recreated this locally and will have a PR for it shortly!
