### ISSUE TITLE
Hunter/Predator/Apex Predator post-threshold mutations require Bear as a mutation, but Ursine does not include any of them therefore making Carnivore a truly mandatory mutation to gain any of them

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [CleverRaven/Cataclysm-DDA#27924]
**Describe the bug**  
The entire description

**To Reproduce**  
1. With debug mutate, cross any threshold that gives, say, Predator.
2. Get Predator
3. Observe that you will get Carnivore.

**Expected behavior**  
The only mutation triplet that requires a virtual threshold mutation instead of being a part of threshreq -- there is something funny going on here. Either Bear should be removed from the prereqs or Ursine should be the only mutation path that allows you to have Hunter/Predator/Apex Predator without becoming a carnivore.

**Screenshots**  
![Mutation graph](https://vgy.me/bCVvST.png)

**Comment by PsyXypher** [comment]
This issue was brought up before with Rat; in getting some of Rat's keystone diet mutations (Eater of the Dead), you're most likely going to get Carnivore instead of the other mutations required. Rats are omnivorous in nature, naturally.

**Comment by mlangsdorf** [comment]
Bears are omnivorous and should be able to get Apex Predator and Sapiovore without requiring Carnivore.
