### ISSUE TITLE
Heating up items needs a hotkey

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#27937]
**Is your feature request related to a problem? Please describe.**  
Heating up food/drinks is something the player commonly faces, releasing 0.D without a hotkey assigned to going directly to the action, or from the % menu will not be appreciated by any of player base.
That and being able to do it using nearby items, having to grab that frying pan every time is needless key-presses unless I use the 'a' menu and need to arbitrarily locate it there.

**Describe the solution you'd like**  
Heating up items mapped to something convenient to use with minimal key-presses and no scrolling through lists required, being able to do it from nearby items

**Describe alternatives you've considered**  
More items eaten frozen at the cost of time taken and morale, honestly that isn't a real alternative, more a suggestion to reduce tedium.

**Comment by SirPendrak** [comment]
Maybe you should be able to heat frozen food directlu fro "E"at menu. 
It would solve only part of the problem, but it would be biggest part. 
If you want to heat something for better morale while its edible frozen or it is just room temperature, you still have to press 100 buttons.

**Comment by ThinkInvis** [comment]
Maybe add a prompt to heat up relevant items while "E"ating, if a heat source is available? This could be shown if a food item if frozen, and _also_ if it doesn't match its preferred eating temperature.

**Comment by KorGgenT** [comment]
if you wield the item you're using you can just press ```A```

**Comment by GroeneAppel** [comment]
This is probably a good idea and a feature that should really make it into 0.D
Going the road @ThinkInvis suggests is probably a great idea. However no prompt should be given. Instead a hotkey should be added to _disable/enable_ heating up food items if they are below preferred eating temperature or frozen.

That way eating food will become much more convenient to do, as the player uses a minimal amount of button presses to get an optimal situation. A player in a less than safe situation can skip heating up their food, while those relaxing in their base won't want to press Y on a prompt over and over to eat food.
