### ISSUE TITLE
Pale Skin and Web Walker have redundant/asymmetric connections

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [CleverRaven/Cataclysm-DDA#27948]
**The assumption**
If Mutation A leads to Mutation B, then Mutation B has Mutation A as a possible prerequisite eventually.

**Describe the bug**
Web Walker leads to Web Weaver, however Web Weaver doesn't require Web Walker, it requires Web Spinner.
So to evolve Web Weaver you must evolve Web Walker which is a prerequisite for Web Spinner which then changes into Web Weaver. Once it's done, Web Walker can be removed. The assumption is broken.
Additionally, if you lose Web Walker, then spinning webs will make you stuck.

Pale Skin leads to Light Sensitive, but Light Sensitive has no prerequisites at all. "Leads-to" link has no effect as a result???
Interestingly enough Pale Skin changes into Albino, yet leads to Light Sensitivity, however Albino does not lead to anything, which makes it possible to be both albino and light sensitive.

**Expected behavior**  
Web Weaver should have Web Walker as an additional prerequisite or Web Walker shouldn't be purifiable.
Pale Skin shouldn't lead to Light Sensitive if Light Sensitive develops on its own.

**Screenshots**  
![Web Walker](https://vgy.me/OulhQH.png)
![Pale Skin](https://vgy.me/gqSwHH.png)

**Comment by Asmageddon** [comment]
A legend for the graph would be useful.

**Comment by DeltaEpsilon7787** [comment]
> 
> 
> A legend for the graph would be useful.

The whole thing is here, including the legend
https://github.com/DeltaEpsilon7787/CataDDA-Mutations/
