### ISSUE TITLE
Constant errors in world generations and occasionaly ingame

### ISSUE THREAD

**Issue by xewan** [CleverRaven/Cataclysm-DDA#27941]
DEBUG    : Tried to access invalid map position at grid (2,1,-1)
 
 FUNCTION : size_t map::get_nonant(const tripoint&) const
 FILE     : src/map.cpp
 LINE     : 7730

I get this errory almost everytime I generate "Missed" profession character.
Sometime it shows up ingame. Can't be reproduced.
I am playing Windows, tileset version 0.C-37065-g1aeee0e (tiles)
but error showed up for last four experimental version before that including text version.

**Comment by ZhilkinSerg** [comment]
Are you using any mods?

**Comment by kevingranade** [comment]
You're one commit away from the fixed version, any more recent version than the one you're using should not have that bug.

**Comment by xewan** [comment]
Thanks for information. I've got newest version. When you asked question
about mods - no i havent used mods ;)


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
