### ISSUE TITLE
Pry-on-examine uses temporary "dummy" items, unsuitable for adding lockpicking

### ISSUE THREAD

**Issue by ThinkInvis** [CleverRaven/Cataclysm-DDA#27949]
**Is your feature request related to a problem? Please describe.**  
Pry-on-examine currently draws options from `player.crafting_inventory().items_with()`, which returns `const` items. I'm not terribly familiar with C++, but AFAIK this means those items can't be passed to anything that would modify the item in any way... such as lockpicks being damaged/consuming power (in the case of bionics?) during use. The existing method of going from `crafting_inventory().items_with()` to `iuse.crowbar()` (the latter of which requires a non-`const` item reference) is to create a new temporary item of the same ID as the chosen tool, which is discarded completely once the examine action ends.

**Describe the solution you'd like**  
There should be a way to get _modifiable_ item references from around the player, and not just from their own inventory.

**Describe alternatives you've considered**  
So far, the only way I've found to change this is to use `player.items_with()` (which is non-`const`) instead of `player.crafting_inventory().items_with()`, meaning nearby items won't be considered. This is likely a viable way to implement lockpick-on-examine, but it means other functionality (using nearby tools instead of just those in inventory) will be lost.
Alternate solution: transfer the nearby items to the player's inventory temporarily? Seems like this would just cause more problems, but it's a possibility.

**Additional context**  
Full code involved: iexamine.cpp, line 1165-1212. Note the use of `item temporary_item`.
```
void iexamine::locked_object( player &p, const tripoint &examp )
{
    const bool has_prying_tool = p.crafting_inventory().has_quality( quality_id( "PRY" ), 2 );
    if( !has_prying_tool ) {
        add_msg( m_info, _( "If only you had something to pry with..." ) );
        return;
    }

    auto prying_items = p.crafting_inventory().items_with( []( const item & it ) -> bool {
        return it.has_quality( quality_id( "PRY" ), 2 );
    } );

    iuse dummy;
    if( prying_items.size() == 1 ) {
        item temporary_item( prying_items[0]->type );
        // They only had one item anyway, so just use it.
        dummy.crowbar( &p, &temporary_item, false, examp );
        return;
    }

    // Sort by their quality level.
    std::sort( prying_items.begin(), prying_items.end(), []( const item * a, const item * b ) -> int {
        return a->get_quality( quality_id( "PRY" ) ) > b->get_quality( quality_id( "PRY" ) );
    } );

    // Then display the items
    uilist selection_menu;
    selection_menu.text = string_format(_("The %s is locked..."), g->m.tername(examp));

    int i = 0;
    selection_menu.addentry( i++, true, MENU_AUTOASSIGN, _( "Leave it alone" ) );
    for( auto iter : prying_items ) {
        selection_menu.addentry( i++, true, MENU_AUTOASSIGN, string_format( _( "Use the %s" ),
                                 iter->tname() ) );
    }

    selection_menu.selected = 1;
    selection_menu.query();
    auto index = selection_menu.ret;

    if( index == 0 || index == UILIST_CANCEL ) {
        none( p, examp );
        return;
    }

    item temporary_item( prying_items[index - 1]->type );
    dummy.crowbar( &p, &temporary_item, false, examp );
}
```

**Comment by ZhilkinSerg** [comment]
What exactly the issue is? If you need some code which is missing now - just add it.

**Comment by MetroidHunter** [comment]
Are you suggesting then that the pry on examine should prompt for whether u want to use a tool with pry or a lockpick given that the examined thing is pryable and lockpickable? So that it would be something more of an open with tool on examine where we cross reference tools that can open this thing and present those tools for use? Im trying to ascertain what the feature request is because just making the references non const doesnt gain us much since to my knowledge prying items can not currently be damaged by prying.

My only concern with the approach i mention here, if thats the end goal, is that it increases the clicks to open locked doors. I have though run into times when id like to lockpick a door but instead pry it because i wasnt aware it was locked amd examining immediately pried it.

What are your thoughts?

**Comment by ThinkInvis** [comment]
My current plan is to add lockpicks to the current list of tools in the prompt for opening locked objects (not crates), and to make the list order as follows: do nothing, best lockpick (initially selected option), best prying tool, all other lockpicks, all other prying tools.

This issue is not _directly_ related to the pry-on-examine menu; instead, it's an underlying problem that likely applies to other examine operations. Adding lockpicks to said menu is just the first subsequent issue I intend to solve. A solution to this issue may have uses elsewhere -- basically anywhere it would be better to use a direct item reference, instead of a copy, from nearby; also, anywhere only the player's inventory is scanned when nearby items could be used too. Such behavior may have been previously left out in favor of avoiding this issue.

The recent increase in keypresses required to open crates/locks already has its own issue: #27880. It's possible that the solution to that will be to revert the tool list and go back to using the best available tool; however, as mentioned above, a way to collect non-`const` item references from around the player (which is what the current issue proposes) may still be useful in general.

**Comment by ZhilkinSerg** [comment]
So why do you need an issue about code? If there is anything in the code that prevents you from implementing anything - feel free to refactor the code.

**Comment by ThinkInvis** [comment]
I've already been digging through things trying to figure out what `crafting_inventory()` does and how items get collected. Again, I don't feel like I'm anywhere near familiar enough with C++, nor with C:DDA's code specifically, to figure out a solution to this issue. I could probably piece something together over a week or two, but I'd be very worried about efficiency and hidden bugs; this is a request for help from someone more familiar with the inventory code.
