### ISSUE TITLE
Let's talk about cash, baby.

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#27955]
**Lore Discussion**

The Free Merchants are a group that springs up out of the refugee center quite early on in the Cataclysm. US currency has lost all value, but they have a significant need for trade chits... even internally there's an immediate value to, for example, being able to give out a token for labour that can be traded for food, smokes, time on an arcade machine, whatever things might be limited and in demand - which is almost anything. This rapidly evolves into something that become of value for people trading regularly with the Free Merchants. From the player perspective, for example, many of the refugees will happily accept these tokens in exchange for goods and services.

**The Issue**

I'm about two PR's from allowing the player to pay for goods and services from refugee center citizens, and their preferred trade good is Free Merchant money. So, it behooves us to decide what exactly the free merchants use.

Certain items are certainly used as "universal trade goods". The Merchants don't expect everyone to be willing to accept their money, although if you're willing they'll happily accept it. I'd like to suggest the following things as items the Free Merchants will readily give to travelers in exchange for things like food and scrap metal and other stuff the Merchants need:
- Batteries, charged from the Merchants' central generator, are pretty readily available.
- .22 calibre ammo is extremely plentiful and the Merchants don't use it that much, so they're happy to give it away.
- I'm open to further suggestions, but remember it can't be something the Merchants have a lot of ongoing need for; rather, something they can either produce more than they use (batteries) or something they get lots of from salvage and don't need much (small calibre bullets)

These items work for pseudo-currency trading with adventurers, but the actual Merchant money should be something else.
Here are some ideas:
- Old paper money stamped with a hard-to-forge seal and signed by the Merchants' head treasurer. This is my current favourite. The lore idea behind it would be that they are "confirming" the currency, recognizing that it stands for an actual supply of goods.
- Hand-signed paper notes
- Old metal coins flattened by one of those coin-rolling machines you find at amusement parks and gift stores, marked with the merchants' seal (update: as discussed below, this works quite well for a different faction, the Campus)

Any other ideas?

**Terminology**
If we go with the stamped-note, what would some common terms for it be? I see the following being common.
- Dollars/bucks/any other term previously used for money
- Free Merchant Confirmed Notes (official name), or C-notes for short
- Stamp-bucks, stamp-notes, food stamps (ha ha), and simply "stamps"
- ooh, they might also be called "merch". "Yeah, we accept merch here. Thirty merch for the canner."

**Comment by Admiral-Wily** [comment]
I would imagine that they would go with the old paper money thing as paper money is familiar and could offer some sense of normalcy that has been lost.

**Comment by mlangsdorf** [comment]
The Free Merchants almost certainly have economists on staff, since they're "6 busloads of office workers and soccer moms."  So they're really aware of the difficulties you get when someone can bring in currency without actually bringing in wealth.  So they're going to control the supply of currency, so someone can't bring in a security van's worth of banknotes and buy everything out of the Free Merchants' stock.  We're already seeing that problem with cash cards, and that's something we're going to fix.  The Free Merchants are going to control their currency, and if you want to buy a nice rifle scope from them, you'd best sell them something equally valuable.

On the other hand, they don't want the money supply to be too tight, either.  So they're willing to buy money bundles, but a stack of pre-Cataclysm bank notes aren't FM Confirmed Notes and you can't give them a large stack of $20s and get a rifle scope though you can probably get a couple of days of meat jerky.

**Comment by I-am-Erk** [comment]
I'm sure the pedants among the Free Merchants are willing to just call them "Confirmed Notes" or perhaps "C-notes".

I think a second reason the Merchants would be willing to buy out all old paper currency, besides making sure they have a stock of money for making more confirmed notes later, is that the rarer they make paper money in the area, the harder it gets for anyone to forge their currency. If they can buy out tons of paper money early on, they'll make it tough to find for forgery later.

**Comment by mlangsdorf** [comment]
So the economist will let you slide with C-Notes, but there's a Marketing guy among the office workers and he's insistent that you not dilute the brand name.

**Comment by I-am-Erk** [comment]
That seems reasonable yes.

**Comment by I-am-Erk** [comment]
Batteries: just because the players don't have a recipe to recharge batteries yet doesn't mean it's not possible. In my opinion the whole battery thing needs a bit of an overhaul.

Survivor Z dropping Merch: not yet I think. Maybe later when we can determine if they're actually close to the free merchants and enough time has passed, but this isn't the accepted currency of the apocalypse unless you help the free merchants rise to a position of local dominance first.

**Comment by Epictyphlosion** [comment]
I think either people would stick with the US Dollar, and/or just go back to trading items and not money. It's very unlikely that people would adopt a new currency, even after the cataclysm, because even though the US mint and government is dead for the most part, that doesn't mean people have to stop using the dollar. It'd also be much easier to just stick with the dollar, because adopting a new currency and making that currency known and recognized would be difficult, and even if people did adopt new currencies, they would vary from place to place. If that as the case, the people in Boston would pay in bottle caps, while the people in Providence would be paying in casino chips, and the people in Hartford would pay in arcade tokens.

**Comment by I-am-Erk** [comment]
> Lore wise, I think the Merchants should be looking to create a new credit based fiat currency. That is to say that their currency should represent a debt that they owe to the holder and should be backed by nothing more than their good word. This means they can always have more cash if they need it because they can just make more (and go further into debt) and that they're always coming out ahead with regards to ensuring they get goods/services in exchange for their currency because the only way that their currency is given out is in return for goods/services. Likewise upon their currency being redeemed it would just be removed from circulation.

What you're describing are promissory notes, and the FM Confirmed Note is somewhere between a promissory note and a real currency. It has its origins in paying refugees in the center, for use as a food/water chit, but the creators (many of whom likely have economics degrees given the population of the center) were aware that it would almost immediately be used as a currency for other things and designed it with that in mind.

> They should also be looking to make their notes easily destroyed. Every destroyed note is a debt they don't have to pay. 

This is a good point, but there's a tight balance to it. They also want people to start adopting their currency. If a Merch note is known to be impossible to store and hard to get honoured, nobody is going to accept them, they'll just barter first. The notes have to be something survivors will trust as a reasonable currency that they can hold onto and bring back to be exchanged. That's why for a long time only people working very closely with or living in the refugee center are likely to accept them.

> The only reason for them to have a commodity currency is if they can't convince people to take their fiat currency. That said, people should be unwilling to take their fiat currency especially at first. Who knows if the Merchants will be here to pay their debts tomorrow?

Precisely, and the merchants are well aware that their currency will not be widely accepted for some time. This is why they have specified commodities that they have a surplus of to be able to trade to survivors that would either have use for them or would recognize them as useful trade goods that other survivors would accept. My favourite example of this is a .22 cal bullet - it's not something so useful they can't part with it, but it's not useless either. Everyone is aware they'll be able to give someone else a box of small calibre bullets and get something in return. These are still good for killing zombies and game after all.

> As for de facto commodities used as currency food seems the obvious answer, especially long lasting food. It's something everyone needs and it's fairly divisible. 

Actually, food is a tough one. Non perishable food is in too high of demand for them to be willing to trade it. The status quo at the beginning of the game is that the merchants aren't likely to sell you food for practically anything: if there's one thing they're desperately low on, it's sandwiches. Among other survivors, who may be able to make and raid more than they need, that's another matter.

**Comment by I-am-Erk** [comment]
> I think either people would stick with the US Dollar, and/or just go back to trading items and not money. It's very unlikely that people would adopt a new currency, even after the cataclysm, because even though the US mint and government is dead for the most part, that doesn't mean people have to stop using the dollar. It'd also be much easier to just stick with the dollar, because adopting a new currency and making that currency known and recognized would be difficult, and even if people did adopt new currencies, they would vary from place to place. If that as the case, the people in Boston would pay in bottle caps, while the people in Providence would be paying in casino chips, and the people in Hartford would pay in arcade tokens.

Given how easy it is for someone to wind up with 100,000 dollars or more just by breaking open an ATM or wandering into a busted armoured car, it's very unlikely the old-world cash has any meaningful value. With something like 1 in 10,000 people surviving, you'd need about 10,000 dollars to make up the equivalent of one old-world dollar. The giant wads of cash would be strictly impractical.

**Comment by I-am-Erk** [comment]
At this point I think I've got the feedback I need but people can still comment as desired
