### ISSUE TITLE
'Chesthole Indicators' mod does not replace all indicators

### ISSUE THREAD

**Issue by Myobu1** [CleverRaven/Cataclysm-DDA#27964]
**Describe the bug**  
The 'Chesthole Indicators' mod does not replace all of the indicators with the one's used in the Chesthole tileset. 

When using the MSX++DeadPeopleEdition tileset with the 'Chesthole Indicators' mod enabled and pressing 'Shift+V' to see items in the surrounding area, the box that appears is the one present in the MSX++DeadPeopleEdition tileset. However, when pressing 'X' to look around the box that appears is the one present in the Chesthole tileset.

**To Reproduce**  
1. Switch to the MSX++DeadPeopleEdition tileset (for some reason called MSX++Live_People).
2. Create a new world using the 'Chesthole Indicators' mod.
3. Press 'Shift+V' to see items in the surrounding area.
4. The 'box' that appears around the selected item will be the default for the MSX++DeadPeopleEdition tileset rather than the one present in the Chesthole tileset.

**Expected behavior**  
When using the 'Chesthole Indicators' mod, all indicators should be changed to the one's present in the Chesthole tileset. The box that appears when pressing 'Shift+V' to see items in the surrounding area should be the one present in the Chesthole tileset rather than the MSX++DeadPeopleEdition tileset.

**Screenshots**  
Making sure that the 'Chesthole Indicators' mod is present and active.
![screenshot 3](https://user-images.githubusercontent.com/44004977/51944431-0c77ad80-23ea-11e9-9c6f-b56bff4f9822.png)
![screenshot 6](https://user-images.githubusercontent.com/44004977/51944441-113c6180-23ea-11e9-8bf5-a01a69066cac.png)
Pressing 'Shift+V' to view items in the surrounding area, resulting box is the MSX++DeadPeople default.
![screenshot 4](https://user-images.githubusercontent.com/44004977/51944439-113c6180-23ea-11e9-82e6-baa0db8a5311.png)
Pressing 'X' to freely look around, the resulting box is the Chesthole version
![screenshot 5](https://user-images.githubusercontent.com/44004977/51944440-113c6180-23ea-11e9-8828-8f79b051e61e.png)
When switching to the Chesthole tileset, all indicators are the Chesthole defaults, as to be expected.
![screenshot 7](https://user-images.githubusercontent.com/44004977/51944442-113c6180-23ea-11e9-8b99-88237b37b26d.png)
![screenshot 8](https://user-images.githubusercontent.com/44004977/51944443-113c6180-23ea-11e9-8266-4caa12ff0f9b.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 Pro
 - Game Version: 0.C-37176-g88c8f68
 - Graphics version: Tiles
 - Mods loaded: 
1. Disable NPC Needs
2. Filthy Clothing
3. Simplified Nutrition
4. Icecoon's Arsenal
5. Medieval and Historic Content
6. More Survival Tools
7. DR_RP Chesthole Indicators
8. No Flaming Weapons
9. No Survivor Armor
10. Classes and Scenarios Mod

**Additional context**  
Before the 'indicators' became a mod and you had to install them manually, the 'Chesthole Indicators' used to change all of the indicators in the MSX++DeadPeopleEdition tileset to the ones from the Chesthole tileset. Including the box that appears when you press 'Shift+V' rather than keeping it the MSX++DeadPeopleEdition version of the box. Now that it's a mod, the box that appears pressing 'Shift+V' remains unchanged no matter which "indicator mod" you choose upon world creation.

Is this intentional now? I don't like having a big red dot right in the middle of items and such taking up all of that sprite real estate. I was hoping the 'Chesthole Indicators' would change that.

First time submitting an issue so please don't crucify me. I couldn't find where to add labels either, so that's why this report doesn't have any.

**Comment by Night-Pryanik** [comment]
`Chesthole Indicators` mod is not an official one and thus is not supported.

**Comment by Myobu1** [comment]
> `Chesthole Indicators` mod is not an official one and thus is not supported.

Funny, the mod shows up in the 'installed' list by default upon first installing the game. I also tried using using the 'Chesthole Indicators' mod from the 'MSX++DeadPeopleEdition' github repo and that didn't work  either. So I fail to see how it isn't the 'official one' as it were.

**Comment by Night-Pryanik** [comment]
Oh, sorry, I was mistaken.

**Comment by Myobu1** [comment]
> Oh, sorry, I was mistaken.

It's fine. I just haven't had my coffee yet so I'm a bit grumbly. :C

**Comment by SomeDeadGuy** [comment]
Sorry it took so long. On my github fix for that error will be added later today.
