### ISSUE TITLE
Pillow forts can be constructed under vehicles

### ISSUE THREAD

**Issue by ThinkInvis** [CleverRaven/Cataclysm-DDA#27977]
**Describe the bug**  
The Build Pillow Fort construction can be performed under any vehicle-containing tile. This is unexpected, as any vehicle part that tries to move onto a pillow fort will collide with it. This bug may apply to other constructions, but this is the only one I could find.

**To Reproduce**  
1. Get any vehicle over a wooden floor tile (natural or placed with debug/construction).
2. Give self the ingredients for a pillow fort (19 pillows, 3 blankets), OR add Debug Hammerspace mutation to self.
3. Move adjacent to the part of the vehicle that's over a floor tile, in a spot where you're allowed to construct.
4. Perform Build Pillow Fort construction, with any of the vehicle's floor-overlapping tiles as the destination.
5. Pillow fort construction will succeed.
    
    Steps to confirm that this behavior is undesired:
6. Ensure that the vehicle can be moved, whether manually or under its own power.
7. Grab or take control of the vehicle, whichever will allow it to be moved.
8. Attempt to move the vehicle off of the pillow fort. If this succeeds, attempt to move it back on.
9. At some point during step 8, a collision will occur instead ("The [vehicle] collides with the pillow fort.").

**Expected behavior**  
Because pillow forts collide with vehicles, it should not be possible to construct a pillow fort under a vehicle. Either the "You cannot build there!" error should appear after step 4 above, preventing progress to step 5 and beyond; or pillow forts should not collide with vehicles, preventing step 9.

**Versions and configuration**
 - OS: Windows 10
 - Game Version: 0.C-37192-gf53995c
 - Graphics version: Tiles
 - Mods loaded: default (dda, no_npc_food, filthy_morale, novitamins)

**Comment by kevingranade** [comment]
Fixed by #27992
