### ISSUE TITLE
Boats allow you to walk on water

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#27974]
**Describe the bug**  
Grabbing a boat and pushing it onto water allows you to walk on water.

**To Reproduce**  
Craft a little boat, push it onto the water, turn away from it whilst still grabbing it, you can now walk freely across the river indefinitely as long as you don't "release" the boat.

**Expected behavior**  
Maybe, holding onto a boat while in the water is a good feature, but walking on top of the waters surface is not.
The character should either release the boat, or start swimming whilst grabbed.

**Screenshots**  
![image](https://user-images.githubusercontent.com/39344466/51991595-540e4000-24a3-11e9-9b73-c2259de73c5b.png)

**Versions and configuration(please complete the following information):**
 - OS: Lubuntu 18.04]
 - Game Version latest master
 - Graphics version Tiles 
 - Mods loaded dda, boats

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by davidpwbrown** [comment]
I now can't reproduce turning away from the boat and walking away from it on the surface of the water, but it happened.
What happens every time is being able to push the boat, grabbing it, whilst walking on water.

**Comment by CoroNaut** [comment]
Still, should probably limit the player to walking only in shallow water when grabbing a boat-like vehicle

**Comment by wapcaplet** [comment]
Confirmed, still reproducible in 0.E-9681-g2cca4d658c. The same behavior occurs when pushing a bicycle into deep water, like in #19226

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10563. 
Grabbed a kayak, pushed it into water. As long as I pushed it in front of me, everything was ok. The moment I moved away from it (without letting it go), I immediately started to sink.
