### ISSUE TITLE
Charcoal smoker fits more charcoal than its volume

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#27988]
**Describe the bug**  
The charcoal smoker is 4.5L and fits 200 charcoal inside that is 5L.
Also, converting wood into charcoal increases its volume it seems, so maybe charcoal unit volume should be lowered?

0.C-37176-g88c8f68af8-dirty

**Comment by jeremyshannon** [comment]
I checked it out, and 10L of wood produces 5L of charcoal in game, which is about right, Where it was off is that it was like 97% of the weight of the input wood, when it should be about 25% according to wikipedia. The smoker being a Tardis is clearly off.

**Comment by kevingranade** [comment]
Fixed by #28004
