### ISSUE TITLE
completing a mission for the refugee farm doesn't "complete" it

### ISSUE THREAD

**Issue by nulman** [CleverRaven/Cataclysm-DDA#27983]
[Hilton Head Island.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2814364/Hilton.Head.Island.zip)

**Describe the bug**  
completing a mission for the refugee ranch does not remove items or remove the mission form the log.
this appears to be a new behavior as i was completing missions successfully 3 days ago

**To Reproduce**  
provided save is right in front of mission giver with required items
talk to him and complete the mission.
you can also go to the scavenger boss in the building to the north and give him 12 knife spears for the same effect

**Expected behavior**  
the items and the mission should be removed

![image](https://user-images.githubusercontent.com/7602897/52011575-06182d00-24e1-11e9-81e7-9e9c83aef9e6.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-37192-gf53995c]
 - Graphics version Tiles
 - Mods loaded [
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "Mining_Mod",
  "mutant_npcs",
  "national_guard_camp",
  "deoxymod",
  "blazemod",
  "Tanks",
  "No_Fungi",
  "more_classes_scenarios",
  "StatsThroughSkills"
]

**Comment by Mcrone617** [comment]
I can also confirm this happens with NPC missions, just tested a mission via debug, giving the antibiotics  gave the reward dialog, but the mission remained in the log, and relations didn't improve.
