### ISSUE TITLE
change description of acid ant

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#27993]
Right now acid ant workers gave collor red in their description, just how normal worker ant. I propose change to brown, instead of red, so it would be in line with the rest acid ants.
Acid Soldier and Acid Queen all have collor brown in their description.

**Comment by Fris0uman** [comment]
Done, but making the PR yourself would have been slightly faster since it just required to change `red` for `brown` in the json file ^^.

**Comment by SomeDeadGuy** [comment]
If i knew how to do it, i would also update my tileset in main repo every day. :D
Sadly i am clueless on this.
Thank you btw. :3

**Comment by Fris0uman** [comment]
Then I recommend [Guide to adding new content to CDDA for first time modders](https://discourse.cataclysmdda.org/t/guide-to-adding-new-content-to-cdda-for-first-time-modders/17781) for info on the code and things available in json.
and [Contributing](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CONTRIBUTING.md) for how to use git, and git hub.
and [Using Git and Github to contribute](https://discourse.cataclysmdda.org/t/using-git-and-github-to-contribute/1030) for more about git and github, it's from the old forum and some stuff are a bit broken but it's good.

**Comment by kevingranade** [comment]
Fixed by #27998
