### ISSUE TITLE
Aren't map specials grossly unbalanced?

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#28002]
**Is your feature request related to a problem? Please describe.**  
Military helicopter crashsites and dead science/military teams are plentyful, easy to find, don't pose any threat to most early game characters and provide ludicrous amounts of top-end loot. As long as you have a gun, you can kite and kill soldiers and bio-operators without taking any risks. If you don't have a gun you can simply grab one from the dead soldiers. With helicopters you can also easily lure zombies into wreckage killing them without any weapons at all. You can also easily lure zombies/mi-go away or let them fight each other. You can run them over with any semi-working car you found. The point is, almost any character can clear these map specials on day 1 and get the loot. Even worse, none of the enemies found there evolve, making them even more obsolete later.

Even bigger problem is the loot. Most soldiers drop some guns or some ammo, essentially making these sites provide more ammo that's required to clear them. More often than not you get belts with 100 or 500 (hello?) rounds. Science teams usually have 1 rare item with them, on top of the usual books, IDs and CBMs. Bio-operators, in particular, have an INSANE drop list, including power armors. Both scientists and bio-ops can be further gutted for high-end CBMs. One would think the best way to get power armor or RM13 is to raid some super high security military installation, but as it is now, the best way is to run across the fields until you find enough bio-operators to drop both helmets and suits. This is just not reasonable.

**Describe the solution you'd like**  
Loot found in these map specials should be toned down A LOT. They should also probably be made more dangerous. The ones that have grenadiers are adequate for what they give, maybe all of them should have some similar-level threats.

**Describe alternatives you've considered**  
Just make them a lot more rare.

**Comment by AskaHope** [comment]
Please use the forum for discussions.

https://discourse.cataclysmdda.org

**Comment by Night-Pryanik** [comment]
That's a rather serious balance issue, and its resolution should be tracked here.

**Comment by GearheadLydia** [comment]
Honestly, one of the biggest unbalanced ones at the moment is the random cluster of dropped crates.

**Comment by Hirmuolio** [comment]
These are map extras instead of map specials (at least that is how they seem to be called).

Map specials are defined in json and are easy to mod (special_locations.json). Map extras are hardcoded in c++. In json you can only change how often and where they spawn (regional_map_settings.json).

**Comment by logros13** [comment]
I don't see how this is any worse than gun stores from a balance viewpoint, they to are easy to get into and have far more guns/ammo than any helicopter crash site i have seen.

**Comment by mark7** [comment]
> Honestly, one of the biggest unbalanced ones at the moment is the random cluster of dropped crates.

What's wrong with having a "good" find?  I can understand something really "good" being rare, but why does it need to have an equal mix of "good" and "bad"?

> I feel like that could probably somehow be intermingled with a dropped mine

Let's say this happens.  Then either a player knows about the mines, in which case I assume that it's just one more bit of annoyance, or a new player doesn't, in which case they have a random instadeath to learn about the fact that crates can randomly kill you.  That doesn't seem great from a game experience standpoint.

**Comment by Amoebka** [comment]
Gun shops are less of a problem mostly because 1) they are located deep in the cities, which is usually the deadliest location once the zombies evolve 2) the have mostly low-level guns and low caliber ammo.

Crates are kinda an issue (the high rolls can get pretty stupid, one person on reddit recently mentioned getting 1000 rifle rounds from one crate), but less so, because usually they contain weaker items.

Another notable offender is military cars. They can have 100-200 rifle rounds in them, for free with no risk involved. The game in general has WAY too many 5.56 and 7.62 ammo spawning in easily accessible locations.

From a design perspective, I greatly appreciate the game giving you a chance to luck into some amazing item early, but it sould be balanced with more care, imo. Finding an M4A1 with 30 rounds in it is perfectly fine, finding 500 rounds for it on a random dead soldier or in a random crate ruins the difficulty curve.

**Comment by nexusmrsep** [comment]
Not going into loot, but the sheer abundance of crashed helicopters is a bit off. Just how many helis did the military have?

**Comment by thethunderhawk** [comment]
> how many helis did the military have?

Well, between 2 army bases, 2 Air Force bases, 2 coast guard bases, the Atlantic fleet referred to by the Old Guard rep, and the potential for any number of marine units to be redeployed in the region during the cataclysm, I’d say there could be hundreds.

**Comment by SaltatorMortis** [comment]
maybe the most logical approach would be to "grade" loor possibility and spawn on the  location  the loot / enemys accordingly.

- cleaned out
  - only the "set peces" are left

- hot extraction
  - a few unopened crates
  - low leveled / scattered  Z 

- overrun
  - reanimated Military Z and other strong enemys
  - good gear

for supply-drops 2 additional cases
- planned/unreached drops (rare)
  - basicly drops like now

- civilian airdrop

**Comment by kevingranade** [comment]
As per the initial comment, this issue is too amorphous to take action on in it's current state, so as expected it turned into a rambling conversation about possible solutions, which just clutters the issue tracker.
