### ISSUE TITLE
Lighting a fire instantly turns charcoal/tinder/?other charge based items? into ash without adding to fire fuel.

### ISSUE THREAD

**Issue by ussdefiant60** [CleverRaven/Cataclysm-DDA#28003]
**Describe the bug**  
I've been trying to do innawoods style games out of cabins/hermit shacks for the past little while, and i've noticed that chopping up tinder for burning for cooking etc. provided very little burn time. I decided to do a bit of experimenting, bought in 3 logs worth of charcoal from outside, lit it on fire, and it lasted the same amount of time as 100 charges of tinder, which seems to be the same amount of time you get for lighting any fire at all. I also noticed that the entire 30 liters of charcoal turned into wood ash in one turn, which is rather the opposite behaviour than i'd expect from burning an equivalent volume of other wooden items.

**To Reproduce**  
1. Find a stove/oven/hole in the ground
2. Toss tinder/charcoal in amounts of your choosing inside.
3. Light it on fire, observe lack of burning time

**Expected behavior**  
I'm not certain on the burnability of charcoal, per se, but i'd sorta expect, say, 500 tinder from the MST mod to fuel a fire for approximately the same amount of time as a 2-by-4, which is equal in volume. I'd certainly also expect 30 liters of charcoal to not all burn up instanteously, however much it actually adds to the fire.

**Versions and configuration(please complete the following information):**
 - OS: Win 10 Home
 - Game Version [from the main menu, e.g. 0.C-37210-ge6e1890]
 - Graphics version [Tiles]
 - Mods loaded [
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "craftgp",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "Mining_Mod",
  "mutant_npcs",
  "more_locations",
  "FujiStruct",
  "deoxymod",
  "blazemod",
  "Tanks",
  "boats",
  "Arcana",
  "necromancy",
  "safeautodoc",
  "manualbionicinstall",
  "more_classes_scenarios",
  "StatsThroughSkills",
  "PK_REBALANCE"
]

**Comment by jeremyshannon** [comment]
Tinder should go up faster (and hotter) than an equivalent-mass of log or two-by-four, simply because it's got more surface area and air available. But the current result really is way too fast. "Poof!" and it's all vanished.
