### ISSUE TITLE
npctalk requests

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#28008]
I've been testing out the newly jsonized NPC stuff and I've run into a few issues.  A few options I would like to see:

1> Setting the data for static NPCs in npc.json requires giving them a faction.  But it should have an option for generating a factionless NPC.  Factions like 'Wasteland Scavengers' are really unnecessary, since they should just be unaffiliated beggars or scavengers. 

2> Because class determines starting dialog topic, there needs to be a dialog effect to switch an NPC's class. Not reroll their stats, just change the id/name.  I made 'captive' npcs , but they should be converted to something else after they're freed.  It doesn't make sense for them to keep asking to be saved after the intro scenario is over. 

3> You can add effects or traits, but you can't remove them.  Since effects are used for talk flags, it would nice to have both. For example, if an NPC gets mad, there is usually a timed effect like asked_about_x.  But I wanted a way for the NPC to stay mad until you pass a trial or do something to remove the flag.  Currently, you could make counter effects and apply them, but that's pretty messy. 

I don't know if anyone is adding stuff to npctalk right now or just migrating it to json, but those would be pretty useful options for making dialog trees.

**Comment by mlangsdorf** [comment]
I'm doing npctalk support.  Sorry I missed these; I'll try to add them soon.
