### ISSUE TITLE
Suggestion: move "default" game start to later

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#28000]
**Is your feature request related to a problem? Please describe.**  
As we continue to make the game more realistic, early spring start is becoming more and more difficult. This is as it should be, because surviving early spring with nothing is really hard. Gathering plants has been reduced to realistic levels now, but this makes a lot of default survival tactics hard. It is constantly raining and freezing, making it hard to get food or drink water or stay warm. It's a really hard time to survive: traditionally even if you had a filled larder in your 18th century home, the last time before things really warmed up would be the toughest.

Nearly any change to make survival more realistic and complex is going to make starting the game harder, and at some point it's going to become pretty much totally inaccessible to new players.

**Describe the solution you'd like**  
Make "early spring start" a challenge rather than the default.

Start the game at least one month into spring, when the freeze is over and players can plant. Maybe just move it right into the first day of summer, which will mostly just return the difficulty to what it was before freezing and gathering mechanics were made more realistic.

My own preference is to move the start of the cataclysm to 5days before the beginning of summer, and make the game start in early summer. This restores early game hunter gathering viability, reduces the impact of wetness and cold for brand new characters, and allows new survivability changes because it's not all that hard to get by in summertime.

Another very good option would be to go right to late summer or early autumn. While this would still give the same survivability, there would be a new added challenge - that in a fairly short time, winter will come. This means that in the first year, the challenge would change from "here you are, unarmed and unequipped in freezing wet weather with no food" to "you have only a short while to get ready to survive your first winter without amenities. GO!"

*Ideally* I would like the "start of the cataclysm" to be 5 days before whatever the 'default start season' was set to in World Settings, and for that default to start as summer. Then you can set it to whatever you prefer and not have monster evolution and NPC conversations and things advance with it.

**Describe alternatives you've considered**  
Another, simpler option would be to have the game start a month or two after the date of the cataclysm by default. This would have some repercussions though; we'd probably need a new default survival scenario for example, and the player would need an excuse for still just having the clothes on their back.

**Additional context**  
Keep in mind spring start should still totally be an option, just not the *default*. Ideally I'd like to be able to move around the cataclysm start date depending on what your default season start is set to.

**Comment by curstwist** [comment]
I like the idea of moving it a lot.  I'm leaning towards summer day 1 but really anything from mid spring to mid summer works.

This would reset zombie evolution to also start then, right?  That would make a spring start challenge problematic. All current 'other season' starts are later then the default start and result in higher evolution rates.  So spring, day 1, year 2 for the challenge mode?  That would make it almost as hard a winter starts.

A moderately experienced player now hits mid/late game within the 1st season due to 91 day seasons so a mid-season start may actually be better.

**Comment by RosaEscura** [comment]
I like the sound of the summer start from day 1. Think that'd make more sense than starting in the middle of a season and I like the idea of the game being a bit easier for new players early game but then it getting to the harder part sooner (winter). Also I like the sound of game start always being a few days before whatever season you choose as your starting season as right now starting in winter means you'll only find rotten food and monsters that have gone through some evolution which I wouldn't like to be the case by default.

**Comment by I-am-Erk** [comment]
Zombie evolution would go from whenever we set the game start. Either it would always be from summer day 1 (or whatever the default is) just as it's spring day 1 now, or it would be from day 1 of whatever season you'd picked in world settings if we went with the 'flexible cataclysm day' option. Likewise the food rot timer, although of course if you start in summer then the food is going to rot pretty fast. However if you did a winter start, there'd be tons of frozen food around to be scavenged.

**Comment by RosaEscura** [comment]
Yeah that sounds good to me.

**Comment by Barhandar** [comment]
Scenarios need to be able to override flexible cataclysm, since some of them rely on more time passing since then.

**Comment by I-am-Erk** [comment]
Yeah I think there'd have to be a 'time passed' flag for scenarios.

I'd like that anyway, so that someday when there are dynamic npc factions and stuff we can have the game start years in with fully established npc cities and things...

**Comment by mlangsdorf** [comment]
I'd like to be able to set both in options or a scenario: start of Cataclysm and start of the game.  I think defaulting to a late spring start for both makes sense.

**Comment by nexusmrsep** [comment]
I agree with those ideas.

**Comment by I-am-Erk** [comment]
Just about the only reason I can think of not to start in late spring is that it sounds tough to do, needs calendar reworking.however, if we redid the calendar to allow for variable cataclysm dates I'm sure varying the day of the season would also be easy

**Comment by nexusmrsep** [comment]
Callendar rework could include an actual callendar too. Wouldn't it be nice
to determine the exact date? Or are we "lost in time" never to return to
the old days of day tracking?

pt., 1 lut 2019, 03:13: I-am-Erk <notifications@github.com> napisał(a):

**Comment by paulenka-aleh** [comment]
Would like to add my 5 cents too. I tried starting in all the seasons and even though it was different I can't say any season is really much harder. The main advantage of cold seasons is reduced rot which is basically off in winter and a real pain in summer. In addition in winter swamps are ideal location for innawoods life should you get enough warm clothes. Spring seems to me like a nice tradeoff: rot isn't a big deal and it's not that freezing on the other hand. You also can forage, trap and hunt which would be less effective in winter. The only option that seems unavailable from scratch is farming which in any case wouldn't provide you food until much later where you supposedly should find alternative means of feeding yourself.

**Comment by I-am-Erk** [comment]
As far as I'm concerned, the canon start is probably going to be mid spring, day 30 or 45 or so. I agree that spring has most of the advantages, and if you move it just out of the coldest part it's about perfect
