### ISSUE TITLE
The "Salvageable Robots" mod is really two mods rolled into one, and far crazier than its name suggests.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#28011]
## Summary:

Where the Modular Turrets mod has turrets such as "shotgun defense turret", "riot control turret", "5.56mm military turret", which is along the lines of what I expected from Salvageable Robots, it instead has robots such as: "bee-bot" which produces infinite(if paced) honey for you at the added cost of a microreactor, crossbow, some wood, and 4 2L tanks, or the "arson hack", which at the added cost of 1 pilot light, 2 heating elements, and 25 gasoline, will unleash infinite fire...

And the other bots all have funky names such as "glittering lady", "shortcircuit samurai", "slapdash paladin", "bitter spinster"... you get the idea. There is no "9mm defense bot", or "riot control bot", or anything among those lines.

Furthermore, while it's stated in the description, the mod's name by no mean suggests that it actually adds a lot of those robots to spawn groups. All the way down to cyborg necromancers, and chicken walker variants you'd expect in Mad Max, rather than the New England military.

## What I would like to propose:

To either expand "Modular Turrets" into "Modular Turrets and Robots", or to create a separate "Modular Robots" mod to complement it, with similarly systematically named, and well-balanced **<sup>1</sup>** content, rename "Salvageable Robots" to "Extra Robot Types", and either remove overlapping robots from it, or make the mod rename them, e.g. from "5.56 military bot" to the current "robo-protector".

Since it looks like a fun project, and with majority of the groundwork done, **I'm willing to undertake it myself, given a green light**. 

<sup>**1** Honestly, with the removal of the brokenly overpowered control laptop, the Modular Turrets should in my opinion make its way into vanilla. It's both more involved, and better balanced, although I'd like to reintroduce the ability to scavenge some ammo out of the robots somehow.</sup>

**Comment by kevingranade** [comment]
I'm fine with you splitting it up, improving the description (I wasn't actually aware it had particularly wacky things in it myself...), and/or rebalancing it.  Maininlining content is always an option as well.
The control laptop is another issue, it needs a pretty huge nerf, but I think we want some kind of mechanism like that in the game.

**Comment by SunshineDistillery** [comment]
The names are wacky to emphasize that those are junkyard robots made by the player, not factory models.

The robots are a bit wacky because I was trying to figure out what was possible with new monster options and if they had any utility for non combat utility bots.  I'll admit the dancing party-bot that shoots marijuana smoke is a bit silly, but you don't have to build it. 

Salvaged (player-made) robots shouldn't show up as monsterspawns. That's either somebody else's edit or a bug. 

I don't know how you'd split it up exactly. You just want to move the recipes to a different mod?

**Comment by jeremyshannon** [comment]
Quick thought: Would it be possible to make the crazier robots only available if Crazy Cataclysm was also enabled?

**Comment by Shodan14** [comment]
While the names are "whacky", the robots themselves are very cool and fit the theme of the game well. I don't see why any of them should be changed or moved anywhere, seeing that it is already a mod. Splitting and expanding the descriptions of the mod(s) seems fine.

**Comment by Asmageddon** [comment]
@jeremyshannon I don't think mods can contain individual content packs that are enabled/disabled based on which other mods you load. It could be an interesting feature, though, so feel free to open an issue for discussion to happen. 

@Shodan14 They certainly are cool, but a lot are strongly on the ridiculous side, either theme-wise, or balance-wise. The names are just the first turn-off I noticed.

I'll let discussion go on a little longer before deciding exactly what to do. I'm currently minded to just expand "Modular Turrets" into "Modular Turrets and Robots", rename "Salvageable Robots" into "Extra Salvageable Robots", and split the more wacky stuff into that. And perhaps expand it with some extra cool turrets as well?

What's your take on that, @SunshineDistillery? If you'd like to do some crazy turrets yourself, that'd be pretty golden. And I'd personally prefer all of the mod's content renamed into something more systemic(so it's a) intuitive and b) searchable), but I feel like that should be your decision to make, in a way.

**Comment by Asmageddon** [comment]
@Shodan14 I'm not 100% certain about that. It's not exactly like you can convert existing firearms to interface with whatever integral firearms connect to, and crafting them from scratch is I think beyond what a survivor would be able to do.

Though perhaps being able to convert right caliber firearms with sufficient mechanics and electronics skill would be alright... I dunno.

**Comment by Shodan14** [comment]
@Asmageddon I guess it's up to the mod maker, but if you can strip the firing mechanism out of a M2 Browning and strap it to a 2x4 for a single shot gun, I can imagine doing the same with other guns and making them robot-compatible. I don't mean just creating them from scrap.

**Comment by SunshineDistillery** [comment]
I would not expand turrets beyond being just turrets, since some players probably don't want any of that extra robo-craft stuff. You might want to split it in three: turrets, mod-robots, and salvaged.  Make mod-robots and salvaged dependent on turrets but not on each other so the players can pick what they want.  Then modify turrets however and migrate the shooty robots to mod-robots.

When you're balancing robots, keep in mind that what makes a good enemy-monster and what makes a good sidekick-monster are different.  Players care way more abouta conserving ammo.  Increase damage but lower fire rate.  Also adjust firing modes to different distances so they don't full-auto against targets too far away to hit. That's kinda why I made mostly melee types. 

Also, mod turrets wasn't supposed to blacklist the control laptop. That was a copypaste error.

**Comment by Asmageddon** [comment]
Too bad that the game wasn't built with truly modular content in mind, like being able to swap out individual energy battery/generator components, integral firearms, a control chip, an iff chip, armor plating, engine, etc....

All of that makes me wish so hard I was stable enough to just code a game of my own. But alas, so it is that even whether I can touch code/data/anything on any given day at all is not free for me to decide :-(

**Comment by Asmageddon** [comment]
@SunshineDistillery I started prepwork to work on this, but I'm mostly new to CDDA's JSON files, and I have a rather major degree of anxiety and such, is there anywhere like IRC or Discord that I could get in touch with you through? Both regarding JSON stuff, and your opinions, being as you're the original author of both concerned mods.

**Comment by kevingranade** [comment]
Discussion seems completed, if you want to tackle this, feel free, but it doesn't need an issue.

**Comment by Asmageddon** [comment]
@kevingranade In the end I lost motivation since without being able to configure firing modes, robots and turrets are pretty useless anyway, I don't have enough confidence in my rusty abilities to implement a JSON-ified action system, and I didn't want to halfass it with more hardcoding either.

I'll def remember about this the next time I get around to playing CDDA.
