### ISSUE TITLE
Enabling sound does not enable/disable title screen music

### ISSUE THREAD

**Issue by mark7** [CleverRaven/Cataclysm-DDA#28016]
**Describe the bug**  
In the tiles build with sound enabled, enabling/disabling sound does not halt or start the titlescreen music.  A restart of the game is required.

This is confusing to the user, as it's not clear whether his changes are working or not.

While I'd suggest that it'd be preferable to have immediate effect, there isn't even a "restart the game for changes to have effect" message from the game.

**To Reproduce**  
1. Start the game with sound enabled
2. Go to the Options->Sound Enabled setting.  Toggle it.  Close the Options pane.

Title screen music will continue playing.

OR

1. Start the game with sound disabled.
2. Go to the Options->Sound Enabled setting.  Toggle it.  Close the Options pane.

Title screen music will not begin playing.

**Expected behavior**  
I'd expect the sound to begin/end immediately when the option is toggled.  If not then, at least when the pane is closed.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Debian Buster
 - Game Version: 0.C-37210-ge6e18909ca
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition

**Additional context**
Might be a side effect of #23356; have not checked.  It's also possible that part of the issues hit in #26422 was the user not understanding that restarting was required (@perryprog mentioned "a few restarts").

**Comment by mark7** [comment]
Note that menu move sounds are enabled/disabled -- just not the music.

**Comment by mark7** [comment]
Throwing more issues in here, since filing all of these as separate tiny issues is probably pointless spam; probably easier to just have a "fix basic audio issues" patch.

Another bug that this turns up is that closing the options menu tries to apply music volume settings.  It does so by calling Mix_VolumeMusic() globally, which clobbers the per-track music volume soundpack setting support in musicset.json until the next track starts playing.  AFAICT, no actual soundpack is making use of a per-track volume anyway (they just set all tracks to the same volume), but even then it throws out the existing global scale to the volume that the soundpack author has set.  I've not tested this; this is just from code examination.

Another likely bug is that Cataclysm has probably been inadvertently playing music (maybe sounds in general) at too low a volume.  SDL_mixer appears to use a 0-MIX_MAX_VOLUME (presently 128)-based volume; Cataclysm appears to use a 0-200 range (defaulting to 100), and has been passing this number directly to SDL_mixer calls without mapping to 0-MIX_MAX_VOLUME.  That being said, presumably soundset authors have tuned as best they can to this, so retaining existing volume levels would be desirable, though the existing volume-setting behavior will probably be wacky for users; increasing the music volume above 128 will simply internally leave it at 128 as per SDL_mixer documentation.

**Comment by kevingranade** [comment]
> Throwing more issues in here, since filing all of these as separate tiny issues is probably pointless spam; 

If you're ok with the issue being closed based on the contents of the OP, go ahead.

**Comment by mark7** [comment]
SDL_Mixer apparently lacks built-in amplification support; short of adding another library, it's not possible to play audio louder than the initially-recorded level.

It looks like the problem is also present for all Cataclysm audio, not just for music, so I'll indeed commit the volume fix out in a different patch.

**Comment by mark7** [comment]
Patch will fix the "clobbering playlist volume" bug, just not the global music volume bug; moved that to #31301.

**Comment by mark7** [comment]
One more breakage in the current sound preferences: switching a soundpack presently does not start playing a track from the newly-loaded music playlist.  This patch will also fix that.
