### ISSUE TITLE
Some woods soup recipes can use organs, while some can't

### ISSUE THREAD

**Issue by Xhuis** [CleverRaven/Cataclysm-DDA#28020]
**Describe the bug**  
The normal and jarring recipes for woods soup can utilize organs like kidneys, livers, and lungs in their recipes as part of the first ingredient, while the canning and 3L jarring recipes can't.

**To Reproduce**  
1. Try to craft woods soup.
2. See that canning and 3L recipes can't use organs.

**Expected behavior**  
Because the other two recipes can use organs fine, I'd assume that they're also usable in regular crafting. Seeing as portion size between the normal soup and canned soup is the exact same, I know it's not that smaller portions can't use it.

**Screenshots**  
### Normal soup, with organs
![](https://i.imgur.com/KYLHnPp.png)
### Canned soup, lacking organs
![](https://i.imgur.com/1fEQjJW.png)

**Versions and configuration:**
 - OS: Windows 10
 - Game Version: 0.C-37210-ge6e1890
 - Graphics version: Tiles
 - Mods loaded: Reproducable with no mods loaded except Dark Days Ahead

**Additional context**  
I'm not really sure why this issue exists, as the json seems identical between the variants.

**Comment by KorGgenT** [comment]
woopsie. missed a couple. this would be a very simple fix.

**Comment by mount2010** [comment]
looks like canned and jarred lack meat_nofish which has the organs. PRing
