### ISSUE TITLE
Advanced inventory moves wrong items (bones)

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#28023]
**Describe the bug**  
Advanced inventory moves items not from pile that was selected.

**To Reproduce**  

0. Have different types of bones on the same tile with some other items. Wish for 10 bones. Spawn a beaver. Kill the beaver and butcher it. Put wished-for bones in the same tile as beaver bones. ~~I have three types of bones: one from underbrushes, one from butchered beaver, one form butchered pit bull mix.~~
1. Try moving one bone from each group or some other items from the save tile into your inventory.
2. When selecting bones only one group is moved, additionally sometimes bones from this group is moved when some other item is selected for moving.

**Versions and configuration:**
 - OS: Ubuntu 19.04
 - Game Version: latest master, 37a8bcd
 - Graphics version: Tiles

**Additional context**  
If this will not be confirmed in several hours I'll try to produce a minimal savegame for reproduction.

**Comment by int-ua** [comment]
Any pile with charges will also get you a wrong item in the inventory.

**Comment by ifreund** [comment]
Confirmed, working on a fix now.

**Comment by ifreund** [comment]
Well, I can tell you what happened, [this comment](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/advanced_inv.h#L142) lied to me.  The fix isn't very straightforward unfortunately, so it might take a minute.

**Comment by kevingranade** [comment]
Fixed by #28028
