### ISSUE TITLE
Crowbar in Firefighter Belt.

### ISSUE THREAD

**Issue by MechaJeb** [CleverRaven/Cataclysm-DDA#28037]
If I have a crowbar in a firefighter belt, whenever I try to pry a window it asks me which tool to use, The belt with the crowbar, or the crowbar. https://i.imgur.com/VXcoAqn.png  
If I pick the belt, prying action fails. https://i.imgur.com/bEuw3H7.png  
Ideally it would just use the crowbar by default without asking.

**Comment by ThinkInvis** [comment]
Seems like this is another consequence of #27949: it's using a "stock" dummy copy of the firefighter belt to attempt the actual pry action, ignoring entirely that the original reference was to one with a crowbar in it. The "would just use the crowbar by default without asking" part is already an issue of its own (#27880), and the solution I started working on is currently affected by the 0.D Feature Freeze. I'll see about patching _this_ issue for now -- probably by making the "does this tool have a prying quality" check also use dummy items -- but the underlying issues linked above will need to be solved eventually.

**Comment by kevingranade** [comment]
Fixed by #28039
