### ISSUE TITLE
Advanced Inventory "all surrounding tiles" unable to move items out of vehicles

### ISSUE THREAD

**Issue by gcaliber** [CleverRaven/Cataclysm-DDA#28047]
**Describe the bug**  
Advanced Inventory does not move items out of vehicles when all 9 squares are selected. Move a specified number of items will still prompt for how many, but nothing is moved.

**To Reproduce**  
Choose all surrounding tiles in advanced inventory and try moving any items inside a vehicle to another inventory.

**Versions and configuration:**
 - OS: Ubuntu 18.04
 - Game Version 0.C-37239-g4feabd3ccf

**Comment by JayThirtySeven** [comment]
I'm having the same bug, only one thing to add: Using the 'move all' command still works as expected.

OS: Arch Linux
Version: 0.C-37240-gdb346f94e8

**Comment by ifreund** [comment]
Confirmed, will take a look at this when I wake up.

**Comment by MetroidHunter** [comment]
> I'm having the same bug, only one thing to add: Using the 'move all' command still works as expected.
> 
> OS: Arch Linux
> Version: 0.C-37240-gdb346f94e8

I was worried there for a moment!

**Comment by kevingranade** [comment]
Fixed in #28056
