### ISSUE TITLE
Can't make clean water out of water in a pot

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#28044]
**Describe the bug**  
If I'm wielding a pot, that has some (not clean) water in it, I cannot use "clean water" recipe as it tells me I don't have a tool with boiling quality of 1 or more.

**To Reproduce**  
1. wield a pot
2. get some water into the wielded pot ("pour it into container")
3. try to craft clean water

**Expected behavior**  
The clean water is crafted.

**Screenshots**  
![cataclysm-tiles_2019-02-03_21-34-52](https://user-images.githubusercontent.com/7831163/52183020-9dd88c80-27fb-11e9-827e-fb4d604997f3.png)
![cataclysm-tiles_2019-02-03_21-35-05](https://user-images.githubusercontent.com/7831163/52183021-9fa25000-27fb-11e9-8a0f-a3c8bea14952.png)

**Versions and configuration(please complete the following information):**
![cataclysm-tiles_2019-02-03_21-35-44](https://user-images.githubusercontent.com/7831163/52183023-b2b52000-27fb-11e9-9661-905d3afcc321.png)

**Comment by ThinkInvis** [comment]
This looks an awful lot like a duplicate of #171. ...and there've been at least two more similar issues posted in the past three months. Kinda surprised nobody's tried putting a bounty on it yet, but I'm not sure what the criteria on those are.

Tried taking a shot at brainstorming the beginnings of a solution, which I'll post on the linked issue shortly.

**Comment by moxian** [comment]
Right. Specifically a duplicate of #27326
Didn't find that on initial search.
I'll close this one then, apologies.

**Comment by joeljpa** [comment]
Add another take on this...I raised this on Reddit and quite a few ppl in the sub concurred. 
["can drink boiled water directly but can't do it when we don't have a container"](https://www.reddit.com/r/cataclysmdda/comments/bqvn1s/can_drink_boiled_water_directly_but_cant_do_it/)
