### ISSUE TITLE
Boxes of flour still only spawn with 10

### ISSUE THREAD

**Issue by gcaliber** [CleverRaven/Cataclysm-DDA#28048]
Several recipes that use flour were changed to use 10 times as much, but boxes of flour still spawn with just 10. The recipes to make flour were changed to make 10 times as much, so spawned boxes of flour should probably have more than 10. Cornmeal looks like it may be a similar issue.

Game Version 0.C-37239-g4feabd3ccf

**Comment by KorGgenT** [comment]
dumplicate of #27863
