### ISSUE TITLE
Scenario description shown on every load of save

### ISSUE THREAD

**Issue by ifreund** [CleverRaven/Cataclysm-DDA#28062]
**Describe the bug**  
The message describing the starting scenario introduced in #28042 is shown every time a save is loaded

**To Reproduce**  
Load a save.

**Expected behavior**  
The message is only shown when first loading into the game as a new character.

**Comment by Treah** [comment]
I can confirm this is happening on the current build and I do not think its limited to just that scenario. 
![screenshot_2019-02-05_11-34-58](https://user-images.githubusercontent.com/12091471/52295917-3f65f800-293a-11e9-93de-2fca5a1f00d8.png)

**Comment by ifreund** [comment]
> I can confirm this is happening on the current build and I do not think its limited to just that scenario.

Just realized I linked #2804 not #28042.  Yeah this is a problem with every scenario if that wasn't clear originally.
