### ISSUE TITLE
Mark favorite items in inventory

### ISSUE THREAD

**Issue by IronRex** [CleverRaven/Cataclysm-DDA#28061]
**Is your feature request related to a problem? Please describe.**  
It is common to carry a certain set of items in inventory at all times. Might be a lighter to start fires, a flashlight, a lock-pick, aspirin, syringe of adrenaline, etc. It varies from player to player and from situation to situation. It is also common to load your backpack, pockets and any other place that can hold a milliliter with the random, not immediately useful, temporary loot that is to be dropped later at your truck or base.

**Describe the solution you'd like**  
Add an option to mark an item as favorite. Favorite items appear a different color in inventory. Later that can be expanded to "drop all but favorite" functionality.

**Describe alternatives you've considered**  
Perhaps some integration with auto pickup but this is not for pickup (might be for drop-off later). It is purely visual.

**Additional context**  
I am keeping the scope intentionally small: only a color change. I want to try to code this myself. If requested additional functionality ("drop all but favorite") can be added later.

**Comment by ThinkInvis** [comment]
If it doesn't add too much overhead: this might be better as _named sets_ of items (or tags or something else similar), instead of just one direct on/off category.

**Comment by IronRex** [comment]
@ThinkInvis That is out of scope of this issue but may be open another issue for that.

I am new to Cataclysm code so I want to do something small yet useful. Named item sets would require a separate menu to manage them (add, remove, rename, etc.).

**Comment by IronRex** [comment]
I am still studying the code base. No PR yet but I already have some things figured out.

Devs please leave this to me unless this message is really old and I gave up.

**Comment by IronRex** [comment]
I figured out how to add a menu item, how to act on that menu item and how to persist new item property. I still have to figure out how to highlight favorite items in various items lists. Here is current progress.
https://github.com/IronRex/Cataclysm-DDA/tree/favorite_items

**Comment by Fris0uman** [comment]
You could make a PR marked as [WIP] to get feedback as you go.
But figuring it out on your own before the PR also works of course.

**Comment by ZhilkinSerg** [comment]
Closed in #28105.
