### ISSUE TITLE
New zombie drops seem unbalanced 

### ISSUE THREAD

**Issue by Mcrone617** [CleverRaven/Cataclysm-DDA#28072]
**Describe the bug**  
This might just be me, but the new zombie drop system (which is great btw, zombies drops finally make sense) seems a bit unbalanced. Every other zombie drops pretty useful items, anything from watches, multi tools, solid storage items, it's a cornucopia of wealth compared to previous zombie drops.  

**To Reproduce**  
Kill zombies, enjoy your newfound wealth

**Expected behavior**  
The basic behavior is fine, just maybe slightly toned down? If this is going to be the new norm i'm not complaining, it just seems pretty easy to get everything, and houses seem slightly toned down for drops comparatively.

**Versions and configuration
Windows 10, 
Version O-C 37268- ga356c14

**Additional context**  
Again, the current setting are pretty good, I'm just concerned it's a bit easier to get rare "handheld" items now, not sure every other person should have a game system on them. I suppose I could always turn down item spawns, although i'm not sure it affects zombie drops.

**Comment by Leland** [comment]
PR in question is #27626

**Comment by Zombiemanpig** [comment]
Just want to say I made a Github accouunt to comment on this.

I like how drops are changed, but as of right now zombies (even low level ones) drop so many items that in the early game my 9 stats 0 skills survivor can punch a few zombies to get to unarmed 2 and find most early game tools I would need to really look for all before the first sleep. I don't even feel the need to explore, killing seems to make more sense in some ways except for maybe basements...

I think just general drops on the numbers all around is needed, so regular zombies don't drop more than 2 items a piece (and on average 1 with some 0's) and things like brutes and hulks can drop a few more cause they probably ate some people to get so big and thus would have more items on them.

Also I think the min battery on some of the drops should be increased from 0, when I first played this patch (and maybe this is a bug too!?) the battery of the first item I saw was 0, the second one was 1, the third one was 2, etc until 17 and then it seemed to go random. 

Too many drops = boring game.

**Comment by Treah** [comment]
I think the fix for this would probably to make some of the items a bit more rare on zombies. The multitool is the first one that comes to mind for me as I think it drops a bit too often and honestly I kinda feel that people don't normally carry them around all the time.

**Comment by Shodan14** [comment]
Another idea might be to reduce the condition of pretty much everything they drop as well.

**Comment by MyculplantKatze** [comment]
what if we made it so the zombies ate said items and you had to do a full butcher to get it out of their stomach Owo

**Comment by WilliamtheCardboardBox** [comment]
I completely agree. The drops are way too much right now. Currently, I have about 15 multitools on day 10.

**Comment by Night-Pryanik** [comment]
Okay, one specific suggestion - reduce the number of multitool drops. 
What else? Please be specific, as generic suggestions like "Zombie drops are unbalanced" ain't good.

**Comment by Mcrone617** [comment]
The problem is of course is that your argument is pretty on point, it's pretty conceivable that people could have all this stuff on them when they die, Maybe limiting the number of items that spawn on a zombie that doesn't have a bag, for example limiting item spawns on a person to one or two items max? 

Another thing that could be important could be the increase the spawning of "useless" items, such as files, dead phones/smartphones, cigarettes, and maybe the reduce the chance of the knives/tools spawning? , although when looking at your PR, it seems your weighting is pretty good already, people do tend to carry stuff around with them.

I don't know if this is possible, but as I stated above if its possible to cap the number of items that can spawn on a zombie without a bag to one or two, and including the cash cards in this calculation this would really slow down the rate at which the loot drops. Combined with a slight reduction in the chance a bag spawns on zombies, and I feel it would probably slow down the rate of extreme loot progression we have today.

**Comment by Eliijahh** [comment]
It is difficult to strike a good balance. For instance, most zombies should have a mobile phone, probably the most universal item anyone would have on themselves while wandering around in a city (free batteries from a gameplay perspective)

Surely the multi-tool spawn rate should be decreased, as I do not think most people would go about with one. 

**Just throwing some ideas:**

- Perhaps adding the "Filthy" tag to items dropped from zombies? (inb4 30 dislikes) I mean it would make sense: clothes are filthy, but items are not? 
- Maybe make the quality of tools much lower when spawned from zombies: you can still use them for some activities, but for more complex ones you need to find proper tools from stores etc... 
- Dramatically slash the drop chance for items from zombies, tanking the "lack of realism" for the sake of gameplay

@Mcrone617 I also like the idea of increasing the drop-rate of useless items, so that the more useful ones will spawn less

**Comment by Night-Pryanik** [comment]
> so that the more useful ones will spawn less

What items in particular do you consider "more useful ones"?

**Comment by Zombiemanpig** [comment]
> It is difficult to strike a good balance. For instance, most zombies should have a mobile phone, probably the most universal item anyone would have on themselves while wandering around in a city (free batteries from a gameplay perspective)

Do we really want that tho? The catacylsm world is a place with more advanced tech than us, I would assume they got there not by wasting time on their phones and inventing smart phones but by focusing on bionics and mutations and tran's universal travel (instead of other stuff). 

Also gameplaywise:
Can we all agree that ideally all zombies have at least 1 item even if that item is an empty cellphone or file or something?

I can do a bit of math can get some good numbers for the people wanting exact numbers, I just want to double check something:
We can have the chance to spawn a cellphone with 0 battery at a certain % level, and then the chance to spawn a 50:100 cellphone at a different level (I imagine the code would be just the same thing twice but with different values, no problems doing that right?).

**Comment by Eliijahh** [comment]
> > so that the more useful ones will spawn less
> 
> What items in particular do you consider "more useful ones"?

You are right, I should've specified. I believe I meant the following categories as "useful":
- Objects containing batteries, especially phones should have 0 battery as they were probably switched on at the time of the apocalypse
- Tools, multi-tools specifically, maybe reducing the drop-rates, or allowing only firefighters, technicians and zombie survivors to be able to drop tools 
- Food, I felt zombie children drop too many candies, but it may be only me!

To be honest I do not feel that currently the system is **too** unbalanced, maybe those additions are enough?

**Comment by Night-Pryanik** [comment]
> Do we really want that tho? The catacylsm world is a place with more advanced tech than us, I would assume they got there not by wasting time on their phones and inventing smart phones but by focusing on bionics and mutations and tran's universal travel (instead of other stuff).

Even if people focus on bionics and mutations, they won't simply throw away one of the most practical tools invented ever such as mobile phones.

> Can we have the chance to spawn a cellphone with 0 battery at a certain % level, and then the chance to spawn a 50:100 cellphone at a different level

Yes, we can, but in some cases this would spawn two phones, I don't think we want this.

> Objects containing batteries, especially phones should have 0 battery as they were probably switched on at the time of the apocalypse

As by default game starts 5 days after the Cataclysm, phones will be mostly discharged by that time. As for now, I made phones spawn with a 0..20 batteries in them, but ok, I can decrease the upper limit even lower, up to 10 (is this okay?) batteries. (No one cared though that prior to zombie drops rebalance most tools - including phones - always spawned with 100 batteries in them).

> Tools, multi-tools specifically, maybe reducing the drop-rates, or allowing only firefighters, technicians and zombie survivors to be able to drop tools

For now, there is 20% chance to spawn multi-tool, I can decrease it to only 5% (is this okay?). Other tools (carpentry, electronics etc) already have only 5% to spawn, I don't think it needs further lowering.

> I felt zombie children drop too many candies, but it may be only me!

Zombie children have their own drops list, different from the ordinary zombie drops list.

* * * 

In my PR I increased chance to drop something from 50% to 75%. I could decrease it back down to 50% if you think that too many zombies drop things on their own, no matter how many things in particular they get.

**Comment by Mcrone617** [comment]
The multi tool change seems good. Maybe decrease the rate at which knifes spawn also? (slightly) And when you say reduce the drop chance to 50%, does that mean that zombies have a 50% chance of having either items and bags? or do the bag zombies have a different selection process in addition to people with full pockets.

**Comment by Night-Pryanik** [comment]
> Maybe decrease the rate at which knifes spawn also? (slightly)

For now it's 10% chance to spawn. Decrease it to 5%?

> And when you say reduce the drop chance to 50%, does that mean that zombies have a 50% chance of having either items and bags?

For now zombies have a 75% to spawn anything (except for clothing, which spawn is guaranteed) on their death. If this check succeeds, there is 20% chance to spawn items from the "pockets" items list, and 16% to spawn items from the "bags" items list. "Bags" items list includes "pockets" items list. 

(Oh, it seems that I forgot to add percentage of spawn for this "included" "pockets" items list, so "pockets" items list will _always_ spawn if 16% chance to spawn "bags" items list check succeeds. Will fix.)

**Comment by Amoebka** [comment]
Having most zombies drop items with low battery charges can feel bad for players - you need to manually unload way too often, which is extra clicks. I think having completely empty appliances with a small chance of having full charge is much better. It leading to a small chance of zombies dropping 2 phones might be acceptable evil, some people do indeed carry 2 phones around in real life. Alternatively, all devices would drop empty, but some zombies would carry spare batteries on them.

**Comment by Mcrone617** [comment]
I agree about the devices being empty, it's easier on the inventory management also, as having a list of 6 identical phones with 6 different charges could get a bit annoying. Compensating by slightly bumping up the chance for a spare battery would work well. 

When you say that there is a 20% and 16% chance for the pockets/bag loot list, what happens if neither of these items spawn? does it just spawn a cash card? I agree that dropping the overall item spawn rate back to 50% would help out a lot. reducing the knives to 5% is also a good idea I feel.

**Comment by Night-Pryanik** [comment]
> When you say that there is a 20% and 16% chance for the pockets/bag loot list, what happens if neither of these items spawn? does it just spawn a cash card?

`default_zombie_drops` item group contains 100% chance of spawning clothing, 75% chance of spawning items, and 10% chance of spawning cash card. These chances are all rolled independently.

**Comment by baraba3** [comment]
While multitool drops seem too frequent for gameplay purpose i like that i didnt find much toolboxes and other heavier tools.Lore wise mutlitools and some other usable drops make sense as if people were trying to run and they took some usable items with them before they died.I particulary like that sunlasses are no logner ultra rare and i can make weldign googles myself before i find pba mask. Also smartphones  being common now is god send and understadable(like those high quality lenses)

**Comment by ZhilkinSerg** [comment]
Should be fixed with #28130 or need more balancing?
