### ISSUE TITLE
Static NPCs are too vulnerable to burning buildings

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#28070]
**Describe the bug**  
Start with an NPC in a burning building, and he is unlikely to outlive the fire. Light the refugee center or the farm - no survivors. The easiest way to deal with the bandit cabin is to burn it. Static NPCs shouldn't count as sentient species, i think.

**Comment by Night-Pryanik** [comment]
Addressed by #28840.
