### ISSUE TITLE
it should be possible to `a`ctivate stone adze to saw trunk into planks

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#28071]
**Describe the bug**  
Trying to `a`ctivate stone adze is possible but gives a "you can't do anything interesting with your stone adze", even when staying near/on a fallen tree trunk.

I've just now (several IRL days after crafting adze) accidentally noticed a "chop tree trunk into planks" option in construction menu (`*`). This is very confusing, since chopping down a tree is done in a completely different way - by `a`ctivating an axe, not via construction menu.

**To Reproduce**  
1. Have a stone adze
2. try to `a`ctivate it
3. "you can't do anything interesting with your stone adze"

**Expected behavior**  
`a`ctivating stone adze asks which tree trunk I want to saw (direction), similar to what `a`ctivating an axe does (and then, naturally, saws the trunk into 2x4s)

Alternatives I see are:
- move using axe to cut a tree to construction menu as well (please don't)
- disabling the `a`ctivatable bit on adze (and other wood sawing tools?)
- adding a "you can saw tree trunks via construction menu" to the description of all tools with wood sawing quality

**Versions and configuration(please complete the following information):**
![cataclysm-tiles_2019-02-03_21-35-44](https://user-images.githubusercontent.com/7831163/52254109-a9af7600-2903-11e9-8532-bf3b4be40a1c.png)

**Additional context**  
Somewhat offtopic, but the action of producing planks with adze is "Saw tree trunk into planks" not "Chop tree trunk into planks" as the construction menu has it.
Additionally, (on a different offtopic) the description for the result of the construction action is... the following:
![cataclysm-tiles_2019-02-05_05-03-22](https://user-images.githubusercontent.com/7831163/52254103-a1573b00-2903-11e9-9514-c255536fe594.png)

**Comment by Treah** [comment]
They used to both be in the construction menu and then chopping tree was moved out to a item activation. Not sure why it was done but this is the reason for the discrepancy.

**Comment by Night-Pryanik** [comment]
It was done because chopping trees doesn't belong to "construction". 
As for the issue itself - sawing wood should be moved from construction to `a`ctivating wood sawing tools too.

**Comment by Zombiemanpig** [comment]
> It was done because chopping trees doesn't belong to "construction".
> As for the issue itself - sawing wood should be moved from construction to `a`ctivating wood sawing tools too.

If you do that can you keep the survival 2 requirement or would that be removed? Should it even be there?

**Comment by Night-Pryanik** [comment]
> If you do that can you keep the survival 2 requirement or would that be removed? Should it even be there?

Well, I think survival 2 is a bit extreme, I believe almost everyone can figure out how to saw tree trunks. Probably lower it to survival 1.

**Comment by kevingranade** [comment]
Survival 2 is warranted, this is not a simple process, especially with a blade instead of a chainsaw.

**Comment by Treah** [comment]
If work is going to be done to move items out can we also make the levels mean something? Currently tree chopping 2 means nothing and is not required for anything. I think this has been requested before as well. 

Survival 2 is also extremely easy to get, just examining bushes can get you there on day one.

**Comment by Zombiemanpig** [comment]
> If work is going to be done to move items out can we also make the levels mean something? Currently tree chopping 2 means nothing and is not required for anything. I think this has been requested before as well.
> 
> Survival 2 is also extremely easy to get, just examining bushes can get you there on day one.

I thought tree chopping 2 substituted for for wood cutting 1 or something like that? (as shown in the picture in the OP) As well as be able to chop trees. It is not useless.

**Comment by Night-Pryanik** [comment]
> Currently tree chopping 2 means nothing

Tree chopping quality level directly affects time required to chop down tree.

**Comment by Treah** [comment]
@Night-Pryanik 
I thought it did not but I had not tested it in a recent build. So ill redact that.

**Comment by kevingranade** [comment]
I totally missed this the first time around, a stone adze is completely unusable for riving planks, the current lack of AXE quality is intentional.

It looks like it CAN be used to very slowly fell a tree, and it's useful to very roughly hew logs into rough beams for e.g. building a cabin, but planks are *right out*.

**Comment by moxian** [comment]
Stone adze:
- is still `a`ctivatable
- still yields a "you cannot do anything useful with your stone adze" message if activated.
- still can be used to "Chop Tree Trunk Into Planks" because it still has wood sawing quality of 1.

I'm not sure why this issue is closed - no changes were made and none of the original concerns are addressed as I see it.

I don't have an opinion on the balance and whether adze should or shouldn't be able to fell a tree/cut trunk into logs/cut log into planks.
However the current behavior is terribly confusing purely from the UI perspective.

**Comment by Treah** [comment]
@moxian 
LOL I just read this and I agree, everyone got so flustered about the balance change and never fixed the actual problem you asked to change. I would make a new issue.
