### ISSUE TITLE
Repairing items with filthy materials causes error

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#28089]
**Describe the bug**  

When you repair CLEAN clothing and only have filthy stuff around, it will work and you will get an error.

**To Reproduce**  
1. Use a wooden needle or bone needle or something
2. Have filthy rags or something filthy nearby to repair your clothes with
3. Repair clothes.

**Expected behavior**  

Not sure, but not a bug error thing,

**Screenshots**  

https://i.imgur.com/awE7ffw.png

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-37270-g86ec372
 - Graphics version Tiles
 - Mods loaded quite a few but I don't think they matter to this...

**Additional context**  

Can't believe no one tried this yet... or no one who found it is reporting it...

**Comment by ifreund** [comment]
Confirmed, working on a fix.

**Comment by Zombiemanpig** [comment]
> Confirmed, working on a fix.

I know it's a major thing that should be fixed before the Dick release but the fact that no one has found it for so long and I have been using it for so long and used to it (super good early game to repair your stuff, before you have access to like washing machine). I hope you don't put it on the top of your list to fix...

**Comment by moxian** [comment]
I think the ideal solution would be to allow all the following cases:
- you can repair clean items with clean materials (naturally)
- you can repair filthy items with either filthy or clean materials.
- you can repair clean items with filthy materials, but doing so makes item filthy. A warning/confirmation dialog would be useful.

When the item is composed of several different materials, and you have some of them only at a different cleanliness level from what you are repairing, you should still have them as an option.
E.g., you are repairing dirty sneakers (leather + cotton), and you have clean rags, clean leather patches and dirty leather patches, the game should not auto-assume that you want to use dirty leather patches, but instead ask the player if they maybe want to use clean rags for it.

I have no idea how difficult this is to implement.

**Comment by kevingranade** [comment]
Fixed by #28115

**Comment by adamkad1** [comment]
this still applies to padding though
