### ISSUE TITLE
wear UI try to duplicate object

### ISSUE THREAD

**Issue by nsklaus** [CleverRaven/Cataclysm-DDA#28086]
**Describe the bug**  
wear UI try to duplicate object

**To Reproduce**  
1. press W (wear something)
2. press / (filter)
3. press esc

```
 DEBUG    : Tried to add a duplicate entry.
 
 FUNCTION : void inventory_column::add_entry(const inventory_entry&)
 FILE     : src/inventory_ui.cpp
 LINE     : 599
```

**Expected behavior**  
nothing special should happen when cancelling the filter

**Versions and configuration(please complete the following information):**
 - OS: [Ubuntu 18.10]
 - Game Version [0.C-37276-gb0e46bd217-dirty]
 - Graphics version [Tiles]
 - Mods loaded [
  "dda",
  "no_npc_food",
  "novitamins",
  "generic_guns",
  "more_locations",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "DP_AMAZING_CHEST_INDICATORS",
  "DP_REMIX_INDICATORS",
  "DP_XOTTO_INDICATORS",
  "no_rivtech_guns",
  "more_classes_scenarios",
  "safeautodoc",
  "manualbionicinstall"
]

**Additional context**  
this is the saved game (note it is tar.gz i just renamed it to 'zip' to be able to upload it)
[evergreen.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2834321/evergreen.zip)

this is the debug log:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2834326/debug.log)

**Comment by MyculplantKatze** [comment]
* "generic_guns"
or these 3 probably did it because i have tested most of those mods and i dont think that classes scenarios can fuck around with inv last time i looked 
* "DP_AMAZING_CHEST_INDICATORS",
  "DP_REMIX_INDICATORS",
  "DP_XOTTO_INDICATORS",

**Comment by nsklaus** [comment]
>     * "generic_guns"
>       or these 3 probably did it because i have tested most of those mods and i dont think that classes scenarios can fuck around with inv last time i looked
> 
>     * "DP_AMAZING_CHEST_INDICATORS",
>       "DP_REMIX_INDICATORS",
>       "DP_XOTTO_INDICATORS",
>       Edit: NVM i tested all 4 of those together and they were not causing it ¯_(ツ)_/¯

but can you confirm the issue ?

**Comment by MyculplantKatze** [comment]
Did you use a save from a previous version? I'm guessing it may just be the download or the save missing something or having something extra, like my endless acid ant faction bug that I refuse to fix!

**Comment by nsklaus** [comment]
> Did you use a save from a previous version? I'm guessing it may just be the download or the save missing something or having something extra, like my endless acid ant faction bug that I refuse to fix!

it is quite possible that it was something in my inventory. i'm using the same saved game across various builds i'm working on, some were a bit old. and i noticed with a new game i could not reproduce this, while with my usual save it was 100% reproducible. if noone experience this bug it maybe be safe to conclude you were correct in your assumption i think.

**Comment by ifreund** [comment]
Couldn't reproduce on the save you uploaded or a clean one.  I think you're right in suspecting that it was something weird on your end.
