### ISSUE TITLE
Reloading sealed stomach with fruit juice causes crash

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [CleverRaven/Cataclysm-DDA#28096]
**Describe the bug**  
When attempting to refill a container, you will crash.

**To Reproduce**  
This one is a little inconstant with how it happens, but when it happened to me, I was using a sealed stomach. I filled it using a hydria of fruit juice. This resulted in a segmentation fault error.

**Expected behavior**  
A lack of crashing.

**Screenshots**  
![image](https://user-images.githubusercontent.com/38237593/52337862-ae386500-29bd-11e9-88bc-4d560d670f1c.png)

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version [0.C-37272-g429ff34]
 - Graphics version [Tiles]
 - Mods loaded [
  "dda",
  "filthy_morale",
  "novitamins",
  "More_Survival_Tools",
  "alt_map_key",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "dda-lua",
  "dda-lua-items",
  "dda-lua-skills",
  "dda-lua-traits",
  "Tolerate_This",
  "Bootleg_Walkers",
  "FIC_Weapons",
  "realguns",
  "growable-pots",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "nw_pack",
  "DracoDogMod",
  "DinoMod",
  "modular_turrets",
  "Salvaged_Robots",
  "Mining_Mod",
  "mutant_npcs",
  "national_guard_camp",
  "BIGRIVER",
  "more_locations",
  "FujiStruct",
  "cityside",
  "oa_additional_buildings_mod",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "necromancy",
  "StatsThroughSkills"
,
  "sleepdeprivation",
  "manualbionicinstall"
]

**Comment by ifreund** [comment]
Can't seem to reproduce this one. Could you upload the affected save maybe? More detailed instructions?  Does it still happen on the most recent version?

**Comment by SolsticeTheTechMarine** [comment]
That's another issue, the method of reproducing this is unreliable. I tried the same thing after I reloaded the save and it didn't cause segmentation fault error. What I put into the top portion is the stuff I did before the error occurred.

**Comment by aoae23** [comment]
Would it be possible to upload the affected save? That would allow more testing to be done to resolve the issue.

**Comment by SolsticeTheTechMarine** [comment]
[Nocturne.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2848950/Nocturne.zip)
This is the file it happened on. I have played it a decent amount since.

**Comment by kevingranade** [comment]
If we can't reproduce the issue, there are no prospects for fixing it before 0.D.

**Comment by ZhilkinSerg** [comment]
Cannot reproduce on current `master`.
