### ISSUE TITLE
Harvesting garlic garden pot yields cucumbers

### ISSUE THREAD

**Issue by settdigger** [CleverRaven/Cataclysm-DDA#28099]
**Describe the bug**  
Harvesting garlic garden pot yields cucumbers

**To Reproduce**  
Harvest by disassembling a garden pot of garlic

**Expected behavior**  
Get garlic

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS:  Windows 10 
 - Game Version 0.C-37221-ga9b8568 (tiles)
 - Graphics version Tiles
 - Mods loaded: boats

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by AMurkin** [comment]
Fixed by #28107
