### ISSUE TITLE
Zombie Hollow causes messages to appear when attacking a creature it can't reach, as if it's attacking the player

### ISSUE THREAD

**Issue by Little-119** [CleverRaven/Cataclysm-DDA#28092]
**Describe the bug**
As I explored a lab, I kept getting messages about how a zombie hollow that I couldn't see was thrusting its arm at me, but it bounced off reinforced glass.
Upon finally finding the zombie hollow, I found that a skitterbot was stuck just outside the glass box that was containing the zombie hollow. Apparently both wanted to attack the other but was blocked by the reinforced glass. Upon defeating the skitterbot, the message spam stopped.

**To Reproduce**
1. Put a zombie hollow in a reinforced glass box, or otherwise some kind of container that allows it to see a non-player hostile creature but not attack it
2. Put a non-player hostile creature outside of the box
3. Move away from what you've just created
4. Observe the message spam

**Expected behavior**
To not get messages about what a creature is trying to do to another creature, as if I am the latter creature, especially when neither is in sight.

**Screenshots**
![](https://i.imgur.com/eUvdZcV.png)
![](https://i.imgur.com/MAhbe5M.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-37270-g86ec372
 - Graphics version Tiles
 - Mods loaded: Bens GF recipes, Extended Realistic Guns, Craft Ammo Mags & Belt Links, Craft Ammo Mags - ERG, Growable pots, Makeshift Items Mod, More Survival Tools, Modular Turrets, Salvaged Robots, Alternative Map Key, Mining Mod, Mutant NPCs, More Locations, Fuji's More Buildings, Big River Building Pack, Oa's Additional Buildings mod, Urban Development, Vehicle Additions Pack, Boats, Folding Parts pack, Disable Religious Texts, No Bees, Classes and Scenarios Mod Filthy Clothing, StatsThroughSkills

**Additional context**
To clarify, the messages seem to appear so long as the zombie is in the reality bubble.

**Comment by ZhilkinSerg** [comment]
Should be fixed with #28130.
