### ISSUE TITLE
NPC with venom mob protege does not have any martial arts to teach player character

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#28106]
**Describe the bug**  
NPC with the trait Venom mob protege is not able to train me in any martial arts.

**To Reproduce**  
1. Find NPC with venom mob protege (maybe keep spawning them in until you get one)
2. Get as a follower or complete quest (I have done both) and ask for training
3. Cry when there is no martial art to learn available 

**Expected behavior**  
I suspect the NPC doesn't even have the martial art himself but not sure how to check.

The behavior should be he has a martial art to train me in.

**Screenshots**  

https://i.imgur.com/i01V4C7.png
https://i.imgur.com/Cj7q564.png

**Versions and configuration(please complete the following information):**

* OS: * Windows 10
* Game Version  0.C-37270-g86ec372
* Graphics version Tiles
* Mods loaded StatsThroughSkills, Mutant NPCs, location mods, no extra items mods AFAIK (Except for vehicle additions).

**Additional context**  
I am using Mutant NPC mod but I don't think that should affect this, maybe it does?

**Comment by Night-Pryanik** [comment]
Please replace the template text with your own description of the bug.

**Comment by Zombiemanpig** [comment]
> Please replace the template text with your own description of the bug.

Yea, I accidentally pressed enter.

**Comment by I-am-Erk** [comment]
The issue here is that venom mob protege is outdated and no longer does anything, but is still listed as a possible NPC trait. It just needs to be removed from the list of NPC traits.

**Comment by Zombiemanpig** [comment]
I found another starting static NPC with Martial Arts Training but with 0 unarmed combat and no martial art that they can train me in. I forgot to take a pic showing the NPC cannot train me in it but here is a pic showing that martial arts training is also affected and not just venom mob protege. @I-am-Erk 

https://i.imgur.com/ATayrb9.png

**Comment by Night-Pryanik** [comment]
Seems like it's a more complex problem, and there should some sort system which will decide what traits could be added to the character based on their stats and skills. In @Zombiemanpig's example NPC has a Skilled Liar trait, but has absolutely no skills in speaking.

**Comment by I-am-Erk** [comment]
That's no different from the player with the same traits
