### ISSUE TITLE
Mini Speargun does not appear in Ranged tab in crafting under the weapon header

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#28101]
**Describe the bug**  
In the All tab you can find the recipe but in the ranged tab you cannot.

**To Reproduce**  
1. Have required skills (just cheat in 20 in all)
2. Open crafting menu
3. Look for mini Speargun in the ranged tab in weapons (can find it in ALL tho)

**Expected behavior**  

Ranged weapons should be in the ranged tab.

**Screenshots**  

https://i.imgur.com/xIq9AKN.png
https://i.imgur.com/GIZHmTR.png

**Versions and configuration(please complete the following information):**

* OS: * Windows 10
* Game Version  0.C-37270-g86ec372
* Graphics version Tiles
* Mods loaded StatsThroughSkills, Mutant NPCs, location mods, no extra items mods AFAIK (Except for vehicle additions).

One day I will get more into programming and will fix these small bugs I see myself, but for now I hope yall don't mind I report them without being able to fix them :)

**Comment by ZhilkinSerg** [comment]
Should be fixed with #28130.
