### ISSUE TITLE
NPC's do not show splint healing on the (w)ound screen

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#28100]
**Describe the bug**  
About 2 months ago I was able to heal my friendly NPC's legs and see the progress on the wound screen.
New game, new version, 2 months later, my NPC equips the splints but the (w)ound screen doesn't show signs of healing. It seems to be working however as "recovery has started" on all 4 limbs in the character screen.

**To Reproduce**  
1. Break NPC limbs
2. Give them or equip them splints (before when it worked I did the "use this item" and I tried that again here and other methods and none seem to work)
3. Notice there is no change in the wound screen.

**Expected behavior**  
NPC's limb should show healing progress in the wound screen. He is equiping the splints... It used to show the progress....

**Screenshots**  
https://i.imgur.com/U6lzjU4.png
https://i.imgur.com/KOWiYbt.png
https://i.imgur.com/YGT6tIQ.png

**Versions and configuration(please complete the following information):**
 - OS: * Windows 10
 - Game Version  0.C-37270-g86ec372
 - Graphics version Tiles
 - Mods loaded StatsThroughSkills, Mutant NPCs, location mods, but I don't think any mod effects the wound screen, 

For sure it used to show the healing progress the same as on the player character. I will see if it actually heals or not over a bit of time from now.

EDIT: The NPC healed fine but the "inprogress" blue line I am used to never showed up on them.

**Comment by Night-Pryanik** [comment]
It would have been the duplicate of that item #23634, except that you're saying that wound screen actually showed limb healing progress..

**Comment by Zombiemanpig** [comment]
> It would have been the duplicate of that item #23634, except that you're saying that wound screen actually showed limb healing progress..

I remember it did about 2 months ago when I started playing Cataclysm DDA again. That issue you brought up is from Apr which is weird (I got back into it near the end of Nov 2018).

Too bad I don't have screenshot of it working... didn't know it was a bug...
