### ISSUE TITLE
move steeltoed boots into armor category

### ISSUE THREAD

**Issue by Leviathan21** [CleverRaven/Cataclysm-DDA#28110]
**Is your feature request related to a problem? Please describe.**  
as title says

**Describe the solution you'd like**  
steeltoed boots are armored leather boots with high protection values so they must be in armor category

**Comment by cburns2017** [comment]
Waiting for confirmation to make the change from the Discord. Then will start coding.

**Comment by Night-Pryanik** [comment]
Umm, they are already in the `ARMOR` category:
https://github.com/CleverRaven/Cataclysm-DDA/blob/2a8c342104ca756bd35775b73d6033192568d541/data/json/items/armor/boots.json#L350-L351

**Comment by austin9240** [comment]
I thoughts it had something to do with boots.steel being in clothing.json but that didn't seem to fix it when I removed it from that file, so I think it's reading it from some other .json file and that it gets categorized as a clothing item before it gets to the armor file I just can't figure out where.

**Comment by Photoloss** [comment]
Did you try adding [this](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/armor/boots.json#L69) line? `"type"` mostly seems to control which additional item properties are loaded while `"category"` is the in-game inventory assignment.
