### ISSUE TITLE
toss and turn mechanic delaying start of wake up a

### ISSUE THREAD

**Issue by joe9000** [CleverRaven/Cataclysm-DDA#28117]
**Describe the bug**  
Setting an alarm to wake up seems broken by the toss and turn mechanic. It appears that count-down until the alarm goes off isn't getting set until toss and turn transitions to fell asleep. As a result, character oversleeps.

**To Reproduce**  
1. Make a player that isn't tired and has an alarm clock.
2. Attempt to sleep and set an alarm for eight hours.
3. Eight hours from when you first attempted to go to sleep, the alarm does not go off.

**Expected behavior**  
The alarm should go off eight hours (or whatever the desired time period was) from when you first try to go to sleep, not a later point when you transition from tossing and turning to falling asleep.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 
 - Game Version 0.C-37320-g2a8c342
 - Graphics version: Tiles
 - Mods loaded: [ "dda", "filthy_morale", "makeshift", "Medieval_Stuff", "More_Survival_Tools", "npc_traits", "mutant_npcs", "deoxymod", "blazemod", "Tanks", "manualbionicinstall", "safeautodoc", "boats", "No_Fungi"]

**Comment by cburns2017** [comment]
Unable to replicate on build 0C.-37136-gb47fde8d25-dirty
No mods, Tiles, MacOS

**Before Sleep**
![before sleep](https://user-images.githubusercontent.com/46461848/52493861-83efce80-2b9a-11e9-9fc4-10ef8d5b4d69.jpeg)

**After Sleep**
![after sleep](https://user-images.githubusercontent.com/46461848/52493930-ad105f00-2b9a-11e9-8764-99bf5102d334.jpeg)

Other conditions necessary to replicate?

**Comment by joe9000** [comment]
haven't been able to reproduce outside the save i originally saw it in. going to close the issue, will circle back if i can reproduce.
