### ISSUE TITLE
NPC save their attitude towards player after his death

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#28113]
**Describe the bug**  
When your character dies, all your NPCS who you made friends with will be friends with your brand new character in your world.

**To Reproduce**  
1. Make friends
2. Die alone
3. Have people you never met before be willing to die for you.

**Expected behavior**  
Their faction should get reset on character death.

**Versions and configuration(please complete the following information):**

* OS: * Windows 10
* Game Version  0.C-37270-g86ec372
* Graphics version Tiles
* Mods loaded StatsThroughSkills, Mutant NPCs, location mods, no extra items mods AFAIK (Except for vehicle additions).

**Comment by CoroNaut** [comment]
Similar to #27293

**Comment by Night-Pryanik** [comment]
Renamed to show the broader issue.
