### ISSUE TITLE
Joint Torsion Ratchet stationary recharging activity

### ISSUE THREAD

**Issue by thethunderhawk** [CleverRaven/Cataclysm-DDA#28111]
Game version: current

Operating system: any

Tiles or curses: any

Mods active:any
I spend a lot of time on my Bionic Prepper running around in circles to generate bionic power for my Integrated Toolset. This forces me to spam button presses for irritatingly long periods of time. Since this is the optimal way to play and adds tedium, I think it’s a good candidate for automation. 
My pitch is this: give an option from the bionics screen to do standing squats, activating the Joint Tortion Ratchet while draining stamina and staying stationary. 

### Expected behavior
You can do stationary leg workouts to generate power in your Joint Torsion Ratchet

### Actual behavior
Game instead encourages you to do this tedious thing.

### Steps to reproduce the behavior
Play as a bionic prepper, try to make a bunch of clean water using your Integrated Toolset, notice how after a certain point you have to go run in circles to recharge.

**Comment by Zombiemanpig** [comment]
After the nerf to it's power generation I def would like this feature in. 

You can try setting up zones and having your character sort stuff to waste time/ build energy. Not sure if it works, I used to jumper cable myself to charge up and then sort stuff 10 tiles away with no problem with the cable so maybe it doesn't even count as movement.

Zoning and digging holes / planting / harvesting would def work for the movement.

**Comment by kevingranade** [comment]
Expected behavior invalid, the use case is passively charge while doing other activities, not intensively use it to charge.

**Comment by Szara-ManOfHonor** [comment]
That's hardly an invalid expected use. If a survivor needed to exercise to gain power, and had no other easier method to gain that power, that's what they would do if they wanted the power enough.

**Comment by thethunderhawk** [comment]
Maybe this is a miscommunication? If by “intensively” kevin means it shouldn’t generate more power/turn than walking around does, I totally agree.
Otherwise, I’ll just say this: IMO if the idea is that the Joint Torsion Ratchet should only generate power “passively” (that is, while doing things other than specifically trying to generate bionic power), the mechanics behind it need to be totally reworked, since as of now it makes sense both mechanically for the player and in lore for the average character to go out of their way to generate bionic power by whatever means they have.
