### ISSUE TITLE
Game crashing when i try to reach a npc

### ISSUE THREAD

**Issue by MigmaDiscordia** [CleverRaven/Cataclysm-DDA#28126]
i was playing cataclysm dda, then i went for search resources, and then i've found two npcs (in differents places) but when i try to reach the npcs, the games crashes(graphic version) or the game become very very very very laggy(console version).PS:my world is a inawoods, thats mean, no zombies and no cities

i've already updated the game , but it keeps crashing, i think its because i've edited the json files , the default npc spawn was 0.10 but i changed to 10.10. And i've disabled a mod in json files, but this dont crashed the game (i had another npc when i disabled the mod of "no_npc_food".

my computer is windows 10 , and my game version is 0.C-37320-g2a8c342, and the mod that i have in the world is:
-Dark days ahead
-filthy clothing
-Bens GF recipes
-Craftable gun pack
-Extended Realistic guns
-medieval and historic content 
-More survival tools 
-mythological replicas
-makeshift items mod
-npc traits 
-Boats
-Folding parts pack
-vehicle addition pack
-tanks and other vehicles
-no monsters
-sleep deprivation

![image](https://user-images.githubusercontent.com/47425222/52424616-82160480-2ae1-11e9-995b-7bb776b315ae.png)

![image](https://user-images.githubusercontent.com/47425222/52424651-922de400-2ae1-11e9-988b-eaeb745488f7.png)

![image](https://user-images.githubusercontent.com/47425222/52424756-c4d7dc80-2ae1-11e9-9993-96199b6a49a5.png)

if you need the save game , the download is in comment section bellow

**Comment by MigmaDiscordia** [comment]
please, if possible, try to resolve quickly as possible, cause i'm very anxious to play the game but i cant

**Comment by AMurkin** [comment]
That map file is private. Publish it to everyone.

**Comment by MigmaDiscordia** [comment]
now the file is public right?

**Comment by AMurkin** [comment]
I can open that link and probably download files (it's started at least).

**Comment by MigmaDiscordia** [comment]
you did it?

**Comment by AMurkin** [comment]
I did.
Now it's here, to save on waiting if someone want to test it.
[Jakin-20190209T182945Z-001.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2848128/Jakin-20190209T182945Z-001.zip)

**Comment by MigmaDiscordia** [comment]
oh thanks very much

**Comment by AMurkin** [comment]
It's NPC's pathfinding in dense forest probably.

Paused debugger after taking one step near npc:
```
#0  0x00005555558fbb7e in divide (v=v@entry=425, m=m@entry=180, r=r@entry=@0x7fffffffd60c: 425) at src/coordinate_conversions.cpp:16
#1  0x00005555558fbc36 in omt_to_om_remain (x=@0x7fffffffd60c: 425, y=@0x7fffffffd608: 164) at src/coordinate_conversions.cpp:38
#2  0x0000555555d2cd4d in overmapbuffer::get_om_global (this=0x555556488940 <overmap_buffer>, x=@0x7fffffffd60c: 425, x@entry=@0x7fffffffd60c: <optimized out>, y=@0x7fffffffd608: 164, y@entry=@0x7fffffffd608: <optimized out>) at src/overmapbuffer.cpp:255
#3  0x0000555555d2dd82 in overmapbuffer::check_ot_type (this=<optimized out>, type="s_pharm", x=<optimized out>, y=<optimized out>, z=7) at src/overmapbuffer.cpp:697
#4  0x0000555555d2e19a in overmapbuffer::is_findable_location (this=this@entry=0x555556488940 <overmap_buffer>, location=..., type="s_pharm", must_be_seen=must_be_seen@entry=false, allow_subtype_matches=allow_subtype_matches@entry=false, existing_overmaps_only=existing_overmaps_only@entry=false, om_special=...) at src/overmapbuffer.cpp:727
#5  0x0000555555d2e327 in overmapbuffer::find_closest (this=0x555556488940 <overmap_buffer>, origin=..., type="s_pharm", radius=radius@entry=0, must_be_seen=must_be_seen@entry=false, allow_subtype_matches=allow_subtype_matches@entry=false, existing_overmaps_only=false, om_special=...) at src/overmapbuffer.cpp:794
#6  0x0000555555c9b733 in npc::set_destination (this=this@entry=0x555593ee5ff0) at src/npcmove.cpp:3037
#7  0x0000555555c9be0a in npc::long_term_goal_action (this=0x555593ee5ff0) at src/npcmove.cpp:1301
#8  0x0000555555ca6f9f in npc::move (this=this@entry=0x555593ee5ff0) at src/npcmove.cpp:423
#9  0x00005555559bb701 in game::monmove (this=this@entry=0x555557d88b50) at src/game.cpp:4779
#10 0x00005555559c33d6 in game::do_turn (this=0x555557d88b50) at src/game.cpp:1639
#11 0x00005555557eb457 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:673
```

**Comment by MigmaDiscordia** [comment]
yeah, now i updated the game with the game launcher, the game don't crash anymore, BUT become very very very very VERY laggy

**Comment by ZhilkinSerg** [comment]
Probably fixed right now.
