### ISSUE TITLE
mixed up effects

### ISSUE THREAD

**Issue by nsklaus** [CleverRaven/Cataclysm-DDA#28134]
**Describe the bug**  
drinking alcohol create unrelated effects.
player info screen make it look like i took various drugs.

**To Reproduce**  
1.  drink alcohol
2. check player info and see effects: painkiller, depressants, tipsy

**Expected behavior**  
drinking alcohol should result in 1 effect: drunk, or tipsy
i didn't take neither painkillers nor depressants pills, 
so these effects shouldn't appear. 

**Additional info**
as i suspected it's the same with other substances, 
for example taking a xanax result in two effects:
took_xanax and depressants.
those two are the same, no need to have duplicate effects listed.
choose one of them and be done with it.

**Versions and configuration(please complete the following information):**
 - OS: [Ubuntu 18.10]
 - Game Version [0.C-37273-gdf01e1f52a-dirty]
 - Graphics version [Tiles]
 - Mods loaded [  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "generic_guns",
  "more_locations",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "DP_AMAZING_CHEST_INDICATORS",
  "DP_REMIX_INDICATORS",
  "DP_XOTTO_INDICATORS",
  "more_classes_scenarios",
  "manualbionicinstall",
  "safeautodoc",
  "no_olg_guns"
]

**Comment by sneeze-attack** [comment]
I personally do not see this as an issue. Drinking alcohol should have multiple effects as they are not duplicate effects. Basically, if a drug has more than one effect on the body, why shouldn't it be represented?

**Comment by Photoloss** [comment]
As long as it is used consistently I prefer the multi-effect approach. That way if there is a group of medicines with similar effects and no catastrophic interactions it is easy to see the cumulative effect on your character's performance. Note alcohol is an *incredibly bad* example here but similar opiates might be "safe" in game terms as long as you keep the total dosage in check.

The "stim" and "depressant" effects are also applied by various foods as well as mutagen. According to [this](https://www.drinkaware.co.uk/alcohol-facts/health-effects-of-alcohol/effects-on-the-body/alcohol-and-energy-drinks/) the awareness-altering properties of energy drinks and alcohol *can* cancel each other out so the generic effect you see is only displaying what the game *should* be doing behind the scenes anyway.

How much of this information should be available without the self-aware trait and to what extent the !FUN! drug interactions are coded into the game is another matter but different sources of cramps, paralysis and so on would likely stack up as well.

**Comment by KorGgenT** [comment]
alcohol is a depressant. it also kills pain. why do you think those cowboys in westerns drink whisky when they have an injury?

**Comment by Treah** [comment]
https://en.wikipedia.org/wiki/Alcohol_(drug)

> Among other effects, alcohol produces a mood lift and euphoria, decreased anxiety, increased sociability, sedation, impairment of cognitive, memory, motor, and sensory function, and generalized depression of central nervous system function.

>     2\. painkiller, depressants, tipsy

Painkiller: generalized depression of central nervous system function
Depressants: sedation, impairment of cognitive, memory, motor, and sensory function
Tipsy: mood lift and euphoria

Google search of 2 min.

**Comment by nsklaus** [comment]
ah the experts, so nice to see you, 
how many phd's you monkeys have today ?
now, i have grave news, you've got to be strong, 
i came without peanuts today, but, no, no, don't be so sad
if you're nice and behave maybe i'll bring you some next time.

**Comment by Treah** [comment]
I edited my last line in there cause I think it can bee seen as condescending. 

However the info I found was on wikipeida and explains the effects we see in game tho so I think that's valid even if I am not a doctor by trade. Wikipedia however is not accepted as a reference in any academic papers so if a medical source is needed I can provide it? 

I am sorry if my response was seen as disrespectful in any way @nsklaus

**Comment by I-am-Erk** [comment]
I don't think citing wikipedia qualifies one as an expert... one doesn't need to be an expert to understand this.

I do agree that xanax shouldn't give a "took xanax" effect. The one we're looking for there is maybe "anti-anxiety", which should also be an alcohol effect.

(interestingly, xanax and alcohol work in extremely similar pathways, and benzos like xanax are the primary treatment for alcohol withdrawal)

**Comment by nsklaus** [comment]
this is the moment i'd like to say, 
if somehow this project decide to use a panel system even vaguely similar to the one i offered, 
you'll be able to remember me fondly on every game you do and you'll be thinking: 
" ah nsklaus he was great, how right he were, he was the man,
i'm so happy to have a bit of him in front of my face on my every play. "
that's how great i am guys.
now it would also good time to make a little song about me, and keep it in your heart, 
in the difficult moments in life you'll have  the thought of me to comfort you, 
while sliding panels a tear in your eye ...
 " aaah nsklaus..thank you so much for Everything you enlightened our lives ".
i know.

**Comment by I-am-Erk** [comment]
I think it's pretty weird you're upset enough about this to leave. Most or all of the people in this thread have loudly defended your right to work on the game to your detractors at some point or another, and you've done some neat stuff. However, if it's going to upset you to have a feature explained or to have people disagree with the way you want to do something, I don't think it's really going to work out. That sort of stuff happens pretty much constantly on a collaboration project.

**Comment by nsklaus** [comment]
sing the song it will sooth your angst. you will know i am right. i always am.

**Comment by Night-Pryanik** [comment]
@nsklaus please stop spamming.

**Comment by SirPendrak** [comment]
Somebody please call Riot Control Bot, we have a crazed individual here

**Comment by kevingranade** [comment]
Seperating out the various sub-components of inebriation is a design choice, this is working as intended.

**Comment by EldritchHorror** [comment]
You're acting like a total manchild, grow up.

Nobody cares about you past the point everything you try to improve ends up fucked over and broken. You're like the speed weed guy and all we will remember of you is the mild inconvenience your lack of competence gave us.
