### ISSUE TITLE
Shooting over objects destroys objects randomly.

### ISSUE THREAD

**Issue by CptCodpiece** [CleverRaven/Cataclysm-DDA#28139]
While shooting down a fungal spire, I noticed it dropped some seeds and gelatin. After gunning down the rest of the wall, I went in to gather my loot, but the loot vanished somehow.  After creating a test world, I found that on occasion, if you shoot arrows, bullets, whatever overtop of objects on the ground, sometimes the objects on the ground will get hit as well just by virtue of passing over the square with the objects upon it.  This doesn't seem to stop or reduce damage to said projectile in any fashion.

Make a new world, wish in an RM 614 LMG, a drum mag and some ammo, wish skills to 10 (so you actually hit where you're aiming OVER the objects), wish 30 copies of trash objects, drop them in a field around you, aim and full auto fire way over the objects so they can't get hit. Watch as objects on the ground magically disappear just because the bullet went through their tile.

**Expected behavior**  
When shooting over objects that lay on the ground, the objects on the ground should not be randomly destroyed, unless the projectile lands within that square for some reason (directly targeting, hit a monster you weren't aiming at, botched skill roll, etc.) If this is working as intended, then bullets that hit objects upon the ground should likely do some sort of damage check of object vs. bullet and reduce bullet damage or block the shot entirely within sanity. (Power armor suit should stop small arms gunfire. Glass tube should not.)

**Screenshots**  
Aiming over a pile of Under The Hoods
![image](https://user-images.githubusercontent.com/47262327/52510922-f1682300-2bcb-11e9-8572-65dcf2888a42.png)

The aftermath.
![image](https://user-images.githubusercontent.com/47262327/52510941-080e7a00-2bcc-11e9-8828-a1054c9c640d.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-37361-g792b3cb
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Vehicle Additions Pack, DinoMod, NPC traits, Mutant NPCs, Beta National Guard Camp, More Buildings, More Locations, Filthy Clothing, Tanks and Other Vehicles, Urban Development, Tall Buildings, Stats Through Skills

**Additional context**  
This might just be intentional that bullets strike random objects laying on the ground as they sail overhead and it's actually working as intended?  Just this seemed really fishy and this is partway me getting upset that I lost a bunch of fungal seeds and marloss gelatin, 

Also, within that pile, there's a few suits of wished in heavy power armor/ power armor that did not get destroyed, so one assumes there's some level of sanity check on objects destroyed via this fashion.

**Comment by DSeyka** [comment]
Can confirm. Also, I'm pretty sure that bullets never hit the ground, ever. Even if you aim at the tile next to you, they just go off-screen and stop existing outside of reality bubble.  

Arrows and throwable objects just stop in mid-flight, but they never damage whatever is underneath. The code only checks if they hit the intended target, and if not, it teleports them to the ground somewhere nearby.  

If anyone wants to try and get this fixed, please make sure that bullets can still hit furniture (as opposite to objects), and damage it in the process. This actually seem to happen now, and is likely intended.

**Comment by Treah** [comment]
This is actually working as intended since there is no concept of height when it comes to bullets. Someone else here had a similar problem with turrets damaging crops when it was placed int he middle and it was shooting at things.

**Comment by I-am-Erk** [comment]
Could it be refined to make the hit chance work based on the volume of the object, and perhaps reduce the bullet damage based on the object's mass?

**Comment by CptCodpiece** [comment]
I'll go ahead and close the issue since this is intended behavior then. Thanks for letting me know!
