### ISSUE TITLE
Vehicles with combustion engines not producing smoke

### ISSUE THREAD

**Issue by davidpwbrown** [CleverRaven/Cataclysm-DDA#28159]
**Describe the bug**  
Vehicles don't produce smoke currently.

**To Reproduce**  
1. debug in a vehicle with a combustion engine, drive it, no smoke is produced.

**Expected behavior**  
Combustion engines should produce smoke like they used to.

**Versions and configuration(please complete the following information):**
 - OS: Lubuntu 18.10
 - Game Version fresh master
 - Graphics version tiles
 - Mods loaded dda

**Additional context**  
May be tangentially related to #28079 
in that conditional checking for engine_type uses ammo_current instead of fuel_current, and dosnt return expected results.
spew_smoke checks fuel_type too, so it may be all related to that, not sure when smoke stopped being produced.
Was asked to @mlangsdorf  with this.

**Comment by DSeyka** [comment]
Might be related, when driving a vehicle with a leaking tank it no longer seems to leave puddles of gasoline behind it like it used to.

**Comment by davidpwbrown** [comment]
Yeah definitely sounds like the same root cause.

**Comment by Shodan14** [comment]
I kind of remember trying to use a in-door generator with an exhaust outdoors, but all the smoke still came out next to the engine. Not sure if that's related.

**Comment by kevingranade** [comment]
Fixed by #28222
