### ISSUE TITLE
Force unarmed and non-conductive objects

### ISSUE THREAD

**Issue by mding9** [CleverRaven/Cataclysm-DDA#28153]
When using the force unarmed style or a martial art that forces unarmed attacks, you can wield non-conductive weapons to safely use unarmed attacks on shocker-type zombies.

To reproduce the behavior:
1. Spawn a shocker zombie
2. Pick a style that forces unarmed attacks.
3. Wield something conductive or don't wield anything at all.
4. Attack the shocker zombie, and it will hurt you.
5. Wield something non-conductive.
6. You can safely attack the shocker zombie without receiving the electric shock.

If you are attacking an electrified opponent with your limbs, you would get shocked either way.

 - OS: [Windows 10]
 - Game Version: [0.C-37390-geef02ee (tiles)]
 - Mods loaded [dda]

**Comment by kevingranade** [comment]
Fixed by #28236
