### ISSUE TITLE
Factor in NPC's speech skill when reading to an illiterate player.

### ISSUE THREAD

**Issue by WilliamtheCardboardBox** [CleverRaven/Cataclysm-DDA#28151]
**Is your feature request related to a problem? Please describe.**  
Currently NPCs can read books to player characters which almost nullifies the illiterate trait if you tuck the NPC away and the NPC has sufficiently high intellect to read the books. 

**Describe the solution you'd like**  
Raw solution I would like: it needs more checks and balances to make illiterate worth six points otherwise it needs a point reduction. How I think it could be balanced if you don't want to reduce the point cost: factor in the NPC's speech skill into reading books to the player to either speed up, speech 10 for example, or slow down, speech 0, the reading of books to illiterate players. Ultimately, there needs to be more against the RNGness of it so adding an extra factor against it would at least help it a little bit and in my opinion factoring in speech as a multiplier would not ruin the trait or gameplay of illiterate players.

**Describe alternatives you've considered**  
N/A

**Additional context**  
Getting an NPC with high intellect basically nullifies illiterate and presents only a minor inconvenience to the player instead of actually being a pain in the neck like it's supposed to be.

**What improvements would this make to gameplay?** 
Illiterate is currently worth six points while imperceptive healer is worth eight points. So, a long term and debilitating trait such as imperceptive healer is just about on par with the illiterate trait. Makes sense, right? 1/10 the healing is equal to being unable to read books. Well, it sounds good on paper; however, in real gameplay a random NPC with, often dramatically, randomized stats can solve the six point negative called illiterate. Sadly there's no way for an NPC to fix imperceptive healer... yet!

Edit: removed some of the original since there was already an issue in 2015 for it. 
Edit two: added a stronger argument for my suggestion. Edited other things as well.
Also, working on an argument to add a "geneticist" NPC that can cure the player of unfavorable starting traits and has a 3/4 chance of spawning at evac shelters. <- This is a joke. 

My apologies for the scatterbrained feeling this has to it. I tried to do my best to minimize that. 
And forgive my attempted (horribly attempted) sarcasm also it is not against anybody as I love all of you guys so forgive me.

**Comment by OrenAudeles** [comment]
This would also bring some balance to the Player's capability to read to the NPC to train them up through book-lurnin

**Comment by DracoGriffin** [comment]
#11906

**Comment by kevingranade** [comment]
Need a stronger argument for why this is necessary and how the fix improves things, you dont seem to have a grasp of how it works right now.  Factoring in npc skills doesn't seem to meaningfully change the situation.

**Comment by Zombiemanpig** [comment]
Didn't even know you could do that, makes me want to play as a medieval knave now.

**Comment by Asmageddon** [comment]
@kevingranade I think the premise is that you should need more than just finding any NPC to be able to learn from books effectively.

I'm not sure if the proposed solution would be effective enough, though. 

Sheesh there's so many individual issues in this huge game.
