### ISSUE TITLE
Make monster evolution dependent on starting season.

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#28158]
**Is your feature request related to a problem? Please describe.**  
Monster evolution has its starting point in spring, regardless of chosen starting season. This makes starting in any other season than spring virtually impossible due to difficulty.

**Describe the solution you'd like**  
To solve this problem, monster evolution can start with the chosen starting season that was selected during world creation.

**Additional context**  
Wanted to play a game with an eternal winter season, but it's not possible due to extremely high evolved monsters right from day 1. Sadness ensured, quickly followed by a gruesome death.

**Comment by Uviray** [comment]
It is harder, but definitely not impossible to survive. I almost always start in autumn or winter exactly for this reason, and I like it this way. My characters are fine. It's also the whole point of 'Next Summer' etc. scenarios.

**Comment by kevingranade** [comment]
The fact that you can't play eternal winter without wrecking evolution is a major problem.

**Comment by Uviray** [comment]
Well, that is also true. I think that player should be able to set when evolution starts during worldgen.

**Comment by Bulletfang** [comment]
Exactly my thought.

**Comment by Night-Pryanik** [comment]
With the ability to set the starting date with or without monsters evolving added in #28841, I guess this issue can be closed?
