### ISSUE TITLE
Add eyes to character creation, and make player and NPCs close eyes when they sleep. 

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#28167]
Right now, with implementation of skin and hair all characters still cant change eye color. 
I want to see eyes implemented, and also suggesting a feature, what will remove character eyes when they sleep. I will edit skin sprites so they not gonna have holes for eyes when they disapear, and it will look like their eyes are closed when eyes sprite disappears.
But one set of eyes in customization menu should always be toggled (skin and hair too, i think), or else character always gonna look like he closed his eyes.

Latter i will upload some edited screenshots to represent more accurate what i want.

**Comment by Fris0uman** [comment]
For the close eye while asleep part there is already something to do that (unless I missunderstood what you're saying).
[Sleeping Toon](https://imgur.com/a/azBmagL)
I don't know how it's implemented though, but it's possible.

**Comment by SomeDeadGuy** [comment]
No, it is just eyelids painted over the face. It will not work for other skin collors. Imagine you being black, but having white eyelids :)
What i want is having skin with closed eyes already on it. When eyes gonna be added to the character above skin, so you will not see closed eyes. When character tries to sleep hi closes his eyes and eye sprite disappearing from the character, revealing closed eyes already drawn on the skin.
