### ISSUE TITLE
two different map symbol for the same kind of place

### ISSUE THREAD

**Issue by nsklaus** [CleverRaven/Cataclysm-DDA#28163]
**Describe the bug**  
gun stores on map have different symbols.
one is "g", the other is "^"

**To Reproduce**  
1. start a game find a town with two gun stores :)
please look at the screenshots.

**Expected behavior**  
same kind of place should have same symbols on map.

**Screenshots**  
![screenshot_20190211_000555](https://user-images.githubusercontent.com/6810861/52541076-5456e700-2d91-11e9-8691-46d85334fa12.png)
![screenshot_20190211_000559](https://user-images.githubusercontent.com/6810861/52541077-5456e700-2d91-11e9-9490-9766c5538ee1.png)

**Versions and configuration(please complete the following information):**
 - OS: [Ubuntu 18.10]
 - Game Version [0.C-37393-g4bf228ddcc-dirty]
 - Graphics version [Tiles]
 - Mods loaded [
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "generic_guns",
  "more_locations",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "DP_AMAZING_CHEST_INDICATORS",
  "DP_REMIX_INDICATORS",
  "DP_XOTTO_INDICATORS",
  "more_classes_scenarios",
  "manualbionicinstall",
  "safeautodoc",
  "no_olg_guns"
]

**Comment by Leviathan21** [comment]
you have a mod that adds additional buildings that come with their markings

**Comment by nsklaus** [comment]
that mod should be put aside until it resolve the problem then. because we have a mod that is accepted in the game tree but introduce inconsistency to the game. either this mode should replace all symbols for gun store, or don't, but not doing it half way. having both symbol being used in the same time is not a good thing.

**Comment by kevingranade** [comment]
The mods are not curated, they are "use at your own risk".  If they are actively broken and not being updated they can be considered for removal, but a style in consistency does not meet that bar.
