### ISSUE TITLE
Crafted hard cheese lacks calories

### ISSUE THREAD

**Issue by Photoloss** [CleverRaven/Cataclysm-DDA#28161]
**Describe the bug**  
Looted/spawned hard cheese has ~3.8kcal/g (or 130 per "portion") in line with e.g. [parmesan](https://en.wikipedia.org/wiki/Parmigiano-Reggiano). Crafted from curdled milk however it only has 0.76kcal/g (26 per portion).

**To Reproduce**  
1. Spawn in some hard cheese via debug menu
2. Spawn in some curdled milk and craft it into hard cheese
3. Compare calorie amounts

**Expected behavior**  
Crafted hard cheese should have close to identical calorie amounts. The portion yield of the recipe might need to be adjusted as the current chain is 15 milk->18 curdling->18 curdled->21 hard cheese while in real life the milk is condensed down a lot.

**Version:**
0.C-37270-g86ec372

**Additional context**  
The curdling milk was displayed as "rotten" in the fermenting vat. This does not currently seem to change the calorie content of the product but may become an issue.

**Comment by austin9240** [comment]
Looking into effects

**Comment by KorGgenT** [comment]
> Looking into effects

wouldn't be related to effects. if curdled milk has no kcal, hard cheese just needs the NUTRIENT_OVERRIDE flag to override the recipe

**Comment by KorGgenT** [comment]
> **Describe the bug**
> Looted/spawned hard cheese has ~3.8kcal/g (or 130 per "portion") in line with e.g. [parmesan](https://en.wikipedia.org/wiki/Parmigiano-Reggiano). Crafted from curdled milk however it only has 0.76kcal/g (26 per portion).
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Spawn in some hard cheese via debug menu
> 2. Spawn in some curdled milk and craft it into hard cheese
> 3. Compare calorie amounts
> 
> **Expected behavior**
> Crafted hard cheese should have close to identical calorie amounts. The portion yield of the recipe might need to be adjusted as the current chain is 15 milk->18 curdling->18 curdled->21 hard cheese while in real life the milk is condensed down a lot.
> 
> **Version:**
> 0.C-37270-g86ec372
> 
> **Additional context**
> The curdling milk was displayed as "rotten" in the fermenting vat. This does not currently seem to change the calorie content of the product but may become an issue.

that would be because food recipes inherit kcal from input items.

**Comment by austin9240** [comment]
Fixed
