### ISSUE TITLE
Remove high quality lens from smart phones

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#28175]
**Is your feature request related to a problem? Please describe.**  
Smart phones have becomes quite common due to new zombie drop balance, this makes sense. But Smart phones contains high quality lens that can be use to craft survivor telescope and some gun mods.
Can someone really use the lens from a phone to make a scope ?
**Describe the solution you'd like**  
Remove the lens from the disassemble recipe of the smart phone.
Or make it a small lens that will be added to other appropriate recipes.

**Describe alternatives you've considered**  
Change nothing, this doesn't break game balance, it's just a bit weird.
**Additional context**  
I'm willing to do the json edit, but I wanted to ask before what people think of this.

**Comment by kevingranade** [comment]
Yea, it's a bit weird that a tiny smartphone lens is being used for a telescope.

**Comment by SirPendrak** [comment]
But maybe they might be suitable for laser sights? Idk

**Comment by Fris0uman** [comment]
We could replace high quality lens with small lens and make the laser sight use (require ?) small lens.

**Comment by Astrobia** [comment]
Should a telescope then use a small and a large lens? And should cameras give both?

**Comment by Fris0uman** [comment]
> Should a telescope then use a small and a large lens? And should cameras give both?

It's more a question of Diverging and Converging lenses that of lens size I think, we can admit that both type of lens are abstracted inside `High quality lens`

**Comment by Photoloss** [comment]
> It's more a question of Diverging and Converging lenses that of lens size I think, we can admit that both type of lens are abstracted inside `High quality lens`

You can build a telescope [as long as you have *one* convergent lens](https://en.wikipedia.org/wiki/Refracting_telescope#Refracting_telescope_designs) and the smartphone ones definitely are of sufficient quality. At the level the game treats it really *does* boil down to size for once as a larger objective lens collects more light, focal distance would be more important for controlling physical size and field of view though.

It should also be noted the term "single-lens" reflex camera refers to using the same primary optics for both the actual photography and rangefinding, a single modern camera contains more than enough individual lenses to build a crude telescope unless the loss is meant to reflect searching for a decent match in focal distance or other detailed properties.

**Comment by Fris0uman** [comment]
So are smart phone lens big enough to build the survivor telescope ?

**Comment by Photoloss** [comment]
> So are smart phone lens big enough to build the survivor telescope ?

Big enough for the eyepiece definitely. For the objective you'd get a *very* crummy pirate-style tube with a terrible FoV but the image quality could be pretty good. The way these items function in-game right now would not be possible with such an item but a stationary "survey area" action would yield the same effective range while taking vastly more time to cover the entire area.

So basically split off a "small hq lens" item and the current telescope item requires one full-size lens and one which can be either full-size *or* small. [Binoculars](https://en.wikipedia.org/wiki/Binoculars) should yield two full-size lenses and either another two or two small ones at minimum, though I am not sure what we would currently use them for besides weapon scopes.

**Comment by Asmageddon** [comment]
What's even worse is that there's two Security Camera(vehicle part) recipes... one takes 4 high-quality lens... the other takes 2 cellphones instead, takes less time, and has lower skill requirements.

**Comment by Photoloss** [comment]
> What's even worse is that there's two Security Camera(vehicle part) recipes... one takes 4 high-quality lens... the other takes 2 cellphones instead, takes less time, and has lower skill requirements.

I would say that's actually pretty good if they're **smart**phones. Jury-rigging a functional digital camera from salvaged components is much harder than sticking two semi-functional phones in an actuated rig and you could even calculate parallaxes or simple image recognition on the phone itself. The two non-"pro" cameras seem a little more iffy since the recipe does not include any external processor/DAQ boards.

**Comment by Hirmuolio** [comment]
Phone lense could maybe work for lasers. But it is definitely too small for any kind of eye piece.

Just take your phone and look at the camera. The lense is that <1 mm circle in the middle.

**Comment by Photoloss** [comment]
> Phone lense could maybe work for lasers. But it is definitely too small for any kind of telescope or binocular recipe.
> 
> Just take your phone and look at the camera. The lense is that <1 mm circle in the middle.

A *[camera obscura](https://en.wikipedia.org/wiki/Camera_obscura)* uses a literal pinprick as its aperture and is perfectly fine for direct viewing. Not exactly 4k HD and you would usually add a paper screen to the Pringles can version but it still *works*.

"Realistically" you'd need a lot of testing and decent knowledge of ray optics to actually build a functioning telescope. Light yield and/or field of view will suffer greatly.

**Comment by Fris0uman** [comment]
>So basically split off a "small hq lens" item and the current telescope item requires one full-size lens and one which can be either full-size _or_ small. [Binoculars](https://en.wikipedia.org/wiki/Binoculars) should yield two full-size lenses and either another two or two small ones at minimum, though I am not sure what we would currently use them for besides weapon scopes.

This sounds like a very good idea, it solves the oddity of making telescope entierly from smart phones without making things needlessy complicated.

**Comment by ZhilkinSerg** [comment]
Fixed with #28183.
