### ISSUE TITLE
"Trash"

### ISSUE THREAD

**Issue by WilliamtheCardboardBox** [CleverRaven/Cataclysm-DDA#28171]
**Is your feature request related to a problem? Please describe.**  
A new scenario set in the lab. This would add a special scenario specific room "Trash management."

**Describe the solution you'd like**  
**Scenario description** >credit of I-am-erk< - "'Trash' challenge start. You were a xedra experiment being shipped to the incinerator, when the facility lost power. You woke up groggy from the sedatives they'd given you, in a sealed crate. It took hours, maybe days, but in desperation you broke the crate open and are now down in the trash management level, dehydrated and starving but alive."                               
**In-game description:** "You were a failed experiment moments away from being incinerated when the power mysteriously went out. Now, days later, you finally escape the container that trapped you for so long. As you're trying to find your way out of this god-forsaken place you find out you aren't alone."

**Describe alternatives you've considered**  
N/A

**Additional context**  
**The idea of it** The player spawns in a scenario specific room "Trash management level" as a failed experiment which was deemed worthy of termination by those who created you. The idea of this is a sort of a Really Bad Day lab scenario. The player would have access to more mutations than other lab starts to balance the difficulty of escaping this scenario given that they have to escape trash management *alongside* the lab above them. This would also allow people to gamble for more specific mutations in a Really Bad Day style lab start.  

**The details** The player starts starving and dehydrated with no items except the medical gown on their back. Semi-random items can be found in this area including containers which could house anything from a mi-go to a failed experiment like you. There's also various *things* lurking around which don't sound too nice.

**"But doesn't starting in a lab nullify starting with no items?"** There shouldn't be any items for emp grenades or electrohacks just laying around the room as any items like these should be inside containers or perhaps on some special monsters. The scientists would obviously have devices like computers and laptops in line to be destroyed and whatnot so these can be found in containers similar to what the player started in. Ultimately the player needs to see it as a gamble opening these containers which could either be a great find or the possible end of their character.

This still feels like it needs some additions to make it truly worthy of a Really Bad Day lab start and so this page is absolutely open to suggestions. Also, someone mentioned that I need to leave this idea very open since I'm not the one coding this and I agree, but if it is too specific then feel free to make changes to it to make it possible or more playable. Personally I feel like it's already a very open suggestion.

**Comment by Leviathan21** [comment]
the profession name should be like xedra project defect

**Comment by Zombiemanpig** [comment]
Something like this is moddable?

**Comment by WilliamtheCardboardBox** [comment]
> the profession name should be like xedra project defect

Yeah it does need a profession name.

**Comment by Zireael07** [comment]
Can you change the issue name? It's very very unclear...

**Comment by Marrim** [comment]
I suggest a mandatory bad mutation trait, similar to how Challenge-Abandoned (hospital start) mandates Frail.

**Comment by paulenka-aleh** [comment]
First of all there must be a reason why they abandoned you, e.g. failed bionics instaplations and forced negative mutations like "Unstable" or worse. During experiments on your body it might have been damaged, infected, irradiated and you might have an addition on painkillers. To make the day bad put nothing fancy on those containers, in any case it's a scenario start so unlucky container would simply mean a reroll. Finally to make it really bad make this lab ice (so all food is frozen and hypotermia is great risk given your injures)

I also don't think this room should be unique and scenario-specific. Why wouldn't all labs have it randomly?
