### ISSUE TITLE
NPC mutations visibility bugged

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#28196]
**Describe the bug**  
Mutations are visible to low PER characters, but invisible to high PER characters.

**To Reproduce**  
1. Spawn mutant NPCS
2. Alter your PC's PER in the debug menu or do things like move close/far, turn lights off/on, etc.
3. Look at Mutant NPCs to see if things like fur or spots show up in description.

**Expected behavior**  
The opposite of that. 

**Versions and configuration(please complete the following information):**
 - OS: Windows
 - Game Version 0.C- 8475
 - Graphics version Tiles
 - Mods loaded Mutant NPCs

**Additional context**  
This is for the look command or mouseover.  When you go to the extended description, the traits don't seem to be listed at all.

**Comment by mlangsdorf** [comment]
Closing this because the cap to see mutations is fixed at 0.
