### ISSUE TITLE
cooking organ parts takes way too long

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#28205]
**Describe the bug**  
Cooking 1lb liver IRL takes about 5 minutes
Cooking 1lb liver in game takes 6 hours
If you were including marinating/soaking time, I MIGHT be able to believe 1-2h, but if that's the case it should greatly benefit from batch cooking (setup time for marinating would only add a couple minutes, and they can all soak simultaneously), and it doesn't take water or anything so I doubt soaking is why it takes so long.

**To Reproduce**  
spawn some raw liver
check the cooking time

**Expected behavior**  
cooking time should be about 5 minutes

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: windows
 - Game Version: 0.C-37406-g8d3edd7
 - Graphics version: Tiles
 - Mods loaded: lots, including some of the backwoods mods

**Additional context**  
Liver and onions: https://www.lakegenevacountrymeats.com/recipes/beef-liver-and-onions
liver and onions: https://mommyshomecooking.com/venezuelan-liver-and-onions/

Related: Cooked Meat should be about the same time, currently in game it's 15m with 67% savings at >5 units (should probably be closer to 70% at >1 unit since that's really just time to heat the pan) but it's at least somewhat reasonable.

**Comment by Xpyder** [comment]
Also the recipes linked were both for 1-2 pounds of liver.  Which would be 8 in game units.
so the actual time comparison would be
IRL: 5 minutes
in game: 6 hours

**Comment by Xpyder** [comment]
The recipies linked were all for 1-2 lbs of liver
1lb liver in game is about 8 units

**Comment by Xpyder** [comment]
I did the math and if the game burns 2,000 kcal/day then you literally burn as many calories cooking the liver as you get by eating it currently

**Comment by junkyjb** [comment]
Cooked liver also calls for 100 charges of cooker/smoker/mess kit/integrated-toolset instead of the 7 charges for normal cooked meat, which seems odd.

**Comment by capSAR273** [comment]
The liver recipe is inside '''offal_dishes.json''' , which copies the recipe for cooked brains, giving it the 45000 units of time to cook and the 100 units of surface heat required. If we change this, we might also have to adjust similar smaller meat dishes that copy the brains one. I'd imagine kidneys and a few others take less time to cook than a whole brain.

**Comment by Xpyder** [comment]
cooking brains takes like 15 minutes, and most of that is boiling in water.  And 100 heat seems like way to much.

Maybe we should collect a list of recipes affected, then start by adjusting brains and see if the others fall in line?

**Comment by Xpyder** [comment]
Cooking brains reference: 
https://oureverydaylife.com/438525-how-to-cook-beef-brains.html
http://foragerchef.com/how-to-cook-brains/
https://dentistvschef.wordpress.com/tag/how-to-cook-beef-brain-recipe/

**Comment by Xpyder** [comment]
If someone gives me names and numbers, I'll prototype changes if I get some time
