### ISSUE TITLE
Zombie Dogs are able to be skinned, produce no hides

### ISSUE THREAD

**Issue by garnik-ananikyan** [CleverRaven/Cataclysm-DDA#28209]
Issue:
Skinning zombie dogs and rot-weilers produces no skins/hides/furs at all despite being able to skin them through the butchery menu and afterwards even getting messages about successful skinning. After finishing skinning process corpse turns into a skinned one, you can't try to skin again ("corpse is already skinned"), upon further "full butchery" you are getting just fat, meat and butchery refuse, as you normally would, no hide to be seen.

To reproduce:
Make a character, raise survival skill to, for example, 6 level, give character necessary tools (for example, butchering knife and x-octo knife), kill a zombie dog in your nearest town, choose "Skin a corpse" in the butchery menu.

Expected:
Either to get skins from those corpses, OR not being able to skin in the first place due to lack of skin, OR at least not getting a successful messages upon skinning that produces nothing.

WIN10
0.C-37442-gd597d68
Tiles
Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, DDA: Lua, Safe Autodoc, Manual Bionic Installation, Prevent Zombie Revivication, (DP_RP) Xotto Indicators, Alternative Map Key, Classes and Scenarios Mod, Medieval and Historic Content

**Comment by zacklucky7** [comment]
I've noticed many monsters can be skinned and produce successful messages despite giving no hide. I've had it happen with the fish in ponds, a giant rattlesnake (which I'm sure had hides before), a zombie, and a giant fly.

**Comment by KorGgenT** [comment]
every monster can be "skinned".
this doesn't mean you're going to get any usable resources from it.
It's the same way you can field dress anything, but zombies don't give you anything.
