### ISSUE TITLE
travel_to doesn't work with shelves

### ISSUE THREAD

**Issue by nsklaus** [CleverRaven/Cataclysm-DDA#28200]
**Describe the bug**  
player cannot "travel_to" an item placed on a shelf.

**To Reproduce**  
1. put an item on a shelf
2. move away a few meters, open list_items() ui
3. select the item on the shelf and try to perform a normal "travel_to" towards it.

**Expected behavior**  
like for other items, player should be able to "travel_to", and place himself in front of the item. 
please note that i'm saying:  "in front of" and not  "above", or "on top of" the item.

player shouldn't have a problem to move (travel_to) in front of a shelf.
there is nothing blocking the way towards there. 
also, you can see with other working cases that the player never tries to travel_to and place himself "above" or "on top" of the item when "traveling_to" but rather it always places himself in "front of" the item, which is good. 
since shelfs are not passable if player tried to do so, that would be a good reason,
but, this here, is not the case, player never attempt to pass through or move on top of the shelf.
as you can see with the other (working) travel_to cases, player always just place himself in front of it.  so what's stopping player to move in front of the shelf using travel_to function ?

**additional info**
i noticed this while working on a possible new feature that would allow the player to use the list_items() ui, to select some items from those being listed, and initiate a "now go pick them up" automated action . i was wondering why he would not go there ?

**Screenshots**  
![screenshot_20190214_170455](https://user-images.githubusercontent.com/6810861/52800047-4815a700-307b-11e9-86b2-42f4f9bac7f2.png)
![screenshot_20190214_170509](https://user-images.githubusercontent.com/6810861/52800049-4815a700-307b-11e9-986b-9f4910fb17f2.png)

** video **
please also consider watching this small video.
as you will see player will travel_to and automatically pickup a selected item on the floor.
but for the item placed on the shelf, it will still automatically pick it up but will refuse to travel_to in front of the shelf. i am testing this with the new feature i am making, but this can also be confirmed using vanilla code from mainline with plain old travel_to function. (which is exactly what i am using anyway)
https://streamable.com/h6qf4

**Versions and configuration: **
 - OS: [Ubuntu 18.10]
 - Game Version [0.C-37406-g33ed69b6aa-dirty]
 - Graphics version [Tiles]
 - Mods loaded [  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "generic_guns",
  "more_locations",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "DP_AMAZING_CHEST_INDICATORS",
  "DP_REMIX_INDICATORS",
  "DP_XOTTO_INDICATORS",
  "more_classes_scenarios",
  "manualbionicinstall",
  "safeautodoc",
  "no_olg_guns"
]

**Comment by nsklaus** [comment]
thanks for the correction @Night-Pryanik

**Comment by Night-Pryanik** [comment]
You are welcome.

**Comment by kevingranade** [comment]
Is the issue resolved?
