### ISSUE TITLE
Dino Dave's pillow fort appears in every refugee center with or without static NPCs

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#28210]
**Describe the bug**  
Every refugee center always contains a pillow fort in the entrance even if static NPCs is disabled.

**To Reproduce**  
Visit every refugee center on the map.

**Expected behavior**  
Pillow forts should only be generated within the refugee center if Dino Dave existed in the world.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-37320-g2a8c342
 - Graphics version: Tiles
 - Mods loaded: dda

**Comment by I-am-Erk** [comment]
Static NPCs on is going to be the default very shortly, and the refugee center unique. I don't think this is too big an issue.
