### ISSUE TITLE
basements reveals  map sewer entry points

### ISSUE THREAD

**Issue by nsklaus** [CleverRaven/Cataclysm-DDA#28211]
**Describe the bug**  
being in a basement reveals on map all sewer entry points despite having not discovered them yet.

**To Reproduce**  
1. go in a house's basement
2. open map
3. see all sewer entry points

**Expected behavior**  
locations that not been visited yet should not be revealed on map.
i believe this is the auto-note option for marking stairs that go up or down.
but note should not appear if area was not visited yet.

**Screenshots**  
i've just started a new game i go in house basement (4th visited house in my new game) i open map and i see that:
![screenshot_20190215_174350](https://user-images.githubusercontent.com/6810861/52871117-9f824880-3149-11e9-9b8a-afcc07e704f3.png)

![screenshot_20190215_173100](https://user-images.githubusercontent.com/6810861/52870646-9644ac00-3148-11e9-8f55-69c3780cca05.png)

**Versions and configuration(please complete the following information):**
 - OS: [Ubuntu 18.10]
 - Game Version [0.C-37406-g33ed69b6aa-dirty]
 - Graphics version [Tiles]
 - Mods loaded [  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "more_locations",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "DP_AMAZING_CHEST_INDICATORS",
  "DP_REMIX_INDICATORS",
  "DP_XOTTO_INDICATORS",
  "manualbionicinstall",
  "safeautodoc",
  "Urban_Development"
]

**Comment by kevingranade** [comment]
If it's still happening it needs to stay open, this is a bug.

**Comment by Night-Pryanik** [comment]
Cannot confirm on latest experimental as of September 30, 2019.
