### ISSUE TITLE
Feature/fix: Moving over this repeated message is slow.

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#28215]
**Is your feature request related to a problem? Please describe.**  
There are several majorly spammy or even game-interrupting messages that detract from basic gameplay elements while moving. The two key offenders seem to be:

"Moving over this long grass is slow"
and
"Do you really want to step into that blackberry bush, Y/N"

Edit: anything related to jumping into or diving out of deep water is also a major culprit.

**Describe the solution you'd like**  
1. An options setting to silence identical movement related error messages for X minutes, where X is specified by the user and 0 minutes would maintain the current behaviour. 
- So, if set to 5 minutes, then once per 5 minutes you would get a "moving over this long grass is slow" message when getting onto long grass. You might still get a "moving over this giant pile of moose turds is slow" message while the long grass one was silenced, because they're different messages.
- I would suggest keeping the hidden messages visible in the message log though. Only hide them in the sidebar.

2. Make harmful terrain impassable while walking (including pits, identified traps. and things as well as rose bushes), and:
- Replace the "do you really want to step into the hip-deep pool of molten lead Y/N" prompts with a message in the message log saying "Stepping into that hip-deep pool of molten lead looks risky.  Press (run key) and move into it to force movement."
- Allow movement message silencing in options to apply to the "stepping into" message as well

Making "run" the way to force movement into hazards would improve the feeling of stepping into hazards anyway, making it harder for players to step into a deep pit of spikes when travelling at walking speed (something that should be difficult) but allowing them to do it accidentally when fleeing a zombear (something that should be easy to do).

**Comment by NotFuji** [comment]
A similar issue exists with the sound effects for the same action.  The sounds will repeat every time you walk over a grass tile (or any other slow tile), which gets just a little annoying after awhile of walking through a field or forest.

**Comment by I-am-Erk** [comment]
Sound effects seem trickier to me, I would say that's more a matter of wanting to have some variation in the sound font for common terrains like long grass...

**Comment by NotFuji** [comment]
A possible fix for walking over "dangerous" terrains like berry bushes would be to make them "impassable but climbable" similar to how chain fences work.  There's not a lot of cases when walking into a berry bush is a desired outcome of regular movement.  Plus, berry bushes are large enough that it's not inconceivable for a zombie to get stuck behind one.

**Comment by I-am-Erk** [comment]
The advantage of making them climbable (even for things like a rose bush that wouldn't strictly be climbable) is that it can be done straight away in JSON. I like that aspect of it even if I generally prefer the mechanical side of "press run to ignore safety and push forward"

**Comment by Wayticus** [comment]
I like the option of making the damaging obstacles like bushes and pits impassable by default with the ability to press a key to have the option to go through it and take damage if you really needed to save on time going around it.
The long grass sound bothered me so I turned down the obstacle effect in the sound pack, I don't need a sound telling me I'm walking through long grass or jumping over a counter, would be nice to be able to suppress the messages.

**Comment by DSeyka** [comment]
>Making "run" the way to force movement into hazards would improve the feeling of stepping into hazards anyway  

Problem is, with the way running is currently implemented, it's quite easy to forget that you're still running after the danger is over (e.g. after getting away in a car), and only be reminded of that by draining stamina (and/or heavy breathing, if using soundpacks). Or at the very least, *I* forget it all the time.  

I'm not against the idea per se, but it will likely lead to accidental deaths if implemented as is.

**Comment by kevingranade** [comment]
An alternate solution is to make these random semi-obstacles more "clumpy" so they're still obstacles, but require less mental effort to navigate around.

**Comment by I-am-Erk** [comment]
I'd say that's just a good reason to add more reminders that you're running. I'd suggest a colour change to the stamina bar and/or movement speed as well as the change from W to R... As well as possibly the message "you run through the blackberry bush"

**Comment by I-am-Erk** [comment]
@kevingranade I think clumping obstacles more would help, but both solutions would be ideal

**Comment by SunshineDistillery** [comment]
Instead of run, maybe tie the pop-up windows to safe mode.

**Comment by DSeyka** [comment]
These "y/n" pop-up windows, while being mildly annoying, not only prevent you from running through rose bushes, but also from fat-fingering a move into a landmine, or a shotgun trap you have discovered while being a step away from it. Or even your own trap you have just installed.

**Comment by I-am-Erk** [comment]
What I'm suggesting is that it not be possible to just wander into a trap or hazard you're aware of, unless you choose to do it. The Y/N prompt is a waste of time, given that 999/1000 times the answer is "no, obviously I don't want to walk into that landmine". Just treat an identified hazard as blocking terrain and require a specific override to force the character to go onto it if they want that.

**Comment by ifreund** [comment]
Just to add to this, walking through sewage/shallow water also fills your message log with "Moving through this shallow water is slow!" messages, and should probably be addressed here as well.

**Comment by DSeyka** [comment]
I like I-am-Erk's suggestion, make dangerous stuff impassable without deliberate intent from player's side.

**Comment by Phenomphear** [comment]
I would love an option to entirely suppress the "moving / is slow" from the log just like you can with the unknown messages from the options panel.

I personally don't care to be told that moving through long grass/clearing obstacles/wading through water is slow. I KNOW it's slow. I have a speed indicator on my UI. Suppressing these messages would be amazing.

**Comment by DSeyka** [comment]
Another option until something is done with this, is to play with a Parkour Expert trait. It's not a solution, of course, but a viable workaround. :)

**Comment by Phenomphear** [comment]
> Making "run" the way to force movement into hazards would improve the feeling of stepping into hazards anyway, making it harder for players to step into a deep pit of spikes when traveling at walking speed (something that should be difficult) but allowing them to do it accidentally when fleeing a zombear (something that should be easy to do).

I forgot to mention how much I love this idea btw. I can't tell you how many times I've been driving and hit a freaking tree or boulder because I wasn't paying attention and I kinda liked it because its somewhat realistic, you could easily run into something if your not paying attention, and while running, your certainly not focused completely, especially if your panicked.

**Comment by I-am-Erk** [comment]
Most of this issue remains unresolved, only the dangerous terrain prompt has been fixed

**Comment by Ramza13** [comment]
> Most of this issue remains unresolved, only the dangerous terrain prompt has been fixed

Which part remains?  Number 1 was fixed by #30543 I thought and now number 2 has been fixed.  Is there a part of number 1 that you don't think #30543 has addressed?

**Comment by I-am-Erk** [comment]
Honestly I'd forgotten about 30543, it's been a while. The last portion we'd planned was to remove long grass from spawning everywhere to cause spammy messages in the first place, which will be resolved by #35990, per [Kevin's comment](https://github.com/CleverRaven/Cataclysm-DDA/issues/28215#issuecomment-464277972)

**Comment by I-am-Erk** [comment]
This was basically closed already as Ramza13 pointed out, but now it's like, **uber** closed.
