### ISSUE TITLE
Headless zombies

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#28217]
**Is your feature request related to a problem? Please describe.**  
Some zombie types imply heavy damage to the body prior to reanimation; crawling zombies most notably. It has been said that beheading does not stop zombies from reanimating, and some survivors might falsely assume it does.

**Describe the solution you'd like**  
Some zombies should spawn as headless, a new zombie type, which may optionally have a new evolution line (characterized by lack of vision and scent but ablility to "hear" through sensing ground vibrations).

**Describe alternatives you've considered**  
Sufficiently damaged zombie corpses reanimating as a lesser version (decayed/crawling/headless).

**Additional context**  
N/A

**Comment by I-am-Erk** [comment]
Seems like a fair addition, the JSON would be fairly easy too.

**Comment by mlangsdorf** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-modders

**Comment by Ilysen** [comment]
I think this might require some code to execute properly, so that ranged weapons' Headshot mechanic wouldn't show up. It'd be a little silly to headshot something with no head.

**Comment by nexusmrsep** [comment]
I believe there is a flag for that, that can be set for such monster.
