### ISSUE TITLE
Wind turbines do not charge car battery on hippy van

### ISSUE THREAD

**Issue by Duhuh54321** [CleverRaven/Cataclysm-DDA#28219]
**Describe the bug**  
Wind turbine does not charge battery when I install it on a hippy van.

**To Reproduce**  
1. Start at evacuation shelter.
2. Spawn hippy van, 2 car batteries, 2 wind turbines, 1 toolbox
3. Set mechanic to 10 and install the parts to the van. 
4. Remove the existing battery of the van, which has 100% charges
5. Wait. And notice that the two 0% battery never get charged.

Test at place not near forest

6. Remove the two 0% batteries. Install 100% battery.
7. Drive van to place not near forest.
8. Remove the ~100% battery. install the 0% batteries.
9. Wait.  And notice that the two 0% battery never get charged.

Test removing roof

10. Remove the roof tiles of the car that are below the wind turbines.
11. Wait. And notice that the two 0% battery never get charged.

**Expected behavior**  
Expect car batteries get charged. I think I can install the wind turbine above the roof. Other parts of the car should not make the wind turbines stop working.

**Screenshots**  

![test_wind](https://user-images.githubusercontent.com/46102356/52896134-8b623980-3191-11e9-8c8c-760bcff05051.png)

**Versions and configuration(please complete the following information):**
 - OS: Linux
 - Game Version: 0.C-37450-ga123eea3e6
 - Graphics version: Tiles
 - Mods loaded:  No extras. I just use the default ones.

**Additional context**  
I have just git pull and recompile the game. 
I didn't delete any old files.
save:
[Test Wind2.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/2871704/Test.Wind2.tar.gz)

**Comment by davidpwbrown** [comment]
Removing the roofs and boards around the turbines allowed them to start charging. 
This is down to the ```            if( g->is_sheltered( global_part_pos3( part ) ) ) {
                continue;
            }```

Confirmed, yet will need to look into it some more, to disable surrounding vehicle parts as wind blockers. ( the assumption is that its taller than other parts )

**Comment by kevingranade** [comment]
Fixed by #28229
