### ISSUE TITLE
Opening help wont redraw some areas of the screen

### ISSUE THREAD

**Issue by dje4321** [CleverRaven/Cataclysm-DDA#28212]
**Describe the bug**  
Opening help on world options screen wont cause it to redraw

**To Reproduce**  
Create a world, Goto world options and press (?)

**Expected behavior**  
Should redraw

**Screenshots**  
Before
![screenshot_2019-02-15_10-50-27](https://user-images.githubusercontent.com/10913120/52871591-ff5bfd80-310f-11e9-865c-041991ddc930.png)
After
![screenshot_2019-02-15_10-50-49](https://user-images.githubusercontent.com/10913120/52871592-ff5bfd80-310f-11e9-9883-29fb7e1e8602.png)

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux
 - Game Version 0.C-37448-ga7144d223f
 - Graphics version: Both Tiles and Terminal
 - Mods loaded: N/A

**Comment by dje4321** [comment]
Bit more poking around reveals that its not just the world options menu thats affected. 

![screenshot_2019-02-15_13-25-23](https://user-images.githubusercontent.com/10913120/52879677-6637e180-3125-11e9-943f-9136e6b2bfef.png)
![screenshot_2019-02-15_13-26-01](https://user-images.githubusercontent.com/10913120/52879678-6637e180-3125-11e9-8f6f-c5855dd119a0.png)

**Comment by wapcaplet** [comment]
I could not reproduce any of these refresh issues in 0.E-9702-gdc4167363d. Pressing `?` then `Esc` from the world generation screen (any tab, including world options), or from the vehicle interaction menu, or the Actions menu, in all cases the screen was redrawn correctly.

**Comment by anothersimulacrum** [comment]
Fixed by the ui adaptor overhaul.
