### ISSUE TITLE
Please make a pumpkin pie recipe

### ISSUE THREAD

**Issue by settdigger** [CleverRaven/Cataclysm-DDA#28237]
**Is your feature request related to a problem? Please describe.**  
Nope

**Describe the solution you'd like**  
Pumpkin pie

**Describe alternatives you've considered**  
Not a pumpkin pie

**Additional context**  
Yum

**Comment by Fris0uman** [comment]
If you could provide a recipe for pumpkin pie it would make things easyer.

**Comment by settdigger** [comment]
Here's 1:

1 pumpkin
Cooking oil
Salt
Flour
Fat
Condensed milk
Sugar
3 eggs
Cinnamon

**Comment by Fris0uman** [comment]
A quick look at the recipe of pies in the game right now shows that `meat pie` `veggie pie` and `humble pie`just use `flour` and `water` for the dough and then meat, veggie or offal as filling.
Which mean that the pumpkin pie would be, by far, the hardest pie to make in the game.
Also i'm not 100% sure but I think cinnamon is not available in the game.

**Comment by mlangsdorf** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-modders

**Comment by mlangsdorf** [comment]
cinnamon is already a spice in the game.

**Comment by kevingranade** [comment]
Someone can feel free to PR a pumpkin pie recipe, but we can't afford to leave such specific issues in the tracker as it is already extremely difficult to find issues.
