### ISSUE TITLE
Npc camp upgrades (forge ) limit options instead of increasing it

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#28238]
Upgrades for forge in npc camp seem to  limit options and go backward as all options are seemingly avaible on start.

**To Reproduce**  
start camp and go for forge upgrades

**Expected behavior**  
Upgraded forge should give more options not less and some inital otpions like drop hammer shoudl not be avaible at start.

**Screenshots**  
this is first level forge
http://prntscr.com/mm9dsi

**Versions and configuration(please complete the following information):**
 last version
pk rebalance mode
dirty clothes

**Comment by SolsticeTheTechMarine** [comment]
The option to make a normal hammer also disappears when you upgrade a couple of times.
