### ISSUE TITLE
Impossible to sleep with insomniac trait on uncomfortable surfaces i,e pine lean-to.

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#28247]
**Describe the bug**  
Character refuses to fall asleep until survivor sleep now triggers from extreme sleep deprivation.

It shouldn't be impossible or it should at least state, when you attempt to sleep that you will NOT be able to sleep with the insomniac trait on uncomfortable surfaces, i,e a "Pine Lean-To" in this case.

**To Reproduce**  
1. Make a character with the insomniac trait.
2. Make a pine lean-to
3. Attempt to sleep.

**Expected behavior**  
It should be possible to eventually fall asleep at dead tired / exhausted. - I can make a makeshift straw bed and it works fine as that's classed as comfortable, so the problem lies with the combination of insomniac and uncomfortable surfaces, the combination is simply too strong, so much so that it prevents the willing attempt at sleep.

**Screenshots**  
![image](https://user-images.githubusercontent.com/5264667/52948122-86a7ac00-3370-11e9-842b-da83243a0ce0.png)

**Versions and configuration(please complete the following information):**
 - OS: Win 7 64bit.
 - Game Version [0.C-37519-g9900d9c]
 - Graphics version Tiles - chesthole32
 - Mods loaded [[ "dda", "Experimental-Z-Level", "more_locations", "FujiStruct", "Medieval_Stuff", "More_Survival_Tools", "Packaging", "RL_Classes", "SD_Magcrafting", "StatsThroughSkills", "blazemod", "Tanks", "Urban_Development", "ZSFIXED_cddaxp", "boats", "cityside", "craftgp", "deoxymod", "ew_pack", "filthy_morale", "makeshift", "more_buildings", "more_classes_scenarios", "mutant_npcs", "national_guard_camp", "no_npc_food", "npc_traits", "oa_additional_buildings_mod", "realguns", "Tolerate_This", "modular_turrets", "Salvaged_Robots", "Bootleg_Walkers", "DracoDogMod" ]]

**Additional context**  
I'm always on the discord if you want to narrow down any more specifics under the same username, or want a faster response.

**Comment by constatinus** [comment]
I had the same issue but without the insomniac trait. In multiple worlds.
