### ISSUE TITLE
Zombies revive through vehicle floors

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#28243]
**Describe the bug**  
Zombies revive inside vehicles when said vehicle is parked over them, regardless of whether the car is sealed airtight or not.

**To Reproduce**  
1. Find dead zombie that's eligible for revivication.
2. Park vehicle on top of it.
3. Let it revive.

**Expected behavior**  
Zombies shouldn't be able to revive inside vehicle, the revivication process should either be halted directly prior to getting up or the location of the revival set to a tile that the vehicle doesn't occupy.

**Versions and configuration(please complete the following information):**
 - Windows 10
 - 0.C-37519-g9900d9c
 - Tiles
 - PK's

**Comment by Night-Pryanik** [comment]
Related: #20727.
