### ISSUE TITLE
Chainmail armor unrealistically strong against blunt

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#28246]
**Is your feature request related to a problem? Please describe.**  
The chainmail items as they currently exist in the game have the same protection value against bashing and cutting damage, which is unrealistic at even a passing glance.

**Describe the solution you'd like**  
Strongly decrease bashing protection, increase cutting protection.

**Additional context**  
Chainmail armor is designed to protect against slicing and dicing, and is known to be weak against piercing and notoriously useless against bashing attacks. Historically, chainmail was always used in combination with a gambeson in order to alleviate this exact weakness at least partially.

Here's a convenient link to the wiki paragraph about effectiveness:
https://en.wikipedia.org/wiki/Chain_mail#Effectiveness

**Comment by Photoloss** [comment]
One potential issue is that chainmail is pretty decent at limiting the "maximum penetration" of a blunt impact which means when combined with sturdy padding the multi-layer arrangement is stronger than the sum of its parts. This is not true for most rigid armour (e.g. plate armor+kevlar/MBR vest) so a universal layering bonus is not justified either. 

On the programming side the game does not actually support an easy fix AFAIK as protection values are derived from the constituent materials. If no override exists this might be a more general solution as the same issues apply to lamellar construction and potentially even things like plate inlets (MBR/dragonskin vest) where the material definition assumes full rigidity. Adding a new "chain link" material would be a simple but inelegant fix for this one particular case.

The actual cutting protection also seems to be fairly low blocking less than half of a "standard" katana hit where IRL regular swords are essentially unable to cut through metal armour. This is even worse on plate armor though so I presume there is some deliberate deviation from reality for the sake of gameplay at work.

**Comment by Slumbrero** [comment]
Totally agree with OP. I'd reduce bash protection to a value between 5 and 9.
