### ISSUE TITLE
Game crash while in Shift-v and then 'x' mode to look around

### ISSUE THREAD

**Issue by BillCRobinson** [CleverRaven/Cataclysm-DDA#28257]
**Describe the bug**  
When in the Shift-V mode and using 'x' mode to look around the map I have had several cases when the game has crashed with a message such at the error shown in the attached screenshot.

**To Reproduce**  
1. type shift-v
2. type x
3. use number pad to look around (not sure if restricted to number pad, but that is what I use)
4. after a bit of looking around the game will sometimes crash

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 7  Ultimate
 - Game Version : 0.C-36390-g8b1361c
 - Graphics version Tiles
 - Mods loaded : no mods

**Additional context**  
May be related:  The sizing I have configured to start with is slightly larger than my main monitor (of 2).  I double click the top of the window and it resizes to my monitor.
![cdda_crash_log](https://user-images.githubusercontent.com/35176470/52976747-a783f780-3398-11e9-8928-2db63b332d0b.png)

**Comment by SolsticeTheTechMarine** [comment]
I can't seem to reproduce this. It was probably just trying to use a part of your systems memory that it couldn't. I had something similar happen when refilling a sealed stomach with liquid.

**Comment by ifreund** [comment]
This was probably fixed by #28436.  Please reopen if you can still reproduce.
