### ISSUE TITLE
The bug report form is missing three colons

### ISSUE THREAD

**Issue by Throwaway-name** [CleverRaven/Cataclysm-DDA#28251]
**Describe the bug**  
> 
> Versions and configuration(please complete the following information):
>  - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
>  - Game Version <<<<
>  - Graphics version <<<<
>  - Mods loaded <<<<
> 

**Additional context**  
Kind of a minor detail.

**Comment by kevingranade** [comment]
Fixed by #28256
