### ISSUE TITLE
Rotten Ingredient Check

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [CleverRaven/Cataclysm-DDA#28250]
**Is your feature request related to a problem? Please describe.**  
Occasionally if I am not paying attention to the massive stack of random ingredients I have acquired, I will get a rotten meal out of whatever recipe I create.

**Describe the solution you'd like**  
I would propose a check for the ingredients to see if any are rotten. If rotten ingredients are detected, it should ask if you are sure you wish to continue creating the meal, just as one would be asked before jumping into a pit. 

**Describe alternatives you've considered**  
Other alternatives would be to exclude rotten material all together, but I don't think that would be great for certain recipes.

**Comment by Zireael07** [comment]
I believe this (or a form of this) has been suggested multiple times?

**Comment by Night-Pryanik** [comment]
Yes, but I couldn't find the exact issue.

**Comment by codemime** [comment]
One of the corresponding issues is #25382.

**Comment by Ilysen** [comment]
I went and took a look at this to try and figure it out, but my coding skills aren't up-to-snuff enough to figure it out. It seems as though the crafting doesn't actually recognize that the individual items exist; just that items of that type exist. The crafting system doesn't differentiate between 3 rotten chunks of fat on the ground and 2 frozen chunks of fat in a minifreezer - it just counts it as "5 nearby chunks of fat."

I'm sure that this is doable, but I don't know how...
