### ISSUE TITLE
Multi-tile OM specials in cities

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#28265]
**Is your feature request related to a problem? Please describe.**  
City mapgen now allows multi-tile overmap specials, but these are not yet set to spawn in townl

**Describe the solution you'd like**  
Overmap specials that should spawn inside cities should be changed to spawn inside cities.
That is done by adding them to this list: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/regional_map_settings.json#L525

These are all buildings that should be spawning inside cities rather than out in the wilderness, and suggestions for which part of the city to put them in.
- Hotel (downtown/suburb)
- Motel (suburb) (should also spawn outside of town though)
- Megastore (downtown/outskirts)
- Hospital (downtown/suburb/outskirts)
- Public Works (downtown/outskirts)
- Apartments_Con (downtown/suburb)
- Apartments_Mod (downtown/suburb)
- Office Tower (downtown)
- Office_Tower_2.0 (downtown)
- Office Tower 2 Hidden Lab (downtown)
- Cathedral (downtown/outskirts)
- School (downtown/suburb/outskirts)
- Mall (downtown)
- Home Improvement Superstore (downtown/suburb/outskirts)
- football_field (downtown/suburb/outskirts)
- garage_gas (downtown/suburb/outskirts) (should also spawn outside of town though)
- cemetery_religious (downtown/suburb/outskirts) (should also spawn outside of town though)
- Lumberyard (downtown/outskirts)
- public pond (downtown/suburb/outskirts) (should also spawn outside of town though)
- cemetery (downtown/suburb/outskirts) (should also spawn outside of town though)
- botanical garden (downtown/suburb/outskirts)
- landscaping supply co (downtown/outskirts)
- storage_units_large (downtown/outskirts)
- storage_units_medium (downtown/outskirts)
- baseball_field (downtown/outskirts)
- shopping_plaza (downtown/suburb)
- Zoo (downtown/outskirts)
- Stadium (downtown/outskirts)
- Movie Theater (downtown)
- Trailer Park  (should also spawn outside of town though)
- Railroad Station (should also spawn outside of town though)
- Large Office Tower (downtown)
- 2fMotel (downtown, outskirts) (should also spawn outside of town though)

**Describe alternatives you've considered**  
Not really an alternative, but we should also look at adding more urban and suburban overmap types

**Comment by Hirmuolio** [comment]
I don't think all of them will work in cities. AFAIK only multi tile specials that can fit in without overlapping with roads can be in cities (3x2 or 2x2 max?).

**Comment by curstwist** [comment]
Was thinking about this last night, can we consider adding industrial and commercial zones/tags to group like buildings together?  Right now these may not have a great impact, but if we can say something should be both downtown/industrial or rural/industrial we could get some really nice building groupings.

**Comment by I-am-Erk** [comment]
@curstwist I don't think we can add industrial/commercial zoning just yet. As a whole I think city generation has some improvements in the pipeline but I'm not sure how they'd work...

@Hirmuolio per @ralreegorganon, who knows this way better than me, even giant specials like a mall can go in. The roads will just run around them. If we introduce all these we'll probably need to make the default city size larger, although that should really be part of more robust city building that prioritizes certain buildings first, so that you don't find a city with a megamall but no grocery store.
