### ISSUE TITLE
Expand procedural lab support to more general "facilities"

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#28261]
**Is your feature request related to a problem? Please describe.**  
Currently there is one universal type of "lab" drawn using fairly robust procedural map generation code.

**Describe the solution you'd like**  
Allow the same code to be used to build multiple different types of facilities, choosing from an appropriate list of JSON mapgen files.

This would allow the creation of all kinds of things, but in particular I'd be interested to see:
- Labs broken into specific types of labs - mutation labs, bionics labs, weapons research labs, and portal labs in particular.
- Sprawling military bunker or vault complexes
- Alien caverns, either in this world or others

**Describe alternatives you've considered**  
These kinds of alternate facilities could be made in json without the procedural generation code, but it would be a bit of a waste of some cool flexible code.

**Comment by Photoloss** [comment]
How easily can the code be generalised to non-square templates? Diamonds, triangles, hexagons and so on [tile just as easily](https://en.wikipedia.org/wiki/Lattice_(group)#Lattices_in_two_dimensions:_detailed_discussion) and would add a lot of variety but they'd need unique subdivision rules and slightly "smarter" door placement.
