### ISSUE TITLE
Lab/Facility "zones"

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#28262]
**Is your feature request related to a problem? Please describe.**  
Currently it is quite difficult to gate levels of a procedurally generated lab. The lab is our roguelike dungeon, and should get more difficult and have better loot as you delve deeper.

**Describe the solution you'd like**  
The name is up for debate - Zones already has meaning in the game - but we should be able to define a number of zones in the overmap terrain definition for the lab, and provide different mapgen options, monster, and item groups for the different zones.

**Describe alternatives you've considered**  
It could be possible to just specify certain item/monster groups to appear at particular z-levels down, but that would remove the possibility of having the difficulty increase as the player travels more northward into the facility or something like that.

**Additional context**  
Goes hand-in-hand with https://github.com/CleverRaven/Cataclysm-DDA/issues/28261

**Comment by cainiaowu** [comment]
or just call it "sections"

**Comment by CoroNaut** [comment]
We could go the SCP route and have levels accessible to level 1-5 personnel with special keycards that only work for a single lab. Besides the SCP's, having levels to a lab would be cool. Perhaps there could also be specifically a monster research level or something like that.

**Comment by I-am-Erk** [comment]
I'd be a huge fan of typed keycards with levels, especially if there were a few types. "XEDRA senior staff" could get you access to any facility, while "Biosciences Level 1" gets you into the top level of a mutation research lab only.

**Comment by Inglonias** [comment]
I also like the idea of key card levels, but a system like that requires a reworking (or if we're lazy, removal) of the lab start, which is fine because it's more or less free shelter, loot, and character points right now with very little risk or danger if you play your cards right.

Having different levels of lab also implies that we'd be reworking how labs are generated, which is also an idea I can get behind, but one that might be outside the scope of this issue.

**Comment by I-am-Erk** [comment]
The lab start is going to be a challenge again quite soon anyway, but yes, lab areas would require reworking it.
