### ISSUE TITLE
Faction Camp task Hunt Large Animal doesn't give corpses

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [CleverRaven/Cataclysm-DDA#28272]
**Describe the bug**  
When finishing the hunt large animal task, nothing is generated as a product of the task.

**To Reproduce**  
1. Start a hunting mission.
2. Finish the mission.
3. Look around for the corpses you were supposed to get.
4. Realize that they don't exist.

**Expected behavior**  
I expected it to work similarly to the trap small game task, where it would give an additional corpse every couple of hours.

**Versions and configuration(please complete the following information):**
* OS: [e.g. Windows 10]
* Game Version [0.C-37519-g9900d9c]
* Graphics version [Tiles]

**Comment by mlangsdorf** [comment]
You need a fairly skilled hunter for it to work.  I'm adjusting the difficulty from marksmanship versus 25 to 1.5 * marksmanship + perception / 2 versus 30.  There's two hunting attempts per 4 hours.

Marksmanship | Perception | Success % Per Check | Corpses/ 4 Hours
-- | -- | -- | --
0 | 4 | 7 | 0.14
0 | 6 | 10 | 0.2
0 | 8 | 13 | 0.26
0 | 10 | 17 | 0.34
0 | 12 | 20 | 0.4
2 | 4 | 17 | 0.34
2 | 6 | 20 | 0.4
2 | 8 | 23 | 0.46
2 | 10 | 27 | 0.54
2 | 12 | 30 | 0.6
5 | 4 | 32 | 0.64
5 | 6 | 35 | 0.7
5 | 8 | 38 | 0.76
5 | 10 | 42 | 0.84
5 | 12 | 45 | 0.9
8 | 4 | 47 | 0.94
8 | 6 | 50 | 1
8 | 8 | 53 | 1.06
8 | 10 | 57 | 1.14
8 | 12 | 60 | 1.2
10 | 4 | 57 | 1.14
10 | 6 | 60 | 1.2
10 | 8 | 63 | 1.26
10 | 10 | 67 | 1.34
10 | 12 | 70 | 1.4

**Comment by SolsticeTheTechMarine** [comment]
Retesting for certainty.

**Comment by SolsticeTheTechMarine** [comment]
It appears that I was wrong. I kind of assumed it would be similar to the rate at which I got small game.

**Comment by mlangsdorf** [comment]
No, it's deliberately more difficult, because the pay-off is the occasional wolf, bear, moose, or cow corpse.
