### ISSUE TITLE
NPC refugee center not reacting

### ISSUE THREAD

**Issue by Trokinos** [CleverRaven/Cataclysm-DDA#28288]
**Describe the bug**  
In the entrance room of the refugee center there are a bunch of NPC sitting on benches, and a couple of armed guards.
Only NPC that are close to a zombie is reacting, every other NPC are waiting as if there was nothing despite an obvious enemy is in range.

**To Reproduce**  
Player character started in the refugee center scenario.
Exited the refugee center after having talked to every NPC in there.
Moved a bit until character catched the attention of a brute zombie.
Decided to lead him into the refugee center so the armed guards would take care of it.

Once the brute zombie finally entered, no NPC reacted until he finally went very close (+/- 1 tile away) of one of the beggars and they fought, but only them, no other NPC acted, they are all still waiting until surviving monster come at +/-1 tile from them (and the other NPC still wil not react)

**Expected behavior**  
Considering the room is fully lit, there's no object breaking line of sight and all those NPC are all on the same area, the NPC should either run away (probably depending on their personality) or fight (armed guards are present in the room),

**Screenshots**  
https://i.imgur.com/PV8gF3J.jpg

**Versions and configuration(please complete the following information):**
recent experimental build 0.c 37523 g4c3c368

**Comment by I-am-Erk** [comment]
I wonder if this is because most of the beggars have the Pacifist trait, to signify their general combat incompetence. Does the mutant beggar act at all?

The guards not reacting might be because they're a different faction, but you'd think they'd be a bit more aggressive.

**Comment by Trokinos** [comment]
The mutant didn't react too as the zombie never got to 1 tile of distance from it, and the guard only reacted to the zombie when they moved to 1 tile close from them.

Same as the beggar that decided to fight (before dying).
It seems none of those NPC (beggars or guards) consider the zombie hostile as long as it is not at 1 tile of distance from them.

**Comment by Trokinos** [comment]
Downloaded the latest experimental at the time i write ( 0.c 37535 g409acf7 ) , and created a world without any extra mod just in case one played a role in the problem, then used the refugee center scenario start , went out and managed to lead a pack of zombie inside.

I can confirm this npc problem :

In this situation similarly to the original report the beggars do not react until the zombies are in melee fighting range, and the armed guard do nothing unless one of the zombie comes very close to them (they sometime shoot it and sometime seems to absolutely want to go in melee instead of shooting), and when they kill it, they just ignore the other zombies nearby.
Until one of those zombies comes very close to them.

At least this problem can be reproduced everytime.

**Comment by ZhilkinSerg** [comment]
Should be addressed after #22710 is merged.
