### ISSUE TITLE
Reloaded .460 rowland rounds have 0 crafting time.

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#28296]
**Describe the bug**  
As tilte 

**To Reproduce**  
1. Craft or spawn some .460 casings
2. Craft reloaded .460, standard or FMJ. Even more visable when bath crafting.

**Expected behavior**  
These rounds having similar crafting time to similar ammunition, 3m24s and batch crafting of 60% at >5

**Additional context**  
0 crafting time means its impossible or very hard to memorise the recipe by character.

**Comment by kevingranade** [comment]
Fixed by #28300
