### ISSUE TITLE
items rarely disappearing when dropped

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#28299]
**Describe the bug**  
3 times in the past 24 hours I've had items vanish when I dropped them.
I'm dropping them indirectly, they're falling when I drop my rucksack when preparing for a fight
I've lost
 - Glass bottle
 - Sledgehammer
 - Fire Axe

Possibly related: the sledgehammer and fire ax have occasionally been throwing an error about not existing after reloading a save (prior to vanishing), but changing the assigned letter to something else and then back makes the error stop.

Also possibly related: I'm updating the game in place through the launcher, i.e. using the same world after updating (though the world is only about a week old irl)

Also possibly related: my game's been getting confused between stacks of various ages.  I ask it to drop 10 meat (rotten) and instead it drops 10 meat (fresh) [from a 15 stack of meat (fresh)]

**To Reproduce**  
Not sure yet

**Expected behavior**  
dropping stuff shouldn't make it vanish

**Screenshots**  
None yet

**Versions and configuration(please complete the following information):**
 - OS: windows 10
 - Game Version: 0.C-37535-g409acf7
 - Graphics version: Tiles
 - Mods loaded: so many...
dark days ahead
filthy clothing
disable npc needs
simplified nutrition
bionics systems mod
makeshift items mod
more survival tools
alternative map key (this one doesn't seem to be working)
mutant npcs
npc traits
more buildings
folding parts pack
stats through skills
craftable gun pack
safe autodoc
growable pots

**Additional context**  
none yet

**Comment by Xpyder** [comment]
Here's the error I get when trying to equip or unequip the sledgehammer after reloading a save
 DEBUG    : item location does not point to valid item
 
 FUNCTION : void item_location::remove_item()
 FILE     : src/item_location.cpp
 LINE     : 601

**Comment by Xpyder** [comment]
[Cinnaminson.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2887815/Cinnaminson.zip)
Here's a copy of the world

**Comment by ifreund** [comment]
I'm pretty sure that #28276 will have fixed this.  Can you still reproduce after that commit?

**Comment by Xpyder** [comment]
"This also fixes errant removal of items if the wield was canceled by checking for success before removal"
Interesting confluence.  This definitely came in after i updated.

This definitely sounds like what was causing it, I'll check but it was inconsistent so it'll be a while and I'll probably forget about this ticket.

So I'm going to close it for now and I'll reopen if it persists
