### ISSUE TITLE
Map out roofs

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#28294]
**Is your feature request related to a problem? Please describe.**  
As we move towards z-levels being the norm, buildings should be spawning with roofs that can be climbed on and explored.

**Describe the solution you'd like**  
A few new terrain types:
- tar flat roof
- shingle roof
- metal roof
- tile roof
- glass panel (could be a roof/skylight or a floor)
A few new furniture types:
- chimney
- vent pipe
- TV antenna
- roof turbine vent

Roof terrain might need some new drawing code to make the "grain" point the right direction, and to create seams, or we could simply have a few different tiles and do it manually.

Once these terrains are made, we need to make roofs for existing worldgen buildings and have them appear appropriately.

**Describe alternatives you've considered**  
Not all these terrain types are needed, but variety is better to start with than to add later and have to retrofit.

**Additional context**  
It would also be nice to add a ladder tile, so we can do attics.

**Comment by Mecares** [comment]
Not to forget: Solar Panels on roofs

**Comment by I-am-Erk** [comment]
They're in furniture.json already

**Comment by I-am-Erk** [comment]
I am going to mark this closed, because while there are still a few roofs left it's basically done.
