### ISSUE TITLE
firecrackers and firecracker pack have no volume or weight

### ISSUE THREAD

**Issue by Leviathan21** [CleverRaven/Cataclysm-DDA#28291]
**Describe the bug**  
title

**Additional context**  
version 8515

**Comment by Night-Pryanik** [comment]
Firecracker has a weight of 3 grams. Both firecracker and pack has volume 0 because their volume is less than a minimum of 250 ml. The only thing that needs fixing here is firecrackers pack, since it's 25 pieces of firecrackers. Will fix it.
