### ISSUE TITLE
It's possible to cancel NPC missions from the camp manager interface.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#28308]
**Describe the bug**  
When issuing a NPC mission for camp expansion, it displays NPCs that are out on missions as options to accept the new mission.  If you select a currently dispatched NPC, the current mission is canceled and the NPC starts working on the new mission.

**To Reproduce**  
1. Give a player debug mind control.
2. Spawn and mind control three NPCs.
3. Spawn resources for a camp upgrade.
4. Send a NPC on the upgrade mission (remember their name).
5. Select another mission, the NPC out on the upgrade mission will appear as an option to send on the new mission.  Send that NPC on the new mission.
6. The upgrade mission is cancelled.

**Expected behavior**  
Filter NPCs on missions out of the list.

**Additional context**  
The behaviour isn't per-se *wrong*, especially when a NPC is doing something like a camp upgrade and cancelling their current task is a reasonable thing to do, but the way it works right now, there is no indication that is happening, so there is significant risk that the task you are cancelling costs you a significant amount of time and possibly other resources (I didn't check whether the resources dedicated to the task were wasted or not.

Another way to address this issue is to label the NPC entry with their current task so it is clear that it is being cancelled, but I think that's a riskier feature that is going to require validation that nothing funny is happening with resource consumption and other moving parts.

**Comment by mlangsdorf** [comment]
I have a fix for this.  It's pretty straightforward to filter the list of available NPCs to not include NPCs already on a mission.

**Comment by kevingranade** [comment]
Fixed by #28314
