### ISSUE TITLE
Bow sling has dissappeared after bow extraction <bag> <Items / Item Actions / Item Qualities>

### ISSUE THREAD

**Issue by grigoriynikolaev** [CleverRaven/Cataclysm-DDA#28306]
When I put a bow (I tried short and composite) in bow sling it works fine, but when I try to pull it out(through "a"ctivate menu) bow appears in my hand and bow sling simply dissappears from my inventory. Tested on various character in different world. 

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.C-37544-g1f473dc
 - Graphics version: Tiles
 - Mods loaded: vanilla

**Additional context**  
I use CDDA Game Launcher.(https://github.com/remyroy/CDDA-Game-Launcher/releases)

**Comment by kevingranade** [comment]
Fixed by #28312
