### ISSUE TITLE
Multiple errors when wielding wooden needle (Tried to find item parent/did not found item to remove it)

### ISSUE THREAD

**Issue by zacklucky7** [CleverRaven/Cataclysm-DDA#28319]
**Describe the bug**  

When attempting to wield a wooden needle (loaded or not), I receive multiple errors. Here is the log from debug.log:

    src/visitable.cpp:30 [item* visitable<T>::find_parent(const item&) [with T = Character]] Tried to find item parent using an object that doesn't contain it

    08:53:43.302 ERROR : src/character.cpp:838 [item Character::i_rem(const item*)] did not found item wooden needle to remove it!

    08:53:48.017 ERROR : src/visitable.cpp:30 [item* visitable<T>::find_parent(const item&) [with T = Character]] Tried to find item parent using an object that doesn't contain it

    08:55:11.972 ERROR : (error message will follow backtrace)

	(@0x5eae6e[cataclysm-tiles.exe+0x1eae6e]), 

	(@0x5eb44a[cataclysm-tiles.exe+0x1eb44a]), 

	(@0x5ed0e3[cataclysm-tiles.exe+0x1ed0e3]), 

	(@0x5687e0[cataclysm-tiles.exe+0x1687e0]), 

	(@0x6b5bd6[cataclysm-tiles.exe+0x2b5bd6]), 

	(@0x6b5cb1[cataclysm-tiles.exe+0x2b5cb1]), 

	(@0x71f0ed[cataclysm-tiles.exe+0x31f0ed]), 

	(@0x700c16[cataclysm-tiles.exe+0x300c16]), 

	(IMG_LoadWEBP_RW+0x4e8de9@0x1486949[cataclysm-tiles.exe+0x1086949]), 

	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 

	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 

	(BaseThreadInitThunk+0x14@0x7ffd42af3dc4[KERNEL32.DLL+0x13dc4]), 

	(RtlUserThreadStart+0x21@0x7ffd44243691[ntdll.dll+0x73691]), 

Backtrace emission took 0 seconds.`

The needle is wielded anyway and acts as expected.

**To Reproduce**  

1. Attempt to wield a wooden needle.

**Expected behavior**  

I was not expecting error messages, but the needle was wielded despite them and seems to work normally.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 Pro
 - Game Version: 0.C-37555-gf76242f (8536)
 - Graphics version: Tiles
 - Mods loaded: Issue occurs in a vanilla game

**Comment by ifreund** [comment]
Fixed by #28318

**Comment by kevingranade** [comment]
Fixed by #28318
