### ISSUE TITLE
Can create character with dark brown skin tone and Albino trait

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#28325]
**Describe the bug**  
In the character creation menu, you can select “Skin tone: Dark brown” and the Albino trait at once.

**To Reproduce**  
1. Start new character
2. In trait tab, select “Albino” and “Skin tone: dark brown”

**Expected behavior**  
The game prevents me from doing that, because it doesn't make sense.

**Actual behavior**
The game lets me do that.

**Versions and configuration(please complete the following information):**
 - Game Version: 0.C-37555-gf76242ff62

**Comment by RosaEscura** [comment]
Skin tone isn't actually from base game though, is it?
If not I'm afraid this issue will be closed pretty quickly.
Also that's something you just shouldn't do, picking them both at once I mean.

**Comment by Wuzzy2** [comment]
Oops. Sorry. Here's the full list of mods I used:

- Dark Days Ahead

PS: I have no idea what's it all about with skin tone/hair color, is it important for gameplay?

**Comment by RosaEscura** [comment]
I'm not 100% sure but I'm quite sure it only affects how your character looks with tiles. No effect on actual game play. Please feel free to correct me if I'm wrong.

**Comment by Rivet-the-Zombie** [comment]
Dark skinned people can have albinism too.

**Comment by SomeDeadGuy** [comment]
Their skin should be white tho, and no dark hair too.

**Comment by Myobu1** [comment]
> Skin tone isn't actually from base game though, is it?
> If not I'm afraid this issue will be closed pretty quickly.
> Also that's something you just shouldn't do, picking them both at once I mean.

It was added into the base game. You don't need a mod for that sort of thing anymore.

> Dark skinned people can have albinism too.

Albinos in Africa are white, and are horribly persecuted for their appearance. If they were black like everyone else (or dark skinned) they probably wouldn't have nearly as much trouble from their community.

**Comment by kevingranade** [comment]
This is a cosmetic issue the player has to take action to trigger.
