### ISSUE TITLE
Incorrect Terminal sizing aspect ratio

### ISSUE THREAD

**Issue by Nisteth** [CleverRaven/Cataclysm-DDA#28322]
Game version: 0.C-37555-gf76242f

Operating system: Windows 10 Pro 64-bit (build 17763)

Tiles or curses: Tiles

Mods active: N/A

### Expected behavior
Terminal Height variable should increase resolution in steps of 9 or 18, making all 16:9 and 4:3 aspect ratios accessible

### Actual behavior
Terminal Height increases in steps of 16, keeping it from precisely reaching 800x600, 1600x900, 1920x1080 and others

### Steps to reproduce the behavior
Change terminal height in the options menu.

**Comment by ifreund** [comment]
The step size is determined by the width/height of your font.  If you want to change the step size, consider changing your font.
