### ISSUE TITLE
Getting Deaf! when moving from a road in a vehicle at high speed

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#28320]
**To Reproduce**  
1. Get yourself an Armored Car or something
2. Reach 64kph on road
3. Move off road to explore this field nearby
4. "Your ears ring!"

**Expected behavior**  
I should still hear things

**Versions and configuration(please complete the following information):**
0.C-37429-g2365f4b02b-dirty

**Comment by SolsticeTheTechMarine** [comment]
Can confirm. This happens for me around 60 mph, but it should also be noted that I am using a vehicle without a roof, windshield or other things.
