### ISSUE TITLE
Fried Dandelions have too few calories

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#28338]
**Describe the bug**  
Fried dandelions give 17kcal but take wastebread which is worth 73kcal which is a 3/4 drop in calories from adding ingredients and oil.  
Flour, cornmeal, and tortilla are closer at 43kcal (which is still a 2/3 drop after adding in cooked dandelions)
Biscuit and harddtack are much farther at 200+ kcal

**To Reproduce**  
give yourself max cooking
compare recipes

**Expected behavior**  
kcal from food results should usually be comparable to kcal from ingredients.  Sometimes lower but not 1/4 their ingredients

**Screenshots**  
ask if needed

**Versions and configuration(please complete the following information):**
 - OS: Windows
 - Game Version: 0.C-37566-g60ad4a4
 - Graphics version: TIles
 - Mods loaded: lots, ask if needed

**Additional context**  
ask if need save

**Comment by Xpyder** [comment]
Note: I used wastebread as the base calibration since it's the most resource efficient ingredient with a reasonable availability

**Comment by KorGgenT** [comment]
you are just looking at the crafting menu and not the resulting food aren't you

**Comment by Xpyder** [comment]
I am.  Where does it indicate the resulting food will have a variable kcal?

**Comment by KorGgenT** [comment]
it does not currently indicate that. i am closing this issue, and will be making a PR within a few days to update the iteminfo in the crafting menu.
