### ISSUE TITLE
Cannot change wheel (wheel not detected by `has_components()`?)

### ISSUE THREAD

**Issue by keyspace** [CleverRaven/Cataclysm-DDA#28333]
**Describe the bug**  

Even if all tools/components are present, changing wheels (tires) is impossible, because the inventory does not detect presence of relevant vehicle part.

**To Reproduce**  

0. (NOTE: savegame provided below)
1. Stand next to a bicycle (light vehicle - no need for jack).
2. Have a multi-tool and appropriate-size wheel.
3. `e`xamine vehicle.
4. `c`hange tire on appropriate tile.
5. Observe wheel displayed in red.

**Expected behavior**  

Wheel is detected in inventory and action is permitted.

**Screenshots**  

N/A

**Versions and configuration:**
 - OS: Arch Linux 64-bit
 - Game Version: `0.C-37535-g60ad4a4a0e` (commit 60ad4a4a0e4140b0329e53c65d1e7309cb991a15)
 - Graphics version: Terminal
 - Mods loaded: vanilla

**Additional context**  

This happens on all vehicles I've tried, not just bicycles.

Tried last merge commit before PR #28114 - same issue. Did not attempt bisect.

-----

[vanilla.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2897045/vanilla.zip)

**Comment by ifreund** [comment]
Problem is that the list of wheels that are checked for is hardcoded, and more wheel variants have been added without updating it.
