### ISSUE TITLE
Tutorial seg fault

### ISSUE THREAD

**Issue by gmiz** [CleverRaven/Cataclysm-DDA#28334]
**Describe the bug**  
I'm a total new player in the world of cataclysm, and i just wanted to play out the tutorial. When I selected the right menu, and chose "Tutorial", everything seemed to "load" normally, and then everything freezes and i have to close the game manually, while also getting a message saying it's a segmentation fault.

**Versions and configuration(please complete the following information):**
 - OS: Fedora 24 Linux
 - Game Version: 0.C-37270-g86ec372
 - Graphics version: Tiles
 - Mods loaded: the default ones only? (i didn't touch anything yet)

Thank you for your time!

**Comment by ipcyborg** [comment]
Tried to reproduce that on the latest experimental 0.D-6237-g7682029.
No freeze or crash. 
The only issue I have found so far is that the flashlight have no batteries.  
No batteries at all on both top and bottom tutorial levels.

**Comment by Night-Pryanik** [comment]
Cannot confirm either. Tutorial is loading just fine.
