### ISSUE TITLE
Cannot activate road maps even though in bright tile

### ISSUE THREAD

**Issue by e-kato2** [CleverRaven/Cataclysm-DDA#28339]
**Describe the bug**  
Cannot read road maps even though in bright tile.

**To Reproduce**  
1. Find a road map.
2. Try to activate the road map in a bright tile.
3. The game responds with "It's too dark to read."

**Expected behavior**  
The map should be activated, and road locations added to the overmap.

**Screenshots**  
![zrzut ekranu z 2019-02-24 00-06-04](https://user-images.githubusercontent.com/47860596/53292773-4f9a2600-37c8-11e9-8be4-eae6be3e6098.png)

**Versions and configuration(please complete the following information):**
 - OS: NixOS 18.09
 - Game Version: 0.C-37566-g60ad4a4a0e-dirty
 - Graphics version: Tiles
 - Mods loaded: dda, disable npc needs, simplified nutrition, craftable gun pack, deadleavs' fictional guns, growable pots, icecoon's arsenal, makeshift items mod, medieval and historic content, more survival tools, dinomod, modular turrets, salvaged robots, mutant npcs, fuji's more buildings, oa's additional buildings mod, urban development, boats, folding parts pack, vehicle additions pack, tanks and other vehicles

**Additional context**  
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2897369/save.zip)

**Comment by e-kato2** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/28321/commits/c0a04e57b0c67c98ee357ae17153cb2b5226f747

The ">" at line 997 should be changed to a "<".

**Comment by stk2008** [comment]
**Screenshots**
https://i.imgur.com/uwWTnS8.png

* OS: win10

* Game Version: 8538

* Graphics version: Tiles

* Mods loaded: https://i.imgur.com/dvEN2lR.png

**Comment by e-kato2** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/28342

Should be fixed here.

**Comment by kevingranade** [comment]
Fixed by #28347
