### ISSUE TITLE
Charcoal smoker listed as tool in some recipes that it can't be used in

### ISSUE THREAD

**Issue by anothersimulacrum** [CleverRaven/Cataclysm-DDA#28343]
**Describe the bug**  
The charcoal smoker can only contain 180 charges of charcoal, but is listed as a tool in recipes that require 200 charges.
This occurs because the amount of charges was changed in #28004 
Recipes that it is listed as a tool in, but lacks the charges for:
3l Jarred versions of:
fish soup, canned fish, broth, human broth, tomato, canned veggy, redsauce, canned meat, canned fruit, canned offal, woods soup, sap soup, bone broth, vegetable soup, meat soup, red sauce, condensed milk.

**To Reproduce**  
1. Get charcoal smoker
2. Fill with charcoal
3. Attempt to craft a recipe that requires 200 charges
4. Don't have enough charges to craft

**Expected behavior**  
Charcoal smoker should not be listed as a tool for these recipes, or should have enough charges for these recipes.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-37555-gf76242f
 - Graphics version: Tiles
 - Mods loaded: dda

**Additional context**  
[Bug originally reported on reddit](https://old.reddit.com/r/cataclysmdda/comments/arkphc/cdda_changelog_february_17_2019/ego3nbq/)

**Comment by I-am-Erk** [comment]
I'm not sure if the better solution here would be to:
1. Make the script to show optional tools recognize if the tool hasn't got enough maximum capacity to ever do the recipe,
2. Increase the capacity of the charcoal cooker, or
3. Make it possible to reload something like a charcoal cooker while you're crafting.

I'm inclined towards 2, because realistically it doesn't matter much how many charges the charcoal cooker "holds", you can stoke it as you work. It should just have enough capacity for any of hte recipes in the game

**Comment by Dragometh** [comment]
> I'm not sure if the better solution here would be to:
> 
> 1. Make the script to show optional tools recognize if the tool hasn't got enough maximum capacity to ever do the recipe,
> 2. Increase the capacity of the charcoal cooker, or
> 3. Make it possible to reload something like a charcoal cooker while you're crafting.
> 
> I'm inclined towards 2, because realistically it doesn't matter much how many charges the charcoal cooker "holds", you can stoke it as you work. It should just have enough capacity for any of hte recipes in the game

I'd rather go with 3. It never made any sense not being able to recharge tools while crafting; If the required "fuel" for the tool is in range, why not just give a prompt to recharge the tool being used should it run out of charges? Same thing with repairing clothing with needles/kits or weapons.

> 2. Increase the capacity of the charcoal cooker, or
The problem with this is that the charcoal smoker could contain 50L of charcoal and only occupy 2L.
