### ISSUE TITLE
Transifex is not up to date

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#28357]
**Describe the bug**  
It appears the Transifex file for German is not up to date.

**Evidence**
I am approaching 100% for the German translation and there are strings that look untranslatable to me:

* All hair/skin tone style names and descriptions in the Trait selection screen
* Tab “HIDDEN” in crafting menu
* “(Case Sensitive)” in some Y/N menus
* probably a few others as well

Those appear in the POT file in the C:DDA repo (`master`), however.

**Version**
60ad4a4a0e4140b0329e53c65d1e7309cb991a15

**Comment by chaisawlajatang** [comment]
Transifex for Russian is not up to date too (the last update was about a month ago).

**Comment by BrettDong** [comment]
I'll create a 0.D branch on Transifex soon.

**Comment by Wuzzy2** [comment]
So we're no longer supposed to translate on master? How will you make sure that all translators will notice and don't accidentally translate “the wrong” branch where all their efforts will go to waste?

**Comment by BrettDong** [comment]
You're free to translate on whatever branch you like. If you wanna contribute to 0.D, go translate 0.D. If you want to translate master branch, go translate master branch.

**Comment by Wuzzy2** [comment]
SIGH.
Look. For obvious reasons 0.D has the top priority right now. Why would I want to push for only master when the efforts will go to waste and won't make it into 0.D? I really don't need such pointless confusion so short before release right now! And I think other translators think so, too.

I just noticed you already created the branch. So basically all my translations of the past few days went to waste because I pushed to the wrong branch. Nice. You should not have just switched the meaning of the resources on Transifex right in the middle of translation work!

I don't know how many translators still accidentally work on the master resource (which I just learned, is the WRONG one) because they didn't get the memo.

Now what do I do now to fix this mess?

Yes, I am quite pissed right now.

**Comment by Wuzzy2** [comment]
@BrettDong. Please talk to me in IRC. Name's Wuzzy. Server's `irc.freenode.net`. Channel's #CataclysmDDA.

**Comment by Wuzzy2** [comment]
OK, so it seems it's not too bad. Thanks to the translation memory feature in Poedit, I was able to restore most of the strings for the 0.D resource. Working with full steam power on 0.D translations now.

**Comment by BrettDong** [comment]
Your work on master branch is on master branch, your work on 0.D branch is on 0.D branch. Nobody deletes your translation. How Is it wasted? If a translator wants to translate master branch, he/she goes to master branch. If a translator wants to translate 0.D branch, he/she goes to 0.D branch. That's pretty simple. I don't get how you are confused.

**Comment by ifreund** [comment]
Isn't the problem that there is overlap between the untranslated strings on master and development? 
Or does Tranisfex merge that stuff automatically?

**Comment by BrettDong** [comment]
Transifex has a feature called translation memory auto-fill or something like that. Transifex will automatically fill in the translation for identical strings even across different branches.

**Comment by ifreund** [comment]
>Transifex has a feature called translation memory auto-fill or something like that. Transifex will automatically fill in the translation for identical strings even across different branches.

Sounds like there is zero issue here then, thanks for clearing that up.

**Comment by Wuzzy2** [comment]
I have discussed matters with BrettDong now. The dust has settled. Everything is fine.
