### ISSUE TITLE
Transparent crew-cut black hair

### ISSUE THREAD

**Issue by Foxtrot-Uniform42** [CleverRaven/Cataclysm-DDA#28352]
**Describe the bug**  
Black crew-cut hair is transparent, but it should not.

**To Reproduce**  
1. Create character with black crew-cut hair
2. It's transparent

**Expected behavior**  
Hair must be non-transparent

**Screenshots**  
How it looks now:
![transparent_hair](https://user-images.githubusercontent.com/46412513/53299781-1c57a580-3861-11e9-8618-6ae6e1ddce18.PNG)
Example of white hair, how it should be:
![non-transparent](https://user-images.githubusercontent.com/46412513/53299787-30030c00-3861-11e9-818d-96dc4767fae4.PNG)

**Versions and configuration:**
 - OS: Windows 10
 - Game Version: 0.C-37575-gf07c447
 - Graphics version: Tiles, msx++live_people
 - Mods loaded: dda

**Comment by Night-Pryanik** [comment]
I guess this could be closed after removal of the affected tileset?
