### ISSUE TITLE
Changing terminal size in the options menu doesn't work properly

### ISSUE THREAD

**Issue by ifreund** [CleverRaven/Cataclysm-DDA#28350]
**Describe the bug**  
Changing the terminal size fails to resize the window in tiles builds, resulting in scaled up or scaled down text.

**To Reproduce**  
1. Open a small window
2. Change the size to be very large
or
1. Open a large window
2. Change the size to be very small

**Expected behavior**  
Either we should actually require a restart for the effects to take place like it says in the option description, or resize the window properly.

**Screenshots**  
Medium sized window set to max terminal size in game:
![](https://image.frl/i/cqd8bkqn031jb0xv.png)

**Versions and configuration(please complete the following information):**
 - OS: macOS 10.14.2
 - Graphics version: Tiles

**Additional context**  
May only be an issue on mac, haven't tested other operating systems.

**Comment by Zireael07** [comment]
I have seen it on Windows 7 x64, ga7144d2

@ifreund what commit is that? (the final part of the string, after the dash, in window title)?

**Comment by ifreund** [comment]
Oh yeah forgot to add that, I tested on the current HEAD and before #28253 got merged in case I screwed messed it up with that somehow (doesn't look like I did).

**Comment by ZhilkinSerg** [comment]
I think it is resolved now (at least on Windows) after tremendous work by @Qrox.

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.
