### ISSUE TITLE
Heavy stick description suggests it can be used to make 2x4s, but that recipe was removed

### ISSUE THREAD

**Issue by zacklucky7** [CleverRaven/Cataclysm-DDA#28354]
**Describe the bug**  
The description of a heavy stick is as follows:

    A sturdy, heavy stick. Makes a decent melee weapon, and can be cut into two by fours for crafting.

However, the ability to cut heavy sticks/long sticks into two-by-fours was removed in #25735.

**Comment by Night-Pryanik** [comment]
Closed by #28356.
