### ISSUE TITLE
Fix description of heavy stick to not include making two by fours.

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#28359]
### Expected behavior

Descriptions should not mention crafting recipes that are impossible

### Actual behavior

Heavy stick --> 2x4 recipes were removed in https://github.com/CleverRaven/Cataclysm-DDA/pull/25735, but heavy sticks still say they can be made into 2x4s

### Steps to reproduce the behavior

Look at a heavy stick.

**Comment by ifreund** [comment]
Duplicate of #28354.

**Comment by I-am-Erk** [comment]
You're a duplicate
