### ISSUE TITLE
write dice throw against skill output in message log

### ISSUE THREAD

**Issue by nsklaus** [CleverRaven/Cataclysm-DDA#28363]
**Is your feature request related to a problem? Please describe.**  
lack of information about failure in performing tasks.

**Describe the solution you'd like**  
i think it would be a good idea to create an entry in the message log about why some intended action failed. for example:

- you failed to pick the lock, your skill is too low
- enemy attack dodge failed: your skill is too low
- you attempted to salvage cbm from the dead carcass but failed, your butchery skill is too low

you could also put in some actual numbers from the dice throw.  a simple example: "throw 8/10"  
(needed at least a 10 to succeed , you made an 8)
it would help new players to give them an idea why they fail.
it would also give them a goal, to find a way to raise said skill. 
it's better than just seeing your character failing without knowing exactly why.
it is frustrating to fail without knowing why. and you're never sure what exactly you should try to raise.
you might decide to raise some unrelated skill, and loose lots of time doing something unnecessary.

**Additional context**  
i was reading some article explaining game strategy for survival and importance of skill points in doing tasks and at start of the game (just after character creation at the very beginning)
and i was thinking, yes well, if i had known that i could have done something about those weaknesses.
so here's the idea. let the player know what's missing to they can try and remedy to a bad situation instead of being clueless about their horrible fate.

**Comment by kevingranade** [comment]
Reason for failure is fine, we do something like that already for melee
attacks.

Exposing skill check numbers is not.

**Comment by nsklaus** [comment]
thanks for the answer, 
also i would like to say the message log is being polluted, spammed by repetitive messages. drowning good infos in a sea of repetitive, useless ones.
i think this problem have been noticed and @I-am-Erk  is doing something about it.
that is good, both of these would improve, imho, user experience.
more meaningful messages, less spam.
but, i'd like to ask: why not letting the user know about the reason of his failure on the various skill based tasks ?
failure to pick a lock for example could be related to a lot of things like: being too dark, player being physically not well, stress, lack of sleep, or just insufficient skill point on that skill.
that one is easy to figure out you might say, but for someone who know the code and/or the game well yes, but not for others. me for example i'm starting to know the code, but i'm often puzzled why i repetitively fail at picking a lock whereas i think i should have succeeded but end up spending lots of time try and failing and i get no clues from the game about why it is so. 
and there's lot of example like this, i've just chosen one to illustrate. maybe it's not the most pertinent, but you see my idea, i think ?

**Comment by kevingranade** [comment]
> why not letting the user know about the reason of his failure on the various skill based tasks ?

You don't seem to have read my answer.  I said exposing the reason is fine.  Either say what the largest penalty the player was suffering from was, or choose a penalty to complain about based on the size of the penalties.

However exposing the actual formula used is not ok.  The formula is subject to change at any time, it's often not something the player should know about, etc.

**Comment by nsklaus** [comment]
ah i understand better what you said now. thank you for clarifying.

is there any pointer you could give me on where to start looking for exposing the reasons of failure in the message log ?  how are the skill checks actually implemented as of now, are they scattered in multiple files/multiple functions or is there a specific point (file or function) i should look at in particular ?
