### ISSUE TITLE
map::get_nonant Error When Entering Farm Building

### ISSUE THREAD

**Issue by HarleyLorenzo** [CleverRaven/Cataclysm-DDA#28361]
**Describe the bug**  
Early into my new playthrough, I stepped into a farm building with a pool table and the game gave me the error in the screenshot (the game wouldn't let me copy the bug but eventually it responded to spacebar spam.)

I'm unsure exactly what will make it reproducible.

**To Reproduce**  
1. Play version (0.C+git20190124.0525397-1) from Debian Testing
2. (?) Enter a farm house with a pool table 
3. (?) Map error

**Expected behavior**  
I would have expected the game to continue normally since I stepped into a mundane tile, but instead it completely froze.

**Screenshots**  
![screenshot_20190224_134234](https://user-images.githubusercontent.com/16141371/53303642-00410d80-383b-11e9-9a76-9bfdcc7d0148.png) (sorry about the transmission icon that appeared in the bottom)

**Versions and configuration(please complete the following information):**
 - OS: Debian Testing (Debian 10/Buster)
 - Game Version: 0.C+git20190124.0525397-1
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs, Filthy Clothing, Simplified Nutrition

**Additional context**  
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2898253/debug.log)

**Comment by HarleyLorenzo** [comment]
I've noted in a second playthrough the error happens at seemingly random intervals as well and requires a lot of spacebar spam to get it to continue afterward each time.

**Comment by Night-Pryanik** [comment]
@HarleyLorenzo have you encountered this error on latest experimental (or at least on 0.D stable) ever since?

**Comment by HarleyLorenzo** [comment]
@Night-Pryanik I have not noticed it in recent experimental builds, no.
