### ISSUE TITLE
"You put your $ITEMs in the wall"

### ISSUE THREAD

**Issue by Vivit-R** [CleverRaven/Cataclysm-DDA#28364]
**Describe the bug**
The advanced inventory management "move all" command moves items through walls.

**To Reproduce**
1. Open the inventory management screen.
2. Set one of the windows to some direction *n* in which there is no adjacent wall. (The game does not allow you to select one in which there is a wall, as presumably intended.)
3. Close the inventory menu.
4. Move to a tile where there is an adjacent wall in direction *n*.
5. Ensure that there is at least one item on that tile, or on a tile adjacent to that tile.
6. Open the advanced inventory management menu again.
7. Set the window *not* set to display the wall tile in direction *n* to display the tile containing the items, or to display all adjacent tiles.
8. In the window that displays the items, enter the "move all" command bound to ',' by default.

**Expected behavior**
The message "You put your $ITEM in the wall" is printed for every $ITEM moved. These items are then placed on some *valid, non-wall* tile adjacent to the wall tile in direction *n*, including the tile on which the player character is standing, and also including the tiles on the other side of the wall. All items are placed on the same tile.

**Screenshots**
![Advanced inventory management screen -- note minimap](https://i.imgur.com/13Wx3yo.png)
!["You put your splintered wood in the wall. x 3"](https://i.imgur.com/qu5tm9f.png)
![Items have moved southeast to the other side of the wall.](https://i.imgur.com/gp3sU7e.png)

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 18.04.1
 - Game Version: Sucessfully reproduced on head of master
 - Graphics version: Terminal
 - Mods loaded: dda

**Additional context**
The bug works when "moving all" from adjacent tiles and the center tile, including from vehicle storage, but does *not* work when moving from your inventory -- in that case, the intended "You can't put items there!" denial message is printed.

**Comment by kevingranade** [comment]
Fixed by #28369
