### ISSUE TITLE
"You are too pacified to strike anything" can be bypassed with spears

### ISSUE THREAD

**Issue by Sammmmm** [CleverRaven/Cataclysm-DDA#28367]
Pressing f to strike with a spear rather than moving into a creature to attack lets you bypass the effects of relaxation 

Repro:
1. Get pacified by a riot control bot ("Relaxation Gas" debuff)
2. Attempt to attack something normally to ensure you're pacified enough.
3. attack with f and strike with your spear as normal

Expected:
"You are too pacified to strike anything"

**Comment by kevingranade** [comment]
Fixed by #28368
