### ISSUE TITLE
Crash to desktop 

### ISSUE THREAD

**Issue by Alapaga** [CleverRaven/Cataclysm-DDA#28375]
**Describe the bug**  
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2898823/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2898824/crash.log)
Crash to desktop after restarting the game for graphical settings to take effect after resizing the game window
The latest update is permanently broken for me now, i had to rollback to even load the game

**To Reproduce**  
console to 100width 28height, the other elements were adding a scaling factor x2, with direct x11 enabled and switching from windowed borderless to windowed mode 

**Expected behavior**  
I expected the game to be on the right aspect ratio for my screen and have readeable enough interface

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-37516-gc5d1def 
 - Graphics version: Tiles
 - Mods loaded: Retrodays fo life

**Additional context**  
How do i unbreak the game? I am part of the cdda discord as Alapaga if you guys wanna contact me.
The reason i was tweaking the graphics is to try and stream the game, i has been unsuccessfull in finding a good aspect ratio so as the game text is readeable enough for someone watching the stream while the player is not on fullscreen. the idea is to try and find a good 853x480 game window with a scale factor so  that i can read the text myself on my 1920x1080 monitor. Any suggestions are welcome!

Thanks for your help guys, keep up the good work

**Comment by Headjack** [comment]
Yeah I am also having constant crashes involved in changing the focus of the screen or tabbing out, or minimizing.

**Comment by DSeyka** [comment]
Can confirm, 0.C-37523-g3cf96a9 crashes when alt+tabbing out of the game if both fullscreen mode and direct3d rendering are enabled. Couldn't reproduce with either of these settings set to anything else, though.

>CRASH LOG FILE: config/crash.log
VERSION: 0.C-37523-g3cf96a9
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x54BEF0[cataclysm-tiles.exe+0x14BEF0]
    @0x54C291[cataclysm-tiles.exe+0x14C291]
    SMPEG_error+0x3DAF3@0xB9DE95[cataclysm-tiles.exe+0x79DE95]
    UnhandledExceptionFilter+0x1CB@0x7551A3DB[KERNELBASE.dll+0x1AA3DB]
    LdrResolveDelayLoadsFromDll+0xD4F@0x7731DB7F[ntdll.dll+0xADB7F]
    KiUserApcDispatcher+0x96@0x772E2846[ntdll.dll+0x72846]
    RtlInterlockedCompareExchange64+0x1B4@0x772F5004[ntdll.dll+0x85004]
    KiUserExceptionDispatcher+0x26@0x772E2936[ntdll.dll+0x72936]
    @0x71F3DB25
    SDL_LogCritical+0x170AD@0xBC147D[cataclysm-tiles.exe+0x7C147D]
    SDL_LogCritical+0xFFDF@0xBBA3AF[cataclysm-tiles.exe+0x7BA3AF]
    SDL_LogCritical+0x141C@0xBAB7EC[cataclysm-tiles.exe+0x7AB7EC]
    SDL_LogCritical+0x39D8C@0xBE415C[cataclysm-tiles.exe+0x7E415C]
    SDL_LogCritical+0x3E6BE@0xBE8A8E[cataclysm-tiles.exe+0x7E8A8E]

**Comment by ifreund** [comment]
>How do i unbreak the game?

Manually setting the scaling factor back to 1 by editing `options.json` should do it.  Minimum terminal size for a 2x scaling factor is 160x48, two times the normal minimum.  There are checks that are supposed to handle this situation, and they work fine on mac and linux as far as I can tell.  Not sure what's up with windows but I'll look into it.

**Comment by ifreund** [comment]
If any of you people were were using the windows terminal build, #28380 will hopefully fix things.

**Comment by kevingranade** [comment]
No indication that this is extant.
