### ISSUE TITLE
The option to change skin tone, hair color and hairstyle is missing.

### ISSUE THREAD

**Issue by 198six** [CleverRaven/Cataclysm-DDA#28389]
**Describe the bug**  
The option to change skin tone, hair color and hairstyle is missing.

**To Reproduce**  
1. Make a custom player.
2. Go to the traits option.
3. The third column that has skin tone, hair color and hairstyle is missing.

**Expected behavior**  
Under traits, you should have the option to customize your appearance such as skin tone, hair color and hairstyle.

**Versions and configuration(please complete the following information):**
 - OS: Windows 8.1
 - Game Version: 0.C-37529-g91a0c5f
 - Graphics version: Tiles
 - Mods loaded: dda, disable NPC needs, filthy clothing, simplified nutrition

**Comment by ifreund** [comment]
This is intended, hair and skin traits are not part of 0.D

**Comment by 198six** [comment]
That doesn't make sense. The previous versions of the file I mentioned has those options. I'm assuming someone removed it.

**Comment by ifreund** [comment]
see https://github.com/CleverRaven/Cataclysm-DDA/issues/27843#issuecomment-466832539

the former master branch, "experimental" if you will, has been moved to the development branch and the 0.D moved to master.  This means that the automated build systems are now building from the 0.D release candidate, not the experimental.

**Comment by 198six** [comment]
I got it. Thanks for breaking it down for me.
