### ISSUE TITLE
Some text is distorted

### ISSUE THREAD

**Issue by DarkDaskin** [CleverRaven/Cataclysm-DDA#28385]
**Describe the bug**  
Some text is distorted (squashed or cropped). Software rendering mode works better, but still has some cropping.

**To Reproduce**  
1. Load a game

**Expected behavior**  
All text is rendered without cropping or distortion.

**Screenshots**  
direct3d/direct3d11/opengl:
![direct3d](https://user-images.githubusercontent.com/200260/53358611-db838d80-3941-11e9-866c-aca56e7615d2.png)
software:
![software](https://user-images.githubusercontent.com/200260/53358631-e76f4f80-3941-11e9-99a2-f4ee8937f41c.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-37529-g91a0c5f
 - Graphics version: Tiles

**Additional context**  
Version 0.C-34978 did not have this problem.

**Comment by ifreund** [comment]
[This](https://github.com/CleverRaven/Cataclysm-DDA/pull/28380/files#diff-58d299f459cbd7d41c0d673ed9d9ad4cR1107) if statement should fix this

**Comment by ifreund** [comment]
Can you confirm that this has been fixed at 1x scaling factor @DarkDaskin?

**Comment by DarkDaskin** [comment]
@ifreund yes, seems fixed. Thank you.
