### ISSUE TITLE
Fingerhack not hacking id gates

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#28399]
I don't know if this is intended or not, but Fingerhack should able to hack card readers just like the electrohack.

![image](https://user-images.githubusercontent.com/44106380/53418131-0d642500-3a12-11e9-8158-26280099ff75.png)

![image](https://user-images.githubusercontent.com/44106380/53418190-2a005d00-3a12-11e9-8f51-f901d47b68f5.png)

**Comment by Night-Pryanik** [comment]
Check if you have enough power (at least 25 power units) to activate the fingerhack. Tested right now on latest experimental as of 27th February 2019 - fingerhack with enough bionic power is working perfectly on card readers.

**Comment by BBlankie** [comment]
oops i forgot about that power requirement
