### ISSUE TITLE
Change city size and spacing values to a range for increased variability

### ISSUE THREAD

**Issue by RosaEscura** [CleverRaven/Cataclysm-DDA#28390]
**Is your feature request related to a problem? Please describe.**  
Not a problem per se but the world could do with more variation in terms of city spacing and size

**Describe the solution you'd like**  
Instead of one value for size of cities and another for city spacing player could choose a minimum and a maximum value for these two. For example: City spacing is 4 by default (0 min, 8 max) so if you wanted the distance between cities to be more random but on the lower end of the spectrum you could choose 1-4.

**Describe alternatives you've considered**  
Don't do anything, you lazy bastard! :p

**Comment by RosaEscura** [comment]
@I-am-Erk in case you want to have a look at this : >

**Comment by I-am-Erk** [comment]
I'd like to see this done by changing city size to a normal distribution instead of a series of if statements

**Comment by kevingranade** [comment]
These values already imply a range, making this more varied is a valid goal, but this isn't a good approach.
