### ISSUE TITLE
Camp Communications Tower

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [CleverRaven/Cataclysm-DDA#28393]
**Is your feature request related to a problem? Please describe.**  
So, when I was scavenging through the city, I happened upon some radios and subsequently thought that it would be pretty neat if you could call one of your camps and arrange missions away from the base. I like the option to build little supply points, but it seems like there is no way to do so without first going to the camp, talking to the manager, finding things to pass the time while things are set up, then returning to the manager to create the site or relay the objects. This is a tedious process. 

**Describe the solution you'd like**  
This is where the criminally underused two way radio comes in. Spread all throughout the towns and cities you will find these books called "Ham Radio Illustrated" and "Amateur Home Radio for Enthusiasts", and I doubt that the pc is the only person to pick up a copy and use what is inside. I would think that there would be many more people and even factions would be communicating via the radio throughout the area. 

This brings me back the two way radio. You could use it as a method to contact your base manager at whichever camp you have built a certain building, or finished a center base upgrade on. Maybe, that same building could be used to do various other actions that a radio station would perform, such as signalling for survivors to come to your camp, (which could attract roving raiders) or contacting the refugee center or other survivor groups to trade or get missions.

**Describe alternatives you've considered**  
Currently, I cannot think of any, but I will edit this post if I do think of any.

**Additional context**  
Currently, I cannot think of any, but I will edit this post if I do think of any.

**Comment by mlangsdorf** [comment]
Remote basecamp control via two-radios is a planned feature for 0.E or 0.F, probably 0.E.

**Comment by mlangsdorf** [comment]
Fixed.
