### ISSUE TITLE
(w)ielding from a scabbard/holster takes longer than (a)ctivating it

### ISSUE THREAD

**Issue by Feuerhai** [CleverRaven/Cataclysm-DDA#28395]
**Describe the bug**  
When you try to take out a sword by (w)ielding the scabbard and confirming the prompt to take out the sword instead, you need more time than when you (a)ctivate the scabbard instead. Same thing for guns and holsters.

**To Reproduce**  
1. Make a player with a broadsword, a scabbard and a watch(optional).
2. Wear the scabbard and put the sword in it.
3. (a)ctivate the scabbard and note the time it takes.
4. Put the sword back.
5. (w)ield the scabbard and confirm the prompt, noting the time again.
6. Wielding took longer than activating.

**Expected behavior**  
You use the same time to take out the weapon both times.

**Versions and configuration:**
 - OS: Win 7
 - Game Version: 0.C-37527-gd075e8d
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, NPC traits, Zetsukaze's Hair Extensions!, (DP_RP) REMIX Indicators

**Comment by ifreund** [comment]
Ok, I know what's happening here.  `holster_actor::use()` checks if/where the item is worn at when determining wield costs.  However, after recent changes to `game::wield()` the item isn't actually worn at the time that is it invoked, rather floating in limbo.  Will have to think about the best way to fix this.
