### ISSUE TITLE
Title screen is messed up and segfaults when selecting anything

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#28400]
**Describe the bug**  
If you start CDDA (terminal mode), the title screen is messed up (the ASCII art is split in half) and when you do anything in the main menu, it quickly crashes.

**To Reproduce**  
1. Start CDDA (console mode)
2. Do one of the following: Select MOTD or Credits, or open one of the menus that would trigger a new window (new world, options, etc.). It's easy to trigger the crash

**Expected behavior**  
CDDA has a normal title screen and does not crash.

**Versions and configuration(please complete the following information):**
 - OS: GNU/Linux
 - Game Version: 91a0c5f1df4365908db76ae10b7b9a4f62ab8be2
 - Graphics version: Terminal
 - Mods loaded: N/A

**Additional context**  
GDB backtrace:

#0  0x00007ffff7f31eeb in _nc_printf_string_sp () from /usr/lib/libncursesw.so.6
#1  0x00007ffff7f2b862 in vwprintw () from /usr/lib/libncursesw.so.6
#2  0x00007ffff7f2b9f5 in wprintw () from /usr/lib/libncursesw.so.6
#3  0x0000555555ce152f in wprintz(catacurses::window const&, nc_color const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#4  0x0000555555ce7674 in fold_and_print_from(catacurses::window const&, int, int, int, int, nc_color, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#5  0x0000555555b0b3db in main_menu::display_text(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&) ()
#6  0x0000555555b0f316 in main_menu::opening_screen() ()
#7  0x00005555557ed286 in main ()

**Comment by Treah** [comment]
This is fixed by  #28380
