### ISSUE TITLE
Make lava more THICC

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#28407]
In my tileset lava supports connected textures. However all the time lava line spawns on the ground it placed in such a way what my connected tiles are not connected. Lava should be slighttly more thick, so it will connect propper.
Here an exapmle.
not thick, original, not connected in most parts
![lavawrongtiles](https://user-images.githubusercontent.com/37592026/53503640-83739500-3ac1-11e9-8a8b-4f1eda94faab.png)
THICC, connected
![lavarighttiles](https://user-images.githubusercontent.com/37592026/53503832-e9f8b300-3ac1-11e9-8d00-812e1beee0a5.png)

**Comment by Mecares** [comment]
Also, Lava should set adjacent flammable buildings/furniture on fire.
