### ISSUE TITLE
Listening to mp3 player music sometimes shows untranslatable msg

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#28409]
**To Reproduce**  
1. Get yourselves an MP3 player
2. Listen to its music
3. Wait a few turns and watch the messages scroll

**Expected behavior**  
Display random music styles from time to time in the message log, translated properly.
Like “You listen to Christian porno polka.”.

**Actual result**
It works most of the time. But sometimes, the meesage shows just “You listen to music.”. The word “music” is untranslatable.

**Suggestion**
Since we're way behind string freeze, just drop the special case of “You listen to music.”.

**Versions and configuration(please complete the following information):**
 - OS: GNU/Linux
 - Game Version: 0.C-37544-gc172ff663e
 - Graphics version: Terminal
 - Mods loaded: DDA, disable NPC needs, filthy clothing, simplified nutrients

**Additional context**  
N/A

**Comment by anothersimulacrum** [comment]
On lines [3594](https://github.com/CleverRaven/Cataclysm-DDA/blob/c172ff663ec8900fbf75d6b0a7c085160c74a4ac/src/iuse.cpp#L3594) (maybe) and [3636](https://github.com/CleverRaven/Cataclysm-DDA/blob/c172ff663ec8900fbf75d6b0a7c085160c74a4ac/src/iuse.cpp#L3636) (definitely)  in iuse.cpp, "music" should be _( "music" ), so that it's included in the translation.

**Comment by Wuzzy2** [comment]
Yes, but we're in string freeze now.

**Comment by kevingranade** [comment]
It's possible that string is already captured elsewhere, then we could just
add the redundant capture.

**Comment by kevingranade** [comment]
Not the word music, but I made one of the other genre snippets that is already translated the fallback.

**Comment by Wuzzy2** [comment]
Interestingly, the “fallback” seems to be used fairly often! Intentional?
