### ISSUE TITLE
performance problems with finalizing vehicle prototypes

### ISSUE THREAD

**Issue by spacenookie** [CleverRaven/Cataclysm-DDA#28402]
**Describe the bug**  
game takes much longer than you would expect to finalize vehicle prototypes.

**To Reproduce**  
start a new game or load a save game, there will be a noticeable delay in the loading process when finalizing vehicle prototypes.

**Expected behavior**  
should be much faster

**Versions and configuration(please complete the following information):**
 should be all versions and configurations but exact amount of delay varies

**Additional context**  
occurs because vehicle_prototype::finalize calls vehicle::install_part once for each part in the vehicle prototype. vehicle::install_part installs one part then calls vehicle::refresh. vehicle::refresh is an expensive routine that iterates all parts in the vehicle and recalculates all vehicle dynamics. this results in a cost of (where N = number of vehicle parts) of N * N/2 instead of N as it should be. if average vehicle has 100 parts this inflates runtime of this routine (vehicle_prototype::finalize) by a factor of around 50.

**suggested fix**
easy way to go seems to be to suppress calls to vehicle::refresh from vehicle::install_part until the last part is added in vehicle_prototype::finalize.

**Comment by mlangsdorf** [comment]
Fixed queued for post 0.D
