### ISSUE TITLE
0.D (dev) list of typos

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#28418]
Here's the list of typos I found in the 0.D branch, as of c172ff663ec8900fbf75d6b0a7c085160c74a4ac:

* .460 Rowland ammunition with 185gr JHP bullets.  The .460 Rowland round is designed to emulate hard-hitting .44 magnum in common autoloading pistols. Like the .44, .460 rowland has exceptional power - and recoil. It is almost dimensionally identical to .45ACP, save for having a longer case and deeper seated bullets to prevent ammunition mix-ups.
       * rowland → Rowland
* robo-gaurdian
       * → robo-guardian
*A salvaged defense robot refitted with a homemade flamethrower and two searing hot blades.  Activate this item, with gasoline in your inventory, to load and deploy the robot... preferably far from anything flamable
        * flamable → flammable
* A salvaged utility robot converted into an ambulatory bee hive that periodically removes and delivers honey combs.  It protects the insect colony with a mechanical crossbow mounted to its chasis.
        * chasis → chassis
* A salvaged utility robot converted into an ambulatory bee hive that periodically removes and delivers segments of fresh honey comb.  It protects the insect colony with a mechanical crossbow mounted to its chasis.  Activate this item, with wooden bolts in your inventory, to load and deploy the robot.
        * chasis → chassis
* A salvaged defense robot refitted with a homemade flamethrower and two searing hot blades.  Activate this item, with gasoline in your inventory, to load and deploy the robot... preferably far from anything flamable
        * flamable → flammable
* Your base has become large enough to support an expansion.Expansions open up new opportunities but can be expensive and time consuming.  Pick them carefully, only 8 can be built at each camp
        * expansion.Expansions → expansion.  Expansions
* cop3
        * Bad string. Description of NPC mutation `BGSS_Cop_3`. For similar mutations the description is “This NPC could tell you about how they survived the cataclysm”
* In the data we found a major contract for tunneling and train equipment, ordered eight months ago.  It's the best lead we have.  Here's the address of the government lab where the equipment was delivered.  I want you to go there, find the tunnels that they dug, and download everything you can about the train network.
        * → does this string also appear when you survived >1 year?
* I'm not a cortionist!
        * cortionist → contortionist
* Well now, That's a hell of a story, so settle in.  It all goes back to about five years ago, after I retired from my job at the mill.  Times was tough, but we got by.
        * That's → that's
I was just in a warehouse, not in Zambonia.  I had the internet.  Watched those crazy videos on youtube in real time, scared the shit out of me.  I had it pretty good though, I'd lifted a bunch of canned food and shit, and I had a pretty sweet little squat in that warehouse.  I'd been planning on spending a long time there after all, while I figured out how to get in good with my crew.
        * youtube → YouTube
* I thought I had those damned <zombies> figured out.  I got braver, started heading out by day more and more.  One of those screamer zombies spotted me and called in a horde, with a giant <swear> beasty at the head of it, the size of a volkswagen and all covered in bone plates.  I know when I'm outclassed.  The big guy was held back by his own horde of buddies, and I managed to book it back to my place.  I closed the windows, locked it down, but it was too late.  The giant followed me and just started hammering right through the walls.  I grabbed what I could and made for the horizon.  Last I saw of my squat, it was collapsing on the bastard.  For all I know, it died in the crash, but I am not going back to find out.
        * beasty → beast
* Probably best choice of installing or uninstallings bionic for lone surviros is Autodoc.  Usually you can find those in hospipatls and clinincs (even in some 'unnoficial' ones).  Any procedure using it requires consuming of single Anesthesia kit.  You can bypass this restriction if you find the way to completely ignore pain.  But don't even try to bypass this restriction using drugs - it won't help.
        * there's a ton of typos here!
* I did.  Took a few hours to get an opening.  And you wanna know the fucked up part?  Like, out of all this?  My wife was still alive.  She'd been in the basement the whole time, pinned under a collapsed piece of floor.  And she'd lost a ton of blood, she was delirius by the time I found her.  I couldn't get her out, so I gave her food and water and just stayed with her and held her hand until she passed.  And then...  well, then I did what you have to do to the dead now.  And then I packed up the last few fragments of my life, and I try to never look back.
        * delirius
* I did.  Took a few hours to get an opening.  And you wanna know the fucked up part?  Like, out of all this?  My husband was still alive.  He'd been in the basement the whole time, pinned under a collapsed piece of floor.  And he'd lost a ton of blood, he was delirius by the time I found him.  I couldn't get him out, so I gave him food and water and just stayed with him and held his hand until he passed.  And then...  well, then I did what you have to do to the dead now.  And then I packed up the last few fragments of my life, and I try to never look back.
        * delirius
*What's up in your life these days
        * missing "?"
* Named coefficients are measured in the range from 0%% (which means terrible inefficiency) to 100%% (ideal conditions).
        * double percent sign (tested, yes, it actually renders as 2 percent signs in the final help)

Don't touch strings as long string freeze is in place, but I post this issue for the time after 0.D got released.

**Comment by kevingranade** [comment]
You can open a PR against the development branch and we can go ahead and
merge it without disrupting 0.D.

**Comment by I-am-Erk** [comment]
>* beasty → beast
That's intentional.

**Comment by KorGgenT** [comment]
> > * beasty → beast
> 
> That's intentional.

should it be "beastie" then?

**Comment by I-am-Erk** [comment]
[I have no strong preference](https://en.wiktionary.org/wiki/beasty).

**Comment by Wuzzy2** [comment]
Just noting: There will be no PR from me, sorry. I am active in a ton of other projects.

**Comment by kevingranade** [comment]
No problem at all, reporting is, well way more than half the battle in this case.
