### ISSUE TITLE
Sugar crafted from wood contains no calories

### ISSUE THREAD

**Issue by jeremyshannon** [CleverRaven/Cataclysm-DDA#28414]
**Describe the bug**  
There exists a recipe to extract sugar from wood pulp using acid. Since the food rework, however, it generates sugar with no calories as the wood and acid inputs don't have any.

**To Reproduce**  
You need cooking 7 and a copy of one of the books, Advanced Physical Chemistry will do.
Then you just need a fire/hotplate and some acid and wood, and presto! Magic calorie-free sugar. 

**Expected behavior**  
Cooking 7 shouldn't let you create a perfect no-calorie sugar substitute with this one weird trick. (Dietitians hate him!) It should produce sugar of the normal calorie count.

**Comment by SwagNaut** [comment]
The same thing happens in #28391, only with burritos.

**Comment by int-ua** [comment]
#28180

**Comment by kevingranade** [comment]
I'm pretty sure this should use NUTRIENT_OVERRIDE, we can't derive the nutrition from inputs if they're inedible.
