### ISSUE TITLE
Coffee pods can't be used to make coffee beans

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [CleverRaven/Cataclysm-DDA#28422]
**Describe the bug**  
When looking at the item browser (https://cdda-trunk.chezzo.com/coffee_pod/recipes/CC_FOOD), coffee pods can be used to create roasted coffee beans. Even after using learn all recipes to see if I can use pods to do anything. There are no crafting recipes associated with it.

**To Reproduce**  
1. Acquire coffee pods via wish or a tree.
2. do a f search in the crafting menu (c:coffee pod)
3. find nothing.

**Expected behavior**  
I expected a method to turn it into coffee beans or roasted coffee beans.

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version: [0.C-37544-gc172ff6]
 - Graphics version: [Tiles]

**Comment by NotFuji** [comment]
This is intentional.  The recipe was removed since coffee plants ( which do not grow in New England ) and coffeetrees ( which do ) are different things.  While you can brew drinks from coffeetree pods, it is not coffee.
