### ISSUE TITLE
Taking off a filthy military rucksack to wield it produces Morale "Filthy Gear" is inconsistent.

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#28425]
0.C-37429-g2365f4b02b-dirty

**Comment by KorGgenT** [comment]
is this the same problem as #27619 ? it's closed because it's supposedly fixed. can you confirm that you've updated your game?

**Comment by l29ah** [comment]
Yes, 6567661e931213b03566f248353bb92bef75215a is in.

**Comment by l29ah** [comment]
Saved game: https://dump.bitcheese.net/files/mytiwon/filthy.tar.xz

**Comment by ifreund** [comment]
Can't reproduce, and that download link seems to be broken.  Can you give the exact command sequence you used to get the message? Not the same problem as #27619, if this gets confirmed its caused by something else.

**Comment by l29ah** [comment]
WORKSFORME. I worn the rucksack, then `i`, then selected it, then `w`.

**Comment by davidpwbrown** [comment]
Can't reproduce in latest master, wielding after wearing removes the morale modifier.

**Comment by l29ah** [comment]
I cannot reproduce it either on the latest master.
