### ISSUE TITLE
Vehicle behavior when transitioning from road to off-road seems off.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#28428]
**Describe the bug**
When going off-road, the reduction in speed causes the difference between cruise speed and actual speed to go very negative, causing the subsequent code to act as though the engine is expending an immense amount of power.
This used to result in extremely high noise levels, but I capped that in #28423 
I suspect this is still doing things it shouldn't, like spiking fuel consumption and causing high strain on engines.

**To Reproduce**  
1. Spawn a vehicle.
2. Get up to 88MPh on a road (not really, just fast er than the vehicle can sustain off-road)
3. Swerve off the road.
4. Engine strain and fuel consumption go crazy, despite the fact that the vehicle is slowing down instead of speeding up.

**Expected behavior**  
Going off-road when moving too fast should probably coast at first as the higher rolling resistance kicks in and then engine load would pick back up again to nominal levels as speed reaches a level the vehicle can maintain when off-road.

**Additional Notes**
The key point seems to be in https://github.com/CleverRaven/Cataclysm-DDA/blob/56d7e98165f09d3445ec137dc19951cceed61e4b/src/vehicle_move.cpp#L154-L162 where it it silently taking the absolute value of the difference between current velocity and cruising velocity instead of refraining from using the engines when the difference is negative.

I'm posting an issue instead of making this change in #28423 because I'm worried about triggering a regression somewhere right before 0.D release.

**Comment by mlangsdorf** [comment]
Probably should be 
```
     if( thd > 0 ) { 
         vel_inc = std::min( vel_inc, std::max( 0, effective_cruise - velocity ) ); 
     } else { 
         vel_inc = std::max( vel_inc, std::min( 0, effective_cruise - velocity ) ); 
     }
```
let me run some tests on that.

**Comment by mlangsdorf** [comment]
Nope, that was bad.
```diff
diff --git a/src/vehicle_move.cpp b/src/vehicle_move.cpp
index 2a24a221ee..e2773b94ec 100644
--- a/src/vehicle_move.cpp
+++ b/src/vehicle_move.cpp
@@ -155,11 +155,12 @@ void vehicle::thrust( int thd )
         int effective_cruise = std::min( cruise_velocity, max_vel );
         if( thd > 0 ) {
             vel_inc = std::min( vel_inc, effective_cruise - velocity );
+            //find power ratio used of engines max
+            load = 1000 * std::max( 0, vel_inc ) / std::max( ( thrusting ? accel : brk ), 1 );
         } else {
             vel_inc = std::max( vel_inc, effective_cruise - velocity );
+            load = 1000 * std::min( 0, vel_inc ) / std::max( ( thrusting ? accel : brk ), 1 );
         }
-        //find power ratio used of engines max
-        load = 1000 * abs( vel_inc ) / std::max( ( thrusting ? accel : brk ), 1 );
     } else {
         load = ( thrusting ? 1000 : 0 );
     }
```
is better - vehicle slow down rapidly when going off-road with busting their engines open.
