### ISSUE TITLE
Keybindings shortcut error

### ISSUE THREAD

**Issue by Solomonome** [CleverRaven/Cataclysm-DDA#28437]
**Describe the bug:**  
After pressing ESC to get to the MAIN MENU screen, there are two ways to open the KEYBINDINGS menu: either by navigating to the menu with arrow keys and then pressing ENTER, or by pressing the shortcut '?' which is supposed to get you to the menu. I tried to get to the menu using both ways, and it seems like a lot of those keybindings disappear when i try the '?' shortcut way.

**To Reproduce:** 
1. Press escape on your keyboard
2. Press '?' on your keyboard
3. You will notice a lot of keybindings aren't there

**Screenshots:**  
![keybindings](https://user-images.githubusercontent.com/47925487/53627682-62b65700-3c09-11e9-8c94-87c93bf904c7.png)

**Versions and configuration:**
 - OS: Fedora 24 linux
 - Game Version: 0.C-37270-g86ec372
 - Graphics version: tiles
 - Mods loaded: default

**_Please do let me know if this has already been fixed and I need to update to a newer game version, thank you!_**

**Comment by ZhilkinSerg** [comment]
Keybindings opened from Escape menu contains keybindings from all input contexts. Keybindings from ? menu probably contains only menu navigation keybindings.

**Comment by Solomonome** [comment]
@ZhilkinSerg thank you for the reply. I understood what you mean, and i tested it a bit more. It makes sense to me, but it may be confusing for some players just because you can access other MAIN MENU screens by pressing the characters next to them, so for example, by pressing ESC and then pressing '4' you get to the color manager, so it would make sense for '?' to move you to the "all keybindings" section. But since '?' is pretty much a global keybinding, it will actually show keybindings for the MAIN MENU :-)

Again, I do understand this, and I hope other players will understand it too.
Thank you again for your reply!
