### ISSUE TITLE
Carnivores get too little nutrition from mixed foods

### ISSUE THREAD

**Issue by halfahermit** [CleverRaven/Cataclysm-DDA#28440]
**Describe the bug**  
With carnivore trait, any food that contains both edible and inedible ingredients has its nutrition halved. This leads to cases like:

- Pemmican w/o carnivore trait: 460 kcal (13 kcal from ingredients inedible to carnivores)
- Pemmican w/ carnivore trait: 226 kcal
- Glazed tenderloin w/o carnivore trait: 616 kcal (12 kcal from inedible)
- Glazed tenderloin w/ carnivore trait: 304 kcal

**To Reproduce**  
1. Craft any food that contains both flesh and vegetable ingredients
2. Look at the kcal count with and without the carnivore trait

**Expected behavior**  
Instead of giving half nutrition, I'd expect inedible ingredients to give 0 nutrition, and edible ingredients to give full or near-full nutrition.

**Comment by kevingranade** [comment]
Extending item representations to the degree necessary for this is a massive amount of work that AFAIK only fulfills this relatively niche goal.
