### ISSUE TITLE
Add query of metadata for crafting components

### ISSUE THREAD

**Issue by Photoloss** [CleverRaven/Cataclysm-DDA#28448]
**Describe the solution you'd like**  
Crafting recipes should allow checking for the numerous properties the component items might have. A simple one would be damage as turning a threadbare jumble of rags formerly known as a trenchcoat into a pristine sleeveless (or survivor) garment makes no sense. My particular use case is a little more complex, wanting to query species and integrity of a monster corpse.

**Describe alternatives you've considered**  
Some individual cases could be worked around, for example "butchering" a chicken might be sped up and yield a "whole chicken" which can then be roasted in one piece or "disassembled" for your regular yield of meat. This will not work in all cases however as for example blacklisting damaged items globally makes little sense if the components are to be shredded for chemical processing.

**Additional context**  
Was pondering how to implement a shocker zombie "battery" which would also require the "breaks_into" vehicle part property to allow spawning of custom items (i.e. the shocker about to revive and taze your rear) but that particular case probably warrants a completely different approach.

**Comment by kevingranade** [comment]
Incoherent
