### ISSUE TITLE
Plum fruit juice has negative calories

### ISSUE THREAD

**Issue by stopple** [CleverRaven/Cataclysm-DDA#28444]
**Describe the bug**  
Made fruit juice from 2 plums

**To Reproduce**  
1. Get 2 plums
2. Make fruit juice using recipe that consumes both

**Expected behavior**  
Fruit juice with >0 calories

**Screenshots**  
![fruit_juice_recipe](https://user-images.githubusercontent.com/19255442/53663677-63b0ae00-3c34-11e9-964f-9347e60d4e88.PNG)
![fruit_juice](https://user-images.githubusercontent.com/19255442/53663684-67443500-3c34-11e9-9a88-b146ec51ad5a.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Win 10
 - Game Version: 0.C-37566-g60ad4a4
 - Graphics version: Tiles
 - Mods loaded: ![active_mods](https://user-images.githubusercontent.com/19255442/53663760-9b1f5a80-3c34-11e9-9de4-d0c9c9f278ea.PNG)

**Comment by SirPendrak** [comment]
Dietetics hate him

**Comment by KorGgenT** [comment]
that's... interesting. i know exactly what's causing this; it's the fruit pulp byproduct.

**Comment by KorGgenT** [comment]
this was fixed in the above referenced PR
