### ISSUE TITLE
Untranslated NPC combat rule notes (and others)

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#28445]
**Describe the bug**
If you tell an NPC to change the combat rules, many strings in the window are untranslated.

First, the combat rule notes at the bottom of the left part are mostly untranslated. And some selectable dialog options, too.

Steps to reproduce
* Use German (which is at 100% now)
* Spawn NPC
* Make NPC your friend, somehow
* Tell NPC to alter combat rules, aim rules, etc.

**Expected behavior**
Everything is translated (non-English).

**Versions and configuration**

OS: GNU/Linux
Game Version: 0.C-37564-g412ee858b5
Graphics version: Terminal
Mods loaded: DDA

**Additional context**
None.

**Comment by BrettDong** [comment]
They are translated now so closing this.

<img width="1072" alt="螢幕截圖 2021-01-08 下午7 23 35" src="https://user-images.githubusercontent.com/21075502/104077258-02ba6f80-51e7-11eb-8af8-20bd10176a50.png">
