### ISSUE TITLE
Searching interactable terrain

### ISSUE THREAD

**Issue by pingpong2011** [CleverRaven/Cataclysm-DDA#28442]
**Is your feature request related to a problem? Please describe.**  
With more trees/bushes/etc being added, it can be hard to spot specific kinds if you don't know what they look like off-hand.

**Describe the solution you'd like**  
Extend the V menu to include environmental things that are examinable/interactable (neither items nor monsters). Don't need terrain itself, just the things on terrain (perhaps placeables too?).

**Describe alternatives you've considered**  
I'm not sure how else it could be done. V is just the easiest menu because you could tab over and filter.

Forests could be diversified, so each section only has a few kinds of trees/fruit, or explicitly different types of "forest" in general, which would basically be the same as above but could be done via map-generation. This might be better so different wildlife could prefer different forest zones.

**Comment by kevingranade** [comment]
Yea, kind of "points of interest", I like it.

**Comment by FONZACUS** [comment]
this would be very nice QOL addition, especially for those with aging eyes. im playing on tiles and i have a hard time guessing which is a shrub, an underbush, fruit tree/shrub, and which are already harvested.

also separate labels would be nice too. which ones are ready for harvest and which are empty.
