### ISSUE TITLE
Part of the key control help in the world creation dialog is lost

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#28447]
**Describe the bug**  
A part of the key control help in the world creation dialog is lost.

**To Reproduce**  

1. Use English w/ default settings
2. Restart
3. Open the “new world” dialog
4. Look at the “green” keyboard help and compare it with sources

**Expected behavior**  
The full string of the dark green keyboard help is shown.

**Actual behaviour**
A part of the string is lost.

The full string is:

> %s = Save Load Order as default.  %s = Controls %s/%s = Prev/Next Option. %s/%s = Prev/Next Tab.

Actually shown is only:

> %s = Save Load Order as default.  %s = Controls %s/%s = Prev/Next Option.

**Versions and configuration(please complete the following information):**
OS: GNU/Linux
Game Version: 0.C-37564-g412ee858b5
Graphics version: Terminal
Mods loaded: DDA

**Additional context**  
None.

**Comment by Night-Pryanik** [comment]
@Wuzzy2 could you please describe in more detail how to reproduce the issue? In my testing I cannot confirm the bug.

**Comment by Wuzzy2** [comment]
It's probably outdated after all these months.

**Comment by Night-Pryanik** [comment]
Ok, I'll close it until confirmed.
