### ISSUE TITLE
Offroad obstacles (bushes) too strong against vehicles

### ISSUE THREAD

**Issue by Xelat84** [CleverRaven/Cataclysm-DDA#28453]
**Is your feature request related to a problem? Please describe.**  
I have a 17 tons armored truck, which could be stopped by hitting few bushes, and after that of course I cannot event start driving through that bushes. I believe it's too much unrealistic.

I can agree there could be the cases with bushes which not allowing you to rise speed above zero, when you rested against the bush. Because those bushes could be big and massive enough, so engine need produce enough energy, and tires should have enough wheel adhesion to offroad.

But 17 tons armored truck running even at 20 kmph have huge amount of kinetic energy to smash almost any bush and don't even feel that.

**Describe the solution you'd like**  
Game should handle energy of vehicle when hitting bushes properly, and not lowering speed too much, if kinetic energy high enough.

Also I believe vehicle wheels while driving should press down long grass and make it common grass, which not lowering your movement by feet. It also could be very useful when you are making your base in the wild. Especially if you have Road Roller.

**Describe alternatives you've considered**  
I open to discussion to find proper solution.

**Comment by kevingranade** [comment]
Please outline in detail how this should work.
If it were simply a matter of doing it "right", we would have done it already.

**Comment by Xelat84** [comment]
Okay, I agree. Let's do some math.
At the moment **1.2 tons** common car losing about 60% of it's energy hitting an underbrush at **26 kmph** - it's about **18 kJ**. It's okay, I'm completely agree with this behaviour. Let's use it as reference - underbrush require to apply **18 kJ** do destroy it.
Now, **17 tons** truck running at **20 kmph** have energy about **262 kJ**, so losing **18 kJ** will lower speed to only roughly **19 kmph**.
So final formula of losing speed should be
`final_speed = max( 0, kJ_to_speed( mass, speed_to_kJ( mass, current_speed ) - 18 ) )`

**Comment by phaethonfire** [comment]
The current code looks like it does alright on the physics. Velocity is calculated using conservation of momentum.  Damage is calculated based on kinetic energy. The hard part is that the mass of terrain objects is estimated from their “bash” values. If there is room for improvement, it is probably in the “terrain_collision_data” function in vehicle_move.cpp. Shrubs have a “SHRUB” flag if they need to be handled differently. There is currently no entry in the JSON giving mass of an object or elasticity or the energy required to destroy it, and adding that kind of info for every terrain type in the game is probably out of scope.

**Comment by Xelat84** [comment]
Of course it's a bad way adding energy to destroy for each terrain object.
Looks like counting "SHRUB" flag should be enough to calculate speed reduction properly.

For now looks like physics works improperly. Hitting a single bush on a 17 tons truck at 24 kmph drops speed to 9 kmph. Second bush after it drops to 1 kmph. It's too much. With 262 kJ of kinetic energy this truck should be able to destroy about 14 bushes one after another to stop completely (and this doesn't even count you are still accelerating).

On the other hand I noticed that Atomic Mini-Tank with 17 tons total mass drops it's speed to 13 kmph after first bush, and after that doesn't feel any other bushes, keeps it's speed around 13 kmph or higher (was driven using only one enhanced electric engine, two others was turned off).
Probably it's somehow related to tires/tracks. But shouldn't. Tires should only affect acceleration (especially on different terrain types).

**Comment by Fris0uman** [comment]
> \- 18 

This will only account for your bush exemple but not anything else, it seems that @phaethonfire is right when he says that you're missing some info about the object you're hitting. 
Maybe json could have info on volume and material and then the game uses that to figure out the rest ?

**Comment by Xelat84** [comment]
I'm talking about bushes (shrubs) only, because offroad full of them. And there only few bush species could be met offroad. And mostly you drive only road or offroad. So fixing at least bushes will cover 99% of cases.
So, if someone disagree with applying 18 to all bush types, then okay, I can count energy value for each bush type. Just let me know, it's not difficult. I'll do that.
I also like idea of making formula based on bash value, and then may be tweak bash value of some bushes (if needed) to meet energy requirement to destroy them.

But I definitely don't expect fixing all the items in the game to apply this formula on vehicle hit.

**Comment by kevingranade** [comment]
Where are you getting the 18kJ from?  Just because an arbitrary collision used it?

**Comment by Xelat84** [comment]
I took it as a reference from current behaviour of `car` vehicle, to not make it worse, because I totally agree how it behave (with `car`). I'd like if someone suggest better option for reference.

**Comment by Tharn** [comment]
This is an annoying issue. Shrubs are bendable and should provide virtually no resistance to a car with *any* momentum. This was somewhat less important when cars were faster off-road, but now that they have to fight their way through the mud, bushes should simply be eradicated without any of this collision nonsense.
