### ISSUE TITLE
Collect Firewood doesn't repeat

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [CleverRaven/Cataclysm-DDA#28455]
**Describe the bug**  
In the description for Collect firewood, it says that it is a 3 hour interval repeated action, which implies that it would be like Gather Materials. However, it only gathers for the first 3 hours before being "Done".

**To Reproduce**  
1. Go to camp manager.
2. Send a companion on both firewood and material gather duties.
3. Wait 3 or more in-game hours.
4. Look at results.

**Expected behavior**  
I expected it to be repeatedly gathering material at the intervals noted in the portion of the notes.

**Screenshots**  
![image](https://user-images.githubusercontent.com/38237593/53680657-3ba46780-3c93-11e9-87a9-782259f591f5.png)
![image](https://user-images.githubusercontent.com/38237593/53680667-60004400-3c93-11e9-846f-e621ce13b3ac.png)
![image](https://user-images.githubusercontent.com/38237593/53680778-e1a4a180-3c94-11e9-801a-a410d56f41ae.png)

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version: [0.C-37564-g412ee85]
 - Graphics version: [Tiles]

**Comment by mlangsdorf** [comment]
Here's the fix:
```diff
diff --git a/src/faction_camp.cpp b/src/faction_camp.cpp
index 075e951ae9..8959438a63 100644
--- a/src/faction_camp.cpp
+++ b/src/faction_camp.cpp
@@ -401,7 +401,7 @@ void talk_function::camp_missions( mission_data &mission_key, npc &p )
                                npc_list.size() < 3 );
         if( !npc_list.empty() ) {
             entry = _( "Searching for firewood.\n" );
-            bool avail = update_time_left( entry, npc_list );
+            bool avail = update_time_fixed( entry, npc_list );
             mission_key.add_return( "Recover Firewood Gatherers",
                                     _( "Recover Firewood Gatherers" ), "", entry, avail );
         }
```
will submit it after the post 0.D backlog clears.
