### ISSUE TITLE
40mm Flechette grenades and 40mm Buckshot grenades have a misleading description

### ISSUE THREAD

**Issue by junkyjb** [CleverRaven/Cataclysm-DDA#28457]
**Describe the bug**  
When firing 40mm Flechette grenades, or 40mm Buckshot grenades, from a vehicle mounted Mark 19 grenade launcher there is no explosion. Only a "You hear Thunk!" message.

**To Reproduce**  
Both grenades are player crafted reloads, using the recipes in "Jane's Mortars and Rocket Launchers" and "Shotguns: The art and science."

I also tested firing them from the Mark 19, without it mounted to a vehicle, and from a player crafted Tube 40mm launcher. Again there was no explosion, but when not vehicle mounted there wasn't even the "You hear Thunk!" message.

Standard 40mm Frag grenades exploded correctly, every time, with each weapon.

I would think I was just being unlucky with miss-fires, as they are reloaded ammo, but they are marked as "this ammo never miss fires" in their description and I fired 8 of them with the same result - in case the description was incorrect.

**Expected behavior**  
A large explosion, as with the standard 40mm Frag grenade.
(Although with more armor piercing on the Flechette variant, and less range on both the Flechette and Buckshot, as per their stats.)

**Versions and configuration(please complete the following information):**
 - OS: Windows 7, 64bit
 - Game Version: 0.C-37566-gdba7ceb  (Build 8555)
 - Graphics version: Tiles
 - Mods loaded: Craftable Gun Pack, Extended Realistic Guns, Modular Turrets, No Antique Firearms.
(The items in the report aren't added by these mods and I've made a quick test world without any mods and the issue still occurs)

**Comment by Leviathan21** [comment]
buck/flechette 40mm are supposed to be used in manner of shotguns

**Comment by junkyjb** [comment]
Ahh, thanks! That makes sense then.

Maybe their description could be changed?
It's currently "A 40mm grenade with an armor-piercing flechette load", and their type is "40mm grenade".

I guess the type can't be changed, as it need to indicate the weapon fired from, but could the description say something like "A large 40mm shotgun round with an armour-piercing flechette load, fired from grenade launchers." or similar?

**Comment by Photoloss** [comment]
*Technically* the terms "buckshot" and "flechette" already specify their nature in this context. One *could* imagine a homebrew "bunch of flechettes/buckshot glued to an IED" type of grenade though so maybe the base type should be named "40mm cartridge" and the term "grenade" reserved for those with a circular AoE yield.

**Comment by junkyjb** [comment]
> One could imagine a homebrew "bunch of flechettes/buckshot glued to an IED" type of grenade 

Exactly, and our current recipe for the normal thrown hand grenade is a tin can, some nails, and gunpowder.
So I just assumed, (incorrectly), that this was a more powerful armor piercing variant, using flechettes for increased shrapnel damage.

I don't think the name needs changing, as it's still fired from a grenade launcher. Just maybe a little more detail in their description to clarify they are effectively a giant shotgun cartridge/shell.

**Comment by kevingranade** [comment]
I agree having grenade in the description is inaccurate and misleading.  Maybe ajust to, "A 40mm shell with an armor-piercing flechette load".

It's not a shotgun though, it's a flecechette round for a grenade launcher.

**Comment by kevingranade** [comment]
Addressed by #28641
