### ISSUE TITLE
Sword bayonet volume is far too high

### ISSUE THREAD

**Issue by Photoloss** [CleverRaven/Cataclysm-DDA#28459]
**Describe the bug**  
The sword bayonet has a volume of 1.75l which due to gunmod mechanics and movecost scaling makes it an incredibly unwieldy weapon when attached to an actual gun.

**Expected behavior**  
According to [this list](http://worldbayonets.com/Misc__Pages/bayonets_by_length/index_by_oal.html) sword bayonets tend to be about 0.5-0.75m long in total. At the current volume this implies an almost 5cm x 5cm cross-section. Approximating a sword blade as 2cm x 0.5cm and the handle as 2cm x 2cm I obtain a total volume of 0.11l for the **largest** sword bayonet listed on that page. 

**Additional context**  
Other melee weapons have excessive volume values as well, for example the longsword has an implied mass density of 0.66g/cm³ where steel tends to be around 8g/cm³. These only need to define their standalone move cost and the space taken up in personal inventory however while the primary intended use of the bayonet requires interaction with the host gun's volume.

**Comment by kevingranade** [comment]
Misunderstanding about what volume means in the game, it is roughly a bounding volume around the item, not precise displacement.
