### ISSUE TITLE
Dehydrating eggs into Powdered Eggs causes a severe reduction in their calories.

### ISSUE THREAD

**Issue by junkyjb** [CleverRaven/Cataclysm-DDA#28463]
**Describe the bug**  
12 portions of chicken eggs at 174 calories each results in 12 portions of powdered egg at 26 calories each.

**To Reproduce**  
Start with 12 chicken eggs, at 174 calories each, for a total of 2088 calories.
Use them to make scrambled eggs 6 times, as the recipe calls for 2 eggs, this correctly results in 12 portions of 174 calories each and a total of 2088 calories.

Take another 12 chicken eggs and dry them into one recipe of powdered eggs, resulting in 12 portions of only 26 calories each.
Adding the water back in to make scrambled eggs, again crafting 6 times, results in 12 portions which retain the that 26 calories each, for a total of 312 calories.  1776 calories have been lost by drying and rehydrating the eggs.

The same happens with 1 ant egg, at 764 calories, which also dries and rehydrates to 12 portions of 26 calories for 312 calories.
And 4 giant spider eggs, totaling 3072 calories, dries and rehydrates to 12 portions of 26 calories too.

**Expected behavior**  
In the real world, when you dry whole eggs to a powder only the water is removed which naturally has 0 calories. The high calorie fat and proteins remain, resulting in a very light and calorie dense powder.

But you don't eat the dry powder, and the game currently has it correctly marked as inedible.
When you re-add the same amount of water that was originally removed the calorie density should return to that of normal eggs.

A realworld 60g egg has around 66 calories, or about 110 calories per 100g.
Realworld powdered egg has around 500 calories per 100g but when you rehydrate it that calorie density is diluted by the water, resulting in reconstituted egg that has around 110 calories per 100g again.

I think that part of the problem occurred in [#22950](https://github.com/CleverRaven/Cataclysm-DDA/pull/22950), where powdered egg was compared to other high calorie edible foods such as nuts and seeds, when it would be more suitable to compare it to other inedible ingredients such as flour and protein powder - which are then "diluted" with water to make bread and protein shakes.

I suggest that 1 portion of powdered egg be given the same amount of calories as 1 portion of chicken egg, as scrambled eggs calls for 2 portions of either. 

This will mean that the inedible powdered eggs will have a very high calorie to weight ratio, as in real life, but when the weight of the water is added back in the edible form will have the same calorie to weight ratio as eggs.

Additionally, 174 calories does seem a bit high for chicken egg, but I assume that is to allow for variance between the sizes of Duck, Chicken, Pheasant and Turkey eggs as the scrambled eggs recipe treats 2 chicken eggs the same as 2 goose eggs?

**Versions and configuration(please complete the following information):**
 - OS: Windows 7, 64bit
 - Game Version: 0.C-37566-gdba7ceb (Build 8555)
 - Graphics version: Tiles
 - Mods loaded:

**Comment by junkyjb** [comment]
Follow up thought: The calories of raw Ant egg and raw Spider egg could probably be adjusted to match 12 bird eggs and 3 bird eggs respectively - as the powdered egg recipe calls for 12 bird eggs, or 4 spider eggs, or 1 ant egg.
This would effectively reduce the calories of spider eggs a little, better matching their description of "fist-sized", and increase the calories of ant eggs - matching their description of "the size of a soft ball" and "Extremely nutritious".
The result being that all powdered egg would have the same calories per portion, no matter the source, while still matching the calories of the raw item before processing.

**Comment by KorGgenT** [comment]
eggs having 180 calories is a bug, they should have 80. 80 is even pretty generous.

**Comment by junkyjb** [comment]
80 sounds good to me, (as bird eggs include duck and goose, which are bigger), and I see your change  makes raw and powdered eggs match - thanks!

Could you also fix spiders eggs to be 3*80=240 and ant eggs to be 12*80=960 too please?
(To match the ratios in the powdered egg recipe, and their descriptions of fist sized and softball sized)

**Comment by KorGgenT** [comment]
fixed in #28518
