### ISSUE TITLE
Stack rotten foods

### ISSUE THREAD

**Issue by KongMD-Steam** [CleverRaven/Cataclysm-DDA#28462]
**Is your feature request related to a problem? Please describe.**  
When comestibles are 'rotten', they do not stack with other rotten foods of the same type. For example, I often see this behavior in my inventory:
a - stomach (rotten) (1)
b - stomach (rotten) (1)

**Describe the solution you'd like**  
Rotten foods stack, no matter what their current rot timer is. In the previous example, the player would see this:
a - stomach (rotten) (2)

**Describe alternatives you've considered**  
N/A

**Comment by DarkDaskin** [comment]
Some rotten items, e.g. said stomach, are still usable in crafting. Thus it makes sense to differentiate them to use most rotten ones first.
