### ISSUE TITLE
active firefighter PBA mask same stats as inactive

### ISSUE THREAD

**Issue by stopple** [CleverRaven/Cataclysm-DDA#28460]
**Describe the bug**  
fighterfighter PBA mask has the same protection attributes regardless of active status

**To Reproduce**  
1. Find a firefighter PBA mask
2. Activate it

**Expected behavior**  
Environmental protection value should increase when active, as the description claims

**Screenshots**  
![pba_mask](https://user-images.githubusercontent.com/19255442/53684694-7bdd0780-3cde-11e9-840e-5187626b5184.PNG)

**Versions and configuration(please complete the following information):**
 - OS: win10
 - Game Version: 0.C-37566-g60ad4a4
 - Graphics version: Tiles
 - Mods loaded: ![active_mods](https://user-images.githubusercontent.com/19255442/53684704-97e0a900-3cde-11e9-94bb-2e6e19edbaea.PNG)

**Comment by Photoloss** [comment]
This is a display bug with the "active" version of the item. Truly inactive states show the stat increase as expected but the active mask shows its own boosted stats in the non-"active" line as well. Also occurs with other "gas" masks (tested with gas, PBA and light survivor) as well as the filter mask but **not** the dive masks.
