### ISSUE TITLE
Maze Runner "Grievers" and mazes

### ISSUE THREAD

**Issue by Solomonome** [CleverRaven/Cataclysm-DDA#28477]
First of all, I know you guys are busy fixing bugs and making the game work properly for the 0.D release. So I don't know if this is the right place to recommend any cool features or ideas right now. Anyway, here's what I was thinking:

Would it be possible to add the "Grievers" from the first Maze Runner movie. I think they're a really unique creature type and would fit nicely into Cataclysm. Even better, creating mazes where those creatures would wonder around killing everything alive, and in the middle of the maze, something very useful and unique for the player to find. It would also be cool if they could drop CBMs because they're like half-mechanical.

I don't know devs, you decide. I just thought it would be a really cool addition.
Thank you for your precious time!

-- 
Sol

**Comment by kevingranade** [comment]
If you feel like making a much more detailed proposal, feel free to do so, but at this level of detail this isn't a meaningful suggestion.
