### ISSUE TITLE
Incorrect stack is selected when moving in AIM from stacks of differing freshness

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#28471]
**Describe the bug**  
When moving perishables from a tile with multiple stacks of the same type wrong stacks are selected.

**To Reproduce**  
1. On the first day of spring wish for multiple chunks of tainted meat.
2. Drop it and wait enough time that it loses `(fresh)` state.
3. Wish for another stack of multiple chunks of tainted meat [with different amount] and drop it to the same tile.
4. Try moving one chunk at a time into inventory from different stacks noting which stack is reduced.

**Expected behavior**  
Items with selected freshness are moved to inventory. 

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 19.04
 - Game Version: 2a443ac (freshest master at the moment of writing)
 - Graphics version: Tiles
 - Mods loaded: default

**Additional context**  
Looks related to #28023

**Comment by Xpyder** [comment]
Here's a save where it's happening near constantly with the Tallow in the fridge.  I've tried 6 times and I can't get the tallow that's past midlife into my inventory to use
[Cinnaminson.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2934343/Cinnaminson.zip)
 it
