### ISSUE TITLE
Can't craft clean water in a basement

### ISSUE THREAD

**Issue by Alapaga** [CleverRaven/Cataclysm-DDA#28472]
**Describe the bug**  
Cooking clean water in a building basement doesn't work

**To Reproduce**  
1. go to a basement with a gallon jug and a plastic bottle that's empty, a Brazier and a frying pan.

2. fill the gallon jug with toilet water

3. Deploy Brazier and put two by fours on it (there's already a firesource on the tile next to it with more two by fours)

4. Light it up using a matchbook

5. bring up the crafting menu, and craft clean water, either a single unit or a batch

**Expected behavior**  

Well i expected to get the prompt to consume/store water in a bottle, like when i crafted this before
a man gotta quench his thirst

**Screenshots**  
I recorded a video with the bug 
[water problem.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2923037/water.problem.zip)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-37580-g24e3f81
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Filthy clothing, Disable NPC needs, Simplified Nutrition, Generic Guns, More locations, Fuji's More Buildings, Disable Religious Texts, No Fungal Monsters, Manual Bionic Installation, Safe autodoc, StatsThroughSkills

**Additional context**  
a savegame that allows the issue to be reproduced.
[manual_backup2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2923043/manual_backup2.zip)

Thank you guys for your attention, keep up the good work!

**Comment by ifreund** [comment]
Should be fixed by #28469.
