### ISSUE TITLE
Spiritual trait is devalued with No Religious Texts mod

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#28475]
**Describe the bug**  
This is not really a bug, but more of a design flaw / balancing fail, I guess.

The trait “Spritual” is devalued when the mod “Disable Religious Texts” is enabled.

The trait gives you moral boost for reading religious texts and “experiencing mystical things”.
However, if the religious texts are removed from the game, this trait is now much less worth.

I don't think this was intentional when the trait / mod was created.

You might claim it's the player's own fault for shooting themselves in the foot and they should just not select Spiritual but keep in mind that the Spiritual trait can still be selected at random.

**To Reproduce**  
1. Start new world
2. Use No Religious Texts mod
3. Use Spiritual trait
4. Find a holy book to boost your morale … oops, there are none!

**Possible solution**
IMO the best solution would be to replace this mod with something different: Instead of just outright removing all religious texts, I suggest to just replace them with generic items, similar to how the “Generic Guns” mod does it.

Maybe use such names like “Holy Book” “Book of Faith”, “Struggles of The Prophet”, etc. Or heck, even come up with some fantasy religions.

**Versions and configuration:**
 - OS: GNU/Linux
 - Game Version: 0.C-37564-g412ee858b5
 - Graphics version: Both
 - Mods loaded: DDA, No Religious Texts

**Comment by int-ua** [comment]
As a skeptic I'm opposed to any religion and I like my game without any mentions of it. So I politely disagree with suggested solution.

With the Illiterate trait you will not benefit from any book, for example. It's precisely players' responsibility to select traits that are needed as you already said.

**Comment by Hirmuolio** [comment]
The No Religious Texts mod could mod the trait. Either remove the trait from character generation or change the description to say that it won't work.

**Comment by DSeyka** [comment]
Spiritual trait also works with religious symbols (including makeshift ones), which the mod doesn't remove.

**Comment by Wuzzy2** [comment]
Look. I get where you're coming from.
But you don't seem to get where I'm coming from. I am complaining PURELY from a balancing perspective. I'm not a defender of religion nor the spiritual realm or whatever. I am a non-believer, too.

My claim is that removing all religious books throws the balance of Spiritual a bit off. It's true, it doesn't make it entirely useless, but still.

> As a skeptic I'm opposed to any religion and I like my game without any mentions of it. So I politely disagree with suggested solution.

Well, there's always the option to burn all those books! Muhaha!

OK, but now for serious: My point in that the mod slightly throws the trait off-balance. The whole point of Sprititual is to give a moral boost that you can gain from certain items. Removing some of those items reduces the usefulness of the trait.

Maybe the “holybook” items could be replaced with something completely different that would have the same effect for the trait.

Unless you also propose to remove the entire idea of spirituality from the game. This would also be a valid way to fix the balancing problem. However, it would strip players from a useful moral booster. If that's what you want, maybe replace the idea of the Spritual trait with something completely different that basically has the same effect?

But if we take your approach to the extreme then a whole bunch of backgrounds and even the church and cathedral have to be removed as well. This wouldn't really fit to New England then, however. Also, entire NPC quest trees would have to be rewritten or removed.

> Spiritual trait also works with religious symbols (including makeshift ones), which the mod doesn't remove. If you choose action -> meditate on these items, you get a better morale boost.

Yes, it works with religious symbols. But it is untrue they give a better morale boost. With the holy symbol (makeshift or not) you only get up to +10 morale (2 uses or more), but with reading a “holybook”, you get up to +45 morale (3 reads or more). This is a significant difference! That's why I am so concerned about “throwing off the balance”.

> With the Illiterate trait you will not benefit from any book, for example. It's precisely players' responsibility to select traits that are needed as you already said.

But Illiterate is a negative trait, but Spitiual is a positive one. This argument is thus pointless.
I don't think it was intentional to make Spritual as a lesser useful trait, it's just a bad and possibly unintentional side-effect of the No Religious Texts mod.

> The No Religious Texts mod could mod the trait. Either remove the trait from character generation or change the description to say that it won't work.

Removal is an option (but then it must be clearly mentioned in the mod desc.). As said before, it's not true that the trait won't work at all.

**Comment by DSeyka** [comment]
What Spiritual (as a trait) does:
- gives you morale boost from reading certain books, which is a generic fun_to_read bonus. You only get it if the book IS_INSPIRATIONAL, and you have the trait.
- gives you ability to meditate over the holy symbols, which gives you +5 - +10 morale and has a 2000 turns cooldown.
- has some intertwining with cannibalism, but that's spoiler territory.  

The mod is specifically called "Disable Religious Texts", is working as intended, and the trait is still useful even with the mod enabled.

**Comment by kevingranade** [comment]
Mods are not balanced. 
If you decide to enable ANY mods, the game is no longer balanced.
I'm not interested in adding any special support to tweak the game more extensively to balance arbitrary mods.

**Comment by Night-Pryanik** [comment]
For what it's worth, it's the mod that could (should be?) be modified, not the trait.

**Comment by Wuzzy2** [comment]
Yes, this issue is about fixing the mod's balance, and ONLY the mod.

Well, all mods are shipped by default, so I'm really not happy with the “I don't give a shit about quality” attitude.
And saying that any mod will destroy game balance suggests that there is something seriously rotten about the mod concept in the first place. One might believe that imods should at least try to not break the game balance.
To me, it makes zero sense to KNOWINGLY ship low quality or poorly-thought out mods with the game. Either remove them or fix them. Send the mod makers back to the drawing board, if neccessary.

**Comment by Wuzzy2** [comment]
BTW, I agree that mods should align to the game, not vice-versa.

**Comment by Night-Pryanik** [comment]
I guess we care only about default mods. For now they are Filthy Clothing, Simplified Nutrition, and Disable NPC Needs.

Mods shipped with the game are not officially supported or officially recommended, at least I think so. They were added based on the "Why not?" principle. If they work while generating no errors, they could be added in the "official" game bundle, nothing else. Their quality depends mostly on their maintainers (if any).

Though personally I'd remove most of the mods from the bundle. Authors can always place them in some special appropriate place like nexusmods.

**Comment by kevingranade** [comment]
There *is* something seriously rotten about all the "remove bla content for the game" mods. The rationale for them is beyond shaky, and they DO screw with game balance indiscriminately, partially because they don't have an in-game rationale, but a personal one. This is why I'm dismissive about "fixing" them, the fix is not to use them, they're dumb.

Regarding removal:
The rationale for keeping mods *in general* in the main repository is so that they can be kept in sync in case things like, "we're adjusting how weight is calculated, or how calories are determined" happen, it makes it easier to mechanically keep everything together.  This doesn't apply to content removal mods though, so the rationale for keeping them in the main repository is quite tenuous.

Especially since the launcher is a thing now, I'd be totally happy for them to all go live elsewhere.

**Comment by DSeyka** [comment]
If we're going this route, we should also mainline the mods which are currently enabled by default.

**Comment by kevingranade** [comment]
Do you mean you want to un-mainline mods that are NOT enabled by default?  And why do you think that's a good idea? I already outlined why they are maintained together, and that only content blacklisting mods are different.

**Comment by DSeyka** [comment]
By mainlining, I meant to incorporate them at the source level, so they're part of the core experience rather than enabled-by-default mods.  
Then again, doing so would mean less options to customize the game, so maybe not such a good idea after all.

**Comment by Night-Pryanik** [comment]
> Then again, doing so would mean less options to customize the game, so maybe that's not such a good idea after all.

Those who want to customize their game still can get mods from somewhere else.

**Comment by Night-Pryanik** [comment]
> I can also help with setting up CDDA mods repository on Nexus, if need be.

It would be cool, especially when CDDA repo on Nexus already exists - https://www.nexusmods.com/cataclysmdarkdaysahead. I guess blacklist mods removal could be started right after the 0.D.

**Comment by DSeyka** [comment]
Huh, I couldn't find CDDA via Nexus's search engine (maybe the game isn't popular enough?), but that's even better. I'll upload relevant stuff as soon as we hit 0.D and I can confirm they're still compatible.

**Comment by Wuzzy2** [comment]
Maybe change the mod so that instead of just removing all religious texts, just replace the religious texts with one generic “holy book”?
This would at least keep gameplay (mostly) intact.
