### ISSUE TITLE
Cutting up laundry basket gives too many plastic chunks

### ISSUE THREAD

**Issue by Lum4r** [CleverRaven/Cataclysm-DDA#28476]
**Describe the bug**  
Cutting up a laundry basket gives about 100 plastic chunks

**To Reproduce**  
1. Start a game with any character
2. Wish for a laundry basket and a cutting tool
3. Cut up the basket

**Expected behavior**  
It should give you a more reasonable amount based on the 20 chunks it takes to make one

**Screenshots**  
![image](https://user-images.githubusercontent.com/5982057/53696504-7c84a500-3d95-11e9-86e0-4ad7fea01cf6.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-37582-g2a443ac
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs, Filthy Clothing, Simplified Nutrition

**Comment by DSeyka** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/27478
https://github.com/CleverRaven/Cataclysm-DDA/pull/28009
This was supposed to be fixed already, looks like it wasn't, or there was a regression.

**Comment by davidpwbrown** [comment]
That fix seemed to only add a disassembly recipe with a sane yield.
It did nothing for the cutting up yield, which is hardcoded, and needs to be based on weight, not volume.
