### ISSUE TITLE
Impossible open palisade gate tiles in house

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#28479]
**Describe the bug**  
There's a house with many “impossible” open palidade gate tiles (`t_palisade_gate_o`).
These tiles are placed in such a way that they don't make sense. There are only these gate tiles but no corresponding palidade tiles to which they “attach”.
The way these tiles look like makes me assume these tiles were intended to be normal dirt tiles instead.

This bug is very visible in the Tiles version.

Note: For some reason, the in-game name of the tile is just “Dirt” which seems a bit confusing.

**To Reproduce**  
1. Generate the house until you find the correct one. Sorry, I have no idea how to reproduce it better.

**Expected behavior**  
The house in question should not have any palisade-related tiles whatsoever.

**Screenshots**  
![Screenshot of the offending house](https://ptpb.pw/ZxiR.png)

The `t_palisade_gate_o` tiles are at the outside, these strange wooden things.

(ignore the sign, it was not part of the house)

**Versions and configuration(please complete the following information):**
 - OS: GNU/Linux
 - Game Version: 0.C-37564-g412ee858b5
 - Graphics version: Both, but it's more visible in the Tiles version.
 - Mods loaded: DDA

**Additional context**  
N/A

**Comment by Throwaway-name** [comment]
detached_house.json line 120

**Comment by Night-Pryanik** [comment]
I guess this open palisade gates could be just removed. To me they completely make no sense, even it we suppose that this is just a typo and there should be palisade wall instead like this:

![default](https://user-images.githubusercontent.com/11132525/53716788-74009d00-3e6f-11e9-8547-97765bdc2077.png)

**Comment by Wuzzy2** [comment]
It seems other houses are affected as well if you search for `t_palisade_gate_o` in `data/`.

I agree, all those weird palisade gate tiles should be replaced with dirt, then it would make sense.

**Comment by int-ua** [comment]
Fixed: https://github.com/CleverRaven/Cataclysm-DDA/commit/e803fc75b36ae6b170535e390da2300278817eb5
(AFAIU the mentioned PR had some unrelated changes but Kevin merged just the needed commit)

**Comment by Wuzzy2** [comment]
> I was also able to find t_palisade_gate_o in these files:
> 
> `json/mapgen/house/house_vacant.json` (2 times)
> `json/mapgen/trailer_park.json` (1 time)
