### ISSUE TITLE
Add bar door tile.

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#28483]
Right now in bars and other buildings where is no real bar door tile, instead it uses wooden gate tile from outside, which has dirt uder it, and it is also painted in white. It do not gell at all with the wodden counter next to it. I suggest adding proper bar doors tiles in the game, and replace all wooden gates inside buildings with them.

**Comment by Night-Pryanik** [comment]
> it is also painted in white

It could have been painted in other colors in different tilesets.
