### ISSUE TITLE
Volume control for ambient sounds?

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#28480]
**Is your feature request related to a problem? Please describe.**  
Ambient sounds are too loud and can't be controlled.  They literally hurt my ears when other sounds are at a reasonable volume.

**Describe the solution you'd like**  
They should have a volume control slider

**Describe alternatives you've considered**  
A way to disable ambient, but I like most of the ambients so volume control would be better

**Additional context**  
Also I F*ING HATE CICADAS, it would be nice to be able to mute them in game rather than needing to turn sound off and completely relaunch the game.  If you like them fine, but I can't stand them.

**Comment by kevingranade** [comment]
> Also I F*ING HATE CICADAS

Edit your soundpack.

A global ambient volume adjustment, either within the soundpack configuration or  innannin-game menu is reasonable.

Auto-normalization would also work.

**Comment by cburns2017** [comment]
Working on a fix
