### ISSUE TITLE
Rename t_palisade_gate_o tile to “open palisade gate”

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#28489]
**Is your feature request related to a problem? Please describe.**  
The tile `t_palisade_gate_o` (opened palisade gate) is called “dirt” in-game. But this description is a little misleading. And in console version, the symbol also looks identical to the “real” dirt tile. More confusion is added when the extended description of the tile clearly mentions the existence of a hanging palisade gate.

This is a little confusing and also inconsistent. Many open door tiles have a clear desciption like “open door”, but not this tile.

**Describe the solution you'd like**  
Rename the `t_palisade_gate_o` tile from “dirt” to “open palisade gate”.

**Describe alternatives you've considered**  
None.

**Additional context**  
None.

**Comment by Night-Pryanik** [comment]
Closed by #28492.
