### ISSUE TITLE
NPC stay allied with other characters

### ISSUE THREAD

**Issue by pescepalla** [CleverRaven/Cataclysm-DDA#28487]
NPCs remain allies after death. If, after death, I start again with a fresh character in the same world, old allies will still treat my new character as a friend.

**To Reproduce**  
1. Create a world and a character.
2. Become friends with an NPC.
3. Die and keep the same world.
4. Create a new character and go meet the NPC.

**Expected behavior**  
The NPC should act as if he'd never met you. The old character died and you are interacting with him as a new character.

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux
 - Game Version: 0.C.2016.03.12-1
 - Graphics version: Terminal
 - Mods loaded: Default

**Comment by CoroNaut** [comment]
Connected issue: #27293
