### ISSUE TITLE
"Place Brazier" option disappeared

### ISSUE THREAD

**Issue by Solomonome** [CleverRaven/Cataclysm-DDA#28486]
**Describe the bug:**
After crafting a brazier, I wanted to place it right next to my character. I opened the construction menu and I didn't find the "Place Brazier" option. I thought that option was there before?!

"Place Still" and "Place Forge" still exist, and I don't know about other items, because i'm pretty new to the game itself.

**To Reproduce:**
1. Start a game
2. Open the construction menu by pressing *
3. Try to look for the "Place Brazier" option

**Versions and configuration:**
 - OS: Linux
 - Game Version: the latest linux64 build (0.C - 8563)
 - Graphics version: tiles
 - Mods loaded: default

**Comment by Night-Pryanik** [comment]
Now brazier is `a`ctivable.
