### ISSUE TITLE
Add extended description for more non-obvious tiles

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#28497]
**Is your feature request related to a problem? Please describe.**  
There are some tiles in the game that are not too self-explanatory and would thus benefit from an extended description. Many tiles are still lacking one, or the current extended description isn't that good so far.

**Describe the solution you'd like**  
Write an extended description for most tiles and describe how the “interactive” tiles can be used. Some tiles are a bit more complicated and are only useful in combination with other ti

The description should reflect:

* For interactive tiles: How they work and how they can be used (most important). Also, if it applies: how they interact with other tiles (example: fuel console)
* For machines and apparatuses that can't be used (like the arcade machine): Say in description that these are “broken”. Also maybe say what their pre-Cataclysm use was, in 1 sentence
* For furniture: (roughly) what they are made of (implications for deconstruction)
* For all tiles: What they are
* For all tiles: Whatever you write, write it spoiler-free

**High priority tiles**
- t_cvdmachine
- t_atm
- t_slot_machine (ext. description should explain the game, with all possible winnings and chances)
- t_gas_pump*
- t_diesel_pump*
- t_radio_controls
- t_marloss*
- t_radio_tower
- t_console
- t_gates_control*
- t_centrifuge
- t_manhole*
- t_card
- t_plut_generator

Tiles that might need an improvement:

* mailbox (“You've got mail.” is false)
* f_arcade_machine (cannot be used)
* f_pinball_machine (cannot be used)
* ball machine (cannot be used)
**Describe alternatives you've considered**  
None.

**Additional context**  
None.

**Comment by Night-Pryanik** [comment]
> Some tiles are a bit more complicated and are only useful in combination with other ti

Unfinished phrase.

**Comment by Wuzzy2** [comment]
Some tiles are a bit more complicated and are only useful in combination with other tiles.

**Comment by DracoGriffin** [comment]
Yeah, I went through quite a bit of terrain awhile back, and wanted to clarify.

As in #23335, I tried to make descriptions quite neutral and informative without necessarily breaking the 4th wall *too much*.

Are you in line with this type of description:
https://github.com/CleverRaven/Cataclysm-DDA/blob/56e17d7ac9b79130296e7cb2567e0bf1bc0072b5/data/json/terrain.json#L2642

Or are you asking for more of a detailed description that *literally specifies* `Use the examine hotkey on this tile to prompt for closing/opening curtain or tear down curtains for two sheets, long string and sticks.`

It'd be great if you could give examples that you feel are appropriate or meeting what your expectations are.

**Comment by Mooses2k** [comment]
I've basically finished this issue and I'll put a PR for it shortly. My style for some items is a bit colorful, though. I think there's a lot of good, simple, helpful stuff covered, though.
