### ISSUE TITLE
Giant naked molerats, labs, and Z-levels

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#28503]
**Is your feature request related to a problem? Please describe.**  
I'm always frustrated by the fact that labs typically come with at least one giant naked molerat. This wouldn't be too big an issue, except I also play with Z-levels on, meaning they're active no matter what. This results in large segments of the lab being destroyed if I leave them alone (and they're also quite loud).

**Describe the solution you'd like**  
I don't think removing the molerats is a good solution, though I admit a blacklist mod would be a great temporary workaround. I think the better solution would be to make them a bit less dig-happy, really.

**Describe alternatives you've considered**  
This might just be something that pisses me off, and others have learned to deal with. All I know is that my first order of business in a lab start is to find the molerat and either kill it with a gun turret, or lead it into a slime pit to make it something that won't tear up the lab.

**Additional context**  
Is this even a thing to worry about? Should I be concerned about this, or should I just suck it up and blacklist molerats at the start of the game, turning that off later? I dunno.

**Comment by curstwist** [comment]
Yeah, killing the mole rat is priority number 1 if you use experimental z levels, otherwise you have a good chance of them destroying a significant portion of the lab and releasing the shoggeths/migos.  

It is a challenge though, so I like the first idea, a way to slow their digging some.

**Comment by int-ua** [comment]
Additionally I think the fact that they dig concrete and rocks instantly is completely off. Imagine giving a couple of diamond drills to a rhino or an elephant and making them dig. It would still take quite a while. The only instant digging tool known is explosives currently. Do the molerats have a mutation where they secrete diesel and ammonium nitrate and have a blast shield? Okay, I don't really mind if they do, let there be dragons, but let's create these explosions at least.

**Comment by int-ua** [comment]
I do not really mind making labs harder. But not with monsters that destroy every tile instantly just by moving to any loud noise.

**Comment by DracoGriffin** [comment]
Related: #23814

Additionally, they were designed in mind to disrupt the static lab gameplay --- it was very easy to go through labs without too much issue or threats as long as you went slowly and methodically. For a late-game location, that doesn't feel right and GNMR make it much more dynamic; areas that may have been safe are now much more dangerous as the walls have collapsed and turrets have LoS on larger areas or particularly deadly specimens have been released (GNMR wouldn't be intelligent enough to determine if some sounds are deadlier than others).

Hulks and turrets can make short work of them, so in essence, they'll eventually run into a deadly target and die (even more so if it was shoggoth).

I don't believe there is an option to reducing the speed of their tunneling but would probably be more appropriately.

Z-level tunneling and reducing tunneling speed would be ideal goals for this creature.

**Comment by kevingranade** [comment]
Another option for tuning their impact is making some walls immune to their
burrowing.

**Comment by MrOlaf** [comment]
Naked Giant Mole Rats are fine as is, but it's more about them burrowing up/down through floors with experimental z-levels on as they can damage several tiles for no really good reason. Based on Wikipedia real-life molerats eat roots and tubers, is there a way to make non-stone/dirt tiles less attractive to the Giant Naked Mole Rat?
