### ISSUE TITLE
Crossbow gets pulled from hands

### ISSUE THREAD

**Issue by Feufollet62** [CleverRaven/Cataclysm-DDA#28502]
Description:
While shooting zombies from afar, the crossbow is pulled from the player's hands seemingly at random. It either goes in a monster's inventory or on an already dead enemy. 

Reproducing:
-Get a crossbow and bolts
-Shoot zombies until it happens

Expected:
Crossbow shouldn't be pulled from hands at all, as it's not a piercing weapon.

 - OS: Windows 10
 - Game Version: 0.C-37599-gdrcafd3
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs, Simplified Nutrition, Craftable Gun pack, Safe Autodoc, Bright nights, DeadLeave's Fictional Guns, More Survival tools, medieval and Historic Content, Mutant NPCs, Beta National Camp, More locations, Fuji's more buildings, Oa's additional buildings mod, Urban Development, Classes and Scenarios Mod, Classic Roguelike Classes, Manual Bionic Installation, StatsThroughSkills

**Comment by Night-Pryanik** [comment]
Most probably it's the zombie technician. It has a bionic that allows him to pull metal items from afar.

**Comment by Solomonome** [comment]
I ran a test by spawning a common zombie and was able to kill him normally without any pulling. After that I spawned a zombie technician and he first pulled out my composite crossbow from my hands and then after some time, he pulled the bolts too. So, most probably there was a zombie technician in the group of zombies you saw in the game.

**Comment by Night-Pryanik** [comment]
I guess this could be closed then.
