### ISSUE TITLE
Dissectors don't harm zombies

### ISSUE THREAD

**Issue by pescepalla** [CleverRaven/Cataclysm-DDA#28504]
**Describe the bug**  
Dissectors fail on occasion to harm zombies.

**To Reproduce**  
1. Lead a zombie into a dissector. 
2. According to the wiki, it should deal 60 damage to the zombie, but in some cases the zombie remains uninjured even after getting the message "Electric beams emit from the floor and slice the ... flesh". It happened twice: once with a Bio-operator and once with a Soldier.

**Expected behavior**  
Dissectors should damage zombies.

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux
 - Game Version: git master
 - Graphics version: Terminal
 - Mods loaded: default

![screenshot_2019-03-05_15-43-58](https://user-images.githubusercontent.com/46329185/53813621-53fbd700-3f5e-11e9-8fbb-0614ef7c086b.png)

Save game: https://mega.nz/#!IgYyHC4S!aEvAigWXbnY-u7B9oSVnmdUrKKFPsts0P5jutOhpaUA

**Comment by Ivan-Shestakov** [comment]
I think soldiers and bio-ops have too high armor rating to be damaged by dissectors... I've successfully fried regular zombies and the lab challenge-newcomer-greeter brutes on them.

**Comment by pescepalla** [comment]
Right, that might be it. Cheers!
