### ISSUE TITLE
monster speed setting isn't working

### ISSUE THREAD

**Issue by nsklaus** [CleverRaven/Cataclysm-DDA#28523]
**Describe the bug**  
monster speed setting isn't working

**To Reproduce**  
set monster speed to 1%
1. see the monster outpace you

**Expected behavior**  
i expected the setting to work. 
i tried 30% speed, i was still getting outpaced by monster, being caught and killed.
then i tried 10%, same result. i tried 1% same result.
at 30% i thought they would be really slow.
at 1% speed i expected them to be pretty much static.

**Versions and configuration(please complete the following information):**
 - OS: [Ubuntu 18.10]
 - Game Version: [0.C-37605-g7a48668]
 - Graphics version: [Tiles]
 - Mods loaded: [vanilla]

**Additional context**  
this is the latest build: cataclysmdda-0.C-8569.tar.gz  (not my own build)

update:
----------
edit: ok, it works but require a world reset, this should be added to the option detail text.
otherwise the user doesn't understand why the setting seems to have no effect until he try a world reset.

**Comment by davidpwbrown** [comment]
Can not reproduce on development branch, monsters are static with speed set to 1% on my build - which is will try with 0.D master now.

**Comment by davidpwbrown** [comment]
ah yes, the world default options are applied on world creation, they will often have no effect when applied on an existing world.
