### ISSUE TITLE
idea to reduce  message log spam

### ISSUE THREAD

**Issue by nsklaus** [CleverRaven/Cataclysm-DDA#28526]
**Is your feature request related to a problem? Please describe.**  
message panel is often filled with the same output over and over again

**Describe the solution you'd like**  
do not print a given message if it is still in the visible output of the message panel. 
so like in the screenshot below, if the message " moving through long grass is slow" is still being visible on the message panel, do no print it again until it has been moved out of visible area by new messages. no need to repeat something if it is already visible on the message panel.
so before printing message, make a check to see if it not already printed in the last 20 lines or whatever the height of the message panel.
so in the screenshot below, this message should be printed just once. and never again until it went off visible message area, pushed away by other new messages. just because you made that check i'm suggesting. 

**Additional context**  
![screenshot_20190306_225800](https://user-images.githubusercontent.com/6810861/53917040-f2259500-4063-11e9-8335-df95fe1596b8.png)

**Comment by Photoloss** [comment]
The suggestion will not catch all instances as for example fish will include their name in the "leaps from the water" message spam. Meanwhile too aggressive culling may start omitting things like damage reports.

Unfortunately a few messages *can* be spammy but definitely need to be reported exactly under different circumstances, for example zombies mashing up a vehicle in town during daytime will quickly pile on the "the [vehicle]'s [component] is destroyed" messages which gets old real fast but if I were stood next to my own ride I'd definitely want every little scratch reported even when I'm not currently driving or grabbing it.

For messages where the exact text is repeated it's easy to append a "xN" and change the colour, but what would you do if stood in a field of many different bush types?

**Comment by nsklaus** [comment]
it would be easy to make a blacklist of messages that don't need to get printed all the time, 
while letting all other kind of messages pass as usual.
example: 
if the string is about long grass being slow : perform the check 
(is the message already printed in the last 20 lines ? if yes: don't print / if no then print it )
else, if it's any other kind of message, not in the blacklist, just print it, don't perform the check.

**Comment by CoroNaut** [comment]
The point of the message log is to record your movements and surroundings chronologically, if the chronological part of that is tampered with, messages will start to be much less meaningful.

**Comment by nsklaus** [comment]
@CoroNaut 
you're sure about that ? i would have swore the message log was a place to cook pizzas.
what make you think i wanted to hear what you personally think the message log is for ?
if you want to make your opinion heard open your own issues, and don't come in other's.
and if you must come into other's issues, do it to help, instead of telling them they completely miss the point. now please go fuck yourself elsewhere. thanks.

**Comment by nsklaus** [comment]
same goes to you photoloss, take your little thumbs up and down and go put them where they belong.
(in case i'm not clear enough that's your ass)

**Comment by CoroNaut** [comment]
The issue has specifically the tag "<Suggestion / Discussion>", and as I believe the original post would indeed be a quality of life improvement, I wanted to share the main invariant for the message log. Whether you already know this or not, you also have the ability to ignore my message altogether, or take the information and formulate another solution with it in mind.

**Comment by I-am-Erk** [comment]
Nsklaus, the purpose of the GitHub issues section, especially when discussing changes, is to discuss changes. If you can't accept a differing opinion politely I'm not sure how you can work on a collaborative project.

**Comment by nsklaus** [comment]
i'm not asking for others opinions. 
i offer an idea. take it or leave it.
others can share their opinion on their own threads, here i'm not interested in their little thumbs up and down games, or their trisomic view of the world. 

and if that's how it's gonna be, each time i try to contribute i get talked to by morons telling me i miss the point, i'm doing it wrong, i'm evil, my ideas are shit, or how they view the world and how their view is waay better than mine, then i really shouldn't try to help this project anymore.
..why am i loosing my time trying to explain such things again.. i'm out. this community is shit.

**Comment by I-am-Erk** [comment]
Yeah... "i offer an idea. take it or leave it" is not compatible with a collaborative project. If that's your idea of how to work together on a project, it is definitely for the best that you leave. We have no use for that whatsoever.

**Comment by davidpwbrown** [comment]
The irony is, a modification or tweak of the original issue, would not be a bad thing, message spam reduction has been discussed by the devs.
But... wow.. .. yeah I'm not gonna say too much about what happened next, but it's a shame, maybe someone else who can discuss things rationally like an adult can propose a fix to message log spam.

**Comment by Eschar** [comment]
Nsklaus is bailing out while reviling the "shit community," and has closed the issue. But could someone open an identical issue request? I don't think *I* should, as I'm not familiar enough with the requirements for and workings of the message log.

**Comment by I-am-Erk** [comment]
I could, in fact I thought I already had.

Yeah.
https://github.com/CleverRaven/Cataclysm-DDA/issues/28215
