### ISSUE TITLE
monster resilience setting isn't working

### ISSUE THREAD

**Issue by nsklaus** [CleverRaven/Cataclysm-DDA#28525]
**Describe the bug**  
monster resilience setting isn't working

**To Reproduce**  
set monster resilience to 1%
1. see the monster being as strong as usual.

**Expected behavior**  
i expected the setting to work.
at 1% resilience i expected sneezing on them would be enough to kill

**Versions and configuration(please complete the following information):**
 - OS: [Ubuntu 18.10]
 - Game Version: [0.C-37605-g7a48668]
 - Graphics version: [Tiles]
 - Mods loaded: [vanilla]

**Additional context**  
this is with build: cataclysmdda-0.C-8569.tar.gz  (not my own build)

update:
----------
edit: ok, it works but require a world reset, this should be added to the option detail text.
otherwise the user doesn't understand why the setting seems to have no effect until he try a world reset.

**Comment by davidpwbrown** [comment]
Can not reproduce on development branch, monsters are as weak as expected with resilience set to 1% on my build - will try with 0.D master now.

**Comment by davidpwbrown** [comment]
ah yes, the world default options are applied on world creation, they will often have no effect when applied on an existing world.

**Comment by nsklaus** [comment]
@davidpwbrown  
in other word, there is a setting that doesn't work 99% of the time.
it only work upon world creation or world reset. and it is not specified in the setting description.
so user is left with the idea it just doesn't work. 

this game suffer a lot from such problems.
in a lot of areas. 
player needs to either know the source code, 
or are used to the quirks and problems and know how to work around them.
the user feedback is often missing, it is not good enough.

**Comment by Night-Pryanik** [comment]
@nsklaus I've updated descriptions for both options.

**Comment by nsklaus** [comment]
@Night-Pryanik 
thank you. 
little details like that don't look like much, but they are important.
