### ISSUE TITLE
Auto Forage doesn't pick cattails

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#28535]
**Describe the bug**  
Auto-forage ignores cattails

**To Reproduce**  
Turn on auto forage, walk around cattails. Observe.

**Expected behavior**  
Cattail pickin'

**Versions and configuration(please complete the following information):**
 - OS: Win 10
 - Game Version: 0.C-37608-g84fdfd2 (tiles)

**Comment by I-am-Erk** [comment]
I'd like cattails to regrow if we add this

**Comment by anothersimulacrum** [comment]
If this does get added, we should probably also auto-forage berry bushes and fruit trees.

**Comment by Night-Pryanik** [comment]
Game options explicitly states that it is possible to forage only trees or bushes. And what type (trees or bushes) cattail can be attributed to?

**Comment by Zireael07** [comment]
I'd see no issue with cattails and berry bushes be lumped in with bushes.

**Comment by Night-Pryanik** [comment]
I made a PR already, was asking just for fun.
