### ISSUE TITLE
Secubots never run out of ammo while you wait

### ISSUE THREAD

**Issue by pescepalla** [CleverRaven/Cataclysm-DDA#28537]
**Describe the bug**  
In the bottom Lab Challenge rooms there are often Secbots and a reinforced glass panel. I hide behind the glass and let the Secbots waste their ammo. Repeatedly pressing "." results in the bots eventually running out of ammo. Instead, the Secbots never run out of ammo pressing the "|" (wait 300/1800 heartbeats) even though it looks like they're shooting all the time.

**To Reproduce**  
1. Spawn at the bottom of a Lab where there are Secbots and a glass panel.
2. Hide behind the glass. Press "." to wait one turn. Secbots start shooting ineffectually.
3. Wait for 1800 heartbeats with "|". Notice the Secbots firing sprite.
4. Wait one more turn.
4. Secbots still have ammo and keep shooting.

**Expected behavior**  
Waiting with "|" should also let Secbots waste their ammo.

**Screenshots**  
![screenshot_2019-03-07_18-24-08](https://user-images.githubusercontent.com/46329185/53975924-3bc6bc00-4106-11e9-8832-cd5d15d0482f.png)

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux 
 - Game Version: git master
 - Graphics version: Terminal
 - Mods loaded: default

Savegame: https://mega.nz/#!sg5GUYLb!Fva8Aq8Ir4XSjJpvhKS5rs9JnXs8EMhDWBZ4OcMyO3M

**Comment by spacenookie** [comment]
as far as I can tell if the animation plays the ammunition count should be properly updated.

could be 100% wrong on this, but it looks like secubots spawn with 100 rounds of ammo and only fire a couple of times per minute. if you are at range 7-12 they only fire single shot. so it might be that it just takes 50 minutes (3000 heartbeats) or more to use up the ammo.

**Comment by pescepalla** [comment]
Damn, you're right!
