### ISSUE TITLE
This is a nothing

### ISSUE THREAD

**Issue by Gmiz** [CleverRaven/Cataclysm-DDA#28549]
**Describe the bug**  
I don't know how, or why nothing exists there, but it was there, without me changing any saved world data.
![nothing](https://user-images.githubusercontent.com/47925487/54011381-9f86ce80-4172-11e9-8c46-be657ee98ea7.png)
Maybe a way to fix this would be to check for all the blocks in the current refresh area and replace those kind of tiles with ground or something.

**To Reproduce**  
I have no idea how this happened unfortunately.

**Expected behavior**  
There should be a tile there.

**Versions and configuration:**
 - OS: GNU/Linux
 - Game Version: 0.C linux64 build 8555
 - Graphics version: tiles
 - Mods loaded: default

**Comment by SomeDeadGuy** [comment]
I've also encountered n҉̀ơ͝t͞h̢̀ing̀ in the same place. Someone made a mistake with the building layout.
Make screenshot of the whole building, so people can recognize it.

**Comment by Solomonome** [comment]
Ok, so the house looks like this:
![nothinghouse](https://user-images.githubusercontent.com/47925487/54068996-f82d9880-4252-11e9-87c0-715124030326.png)
and there is a couple of things I found weird about it:
1. It's a wooden house with metal doors?
2. There is a "nothing" tile I showed earlier
3. Windows don't have curtains on them (it's ok if it's intended)

**Comment by KongMD-Steam** [comment]
I think it's this house:
https://github.com/CleverRaven/Cataclysm-DDA/blob/03b0f91abbc47bb19280bf5bda9f762cd99476a5/data/json/mapgen/house/house_vacant.json#L801

**Comment by Throwaway-name** [comment]
@KongMD-Steam 

Blank space next to the c:
https://github.com/CleverRaven/Cataclysm-DDA/blob/03b0f91abbc47bb19280bf5bda9f762cd99476a5/data/json/mapgen/house/house_vacant.json#L805
