### ISSUE TITLE
Not receiving benefits from mutation

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#28543]
**Describe the bug**  
A stat enhancing mutation is not increasing stats.

**To Reproduce**  
1. Get stat enhancing mutation.
2. See that it does nothing.

**Expected behavior**  
Mutation should do what it says it does.

**Screenshots**  
![untitled](https://user-images.githubusercontent.com/45204409/53996971-bd384180-413a-11e9-9090-35934f130b25.png)

**Versions and configuration(please complete the following information):**
OS: [Windows 10]
Game Version: [0.C-37588-gc5f2b3b]
Graphics version: [Tiles]
Mods loaded: [Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Just Craftable Gunpowder, Makeshift Items Mod, PKs Rebalancing, Alternative Map Key, Mutant NPCs, More Locations, Fuji's More Buildings, Urban Development, PK - No Doom Monsters, Nonperishable Overhaul, StatsThroughSkills, DinoMod]

**Additional context**  
I found a Fish Serum on the street and used it, it gave me Extremely Dextrous and Indefatiguible right off the bat, which seems odd. The other mutations stuff is from character creation, there was only ever one single Fish Serum taken, no other mutagens at all. Stats can still be influenced by food and status effects like poisened and thirsty.

**Comment by ifreund** [comment]
This works as expected in vanilla as far as I can tell. Pretty sure it's a known issue caused by PKs.  If you can reproduce this in vanilla please reopen.
