### ISSUE TITLE
Cannot build on linux x64

### ISSUE THREAD

**Issue by n3tr4k** [CleverRaven/Cataclysm-DDA#28568]
**Describe the bug**  
Trying to build from souce but it returns error. It seems some problem with asyle.
```
astyle -V: Artistic Style Version 3.1
astyle regressions found.
Formatted  src/monattack.cpp Formatted  src/character.cpp
make: *** [Makefile:1067: astyle-check] Error 1
```
**To Reproduce**  
make -j8 TILES=1 SOUND=1 RELEASE=0 LUA=1 LOCALIZE=0 CCACHE=1

**Versions and configuration(please complete the following information):**
 - OS: Debian 4.19.20 x64
 - Game Version: 0.D-131-ge2a661fa19

**Comment by gcaliber** [comment]
You can build it if you set ASTYLE=0.

**Comment by gcaliber** [comment]
I was able to build with ASTYLE=0 and LINTJSON=0.

**Comment by kevingranade** [comment]
I believe this is a version disagreement betweennastyle 3.0.1 and 3.1.

**Comment by ZhilkinSerg** [comment]
Please try again with latest master.

**Comment by n3tr4k** [comment]
> Please try again with latest master.
Hi, yes it works fine now, thanks.

**Comment by n3tr4k** [comment]
It was building fine but today it's the same
```
astyle -V: Artistic Style Version 3.1
astyle regressions found.
Formatted  src/character.cpp
make: *** [Makefile:1059: astyle-check] Error 1
```

**Comment by Inglonias** [comment]
PR #28621 will fix this
