### ISSUE TITLE
Naming in json files, mapgen

### ISSUE THREAD

**Issue by KacperGawronski** [CleverRaven/Cataclysm-DDA#28560]
**[edit]**
**Well, was sick of it, found answer:**

	  "item":{
	      "T":[{"item":"wrench"},{"item":"screwdriver"}]  
	  },

Well, it's quite ok, nvm, topic to close :D

[History:]
**Describe the bug**  

{
   "type": "mapgen",
    "method": "json",
	[...],
    "items":{
        //HERE ARE PLACED ITEMS GROUPS, like:
        "c":{ "item": "crate_wine", "chance":25}
        //item should specify rather item or list of items than items group,
        },
    [...]
}

**To Reproduce**  
Check every single mapgen file. 
Instead of placing items, there are placed itemgroups.

**Expected behavior**  
Distinguish between items and items groups. Placing single precised item without a need to create a group with one item is way forward for creating scenarios. 
example:
    "items":{
         "w":{"item":"wrench","chance":100},
         "e":{"item":"ethanol","chance":20}
    }
    "item-groups":{
        "c":{"item":"crate_wine","chance":10}
    }
or:
    "items":{
         "w":{"item":"wrench","chance":100},
       "C":[{"item":"can_drink"},{"item":can_food"}],
         "c":{"item-group":"crate_winel","chance":20}
    }
**Versions and configuration(please complete the following information):**
0-D-branch

[edit]
Quite rare, but found it in labs:
"mapping": {
   <symbol>: { "item": [{"item": <item_name_id>, "chance": <X>}]}
}

Also, by "blind try":
"item":{
   "W":{"item":"wrench"}
}
However, it allow to put one item, not list of them.

But still should be fine to fix this mismatch in naming in files.

[edit 2]
Also, by documentation:
1)
"place_item":{
 { "item": "weed", "x": 14, "y": 15, "amount": [ 10, 20 ], "repeat": [1, 3], "chance": 20 }
}

**Comment by ZhilkinSerg** [comment]
I am pretty sure there are ways to place items without item groups.

**Comment by KacperGawronski** [comment]
well, there is, but it's working around and not intuitive.

like here:
"mapping": {
        "c": { "items": [{"item": "chem_lab", "chance": 10}]},
        "~": { "items": [{"item": "hydro", "chance": 20}]}
}

**Comment by KacperGawronski** [comment]
hmm, it's not placing items, will still look around for it

**Comment by curstwist** [comment]
place_loot : 
worked for me to place individual items.
