### ISSUE TITLE
mark 19 grenade launcher fires on own tile when damaged

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#28573]
**Describe the bug**  
Mark 19 grenade launcher's damage goes negative when damaged, causing the explosion to originate from the player instead of at the target
**To Reproduce**  
1. Make a player with a gun, magazine, and some ammo.
2. Try to aim at a wall.
3. There's no way to increase aim level.
Fire a mark 19 grenade launcher in yellow condition

**Expected behavior**  
not 100% misfire rate
**Versions and configuration(please complete the following information):**
Windows 10, tiles, 0.C-37564-g412ee85

mods:
[
  "dda",
  "no_npc_food",
  "novitamins",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "blazemod",
  "Tanks"
]

**Additional context**  
Tested with the M79, various tankmod guns, the M72 LAW, and all of them only risk misfires at lower levels of damage, with less of a sharp jump to 100% misfire rate. Most notably, tested using the RM228 PDW (loaded with frag shells) and tankmod's 30mm cannon, even when damaged to yellow condition they would not misfire constantly.

This is especially unusual as both the 30mm and the Mark 19 have 8 durability, and both their ammo belts have 6 reliability, so that alone doesn't seem to be the cause.

1. Mark 19 with concussion ammo still does this if scratched, so it's not just the FRAG ammo effect.
2. 30mm autocannon still does NOT do this even if its ammunition's custom explosion is replaced with FRAG. 
Which leaves me right back at the issue where I dunno why in the hell the Mark 19 does this when the 30mm autocannon does not, even when all things that logically should affect reliability are the same...

**Comment by NotFuji** [comment]
It's not misfiring, the projectile damage reaches 0 when the gun is damaged so the projectile is assumed to be immobile and falls at the player's feet.

Increase `ranged_damage`

**Comment by KorGgenT** [comment]
at minimum item health, the grenade launcher is at -17 (plus the damage of the ammo which in this case is 5) 
so in order for grenades not to blow up in your face always they need to be a minimum of 18 damage?

**Comment by SirPendrak** [comment]
Possible sollution could be: 
Treat ranged weapons the same way as melee when considering weapon damage. -10% damage for every point of damage, and +10% for accuarized weapons. This way .22 pistol wont get same DMG boost as .50 rifle. Right now, we have +6 flat, ant its seems weird

**Comment by NotFuji** [comment]
If we're doing damage based on kinetic energy, 40mm grenades should be at ~140 damage using 9x19 as a base.  They should at least do firearm-levels of blunt damage, even without explosives they're very lethal.
