### ISSUE TITLE
resin_cord is undefined

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#28584]
**Describe the bug**  
When I examine a long stick, I get an error report.

**To Reproduce**  
1: Make a character, smash a young tree, look at long stick. Get error message:

 DEBUG    : Missing item definition: resin_cord
 
 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1148

Also, when looking at the long stick, it says: Repaired with: basic repair kit or undefined-resin_cords

**Expected behavior**  
No error message, and the proper name for the the undefined-resin_cords in the item description.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-3-g1215bf2
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs, Filthy Clothing, Simplified Nutrition

**Comment by Pr0man** [comment]
This is due to an update that you ran - `resin_cord` is the entry to a modded item called "Resinous Cord" added by "More Survival Tools". Updating via the launcher may have eaten your mod and this is now causing the issue.

**Comment by KorGgenT** [comment]
looks like this issue is resolved. just reopen it if an actual bug is found.

**Comment by alkemann** [comment]
I encountered this in a fresh world without the mod.
```
 DEBUG    : Missing item definition: resin_cord
 
 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1212

```
```
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-6904-g54da45e77c-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    More Locations [more_locations],
    Urban Development [Urban_Development]
]

```
