### ISSUE TITLE
Cannot craft clear water

### ISSUE THREAD

**Issue by n3tr4k** [CleverRaven/Cataclysm-DDA#28595]
**Describe the bug**  
Cannot craft "clear water" if stone pot is inside inventory but works fine if it lays on the next tile.

**Versions and configuration(please complete the following information):**
 - OS: Debian x64
 - Game Version: 0.D-148-gdcfa1dbbc8
 - Mods loaded:
```javascript
[
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "realguns",
  "growable-pots",
  "makeshift",
  "More_Survival_Tools",
  "alt_map_key",
  "mutant_npcs",
  "national_guard_camp",
  "more_locations",
  "FujiStruct",
  "mapgen_demo",
  "oa_additional_buildings_mod",
  "Urban_Development",
  "boats",
  "blazemod",
  "Tanks",
  "no_mutagen",
  "no_religious_Texts",
  "no_flaming_weapons",
  "more_classes_scenarios",
  "manualbionicinstall",
  "no_reviving_zombies",
  "safeautodoc",
  "StatsThroughSkills"
]
```

**Additional context**  
Save file:
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2948694/save.zip)

**Comment by RosaEscura** [comment]
I believe what you're talking about is a gameplay mechanic: You cannot contain liquids in open containers when they are in your inventory, only if they are on the ground or wielded by the player.

**Comment by n3tr4k** [comment]
> I believe what you're talking about is a gameplay mechanic: You cannot contain liquids in open containers when they are in your inventory, only if they are on the ground or wielded by the player.

Alright, it sounds logical but poor begginers... somehow it should be more obvious that you need to drop pot on the ground if you want to use it for water boiling. I don't see why this micromanagment is needed for game.

**Comment by Feuerhai** [comment]
Clarifying a bit: You should be able to use the pot while it's in your inventory, you only need to have some place to store the clear water afterwards that isn't the original container. 
If the pot is on the ground, it functions as a container for fluids. 
If it's in your inventory, you need another item like an empty plastic bottle (which you can carry with fluids in it) or an empty can (which, like the pot, is only able to store fluids while sitting on the ground).

**Comment by aoae23** [comment]
Possibly a message that says "You have a container to store foo, but you cannot while it is in your inventory"? To clarify it.

**Comment by KorGgenT** [comment]
this is not a bug, this is a gameplay mechanic of not being able to put liquids in open containers in your inventory.
you can do this fine with any sealed container, but something like a stone pot will need to be on the ground or wielded
