### ISSUE TITLE
Electric charge consumption of many items and recipes are too arbitrary.

### ISSUE THREAD

**Issue by Vasyan2006** [CleverRaven/Cataclysm-DDA#28590]
**Is your feature request related to a problem? Please describe.**  
Electric charge consumption of many items are too arbitrary and not follow 1 charge = 1 kJ rule. 

For example boiling eggs require only 2 charges from the hotplate (crafting clean water requires 3 charges), despite most hotplates have at least 1 kW power requirements 
https://www.amazon.com/Ovente-Countertop-Infrared-Burner-Temperature/dp/B07456SPMF/
and 1 kW = 1 charge/second = 6 charges every turn. I never saw someone using a hotplate outside of the electrical grid because none of portable batteries can provide such high wattage over few minutes.

Melting metals is even more interesting, because ingame electric furnaces are build on hotplate heating elements. It is acceptable for working with fusible metals and crafting gold jewelry for your monster waifu, but melting iron or steel require much higher temperatures which will destroy heating elements.
That is why induction furnaces are used. They have energy consumption starting from 10 kW and require external water cooling.
https://www.amazon.com/Superland-Frequency-Induction-Furnace-Promotion/dp/B072MYR6N9
Such furnaces theoretically have no temperature limit and can melt any metal as long as enough electrical power and coolant are pumped into the coil.

On the other hand tiny mp3 players have 3.7 V 330 mAh batteries with capacity about 4 kJ or 4 charges, and can work 20+ hours. Thus gives power consumption 1 charge every 5 hours.

**Describe the solution you'd like**  
Recalculate energy consumption of items and recipes based on 1 charge = 1 kJ.

**Comment by KorGgenT** [comment]
[i have started work on this,](https://github.com/KorGgenT/Cataclysm-DDA/issues/24) but i'm currently eyeball-deep in other projects. i'll leave this link here for later use
