### ISSUE TITLE
Error on crafting

### ISSUE THREAD

**Issue by n3tr4k** [CleverRaven/Cataclysm-DDA#28592]
**Describe the bug**  
Tried to craft wooden arrow and got erro message.

**To Reproduce**  
Not sure, after error I was able to create wooden arrows fine.

**Screenshots**  
![Screenshot from 2019-03-09 17-16-07](https://user-images.githubusercontent.com/8440999/54074878-00f08f80-4290-11e9-98c5-1d03e859e09c.png)

**Versions and configuration(please complete the following information):**
 - OS: Debian x64
 - Game Version: 0.D-148-gdcfa1dbbc8
 - Mods loaded:
```javascript
[
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "realguns",
  "growable-pots",
  "makeshift",
  "More_Survival_Tools",
  "alt_map_key",
  "mutant_npcs",
  "national_guard_camp",
  "more_locations",
  "FujiStruct",
  "mapgen_demo",
  "oa_additional_buildings_mod",
  "Urban_Development",
  "boats",
  "blazemod",
  "Tanks",
  "no_mutagen",
  "no_religious_Texts",
  "no_flaming_weapons",
  "more_classes_scenarios",
  "manualbionicinstall",
  "no_reviving_zombies",
  "safeautodoc",
  "StatsThroughSkills"
]
```

** DEBUG LOG **
```
13:43:46.590 : Starting log.
13:43:46.592 INFO : Cataclysm DDA version 0.D-148-gdcfa1dbbc8
13:43:46.595 INFO : Number of render drivers on your system: 3
13:43:46.595 INFO : Render driver: 0/opengl
13:43:46.595 INFO : Render driver: 1/opengles2
13:43:46.595 INFO : Render driver: 2/software
13:43:46.775 INFO : SDL version used during compile is 2.0.9
13:43:46.775 INFO : SDL version used during linking and in runtime is 2.0.9
13:43:46.909 INFO : Active renderer: 1/opengles2
13:43:47.026 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
13:43:47.079 WARNING : opendir [./mods/] failed with "No such file or directory".
13:43:58.679 WARNING : opendir [./save/Hannibal/mods] failed with "No such file or directory".
13:44:05.268 INFO : Loaded tileset: MSX++DEAD_PEOPLE
13:47:11.122 WARNING : opendir [./save/Hannibal/mods] failed with "No such file or directory".
13:47:13.123 INFO : Loaded tileset: MSX++DEAD_PEOPLE
13:56:53.786 WARNING : opendir [./save/Hannibal/mods] failed with "No such file or directory".
13:56:55.771 INFO : Loaded tileset: MSX++DEAD_PEOPLE
17:14:56.430 ERROR : (error message will follow backtrace)
	./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x2f) [0x556d75a0f524]
	./cataclysm-tiles(_Z8DebugLog10DebugLevel10DebugClass+0x104) [0x556d75a0fa79]
	./cataclysm-tiles(_Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x134) [0x556d75a0ffa6]
	./cataclysm-tiles(_Z12realDebugmsgIJEEvPKcS1_S1_S1_DpOT_+0x36) [0x556d758c530e]
	./cataclysm-tiles(_ZN13craft_command18consume_componentsB5cxx11Ev+0x110) [0x556d759eb12a]
	./cataclysm-tiles(_ZN6player28consume_components_for_craftB5cxx11ERK6recipeib+0x99) [0x556d759f14e5]
	./cataclysm-tiles(_ZN6player14complete_craftEv+0x6c6) [0x556d759f1e7c]
	./cataclysm-tiles(_ZN17activity_handlers12craft_finishEP15player_activityP6player+0xc) [0x556d758b2e31]
	./cataclysm-tiles(_ZNKSt8functionIFvP15player_activityP6playerEEclES1_S3_+0x24) [0x556d758d4c7e]
	./cataclysm-tiles(_ZNK13activity_type11call_finishEP15player_activityP6player+0x8e) [0x556d758d4458]
	./cataclysm-tiles(_ZN15player_activity7do_turnER6player+0xdc) [0x556d75e49496]
	./cataclysm-tiles(_ZN4game16process_activityEv+0x69) [0x556d75aa1af5]
	./cataclysm-tiles(_ZN4game7do_turnEv+0x28f) [0x556d75ab374f]
	./cataclysm-tiles(main+0x159b) [0x556d7587d373]
	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7faa5915a09b]
	./cataclysm-tiles(_start+0x2a) [0x556d758a846a]

	Attempting to repeat stack trace using debug symbols...
	debug_write_backtrace(std::ostream&)
	??:?
	DebugLog(DebugLevel, DebugClass)
	??:?
	realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
	??:?
	void realDebugmsg<>(char const*, char const*, char const*, char const*)
	??:?
	craft_command::consume_components[abi:cxx11]()
	??:?
	player::consume_components_for_craft[abi:cxx11](recipe const&, int, bool)
	??:?
	player::complete_craft()
	??:?
	activity_handlers::craft_finish(player_activity*, player*)
	??:?
	std::function<void (player_activity*, player*)>::operator()(player_activity*, player*) const
	??:?
	activity_type::call_finish(player_activity*, player*) const
	??:?
	player_activity::do_turn(player&)
	??:?
	game::process_activity()
	??:?
	game::do_turn()
	??:?
	main
	??:?
	__libc_start_main
	/build/glibc-CEX3HA/glibc-2.28/csu/../csu/libc-start.c:342
	_start
	??:?
Backtrace emission took 0 seconds.
src/craft_command.cpp:151 [std::__cxx11::list<item> craft_command::consume_components()] Aborting crafting: couldn't find cached components
17:16:25.725 : Log shutdown.
```

**Comment by n3tr4k** [comment]
It seems the same problem with other items as well. Got an error while crafting stone knife.
```
 DEBUG    : Aborting crafting: couldn't find cached components
 
 FUNCTION : std::__cxx11::list<item> craft_command::consume_components()
 FILE     : src/craft_command.cpp
 LINE     : 151
```

**Comment by ifreund** [comment]
Can't reproduce.  Does the debug message occur every time? Does it occur on a fresh save? Exactly which components are you using?

**Comment by n3tr4k** [comment]
> Can't reproduce. Does the debug message occur every time? Does it occur on a fresh save? Exactly which components are you using?

- Yes, debug message occurs every time. 
- It is basically a fresh start.
- It doesn't happen always only from time to time.

Here's a world I saved when I was hit by first error message when I tried to create wooden arrow.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2948729/save.zip)

On next day happen next error with stone knife.

**Comment by Hirmuolio** [comment]
One awy to get this error is if the required material is dropped during the crafting process (it is too heavy/takes too much room).
(Easy to trigger with debug menu. Spawn more items than you can carry and try to craft. If the materials got dropped then the craft fails with this message)

Check if the materials for the craft process dropped to ground from you inventory when the error happens.

**Comment by n3tr4k** [comment]
> One awy to get this error is if the required material is dropped during the crafting process (it is too heavy/takes too much room).
> (Easy to trigger with debug menu. Spawn more items than you can carry and try to craft. If the materials got dropped then the craft fails with this message)
> 
> Check if the materials for the craft process dropped to ground from you inventory when the error happens.

Doesn't see anything dropped and don't remember that it happend. There also enough room in inventory.

**Comment by ifreund** [comment]
>One awy to get this error is if the required material is dropped during the crafting process (it is too heavy/takes too much room).

Ok, yeah I know why that would cause this debug message.  That's probably not the same cause as @n3tr4k's bug though, since that's not likely to happen without using the debug menu. I'll take a look at the save and see if I can get it to reproduce.

**Comment by n3tr4k** [comment]
> > One awy to get this error is if the required material is dropped during the crafting process (it is too heavy/takes too much room).
> 
> Ok, yeah I know why that would cause this debug message. That's probably not the same cause as @n3tr4k's bug though, since that's not likely to happen without using the debug menu. I'll take a look at the save and see if I can get it to reproduce.

Alright, thanks. I don't know how the code is built but it looks like race condition bug.
