### ISSUE TITLE
Tools useable without charges via Battery Compartment toolmod

### ISSUE THREAD

**Issue by KongMD-Steam** [CleverRaven/Cataclysm-DDA#28601]
**Describe the bug**  
Tools that have been modded with the Battery Compartment toolmod can be used when they have no charges.

**To Reproduce**  
1) Wish for a vibrator, mp3 player, and 2 battery compartment mods
2) Set all skills to 10 in debug menu
3) Unload batteries from vibrator & mp3 player
4) Attach a battery compartment mod to the vibrator & to the mp3 player
5) Activate menu > use these tools for free

**Expected behavior**  
Tools with this toolmod can only be activated when they have charges.

**Screenshots**  
This screenshot also shows another issue where an item I put into a battery compartment tool disappeared, and I can no longer unload that item. I have to remove the entire toolmod from the Action menu to have a useable tool again.
![Vibe_Bug](https://user-images.githubusercontent.com/36478131/54077078-95b4b680-42ab-11e9-8067-1684f3c8f7ed.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 8
 - Game Version: Build 8576
 - Graphics version: Tiles
 - Mods loaded: None

**Additional context**  
None

**Comment by Night-Pryanik** [comment]
These "tools" are usable even without the Battery Compartment mod and without battery charge in them.
