### ISSUE TITLE
Vehicle Controls no longer show cameras, headlights etc.

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#28605]
**Describe the bug**  
The vehicle controls no longer show certain vehicle part controls, like camera systems and headlights.

I tried removing and re-installing the parts in question, no luck.

**Expected behavior**  
When having a powered vehicle with a camera, as well as controls & camera control system in the same tile, a camera option should appear. When having a powered vehicle with controls & headlights, a headlights option should appear.

**Versions and configuration(please complete the following information):**
 - OS: Win 8.1 x64
 - Game Version: 0.D-155-gede79d4
 - Graphics version: Tiles
 - Mods loaded: StatsThroughSkills, No Religion, No Zombie Revivification

**Additional context**  
This is a regression, but I don't know how long ago it was introduced.

**Comment by anothersimulacrum** [comment]
After #24594, you need a dashboard or and electronics control unit to control electronic components.

**Comment by Tharn** [comment]
Cheers!
