### ISSUE TITLE
Yogurt gets mushy after freezing.

### ISSUE THREAD

**Issue by hyper2snyper** [CleverRaven/Cataclysm-DDA#28603]
**Describe the bug**  
![Really?](https://user-images.githubusercontent.com/43631032/54077836-c88e8880-4272-11e9-833b-e9a315e864cc.png)
Do I even have to explain.

I will anyways, how can yogurt be mushy. Is it even possible for yogurt to freeze?
**To Reproduce**  
freeze yogurt, then thaw said yogurt

**Expected behavior**  
non mushy yogurt

**Screenshots**  

**Versions and configuration(please complete the following information):**
Latest version, as of 2 days ago.

**Additional context**

**Comment by mlangsdorf** [comment]
https://healthyeating.sfgate.com/freeze-natural-yogurt-7813.html.  quoting "When yogurt is frozen then thawed, it can separate and become grainy and watery."

Not a bug, behavior is intended.
