### ISSUE TITLE
Lumbermill

### ISSUE THREAD

**Issue by nexusmrsep** [CleverRaven/Cataclysm-DDA#28602]
**Is your feature request related to a problem? Please describe.**  

There is a constant need for more interesting places to visit/plunder.

**Describe the solution you'd like**  

#28578 suggested a sawmill / lumber mill, where tree trunks are being processed to logs & 2x4, etc.
- Might be great in a forested areas, perhaps near river?
- Obvious finds would be chainsaws in all types, wood saws, circular saws, etc. and other tools; working clothes, etc.
- heavy machinery, cranes for lifting?
- perhaps some logging vehicles
- tons of splintered wood

**Describe alternatives you've considered**  
can be connected to partially deforested forest

**Additional context**  
inspirational image [SOURCE](https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjNrYfr-_XgAhVCmIsKHYZOCK8QjRx6BAgBEAU&url=https%3A%2F%2Fwww.reddit.com%2Fr%2FCitiesSkylines%2Fcomments%2F8505h0%2Flevonelm_lumber_mill%2F&psig=AOvVaw2AM7lk6EN6W7cllsznPWWq&ust=1552252099667088)
![image](https://user-images.githubusercontent.com/39925111/54077406-ffd35880-42b7-11e9-8320-51bb124f0a0b.png)

**Comment by Gmiz** [comment]
I think it would be lovely, as long as it's balanced enough. Such a nice wood mine should be protected with some hard-to-pass zombies. In addition to that, imagine having a kind of zombie "lumberjacks" running throughout the forest and chopping down trees all over the place :smile:

Anyway, a big :+1: from me always for the cool new ideas!

**Comment by LovamKicsiGazsii** [comment]
This is how my unused lumbermill looks like. 

This lumbermill didn't spawn any vehicles. 
![Lumbermill_1](https://user-images.githubusercontent.com/44979050/54086704-44a8cf00-434c-11e9-8df6-ae73f9e2accb.png)
This one connects to the forest trail
The deforested area will always generate differently (sort of)
![Lumbermill_2](https://user-images.githubusercontent.com/44979050/54086707-470b2900-434c-11e9-9684-8e00a7e74f9d.png)

I still need to add some special item groups, maybe some heavy machinery.

**Comment by nexusmrsep** [comment]
@LovamKicsiGazsii  great job!
Ideas: you could add conveyor belt(s) leading from an open space into a building where machines on both sides would imitate the sawing machinery, imitating loading bay on the free air (where trunks are loaded) and 2x4 lying on the floor on the other side (where cut planks are being stored before being packed). And lot of splintered wood imitating sawdust. It's not like those items are super hard to get, so spamming them in an actual place where they are produced has minuscule impact on the game balance, but makes up for more realistic feel.
More item options: dust masks, hardhats, axes.

**Comment by nexusmrsep** [comment]
I've just realized that @I-am-Erk just added some woodworking furniture that would fit perfectly in such a place.

**Comment by LovamKicsiGazsii** [comment]
I'll expand the storage and woodworking building, and may separate it. I'll add an item group, will probably be "wood_scraps". 
And maybe add a spawn for zombies and forklifts.

**Comment by I-am-Erk** [comment]
I am in the process of making some bulk items and new wood types that would go there too.
Also there is a floor type t_woodchips that would probably be scattered around a sawmill all over the place.

**Comment by LovamKicsiGazsii** [comment]
So, I lost access to the files and had to remake it.
But hey, it's finally complete. 
I'll open a PR, when I get home.
