### ISSUE TITLE
Chitin plating should install via glue/tape not welding

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#28608]
**Describe the bug**  
Chitin armor kit -> Chitin plating
installs via welder despite having no metal components

**To Reproduce**  
find a vehicle
give yourself fabrication 10
compare the recipe for the kit, vs it's install requirements

**Expected behavior**  
Should require tape or glue to install, similar to how wooden armor kit installs via nails

**Screenshots**  
ask if needed

**Versions and configuration(please complete the following information):**
 - OS: windows 10
 - Game Version: 0.D-155-gede79d4
 - Graphics version: tiles
 - Mods loaded: lots, ask if needed

**Additional context**  
ask if need save or anything else

**Comment by Night-Pryanik** [comment]
Closed by #28610.
