### ISSUE TITLE
Whistle and scarf shows time

### ISSUE THREAD

**Issue by Foxtrot-Uniform42** [CleverRaven/Cataclysm-DDA#28619]
**Describe the bug**  
Some items (i found two only) shows game time, but they must not.

**To Reproduce**  
1. Wield or wear whistle, or knit scarf
2. It shows time

**Expected behavior**  
Whistle and knit scarf should not telling time

**Screenshots**  
![timeshistl](https://user-images.githubusercontent.com/46412513/54085621-dcfd7e80-4361-11e9-8145-dd9192216d7a.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-285-g689eec0
 - Graphics version: Tiles
 - Mods loaded: Dark days ahead

**Comment by tinukedaya** [comment]
Copy&pasting from the PR:

Updated to 0.D-8613 today and I'm getting time on some stuff I managed to gather on my starting position.
Namely: Multi-tool, matchbox, pro fishing rod, screwdriver, wooden needle, plastic chunks and rags.
Also a camera, but I guess that one is fine telling me the time.
