### ISSUE TITLE
too many key presses: reading a book

### ISSUE THREAD

**Issue by spacenookie** [CleverRaven/Cataclysm-DDA#28611]
**Is your feature request related to a problem? Please describe.**  
if I read a book, but don't want to read until I gain a skill level, I have to press  either 4 keys for each time I read the book (inventory -> select item -> apply -> read once), or 3 ('R' ead menu -> select item -> read once).  or if I have to read it 20 times, 60-80 presses.

**Describe the solution you'd like**  
would like the option to read more than once on the menu, e.g. read twice, or even read three (or more) times. this would cut the number of key presses required by at least a factor of 2 (or more).

**Describe alternatives you've considered**  

**Additional context**  
seems like an easy way to go would be to take the code for "read until you gain a level" and break out of it when you reach the desired number of chapters.

**Comment by CoroNaut** [comment]
Perhaps also a "read for...5/10/30/60" minutes option?

**Comment by SourSlime** [comment]
I think the best way to implement a solution for this would be adding an input box, which allows the player to select a custom number of times to read a chapter.

**Comment by Muffinut** [comment]
I've always selected "read until you gain a level", then pressed 5 when I want to cancel. What's wrong with this option?

**Comment by spacenookie** [comment]
I feel like if you cancel out of a partial read you lose your time invested (in that partial read). also sometimes I like to tab out and do other stuff while the clock is advancing e.g. while sleeping.

**Comment by Muffinut** [comment]
In my experience reading advances the clock fast enough to where tabbing out isn't really an issue. 

I'm not opposed to SourSlime's idea of a third read option to input X chapters to be read. Though I am curious if it is possible to implement a way to save the player's place in the middle of the chapter in the case of a 'partial read.' It's not as if people suddenly forget 5-30+ minutes of attentive study if they're interrupted.
