### ISSUE TITLE
Error while generating new world

### ISSUE THREAD

**Issue by Foxtrot-Uniform42** [CleverRaven/Cataclysm-DDA#28616]
**Describe the bug**  
When creating new character, error message appears: 
"src/monstergenerator.cpp:1035 [void MonsterGenerator::check_monster_definitions() const] monster mon_tripod has unknown revert_to_itype: bot_tribot"

**To Reproduce**  
Create new character in new world

**Expected behavior**  
The world must be created without error

**Screenshots**  
![errscrn](https://user-images.githubusercontent.com/46412513/54083262-2ee2dc00-4343-11e9-9e35-3cc7d6838bbc.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-215-g6b7bfbf
 - Graphics version: Tiles
 - Mods loaded: Dark days ahead

**Additional context**  
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2949283/debug.log)

**Comment by AMurkin** [comment]
Fixed by #28614
