### ISSUE TITLE
Equip Armor for Pet-declared Creatures

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#28627]
**Is your feature request related to a problem? Please describe.**  
The problem is when you tame a creature into a pet, you have the "Attach bag" which allows such pets to carry suitable "bag" containers ([relevant code here](https://github.com/DracoGriffin/Cataclysm-DDA/blob/master/src/game.cpp#L6063)) but there is no option for "Attach armor/equipment" such as [Kevlar dog harness](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/generic.json#L1296).

**Describe the solution you'd like**  
An option for "Attach armor/equipment" that would allow the pet to inherit the defensive properties from the attached item that should still track durability and be damaged appropriately when attacked. Additionally with an ability to set JSON flags for specify mon_ids (inclusively or exclusively); such that tamed cows shouldn't be able to wear Kevlar dog harnesses. Depending on how animal mounts are handled (for instance, like horses), this may be different if there becomes a pseudo-vehicle interaction menu but for pets (i.e., will tamed horses have a pet menu options of "Equip saddle/bridle/etc" and "Ride pet" or a screen similar to interacting with vehicles with prompt for "installing" saddles/bridle/etc and sharing the same tile (like sitting in/on a seat within a vehicle) and "starting" the engine).

**Describe alternatives you've considered**  
Obtuse JSON that requires specific entries for every combination.

**Additional context**  
Proof of JSON concept can be [reviewed here](https://github.com/DracoGriffin/DG_Mods/blob/master/DracoDogMod/dog_monsters.json#L54) and [here](https://github.com/DracoGriffin/DG_Mods/blob/master/DracoDogMod/items/dog_items_armor.json).

**Comment by RosaEscura** [comment]
The Kevlar dog harness is dropped by K-9 units right? So I think it would also make sense to put a size restriction on it that dogs and other animals that are "small" can't equip it, same goes for too large animals.

**Comment by DracoGriffin** [comment]
> 
> 
> The Kevlar dog harness is dropped by K-9 units right? So I think it would also make sense to put a size restriction on it that dogs and other animals that are "small" can't equip it, same goes for too large animals.

Currently, dogs range from tiny (Chihuahua) to small (Labradors) to medium (Rottweiler); Kevlar dog harness drops from German Shepherd Z-9s, which are more or less "small" as the new system is based on volume/weight for size thresholds. Given that, I think it may be simpler to avoid size and go with faction, species or mon_ids to avoid outlier cases (or having to make override flags).

**Comment by RosaEscura** [comment]
Z-9s are actually small? And yeah, fair enough.

**Comment by mlangsdorf** [comment]
current plan is to go with default_faction (so bear, big_cat, cat, dog, fox, herbivore, molerat, otter, pig, rat, small_animal, wolf) and minimum and maximum volumes.
or possibly add an "armor_type" to monsters and roughly categorize creatures:
doglike: cats, dogs, wolfs, sheep, foxes, and other quadrapeds with small necks
horselike: cows, horses, donkeys, and other quadrapeds with long necks
bearlike: bears and other quadrapeds with minimal necks and a bipedal fighting posture
piglike: pigs, molerats, rats, and other quadrapeds with minimal necks
froglike: frogs and other  quadrapeds with minimal necks and huge hindlegs
spiderlike: 8 legs, two body segments like spiders
crablike: razorclaws, etc.

but that's a lot of extra data for not much extra value.

**Comment by mlangsdorf** [comment]
Decided to go with the bodytype solution after all because default_faction and species really aren't suitable.
