### ISSUE TITLE
Crash to desktop after accepting a quest twice

### ISSUE THREAD

**Issue by Alapaga** [CleverRaven/Cataclysm-DDA#28622]
**Describe the bug**  
Acquired a mission from the new mission system where i could intimidate the starting NPC, and i didn't intimidate him. Then i talked to the NPC again and i had the same choices to choose from, then the game detected the error, and upon ignoring the issue the game crashed

**To Reproduce**  
Start a fled the riot scenario and talk to the starting NPC, then accept to help him, and talk to them again.

**Expected behavior**  
I was expecting to get the regular menu you get when you're finished discussing with and NPC? but since the mission was a critical one, I apparently can't talk to them again before finishing the mission

**Screenshots**  
https://clips.twitch.tv/ScrumptiousAttractiveJayNotATK

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-317-g1ee397a 
 - Graphics version: Tiles
 - Mods loaded: Yes

**Additional context**  
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2949619/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2949620/debug.log)

**Comment by Feuerhai** [comment]
Can confirm, happens with any NPC with an "urgent" mission
