### ISSUE TITLE
Craft clean water doesnt spend dirty water in container

### ISSUE THREAD

**Issue by ZarenOFF** [CleverRaven/Cataclysm-DDA#28625]
Describe the bug
When you make clean water it doesnt spend dirty water in container

To Reproduce
1. Take water in any container
2. Try to craft clean water
3. You took clean water but container of dirty water still full

Screenshots
https://imgur.com/hARvFGO
https://imgur.com/rDIKzlt
https://imgur.com/UA04fhx
https://imgur.com/uzB0YAd

Versions and configuration
 - OS: Windows 10
 - Game Version: 0.D-317-g1ee397a
 - Graphics version: Tiles
 - Mods loaded: https://imgur.com/O7rMMQg

_My English is bad, sorry_

**Comment by KurzedMetal** [comment]
I could reproduce this: I had a canning pot full water, I used it often for several days and then when I looked it again it still was at full capacity.

**Comment by Tharn** [comment]
That's because the canning recipes don't seem to consume water, they do however produce large amounts of regular water.

**Comment by KurzedMetal** [comment]
I said I had a canning pot full of water, not that I was using canning recipes. I just crated "clean water" out of that source, just like the bug creator.

**Comment by Tharn** [comment]
Oh, alright. Since both the canning recipes and the clean water recipe don't consume water properly, I'll just leave the info here instead of making a new bug report for now.

**Comment by baraba3** [comment]
I can craft clean water without any water source present  in last version-8599

**Comment by Alapaga** [comment]
I can confirm this is still a problem in the newest version 0.D-400-g73b0882 (tiles)
I am a windows 10 user
Clean water crafted by putting a fire next to a toilet doesn't deplete the toilet water 
Also, cleaning clothes by "A"ppliying a washboard near a toilet shows that you have infinite water to wash things with, and doesn't deplete toilet water either.
I don't know if the two issues are related somehow but I tought i'd mention this too here

**Comment by ifreund** [comment]
This is most likely caused by my changes when making washboards require non frozen water.  Will work on a fix when I have a minute.

**Comment by jimmydoh** [comment]
I believe this issue, #28635 and #28650 are all caused by Pull Request #28014.

Pretty rusty but this issue was annoying me so I had a look and specifically, this logic looks like it results in all terrain that isn't deep, flowing water being regarded as a water source:

    item ret( "water", 0, item::INFINITE_CHARGES );
    if( !terrain_id.obj().has_flag( TFLAG_DEEP_WATER ) &&
        !( terrain_id.obj().has_flag( TFLAG_CURRENT ) ) ) {
        if( one_in( 3 ) ) {
            ret.poison = rng( 1, 4 );
        }
        return ret;
    }

src/map.cpp 4302 - 4309

First time I've looked at the code so I think someone will be able to fix it quicker than I can, but thought it might be helpful.
