### ISSUE TITLE
Pick up frozen liquids

### ISSUE THREAD

**Issue by aawilson** [CleverRaven/Cataclysm-DDA#28638]
**Is your feature request related to a problem? Please describe.**  
I cannot pick up frozen liquids, which results in the following amusing messaging:
![image](https://user-images.githubusercontent.com/57950/54099337-b581d280-43b0-11e9-9e8b-90813941a155.png)

The end result is that liquids have to be thawed in order to be transported in any way, unless they're already in a transportable container, or there is a ready heat source that won't take the surroundings down with it.

**Describe the solution you'd like**  
I should have some way to transport frozen liquids without having to find a mess kit or wait until mid-spring, either by chipping it into carryable chunks, or just being able to carry it (abstracting away the fact that frozen toilet bowl water might be hard to get at, for instance).

**Comment by misterprimus** [comment]
Not sure how practical it would be. How do you get the water out of the toilet anyway? It's frozen solid to the container. Mountain climbers have commented that even snow is a poor source of water unless you're actively taking large chunks and melting it with propane or some other heat source.

Does toilet water current thaw if you use a brazier near the toilet and raise the ambient temp? If so, that's by far the most practical way of getting water out IRL anyway.

**Comment by aawilson** [comment]
Chipping it out with an ice pick comes to mind. Or just abstracting it away. Note that the issue is that the heat source currently has to be brought to the container (toilet in this particular case), not that the water is undrinkable (so unsuitability to drink is not applicable, at least in this issue's context). It's also worth noting that this increases the desirability of starting near a brazier, possibly by more than intended.

**Comment by CoroNaut** [comment]
I know that if you have a standing tank and its contents are frozen, you can light a fire directly underneath it and wait for quite a while before you can access and transfer its contents. I'm sure a toilet won't handle the fire too well though.

**Comment by Feuerhai** [comment]
As a quick tip in the meantime, you can drag an oven into the bathroom and light a fire in it to heat up the water with a pot. Makes a bit of noise, but better than nothing.

**Comment by nexusmrsep** [comment]
There is need for ice item, that is frozen by default and unfreezes either spontaneously and leaks away if not stored in appropriate container, or via interaction thus allowing to choose container. Toilet cystern I'm home is accessible enough to use bashing tool to break the ice eventually, hopefully without breaking the toilet itself.

**Comment by paulenka-aleh** [comment]
Water frozen to the container doesn't sound like a good explanation or justification, just something to consider implementing right or abstracting away. You can drag an oven, place it 6 tiles away and craft clean water from the toilet depite fire is quite in a distance and neither fire, nor water is supposed to be moved while crafting
