### ISSUE TITLE
Chocolate Pancake is over 2000 calories

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#28634]
**Describe the bug**  
![image](https://user-images.githubusercontent.com/2125926/54093559-62d3f680-436f-11e9-9e50-c333e227d422.png)

**To Reproduce**  
1. I found this pancake in a sugar house

**Expected behavior**  
That's a hell of a chocolate pancake! IHOP serves three chocolate pancakes and they're 330 calories total. Something is off, I think.

**Screenshots**  
See above
**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D stable
 - Graphics version: Tiles
 - Mods loaded: No non-default mods
**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by Tharn** [comment]
In a similar vein, grown Lettuce shows 0 calories. Should be 15 cal per 100g.

**Comment by KorGgenT** [comment]
> In a similar vein, grown Lettuce shows 0 calories. Should be 15 cal per 100g.

this is fixed in #28521

the chocolate pancakes are that way because their recipe takes lard, probably, but it's good to know

**Comment by anothersimulacrum** [comment]
Lard isn't one of the ingredients in the recipe for Chocolate pancakes, it's a tool. Unless tools are used in nutritional calculation, it's something else causing this.

**Comment by KorGgenT** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/recipes/recipe_food.json#L3310

**Comment by Inglonias** [comment]
Incidentally, the number of calories is listed on the [chocolate pancakes entry in JSON](https://github.com/CleverRaven/Cataclysm-DDA/blob/412ee858b5dd7475cf2fc4a2228286379797dcfa/data/json/items/comestibles/junkfood.json#L989) as 2193 as well. I'm guessing that number was automatically calculated by some utility? I honestly lost track of the food rebalance a while back, so I don't know where that number came from.

**Comment by KorGgenT** [comment]
essentially. if the chocolate pancake entry needs to change, then the recipe to make it needs to be changed as well, because of the recipe permutation test that travis will run

**Comment by Inglonias** [comment]
anothersimulacrum may have hit the solution. _Can_ we make the lard a tool rather than an ingredient? That seems to be the main factor increasing the calorie count.
