### ISSUE TITLE
Saves from 0.D throwing "Loaded bad ter!" on current master

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#28649]
**Describe the bug**
`loffice_tower`, `hdwr_large` and `cemetery_4square` overmaps turn into `nothing` if world is loaded on latest master build.

**To Reproduce**  
1. Generate a world on `0.D` with either one of these specials visible on debug-revealed map. 
2. Save and exit.
3. Try loading this world on a master build `73b0882`.

The error (full debug.log below): 

    ERROR : src/savegame.cpp:828 [void overmap::unserialize(std::istream&)] Loaded bad ter! ter loffice_tower_2

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 19.04
 - Game Version: `73b0882`
 - Graphics version: Tiles
 - Mods loaded:
```
  "dda",
  "no_npc_food",
  "filthy_morale",
  "makeshift",
  "no_religious_Texts",
  "no_olg_guns",
  "No_Fungi",
  "StatsThroughSkills"
```

**Additional context**
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2953760/debug.log)

[Pleasant Mound.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/2953702/Pleasant.Mound.tar.gz)

**Comment by int-ua** [comment]
Trying to bisect it now.

**Comment by int-ua** [comment]
Bisect showed that feaca1eb03da15e1c5f8970c96356488dc5715fb is the commit that introduced it.

**Comment by int-ua** [comment]
Yes, many specials were renamed in that commit https://github.com/CleverRaven/Cataclysm-DDA/commit/feaca1eb03da15e1c5f8970c96356488dc5715fb#diff-3e7d0bd7cf252afbb3b94bbf253efe53L2565

**Comment by Mcrone617** [comment]
I'm also having this problem, and i'm wondering if I just edited the map and respawned a home improvement store over the nothing tiles for example, would that prevent the errors from continuing? Or is it better to simply wait it out for a fix.

**Comment by int-ua** [comment]
Maybe it is. Looks like more reliable way is to make a migration script to autoreplace renamed overmaps in save files (no need to remember which special was where). It's easy with grep and sed on Linux/macOS. Can't help with Windows though. But before that we should better find out if these backwards incompatible changes were intended. I've created a comment mentioning the author, waiting for a reply.

**Comment by int-ua** [comment]
@Pr0man please respond. Were the changes intended? Are you aware that they made saves incompatible?
