### ISSUE TITLE
I can boil water with a pointy stick

### ISSUE THREAD

**Issue by pescepalla** [CleverRaven/Cataclysm-DDA#28648]
**Describe the bug**  
It is possible to boil water using only a pointy stick as a tool, since it has food cooking value 1.

**To Reproduce**  
Have pointy stick and some water in inventory. Make clean water.

**Expected behavior**  
The player shouldn't be able to boil water using a pointy stick, since it doesn't make sense.

**Versions and configuration(please complete the following information):**
 - OS: Arch linux
 - Game Version: git master
 - Graphics version: tiles
 - Mods loaded: default

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental: 
![изображение](https://user-images.githubusercontent.com/11132525/54148189-37273e00-444d-11e9-882f-b4d249ded215.png)

![изображение](https://user-images.githubusercontent.com/11132525/54148215-45755a00-444d-11e9-847f-fd925cd9f7f5.png)

**Comment by pescepalla** [comment]
Yep. Sorry!
