### ISSUE TITLE
Loading Error 

### ISSUE THREAD

**Issue by SirClarke** [CleverRaven/Cataclysm-DDA#28642]
**Describe the bug**  
I'm not very Technology-savvy but Every time I try and build a new world it crashes
Seems to Happen  when finalizing Overmap Specials Everytime 

**To Reproduce**  
Trying to build a world

**Expected behavior**  
Build a new world?  I guess sorry don't know what you mean 

**Screenshots**  
![Screenshot (37)](https://user-images.githubusercontent.com/31796878/54112965-ace3c900-43bd-11e9-985c-241f9c73817c.png)
![Screenshot (36)](https://user-images.githubusercontent.com/31796878/54112966-ace3c900-43bd-11e9-986d-3573935bffcf.png)
![Screenshot (35)](https://user-images.githubusercontent.com/31796878/54112967-ace3c900-43bd-11e9-93f5-d97d50b48b06.png)
![Screenshot (14)](https://user-images.githubusercontent.com/31796878/54112969-ace3c900-43bd-11e9-8f1e-4b0f5a0a27de.png)
![Screenshot (11)](https://user-images.githubusercontent.com/31796878/54112970-ace3c900-43bd-11e9-84a6-d5e6f26e6e05.png)
![Screenshot (9)](https://user-images.githubusercontent.com/31796878/54112971-ad7c5f80-43bd-11e9-8f5a-8a53818b8f00.png)
![Screenshot (7)](https://user-images.githubusercontent.com/31796878/54112973-ad7c5f80-43bd-11e9-96cb-5c88c3bd147e.png)
![Screenshot (6)](https://user-images.githubusercontent.com/31796878/54112974-ad7c5f80-43bd-11e9-847c-2700d4d150d3.png)
![Screenshot (2)](https://user-images.githubusercontent.com/31796878/54112975-ad7c5f80-43bd-11e9-87dd-b9e47f30ea51.png)
![Screenshot (1)](https://user-images.githubusercontent.com/31796878/54112976-ad7c5f80-43bd-11e9-866b-d79e28c62077.png)
![Screenshot (51)](https://user-images.githubusercontent.com/31796878/54112977-ad7c5f80-43bd-11e9-855e-9a5b241b098b.png)
![Screenshot (50)](https://user-images.githubusercontent.com/31796878/54112978-ad7c5f80-43bd-11e9-861b-4ecdeb96f622.png)
![Screenshot (49)](https://user-images.githubusercontent.com/31796878/54112980-ae14f600-43bd-11e9-8408-94fb3944d731.png)
![Screenshot (48)](https://user-images.githubusercontent.com/31796878/54112982-ae14f600-43bd-11e9-88fb-00eaa952ffe6.png)
![Screenshot (47)](https://user-images.githubusercontent.com/31796878/54112983-ae14f600-43bd-11e9-8302-3de4625a6198.png)
![Screenshot (46)](https://user-images.githubusercontent.com/31796878/54112984-ae14f600-43bd-11e9-87d6-b6d7dd364ef4.png)
![Screenshot (45)](https://user-images.githubusercontent.com/31796878/54112985-ae14f600-43bd-11e9-93a3-b3a199aabffe.png)
![Screenshot (44)](https://user-images.githubusercontent.com/31796878/54112986-aead8c80-43bd-11e9-90de-a2e5cf8a5af0.png)
![Screenshot (43)](https://user-images.githubusercontent.com/31796878/54112987-aead8c80-43bd-11e9-85f9-ef950df9a4e0.png)
![Screenshot (42)](https://user-images.githubusercontent.com/31796878/54112988-aead8c80-43bd-11e9-8eb6-d6092da9a0d8.png)
![Screenshot (41)](https://user-images.githubusercontent.com/31796878/54112989-aead8c80-43bd-11e9-916b-7f200ebc5425.png)
![Screenshot (40)](https://user-images.githubusercontent.com/31796878/54112990-aead8c80-43bd-11e9-92ae-d501e33aad5e.png)
![Screenshot (39)](https://user-images.githubusercontent.com/31796878/54112991-aead8c80-43bd-11e9-9f59-89cd5d0c862e.png)
![Screenshot (38)](https://user-images.githubusercontent.com/31796878/54112992-af462300-43bd-11e9-85b7-62b7c43673dc.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-399-gd677a65
 - Graphics version: Tiles
 - Mods loaded:
Dark Days Ahead
Medieval and Historic Content
More Survival tools
Classic Roguelike classes
Statsthroughskills
Vehicle Additions Pack
Tanks and other Vehicles
Altenative map key
Boats
Folding parts pack
Filthy Clothing
Makeshift Items MOd
Classes and Scenarios mod
Mutant NPCs
Necromancy
Mythological Replicas
Modular Turrets
Salvaged
Arcana and Magic Items
Disable Npc Needs
Urban Development
More Locations 
Fuji's More Buildings
**Additional context**  

Never had a problem with these Mods before hand

**Comment by Pr0man** [comment]
This is due to the changes to overmap generation regarding cities while using the "Alternate Map Key" mod. There is a change underway, but for now, disabling the mod should resolve the issue.

**Comment by SirClarke** [comment]
Thank you so much Dude you have saved my Gaming life
