### ISSUE TITLE
Keyboard input partially ignored in tiles build

### ISSUE THREAD

**Issue by danielrempel** [CleverRaven/Cataclysm-DDA#28651]
Pressing keys like `a`, `'`, `1`, and Shift, Control combinations of them ignored while pressing Tab, Enter, arrow keys, F1-F12 and others works properly
Related to both input fields and ordinary input (game screen - movement keys etc)

(terminal build works properly)

**To Reproduce**  
1. Run tiles build of Cataclysm
2. Open settings
3. Find "Default character name"
4. Press Enter
5. Try typing in some text in the field

Or:
1. Run tiles build of Cataclysm
2. Start/Load game
3. Try moving with vim keys

**Expected behavior**  
Game reacting on the input: characters appearing in an input field, game character moving according to my input

**Versions and configuration:**
 - OS: Xubuntu 16.04, amd64
 - Game Version: 0.D-8574 (Linux tiles build from GitHub)
 - Graphics version: Tiles
 - Mods loaded: unapplicable

**Additional context**  

Possibly related issue: https://github.com/CleverRaven/Cataclysm-DDA/issues/18261
I thought that reopening an issue from 2016 is worse than creating a new one

SDL packages installed:

```
ii  libsdl-image1.2:amd64                       1.2.12-5+deb9u1build0.16.04.1                      amd64        Image loading library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-mixer1.2:amd64                       1.2.12-11build1                                    amd64        Mixer library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-net1.2:amd64                         1.2.8-4                                            amd64        Network library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-ttf2.0-0:amd64                       2.0.11-3                                           amd64        TrueType Font library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl1.2debian:amd64                       1.2.15+dfsg1-3                                     amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:amd64                         2.0.4+dfsg1-2ubuntu2                               amd64        Simple DirectMedia Layer
ii  libsdl2-dev                                 2.0.4+dfsg1-2ubuntu2                               amd64        Simple DirectMedia Layer development files
ii  libsdl2-image-2.0-0:amd64                   2.0.1+dfsg-2+deb9u1build0.16.04.1                  amd64        Image loading library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-image-dev:amd64                     2.0.1+dfsg-2+deb9u1build0.16.04.1                  amd64        Image loading library for Simple DirectMedia Layer 2, development files
ii  libsdl2-mixer-2.0-0:amd64                   2.0.1+dfsg1-1                                      amd64        Mixer library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-ttf-2.0-0:amd64                     2.0.14+dfsg1-1                                     amd64        TrueType Font library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-ttf-dev:amd64                       2.0.14+dfsg1-1                                     amd64        TrueType Font library for Simple DirectMedia Layer 2, development files
```

**Comment by Night-Pryanik** [comment]
Cannot confirm on latest experimental as of September 30, 2019, though I'm on Windows 10 and not on Xubuntu:
![изображение](https://user-images.githubusercontent.com/11132525/65902533-b3727600-e3cb-11e9-8bd9-5370109ee524.png)

**Comment by int-ua** [comment]
Sorry, it needs an improvement to steps to reproduce. I'm on *buntu (several environments installed) and I've never noticed anything similar.
