### ISSUE TITLE
Bug-Water source always avaible for crafting

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#28650]
**Describe the bug**  
You can craft clean water all the time with heat source and boiling suplement even without actual dirty water present.Same as making dishes which require water.Seems liek fairly important bug to me which is present for several version now.

**To Reproduce**  
try crafting clean  water anywhere or see checks for other recipes which require water.

**Expected behavior**  
clean water shoudl require water source present..this shoudl go for other recipes which require water

**Screenshots**  
http://prntscr.com/mwh36f
screenshot of crafting from beging of game without any actual water present.

**Versions and configuration(please complete the following information):**
 
 - Game Version: [from the main menu, e.g. 0.D-400-g73b0882]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: vanilla

**Comment by RosaEscura** [comment]
Probably related to this issue: "Craft clean water doesnt spend dirty water in container" #28625

**Comment by baraba3** [comment]
Yes,probably water is not spend as game have unlimited water anywhere. As this seemed as major bug i posted it seperate thoguh i dont mind if someone merge issues.
