### ISSUE TITLE
Certain things cause freezing upon loading world

### ISSUE THREAD

**Issue by MitztheKat** [CleverRaven/Cataclysm-DDA#28661]
**Describe the bug**  
Certain actions to the game (as in, re-using files, overloading NPC count) can cause crashing & freezing.
**To Reproduce**  
1-use modlist
2-boost npc-gen to 1.5, static & wander NPC on
3-attempt to generate a world with previous stats
4-freeze happens
*Crash logs will appear when you re-use assets from old games*
crash log 1:
sadly, i cannot recover the first error, this is the best i can get. https://gyazo.com/250a652f2a7e5f1cf100023cfffbf18b
crash log 2:
`CRASH LOG FILE: config/crash.log
VERSION: 0.D-402-gb4fb397
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x54CFC0[cataclysm-tiles.exe+0x14CFC0]
    @0x54D361[cataclysm-tiles.exe+0x14D361]
    SMPEG_error+0x3DAF3@0xBA3755[cataclysm-tiles.exe+0x7A3755]
    CreateProcessAsUserW+0x12E8A@0x7548040F[kernel32.dll+0x5040F]
    RtlKnownExceptionFilter+0xB7@0x773C50E7[ntdll.dll+0x750E7]
    RtlInitializeExceptionChain+0x36@0x773897D5[ntdll.dll+0x397D5]
`

**Expected behavior**  
I expect to load safely, at a refugee center.
**Screenshots**  
i might add screenshots if expected.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
- Game Version: 0.D-8574
 - Graphics version: Tiles, for both versions
 - Mods loaded:
`"dda",
  "no_npc_food",
  "novitamins",
  "generic_guns",
  "makeshift",
  "More_Survival_Tools",
  "Medieval_Stuff",
  "modular_turrets",
  "Salvaged_Robots",
  "more_locations",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "boats",
  "deoxymod",
  "blazemod",
  "No_Fungi",
  "No_Explosive_Zombies",
  "No_Big_Zombies",
  "No_Anthills",
  "Mundane_Zombies",
  "manualbionicinstall",
  "no_reviving_zombies",
  "safeautodoc",
  "StatsThroughSkills"`
**Additional context**  
i have attempted to sort through my modlist, but if a trace of the old save appears, then it will crash because of save incompatibilities. (and produce errors)
I mod rimworld, so i have basic debugging instructions
... solved one problem

**Comment by RosaEscura** [comment]
I believe default settings have static NPCs as false which means no NPCs spawn in specific locations at game start such as Refugee centres or Bandit camps so yes, that's a feature.

**Comment by MitztheKat** [comment]
yes, i have noticed. i put together those pieces. will edit the bug

**Comment by ZhilkinSerg** [comment]
Doesn't reproduce for me with same mod list and scenario setting.

**Comment by MitztheKat** [comment]
it seems when i do something, it'll break every time until i do a complete re-install & wipe (i think)? this may be an even deeper problem.
might be connected to another problem, but if i have to give up everything i worked hard on *on a stable branch* just to fix an unknown bug, i'm not sure this can just be passed.
anything passing on from the old game will make the loading process spontaneously combust.
i'm in kind of a burnout right now. spent 2 hours trying to do the bug-testing to find what causes it, to find out this.

**Comment by ZhilkinSerg** [comment]
Is your world new? Or do you spawn new character to existing world?

**Comment by MitztheKat** [comment]
the world is new, sometimes the template is new, but when both are absolutely new it works
NOTE: copying the world settings will also break it, so that's incredibly weird how much it copies and how little it changes.
it seems it keeps so much of the code from the previous version that mod removal is impossible/version change is impossible (?)

**Comment by Throwaway-name** [comment]
Cannot reproduce on 0.D-119 0.D-8576.

**Comment by Alapaga** [comment]
I tested for this on windows 10 and the latest experimental version 0.D-430-g0e33cec (tiles)
This is what I got as error messages

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2960414/debug.log)

then upon ignoring all the errors, the character creation process begins
I Hope this helps

**Comment by ZhilkinSerg** [comment]
That is a different unrelated issue already solved in #28671.

**Comment by MitztheKat** [comment]
well, it seems it's happening again when i bump up the NPC count to 1.5 and make everything fresh.

**Comment by LyleSY** [comment]
I see at least two mods on there that mess with MapGen and it sounds like this is a MapGen crash. My suggestion would be to pick one and only one mod that adds locations since they conflict.
