### ISSUE TITLE
Pick up liquids in non-sealable container

### ISSUE THREAD

**Issue by africalinguist** [CleverRaven/Cataclysm-DDA#28677]
**Is your feature request related to a problem? Please describe.**  
I feel that you should be able to pick up fluids (e.g. from riverbanks) in non-sealable, but watertight containers

**Describe the solution you'd like**  
You should be allowed to pick up fluids in a Watertight container that is not sealable, but you must be wielding the container. Also, if you attack with the container you should spill most or all of the fluid, and keeping the fluid in the container requires concentration, and stumbling may spill some of it.

**Describe alternatives you've considered**  
The system could be left as it is.

**Additional context**  
If I'm wrong about anything, or thought something was in the game mistakenly, or there's a good reason for this not to be in the game, please tell me.

**Comment by Hirmuolio** [comment]
You can already fill non watertight containers like that.

Wield the item and you can fill it with liquids. At least the bucket works.

If you put the item to inventory you will spill all the contents. You can drop it and it stays full.

**Comment by KorGgenT** [comment]
you can already do this if you ```w```ield the item from the floor. it dumps out if it's in your inventory.
