### ISSUE TITLE
better ideas to reduce message log spam

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#28683]
**Is your feature request related to a problem? Please describe.**  
Message panel is often filled with the same output over and over again
• This can hide important messages in a haystack of unimportant ones
• And in worst case push important messages entirely out of the recent messages log within a single turn (usually only happens if your turn is skipped for some reason)

**Describe the solution you'd like**  
• A clean message log that makes it easy to tell important messages (you're on fire stupid) from less important ones (moving through this grass is a little slow)
• And while still letting me know what's going on
• And without looking like unnecessary spam
• And possibly giving me control over what I consider to be more important or less important
(the last three are more wishlist ideas)

**Describe alternatives you've considered**  
• Just like the Auto Pickup and Auto Safe white/blacklists, a message log white/black list of some sort (options TBD, there's a few ways this could work)
• Some way to differentiate messages from purely informational, to danger warning, to YOU'RE ON FIRE STUPID (possibly coloring?)
• better merging of messages
  ♦ An idea here might be to merge all messages that have happened in the last XX time to show up as "message x10", in the order of their most recent occurance... Except for the most recent message, which should also be merged but only with identical examples that are at the bottom
  ♦ That explanation is really confusing so here's an example from the image below
________________
[as seen below]
Moving onto this long grass is slow! x5
Moving off of this long grass is slow! x5
Moving onto this long grass is slow! x 2
________________
[if next step is off grass]
Moving off of this long grass is slow! x5
Moving onto this long grass is slow! x7
Moving off of this long grass is slow!
________________

**Additional context**  
This is a rework from #28526 to give better examples and a more collaborative approach to determining if this is an issue that needs to be solved, and how we might go about it

Personally the issue doesn't really bother me that much, but that post did but rather than yelling at him I wanted to give a positive example of a better way to post.

Here's a related image from the original post

![](https://user-images.githubusercontent.com/6810861/53917040-f2259500-4063-11e9-8335-df95fe1596b8.png)

**Comment by Xpyder** [comment]
Hey look, seems like someone else had the same idea!
Hi there #28215

**Comment by KorGgenT** [comment]
yeah, this is a duplicate. closed in favor of #28215

**Comment by KorGgenT** [comment]
please do continue the conversation of this feature. if we keep it to one issue we can get all the ideas in one place and decide on the best course of action. thanks!
