### ISSUE TITLE
Game crash after vehicle crash

### ISSUE THREAD

**Issue by KiwiTrinsic** [CleverRaven/Cataclysm-DDA#28684]
After crashing vehicle and getting a message it was too heavy for its engines, I attempted to 'e'xamine vehicle, at which point the game crashed.

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.D-215-g6b7bfbff67
TYPE: Signal
MESSAGE: SIGFPE: Arithmetical error
STACK TRACE:

        ./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x43) [0x5583236d28be]
        ./cataclysm-tiles(+0x477ffc) [0x5583236c3ffc]
        ./cataclysm-tiles(+0x47822c) [0x5583236c422c]
        /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fd0bae9cf20]
        ./cataclysm-tiles(_ZNK7vehicle20consumption_per_hourERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0xf8) [0x558323c38ba6]
        ./cataclysm-tiles(_ZN7vehicle20print_fuel_indicatorERKN10catacurses6windowEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt3mapIS9_iSt4lessIS9_ESaISt4pairISA_iEEEbb+0x35a) [0x558323c42d72]
        ./cataclysm-tiles(_ZN7vehicle21print_fuel_indicatorsERKN10catacurses6windowEiiibbbb+0x290) [0x558323c433fa]
        ./cataclysm-tiles(_ZNK12veh_interact13display_statsEv+0xdf8) [0x558323c03432]
        ./cataclysm-tiles(_ZN12veh_interact16allocate_windowsEv+0x223) [0x558323c064ed]
        ./cataclysm-tiles(_ZN12veh_interactC2ER7vehicleii+0x787) [0x558323c06caf]
        ./cataclysm-tiles(_ZN12veh_interact3runER7vehicleii+0x2a) [0x558323c0bfe2]
        ./cataclysm-tiles(_ZN4game12exam_vehicleER7vehicleii+0x2a) [0x55832374e2ce]
        ./cataclysm-tiles(_ZN6Pickup7pick_upERK8tripointi+0x1477) [0x558323aee3d7]
        ./cataclysm-tiles(_ZN4game13handle_actionEv+0x166b) [0x5583237ab9db]
        ./cataclysm-tiles(_ZN4game7do_turnEv+0x387) [0x5583237739f7]
        ./cataclysm-tiles(main+0x1293) [0x558323529aeb]
        /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fd0bae7fb97]
        ./cataclysm-tiles(_start+0x2a) [0x5583235548ba]

        Attempting to repeat stack trace using debug symbols...
        debug_write_backtrace(std::ostream&)
        ??:?
        log_crash
        crash.cpp:?
        signal_handler
        crash.cpp:?
        ??
        ??:0
        vehicle::consumption_per_hour(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) const
        ??:?
        vehicle::print_fuel_indicator(catacurses::window const&, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >, bool, bool)
        ??:?
        vehicle::print_fuel_indicators(catacurses::window const&, int, int, int, bool, bool, bool, bool)
        ??:?
        veh_interact::display_stats() const
        ??:?
        veh_interact::allocate_windows()
        ??:?
        veh_interact::veh_interact(vehicle&, int, int)
        ??:?
        veh_interact::run(vehicle&, int, int)
        ??:?
        game::exam_vehicle(vehicle&, int, int)
        ??:?
        Pickup::pick_up(tripoint const&, int)
        ??:?
        game::handle_action()
        ??:?
        game::do_turn()
        ??:?
        main
        ??:?
        __libc_start_main
        /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344
        _start
        ??:?

**Comment by esotericist** [comment]
So I've got a save file that consistently crashes for me on MacOS, tested with the current master repo.

All I have to do is load this save, attempt to examine the vehicle, and I immediately crash with 'Arithmetical error'.

Unlike KiwiTrinsic, I'm unable to get anything useful from crash.log:
```
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.D-1418-g1198109bc5
TYPE: Signal
MESSAGE: SIGFPE: Arithmetical error
STACK TRACE:

        0   cataclysm-tiles                     0x000000010638d69f _Z21debug_write_backtraceRSo + 47

        Attempting to repeat stack trace using debug symbols...
        backtrace: Could not extract binary name from line
```
[crashysave.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3046127/crashysave.zip)

**Comment by esotericist** [comment]
as a possible hint to whoever looks at this:
I was able to produce this save file by realizing all I had to do to create the condition was rotate the vehicle so it pointed south
