### ISSUE TITLE
Adjacent 'standing mirrors' block vision even when standing on them

### ISSUE THREAD

**Issue by A-lxe** [CleverRaven/Cataclysm-DDA#28694]
**Describe the bug**  
When there are 3+ adjacent mirrors along a wall, standing on the middle one doesn't reveal vision of the wall as it should. This doesn't occur when the mirrors aren't along the wall.

This particular edge case isn't too impactful, but I figured I would report it in case there are other examples or it impacts the vision system.

**To Reproduce**  
1. Make a player.
2. Find/make a row of standing mirrors along a wall - I found it in a basement gym.
3. Check vision as you stand on the center mirror. Compare with other configurations with fewer mirrors.

**Expected behavior**  
When standing on furniture, I should be able to see all around it.

**Screenshots**  
Mirrors block view (expected, right?):
![image](https://user-images.githubusercontent.com/5279257/54328161-3d4f2300-45e3-11e9-840a-dc5e8d5f1957.png)

Standing on the center mirror doesn't reveal the wall behind it:
![image](https://user-images.githubusercontent.com/5279257/54328226-83a48200-45e3-11e9-82b5-23de44404d19.png)

Moving the mirrors to the sides reveals the wall:
![image](https://user-images.githubusercontent.com/5279257/54328215-74253900-45e3-11e9-96ec-4e5b354a4365.png)

Moving the three mirrors away from the wall fixes the issue:
![image](https://user-images.githubusercontent.com/5279257/54328303-c1090f80-45e3-11e9-93e0-552b537c04d2.png)

This bug occurs even when the mirrors are broken:
![image](https://user-images.githubusercontent.com/5279257/54328637-0ed24780-45e5-11e9-9bf6-3d245b70e4fd.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D - first release
 - Graphics version: Tiles
 - Mods loaded: 
```
[
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "realguns",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "alt_map_key",
  "mutant_npcs",
  "more_locations",
  "FujiStruct",
  "mapgen_demo",
  "oa_additional_buildings_mod",
  "Urban_Development",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks"
]
```

**Comment by Night-Pryanik** [comment]
Looks like this is a bug in the LOS system.

**Comment by kevingranade** [comment]
Not sure if this is lighting or LOS, I'm pretty sure your character is the source of the light, so it can easily be the case that the square is not illuminated rather than invisible, and the cause is some interaction caused by standing on an opaque tile (which is not a typical situation) while adjacent to another opaque tile.
Either way, thanks for reporting.

**Comment by kevingranade** [comment]
I SUSPECT all we need to do is to set the square the player is standing on to transparent when calculating FoV and Dynamic lighting, probably here https://github.com/CleverRaven/Cataclysm-DDA/blob/cee2784d37ef8b5e8698316a2558cf046935725d/src/map.cpp#L7594

**Comment by A-lxe** [comment]
I should've tested this, but I'm pretty sure that I had the stats/eye encumbrance to see 1 space around me without my flashlight in that basement.

**Comment by A-lxe** [comment]
I went back, the same situation with no flashlight:
![image](https://user-images.githubusercontent.com/5279257/54484371-e09a7500-483b-11e9-99e4-a495f3818602.png)

The same, but with the outer mirrors moved to the sides:
![image](https://user-images.githubusercontent.com/5279257/54484380-0fb0e680-483c-11e9-9e0f-0bca7c2f2d2e.png)

**Comment by kevingranade** [comment]
Thanks for confirming, so it's definitely FoV then.
