### ISSUE TITLE
Negative/Positive Effects for drinking Hot/Cold Water

### ISSUE THREAD

**Issue by MisterWytt** [CleverRaven/Cataclysm-DDA#28699]
**Is your feature request related to a problem? Please describe.**  
I was always curious about how the temperature of foods and drinks were put in place. It's a nice mechanic, but then I realized I can drink a bottle of water that's FRESH OUT OF THE FRYING PAN!

You would think by drinking super hot boiling water it would burn the crap out of your mouth, throat, and your insides, causing HP damage of some sort. I'm rather surprised this was overlooked. If nothing else, it should at least provide a negative joy moodlet for not drinking it room temperature or cold. I imagine cold clean water would be nice and refreshing, thus giving an increased joy moodlet, but ymmv with people and how they prefer their water.

**Describe the solution you'd like**  
What I'd like to happen is provide some kind of negative moodlet/damage for drinking boiling hot water that's fresh out of the frying pan/pot. It's a bit unrealistic to just guzzle bubbling hot water and have no consequences whatsoever.

**Describe alternatives you've considered**  
Can't think of any.

**Additional context**  
Can't think of any as well.

**Comment by Photoloss** [comment]
It's important to distinguish between "warmed up" hot and "freshly boiled" though, and they currently use the same display. I can't think of any context where this would be gameplay-relevant beyond the waiting time itself which could simply be abstracted into the crafting time. In fact who says the current crafting time does not include vigorous stirring to cool it down already considering we can't just leave the pot unattended?

And the "cold" tag is only applied below 4°C or so. Now YMMV but I personally find near-freezing or iced tap water unsuitable for bulk consumption while "cellar-cool" is just fine. A quick refreshment when it's actually hot outside sure but a single "unit" of water in-game is 250ml and players tend to drink several portions at once.

All in all what you propose just sounds like a lot of unnecessary player tedium, can you think of any gameplay-relevant uses for a dedicated mechanic as opposed to simply double-checking the crafting times of "boiled" foods versus "warmed" ones?

**Comment by GroeneAppel** [comment]
This may seem good on paper, but ingame this will result in frustration as the player now has to wait some time before being able to consume any boiled water. In addition it's an action so obviously damaging that it'll carry either a prompt with it or simply wouldnt be possible.

It essentially boils down to this: Would it really add any significant gameplay to the game? You will want this to avoid adding any extra keypresses. So water wouldnt be drinkable at all after boiling for some time. The only use of this would perhaps be a 'hot!' debuff and alternatively an increased drinking time.
