### ISSUE TITLE
Siphoning gas to/from vehicle crashes the game, sometimes

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#28704]
**Describe the bug**  
Siphoning diesel from a cargo truck into a plastic jerrycan causes a crash. Siphonong from same truck into a gallon jug doesn't crash

CRASH LOG FILE: config/crash.log
VERSION: 0.D-498-g5b6a055
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:
    @0x554E45[cataclysm-tiles.exe+0x154E45]
    @0x5559F2[cataclysm-tiles.exe+0x1559F2]
    raise+0x200@0x7FFB6479A9E0[msvcrt.dll+0x2A9E0]
    abort+0x1B@0x7FFB6479EDEB[msvcrt.dll+0x2EDEB]
    IMG_LoadWEBP_RW+0xFDCC1@0x100A2E1[cataclysm-tiles.exe+0xC0A2E1]
    IMG_LoadWEBP_RW+0xFDDA7@0x100A3C7[cataclysm-tiles.exe+0xC0A3C7]
    @0x71F499[cataclysm-tiles.exe+0x31F499]
    @0x73B6D5[cataclysm-tiles.exe+0x33B6D5]
    @0x4E7078[cataclysm-tiles.exe+0xE7078]
    @0x427CFA[cataclysm-tiles.exe+0x27CFA]
    @0x432AEC[cataclysm-tiles.exe+0x32AEC]
    @0xB7FF3B[cataclysm-tiles.exe+0x77FF3B]
    @0x646EA4[cataclysm-tiles.exe+0x246EA4]
    @0x685D7C[cataclysm-tiles.exe+0x285D7C]
    IMG_LoadWEBP_RW+0x4D2619@0x13DEC39[cataclysm-tiles.exe+0xFDEC39]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFB663E3DC4[KERNEL32.DLL+0x13DC4]
    RtlUserThreadStart+0x21@0x7FFB66943691[ntdll.dll+0x73691]

**Comment by Hirmuolio** [comment]
#28700 should fix this.

**Comment by Tharn** [comment]
Had the same thing happen just now. Attempting to fill 500 units of lamp oil into a gallon jug of lamp oil (3250/3750) which was stored in a vehicle trunk. Upon hitting 'U' I got the crash.
```
CRASH LOG FILE: config/crash.log
VERSION: 0.D-498-g5b6a055
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:
    @0x554E45[cataclysm-tiles.exe+0x154E45]
    @0x5559F2[cataclysm-tiles.exe+0x1559F2]
    raise+0x1FB@0x7FFBD13B633B[msvcrt.dll+0x6633B]
    abort+0x2E@0x7FFBD13B99FE[msvcrt.dll+0x699FE]
    IMG_LoadWEBP_RW+0xFDCC1@0x100A2E1[cataclysm-tiles.exe+0xC0A2E1]
    IMG_LoadWEBP_RW+0xFDDA7@0x100A3C7[cataclysm-tiles.exe+0xC0A3C7]
    @0x71F499[cataclysm-tiles.exe+0x31F499]
    @0x73B6D5[cataclysm-tiles.exe+0x33B6D5]
    @0x4E7078[cataclysm-tiles.exe+0xE7078]
    @0x63866F[cataclysm-tiles.exe+0x23866F]
    @0x67BE1C[cataclysm-tiles.exe+0x27BE1C]
    @0x67BFC1[cataclysm-tiles.exe+0x27BFC1]
    @0xB53F0D[cataclysm-tiles.exe+0x753F0D]
    @0xB688C7[cataclysm-tiles.exe+0x7688C7]
    @0x638DEE[cataclysm-tiles.exe+0x238DEE]
    @0x6A3D79[cataclysm-tiles.exe+0x2A3D79]
    @0x6862B9[cataclysm-tiles.exe+0x2862B9]
    IMG_LoadWEBP_RW+0x4D2619@0x13DEC39[cataclysm-tiles.exe+0xFDEC39]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x22@0x7FFBD11C13D2[KERNEL32.DLL+0x13D2]
    RtlUserThreadStart+0x34@0x7FFBD33354F4[ntdll.dll+0x154F4]
```

**Comment by Tharn** [comment]
This also occurs when using a broth recipe that fills a jar.
