### ISSUE TITLE
Use a different default tileset than Livepeople for Android version.

### ISSUE THREAD

**Issue by Acidifie** [CleverRaven/Cataclysm-DDA#28708]
Tested on Shield Tablet (2gb ram) on LineageOS 14.1

The default tileset of 0.D, which is MSX++LIVE_PEOPLE, is way too memory intensive, the game would be force closed by the OS at every new game or even when starting the tutorial. 

![Screenshot_20190314-164340](https://user-images.githubusercontent.com/48562002/54370755-7e454700-4678-11e9-9415-90f23d1a523d.png)

**Comment by curstwist** [comment]
this was brought up on reddit too, crashing on starting world 
[Reddit question post](https://old.reddit.com/r/cataclysmdda/comments/axulme/new_players_come_here_weekly_questions_and/ei72ixm/ )

**Comment by halfahermit** [comment]
Seems like the two best options are RetroDays and ChestHole16. RetroDays is more up to date by ~a year, but it also may not be accessible enough to work as a default tileset.

**Comment by kevingranade** [comment]
Default switched to retrodays by #30302
