### ISSUE TITLE
Game doesn't run, on linux.

### ISSUE THREAD

**Issue by robbie61** [CleverRaven/Cataclysm-DDA#28705]
Everything on linux
I click on 'cataclysm-tiles' or 'cataclysm-launcher' and it doesn't work or do nothing, i try it with the windows version, but another error (using wine).
But when i use curse version it works perfectly, but i don't like ascii and i would prefer understand what i'm doing, right?

OS: Ubuntu 18.04 LTS.
Version: 8613, tiles.
Directory: Downloads.

**Comment by Zireael07** [comment]
You are probably missing sdl2 libraries. Off the top of my head, I needed libsdl2-2.0.0, libsdl2-image-2.0.0 and libsdl2-ttf-2.0.0.

**Comment by robbie61** [comment]
![Captura de pantalla de 2019-03-14 18-34-09](https://user-images.githubusercontent.com/48559972/54378564-dcc5f180-4687-11e9-92fc-7ef2c7b5570a.png)
![Captura de pantalla de 2019-03-14 18-34-16](https://user-images.githubusercontent.com/48559972/54378565-dcc5f180-4687-11e9-9fe4-0c5f1250561f.png)
![Captura de pantalla de 2019-03-14 18-34-18](https://user-images.githubusercontent.com/48559972/54378566-dd5e8800-4687-11e9-87db-7265126f90e2.png)

problem still exist

**Comment by Zireael07** [comment]
That's curious - I am on the same OS and installing those packages solved the problem.
Did you try running from the terminal to see if there's an error message on there?

**Comment by robbie61** [comment]
![Captura de pantalla de 2019-03-14 19-56-41](https://user-images.githubusercontent.com/48559972/54383857-4ef00380-4693-11e9-88f3-73f0078f03e1.png)

**Comment by robbie61** [comment]
OK, i already solve it, thanks.
4 other ppl: 
sudo apt-get install git curl libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0
