### ISSUE TITLE
Wrong noise indication in the UI.

### ISSUE THREAD

**Issue by Vasyan2006** [CleverRaven/Cataclysm-DDA#28703]
**Describe the bug**  
Noise volume shown on the side panel must be equal to ``volume`` calculated in

https://github.com/CleverRaven/Cataclysm-DDA/blob/5b6a0554eb750faf7c0d53c7675af51a538a84d8/src/game.cpp#L10744-L10756

Instead it is ``Sound: 2`` for default character  which has ``volume = 6`` from the code above.
Light step and clumsy mutations set volume to 2 and 10, but in the UI is presented as sound 0 and 6.
RM13 armor set volume to 2 but it is presented as sound 0.

**To Reproduce**  
See noise value in the UI.

**Versions and configuration(please complete the following information):**
 - Game Version: 8608 and self compiled 8613

**Comment by Night-Pryanik** [comment]
Tested right now. I have `Sound: 4` by default when my character walks.

**Comment by Vasyan2006** [comment]
My bad, I got ``Sound: 2`` on homemade build from master branch. Redownloaded 8613 builds:
Windows Curses 64-bit: ``Sound: 6`` as intended
Windows Tiles 64-bit: ``Sound: 4``

**Comment by Night-Pryanik** [comment]
Hmm, that's really weird.

**Comment by esotericist** [comment]
So, while I was looking at something *completely different* I stumbled on a key piece of the puzzle:

First of all, the displayed sidebar is sound heard by player, not the actual real sound in-game. There's a few factors that can affect heard sound, but the biggest is this:

The game has sound attenuation *based on weather*. For instance, during Flurries or Drizzle, sound is reduced by 2. During Rain or Snowing, sound is reduced by 4. And more intense weather has a greater effect.

There's other factors as well, but this seems very likely the explanation for this, and it is almost certainly not an actual bug, just a mechanic not obvious to players.
