### ISSUE TITLE
Firewood source uses materials designated for crafting

### ISSUE THREAD

**Issue by Warlander** [CleverRaven/Cataclysm-DDA#28718]
**Describe the bug**  
Firewood source will keep feeding the fire with materials contained in it even if this means using materials designated for crafting, causing the craft to fail and display an error.

**To Reproduce**  
1. Create a character with 2 survival (to be able to craft tinder)
2. Spawn a firewood source and safe fire place like brazier or oven
3. Spawn matchbox and 41 splintered woods (because it burns quickly, so it's easier to trigger the bug)
4. Use 1 splintered wood and matchbox to start the fire in fire source
5. Try to craft 20 tinder
6. At the end of crafting game will show error about not found cached components

**Expected behavior**  
Either stop the crafting immediately once any needed material is consumed, or if possible craft less of an item, or block firewood source from using cached components

**Screenshots**  
![](https://i.imgur.com/bkW0GN7.png)

**Versions and configuration(please complete the following information):**
- OS: Windows 7
- Game Version: 0.D-498-g5b6a055
- Graphics version: Tiles
- Mods loaded: dda, boats, more survival tools, folding parts pack, vehicle extensions, PK rebalancing

**Comment by NicholasDM** [comment]
Implementing #28775 should fix this as well.
