### ISSUE TITLE
Bionic installation shows success/faulure messages before the operation

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#28714]
**Describe the bug**  
When you install a bionic the success/failure messages come before the operation starts.

**To Reproduce**  
Install a bionic on the autodoc.

**Expected behavior**  
You should get success/failure messages after the operation.

**Screenshots**  
Here I install a Power Storake Mk. II
![operation](https://user-images.githubusercontent.com/22011552/54389979-0abc2d80-46aa-11e9-84e9-db6a6879b3df.png)

**Versions and configuration(please complete the following information):**
 - OS: W10
 - Game Version: 0.D-498-g5b6a055 (tiles)
 - Graphics version: Tiles
 - Mods loaded:   "dda",  "no_npc_food",  "filthy_morale",  "No_Anthills",  "No_Bees",  "No_Fungi",  "vertakoski",  "caliber_in_name",  "deoxymod",  "Urban_Development",  "alt_map_key"

**Additional context**

**Comment by mlangsdorf** [comment]
You're welcome to try resort the logic so the messages appear in the right order.  I tried but couldn't make it happen.

**Comment by RickySandbox** [comment]
Does this only happen when the interface is set to display new messages on Top?

**Comment by Hirmuolio** [comment]
Message log flow is bottom.

**Comment by RickySandbox** [comment]
> Message log flow is bottom.

Oops,  I was half asleep. Thanks for the correction.
