### ISSUE TITLE
Improved inventory key binding

### ISSUE THREAD

**Issue by Melodeiro** [CleverRaven/Cataclysm-DDA#28716]
For me it is very unconvenient to use inventory item binds. Most of the time im using binds just for few items: food, sometime medications, and some custom binds. At the sime, there is a lot of items im don't using binds at all. That leads to a sutiation, when there isn't enough keys, or keys are inconvenient (symbols, or uppercase letters), keys assignations are changing illogically (described later).

Im offering multiple changes, which should improve speed and pleasure, managing inventory:
- An option to generate key binds per item category (for example, food + medications)
- Save custom key binds between worlds/characters. There is some common items, which im using between play sessions.
- Force the same key to be bound to the all items in stack until all of them will be used. Example: when im having 2 bottles with water (2/2), and it has a 'w' bind, when i drink it, it is more logically if it will set 'w' to a unstacked 1/2 bottle, and then if i drink from 1/2 - return to a 2/2 bottle again. Right now it is just rotating between free keys, and 'w' is bound to an empty bottle.
- Maybe blacklist/whitelist for items to free up more available keys (for auto assignment).

**Comment by RickySandbox** [comment]
Are you aware of the option to disable auto generated key bindings for inventory?

**Comment by Melodeiro** [comment]
> Are you aware of the option to disable auto generated key bindings for inventory?

Yes im aware, and disabling it at all isn't an option for me. I mean it would be better, if i can set some categories enabled, while other - disabled (as one of the improvements). Otherwise sometimes there isn't enough keys at all, or convenient lowercase letters.

Im offering such fast style item repeated usage:
"i" -> "find out auto generated key" -> "p" -> "enter (to eat food for example)" -> "i" -> "p" -> "enter" -> ...repeat until food/hunger gone.

**Comment by RickySandbox** [comment]
It only disables auto generated bindings, not all bindings and not those you set yourself. I use this option and clear all of my clothing and other categories of their bindings with "=" Then, they can be used for more important items that I choose based on scenario I'm playing.

**Comment by Melodeiro** [comment]
Seems like you are still completely misunderstand me. I want both: manual set and auto generated (only for some categories).
