### ISSUE TITLE
Crash to desktop report

### ISSUE THREAD

**Issue by Alapaga** [CleverRaven/Cataclysm-DDA#28728]
**Describe the bug**  
The game crashed seemingly randomly, i was eating my junkfood and reading books in a lab when it happened.

**To Reproduce**  
Eat food
Read books
Eat food
Sleep 
Rince and repeat

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-498-g5b6a055
 - Graphics version: Tiles 
 - Mods loaded:   "dda",
  "no_npc_food",
  "filthy_morale",
  "generic_guns",
  "alt_map_key",
  "crazy_cataclysm",
  "no_religious_Texts",
  "no_olg_guns",
  "No_Fungi",
  "more_classes_scenarios",
  "manualbionicinstall",
  "safeautodoc",
  "StatsThroughSkills"

**Additional context**  
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2970507/crash.log)
[Crash save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2970511/Crash.save.zip)

**Comment by ZhilkinSerg** [comment]
Need more info about steps for crash reproduction. Where was your character located, what he was doing and such.

**Comment by Night-Pryanik** [comment]
Closing as non-confirmed for more than a year.
