### ISSUE TITLE
Game crash when making pickled veggy

### ISSUE THREAD

**Issue by Domura** [CleverRaven/Cataclysm-DDA#28724]
**Describe the bug**  
Game suffers some sort of critical error when attempting to craft pickled veggy and crashes. Happens with

**To Reproduce**  
1. Attain the materials to pickle vegetables
2. Attempt to craft delicious pickled greens
3. Instead forge the destruction of reality

**Expected behavior**  
I expected to make pickles.

**Screenshots**  
https://puu.sh/D0dcH/d3ba743ee8.png
https://puu.sh/D0fNd/068e36c15b.png

**Versions and configuration(please complete the following information):**
 - OS: W8.1(?)
 - Game Version: 0.D-498-g5b6a055
 - Graphics version: Tiles
 - Mods loaded: Total base: DDA, No NPC Needs, Filthy Clothes

**Additional**

Issue still present even in newest build under identical circumstances.
https://puu.sh/D0gbZ/d0f9eb6a63.png

**Comment by Hirmuolio** [comment]
#28725 will fix this.

Until that is merged you can ignore the error messages. Eventually (after 6 ignored errors) the crafting will complete. There probably won't be any problems from ignoring the error.

**Comment by Domura** [comment]
Good to know. I actually hit ignore a few times the first time it came up but I suppose I stopped short just literally one click before it passed and assumed it wouldn't go.
