### ISSUE TITLE
"Assertion failed" when batch crafting broth

### ISSUE THREAD

**Issue by drayath** [CleverRaven/Cataclysm-DDA#28739]
**Describe the bug**  
Batch crafting broth (6x broth from veg into 3L jars with npc helper), got a assertion failure.

Version: cataclysmdda-0.D-8616 (Windows 10 64-Tiles)

Assertion Error: src/optional.h, line 45.

Dump: [core.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2972102/core.zip)
CRASH LOG FILE: config/crash.log
VERSION: 0.D-508-g80872c5
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:
    @0x4E1A90[cataclysm-tiles.exe+0xE1A90]
    @0x4E1E31[cataclysm-tiles.exe+0xE1E31]
    raise+0x1A1@0x76446F61[msvcrt.dll+0x56F61]
    IMG_LoadWEBP_RW+0xFDF7B@0xD14CAB[cataclysm-tiles.exe+0x914CAB]

mods:
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "safeautodoc",
  "no_survivor_armor",
  "alt_map_key",
  "mutant_npcs",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "generic_guns",
  "modular_turrets",
  "More_Survival_Tools",
  "Medieval_Stuff",
  "makeshift",
  "growable-pots"

**Comment by Tharn** [comment]
Can confirm.

**Comment by Hirmuolio** [comment]
#28725 fixes this.

You can press the ignore button until the errors go out. The only downside to this is that the empty jar you eventually get probably won't stack with other jars.

**Comment by Tharn** [comment]
Also you might not be able to 'U'nload a container after you've ignored an error like this. I would recommend to wait and not ignore anything.

**Comment by BloodyDaft** [comment]
> #28725 fixes this.
> 
> You can press the ignore button until the errors go out. The only downside to this is that the empty jar you eventually get probably won't stack with other jars.

I'm having a similar issue, but there's no ignore button. It's a complete crash to desktop for me.

**Comment by udAL** [comment]
Same here. A series of errors when crafting canned meat, single or batch.
crash.log:
```CRASH LOG FILE: config/crash.log
VERSION: 0.D-612-g7440da3
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:
    @0x555575[cataclysm-tiles.exe+0x155575]
    @0x556122[cataclysm-tiles.exe+0x156122]
    raise+0x200@0x7FFC8161A9E0[msvcrt.dll+0x2A9E0]
    abort+0x1B@0x7FFC8161EDEB[msvcrt.dll+0x2EDEB]
    IMG_LoadWEBP_RW+0xFDCC1@0x100ECC1[cataclysm-tiles.exe+0xC0ECC1]
    IMG_LoadWEBP_RW+0xFDDA7@0x100EDA7[cataclysm-tiles.exe+0xC0EDA7]
    @0x71EE49[cataclysm-tiles.exe+0x31EE49]
    @0x540F23[cataclysm-tiles.exe+0x140F23]
    @0x40EAF0[cataclysm-tiles.exe+0xEAF0]
    @0x432D0C[cataclysm-tiles.exe+0x32D0C]
    @0xB84350[cataclysm-tiles.exe+0x784350]
    @0x647404[cataclysm-tiles.exe+0x247404]
    @0x684D4C[cataclysm-tiles.exe+0x284D4C]
    IMG_LoadWEBP_RW+0x4D3C29@0x13E4C29[cataclysm-tiles.exe+0xFE4C29]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFC7F2D3DC4[KERNEL32.DLL+0x13DC4]
    RtlUserThreadStart+0x21@0x7FFC81803691[ntdll.dll+0x73691]
```

[Save file here ](https://www.dropbox.com/s/95b9e402pibl55k/Mamaroneck.2.zip?dl=0) Just craft canned meat right there
