### ISSUE TITLE
Strong mixed alcohol recipe defies conservation of mass, leads to infinite ethanol

### ISSUE THREAD

**Issue by AlmondRoll** [CleverRaven/Cataclysm-DDA#28736]
**Describe the bug**  
Strong mixed alcohol recipe produces 7x as much liquid as input strong liquor,
leads to infinite ethanol with sufficient cooking skill and the required tools

**To Reproduce**  
1. Start with 250 ethanol, 2 clean water, still, pot, charged heating tool/fire, and enough containers to hold the resulting mix
2. Make 14 vodka with the ethanol and clean water
3. Turn vodka into 98 strong mixed alcohol
4. Distill strong mixed alcohol into 1750 ethanol and 7 clean water, 7 and 3.5 times the initial amount of ethanol and water respectively.
5. Repeat until desired quantity of ethanol is obtained, like for example, enough to make the required 2700 ether for anesthetic kits.
Process is limited only by time and fuel/tool charges

**Expected behavior**  
Recipe follows law of conservation of mass, i.e. 1 strong liquor (35.7ml) converts to 1 strong mixed alcohol (35.7ml) and not 7 (250ml)

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D stable
 - Graphics version: Tiles
 - Mods loaded: "dda", "no_npc_food", "filthy_morale", "alt_map_key", "mutant_npcs", "boats"

**Additional context**

**Comment by Zombiemanpig** [comment]
Biodiesel: Infinitely Renewable Fuel Resource

**Comment by Reclusive-reptile** [comment]
Can not confirm. 0.D-932-gce983ff crafting 14 of vodka into strong mixed alcohol yields 14 charges, distilled into 250 charges of ethanol and crafted back into 14 charges of vodka.

**Comment by kevingranade** [comment]
Can't confirm.
