### ISSUE TITLE
Some comestibles don't make sense with "frozen" tag

### ISSUE THREAD

**Issue by aawilson** [CleverRaven/Cataclysm-DDA#28737]
**Is your feature request related to a problem? Please describe.**  
It's mostly a display/verisimilitude issue, although there may be a mechanical effect when using the items in recipes as it "defrosts", but essentially some things with the COMESTIBLE tag don't make sense having a "frozen" state (usually because they don't have an appreciable liquid component and are thus always "frozen" at room temperature). Salt is the one I noticed.

**Describe the solution you'd like**  
The end result that would make the most sense is just for salt, cinnamon, etc to never show as "frozen" in the interface, since we never talk about it that way in real life and especially because it shows as "frozen" below 0C and does not above 0C despite not actually being any different, physically (since salt, to continue with its example, is "frozen" until many many degrees above zero).

**Describe alternatives you've considered**  
It looks like there's already a "freezing_point" tag, so the quickest change is probably to add "freezing_point" to anything where it is significantly far away from 0, and then have the display only show "frozen" if the "freezing_point" isn't in some band around room temp (and maybe eventually have "non-frozen" items display as "liquid" or "molten" if their freezing_point is high enough, and if there's ever a future situation where ambient temperature might be high enough for the latter to be a thing).

**Comment by Zireael07** [comment]
Frozen tag is older than freezing point, IIRC, that's why we have both. Freezing points are a recent addition, one that is still being worked out.

**Comment by DoctorGoat** [comment]
the only one I've stumbled upon where I've been like... "wait, what?" was a box of frozen cinnamon

**Comment by aawilson** [comment]
My guess is this applies to most stuff in spices.json, so you'd see it most often on salt, cinnamon, seasoned salt, etc. The "root cause" is clearly that the COMESTIBLE tag determines whether or not something can be "frozen", and there's no tag/logic for determining whether that makes sense per-comestible (which is fine in most cases, since most edible things have enough water in them that they can "freeze" even when they're technically already solid at room temp).

**Comment by n3tr4k** [comment]
Probably similar issue with **paper (cold)**. Usually I have two stacks of paper one is normal and another is cold. Doesn't make sense.
