### ISSUE TITLE
Vehicle Tanks destroy charges upon being filled

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#28740]
**Describe the bug**  
I have a vehicle tank with 10L disinfectant in it. I want to fill it from a bottle of disinfectant (10). After filling, the tank now shows 0.3L (10 units). This happens repeatably every time.

**Expected behavior**  
The tank keeps its charges.

**Versions and configuration(please complete the following information):**
 - OS: Win 8.1 x64
 - Game Version: 0.D-508-g80872c5 (8616)
 - Graphics version: Tiles
 - Mods loaded: Filthy Clothing, Disable NPC Needs, Disable Religious Texts, Prevent Zombie Revivication, StatsThroughSkills

**Additional context**  
Recent regression.

I have found that Cata creates a second item of disinfectant as follows. I can repeatably 'fix' the save to only have a single typeid of disinfectant. I can siphon from it into a bottle and the amounts are correct. But as soon as I refill the tank with the bottled stuff, the tank shows 0.3L.

`{"id":"tank","base":{"typeid":"metal_tank","bday":1169181,"invlet":73,"item_tags":["VEHICLE"],"contents":[{"typeid":"disinfectant","charges":590,"rot":4530093,"last_rot_check":8358227},{"typeid":"disinfectant","charges":10,"rot":4530093,"last_rot_check":8358227}]},"mount_dx":-6,"mount_dy":0,"open":false,"direction":0,"blood":0,"enabled":false,"flags":0,"passenger_id":0,"crew_id":-1,"items":[],"target_first_x":0,"target_first_y":0,"target_first_z":0,"target_second_x":0,"target_second_y":0,"target_second_z":0,"ammo_pref":"null"}`

**Comment by Hirmuolio** [comment]
#28732 fixes this.

**Comment by Tharn** [comment]
Cheers. I'll close after a test.
