### ISSUE TITLE
Dropping items from ledges

### ISSUE THREAD

**Issue by pescepalla** [CleverRaven/Cataclysm-DDA#28747]
**Describe the bug**  
Drop item from a first floor window and it will remain in mid-air instead of falling on the lower z-level.

**To Reproduce**  
1. Drop an item out of a window in a multi-level buiding.

**Expected behavior**  
The item should fall through to the lower z-level. Instead it remains in mid-air.

**Screenshots**  
![Screenshot_2019-03-15_22-56-43](https://user-images.githubusercontent.com/46329185/54464094-a1a1ec00-4775-11e9-8266-c288509eb104.png)

**Versions and configuration(please complete the following information):**
 - OS: Arch linux
 - Game Version: git master
 - Graphics version: tiles
 - Mods loaded: default

**Comment by I-am-Erk** [comment]
Do you have experimental z-levels turned on?

**Comment by pescepalla** [comment]
No I don't. I'm using vanilla.

**Comment by I-am-Erk** [comment]
This is the sort of behaviour that experimental z-levels is for. If you have z-levels turned off, z-levels will not function properly.
