### ISSUE TITLE
2byte text savefoldername cause savegame missing

### ISSUE THREAD

**Issue by clovercorone** [CleverRaven/Cataclysm-DDA#28756]
2byte text savefoldername cause savegame missing

Reproduction
1. Some world create, just worldname is 2byte japanese example:"ワレワレ"
2. Character create in [C]Custom
3. Character create complete, game start
4. [S]Game end withsave
5. [a]read game
6. ワレワレ(0). savegame is missing

solve
7. Game shutdown
8. Rename ./save/someworldfolder 2byte to 1byte text, ex:"ワレワレ" to "wareware"
9. [a]read game wareware(1+) worked.

version 0.D-484-g7fcdb58
Windows 10
Tile

  "type": "MOD_INFO",
  "ident": "user:default",
  "dependencies": [ "dda", "filthy_morale", "no_reviving_zombies", "novitamins", "StatsThroughSkills", "safeautodoc", "More_Survival_Tools", "makeshift", "modular_turrets", "Salvaged_Robots", "alt_map_key", "Urban_Development", "deoxymod", "boats"
  ]

**Comment by ZhilkinSerg** [comment]
Did you try this option?

![image](https://user-images.githubusercontent.com/16213433/54481025-98318600-4840-11e9-99b9-47740b6bc87e.png)

**Comment by clovercorone** [comment]
> Did you try this option?
> 
> ![image](https://user-images.githubusercontent.com/16213433/54481025-98318600-4840-11e9-99b9-47740b6bc87e.png)

Yes this option True default

**Comment by ZhilkinSerg** [comment]
It is not working then and something needs to be updated after #20122.

**Comment by BrettDong** [comment]
What is your Windows system region and language?

**Comment by BrettDong** [comment]
You may try turning file path encoding conversion off if your Windows system language is not Japanese (Japan).

**Comment by BrettDong** [comment]
The ultimate solution to file path encoding issues is to use `std::filesystem` which handles these problems neatly for us (https://en.cppreference.com/w/cpp/filesystem/path/path), but unfortunately it's a C++17 feature.
