### ISSUE TITLE
Crash when trying to butcher a fish corpse

### ISSUE THREAD

**Issue by adamkad1** [CleverRaven/Cataclysm-DDA#28751]
Exactly whats said on tin
Step 1-get fishing rod and fish, or murder a fish mod
step 2-try to butcher
step 3-game crashes
and a shot of crash window https://i.imgur.com/cmDdjRd.png

**Comment by ZhilkinSerg** [comment]
Please provide info on game version and mods used.

**Comment by SolsticeTheTechMarine** [comment]
Could you be specific about the fish? Is it a Giant Salmon, or trout? if neither, what is it?

**Comment by KongMD-Steam** [comment]
I can't reproduce this with vanilla on the latest build.

**Comment by adamkad1** [comment]
Right, i tested a bit, it seems be be issue from PK's

**Comment by dissociativity** [comment]
can people please report issues with PK to me so I can actually fix them?
I hate having to find out issues through closed issues, it's a pain.
