### ISSUE TITLE
A pet dog will eat the hide bag it is given

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#28763]
**Describe the bug**  
A dog will eat the hide bag it is given, presumably because it's food as well as storage. For some reason, this will not cause the items to fall to the ground.

**To Reproduce**  
1. Tame a dog.
2. Give the dog a hide bag through the interface.
3. Fill the bag with things.
4. Wait a while (it was maybe two days for me).
5. Dump all items. The contents is there, and the bag is gone.

**Expected behavior**  
There's two possibilities here. I can see a dog eating the bag, but then the items should fall to the ground. Or the dog should be prevented from eating the bag. Either would make some sense.

**Versions and configuration(please complete the following information):**
 - OS:  Windows 10
 - Game Version: 0.D
 - Graphics version: Tile
 - Mods loaded: DDA, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, StatsThroughSkils, Growable Pots, Makeshift Items Mod, Medieval and Historic Content, More survival Tools, Alternative Map Key, Boats, Folding Parts Pack, Vehicle Additions Pack, Tanks and Other Vehicles.

**Comment by anothersimulacrum** [comment]
The dog's not eating the bag, the bag is rotting away.

**Comment by MrHrulgin** [comment]
Raw hide and hid bags both do not vanish entirely so quickly; in a test world starting in summer for minimal freezing time, both the raw hide and the rotten bag left on the ground were still present (and in the case of the bag, still equippable and usable) after six days.

**Comment by Headjack** [comment]
Functioning realistically. Let him destroy your shoes too.

**Comment by MrHrulgin** [comment]
Ok, but that doesn't answer the items not dropping when it eats the bag.

**Comment by kevingranade** [comment]
It's a Flurkin, run.
