### ISSUE TITLE
STS (StatsThroughSkills) still has HP bug, but occurs very slowly.

### ISSUE THREAD

**Issue by MisterWytt** [CleverRaven/Cataclysm-DDA#28769]
**Describe the bug**  
A few days or so ago, STS was jsonized, and had a couple bugs dealing with HP calculation and the fact it degenerated 1 HP on each Limb per turn. This was fixed for the most part, but under delayed circumstances. Let me explain.

Remember how the bug deteriorated HP by 1 per turn? This still occurs, but at a much slower rate. While maybe not deadly at first, if you have a heavily injured character, their HP will tick down more noticeably. I was wondering what was causing it at first until I tested STS by itself and let the time tick away. Slowly but surely, the degeneration bug is still there.

**To Reproduce**  
1. Start a character with STS enabled (In my case, I started with Str 12, Dex 9, Int 9, Per 9)
2. Wait for a long period of time while keeping an eye on the HP counter on every limb.
3. Watch as, slowly but surely, your HP starts decreasing for seemingly no reason.

**Expected behavior**  
STS is expected to recalculate HP as your stats increase via this mod, not to slowly "poison" your HP away.

In all honesty, if it's the recalculation that's causing that, I can be without it as long as I get the stat boosts and not be a ticking time bomb. It seems to be rather problematic as it is.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-572-gc62f18a (tiles)
 - Graphics version: Tiles
 - Mods loaded: DDA, StatsThroughSkills

**Comment by Night-Pryanik** [comment]
Already reported in #28680, decided to reopen it.
