### ISSUE TITLE
hit a wreck, it moved forever until it hit something else

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#28765]
**Describe the bug**  
Car collisions act like there is no drag? or something.

**To Reproduce**  
hit a vehicle with another vehicle. 

**Expected behavior**  
For vehicles to stop moving after a while after being hit. This is not outer space.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 8621
 - Graphics version: Tiles
 - Mods loaded: Various, is there some easy way of copy pasting my list onto these reports?

**Comment by anothersimulacrum** [comment]
Mods: mods.json in your save file.
Could you upload a save as well?

**Comment by mlangsdorf** [comment]
static drag for stopped vehicles was getting applied incorrectly, causing acceleration.  No need for a save, it's easy to see.
