### ISSUE TITLE
Water pump terrain fills container with ice not water.

### ISSUE THREAD

**Issue by drayath** [CleverRaven/Cataclysm-DDA#28779]
**Describe the bug**  
Fill container with water from a water pump (terrain item)
Container is filled with frozen water (air temp=17C)

**To Reproduce**  
Wield 200L drum (other containers untested)
Examine water pump, select fill container and choose drum.
Drum filled with frozen water.

**Expected behavior**  
Drum fill with water not ice (water should probably be at ground temperature (i.e. 4-10C)

Cataclysm DDA version 0.D-572-gc62f18a (Windows 64 - Tiles)
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "safeautodoc",
  "no_survivor_armor",
  "alt_map_key",
  "mutant_npcs",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "generic_guns",
  "modular_turrets",
  "More_Survival_Tools",
  "Medieval_Stuff",
  "makeshift",
  "growable-pots",
  "Salvaged_Robots"

**Comment by Hirmuolio** [comment]
Found the problem. Something really strange is happening when you fill a large container with liquid from "infinite source" such as pumps or pools of water.

**Comment by Hirmuolio** [comment]
#28784 fixes this.
