### ISSUE TITLE
Boats can't move on flowing water tiles.

### ISSUE THREAD

**Issue by Shodan14** [CleverRaven/Cataclysm-DDA#28777]
Boats (from the boats mod) don't seem to be able to turn or accelarate on flowing water tiles.

To test, find a river, spawn a kayak and try to move around.

**Comment by davidpwbrown** [comment]
Hm. didn't know the boat code used hardcoded terrain ids instead of flags.
I can fix this after ive fixed a few other bugs today.

**Comment by davidpwbrown** [comment]
This seems to be the same behaviour as before the flowing water change, and not related to that.
`        water_tiles += g->m.has_flag( TFLAG_DEEP_WATER, p ) ? 1 : 0;
    }
    // floating if 2/3rds of the vehicle is in water
    is_floating = 3 * water_tiles > 2 * pts.size();`

If the boat is_floating , then you can jump on and it works perfectly fine.
If it's in shallow water, or more than 1/3 in shallow water, then it wont work. 
This is intended.
