### ISSUE TITLE
Vitamin RDAs change after cooking

### ISSUE THREAD

**Issue by M1nks** [CleverRaven/Cataclysm-DDA#28778]
Describe the Bug: 
Currently I'm playing a Wilderness Winter Start on 91 day seasons so I'm taking great care to watch my vitamin intake.  Currently I'm struggling to remove a Vitamin A deficiency.  Many recipies which list high Vitamins in the & menu, when actually cooked have much much lower values or none at all.  Initially I detetected this in the Broth recipies which I thought could simply because the game tracked the soup base ingrediants and changed the end result.  So, I have just now cooked up plain scrambled eggs which has less variation and seen the results.

According to the & menu Scrambled Eggs should give:  Iron 4%, Vitamin A 8%, Vitamin B12 20%.

When cooked and checking the values say: Iron 4%, Vitamin A 4% and Vitamin B12 4%

There are lots of recipies but I like this one because it doesn't have any other ingrediants to possibly throw the calculation off.  I have no idea how it works.

I have just updated to the latest experimental version and tried again but I still see the problem.

I'm playing on Windows 7

**Comment by KorGgenT** [comment]
recipes should inherit from their ingredients. what ingredients did you use?

**Comment by M1nks** [comment]
Powdered eggs.  Originally spider eggs if that makes a difference.  

I found this RDA difference on just about every recipie I looked at but as there are so many ingrediants which can be swaped interchangably I wasn't sure if it made a difference.  I was orignally delighted to see that Woods Soup gave such a huge Vitamin A boost in the & menu but when I made it using either Bone Broth or Pine Needle Tea and then Acorn Meal there was no Vitamin A at all.  

That was why I tried with the most basic recpie available to me with the ingrediants that I had - Scrambled Eggs.

**Comment by M1nks** [comment]
Actually looking at RDAs for Powdered Eggs the RDAs are quite low so I guess that is the answer.  The RDA in the & menu must go off other sorts of eggs.  Well, that makes sense, there's no bug which is a relief.  I guess that the RDAs in the & menu take the highest possible values?  

Thank you KorGgenT.

**Comment by KorGgenT** [comment]
i'm glad i've clarified, then. i will be working on changing the display to show that recipes can have varied outputs. yes, in the future you can close your own issues.
