### ISSUE TITLE
Crash when reloading empty container.

### ISSUE THREAD

**Issue by drayath** [CleverRaven/Cataclysm-DDA#28781]
**Describe the bug**  
Reloading an empty container causes a crash

**To Reproduce**  
Wield an empty container (e.g. 200L drum)
Select container from inventory and select reload.
Crash

**Expected behavior**  
Should show the dialog to select a valid container to reload from.

Version: Cataclysm DDA version cataclysmdda-0.D-8616 (windows 64-tiles)
dump: [core.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2975526/core.zip)
CRASH LOG FILE: config/crash.log
VERSION: 0.D-572-gc62f18a
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x4E1B80[cataclysm-tiles.exe+0xE1B80]
    @0x4E1F21[cataclysm-tiles.exe+0xE1F21]
    SMPEG_error+0x3DAF3@0xB3D825[cataclysm-tiles.exe+0x73D825]
    UnhandledExceptionFilter+0x1A0@0x73CE5F10[KERNELBASE.dll+0x195F10]
    RtlCaptureStackContext+0x1E521@0x7717DA71[ntdll.dll+0x9DA71]
    RtlAreBitsSet+0x58@0x77144198[ntdll.dll+0x64198]

**Additional context**  
Have seen a similar issue (without crash) where reloading an empty container from inventory failed when determining what items where valid to reload from.

Cataclysm DDA version 0.D-572-gc62f18a
21:07:14.093 ERROR : (error message will follow backtrace)
	(@0x4ece68[cataclysm-tiles.exe+0xece68]), 
	(@0x4ed1ca[cataclysm-tiles.exe+0xed1ca]), 
	(@0x4eda3a[cataclysm-tiles.exe+0xeda3a]), 
	(IMG_LoadWEBP_RW+0x110f7f@0xd286bf[cataclysm-tiles.exe+0x9286bf]), 
	(@0x935fa1[cataclysm-tiles.exe+0x535fa1]), 
	(@0x625903[cataclysm-tiles.exe+0x225903]), 
	(@0x5877d2[cataclysm-tiles.exe+0x1877d2]), 
	(@0x587cd9[cataclysm-tiles.exe+0x187cd9]), 
	(@0x5a29af[cataclysm-tiles.exe+0x1a29af]), 
	(@0x5bfc7b[cataclysm-tiles.exe+0x1bfc7b]), 
	(@0x5ccbf5[cataclysm-tiles.exe+0x1ccbf5]), 
	(@0x5a10de[cataclysm-tiles.exe+0x1a10de]), 
	(IMG_LoadWEBP_RW+0x48b2da@0x10a2a1a[cataclysm-tiles.exe+0xca2a1a]), 
	(@0x4013e2[cataclysm-tiles.exe+0x13e2]), 
	(BaseThreadInitThunk+0x24@0x76cc8494[KERNEL32.DLL+0x18494]), 
	(RtlAreBitsSet+0x88@0x771141c8[ntdll.dll+0x641c8]), 
	(RtlAreBitsSet+0x58@0x77114198[ntdll.dll+0x64198]), 
Backtrace emission took 0 seconds.
src/player.cpp:8256 [int player::item_reload_cost(const item&, const item&, long int) const] cannot determine reload cost as Autonomous Surgical Scalpels CBM is neither ammo or magazine
21:07:19.976 ERROR : src/item.cpp:5774 [bool item::reload(player&, item_location, long int)] Tried to reload liquid container with non-liquid.

**Comment by neitsa** [comment]
Do you still have the save file that exhibits the crash?

I haven't been able to reproduce with just the following steps:

* Debug spawn a steel drum (200L)
* Wield it
* Open inventory
* Pick steel drum
* `r`eload

The game says: 

> You don't have any liquid to reload your steel drum (200L)!

![image](https://user-images.githubusercontent.com/4538670/54869253-21dbd900-4d96-11e9-9b27-073f7cfb13f8.png)

There must be something particular to your save game that poses the problem.

**Comment by ZhilkinSerg** [comment]
Should be fixed after #29062 is merged. Please inform us if you still experience the issue.
