### ISSUE TITLE
Player/NPCs should revive as zombies

### ISSUE THREAD

**Issue by chaisawlajatang** [CleverRaven/Cataclysm-DDA#28787]
**Is your feature request related to a problem? Please describe.**  
The lab notes clearly point the total blob infestation and describe the resuscitation process in a great detail. Some survivors tell about their companions revived after death. The mutations occur because of the blob, so the player is infested too. So both the player (via deathcam?) and NPCs should go back as zombies in a few minutes or hours after their death, but they don't.

**Describe the solution you'd like**  
Both the player (via deathcam?) and NPCs should go back as zombies in a few minutes or hours after their death. Some sort of pulping should prevent this.

**Describe alternatives you've considered**  
Leave everything as is.

**Additional context**  
Pulping human corpse (to prevent zombification) should probably give moral debuff to non-cannibals and such.

**Comment by Meuka** [comment]
As far implementation, perhaps the corpse could revive as a survivor zombie with some extra data for their name, physical traits, and mutations/bionics? 

I suppose eventually the mutations/bionics they have could also determine what zombie type they become as well.

**Comment by n3tr4k** [comment]
That would actually solve this issue a bit :) #28828 By zombie-you eating yourself
