### ISSUE TITLE
Degenerating HP (Without STS)

### ISSUE THREAD

**Issue by MisterWytt** [CleverRaven/Cataclysm-DDA#28795]
**Describe the bug**  
I've been having a difficult issue. What I first thought was the source to STS, it seems I was completely mistaken.

I seem to have a bug that occurs randomly in my playthroughs. I haven't been able to replicate it with successful results, but I managed to pin it down in one of my recent saves.

Here's how it goes. Every so often each of my limbs will lose a point of HP. This happens more frequently when I'm waiting in place. Along with that, I get 1 point of Pain. I'm made aware of this thanks to the Self-Aware trait.

I've managed to tie it to my save file which I have not been able to replicate in other worlds and chars that I've tested. And I'm at a loss on what mod or function may be causing it, as it either pops up, or it doesn't.

**To Reproduce**  
1. Grab the save file that's attached to this report.
2. Load the game up with its required mods, and just wait in place with the | key, keeping a careful eye on both the HP of your limbs, and your pain meter.
3. When successful, you'll see every limb take a point of damage, and you yourself take a point of pain from seemingly nowhere.

**Expected behavior**  
You aren't supposed to take damage or pain (Unless otherwise indicated)

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-576-g6d4a4ba (tiles)
 - Graphics version: Tiles
 - Mods loaded:
  "dda",
  "no_npc_food",
  "aftershock",
  "SD_Magcrafting",
  "realguns",
  "SD_Magcrafting_Realguns_Extension",
  "FIC_Weapons",
  "growable-pots",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "modular_turrets",
  "PK_REBALANCE",
  "Salvaged_Robots",
  "alt_map_key",
  "Cata++",
  "npc_traits",
  "crazy_cataclysm",
  "mutant_npcs",
  "national_guard_camp_edit",
  "mapgen_demo",
  "more_locations",
  "FujiStruct",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "DP_REMIX_INDICATORS",
  "no_religious_Texts",
  "no_olg_guns",
  "no_pipe_guns",
  "more_classes_scenarios",
  "manualbionicinstall",
  "no_reviving_zombies",
  "safeautodoc"

Additional

Remember: STS isn't loaded in this playthrough, and yet I still have this degeneration bug. Something or some bugged mechanic has to be causing this. And I just can't pin it down reliably. Sometimes it happens, sometimes it doesn't.

[Save File.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2977404/Save.File.zip)

**Comment by Zireael07** [comment]
Is there anything radiating around? Waste dump? Artifacts?

**Comment by ZhilkinSerg** [comment]
Does not reproduce for me on latest `master` - hp won't go down and no pain increase while waiting a lot.

You have a bunch of third-party mods (which I didn't use), so it could be their fault - for example, PK has [`Quivering Bowels`](https://github.com/pisskop/PKs_Rebalancing/blob/3c28b017202df1e52cba6afe41a7b66a9ca21316/pk_effects.json#L457) effect which can cause pain. It is also possible there are items in one of the mods which have flag like `RADIOACTIVE`.

**Comment by MisterWytt** [comment]
Try it with PK's loaded. I removed that mod and the random acts of pain and damage suddenly stopped. 

As for status effects and irradiation, no, I didn't get any of those status effects while waiting. I even carefully timed it where I got the damage at the exact time it happened.

**Comment by ZhilkinSerg** [comment]
If it is PKs - we can't help you here.

**Comment by MisterWytt** [comment]
Yeah. I've reloaded the map and char several times now with and without PK's. It's being the culprit. Debug menu also says my Healing is in the negatives.

I'll post a report over at PK's and see if something can be done.

**Comment by ZhilkinSerg** [comment]
Try here 
- https://discourse.cataclysmdda.org/t/pks-rebalancing-unofficial-patch/16060/124

**Comment by Night-Pryanik** [comment]
Closing then.
