### ISSUE TITLE
Issues with deaf characters

### ISSUE THREAD

**Issue by Noah-Smitty** [CleverRaven/Cataclysm-DDA#28799]
**Describe the bug**  
Deaf characters hear *crunch*, *clank*, etc.  They are interrupted by footsteps of zombies and npcs.  I can see the noise value of noises that I make.

**To Reproduce**  
1. Be a deaf character
2. Hear footsteps
3. Or smash things

**Expected behavior**  
I expect no sound interruptions (such as "You hear footsteps! Stop reading? (Y/N)"), also no *you hear... etc.* messages.  Also no indication of my noise level.

**Screenshots**  
![image](https://user-images.githubusercontent.com/7375413/54553145-f321c500-4987-11e9-8237-850e97082769.png)

**Versions and configuration(please complete the following information):**
 - OS: Win 10
 - Game Version: 0.d something
 - Graphics version: Can't remember, too lazy to look up
 - Mods loaded:

**Comment by ZhilkinSerg** [comment]
Are you using https://github.com/ZhilkinSerg/Cataclysm-DDA-LUA? We don't have `Deaf` trait in vanilla.

**Comment by Ramza13** [comment]
Just tested and deaf seems to work fine to me.

**Comment by Saicchi** [comment]
Can't replicate on `0.E-10134-g9b256f63cd [64-bit]`.
Created a deaf character and I could not hear footsteps, shuffling nor glass being broken from zombies in a place where I could not see them.

**Comment by Night-Pryanik** [comment]
Ok, closing until reconfirmed.
