### ISSUE TITLE
Crash on filling keg with gas

### ISSUE THREAD

**Issue by reed501** [CleverRaven/Cataclysm-DDA#28794]
**Describe the bug**  
I was filling a keg with gasoline from a nearby car. I tried siphoning out from one tank into the keg and it went fine. Then I tried siphoning from the other tank, and the game crashed. This happened twice.

**To Reproduce**  
1. Fill a keg with gasoline
2. Fill a keg with gasoline again

**Expected behavior**  
I thought the keg would get filled, but it did not.

**Screenshots**  
![Screenshot 2019-03-17 at 22 50 24](https://user-images.githubusercontent.com/12606597/54509820-17d65800-4908-11e9-870f-52146b3c9fe8.png)

**Versions and configuration(please complete the following information):**
 - OS: Debian Container inside ChromeOS
 - Game Version: 0.D-498-g5b6a055
 - Graphics version: Tiles
 - Mods loaded: Default

**Additional context**  
Error:
cataclysm-tiles: src/optional.h:45: const T& cata::optional<T>::get() const [with T = islot_comestible]: Assertion `full' failed.
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.D-498-g5b6a055
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

        ./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x25) [0x7c2e02]
        ./cataclysm-tiles() [0x7b512d]
        ./cataclysm-tiles() [0x7b532e]
        /lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0x7fef69ef8060]
        /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7fef69ef7fff]
        /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fef69ef942a]
        /lib/x86_64-linux-gnu/libc.so.6(+0x2be67) [0x7fef69ef0e67]
        /lib/x86_64-linux-gnu/libc.so.6(+0x2bf12) [0x7fef69ef0f12]
        ./cataclysm-tiles(_ZNK4cata8optionalI16islot_comestibleE3getEv+0x26) [0x79ad54]
        ./cataclysm-tiles(_ZN4item24set_item_specific_energyEf+0x20) [0x8eb294]
        ./cataclysm-tiles(_ZN4item9fill_withERS_l+0x1b3) [0x8f9c69]
        ./cataclysm-tiles(_ZN9Character9pour_intoER4itemS1_+0xf4) [0x76422a]
        ./cataclysm-tiles(_ZN4game23perform_liquid_transferER4itemPK8tripointPK7vehicleiPK7monsterR15liquid_dest_opt+0x254) [0x8417dc]
        ./cataclysm-tiles(_ZN4game13handle_liquidER4itemPS0_iPK8tripointPK7vehicleiPK7monster+0x189) [0x86c853]
        ./cataclysm-tiles() [0xcceceb]
        ./cataclysm-tiles(_ZN12veh_interact8overviewESt8functionIFbRK12vehicle_partEES0_IFbRS1_EE+0x198b) [0xcd7559]
        ./cataclysm-tiles(_ZN12veh_interact9do_siphonERSs+0xfa) [0xcd7a5e]
        ./cataclysm-tiles(_ZN12veh_interact12do_main_loopEv+0x1dd) [0xcdb919]
        ./cataclysm-tiles(_ZN12veh_interact3runER7vehicleii+0x1f) [0xcdbbe5]
        ./cataclysm-tiles(_ZN4game12exam_vehicleER7vehicleii+0x13) [0x83ed77]

        Attempting to repeat stack trace using debug symbols...
        sh: 1: addr2line: not found
        backtrace: addr2line failed

**Comment by Hirmuolio** [comment]
This was fixed in build 8619. Update the game.

**Comment by Night-Pryanik** [comment]
@reed501 Can you confirm?

**Comment by reed501** [comment]
I just updated and yes, it is fixed. Sorry for wasting your time.
