### ISSUE TITLE
0.D crash when loading world

### ISSUE THREAD

**Issue by shadowski590** [CleverRaven/Cataclysm-DDA#28792]
**Describe the bug**  
When trying to load a world it will get to the finalizing step and crash with a segmentation fault.

**To Reproduce**  
For me this happens 100% of the time
1. Create a world
2. Attempt to make character

**Expected behavior**  
Load into the game or the character creator

**Screenshots**  

**Versions and configuration:**
 - OS: Windows 10 64 bit
 - Game Version: 0.D-576-g6d4a4ba
 - Graphics version: Tiles
 - Mods loaded: Filthy Clothing, Disable Npc Needs, Simplified Nutrition, Lua (Base, Items, Skills, and Traits), Bionics Systems Mod, Extended Realistic Guns, Deadleaves' Fictional Guns, Makeshift items Mod, More Survival Tools, Mundane Zombies, Prevent Zombie Revivicaation, StatsThroughSkills

**Additional context**  
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2976431/crash.log)
I'm running this through the CDDA Game Lancher

**Comment by Hawkaer** [comment]
I may be incorrect about this, but remove the Lua mods, I believe they dropped support for those mods. I had the same problem when I was using them.

**Comment by shadowski590** [comment]
That fixed it, thanks.
