### ISSUE TITLE
Bulletin board after fully upgrading faction camp causes Nothing tile.

### ISSUE THREAD

**Issue by Crafty908** [CleverRaven/Cataclysm-DDA#28808]
**Describe the bug**  
Asking the camp overseer to create a bulletin board after fully upgrading survivor base tile creates a nothing tile, erasing all upgrades such as palisades, tents, and any player constructed furniture. 

**To Reproduce**  
1. Fully upgrade a survivor camp tile
2. Ask the overseer to create a bulletin board and do something more useful
3. Tile changes to a nothing tile

**Expected behavior**  
The camp overseer creates a bulletin board and the camp retains its upgrade level

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-636-g88b951f Build 8626
 - Graphics version: Tiles
 - Mods loaded: STS, Boats, Disable NPC Needs, Simplified Nutrition, Makeshift Items Mod, More Survival Tools, Folding Parts Pack, Vehicle Additions Pack, Tanks and Other vehicles,

**Additional context**  
@davidpwbrown

**Comment by davidpwbrown** [comment]
currently investigating.
Appears there is a crash when creating a new camp aswell.
Which was not present before merging - perhaps recent panels PR changed editmap.cpp somehow, cant see how though, but will dig further.

**Comment by davidpwbrown** [comment]
Ok there was a problem with editmap caused by the change in terrain window width , when I fixed that crash, and then tested a fully upgraded camp with a camp manager , and asked him to resign, I didnt get it turning to a "nothing" .
So I think fixing the crash also fixed this. I hope. 
If you have a savegame to provide I can try that.
