### ISSUE TITLE
Bring NPCs to target overmap using long distance teleport

### ISSUE THREAD

**Issue by Axema** [CleverRaven/Cataclysm-DDA#28804]
**Is your feature request related to a problem? Please describe.**  
It's annoying when you need to walk or drive along with your NPCs just for debug purposes

**Describe the solution you'd like**  
Bring all your NPCs that follows you to the selected overmap with the long distance teleport debug.

**Describe alternatives you've considered.**
That's all.

**Additional context**  
This should ease the players whether they need to debug and test for bugs.

**Comment by kevingranade** [comment]
No debug feature requests.
If you want to add it, go ahead.
