### ISSUE TITLE
Accurized damage bonus broken for most guns

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#28814]
**Describe the bug**  
Most of the guns currently do not show increased damage when being accurized. Here's a list of all the guns that I can currently verify as showing 0 damage as their accurized version (probably not complete). Note that guns that have around -4 damage normally may be correct in having 0 damage when accurized. I did not comb through the list for those.

As an example: M1 Garand has 0 damage bonus by default. Accurized M1 Garand still has 0 damage bonus.

`AK-74M, AR-15, Beretta ARX-160, Beretta M9, Browning Automatic Rifle, Colt M1860 Army, Colt M1861 Navy, FN P90, H&K G36, H&K MP7, L12 Defender, L39, L39-460, L39B, L39B-45, M1 Garand, M1911, M2 Browning HMG, M2010 ESR, M202 FLASH, M240, M249, M3 recoilless rifle, M320 stand alone launcher, MAC-10, Makarov PM, Milkor MGL, Mosin-Nagant 1891/30, Mossberg 500, RM103A automagnum, RM20 autoshotgun, RM2000 submachine gun, RM228 PDW, RM232 IDW, Remington 700, Remington 870, Ruger Redhawk, S&W 22A, S&W 500, S&W 619, SIG 552, SIG P226, SIG Pro .40, SIG Sauer P230, Saiga-12, Savage 111F, Skorpion Vz. 61, Skorpion Vz. 82, TEC-9, Taurus Pro .38, TDI Vector, Tokarev TT-33, USP .45, Walther PPK, Weatherby Mark V, Winchester Model 70, briefcase SMG, double barrel shotgun, flamethrower, flaregun, shotgun revolver, single barrel shotgun, triple-barrel 40mm launcher, tube 40mm launcher.`

**To Reproduce**  
Find one of those listed guns.
Check its damage bonus and dispersion.
Accurize it.
Check the stats again.

**Expected behavior**  
The damage bonus goes up by several points when accurized. Dispersion gets reduced.

**Versions and configuration(please complete the following information):**
 - OS: Win 8.1 x64
 - Game Version: 8628
 - Graphics version: Tiles
 - Mods loaded: Filthy Clothing, Disable Npc Needs, Disable Religious Texts, Prevent Zombie Revivication, StatsThroughSkills

**Comment by KongMD-Steam** [comment]
Confirmed in vanilla Cataclysm on build 8627. I tested w/ these guns:
AR-15, MAC-10, Remington 700
![Screenshot - 3_19_2019 , 7_43_51 AM](https://user-images.githubusercontent.com/36478131/54603695-e7dca100-4a3c-11e9-8d1c-30977a004b87.png)

**Comment by dissociativity** [comment]
I'm curious as to how accurizing a gun would increase damage in reality and not just.. make it more accurate anyway?

**Comment by Photoloss** [comment]
> I'm curious as to how accurizing a gun would increase damage in reality and not just.. make it more accurate anyway?

Depends on what exactly "accuracy" and "damage" represent. We have no "subsystem damage" on monsters save for "headshot" crits and no way of targeting specific limbs on NPCs. Therefore your ability to accurately hit specific vitals or vulnerable areas is abstracted somewhere in between those two stats.

Several weapon mechanics are indeed quite "game-y" though, for example "reinforcing" a Halligan bar will not improve its offensive capability anywhere near as much as sharpening a sword to shaving sharp.

**Comment by kevingranade** [comment]
Damage should not be going up, "goodness" of a hit is calculated seperately
from damage amount.

**Comment by Tharn** [comment]
If we're looking for realism, I agree. It would make the most sense if improving gun health to reinforced status did not change damage but did 1. reduce dispersion and 2. improve durability by +1. Since durability is mostly just related to how often a gun misfires and accurizing includes gun maintenance, cleaning and oiling, it would realistically assure peak performance with less misfires.

This issue ties into #24158. As you can see, it's an old issue that no one really wants to look at guns. Damage bonuses for guns are all over the place. Lots of 0 damage stats and some strange outliers. I would love to see more granular numbers in the low positive and negative ranges thrown in there too.
