### ISSUE TITLE
No Freeze Mod Crash on World startup/Gen

### ISSUE THREAD

**Issue by Lexingtondavid** [CleverRaven/Cataclysm-DDA#28819]
**Describe the bug**  
Upon world loading, random or preconstructed character, any world that has the launcher's No-Freezing-Master mod causes the game to crash upon loading. Disabling other mods and loading up a world with only the no freezing mod will still crash the game.

**To Reproduce**  
1. construct a world that has the No-Freezing mod enabled
2. throw a character into it (Randomized is easier for testing)
3. game will crash after attempting to load the mod.

**Expected behavior**  
Upon reaching the mod for loading, the game will display the following red text: 

 DEBUG    : JSON contains circular dependency. Discarded 3 objects:
{
    "type": "COMESTIBLE",
    "id": "mushroom_poison",
    "name": "mushroom",
	"copy-from": "mushroom_poison",
	"freezing_point": -1000
  },{
    "type": "COMESTIBLE",
    "id": "mushroom_magic",
    "name": "mushroom",
	"copy-from": "mushroom_magic",
	"freezing_point": -1000
  },{
    "type": "COMESTIBLE",
    "id": "dry_mushroom_magic",
    "name": "dried hallucinogenic mushroom",
	"copy-from": "dry_mushroom_magic",
	"freezing_point": -1000
  },
 
 FUNCTION : void DynamicDataLoader::load_deferred(DynamicDataLoader::deferred_json&)
 FILE     : src/init.cpp
 LINE     : 120

Followed by a pop up that assembles a crash log:

CRASH LOG FILE: config/crash.log
VERSION: 0.D-711-ga159ebb
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x555A05[cataclysm-tiles.exe+0x155A05]
    @0x5565B2[cataclysm-tiles.exe+0x1565B2]
    SMPEG_error+0x4B034@0xE2CF90[cataclysm-tiles.exe+0xA2CF90]
    _C_specific_handler+0x96@0x7FFA98D61E26[ntdll.dll+0x81E26]
    _chkstk+0x9D@0x7FFA98D7349D[ntdll.dll+0x9349D]
    RtlRaiseException+0xF67@0x7FFA98D348D7[ntdll.dll+0x548D7]
    KiUserExceptionDispatcher+0x3A@0x7FFA98D7262A[ntdll.dll+0x9262A]
    @0x77189A[cataclysm-tiles.exe+0x37189A]
    @0x774515[cataclysm-tiles.exe+0x374515]
    @0x6DE556[cataclysm-tiles.exe+0x2DE556]
    @0x653E86[cataclysm-tiles.exe+0x253E86]
    @0x67D725[cataclysm-tiles.exe+0x27D725]
    @0x82EF67[cataclysm-tiles.exe+0x42EF67]
    @0x831AD0[cataclysm-tiles.exe+0x431AD0]
    IMG_LoadWEBP_RW+0x4D6540@0x13F5340[cataclysm-tiles.exe+0xFF5340]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x22@0x7FFA98A513D2[KERNEL32.DLL+0x13D2]
    RtlUserThreadStart+0x34@0x7FFA98CF54F4[ntdll.dll+0x154F4]

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 
 - Game Version: 0.D-711-ga159ebb 
 - Graphics version: Tiles, happens regardless of tilepack
 - Mods loaded: ( While i did test it out without the extra mods, this is my original modpack )
[
  "dda",
  "no_npc_food",
  "filthy_morale",
  "dda-lua",
  "dda-lua-fun",
  "dda-lua-items",
  "dda-lua-skills",
  "dda-lua-traits",
  "aftershock",
  "Tolerate_This",
  "craftgp",
  "FIC_Weapons",
  "realguns",
  "growable-pots",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "DinoMod",
  "DracoDogMod",
  "modular_turrets",
  "Salvaged_Robots",
  "Cata++",
  "Mining_Mod",
  "mutant_npcs",
  "Ninja",
  "national_guard_camp_edit",
  "more_locations",
  "boats",
  "cars_to_wrecks",
  "deoxymod",
  "blazemod",
  "necromancy",
  "more_classes_scenarios",
  "RL_Classes",
  "sleepdeprivation",
  "no_freeze",
  "BIGOLBUILDING"
]

**Comment by AMurkin** [comment]
Look at #28792

**Comment by Lexingtondavid** [comment]
Again, as i stated before, I removed the LUA mods, and the crashing still remains.

**Comment by ZhilkinSerg** [comment]
We cannot provide support for third party mods here. I suggest you to address the issue to mod author to update it for newer game version - https://discourse.cataclysmdda.org/t/no-freeze-mod-release/16709

**Comment by Poragon** [comment]
Whoops, forgot to comment here in retrospect. For all those gazin' in, No-Freeze v1.52 forwards has this issue corrected!
