### ISSUE TITLE
It more straining to pull a cart full of items than carrying them on youself

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#28816]
**Describe the bug**  
I'm playing as str4 char, and have a big problem with hauling logs and steel frames around, so i built a wooden cart, but the pain is actually higher this way:

> It takes some time to move the FAT BUDDY.
> You strain yourself to move the FAT BUDDY!

FAT BUDDY is 57kg.

**Expected behavior**  
Even a weakling should be able to push a few hundreds kg around without incurring lots of pain given they have wheels in place.

**Versions and configuration(please complete the following information):**
0.C-37610-g8ea7031265-dirty

**Additional context**  
[save](https://github.com/CleverRaven/Cataclysm-DDA/files/2983835/2019.03.17.zip)

**Comment by l29ah** [comment]
Pavement.

**Comment by jeremyshannon** [comment]
A quick test: 6 logs with 4 strength, carried in a MOLLE/survivor duffel bag setup, I get about thirty steps before stamina runs out and pain starts up.
 Put 'em in a shopping cart, and it works right, stamina stays full, no strain.
 Take the wheels off the cart so it scapes along the ground: stamina stays full, but repeated straining causes pain.
 Does your FAT BUDDY have "enough" wheels in the status screen?

**Comment by l29ah** [comment]
Yes.

**Comment by jeremyshannon** [comment]
There's definitely something weird going on.

 I checked your save, (totally missed seeing it last night) and it works fine if I put a single set of casters on FAT BUDDY, with a rolling drag (when loaded) of like 2.5, but with your original wheels it's a strain now and then.
 With a pair of 27" bicycle wheels, the loaded rolling drag drops to a puny 0.04, and the cart is completely unmoveable, as if rolling drag were being inverted.

Rebuilding the FAT BUDDY in my Testworld reproduces the problem.

**Comment by l29ah** [comment]
Still an issue on today's master and effectively makes low-strength characters unplayable since they cannot carry much both on themselves and in the dragged vehicles.

**Comment by kevingranade** [comment]
This is where the checks are happening, some of the math in here is definitely a bit odd.
https://github.com/CleverRaven/Cataclysm-DDA/blob/219b12f3de88348f759d954938f9834d5f403b7f/src/grab.cpp#L20
