### ISSUE TITLE
Crash when opening map

### ISSUE THREAD

**Issue by drayath** [CleverRaven/Cataclysm-DDA#28825]
**Describe the bug**  
Opened map. Crash.

Maybe related, had some earlier errors when opening map that i selected Ignore for:
src/savegame.cpp:828 [void overmap::unserialize(std::istream&)] Loaded bad ter! ter cemetery_4square_00
18:58:21.494 ERROR : src/savegame.cpp:828 [void overmap::unserialize(std::istream&)] Loaded bad ter! ter cemetery_4square_10
18:58:24.567 ERROR : src/savegame.cpp:828 [void overmap::unserialize(std::istream&)] Loaded bad ter! ter cemetery_4square_01
18:58:25.319 ERROR : src/savegame.cpp:828 [void overmap::unserialize(std::istream&)] Loaded bad ter! ter cemetery_4square_11

--

Version:  cataclysmdda-0.D-8616 (Windows 10-64 Tiles)
Mods:   "dda",  "no_npc_food",  "filthy_morale",  "novitamins",  "safeautodoc",  "no_survivor_armor",  "alt_map_key",  "mutant_npcs",  "more_locations",  "FujiStruct",  "Urban_Development",  "generic_guns",  "modular_turrets",  "More_Survival_Tools",  "Medieval_Stuff",  "makeshift",  "growable-pots",  "Salvaged_Robots"

--
Dump: [core.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2985340/core.zip)
CRASH LOG FILE: config/crash.log
VERSION: 0.D-572-gc62f18a
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x4E1B80[cataclysm-tiles.exe+0xE1B80]
    @0x4E1F21[cataclysm-tiles.exe+0xE1F21]
    SMPEG_error+0x3DAF3@0xB3D825[cataclysm-tiles.exe+0x73D825]
    UnhandledExceptionFilter+0x1A0@0x76C85F10[KERNELBASE.dll+0x195F10]
    RtlCaptureStackContext+0x1E521@0x777CDA71[ntdll.dll+0x9DA71]
    RtlAreBitsSet+0x58@0x77794198[ntdll.dll+0x64198]

**Comment by KorGgenT** [comment]
we just merged a fix for this. #28823 before the build comes out you can just set the pixel minimap height to 22. if this is a different problem than the one related to the pixel minimap, please either ping me or open another pr

**Comment by drayath** [comment]
@KorGgenT This was for opening the main map (keypress m) rather than the mini-map. I haven't been able to reproduce this from my last save so can't test if this fix resolves the issue.

**Comment by ZhilkinSerg** [comment]
Should be fixed by #29007.
