### ISSUE TITLE
"It looks like you woke up before your alarm" erroneous

### ISSUE THREAD

**Issue by qtquazar** [CleverRaven/Cataclysm-DDA#28836]
Character with *heavy sleeper* and *poor hearing* and *insomniac* traits consistently oversleeps time period (expected) but is frequently notified that he has woken up before alarm, when clearly he's way over expected (often several hours) alarm time. 

Thought maybe this was down to it taking extra long to fall asleep, so alarm was being counted from actual point of sleep (which would be questionable design, but understandable), but further testing (dead tired, OR managed to fall asleep right away on 'tired' status) reveals this is not the case.

Thank heavens I don't have a day job in the post-apocalypse.

**To Reproduce**  
1. Make a player with the above three traits.
2. Go to sleep.
3. Wake up, check message.

**Expected behavior**  
Overslept alarm message.

**Versions and configuration(please complete the following information):**
0.D

**Comment by n3tr4k** [comment]
I have the same just only with "heavy sleeper" trait

**Comment by neitsa** [comment]
I'm going to take a look at it. No promise, just taking a look to see if I can understand what's going on.
