### ISSUE TITLE
Can't disassemble Frontier Starter Kit 

### ISSUE THREAD

**Issue by Fourest** [CleverRaven/Cataclysm-DDA#28849]
**Describe the bug**  
Player can't disassemble Frontier Starter Kit 

**To Reproduce**  
1. Find Frontier Starter Kit
2. Try to disassemble

**Expected behavior**  
Frontier Starter Kit is disassebled

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-612-g7440da3
 - Graphics version: Tiles
 - Mods loaded: A lots of mods

**Comment by Leviathan21** [comment]
aint you supposed to activate one

**Comment by Fourest** [comment]
I can't do it

**Comment by ZhilkinSerg** [comment]
> A lots of mods

Could be the reason.

**Comment by l29ah** [comment]
I don't think "Frontier Starter Kit" is a part of CDDA.

**Comment by NotFuji** [comment]
> I don't think "Frontier Starter Kit" is a part of CDDA.

It is.

Latest experimental, I can butcher it just fine, but it's missing an the disassembly action.

**Comment by Vormithrax** [comment]
I believe this happens when your world setup includes blacklist mods like 'No Fictional Guns'. Since the Frontier Starter kit contains Leadworks guns, which are fictional, it won't allow you to disassemble the kit.

**Comment by pjf** [comment]
Found one last night and was able to disassemble it just fine. Not playing with any mods, though.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 14 June 2019.
