### ISSUE TITLE
Mini-Flamethrower CBM lights fuelless fires

### ISSUE THREAD

**Issue by Photoloss** [CleverRaven/Cataclysm-DDA#28855]
**Describe the bug**  
Unlike most lighters the mini-flamethrower can be used on empty tiles to light a fully-fledged fire. It can burn for several minutes and deal fatal damage to creatures. Nothing in the usage cost provides any combustible fuel to sustain such a blaze, nor is there any easy explanation to add one to a finger implant.

**To Reproduce**  
1. Install Mini-Flamethrower CBM
2. Use it on an empty, non-flammable tile such as a road
3. Wait for several minutes by holding the "pass turn" button, optionally kite a monster into the flames.

**Expected behavior**  
A purely electrical heater could potentially dry out and ignite certain living plants where a match might fail, but ultimately there needs to be enough fuel to actually maintain combustion. Harvesting metabolic waste, blood sugar or body fat *might* be a valid explanation but this would incur a cooldown on repeated uses and/or a metabolic cost on each activation (similar to active mutations). 

Otherwise, and more suited to the implied technological context, the CBM should be unusable on empty tiles just like other lighters. Its current usage time and energy cost implies a power consumption of 1500W which is on the low end for modern toasters, kettles or hairdryers and thus barely enough to cause combat-relevant injuries on direct application. At this point it ought to be renamed as well since anything vaguely resembling a flamethrower definitely needs a stream of fuel projected at the target.

**Comment by Xpyder** [comment]
maybe it could launch a quick, short lived, burst of fire that can ignite combustibles on tiles it hits?

**Comment by Photoloss** [comment]
Define "fire". The common understanding involves both air/oxygen and a combustible fuel, where does this fuel come from? Pre-heating air/steam to ignition temperatures to release a short burst is neither safe nor effective compared to a continuous resistive heating+fan setup.

**Comment by Xpyder** [comment]
> where does this fuel come from? 
A short lived flame (1 roundish) can be fueled by [suspension of disbelief](https://tvtropes.org/pmwiki/pmwiki.php/Main/WillingSuspensionOfDisbelief).  The main purpose would be to light any combustible materials in the affected cells

**Comment by kevingranade** [comment]
Why would you start a nonsense fire instead of just igniting the fuels in question?
If implementation wise you want to make an ephemeral fire, it should only last until the end of the next field processing tick, i.e. it should disappear before the player has a chance to see it.

**Comment by Xpyder** [comment]
So the player understands what happened, that it worked correctly, why it went out, and what the range is, without having to meticulously lay out clothing to test it's invisible effect.

**Comment by Xpyder** [comment]
Also, to clarify
• I'm operating under the _assumption_ that it creates a 3x3 area of flame like other small flamethrowers, if its a 1x1 area specifically then that conveyance happens using the targeting (I wonder if targeting could show a ghost or expanded box for aoe effects? hmm..  but that would be beyond the scope of this issue)
• It doesn't have to be a real fire.  Just something that looks like it (or close enough™) to the player.  How the ignition is actually coded is a different matter entirely, and I know there's some weirdness where fuel-less fires still manage to burn for too long so I agree it ideally wouldn't spawn a "real" fire, just something that looks like it for a sec so the player doesn't think it misfired and failed to mention it in the log.

**Comment by Photoloss** [comment]
@Xpyder nope, 1 tile of fire adjacent to you, basically as if you were using a lighter except it also works on non-flammable terrain.
