### ISSUE TITLE
Crash to desktop upon going upstairs on a mansion with a companion NPC

### ISSUE THREAD

**Issue by Alapaga** [CleverRaven/Cataclysm-DDA#28850]
**Describe the bug**  
Pretty straight forwards, there's an NPC character on the kitchen of the mansion (the starting NPC character that i successfully recruited) I ask him to follow me around and upon going upstairs the game crashes to desktop

**To Reproduce**  
There was a precedent where my NPC character and I were able to get upstairs, but the game crashed a few ingame minutes after

**Screenshots**  
https://clips.twitch.tv/SincereFilthyDugongOSfrog

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 
 - Game Version: 0.D-760-g45d0f89 (tiles)
 - Graphics version: Tiles 
 - Mods loaded:   "dda",
  "no_npc_food",
  "filthy_morale",
  "generic_guns",
  "ew_pack",
  "modular_turrets",
  "Salvaged_Robots",
  "crazy_cataclysm",
  "alt_map_key",
  "mapgen_demo",
  "no_religious_Texts",
  "No_Fungi",
  "more_classes_scenarios",
  "manualbionicinstall",
  "safeautodoc",
  "StatsThroughSkills"

**Additional context**  
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2988927/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2988928/crash.log)

[bug save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2988934/bug.save.zip)

**Comment by neitsa** [comment]
I have been able to repro once on 10 tries 

* It definitely crashed while trying to go upstairs
* The NPC was with me (can't confirm if it can be reproduced without the NPC)

The problem being that the crash seems completely random. I'll try to do more tests with a debugger attached.
