### ISSUE TITLE
(R)eading materials for lore and immersion

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#28853]
**Is your feature request related to a problem? Please describe.**  
Currently the only way to implement lore is through computer terminals, NPCs, or blurbs you get on examining items.

**Describe the solution you'd like**  
I'd like the ability to designate items to open a window on (R)ead. This would be used for things like newspapers, pamphlets, journal entries, and later on maybe entire books.

For example consider the lab pamphlet I wrote up as a joke in this pr: https://github.com/CleverRaven/Cataclysm-DDA/pull/28722, ideally with the screenshots replaced with pixel art PNG images.

Another example would be a journal found in a survivor's den.

Features I'd like:
- open a new window with a specific text entry (base feature)
- allow a given item_id to open one of several options for contained text: ie. similar to how I've done classic books, or how printed t-shirts are done, you could spawn a survivor_journal and it would pick from one of several text options.
- allow use of nested documents - ie. select a bunch of journal entries from a list and stick them together to form a complete document
- for journals especially - allow certain random text blocks to only be chosen after a particular time_since_cataclysm.
- Allow certain variable texts to be entered, such as <u_name>, or <u_name_first>, replacing the snippet with the player's name. If we had NPC unique IDs I'd love to be able to refer to a specific NPC... sigh.
- allow definition of specific variables that can be used in the journal, eg <facility_name>, so that one pamphlet can refer to the HG Bennett Research Facility throughout while another refers to Marcotte Memorial Labs. I see this as something that could be defined at mapgen.
- allow embedded images
- permit pulling up an entire image instead of a text file.

#### Additional context
I'll make a mock-up in a bit

**Comment by capSAR273** [comment]
I love this :D User submissions for survivor journals to tell little stories would be a neat way to expand the lore. Maybe for randomly generated texts a Markov chain could be used to simulate someone telling a story but also being a bit mentally unstable (since the word prediction isn't perfect).

**Comment by I-am-Erk** [comment]
The only trouble with doing Markov chains is I think they're tricky to translate. However this would be prime territory for a Markov chain tool, yes.

**Comment by I-am-Erk** [comment]
This has come up enough times from people wanting to add content that I am going to mark it p3

**Comment by S0ZDATEL** [comment]
And maybe tell there some useful things? Like survivor's log would contain things like "Found a working car to the south from school, but it had no fuel." or "Tried to sleep at the bar. They noticed me, and I had to run away. Left my backpack there, I had no time to pick it up.", or , or something else that would tell the player some useful information, for example, where he can find some loot.

**Comment by Night-Pryanik** [comment]
No discussion in over a year, closing.
