### ISSUE TITLE
Guarding npcs sent to missions can be used in other missions

### ISSUE THREAD

**Issue by adamkad1** [CleverRaven/Cataclysm-DDA#28864]
So i think its the bug that got fixed with nonguard npcs, if npcs on guard are sent to a mission, they can then be sent to another mission, wasting progress on the mission there were on

**Comment by Melodeiro** [comment]
Confirmed. Also it wastes resources, used for upgrading a camp, for example, because its cancels that proccess.

**Comment by davidpwbrown** [comment]
Will look into it
