### ISSUE TITLE
New panel system causes "z-fighting" style problem in curses

### ISSUE THREAD

**Issue by jeremyshannon** [CleverRaven/Cataclysm-DDA#28863]
**Describe the bug**  
The panel windows are drawn over the top of ground tiles, and each is redrawn with every update, meaning rapid updates (like scrolling through the list of nearby items) produce a flickering display.

**To Reproduce**  
Fire up a terminal-mode game, then open up the "V" (list all items around player) window somewhere with a decent pile of items nearby, and hold the down arrow to scroll.

**Expected behavior**  
The panel windows should be declaring their section of the screen off-limits for regular tile drawing so they aren't clobbered  on every update.

**Versions and configuration(please complete the following information):**
 - OS: Debian stable 64 bit
 - Game Version: 0.D-764-g876f0bbde0
 - Graphics version: Terminal

**Comment by Gmiz** [comment]
IMHO, flickering exists on multiple places in the game. For example, when you're moving all the items from one place to another using the advanced inventory in tiles AND curses mode, you can notice flickering of the advanced inventory screen. Another problem is that advanced inventory screen sometimes gets back after the moving of those items, and sometimes it just disappears leaving the player with a dose of confusion.

**Comment by jeremyshannon** [comment]
Yeah, it's definitely been a problem, but it seems it's gotten noticeably worse with the recent update. I kung-fu'ed a bunch of zombies in the street the other day (far from the first time I've done that) and scrolling through the huge list of items was really unpleasant, like I saw the street more than the menu.
