### ISSUE TITLE
Expand base feature is bugged probably.

### ISSUE THREAD

**Issue by Melodeiro** [CleverRaven/Cataclysm-DDA#28868]
**Describe the bug**  
Im trying to expand my base, but instead looks like it just replaces the main center map tile, not adding a new one. There is also bugged fast crafting menu item, which will disappear if i save and load the game.

**To Reproduce**  
Use "expand base" feature.

**Expected behavior**  
Probably it should add a new tab instead but i never did that before.

**Screenshots**  
![image](https://user-images.githubusercontent.com/2702567/54731757-1bd0d700-4ba1-11e9-8f64-558b22871c18.png)

**Versions and configuration:**
 - OS: [Windows 10]
 - Game Version: [from the main menu, e.g. 0.D-760-g45d0f89]
 - Graphics version: [Tiles]

**Additional context**  
Save: https://www.dropbox.com/s/dgt5wgdvm7qlplc/base%20bugs.zip?dl=0

**Comment by davidpwbrown** [comment]
Will look into it
