### ISSUE TITLE
Player uses stairwell, animal tied close-by follows

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#28870]
**Describe the bug**  
Having a cat tied a couple of tiles away from a stairwell will make the animal follow the player as soon as the player changes z-level. It'll give a message that the animal follows you, then it will appear on the stairwell tile, tied to this new spot. Same thing when the player changes z-level again.

**To Reproduce**  
1. Have a cat. Tie her down in proximity to the stairs. 4-5 tiles will work.
2. Go down/up the stairs.

**Expected behavior**  
An animal that has been tied down should not follow the player at all.

**Versions and configuration(please complete the following information):**
- OS: Win 8.1 x64
- Game Version: 8634
- Graphics version: Tiles
- Mods loaded: Filthy Clothing, Disable Npc Needs, Disable Religious Texts, Prevent Zombie Revivication, StatsThroughSkills

**Comment by Night-Pryanik** [comment]
Duplicate of #27014.
