### ISSUE TITLE
More bugs with faction camps

### ISSUE THREAD

**Issue by Melodeiro** [CleverRaven/Cataclysm-DDA#28872]
**Describe the bug**  
If you create a camp, then safe-load your game, your camp name will be reset to "Faction Camp 1". Moreover, if you create more than 1 camp, all will be removed from your factions menu, except for last one. There will be only "+" symbol on the map, and all buildings will stay there. Also i tried to remove the camp data from .map file, and was able to occupy it and enter new name, but the same result on save-load

**To Reproduce**  
1. Create new world
2. Spawn some camps
3. Press save and exit
4. Load

**Additional context**  
If you can't reproduce the bug, use the save file from that issue: #28868

**Comment by davidpwbrown** [comment]
Will look into it

**Comment by Melodeiro** [comment]
I just restored all 3 camps which i built with default name:
![image](https://user-images.githubusercontent.com/2702567/54784223-5cc5fb80-4c34-11e9-918c-1bc126d5821a.png)

I went near camp, and just opened the camp manager, and an entry with default name was added to it (and map). But if i do safe+load, all camps will be lost except for one im standing in. I mean, if i exit the game not standing near any camp, there will be no camps at all after loading the game.

Btw, please, add an ability to rename the camps 😀
