### ISSUE TITLE
Player wiki with incorrect link in the GitHub Wiki's sidebar

### ISSUE THREAD

**Issue by dhiegov** [CleverRaven/Cataclysm-DDA#28879]
**Describe the bug**  
Exactly the same as the bug in #28848, but differs because the wrong link appers in the [GitHub Wiki tab](https://github.com/CleverRaven/Cataclysm-DDA/wiki)'s sidebar.

**To Reproduce**  
1. Go to [GitHub Wiki tab](https://github.com/CleverRaven/Cataclysm-DDA/wiki);
2. On the sidebar to the right, click "Wiki for players";
3. There is no page here. 

**Expected behavior**  
Same as #28848: I expected to follow a link that guided me to http://cddawiki.chezzo.com/cdda_wiki/index.php, because it is an actual wiki, in contrast with the "Wiki" pointed at the project home page, which links to nothing.

**Additional context**  
I personally checked every page in this project's GitHub Wiki by:

1. Going to the page;
2. Opening the source code for the page;
3. Searching for the wrong link: "http://tools.cataclysmdda.com/wiki" (without quotes).

And there is no other link beyond the sidebar's one that links to the wrong wiki.

**Possible solution**
I suppose (never messed with GitHub wikis before) just editing [Home_Sidebar](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Home_Sidebar) solves this problem, because its content is the same as the sidebar's.

**Comment by kevingranade** [comment]
Done, thanks for reporting these.

**Comment by dhiegov** [comment]
You're welcome :)
