### ISSUE TITLE
Strange vehicle "Jittering" after crashing onto it

### ISSUE THREAD

**Issue by Genryt** [CleverRaven/Cataclysm-DDA#28877]
So I was parking my vehicle (solar powered car) and then out of the blue, while i had 0 input in speed it jumped to 70mph in reverse and crashed into another vehicle behind. It was night so i could not see if there was any damage, so after i made sure that the vehicles speed was indeed at zero and it had stopped moving i moved out and went to check. I was beaten badly by the other still moving vehicle. I managed to escape but barely. Not really sure what happened so I dont know if its reproducible. The other vehicle continued to move through out the night non-stop. After a while I decided to crash on it with a Flatbird truck to see what will happen. It solved the bug alright. It seems that this bug is vulnerable to Flatbird trucks. 

![1](https://user-images.githubusercontent.com/48786795/54744015-7df40100-4bce-11e9-9ea3-82acdac3717b.png)
![2](https://user-images.githubusercontent.com/48786795/54744016-7e8c9780-4bce-11e9-9a8d-ff248a235b85.png)
![3](https://user-images.githubusercontent.com/48786795/54744017-7e8c9780-4bce-11e9-8267-0abc04f61039.png)
![4](https://user-images.githubusercontent.com/48786795/54744019-7f252e00-4bce-11e9-8154-41e80c3b5aa3.png)
![5](https://user-images.githubusercontent.com/48786795/54744020-7f252e00-4bce-11e9-9d9d-cabc7192779e.png)
![kis](https://user-images.githubusercontent.com/48786795/54744023-7fbdc480-4bce-11e9-93bc-03f9e4dd5e20.png)

A link with a video documenting the [gitch ](https://www.dropbox.com/s/i9b0yfn9pj5hmh6/2019-03-19-14-22-48.mkv?dl=0)

Versions and configuration-
 -  Windows 10
 - Game Version: 0.D-760-g45d0f89 (tiles)
 - Graphics version: ChestHole
 - Mods loaded
![mod2](https://user-images.githubusercontent.com/48786795/54744554-f3ac9c80-4bcf-11e9-9e30-eea957a2adae.png)
![mod3](https://user-images.githubusercontent.com/48786795/54744555-f4453300-4bcf-11e9-8216-992c67c84cb2.png)
![mod4](https://user-images.githubusercontent.com/48786795/54744558-f4ddc980-4bcf-11e9-8f11-e7920fadde23.png)
![mods1](https://user-images.githubusercontent.com/48786795/54744559-f4ddc980-4bcf-11e9-96cf-6a690bfe9deb.png)

**Comment by Inglonias** [comment]
Possible duplicate of #28765, but if it is, then this has been fixed.

**Comment by Genryt** [comment]
> Possible duplicate of #28765, but if it is, then this should have been fixed.

Seems like it, should i close the issue?

**Comment by Night-Pryanik** [comment]
If it doesn't happen anymore then yes.
