### ISSUE TITLE
Getting boomered overrides map memory

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#28881]
**To Reproduce**  
1. Get boomered.

**Expected behavior**  
I should still remember my surroundings even though my vision radius is crippled.

**Versions and configuration(please complete the following information):**
0.D-760-g45d0f89a1d-dirty

**Comment by Wokko1** [comment]
Can it be hand-waved that the survivor is just confused because of being covered in bile?

**Comment by l29ah** [comment]
If one's confused, why doesn't it affect the relevant stats?

**Comment by kevingranade** [comment]
Not intended, but this is perfectly reasonable, map memory isn't intended to provide perfect dead-reckoning abilities.
