### ISSUE TITLE
Add cooling clothes

### ISSUE THREAD

**Issue by adamkad1** [CleverRaven/Cataclysm-DDA#28886]
So, right now the only way to reduce heat bar taking off clothes, which only works to a certain point, is having something with climate control, but that is not very common. Maybe there could be  (powered?) clothes with negative warmth? something like thermal electric outfit, but reverse?

**Comment by Ilysen** [comment]
I think that "cooling clothes" are a bit strange, since the only things with climate control are advanced things like power armor. I *do* think, though, that some clothes could have a flag that reduces the impact of high temperatures, like `COOLS` or something like that. Things like tank tops, maybe?

**Comment by gimlettio** [comment]
There are real-world cooling clothes.  Two I know of are the air conditioning hook up in Humvees for soldiers in body armor, and the recirculating water cooling suits for race car drivers and astronauts.

The Humvee unit is basically a tube that connects into the Humvee air blower.  the race cars / astronaut systems are clothing with integrated water tubes that circulate through a powwred cooling unit.  There are portable versions that are about the size of a small cooler.


https://slashdot.org/story/63532

https://chiefsupply.com/products/coolcop-inc-coolsoldier-military-armor-air-conditioning-device-universal-cc02-coolsoldier

https://www.pegasusautoracing.com/document.asp?DocID=TECH00140

**Comment by Shodan14** [comment]
Add one of those tiny fans that you can clip your your cap.

**Comment by Photoloss** [comment]
A more mundane and far more practical solution would be to remove "wet" morale penalties from fabric clothing if you are still in a comfortable temperature range. Possibly combined with an option to (a)ctivate or (u)nload water containers to deliberately douse yourself.

Being completely drenched could still be annoying but soaking long sleeves or pouring water over your head like athletes do is no worse than sweating profusely.

**Comment by Headjack** [comment]
Adding air conditioners as "reverse fires" that make an area of cool would be nice.

**Comment by adamkad1** [comment]
yes
