### ISSUE TITLE
Faction camp "drop points reset" little bug

### ISSUE THREAD

**Issue by Melodeiro** [CleverRaven/Cataclysm-DDA#28880]
**Describe the bug**  
When you press reset drop points, it asks you if you want to reset every point. But if you say "no" it will reset it to a very far point on the map. So its only possible to set everything up in a single run, or don't touch that feature at all. Since it doesn't shows you how do you set your stuff previously, its quite hard to remember all old placements.

**Expected behavior**  
A possibility to change only a few drop points instead of all.

**Comment by mlangsdorf** [comment]
This is shortly going to be fixed by using the zone manager instead.

**Comment by adamkad1** [comment]
Zone manager will be sort points? nice
