### ISSUE TITLE
Keys ">" and "<" don't work in menus on laptop

### ISSUE THREAD

**Issue by Wokko1** [CleverRaven/Cataclysm-DDA#28898]
**Describe the bug**  
The keys "<" and ">" don't work in menus, only "Tab" works. The issue persists even after remapping those keys. Regular ascending/descending in gameplay is working fine.
Makes it impossible to return on character creation screen, crafting screen, etc, as only Tab key works.

**To Reproduce**  
1. Launch the game
2. Go to "options"
3. Press "<" or ">"

**Expected behavior**  
Pressing "<" or ">" should flip the menu to the next page as normal.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 64-bit Home
 - Game Version: 0.D-8644, but the same applies to 0.D-8616
 - Graphics version: both
 - Mods loaded: only default

**Additional context**  
I have a laptop, maybe the issue is related to that.

**Comment by esotericist** [comment]
Default keybindings in 0.D include shift-tab as the reverse action of tab (effectively that's 'backtab'). Does that work for you?

**Comment by Wokko1** [comment]
Yes, shift-tab works, but > and < don't.
