### ISSUE TITLE
Crash - SIGSEGV: Segmentation fault. 

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#28897]
**Describe the bug**  
Whenever I go to examine a water tile I'm also getting options to pour it into a keg that's nowhere nearby.

**To Reproduce**  
Pouring in any already pre-allocated water tile causes the crash. 

**Expected behavior**  
Not to have a option to empty water into a keg that doesn't even exist.

**Screenshots**  
![image](https://user-images.githubusercontent.com/5264667/54793443-576baf80-4c3a-11e9-8583-a502f02b6e69.png)

![image](https://user-images.githubusercontent.com/5264667/54793535-c9dc8f80-4c3a-11e9-9f1d-ee216c93a92d.png)

![image](https://user-images.githubusercontent.com/5264667/54792720-38b7e980-4c37-11e9-9c08-1780baff21bb.png)

**Versions and configuration(please complete the following information):**
 - OS: Win7 64bit
 - Game Version: [0.D-873-ge87ef58]
 - Graphics version: [Tiles chesthole32)

 - Mods loaded: [[ "dda", "more_locations", "FujiStruct", "Medieval_Stuff", "More_Survival_Tools", "Packaging", "RL_Classes", "SD_Magcrafting", "StatsThroughSkills", "blazemod", "Tanks", "Urban_Development", "ZSFIXED_cddaxp", "boats", "cityside", "craftgp", "deoxymod", "ew_pack", "filthy_morale", "makeshift", "more_classes_scenarios", "mutant_npcs", "national_guard_camp", "no_npc_food", "npc_traits", "realguns", "Tolerate_This", "modular_turrets", "Salvaged_Robots", "Bootleg_Walkers", "DracoDogMod", "growable-pots", "aftershock" ]

**Additional context**  
[Zakhadia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2994432/Zakhadia.zip)

**Comment by ZhilkinSerg** [comment]
Fixed in #28903.
