### ISSUE TITLE
nuts inconsistent

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#28902]
**Describe the bug**  
given calorie count, I can assume all nuts are supposed to be handfuls.
The following nuts should have their names updated (for their raw forms).  If you have only one unit, it sounds like you're holding a single nut

- peanut
- walnut
- chesnut
- hazelnut
* beech nut
* cashew

The last two I'm not sure about

**To Reproduce**  
either
 wish for one of each
or
 give yourself max skills, and search crafting recipies for nut

**Expected behavior**  
All nuts should probably be consistent, and current form is "handful(s) of xxxs"

**Screenshots**  
ask if need

**Versions and configuration(please complete the following information):**
 - OS: ask if need
 - Game Version: most recent as of 3/21
 - Graphics version: ask if need
 - Mods loaded: ask if need

**Additional context**  
ask if need

**Comment by Xpyder** [comment]
Not sure this is game balance, it's really just a naming issue.  Unless there's other problems with them I missed?

**Comment by golankra123** [comment]
> Not sure this is game balance, it's really just a naming issue. Unless there's other problems with them I missed?

Yes it's a naming issue as far as I understand, I've dealt with it to some extend.
if you want to take a look at the pull request feel free :)
[https://github.com/CleverRaven/Cataclysm-DDA/pull/28924](url)

Thanks for reporting the issue

**Comment by KorGgenT** [comment]
close via #28924
