### ISSUE TITLE
Player wiki with incorrect link in the README.md

### ISSUE THREAD

**Issue by dhiegov** [CleverRaven/Cataclysm-DDA#28900]
**Describe the bug**  
The README.md does not link to the player wiki where it should. Same issue as #28879 and #28848.

**To Reproduce**  
1. Go to the [README.md, Community section](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/README.md#community);
2. Click on the link after "Wiki: ";
3. There is no page here.

**Expected behavior**  
Same as #28848: Follow a link to http://cddawiki.chezzo.com/cdda_wiki/index.php.

**Additional context**  
I'm sorry for sort of "spamming" issues of basically the same thing. My intent is to report a broken link as fast as possible after I realise its existence.

**Comment by Wokko1** [comment]
Just change "README" and make a PR.

**Comment by kevingranade** [comment]
Whoops, I changed it before I saw your PR.
