### ISSUE TITLE
Sidebar - Delayed Messages

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#28914]
**Describe the bug**  
When repairing items using tailor's kit (tested with wooden needle as well for the same result) and you have missing material, the message with the fact only display once you close the item selection menu.

**To Reproduce**  
1. Get the tools needed for item repair and some damaged clothing
2. Try to repair the clothing without having required rags (or leather patches or something else)
3. Be confused as of why nothing happens
4. Hit ESC to close the item selection menu and see the "You don't have enough rags ... " message

**Expected behavior**  
To see that message immediately upon selecting the item.

**Versions and configuration(please complete the following information):**
Latest experimental Win64 Tiles

**Comment by Petethegoat** [comment]
This is definitely still happening. Very annoying.
