### ISSUE TITLE
Sidebar - Missing indent in Classic and Compact view

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#28916]
**Describe the bug**  
Text starts directly on the left margin of the sidebar in classic and in compact view

**To Reproduce**  
1. switch the sidebar

**Expected behavior**  
to have a little margin on the left as in labels view

**Screenshots**  
the classic view
![image](https://user-images.githubusercontent.com/19891532/54830924-b91f2e80-4cb9-11e9-98dc-cf1c55fdb972.png)

the labels view
![image](https://user-images.githubusercontent.com/19891532/54831034-e4a21900-4cb9-11e9-8378-a39692c9fee9.png)

**Versions and configuration(please complete the following information):**
Latest experimental Win64 tiles

**Comment by KorGgenT** [comment]
not a bug. it is a style choice.

**Comment by tinukedaya** [comment]
Well... as it's not consistent with the labels layout I though it's bug. Can I have it as feature request then? A single pixel (or two) would do wonders to readability.

**Comment by KorGgenT** [comment]
sure. reword it as a feature request and ping me, or reopen as a feature request
