### ISSUE TITLE
reload button stopped working

### ISSUE THREAD

**Issue by n3tr4k** [CleverRaven/Cataclysm-DDA#28920]
**Describe the bug**  
"r" button for reload item in inventory doesn't work anymore, but if you go into item menu through inventory it works there. Instead hitting "r" is passing time instead, keybinding is also fine. Rebinding key doesn't work as well.

**Versions and configuration(please complete the following information):**
 - OS: debian x86_64
 - Game Version: 0.D-915-gfd0996979d

**Comment by ZhilkinSerg** [comment]
Reloading was changed recently - #28245.

**Comment by dommon** [comment]
indeed, and r does work - sorta, just reloading empty hands silently passes a turn, another features of that pr is being able to reload bows and no way to reload adjacent squares
likely paste to wrong indent in game::reload

**Comment by thquinn** [comment]
Is there no longer a hotkey assignable for the generic "reload" action -- i.e. opening up your inventory and choosing any item to reload? Now I have to i -> [item key] -> r to refill my flashlight when holding a bow and multiple arrow types.

**Comment by LOMS** [comment]
But old reload... it was so convenient! With old "r" player could reload his flask and all necessary things for journey without scrolling inventory. 

Also, got that problem on latest experemental:
Wearing large quiver with 43/60 of broadhead arrows.
Crafted another 40.
Reload button still prompts me to reload my quiver, but when I choose to reload it - nothing happens.

**Comment by Mythiran** [comment]
I am also experiencing this. The reload menu no longer appears ever. If I wield a glock, r reloads it, if I wield unarmed or a bow, 'r' just 'waits'... I can't seem to get the reload menu to come back up to reload MP3 players with batteries etc.

I have tried messing about with key-bindings but it hasn't helped. 

Perhaps having a separate key binding for 'reload menu' from 'auto reload' would help sort this out?

**Comment by Night-Pryanik** [comment]
Reloading doesn't do anything if there is a `RELOAD_AND_SHOOT` weapon and its ammo in the inventory. For example, having a sling and pebbles in the inventory won't let you to reload a flashlight through the `r` keybinding.

**Comment by Night-Pryanik** [comment]
I think this is no longer an issue after #32798. Closing for now, ping me if it's still an issue.
