### ISSUE TITLE
View is off-center when starting/loading a character.

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#28927]
**Describe the bug**  
View is off-center when starting/loading a character.

**To Reproduce**  
Start or load a character.

**Expected behavior**  
View is centered.

**Screenshots**  
Max zoom in
![max zoom in](https://user-images.githubusercontent.com/28264543/54859181-293cad00-4cd8-11e9-974a-7c56c45a5b4f.png)
Max zoom out
![max zoom out](https://user-images.githubusercontent.com/28264543/54859182-2e016100-4cd8-11e9-9f71-f4b702834780.png)

**Versions and configuration(please complete the following information):**
 - OS: Manjaro Linux 64-bit
 - Game Version a385342
 - Graphics version Tiles
 - Default mods

**Additional context**  
I deleted the user config folder @ /home/username/.config/cataclysm-dda/ and ran a fresh installation of CDDA with:

#!/bin/bash

repo=("/home/username/Cataclysm-DDA")

git clone --depth 1 git://github.com/CleverRaven/Cataclysm-DDA.git
cd "${repo}"
make -j14 RELEASE=1 TILES=1 SOUND=1 LUA=1 USE_XDG_DIR=1
./cataclysm-tiles

Savegame
[Gate City.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2998833/Gate.City.zip)

**Comment by int-ua** [comment]
Looks like a #28813 duplicate. Alternatively, there is a feature where you can shift focus point with Shift+direction keys. When you press x to examine distant tiles does the pointer start on your character?

**Comment by Quintovir** [comment]
>Looks like a #28813 duplicate.

Indeed. A quick search didn't bring up that issue.

> Alternatively, there is a feature where you can shift focus point with Shift+direction keys.

Shift + h,j,k,l does shift the view, but every time I change the zoom level the view needs to be shifted if I want it to be centered.

>When you press x to examine distant tiles does the pointer start on your character?

Yes.
