### ISSUE TITLE
Move center of character camera relative to sidebar border

### ISSUE THREAD

**Issue by Adevald** [CleverRaven/Cataclysm-DDA#28933]
There is some little problem, about center of camera. I know what i can move it on HJKL, but zooming and riding a car is little dumb.

![image](https://user-images.githubusercontent.com/39699252/54865319-564f9500-4d96-11e9-8e5e-109b9bcbb647.png)

![image](https://user-images.githubusercontent.com/39699252/54865336-ab8ba680-4d96-11e9-9d79-b81cf5ad0706.png)

**Comment by OrenAudeles** [comment]
Duplicate of #28813 
For temporary fix you can use SHIFT+DirectionKey to shift the focus as explained in [This Comment](https://github.com/CleverRaven/Cataclysm-DDA/issues/28927#issuecomment-475835003)

**Comment by Adevald** [comment]
@OrenAudeles Sorry, i'll close it
