### ISSUE TITLE
Support XBox controller input on Android

### ISSUE THREAD

**Issue by gavofih** [CleverRaven/Cataclysm-DDA#28949]
I would like to play the game on my phone with one of these 
![image](https://user-images.githubusercontent.com/47798071/54877184-f519d700-4e12-11e9-8b83-e019168fac2f.png)

But currently game doesn't recognize xbox controller inputs on phone keybinding menu. In desktop version it does, but doesn't recognize right stick
#23337

Right now the only option is to create keybinding on desktop and `adb push` it on phone, but still no right stick, which could be very usefull to pan camera and look around as the view is very restricted by the menus

**Comment by Inglonias** [comment]
Implementation aside, I'm very curious as to how playing this game with a controller improves your experience. I'm not saying it's a bad idea, I'm just curious as to the reasoning here, though I suppose any real buttons are better than a set of touch controls. It's the big thing keeping me from playing this game on my Android device: I cannot stand touch controls.

If it were me, I'd attach one of those [tiny Bluetooth keyboards](https://www.amazon.com/Rii-Bluetooth-Wireless-Backlight-RTi8BT-6/dp/B01FXDW2YA/) instead.

**Comment by gavofih** [comment]
> 
> 
> Implementation aside, I'm very curious as to how playing this game with a controller improves your experience. I'm not saying it's a bad idea, I'm just curious as to the reasoning here, though I suppose any real buttons are better than a set of touch controls. It's the big thing keeping me from playing this game on my Android device: I cannot stand touch controls.
> 
> If it were me, I'd attach one of those [tiny Bluetooth keyboards](https://www.amazon.com/Rii-Bluetooth-Wireless-Backlight-RTi8BT-6/dp/B01FXDW2YA/) instead.

Mainly to move controls away from touchscreen, yea. Game in current state is very cluttered with menus on Android barely leaving any space for actual game and on top of that touchscreen controls and your fingers block even more view. 

The way i see this implemented is to move most used controls to gamepad ( with less used to combination of controller buttons ) and leave very rarely used buttons on screen.

Regarding your bluetooth keyboard i couldn't find any good ones that would attach to a phone and be comfortable to use on the go. I did find [this](https://www.aliexpress.com/item/KuWfi-Mini-Bluetooth-Folding-Keyboard-64Keys-Aluminum-Alloy-Dual-Channel-Keyboard-For-Phone-PC-Laptop-Tablet/32926323136.html) and [this](https://www.aliexpress.com/item/PU-Leather-Case-Micro-USB-Wireless-Bluetooth-Keyboard-Stand-Cover-For-Android-Mobile-Phone-Cover-Phone/32956970639.html) but they gonna be pain the in ass to use. There are also qwerty smartphones like [Nokia N950](https://duckduckgo.com/?q=N950&t=ffab&atb=v141-6__&iax=images&ia=images) which would be perfect to play on, but its hard to find/buy these.
