### ISSUE TITLE
Rotten Milk is permanently a solid (and can't be [U]nloaded from containers)

### ISSUE THREAD

**Issue by Crunchepillar** [CleverRaven/Cataclysm-DDA#28948]
**Describe the bug**  
When milk goes rotten it gains the property "current_phase": 1 which seems to be the solid phase. Milk in containers with this flag cannot be [U]nloaded from the container and other containers cannot be [R]eloaded with it either. ("You don't have any liquid to reload your XXX") Even heating the milk up with a cooker until it had the {Hot} tag doesn't change its phase, it just has both current_phase: 1 and {Hot} with current_phase taking priority when trying to unload. Editing the save to remove current_phase:1 from my hydria of rotten milk allows it to be poured normally.

**To Reproduce**  
1. Get Milk
2. Wait for Milk to Rot
3. Try to unload rotten milk to use container for other purposes

**Expected behavior**  
Rotted milk should be able to be disposed of like other rotted liquids, Eg: Coffee Milk can still be unloaded.

**Screenshots**  
Available as needed

**Versions and configuration(please complete the following information):**
 - OS: Win10
 - Game Version: 0.D-915-gfd09969 (tiles)
 - Graphics version: Tiles
 - Mods loaded: 
  "dda",
  "no_npc_food",
  "filthy_morale",
  "makeshift",
  "More_Survival_Tools",
  "alt_map_key",
  "Urban_Development",
  "DP_XOTTO_INDICATORS",
  "more_classes_scenarios",
  "cars_to_wrecks"

**Additional context**  
Rotten milk can still be used to make Coffee Milk and the disposed of but that burns through my coffee powder supply pretty quickly when trying to clean out the clay hydria I use to store milk :[

World save: [HardPecs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3000195/HardPecs.zip)
The dairy farm where I set up my camp is located at maps\5.3.0\160.107.0.map

**Testing**
I decided to test this on a new world with the same mods loaded and wished for a jug of milk. This one remained able to be poured even after rotting so whatever caused my hydria of milk to become solid must have to do more with the specific situation surrounding it.

Other details that might be relevant: This hydria was used to milk my cows in the save that has that issue and stacking milk causes the "Poured item has no defined temperature" error and then freezes the milk. I'm thinking this is culprit behind this issue.

**Comment by Crunchepillar** [comment]
I just remembered in one of my earlier saves I had a very similar issue with a vehicle tank that had about 3L of clean water freezing and then thawing but becoming completely unusable, no siphoning, no refilling and no drinking it through a kitchen unit or faucet. This issue may not be specific to milk or rotting but some freak occurrence involving temperature.

**Comment by Hirmuolio** [comment]
#28980 will fix this. The item needs to remelt to get fixed after that pull get in.
