### ISSUE TITLE
NPCs BackStories after character dies Overwrite eachother (for 2 NPCs or more)

### ISSUE THREAD

**Issue by adamdeno** [CleverRaven/Cataclysm-DDA#28940]
**Describe the bug**  
When the player dies . the game would give the player an idea of what happened to their following friendly NPCs by giving them stories

**To Reproduce**  
1. get at least 2 Friendly NPCs or more
2. Die
3. hope for a long story NPC and a short story one
4. The second NPC story overwrites the long one

**Expected behavior**  
Should Not overwrite

**More info**
how it works
Example...
(NPC1 has found a party after you died and helped them and some say he is dead.)
(NPC2 was a good guy but he died.)

BUT.. it shows it like this for the second NPC story

(NPC2 was a good guy but he died. and helped them and some say he is dead.)
                                                     ^                                                                ^ --- dots (end of story)

**Screenshots**  
N/A

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-929-gc8f8aa2 (tiles)
 - Graphics version: 
 - Mods loaded: alot

**Comment by xrandomuserx** [comment]
NPC Backstory Loops - Doctor sleeping in maintenance room and drinking from the puddle

**Comment by I-am-Erk** [comment]
I don't understand what you are trying to say here.

**Comment by xrandomuserx** [comment]
> NPC Backstory Loops - Doctor sleeping in maintenance room and drinking from the puddle

When you ask about how they survived the cataclysm, for the story for doctor/medical, part of the dialogue was in a never-ending loop

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/npctalk.cpp

**Comment by I-am-Erk** [comment]
I don't think that's what OP was talking about at all, and it definitely has nothing to do with npctalk.cpp, but I think I've found what you were referring to, so thanks for bringing that up. I'll go fix it.

I still have no idea what the OP is trying to say either
