### ISSUE TITLE
Error when starting quest

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#28950]
**Describe the bug**  
Talked to a doctor in a refugee center and he gave me the quest to get zombie blood and put it through a centrifuge in a hospital, then the error message popped up.

**To Reproduce**  
1. Try to get quest from doctor.
2. Get error message instead.

**Expected behavior**  
No error message.

**Screenshots**  
![Untitled](https://user-images.githubusercontent.com/45204409/54876955-a1aa8780-4e18-11e9-9dcd-ddfa4c48cf25.png)

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version: [0.D-947-g980ca05]
 - Graphics version: [Tiles]
 - Mods loaded: [Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Just Craftable Gunpowder, Makeshift Items Mod, PKs Rebalancing, Alternate Map Key, Mutant NPCs, More Locations, Fuji's More Buildings, Urban Development, PK - No Doom Monsters, Nonperishable Overhaul, DinoMod, Medieval and Historic Content, Vehicle Additions Pack, Tanks and Other Vehicles]

**Additional context**  
The quest still seems to be issued succesfully and can be finished properly, if the player can find a working centrifuge on their own (I went back to a hospital that was quite a distance away).

**Continuation**
The next quest from the same character has me going into a Lab, but the workstation I'm supposed to download from is broken and cannot be interacted with in any way that would help with the quest.
![Untitled](https://user-images.githubusercontent.com/45204409/54878014-a6763800-4e26-11e9-9319-0f7245c92340.png)
![Untitled](https://user-images.githubusercontent.com/45204409/54878039-e1786b80-4e26-11e9-86c0-c54b9cc392d8.png)

After having lost all hope of ever finishing this quest, I searched through the rest of the Lab and eventually found the actual workstation that I was supposed to download from, intact and working. Guess you can just ignore the second part of this bug report, the very specific coordinates confused me.

**Comment by MichaelEricOberlin** [comment]
For part one, I got the same issue on Linux Mint 19.1. It isn't Windows 10 specific.
