### ISSUE TITLE
Unable to craft Survivor belts (Tool-less ones)

### ISSUE THREAD

**Issue by Trilbyspaceclone** [CleverRaven/Cataclysm-DDA#28956]
**Describe the bug**  
For a unknown reason or incompetents, We are unable to learn how to make a Survivor Belt
The belt needed for Survivor Utility Belt!
**To Reproduce**  
1. Make a player with high or low skills.
2. Try to look for the Survivor belt in crafting.
3. Fine it missing and then cry.

**Expected behavior**  
A some point being able to learn how to make a Survivor belt

**Screenshots**  
![image](https://user-images.githubusercontent.com/30435998/54881486-e50bf280-4e26-11e9-93ed-4a7d28427d65.png)

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version: [0.D-931-gce983ff (tiles) -  8654 (a day ago)]
 - Graphics version: [N/A]
 - Mods loaded: [Like all of them >_<]
Mod lists - 
![image](https://user-images.githubusercontent.com/30435998/54881626-22bd4b00-4e28-11e9-9ea2-b6ffcb1d2bc1.png)

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.
![image](https://user-images.githubusercontent.com/30435998/54881531-5a77c300-4e27-11e9-88e6-12cc8dae946e.png)
https://github.com/CleverRaven/Cataclysm-DDA/blob/46053511ec0f9aabfd9e7868c8a9dbc20097a8b8/data/json/recipes/armor/other.json

My Skills - 
![image](https://user-images.githubusercontent.com/30435998/54881670-7fb90100-4e28-11e9-8dae-f2e1f8be1bbd.png)

**Comment by Trilbyspaceclone** [comment]
First time bug reporter long time watcher - Hope I did good

**Comment by gimlettio** [comment]
Survivor belt requires tailoring six, for whatever reason.   There are a few recipes like that where a product can be made from them earlier than the base product can be crafted.

**Comment by Trilbyspaceclone** [comment]
@gimlettio Oh thanks! I thought it was using faberaction... My bad!
