### ISSUE TITLE
Sound meter improvement needed (was Soundless explosions)

### ISSUE THREAD

**Issue by minakitty** [CleverRaven/Cataclysm-DDA#2897]
I've been seeing this for awhile, but haven't bothered to bug report.  Different things that should cause sound (shriekers, exploding boomers/smokers) seem to have the desired effect on mobs, but the sound display has never fluttered about 0 for me in weeks.
![screenshot from 2013-09-07 15 57 00](https://f.cloud.github.com/assets/5273418/1102329/4490a34a-1813-11e3-9a4e-53f096d3653c.png)
##

**Comment by tswood** [comment]
Sound display currently works as noted in the prior comment, sans vehicle noise. Could this issue be modified for including vehicle noises or perhaps closed and a new issue opened?

**Comment by Leland** [comment]
@tswood I'm closing this one since it's been stalled for so long. Feel free to make a new issue regarding the proposal if you want! It'll be more visible that way as well.
