### ISSUE TITLE
Cannot assign more than one item use_action of same type?

### ISSUE THREAD

**Issue by Photoloss** [CleverRaven/Cataclysm-DDA#28975]
Not filing as a bug report since I am not aware of any items in the base game actually trying to do this. I stumbled upon this issue while experimenting with JSON modding.

In my particular case I am trying to assign several "transform" actions to a single item. Think vehicle subsystems in a powersuit or Bloodborne transformer weapons. Using the array syntax for use_action only the first "transform" definition actually gets registered to the item in game. Additional actions of a different type (e.g. "CAMERA") appear as expected.

Based on a quick search I presume something within `item_factory.cpp` is giving me grief but the way [this](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item_factory.cpp#L2489) JSON-loading function is written, iterating over the array and using `insert`, makes it seem as if the code is meant to support an essentially arbitrary selection of actions.

If anyone happens to know an item in the base game which attempts to make use of this please post it and I'll re-file this as a bug report. If anyone can give me pointers as to where or why actions of identical "type" are simply ignored thanks in advance.

**Comment by ralreegorganon** [comment]
> If anyone can give me pointers as to where or why actions of identical "type" are simply ignored thanks in advance.

The use methods are stored in [a map](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item_factory.cpp#L2502) where the type is the key, which means a given type will only have a single value associated with it.

Basically, as written you can have as many different types of actions as you want, but only a single action per type.

**Comment by Photoloss** [comment]
Hmm, thanks. Looks easy enough if potentially tedious to change, but incredibly hard to actually get *right* and not suffer knock-on effects elsewhere. At a glance I can't really find any "advanced" usage of the map structure though and only [one](https://github.com/CleverRaven/Cataclysm-DDA/blob/271c66ba306f7340f600f9ce762372f3028423c8/src/itype.cpp#L47) obvious dependency on having a list of action types for searching, but it seems that `itype::get_use` is sometimes used expecting a single (and full action) return value e.g. [for morale adjustments](https://github.com/CleverRaven/Cataclysm-DDA/blob/ad2c68aed61f38ce02c645caf8dec64b273ee755/src/morale.cpp#L569).

Maybe it would be better to code "multi" functionality into the actions themselves then? The toolbelt already does it but that would lead to a fair amount of code duplication down the line. Do any of the existing actions save data to the item in a way which will break for multiple entries? Looking through the list of actions it seems only transforms, holsters and hypothetical JSONised repair or "toggle flag" actions would really benefit. Do any of the higher-ups have a preference towards either approach?

**Comment by kevingranade** [comment]
The cannonical way to do this would be to convert it to a std::multimap and then sort out the interface changes, presumably only a few places (exposing the iuse options to the player) would need to handle having several iuses of the same type attached.
