### ISSUE TITLE
Can't manually empty unfrozen liquids

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#28983]
**Describe the bug**  
Liquids in containers that have been frozen at one point or another and thawed back into liquid form can't be manually unloaded from their containers anymore.

**To Reproduce**  
1. Let contained liquid freeze.
2. Let it thaw.
3. Try to unload it from container.
4. Can't unload it.

**Expected behavior**  
Unfrozen liquid can be unloaded from container.

**Screenshots**  
![Untitled](https://user-images.githubusercontent.com/45204409/54925770-45765f00-4f0f-11e9-9e7d-d2a3ed2e281a.png)
See how the unload option is greyed out.
Bleach in gallon jugs from ice labs, that has thawed, also can't be poured into vehicle tanks anymore. Strangely with Ammonia from the same lab it was still possible.

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version: [0.D-947-g980ca05]
 - Graphics version: [Tiles]
 - Mods loaded: [Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Just Craftable Gunpowder, Makeshift Items Mod, PKs Rebalancing, Alternate Map Key, Mutant NPCs, More Locations, Fuji's More Buildings, Urban Development, PK - No Doom Monsters, Nonperishable Overhaul, DinoMod, Medieval and Historic Content, Vehicle Additions Pack, Tanks and Other Vehicles]

**Comment by Hirmuolio** [comment]
#28980 should fix this. The item will need to melt again to get fixed though.
