### ISSUE TITLE
Linuxdepoly -archlinux to  makepkg . Does not support aarch64

### ISSUE THREAD

**Issue by neoiso** [CleverRaven/Cataclysm-DDA#28994]
Game version:

Operating system:

Tiles or curses:

Mods active:

**Comment by OrenAudeles** [comment]
Please stop closing and opening new issues. You can edit your open issue contents/title.

**Comment by Night-Pryanik** [comment]
Honestly I don't understand what's the issue here. Could you please describe it in details?

**Comment by neoiso** [comment]
我用的depoly软件在安卓手机上运行的arch系统…然后看的aur的提示做了下来…软件提示不支持aarch64

**Comment by ZhilkinSerg** [comment]
Are you are using Archlinux installed on Android phone? This is rather uncommon configuration and Cataclysm probably doesn't support it. Anyway you can try compiling by yourself on the phone itself using [Linux compilation guide](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING.md#general-linux-guide).

**Comment by neoiso** [comment]
使用源码编译的话可以让aarch64的架构也能成功运行游戏吗？

**Comment by ZhilkinSerg** [comment]
I really don't know, so you better try to see if there are any errors during compilation, linking or running application.

**Comment by neoiso** [comment]
Whoa! Your terminal is tiny! This game requires a minimum
terminal size of 80x24 to work properly. 60x20 just won't
do. Maybe a smaller font would help?
这是运行软件后的提示。
这就是成功了？
我该从哪里设置分辨率？

**Comment by neoiso** [comment]
或者说因为我的手机屏幕太小…或许我应该使用ipad 
 ssh连接使用？
可不可以强制设置游戏的显示大小？

**Comment by neoiso** [comment]
我刚刚成功的在ipad上ssh的界面上成功运行游戏了！
只是还是英文…或许我还可以再努力下看看在哪里设置…

**Comment by neoiso** [comment]
手机上另外下载了ssh客户端…成功运行游戏！
我想问一下 …编译的选项通常是 NATIVE=linux64
但是我使用的是NATIVE=aarch64.
请问这个参数是指的还是系统版本是32位还是64位？还是指的架构？
因为我的编译选项是NATIVE= aarch64竟然也能成功运行…感觉很意外…
另外…我可以在该游戏目录下直接重新编译吗？

**Comment by neoiso** [comment]
手机上另外下载了ssh客户端…成功运行游戏！
我想问一下 …编译的选项通常是 NATIVE=linux64
但是我使用的是NATIVE=aarch64.
请问这个参数是指的还是系统版本是32位还是64位？还是指的架构？
因为我的编译选项是NATIVE= aarch64竟然也能成功运行…感觉很意外…
另外…我可以在该游戏目录下直接重新编译吗？
