### ISSUE TITLE
Sidebar and firing modes.

### ISSUE THREAD

**Issue by Nvemri** [CleverRaven/Cataclysm-DDA#28998]
Could we please get info about weapon firing mode (semi/3/auto) back into the HUD? It is absent in all 3 layouts, even in the classic one.

Also, it would be really nice to have the run/walk indicator change color when switched to "run" mode, to make it more noticeable.

Also, it is strange that the "labels" layout has no info about current fighting style used, and no option to display it. It is also strange that the "compact" layout looks like the only way to check wind conditions, the other two don't have this option.

**Comment by nexusmrsep** [comment]
Related: #29032

**Comment by KorGgenT** [comment]
this should already have been fixed in #29127
