### ISSUE TITLE
Can not load saved game after latest update

### ISSUE THREAD

**Issue by micage** [CleverRaven/Cataclysm-DDA#29009]
After having updated the game today I wasn't able to load my saved game.
I wasn't even able to start a new game. Also tried it with a fresh world. Without any success.

The update is 0.D-381-gd80839ebc9.

debug.log says:
src/iexamine.cpp:4522 [iexamine_function iexamine_function_from_string(const std::string &)] Could not find an iexamine function matching 'fireplace'!
17:33:58.229 ERROR : src/iexamine.cpp:4522 [iexamine_function iexamine_function_from_string(const std::string &)] Could not find an iexamine function matching 'fireplace'!
17:33:58.229 ERROR : src/iexamine.cpp:4522 [iexamine_function iexamine_function_from_string(const std::string &)] Could not find an iexamine function matching 'fireplace'!
17:33:58.282 ERROR : src/iexamine.cpp:4522 [iexamine_function iexamine_function_from_string(const std::string &)] Could not find an iexamine function matching 'fireplace'!
17:34:00.553 ERROR : src/main_menu.cpp:952 [bool main_menu::load_character_tab()] Error: data/mods//dda/../../json/items/generic.json: line 1310:12: unrecognized JSON object
  },
  {
    "type":
           ^
            "PET_ARMOR",
    "id": "kevlar_harness",
    "symbol": "[",

OS: OS X 11.6

Is there a way to rescue my saved game?

**Comment by kevingranade** [comment]
Your executable and json are out of sync, specifically your json is newer than your executable.
I'm guessing during the update you did overwrite the json, but not the executable.

Try grabing a fresh copy of the game and copying the contents of the save/ directory into it.  This is a safer process than updating things in-place anyway.

**Comment by micage** [comment]
Ok, will do. Thank you for your fast reply.
