### ISSUE TITLE
Option to adjust automatic vehicle turret firing range

### ISSUE THREAD

**Issue by VoidForge** [CleverRaven/Cataclysm-DDA#29001]
**Is your feature request related to a problem? Please describe.**  
No, or the inability to adjust the range of automatic firing.

**Describe the solution you'd like**  
Add an option in electronic menu to allow change of maximum (or even better, and minimum) range of automatic fire of vehicle turret. Default range is calculated by chance of hit. I may be able to add this feature by myself, if time permits.

**Describe alternatives you've considered**  
automatically set the range of automatic fire according to chance to hit as suggested in the code
`// TODO: calculate chance to hit and cap range based upon this`

**Additional context**  
I am not English native speaker, please forgive any language error I made.

**Comment by Night-Pryanik** [comment]
> I may be able to add this feature by myself, if time permits.

No one is rushing. Feel free to implement.
