### ISSUE TITLE
Rock forge cannot be unloaded

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#29005]
**To Reproduce**  
1. Accidentally dump all your thousands of charcoal into a rock forge.
2. Feel you cannot smoke all that meat anymore.

**Expected behavior**  
`e`xamining a rock forge should provide a way to unload charcoal from it.

**Versions and configuration(please complete the following information):**
0.D-1000-g71fd5f239e-dirty

**Comment by Reclusive-reptile** [comment]
Clay kilns also eat your charcoal.
