### ISSUE TITLE
Incandescent Husks create zombie brawls

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#29003]
**Describe the bug**  
I regularly see bunches of zombies that kill each other instead of looking for the player. This seems to be caused by incandescent husks and their shock fields / EMP blasts.

**To Reproduce**  
1. Have a sufficiently long-lived survivor who will spawn incandescent husks as part of zombie groups.
2. Wander into a city.
3. Observe the carnage.

**Expected behavior**  
Zombies should not be fighting or damaging one another.

**Screenshots**  
![Untitled](https://user-images.githubusercontent.com/13466852/55001115-33122900-4fd4-11e9-8409-83ee991875c3.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 8.1 x64
 - Game Version: 8663
 - Graphics version: Tiles
 - Mods loaded: Filthy Clothing, Disable Npc Needs, Disable Religious Texts, Prevent Zombie Revivication, StatsThroughSkills

**Comment by Night-Pryanik** [comment]
> Zombies should not be fighting or damaging one another.

No, that's not the expected behavior. There are lots of ways zombies can damage each other.

**Comment by int-ua** [comment]
Happens with juggernauts too

**Comment by kevingranade** [comment]
It is intended that the incandescent hulks are damaging other zombies. It is not intended that those zombies fight back, do they?

**Comment by Tharn** [comment]
Going by my screenshot there, and as far as I remember, the zombies don't fight back. So everything is in order.

Would it be too game-y to suggest zombies being pushed away or stepping away from these blasts? I don't suppose they have a sense of self-preservation, but when a crackling husk clears a whole group for ya, it feels like easymode.
