### ISSUE TITLE
Segfault when opening Minimap

### ISSUE THREAD

**Issue by Vollblut** [CleverRaven/Cataclysm-DDA#29006]
**Describe the bug**  
Minimap is closed even though it's configured to be open as standard, hitting the Hotkey for it gives out a message "Fatal Error"
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3008490/crash.log)

**Expected behavior**  
Minimap opens

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux, Kernel 5.0.4
 - Game Version: 0.D. Danny
 - Graphics version: [MX Live People]
 - Mods loaded: [e.g.dda, boats,  StatsThroughSkills, Bright Nights, Simpified Nutrition, Crazy Cataclysm]

**Additional context**  
Can't tell if it's a system configuration on my side or a game issue, i'm not so versed at it.

**Comment by KorGgenT** [comment]
what build are you on?

**Comment by Vollblut** [comment]
0.C.2019.03.26-1
It's the cataclysm-dda-git from the AUR. 
It says 0.D. on the main screen.

**Comment by KorGgenT** [comment]
yes, if you can do that please confirm that it's happening on current master

**Comment by KorGgenT** [comment]
very well. closing because it has been fixed on more recent builds.
