### ISSUE TITLE
Segfault in 0.D-1027-ge0c9fb5

### ISSUE THREAD

**Issue by Crunchepillar** [CleverRaven/Cataclysm-DDA#29026]
**Versions and configuration(please complete the following information):**
 - OS: Win10
 - Game Version: 0.D-1027-ge0c9fb5
 - Graphics version: Tiles
 - Mods loaded:
  "dda",
  "no_npc_food",
  "filthy_morale",
  "makeshift",
  "More_Survival_Tools",
  "alt_map_key",
  "Urban_Development",
  "DP_XOTTO_INDICATORS",
  "more_classes_scenarios",
  "cars_to_wrecks"

**Additional Context**
Last actions were stabbing a zombie through with the pipe spear's critical impale and then the enemy getting turns and it crashed. Sorry I can't be much more helpful but this crash log may as well be in cuneiform for all I can read into it.

CRASH LOG FILE: config/crash.log
VERSION: 0.D-1027-ge0c9fb5
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x555FB5[cataclysm-tiles.exe+0x155FB5]
    @0x556B62[cataclysm-tiles.exe+0x156B62]
    SMPEG_error+0x4B034@0xE280A0[cataclysm-tiles.exe+0xA280A0]
    _C_specific_handler+0x98@0x7FF90DFF7C58[msvcrt.dll+0x27C58]
    _chkstk+0x11D@0x7FF91088F7DD[ntdll.dll+0x9F7DD]
    RtlWalkFrameChain+0x13F6@0x7FF9107FD856[ntdll.dll+0xD856]
    KiUserExceptionDispatcher+0x2E@0x7FF91088E70E[ntdll.dll+0x9E70E]
    SDL_LogCritical+0x12FD6@0xE48976[cataclysm-tiles.exe+0xA48976]
    IMG_LoadWEBP_RW+0x4413D0@0x135B2E0[cataclysm-tiles.exe+0xF5B2E0]
    IMG_LoadWEBP_RW+0x19DCCE@0x10B7BDE[cataclysm-tiles.exe+0xCB7BDE]
    initterm_e+0x1AB@0x7FF90E00A2BB[msvcrt.dll+0x3A2BB]
    @0x556AA6[cataclysm-tiles.exe+0x156AA6]
    IMG_LoadWEBP_RW+0x188DE8@0x10A2CF8[cataclysm-tiles.exe+0xCA2CF8]
    IMG_LoadWEBP_RW+0x4A34D3@0x13BD3E3[cataclysm-tiles.exe+0xFBD3E3]
    IMG_LoadWEBP_RW+0x4A8900@0x13C2810[cataclysm-tiles.exe+0xFC2810]
    @0x99C26A[cataclysm-tiles.exe+0x59C26A]
    @0x99D3D8[cataclysm-tiles.exe+0x59D3D8]
    @0x680F41[cataclysm-tiles.exe+0x280F41]
    @0x682F93[cataclysm-tiles.exe+0x282F93]
    IMG_LoadWEBP_RW+0x4D91C9@0x13F30D9[cataclysm-tiles.exe+0xFF30D9]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FF90FC13DC4[KERNEL32.DLL+0x13DC4]
    RtlUserThreadStart+0x21@0x7FF910863691[ntdll.dll+0x73691]

**Comment by ZhilkinSerg** [comment]
Were there open fire anywhere nearby?

**Comment by Crunchepillar** [comment]
I'm gonna close this cause I think it was resolved with a recent fix for several other segfaults.
