### ISSUE TITLE
Switching firing modes and ammo in firing menu doesn't work

### ISSUE THREAD

**Issue by nexusmrsep** [CleverRaven/Cataclysm-DDA#29032]
**Describe the bug**  

Firing mode cycling option in firing menu is bugged. Same with ammo change.
Both are linked to they respective local keys:

![image](https://user-images.githubusercontent.com/39925111/55035726-00d6ea80-5019-11e9-8b46-ecb75ed818af.png)

but they are not mentioned here:

![image](https://user-images.githubusercontent.com/39925111/55035751-13e9ba80-5019-11e9-8798-60ae36d0ce49.png)

and they simply don't work.

**To Reproduce**  
1. Make a player with a gun with auto/semi modes, magazine, and some ammo (different types at best).
2. Try to aim at a wall - activate firing menu.
3. Check local menu keybindings for firing mode cycling (auto/semi/etc.) & ammo change
3. There's no way to use that options from that menu.

**Expected behavior**  
You should be able to cycle firing modes from firing menu.
You should be able to reload different ammo from firing menu.

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version: [most recent experimental]
 - Graphics version: [Tiles]
 - Mods loaded: [vanilla]

**Comment by anonym** [comment]
Just noticed this and was gonna report it. I had a quick look and it could be the fix for #18724 (commit a4af67e9e986f042fd53aa81f12668e0d76cb3af by @mugling. Want to have a look?). If I revert to the `relevant->gun_cycle_mode()` approach I can switch gun modes fine. But that fix landed 1½ years ago; have these two actions been broken for that long really? If not, then I'm wrong and the problem lies elsewhere.

**Comment by anonym** [comment]
Actually, it seems like the `on_mode_change` callback isn't set when firing your wielded weapon, so I think we need something like this:
```diff
--- a/src/ranged.cpp
+++ b/src/ranged.cpp
@@ -1459,6 +1459,8 @@ std::vector<tripoint> target_handler::target_ui( player &pc, target_mode mode,
         } else if( action == "SWITCH_MODE" ) {
             if( on_mode_change ) {
                 ammo = on_mode_change( relevant );
+            } else {
+                relevant->gun_cycle_mode();
             }
         } else if( action == "SWITCH_AMMO" ) {
             if( on_ammo_change ) {
```
I don't really get what "switch ammo" is supposed to do exactly, and I haven't at all tried to understand these callbacks or where they are supposed to be set, so I'll just leave the above as a clue for whoever picks this up. Feel free to open a PR with the above change if you did the homework and believe it makes sense.

**Comment by nexusmrsep** [comment]
Your solution is working, and is quite effective since it doesn't touch the call backs themselves, and I'm half way to dropping a PR fix. Have to fix the display too to make it show the help for the options. Switch ammo for the guns should actually call reload, so the player can change magazine if he has another. I'll add that option too, and it can also be done without touching callbacks, though it has to kick you of of the menu to properly trigger activity handlers.

Thanks for the good advice.
