### ISSUE TITLE
Make foldable vehicles trackable when folded/track their last unfolded location

### ISSUE THREAD

**Issue by adamkad1** [CleverRaven/Cataclysm-DDA#29039]
What the title says. i sometimes lose my cart when i miss the message that my vehicle cargo space is full, so it would be nice if you could track folding vehicles when folded, or have it track their last unfolded location

**Comment by Beetlecat** [comment]
That could work for generically "favorite"-ing an item as well. Though I'm not sure how realistic that is, given that we misplace things all the time -- and you *were* given in-game notification that the thing you were loading somehow magically fell onto the ground. ;)

**Comment by adamkad1** [comment]
i know that, but i sometimes miss the notification among all the other stuff that i do at the moment

**Comment by Crunchepillar** [comment]
I would suggest getting in the habit of [e]xamining each cargo tile on your vehicle after you modify its contents to make sure the option to pick items up off the ground isn't available before even starting up the engine. It took me a minute to get that drilled in but now I never leave things behind. Alternatively you can use advanced management on the slash key [\] to move things from your inventory to the cargo space and it won't even allow you to overstock it so you never lose items.

While I think your suggestion has merits I also think with proper use of the tools you already have you can build good habits that remove the need altogether. 😸

**Comment by adamkad1** [comment]
pshh, habits

**Comment by kevingranade** [comment]
This feature exists, when you fold or unfold a vehicle, open the map interface and add a note.
