### ISSUE TITLE
Include minimap while peeking

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#29038]
**Is your feature request related to a problem? Please describe.**  

  Sort of?  With the changes to the sidebar, things are now a bit wonky.  My issue is that now, when using peek 'X', the minimap vanishes.  It didn't used to be this way, and I'm not sure why it went away or if it was intentional.  Because of this it is difficult to quickly 'peek' and see enemies, requiring you instead to use 'x' to pan around in all directions to see if there are enemies about.

  I am on 8665.  I am also using 'classic' sidebar settings.

**Describe the solution you'd like** 
 
  I don't see any reason why the minimap should disappear just because I'm peeking?  I'd like it to be an option, at least.

**Describe alternatives you've considered**  

  Sucking it up and getting used to it.

**Additional context**  

  If you tell me to suck it up, I will.  I just liked it the way it used to be.

**Comment by Crunchepillar** [comment]
It would be nice if the mini-map didn't go on vacation while peeking but you can still use shift+V to quickly enumerate all the monsters and items your character can see while peeking and I find that a satisfactory alternative for now.
