### ISSUE TITLE
Delayed spawns rot food the player starts with

### ISSUE THREAD

**Issue by ianestrachan** [CleverRaven/Cataclysm-DDA#29037]
**Describe the bug**  
Discovered during the writing of #28841. If you have a profession with a delayed start (The Next Summer, for example) and you start with perishable food in your inventory, the food is rotten unless it's extremely long-lived.

This appears to be because the items you start with always have a birthday of 0. I tried to fix this by setting the birthday to calendar::turn in newcharacter.cpp#player::create when the items are inserted into the player's inventory, but something seems to set the birthday back to 0 by the time the first rot check comes up, and I was unable to find where this is.

**To Reproduce**  
Steps to reproduce the behavior (easier now that #28841 is merged):
* Create a new world where the Delayed Spawn option is set to 182 days (2 seasons).
* Start the game.
* Create a new character in the new world, with the Otaku profession (it starts with a cheeseburger).
* Look in your inventory. Observe that, as soon as the game starts, you have a fresh cheeseburger in your inventory (because no rot checks have been made yet).
* Move 1 step in any direction.
* Look in your inventory. The cheeseburger is now suddenly rotten.

**Expected behavior**  
Perishable items the player starts with ought to be fresh, even if the rest of the items around them in the world have rotted. Who would carry a rotten burger around for a year?

**Comment by nexusmrsep** [comment]
Check calc_rot() in item.cpp.
It compares calendar::turn with item's last_rot_check to determine passage of time. Didn't go deep with the problem, but my rough guess is that setting item birthday without updating last_rot_check may result this effect.

**Comment by ianestrachan** [comment]
You are right, though in the context of my original discovery (the linked PR) I am taking the max of the item's `birthday`, `calendar::start`, and `last_rot_check`, and somehow all of them are zero even if the birthday is set explicitly.

Perhaps it would be reasonable to automatically set last_rot_check to the same value as the birthday when the birthday is updated (having a last rot check prior to the item existing is kind of nonsensical, after all).

**Comment by ianestrachan** [comment]
I cannot for the life of me find where the item's values get reset. I went over to profession.cpp where it returns the list of items and made sure all the items created had their birthday set in the constructor, I even updated the constructors to set `last_rot_check` along with the birthday, and no matter what, bday and last_rot_check are both 0 on the first invocation of calc_rot(). I'm at a loss to figure out where it keeps getting set back to 0.
