### ISSUE TITLE
Being blinded wakes you up

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#29033]
**Describe the bug**  
Being blinded wakes you up

**To Reproduce**  
1. Have a condition that will cause moments of blindness. A parasite in your head will do it.
2. Try to sleep.
3. Be continually woken up as you lay in a dark place with your eyes closed and unconscious because you suddenly can't see.

**Expected behavior**  
A change in sighted status should not wake you up.

**Versions and configuration(please complete the following information):**
 - OS:  Windows 10
 - Game Version: 0.D-947-g980ca05
 - Graphics version: Tiles
 - Mods loaded: cdda, Disable NPC Needs, Simplified Nutrition, StatsThroughSkills, Garden Pots, Makeshift Items Mod, Medieval & Historic Content, More Survival Tools, Alternative Map Key, Boats, Folding Parts Pack, Vehicle Additions Pack, Tanks & Other Vehicles.

**Comment by thquinn** [comment]
Looks like that event also causes damage: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/player_hardcoded_effects.cpp#L738

**Comment by Night-Pryanik** [comment]
I think there's nothing wrong with getting damage by brainworms even while sleeping.

**Comment by thquinn** [comment]
Definitely not, but the message could be changed slightly if you're asleep.
