### ISSUE TITLE
Crashing to desktop while exploring or driving

### ISSUE THREAD

**Issue by Ilysen** [CleverRaven/Cataclysm-DDA#29049]
**Describe the bug**  
While generating new tiles, the game crashes to desktop at random. Relaunching and regenerating those tiles sometimes causes it, and sometimes not. This is the exact behavior as in #26342, but as that was fixed some time ago, I'm not sure what's causing it. I unfortunately can't provide any kind of logs for this, because the `debug.log` doesn't seem to log anything; the game just abruptly crashes.

**To Reproduce**  
1. Drive around or explore.
2. Crash to desktop at random!

**Expected behavior**  
For the game to not crash to desktop.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: Build 8611 built from source; current version is modified, but the crash occurred before any modifications from the build
 - Graphics version: Tiles
 - Mods loaded: CGP, Makeshift Items Mod, More Survival Tools, Medieval and Historic Content, Alternative Map Key, Boats, Folding Parts Pack, No Ants, Disable NPC Needs, Filthy Clothing, Manual Bionic Installation, Safe Autodoc, Simplified Nutrition.

**Comment by golankra123** [comment]
Does it still happen on the newest versions?
What's the speed of the vehicle your driving?
What are your world settings?
If possible try to send a save file - I would try to reproduce it on my end.

**Comment by Ilysen** [comment]
I haven't updated, since this is a version with modified C++ and can't easily be updated. It was either build 8611 or 8613; the speed was 6/t/t. I'll post world settings in a bit, and I'll try on the newest version as well.

**Comment by Ilysen** [comment]
I wasn't able to reproduce it on the latest Git build, but I *was* able to reproduce it on an earlier build that came *after* 8611, so it's some kind of bug caused by a version in between. I'll start looking around and see if I can't find anything, but it seems this issue is localized to me.

**Comment by Ilysen** [comment]
Reopening this, as I unexpectedly reproduced it while testing a different PR on the latest build.

**Comment by neitsa** [comment]
@Ilysen Do you happen to have a save file where it can be reproduced (even if it's not with 100% certainty)?

I'd be glad to take a look at this one. Thanks!

**Comment by Ilysen** [comment]
I've unfortunately already deleted the file (since the PR I was testing was merged).

**Comment by kevingranade** [comment]
Fixed by #29753
