### ISSUE TITLE
In drop menu, ability mark to drop all non-favorite and non-worn items 

### ISSUE THREAD

**Issue by KarateSnoopy** [CleverRaven/Cataclysm-DDA#29041]
**Is your feature request related to a problem? Please describe.**  
When coming back from a looting raid, I have a lot of stuff in my inventory and I want to drop everything except the items I want to keep on me.  This is a bit tricky right now.  I know there's a tab option to drop all of a specific category but I really want to quickly drop all items I don't want and know when I leave my base I'm not missing vital gear.  

**Describe the solution you'd like**  
Using the current ability to mark inventory items as favorite, and I want to add the ability to drop all non-favorite and non-worn items.  On the drop menu, you can press a key to mark all non-favorite and non-worn items as items to be dropped on the right hand menu called "items to drop" . You can edit the "items to drop" list as usual before dropping the items, and pressing enter will confirm the drop list as usual. So basically to drop all non-favorite and non-worn items it'd be d, *, enter with default keybindings.

**Additional context**  
If this sounds like a something worth having in the game, I can work on coding up the feature as its been bugging me while playing the game and I knows code.

**Comment by ZhilkinSerg** [comment]
You already can favorite items #28061, so just need to add command to "drop all, but favorite items"

**Comment by KarateSnoopy** [comment]
Thanks @ZhilkinSerg.  I'll work on that feature

**Comment by ZikoWong** [comment]
I'm not sure if I can speak here. If not, I'm terribly sorry.
English is not my mother tongue. I hope you can understand what I want to say.
I think we can add a favorite type.
Marked by us will appear in this type

**Comment by jokaro** [comment]
It would be great to keep the items marked as favorite at the bottom of the list when auto-dropping stuff along with your backpack. So that those are the last things being dropped. Hate that my inhaler always gets dropped with my backpack.

**Comment by KarateSnoopy** [comment]
@jokaro what I'm planning to do with this change is on the drop menu, you can press a key to mark all non-favorite and non-worn items as items to be dropped on the right hand menu called "items to drop" .  You can edit the "items to drop" list as usual before dropping the items, and pressing enter will confirm the drop list as usual.  So basically to drop all non-favorite and non-worn items it'd be d, *, enter with default keybindings.

In your case it sounds like you should mark your inhaler as favorite and wear your backpack and then neither would be dropped by d, *, enter
