### ISSUE TITLE
Ascending Z-levels

### ISSUE THREAD

**Issue by Gmiz** [CleverRaven/Cataclysm-DDA#29042]
Here's an idea: We could have z-levels ascending in addition to already existing descending ones. So you could build a skyscraper with 20 floors above the ground or so. At the top there would be a roof or something. Making this would require a lot of work though. There would be problems such as: What would happen when a 20-floor building collapses? It would probably fall like a tree falls currently.

BTW, this is just an idea, but IMHO it would add a very powerful new dimension to the game.
I know z-levels are a really hard thing to code at this point probably, but I would appreciate everyone's opinion, including the devs and their perspective.

What problems do you think might occur during the process of adding something like this?

**Comment by OrenAudeles** [comment]
Current z-level range is from [-10, +10], so 10 levels below surface level and 10 levels above. While technically possible to increase this range we aren't currently doing much that requires increasing the above surface z-level range.
