### ISSUE TITLE
Fire not stops upon consuming all fuel and can spread over any wall.

### ISSUE THREAD

**Issue by Vasyan2006** [CleverRaven/Cataclysm-DDA#29046]
**Describe the bug**  
Fire not stops upon consuming all fuel and can spread over any wall.

**To Reproduce**  
Start fire in mansion basement with brick walls and rock floor.
Fire spread over solid rock.
![001](https://user-images.githubusercontent.com/34272516/55086609-5eb71100-50b1-11e9-8155-4598b76cdcb2.png)

Start fire in brazier outside.
Character inside the building is damaged by overheating.
![002](https://user-images.githubusercontent.com/34272516/55086670-755d6800-50b1-11e9-817b-2a9b3ac179e9.png)

**Versions and configuration(please complete the following information):**
 - OS:  Windows 10 x64
 - Game Version: 8663
 - Graphics version: Tiles 
 - Mods loaded: none

**Comment by Aakochar** [comment]
Probably reproduced. I saw eternal fire in braziers on
OS: Linux x64
Game version: several, probably from 8659 to 8668
Graphic version: Curses
Mods loaded: default setup.

**Comment by Wokko1** [comment]
Fire started from a newspaper page on the road tiles resulted in 2x2 raging fire without further fuel consumption.
Windows 10 x64
0.D 8666
Tiles
No mods

**Comment by adamkad1** [comment]
so cataclysm dda is now a pyromaniac simulator?

**Comment by Night-Pryanik** [comment]
> so cataclysm dda is now a pyromaniac simulator?

What did you mean by "now"? It was always!

**Comment by Vasyan2006** [comment]
>pyromaniac simulator
Either this or "Fungaloid Conqueror".

**Comment by davidpwbrown** [comment]
related to https://github.com/CleverRaven/Cataclysm-DDA/issues/29060, possibly caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/28058 if the behaviour is different to previous
