### ISSUE TITLE
Photos taken add to a player accessible "Monster Compendium" from a tablet

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#29048]
Photos of monsters could be expanded upon. 

Suggestion:
Each time the player takes a photo of a monster, the description of the monster is recorded and added to a list that the player slowly builds over time with each photo taken. If the monster has been dissected "x" amount of times, the player could then receive a small boost to damage against that particular type. This simulates the survivor slowly gaining knowledge about the anatomy of the monsters in the game and logging his/her observations.

The list should be simple like the debug list for spawning monsters or alternatively, the killboard could be used by adding a simple symbol i.e. "+" next to each monster that has been photographed and dissected the needed number of times. This symbol is selectable and brings up the description of the monster.

Alternative supplemental book idea:
The player could even be allowed to craft books in "volume" format. After "x" amount of newly discovered species, a volume may be printed using a recipe that stores them in book format. It would have the players name as the author. 

Reading this book can then increase the player's damage against the monsters recorded in that book. If the killboard is used as the selectable list i.e. '++' could be added next to the monster and would indicate that it has been photographed, dissected the correct number of times, has been written and read in a volume and the player is receiving a damage bonus against this monster.

--------------------------

Ideally, this should be done in a way that any new monster added is automatically supported. The monster is recorded in the killboard and its data is stored locally in whatever mod so hopefully that wouldn't be too hard.

**Comment by CoroNaut** [comment]
I like the small damage boost aspect, but learning weaknesses in these creatures should require some minimum skill set

**Comment by curstwist** [comment]
also adding a bonus to butchering/skinning/dissecting times would be nice too.  Maybe become part of that skill-up system idea that I've seen mentioned.  

In game bookmaking as a whole should be a different idea/PR I think?  there are other things that could make use of it.

**Comment by Phenomphear** [comment]
After some discussion on discord another idea/change was suggested:

Rather than damage bonus, extended descriptions of monsters.

A user wrote:

> "What I would be more interested in is not direct mechanical benefits, but documenting more about the creature, possibly stuff that isn't obvious through the game's normal interfacing."

**Comment by Wokko1** [comment]
Why not both?
Idk about others, but I wouldn't be interested in simply extended descriptions. Damage or crit chance boost would feel more rewarding.

**Comment by kevingranade** [comment]
If theres a damage boost, it needs to be oriented around an initial inability to target a "critical" hit, i.e. getting a critical hit is unrelated to how good you are at landing a blow or placing a shot, because you don't know where to aim.  This would only occur on creatures so alien that you can't even guess at where to hit them.

In other words, this doesnt apply to any kind of natural animal, including mutated versions, or most zombies.  In fact I'm having trouble coming up with things that would qualify, maybe mi-gos or giant worms?

**Comment by rmgr** [comment]
I think even if it didn't have a damage bonus and was just for extended lore, it'd be pretty cool. Might scratch that collecting pokemon type itch. Only with zombies and mi-go

**Comment by Phenomphear** [comment]
Unfortunately, there are only a few extremely exotic monsters like you said @kevingranade So, setting the damage boost aside we would be looking at a pretty straight forward compendium. The next best way I can think of to mesh it all together would be delivering this information to NPC's for quest rewards. This would also tie in nicely with the added book idea.
