### ISSUE TITLE
Map on side?

### ISSUE THREAD

**Issue by SirClarke** [CleverRaven/Cataclysm-DDA#29059]
**Describe the bug**  
I don't know what its called but the Info Panel on the side is not all the way down the side

**To Reproduce**  
Happens on new Character and Maps 

**Expected behavior**  
The Panel would be all the way down the side

**Screenshots**  
![Screenshot (57)](https://user-images.githubusercontent.com/31796878/55109163-873c0c80-50ab-11e9-9b92-f06a2d36371a.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1062-g14a0cbf
 - Graphics version: Tiles
 - Mods loaded:
Dark Days Ahead
Medieval and Historic Content
More Survival Tools
Classic Roguelike Classes
StatsThroughSkills
Vehicle Additions Pack
Tanks and Other Vehicles
Boats
Folding Parts pack
Filthy Clothing 
Makeshift Items Mod
Classes and Scenarios Mod
Mutant NPCs
Necromancy
Mythological Replicas
Modular Turrets
Salvaged Robots
Arcana and Magic Item
Disable NPC Needs
More Locations
Fuji's More Buildings
Urban Development
**Additional context**  
Sorry if I can't be of more help as I don't know much about this kinda stuff

**Comment by Crunchepillar** [comment]
Yea that's funky, have you tried using } to manage your panels and see if its a specific one? Or maybe you had the pixel map height setting in the options menu set to something that isn't playing well with the panels.

If those suggestions don't work then I'm outta ideas 🦐

**Comment by SirClarke** [comment]
Nope damn thanks anyways that does not seem to be it. I tried changing everything you suggested but it did not seem to work sadly. I mean it's not unplayable thankfully but still a bit odd to get used to.

**Comment by SirClarke** [comment]
I've got a Terminal Width of 240 And a Height of 67 for a 1920 by 1080 Monitor if that makes any difference... and it's on Window borderless so i can Tab out if need be

**Comment by KorGgenT** [comment]
#28884

**Comment by SirClarke** [comment]
Thanks, I'll try and keep an eye on this but most of the Tech Talk goes over my head
