### ISSUE TITLE
Segfault whilst saving game.

### ISSUE THREAD

**Issue by drayath** [CleverRaven/Cataclysm-DDA#29053]
**Describe the bug**  
Selected save and exit game.
Got a segfault during save.
Save file is now corrupted and can't be loaded.

Crash Dump: [core.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3014814/core.zip)
Corrupted Save: [save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3014815/save.zip)

Don't have crash log (was wiped during crash trying to load save & also not written to debug log)

Version: cataclysmdda-0.D-8655
Mods:   "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "safeautodoc",
  "no_survivor_armor",
  "alt_map_key",
  "mutant_npcs",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "generic_guns",
  "modular_turrets",
  "More_Survival_Tools",
  "Medieval_Stuff",
  "makeshift",
  "growable-pots",
  "Salvaged_Robots",
  "blazemod",
  "Tanks"

**Comment by Tharn** [comment]
I had the same thing happen yesterday. The segfault produced a savefile that was cut off at the part of "weapon" data in JSON. The character was wielding 15 throwing knives, which were not saved correctly I assume.

**Comment by drayath** [comment]
@Tharn If you have the crash.log from this it may help the devs.

FIle writing is buffered (i.e written to disk in batches) so could be any point in the writing of that file (after the cutoff point) that failed. crash log stacktrace or dump is the only real way of telling where the issue likely is

**Comment by Tharn** [comment]
I think this was the one.

```
CRASH LOG FILE: config/crash.log
VERSION: 0.D-1060-g7c5c706
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x556EA5[cataclysm-tiles.exe+0x156EA5]
    @0x557A52[cataclysm-tiles.exe+0x157A52]
    SMPEG_error+0x4B034@0xE29110[cataclysm-tiles.exe+0xA29110]
    _C_specific_handler+0x96@0x7FFD90401E26[ntdll.dll+0x81E26]
    _chkstk+0x9D@0x7FFD9041349D[ntdll.dll+0x9349D]
    RtlRaiseException+0xF67@0x7FFD903D48D7[ntdll.dll+0x548D7]
    KiUserExceptionDispatcher+0x3A@0x7FFD9041262A[ntdll.dll+0x9262A]
    IMG_LoadWEBP_RW+0x27B78C@0x119670C[cataclysm-tiles.exe+0xD9670C]
    @0x843332[cataclysm-tiles.exe+0x443332]
    @0x6392DF[cataclysm-tiles.exe+0x2392DF]
    @0x680EC6[cataclysm-tiles.exe+0x280EC6]
    @0x831FAB[cataclysm-tiles.exe+0x431FAB]
    @0x83352A[cataclysm-tiles.exe+0x43352A]
    IMG_LoadWEBP_RW+0x4DA080@0x13F5000[cataclysm-tiles.exe+0xFF5000]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x22@0x7FFD8DA213D2[KERNEL32.DLL+0x13D2]
    RtlUserThreadStart+0x34@0x7FFD903954F4[ntdll.dll+0x154F4]
```

**Comment by LyleSY** [comment]
I'm not able to replicate on a current vanilla experimental. Save works as expected. I'm guessing one of those mods was bugged and corrupted the save. Here's what I see in the log:

src/savegame.cpp:245 [void game::unserialize(std::istream&)] Bad save json
EOF: expected JSON value but got 'ÿ'

That makes me think a mod threw a value JSON can't understand into the save file and killed it but I'm open to being corrected by someone who reads logs better than me.

**Comment by Night-Pryanik** [comment]
Closing until confirmed.
