### ISSUE TITLE
Fire burns without fuel

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#29060]
**Describe the bug**  
Fire continues to burn for several minutes in the absence of fuel

**To Reproduce**  
wish for
• brazier
• a stack of two by fours
• a lighter
then toss a two by four in the brazier and light it
then pull it out of the brazier
notice that
• burnt two by four doesn't spread fire
• fire continues burning for a LONG time

**Expected behavior**  
Either fire follows the two by four, or extinguishes

**Screenshots**  
ask if need

**Versions and configuration(please complete the following information):**
 - OS: ask if need
 - Game Version: ask if need
 - Graphics version: ask if need
 - Mods loaded: ask if need

**Additional context**  
• It's likely the fire is consuming part of the wood and then continuing to burn, presumably for efficiency, with large fires constantly checking for fuel could become taxing for the system.  Maybe it should check more often for small fires (eating in smaller chunks), and less often for roaring fires or infernos (eating in bigger chunks) for scaling if this is indeed a problem?
• Likely root cause of the balance issue in #28855

**Comment by nexusmrsep** [comment]
Fire has internal fuel count and unfortunately it's code is quite old and tangled, so there are also two methods of burning. One burns items gradually adding small amounts of fuel. Second burns items quickly adding lots of invisible fuel. Second one can create illusion of fuelless fire. Methods differ between contained fires (braziers etc.) and wild free fires.

**Comment by davidpwbrown** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/29046 possibly caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/28058 if the behaviour is different to previous
