### ISSUE TITLE
Fire doesn't spread to the left.

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#29078]
**Describe the bug**  
Fire does not spread to the left on fungus.

**To Reproduce**  
1. Light a decently sized patch of fungus on fire.
2. Watch it burn.
3. Fire will exclusively spread to the right, up and down, never to the left, even after over 12 hours of burning inside the reality bubble.

**Expected behavior**  
Someone in the discord told me this is happening because of wind, but even if wind is affecting it, it shouldn't block the spread of fire to the left 100%, it's creating vertical walls of fire as seen in the screenshot below.

**Screenshots**  
![Untitled](https://user-images.githubusercontent.com/45204409/55162918-1fe49200-5169-11e9-876f-552c807da614.png)

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version: [0.D-1075-gc943431]
 - Graphics version: [Tiles]
 - Mods loaded: [Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Just Craftable Gunpowder, Makeshift Items Mod, PKs Rebalancing, Alternate Map Key, Mutant NPCs, More Locations, Fuji's More Buildings, Urban Development, PK - No Doom Monsters, Nonperishable Overhaul, DinoMod, Medieval and Historic Content, Vehicle Additions Pack, Tanks and Other Vehicles]

**Additional context**  
The fire spread extremely quick to the right, so it seems very plausible that wind could be the cause, however I don't know whether or not wind is implemented in the current iteration of the game.

**Comment by Inglonias** [comment]
[Wind affecting fire was merged four days ago](https://github.com/CleverRaven/Cataclysm-DDA/pull/28058)

**Comment by davidpwbrown** [comment]
It's definitely the wind, I'm no fire expert, but if the wind is strong enough it could potentially mean it hardly spreads at all into the wind.... I could perhaps add an RNG low change to still spread into the wind...

**Comment by golankra123** [comment]
I've tested it on version `0.D-1158-g2dc4ad2`

And messing around with the wind direction affected how the fire spread and it spread the same for me as it did for you - like there is an invisible wall. 

after I've changed the wind direction it spread to the other side as well

**Comment by tinukedaya** [comment]
If there is a fire next to a tree, it will eventually catch fire as well, even if the wind blows opposite way... It will just take a little longer.  So I think adding a low chance to spread into the wind makes sense.  And it will look better as well not like this wall of fire.
