### ISSUE TITLE
(Character Creation) DEBUG:line 551:23: assignment does not update value

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#29079]
**Describe the bug**  
 DEBUG    : line 551:23: assignment does not update value

    "id": "brownie",
    "type": "COMESTIBLE",
    "comestible_type":
                      ^
                       "FOOD",
    "name": "brownie",
    "copy-from": "brownie_weed",
 
 FUNCTION : void report_strict_violation(JsonObject&, const string&, const string&)
 FILE     : src/assign.h
 LINE     : 46

**To Reproduce**  
See modlist load below. Error appears when attempting to create a character on a world with the following mod loadout. 

**Versions and configuration(please complete the following information):**
PR (8676)

**Additional context**  
MODLIST:
  "dda",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "aftershock",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "mutant_npcs",
  "crazy_cataclysm",
  "alt_map_key",
  "more_locations",
  "Urban_Development",
  "deoxymod",
  "blazemod",
  "Tanks",
  "boats",
  "no_religious_Texts",
  "no_olg_guns",
  "no_flaming_weapons",
  "StatsThroughSkills",
  "sleepdeprivation",
  "filthy_morale"

**Comment by ZhilkinSerg** [comment]
#29076

**Comment by kevingranade** [comment]
Should be addressed by #29076

**Comment by Tharn** [comment]
It's not just brownies that show this error for me:

```
src/assign.h:46 [void report_strict_violation(JsonObject&, const string&, const string&)] line 551:23: assignment does not update value


    "id": "brownie",
    "type": "COMESTIBLE",
    "comestible_type":
                      ^
                       "FOOD",
    "name": "brownie",
    "copy-from": "brownie_weed",

17:37:03.473 ERROR : src/assign.h:46 [void report_strict_violation(JsonObject&, const string&, const string&)] line 559:15: assignment does not update value


    "volume": 3,
    "price": 5000,
    "charges":
              ^
               8,
    "material": "wheat",
    "symbol": "%",

17:37:03.936 ERROR : src/assign.h:46 [void report_strict_violation(JsonObject&, const string&, const string&)] line 565:17: assignment does not update value


    "calories": 174,
    "fun": 7,
    "spoils_in":
                ^
                 420,
    "flags": [ "EATEN_HOT" ]
  }
```

**Comment by ZhilkinSerg** [comment]
It is an error related to three fields in brownies item definition.
