### ISSUE TITLE
json mods multilang translation

### ISSUE THREAD

**Issue by Adevald** [CleverRaven/Cataclysm-DDA#29077]
**Is your feature request related to a problem? Please describe.**  
I have some suggestions about way to translate mod. Now its not enough comfortable, and a mod can't place more than one language. 

**Describe the solution you'd like**  
What if automatically (or maybe not automatically) create additional file for whole possible text in mod? it can be like another json, or other file. I think adding new texts in a file its make translation procces more convenient for big mods content. 

it will be placed in the mod directory.

(examle of file organization)
*\translition\ru_RU.json
it also can be sort in files by types (merged by approximate categories )
*\translition\ru_RU\items.json
*\translition\ru_RU\monsters.json
*\translition\ru_RU\overmap.json
*\translition\ru_RU\npc.json
*\translition\ru_RU\missions.json
*\translition\ru_RU\other.json

**Describe alternatives you've considered**  
It can also be created manually.

Or, it can placed directly in main files (items.json as an example) like additinal syntax 
"name":  "nails",
"name": [{ru_RU , "Гвозди"}],
"description": [{ru_RU , "Просто гвозди"}],

**Additional context**  
Probably one of the most important conditions, that modders (not translators) dont need to perform additional actions if they dont  want to translate the mod themselves, and easy to maintain when it perform updating

**Comment by ZhilkinSerg** [comment]
There are [scripts](https://github.com/CleverRaven/Cataclysm-DDA/tree/master/lang) to extract strings from json which you can use to pull strings from mod files, make translations on [Transifex](https://github.com/CleverRaven/Cataclysm-DDA/tree/master/lang) (or anywhere else), combine these translations with existing localization files and compile them for distribution.

**Comment by Adevald** [comment]
@ZhilkinSerg I think its a useful script, but in my opinion there is bad idea ti pollute code with tons of text with mods which someone doesnt uses. Also, its more comfortable, when you operate directly with the json, and you dont need to compile anytime when you change couple files, and then wait when it pull it on master.

Besides, i dunno how to combine mod translition files in master file correctly.

**Comment by ZhilkinSerg** [comment]
> 
> 
> @ZhilkinSerg I think its a useful script, but in my opinion there is bad idea to pollute master code with tons of text with mods which someone doesnt uses. Also, its more comfortable, when you operate directly with the json, and you dont need to compile anytime when you change couple files, and then wait when it pull it on master.
> 
> Besides, i dunno how to combine mod translition files in master file correctly.

I am not suggesting adding anything from third-party mods to `master`. What I am saying that there is an existing infrastructure one can utilize to translate their mods. It can be not so easy to use, but it is a problem for mod authors to resolve.

Adding another translation infrastructure (like the one you suggest with json) would only confuse people. [Maybe](http://www.gnu.org/software/gettext/manual/html_node/Contexts.html) it is possible to use several files for same language in existing process - someone should look into it.

There are json-only ways too - you can either distribute several translated mods versions or make a master mod and several dependent mod with translations which utilize `copy-from` to change translatable strings.

**Comment by Adevald** [comment]
> There are json-only ways too - you can either distribute several translated mods versions or make a master mod and several dependent mod with translations which utilize `copy-from` to change translatable strings.

I am already do. And that is why i soggest that infrastructure. Because now, json translition is incredibly dumb, when it comes to mod updating. Every time whem mod updates, it becomes incredibly pain in the ass, like move every json string onto new files. I always try to automate it with github, but it get worsed.

I think simplification of procces of translition in the long run only makes everything better, not confusing.

**Comment by kevingranade** [comment]
@ZhilkinSerg outlined a usable solution, there is no reason for us to build a separate system for this.
