### ISSUE TITLE
3D FOV makes the dots minimap render oddly.

### ISSUE THREAD

**Issue by curstwist** [CleverRaven/Cataclysm-DDA#29088]
**Describe the bug**  
3D FOV makes the dots mini map render oddly.

**To Reproduce**  
1. Turn on 3D FOV and use the dots mini map.
2. Run around for a while, took a few minutes to trigger it.
3. Switch between z levels and mini map will have issues rending the new level, leaving portions of the old level and dragging out images.

I couldn't replicate this in squares or solid maps.  Switching to those would also fix dots for a while.

**Expected behavior**  
A less surreal mini map.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows10
 - Game Version: 0.D-1062-g14a0cbf
 - Graphics version: Tiles
 - Mods loaded: no mods besides defaults.

**Additional context**  
ascend roof, blackout areas are outlines of the buildings from below.
![roof level](https://user-images.githubusercontent.com/39442864/55193260-d605a700-517c-11e9-837e-16c1a5308755.PNG)

return to ground, blue areas are from the roof level.
![ground level 1](https://user-images.githubusercontent.com/39442864/55193265-d9992e00-517c-11e9-91cc-30907af1c220.PNG)

begin moving character, tiles begin to be dragged out.
![ground level 2](https://user-images.githubusercontent.com/39442864/55193269-daca5b00-517c-11e9-960a-cca89f1f3d91.PNG)

moving along  (I began to experience a lot of lag here)
![ground level 3](https://user-images.githubusercontent.com/39442864/55193271-dc941e80-517c-11e9-9c26-27db90dcbcbb.PNG)

returning to the roof
![return to roof level](https://user-images.githubusercontent.com/39442864/55193275-ddc54b80-517c-11e9-8665-5ae57a9e8869.PNG)

**Comment by esotericist** [comment]
For the record, I can replicate this with all three modes (dots, solid, squares).

**Comment by jbytheway** [comment]
Is this still an issue since #30289 was merged?

**Comment by esotericist** [comment]
> Is this still an issue since #30289 was merged?

Thanks for reminding me to test this.

It looks like #30289 fixed the rendering issues. 

There's still the matter of the memory getting messed up by looking too far/down but that's more a matter of how memory is cached (more particularly how many tiles can be remembered) and thus a separate matter.

**Comment by jbytheway** [comment]
Hmm... perhaps we should have a separate map memory for uniform submaps, so that all the ones filled with just air don't require so much memory space.  That would help and make sense (much easier to remember a big empty space!).

**Comment by kevingranade** [comment]
Oh right, I dont know why I didn't notice the significance of this before.
1. Map memory code is very much not 3D aware.  The data structure is, but
not the code itself.
1.a. Tiles the player can see, but aren't drawn aren't captured because the
capture happens in the draw code.
1.b. I'm not sure map memory will generate correct offsets when looking
outside the current level.
1.c. The caching layer that prevents constant re-memorization of tiles
probably doesn't work at all when looking outside the current level.
2. Open air tiles might be horrifically bad for map memory.
