### ISSUE TITLE
Activated Abilities List, Ability Keybindings, and Improved Mutation Trees

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#2908]
People have been talking about how some mutations should be able to be activated like bionics, and I noticed how annoying  it is to choose the Fusion Arm Blaster from the list every time I want to fire it. Has anyone played Caves of Qud? If so, you would probably know about its mutation system. It's similar to the Cataclysm bionic system, but mutations and any other activate-able abilities are all accessible through one menu that classes mutations based on mental and physical. Something similar exists for Dwarf Fortress Adventure Mode: there is an sorted ability menu that allows you to activate any abilities, from natural to acquired, like fire breathing or necromancy.

What I think we should do is change the bionic menu to include both bionics and mutations color coded to show if it's activated, passive, good or bad. The menu can also have other abilities if there are any that would work for it, and could be sorted by body part. For example, horns would be in the head category, and so would Cranial Flashlight. Maybe we could even have a nice full body picture to go along, just so you can see where you mutations are. Lastly, there should be an option to make temporary keybindings for mutations/bionics that are used often, or perhaps add default keybinds for specific bionics.

Also, the mutation classing existent right now (based on animal types) seems like it could be improved on. We can have mutation trees that are more connected, with lesser mutations as the roots, and powerful mutations later on. For example, light sensitive could lead to fangs, which could lead to blood drain.

**Comment by kevingranade** [comment]
There's a mutation menu now, which is as far as we're going to go in this direction I think.
