### ISSUE TITLE
(Character Creation) DEBUG:duplicate bionic id (LINE:1507)

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#29080]
**Describe the bug**  
 DEBUG    : duplicate bionic id
 
 FUNCTION : void load_bionic(JsonObject&)
 FILE     : src/bionics.cpp
 LINE     : 1507
 
 FUNCTION : void report_strict_violation(JsonObject&, const string&, const string&)
 FILE     : src/assign.h
 LINE     : 46

**To Reproduce**  
See modlist load below. Error appears when attempting to create a character on a world with the following mod loadout. 

**Versions and configuration(please complete the following information):**
PR (8676)

**Additional context**  
MODLIST:
  "dda",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "aftershock",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "mutant_npcs",
  "crazy_cataclysm",
  "alt_map_key",
  "more_locations",
  "Urban_Development",
  "deoxymod",
  "blazemod",
  "Tanks",
  "boats",
  "no_religious_Texts",
  "no_olg_guns",
  "no_flaming_weapons",
  "StatsThroughSkills",
  "sleepdeprivation",
  "filthy_morale"

**Comment by anothersimulacrum** [comment]
This is caused because bright night and aftershock are incompatible. Removing either mod would fix this error.

**Comment by ZhilkinSerg** [comment]
Aftershock and Bright Nights mods are incompatible.
