### ISSUE TITLE
SCT drawn with an offset.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#29098]
**Describe the bug**  
Scrolling Combat Text (SCT) is drawn offset to the side instead of being centered on the entity it is portraying.
Happens in curses, probably also Tiles.

**To Reproduce**  
1. Spawn a monster.
2. Enable SCT.
3. Hit the monster a bunch.

**Expected behavior**  
SCT is drawn as if "coming out of" the entity being hit.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Amazon Linux 2 (4.14.88-88.73.amzn2.x86_64)
 - Game Version: 0.D-1155-0.D-1155-g40dfadfb2c (custom build after merging #28884 )
 - Graphics version: Curses
 - Mods loaded: dda + defaults

**Comment by OzoneH3** [comment]
So is the weather on curses.

**Comment by KorGgenT** [comment]
i thought i fixed the weather?

**Comment by OzoneH3** [comment]
@KorGgenT Opened a new ticket #29192
