### ISSUE TITLE
Cant talk to npc companion

### ISSUE THREAD

**Issue by LittleDarkPenguin** [CleverRaven/Cataclysm-DDA#29105]
**Describe the bug**  
After [#8681](http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/8681/changes) I cant talk to my npc companion, as it says he is hostile. I still can use items/examine wounds etc, he still follow me and attack enemies - well, all of [e] menu works, except talking
If downgrade to previous #8680 - all works.

**Screenshots**  
NPC debug info
![npc info](https://user-images.githubusercontent.com/47349494/55220222-5db0eb80-5239-11e9-80d1-f5cf606735d1.png)

Log 
![chat screen](https://user-images.githubusercontent.com/47349494/55220243-6a354400-5239-11e9-844a-f2030e23d21e.png)

Save
[PenguinWorld.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3021786/PenguinWorld.zip)

**Versions and configuration(please complete the following information):**
 - Win 8.1 x64
 - Game Version: 0.D-1142-ge8942a7
 - Graphics version: Tiles

**Comment by Necrosian** [comment]
Same happened to me when i update today.

**Comment by LittleDarkPenguin** [comment]
I'm not sure, but i think reason is in [this](https://github.com/CleverRaven/Cataclysm-DDA/commit/018d9af52e087d9852985978407eee0f6c88f507#diff-80e97f643532c47e218f026bed2432f9) change
