### ISSUE TITLE
Respect favorite items when auto-dropping on over encumbered

### ISSUE THREAD

**Issue by jokaro** [CleverRaven/Cataclysm-DDA#29103]
**Is your feature request related to a problem? Please describe.**  
I wear a duffel bag for looting and usually drop it on the ground when engaging in combat. When I do this a random selection of items are dropped since I no longer have that much room in my inventory. The problem is that a few items vital for me can also be dropped with this random selection. Like m inhaler or anything that I want to keep accessible in combat.

**Describe the solution you'd like**  
The solution would be that if I mark items as favorite this would be respected when auto-dropping. So that all items not marked as favorite are selected for auto-dropping first. The items not marked as favorite are most likely items that I have recently looted and would naturally be stored in the duffel bag.

**Describe alternatives you've considered**  

**Additional context**

**Comment by Night-Pryanik** [comment]
#29099 should address your issue.

**Comment by jokaro** [comment]
Not really the same thing. That features is to drop all unmarked and non-worn items. The issue I point at is when you drop a worn bag and a lot of items get dropped along with it because your volume has been lowered.

**Comment by Night-Pryanik** [comment]
The solution you propose (if implemented) would be the temporary one. The proper solution is to add real containers for all the stuff one is carrying, which is a VERY OLD issue.

**Comment by Mooses2k** [comment]
I'm totally going to post a bounty for this.
