### ISSUE TITLE
Boats Mod - Disassembling Plastic Hull gives more plastic than it requires to craft.

### ISSUE THREAD

**Issue by Mythiran** [CleverRaven/Cataclysm-DDA#29114]
Crafting plastic hull requires 25 plastic chunks. Disassembly produces 50.

**To Reproduce**  
Get 25 plastic chunks.
Craft plastic hull
Disassemble

**Expected behavior**  
You get 50 plastic chunks... +25 plastic chunks, baby!

**Versions and configuration(please complete the following information):**
0.D-1100

**Comment by l29ah** [comment]
See also: https://github.com/CleverRaven/Cataclysm-DDA/issues/28476
