### ISSUE TITLE
Debug map editor missing selection indicator 

### ISSUE THREAD

**Issue by ZikoWong** [CleverRaven/Cataclysm-DDA#29111]
**Describe the bug**  
i use the Google translation，i want the problem described to be understood。

Debug menu， map editor， selection Tile， Lack of 【 】。I don't know how to express this in English. Maybe a selection box?

**To Reproduce**  
1. Debug menu
2. map editor
3. selection Tile

**Expected behavior**  
Restore marquee
![11](https://user-images.githubusercontent.com/48346762/55238515-b00cff00-526f-11e9-8827-79a781171ab2.png)

**Screenshots**  
![11](https://user-images.githubusercontent.com/48346762/55238182-d2eae380-526e-11e9-8a9d-5ec845c801d4.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1158-g2dc4ad2
 - Graphics version: MSX++LIVE_PEOPLE
 - Mods loaded: Dark Days Ahead

**Comment by golankra123** [comment]
Happens on my end also.
[https://youtu.be/kjrp16bTG_w](https://youtu.be/kjrp16bTG_w)

**Comment by davidpwbrown** [comment]
confirmed.
