### ISSUE TITLE
Refugee center NPC went into my car after i grabbed a bench and dragged it there

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#29112]
**To Reproduce**  
1. Drag some benches around.
2. Watch NPCs running around like crazy and stopping in random places.
3. There's no way to push them out of my car.

**Versions and configuration(please complete the following information):**
0.D-1102-g7c3a0383af-dirty

**Additional context**  
[save](https://github.com/CleverRaven/Cataclysm-DDA/files/3023274/2019.03.28.zip)

**Comment by l29ah** [comment]
After dragging some benches back and forth i've managed to lure NPCs out of my car, but now they are staying all around the refugee center, making it more challenging to ride around and spending their lives on random zombies (also producing gun shots when i'm sleeping).

**Comment by NiktoNekto** [comment]
Keep the discussion. So it should be?
NPS from my team in the "guard" starts to run around the territory when I move the furniture, and "breaks down barriers"? broke auto welding ... why?
**версия: 0.D-1191-gf5f1b9a (tiles)**
sorry for my english, i use google translator

**Comment by davidpwbrown** [comment]
This seems more down to the noise-investigation being a bit screwy , then ownership?
