### ISSUE TITLE
Being attacked while lock picking does not trigger warning

### ISSUE THREAD

**Issue by SkuliAdams** [CleverRaven/Cataclysm-DDA#29120]
**Describe the bug**  
When the player begins to pick a locked door, if a zombie approaches and begins to attack the player, they will continue to pick the lock without pausing the game. Encountered at night.

**To Reproduce**  
Attempt to pick a lock at night with a zombie just out of your line of sight.

**Expected behavior**  
A pop up should appear, describing the zombie approaching and asking if you want to stop picking the lock.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D - 1158 - g2dc4ad2
 - Graphics version: Tiles
 - Mods loaded: dda and defaults.

**Comment by Zireael07** [comment]
I guess it needs to be made an activity, if it isn't yet?
