### ISSUE TITLE
Add flame_on graphics to things specificly designed to start a fire inside of it

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#29136]
Any thing what can be lit, brazier, or campfire stone ring for example, right now just puts "fire tile" on it when you start fire inside of it. I do not think this is correct way to present what it is used correctly.
braizer not just go up in flame wholesomely, fire only burn inside of it, and i think it should be represented in the game.
So it would be nice to have ability to set different tiles for correctly_lit and unlit furniture instead of just drawing giant fire what covers it whole.
Ofcourse from my side i will make graphics for any object what needs liten up version.
And also if fire goes out of control, then you can draw fire tile on it representing what fire got out of control and need to be putted out before it spreads on other tiles around it.

**Comment by SomeDeadGuy** [comment]
do not touch

**Comment by Night-Pryanik** [comment]
No discussion in over two years, closing.

**Comment by Zireael07** [comment]
I imagine this would still be useful for tilesets?

**Comment by Night-Pryanik** [comment]
Sure, but it isn't worth an open issue.
