### ISSUE TITLE
Status icons for monsters

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#29137]
Just like for the player and npc i want to set status icons (on fire, bleeding, etc.) for monsters as well.
I will need to be able to set status icon for each type of mosters individually too, cause monsters come in all shapes and sizes so common status icons can be too small or too big for some creatures.

**Comment by golankra123** [comment]
I would attempt at first place on all the monsters the same height for the status icon.
and then mark which monsters need it adjusted
(can save a bunch of time rather from testing it on each monster due to most of them being the same size)

**Comment by SomeDeadGuy** [comment]
yes, set of default status icons for 32x32 monsters, and then status icons if need for individual monster

id something like 
"mon_on_fire" or "mon_bleeding" for default status icon
and IDs like
"mon_zombie_on_fire" for individual type of monster.

**Comment by SomeDeadGuy** [comment]
I still want this. :P
