### ISSUE TITLE
Wearable containers should be categorized by their contents.

### ISSUE THREAD

**Issue by Break-Off** [CleverRaven/Cataclysm-DDA#29139]
**Is your feature request related to a problem? Please describe.**  
Wearable containers (e.g. firearm holsters, waterskins, tool belts, MBR vests) are all considered clothing items. Often, a player will leave these occupied for convenience. Since the game still categorizes the items as clothing (even when they have weapons, tools or magazines inside), having a large pile of clothing can make these items hard to find, even when using advanced inventory management.

**Describe the solution you'd like**  
The game should re-categorize a wearable container item by its contents, and when empty, return to "clothing" category.

**Describe alternatives you've considered**  
Concatenate categories (i.e. clothing with guns/weapons/tools/magazines) and make it separate from both weapons/tools and clothing.

**Additional context**  
An image of the problem and a mockup of a possible solution (category concatenation). There's two guns in this large pile of clothes, but they are still categorized as clothing.

![mockup](https://user-images.githubusercontent.com/5843433/55278255-22322200-530a-11e9-96d3-105e6bea5f21.png)

![mockup2](https://user-images.githubusercontent.com/5843433/55278257-24947c00-530a-11e9-9c6d-b07cf5472539.png)

**Comment by Crunchepillar** [comment]
There are a few of these containers that don't even list the name of what is holstered in them, either. For example I recall my last character used a survivor harness to hold different weapons depending on what I was setting out to do that day and it was kind of a pain when gearing up to always check what was in it from the last use.
