### ISSUE TITLE
Allowing flags to be added through json for item drops.

### ISSUE THREAD

**Issue by zombiethoughts** [CleverRaven/Cataclysm-DDA#29149]
**Is your feature request related to a problem? Please describe.**  
I was attempting to add a flag to an item drop using json and was told it's currently not possible.

**Describe the solution you'd like**  
I would like there to be an option to add flags to item drops for the ease of implementing future IDs in harvest.json for specific types of monster drops. The example here is one I'm working on in #29142.
Adding the "filthy" flag to kevlar drops from butchering.

**Describe alternatives you've considered**  
Possibly forcing the flag filthy on any material dropped from butchering. Minus the usual refuse/bone/fat/meat.

**Additional context**  
What I would hope is possible.

      { "drop": "kevlar_plate", "type": "skin", "mass_ratio": 0.015, "flags": [ FILTHY ] }

**Comment by anothersimulacrum** [comment]
Implemented in #32013
