### ISSUE TITLE
Dive watch has no alarm function

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#29144]
Wearing a dive watch and sleeping gives no option to sleep for X hours. You just fall asleep and wake up whenever.

Please add the code from the normal wrist watch to the dive watch. Wearing both makes me feel very weird.

**Comment by nexusmrsep** [comment]
Good first PR material. Just add ALARMCLOCK flag to the item in JSON file.

**Comment by Throwaway-name** [comment]
@nexusmrsep that doesn't work with the dive watch.

**Comment by nexusmrsep** [comment]
Fixed by #29159
