### ISSUE TITLE
There's already a monster at [X,Y,Z] 

### ISSUE THREAD

**Issue by Alapaga** [CleverRaven/Cataclysm-DDA#29146]
**Describe the bug**  
Pretty straight forwards, this message pops up every time I try to go towards the locations listed on the debug file. I know this has already been reported in the past and some reports of it being fixed have been produced, but it seems to be happening again. 

**To Reproduce**  
1. I try to go past the abandonned shops to the south of the city
2. The message pops up, sometimes multiple times
3. I press space and resume playing as if nothing happened

**Screenshots**  
This is an animated screenshot of the whole problem
https://clips.twitch.tv/IronicLittleSnailDxAbomb

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1191-gf5f1b9a
 - Graphics version: Tiles
 - Mods loaded: "dda",
  "no_npc_food",
  "filthy_morale",
  "aftershock",
  "generic_guns",
  "modular_turrets",
  "Salvaged_Robots",
  "alt_map_key",
  "crazy_cataclysm",
  "no_religious_Texts",
  "No_Fungi",
  "more_classes_scenarios",
  "StatsThroughSkills"

**Additional context**  
I suspect Mr Skeltal to be responsible of the issue, seeing that it is the only sumonner mob in the area
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3025985/debug.log)
[stream save6.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3025986/stream.save6.zip)

**Comment by drayath** [comment]
Seen similar issues with chickens (spawning from chicks?) in apartment towers, small blobs in lab and something from random portal in lab for various versions back to 0.D release.

**Comment by ianestrachan** [comment]
This has been around _forever_ (I recall seeing it in the original pre-DDA Cataclysm) and I feel like it shouldn't be something that pops up a debug error into the player's face, given that "trying to add a monster where there already is one" seems like something that could easily happen in normal play.

It should probably try to look for nearby empty spaces within a radius, and then give up quietly, because this can happen with roaming hordes, densely-populated structures, or really any time the game ever wants to spawn a monster.

**Comment by neitsa** [comment]
I guess that just commenting / removing / silently logging this [line here](https://github.com/CleverRaven/Cataclysm-DDA/blob/5225ecb150de734debe0a90deb47000a442b424e/src/creature_tracker.cpp#L70) should be enough?

**Comment by kevingranade** [comment]
Any time this happens it's a bug and it needs to be tracked down.
The message is a symptom, there have been a half dozen causes over the years.

**Comment by drayath** [comment]
This is the only log item
`
Game Version: cataclysmdda-0.D-8666 (Windows 10-64 Tiles)
Notes: Wander Hordes are switched on.
-----------------------------------------
14:57:11.874 : Starting log.
14:57:11.875 INFO : Cataclysm DDA version 0.D-732-g54c3388
14:57:11.937 INFO : Number of render drivers on your system: 4
14:57:11.937 INFO : Render driver: 0/direct3d
14:57:11.937 INFO : Render driver: 1/direct3d11
14:57:11.937 INFO : Render driver: 2/opengl
14:57:11.937 INFO : Render driver: 3/software
14:57:11.955 INFO : Language is set to: 'en'
14:57:14.471 INFO : SDL version used during compile is 2.0.5
14:57:14.471 INFO : SDL version used during linking and in runtime is 2.0.5
14:57:14.693 INFO : Active renderer: 0/direct3d
14:57:15.498 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
14:57:16.082 WARNING : opendir [./mods/] failed with "No such file or directory".
15:00:50.433 WARNING : opendir [./save/Sylvan Springs/mods] failed with "No such file or directory".
15:01:06.805 INFO : Loaded tileset: MSX++DEAD_PEOPLE
16:01:23.632 ERROR : (error message will follow backtrace)
	(@0x4ed02c[cataclysm-tiles.exe+0xed02c]), 
	(@0x4ed38e[cataclysm-tiles.exe+0xed38e]), 
	(@0x4edbfe[cataclysm-tiles.exe+0xedbfe]), 
	(IMG_LoadWEBP_RW+0x116912@0xd3cd12[cataclysm-tiles.exe+0x93cd12]), 
	(@0x4e935f[cataclysm-tiles.exe+0xe935f]), 
	(@0x56660f[cataclysm-tiles.exe+0x16660f]), 
	(@0x56663f[cataclysm-tiles.exe+0x16663f]), 
	(@0x906747[cataclysm-tiles.exe+0x506747]), 
	(@0x71aa2c[cataclysm-tiles.exe+0x31aa2c]), 
	(@0x71aee2[cataclysm-tiles.exe+0x31aee2]), 
	(@0x594ba7[cataclysm-tiles.exe+0x194ba7]), 
	(@0x5ac535[cataclysm-tiles.exe+0x1ac535]), 
	(@0x5c7c6a[cataclysm-tiles.exe+0x1c7c6a]), 
	(@0x59f0de[cataclysm-tiles.exe+0x19f0de]), 
	(IMG_LoadWEBP_RW+0x48df6e@0x10b436e[cataclysm-tiles.exe+0xcb436e]), 
	(@0x4013e2[cataclysm-tiles.exe+0x13e2]), 
	(BaseThreadInitThunk+0x24@0x77288494[KERNEL32.DLL+0x18494]), 
	(RtlAreBitsSet+0x88@0x777e41c8[ntdll.dll+0x641c8]), 
	(RtlAreBitsSet+0x58@0x777e4198[ntdll.dll+0x64198]), 
Backtrace emission took 0 seconds.
src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 75,93,0
16:01:28.092 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 75,93,0
16:01:29.327 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 93,85,0
16:01:29.991 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 93,85,0
16:01:30.456 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 93,85,0
16:01:34.728 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 93,85,0
16:01:35.120 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 93,85,0
16:01:35.335 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 93,85,0
16:01:35.519 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 93,85,0
16:01:35.792 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 123,45,0
16:01:36.031 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 123,45,0
16:01:36.550 ERROR GAME : src/game.cpp:4512: game:monmove: brown chick can't move to its location! (94:95:0), concrete wall
16:01:53.530 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 129,12,0
16:01:58.717 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 129,12,0
16:01:59.943 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 129,12,0
16:02:00.576 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 129,12,0
16:02:01.079 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 129,12,0
16:47:22.764 ERROR : (error message will follow backtrace)
	(@0x4ed02c[cataclysm-tiles.exe+0xed02c]), 
	(@0x4ed38e[cataclysm-tiles.exe+0xed38e]), 
	(@0x4edbfe[cataclysm-tiles.exe+0xedbfe]), 
	(IMG_LoadWEBP_RW+0x116912@0xd3cd12[cataclysm-tiles.exe+0x93cd12]), 
	(@0x4e935f[cataclysm-tiles.exe+0xe935f]), 
	(@0x56660f[cataclysm-tiles.exe+0x16660f]), 
	(@0x56663f[cataclysm-tiles.exe+0x16663f]), 
	(@0x906747[cataclysm-tiles.exe+0x506747]), 
	(@0x71aa2c[cataclysm-tiles.exe+0x31aa2c]), 
	(@0x71aee2[cataclysm-tiles.exe+0x31aee2]), 
	(@0x594ba7[cataclysm-tiles.exe+0x194ba7]), 
	(@0x5ac535[cataclysm-tiles.exe+0x1ac535]), 
	(@0x5c7c6a[cataclysm-tiles.exe+0x1c7c6a]), 
	(@0x59f0de[cataclysm-tiles.exe+0x19f0de]), 
	(IMG_LoadWEBP_RW+0x48df6e@0x10b436e[cataclysm-tiles.exe+0xcb436e]), 
	(@0x4013e2[cataclysm-tiles.exe+0x13e2]), 
	(BaseThreadInitThunk+0x24@0x77288494[KERNEL32.DLL+0x18494]), 
	(RtlAreBitsSet+0x88@0x777e41c8[ntdll.dll+0x641c8]), 
	(RtlAreBitsSet+0x58@0x777e4198[ntdll.dll+0x64198]), 
Backtrace emission took 0 seconds.
src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 129,25,2
16:47:26.102 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 129,25,2
16:47:27.280 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 129,24,2
16:47:27.713 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 129,25,2
16:47:28.153 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 129,24,2
16:47:28.489 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 129,25,2
16:47:28.728 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 129,25,2
17:20:41.310 ERROR : (error message will follow backtrace)
	(@0x4ed02c[cataclysm-tiles.exe+0xed02c]), 
	(@0x4ed38e[cataclysm-tiles.exe+0xed38e]), 
	(@0x4edbfe[cataclysm-tiles.exe+0xedbfe]), 
	(IMG_LoadWEBP_RW+0x116912@0xd3cd12[cataclysm-tiles.exe+0x93cd12]), 
	(@0x4e935f[cataclysm-tiles.exe+0xe935f]), 
	(@0x56660f[cataclysm-tiles.exe+0x16660f]), 
	(@0x56663f[cataclysm-tiles.exe+0x16663f]), 
	(@0x906747[cataclysm-tiles.exe+0x506747]), 
	(@0x71aa2c[cataclysm-tiles.exe+0x31aa2c]), 
	(@0x71aee2[cataclysm-tiles.exe+0x31aee2]), 
	(@0x594ba7[cataclysm-tiles.exe+0x194ba7]), 
	(@0x5ac535[cataclysm-tiles.exe+0x1ac535]), 
	(@0x5c7c6a[cataclysm-tiles.exe+0x1c7c6a]), 
	(@0x59f0de[cataclysm-tiles.exe+0x19f0de]), 
	(IMG_LoadWEBP_RW+0x48df6e@0x10b436e[cataclysm-tiles.exe+0xcb436e]), 
	(@0x4013e2[cataclysm-tiles.exe+0x13e2]), 
	(BaseThreadInitThunk+0x24@0x77288494[KERNEL32.DLL+0x18494]), 
	(RtlAreBitsSet+0x88@0x777e41c8[ntdll.dll+0x641c8]), 
	(RtlAreBitsSet+0x58@0x777e4198[ntdll.dll+0x64198]), 
Backtrace emission took 0 seconds.
src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 0,129,0
17:20:44.399 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 0,129,0
17:20:45.104 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 0,129,0
17:20:45.617 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 0,129,0
17:20:46.561 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 0,129,0
17:37:30.108 ERROR : (error message will follow backtrace)
	(@0x4ed02c[cataclysm-tiles.exe+0xed02c]), 
	(@0x4ed38e[cataclysm-tiles.exe+0xed38e]), 
	(@0x4edbfe[cataclysm-tiles.exe+0xedbfe]), 
	(IMG_LoadWEBP_RW+0x116912@0xd3cd12[cataclysm-tiles.exe+0x93cd12]), 
	(@0x4e935f[cataclysm-tiles.exe+0xe935f]), 
	(@0x56660f[cataclysm-tiles.exe+0x16660f]), 
	(@0x56663f[cataclysm-tiles.exe+0x16663f]), 
	(@0x906747[cataclysm-tiles.exe+0x506747]), 
	(@0x71aa2c[cataclysm-tiles.exe+0x31aa2c]), 
	(@0x71aee2[cataclysm-tiles.exe+0x31aee2]), 
	(@0x594ba7[cataclysm-tiles.exe+0x194ba7]), 
	(@0x5ac535[cataclysm-tiles.exe+0x1ac535]), 
	(@0x5c7c6a[cataclysm-tiles.exe+0x1c7c6a]), 
	(@0x59f0de[cataclysm-tiles.exe+0x19f0de]), 
	(IMG_LoadWEBP_RW+0x48df6e@0x10b436e[cataclysm-tiles.exe+0xcb436e]), 
	(@0x4013e2[cataclysm-tiles.exe+0x13e2]), 
	(BaseThreadInitThunk+0x24@0x77288494[KERNEL32.DLL+0x18494]), 
	(RtlAreBitsSet+0x88@0x777e41c8[ntdll.dll+0x641c8]), 
	(RtlAreBitsSet+0x58@0x777e4198[ntdll.dll+0x64198]), 
Backtrace emission took 0 seconds.
src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 81,71,0
17:37:30.108 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 81,71,0
17:37:30.108 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 81,71,0
17:37:30.108 ERROR : src/creature_tracker.cpp:71 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 81,71,0
17:55:07.592 : Log shutdown.
-----------------------------------------
`

**Comment by drayath** [comment]
Blob one looks like a different issue:

Game Version: cataclysmdda-0.D-8666 (Windows 10-64 Tiles)
`
16:47:08.409 ERROR GAME : (error message will follow backtrace)
	(@0x4ed26c[cataclysm-tiles.exe+0xed26c]), 
	(@0x4ed5ce[cataclysm-tiles.exe+0xed5ce]), 
	(@0x5937c2[cataclysm-tiles.exe+0x1937c2]), 
	(@0x5a0466[cataclysm-tiles.exe+0x1a0466]), 
	(IMG_LoadWEBP_RW+0x48edce@0x10b700e[cataclysm-tiles.exe+0xcb700e]), 
	(@0x4013e2[cataclysm-tiles.exe+0x13e2]), 
	(BaseThreadInitThunk+0x24@0x77288494[KERNEL32.DLL+0x18494]), 
	(RtlAreBitsSet+0x88@0x777e41c8[ntdll.dll+0x641c8]), 
	(RtlAreBitsSet+0x58@0x777e4198[ntdll.dll+0x64198]), 
Backtrace emission took 0 seconds.
src/game.cpp:4522: game:monmove: small blob can't move to its location! (59:87:-4), concrete wall
`

**Comment by neitsa** [comment]
@drayath : You can put text into three backticks like this: 

` ```
bla 
bla
``` `

And it renders like this:

```
bla bla
```
