### ISSUE TITLE
Bionics don't interact correctly with vitamin consumption/usage.

### ISSUE THREAD

**Issue by drayath** [CleverRaven/Cataclysm-DDA#29147]
**Describe the bug**  
When you have the bionic:
 - 'Expanded Digestive System' you gain an extra 50% calories from food but do not appear to gain +50% to vitamin intake.
 - 'Recycler Bionic' calories are consumed at half the normal rate, but still consume vitamins as normal.

In addition mutations that change metabolic rate don't appear (from a quick code/json browse) to change vitamin usage rates.

Combined you need (can only) eat 1/3 of the food but you still somehow have to consume full amount of vitamins.

**Expected behavior**  
Mutations/bionics that impact food intake should also affect vitamin intake (and item description vitamin values)

Mutations/bionics that impact metabolism rate (nicely like mutations or hard coded like bionics) should impact vitamin usage rates.

Game Version: cataclysmdda-0.D-8676

**Additional context**  
Bionic: Expanded Digestive System
Description: You have been outfitted with three synthetic stomachs and industrial-grade intestines.  Not only can you extract much more nutrition from food, but you are highly resistant to foodborne illness, and can sometimes eat rotten food.

**Comment by drayath** [comment]
Another missing vitamin interaction: If you vomit hunger/thirst are raised (i.e. unprocessed stomach contents are ejected and thus can;t be digested for nutrition). Should also lower vitamin levels for stomach contents (which would either need a quick hack or to track stomach vitamin contents as is done for nutrition/water)

**Comment by kevingranade** [comment]
Invalid expected behavior, this is working as intended.  I'm happy to hear whatever rationale you have for why they should do what you want, but you haven't provided one.

**Comment by KorGgenT** [comment]
> Another missing vitamin interaction: If you vomit hunger/thirst are raised (i.e. unprocessed stomach contents are ejected and thus can;t be digested for nutrition). Should also lower vitamin levels for stomach contents (which would either need a quick hack or to track stomach vitamin contents as is done for nutrition/water)

this is actually something that'll happen soon(TM)
once i finish the stomach contents stuff.
