### ISSUE TITLE
Make cooking prioritize non-rotten materials

### ISSUE THREAD

**Issue by adamkad1** [CleverRaven/Cataclysm-DDA#29153]
Title. Someone suggested this in https://github.com/CleverRaven/Cataclysm-DDA/issues/9879
and it really annoys me how the game allways seem to use rotten material before fresh, it should either prioritize fresh or give you a choice which material you want to use

**Comment by Tharn** [comment]
A choice would be ideal, similar to the 'E' screen that shows freshness. Sometimes you want to craft with aging food before it rots completely, sometimes you want the freshest stuff available.
