### ISSUE TITLE
Tazer does not charge from bionic ups.

### ISSUE THREAD

**Issue by drayath** [CleverRaven/Cataclysm-DDA#29154]
**Describe the bug**  
I am outfitted with a bionic ups (switched on and with power)
Have a basic tazer which has a description that it can charge from ups.

Item does not charge when in inventory.
Item does not charge when in wielded.
Item **DOES** charge if placed in a vehicle ups charger.

Checked that bionic charger is working for others items (Firearm Repair Kit+ups mod)

 - Game Version: cataclysmdda-0.D-8676 (Windows 10-64 Tiles)

**Comment by adamkad1** [comment]
have you tried just firing it?

**Comment by Night-Pryanik** [comment]
I don't know if it's a bug. Description explicitly states that it will charge in UPS-compatible recharge station, there's nothing about it can charge from any other UPS.

**Comment by drayath** [comment]
Closing this; Looks like reading comprehension error.

Text says:  'UPS Compatible Charging Station' not 'Universal Power Supply' and i was not aware that items could have that variant.

Nb/ Adding ups-mod to tazer DOES allows ups charging as i wanted.
