### ISSUE TITLE
New Surface Lab: Guardrails turn into deep water tiles

### ISSUE THREAD

**Issue by Break-Off** [CleverRaven/Cataclysm-DDA#29155]
**Describe the bug**  
The recently introduced surface lab has a parking lot entrance with "guard rail" tiles imitating a parking barrier gate. When smashed, they leave a "bridge pavement" tile, probably because guard rails were introduced with bridges. When the guard rails are smashed hard enough (i.e. with a vehicle) the "bridge pavement" tile is destroyed too, leaving a deep water tile (as if the vehicle ran off a bridge).

**To Reproduce**  
1. Find a research facility.
2. Smash parking gate hard enough.
3. Deep water tiles are left.

**Expected behavior**  
Water not appearing out of destroyed guardrails.

**Screenshots**  
![image](https://user-images.githubusercontent.com/5843433/55283526-9cdc5b00-5365-11e9-9c0c-5e89942ea552.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1192-g29d6ea3
 - Graphics version: Tiles
 - Mods loaded: 
```
[
  "dda",
  "no_npc_food",
  "filthy_morale",
  "ew_pack",
  "alt_map_key",
  "mutant_npcs",
  "npc_traits",
  "more_locations",
  "deoxymod",
  "blazemod",
  "Tanks",
  "no_olg_guns",
  "no_flaming_weapons",
  "more_classes_scenarios",
  "safeautodoc",
  "no_pipe_guns",
  "growable-pots",
  "modular_turrets",
  "Salvaged_Robots",
  "boats",
  "manualbionicinstall"
]
```

Referencing https://github.com/CleverRaven/Cataclysm-DDA/pull/28722 and https://github.com/CleverRaven/Cataclysm-DDA/pull/29188

**Comment by l29ah** [comment]
Also the loot is just too good.

**Comment by l29ah** [comment]
Those tiles are also present on the second floor.
