### ISSUE TITLE
Game have two sound folders, one of them seems to be unused

### ISSUE THREAD

**Issue by Warlander** [CleverRaven/Cataclysm-DDA#29164]
**Describe the bug**  
Game have two sound folders, one of them seems to be unused. These folders are:
<root>/sound (seems to be unused)
<root>/data/sound (used for soundpacks)

**To Reproduce**  
Launch the game and <root>/sound folder will be automatically created.

**Expected behavior**  
No empty folder is created. My assumption is that it might be some leftover code which checks for soundpacks in wrong location, but is never used elsewhere.

**Versions and configuration:**
 - OS: Windows 7
 - Game Version: 0.D-1191-gf5f1b9a
 - Graphics version: both
 - Mods loaded: not relevant

**Comment by OrenAudeles** [comment]
I think (unconfirmed) that `./sound` is intended to be used for user-added soundpacks while `./data/sound` is intended to be used for mainlined soundpacks (if they ever exist beyond the basic default sounds).
Similarly for mods, there are `./data/mods` and `./mods` folders that serve the same purpose of separating user added data from the game's default data.

If someone else can chime in to confirm or refute my claim that'd be helpful

**Comment by Warlander** [comment]
I just checked and `./sound` folder is also checked for soundpacks. It is a bit confusing through that there are two separate sound folders (and named the same) while there is just one mods folder even through two locations are checked in this case as well.

My suggestion - maybe make a clear distinction that './data/sound' and './data/mods' are meant for mainlined mods/soundpacks, while './sound' and './mods' are better place for user-added mods/soundpacks?

**Comment by OrenAudeles** [comment]
might make sense to have a `user_data` folder for application-level user stuff, and move `./mods` and `./sounds` into `./<user_data>/mods` and `./<user_data>/sounds`. I think that would handle the ambiguity case. Needs a good name though, not fond of `user_data` as the folder name

**Comment by Crunchepillar** [comment]
I'm a huge fan of the user_data suggestion. Things being more organized makes me feel warm and fuzzy inside 😸

**Comment by Warlander** [comment]
Some kind of user_data folder for mods/tilesets/soundpacks would also be helpful for launcher - less hassle of dealing with mainlined stuff. :)

**Comment by ZhilkinSerg** [comment]
That is not a bug - game looks for mods and soundpacks in several paths.

**Comment by esotericist** [comment]
For instance, on Mac, Cataclysm correctly checks `~/Library/Application support/Cataclysm/sound` for soundpacks (and that's also the tree where save files and local config live).
