### ISSUE TITLE
Attacks from under ceiling with 3D FOV on.

### ISSUE THREAD

**Issue by curstwist** [CleverRaven/Cataclysm-DDA#29175]
**Describe the bug**  
When on a roof, zombies from inside the building can use special attacks on you, most notably shockers.

**To Reproduce**  
1. Turn on 3D FOV
2. Get a nice hoard and lure it into a json roofed building.
3. Get on roof, enjoy endless perfectly targeted shocks.

**Expected behavior**  
No attacks through the roof from inside.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Win10
 - Game Version: 0.D:1214
 - Graphics version: TILES
 - Mods loaded: none 

**Additional context**  
On roof getting shocked
![shocker below](https://user-images.githubusercontent.com/39442864/55295324-cafb8280-53d9-11e9-87cd-0a7507197257.PNG)
shocker below & inside
![shocker](https://user-images.githubusercontent.com/39442864/55295325-cafb8280-53d9-11e9-9e6b-249d86f54da2.PNG)
gifs are fun
![shocker](https://user-images.githubusercontent.com/39442864/55295337-f2524f80-53d9-11e9-9a87-a02fb5d7e96f.gif)

**Comment by kevingranade** [comment]
Here's the execution stack for shockstorm
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/monattack.cpp#L624
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/monster.cpp#L842
https://github.com/CleverRaven/Cataclysm-DDA/blob/469d2498f7f469c180368f5a84e9419bbc4099fb/src/creature.cpp#L165

There are a couple of suspicious things happening here, all of them revolving around creature::sees( creature ).
If the shocker is directly beneath the player, it executes ``g->m.valid_move( pos(), critter.pos(), false, true )``, which is not used and tested a ton in a vertical context, so I wouldn't be surprised if it has a bug or two.
Later the final check is the symmetric ``g->m.get_cache_ref( pos().z ).seen_cache[pos().x][pos().y] > LIGHT_TRANSPARENCY_SOLID;`` check, which I'm not 100% convinced is doing the right thing.

Next is either stepping through the code to find out where this is happening, or maybe creating a test to tease it out.

**Comment by kevingranade** [comment]
The problem is in 3D shadowcasting, there is some scenario where it allows the player to see the shocker and vice versa.  You can see this because the shocker will intermittently appear on the threat compass as you wander around.

**Comment by kevingranade** [comment]
It turns out it is not the shadowcasting algorithm itself, but rather something related to map shifts.  If you identify a submap edge (roughly the center of a roof, but not always) and then step over the border, the shocker will see you almost every time, but if you walk around without crossing a border, I've yet to trigger it.
