### ISSUE TITLE
编译结束后出现的报错信息

### ISSUE THREAD

**Issue by neoiso** [CleverRaven/Cataclysm-DDA#29173]
lang/compile_mo.sh zh_CN
lang/compile_mo.sh: 28: lang/compile_mo.sh: msgfmt: not found
Makefile:778: recipe for target 'localization' failed
make: *** [localization] Error 127
make: *** Waiting for unfinished jobs....

**Comment by ZhilkinSerg** [comment]
Apparently `msgfmt` application is missing on your system. It is part of [gettext](https://www.gnu.org/software/gettext/), so you need this installed.

**Comment by neoiso** [comment]
谢谢！
