### ISSUE TITLE
While aiming, the character sprite is positioned incorrectly

### ISSUE THREAD

**Issue by rumly111** [CleverRaven/Cataclysm-DDA#29183]
**Describe the bug**  
When I fire with a gun, the character tile is centered relatively to the whole screen, but it should be positioned in the center of the "game" part of the screen.

**Screenshots**  
It's hard to explain with words, better demonstrate with a screenshot:
![cdda-aiming](https://user-images.githubusercontent.com/8035743/55297165-0c1c8280-542c-11e9-9c42-cc111432c535.png)

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 18.04
 - Game Version: 0.D-1194-gb45c3cb
 - Graphics version: Tiles
 
**Additional context**  
Not sure if it matters, in settings I have "move target to screen edge", so when I switch between monsters/items on the floor that are further away, they appear on the screen edge.

**Comment by l29ah** [comment]
Still an issue in the terminal interface.

**Comment by l29ah** [comment]
![](https://pstbin.ru/f/75721/)
