### ISSUE TITLE
Sidebar config: element labels are not correct when moving them around

### ISSUE THREAD

**Issue by rumly111** [CleverRaven/Cataclysm-DDA#29180]
**Describe the bug**  
I open sidebar config with } and try to move elements in the left side up/down. I can see duplicates and missing elements.

**To Reproduce**  
1. Open sidebar config with }
2. Select an element in the left panel, then press Enter
3. Start moving it up/down

**Screenshots**  
As you can see, at one point there is a duplicate "Compass" element, and at another, the "Log" element is missing.
![cdda-sidebar](https://user-images.githubusercontent.com/8035743/55296940-096c5e00-5429-11e9-8c58-511f64aff8e0.gif)

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 18.04
 - Game Version: 0.D-1194-gb45c3cb
 - Graphics version: Tiles

**Comment by Night-Pryanik** [comment]
I guess yellow "Compass" is still visible for convenience reasons, to see where it was located before its selection.

**Comment by rumly111** [comment]
> I guess yellow "Compass" is still visible for convenience reasons, to see where it was located before its selection.

It's not an expected behavior IMO. It would be better to follow WYSIWYG principle.
