### ISSUE TITLE
'Really step into pit?' dialog when moving inside vehicle.

### ISSUE THREAD

**Issue by drayath** [CleverRaven/Cataclysm-DDA#29200]
**Describe the bug**  
If you have a vehicle parked over a pit, when you walk around in the vehicle you get a warning dialog: Really step into pit? Yes/No

Game Version: cataclysmdda-0.D-8676 (Windows 10-64 Tiles)

**To Reproduce**  
Place vehicle (with full floor) over pit.
Walk into the vehicle tile over the pit.
Get move confirmation dialog.
(Say Yes, and move within vehicle without falling in pit)

**Expected behavior**  
Don't give spurious warning.

**Additional context**  
This if for my garage that has plank covered pits for the wheels to drive over, but several uncovered pits under the middle of the vehicle.

Untested if this also happened with other move warnings (e.g. traps on ground under (non-wheel tile) of vehicle)

**Comment by davidpwbrown** [comment]
Huh, trying to step on a pit to test this, with no vehicle, actually crashed.....
