### ISSUE TITLE
Advanced organ recipes need review

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#29208]
**Describe the bug**  
They take too long, consume too much heat, and lack batching
related to #28205
NEED: may need someone to run scans on the jsons to try and get a (mostly complete) list of recipes that may fall under this.  I'm guessing they're all likely to require 100 heat

**To Reproduce**  
give yourself max cooking
compare the following recipes (mentioned by @Crunchepillar in #28991 )
    cooked liver (benchmark)
    canned liver
    foie gras (consider removing or replacing with more believable variant)
    grilled sweetbread
    deviled kidney
    (and probably others)

**Expected behavior**  
food cooking should be relatively on par, with increases in time/heat/skill matching increases in stats

**Screenshots**  
ask if needed

**Versions and configuration(please complete the following information):**
 - OS: ask if needed
 - Game Version: ask if needed
 - Graphics version: ask if needed
 - Mods loaded: ask if needed

**Additional context**  
This may be a case of diversity creep.
It's fine (and even good) to have interesting variants for flavor, but they should be templated from base versions so they inherit updates and we don't have to hunt them down each time (see Cooked Liver <- Cooked Brains in offal_dishes.json for an example of this in action)

**Comment by I-am-Erk** [comment]
Could you offer some details on what you think is off?

**Comment by Xpyder** [comment]
• too much heat (100 vs 7)
• too much time

both of which should be fixed by fixing the following
• should be built off baseline recipe (so it inherits balance changes)

**Comment by Xpyder** [comment]
for preliminary review, here's a list of all recipes that require 50 or more surface heat

apple_canned
broth
broth_bone
broth_human
can_beans
can_tomato
canned_liver
con_milk
denat_alcohol
deviled_kidney
fish_canned
fish_pickled
foie_gras
fried_tripe
grilled_sweetbread
human_canned
human_pickled
kompot
leverpostej
liver_onion
meat_canned
meat_pickled
offal_canned
sauce_red
soup_fish
soup_human
soup_meat
soup_mushroom
soup_veggy
soup_woods
V8
veggy_canned
veggy_pickled

**Comment by Xpyder** [comment]
Here are the variant recipes that probably need to be fixed

deviled_kidney
foie_gras
fried_tripe
grilled_sweetbread
leverpostej
liver_onion
