### ISSUE TITLE
Analyze zombie blood "unable to find and assign mission target hospital_2"

### ISSUE THREAD

**Issue by SkuliAdams** [CleverRaven/Cataclysm-DDA#29217]
**Describe the bug**  
When I accept a mission to analyze zombie blood from a doctor at the refugee center, an error appears, telling me that the game was unable to find the mission target. I am able to continue with the game after this error, but the quest does not point me in the direction of a specific hospital on the map. I have not tried to find another location to complete the quest.

**To Reproduce**  
Download and use save in most recent experimental, then go and speak with the doctor in the refugee center. Accept the quest.

**Expected behavior**  
The game should find an appropriate hospital.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-1282-g0631476
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Disable NPC Needs, Filthy Clothing

**Additional context**  
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3032251/debug.log)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3032264/save.zip)

**Comment by golankra123** [comment]
Debug file has nothing useful ^^.

Probably it's something to do with the ```missions.json``` file.

Or world genration or the hospital chunk

**Comment by davidpwbrown** [comment]
same as #28950
