### ISSUE TITLE
Crash at Startup

### ISSUE THREAD

**Issue by WilsonAutomation** [CleverRaven/Cataclysm-DDA#29229]
**Describe the bug**  
Just downloaded the game on a new Windows 10 laptop.  Double-clicky the icon, and the game window opens to white, and I get a error pop-up.

**Crash Log**  
CRASH LOG FILE: config/crash.log
VERSION: 0.D-1319-gdca9d26
TYPE: Signal
MESSAGE: SIGILL: Illegal instruction
STACK TRACE:
    @0x5574D5[cataclysm-tiles.exe+0x1574D5]
    @0x558082[cataclysm-tiles.exe+0x158082]
    SMPEG_error+0x4B0FC@0xE2EB98[cataclysm-tiles.exe+0xA2EB98]
    _C_specific_handler+0x98@0x7FF918047C58[msvcrt.dll+0x27C58]
    _chkstk+0x11D@0x7FF91A7BF7DD[ntdll.dll+0x9F7DD]
    RtlWalkFrameChain+0x13F6@0x7FF91A72D856[ntdll.dll+0xD856]
    KiUserExceptionDispatcher+0x2E@0x7FF91A7BE70E[ntdll.dll+0x9E70E]
    @0x7FF8C5EDE164
    @0xE7F7E98

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 on very low-end laptop (think <$200)
 - Game Version: 0.D-1319-gdca9d26
 - Graphics version: Tiles
 - Mods loaded: None

**Additional context**  
It's probably just a prerequisite program that I need (like how some things need DirectX), but I don't know which one?

**Comment by WilsonAutomation** [comment]
There is also a debug file next to the crash file that might be useful:

-----------------------------------------
14:05:17.171 : Starting log.
14:05:17.176 INFO : Cataclysm DDA version 0.D-1319-gdca9d26
14:05:17.197 WARNING : opendir [./sound/] failed with "No such file or directory".
14:05:17.230 INFO : Number of render drivers on your system: 4
14:05:17.230 INFO : Render driver: 0/direct3d
14:05:17.230 INFO : Render driver: 1/direct3d11
14:05:17.231 INFO : Render driver: 2/opengl
14:05:17.231 INFO : Render driver: 3/software
14:05:17.232 INFO : Language is set to: 'en'
14:05:18.141 INFO : SDL version used during compile is 2.0.5
14:05:18.141 INFO : SDL version used during linking and in runtime is 2.0.5

**Comment by WilsonAutomation** [comment]
Okay, making progress.  Downloaded the game as console, and it runs just fine, so we have limited it to the tiles version.  Wonder what the prereqs are for tiles.

**Comment by golankra123** [comment]
As far as I understand ```ntdll.dll``` the system DLL the debug file is refrencing.

Is a file which deals with exporting "Windows Native API", 
It might mean that it won't work with even other ASCII based games (try to test it).

If it's indeed the case - try to do a system repair.

**It's my assumption* *

**Comment by WilsonAutomation** [comment]
I just loaded up Cogmind (the only other top down ASCII/tile based game I have) and it works fine.  I'll do some searching on the ntdll.dll and see what I can find.

**Comment by golankra123** [comment]
Maybe directX causing the crash(?)

I'm not sure but you could try to force the game CDDA to render at OpenGL.

**Comment by WilsonAutomation** [comment]
So, yea DirectX was kinda close.  I tried to run a dxdiag and it kept crashing.  Searched for the answer, and it seemed all I needed was an update to my graphics driver for my ADM Radeon R5.  Updated that driver and I'm off to the races.

Appreciate the help.  Not sure why none of my other games had problems?  Oh well, just happy it works again.
