### ISSUE TITLE
allow modifier keys ( 'shift' 'alt' 'ctrl') to be used in keybindings. Ex. Shift+Alt+N as a keybinding for whatever you want.

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#29227]
I will reference a few issues that have requested something similar.
#20447
#21412
#24325
#26550

All but the last issue are closed for various reasons. I was hoping we could find a few key modifiers that do work in both SDL and curses format and allow them to be used, and then in the help files and "view help" menu have those combinations identified for quick reference.

CDDA has a lot of keybindings and a lot of people that play different ways. Adding in a few more key modifier combinations would certainly help me and I assume others in coming up with the perfect keybinding we enjoy.

**Comment by Night-Pryanik** [comment]
The last issue you mentioned isn't closed. Why opening a duplicate?

**Comment by Phenomphear** [comment]
I was trying to consolidate. Sorry. If want just close this and put it in his
