### ISSUE TITLE
More NPC Death Effects (for player)

### ISSUE THREAD

**Issue by adamdeno** [CleverRaven/Cataclysm-DDA#29220]
**Is your feature request related to a problem? Please describe.**  
Yes. When a follower dies the player shows no reaction to them dying.

**Describe the solution you'd like**  
A Huge moral drop depending on friendship and days survived with NPC if it dies

**Describe alternatives you've considered**  
For example a a new guy that want to follow you will cause a small moral drop , You dont know him and dont care about him BUT seeing someone with you dying is just sad

a NPC with completed mission (Being very friendly) and it dies it would cause a huge moral drop to player and it stacks if alot days passed with NPC Of course just like real life you will be sad to the point of depression from losing a close one , You still will move on after a long time depending on time spent with the npc.

ISNT AFFECTED WITH PSYCOPATH TRAIT.

**Additional context**  
Its just an idea , Supported or no Its just for the proplem of just letting NPC dies so player keep aiding his closest ones more and friendly ones. you dont want anyone in your group killed...

**Comment by Fris0uman** [comment]
How do we measure friendship of NPC ?

**Comment by davidpwbrown** [comment]
Currently it's very easy for NPCs to die, but they are slowly getting better at staying alive.
Penalising the player hugely for an NPC death before they are good at staying alive seems premature.

**Comment by adamdeno** [comment]
i get what you are saying. noone is ready for the cataclysm and every can die no matter what. of course the longer they survive the longer they dont die

**Comment by Wokko1** [comment]
Sorry, but it's not an idea, it's just a random thought to make gameplay more frustrating. Better let the player decide do they want to mourn perished NPCs or not.
