### ISSUE TITLE
Color Code Zones for better identification 

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#29226]
![image](https://user-images.githubusercontent.com/28910998/55426275-3e67d600-5539-11e9-856a-c53dd9edebf7.png)
We should add a better way to identify currently placed zones, I suggest color, so it is easier to see where the zone is. I struggle placing zones in ASCII due to not being able to remember exactly where a zone starts and where it ends.

The above screenshot shows this with 1 tile zones placed just below the white "%" symbol.

This is especially difficult and apparent when placing a new zone.

![image](https://user-images.githubusercontent.com/28910998/55426494-cb129400-5539-11e9-87bf-795ffbfac013.png)

I can not tell where my previous zones are. I remember where a few are, but, I can't remember them all.

**Comment by mlangsdorf** [comment]
Farm zones show the plant tile or symbol.  Other zones should do something similar, though I'm not sure what symbols are appropriate for some of the more abstract zones like no NPC pickup.
