### ISSUE TITLE
Sign Language Communications for Deaf Characters

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [CleverRaven/Cataclysm-DDA#29225]
**Is your feature request related to a problem? Please describe.**  
So recently the "Deaf" trait was added to the game, which can a hindrance for those who wish to setup a faction camp or otherwise use npcs. On top of this, npcs will attempt to speak with you multiple times only to get the "you are deaf and can't speak" message. 

**Describe the solution you'd like**  
The easiest solution I can think of is adding a sign language trait you can take from the start, or a book that illustrates how to use sign language.

**Describe alternatives you've considered**  
Another possible method would be to use player and npc intelligence stats to sort of play charades in an attempt to convey meaning (or just outright use intelligence to determine if they know sign language, though that is a little janky).

**Additional context**  
an example of the trait description:
American Sign language:
You have a good grasp on how wiggle your fingers and contort your hands to convey meaning. You can talk to npcs even while "Deaf".

**Comment by Crunchepillar** [comment]
I think it makes sense that deaf characters should know sign language if they started with the deaf trait, I still have to wonder how many survivors would be able to understand it.

**Comment by SolsticeTheTechMarine** [comment]
That is why I was thinking it might be done off of intelligence or forcing npcs to read certain books.

**Comment by Zireael07** [comment]
Sign language booklets and dictionaries exist. I would give some sort of a sign language trait to Deaf player characters, and a random chance for NPCs with above-average intelligence to know it.

**Comment by KurzedMetal** [comment]
Or, they can simply communicate by writing with anyone, without the need to expect the other to know sign language.

**Comment by Zireael07** [comment]
True, but writing on paper, is impractical in the situations DDA portrays. I'd like you to communicate on paper when there's no paper around (evac shelter) and/or you're in immediate danger (like most situations involving NPCs in the game, either due to NPCs themselves and/or Zs)

**Comment by KurzedMetal** [comment]
Well, isn't that the life of a Deaf person? They can't communicate with everyone they want.
I'd bet only a very minor portion of the world population knows Sign Language, and most of them are deaf themselves. Why would it change after the Cataclysm?

IMO, If this Sign language skill is implemented, it should be assigned only at random to NPC with a low percentage of chance, and not let the player interact unless they have paper (1 per dialog option?) and permanent marker (or implement pens?)

Another option is that the player learns to read lips (maybe partially ofuscating words depending on skill?, but that wouldn't help players that born deaf, only the ones that got deaf after learning how to speak (maybe you shouldn't have abused explosives and heavy weaponry without noise cancelling).

IMO it's way more complex than you suggest.

**Comment by golankra123** [comment]
If it gonna get implanted you could try to teach NPC's sign language with books

**Comment by Zireael07** [comment]
I agree that the chance for NPC to know sign should be very low.

**Comment by Fris0uman** [comment]
Does talking to NPC make noise in the current game ?
Because sign language could be usefull to communicate silently with NPC even if you're not deaf.

**Comment by Inglonias** [comment]
It might be a really cool challenge to teach NPCs how to use sign language after the end of the world. It would change the way a character interacts with NPCs drastically.

**Comment by DillonSimeone** [comment]
Hmm, I might poke at this. I'm deaf, so... Yeah. 

I'm thinking that instead of sign language or writing notes, the current approach to deaf players trying to talk to other NPCs could just be replaced with a different tree of dialogs that's made up of vague gestures.

<Point at NPC, wave toward yourself, point in a direction> (Attempting to convince NPC to come with you.)

<Make shooting motions, shrug, gag expression, point at NPC, shooting motion with raised eyebrow> (Attempting to request that NPC gives some training.)

<Moves thumb across throat, punches right fist into left palm at NPC> (Threatening NPC)

Just like real life, I'd simply double the DR of the speech checks you make for the same options you'd have to choose from if you're hearing. 

Critical failure? Whoops, the NPC thinks you motioned out a threat to their life and is now hostile!
