### ISSUE TITLE
Self-Aware trait improperly displaying pain

### ISSUE THREAD

**Issue by Vestrise** [CleverRaven/Cataclysm-DDA#29239]
**Describe the bug**  
When you have the Self-Aware trait displays pain with various ASCII characters such as quotes and parenthesis or nothing at all at low pain levels.

**To Reproduce**  
Create a character with the Self-Aware trait and recieve enough damage to cause pain.

**Expected behavior**  
Self-Aware should display pain levels as a numerical value unless that was changed previously.

**Screenshots**  
Sorry, on mobile :(

**Versions and configuration(please complete the following information):**
 - OS: Windows 8.1
 - Game Version: 0.D-1320-g341717d
 - Graphics version: Tiles with "Compact" sidebar setting
 - Mods loaded: DDA and nothing else

**Additional context**  
My assumption is it's displaying whatever ASCII character is associated with the pain number it should be displaying, but I'm not familiar enough with everything to investigate myself.

**Comment by KorGgenT** [comment]
fix is just awaiting merge.

**Comment by Vestrise** [comment]
Ah, okie. Sorry about that, super new to github and bug reporting. Didn't know it was already know. Thank you for your quick reply and all your hard work!

**Comment by KorGgenT** [comment]
it's all good. thank you for the initiative.

**Comment by Vestrise** [comment]
Out of curiousity, was I close in my assumption about the ASCII values or was it something else?

**Comment by KorGgenT** [comment]
probably. i didn't question how it worked before, it was as simple as doing a string_format() function on the values
