### ISSUE TITLE
Launcher not updating game

### ISSUE THREAD

**Issue by DragonFire0704** [CleverRaven/Cataclysm-DDA#29231]
**Description**
Pretty much, whenever I start the launcher, it says that it can't find any updates for the game, this happened at random, and I have no idea how to fix it. I've tried disabling firewall and launching, launching as admin, and both at the same time. I do have access to the update directory myself too.

**To Reproduce**  
Start the launcher
Look at updates
See there are none to be found

**Expected behavior**  
I expected that it would be able to update

**Screenshots**  
![Capture](https://user-images.githubusercontent.com/49149366/55436164-6c0c4980-5550-11e9-9263-8b4dd1b3ec4d.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Windows 8.1
 - Game Version: 0.D-1250-gd3067e8
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: I don't think this matters in the launcher

**Comment by ifreund** [comment]
issues with the launcher belong here: https://github.com/remyroy/CDDA-Game-Launcher/issues
