### ISSUE TITLE
After successfully recruiting NPCs, they get angry or afraid 1-2 turns later every time (AFTER becoming 'followers').

### ISSUE THREAD

**Issue by Mythiran** [CleverRaven/Cataclysm-DDA#29246]
**Describe the bug**  
This is a game which has been going on for several in-game years. I've spoken to people on discord and haven't found anyone with the same issue so it might be something bugged about my save...

I noticed a few days ago that every NPC I encountered and successfully convinced to join me would immediately turn hostile AFTER persuading them. I was also able to have a post-'join' conversation (the one with all the trade options, engagement settings, etc.)

I decided to test this out by spawning NPCs from debug, and it seems that, yes, 100% of the time that I successfully persuade NPCs, 1-2 turns later they turn hostile.

I have included a save with an NPC ready for recruitment below. He was inhaler quest... I gave him the inhaler... now he's happy - follow steps in 'to reproduce' to see effect.

Note... _the current 4 NPCs I have in my faction camp do NOT act in this way... they are still happy followers who won't randomly go hostile._

**To Reproduce**  
1. Talk to NPC.
2. "We should travel together..."
3. Persuade through any of the 100% options.
4. Do whatever you want and wait for the inevitable.
5. Two turns later he'll flee or attack and no longer be a follower.

You can also Spawn NPCs until you get one who'll join and the same thing will happen. 

![image](https://user-images.githubusercontent.com/33970439/55470521-ff697b80-5631-11e9-9be4-64c0c77db168.png)
^ My Mutations etc... not too severe. Also, I had no problem recruiting with these mutations just a few days ago (I update every day more or less so new patch my be cause...?)
![image](https://user-images.githubusercontent.com/33970439/55470588-2031d100-5632-11e9-8999-bd5a04cc4ee2.png)
^ Here we see the paradox of recruiting NPC.. having access to 'relaxing conversation' and then that very conversation being interrupted by my 'follower' going nuts and attacking me.

**Expected behavior**  
Any NPC will turn hostile or flee almost immediately after successful recruitment on the attached save. Tested 20+ times and save with the situation 'ready to go' included.

**Additional context**  
Save game here... follow instructions above. This is first time I've uploaded a save so if any problems or more things needed, post here and I'll get on it. Cheers. 

[Abc.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3038079/Abc.zip)

**Comment by davidpwbrown** [comment]
What mods?

**Comment by davidpwbrown** [comment]
also are you running the latest master? or what build?

**Comment by Mythiran** [comment]
> 
> 
> also are you running the latest master? or what build?
> Oh I see you say you update every day. could be the change I did to form opinion on dialogue start.... ill look into that.

Latest build (or at the time, you can see in the second screenshot the version number).

Mods - 
[
  "dda",
  "no_npc_food",
  "safeautodoc",
  "alt_map_key",
  "national_guard_camp",
  "deoxymod",
  "blazemod",
  "Tanks",
  "necromancy",
  "no_religious_Texts",
  "no_olg_guns",
  "No_Fungi",
  "aftershock",
  "Cata++",
  "more_locations",
  "FujiStruct",
  "More_Survival_Tools",
  "boats"
]
