### ISSUE TITLE
Action highlights are rendered offset after sidebar changes

### ISSUE THREAD

**Issue by ralreegorganon** [CleverRaven/Cataclysm-DDA#29256]
**Describe the bug**  
Certain actions (e.g. examine, open) call `choose_adjacent_highlight` which highlights the locations that can be interacted with for that action when in Curses mode. Following the sidebar changes, this highlight is offset.

**To Reproduce**  
1. Use Curses mode
2. Stand next to a door
3. Press the key to open a door (default `o`)
4. Notice that the highlight is offset

**Expected behavior**  
The highlight should be drawn in the same location as the thing being highlighted.

**Screenshots**  
_before_
![image](https://user-images.githubusercontent.com/11464/55514186-eb168600-5613-11e9-9cdf-171fb9f11c36.png)

_after, notice the brown + offset to the right_
![image](https://user-images.githubusercontent.com/11464/55514198-f49fee00-5613-11e9-9bd6-3855f25aaf55.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1371-g46cfae9ca7
 - Graphics version: Tiles (with tiles disabled in the options menu)
 - Mods loaded: default

**Comment by reed501** [comment]
I think this might be the same issue as #29186
