### ISSUE TITLE
Option to show all recipes independently of skill level

### ISSUE THREAD

**Issue by Break-Off** [CleverRaven/Cataclysm-DDA#29255]
**Is your feature request related to a problem? Please describe.**  
For new players, is a common occurrence to be on the quest to craft some new item. They have the book, they have the materials, but the recipe doesn't show up simply because they don't have the correct skill level. This is not indicated in the game whatsoever, except the recently introduced color-coding of book list recipes in brown if the player doesn't meet the level requirement. Players already accustomed to game will either memorize what skill level requires what recipe or consult the [item browser](http://cdda-trunk.chezzo.com/).

Don't get me wrong, third-party tools built by the community enhance and facilitate an already interesting game experience, but the game should have self-contained information, so that it doesn't force players to ask why they can't craft something even when requirements are apparently met.

Also, some recipes are autolearned by skill level, while others are only learned by finding an specific book AND meeting the required level.

**Describe the solution you'd like**  
Show all recipes in the crafting menu, independently of skill level, by default. They could be color-coded brown, like the book recipe list. There also would be a pop-up error when trying to craft the item that says "_You don't understand some parts of the recipe (level required: **skill: #**)_". Much like the hide function, brown recipes could be hidden with a key.

Ideally, autolearned recipes could be shown within a range of the player's current skill (as to prevent bloating and overwhelm new players with a huge crafting list). Example: If the player has survival 0, show up to level 3 recipes.

**Describe alternatives you've considered**  
If changing the crafting screen is not an option, books could carry the burden of informing players of crafting skill requirement:

1. The 'R'ead menu (which asks if you want to read once or until you gain a level) could have a third option: "List all recipes", which would be essentially an expanded book recipe list, detailing specifically which recipes are currently craftable and vice-versa.

2. Same as the first, but the detailed recipe list is invoked by 'a'ctivating the book (instead of 'R'eading it).

**Additional context**  
A common example: new players that jump right into the game without knowing that certain skills are vital (survival, tailoring, fabrication) and not spending points on them or immediately grinding them, will have problems trying to figure out [why they can't craft something they need](https://www.reddit.com/r/cataclysmdda/comments/b9195w/new_player_cant_find_craft_a_splint/).

**Comment by kevingranade** [comment]
> Show all recipes in the crafting menu, independently of skill level, by default.

It's an intentional feature that we don't overwhelm starting players with the huge number of recipes available. I could see having it default to the way it is now, and optionally un-filtering recipes that the player knows about but can't craft.

Also the player character does not know that many recipes exist.  If you want to spoil the intentionally hidden information, that's your call, but it's intentional that some recipes are unknown until discovered. We can distinguish between "known about but uncraftable" and "unknown" recipes.  E.g. if you skim a book that has a recipe, we can add that recipe to "recipes I know about" and optionally show it in the main crafting menu.

> Ideally, autolearned recipes could be shown within a range of the player's current skill

This is totally reasonable.
