### ISSUE TITLE
installing bio_ears should remove effect effect_deaf

### ISSUE THREAD

**Issue by spacenookie** [CleverRaven/Cataclysm-DDA#29261]
**Is your feature request related to a problem? Please describe.**  
this reddit thread 
[Can installing the enhanced hearing bionic give back your hearing if you're deaf?](https://www.reddit.com/r/cataclysmdda/comments/b92x24/can_installing_the_enhanced_hearing_bionic_give/)

**Describe the solution you'd like**  
in player::install_bionics():
if b_id == "bio_ears" 
  remove_effect(effect_deaf)

deafness effect removed when you install bionic ears

**Describe alternatives you've considered**  
could also cap the maximum time you can be deafened
 
**Additional context**  
I didn't consider interactions with mutations here, also it seems like ear mutations should also possibly remove effect_deaf

**Comment by golankra123** [comment]
Type the code stuff like this `` ``code`` ``.
And I do agree as it's a bionic it's probably installed permanently -
If it is so it would be connected to the brain or the ear mussels

**Comment by Photoloss** [comment]
> I didn't consider interactions with mutations here, also it seems like ear mutations should also possibly remove effect_deaf

*Newly developing* an ear mutation could make sense as the Blob is actively reconfiguring your anatomy and we know that comes with enhanced healing/regeneration. Pre-existing ear/hearing mutations should, if anything, make you *more* susceptible to deafness as human hearing actually is pretty poor compared to many animals.

**Comment by int-ua** [comment]
Bionics can be lost so the suggested solution looks like not ideal

**Comment by Hawkaer** [comment]
> Bionics can be lost so the suggested solution looks like not ideal

Just a random suggestion here, maybe add a hidden "was deaf" tag or something? So if the bionic is removed for some reason or another, check to see if the player "was deaf" and then make them deaf again if they have that tag.

**Comment by Kaltag1925** [comment]
> > Bionics can be lost so the suggested solution looks like not ideal
> 
> Just a random suggestion here, maybe add a hidden "was deaf" tag or something? So if the bionic is removed for some reason or another, check to see if the player "was deaf" and then make them deaf again if they have that tag.

Could we implement a check for everytime hearing is called, like where is deaf is checkex?

**Comment by Kaltag1925** [comment]
Or am I misunderstanding. Is the problem just removing the trait, or can you not hear when deaf with bionic ears?

**Comment by spacenookie** [comment]
issue was prompted by a guy who had effect_deaf with an extremely long duration as a result of a nearby mininuke explosion, who thought that installing bionic ears should allow him to hear again.

pretty sure there is no current way to remove or reduce effect_deaf you just have to wait it out.

currently player is immune to (additional) effect_deaf if he has BIO_EARS.
```
if( eff == effect_deaf ) {
        return worn_with_flag( "DEAF" ) || worn_with_flag( "PARTIAL_DEAF" ) || has_bionic( bio_ears ) || is_wearing( "rm13_armor_on" );
```
