### ISSUE TITLE
Crash: Segmentation fault

### ISSUE THREAD

**Issue by Necrosian** [CleverRaven/Cataclysm-DDA#29278]
**Describe the bug**  
Crash . Suspect it's something to do with NPC infection.
Crashes after ~~4 hours in game time.

**To Reproduce**  
1.Get NPC infected
2.Wait

**Expected behavior**  
Game crashes after ~~4 hours in game, right after npcs complains about infection. 
Suspect it's something to do with NPC infection progression.

**Screenshots**  
![crash](https://user-images.githubusercontent.com/26538192/55576387-e3410980-5719-11e9-9f87-ccc49928533c.PNG)

Screenshot at crash:
![crash screen](https://user-images.githubusercontent.com/26538192/55576780-b8a38080-571a-11e9-8c47-a540bd1000ca.png)

**Versions and configuration(please complete the following information):**

    OS: Windows 10 x64
    Game Version: 0.D-1411-g6c79f15
    Build: 8718
    Graphics version: Tiles
    Mods loaded: 
    Disable npc needs,Filthy clothing,
    (DP_RP)Remix Indicator,
    Vehicle Addition pack,Tanks and Other Vehicles, Folding parts Pack,
    Urban Development,More Locations,Fuji's More Buildings,
    Mutant NPCs,Alternate Map key,
    More Survival Tools, Medieval and Historic Content, Extended Realistic Guns,
    No Fungal Monsters

**Additional context**  
Save: [Glenwillard.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3044772/Glenwillard.zip)
Crash log:
CRASH LOG FILE: config/crash.log
VERSION: 0.D-1411-g6c79f15
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x558625[cataclysm-tiles.exe+0x158625]
    @0x5591D2[cataclysm-tiles.exe+0x1591D2]
    SMPEG_error+0x4B034@0xE3AF80[cataclysm-tiles.exe+0xA3AF80]
    _C_specific_handler+0x98@0x7FFAB31E8068[msvcrt.dll+0x28068]
    _chkstk+0x11F@0x7FFAB47F468F[ntdll.dll+0xA468F]
    RtlWalkFrameChain+0x14BF@0x7FFAB4754BEF[ntdll.dll+0x4BEF]
    KiUserExceptionDispatcher+0x2E@0x7FFAB47F33FE[ntdll.dll+0xA33FE]
    @0x686CEC[cataclysm-tiles.exe+0x286CEC]
    IMG_LoadWEBP_RW+0x4DF0B9@0x140BEA9[cataclysm-tiles.exe+0x100BEA9]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFAB1B581F4[KERNEL32.DLL+0x181F4]
    RtlUserThreadStart+0x21@0x7FFAB47BA251[ntdll.dll+0x6A251]

**Comment by ZhilkinSerg** [comment]
Confirmed on latest master, but stack trace is more than strange:

![image](https://user-images.githubusercontent.com/16213433/55629690-7a5e9d80-57bc-11e9-86c3-7c8b8399448d.png)
