### ISSUE TITLE
View jumps when performing actions which hide the sidebar

### ISSUE THREAD

**Issue by Chryseus** [CleverRaven/Cataclysm-DDA#29275]
**Describe the bug**  
Using look, fire and peek causes the view to recenter which is very jarring if you're performing these actions a lot.

**To Reproduce**  
1. Look, fire a weapon or peek.

**Expected behavior**  
Viewpoint should stay fixed so it isn't constantly bouncing around, this is particularly annoying when using reach weapons. 

**Screenshots**  
![image1](https://i.imgur.com/7nrgOim.png)
![image2](https://i.imgur.com/VLTgyVV.png)

**Versions and configuration(please complete the following information):**
 - OS: 5.0.5-arch1-1-ARCH
 - Game Version: 6c79f15
 - Graphics version: Tiles
 - Mods loaded: N/A

**Additional context**  
Possible fixes I can think of:
* Return to the old style sidebar, viewport rendered full size below
* Change the targeting, look, etc to be in place of the sidebar
* Don't hide the sidebar
* Don't recenter the view

**Comment by Zireael07** [comment]
Related to #29256 ?

**Comment by Chryseus** [comment]
> Related to #29256 ?

Looks like it, I just tested with the zone manager and the highlight point when adding a zone is shifted to the right.
![image](https://i.imgur.com/vgg05MS.png)

**Comment by KorGgenT** [comment]
it recenters itself since the sidebar covers part of the screen and the new mode's sidebar does not go all the way down, are you asking to have a non-centered screen when using reach weapons etc?

**Comment by Chryseus** [comment]
> it recenters itself since the sidebar covers part of the screen and the new mode's sidebar does not go all the way down, are you asking to have a non-centered screen when using reach weapons etc?

Yes, the jumping around in combat is very distracting.
