### ISSUE TITLE
Kiwis are 501 kcal?

### ISSUE THREAD

**Issue by Alapaga** [CleverRaven/Cataclysm-DDA#29271]
**Describe the bug**  
As the title says, a normal sized kiwi should not be worth 501kcal

**Expected behavior**  
60-80 kcal is more of a normal range for such a fruit, and that's a big kiwi that i'm talking about

**Screenshots**  
https://clips.twitch.tv/AmusedTransparentInternRaccAttack

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1370-gb52c60f
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Aftershock, Generic Guns, PKs Rebalance, Alternative Map Keys, Cataclysm ++, Crazy Cataclysm, No Religious Texts, No Fungi, More Classes & Scenarios, Stats Through Skills

**Comment by Photoloss** [comment]
[This](https://ndb.nal.usda.gov/ndb/foods/show/45209709?man=&lfacet=&count=&max=25&qlookup=raw+kiwi&offset=&sort=default&format=Full&reportfmt=other&rptfrm=&ndbno=&nutrient1=&nutrient2=&nutrient3=&subset=&totCount=&measureby=&Q451206=1.56&Qv=1&Q451206=1&Qv=1) is the reference cited for that value. [Here](https://world.openfoodfacts.org/product/0028744019140/kiwi-regal-gourmet-snacks)'s an entry with matching UPC, both pages list "sugar" in the ingredients making me believe this might be a processed food and not the raw fruit.

[Here](https://ndb.nal.usda.gov/ndb/foods/show/45362722?fgcd=&manu=&format=&count=&max=25&offset=&sort=default&order=asc&qlookup=kiwi&ds=&qt=&qp=&qa=&qn=&q=&ing=)'s a different entry from the database used for the nutrient rebalance giving a more sane 61kcal/100g which equates to 87kcal for the currently given weight.

**Comment by Alapaga** [comment]
> 
> 
> [This](https://ndb.nal.usda.gov/ndb/foods/show/45209709?man=&lfacet=&count=&max=25&qlookup=raw+kiwi&offset=&sort=default&format=Full&reportfmt=other&rptfrm=&ndbno=&nutrient1=&nutrient2=&nutrient3=&subset=&totCount=&measureby=&Q451206=1.56&Qv=1&Q451206=1&Qv=1) is the reference cited for that value. [Here](https://world.openfoodfacts.org/product/0028744019140/kiwi-regal-gourmet-snacks)'s an entry with matching UPC, both pages list "sugar" in the ingredients making me believe this might be a processed food and not the raw fruit.
> 

A cup of kiwi is definitely not the fruit itself, and i'm pretty sure that first source is for a kind of processed food that has added sugar.

**Comment by ifreund** [comment]
looks like it's actually called a kiwifruit in the USDA data base.  This [entry](https://ndb.nal.usda.gov/ndb/foods/show/45212913?fgcd=&manu=&format=&count=&max=25&offset=&sort=default&order=asc&qlookup=KIWIFRUIT%2C+UPC%3A+893265001550&ds=&qt=&qp=&qa=&qn=&q=&ing=) also cites the 61 kcal/100g number so let's go with that.

Only source I've been able to find that mentions the weight is [this](https://www.livestrong.com/article/445497-kiwi-cholesterol/) which says "One medium kiwifruit weighing approximately 76 g, or 2.6 oz., contains only 46 calories." This also seems to be using the 61 kcal/100g number.

[This source](https://www.medicalnewstoday.com/articles/271232.php) cites an average value of 42kcal per fruit, which would suggest an average weight of 69 grams using the same value of 61.

[another for weight](https://hort.purdue.edu/newcrop/morton/kiwifruit_ars.html)
[yet another source for weight](https://www.answers.com/Q/What_is_the_average_weight_of_a_kiwifruit)

Not a whole lot of agreement between sources for weight, I think I'm just going to go with 75g, which seems to be on the high side and is a nice round number.
