### ISSUE TITLE
Filling a pit requires no materials, while digging a pit provides them.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#29303]
**Describe the bug**  
Infinite stone, pebbles, sand, clay and soil.

**To Reproduce**  
1. Dig a pit.
2. Fill the pit back in.
3. Have more materials than you started with.

**Expected behavior**  
Filling a pit should use most or all of the materials gained from emptying it. 

**Versions and configuration(please complete the following information):**
 - OS: Win 10
 - Game Version: 0.D-1102-g7c3a038
 - Graphics version: Tiles
 - Mods loaded: so many, probably not relevant

**Comment by NetSysFire** [comment]
In the construction menu, filling a pit requires 200 soil. Any digging tool that can fill up a pit should require
- 150 soil to convert a pit to a shallow pit
- 50 soil to fill a shallow pit

I think the "Digging a pit essentially makes clay, soil and rock infinite" may be a separate issue.

**Comment by qoreQyaS** [comment]
idk if my problem is related to somethiing else, but i am standing next to a pit, i have no soil in reach, and i try i to use an entrenching tool via (a)activate/fill Pit while being in a lightened area.
it doesn't work. a msg is displayed "You can not build here" after selecting the pit.
![image](https://user-images.githubusercontent.com/4641233/232250433-a2eb465a-2a21-4655-8ba2-c1fff5802bab.png)
![image](https://user-images.githubusercontent.com/4641233/232250442-a1e5fa5d-7fe0-4749-b7b0-e0f6da99cced.png)

seems like this issue can be closed?

**Comment by qoreQyaS** [comment]
after hauling soil next to me i was able to fill the pit in the described way.

**Comment by qoreQyaS** [comment]
fixed via #57466
