### ISSUE TITLE
Zombie Grenadier variants still spawn normally, instead of the NR dispatch variants

### ISSUE THREAD

**Issue by Mcrone617** [CleverRaven/Cataclysm-DDA#29310]
**Describe the bug**  
I did some very rudimentary testing after coming across a Elite Zombie Grenadier in a military outpost, and it seems that the NR dispatch are not spawning, and the Zombie Grenadiers still are instead.

**To Reproduce**  
-generate new worlds, and teleport to areas that have military zombies
-for example, Lab barracks, military outposts
-eventually you will find only zombie grenadiers, and no NR dispatch (at least I didn't)

**Expected behavior**  
Based on #28664 zombie grenadiers shouldn't spawn on new worlds anymore, and instead the NR dispatch should. I made a completely new world with no mods in order to test this out, and some quick debug teleportation around found some examples pretty quickly.

**Screenshots**  
![ZG_1](https://user-images.githubusercontent.com/26668115/55657009-22bd3380-57b6-11e9-87b9-ed4429790aff.PNG)
![ZG_2](https://user-images.githubusercontent.com/26668115/55657021-281a7e00-57b6-11e9-8d64-1317a2492e06.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D- 1440 - g977aca1
 - Graphics version: Tiles
 - Mods loaded: None 

**Additional context**  
Unless this is a multi-part change, Zombie Grenadiers should be obsoleted at this point, so something may be wrong with the spawning list.

**Comment by Ilysen** [comment]
I imagine that this is probably a case of me not changing instances of the grenadier in all the locations it happens, but I can't check right now. Can you see if there are any monster groups of `place_monster`s in mapgen involving grenadiers?
