### ISSUE TITLE
The Northrop Dispatch is not hostile to other enemy factions, only the player

### ISSUE THREAD

**Issue by Mcrone617** [CleverRaven/Cataclysm-DDA#29312]
**Describe the bug**  
When testing, it appears the NR dispatch (both the riot and the military variants) isn't hostile to any other faction in the game. I spent some time testing it via the debug, and it will let zombies smash away at it while not releasing any drones.

**To Reproduce**  
-Spawn in a NR-dispatch and your mob of choice
-make sure your character is invisible via the debug menu, to simulate the character being missing
-watch as the NR-dispatch does nothing as the zombie of your choice slowly destroys them

**Expected behavior**  
Based on my understanding of the lore, shouldn't all robots be programmed to destroy blob-infected beings, both alive (the player) and undead? While it makes sense in some specific situations for robots to be non-hostile, like turrets in labs not killing scientists and approved personnel, for the most part robots should be doing their due diligence to eradicate the blob menace until they run out of ammo.

However it seems like these robots are simply bugged, and were intended to attack zombies, as other robots in the game already do this. (police bots for example)

**Screenshots**  
![NRD_1](https://user-images.githubusercontent.com/26668115/55658013-6ebda780-57b9-11e9-8398-792964ef17ae.PNG)
![NRD_2](https://user-images.githubusercontent.com/26668115/55658020-72e9c500-57b9-11e9-88c8-283e1dc0306d.PNG)
This photo below shows how the bot suddenly works when I take the debug invisibility off, but before it was doing nothing to stop the zombies from destroying it.
![NRD_3](https://user-images.githubusercontent.com/26668115/55658027-767d4c00-57b9-11e9-9de5-b2320defe3ed.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version:  0.D- 1440 - g977aca1
 - Graphics version: Tiles
 - Mods loaded: None 

**Additional context**  
Again, I think something was missed in #28664 as most other robots are properly hostile to zombies. It's not that big of a deal, but its probably something that should be taken care of when the bug is fixed that starts spawning these monsters instead of Grenadiers, as I detail in #29310

**Comment by Ilysen** [comment]
This was a technical limitation caused by the way grenadiers were coded, which seemed to only let them attack players, and resisted all my attempts at changing that. I'd like to fix it, but I have no idea where to start.

**Comment by Maleclypse** [comment]
@actual-nh I'm pretty sure this should be closed post your faction attitude rebalance as I recently watched a dispatch absolutely annihilate the squad of soldier zombies it spawned next to.

**Comment by actual-nh** [comment]
Thanks!
