### ISSUE TITLE
Pushing a NPC away will sometimes move into a seen/known/already found landmine

### ISSUE THREAD

**Issue by adamdeno** [CleverRaven/Cataclysm-DDA#29325]
**Describe the bug**  
When trying to move NPCs out of the way they will sometimes think that a landmine is a clear floor and thus exploding in it!

**To Reproduce**  
1. Find a NPC (Make him follow you)
2. Find any variant of minefields (Mine was in a house)
3. push him out of the way near the landmine and he will move into it

**Expected behavior**  
NPCs should find a suitable spot rather than moving randomly and exploding

**Screenshots**  
![7x1](https://user-images.githubusercontent.com/41305926/55666705-fb687400-5852-11e9-92c2-6110440c02b5.PNG)

![7x2](https://user-images.githubusercontent.com/41305926/55666719-10450780-5853-11e9-826d-c6d334cf8d98.PNG)

**Versions and configuration(please complete the following information):**
 - OS:  Windows 10
 - Game Version: 0.D-1443-gac73a97 (tiles)
 - Graphics version: Tiles
 - Mods loaded: [ dda , (filthy clothing) , (disable NPC needs) , (garden pots) , (makeshift item mod) , (more survival tools) , (mythological replicas) , (medieval and historic content) , (Mining mod) , (mutant NPCs) , (beta natonal guards) , (more locations) , (fuji's more buildings) , (mapgen demo) , (more city locations) , (urban devolpments) , (boats) , (folding parts pack) , (vehicle addition pack) , (tanks and other vehicles) , (classes and scenarios mod) , (classic roguelike classes) , (stats through skills) , (no fungul)

**Additional context**  
I know pushing someone away should make them accidentally step on landmine , but its not intended or is it?

**Comment by Night-Pryanik** [comment]
That's just because NPCs are VERY obedient.
