### ISSUE TITLE
Swamps are very noob friendly.

### ISSUE THREAD

**Issue by Vasyan2006** [CleverRaven/Cataclysm-DDA#29329]
**Is your feature request related to a problem? Please describe.**  
Swamps are very noob friendly, they are basically just forest with placed water tiles, despite the fact that real swamps can be very dangerous even for experienced survivor.

**Describe the solution you'd like**  
Replace most dirt tiles with traps, but they will require survival skill for being detected instead of trapping. 

Effect of these traps can vary from simple fall into deep water to stuck in the bog with low chances for getting out. So swamps will be more like mine fields, which most characters should avoid.

Optionally add ability to use long stick for checking neighbor tiles to find solid ground.

**Comment by mlangsdorf** [comment]
I am an ignorant city guy and I've walked through swamps in New England without risking my ankles to constant sprains.

Swamps could be more dangerous but nothing but traps seems like overkill.

**Comment by Amoebka** [comment]
There is infinite water in normal forests now, so the only advantage of swamps is salt water, which isn't relevant until mid-late game.

Swamps are also already a lot more dangerous than forests. Giant dragonflies/wasps wreck weaker characters and new players.

**Comment by Hirmuolio** [comment]
Some zombies could be added to forest/swamp/field monster groups.

Currently zombies only spawn in overmap special locations (=buildings) and in some overmap extras (=random corpses and plane crashes).

Until player lures zombie hordes from cities the countyside has no zombie apocalypse going on.

For terain hazard one could be water that is deeper than it looks. It looks like shallow water but when you step in it it is actually full depth water. Taking one step into deep water won't likely be a life threatening but it will be a nasty suprise.

**Comment by Alapaga** [comment]
How about adding a risk of leeches, if the character wades in the water without propper equipement (Rubber boots or tigh high boots or fishing waders) it could result in leeches.

The affected limbs would be marked with a yellow modifier and you can apply a lit cigarette or cigar to "burn" the leeches within the next 12 hours, resulting in minor pain. 

If symptoms are not treated within a reasonnable timeframe, it would result in a parasitic infection, resulting in higher thirst and occasionnal vomiting. 

These are just my ideas to help you guys in this tought process, thanks for reading me

**Comment by kevingranade** [comment]
Rather than dealing damage, we could have traps that trigger slowdown, like stepping in deep mud or similar.
For that to matter it has to be paired with enemies the player would want to run from.

I think a major contributor to this problem is we have no large swamps, just small marshy areas.

There are lots of other interesting swamp hazards that come up with lots of exposure, like lack of shelter, lack of fresh water, fungal infections (from being constantly wet), leeches and other parasites, etc.

**Comment by codemime** [comment]
Speaking of swamp friendliness, I suppose there should be two distinct types of them: common swamps with fresh water and (much less common) [salt marshes](http://www.ocvts.org/classroomconnect/classrooms/jwnek/documents/Oceanography/Salt%20Marsh%20Pool%20Comparison.pdf). Currently, you can always have both fresh water and salt water at your disposal in any nearest swamp. This is neither realistic nor interesting gameplay-wise.

**Comment by l29ah** [comment]
Is it me or swamp creatures have stopped spawning?
