### ISSUE TITLE
Idea - Craftable detergent

### ISSUE THREAD

**Issue by reusual** [CleverRaven/Cataclysm-DDA#29330]
In some playthroughs, I wasn't finding a lot of detergent, and after rigging up a washing machine from an old RV I was frustrated by the fact that it was essentially useless until I managed to locate a box of washing powder. The soap & washboard solution is available in lieu of this, but it seems like a step backward to have to find a puddle of water or use a handpump after going to the trouble of installing a washing machine.

From the wiki on laundry detergent:

"From ancient times, chemical additives were used to facilitate the mechanical washing of clothing with water. The Italians used a mix of sulfur and water with charcoal to clean cloth. Egyptians added ashes and silicates to soften water. Soaps were the first detergents."

**Describe the solution you'd like**  

A craftable form of detergent utilising already available components, but with the addition of "Sodium Carbonate", a simple compound created from limestone and saltwater.

https://en.wikipedia.org/wiki/Solvay_process

**Describe alternatives you've considered**  

Instead of adding a recipe, we could look towards creating a common building blueprint like a laundrette (a self-service laundry shop), and adding laundry/washroom facilities to hospitals/schools/prisons/apartments and any other relevant places. These places would have a higher chance of spawning large caches of detergent.

**Additional context**  

I've attached my solutions. One additional core item, and two recipes. Tested and working but will need balancing for composition, yields and weights.

[chemicals_and_resources.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/3050464/chemicals_and_resources.txt)

[recipe_medsandchemicals.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/3050465/recipe_medsandchemicals.txt)

**Comment by mlangsdorf** [comment]
Would you mind reading the guide for new contributors (https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-modders) and submitting your fixes yourself?  If you've already created a GitHub account and written the JSON, you're 80% of the way to solving this.

**Comment by reusual** [comment]
Thanks for the quick reply. I did give the guide a look, and was under the impression that I'd need to clone/fork/test/compile in order to get anything submitted. That process is unfortunately beyond the capabilities of my current system, so I thought I'd post this here for anyone who wants to take it any further.

Is there a process for submitting new content which doesn't require the above procedure? Forgive me if I missed those instructions, if you could point me to the specific section for this then I'll get to work on it.

**Comment by Zireael07** [comment]
JSON editing doesn't require forking/compiling, but it does require testing (so you have to have a copy of CDDA)

**Comment by Rail-Runner** [comment]
I did a bit of research, most Russian sources indicate that soap can be somewhat successfully used in washing machines too if it's cut into small bits first (some soap might stay on the clothing, but for survivor that likely wouldn't matter; that's still much more clean than clothing taken off of a zombie), and the washing machine will need regular cleaning to remove sticky residue (which may be abstracted away as done automatically by the character as needed). Hope that helps.

**Comment by kevingranade** [comment]
I have also heard many reports of ordinary fat/lye based soap working in mechanical washing machines.
