### ISSUE TITLE
Updating from [8712] to [8731] Deletes bionics.

### ISSUE THREAD

**Issue by Helldrone** [CleverRaven/Cataclysm-DDA#29336]
![CDDA 8712 Bionics](https://user-images.githubusercontent.com/49344129/55671130-e90b2c00-588c-11e9-8986-005112ee2d87.png)

![CDDA 8731 Bionics gone](https://user-images.githubusercontent.com/49344129/55671132-ec061c80-588c-11e9-8d08-94c448748455.png)

Win 10 Laptop
and mod list

![Mods](https://user-images.githubusercontent.com/49344129/55671284-e8739500-588e-11e9-91b8-df6c3b26ab4a.png)

**Comment by Dwaggy** [comment]
Confirmed.
And narrowed down to build 8730
i updated from 8729 (which had all bionics just fine). But updating to or past 8730 (as of right now) causes all bionics from current saves to be lost and re-finding or debugging them all back in.
New worlds/characters with starting bionics are fine, however.
