### ISSUE TITLE
NPC activity control

### ISSUE THREAD

**Issue by mlangsdorf** [CleverRaven/Cataclysm-DDA#29333]
NPCs need a couple of new features to deal with fleeing and investigating noises:
- [x]  For followers, distinguish between "guard and investigate noises" and "stay here for a bit."
- [ ]  Get rid of the follower attitude, which is only causing problems, and replace it with checking if an NPC is part of the player's faction.
- [x]  Add a "don't investigate here" zone so that you can tell NPCs to not investigate the shoggoth noises.
- [x]  Add a "investigation limits" zone so that NPCs don't wander too far off.
- [x]  Add a "retreat target" zone so that NPCs can have a sensible place to retreat.
- [ ]  Add the ability to define zones in mapgen so pre-gren NPCs can have a limit or retreat zone.
- [x]  Add an NPC AI rule to not open doors (so useful for exploring labs!)
- [x]  Add an NPC AI rule to not move through obstructed terrain/doorways that are adjacent to the player (teach NPCs to hold a chokepoint!)
- [x]  Add rule overrides, so that players can temporarily set several rules at once or unset them, but doesn't change the underlying behavior.
- [x]  Add a shout command "we're in a danger zone" that (via rule overrides) shuts NPCs up, prevents them from sleeping, makes them flee with the player, prevents them from opening doors, and prevents them from moving past chokepoints and a shout command "we're safe" that clears the overrides.
- [x]  Bugfix: shouts should work on NPCs the player can't see but that can hear the player, but not on NPCs the player can see but who can't hear the player.  Obviously.

**Comment by adamdeno** [comment]
Yes , This is a good one. i always run into troubles when having to tell my NPCs to guard ALSO if there is a sound downstairs while they are guarding they will go to investigate and probs get themselves killed

**Comment by curstwist** [comment]
All great improvements.  Will window 'management' also be included with closing doors?

**Comment by mlangsdorf** [comment]
NPCs won't open windows if they are told they can't open doors.

**Comment by mlangsdorf** [comment]
Incomplete and closed prematurely.

**Comment by neitsa** [comment]
> Add a shout command "we're in a danger zone" that (via rule overrides) shuts NPCs up, prevents them from sleeping, makes them flee with the player, prevents them from opening doors

Is this like a "flee you fools" command where every NPC try to save his own life? If yes, should not they be allowed to open doors if they want to flee?

I might have misunderstood the command though. I also read it has "Be on your guard".

**Comment by mlangsdorf** [comment]
See the NPC tutorial talk topics that explain what it's for.

**Comment by mlangsdorf** [comment]
"Flee you fools" tells them to prioritize staying close to you over fighting, so if you run, they'll run.
"In a danger zone" says we're in zombie country, don't take naps or open closed doors that will lead to hostile turrets and death.

The tutorial should make this stuff clearer.

**Comment by neitsa** [comment]
Yep, thank your very much Mark!

**Comment by ZhilkinSerg** [comment]
Is it  fully done after #30150?

**Comment by mlangsdorf** [comment]
Yes, it's finished.
