### ISSUE TITLE
NPC give inventory gives -very- dangerous items

### ISSUE THREAD

**Issue by minakitty** [CleverRaven/Cataclysm-DDA#2934]
Zaweri just had an NPC give him an active bomb, which of course blew him to "tiny bits, in thy mercy."

(Quote curtosy of the Book of Armaments, chapter two, verses nine through twenty-one)

**Comment by qbradq** [comment]
This is no longer an issue. NPC inventories are now populated from item groups from the data/json/npcs/NC_*.json files.

Please close.
