### ISSUE TITLE
Calves are a hassle and I need a way to move them around and contain them.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#29343]
**Describe the bug**  
My herd of cows sometimes will cause a new neutral calf to spring into existence. There is currently no way to manage their movements or the sound they make, which causes me to wake up in the night, and my guard NPC's follow them around to track their footsteps. 

Additionally, when they reach adulthood, the guard promptly kills the new neutral cow before I can tame it.

**To Reproduce**  
Have a cow, set a guard, see a calf born, watch everything go sideways.

**Expected behavior**  
- [ ] I would expect there to be a way to manage baby animals, even if they can't be tamed. 
- [x] I would expect that mechanism to limit the noise they make and NPC guards from being so interested in them.
- [x] I would expect that mechanism to keep the new adult from being attacked by NPC guards.

**Comment by dom4op** [comment]
Exact same problem with lambs. Can't tame it until it grows up.

How about tranquilizer gun using tranquilizer darts as ammunition? Let it have 0 damage and cause "tranquilized" effect that only applies to Wilderness-class monsters (everything else should be immune). The effect does the following:
- reduces speed by 80%
- makes it possible to cage non-tamed creatures

This way the player will be able to release calves and lambs in some sort of enclosed area and wait for them to grow and become tamed.

Also, we should probably make huge beasts like moose and bear immune to that effect as well.
