### ISSUE TITLE
Roads don't render with non-default font on overmap

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#29350]
**Describe the bug**  
Roads, trails, and a few other overmap features show as an unprintable character in certain fonts, such as Square Modern.
**To Reproduce**  
1. Set fonts.json overmap font to Square Modern
2. Look at any overmap
**Expected behavior**  
I expect roads to continue to render as they did in the past. I think I remember that we updated our version of Unifont recently, and while that's nice, I really do prefer my map grids to be square. Setting overmap font width to 16 helps, but also looks kind of strange with unifont.

**Screenshots**  
![image](https://user-images.githubusercontent.com/2125926/55674617-e86e9780-5884-11e9-88eb-a17f1ead06c7.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1508-gdd8f6a9
 - Graphics version: Tiles
 - Mods loaded: N/A

**Additional context**  
My fonts.json file is below:

```
{
  "fontblending": false,
  "fontwidth": 8,
  "fontheight": 16,
  "fontsize": 16,
  "typeface": "Terminus",
  "map_fontwidth": 16,
  "map_fontheight": 16,
  "map_fontsize": 16,
  "map_typeface": "Square Modern",
  "overmap_fontwidth": 16,
  "overmap_fontheight": 16,
  "overmap_fontsize": 16,
  "overmap_typeface": "Square Modern"
}
```

**Comment by KurzedMetal** [comment]
Can reproduce, doesn't work with "white rabbit" either.

```
{
  "fontblending": true,
  "fontwidth": 9,
  "fontheight": 18,
  "fontsize": 18,
  "typeface": "terminus",
  "map_fontwidth": 20,
  "map_fontheight": 20,
  "map_fontsize": 20,
  "map_typeface": "wrabbit",
  "overmap_fontwidth": 20,
  "overmap_fontheight": 20,
  "overmap_fontsize": 20,
  "overmap_typeface": "wrabbit"
}
```

![20190406_170500_cataclysm-tiles](https://user-images.githubusercontent.com/1426680/55674682-23c19400-588e-11e9-9d44-c4b08449a323.png)

**Comment by kevingranade** [comment]
Did the change shift these from legacy line drawing characters to unicode line drawing characters?

**Comment by AMurkin** [comment]
Related #29161.

**Comment by ZhilkinSerg** [comment]
> Did the change shift these from legacy line drawing characters to unicode line drawing characters?

Possibly, but the symbols used are actually the same.

**Comment by Inglonias** [comment]
Apparently not?

**Comment by ZhilkinSerg** [comment]
> 
> 
> Apparently not?

Yes. With all of our transformations that were actually different characters which are missing in most of the fonts.

**Comment by KurzedMetal** [comment]
I have always used the same fonts over a 6 months now, and always worked.

Something changed recently that broke this.

**Comment by ZhilkinSerg** [comment]
Just to make sure: you are both on Windows Tiles version, right?

**Comment by Inglonias** [comment]
I am on Windows tile. Sorry, didn't fill that part in on my report.

**Comment by dkargin** [comment]
The same thing happens with linux tiles.

**Comment by KurzedMetal** [comment]
Windows Tiles too
