### ISSUE TITLE
NPCs will take unsafe shots (player/ally in the way) even when told not to

### ISSUE THREAD

**Issue by drhead** [CleverRaven/Cataclysm-DDA#29358]
**Describe the bug**  
NPCs seem to take shots at enemies even when a player is directly, unambiguously, in the line of fire, when they have been specifically told (well, defaulted to) not to.

**To Reproduce**  
1. Ensure an allied NPC is armed with a gun and has been told to not take unsafe shots.
2. Get between them and an enemy.
3. They'll probably shoot at you.

**Expected behavior**  
I'd expect an NPC to not take shots if there is more than a certain percent chance to hit an ally.  This should always mean that NPCs do not take shots when an ally is in the way.

**Screenshots**  
http://puu.sh/Db258/ffdd1849f6.png
http://puu.sh/Db3hN/1092e5fd0b.jpg

The corpses in both of these images are where enemies were.  I'm the unarmed guy.  That asshole with the shotgun is the NPC.  The blood in the second screenshot picture is not from the zombies.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: Build 8728
 - Graphics version: Tiles x64

**Comment by mlangsdorf** [comment]
I think this is a result of the NPC being too confident on their hit percentage.  I've definitely seen it happen but haven't dug into it yet.  It's amiable to automated testing so it should go pretty when I have a chance to test.

**Comment by anothersimulacrum** [comment]
I can't reproduce this anymore, can someone confirm it?

**Comment by mlangsdorf** [comment]
I can confirm that NPCs will move to avoid the avatar.
