### ISSUE TITLE
New Triffid & Miscellaneous Monsters

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#29361]
Recently attended a conference and saw some interesting flora/fauna that I think would be useful and unique monsters. These do not necessarily have to be exact if anyone is interested in coding/implementation, but if I were capable of implementing them, this is how I'd approach them.

Hemiparasites - basis: [Indian paintbrush](https://en.wikipedia.org/wiki/Castilleja) - essentially, parasitic plants that are enhanced by being able to attach to nearby hosts but capable of surviving on their own. A triffid hemiparasite would be an enhanced specialty fighter (similar to Fungal Fighters) that are capable of occasionally attacking with a special "draining" attack that could receive a bonus temporary "power-up" randomly chosen from a pool based on the target.

For player targets, the pool choice would be from:
* **Beneficial** (_"steals" from positive mutations [starting traits would be ignored, like Gourmand or Spiritual] that grants the Hemiparasite enhanced attack damage and speed_)
* **Neutral** (_"steals" nutrients, draining player HP, Health, Hunger/Thirst, Vitamins, grants Hemiparasite health and/or small regen bonus_)
* **Malus** (_"steals" from negative mutations [starting traits would be ignored, like Asthmatic or Bad Knees_] that confers the Hemiparasite decreased attack damage and speed and reduces HP)
* **CBM** (_if player has CBMs, then can confer temporarily similar abilities to shocker type monsters [zapback, zap when attacking, and electrical ranged zap] - if player has no CBMs, defaults to Neutral behavior_).

Against Blob:

* **Regeneration** - _"steals" Blob goo that was being used for healing, that grants Hemiparasite mild regeneration for a few rounds (enough that Hemiparasites alone should be capable of taking on a small-moderate sized group of average zombies without loss). 30% chance._
* **Overgrowth** - _"steals" intense Blob goo that instead of healing damaged parts, actually causing a near tumorous growth of hardened protective cells (aka bark and the like), that dramatically increases defense with some health (think along the lines of [Temporary Hit Points from D&D](https://www.dandwiki.com/wiki/5e_SRD:Temporary_Hit_Points) but because the Hemiparasite isn't capable of supporting the new vascularization, the overgrowth will begin to "shed" after some time (lasts longer than Regeneration, but occurrence should be much lower, like at most, once an encounter/fight, whereas Regeneration may occur 2-3 times), gradually losing both the defense and HP. (Example: Overgrowth Activates - Turn 1: +10 defense, +25 HP - Turn 2: +9 defense, +23 HP - Turn 3: +8 defense, +21 HP, etc.) 15% chance._
* **Rapid Synthesis** - _"steals" manufacturing Blob goo that allows Hemiparasite to rapidly synthesize thorns that erupt off forcefully, similar to Boomer Zombies, except basically a living nail bomb. Lasts a few rounds, with decreasing amount of force and amount each turn (so the first blast is the most painful, the last is a "scratch"). 30% chance._
* **Rejection** - _fails to "steal" and is actually temporarily overcome by Blob influence --- essentially similar to a "Downed" status and loses a slight bit of health due to the rapid shedding and internal processes to rid itself of the actively hostile Blob. Should be about 25%._

Against Mycus:

* **Antibodies/fungal** - _vomits (or probably just sprays from some type of orifice) (similar to acid zombie ACID_BARF) antifungal stuff that disables sporulation upon contact, and for terrain, slowly reverts it back to normal (but depends on amount similar to acid amount [splatter/streak/pool], so only when reaches the highest amount does it revert the tile). Lasts a significant amount of time (5 in-game minutes maybe? Triffids should be able to handle Mycus a bit easier than Blob)._
* **[CAM](https://en.wikipedia.org/wiki/Crassulacean_acid_metabolism) Protection** - _Can take a "deep breath" (plants "breathe" through their stomata in a weird sense) and becomes immune to fungal infections/spore infiltration. Lasts a significant time but also incurs brief intense slowdowns (Downed status maybe?) to simulate taking another breath._
* **Drain** - _nullify the infectious fungus and breaks down into suitable nutrients to replenish and repair Hemiparasite's structure. Grants unequal HP (energy required to "clean" and flush from body safely) - so if it "drains" 10 HP from fungaloid, Hemiparasite only receives 6~ HP._
* **Infection** - _Hemiparasite fails to resist fungal infection and spends a few turns downed and expels 2-3 spore clouds as a rapid response. Probably once every 2-3 fights (Triffids again, should be a bit more adept at combating Mycus than Blob)._

Lore would be these are resource-intensive creations by the Triffid hearts that have begun to utilize fungal abilities and Blob abilities against themselves, typically accompanying Triffid Queen hunting parties in small amounts that are sent out to clear inhospitable areas (specifically for Blob/Mycus). Basically, "crops" of these hemiparasites are grown and undergo something similar to [clonal selection](https://en.wikipedia.org/wiki/Clonal_selection), in that they must resist Blob/Mycus influence and still capable of "absorbing" their powers, albeit for brief moments of time. Those that fail selection, are immediately culled and cleansed before re-utilizing the nutrients for another attempt. The success rate is essentially miniscule at a macro scale (Blob and Mycus both would easily sweep aside Triffid forces, but this is "early" Triffid counter-research --- perhaps players could sway Triffid hearts to some cooperation to assist in providing human knowledge adapted for Triffid physiology to exert greater influence and control [creating "better/stronger" Hemiparasites at the long-term cost of human independence as these Hemiparasites would also become more adept at combating humans]).

---

Burying Beetles - basis: [American Burying Beetles](https://en.wikipedia.org/wiki/Nicrophorus_americanus) - All those corpses left behind? Now they become mummies that support the beetle larva! Active only in the summer months, the burying beetles would be in small groups (probably usually 2) and would actively seek out corpses, dig a pit, inject eggs and bury the body, wherein a small amount would hatch the following summer. However, given the Blob influence, this huge beetles can only use SMALL or above sizes for their eggs, and Burying Beetles [will actually cull their larva suitable to carcass](https://en.wikipedia.org/wiki/Burying_beetle), so we can assume they lay the same amount of eggs regardless of carcass size but commit infanticide suitable for food available. Each pair of beetles once finding a carcass, will hide in an adjacent tile with the mound of dirt.

Interacting with survivors and wildlife would be limited as burying beetles would be these "gentle giants" that just go around "stealing" corpses from players (weren't able to haul back that Moose kill, too late, belongs to the burying beetles now!) and also "clean up" in a sense.

In terms of zombies, they would do the same behavior, but their larva have an extremely high chance of becoming infected, wherein they would become the "mummified" (sorry, too good of a pun) variants that now seek to bury the living and dead together, amalgamating into pseudo-slime pits that birth Jabberwock/Shoggoth-like beings (or could even be the source of here-to-unknown origins of Jabberwocks and an in-game ability to generate them, as they only exist when spawned by NPC quests).

---

This last monster is a bit in a gray area and may require some rewording but essentially there are two types of uses found in nature (alternate names could easily be [Frass/Exuviae/Execreta]):

[Fecal Shield / Club](https://en.wikipedia.org/wiki/Fecal_shield) - some insects ([tortoise shield beetles](url)) will use it as a shield against predators and such. Others will actually use it as a [poisoned club to ward off predators](https://www.wired.com/2015/06/absurd-creature-of-the-week-tortoise-beetle/) (the [poison is from whatever toxic plants](https://en.wikipedia.org/wiki/Fecal_shield#Function) the insect is native to and developed resilience against). Basically it consists of bits of exoskeleton as well as excreted matter (with the poisonous component generally from plants).

Triffids have domesticated these native Earth species as "sentries" in high-risk Fungal areas of engagement that have been fed highly concentrated anti-fungal compounds, similar to ants farming aphids. Typically, these are found protecting the perimeter of the more advanced Triffid Heart caves (newer colonies have yet to collect enough "cattle", although they may have brought a few "breeding" pairs to get started but nothing serious enough to ward off attacks).

Player interaction could involve collecting and weaponizing the hyperpoison against Mycus, in addition to for Mycus players, becoming a severe obstacle (being attacked by such sentries would inflict major hemorrhagic damage).

**Comment by nexusmrsep** [comment]
To,dr: Giant dung beetles

**Comment by DracoGriffin** [comment]
> Tl,dr: Giant dung beetles

Those eat dung, these beetles make it full of toxins and protect themselves with it like an umbrella or a shillelagh.

Again, they don't have to be beetles, could be anything --- the interesting factor is meant to be used however a contributor wants; I personally would implement them as I described above.

**Comment by Photoloss** [comment]
Overall these sound like a lot of work for fairly little player interaction, no harm to that though as long as they aren't also CPU hogs.

> starting traits would be ignored, like Gourmand or Spiritual

Does not work that well for lab mutant starts where you can pick gills or hooves as a "starting trait". Conversely not everything you can mutate into will make sense to "steal" e.g. Ursine Vision.

> CBM (if player has CBMs, then can confer temporarily similar abilities to shocker type monsters

Not sure those can be "stolen" as they require either electrical hardware in place or a direct power supply from the Blob.

> All those corpses left behind? Now they become mummies that support the beetle larva!

These would need to operate outside the reality bubble to be worthwhile. And any spawned beetles would need to be `TINY` so we don't get a resurgence of "roach ranching" for infinite self-replicating food.

> This last monster is a bit in a gray area and may require some rewording

Should be easy enough if the gameplay part is desirable. Just change or don't specify the manner of "excretion" so it's in line with web-spinning, acid spit and parasitic infestations (dermatik).

**Comment by kevingranade** [comment]
I actually think the shield/club concept is the strongest of the three, as it establishes a pattern a plant or animal can use to defend against crazy alien toxins, which in order to be a major player in the dda world, seems like something that needs to happen.

Burying beetles: let's set aside the non-zombified ones for now, if they dont distinctly interact with the player, they might as well not exist.
My read on the zombie variant of the beetle is that they would somewhat serve a similar purpose as (the original intent at least) zombie roaches, if you leave corpses lying around, you're risking a beetle infestation. In other words the focus is more on establishing an alien ecology than establishing a distinct threat.  I think it's a neat idea, but it needs a bit more development

Hemiparasite: this stretches the parasitism concept beyond the breaking point, all the individual interactions seem like a pain in the ass to code and maintain, and I don't think all the different variations actually bring anything to the game.  If you want a hemiparasitic plant, why not have a plant that has both it's own existence and can latch onto a host animal to become e.g. more mobile, more energetic, etc? Then it's monster/monster pairings instead of being target-centric.

**Comment by DracoGriffin** [comment]
> Overall these sound like a lot of work for fairly little player interaction, no harm to that though as long as they aren't also CPU hogs.

They might be, but no different than when there was a ton of scavengers/critters before being temporarily removed. If anything, it's meant to make the world more vibrant and alive (even if it has been taken over), not a very isolated experience.

> Does not work that well for lab mutant starts where you can pick gills or hooves as a "starting trait". Conversely not everything you can mutate into will make sense to "steal" e.g. Ursine Vision.

It's less "stealing powers" and more "appropriating Blob" --- negative mutations having a more discordant/harmful resonance with the Blob and positive mutations yielding the more harmonious/helpful resonance. Akin to taking a terrible garage band's song and trying to fit your own notes in contrast to hiring a symphony orchestra to play along your notes.

> > CBM (if player has CBMs, then can confer temporarily similar abilities to shocker type monsters

It's more of turning electrical energy into chemical energy, akin to something like the [ETC](https://en.wikipedia.org/wiki/Electron_transport_chain). Triffid biology may be more adept at converting different types of energy into chemical energy (similar to photosynthesis but optimized for new environments).

> These would need to operate outside the reality bubble to be worthwhile. And any spawned beetles would need to be `TINY` so we don't get a resurgence of "roach ranching" for infinite self-replicating food.

Or just make it so they don't target their own species corpses, but that is a good catch to avoid infinite circle.

> Should be easy enough if the gameplay part is desirable. Just change or don't specify the manner of "excretion" so it's in line with web-spinning, acid spit and parasitic infestations (dermatik).

Just more of players *really* run with the whole "poop" thing, but if the name is different enough (like Frass) that they will have no idea unless they research it, then in my mind, I've already won the battle as now they've learned something they never knew before (and maybe get interested in the *why*).

---
 
> I actually think the shield/club concept is the strongest of the three, as it establishes a pattern a plant or animal can use to defend against crazy alien toxins, which in order to be a major player in the dda world, seems like something that needs to happen.

That surprises me as that was the one I was really apprehensive about adding. But again, none of the suggestions *have* to be added *as is*, I just really wanted to share these plans instead of hibernating in a text document on my hard drive.

> Burying beetles: let's set aside the non-zombified ones for now, if they dont distinctly interact with the player, they might as well not exist.

See above response but I'm of the mind not everything has to interact with the player directly, but the player could potentially utilize them in some way for clean up or farming (maybe there is a useful byproduct of the process for soil, such as the Blob absorbed into the soil/crops and growing at an increased rate or something).

> My read on the zombie variant of the beetle is that they would somewhat serve a similar purpose as (the original intent at least) zombie roaches, if you leave corpses lying around, you're risking a beetle infestation. In other words the focus is more on establishing an alien ecology than establishing a distinct threat. I think it's a neat idea, but it needs a bit more development

Not so much roaches, but a way to kinda explain slime pits (which could have alternative creation paths as well, it doesn't need be exclusive) --- but essentially the Blobified beetles begin accruing all Blob mass in centralized locations to allow creation of larger Blob vessels (such as Brain Blobs) --- or even allowing increased sentience and control. They could, in a way, be the inverse of Mycus (spread out) --- collect and amass Blob into forming "radio towers" aka beginning stages to allow for Overlords and other deeper Blob footholds. Also for generating larger creations from melding things together, rather than using limiting hosts.

> Hemiparasite: this stretches the parasitism concept beyond the breaking point, all the individual interactions seem like a pain in the ass to code and maintain, and I don't think all the different variations actually bring anything to the game. If you want a hemiparasitic plant, why not have a plant that has both it's own existence and can latch onto a host animal to become e.g. more mobile, more energetic, etc? Then it's monster/monster pairings instead of being target-centric.

I really enjoyed the idea of how hemiparasites operate and being able to literally steal anything (nutrients, enzymes, toxins, etc) and utilize it for their own enhanced survivability whilst still capable of living alone. The way I see the hemiparasites for the Triffid are specialized troops that increase in strength the more enemies they are exposed to (although that requires them surviving encounters) and becoming terrifying late-game enemies that somewhat "grow" in power levels with players, but very reliant on interactions with surrounding factions/flora/fauna.

---

I forgot to add _Physaria_, more specifically _[Physaria bellii](https://en.wikipedia.org/wiki/Physaria_bellii)_, as it's just a stark and beautiful contrast as the _Physaria_ typically grow on unheard of soil, such as shale for _P. bellii_ ([image](http://extras.mnginteractive.com/live/media/site21/2018/0329/20180329__30DCGCENw~1.jpg)). There is also _P. cinerea_ ([image](http://swbiodiversity.org/seinet/taxa/index.php?tid=16352&taxauthid=1&clid=0)) which grows on gypsum and limestone.

Triffids would basically use these similar mechanisms to grow "terraformer" plants that thrive in radioactive/Mycus/Blob regions but rapidly die off (and generally need tending and transplantation to new regions). This would allow new Triffid Heart caves to surround themselves initially with Terrapods, that essentially act as demarcation lines for territory (at least in hostile locations, like Earth).

For player interaction, they could be used to clean up radioactive areas as well as extensive Blob infected areas (for instance, reverting slime pits back to normal terrain/areas). There could additionally be ways of utilizing the synthesized toxic materials (such as extracting Terrapods for blob glob or precursor material for mutagen/serums or radioactive Terrapods giving soft glows, acting as organic pseudo-light posts).
