### ISSUE TITLE
if you turn bum guard hostile in refugee center other guards dont help him

### ISSUE THREAD

**Issue by Leviathan21** [CleverRaven/Cataclysm-DDA#29371]
**Describe the bug**  
title

**To Reproduce**  
1. find refugee center 
2. piss off a guard so he becomes hostile
3. guards refuse to help him so you may pick them one by one

**Expected behavior**  
bums go hostile

**Comment by mlangsdorf** [comment]
Should be fixed by #30984, please retest with a recent experimental.

**Comment by kevingranade** [comment]
Presumed fixed.
