### ISSUE TITLE
schrodinger's pizza box

### ISSUE THREAD

**Issue by Substance455** [CleverRaven/Cataclysm-DDA#29373]
**Describe the bug**  
The Pizza Delivery Boy/Girl profession starts with a box of meat pizza that contains 4/2 portions. Yes. that's right. Somehow, your local pizza chain has somehow designed quantum tunnel pizza boxes.

**To Reproduce**  
It's visible in character creation, and in-game.

**Expected behavior**  
I expected the cardboard box to contain 4 portions as a normal pizza box would.
What's even worse is that there's a full 4 portion pizza jammed inside a box that's only big enough for 2 portions.

**Screenshots**  
![image](https://user-images.githubusercontent.com/17332094/55695453-a9c10600-5986-11e9-9cc9-8066e89b8ec3.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: Expirimental Build 8737
 - Graphics version: Tiles
 - Mods loaded: Defaults

**Comment by esotericist** [comment]
Clearly someone folded a pizza and shoved it into a pasta box.

**Comment by adamdeno** [comment]
Not only that. the game forces you to eat an entire pizza! the entire pizza! what if i want to eat a slice?
