### ISSUE TITLE
"Rigid table manners" doesn't work with vehicle seat+table

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#29384]
**To Reproduce**  
1. Get a luxury RV and some food
2. Sit in a seat next to a table
3. Consume food.
4. `Ate like an animal         -2`

**Versions and configuration(please complete the following information):**
0.D-1522-gea190d32b1-dirty

**Comment by Mecares** [comment]
What kind of peasant do you think we are to eat in a vehicle? Joke aside good catch it should work there.

**Comment by Mythiran** [comment]
Yep, just got the same thing with installed fancy table and seat in custom vehicle.

**Comment by misterprimus** [comment]
Your character is just such a snob, he'll only eat in a mansion's dining room at the head of a 30 ft long oak table.
