### ISSUE TITLE
Cellphone compresses batteries three-fold

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#29382]
**Describe the bug**  
A cellphone is 100mL and can hold 120 batteries that take 300mL of volume.

**Versions and configuration(please complete the following information):**
0.D-1522-gea190d32b1-dirty

**Comment by Photoloss** [comment]
This might be the only case where it can actually work IRL: *discharge* the batteries into the cellphone's integrated accumulator instead of wiring them up directly. What cellphone actually runs on commercially available battery cells to begin with?

**Comment by jeremyshannon** [comment]
Yeah, this feels like just the tip of the "batteries are weird' iceberg.

**Comment by Inglonias** [comment]
> What cellphone actually runs on commercially available battery cells to begin with?
A quick Google search reveals that [yes, this is a thing that someone made](https://www.amazon.com/SpareOne-Plus-Emergency-Mobile-Phone/dp/B00D6LNC1O), but it's meant strictly for emergencies.

Considering how handy it feels like it would be to be able to just have a phone run off of batteries you can buy pretty much anywhere, I wonder why nobody has tried this yet?

**Comment by l29ah** [comment]
In fact i'm using ![my cute n900](https://dump.bitcheese.net/files/avijeju/n900-cutie.jpeg).

**Comment by l29ah** [comment]
Turns out mp3 players are even better at battery compression.
