### ISSUE TITLE
It is possible to use frozen water to wash filthy clothes

### ISSUE THREAD

**Issue by Flutterlice** [CleverRaven/Cataclysm-DDA#29391]
**Describe the bug**  
It is possible to use washboard near toilet containing frozen water

**To Reproduce**  
1. Self explainatory

**Versions and configuration(please complete the following information):**
 - Linux
 - Game Version: 0.D release
 - Graphics version: Terminal
 - Mods loaded: dda, filthy clothes

**Comment by ifreund** [comment]
Fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/28473
