### ISSUE TITLE
Butchery refuse has no calories

### ISSUE THREAD

**Issue by RedBloodCat** [CleverRaven/Cataclysm-DDA#29392]
Butchery refuse has no calories or quench, is this supposed to be like that?

checked the CDDA item browser(https://cdda-trunk.chezzo.com/ruined_chunks) and ingame, i would exspect it to have some calories(say around 10)  but there is no

 - OS: Windows 10
 - Game Version: 0.d-1062-g14a0cbf

**Comment by KorGgenT** [comment]
yes. it's not a bug. it's supposed to be that. it's not supposed to be edible.
