### ISSUE TITLE
Segmentation Fault on New Game world generation

### ISSUE THREAD

**Issue by EnclaveA** [CleverRaven/Cataclysm-DDA#29395]
Game version:
Experimental 0.D-1561-ge1615c1 build #8741 

Operating system:
Windows 10

Tiles or curses:
Tiles

Mods active:

Dark Days Ahead
Craftable Gun Pack
Safe Autodoc
Bright Nights
Dark Days Ahead; Lua
Dark Days Ahead: Lua (Fun)
Dark Days Ahead: Lua (Skills)
Dark Days Ahead: Lua (Traits)
Armor Up! PA Utilities
Armor Up! Survivor Expansion
Bens GF recipes
Bootleg Walkers
Craft Ammo Mags & Belt Links
Extended Realistic Guns
Craft Ammo Mags - ERG
DeadLeaves' Fictional Guns
 Garden Pots
Icecoon's Arsenal
Makeshift Items Mod
Medieval and Historic Content
No Freeze
Packaging
Storage Battery Conversions
DinoMod
Draco's Dog Mod
Modular Turrets
PKs Rebalancing
Salvaged Robots
Alternative Map Key
Cataclysm ++
Crazy Cataclysm
Mutant NPCs
Beta National Guard Camp, Aggregate's edit
Big River Building Pack
More Locations
Fuji's More Buildings
Mapgen Demo
More City Locations
Urban Development
Boats
Folding Parts pack
Tanks and Other Vehicles
Arcana and Magic Items
Necromancy
Artyoms' Gun Emporium - Reloaded
Whaley's Big Ol' Building Pack
Classes and Scenarios Mod
Manual Bionic Installation
Mutation Changes
Simplified Nutrition
Sleep Deprivation
Stats Through Skills
Wintertime Classes
### Expected behavior
World gen loads without crashing to segmentation fault, usually it loads with some errors but that hasn't stopped it from working before.
### Actual behavior
[https://gyazo.com/a241c14e6a657aae7f02d2248a151d74](url)
As seen in the provided picture, once the generating reaches the Items section it crashes to segmentation fault.
### Steps to reproduce the behavior
Download my cdda folder and run it for yourself, the mods should all be in order there and there should be a world already made.

Anyhow I'm gonna troubleshoot each of my mods one by one, that usually fixes it. Thought you guys should still see this in case this is something different then a mod problem.

File https://mega.nz/#F!eBpQWQII!W3Ja_HbzcYa9ydov4lsRrQ

**Comment by ZhilkinSerg** [comment]
You didn't provided a savegame/world settings.

**Comment by EnclaveA** [comment]
Sorry I was setting up a Mega account, it should be there now.

**Comment by EnclaveA** [comment]
Troubleshooted and found the problematic mod. It was PKs Rebalancing.

I'm gonna check to see if it didn't update or what not.

**Comment by kevingranade** [comment]
Just a side note, any LUA based mods are not going to work.
