### ISSUE TITLE
Option to change the loot table from left to right

### ISSUE THREAD

**Issue by TommyGun3211** [CleverRaven/Cataclysm-DDA#29415]
Is your feature request related to a problem? Please describe.
While this is not a major problem by a wide margin, it is rather difficult to adjust to the new loot table. Back then every information is relayed on the table to the right. Now with the newest update, whenever you want to check an item on the ground your head need to be jerked to the left to see everything. Ergonomic wise it was a bit uncomfortable. I think the loot table in the old version works really well so far.

Describe the solution you'd like
While i think some might like this feature, i think removing this entirely is not necessary. I would love it if there's simply an option to move the loot table back to the right. the 'classic' mode.

Describe alternatives you've considered
So far the solution above is the only one i have, i don't think it's removing anything. just adding an option for the user interface.

Additional context
Here is the screenshot provided of the current loot table on the left.
![123123](https://user-images.githubusercontent.com/49436426/55804467-8755f680-5b06-11e9-8703-43d67a4079b7.png)

**Comment by CoroNaut** [comment]
I cannot find the PR that changed this in the first place, if someone finds the person who did this to begin with, pinging them is the right choice to get this fixed.

**Comment by KorGgenT** [comment]
> I cannot find the PR that changed this in the first place, if someone finds the person who did this to begin with, pinging them is the right choice to get this fixed.

no it is not

**Comment by CoroNaut** [comment]
How so? Their PR would be able to tell us alot about how they moved it and provide insight into making an option for it.

**Comment by esotericist** [comment]
> How so? Their PR would be able to tell us alot about how they moved it and provide insight into making an option for it.

To expand on what Korg was saying: Looking for someone to nag who may or may not be around anymore or may not be involved in that subset of the project is generally a good way to make someone less inclined to help you, as a rule.

It's an open source project. If someone wants to extend the framework to add an option that currently doesn't exist, the right thing to do is to attempt to add it. If for some reason the person wanting the feature is not in a position to do that work themselves, making sure that the request is in the issue tracker with all of the information necessary for that to be done is the next best right thing to do.

As for this specific issue: 
We don't currently have the appropriate framework to do this right. The change is a consequence of having to re-implement things for the new sidebar layout. There's a good bit more involved than just "add an option to swap what side it's on".

It'd be a good thing to have, but it's not a matter of "look at what was done before and conditionally un-do it".

**Comment by CoroNaut** [comment]
I understand what you are saying and have been here for quite some time. I also realize the difficulties of the sidebar implementation. I usually ask in the same manner when I'm at work, so I didn't think twice about the phrasing.

I assumed it wasn't this large an issue because the examine menu would simply overlap the tiles that consisted of the main sidebar, but I suppose there's something I'm unaware of.

**Comment by CoroNaut** [comment]
I would still like to see the PR or initial issue to look at the code myself, I'm just curious, but for someone willing to solve this issue, it would be helpful.

**Comment by Petethegoat** [comment]
I like the sound of this, might look into it. I think I'd want three options of left, right, or right, but not overlapping the main sidebar.

**Comment by Petethegoat** [comment]
Right aligned, right sidebar:
![right aligned](https://user-images.githubusercontent.com/734762/61930503-8de86c80-af43-11e9-8ec1-82cf8114395c.png)
Overlapping, with left sidebar:
![overlapping](https://user-images.githubusercontent.com/734762/61930539-abb5d180-af43-11e9-9dd1-a0016248831a.png)

And obviously it can do the old setup too.

Will make a PR soon, but be warned that it may not be merged until work is done to make the options less of a mess. I'm interested in fixing that too, but I'm pretty new and I don't know how long I'll take.
