### ISSUE TITLE
Add effect to the character when he is not happy nor sad

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#29412]
I am making player expressions now, and got in to problems. I can make character sad or happy, and their face in the game will change accordingly, but i have no ID for when character do not feel happy or feel sad.
Sadly i cant make normal expression the default look of the player, cause it will mess with his eyes and skin color.
So i am requesting some hidden status effect ID when character has this " :l " in his mood status.

**Comment by Night-Pryanik** [comment]
No discussion in over two years, closing.
