### ISSUE TITLE
Crash while crafting!

### ISSUE THREAD

**Issue by Necrosian** [CleverRaven/Cataclysm-DDA#29414]
**Describe the bug**  
Game crashed while cooking 2x fruit leather. Crafting sweet water doesn't seem to crash the game, also single crafting works too. 

**To Reproduce**  
1. Start crafting fruit leather/lentils/cooked fruit.
2. Game crashes.

**Screenshots**  
Crash : 
![Capture](https://user-images.githubusercontent.com/26538192/55802438-e9036a00-5ae0-11e9-8b42-26ee883bc925.PNG)
Screen : 
![screen](https://user-images.githubusercontent.com/26538192/55802451-f15ba500-5ae0-11e9-9073-6eb9041e2bde.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 x64
 - Game Version: 0.D-1629-g7e1a5c0
 - Build: 8745 
 - Graphics version: Tiles
 - Mods loaded: 
Disable npc needs,
(DP_RP)Remix Indicator,
Vehicle Addition pack,Tanks and Other Vehicles, Folding parts Pack,
Urban Development,More Locations,Fuji's More Buildings,
Mutant NPCs,Alternate Map key,
More Survival Tools, Makeshift items mod,
No Fungal Monsters,
Sleep deprivation

**Additional context**  
Save: [Morgan Mill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3059089/Morgan.Mill.zip)

*Crash log:*
 CRASH LOG FILE: config/crash.log
VERSION: 0.D-1629-g7e1a5c0
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x557FA5[cataclysm-tiles.exe+0x157FA5]
    @0x558B52[cataclysm-tiles.exe+0x158B52]
    SMPEG_error+0x4B034@0xE44C70[cataclysm-tiles.exe+0xA44C70]
    _C_specific_handler+0x98@0x7FFAB31E8068[msvcrt.dll+0x28068]
    _chkstk+0x11F@0x7FFAB47F468F[ntdll.dll+0xA468F]
    RtlWalkFrameChain+0x14BF@0x7FFAB4754BEF[ntdll.dll+0x4BEF]
    KiUserExceptionDispatcher+0x2E@0x7FFAB47F33FE[ntdll.dll+0xA33FE]
    @0x7109B6[cataclysm-tiles.exe+0x3109B6]
    @0x710BBE[cataclysm-tiles.exe+0x310BBE]
    @0x732E54[cataclysm-tiles.exe+0x332E54]
    @0x543955[cataclysm-tiles.exe+0x143955]
    @0x537A3D[cataclysm-tiles.exe+0x137A3D]
    @0x53B342[cataclysm-tiles.exe+0x13B342]
    @0x69ED8A[cataclysm-tiles.exe+0x29ED8A]
    @0x6800B7[cataclysm-tiles.exe+0x2800B7]
    IMG_LoadWEBP_RW+0x4DFD39@0x1416819[cataclysm-tiles.exe+0x1016819]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFAB1B581F4[KERNEL32.DLL+0x181F4]
    RtlUserThreadStart+0x21@0x7FFAB47BA251[ntdll.dll+0x6A251]

**Comment by neitsa** [comment]
I could repro; here's the full stack trace:   

    Address	Module	Function
    000000000061C8E6	cataclysm-tiles.exe	item::is_food(void)const+0xE
    000000000061C952	cataclysm-tiles.exe	item::goes_bad(void)const+0xC
    000000000061C97C	cataclysm-tiles.exe	item::get_relative_rot(void)const+0xC
    0000000000632DDE	cataclysm-tiles.exe	item::item(recipe const*,long,std::__cxx11::list<item,std::allocator<item>>)+0x1D4
    00000000004D823F	cataclysm-tiles.exe	player::start_craft(recipe const&,int,bool)+0x193
    00000000004CF137	cataclysm-tiles.exe	craft_command::execute(void)+0x685
    00000000004D1AD3	cataclysm-tiles.exe	player::make_craft_with_command(string_id<recipe> const&,int,bool)+0x113
    00000000004D1AFE	cataclysm-tiles.exe	_ZN13QFSFileEngine4openE6QFlagsIN9QIODevice12OpenModeFlagEEP6_iobuf_1+0x20
    00000000004D1CE8	cataclysm-tiles.exe	player::craft(void)+0x46
    00000000005CC5BB	cataclysm-tiles.exe	def_5C783F+0x33A0
    00000000005A110F	cataclysm-tiles.exe	game::do_turn(void)+0x617
    00000000010CAEB2	cataclysm-tiles.exe	_main+0x195A
    00000000004013E2	cataclysm-tiles.exe	___tmainCRTStartup+0x272
    00000000764B0179	KERNEL32.dll	kernel32_BaseThreadInitThunk+19
    0000000077E5662D	ntdll.dll	0000000077E5662D
    0000000077E565FD	ntdll.dll	0000000077E565FD

ECX (`this*`) is 0 / null in  `item::get_comestible`:

```
.text:0061C022 ; _DWORD item::get_comestible(item *__hidden this)
.text:0061C022 public __ZNK4item14get_comestibleEv
.text:0061C022 __ZNK4item14get_comestibleEv proc near
.text:0061C022
.text:0061C022 var_1C= dword ptr -1Ch
.text:0061C022 this= dword ptr  4
.text:0061C022
.text:0061C022 mov     eax, [ecx+9Ch]  ; ecx = 0
```

I haven't investigated further.

**Comment by Fris0uman** [comment]
Same crash while crafting coffee milk ( same  build)

**Comment by ifreund** [comment]
Alright, I'm 90% sure this happens when `get_most_rotten_component()` returns a `nullptr` having not found any components which go bad.  Just need to add a check for this case.

Thanks for the stack trace @neitsa!
