### ISSUE TITLE
Minefields can spawn on roofs

### ISSUE THREAD

**Issue by Ilysen** [CleverRaven/Cataclysm-DDA#29420]
**Describe the bug**  
Roof tiles can have minefields on them. This happened with the home improvement superstore, so I'm not sure if it can happen on others.

**To reproduce**  
1. Become a US general.
2. Go incredibly overboard with defending from criminals.
3. Have the Cataclysm happen.
4. Go to a home improvement superstore roof and admire your handiwork.

**Expected behavior**  
For minefields to not spawn on rooftops.

**Screenshots**
![image](https://user-images.githubusercontent.com/47678781/55815492-7386a200-5abe-11e9-96c7-4c8b841bc16d.png)
![image](https://user-images.githubusercontent.com/47678781/55815651-ad57a880-5abe-11e9-9f5d-8bb906c01af8.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1549-g71b58ff
 - Graphics version: Tiles
 - Mods loaded:
```
  "dda",
  "aftershock",
  "makeshift",
  "More_Survival_Tools",
  "alt_map_key",
  "boats",
  "deoxymod",
  "despoiled",
  "no_npc_food",
  "filthy_morale",
  "manualbionicinstall",
  "safeautodoc",
  "novitamins",
  "No_Anthills",
  "nomolerats",
  "craftgp",
  "growable-pots"
```
(Despoiled just removes the spoilage timers on some foods.)

**Comment by curstwist** [comment]
That's a new one. I've seen artifacts, body sites also spawn up there.

**Comment by chaisawlajatang** [comment]
It may be a tactical solution to prevent airdrops. Someone placed mines on a possible drop location, some dirt for disguise and voila, a nasty surprise for enemy paratroopers!

**Comment by Ilysen** [comment]
I guess that explains the floating sign just to the right of the screenshots...!

**Comment by evil-toe-puppet** [comment]
Hi, 
**Describe the bug**
i have a the same roof minefield stuff just on a Farm/ Green house roof with floating warning signs
![grafik](https://user-images.githubusercontent.com/53195771/61663854-d39dfe80-acd1-11e9-807e-6d0b3a66a2e3.png)
Versions and configuration(please complete the following information):

    OS: Windows 7
    Game Version: 0.D-3611-g47d604b
    Mods loaded: 
![grafik](https://user-images.githubusercontent.com/53195771/61664460-144a4780-acd3-11e9-8a8e-199b627f6c53.png)

**Comment by anothersimulacrum** [comment]
Minefields should only spawn at bridge entrances now, so unless you can confirm this on a more recent version, this issue should be closed.

**Comment by anothersimulacrum** [comment]
Minefields should only spawn at bridge entrances now (as of #31088), so unless you can confirm this on a more recent version, this issue should be closed.
