### ISSUE TITLE
Autofire recoil is weird

### ISSUE THREAD

**Issue by chaisawlajatang** [CleverRaven/Cataclysm-DDA#29424]
**Describe the bug**  
When autofiring, bullets fly on a wide cone, basically hitting **everything** except the target, not even close. It looks like character just not able to hold up the gun at all or maybe he swings it side to side in a Rambo style. And it happens regardless of skill or upgrades or anything.

**To Reproduce**  
1. Make a player with an auto-capable gun, magazine, and some ammo.
2. Set a gun to autofire.
3. Aim at zombie (or debug monster, or anything).
4. Watch a nice wide cone of bullets going nowhere.

**Expected behavior**  
Autofire should hit **mostly** the target. What happens now could happen on low skill levels, or low strength or with extremely heavy gun or something, but a skilled shooter should be able to concentrate his hits to a certain degree. Which degree is "certain" and what is "skilled" is discussable for sure.

**Additional context**  
Looking to previous issues, it might occur due to recoil accumulation algorithm. I know this issue had been discussed for a good couple of times, but it still **persists** and renders autofire, machine guns and related stuff practically useless.

**Comment by chaisawlajatang** [comment]
So, how I **think** it should be gameplay-wise:

A character with 8 Str, Dex and Per, armed with non-upgraded M4A1, ammo is .223 Remington. Max range 26, Burst size 14. Skill = Marksmanship and Rifles of the same level (i.e. Skill 3 means Marksmanship 3 and Rifles 3). "Hit" means total hit chance (including headshot and graze).

 - Skill 0. Up to 5 tiles - 10-15% hits, 5-15 tiles - 5-10% hits, 15-25 tiles - <5% hits, 25-36 tiles - about 0-5% hits.
 - Skill 3. Up to 5 tiles - 60-40% hits, 5-15 tiles - 30-40% hits, 15-25 tiles - 20-40% hits, 25-36 tiles - <20% hits.
 - Skill 6. Up to 5 tiles - 60-80% hits, 5-15 tiles - 50-60% hits, 15-25 tiles - 40-60% hits, 25-36 tiles - <40% hits.
 - Skill 8. Up to 5 tiles - 80-100% hits, 5-15 tiles - 70-80% hits, 15-25 tiles - 50-70% hits, 25-36 tiles - 40-50% hits.

Shorter bursts may be more accurate accordingly. Strength could also affect this proportionally.

I pick those numbers due to reasonability of autofire at all, because with current to-hit chances there's no reason to use autofire. It's loud, it consumes a lot of ammo and requires to reload faster, so it has to be at least somewhat efficient.

If there's a skilled marksman here or someone familiar with the topic or anyone with suggestion how it should be, please feel free to correct me.

**Comment by nexusmrsep** [comment]
Also, if mechanically possible, it wouldn't hurt to allow bullet to pass the target's tile without hitting (can be visually enhanced by a "miss" animation) and flying further off. It would allow much narrower cones without  misinterpretation of hitting the target itself. Can be also applied for subsequent targets on tiles the bullet passes through, some check if it also missed or it hit the secondary target. This might even be some kind of solution for more granular approach to NPC friendly fire problem.

**Comment by Adevald** [comment]
I think the core problem of lowering autofire decoy, is potentially proportionally lowering of difficulty when player gets some automatic rifle. At the same time to solve this problem, it will need to change the difficulty of the fighting so that it doesn't affect to the difficulty of fighting without automatic weapon. But just lower damage is dumb decision.

**Comment by kevingranade** [comment]
This is working as intended. For more effective gunfire, we can redo burst fire to fire smaller groups, but the fact that it accumulates like this is intended.

The width of the cone is also intended, accuracy levels, including those from recoil, are intentionally exaggerated to differentiate between different gun types within the restricted range we have to play with.

Bullets *can* pass through an occupied square without hitting a monster, there is only about a 50% chance of a hit vs a medium sized monster when a round passes through an occupied square.

**Comment by Firestorm01X2** [comment]
@kevingranade 
>This is working as intended

Wait. Then you've closed my issues, you argumentation was **compeletely** different.

You've asked some kind of data fro me. And after that current situation suddenly become **intended**?

In this case if I am jerk then who are you?
