### ISSUE TITLE
House spawned with lava seam in basement

### ISSUE THREAD

**Issue by StrongEUW** [CleverRaven/Cataclysm-DDA#29431]
**Describe the bug**  
Generic house spawned with lava seam in basement, instant death on descent with no warning.

**To Reproduce**  
Load game in the attached save file, descend stairs.
[Lumberton2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3061196/Lumberton2.zip)

**Expected behavior**  
There is not a lava seam in a basement, or if there is, there is at least a warning about it. 

**Screenshots**  
![2019-04-09 23_03_35-Cataclysm_ Dark Days Ahead - 0 D-1522-gea190d3](https://user-images.githubusercontent.com/49459628/55838885-d4919280-5b1d-11e9-9f35-9db6f09ebe3d.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-1522-gea190d3
 - Graphics version: Tiles
 - Mods loaded: dda, disable NPC needs (default)

**Additional context**  
Experimental Z-levels were not enabled. Possibly related to #29420 .

**Comment by Zireael07** [comment]
For some reason, I think this was already reported but a loooong time ago?

**Comment by I-am-Erk** [comment]
I'm not sure this is a bug, so much as really awful luck.

**Comment by StrongEUW** [comment]
I believe it was a descent into the flames rather than the lava itself - on the initial occurrence, I was able to reascend the stairs before dying a couple of minutes later from the injuries. My understanding was that:

a) you should get a message upon descending into any situation like that.
b) lava seams like that aren't intended to be spawnable in 'standard' subterranean locations anyway.

I'm unsure about b) after the rework since it was coded out for Z-levels above 0 as per #24459, so I would figure that coding it out for Z-levels below 0 would have come with that; if it is intended behaviour now, it should probably still do a) somehow (checking the 8 surrounding tiles for lava instead of just the one immediately below I would presume? not 100% sure how the check is coded)

**Comment by I-am-Erk** [comment]
I think lava seams can spawn just about anywhere. (A) is definitely a problem, I'm fairly sure the game won't warn you before you descend into a fire whether or not z-levels are enabled.

**Comment by Amoebka** [comment]
Why do underground lava rifts exist in the first place? They seem to serve absolutely no purpose except regularly overlapping with other map features and breaking the game as a result. I remember reading complaints like this one before many times, with labs, and even before that with missile silos.

**Comment by I-am-Erk** [comment]
They exist because exposed pools of lava are really cool.

You don't hear about them when they work fine, in the majority of cases, because nobody pops in to say "fyi saw a lava rift and nothing was wrong with it, just thought you should know"
