### ISSUE TITLE
Impossible to disassemble vehicle in player faction camp garage expansion (0.D Build 8752)

### ISSUE THREAD

**Issue by midnightrayne** [CleverRaven/Cataclysm-DDA#29448]
**Describe the bug**  
When I wanted to diassemble vehicles in my player faction camp garage (Chop Shop Mission in the garage expension) nothing happens. No crash, no promt to select a NPC, no message, no error, just nothing in return. I tested this in Build 8737 and in Build 8752.

**To Reproduce**
Start a player faction camp (or use your existing one)
Build garage so you are able to disassemble vehicles
Put a vehicle in a garage overmap tile
Examine the Bulletin Board and start Mission Chop Shop in the Garage Expansion
Nothing happens

**Expected behavior**
The Game should open a dialog option to choose a NPC for the Mission and afterwards start the disassembly.

**Versions and configuration:**
OS: Windows 10
Game Version: 0.D-1653-g9ab8172 (tiles) - Build 8752
Graphics version: Tiles
Mods loaded: DDA, Disable NPC Needs, Filthy Clothing, Garden Pots, Mythological Replicas, Mutant NPCs, Mythical Martial Arts

**Comment by ifreund** [comment]
possibly related to #28239, though not a crash report.

**Comment by Mythiran** [comment]
Same problem here using latest build. Also, my garage is fully upgraded. Chop shop option just does nothing.

**Comment by davidpwbrown** [comment]
Was a typo, ( needed a space in a string, and it wasnt there )
