### ISSUE TITLE
0.D Upgraded solar panels working well even in complete darkness

### ISSUE THREAD

**Issue by Ystyr** [CleverRaven/Cataclysm-DDA#29443]
**Describe the bug**  
Upgraded solar panels working in the cloudy day, night, and even indoors.
**To Reproduce**  
1. Build a generator indoors
2. Expand it outside the building
3. Build upgraded solar panels outside and indoors 

**Expected behavior**  
Solar panels working well on a clear day, not so good on a cloudy day, and not at all at night and/or in a dark building.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D release version
 - Graphics version: Terminal
 - Mods loaded: [
  "dda",
  "no_npc_food",
  "filthy_morale",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "FIC_Weapons",
  "growable-pots",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "mutant_npcs",
  "more_locations",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "Urban_Development",
  "boats",
  "blazemod",
  "Tanks",
  "necromancy"
]

![Untitled](https://user-images.githubusercontent.com/6534608/55890040-990dcb80-5be4-11e9-8b75-b24857fd1cc3.png)

**Comment by mlangsdorf** [comment]
is the battery actually charging, or is the vehicle interaction menu just displaying how stuff would be charging if you were in sunlight?

**Comment by Ystyr** [comment]
It is actually charging. Infinite energy! ;p

**Comment by mlangsdorf** [comment]
Moonlight is up to 10% of sunlight, which is necessary for the vision code but not quite right for the solar panel code.
