### ISSUE TITLE
Auto-wield items in-progress crafting items if hands are free and there's insufficient inventory space

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#29442]
**Is your feature request related to a problem? Please describe.**  

Right now if a character starts crafting an item but don't have the inventory space it gets dropped on the floor. This happens even if the character's hands are free, and results in two extra steps, one to manually wield the in-progress item, and a second to re-start the crafting process.

**Describe the solution you'd like**  

If there's insufficient inventory space to hold the in-progress item, give the player the option to wield it instead, similar to what we do when trying to pick up an item. If the character has nothing wielded, then auto-wield the in-progress item. In both cases crafting should auto-continue.

**Describe alternatives you've considered**  

Allow crafting to continue for items dropped on the floor.

**Comment by ifreund** [comment]
Certainly will add this soon, just have a long todo list right now.  I'm going to try and get workbench mechanics wrapped up before addressing this since that pr adds infrastructure for crafting from the map.

**Comment by Zireael07** [comment]
I would go with the alternative, continue crafting items dropped instead of auto-wielding. Auto-wielding might rob you of your actual weapon, y'know.

**Comment by ifreund** [comment]
Yeah, that was my thought as well, and the workshop pr makes that possible which is why I plan to wait.
