### ISSUE TITLE
Trying to construct Faction Camp expansion on tile with vehicle, then moving vehicle causes unusable tile with partial constructed expansion.

### ISSUE THREAD

**Issue by Mythiran** [CleverRaven/Cataclysm-DDA#29455]
**Describe the bug**  
Unusable constructed expansion (not recognized from faction camp BB menu) appears from steps below.

**To Reproduce**  
Park vehicle on tile east of main camp.
Send NPC to survey.
Attempt to make a Blacksmith on that tile.
Get error message (cannot merge with vehicle).
Move vehicle.
Go back to bulletin board, try again... this time a tile shows with a constructed Blacksmith, but it is not recognized by the menu as functioning... cannot build on tile as it says it's not a field any more. Surveyor is still in the ether (although can be returned by constructing an expansion on a different tile.

**Comment by ifreund** [comment]
Related to #26341.  Leaving this open as I don't think there's a standalone issue for this yet.

**Comment by mlangsdorf** [comment]
The day when camps can be upgraded with vehicles on the map - like every other map in the game - is in sight.  I'm not going to spend too much time debugging this because I'm going to apply a much better fix with a different set of bugs instead.

**Comment by I-am-Erk** [comment]
>I'm going to apply a much better fix with a different set of bugs instead.

That's the spirit!
