### ISSUE TITLE
Salvaged Robots Mod, follower AI acts strangely.

### ISSUE THREAD

**Issue by Rosethorns** [CleverRaven/Cataclysm-DDA#29479]
**Describe the bug**  
The AI that the Salvaged Robots use seems to act bizarrely. For example a floating furnace while following you may teleport underground if you pass over an area with a underground space, ironicly the bot has trouble following /you/ across Z levels and will not go down or up stairs after you. (with experimental Z levels on, have not tested without) Also the bot will stop following you if monsters are nearby.

**To Reproduce**  
For Z level bug
1. create a salvaged bot with no weapon for best results.
2. activate the bot and travel over an area. above a lab is a good place to see this.
3. the bot will teleport into chambers below you as you travel over the area.
For follow bug.
1. create a salvaged bot with no weapon for best results
2. activate the bot and approach an area with known hostiles. A lab autodoc room is good for this.
3. The bot will become distracted and will not continue to follow you.

**Expected behavior**  
The salvaged bot to remain on your Z level and to follow you correctly, and across Z levels.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1513-g0194338
 - Graphics version: Tiles
 - Mods loaded: filthy clothing, makeshift items mod, more survival tools, mutant npcs, npc traits, zetsukaze's hair extensions, alternative map key, more locations, fuji's more buildings, urban development, boats, folding parts pack, vehicle additions pack, tanks and other vehicles, (DP_RP) xotto indicators, whaleys tattoos and scars, classes and scenarios mod, statsthroughskills, modular turrets, salvaged robots

**Additional context**  
save link
https://drive.google.com/file/d/1wKxUfpWPLhTr3WnIQISwzsSm0u6NOGjr/view?usp=sharing

there should be a floating furnace on the ground south of where you load, and a atomic sultan in the south west cargo carrier. West is a cold lab. running directly west toward the lab with the furnace bot active should almost immediately show the z level behaviour

**Comment by Rosethorns** [comment]
Stale bot is threatening this issue I see it has been marked but has it been investigated at all? is it safe for this to be forgotten?

**Comment by anothersimulacrum** [comment]
Stale issues are not forgotten, they're just not actively being worked on.

**Comment by Rosethorns** [comment]
![image](https://user-images.githubusercontent.com/2171914/63389118-d68a2d00-c3fe-11e9-86cc-e823be8213ae.png)

**Comment by anothersimulacrum** [comment]
[Stale issues are still considered](https://github.com/CleverRaven/Cataclysm-DDA/issues/32475#issuecomment-522299323). That text is a little out of date.

**Comment by kevingranade** [comment]
Please don't bump stale issues.
