### ISSUE TITLE
Add new trait that gives a small morale bonus after killing monsters.

### ISSUE THREAD

**Issue by JerreeLynn** [CleverRaven/Cataclysm-DDA#29474]
**Is your feature request related to a problem? Please describe.**  
Some individuals may find satisfaction in killing zombies and monsters. 

**Describe the solution you'd like**  
Add a new trait that gives a small morale bonus after killing a monster. Could call it "Bloodlusted" or something like that.

**Describe alternatives you've considered**  
Maybe even make a morale penalty when you haven't killed something in a while.

**Comment by nexusmrsep** [comment]
Call it "murderer" or "butcher". Conflicts with pacifist. And add it at random to convict profession. Make NPCs trust you less as they feel awkward being near you. Fun idea. I like it.

**Comment by Rail-Runner** [comment]
Might also give additional morale bonus if the monster is killed in a "bloody" way which badly damages or destroys the corpse.

**Comment by Bulletfang** [comment]
My recommendation for a name would be "Sadistic". But it's a good idea regardless, dispatching of dangerous enemies should yield some kind of satisfaction, maybe even baseline without a trait, and the trait can just amplify the effect.

**Comment by paulenka-aleh** [comment]
Dunno if it should be a pre-requisite or if it should stack with Psychopath, but definetly should interfere

**Comment by cosmo-naut** [comment]
Would this counter morale deficits caused by killing children, the same way hunter and it's derivatives currently work?
