### ISSUE TITLE
Linter line wrapping causing problem with visual flow of json files.

### ISSUE THREAD

**Issue by zombiethoughts** [CleverRaven/Cataclysm-DDA#29492]
**Describe the bug**  

Using the linter causes an issue with visual flow in json files.

**To Reproduce**  

Open /data/json/vehicles/bikes.json as an example.
Look at the "parts" section before and after linting.

**Expected behavior**  

Linting should properly keep the visual flow of the document.

**Screenshots**  
Before:
<img width="1275" alt="Before Linting" src="https://user-images.githubusercontent.com/295691/56050914-b3de5e00-5d12-11e9-9903-5414af6e7eac.png">

After:
<img width="928" alt="After Linting" src="https://user-images.githubusercontent.com/295691/56050925-be98f300-5d12-11e9-904b-1a7d596f8f81.png">

**Versions and configuration(please complete the following information):**
Using the online linter located here.
http://dev.narc.ro/cataclysm/format.html

**Additional context**  
Hopefully this doesn't affect previously linted files.
If it does, just throw them back in the blacklist.

**Comment by kevingranade** [comment]
First, I'm assuming you think it should leave this chunk formatted as in the "before" screenshot?

Do you have any suggestions for how to make this happen?

How it works is it formats a json entity, if outputting that entity on the current line results in a line more than 120 characters long, it redoes it with a "force wrap" flag, which means it outputs each sub-entity on it's own line.  while doing that it repeats the same logic, so if a sub-entity would result in a too-long line, that one gets split too.  Entities that can't be split like strings aren't even checked, though they can end up as the only entity on a line.

Specifically, this line from quad_bike:
``    { "x": 1, "y": 0, "parts": [ "frame_cover","engine_vtwin", "alternator_motorbike", "battery_motorbike", "headlight", { "part": "tank_small", "fuel": "gasoline" }, "plating_steel" ] },``
is 208 characters long.  We're not going to bump the line length that long, no way no how.

I'm pretty skeptical of not wrapping this line, period, it's just way too long.

An alternative is that I believe this specific entry *might* be splittable, so you can maybe do this manually:
```
    { "x": 1, "y": 0, "parts": [ "frame_cover", "engine_vtwin", "alternator_motorbike", "battery_motorbike" ] },
    { "x": 1, "y": 0, "parts": [ "headlight", { "part": "tank_small", "fuel": "gasoline" }, "plating_steel" ] },
```

**Comment by zombiethoughts** [comment]
I mentioned this in #mod-and-dev-general and iFreund asked me put it up as an issue. 

I wanted to know if what was happening was acceptable behavior. If the visual flow is okay to split the line like the example above, I have no problem with that, and I'll continue linting what's left in the blacklist.

As far as the alternative you've mentioned, I could give it a shot and see if it works if you would prefer that.

**Comment by kevingranade** [comment]
Splitting the line would be fine, as you point out we aren't just ticking a checkbox here, we want everything to be readable.
If that doesn't work... I dont have an alternative.

**Comment by zombiethoughts** [comment]
Yep, splitting the line the way you showed seems to work fine. I'll start modifying as I catch them.
