### ISSUE TITLE
Giant worms have loud footsteps

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#29490]
**Describe the bug**  

Giant worms have reasonably loud footsteps when they move about, even though they (presumably) don't have feet.

**To Reproduce**  

1. Travel around the world until you find evidence of a giant worm.
2. Listen carefully.
3. Footsteps!

**Expected behavior**  

Giant worms make a different sound. Maybe a slithering one, or perhaps no sound at all? Worms are pretty quiet.

**Versions and configuration:**
 - OS: Ubuntu 16.04
 - Game Version: 0.D-1693-g9a54f07b7f
 - Graphics version: Tiles
 - Mods loaded: None

**Comment by kevingranade** [comment]
I agree the description needs changing, but I'm pretty sure earthworms are
only quiet because of size.
https://www.wired.com/2014/03/absurd-creature-week-earthworm-backup/
Dog-sized worms would be quite loud.

**Comment by pjf** [comment]
@kevingranade : Oh gosh, today I learned what giant worms sound like. Thank you! :)
