### ISSUE TITLE
Reheating large quantities of food locks the player in place for huge amounts of time

### ISSUE THREAD

**Issue by Ilysen** [CleverRaven/Cataclysm-DDA#29494]
**Describe the bug**  
When reheating or defrosting large amounts of food, such as a jerrycan of water, the player is stuck doing this for an immensely long amount of time, unable to respond to being attacked or otherwise threatened.

**To Reproduce**  
1. Fill a 60L tank or other large container with liquid.
2. Wait for the liquid to freeze in cold temperatures.
3. Defrost the liquid, and see yourself locked in place.

**Expected behavior**  
Defrosting, reheating, etc. can be canceled, or has a cap on the amount of time it takes from you.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D
 - Graphics version: Tiles
 - Mods loaded: Default

**Additional context**  
I imagine that this functions because the method to reheat foods probably uses an algorithm to subtract moves from the player, but that this algorithm has no upper bound on the moves it can subtract, resulting in a gigantic amount of missing moves that has to be filled over the course of several hours. The opposite also happens with Time Dilation, providing a huge amount of moves for the player.

**Comment by Night-Pryanik** [comment]
Just another action that should be a long activity.
