### ISSUE TITLE
RC merchant second quest crash

### ISSUE THREAD

**Issue by echomirage1** [CleverRaven/Cataclysm-DDA#29503]
**Describe the bug**  
Accepting the second quest for the Refugee Center merchant crashes to desktop with segfault.

**To Reproduce**  
1. Go to RC.
2. Accept ("I'll do it!") the second quest from the merchant.
3. Crash.

**Expected behavior**  
No crash.

**Versions and configuration(please complete the following information):**
 - OS: Win 7
 - Game Version: 0.D-1701-g46f5ee4
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs, No Flaming Weapons, No Survivor Armor.

**Comment by neitsa** [comment]
Thanks for your bug report! Do you have a save file please?

**Comment by mlangsdorf** [comment]
Fixed in #29473 - bug was trying to substr("field", 6) in the update_mapgen rotation check.
Thanks for volunteering to look at this, neitsa.

**Comment by Night-Pryanik** [comment]
@echomirage1 could you please update and confirm if this is still an issue on latest version?

**Comment by echomirage1** [comment]
Today I've updated to the latest experimental, can accept the mission without crash.
