### ISSUE TITLE
Craft entity can't be wielded with one hand

### ISSUE THREAD

**Issue by Break-Off** [CleverRaven/Cataclysm-DDA#29500]
**Describe the bug**  
When the player character has a broken arm, they can't wield the craft entity introduced in https://github.com/CleverRaven/Cataclysm-DDA/pull/28937. Therefore, they can't craft.

**To Reproduce**  
1. Try to batch-craft anything heavy or large enough that a player with disabled arms drops it in the ground.
2. Wield the item.
3. An error will appear notifying the player that he can't wield the craft entity.

**Expected behavior**  
Craft entities can be activated regardless of player's wielding capacity.

**Screenshots**  
![image](https://user-images.githubusercontent.com/5843433/56060089-1280f780-5d66-11e9-8ebc-509d0c7138e4.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1701-g46f5ee4
 - Graphics version: Tiles
 - Mods loaded: `[
  "dda",
  "no_npc_food",
  "filthy_morale",
  "ew_pack",
  "alt_map_key",
  "mutant_npcs",
  "npc_traits",
  "more_locations",
  "deoxymod",
  "blazemod",
  "Tanks",
  "no_olg_guns",
  "no_flaming_weapons",
  "more_classes_scenarios",
  "safeautodoc",
  "no_pipe_guns",
  "growable-pots",
  "modular_turrets",
  "Salvaged_Robots",
  "boats",
  "manualbionicinstall"
]`

**Comment by ifreund** [comment]
This will be fixed by #29434
