### ISSUE TITLE
The new interface is very slow

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#29509]
**To Reproduce**  
1. Grab i5-3320M CPU and urxvt
2. Ride a car @64kph through a forest
3. It takes around four seconds every `.`turn with a terminal visibly redrawing each frame.

**Expected behavior**  
Every turn taking less than half a second like it used to.

**Versions and configuration(please complete the following information):**
 - OS: Gentoo
 - Game Version: 0.D-1718-g1f89a2dc6d-dirty
 - Graphics version: Terminal
 - Mods loaded: dda, boats, aftershock, bright nights

**Comment by spacenookie** [comment]
are you compiling from source or using the download? I had an issue with compiled running slow that disappeared when I switched to the download.

**Comment by kevingranade** [comment]
Not reproduceable.
