### ISSUE TITLE
Segfault on loading save (provided)

### ISSUE THREAD

**Issue by micrem** [CleverRaven/Cataclysm-DDA#29518]
**Describe the bug**  
Crash on loading save file, w10 tiles x64 and 
x32

**To Reproduce**  
1. Load save file

**Expected behavior**  
No crash

**Screenshots**  
![image](https://user-images.githubusercontent.com/43637388/56078443-646a6180-5de8-11e9-82ac-8825911ce2d0.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1739-gc00528a
 - Graphics version: 
Tiles
Mods: 
```
[
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "realguns",
  "More_Survival_Tools",
  "makeshift",
  "growable-pots",
  "blazemod",
  "Tanks"
]
```

**Additional context**  
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3076089/save.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3076092/crash.log)

**Comment by AMurkin** [comment]
Can confirm on linux. Rev c00528a
Segfaults on [line](https://github.com/CleverRaven/Cataclysm-DDA/blob/c00528a4ff1009debff84ecf182ec9fdcd5f5d57/src/activity_handlers.cpp#L2396)
```cpp
const auto f = target->faults.find( fault_id( act->name ) );
```

```
#0  activity_handlers::mend_item_finish (act=0x5555588744a8, p=0x555558871680) at src/activity_handlers.cpp:2396
#1  0x00005555558633e2 in std::function<void (player_activity*, player*)>::operator()(player_activity*, player*) const (this=<optimized out>, __args#0=<optimized out>, __args#0@entry=0x5555588744a8, __args#1=<optimized out>, __args#1@entry=0x555558871680) at /usr/include/c++/7/bits/std_function.h:706
#2  0x0000555555862be4 in activity_type::call_finish (this=<optimized out>, act=act@entry=0x5555588744a8, p=p@entry=0x555558871680) at src/activity_type.cpp:96
#3  0x0000555555dc2ef4 in player_activity::do_turn (this=0x5555588744a8, p=...) at src/player_activity.cpp:123
#4  0x00005555559c8e17 in game::process_activity (this=0x5555569f76a0) at src/game.cpp:1558
#5  0x00005555559ea4ae in game::do_turn (this=0x5555569f76a0) at src/game.cpp:1369
#6  0x0000555555801530 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:682
```
Activity name is "fault_engine_immobiliser"
