### ISSUE TITLE
Internal Furnace CBM bug with consuming tools that have batteries.

### ISSUE THREAD

**Issue by PMajesty** [CleverRaven/Cataclysm-DDA#29522]
**Describe the bug**  
The Internal Furnace CBM consumes only a variable amount of battery charges (3 in cordless drill, 30 in cellphone, 6 in handheld game system etc) and does not consume the tool, but gives bionic power as if the whole tool is consumed and extra for some reason (up to 60% more I think). For example: "Cordless drill 300/300 consumed by Internal Furnace CBM, player recieves 300+ bionic power, item changes to Cordless Drill 297/300. Player can proceed to consume the drill a hundred times for roughly 30000 bionic power."

**To Reproduce**  
1. Make a player with Internal Furnace CBM, give them a cordless drill item with full charge (300/300).
2. Try to consume the cordless drill item.
3. Player gains bionic power as if consumed whole drill (300+), drill loses only 3 points of batteries and remains intact (297/300). Player can continue to consume the drill a hundred times.

**Expected behavior**  
The drill (or any consumable with charges) should be consumed and the batteries should be destroyed/unloaded after the first time, as the batteries themselves ARE NOT consumable by Internal Furnace.

**Screenshots**  
1. I consume phone with 120 charges
2. Phone doesn't disappear, gives a lot of power (comparatively)
3. Lastly I unload the phone and consume it without batteries (notice the low power gain):
4. Phone disappears.

![123](https://user-images.githubusercontent.com/46195466/56080729-71e61280-5e0d-11e9-90a8-168ef47ab36e.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1706-g7023fc4
 - Graphics version: Tiles
 - Mods loaded: dda, disable npc needs, filthy clothing, aftershock, craftable gun pack, safe autodoc, bright nights, bens gf recipes, deadleaves' fictional guns, extended realistic guns, garden pots, icecoon's arsenal, makeshift items mod, medieval and historic content, modular turret, salvaged robots, dinomod, more survival tools, alternative map key, mutant npcs, more locations, fuji's more buildings, urban development, boats, folding parts pack, vehicle additions pack, tanks and other vehicles, arcana and magic items, artyom's gun emporium - reloaded, classes and scenarios mod, classig roguelike classes, prevent zombie revivification, sleep deprivation, statsthroughskills, extended_buildings, mythical martial arts, pks rebalancing, beta national guard camp, mapgen demo, no survivor armor no acid zombies, manual bionic installation.

**Comment by Dacendeth** [comment]
This happens with everything with charges for me, tailor kits for example.
