### ISSUE TITLE
Materials from grenade dissasembly are not in line with crafting requirements.

### ISSUE THREAD

**Issue by Mythiran** [CleverRaven/Cataclysm-DDA#29539]
**Describe the bug**  
You can currently craft a grenade with 1 pilot light, 1 long string, 1 tin can,, 30 nails and some
gunpowder... but disassembly gives 2 RDX (as well as pilot light and empty canister)! The craft for this only takes 5 minutes, whereas crafting RDX itself takes over an hour (for 5 units)

This means you can essentially produce RDX from 1 long string, 30 nails, and some gunpowder in much less time than making it with hexamine and chemical components. 

**To Reproduce**  
Make a grenade.
Disassemble it.
Get 2 RDX... from 5 minutes!

**Expected behavior**  
Presumably, either RDX should be craft-able from gunpowder and a handful of nails in less than 5 minutes, or this kind of 'makeshift grenade' should be a separate entity.

**Comment by thquinn** [comment]
Seconding makeshift grenades, with worse damage. These improvised explosives I'm making with duct tape, nails, and 00 shot seem awful effective right now.
