### ISSUE TITLE
Unable to repair installed swappable storage battery

### ISSUE THREAD

**Issue by SkuliAdams** [CleverRaven/Cataclysm-DDA#29548]
**Describe the bug**  
When a damaged swappable storage battery is installed into a swappable storage battery case in a vehicle, and one tries to repair it, they are unable to do so. On my current vehicle, the storage battery is the only damaged part, and I am told that "there are no damaged parts on the vehicle"

**To Reproduce**  
1. Install a storage battery case in a vehicle
2. Install a damage storage battery in the case
3. Attempt to repair battery

**Expected behavior**  
The vehicle should recognize that the battery is damaged, and allow you to repair it. Alternatively, if this is intended behavior, the player should be told that it cannot be repaired while inside the swappable storage battery case.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-1630-g7f245f8
 - Graphics version: Tiles
 - Mods loaded: dda, disable npc needs, generic guns, makeshift items mod, medieval and historic content, mutant npcs, mythical martial arts, boats, vehicle additions pack, tanks and other vehicles, no fungal monsters.

**Additional context**  
To clarify, installed storage batteries can be repaired so long as they are not installed as a swappable storage battery in a case.

**Comment by CoroNaut** [comment]
#21897 and #19451

**Comment by SkuliAdams** [comment]
#29552, issue now obsolete.
