### ISSUE TITLE
Slimesprings spawn even when Very hungry/very thirsty

### ISSUE THREAD

**Issue by CyborgSlime** [CleverRaven/Cataclysm-DDA#29545]
**Describe the bug**  
I have a Slime Mutant With Omnicellular.  Current game version 8776.
Eating/drinking anything if you are not malnourished spawns a slimespring. Even if your character is Very Hungry/Very thirsty and you only eat/drink a small amount.

**To Reproduce**  
1. Make a player (I used Unwilling Mutant).
2. Use the Debug menu to grant Aqueous then Omnicellular. (Have to select OminiCellular twice, I think it grants the prereq the first time)
3. Using the debug menu set your Hunger to 200. (Or wait to get that hungry)
3. Wish for potato chips
4. Eat the chips. You will spawn a slimespring despite being Very Hungry.

To test cause. 
1. Edit Stored kCal in your needs menu to 60000 This will give you Malnourished.
2. Eat/drink anything you want. Until malnourished goes away you won't spawn slimesprings.

**Expected behavior**  
I don't know precisely which version broke it but it seems related to the new stomach mechanics. (How when drinking you slowing get less thirsty rather than instantly)
-I would expect it to work the way it did before where only if you Overeat or Overdrink will you spawn a Slimespring. Instead of getting full you pop out a slime and get hungrier/thirstier.
-Alternatively, with the new mechanics I would not mind if there were a cap of your stored kCal that spawned slimes but it should then spawning a slime should drain the stored kCal rather than your hunger/thirst.  As it stands my slime character can't get out of thirsty/hungry without me manually draining his stored kCal so I can drink and eat without popping out a slime. -Very frustrating to be Very Thirsty, drink water, then be dehydrated :(

**Versions and configuration(please complete the following information):**
 - OS:  Windows 10
 - Game Version: 0.D-1739-gc00528a
 - Graphics version: Tiles
 - Mods loaded: Only core in my test world

**Comment by KorGgenT** [comment]
ok. should be a pretty easy fix to drain stored kcal instead of hunger. i don't know why i did that in the first place. thanks for finding it!

**Comment by ktoma36** [comment]
Something else that I found is that once you dip into parched every time you try to drink something you produce a slimespring. This leads to a downward spiral until you die of dehydration. I got to this point by consuming a lot of high kcal and low thirst stuff (root beer, lemonade, other such drinks you can find from a vending machine) and despite chugging down clean water like a fish they end up keeling over.
