### ISSUE TITLE
Taking out Road Roller's wheels

### ISSUE THREAD

**Issue by scanevaro** [CleverRaven/Cataclysm-DDA#29547]
**Describe the bug**  
Even if having an Internal Boom Crane, that has 40 Jacking, it doesn't show the possibility to take out the 60´´ Roller Drums.

**To Reproduce**  
1. Find/Spawn Road Roller
2. Add Internal Boom Crane
3. Try to take out Wheel.

**Screenshots**  
https://ctrlv.cz/shots/2019/04/14/98AS.png
https://ctrlv.cz/shots/2019/04/14/gznD.png

**Comment by esotericist** [comment]
The boom crane text explicitly says "another vehicle". Try it with the boom crane on a different vehicle (and still near this one) and tell us if that works.
