### ISSUE TITLE
Batch crafting allows crafting without enough items and returns item labeled 'none'

### ISSUE THREAD

**Issue by zombiethoughts** [CleverRaven/Cataclysm-DDA#29556]
**Describe the bug**  

When crafting some items in batch. It will allow you to craft without necessary ingredients, leaving you with an item named 'none'

**To Reproduce**  

1. Batch craft 2 chest ammo pouches with only 5 leather. But enough rags to make 2.
2. Select leather to craft with.
3. Ignore the errors.
4. Get your 'none' item.

**Expected behavior**  

That the ability to craft with 8/5 leather would not be an option.

**Screenshots**  
![Chest ammo pouch 8 out of 5 small](https://user-images.githubusercontent.com/295691/56087486-15491e80-5e32-11e9-8f86-479ee7a8398e.png)

<img width="556" alt="Chest ammo pouch error" src="https://user-images.githubusercontent.com/295691/56087492-2560fe00-5e32-11e9-9b50-c7cbe3272774.png">

<img width="626" alt="Chest ammo pouch error 2" src="https://user-images.githubusercontent.com/295691/56087495-28f48500-5e32-11e9-9721-dad4da32a9fd.png">

<img width="318" alt="Chest ammo pouch log" src="https://user-images.githubusercontent.com/295691/56087497-2d20a280-5e32-11e9-95a0-11ca66048427.png">

<img width="195" alt="Inventory item none" src="https://user-images.githubusercontent.com/295691/56087511-4e818e80-5e32-11e9-890a-b6acf930c31f.png">

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1748-g38a2ebc
 - Graphics version: Tiles
 - Mods loaded: "no_npc_food","filthy_morale", "alt_map_key", "mapgen_demo", "more_locations", "FujiStruct", "StatsThroughSkills"

**Additional context**  

Save game link.

https://www.dropbox.com/s/2h9shewrvi7qyx8/save.zip?dl=0

**Comment by ifreund** [comment]
Thanks for the save man, turns out it was the filthy leather patches lying around your base that were the key to reproducing it.

**Comment by zombiethoughts** [comment]
Glad my filthy base helped you figure out what was going on. Time to hire a maid.
