### ISSUE TITLE
skinning zombifed animal yield no skin

### ISSUE THREAD

**Issue by Leviathan21** [CleverRaven/Cataclysm-DDA#29551]
**Describe the bug**  
title

**To Reproduce**  
1. kill z animal
2. skin one
3. have no skin through corpse reads that its skinned

**Comment by kevingranade** [comment]
It's intentional that they drop no skin, the bug is that it allows you to
try.

**Comment by Rivet-the-Zombie** [comment]
We're not doing tainted hides/pelts any more?

**Comment by kevingranade** [comment]
Hrm, I stand corrected, these are supposed to yield raw_tainted_leather

**Comment by Night-Pryanik** [comment]
Fixed by #34221.
