### ISSUE TITLE
Indicator not showing on Terrain Editor

### ISSUE THREAD

**Issue by InsanityComplx** [CleverRaven/Cataclysm-DDA#29555]
**Describe the bug**  
Title

**To Reproduce**  
1. Make a World and Character.
2. Load up the map.
3. Open Debug menu and the Terrain editor.
4. No indicator shows.

**Expected behavior**  
An indicator to show me where my cursor is.

**Screenshots**  
http://prntscr.com/nbn4af
(For reference the indicator should be showing to the right of the closest Pine Tree.)

**Versions and configuration(please complete the following information):**
 - OS: Win 10
 - Game Version: 0.D-1748-g38a2ebc
 - Graphics version: Tiles

**Comment by CoroNaut** [comment]
#29111
