### ISSUE TITLE
Failing to Craft returns Frozen Water outside of container in Inventory

### ISSUE THREAD

**Issue by EirenexTheDragon** [CleverRaven/Cataclysm-DDA#29569]
**Describe the bug**  
failing to craft an specific item ( lets say tallow)  gives back the water, but not back into the container from where it came it. so now the water is in the inventory and about to spill in the next turn

**To Reproduce**  
1. a Container with water , a tool for cooking and a heat source
2. Start Crafting a Item that uses water as ingredient ( i used Tallow)  and repeat crafting until failing
3. on fail, you receive the water outside of the container 

**Expected behavior**  
The water to be either used up, or returned from the original container it was drawn from 

**Screenshots**  
![grafik](https://user-images.githubusercontent.com/41762755/56094089-71fb1680-5ed0-11e9-84a1-e5a5fad980ec.png)

**Versions and configuration(please complete the following information):**
 - OS: Win 7 
 - Game Version: O.D-1760-g3ef243b
 - Graphics version: Tiles
 - Mods loaded:  
  "dda",
  "blazemod",
  "Tanks",
  "deoxymod",
  "boats",
  "more_locations",
  "FujiStruct",
  "mutant_npcs",
  "alt_map_key",
  "More_Survival_Tools",
  "Medieval_Stuff",
  "makeshift",
  "realguns",
  "No_Fungi",
  "manualbionicinstall",
  "safeautodoc"

**Additional context**  
I also think it happened, because my cold water has become frozen aswell during crafting, but i am not sure exactly on that. If so, i rename the title.
Turns out its indeed related to the water becoming frozen.

**Comment by eliotcougar** [comment]
I have been struggling with this too today... Some weird stuff is happening since most crafting has been moved to "batch has been queued, press a, and activate craft in progress" design... Couldn't craft a kitchen unit because I'm unable to pick up the huge "craft in progress", it doesn't fit in inventory, and some other small issues...

**Comment by pjf** [comment]
Confirming this as well. I'm asked what to do with the returned water (which was from a lake), and pouring it onto the ground oddly results in negative volume:

![That water is worth how much?](https://user-images.githubusercontent.com/12072/56268900-c4893c80-6135-11e9-9a86-6e355f29f6a3.png)

**Comment by ifreund** [comment]
seems like this only happens when the liquid freezes.  The weird stuff that happened with crafting from an infinite map water source should be fixed by #29823

**Comment by EirenexTheDragon** [comment]
I will the name of the issue thus.
