### ISSUE TITLE
CTD While driving

### ISSUE THREAD

**Issue by Allmyusualnamesaretaken** [CleverRaven/Cataclysm-DDA#29562]
**Describe the bug**  
Game consistently crashes while driving

**To Reproduce**  
1. Load game
2. Start vehicle and turn on headlights
3. Drive northeast or east
4. Game crashes after several screen lengths

**Expected behavior**  
Ideally, game should probably not crash

**Screenshots**  
CRASH LOG FILE: config/crash.log
VERSION: 0.D-1760-g3ef243b
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x4D1830[cataclysm.exe+0xD1830]
    @0x4D1B7A[cataclysm.exe+0xD1B7A]
    @0xAC9035[cataclysm.exe+0x6C9035]
    UnhandledExceptionFilter+0x1A0@0x77A45F10[KERNELBASE.dll+0x195F10]
    RtlCaptureStackContext+0x1E521@0x77CEDA71[ntdll.dll+0x9DA71]
    RtlAreBitsSet+0x58@0x77CB4198[ntdll.dll+0x64198]

**Versions and configuration(please complete the following information):**
 - OS: Win10
 - Game Version: 0.D-1760-g3ef243b
 - Graphics version: Terminal
 - Mods loaded: "dda",
  "no_npc_food",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "deoxymod",
  "no_mutagen",
  "no_olg_guns",
  "No_Fungi",
  "more_classes_scenarios",
  "manualbionicinstall",
  "safeautodoc",
  "novitamins",
  "StatsThroughSkills"

**Additional context**  
I initially noticed the problem with a version from 4/1, and tried updating to correct but it persisted. I've also found with continued experimentation that if you walk several screens to the east, then come back and drive in the same direction, the issue doesn't occur. I'll attach a copy of my save as this seems weirdly specific. EDIT: Apparently you have to have the headlights on and be driving northeast or east

[Eastgate.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3077085/Eastgate.zip)

**Comment by ipcyborg** [comment]
Can't reproduce in 0.D-6237-g7682029.
Tried to drive all the way northeast to the city, and then through it. Then tried to just drive back and forth to northeast or east.
Headlights on, no crash.

**Comment by kevingranade** [comment]
Unteproduceable
