### ISSUE TITLE
Fungal environment spawned in lab in world with No_Fungi mod

### ISSUE THREAD

**Issue by communistkiro** [CleverRaven/Cataclysm-DDA#29570]
**Describe the bug**  
In a lab-escape, starting out as a broken cyborg; at -5 the lab was fungal-ized, floors and walled have been transformed into fungal floors and walls and fungal clumps covered items and, if destroyed, spreading to select surrounding tiles. I even get the `spore dusted` effect, although I haven't explored fully, I saw utility bots and zombie scientists in the first 4 rooms.

No_Fungi, the mod by Chaosvolt (who I have no idea who to contact) included in the normal distribution as a blacklist mod, should blacklist the monsters, monster groups, and regions in the fungal category. It is lastly loaded in this world.

**To Reproduce**  
Get lucky to find a fungal environment in a lab on a lab-escape scenario..?

**Expected behavior**  
No fungal environments, effects, monsters.

**Versions and configuration**
 - Win 7 Pro
 - Game Version: 0.D-1739-gc00528a
 - Graphics version: tiles
 - Mods loaded: ["dda", "aftershock", "DP_REMIX_INDICATORS", "more_locations", "FujiStruct", "FIC_Weapons", "realguns", "SD_Magcrafting_Realguns_Extension", "ew_pack", "nw_pack", "crazy_cataclysm", "alt_map_key", "modular_turrets", "Salvaged_Robots", "no_npc_food", "safeautodoc", "manualbionicinstall", "novitamins", "mutant_npcs", "dda-lua", "dda-lua-fun", "dda-lua-skills", "dda-lua-traits", "modi", "no_freeze", "No_Fungi"]
  
modi is a collection of json balances that are to my liking, none have to do with environments, monsters, etc.

**Comment by DoctorGoat** [comment]
Can absolutely confirm this happens. Did yours have a portal near it?

**Comment by communistkiro** [comment]
@DoctorGoat Like a trap? I didn't smash all the fungal clumps to find see what I could be missing. I don't know if items are visible without smashing them, but I have 4 PER and some condition for even less.

**Comment by Adomatic** [comment]
This still happens in 0.F-2, fully two years after this patch was merged.

**Comment by ZhilkinSerg** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/pull/51620
