### ISSUE TITLE
Auto-sort infinite loop/game hang

### ISSUE THREAD

**Issue by Warlander** [CleverRaven/Cataclysm-DDA#29573]
**Describe the bug**  
When you sort items on the ground, in some circumstances game will enter infinite sorting loop and finally hang forever. I'm not sure what's the exact cause, but I'm supplying world with this bug present.

**To Reproduce**  
Steps to reproduce the behavior (in this specific case):
1. Download, put world in proper directory and launch it
2. Press auto-sort key (default "O")
3. Watch character being stuck in infinite sorting loop and finally hanging the game

**Expected behavior**  
No infinite sorting loop or hanging happens, loot is sorted.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-1789-gc0d27c5
 - Graphics version: Tiles
 - Mods loaded: visible in attached world

**Additional context**  
World file: 
[Matherville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3077604/Matherville.zip)

**Comment by ifreund** [comment]
Possibly related to #28571.  I noticed that the caching in `ACT_MOVE_LOOT` got effectively disabled by that pr, but haven't gotten around to doing anything about it yet.

Could also be an unrelated bug though.
