### ISSUE TITLE
homemade halfpike seems poorly balanced

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#29578]
Homemade halfpike vs wooden spear
halfpike requires
  more skill
  significantly more time (10x)
  more tools (hammer 2 vs nearby fire)
  more resources (3x of auxiliary, adds spike)
  loses blocking ability

In exchange it has 22 damage per hit instead of 18, but 20% more moves per attack for a dps gain of 2%

In addition the slower attack makes it much harder to dance on the edge of the zombie range.

Generally I would expect greater cost (or significantly greater cost in this case) to come with a commensurate increase in value.  Not perfectly, for sure but at least some.

But in this case Halfpike seems like either a sidegrade (more damage per hit, for slower attack) or measurably worse (more costly, loses block, harder to dance)

**Screenshots**  
-----------------------------------
![image](https://user-images.githubusercontent.com/12039454/56098030-cdb5a780-5eb0-11e9-8024-8166d3452da5.png)
-----------------------------------
![image](https://user-images.githubusercontent.com/12039454/56098036-d5754c00-5eb0-11e9-8be7-b2e647d7ba2e.png)
-----------------------------------

 - Game Version: 0.D-1706-g7023fc4
 - Mods loaded: ask if need

**Comment by Xpyder** [comment]
Maybe it could be sturdy so it breaks less often?  a wooden point isn't going to last very long, though a wooden spear should still last longer than a pointy stick.

**Comment by jeremyshannon** [comment]
I'd add that more damage per hit for a slower attack is usually a poor trade, too.

**Comment by Xpyder** [comment]
It seems to be intended as an upgrade to Knife Spear but needs to be stronger than it currently is (relative to the other reach weapons) given it's materials.

Maybe make it durable, and give Pipe Spear a similar treatment (that one does more damage and hits faster than this, but requires welder so would be an upgrade to this effectively)
