### ISSUE TITLE
Web spiders should be more passive.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#2957]
As pointed out on the forums by RadaRadaRada http://smf.cataclysmdda.com/index.php?topic=3106.msg45409#msg45409, it doesn't make sense that web spiders are so agressive.  Possibly limit them to walking on webs?
##

**Comment by ituluwituluwzev** [comment]
Closing - No active discussion for over a year. Feel free to reopen if there's still interest.
