### ISSUE TITLE
Lithium Ion batteries should decay over time

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#29587]
In commit #29552 Kevin indicated large storage batteries should be closer to real lithium ion batteries.  This would also mean all large storage batteries need to stop working after around the 4th in game year (at the latest) even if unseen and unused

https://electronics.howstuffworks.com/everyday-tech/lithium-ion-battery2.htm

Lithium-ion batteries age. They only last two to three years, even if they are sitting on a shelf unused. 

Other research sources indicate the same.

**Comment by Xpyder** [comment]
Kevin being @kevingranade who seems to be the core maintainer

**Comment by KorGgenT** [comment]
so... what would they be replaced with? if batteries stop working, and gas stops working, then a major part of the game (vehicles) is reduced to bicycles if you play long enough? i know realism is important, but that just sounds like a punishment for playing the game in a good way (long in-game time)

**Comment by kevingranade** [comment]
You can mass craft biodiesel, we also have steam engines now, horses and wagons are doable.  Maybe add more stable high density batteries as a rarer drop.

A major part of the post-apocalyptic narrative is the surprising number of things that stop working once civilization and industry fall apart, but that alternatives are waiting in the wings.

**Comment by drayath** [comment]
For a real world degradation example for something like Large Storage Batteries, Telsa claim an 8 year lifetime for there battery packs (with lifetime defined as reduced to 70% of max capacity).

Was also mentioned that could still be usable for static installation (where cheapness of second hand batteries trumps power storage density) for another 8+ years with a similar rates of max power degradation.

**Comment by paulenka-aleh** [comment]
Once this is implemented it will bring attention to alternative way of energy storage. There are a lot of creative ideas over the Internet (though little of them are suitable for vehicles and two-way radios). Even within game there are conventional car batteries that have a bit differnt characteristics. I suppose huge non li-ion batteries can be later added to labs, ship wreakages and trains where weight and energy density isn't much of concern. Some limited sci-fi storages can be added to labs, e.g. small (non-craftable) supercapacitors or finales with huge immobile SMES (especially well fits for ice labs given supercoductors require extremly freezing temperatures). Also gives a reason for surivor to look for plutonium...

A question though. Is bionic power storage is also based on li-ion batteries and thus would render most of bionics useless in a long run?

**Comment by Uesrnme** [comment]
For consistency, gas storage life then have to be taken into account.

> The storage life of petrol is one year when stored under shelter in a sealed container. Once a seal is broken the fuel has a storage life of six months at 20°C or three months at 30°C. The storage life of petrol in equipment fuel tanks is one 
[https://www.bp.com/content/dam/bp-country/en_au/products-services/fuels/opal-fuel/Opal-factsheet-storagehandling.pdf](url)

**Comment by Zombiemanpig** [comment]
> so... what would they be replaced with? if batteries stop working, and gas stops working (mentioned elsewhere as a possibility), then a major part of the game (vehicles) is reduced to bicycles if you play long enough? i know realism is important, but that just sounds like a punishment for playing the game in a good way (long in-game time)

Not sure if it's only from the vech additions mod but nuclear power is usually the best :)

**Comment by paulenka-aleh** [comment]
> Not sure if it's only from the vech additions mod but nuclear power is usually the best :)

It's in the main game... However minireactors generate electricity which has to be stored somewhere at least temporarely and than used by electric motors to drive the vehicle. So it relies on batteries too.

**Comment by Zombiemanpig** [comment]
Perhaps the best solution would be to put in "advanced" batteries that people created using secret science not available to the public and thus not requiring a "realism" explanation.

**Comment by Fris0uman** [comment]
>Once this is implemented

It might be better to start adding alternatives befores making the current battery perishable. But then again 8 years of life seems like a very long time in game.

**Comment by Mcrone617** [comment]
Could this also be something that factions could deal with in the (very) long term? Assume you side with the old guard or the robot faction, and help them reclaim a factory, with great cost you should be able to produce large scale batteries like this. It's a contrast, as the lone survivor/mutant monstrosity has to rely on salvaged decaying tech, but those who side with a powerful and technologically focused faction should get some benefits like this.

**Comment by tenmillimaster** [comment]
@Mcrobe617 I would think that in the long term, any faction with the will to do so would focus on Nickel metal hydride chemistry, due to its relative abundance as compared to lithium.
