### ISSUE TITLE
standing on the edge of the roof should be unsafe

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#29581]
**Describe the bug**  
If I'm on a roof and rapidly hitting movement commands, I can easily jump off without intending to, even with Safe Mode on.

**To Reproduce**  
start at shelter
break into roof
walk off in safe mode

**Expected behavior**  
Just like stepping into a fire, stepping onto the edge of the roof should be an Unsafe activity, and you should be prompted for certainty if you have Safe Mode active

**Versions and configuration(please complete the following information):**
 - Game Version: 0.D-1706-g7023fc4

**Comment by Xpyder** [comment]
Note: I haven't actually tried to jump off.  Only noticed that when I accidentally walk to the edge I get a message "you try to keep your balance", which on the edge of the roof seems precarious

**Comment by curstwist** [comment]
Gutters have unstable footing like rubble piles. I dont think they can actually make you stumble off the ledge though ( I'd fully support that functionally). If you do try to walk off, I think you get a warning,  you definitely get the warning if you examine the adjacent open air,  like you want to climb down.

**Comment by kevingranade** [comment]
Please actually verify that there's a problem before opening an issue.
