### ISSUE TITLE
Wooden Dowels?

### ISSUE THREAD

**Issue by InsanityComplx** [CleverRaven/Cataclysm-DDA#29580]
**Is your feature request related to a problem? Please describe.**  
I'm playing in an Innawoods game and nails take so much time to make.

**Describe the solution you'd like**  
Perhaps the addition of wooden dowels would be efficient for innawoods players. Perhaps to balance them out they could be heavier that regular nails, and take around the same amount of time to make.

**Describe alternatives you've considered**  
Lower the craft time of Nails? Though I think the addition of Dowels would be a more realistic choice.

**Comment by curstwist** [comment]
Good idea, think it should require glue/bone glue too.

**Comment by Rail-Runner** [comment]
Well, the problem with this would be that if you construct something using dowels, then you can later deconstruct/smash it to turn dowels into actual nails. Making a separate constructable version of every terrain/furniture that uses nails doesn't seem like a good way to handle it.

**Comment by JerreeLynn** [comment]
> Well, the problem with this would be that if you construct something using dowels, then you can later deconstruct/smash it to turn dowels into actual nails. Making a separate constructable version of every terrain/furniture that uses nails doesn't seem like a good way to handle it.

Could allowing constructions to store the materials used similar to how some crafts store the materials used (and can be disassembled back into them) be a potential solution?

**Comment by cosmo-naut** [comment]
Are there any conceivable 'alternate' methods of crafting nails?
Perhaps involving bolt cutters and some form of metal object. 
Wire could be used and also require a heat source and water to harden the metal.
Nail mould maybe? Takes a similar time but gives a larger batch

**Comment by Scischm** [comment]
> Are there any conceivable 'alternate' methods of crafting nails?

I really like this line of thinking. I think that having tools or even machines to speed up production of slow crafting objects (with an appropriate resource cost/investment) would be a great thing to look into. The biggest downside would be trying to manage the repetitive recipe clutter. Maybe machines that have a specific purpose could work akin to the smoking rack whereby a container inventory of items is processed.

**Comment by kevingranade** [comment]
As stated, "just replace nails with dowels", this isn't happening. There's a much more nuanced way of doing construction or crafting that doesn't use nails, and we can follow up with that.
