### ISSUE TITLE
SCT "hit marker" offset in ASCII

### ISSUE THREAD

**Issue by molkero** [CleverRaven/Cataclysm-DDA#29593]
**Describe the bug**  
While fighting, the enemys letter on red background flashes ~10 tiles the right of it.

**To Reproduce**  
1. Disable tiles
2. Find some creatures
3. Fight, look ~10 tiles to the right while doing so

**Expected behavior**  
The enemy flashes red when hit, only guessing here.

**Screenshots**  
![20190415040700_1](https://user-images.githubusercontent.com/49575273/56102642-04360580-5f37-11e9-9228-09d425793050.jpg)
![20190415040809_1](https://user-images.githubusercontent.com/49575273/56102651-0730f600-5f37-11e9-9fc5-769413f2c768.jpg)

**Versions and configuration(please complete the following information):**
 - OS: Linux
 - Game Version: 0.D-1798-gf078e2d
 - Graphics version: Tiles

**Comment by kevingranade** [comment]
Fixed by #29657
