### ISSUE TITLE
Expanded NPC offered missions

### ISSUE THREAD

**Issue by Axema** [CleverRaven/Cataclysm-DDA#29603]
**Is your feature request related to a problem? Please describe.**  
Multiple missions are not applicable for NPCs.

**Describe the solution you'd like**  
As I said in the title, NPCs will give us a more offered missions for us to partake.

**Describe alternatives you've considered** 
I was thinking of this format:

`{"type": "npc",
"id": "old_guard_soldier",
"//": "Generic guard for the old guard.",
"name_suffix": "Soldier",
"class": "NC_SOLDIER",
"attitude": 0,
"mission": 8,
"chat": "TALK_OLD_GUARD_SOLDIER",
"faction": "old_guard",
"mission_offered": [
"MISSION_OLD_GUARD_TEST_1",
"MISSION_OLD_GUARD_TEST_2",
"MISSION_OLD_GUARD_TEST_3"
]
}`

Where `"mission_offered"` is expandable with additional missions.

**Additional context**  
Instead of continuous flow of missions, why not give all at once?

**Comment by mlangsdorf** [comment]
Okay.
