### ISSUE TITLE
Add Graphics to Artifacts

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#29602]
This game desperatly needs some sort of way to draw artifacts correctly!
All i can do with my tileset is assign graphics to id's, but artifacts do not have any fixed IDs, so i cant give them any specific graphics! As a result all artfacts can only look like some one common item, and nothing else.
As i see it now artifacts are created from two words. What item it is, and what effect it posses.
It would be great i lf i somehow could make tiles for any combination of item and effect. Or maybe have some types of overlay graphics on items. Like if it is a fire sword artifact when main part of this tile is the sword, and game draws fire on that item tile as overlay for the item.
Then i can make graphic for the sword artifact template, and also for all the overlays this sword can get.
I want to show some tileset love for the artifacts. :)

**Comment by Axema** [comment]
Now we could see what an artifact really looks like!

**Comment by mlangsdorf** [comment]
I looked at assigning looks_likes to artifacts for #24758, and it turned out to be fairly complicated.  Assigning the looks_likes was very easy, getting those values to interface with the cata_tiles was not.

**Comment by SomeDeadGuy** [comment]
I still want normal tile graphics for artifacts.
