### ISSUE TITLE
Keybinding Menu crashes game

### ISSUE THREAD

**Issue by Matt-Hillesheim1** [CleverRaven/Cataclysm-DDA#29618]
Whenever you try to bind a key to an action that already has a key binding the game crashes immediately.

**To Reproduce**  

1. Create a character and open the key binding menu

2. I selected the "debug menu" option and tried to map it to (shift+8) and then immediately to "`" or tilde key without clearing the (shift+8) binding.

3. The game pops up an error message and freezes.

**Expected behavior**  
I expected the game to inform me that I must remove the existing keybinding already assigned to it and then allow me to remove the current keybinding.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 64-bit
 - Game Version: 0.D-1062-g14a0cbfa20-dirty
 - Graphics version: Tiles
 - Mods loaded: None

**Comment by esotericist** [comment]
I'm, at least, unable to reproduce this. The game allows multiple keys to be bound to a function. As a test, I just added a bunch of bindings to Debug Menu (this is on shortened commit hash bd089f01ee):

![image](https://user-images.githubusercontent.com/1569754/56167650-91a44480-5f8d-11e9-9301-b4279c9ed696.png)

I notice your version includes "-dirty". Can I ask what kind of alterations you have made to your tree?
