### ISSUE TITLE
Locked storage furniture idea that NPCs would not be able to take from.

### ISSUE THREAD

**Issue by JerryLin1** [CleverRaven/Cataclysm-DDA#29615]
**Is your feature request related to a problem? Please describe.**  
Neutral NPCs will walk through your base and take your items. The main ways to deal with this are hiding your items or killing the NPC, neither of which are elegant solutions. 

**Describe the solution you'd like**  
Add a furniture called lockbox/locked crate/locked chest that you can drop items in. NPCs will not be able to access the items on the furniture tile. It could be crafted and deployed (think brazier) or be made using the construction menu using a lock, two by fours, and a medium level of fabrication.

**Additional context**  
I know NPCs are being worked on and once player ownership is defined this won't be a problem, but this could be a simple solution for now (I don't know C++ so this might be harder than I think it is)

**Comment by 0be1isk** [comment]
it wouldn't be too hard to add, just need to add a conditional to the section from where NPCs can pick things up

**Comment by mlangsdorf** [comment]
I'm not going to stop anyone else from doing it, and if someone wants to start working on NPC AI, this is a good simple project and I'll be happy to help.  But I'm not going to work on it myself because I would rather implement ownership.

**Comment by DracoGriffin** [comment]
This feature already exists as the [cargo lock set](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/vehicle_parts.json#L2573).

However, the part can only be installed on these [vehicle storage parts](http://cdda-trunk.chezzo.com/flags/LOCKABLE_CARGO).

Duplicate of #19439.

**Comment by mlangsdorf** [comment]
This is a request for a furniture item with similar functionality.

**Comment by DracoGriffin** [comment]
> This is a request for a furniture item with similar functionality.

Whoops, you are correct. I apologize, I hastily read through this as I was already seeing quite a few similar questions on subreddit about locking stuff.

**Comment by chriseich21** [comment]
I feel it might be better if player was able to use a lock function/terrain recipe on certain objects, such as storage locker and doors, but might be better to implement after or with ownership since they're similar. Also description wise would probably be a combo lock or something similar to avoid needing a key or item to unlock it everytime. Would be interested in working on it or another simple project mlangsdorf, to begin digging into Cataclysm and contributing.

**Comment by mlangsdorf** [comment]
See #29834 - it's complicated and has lots of moving parts.

**Comment by davidpwbrown** [comment]
Is this still wanted/required now item ownership is implemented?

**Comment by korvyr** [comment]
Tagging this for this weekend or next. (The comment lets me find it again.)

Current thought process for a quick fix:
1) Create a "SECURED" tag that can be applied to furniture, and slap it on safes for good measure (gives an example, is applicable, and allows testing).
2) Modify the NPC AI behavior that goes a hunting for loot in furniture and have it check for the "SECURED" tag if it belongs to a hostile faction. If it is "SECURED" and belongs to a hostile faction, no NPC looting.
3) Test it.
4) Profit.

**Comment by Night-Pryanik** [comment]
> Create a "SECURED" tag that can be applied to furniture

There is no way to apply flags to furniture in the runtime, that's the main issue.

**Comment by korvyr** [comment]
> > Create a "SECURED" tag that can be applied to furniture
> 
> There is no way to apply flags to furniture in the runtime, that's the main issue.

Didn't plan to.

**Comment by Night-Pryanik** [comment]
Then what did you plan to?

**Comment by Night-Pryanik** [comment]
Then what did you plan to? Just set a prohibition for NPCs to check for loot? How it would be explained? Why wouldn't they want to look in some openable safe?

**Comment by korvyr** [comment]
> Then what did you plan to? Just set a prohibition for NPCs to check for loot? How it would be explained? Why wouldn't they want to look in some openable safe?

More thinking along the lines of if it's able to be secured then why would you keep it secured after each use? If you want to get into it at that point, you'd have to break into it (smash). Unless, of course, it's yours and then you'd have access.

That's why I said it would make said check for hostiles only. I suppose in that same vein I should have it equally act as "sealed" is the player attempts to access a "secured" piece of furniture that doesn't belong to them.

**Comment by korvyr** [comment]
Second post for a second thought: Along those lines, might even be worth looking at adding a lock picking check when accessing a hostile-owned secured container? Thoughts?

**Comment by Night-Pryanik** [comment]
> Short of having two objects, one for a secured state and one for an opened state?

This was always and option, of course, but this limits us to only that specific type of furniture. And we want to place a lock on any container-type furniture.

**Comment by korvyr** [comment]
> > Short of having two objects, one for a secured state and one for an opened state?
> 
> This was always and option, of course, but this limits us to only that specific type of furniture. And we want to place a lock on any container-type furniture.

Hrm, would it be possible then to have the item gen take every type of furniture marked as "LOCKABLE" or some sort in the json data and automatically generate a second, locked version of that container? I know that too is getting into the danger zone, but it would allow you to have two different "states" for a collection of objects without actually having to have two different objects defined in the json data. It would then even permit tile designers to create an open/unlocked visual version by just apply it to the different objects.

At that point you could easily type up a piece of code that, when called, "locks" or "unlocks" a piece of furniture by reaching out to its designated  and generated counterpart.

**Comment by korvyr** [comment]
This is no longer the low-hanging fruit I thought it would be, but still all for trying it.

**Comment by Night-Pryanik** [comment]
I think this is possible, but I believe it would require a lot of coding.

**Comment by korvyr** [comment]
> I think this is possible, but I believe it would require a lot of coding.

I'll give it a whirl, after I fix my big mistake on my open pull request. I'm hoping I can find a point in the furniture object generation process to hook in, check for a flag, and then generate a second item with a slightly modified ID and the flag removed.

I'd want a check to make sure the generated ID name doesn't already exist, of course. I'm excited to see if I can make it work without blowing everything up.

**Comment by Night-Pryanik** [comment]
Good luck! Looking forward for your work.

**Comment by korvyr** [comment]
It seems I sadly won't be getting to this one. I think the idea is sound, though, if anyone else wants to give it a whirl.

**Comment by kevingranade** [comment]
Stale,  and moving in the wrong direction. 
Instead of magic lockboxes that NPCs cant open (since when did that stop the player?), we need a way to mark territory (signs,  totems even) that tell NPCs to stay out.
