### ISSUE TITLE
Compass skewed by map portion under sidebar

### ISSUE THREAD

**Issue by molkero** [CleverRaven/Cataclysm-DDA#29619]
**Describe the bug**  
NPC  & zombies not showing up on compass when under the sidebar.

**To Reproduce**  
1. Find/spawn NPC or zombies.

**Screenshots**  
Bandit NPC not on compass at all.
![20190416001557_1](https://user-images.githubusercontent.com/49575273/56166693-f340cf00-5fde-11e9-9446-08fadb1c855d.jpg)
Zombie not on the compass directions.
![20190416014154_1](https://user-images.githubusercontent.com/49575273/56170232-7109d800-5fe9-11e9-8cea-c824c1e55ca1.jpg)
If you disable all sidebar panels you can see the zombie in the forest.
![20190416014244_1](https://user-images.githubusercontent.com/49575273/56170233-72d39b80-5fe9-11e9-8899-c0e6f54dda26.jpg)
NPCs to the west side seen on compass, shady zombie under sidebar.
![20190416021731_1](https://user-images.githubusercontent.com/49575273/56171620-ab29a880-5fee-11e9-87d1-ec429616cabd.jpg)

**Versions and configuration(please complete the following information):**
 - OS: Linux
 - Game Version: 0.D-1802-gbd089f0, 0.D-1803-gaf6dfe3
 - Graphics version: Tiles

**Comment by molkero** [comment]
I'm guessing the part of the map drawn under sidebar skews the compass since the zombie cop is straight north.
![20190416025519_1](https://user-images.githubusercontent.com/49575273/56173062-c5668500-5ff4-11e9-9061-e87ebf463948.jpg)

This NPC to the west appears in the compass instantly when it goes offscreen.
![20190416030255_1](https://user-images.githubusercontent.com/49575273/56173066-c7c8df00-5ff4-11e9-9c40-7ab65bd1099b.jpg)
![20190416030302_1](https://user-images.githubusercontent.com/49575273/56173069-c992a280-5ff4-11e9-9e94-ec4e5aae182f.jpg)

To the east the NPC appears in the compass only after leaving the part of the screen under the sidebar.
![20190416030335_1](https://user-images.githubusercontent.com/49575273/56173070-cbf4fc80-5ff4-11e9-80e8-c92b2ec78773.jpg)
![20190416030436_1](https://user-images.githubusercontent.com/49575273/56173073-ce575680-5ff4-11e9-9022-e808bb5ad16e.jpg)

**Comment by KorGgenT** [comment]
looks like another offset issue.
