### ISSUE TITLE
Make crates close-able

### ISSUE THREAD

**Issue by Axema** [CleverRaven/Cataclysm-DDA#29624]
**Is your feature request related to a problem? Please describe.**  
For us players who gets robbed by random NPC trespassers.

**Describe the solution you'd like**  
Make open crates close-able, in which it hides items inside and needs to be reopened by prying it.

**Describe alternatives you've considered**  
Maybe the option to close an open crate is by a hammer. (A)ctivating the hammer shows the `"close nearby crate"` as a part of its pop-up menu and will require us to have atleast 4-8 nails.

**Additional context**  
Well, crates will look like valuable chests if this happens :grin:

**Comment by l29ah** [comment]
You can seal a crate in the construction menu.

**Comment by Axema** [comment]
That's unfortunate... Thanks for letting me know :+1:
