### ISSUE TITLE
Oats progress to the next stage of growth instantly when fertilized

### ISSUE THREAD

**Issue by Probe1** [CleverRaven/Cataclysm-DDA#29638]
**Describe the bug**  
When oats are fertilized they immediately jump to the next stage.  By walking out of loaded map cell distance and then back, you can fertilize them again resulting in fully grown oats in about 30 in game minutes.

**To Reproduce**  
Plant oats using the zone manager.  Fertilize oats using the zone manager using liquid fertilizer.  Leave the current map cell and return.  Oats done grown up.

**Expected behavior**  
Seeds to have logic requiring a minimum time to pass regardless of fertilizer.
Oats to not insta grow when fertilized because their grow time short.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: O.D-1853-g9e2580e
 - Graphics version: Tiles
 - Mods loaded: Tested and replicated without mods.

**Additional context**  
Oats have a growth period of 45 days.  Fertilizer logic needs to respect a minimum transform age or alternatively (and much easier), oats can be bumped up to take longer to grow.  Compare oats to the rest of the farmable stuff.

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/comestibles/seed.json#L624
Oats growth speed.

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iexamine.cpp#L2052
Fertilizer function.

One of these two are the villain.

**Comment by ZhilkinSerg** [comment]
I cannot reproduce it on current `master`.

**Comment by davidpwbrown** [comment]
Cant reproduce. 
Fertilized oats did visually change after re-entering reality bubble, but could not be immediately fertilized again.
