### ISSUE TITLE
Basic repair kit can still reinforce items

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#29643]
**Describe the bug**  
Basic repair kit can still reinforce items made of wood, bone, paper and chitin.

**To Reproduce**  
1. Use the second option from the action menu of the kit on an applicable item.
2. It gets reinforced.

**Expected behavior**  
Shouldn't get reinforced.

**Versions and configuration(please complete the following information):**
 - OS: Win 7
 - Game Version: 0.D-1855-gfff1726
 - Graphics version: Tiles
 - Mods loaded: Default

**Comment by Night-Pryanik** [comment]
> Shouldn't get reinforced.

Is it? I believe we could actually reinforce these kind of materials.

**Comment by anothersimulacrum** [comment]
Cannot reproduce
