### ISSUE TITLE
Corpses appears in yellow even if pulped or not zombie

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#29641]
**Describe the bug**  

Corpses name appear in yelllow even if they can't revive

**To Reproduce**  

1. Get a corpse.
2. Pulp it or check that it's not a zombie corpse
3. Look at in AIM or with <kbd>V</kbd>
4. It's in yellow like an active item

**Expected behavior**  

Non active item are not yellow, pulped corpses and non zombie corpses are not active items.

**Screenshots**  
![image](https://user-images.githubusercontent.com/41293484/56230813-5719d500-607d-11e9-886e-9f7137ea1a78.png)

**Versions and configuration(please complete the following information):**
 - OS: r Windows 10 
 - Game Version:0.D-1855-gfff1726
 - Graphics version: Tiles
 - Mods loaded:  
  "dda",
  "no_npc_food"

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by echomirage1** [comment]
I get this sometimes when I gib them with car or a crit.

**Comment by Hirmuolio** [comment]
I am guessing that the corpse name is in yelow if the item is active. Now that the corpse has temperature they are all active.
