### ISSUE TITLE
Advanced inventory: exclude other vehicle slots from `all`; pet (bag) slot; category selection in advanced

### ISSUE THREAD

**Issue by communistkiro** [CleverRaven/Cataclysm-DDA#29646]
Two suggestion and one bug, all regarding the advanced inventory.
**Is your feature request related to a problem? Please describe.**  
1. Recently I had a lot to haul back home, >500lbs, lotsa volume. I had a 2-tile foldable cart. From the `(a)ll` slot in advanced I stored as much as it couch carry, 150L or whatever, switched to the second basket, and did the same from all via the move all key. I noticed the `+` on the tile, indicating items disappeared, i.e., `(a)ll` doesn't exclude vehicle storage.

2. Examining tile on which pet is doesn't prompt for possible examination of item on same tile on cancelation via escape or whatever mapped key, thus leading to having to either get it to move, shoot it, or swap positions and pick up from same tile. It'd be much easier a pets bag or inventory be accessible through the advanced inventory, the same way a vehicle's storage is.

3. Unexpected behavior or bug- toggling category selection doesn't select a category to be moved- depending on which of the 4 move keys is press, a single item, stack, or specific amount is moved, or all items on the resp. tile. The selected item has its background color turned red, and only the top and bottom items of a category can be moved, but not selected, like in normal inventory or picking up.

**Describe the solution you'd like**  
1. All should contain all items _on_ tiles 1--9, not _in_ vehicles parts on them; otherwise you can easily mistakingly loop items from vehicle storage 1 to vehicle storage 2.

2. A `p<#>` default keybinding for direct selection of inventory of pet standing on tile `<#>`; that or a keybinding to toggle between inventory of pet (or vehicle? or furniture?) and ground. Lastly, a prompt to examine ground underneath pet after cancelation of pet menu, if the player doesn't use advance inventory screen.

3. It moving everything, if there's enough room?

**Describe alternatives you've considered**  
1. Not using `(a)ll`.
2. Killing the pet, or leashing it every time it's in your way.
3. ?

**Comment by anothersimulacrum** [comment]
All should show you items in vehicles, removing that would be an incredible pain for most people that use vehicles. Perhaps an optional toggle that won't show item in vehicle tiles?

**Comment by SourSlime** [comment]
Totally agreee with anothersimulacrum. I use all for my vehicle storage very often.
