### ISSUE TITLE
Deadpeople tileset uses motorbike tire tile for off-road wide tire

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#29642]
**Describe the bug**  
The Deadpeople tileset uses motorbike tire tile for off-road wide tire, which is thinner even than a normal 17" car tire. This makes tractors look strange. A couple of weeks ago it had the same tile as the 24" wide tire, then it got changed.

**To Reproduce**  
1. Spawn in a tractor using the tileset.
2. Inspect the tires.
3. They are thin like a motorbike tire.

**Expected behavior**  
They should use the same tile as the 24" wide tire.

**Screenshots**  
![Névtelen](https://user-images.githubusercontent.com/49099349/56232062-2e470f00-6080-11e9-9452-e3b29d7045c0.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-1855-gfff1726
 - Graphics version: Tiles
 - Mods loaded: Default

**Comment by Night-Pryanik** [comment]
Closing as per lack of object of discussion.
