### ISSUE TITLE
"Random Character" main menu item doesn't randomize scenarios

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#29655]
**To Reproduce**  
1. `New Game` -> `Random Character`
2. Check the scenario picked by the RNG
3. It's always `Evacuee`

**Versions and configuration(please complete the following information):**
0.D-1835-g77b6da45ee-dirty

**Comment by curstwist** [comment]
I have gotten others, but it is heavily weighted towards Evacuee.  I recently got the winter start one (wondered why the ground what all white and the mobs were insanely evolved)...

**Comment by Night-Pryanik** [comment]
This is working as intended. You want random scenario on random character, you choose `Play Now!`.

https://github.com/CleverRaven/Cataclysm-DDA/blob/be0d5201328281e1b6dd46dd2a420f75a7eb02f7/src/newcharacter.cpp#L444-L453

>I have gotten others, but it is heavily weighted towards Evacuee. I recently got the winter start one (wondered why the ground what all white and the mobs were insanely evolved)...

It can't be. The code explicitly states that on `Random Character` the scenario will be set as `Evacuee` and nothing else.

**Comment by l29ah** [comment]
`Play Now!` doesn't let me to select world.

**Comment by Night-Pryanik** [comment]
Well, it's literally one line change. Just change `randomize( false, points )` to `randomize( true, points )` on line 445 (and update comments) and open a PR with this change if you think it should behave like that.
