### ISSUE TITLE
Survivor's Utility Belt (Holster) Cannot Hold Pistols.

### ISSUE THREAD

**Issue by Scottvrakis** [CleverRaven/Cataclysm-DDA#29661]
**Describe the bug**  
Simply put, the Sheath can hold knives/machetes but the Holster can't seem to hold any firearms.

**To Reproduce**  
1. Make a player with a gun & Survivor Utility Belt (Holster)
2. Try to holster any small firearm.
3. Firearm cannot be holstered.

**Expected behavior**  
This is pretty much self explanatory - can't holster firearms.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1860-ga011d43]
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs, Aftershock, Craftable Gun Pack, Extended Realistic Guns, Icecoon's Arsenal, Makeshift Items Mod, More Survival Tools, Modular Turrets, Salvaged Robots, Alternative Map Key, Crazy Cataclysm, Mythical Martial Arts, More Locations, Fuji's More Buildings, Urban Development, Boats, Folding Parts Pack, Vehicle Additions Pack, Tanks and Other Vehicles, Necromancy, (DP_RP) Xotto Indicators, Classes and Scenarios Mod, Classic Roguelike Classes, Manual Bionic Installation, Simplified Nutrition, StatsThroughSkills, Armor Up! PA Utilities, Armor Up! Survivor Extension, Arcana and Magic Items, Cataclysm++, PKs Rebalancing, Ascension.

**Comment by ZikoWong** [comment]
From the description, he designed it to hold tools, not guns.
Of course, that's my guess, and maybe it was a mistake.

**Comment by DSeyka** [comment]
While I think that realistically belts *could* "hold" pistols, that would make holsters less interesting of a loot.

**Comment by mlangsdorf** [comment]
"A custom-built leather utility belt covered with straps and pouches with a sheath to carry a smaller blade."

Working as designed, you're not supposed to holster pistols in it.

**Comment by DSeyka** [comment]
It probably just needs a name change to prevent confusion. It's from Aftershock though, so the mod author should be the one to decide.

**Comment by Scottvrakis** [comment]
> It probably just needs a name change to prevent confusion. It's from Aftershock though, so the mod author should be the one to decide.

Ohh I see, it's an Aftershock thing, thanks!

**Comment by Scottvrakis** [comment]
> "A custom-built leather utility belt covered with straps and pouches with a sheath to carry a smaller blade."
> 
> Working as designed, you're not supposed to holster pistols in it.

As someone mentioned elsewhere, the Holster/Sheathe versions are added by Aftershock, my bad.

**Comment by TechyBen** [comment]
As a note (I'll put a new bug report in if so) seems crafting from one to the other destroys sheathed blades if not removed before crafting?
