### ISSUE TITLE
Differentiate metal doors

### ISSUE THREAD

**Issue by Shodan14** [CleverRaven/Cataclysm-DDA#29666]
Having metal doors be the ultimite hardest to open door type feels like a product of a much earlier time.

**Describe the solution you'd like**  
I feel that there should be at least two kinds of "metal doors": 

- Normal metal security doors that are hard to open or break, but not as hard as it is now. This would be modern security doors, stuff you'd put on your jewelry shop, police station, gun store.
- Military grade vault doors for stuff like bank vaults, lab armories, barracks, military bases. These should be openable only by computer, welding or digging through the reinforced walls.

Just throwing some thoughts out there.

**Comment by cosmo-naut** [comment]
I think there's 3 kinds of metal doors you encounter at the moment.
Openable by lockpick
Openable by crowbar
Not openable by the afforementioned means

At the moment they all look the same and have the same name. I would be nice to differentiate them.

**Comment by neitsa** [comment]
@cosmo-naut From my POV, it is fine if the game internally (that is, in the code) knows which kind of door the player is facing. 

Now, IRL, if you stand in front of a metal door with a lock picking set and a crowbar, you can't tell what "kind" of door it is until you have tried (and maybe failed!).

So all in all, I think this information shouldn't available to the player.

**Comment by SourSlime** [comment]
I’m not really sure what you mean. I think it would be obvious at a glance whether or not a metal door is pickable/pryable (a door with an electronic lock cannot be opened by a lockpick)

**Comment by jeremyshannon** [comment]
Yeah, I feel like it should be obvious at a glance whether or not you would be able to jam a crowbar in to pry a door.

**Comment by DracoGriffin** [comment]
This sounds more like a tileset/graphical issue as the description should already indicate the differences. If you e`x`amine terrain, it should give you enough information to identify what actions you can take (for instance, checking windows for security stickers is helpful for determining which ones have alarms).

Generic metal door:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/terrain.json#L3071
>  "description": "An extremely resilient door made of assorted steel, carved and pounded into shape.",

Pickable metal door:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/terrain.json#L3213
> "description": "An extremely resilient door made of assorted steel, carved and pounded into shape.  This one has an extra keyhole, so it's likely locked.  You could probably pick the lock.",

Unpickable metal door (strongly hints needs computer access):
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/terrain.json#L3193
> "description": "A galvanized steel door, forged to withstand punishment and impede anyone or anything.  Typically used in conjunction with automated electronic locking mechanisms that require an external source to unlock.",

>     * Military grade vault doors for stuff like bank vaults, lab armories, barracks, military bases. These should be openable only by computer, welding or digging through the reinforced walls.

All three of these already exist.

Other than suggesting graphical differences, I'm not sure what else this Issue accomplishes that isn't already in-game.

**Comment by Night-Pryanik** [comment]
> All three of these already exist.

No it's not. No metal doors could be pryed by crowbar. Your `Generic metal door` isn't locked at all and could be opened by simple walking into it.
We have only two types - the pickable one and the unopenable one.

**Comment by nexusmrsep** [comment]
> We have only two types - the pickable one and the unopenable one.

The unopenable one can be opened by a ID card or computer console options, as they have the corresponding options to do so.

**Comment by Phenomphear** [comment]
In ASCII they all look exactly the same. A blue `+`
