### ISSUE TITLE
Liquids in attached vehicles are displayed in portions

### ISSUE THREAD

**Issue by HeadstrongCatgirl** [CleverRaven/Cataclysm-DDA#29671]
The amount of water is 60L in a separate vehicle, but 240 when it's attached to a bike rack.
That's an bit of an inconsistency.

Steps to reproduce the behaviour:
1. Create a small vehicle with a tank.
2. Put some water in that tank.
3. Examine the vehicle. The amount of water should be in liters.
3. Attach it to another vehicle through the use of bike rack.
5. Examine the vehicle again. The amount of water is in portions now.

I expect the units to be consistent no matter how the tank is attached.

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 18.04
 - Game Version: 0.D-1874-g540e41fed4
 - Graphics version: Terminal
 - Mods loaded: dda, bright nights, generic guns, makeshift items mod, more survival tools, crazy 

Screenshots:
Separate vehicles.
![Screenshot_20190417_230005](https://user-images.githubusercontent.com/27099292/56310235-d3d3ae80-6164-11e9-8ea5-c335a6c6d865.png)
![Screenshot_20190417_230026](https://user-images.githubusercontent.com/27099292/56310237-d3d3ae80-6164-11e9-9964-15abc7c1a0a7.png)
Two vehicles together. 
![Screenshot_20190417_230041](https://user-images.githubusercontent.com/27099292/56310236-d3d3ae80-6164-11e9-806a-2145d1401431.png)

**Comment by irwiss** [comment]
Carried parts (including tanks) are hidden from display in https://github.com/CleverRaven/Cataclysm-DDA/commit/057d033ec981aaf8902d3f4683d8337d49ffe4e0#diff-9fa08b2225e9d5a93c48ba623ef23eeb8d2f6352bdad5403dd6c0195a897be17R1425
