### ISSUE TITLE
Make uniform submaps Copy On Write

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#29674]
**Is your feature request related to a problem? Please describe.**  
We waste a non-trivial amount of memory because "uniform" submaps each contain a copy of the submap data, even though it's totally redundant.

**Describe the solution you'd like**  
Establish a cache of immutable uniform submaps.
When a uniform submap is generated, check for a match in the cache, if present just use that pointer, if not, insert a copy of the submap and capture the pointer.
If a uniform submap is written to, replace it with a copy of the uniform submap before writing to it.

**Comment by Maleclypse** [comment]
Closed by #63762
