### ISSUE TITLE
Craft liquid stuff successfully but get nothing

### ISSUE THREAD

**Issue by Digi1980s** [CleverRaven/Cataclysm-DDA#29677]
**Describe the bug**  
Craft liquid stuff get nothing in result.

**To Reproduce**  
1. Craft any liquid stuff, from clean water to broth to concentrated acid.
2. The log reads: "You craft (any liquid you name it) from memory."
3. Nothing obtained, though the materials has been consumed.  

**Expected behavior**  
A dialogue box ask you how to deal with the liquid crafted, consume or pour.

**Versions and configuration(please complete the following information):**
 - OS: Win10
 - Game Version: 0.D-1921-gbe0d520
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs

**Additional context**  
If you craft at the newly introduced workbench, the liquid stuff will spill on it.

**Comment by tinukedaya** [comment]
Just happened to me as well... Already dehydrated as I can't craft me any drink... ;) 
Also, if you use the "craft item" function on the table to craft the water it will spill in on the table and you get your spilled "Clean water (dirty)"
