### ISSUE TITLE
Save wont load [8799] to [8801]

### ISSUE THREAD

**Issue by Helldrone** [CleverRaven/Cataclysm-DDA#29676]
**Describe the bug**  
When updating from [8799] to [8801] my game wont load my save and throws me back to the menu, it appears updating Cata++ don't works any more as usual.

**To Reproduce**  
Update from
![image](https://user-images.githubusercontent.com/49344129/56358397-c65b0a80-61de-11e9-81d7-6485e7c75b27.png)
To 
![image](https://user-images.githubusercontent.com/49344129/56358427-d96dda80-61de-11e9-9f14-7924d4776abb.png)

**Screenshots**  
![image](https://user-images.githubusercontent.com/49344129/56358462-ef7b9b00-61de-11e9-9758-50293fb208f7.png)

**Versions and configuration(please complete the following information):**
 - OS: Win 10
 - Game Version: 0.D-1921-gbe0d520 [8801]
 - Graphics version: DEADPEOPLE
 - Mods loaded: 
![image](https://user-images.githubusercontent.com/49344129/56358755-e3dca400-61df-11e9-9d73-188d0a954873.png)

**Additional context**  
Just updating it, even updating the cata++ mod wont allow me to load my save.

**Comment by ZhilkinSerg** [comment]
That is third party mod issue which we cannot help with. Please contact mod author [here](https://github.com/Noctifer-de-Mortem/nocts_cata_mod).
