### ISSUE TITLE
Why Can Frozen Water be used to Craft?

### ISSUE THREAD

**Issue by DexterBobo** [CleverRaven/Cataclysm-DDA#29682]
I've got a container of frozen water. I can't drink it, but I can add some lemonade mix and then it magically becomes unfrozen drinkable lemonade. This seems wrong?

**Comment by thethunderhawk** [comment]
“Ice OP pls nerf”

Im pretty sure there are plans to fix this. You can use water(frozen) it to craft liquids for the same reason you can’t carry it outside of a container. That is, it’s not ice so much as water you cant consume (and can’t get out of a toilet for some reason).

**Comment by DexterBobo** [comment]
Ah, but you can get it out of toilet... by using it to craft!

**Comment by l29ah** [comment]
Only if you have something to boil it with.

**Comment by DexterBobo** [comment]
Is it different for vehicle tanks? What brought this to my attention in the first place was noticing that I could make recipes that called for clean water using the frozen clean water from my vehicle tank, but there is no way to just get clean water out of it (can't pour it from the kitchen unit faucet and can't craft "clean water" with it since the recipe requires unclean water. But if you have another tank of frozen unclean water, you can use it to craft clean water).
