### ISSUE TITLE
410-bore shotgun shells too voluminous

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#29694]
**Describe the bug**  
Empty 410-bore shotgun shells are too big (0.50L per shell), while their loaded variant is much smaller (a single loaded shell is 0.02L). 410 shells also have no crafting recipes at all.

**To Reproduce**  
1. Fire 410 ammo.
2. Gather fired shells.
3. They too big.

**Expected behavior**  
The volume of empty 410-bore shells should be somewhat more along the lines of their loaded counterparts. Also please add crafting recipe for 410 ammunition.

**Screenshots**  
![Untitled0](https://user-images.githubusercontent.com/45204409/56396701-71e87700-6240-11e9-89a0-bb8926685449.png)
![Untitled1](https://user-images.githubusercontent.com/45204409/56396709-744ad100-6240-11e9-85df-f9c6662f5d2b.png)
![Untitled2](https://user-images.githubusercontent.com/45204409/56396722-80369300-6240-11e9-907a-82d8710b0450.png)

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version: [0.D-1855-gfff1726]
 - Graphics version: [Tiles]
 - Mods loaded: [Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Just Craftable Gunpowder, Makeshift Items Mod, PKs Rebalancing, Alternate Map Key, Mutant NPCs, More Locations, Fuji's More Buildings, Urban Development, PK - No Doom Monsters, Nonperishable Overhaul, DinoMod, Medieval and Historic Content, Vehicle Additions Pack, Tanks and Other Vehicles]

**Comment by Throwaway-name** [comment]
This isn't caused by mainlined mods. Testing revealed the .410 hull from Extended Realistic Guns is actually smaller than a loaded .410 slug (0.01L vs 0.02L).

**Comment by Night-Pryanik** [comment]
This ammo isn't from vanilla or mods that come with the game, so it isn't our concern.

**Comment by Bulletfang** [comment]
I don't understand, I don't have Extended Realistic Guns in my mods, never have played with it.

**Comment by Throwaway-name** [comment]
@Bulletfang the .410 hull you're talking about isn't part of the game or any mods shipped with it (only E.R.G. mod has .410 shells at the moment), so we can't fix it from here. 

The undersize .410 hull from E.R.G can be fixed by us, so an issue related to that can be fixed here.
