### ISSUE TITLE
Dropping prone and crawling

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#29695]
**Is your feature request related to a problem? Please describe.**  
Based on #29092, we can further extend this mechanic to cover dropping fully prone.
This would offer even more concealment at a cost of even further penalties.

**Describe the solution you'd like**  
Mirror #29092 and add even more extreme penalties for this new mode, and enhanced ability to hide behind furniture.
You should be able to hide behind e.g. tall grass and other very small obstacles.

**Describe alternatives you've considered**  
Put off crawl mode for a while?

**Additional context**  
This mode has some additional features it enables in addition to hiding.
It GREATLY reduces your effective cross-section, so it's actually somewhat "safe" to throw a grenade on open ground and then drop prone to protect yourself from bomb fragments.
That should probably go in a separate PR though.

**Comment by Phenomphear** [comment]
This should also greatly increase any rifle's accuracy. If you ever fired a weapon standing and then lay down to fire, you KNOW it's much easier to aim. Getting up from the prone with a weapon takes some time though. Not a lot, but more so than just running away while standing.

**Comment by l29ah** [comment]
The controls should be better than cycling through all the available modes.

**Comment by jeremyshannon** [comment]
I don't know if I'd want it on another key. "Pay attention to your run/walk mode" is something new players have to learn already, adding another key/state would make it even harder on them. Leaving it on one key makes it harder on the veterans who've long trained themselves on the assumption that there are only two states for that key, but given time I don't see why they can't adapt just like the newbies.

**Comment by l29ah** [comment]
Makes sense. OTOH it would be good to be able to cycle it back and forth, say, with `"` and `'`, so switching between walking and running while retreating from a zombie horde in the city would be more comfortable than pressing `"` three times. Also, dropping prone and standing up should consume action points, otherwise it would be extremely cheap way to improve your grenade/rifle performance.

**Comment by kevingranade** [comment]
Toggling the movement mode doesn't take effect until you take your next action, so you shouldn't get any benefits for free.
