### ISSUE TITLE
Recognize different sound with skill progressing.

### ISSUE THREAD

**Issue by vivi00790** [CleverRaven/Cataclysm-DDA#29701]
# Is your feature request related to a problem? Please describe.
The sound effects are always like ka-boom, pew, p-p-pew, etc. How creative and immersive, isn't it?

# Describe the solution you'd like
Character can recognize different sound with skill progressing.
For example, @ can only recognize generic gun shot sound such as pew, ra-ta-ta-ta, etc, but with @'s marksman (or certain weapon type skill) progressing, he/she can recognize them as __"You hear a small caliber weapon firing"__ or __"A full auto rifle is firing nearby"__, etc.
With high enough skill you can even tell WHAT exactly make the sound, such as __"You hear a 9mm pistol gun shot, probably a Glock 17"__ or __"You hear a 7.62mm rifle firing full auto, sounds like an AK74"__, etc.
Same, as survival (or construction, or fabrication, or mechanic) progressing, simple "thump!" could be __"You hear flesh hitting on metal surface."__, "crash!" could be __"Heavy wooden construct collapse on solid ground"__, "hmm" could be __"medium size engine roaring"__...etc.

# Describe alternatives you've considered
Just make sound effects more detailed and immersive.

**Comment by Phenomphear** [comment]
Brilliant! I love the idea! That would certainly help a lot with NPC's enabled or to tell whether that explosion was from a tank drone or a land mine.

**Comment by Yunatan** [comment]
It would be cool if Mi-go got some development alongside this feature. So they can sensibly lure player.

**Comment by Phenomphear** [comment]
I agree mi-go's are common enough that giving them the ability to reasonably trick someone would be neat. Currently, it's pretty easy to tell when a mi-go is speaking.

![image](https://user-images.githubusercontent.com/28910998/56471956-6e561b00-640d-11e9-9dcb-69379d3cfb03.png)
