### ISSUE TITLE
Sorting by rotten in (E)at menu

### ISSUE THREAD

**Issue by vivi00790** [CleverRaven/Cataclysm-DDA#29702]
**Is your feature request related to a problem? Please describe.**  
Let us more easily to decide which food to eat first.

**Describe the solution you'd like**  
In (e)at menu, add sort by rotten option.

**Describe alternatives you've considered**  
Sort by default.

**Comment by Wedlor** [comment]
It would be nice to add different sorting: rotten, rotting time left, heat\frozen and etc.

**Comment by ifreund** [comment]
I'd suggest just sorting by spoilage in the advanced inventory for now, though I agree that the eat menu could benefit from some sorting as well.

**Comment by Phenomphear** [comment]
Every menu should be able to sort 🐙 . It makes things so nice

**Comment by kevingranade** [comment]
This is done.
