### ISSUE TITLE
Crafting using the new system drops or vanishes liquids

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [CleverRaven/Cataclysm-DDA#29708]
**Describe the bug**  
Crafting liquids results in the liquid disappearing or dropping onto the floor, without option to consume or store it. I specifically used nutriment water to do this, but it should work with water too.

**To Reproduce**  
1: Attain necessary tools to craft your liquid beverage of choice.
2: Proceed to attempt to craft said beverage.
3: Drop it all over the floor because you don't know what a container is.

**Expected behavior**  
I would expect the usual menu where you get to designate where your liquid is placed.

**Comment by ZhilkinSerg** [comment]
Should've been fixed in #29687 alreadyy.

Please report game version when submitting bugs.
