### ISSUE TITLE
Separate cave rock from rock used for buildings.

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#29715]
Right now game uses solid rock for rock in caves and rock in churches and other buildings made of rock. I propose adding separate man made rock walls for buildings so i can make normal cave rock (solid rock) and rock wall tiles.
Also floor in church can be also added like man made rock floor, so churches will not look like a cave.

**Comment by Phenomphear** [comment]
What about "tiled rock" for man-made?

**Comment by SomeDeadGuy** [comment]
And "tiled rock floor"!

**Comment by Reclusive-reptile** [comment]
We already have `t_rock_wall` for structures made of stone masonry, we just need to add it to building where it would make sense.

**Comment by SomeDeadGuy** [comment]
poke
