### ISSUE TITLE
Linear Filtering only for Zoomed Out Mode

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#29725]
Right now when you use no filtering with tileset it look great when you zooming in, but when you zooming out the game looks like terrible mess of pixels. If you will use Linear Filtering when you zooming out game looks awesome, but when you zooming in all textures looks terribly blurry and have grid around every tile.
What i propose is special linear filtering option, when it only applies when you zooming out view, and it do not applies to the picture when you zooming in.
It will make 32x32 tileset look awesome at any zoom level.

Also something wrong with software rendering. It makes transparent tiles darker for some reason.

Software Rendering  Linear filternig Unavailible. zoom x0.5. wrong color for tansparent tiles. Pixelated mess.
![LINEAR_OFF Software](https://user-images.githubusercontent.com/37592026/56431622-174c2b00-62d3-11e9-9b70-c3861d5e989c.PNG)

Direct3D Rendering Linear filternig OFF. zoom x0.5. correct color for transparent tiles. Pixelated mess.
![LINEAR_OFF](https://user-images.githubusercontent.com/37592026/56431669-3e0a6180-62d3-11e9-8793-584108bdb880.PNG)

Direct3D Rendering Linear filternig ON. zoom x0.5. correct color for transparent tiles. Great picture.
![LINEAR_ON](https://user-images.githubusercontent.com/37592026/56431715-75790e00-62d3-11e9-9297-03afa6056864.PNG)

**Comment by mark7** [comment]
Took a quick skim.

OpenGL actually apparently natively-supports this "different scale-up and scale-down scaling mode" mechanism via GL_TEXTURE_MAG_FILTER and GL_TEXTURE_MIN_FILTER, but SDL does not expose this and internally always uses the same scaling mechanism both when scaling up and down.

It looks like SDL attaches the scaling mode to the source SDL_Texture, so it's probably possible to create a linear-scaling texture and a nearest-neighbor scaling texture for each tile at the cost of double the memory, then switch between the two depending upon zoom level.  Not sure how substantial the memory usage for the textures is today.

**Comment by SomeDeadGuy** [comment]
Nooooo, save me!

**Comment by Night-Pryanik** [comment]
No discussion in over two years, closing.
