### ISSUE TITLE
Opening notifications menu freezes game, android

### ISSUE THREAD

**Issue by GenericDM** [CleverRaven/Cataclysm-DDA#29739]
Game will freeze if system notifications menu is opened (Google Pixel 2 XL) . Android 9 with latest security updates, game version 0.D-1799-g43f1f6e

**Comment by ZhilkinSerg** [comment]
Is it still an issue on latest available version?

**Comment by ZhilkinSerg** [comment]
Thanks for checking. Closing as resolved then.
