### ISSUE TITLE
tools_common, Cannedfood, and raw_materials error.

### ISSUE THREAD

**Issue by ZareCograth** [CleverRaven/Cataclysm-DDA#29732]
![Error](https://user-images.githubusercontent.com/16278326/56427945-aafa0900-628b-11e9-9271-ae856dbabbd1.png)
I have an error that seems to only happen when I add mods that add more buildings. At first I thought it was just Cata++ again, but even without it I still get this error. Went through my mods, and the game will run fine without Cata++ or any of the mods that add buildings.

Just updated today twice just to make sure, so at least the last 2 or 3 builds have been causing this issue for me, which as of right now the latest build is 8808. I'm running Windows 10 x64, and tiles for graphics.

**Comment by ZareCograth** [comment]
The latest updates still are doing the same thing? Any update on this issue?

**Comment by Eddyskingdom** [comment]
when will this ever be fixt

**Comment by kevingranade** [comment]
When the mods in question update, this is not a core game problem.
