### ISSUE TITLE
Surface level of Strange Temple could use some love.

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#29742]
**Is your feature request related to a problem? Please describe.**  
As title. While undergroud part is relativelly intresting, all we have on surface are some metal bars and socekt for eye. Its not even a temple! More like a strange bunker, or dungeon. 
**Describe the solution you'd like**  
Maybe some of many talented catacysm artists would like to try making some ruined-church-like location. With bars to dungeon behind alter with sacrifices on it, or hidden somewhere. With partially colapsed bell tower that could be used to scout the forest.

Adding some unussued enemies would be cool, for example one flesh angel and like 3 homunculus. Dementia and blood sacrifice optional.
**Describe alternatives you've considered**  
Renaming strange temple to strange bunker. 
Trying to learn making own PR and lern to design locations, but it would look like potato, or minecrafters first dirt house.

**Additional context**  
I find occult part of the game very intrigatting for some reason.

**Comment by SirPendrak** [comment]
Pls no, isue still exists. 

Unless i missed something.

**Comment by kevingranade** [comment]
Feature requests can not stick around forever. We have way too many filling up the issue tracker, and we need to trim the numbers.
