### ISSUE TITLE
Railroad track tiles block movement of vehicle 

### ISSUE THREAD

**Issue by egorzaderiy** [CleverRaven/Cataclysm-DDA#29743]
**Describe the bug**  
Railroad track tiles prevent movement of vehicle. It produces message "<Carname> collides with the railroad track"

**To Reproduce**  
1. Teleport to railroad station
2. Spawn any vehicle
3. Move or drive vehicle to railroad truck tile

**Expected behavior**  
Vehicle can move over these tiles.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-1963-gf689218
 - Graphics version: Tiles
 - Mods loaded: None

**Additional context**  
On build # 8806 it worked fine, on build # 8807 it started happening. I'm sure it's related to #29628

**Comment by ZhilkinSerg** [comment]
I would say it is an accurate behavior and non issue - most vehicles cannot drive over railroad tracks in real life.

**Comment by egorzaderiy** [comment]
Hmm.. But how trains(when they will be implemented) are supposed to work then?

I have used these tunnels with my portable car what i bring here to go from lab to lab. If I could build a train, i would do it. But until that, can we have a workaround with allowed movement on track tiles?

**Comment by Night-Pryanik** [comment]
> But how trains(when they will be implemented) are supposed to work then?

Their wheels could have a flag that would allow them to move only on rails.

**Comment by kevingranade** [comment]
> I have used these tunnels with my portable car what i bring here to go from lab to lab. If I could build a train, i would do it. But until that, can we have a workaround with allowed movement on track tiles?

I'm not interested in throwing out correct definitions of rails for some arbitrary workarounds.  If you want to patch in something like this locally, feel free, but rails work as intended right now.

What is the state of railroad crossings, do we have a different terrain for those?  If we don't, we need to address that.  If we have that already there's nothing to address here.

**Comment by ZhilkinSerg** [comment]
> What is the state of railroad crossings, do we have a different terrain for those? If we don't, we need to address that. If we have that already there's nothing to address here.

Yes, it needs to be addressed - they use basic rails now and that would be an issue when overmap railroads spawn would be in.

**Comment by ZhilkinSerg** [comment]
I guess we could also add some makeshift ramp construction which can be built over rails and allow vehicle movement. This should be achievable with json-only modification.

**Comment by AnomalyXIII** [comment]
> I would say it is an accurate behavior and non issue - most vehicles cannot drive over railroad tracks in real life.

in real life there are plenty of places to cross railroad tracks in a vehicle however that is not in the least so in cdda.
