### ISSUE TITLE
Clean water doesn't appear after crafting

### ISSUE THREAD

**Issue by caitisgreat** [CleverRaven/Cataclysm-DDA#29740]
**Describe the bug**  
I'm trying to boil water and give my character something to drink, but when I do the water seems to just disappear.  I can't totally explain where the water goes, but it appears as though the clean water was successfully crafted.

**To Reproduce**  
1. Collect water to boil, find containers to put the clean water product in
2. Start a fire source near by your character
3. Craft clean water from water using the fire source with a container for boiling water

**Expected behavior**  
The clean water product should be placed in to a container on or nearby my character.

**Screenshots**  
https://youtu.be/1MStt1aHvn8

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1921-gbe0d520
 - Graphics version: Tiles
 - Mods loaded: 
* Dark Days Ahead 
* Disable NPC Needs
* Garden Pots
* Boats
* StatsThroughSkills

**Additional context**  
This is a link to my save file: https://metaloma.com/index.php/s/Coe6JNAAP2tAZGs

**Comment by ifreund** [comment]
Fixed by #29687, you should update your game.

**Comment by caitisgreat** [comment]
Perfect.  Thank you!

**Comment by ifreund** [comment]
No problem!
