### ISSUE TITLE
(&)Crafting menu tabs too generic. / More classification of (&)crafting menu tabs.

### ISSUE THREAD

**Issue by vivi00790** [CleverRaven/Cataclysm-DDA#29758]
**Is your feature request related to a problem? Please describe.**  
With more and more recipes join CDDA, some category of (&)crafting menu getting too long and more and more hard to find what to, or can, craft.

**Describe the solution you'd like**  

- There should be sub-classes and sub-sub-classes under current categories, for example:

1. Food/Drink may have sub-class such as brewed drinks (dry stuff + (usually hot) water: tea, dandelion tea, coffee, etc), alcoholic, and fresh drinks (make from fresh stuff, juice, almond milk, kompot, etc)

2. Food/Others may have sub-class such as deluxe foods, raw material (flour, starch, sugar, etc)

3. Vehicle parts (anything that can be installed on vehicle) may have it's own tab, and sub-classes :mounted weapon, solar panel related, tanks, armor plates, blob series, etc).

4. Fish and its products should have their own tab

5. Move pet foods from food/others to ANIMAL tab

6. Others/Tool may have sub-classes like makeshift tools, crafting tools (tools participate in crafting, toolbox, crucibles, etc) and survival tools (useful for surviving, cookers, Halligan bars, tree spiles, etc)

7. Weapon/ranged should have sub-classes: firearms, bows (crossbow, bow, slingshot) and hi-tech weapon (railgun, laser raifle, etc)

-  **_NEED TAB FOR CANNED FOODS_**, they are mixed with general recipes and it's so misleading :( 

**Describe alternatives you've considered**  
Just throwing my thought about classification out , more than glad to see any other solutions.

**Comment by Yunatan** [comment]
I find armor\clothing tab to be especially long at higher levels

**Comment by Inglonias** [comment]
What might work better with the UI is user-definable tags rather than more and more subcategories. So when you search +hot +drink, you get things tagged with both of those.
