### ISSUE TITLE
Relaying cover information visibly to player/ balance crouching

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#29752]
**Is your feature request related to a problem? Please describe.**  
Well, I suppose it's a problem.  Currently, there's no verification (that I've seen) that crouching in a particular location is actually protecting you from being seen.  It would be nice to have a quick and obvious way of communicating that to the player.  It also needs some negative, as currently crouching is basically always beneficial outside of combat.

**Describe the solution you'd like**  
I was thinking that crouching behind cover should partially obscure the player's vision to reflect this.  Currently, crouching behind, say, a desk or car, you have full vision.  Having that vision obscured could quickly show the player that they're crouched behind cover.  It also reflects some amount of realism.  If you're crouching behind a desk, you probably don't have a full, unobstructed view of the other side of that desk, unless you would peek, an action we already have implemented.

**Describe alternatives you've considered**  
I'm sure there are other ways to communicate this, even just a simple letter or word in the sidebar, but I like the idea of partially blocked vision better.  Crouching will need something to balance it (like stamina consumption balances sprinting).

**Additional context**  
I know it's new and I'm sure it will be worked on a lot over the next few weeks/months.  Just thought I'd put this idea out there.  I also think crouching should burn more stamina.  Go outside and crouch-walk around for 5 minutes.  Your calves will be on fire.  That would be a separate issue, though, I guess.  With the way crouching currently is, there's really no negative to it at all, aside from slower movement speed.  Unfortunately, movement speed isn't super relevant outside of combat-related situations, so there's really no downside to crouching everywhere and obstructed vision could help with that.

I'm also just a baby coder.  This might be a big ask and I just don't realize it.

**Comment by Wokko1** [comment]
> Currently, crouching behind, say, a desk or car, you have full vision. Having that vision obscured could quickly show the player that they're crouched behind cover. It also reflects some amount of realism. If you're crouching behind a desk, you probably don't have a full, unobstructed view of the other side of that desk, unless you would peek, an action we already have implemented.

I was thinking the player-character is constantly "peeking" out of their cover while crouching, which is not too unrealistic? Besides, forcing the player to use the peek button all the time would be tedious and not encouraging for stealth approach, imo.

> It also needs some negative, as currently crouching is basically always beneficial outside of combat.

There is, crouching makes you slower. "Outside of combat" is exactly when it should be used, when you don't want to fight enemies. Crouching while there are no enemies is still a waste of time (and potentially food/water resources).

> I also think crouching should burn more stamina. Go outside and crouch-walk around for 5 minutes. Your calves will be on fire.

"Crouching" is more like "stealth mode" from GTA V, where the player character doesn't literally duckwalk, but assumes a lower posture and tries to be inconspicuous. Or at least that's what I imagined. Even if we make it consume stamina, it would be silly to force the player to walk when stamina is depleted to 0, so the only way to balance it is to further decrease movement speed, but I don't think it's necessary.

> I'm also just a baby coder. This might be a big ask and I just don't realize it.
It's not a big ask, but I absolutely don't have ideas how to represent hiding info. I hope people would post some ideas on how to show what areas the player can hide in.

**Comment by Wokko1** [comment]
> Currently, crouching behind, say, a desk or car, you have full vision. Having that vision obscured could quickly show the player that they're crouched behind cover. It also reflects some amount of realism. If you're crouching behind a desk, you probably don't have a full, unobstructed view of the other side of that desk, unless you would peek, an action we already have implemented.

I was thinking the player-character is constantly "peeking" out of their cover while crouching, which is not too unrealistic? Besides, forcing the player to use the peek button all the time would be tedious and not encouraging for stealth approach, imo.

> It also needs some negative, as currently crouching is basically always beneficial outside of combat.

There is, crouching makes you slower. "Outside of combat" is exactly when it should be used, when you don't want to fight enemies. Crouching while there are no enemies is still a waste of time (and potentially food/water resources).

> I also think crouching should burn more stamina. Go outside and crouch-walk around for 5 minutes. Your calves will be on fire.

"Crouching" is more like "stealth mode" from GTA V, where the player character doesn't literally duckwalk, but assumes a lower posture and tries to be inconspicuous. Or at least that's what I imagined. Even if we make it consume stamina, it would be silly to force the player to walk when stamina is depleted to 0, so the only way to balance it is to further decrease movement speed, but I don't think it's necessary.

I don't really know how to represent hiding info, and I hope people would post some ideas here on how to show what areas the player can hide in, how to make it more intuitive, etc.

**Comment by TheMurderUnicorn** [comment]
I mean, I don't hate it.  I won't be the one working on it, so its really up to whoever is putting in the work.  I really do think that affecting vision is the quickest and most easily understood way to do it, though.

**Comment by Yunatan** [comment]
> I also think crouching should burn more stamina. Go outside and crouch-walk around for 5 minutes. Your calves will be on fire.
If I was in a survival situation I wouldn't literally crouch-walk like I am in a PE class. I would probably free my hands and crouch on all fours, which is easier AND stealthier.

**Comment by kevingranade** [comment]
>  I really do think that affecting vision is the quickest and most easily understood way to do it, though.

We might do it at some point, but it is not at all quick or easy.
