### ISSUE TITLE
Add filter for cover and layer locations in crafting menu (&)

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#29766]
**Is your feature request related to a problem?**  
There are too many cloth and armor crafting in crafting menu (&), sometimes finding something that covers something specific is hard to find specially at high levels of tailoring.

**Describe the solution you'd like**  
I have been thinking for a while that a filter for cover and layer locations would be really nice to find something specific.

**Describe alternatives you've considered**  
Someone mentioned Cloth & Armor is cluttered in #29758 (More classification of (&)crafting menu tabs.) and I agree, but I don't think more tabs can actually improve this situation.

**Comment by esotericist** [comment]
You can sorta fake this right now with the current filtering, by doing `d:torso, d:outer`, but it's pretty slow. Not a full solution (nor an obvious one), nor is it particularly swift, but there is a current workaround.

**Comment by KurzedMetal** [comment]
I thought I tried that before and didn't work, I guess I didn't do the search correctly. My bad.

**Comment by esotericist** [comment]
It's finicky.

**Comment by esotericist** [comment]
![image](https://user-images.githubusercontent.com/1569754/56462114-57161f80-6372-11e9-8b9a-4493f142c40a.png)

This worked for me just now. Took a couple seconds after hitting enter for the search to resolve, but it does work. It's just not an obvious way to do it.

**Comment by pjf** [comment]
I know our friendly bot is marking this as potentially stale, but it's something I would dearly love. Being able to search for `l:torso,L:strapped` would make it much easier to navigate armor and clothing options at higher levels.

**Comment by kevingranade** [comment]
Please do not, "bump" issues that are marked stale.
