### ISSUE TITLE
Bandit Tree Blockade spawns in cities

### ISSUE THREAD

**Issue by Mcrone617** [CleverRaven/Cataclysm-DDA#29769]
**Describe the bug**  
#28761 describes the tree blockade as only spawning between two tree tiles on the overmap, but I've been seeing it spawn in cities every now and again.

**To Reproduce**  
1. Make a normal game
2. eventually run into this, if you play long enough.

**Expected behavior**  
I could be reading the PR wrong, but shouldn't this happen only in forests? and not in the middle of cities for example.

**Screenshots**  
![NPC__tree_spawn_01](https://user-images.githubusercontent.com/26668115/56462989-6eacd280-6389-11e9-922c-a69f065804a6.PNG)
This one is angled incorrectly (maybe something else to check out) But I've seen a couple in normal games where the ambush is also angled correctly in cities, I just decided to go hunt down a example in debug mode for a bug report.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: O.D 2042-g38a7bd7
 - Graphics version: Tiles
 - Mods loaded: none

**Additional context**  
It's pretty rare, but for some reason this scenario can spawn in cities, when it really shouldn't be able too. The angle is off here also, but that may be because it spawned in a city instead of a forest road.

**Comment by echomirage1** [comment]
I've seen the roadblock twice, and both times there were empty fields on both sides of it.

**Comment by chriseich21** [comment]
Would actually be cool to still have it spawn in cities, but use something appropriate/intended, like metal wreckage, debris representing streetlight, or cars.

**Comment by chriseich21** [comment]
Would actually be cool to still have it spawn in cities, but use something appropriate/intended, like metal wreckage, debris representing streetlight, or cars.
