### ISSUE TITLE
We shouldn't get zapped inside vehicles

### ISSUE THREAD

**Issue by Vamael** [CleverRaven/Cataclysm-DDA#29771]
**Describe the bug**  
As I'm driving through a town in my super advanced deathmobile and using a Tesla turret me and my followers inside are occasionaly zapped.

**To Reproduce**  
1. Place Tesla turret on top of vehicle
2. Set to auto and drive
3. Get zapped

**Expected behavior**  
In a green, not destroyed vehicle we shouldn't get zapped, seeing as real-life cars can use their body to redirect even lightning strikes to earth.

**Screenshots**  
https://mega.nz/#!sodmRKrI!Rl3IQIKONV9EEnJRNyJq6lrWqYSe0SI3NXJo62B3JTI

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2038-g49c568e (tiles) /experimental 8815
 - Graphics version: Tiles
 - Mods loaded: 
[
  "dda",
  "no_npc_food",
  "aftershock",
  "Tolerate_This",
  "craftgp",
  "FIC_Weapons",
  "realguns",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "modular_turrets",
  "PK_REBALANCE",
  "Salvaged_Robots",
  "alt_map_key",
  "Cata++",
  "mutant_npcs",
  "national_guard_camp_edit",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "shardstuff",
  "Arcana",
  "Arts' Guns",
  "no_religious_Texts",
  "winning_dda",
  "more_classes_scenarios",
  "novitamins",
  "StatsThroughSkills",
  "secronom",
  "Metabolism_Rates",
  "noctpk"
]

**Additional context**  
It mostly happens when I'm driving forward (electric tiles are getting inside the vehicle and thats why it zaps maybe?) If I'm staying still its OK.

**Comment by kevingranade** [comment]
Your first problem is that you have a Tesla turret, that's not core game.  However I'm willing to believe this would happen with shocker zombies too.

**Comment by PatrikLundell** [comment]
Yes, you get zapped by electric zombies in vehicles, and fried by gasoline ones (both were nasty, unexpected surprises).
