### ISSUE TITLE
Game crashed when I crafted an arrow

### ISSUE THREAD

**Issue by FrancisDec** [CleverRaven/Cataclysm-DDA#29778]
I crafted a small game arrow and the game crashed.

![Untitled](https://user-images.githubusercontent.com/49828633/56466034-d1798a80-63d8-11e9-96fd-52bbfccd357b.png)

I wasn't able to upload my game save because it crashed before I could save.

 - OS: Windows 10
 - Game Version: 8819
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Disable NPC Needs

**Comment by lool228** [comment]
![image](https://user-images.githubusercontent.com/48703401/56467199-84bba100-6424-11e9-9cfa-fa4fc0b26085.png)

me too

**Comment by dom4op** [comment]
Just had a similiar crash, although I didn't do any crafting atm. I was just starting fire in an oven as usual.

![Crash1](https://user-images.githubusercontent.com/49651777/56467804-6063c280-642c-11e9-8c39-4d17b5357bb0.jpg)

**Comment by dom4op** [comment]
This might be related to the error I get after updating from 8815 to 8820:

![Sprite-0002](https://user-images.githubusercontent.com/49651777/56468221-a2433780-6431-11e9-8286-7c11c6e99061.jpg)

The only mod I'm using is my own mod that just tweaks some values in overmap-specials and regional_map_settings. It makes some locations and map extras spawn less and doesn't add anything.

**Comment by Necrosian** [comment]
Might be related to mine too. C rafting water first 2 attempts succeed now it just crashes.
![Capture](https://user-images.githubusercontent.com/26538192/56470077-ab8cce00-644a-11e9-86b0-b7084cda60db.PNG)

**Comment by ViralAnomalyX** [comment]
Could be related to mine as well.
[CataclysmError.docx](https://github.com/CleverRaven/Cataclysm-DDA/files/3101192/CataclysmError.docx)

**Comment by GenericDM** [comment]
Error occurs in [this file](https://github.com/CleverRaven/Cataclysm-DDA/blob/83dfde8aa18e6224c90b53196d92f25513b7ac9a/data/json/items/chemicals_and_resources.json) at line 996, presumably due to a rounding error of some sort.

**Comment by dom4op** [comment]
Can't we just revert to previous wood ash weight? At this point I'm pretty sure the game crashes during ash generation process (when a burning fire produces ash)

**Comment by Zireael07** [comment]
Previous wood ash was WAAAAAAAAAAAAY too dense.
