### ISSUE TITLE
Entering silos crashes game

### ISSUE THREAD

**Issue by FeelsBadMatey** [CleverRaven/Cataclysm-DDA#29773]
Whenever i enter a silo, the game crashes. However, if i enter via falling, it doesn't crash right away, but when i go up the stairs provided, it does.

1. Enter a missile silo.
2. The game crashes.

 - OS: Windows 7
 - Game Version: 0.D=2040-g45666d8
 - Graphics version: Tiles
 - Mods loaded: (i have a big modlist, so here's a version with related mods)
                          Modular Turrets, Generic Guns, More Survival Tools, Icecoon's Arsenal 

The crashdump mentions tiles, so that may be related.

**Comment by pjf** [comment]
@FeelsBadMatey : I don't suppose you have a copy of the crashlog that you can attach? Copy'n'paste works, as does the 'attach files' link at bottom of the comment textarea.

**Comment by FeelsBadMatey** [comment]
I don't know why, but it works now. Weird.

**Comment by kevingranade** [comment]
I did fix a crash bug recently that's possible to trigger in all kinds of
ways.
