### ISSUE TITLE
Freed prototype cyborgs not recruitable?

### ISSUE THREAD

**Issue by GearheadLydia** [CleverRaven/Cataclysm-DDA#29774]
**Describe the bug**  
Prototype cyborgs fresh out of the AutoDoc are not properly recruitable. 

**To Reproduce**  
1. Find an AutoDoc.
2. Spawn an inactive prototype cyborg with cheats and drop it on the autodoc.
3. Remove its Personality Override chip with the Autodoc.
4. Attempt to recruit it.

**Expected behavior**  
Prototype cyborgs freed in this manner 

**Versions and configuration(please complete the following information):**
 - Game Version: 0.D-1789-gc0d27c5
 - Graphics version: Tiles

**Additional context**  
Might have something to do with their attitude being set to Ignoring? Which is not an attitude I see on NPCs a lot.

**Comment by Fris0uman** [comment]
What happens when you attempt to recruit ?
What should happen is that if you go through the dialogue they can be automatically recruited.

**Comment by GearheadLydia** [comment]
> What happens when you attempt to recruit ?
> What should happen is that if you go through the dialogue they can be automatically recruited.
I get to "recruit" them and see the NPC management screen, but once I exit out of it, the NPC stays purple and chatting with them again causes them to return to the initial recruitment dialogue.

> Also they should `want to talk` and not be ignoring.
They're set to "ignoring" in every test I've run (admittedly, all with debug mode, never with organically generated NPCs). They move away from my survivor and don't try to talk to them, and say "Ignoring" in the debug NPC info menu rather than "Wants to talk".

**Comment by Fris0uman** [comment]
That does sound like a bug, I'll try to fix it this week.

**Comment by GearheadLydia** [comment]
I found it. There was an additional JSON flag that was missing that controls recruitment.

I also mooted the idea of putting more depth into the initial recruitment dialogue, like making it so the cyborgs have semi-randomized initial opinions, but that's another matter.
