### ISSUE TITLE
Failed crafting (Cornbread) - with a infinite water source causes the game to indefinitely hang/crash

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#29781]
**Describe the bug**  
Failing to craft cornbread but the water component doesn't get wasted, then asks me what do i want to do with the water, so i go about emptying it into containers but several containers later it doesn't end with the request to dump water somewhere, so i dump the water on the ground, and it appears and only 1 unit of water (Dirty) and as soon as I move the game will hang, infinite loading crash... you get the idea. 

I am able to pass time but it's only when I move the game crashes.

**To Reproduce**  
1. Fail to craft cornbread with infinite watersource 
2. Empty water on floor
3. Move anywhere and it crashes.

**Expected behavior**  
Only consume / give me the water it requires to be crafted which is 2 in this case.

**Screenshots**  
![image](https://user-images.githubusercontent.com/5264667/56466844-0e607400-640f-11e9-9535-96d58e5ea0b0.png)

**Versions and configuration(please complete the following information):**
 - OS: Win7 64bit
 - Game Version: 0.D-2042-g38a7bd7
 - Graphics version: [Tiles chesthole32]
 - Mods loaded: [ "dda",   "Medieval_Stuff",   "More_Survival_Tools",   "Packaging",   "RL_Classes",   "SD_Magcrafting",   "StatsThroughSkills",   "blazemod",   "Tanks",   "Urban_Development",   "ZSFIXED_cddaxp",   "boats",   "craftgp",   "deoxymod",   "ew_pack",   "filthy_morale",   "makeshift",   "more_classes_scenarios",   "mutant_npcs",   "national_guard_camp",   "no_npc_food",   "npc_traits",   "realguns",   "Tolerate_This",   "modular_turrets",   "Salvaged_Robots",   "Bootleg_Walkers",   "DracoDogMod",   "DP_AMAZING_CHEST_INDICATORS",   "aftershock",   "SD_Magcrafting_Realguns_Extension",   "Arcana",   "more_locations",   "FujiStruct",   "Uekibati_mod" ]

**Additional context**  
[Game 52.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3101004/Game.52.zip)

**Comment by ifreund** [comment]
![Screen Shot 2019-04-21 at 2 35 30 PM](https://user-images.githubusercontent.com/12723818/56470118-c0656380-6442-11e9-9470-55d3aea5f720.png)
Yeah that' seems like a bug, will investigate.

**Comment by communistkiro** [comment]
I've had this happen to me twice, once with bone glue (or superglue?), and once with boiled bandages. It asked me what to do what the water, even though that shouldn't be the endproduct. I can't remember if I was interrupted by pain, because I play a the megafail cyborg, but in the end you get spill of over 6-digits of water.
