### ISSUE TITLE
Eventual Crash after moving around, Arithmetic Error

### ISSUE THREAD

**Issue by Xenotrenium** [CleverRaven/Cataclysm-DDA#29788]
![cdda_x1](https://user-images.githubusercontent.com/15146006/56470856-73d25600-644b-11e9-8dc1-e3cee9d71e64.png)
Game version:
0.D-2055-ga1cdc83 (tiles)
build 8822 (released 21.04.2019)

Operating system:
Windows 10

Tiles or curses:

Mods active:
![cdda_x2](https://user-images.githubusercontent.com/15146006/56470955-ceb87d00-644c-11e9-89a4-b2384ea8f5ae.png)

Log file:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3101244/crash.log)

### Expected behavior
No crash

### Actual behavior
CTD after observing the message shown in the first picture

### Steps to reproduce the behavior
Don't know how and why. Using my save file as example: Walk back and forth a bit. Should take less than 20 turns before crash. Alternate between going left from origin position to right. Bug seems to happen after a set amount of time, though not certain of that.

EDIT: Fire going 2-3 viewscreens south of main image. Fire is free, meaning there is no brazier or pit to contain it.

**Comment by GenericDM** [comment]
Did you have any fires set? If so, may be related to #29778.

**Comment by Xenotrenium** [comment]
> Did you have any fires set? If so, may be related to #29778.

I do have a fire set south of the Lab my character is in. It does appear to be related to #29778, though finer heads at CDDA bug tracking should decide. Is there something else I can do to clarify?

**Comment by GenericDM** [comment]
I got an almost identical stack trace with a crash related to #29778 so if it keeps happening after you update to build 8824 (it's in progress with windows tiles version as of posting) then it'll need to be looked into further.

**Comment by ifreund** [comment]
Closing since it seems like this was fixed, if this problem is still present on the latest version please reopen
