### ISSUE TITLE
`favorite` is useless with bolts and arrows

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#29794]
**Describe the bug**  
Firing (or even aiming and then putting them back) clears the flag, so you either have to re-flag all the arrows and bolts every time you collect them or re-pick them after you drop all your loot in your deathmobile cargo spaceusing `,` in AIM.

**Versions and configuration(please complete the following information):**
0.D-2045-g83dfde8aa1-dirty

**Comment by alkemann** [comment]
Are you aware of a potential alternative to your need? Hit `F` while wielding bow. This will pre-pick bow and each `f` will shoot that arrow, saving the need to pick arrow each time.

**Comment by l29ah** [comment]
This is not related to `,`.

**Comment by alkemann** [comment]
No, but I thought maybe the reason you wanted to have arrows be favorites. Sorry if that was not helpful

**Comment by l29ah** [comment]
Still an issue on today's master.
