### ISSUE TITLE
Better way to smash objects and terrain

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#29793]
![image](https://user-images.githubusercontent.com/28910998/56471797-83ca4580-640b-11e9-8e6b-b5a440db0133.png)

We all know pressing `s` and a direction key x47 sucks.

What I propose is when the player presses `s` to smash, and then the direction, if the first strike does not destroy the object/terrain a check can be preformed to see if the character is able to smash the object and if able a prompt that reads something like "It may take some time to smash this. Smash?" and then yes/no. Upon selection of Yes the player will begin smashing until the object breaks, just like any other task that is performed over time.

When the player is unable to meet the check the log can read "It seems like you are too weak to smash the 'foo'"

I believe this second message is far more informative then "You don't seem to be damaging the 'foo'"

**Comment by Rustybuckets6601** [comment]
so uhh i'm guessing this feature still isn't added?

**Comment by Zireael07** [comment]
No, it was just closed by stalebot before Github allowed differentiating reasons for closing
