### ISSUE TITLE
Crash when creating character

### ISSUE THREAD

**Issue by Chryseus** [CleverRaven/Cataclysm-DDA#29790]
**Describe the bug**  
Crash when reaching the attribute stage of the custom character creator.

**To Reproduce**  
1. Create new world
2. Create custom character

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux 5.0.7
 - Game Version: c71b04bb
 - Graphics version: Tiles
 - Mods loaded: dda, disabled npc needs

**Additional context**  
Backtrace
https://ghostbin.com/paste/tmvzp

Addional message sometimes appears when creating custom character:
https://ghostbin.com/paste/tan9b

**Comment by AMurkin** [comment]
#29787 should fix this.

**Comment by Night-Pryanik** [comment]
@Chryseus could you test the latest build and check if this still an issue?

**Comment by Chryseus** [comment]
Issue has been fixed, closing.
