### ISSUE TITLE
Plantings from pervious character in same world don't grow

### ISSUE THREAD

**Issue by DexterBobo** [CleverRaven/Cataclysm-DDA#29792]
I made a base. I farmed. I died. :(

Then I re-entered that same world with a new character and moved into the first character's base. 70 days later and the vegetables planted by the first character are still stuck in the growth state they were when he died, and will not progress further, giving only the "This _____ has already been fertilized." message when examined from now until eternity...

**Comment by echomirage1** [comment]
Plants won't grow if they are below the minimal planting temperature. If your new character started spring day 1, then the plants were just sitting there for a while without actually growing.

**Comment by DexterBobo** [comment]
This is 70 days into the second character though. I have already planted and harvested new plants in this second timeline. Does the old plants being subjected to the cold temps of the start of spring forever stop their growth?

**Comment by echomirage1** [comment]
Different plants have different growing times.

https://cddawiki.chezzo.com/cdda_wiki/index.php?title=Farming

From the data here you can calculate if your plants really bugged out or just need more time.
I had the same situation before (on an older version), and all the plants went through the growing process eventually.

**Comment by DexterBobo** [comment]
These have been sitting unchanged at either the "planted seed" or "seedling" stage for over 70 days and counting in the new timeline. 

Seeds planted in the new timeline (including some of the same varieties as the old plants) have already reached maturity.

**Comment by DexterBobo** [comment]
Okay, the plants have now appeared to resume growing at what I believe is the point in the timeline of the original character's death. So the growing timeline for the old plants are tied to the timeline for the original character? Like if the previous character planted them at day 70 of his timeline, they will not age until the new character reaches day 70 of their timeline?

That behavior seems pretty weird? At least not how I would expect it to be. 

If the new timeline is supposed to be sort of an alternate universe-type thing I guess I can kinda understand it?

**Comment by echomirage1** [comment]
Yes, it works like that. Some other things with solar panels and vehicles were doing the same thing and got fixed. It is a bug for sure. I suggest adding the additional details to the original issue so it's more to the point.

Different characters are not handled very well in one world. You can do things with one character and see the results with the other one, but they can't meet even if they stand in the same room at the same time. It's just that nothing was really implemented about sharing a world, it doesn't have anything to do with lore or anything.

**Comment by kevingranade** [comment]
We don't have a workable proposal for making this happen.
