### ISSUE TITLE
Zombie Masters and Necromancers should have the CAN_OPEN_DOOR json flag

### ISSUE THREAD

**Issue by Mcrone617** [CleverRaven/Cataclysm-DDA#29799]
**Is your feature request related to a problem? Please describe.**  
Because #29597 has been merged, and applies to the prototype cyborg and the zombie scientist, it should be added to more enemies that it makes sense for. 

**Describe the solution you'd like**  
Because the new zombie scientist currently has the flag, and it's description implies it is being controlled, or somewhat controlled by the blob, other zombies that have greater blob control should also get this flag.

Specifically, the Zombie Necromancer and the Zombie Masters are both implied to have greater blob involvement than the average zombie, as they are both smart enough to stay out of danger and hide at the back of the horde, using their abilities to make life hell for the player. They only charge and start directly attacking when there are no other zombies left. A intelligence of that level should also be able to open doors also, which could potentially allow Hordes easier access to a survivor fleeing through a house.

Lore wise, it kinda makes sense (although the lore is fluid, and can easily be changed) because it would make sense that the blob would devote a little more attention to the labs, to make sure that the pesky humans don't try to seal it off or develop weapons/cures that would hurt it on a larger scale. By the same logic, the Necromancers and the Masters are conduits for the blob to shape and support the hordes or zombies, and should have the intelligence and motor skills on par with the zombie scientist.

**Describe alternatives you've considered**  
A alternative would be to remove the flag for the zombie scientist, if we determine lore-wise that zombies should not have the skills required to open doors, and limit this flag to enemies that are human, robots, and other smart nether monster. The old broken cyborg should possibly have this flag also, for example, and there could be a case made for robots such as the riot control bot (and other robots) having this flag, as a robot that could breach houses would probably be designed to open doors instead of just bashing through them.

**Additional context**  
Ultimately, because this is a new flag, It could go either way, but I just wanted to start a discussion on what enemies are allowed to have this flag, and to understand the lore criteria for an enemy getting this flag.

**Comment by kevingranade** [comment]
This isn't as simple as giving masters and necros the ability to operate doors, that would be fine lore-wise but have little to no impact on the game.

What I want to happen is masters make all controlled zombies act more intelligent.

**Comment by darktoes** [comment]
That sounds awesome. However, using this as a stopgap measure to represent that and seeing how it interacts with current mechanics and the zombie horde meta could be really interesting and useful.

**Comment by Mcrone617** [comment]
> This isn't as simple as giving masters and necros the ability to operate doors, that would be fine lore-wise but have little to no impact on the game.
> 
> What I want to happen is masters make all controlled zombies act more intelligent.

Will that eventually end up replacing the master's current abilities? I'd definitely say a intelligence booster (horde coordinating via shared vision possibly, avoiding fire/acid, opening doors) would be far more interesting than the current ability, but it could definitely have both the old and (eventual) new abilities, they're pretty rare anyways. 

Also, lore-wise what is the status of the blob interest in the world? Before, the old lore basically said as soon as it hit the ocean it stopped caring and paying attention, but the new zombie scientist description implies more involvement than before. And I know you were working on a rewrite of a design document/vision for a while.

**Comment by kevingranade** [comment]
> Will that eventually end up replacing the master's current abilities?

Replace master abilities, though a buffing zombie could inherit the old master abilities.

> Also, lore-wise what is the status of the blob interest in the world?

Mostly it's done, it's in control of most of the planet, and it'll stay that way for the foreseeable future.
