### ISSUE TITLE
Arrow_wood_heavy missing prop damage

### ISSUE THREAD

**Issue by JamesStrife** [CleverRaven/Cataclysm-DDA#29806]
**Describe the bug**  
arrow_wood_heavy is missing prop damage in master 

**To Reproduce**  

inspect file: data\json\items\archery.json
ID: "arrow_wood_heavy"
Missing Line: ""prop_damage":[A Number]"

**Expected behavior**  
A value greater than zero.

**Screenshots**  

![image](https://user-images.githubusercontent.com/24858167/56477649-05ef5400-6476-11e9-868a-91ba33aa34fe.png)

**Versions and configuration(please complete the following information):**

 - OS: Win 10
 - Game Version: 0.D-2092-gdf6c61e (tiles)
 - Graphics version: [Tiles]
 - Mods loaded: N/A exists in current master

**Comment by JamesStrife** [comment]
Found when my old heavy wooden arrows went from one of the best early game arrows to the worst.

**Comment by JamesStrife** [comment]
Looks like ID:"arrow_metal_sharpened_fletched" is also missing prop damage:

![image](https://user-images.githubusercontent.com/24858167/56478285-199db900-647c-11e9-9ef1-c5dc01cc291d.png)

**Comment by darktoes** [comment]
They're both intended to have a proportional damage value of 1, and just inherit the damage of the bow they're fired from. Is that not working as intended?

**Comment by echomirage1** [comment]
I believe this is the same case with the simple metal bolt and the makeshift wooden bolt. They don't display any data whatsoever. Even if they use the same values as the weapon, they should display them, so you can confirm that they don't improve the weapon stats.

**Comment by darktoes** [comment]
Normally bullet damage is added to the damage of the gun, so displaying it isn't necessary. This is a unique case where the "bullet" doesn't modify the damage of the gun at all.
The only way I can see to improve this, if it bothers people, is to run a check and display a damage multiplier of 100% if there's no associated additive damage.

**Comment by echomirage1** [comment]
@darktoes No information can mean it is bugged or not displayed. Now that the arrows work differently than bullets, it is more important to actually display data. I thought that the two bolt types were missing their data sheet.

**Comment by darktoes** [comment]
It's sensible so long as you understand how the game works, but I agree it would probably be weird for players. I mean, I get what you're saying, I'm just a little surprised it's an issue.

**Comment by JamesStrife** [comment]
Looks like this should be closed once 29814 is tested to work as it should be resolved with the issues linked below so that if the Prop_Damage stat is missing then the formula defaults to 1.00(100% of weapon stats)

Issue: https://github.com/CleverRaven/Cataclysm-DDA/issues/29811
PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/29814
