### ISSUE TITLE
The volumes of pole arms and other weapons crafted from long stick should be increased to somewhat match long stick's volume.

### ISSUE THREAD

**Issue by JerryLin1** [CleverRaven/Cataclysm-DDA#29829]
**Is your feature request related to a problem? Please describe.**  
#24595 added long sticks to multiple pole arm recipes, but the volumes of the weapons have not been updated to reflect this. For example, long stick currently has a volume of 2.5L, while wooden spear has a volume of 1.25L. While a small bit of volume loss would make sense due to refining, losing half the volume is unrealistic. It also puts it at the same volume of heavy stick. Another strange thing you can do is craft multiple knife spears (volume of 1.25L), then disassemble them back into long sticks and end up with double the amount of volume taken up.

**Describe the solution you'd like**  
Increase the volume of weapons that are crafted from long stick to better match their actual size.

**Comment by SirPendrak** [comment]
Keep in mind that volume of weapon affects its performance, and sometimes compromises need to be made. It might be better to do the other way arround, and change long sticks volume, or change some other stats of theese weapons to compensate.

**Comment by kevingranade** [comment]
You can no longer disassemble spears back into long sticks AFAICT, and the volume *loss* from cutting a stick down to be a spear shaft is intended.
