### ISSUE TITLE
Failed crafting with an infinite water source returns unused water to the player 

### ISSUE THREAD

**Issue by Yunatan** [CleverRaven/Cataclysm-DDA#29841]
**Steps to reproduce the behavior**  
1. Fail to craft something that requires water (e.g. pine needle tea) using an infinite water source (e.g. shallow water tile)
2. Be asked "What to do with the water (1)?"

**Expected behavior**  
I expect unused water to go back into the shallow water tile automatically.

**Screenshots**  
![image](https://user-images.githubusercontent.com/6611291/56538683-5e088200-656c-11e9-979e-280c522d1bb7.png)

**Versions and configuration:**
 - OS: Windows 10
 - Game Version: 0.D-2107-gf1de98d (tiles)

**Comment by adamkad1** [comment]
it kinda makes sense, you draw water from the tile, and if you use it or not use it, you have that water

**Comment by Yunatan** [comment]
Yeah, but it is not adding anything besides additional key presses to manually pour water back into the pool. Might as well make player draw water manually before each crafting attempt (please don't).

**Comment by adamkad1** [comment]
you technically draw water manually, just its included in crafting

**Comment by ifreund** [comment]
It makes sense to automatically pour water into adjacent infinite water sources if present.
