### ISSUE TITLE
Zombie Spaw is broken

### ISSUE THREAD

**Issue by Luiizz** [CleverRaven/Cataclysm-DDA#29844]
Game version: #8824
Operating system: Win 10
Tiles or curses: Tiles
Mods active: No Fungal Zombies, Safe Autodoc,, DP_RP REMIX Indicators

Base is always surronded by skeleton dogs and skeleton dogs only.

### Actual behavior: Base is always surronded and using debug kill all only works for a few turns, after that more just come from the woods.

![Screenshot_1](https://user-images.githubusercontent.com/39201027/56543569-330c3700-6548-11e9-8cf3-ac673f9a20c2.png)

**Comment by keupo** [comment]
Un-pulped zombies seem to reanimate repeatedly leading to enormous numbers of zombies near turrets, dissectors, animals etc. I've found lab rooms with literally thousands of dogs. Here's a clip with thousands of zombies in town: [https://clips.twitch.tv/AbstruseLitigiousChowderKeepo](https://clips.twitch.tv/AbstruseLitigiousChowderKeepo); note wander spawns were off.

It doesn't seem to be every un-pulped zombie, but it's pretty frequent. I seem to see it after reading/training following raiding. I guess giving time for them to multiply. Time on a different z-level may well be related, as I've encountered the problem in labs and while living above a garage.

I suspect what's happening is that a single un-pulped corpse is reanimating every time it's time for a corpse to reanimate, and would expect it to reanimate once per death.

**Versions and configuration:**
 - Mac OS 10.14.4
 - Game Version: 0.D-2165-geea880c044 and 0.D-1860-ga011d43925
 - Tiles
 - All default Mods included in the homebrew distribution active

**Comment by niglow** [comment]
Strange things are happenning indeed.

Here's the setup: zombie scientist corpse to the north, zombie dog corpse - to the south, regular zombie corpse - to the east, me & my keg of beer & some jerky - in the center.

![Bug_01](https://user-images.githubusercontent.com/5590079/56690073-47d20180-66e5-11e9-91f7-9682762dc8b0.jpg)

After waiting a while:
![Bug_02](https://user-images.githubusercontent.com/5590079/56690170-7d76ea80-66e5-11e9-81b8-bbaba71a3589.jpg)

Another attempt:
![Bug_03](https://user-images.githubusercontent.com/5590079/56690182-85368f00-66e5-11e9-83b2-f6789d0e137c.jpg)


During other attempts one scientist corpse revived as four zeds and one time a regular zed revived as a skeletal juggernaut.

Feel free to reproduce:
[Robinsonville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3113963/Robinsonville.zip)

**Comment by niglow** [comment]
Strange things are happenning indeed.

Here's the setup: zombie scientist corpse to the north, zombie dog corpse - to the south, regular zombie corpse - to the east, me & my keg of beer & some jerky - in the center.

![Bug_01](https://user-images.githubusercontent.com/5590079/56690073-47d20180-66e5-11e9-91f7-9682762dc8b0.jpg)

After waiting a while:
![Bug_02](https://user-images.githubusercontent.com/5590079/56690170-7d76ea80-66e5-11e9-81b8-bbaba71a3589.jpg)

Another attempt:
![Bug_03](https://user-images.githubusercontent.com/5590079/56690182-85368f00-66e5-11e9-83b2-f6789d0e137c.jpg)


During other attempts one scientist corpse revived as four scientists and one time a regular zed revived as a skeletal juggernaut.

Feel free to reproduce:
[Robinsonville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3113963/Robinsonville.zip)

**Comment by Hirmuolio** [comment]
I tried to look at the corpse multiplying on revive. But I can't make any sense of it.

What happens normally:
`process_item()` runs. It calls `process()`. Corpse revives and `process()` returns true. The corpse is removed.

What happens with the bug:
`process_item()` runs. It calls `process()`. Corpse revives and `process()` returns true but actually returns false. The corpse is not removed.

I have no idea how the `process()` is returning false.
I even added an extra msg there like this. The message prints but the function returns false.

    if( is_corpse() && process_corpse( carrier, pos ) ) {
        add_msg( _( "Returning True" ) );
        return true;



Also the bug seems to happen only if the zombie was killed "normally". I have not seen the bug happen to any zombie that was killed with the debug menu.
