### ISSUE TITLE
Telling a follower to use a serum crashes the game

### ISSUE THREAD

**Issue by adamkad1** [CleverRaven/Cataclysm-DDA#29843]
**Describe the bug**  
Telling a survivor to use a serum crashes the game

**To Reproduce**  
1-Aquire serum
2-Aquire friendly NPC
3-Tell them to use serum
4-Profit. Or rather lack thereof

**Expected behavior**  
NPC uses serum

**Actuall behavior** 
game crashes

**Screenshots**  
https://i.imgur.com/AzyH23H.jpg

**Versions and configuration(please complete the following information):**
 - OS: Win 10
 - Game Version: 8827
 - Graphics version: Tiles
 - Mods loaded: Tried on a vanilla world

**Additional context**  
Tried giving them a syringe and then telling them to use it, no change. Npcs probally cant use syringes in that way

**Comment by neitsa** [comment]
Can't repro on `0.D-2341-g1c62c69e96` (8857).

So I'm with a friendly NPC; I have two `test tube of mutagenic serum` on me. 

First `h` (`hold onto this item`) (just to try if it could trigger something): 
![image](https://user-images.githubusercontent.com/4538670/56866815-2a9b7c80-69de-11e9-8e8e-e6f4c666ac7e.png)

Then `g` (`I want you to use this item`):
![image](https://user-images.githubusercontent.com/4538670/56866808-18b9d980-69de-11e9-8077-be0d7a210d02.png)

Then he gets new mutations, as expected:

![image](https://user-images.githubusercontent.com/4538670/56866847-66cedd00-69de-11e9-8bed-c2843c9f469f.png)

**Comment by neitsa** [comment]
If you can still trigger it on your actual game, could you please upload your save file and you crash log?

**Comment by AMurkin** [comment]
Was fixed by #29953.
