### ISSUE TITLE
Rotten Tainted Fat unusable for Tainted Tallow (Build 8829)

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#29850]
**Describe the bug**  
Not sure if related to #29770 but in current PR 8829 - Rotten Tainted Fat is unusable for Tallow/Oil but Rotten Tainted Meat is still usable for dehydration, pheromone etc. Please inform if intentional.

**To Reproduce**  
1. Harvest Fat from (Zombie) corpse and allow to rot. Fat becomes unusable for Tainted Tallow Recipe.

**Versions and configuration(please complete the following information):**
Build via Game Launcher: (8829)

**Additional context**  
Please advise if any additional context is required.

**Comment by communistkiro** [comment]
Anything with a `rotten` and/or `dirty` flag/s is unsuitable for crafting.

It'd be reasonable to have certain items reset after undergoing some treatment, i.e., a dirty wristwatch _not_ yielding dirty whatever, or a dirty silver tie pin yielding 20 dirty silver. I mean, silver and copper have antibacterial properties irl, yet a little direct can't be brushed off with a hand or a rag. I'm not suggesting to be able to `wash` metal or solid items with rags, just to not have them be able to get `dirty`. 

A bug (or trick, if you will)- load dirty thread into something with a `sewing` quality, then unload it to get non-dirty thread/ yarn/ plant fiber.

**Comment by Xpyder** [comment]
Well, in the case of food, rate of spoilage is dependant on how compromised it is with microorganisms, with them multiplying exponentially over time.  Cooking it kills much of the existing population, setting them back quite a bit but at the same time makes it easier to digest allowing them to accelerate faster.

Short of some very complex modeling, I think the easiest way to handle this (should we decide to) for food, would be for cooking, curing, etc to restore a % of it's current rottenness.  This creates diminishing returns for multistage items, and paired with faster spoiling for cooked but uncured items seems more realistic

**Comment by Xpyder** [comment]
Also `dirty` should be broken out into a separate PR, as that was primarily to address a vast overabundance of clothing materials that was unbalancing the game

**Comment by Xpyder** [comment]
I just thought of something, if we do decide to have processing of a partly spoiled item restore some of it's vitality and we wanted to get advanced with it, we could do the following

Restore a % of current rottenness
Separate the rottenness 
 - reducing calories, value, weight, volume, etc by that amount
 - generate butchery refuse (rotten) with matching volume as byproduct
proceed as normal
print to log something like "you toss away the rotten bits" so the player intuitively understands why the volume/kcal dropped and realizes we generated byproduct

**Comment by pjf** [comment]
Oh hey, I did the pull request for this one (PR #29808). The *only* change I made was to the lamp oil recipe, allowing rotten fats to be rendered to lamp-oil directly, albeit at a lower recovery rate. The rationale behind this [is described in the PR itself](https://github.com/CleverRaven/Cataclysm-DDA/pull/29808).

Also apologies in advance that I may be slow with replies; I'm in middle of relocating from Australia to Seattle.

**Comment by evankimori** [comment]
> Also apologies in advance that I may be slow with replies; I'm in middle of relocating from Australia to Seattle.

Best of luck with the move! Lucky to see a new land! :D Best of luck and make sure you get some rest and recovery time post-move!

> Oh hey, I did the pull request for this one (PR #29808). The only change I made was to the lamp oil recipe, allowing rotten fats to be rendered to lamp-oil directly, albeit at a lower recovery rate. The rationale behind this is described in the PR itself.

If that's the case and we can still have a use for the (Rotten) Fat aside from the missed opportunity for Tallow (Either Normal or Tainted) due to rotting/time - I'm fine with the PR change. Just means that there's an opportunity cost AND the fact that Tainted Fat isn't exactly -rare- by any standard anyway.

Partially my fault for misunderstanding the changes in PR#29808 in the first place. 

I think with @pjf reply there that this issue can be considered closed.
