### ISSUE TITLE
Keep original pickup items function on pressing `,`

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#29856]
**Describe the <s>bug</s>**  
#29845 introduced the `g` hotkey for picking up items from nearby locations. It's nice and useful <s>but I guess the intention was to keep the  original functionality of `,`</s> Right now, they both work the same way.

edit: I see now, that `,` and `g` shared Pickup Item action from the beginning but I never used `g` so it felt weird. So not a bug, but can we maybe have that action split to keep the original pickup from below you function on pressing one of the hotkeys and the new function on the other hotkey?

<s>**To Reproduce**  
1. Try to pickup some stuff with more items around you using the `,`
</s>

**<s>Expected</s> Requested behavior**  
`,` picks up items from the tile you are standing on
`g` is for nearby items. 

**Versions and configuration(please complete the following information):**
 - OS: Win7x64
 - Game Version: [build 0,D-8830]
 - Graphics version: [Tiles]

**Comment by halfahermit** [comment]
I think leaving `g` as pickup adjacent and restoring the old behavior to `,` makes sense.

**Comment by ifreund** [comment]
I can do that, It seems a little silly that we have two default hotkeys assigned to the same action anyways.

**Comment by evankimori** [comment]
Came to ask this same question. I don't mind the 'g' functionality but it's a little cumbersome and annoying to have to choose a direction every time to pick up something. I didn't mind the previous system as it was since you could just use Advanced Inventory to pick up all around you but I understand the design idea behind this change.

Better yet if there was a menu option to turn it off entirely...but that's probably just me nitpicking.

**Comment by halfahermit** [comment]
One more suggestion - don't auto-pickup single items with adjacent grab, since it's often not possible to tell what an item is from sight. Most obvious in ascii since so many things share symbols, but pretty common in tilesets also.

**Comment by ifreund** [comment]
>One more suggestion - don't auto-pickup single items with adjacent grab, since it's often not possible to tell what an item is from sight. Most obvious in ascii since so many things share symbols, but pretty common in tilesets also.

Done

**Comment by halfahermit** [comment]
Cool, thank you. Great qol feature.

**Comment by kevingranade** [comment]
Pondering this and a bunch of other feedback around it, I think what we really want is:
'g'rab ->
If the player is "standing on" the only item in reach, just pickup
otherwise lists ALL adjacent items in one menu for selection and pickup

',' gets freed for use by something else.

**Comment by evankimori** [comment]
Isn't that first suggested feature just the same as using (A)ll and (I)inventory in the Advanced Inventory screen and just picking up what you want or using (,) in the AI menu anyway?

**Comment by halfahermit** [comment]
>otherwise lists ALL adjacent items in one menu for selection and pickup
I kind of like having to choose a direction. It's more immersive. And I could see the pickup menu getting cluttered if it's not filtered by direction, if you're surrounded by zombie corpses or something.

**Comment by tinukedaya** [comment]
I really like to option to just pickup items from the tile I'm standing on without the clutter of all surrounding tiles. When I know where is what in my base / or I want to pickup the item I wielded before I had to grab my weapon quickly, I do not want to search through all items on all surrounding tiles. I have the advanced inventory for that.

**Comment by halfahermit** [comment]
How about - 
`,` works the same as it did before (pick up current tile).  
`g` works exactly the same as `e`, except:
- It ignores any examine functions
- auto select direction if there's only one
- You can press `g,` (or something, probably shouldn't be a letter) to pick up items in all directions.

**Comment by tinukedaya** [comment]
I like that a lot!

**Comment by KurzedMetal** [comment]
I want my `,` back :'(

We already have Advanced inventory to manage adjacent tiles, I think this new default it's too similar to Adv Inv.

I feel that new behavior on `g` and old behavior on `,` would be the best of both worlds

**Comment by tinukedaya** [comment]
Yeah... I keep struggling with this as well... I miss the ability to just pickup anything I'm standing on without the additional key presses...
