### ISSUE TITLE
Psychopaths get mood penalty for grave digging

### ISSUE THREAD

**Issue by FrozenSnowFox** [CleverRaven/Cataclysm-DDA#29854]
**Describe the bug**  
According to the PR that added gravedigging #28803 people with the psychopath trait should not get morale penalties for grave digging.  Despite that they still get a hefty negative mood debuff.

**To Reproduce**  
Create a new character with the psychopath trait, wish for shovel, find a cemetery and dig up bodies.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2121-g501d9a2

**Comment by TartarusKelvin** [comment]
Currently looking into it should have fix soon
