### ISSUE TITLE
Items that have refittable description can't be refitted

### ISSUE THREAD

**Issue by communistkiro** [CleverRaven/Cataclysm-DDA#29852]
**Describe the bug**  
With the `Tiny` mutation I can't get a military rucksack to not be `oversized`. Thought it might be because I was wearing it, it might have been reinforced, can't remember. Debugged in a fresh one in inventory and tried again, it got reinforced, but not undersized. Same goes for a dust mask. Both had the `this item can be refitted` string in the description. 

**To Reproduce**  
1. Be tiny.
2. Get mil. rucksack, dust mask, possibly other items, too?
3. Repair/ reinforce them/ single use of thread on them -but it doesn't work, hence extra encumbrance.

**Expected behavior**  
If it can be refitted, it should be refitable. _Perhaps an extra tailoring option RESIZE (to current char's size) would be suitable, rather than expecting the game to do it for you._ I'd understand why a container wouldn't be refitable, it has a certain volume, but that could be reduce by a percentage, just to get the encumbrance down.
d
**Versions and configuration(please complete the following information):**
 - Game Version: 0.D-2902-gdf6c61e

**additional**
I don't really know how resizing works other then that a description is provided on some items and that i can work, or not work. Is a certain level of tailoring as is for modification, i.e., lining with x necessary? Is it percentage based? It'd be appreciated if these thing were in the `texts`, `hints` files or elsewhere in-game.

**Comment by Night-Pryanik** [comment]
Military rucksack can't be refitted at all:
![изображение](https://user-images.githubusercontent.com/11132525/184636209-fb11ab95-f560-46b4-8070-639ef125e40f.png)

Dust mask can be refitted:
![изображение](https://user-images.githubusercontent.com/11132525/184636331-4a487684-3b5e-4fb6-8937-f74807d6b708.png)

Right now I'm closing this issue, but if there's examples of non-refittable items that should be refittable, ping to reopen.
