### ISSUE TITLE
Inactive lightstrip (900/900) produces light

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#29862]
**Describe the bug**  
Found in a mansion basement.

**Versions and configuration(please complete the following information):**
0.D-2107-gf1de98d872-dirty

**Additional context**  
[2019.04.23.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3108047/2019.04.23.zip)

**Comment by Night-Pryanik** [comment]
It's not an _inactive_ lightstrip. Inactive variants have `(inactive)` suffixes next to their names.

There is a bug though, it doesn't spend any charges.
