### ISSUE TITLE
Crazy Cataclysm: Mr. Skeltal tries to produce too many minions, which leads to error messages.

### ISSUE THREAD

**Issue by HeadstrongCatgirl** [CleverRaven/Cataclysm-DDA#29868]
**Describe the bug**  
Whenever there's a mr.skeltal in my reality bubble I get error messages saying that the game is unable to spawn a zombie. 'I' works for a while, but then those messages return. Can we somehow limit the amount of minions?

**To Reproduce**  
1. Be near mr. skeltal for a few days.
2. Get a ton of error messages.

**Expected behavior**  
No error messages.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Debian stable
 - Game Version: 0.D-2092-gdf6c61ec29
 - Graphics version: curses
 - Mods loaded: Crazy Cataclysm

**Comment by neitsa** [comment]
Is the message `There's already a monster at <location>`? if yes it's a duplicate of #29146

**Comment by BevapDin** [comment]
Fixed by #32210.
