### ISSUE TITLE
Pressing `,` doesn't pop up vehicle interactions on a tile with controls

### ISSUE THREAD

**Issue by Informalis** [CleverRaven/Cataclysm-DDA#29864]
**Describe the bug**  
While standing on a tile with vehicle controls and pressing the pickup item (default ```,```) key, the game tries to pick up items, instead of offering to interact with the vehicle, while the examine key (default ```e```) key plus the keybind for directly below (default ```5```) works.

Additionally, the introduced behavior doesn't pick up items in a container (in this case a reclining seat with a blanket and pillow) the avatar is standing on.

**To Reproduce**  
1. Stand on a vehicle tile with controls.
2. Press ```,``` to try to interact with the vehicle as the tool tip for the ```controls``` vehicle part suggests.
3. Get a log message that there's no items to pick up.

**Expected behavior**  
Get the vehicle interaction options pop up menu.

**Versions and configuration**
 - OS: Windows 10 Home x64
 - Game Version: 0.D-2165-geea880c (Build 8831 on the CI)
 - Graphics version: Tiles
 - Mods loaded: [
  "dda",
  "no_npc_food",
  "growable-pots",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "mutant_npcs",
  "alt_map_key",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "novitamins",
  "StatsThroughSkills"
]

**Comment by ifreund** [comment]
As far as I know, the fact that `,` worked to access the controls was a side effect of the way `Pickup::pick_up()` and `vehicle::interact_with()` were structured.  It also makes more sense in my opinion to have `g`/`,` be exclusively for picking up items, while `e`xamine is for interacting with things.

I'll add a commit updating the tool tip to reflect the new behavior.

>Additionally, the introduced behavior doesn't pick up items in a container (in this case a reclining seat with a blanket and pillow) the avatar is standing on.

This should be fixed by  #29865

**Comment by l29ah** [comment]
Also it's no longer possible to pick stuff up from counters with `,`.

**Comment by l29ah** [comment]
So, how do i interact with vehicle controls located on the tile i'm on these days?
