### ISSUE TITLE
Split out professions.json into several files

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#29861]
**Is your feature request related to a problem? Please describe.**  
Recently, I saw that the professions.json file included with the game is alarmingly big

**Describe the solution you'd like**  
Please split this JSON file into several smaller, ideally categorized files.

**Describe alternatives you've considered**  
Not doing this is also fine, I suppose. Nothing is actually broken.

**Additional context**  
It's a big file. Whoever does this will probably want to use a script to automate this process. Python supports JSON structures natively, just as a suggestion.

**Comment by kevingranade** [comment]
No real justification or plan for making the change.
