### ISSUE TITLE
More customizable auto-pulping options?

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#29877]
**Is your feature request related to a problem? Please describe.**  
With the addition of #29586, pulping a corpse now significantly decreases the possibility of getting a CBM. This makes it very important to avoid pulping the corpses of any zombie you want to dissect for CBMs. At the moment, auto-pulp has no options for differentiating between valuable and non-valuable corpses with regards to their potential for CBM's, so if I see a potential dissection target I have to revert to manually pulping everything in the area to be safe.

**Describe the solution you'd like**  
An option to avoid pulping corpses where dissection of an un-pulped corpse may yield greater rewards while still pulping the useless ones.

**Describe alternatives you've considered**  
A whitelist functionality much like auto-pickup would be more powerful, but less accessible.

**Comment by Night-Pryanik** [comment]
> An option to avoid pulping corpses where dissection of an un-pulped corpse may yield greater rewards while still pulping the useless ones.

How would newbies know why technicians (for example) corpses are valuable? Looks like a meta-gaming to me. Newbies would be asking "Why auto-pulp don't pulp this particular corpse?"

**Comment by Yunatan** [comment]
Yeah, a whitelist functionality makes more sense considering the meta-gaming issue.

**Comment by MrHrulgin** [comment]
I'm torn on the meta-gaming issue, as I learned about some of the plants I could harvest by turning on auto-gather and walking through a forest. I'm not sure that there's zero value in providing opportunities for learning for people who go through the options and read all the tooltips.

**Comment by Kitaragna** [comment]
There's simply no reason to this. Now you'll have to implement whitelist functionality, meanwhile auto-pickup has never gotten a whitelist. You can't even tell followers to stop picking up filthy objects. I get that you view anything that's not "realistic" as a problem, and that's okay, but fixing a problem only to create new ones isn't the way to go. Implement a whitelist system first before making a change like this. 

It's not just player-based autopulp. It also applies to followers. Am I supposed to go through the entire dialogue menu with a follower of mine when I kill a technician or a shocker? Way too long.

**Comment by MrHrulgin** [comment]
@Kitaragna I think you're commenting in the wrong place. For one thing, there is a auto-pickup whitelist, (hit Esc., and it's #3 on the list) and you can absolutely tell your followers to ignore filthy gear (talk to your follower, [i] for misc. rules, [i] again for pickup rules, add a rule to exclude "*filthy*"). For another, this issue is for talking about ways to make it possible to avoid pulping the zombies you want to retain whole, not complaining about the change that led to this discussion. 

I do agree that the auto-pulp settings should propagate to any followers without having to set that on a NPC by NPC basis, but getting NPCs to behave in a standardized way is far beyond the scope of this particular issue.

**Comment by echomirage1** [comment]
It's not a solution, but it makes easier if you bind auto-pulping to a hotkey, and start pulping after you have finished dissecting the valuable corpses.

**Comment by MrHrulgin** [comment]
Thank you. That definitely makes the wait for a resolution a bit easier.
