### ISSUE TITLE
Strange multiplying spawns issue

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#29881]
**Describe the bug**  
This is an odd bug I've seen reported by multiple users with varying mod configs. Essentially, an extreme amount of enemies of varying kinds spawn all at once, and seem to have odd interactions with the reality bubble, duplicating when leaving or reentering it, or in one reported case immediately reappearing in full when killed via debug commands. Examples below:

Zombie dogs in a mansion, reported by Lurak
![image](https://user-images.githubusercontent.com/19789267/56645835-00ca1900-66b1-11e9-9b5b-7cd65bfec250.png)

![image](https://user-images.githubusercontent.com/19789267/56645865-10496200-66b1-11e9-9912-cac10aadb82e.png)

Assorted zombies (mostly bio-ops) in a research lab, reported by Marionette, using build 8804:

![image](https://user-images.githubusercontent.com/19789267/56645910-248d5f00-66b1-11e9-85fd-095d2a2f895b.png)

![image](https://user-images.githubusercontent.com/19789267/56645926-2e16c700-66b1-11e9-9e2f-527c101a781c.png)

![image](https://user-images.githubusercontent.com/19789267/56645944-34a53e80-66b1-11e9-8229-369935e07be7.png)

![image](https://user-images.githubusercontent.com/19789267/56645969-3c64e300-66b1-11e9-821c-f2f8662a8949.png)

Marionette's modlist:
[
  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "bio_mod",
  "makeshift",
  "More_Survival_Tools",
  "alt_map_key",
  "npc_traits",
  "craftgp",
  "Mining_Mod",
  "growable-pots",
  "manualbionicinstall",
  "safeautodoc",
  "modular_turrets",
  "Salvaged_Robots",
  "mutant_npcs"
]

There are several other cases that have been reported on discord, but I haven't been able to get much information from the players involved.

**To Reproduce**  

I have no idea how to reproduce this. I'm just reporting on behalf of several people in Discord without github accounts.

**Comment by ktoma36** [comment]
Here's a copy of my save file for those wishing to tinker with it (Build 8804)
[Marionette's Borked Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3110614/Marionette.s.Borked.Save.zip)

**Comment by Inglonias** [comment]
Related to #29844 ?
