### ISSUE TITLE
A suggestion regarding stomach contents

### ISSUE THREAD

**Issue by dom4op** [CleverRaven/Cataclysm-DDA#29888]
**Is your feature request related to a problem? Please describe.**  
Lack of feedback while eating remains a problem. Of course you shouldn't know in details what's going on inside your stomach atm, but in the current implementation you can devour massive amount of food and the game won't give any signs about how full you are until you can't eat any more. Even then, it's possible that your hunger meter will still be at "hungry", but the game will give warning about "you're forcing yourself to eat".

Bottom line, the system is still confusing.

**Describe the solution you'd like**  
Flavour messages seem like an easy solution. Let's say your char got the "Very Hungry" status and his calorie storage is at 30% of maximum value. When you eat a slice of pizza, you'll get the "you devour your pizza with great appetite". A few slices later, you'll get another message, something like "you enjoy eating your slice of pizza" or something like "you try to ignore the awful taste of rotten chunk of fat while you eat it". When you're closer to full, it should be something like "swallowing your chunk of raw human meat takes some time and makes you want to burp". Alas, I am no native english speaker, so it would be better if someone else came up with specifics.

I believe that every person can feel when it's hard to take another bite. But the game sends you a warning ONLY at the point when eating something else will likely lead to throwing up. It doesn't work that way IRL. All of us have a vague idea when we're still hungry, hungry a bit less and finally when we're full.

**Describe alternatives you've considered**  
Copy-paste those messages from Unreal World? They vary depending on how tasty the food you eat and how hungry you are.

**Additional context**  
I am totally okay with new system in general and don't mean to offend anybody. Just making a suggestion that in my opinion will improve the overall experience and is not too hard to implement. Especially considering the huge amount of work already being done to the new system.

**Comment by Inglonias** [comment]
The biggest reason there's no feedback right now is because eating food is basically instantaneous. If you could eat a whole pizza instantly IRL (I mean instantly teleport it from your mouth to your stomach), it would take a few seconds for the feedback to reach your brain. That's essentially what's happening.

There are plans to make it so that eating takes time, which I think will greatly help with this problem.

**Comment by Yunatan** [comment]
Just make stomach contents and calorie storage displayed via bars. Why would you have an idea of your limbs health but not you digestive system status?
