### ISSUE TITLE
'E'at menu displays '<_COLOR_C_LIGHT_GRE…' strings for vehicle parts

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#29889]
**Describe the bug**  

When opening the 'E'at menu, vehicle parts show as `<COLOR_C_LIGHT_GR…` instead of the name of the part itself.

It looks like this was introduced as a side-effect of #29817 in commit eea880c04433a292a44c9af509ae59e0900788bc, a change that I am eternally grateful for, and which is well worth putting up with a minor UI artefact. :)

**To Reproduce**  

1. Store food in a vehicle part
1. Open the 'E'at menu.
1. Look at what the vehicle part is called.

**Expected behavior**  

The vehicle part's name is shown.

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 16.04, x86
 - Game Version: 0.D-2184-ge124e8d8ba (local fork from 0269b1b183182ec61ddfd31ae5b48e04d5b2c87f)
 - Graphics version: Tiles
 - Mods loaded: No NPC Needs, filthy clothing

**Additional context**  

Tagging in @esotericist as the local expert and author of the amazing vehicle part status changes.

**Comment by esotericist** [comment]
Thanks for tagging me on this, although I dunno how I feel about being labeled 'expert'.
