### ISSUE TITLE
Rotten vegetables on dirt have a chance to seed?

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#29880]
**Is your feature request related to a problem? Please describe.**  
I find it frustrating to run across a community garden a couple of weeks into a run only to find it entirely bereft of plants.

**Describe the solution you'd like**  
I would like a mechanism that sustains access to a wider variety of plant seeds further into a run, rather than depending entirely on the rare building that has seed packets. I don't know if it's technically feasible, but the idea that any food that 

A. rots, 
B. can be turned into seeds and planted
C. is resting on the ground 

will have a chance to root as if planted. Given the weeds that I see in cracks in the sidewalk IRL I wouldn't even disbelieve a very rare chance for plants to grow even inside houses, on sidewalks, etc. This does come with the inconvenience that a living plant can't be harvested for seeds prior to harvesting, but the idea of needing to protect it against zombie wandering and come back for a treasured plant in a couple of weeks appeals to me as a concept.

**Describe alternatives you've considered**  
My initial thought was that plants could rot directly to seeds, but reading up on seed preservation online makes it clear that in the absence of human intervention (sorting, separating from other vegetable matter, etc.) the only thing veggies would do is try to grow. Depending on enthusiasm for this idea, there may be a separate level of "sprouted" food where the plant is no longer edible or convertable to seed, but could still be planted (onions and potatoes are the two I've seen this with IRL)

**Comment by karekanol13** [comment]
I think this would be a great idea, it's pretty unfortunate to come across a farm and find nothing but rotten vegetables and fruits that can't be used for seeds anymore for some reason.
