### ISSUE TITLE
Reflectors. Driveway Reflectors / Pole Reflectors / Patch Reflectors

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#29897]
I had an idea when traveling with one of my NPC's at night during the early game. Often you can not see them or where they are because they follow a few steps back. I thought to add an item "Reflector" to the game that will illuminate 1 tile if there is sufficient ambient light, like moonlight and such. They can even be added to all the homes with garages so that with a flashlight on you would be able to see 1 tile illuminated and know that that is a house or something.

The best part is you could dissemble these little poles and get the little reflector and then make a recipe that uses it and a string to make "Wearable reflector" and you could then place on each of your NPC's.

The tile that is illuminated should not reveal everything in the tile, just the fact that there is something reflective there. So behind you, you would see in ASCII an illuminated `.` following you. That's your NPC if he's wearing one.

**Comment by kevingranade** [comment]
Interesting idea, I had a similar thought with #22687 relative to monster eyes, the same effect would apply here.
