### ISSUE TITLE
Possibility to hide in a locker (akin to a dumpster)

### ISSUE THREAD

**Issue by Yunatan** [CleverRaven/Cataclysm-DDA#29891]
**Is your feature request related to a problem? Please describe.**  
Hiding in a dumpster is a fun little mechanics to have but, sadly, dumpsters are not very frequently encountered.

**Describe the solution you'd like**  
Hiding in a locker would be a nice way to reuse the aforementioned mechanics as lockers are almost everywhere.

**Describe alternatives you've considered**  
There are probably other furniture inside which you could theoretically hide yourself but locker is the most obvious one. 

**Additional context**  
I got inspiration for this from [Alien Isolation](https://youtu.be/IM61YD0DSfA?t=6). 

**Just a heads-up**  
Player shouldn't be able to hop from locker to locker staying hidden, potentially building long safe-tunnels out of them.

**Comment by Fris0uman** [comment]
This PR #28593 already tries to do that

**Comment by Yunatan** [comment]
Cool, wasn't aware of that. I've left a few notes under your PR, thanks.

**Comment by Yunatan** [comment]
Reopening this feature request as #28593 was closed
