### ISSUE TITLE
Cannot move furniture over spilled liquids

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#29899]
**Describe the bug**  
`There's stuff in the way.`

**Versions and configuration(please complete the following information):**
0.D-2175-gdd04a6bdcc-dirty

**Comment by Night-Pryanik** [comment]
Moving furniture over the liquids could cause all sorts of weird stuff, for example the furniture with `LIQUIDCONT` flag - this will make spilled liquids pickable.

**Comment by Amoebka** [comment]
Moving furniture should just destroy spilled liquid beneath. Obviously, this isn't ideal either, but it's less immersion-breaking than not being able to move tables over wet floors.
