### ISSUE TITLE
Wrong alternative fuel types in engines.

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#29890]
**Describe the bug**  
Diesel engines offer ethanol, methanol and denatured alcohol as alternative fuel type. Gasoline engines offer no alternative fuel types.

**To Reproduce**  
Examine engine tweaking menu and json files :)

**Expected behavior**  
IRL, ethanol is more similar to gasoline than to diesel fuel, and actually gasoline, not diesel engines can accept it as alternative fuel with minimal to no tweaking. [Actually, many gasoline cars run on mixed fuel that consists of gasoline and ethanol nowadays.](https://en.wikipedia.org/wiki/Ethanol_fuel) Lamp oil should be left for diesel engines as it is more similar to diesel than gasoline.

Also, It makes sence to add mixed ethanol-gasoline fuel and biodiesel fuel to the game. (There is a book that allows player to create diesel from fats in the game, but that is actually NOT the diesel fuel, it's [biodiesel](https://en.wikipedia.org/wiki/Biodiesel), another substance with another efficiency values.)

And, finally, It would be right to add a chance for a vehicle to spawn with biodiesel/bioethanol in the tanks instead of diesel/gasoline. And add biofuel pumps to gas stations.
**Screenshots**  
None

**Versions and configuration(please complete the following information):**
 - OS: Any
 - Game Version: 0.D-2175-gdd04a6b
 - Graphics version: Any

**Additional context**  
![Fuel efficiency graph](https://thumbor.forbes.com/thumbor/1280x868/https%3A%2F%2Fblogs-images.forbes.com%2Fjudeclemente%2Ffiles%2F2015%2F06%2FScreen-Shot-2015-06-17-at-9.32.21-AM.png)

**Comment by mlangsdorf** [comment]
You can make all these changes in JSON, so please submit a PR.

Also, CDDA energy density is MJ/L, not MJ/kg, for what little it matters.
