### ISSUE TITLE
Upgrade faction camp radio not working

### ISSUE THREAD

**Issue by Permaphrost** [CleverRaven/Cataclysm-DDA#29909]
**Describe the bug**  
Faction camp won't go past the 19th upgrade where you start the radio tower. NPC goes out and comes back like the mission was done but it just keeps repeating on the bulletin board, halting camp progress.

**To Reproduce**  
1. Make a player and get some NPCs to join you
2. Make faction camp somewhere in a field
3. Do all camp upgrades until you get to the radar mission
4. Do it.
5. Repeat 4

**Expected behavior**  
Ideally also describe *why* you expect it to happen.
I expected the camp to upgrade, perhaps with a radio tower built either on top of the main building, somewhere inside the walls, or outside the walls. Then the camp upgrades would continue. I expected it because the first 18 missions made me expect it. 

**Screenshots**  
![cataclysm-tiles_2019-04-24_18-43-29](https://user-images.githubusercontent.com/49964454/56702808-3ed03880-66c3-11e9-8bfd-7c80d5063880.png)

Also on the box that shows the components needed, I couldn't figure out how to scroll to see the rest of the text, if there even is a way. Had to look at the recipe_construction_om.json to see what was required.

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version: [0.D-2189-gab78130] experimental 8836
 - Graphics version: [Default Tiles]
 - Mods loaded: [DDA, Disable NPC Needs, StatsThroughSkills, Simplified Nutrition, Safe Autodoc, Prevent zombie revivication, No filthy clothing, Manual Bionic Installation, Classic Roguelike Classes, Classes and Scenarios mod, Alternative map Key, Boats]

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

Link to savegame: https://drive.google.com/open?id=1YOdD20IGbO0gaSvDf6_m8gBnTBXIW11L

I kept sending NPCs out on missions perhaps because you need to do it multiple times to "build" the radio tower, but after like 10 tries it still wasn't finished. Not sure why a radio tower would need 10 large wind turbines but I don't know a lot of things.

**Comment by mlangsdorf** [comment]
Pretty sure this is a bug caused by my updating faction camps to update using mapgen_update at the same time that dpwb added radio towers using the old edit_mapgen logic.  There wasn't a merge conflict, but the semantics changed.  It should be a straightforward fix.
