### ISSUE TITLE
Corpses persist sometimes when a zombie revives, it seems

### ISSUE THREAD

**Issue by Little-119** [CleverRaven/Cataclysm-DDA#29906]
**Describe the bug**  
It seems as if, when a prototype cyborg revives, it comes back as a broken cyborg, and when this happens, the prototype cyborg corpse isn't removed.

**To Reproduce**  
1. Kill a prototype cyborg
2. Don't pulp it or anything like that
3. Wait for it to revive
4. Observe the resulting broken cyborg and persisting corse

**Expected behavior**  
Ideally also describe *why* you expect it to happen.

**Screenshots**  
![](https://i.imgur.com/vJAFeKi.png)
This is one of those cyborg holding cell areas you find near autodocs in labs.
All of those missing sprites are cyborgs (electroreceptors mutation).
There were initially two prototype cyborgs and one regular broken cyborg.
I killed them twice, and left them to revive twice.
There are now 8 broken cyborgs.
The prototype cyborg corpses are still there.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: ).D-2189-gab78130
 - Graphics version: Tiles
 - Mods loaded: aftershock, Tolerate_This, realguns, SD_Magcrafting, SD_Magcrafting_Realguns_Extension, makeshift, More_Survival_Tools, modular_turrets, alt_map_key, Mining_Mod, crazy_cataclysm, mutant_npcs, hydroponics, BIGRIVER, Urban_Development, blazemod, boats, deoxymod, No_Anthills, more_classes_scenarios, filthy_morale, sleepdeprivation, No_Fungi

**Additional context**

**Comment by Little-119** [comment]
Actually, now that I've played some more, I think this isn't just for prototype cyborgs. Rather, revivals seem to be duplicating monsters somehow.

**Comment by Hirmuolio** [comment]
Seem like the extra tags on corpses may be causing this somehow. If the corpse is cold it isn't removed when it revives (probably frozen/rotten/old do this too)

**Comment by niglow** [comment]
Looks related to #29844 and #29881

**Comment by Little-119** [comment]
Yeah, those look like they're about the same thing, so I'm going to go ahead and close this
