### ISSUE TITLE
Search in map editor 

### ISSUE THREAD

**Issue by RedBloodCat** [CleverRaven/Cataclysm-DDA#29919]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**  
Search in map editor, train/furn part.
lets say that you looking to spawn an autodoc, it is a pain in the ### to see through everything until you realise it is on the last part. i would like if you could add an search in there (Like you have in mapgen(press /).

**Describe alternatives you've considered**  
do nothing

**Additional context**  
dabugmenue -> mapeditor(G) -> terrain/furn(G)

**Comment by Night-Pryanik** [comment]
Your post is not descriptive at all. Please add more details.

**Comment by RedBloodCat** [comment]
> Your post is not descriptive at all. Please add more details.

updated it now, is it ok now?

**Comment by Night-Pryanik** [comment]
>updated it now, is it ok now?

Yeah, I guess so.

**Comment by kevingranade** [comment]
We dont track feature requests for debug menus.

**Comment by SomeDeadGuy** [comment]
It would be nice feature.
