### ISSUE TITLE
Add cbm spawning on characters in debug

### ISSUE THREAD

**Issue by RedBloodCat** [CleverRaven/Cataclysm-DDA#29918]
Irritating when you need to find/spawn a hospital to install one

an idea could be to add an option in debug to spawn CBM witch is installed, and remove installed CBM in the debug menu.

**Comment by Night-Pryanik** [comment]
There is already Debug CBM Installation mutation. With it you don't need an autodoc to install CBMs.

**Comment by kevingranade** [comment]
We don't track feature requests for the debug menu.
