### ISSUE TITLE
Is there an error that causes the text waiting to be translated

### ISSUE THREAD

**Issue by kwl01skz** [CleverRaven/Cataclysm-DDA#29929]
Game version:
0.D-2218-g31fa3b6

![2019-04-25 23-57-17屏幕截图](https://user-images.githubusercontent.com/1281487/56750811-27727780-67b7-11e9-9895-6545e9604537.png)
  
What happened, so much similar content needs to be translated? Is there any bug?
This reminds me of the elementary school teacher who punish me for copying the text.
lol

The similar repetition appears in "nice to meet you. I gotta go though", etc.

**Comment by BrettDong** [comment]
Seems like contributors had created copies of the same dialogue for each NPC in the refugee center.

```bash
[brett@localhost Cataclysm-DDA]$ cd data/json/npcs/refugee_center/
[brett@localhost refugee_center]$ ls
NPC_Aleesha_Seward.json    NPC_Jenny_Forcette.json
NPC_Alonso_Lautrec.json    NPC_John_Clemens.json
NPC_Boris_Borichenko.json  NPC_Mandeep_Singh.json
NPC_Dana_Nunez.json        NPC_Mangalpreet_Singh.json
NPC_Draco_Dune.json        NPC_Pablo_Nunez.json
NPC_Garry_Villeneuve.json  NPC_Stan_Borichenko.json
NPC_Guneet_Singh.json      NPC_Vanessa_Toby.json
[brett@localhost refugee_center]$ grep -Rl "What's up?" .
./NPC_Garry_Villeneuve.json
./NPC_Jenny_Forcette.json
./NPC_Aleesha_Seward.json
./NPC_Boris_Borichenko.json
./NPC_Guneet_Singh.json
./NPC_John_Clemens.json
./NPC_Dana_Nunez.json
./NPC_Alonso_Lautrec.json
./NPC_Mangalpreet_Singh.json
./NPC_Stan_Borichenko.json
./NPC_Mandeep_Singh.json
./NPC_Vanessa_Toby.json
./NPC_Pablo_Nunez.json
./NPC_Draco_Dune.json
```

**Comment by kwl01skz** [comment]
Is writing code in code so expensive?
I have always thought that the NPC of this game is automatically generated.
This seems to involve the direction of the game, forget it.
