### ISSUE TITLE
Fungal growth causes flammable walls

### ISSUE THREAD

**Issue by Scischm** [CleverRaven/Cataclysm-DDA#29923]
**Is your feature request related to a problem? Please describe.**  
I find it a bit strange that fungal walls are capable of overtaking solid rock or metal and turning
them into a burnable tile.

**Describe the solution you'd like**  
There are a few ways of doing this, but the basic idea is that the game would check if the terrain was "burnable" before the fungal overtake and revert it to that tile type after being burned, or perhaps even add a flag for a "burned" status causing the wall to gain the "scorched" prefix, i.e. scorched rock wall.

**Comment by Zireael07** [comment]
Fungi of CDDA is basically magic, so...

**Comment by Scischm** [comment]
If that is the intended result then it is understandable. I hadn't seen much discussion of the walls being affected so I was unsure if it was an unintended side effect.

**Comment by l29ah** [comment]
It's strange that fungus are able to overtake and permeate solid steel walls at all.

**Comment by Fris0uman** [comment]
Fungus CAN melt steel beams ?

**Comment by cidane** [comment]
> Fungus CAN melt steel beams ?

The NSA / CIA be like: "Hang on right there!"
