### ISSUE TITLE
Interrupted and moved intermediate crafting results vanishes after completion

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#29928]
**To Reproduce**  
1. Start crafting a forge.
2. Interrupt it.
3. Pick the in-progress item.
4. Move 20 tiles away from the place your crafted it at.
5. Resume crafting till completion.
6. Observe it completed and completely vanished.

**Versions and configuration(please complete the following information):**
0.D-2215-g6b8c6f2a60-dirty

**Comment by l29ah** [comment]
Also when i craft hand press & die set it just vanishes whatever i do.

**Comment by ifreund** [comment]
I can't reproduce this, could you provide a save or more specific steps? Did you try updating you game?

**Comment by l29ah** [comment]
[#29928.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3122130/29928.zip)
Yes.

**Comment by l29ah** [comment]
Also you can load [2018.05.06-29928.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3249824/2018.05.06-29928.zip) and try crafting a recharge station.

**Comment by l29ah** [comment]
Damn my forge vanished again! This time w/o any interruptions.

**Comment by l29ah** [comment]
Damn my makeshift welder vanished again!

By the way, every time i was crafting, i was doing it in a vehicle.

**Comment by ifreund** [comment]
>By the way, every time i was crafting, i was doing it in a vehicle.

That's very helpful for trying to reproduce this.  I'm super busy right now but will get back to this before 0.E

**Comment by l29ah** [comment]
Now a clay crucible have vanished when i crafted it in a faction camp tent.

**Comment by l29ah** [comment]
Made a repro:
[2019.07.22.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3438402/2019.07.22.zip)
* load the game
* spawn a heating element
* craft a makeshift welder in your hands
* after it finishes it's gone

**Comment by davidpwbrown** [comment]
I cant repro on new world, but can repro with forge on your save.

**Comment by davidpwbrown** [comment]
ah hah, its the swag bag your character is wearing. which has RESTRICT_HANDS , which means some things cant be wielded, but the crafting code dosnt check for that.
