### ISSUE TITLE
Bicycle engine fails to start and makes a hmm sound while driving

### ISSUE THREAD

**Issue by DanteTorn** [CleverRaven/Cataclysm-DDA#29934]
**Describe the bug**  

Attempting to drive a pedal bicycle will fail when you first "start it up" and will do so randomly when you try to drive it after stopping. It also creates a humming sound when you are driving around.

**To Reproduce**  

1: Attempt to drive any pedal bicycle as normal
2: Bicycle fails to start, and you let go of the controls 
3: Attempt to drive again, it will work as intended
4: Drive around, get "You hear hmm" as if it has an engine, which happens no matter what
5: This will happen again if you stop driving the bicycle and then get back on it later

**Expected behavior**  

Pedal bicycles don't have engines, thus they should not "fail to start," nor hum while you drive them.

**Screenshots**  

https://i.imgur.com/z0soVoJ.jpg

**Versions and configuration:**

 - OS: Windows 7
 - Game Version: 0.D-2215-g6b8c6f2
 - Graphics version: Tiles
 - Mods loaded: Boats, Folding Parts Pack, Vehicle Additions Pack, Tanks and Other Vehicles

**Additional context**  

Similar bugs were fixed by KorGgenT, as shown here:
https://github.com/CleverRaven/Cataclysm-DDA/pull/28222

It seems that while he stopped the "engine starts up" message, it's somehow still confused and now shows "the engine fails to start" instead. The hmm-ing isn't mentioned though, so it may or may not be a new issue.

**Comment by Night-Pryanik** [comment]
Fixed by #34287.
