### ISSUE TITLE
Quick butchering always finds implants while in fact there are none

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#29936]
**Versions and configuration(please complete the following information):**
0.D-2215-g6b8c6f2a60-dirty

**Additional context**  
[2019.04.23.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3118838/2019.04.23.zip)

**Comment by HeadstrongCatgirl** [comment]
I think it considers zombie pheromone an implant. The only thing dissection yielded on regular zombies was pheromone.

**Comment by KorGgenT** [comment]
so the messages need updating with more generic messages.

**Comment by l29ah** [comment]
Meanwhile i couldn't yield anything when i dissected a few corpses with a scalpel.

**Comment by nexusmrsep** [comment]
> Meanwhile i couldn't yield anything when i dissected a few corpses with a scalpel.

That doesn't mean anything. Did you have a proper skill to do that? Did you have luck to get it? It's not a shop with organs. It was designed to be hard to get pheromones and CBMs, especially pheromones. Even with high skill it's less then 1/4 chance to get them, and with low skill it's futile but a good way to train first aid.

**Comment by xxEntity** [comment]
Although maybe there should be a small chance at finding bionics on NPCs and zombies that wouldn't normally yield a CBM. There would have to be a better way for determining there is a CBM installed other than butchering and finding out after destroying the bionic.

**Comment by Night-Pryanik** [comment]
> There would have to be a better way for determining there is a CBM installed other than butchering and finding out after destroying the bionic.

Only if CBMs are "external" CBMs that are recognizable at first glance, i.e. Telescopic Eyes or Alloy Plating. I doubt one can determine if there is Internal Furnace installed simply by looking over the body.
