### ISSUE TITLE
Partially derrive crafting result properties from the components used

### ISSUE THREAD

**Issue by anonym** [CleverRaven/Cataclysm-DDA#29946]
**Is your feature request related to a problem? Please describe.**  
Currently crafting/cooking a recipe yields a fixed result no matter which components where used, leading to problems like:
* Crafting a duffel bag from leather or tanned pelts that yields rags when disassembled.
* If you have a wool allergy you can't wear that wool scarf, but you can make a blindfold out of it which magically turns it into cotton and then you can wear it.
* Similarly, for cooking you currently can make biscuits (or granola, or fish soup, ...) containing milk without the result having dairy as a material, so lactose intolerance won't trigger.
* To combat these problems there's a maintenance burden for developers in trying to keep the components consistent with the result. This is particularly bad for cooking where all combinations of components should sum up to approximately the calorie/vitamin/mineral content of the result (there's even an automated test for this). And something similar for the result's Material; think about the previous bullet.

**Describe the solution you'd like**  
Instead we could derive certain item values from the components it was created from. I'll discuss how situations in the corresponding bullets above could look under such a system:
* Disassembling a crafted duffel bag returns a subset of the components used when crafting it, so we'd get leather/pelts, not rags. For non-crafted/spawned items it could just pick some random combination of components that satisfies the recipe (so the item would have to reference a recipe) and/or there could be a new field for "default components" which would represent what you'd expect from a store-bought version. An issue might arise can be exemplified with said duffel bag if it itself is used in a recipe and we disassemble the result: we should get the same duffel bag back. So in order to keep this fully consistent in multiple crafting/disassembly steps we would need to store the exact item instances used, so we don't get back "generic" versions. Not sure how bad this would be for performance/memory, but perhaps not so bad since most items are not crafted?
* Items should inherit the Materials from the components, so making a blindfold from a wool scarf will make it unwearable for people characters with wool allergy. 
* Same for food! Making a biscuit from milk will add Diary to its Materials to the detriment of characters with lactose intolerance. (And if animal cooking oil is used, perhaps Flesh should be added?)
* We could largely eliminate the maintenance burden of keeping recipe input and output consistent. Calories could be derived from a sum of its components' calories, possibly with some multiplier > 1 if cooking was involved since that tend to ease digestion → more available calories. The same applies for vitamins, although they should have a < 1 multiplier since cooking breaks them down (IIRC).

I came up with this idea while balancing cooking recipes, and that's where I think this idea would benefit the most given all the effort currently put on balancing cooking recipes, which this would more or less solve once and for all.

As the cataclysm's master chef you might be interested in this one, @KorGgenT.

**Comment by esotericist** [comment]
While I have only skimmed this, some of these things are already true.

The game keeps track of what components are used to craft things, and most especially the nutritional information of food (both calories and vitamins) is *directly* derived from what ingredients were used to make it. This is the very reason it was necessary for me to add a disclaimer to the crafting screen for comestibles.

**Comment by anonym** [comment]
> While I have only skimmed this, some of these things are already true.

Damn, sorry for the noise! I totally admit to not having done my homework and actually trying to understand the code first. I'll close this issue soon and will try to salvage the relevant stuff into new issues.

> The game keeps track of what components are used to craft things

Great news! My duffel bag experiment didn't use proper disassembly, so rather I've found a bug that it is cutting items up that result in this inconsistency.

> the nutritional information of food (both calories and vitamins) is directly derived from what ingredients were used to make it.

While I feel a bit silly for not looking this up, also great news!

I believe my points about Material not being derived still stands. And I should look if cooking (read: heating) affects calories and vitamins.

> This is the very reason it was necessary for me to add a disclaimer to the crafting screen for comestibles.

What crafting screen are you referring to? I've clearly missed it! :D

**Comment by esotericist** [comment]
> Great news! My duffel bag experiment didn't use proper disassembly, so rather I've found a bug that it is cutting items up that result in this inconsistency.

Not so much a bug as a not-yet-implemented feature. As you noted, materials do not currently change based on ingredients. That's desired, we're just not there yet.

> I believe my points about Material not being derived still stands. And I should look if cooking (read: heating) affects calories and vitamins.

To my knowledge, the only actual mechanic we have where the crafting process can change the calorie value of a food/drink is when the recipe has an effect to explicitly override the nutrition of its ingredients. I don't think anyone is opposed to doing more with that, but I'm fairly certain there will not be any support in any such process *increasing* any of the nutritional information over what was in the supplied ingredients to begin with. If anything such a process would be lossy if it were implemented at all.

> What crafting screen are you referring to? I've clearly missed it! :D

I'm referring to my PR here:  https://github.com/CleverRaven/Cataclysm-DDA/pull/29400

and in specific this text here:
![image](https://user-images.githubusercontent.com/1569754/56806998-679b1f80-67e2-11e9-90a4-a9ad36f7d358.png)

**Comment by KorGgenT** [comment]
so referring to food, and not repeating anything esotericist said (all true btw)
the food's material inheritance is not fully implemented, but there is some partial infrastructure there. i have not made it so the material shows correctly in the display, or changed how allergies check materials to apply effects, but when you have a meat allergy, and you eat woods soup only made with eggs in game, you derive all of the nutrition for it, where the meat allergy actually causes individual meat products in the food to lose their nutritional value.

**Comment by anonym** [comment]
Thanks for all the clarifications! Next time I'll do my due diligence in order to not waste any one's time.
