### ISSUE TITLE
Can't batch-disassemble small metal sheets on the ground

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#29954]
**Describe the bug**  
When attempting to disassemble small metal sheets in bulk with the (B) command on the ground, instead of getting the normal "Disassemble everything/Disassemble everything once" menu, I get a prompt only for one small metal sheet.

**To Reproduce**  
1. Drop more than one small metal sheet on the ground.
2. Stand over it and press (B).
3. No option for batch disassembling.

**Expected behavior**  
Getting a prompt for disassembling the whole batch.

**Versions and configuration(please complete the following information):**
 - OS: Win 7
 - Game Version: 0.D-2255-g86cc2e1
 - Graphics version: Tiles
 - Mods loaded: Default mods

**Comment by wapcaplet** [comment]
Confirmed in 0.E-9702-gdc4167363d. This may be because "small metal sheet" is classified as `AMMO` type, and comes in a stack. The same `B`/disassembly behavior occurs with similar items like "chunk of steel" and "lump of steel", which are also arranged in stacks.

**Comment by dseguin** [comment]
Looks like this is fixed currently (as of 44b27ad5d59807c7e6b0246a9cf3e0c5db87027e):

![disassemble](https://user-images.githubusercontent.com/12537966/153118265-ff1a1230-59a2-4f8c-b5ab-c33e7669d02e.png)
