### ISSUE TITLE
Seg Fault when opening status window

### ISSUE THREAD

**Issue by DanielWare** [CleverRaven/Cataclysm-DDA#29951]
**Describe the bug**  
Game crashes when trying to open the character status window. This obviously has something to do with the state of this save since I was able to open the menu earlier in the game no problem.

CRASH LOG FILE: config/crash.log
VERSION: 0.D
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5D5705[cataclysm-tiles.exe+0x1D5705]
    @0x5D62B2[cataclysm-tiles.exe+0x1D62B2]
    SMPEG_error+0x4B034@0xE8DD90[cataclysm-tiles.exe+0xA8DD90]
    _C_specific_handler+0x98@0x7FFDFA4A8068[msvcrt.dll+0x28068]
    _chkstk+0x11F@0x7FFDFD1246AF[ntdll.dll+0xA46AF]
    RtlWalkFrameChain+0x14BF@0x7FFDFD084BEF[ntdll.dll+0x4BEF]
    KiUserExceptionDispatcher+0x2E@0x7FFDFD12341E[ntdll.dll+0xA341E]
    IMG_LoadWEBP_RW+0x3F2C15@0x13930A5[cataclysm-tiles.exe+0xF930A5]
    @0xCC277A[cataclysm-tiles.exe+0x8C277A]
    @0xCC6728[cataclysm-tiles.exe+0x8C6728]
    @0xC0243E[cataclysm-tiles.exe+0x80243E]
    @0x71DEFD[cataclysm-tiles.exe+0x31DEFD]
    @0x7015B6[cataclysm-tiles.exe+0x3015B6]
    IMG_LoadWEBP_RW+0x4EA079@0x148A509[cataclysm-tiles.exe+0x108A509]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFDFCC67974[KERNEL32.DLL+0x17974]
    RtlUserThreadStart+0x21@0x7FFDFD0EA271[ntdll.dll+0x6A271]

**To Reproduce**  
1. Open the character status menu

**Expected behavior**  
The character status menu is opened.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D
 - Graphics version: Tiles
 - Mods loaded: [
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "deoxymod",
  "alt_map_key",
  "modular_turrets",
  "Medieval_Stuff",
  "makeshift",
  "No_Fungi",
  "StatsThroughSkills"
]

**Additional context**  
attached save
[Mount Olivet.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3121822/Mount.Olivet.zip)

**Comment by neitsa** [comment]
Thank you for your bug report!

I haven't been able to repro on `0.D-2255-g86cc2e1a7e`.

Just to be sure that I didn't miss something obvious, by `character status` you mean the `View player info` menu (bound by default to `@`), right?

**Comment by codemime** [comment]
I can't reproduce that either.

**Comment by DanielWare** [comment]
@neitsa yes i am talking about the View player info menu

I backed up my save, deleted 0.D and got a new copy of it. After copying my save over, I can't reproduce it either. Should I close this issue?

**Comment by neitsa** [comment]
Could you let it opened a bit please? I'm going to check the stack trace but this takes a long time since I have to do it manually. The bug might be related to another one or be completely new, in which case we need to know what went wrong. Or it might simply be a [Heisenbug](https://en.m.wikipedia.org/wiki/Heisenbug)...

**Comment by DanielWare** [comment]
Okay I have reproduced it by changing the scaling factor in the graphics to '2x'.

**Comment by neitsa** [comment]
Thanks for reporting the cause of the problem. So, one more dumb question; are you playing on the **stable** 0.D release?

If yes, then this bug was (probably) fixed later in #28953. If no, then its another bug. I still need to check if's the same bug or not than in #28953.

**Comment by DanielWare** [comment]
@neitsa yes, 0.D-8574. I'll try building from source and pulling in #28953 to see if that will fix it.

**Comment by neitsa** [comment]
I can confirm the bug doesn't trigger anymore on the latest experimental, with the scaling factor set to `x2`. It was probably fixed by #28953.

I guess the issue can be closed.

**Comment by DanielWare** [comment]
@neitsa thanks for the help and for the fix! Closing

**Comment by neitsa** [comment]
You're welcome, thanks @DanielWare!
