### ISSUE TITLE
Hydroponics and Modular Turrets mods cause errors related to an apparently missing item, 'lightstrip_dead'

### ISSUE THREAD

**Issue by Little-119** [CleverRaven/Cataclysm-DDA#29950]
**Describe the bug**  
The hydroponics and modular turrets mods seems to be the culprits of several errors mentioning 'lightstrip_dead', probably because this item was removed at some point and their recipes and buildings use those items.

The errors do _not_ occur with this list of mods loaded: `aftershock, Tolerate_This, realguns, SD_Magcrafting, SD_Magcrafting_Realguns_Extension, makeshift, More_Survival_Tools, alt_map_key, Mining_Mod, crazy_cataclysm, mutant_npcs, BIGRIVER, Urban_Development, blazemod, boats, deoxymod, No_Anthills, more_classes_scenarios, filthy_morale, sleepdeprivation, No_Fungi`

**To Reproduce**  
1. Make a world with only Dark Days Ahead and Hydroponics and/or Modular Turrets loaded
2. Attempt to enter character creation
3. Observe errors

**Expected behavior**  
Not encountering errors.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2247-g97d7e5b
 - Graphics version: Tiles
 - Mods loaded (upon first encountering this issue): `aftershock, Tolerate_This, realguns, SD_Magcrafting, SD_Magcrafting_Realguns_Extension, makeshift, More_Survival_Tools, modular_turrets, alt_map_key, Mining_Mod, crazy_cataclysm, mutant_npcs, hydroponics, BIGRIVER, Urban_Development, blazemod, boats, deoxymod, No_Anthills, more_classes_scenarios, filthy_morale, sleepdeprivation, No_Fungi`

**Additional context**

**Comment by Inglonias** [comment]
This occurred in pull #29651. I removed the lightstrip_dead item because I felt it was redundant given the way batteries now work. It seems like I might have been a little wrong on that front and will need to check on lightstrips in general.
