### ISSUE TITLE
Foraging cactus yields poppy buds

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#29955]
**Describe the bug**  
Foraging cactus found in the botanical garden yields poppy buds.

**To Reproduce**  
1. Go to a botanical garden.
2. Forage the cactus.
3. Get poppy bud.

**Expected behavior**  
Not sure, I've never seen a cactus anywhere else in the game, but I wouldn't expect a poppy bud.

**Versions and configuration(please complete the following information):**
 - OS: Win 7
 - Game Version: 0.D-2255-g86cc2e1
 - Graphics version: Tiles
 - Mods loaded: Default

**Comment by TartarusKelvin** [comment]
What item should it be getting instead?

**Comment by TartarusKelvin** [comment]
Will have a PR up tonight turns out cactus is marked as a poppy

**Comment by Zireael07** [comment]
@TartarusKelvin: Spikes of some sort probably :P

**Comment by echomirage1** [comment]
First I thought that the poppy bud is supposed to be there to make mescaline out of the cactus, but then I realized that that's too much of a long shot from anything. I don't think it needs to yield anything, there are several trees in the botanical garden that yield nothing.

**Comment by TartarusKelvin** [comment]
For now I am just adding cactus pads a edible item will look at it later for more spikes in the future
