### ISSUE TITLE
UPS conversion mod don't work

### ISSUE THREAD

**Issue by egorzaderiy** [CleverRaven/Cataclysm-DDA#29961]
**Describe the bug**  
UPS conversion mod don't work. 

- Can't install on pre-patch items;
- Can install but doesn't charge after-patch items

**To Reproduce**  
1. Spawn `Mechanized Infantry Carrier` vehicle
2. Turn on engine and UPS charge station
3. Wish for flashlight and UPS conversion mod
4. Attach mod to flashlight (Can't attach to pre-patch items.)
5. Drop flashlight to UPS recharge station
6. Wait long period of time (i've waited ~16 hours)
7. Item dont charges.

**Expected behavior**  
After patch item should charge, pre-patch item ideally too

**Versions and configuration:**
 - OS: Windows 7
 - Game Version: 0.D-2247-g97d7e5b
 - Graphics version: Tiles
 - Mods loaded: None

**Additional context**  
Pull request: #29651

**Comment by esotericist** [comment]
UPS conversion mod is obsolete. You can put one of the new battery cells in a recharging station, with or without it being in a tool.

**Comment by HKMist** [comment]
UPS Conversion Mod is just break by the battery update and not obsoleted.

One of the main usage of ups conversion is to make tools run on standard battery to able to directly power by UPS/ Bionic power with UPS upgrade, the new battery system just annoy this function of the mod.

Item install with ups conversion mod before the battery update now functioning in a strange way, it will drain its own battery first, when its own battery is out it will start draining UPS/Bionic power until it is off, And if the item is turn off, it won't turn on again until it is recharge even with a UPS.     

Unload a battery to recharge is good but it can't/shouldn't replace the direct supply function. And outright remove everything relay to the mod seem too early, it is better trying to fix it or at least add something to replace the function of the mod first.

**Comment by Zollec84** [comment]
Also using welding rig and kitchen unit directly with "e" says they have 0 charge, while I have more than 250K stored in my vehicle bateries. 
And I just made me a feromagnetic rail rifle and the UPS just wont recharge, so I cant use it.

**Comment by esotericist** [comment]
> Also using welding rig and kitchen unit directly with "e" says they have 0 charge, while I have more than 250K stored in my vehicle bateries.

This is a completely different problem (that I already have a PR submitted for).

**Comment by dunstad** [comment]
I'm pretty sure this issue can be closed. There are other issues such as https://github.com/CleverRaven/Cataclysm-DDA/issues/33968 that highlight remaining problems with UPS modded tools, and the specific case mentioned in the original post here has been resolved for a while.

(The correct way to charge the flashlight in the scenario above, for anyone confused, is to unload the flashlight's battery and put that in the recharging station.)
