### ISSUE TITLE
Appliances in vehicles do not have any charge.

### ISSUE THREAD

**Issue by Rosencratz** [CleverRaven/Cataclysm-DDA#29965]
I converted an armored truck into a mobile base, but after installing the kitchen and chem station inside, I noticed that the hotplates do not have any charges. Yet, when using crafting, they do indeed have charges. 

In order to recreate it, I suppose you could do the same with any vehicle and see if they have any charges in it. The result I'm getting is that I get a text saying that the hotplate does not have enough charges. 

![image](https://user-images.githubusercontent.com/49988651/56842389-36e0e600-68c7-11e9-9fb3-8edc326cdb89.png)
![image](https://user-images.githubusercontent.com/49988651/56842392-3d6f5d80-68c7-11e9-98fa-a92a680c1d57.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-8847
 - Graphics version: Tiles
 - Mods loaded: 
![image](https://user-images.githubusercontent.com/49988651/56842412-6a237500-68c7-11e9-8d00-11624a13d3e6.png)
![image](https://user-images.githubusercontent.com/49988651/56842419-727bb000-68c7-11e9-9a27-82c198a43200.png)
![image](https://user-images.githubusercontent.com/49988651/56842425-7a3b5480-68c7-11e9-9149-11c25b58b3a0.png)

**Comment by anothersimulacrum** [comment]
It looks like the relevant code is on
Lines [1443](https://github.com/CleverRaven/Cataclysm-DDA/blob/feea9e09f84d884c9316bd09d80bb348ac831476/src/vehicle_use.cpp#L1443), [1450](https://github.com/CleverRaven/Cataclysm-DDA/blob/feea9e09f84d884c9316bd09d80bb348ac831476/src/vehicle_use.cpp#L1450), maybe [1454](https://github.com/CleverRaven/Cataclysm-DDA/blob/feea9e09f84d884c9316bd09d80bb348ac831476/src/vehicle_use.cpp#L1454), and [1483](https://github.com/CleverRaven/Cataclysm-DDA/blob/feea9e09f84d884c9316bd09d80bb348ac831476/src/vehicle_use.cpp#L1483).
