### ISSUE TITLE
Lab handheld teleporters do not function

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#29969]
**Describe the bug**  
Lab handheld teleporters used to have 25 charges, now they have zero and cant be reloaded with anything

**To Reproduce**  
1. Spawn a teleporter
2. Try to use it.

**Expected behavior**  
For the teleporter to be usable 25 times instead of zero

**Versions and configuration(please complete the following information):**
 - OS: Windows 10]
 - Game Version: [o.d-2255-g86cc2e1]
 - Graphics version: [Tiles]
 - Mods loaded: [StatsThroughSkills, Urban development,more locations, fuji's more buildings]

**Additional context**  
Probably related to the new way batteries work now?

**Comment by Inglonias** [comment]
I'll look into the cause of this.
