### ISSUE TITLE
Saline Solution being ignored as Salt ingredient. (PR 8848) 

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#29975]
**Describe the bug**  
Saline Solution amalgamated into a container is not selectable as a dropdown option when producing Salt when there is an alternative Salt Water source. (e.g. Swamp)

**To Reproduce**  
Fill a container with 50x Saline Solution and stand in crafting range of Salt Water source (e.g. Swamp) and attempt to craft Salt. No dropdown appears to select Source of ingredients and (Swamp) Salt Water is always chosen primarily. 

Current example is 50 x Saline Solution in a 3L Jar, standing at a campfire in a marsh to craft Salt. Saline Solution is being ignored as a prospective ingredient option. The Salt Water (pool) is automatically chosen.

**Versions and configuration(please complete the following information):**
PR 8848. 

Mod list:
  "dda",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "growable-pots",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "alt_map_key",
  "crazy_cataclysm",
  "Mining_Mod",
  "mutant_npcs",
  "BIGRIVER",
  "boats",
  "deoxymod",
  "blazemod",
  "necromancy",
  "DP_XOTTO_INDICATORS",
  "DP_REMIX_INDICATORS",
  "DP_AMAZING_CHEST_INDICATORS",
  "no_olg_guns",
  "StatsThroughSkills"

**Additional context**  
[Disease.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3123486/Disease.zip)

**Comment by HeadstrongCatgirl** [comment]
What are the advantages of using saline solution instead of infinite salt water?

**Comment by evankimori** [comment]
Nothing really. Just what you find more often since RNG can be a bitch where you spawn - especially in Escape Labs scenarios where Salt is a premium item.

Just brought it up really because it's still a bug and a system not working as it should as far as I can see. :)

**Comment by HeadstrongCatgirl** [comment]
If the system prioritises an infinite source, that is probably intended.

**Comment by evankimori** [comment]
Good point there if there an "infinite source" but I'd still like to have the choice to burn off a resource I have if I want to recover a container/commodity. 

Just because it's by far "infinite" doesn't mean the player shouldn't be given the choice. Not that I'm too great at programming to view the backend of the game to see the truth behind it but let's see if anyone a bit better at this than me can confirm/deny your theory. :)

**Comment by HeadstrongCatgirl** [comment]
If you want to get rid of a liquid, you can unload it on the ground and clean up by moving some furniture over it.

**Comment by ifreund** [comment]
Infinite sources are automatically selected, and that is 100% intended as there is no disadvantage to using an infinite resource.
