### ISSUE TITLE
Error while loading map weights

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [CleverRaven/Cataclysm-DDA#29987]
**Describe the bug**  
While loading a existing map or creating a new character on a new one, the error shown in the screenshot fires. I tested this with a new world with the same settings, so it doesn't appear to be a save issue. This doesn't seem to happen in a mod-less world. 

**To Reproduce**  
1: Create a world with a mod list composed of what is shown below.
2: Attempt to create a character
3: Get booted back to main menu due to error.
I have also included a copy of the world I was using before the bug was introduced.

**Expected behavior**  
Load into game a normal, or load into new character menu, depending upon which is picked.

**Screenshots**  
![image](https://user-images.githubusercontent.com/38237593/56849865-186ef080-68af-11e9-8c91-cb9cdcbc1c0b.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: [0.D-2256-gdbf3bee]
 - Graphics version: [Tiles]
 - Mods loaded: [
  "dda",
  "no_npc_food",
  "aftershock",
  "craftgp",
  "FIC_Weapons",
  "realguns",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "DinoMod",
  "nw_pack",
  "mutant_npcs",
  "MMA",
  "national_guard_camp",
  "BIGRIVER",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "necromancy",
  "StatsThroughSkills",
  "safeautodoc",
  "manualbionicinstall",
  "more_classes_scenarios",
  "Cata++",
  "Bootleg_Walkers"
]

**Additional context**  
[Dr. Light's Laboratory.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3123888/Dr.Light.s.Laboratory.zip)

**Comment by TartarusKelvin** [comment]
Seems like elec_parts has been renamed or removed

**Comment by ZhilkinSerg** [comment]
That is a third party mod issue. Contact mod author to fix it or update your mod if it was already fixed in latest version of the mod.
