### ISSUE TITLE
Aftershock Mod battery crafting error

### ISSUE THREAD

**Issue by YukariMindGap** [CleverRaven/Cataclysm-DDA#29984]
**Describe the bug**  
When i generate a world with the Aftershock mod active, I've got an error about the light battery cell crafting recipe needing charges but its result not counted by charges.

**To Reproduce**  
1. Create a world with aftershock mod installed
2. Try to create a character

**Expected behavior**  
I expect the game to load up correctly

**Screenshots**  
![image](https://user-images.githubusercontent.com/39007766/56848424-10489c80-6913-11e9-8c57-4afe36e55611.png)

**Versions and configuration**
 - OS: Windows 7
 - Game Version: 0.D-2256-gdbf3bee
 - Graphics version: Tiles
 - Mods loaded: dda, aftershock

**Additional context**  
World save:
[Magas Arriba.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3123771/Magas.Arriba.zip)

**Comment by ifreund** [comment]
Should be fixed by #29977
