### ISSUE TITLE
Transcribe Recipes from books to e-ink tablet.

### ISSUE THREAD

**Issue by Greevv** [CleverRaven/Cataclysm-DDA#29996]
**Is your feature request related to a problem? Please describe.**  
Nope.

**Describe the solution you'd like**  
I think we should be able to either transcribe or scan recipes into the e-ink tablet. This would cut down on the amount of books you'd have to keep around. Transcription would take time, obviously, but likely not a lot since you'd be transcribing just the recipes, not the whole book. Alternatively, allow us to use that handy dandy camera feature on the tablet to take pictures of or scan the recipes from the books.

**Comment by TechyBen** [comment]
Could also be a smart phone (the camera version) option. E-ink would use less power when crafting than using the smartphone (due to display tech). Could also use SD cards to upgrade storage size "4 books stored" etc.

**Comment by MrHrulgin** [comment]
Given the current storage capabilities of portable tech, there's no reason to try to constrain the number of books held. Smart phones can hold thousands of pictures effortlessly, e-ink tablets can hold dozens of books with hundreds of pages. If all that is being stored is the recipes and not the full text, I would argue for unlimited storage. If the entirety of the book is being stored for later skill gain, then *maybe* data storage concerns would be an issue after the first dozen books.

**Comment by chaoticidealism** [comment]
Agreed. Have it drain the battery just like any use of the e-ink PC does, and allow unlimited storage capacity. I've got like five hundred books on my tablet right now, and I'm nowhere near its storage capacity. It should require a low-level computers skill check that can reliably succeed around Computers 1 (you do need to be computer-literate to figure out how to scan and convert to PDF, but it's not hard).

**Comment by Gevouden** [comment]
How about a version of the laptop that can do this?

**Comment by TechyBen** [comment]
Did the CDDA world have the internet? We could have HDDs come out of some PCS/Laptops. (Some would be dumb terminals with just OS/browsers on).

Then you could balance it for "hack pro" or a new "data recovery" usb. Crafted with laptop/build a PC with "data recovery PC/laptop". Then use long times (a day or more) to see if the HDDs have data, such as currently the photos/recipes/lore. The majority could end up empty/corrupted (as with SD cards in game currently).

But it would give a long term goal for finding recipes that differs from lab runs (as a lot of my games turn into 100% lab and military lab runs as they are the only places certain things seem to drop).

It would need an average computers skill (the usb would basically do it for you though) and a lot of effort in mechanics to get the power generation up and running. Though the laptop could be a craftable option, similar to how other craft and leave a day items work.

**Comment by Zireael07** [comment]
There's no mains electricity, so I imagine no internet either.

**Comment by TechyBen** [comment]
> There's no mains electricity, so I imagine no internet either.

Sorry, I meant in the past of the CDDA world. As, cache/servers would have info on HDDs. Laptops could have 1 or two recipes after a long process of recovery. Computers could drop HDDs when disassembled, and those would have a chance for a few recipes on them.

**Comment by Zireael07** [comment]
With start time being an option now, we can start up to a year after the cataclysm (= a year after electricity died). I imagine most disks would be dead then. And adding complex code that only makes sense for spring starts (roughly five days after the doom), is well, untenable...

**Comment by MrHrulgin** [comment]
@TechyBen You might consider starting a feature request just for your idea. It definitely has some merit.

**Comment by TechyBen** [comment]
> With start time being an option now, we can start up to a year after the cataclysm (= a year after electricity died). I imagine most disks would be dead then. And adding complex code that only makes sense for spring starts (roughly five days after the doom), is well, untenable...

Disks don't work like that. Providing they are not flooded (rust) they will last decades in cold storage if SSDs or HDDs (SSD can lose their bit coding to age, so may not last as long. HDDs can seize up on the spindle if the oil dries out. But varies).

Will put in a feature request then. :P

**Comment by Zireael07** [comment]
SSDs can lose data even to shorter power outages, if they're sudden (i.e. not you switching the computer power off). And we can pretty much bet that the power outage at the time of cataclysm was SUDDEN.

We'd have to assume old fashioned HDDs, then. Those could probably survive, if the data wasn't corrupted (again) by the sudden shutdown.

**Comment by TechyBen** [comment]
> SSDs can lose data even to shorter power outages, if they're sudden (i.e. not you switching the computer power off). And we can pretty much bet that the power outage at the time of cataclysm was SUDDEN.
> 
> We'd have to assume old fashioned HDDs, then. Those could probably survive, if the data wasn't corrupted (again) by the sudden shutdown.

Lol no. I've trashed around with SSDs an not had one die unless it is faulty/poor quality. Same with USBs and SD cards. Some will. Not "we'd have to" situation. But for gameplay/lore they can literally be anything (I've still got some old floppies and tape reels around. Just not got the time or knowledge to check if the hardware still works... no, I did not keep them... was a house clearance XD ).

As said, this also would *require* a "data recovery usb" type situation. As only a trained user, or with the right tools, can you seamlessly recover data. However, it can be done to anything not physically abused or purposefully erased.

If E-books and Cameras/phones survive in CDDA, no reason other things should not. But I could understand limitations to coding, time/effort/desire/art/lore etc. But having a proper "hacker" survivor could be cool. :)

Ebooks are a good start for looking to branch out features. Such as copying over books/recipes so space is saved on the bookshelf (at the expense of needing power and much easier to destroy/lose).

**Comment by Zireael07** [comment]
Still a valid suggestion.
