### ISSUE TITLE
[m]end should attempt to use an appropriate tool to repair the item.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#29991]
**Is your feature request related to a problem? Please describe.**  
It bothers me that we have an option in the item menu to [m]end the thing, and when I use it I get a response like "The |\ homemade halfpike doesn't have any faults to mend." I know that as it stands [m]end is used only for fixing faulty engines, but clearly the thing is damaged, so "no faults" feels incorrect.

**Describe the solution you'd like**  
When you use [m]end on something that is damaged or could be reinforced try to use an appropriate tool (or if multiple available tools are appropriate, offer a list.)

**Describe alternatives you've considered**  
Leave it the way it is, this is just a QoL change.

**Comment by Petethegoat** [comment]
Agreed and I might look into this.
