### ISSUE TITLE
Bottom of Mine scenario starts without battery in mining helmet

### ISSUE THREAD

**Issue by CEG86** [CleverRaven/Cataclysm-DDA#29993]
**Describe the bug**  
Bottom of Mine scenario starts without battery in mining helmet.

**To Reproduce**  
1. Start bottom of the mine scenario.

**Expected behavior**  
Fully charged `light battery cell` to be loaded in helmet

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2256-gdbf3bee
 - Graphics version: Tiles
 - Mods loaded: Tested on vanilla
**Additional context**

**Comment by CEG86** [comment]
Ditto on all flashlights in the area.  I imagine this problem is present in most starting scenarios that have battery items.

**Comment by Inglonias** [comment]
This should be a relatively simple fix. I'll take care of it as soon as I can which means probably tomorrow. I am travelling today.
