### ISSUE TITLE
Change movement cycling to shifting stance up and down

### ISSUE THREAD

**Issue by FrozenSnowFox** [CleverRaven/Cataclysm-DDA#29997]
**Is your feature request related to a problem? Please describe.**  
The current movement cycle system requires cycling through movement styles you don't want.  Cycling through unwanted styles will be an issue if/when someone implements an action point cost and will become more annoying when crawling/prone is added #29695 .

**Describe the solution you'd like**  
Instead of cycling through multiple movement styles to the one you want the cycling should be changed to shift a stance up or down.  While there are currently 3 styles there will likely be four in the future once crawling/prone is added.  Walking would be the default style and you would shift the stance up or down using the shift key as a modifier.  So you'd have something like "m" shifts a stance down and "M" shifts a stance up (I imagine something like ' and " would work better but m and M works well for visibility in this written example).

Running
Walking <- Default
Crouching
Crawling/Prone

For an example say you are walking and you want to crouch you should press "m" to shift your stance down but then later you want to run so you shift your stance up by press "M" twice.  With the existing toggle keys you could jump from running to crawling immediately without multiple key presses.  However for general use you'll probably be shifting between the top 3 and only dropping prone on rare occasions.

This stance system is used in a variety of hunting and tactical games and works quite well when changing between stances costs the player time.

**Describe alternatives you've considered**  
Not doing anything and sticking with the current cycling system.

**Comment by kevingranade** [comment]
Changing between stances does not and will not cost move points, and using a second key for cycling in the opposite direction isn't particularly compelling.

If someone wants to implement cycling in reverse as annunbound option they can feel free, but it doesn't need an open issue.
