### ISSUE TITLE
Missing Item Definition: Resin_Cord

### ISSUE THREAD

**Issue by YukariMindGap** [CleverRaven/Cataclysm-DDA#30000]
**Describe the bug**  
There's a missing item definition error of the resin_cord. It's apparently an item from the More_Survival_Tools mod

**To Reproduce**  
1. Open Debug Benu
2. Try to wish for an item

**Expected behavior**  
No error when opening item wishing menu

**Screenshots**  
![image](https://user-images.githubusercontent.com/39007766/56858849-2efa7200-69ab-11e9-8536-0dd8980a9bac.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-2256-gdbf3bee
 - Graphics version: Tiles
 - Mods loaded: dda

**Comment by MrHrulgin** [comment]
See #28584.

**Comment by Epictyphlosion** [comment]
30,000 issues, yay!
