### ISSUE TITLE
Can craft scope with single lense

### ISSUE THREAD

**Issue by Michael1993** [CleverRaven/Cataclysm-DDA#30001]
Game version: 8851

Operating system: Windows 7

Tiles or curses: Tiles

Mods active:
Filthy clothing
Disable NPC needs
Sleep deprivation

### Expected behavior
Ideally I'd need 2 high-quality lenses or 1 high-quality lens and 1 small high-quality lens
### Actual behavior
I was able to 
### Steps to reproduce the behavior
Spawn stuff to craft the bow scope or telescopic sight, but only a single lens. Try crafting the scope.

**Comment by ZhilkinSerg** [comment]
Closed in #30264.
