### ISSUE TITLE
Kitchen unit hotplates don't draw power from vehicle batteries

### ISSUE THREAD

**Issue by 81Denton** [CleverRaven/Cataclysm-DDA#30010]
**Describe the bug**  
Vehicle kitchen units don't draw power from the vehicle's batteries, but try to use an internal power cell which is always empty.
I suspect that this has to do with the recent battery refactor PR.

**To Reproduce**  
Install a kitchen unit and battery in a vehicle, then try to use the kitchen unit's hotplate.
Or just spawn an RV/luxury RV.

**Expected behavior**  
The kitchen unit's hotplate should draw power from any batteries installed in the vehicle.

**Versions and configuration(please complete the following information):**
 - OS: Win 10
 - Game Version: 0.D-2318-g1323624
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs

**Comment by esotericist** [comment]
This literally just got fixed by #29973

**Comment by 81Denton** [comment]
Sweet!

**Comment by 81Denton** [comment]
I'm able to reproduce this on 0.D-2318-g1323624 (tiles), even when creating a new world/character.

Error message is the standard "Your hotplate has 0 charges but needs 5."

**Comment by esotericist** [comment]
> I'm able to reproduce this on 0.D-2318-g1323624 (tiles), even when creating a new world/character.
> 
> Error message is the standard "Your hotplate has 0 charges but needs 5."

Just because a PR is accepted doesn't mean a build has been produced with it yet.

**Comment by 81Denton** [comment]
My bad, just realized I'm running build 8855 instead of 8856.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/kitchen-unit-hotplates-dont-draw-power-from-vehicle-batteries/23910/1
