### ISSUE TITLE
Inconsistencies with Poison Resistant and Air Filtration System

### ISSUE THREAD

**Issue by DaviBones** [CleverRaven/Cataclysm-DDA#30012]
**Is your feature request related to a problem? Please describe.**  
Poison Resistant and Air Filtration System do not stack, which got me to thinking, and I realized there are a couple of logical inconsistencies here.
1. Air Filtration System protects partially against all poison, including venom, despite explicitly stating it protects only your windpipe.
2. Air Filtration System does *not* protect against smoke, despite that fact that intuitively it should, from reading the description.
3. Again, going by the descriptions, Air Filtration and Poison Resistant operate in completely separate ways; there seems to be no reason they shouldn't stack.
4. (More of a minor balancing issue the bugs me, but I'll throw it in) Neither Poison Resistant nor Air Filtration System do anything at all about the speed malus from Badly Poisoned, which is arguably the worst part of said debuff.

**Describe the solution you'd like**  
To fix 1 through 3, Air Filtration's effects could be replaced with a permanent, passive Environmental protection on the mouth location. Perhaps somewhere between a filter mask (7) and a gas mask (16).
To fix 4, Poison Resistant could be altered to reduce the speed malus by a fraction consistent with its other effects.

**Describe alternatives you've considered**  
Alternatively, Air Filtration could be refactored as a blood filtration that specifically targets toxins, but we already have a Blood Filter CBM, and it still doesn't entirely resolve issue 3.

**Comment by Night-Pryanik** [comment]
Considering AFS - this was already discussed several years ago - https://discourse.cataclysmdda.org/t/question-about-air-filtration-cbm/11658.

> To fix 1 through 3, Air Filtration's effects could be replaced with a permanent, passive Environmental protection on the mouth location.

In fact AFS is already providing environmental protection. It's just extremely small (adding just 2 point to EP if EP is smaller than 5) and most probably needs a solid buff.

**Comment by Fris0uman** [comment]
AFS does nothing about poison, and the description odes not says so.
It passively gives 7 EP this is as much as a filter mask, so the question is is that enough or should it be bumped up. If it's enough I think the issue is closed.

**Comment by DaviBones** [comment]
Yes, this is resolved. Could have been my imagination that AFS was affecting poison (I had done some testing with a debug-spawned rattlesnake), or maybe it got fixed along the way. Either way, some cursory code-diving has made it clear to me that this is not the case now.

As far as 7 EP being enough, I would say that respiratory protection may need to be researched and retooled in general, as was attempted in #25618, but that's only tangentially related at best to this issue, and 7 EP is acceptable in the meantime.
