### ISSUE TITLE
bone crossbow bolt still uses old archery values

### ISSUE THREAD

**Issue by YukariMindGap** [CleverRaven/Cataclysm-DDA#30026]
**Describe the bug**  
More survival tools' Bone Crossbow Bolt still uses old damage value.

**To Reproduce**  
1. Open the crafting menu
2. Look at Bone Crossbow Bolt's damage value

**Expected behavior**  
No bolts are missed in the archery overhaul

**Screenshots**  
Normal Bolt
![image](https://user-images.githubusercontent.com/39007766/56867081-55e89080-6a0b-11e9-9979-558b15ec381c.png)

Bone Bolt
![image](https://user-images.githubusercontent.com/39007766/56867086-5b45db00-6a0b-11e9-8cd7-b981d0fef430.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-2318-g1323624
 - Graphics version: Tiles
 - Mods loaded: More Survival tools

**Additional context**  
It's just a simple one-line fix, but just letting you know you might missed more than the bolt

**Comment by Zombiemanpig** [comment]
There is def a few items that were missed when they changed ranged weapons.
