### ISSUE TITLE
Make vehicle side mirrors foldable

### ISSUE THREAD

**Issue by dom4op** [CleverRaven/Cataclysm-DDA#30028]
**Is your feature request related to a problem? Please describe.**  
Every modern vehicle has foldable side mirrors, yet we don't have that function in DDA.

**Describe the solution you'd like**  
An option in vehichle controls to fold mirrors. When you press the button they dissapear and player should no longer be able to see the rear. Then he can unfold the mirrors whenever he needs them again.

**Describe alternatives you've considered**  
Stop driving, remOve mirrors, pass a narrow path without breaking the mirrors, stop driving, install the mirrors again.

**Additional context**  

![Sprite-0002](https://user-images.githubusercontent.com/49651777/56867368-fe3b2c80-69ec-11e9-98a8-4654792387de.jpg)

**Comment by MrHrulgin** [comment]
You can also take off the wing mirrors and install them on the front corners as inline mirrors. This will keep them much safer while only losing some vision directly behind the vehicle.

**Comment by dom4op** [comment]
>The vehicles that do have wing mirrors in CDDA are ones that generally have physical framework supporting them in real life, and that framework can't be folded in.

Alright, that makes sense.
