### ISSUE TITLE
Camera stuck on driving mode on death

### ISSUE THREAD

**Issue by YukariMindGap** [CleverRaven/Cataclysm-DDA#30021]
**Describe the bug**  
If you die while driving any vehicle and then respawn on the world, the camera will get stuck on the furthest "driving focus/offset" and unable to be reset to the proper position. If you die while the camera is stuck, it will reset to the proper position

**To Reproduce**  
1. Find, or spawn in a vehicle
2. Get killed or commit suicide
3. Create a new character in the same world without exiting the game.

**Expected behavior**  
The camera should reset to the correct position upon respawning in the world.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-2318-g1323624
 - Graphics version: Tiles
 - Mods loaded: Vanilla DDA

**Comment by esotericist** [comment]
Oh, that's a good one. Now I have a much stronger reason to revisit the driving offset logic than I already had. Thanks for reporting this
