### ISSUE TITLE
Dog Not Attacking Enemies (and bad pathing)

### ISSUE THREAD

**Issue by SomethingintheMist** [CleverRaven/Cataclysm-DDA#30037]
I recently domesticated a Cattle Dog, but even in attack mode with the Dog Whistle it will not attack enemies. It will only follow me around at varying distances depending on if it's in attack mode or docile. Its AI also seems to have very poor pathing, as it waltzed right into a pool of acid after I killed an Acidic Zombie and killed itself. I save-scummed because that felt like the BS and not me making any kind of mistake.

My mods are as follows:
Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Craftable Gun Pack, Extended Realistic Guns, Garden Pots, Makeshift Items, More Survival Tools, Modular Turrets, Salvaged Robots, Alternate Map Key, Mutant NPCs, More Locations, Fuji's More Buildings, Boats, Folding Parts Pack, Vehicle Additions Pack, Tanks and Other Vehicles, Cataclysm++, PKs Rebalancing.

To re-create this, start a world with the following mods, wish for Dog Food, spawn a Cattle Dog (maybe any dog, not sure) and find some enemies to fight. Unless there's something really weird going on in my files specifically the Cattle Dog won't attack at all.

What should happen is that the dog attacks, obviously. I would also like if the dogs had better pathing though, so that I don't have to worry about them walking right through acid or fire and killing themselves when it was completely avoidable.

I am using Windows 7
I am on a recent experimental build, version 0.D-2341-g1c62c69
Using MSX++LIVE_PEOPLE tiles

**Comment by anothersimulacrum** [comment]
Why does this have the mods flag? I don't think this specific failure is mod related.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10650. Tamed cattle dog, blew a whistle so it went to attack mode, and got this:

![изображение](https://user-images.githubusercontent.com/11132525/184638081-17322988-7b34-4301-9615-7f4f06e15168.png)
