### ISSUE TITLE
NPC head exploded from infinite loop

### ISSUE THREAD

**Issue by drhead** [CleverRaven/Cataclysm-DDA#30047]
**Describe the bug**  
An NPC's head exploded in my save from attempting to move. 

**To Reproduce**  
1. Load save
2. Sleep until you wake up (may or may not be important though it would be nice to recreate conditions)
3. Move to the road in front of the southeastern most house in the nearby necropolis.  You should get a head exploding message.

**Expected behavior**  
I expect her head to not explode.

Based on the debug message, it is possible the function doesn't have proper handling for move orders which end on the same tile they start and thus don't use moves.  This particular NPC does not actually move, she's a necropolis soldier and just stands there forever really.

**Screenshots**  
![](https://cdn.discordapp.com/attachments/252368751016542218/572279731693813779/unknown.png)

**Versions and configuration:**
 - OS:  Windows 10
 - Game Version: 0.D-2341-g1c62c69
 - Graphics version: Tiles
 - Mods loaded: dda, aftershock, vehicle additions

**Additional context**  
Savegame:
[Hesler.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3125962/Hesler.zip)

**Comment by chaoticidealism** [comment]
I observed this as well. The bug I just reported, with NPCs causing extreme lag, came complete with a couple of their heads exploding--both guards at the refugee center. Didn't remember that part until I saw your report. I bet they're connected.

**Comment by davidpwbrown** [comment]
hmmm.  I got this 
![image](https://user-images.githubusercontent.com/39344466/56975986-d58c7180-6b69-11e9-9e68-44682d6a06dc.png)
Seems they can handle going to a destination that is already where they are.
Not sure under what conditions your NPCs head exploded, maybe it's the z-level?? can anyone else reproduce?

**Comment by neitsa** [comment]
If a NPC spends 10 moves without moving, then the NPC is programmed to have its brain explode 😭 . I think this was made so a NPC is not stuck forever:

https://github.com/CleverRaven/Cataclysm-DDA/blob/33a049e6d7e81d9dd2a941156ee3fc16e3be766f/src/game.cpp#L4229-L4257

Maybe we could check if the NPC was ordered to move to the same tile (I mean, it was ordered to move, but the destination was the same tile), which is in this case would simply state that the NPC isn't stuck at all.

At least we need a way to discriminate between "NPC is stuck" and "NPC moved in place".

**Comment by mlangsdorf** [comment]
I think this is the bug:
```
    const tripoint omt_pos = global_omt_location();
    int sx = sgn( goal.x - omt_pos.x );
    int sy = sgn( goal.y - omt_pos.y );
    const int minz = std::min( goal.z, posz() );
    const int maxz = std::max( goal.z, posz() );
    add_msg( m_debug, "%s going (%d,%d,%d)->(%d,%d,%d)", name,
             omt_pos.x, omt_pos.y, omt_pos.z, goal.x, goal.y, goal.z );
    if( goal == omt_pos ) {
        // We're at our desired map square!
        reach_omt_destination();
        return;
    }
```
There should be a move_pause() after reach_omt_destination() to 0 out the NPC's moves and skip the infinite loop detection.
