### ISSUE TITLE
Hand-loaded ammunition should be better than factory ammo.

### ISSUE THREAD

**Issue by GreevyGreev** [CleverRaven/Cataclysm-DDA#30046]
**Describe the solution you'd like**  
Ammunition that has been reloaded should be more accurate and reliable than ammunition that is factory made. IRL, hand-loaded ammunition is almost always more consistent than factory ammo. In addition, you've got far more options for hand-loading than you do for factory ammo. You can load your ammo as light or as hot as you want (within CIP standards, I mean).

**Describe alternatives you've considered**  
Alternatively, add a new recipe for each caliber called "hand-loaded match ammunition". This match ammo would take longer to load (because you're taking your time and carefully measuring powder charge and such) but would be much more accurate and powerful than factory.

**Additional context**  
Here is an article that shows this: http://www.massreloading.com/reloadsVfactory2.html
Notably, look at the first picture where it's comparing hand-loads to factory loads.

**Comment by tenmillimaster** [comment]
I agree and also vehemently disagree. Handloading in CDDAA is riddled with so many compromises and shortcuts that I legitimately am concerned for the safety of CDDA survivors everywhere shooting handloads. 

That said, yes, what you are describing should be possible, but we need some overhauls of the handloading system and other items to get there.

**Comment by GreevyGreev** [comment]
I agree, but I feel that we shouldn't overcomplicate it just because "muh wealism". I could agree with maybe just breaking the powders down into separate types so you can't just break a .50 round down and make 9mm ammo with it, but you'd be edging into stupidly complex if you did much more than that.

**Comment by tenmillimaster** [comment]
I believe that's the ideal solution- change all the smokeless powder types to the various types, broadly, make the factory recipes more detailed, but retain the current handloaded ones as 'compromise' loadings, compromises for using mixed powder, various metals, questionable primers and inadequate reloading equipment.

**Comment by kevingranade** [comment]
@tenmillimaster has it here, you're conflating ideal handloading with unlimited access to industrially produced bullets, casings, primers and gunpowder with the reality of scavenged all-of-the-above.

As long as the handloading recipe has requirements no more stringent than, "I found a generic mold kit and a kenetic bullet puller and I'm swapping around gunpowder and recasting bullets", then hand loads will continue to have stats inferior to factory loads.
