### ISSUE TITLE
Follower won't take anti-biotics, decides to crash the game instead

### ISSUE THREAD

**Issue by Kitaragna** [CleverRaven/Cataclysm-DDA#30050]
**Describe the bug**  
When I tell my Follower (who has an infected leg) to take some anti-biotics, the game crashes.

**To Reproduce**  
1. E"x"amine the follower (Atropos)
2. Chat, tell her to take the Antibiotic that's not Favorited. The game will crash.

**Expected behavior**  
I expect her to take the Antibiotics and for the infection to cease.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2224-gde41139
 - Graphics version: Tiles
 - Mods loaded: Garden Pots

CRASH LOG FILE: config/crash.log
VERSION: 0.D-2224-gde41139
TYPE: Signal
MESSAGE: SIGFPE: Arithmetical error
STACK TRACE:
    @0x4EA2EE[cataclysm-tiles.exe+0xEA2EE]
    @0x4EA566[cataclysm-tiles.exe+0xEA566]
    SMPEG_error+0x3DB58@0xB6124A[cataclysm-tiles.exe+0x76124A]
    UnhandledExceptionFilter+0x1CB@0x7674A76B[KERNELBASE.dll+0x1AA76B]
    RtlCaptureStackContext+0x1DC4F@0x771D2FFF[ntdll.dll+0xA2FFF]
    RtlGetAppContainerNamedObjectPath+0xBD@0x771965FD[ntdll.dll+0x665FD]

[Tanglewood Forest.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3126254/Tanglewood.Forest.zip)

**Comment by neitsa** [comment]
Thanks for your bug report!

Downloaded your archive multiple times, but it seems to be corrupted. Could you upload a new one please?

Could you also test on the very latest experimental (8862 as of today). The bug **might** have been fixed in #29953.

**Comment by drhead** [comment]
I have experienced a similar crash on a recent build while giving an NPC a gamma globulin shot.  Possibly related?

**Comment by Kitaragna** [comment]
Seems to be okay now. Newest Experimental seemed to have fixed it.
