### ISSUE TITLE
Electrohacked doors open at the start of the hack instead of the end.

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#30067]
**Describe the bug**  
When you electrohack a door open it takes about 30 seconds, but when you successfully do this the door opens and then 30 seconds past, giving a potential turret behind a door multiple turns to shoot you. 

**To Reproduce**  
1. Hack a door open with a turret behind it
2. Watch as the door opens and then you spend 30 seconds sitting there "hacking" while the turret shoots you for multiple turns.

**Expected behavior**  
To spend 30 seconds hacking, having the door open at the end and then possibly getting shot for one turn.

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version: [0.D-2372-g1a0a791]
 - Graphics version: [Tiles]
 - Mods loaded: [StatsThroughSkills, Urban development,more locations, fuji's more buildings]

**Comment by spacenookie** [comment]
looks like this is because of how iexamine::hack_attempt is implemented, mainly
```
  p.moves -= 500;
```
seems like hacking should be implemented more like reading a book or aiming a gun, currently it is an instantaneous action that paralyzes player for 30 secs
