### ISSUE TITLE
Nearby triffids gradually make the game way too slow

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#30060]
**Describe the bug**  
About one second per step on my shiny i7-8550U after a few days nearby.

**Versions and configuration(please complete the following information):**
0.D-2347-gd2817f395f-dirty, RELEASE=1

**Additional context**  
[2019.04.23.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3127100/2019.04.23.zip)

May be related to https://github.com/CleverRaven/Cataclysm-DDA/issues/17467

**Comment by ZhilkinSerg** [comment]
I confirm the issue - performance while waiting on provided savegame is really terrible.

Most time is spent on monster movement planning and movement:

![image](https://user-images.githubusercontent.com/16213433/62767584-b02ece00-ba9d-11e9-9917-fd9a0502d6bf.png)

![image](https://user-images.githubusercontent.com/16213433/62767659-dc4a4f00-ba9d-11e9-91f6-b31e73459784.png)

![image](https://user-images.githubusercontent.com/16213433/62767671-e0766c80-ba9d-11e9-9d05-97658876bc02.png)

![image](https://user-images.githubusercontent.com/16213433/62767681-e5d3b700-ba9d-11e9-9c37-986f6493cfb3.png)

![image](https://user-images.githubusercontent.com/16213433/62767610-bfae1700-ba9d-11e9-9e7b-2e6b6557c781.png)

**Comment by ZhilkinSerg** [comment]
Updated profiling info on current master:

![image](https://user-images.githubusercontent.com/16213433/65187836-8e017600-da75-11e9-859c-7f4012cc731c.png)

**Comment by kevingranade** [comment]
mattack::vine() is just wacky, this is the real issue:
https://github.com/CleverRaven/Cataclysm-DDA/blob/5a03b229db049fb29d9db11931062f1805f4deac/src/monattack.cpp#L1489-L1496

Every time a vine special fires, which is once every 5 turns, this scans the entire list of monsters.
Making this worse is the fact that vines are multiplying on this same period.

One thing that we should do is restrict the vine growth area to some radius around the parent hub, currently it is only restricted by growth rate falling off with distance from the hub, and then if there is no hub in range it falls back to a 1 / 999 chance of growing.  The implication of this is that hubs should grow to cover immense areas eventually, but they suffer from only growing when near the player.  Considering this, capping hub growth to a reasonable number (10 - 20 or so?) should help make the performance problem easier to resolve.

A simple stab at resolving the performance problem then would be to stash the location of the parent hub when a vine is created, then use A* to confirm connectivity between the hub and the current vine, which is expected to be near-linear the vast majority of the time.  If the A* search fails, the vine should die or at least take damage.
