### ISSUE TITLE
Spiders don't attack Zombies

### ISSUE THREAD

**Issue by Oakeave** [CleverRaven/Cataclysm-DDA#30066]
**Describe the bug**  
Spiders and Zombies don't attack each other.

**To Reproduce**  
A
1. Make a lab character.
2. Find a spider room.
3. Find a zombie.
4. Lead zombie to spider room.
Spiders don't attack zombies.

B
1. Make a regular character.
2. Find a house with a basement full of spiders.
3. Find a zombie.
4. Lead zombie to basement of spiders.
Spiders don't attack zombie.

**Expected behavior**  
Spiders and zombies should attack each other.
Spiders are a living non-zombie creature, thus zombies, which hates anything that breathes, should attack spiders.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2396-g1b60b95
 - Graphics version: Tiles
 - Mods loaded: dda, aftershock, disable NPC needs, Bens GF recipes, garden pots, craftable gun packs, makeshift items mod, medieval and historical content, more survival tools, modular turrets, salvaged robots, mutant NPCs. mythical martial arts, boats, folding parts pack, vehicle additions pack, no survivor armor, classes and scenario mod

**Additional context**  
[Latta.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3127908/Latta.zip)

**Comment by ifreund** [comment]
This is intentional, see #15372 for reasoning.
