### ISSUE TITLE
Provide the ability to copy relevant version & config info from game.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#30062]
**Is your feature request related to a problem? Please describe.**  
When making a bug report, I'm always tempted to skip reporting the version and configuration detail because it's a pain to transcribe the full list of mods, version#, etc.

**Describe the solution you'd like**  
I'd like the "Active World Mods" option on the Main Menu to be expanded to state the other info relevant to a bug report, as well as an option to copy it to clipboard for easy pasting into a bug report, ideally formatted as is desired for the format here on GitHub. This would likely increase the accuracy and completeness of info on bug reports.

**Describe alternatives you've considered**  
Leave it alone.

**Comment by AMurkin** [comment]
You can copy version info as well as errors texts from `config\debug.log`.
Mod list available at `save\[world_name]\mods.json`.

That's not one click solution, but ready to copy-paste text.
