### ISSUE TITLE
Impossible to boil stuff using a military mess kit

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#30069]
**To Reproduce**  
1. Load the save.
2. Try crafting clean water or large sealed stomach.
3. `1 tool with boiling of 1 or more.` is red

**Additional context**  
[2019.04.29-2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3128437/2019.04.29-2.zip)

**Comment by l29ah** [comment]
I guess something like https://github.com/CleverRaven/Cataclysm-DDA/pull/28830 needs to be done.

**Comment by Inglonias** [comment]
Yeah, it explicitly checks for toolmods. I guess we'll need to add an explicit magazine check too. Good catch!
