### ISSUE TITLE
Creating a new game will cause the game to crash

### ISSUE THREAD

**Issue by kwl01skz** [CleverRaven/Cataclysm-DDA#30119]
**Describe the bug**  
After creating a new role confirmation, the game crashes before it starts.

**To Reproduce**  
1.Select one of the following Scenarios, all others use the default values.
 * Challenge-Really Bad Day
 * Challenge-Lab
 * Challenge-Abandoned

2.Confirm the creation of the character and start the game
3.the game crashes

**Versions and configuration(please complete the following information):**
 - OS:  Ubuntu 18.04
 - Game Version: 0.D-2460-gc0cef43
 - Graphics version: Tiles
 - Mods loaded: None

**Additional context**  
Not crash in these Scenarios:
Evacuee
Challenge-Medieval Peasant

At least still working in this version:
2347-gd2817f3
I''ve not been to test more versions.

**Comment by kwl01skz** [comment]
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3131155/crash.log)

**Comment by Hirmuolio** [comment]
The game places water in toilets.
The temperature of the water gets processed.
The game starts at t=8 h. The item has its last temp check at t=0.
The 8 hours of history gets calculated.
Tries to get the heat from heat sources (this is new feature).
I guess the game doesn't like it when you try to get the heat field at this point of map gen.

For now if you want to start a scenario that has toilets/vending machines nearby you can set the game start time to 0 hours (world options -> initial time)

**Comment by Inglonias** [comment]
Again with this? This reminds me of #24288

**Comment by ZhilkinSerg** [comment]
Also https://github.com/CleverRaven/Cataclysm-DDA/pull/29818#issuecomment-487854984
