### ISSUE TITLE
Avast Triggered on Boot

### ISSUE THREAD

**Issue by AFoxInAviators** [CleverRaven/Cataclysm-DDA#30110]
I updated my game recently (running experimental, latest version. Was previously only about a week behind updates) and now the game triggers my Avast. I have never had any issues with the game triggering any antivirus before, so this is very odd. My Avast scans it for about a second before my PC BSoD's. I know it is Avast's fault since making the game an exception seems to have solved the issue, but I figured I would start a ticket in case it helps any of the devs. 

I don't know exactly what it's flagging, but I know when my PC BSoD's it gives me the KMODE_EXCEPTION_NOT_HANDLED Error with the ClipSP.sys file specifically, if that helps anybody pinpoint the issue.

Windows 10,
Version 0.D 2423-g437197c, Tiles, with all the default mods. I have not installed any extra mods via the launcher.

I'd add my save file but I can't figure out how... Apologies for the ineptitude.

**Comment by kevingranade** [comment]
Thanks for the report, but theres nothing we can do. Every new build is a roll the dice with each antivirus system, though usually they just quarantine or report something instead of BSoDing.
