### ISSUE TITLE
Crafting  anesthetic does not count an empty anesthesia kit as a valid container

### ISSUE THREAD

**Issue by Naive8A** [CleverRaven/Cataclysm-DDA#30113]
**Description**  
If you try to make anesthetic AND you have a large enough nearby container, you can craft it normally. When the recipe is finished, you can choose to put the anesthetic in an empty anesthesia kit (or other container) as expected. 
However, if you have no suitable container, even if you have an empty anesthesia kit you cannot make anesthetic. You get the message "You don't have anything to store anesthetic in!" and cannot proceed with the recipe. 
This is NOT related to the tool requirement of the recipe. Having only a glass bowl will not allow you to proceed with the recipe despite showing the tool requirement as filled. 

**To Reproduce**  
1. Wish for an anesthesia kit (NOT an anesthetic kit!), a glass bowl, and 5 heroin.
2. Unload the anesthesia kit. It should read (0/3). 
3. Wish for 2700 ether (this must be done just before attempting the recipe or it spills).
4. Open the crafting menu and try to craft anesthetic. If you do not have a large, empty container nearby, you will not be able to craft it. 

**Expected behavior**  
Crafting anesthetic should count the anesthesia kit as a valid place to store anesthetic.  
Otherwise, instead of only needing one 3L glass jar for the anesthesia kit, you need a second one (or other suitably large liquid container) in order to craft the anesthetic even though you may never put anesthetic in the second container. 

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2396-g1b60b95
 - Graphics version: Tiles
 - Mods loaded: DDA

**Comment by Fris0uman** [comment]
It's probably because the kit is not a container. Will look into it in a few hours

**Comment by Fris0uman** [comment]
So I see two possible way to fix that : 
- The 3l jar is a magazine for the kit. You pour the anesthesia in the jar and load the jar in the kit.
- We get rid of the kit entierly and just use 1L of anesthesia per surgery

**Comment by Naive8A** [comment]
I'm a fan of using 3L jars as magazines, bu since anesthesia kits have no other use, if changing autodocs to accept straight anesthetic is a simple change I think it makes sense to say that the autodocs have anesthesia kits built in and just need the materials.

**Comment by kevingranade** [comment]
Summary of discussion on discord:
AFAICT the kit just needs the appropriate container metadata to be recognized by the crafting code, just a guess, I think this will do it:
```
"container_data": { "contains": 3, "watertight": true },
"qualities": [ "CONTAIN", 1 ]
```

**Comment by kevingranade** [comment]
The approach I suggested triggered a seemingly endless series of bugs, so we've reverted it and need a new solution now.

**Comment by ifreund** [comment]
The solution I would like to see for this is to just add a special case to the liquid handling code to allow liquids to be loaded into tools, instead of forcing them to be poured on the ground.  Then add an equivalent special case to `player::check_eligible_containers_for_crafting()` that allows crafting if the resulting liquid could be loaded into an available tool.
