### ISSUE TITLE
Improper plural form of Medium Battery Cell

### ISSUE THREAD

**Issue by YukariMindGap** [CleverRaven/Cataclysm-DDA#30112]
**Describe the bug**  
Medium Battery Cells have the plural form of Light battery cells (A smaller type of battery)

**To Reproduce**  
1. Check out ammo.json

**Expected behavior**  
The profer plural form of Medium battery cell is medium battery cells

**Screenshots**  
```
`"name": "medium battery cell",
    "name_plural": "light battery cells",`
```

**Versions and configuration(please complete the following information):**
 - OS:  Windows 7
 - Game Version: 0.D-2318-g132624
 - Graphics version: Tiles
 - Mods loaded: vanilla

**Additional context**  
A small mistake that can be fixed with simply deleting the offending line

**Comment by esotericist** [comment]
Already discovered and fixed in #30005
