### ISSUE TITLE
Fibrous stalks?

### ISSUE THREAD

**Issue by Scischm** [CleverRaven/Cataclysm-DDA#30111]
**Is your feature request related to a problem? Please describe.**  
Fibrous stalks serve very few purposes in their current state. Their main use is dissassembly to get plant fiber (Which is great! More sources of thread are always appreciated). In their current state however they tend to be rather useless after a few disassemblies for anything other than ~~firewood~~ (apparently it doesn't work for fuel) or an emergency food source.

**Describe the solution you'd like**  
Until more uses can be decided for the item I think a worthwhile solution would be to decrease their current disassemble time of one hour. A vine beast can drop around 350 of these stalks. If I decided to go crazy and just make use of one kill for more plant fiber than I would ever need it would take over 350 hours just to process the one kill. If the amount of plant fiber being provided is a concern I would think that decreasing the yield of the plant fiber would be appropriate as well.

I opened the topic to discuss what a reasonable time and yield should be.

**Describe alternatives you've considered**  
Instead of just dropping plant fiber, disassembly could also yield withered plants. The marijuana crop disassembly times come to mind.

The stalks working as fuel would be a good use as well.

This is the current marijuana yield of 100 fiber and 1 withered plant in just 5 minutes of deconstruction. Since it is significantly quicker to kill a vine beast than it is to wait for marijuana to grow perhaps it could be a smaller amount of plant fiber, i.e. 20 per stalk and 1 withered plant per, or if chances are possible 0-1 withered plant per deconstruct with a time around 8 or 10 minutes?
![image](https://user-images.githubusercontent.com/49844315/56945751-28c4dc80-6af6-11e9-8ab3-50ffdd4b460d.png)

**Comment by l29ah** [comment]
They can be used as veggies and as a source of a disinfectant now.

**Comment by kwl01skz** [comment]
Burning straw? The Air Protection Association is concerned about you.
Ok, my proposal is to allow quick disassembly of Fibrous stalks, resulting in less fiber and some wilted plants.

**Comment by KorGgenT** [comment]
i'm strongly against "reducing processing time"

rather, i'm in favor of adding more uses, possibility to burn it as firewood, that sort of thing. (all of which can be done in json)

**Comment by Scischm** [comment]
If use as a fuel as a direction is a good way to go then these stalks might benefit from a volume increase. As it stands they are pretty small and are dropped in very large stacks. Perhaps larger stalks with a smaller stack drop size would be the way to go? 

Since it says the stalks are rather green I would think they would be better classified as veggy material than wood, or possibly veggy and wood. I'm unsure of how effective burning veggy material is vs wood.

Depending on what exactly these are we could even add other deconstruct recipes. If it is soley veggy material it could just be used for plant fiber, or a combination of plant fiber and withered plants. It could be disassembled into a vine and fiber (which is fitting from vinebeasts).

 If it is a combination of wood and veggy perhaps you can get splintered wood in addition to plant fiber or plants. If we really increase the size of the sticks (drastically reducing the drop amount) perhaps disassembly could yield a heavy stick in addition to fiber, plants, or a vine. 

Another option for vinebeast harvest would be to add a few vines that drop, taking the place of the volume that was previously occupied by all the fibrous stalks.

I'm poking through the code trying to figure out how useful veggy is for fires but I haven't found anything yet.

**Comment by kevingranade** [comment]
Your problem is a non-problem.  If you want to add functionality to the item, PRs are welcome, but this isn't a problem, and there's no feature request either as you're basically brainstorming.

**Comment by Scischm** [comment]
Sorry I guess? It was my understanding that before you implement features that it is encouraged to discuss them, noted by the "Talk it out before implementing" discussion tag, which is apparently misleading. I didn't think it necessary to open a full fledged PR, which was my next step if this yielded any meaningful input.

I suppose it was my fault for not wording it correctly. I do have a problem with their current implementation as they serve almost no purpose, have no material tags, and are unbalanced in both the amount dropped for how long the dissassembly takes. 

My intent was to facilitate discussion about the item while also learning a bit about materials. I was actually hoping to get some clarification on the exact nature of them, and was anticipating input of somone who was more familiar with the lore of the monsters that drop them.

**Comment by kevingranade** [comment]
Please look into what is involved in processing plants into plant fibres in reality if you want to look at rebalancing yield and disassembly time.

As for *what* it drops, it's a plant monster as per the description, wood, vines, leaves and plant stalks are all appropriate to drop.

The content policy for the game is to simply be representative of reality and let the chips fall where they may.  We don't second-guess how things work based on how they impact game balance.  In this case plant stalk processing takes as long as it takes, it's irrelevant how convenient or beneficial that is for the player.
