### ISSUE TITLE
Crafted food can have its bday in the future

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#30126]
**Describe the bug**  
Food crafted by the player can have its birtday in the future.

**To Reproduce**  

1. Craft food (for example cooked meat or a meat sandwitch).
2. Enable debug mode.
3. Look at the food age. Negative number is in the future.

The ammount of in the future seems random. Ranging from less than an hour to 5+ hours.

**Expected behavior**  
The time of crafting should be the birth day.

**Screenshots**  

![sand](https://user-images.githubusercontent.com/22011552/56981903-ac2f0e00-6b88-11e9-9619-ad59e2254d2b.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 8867
 - Graphics version: Tiles
 - Mods loaded: No

**Additional context**  
Birtday is used for rotting calculations (calc rot from bday or from last rot check). Birthday in the future causes the item to rot backwards making it more fresh as time goes on. (a pull is going to remove bday from there. Not sure what else it is used for)

**Comment by Scischm** [comment]
One solution might be to restrict age to positive numbers only. That way it can begin rotting correctly if you happen to stumble across something like this.

**Comment by ifreund** [comment]
Not sure what could be causing this, the bday seems to be set properly to `calendar::turn` here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/65a05026e7306b5d1228dc6ed885c43447f128b5/src/recipe.cpp#L313-L315

**Comment by ifreund** [comment]
Whoops, missed this which is obviously causing this issue:
https://github.com/CleverRaven/Cataclysm-DDA/blob/65a05026e7306b5d1228dc6ed885c43447f128b5/src/crafting.cpp#L561-L566

**Comment by Ramza13** [comment]
The comment right above the 

> 
> 
> Whoops, missed this which is obviously causing this issue:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/65a05026e7306b5d1228dc6ed885c43447f128b5/src/crafting.cpp#L561-L566

The comment right above this block says "The purpose of this is so that items with close birthdays will stack more readily."  

Given that and the fact that the birthday isn't visible without debug this looks to me like no bug at all.

**Comment by ifreund** [comment]
Quoting from the OP:
>Birthday is used for rotting calculations (calc rot from bday or from last rot check). Birthday in the future causes the item to rot backwards making it more fresh as time goes on. (a pull is going to remove bday from there. Not sure what else it is used for)

You're right that we want to preserve the stacking behavior, but it seems like we should do that in a way that disallows negative values.  Even if this specific case is no longer an issue (not sure, haven't checked up on the rot calculations) we want to guarantee that this is positive to avoid potential problems in the future.
