### ISSUE TITLE
firearm repair kit spends battery charges when cutting rebar cage

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#30137]
Even though it's supposed to contain a hacksaw as a cutting tool.

**To Reproduce**  
1. `a`ctivate the `firearm repair kit (500/500)`
2. `2 Cut metal`
3. Select nearby `rebar cage`
4. After it's cut observe it spending 100 battery charges.

**Versions and configuration(please complete the following information):**
0.D-2467-g43b8e97956-dirty

**Comment by dommon** [comment]
well, the surface problem is there is currently no way to assign individual charges_per_use to various actions, so if GUN_REPAIR uses 100 charges any other function that tool fulfills will also consume same amount

the actual problem is how gun repair is currently implemented

**Comment by Night-Pryanik** [comment]
That's the same problem I encountered in #16237.

**Comment by int-ua** [comment]
Is it fixable just by defining the `use_action` list? https://github.com/CleverRaven/Cataclysm-DDA/pull/16237/files#diff-c9aca6bfd4b16b9c081cb2187c3c33abb2b559d061e9d07cdf61c662974d9020R7581

**Comment by Rjtheperson** [comment]
Similarly the misc repair kit uses up duct tape when only using the saw.
