### ISSUE TITLE
CDDA Launcher Failure - Crashes

### ISSUE THREAD

**Issue by ViralAnomalyX** [CleverRaven/Cataclysm-DDA#30130]
**Describe the bug**  
Trying to open the launcher and it crashes.

**To Reproduce**  
1. Double click to open launcher

**Expected behavior**  
Launcher opens and loads properly.
![CDDAErrorPic](https://user-images.githubusercontent.com/45217141/56992618-11bad480-6b60-11e9-895b-d8bfc950b946.png)

**Comment by esotericist** [comment]
a) this belongs in the launcher's github, not the game's
b) i'm told it should have been fixed already if you get a newer version of the launcher

**Comment by ViralAnomalyX** [comment]
Ah, thanks.  First time I've seen/come across this.

**Comment by KorGgenT** [comment]
the launcher is not part of the main repo, as esotericist said.
