### ISSUE TITLE
Add wall climbing to the game.

### ISSUE THREAD

**Issue by lardf** [CleverRaven/Cataclysm-DDA#30147]
**Is your feature request related to a problem? Please describe.**  
It is not related to a problem, this is just a suggestion to add content to the game.

**Describe the solution you'd like**  
The way it should work is that when you examine a wall, you get the option to climb it if there's a tile on the Z level above you that you can climb onto. Climbing success should depend on your dodging skill, if no climbing skill is added. With level 4 dodging, you should be able to climb walls safely without risk of falling and injuring yourself. With lower levels, there should be a chance of you falling and injuring yourself in the process, depending on your level, something like level 1 being a 75% chance, level 2 being a 50% chance and level 3 being a 25% chance. There should also maybe be climbing gear added that decrease your chances of failing. Only feral runners and maybe NPCs should be able to climb walls.

**Describe alternatives you've considered**  

**Additional context**

**Comment by kevingranade** [comment]
You can, you need some kind of foothold or something to brace against, and it only works with z-levels enabled, which is now the default.

**Comment by lardf** [comment]
meant if you could climb with your hands but okay
