### ISSUE TITLE
Monsters with FLIES can warp through walls with experimental z-levels.

### ISSUE THREAD

**Issue by Davi-DeGanne** [CleverRaven/Cataclysm-DDA#30149]
**Description**  
Monsters with FLIES are able to warp through walls into completely enclosed rooms, if experimental z-levels are enabled, and the building is a house or some other building that has no "roof" z-level. Monsters with FLIES *and* BASHES don't bother, they just break down a door/wall.

**To Reproduce**  
1. Create a new world with experimental z-levels enabled.
2. Create a new character and teleport to a building that can be completely enclosed, but has no roof z-level.
3. Spawn a giant wasp outside.
4. Wait for the wasp to notice you and warp through the wall to murder you (this step goes faster if the wasp can see you through a closed window).

**Expected behavior**  
Monsters with FLIES shouldn't be able to get into a building if light can't either.

**Versions and configuration:**
 - OS: Windows 7
 - Game Version: 0.D-2460-gc0cef43
 - Graphics version: Terminal
 - Mods loaded: None

**Solutions**  
The only reasonable solution I can think of is to add z-level roofs to all buildings; any artificial restrictions I can think of to add to monsters' AI would only be a band-aid fix that would stop them from doing actually reasonable things (Like invading a player-built structure if that player built walls but no ceiling).

For buildings like houses that would have sloped roofs, a new impassable tile could be added to cover the roof's z-level, perhaps even automatically for buildings without specified roofs.

**Comment by Scischm** [comment]
My character has been sleeping in the second story of a mansion and being assaulted by various birds in their sleep due to pks rebalancing, this sounds wonderful.

**Comment by DaviBones** [comment]
Agreed, the roofs are simply awesome, and even strategically useful. But there will inevitably be roofs which will only make sense if they are inaccessible, and we will need to come up with a solution for those in order to resolve this bug.

**Comment by 8ctopus** [comment]
same bug for me, wasps flying through the walls of a cabin I took shelter in.

**Comment by wapcaplet** [comment]
I could not reproduce this in 0.E-9737-g511ddcb179, testing with one of the few buildings that does not yet have a roof (a cathedral). Z-levels are always on now, and cannot be disabled. I replaced one of the stained glass windows with a regular transparent windows so these wasps can see me, but even waiting for a couple hours, they did not get through:

![image](https://user-images.githubusercontent.com/238395/108455623-d05f5180-722b-11eb-9fc1-26d781390c3b.png)
