### ISSUE TITLE
Butchering creates rotten meat

### ISSUE THREAD

**Issue by Edwards-R** [CleverRaven/Cataclysm-DDA#30152]
**Summary**
Butchering a fresh corpse creates some rotten products

**Reproduce**
Kill any animal (tested on ant, opossum, Labrador mutt) with a weapon (tested with RM11B and pneumatic rifle). Full butcher. Meat, refuse, pelt, liver, scraps, all are rotten. Fat wasn't on the Labrador.

**Expected behavior**  
All products of a fresh kill should be fresh

**Version:**
0.D-2478-ge68efed (tiles)

No mods loaded

**Additional context** 

Savefile. Started, walked out, shot dog, butchered it.
[Chevak.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3134844/Chevak.zip)

**Comment by GreevyGreev** [comment]
This is a duplicate, see #30151.

**Comment by Edwards-R** [comment]
You beat me by 2 minutes. Agreed, duplicate issue so closing this
