### ISSUE TITLE
Solder with heat source and appropriate nearby tools?

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#30156]
**Is your feature request related to a problem? Please describe.**  
It is possible to do small repairs without a powered soldiering iron as shown [here](https://www.youtube.com/watch?v=WR5L_C0EPyM)

**Describe the solution you'd like**  
Have a tool that allows some or all of the soldering iron functions using a separate heat source for an increased investment of time.

**Describe alternatives you've considered**  
Leave it alone.

**Comment by Inglonias** [comment]
Minor quibble: It's spelled "solder". "Soldier" is something different, which confused me for a bit.

**Comment by HeadstrongCatgirl** [comment]
Basically scrap metal, pliers/tongs/wrench and open fire could be enough for some applications, but how do you acccount for all possible combinations of makeshift soldering tools? 
Also the chance of failure should be significantly higher with such tools.

**Comment by Inglonias** [comment]
> Basically scrap metal, pliers/tongs/wrench and open fire could be enough for some applications, but how do you acccount for all possible combinations of makeshift soldering tools?
> Also the chance of failure should be significantly higher with such tools.

The solution for this is to make a new tool called a "makeshift soldering iron" and allow for many recipes for that tool.

**Comment by kevingranade** [comment]
Chance of failure plus speed, there is a huge amount of efficiency baked into an ordinary soldering iron, if you discard that in flavor of an extremely ad-hoc solution, you're going to have a bad time with respect to speed.

So in summary:
Add support for adjusting time required to complete a craft based on properties of the tools used.
Add a "makeshift soldering iron" item that can solder and requires a nearby fire to operate.
Add one or more recipes for a makeshift soldering iron.

**Comment by Scischm** [comment]
> Add support for adjusting time required to complete a craft based on properties of the tools used.

That would be wonderful. It would open up so many opportunities to add tools, furniture, or ad-hoc solutions at the expense of speed and success, making crafting less restrictive overall without needed to bloat the recipes menu. This would definitely be a great step for adding endgame machines that take user effort and input to help with production of items with long crafting times, especially in batches. 

The code could also be applied in order to receive help from friendly npcs (with the correct skill and tools) or even have multiple relevant tools help with craft times.

**Comment by TechyBen** [comment]
Possibly not part of this, but as a side note, multiple types of soldering irons do exist. Such as a gas/butane powered soldering iron. So having more than one type and quality, is very legit a consideration! (They even do usb ones these days)

**Comment by kevingranade** [comment]
A butane powered soldering iron actually fits the niche where we use
battery powered soldering irons, but when they were added butane wasn't
really an option.

**Comment by TechyBen** [comment]
Battery ones do still exist IRL though. As said, the USB ones can be run off usb battery banks (I have not seen classic battery irons though, only plug in ones and gas ones when I was a little lad).

I see CDDA as a world where wall power is no longer really an option. But depending on the development, it could be a thing (say in labs/off generators). So it's really down to how the developers/team/each one wishes to change it. Either way it will be interesting in gameplay (either the limiting factor, or the freedom factor). :)

**Comment by kevingranade** [comment]
> I see CDDA as a world where wall power is no longer really an option.

This is a problem with the way we portray electronic devices.  There *should* be innumerable electronic devices that are corded, and because of that you can't use them unless you have a generator.
