### ISSUE TITLE
Corpses are rotting within 10 turns of killing the animal.

### ISSUE THREAD

**Issue by GreevyGreev** [CleverRaven/Cataclysm-DDA#30151]
**Describe the bug**  
I killed a person, went over to butcher them, and they were already rotten. I tested this on a few other animals and had the same results each time. I believe the bug is caused by #30125.

**To Reproduce**  
1. Shoot animal.
2. Wait 5-10 turns.
3. Check corpse.
4. ???
5. Rotten.

**Expected behavior**  
Not that?

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2478-ge68efed
 - Graphics version: Tiles
 - Mods loaded:  
 "dda",
  "no_npc_food",
  "realguns",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "alt_map_key",
  "blazemod",
  "Tanks",
  "deoxymod",
  "DP_REMIX_INDICATORS",
  "no_flaming_weapons",
  "No_Acid_Zombies",
  "No_Anthills",
  "No_Bees",
  "No_Fungi",
  "no_filthy_clothing",
  "safeautodoc",
  "novitamins",
  "StatsThroughSkills"

**Comment by Hirmuolio** [comment]
For some reason the corpse has its last_rot_check set to T=0 when it is created. It should be set to the time when the corpse was created.

**Comment by GreevyGreev** [comment]
If it were just JSON I'd fix it myself but I'm not too familiar with C++.
