### ISSUE TITLE
Battery migration crashes on Win10/64

### ISSUE THREAD

**Issue by micalm** [CleverRaven/Cataclysm-DDA#30161]
**Describe the bug**  
As in the title. Additional details on reddit [here](https://www.reddit.com/r/cataclysmdda/comments/bjgrbo/started_a_new_character_on_build_8883_and_this/).

**To Reproduce**  
1. Create a new world on Windows 64bit tiles, build between 8883-8885 (newest as I'm writing this)
2. Enable the battery migration mod.
3. Run around for ~50 turns.

**Expected behavior**  
Game games.

**Screenshots**  
[Stolen from the original post](https://preview.redd.it/xrhzlzciklv21.png?width=960&crop=smart&auto=webp&s=3e7e75ac910713f5212d34beaa034b5462d9aa19). Same applies to me.

**Versions and configuration(please complete the following information):**
 - OS: Win10 64
 - Game Version: [from the main menu, e.g. 0.D-2478-ge68efed]
 - Graphics version: Tiles
 - Mods loaded: Defaults + Battery_Migration

**Additional context**  
Just pingin @Inglonias, probably he dun it. That mod is temporary anyways, but it might indicate an issue with the game or battery overhaul itself. I'm not C enough to decide that.

**Comment by Inglonias** [comment]
Yep. The mod is not great. Probably should have tested it.

All it does it let you unload batteries as well as reload them. I'll redo it with the latest version of everything.
