### ISSUE TITLE
Add support of snippets for stacked items and contained liquids.

### ISSUE THREAD

**Issue by curstwist** [CleverRaven/Cataclysm-DDA#30172]
**Is your feature request related to a problem? Please describe.**  
I am interested in using snippets to increase food variety.  Working on a tea shop, I expanded tea & tea_raw with some snippets for tea varieties.  

current behavior:

- When I spawn the tea in containers, it reverts to the base description instead of the snippet.

- When I spawn loose liquid it retains the snippet.  

- tea_raw retains snippet unless combined with other tea varieties.  Then it takes on the snippet of the 1st one picked up.

- tea_raw when brewed loses snippet and defaults to base description for tea.

**Describe the solution you'd like**  
I'd like teas to retain snippets through their life cycle.  Defaulting to the base description if you brew them together.

**Describe alternatives you've considered**  
Leaving us in a world with only one flavor of tea besides specialty drinks.

**Additional context**  
my tea item entries for testing if someone picks this up:
https://pastebin.com/c97BEKvu

**Comment by Night-Pryanik** [comment]
No discussion in more than two years, closing.

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/51613 is not too far from this.
