### ISSUE TITLE
dangerous pickup

### ISSUE THREAD

**Issue by communistkiro** [CleverRaven/Cataclysm-DDA#30187]
**Describe the bug**  
Having the `Dangerous pickups` setting in the options `enabled` should enable auto-pick of items passing the filter despite increasing stamina cost (and perhaps various action movement costs?) for you. This doesn't work for `auto-forage`d items, which are left on the ground. 

**To Reproduce**  
1. Have `Dangerous pickups: enabled`;
2. Turn on any form of `auto-forage`;
3. Reach carry weight limit;
4. All new to-be-auto-picked-up items remain on tile your char's standing on with the log messages `"You harvest and drop %s x%d"` and `"You see <thing you harvested> x %d here"`

**Expected behavior**  
If `dangerous pickups` is `enabled`, items that were auto-foraged should be moved to inventory if there is more sufficient volume rather than dropped.

**Versions and configuration(please complete the following information):**
 - Game Version: 0.D-2518-g65a0506
 - Graphics version: tiles

**Comment by MrHrulgin** [comment]
C:DDA doesn't have a soft weight limit with increasing encumbrance, it's a hard limit. There aren't any other circumstances where you can carry more than your limit; why should auto-forage circumvent that?

**Comment by communistkiro** [comment]
There are two fractions, carry weight and volume. Exceeding the latter results in items dropping, exceeding the former makes make actions cost more movement points. Both indicated by red.

What I meant with 'overencumbered' is that message one gets when carrying over the carry soft limit, not the encumbrance mechanic.

**Comment by MrHrulgin** [comment]
You're right, my brain completely slipped a cog. I would imagine that it was put in place to keep people from accidentally overloading themselves, but an option to extensively burden yourself makes sense.

**Comment by ifreund** [comment]
>If dangerous pickups is disabled, items that were auto-foraged should be moved to inventory, rather than dropped.

I think you may have this backwards:  *enabling* not *disabling* dangerous pickups should cause the behavior you described.

**Comment by communistkiro** [comment]
@ifreund , my mistake, I'll edit it.
