### ISSUE TITLE
roof-mounted external tank (200L) on shopping cart (\wo roof)?

### ISSUE THREAD

**Issue by communistkiro** [CleverRaven/Cataclysm-DDA#30186]
**Describe the bug**  
Examining my self-built shopping cart consisting of `4'' casters`, `shopping cart basket`, and `superalloy coating` with a 200L tank within 6 tiles allows highlights `roof-mounted external tank (200L)` on the vehicle (skills and tool reqs being met), despite there being roofless.

**To Reproduce**  
See above. Will test on most recent build and a spawned cart, and report back.

**Expected behavior**  
No roof -> no roof-mounted things. Otherwise, my military, nuclear-powered, roof-mounted solar turrets shopping carts will reign down hell.

**Versions and configuration(please complete the following information):**
 - Game Version: 0.D-2165-geea880c
 - Graphics version: tiles
 - Mods loaded: Aftershock, ...

**Comment by Night-Pryanik** [comment]
While example you provided came from Aftershock mod, there is a more general issue like ability to mount solar panels or turret mount on roofless vehicles.
