### ISSUE TITLE
food dehydrator w/ atomic battery mod doesn't work

### ISSUE THREAD

**Issue by communistkiro** [CleverRaven/Cataclysm-DDA#30184]
**Describe the bug**  
`food dehydrator (off)` doesn't want to reload, and hence also work, with plutonium cells after an `atomic battery mod` has been installed. The UPS mod slowly recharges the thing, drain power from your bionic power or (adv.) UPS. The extra battery mod only doubles capacity, but should work- didn't test.

Looking for any differences of the json entries of all the tools/weaps I had atomic battery mods on that worked, particularly the flags, and this thing wasn't helpful. Didn't have internet ~1w, so 

**To Reproduce**  
New world, no mods, only core; new char, debug in `food dehydrator (off)`, `atomic battery mod`, and >= 1 `plutonium cell`. Install mod on tool, try to reload, violá.

**Expected behavior**  
It to work.

**Versions and configuration(please complete the following information):**
 - Game Version: 0.D-2165-geea880c
 - Graphics version: tiled
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

**Comment by esotericist** [comment]
The atomic battery mod just flat out does not work right now for anything. Has nothing to do with the food dehydrator.

I'm working on it.

**Comment by Inglonias** [comment]
It takes plutonium as ammo, but it also only accepts battery magazines. As a result, right now it accepts neither. Sorry about that.

**Comment by communistkiro** [comment]
Is this related #26498? 
Anyways, the `electric jackhammer` and `soldering iron` could have it installed _and_ reloaded,

**Comment by esotericist** [comment]
Just so you know, the current plan is actually to completely remove the atomic battery mod and replace it with craftable non-rechargable plutonium power cells. So don't make any plans that rely on using the atomic battery mod itself.

**Comment by communistkiro** [comment]
Is this related #26498? 
Anyways, the `electric jackhammer` and `soldering iron` could have it installed _and_ reloaded,
