### ISSUE TITLE
Cellphones from Battery Overhaul (#29651) persists as (U)nloadable even when empty.

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#30185]
**Describe the bug**  
Cellphone remain as an Unloadable choice despite removal of battery-magazine with latest Battery Overhaul changes from #29651 

**To Reproduce**  
Unload a Cellphone with new battery overhaul changes and the cellphone remains as an Unloadable item in menu regardless, despite player cannot interact with it further.

**Expected behavior**  
Items/tools usually disappear from (U)nload menu once it's empty of battery/ammo/magazine etc.

**Versions and configuration(please complete the following information):**
PR 8897.

**Comment by Inglonias** [comment]
I'll take a look at this later today. Thanks for bringing it to my attention.

**Comment by evankimori** [comment]
@Inglonias The Battery change took a while to get adjusted to but I see it's doing pretty well so far so I'm glad to help test it. :)

Question though since I just found this one: are Storage Batteries not repairable? Cannot repair them whilst mounted on vehicles nor by hand interacting with a Welding Rig. Nothing in their description allows for repair. Is this intended?

I've also gotten a strange issue with making a Pedal Charger and suddenly all batteries in Vehicle Charger Storage being randomly depleted and the mounted Batteries (Storage ones as well) losing charge with no activated appliances. I'll post this if I manage to pinpoint where it's coming from.

**Comment by Inglonias** [comment]
I appreciate your understanding. It's certainly forcing me out of all kinds of comfort zones for sure.

> Question though since I just found this one: are Storage Batteries not repairable? Cannot repair them whilst mounted on vehicles nor by hand interacting with a Welding Rig. Nothing in their description allows for repair. Is this intended?

It looks like that's caused by #29552

> I've also gotten a strange issue with making a Pedal Charger and suddenly all batteries in Vehicle Charger Storage being randomly depleted and the mounted Batteries (Storage ones as well) losing charge with no activated appliances. I'll post this if I manage to pinpoint where it's coming from.

I'll have to look at this too. My current plan is to do a quick fix for #30184 and then take a look at this one.

**Comment by evankimori** [comment]
@Inglonias 
> I appreciate your understanding. It's certainly forcing me out of all kinds of comfort zones for sure.

Yeah I've seen the Reddit assholes complain yet refuse to do any kinda testing - much less proper feedback. If the change is to remain as an upgrade: one can't complain about features if you're not willing to give back to the community.

> It looks like that's caused by #29552 and is intentional.

Well that's disappointing...yet...it'll force some adaptation I guess. Sigh. Means I just have to scrap some of them. Ah well, adapt or die. I'm still looking out for a change to this if they plan on keeping it this way but meh. I'll survive either way. Players can't be rolling around flawlessly all the time then. And with the adaption of the Blob (Frames) systems, Wind/Water mills will make Innawoods games still survivable.

What I find odd though is that this change to unrepairable Storage Batteries is made perm...yet we can still repair Car/Motorcycle Batteries. I know the overall charge storage is obviously smaller but I just don't personally see the reason why this is a thing that the smaller batteries can be repaired but not the larger ones. Just my 2 cents.

> I'll have to look at this too. My current plan is to do a quick fix for #30184 and then take a look at this one.

Aight, did some more tests for you and I have some more data. Please indicate if you want these in separate issue tickets.

- UPS modded Firearm Repair Kit does not drain from loaded, charged UPS with a damaged/repairable weapon in inventory. (**_Current example is a H&K UPC @ 50%_**) UPS is loaded with a fully charged Heavy Battery Cell (high capacity) but when activated to Repair - the tool just blanks off and does not activate or do anything. If UPS is dropped: tool does not (A)ctivate. 
--Removed the UPS mod on the FRK, built a new one and added it to the tool and the issue persists so it's not something with old coding from the previous system. (Since this is an older savegame I'm testing on.)

- I think I pinpointed -somewhat- where the "power drain" comes from with the previous example of the pedal charger. Damaged Storage Batteries have a red (*) in their power readout on a vehicle/frame screen. No idea what this symbol is for but apparently damaged storage batteries when installed on a vehicle with no power draw (e.g. appliances, welding rig, fridge etc) - they seem to "drain" power from other batteries or 'leak' in some way because the power storage drops slowly for some reason. Not 100% sure on this because I don't know the background coding for this setup but I guess with this input -you can take a look at how it's structured. :)
--The reason I bring up this is because I stopped having the issue of power drain once I removed the damaged Storage Battery unit. Since as above - they are unrepairable - I scrapped it and rebuilt it into something else and reused that new battery so far. No issues with installing a fresh/fully repaired battery so you can take that under consideration.

I just had to type these out before leaving work today so please tell me if you'd want these in separate issue tickets.

**Comment by esotericist** [comment]
@evankimori *Please* always open separate issues for separate problems, rather than shoving them in something that seems tangentially related (and try to search to see if there's already an issue or PR touching on them). There's too much of a risk of the information not getting to someone who might be in a position to do something about it if it's hidden somewhere irrelevant. I just happened to look here out of curiosity, if I hadn't, I wouldn't be able to give you these answers:

Re: UPS Conversion Mod: It is completely broken right now, and it's in my task list.

Re: red asterisks: Those do, in fact, indicate that the storage item is sufficiently damaged it will leak charge/fuel. This applies to all installable batteries as well as all tanks. Basically, if it's below 50% durability, it will leak over time. Not a bug, an actual gameplay element.

Re: storage batteries: it is in fact intentional that they must be disassembled in order to get parts for reassembly. Lithium-Ion battery cells are not servicable outside of factory conditions. Car batteries are lead-acid batteries, and fairly trivial to maintain. Has nothing to do with the size, it's due to the technology. Small Storage Batteries are smaller than car batteries, and cannot be repaired either.

Once again: please keep issues focused, they aren't meant for this kind of back and forth (and you might not be as fortunate in the future about getting the information you're looking for this way).

**Comment by evankimori** [comment]
@esotericist Thank you for the helpful info. I'm still learning my way around Git here but thank you and the community for being so patient and teaching. :) I've honestly been trying to avoid the Discord server as I'm not too much a people person outside of working hours but it seems I may have to pass in if it is I have something to contribute because clearly I'm not doing this properly. :)
