### ISSUE TITLE
NPC despawning solutions

### ISSUE THREAD

**Issue by communistkiro** [CleverRaven/Cataclysm-DDA#30189]
**Is your feature request related to a problem? Please describe.**  

On my main save 3 NPC despawned- why, I dunno. I usually just have psychopath and kill everything, but I decided to try Danny's new things. 

So during the blackbox transcript mission, my dude disappeared at -1 of research facility, the `lab_basement_hiddenstairs` or whatever it's called in mapgen. It's a a 1x1 overmap tile, so you'd think I'd see him somewhere. With a clairvoyance artifact he's nowhere to be found. The blackbox transcript on the other hand was supposed to be found 4 overmap tiles away from the basement, i.e., in solid rock. I mined towards there, before he'd disappeared and the clairvoyance, having never seen the basement, thinking there a secret room somewhere accessible only through the correct number of left and right mech. winch operations. That was that reason I asked the NPC to come over- to try and make him somehow use the winch at the same time as me, thinking it's like a obligatory, scripted NPC-related quest. Nah.. Told him to guard went mining, and now he's lost. 

Two captives I found in a military outpost who were 2 tiles away from base camp disappeared too, after I'd told them to stay guard. 

Dunno if me teleporting around for utility at time has anything to do with this. 

The `game state` shows both the first npc and the captives on the same overmap tile, but the character editor doesn't see them. Not accessible through radio because guarding is considered a mission, can't talk to them, cause not spawned- like not even teleported in the solid rock or tree, just not there. 

**Desired solution and alternatives**  
- Make `guard`ing not a mission and interruptible over radio,
- or add a `teleport to me` in the debug menu for already spawned NPC, 
- or some kind of magical pathfinding to get them from the minus realm back to cdda.

**Comment by davidpwbrown** [comment]
The teleporting around does have something to do with it.
Teleporting seems to break various things, and can cause bugs when you are using it to hunt bugs, making it unhelpful.
When I was adding the NPC radio contact, using debug teleport caused them to not register their distance correctly, and sometimes they dissappeared.

**Comment by mlangsdorf** [comment]
If you tell an NPC with a two-radio to guard, you can still contact them over the radio and tell them to come to you.  I just verified that I could do that.

**Comment by communistkiro** [comment]
I have [this (screenshot](https://www77.zippyshare.com/v/U8yKq70X/file.html
) for both the captives, the other NPC, although I was certain was guarding, doesn't appear to be so according to the followers tab. All three have the two-way radio- I've activated it, I hit enter on the followers' tab, unless I'm using it improperly.. If I'd discovered the base camp, I probably wouldn't've found them.

**Comment by mlangsdorf** [comment]
The screenshot shows them as guarding but also on a mission traveling.  I think I know what happened here: the NPCs were probably not in the your_followers faction, so when they arrived at their destination, they got set to the guard mission without clearing the companion mission traveling.

I don't think this bug can be easily recovered through code though I'll think some more on it  However, if you go into your save folder and the world directory and poke around in the o.0.0 and o.0.1 files until you find the NPCs, you could make sure all of the companion_mission_ids look like this:
`"companion_mission_role_id":""`
and the NPCs should pop back into the world.

**Comment by communistkiro** [comment]
All of the `o.%d.%d` files with `"npcs":` have empty brackets `[]`. And `role` is not to be found once, and the few maps that do have a `mission` string are critters or monsters w/ `"mission_id":-1.
The followers tab remains the same, only the my base camp has been erased from there (unless there's a time limit how much they (who's they when nobody's there tho..?) can last wo/ food); I still haven't found it because the mapgen is fugged and the refugee center is supposedly in the middle of a river, even tho it's not, there were 2 overmap swamp tiles like 15 tiles away.


So, I guess it'll get fixed eventually. However, the teleport to me would still be nice, if any of the map files, or game files, or any file indeed has the location and full info for the npcs that've already spawned.

**Comment by davidpwbrown** [comment]
ah. Basecamp deleted whilst they were travelling to it? that could do it.

**Comment by communistkiro** [comment]
Well, I didn't look into the files or their existence as it happened. But the overmap got regenerated and my char's memory of it go del'd after I'd updated. The river could've been there on accident, could've been because I'd placed 2 tiles to have water nearby and not go to the end of the world, or could've been some patch migration error? There was, indeed, a very similar river in shape to the south, but I don't recall any other landmark from the south being transposed up.
