### ISSUE TITLE
Temperature Calculation is broken.

### ISSUE THREAD

**Issue by Greevv** [CleverRaven/Cataclysm-DDA#30180]
**Describe the bug**  
When wearing light clothing during summer, character quickly dies of heatstroke. Warmth values vary by up to 40 points depending on whether you are inside or outside and the temperature on the dive watch does not reflect this. Warmth values for body parts vary wildly even if no clothes are worn.

**To Reproduce**  
1. Create a new world during the summer. Other seasons may work, but summer does for certain. 
2. Spawn in some clothes. Wear them.
3. Go indoors.
4. As soon as your character has a body part that is "warm", that body part starts getting damaged extremely quickly.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: Latest experimental.
 - Graphics version: Tiles

**Comment by brobey8** [comment]
I have just updated my experimental to solve the issue with instant rotten corpses and I am pretty sure I am now encountering this bug. 

My character is dressed in fairly heavy clothing and dies in a few turns, taking a lot of damage from seemingly nothing.

**Comment by GreevyGreev** [comment]
Yep, that's precisely what happened to me and it took some trial and error to figure out what was causing it.

**Comment by GreevyGreev** [comment]
Did some testing and being wet affects it a LOT. As soon as I dried out I started taking damage again.

**Comment by GreevyGreev** [comment]
I suspect the RNG update broke it with the wetness changes somehow.

**Comment by TechyBen** [comment]
Thanks. Though it was me... was wondering why the (possibly ice?) lab I'd just survived in for 10 days was either cooking me or freezing me instantly... I though I was being stupid and forgetting to wear/work safely with temp protection. But no, my legs/char/things died very quick from full health, and no "frostbite" warning, just goes -31 degrees and breaks arms/legs/head and dies.

**Comment by Inglonias** [comment]
Can confirm this seems to be happening in build 8897, but not in build 8890, which is the most recent build I can use prior to that one.

**Comment by Greevv** [comment]
Same here.

**Comment by brobey8** [comment]
I can also confirm that reverting to the previous 8890 release resolves the issue for me.
