### ISSUE TITLE
UPS in energy weapon lab finale does not have a magazine

### ISSUE THREAD

**Issue by Kirefire** [CleverRaven/Cataclysm-DDA#30196]
The UPS in the energy weapon lab finale does not have a magazine, while the previous batteries spawn.

**To Reproduce**  
1. Find the Finale in question whether or spawning from a lab finale start.
**Expected behavior**  
The UPS having a charged magazine as well as the removal of the old Batteries.

**Screenshots**  
![Batteries that maybe shouldn't exist](https://user-images.githubusercontent.com/20845317/57113457-7f4e3880-6cf9-11e9-80de-9db9d6523c1b.PNG)
![UPS not having magazine](https://user-images.githubusercontent.com/20845317/57113458-7f4e3880-6cf9-11e9-894d-7777f08a596c.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10, presumably all other platforms as well.
 - Game Version: 0.d-2518-g65a0502
 - Graphics version: Tiles
 - Mods loaded: DDA

**Comment by Inglonias** [comment]
This was missed because the lab finales are not part of JSON right now. I'll see what I can do about this.

**Comment by eilaattwood** [comment]
Actually crafting yield UPS with no magazine as well.

**Comment by Inglonias** [comment]
> Actually crafting yield UPS with no magazine as well.

That is intentional. UPS takes heavy batteries now.

**Comment by Inglonias** [comment]
Back to the issue itself here, it looks like given the way that the labs are currently handled, the best fix would be to JSONize them. Unfortunately, I am not a map maker.
