### ISSUE TITLE
Alcohol makes you pass out

### ISSUE THREAD

**Issue by chaoticidealism** [CleverRaven/Cataclysm-DDA#30198]
**Describe the bug**  
Drinking any alcohol whatsoever makes you pass out immediately. For example, a Hobo character with all stats 8, no traits, took one sip of cheap wine and passed out 291 times in a row.

**To Reproduce**  
1. Drink an alcoholic drink.

**Expected behavior**  
Alcohol shouldn't make you pass out until you've had a lot of it.

**Versions and configuration(please complete the following information):**
 - OS: Win 7
 - Game Version: 0.D-2518-g65a0502
 - Graphics version: Terminal
 - Mods loaded: Dark days ahead, Disable NPC needs, generic guns, makeshift items, more survival tools, mining mod, mutant NPCs, mythical martial arts, no flaming weapons, classes and scenarios, manual bionic installation, safe autodoc

**Comment by esotericist** [comment]
There's some problems with evaluating chances for certain effects to fire that are currently in the process of being corrected. This is an affected effect.

**Comment by kevingranade** [comment]
Should be fixed by #30197 
Please reopen if it recurs.
