### ISSUE TITLE
NPC state doesn't get reset properly after character death

### ISSUE THREAD

**Issue by ethankaminski** [CleverRaven/Cataclysm-DDA#302]
Sometimes, when I start a new character in an existing world, I'll encounter the started NPC that a previous character knew, who thinks I'm still the same character (including asking about my previous quest!). Often they'll be in the new shelter, as well.

**Comment by qbradq** [comment]
#11384 changes NPC behavior such that this can be closed. Validated new behavior with the following test:

- Create character A
- Create character B
- Create an NPC with a mission
- Accept mission with character A
  - At this point character B can also accept the mission
- Suicide character A
- Mission is still available to character B
