### ISSUE TITLE
Add disassembly to bullets that don't have one.

### ISSUE THREAD

**Issue by YukariMindGap** [CleverRaven/Cataclysm-DDA#30201]
**Is your feature request related to a problem? Please describe.**  
As you can see, .380 and .357 caliber bullets cannot be disassembled, even though none of the bullets are described as "cannot be disassembled or reloaded".

**Describe the solution you'd like**  
Add the ability to disassemble the bullets along with the materials gained for the bullets

**Describe alternatives you've considered**  
If you meant for the bullets to never be able to be disassembled or reloaded, add a description that says that.

**Comment by tenmillimaster** [comment]
Woopsies. I accidentally a thing it seems. Thanks for fixing my mistake!

**Comment by YukariMindGap** [comment]
I fixed my own problem
#30293
