### ISSUE TITLE
Add high-capacity battery crafting recipe and disassembly

### ISSUE THREAD

**Issue by YukariMindGap** [CleverRaven/Cataclysm-DDA#30202]
**Is your feature request related to a problem? Please describe.**  
I don't like it when i have piles of high-capacity battery cells and no way to use them in crafting. There are the normal batteries' crafting recipes which, medium and up, requires batteries of a lower size to craft. However, you can't use high-cap versions of the batteries to craft a battery of a larger size, even if it would produce a non-high-cap battery cell. Also, the high-cap medium and high battery cells can't be disassembled, even if the normal medium and heavy batteries can.

**Describe the solution you'd like**  
Either add high-capacity batteries to existing crafting recipes or add a new crafting recipe that uses the high-capacity battery cells to produce a high-cap version of a larger battery. Also, add disassembly to the high-cap medium and heavy battery cells

**Describe alternatives you've considered**  
If you meant for the high-cap batteries to not be craftable, add descriptions that say that.

**Comment by kevingranade** [comment]
Just to clarify, the cells are intended to be uncraftable, but assembling
them into batteries should be doable.
