### ISSUE TITLE
Allow disassembly on reloaded ammo

### ISSUE THREAD

**Issue by YukariMindGap** [CleverRaven/Cataclysm-DDA#30200]
**Is your feature request related to a problem? Please describe.**  
In this game, you can reload ammo from various materials pretty easily. However, the reloaded ammo cannot be disassembled even thought it would be pretty easy to disassemble.

**Describe the solution you'd like**  
Make them disassemblable and add the materials gained from it.

**Describe alternatives you've considered**  
If you meant for the bullets to never be able to be disassembled, add a description that says that.

**Comment by dommon** [comment]
well, reloaded ammo is also always magically weaker than factory loads, whilst in reality you would be fine tuning hand loads to the gun they are intended to be fired from, getting potentially match grade performance loads - +P+ pressures, superior accuracy and reliability. tho i agree you would be loosing some wounding performance over super-engineered modern bullets (9mm para comes to mind) when hand-forming them by (casting from lead/jacketing in hand press)

**Comment by SirPendrak** [comment]
I remember having one character that found gun-basement early on, and inside there were tons of reloaded ammo for guns i did not owned. So i grabbed all theese, with inteend to make some granades or pipe bombs, but then i realised its not possible to disassemble theese munitions, so big upvote from me.
