### ISSUE TITLE
Minifridge/freezer doesn't work outside the reality bubble

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#30209]
**Describe the bug**
Vehicle fridges/freezers do not keep their contents cool when the vehicle is distant from the player.

**To Reproduce**  
Set time to summer.
Spawn a luxury RV, spawn a minifreezer, install the minifreezer.
Spawn 10 chunks of meat.
Wait 6 hours for it to reach ambient temperature.
Put in minifreezer.
Turn on the freezer.
Wait 6 hours for the meat to freeze.

Observe the specific energy of the meat is low and decreasing.

Move far enough away that the reality bubble excludes the vehicle.
Wait for 24 hours.
Return to the vehicle.

The meat specific energy has increased and it's probably thawed. Once the player is nearby again, it'll slowly re-freeze.

Similar effects with minifridges (without the freezing): cold items unexpectedly warm up.

**Expected behavior**  
There should be no difference in freezer operation when the vehicle is distant vs. nearby.

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 18.04.2
 - Game Version: 0.D-2530-gaf7f5cdcd9
 - Graphics version: tiles
 - Mods loaded: none (core dda only)

**Comment by Hirmuolio** [comment]
Found the reason, working on fix.
