### ISSUE TITLE
Redundant table examination menu

### ISSUE THREAD

**Issue by chaisawlajatang** [CleverRaven/Cataclysm-DDA#30217]
**Describe the bug**  
Action menu appears every time I try to pick up items from the table.

**To Reproduce**  
1. Go to the table with some items on it.
2. Try to pick up the items by 'e'xamining the table.
3. Action menu pops up.

**Expected behavior**  
The most common situation when I (and I dare to say other players too) 'e'xamine the table is when I want to pick up items from it, especially at the early game. We already have crafting menu on a separate key. I know the described feature is for prolonged and delayed crafts, but it's not very convenient interface-wise. Action menu popping up just for nothing is pretty annoying.

Maybe it could be transferred somewhere in the main craft menu? Like another tab 'unfinished crafts' or something.

**Comment by esotericist** [comment]
The reason the craft menu is on the table's examine menu is there isn't currently a method in the craft menu to select *which* table you'll be working with, which is a meaningful choice.

If all you want to do is grab things from the table, why not use `g`?

**Comment by kevingranade** [comment]
If you don't want to risk having an interaction menu pop up, use 'g'rab instead.

This is a specific instance of a general problem, which is that 'e'xamine is a heavily overloaded "do-everything" interaction.  We have started extending the 'g'rab interaction to do the right thing, and I understand that will be a potentially painful to switch out your muscle memory, but the 'e'xamine key is for interacting with things, not for just picking up items.

Having said that, it's possible we can streamline the 'e'xamine menu. For example, what if we presented items to pick up and interactions all in the same menu?

**Comment by chaisawlajatang** [comment]
>For example, what if we presented items to pick up and interactions all in the same menu?

Sounds nice, in fact. It would help to interact with an item without having to pick it up, adding usability of the popping menu.
Well, if it's made for the future heavy use of 'e'xaminate button, then looks like I should rewrite my muscle memory.

**Comment by joe9000** [comment]
i'd rather bite the bullet now and retrain on [g]rab for picking up items off of furniture. complements [G]rab in a mildly intuitive way. that clears the way for an enhancement to the crafting table [e]xamine where the "get items" menu item is replaced with a "use items" menu item that performs an [a]pply command but filters to items in the square with the furniture that you [e]xamined. this would gel nicely with the heating up mechanic because you could keep your pot on the table you use to craft food and select the pot to heat up food without navigating a list of every [a]pplyable item within the local 3x3 squares. i'll create a new issue for that

**Comment by Little-119** [comment]
@esotericist If I remember correctly, crafting in the craft menu gave you a choice of which nearby table to use. It was then changed to automatically select the best workbench, and only ask the player what to do if there is nothing that can be used as a workbench nearby.

**Comment by kevingranade** [comment]
Final answer is that this use case is handled by 'g'rab, not examine.
