### ISSUE TITLE
JSONize lab finales

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#30210]
**Is your feature request related to a problem? Please describe.**  
Lab finales are currently generated in the C++ code, making editing what they drop a relative hassle.

**Describe the solution you'd like**  
JSONize lab finales like we have everything else.

**Describe alternatives you've considered**  
N/A

**Additional context**  
I'll admit it. If you can do this, you basically solve #30196 for me. I'll continue looking into solving that myself, of course, but a man can dream, right?

**Comment by Inglonias** [comment]
@ZhilkinSerg mentioned in #21824 that lab finales likely would not be moved to JSON. If there's a good reason for that, I can close this issue, and continue looking for other, non-lazy solutions to the problem.

**Comment by ZhilkinSerg** [comment]
One can use nested mapgens to move more things to json.
