### ISSUE TITLE
Impossible to sleep on hard ground

### ISSUE THREAD

**Issue by Vzor-** [CleverRaven/Cataclysm-DDA#30221]
**Describe the bug**  
This is similar to #28247 but more severe in scope. If you attempt to sleep in a cave (that is all I have tested) you will fail until fatigue causes you to pass out.

**To Reproduce**  
1. Make a basic survivor
2. Teleport to a cave, go down a level
3. Teleport in enough food and water
4. Attempt to sleep for 5 days straight, pausing only to eat/drink

**Expected behavior**  
Sleep. Bad sleep, maybe cut short or something, but sleep of some sort.

**Versions and configuration(please complete the following information):**
cataclysmdda-0.D-Windows_x64-Tiles-8897
Vanilla

**Comment by MrHrulgin** [comment]
Speaking as someone who has attempted to sleep on the ground with only a coat to throw over myself (it was a camping trip where I forgot my sleeping bag and pad) the real unreal thing is how long you can go before fatigue wipes you out.

**Comment by Vzor-** [comment]
I have slept on the ground before with nothing but a coat, as have many other people. It sucks but it is certainly possible.

**Comment by Night-Pryanik** [comment]
I never claimed it's not a bug. 
I'll add the "Bug" tag when I'll be at my desktop.
