### ISSUE TITLE
Anesthesia kit can't be unloaded, and once reloaded can't be used

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#30230]
**Describe the bug**  
Anesthesia kit can't be unloaded, and once reloaded can't be used
**To Reproduce**  
1. Get anesthesia kit
2. Try to unload : you can't
3.  Use three times on auto doc to empty
4. Get anesthetic
5. Reload
6. Try to use autodoc : You can't

**Expected behavior**  
Being able to load unload and using the auto doc with it.

**Versions and configuration(please complete the following information):**
 - OS:  Windows 10
 - Game Version: experimental build #8897
 - Graphics version: Tiles 
 - Mods loaded:  "dda",  "no_npc_food"

**Additional context**  

Definitely caused by #30131 .

**Comment by Fris0uman** [comment]
So I re-tested my local branch of #30131  and it works, you can unload, reload and use the kit. Something else has broke in between.

**Comment by Fris0uman** [comment]
So there is no logic in place (or I can't find it) for a tool that is also a container.
When we put a liquid inside a container it change its `contents` but not it's charges.
Adding : 
```c++
    if( is_tool() || is_gun() ) {
        for( auto &it : contents ) {
            if( ammo_type() == ammotype( it.typeId() ) ) {
                charges = it.charges;
            }
        }
        if( ammo_data()->phase == LIQUID ) {
            if( is_container_empty() ) {
                charges = 0;
            }
        }
    } 
```
To `on_contents_changed()` does make the content of the tool/container affect it's charges, but I haven't figure out how to make the charges of the tool afect it's content.

Or maybe it's not the right way to go at it at all.

**Comment by Shibimon** [comment]
I just found this bug and can confirm, making anesthesia is no simple task as i cooked over 500 wines to make just 3 "charges" for the used kit and filled with it still marks 0 charges.
I also noted that reloading the kit shows twice the anesthesia for reload, but tried multiple times unloading and reloading the other one and never "charged" the kit but dont know if it is somehow related.
![imagen](https://user-images.githubusercontent.com/43771067/57584277-920dfd80-74af-11e9-8f08-04fefe8b2f52.png)

**Comment by Shibimon** [comment]
Fiddling with reloading and recrafting the kit searching if i have done something wrong or was just a bug, i also discovered you can fill the empty kit with 3L of other liquids (like clean water) and keeps using just 0.25L of the storage volume space, not marking what liquid is in or how many sips have left in it in the name like other watertight and or sealable containers, but perfectly usable as a quantum 3L jar.

**Comment by Fris0uman** [comment]
I just tried that and could put 3L of water in it and not more thant that, this is normal behavior.

**Comment by Shibimon** [comment]
Im sorry if im not expressed right, english is not my main language.
What i meant to say is that you can store 3 liters of liquid in a container that only use 0.25 of player inventory, other containers normally occupy at least the same (a 3L jar uses 3L of the inventory space)
With 3L jars i can fit in 12 portions of water in 3L space.
With 6 half liter plastic bottles i can fit 12 portions of water in 3L space.
With 12 anesthetic kits and its quantum space i can fit 144 water portions in 3L space (it still wheights correctly i think, but the volume is definitely wrong)

**Comment by Fris0uman** [comment]
Ah I see what you mean, I'll add a fix for it in #30255. Thanks

**Comment by Fearen-sm** [comment]
This behavior of anesthesia kit also applies to kits found in world, not only for crafted ones. Even starting kit behave like this, you just cannot recharge it with any anesthetic (makeshift or one found in hospitals for example).

**Comment by Fearen-sm** [comment]
Anesthesia kit start working properly and you now can do autodoc surgeries, but when you use anesthesia charges this is what you'll get.

DEBUG    : Tried to set invalid ammo of none for anesthesia kit
 
 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 377
