### ISSUE TITLE
Seatbelts all provide equal protection

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#30239]
**Describe the bug**  
A 5 point harness provides no more protection against injury than a seatbelt. It is only more resistant to being destroyed. 

**To Reproduce**  
1. Smash into a wall at high speed wearing a seatbelt.
2. Smash into a wall at high speed wearing a 5 point harness.
3. Take 0 damage either way unless the part breaks.

**Expected behavior**  
A seatbelt would provide protection from damage to a lesser degree or different body parts than a 5 point harness does.

**Additional Context**
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/vehicle_move.cpp line 1265 is the current calculation for protection from being thrown from the vehicle, and doesn't differentiate about seatbelt type as far as I can tell.

**Comment by jeremyshannon** [comment]
It seems to me like seatbelts should suffer wear when a vehicle stops hard. Maybe scaled a bit so a belt at full repair would take only the bare minimum or even no wear, while a previously damaged one would take more damage proportionate to how bad it is, and so be more prone to snap.

**Comment by MrHrulgin** [comment]
Makes sense. Based on [this answer](https://www.quora.com/What-happens-to-seat-belts-during-an-accident), modern seatbelts trade better crash responsiveness for lower repeated effectiveness. Whether that is modeled ingame is a whole separate question, as the level of technology involved seems more like "piece of rope across your lap" or "web of ropes holding you down". Perhaps separate actual seatbelts and jury-rigged versions? The better ones would need more fabrication & some parts (or could only be salvaged), but respond better to faster crashes, while the ones made entirely of rope are far more accessible but provide less protection.

**Comment by WeisserRitter** [comment]
Perhaps the code regarding the player being shaken and taking damage should be reworked to inflict damage upon their seatbelts as well, if they are being worn. With a five point harness having far superior durability to the seatbelt.
