### ISSUE TITLE
Batteries magically generating when dissembling cellphones

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#30236]
**Describe the bug**  
When you disassemble a normal cellphone you recieve old batteries as well as a charged cell.

**To Reproduce**  
1. put a battery in a cellphone, 115/150 for example.
2. disassemble it and open inventory.
3. notice how you now have 150 batteries AND a 115/150 cell in your inventory.

**Expected behavior**  
To just get the charged cell back and not get randomly extra old batterys.

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version: [o.D-2546-g2ac90b3]
 - Graphics version: [Tiles]
 - Mods loaded: [Alternative map key, folding parts pack, classes and scenarios mod, more locations, urban development, fuju's more buildings,]

**Additional context**  
Might work for other electronic tools but I only noticed it with basic cellphones.

**Comment by esotericist** [comment]
That's odd. I can't seem to reproduce this.
![image](https://user-images.githubusercontent.com/1569754/57182580-8c803a00-6e55-11e9-84d0-fadf7a2a6d48.png)

![image](https://user-images.githubusercontent.com/1569754/57182585-986bfc00-6e55-11e9-96f6-a7993a8e6bdc.png)
![image](https://user-images.githubusercontent.com/1569754/57182589-9efa7380-6e55-11e9-8603-45ae9a2f1465.png)

**Comment by esotericist** [comment]
Oh, disassemble! Now I understand.

**Comment by esotericist** [comment]
Fascinatingly, it gives the 150 battery charge regardless of whether there's a battery cell in the phone or not, or what size the battery cell happens to be.

**Comment by RocketPapaya413** [comment]
Crafting an underbarrel laser sight using a light battery cell (100/100) leaves battery (100), which can be used to refill empty battery cells, in my inventory afterwards.

Crafting a medium battery cell using 6 light battery cells (100/100) however does not give any battery goop.

Radio activation mod and heavy battery cell additionally gave battery items. 

Rail laser sight and concentrated acid (from 5 light battery cells (high-capacity) (150/150) did not.

**Comment by esotericist** [comment]
I've found the source of this, am currently trying to find the best fix for it.

**Comment by Inglonias** [comment]
Keep in mind that the cell phone is a special case right now.

I didn't want to go through each and every profession to make sure it spawned with charges, so it's the only battery powered tool in the game with initial charges.

My guess is that even though it acts correctly in most cases, the fact that the cell phone itself has charges AND a magazine makes the game a little upset. I think if we just went through professions.json correctly, this would go away.
