### ISSUE TITLE
Issues with mansion's fireplaces.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#30238]
**Describe the bug**  
The fireplaces you find in mansions can't have items dropped on them, making them useless for fires.

**To Reproduce**  
1. Go to a mansion.
2. Be frustrated that you can't use any of the fireplaces scattered around.

**Expected behavior**  
The fireplaces you find in a mansion should be equivalent to the Stone Fireplace you can make from the construction menu.

**Comment by mlangsdorf** [comment]
mansion palettes haven't changed since September 2018 and use f_fireplace for fireplaces.

I loaded a game built on build 8903 (2ac90b3f) and the first floor fireplaces worked just fine: I could drop items in them and ignite fires.

**Comment by MrHrulgin** [comment]
Oh, I see what this issue is. Upon inspecting the fireplaces I was having issues with, they are ones in the basement that are overlapped with broken generators.
