### ISSUE TITLE
suv_atomic debug error after starting a core content world

### ISSUE THREAD

**Issue by Throwaway-name** [CleverRaven/Cataclysm-DDA#30242]
**Describe the bug**  
After starting a new world with only the dda content pack a debug error appears once then never again.

**To Reproduce**  
No clue.

**Expected behavior**  
No errors related to disabled core content packs.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2530-gaf7f5cd
 - Graphics version: Tiles
 - Mods loaded: dda

**Additional context**  
I'd updated my current version by copying the keybindings, lastworld, options, panel_options and user-default-mods files from my previous game.

The suv_atomic is from the BrightNights content pack but it wasn't activated.

**Comment by ZhilkinSerg** [comment]
Yes, there are some issues with cleaning of content after starting in a new world when previously played world had mods activated.
