### ISSUE TITLE
"Reload" is now reload_item

### ISSUE THREAD

**Issue by Throwaway-name** [CleverRaven/Cataclysm-DDA#30241]
**Describe the bug**  
Something changed the "r"eload button in the inventory menu into reload_item.

**To Reproduce**  
Look at an item with charges in your inventory

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2530-gaf7f5cd
 - Graphics version: Tiles
 - Mods loaded: dda

**Comment by esotericist** [comment]
Derp. I'll get that fixed.

**Comment by esotericist** [comment]
(it's literally just from me having a brainfart on what I was doing a search-and-replace on in a previous task)
