### ISSUE TITLE
Mini/carryable charging options?

### ISSUE THREAD

**Issue by TechyBen** [CleverRaven/Cataclysm-DDA#30256]
Now batteries are getting nice charging code. Could we add one or two simple charging options for our survivors?

Such as a hand crank charger (I've had torches/lanterns that have these, and converting them to charge similar very small batteries is simple).

**Describe alternatives you've considered**  
Hand crank chargers, small solar and transfer from car batteries. These options would need (IRL and in game too ;) ) some conversion circuitry, and probably only worth it on smaller batteries. Though a car battery could charge even a power drill 24v battery I guess.

**Additional context**  
For example: https://images.homedepot-static.com/productImages/dd968fe9-0cf3-4565-970f-667007017b83/svn/blacks-whetstone-lanterns-80-9690-64_1000.jpg

While rare to "find" is rather simple to build. A motor in reverse, and knowing how to change the voltages etc so you don't blow the battery.

https://www.instructables.com/id/DIY-Hand-Crank-Phone-Charger/

In game it would turn calories into light for example. Or if a small solar charger added, would allow some time limited charging (still resource limited, as solar cells are rather rare drops in vanilla, and need swapping out or stockpiling of batteries). Balance could be added by their speed of use/charge. Also the hand cranks would be noisey. Solar needs to be outside and would be slow/need tending for swapping out.

Thanks.

**Comment by esotericist** [comment]
I definitely want to make this happen.

**Comment by eilaattwood** [comment]
Maybe make solar backpack usable for charging batteries?

**Comment by TechyBen** [comment]
Thanks. I've not done the hand crank IRL for the phone charger yet... but I'm about to soldier in 4 panels to a 1 panel solar "charge bank" to turn it from something rather not useful to something just above useless. XD

May post the results.

**Comment by Petethegoat** [comment]
There's a `hand_crank_charger` item now with the vanilla game, so I think this issue has been resolved.

**Comment by esotericist** [comment]
The reason this issue wasn't marked closed was because as I mentioned in the PR I used to make the hand crank charger, I believe we still actually need some more to work with.

It's possible someone else might disagree, but I think there's still utility to be filled in this space.

**Comment by Petethegoat** [comment]
Oops, somehow didn't actually notice the PR reference, I just found them in game. More charging would be great.
