### ISSUE TITLE
Dirt lot

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#30267]
While lurking through the `mapgen_functions.cpp` I found a `dirtlot` function. Then I searched through the code and jsons to find out where this map extra should spawn. And it seems that it isn't spawning anywhere.
According to the code, it's a square of dirt, occasional grass, rare shallow pits and sometimes a vehicle (pickup, quad bike, or dirt bike).

![изображение](https://user-images.githubusercontent.com/11132525/57215452-fa676580-6ffd-11e9-8fab-557b3168ffbb.png)

Do we need this map extra, and if we do, where should it spawn?

**Comment by Fris0uman** [comment]
Would it make sens to spawn it away fom cities but near roads ? Like gas stations and road stops

**Comment by JeanLucVanDamme** [comment]
It would make sense as the scene of an interrupted mudding session. (Or whatever other mess-around-with-your-vehicle activities to avoid boredom in rural areas).

https://www.giantbomb.com/forums/off-topic-31/what-is-the-appeal-of-mudding-1491016/

**Comment by Xenomorph-III** [comment]
Is there a chance for the vehicle to spawn working (engine, wheels, gasoline, non-leaking battery), but damaged to represent wear and tear?

**Comment by Night-Pryanik** [comment]
> Is there a chance for the vehicle to spawn working (engine, wheels, gasoline, non-leaking battery), but damaged to represent wear and tear?

Yeah, it's possible.
