### ISSUE TITLE
Alternative Map Key causes Assertion Failure and CTD on new game.

### ISSUE THREAD

**Issue by gynther** [CleverRaven/Cataclysm-DDA#30279]
**Describe the bug**  
Alternative Map Key causes errors when loading world but before you design character. Then after finalizing character same error pops up with an Assertion Failure! which crashes the game

```
 DEBUG    : invalid overmap terrain id "pool_north"
 
 FUNCTION : int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = oter_t]
 FILE     : src/generic_factory.h
 LINE     : 383
```

```
DEBUG    : In overmap special "pool", terrain "pool_north" is invalid.
 
 FUNCTION : void overmap_special::check() const
 FILE     : src/overmap.cpp
 LINE     : 953

```

**To Reproduce**  
Create new world, pick "Alternative Map key". start a game in that world.

**Expected behavior**  
Not crash

**Versions and configuration(please complete the following information):**
 - OS: Win10, Ryzen 5
 - Game Version: 8915 from launcher
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC needs, Alternative Map Key

**Comment by Night-Pryanik** [comment]
Are you sure it's crashing specifically with Alternative Map Key? Have you tried without this mod?
Also, is there any chance that #30273 fixed this?

**Comment by gynther** [comment]
Yes, i've tried it with several other setups and it only crashed with alternative map key. currently playing with a bunch of mods (except alternative map key) and it works fine.

On the second part i have no idea sadly.

**Comment by KorGgenT** [comment]
i'll also confirm that the bug still existed on master when this pr was created. i only tested with the mod, not without.

**Comment by ZhilkinSerg** [comment]
`alt_map_key` mod uses old definition of `pool` overmap terrain with `NO_ROTATE` flag.
