### ISSUE TITLE
Monsters won't follow you up and down in a lot of areas

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#30297]
**Describe the bug**  
I've noticed in a lot of areas recently zombies wont follow you up and down stairs no matter what.

**To Reproduce**  
1. Spawn in a lab, or a LMOE shelter, or a house with a basement
2. Go near the stairs and get a zombie's attention and then traverse the stairs.
3. Wait for the zombie that never comes.
4. Repeat this test at a evac shelter and notice how they do follow you now.

**Expected behavior**  
Zombies able to follow me through z levels stairs always.

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version: [0.D-2638-gd09a0d2]
 - Graphics version: [Tiles]
 - Mods loaded: [Tested on Vanilla]

**Additional context**  
All areas with second floors + roofs seem to work as intended.

**Comment by Dacendeth** [comment]
![stairfail](https://user-images.githubusercontent.com/26881007/57338210-852d8a80-70fa-11e9-955e-0be66d6d5c71.gif) 
here is a gif of a mi-go failing to understand how to use stairs, it actively stands on the tile preventing me from going up at one point during it, but never comes down.

**Comment by Night-Pryanik** [comment]
Updated issue name to mention it's not only zombies, but other monsters too.

**Comment by Inglonias** [comment]
Don't we abstract this behavior into existence when Z-levels are turned off? Is there a reason we can't just keep doing that with Z-levels on?

**Comment by Dacendeth** [comment]
![image](https://user-images.githubusercontent.com/26881007/57660704-d683c100-75b5-11e9-984a-af78f5d5a96c.png)
![image](https://user-images.githubusercontent.com/26881007/57660779-2ebac300-75b6-11e9-8932-27ac2a2ac086.png)
locked a mi-go in the LMOE shelter area and went down, both times it managed to "come down the stairs" and appearing where it's pictured in these screenshots.

**Comment by l29ah** [comment]
Can confirm the issue. There are a few zombies downstairs that won't follow me up. Save: 
[2019.06.14.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3336507/2019.06.14.zip)
0.D-5041-g5d8dcd3826

**Comment by Dacendeth** [comment]
I feel like the PR that linked staircases together fixed this issue, I've had zombies follow me in basically every location now.
