### ISSUE TITLE
New default screen size

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#30291]
I think I won't discover America here by saying that default 80x24 terminal size is outdated to hell.
80x24 terminal size translates into 640x384 pixels on default 8x16x16 font dimensions. And I'm VERY doubtful that anyone plays at default terminal size. I'll take the liberty to say that time for increasing default screen size has come.

I suggest set 1280x720 as a new standard. This size translates into 160x45 terminal size on default font dimensions. I'm pretty sure HD resolution is supported by every modern monitor and most of the modern mobile phones.

The advantages of new, increased, screen size are innumerable. This change can be a first step of upgrading interface to modern standards, and not to mention improved convenience of playing.

**Comment by Zireael07** [comment]
I believe the default size was rationalized as people playing Cata:DDA over ssh? And I know there existed at least one server that provided such an ability. I'm not sure if that's still the case, but if yes, maybe provide a default with increased screen size and a config file that would allow going back to 80x24 for playing over ssh?

**Comment by narc0tiq** [comment]
I play over SSH and I keep my terminal size around 160x41 (but -1 for the tmux status, so call it 160x40). This is a good size.

**Comment by Rail-Runner** [comment]
I still play on 1024x768 resolution, at least keeping it supported would be good.

**Comment by Night-Pryanik** [comment]
> The best idea would be to automatically set terminal size to match current screen resolution on first launch, I think.

Not everyone like to play full-screen.

> I still play on 1024x768 resolution monitor, at least keeping it supported would be good.

Well, the new default screen size could be 1024x768 pixels (128x48 on default font dimensions). It is still better than the old one.

**Comment by Rail-Runner** [comment]
> Not everyone like to play full-screen.

Well, that's how most games work. They're launched in fullscreen mode, but if player doesn't want that, they can be changed into windowed mode in settings.

**Comment by ZhilkinSerg** [comment]
Full screen mode is very unstable on Windows.

**Comment by Zireael07** [comment]
I think he means that Cata should fill the whole screen, not that it should use fullscreen mode.

**Comment by ZhilkinSerg** [comment]
Borderless window then - it behaves better iirc.

**Comment by HeadstrongCatgirl** [comment]
I'm pretty sure it uses the dimensions of the terminal and one can run console-setup to change it in vt. If this is only related to ms windows, you might want to add the "OS: Windows" label.

**Comment by Inglonias** [comment]
If we're just talking about tiles versions (assuming that terminal doesn't try to change the viewport size), then I would like to propose 800x600. It's a heck of a lot better than what we've got, but still not big enough to fill any reasonably modern screen.

**Comment by Night-Pryanik** [comment]
The one thing I don't like about 800x600 and 1024x768 resolutions is their 4:3 ratio. Original 80x24 resolution has 3,33:1 ratio, and I'd like the new standard have more "rectangular" ratio, resembling the original one.

**Comment by kevingranade** [comment]
To clarify, we currently support a minimum screen size of 80x24 (either tiles or characters) and avoid making changes that will not work properly on screens this size.

The proposal is to allow changes that do NOT work at 80x24, instead setting the limit at 160x45 or 160x40 or 128x48.

**Comment by Inglonias** [comment]
In that case a simple doubling of the terminal size would be ok by me.

**Comment by chriseich21** [comment]
160x45 is, imo, also a good resolution for Mobile/Android as far as a balance between in-game vision distance and legibility. Although I run the DeadPeople modded tileset as opposed to retrodays (honestly surprised about feedback that it consumes too much memory considering amount of RAM in any recent semi-flagship phone - no issues with that tileset on Note 9) and now went back to running no tiles anyway.

**Comment by neitsa** [comment]
If I can suggest something which would apply **only** to windows systems (or maybe the tile version in a broader way); 

* Following discussions in the #24528 issue about the Windows crash when the tiles version is in fullscreen.
* Given TheZoneWizard suggestion [on this discourse](https://discourse.cataclysmdda.org/t/tab-out-crash-assistance-needed/20056/10?u=neitsa) post.

A few considerations:

- I think most people **on Windows** want to play on a game size which covers entirely their screen.
    - I obviously don't have any number to back this assertion; just that most people that I know of do this for any game they play.
- People don't SSH to play the tiles version (they can [RDP](https://fr.wikipedia.org/wiki/Remote_Desktop_Protocol) though, but its completely different).
- As fullscreen is bugged with DirectX (see #24528)

Suggestion:

- On windows, for the tiles version, make the default option to be `Windowed Bordeless` and try to reach a size which covers most of the screen.
