### ISSUE TITLE
Item description section of "View nearby items" mode can't be scrolled

### ISSUE THREAD

**Issue by ErdrickXLII** [CleverRaven/Cataclysm-DDA#30292]
**Describe the bug**  
Pressing Page Up/Page Down only lets you scroll down one line, regardless of how much text there is to display.

**To Reproduce**  
1. Have an item nearby with a sufficiently long description (Any gun will work, many other items as well.)
2. Press 'V' to go into "View nearby items" mode (Default keybind).
3. Select the item
3. Press Page Down a few times.

**Expected behavior**  
The item description scrolls until there's no more text to display.

**Versions and configuration(please complete the following information):**
 - OS: Windows
 - Game Version: 0.D-2638-gd09a0d2
 - Graphics version: Tiles
 - Mods loaded: dda

**Comment by FrancisDec** [comment]
Having the same issue here. I'm playing on #8918.

**Comment by Inglonias** [comment]
This is still a problem as of today.
