### ISSUE TITLE
uses wrong eat verb when trying to eat too much

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#30306]
**Describe the bug**  
![image](https://user-images.githubusercontent.com/30208401/57332528-ecdada00-70e8-11e9-9427-86053fa59644.png)

**To Reproduce**  
Try to eat a cattail rhizome when you can't eat any more.

**Versions and configuration(please complete the following information):**
probably not necessary.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of October 9, 2019:
![изображение](https://user-images.githubusercontent.com/11132525/66509952-1909e500-eae5-11e9-8fe5-c7dae5ba8929.png)

**Comment by KorGgenT** [comment]
seconded. closing the issue then.
