### ISSUE TITLE
Crafting auto-uses Filled Containers & discards contents (PR 8918)

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#30308]
**Describe the bug**  
Crafting items that require containers as a component take filled containers, dump contents onto floor and consume the container. Not sure if this is related to #26928 

**To Reproduce**  
1-Craft item and place in Glass Jar (e.g. Coffee x2 into Glass Jar)
2-Drop GJ with contents onto Floor/Cargo space.
3-Attempt to craft item with GJ as ingredient with no (Empty) versions around. (e.g. Match Bomb, Sourdough Starter)
4-Craft (e.g. Match Bomb) will consume the filled GJ container, dumping Coffee x 2 onto floor where container was situated.

**Expected behavior**  
Filled/used containers are supposed to be ignored/unusable once they contain solids/liquids etc. Contents are not supposed to be dumped onto floor.

**Versions and configuration(please complete the following information):**
PR 8918.

Mod list:
[
  "dda",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "growable-pots",
  "makeshift",
  "More_Survival_Tools",
  "crazy_cataclysm",
  "mutant_npcs",
  "boats",
  "deoxymod",
  "blazemod",
  "DP_XOTTO_INDICATORS",
  "DP_REMIX_INDICATORS",
  "DP_AMAZING_CHEST_INDICATORS",
  "necromancy",
  "no_religious_Texts",
  "manualbionicinstall",
  "more_classes_scenarios",
  "RL_Classes",
  "sleepdeprivation",
  "StatsThroughSkills"
]

**Comment by ifreund** [comment]
I can't reproduce this on f2df59c59dc1b3f3d8350c758ca041c903e797bd (~Build 8931) following the steps you provided.  Also unsure how this could happen looking at the code.

If you can reliably reproduce with your save on the latest version would you mind uploading the save?

**Comment by evankimori** [comment]
@ifreund - Sadly, even if I rollback to the save: this was the error on loading. :( I can't get the save to load with the version, having moved to newer PRs to test. :(

 DEBUG    : Error: line 91:21: no such vehicle type or group

      "place_vehicles": [
        { "vehicle": "buses", "x": 35, "y": [ 6, 7 ], "chance": 35, "status": 0, "rotation": 360 },
        { "vehicle":
                    ^
                     "buses", "x": 35, "y": [ 16, 17 ], "chance": 35, "status": 0, "rotation": 360 }
      ],
      "vendingmachines": { "8": { "item_group": "vending_drink" }, "9": { "item_group": "vending_food" } },
 
 FUNCTION : bool main_menu::load_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 975

**Comment by Night-Pryanik** [comment]
@evankimori have you encountered this since then?

**Comment by evankimori** [comment]
> @evankimori have you encountered this since then?
Nope. Not been happening for quite some months now. Will close.
