### ISSUE TITLE
Difficulty spike to install more than 1 battery on a vehicle

### ISSUE THREAD

**Issue by Yunatan** [CleverRaven/Cataclysm-DDA#30314]
**Is your feature request related to a problem? Please describe.**  
Installing one and more than one battery on a car shouldn't have equal difficulty. 

**Describe the solution you'd like**  
Require ``electronics 2`` to install more than one power source on a vehicle.

**Describe alternatives you've considered**  
You don't want to know. 

**Additional context**  
Installing two and more batteries on a car has pretty much the same difficulty regardless of the number of batteries.

**Comment by MrHrulgin** [comment]
Wiring batteries in sequence is not more difficult than wiring one battery, though it seems that all vehicle batteries in game are wired in parallel given equal draw across the batteries. Given parallel draw, I'd agree that a second battery should take a little more skill but not have continued scaling of difficulty the way engines do.

**Comment by HeadstrongCatgirl** [comment]
Wiring batteries in parallel is also pretty easy. I think if someone is able to install one, they won't have any issues with installing more.

**Comment by Little-119** [comment]
Does this apply to storage batteries, or just motorbike/car/truck batteries?

**Comment by esotericist** [comment]
So the intent behind this is: swapping out a car battery is easy peasy. Doing anything more involved than that should require some technical know-how.

Gating installing more than one battery behind `electronics 2` is an arguably overly simplified abstraction, but I don't think it's entirely without merit.

I have some longer-term notions about power storage devices and their relationships with vehicles that would have a stronger coupling of game purpose to real-world logic, but I think doing this as an interim "at least be this capable" makes a kind of sense.

**Comment by Ker-Nes** [comment]
Adding a minor electronics requirement to install multiple batteries might be good, although it should not increase further for even more batteries. 2 or 20, same practical difficulty to get it done.

Also, any implementation should remember to not include the difficulty to swap storage batteries in storage cases, for obvious reasons, although it could be included in actually installing multiple storage cases in a vehicle.

**Comment by esotericist** [comment]
Were I to implement this change, it would not increase past that initial elec requirement. The threshold here is simply "more than one battery"

Also were I to implement this change, I would consider the storage case to be "a battery" for the purposes of this mechanic, and the swappable storage battery would not (since it requires that case).

**Comment by eilaattwood** [comment]
Batteries with same capacity and voltage can be wired in parallel without any protection and many real-life technical solutions actually using that. However, in that case if one of the batteries in the pack gets damaged or wears out, other batteries in the pack will be affected to. Connecting batteries with different capacity, current  capabilities, or, especially, voltage is a lot more tricky and requires at least powerful diodes, at most - power converters, manual or automatic switches, etc.

As batteries behave currently in the game, we can suggest that some kind of automatic switching is used, as batteries discharge one after another, and there is no redistribution between batteries with unequal charge.
