### ISSUE TITLE
Quivers and Bandoliers to accept multiple ammo types

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#30319]
**Is your feature request related to a problem? Please describe.**  
Currently you can only have one specific ammo type in the Quivers and Bandoliers.

**Describe the solution you'd like**  
I'd like to be able to load different type of ammo in those. For example I have the Large Quiver, which is able to hold 60 arrows. I'd like to be able to put in 40 Broadhead arrow and 20 Bodkin arrows. Might come at the cost of draw time for normal quivers (the arrows mix as you move) and/or we can see an introduction of new quivers with "slots" where each slot would work separatedly and if ammo in each slot is not mixed no draw penalty happens.

![image](https://user-images.githubusercontent.com/19891532/57367492-61655580-7189-11e9-8d7c-09f23222314c.png)

Same goes for bandoliers, you should be able to put in different types in each single slot.

**Describe alternatives you've considered**  
For quivers: Don't allow mixing in normal quivers and only introduce the "slotted" version with the same encumbrance and volumes but with less capacity as well as little slower draw times. 

For bandoliers: No aternative, this should just be possible. 

**Additional context**  
We should actually be able to even load magazines and ammo belts with mixed ammo types. Not sure if that might be a connected to the above feature or a separate one.

**Comment by tinukedaya** [comment]
Yeah I thought it would probably be unrelated code wise, but it's more or less connected by the "topic", that's why I put it to the additional context.
I might open a separate request for that, not to drive this one off-topic. I'd like to see that happen at one point as well.

**Comment by kevingranade** [comment]
I suspect this would entail a large amount of ui and infrastructure work for a very minimal benefit.

Mixed ammo in a magazine could be simulated by making an ammo variant that specifies the ratio between types, so e.g. you could alternate regular and tracer rounds, or mix in some AP rounds. Tracking individual rounds having different properties in the same magazine is extremely unlikely to be implemented.

**Comment by tinukedaya** [comment]
> I suspect this would entail a large amount of ui and infrastructure work for a very minimal benefit.
This is for the Quiver request or the magazines?

The mixed ammo in magazines was really just an idea that sparked while writing about the quivers. That one is not that important. The benefit I can see in that is when you have a few rounds from all kind of different 9mm ammo, you could refill the whole magazine and do not need to reload all the time.
