### ISSUE TITLE
Using burrowing mutation to dig a pit crashes the game

### ISSUE THREAD

**Issue by halfahermit** [CleverRaven/Cataclysm-DDA#30322]
**Describe the bug**  
Using burrowing mutation to dig a pit crashes the game

**To Reproduce**  
1. Have a player with burrowing trait
2. Activate burrowing through the mutation window
3. Choose "Dig pit" 
4. Choose direction with a diggable terrain
5. Game crashes

**Comment by ejseto** [comment]
I can confirm this. Both shovels and the mutation use the ACT_DIG activity which assumes a bunch of parameters. I don't believe the mutation creates these parameters while shovels do, leading to null pointer dereference for the mutation.

In void activity_handlers::dig_finish( player_activity *act, player *p )
>const ter_id result_terrain( act->str_values[1] );

The shovel code contains these lines:
> act.str_values.emplace_back( moves_and_byproducts.byproducts_item_group );
    act.str_values.emplace_back( moves_and_byproducts.result_terrain.id().str() );

The burrowing code does not.

**Comment by halfahermit** [comment]
Thanks. Not sure if I can assign it but I am working on this one.
