### ISSUE TITLE
Json roofs don't always spawn with ground floor

### ISSUE THREAD

**Issue by curstwist** [CleverRaven/Cataclysm-DDA#30330]
**Describe the bug**  
I have seen two reports of this and got one save file for examination.  I haven't experienced this myself, but thought it was important to post.

**To Reproduce**  
1. Open appended save file
2. Try to go up stairs (either character is fine to choose)
3. Fall through/teleport to see that there isn't a roof.

**Expected behavior**  
Ensure roofs spawn with their ground floors.

**Screenshots**  
![no roof](https://user-images.githubusercontent.com/39442864/57409446-4bba5500-71b6-11e9-8b7b-207d24d999ee.PNG)
![ground with access routes](https://user-images.githubusercontent.com/39442864/57409447-4bba5500-71b6-11e9-8e9a-965eec0a62fa.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Win10
 - Game Version: fairly recent 0.D experimental (I didn't ask for their version #)
 - Graphics version: tiles
 - Mods loaded: 
[
  "dda",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "growable-pots",
  "makeshift",
  "More_Survival_Tools",
  "crazy_cataclysm",
  "mutant_npcs",
  "boats",
  "deoxymod",
  "blazemod",
  "DP_XOTTO_INDICATORS",
  "DP_REMIX_INDICATORS",
  "DP_AMAZING_CHEST_INDICATORS",
  "necromancy",
  "no_religious_Texts",
  "manualbionicinstall",
  "more_classes_scenarios",
  "RL_Classes",
  "sleepdeprivation",
  "StatsThroughSkills"
]

**Additional context**  
save file, use either character.
[Mutant.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3159353/Mutant.zip)

**Comment by I-am-Erk** [comment]
I am pretty certain this is not a json roof. The holes in the roof match exactly with the tile floor and chainlink fences, suggesting it's a procedural roof that didn't form over those tiles. Further, there is no gutter under it, and I have never actually seen this happen despite quite a lot of rooftop exploring.

**Comment by I-am-Erk** [comment]
I'm closing this issue.
![image](https://user-images.githubusercontent.com/45136638/70577189-90004000-1b5f-11ea-9412-476e4b52b15a.png)This is the roof location in the attached save

JSON roofs have overmap id's and register like this:
![image](https://user-images.githubusercontent.com/45136638/70577304-da81bc80-1b5f-11ea-94c2-0e157326ca0e.png)
