### ISSUE TITLE
Some non-watertight containers cannot hold liquid

### ISSUE THREAD

**Issue by Reclusive-reptile** [CleverRaven/Cataclysm-DDA#30331]
**Describe the bug**  
Some cups (`tin_cup`, `ceramic_cup`, etc.) or metal pot can't hold liquid.

**To Reproduce**  
1. Generate new basic vanilla world.
2. Generate new random character, spawn in, wish for any metal pot.
3. Hold pot or place on ground.
4. Attempt to full pot with water and fail.

**Expected behavior**  
Containers to hold water/beer/tea/sewage samples.

**Versions and configuration(please complete the following information):**
 - OS: windows 10
 - Game Version: 0.D-2712-gae9c227
 - Graphics version: Tiles

**Additional context**  
#29706 added a bunch of pots, pans, and glassware that all have `"type": "GENERIC"`. They need to be `"type": "CONTAINER"` or have `"container_data"` fields defined in order to actually function as containers.

**Comment by Zireael07** [comment]
I believe it's intended: if you put such a cup in your backpack, it won't hold water.

**Comment by Hirmuolio** [comment]
There are two kinds of liquid containers.

Watertight. These can contain liquid while in inventory.

Not watertight. These can contain liquid only when held/on ground. Buckets, pans and pots are like this.

**Comment by I-am-Erk** [comment]
Can I get a confirm on this? They have all the same JSON definitions as existing cups, they should hold fluid in all the same situations.

**Comment by MrHrulgin** [comment]
2 days ago I spawned in a tin_cup, held it in my hands, went to a forest pool, tried to fill it and was told that I didn't have any containers. I can't speak to the full set, but some of them don't work.
