### ISSUE TITLE
Proposal: Live dismemberment.

### ISSUE THREAD

**Issue by Greevv** [CleverRaven/Cataclysm-DDA#30343]
**Describe the solution you'd like**  
I propose a system wherein if a zombie's body part takes more than x damage in one hit, the body part is destroyed or lopped off. The zombies would still have their normal health pool, so no need to track HP individually per body part, but if a zombie with 100 health (just an example) takes say, more than 20 damage to any individual limb in one hit, the limb would be dismembered and a flag would be added to the zombie to reflect this. Arm loss could result in either a damage decrease, slower attack speed (zombies are dumb and may not immediately realize their arm is missing, thus leading to wasted attacks.), inability to grab, etc. Loss of a leg would lead to greatly decreased move speed and or make them harder to hit with ranged attacks (smaller target.).

Currently we have no system of determining what limb is hit by each attack, but I suspect it wouldn't be too difficult to implement. Implement some formula that scales off of melee/ranged accuracy to decide if an arm, leg, torso, or head is hit.

I've written up a formula that I believe does this quite nicely. This formula only applies to melee weapons. Due to the differences between the accuracy systems, the ranged values would have to be calculated separately if deemed necessary. 

head_chance = (accuracy + 3) * 1.5 + 10
body_chance = (accuracy + 3) * 2 + 15
arm_chance = (100-(head_chance + body_chance))/1.5
leg_chance = 100 - (head_chance + body_chance + arm_chance)

If so desired, the body part hit could multiply the global HP damage, but otherwise we would simply use this for one calculation, deciding if the body part you hit gets dismembered/disabled.

Formula would scale off of monster HP, exceptions would likely need to be added for monsters such as crawlers which are missing body parts. In the case of those, the hit could be redirected to the next most likely to hit body part.

Dismemberment threshold/chance calculations:
You would have to exceed the threshold of the body part to even have a chance of disabling/dismembering it. Thresholds are calculated as follows:
arm_dc = hp/5
leg_dc = hp/4
Now, the chance of dismemberment if you exceed the threshold is calculated as follows:
(damage - threshold)/threshold
So, if you did 1 damage over the threshold, you would have a very low chance of dismembering, whereas if you dealt more than double the threshold damage, you would be guaranteed to dismember the target.

Keep in mind that even though I've put a lot of thought and effort into these formulas they can be changed as needed. The effects of dismemberment should be relatively simple to calculate, so I'll leave that up to you guys.

**Describe alternatives you've considered**  
HP bars for individual body parts, which would require the tracking of 6 HP bars per zombie instead of one, thereby unduly decreasing performance.

**Additional context**  
I put all of the possible values for melee accuracy into my formula to get some example probability tables.
![Imgur](https://i.imgur.com/0hJPFq3.png)

**Comment by esotericist** [comment]
Still musing on the rest of this, but I want to comment on this part:

> HP bars for individual body parts, which would require the tracking of 6 HP bars per zombie instead of one, thereby unduly decreasing performance.

Performance is actually not a substantial concern here to the best of my knowledge.

It's more about what actually benefits the model to track, and in particular, *if* that information is going to exist then it's a thing players would reasonably want to be informed of (due to the implied tactical considerations). This then becomes an inundation of data problem; presenting this stuff in a useful fashion to players can get tricky.

That said:

There's been discussion in the past about e.g. applying a status effect that implies impairing/removing a target's ability to move or attack under unspecified circumstances, so something like this has a possibility of making it into the game at some point. Which *I* think would be cool.

**Comment by Greevv** [comment]
Thanks! The only reason I mentioned performance was because *somebody* (you know who you are) claimed that it would cause an absurd amount of lag.

**Comment by MrHrulgin** [comment]
See the Monsters section of the [Frequently Made Suggestions](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions) in the Wiki. Limb tracking & damage is addressed there.

**Comment by Greevv** [comment]
While it is in the wiki, I feel like I've mostly addressed the problems laid out in the wiki. I made proper, functioning formulas for it, my idea doesn't utilize limb HP bars at all, etc.

**Comment by glimpsebeyond** [comment]
If we're going for dismemberment, which I think we should, it should be done with limb simulation. I posted a write-up on [reddit](https://www.reddit.com/r/cataclysmdda/comments/jaisp2/lets_discuss_limbs_limb_targeting_and/) with more detail.
