### ISSUE TITLE
Make a "core" health value that when drops to 0 kills you

### ISSUE THREAD

**Issue by lmaolollmao** [CleverRaven/Cataclysm-DDA#30341]
Killing NPC's is a pain, sometimes I can kill them with 2 bullets sometimes I need 20 because I keep shooting their already broken limbs which deals no damage to them.
Make a "core" health value which is damaged when your body parts get damaged, for example in fallout where even tho your enemies limbs are cripled you can still kill them by shooting their limbs, my suggestion is having different multipliers for different body parts, for example if you get shot for 60 damage to the left arm 75% of that damage would deal damage to the "core" health.
I think its still fine to keep the current health system of head/chest health reaches 0 you would die, but I want this to be added because you can have all your limbs broken, survive 30 shots to your arms and still be nowhere near death.

**Comment by darktoes** [comment]
This is a weird situation because you also have to avoid the situation where a bunch of very small hits to a non-vital body part kill the player/an NPC. Also, just outright blowing a person's arm off isn't going to outright kill them. Shock maybe, bleeding definitely. The way forward imo is probably something like expanding bleeding effects, so shooting/cutting a limb or two off causes them to bleed out in a handful of turns.

**Comment by codemime** [comment]
I'm strongly against any kind of "core" health, apart from the existing junk-food-eating one. General blood loss, on the other hand, looks like the most viable alternative (the way it's implemented in URW):

![](http://unrealworld.fi/images/screenshots/330/unreal-world-330-fighting-wolves.png)

**Comment by lmaolollmao** [comment]
Adding a blood loss and bleeding system would be a really cool idea I think that's a better solution than a core health value

**Comment by drayath** [comment]
Would not a simple solution be to redirect such damage to the torso.  E.g. a hit on the arm or leg reducing hp to below 0, directly does the overflow damage (ignoring armor) to the torso. Representing both follow though of the blow and general; trauma/bleeding damage. Also simple code change with no UI stuff needed.
