### ISSUE TITLE
Possibility for Recipe recovery off PCs/Laptops?

### ISSUE THREAD

**Issue by TechyBen** [CleverRaven/Cataclysm-DDA#30345]
**Is your feature request related to a problem? Please describe.**  
PCs and Laptops are mainly just parts for the game currently. Would some small uses be welcome? Mainly to counter the best recipes only being in labs. Could some computers or laptops be marked to contain recipes (possibly some random results)?

**Describe the solution you'd like**  
Some PCs would be deconstructed and drop HDDs, some would not as these would be "terminals". Some laptops could contain recipes if powered with batteries. Both HDDs and Laptops would have a high chance of being locked/encrypted if high tech recipes, and low chance of being locked for low tech recipes.

The laptop would require a "hacker USB" or possibly a "decryption USB" or "Data recovery USB", for unlocking and recovering data. To use the HDDs, the player would require a laptop with the usbs also. I assume the crafting recipe could have a time countdown of a day or more and be similar to the leather making/sauerkraut recipes that you drop and come back to. Laptop would have to consume batteries, or the crafting recipe would.

This would allow resources and time to be used to turn some special drops into extra recipes. Labs would still be quicker and have more. But some other places (hidden bunkers, military outposts) could drop laptops and HDDs but require much more to access than just reading the books. Even labs could put some of the recipes over I guess... depending on how recipie discovery would be balanced (a small tech tree limit would mean you need some access to electricity before discovering some tech if we hide it in HDDs instead of books for example).

**Describe alternatives you've considered**  
E-ink PC can contain recipies at the moment. There is nothing wrong with this. I was just wondering how to extend this idea. Perhaps plugging it in to PCs/terminals that are powered for a single use (per terminal) to "download data". Player would probably need a "hackers E-ink PC" by combining it with the hacking USB and high computers skill crafting.

Otherwise the option to "hack" any live terminal in game to find personal/additional content/lore/recipes would be an easy addition.

**Additional context**  
Simply some PCs/terminals would be marked as able to drop HDDs as loot. HDD + data recovery USB + laptop crafting item would drop a "data recovering laptop" and after 1 day it would turn into a "recovered data laptop". It would then work like the E-Ink PCs "decrypt" option. On activating it would drop an empty, encrypted, or recipe containing HDD. The Laptop would then access the HDD similar to how the E-ink pc accesses sd-cards.

I have not included a "hdd access caddy", but it could be added as a requirement (assuming SSDs, these do currently fit in some laptops, so some interprobility is possible, just not in every case).

**Comment by eilaattwood** [comment]
I've proposed capability of storing recipes from books into the e-ink tablets very long time ago, but recently i begin to dig into the code and now understand that storing and moving recipes require complete rewrite of external recipe code. Now that code just check that corresponding book is within reach, isn't it?
