### ISSUE TITLE
Unable to open keyboard to perform actions

### ISSUE THREAD

**Issue by SortaKindaSnek** [CleverRaven/Cataclysm-DDA#30350]
**Describe the bug**  
Hitting the "back" button will not open the virtual keyboard

**To Reproduce**  
Install CleverRaven's version of CDDA on the google play store, hit the back button, and be unable to see the keyboard to perform actions

**Expected behavior**  
I expect the phones keyboard to show up like other versions, so I may perform advanced actions.

**Screenshots**  
N/A

**Versions and configuration(please complete the following information):**
 - OS: Samsung Galaxy J3 Duo
 - Game Version: Whatever the Google play version is
 - Graphics version: Tiles
 - Mods loaded: Any and all, mods loaded do not change the result

**Additional context**  
N/A

**Comment by ZhilkinSerg** [comment]
Duplicate of #33781
