### ISSUE TITLE
Zinc is dangerous. Stop storing it in plastic bags.

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#30352]
![image](https://user-images.githubusercontent.com/28910998/57489383-ac0ace80-726a-11e9-8b9b-af95d11ba141.png)

`Zinc powder must be handled and stored properly and carefully because it is a flammable and hazardous substance. It should be stored in a tightly sealed container at all times and kept away from substances with which it is incompatible. These substances are water, sulfur, strong acids and bases, heat, chlorinated solvents, amines and cadmium. It is also air sensitive, but stable in cool dry places.`

**Comment by MrHrulgin** [comment]
At the moment the other containers available are plastic, glass and canvas (probably not this one). Do you have experience with storing zinc powder? The hazardous material guidelines just say securely sealed, but if you have personal experience with how it's actually stored that'd be great.

**Comment by tenmillimaster** [comment]
A plastic bag is fairly capable of holding zinc powder, though I think Fisher and Sigma Aldrich sell the stuff in plastic bottles.

**Comment by Phenomphear** [comment]
No, I don't have personal experience. I wish I did. I was just looking up stuff about it. @MrHrulgin

**Comment by EldritchSigma** [comment]
Zinc Powder can be stored in plastic bags, but it really shouldnt be. Like most powders they should be stored in those small plastic bottles you get from Sigma Aldrich. Reason for this is basicly that a plastic bottle has a much harder time getting damaged than a plastic bag. Heck there were some substances a while back that should decompose slowly when not stored in a Stockline or Glovebox filled with Nitrogen or Argon. Think both objects (Fume Hood with Stockline and Glovebox) are in the game so one could add more "real" chemistry to the game, like precursors synthesis (for instance metalalcoxides) for various nanoscaled compounds. Perfectly doable, aslong someone finds a operational Stockline or Glovebox in a lab and has some know how, e.g. from various, lenghthy books or research papers.
