### ISSUE TITLE
Unable to play world

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#30357]
![image](https://user-images.githubusercontent.com/44106380/57497612-f80d5000-730a-11e9-984c-1992e83331bd.png)

I've returned to playing cdda.
I updated the game and adjust some things, but when i try to create a new character this error happens.

**Comment by Zireael07** [comment]
The issue template is there for a reason. Moreover, if it's a preexisting world, you should zip it up and attach to the issue.

**Comment by BBlankie** [comment]
This is a new world with the same modlist from my old world, I removed cata++ and other mods i deem not working but i still can’t play my new world.

**Comment by BBlankie** [comment]
![image](https://user-images.githubusercontent.com/44106380/57818746-ed920100-77b7-11e9-9654-08eb5351d14c.png)

Found it on debug.log, This is the error i always get before getting a seg fault and crashing.

**Comment by kevingranade** [comment]
You have a mod that is blacklisting the hk_ucp, probably generic guns.  That item was removed from the game and the mod needs to be updated.
