### ISSUE TITLE
Arithmetic Error

### ISSUE THREAD

**Issue by JennyBundrick** [CleverRaven/Cataclysm-DDA#30369]
**Describe the bug**  
Game crashes seemingly for no reason

**To Reproduce**  
Open my current save, crashes

**Log**
CRASH LOG FILE: config/crash.log
VERSION: 0.D-2051-gc8883c7
TYPE: Signal
MESSAGE: SIGFPE: Arithmetical error
STACK TRACE:
    @0x5601F5[cataclysm-tiles.exe+0x1601F5]
    @0x560CC2[cataclysm-tiles.exe+0x160CC2]
    SMPEG_error+0x4B0B1@0xE4286D[cataclysm-tiles.exe+0xA4286D]
    _C_specific_handler+0x98@0x7FFC90698068[msvcrt.dll+0x28068]
    _chkstk+0x11F@0x7FFC915246AF[ntdll.dll+0xA46AF]
    RtlWalkFrameChain+0x14BF@0x7FFC91484BEF[ntdll.dll+0x4BEF]
    KiUserExceptionDispatcher+0x2E@0x7FFC9152341E[ntdll.dll+0xA341E]
    @0x60CC4F[cataclysm-tiles.exe+0x20CC4F]
    @0x61754F[cataclysm-tiles.exe+0x21754F]
    @0x61AEB7[cataclysm-tiles.exe+0x21AEB7]
    @0x687352[cataclysm-tiles.exe+0x287352]
    IMG_LoadWEBP_RW+0x4F87A9@0x142CE09[cataclysm-tiles.exe+0x102CE09]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFC90787974[KERNEL32.DLL+0x17974]
    RtlUserThreadStart+0x21@0x7FFC914EA271[ntdll.dll+0x6A271]

**Versions and configuration(please complete the following information):**
 - OS: [Windows 10]
 - Game Version: [0.D-2051-gc8883c7]
 - Graphics version: [Tiles]

**Comment by Zireael07** [comment]
Attach the save, otherwise we can't do anything about this.

**Comment by JennyBundrick** [comment]
oh shoot maybe i should actually pay attention to my emails.... how do i do that?

**Comment by JennyBundrick** [comment]
also that seems completely reasonable i dont know why i even created an issue that cant be solved in any tangible way

**Comment by anothersimulacrum** [comment]
You need to zip your save and then you can attach it to a post

**Comment by kevingranade** [comment]
Unreproduceable crash with no leads.
