### ISSUE TITLE
Skeletal juggernaut has HARD_TO_SHOOT flag despite being many times larger than skeletons.

### ISSUE THREAD

**Issue by JonahDes** [CleverRaven/Cataclysm-DDA#30374]
A skeleton juggernaut as described ingame is:

"This hideous golem of plated bones and misshapen flesh drags its heavy, pointed limbs behind it like an unwanted burden. Formerly soft and vulnerable, bones grew around its form to protect it - only, they kept growing. And growing. And growing."

Whilst a skeleton is understandably harder to hit for the spacing between bones, the juggernauts appearance, stats and move speed seem to imply a lumbering mass which is both easier to lead a shot on and easier to hit than their smaller counterparts.

Bones are considered to be 'plates' and presumably fan out a large area. Flesh further fills gaps making the 'golem' seem more meaty. Reasoning for not removing HARD_TO_SHOOT is that they're supposed to be tough, but I feel that toughness is better represented by their armour stats than being an inherently dodgy monster.

In practice, it would take an average of 5-6~ Shotgun blasts or more to skill the skeleton assuming complete accuracy, at present it takes much more due to misses.

Alternatives: You could also make a new flag for "PLATED" which essentially causes ranged shots to potentially ricochet off the monster being hit and end up flying in random directions (can include the player). The easiest thing to do is to remove the HARD_TO_SHOOT flag itself, and either leave it as is or slightly buff its already high armour.

**Comment by kevingranade** [comment]
HARD_TO_SHOOT means "the vitals of this monster are harder to hit than usual, effectively reducing the size of the monster by one level.  I.e. they are "spindly" and "compact".  That's independent of size, if they start huge, they drop to large, if they start large, they drop to medium, etc.
This is working as intended.
