### ISSUE TITLE
Faux fur trenchcoat Deadpeople tile inconsistency

### ISSUE THREAD

**Issue by RarkGrames** [CleverRaven/Cataclysm-DDA#30389]
**Describe the bug**  
Faux fur trenchcoat and sleeveless faux fur trenchcoat tiles are inconsistent to the rest

**Expected behavior**  
Faux fur trenchcoat and sleeveless faux fur trenchcoat should use the duster counterpart tiles, just like the rest of the trenchcoats.

**Screenshots**  
![image](https://user-images.githubusercontent.com/50421549/57554332-743a7e80-7371-11e9-93e7-94ce21cf94d3.png)

**Versions and configuration(please complete the following information):**
 - OS: Win x64
 - Game Version: 0.D-2773-g2d05871 (tiles)
 - Graphics version: Tiles
 - Mods loaded: Default

**Comment by Night-Pryanik** [comment]
Pinging @SomeDeadGuy.

**Comment by SomeDeadGuy** [comment]
Please redirect this issue to official DeadPeople tileset github!
https://github.com/SomeDeadGuy/Cata-MSX-DeadPeopleTileset/issues
Also i need to separate Duster graphics from Trenchcoat graphics.

**Comment by RarkGrames** [comment]
@SomeDeadGuy Thanks, I've opened an issue over there.
