### ISSUE TITLE
Fail to access ice labs

### ISSUE THREAD

**Issue by IvanShestakov** [CleverRaven/Cataclysm-DDA#30394]
**Describe the bug**  
Whenever I get close to an ice lab an exception pops up  with this text:
 DEBUG    : Error: tried to generate map for omtype ice_lab, "science lab" (id_mapgen ice_lab)
 
 FUNCTION : void map::draw_map(const oter_id&, const oter_id&, const oter_id&, const oter_id&, const oter_id&, const oter_id&, const oter_id&, const oter_id&, const oter_id&, const oter_id&, const oter_id&, const time_point&, float, int, const regional_settings*)
 FILE     : src/mapgen.cpp
 LINE     : 2735

**To Reproduce**  
1. Navigate near an ice lab. Get the exception. 
2. Approach the location of the lab and find out the whole thing is only floor tiles.
3. I tried mining a downstairs to access, but whenever I peek, the screen goes black and same exception is shown again. 
4. Driven to another lab, regular one and explored it successfully.
5. Driven to another one - which happened to be ice lab, got the exceptions on approach, and found floor tile and no lab - 3 security guard zombies spawned out of thin air. 
**Expected behavior**  
I know that this world "had" correct functioning ice labs (as this character started in one - and explored it all right). Then I've pulled fresh code and compiled to find this error.

**Screenshots**  
![Screenshot_2019-05-11_01-31-25](https://user-images.githubusercontent.com/9976709/57559860-88d84000-738c-11e9-8098-04c3254c518f.png)

**Versions and configuration:**
 - OS: Linux Mint 18.3
 - Game Version: 0.D-2821-gfb70e6b-dirty
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs, More Survival Tools, Medieval and Historic Content, Folding parts pack, Vehicle Additions pack, Boats.

**Comment by JeanLucVanDamme** [comment]
I'm also getting this exact same bug, same error message, and same inability to mine to lab z-levels below.

OS: Windows 10 Pro
Game Version: 0.D-2761-gf00bfc8 (winx64 tiles)
Graphics version: Tiles

Mods loaded:
(**tl;dr:** the mods OP and I share are Disable NPC Needs, More Survival Tools, and Folding Parts pack. Then I have a bunch more.) 

DDA, Disable NPC Needs, Aftershock, Deadleaves' Fictional Guns, Makeshift Items Mod, Mythological Replicas, Modular Turrets, Salvaged Robots, Alternative Map Key, Hydroponics, Mutant NPCs, More Locations, Fuji's More Buildings, Vehicle Additions Pack, Tanks and Other Vehicles, Manual Bionic Installation, Prevent Zombie Revivification, Safe Autodoc, More Survival Tools, Folding Parts pack, Classes and Scenarios Mod.

**Comment by AMurkin** [comment]
Can confirm on 0.D-2807-g5a355eec34.
Mods:
```
[
  "dda",
  "alt_map_key"
]
```

Debug message from the code changed in #30214 by @mlangsdorf.

```
	debug_write_backtrace(std::ostream&)
	.../src/debug.cpp:605
	DebugLog(DebugLevel, DebugClass)
	.../src/debug.cpp:768
	realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
	.../src/debug.cpp:98
	void realDebugmsg<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, char const*>(char const*, char const*, char const*, char const*, char const*&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&&, char const*&&)
	.../src/debug.h:78
	map::draw_map(int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, int_id<oter_t> const&, time_point const&, float, int, regional_settings const*)
	.../src/mapgen.cpp:2731 (discriminator 6)
	map::generate(int, int, int, time_point const&)
	.../src/int_id.h:97
	map::generate(int, int, int, time_point const&)
	.../src/mapgen.cpp:203
	map::loadn(int, int, int, bool)
	.../src/map.cpp:6676 (discriminator 3)
	map::loadn(int, int, bool)
	.../src/map.cpp:6601 (discriminator 2)
	map::load(int, int, int, bool)
	.../src/map.cpp:6381 (discriminator 2)
	game::place_player_overmap(tripoint const&)
	.../src/game.cpp:9882
	debug_menu::teleport_long()
	.../src/debug_menu.cpp:267
	debug_menu::debug()
	.../src/debug_menu.cpp:904
	game::handle_action()
	.../src/handle_action.cpp:2008
	game::do_turn()
	.../src/game.cpp:1432
	main
	.../src/main.cpp:689
	__libc_start_main
	/build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344
	_start
	??:?
Backtrace emission took 1 seconds.
src/mapgen.cpp:2732 [void map::draw_map(const oter_id&, const oter_id&, const oter_id&, const oter_id&, const oter_id&, const oter_id&, const oter_id&, const oter_id&, const oter_id&, const oter_id&, const oter_id&, const time_point&, float, int, const regional_settings*)] Error: tried to generate map for omtype ice_lab, "science lab" (id_mapgen ice_lab)
```

**Comment by ralreegorganon** [comment]
I'm pretty sure the issue here is that [this check](https://github.com/CleverRaven/Cataclysm-DDA/pull/30214/files#diff-f4dada645aa2c6343e16a20b047c07c5R2722) needs to use `is_ot_subtype` instead of `is_ot_type`, because `is_ot_type` only looks for suffixes, but `ice_lab` and it's kin are prefixes, which `is_ot_subtype` does handle.
