### ISSUE TITLE
Should autodoc surgery on an NPC require anesthetic every time?

### ISSUE THREAD

**Issue by GearheadLydia** [CleverRaven/Cataclysm-DDA#30400]
For the prototype cyborgs, or even just installing bionics on another NPC, it seems like the NPC is out cold for some time due to the anesthetic. In real-world surgery, it's not unheard of to do multiple procedures during one anesthetic session. Also, repeatedly dosing the NPC with a full dose of anesthetic sounds like it'd be unhealthy and dangerous.

Maybe the procedure should require an anesthetic as a tool if the autodoc detects that the NPC is already unconscious, but the anesthetic should not be consumed unless the NPC would otherwise have woken up during the procedure.

My strong suspicion, though, is that it is the way it is for balance reasons, which I get and respect.

**Comment by mlangsdorf** [comment]
A dose of sedative is sufficient to knock the subject out for a single operation, whether that operation lasts 15 minutes or 15 hours.  That's not realistic, but that's the way it is.

Working as designed so I'm closing the issue for now.  We can re-open it when NPCs have varied body weights , i-am-erk has made the pharmaceutical model much more accurate, and anesthesia has more finely grained doses.
