### ISSUE TITLE
Lightstrip recipe is unavailable

### ISSUE THREAD

**Issue by RarkGrames** [CleverRaven/Cataclysm-DDA#30403]
**Describe the bug**  
Lightstrip recipe is unavailable if crafting menu.

**To Reproduce**  
1. Unlock all recipes in debug menu.
2. Search for "lightstrip".
3. No result.

**Versions and configuration(please complete the following information):**
 - OS: Win x64
 - Game Version: 0.D-2791-gc495419 (tiles)
 - Graphics version: Tiles
 - Mods loaded: Default

**Additional context**  
The recipe can't be found in the .json files either.

https://cdda-trunk.chezzo.com/lightstrip_inactive/craft
This page points to some advanced recipe with a lab journal and plutonium cells.

**Comment by Zireael07** [comment]
I don't know when the site was last updated, though - and the way we serve the experimentals has changed recently. It's highly likely that the info there is outdated.

**Comment by RarkGrames** [comment]
@Zireael07 Sometimes I see recent changes on it, so it must be somewhat updated. Not sure about the frequency though.

**Comment by Night-Pryanik** [comment]
Recipes of lightstrip and inactive lightstrip were removed in https://github.com/CleverRaven/Cataclysm-DDA/pull/29651/files#diff-22c35476e387c0c147802b32a0ec33ec.
