### ISSUE TITLE
Design oversight for rollers? (Steel drums)

### ISSUE THREAD

**Issue by Rosencratz** [CleverRaven/Cataclysm-DDA#30406]
Not sure if this classifies as a bug, but the way rollers currently work in CDDA is counterintuitive to how it should function as a ramming extension. Compared to other rams that require no frames attached, the rollers must have a frame, which means whenever it crashed into anything, the frames are more likely to collapse compared to the rollers. Slapping on armor helps prolong the time it takes before it breaks, but rollers really should be installed the same way as rams should be to bring it in line with other ramming equivalents.

**Comment by anothersimulacrum** [comment]
#24721 was supposed to stop that from happening, is that not working?

**Comment by Rosencratz** [comment]
> #24721 was supposed to stop that from happening, is that not working?

It still takes damage as far as I am aware. Build is 8909 when I last had rollers on.

**Comment by mlangsdorf** [comment]
Road rollers are supposed to crush and flatten things, not be invulnerable battering rams that allow you to wreck buildings without damaging your vehicle.  

The weight of 750 kg per nominally 1m wide drum means that if the drums are solid steel, they're only 0.1m^2 in cross-section, or .35m cross.

**Comment by kevingranade** [comment]
Closing, bad assumption about the purpose of rollers, it's not a ram.
