### ISSUE TITLE
Android crash when approaching bandit and zombies

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#30413]
**Describe the bug**  
The Android version of the game crashes when approaching a bandit and a horde of zombies in the attached save. The crash does not happen in the Windows version.

**To Reproduce**  
1. Load the save in the android version;
2. Drive the vehicle forward to crush the zombies;
3. The game consistently crashes after driving for a bit.

**Expected behavior**  
The game does not crash.

**Versions and configuration**
 - OS: Android
 - Game Version: 0.D-2786-gb574176
 - Graphics version: Tiles
 - Mods loaded: Makeshift Items Mod, Medieval and Historic Content, More Locations, Urban Development, Fuji's More Buildings, Bete National Guard Camp, Alternative Map Key, Crazy Cataclysm, Classes and Scenarios Mod, DIsable NPC Needs.

**Save**
[Petaluma android crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3169153/Petaluma.android.crash.zip)

I'm not sure if it's related to memory issues, but my device handled this amount of zombies just fine before, so I'm suspecting it's related to the bandit. I can't be sure though since I don't have debugging environment for android.

**Comment by neitsa** [comment]
Thank you for your bug report. 

* Do you have access to the `debug .log` / `crash.log` files from the game?
* Do you also have access to your tombstones (they should be in `/data/tombstones/`)?
    - If you didn't experience any other crash (from any app), the one for cataclysm should be the last tombstone.

The tombstone should give us a lot of information (they don't contain anything private, it's a glorified crashlog).

If you have access to any of those files, could you please upload them?

**Comment by Qrox** [comment]
I can't seem to find the tombstones anywhere, and the crash log is not generated. debug.log only seem to contain irrelevant information, but I still copied the log of the last run here in case it is helpful.

```text
-----------------------------------------
01:38:42.380 : Starting log.
01:38:42.380 INFO : Cataclysm DDA version 0.D-2786-gb574176
01:38:44.026 INFO : SDL version used during compile is 2.0.8
01:38:44.026 INFO : SDL version used during linking and in runtime is 2.0.8
01:38:44.058 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
01:38:44.117 WARNING : opendir [/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/mods/] failed with "No such file or directory".
01:38:49.152 ERROR : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/assign.h:46 [void report_strict_violation(JsonObject &, const std::string &, const std::string &)] line 12:21: assignment does not update value


    "type": "overmap_land_use_code",
    "id": "cropland",
    "land_use_code":
                    ^
                     1,
    "name": "Cropland",
    "detailed_definition": "Generally tilled land used to grow row crops.  Boundaries follow the shape of the fields and include associated buildings (e.g., barns).  This category also includes turf farms that gro
01:38:54.021 WARNING : opendir [/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/save/Petaluma/mods] failed with "No such file or directory".
```

**Comment by neitsa** [comment]
Thank you for your feedback! Too bad, I guess tombstones are only generated if the phone is in dev mode...

I don't think the error in the log is the source of the crash. I'll give your save file a try on a PC version and see if I can trigger something.

**Comment by Qrox** [comment]
Well, I just recalled something that might be of help: In some previous version, a lot of my new games crashed when there's starting NPC around. However they did not crash immediately, but crashed randomly after some time. I suspect this might be related since in this save there's also an NPC (the bandit) around.

**Comment by Zireael07** [comment]
I believe the official (CleverRaven) Android version is 0.D (Danny), not the experimentals? So it's highly likely the issue is already fixed?

**Comment by Qrox** [comment]
I was playing the experimental version, downloaded from http://dev.narc.ro/cataclysm/jenkins-latest/Android/Tiles/. Judging from the version number displayed in game (0.D-2786-gb574176), it is a commit from two days ago.

**Comment by Night-Pryanik** [comment]
@Qrox have you encountered any similar crashes throughout almost two years?

**Comment by Qrox** [comment]
I haven't played the Android version very frequently to say that the crash is gone, but I guess we can close this issue until anyone reproduces it.
