### ISSUE TITLE
"Auto-eat" zones: Snack while you study.

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#30415]
**Is your feature request related to a problem? Please describe.**  
Stopping what you're doing to eat or drink is mundane. It would be nice if while reading a book / practicing (https://github.com/CleverRaven/Cataclysm-DDA/issues/28283) / doing maintenance (https://github.com/CleverRaven/Cataclysm-DDA/issues/30414) / crafting, your character would automatically eat and drink food a bit.

**Describe the solution you'd like**  
The ability to designate "auto-eat" and "auto-drink" zones. Items stored in these zones will be eaten or drunk by the player if they are doing an ongoing action and within range. 

The trick would be when the player would know to eat. I'd suggest that the default behaviour be that the player eats up to 200 kcal of food each half an hour if they are peckish, 300 if hungry, 400 if famished or worse. Maybe later we could make an unbound options menu you could open to adjust the settings to your preference. Alternatively we could leverage whatever hungry/eat AI we give the NPC but I think that NPCs are going to have a different digestive tract so that might not work.

**Describe alternatives you've considered**  
Keeping the current system is fine, it works... but this is something that could be automated for smoother play.

**Additional context**  
See my notes on practice actions and maintenance actions for more things that could and should be a bit more automatic.

**Comment by Mecares** [comment]
I would like if we could use the favourite mechanic to mark food for auto consumption maybe only  while safe mode is active.

**Comment by Yunatan** [comment]
Looks like this resonates with [what Kevin said](https://github.com/CleverRaven/Cataclysm-DDA/issues/30354#issuecomment-491107542) about managing leisure\studying\maintenance activities

**Comment by JeanLucVanDamme** [comment]
Find myself doing all this stuff manually quite often - yeah, it's tediuous. I'm 100% behind all of these ideas.

**Comment by Mooses2k** [comment]
Obviously, it should eat the item most soon to spoil that is safe to eat (not uncooked or tainted meat).

**Comment by I-am-Erk** [comment]
Well, you shouldn't put tainted or uncooked stuff in your auto eat zone

**Comment by Mooses2k** [comment]
Maybe I misunderstand, but say I was in an RV and my minifridge was an autoeat zone. Sure, for mutagen crafting I could not store stuff there, but it would be a fairly shortlist of things we could blacklist: tainted* & *mutagen, *serum, anything <-negative 20 quench, maybe marloss?

You at least agree it should eat the soonest to spoil?

**Comment by I-am-Erk** [comment]
It should eat the soonest to spoil as default behaviour, yes.

I don't think specific foods should be blacklisted, because we have all kinds of traits that make certain foods edible. If, for example, we blacklist marloss berries then we need to make exceptions for fungal characters. The easiest answer is "don't put it in your auto-eat zone if you don't want to automatically eat it". Just like you shouldn't leave hand grenades in your firewood pile.

**Comment by nexusmrsep** [comment]
This would be also handy in long-lasting crafting jobs.

**Comment by I-am-Erk** [comment]
Yeah. I'd like to be able to set a character to craft chain armour sheets for a week, or hand sew their custom clothes for a few days, and have them eat and sleep automatically the whole time
