### ISSUE TITLE
"Take a break" action for automatic maintenance and mundane stuff

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#30414]
**Is your feature request related to a problem? Please describe.**  
There are a lot of suggestions and even demand for realism elements that are cool on paper, but too damn tedious to enact. Some of these are already a problem in game. This doesn't mean they don't add cool gameplay at all, in fact often they do, but the tedium of playing them is prohibitive - or even if they aren't that tedious, they also aren't really that fun.

Examples that exist already:
- Washing all your filthy clothes
- Maintaining your equipment once your skills are high
- mopping spills on the ground
- trimming your hair
- play with your pets
- small talk with your followers

Examples that come up frequently as features that could be implemented:
- Keeping your non-filthy clothes clean to keep them from getting stinky
- Washing yourself
- Sharpening your bladed tools
- Washing the dishes
- Going to the bathroom

**Describe the solution you'd like**  
A "downtime" action, called something like "take a break", that automates small flavourful activities.
This is not meant to be a total automation action for things like skill improvement (see practice actions), farming or sorting (see zone activities) or anything like that; these are specifically for things where the in-game effect is kind of a flavour piece. I think filthy gear and small talk are two very cogent examples.

***How I see it working***
You use zone designation for downtime stuff, probably just a zone called "maintenance supplies". There might be a few other such zones, like "clothes to wash", "gear to mend" and things. Obviously these could be set up right on top of your sort zones if you just want your player to mend everything. 
When you perform the "Take a Break" action, you get a menu listing all the possible downtime actions based on what items you have in nearby maintenance supply zones. If you don't have soap. "do the laundry" would be browned out like a recipe you don't have components for. 

You can manually strikeout downtime actions you don't want your player to do, if you want. You also arrange the order they are done, so for example you can make sure your character doesn't start playing with her pets until she's done the laundry. You can set a time cap to keep the player from doing activity x for more than y minutes. There would also be a toggle to mend/maintain worn gear, carried gear, and gear in zones, so that you could tell your character to ignore zones and just take care of his own equipment right now. If that has all been set already, when you open the Take a Break menu, you can just double tap the key to get into it to continue with downtime using whatever settings you had before.

Actions that use skills, like maintaining gear, would let you choose a 'minimum success rate', so you wouldn't automatically try to maintain your gear if the success rate was lower than X%.

On a first pass I'd see this just using those maintenance actions I already listed. Later, once set up, we could start integrating the ability to take a damn shower, or have your clothes get slowly dirtier, because the player investment in keeping it all sorted out would be much lower.

**Describe alternatives you've considered**  
Keeping it as is, but I see this as a constant struggle between implementing cool ideas that expand gameplay but add chores (filthy clothes, great example). Individually the effort of washing your clothes is trivial, but collectively all these different activities do really pile up and become tedium.

**Comment by Greevv** [comment]
A "repair all" option for vehicles would be nice too.

**Comment by I-am-Erk** [comment]
I think this has been superceded by some different ways of doing this, ie. rolling passive activities into ongoing long term actions.

**Comment by Zireael07** [comment]
Boiling water still has the issue though?

**Comment by I-am-Erk** [comment]
Not sure what boiling water has to do with this one?

**Comment by Zireael07** [comment]
Tedious and long task that has to be repeated - and the character can't do anything else in the middle.

**Comment by I-am-Erk** [comment]
That's not what this issue is about. There's a different issue for that stuff

**Comment by Zireael07** [comment]
Ah, forgive my mistakes then
