### ISSUE TITLE
Build #8949 broke command: yell (C) to make all NPCs follow 

### ISSUE THREAD

**Issue by Daxtgnomoria** [CleverRaven/Cataclysm-DDA#30457]
**Describe the bug**  
Before Build #8949 you could make all NPCs follow you at the same time, using the command yell (c) and selecting the option to tell everyone to follow at the same time. After the refine of the menu, this command is acknowledged by all NPCs, but they just stand still and remain in Guard position. Using the same menu (yell) to ask them individually to follow works fine, but not for everyone at the same time. I tested it with 3 NPCs.

**To Reproduce**  
1. Spawn more than one NPC.
2. Recruit them.
3. Use command "yell" (C) and select option (f) "Tell someone to follow" and in the next menu select option "Everyone".  
4. Walk away.

**Expected behavior**  
All NPCs should leave their guard position and start following the player.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2863-gca633a0
 - Graphics version: Tiles - MXotto+
 - Mods loaded: dda, disable NPC needs 

**Additional context**  
Link to TEST savegame with 3 NPCs  already recruited and in guard position, for tests.
[http://s000.tinyupload.com/?file_id=31458396185137637669](http://s000.tinyupload.com/?file_id=31458396185137637669)

**Comment by esotericist** [comment]
Damn, I swear I tested the hell out of that. Let me look into it

**Comment by esotericist** [comment]
... Found the problem, and I'm stupid. I'll have a PR for this shortly.
