### ISSUE TITLE
Streamline wound care?

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#30454]
**Is your feature request related to a problem? Please describe.**  
If I've taken a bunch of small wounds across my body, it's frustrating to need to activate a bandage, select a body part, activate a bandage, select the next body part that would benefit, repeat that until fully bandaged, and then repeat the whole process with a disinfectant.

**Describe the solution you'd like**  
I would like a single option in the "select a body part for treatment" screen which lets me apply bandages or disinfectant to all body parts that would benefit from it.

**Describe alternatives you've considered**  
An alternative would be the same sort of change that was recently added to the [E]at screen, where the screen re-opens automatically. If I have one wounded body part, it's likely I've got multiple.

**Comment by capSAR273** [comment]
Re-opening the screen to apply bandages would be a nice change that could streamline wound care. However, wouldn't we also need to be able to select which bandages/medications to use on each part? Maybe a screen similar to [E]at, but instead have it be all about wounds.

Panel on the left lets you pick the healing related item to use, right panel lets you pick which body part to use it on?

**Comment by I-am-Erk** [comment]
Having the window not close would be the ideal solution, it adds a single keypress if you only have a single thing to fix but saves dozens if you're really hurt, which is more often

**Comment by MrHrulgin** [comment]
Having played around a bit more, the expanded consumption functionality plus the auto-reopen does mostly cover this. If you use the "Consume Item Menu" command as opposed to the standard "Eat" command, you can choose medication as one of your categories to use. Within that, you can repeatedly use bandages, and while you do have to hit Enter each time to reselect a bandage before saying where to apply it, it's much better than the default "Eat".

**Comment by kevingranade** [comment]
Thanks for the reminder.
