### ISSUE TITLE
Map search hotkeys incorrect

### ISSUE THREAD

**Issue by Kenshkrix** [CleverRaven/Cataclysm-DDA#30462]
The map search UI says:
'<' '>' Cycle targets.

The hotkeys '<' and '>' don't do anything, but the hotkeys 'Shift+Tab' and 'Tab' cycle targets instead.

To reproduce this, press 'm' to go to the map, and '/' to search for something common, like a 'field' or 'forest', then attempt to cycle targets using the '<' and '>' keys.

This was using 0.D-2863-gca633a0 which I downloaded several minutes ago.

Solution: Either make the UI mention Shift+Tab and Tab, or make the < > keys actually cycle targets.

**Comment by esotericist** [comment]
That screen actually accepts left and right arrows, and I think that's actually what's being signaled here, not the literal `<` and `>` keys. probably changing that to `<-` and `->` would clarify it.

**Comment by Weyrling** [comment]
That makes more sense.
I don't have any particular preferences beyond removing the ambiguity, which should be simple enough regardless of which solution is decided upon.
