### ISSUE TITLE
Enable two-finger swipe in menus to be used as pageup/down

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#30468]
**Is your feature request related to a problem? Please describe.**  
In many menus (such as item description) the text needs to be scrolled by using pageup/down keys. However on Android it's very tedious to press the keys from the shortcut menu. Moreover, when you're tapping too fast it's very easy to trigger the removal of the shortcut, and it's then impossible to add it back from the virtual keyboard, which does not contain any special keys normally present on a real keyboard (this actually can be a separate issue).

**Describe the solution you'd like**  
The two-finger swipe gesture is currently not used outside the default mode. It would be nice to utilize it to be used as pageup/down to speed up scrolling of these screens. In addition it's possible to also add functions to swiping left/right, such as tab/backtab keys.

**Describe alternatives you've considered**  
Perhaps the gestures should really have their own virtual key code, and we can then customize the gestures in the keybindings menu like any other keys.

**Comment by Zireael07** [comment]
@Leland: I believe yes - a recent issue has demonstrated NPC dialogue screen doesn't fit on screen and that the Android port at least lacks any way to scroll up or down

**Comment by LeahLuong** [comment]
In #54756, PageUp & PageDown functionality is respected; there, it's about needing more & functional scrolling keybindings. I know that 2-finger swipes work in the main game screen & mobile users have customizable hotbar settings for size & transparency if the buttons are too small @ 1st. Personally, I don't really use 2-finger swipes & wouldn't mind seeing this thread closed but I can't speak for every1.
