### ISSUE TITLE
Errors/crash while attempting to craft starch from cattail rhizomes

### ISSUE THREAD

**Issue by esotericist** [CleverRaven/Cataclysm-DDA#30473]
# Describe the bug

While attempting to craft a batch of 5 starch from cattail rhizomes after accidentally auto-sorting the in-progress craft to a loot zone, a series of errors occurred.

Further, when attempting to try the craft again (using debug-spawned replacement rhizomes) the game outright crashed.

# Steps To Reproduce

I can't reproduce the problem directly myself even with the save from before the issue, but this is the order of events as i experienced it:

1. started starch crafting task too late in the day to complete.
2. went downstairs to sleep when it got too dark to keep going.
3. came back upstairs and realize a few items got left on the floor, hit `O` to auto-sort loot.
4. realize that the in-progress craft got relocated, fetch it, return it to counter
5. attempt to resume craft
6. ???
7. anti-profit

# Expected behavior

Ideally, crafting tasks should complete without either errors nor crashes.

# Versions and configuration
- OS: MacOs [64-bit] 10.14.1
- Game Version: 0.D-2890-g979f45f057
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Hydroponics [hydroponics],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Bionic Slots [cbm_slots]
]

# Additional context

debug.log and crash.log:
https://gist.github.com/esotericist/cc9ffa0b2b29590a87c5396d80746b1b

Save file:
[Roosevelt Beach.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3172135/Roosevelt.Beach.zip)

As of this save file, it is night time, i'm at my bed, the in-progress starch is on the counter upstairs.

Again, I don't know if the save file will be terribly useful, seeing as how it's before the problem occurred, and it doesn't appear to be readily reproducible.

**Comment by spookymotion** [comment]
I have this happen to me pretty regularly. For me the specific details are:
1) something in hands
2) pick up 0% progress item
3) activate item
4) cdda prompts "what do you want to do with the thing in your hands"
5) select drop
6) cdda crashes

Will confirm if this is 100% reproducible.

**Comment by wapcaplet** [comment]
Could not reproduce in 0.E-9702-gdc4167363d.
