### ISSUE TITLE
Base Camp Kitchen Missions do not allow Frozen ingredients to be used for some recipes

### ISSUE THREAD

**Issue by chronicpayne** [CleverRaven/Cataclysm-DDA#30478]
# Bug

Base Camp Kitchen Missions do not allow Frozen ingredients to be used for most recipes.

# Steps To Reproduce

1. Set frozen food (e.g. chunk of meat (frozen)) on the "Basecamp: Food" tiles so they can be accessed by NPCs.
2. Open the Base Camp Menu, Select a Kitchen Expansion, and attempt to have NPCs work with the frozen ingredients.
3. Most recipes will be grey/invalid, as they seem unable to use the frozen versions of the ingredient.

# Expected behavior

NPCs should be allowed to use frozen ingredients in the Base Camp's Kitchen Expansion via cooking missions.

My testing has shown the following recipes are impacted:

Cook: Cornmeal
Cook: Egg, Boiled
Cook: Fish, Cooked
Cook: Fish, Smoked
Cook: Lard
Cook: Meat, Aspic
Cook: Meat Jerky
Cook: Meat Pie
Cook: Meat, Cooked
Cook: Meat, Smoked
Cook: Mushroom, Cooked
Cook: Mushroom, Dried
Cook: Sausage
Cook: Sausage, Wasteland
Cook: Veggy Aspic
Cook: Veggy Pie
Cook: Veggy, Pickled

The following recipes are not impacted, or seem to work with (some) frozen ingredients:

Cook: Hardtack (frozen flour works OK, but frozen salt does NOT, so it technically cant be made)
Cook: Bread
Cook: Flatbread
Cook: Meat, Canned

(Unlisted/missing recipes were ones I was unable to test at the time.)

# Screenshots

Here you can see a stack of frozen chunks of meat placed on the Basecamp: Food tile for usage
![1](https://user-images.githubusercontent.com/39817146/57628097-1dd66700-754e-11e9-9db6-312082e5a5fe.jpg)

Here you can see the Cook: Meat, Canned is able to use the ~1600 peices of meat as expected 
![2](https://user-images.githubusercontent.com/39817146/57628159-3e9ebc80-754e-11e9-9433-2523d0d39161.jpg)

Here you can see both the Cook: Meat, Cooked + Cook: Meat, Smoked are unable to pull from this same pile of (frozen) chunks of meat
![3](https://user-images.githubusercontent.com/39817146/57628168-42324380-754e-11e9-89c4-2ed5a7b7ee4a.jpg)
![4](https://user-images.githubusercontent.com/39817146/57628171-44949d80-754e-11e9-8b35-17f687b22e25.jpg)

# Versions and configuration
- OS: Windows [64-bit]
- Game Version: 0.D-2863-gca633a0
- Graphics Version: Tiles
- Mods loaded: 
    Dark Days Ahead [dda],
    Urban Development [Urban_Development],
    More Locations [more_locations],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Filthy Clothing [filthy_morale],
    StatsThroughSkills [StatsThroughSkills],
    Classes and Scenarios Mod [more_classes_scenarios],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Extended Realistic Guns [realguns],
    No Fictional Guns [no_rivtech_guns],
    Mutant NPCs [mutant_npcs],
    Mining Mod [Mining_Mod],
    NPC traits [npc_traits],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    [DP_MOD] No Highlight [DP_No_Highlight]

(Am new to GitHub, so constructive criticism welcome for next time)

**Comment by mlangsdorf** [comment]
Camp crafting is about to get overhauled to fix issues like this.
