### ISSUE TITLE
Starting With A Full Container

### ISSUE THREAD

**Issue by TeslaDrive** [CleverRaven/Cataclysm-DDA#30475]
**Is your feature request related to a problem? Please describe.**  
When making a profession there doesn't seem to be an easy way to have the user start with a container full of a select liquid.

**Describe the solution you'd like**  
Ability to toggle if a liquid is "contained" or not in the json and an example of the ability in the json.

**Describe alternatives you've considered**  
Item IDs for liquid without default containers, complete removal of default containers, or new commands for implementing liquids in containers.

**Additional context**  
Right now the closest I could pull off was getting a hydration pack partially filled with clean water via the following code, any other methods resulted in a water bottle being put into the bag instead of the liquid itself.

{
 "item": "water_clean",
 "container-item": "camelbak"
}

**Comment by mlangsdorf** [comment]
```
{
    "item": "water_clean", "container-item": "camelbak", "charges": 16
}
```
doesn't work?

**Comment by TeslaDrive** [comment]
It does! Didn't think of using charges
