### ISSUE TITLE
Replica Wakizashi and Kris are both made out of the wrong material.

### ISSUE THREAD

**Issue by Sorgklaan** [CleverRaven/Cataclysm-DDA#30497]
The Wakizashi_Fake and Kris_Fake are both made of steel. Every other weapon described as a " dull, cheap replica " is made of aluminum. So they should both be aluminum rather than steel.

**Comment by Night-Pryanik** [comment]
> Every other weapon described as a " dull, cheap replica " is made of aluminum.

No, it's not. Fake rapier is made of steel too. I'll fix that too though.
