### ISSUE TITLE
NO_NPC_FOOD mod is not working anymore

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#30501]
# Describe the bug

NPCs ask for food and drink even with "No NPC needs" mod enabled.

# Steps To Reproduce

1. Create new world with NO_NPC_FOOD mod enabled
2. Spawn NPC companion
3. Wait until NPC gets hungry/thirsty

# Expected behavior

NPCs should not mention their needs.

# Screenshots

None

# Versions and configuration

 - OS: Windows 7 and Windows 10
 - Game Version: 0.D-2912-g2ad83e9
 - Graphics version: Tiles
 - Mods loaded: 
[
  "dda",
  "no_npc_food",
  "filthy_morale",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "realguns",
  "More_Survival_Tools",
  "Medieval_Stuff",
  "makeshift",
  "modular_turrets",
  "Salvaged_Robots",
  "Mining_Mod",
  "mutant_npcs",
  "alt_map_key",
  "cityside",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "boats",
  "blazemod",
  "deoxymod",
  "Tanks",
  "DP_REMIX_INDICATORS",
  "jury_rigged_robots",
  "EngineeringEssentials",
  "StatsThroughSkills",
  "sleepdeprivation",
  "more_classes_scenarios",
  "manualbionicinstall"
]

# Additional context

None

**Comment by XhameX** [comment]
I had this problem on experimental about 1 week ago, but some how it fixed itself in one of the latest versions.

This was the starting NPC.
But on further inspection the NPC had the `Chemical Imbalance` trait,
check your NPC traits and se if He/She/They have this. I have no idea if this is similar or close to what i was experiencing in my game though.

**Comment by eilaattwood** [comment]
I actually have this issue on two separate worlds with two different characters. One's companion NPC has Chemical Imbalance, I believe. But the second surely doesn't.

**Comment by chriseich21** [comment]
Is it to do with the initial implementation of the behavior tree in #29151?

**Comment by chriseich21** [comment]
Was going to say it might be from initial behavior tree in #29151 but that is dated after. Is this still a problem in builds after that update, build 9000 roughly a few days ago?

**Comment by eilaattwood** [comment]
> 
> 
> Was going to say it might be from initial behavior tree in #29151 but that is dated after. Is this still a problem in builds after that update, build 9000 roughly a few days ago?

Yep, it's happening just now.

**Comment by Funguss** [comment]
When viewing the NPC via the debug menu you can see when they are spawned without needs as they lack the needs_* flags. Most NPCs generated through starting scenarios seem fine, NPCs generated any other way appear to have needs. I'm guessing it comes down to the way NPCs are built. I assume scenario NPCs are generated in a slightly different (now obsolete) way, as they also seem to have a weird ruleset that can only be fixed by copying from another NPC. This is especially true for forced starting NPC spawn.

**Comment by sdp0et** [comment]
It always seemed to me that the needs weren't disabled but rather that they were just immune to the effects of needs.  When monitoring NPCs with debug that their needs ticker still decremented over time but none ever died of thirst or hunger.  Is it that the needs tracking is supposed to be disabled or the effects of the needs are disabled?

**Comment by Foxtrot-Uniform42** [comment]
Starting npc still needs food (but not water, according to info through shift+s menu) although he doesn't complains about it
