### ISSUE TITLE
Farming vehicles are useless now.

### ISSUE THREAD

**Issue by Mythiran** [CleverRaven/Cataclysm-DDA#30507]
**Is your feature request related to a problem? Please describe.**  
Now that we have functioning zoning (an awesome feature), it takes much more effort to use a 'farming vehicle' (seed planter, etc) than it does to just zone up, till and plant using Y and O.

**Describe the solution you'd like**  
Farming vehicles need to have SOME utility (since automation is probably not coming any time soon.). Perhaps a realistic solution would be for zone tilling/planting to stack unhappiness until you 'no longer feel like working'. In other words, zoning would be useful for small plots, but impractical for larger farms when you need to use vehicles. 

**Describe alternatives you've considered**  
1. Farming vehicles provide a growing bonus. I like this a lot but it's not very realistic.
2. Farming vehicles get zoning/automation implementation. (probably a ridiculous amount of work needed and unlikely to happen).
3. Automated farming from zoning removed (not something anyone wants... and probably a bad solution.)
4. Remove farming vehicle parts from the game, or just accept that they are nothing but scrap.

**Overall, the main point is that automated zone farming needs a debuff OR vehicle farming needs a buff, otherwise farming vehicles are USELESS**

**Comment by GrandpuhTy** [comment]
I have a feeling that tasks like this will eventually start burning extra calories from the survivors stores in the future. So farming vehicles will still have a use since they can effortlessly till a ton of land instead of doing it by hand which would be very energy intensive.

Ideally you should get more energy out of your harvest than you put into it if all goes well, but it's the huge upfront cost of breaking your back breaking dirt.

**Comment by faefux** [comment]
I'm not against any of your proposed solutions but that said, i'm personally hesitant to the idea that everything needs a use. From a flavour point a lone it's good that we can go into a barn and find a piece of farming equipment, it is even better to discover that it works mechanically.  This is cool regardless of if it's not the optimal way of doing things, or as you put it, 'useless'.

**Comment by eilaattwood** [comment]
> 
> 
> I'm not against any of your proposed solutions but that said, i'm personally hesitant to the idea that everything needs a use. From a flavour point a lone it's good that we can go into a barn and find a piece of farming equipment, it is even better to discover that it works mechanically. This is cool regardless of if it's not the optimal way of doing things, or as you put it, 'useless'.

Well, having working farming equipment in the game is, of course, really cool and shouldn't be removed just because it`s useless for now. But speaking about realism, in real life that equipment DOES benefit users a lot. So why it should be different in the game that pretend to be highly realictic?

**Comment by davidpwbrown** [comment]
Once calorie usage is in the game, then farming vehicles will have more appeal, as grandpuhty said.
other than that, an auto-drive functionality would bring it on par with the ease-of-use of the zoning functions.
That has been discussed aswell.
I don't think adding an arbitrary morale penalty to planting manually is the way, but there will certainly be work in this area in future.

**Comment by I-am-Erk** [comment]
The easiest way to do this would just be to allow you to do zone farming from the seat of a farming vehicle and getting a bunch of buffs for it without actually simulating the vehicle. That is pretty messy though.

Eventually we need to make automated driving, and when we do, you will likely be able to zone farm from a tractor. Until then, the BMR changes will add incentive to do it the non automated way.
