### ISSUE TITLE
Design Document and Factions.

### ISSUE THREAD

**Issue by faefux** [CleverRaven/Cataclysm-DDA#30512]
Hi, I've currently been writing some NPCs and missions in my spare time, What are your ideas or rough outline for the 'Neo-Natives' in the design document? I stumbled upon this and was trying to work out where they could fit within the design view of the world. My idea for for a faction and the theme a lot of the characters i have written is generally people who lived outside of or on the margins of the mainstream society before the cataclaysm, so that would mean your 'back to nature' primitive types living inawoods for years before it became a necessity. The  anarchists and radicals. the Squatters. The hobos and travellers, the kids with backpacks, face tattoos and stories of traveling the rails. The ones that lived in cabins in the woods, hoarding guns and explosives materials. In short many that were critical of society and civilization before it's fall. 

The interesting being in exploring these themes and ideas post-civlized society and how they change, as well as introducing a group in which some might even be happy that it's all ended and may try to sabotage any efforts at rebuilding the United States (anti-Old Guard missions). Well, this got longer and i explained more than i intended to here, sorry for that. Hopefully it provides some context as to what i'm trying to do and will aid in trying to find where these characters could fit most naturally. The other option is to obviously just release this as a mod.

Sorry if this is an inappropriate place to ask this, i'm pretty new to github. If so i'd very much appreciated being pointed in the right direction. Thanks.

Also, i just wanted to say, a huge thankyou to @mlangsdorf and others for expanding the NPC stuff and moving so much over json. <3

**Comment by anothersimulacrum** [comment]
There are more details available in #27479. This should probably be referenced somewhere in the design doc or get it's own page.

**Comment by faefux** [comment]
Yea, i found this about thirty minutes after making this, there were some interesting ideas there but i found a fair few of them (including neo-natives) either problematic as groups in that they are potentially 2D or over-reliant on a schtick.  Are these descriptions locked in? If so i'd love to take one of them and mold it to what i'm building, if not how resistant to creating new factions is the dev-community when these are barely complete or even started?   

If there is not room to modify one of these factions or build a new one for the mainline i'm still happy to have content as a mod, so it isn't an issue from this end.

entierly offtopic but is your nick referencing J. Baudrillard? Wondered because Simulacra is a pretty uncommon word and i'm currently re-reading so found it a little serendipitous. :)

**Comment by anothersimulacrum** [comment]
Nothing is set in stone - their interpretation is up to whoever gets around to implementing them, but it should try to fit the basic outline given there.
From what I've seen the 'devs' are the opposite of resistant to creating new factions - I know I'd love new factions, and I'm sure others would! It'd be preferable if these ones were implemented, but you can make your own if you're not interested in any of those ideas.

No, it's just a coincidence.

**Comment by faefux** [comment]
Thanks! I'll probably keep on with what i already have as i've been really enjoying writing these and the missions for them. I'd be more than happy to help work on some other factions in the future though, the librarians caught my eye specifically. 

An issue i had when looking at creating factions with spaces in cities is how do I stop them from getting them torn apart in attempting to run after zombies as soon as you enter the reality bubble. This was a pretty big limitation early on, meaning i had too stick to and spawn maps that are not within cities. Any suggestions on this?

**Comment by anothersimulacrum** [comment]
You should be able to do that by blocking their sight to zombies and adding a no investigate zone to the map where they spawn.

**Comment by faefux** [comment]
Oh, i didn't know about no investigate zones at all. I'll look into that! This changes things a lot!!! Thanks!
