### ISSUE TITLE
Map Memory - Remember Familiar Locations aka No Place Like Home

### ISSUE THREAD

**Issue by Teeklin1** [CleverRaven/Cataclysm-DDA#30517]
**Is your feature request related to a problem? Please describe.**  
Even when I've been away from home for many years, when I go back there I still know the streets and the directions to get there and remember where each room in the house is.  Not quite so in CDDA.  Every time I come back to base I have to re-learn the layout no matter how long I've been there.

**Describe the solution you'd like**  
Ideally we would tie map memory into some kind of familiarity system.  The longer you've spent in a location, the more you remember it and are familiar with it until it's just cemented in your memory forever.

Of course when I visit home again I take those same routes and find a road has changed, or a new building has been put up, so you'd still have instances where you go to someplace familiar and find it's been destroyed or changed or infested.  But it would let you retain certain locations for much longer than currently, where I forget what's behind my bedroom door when I leave for two days :)

**Describe alternatives you've considered**  
None yet.

**Additional context**
Giving it some more thought, the most realistic way would be to give each tile a familiarity number and create a familiarity system with certain breakpoints.  Every hour the tile is in view, that familiarity number increases and every hour it's out of view, it decreases.  Set it so that a tile being at X breakpoint for Y duration then drops to a lower level.

So for example, the tiles inside my base start off as strange with 0 points in familiarity when I first get there.  After an hour, each tile is at 1 familiarity.  After familiarity hits 24 for any given tile, familiarity is reset to 0 and that tile is now set as "frequently visited" and it goes up from there.  When familiarity on a  "frequently visited" tile hits say 100, it then goes up to "comfortable" and the number is reset again.  When a "comfortable" tile gets to say 500 familiarity, it then becomes a "well known" tile and the number is reset again.  Finally when the "well known" number is capped out at say 2000, the tile is just cemented forever and we can flag it as a "Home" tile to stop tracking for that character and let them remember it forever and stop decay on it.

Now say you visited a place in the city and it's frequently visited, and then you leave and it decays to 0 familiarity for those tiles flagged as FV, well each breakpoint determines how long you'd remember that tile.  So a "frequently visited" tile would decay down to "unknown" and be forgotten entirely after being at 0 familiarity for 24 hours.  But a "well known" tile would take say, 3 weeks of ingame time to decay down to comfortable, and then comfortable would have to be at 0 for a week to go down to frequently visited, essentially making it so that a "well known" tile would take a month to go through all those stages and be forgotten entirely.

**Comment by MrHrulgin** [comment]
I like this idea.  There's already a mechanism for tracking time spent in an area that's used for the Nomad flaw; perhaps it can be the starting point for remembering an area well?

**Comment by I-am-Erk** [comment]
This ties into my personal wish, that there be a number of mechanics oriented around selecting your "home", whether that's a manual selection or a clever bit of code.

**Comment by ElfLeaderMike** [comment]
I was gonna make an issue but this one seems to fit exactly what I wanted to complain about, just wanted to say this would still be a great addition and it's very silly that you forget "home" after sleeping there for weeks.
