### ISSUE TITLE
More Robust AI/Pathing for friendly robots.

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#30510]
If you choose the robot adoptee start you will notice that your "little" friend smashes through any and all obstacles to reach you. vehicles, gates, windows, benches, etc. About the only thing it doesn't face check is walls.

I suggest a little better pathing/AI. Especially since a military grade robot should be a little bit smarter.

**Comment by Night-Pryanik** [comment]
I'm afraid "Enhance AI of monsters" is not a valid suggestion - AI is already being constantly enhanced.

**Comment by Phenomphear** [comment]
Oh, I guess I was too vague. Human NPC's pathing is much better than the robots pathing. Maybe use that instead? It's annoying because it literally just breaks everything while following you.
