### ISSUE TITLE
Furniture - fire barrel

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#30515]
**Is your feature request related to a problem? Please describe.**  
metal barrels are a great way to safely contain fires, but can't be used for this in game.

**Describe the solution you'd like**  
Make metal barrels a placeable furniture via the construction menu, and function like a brazier.

**Describe alternatives you've considered**  
Could also be (a)ctivated like folding furniture, as with braziers.

**Additional context**  
This is a simple thing to add. If you're thinking of getting into contributing, this would be a great starting point.

![image](https://user-images.githubusercontent.com/45136638/57721342-cbbe4000-7638-11e9-9feb-84e7c2580b7b.png)

**Comment by curstwist** [comment]
be nice to have a variant that includes a grill for cooking too.  Also, bbq grills for backyards if someone decides to expand on outdoor cooking options.

**Comment by Epictyphlosion** [comment]
> be nice to have a variant that includes a grill for cooking too. Also, bbq grills for backyards if someone decides to expand on outdoor cooking options.

I agree with this and OP. This would be a great addition

**Comment by SourSlime** [comment]
Fire barrels have holes in the sides near the bottom, so some metal-cutting tool should be needed to set one up.

**Comment by eilaattwood** [comment]
> 
> 
> Fire barrels have holes in the sides near the bottom, so some metal-cutting tool should be needed to set one up.

Hammering of one-two and a piece of rebar or something similar as a stamp. You don't cut such holes, you pierce them.

**Comment by Dekker3D** [comment]
Yeah, it doesn't need to be a clean hole, it just needs to let air through. A rock or hammer (hammering:1) and a spike would be plenty.

**Comment by I-am-Erk** [comment]
Yeah, generally you can put the holes in with a rock or a chunk of metal I'd assume

**Comment by tinukedaya** [comment]
So I tried to do this, but I have a question.
I thought it's going to be easy just taking the brazier and modify it and the corresponding recipe.
And I was kinda right. Took me few tries, but I made it.

I made it possible to craft from the 100L or 200L drums. But I made the result have the stats of the 100L one, as I have no clue how to make it different based on input components (if possible at all).

Question is: Is that ok? Or should I do 2 recipes one for each variant? 

I don't want to make an PR now, because I'm not sure how I would be able to push the change if 2 recipes would be preferred. NOOB@GIT

**Comment by Night-Pryanik** [comment]
> I have no clue how to make it different based on input components (if possible at all).

It isn't possible at the moment.

> Question is: Is that ok? Or should I do 2 recipes one for each variant?

Two recipes is more complete solution, but I'm not sure if we need two identical (in terms of functionality) items. On the other hand, we already have two almost identical items, differing only by their volume.

**Comment by I-am-Erk** [comment]
While it would be possible to make a fire barrel with a 100L barrel, the 200L drum is the classic type. I would use that as your template.

I'm not sure there's value to a second item, but people are going to complain if the volume of their barrels increases when they make it into a fire barrel... That's just the kind of player base we have

**Comment by tinukedaya** [comment]
Alright. I PR'ed it with the two items.
