### ISSUE TITLE
Invalid terrain id "", upon load in build 8978 Win64 tiles

### ISSUE THREAD

**Issue by Dekker3D** [CleverRaven/Cataclysm-DDA#30529]
# Describe the bug
I get an error while loading my savegame from yesterday's build (unsure which build number) in build 8978.

DEBUG    : invalid terrain id ""
 
 FUNCTION : int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]
 FILE     : src/generic_factory.h
 LINE     : 383

# Steps To Reproduce
1. Load the save file in build 8978 or 8979, Win64, Tiles
2. Error on load.

# Expected behavior
Game no crashy.

# Versions and configuration
- OS: Windows [64-bit]
- Game Version: 0.D-2959-g2af8238
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Explosive Zombies [No_Explosive_Zombies],
    StatsThroughSkills [StatsThroughSkills],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context
[Celada.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3182256/Celada.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3182257/debug.log)

**Comment by Dekker3D** [comment]
Just reverted to build 8975 (http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/8975/changes) and it does not have this error.

**Comment by Dekker3D** [comment]
A second error that happens later during loading mentions a ranch, and build 8976 includes a commit with the comment "mapgen: merge the ranch camp maps"

**Comment by Zireael07** [comment]
That second error already has a fix pending: #30530
