### ISSUE TITLE
mess kits can heat food with no battery

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#30524]
# Describe the bug

Mess kits can heat food when there's no battery magazine installed in them.

# Steps To Reproduce

1. Obtain a mess kit, in your inventory.
2. Unload any battery magazine from the mess kit.
3. 'a'pply the mess kit. You'll get the food heating menu.

# Expected behavior

You shouldn't be able to use the mess kit if there's no battery installed.

# Screenshots

# Versions and configuration

- OS: Windows 10 [64-bit]
- Game Version: 0.D-2937-g23660d6
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Urban Development [Urban_Development],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

# Additional context
NA

**Comment by MrHrulgin** [comment]
Have you loaded a battery into it? It should accept the same size battery as your makeshift welder, so you could try unloading the welder and putting the battery in the mess kit.

**Comment by nornagon** [comment]
Ah, hm. I can load a battery into it, which causes it to show a (current/max) number. But it works fine without a battery in it! I can heat up food with it when it's empty. I'll retitle the bug.

**Comment by Xenomorph-III** [comment]
You should be able to use the kit near a fire to heat up food.

**Comment by nornagon** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/23660d628d3a65483d113a5b45f6cdc8bf0f59b2/src/iuse.cpp#L5223 <-- looks like there's an ammo check here that's exclusively scoped to the atomic coffeepot.

**Comment by Night-Pryanik** [comment]
Hm, can't confirm:
![изображение](https://user-images.githubusercontent.com/11132525/57750154-25367580-76f2-11e9-8b96-8c9cc2ebdece.png)
![изображение](https://user-images.githubusercontent.com/11132525/57750164-2f587400-76f2-11e9-9431-754399aa33a5.png)
![изображение](https://user-images.githubusercontent.com/11132525/57750177-3b443600-76f2-11e9-93ca-d1beee601c7f.png)

**Comment by nornagon** [comment]
![image](https://user-images.githubusercontent.com/172800/57750698-158a4300-7698-11e9-99f5-1a764afc9659.png)
![image](https://user-images.githubusercontent.com/172800/57750725-35216b80-7698-11e9-948f-057e0aebe749.png)
![image](https://user-images.githubusercontent.com/172800/57750708-1f13ab00-7698-11e9-920f-f4ad7526d44d.png)

Save attached.
[Waukee.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3181035/Waukee.zip)

**Comment by Night-Pryanik** [comment]
Activating mess kit and trying to heat up food gives me the following:
![изображение](https://user-images.githubusercontent.com/11132525/57751359-8102fd80-76f6-11e9-9a3d-053ef0bc99b7.png)

Could you please update to the latest version and try again without any mods?

**Comment by Night-Pryanik** [comment]
I tested your save, and it is working as it should - no heating up food without batteries.

**Comment by nornagon** [comment]
I updated to the latest version (build 8974 / 23660d6 -> Build 8977 / 56d0e4b) and now it looks like my mess kit is showing that it has batteries... weird.

![image](https://user-images.githubusercontent.com/172800/57751675-55065e80-769b-11e9-946c-7ae59d85388a.png)

I can't see anything in [this range](https://github.com/CleverRaven/Cataclysm-DDA/compare/23660d6..56d0e4b) which seems like it would have caused that behaviour. I guess my game was just haunted 🤷‍♂
