### ISSUE TITLE
Monster Speed/Resilience Granularity

### ISSUE THREAD

**Issue by hootless** [CleverRaven/Cataclysm-DDA#30528]
**Is your feature request related to a problem? Please describe.**  
There's only one global setting each for both monster speed and resilience, which means you can't choose to have classic shambling zombies while leaving other monster types unchanged.

**Describe the solution you'd like**  
At the very least it'd be nice to have very broad strokes as multiple options. For example, "Zombies", "Otherworldly", "Blobs", etc. The option for a global setting should still exist for people who are fine with everything scaling the same however. The most ideal solution though would be a separate menu (still optional) where it lists every monster in the game and allows you to adjust the speed, resilience, and possibly even their spawn rate individually.

**Additional context**  
Haven't really got any additional context or alternative solutions besides the ones listed

**Comment by kevingranade** [comment]
Plan A:
Exit the game
Using a text editor, open data/json/monsters.json or a file in data/json/monsters/
Find the monster you want to tweak, edit it's stats.

Plan B:
Visit https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors and learn how to make more extensive changes.
