### ISSUE TITLE
Toilet tank water should be safe to drink

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#30520]
# Describe the bug
Water in the toilet furniture is currently considered dirty water. While the water in the bowl is unsafe for consumption, per this [FEMA Fact Sheet](https://www.fema.gov/news-release/2017/10/08/fact-sheet-how-make-your-water-safe-drink) the water in the tank is clean and safe to drink.
 

# Steps To Reproduce
1. Drink water from a toilet.
2. Get food poisoning.

# Expected behavior
I would expect that the 6L of water represented in a toilet would be the water in the tank as opposed to the bowl, and would be clean water, as that's the capacity of a modern day ultra-low flow toilet tank.

EDIT: Additionally, based on the furniture object description of "Emergency water source, from the tank, and provider of relief." It was already intended to contain clean water.

**Comment by nexusmrsep** [comment]
Not in CDDA. The main infection factor of the zombie apocalypse was ground water, so it's not that kind of uncleanness you are thinking of.

**Comment by MrHrulgin** [comment]
We are all infected already. The blob is everywhere and inside every player and NPC. The kind of uncleanness you're talking about is irrelevant.

**Comment by neitsa** [comment]
How long still water in the tank should be considered drinkable without any problem? At some point I guess it should turn and be stale. Is there a flag or something that implements such a decay (turning X into Y after T time)?

**Comment by MrHrulgin** [comment]
While water can taste stale if it stands in a container for long periods of time, that doesn't change its potability. It only goes bad if it is contaminated. With no functioning water supply system, new water won't enter the tank from the municipal system or local well, so the water in the tank will stay the cleanliness it was when the infrastructure was functioning prior to the Cataclysm.

**Comment by ZhilkinSerg** [comment]
Slightly related https://github.com/CleverRaven/Cataclysm-DDA/issues/72

**Comment by JeanLucVanDamme** [comment]
Finding a reliable source of clean water has been one of the primary early-game challenges for years. If toilet water is changed to be clean, it seems too easy on the player. I guess the inevitable compensation is, toilets would end up spawning with variable (sometimes low or empty) amounts of water.

I guess if all that results in the right level of challenge, it's still desirable because it feels more realistic.

Then again, if we end up at the same challenge anyway, why not just make up a realistic justification for why in-game toilet water is dirtier than IRL, and leave it as is? :)   (Not a rhetorical question - not sure which choice I'd prefer)

**Comment by MrHrulgin** [comment]
Honestly, I don't feel like staying hydrated is a challenge in the current game. In a evac center start you can have all the infrastructure and tools you need for fresh water in the first day. In cities (at least in the first week) there's abundant milk and juices as well as more soda than you'd ever want to drink. You'll find a fire source and container to boil water in the first day or so far before you're dying of dehydration; the main early challenge (at least until the default start day is moved to Spring 45) is defrosting drinks, not acquiring them. Beyond that, with the inclusion of hot water tanks in house basements, water is less of a concern than it once was. 

I do like the idea of variable amounts of water remaining. Maybe some of them cracked, or someone used it after the water supply failed. Plenty of justifications for there being less than a full tank.

**Comment by faefux** [comment]
This is something i've always thought about when playing, the water in the cistern should be fine, if you're drinking from the toilet you're not drinking from the bowl, right? 

I always just took it as a gamafaction and a decent explanation i head-cannoned was that running water had stopped functioning before the evacuations, etc. meaning the cisterns were not refilling, so the only water left would be the bowl.

I'm not saying i'm opposed to this, to be clear. What i'm getting at is that either works, if not having so much clean water is better for balance reasons this odd feature could still be explained away.

**Comment by JeanLucVanDamme** [comment]
Great points @MrHrulgin. I'd add one thing though. "Staying hydrated is easy"... true, _but only once you've gotten past "complete noob" skill_. IOW, sure, it's not a challenge for very long, but it's a great little complication that forces players to learn _tons_ of the mechanics in the game. Including clean vs dirty water, food poisoning, the importance of staying moving / looking for loot in more places if the house you're in doesn't have what you need, etc etc.

So even though the only "challenge" removed by this change is trivial to experienced players, that challenge is still important for first-time players as a learning experience. 

(But I could be wrong. Shrug.)

**Comment by Dacendeth** [comment]
Early game water is already crazy easy now that almost every basement has a water heater with 30-80 units of clean water, do we really need it to be even easier?

**Comment by JeanLucVanDamme** [comment]
Wow, are basement water heaters that bad right now? That should probably be nerfed for _both_ balance and realism.

**Comment by MrHrulgin** [comment]
Water heaters have a capacity range from 30-80 gallons (113.5 - 302.75L, or 454 to 1211 units). The amount of clean water in a water heater is actually unrealistically *small*.

**Comment by Dacendeth** [comment]
I dont think water heaters get hot enough to actually boil the water in them, though the water in them is probably on the safer side in terms of potability.

**Comment by MrHrulgin** [comment]
They do not, but the water is intended for human consumption and is potable, as stated in the FEMA factsheet linked in the OP.

**Comment by Greevv** [comment]
I agree with this sentiment, also, why the hell is rainwater dirty?

**Comment by Rivet-the-Zombie** [comment]
It's not considered clean [because a lot of toilet tanks look like this](https://www.howtolookatahouse.com/Blog/ewExternalFiles/ToiletTankMold.JPG).

**Comment by MrHrulgin** [comment]
@Rivet-the-Zombie I agree that's a very impressive image. Does that affect the potability of the water?

**Comment by eilaattwood** [comment]
> I dont think water heaters get hot enough to actually boil the water in them, though the water in them is probably on the safer side in terms of potability.

The water for both toilet cisterns and water heaters is coming from water pipes, and under normal condition it should be clean and disinfected before distributing to the people.

And about water heaters... While working, they stay heated just below boiling point for a very long terms, and that's actually [enough to kill almost every infection.](https://en.wikipedia.org/wiki/Pasteurization)

**Comment by eilaattwood** [comment]
> 
> 
> @Rivet-the-Zombie I agree that's a very impressive image. Does that affect the potability of the water?

Mold can grow in that conditions. And it is definitely not very healthy.

**Comment by Rail-Runner** [comment]
> Mold can grow in that conditions. And it is definitely not very healthy.

Actually this gets me thinking that different varieties of unclean water may be necessary. For some (like water from rivers) simply boiling it is enough, but some would have to be filtered using some advanced filters or distilled to become safe.

**Comment by MrHrulgin** [comment]
@eilaattwood Can you provide sources that mold near a water supply affects the potability? All of my google searching shows a number of respiratory concerns from mold in houses, but nothing relating to potability concerns.

**Comment by CEG86** [comment]
This would pretty much destroy the difficulty of the early game and more than one successful game loved for its challenge has made this kind of silly pitfall.

**Comment by SourSlime** [comment]
Maybe give it a low-medium morale penalty to balance the clean water out? I can’t imagine anyone feeling happy after drinking water that has been in any part of a toilet.

**Comment by eilaattwood** [comment]
> 
> 
> @eilaattwood Can you provide sources that mold near a water supply affects the potability? All of my google searching shows a number of respiratory concerns from mold in houses, but nothing relating to potability concerns.

[Mycotoxins part](https://en.wikipedia.org/wiki/Chaetomium_globosum), for example.

**Comment by MrHrulgin** [comment]
From your link: "It is a saprophytic fungus that primarily resides on plants, soil, straw, and dung." That's not particularly relevant to the inside of a ceramic or porcelain tank with rust-resistant metal fixtures.

**Comment by faefux** [comment]
> It's not considered clean [because a lot of toilet tanks look like this](https://www.howtolookatahouse.com/Blog/ewExternalFiles/ToiletTankMold.JPG).

Lots? Maybe this is common in america, i can't speak specifically for new-england, but i've never seen a cistern that looks like this. We'd have to first know what the lining on the ceramic is, and then, do you have anything to show that this is common?

**Comment by eilaattwood** [comment]
> 
> 
> From your link: "It is a saprophytic fungus that primarily resides on plants, soil, straw, and dung." That's not particularly relevant to the inside of a ceramic or porcelain tank with rust-resistant metal fixtures.

Primarely. But also a with lot of mold types it can grow even on concrete. And almost all of them are toxic. like [this](https://en.wikipedia.org/wiki/Stachybotrys_chartarum), or [this](https://en.wikipedia.org/wiki/Aspergillus_niger)


![That's it.](https://cdn-www.terminix.com/cs/smrblog/found-mold-in-shower-bathtub/1115.10-how-to-prevent-and-get-rid-of-mold-in-bathroom.jpg)

**Comment by MrHrulgin** [comment]
That photo is very impressive, and us backed up by no citations regarding toilet tank water potability. Similarly, both links you provided talk about molds with respiratory effects rather than anything regarding water potability.

**Comment by Rail-Runner** [comment]
Well, I once heard of a person who got badly poisoned by eating mouldy bread. I don't think bathroom mould would be too different from that.

**Comment by MrHrulgin** [comment]
That some molds are toxic is not in question. Please provide a citation that shows that toxic molds that grow on bread are also found in toilet tanks in sufficient quantity to cause food poisoning in someone drinking the water.

**Comment by ZhilkinSerg** [comment]
Current in-game clean water is either boiled or purified with chemicals. Water from toilet tanks is neither of the two. Adding more different water contaminations is fine, but simply making toilet water clean water is not.

**Comment by Rail-Runner** [comment]
Well, it's not actually the mold itself that is toxic, but the waste products of it. If such a mold is growing in or near water, the waste products will be going into the water because they simply can't go anywhere else, and if water isn't changed for a while, they'll keep accumulating. Aspergillus is quite a common mold, which is stated to grow pretty much anywhere there is a lot of oxygen (including on building materials), and produces aflatoxins, which can cause poisoning. Source: https://en.wikipedia.org/wiki/Mycotoxin , mainly section "In indoor environments".

Probably best to just give some chance to find "clean" water, because some people do keep their toilet tanks clean and mold-free.

**Comment by eilaattwood** [comment]
> 
> 
> Current in-game clean water is either boiled or purified with chemicals. Water from toilet tanks is neither of the two. Adding more different water contaminations is fine, but simply making toilet water clean water is not.
It actually WAS purified with chemicals at the water supply station. The question is if it was contaminated after that, or not.

**Comment by eilaattwood** [comment]
> 
> 
> Well, it's not actually the mold itself that is toxic, but the waste products of it. If such a mold is growing in or near water, the waste products will be going into the water because they simply can't go anywhere else, and if water isn't changed for a while, they'll keep accumulating. Aspergillus is quite a common mold, which is stated to grow pretty much anywhere there is a lot of oxygen (including on building materials), and produces aflatoxins, which can cause poisoning. Source: https://en.wikipedia.org/wiki/Mycotoxin , mainly section "In indoor environments".
> 
> Probably best to just give some chance to find "normal" water but with no poison in it, because some people do keep their toilet tanks clean and mold-free. And of course player can't know if it's safe, but can boil it to be sure about it.

Here question will be: Does actually boiling destroys mycotoxins, as they are not life form but chemical poison with unknown properties. It potentially can stand much higher temperatures than infection itself.

**Comment by ZhilkinSerg** [comment]
> It actually WAS purified with chemicals at the water supply station. The question is if it was contaminated after that, or not.

Thanks. I've mastered Water Treatment, so I know a thing or two. It really doesn't matter whether it was treated with chlorine, ozone,  UV or anything else before it came to the tank. It is not clean water which we have in-game right now.

**Comment by faefux** [comment]
How bad the mold may or may not be for you isn't the issue, @Rail-Runner, As i see it the issue is of how common this is. i've personally never seen it but it would be interesting if you could provide a source showing that this is a common problem within america or new-england specifically?

Bigger question is; Do we sacrifice a huge part of what is the start-game and the beginners game

**Comment by MrHrulgin** [comment]
@ZhilkinSerg What has happened to the water between the water treatment plant and the tank it's sitting in when the survivor finds it that has ruined its potability?

**Comment by ZhilkinSerg** [comment]
> 
> 
> @ZhilkinSerg What has happened to the water between the water treatment plant and the tank it's sitting in when the survivor finds it that has ruined its potability?

Time.

**Comment by MrHrulgin** [comment]
Could you be a little bit more detailed about the physical processes involved? Time itself does not cause water to spoil.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Could you explain the physical processes involved? Time itself does not cause water to spoil.

It is more biology than physics, and it is obvious - time passes, life grows.

**Comment by MrHrulgin** [comment]
Could you provide some details into the life that grows in a closed toilet tank that would harm the potability of that water? I cited FEMA in the OP with a clear statement that water in a toilet tank is a potential source of clean water. If you can't provide anything resembling a source, please stop arguing the point.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Could you provide some details into the life that grows in a closed toilet tank that would harm the potability of that water? I cited FEMA in the OP with a clear statement that water in a toilet tank is a potential source of clean water. If you can't provide anything resembling a source, please stop arguing the point.

Did I argue? It is obvious that toilet tank water is not the same as boiled/purified "clean water" we have in game and that's it (i.e. we are not making toilets spawn `water_clean`).

**Comment by MrHrulgin** [comment]
I see. So realism as a guiding force just stops? I've cited direct recommendations from specialists in emergency survival, and that's not enough?

**Comment by ZhilkinSerg** [comment]
> 
> 
> I see. So realism as a guiding force just stops? I've cited direct recommendations from specialists in emergency survival, and that's not enough?

If you look carefully to the link you provided there are two definitions: "safe water" and "clean water". Toilet tank water is the latter.

The thing is "clean water" that we have in game is actually "safe water" by FEMA definitions.

**Comment by MrHrulgin** [comment]
Given that it says that 

> "Water from swimming pools, spas, and collected rain water can be used for personal hygiene and cleaning, **but not for drinking.**"

the fact that it omits that warning for water from toilet tanks makes it clear that it is safe drinking water.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Given that it says that
> 
> > "Water from swimming pools, spas, and collected rain water can be used for personal hygiene and cleaning, **but not for drinking.**"
> 
> the fact that it omits that warning for water from toilet tanks makes it clear that it is safe drinking water.

We are not making toilets spawn `water_clean` similar to boiling. Feel free to expand water contamination/purification system though (rough outlines exist in #72) - that would be a great addition to the game.

**Comment by MrHrulgin** [comment]
Are you going to change the all water heaters to not have clean water? They're from the same source and in similar environmental situations.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Are you going to change the all water heaters to not have clean water? They're from the same source, in similar environmental situations, and recommended by FEMA in the same section.

Yes, I believe they should be changed to spawn `water`, instead of `water_clean` until we have water contamination system expanded.

**Comment by MrHrulgin** [comment]
Ok, what is your belief based upon? You're very clear that you believe that the water is unsafe, but you're not actually citing any basis for that belief. We're trying to make this game as faithful a simulation of what surviving an actual disaster looks like, and I'm citing sources that address that exact situation.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Ok, what is your belief based upon? You're very clear that you believe that the water is unsafe, but you're not actually citing any basis for that belief. We're trying to make this game a faithful simulation of what surviving an actual disaster looks like, and I'm citing sources that address that exact situation.

Until we have expanded water contamination system we have binary system:

- `water_clean` - bottled/boiled/purified water;
- `water` - everything else.

Toilet tank water belongs to second category.

**Comment by MrHrulgin** [comment]
Ok, fair, but there's already [variations in chance to cause food poisoning based upon source](https://github.com/CleverRaven/Cataclysm-DDA/blob/f20ddfdb36ccaf8103b459bccdc65e6b08334fb1/src/map.cpp#L4412). Would you be amenable to leaving it as 'water', but dropping the chance of illness from it to zero or near zero?

**Comment by GroeneAppel** [comment]
A factor that should be taken into account by those who worry about the difficulty: CDDA is a constantly changing game, one change will surely be balanced out in the future by another. 
Since realism is considered a big deal, we shouldn't cancel this suggestion out due to the change in difficulty it may cause. Especially if it is based on some decent evidence.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Ok, fair, but there's already [variations in chance to cause food poisoning based upon source](https://github.com/CleverRaven/Cataclysm-DDA/blob/f20ddfdb36ccaf8103b459bccdc65e6b08334fb1/src/map.cpp#L4412). Would you be amenable to leaving it as 'water', but dropping the chance of illness from it to zero or near zero? It would be safe, as I've shown, but without any of the certainty that comes with 'water_clean'.

Yes, that makes total sense. Leaving `water_clean` alone as perfectly drinkable water and use `water` for any questionable sources with varied poison levels (which could be expanded to different contaminants later).

> 
> 
> A factor that should be taken into account by those who worry about the difficulty: CDDA is a constantly changing game, one change will surely be balanced out in the future by another.
> Since realism is considered a big deal, we shouldn't cancel this suggestion out due to the change in difficulty it may cause. Especially if it is based on some decent evidence.

I wouldn't worry about water anymore - we have #30442.

**Comment by kevingranade** [comment]
I could see dropping the poison chance to something relatively low IF the cistern is clean, but there needs to be some ratio of clean and contaminated cisterns to go with it, because not all cisterns are clean. Along with that there should be some ratio of cisterns that are chemically treated, and therefore even more dangerous than existing poison chance, though they should appear as yet another item type, contaminated water or similar.

As ZhilkinSerg has said a number of times, making toilet water clean_water is not happening.

I don't find the FEMA statement compelling, it doesn't cite any sources, and it only indicates the *possibility* that the water is clean.

``Alternative sources of clean water can be found inside and outside the home.``  Can be found, that's not very meaningful...
``The following are possible sources of water:``
Possible, not definite.
``Water from your home’s toilet tank (not from the bowl), if``
``it is clear``
Ok, so we definitely have some occurrence of not-clear water that is harmful.
``and has not been chemically treated with toilet cleaners``
And we definitely have some occurrence of water that has been treated with toxic cleaners.
``such as those that change the color of the water``
Maybe it changes the color, maybe it doesn't.

So we have several categories of water.
Visibly toxic water.
Invisibly toxic water.
Contaminated cloudy water.
Contaminated clear water.
Safe clear water.

The two dangerous but clear kinds can be further divided into ones that do or do not have hints that they're dangerous, for example nearby mold that doesn't change water color or a toilet bowl cleaner holder.

We can possibly dispense with some of these, but I see no compelling indication that it should always or even almost always be safe.

**Comment by MrHrulgin** [comment]
Ok. I'll focus on #72, then.
