### ISSUE TITLE
Water purification tablets usage is too high

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#30539]
**Is your feature request related to a problem? Please describe.**  
Currently in the game you need 1 tablet per 1 unit (250 ml) of water, while they spawn in bottles of 15, I believe.  That's just too much for realistic and practical usage. I think, nobody actually regularly use them in the game.

**Describe the solution you'd like**  
According to [this](http://www.hydrachem.co.uk/brand/oasis-water-purification-tablets/), water purification tablets come with different concentration of active substance. The smallest is 1 tablet per 1 liter, the biggest is 1 tablet per 200 liters. I think, we should use something in between, like 1 tablet per 10L or at least 1 tablet per gallon. Formula for water container purification should look like this:
N = ceil(V/c), where N is amount of tables needed to purify all the water in the container, V is volume of water in the container, and c is volume that can be purified with one tablet.

**Describe alternatives you've considered**  
Leave it as is, despite it is not right.

**Additional context**  
None.

**Comment by kevingranade** [comment]
I can definitely buy bumping it to 1L/tablet for a "personal use" style product, which it's clearly intended to be.

We *could* introduce some additional variety of tablet sizes, but practically speaking we could also just add in the calculation that says that purifying in large batches is more efficient and have that consume an appropriate number of "1L" tablets.

**Comment by eilaattwood** [comment]
Then it makes sence to make them at least craftable at larger batches and spawn with larger quantities. Because it makes no sence if with a full pack of tablets I found I can only purify contents of TWO regular canteens.

**Comment by Inglonias** [comment]
This is a case where adding some realism makes the game easier, not harder. I'm all for it.
