### ISSUE TITLE
Press ? for help.

### ISSUE THREAD

**Issue by molkero** [CleverRaven/Cataclysm-DDA#30535]
**Is your feature request related to a problem? Please describe.**  
The keybindings menu [?] works on nearly every screen, even the keybindings menu. It's shown in player info screen, crafting menu, construction menu, mutation menu, layering menu, advanced inventory and the map, each with a different flavor of press ? for help/keybindings.

**Describe the solution you'd like**  
Put "Press ? for keybindings on any screen." on the title screen under tip of the day, or player info maybe.
![20190515203216_1](https://user-images.githubusercontent.com/49575273/57797874-1a143180-7754-11e9-9668-3f6dcb4feb85.jpg)

**Describe alternatives you've considered**  
Put a red ? in a corner of every window.
![20190515203515_1](https://user-images.githubusercontent.com/49575273/57797889-226c6c80-7754-11e9-9637-fd7b4d2a9b5e.jpg)

**Comment by esotericist** [comment]
Ironically, the main title screen is a place where `?` does not work. 

I like the idea, though.

**Comment by Night-Pryanik** [comment]
I think simple `<?>` is not enough. I guess it would be better if we add the whole sentence - `Press ? for help` - in the corner of every window.

**Comment by molkero** [comment]
Yeah title screen is the only place it actually gives the help screen, otherwise mapped to 0.

**Comment by molkero** [comment]
`< [?]Keys >` in top right corner, `< [/]Filter [K]eybind [K]eybind ... >` bottom left could be used in almost every window for a nice uniform style. Unfortunately my copy-paste skills are not enough.
