### ISSUE TITLE
Electroreceptors mutation problem/request/QoL fix

### ISSUE THREAD

**Issue by XhameX** [CleverRaven/Cataclysm-DDA#30533]
### Game version:
0.D-2977-gb68b6ca (tiles)
Build: 8980

### Operating system:
Windows 10

### Mods active:
 "dda"  "no_npc_food"  "aftershock"  "adv_gear"  "ArmUpPAUtil"  "ArmUpSurvEx"  "realguns"  "SD_Magcrafting"  "SD_Magcrafting_Realguns_Extension"  "craftgp"  "FIC_Weapons"  "antifunguskit"  "growable-pots"  "ew_pack"  "makeshift"  "Medieval_Stuff"  "modern_weapon"  "More_Armors"  "More_Survival_Tools"  "nw_pack"  "Nechronica_Redux"  "shardstuff"  "DinoMod"  "modular_turrets"  "PK_REBALANCE"  "Salvaged_Robots"  "alt_map_key"  "Cata++"  "noctpk"  "mutant_npcs"  "MMA"  "Arcana"  "vamp_stuff"  "vamp_stuff+arcana"  "zets_hair_extensions"  "more_locations"  "zets_hair_ext_more_locations"  "zets_hair_ext_pk_rebalance"  "national_guard_camp"  "national_guard_camp_edit"  "P_Caches"  "mapgen_demo"  "Urban_Development"  "boats"  "deoxymod"  "blazemod"  "Tanks"  "MST_Extra"  "necromancy"  "Airdrops_n_Alchemy"  "Arts' Guns"  "jury_rigged_robots"  "NM_wpns"  "MGCPatch"  "more_classes_scenarios"  "RL_Classes"  "disable_bots"  "disable_bots_natcamp"  "cddaxp_Malkeus"  "manualbionicinstall"  "Mutation_Changes"  "no_reviving_zombies"  "StatsThroughSkills"  "blaze_extension_M"  "ZSFIXED_cddaxp"  "DP_No_Debug_Tile"  "DP_No_Status_Tiles"  "DP_REMIX_INDICATORS" "DP_No_Highlight"

### Actual behavior 
The Electroreceptors mutation has the effect that `allowing you to see robots and creatures charged with electricity through walls` and while using a gun to `Aim`
the target to shoot at can snap to targets below or above current Z-level.
And the main problem here is that if a zombie on my current Z-level is
x amount of tiles away: 1-x and another enemy i can see with my `Electroreceptors` is the same range away, the aim starts at enemies above or below current Z-level first.
This makes ranged combat somewhat frustrating/unclear since i can't turn of the mutation that is causing it unlike the `night-vision` mutation.
### Expected behavior
Aim at threats that is in current Z-level LOS first
Or
Just not aim/auto-aim at targets that is on another Z-level with x amount of solid rock between player and target

### Steps to reproduce the behavior

# Steps To Reproduce
1: Add Electroreceptors mutation
2: wield a gun
3: go to a Lab and stand on normal Z-level
4: spawn electronic/robotic enemy x-amount of tiles below current Z-level
5: spawn enemy at the same distance on current Z-level
6: Aim

**Comment by HeadstrongCatgirl** [comment]
Duplicate of #29945, but this one has better structure.

**Comment by XhameX** [comment]
> Duplicate of #29945, but this one has better structure.

Terribly sorry about that.
I was looking around for this problem, but could only find a couple of other posts about this issue.

Let me know if this is to much of a duplicate post and i'll remove this one and add my text and toughs to the one @HeadstrongCatgirl pointed me to.
