### ISSUE TITLE
Can't find new battery cells when reloading certain (on) electronics

### ISSUE THREAD

**Issue by dsmky117** [CleverRaven/Cataclysm-DDA#30541]
# Describe the bug

When reloading an mp3 player (on) (and some other electronics, see Additional Context below) loaded with a battery cell from the battery overhaul (#29651), the reload menu only finds legacy batteries instead of the new battery cells.

# Steps To Reproduce

1. Make a player with an mp3 player loaded with a light battery cell with an extra cell in your inventory. (I couldn't figure out how to spawn charged batteries, so you might need to stick them in a vehicle recharger first).
2. Activate the mp3 player and try to reload it.
3. If there are legacy batteries nearby, the reload menu will allow you to load those batteries (a single stack appears twice for some reason). Light battery cells are not displayed. Attempting to reload the legacy batteries consumes them and does not affect the charge of the mp3 player.

# Expected behavior

It shouldn't matter that the mp3 player is on or off, reloading should allow you to insert light battery cells.

# Screenshots

![image](https://user-images.githubusercontent.com/19257672/57809666-e9240480-7733-11e9-8e45-ca1a739f3495.png)

# Versions and configuration

- OS: Windows 10 [64-bit]
- Game Version: 0.D-2980-g8b1dd86
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

It looks like this does not affect flashlights, they reload as expected. I did some testing and found that this is also an issue for the following items (I didn't test everything, but you can find items by searching for '(on)' in the item spawn menu):

- All thermal electric gear
- radio
- geiger counter
- noise emitter

**Comment by esotericist** [comment]
I can at least explain the "battery goo shows up twice" problem: one of those is attempting to reload the device itself (which it shouldn't allow) the other is attempting to reload the magazine (which is technically legal, but should be superceded by attempting to swap the magazine on the device).

That's why they have different "Moves" indicators.

**Comment by esotericist** [comment]
I think I see the difference between these devices and the flashlight, though. the `flashlight (on)` item uses `"copy-from": "flashlight"` to inherit the properties of the normal flashlight. the mp3 player does not.

**Comment by esotericist** [comment]
Legit misclick on the assignment. But if someone else hasn't gotten to this by the time I wake up I'll probably tackle it then
