### ISSUE TITLE
Imaginary Npc can be Disarmed and their weapon remained after

### ISSUE THREAD

**Issue by EirenexTheDragon** [CleverRaven/Cataclysm-DDA#30544]
# Describe the bug
So basically i tried to disarm the Npc from my hallucination off his weapon by examining him and using the command to disarm. i succeeded and it caused his weapon to drop, and him to dissappear afterwards. the weapon was real and all that was left

# Steps To Reproduce

1. Start to hallucinate (i had used Schizo for that)
2. Find an imaginary Npc that is wielding something
3. press e on him, and choose the option to disarm the npc. notice how it leaves behind the weapon (probably need high skill for success in disarming?)

# Expected behavior
It should either be a fake item that fades away when you try to pick it up, or make the npc vanish at the attempt to disarm already.

# Screenshots
![grafik](https://user-images.githubusercontent.com/41762755/57813254-c1eb2880-776f-11e9-88e9-2056b910cfbf.png)

# Versions and configuration
- OS: Windows [64-bit]
- Game Version: 0.D-2980-g8b1dd86
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Extended Realistic Guns [realguns],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Hide STATUS [DP_No_Status_Tiles],
    No Fungal Monsters [No_Fungi],
    Safe Autodoc [safeautodoc],
    Manual Bionic Installation [manualbionicinstall]
]

# Additional context

I dont think there is much more to add. maybe make it create a funny message?

**Comment by Rod995** [comment]
I suppose this could be fixed by making a check for hallucinations in the disarm function.
