### ISSUE TITLE
An error pops up when I'm driving through a city on my vehicle

### ISSUE THREAD

**Issue by dom4op** [CleverRaven/Cataclysm-DDA#30559]
# Describe the bug
Just an error message. Currently having a time of my life ramming into zombies on my custom truck. But every turn there is an error which is totally skippable (the game seems to run just fine). It's just mildly worrying.

# Steps To Reproduce
No clue, sorry. Just load the save attached below, and ram some zombies, I guess.
(press 5 after loading the game)

# Expected behavior
Not receiving that error? I'm mostly reporting this because it might indicate some hidden problem that would affect other vehicle-related stuff.

# Screenshots

![Sprite-0002](https://user-images.githubusercontent.com/49651777/57879000-15b74980-7824-11e9-9311-8a193d7d7173.jpg)

 - OS: Windows 10
 - Game Version: build 8990 (0.D-3040-g9565c64)
 - Graphics version: Tiles
 - Mods loaded: Just one minor personal mod tweaking some .json values regarding location spawn rates.

# Additional context
I was just testing how much zombies can my vehicle run down before it will need repairs. Never had this problem before, but then again - never rammed that much zeds before.

[Highgate.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3188557/Highgate.zip)
[Grimwulf_mod.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3188563/Grimwulf_mod.zip)

**Comment by dom4op** [comment]
Something's definitely broken with collision system. Same city, except I was travelling on foot. At some point got surrounded by zombie hordes and decided to hide in an abandoned storefront. Then some weird messages began appearing, like, "some vehicle collides with another vehicle". Weird, because I had no way to see what's outside - there were no windows in my room.
After just a couple of collision messages the game crashed.
![Sprite-0002](https://user-images.githubusercontent.com/49651777/57949865-482d7900-78ee-11e9-91d8-e632b2e2f4d9.jpg)

... Maybe I should just stop visiting that city.

**Comment by dom4op** [comment]
Attaching log files.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3192763/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3192764/debug.log)

So there's this:

src/game.cpp:4108: game:monmove: spore cloud can't move to its location! (58:39:0), brick wall
21:47:07.149 ERROR GAME : src/game.cpp:4108: game:monmove: boomer can't move to its location! (19:13:0), pavement
21:51:47.385 : Log shutdown.

Presumably collided vehicles might have blocked zombie movement, can't really tell for certain.

**Comment by int-ua** [comment]
Please comment if it's still an issue.
