### ISSUE TITLE
Can batch craft more laser sights then you should be able to

### ISSUE THREAD

**Issue by Koalabog** [CleverRaven/Cataclysm-DDA#30564]
# Describe the bug
when crafting laser sights you can craft batches larger then you should be able to because the recipe has the same component(Lenses) show up twice

# Steps To Reproduce
1. have surplus components for multiple laser sights but only 2 lenses
2. batch craft 2 laser sights
3. you now have 4 lenses worth of laser sights

# Expected behavior
That if i only have 2 lenses i will only be able to make 1 laser sight because it needs 2

# Screenshots
with only 2 lenses in storage it is marked as "enough" for batch crafting 2 laser sights which should require 2 each
![image](https://user-images.githubusercontent.com/41955378/57895003-a94f4100-7849-11e9-9d8c-8abfcc561217.png)

# Versions and configuration
- OS: Windows [64-bit]
- Game Version: 0.D-3040-g9565c64
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Weapon fixes [variousweaponfixes],
    Boats [boats]
]

**Comment by kevingranade** [comment]
That has a simple fix, these shouldn't be craftable at all, at least not with the extant recipe.

**Comment by Mooses2k** [comment]
> 
> 
> That has a simple fix, these shouldn't be craftable at all, at least not with the extant recipe.

This is labeled Good First Issue, so.
What's your desired fix? Remove that recipe or make it realistic and make this one a 'makeshift underbarrel lasersight' that's twice as bulky?

**Comment by kevingranade** [comment]
Remove, there isn't a reasonable 'from scratch' crafting recipe for making a laser.

If you want to spawn lasers in various places and overhaul the recipe to take a laser as the primary component, that would be fine too.
