### ISSUE TITLE
Equipment layer temperature reporting wrong numbers

### ISSUE THREAD

**Issue by TinkerWorX** [CleverRaven/Cataclysm-DDA#30561]
# Describe the bug

Temperature in the `+` menu seems to not match actual body part temperature.
![cataclysm-tiles_2019-05-16_21-55-46](https://user-images.githubusercontent.com/1730988/57888774-5f5b6080-7833-11e9-8f86-a002995ca40a.png)
`+` menu shows both body parts hot, but game thinks they're chilly.

Head temperature also keeps jumping back and forth between two values
![cataclysm-tiles_2019-05-16_21-44-51](https://user-images.githubusercontent.com/1730988/57888808-769a4e00-7833-11e9-84b0-1bc2248270f6.png)
![cataclysm-tiles_2019-05-16_21-45-04](https://user-images.githubusercontent.com/1730988/57888809-77cb7b00-7833-11e9-8f32-57f5619d8d34.png)

# Steps To Reproduce

1. open up the attached save game
2. skip a few turns and notice how the head temperature is jumping
3. open the character menu
4. notice the hands are chilly, but they're actually hot in the layer menu

# Expected behavior

Temperature should match what the player is told.

# Versions and configuration

- OS: Windows 10 [64-bit]
- Game Version: 0.D-3040-g9565c64
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Manual Bionic Installation [manualbionicinstall],
    StatsThroughSkills [StatsThroughSkills]
]
[Fort Totten.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3189122/Fort.Totten.zip)

**Comment by Dacendeth** [comment]
Isnt this just your character using their pockets/hood when they get cold, and then stop using them when they get hot since the winter coat is such a huge temp swing?

**Comment by I-am-Erk** [comment]
I'm just going to accelerate and close this unless OP wants to confirm that they weren't in fact putting their hood on to explain the result.
