### ISSUE TITLE
Infinite Dog food

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#30570]
# Describe the bug
Feeding a dog with Dog food tames the dog but keep the item. 

# Steps To Reproduce
Spawn dog food
Spawn a dog
Tame the dog
observe Dog Food still in the inventory with (1) portion.
- Feed the dog again if you want. 

# Expected behavior
Dog food will be eaten by the dog.

- OS: Windows [64-bit]
- Game Version: 0.D-2977-gb68b6ca
- Graphics Version: Tiles

**Comment by gr0mazeka** [comment]
same for chicken

**Comment by LordSunder** [comment]
Infinite bird food in general. Tried with waterfowl and yellow chicks (wanted pets to replace a dead npc), can confirm.
