### ISSUE TITLE
Can select killer drive trait without psychopath

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#30575]
# Describe the bug

In character creation you are able to select the killer drive trait without having to take the psychopath trait, and I understand the latter is a prerequisite of the former. If you select psychopath you are not able to take killer drive; however, if you take psychopath first and then killer drive then killer drive is just greyed out while still taking the char points.

# Steps To Reproduce

1. Make a new world and select option to make a new character.
2. In char gen go to the traits section and choose psychopath
3. Option for killer drive if greyed out

1. Make a new world and select option to make a new character.
2. In char gen go to the traits section and choose killer drive.
3. Choose psychopath trait.
4. Option for killer drive if greyed out but points are still taken.

# Expected behavior

Taking killer drive makes you have psychopath or should be allowed you take both of them.

# Versions and configuration

 - OS: [Window 10]
 - Game Version: [0.D-3050-g663428a, Build # 8991]
 - Graphics version: [Tiles]
 - Mods loaded: [Core]

**Comment by Night-Pryanik** [comment]
As far as I remember, there is no other traits available at the character generation that require predecessor traits. Killer drive is a sole exception of this. Simplest solution would be removing it from the list of starting traits.
On the other hand, if we remove it from starting traits, players could get this trait only by mutating, and it doesn't look like a good thing. So we could remove Psychopath from prerequisites, and players could get Killer Drive from the start, alongside with Psychopath.
