### ISSUE TITLE
Cauterize NPC

### ISSUE THREAD

**Issue by Nickmarez** [CleverRaven/Cataclysm-DDA#30572]
# Describe the bug

There is no current mechanism to cauterize the wounds of an NPC

# Steps To Reproduce

When an NPC has a bite wound, try to use a knife on the NPC

# Expected behavior

An attempt will be made to cauterize/disinfect the NPC's wound.
Items that can cauterize could be available when using the "Use Item On" selection of an NPC.

**Comment by kevingranade** [comment]
This needs to either happen through the conversation menu or another dedicated NPC interaction menu so the NPC can decide how they want to respond.
