### ISSUE TITLE
Instance based level generation for creation of small special area maps

### ISSUE THREAD

**Issue by Phenomphear** [CleverRaven/Cataclysm-DDA#30587]
I had an idea come to me a little while ago. The shimmering portals do a few things like spawn nether creatures, but, what if you could enter them and find yourself somewhere in another area/dimension instead of simply being teleported randomly a few tiles. 

There could be lots of weird things added like floating gas balls that glow, odd-looking objects that take the place of "furniture" like in houses, unique loot, lots of nether creatures and so on. It could even have its own unique terrain and traps that affect the player in some way even if just occasionally. You could vary what is found there based upon some lore and other things.

I also had an idea of adding a sort of rebirth mechanic that could rarely be found in this area that's guarded by traps and creatures. A pod that when interacted with creates an identical copy of the player but with some degree of random stats and mutations based on what the player has already and is then stored in the save data and accessed upon the player's death. You would then wake up in that pod and have to leave the portal the same way you came in. (Ideally, you would leave yourself supplies next to the pod "just in case") The message you get upon death could be "You feel you're conscious swept away, warping in on itself just before you die." with a "Resist?" yes/no prompt allowing the player to choose death instead. (This idea probably has a lot to overcome but I thought I'd put it out there anyway.)

The Dimension:
It could be mostly dark and only lit by certain objects or monsters. Should be deadly or at least extremely difficult for unprepared players.

I'll list a few items and objects to kinda give the general feel:
"Floating gas sphere"
'A sphere of floating gas that looks just as flammable as it does beautiful. Inside are several swirling layers of different colors all held together by a thin organic grayish membrane.'
*These could be a sort of "trap" that would explode if hit by accident or run into. Either catching fire and exploding shortly after or dousing the player in harmful toxic gas and goo if simply smashed.*

"Otherworldly Terrain"
'You try to focus on the terrain but it keeps moving in and out of focus. It seems to occasionally slime over or absorb your feet like a tide. It is blackish gray. Most of the time.'
*The terrain the area would be mostly made of.*

"Glowing Mold Swarm" (Monster)
A swarm of orange glowing mold spores. Each one is the size of a shirt button! They look toxic. You can see a dripping overflow of juices pooling on the ground below them.

*This nasty thing can poison, acid burn and create toxic clouds but should probably be blind and sense from noise and smell*

"Mutated Mi-Go"
"A Mi-Go that has been accidentally, or purposefully, mutated by unknown means."

*A Mi-Go with "select" random mutations erring on the more deadly side that should have some kind of mutational armor to prevent cheesing it. Yea, that should be pretty tough to fight.*

And now for some cool loot:

"Morphing Tissue Ball"
"A ball of morphing tissue about the size of a tennis ball. It withers about in place as if intelligent. Disgusting."
*This item could act like a CBM, giving the player a nice bonus but rather then installed, if picked up, the tissue ball would immediately unravel itself like a "rolly Polly" and attach itself to the player "installing" itself and forming Symbiosis. Now for the next part, there are 2 ways I can think of to do this. One way is to give the player a trait called "Symbiosis" and then 3 random traits. 2 Positive and 1 negative. The other way is to give them a trait called "Symbiosis" and in that trait are set bonuses and negatives. I would really like the creature to incure some kind of negative penatily on the player to give it a risk reward scenerio and because I seriously doubt something like that is just going to attach itself and say "Here let me make you all better!". No, it WANTS something and will GIVE you something for it. Which is why I think traits are a good choice. Like chemical imbalance but Light Step and Scout. Or Very Fast metabolism but Very Fast Healer and Tough Skin. Stuff like that.

I know that seems kinda crazy, but, it'd be like an organic version of a CBM that you don't need any skill to install. So it should be pretty good but also have a downside because it's a living thing that wants stuff from you.

You could easily create a whole suite of these that do different specific things like the CBM's once you establish a code for them and keep them available only in this place.

The whole idea could use some discussion, tips, and constructive criticism so here it is!

**Comment by faefux** [comment]
Well, seems like it'd mostly be json, right? More than happy to help you build this if it's a project you want to work on with others.

**Comment by Phenomphear** [comment]
I'd love to do it but I only have a small amount of time I could dedicate to it. I also don't really know how to do all the stuff I suggested. I was kinda hoping someone would be like "I know how to do that!" and then come up with something like it. I might be able to do some of the more simple things like items and stuff, but I don't know how to do anything else.
