### ISSUE TITLE
NPC fire ranged weapon Crash

### ISSUE THREAD

**Issue by Specter1882** [CleverRaven/Cataclysm-DDA#30580]
# Describe the bug

NPC that use a range weapon over a grid distance will crash

# Steps To Reproduce

1. Make a npc with a gun, magazine, and some ammo.
2. spawn an enemy nearing the npc ( at least 3 blocks)
3. Following error message appears in debug.log:

# Expected behavior

hope can fix this bug 
This makes many of the combat missions impossible

# Versions and configuration
- OS: Android [32-bit]
- Game Version: 0.D-3092-ge386936
- Graphics Version: Tiles
- Mods loaded: [
    [dda]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3192592/debug.log)
[沃拉沃拉.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3192595/default.zip)

**Comment by ZhilkinSerg** [comment]
Can you please signup for Beta on PlayStore (that way you can receive semi-stable Experimental updates) and see if issue is resolved there?

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed for a year.
