### ISSUE TITLE
Unable to reassign key for inventory item to none

### ISSUE THREAD

**Issue by JeanLucVanDamme** [CleverRaven/Cataclysm-DDA#30597]
# Describe the Bug

At the reassign prompt (triggered by "=" while examining an inventory item), pressing SPACE is supposed to clear the key assigned to the item (i.e., change it to none.)

SPACE actually does the same thing as ESCAPE - exits out of the reassign prompt, leaving item key unchanged.

# Steps To Reproduce

1. Select a carried item in the [i]nventory screen with ENTER.
2. Press = for prompt to reassign item key.
3. Press SPACE -- item key remains unchanged.

# Expected behavior

Item key should now be blank in inventory.

# Screenshots
![Before (same as After!)](https://user-images.githubusercontent.com/50250164/57965183-5f786080-7906-11e9-8fac-de5fbaadb337.png)
**Before attempting to reassign cash card (u) to none. The after screenshot would be identical, so is not included.**

![Reassign Prompt](https://user-images.githubusercontent.com/50250164/57965187-70c16d00-7906-11e9-8602-6a2810b9f1ea.png)
**The reassign prompt**

# Versions and configuration

 - OS: [ Windows 10 Pro, Version 1709, Build 16299.967 (64-bit) ]
 - Game Version: [0.D-3099-gb961576]
 - Graphics version: [Tiles]
 - Mods loaded: Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food] 

# Additional context

The same result occurs when SPACE is pressed with or without SHIFT, and also with and without CAPSLOCK.

**Comment by esotericist** [comment]
You appear to have the game set to automatically assign invlets. The "space" choice is not to give an item no invlet, it's to clear an invlet you have set.

Try setting the item to something specific, then clearing it with space.

**Comment by esotericist** [comment]
The setting in question that causes the inventory letters to be automatically assigned:
![image](https://user-images.githubusercontent.com/1569754/57965243-7747e880-78f6-11e9-8d03-d30c6e1688d9.png)

**Comment by JeanLucVanDamme** [comment]
That doesn't seem to work quite right either. 

1. I reassigned the item to "j" (below). Note, font color changed to orange (I guess that means, manually assigned.)
![image](https://user-images.githubusercontent.com/50250164/57965260-8b481600-7907-11e9-81b6-49294de4df26.png)

2. Used reassign prompt, pressed SPACE to clear (below). The result was: the item still assigned to "j", but "j" is now in white font rather than orange.
![image](https://user-images.githubusercontent.com/50250164/57965276-c1859580-7907-11e9-8889-ce8f393a7646.png)

**Comment by JeanLucVanDamme** [comment]
Just tested with a new game, with Auto Inventory Letters set to "False". In that case, it works as expected - SPACE clears the item invlet.

**Comment by esotericist** [comment]
the reason it stays `j` with auto inventory letters on is because once it no longer has a manually assigned invlet, it automatically gets an available invlet. and you just made `j` available.

Basically, you need that setting off in order to be able to have an item with no invlet.

**Comment by esotericist** [comment]
What I can do is change that text to be more clear about what "space" is actually offering, since it's probable you're not the only person who's been confused by this.

**Comment by JeanLucVanDamme** [comment]
Huh. Is that intended behavior? It's really unintuitive/weird to me. Especially given no prompts or warnings that it wouldn't work.

**Comment by esotericist** [comment]
It's the only way it basically *can* work from an implementation angle. auto inventory letters does its best to guarantee letters on everything in your inventory.

I'll try to work on the message so that's clearer.

**Comment by JeanLucVanDamme** [comment]
That sounds like a good improvement, thanks!

Is there something I'm missing about my intended use case? I was happy with the game auto-assigning letters for most items, but then for certain unimportant items, I wanted to clear those.

I also just assumed the auto-assignment only happens when an item is first picked up.

**Comment by esotericist** [comment]
There's been discussion about making a third setting for auto-assigning invlets: favorited items only.

Because being honest, now that we *have* favorited items, there's a very clear way for a player to communicate to the game "I actually care about this", and most things you pick up are probably going to end up in a loot pile.

**Comment by JeanLucVanDamme** [comment]
"Favorited items only" actually sounds like the perfect solution to this.
