### ISSUE TITLE
Crash while driving a vehicle one Z-level up

### ISSUE THREAD

**Issue by YukariMindGap** [CleverRaven/Cataclysm-DDA#30599]
# Describe the bug
When i try driving a vehicle into open air, the vehicle is still on the same Z-level. Then the game will crash if you turn the vehicle while still mid-air.

# Steps To Reproduce
1. Teleport to a roof (or anything one z-level up
2. Spawn a bicycle and get on it.
3. Try riding it into open air.
4. For additional fun, try turning mid-air

# Expected behavior
The bike will fall down a z-level and receive damage. Also, there's no crash while it's happening

# Versions and configuration

- OS: Windows [32-bit]
- Game Version: 0.D-3101-g3efcc3e
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3193742/save.zip)

**Comment by egorzaderiy** [comment]
For me car just moves and turns freely in air.
I think it is related to line 7736 in map.cpp: 
```
if( vp.has_feature( VPFLAG_BOARDABLE ) && !vp.part().is_broken() ) {
    floor_cache[px][py] = true;
}
```
It sets floor_cache which is later used to decide whenever or not vehicle falls down in `vehicle_move.cpp: 
 vehicle::check_falling_or_floating()`
