### ISSUE TITLE
Repair cloth for friendly NPC

### ISSUE THREAD

**Issue by LOMS** [CleverRaven/Cataclysm-DDA#30607]
**Is your feature request related to a problem? Please describe.**  
Repairing clothes for your NPC-followers is pain. You must unequip their cloth/armor items, then go to trade, find and grab all you need to repair, then repair, then ask your NPC to use this item (and they may refuse!), or drop these items on the ground and then equip them back through "sort armor" menu. That's just too much.

**Describe the solution you'd like**
Ability to repair clothes for friendly NPC's, which are adjacent to player.

**Describe alternatives you've considered**  
These features will make current process less tedious:
Ability to unequip items from NPC directly to players inventory. 
In "sort armor", ability to equip items directly from your inventory, not only from ground or NPC's own inventory.

**Additional context** 
This picture gives me minor pain.
![image](https://user-images.githubusercontent.com/2064587/57968679-2bd51f00-7976-11e9-8753-a8e329494864.png)

**Comment by Mooses2k** [comment]
Eventually give NPCs ability to using sewing kits too, though they'll need to train up, of course.
