### ISSUE TITLE
Morale menu feedback is unclear and potentially misleading

### ISSUE THREAD

**Issue by BTAxis** [CleverRaven/Cataclysm-DDA#30612]
# Describe the bug

When multiple sources of morale are present (music, books, food, etc) the "total morale gain" is not the sum of all morale modifiers, which was the case in 0.D. If this is now intended behavior it is still problematic due to the way the morale modifiers are represented, which very much implies they should be summed. 

# Steps To Reproduce

1. Gain morale from a source
2. Gain morale from at least one more source
3. Add the morale modifiers together (there are programs that can help with this)
4. Compare the answer obtained above with the total morale value displayed

# Expected behavior

Either the same behavior as in 0.D, or clearer communication to the player in regards to how the total morale gain value is calculated.

# Screenshots

![image](https://user-images.githubusercontent.com/119742/57971868-1f5fbf00-7994-11e9-860e-cd0bf0619977.png)

# Versions and configuration

- OS: Windows 10 Pro [64-bit]
- Game Version: 0.D-3101-g3efcc3e
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Filthy Clothing [filthy_morale],
    Simplified Nutrition [novitamins],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Locations [more_locations],
    Boats [boats],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Makeshift Items Mod [makeshift]
]

**Comment by ifreund** [comment]
This is intentional, see #29396.

I do agree that there is room for improving the way the total bonus is communicated though.  Any specific suggestions are welcome.

**Comment by BTAxis** [comment]
Alas. I feel this is not a change for the better.

Moving on though, I think morale representation is a bit of a mess generally, not only because the final value is now not what one would expect, but also because in the item descriptions of books the morale gain displayed is actually multiplied by 5, while for food items the value displayed is the value used.

Perhaps at the heart of the problem is the fact that morale is given as an explicit number in the first place, which is rare in a game that typically hides most of the underlying mechanics and represents them with vague indicators, if at all.

**Comment by esotericist** [comment]
The morale menu can definitely use some cleaning up to make what's happening clearer. As for books, I suspect the inconsistency might be related to the blocks of time in which reading is done.

**Comment by kevingranade** [comment]
I'd be all for making all of the morale feedback fuzzier, ideally textual.
