### ISSUE TITLE
Crash on smoking a joint

### ISSUE THREAD

**Issue by Randonx** [CleverRaven/Cataclysm-DDA#30624]
# Describe the bug

If I try to smoke a joint, my game immediately crashes.

# Steps To Reproduce

**Steps to reproduce the behavior:**
1. Have a joint in my inventory
2. Activate the joint

# Expected behavior

Alleviation from my broken legs as they heal.

[Additionally, I've smoked joints on this play through before, without issue]

# Versions and configuration

 **- OS:** Windows 10 Pro
 **- Game Version:** 0.D-3178-g258b2e8
 **- Graphics version:** Tiles
 **- Mods loaded:**
  "dda",
  "no_npc_food",
  "growable-pots",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "no_freeze",
  "PK_REBALANCE",
  "alt_map_key",
  "Cata++",
  "hydroponics",
  "Mining_Mod",
  "national_guard_camp_edit",
  "more_locations",
  "FujiStruct",
  "mapgen_demo",
  "deoxymod",
  "boats",
  "Arcana",
  "DP_Old_Floor",
  "DP_REMIX_INDICATORS",
  "cbm_slots",
  "Battery_Overhaul_Legacy_Mode",
  "manualbionicinstall",
  "no_filthy_clothing",
  "no_reviving_zombies",
  "safeautodoc",
  "StatsThroughSkills"

# Additional context
**Crash/Debug:**
[Crash-Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3194457/Crash-Debug.zip)
**Save (Including Mods):**
[Crash save(Including mods).zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3194465/Crash.save.Including.mods.zip)

**Comment by Randonx** [comment]
Further into the same run, I decided to save an try it again.  This time I was able to do it no problem, but I only had one to test.

**Comment by ZhilkinSerg** [comment]
Cannot reproduce on current master w/o third-party mods. Please report here if you still got the crash.
