### ISSUE TITLE
Move *some* for Advanced Inventory 

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#30628]
When being a hilarious packrat in the early game, some times you have to make do moving huge piles of crap with multiple trips with and a small shopping cart. When doing so, though, your only options for easy transfer of items are either to hold down return and hope it works out, or to move all via advanced inventory, but it will keep going even after the destination is full and keep dumping it overboard..

I would love if there were a move-until-full option, that would auto-stop if the destination was full.

I've tried just waiting till I see the yellow messages about the destination being full and then stopping, but it still ends up wasting time and sometimes you gotta stop it a few times for it to register.

**Comment by JeanLucVanDamme** [comment]
This may be only a partial solution for you, but I believe "M" (SHIFT-m) moves the entire highlighted item stack in AIM. That's certainly a lot better than pressing ENTER dozens of times on one stack.

Do you still find the overall process annoying or unintuitive with "M" in your bag of tricks?

**Comment by Randonx** [comment]
Also, 'm' allows you to move a certain quantity of an item.  But I think his issue is the move all command wasting time even after it's moved everything that will fit in your destination.  So maybe that portion of move all just needs to be fixed.

**Comment by Midaychi** [comment]
I guess I just don't understand the point of move all not stopping on destination full by default.

**Comment by TinkerWorX** [comment]
Interestingly, in the past, it would stop and ask if you wanted to continue when it was full. That was changed at some point. Whether intentionally or not I don't know.
