### ISSUE TITLE
Removing Zoo Keeper Profession does not remove attached Animal Empathy trait

### ISSUE THREAD

**Issue by TheSalamanderDJ** [CleverRaven/Cataclysm-DDA#30629]
Game version: 0.D-3181-g339945f (Build 9002)

Operating system: Windows 10 64-bit

Tiles or curses: Tiles

Mods active: None

### Expected behavior
After removing the profession Zoo Keeper while creating a character, Animal Empathy trait would be removed as well.
### Actual behavior
Animal Empathy trait remains after switching professions from Zoo Keeper. Can be removed manually for an extra point in the pool.
### Steps to reproduce the behavior
1. During character creation, select the Zoo Keeper Profession
2. Select any other profession
3. Remove Animal Empathy trait for extra pool point

**Comment by Feuerhai** [comment]
Related/duplicate: #23851

**Comment by Night-Pryanik** [comment]
Closing as duplicate.
