### ISSUE TITLE
Apartment escape

### ISSUE THREAD

**Issue by Tommyboyo1** [CleverRaven/Cataclysm-DDA#30646]
need to be a apartment escape start
start on roof with help sign and random mats depending on starting class and have to get from top to bottom and go through tons of zombies
like that one lfd map
"The helicopter flew over you, bringing the sounds of the dead just behind it, for once getting down is gonna be harder than it was getting up"
check that idea

**Comment by LordSunder** [comment]
Why not give it a shot and edit some json to make your idea a reality? You seem fairly invested in the idea, so making it yourself might be the thing you need to get started with contributing. I think the apartment you're looking for is in json/mapgen/apartment_mod_new.json, and the starting location stuff is also in the json folder. The people on the discord are pretty helpful, if you get stuck.

**Comment by FrozenSnowFox** [comment]
I'm actually messing with it right now.  Just wondering if I should make a custom profession, allow all professions or lock it to survivor.

**Comment by Maxi25554** [comment]
Just allow all professions. Anyone could get in that situation.

**Comment by Tommyboyo1** [comment]
I don't think a broken cyborg or a mycus bio weapon could but others for
sure, ill work on it myself on my own time just to say I'm not useless.

**Comment by FrozenSnowFox** [comment]
I have it all working fine except one possible spawn location gets you stuck behind a stupid npc with no way out.  There doesn't seem to be a way to avoid it either since the orientation varies the map id number.

**Comment by Tommyboyo1** [comment]
Just a small problem there, player can just use debug menu to teleport a
square away.

**Comment by FrozenSnowFox** [comment]
Yeah but that's really not an acceptable solution.  I was thinking of maybe modifying the terrain slightly so you can walk around the npc.

**Comment by Tommyboyo1** [comment]
True enough, might be able to just replace terrain with that one old
machinery tile, or even just a roof turbine.
Those are passable.

**Comment by Tommyboyo1** [comment]
any updates buddy <3?

**Comment by FrozenSnowFox** [comment]
You might not have seen it via email but if you look above your comment on the github it has a link to the PR I posted for the scenario.

**Comment by Tommyboyo1** [comment]
thank you Pardner'

**Comment by Wayticus** [comment]
Messed around with it myself, way to solve the NPC blocking you is make a solo start no NPC.  I don't think it will be as challenging as the OP thinks since you just have to run down all the flights of stairs to ground level, now if you increased the zombie spawns on the ground floor it would be harder.

**Comment by FrozenSnowFox** [comment]
I missed the solo start tag earlier.  I need to fix a few things, revert the map changes, add solo start and surrounded start.  I think that should do for a decent new starting scenario then.

A version more as OP described would be good too later.  Start in the summer, help sign on the roof, used up supplies and the floors packed with zombies.  Although I'm not sure how exactly that stuff would be done.  I still don't know a lot about modding this game.

**Comment by Night-Pryanik** [comment]
I think this one could be closed after #30678.
