### ISSUE TITLE
Charge containers displaying wrong contents and contents going missing

### ISSUE THREAD

**Issue by FrozenSnowFox** [CleverRaven/Cataclysm-DDA#30643]
# Describe the bug

I'm not sure what exactly is happening but charge containers are displaying wrong and their contents is going missing or reappearing.  Looking at the recent PRs this one #30255 did something to containers so it may be the cause?

My empty anaesthetic kits showed 3/3 charges but the autodoc said they are empty.  Unloading one allowed me to empty non existent anaesthetic into a container and then transfer it back to have a working kit.

When trying to unload gasoline from one refillable lighter to another the contents disappeared entirely.

# Steps To Reproduce

1. Dev mode in 2 refillable lighters.
2. Unload one lighter into the other.
3. Weirdness ensues.

# Versions and configuration

- OS: Windows [64-bit]
- Game Version: 0.D-3181-g339945f
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Urban Development [Urban_Development],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Filthy Clothing [filthy_morale],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    No Fungal Monsters [No_Fungi]
]

**Comment by Fris0uman** [comment]
Definitly caused by #30255 , it's due to a missing check for is_container(). But there's more stuff broken by that PR so I'll try to fix all of them, hopefully without breaking even more stuff this time U_U

**Comment by FrozenSnowFox** [comment]
Thanks for getting to it so quickly.

There's definitely more I didn't notice initially.  I think even guns might have been affected.  I saw someone mention it on reddit and when I unloaded a gun I found it still listed its ammo but was considered empty.

**Comment by Fris0uman** [comment]
Yep guns and tools, but #30653 should fix all of it
