### ISSUE TITLE
Electric Chainsaw no longer turns on with UPS conversion mod installed

### ISSUE THREAD

**Issue by FrozenSnowFox** [CleverRaven/Cataclysm-DDA#30647]
# Describe the bug

If the electric chainsaw is fitted with a UPS conversion mod it can no longer be turned on even if the player has bionic power and the UPS bionic or a charged UPS device on them.

Edit: After playing more I discovered the Survivor Headlamp also fails to turn on and the soldering iron complains it has no charges.  The Electric Jackhammer, MP3 Player and E-Ink Tablet all work fine however.  So it seems some tools work and some don't.

# Steps To Reproduce

1. Dev mode in an electric chainsaw and a UPS conversion mod.
2. Have a UPS bionic or charged UPS device.
3. Try and fail to turn on the electric chainsaw 20+ times.

# Expected behavior

The electric chainsaw should turn on.

# Versions and configuration

- OS: Windows [64-bit]
- Game Version: 0.D-3181-g339945f
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Urban Development [Urban_Development],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    No Fungal Monsters [No_Fungi]
]

**Comment by KurzedMetal** [comment]
Dup of #29961?

**Comment by FrozenSnowFox** [comment]
Worded differently but it seems like the same general issue.  I must have missed it when I searched, sorry about that.

**Comment by ifreund** [comment]
No worries, we just want to keep the number of open issues down as much as possible.  We're obviously somewhat failing though 😄
