### ISSUE TITLE
Idling in main menu wastes cpu cycles

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#30654]
f084da0dcaf4e08c13025d7d912b3518308e0426
`main_menu::print_menu` is entered repeatedly and needlessly.
Seems like the culprit is `handle_input_timeout`. I think it shouldn't actually time out.

**Comment by l29ah** [comment]
Meanwhile in gprof:
```
nds   seconds    calls  ms/call  ms/call  name····
 25.00      0.01     0.01   143869     0.00     0.00  get_all_colors()
 25.00      0.02     0.01    56617     0.00     0.00  void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag)
 25.00      0.03     0.01     1504     0.01     0.01  std::_Vector_base<long, std::allocator<long> >::~_Vector_base()
 25.00      0.04     0.01       21     0.48     0.48  level_cache::level_cache()
```

**Comment by kevingranade** [comment]
This exit from blocking on input is currently used in animation code, and in the future it will be used for background processing.

I can take a look at how much time it is spending during this processing though, it *should* be negligible.

**Comment by kevingranade** [comment]
This is redundant with #22375
