### ISSUE TITLE
Described action different from real action when activating pot of water

### ISSUE THREAD

**Issue by pltrz** [CleverRaven/Cataclysm-DDA#30651]
# Describe the bug

Activating a pot of water (presumably other containers are the same) describes the action as "Heat up food (in it)". When selecting this, the character drinks the water. The described action is different from the real action.

# Steps To Reproduce

1. Get a pot
2. Walk up to a toilet
3. Fill the pot with toilet water
4. [A]ctivate the pot ("Heat up food (in it)")
5. Character drinks the water

# Expected behavior

Character should not drink the water, or the described action should change to "drink water"

# Versions and configuration

 - OS: Void Linux
 - Game Version: 0.D; compiled myself with the following variables:
    - RELEASE
    - CLANG
    - LTO
    - LUA
    - TILES
    - SOUND
    - USE_XDG_DIR
 - Graphics version: Tiles
 - Mods loaded:
    - Dark Days Ahead
    - Disable NPC Needs
    - Filthy Clothing
    - Simplified Nutrition
    - Alternative Map Key
    - Stats Through Skills

**Comment by Feuerhai** [comment]
I tried it out in the latest version and wasn't able to put water inside a pot. It's ability to hold water seems to have been removed.

**Comment by RedShakespeare** [comment]
Bug still exists in 0.d-6692-gcf4ce7d or 0.d-9512.
I tried to fix this but found the use_action-related functions are to complecated and failed to locate the bug. Hope someone else can help.

**Comment by KorGgenT** [comment]
I have been told that this bug is fixed. can i get another person to independently verify please?

**Comment by wapcaplet** [comment]
Confirmed, this appears to be fixed as of 0.E-5799-gd2843c7920

The `a`ctivation menu for the pot shows "Heat up food (in it)"

![image](https://user-images.githubusercontent.com/238395/92532494-a66e2180-f1ed-11ea-9bab-7f6956a9e0be.png)

And selecting the pot correctly prompts "Heat up what?"

![image](https://user-images.githubusercontent.com/238395/92532507-ad952f80-f1ed-11ea-8735-fb5b817a198c.png)
