### ISSUE TITLE
"From the below you hear whump!" (Typo)

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#30666]
# Describe the bug
![image](https://user-images.githubusercontent.com/2125926/57987443-6c549b80-7a4f-11e9-8116-847f6e4f1a9d.png)

# Steps To Reproduce

Have a zombie make noise below you.

# Expected behavior
"From below you hear whump". It's a typo

# Versions and configuration
 - OS: Windows 10 Home
 - Game Version: 0.D-3181-g339945f
 - Graphics version: Tiles
 - Mods loaded: N/A

# Additional context
N/A

**Comment by Night-Pryanik** [comment]
It's not a typo, but our template for messages - `From the %1$s you hear %2$s`. While it's entirely possible to add a cases from `below` and `above` directions, I don't think it'll worth the hassle.

**Comment by micage** [comment]
"..., I don't think **it's** worth the hassle"
Bringing incorrect language into a game is never a good idea. Just because it's only human language and not program code does not mean that we are allowed to leave it incorrect.

**Comment by Inglonias** [comment]
You can argue that we can remove the word "the" template and it would still be more correct than what we've got. `From %1$s you hear %2$s`. It's really a matter of preference, and yeah, this is far from a gamebreaker.

**Comment by neitsa** [comment]
Not a native English speaker, but would it sill be correct if the direction is one of the cardinal directions?

For example `From north you hear thump`. It doesn't look / sound quite right to me, but I might be wrong, of course.

**Comment by Inglonias** [comment]
I mean... You're right. Its not correct either
