### ISSUE TITLE
Vehicle or item related crash

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#30660]
When examining my vehicle after installing some batteries, the game crashed. Stack trace below:

```
 	ntdll.dll!00007ff90697475a()	Unknown
 	ntdll.dll!00007ff90697c266()	Unknown
 	ntdll.dll!00007ff90697c531()	Unknown
 	ntdll.dll!00007ff90691a505()	Unknown
 	ntdll.dll!00007ff90692990d()	Unknown
 	Cataclysm-vcpkg-static-Release-x64.exe!_free_base(void * block) Line 105	C++
 	[External Code]	
 	Cataclysm-vcpkg-static-Release-x64.exe!vehicle::remove_item(int part, std::_List_iterator<std::_List_val<std::_List_simple_types<item> > > it) Line 4456	C++
 	Cataclysm-vcpkg-static-Release-x64.exe!vehicle_stack::erase(std::_List_iterator<std::_List_val<std::_List_simple_types<item> > > it) Line 82	C++
 	Cataclysm-vcpkg-static-Release-x64.exe!process_item(item_stack & items, std::_List_iterator<std::_List_val<std::_List_simple_types<item> > > & n, const tripoint & location, const bool activate, const float insulation, const temperature_flag flag) Line 4498	C++
 	Cataclysm-vcpkg-static-Release-x64.exe!map::process_items_in_vehicle(vehicle & cur_veh, submap & current_submap, const int __formal, bool(*)(item_stack &, std::_List_iterator<std::_List_val<std::_List_simple_types<item> > > &, const tripoint &, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, temperature_flag) processor, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & signal) Line 4707	C++
>	[Inline Frame] Cataclysm-vcpkg-static-Release-x64.exe!map::process_items_in_vehicles(submap & gridz, const int) Line 4645	C++
 	Cataclysm-vcpkg-static-Release-x64.exe!map::process_items(bool active, bool(*)(item_stack &, std::_List_iterator<std::_List_val<std::_List_simple_types<item> > > &, const tripoint &, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, temperature_flag) processor, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & signal) Line 4594	C++
 	Cataclysm-vcpkg-static-Release-x64.exe!map::process_active_items() Line 4576	C++
 	Cataclysm-vcpkg-static-Release-x64.exe!game::do_turn() Line 1484	C++
 	Cataclysm-vcpkg-static-Release-x64.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 689	C++

```

![image](https://user-images.githubusercontent.com/30208401/57986019-85ece780-7a3d-11e9-8fff-441272ed2c45.png)

Upon force quitting the game, I appear to be right before the point where the game crashed. This could mean the crash was related to saving, as i was also installing car batteries recently.
To reproduce the actual crash: Walk a couple squares northwest on the provided save.

# Versions and configuration

commit 85a7b72507 compiled from master
I also have some magic mod content on this particular build. However, I re launched the game on master to make sure the error is not because of my own content. That being said, The debug messages about missing Magiclysm content, missing item definitions, and a missing trait can safely be ignored for bugtesting purposes.

OS: Windows 10

[Magiclysm Play.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3195432/Magiclysm.Play.zip)

**Comment by OrenAudeles** [comment]
Tested on Ubuntu 18.04, using master and your magic-complete branch. Was unable to reproduce crash.
Moved around a bit, saved the game, then zipped it up as requested on Discord.
[Magiclysm Play.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3195690/Magiclysm.Play.zip)

**Comment by KorGgenT** [comment]
i'l confirm that the error has disappeared in the new save. maybe the original error was windows only or something?

**Comment by chriseich21** [comment]
Did you remove a part from the vehicle and what was it?

**Comment by KorGgenT** [comment]
Loaded the save again with current master, got some errors due to the save being old, and vehicle not found" but it doesn't seg fault anymore, so i'm closing it.

**Comment by gc2020x4** [comment]
@kevingranade @KorGgenT 
Kevin Grenade must leave the project forever.
