### ISSUE TITLE
Soybean and raw edamame are in the SEED category

### ISSUE THREAD

**Issue by RarkGrames** [CleverRaven/Cataclysm-DDA#30670]
# Describe the bug
Soybean and raw edamame are in the SEED category instead of FOOD.

"Additional context" -->
Both items use "copy-from": "seed".

# Versions and configuration

- OS: Windows [64-bit]
- Game Version: 0.D-3220-gf084da0
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Boats [boats],
    No Filthy Clothing [no_filthy_clothing]

**Comment by I-am-Erk** [comment]
They are edible seeds though.

**Comment by RarkGrames** [comment]
@I-am-Erk Yeah, they belong to both category technically. For me it would be more logical to have them as raw food that can be planted, based on that you eat them more often than sow them.

**Comment by I-am-Erk** [comment]
I think it comes to personal preference there. If they're in seeds, people may not think of eating them; if they're in food, people may not think of planting them.

**Comment by RarkGrames** [comment]
I can see that. It is just these two are the only seedlike comestibles that give calories and not a "handful of". First I thought that there was a miscategorization, but it seems like that you can't craft planting seed item out of them.
