### ISSUE TITLE
Tools showing wrong current charges count.

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#30686]
# Describe the bug

Gas masks are crafted with 100 charges of cartridge showing, but can't be unloaded, CAN be reloaded, can't be used in recipes (e.g. rebreather), and dupe cartridges on disassemble.

# Steps To Reproduce

1. Craft a gas mask
2. Try to unload and reload it.
3. Try to craft rebreather with it.
4. Disassemble gas mask.

# Expected behavior
Gas mask is crafted with no charges in it, and crafted gas mask can be used as ingridient in crafteing.

# Screenshots

None

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-3241-g5372d73
 - Graphics version: Tiles
 - Mods loaded: []

# Additional context

None

**Comment by spacenookie** [comment]
*NOT* confirmed on
cataclysmdda-0.D-8574-Linux
works as expected on this version

**Comment by eilaattwood** [comment]
> _NOT_ confirmed on
> cataclysmdda-0.D-8574-Linux
> works as expected on this version

Now I see the problem occuring not only with gas masks, but with different tools having charges. Their shown charges became fixed and does not update during reload, and showing correctly only in extended view. Will try to make screenshot later...

**Comment by eilaattwood** [comment]
Ah, this was caused by #30255 and is already fixed, but savefile is now corrupted.
