### ISSUE TITLE
Error on load in build 9011. "assignment does not update value"

### ISSUE THREAD

**Issue by Dekker3D** [CleverRaven/Cataclysm-DDA#30682]
# Describe the bug
The following error message shows up when I load my save in build 9011, win64, tiles. It's fine in build 9010.

 DEBUG    : line 62:19: assignment does not update value

    "techniques": [ "WBLOCK_1" ],
    "warmth": 5,
    "encumbrance":
                  ^
                   15,
    "coverage": 80,
    "material_thickness": 4,

 
 FUNCTION : void report_strict_violation(JsonObject&, const string&, const string&)
 FILE     : src/assign.h
 LINE     : 46

# Steps To Reproduce
Load the savegame, crash on load.

# Versions and configuration
- OS: Windows [64-bit]
- Game Version: 0.D-3251-gba376ea
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Explosive Zombies [No_Explosive_Zombies],
    StatsThroughSkills [StatsThroughSkills],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context
[Celada.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3197054/Celada.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3197055/debug.log)

**Comment by Night-Pryanik** [comment]
That's not a crash, that's a bug.

**Comment by jniscior** [comment]
Additional info: Also happens on OS X when trying to create a new character without any mods.

**Comment by SecretaryNotSure** [comment]
Hey, I'm new here. So... how to fix?? Restore previous build, or reinstall vanilla...?

**Comment by Night-Pryanik** [comment]
Wait a little until someone fixes this. Or revert to earlier build, up to the stable one.

**Comment by Dekker3D** [comment]
Just loaded the same save file into build 9016. No issue whatsoever. It looks like this was fixed and ZhilkinSerg says it was, so I'm closing this issue.

**Comment by ZhilkinSerg** [comment]
Cause by #30412, closed in #30700.
