### ISSUE TITLE
OS X build extremely slow

### ISSUE THREAD

**Issue by micage** [CleverRaven/Cataclysm-DDA#30698]
I'm not 100% sure when it exactly happened because I played CDDA on Windows for the last 2 weeks. The windows version plays like a charm. OS X and Windows are installed on the same machine. But the OS X version is so laggy that I can not play it anymore.

For OS X I built the last version from github and also downloaded a precompiled DMG to compare - no difference, both laggy. What happened?

I've also not been able to make a release build with RELEASE=1. Ok, the build is made but it crashes immediately.

My systems:
OS X 10.11.6, El Capitan, 4 GB RAM, Intel Q6600, NVidia 8800 GTX
Window 7 Ultimate, ... like above

**Comment by ifreund** [comment]
>I've also not been able to make a release build with RELEASE=1. 

This is why it runs very slowly

>Ok, the build is made but it crashes immediately.

What's the stack trace?

I admittedly haven't downloaded any of the automated builds for a while, but I haven't noticed any issues with building or running the game on OS X

**Comment by micage** [comment]
The point is that there is no difference in performance neither my compiled version nor the precompiled version I downloaded. So I guess the precompiled version is a debug build. Has anyone been able to build it with RELEASE=1 on OS X lately?

As I mentioned there is a huge performance difference between Windows and OS X. And the computer is exactly the same. So I think the Windows version is a REAL release version with all optimizations applied and the OS X is always a debug build. Correct me if I'm wrong.

STACK TRACE:
        0   cataclysm-tiles                     0x00000001100fd5ba _Z21debug_write_backtraceRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEE + 43
        1   cataclysm-tiles                     0x00000001100e70ca _Z9log_crashPKcS0_ + 896
        2   cataclysm-tiles                     0x00000001100e6c68 _Z14signal_handleri + 66
        3   libsystem_platform.dylib            0x00007fff9778552a _sigtramp + 26
        4   ???                                 0x0000000000000000 0x0 + 0
        5   cataclysm-tiles                     0x00000001107d3bcf _ZN13player_moraleaSEOS_ + 93
        6   cataclysm-tiles                     0x00000001107ad0bc _ZN6playeraSEOS_ + 2118
        7   cataclysm-tiles                     0x0000000110441fac _ZN9main_menu14opening_screenEv + 1028
        8   cataclysm-tiles                     0x000000011043c536 main + 3264
        9   libdyld.dylib                       0x00007fff94fb95ad start + 1
        10  ???                                 0x0000000000000001 0x0 + 1

**Comment by ZhilkinSerg** [comment]
Did you try homebrew version? Is it slow too?

**Comment by esotericist** [comment]
There were a lot of problems with errors in compilation on older versions of OS X (10.11 and earlier, to be exact) with optimizations enabled, so most optimizations are disabled for that target for release versions. Ironically, the debug version has slightly more optimization.

Unfortunately, as you're on 10.11, there's not a whole lot that can be safely done. You *could* adjust your local copy of the makefile to enable higher optimizations than `-O0` but this is very much a "at your own risk" issue.

**Comment by micage** [comment]
10.11 is too old? From my experience the newer libraries mostly address new features of the latest Apple products. That does not touch any desktops and the most macbooks. In your makefile you give a compile target OSX_MIN=10.5. But anyway, I see, I have to buy a newer computer too play CDDA on OS X. Or use Windows. Grmpf.

**Comment by ZhilkinSerg** [comment]
> 
> 
> 10.11 is too old? From my experience the newer libraries mostly address new features of the latest Apple products. That does not touch any desktops and the most macbooks. In your makefile you give a compile target OSX_MIN=10.5. But anyway, I see, I have to buy a newer computer too play CDDA on OS X. Or use Windows. Grmpf.

It is not about hardware. While we aim to support multiple build and runtime environments nobody is obliged to support a specific configuration for you. It is possible that that CDDA would fail to compile, have bad performance or something else on certain environment - right now we have various compilation issues with MinGW, Cygwin, OS X, MSYS and VS. People who are interested in resolving these issues are working on patches. Documentation is not always up-to-date (i.e. we've just updated it to reflect possible issues on older OS X versions). You (or anyone else) are free to research the issue and make a pull request with necessary patches.

**Comment by ifreund** [comment]
Also remember that you can always have homebrew build it for you. Just
```
brew install cataclysm --HEAD
```

**Comment by micage** [comment]
Thanks for your comments, guys. I had no problems doing a build on OS X 10.11. I'm doing that on a daily base. The problem is that the versions get slower and I'm not able to build it with optimizations. But I will continue to try. Just wanted to know if anyone has some useful insights.

**Comment by micage** [comment]
News! It's possible to build cataclysm-tiles with all optimizations (Os, O1, O2, O3) on OS X 10.11.6.
I managed to successfully do that with g++-8 [(hpc.sourceforge.net)](http://hpc.sourceforge.net/).
With brew: `brew install gcc@8` (be prepared that this takes a while). Now the performance is comparable to the windows version. Yikes!
