### ISSUE TITLE
Upgrading faction camp puts buildings into vehicles

### ISSUE THREAD

**Issue by RarkGrames** [CleverRaven/Cataclysm-DDA#30691]
# Describe the bug

Recovered an NPC from the faction_base_camp_5 mission, and had a car parked at the place of the second tent. When the tent appeared, it fused with the car.

# Steps To Reproduce

1. Park a car on the second tent place.
2. Finish the mission.

# Expected behavior

Warning that a vehicle is in the way.

# Versions and configuration

- OS: Windows [64-bit]
- Game Version: 0.D-3251-gba376ea
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Boats [boats],
    No Filthy Clothing [no_filthy_clothing]
]

**Comment by l29ah** [comment]
Also creating a faction camp in a vehicle results in the vehicle vanishing: 
[2019.07.22.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3429177/2019.07.22.zip)
