### ISSUE TITLE
Crafted soda can stove kit only accepts one ammo type

### ISSUE THREAD

**Issue by GrandpuhTy** [CleverRaven/Cataclysm-DDA#30709]
# Describe the bug

A crafted soda can stove kit does not accept any other fuel type listed under concentrated alcohol.

Methanol and ethanol claim to be usable in their descriptions for cookers that use concentrated alcohol but when trying to reload a crafted soda can stove kit it says that it requires denatured alcohol specifically.

When using a wished for soda stove it works as normal, accepting all three fuel types.

# Steps To Reproduce

1. Make a player with Survival 3, Cooking 3, Fabrication 3
2. Wish for mats to craft soda can stove kit
3. Craft stove kit
4. Wish for bottle of methanol, ethanol, and denatured alcohol
5. Attempt to reload with either methanol or ethanol and fail prompted for denatured alcohol
6. Reload soda can stove kit with denatured alcohol
7. Wish for soda can stove kit
8. Reload with either methanol or ethanol

# Expected behavior

Soda can stove kit should reload concentrated alcohols.

**Comment by jmattspartacus** [comment]
I've managed to replicate the issue, on the current experimental, my best guess at the moment is that it has to do with how liquid containers are created when crafting.
