### ISSUE TITLE
Unable to Launch Game

### ISSUE THREAD

**Issue by AbsurdRage** [CleverRaven/Cataclysm-DDA#30715]
# Describe the bug

I am currently unable to launch the game normally or through the launcher.

# Steps To Reproduce

Attempt to open the game,

# Expected behavior

Load in to the main menu.

# Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/50869490/58089979-c3f82180-7b8b-11e9-831a-0de6f03e4b6b.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-3275-g29e897c (tiles)
 - Graphics version: Tiles
 - Mods loaded: StatsThroughSkills, DisableNPCNeeds, MakeShiftItemsMod, MoreSurvivalTools, MundaneZombies, NoFilthyClothing, SimplifiedNutrition, think that's it.

# Additional context
I do have a fairly large Save Directory, and was actually in that game when I believe the update went through. My PC actually crashed (GREEN screen of death??), and after reboot I was unable to open the game through the launcher as I normally do. I updated (through the launcher) and then updated the launcher itself, both actions having no effect on my ability to play. I get the same error message every time, and I took a screen shot as I was also unable to copy paste the exact message.

**Comment by ZhilkinSerg** [comment]
Is it crashing on loading savegame or even before showing main menu?

**Comment by AbsurdRage** [comment]
Before main menu :(

**Comment by ZhilkinSerg** [comment]
Try to backup and clear your config folder and see if it helps to show main menu.

**Comment by AbsurdRage** [comment]
Okay! Thanks

**Comment by AbsurdRage** [comment]
Hey hey, it worked!

**Comment by ZhilkinSerg** [comment]
Great!

**Comment by AbsurdRage** [comment]
Thanks a lot! I can't go like more than an hour without fiddling a little
bit. I'm absolutely hooked....love this game :D
