### ISSUE TITLE
Crafting menu does not take into account ANY items on the tile you are standing on

### ISSUE THREAD

**Issue by EternalHunter777** [CleverRaven/Cataclysm-DDA#30722]
# Describe the bug
Crafting menu does not take into account ANY items on the tile you are standing on.
For example, stand on your spare parts tile, and none of those components will be found for crafting. Stand on your tools tile and same thing.

# Steps To Reproduce
Drop items for whatever recipe on the floor, stand on the tile, enter crafting menu and you will see all red (not available) components.

# Expected behavior

Any items on the tile you are standing on should be taken into account when crafting.

# Versions and configuration
- OS: Windows [64-bit]
- Game Version: 0.D-3304-gc5fd74f
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mutant NPCs [mutant_npcs],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Boats [boats],
    Disable Religious Texts [no_religious_Texts]
]

**Comment by ifreund** [comment]
I know what the fix is for this, will get to it soon.

**Comment by Leosky** [comment]
The issue is a bit different, tools on your tile can't be used to craft. I guess you can't use recipe you are standing on too but i don't have book on my current play.
