### ISSUE TITLE
Make railroad tiles more natural and fix "center" tile for track on railroad tie.

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#30728]
**Is your feature request related to a problem? Please describe.**  
Railroad tracks, in my opinion, has really huge gap between ties. Also "track on tie" tile connects with any railroad tile so it always surrounded by connecting tiles so it presents incorrect graphics.

**Describe the solution you'd like**  
I am asking to consider changing layout of railroad track so it would look better with tilesets.
Here screenshots of pair of railroads. Right one i edited to present to you how i think it should be. Left one is vanilla railroad. Looks kinda broken.
![scr1](https://user-images.githubusercontent.com/37592026/58113104-846a1d80-7bfd-11e9-9b37-8114137bafac.png)
![scr2](https://user-images.githubusercontent.com/37592026/58113143-9481fd00-7bfd-11e9-8925-c9b57a18daae.png)

**Comment by SomeDeadGuy** [comment]
Nope.

**Comment by kevingranade** [comment]
Yep
