### ISSUE TITLE
Chemical Imbalance can make you Warm and Chilly at the same time.

### ISSUE THREAD

**Issue by ErdrickXLII** [CleverRaven/Cataclysm-DDA#30733]
# Describe the bug

Presumably because there's no specific logic written for it, the Warm and Chilly effects are not mutually exclusive.  This allows particularly bad rolls from Chemical Imbalance (and potentially other edge cases) to give you both of them simultaneously.

# Steps To Reproduce

1. Have the Chemical Imbalance trait.
2. Wait a very long time :). (It took about 34 in-game days for the random effect rolls to give me both effects close enough together to notice it could happen.)

# Expected behavior

Gaining Warm while having Chilly should cancel both, and vise versa.  Alternatively, gaining Warm while having Chilly should replace Chilly with Warm, and vise versa.

# Versions and configuration

 - OS: Windows
 - Game Version: 0.D-2638-gd09a0d2
 - Graphics version: Tiles
 - Mods loaded: dda, Disable NPC Needs, StatsThroughSkills, Bionic Slots

**Comment by Zireael07** [comment]
There are situations IRL (usually being very sick) that can make you feel both warm and chilly, and chemical imbalance being what it is, I think it's legit.

**Comment by ifreund** [comment]
I'd say that behavior sounds accurate for what chemical imbalance is, but I'm not sure if it was originally intended.  Investigating may reveal corner cases in the code.

**Comment by ErdrickXLII** [comment]
Honestly, and I forgot to mention this in the original post, I was just reporting it because it looked silly in the context of how Warm and Chilly are usually applied to the player (external physical forces), and also that it didn't seem right, at first, to be able to give you double the speed penalty for what is basically the same effect twice.  It's so uncommon for it to happen, though, and, as mentioned, it does fit into the purview of what Chemical Imbalance is, that it's probably fine.

**Comment by kevingranade** [comment]
This seems fine as it is.
