### ISSUE TITLE
Full world regeneration on reload save.

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#30735]
# Describe the bug

Full world regeneration on save reload. Issue seems to be Save got corrupted mid-creation. Character is 44+ days old and on previous game: established base. Saved and Quit and reloaded save and was dumped into middle of a lake in a completely regenerated world.

# Steps To Reproduce
Not sure how to replicate seeing that I S&Q to IRL and when reloading the save: was dumped into the middle of a lake. Used Debug menu to teleport to shore to prevent drowning and revealed map overlay to ensure that my base wasn't nearby but the entire map was regenerated. Not sure what to think about what happened. No visible error screens appeared either while game was loading.

# Screenshots
Character on respawn standing in middle of lake.
![help](https://user-images.githubusercontent.com/43046067/58127222-e1a4a580-7be2-11e9-845a-9fc2206d7453.png)

# Versions and configuration
- OS: Windows [64-bit]
- Game Version: 0.D-3304-gc5fd74f
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Craftable Gun Pack [craftgp],
    Safe Autodoc [safeautodoc],
    Bright Nights [brightnights],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs],
    Crazy Cataclysm [crazy_cataclysm],
    Alternative Map Key [alt_map_key],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Boats [boats],
    Disable Religious Texts [no_religious_Texts],
    No Antique Firearms [no_olg_guns],
    No Flaming Weapons [no_flaming_weapons],
    StatsThroughSkills [StatsThroughSkills],
    Sleep Deprivation [sleepdeprivation],
    Filthy Clothing [filthy_morale]

# Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3204312/config.zip)

Save inside is made using the debug menu to get to shore before drowning and revealing the map overlay to see if my base was nearby or map was regenerated:  
[Frozen Waste I.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3204298/Frozen.Waste.I.zip)

**Comment by ZhilkinSerg** [comment]
Unfortunately we can't help with corrupted saves. Most of reported savegame corruptions were caused by faulty environment (power went off unexpectedly and such).

We suggest you to make savegame backups frequently (manually or using launcher).

**Comment by evankimori** [comment]
Fair enough, just thought the data would be of some use is all. Closing since there's nothing really that can be done. :)

**Comment by ZhilkinSerg** [comment]
If savegame is corrupted there is nothing in it which would indicate the reason it was corrupted.

**Comment by evankimori** [comment]
Noted for future then in case this happens again! Thanks for the input! :)
