### ISSUE TITLE
Light Survivor Body Armor missing OUTER flag.

### ISSUE THREAD

**Issue by carloslopez567** [CleverRaven/Cataclysm-DDA#30743]
# Describe the bug

Light Survivor Body Armor missing OUTER flag.

# Steps To Reproduce

1. Equip or view Light Survivor Body Armor

# Expected behavior

Body armor is usually worn on the outer layer. Causes extra encumbrance since it overlaps with Normal Layer.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

Build 9021

**Comment by chriseich21** [comment]
I believe this is actually intended, if you check all of the other armor items they are also marked as NORMAL layer, not OUTER. Light survivor suit is also marked as NORMAL

**Comment by TechyBen** [comment]
Ah. Yeah. This is an armoured normal layer/clothing then. As supposed to a seperate outer armour (such as a jacket/vest).

**Comment by carloslopez567** [comment]
Ahhhh. Well, I feel like an idiot. Thank you all. Just though since when I wore body armor, it'd be outside my shirt haha.
