### ISSUE TITLE
Known recipes and read books not saved

### ISSUE THREAD

**Issue by Koalabog** [CleverRaven/Cataclysm-DDA#30744]
# Describe the bug

Read books and recipes don't appear to be saved or loaded properly
Happened first when updating to build 9021 through launcher and it deleted the entire game instead. I used a settings file from an old backup but that probably shouldn't cause this issue?

# Steps To Reproduce

1. Read a book and craft something from it until you memorize the recipe
2. Save and close game
3. Load
4. I would now be presented with a red book title and not having the recipe memorized

# Expected behavior

A less forgetful character

# Screenshots

All the books i have from various places and definitely read
![image](https://user-images.githubusercontent.com/41955378/58148253-4d782400-7c5e-11e9-8e12-3a5c03b5a0a6.png)
When searching "Storage" in crafting menu
![image](https://user-images.githubusercontent.com/41955378/58148295-74365a80-7c5e-11e9-9aa7-d0c817da40bd.png)

# Versions and configuration

- OS: Windows [64-bit]
- Game Version: 0.D-3321-gdec03b2
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Weapon fixes [variousweaponfixes],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Boats [boats],
    Craft Ammo Mags & Belt Links [SD_Magcrafting]
]

**Comment by EternalHunter777** [comment]
Same issue here with build 9025, reverted back to 9020 where it's working as intended.
Hope you didn't save in the new build, or backed up your saves, otherwise you got alot of reading to do.

**Comment by ifreund** [comment]
Looks like this is most likely caused by #30708

**Comment by Dekker3D** [comment]
Possibly related: I forgot all my missions, including any that I'd finished before.

**Comment by Koalabog** [comment]
From what i can tell selected martial art is also not saved as it resets to "No Style" every time i load

**Comment by ifreund** [comment]
Found the issue, will push a fix soon

**Comment by IvanShestakov** [comment]
@ifreund  I'm still getting the issue with latest version (which includes commit ed96404b6edf6595aa72da2f5026700b365aab73). Linux, built from source using `make clean && make -j4 CCACHE=1 TILES=1 SOUND=1 LUA=0 LOCALIZE=0 RELEASE=1 ASTYLE=0` command.
The books aren't read anymore - but the auto-learned recipes don't show: specifically for character which started with 4 electronics and could create EMP grenades from hour 0.

**Comment by ifreund** [comment]
Can't confirm this. Just made a new character with electronics 5 and the auto learn recipes persisted through a save and load.  It's possible that loading and saving the game while this bug was in effect could have deleted some data, but there's nothing that I can do about that.

**Comment by IvanShestakov** [comment]
Thanks for checking this out. Sad that I can't continue with this character then :( as it doesn't have the recipe shown - even though I've got the book with EMP grenade recipe... I made sure it isn't hidden or something. Just isn't there.

**Comment by Randonx** [comment]
I noticed that too Ivan.  My character can't make several electronics that he could before, even with the same books I had.
