### ISSUE TITLE
"Stand next to me" NPC command.

### ISSUE THREAD

**Issue by Dekker3D** [CleverRaven/Cataclysm-DDA#30747]
**Is your feature request related to a problem? Please describe.**  
My NPC, let's call her Kate because I forget her name, likes to punch things. She *really* likes to punch things. This is fine, as I like to slash things with my nodachi and we make a terrific team when we're standing on one side of a doorway or standing next to each other and slaughtering zombies. And then she goes ADHD and runs right into the zombie horde because she wants to flank the one I'm killing, and I end up running after her and we both die for stupid reasons and I savescum. Or I tell her not to engage targets so she'll stay at a safe place, but then she won't attack anything even when standing still and being bitten.

I'm certain I saw and actually used a "yell at everyone to flee" command before, but it seems to be gone now.

**Describe the solution you'd like**  
I would like to be able to tell Kate to stay next to me. Within 1 tile distance, and ideally to my side (so we can re-murder zombies together). None of the current commands seem to really cover this. I would also like to have the "flee dammit" command back. Some others on Discord suggested it would be nice to tell one NPC to stay next to another NPC as well, allowing rudimentary formations to be formed. Surely you understand the importance of having a gang of survivors go all *testudo* on a hospital full of zombies.

![](https://upload.wikimedia.org/wikipedia/commons/a/ac/Testudo_formation.jpg)

**Describe alternatives you've considered**
A flee command would at least keep her from getting herself killed. She could smack some zombies around, run in too far, I tell her to flee and she withdraws again.

Situational awareness would prevent all of this from being necessary, but that's too much to ask of a game AI.

**Comment by esotericist** [comment]
> I'm certain I saw and actually used a "yell at everyone to flee" command before, but it seems to be gone now.

The "yell at everyone to flee" command was basically just invoking what is now called "follow_close" in the temporary orders. The behavior hasn't actually changed, it's just better labelling what it actually does. you can still give that order and they'll follow you if you get more than ~ 5-6 tiles away, so it can still be used for fleeing.

If you combine that with the new command to not engage hostiles, they definitely won't try to take attacks while you're following you (admittedly at that 5-6 tile distance).

This is basically the equivalent of the old 'flee' command, but actually works to force the NPCs to not try to stop and shoot or whatever:
![image](https://user-images.githubusercontent.com/1569754/58205884-61d71380-7c94-11e9-9997-c002aa2f530b.png)


We have someone working on a "follow very close" variant which should get you something closer to what you want.
