### ISSUE TITLE
Professions aren't saved when loading character templates

### ISSUE THREAD

**Issue by FrancisDec** [CleverRaven/Cataclysm-DDA#30741]
When you save a character template and load it, you will end up in the evac shelter as a survivor regardless of which scenario or profession picked.

1. Create a character in a scenario that isn't evacuation and profession that isn't survivor
2. Save the template
3. Load the template

Should create a character with the scenario and profession picked for the saved template

 - OS: Windows 10 LTSC
 - Game Version: 0.D-3321-gdec03b2
 - Graphics version: Tiles
 - Mods loaded: [dda, Disable NPC Needs]

**Comment by Nickmarez** [comment]
Experiencing the same issue

**Comment by YukariMindGap** [comment]
Also, points differences in professions aren't saved, too.

**Comment by Leosky** [comment]
scenario is ignored too

**Comment by Leosky** [comment]
should be fixed in https://github.com/CleverRaven/Cataclysm-DDA/commit/ed96404b6edf6595aa72da2f5026700b365aab73

**Comment by ifreund** [comment]
Fixed by #30778
