### ISSUE TITLE
Error from getting out of a destroyed vehicle

### ISSUE THREAD

**Issue by YukariMindGap** [CleverRaven/Cataclysm-DDA#30753]
# Describe the bug

When i try to exit a destroyed vehicle (Vehicle originally not destroyed when i get in), there's an error about a vehicle not found. I think it's connected to the destruction of the vehicle seat while the player is driving on it.

# Steps To Reproduce
1. Spawn a vehicle
2. Destroy the vehicle utterly so its driver seat is destroyed, too (Driving it off the roof is the easiest way.
3. Try to dismount.

# Expected behavior

I dismount successfully with no errors

# Screenshots
![image](https://user-images.githubusercontent.com/39007766/58187626-53fbaf80-7ce1-11e9-86d9-5816c54ee603.png)

# Versions and configuration
- OS: Windows [64-bit]
- Game Version: 0.D-3343-g3f52a39
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Bens GF recipes [Tolerate_This],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Extended Realistic Guns [realguns],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    Boats [boats],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Classes and Scenarios Mod [more_classes_scenarios],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by ifreund** [comment]
I'm fairly sure this only happens when driving off a roof as was mentioned in #30613

**Comment by irwiss** [comment]
Can't reproduce on f5b184f046f852449e4a19a7cdaca12efef72c2b looks like it's handled in remove_part calling RemovePartHandler::unboard
https://github.com/CleverRaven/Cataclysm-DDA/blob/4840ee2e553ca74e14f3bbd624750cc51766ec8f/src/vehicle.cpp#L1858-L1861
