### ISSUE TITLE
Ferromagnetic projectiles are too heavy.

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#30750]
**Is your feature request related to a problem? Please describe.**  
One steel rail has a weight of 0.52 kg and volume of 0.03l, both numbers are too high. Even if we keep the volume value of 0.03 l, the weight then should be 7800*0.00003=0.234 kg (where 7800 kg/m3 is the density value of steel). But 0.03l volume is still too high, that projectiles should be  0.01l or even less (if it is possible to set that value in game). Maybe 0.005l, I think. 
Same with rebar rails.

**Describe the solution you'd like**  
Adjust steel and rebad rails volume and weight so thay don't violate laws of physics. Also adjust crafting quantyty to meet law of preservation of mass.

**Describe alternatives you've considered**  
None. Physics law violation is punished by death.

**Additional context**  
This 50 ml syringe can be good visual reference to a possible ferromagnetic projectile size.
![50 ml syringe](https://ae01.alicdn.com/kf/HTB1Y0FSRFXXXXcwXXXXq6xXFXXXC/50-ml-en-plastique-jetable-injecteur-Animal-seringue-oiseau-seringue-laboratoire-mesure-mangeoire-pour-Animal-domestique.jpg)

**Comment by eilaattwood** [comment]
Also I can't see a reason not to add ferromagnetic projectiles to rifle bandoliers accepted ammo list. They have corresponding shape and are used in the actual rifle - ferromagnetic rail rifle.

Also, why that projectiles are called rails in the game? Rails performs a function of a barrel in the rifle. Projectiles are just cylinder pigs, not rails.

**Comment by TechyBen** [comment]
Perhaps they were thinking of "rod" and put rail instead? "Rod" for the projectiles makes sense. As to size, it depends on what type of weapon and it's strength/stats. But I can agree the weight/etc could be adjusted to make it fairer (more realistic!).

If the weight/size is a balance concern after the change, the damage could be reduced or alternatively the power requirement from the UPS increased, per shot (as speed vs weight scales rather well for a projectile).

**Comment by eilaattwood** [comment]
Looks like "count" and "stack_size" values from ammo definition are ignored for ferromagnetic projectiles for some reason. Ammo definition says that 0.52 kg is the weight of 10 rods, but game ignores that and sets a single rod weight to 0.52 kg.

**Comment by anothersimulacrum** [comment]
> Ammo definition says that 0.52 kg is the weight of 10 rods, but game ignores that and sets a single rod weight to 0.52 kg.

The weight defined in JSON for something with charges is for one charge. It's possible that the person who created these believed that it was for the whole stack, not just one charge.

**Comment by eilaattwood** [comment]
> The weight defined in JSON for something with charges is for one charge. It's possible that the person who created these believed that it was for the whole stack, not just one charge.

So why this is working for nails, but not working for ferromagnetic rods? Also, documentation says:
 
`"weight" : 350,                   // Weight of the item in grams. For stackable items (ammo, comestibles) this is the weight per charge.`
`"volume" : 1,                     // Volume, measured in 1/4 liters. For stackable items (ammo, comestibles) this is the volume of stack_size charges. Volume in ml and L can be used - "50ml" or "2L"`

**Comment by Greevv** [comment]
Seems like an easy fix, I'm on it.

**Comment by RarkGrames** [comment]
> Also, why that projectiles are called rails in the game? Rails performs a function of a barrel in the rifle. Projectiles are just cylinder pigs, not rails.

Yes, the projectile runs on the rails, like a train. The projectile having this name is confusing. The word "rail" implies that the long piece of metal is resting on something and an other thing runs on top of it, like railroad rail or handrail. I couldn't even find a definition in any better dictionary that suggests that it is a long piece of metal by itself, without attached to anything.

**Comment by eilaattwood** [comment]
> Yes, the projectile runs on the rails, like a train. The projectile having this name is confusing. The word "rail" implies that the long piece of metal is resting on something and an other thing runs on top of it, like railroad rail or handrail. I couldn't even find a definition in any better dictionary that suggests that it is a long piece of metal by itself, without attached to anything.

It should be called 'slug' or 'rod', I think.

**Comment by RarkGrames** [comment]
To be honest I'm not sure. I'm not a native english speaker, but for me both slug and rod implies that they are blunt at the end, and the description says it has been sharpened. With the current description I would call them simply projectiles.

After doing a little bit of research it seems that anything made of ferrous metal can be used with these (they even tried to shoot mortar shells from these in experiments), so if you straighten up a piece of rebar and load it in, I would call that a slug or a rod.

**Comment by TechyBen** [comment]
For the game, yes it is sharpened. But in general, it could fire anything metal. :)
Seems reference to them in Wikipedia is just "projectile" as you say.

**Comment by eilaattwood** [comment]
> 
> 
> For the game, yes it is sharpened. But in general, it could fire anything metal. :)
> Seems reference to them in Wikipedia is just "projectile" as you say.

And sometimes even non-metal (so-called plasma slug, when the projectile itself is non-conductive, but has thing conductive layer sprayed on the bottom. When railgun fires, that layer evaporates and forms plasma coating behind the non-conductive projectile. And plasma is actually decent conductor, so it's still affected by the Lorentz force, pushing the projectile forward.) ;)
