### ISSUE TITLE
Ridable shopping carts

### ISSUE THREAD

**Issue by 2birdie** [CleverRaven/Cataclysm-DDA#3076]
Shopping carts are great.
You know what would make them greater? Getting a good running start, hopping in and cruising down the street, hacking away at the horde of the undead/catching your wheels on a rock and doing three frontflips before landing facedown in the middle of two spitter zombies.

Also, being able to reach down with a long object like a stick to push yourself along would be nice.

**Comment by kevingranade** [comment]
I don't see a reasonable way to implement this, if someone has one please reopen.
