### ISSUE TITLE
Lookaround from monster list moves cursor in some situations

### ISSUE THREAD

**Issue by BTAxis** [CleverRaven/Cataclysm-DDA#30779]
# Describe the bug

Pressing x for look around from the monster list (Shift+V) sometimes results in the cursor moving one square to the left. This only seems to happen when the monster in question is eastward from the player.

# Steps To Reproduce

1. Find some monsters or other listable creatures. Try to have some both east from the player and west from the player.
2. Enter the monster list with Shift+V.
3. Hit x to enter lookaround mode. If the cursor was east from the player it should move one tile to the west. If it was west from the player, it will not do so.

# Expected behavior

The cursor should remain over the selected creature in all cases.

# Versions and configuration

- OS: Windows 10 Pro [64-bit]
- Game Version: 0.D-3241-g5372d73b8d
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Filthy Clothing [filthy_morale],
    Simplified Nutrition [novitamins],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Locations [more_locations],
    Boats [boats],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Makeshift Items Mod [makeshift]
]

**Comment by esotericist** [comment]
I'd swear I fixed this bug once before already...
