### ISSUE TITLE
Crash when accepting quest

### ISSUE THREAD

**Issue by LyuKalev** [CleverRaven/Cataclysm-DDA#30776]
# Crash when excepting quest

When excepting a quest form NPC error occurs and game crashes to desktop: 
"DEBUG: Requested non-existing faction" 

# Steps To Reproduce

**Take quest from NPS with dialog:**
"We've got another problem to deal with but I don't think we can handle it on our own. So, I sent word out and found us a volunteer... of sorts. He's vain as hell but a little skill with firearms. He was supposed to collect whatever he had of value and is going to meet us at a cabin in the woods. Wasn't sure how long we were going to be so I told him to just camp there until we picked him up."

**Mods installed:**
- Disable NPC Needs
- Bionic Slots
- Classes and Scenarios Mod
- Sleep Deprivation
- StatsThroughSkills
- Medieval and Historic Content
- Makeshift Items Mod 
- Hydroponics
- Mutant NPCs

# Screenshots
https://drive.google.com/file/d/1pWyN9NOr-oXrNekWiaZb2zxrr8BPpWr0/view?usp=sharing

**Comment by ZhilkinSerg** [comment]
Please report game version you are on. Make sure you've updated to latest version.

**Comment by Jullan-M** [comment]
Okay, so I've found a way to reproduce it on the latest build (9044):
1. Load a character with a NPC conveniently close by.
2. Make the NPC your follower and give them the "Recruit Tracker" mission with the debug menu.
3. Accept the mission and observe the debug message.
`src/faction.cpp:319
[faction* faction_manager::get(const faction_id&)]
Requested non-existing faction ''`

I'm aware that managing missions on the debug menu is slightly unstable, but this has happened "organically" to me before for one of my main characters.

**Comment by LyuKalev** [comment]
BUILD:  9052
Also update the issue on github,

На чт, 23.05.2019 г. в 15:07 ч. ZhilkinSerg <notifications@github.com>
написа:

**Comment by cozardi** [comment]
I've had the same thing happen, same mission and nonexistant faction

**Comment by ZhilkinSerg** [comment]
Does not reproduce on current master using debug menu and also no similar complaints for a while. There were a lot of changes to NPC and factions since May, so it was probably fixed. Please ping me to reopen if you still having this issue.
