### ISSUE TITLE
Bark Shield

### ISSUE THREAD

**Issue by faefux** [CleverRaven/Cataclysm-DDA#30789]
https://www.theguardian.com/science/2019/may/23/2300-year-old-iron-age-bark-shield-leicestershire

>Bark shields of the period were entirely unknown in the northern hemisphere, he told the Guardian, and the assumption was that the material may have been too flimsy for use in war. However experiments to remake the weapon in alder and willow showed the 3mm-thick shield would have been tough enough for battle but incredibly light.

>The shield is made from green bark that has been stiffened with internal wooden laths, described by Beamish as “like a whalebone corset of split hardwood”, and surrounded by a rim of hazel, with a twisted willow boss. “This is a lost technology. It has not been seen before as far as we are aware, but presumably it is a technique that was used in many ways for making bark items.”

This was super interesting,  Can i get some suggestions about how you would abstract the build materials for this in relation to what materials we have in the game?

**Comment by EirenexTheDragon** [comment]
Just wooden log, i say myself. and some cutting or wood sawing quality. should take as long as making a Bokken

**Comment by Rail-Runner** [comment]
All shields currently exist in Medieval Stuff mod. I considered mainlining them at some point, but since they're still not quite finished yet (don't help against ranged attacks, for instance), not sure if it'd be good.

**Comment by faefux** [comment]
Thanks, @Rail-Runner, If you ever mainline that give me a msg and i'll add the bark shield. :)
