### ISSUE TITLE
Jenkins builds aren't uploaded to the releases page anymore

### ISSUE THREAD

**Issue by Throwaway-name** [CleverRaven/Cataclysm-DDA#30796]
# Describe the bug

None of the builds after 9032 have appeared on the releases page.

# Steps To Reproduce

https://github.com/CleverRaven/Cataclysm-DDA/releases

# Expected behavior
Pre-built experimental games available on the releases page.

# Versions and configuration
N/A

Pinging @narc0tiq

**Comment by Nickmarez** [comment]
Looks like the builds are failing :(

**Comment by narc0tiq** [comment]
If the builds don't succeed, they won't make artifacts, and therefore won't show up on the releases page of the website.
