### ISSUE TITLE
MGOAL_FIND_ITEM missions with multiple item counts should allow partial completion

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#30849]
**Is your feature request related to a problem? Please describe.**  
MGOAL_FIND_ITEM quests that require multiple items to be found should allow you to hand in several items at a time. For example, if Jenny Forcette wants you to bring her 30 rifles, you should be able to give her 10 and have her accept them but not complete the mission until 20 more are brought.

This is a fairly minor issue, and would likely require a large fix, but it would smooth gameplay out for large fetch missions.

**Describe the solution you'd like**  
A new mission dialogue line for MGOAL_FIND_ITEM, "partial_complete". This line will be displayed if the player returns some but not all of the mission items. For example
`"partial_complete": "Thanks, these will do nicely... I still need more though.",`

When the player brings appropriate mission items to the NPC, they get the normal mission complete dialogue options, the items are taken, but if the item count isn't sufficient yet the NPC increments the number of items that have been brought back, displays partial_complete, and doesn't recognize the mission as completed yet.

**Additional context**  
Some of the missions I'm writing require a large number of bulky items that may be impossible to hold in the inventory simultaneously, which may cause problems with mission completion if this isn't doable.

**Comment by mlangsdorf** [comment]
The Tacoma Commune missions start with you collecting 200 two by fours, but you can just drop them off in the garage.  I can probably generalize that trick so that there is a faction tagged loot zone that the NPC will count for deliveries, which will probably be less hassle than partial completion.

I'll look at it soon.

**Comment by I-am-Erk** [comment]
this is something we can handle with EOC now
