### ISSUE TITLE
MGOAL_FIND_ITEM missions do not display COUNT in mission dialogue

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#30848]
# Describe the bug/issue

MGOAL_FIND_ITEM missions support COUNT as a property to create missions that require more than one item to complete. However, the Mission dialogue does not list how many items are required to finish the mission, which is likely to be a huge pain for players.

# Steps To Reproduce

1. Get a quest that requires you to find more than one item (playtest https://github.com/CleverRaven/Cataclysm-DDA/pull/30828 for a few sample missions from Dino Dave)
2. Check mission dialogue
3. You will only be told you need to "find small cardboard boxes" and not how many you need to find.

# Expected behavior

The mission dialogue should read "find (x) cardboard boxes" where (x) is the number.

# Screenshots

![image](https://user-images.githubusercontent.com/45136638/58372873-5c1e3f80-7ed9-11e9-9f4f-a13d175a8d34.png)

# Additional Context

I'm not sure if we simply haven't programmed this feature yet, or if it's expected behaviour that isn't working properly.

**Comment by mlangsdorf** [comment]
Mission descriptions are criminally underused.

**Comment by I-am-Erk** [comment]
Also true and applicable

**Comment by Petethegoat** [comment]
I'll look into this. Quests in general can be fairly painful to keep track of, and I'd like to make further UI improvements.

**Comment by I-am-Erk** [comment]
If you want further suggestions on how to improve the mission code, I have many.
