### ISSUE TITLE
Crash while sleeping. Assumed during interruption event.zip

### ISSUE THREAD

**Issue by antofdeath** [CleverRaven/Cataclysm-DDA#30846]
# Describe the bug

The bug occurs during a sleep state. Current variables, dead tired, multiple annoying bionics that can wake you up, radiation poisoning leading to vomiting (maybe?) and chemical imbalance. The timing of the event is inconsistent, as such is not created by the falling asleep or sleeping settings. Can not properly test a "well rested" sleep with this character. Tested "Exhausted" naps, and character will sleep then wake up without crash.

# Steps To Reproduce

Currently the simplest reproducability is to go to bed and sleep, which then triggers sleep scripts and leads to a crash.

# Expected behavior

I expect to actually sleep. 

# Screenshots

**If applicable**, add screenshots to help explain your problem.

N/A

# Versions and configuration

 - - OS: Windows [64-bit]
    - OS Version: 10.0 1809
 - Graphics version: Tiles
 - Mods loaded: Aftershock, Stats through skills, Disable NPC needs, then basically the entire list of items and content that came with this version.

# Additional context

[Crash while sleeping. Assumed during interruption event.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3219538/Crash.while.sleeping.Assumed.during.interruption.event.zip)

**Comment by anothersimulacrum** [comment]
Because this appears to be a result of interruptions while sleeping, could this be related to #30830?

**Comment by neitsa** [comment]
Does it happens when you set an alarm or without an alarm? Haven't been able to repro yet.

**Comment by neitsa** [comment]
Ok got a crash after pressing that damn sleep key a lot :) Yep, It's from my PR... I should have checked if the effect is there before setting it's duration to 0... 😢 Fix on its way.
