### ISSUE TITLE
Unable to compile code using Code Blocks

### ISSUE THREAD

**Issue by Hymore246** [CleverRaven/Cataclysm-DDA#30855]
# Describe the bug

I am unable to compile code using when using Code Blocks. Trying to do so gives me the following errors:

> ||=== Build file: Release in Cataclysm (compiler: GNU GCC Compiler) ===|
> C:\Users\Mark\Documents\GitHub\Cataclysm-DDA\src\debug.cpp||In function 'std::__cxx11::string windows_version()':|
> C:\Users\Mark\Documents\GitHub\Cataclysm-DDA\src\debug.cpp|1014|warning: '__stdcall__' attribute only applies to function types [-Wattributes]|
> C:\Users\Mark\Documents\GitHub\Cataclysm-DDA\src\debug.cpp|1014|error: expected ';' before '(' token|
> C:\Users\Mark\Documents\GitHub\Cataclysm-DDA\src\debug.cpp|1020|error: 'RtlGetVersion' does not name a type|
> C:\Users\Mark\Documents\GitHub\Cataclysm-DDA\src\debug.cpp|1024|error: 'union windows_version()::<anonymous>' has no member named 'p'|
> C:\Users\Mark\Documents\GitHub\Cataclysm-DDA\src\debug.cpp|1025|error: 'RTL_OSVERSIONINFOW' was not declared in this scope|
> C:\Users\Mark\Documents\GitHub\Cataclysm-DDA\src\debug.cpp|1026|error: 'os_version_info' was not declared in this scope|
> C:\Users\Mark\Documents\GitHub\Cataclysm-DDA\src\debug.cpp|1027|error: 'union windows_version()::<anonymous>' has no member named 'p'|
> ||=== Build failed: 6 error(s), 1 warning(s) (0 minute(s), 2 second(s)) ===|

This might be an issue with compiler settings. I am using the default setup with -std=c++11 as indicated in the [COMPILING.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING.md) doc but I have not had any luck compiling it with other settings.

# Steps To Reproduce

1. Using this [link](https://cddawiki.chezzo.com/cdda_wiki/index.php?title=How_to_compile), follow the steps for creating a git clone and downloading and setting up CodeBlocks + MinGW.
2. Pull the most recent build of CDDA.
3. Using Code Blocks, open CataclysmWin.cbp in the git repository of CDDA.
4. Attempt to compile the entire project or just debug.cpp to see the error.

# Expected behavior
Freshly pulled code from Github should compile without any errors.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-3479-g3233182

**Comment by neitsa** [comment]
Can you try with `-std=c++14` and give us a feedback on whether you succeeded or not?

**Comment by Hymore246** [comment]
I tried with -std=c++14 and I got the exact same errors.

**Comment by neitsa** [comment]
What is your gcc version? you can get it with `$ gcc --version`.

**Comment by Hymore246** [comment]
Using gcc 6.3.0-1

**Comment by ZhilkinSerg** [comment]
Let's just guard this code block for MinGW builds.

**Comment by nexusmrsep** [comment]
Can confirm, it's also seen in VSCODE:

![image](https://user-images.githubusercontent.com/39925111/58429693-fda6bc00-80a6-11e9-892a-fbcece157b47.png)

MinGW's winapi.h has the `#define WINAPI __stdcall` defined, but both PRTL_OSVERSIONINFOW and RTL_OSVERSIONINFOW are unrecognized ("indentifier ... is undefined").
Microsoft docs say that the dependency requirement is in `wdm.h (include Ntddk.h)` but I have no idea if this should be included separately (I guess not) or via MinGW's own winapi.h (which it does not apparently.
Tried to follow the lacking dependency further, but that's way out of my field of expertise at this point.
Wanted to test if MinGW upgraded to gcc8.2 would fix that but that upgrade is a task on its own for someone who is not a pro in this department, like me.
