### ISSUE TITLE
Zombie evolution ignores MONSTER_WHITELIST

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#30851]
# Describe the bug

If MONSTER_WHITELIST is used to limite monsters to a specific category only they can still evolve into monsters out of this category.

# Steps To Reproduce

1. Create a mod with following contents
```
{
    "type": "MONSTER_WHITELIST",
    "categories": [ "CLASSIC" ]
}
```
2. (optional) Teleport to a city. You will see that only monsters from "CLASSIC" category are spawning.
3. Move time forwards.
4. Go to a city. You will find monsters that do not belong to the "CLASSIC" category.

# Expected behavior

Zombies do not evolve into non whitelisted types.

# Versions and configuration

- OS: Windows [64-bit]
    - OS Version: 10.0 1803
 - Game Version: 9052
 - Graphics version: Tiles
 - Mods loaded: The one given above.

# Additional context

Blacklisting works. Zombies do not evolve into monsters that are blacklisted.

**Comment by Hirmuolio** [comment]
After looking around more I stubled upon `"mode": "EXCLUSIVE",` on another mod.
Using that makes everything work as expected.

Makes me think that MONSTER_WHITELIST used above shouldn't stop the initial spawning of special zombies at all witout `"mode": "EXCLUSIVE",`.

All of this undocumented too BTW.

**Comment by Night-Pryanik** [comment]
This is working as intended. `MONSTER_WHITELIST` _without_ `"mode": "EXCLUSIVE"` just allows spawning of monsters blacklisted by any other mods. `MONSTER_WHITELIST` _with_ `"mode": "EXCLUSIVE"` correctly permits spawning only whitelisted monsters.
