### ISSUE TITLE
Game crashes after "Tileset" stage of loading (build 9055)

### ISSUE THREAD

**Issue by FirebrandCoding** [CleverRaven/Cataclysm-DDA#30875]
# Describe the bug

Game crashes after the "Tileset" stage of the "Finalizing" part of loading. Happened on build 9055 (latest at the time of the error). Build 9051 had the same error eventually, though it was playable for a while. No particular thing – enemy, item, action – seems to have triggered it.

As it seems to be related to the tileset, I tried updating the one I use (DeadPeople) manually from Github, to no avail.

Tested on previously-existing worlds with characters in, and on two testing worlds: one with CDDA core, Disable NPC Needs, Aftershock, and Magiclysm, and one with CDDA core and Disable NPC Needs. Previous worlds had error messages that never led to crashes before (like missing crafting recipes from using No Medieval Items mod), testing worlds had no error messages.

# Steps To Reproduce

1. Use or create any world
2. Try to load the world
3. Wait until it's been a few seconds doing the "Tileset" part of loading
4. See the game crash with the aformentioned errors

# Expected behavior

Game should've loaded, as it did many other times, with many other builds, under very similar circumstances.

# Screenshots

—

# Versions and configuration

 - OS: Windows 10 Enterprise LTSC, version 1809, build 17763.292
 - Game Version: 0.D-3508-gf4c1c1c
 - Graphics version: Tiles
 - Mods loaded: tested on multiple worlds/mod stacks:

	* last working world (crashes currently): dda, no_npc_food, aftershock, magiclysm, adv_gear, More_Survival_Tools, alt_map_key, mutant_npcs, more_locations, FujiStruct, cityside, DP_No_Debug_Tile, DP_REMIX_INDICATORS, sarcophagi_access, no_olg_guns, no_medieval_items, no_flaming_weapons, Mundane_Zombies, No_Anthills, No_Bees, No_Fungi, manualbionicinstall, Mutation_Changes, no_filthy_clothing, no_reviving_zombies, safeautodoc, novitamins, StatsThroughSkills
	* fuller testing world: dda, no_npc_food, aftershock, magiclysm
	* empty testing world: dda, no_npc_food

# Additional context

[crash_save_Starrucca.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3220151/crash_save_Starrucca.zip)

[crash+debug.log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3220152/crash%2Bdebug.log.zip)

Unfortunately, I'm unable to assess whether it's close to the crash conditions. It crashed when I was walking west out of the city I was in through the field behind some houses. Nothing unusual happened right before the crash.

**Comment by Night-Pryanik** [comment]
@FirebrandCoding is still an issue?

**Comment by FirebrandCoding** [comment]
Negative, since very soon afterwards. Thanks for reminding me; this issue should be closed.
