### ISSUE TITLE
New "Alcatraz" Prison island can spawn too close of main land

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#30887]
# Describe the bug
I created a new world with the "Alcatraz" Prison start and I was expecting it to be far from main land.

# Steps To Reproduce
Not sure how to force this specific map creation (if even possible).

# Expected behavior
"Alcatraz" should be at least a few-several tiles from any kind of land.

# Screenshots
![image](https://user-images.githubusercontent.com/1426680/58388232-962f3480-7ff2-11e9-918f-62b9393e06fd.png)

![image](https://user-images.githubusercontent.com/1426680/58388234-98918e80-7ff2-11e9-9c1b-1ba75979eae1.png)

# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.D-3509-ge10d164]
 - Graphics version: Tiles
 - Mods loaded: Alternative Map Keys, Mutant NPCs

**Comment by ralreegorganon** [comment]
The fix here is to add a ring of `lake_surface` locations to the special definition (e.g. is lake surface and can only be placed on lake surface) which will ensure that padding is present when the game is attempting to place the location.

**Comment by TechyBen** [comment]
[Just realises Laks + Alcatraz is a thing in this game now] :O
