### ISSUE TITLE
Crash while building

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#30883]
# Describe the bug
Game crashes when performing building actions when fungaloids are around. (Possibly related to interrupts?)

# Steps To Reproduce

1. Load save file provided.
2. Try to bury sealed coffin.
3. Get a crash. If not, repeat some building actions like falling a tree or building something.

# Expected behavior

No crash.

# Screenshots

N/A

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-3509-ge10d164 (build 9056)
 - Graphics version: Tiles
 - Mods loaded:   "dda",  "no_npc_food",  "aftershock",  "realguns",  "More_Survival_Tools",  "makeshift",  "craftgp",  "growable-pots",  "modular_turrets",  "mutant_npcs",  "alt_map_key",  "hydroponics",  "more_locations",  "FujiStruct",  "Urban_Development",  "boats",  "blazemod",  "deoxymod",  "Tanks",  "DP_REMIX_INDICATORS",  "MMA",  "safeautodoc",  "no_reviving_zombies",  "more_classes_scenarios",  "StatsThroughSkills"

# Additional context

[Оттаму.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3221065/default.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3221068/debug.log)

**Comment by AMurkin** [comment]
Nice repro case. Thanks for the savefile.
Did my attempt to fix a crash.
