### ISSUE TITLE
New Aura equipment layer request 

### ISSUE THREAD

**Issue by foulman** [CleverRaven/Cataclysm-DDA#30897]
**Is your feature request related to a problem? Please describe.**  
There are a lot of useful functions that can be accomplished with the magic mod, but in making spells I have run into problems with because when I create "protection" from spells (typically a 0 enc, 0 vol, 0 weight suit or body part protection item), regardless of what layer of the body I put it on, it's going to conflict and create an encumbrance penalty even if the object has 0 encumbrance itself. 
I would love to have a spell of warmth for example, that just added a 0 enc/50 warmth layer, or 5 point acid protection layer, but with it supposedly just being some magic field protecting the player, instead they are slowed down when that doesn't make sense, it hampers the implementation of defensive abilities because I don't want to penalize the players nonsensically.

**Describe the solution you'd like**  
Optimally, what I would request is the addition of 2 additional Aura layers (or one Aura and one something else), one that is the last thing before your skin, and one that is the furthest thing outside of you. Neither would have encumbrance penalties or conflict with anything worn or even other auras layer items. This will also be useful for things like sci-fi style forcefields (which would be furthest out aura), which should be easy to do now with the coming items-casting-spells functionality.
Kevin and esotericist both indicated that it shouldn't be difficult to do at all, so I'm asking for two for maximum flexibility. In many cases it may be desired to have something be the first or last layer of defense, protecting your physical body (and not your gear) from acid is a lot different than growing bony magical armor outside to go toe-to-toe with Skeletal Juggernauts, 
I think all mod authors would prefer maximum flexibility and not be forced into giving more benefits than intended to the player, as the one working on spell and item content for Magiclysm I'm keenly trying to avoid that as we try to work out balance with the main game.

**Describe alternatives you've considered**  
Alternatively, the only other solution I can think of is the addition of a flag (NO_CONFLICT?) to specify that the worn item on that layer does not conflict with other worn items on that layer or create the encumbrance penalty. 

I feel my suggestion of two options provides the most long term and future-proof solution to providing this functionality as the game continues to grow, and I think a lot of current and future mod content would benefit from having them.

**Comment by Szara-ManOfHonor** [comment]
I think both options are full of merit, and the second can already be applied to some items ingame, though it brings up other suggestions, which I started to type and then decided it was getting a wee bit off topic so I think I'm just going to make another issue for it rather than run roughshod over this one.
