### ISSUE TITLE
Guns with multiple different magazine firing mods wont trigger if the main magazine is empty

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#30907]
# Describe the bug
When you have a gun like the Kel-Tec KSG and try to fire it while the main clip is empty you cannot fire the alternate fire modes no matter what, pressing fire prompts you with "you need to reload". 
Another related issue is if you fire the L523-MBR rifles grenade launcher you cannot fire a single shot from the rifle. You can still press shift F to burst fire but even changing firing modes in the firing menu to single shot will still cause you to fire a burst fire.

# Steps To Reproduce

1. Get a Kel-Tec KSG
2. Put ammo in the alternate magazine while having the main magazine empty
3. There's no way to fire the secondary magazine.

# Expected behavior
Being able to use all features of a gun reliably 

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-3509-ge10d164 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Folding Parts pack [deoxymod],
    Classes and Scenarios Mod [more_classes_scenarios],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA]
]

**Comment by foulman** [comment]
I was noticing this a month or so ago myself. If I recall correctly, you can actually hit 'F' to do this from outside the fire screen, however inside it, when you are actually trying to shoot the weapon, you cannot.
This obviously should not be the case.

**Comment by ThomasLinkin** [comment]
Tried it ,confirmed. Gotta unload the secondary magazine to reload the main in order to shoot,so i was talking to myself "if that's the case,then why do i even need that one for". Not until now did i realize it was a bug

**Comment by ymber** [comment]
I can't reproduce the bug described here in current master. The issue I noticed when testing is that the sidebar shows the fire mode for the current weapon but not whether it's the fire mode for a gun-type gunmod, so in the ksg case where the ksg and the gun-type gunmod that acts as its second magazine both have fire modes of semi-auto you cant tell which one you're trying to fire until you get into the aim screen, which you can't do if you're trying to fire the one with no ammo. I think the solution for this is for the game to check whether the gun or any gunmods are in a state where they can fire and bring up the aim screen if any are.
