### ISSUE TITLE
Negative-calorie food

### ISSUE THREAD

**Issue by BenlyAZ** [CleverRaven/Cataclysm-DDA#30904]
Crafting a food with high-calorie side products from low-calorie ingredients results in negative food. This happens for stewed tripe; I don't know if other recipes meet the requirements.

Steps to reproduce:
1: Craft stewed tripe from a large boiled stomach, two cabbages, salt and water. It produces four servings of 90-calorie broth and two servings of -15-calorie stewed tripe.

I guess expected behavior would be low-calorie broth and low-calorie tripe instead of high-calorie broth and negative-calorie tripe.

![negativetripe](https://user-images.githubusercontent.com/51046470/58439167-adc4f680-80a0-11e9-9058-5129feb60dcf.png)

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-3509-ge10d164 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mythical Martial Arts [MMA],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Disable Religious Texts [no_religious_Texts],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    StatsThroughSkills [StatsThroughSkills],
    Magiclysm [magiclysm],
    Cataclysm++ [Cata++],
    Bens GF recipes [Tolerate_This],
    Vampiric Stuff [vamp_stuff],
    Arcana and Magic Items [Arcana],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    No Fungal Monsters [No_Fungi]
]

**Comment by Reclusive-reptile** [comment]
The carton of chicken stock in my fridge says it has 5 Kcal per cup serving. If we nerf broth to 5 Kcal it should fix this.
