### ISSUE TITLE
Cannot produce webs inside vehicle

### ISSUE THREAD

**Issue by Fearen-sm** [CleverRaven/Cataclysm-DDA#30916]
I obtained web weaver mutation on a char and cannot sleep without webs. I have vehicle base with reclining seat for sleep but I cannot produce webs inside vehicle at all, so I now cannot sleep inside my movable base. I hardly can see reason not having the ability so spin webs inside vehicle if I want to.
Ok, I saw the reverse bug it seems #1092, guess it was fixed so now I have my problem.

# Steps To Reproduce

1. Have web weaver mutation
2. Try to make webs inside vehicle
3. Get too malnourished to keep going, but produce no webs

# Expected behavior

Have an ability to produce webs inside a car

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-3508-gf4c1c1c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Classes and Scenarios Mod [more_classes_scenarios],
    StatsThroughSkills [StatsThroughSkills],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots]
]

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10650. I got Web Weaver and I was able to successfully weave web in the vehicle.

![изображение](https://user-images.githubusercontent.com/11132525/184649732-7899a49a-3f9c-4fa4-83e2-41cccd17dfd9.png)
