### ISSUE TITLE
Open and close curtains (and doors maybe) in Vehicle info screen

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#30918]
**Is your feature request related to a problem? Please describe.**  
Recently found a luxury RV but I can't close some curtains on it as the spaces next to them are blocked by the fridge, table, etc.

**Describe the solution you'd like**  
To be able to open and close curtains in the (e)xamine vehicle screen. Maybe add doors to the list of things you can open and close in this screen and you are able to repair anywhere on the vehicle from here already makes sense to be able to open and close things.

**Describe alternatives you've considered**  
I have no mechanics skill so there is nothing I can do but leave them open for now.

**Comment by anothersimulacrum** [comment]
This is already possible if you install door motors over the curtains or windows.

**Comment by Zombiemanpig** [comment]
> This is already possible if you install door motors over the curtains or windows.

Why can't my 0 mechanics character just reach a bit to close the curtains instead?
