### ISSUE TITLE
Mouse mutants invisible to turrets

### ISSUE THREAD

**Issue by Kanexan** [CleverRaven/Cataclysm-DDA#30913]
With the Unassuming trait, turrets, milspec turrets, and secubots cannot see the player character, no matter the light level, until the player character is in a tile directly next to the turret/bot.

Expected behavior:
The turret notices and shoots at the player character at slightly below its standard viewing range, due to the stealth granted by Unassuming.
Actual behavior:
The turret cannot see the player character until said character is directly next to said turret.

1: Have a post-Threshold Diminutive character with the trait "Unassuming"
2: Approach a turret, milspec turret, or secubot, in any light level.
3: The turret will not be aware of you until you are directly next to it.

Screenshots:

![image](https://user-images.githubusercontent.com/51104434/58448185-b03d4580-80cc-11e9-989e-e271feed29a6.png)

![image](https://user-images.githubusercontent.com/51104434/58448198-bb907100-80cc-11e9-88ef-65fa0a97220a.png)

Versions and configuration:
 - OS: Windows 10
 - Game Version: 0.D-3534 and all previous versions since -2404, possibly longer.
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs

Additional Context:
I'm not 100% sure if this is a bug, or if the Mouse line is genuinely supposed to be this stealthy. In any case, it seemed like something to mention here.

**Comment by Saicchi** [comment]
Can't replicate on `0.E-10474-g1ae66c97a0 [64-bit]`.
Turrets can still see me from their usual range.
![110909](https://user-images.githubusercontent.com/47158232/117672396-318a2780-b180-11eb-8fcd-1170fb4ca4f3.png)

**Comment by anothersimulacrum** [comment]
A mouse mutant can be seen from 30 tiles by a m249 crows, whereas an unmutated human can be seen at 50 tiles. That seems off to me.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10650. Turrets are able to see Unassuming mutants from their usual ranges.

![изображение](https://user-images.githubusercontent.com/11132525/184648104-b7294ccf-3cd4-4501-aaa4-bdc8e4645474.png)
