### ISSUE TITLE
Reloading an Anesthesia Kit with Anesthetic Does not Restore Autodoc Charges

### ISSUE THREAD

**Issue by drachs** [CleverRaven/Cataclysm-DDA#30917]
# Describe the bug

Anesthesia kits seem to have charges as opposed to using a storage of anesthetic.   You can craft anesthetic, and load it into an anesthesia kit, but this doesn't affect the charges.   The autodoc doesn't seem to care about anesthetic, it seems to care about charges.  This seems like maybe an an attempt was made to implement craftable anesthetic to recharge kits but not finished, or was subsequently broken.

# Steps To Reproduce

1. Make 3 charges of anisthesia with the debug menu
2. Load it into an Anisthetic kit
3. See that charges aren't affected, but now you have charges and anesthetic
4. Use the kit 3 times in the autodo and see that it now has 0 charges, 3L of anesthetic, and shows up under chemicals instead of medicine.
5. Try your kit with 3L of anesthetic in autodoc and get an error message about needing an anesthetic kit with charges

# Expected behavior

Anesthesia kits should use anesthetic and not charges.  Crafted anesthetic should be able to reload the kits.

**Comment by Fris0uman** [comment]
What version are you on ?

**Comment by RarkGrames** [comment]
I had something similar. Rechargable anesthesia kits obtained prior to the revert in #30696 don't consume charges when using them for installing CBMs.

**Comment by Fris0uman** [comment]
So if the anesthesia kit appears to be a container, when you `e`xamine it it tells you how much volumes it can contain, then it probably won't reload charges when you put anesthetic in it.
Qet rid of it, spawn a new one and you should be set.

**Comment by drachs** [comment]
This is probably it, I'm on 8944! (18 days ago).  Sorry for wasting your time on something you already fixed.
