### ISSUE TITLE
Deploying a wielded mattress does not remove it from inventory

### ISSUE THREAD

**Issue by CafeineCawfee** [CleverRaven/Cataclysm-DDA#30921]
# Describe the bug

Deploying a wielded mattress does not remove it from inventory.

# Steps To Reproduce

1. Deconstruct a bed.
2. Wield mattress.
3. Deploy mattress.

# Expected behavior

Deploying a wielded mattress should remove it from inventory.

# Screenshots

![Screenshot (2042)](https://user-images.githubusercontent.com/51116144/58469216-087e5100-817a-11e9-9863-5b8d56c95207.png)
![Screenshot (2043)](https://user-images.githubusercontent.com/51116144/58469149-e97fbf00-8179-11e9-8490-a7068a152efa.png)
![Screenshot (2044)](https://user-images.githubusercontent.com/51116144/58469162-ee447300-8179-11e9-995c-e62ee2514807.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 9062
 - Graphics version: Tiles
 - Mods loaded: None

# Additional context

**Comment by TechyBen** [comment]
Was getting the same for large cardboard boxes.
