### ISSUE TITLE
morale/focus reset when loading up a game

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#30924]
# Describe the bug

My pyromaniac doesn't remember the morale boost he gets from a fire he made right before I saved an exited. Also his focus is always 100% when I load up a game.

# Steps To Reproduce

Load up any game on the latest experimental.

# Expected behavior

The game remembers the morale/focus from the previous play session. 

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-3543-g24f066f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    PKs Rebalancing [PK_REBALANCE],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs]
]

**Comment by Orange01gaming** [comment]
I also debug/renamed my character and now there are two characters I can select from. Could that be related?

**Comment by Ramza13** [comment]
Just tried and cannot reproduce this issue.  Lit a fire, my pyro was happy, saved and quit and on load he was still happy.

**Comment by kevingranade** [comment]
The debug rename is a likely cause, reopen if anyone encounters the issue without that.
