### ISSUE TITLE
Assertion failed when switching firing mode

### ISSUE THREAD

**Issue by Dekker3D** [CleverRaven/Cataclysm-DDA#30925]
# Describe the bug
An assertion failure in optional.h when I aim at a security bot and try to switch to full-auto firing mode. No clue what's causing it.

# Steps To Reproduce
1. Open the save file
2. Press e to open the door to the southwest
3. Press f to enter aiming mode
4. Press s to switch firing mode
5. Crash
6. ???
7. Profit

# Expected behavior
Brrap

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-3543-g24f066f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Explosive Zombies [No_Explosive_Zombies],
    StatsThroughSkills [StatsThroughSkills],
    Prevent Zombie Revivication [no_reviving_zombies],
    Magiclysm [magiclysm]
]

# Additional context
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3228161/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3228157/crash.log)
[Celada.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3228155/Celada.zip)

**Comment by Dekker3D** [comment]
Removing the sword bayonet fixes it. Apparently I forgot I'm not supposed to brrap with the Cx4 Storm anyway. I think it was trying to fire my sword bayonet and then realized swords don't really do that.

**Comment by AMurkin** [comment]
Duplicate of the #30676.

**Comment by neitsa** [comment]
I have a patch ready for this bug, but while fixing it, I spotted another problem which will require a more thorough investigation (i.e see with the other devs what can be done about this other problem)...

**Comment by ifreund** [comment]
Closing as a duplicate
