### ISSUE TITLE
Format Exec Error

### ISSUE THREAD

**Issue by DAMO238** [CleverRaven/Cataclysm-DDA#30937]
Game version:
0D Danny binary from main website

Operating system:
KDE neon for Pinebook (ARM architecture)

Tiles or curses:
tiles

Mods active:
none

### Expected behavior
game launches

### Actual behavior
running launcher gives error: ./cataclysm-launcher: 33: exec: ./cataclysm-tiles: Exec format error
running tiles binary gives error: bash: ./cataclysm-tiles: cannot execute binary file: Exec format error

### Steps to reproduce the behavior
Run binary from website on kde neon for Pinebook

**Comment by ZhilkinSerg** [comment]
I don't think we provide prebuilt ARM executables for download. You probably need to build them by yourself on your system.

**Comment by kevingranade** [comment]
Yep, you'll need to compile yourself, though we seem to be portable enough that I'm confident that will work at least.
