### ISSUE TITLE
[SOLVED] error while loading shared libraries: libSDL2_ttf-2.0.so.0

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#30931]
# Describe the bug
I installed the game by downloading and extracting https://github.com/CleverRaven/Cataclysm-DDA/releases/download/0.D/cataclysmdda-0.D-8574-Linux-Tiles.tar.gz

When I try to run the game I get an error message : 
```
error while loading shared libraries: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
```

# Steps To Reproduce

```
hippo@hippo-camp:~/Desktop/cataclysmdda-0.D$ ls
cataclysm-launcher  cataclysm-tiles  data  doc  gfx  lang  lua  README.md
hippo@hippo-camp:~/Desktop/cataclysmdda-0.D$ ./cataclysm-launcher 
./cataclysm-tiles: error while loading shared libraries: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
hippo@hippo-camp:~/Desktop/cataclysmdda-0.D$ ./cataclysm-tiles
./cataclysm-tiles: error while loading shared libraries: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
```

# What I have tried 
I reinstalled both x64 and i386 versions of libSDL-ttf2.0-0
```
sudo apt-get install libSDL-ttf2.0-0
sudo apt-get install libSDL-ttf2.0-0:i386
```
same error message.

I then tried to create a symlink to the x64 library, same error message.
I then tried to create a symlink to the i386 library, same error message.

# Versions and configuration
OS : Ubuntu 18.04.2 LTS
Game Version: 0.D
Graphics version: Tiles 
Mods loaded: NA

**Comment by ZhilkinSerg** [comment]
Related - https://github.com/CleverRaven/Cataclysm-DDA/issues/26745

**Comment by ZhilkinSerg** [comment]
Related too - https://github.com/CleverRaven/Cataclysm-DDA/issues/12638

**Comment by matt32106** [comment]
The package I tried to install to fix it were the wrong ones. The following solved the problem:

```
sudo apt install libsdl2-ttf-2.0-0
```
notice that libsdl2-ttf-2.0-0 <> libsdl-ttf2.0-0

**Comment by matt32106** [comment]
I have changed the title but I let the issue opened as you may want to update the install doc or check fr dependencies when installing.

**Comment by kevingranade** [comment]
I can't find any references to the incorrect library in the installation instructions.

**Comment by matt32106** [comment]
I did not want to imply that the installation instructions were incorrect. What I wanted to say was that the install doc should mention that **some dependencies should be installed by the user himself**.
From my experience, on Ubuntu 18.04 you have to install 3 libs: 

`sudo apt-get install libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0`

and on Lubuntu 18.04 minimal install, you have to add one lib for lua

`sudo apt-get liblua5.3-0`

But YMMV.

**Comment by kevingranade** [comment]
It does, here https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING.md#dependencies
And here https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING.md#debian

**Comment by matt32106** [comment]
Why should a **player** ever read a compilation guide? This should be in a readme or installation file don't you think?

**Comment by ZhilkinSerg** [comment]
Wasn't it obvious what's need to be installed from error message?

**Comment by matt32106** [comment]
No. 
The error complains about "libSDL2_ttf-2.0.so.0" which is not a package name. It does not tell you the exact name of the package you have to install to make it work. 
The best would be to get no error at all when you launch the game but if this is not possible yet, at least some pointers in the INSTALLATION doc (not the compilation one) would help users.

**Comment by ZhilkinSerg** [comment]
Yes, that is not a package name because there are multiple package management systems and it is not known during compile time which one would be active on end user system. Thus we assume user should figure out specific package names by themselves considering system that they use.
