### ISSUE TITLE
Items made from multiple addicting substances cannot give multiple addictions

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#30947]
# Describe the bug

Cannot fix Irish coffee(currently alcoholism-sating only) or my recent PR addition of corretto from #30945 to work on both caffeine and alcohol addiction. Attempting to give the items both properties fails to sate hobo's addiction.

# Steps To Reproduce

1. Give item multiple addiction types.
2. Become or started addicted to one of the types specified.
3. Consume item.
4. Item will not sate withdrawal.

# Expected behavior

Item sates and causes addiction to all types given to it.

# Versions and configuration

- OS: Windows 10, build 17134.765
 - Game Version: 0.D-3556-g65a92b9
 - Graphics version: Tiles
 - Mods loaded: DDA, No NPC Needs

**Comment by Maleclypse** [comment]
Can be completed now if someone decides to do so.

**Comment by Procyonae** [comment]
Using #65480 for anyone looking to do this

**Comment by tjlaxs** [comment]
This seems like a pretty simple JSON change to do that I could try.

I was just wondering that are there other multiple addicting substances that come to mind. Quickly looking I can at least see the "irish_coffee" and "drink_karsk" next to it. But then there are probably other combinations than just coffee and alcohol?

And how would you test this? Would it be enough to spawn the item in game?
