### ISSUE TITLE
Nearby empty vehicle tank not recognized as potential container for clean water

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#30946]
# Describe the bug

Nearby empty vehicle tank not recognized as potential container for clean water

# Steps To Reproduce

1. Have a nearby car with an empty tank.
2. Have a nearby puddle of water.
3. Have ability to boil water (fire, pot, etc...).
4. Have no other empty containers nearby.
5. Make clean water.

# Expected behavior

You should be offered the opportunity to create as much water as you want given the available tank installed on a car. Ideally, you should also get the opportunity to craft anyway, though with a warning that no empty container is available at the time (useful when thirsty and you want to drink all the water).

# Versions and configuration

 - OS: Win7x64
 - Game Version: 0.D-3556-g65a92b9
 - Graphics version: Tiles
 - Mods loaded: none

**Comment by Night-Pryanik** [comment]
Cannot confirm on 0.D-8431. Closing for now, ping me if this still an issue.
![изображение](https://user-images.githubusercontent.com/11132525/66701200-babe4b80-ed0a-11e9-9320-a369d6aa33f6.png)

![изображение](https://user-images.githubusercontent.com/11132525/66701183-97939c00-ed0a-11e9-8b49-632d9cba2b08.png)

**Comment by misterprimus** [comment]
Part of the reason I added that "force craft" feature: to save people from that frustration while the writer of the code figures out a way to make it more accurate.
