### ISSUE TITLE
Error message concerning DISABLE_ROBOT_RESPONSE option

### ISSUE THREAD

**Issue by DSeyka** [CleverRaven/Cataclysm-DDA#30963]
An error message appears, as detailed below. Seems to always happen shortly after any building alarm is triggered. No crash occurs, the game can be continued by ignoring or skipping the message. Build 9070 (tiles), Win x64, no mods.

DEBUG    : requested non-existing option DISABLE_ROBOT_RESPONSE
FUNCTION : options_manager::cOpt& options_manager::get_option(const string&)
FILE     : src/options.cpp
LINE     : 2836

![image](https://user-images.githubusercontent.com/34726992/58584232-8582f680-825e-11e9-8a05-b5ba98791b8e.png)

![image](https://user-images.githubusercontent.com/34726992/58585559-b9135000-8261-11e9-9b57-57dab85ed0f6.png)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3234067/debug.log) attached.

**Comment by Hirmuolio** [comment]
Seems like I forgot to add the default state for that setting in.

For now you can add this to the game_balance.json to fix it.

```
  {
    "type": "EXTERNAL_OPTION",
    "name": "DISABLE_ROBOT_RESPONSE",
    "info": "Disables robot spawning from alerts and from being wanted.",
    "stype": "bool",
    "value": false
  }
```

**Comment by DSeyka** [comment]
Thanks!
