### ISSUE TITLE
Atomic Lamp deleted from inventory after closing cover

### ISSUE THREAD

**Issue by PixelatedBearz** [CleverRaven/Cataclysm-DDA#30970]
# Describe the bug

When I re-cover the atomic lamp, it simply gets deleted from my inventory. It isn't being dropped, it isn't being put in some weird holster, it's simply being deleted

# Steps To Reproduce

1. Get atomic lamp
2. Close the cover / turn it off
3. Have it disappear from inventory

# Expected behavior

I expected the cover on the atomic lamp to be closed, and not be deleted from my inventory. Not entirely sure why it would happen, but I like keeping my lamp.

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1803
- Game Version: 0.D-3614-ga9b9390 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Filthy Clothing [filthy_morale],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Bionics Systems Mod [bio_mod],
    Craftable Gun Pack [craftgp],
    Extended Realistic Guns [realguns],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    NPC traits [npc_traits],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    StatsThroughSkills [StatsThroughSkills],
    Necromancy [necromancy]
]

**Comment by Randonx** [comment]
My atomic lamp just did the same thing.  I'd been using it off and on up until a few days ago (Older version).  Then when I used it today it disappeared.

**Comment by PixelatedBearz** [comment]
Update: bug still present in version 0.D-3880-g89feb2b

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 14 June 2019. Closing until confirmed.
