### ISSUE TITLE
Items with the FIRE flag do not function as expected.

### ISSUE THREAD

**Issue by Chase-san** [CleverRaven/Cataclysm-DDA#30976]
Items with the FIRE flag, such as a torch do not act as a "nearby fire", for the purposes of crafting.

# Steps To Reproduce

1. Be somewhere without any kind of heat source or fire.
2. Craft a torch.
3. Light the torch.
4. Attempt to craft something that needs a nearby fire/fire. (You can't).

# Expected behavior

When crafting something that requires fire to craft, a torch or similar item with the FIRE flag should be an acceptable alternative based on the description of the flag in game.

# Versions and configuration

- OS: Linux
  - OS Version: Distributor ID: LinuxMint; Description: Linux Mint 19.1 Tessa; Release: 19.1; Codename: tessa; Kernel: 4.19.46-041946-generic
- Game Version: 0.D-3551-g5319bdd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Inglonias** [comment]
Can you use a torch for cooking food? Is there enough energy there to boil water? Googling just shows me what you use a blowtorch for in cooking food.

**Comment by Chase-san** [comment]
I am just going by what the flag description says. Maybe this FLAG needs to be removed from the torch, but that doesn't change that the flag does not function as described.

**Comment by TechyBen** [comment]
What is the description of the flag? Should that just be amended to be things that are on fire, not things that function as "fireplace"?

**Comment by Chase-san** [comment]
The description of the flag is:

This item counts as fire for crafting purposes.

**Comment by Inglonias** [comment]
That's a fair enough bug report. I apologize.

**Comment by Chase-san** [comment]
I can confirm that this issue is still an issue.

**Comment by kevingranade** [comment]
Fixed, FIRE is used to light fires, not craft.
