### ISSUE TITLE
Batteries are fireproof

### ISSUE THREAD

**Issue by Szara-ManOfHonor** [CleverRaven/Cataclysm-DDA#30978]
# A clear and concise description of what the bug is.

Batteries do not get destroyed in fire
# Steps to reproduce the behavior:

Dump batteries on the ground (Tested with light batteries, light high capacity batteries, light plutonium batteries, and ultralight batteries, previously observed with others)
Apply fire to batteries (I used 30 logs and lit them on fire)
Watch the impervious nature of these volatile storage mediums

# Expected behavior

Batteries are destroyed. Potentially with a very small (or not so small for larger batteries) explosion involved after some time.

# Versions and configuration

 - OS: WIN10
 - Game Version: 0.D-3551-g5319bdd [64-bit]
 - Graphics version: Tiles
 - Mods loaded: dda

# Additional context

Optionally, also get lost on youtube watching batteries explode when lit on fire.
Or on wikipedia reading about battery explosions. And/or submarines.

**Comment by Inglonias** [comment]
Simple fix. Add the `FLAMMABLE` flag to battery's JSON. Or the `COOKOFF` flag if you want them to explode.
