### ISSUE TITLE
How to remove a chunk of roof?

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#30989]
I want some sunlight in, but i can't even climb the roof with a stepladder.

**Comment by Night-Pryanik** [comment]
You need to somehow remove the underlying floor that supports the roof. There is always a chance of entire roof collapsing though.

**Comment by l29ah** [comment]
Okay, how do i remove a chunk of floor?

Ideally i would want something like https://ichef.bbci.co.uk/news/660/media/images/69195000/jpg/_69195942_moser_montage.jpg

**Comment by Night-Pryanik** [comment]
AFAIK there is no "civilized" method, only by bashing.

**Comment by abvgdeyoj** [comment]
Still waiting for a "civilized" method.
