### ISSUE TITLE
Locker storage volume is 500L rather than 2000L

### ISSUE THREAD

**Issue by Carrnage** [CleverRaven/Cataclysm-DDA#30996]
Version 0.D experimental build 9073, no mods, no version changes in save

When i build a locker according to advanced inventory management "/" the storage volume of the built locker is only 500L as this is empirically worse than just having nothing (and the wooden alternative the dresser) there i'm fairly certain it's a bad value somewhere.

**Comment by Carrnage** [comment]
Okay decided to investigate a bit more. both local and current git version have the max volume of locker as 2000L

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/furniture.json
`  {
    "type": "furniture",
    "id": "f_locker",
    "name": "locker",
    "symbol": "{",
    "description": "Usually used for storing equipment or items.",
    "color": "light_gray",
    "move_cost_mod": -1,
    "coverage": 90,
    "required_str": 9,
    "flags": [ "CONTAINER", "PLACE_ITEM", "BLOCKSDOOR" ],
    "deconstruct": {
      "items": [
        { "item": "sheet_metal", "count": [ 1, 2 ] },
        { "item": "sheet_metal_small", "count": [ 0, 4 ] },
        { "item": "lock", "count": [ 0, 1 ] },
        { "item": "pipe", "count": [ 4, 8 ] }
      ]
    },
    "max_volume": 2000,
    "bash": {
      "str_min": 12,
      "str_max": 40,
      "sound": "metal screeching!",
      "sound_fail": "clang!",
      "items": [
        { "item": "scrap", "count": [ 2, 8 ] },
        { "item": "steel_chunk", "count": [ 2, 4 ] },
        { "item": "sheet_metal_small", "count": [ 6, 10 ] },
        { "item": "pipe", "count": 1 }
      ]
}`

but when i try and drop 6 100L steel drums in the locker it only takes 5 confirming that it's not just advanced inventory management showing the wrong value for some reason

![locker inv](https://user-images.githubusercontent.com/44126959/58681440-86339e00-83c0-11e9-80a5-91e49dcc8c2f.PNG)

**Comment by Rivet-the-Zombie** [comment]
That's 2000 of our weird 250ml base volume units, so 500L.

**Comment by anothersimulacrum** [comment]
Looks like this is the result of #29324

**Comment by Greevv** [comment]
This is a misinterpretation of the data values, not an actual issue IMO.

**Comment by Carrnage** [comment]
> 
> 
> This is a misinterpretation of the data values, not an actual issue IMO.

So are lockers supposed to have half the storage value of empty ground?

**Comment by Night-Pryanik** [comment]
> So are lockers supposed to have half the storage value of empty ground?

Yes they are. 

Maybe we need to adjust (decrease) max volume of empty ground.
