### ISSUE TITLE
Crash during sleeping

### ISSUE THREAD

**Issue by aoae23** [CleverRaven/Cataclysm-DDA#30994]
# Describe the bug

The game will crash shortly after beginning to sleep. It's unclear what the exact cause is.

# Steps To Reproduce

1. Using the below save file, try to sleep immediately.

# Expected behavior

No crash.

# Versions and configuration
- 0.D-3480-gf6c6dfd
- OS: Windows [64-bit]
    - OS Version: 10.0 1809

# Additional context

![image](https://user-images.githubusercontent.com/42950339/58675649-1bc02680-830a-11e9-9aee-8a4a2cf54e2d.png)

[Lometa.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3239329/Lometa.zip)

**Comment by Feuerhai** [comment]
Tried it out with the lastest version and slept till it was too bright to sleep with a few interruptions from landmines exploding next to the house.

**Comment by ZhilkinSerg** [comment]
Cannot reproduce on latest master.
