### ISSUE TITLE
Magiclysm mana bar overflows sidebar options

### ISSUE THREAD

**Issue by Feuerhai** [CleverRaven/Cataclysm-DDA#31003]
# Describe the bug

The magic bar option in the sidebar options is outside of the shown menu when on "lables" configuration. You can still scroll down to select it and move it up, but the courser leaves the menu.

# Steps To Reproduce

Start a character and switch to lables in the interface options.

# Expected behavior

The menu is big enought to show all options.

# Screenshots

![DDA Interface](https://user-images.githubusercontent.com/25032400/58697830-62f5f800-839a-11e9-8a21-455a5fcc42e9.png)
Cursor is on the mana entry below the menu.

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-3659-g07cbc77
 - Graphics version: Tiles
 - Mods loaded: dda, disable npc needs

**Comment by KorGgenT** [comment]
i can lengthen the window as a stopgap, but i'll have to think about a longer term solution for the menu.
