### ISSUE TITLE
Chainlink gate is impossible to build

### ISSUE THREAD

**Issue by dom4op** [CleverRaven/Cataclysm-DDA#31018]
# Describe the bug
What title says. It's in the construction menu, but the game doesn't allow you to build it.

# Steps To Reproduce
1. Gather required resources.
2. Build chainlink fencing for support.
3. Try to build chainlink gate. You won't be able to.

# Expected behavior
I expect my char to build a chainlink gate.

# Screenshots
![Sprite-0002](https://user-images.githubusercontent.com/49651777/58727455-11c32400-83ed-11e9-8d7d-f251845f0663.jpg)
![Sprite-0003](https://user-images.githubusercontent.com/49651777/58727671-a6c61d00-83ed-11e9-8e2e-5bd3d3a22056.jpg)

# Versions and configuration
 - OS: Windows 10
 - Game Version: 9079
 - Graphics version: Tiles
 - Mods loaded: personal mini-mod, doesn't affect structures in any way

# Additional context
Maybe chainlink fence is not enough for support? Well, it should be. I see chainlink fence+gate all over the world.

**Comment by ZhilkinSerg** [comment]
Two adjacent orthogonal terrains should have certain flag (which chainfence probably lacks of):

https://github.com/CleverRaven/Cataclysm-DDA/blob/5c05a83ef65c9f11bc92e5f0b7ffa7d68ee547ce/src/construction.cpp#L904-L917

**Comment by DemAvalon** [comment]
You also cant build the chiken wire gate.

**Comment by Night-Pryanik** [comment]
I guess `check_support` requirement is wrong for these terrain types. Chainlink/chickenwire fences shouldn't be able to support roof, which is implied by `check_support`.
