### ISSUE TITLE
error message about "starting location lab stairs for scenario lab chal does not exist" when entering world.

### ISSUE THREAD

**Issue by fuckthatshit** [CleverRaven/Cataclysm-DDA#31014]
DEBUG    : starting location lab_stairs for scenario lab_chal does not exist
 
 FUNCTION : void scenario::check_definition() const
 FILE     : src/scenario.cpp
 LINE     : 153

as with the other issues i've created, if this is not okay, please tell me how to identify which causes it  and such on my own later.

**Comment by Night-Pryanik** [comment]
Please use the template for a bug reporting. We're not telepathists and don't know your game version, which mods you're using and other info.

**Comment by fuckthatshit** [comment]
ah okay, i wasn't sure how necessary that was, i'll try to leave the template intact and respond to it from now on as best i can.

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-3772-g140838e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Craftable Gun Pack [craftgp],
    Safe Autodoc [safeautodoc],
    Aftershock [aftershock],
    Bens GF recipes [Tolerate_This],
    Bootleg Walkers [Bootleg_Walkers],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    No Freeze [no_freeze],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    PKs Rebalancing [PK_REBALANCE],
    Salvaged Robots [Salvaged_Robots],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    Big River Building Pack [BIGRIVER],
    More City Locations [cityside],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Arcana and Magic Items [Arcana],
    Necromancy [necromancy],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    Battery Migration for Existing Games [Battery_Overhaul_Legacy_Mode],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Mutation Changes [Mutation_Changes],
    No Filthy Clothing [no_filthy_clothing],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by fuckthatshit** [comment]
i think i've added the relevant information to the issues i created which were lacking it now, let me know if i missed anything.

**Comment by kevingranade** [comment]
None of the mainline versions of the lab challenge reference lab_stairs, this error is caused by a third party mod.

Please reproduce issues with third party mods removed before reporting them.

**Comment by fuckthatshit** [comment]
@kevingranade is there some trick to finding that information out? Cause I really have no clue or I would have said where I believe it to be from.
