### ISSUE TITLE
no fungal mod does not actually properly stop fungal creatures and structures from spawning

### ISSUE THREAD

**Issue by fuckthatshit** [CleverRaven/Cataclysm-DDA#31012]
# Describe the bug

the no fungal mod does not actually stop triffid, marloss amd mycus enemies/mapgen/etc from spawning

# Steps To Reproduce
create new world with the no fungal mod
observe fungal things still spawn, a triffid grove in this case for me.
note: it may be related to PK's rebalancing i believe, which i do always use the (current) version of and as far as i know adds several variants of most types to the mundane enemies.

# Expected behavior
i expected it to be impossible except through debug to have any structures spawn, enemies rez, or items/etc appear at all without exceptions for all three fungal types.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-3772-g140838e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Craftable Gun Pack [craftgp],
    Safe Autodoc [safeautodoc],
    Aftershock [aftershock],
    Bens GF recipes [Tolerate_This],
    Bootleg Walkers [Bootleg_Walkers],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    No Freeze [no_freeze],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    PKs Rebalancing [PK_REBALANCE],
    Salvaged Robots [Salvaged_Robots],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    Big River Building Pack [BIGRIVER],
    More City Locations [cityside],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Arcana and Magic Items [Arcana],
    Necromancy [necromancy],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    Battery Migration for Existing Games [Battery_Overhaul_Legacy_Mode],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Mutation Changes [Mutation_Changes],
    No Filthy Clothing [no_filthy_clothing],
    StatsThroughSkills [StatsThroughSkills]
]

screenshot here:
![bugreport](https://user-images.githubusercontent.com/51243084/58723406-d42fae00-838e-11e9-813e-c9bd3b450c52.png)

save here:
https://www.dropbox.com/s/eelbxiyx6zych1k/Society%20Hill.rar?dl=0

**Comment by anothersimulacrum** [comment]
Triffids shouldn't be included in No Fungal monsters - they should have a separate exclusion mod.

**Comment by fuckthatshit** [comment]
@anothersimulacrum oh, I wasn't aware of that can you please share? If there's one for each of the three varieties I'd like to know about them all, thanks.
