### ISSUE TITLE
error message about "battery atomic in inline recipe shockcannon plut is not a valid item template" when enterting world.

### ISSUE THREAD

**Issue by fuckthatshit** [CleverRaven/Cataclysm-DDA#31013]
i get the error message here when entering a world each time, i'm unsure if this is an issue in vanilla or a mod or how to tell in general, so please forgive me if this is frowned on, but i will post it here, please advise if this is not okay.

 DEBUG    : battery_atomic in inline_recipe_shockcannon_plut is not a valid item template
 
 FUNCTION : void component::check_consistency(const string&) const
 FILE     : src/requirements.cpp
 LINE     : 358

**Comment by kevingranade** [comment]
This is from a third party mod, you need to report it to whatever mod owns the shockcannon.

**Comment by fuckthatshit** [comment]
@kevingranade how can i reliably find out where a certain piece of content is added from?

**Comment by kevingranade** [comment]
Search the repository for the id string.
