### ISSUE TITLE
Broth is considered a "veggie" food regardless of ingredients used

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#31017]
# Describe the bug

Broth (just "broth" in jsons) is considered a veggie food regardless of how it is made. I'm willing to consider mushrooms vegetables for gameplay purposes, but broth made from eggs or as a byproduct of stewing tripe should 100% be edible by carnivores.

# Steps To Reproduce

1. Craft broth from reptile/bird/powdered eggs. Craft stewed tripe and get broth as a byproduct.
2. Be a carnivore.
3. Eww, inedible plant stuff.

# Expected behavior

Broth made from eggs or tripe should be different from vegetarian broth made from vegetables and mushrooms.

**Comment by Regularitee** [comment]
Other items considered vegetables by the game:
- Coffee beans (even chocolate-covered, they're considered a vegetable, not junk food!)
- Popcorn (though salted popcorn is a junkfood)
- Nuts
- Rice
- Seeds

I think someone got lazy and just decided to classify every non-fruit plant product as a vegetable automatically. Broth included. I think this is a symptom of that larger overarching issue.
