### ISSUE TITLE
Pots no longer can hold water despite having containing 1 

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#31026]
# Describe the bug

My Pot can't hold water, not only that it does not say how much it can hold it only says it has containing.

# Steps To Reproduce

![image](https://user-images.githubusercontent.com/47362783/58740591-2b5d6f00-83df-11e9-8720-90389f06145c.png)

# Expected behavior

Pots can hold water. They were broken recently.

# Screenshots

I already posted one

# Versions and configuration

 - OS: Windows 10 64bit
 - Game Version: 9081
 - Graphics version: Tiles 64bit
 - Mods loaded: 
![image](https://user-images.githubusercontent.com/47362783/58740619-5f389480-83df-11e9-9f38-d15b84f8443d.png)
![image](https://user-images.githubusercontent.com/47362783/58740629-6790cf80-83df-11e9-9624-e1f2d11cb35a.png)

# Additional context

Is it one of the mods I have loaded or something? I assume everyone would of found this bug right away.
    before the crash happens. -->

**Comment by I-am-Erk** [comment]
Containers seem to be behaving strangely with copy-from since I updated kitchen stuff

**Comment by LaVeyanFiend** [comment]
Since I fixed kitchen stuff for Erk when he added new containers(which still work correctly), I'll just do it again. ASSIGNMENT ACCEPTED
