### ISSUE TITLE
Omnicellular/Slimesprings spawn when Very Hungry;Famished/Very Thirsty;Dehydrated

### ISSUE THREAD

**Issue by AJubatus** [CleverRaven/Cataclysm-DDA#31037]
# Describe the bug

With Omnicellular. when drinking water when "Very Hungry/Very Thirsty", a slimespring is spawned which further drains thirst.

I tested this by letting my Hunger/Thirst go to Very Hungry/Dehydrated, with the following needs:

![image](https://user-images.githubusercontent.com/9111588/58748416-4c21d500-8470-11e9-98ff-42dd65011840.png)

Taking a single drink of clean water then spawns a Slimespring, resulting in this:

![image](https://user-images.githubusercontent.com/9111588/58748421-5f34a500-8470-11e9-9d30-fdf7a882accd.png)

For some reason, Hunger is set to 0, but the Thirst goes up! Stored kCal doesn't change, which appears to be the behaviour that was fixed in #30642 

This has the unfortunate effect of making it very difficult to manage an Omnicellular character. The times where I've successfully been able to eat/drink are times when I let it dip into Famished/Dehydrated, which come with their own maluses.

# Steps To Reproduce

1. Create a character with Omnicellular
2. Let Hunger/Thirst drop to Very Hungry/Very Thirsty
3. Drink.

# Expected behavior

What I'm expecting to happen is that I can drink/eat up until these needs reach 0, at which point further eating/drinking spawns slimesprings. It seems like the current system instead spawns slimesprings when the "stomach is full" (not too up to date on the satiety changes so please correct me if there is a more accurate terminology for this or I'm just plain wrong).

This results in making it very difficult to maintain an Omnicellular character, especially coupled with the metabolism and thirst mutations. I spend most of the time eating/drinking then waiting an hour or two before continuing to eat/drink, instead of just drinking/eating enough to satisfy the needs.

If slimesprings were to spawn when these needs were satisfied rather than on a "fullness", it would still keep much of the challenge of a high maintenance character.

# Versions and configuration

 - Windows 10
 - 0.D-3661-gbe7d5af
  - build 9078
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs, More Survival Tools, Medieval and Historic Content, Boats, Folding Parts pack, Vehicle Additions Pack, Icecoon's Arsenal, Makeshift Items Mod, Mutant NPCs, Tanks and Other Vehicles, More Locations, Fuji's More Buildings, Classes and Scenarios Mod, Filthy Clothing, Disable Religious Texts.

**Comment by Night-Pryanik** [comment]
Addressed by #31605.
