### ISSUE TITLE
Randomize race and hair color for Play Now! mode

### ISSUE THREAD

**Issue by Throwaway-name** [CleverRaven/Cataclysm-DDA#31049]
**Is your feature request related to a problem? Please describe.**  
The character always spawns bald and white if the player starts the game in Play Now! mode.

**Describe the solution you'd like**  
Randomly assign skin and hair at character generation if Play Now! mode is used.

**Describe alternatives you've considered**  
1. Skinhead world.
2. Demographics-and-epoch-based system for assigning race, sex, culture, subculture and gender within a region.

**Comment by Night-Pryanik** [comment]
That's already a thing. Just started three Play Now! games, and all of them have different sets of hair, race and sex.

![изображение](https://user-images.githubusercontent.com/11132525/58759929-a723fc80-8542-11e9-98ac-c6c77d0b217f.png)

![изображение](https://user-images.githubusercontent.com/11132525/58760091-60370680-8544-11e9-80b1-a15c60c7d2d1.png)

![изображение](https://user-images.githubusercontent.com/11132525/58759926-852a7a00-8542-11e9-8d41-899ef0cb39c7.png)

**Comment by Throwaway-name** [comment]
Weird, all my Play Now! runs up to now (0.D-3795-g0c044d3) gave me a bald white character. I can confirm this is working, so this issue is unnecessary.
