### ISSUE TITLE
Lighting Brazier won't pull from marked firewood source

### ISSUE THREAD

**Issue by Randonx** [CleverRaven/Cataclysm-DDA#31056]
**Describe the bug**
Attempting to light a brazier will not pull wood from a marked firewood source.

**Steps To Reproduce**
Have nearby activated(placed) Brazier
Have ignition source in inventory
Have nearby marked firewood source
`e`xamine brazier
`f` Start a fire
"You attempt to start a fire with your matchbook..."
"There is nothing to light there."

**Expected behavior**
Game will pull firewood from the marked firewood source, ignite the brazier, and start a fire

**Versions and configuration**
- OS: Windows 10 Pro
- Game Version: 0.D-3795-g0c044d3
- Graphics version: Tiles
- Mods loaded:
"dda",
"no_npc_food",
"growable-pots",
"makeshift",
"Medieval_Stuff",
"More_Survival_Tools",
"nw_pack",
"no_freeze",
"PK_REBALANCE",
"alt_map_key",
"Cata++",
"hydroponics",
"Mining_Mod",
"national_guard_camp_edit",
"more_locations",
"FujiStruct",
"mapgen_demo",
"deoxymod",
"boats",
"Arcana",
"DP_Old_Floor",
"DP_REMIX_INDICATORS",
"cbm_slots",
"Battery_Overhaul_Legacy_Mode",
"manualbionicinstall",
"no_filthy_clothing",
"no_reviving_zombies",
"safeautodoc",
"StatsThroughSkills"

**Additional context**
Save (Including Mods):
[NoFiresourceSave+Mods.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3244230/NoFiresourceSave%2BMods.zip)

**Screenshot**
![Screenshot 2019-06-01 13 45 31](https://user-images.githubusercontent.com/50780860/58753811-c99e1300-8479-11e9-8570-32ca0040ce66.png)

**Comment by Dacendeth** [comment]
Happens in my game with mostly no mods as well, was not happening in the previous version I was playing cataclysmdda-0.D-Windows_x64-Tiles-9073

**Comment by Randonx** [comment]
I was looking at that Dac, but didn't want to point any fingers.

**Comment by JeanLucVanDamme** [comment]
I've actually had this bug for a few weeks now, so I don't think the commit referenced above is the culprit.

**Comment by TechyBen** [comment]
I was getting the same with an oven. Can anyone else confirm this also happens with ovens?

**Comment by Dacendeth** [comment]
Yeah mine's with an oven.

**Comment by Kibawan** [comment]
I can confirm with Ovens and Stoves.

**Comment by l29ah** [comment]
It used to be broken in dec 2018. Maybe it never worked?

**Comment by l29ah** [comment]
(c236710b857388ccf66320d8b3cd6a89cce5ec01)

**Comment by Randonx** [comment]
I had worked since I started playing 2 months ago, all the way up to a recent (at the time of my posting) update.

**Comment by matthemsteger** [comment]
It looks like it is everything, an early bail was added in #31002 so that charges werent burned if there was no fuel. I have opened #31256 to remove the early bail and delay the taking of a charge only if successful instead.
