### ISSUE TITLE
Body bags are too common in the woods

### ISSUE THREAD

**Issue by Throwaway-name** [CleverRaven/Cataclysm-DDA#31057]
# Describe the bug
I've found several body bags while foraging during a campground start, and testing the item group shows that they appear 1-5 times out of 100 normally; unlike bottles potsherds and other waste artifacts of civilization, body bags tend to appear in specific, uncommon locations, not hidden within every forest.

# Steps To Reproduce
Forage through bushes in a sizable forest, or map with unforaged underbrush.

# Expected behavior
Body bag spawns should be limited to special maps and event locations, like mass graves and helicopter crashes.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-3611-g47d604b
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [
  "dda",
  "craftgp",
  "safeautodoc",
  "aftershock",
  "realguns",
  "growable-pots",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "modern_weapon",
  "More_Survival_Tools",
  "nw_pack",
  "DinoMod",
  "Mining_Mod",
  "mutant_npcs",
  "national_guard_camp",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "more_classes_scenarios",
  "no_npc_food",
  "filthy_morale",
  "manualbionicinstall",
  "Odds_N_Ends",
  "sleepdeprivation",
  "novitamins",
  "FIC_Weapons",
  "crazy_cataclysm",
  "mapgen_demo"]

# Additional context

Other items are questionable as woodland trash due to their vulnerability to water, like cardboard boxes and newspapers.

**Comment by nexusmrsep** [comment]
Logic behind it was that wind has blown them to forests from the mass graves where they were plenty. However I don't oppose reducing the number if it feels off.

**Comment by l29ah** [comment]
Are they even useful for anything?

**Comment by TechyBen** [comment]
> Are they even useful for anything?

[Toystoreymeme.jpg]
Plastic chunks, plastic chunks as far as the eyes can see.

It's a good source for them, but somewhat possibly too much plastic source for a wilderness survivour.

**Comment by Throwaway-name** [comment]
@nexusmrsep Reducing their spawn weight to 1 seems to work.
