### ISSUE TITLE
Burning Fire changes estimated burn time constantly

### ISSUE THREAD

**Issue by Feuerhai** [CleverRaven/Cataclysm-DDA#31068]
# Describe the bug

E(x)amining a fire in a controlled place (brazier, etc.) while having a low survival skill (between 2 and 4 from my testing) shows a constantly switching estimated burn time.

# Steps To Reproduce

1. Create a character with survival 2.
2. Start a fire in a controlled place.
3. E(x)amine the fire.

# Expected behavior

The description stays the same for a turn.

# Screenshots

![broken fire](https://user-images.githubusercontent.com/25032400/58759055-8d73bc80-8524-11e9-867d-ffd4985578ca.gif)

# Versions and configuration

- OS: Windows 7
- Game Version: 0.D-3795-g0c044d3 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Mythical Martial Arts [MMA],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    sees-player icon, +attitude [sees_player]
]

# Additional context

World save:
[Chariton.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3244618/Chariton.zip)

**Comment by BX442** [comment]
It is more like a character doubting the duration of the burning. And this is not displayed by a period of time as "from 2 to 12 hours", as a non-constant value.
Google translator, sorry :)

**Comment by nexusmrsep** [comment]
> It is more like a character doubting the duration of the burning. And this is not displayed by a period of time as "from 2 to 12 hours", as a non-constant value.

Exactly this. This is a design choice, but if it's sub-optimal it can be changed to "from-to" quite easily.

**Comment by Feuerhai** [comment]
It's a bit confusing and just seems like a bug at first glance (which is proven by the multiple issues here and on reddit for it). I would vote for a static range

**Comment by mark7** [comment]
It's also hard to read because it's changing so quickly.
