### ISSUE TITLE
Cargo locks have no documentation

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#31062]
I've tried asking in the discord multiple times across multiple days, but not a single person seems to know how cargo locks work, if they work, or the conditions of their use (which parts can use them, and when (if they're passive/active)). Not even the original submission -- https://github.com/CleverRaven/Cataclysm-DDA/pull/22144 -- explains their functionality.

As far as I can tell, only examining and understanding the raw code can provide any insight on them. And any game feature that requires taking apart the game to figure out how to use it is... not a great thing. It would explain why it seems like no one uses them or understands how they work, at least.

I'd recommend that the description of the cargo lock inventory item (or the vehicle part, as installed on a vehicle) have its description expanded to explain whether it's toggled or passive, and where it can be installed.

**Comment by nexusmrsep** [comment]
It adds the ability to lock cargo tiles in vehicles so NPCs can't steal from them. It's well described in the original submission. Perhaps it's not working as described?

**Comment by Regularitee** [comment]
By lacking documentation I mean things like:

- When you say "ability to lock cargo", does that imply there's some mechanism to toggle the lock on/off? Or does this just passively prevent strangers from accessing containers? This should be in the description so players won't accidentally install a lock, think it's automatic, but leave their stuff vulnerable to theft. Or inversely if it's passive, won't waste time trying to figure out how to toggle the lock status on/off when there is none. So maybe add something like:
>This part will render the container inaccessable to non-allied NPCs
or
>This part can render the container inaccessable to non-allied NPCs by [instructions for toggling here]

- Which containers types can be locked? Players don't want to have to install all 10+ vehicle containers to test them one by one. So something like
>This part can only be used on enclosed containers with a lid
or
>This part can only be used on external containers
