### ISSUE TITLE
Decorated yet functional armor, should exist.

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#31063]
**Is your feature request related to a problem? Please describe.**  
The only fancy armor that is actually protective in the game (Armor in this case does not include helmets like the pickelhaube and means arm guards, leg and torso armor) is the ornamental plate armor, when there are examples of techniques that were used to decorate armor that have no performance impact at all on the armor (some were actually beneficial, like painting and fluting)

**Describe the solution you'd like**  
Adding recipes on the armorsmith book or a separate book for the player to create "fancy" and "super fancy" armors using techniques that do not impact its performance, much like it has been done for over 500 years in the real world, such as:
Inlay, damascening, encrusting, engraving, pointillé decoration, etching, gilding and silvering (the more durable version of the last two "fire gilding" seems that would be harder to do since it requires mercury, and I don't think there is mercury in the game)

**Describe alternatives you've considered**  
Not doing it or adding some fancy and very fancy armors that spawn in museums and mansions, but can't be crafted (Ornate armor, Decorated full plate mail etc..)

**Additional context**  
Essays on the Metropolitan Museum of Art's website about the subject: 
[The Decoration of Arms and Armor](https://www.metmuseum.org/toah/hd/decaa/hd_decaa.htm)

[Techniques of Decoration on Arms and Armor](https://www.metmuseum.org/toah/hd/dect/hd_dect.htm)

An example of an armor richly decorated in ways that have no impact on its performance:
[Armor Garniture of George Clifford (1558–1605), Third Earl of Cumberland](https://www.metmuseum.org/art/collection/search/23939)

Edit: after reading some modding tutorials it looks like I might be able to code this myself (I think and hope) but I still would like to check if this is something that the main developers agree with.

**Comment by kevingranade** [comment]
Feel free to add as a mod, but this doesn't work for the main gane. Alternately feel free to add ornamental armor without marking it as stylish.

The stylish trait is balanced by stylish clothing being tactically suboptimal, so adding the stylish flag to tactically superior clothing is not ok.
