### ISSUE TITLE
Partially filling/emptying liquid containers

### ISSUE THREAD

**Issue by Feuerhai** [CleverRaven/Cataclysm-DDA#31061]
**Is your feature request related to a problem? Please describe.**  
I tried to use one of the 60L tanks on the surival shelter to carry some saltwater from the nearby swamp. After filling it up I had to take frequent breaks on the way back because it was too heavy. A smart survivor would only partially fill the tank so he/she can carry it back without a problem

**Describe the solution you'd like**  
When filling a container from an endless source, give me an option to only fill it half way or maybe quarter steps. Maybe also only give the option when handeling big containers (>10L) so it won't annoy everyone.

**Describe alternatives you've considered**  
Allow me to unload a container partially to the ground. This could also be a way to extinguish multiple fire tiles by throwing a bit of water on every tile instead of emptying the whole container at one tile.

**Comment by Feuerhai** [comment]
Hauling the tank instead was a solution, but this would still be nice to have.

**Comment by Randonx** [comment]
This would be a fantastic option.

**Comment by foulman** [comment]
I concur, the all or nothing choice leaves a lot to be desired.

**Comment by TechyBen** [comment]
Sounds good. How do we implement it without too much GUI creep or button clicking? Personally I'd prefer a separate manner to then partially fill/empty. But as long us current filling/emptying is one click, it would still be bearable.

A lot of recent GUI changes means some of the 1 option systems are not 2 or 3 clicks down for what use to be 1.
