### ISSUE TITLE
Clothing colors and fabric dyes

### ISSUE THREAD

**Issue by YukariMindGap** [CleverRaven/Cataclysm-DDA#31066]
**Is your feature request related to a problem? Please describe.**  
I thought that clothing lacks color variations so all clothing of the same type look the same, color-wise. Also, I would like to see more use of the coloring feature walls and tiles can have.

**Describe the solution you'd like**  
Add color descriptions and the ability to dye clothing

**Describe alternatives you've considered**  
Keep clothing the same as it is and add dyes for different crafting porposes

**Comment by kevingranade** [comment]
Feel free to add this if you can find a good way to do so, but we have much too large an issue backlog to entertain cosmetic issues like this.
