### ISSUE TITLE
Cat and dog food lasting forever doesn't make sense

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#31076]
# Describe the bug
Cat and dog food are relativity easy to make (cooking 4) they do not perish, despite not requiring any tools such as a canning pot to make, how exacting does combining cooked meat with water make something not spoil?

# Steps To Reproduce

1. Get some raw meat and water
2. Cook some cat food 
3.  Now you have food that never spoils, is healthy to eat, and only has a minor downside of enjoyablility.

# Expected behavior
For cat/dog food to spoil or have a believable reason for it to have a indefinite shelf life.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-3778-gcec1ebf [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Folding Parts pack [deoxymod],
    Classes and Scenarios Mod [more_classes_scenarios],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA]
]

**Comment by DracoGriffin** [comment]
Could alter description and recipe to be in sealed containers of some sort (jarred or canned).
