### ISSUE TITLE
Vanessa Toby is broken, speaking to her causes endless loop

### ISSUE THREAD

**Issue by dom4op** [CleverRaven/Cataclysm-DDA#31075]
# Describe the bug
After merging #30991 speaking to Vanessa causes endless dialogue loop with no option to stop talking

# Steps To Reproduce

1. Ask her to give you a haircut
2. Embrace frustration

# Expected behavior
I expect to be able to say BYE and come back home

# Screenshots
![Sprite-0002](https://user-images.githubusercontent.com/49651777/58761980-fa9e4680-8552-11e9-8a3a-a7d2524438c8.jpg)

**Comment by I-am-Erk** [comment]
Have you completed her mission already?

Is she newly spawned or was she spawned before recent updates?

I can fix this problem so she doesn't loop but I can't tell why she isn't offering you a mission, unless she was spawned earlier and doesn't have the mission in her npc definition.

**Comment by dom4op** [comment]
Does she have a mission? I thought she was a stub and the dialogue option was a placeholder for future PR. Anyway, she didn't give me a mission.

![Sprite-0002](https://user-images.githubusercontent.com/49651777/58762595-03dee180-855a-11e9-8430-f27083a8c23d.jpg)

She was spawned long ago in my game, way before recent updates.

**Comment by I-am-Erk** [comment]
Ok good, then it's just a matter of me forgetting to add talk_none, nothing more sinister

**Comment by dom4op** [comment]
Fixed by #31077
Thank you

**Comment by I-am-Erk** [comment]
Really, unfortunately, you'll have to go to a new refugee center for the new missions and dialogue to work. This just stops you from getting into a loop if you're in an old center
