### ISSUE TITLE
Add brief descriptions of wounds on corpses

### ISSUE THREAD

**Issue by DavidSarif** [CleverRaven/Cataclysm-DDA#31072]
**Is your feature request related to a problem? Please describe.**  

The world of cataclysm is various and fascinating. Random encounters and random positions of objects create numerous possibilities for roleplay and immersion. However, sometimes you I can meet, for example, facility with lots of corpses and I have no idea what it can be: bug,  another creature, one of my previous encounters, etc. It would be very convenient to be able to look on corpse and say: "This one has many cut wounds and probably was killed by NPC/tiger/clawed babaika. This one is partially smashed: probably it can be Juggernaut nearby. This has no visible wounds, I must be realy careful as someone has very special attacks. This has some electric burns and electronics on them is burned out: I must be afraid of shockers".

**Describe the solution you'd like**  

I suggest adding to the corpses new property describing the reason of death. For newly generated corpses it can be set in moment of death and for pregenerated corpses (for example, in lab's lifts) defined semi-randomly depending on the context.
High perception and first aid allows to approximate time passed from death (not exactly, but with some error). Perception – because you must see marks that are pointing to different cases. First aid – because you must interpret found marks.

**Describe alternatives you've considered**  

I can't see any real alternatives except leaving as it is.

**Comment by Zireael07** [comment]
Still a valid suggestion, though.
