### ISSUE TITLE
NPC from faction camp run away

### ISSUE THREAD

**Issue by DavidSarif** [CleverRaven/Cataclysm-DDA#31071]
# Describe the bug

Ordering "Manual Labour" in faction camp makes selected NPC run away from player character and stay at long distance. If I teleport NPC to the player character, order them to come with me and then to guard position, they start to behave as before. However, they don't do "Manual Labour" itself.

# Steps To Reproduce

1. Load attached save
2. Use "Manual Labour" at bulletin board to select any of the NPCs.
3. See NPC running. 

# Expected behavior

NPC perform "Manual Labour" and does not run away.

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1809
- Game Version: 0.D-3772-g140838e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Craftable Gun Pack [craftgp],
    Aftershock [aftershock],
    Extended Realistic Guns [realguns],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    EXTENDED_BUILDINGS [ext],
    Disable Religious Texts [no_religious_Texts],
    No Antique Firearms [no_olg_guns],
    No Flaming Weapons [no_flaming_weapons],
    Classes and Scenarios Mod [more_classes_scenarios],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I don't know if this is related to Labour bug, but I am also unable to upgrade any of the extensions. When I select upgrade option and press Enter, bulletin board window just disappears without any prompt.

Save file attached.
[Fort Benton.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3244710/Fort.Benton.zip)

**Comment by davidpwbrown** [comment]
This should be fixed in latest master.
