### ISSUE TITLE
9089 causing issues with Arcana Mod

### ISSUE THREAD

**Issue by ajaifel** [CleverRaven/Cataclysm-DDA#31081]
# Describe the bug

Game kicks back to main menu when attempting to create a new character when using the new 9089 build.

# Steps To Reproduce

1. Make a world with Arcana and Magic items Mod active
2. Make new custom character
3. Watch the error roll in

# Expected behavior

The character creation menu displays

# Additional context

-----------------------------------------
16:26:23.056 : Starting log.
16:26:23.056 INFO : Cataclysm DDA version 0.D-3879-g5557a8c
16:26:23.079 INFO : Number of render drivers on your system: 4
16:26:23.079 INFO : Render driver: 0/direct3d
16:26:23.079 INFO : Render driver: 1/direct3d11
16:26:23.079 INFO : Render driver: 2/opengl
16:26:23.079 INFO : Render driver: 3/software
16:26:23.083 INFO : Language is set to: 'en'
16:26:23.688 INFO : SDL version used during compile is 2.0.5
16:26:23.688 INFO : SDL version used during linking and in runtime is 2.0.5
16:26:23.879 INFO : Active renderer: 0/direct3d
16:26:24.245 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
16:26:24.444 WARNING : opendir [./mods/] failed with "No such file or directory".
16:26:44.540 ERROR : (error message will follow backtrace)
	(@0x59764e[cataclysm-tiles.exe+0x19764e]), 
	(@0x597c7a[cataclysm-tiles.exe+0x197c7a]), 
	(@0x59b036[cataclysm-tiles.exe+0x19b036]), 
	(IMG_LoadWEBP_RW+0x111b8e@0x10a8eae[cataclysm-tiles.exe+0xca8eae]), 
	(@0x8806b1[cataclysm-tiles.exe+0x4806b1]), 
	(@0x8833a0[cataclysm-tiles.exe+0x4833a0]), 
	(IMG_LoadWEBP_RW+0x5318ef@0x14c8c0f[cataclysm-tiles.exe+0x10c8c0f]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0x14@0x7ff9e0744034[KERNEL32.DLL+0x14034]), 
	(RtlUserThreadStart+0x21@0x7ff9e1e03691[ntdll.dll+0x73691]), 
Backtrace emission took 0 seconds.
src/main_menu.cpp:709 [bool main_menu::new_character_tab()] Error: item group "NC_EVAC_SHOPKEEP_misc" already defined with type "collection"

**Comment by anothersimulacrum** [comment]
Issues with the Arcana mod should be reported in the [Arcana Repo](https://github.com/chaosvolt/cdda-arcana-mod).
