### ISSUE TITLE
Turrets do not turn to the player when they shoot at him.

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#31098]
Maybe it can be fixed somehow, cause now all monsters turn, but turrets do not, and it noticeble in comparsion to other creatures.

**Comment by ZhilkinSerg** [comment]
Critter sprite is flipped on movement while turrets do not move.

**Comment by Fracture64** [comment]
Does that mean monsters with with reach (skeljugs) or ranged attacks (shockers) also don't flip?

**Comment by SomeDeadGuy** [comment]
flip this stale tag
