### ISSUE TITLE
Lab trader over weight limit, prevent buying from them

### ISSUE THREAD

**Issue by archigo** [CleverRaven/Cataclysm-DDA#31091]
# Describe the bug
Trading with a lab through the intercom. The lab is over the weight limit. I try to buy something from them, without selling anything. This is not possible  because "The intercom can't carry all that" which makes no sense.

# Expected behavior
Buying should never be impeeded by the seller being overweight. Probaly not selling either, since they have the whole building to store stuf..

# Screenshots

![sHJBPg9](https://user-images.githubusercontent.com/6784093/58768959-a91da800-85a2-11e9-8365-27ef9d7105a1.jpg)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-3509-ge10d164 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills],
    Simplified Nutrition [novitamins],
    Battery Migration for Existing Games [Battery_Overhaul_Legacy_Mode],
    Alternative Map Key [alt_map_key]
]

**Comment by Dacendeth** [comment]
He mostly goes over weight when he sells skitterbots, those weigh a lot.

**Comment by YukariMindGap** [comment]
I say give them one of those limitless debug bags

**Comment by Inglonias** [comment]
If the intercom is an NPC, then giving it debug carrying capacity might help, yes.
