### ISSUE TITLE
Necco wafers take 1mL of volume

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#31102]
0.D-3880-g89feb2b73f-dirty

**Comment by Fris0uman** [comment]
How much should they take ?

**Comment by anothersimulacrum** [comment]
Please fill out the [template](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). This bug report is useless right now because it just states a fact and your version, not explaining why that is a problem.

**Comment by l29ah** [comment]
Certainly more than 1mL since they are 220kCal that is at least 55g worth of carbohydrates.

**Comment by Hirmuolio** [comment]
Googling reveals that the 220 kCal is per serving.
The site is extremely unhelpful and says that the serving size is one roll.

**Comment by Zombiemanpig** [comment]
![image](https://user-images.githubusercontent.com/47362783/58894373-e0ce4200-86bf-11e9-8666-c40a065711ad.png)


They are tiny...

**Comment by natsirt721** [comment]
Necco(tm) wafers are pure sugar, and are approximately the diameter of a nickel. One roll of wafers is about 4 inches long, so I'd say the volume for a roll is about 35-45mL.
