### ISSUE TITLE
Quarterpanels in the way of your welder let you infintely weld

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#31103]
# Describe the bug

If the only thing between you and your welding tool is a quarterpanel and you try to repair something, it'll repair it and not take any charge from the welder.

# Steps To Reproduce

1. Put a welding tool across from a quarterpanel from you
2. attempt to repair something 
3. It'll complete and the welding tool charge doesn't diminish 

# Expected behavior

For the welding tool to be unusable or used properly

# Screenshots

![image](https://user-images.githubusercontent.com/26881007/58809168-6a5f1080-85e9-11e9-8e49-54cd9a8bf510.png)
Welding tool is on the seat.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-3778-gcec1ebf [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

There might be other things besides welding this works with but I don't know.

**Comment by l29ah** [comment]
Reproduced it in my game.

**Comment by kevingranade** [comment]
I vaguely remember this being fixed, so might just need a retest.

**Comment by Fris0uman** [comment]
Could not reproduce on latest experimental
1- Start default word
2- Find busted RV
3- Spawn 1 welder with medium plut battery on front seat
4-Get out
5-Examine vehicle from the front and repair stuff
6- Charge are consumed

**Comment by ZhilkinSerg** [comment]
Please ping me if it is still reproducible on latest `master`.
