### ISSUE TITLE
Talking to Rhyzaea Johnny causes a chat trap

### ISSUE THREAD

**Issue by EirenexTheDragon** [CleverRaven/Cataclysm-DDA#31107]
At one point when talking with the Npc in the Refugee camp, when you talk about his story and then ask about himself, he has no back button 

# Steps To Reproduce

1. Start a Conversation with said Npc 
2. press 2 times A , then F
3. Notice how the npc keeps you hostage about his storytelling forever, chatrapping you

# Expected behavior

an option that lets you disengage from his storytelling

# Screenshots
![grafik](https://user-images.githubusercontent.com/41762755/58830381-7cbd6680-864a-11e9-8ece-686716a1dc8d.png)

trying out the other options does not reveal a back button

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-3904-gff90617 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Extended Realistic Guns [realguns],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Hide STATUS [DP_No_Status_Tiles],
    Safe Autodoc [safeautodoc],
    Manual Bionic Installation [manualbionicinstall],
    Beta National Guard Camp [national_guard_camp],
    No Fungal Monsters [No_Fungi]
]

# Additional context

i think it requires just a fix like its being done here in #31077 ?

**Comment by krekeler0** [comment]
test [this](https://github.com/CleverRaven/Cataclysm-DDA/pull/31116)

**Comment by krekeler0** [comment]
I believe [this](https://github.com/CleverRaven/Cataclysm-DDA/pull/31116) has fixed your problem.

**Comment by I-am-Erk** [comment]
You danged players and your "I don't want to keep reading the same lines of dialogue over and over again forever". You're so darned entitled.
