### ISSUE TITLE
Pipe bombs have extremely high explosive power for how easily they are crafted

### ISSUE THREAD

**Issue by aoae23** [CleverRaven/Cataclysm-DDA#31110]
# Describe the bug

According to /data/json/items/tools.json, pipe bombs have 500 power. Dynamite has 250 power, fertilizer bombs have 125 power, and black powder bombs have 100 power in comparison. The reason why this is problematic is because pipe bombs are really easy to craft (needing fab 1, a pipe, some explosive material and some strings) rendering the aforementioned explosives unviable.

# Steps To Reproduce

1. Detonate a pipe bomb followed by dynamite.

# Expected behavior

Pipe bombs are not as powerful as dynamite.

# Versions and configuration

-

**Comment by JeanLucVanDamme** [comment]
I was under the impression that the pipe bomb power of 500 was realistic and based on principled calculations?

Specifically: [#26790](https://github.com/CleverRaven/Cataclysm-DDA/pull/26790)

**Comment by kevingranade** [comment]
You're right, this would be one of the benchmarks for rebalancing the
explosion code.
It also strikes me that a proper pipe bomb would likely not be so quick to
craft, just cutting it to length with a hacksaw would take significant time.

**Comment by YukariMindGap** [comment]
What do you come yo for the explosion code rebalance?
