### ISSUE TITLE
NPCs causing world not to load

### ISSUE THREAD

**Issue by TheWalrusFighter** [CleverRaven/Cataclysm-DDA#31111]
# Describe the bug

Can't load world with NPC and arcana

# Steps To Reproduce

1. create world with arcana and build 9092
2. world fails to load

# Expected behavior
world loads successfully

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [0.D-3904-gff90617]
 - Graphics version: [Undeadpeople]
 - Mods loaded: [dda, aftershock, necromancy,arcana, magiclysm.]

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3249742/debug.log)

**Comment by kevingranade** [comment]
Please report to arcana github.
