### ISSUE TITLE
Mission: Find canned goods.

### ISSUE THREAD

**Issue by faefux** [CleverRaven/Cataclysm-DDA#31124]
Hi, i'm finally getting around to finishing this map and these NPCs for a new faction, this might sound like a real silly question but there is/was a mission that required you to find a bunch of canned goods. I can't find it anywhere despite greping my folder and searching here... I'm almost certain i didn't imagine it... Can someone point it out to me?

**Comment by Night-Pryanik** [comment]
It was removed from the game.

**Comment by faefux** [comment]
Thanks @Night-Pryanik. That's actually even better for me. I'm really not good with github, can you link me to the old mission? I think that _should_ still be possible.

Another question whilst i'm here, where are the item id's for the quartered pieces of animal from butchering? Cant seem to find them.

**Comment by Night-Pryanik** [comment]
@faefux https://github.com/CleverRaven/Cataclysm-DDA/pull/31020/commits/50d5b359baf8fcdd4badfe9d4f67141a95d11249#diff-e29f87f08095bfd26996b51966664898L456
