### ISSUE TITLE
New Faction: Adding overmap specials.

### ISSUE THREAD

**Issue by faefux** [CleverRaven/Cataclysm-DDA#31129]
Hi, So i've built a map, some missions and some NPCS for a new faction and they work fine when added too the game through the debug menu but where i'm stuck is actually adding these things to the map to be generated naturally..  I cant seem to get my head around what i should be setting as the 'terrrain_id' and stuff like this. Is there anywhere that lays this out real simply? 

Edit: This is what i have so far, anyways: https://github.com/faefux/Catacylsm-Faction
Github fucked up my spacing in the readme. this website really is a nightmare!

**Comment by kevingranade** [comment]
Please take a look at one of the community sites for support rather than opening issues to ask questions about the game:
https://discourse.cataclysmdda.org
https://www.reddit.com/r/cataclysmdda

**Comment by faefux** [comment]
Sorry!  thought it'd be quicker/easier to get answers here. I'll stick to the forums in the future.

**Comment by SourSlime** [comment]
The cdda discord has a channel specifically for asking coding questions, so if you need help, I’d recommend that.

**Comment by faefux** [comment]
@SourSlime I tried the discord before, they were basically really rude to me when i asked them for help in joining channels and accused me of being a troll for asking? (I'm not a discord person).
I did try again  a few weeks ago, the link didn't work though.  

I appreciate the advice though, thanks.

**Comment by SourSlime** [comment]
That’s very odd, most of the people on the discord are nice. If you do go back, make sure to mention that you’re new.

I’m not sure why the link didn’t work, but it might have been a temporary one. I think there’s a permanent one on the cdda reddit

**Comment by faefux** [comment]
@SourSlime  Thanks, How do i joint he actual chat? It's doing what it did before where when i join it just sticks me into like 4 rooms that are dead, i assume these arn't the main chat and i'm locked out for some reason.

**Comment by faefux** [comment]
@SourSlime Thanks, How do i joint he actual chat? It's doing what it did before where when i join it just sticks me into like 4 rooms that are dead, i assume these arn't the main chat and i'm locked out for some reason. I read the rules like the thing asks and it just speaks about a phrase that seemingly doesn't exist, or even if it does it isn't obvious.... Shit like this makes me wish people just used the IRC more like normal people...
