### ISSUE TITLE
Considerable discrepancy in average zombie loot quantity

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#31127]
An issue made to gauge opinions on suggestions to deal with an issue

# Describe the bug

Currently, average zombie non-clothes loot is managed in a way that zombies upon death have 50% chance to start dropping from a particular item group. However, drop chances in that group are high enough that if RNG hits it, several items are nearly always dropped. It leads to situations where some zombies seem to have absolutely nothing beside clothes on their back, while others carry multiple items of assorted junk, rarely anything in between.

# Expected behavior

I'd suggest, if you fine folks would be alright with that, to adjust the loot so its group is called with higher chance than 50% but individual items in the group have lower chance of appearing. The intention is to make zombies have more varied numerically non-clothes loot on them.

# Versions and configuration

Currently appearing, tested and verified at 0.D-3936-g9f52909 experimental, under Win 7 with tiles, but since it's a matter of json file regarding the loot, it will appear in earlier and future versions using the above loot distribution till changed.

# Additional context

If given a green light I can fiddle with loot values myself or leave it to whoever has a nice idea how to adjust the probability chance to achieve a more even distribution.

**Comment by Night-Pryanik** [comment]
You're welcome to give it a try. Just please comment the why of all the changes you're planning to do.

**Comment by kevingranade** [comment]
Question answered and then went stale.
