### ISSUE TITLE
Mods interfering with vitamin mechanis even though they should not be doing so

### ISSUE THREAD

**Issue by RosieMcCattail** [CleverRaven/Cataclysm-DDA#31122]
The people on discord have convinced me to post an issue here.
So the vitamins fluctuate between -2 and 0 in my game. This looks like some mod is resetting them constantly, because setting vitamins to any arbitrary value and waiting just leads to them being reset to zero. 
A new world created with no mods works fine.

[
  "dda",
  "FIC_Weapons",
  "realguns",
  "growable-pots",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "modular_turrets",
  "Salvaged_Robots",
  "hydroponics",
  "mutant_npcs",
  "Urban_Development",
  "deoxymod",
  "blazemod",
  "Tanks",
  "No_Fungi",
  "no_reviving_zombies",
  "safeautodoc",
  "StatsThroughSkills"
]

Please help by pinning down the mod that's causing this issue to happen.

Many thanks to ecchi squid, draco griffin and anothersimulacrum at discord for helping me with this.

**Comment by l29ah** [comment]
Binary search would pinpoint the mod in five steps :P
