### ISSUE TITLE
Trying to craft some items will cause the game to prompt the "comsume to continue crafting" windown evry single turn.

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#31121]
# Describe the bug

When trying to craft certain items with multiple possible components (this happened with, mutagens and other variety of mutagens) the "consume item to continue" will appear every single turn, regardless of your skill (I had the maximum cooking skill you can get from the secret lab books, 8 or 9 I think)

# Steps To Reproduce

1.spawn enought items to produce mutagem and its variants, making sure there are multiple items that can fufill a (maybe multiple for all parts) part of the recipe (eg have chunks of tainted meat and blob globs for mutagem)

2.Try to craft the mutagens.

3.Hold "Y" until the recipe is done.

# Expected behavior

The message only pops up when I actually fail, not every single time, and especially not when there is no chance of me failing.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-3904-gff90617 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Filthy Clothing [filthy_morale],
    Simplified Nutrition [novitamins],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Extended Realistic Guns [realguns],
    Craft Ammo Mags - ERG [SD_Magcrafting_Realguns_Extension],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Crazy Cataclysm [crazy_cataclysm],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    NPC traits [npc_traits],
    Zetsukaze's Hair Extensions! [zets_hair_extensions],
    Big River Building Pack [BIGRIVER],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Xotto [DP_XOTTO_INDICATORS],
    Safe Autodoc [safeautodoc],
    Manual Bionic Installation [manualbionicinstall],
    Sleep Deprivation [sleepdeprivation],
    StatsThroughSkills [StatsThroughSkills],
    Garden Pots [growable-pots],
    Draco's Dog Mod [DracoDogMod],
    Alternative Map Key [alt_map_key],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Whaleys Tattoos and Scars [TATTOOMOD],
    Hydroponics [hydroponics],
    Beta National Guard Camp [national_guard_camp],
    sees-player icon, -attitude [sees_player_less_attitude]
]

# Additional context

No item will be consumed during the confirmation windows.

**Comment by ifreund** [comment]
Can't reproduce this.  Are you absolutely sure that your skill was 8 or 9? This sounds like the expected behavior for failing repeatedly.  Have you checked your message log to make sure there aren't failures listed there?

**Comment by DemAvalon** [comment]
My skill is actually 10, here is my save, just go to the car on your right and try to craft mutagem and it will happen.

[Magnolia-Hills.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3260164/Magnolia-Hills.zip)

**Comment by ifreund** [comment]
I'm fairly confident that #31163 will fix whatever is happening here.

**Comment by DemAvalon** [comment]
It did not fix it, the problem persists.

Updated save:
[Magnolia Hills.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3266604/Magnolia.Hills.zip)

**Comment by ifreund** [comment]
Can't confirm on the save you provided or a fresh save.  Are you sure that the build you are running includes that PR?

**Comment by DemAvalon** [comment]
I used the launcher to update it, it says I'm on build 9110 (6 hours ago), I just tried crafting a pair of scissors and some sweet water and it also happened, I swear its happening, I have no Idea as to why it's not happening on your end.

**Comment by DemAvalon** [comment]
I'm also seeing this message pop up now (it happened when I tried to craft the scissors and now after downloading my save above and trying to make mutagen)
![bug](https://user-images.githubusercontent.com/29681506/59118301-27bd7100-8926-11e9-99d3-9ad1a490356a.jpg)

**Comment by IvanShestakov** [comment]
I'm having same issue - it happens mainly with mutagen, but also tainted tallow. 
I'm ok that failed craft reduces progress and requires more ingredients, but it doesn't consume them, even if available. 
Tried to update several minutes ago to build with 1 sec turn, but the problem persists. ...And I'm missing a tool with separation 1 currently - I'm sure it will be easy find since I'm at research facility currently. 
The save file:
[Nursing-exp.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3273901/Nursing-exp.zip)
The debug.log file:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3273907/debug.log)

**Comment by Tairesh** [comment]
Have same Issue with crafting clean water and bathtub with 675 liters of water
 - OS: Ubuntu 18.04
 - Game Version: 0.D-4979-g6a0f1c8
- Savefile: [Эриду.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/3333599/tar.gz)

**Comment by davidpwbrown** [comment]
Cant reproduce on latest master
Had cooking skill 8, all the components for mutagen - including possible replacements ( tainted tallow + blob globs ) crafted, no popups about consuming components, changed cooking skill , still no popups.
No similar issues with scissors or clean water.
