### ISSUE TITLE
Solar Panels CBM doesn't work

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#31134]
# Describe the bug

No charge goes in my implanted batteries when i'm standing outside in the daylight.

# Steps To Reproduce

1. Load the save.
2. Wait 2h.
3. There's no charge in my batteries.

# Versions and configuration
```
Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
```

The thing doesn't produce anything in debug.log. Relevant part of the debug.log:
```
01:14:36.028 INFO : Cataclysm DDA version 0.D-3904-gff906176be-dirty
```

# Additional context

[2018.11.17.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3254679/2018.11.17.zip)

**Comment by kevingranade** [comment]
It's all yours @Ilysen

**Comment by OrenAudeles** [comment]
What mods are you using?

**Comment by l29ah** [comment]
```
[
  "dda",
  "no_npc_food",
  "filthy_morale",
  "novitamins",
  "craftgp",
  "safeautodoc",
  "aftershock"
]
```

**Comment by Ilysen** [comment]
What weather is it? Solar Panels only works when it's Sunny out.

**Comment by l29ah** [comment]
Oh, yeah, it's Cloudy, and it works if i cheat it into Sunny. Strange thing though, IRL solar panels work in cloudy environment as well, albeit providing diminished power output.

**Comment by Ilysen** [comment]
Should be an easy enough change. I can look into tweaking it. For now, though, it's not a bug.
