### ISSUE TITLE
Impossible to continue a partially-botched batch craft

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#31137]
# Describe the bug

Imagine you batch-crafting 9 pine nuts and losing 1 pinecone during the process. If you reacquire the pinecone, you won't be able to continue the craft, and you can't even restart it since the state item cannot be disassembled, even though it tells you now it's made of 8 pinecones.

# Steps To Reproduce

1. Load the saved game.
2. Try to work on the craft on the nearby counter.
3. `These components are missing: 1 pinecone`, even though there's a pinecone in the inventory.

# Versions and configuration

0.D-3936-g9f52909abd-dirty

# Additional context

[2019.06.05.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3254846/2019.06.05.zip)

**Comment by l29ah** [comment]
Now it doesn't consume the required pinecone and proceeding as if it was included.

**Comment by ifreund** [comment]
That's expected for crafts started before  #31163 was merged.  New crafts should function properly
