### ISSUE TITLE
Crash on invalid NPC faction.

### ISSUE THREAD

**Issue by faefux** [CleverRaven/Cataclysm-DDA#31139]
# Describe the bug

If you create an NPC with no or an invalid faction the game will throw an error like with any other json problem but rather than return to the menu it'll crash the binary.

# Steps To Reproduce

1. Create NPC
2. Do not add a faction tag or add an invalid faction tag.
3. Start a game.

# Expected behavior

1. I expect to be returned to the main menu after the error has been thrown.
2. Because this is usual behavior for invalid JSON. 

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: Linux  4.15.0-2-amd64 #1 SMP Debian 4.15.11-1 (2018-03-20) x86_64 GNU/Linux
 - Game Version:  ).D-3936-g9f52909abd
 - Graphics version: Terminal
 - Mods loaded: dda

**Comment by ZhilkinSerg** [comment]
Cannot reproduce on latest version.
