### ISSUE TITLE
Faction Camp can't access extend base plots

### ISSUE THREAD

**Issue by erobbied** [CleverRaven/Cataclysm-DDA#31147]
# Describe the bug
Faction Camp can't access extend base plots IE the kitchen or garage.

After extending a faction Camp to include an extra section. Kitchen, and garage tested. You get the first level of the section, ground cleared and a few pits, but are unable access their section of the interface.

# Steps To Reproduce
1. Build a faction camp
2. upgrade the camp until you can "expand base"
3. Expand base 
4. Try to view the new section

# Expected behavior

# Steps To Reproduce
1. Build a faction camp
2. upgrade the camp until you can "expand base"
3. Expand base 
4. view the new section by pressing < or >

# Screenshots

**If applicable**, add screenshots to help explain your problem.

![Camp1](https://user-images.githubusercontent.com/8155512/58931675-67613e80-8715-11e9-9866-2c3f49360d13.PNG)

![Camp2](https://user-images.githubusercontent.com/8155512/58931678-6a5c2f00-8715-11e9-9b03-2c0b21f74228.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-3949-ge061030 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Rancocas.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3255582/Rancocas.zip)

**Comment by Zetsukaze** [comment]
Same issue as #31141
