### ISSUE TITLE
Let "g" pickup items immediately again!

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#31146]
I think it would be really nice to bring back some of the old function of "g" to pickup items on the fly.
Like if there is only one square with items near you, you will pick it up without choosing where you want to pick it up. If there is multiple items on one square it will go in pickup list.

**Comment by anothersimulacrum** [comment]
I'd prefer if this stayed the same - I like that `g` brings up a list, even if there is only one item.

**Comment by SomeDeadGuy** [comment]
Why tho? Unnecessary actions you need to perform. And you need to do this over and over again.

**Comment by YukariMindGap** [comment]
How about the pickup's behavior's defined in the options menu?

**Comment by SomeDeadGuy** [comment]
Of course. If i can set it up one time and forget about it.

**Comment by faefux** [comment]
I agree with this, it's kind of irritating and throws me off constantly not picking stuff up with g anymore. Open to the other side though, what was the reason for this change?

**Comment by ifreund** [comment]
The reasoning for auto pickup of one item with the `Pickup at player's feet` keybind is that the item's name is printed in the message log when you move to the tile.  This is obviously not the case for adjacent tiles, so it doesn't really make sense to auto pickup a single item.

The argument could be made that a single item on the tile the player is standing on should be auto picked up of that tile is selected when using `g` to pickup nearby items.  However, that would be inconsistent.

**Comment by SomeDeadGuy** [comment]
I do not see how it do not make sense. It makes perfect sense to me.  I want to just take item, and not examine it.
If i want to examine item i would press "e" and same menu what showing up now when you press "g"  would pop up.

**Comment by anothersimulacrum** [comment]
I like the current behavior because I don't play with tilesets where it is always clear what the item is - I prefer that 'g' action examining because it saves me keypresses from pressing `;` to look around and see what the item is, then escaping that, then pressing 'g' and maybe selecting a direction to pick it up.

**Comment by faefux** [comment]
> I like the current behavior because I don't play with tilesets where it is always clear what the item is - I prefer that 'g' action examining because it saves me key-presses from pressing `;` (or `V`) to look around and see what the item is, then escaping that, then pressing 'g' and maybe selecting a direction to pick it up.

I think i changed my mind and like the new method, it'll just take some getting used too. But for what isn't what you're saying is what using 'e' is for? Or am i misunderstanding you?

**Comment by anothersimulacrum** [comment]
`e` isn't totally meant for picking thing up - it's a general interaction button. 
It brings up a menu if you use it to examine a workbench - so it's easier to use the dedicated `g`rab button for everything.

**Comment by Dacendeth** [comment]
I like it the current way because it's consistent in how it works, having the same button change functionality because only one item is on the ground felt awkward.

**Comment by jeremyshannon** [comment]
I just have "," set to "Pick up items at player's feet" and use that instead of "g" if I just want to pick up the item under me.

**Comment by faefux** [comment]
> `e` isn't totally meant for picking thing up - it's a general interaction button.
> It brings up a menu if you use it to examine a workbench - so it's easier to use the dedicated `g`rab button for everything.

Oh, yea. I have to admit having that whole menu come up whenever you 'e' on a table is suuupppper irritating. Maybe we should change the button for using something as a workbench?

**Comment by anothersimulacrum** [comment]
No, I think `e`xamine is the right action for that - a different key should be the primary key for picking up items.

**Comment by kevingranade** [comment]
Feel free to rebind 'g' to "Pickup Item(s) at Player Feet" as implemented in #30346
