### ISSUE TITLE
Faction camp bug

### ISSUE THREAD

**Issue by Zetsukaze** [CleverRaven/Cataclysm-DDA#31141]
# Describe the bug

Faction camp cannot upgrade expansions through bulletin board.

Another issue (maybe not?): Number of expansions available are dependent on the number of followers you have.

# Steps To Reproduce

1. Make a camp with any expansion
2. Interact with bulletin board, unable to tab to other expansions

# Screenshots

![image](https://user-images.githubusercontent.com/1698993/58921507-ade08880-8769-11e9-95ea-ab13cb716078.png)

# Additional context

Save file:
[CampBug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3254945/CampBug.zip)

**Comment by Zetsukaze** [comment]
Faction camp where expansions do not work still occuring on build 9116

[Temp.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3268905/Temp.zip)

**Comment by davidpwbrown** [comment]
Works fine for me.... I dont have all the mods in the modlist though.
