### ISSUE TITLE
Magiclysm's 'Root Strike' spell crashes the game with a kill.

### ISSUE THREAD

**Issue by preacherpix** [CleverRaven/Cataclysm-DDA#31143]
# Describe the bug

When using Magiclysm's 'Root Strike' spell, upon getting a kill, the game forcibly closes with an error window (posted below) on the same move the spell is cast, the enemy is killed, and the "You cast Root Strike!" message is printed into the chat log.

# Steps To Reproduce

1. Start a new game as a Druid (or just debug in the spell)
2. Learn the 'Root Strike' spell and level it up to use it
3. Attack an enemy with it until they die, which crashes the game.

# Expected behavior

I can't imagine an attack is meant to crash the game, lol.

# Screenshots

N/A

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-3936-g9f52909 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]

# Additional context
Crash log:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3255177/crash.log)

Save file:
[MAGICLYSM TESTING.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3255174/MAGICLYSM.TESTING.zip)

**Comment by DarianLStephens** [comment]
This isn't quite related, but how do you even cast a ranged spell? Pressing 'Enter' just makes it ask if I want to cancel the spell cast, pressing RMB does the same even though it's listed as 'Fire' in the menu on the right, so I've got no clue.
I've just learnt Magic Missile, trying to cast it out in to the open to practice, but to no avail.

**Comment by KorGgenT** [comment]
magic missile must be cast on a creature. open ground is not a valid target for that spell.

**Comment by Lucewithnootherideas** [comment]
i have the same issue with freezing spells, my guess is if anything causes and effect and kills at the same time it crashes the game

**Comment by Randonx** [comment]
Can confirm, Root Strike crashed my game upon a kill as well.
