### ISSUE TITLE
Local and Global factions.

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#31148]
**Is your feature request related to a problem? Please describe.**  
We have more factions and more fleshed out factions, but they are all global factions.  They are all very large and interconnected across the whole world.  All Bandits are Hell's Raiders.  If you anger one evac center, you anger all of them. Faction relations are predetermined and static.

Global factions are good for big groups with unifying themes, and for adding custom dialog, but for generic groups like survivors, bandits, farmers, small local groups make more sense.  

**Describe the solution you'd like**  
1> Overmap specials would have a flag for being inhabited by a local faction.
2> On map generation it would give local factions a unique id and random name.
3> Faction attitudes could be defined from a template or determined by the map, like proximity to other groups, etc.
4> When the player approached, it would spawn (static) NPCs belonging to the local faction.

So, if there were two inhabited malls next to each other, the player could fight one and join the other, because they would not belong to a global 'Mall Survivor' faction.

**Additional context**  
I don't know what features or goals are planned for factions, but I think things would be more dynamic with smaller players mixed in with the big factions.  More people to fight or recruit. More alliances and rivalries.  Most importantly, different playthroughs would be more randomized based on what appeared on the map.

**Comment by Atherum** [comment]
I like your ideas, and it fits into a suggestion I'm going to make about the sorts of things that a player/npc faction might be able to do in the long run.

**Comment by kevingranade** [comment]
So in short this is "procedurally generated micro-factions".
I had planned to do this sort of thing, but evidently I don't have any notes anywhere on it.

As written this is too vague to act on, there's a lot of infrastructure we need to add to make NPCs capable of self-assembling into a faction, chosing a base, settling in, etc, and this doesn't provide an outline of making that happen.

This level of detail can go in the design document though, I'll look into incorporating it.

**Comment by SunshineDistillery** [comment]
> self-assembling into a faction, chosing a base, settling in, etc,
That's really advanced. I'd love for that stuff to be in the game but I was thinking of a simpler thing that would be mostly set in the jsons. 

Define an NPC class called farm_inhabitant with faction set to local_generated
Define a faction template called farm_inhabitants (with some rng values)
Make a mapgen special called inhabited_farm
Place static NPCs in the om_terrain

Basically the same way same way evac shelters are done now, except all NPCs would belong to a generated local faction instead of a global one. 

More complex versions would be also  great, but that's beyond me.
