### ISSUE TITLE
Crash when starting a new game

### ISSUE THREAD

**Issue by matskuman5** [CleverRaven/Cataclysm-DDA#31152]
Crashes rarely (1-2% chance) when starting a new game with the preset character "Vegas"
Might have something to do with tilesets

Save:
[Fortnite_copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3257226/Fortnite_copy.zip)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3257227/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3257228/debug.log)

Info:
- OS: Windows
    - OS Version: Windows 7 Ultimate 64-bit
- Game Version: 0.D-3980-geb4b37c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Prevent Zombie Revivication [no_reviving_zombies],
    sees-player icon, -attitude [sees_player_less_attitude]
]

**Comment by ZhilkinSerg** [comment]
Please report if you can still reproduce it on latest version.
