### ISSUE TITLE
Car showroom content weirdness

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#31153]
# Describe the bug
Car showroom location is mostly containing motorcycles. Additionally, all of them seem to be banged up, weird for content of a showroom, in location otherwise experiencing no sign of any violence. 
Additionally, during the playthrough one of the cabinets contained, among other things, 10 various survivor notes. Given nature of the notes and descriptions of various, wildly different events often hinting at imminent death of the writer, a bunch of them in one place is weird, especially since there are no signs of any permanent residence by post-cataclysm survivor who would be collecting these.

# Steps To Reproduce

Visit the car showroom location or check its design in json.

# Expected behavior

Given the good state of the location, all the vehicles contained within should be in pristine condition though possibly without power and/or fuel. Potentially, it should be more cars and less motorcycles if it's a car showroom.

The location shouldn't include more than a single survivor note, keeping it consistent with other such locations.

# Versions and configuration

Experimental, tiles, 0.D-3956-g588f8e0 (build 9097) run on Win7
Mods used: DDA, Icecoon's Arsenal, Boats, Vehicle Addition Pack, Tanks and Other Vehicles, No Fungal Monsters, No Flaming Weapons, StatsThroughSkills

**Comment by Xenomorph-III** [comment]
This is a good idea - and a potential risk/reward situation (get a rare pristine vehicle NOW, before monsters get to it, or repair a common, wrecked one.)
