### ISSUE TITLE
Mattress disappears when trying to deploy to a place where it's not possible

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#31150]
# Describe the bug

Mattress disappears when trying to deploy to a place where it's not possible. 

# Steps To Reproduce

1. Make a bed frame.
2. Try to deploy mattress on top of it.
3. see a message saying it cannot be deployed there and mattress disappears. 

Bed frame is not necessary can be any other furniture or wall or anything. 

# Expected behavior

I keep the mattress, if I can't deploy it.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-3913-g4422887 [64-bit]
- Graphics Version: Tiles

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of June 06, 2019. 
Spawned a bed frame, spawned a mattress (had to take it in my hands as I don't have enough free volume for it). Tried to deploy mattress on a bed frame, "You can't deploy a mattress there.". Mattress is still in my hands.
