### ISSUE TITLE
Items,vehicle and constructed terrain vanish

### ISSUE THREAD

**Issue by Yonsisac** [CleverRaven/Cataclysm-DDA#31167]
# Describe the bug

Load save normally,imedietly after finalization debug appears and large number of debug errors appear. Once the large strain of debug is done the game begins but All items and vehicles have dissapeared. Area where base was build (ranch) has "reset" as it was never touched or looted. The player character remain untouched, still have all the items and clothes as rememberd befor the load. Once I take a step more debug appears dame as the last.

# Steps To Reproduce

Unknown. Previusly has happen befor to me but can't find cause of it. I wait always for game to save properly and such suspect of what causes it is unknown and at random

# Expected behavior

All constructed terrain,items dropped and vehicles placed/moved by player seem to vanish and area seem to reset.

# Screenshots
![Capture4](https://user-images.githubusercontent.com/51425610/58998128-4a884200-87cd-11e9-9901-00c995695260.PNG)

![Capture](https://user-images.githubusercontent.com/51425610/58998118-3e9c8000-87cd-11e9-99f5-0b0b5f90f8af.PNG)

![crash](https://user-images.githubusercontent.com/51425610/58998153-5c69e500-87cd-11e9-9031-488965e09d8e.PNG)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D (Stable)
 - Graphics version: Tiles
 - Mods loaded: Dark days ahead,Bens BF Recipes,Craftable gun pack,Deadleaves' fictional guns,extended realistic guns,growa
ble pots,ice con's arsenal,makeshift items mod,medical and historic content,more survival tools,mythological replicas,dinomod,modular turrets,salvaged robots,mutant NPCs,More locations,Fuji's more buildings, urban development,boats,folding parts pack,vehicle additions pack,tanks and other vehicles,necromancy,(DP_RP) xotto indicators,No big zombies,StatsThroughSkills,sleep Deprivation,simplified Nutrition,Safe autodoc,prevent zombie revivication,manual bionic instalation,filthy cloathing,disable NPC needs,classic rogue like classes,classes and scenarios Mod

# Additional context

[Save file and Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3259464/Save.file.and.Debug.zip)

**Comment by kevingranade** [comment]
Can you post copies of any of the files referenced? I'm afraid based on
those errors that you might have some save corruption which unfortunately
we don't have any way to recover from.

**Comment by davidpwbrown** [comment]
Yeah, a lot of the map files are completely borked and have gibberish inside of them instead of text.
When you first mentioned it I thought it might be an error based on some old save being loaded with a recent game, and it just not understanding some serialized objects.

But no it's completely corrupted, and its a lot of the map files too.

Sorry it may not be retrievable.

**Comment by Yonsisac** [comment]
Wierd. I was fine and all and sudently that happen :/ it's like happen at random. And kevin I posted in the additional context the save file with the dedug.

Well. Guess I am off to start fresh. Going to re-download the game and all fresh just to make sure but thanks.

**Comment by kevingranade** [comment]
My guess is your computer lost power shortly after saving, which can leave numerous files corrupted like this.
Cataclysm never opens more than one file at a time, so I can't think of a scenario where the program would corrupt a large number of files.
Regardless, this doesn't leave us with anything to investigate, so I'm closing.
