### ISSUE TITLE
Strange examine issue

### ISSUE THREAD

**Issue by Zetsukaze** [CleverRaven/Cataclysm-DDA#31186]
# Describe the bug

Examining a fire in a stove, the display of timing for the duration that the fire would last keeps changing

# Steps To Reproduce

1. Light a fire in a stove
2. Examine it when all the wood turns to wood ash
3. ....Profit?

# Expected behavior

To show only one duration

# Screenshots

![wonkyExamine](https://user-images.githubusercontent.com/1698993/59052889-b9939280-88c2-11e9-9d64-f04a1fae81b0.gif)

# Versions and configuration

Build 9099

# Additional context

I waited an hour after setting the fire, defrosting water in a toilet bowl o.0

**Comment by chronicpayne** [comment]
I think this is the same as #31068

**Comment by Zetsukaze** [comment]
Y

> I think this is the same as #31068

Yes, thank you! Closing this duplicate
