### ISSUE TITLE
Ideas for advanced factions

### ISSUE THREAD

**Issue by Atherum** [CleverRaven/Cataclysm-DDA#31182]
**Is your feature request related to a problem? Please describe.**  
The faction system opens up some really incredible opportunities to implement some of the systems that have long been requested. These include advanced manufacturing, deeper mission systems and interaction with the actual gameworld.

**The Advanced Faction system**  
Firstly, in keeping with the game's design direction, many of the modern manufactured goods/tools/materials that are available to us today are unrealistic for even a small group of people to develop and work on. However, with the an expansion to the Faction system, it might be possible to essentially have a chain system of technological advancement. This new chain would only be available to players that invest in their factions, factions that are at the highest base level in the current system and that are at a certain count of faction members.

I imagine that this would look like a step system beginning essentially where the player is at the moment. Scavenging for supplies, farming at a basic level, producing simple goods from the junk and scrap of the old world. However, there is also an alternative here, the Faction might decide to focus on more primitive/pre-modern technologies such as reliance on animal driven vehicles, weapons such as medieaval ones, crossbows and bows. Generally though, it is likely people would start from the normal Junk level of tech. 

From there, at a certain milestone, the level might be able to be upgraded and move into some sort of material self-sufficiency like harvesting basic metals and so on, this would perhaps also be accompanied by larger scale manufacturing techniques that may work of the previous tech level, such as jury rigging pressing equipment or metal working tools. This might produce materials and goods at a level equivalent perhaps of 19th century or early 20th century technology.

Earlier I mentioned the possibility of having a low tech version of an advanced faction, this might be for purely gameplay reasons to have an option for those looking for an innawoods or primitive simulation (Reclaiming the world with an army of knights or nomadic hunter-gatherers sounds awesome), it could also link in with magic mods such as Magiclysm, which already has laid a distinction down between tech and magic.

**Mission/Quests, Dynamic problems**
These factions might be able to form the basis for a wider quest system, where the Player faction would pursue goals. It is also possible that through this interaction, deeper elements of the game lore might be explored, for example a series of missions that involve a Lab in order to gain more information into the nature of one of the cataclysmic events that occured. Example: Researching the Blob and weapons/tactics to use against it.
This could also lead to a sort of defense mode where your faction bases were attacked by the enemy/ies that you were confronting. However, in order to avoid the Fallout 4 settlement attack spam, this would likely be initiated by the player.

**Npc factions get the same capability**
Finally for those players that are not interested in investing in the system or factions in general, may be able to trade for the goods and services that an advanced faction could provide. This would be even more dynamic if, as others have suggested, minor npc factions were also capable of being formed and then they would have access to the same system.

**Potential Issues**
Of course, these suggestions may be well outside the bounds of the game, both stylistically and mechanically. One major issue might be the performance loss that definitely would occur from such a high npc count as would make these changes feasible. A possible solution might be essentially having things like the majority of the npc population "living" in the background, but that might become to much of a spread sheet, and purely interacting with menus would quickly lose its flavour.

Any criticism constructive or otherwise is of course welcome. Above all, this game is awesome, and opens up so many possibilties and interesting scenarios.
Apologies for the wall of text, it is unlikely this will be read so sorry :)

**Comment by I-am-Erk** [comment]
This is basically the plan. I think most of this is outlined in the design document currently. It's a long way off; you could accelerate by joining the coding efforts! Even someone with no current skills could help by learning a little mapping (very easy) and starting to make faction base maps for various common buildings.
