### ISSUE TITLE
"Invalid computer action bonesetting"

### ISSUE THREAD

**Issue by AngrySasquatch** [CleverRaven/Cataclysm-DDA#31181]
# Describe the bug

When generating a map for a new game, or loading said save, I get the following message:

DEBUG    : Invalid computer action bonesetting
 
 FUNCTION : computer_action computer_action_from_string(const string&)
 FILE     : src/computer.cpp
 LINE     : 1930

When I discussed this bug on the Discord server, user Dpwb mentioned that the bug may be caused by the 'safe autodoc' mod.

# Steps To Reproduce

Generate a world with the mod list, or use the save file in the attached dropbox link. I have also attached the relevant error log from the game files.

# Expected behavior

Besides the error showing up on world generation, I haven't seen anything happen just yet.

# Versions and configuration

OS: Windows 10
Game Version: 0.D-3993-g5542d7b (tiles)
Build: 9104
Mods: 
Disable NPC Needs
Safe Autodoc
SpeedyDex
Classes and Scenarios Mod
Manual Bionic Installation
StatsThroughSkills
Icecoon's Arsenal
DeadLeaves' Fictional Guns
Garden Pots
Gun Cotton
Makeshift Items Mod
Medieval and Historic Content
More Survival Tools
Alternative Map Key
Hydroponics
Mutant NPCs
Beta National Guard Camp, Aggregate's edit
More Locations
Fuji's More Buildings
Urban Development
Folding Parts pack
Vehicle Additions pack
Tanks and Other Vehicles

# Additional context

The save file and debug log segment are attached below.
[Save File.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3261992/Save.File.zip)
[debug log.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/3261993/debug.log.txt)

**Comment by TheGoldenStarOfVerity** [comment]
I get this error as well with some of the newer game versions.
This comment is mainly to say that I don't use the Safe Autodoc mod and this error will still occur for me.

**Comment by ejseto** [comment]
It's a problem with Fuji's More Buildings. It still has a bonesetting computer that hasn't been updated into an autodoc or removed.
