### ISSUE TITLE
Chickenwire gates and fences provide 2000 nails on deconstruct

### ISSUE THREAD

**Issue by Nezune** [CleverRaven/Cataclysm-DDA#31208]
# Describe the bug

Chickenwire gates, fences and some other fence types are using "count" instead of "charges" for the amount of nails created on deconstruct, look in terrain.json for these:
* t_chickenwire_gate_c
* t_chickenwire_gate_o
* t_chickenwire_fence
* t_splitrail_fence
* t_privacy_fence 

# Steps To Reproduce

1. Build a chickenwire fence or gate
2. Deconstruct it
3. Swim in your pile of nails like a poor-mans scruff mcduck

# Expected behavior

Deconstruction provides 20 or less nails by using "charges" instead of "count"

# Versions and configuration

 - Game Version: 0.D-3992-g9382262

**Comment by dom4op** [comment]
Just a friendly reminder: they are also impossible to build.
#31018
