### ISSUE TITLE
Camp extensions still broken, just slightly differently

### ISSUE THREAD

**Issue by Carrnage** [CleverRaven/Cataclysm-DDA#31200]
#31183 
#31141
#31147

# Describe the bug

When an extension is made by surveying it's tab is inaccessible in the menu after saving and reloading the tab is accessible but selecting an option just closes the menu

# Steps To Reproduce

1. Create a Faction Camp
2. Survey an Extension
3. Attempt to access extension tab on the bulletin board menu
4. Save and Reload
5. Open the now accessible extension Tab and select any option

# Expected behavior

Extension tabs should be accessible without saving and reloading, and after saving and reloading options should do something besides simply closing the menu

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-4012-g0121072 [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

attached are three saves one before sending an NPC to survey one with them ready to be recovered at the end of the survey and one after the extension has been placed

[Camp test 3 saves at different stages.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3264348/Camp.test.3.saves.at.different.stages.zip)

**Comment by davidpwbrown** [comment]
mea culpa, I thought I fixed it, but it was a band-aid over the problem and not even a good one.
