### ISSUE TITLE
Sewer rat corpse doesn't spoil

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#31218]
# Description
Sewer rat corpses don't spoil.

upd: The corpses seem to spoil normally, but the information about spoiling is not shown in the item description. However, when the inventory is sorted by spoilage, the corpses seem to be assigned correct positions.

# Steps To Reproduce
I killed the rats in the basement and put the corpses in the inventory. Dropping the corpses above ground also didn't make them spoil.

# Expected behavior
The corpses should spoil.

# Screenshots
![image](https://user-images.githubusercontent.com/6495727/59125459-134f9780-896b-11e9-8dc1-d74257517a82.png)

# Versions and configuration
 - Debian 10
 - Game Version: 0.D-3993-g5542d7babd
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Bens GF recipes, Bionics Systems Mod, Makeshift Items Mod, Garden Pots, NPC Traits, Folding Parts pack, Classes and Scenarios Mod, Disable NPC Needs, StatsThroughSkills

**Comment by Hirmuolio** [comment]
If you enable debug mode (not bound by default) and look at the corpse what does it show?

**Comment by tsulh** [comment]
> If you enable debug mode (not bound by default) and look at the corpse what does it show?

Sorry, I don't have the save with the sewer rat corpses anymore.
