### ISSUE TITLE
no clean water recipe

### ISSUE THREAD

**Issue by Lucewithnootherideas** [CleverRaven/Cataclysm-DDA#31224]
# the normal clean water recipe wont come up
 
i have the modded and water purifier clean water recipes but not the boiling clean water

# its in the latest version 9112
![image](https://user-images.githubusercontent.com/51459975/59140354-d5417c00-8948-11e9-9475-6ade4caf6e1c.png)

 - OS: [windows 10
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: Tiles
 - Mods loaded:[
  "dda",
  "no_npc_food",
  "aftershock",
  "Tolerate_This",
  "Bootleg_Walkers",
  "craftgp",
  "FIC_Weapons",
  "realguns",
  "ew_pack",
  "growable-pots",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "modular_turrets",
  "PK_REBALANCE",
  "Salvaged_Robots",
  "alt_map_key",
  "Cata++",
  "crazy_cataclysm",
  "hydroponics",
  "Mining_Mod",
  "mutant_npcs",
  "MMA",
  "national_guard_camp",
  "more_locations",
  "FujiStruct",
  "mapgen_demo",
  "Urban_Development",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "Arcana",
  "necromancy",
  "jury_rigged_robots",
  "Battery_Overhaul_Legacy_Mode",
  "more_classes_scenarios",
  "RL_Classes",
  "manualbionicinstall",
  "safeautodoc",
  "StatsThroughSkills",
  "guncotton",
  "crt_expansion",
  "magiclysm",
  "fast_healing"
]

**Comment by Rivet-the-Zombie** [comment]
Have you possibly hidden the recipe? Check under your crafting `*` tab, `HIDDEN` sub-tab.

**Comment by Lucewithnootherideas** [comment]
welp..i forgot that was a feature thanks for pointing out the obvious its a lot more useful then most people think
