### ISSUE TITLE
COMPILING.md needs to mention that CLANG accepts specifing a version

### ISSUE THREAD

**Issue by WhiteHusky** [CleverRaven/Cataclysm-DDA#31229]
Was setting myself up to use the latest and greatest `clang` with `clang-8` to compile Cataclysm with, but it'd error with `CLANG=1` and mention that `clang++` doesn't exist. It took a brief code-dive to find that `CLANG` accepts something like `CLANG=clang++-8` so it might be wise to mention that feature if people are trying to use the latest version of `clang`.

**Comment by ZhilkinSerg** [comment]
Well, it is kinda mentioned in Makefile if you know where to look at.

**Comment by WhiteHusky** [comment]
@ZhilkinSerg Did take a look at `Makefile` and it does mention examples of what each options does at the top of the file, but doesn't mention anything about substituting `1` with whatever version of `clang++` unless you attempt to follow the logic for were the `CLANG` argument is parsed.

**Comment by WhiteHusky** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/34de66244455183e3dc1cf142f63bc29e564433d/Makefile#L1-L79

**Comment by ifreund** [comment]
We should definitely add this to the comments at the top of the Makefile, if not to COMPILING.md as well.  A pull request doing this would be great.
