### ISSUE TITLE
Make computers use NPC dialogue system

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#31225]
**Is your feature request related to a problem? Please describe.**  
I've just recently been playing around with NPC dialog, missions, and mapgen updates and there is a lot of really cool stuff there for modders and json-editors.  I'm glad to see it get so much work and de-hardcoding.  

If computers used the same system for dialog (or mostly the same) it would open up lots of possibilities. Computers are pretty lackluster, giving them dialog would make them more interesting, replace some pretty wack hardcoded options, take advantage of any future NPC features, and move all this stuff to jsons for modders and non-coders. 

**Describe the solution you'd like**  
1. A computer would have some kind of pseudo-NPC status.
2. It would have a way to define its starting talk topic 
3. Add a few new dialog trials based on computer skill or INT rolls.
4. Make new talk topics specifically for interacting with computers. (TALK_SHELTER_COMP)

**Additional context**  
This would allow :
- replacing the toggle-comp mission-objective with dialog 
- replacing door-opening with smarter mapgen_updates
- replace activate elevator with mapgen_update
- turning on lights with mapgen_update, floor-> floor w/oh lights
- retractable bridges with mapgen_update
- summoning any type of monster or monster group
- player learning passwords, effects or variables
- computer printouts for recipes and maps
- conditions based on having/giving software items, HackPro
- conditions based on items, electrohack
- mimicking control of certain machines, like opening vending machines
- changing faction relations
- offering or completing missions
- building a basecamp computer instead of assigning a fragile NPC the role
- lots of Fallout style journal entries

**Comment by Zireael07** [comment]
I'd change issue title to 'Make computers use NPC dialogue system' or something similar, to make it clear you're not trying to make computers into fully fledged NPCs :)

**Comment by faefux** [comment]
This is a really great idea, i've been thinking a lot recently about how there could be a lot of potential if we were able to do a u_has_var check and give effects via computers. :)
