### ISSUE TITLE
give mapgen_update to scenarios

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#31226]
**Is your feature request related to a problem? Please describe.**  
The mapgen_update for NPC dialog is really useful for editing maps for missions and such.  If it were available for scenarios it would allow all kinds of neat tricks.

**Describe the solution you'd like**  
1> Define a mapgen_update_id in a starting scenario.  
2> Have it run once, centered on player, right as the game begins. 

**Additional context**  
This would allow modders to add:
- starting vehicles or wrecked vehicles
- custom NPCs instead of standard shelter NPC
- groups of NPCs, like a group of cops in a police station
- NPCs already following you/in your faction
- surrounded starts with any monster or monster groups
- friendly or named monsters/pets 
- hazards like fire, webs, smoke, shock vents, landmines, etc.  
- unique starting location, you won't find spawned anywhere else in the world, 
- modified locations, boarded up windows, smashed terrain
- bulk items, wheelbarrow full of bricks

You could have a No Place Like Home scenario, where you start in a custom house with your wife, and two kids, who all have custom NPC dialog.  The house would have unique items like photos of your mom and your bowling trophy.  50% chance of having a pet cat or dog.  A car in the garage would be called 'family minivan'.

**Comment by ZhilkinSerg** [comment]
You already can use map extras for that.

**Comment by SunshineDistillery** [comment]
Aren't map extras mostly hard-coded?  If map-extra functions were jsonized then it would work the same.

**Comment by anothersimulacrum** [comment]
JSON support for map extras was added in #31682
Does that resolve this issue?
