### ISSUE TITLE
errors related to refugees Dana and Pablo Nunez on game loading

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#31232]
# Describe the bug

When loading the game after updating to 7ebf7fa00021dfdd75eae24bf8a55e942d3d69e3 or 34de66244455183e3dc1cf142f63bc29e564433d, several errors related to refugees Dana and Pablo Nunez appear.

# Steps To Reproduce
Load the game when updated to commit 7ebf7fa00021dfdd75eae24bf8a55e942d3d69e3 or 34de66244455183e3dc1cf142f63bc29e564433d.

# Expected behavior

No errors appear on loading the game.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster);
- Game Version: 0.D-4079-g7ebf7fa000 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Bens GF recipes [Tolerate_This],
    Bionics Systems Mod [bio_mod],
    Makeshift Items Mod [makeshift],
    Garden Pots [growable-pots],
    NPC traits [npc_traits],
    Folding Parts pack [deoxymod],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

[Novelty.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3268446/Novelty.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3268456/debug.log)

When using the previous commit, b81ea79d33adbaa9d880976a286ec4c066c1e5b2, the problem does not appear.

upd: If I start a new game with the latest commit, 34de66244455183e3dc1cf142f63bc29e564433d, no error occurs. So might be it's just incompatibility with the older saves?

**Comment by ZhilkinSerg** [comment]
Yes, that is just a non-gamebreaking warning during savegame loading. It is not critical, but it would be nice to handle such cases somehow.

**Comment by tsulh** [comment]
(The errors are still there when loading the old save in the current game, so I guess the issue should stay open.)

**Comment by Night-Pryanik** [comment]
I guess this could be safely closed after more than 1.5 years.
