### ISSUE TITLE
Error with mining mod

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#31237]
# Describe the bug

getting this error message when trying to load my save, as soon as it gets to mining mod, also occurs in a new world with the mod.:
 DEBUG    : Error: data/mods//Mining_Mod/furniture.json: line 3:27: missing mandatory member "description"

[
  {
    "id": "f_anvil_stone",
                          ^
    "type": "furniture",
    "name": "stone anvil",
    "symbol": "^",

 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 709

# Steps To Reproduce

try to play a world with mining mod.

# Expected behavior

this not happening

# Versions and configuration

version:0.D-4088-g34de662 (tiles)
build: 9114

**Comment by ZhilkinSerg** [comment]
We do not support third party mods here. Please contact mod author/supporter to fix it.

Some terrain and/or furniture definitions are missing mandatory node "description" (see #31180).

**Comment by ZhilkinSerg** [comment]
We do not support third party mods here. Please contact mod author/supporter to fix it.

Some terrain and/or furniture definitions are missing mandatory node "description" (see #31180).

**Comment by DemAvalon** [comment]
Ah!, got it thanks for the link, now I know what's wrong and can fix it myself.

**Comment by GitGodScrub** [comment]
A fix has been commited on the mod’s page. 
@DemAvalon
