### ISSUE TITLE
Errors with the Draco's dog mod.

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#31238]
# Describe the bug

errors with what I assume is @DracoGriffin 's mod:  
DEBUG  : monster mon_dog has no harvest entry
 
 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1001
 DEBUG    : monster mon_dog_bull has no harvest entry
 
 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1001
 DEBUG    : monster mon_dog_pitbullmix has no harvest entry
 
 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1001
 DEBUG    : monster mon_dog_beagle has no harvest entry
 
 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1001
 DEBUG    : monster mon_dog_bcollie has no harvest entry
 
 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1001
 DEBUG    : monster mon_dog_boxer has no harvest entry
 
 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1001
 DEBUG    : monster mon_dog_chihuahua has no harvest entry
 
 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1001
 DEBUG    : monster mon_dog_dachshund has no harvest entry
 
 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1001
 DEBUG    : monster mon_dog_atk has no harvest entry
 
 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1001
 DEBUG    : monster mon_dog_atkbull has no harvest entry
 
 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1001
(there are manny similar errors for all dogs I assume)
also: 
DEBUG    : Harvest list armor_dog has invalid entry: null type, null type, null type, null type, null type, null type, null type, null type, null type, null type, null type, and null type
 
 FUNCTION : static void harvest_list::check_consistency()
 FILE     : src/harvest.cpp
 LINE     : 156

# Steps To Reproduce

1. Make a player with a gun, magazine, and some ammo.
2. Try to aim at a wall.
3. There's no way to increase aim level.

# Expected behavior

this not happening.

# Versions and configuration

Build:9114 (2 hours ago)
version:0.D-4088-g34de662 (tiles)

# Additional context
this has been happening for a few versions, I just didn't post anything before because it seems harmless, Also I'm opening this issue assuming Draco's dog mod is not a third party mod but if it is I'm sorry.

**Comment by DracoGriffin** [comment]
It isn't an official mod.

Please post this issue on the [DracoDogMod GitHub here.](https://github.com/DracoGriffin/DG_Mods/issues?q=is%3Aopen+is%3Aissue).

Thank you for the report.
