### ISSUE TITLE
Ammo conserving mode for turrets.

### ISSUE THREAD

**Issue by nexusmrsep** [CleverRaven/Cataclysm-DDA#31246]
**Is your feature request related to a problem? Please describe.**  
Turrets mostly use automatic fire and spray bullets like there's no tomorrow.
A single zombie horde will deplete the turret's ammo in no time.

It is possible to switch mode depending on distance to target, or simply set the turret to single file mode, but this happens in the JSON file and no AI controls is internally.
However, taking into consideration the capacity of turrets, if you aim for longevity, but crave for that extra firepower from the auto-mode, you want a better design.

**Describe the solution you'd like**  
Turrets should have ammo conservation mode, and switch to single fire mode if ammo reserves go low (50-25%). This can be set in JSON for more control.

**Describe alternatives you've considered**  
Autofire sounds fine in movies, but considering that you can empty MP5 magazine in 2 seconds in burst, its not a good design for low-capacity turrets unless they have magazines like the Vulcan cannon [CIWS ](https://www.youtube.com/watch?v=-L0ZAGOuaqg)

**Comment by Firestorm01X2** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/29424
https://github.com/CleverRaven/Cataclysm-DDA/issues/28985
