### ISSUE TITLE
Reading only takes a few minutes

### ISSUE THREAD

**Issue by GitGodScrub** [CleverRaven/Cataclysm-DDA#31248]
# Describe the bug
Reading now only takes a few minutes, as opposed to half an hour before.

# Expected behavior
Reading should take a lot longer.

# Screenshots
Before:
![image](https://user-images.githubusercontent.com/18603041/59151079-920d0900-8a2d-11e9-80ed-ee7ea38f5d9e.png)

After:
![image](https://user-images.githubusercontent.com/18603041/59151276-a0a8ef80-8a30-11e9-8f43-bce5fcc5ef2d.png)

# Versions and configuration 
**(Non-updated version)**
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4039-g02eaddf [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bootleg Walkers [Bootleg_Walkers],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Beta National Guard Camp [national_guard_camp],
    Dorf Life [Dorf_Life],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    Necromancy [necromancy],
    Manual Bionic Installation [manualbionicinstall],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context
I think that it is because of https://github.com/CleverRaven/Cataclysm-DDA/pull/30253 that reading only takes a few minutes. 
The way i understood it, it was not intended to affect reading.
I am pretty sure that it also break the game-balance completely.

Save from Build #9112:
[Clemson.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3268843/Clemson.zip)

**Comment by YukariMindGap** [comment]
Book reading time still uses turn count to read as opposed to a time unit.
Will be fixed, probably

**Comment by ymber** [comment]
#30826 should have preempted this. I'll look into what's going on.

**Comment by Leosky** [comment]
The isssue is coming from the reading action being move speed based. Now turn are 6times shorter, reading is too quick too.

**Comment by Feuerhai** [comment]
This should probably be closed. It wasn't auto closed because the wording was slightly off.

**Comment by kevingranade** [comment]
Thanks for the reminder.

**Comment by l29ah** [comment]
Now it takes only a few seconds:
![](https://pstbin.ru/f/16743/)

**Comment by ymber** [comment]
See #31516.
