### ISSUE TITLE
Character get sent back in time on load.

### ISSUE THREAD

**Issue by GitGodScrub** [CleverRaven/Cataclysm-DDA#31249]
# Describe the bug
The date gets messed up, when loading in an game from Build #9112.

# Expected behavior
The date is way off, i think it has reverted to Spring/jumped forward to next Spring.
I think that 

# Screenshots
Before:
![image](https://user-images.githubusercontent.com/18603041/59151086-af41d780-8a2d-11e9-8481-85cf5a771658.png)

After:
![image](https://user-images.githubusercontent.com/18603041/59151228-c2ee3d80-8a2f-11e9-8714-7d3f9a581d4a.png)

# Versions and configuration 
**(Non-updated version)**
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4039-g02eaddf [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bootleg Walkers [Bootleg_Walkers],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Beta National Guard Camp [national_guard_camp],
    Dorf Life [Dorf_Life],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    Necromancy [necromancy],
    Manual Bionic Installation [manualbionicinstall],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context
I think that it is because of https://github.com/CleverRaven/Cataclysm-DDA/pull/30253 .
Season length is set to 14.
Start date was Spring 1

I am not quite sure how the date is calculated, but here is my guess:
Before:
`1 day = 24*60*(60/6) = ‭14400‬ ticks`
Now:
`1 day = 24*60*(60/1) = 86400 ticks`
Difference:
`+72000‬ ticks`

`Spring day 1 -> Autumn day 10 = ‭38‬ days`
Before:
`38‬ days = 547,200 ticks`
Now:
`38‬ days = 3,283,200 ticks`
Difference:
`+2,736,000 ticks`

Now, since the game know that the "date" is 547,200 ticks, that is equal to 6.3 days, according to the new date-system.
That means that the date is now:
Spring 7

Save from Build #9112:
[Clemson.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3268843/Clemson.zip)

**Comment by kevingranade** [comment]
I need to do some testing but we can probably just roll the calendar forward for people suffering from this problem. The main thing I need to check for is that we don't advance rot or zombie mutation by doing so, as far as I know you're currently counting as being behind where you're expected to be so that should be fine.

**Comment by kevingranade** [comment]
For 0.E, we need to verify whether migrating a save from 0.D to 0.E causes this problem, if it does we need to apply the fix, but if there is just some span of experimental releases that are affected, fixing it would do more harm than good.

**Comment by KorGgenT** [comment]
so i started a save on summer 1 with standard season lengths and waited a few days. then i moved the save to most recent master and got the following: 
![image](https://user-images.githubusercontent.com/30208401/70358344-23c3ca80-1847-11ea-9f0a-0d903b48e5b6.png)
