### ISSUE TITLE
Crafting takes a lot more real time now.

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#31252]
# Describe the bug

crafting now takes much longer REAL time, a two-hour craft recipe can take several minutes.
Compare the time between before #30018 and after (at least that is what I think the cause is) 

# Expected behavior

crafting does not consume more of my real life than it used to.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4103-gc30bad0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Filthy Clothing [filthy_morale],
    Simplified Nutrition [novitamins],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Extended Realistic Guns [realguns],
    Craft Ammo Mags - ERG [SD_Magcrafting_Realguns_Extension],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Crazy Cataclysm [crazy_cataclysm],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    NPC traits [npc_traits],
    Zetsukaze's Hair Extensions! [zets_hair_extensions],
    Big River Building Pack [BIGRIVER],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Xotto [DP_XOTTO_INDICATORS],
    Safe Autodoc [safeautodoc],
    Manual Bionic Installation [manualbionicinstall],
    Sleep Deprivation [sleepdeprivation],
    StatsThroughSkills [StatsThroughSkills],
    Garden Pots [growable-pots],
    Draco's Dog Mod [DracoDogMod],
    Alternative Map Key [alt_map_key],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Whaleys Tattoos and Scars [TATTOOMOD],
    Hydroponics [hydroponics],
    Beta National Guard Camp [national_guard_camp],
    sees-player icon, -attitude [sees_player_less_attitude]
]

# Additional context

This combined with #31121 is making crafting anything a huge chore.

Save after the update, you can get a save from before the update from the above issue.

[Magnolia Hills.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3268910/Magnolia.Hills.zip)

**Comment by gotnoface** [comment]
Yeah cooking food inside bases stuffed with materials now takes so much time I can easilly cook lunch irl, while my characters is canning meat. Probably a can of worms to tackle, but quicker turns really excerbate this issue.

**Comment by Galaktiki** [comment]
Same here, crafting and sleeping take very long real time. Ticks of 30 min of sleep take about 5 second real time each, so every night waiting almost 2 minutes to wake up. And it all starts on 9113 version, if downgrade wersion to 9112 its all fine as usual.  

And yes, the date in game gets messed up as posted here https://github.com/CleverRaven/Cataclysm-DDA/issues/31249 but i guess i can live with it.
