### ISSUE TITLE
Release Build for OS X 10.11.6 is possible

### ISSUE THREAD

**Issue by micage** [CleverRaven/Cataclysm-DDA#31254]
With the current makefile release builds are not possible for OS X <= 10.11.6 because of segfault (something goes wrong in player_morale). Sadly I cannot get any upgrade to a newer clang version (mine is 8.0.0), which could potentially solve the problem, so I went a different route and found that

it's possible to build cataclysm-tiles with all optimizations (Os, O1, O2, O3) on OS X 10.11.6 with g++-8 (hpc.sourceforge.net). Maybe it will work for even lower versions. I have no possibility to test this.

`brew install gcc@8` (be prepared that this takes a while).
Then change the compiler accordingly in the makefile.

Now the performance is comparable to the windows version.

**Comment by Night-Pryanik** [comment]
So, what's the issue here?

**Comment by micage** [comment]
The issue is that Release builds are disabled for OS X 10.11.6 and lower which is not necessary if you use a different compiler. The Debug build of clang is really slow. Handling large inventory lists is nearly impossible. Also when my character goes to bed I can prepare for a coffee break in real life.

So changing the compiler to gcc@8 makes it possible again to play CDDA on older versions of OS X.
