### ISSUE TITLE
Bionics that use X bionic power per Y turns now use 6 times more power over in-game time

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#31266]
# Describe the bug

Bionics that use X bionic power per Y turns now use 6 times more power over in-game time since the change from 6s per turn to 1s per turn. For example bionic that uses 1 bionic power per 100 turns used 10 bionic power per 1 in-game hour and now it uses 60 bionic power per 1 in-game hour.

# Steps To Reproduce

1. Toggle on bionic that uses bionic power per turn(s).
2. Wait 1+ hours.

# Expected behavior

It's balance issue. Bionics should use same amount of bionic power per in-game time as before the 1s turn change.

# Versions and configuration

build 9118

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-4111-g0009a3a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Classes and Scenarios Mod [more_classes_scenarios],
    StatsThroughSkills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi],
    Extended Realistic Guns [realguns],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Alternative Map Key [alt_map_key],
    Vehicle Additions Pack [blazemod]
]

**Comment by Zireael07** [comment]
It should be an easy fix - just divide power consumption by 6.

**Comment by gotnoface** [comment]
Ditto and likely another related issue, since it's again bionics - Metabolic Interchange dropped my character down from 58k stored kcal to 50k and gained Malnourished during single night, despite binging on fatty foods. I haven't seen it adjusted in player.cpp so it's probably #30018 and related again.
