### ISSUE TITLE
Does digging with pickaxe even work?

### ISSUE THREAD

**Issue by Fadragnir** [CleverRaven/Cataclysm-DDA#31268]
# Describe the bug

Digging through metal doors with pickaxe and concrete is now impossible? In Build #9099 it was possible to dig through the metal doors in hours and the time ticks were faster(30min of ingame time per 2 sec of realtime). Now time ticks 5 minutes of game time per 2 seconds of real time which is frustrating and it doesn't even give a message of progress. 

# Steps To Reproduce

1. Player in a lab with pickaxe and closed metal doors next to it.
2. Trying to dig through the metal door.
3. There's no way to dig through until starving, thirst and exhausted.

# Expected behavior

Digging through the metal door as it was possible before.

# Screenshots
I think it's not needed.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on  Windows 8.1 version
- Game Version: 0.D-4111-g0009a3a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Wyłącz Potrzeby NPC'ów [no_npc_food],
    Arsenał Icecoon'a [ew_pack],
    Bezglutenowe przepisy Bena [Tolerate_This],
    Doniczki ogrodowe [growable-pots],
    Fikcyjna Broń DeadLeaves'a [FIC_Weapons],
    Mod Prowizorycznych Przedmiotów [makeshift],
    Pakiet Broni do Wytworzenia [craftgp],
    Rozszerzone Realistyczne Bronie [realguns],
    Więcej Narzędzi Surwiwalowych [More_Survival_Tools],
    Średniowieczna i Historyczna Zawartość [Medieval_Stuff],
    Modularne Wieżyczki [modular_turrets],
    Roboty Z Odzysku [Salvaged_Robots],
    Alternatywne Klucze Mapy [alt_map_key],
    Beta Obozu Straży Narodowej [national_guard_camp],
    Zestaw Dodatkowych Pojazdów [blazemod],
    Removes Nether Creatures [Remove_Nether],
    Bez Grzybowych Potworów [No_Fungi],
    Bez Mrówek [No_Anthills],
    Klasyczne Klasy i Profesje [RL_Classes],
    Statystyki Dzięki Umiejętnościom [StatsThroughSkills],
    Uproszczone Żywienie [novitamins],
    Zapobiegaj Ożywieniu Zombi [no_reviving_zombies],
    Zawody i Scenraiusze [more_classes_scenarios]]

**Comment by Dacendeth** [comment]
time ticks in 5 min intervals when doing long tasks usually when you have a npc in your reality bubble.

**Comment by kevingranade** [comment]
This would be a duplicate of #31252 except I'm not at al sure that mining through a metal door with a pickaxe *should* be possible, need to revisit that.

**Comment by Fadragnir** [comment]
It should be possible to break through door with an acetylene torch
