### ISSUE TITLE
Debug.txt log errors related to Salvaged Robots

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#31265]
# Describe the bug

> sym is defined as number instead of string for overmap_terrain: robot_dispatch_first (robot dispatch center)
>  ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: robot_dispatch_second (robot dispatch center)

# Steps To Reproduce

Start a game with salvaged robots mod

# Expected behavior

No debug log messages.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-4039-g02eaddf
 - Graphics version: Tiles

# Additional context
Unrelated item from log:
WARNING : opendir [./mods/] failed with "No such file or directory".

**Comment by anothersimulacrum** [comment]
I can not reproduce this 0.D-11532- 0696252b0a5243445b4588247ef4ade1975d0efe

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.
