### ISSUE TITLE
Hot air kills scent.

### ISSUE THREAD

**Issue by nexusmrsep** [CleverRaven/Cataclysm-DDA#31275]
# Describe the bug

As a result of scent and temperature  display tool I've detected a bug with scent being nullified by hot air. At first I thought it was a bug within the tool, as I tested fire in a building, but then realized that in fact it was emisions from the flame that was causing it.

# Steps To Reproduce

1. Toggle display scent overlay tool.
2. Make a fire.
3. Move around and see how scent is being nullified in the vicinity.

# Expected behavior

Hot and cold air should be excluded from gases spread condition that nullifies scent.

# Screenshots
Will supply one later.

# Versions and configuration
Recent experimental vanilla. Win 10.

**Comment by Dacendeth** [comment]
I thought this was an intended feature, the smell of the fire covers human scent from animals in real life doesn't it?

**Comment by nexusmrsep** [comment]
That's what smoke does, and that's fine. It's not fine for hot/cold air though. Can you smell dinner in a cabin heated with a stove? Can a dog smell you there? Answer is: Yes.

**Comment by kevingranade** [comment]
Quick sketch of a fix:
Add a new field member, "scent_neutralization"
Add to smoke and other scent-nautralizing fields (maybe only the very intense versions).
Only execute the scent neutralization here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/map_field.cpp#L250
if the field has that member set.
