### ISSUE TITLE
Magiclysm mana does not regenerate

### ISSUE THREAD

**Issue by JessevdBerg** [CleverRaven/Cataclysm-DDA#31271]
# Describe the bug

In the Magiclysm mod, mana does not regenerate over time.

# Steps To Reproduce

1. Make a player that starts with a magic book (e.g. druid profession).
2. Learn and use a spell to use up mana.
3. Wait a long time.
4. Mana will not have regenerated.

# Expected behavior

Mana should regenerate over time, as it did so in previous versions, and there doesn't seem to be any other way to regenerate mana.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4113-g5d774e9 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Crazy Cataclysm [crazy_cataclysm],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Fungal Monsters [No_Fungi],
    StatsThroughSkills [StatsThroughSkills],
    Classes and Scenarios Mod [more_classes_scenarios]
]

**Comment by KorGgenT** [comment]
i think it has something to do with the turn time. i'll investigate further.
