### ISSUE TITLE
Crash when looking at an item pile

### ISSUE THREAD

**Issue by CorvetBlyat** [CleverRaven/Cataclysm-DDA#31288]
# Describe the bug
The game crashes when looking at a specific items using (x) or (e). Advanced inventory doesn't crash however it also doesn't show the items. Dunno what the items actually are

# Steps To Reproduce
1 Load my save
2 Look (x) or examine (e) at the rightmost item on the table to the south west (next to the copper spear), or to the south east of the table or the item behind the door south of the table (Whoopee cushion?)
3 Crash

# Expected behavior

Not crashing when looking at a specific items

# Screenshots

![Capture2](https://user-images.githubusercontent.com/36166722/59199888-4d9d7c80-8b97-11e9-8652-93a102fabf4b.PNG)
The highlighted items cause the crash 

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4088-g34de662 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]

# Additional context

[Matoaka.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3269934/Matoaka.zip)
[crash + debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3269944/crash.%2B.debug.zip)

**Comment by neitsa** [comment]
I can't reproduce on the latest version (`0.D-4254-g4259f653f9`) from the master branch.

Be it with <kbd>x</kbd> or <kbd>e</kbd>, it works as intended and doesn't crash (with any of the items you mentioned).

![image](https://user-images.githubusercontent.com/4538670/59452852-ef7ace80-8e0e-11e9-9d59-af056a94d534.png)

**Comment by CorvetBlyat** [comment]
My bad i was running an outdated build, it works perfectly on latest.

**Comment by neitsa** [comment]
Thanks for your feedback and no problems! It's actually useful when people report bugs, even if they are fixed in the meantime, simply because we know they exists (or have been patched).
