### ISSUE TITLE
Cold damage degrades bandages/ causes disinfected wounds to become dirty.

### ISSUE THREAD

**Issue by logros13** [CleverRaven/Cataclysm-DDA#31283]
# Describe the bug

Cold damage degrades bandages/ causes disinfected wounds to become dirty.

# Steps To Reproduce

1. Bandage or disinfect a wound.
2. subject yourself to "very cold" weather.
3. when you get damaged from the cold on a treated body part the bandages get damaged/ the wounds to become dirty.

# Expected behavior

Cold not causing bandages to mysteriously get torn and wounds to spontaneously get dirty.

# Versions and configuration

 - Game Version: 0.D-4123-g37a6167 (tiles)

**Comment by l29ah** [comment]
Also occurs with damage from overheating.

**Comment by kevingranade** [comment]
Infrastructure added in #25932, should just need to add the appropriate flag to apply_damage() when triggered by environmental effects.

**Comment by joe9000** [comment]
can this behavior be kept as a mod? it feels more survivory
