### ISSUE TITLE
Audio volume is incorrect

### ISSUE THREAD

**Issue by mark7** [CleverRaven/Cataclysm-DDA#31301]
# Describe the bug

Presently, Cataclysm uses a 0-200 range for all of music and sound volume, defaulting to 100.  This includes:

* MUSIC_VOLUME
* SOUND_EFFECT_VOLUME
* AMBIENT_SOUND_VOLUME

However, it does not map the volume to the range that the audio API that Cataclysm uses, SDL_Mixer, expects, which is 0-MIX_MAX_VOLUME (internally, 128).

This means that all audio to date has been playing at 78% of what one would normally expect.

My expectation is that the original author of the code expected 100 to be the "pre-recorded" volume, and 200 to be amplified.

It looks like SDL_Mixer lacks the ability to play audio louder than it was initially-recorded, so using amplified audio is not possible (except for systems where there is some form of per-program amplification system that happens post-SDL; my Debian Linux system uses PulseAudio).  The existing SDL_Mixer behavior is to clamp any values passed it above MIX_MAX_VOLUME to MIX_MAX_VOLUME, so currently, the user gets 78% of volume at what appears to him to be "100".  He can increase the volume up to 128, and above that, he can try to keep increasing the volume, and the options setting will show the number increasing, but it has no actual effect on the game's audio playback.

# Steps To Reproduce

Play the game with audio compiled in and sound enabled.

# Expected behavior

The existing audio behavior is to play back audio at 100/128=78% of possible using SDL.  This was probably inadvertent by the original author, but doesn't seem entirely unreasonable behavior-wise -- existing games on my system often seem to provide a bit of "headroom" for amplification.  It would be nice to retain existing volume used for existing versions of SDL.  I'm inclined to just change the allowed options range to 0-128.  The existing options code, if it sees an invalid setting, will just change the setting to default, which probably isn't wildly-unreasonable behavior (though it might be more-reasonable to remap it to 128, which is the loudness that a user with a ramped-up volume will see).  Currently, my bet is that essentially all players use the default volume of 100, so this will retain the existing loudness for them.  For players who have tried to get a really loud volume and have rammed volume up to above 128 and are migrating settings files between Cataclysm versions, this will lower the volume on their migration to 100, rather than the 128 that they've actually been hearing, and so will produce a quieter volume on migration.  However, it will also avoid dealing with adding config migration code between versions (one more maintenance headache, as ping-ponging between versions creates its own potential issues and Cataclysm has no existing system for managing and testing this) and mean that if it's a problem for them, once they've set the volume on a new version, their config will be compatible with older versions.

# Versions and configuration

 - OS: Debian Linux
 - Game Version: 0.D-4031-g6f160dbb95
 - Graphics version: Tiles

# Additional context

**Comment by nexusmrsep** [comment]
I recently worked on sound hooks, and can confirm that this is the case. I personally like the idea of setting max volume to 128 in options = equal to SDL sound max, with default at 100 and mentioning that design in soundpacks.md document so the sound developers can master their sfx for 100, thus leaving room for amplification within the game. Other idea would finding and implementing a whole new sound engine, like the original author did with Audiere, since SDL sounds is kinda clunky and underdeveloped.
