### ISSUE TITLE
CBM installation should ignore anesthetic requirements for characters with deadened mutation

### ISSUE THREAD

**Issue by dkargin** [CleverRaven/Cataclysm-DDA#31300]
# Description

Autodoc menu shows that my character has deadened mutation and anesthetic is not needed. But autodoc still refuses to start operation: "You don't have enough anesthetic for this operation"

A week ago it was working fine.

# Steps To Reproduce

1. Add 'Deadened' mutation
2. Try to install CBM
3. Get a message "You don't have enough anesthetic for this operation"

# Expected behavior

Deadened cenobites should be able to enjoy all the pain of CBM installation. Anesthetic just spoils all the fun.

# Versions and configuration

 - OS: Ubuntu 16.04
 - Game Version: 0.D-4155-g2afc018
 - Graphics version: Tiles
 - Mods loaded: core, magiclysm, StatsThroughSkills

**Comment by DemAvalon** [comment]
Someone else experiencing the anesthesia weirdness.
https://discourse.cataclysmdda.org/t/some-recent-weirdness/20305/15

Also seems to happen even with anesthesia in your inventory.
https://discourse.cataclysmdda.org/t/some-recent-weirdness/20305/22

**Comment by Fris0uman** [comment]
Probably Introduced by #31161, I'll try to fix it this week.
