### ISSUE TITLE
UPS not charging in recharger.

### ISSUE THREAD

**Issue by BenlyAZ** [CleverRaven/Cataclysm-DDA#31308]
# Describe the bug

Putting a UPS in an active recharger does not cause it to gain any charge.

# Steps To Reproduce

1: Make a vehicle with a recharger and sufficient power.
2: Make a UPS.
3: Put the UPS in the recharger and turn on the recharger.
4: The UPS does not charge up.

# Expected behavior

UPS would recharge in a recharging station, as its description suggests and as it did in previous game versions.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-4145-gba5692e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Medieval and Historic Content [Medieval_Stuff],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mythical Martial Arts [MMA],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable Religious Texts [no_religious_Texts],
    No Explosive Zombies [No_Explosive_Zombies],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Prevent Zombie Revivication [no_reviving_zombies],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    Fast Healing [fast_healing],
    Cataclysm++ [Cata++],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    No Fungal Monsters [No_Fungi],
    Necromancy [necromancy]
]

**Comment by esotericist** [comment]
The descriptions surrounding UPS stuff need changing, but I tried to make the description on the behavior of recharging station on the vehicle clear in its description:

It only charges cells placed directly in its storage.

In the specific case of a UPS, that means putting the heavy battery that was in the UPS into the recharging station. Unload UPS, charge battery, reload UPS.

**Comment by BenlyAZ** [comment]
UPS can't be unloaded, though. That part of its description is still accurate.
As it turns out you have to load the UPS with a heavy battery, and then the UPS inherits the heavy battery's capacity and can be recharged in the charger. The heavy battery cannot be recovered from the UPS. A UPS loaded with a disposable heavy battery will inherit its extra capacity and can be recharged.

**Comment by esotericist** [comment]
Well, that's certainly not how it was expected to work.

**Comment by BenlyAZ** [comment]
Extra bit of experimentation: the battery can be recovered by dismantling the UPS, just not by unloading.

**Comment by joe9000** [comment]
in build #9127 i can unload and reload the cell out/in of the ups, but it longer needs to be in the ups to be recharged by the recharging station which is nice.

**Comment by Dacendeth** [comment]
I can unload UPSs just fine, have been able too since the battery update.

**Comment by BenlyAZ** [comment]
Yeah, tried it with no mods and it works. Presumably one of the mods is conflicting with the new UPS. Oh Well.

**Comment by TechyBen** [comment]
> Extra bit of experimentation: the battery can be recovered by dismantling the UPS, just not by unloading.

AFAIK in my current game, I can swap out the battery by "reloading", but requires a second battery. So seems just the "unload" tag/code is missing on this one?

**Comment by Inglonias** [comment]
The UPS has been in a very strange place since the battery overhaul, and as I've said before, it's my biggest mistake in not tackling from the get-go.

The UPS is probably going to be a project for me in the near future. Not quite sure how we're going to make it work in this brave new world.

**Comment by Inglonias** [comment]
I've been screwing with the UPS for the past few days. This particular behavior is intentional. The UPS shouldn't say that it can be recharged anymore, and this can be fixed by removing that flag from the UPS.
