### ISSUE TITLE
Disassembling heavy items takes longer than it should

### ISSUE THREAD

**Issue by ErdrickXLII** [CleverRaven/Cataclysm-DDA#31322]
**Is your feature request related to a problem? Please describe.**  
Taking apart particularly heavy items takes considerably longer than stated.  Things like Electric Motors and Storage Batteries.  This is because you have to pick up the item to disassemble it.  If disassembling the item says it takes 2 hours, but the item weighs 400 pounds, just holding it drops your speed to 25 and it actually takes closer to 8 hours.

**Describe the solution you'd like**  
It would be nice if disassembling items could take advantage of the recent crafting changes to allow you to take things apart at a workbench/table so you don't have to hold them.  Also, being able to suspend/restart a disassembly would be nice too.

**Describe alternatives you've considered**  
Just being able to take something apart without having to pick it up would help a lot.

**Comment by anothersimulacrum** [comment]
> Just being able to take something apart without having to pick it up would help a lot.

You can already do this - wielding something near a crane or something with sufficient lifting quality to lift it will make it so that you don't have to deal with the weight of the item.

**Comment by ErdrickXLII** [comment]
That's good to know, but it's also rather unintuitive.

**Comment by esotericist** [comment]
> That's good to know, but it's also rather unintuitive.

I agree with this, and I originally intended to allow disassembling from the ground, but I found that very difficult to actually implement.

The crane stuff was a compromise until we can do something a bit more comprehensive (and specifically added for disassembling storage batteries).

**Comment by Fris0uman** [comment]
Could we have a message in the log
`"This item is very heavy,  use a tool with lifting X to help you." `?

**Comment by PLUUZ** [comment]
> > That's good to know, but it's also rather unintuitive.
> 
> I agree with this, and I originally intended to allow disassembling from the ground, but I found that very difficult to actually implement.
> 
> The crane stuff was a compromise until we can do something a bit more comprehensive (and specifically added for disassembling storage batteries).

Dear @esotericist  - Is this crane trick still in the game as of Ellison? When I pick up heavy things standing next to a vehicle tile with a telescopic crane (lifting 7, jacking 7) the log still says "you're overburdened!" and my maximum weight (as seen in the (i)nventory screen) does not change. Also, the Disassemble menu still says many things are too heavy to pick up.

**Comment by esotericist** [comment]
@PLUUZ you need to wield, not pick up. sorry, I know that's not super clear in the game at the moment

if that isn't enough, it's easier to help with gameplay issues in the official discord or forums
