### ISSUE TITLE
Time to painting wall, construction etc...

### ISSUE THREAD

**Issue by SuperDIMMaX** [CleverRaven/Cataclysm-DDA#31324]
Paint wall need 40 min. for 1 tile. Its bug from 6>1 sec. or ...?

**Comment by SuperDIMMaX** [comment]
This rhetoric question.
add tag game balance.... this time to long. i can paint all room in this time :)

**Comment by capSAR273** [comment]
I'm trying to understand the issue you're talking about. Do you mean to say that currently it takes 40 minutes to paint one tile, or 40 minutes for the paint to dry after painting one tile?

I agree that painting one tile shouldn't take 40 minutes, 5 minutes seems more appropriate.
