### ISSUE TITLE
Non-generic gun in generic guns mod

### ISSUE THREAD

**Issue by YukariMindGap** [CleverRaven/Cataclysm-DDA#31321]
# Describe the bug
The Generic Guns mod still contain a non-generic gun; the Beretta ARX-160.

# Steps To Reproduce
Check gg_guns_override.json

# Expected behavior
The Beretta ARX-160 is non-existent or at least renamed to fit the generic theme

# Versions and configuration
- OS: Windows 7
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-4170-g4ca7348 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
Offending JSON in question:
{
    "id": "arx160",
    "copy-from": "arx160",
    "type": "GUN",
    "name": "Beretta ARX-160",
    "description": "The Beretta ARX-160 was a Phase II contender in the United States Army Individual Carbine competition to replace the M4 carbine.  It failed to replace it, but it is widely used by military all around the world.",
    "ammo": "308",
    "magazines": [ [ "223", [ "stanag30", "stanag10", "stanag50" ] ], [ "308", [ "akmmag", "akmbigmag", "g3mag", "g3bigmag" ] ] ]
 }

**Comment by kevingranade** [comment]
AFAICT since the gun is blacklisted, it will still not appear in the game. It was added to suppress a data consistency warning in #20320
