### ISSUE TITLE
Carrying volume based on the pocketsize.

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#31325]
Grettings,
you know me. My English is not very good, but I will try anyway.
I love the volume system in the game, but there is something bothering me.
Example: you wear 2 Rucksacks. Both have 10 l of volume to transport in. You are able to stuff 10,1+ l items into it no problem, somehow sharing the space.
How to fix it (from a naive non programmer perspective): Having another carry volume-number attached to you: maximum volume per item. Even with 2 Backpacks you can't carry those 10,1+ l items with you. Stacked items shouldn't be a problem. Also, that way we can give clothing max volume values. (Cargopants max 1l per item?)
Bonus feature: Items are distributed between your carrying spaces and giving you buffs or debufs. Since a pistol can be drawn faster from your pocket than from a duffelbag. Perhaps you can switch items between pockets? (That would be tedious, though)

**Comment by Zireael07** [comment]
Been suggested several times, probably won't happen any time soon because it requires a complete rework of the inventory.

**Comment by Night-Pryanik** [comment]
Duplicate of #3671. Closing, sorry.

**Comment by Lamandus** [comment]
> 
> 
> Duplicate of #3671. Closing, sorry.

no need to be sorry, my fault :)
