### ISSUE TITLE
Cows produce milk way too fast.

### ISSUE THREAD

**Issue by BenlyAZ** [CleverRaven/Cataclysm-DDA#31333]
# Describe the bug

By the time you're done milking a cow, it's already got 8 more milk ready.

# Steps To Reproduce

1: Spawn a cow, cattle fodder and a container. Also spawn a short rope to tie it in place if you don't want to watch it zoom around while you milk it.
2: Apply the cattle fodder to tame the cow.
3: Milk the cow.
4: Milk the cow again immediately afterwards.

# Expected behavior

Cows take time to produce milk.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-4188-g216fe4b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Orange01gaming** [comment]
In my experience if you milk  into a separate container it takes a while for them to produce more. How much of the milk did you remove?

**Comment by BenlyAZ** [comment]
80. I filled up a jerrycan in less than twenty minutes.

**Comment by logros13** [comment]
According to some quick google-fu that's about what they should produce per day (20-25 liters for a modern milk cow) so producing that in just 20 min definitively seems to much.

**Comment by BenlyAZ** [comment]
Bessie was plenty ready to keep going, too, I just ran out of space in the jerrycan. The point is that the cow will produce milk as fast as you feel like taking it.

**Comment by Orange01gaming** [comment]
Months ago it took them a few days to make 10 units of milk. I needed a few cows for my cheese production.

**Comment by mlangsdorf** [comment]
The duration of the milking effect was being clipped at 4 hours, so the math that calculated how much milk a cow had remaining always returned 85% of the initial value.
