### ISSUE TITLE
Range of sight depends on whether you're holding the walk button

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#31334]
# Describe the bug

When you're going step by step, you see a tile farther than if you hold your movement button to spend less real time on moving. It is especially noticeable when you're blind.

# Steps To Reproduce

1. Load the saved game.
2. Try pressing and releasing `j`. You will see yourself remembering the tiles you went through.
3. Try holding `j`. You will remember nothing.

Alternative:
1. Turn off the "FORCE_REDRAW" option. Insure map memory is enabled.
2. Wear a welding mask (make sure it's closed)
3. Walk in a random direction
Result is no tiles memorized.

# Expected behavior

Sight range not depending on your desired key pressing style.

# Screenshots

![](https://pstbin.ru/f/23586/)

# Versions and configuration

0.D-4170-g4ca73481c6-dirty
Console interface.
```
  "dda",
  "no_npc_food",
  "desertpack",
  "alt_map_key"
]
```

# Additional context

[2019.06.10.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3275990/2019.06.10.zip)

**Comment by kevingranade** [comment]
ok that's super weird.

**Comment by ZhilkinSerg** [comment]
Could it be due to shaking and pain effects?

**Comment by AMurkin** [comment]
North-south runs with a welding mask on (ASCII):
![image](https://user-images.githubusercontent.com/1931904/66397254-eec40480-e9ca-11e9-93f8-cd3e2f33cfd1.png)
Pretty sure it's not the status effects.

**Comment by kevingranade** [comment]
I have a guess, we might be handling redraws differently for "moves that occur within a turn" and redraws that occur between turns, moves that happen during a turn might not get an updated visibility map, and therefore never draw the symbol for the tile the player is standing on.  You might be able to replicate this even with short view distances if you crank up player speed a lot, e.g. by using the time dialation CBM.

**Comment by kevingranade** [comment]
The most likely proximate cause is this check:
https://github.com/CleverRaven/Cataclysm-DDA/blob/1fd791147c9efced427c35c2d4d9adb04f39863e/src/map.cpp#L5522
If it fails then we have drawn that tile using a special effect, so we *do not memorize the tile*.  There is a similar check when drawing tiles, with the same behaviour.

My guess is that there is somehow a *chance* of this happening, and if you press the key slowly, there are multiple draw operations, and if one succeeds the tile gets memorized.  Likewise when walking around with a more normal vision range, there are many many chances for the code to make it to the tile memorization statement.

**Comment by kevingranade** [comment]
AFAICT the best way to debug this is going to be to drop some simple print statements somewhere in map::draw() that print out the state of all the possible variables that would cause apply_vision_effects() to kick in and look for values that are toggling between different states.

**Comment by kevingranade** [comment]
Ok weird debugging finding, if I put a print statement in map::draw() right before the check in question, it sometimes prints once per step and sometimes twice per step.  If it prints once per step it does NOT put that tile in map memory, if it prints twice, it does.

I still suspect this has something to do with the draw call inside the turn loop not registering map memory for some reason.

**Comment by kevingranade** [comment]
Ok so it seems like the only time the map memory is updated is if map::draw() is called from outside the action loop, this makes basically no sense, still looking.

AHA, so if you disable the "FORCE_REDRAW" option, it NEVER makes the draw call and it never captures map memory, still not sure why.

**Comment by kevingranade** [comment]
Ok forget the apply effects thing, new theory based on gdb tracing is that there's a sequence of events where the map memory cache gets confused and doesn't trigger on the tile.

**Comment by kevingranade** [comment]
After more testing, if you retrace your steps, it always seems to memorize the tiles.
I'm guessing maybe the memory cache has to be visited twice for it to trigger, possibly the first call autovivifies the entry and the second has it trigger properly.  This also explains why the duplicated draw() calls would make it work, since it would visit it twice per step.

**Comment by kevingranade** [comment]
Orrrrr, it's a really dumb and not at all deep logic error, fix incoming.
