### ISSUE TITLE
Using Construction menu for dig pit does not create soil, peebles, or sand.

### ISSUE THREAD

**Issue by Orange01gaming** [CleverRaven/Cataclysm-DDA#31341]
# Describe the bug

You only get those materials from using the [a] menu not the [*] menu. I suspect that is for similiar projects as well.

# Steps To Reproduce

1. Spawn in a shovel, or dig stick
2. Dig pit using construction menu
3. Observe no soil, etc is made, but pit is dug. 

# Expected behavior

You get the same products from the activate menu.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-4035-g77d70f5 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    PKs Rebalancing [PK_REBALANCE],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs]
]

**Comment by l29ah** [comment]
Similar problem with chopping wood: https://github.com/CleverRaven/Cataclysm-DDA/issues/26729

**Comment by Ramza13** [comment]
So I tried to reproduce this but it doesn't seem like you can dig a pit from the construction menu anymore so I'm either doing it wrong or this is fixed.
