### ISSUE TITLE
Asthma Realism

### ISSUE THREAD

**Issue by chaoticidealism** [CleverRaven/Cataclysm-DDA#31343]
**Is your feature request related to a problem? Please describe.**  
Asthma as it is now gives you repeated asthma attacks that can be treated with a stimulant inhaler; if not treated, they worsen and you die. This isn't how asthma works in real life.

**Describe the solution you'd like**  
- Add a steroid inhaler. Using it daily reduces the odds of having an asthma attack and reduces the severity of the asthma attacks that do happen, so that the maximum allowable asthma attack stage is reduced by 1.
- Asthma attacks should not usually be fatal, even if untreated. They should come in stages, and each stage should have a chance of either moving on to a higher stage, or resolving to a lower one.
- Exercise (anytime your stamina hits a low level) should have a chance of triggering an asthma attack. Using a stimulant inhaler beforehand should prevent this.
- Tear gas exposure should trigger an asthma attack.
- Eating/drinking something the PC is allergic to should have a chance of triggering an asthma attack.
- Colds, flu, and fungal infections should increase the odds of asthma attacks.
- Asthma should come in more or less severe variants.

**Asthma attack progression**  
Stage 0: Normal functioning.
Stage 1 asthma: Stamina decreases more quickly. Player gets a notice about an asthma attack. Will wake the PC, but can go back to sleep. Treatable with stimulant inhaler.
Stage 2 asthma: Stamina decreases very quickly. Player starts coughing, making noise. Sleep is impossible. Treatable with stimulant inhaler.
Stage 3 asthma: Stamina bottoms out and stays there. Player gets a message about not being able to get enough air. Stimulant inhaler will move asthma back to stage 2.
Stage 4 asthma: Mechanically, works like drowning--quick HP loss. Stimulant inhaler is ineffective; adrenaline injection or bionic adrenaline rush will move asthma back to stage 2.

**Variants:**
Exercise-induced asthma: Asthma attacks are triggered only by low stamina, are preventable by stimulant inhaler, and stop at stage 2. 1-point disadvantage.
Mild asthma: Asthma stops at stage 2. 2-point disadvantage.
Severe asthma: Asthma goes all the way to stage 4. 4-point disadvantage.

**Comment by TechyBen** [comment]
Depending on game balance or realism focus, I too wonder about how to treat asthma in game. I can manage my activity IRL and breathing to avoid all but allergic reaction attacks (hay fever/ cat allergy coughing attacks, or exercise causing a coughing attack). But I know others who need daily steroids to keep their breathing/asthma regulated.

**Comment by Night-Pryanik** [comment]
No discussion in more than two years, closing.
