### ISSUE TITLE
CTD in skill Window

### ISSUE THREAD

**Issue by Proman9000** [CleverRaven/Cataclysm-DDA#31346]
# Describe the bug

I have a CTD where it fails the assertion in line 603 of player_display.cpp, which was introduced in #31261.

# Steps To Reproduce

1. Load Save
2. Open character menu
3. Cycle into skill menu ( Only happens in normal cycle direction, does not crash when backtabbing, does also not crash when first backtabbing in, then tabbing in)

# Expected behavior
No CTD

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4204-gc93952d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3278002/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3278003/crash.log)
[Aplin.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3278021/Aplin.zip)

**Comment by JayThirtySeven** [comment]
I am having the same issue in linux. Going to attach my crash log because it has debug symbols.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3278523/crash.log)

**Comment by RocketPapaya413** [comment]
Had a similar crash just now, though it crashed when I tabbed from Enc/Warmth to Speed.

Mods:
  "dda",
  "FIC_Weapons",
  "realguns",
  "ew_pack",
  "DinoMod",
  "national_guard_camp",
  "cars_to_wrecks",
  "blazemod",
  "Tanks",
  "Arts' Guns"

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3279102/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3279103/crash.log)

**Comment by Proman9000** [comment]
fixed
