### ISSUE TITLE
Sanity checking for dialogue

### ISSUE THREAD

**Issue by jbytheway** [CleverRaven/Cataclysm-DDA#31359]
**Is your feature request related to a problem? Please describe.**  
Bugs have been observed due to inconsistencies in dialogue (#31075, #31107).

**Describe the solution you'd like**  
As discussed in the comments of #31077, we could have sanity checking to verify:
* All topics referred to exist.
* All topics can be reached.
* All topics can lead to an exit from the conversation.

@I-am-Erk FYI.

**Comment by I-am-Erk** [comment]
I should note that as described this wouldn't prevent https://github.com/CleverRaven/Cataclysm-DDA/issues/31075, because in the test case the NPC would have had a response to talk_mission_list that broke the cycle, that's how it escaped playtest. It only broke down in older versions of the refugee center where the NPC had no mission list.

https://github.com/CleverRaven/Cataclysm-DDA/issues/31107 was a playtesting miss on my part that could be caught by better automated testing.

**Comment by mlangsdorf** [comment]
there's already a python script to validate that all topics are referenced and exist:
```
$ ./tools/dialogue_validator.py data/json/npcs/* data/json/npcs/*/* data/json/npcs/*/*/* data/json/npcs/*/*/*/* data/json/npcs/*/*/*/*/*
talk topic TALK_STOLE_ITEM defined but not referenced in a response
talk topic TALK_HUB_SECURITY referenced in a response but not defined
talk topic TALK_FREE_MERCHANT_STOCKS_JARS referenced in a response but not defined
talk topic TALK_FREE_MERCHANT_STOCKS_JAR defined but not referenced in a response
talk topic TALK_EVAC_MERCHANT_BACKGROUND defined but not referenced in a response
````

I'm think that validating that all topics reach an exit is a variant of the halting problem, but maybe it's an external validator that gets around that.  Let me think about it.

**Comment by mlangsdorf** [comment]
Walloping the code around a bit:
```
$ ./tools/dialogue_validator.py data/json/npcs/* data/json/npcs/*/* data/json/npcs/*/*/* data/json/npcs/*/*/*/* data/json/npcs/*/*/*/*/*
talk topic TALK_HUB_SECURITY referenced in a response but not defined
talk topic TALK_FREE_MERCHANT_STOCKS_JARS referenced in a response but not defined
talk topic TALK_FREE_MERCHANT_STOCKS_JAR defined but not referenced in a response
talk topic TALK_EVAC_MERCHANT_BACKGROUND defined but not referenced in a response

Checking for topics that do not reach a TALK_DONE
topic TALK_HUB_SECURITY responses []
```
