### ISSUE TITLE
Control Laptop Rebalancing and Expansion Proposal

### ISSUE THREAD

**Issue by matthemsteger** [CleverRaven/Cataclysm-DDA#31357]
**Is your feature request related to a problem? Please describe.**  
The control laptop, although mostly a later game device, is mostly an "I win" button in labs and other robot/turret scenarios. It allows you to stand behind a wall and neutralize all these threats quite easily (in addition to a nice side-effect of 100% success robot detection in a 10 space area around the player). So there is somewhat of a balance problem here. Furthermore, some software on a USB and book learning should not necessarily mean you can get into a robots systems and actually change their friend/foe programming, remotely. It defies some amount of logic that robots would not have some sort of defense against this (which admittedly they have some in the formula determining success, but its not a very balanced formula).

I would like to make it more interesting and varied.

**Describe the solution you'd like**  
I would like to actually make the control laptop an item that is closely tied to the new robot salvage system (#30456) and scales based on your ability to analyze various robot parts for their function and perhaps vulnerabilities. Also, add a more rudimentary hack as the default (without using salvage parts) and lower the skill/roll requirements so that the control laptop becomes a tool a bit sooner.

* The control laptop will still be craftable with a similar recipe (modified a bit to show that it has the ability to scan robot parts) and maybe renamed to `hacking laptop`
* Immediately, you can use the "denial of service" overload attack. It turns the laptop into `hacking laptop (broadcasting)` and will continually drain power and target a single robot, turning it neutral. This will be subject to a roll that has a reasonable chance of success.
* The "dos" attack will have diminishing returns, a single robot should eventually become effectively immune if you do it too many times.
* The following attacks will be based on your salvage (I would like them to be based per robot "species" .. tbd)
  * Blind -> Targeting Module
  * IFF -> Identification Module
  * Disable Guns -> Gun Module
  * Root (no move) -> Pathfinding Module
  * Slow -> Sensor Module

Activating the laptop will give a series of menus that allows you to
* Scan for robot endpoints that are currently available
* Scan a robot salvage part to add the corresponding attack to that corresponding robot to your "book of tricks"
* View your current "book of tricks"
* When selecting an endpoint (robot) you will see the list of effects you can put on it (hoping to make a non-clunky UI that also shows the possible effects on the onset while you are selecting a robot)

**Describe alternatives you've considered**  
Changing the formula for the control laptop and leaving the current system in place would probably be an easy "win", but might be more difficult than I think to balance.

Separating these ideas out into different craftable electronics might also work, and then basically eliminating the control laptop might be a more direct and interesting approach as well. It might also be easier to code since each device would be standalone and activated. I just came up with that thinking of alternatives so its worth noodling.

**Additional context**  
This is related to a PR I plan to devote some time to soon, and wanted to get further feedback in a channel that is seen by maybe slightly more people. See #30892 .

**Comment by joe9000** [comment]
following up on the 10 space radius, another possibility is building a directional antenna that lets you deal with those turrets in the middle of the largest rooms in the labs

**Comment by TechyBen** [comment]
IMO if going for realism, DDOS attacks don't stop working over time without mitigation being used. The mitigation will have it's own weaknesses or costs.

So, changing frequencies, can then be attacked by likewise "cycling hacking laptop" as an option for example. It would mean the laptop would need constant action from the player, and getting distracted would mean death!

Or if the robot/system cut off access to the connection being attacked, it would lose some system operability in that area. So, a DDOSd robot could function properly, but not call in reinforcements.

Also, going from gameplay, having a system just plain stop working is not really fun. Just annoying/RND. Having the system need management/balance (say timed hit and run cooldowns, timed cycling systems/attacks) is more dynamic and risk/reward IMO. :)

**Comment by matthemsteger** [comment]
Yeah, similar arguments came up in the PR. My thoughts on scaling this is the DOS type attack is the "lowest" level attack, so is intentionally limited. I am trying to tie reality based concepts into this, but also look at general balance and gameplay, because from a certain point of view, the reality that a survivor that, only days ago, just read "Computer World" and then several computer science text books can hack a military level robot that autonomously controls a gun is fairly laughable (though to be fair, that is more of a book/skill progression problem than a control laptop problem).

While its not fun to have your attack be nullified, I was envisioning the barrier to roll being fairly low with diminishing returns for the base "attack", along with a longer path to more interesting effects. The goal is to make the control laptop have a progression and curve of power, so in the end, players that enjoy the power of the control laptop will still be able to dominate robots, it just takes some extra effort to gather the parts to do so.

**Comment by faefux** [comment]
>IMO if going for realism, DDOS attacks don't stop working over time without mitigation being used. The mitigation will have it's own weaknesses or costs.

Bots have 'AI Cores'  So i think it's not beyond the pale to say they learn to mitigate said attacks after a time.

**Comment by TechyBen** [comment]
> Bots have 'AI Cores' So i think it's not beyond the pale to say they learn to mitigate said attacks after a time.
That makes sense. But mano e mano then so would our Survivor have access to an "AI-hacking laptop". Kinda off topic, but we always seem to imagine a world in isolation when making games/books/references. Then forget in the real world, reality says otherwise.

So I'm all for it, we just have to be careful how we frame the lore, otherwise the player will think "that's not fair". With correct signposting, they can see how the mechanic works.

I can understand there being no ability to control robots. IRL a car takeover hack requires weeks of research (but after than 3 seconds and a button press XD ). Anything above that would be difficult. But that would make for a nice NPC mission where they supply a 1 time use "control laptop" and a mission to capture a robot! (That limits use a lot, adds to the lore that this is a complex system needing multiple people/chars to program, and also allows for occasional fun without being OP).

I know that's not part of this discussion, but it's an example of how a player can be given fun moments, without having to make items OP, or remove any/all fun items. (And is especially possible now thanks to the hard work of the devs in the NPC/camp/faction projects!)

**Comment by jeremyshannon** [comment]
Perhaps "root' should be named "immobilize" since "root" generally means "the root user" -- i.e. complete access to all systems.
