### ISSUE TITLE
[CR] Split the Mega Skills - Survival and Cooking

### ISSUE THREAD

**Issue by SourSlime** [CleverRaven/Cataclysm-DDA#31350]
**Is your feature request related to a problem? Please describe.**  
Survival is an overused skill. It is used for so many different things, which is the exact opposite of what we see with other skillsets, like melee and ranged. Melee has five subskills - cutting, bashing, piercing, unarmed and melee itself. Ranged has 5 as well - rifles, launchers, shotguns, handguns and marksmanship. Even crafting has several skills - fabrication, electronics and cooking along with skills that have other uses too, like tailoring and mechanics. But survival is not like these. It’s used for a large amount of extremely varied things and could be split up into more skills. Doing so fixes problems such as an expert butcher being an expert forager or expert firestarter.

Cooking is another skill that can be split because brewing mutagen should not make you a master chef. At early levels, they are quite similar, but as others have noted, chemistry quickly evolves into molecular formulas, math equations, advanced equipment and techniques that cooking doesn't require.

Here’s what survival is used for (the list is based on my memory, so it might be wrong):
Butchery 
Fishing
Foraging
Crafting varied items, including drugs and plants

**Describe the solution you'd like**  
Survival can be split into the following skills:
-Zoology (for butchery and other animal-related things)
-Botany (for foraging, farming,  turning plants into products and other plant-related things)
-Fishing
-Survival itself (for things such as starting fires with a fire drill, or setting up tents, making makeshift items, etc)

Cooking can be split into cooking (making food) and chemistry (making bombs, mutagen and drugs). Kevin noted that there may not be enough low-level chemistry recipes, but that isn't a problem as far as I'm concerned. New books for early-level chemistry are a great idea.

**Additional context**  
This opens up future possibilities with larger benefits from individual skills - i.e: high cooking skill could reduce the cooking time of some recipes, as the player learns more efficient food preparation techniques or better morale bonus from cooked food. Another example is examining enemies with higher zoology could give more accurate descriptions of them. 

I may be able to fix this issue by myself, but it's a huge project, so I'm not committing to it yet. I also wanted to open an issue in case others have better ideas on how to implement it.

**Comment by DemAvalon** [comment]
It seems like an ok Idea but having a skill just for fishing seems like a waste, I would merge it with zoology, also animal products can be found while foraging so both zoology and botany would affect that, there would be a need for simple chemistry that the player could do (either that or make some cooking recipes to also give chemistry xp like making vinegar)
on the other hand, it could cause unnecessary clutter much like it was before construction was merged into fabrication, survival seems like a good catch-all skill for primitive tasks (such as skinning and foraging) chemistry and cooking being separate skill seems like a better Idea as its a lot harder to see a master chef being a master chemist than it is to see a master survivalist being a master butcher, skinner, forager, fisher and such.

**Comment by TechyBen** [comment]
Yeah, perhaps just splitting it into 2 groups?
So animals as one, survival as the other? Then splitting the butchering/trapping/taming etc into an animals skill. Then the other aspects of survival into a main "survival" skill. With a mix of the two needed for some survival specific butchuring tasks?

**Comment by SourSlime** [comment]
@DemAvalon thanks for replying. Foraging isn’t about the products you get. It’s in botany because you are rifling through bushes and other leafy things - the eggs are just in hidden nests afaict.

https://www.reddit.com/r/cataclysmdda/comments/bx8c8j/comment/eq4x6ar
Unless I have misread what Kevin said, he specifically stated that mega skills such as survival should be broken down into smaller skills. Fabrication and construction are a bit different imo, since they are very similar, and the existence of construction skill made constructions less useful, according to Coolthulhu

@TechyBen I’m keeping mostly similar things together similarly to what you suggest (e.g: all animal stuff is in Zoology, all plant stuff in Botany). There will definitely be a mix of survival in the new skills, but it won’t be as important.

**Comment by DemAvalon** [comment]
> @DemAvalon thanks for replying. Foraging isn’t about the products you get. It’s in botany because you are rifling through bushes and other leafy things - the eggs are just in hidden nests afaict.

In that case it should be survival, not botany, as the act of foraging fits that action more (I thought it was in botany as one would use that skill to tell a plant from another, same for zoology as one would use their knowledge of animals to identify probable nest locations, identifying which animal laid the eggs and whether they were rotted or not )

I stand that having a skill just for fishing is unnecessary... but splitting survival in three seems ok I was just worried that it might seem unnecessary.

you are going to have to make many books... also is it possible to have a skill book train more than one skill? just thinking that biography of a mountain man and outdoor adventures would train all three skills also keep in mind that an illiterate player should be able to use basic chemistry so there would be a need for basic chemistry recipes.

**Comment by SourSlime** [comment]
I’ve already got plans for the books, and I don’t mind making them. It’ll just take some time to add them.

After thinking about it a little, I agree about foraging using survival, although it should give a small amount of botany and possibly zoology exp.

As for fishing, I think it will be a niche skill, but once fishing gets more features (NPC fishing comps, recording the largest fish of a type caught, fish encyclopedia, non-fish useful items getting caught), it will be much more useful.

I don’t think books can train two skills, but that’s a great idea.

The botany and zoology makes more sense now, and it might be possible to make plant/animal yields scale slightly with botany/zoology level.

I completely forgot about Illiterate, so thanks for reminding me. It looks like making salt water can get chemistry to 1, and afterwards there are multiple level 2, 3, 4, 5, 6 and 7 recipes. Idk how they would learn recipes though.

**Comment by DemAvalon** [comment]
I'm sure someone will add audiobooks with crafting recipes in them one day... other than that they would only learn those that have auto-learn in them.

**Comment by I-am-Erk** [comment]
I don't know about splitting survival, certainly not into four skills. In general, most skills under survival are things that tend to travel in packs. For the most part, it's unlikely you're going to learn detailed wilderness survival and never once touch on how to handle a carcass. It would be better to handle these with proficiencies: butchery and skinning would be proficiencies of survival, with your success rate determined both by your survival skill level and whether or not you have the butchery proficiency.

Cooking and chemistry are totally different skills and learning one doesn't equip you to do the other. They'll probably get split out soon now that we can make some lower level chemistry recipes

**Comment by SourSlime** [comment]
I agree that subskills/proficiencies are a good way to go about it, and might solve some problems, but I was looking at solving the issue from a skills perspective.

You’re right about survival. Survival does encompass the things that the new skills will, but I think this may be a problem with the Survival skill itself. It’s so broad, and survival covers so many different things, arguably even things like fishing, and as you mentioned, skinning/butchery.

Zoology and Botany are poor names, but I can’t think of better ones. I want to call them “animal knowledge” and “plant knowledge”, but it doesn’t really fit.

**Comment by SourSlime** [comment]
It’s also possible to split survival further, and add a Gathering skill for foraging and a Butchery skill for butchering.

**Comment by I-am-Erk** [comment]
It's possible to split it, I'm just saying I disagree that it's a good idea. Survival isn't any broader in scope than fabrication, nor any wider used, and most recently we moved more stuff *into* fabrication, not away. The argument is that if you have learned basic wilderness survival, there's a good chance you've come into contact with all the skills you're talking about. In the courses I did as a kid we learned trapping, shelter making, plant identification, animal skinning and preparation, and fishing as part of a single course called, you guessed it, "survival". I find it extremely unlikely someone could reach level 10 in "shelter building" but be level zero in "plant gathering", yet that is what'll be accomplished by making multiple skills. It will also mean that you can't learn these skills from a wilderness survival guide; that will inexplicably only teach you one of these closely related skills.

The survival skill needs to be handled by a better implementation of the skills system, not by misapplying the current skills system.

**Comment by Rivet-the-Zombie** [comment]
>Kevin noted that there may not be enough low-level chemistry recipes

There are enough precursor chemicals now that the lowest levels of a Chemistry skill could be populated with those basic resource chemicals.

**Comment by Zireael07** [comment]
Kevin's note on not enough chemistry recipies was looong ago, around when I added the chemistry set. I-am-Erk has recently (this year) done a wonderful job of expanding the list of recipes for chemicals.

**Comment by I-am-Erk** [comment]
So far I've only expanded the list of tools actually. We'll need a concerted effort to add more chemistry recipes if we want it to become a skill.

**Comment by Inglonias** [comment]
While I can agree that survival is a little broad, we also have to remember that there are currently an awful lot of skills in general. Just be careful not to go overboard with splitting them out if you end up doing that.

**Comment by SourSlime** [comment]
@Inglonias I might be wrong, but I think Kevin’s plan is to split skills up enough that it becomes very difficult for the player to master every skill - that’s what NPC specialists will be for.

@I-am-Erk my problem with survival is how often it is used, and how important the skill has become compared to others. It seems to me that every recipe and skill that deals with the outdoors gets shoved into Survival. Fishing? Straight into survival. Butchery? Into survival it goes. Making seeds out of plants? Survival. And that’s not even getting into planned features, like hunting/tracking animals and other crude stuff.

I haven’t changed the issue post yet, but as I mentioned in my last comment, I agree that things like fishing and butchery do belong in survival, at least a bit. The issue here is that survival itself is too broad of a skill. Calling it survival, and having it’s description say,
“Your skill in surviving the wilderness” makes it very broad, and include other possible skills such as butchery.

I don’t think our viewpoints on this issue are that far apart. You said this issue shouldn’t be solved by misapplying the current system, and that it could be fixed with subskills/proficiencies of survival. Those didn’t exist when the melee skills or ranged skills were created, but I still think those have a fantastic system. There’s an overarching skill (melee), and then smaller skills which perform different duties (piercing weapons vs cutting weapons) which gain exp when used, but also give melee exp when used.

Maybe that’s how we should go about fixing this issue - make survival the base skill (melee) that gains exp whenever a subskill is used (fishing for example). 

Afaict this skill split doesn’t make the game worse in any way. I haven’t got good ideas for how to split Survival (which is exactly why I made the issue CR). Since survival will be far less useful, exp gains for the skills that split from it can be increased.

Offtopic: It’s also a great plan for fixing fabrication - make fabrication the base skill, and make crafting skills level it through use. Then it could give crafting bonuses or other perks depending on level.
