### ISSUE TITLE
Burning Hands and friends do not start fires

### ISSUE THREAD

**Issue by shinichizio** [CleverRaven/Cataclysm-DDA#31368]
# Describe the bug

When casting the spells Burning Hands, Fireball or Point Flare, the only things that can be damaged (or targeted in the case of Point Flare) are creatures. Their personal belongings, surrounding terrain, nearby tinder and other ostensibly flammable items are completely unharmed.

# Steps To Reproduce

1. Make a new character and debug magic spells into them.
2. Walk to a forest tile.
3. Cast Fireball upon the forest.
4. Nothing is on fire.

# Expected behavior

1. Point finger at trees.
2. Shoot gout of flame at trees.
3. Trees catch fire along with everything else in a 30-degree cone.

# Versions and configuration

- OS: Windows 10 Pro
    - OS Version: 10.0 1803
- Game Version: 0.D-4211-g7a858a4 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context

This may very well be a feature request. I'm not sure if magic flame is meant to be real flame, or if it's a clean-burning neutron flame that kills sentient beings without harming objects. Robots are also extremely immune to magic fire, though an accomplished Kelvinist can still lightning bolt them to death.

**Comment by KorGgenT** [comment]
this is intended for balance reasons.
