### ISSUE TITLE
Add a keybinding to mute sound

### ISSUE THREAD

**Issue by Rainoutt** [CleverRaven/Cataclysm-DDA#31366]
**Is your feature request related to a problem? Please describe.**  
No

**Describe the solution you'd like**  
To add a keybinding to mute all sound coming from the game

**Describe alternatives you've considered**  
Using a script to mute the .exe and muting the game from the sound mixer on windows

**Additional context**  
I play a lot of online games, and sometimes between games I need to wait, so I mute the game from the sound mixer when a game starts. I was considering if is there an easier way to do this.

It's just an idea, its really not necessary but I think it'll be a nice adition, thanks for developing the game even if this feature is never added.

**Comment by mark7** [comment]
For your use case, adding a "pause" feature that pauses not just sound but also animations might be preferable.  Presently, Cataclysm eats some CPU time in the background, so if you just want to leave Cataclysm running but not playing sound or doing anything, that's probably a closer match.

**Comment by Night-Pryanik** [comment]
No discussion in more than two years, closing.
