### ISSUE TITLE
Can't activate a UPS-modded item, unless the UPS is on your person

### ISSUE THREAD

**Issue by belazzz** [CleverRaven/Cataclysm-DDA#31370]
# Describe the bug

My understanding is that UPS-modded items are meant to be able to draw power from UPS sitting in the same tile or nearby. This works from the [&] screen, but not when [a]ctivating a tool.

# Steps To Reproduce

1. Get any UPS-modded tool or appliance that can be [a]ctivated, and a UPS with some charge.
2. Put the UPS in a nearby tile or container. Try activating the tool. The result should be the same whether the tool is in your inventory or in the same tile as the UPS.
3. (Bonus) Now drop the tool and take the UPS into your inventory, and try to activate the tool.

# Expected behavior

If I'm correct, the tool should be treated by the game as having the amount of charge equal to that of the nearby UPS source. At least that is the case when trying to use the tool for a recipe from the crafting screen. Instead, it is being treated as having no charge, unless the UPS is in your inventory. Apparently, the charge check for item activation works differently from the one used in crafting.

This behavior needs to be consistent for both these use cases (crafting and activation). Either they can be powered by a nearby UPS, or it always has to be in your inventory to work.

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 18.0.4; Codename: Illyria; 
- Game Version: 0.D-4211-g7a858a4 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Prevent Zombie Revivication [no_reviving_zombies],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    Garden Pots [growable-pots],
    Hydroponics [hydroponics],
    Fuji's More Buildings [FujiStruct]
]

**Comment by Inglonias** [comment]
Funny story. I'm actually checking to make sure that this is the case for all tools, because we want this to be expected behavior. You're right that the descriptions need to be fixed, though.

**Comment by kevingranade** [comment]
There's no contradiction here, activation is a distinct action, and you need to have a UPS in your inventory for it to work.
When crafting, sub-actions like picking up tools and UPSs is abstracted away and handled as part of the overall crafting activity.

**Comment by TechyBen** [comment]
> There's no contradiction here, activation is a distinct action, and you need to have a UPS in your inventory for it to work.
> When crafting, sub-actions like picking up tools and UPSs is abstracted away and handled as part of the overall crafting activity.

The UPS recharging station previously did allow you to leave a tool in the station, turn the station on, and use it for crafting while also being a couple of tiles away (crafting radius)... If I get time, I may try bug finding to make sure it all still works with the recent changes (UPS portable + charging station etc)...

**Comment by belazzz** [comment]
> When crafting, sub-actions like picking up tools and UPSs is abstracted away and handled as part of the overall crafting activity.

Ah, makes sense. I didn't think about this.

> The UPS recharging station previously did allow you to leave a tool in the station, turn the station on, and use it for crafting while also being a couple of tiles away (crafting radius)...

Yes, this is mostly what bugs me - having to shuffle batteries around every time. I wish you could put whole tools in the recharger without unloading the batteries.

Perhaps it can be done with a separate tool mod (e.g. "built-in charge controller mod"), which would allow a tool to receive power this way if it is loaded with a rechargeable battery.

Do you think I should create a feature proposal? I sadly lack the skill to do it myself.
