### ISSUE TITLE
Peeking through curtains causes them to remain see-through

### ISSUE THREAD

**Issue by SirHall** [CleverRaven/Cataclysm-DDA#31384]
# Describe the bug

When peeking through a curtain, usually 'cancelling' the peek puts the curtain back in a state where you can no longer see through it. However here peeking through a curtain and then stopping the peek will still allow you(and now other mobs) to see through the curtain(which is still closed).

To fully close the curtain you must open it, and close it again.

# Steps To Reproduce

1. Walk up to a curtain
2. Examine the curtain and peek through it
3. Stop peeking

# Expected behavior

The curtain should go back to a state where the player can no longer see through it.

# Screenshots
![image](https://user-images.githubusercontent.com/28499210/59406252-ce0aea00-8df0-11e9-89e9-a9ad68adc838.png)

# Versions and configuration

 - OS: 5.1.8-arch1-1-ARCH
 - Game Version: 0.D-4235-gad1332f1c5 (newest commit as of this issue)
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Disable NPC Needs, Craftable Gun Pack, Extended Realistic Guns, Garden Pots, Makeshift Items Mod, Medieval and Historic Content, More Survival Tools, Modular Turrets, Salvaged Robots, Hydroponics, Floating Parts pack, Boats, Vehicle Additions Pack, Tanks and Other Vehicles, 

# Additional context

I am building the game from source using these parameters: 
make -j2 RELEASE=1 LTO=1 TILES=1 SOUND=1 LOCALIZE=0 USE_HOME_DIR=1 CCACHE=1 BUILD_PREFIX=release/

**Comment by kevingranade** [comment]
This is fallout from the cache invalidation changes that just went in.
All we need to do is invalidate the transparency cash properly when we enter and exit peeking mode.
