### ISSUE TITLE
Asthma attacks trigger too often

### ISSUE THREAD

**Issue by chaoticidealism** [CleverRaven/Cataclysm-DDA#31383]
When 1-second turns were implemented, my asthmatic character started having many more asthma attacks than is realistic. For example, during the 4 hours it took him to read a book, I counted 13 asthma attacks. Reading seems to be particularly bad for triggering a lot of asthma attacks, but I think they're happening more in other situations too.

# Steps To Reproduce
1. Make asthmatic character.
2. Pass some time and count asthma attacks.

# Expected behavior
Real-life severe asthma forces a person to use an albuterol (stimulant) inhaler 4-8 times a day when poorly controlled. Cataclysm pre-1s had them somewhat more frequently, but still nowhere near 13 attacks in 4 hours.

# Versions and configuration
 - OS: Win7
 - Game Version: 0.D-4219-g5bce0cd 
 - Graphics version: Tiles
 - Mods loaded: DDA, no NPC needs, generic guns, makeshift items, moresurvival tools, mutant NPCs, mythical martial arts, no flaming weapons, classes and scenarios, safe autodoc, manual bionic, statsthroughskills, mythological replicas, CRIT expansion, magiclysm, modular turrets, salvaged robots, fasthealing

**Comment by mark7** [comment]
I've no familiarity with the 1-second change, but I did glance at the asthma code the other day, and it looks like it just rerolls periodically to see if an attack should occur.  If the time change increased the frequency of asthma attacks, it probably also fiddled with other things that happen at some fixed chance (teleglow effects?), and if so, might be preferable to do a bulk fix of all of them at once.

**Comment by Leosky** [comment]
should have been fixed with https://github.com/CleverRaven/Cataclysm-DDA/pull/31430
