### ISSUE TITLE
Map exploration is lost on game reload

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#31391]
# Describe the bug

Map exploration is lost on every game reload, both in old and new saves.

# Steps To Reproduce

1. Create a new character. Look at the map, see that some area is explored.
2. Save and quit.
3. Load the game. Look at the map, see that all map is unexplored.

# Expected behavior

The map exploration doesn't get lost.

# Screenshots

![image](https://user-images.githubusercontent.com/6495727/59438438-301d1c80-8dfc-11e9-8c12-52b6ee9ab5d9.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster);
- Game Version: 0.D-4248-g94874bc785 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionics Systems Mod [bio_mod],
    Makeshift Items Mod [makeshift],
    Garden Pots [growable-pots],
    NPC traits [npc_traits],
    Folding Parts pack [deoxymod],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3286414/debug.log)
[Astoria.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3286407/Astoria.zip)

**Comment by ZhilkinSerg** [comment]
Bisecting points to #31115, but I cannot see what could be causing such behavior.

**Comment by methanolium** [comment]
I can add that in some saves overmap is "shrinked" after load. It looks like only one "chunk" of it (where character is located) is lost. For me (Win64 Tiles) it started in 9148. Everything is fine in 9140.

**Comment by jagoly** [comment]
reverting just 74d9af4b82f3905bdea7a682d38cebc42462e5a3 fixes this, the same commit also seems to cause the issue I'm having where missions get messed up when loading a save

**Comment by ZhilkinSerg** [comment]
> 
> 
> reverting just [74d9af4](https://github.com/CleverRaven/Cataclysm-DDA/commit/74d9af4b82f3905bdea7a682d38cebc42462e5a3) fixes this, the same commit also seems to cause the issue I'm having where missions get messed up when loading a save

Thanks for testing this. We will take a closer look into changes in this PR.

**Comment by 7illian** [comment]
Experiencing this as well.

**Comment by sdp0et** [comment]
me as well.  all but one of about 8 reloads had this.  In addition, using a map once removed all knowledge of the nearby map tiles.  

I've also got the mission problem ZhilkinSerg mentioned.  The first reload of a save shows this:
```
16:14:52.790 ERROR : src/mission.cpp:74 [static mission* mission::find(int)] requested mission with uid 2 does not exist
16:14:52.793 ERROR GAME : src/mission.cpp:73: requested mission with uid 2 does not exist
```
several times.  More than my current number of active/completed missions (maybe the others are missions that would be given out in mission chains?).  The missions are still listed for me and I get the marker, but the NPC who gave them stops asking about them so they can't be completed.  Subsequent loads don't have that error, so they're probably not being saved after the initial errors making it seem like they've been removed from the NPCs.  I tried editing the NPCs missions and they didn't have any and I couldn't see an option to add any new ones to give out.

**Comment by P0NYSLAYSTATION** [comment]
I'm having the same issue, can't confirm about missions as I didn't have any. The bug only affects overmap knowledge gained through exploration, everything I know from reading tourist guides, maps etc remains

@sdp0et You could wish yourself maps and guides I think, your knowledge from them is permanent, although you still wont remember any buildings and maps that weren't on the item

[Grayburg.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3292881/Grayburg.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3292883/debug.log)

**Comment by Igryn** [comment]
Have same issue, no mods exept npc needs toggled off

**Comment by Zombiemanpig** [comment]
Can confirm this bug is real and super annoying.

**Comment by Zombiemanpig** [comment]
This is not fixed @kevingranade I just tested it in 9161.

![image](https://user-images.githubusercontent.com/47362783/59555504-5a4c1700-8f81-11e9-97f9-f488047fa2ac.png)

**Comment by ZhilkinSerg** [comment]
It was not fixed in 9161 because fix is in 9162.

**Comment by xMyrkin** [comment]
9161 have #31469 PR...  we'll wait and pray for 9162 :)

**Comment by Zombiemanpig** [comment]
> 9161 have #31469 PR... we'll wait and pray for 9162 :)

Fixed in 9162, it did say that 9161 was the release with the fix.
