### ISSUE TITLE
Cash cards no longer stack

### ISSUE THREAD

**Issue by molkero** [CleverRaven/Cataclysm-DDA#31394]
# Describe the bug

Cash cards don't stack like they used to.

# Steps To Reproduce

1. Pick up cash cards.
2. Check inventory.

# Expected behavior

Cash cards would stack.

# Screenshots

![20190613205405_1](https://user-images.githubusercontent.com/49575273/59456047-23a9bb80-8e1e-11e9-8336-9cf3555fce8c.jpg)

# Versions and configuration

 - OS: linux
 - Game Version: 0.D-4254-g4259f65
 - Graphics version: tiles
 - Mods loaded: dda, extended realistic guns, icecoon's arsenal, makeshift items mod, more survival tools, mutant npcs, boats, folding parts pack, tanks and other vehicles, classes and scenarios mod, sleep deprivation, magiclysm

**Comment by molkero** [comment]
Never mind, didn't happen in new world.

**Comment by EvgenijM86** [comment]
I did a latest git pull (at 888f3e381b1b066fef5053616400bda65ffd1b60), compiled with "make -j8 RELEASE=1 TILES=1 SOUND=1 CCACHE=1 LUA=1", created a new world and encountered this issue.

**Comment by EvgenijM86** [comment]
This bug is also present on "chunks of chitin" item - https://github.com/CleverRaven/Cataclysm-DDA/issues#issuecomment-504668602

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.D-8431. Closing for now, ping me if this is still an issue.
![изображение](https://user-images.githubusercontent.com/11132525/66703080-b6505d80-ed1f-11e9-9719-5befedfdb919.png)
