### ISSUE TITLE
Player info trait list not scrolling.

### ISSUE THREAD

**Issue by molkero** [CleverRaven/Cataclysm-DDA#31397]
# Describe the bug

Player info screen trait list can't be scrolled like the bionic list, instead "extra" traits are printed on the last line of the list.

# Steps To Reproduce

1. Get a lot of traits.
2. Check them on player info screen.

# Expected behavior

Trait list could be scrolled like the bionics list.

# Screenshots

![20190613212146_1](https://user-images.githubusercontent.com/49575273/59458075-6077b180-8e22-11e9-9ac1-796d8e817366.jpg)
![20190613212209_1](https://user-images.githubusercontent.com/49575273/59458086-666d9280-8e22-11e9-8dbc-77d275019d88.jpg)

# Versions and configuration

 - OS: linux
 - Game Version: 0.D-4254-g4259f65
 - Graphics version: tiles
 - Mods loaded: dda

**Comment by jagoly** [comment]
so I went to start looking into this, but when I get lots of traits, this happens 
![Screenshot from 2019-06-15 12-57-53](https://user-images.githubusercontent.com/4125929/59546262-8c537e00-8f6d-11e9-9d04-6d183ae4c29b.png)

I can't get it to do the thing you've shown. Are you actually using the curses version? or just tiles with some ascii tileset

**Comment by kevingranade** [comment]
They have a much smaller terminal so it can't grow any more.
