### ISSUE TITLE
Builds for Windows x84 and x64 are failing.

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#31392]
# Describe the bug

The launcher tells me that builds for windows x84 and x64 have failed six times in a row now (from Build 9141 to Build 9147 ) this seems unusual.

# Additional context

I don't know if this is expected sometimes or even how to get a proper log of what is going on... sorry if this is not informative enough.

**Comment by Kilvoctu** [comment]
The reason for this is referenced in build #9147 ([Fix OSX and MXE Windows builds](https://github.com/CleverRaven/Cataclysm-DDA/pull/31385)).
