### ISSUE TITLE
Vehicle Additions Pack Crashing on version 9148

### ISSUE THREAD

**Issue by Zaragata** [CleverRaven/Cataclysm-DDA#31396]
# Describe the bug

Game gives error when loading into character creation.
Ruled it out to be Vehicles Additions Pack mod.

# Steps To Reproduce

1. Create a new world with Vehicle Additions Pack mod on;
2. Try to create a new character.

# Expected behavior

To work.

# Screenshots

None

# Versions and configuration

- OS: Windows 10 LTSC - 1809
    - OS Version: 10.0 1809
- Game Version: 0.D-4254-g4259f65 [64-bit]
- Graphics Version: Tiles
- Mods loaded:
    - Dark Days Ahead [dda],
    - Vehicle Additions Pack [blazemod]

# Debug Info

`DEBUG : warnings for type cannister_rack:`
`invalid default_ammo h_projectile`
`FUNCTION : void Item_factory::check_definitions() const`
`FILE : src/item_factory.cpp`
`LINE : 1126`

`DEBUG : warnings for type bfeedfuel:`
`ammo type  is not known`
`FUNCTION : void Item_factory::check_definitions() const`
`FILE : src/item_factory.cpp`
`LINE : 1126`

`DEBUG : warnings for type h_projectile:`
`ammo type  is not known`
`FUNCTION : void Item_factory::check_definitions() const`
`FILE : src/item_factory.cpp`
`LINE : 1126`

**Comment by Krylia** [comment]
So, I worked it out so it doesn't spew the errors by trying to fix the issues it was having, but it gives a seg fault crash on the second time you load up character creation.
Here is the crash log, dunno if it'll be useful to anyone.
If you want me to give system details, just ask I guess? Sorry, kind of new to this.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3292159/crash.log)
