### ISSUE TITLE
RECHARGE tag allow recharging disposable and plutonium batteries

### ISSUE THREAD

**Issue by Highmongrel** [CleverRaven/Cataclysm-DDA#31408]
# Describe the bug

Tools with the RECHARGE tag allow charging uncharge-able batteries

# Steps To Reproduce

1. Load a rechargable tool with a disposable battery
2. Discharge the battery
3. Place tool in powered recharging station

# Expected behavior

Batteries don't charge

# Screenshots

![image](https://user-images.githubusercontent.com/47551519/59478245-7af36000-8e0d-11e9-8838-7fe70f3766e8.png)
![image](https://user-images.githubusercontent.com/47551519/59478262-8cd50300-8e0d-11e9-93a0-154773799992.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-4256-g5dcae08 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

UPS is potentially having its flag removed as of #31388 but electric blankets, control laptops, powered quarterstaves, tactical tonfas, tazers and space heaters can all be used to charge un-chargable batteries.

**Comment by Inglonias** [comment]
So the UPS can't recharge with a battery inside, but these tools can? Why?! The reason I removed the UPS' recharge flag is because I thought you COULDN'T recharge the batteries if they were in the tools already!

...Should be an easy fix, at any rate, but what the heck is actually happening here?
