### ISSUE TITLE
Cataclysm++ Causing Crashes

### ISSUE THREAD

**Issue by Bill-Chompski** [CleverRaven/Cataclysm-DDA#31402]
# Describe the bug

Whenever I attempt to make or load a new world with Cataclysm++ in the mod list, it sends me right back to the main menu without even getting to the character creation menu.

# Steps To Reproduce

Just play a game with Cataclysm++.

# Expected behavior

The game will not load the character creation, sending you back to the main menu after an error message.

# Screenshots

# Versions and configuration

<!-- Please complete the following information; you can now go to:
 
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-4254-g4259f65 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Extended Realistic Guns [realguns],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Secronom [secronom],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    CC's Additional Dumps [ccdump],
    CC's Additional Parks [ccpark],
    CC's Additional Vacant Locations [ccvacant],
    Caches [P_Caches],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Boats [boats],
    Vehicle Additions Pack [blazemod],
    Classes and Scenarios Mod [more_classes_scenarios],
    Extra Scenarios [Ex_Scenarios],
    Military Professions Mod [More_Military],
    Bionic Slots [cbm_slots],
    C.R.I.T Expansion Mod [crt_expansion],
    Beta National Guard Camp [national_guard_camp]
also Cataclysm++ but I couldn't generate a report with it in the modlist since I couldn't make a world to generate a report if C++ was there.
]

# Additional context

I think that Crazy Cataclysm might be doing it too, for some reason. It gave me the same error while I had CC on, but not C++ on, but with both removed, the error stopped.

<!-- Crash: if your problem refers to a crash, please add the following files to the "Additional Context" 
Unfortunately since I can't make a world to produce a savefile (or I don't know how), I only have this picture of the error message 
https://i.imgur.com/hjGQRZn.png

**Comment by Bill-Chompski** [comment]
I messed up posting it I think, because everything else I wrote past "expected behavior" isn't shown.
Anyway here's a picture of the error https://i.imgur.com/hjGQRZn.png
And cause I can't make a world with the mods, I can't get a save file or at least don't know how.

**Comment by anothersimulacrum** [comment]
Bug reports for external mods go on the [repositories for those mods](https://github.com/Noctifer-de-Mortem/nocts_cata_mod).

**Comment by ZhilkinSerg** [comment]
We do not fix third party mods here.
