### ISSUE TITLE
Unable to sleep on pile of clothes.

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#31409]
# Describe the bug

I cannot sleep on the ground, regardless of how many clothes I use as a bed.  

When sleeping in a bed, it refers to blankets as 'pile of clothes', so I assumed that clothing on the ground would function as a relatively comfortable place to sleep.  Not so.

Despite trying for AGES (character is exhausted AND I took 2 ambien) I was still unable to sleep.  I was on linoleum tile with a ton of clothes.  My character does not have insomnia or any sleep-related trait, and was full, hydrated, and tired when I first tried to sleep.

# Steps To Reproduce

I assume that you could just throw clothes anywhere on the ground and try to sleep.

# Expected behavior

I don't see why a pile of clothes would not function as a relatively comfortable place to sleep.  My character set up a cot (which I assume is just a pipe frame and a thin mat) and was able to fall asleep instantly.  I think I'd prefer the pile of clothes . . .

If you don't want to make it a 'comfortable' place to sleep, that's fine.  However, a character that's at 'exhausted'/been up for 3 days should be able to fall asleep basically anywhere, especially when they took multiple sleep pills.  I tried for about 24 full hours before I became furious and found an alternative.

# Screenshots
<img width="220" alt="messages" src="https://user-images.githubusercontent.com/41651793/59481996-ca995200-8e34-11e9-91e7-e4561a73fddc.png">
<img width="221" alt="pile" src="https://user-images.githubusercontent.com/41651793/59481997-cb31e880-8e34-11e9-96cd-006f4096c3d0.png">

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-3936-g9f52909 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Bens GF recipes [Tolerate_This],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Caches [P_Caches],
    Folding Parts pack [deoxymod],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food]
]

# Additional context
There are other issues similar to this, specifically: #30221 and #28247 but those were not specifically about using piles of clothing as a bed.  I thought this was different enough.

**Comment by ZhilkinSerg** [comment]
> I cannot sleep on the ground, regardless of how many clothes I use as a bed.

There is no code for that. Only items with `SLEEP_AID` are helping, but it should be trivial to add help from other items here:

https://github.com/CleverRaven/Cataclysm-DDA/blob/81422ba8e44c20240357e66a0e974eaa068745d8/src/player.cpp#L9713-L9720

For the start, I would try to take weight and material into account - i.e. certain total weight of items made of cotton should give some comfort.

**Comment by nexusmrsep** [comment]
Pile of clothes - as far as the code defines it - is a replacement for a blanket. It keeps you warm, but nothing else, yet. So it works under assumption that you lie on the ground and cover yourself with spare clothes and/or use them as a weak insulation from the cold ground, but not thick and organized enough to provide any extra comfort in sleeping.

**Comment by TheMurderUnicorn** [comment]
I see.  I was under the impression that clothing could replace a mattress, or that it previously had.  I'd LIKE it to work that way, but alright.  I'll close this issue.
