### ISSUE TITLE
map notes do not render

### ISSUE THREAD

**Issue by IvanShestakov** [CleverRaven/Cataclysm-DDA#31415]
Whenever I add a map note it is stored and can be seen in notes 'L'ist but it doesn't show on the map.

1. Add a map note. 
2. Try to locate it on map.

# Screenshots
![Screenshot_2019-06-14_10-26-43](https://user-images.githubusercontent.com/9976709/59491404-58a22680-8e8f-11e9-972e-e875478b02e3.png)
![Screenshot_2019-06-14_10-27-16](https://user-images.githubusercontent.com/9976709/59491405-58a22680-8e8f-11e9-9ceb-77e66888cc46.png)
![Screenshot_2019-06-14_10-27-41](https://user-images.githubusercontent.com/9976709/59491406-58a22680-8e8f-11e9-9b4e-3f0cffa6ddc4.png)

"Additional context" -->

# Versions and configuration
GAME REPORT: 
- OS: Linux
    - OS Version: Distributor ID: LinuxMint; Description: Linux Mint 18.3 Sylvia; Release: 18.3; Codename: sylvia; 
- Game Version: 0.D-4518-g4563cc4-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    Mutant NPCs [mutant_npcs],
    Folding Parts pack [deoxymod]
]

**Comment by ZhilkinSerg** [comment]
Map notes overlay is toggleable now. Look at the right menu to see key (`G` is used by default) and state of overlay (pink - enabled, magenta - disabled).

**Comment by l29ah** [comment]
I think they should be enabled by default to avoid such confusion (and introduce the functionality to the new players).
