### ISSUE TITLE
Any chance of multiple tileset_config files?

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#31417]
Right now tileset can have only one json file with tileset configuration, if i understand correctly. This creates the problem when png file runs out of space, nextone need to be assigned after, and numeration of tile ids should be continued from the last one. It is really not confortable at all.
How i see ideal situation - tileset has multiple json config files, all of them are assigned in tileset.txt in load order (same IDs from next file will overwright previous) and in each json numeration of ids starts from zero. That way if, for example, my guns.png file runs out of space i can just extend it's canvas and continue working in this file without worrying about other IDs after it.

How tileset works now
tileset.txt->tile_config.json->1_guns.png->2_monster.png->3_character.png

if i run out of space in 1_guns.png i can not extend this file, because if i change its size all numbers for IDs in 2_monster.png and in 3_character.png will be shifted on the number of grid cell i extended this file

How i want tileset to work

tileset.txt:
tile_config_guns.json->guns.png
tile_config_monsters.json->monsters.png
tile_config_characters.json->charactets.png
 
that way any png file size can be changed without any problems for rest of the IDs

And old way still can be there for old tilesets, i just want ability to use multiple configs with numbers starting with zero in each one of them.

I apologise for my poor english, i hope you can understand what i want. :stuck_out_tongue_closed_eyes:

**Comment by OrenAudeles** [comment]
If I'm understanding correctly: allow multiple tile config files, and each tile config would have tile ids relative to the first tile in the referenced image.
Single primary config file: `tile_config.json`
```json
{
  "tile_info": [
    {
      "height": 32,
      "width": 32
    }
  ],
  "files": [
    "tile_config_guns.json",
    "tile_config_monsters.json",
    "tile_config_characters.json"
  ]
}
```
Then each of the listed files would handle the loading of the associated image, and use image tile relative indexes. The upper-left tile would be index zero. Might make sense to have "global" tiles available for reference such as backgrounds, and would need a way to say "Use global tile ### for this id."

Am I anywhere near what you're thinking of?

**Comment by SomeDeadGuy** [comment]
Almost. I was thinking maybe list config files in tileset.txt, but i guess this will work too.
If i choose to, i can still use two or more png files for config, like it is now.

**Comment by ifreund** [comment]
Something like https://github.com/ifreund/tileset_compiler/ (when completed) would also solve this issue.  Once the initial support for tile definitions is there I may look in to a script to convert existing tilesets to the folder hierarchy format.  

A compiler script like that would also allow optimization of the tileset, removing duplicate sprites and losslessly compressing the pngs for better load times

**Comment by Zaragata** [comment]
Last year when I tried to update xotto tileset I used _GAWK 4 dot something_ to parse the tileset_config for that exact reason. That said, it's still not a comfortable solution at all.

If you want, I can try to rewrite that script for you.

**Comment by ifreund** [comment]
>If you want, I can try to rewrite that script for you.

Well, I don't think it needs a rewrite, just more time put into it than I have right now.  I'm pretty focused on integrating colonies into the code right now.

I would welcome any PRs extending the functionality of the script of course.  Feel free to fork or write your own too of that's what you think is easiest.

**Comment by mark7** [comment]
Git also does not deal very well with PNG files stored in git respositories -- each commit generates a huge commit the size of the new file.  Every time any change is made to a PNG file in one of the tileset git repos, the repository gets bigger.  Change a pixel in a tile, new copy of the whole image gets saved.  The current Cata-MSX-DeadPeopleTileset is at about 1.1GB.

Splitting up the images in to single-tile images and using the above-referenced tileset_compiler addresses this issue, but it also means that there's a stage of compilation required to use the tileset.

**Comment by kevingranade** [comment]
Poking to keep it open for @ifreund#4573
