### ISSUE TITLE
Magiclysm Z Level Targeting Bug when using Stairs.

### ISSUE THREAD

**Issue by RedPine91** [CleverRaven/Cataclysm-DDA#31410]
Magiclysm Mod, Magic Missile Spell, Apartment Tower in More Locations.

Immediately after going up or down a Z-Level using stairs, the spell targetting gets stuck on the previous Z Level, and will attempt to target the previous Z Level instead of the current Z Level.  This results in aiming at a place the player cannot see, preventing casting.

While aiming a spell, pressing "<" then ">" resets the targetting to the current Z Level.  Spending enough time on a Z Level also seems to bring the targetting to the current Z Level.

Build #9150

**Comment by RedPine91** [comment]
No clairvoyance involved, but seeing as this issue is over a year old, it might have been fixed at some point.  If you can't replicate it, the bug is likely gone.

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.
