### ISSUE TITLE
Blazemod loading errors for ammotype specifiers

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#31427]
# Describe the bug
Item_factory::check_definitions is throwing errors for some blazemod ammotype specifiers.

# Steps To Reproduce
Create a new world with blazemod active.

# Expected behavior
Included mods will all load without errors.

# Screenshots
https://cdn.discordapp.com/attachments/365907426270117888/589107777176207405/unknown.png

**Comment by Magikjak** [comment]
I'm getting the same error but I suspect it relates to Extended Realistic Guns instead of Blazemod, as I am not running Blazemod. If you skip through the errors it throws an error for each of the guns in Extended Realistic Guns

**Comment by Magikjak** [comment]
I've attached my debug log (new to this so I'm not sure the general way to go about linking it) for more information.

These are the mods I am using (I know I said earlier that I wasn't using blazemod but I didn't realise at the time the Vehicle Additions Mods was blazemod)

  "type": "MOD_INFO",
  "ident": "user:default",
  "dependencies": [ "dda", "realguns", "growable-pots", "makeshift", "Medieval_Stuff", "More_Survival_Tools", "alt_map_key", "modular_turrets", "Salvaged_Robots", "hydroponics", "mutant_npcs", "national_guard_camp", "more_locations", "FujiStruct", "mapgen_demo", "Urban_Development", "deoxymod", "blazemod", "Tanks", "more_classes_scenarios", "manualbionicinstall", "safeautodoc", "StatsThroughSkills"


[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3291566/debug.log)

**Comment by Krylia** [comment]
Issue here seems related to #31396

**Comment by Magikjak** [comment]
On further investigation this error happens with any world running ONLY DDA and Vehicle Additions Mod, with further errors from other mods that have extra ammo types (such as Extended Realistic Guns), debug log attached

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3292761/debug.log)
