### ISSUE TITLE
Focus loss too fast, possibly new 1 sec turns related.

### ISSUE THREAD

**Issue by TechyBen** [CleverRaven/Cataclysm-DDA#31423]
[Edit] I guess I'm late to the show. If this is a double post, please delete [/edit]
Describe the bug

Focus appears to still be on 6 second turns tick. Now char loses focus 6x faster.

Steps To Reproduce

Doing practically any task, even walking around and focus drops to 25 or less in a few mins.

Expected behavior

Focus to have some useability, or rebalance.

Versions and configuration

Current builds.

I know there are a lot of things that will be updated, but adding so this one can be tracked.

PS, my apologies if I don't understand the code. It may be Focus is used up 6X fast, or is being generated 6X too slow. Thanks.

**Comment by ymber** [comment]
I can't reproduce this and the code looks like it should be fine. Update rate for focus is independent of turn length and there's nothing timing related in `player::update_mental_focus`.
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/player.cpp#L720

**Comment by ifreund** [comment]
Closing, as this doesn't seem to be a a bug.
