### ISSUE TITLE
Machines in cataclysm

### ISSUE THREAD

**Issue by lmaolollmao** [CleverRaven/Cataclysm-DDA#31436]
**Is your feature request related to a problem? Please describe.**  
It takes a long time to craft things especially endgame for example reloading ammo, etc.

**Describe the solution you'd like**  
Add machines like cnc machines that require power in order to run but they can craft things much faster and make bigger batches.

**Describe alternatives you've considered**  
Or atleast make some way to craft faster with a special workbench or something.
**Additional context**  
If we can make vehicles with automatic laser turrets on them all powered by a plutonium minireactor i think machines arent too far out there in terms of realism

**Comment by kevingranade** [comment]
Those kinds of tools will be added, but they aren't likely to do what you think. They can't run unattended and the time to set them up makes manual crafting faster unless you are crafting extremely large batches of items.
