### ISSUE TITLE
Map items reveal incorrect location

### ISSUE THREAD

**Issue by yellowcrescent** [CleverRaven/Cataclysm-DDA#31444]
# Describe the bug

Map items (tourist map, road map, etc.) reveal an incorrect area of the overmap, double the distance away on X any Y axes. Example item "Moscow tourist map" (where Moscow is at -97, 339, 0). Transformation via `om_to_sm_copy()` seems to be why this happens, so potentially map target location needs to be corrected in `reveal_map_actor::use()`?

Disabling all mods (except DDA) doesn't seem to make any difference. Have also created a new World and Character, which didn't seem to help, either. I haven't noticed any similar reports recently, so it's possible I have done something weird, but not sure what it could be.

Last known-working version I tested was build 8774; build 8998 was broken.

# Steps To Reproduce

1. Find or spawn in any map item
2. Use map item
3. Map is not revealed at expected location
4. Scroll on overmap in one of the intermediate directions (NW, NE, SW, SE; depends on whether X and Y are positive or negative) until the revealed area is shown in incorrect location. I think the only time maps might work correctly are with near-zero X and Y coords.

# Expected behavior

Map item to reveal correct location.

# Screenshots

Expected vs Actual reveal location (note the coordinates):
![](https://ss.ycnrg.org/jotunn_20190614_030108.png)
![](https://ss.ycnrg.org/jotunn_20190614_030154.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 16.04.2 LTS; Release: 16.04; Codename: xenial; 
- Game Version: 0.D-4200-g9626aa7 [64-bit] (git: cdda-jenkins-b9138 @ 9626aa7)
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Extended Realistic Guns [realguns],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

Compiled b9138 with debug symbols, and set a breakpoint inside of `reveal_map_actor::use`:

```
(gdb) b src/iuse_actor.cpp:1097
Breakpoint 2 at 0xda0213: file src/iuse_actor.cpp, line 1097.
(gdb) c
Continuing.

Thread 1 "cataclysm-tiles" hit Breakpoint 2, reveal_map_actor::use (this=0x5ccff40, p=..., it=...) at src/iuse_actor.cpp:1097
1097	    const tripoint &center = omt_to_sm_copy( it.get_var( "reveal_map_center_omt",
(gdb) s
item::get_var (this=this@entry=0x1d897e70, name="reveal_map_center_omt", default_value=...) at src/item.cpp:766
766	{
(gdb) print default_value
$1 = (const tripoint &) @0x7fffffffb250: {x = -101, y = 343, z = 0}
(gdb) n
767	    const auto it = item_vars.find( name );
(gdb) n
768	    if( it == item_vars.end() ) {
(gdb) n
771	    std::vector<std::string> values = string_split( it->second, ',' );
(gdb) n
774	                     atoi( values[2].c_str() ) );
(gdb) print values
$3 = std::vector of length 3, capacity 4 = {"-97", "339", "0"}
(gdb) n
773	                     atoi( values[1].c_str() ),
(gdb) n
774	                     atoi( values[2].c_str() ) );
(gdb) n
772	    return tripoint( atoi( values[0].c_str() ),
(gdb) n
774	                     atoi( values[2].c_str() ) );
(gdb) n
771	    std::vector<std::string> values = string_split( it->second, ',' );
(gdb) n
775	}
(gdb) n
reveal_map_actor::use (this=0x5ccff40, p=..., it=...) at src/iuse_actor.cpp:1098
1098	                             p.global_omt_location() ) );
(gdb) n
1099	    for( auto &omt : omt_types ) {
(gdb) print center
$5 = (const tripoint &) @0x7fffffffb260: {x = -194, y = 678, z = 0}
```

Attaching save dir. Character has the 'Moscow tourist guide' in their inventory (unused).

Debug log doesn't show any relevant backtraces or other info.

[ThornyGrove.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3292636/ThornyGrove.zip)

**Comment by TechyBen** [comment]
Hmmm. In my save (9139) trails were really big, so covered a lot of the map away from me. The town/tourist route was actually a different neighbouring town.

What are you world gen options? I wonder if the game picked the next town in the list to map, and the closest was miles away?

Could be a feature (not always a local mapped area, sometimes a surprise area) or a bug?

**Comment by yellowcrescent** [comment]
Looks like b8774 didn't actually work either, after further testing. If your starting location is near zero (less than about 128, 128), you'll still see parts of the revealed map area (but it will not be centered on the correct location), since it reveals a 180 tile radius from the target location (360 tall/wide). To confirm, teleport to `256,256` (2'0, 2'0 on the overmap), then spawn in a road map and activate it. So it may be possible it has always worked like this, not sure.

Dividing the X and Y coordinates by 2 fixes the issue, although not sure if this is the best approach. I'll do some more testing later today and submit a PR, unless somebody else has a better idea (I tried swapping `omt_to_sm_copy()` for `omt_to_om_copy()`, but that did not work).

```
diff --git a/src/iuse_actor.cpp b/src/iuse_actor.cpp
index b8d58c4..b710519 100644
--- a/src/iuse_actor.cpp
+++ b/src/iuse_actor.cpp
@@ -1098,7 +1098,7 @@ int reveal_map_actor::use( player &p, item &it, bool, const tripoint & ) const
                              p.global_omt_location() ) );
     for( auto &omt : omt_types ) {
         for( int z = -OVERMAP_DEPTH; z <= OVERMAP_HEIGHT; z++ ) {
-            reveal_targets( tripoint( center.x, center.y, z ), omt, 0 );
+            reveal_targets( tripoint( center.x / 2, center.y / 2, z ), omt, 0 );
         }
     }
     if( !message.empty() ) {
```
