### ISSUE TITLE
Crash on generating world - non-existing faction 't_tree_cottonwood'

### ISSUE THREAD

**Issue by Kilvoctu** [CleverRaven/Cataclysm-DDA#31447]
# Describe the bug

Crash to desktop upon loading world, whether a save game or new character in world:
_src/faction.cpp:363 [faction* faction_manager::get(const faction_id&)] Requested non-existing faction 't_tree_cottonwood'_

# Steps To Reproduce

Attempt to load any character into the world

# Expected behavior

World is generated successfully.

# Versions and configuration

 - OS: Windows 7 64bit
 - Game Version: 0.D-4328-ga6cb1c7 
 - Graphics version: Tiles
 - Mods loaded:
  "dda",
  "no_npc_food",
  "crt_expansion",
  "Tolerate_This",
  "SD_Magcrafting",
  "realguns",
  "growable-pots",
  "guncotton",
  "makeshift",
  "More_Survival_Tools",
  "DracoDogMod",
  "modular_turrets",
  "Salvaged_Robots",
  "secronom",
  "alt_map_key",
  "hydroponics",
  "BIGRIVER",
  "more_locations",
  "FujiStruct",
  "cityside",
  "Urban_Development",
  "deoxymod",
  "blazemod",
  "Tanks",
  "Arts' Guns",
  "more_classes_scenarios",
  "safeautodoc"

# Additional context

Issue first was seen on build 9152. Afterwards, reverting previous build version did not solve the issue for me. I eventually found a workaround by creating a "t_tree_cottonwood" faction in my world's master.gsav file, allowing me to play with no apparent issues up until a random CTD occuring while on build 9156 (was walking towards a vehicle inside my main hideout). Now game crashes regardless. Issue still persists on build 9157. 

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3292762/config.zip)
https://drive.google.com/file/d/1Ncg9vDOpdctdZHG_NR0rOY7RNqKI5KQi/view?usp=sharing
Save file is too big to attach.

**Comment by ZhilkinSerg** [comment]
Should be fixed in build 9162.
