### ISSUE TITLE
Crash when shooting with sling / bow

### ISSUE THREAD

**Issue by ShadowMiner** [CleverRaven/Cataclysm-DDA#31451]
# Describe the bug

Crash when attempting to shoot with sling.

# Steps To Reproduce

1. Get sling or bow
2. Right click on enemy / press shoot key.
3. Get crash

# Expected behavior

No crash.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-4328-ga6cb1c7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Mining Mod [Mining_Mod],
    Альтернативные символы карты [alt_map_key],
    NPC-мутанты [mutant_npcs],
    Мод на самодельные вещи [makeshift],
    Мод с дополнением К.Р.И.Т [crt_expansion]
]

# Additional context

[debug&crash log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3292796/debug.crash.log.zip)
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3292797/default.zip)

**Comment by zacklucky7** [comment]
Reported in #31398, crash is related to changes in build 9143. Revert to 9140 as a temporary fix
