### ISSUE TITLE
Unable to play world on latest build

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#31450]
![image](https://user-images.githubusercontent.com/44106380/59547928-587e5580-8f79-11e9-887d-3284d83532fb.png)

I've updated to the latest build 9157.
Since then i still can't load my game and had to revert to build 9140 for the second time.

**Comment by LaVeyanFiend** [comment]
Duplicate of #31399. Should be fixed once once #31442 gets merged.
