### ISSUE TITLE
Zombies (including dogs) can climb ladders

### ISSUE THREAD

**Issue by zacklucky7** [CleverRaven/Cataclysm-DDA#31461]
# Describe the bug

Zombies, including zombie dogs, are capable of following the player while climbing ladders.

# Steps To Reproduce

1. Get a zombie on your tail.
2. Climb up a ladder.
3. The zombie will climb the ladder after you.

# Expected behavior

With the increasing use of Z-levels, ladders are being added to many buildings. This could lead the players to believe that ladders are a safe way to escape zombies.

You could argue that some more powerful zombies (like bio-operators) might know how to climb ladders, but it seems like most zombies have trouble walking in a straight line towards you without fumbling and may not be able to operate ladders.

At the very least, zombie dogs being able to climb ladders is at least a more obvious bug.

# Screenshots

Context of screenshot:

1. I used the debug menu to spawn a zombie dog, made sure it was aware of me, and then climbed a ladder and waited for it to follow.

![zombie dog climbing ladder](https://dl.dropboxusercontent.com/s/264pzgu9yyh4rg8/cataclysm-tiles_2019-06-15_06-01-53.png "zombie dog climbing ladder")

This is with experimental Z-levels disabled (for performance reasons) but they still follow with Z-levels enabled.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-4219-g5bce0cd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Filthy Clothing [filthy_morale],
    Garden Pots [growable-pots],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Sleep Deprivation [sleepdeprivation],
    StatsThroughSkills [StatsThroughSkills],
    Generic Guns [generic_guns],
    Mythological Replicas [nw_pack],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    sees-player icon, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex]
]

# Additional context

n/a

**Comment by jeremyshannon** [comment]
I don't think even bio-operators should climb ladders -- their martial arts ability comes from a CBM, and while the software in it is pretty advanced, I doubt it includes a "ladder climbing" DLC or anything.

**Comment by tinukedaya** [comment]
Just got a friendly horse follow me to the barn 2nd level thru ladder.

**Comment by FirebrandCoding** [comment]
@tinukedaya: that's a good horse. You should keep it. ;)

I've never seen a zombie climb a ladder, nor do I expect them to. It's a technical thing zombie brains shouldn't allow for, considering the best way they consistently chase the player character on the streets is by breaking whatever stands between them and the target.

That said: I'm surprised they're unable to use stairs. I'm sure even the husk of a human can understand lifting their foot to step on a higher platform. On my first playthrough, I'd go to the second floor of the mansion I stayed in, and lay down bubble wrap traps in front of the stairs 'cause I worried zombies might come up.

**Comment by jeremyshannon** [comment]
Nearby zombies have been able to chase you up stairs since before the multi-z-levels change, and with z levels enabled, wandering zombies should be able to walk on in and climb stairs, though they're really dumb so it'll be pretty unlikely to happen unless they saw you go up them, or are following your scent.

**Comment by kevingranade** [comment]
I agree no zombies without a special flag should be able to climb ladders, so basically we add a flag to ladders that says they're difficult to climb and then check for that in the monster move code.

**Comment by ThomasLinkin** [comment]
For the people who don't get it,they were talking of LADDER, not STAIRS. so don't say things like "but zombies are able of climbing stairs"
