### ISSUE TITLE
Error in blazemod ammotypes

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#31477]
# Describe the bug

Loading game with blazemod enabled throws ammo type errors, corresponding ammo not working.

# Steps To Reproduce

1. Load save with blazemod
2. Observe

# Expected behavior

No errors, ammo is working.

# Screenshots

None

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-4361-g6508a5c
 - Graphics version: Tiles
 - Mods loaded: [
  "dda",
  "no_npc_food",
  "aftershock",
  "More_Survival_Tools",
  "makeshift",
  "craftgp",
  "growable-pots",
  "modular_turrets",
  "mutant_npcs",
  "alt_map_key",
  "hydroponics",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "boats",
  "blazemod",
  "deoxymod",
  "Tanks",
  "DP_REMIX_INDICATORS",
  "MMA",
  "safeautodoc",
  "no_reviving_zombies",
  "more_classes_scenarios",
  "StatsThroughSkills",
  "EngineeringEssentials"
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3293340/debug.log)

**Comment by anothersimulacrum** [comment]
Can you confirm this after #31459?
I tried on the latest master and cannot.

**Comment by eilaattwood** [comment]
> 
> 
> Can you confirm this after #31459?
> I tried on the latest master (0.D-4382-gf1a5f47d5b) and cannot.

Sure. I've just checked after update, and specified game version in the issue. It's on most recent game. Also compared touched blazemod's json files, they are updated.

**Comment by eilaattwood** [comment]
It is not crashing, it is just throwing debug errors. Game still loads, but more errors when trying to handle involved guns/parts

**Comment by ZhilkinSerg** [comment]
It should be closed in 9160 and above.

**Comment by eilaattwood** [comment]
> 
> 
> It should be resolved in 9160 and above.

But I'm on 9160 now, and it's here.

**Comment by ZhilkinSerg** [comment]
> 
> 
> > It should be resolved in 9160 and above.
> 
> But I'm on 9160 now, and it's here.

Yeah? And when did you get 9161 if this build failed.

![image](https://user-images.githubusercontent.com/16213433/59555527-8fc22600-8fbc-11e9-9a1f-5dd9a774b11b.png)
