### ISSUE TITLE
Crash when loading existing game or starting new one

### ISSUE THREAD

**Issue by Eliijahh** [CleverRaven/Cataclysm-DDA#31472]
# Describe the bug

Game prevents me from loading save game.

# Steps To Reproduce

1. Use the savefile attached to this issue
2. Try to load the game

# Expected behavior

The game should be loaded successfully.

# Screenshots

<img width="1680" alt="Screenshot 2019-06-15 at 16 06 31" src="https://user-images.githubusercontent.com/11465983/59553066-93878580-8f87-11e9-9059-35a873ab38cf.png">

# Versions and configuration

 - OS: MacOs Mojave 10.14.5
 - Game Version: b69b9a15db
 - Graphics version: Tiles
 - Mods loaded: None

# Additional context
[error_logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3293264/error_logs.zip)
[Savegame.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3293266/Savegame.zip)

**Comment by jbytheway** [comment]
Fixed in #31469.

**Comment by Eliijahh** [comment]
Confirmed, it works now thank you!
