### ISSUE TITLE
error to open saved game

### ISSUE THREAD

**Issue by yaunut** [CleverRaven/Cataclysm-DDA#31480]
I can not open the saved game when you press the spacebar opens crash log file
![2](https://user-images.githubusercontent.com/51860240/59554496-69948a00-8fac-11e9-934a-0975945882b2.png)
![1](https://user-images.githubusercontent.com/51860240/59554498-69948a00-8fac-11e9-8767-c9f4b4b784df.png)
saved character in the archive
[Саба.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3293378/default.zip)

**Comment by ZhilkinSerg** [comment]
It would be resolved in 9162.
