### ISSUE TITLE
Crash when exiting game on 9162

### ISSUE THREAD

**Issue by Zaragata** [CleverRaven/Cataclysm-DDA#31497]
# Describe the bug

It gives a seg-fault when closing the program. Only once it didn't.

# Steps To Reproduce

Exit the game.

# Versions and configuration

- OS: Windows 10 LTSC - 1809
    - OS Version: 10.0 1809
- Game Version: 0.D-4484-gbcc75f4 [64-bit]
- Graphics Version: Tiles
- Mods loaded: 
    - Dark Days Ahead [dda]

# Crash Message

CRASH LOG FILE: config/crash.log
VERSION: 0.D-4484-gbcc75f4
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x58A055[cataclysm-tiles.exe+0x18A055]
    @0x58AB22[cataclysm-tiles.exe+0x18AB22]
    SMPEG_error+0x4B034@0xECE5C0[cataclysm-tiles.exe+0xACE5C0]
    _C_specific_handler+0x98@0x7FFFDA898068[msvcrt.dll+0x28068]
    _chkstk+0x11F@0x7FFFDB00477F[ntdll.dll+0xA477F]
    RtlWalkFrameChain+0x14BF@0x7FFFDAF64BEF[ntdll.dll+0x4BEF]
    KiUserExceptionDispatcher+0x2E@0x7FFFDB0034EE[ntdll.dll+0xA34EE]
    SDL_LogCritical+0x12FD6@0xEEEE96[cataclysm-tiles.exe+0xAEEE96]
    initterm_e+0x1BB@0x7FFFDA8AA8CB[msvcrt.dll+0x3A8CB]
    @0x87E4D3[cataclysm-tiles.exe+0x47E4D3]
    IMG_LoadWEBP_RW+0x542BEB@0x150301B[cataclysm-tiles.exe+0x110301B]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFFD8727974[KERNEL32.DLL+0x17974]
    RtlUserThreadStart+0x21@0x7FFFDAFCA271[ntdll.dll+0x6A271]

**Comment by ZhilkinSerg** [comment]
Does it happen on a specific world?

**Comment by Zaragata** [comment]
Not really, just opening and closing (without loading any world) gives the crash. I'll test it with the 9166 release now.

Okay, I'm dumb. After several tests, seems like it only happens when [CO.AG](https://discourse.cataclysmdda.org/t/soundpack-co-ag-soundpack-v1-1-02-mar-19-only-the-music-alternative-addon/18992) soundpack is loaded AND using Nvidia GPU.

**Comment by ZhilkinSerg** [comment]
Won't reproduce for me now on stable 0.D, build 9162 or current master. Probably some environmental issue or maybe something wrong was with soundpack at the moment you experienced the issue.

Please ping me if you still have this issue.
