### ISSUE TITLE
Crash when firing

### ISSUE THREAD

**Issue by Leosky** [CleverRaven/Cataclysm-DDA#31499]
# Describe the bug
Crash quite often when firing a gun.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-4484-gbcc75f4 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Medieval and Historic Content [Medieval_Stuff],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Xotto [DP_XOTTO_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food]
]

# Additional context
CRASH LOG FILE: config/crash.log
VERSION: 0.D-4484-gbcc75f4
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x58A055[cataclysm-tiles.exe+0x18A055]
    @0x58AB22[cataclysm-tiles.exe+0x18AB22]
    SMPEG_error+0x4B034@0xECE5C0[cataclysm-tiles.exe+0xACE5C0]
    _C_specific_handler+0x98@0x7FFA47708048[msvcrt.dll+0x28048]
    _chkstk+0x11F@0x7FFA494C119F[ntdll.dll+0xA119F]
    RtlRaiseException+0x399@0x7FFA4948A229[ntdll.dll+0x6A229]
    KiUserExceptionDispatcher+0x2E@0x7FFA494BFE0E[ntdll.dll+0x9FE0E]
    @0x49E268[cataclysm-tiles.exe+0x9E268]
    @0x6CA702[cataclysm-tiles.exe+0x2CA702]
    @0x6A8A2A[cataclysm-tiles.exe+0x2A8A2A]
    IMG_LoadWEBP_RW+0x541BF8@0x1502028[cataclysm-tiles.exe+0x1102028]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFA491D7BD4[KERNEL32.DLL+0x17BD4]
    RtlUserThreadStart+0x21@0x7FFA4948CE71[ntdll.dll+0x6CE71]

**Comment by Leosky** [comment]
In fact, it happen when i press f and there is no ammo in the mag

**Comment by DeltaKris** [comment]
> In fact, it happen when i press f and there is no ammo in the mag

I'll fix it, I'm sorry for that.

**Comment by ymber** [comment]
Essentially the same bug as addressed in #31465. I'll make sure that ammo check is safe in all cases.
