### ISSUE TITLE
JSONize cbm power generation.

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#31495]
**Is your feature request related to a problem? Please describe.**  
Discussion on Discord prompt me to open this, it would probably make many mod makers lives easier (and also newbies to coding since JSON is easier to understand).

**Describe the solution you'd like**  
JSONize CBM power generation.

**Describe alternatives you've considered**  
...not doing it? that sounds bad tough.

**Comment by Lorith** [comment]
Examples of things that would be handy for modders:
Consume item X for Y fuel (list of items and fuel value)
Maximum fuel of X
Convert X fuel to power per tick
X turns per tick
Efficiency multiplier
Flag for infinite fuel, flag for movement as fuel, flag for metabolic processes as fuel

I'm sure there is a ton I've missed, but that is just off the top of my head.

**Comment by Zireael07** [comment]
I believe this is still a valid issue?

**Comment by Fris0uman** [comment]
I think this one is resolved now.
