### ISSUE TITLE
Giant Cellar spiders and zombies do not fight each other

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#31500]
# Describe the bug

Giant cellar spiders and zombies ignore each other.

# Steps To Reproduce

1. Find a basement with giant spiders.
2. Have the giant spiders morph through the ground up the Z level due to z-levels being kinda broken. Watch as the spiders run you down and bite you till you are slow and the zombies come to finish you off and none of them ever attacking each other.
3. Cry.

# Expected behavior

I want to see monsters fight each other!

# Versions and configuration

 - OS: Windows 10
 - Game Version: 9162
 - Graphics version: Tiles
 - Mods loaded: 
![image](https://user-images.githubusercontent.com/47362783/59557807-520bd000-8fb1-11e9-9c78-ceccd7e35264.png)

![image](https://user-images.githubusercontent.com/47362783/59557808-5a640b00-8fb1-11e9-85db-1bd2ea68a308.png)

**Comment by ifreund** [comment]
This is intentional.  See #15372
