### ISSUE TITLE
Can't adjust starting NPCs spawn in world creation menu if Static NPCs option is false on global settings

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#31505]
# Describe the bug

The option to adjust starting NPCs spawn (default is scenario-based) is always grayed out in world creation menu. Attempting to change it produces "Prerequisite for this option not met! (static NPCs)", regardless of whether or not static NPCs are actually turned on.

edit: This only happens if "Static NPCs" are turned off in Settings - Options - World Defaults. Otherwise it works fine. Still, options in world creation should override global defaults, so this is a bug.

# Steps To Reproduce

edit: 0. Go to Settings - Options - World Defaults and set "Static NPCs" to false.
1. Enter world creation menu.
2. Set "Static NPCs" to true in world options.
3. Try to change "Starting NPCs spawn".

# Expected behavior

Should be possible to turn starting NPCs to "never" and "always", like the description suggests.

edit: global static NPC option shouldn't affect this because it's overriden by world creation.

![bug](https://user-images.githubusercontent.com/44502845/59558501-bb292d00-901d-11e9-9c4b-90ce1f9c84e1.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-4496-gff714b2
 - Graphics version: Tiles
 - Mods loaded: none

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.D-4496. Gif is showing wrong colors for some reason, but I think it's still representative.
![123](https://user-images.githubusercontent.com/11132525/59559312-3d612380-9015-11e9-8ff5-9f2840937fa5.gif)

**Comment by Amoebka** [comment]
I think I've figured it out. If "Static NPCs" are turned on in Settings - Options - World Defaults, then you can adjust the "Starting NPCs Spawn" option both there and in world creation. If "Static NPCs" are turned off in global settings but enabled in world creation, then you can't adjust the setting. Still a bug.
