### ISSUE TITLE
Insane amount of monsters.

### ISSUE THREAD

**Issue by DeltaKris** [CleverRaven/Cataclysm-DDA#31508]
# Describe the bug

I was testing the modular base, and triffids spawned around my base with an impossible amount to win,

# Steps To Reproduce

I really don't know how this happened, I was just giving orders for my companions to build my base.

# Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/45604592/59559212-bdb56380-8fd8-11e9-92df-5e8f64b592b7.png)

# Versions and configuration

- OS: [Windows 10]
 - Game Version: [0.D-4484-gbcc75f4]
 - Graphics version: [Tiles]
 - Mods loaded: ["dda",
  "no_npc_food",
  "aftershock",
  "craftgp",
  "crt_expansion",
  "magiclysm",
  "adv_gear",
  "ArmUpPAUtil",
  "ArmUpSurvEx",
  "Tolerate_This",
  "Bootleg_Walkers",
  "FIC_Weapons",
  "growable-pots",
  "realguns",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "DinoMod",
  "DracoDogMod",
  "modular_turrets",
  "PK_REBALANCE",
  "Salvaged_Robots",
  "alt_map_key",
  "Cata++",
  "fast_healing",
  "hydroponics",
  "mutant_npcs",
  "MMA",
  "vamp_stuff",
  "Arcana",
  "vamp_stuff+arcana",
  "zets_hair_extensions",
  "more_locations",
  "zets_hair_ext_more_locations",
  "zets_hair_ext_pk_rebalance",
  "national_guard_camp",
  "P_Caches",
  "Dorf_Life",
  "FujiStruct",
  "Urban_Development",
  "deoxymod",
  "blazemod",
  "Tanks",
  "necromancy",
  "DP_REMIX_INDICATORS",
  "sees_player",
  "Arts' Guns",
  "duros_doings",
  "jury_rigged_robots",
  "TATTOOMOD",
  "winning_dda",
  "Ex_Scenarios",
  "ZSFIXED_cddaxp",
  "RL_Classes",
  "more_classes_scenarios",
  "disable_bots",
  "disable_bots_natcamp"]

**Comment by Night-Pryanik** [comment]
It seems from the screenshot that you're using third-party mods, maybe that's the culprit. Please don't neglect the issue template, and fill the info on game version, used mods and so on.

**Comment by DeltaKris** [comment]
> It seems from the screenshot that you're using third-party mods, maybe that's the culprit. Please don't neglect the issue template, and fill the info on game version, used mods and so on.

I'll fix it, I'm sorry for that.

**Comment by FulcrumA** [comment]
IIRC big/difficult spawns were one of intentional design decisions behind PK Rebalance. I am not surprised if it gets even exacerbated by some other mods that affect the balance, especially when basic, underlying vanilla spawns are adjusted - and there were some changed to that in the past. May be indeed a case of "you didn't know you've signed up for this yourself, but you did sign up".
