### ISSUE TITLE
The hub01 boss guy (I think that's him?) can spawn as a starting NPC

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#31507]
# Describe the bug

Just had a starting evac shelter NPC who had most skills above 6, a rivtech gun with 1000 (!!!) ammo, RM13 combat armor with spare plutonium and some random grenades. I believe that's the guy who is supposed to be the boss of hub01 faction or something (haven't played with this stuff yet), and he shouldn't spawn as a random starting NPC. Even if he isn't, these kinds of loadouts shouldn't be allowed (too easy for the player to get all that day 1).

This isn't much of an issue in itself, but it might be an indication that predefined static NPCs are legible to spawn as starting ones, which shouldn't be a thing.

# Steps To Reproduce

No real way, sadly. Keep rerolling random evac starts until you get a static NPC like him again?

# Expected behavior

Static predefined NPCs shouldn't be spawned as starting ones.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-4496-gff714b2
 - Graphics version: Tiles
 - Mods loaded: none

# Additional context

I initially didn't really care about this so I didn't take a screenshot and didn't keep the save. I guess I can't prove this bug exists given how random it is, but why would I possible lie about bugs?

**Comment by faefux** [comment]
I think he needs a '"common": false,' tag, maybe.
