### ISSUE TITLE
Map memory no longer works for indoor buildings

### ISSUE THREAD

**Issue by Zetsukaze** [CleverRaven/Cataclysm-DDA#31514]
# Describe the bug

Map memory used to show indoor contents if explored, now they do not. Is this an intended change in the new builds?

# Steps To Reproduce

Explore a building/structure with walls then move till it is not within your visible range.

# Expected behavior

To be able to remember what was within a structure and see the walls of the room.

# Screenshots

![image](https://user-images.githubusercontent.com/1698993/59560623-d7da5a80-9047-11e9-92d5-274e3e531419.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-4484-gbcc75f4 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Advanced Gear [adv_gear],
    BioCo Content [bioco],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Extended Realistic Guns [realguns],
    Craft Ammo Mags - ERG [SD_Magcrafting_Realguns_Extension],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Fungus Fighter Kit [antifunguskit],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Shard's Additions [shardstuff],
    Modular Turrets [modular_turrets],
    PKs Rebalancing [PK_REBALANCE],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    NPC traits [npc_traits],
    Zetsukaze's Hair - 0.D EDIT [zets_hair_extensions],
    More Locations [more_locations],
    Zet's Hair - More Locations [zets_hair_ext_more_locations],
    Zet's Hair - PKs Rebalancing [zets_hair_ext_pk_rebalance],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Arcana and Magic Items [Arcana],
    Necromancy [necromancy],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    No Filthy Clothing [no_filthy_clothing],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    Tame Bugs [tamebugs],
    Zetsukaze's CDDA Tweaks! [zets_tweaks]
]

**Comment by Zetsukaze** [comment]
Actually, map memory seems to not work at all, now that I've noticed it.

**Comment by Zetsukaze** [comment]
User error, sorry =(

**Comment by esotericist** [comment]
For the sake of future possible people looking for help with this problem, am I right to guess the problem was accidentally toggling map memory with `(` ?

**Comment by Zetsukaze** [comment]
Yes, but my key is `{`. PEBCAK lol

**Comment by esotericist** [comment]
Ah, my mistake. I couldn't remember which key it was offhand. Either way, if you discover a report you submitted was due to an issue on your end, it's a good idea to let everyone know what it turned out to be. :)

Either way, I'm glad you figured it out!
