### ISSUE TITLE
Should dim areas be dim and memory black and white?

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#31525]
I found it weird how dim areas are black and white and memory has dim light and color.
Even more wierd when you walk thru black and white field and area behind you color it self as you go.

Maybe it can be switched up? Lighten up areas are normal, dim areas are dim and memory is black and white. I think it will look more "natural" in the game.

**Comment by esotericist** [comment]
I believe dim areas are black and white to model the loss of color information in human low-light vision.

In Curses mode, memory shows as brown (presumably to mimic sepia) which might be more informative, but right now the tiles renderer isn't set up to apply color filters other than than "black & white" or "darker".

**Comment by Night-Pryanik** [comment]
> other than than "black & white" or "darker".

Is it?
![изображение](https://user-images.githubusercontent.com/11132525/59567087-fd805780-9079-11e9-9bf8-ee0f2b50af4b.png)

**Comment by esotericist** [comment]
... huh. I've never actually obtained or debug-tested those tools. Fun times.

I'll add 'sepia tinting' to the list of things to maybe investigate later, then.

**Comment by nexusmrsep** [comment]
I support this idea. Black and white night runs switching to dim but color memory is odd and non intuitive.
