### ISSUE TITLE
Atomic reading light isn't bright enough for reading

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#31528]
Despite being called a "atomic reading light", it is apparently too dim for use when reading. It will effectively increase reading time by 2-3 times due to inadequate light intensity, unlike conventional electric reading lights. Which sounds like a bug. (Unless it's supposed to be a defective product, in which case the description should be modified to reflect this).

**Comment by TechyBen** [comment]
IIRC the voltage/wattage/amps from a small nuclear battery (tritium battery using voltaics) are very low.
So there are 3 choices.
1) Change the description and keep it as is, providing a tiny amount of useable light, matching reality of a tiny device, but with near constant output (tritium glow in the dark keychains exist).
2) Give it the ability to store a small charge, that can be used for useable light. It would drain in use, and need time to recharge (though I've not done the math on that real life charge times).
3) Just boost it for gameplay/function and not worry too much about the physics. "Nanoparticles". ;)

Any is fine. I like the idea of a self charging torch, but lore suggests it's a glow in the dark tritium keyring currently.

**Comment by Rivet-the-Zombie** [comment]
Unless something has changed it should provide sufficient light for comfortable reading while it's active and  in your inventory.

**Comment by matthemsteger** [comment]
The night light was renamed to reading light in #30795 which I think is adding to confusion since the night light was too dim to read at 100% prior and continues to be.

**Comment by nexusmrsep** [comment]
Pinging @I-am-Erk regarding the above comment.

**Comment by logros13** [comment]
Reading is also slow with the normal non atomic reading light so that to needs to be fixed if the name is kept. 
![reading light](https://user-images.githubusercontent.com/20383070/59705666-2120da80-91ff-11e9-849c-00790acecffc.png)
active light and (partially visible) low light message ^

**Comment by Regularitee** [comment]
In my experience the normal reading light works fine. It's only when it's at **low batteries** does it fail to provide sufficient light to read with.

**Comment by I-am-Erk** [comment]
I would say based on my reading around betavoltaic cells, the nightlight is probably not putting out enough light then. It should be around 1/3 to 1/2 a watt, which for an LED would be about 50 lumens, which should be almost exactly enough to read a book. 

> How well an area is lit can be measured with the unit lux calculated by dividing the number of lumens by the lighted area in meters squared. Direct sunlight is about 100,000 Lux, Daylight is 10,000 Lux, Overcast day or office lighting 1000 Lux, Dusk is about 100 Lux and the Minimum light needed for night time visibility is 3 Lux. So with 50 lumens you could light an area about the size of a sheet of paper with the same light level of a cloudy day. https://www.quora.com/How-bright-is-50-lumens

Light amounts are currently hard coded, I'm not sure how to adjust this upward.

**Comment by TechyBen** [comment]
Sorry. IIRC it's "He gets 1.23 **microwatts**" for a homemade version, and about the same for industrial/manufactured ones.
"but it is in fact more than the output of commercial units at 0.84 microwatts" (The industrial ones fit on a PCB so are smaller, as far as I can tell).

https://hackaday.com/2016/12/01/make-your-own-nuclear-battery/

I'm happy to see other stats, or as said, say that it's lore/sci-fi equipment. Just checking that there is not a decimal point error. :)

**Comment by I-am-Erk** [comment]
The versions you're discussing are tiny. The battery in the reading light is roughly 10-100 times heavier by weight.

**Comment by mefimim** [comment]
![Gaseous_tritium_light_source](https://user-images.githubusercontent.com/52053570/59884085-8d314900-938d-11e9-924b-370831b091b8.jpg)

This is what Atomic Nightlight/Reading Light was supposed to repesent (picture courrtesy of Wikipedia, 'Radioluminescence'). It gives off enough light to read while straining your eyes - barely. Keep in mind the picture attached has a secondary, ambient light source.

**Comment by nexusmrsep** [comment]
I guess it would be possible to put like 5 of those in a row to amplify the light output.

**Comment by I-am-Erk** [comment]
The current incarnation of the  light is much larger than that, yeah.

**Comment by Rivet-the-Zombie** [comment]
>This is what Atomic Nightlight/Reading Light was supposed to repesent

It was supposed to be a standard nightlight, just with virtually infinite power back when I originally added it to the game. It wasn't even a reading light in the first place.
