### ISSUE TITLE
Pit firing clay is now possible, but it still requires a kiln

### ISSUE THREAD

**Issue by FuelType-Memes** [CleverRaven/Cataclysm-DDA#31527]
# Describe the bug

PR #31304 made pottery craftable in normal fire, but somehow you still need a kiln

If I'm reading it correctly:
```
{
    "id": "earthenware_firing",
    "type": "requirement",
    "//": "Firing various clay shapes to make earthenware",
    "tools": [ [ [ "brick_kiln", -1 ], [ "kiln", -1 ] ], [ [ "fire", -1 ], [ "brick_kiln", 1 ], [ "kiln", 1 ] ] ]
},
```

Which leads to you needing a kiln nearby to pit fire clay

# Steps To Reproduce

1. Make a player with a fabrication 10, a jug of water and 10 lumps of clay
2. Try to craft a teapot near a lit campfire
3. There's no way to craft it, because you also need a kiln

# Expected behavior

You can make earthenware without a kiln

# Additional context

Can't fix, because computer is borked

Suggested fix:
```
{
    "id": "earthenware_firing",
    "type": "requirement",
    "//": "Firing various clay shapes to make earthenware",
    "tools": [ [ [ "fire", -1 ], [ "brick_kiln", 1 ], [ "kiln", 1 ] ] ]
},
```

**Comment by Rail-Runner** [comment]
Well, I changed this fairly recently, my intention was to allow using less expensive fuel than charcoal to fire those things. Didn't know you could do it wihout having a kiln at all.

**Comment by FuelType-Memes** [comment]
> 
> 
> Well, I changed this fairly recently, my intention was to allow using less expensive fuel than charcoal to fire those things. Didn't know you could do it wihout having a kiln at all.

You won't get anything that [pretty](https://www.youtube.com/watch?v=GX_ZU7yuvzw), but you certainly can

And it doesn't need to be a pit [either](https://www.youtube.com/watch?v=kgbZeCZ7mC8)

Even cooler, you can boil water in wet clay, as [demonstrated here](https://youtu.be/_EzGfug8A2s?t=984) by awesome Tom McElroy
