### ISSUE TITLE
Refugee center can spawn gasoline zombies

### ISSUE THREAD

**Issue by 81Denton** [CleverRaven/Cataclysm-DDA#31521]
# Describe the bug

When the refugee center gets generated, gasoline zombies can spawn among the zombies in the back room.
Killing them can cause fire, which will cause the whole refugee center to go up in flames, killing multiple unique quest givers. Not killing the gasoline zombie prevents quest completion.

# Expected behavior

Gasoline zombies should be excluded from the list of zombies that spawn in the back room, as there is no reasonable way to either prevent their ignition or to put out the flames after killing them.

# Screenshots
https://user-images.githubusercontent.com/32391752/59562936-b0799280-9033-11e9-85d0-6d381c4c5ceb.png

# Versions and configuration

 - OS: Win 10 Pro x64
 - Game Version: 0.D-4039-g02eaddf (tiles)
 - Mods loaded: dda, no_fungi, no_npc_food, safeautodoc

**Comment by ZhilkinSerg** [comment]
You can bring a lot of water with you and [U]nload it to tiles with fire ;)

**Comment by 81Denton** [comment]
Nice, I didn't know that.

**Comment by ZhilkinSerg** [comment]
Not that it is wise to bring a bucket of water instead of machete to a room full of zombies...

**Comment by l29ah** [comment]
AFAIR it doesn't ignite if you kill it with a bow from afar.

**Comment by FulcrumA** [comment]
Either way probably limits on types of zombies allowed to spawn in the back room would help prevent many annoying, somewhat unfair situations.

**Comment by 81Denton** [comment]
Yeah, by the time you get to the back room it will most likely have leaked enough gasoline to ignite into a 4x4 (or larger fire), something you can't take care of with a fire extinguisher at least.

**Comment by kevingranade** [comment]
Special handling to prevent certain zombie types from spawning in the back room is not something we're interested in considering but we can rearrange the scenario to make this a bit less of a trap.
For example there could be more obvious external entrance the player could use to get at the zombies. There could be some dialogue indicating that entering from outside the building is an option.
Anothersimacrulum is also looking into making brick walls less flammable so that the fire would be contained.

**Comment by 81Denton** [comment]
I mean, that's also a way to reduce the amount of open issues.

**Comment by kevingranade** [comment]
This was addressed by #32143 The refugee center shouldn't burn down if this happens.

**Comment by 81Denton** [comment]
I didn't know that, thank you for the info!

**Comment by ZhilkinSerg** [comment]
> I mean, that's also a way to reduce the amount of open issues.

The thing is anyone can take any closed issue and start working on it, but there is a good chance if issue was not taken care of while it was opened, it won't be worked on anyway.
