### ISSUE TITLE
Mining duration is off after the 1 sec per turn conversion

### ISSUE THREAD

**Issue by FuelType-Memes** [CleverRaven/Cataclysm-DDA#31526]
# Describe the bug

Mining activity takes several days to finish

From iuse::pickaxe :
```
int moves = to_moves<int>( 20_minutes );
...
moves *= ( ( MAX_STAT + 4 ) - std::min( p->str_cur, MAX_STAT ) ) * to_seconds<int>( 5_minutes );
```

Given it's 100 moves per turn and 1 turn per sec, that leads to 20min becoming 12 000mov

Which leads to following math: 
12 000 mov * 5 (11 max_str - 10 cur_str) * 300 sec = 18 000 000 mov = 180 000 turns = 180 000 sec = 3000 min = 50 hrs

But before the conversion that would be
2 000 mov * 5 * 300 = 3 000 000 mov = 300 000 turn = 300 000 sec = 500 min = 8.3 hrs

# Steps To Reproduce

1. Make a player with a pickaxe
2. Try to dig through a rock
3. Die from dehydration/sleep deprivation/starvation/boredom

# Expected behavior

Mining taking reasonable time

# Additional context

Using a jackhammer works fine, because it's just flat
```
int turns = 100;
...
turns *= MINUTES( 30 );
```

**Comment by anothersimulacrum** [comment]
Fixed in #31741, but not closed
