### ISSUE TITLE
Lighting is broken (Brightness at night time)

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#31524]
# Describe the bug

See the picture but pretty much it's night time and very dark but it does not look like it and I can see farther. If it helps I just had an encounter with a Wraith and recently put on sunglasses. The tile I am on is very dark tho so I cannot read or anything. I had something similar happen before but it would not follow me around and it would only keep the insides of places bright.

# Steps To Reproduce

1. Find a house on a Green F map tile that is boarded up.
2. Break in.
3. Get attacked by shadows and a thing called a Wraith.
4. Set fire to the house.
5. Run away while being chased by shadows, it became night time while I was running away and my vision is still there.

# Expected behavior

To not be able to see in the dark? Maybe the Wrath did something to me (does not appear in character screen if it did).

# Screenshots

**If applicable**, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/47362783/59564187-c4ac9800-9011-11e9-8931-f30808ea1d6a.png)

![image](https://user-images.githubusercontent.com/47362783/59564220-0fc6ab00-9012-11e9-80f6-9160ef4b9a68.png)

![image](https://user-images.githubusercontent.com/47362783/59564252-721fab80-9012-11e9-907a-400eba53a6a5.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 9166
 - Graphics version: Tiles
 - Mods loaded: Core: Catacylsm DDA and then these mods:
![image](https://user-images.githubusercontent.com/47362783/59564209-f160af80-9011-11e9-9104-dadc01f310bd.png)

**Comment by chphilli** [comment]
Related to #31905 ?

**Comment by aragonasx** [comment]
Same thing happened to me too. But I was just fighting them head on for a while then ran away. And it's dark like that too.

**Comment by aragonasx** [comment]
![image](https://user-images.githubusercontent.com/33196916/65997985-1c78ed00-e4a3-11e9-804d-d255fe7bf1ba.png)
Can't see to craft
