### ISSUE TITLE
Game crashes when Beagle Mini-Tank UGV tries to shoot its rifle

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#31530]
# Describe the bug

Game crashes when Beagle Mini-Tank UGV tries to shoot its rifle.

# Steps To Reproduce

1. Start a new game without mods.
2. Debug spawn a monster with `rifle` special attack (e.g. Beagle Mini-Tank UGV)
3. Try to run away from monster, so it will try to shoot you 

# Screenshots

![image](https://user-images.githubusercontent.com/16213433/59568763-c6b13e00-9087-11e9-8c54-8fb960161d4d.png)

# Expected behavior

Game doesn't crash.

# Additional context

I believe the issue appears because certain monsters have their `starting_ammo` set to value which exceeds maximum capacity of any magazine usable in gun `m4a1` (which is used by `rifle` special attack).

Issue would probably affect any other monster using `rifle` special attack and having too high amount of starting ammo.

**Comment by Regularitee** [comment]
That's strange. I was the one that made that change [about ten months ago](https://github.com/CleverRaven/Cataclysm-DDA/pull/25712). So I don't think it's as simple as having too much ammo, otherwise surely someone else would have noticed or reported it by now. Unless there were recent engine changes in my absence, I suspect ammo count alone couldn't possibly be the cause of a CTD.

**Comment by Zombiemanpig** [comment]
Weird last night I died 2 times in a row on (even after resetting world) to them and my game did not crash either time.  don't remember which version but was one of the last 6 and on windows 10.

**Comment by Noodleboom** [comment]
I've been getting consistent CTDs when hostile turrets try to fire their weapons, which looks like it might be the same issue. They don't have the rifle special attack, but their special attack type is "gun." Crash log attached.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3295582/crash.log)

**Comment by nexusmrsep** [comment]
Maybe it's related to recent muti-ammo support?

**Comment by romkuma** [comment]
I have a savegame with a reproducible crash which may be related.
[CrashingSave.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3301305/CrashingSave.zip)
Moving south along the road will consistently produce a segmentation fault. I'm not sure how to interpret the crash.log file but it includes references to gun_actor which I interpret as being related to turrets or other monsters which fire guns.

If unrelated, let me know and I'll move this to its own issue.
