### ISSUE TITLE
Cattle Fodder Lists Too Much Internal Furnace Energy

### ISSUE THREAD

**Issue by Voideka** [CleverRaven/Cataclysm-DDA#31548]
![fodder power](https://user-images.githubusercontent.com/2141044/59582410-2e768180-90a6-11e9-9b61-70812c18f0de.png)
# Describe the bug

With my Internal Furnace active, the Consume Item screen lists 13+ Cattle Fodder as providing +4001 energy. All amounts tested over 13 show +4001. 12 Cattle Fodder shows +401 energy.

# Steps To Reproduce

1. Make a Bionic Prepper character with the Internal Furnace CBM
2. Get 13 or more Cattle Fodder
3. Activate the Internal Furnace
4. Open up the Consume Item screen, and scroll to Cattle Fodder, it will show +4001

# Expected behavior

1 Cattle Fodder is listed as giving +33 energy, so 13 Cattle Fodder should give around +426

# Screenshots

Screenshot attached

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4532-g35c6114 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Vehicle Additions Pack [blazemod],
    Boats [boats]
]

# Additional context
Save originally started on stable D release.

**Comment by DemAvalon** [comment]
I thought internal furnace was removed from the game?

**Comment by Voideka** [comment]
If it was, that would explain the issue.

**Comment by DSeyka** [comment]
It's supposed to be [removed](https://github.com/CleverRaven/Cataclysm-DDA/pull/30228) from the base game, but [still available](https://github.com/CleverRaven/Cataclysm-DDA/pull/30409) in Aftershock.
