### ISSUE TITLE
Sawing through metal bars takes seconds

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#31542]
# Describe the bug

Selecting cut metal from the toolbox and then selecting metal bars (on a gun shop) took my character 7 seconds to fully cut through.  Doing it again, on the interior bars, took 8 seconds.  There were none of the intermediate 'you're cutting the metal bars and its taking forever' messages.

# Steps To Reproduce

Spawn yourself a toolbox and head to the nearest gun store.

# Expected behavior

Previously, metal sawing took a long time and produced multiple messages about the sound as you slowly worked through the bars.  I assume this is connected to the recent turn-time changes, but I don't know that for sure.

# Screenshots
Before - note the time
<img width="647" alt="before1" src="https://user-images.githubusercontent.com/41651793/59572193-716e3000-9079-11e9-82d4-272dafba7aa3.png">
After - 7 seconds and 1 message later
<img width="626" alt="after1" src="https://user-images.githubusercontent.com/41651793/59572199-79c66b00-9079-11e9-90cb-b5697ec82c5b.png">

Before
<img width="654" alt="before2" src="https://user-images.githubusercontent.com/41651793/59572194-716e3000-9079-11e9-861d-758995942d28.png">
After
<img width="676" alt="after2" src="https://user-images.githubusercontent.com/41651793/59572200-79c66b00-9079-11e9-960d-1899a25e6cde.png">

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4522-g4d34142 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Bens GF recipes [Tolerate_This],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Caches [P_Caches],
    Folding Parts pack [deoxymod],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I didn't test any other saw items or any other locations.  It's possible this is a bug with the toolbox, specifically, but it struck me as probably connected to the turn time change.

**Comment by Regularitee** [comment]
I've noticed a similar issue with other types of metal working, such as welding: You can created a steel jerry can from metal sheets almost instantaneously. Not sure if it's related, or it's just coincidentally a bug with the same effect also affect other metalworking jobs.

**Comment by Rivet-the-Zombie** [comment]
Semi-related - I've noticed that cooked meat scraps are also instantaneous to produce.
