### ISSUE TITLE
bathtub causeing game to freeze/crash 

### ISSUE THREAD

**Issue by sammy202020** [CleverRaven/Cataclysm-DDA#31541]
# bathtubs cause the game to freeze/crash  if there is an item inside when you try and pick it up 

# Steps To Reproduce

Steps to reproduce:
1.  walk into a room with a bathtub with items already inside it 
2. go and pick up said items
3. watch as the game freezes then crashes 

# Expected behavior

the game freezes up and crashes. i think this is caused by the change made to bathtubs to allow them to hold liquids. 

# Versions and configuration
 - OS:  Windows 10 
 - Game Version: 0.D-4522-g4d34142 
 - Graphics version: Tiles
 - Mods loaded:  StatsThroughSkills, no fungus monsters

**Comment by nexusmrsep** [comment]
Also reported in #31554
Culprit: #31438
Bug reason: keg examine function is designed to handle only furniture with NOITEM flag, causing unhandled exceptions with non-liquid items in bathtub.
Possible fix: reverting the PR and introducing an exception to liquid pickup similar to toilet tanks. Alternatively making keg examine functions able to handle non-liquid items present at target furniture.
