### ISSUE TITLE
Allow opening construction menu in dark

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#31555]
**Is your feature request related to a problem? Please describe.**  
Constructions aren't allowed now in dark and that is fine. But the menu should still open and only say it's too dark to construct when I actually select a construction the same way as it is with crafting. It's not only for consistency but right now, my character woke up early in the morning I want to start some construction as soon as it's bright enough, but can't check what materials I need because the menu won't even open. 

**Describe the solution you'd like**  
Same as crafting, just open the menu and say it's too dark once I select the construction. 

**Describe alternatives you've considered**  
None, really. 

**Additional context**  
Some construction could actually be marked as possible in dark. "Mark Firewood Source"?

**Comment by ZhilkinSerg** [comment]
I would argue that firewood source should be moved to zones instead.

**Comment by tinukedaya** [comment]
Agreed. probably all the marks (target, firewood, crafting) would better suit the zones. 

We should still be able to open the menu though, even if none of the constructions would be possible.
