### ISSUE TITLE
Bug with examining bathtub (#9169)

### ISSUE THREAD

**Issue by Joanakor** [CleverRaven/Cataclysm-DDA#31554]
# Describe the bug

When trying examing bathtub that contains item - game crashes

# Steps To Reproduce
1. Find bathtub in any house
2. Make sure there lays an item 
3. Press e and examine it

# Expected behavior
Examining bathtub without crashes
# Screenshots

# Versions and configuration

 - OS: Windows 8.1
 - Game Version: 0.D-4535-g070c348
 - Graphics version: Tiles
 - Mods loaded: 
![Screenshot_7](https://user-images.githubusercontent.com/30211338/59599419-27339000-9107-11e9-81ba-9d5f8160cede.png)

**Comment by nexusmrsep** [comment]
Introduced in #31438
Keg examine function is not compatible with furniture that can hold items other than liquid, causing unhandled behavior.

**Comment by Night-Pryanik** [comment]
Closing as duplicate.
