### ISSUE TITLE
Crash when adding Jade Brooch to trade offer

### ISSUE THREAD

**Issue by CorvetBlyat** [CleverRaven/Cataclysm-DDA#31559]
# Describe the bug

When adding the Jade Brooch item to the trade offer the game crashes. Things to note are that the ones i used were filthy, and i was trading with the free traders merchant.

# Steps To Reproduce

1. Load save or get to free traders merchant and spawn Jade Brooch
2. Open the trade window with the merchant
3. Try to add Jade Brooch to the offer
4.Crash

# Expected behavior

Ideally also describe *why* you expect it to happen.

Adding the Jade Brooch to the offer increasing the worth of my offer accordingly.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

Not deemed needed

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4578-gf477339 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]

# Additional context

[Matoaka.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3298123/Matoaka.zip)
[crash + debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3298124/crash.%2B.debug.zip)

**Comment by Night-Pryanik** [comment]
Tested right now on latest experimental as of June 19, 2019. I was able to successfully trade both clean and filthy jade brooches.

**Comment by CorvetBlyat** [comment]
Tested again on latest (Build 9184) , issue still persists, i've also tested it with the Arsonist NPC and i had the same outcome
[Debug + Crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3306972/Debug.%2B.Crash.zip)

**Comment by anothersimulacrum** [comment]
Could you add a savegame?

**Comment by Night-Pryanik** [comment]
@CorvetBlyat could you test it on latest experimental and on totally fresh world and with fresh character?

**Comment by CorvetBlyat** [comment]
@Night-Pryanik Have done so, works as intended, i'll remember to try that in the future.
