### ISSUE TITLE
Alcohol causes vomiting every time

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#31556]
# Steps To Reproduce

1. Load the saved game.
2. `E`at some alcohol beverage.
3. You will vomit in a few seconds.

# Expected behavior

Survivor having a stronger stomach.

# Versions and configuration

 - Game Version: 0.D-4532-g35c6114f4a-dirty
 - Mods loaded: alternative map key

# Additional context

[2019.06.14-4.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3297027/2019.06.14-4.zip)

**Comment by zacklucky7** [comment]
Does not appear to be all alcohol beverages but very sensitive. I drank weak mixed alcohol and didn't throw up immediately, but I did get to 'drunk' (the character in the save does not have Lightweight)

**Comment by EirenexTheDragon** [comment]
Can confirm that with drinking one gulp of Moonshine, causing the character to throw up soon after because they get really trashed just from using it once. its more noticeable on more heavier beverages while beer or fruit wine usually gets you to drunk instead of tipsy already.

**Comment by chaoticidealism** [comment]
Yup, can confirm! One beer gets my character immediately drunk; one drink of liquor gets my character immediately wasted and vomiting.
