### ISSUE TITLE
Bandages disappear after use

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#31569]
**Is your feature request related to a problem? Please describe.**  

1- Aplly bandage on wound
2- Wait
3- The wound heals
4- The bandage is gone!

**Describe the solution you'd like**  

That's probably not a problem for medical grade bandages as the gauze is probably not reusable.
But makeshift bandages are just rags, you would expect to get them back and be able to clean them, boil them and reuse them.

**Describe alternatives you've considered**  
Ignore that issue, but since we tend to go for conservation of mass instead of disappearing item it doesn't seem satisfying.

**Additional context**  

I tried to fix it myself a few month ago but bandages actually disappear immediatly on use and I did not manage to figure out how to know which kind was used when the wound is healed.

**Comment by tinukedaya** [comment]
Make bandage work somewhat similar to splint then? Basically a wearable, "close to skin". And convert it to dirty bandage with time.

**Comment by barsoosayque** [comment]
> Make bandage work somewhat similar to splint then?

Makes sense, because as per current version bandages might be ripped by enemies like any other clothes.

**Comment by RogueYun** [comment]
I love this idea... Here's my two cent rant.

Maybe have something like "Open Wound" where the max HP of a limb is reduced and it requires a bandage (like a splint) or stitches (sewing kit?) to heal? Open wounds increase chance to get infected? Just some thoughts. I tend to never use bandages unless I'm bleeding. I just sleep off the scratches. But if there were another gimmick that was required to get a limb back to full HP it might help make the game feel more immersive. Just some thoughts.

**Comment by Inglonias** [comment]
> Make bandage work somewhat similar to splint then? Basically a wearable, "close to skin". And convert it to dirty bandage with time.

I really like this. In addition to making the damaging of bandages work like the damaging of clothing, this also allows us to add encumbrance to them if we want. A tourniquet wrapped as tight as possible around your leg to keep your blood from falling out is not exactly an easy thing to walk on.
