### ISSUE TITLE
Will not create world

### ISSUE THREAD

**Issue by Misti3r** [CleverRaven/Cataclysm-DDA#31564]
# Describe the bug
I click finish world and it plops me back to the main menu without a world created.

# Steps To Reproduce

1. Try to create a world.
2. Customize it how ever you want, or don't edit it at all,
3. Finalize it.
4. Realize your at the main screen and there is no world created.

# Expected behavior
To let me create a world so I can play.

 - OS: Windows 7
 - Game Version: 0.D-4522-g4d34142
 - Graphics version: Tiles
 - Mods loaded: It doesn't matter if i put mods in world configuration or not it still won't work.

**Comment by ZhilkinSerg** [comment]
Works fine for me. Could be something in your environment. Where did you install Cataclysm? Do you have full access rights on that path?

**Comment by Misti3r** [comment]
Can you please reword that I'm not very good at english.

**Comment by Misti3r** [comment]
I downloaded it off of the offical website in middle of US.

**Comment by DemAvalon** [comment]
Zhilkin is asking were is your game installed (C:\Users\NAME\Desktop\GAMES\CDDA\Cataclysm-DDA)

and if you might be blocked from modifying the folder (not having administrator privileges)

Try running the game as administrator if you can.

**Comment by Misti3r** [comment]
oh;; Face palm... I'm so sleep deprived and stupid... so stupid. 
![image](https://user-images.githubusercontent.com/51927925/59647451-da6cab00-9140-11e9-9337-73e62ca1169e.png)
