### ISSUE TITLE
Bionic Soldier Profession with No Fictional Weapons Mod results in having no Rifle

### ISSUE THREAD

**Issue by RedPine91** [CleverRaven/Cataclysm-DDA#31577]
# Describe the bug

"No Fictional Weapons" mod removes the rifle that the "Bionic Soldier" profession starts with, causing the "Bionic Soldier" to start with no rifle at all.

# Expected behavior

Item removal mods replace removed items with similar allowed items, or at least warn the player that a mod has removed part of a profession's starting gear.

**Comment by Night-Pryanik** [comment]
Item removal mods are doing what are they expected to do - remove items. They ain't supposed to provide alternatives or replacements for weapons they remove.

**Comment by kevingranade** [comment]
We might be able to check for dependencies and remove a profession that has missing gear.

**Comment by eilaattwood** [comment]
I find it strange to discard fictional guns but to take fictional profession for the character that is intended to use fictional gun and abilities. So I agree with Kevin, professions that use blacklisted gear should be blacklisted too.

**Comment by Hatfish** [comment]
Would that mesh well with something like the generic guns mod?

**Comment by kevingranade** [comment]
Yes, it would blacklist every profession that starts with a gun.

**Comment by kevingranade** [comment]
When you load your world, do you get the error
profession Bionic Soldier: item rm51_assault_rifle does not exist"?
