### ISSUE TITLE
Bionic Sniper magazine inconsistency

### ISSUE THREAD

**Issue by chaohedgehogs** [CleverRaven/Cataclysm-DDA#31588]
# Describe the bug

The Bionic Sniper profession starts with an RM11B Scout Rifle loaded with an RMGP10 magazine, despite the chest rig containing 4 loaded RMGP25 magazines.

# Steps To Reproduce

1. Create Bionic Sniper character.
2. Unload rifle and chest rig to compare.

# Expected behavior

Consistency in magazine usage. The RM11B should start loaded with a 25 round magazine, or alternatively the 4 spare magazines in the chest rig could be replaced with 10 round magazines.

# Versions and configuration

Game Version: 0.D-4623-g09d2e75 (experimental build #9177)
 - Graphics version: Windows_x64 Tiles
 - Mods loaded: dda, disable npc needs

**Comment by Zombiemanpig** [comment]
I tried the start several times, I noticed this too but it never bothered me, I usually switch to a 25 clip turn 1.

110 v 125 bullets isn't too big of a difference, 110 v 50 would be a big nerf to the start I think.

**Comment by chaohedgehogs** [comment]
Agreed, but I included it as an alternative just in case someone wanted to revise magazine capacity for the gun.
