### ISSUE TITLE
Upgraded Faction Camps reset on notice board to level 1

### ISSUE THREAD

**Issue by M1nks** [CleverRaven/Cataclysm-DDA#31598]
A few weeks ago when I loaded my current game (The Wilderness_copy) I had it immediately crash when I tried to access my main faction camp notice board.  Checking on my second faction camp the same thing.  I upgraded my game to the latest release as I saw in the release notes that there had been a great many additions to faction camps and I thought that it might help.  Once upgraded it no longer crashed but it told me that the first thing I needed was a command tent even though my camp was level 13 or something like that with two farms a blacksmith, chop shop and kitchen.  My other camp did the same thing.  It will still allow me to tab to my various upgrades but it only has tasks to upgrade those from the very beginning as well.

I decided to leave it for a week or two to hopefully let the kinks in the latest camp improvements to sort themselves out but after now upgrading again it's still a problem.  In fact my attempting to run the latest update has now wrecked the new game I started while I hoped this issue would be sorted out.  :-(

# Steps To Reproduce

I have no idea.  I don't see any other reports of this issue so maybe I'm just super lucky!

# Expected behavior

I expect my faction camp notice boards to 'notice' my camps actual upgrade level. 

# Screenshots

Not really helpful here

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-4623-g09d2e75 [64-bit]
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3303294/debug.log)

 - Graphics version: Tiles
 - Mods loaded: 
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-4623-g09d2e75 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Classes and Scenarios Mod [more_classes_scenarios],
    Filthy Clothing [filthy_morale],
    StatsThroughSkills [StatsThroughSkills],
    Sleep Deprivation [sleepdeprivation]
]

# Additional context

**Comment by davidpwbrown** [comment]
This is probably legacy handling in the camp code. can you provide a save game?

**Comment by M1nks** [comment]
It's too big to attach - 50MB when zipped.  Is there a way to send it or is there some specific part which you need?

**Comment by M1nks** [comment]
7z gets it down to 23MB but it's still too large to attach here.

**Comment by M1nks** [comment]
This 'might' work.  I've used chainsaw on the file and then zipped those up.  Sooo, if you unzip the files, and merge them together it should theoretically work...



[The Wilderness_copy.7z.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3317125/The.Wilderness_copy.7z.zip)

**Comment by M1nks** [comment]
[The Wilderness_copy.7z (2).zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3317127/The.Wilderness_copy.7z.2.zip)

**Comment by M1nks** [comment]
[The Wilderness_copy.7z (3).zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3317130/The.Wilderness_copy.7z.3.zip)

**Comment by M1nks** [comment]
And here is the merge file.  

[The Wilderness_copy.7z_Merge.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3317134/The.Wilderness_copy.7z_Merge.zip)

**Comment by int-ua** [comment]
Please comment if you are able to reproduce it on a newer version and we'll reopen this issue.
