### ISSUE TITLE
Blacklist Lovecraftian Mobs

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#31594]
I thought this was a thing but I can't find this mod anymore.

**Is your feature request related to a problem? Please describe.**  
The issue I'm running into is being hit by something completely debilitating from the edge of the map during early game exploring . Generally from a flaming eye or gozu. Making it preferable to just restart the game than have to endure the long duration of blindness/boomer (bringing exploring to a complete halt), early negative mutation, or worse the painful death by fungal infection. 

**Describe the solution you'd like**  
A mod to blacklist things like Flaming Eyes, Gozus, Yuggs, etc.

**Describe alternatives you've considered** 
Make the debilitation of these mobs a bit more avoidable.
  - limit their range.
  - limit their percent chance of doing something debilitating.
  - limit their numbers so that they are much rarer encounters.

**Additional context** 
In general I'm cool with the mi-go's and hunting horrors (though they are a bit fast). Usually I can manipulate them on zombies or wildlife to get away, or I die trying. 

Thanks for the awesome game!

**Comment by Night-Pryanik** [comment]
As far as I can tell, mods removing arbitrary monsters wouldn't be welcome in "official" bundle.

**Comment by RogueYun** [comment]
Aren't all blacklisted monsters arbitrary? Don't get me wrong, shockers and acid zombies are super annoying and deserve the mods they have, but at least their debilitating moves are relatively avoidable. Flaming eyes, gozus, and sometimes yuggs are more of a crap shoot that can't be as easily avoided.

**Comment by Night-Pryanik** [comment]
> Aren't all blacklisted monsters arbitrary?

Yes, they are, and we don't plan to add more mods of this type because the reason to blacklist this or that monster is entirely subjective and thus arbitrary.

**Comment by RogueYun** [comment]
I don't mean to be picking and choosing specific monsters. I just gave you the reasoning why I would like a mod to blacklist lovecraftian mobs in general. I'm okay with blacklisting the whole faction (if it exists).

**Comment by logros13** [comment]
I to would love this but more for immersion reasons, coming across giant flaming eye that can curse you feels more DnD than zombie survival. There may be a lore handwave why it is not technically magic but it certainly _feels_  more like something fit for magiclysm than the common mainline stuff.

**Comment by FirebrandCoding** [comment]
@RogueYun: if the developers remain closed to the idea of adding blacklist mods, you can make one for yourself, locally, and post it on the forums and/or on Github. Take Mundane Zombies, remove all entries, add those you find an offense to your preferences, and save it with the required other changes in a different folder.

Go to `data/json/monsters`, pick the file that sounds most like what you're looking for, and `Ctrl + F` your way to the target monsters' ID that you can put into the blacklist.

**Comment by SunshineDistillery** [comment]
The alternatives you listed sound pretty good.

**Comment by TechyBen** [comment]
Is it part of the nether faction? There is an option for this in gamegen: "Remove nether creatures". Mi-go and flaming eye, plus a couple extras. Fungal, zed and others should still be persistent in the game with this mod/switch.

**Comment by EirenexTheDragon** [comment]
there is, and it still should work as intended, despite being years old

**Comment by Rail-Runner** [comment]
Maybe just add a menu to allow blacklisting anything that can be blacklisted (items, monsters, etc.), to make everyone happy?

**Comment by Night-Pryanik** [comment]
This would be an optimal solution and a great enhancement to the game. Implementing it would require a great effort of work though, that's why it isn't in the game yet.

**Comment by kevingranade** [comment]
Not interested in mainlining further blacklist mods.
