### ISSUE TITLE
Starting to build spike pit leads to numerous erros and hurting youself

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#31590]
# Describe the bug
Starting to build spike pit results in error message
![изображение](https://user-images.githubusercontent.com/11132525/59703128-48c97000-920a-11e9-8b51-8eec0e7cfb4a.png)

After that, if you press space bar to ignore the error, construction begins, but weird message pop up
![изображение](https://user-images.githubusercontent.com/11132525/59703213-74e4f100-920a-11e9-87a6-b915e706d265.png)

If you choose "No", you "fall in a pit" (without actual falling) and hurt yourself some more
![изображение](https://user-images.githubusercontent.com/11132525/59703287-9d6ceb00-920a-11e9-87ee-e37681f5e458.png)

If you decide to continue construction no matter the cost, you finish it, but the "construction done" message if weird: `you finishes construction : Spike Pit`

# Steps To Reproduce
1. Dig a pit;
2. Get yourself 4 pointy sticks;
3. Try to build Spike Pit over the pit.

# Expected behavior
No errors popping up, no hurting yourself, correct message on construction done.

# Versions and configuration
 - OS: Windows 10 Pro x64
 - Game Version: 0.D-4615
 - Graphics version: Tiles
 - Mods loaded: default only.

**Comment by davidpwbrown** [comment]
Oops, forgot that some constructions will require to be built on top of a trap, and the unfinished construction marker is also a trap... will look into this.
@ me if I forget.
