### ISSUE TITLE
Omnicellular Slimes Spawning Even When Severely Dehydrated

### ISSUE THREAD

**Issue by DefaultUserame** [CleverRaven/Cataclysm-DDA#31597]
# Describe the bug

"Omnicellular" is a mutation that allows the player to spawn cute & helpful slimespawns. Unfortunately, the mutation has been messed up ever since the change to hunger/thirst. Now it is possible to die of dehydration even by doing nothing but drinking water. Indeed, unless the player is malnourished, the player will not be able to eat or drink at all. This makes it all but impossible to effectively pilot a character with this mutation.

After consuming any food/drink item, the game makes the following checks: Does the player have 51k or more stored kilocalories? Does the amount of water in the player's stomach outweigh their thirst? If either one of these two conditions hold true, the game spawns a slime, consuming both nutrition and hydration. NOTE: the player is considered "malnourished" when the player has fewer than 52.25k stored kilocalories. Thus, even when the player is "malnourished", they will still spawn a slime any time they attempt to eat or drink.

The result of this behavior is that the average player is unable to drink effectively. In trying to do so, the player accrues an ungodly amount of pain and many more slimesprings than they need or want. Even if the player is famished and dehydrated, attempting to eat or drink will still cause the player to spawn a slime.

# Steps To Reproduce

Steps to reproduce the behavior (:
1. Make a player with the "Omnicellular" trait with at least 51k stored calories.
2. Eat or drink any food/drink item
3. You spawn a slimespring.

# Expected behavior

The player should NOT have to be constantly malnourished in order to eat/drink. A thirsty player should NOT find themselves unable to drink water, regardless of how many kilocalories of stored nutrition they have access to. 

Either the mechanism by which the player spawns slimes by eating/drinking should be removed entirely or it should be changed so that players do not find themselves dehydrated and unable to drink (such as by requiring that both conditions hold true).

# Screenshots

![](https://cdn.discordapp.com/attachments/252368751016542218/590607801353764864/unknown.png)

**Comment by Night-Pryanik** [comment]
Addressed by #31605.
