### ISSUE TITLE
"Look Around" menu z-level direction abbreviations wrapping

### ISSUE THREAD

**Issue by ifreund** [CleverRaven/Cataclysm-DDA#31618]
# Describe the bug

The UI layout was designed with directions labels of the `N` and `SE` variety, but with z-levels and 3d fov enabled you can see monsters on other zlevels with get labeled as `DN_NE` for "Down Northeast` for example. The ui code does not expect these longer labels which causes wrapping

# Steps To Reproduce

1. Enable z-levels and 3d fov
2. Go up on a roof
3. Press `V` and view monsters

# Expected behavior

There's a couple of possible solutions here.  There seems to be space in the current UI layot for 3 characters, so one option is using labels such as `DNE` or `USW` that fit in the 3 characters.  I personally think this is a little intuitive however.

I'd prefer something like `NE+1`, `S-1`, and `SW+0` as that is in my opinion more intuitive and also 1 character shorter than the current `DN_NE`.  It does however require more space in the UI.

# Screenshots

![Screen Shot 2019-06-19 at 12 10 21 PM](https://user-images.githubusercontent.com/12723818/59758420-309b3480-928e-11e9-96d8-d4043a125ec8.png)

**Comment by Night-Pryanik** [comment]
I would prefer a total remake of UI, so it could take advantage of modern monitors with high resolutions.

**Comment by ifreund** [comment]
I don't think that dropping curses support is an option, so I'm not quite sure what you're picturing.

**Comment by Night-Pryanik** [comment]
I propose to get rid of fixed sidebar width and make its width scale with monitor resolution and/or monitor dimensions. Playing on a 5'' mobile phone? Get default 45 units for sidebar width. Playing on a 8K 32'' monitor? Enjoy 50, 100, 200 or any other width that would fit all the long monster's name (#24436), and all the long items names, and will fix all other issues that come from fixed and hopelessly outdated UI.
