### ISSUE TITLE
[9183] Critical issue: player displaced and skills erased on game save (possibly other effects)

### ISSUE THREAD

**Issue by zacklucky7** [CleverRaven/Cataclysm-DDA#31627]
# Describe the bug

Starting in 9183, a critical bug has been introduced where the player is displaced (always northwest), has all of their skills erased, and gender set to male when saving and reloading the game.

Stats, traits, and inventory seem to be unaffected, but I did not do a thorough examination for what was affected.

This does lead to situations where survivors will find themselves reloading in midair or in the ocean and then falling or drowning.

# Steps To Reproduce

1. Create a character on version 9183.
2. Move at least one tile. The bug does not trigger if you save and reload in your starting tile. It might also trigger if any time passes, but I was able to reliably trigger it by moving at least one tile.
3. Save and return to the main menu.
4. Reload your save.
5. You will find that your skills have been erased, you have been displaced somewhere to the northwest on your Z-level (including into solid rock), and your gender has been set to male (if female).

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4674-g2e5c67a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Filthy Clothing [filthy_morale],
    Garden Pots [growable-pots],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Sleep Deprivation [sleepdeprivation],
    StatsThroughSkills [StatsThroughSkills],
    Generic Guns [generic_guns],
    Mythological Replicas [nw_pack],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    sees-player icon, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex]
]

**Comment by curstwist** [comment]
Can confirm the displacement issue on vanilla 9184. Didnt notice the rest but I was in a test world.

**Comment by TechyBen** [comment]
Same here. I thought it was due to the skills char - player changes and refactoring.
I am also getting a map crash, but not sure if it's the same or different.

**Comment by KorGgenT** [comment]
'm fairly confident that my refactoring pr is not the cause of this, but i'll help investigate if i can.

**Comment by molkero** [comment]
I also lost the starting scenario profession name & all bionic power.

**Comment by ZhilkinSerg** [comment]
> 
> 
> I also lost the starting scenario profession name & all bionic power.

There is an error during savegame loading, so you characters stats were reset to default values.
