### ISSUE TITLE
Holsters crafting component choice unbalanced

### ISSUE THREAD

**Issue by stopple** [CleverRaven/Cataclysm-DDA#31622]
# Describe the bug

The various crafting recipes for holsters have a lopsided choice when it comes to string vs thread.  Ex: Quickdraw holster.  Choose between **20 thread** or **2 long strings** (2 long strings can be freely converted to 600 thread)

# Steps To Reproduce

View holster crafting requirements

# Expected behavior

The resource choice between thread or string should be closer than 1 to 30

# Screenshots

![resources](https://user-images.githubusercontent.com/19255442/59769954-26207100-9275-11e9-94d3-4aed7ab983aa.PNG)

# Versions and configuration

OS: Windows 10.0 1809
Version: 0.D-4578-gf477339 [64-bit]
Graphics: Tiles
Mods: Dark Days Ahead [dda], Disable NPC Needs [no_npc_food]

**Comment by TechyBen** [comment]
I looked at changing this, but have decided against it for now. Feel free to discuss. As far as I can see, 24 withered plants/small strings from the "2 long strings" would cover the "20" threads (cotton/yarn/plant fibre). So the numbers match to that extent.

 I guess 6 small strings could also be added as an option. If we wish to add granularity.

**Comment by RarkGrames** [comment]
A lot of holsters have thread and string as recipe components, so I think this is an error (OR instead of AND). Also you have no way of fastening the holster on yourself if you don't use strings.
