### ISSUE TITLE
Examining UPS modded tool causes error

### ISSUE THREAD

**Issue by gotnoface** [CleverRaven/Cataclysm-DDA#31633]
# Describe the bug

It has been quite a long time since UPS toolmod was working correctly, but recent ammo changes furthermore made any UPS modded tool cause an error on examining in inventory and same error, but cyclic, softlocking your game, when inspected lying on the ground.

# Steps To Reproduce

1. Choose any tool using plain batteries.
2. Apply UPS conversion mod.
3. Examine modded tool in inventory or drop it and try to pick it up.

# Expected behavior

No error occurs.
Probably a minor problem though, because UPS toolmod doesn't work as intended anyway #31377.

# Versions and configuration

 - OS: Reproduced on Windows 7, Windows 10, Android
 - Game Version: 0.D-4674-g2e5c67a
 - Graphics version: Tiles
 - Mods loaded: [dda], [alt_map_key], [no_npc_food]

# Additional context

-MinGW Runtime Assertion-

Assertion failed!

Program: D:\CDDA\cdda\cataclysm-tiles.exe
File: src/optional.h, Line 45

Expression: full

**Comment by TechyBen** [comment]
I also got this. Picking it up sometimes caused the error I think.

**Comment by Inglonias** [comment]
The crash notwithstanding, my research shows that some UPS modded tools do work as expected if you're carrying the UPS with you, which is the intended behavior going forwards.

**Comment by gotnoface** [comment]
Well if I happen to not crash, when ignoring the error, I found out that some of the ups'd tools actually work without using any power whatsoever after verifying your claim. So that's another bug I'd have to file separately, which seems like a wasted effort at this point.

UPS was in a sorry state even before the ammo wells, now it's just pitiful and it probably won't get any love until this battery revolution gets resolved first. I'm not salty about it, but I think all I can do now is just leave my UPS tools somewhere in a locker somewhere to avoid any crashes and just use up my stash of disposable batteries I left in last town.

**Comment by eilaattwood** [comment]
> I'm not salty about it, but I think all I can do now is just leave my UPS tools somewhere in a locker

It's time to use sealed crate for the first time. I guess ;)

**Comment by eilaattwood** [comment]
Well, Looks like it`s somehow related to wrong ammo type, because I have the same crash when inspecting a gun (S&W 610) that is using realguns ammo that is not currently defined correctly.
