### ISSUE TITLE
Missing item definition: mater

### ISSUE THREAD

**Issue by ShadowMiner** [CleverRaven/Cataclysm-DDA#31648]
# Describe the bug

Missing definition. Error when load world

# Steps To Reproduce

1. Load my world.

# Expected behavior

No error.

# Screenshots

![изображение](https://user-images.githubusercontent.com/20936024/59823981-875d4880-9338-11e9-9ad6-bc99431bca5e.png)

```
 DEBUG    : Missing item definition: 
mater
 
 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1187
```

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-4697-g0f27460 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    [dda],
    [no_npc_food],
    [Mining_Mod],
    [alt_map_key],
    [mutant_npcs],
    [makeshift],
    [crt_expansion]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3308967/debug.log)
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3308974/default.zip)

**Comment by ZhilkinSerg** [comment]
There are most probably no issue in vanilla game, so I will close this issue, but your savegame is definitely borked as one of map contains very strange data:

![image](https://user-images.githubusercontent.com/16213433/59843002-63156200-9360-11e9-91e1-f58346eca6e9.png)

Did you remove any mods from your game recently by chance? Anyway I have fixed save for you (replace invalid `\rmater` item entries with `water`):

[fixed-Ozark.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3309975/fixed-Ozark.zip)
