### ISSUE TITLE
Crash when loading after aborting character creation once

### ISSUE THREAD

**Issue by TinkerWorX** [CleverRaven/Cataclysm-DDA#31642]
# Describe the bug
Crash when loading after aborting character creation once

# Steps To Reproduce
1. Make a world.
2. Start character creation.
3. Abort character creation.
4. Start character creation.
5. Game crashes while loading "Crafting Recipes".

# Expected behavior
It shouldn't crash. Ideally because it makes playing the game difficult.

# Versions and configuration
OS: Windows 10 64-bit
Game Version: 0.D-4692-g5de4516
Graphics version: Tiles
Mods loaded: N/A

# Additional context
[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3308316/logs.zip)

**Comment by Zmedaris** [comment]
![cddaerror](https://user-images.githubusercontent.com/12032854/59810226-162a8080-92b9-11e9-9b43-2fc45f7ca0a5.png)

Can confirm. Much error, many disappoint, wow.
