### ISSUE TITLE
Application error when using fire in combination with firewood source

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#31656]
# Describe the bug

When attempting to lit a fire (using [E]xamine and [f]ire) in a stove with no fuel in it and a firewood source next to it, an application error shows up. Ignoring the application error is possible and the game continues as expected. However if 'terminate' is selected, the application crashes to desktop.

If you ignore the warnings (you have to hold the ignore button for about 6 seconds because a lot of them show up) the fire does lit up. However when attempting to craft clean water and the fuel in the stove runs out, the same error shows up.

Edit: Did not happen in the previous version i ran, 9188. Tested in native /w disable npc needs and it also occurs.

# Steps To Reproduce

1. load attached save
2. attempt to start a fire in the stove with no fuel
3. application error shows up

Alternatively:
1. have a lit fire in the stove
2. attempt to craft clean water
3. The stove runs out of fuel
4. the application error shows up

# Expected behavior
expected to lit a fire without application error

# Screenshots
![image](https://user-images.githubusercontent.com/50166150/59853977-4550f880-9372-11e9-82f7-f6785f3d99ba.png)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-4731-g801d574 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Mining Mod [Mining_Mod],
    Folding Parts pack [deoxymod],
    Simplified Nutrition [novitamins],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    More Locations [more_locations],
    Garden Pots [growable-pots],
    Medieval and Historic Content [Medieval_Stuff],
    Hydroponics [hydroponics],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

# Additional context
[debugandconfig.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3310684/debugandconfig.zip)

[201906191851-50-40.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3310687/201906191851-50-40.zip)

**Comment by MatthewGP** [comment]
VERSION: 0.D-4731-g801d574
* I have experienced this also.
![cataclysm-tiles_2019-06-20_10-47-46](https://user-images.githubusercontent.com/24598677/59862822-7a008800-9351-11e9-852f-fd530baff9ff.jpg)
![cataclysm-tiles_2019-06-20_10-47-28](https://user-images.githubusercontent.com/24598677/59862823-7a008800-9351-11e9-8653-f763f5a1a5c5.png)

**Comment by ProfoundDarkness** [comment]
Potential additional detail... I observed that in build 9192 or 9191 that fires no longer got fed by nearby fire sources.  Tested build 9191 (specifically), got the previously mentioned error.  When I reverted to build 9190 everything was fine again.

**Comment by suka97** [comment]
VERSION: 0.D-4736-g0f5bd17  (Windows x64)

I have also experienced this error

![Crash1](https://user-images.githubusercontent.com/49660888/59883418-67a34000-938b-11e9-8bcd-ffcbe0faf582.png)
![Crash2](https://user-images.githubusercontent.com/49660888/59883444-80abf100-938b-11e9-958d-4ee0aeb1bbc6.png)

**Comment by ZhilkinSerg** [comment]
Provide a savegame and reproduce steps please.

**Comment by suka97** [comment]
> Potential additional detail... I observed that in build 9192 or 9191 that fires no longer got fed by nearby fire sources. Tested build 9191, specifically fresh install from launcher, stock mods, got the previously mentioned error. When I reverted to build 9190 everything was fine again.

### Steps To Reproduce
Steps to reproduce the behavior:

1. Load attached save
2. Try to read "The Big Book of First Aid" until you gain a level


[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3312227/save.zip)

**Comment by ZhilkinSerg** [comment]
Doesn't crash for me. What's your game version?

**Comment by suka97** [comment]
> Doesn't crash for me. ~What's your game version?~ Please try build 9194 when it is out and see if it crashes.

Thank you, the crash is gone now
