### ISSUE TITLE
Deconstructing things crashes the game

### ISSUE THREAD

**Issue by Deak1113** [CleverRaven/Cataclysm-DDA#31651]
# Describe the bug
Deconstructing things crashes the game

Deconstructing things crashes the game

# Steps To Reproduce
Deconstruct whatever 

1. Get tools to dissasemble
2. Try to dissasemble
3. You will get a error message

# Expected behavior

you will get a error log, and if you will try any option, you will get a crash log and game will crash, i have no idea why this happens.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-4722-g52c0721
 - Graphics version: Tiles
 - Mods loaded: Bootleg walkers, Garden pots, Mythical Replicas, Makeshift Gun Pack, Craftable gun pack, Medival and historic content, Alternative map key, hydroponics, mining mod, beta national guard camp, cars to wrecks, vehicle additions packs, tanks and other vehicles, folding parts pack

# Additional context
  
[crash+debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3310024/crash%2Bdebug.zip)

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3310029/save.zip)

(sorry for grammar errors, im not a native english speaker)

**Comment by 7illian** [comment]
Can confirm. Happened twice while deconstructing a computer.

**Comment by davidpwbrown** [comment]
Deconstructing or dissassembling?

**Comment by Deak1113** [comment]
> Deconstructing or dissassembling?

Im so sorry, i was playing with my native language because it had a pretty good translation and made that mistake, i fixed it now i meant deconstructing

**Comment by ifreund** [comment]
No problem, I figured it out
