### ISSUE TITLE
Crash when crafting plastic bowls

### ISSUE THREAD

**Issue by TheCatWizard** [CleverRaven/Cataclysm-DDA#31663]
Game version: 0.D-4736-g0f5bd17 (Experimental 9193)

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: dda, no_npc_food, aftershock, crt_expansion, magiclysm, craftgp, growable-pots, ew_pack, makeshift, Medieval_Stuff, More_Survival_Tools, modular_turrets, Salvaged_Robots, alt_map_key, crazy_cataclysm, hydroponics, MMA, deoxymod, blazemod, Tanks, sees_player, manualbionicinstall, no_filthy_clothing, no_reviving_zombies, safeautodoc, novitamins, StatsThroughSkills

### Expected behavior
I obtain plastic bowls in exchange for plastic chunks.

### Actual behavior
Game Crashes.

### Steps to reproduce the behavior
Load my savefile and attempt to single or batch craft plastic bowls (I have everything set up). I was not able to replicate the issue in a clean world with the same mods.
[My_Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3311278/My_Save.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3311274/crash.log)

**Comment by ZhilkinSerg** [comment]
I cannot reproduce.

**Comment by ipcyborg** [comment]
I can't reproduce it too.
Tried on 0.D-6063-gee64205
