### ISSUE TITLE
Random crashing, unknown reason

### ISSUE THREAD

**Issue by Krisu001** [CleverRaven/Cataclysm-DDA#31678]
# Describe the bug

The game crashes repeatedly and I cannot seem to escape it. I have no idea why. I have a Samsung Galaxy S9.

# Steps To Reproduce

1. Load save.
2. Continously move in one direction or wait 5 minutes. Waiting 5 minutes seems like the more consistent method.
3. Game crash.
# Expected behavior

I expected the game to let me leave or wait 5 minutes but my game crashed instead, and I have no idea why.
# Versions and conﬁguration

- OS: Android
- OS Version: Manufacturer: samsung; Model: SM-G960U; Release: 9; Incremental: G960USQS4CSD3;
- Game Version: 0.D-4736-g0f5bd17 [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
Dark Days Ahead [dda], 
Aftershock [aftershock], 
C.R.I.T Expansion Mod [crt_expansion], 
Magiclysm [magiclysm],
Medieval and Historic Content [Medieval_Stuff],
 More Survival Tools [More_Survival_Tools], 
Mythological Replicas [nw_pack], 
DinoMod [DinoMod],
Modular Turrets [modular_turrets],
Salvaged Robots [Salvaged_Robots], 
Alternative Map Key [alt_map_key], 
Hydroponics [hydroponics], 
Mutant NPCs [mutant_npcs], 
Mythical Martial Arts [MMA], 
More Locations [more_locations], 
Fuji's More Buildings [FujiStruct], 
Folding Parts pack [deoxymod], 
Vehicle Additions Pack [blazemod], 
Other Vehicles [Tanks], 
Necromancy [necromancy],
No Survivor Armor [no_survivor_armor],
Classes and Scenarios Mod [more_classes_scenarios], 
SpeedyDex [speedydex], 
StatsThroughSkills [StatsThroughSkills], 
NPC traits [npc_traits]
]

Additional Context

I can't seem to find a crash log on my android device. 

Debug Log(warning it's quite lengthy, you have to scroll all the way down to get to the latest entry) [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3312334/debug.log)

Save file: [Hiltonia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3312340/Hiltonia.zip)

**Comment by KorGgenT** [comment]
I downloaded the save on current master on pc and was unable to confirm. can anyone confirm this on the mobile version?

**Comment by Krisu001** [comment]
I think I found out why. My game is crashing when NPCs shoot things for some reason, I think.

**Comment by spectre102394** [comment]
My game also crash on android whenever npc's shoots things. Now I have to use debug (kill all npc's) whenever I see an npc with a gun to prevent crash

**Comment by chriseich21** [comment]
Yea this was a problem for a bit but was fixed after a few builds

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.
