### ISSUE TITLE
Suppressors and subsonic ammo should work realistically

### ISSUE THREAD

**Issue by Mooses2k** [CleverRaven/Cataclysm-DDA#31674]
**Is your feature request related to a problem? Please describe.**  
Currently the sound of a gunshot is modeled based only on damage and whether a suppressor is attached. Real life is more complicated and allows for things like ammo that travels faster than or slower than the speed of sound. When a suppressor is used with subsonic ammo, the result is much quieter (though not Hollywood quiet, typically) than supersonic ammo of the same caliber shot through the same suppressor. This is due to, primarily, the sonic-boom crack sound from something breaking the sound barrier.

**Describe the solution you'd like or alternatives considered**  
Well, either we really model muzzle velocity and terminal ballistics, or we have a flag that says 'subsonic' and reduce volume by much more for those and much less for others. Open to options. Recipes for subsonic ammo should be made available.

**Additional context**  
.45ACP and many .22s are subsonic, and subsonic ammo is available for pretty much every caliber. I'm making a PR to add .300BLK supersonic and subsonics to the game as well.

**Comment by adamkad1** [comment]
that would be nice to have

**Comment by ymber** [comment]
We currently have `loudness` definable for ammo items. Should be fairly simple to attach a `subsonic` bool to the `item::gun_noise` calculations.
