### ISSUE TITLE
"Pick up all items" key only picks up batches of items

### ISSUE THREAD

**Issue by mefimim** [CleverRaven/Cataclysm-DDA#31677]
# Describe the bug

The pick-up all items functionality is having a hiccup. It sort of does pick-up all items but it goes in one direction at a time. Press it once to pick-up all items North of your character, press it a second time for items NorthEast, then again for NorthWest, and so on. 

# Steps To Reproduce

1- Surround your character with items on the ground (bash some furniture to pieces inside a house).
2- Optional: debug some backpacks, rucksacks and such - and wear them.
3- Open the advanced pickup menu (default key '/').
4- Press the 'Move all items' key (default key ',').
5- It will pick up all items in one direction each time you press it (eg. all items in SE direction from the character) Press it again to pick up all items in a new direction (eg West). You need to keep pressing once for each direction with items.

# Expected behavior
Until a few weeks ago it would pick up all items on all eight tiles next to the character (assuming there was enough space left in the backpacks). One key-press and it would vacuum all items around.

# Versions and configuration

 Please complete the following information; you can now go to:
- "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
- Please update your OS version with a more precise version. 

I can't find the file 'debug.log' and I get a notice saying: 'No LSB modules are available'. I would expect the file to be inside the config directory. I'm not sure if the notice is telling me the game cannot write the file.

These is my setup:
cataclysmdda-0.D-Linux_x64-Curses-9193
Linux Mint 19.2
No modules whatsoever loaded inside the game, just plain vainilla.

**Comment by Randonx** [comment]
Mefimim

You have to have one of your window panes set to `All` by pressing 'a' or 'A' in the Advanced Inventory Window, and the other pane set to 'i' or 'I' for inventory.  Then if you press ',' while on the side of the screen you want to move items from, it will move all.

**Comment by RDru** [comment]
I have the same issue as @mefimim described.

**Comment by ifreund** [comment]
Adding this to my todo list, though it might be a minute before I get to it.
