### ISSUE TITLE
some conversations cannot be added to the PO

### ISSUE THREAD

**Issue by kwl01skz** [CleverRaven/Cataclysm-DDA#31685]
# Describe the bug

Some conversations in TALK_COMMON_MISSION.json cannot be added to the PO file.

Even though I executed update_pot.sh, I still can't find it in the generated po file, even if these conversations have not been updated recently.

TALK_COMMON_MISSION.json
```
        "no": {
          "has_no_assigned_mission": "I have another job for you.  Want to hear about it?",
          "no": {
            "has_many_assigned_missions": "I just have one job for you.  Want to hear about it?",
            "no": "I just have one job for you.  Want to hear about it?"
          }
}

```
 This could not be found in the PO file.
` I have another job for you.  Want to hear about it?  `
This can be found.
` I just have one job for you.  Want to hear about it?`

TALK_COMMON_MISSION.json
```
      "has_no_available_mission": {
        "has_no_assigned_mission": "I don't have any jobs for you.",
        "no": { "has_many_assigned_missions": "I don't have any more jobs for you.", "no": "I don't have any more jobs for you." }
},
```
Can't find them all.

# Steps To Reproduce

1. Execute update_pot.sh to update the PO file.
2. Search for the above conversation in /lang/po/

# Expected behavior
Find all possible conversations in the PO.

# Screenshots

![无标题](https://user-images.githubusercontent.com/1281487/59893714-6405cc80-9410-11e9-9086-484f01b53892.png)

![无标题2](https://user-images.githubusercontent.com/1281487/59893479-8ea35580-940f-11e9-83bd-bc6a1bfa3872.png)
 
# Versions and configuration

 - OS: Ubuntu 18.04
 - Game Version:0.D-4661-gd23e06a
 - Graphics version: Tiles
 - Mods loaded: None

**Comment by ZhilkinSerg** [comment]
Probably `extract_json_strings.py` should be updated.

**Comment by kwl01skz** [comment]
```
def extract_dynamic_line(line, outfile):
    if type(line) == list:
        for l in line:
            extract_dynamic_line(l, outfile)
    elif type(line) == dict:
        extract_dynamic_line_optional(line, "u_male", outfile)
        extract_dynamic_line_optional(line, "u_female", outfile)
        extract_dynamic_line_optional(line, "npc_male", outfile)
        extract_dynamic_line_optional(line, "npc_female", outfile)
        extract_dynamic_line_optional(line, "yes", outfile)
        extract_dynamic_line_optional(line, "no", outfile)
        extract_dynamic_line_optional(line, "has_no_available_mission", outfile)
        extract_dynamic_line_optional(line, "has_many_assigned_missions", outfile)
        extract_dynamic_line_optional(line, "has_no_assigned_mission", outfile)
    elif type(line) == str:
        writestr(outfile, line)
```
like this?
