### ISSUE TITLE
Increased Firewood Consumption

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#31684]
# Describe the bug

I'll be honest, I could be wrong about this.  It seems to me, though, that while using a marked firewood source, the wood is being consumed extremely quickly.  Additionally, hovering over the fire gives the message saying that the fire will burn out very soon, regardless of having multiple pieces of wood inside it.  

Initially, I thought this was because I was using splintered wood, but it also occurs with planks.

# Steps To Reproduce

1. Set up firewood source
2. Start fire in fire container
3. Read a book!
4. Messages will output constantly as you add wood to the fire.

# Expected behavior

I don't think that wood should be consumed at this rate.  I can't give a precise wood to burn time ratio that I expect, but it feels like I shouldn't be chewing through wood so quickly.

# Screenshots

There's video of this [here](https://youtu.be/rMdvGpKvMWU?t=104) showing the rapid consumption in action.

Here's a shot of the fire displaying as basically dead.
<img width="746" alt="fire1" src="https://user-images.githubusercontent.com/41651793/59892922-0d18dc80-93a9-11e9-8976-744542f482d2.png">

And here's a similar shot of the fire containing a lot of wood but still displaying as basically dead.  I even waited several turns, thinking it would update the fire length, but it still shows as dying.
<img width="696" alt="fire2" src="https://user-images.githubusercontent.com/41651793/59892939-17d37180-93a9-11e9-9aae-378e02d3455a.png">

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4623-g09d2e75 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Bens GF recipes [Tolerate_This],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Caches [P_Caches],
    Folding Parts pack [deoxymod],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I assume this is also connected to the turn time change.  I thought maybe this was actually intentional, but could not find any PRs relating to this.  So, I assume it's a bug.

**Comment by Zombiemanpig** [comment]
Yea I have a feeling fire fuel burns 6 times faster or something similar, I too notice my wood pile disappearing within a day or 2 ever since the time changes.

**Comment by 7illian** [comment]
Yea, this is has been a problem since the 1s change. Hopefully it's fixed soon.

**Comment by matthemsteger** [comment]
Some background when I looked at this .. fuel is simulated to burn and there are calculations that use materials, and materials have a property called `volume_per_turn` that was not adjusted.

https://github.com/CleverRaven/Cataclysm-DDA/blob/dc3475c7b9b81e8305161a661cc7e36dd0179e16/data/json/materials.json#L1174-L1198

That being said, I just going through this file and dividing by 6 is not a particularly great solution. This file is confusing because much of the way things burn such as creating smoke, for example, seems to be abstracted and burning something does have a time component that interplays with fields.

**Comment by emptyexpression** [comment]
This still seems like an issue in the latest experimental. I'd like to also add that fires seem to generate smoke more often, judging by the number of "You inhale thick smoke" messages I've been getting.

**Comment by YakumoChen** [comment]
![image](https://user-images.githubusercontent.com/10399117/60764346-7f5f1180-a077-11e9-89f9-0ca8e6c55fa4.png)
This is a freshly lit log, barely lasts half an hour at best, and I would have thought logs burn all night. Hope this is fixed soon since I burn through trees extremely fast.

**Comment by emptyexpression** [comment]
This seems to have been fixed for planks in commit e7ab27, but I'm not sure it's been fixed for other materials.

**Comment by TheMurderUnicorn** [comment]
My complaint was specifically about firewood.  I wasn't concerned over other materials, as they're the less common 'fuel'.  For this reason, I'll be closing the issue.  If anyone is concerned about other materials, you should make a new issue, I think.
