### ISSUE TITLE
Common cold causes fatigue and dehydration at extreme rate

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#31691]
# Describe the bug

I believe, It's caused by #30253 . When player character suffer common cold (other diseases may also be affected) his/her needs are increasing with the extreme rate causing game to be almost unplayable (player need to sleep, drink and eat almost all the time)

# Steps To Reproduce

1. Obtain common cold effect.
2. Try to play with it for a while.

# Expected behavior

Common cold being less extreme as it used to be before.

# Screenshots
N/A

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-4796-g8fd4c4a
 - Graphics version: Tiles
 - Mods loaded: probably not needed

# Additional context

None

**Comment by Inglonias** [comment]
Is there a way to debug yourself sick to test this? Do you have a save file handy?

**Comment by TechyBen** [comment]
I had the flu in game, and yes, it made it really hard to manage. I was not sure if it was just my save/char or the new tick/turn rate. I did not post at the time because I know lots of things were already getting picked up/changed, so was waiting it out. :p 

The character survived, but I had to constantly eat and drink for like 5 in game days!

**Comment by Inglonias** [comment]
Hmm. Might be worth spawning in royal jelly until this gets resolved.

**Comment by Inglonias** [comment]
I cannot, for the life of me, figure out where in the code having a cold modifies your thirst or fatigue.

**Comment by TechyBen** [comment]
I am not getting similar with flu on a new start in the new builds. So not sure what else needs to be changed (health stat, underweight?). Sorry. :(

**Comment by eilaattwood** [comment]
> 
> 
> Hmm. Might be worth spawning in royal jelly until this gets resolved.

Already did that, sorry. So no save file with that effect.
