### ISSUE TITLE
Butchering sometimes causes the game to hang

### ISSUE THREAD

**Issue by Zetsukaze** [CleverRaven/Cataclysm-DDA#31702]
# Describe the bug

During a full butcher (unsure if the other options cause it), intermittent hang/freeze of the game

# Steps To Reproduce

1. Butcher something

# Expected behavior

For the game not to hang

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-4796-g8fd4c4a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Advanced Gear [adv_gear],
    BioCo Content [bioco],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Craftable Gun Pack [craftgp],
    Fungus Fighter Kit [antifunguskit],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Shard's Additions [shardstuff],
    Modular Turrets [modular_turrets],
    PKs Rebalancing [PK_REBALANCE],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    NPC traits [npc_traits],
    Zetsukaze's Hair - 0.D EDIT [zets_hair_extensions],
    More Locations [more_locations],
    Zet's Hair - More Locations [zets_hair_ext_more_locations],
    Zet's Hair - PKs Rebalancing [zets_hair_ext_pk_rebalance],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Arcana and Magic Items [Arcana],
    Necromancy [necromancy],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    No Filthy Clothing [no_filthy_clothing],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    Tame Bugs [tamebugs],
    Zetsukaze's CDDA Tweaks! [zets_tweaks]
]

# Additional context

Save file won't help, I reloaded and tried again with no issue 😞 

Unsure of the root cause, happened 3 times so far, once with a bear, once with a floating eye, once with a zombie pig. Sorry that I can't provide more pertinent information.

**Comment by Zetsukaze** [comment]
Edit: Full butchery on the flaming eye in this save hangs the game
[Temp.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3315443/Temp.zip)

**Comment by anothersimulacrum** [comment]
I tested this a bit, and it appear to happen when you don't have the required tools/materials in range

**Comment by SleeperJack** [comment]
I've had exact same issue with butchering. Full butcher on moose caused hang

**Comment by EvgenijM86** [comment]
I have encountered this on giant wasps. The only pattern I noticed is that in cases with no hangs I had rope in my hand (2 times) and in case where it hanged the rope was near me on the table (1 time). Not much of a statistic though.

**Comment by anothersimulacrum** [comment]
> I have encountered this on giant wasps. The only pattern I noticed is that in cases with no hangs I had rope in my inventory (2 times) and in case where it hanged the rope was near me on the table (1 time). Not much of a statistic though.

Yeah, that's a case where you don't have the tools in range - it only checks in your inventory for the rope.

**Comment by sdp0et** [comment]
I got this trying to see if a plastic sheet would work in place of a tarp.  Or maybe it was that I had a short rope in place of a long one.

Others have reported it [here](https://www.reddit.com/r/cataclysmdda/comments/c3ug1v/attempting_full_butchery_without_the_required/).
