### ISSUE TITLE
Mission to find Refugee Center leads you NEAR refugee center, not to it.

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#31713]
# Describe the bug

![image](https://user-images.githubusercontent.com/2125926/59954576-60e00000-9453-11e9-951d-6631d9fcbead.png)

# Steps To Reproduce
Use the computer in an evac shelter to get the Find Refugee Center mission

# Expected behavior
That red star should be in the refugee center itself.
# Screenshots
See above.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4799-g044439e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Ants [No_Anthills],
    No Fungal Monsters [No_Fungi],
    No Rail Stations [No_Rail_Stations],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins]
]

# Additional context
Likely caused by #31221. Paging @I-am-Erk

**Comment by ralreegorganon** [comment]
It's a deliberate change by @I-am-Erk to ensure that the game will reveal the route to the target after the changes in #31221. 

The code that reveals the route requires that the target be within a couple spaces of a road--and while those roads between the indicated point on the map and the actual center look like roads, they are not in fact road terrain but are custom terrains with a symbol and name, which means the pathfinding will not traverse them, and thus not reveal the route.

This is basically targeting the "entrance" to the area. You'll also notice there are fences surrounding it.

**Comment by Inglonias** [comment]
I figured the pathfinding code couldn't get through the custom terrain, but I was hoping it could still be fixed. Might cause confusion. It caused me enough confusion to file this bug report.

**Comment by kraetzin** [comment]
I agree with it causing confusion. It resolves itself when you get there and continue going past the marker, however it's not obvious when you reach it and see nothing. You have to go further than the marker itself, which confused me for a while. It's obvious once you know, but before then not so much.
