### ISSUE TITLE
Massive game slowdown on very specific map locations

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#31711]
Most recent revision. I've noticed that when approaching certain areas of the map (usually a zone of 50x50 local tiles), the game's turn speed degrades massively... up to 10 real-life seconds required to process each turn. I normally don't get turn speeds this slow even when the game is processing a massive explosion or building collapse. These sites slow down the game even when re-approaching them in-game hours or days later.

I often (but not always) see error messages in relation to these "lag spots":

![bugg](https://user-images.githubusercontent.com/8593513/59953773-d8effb00-943e-11e9-9f87-f981ef55e16d.png)

Accompanied entry from the debug.log attached below:

> 16:03:57.785 ERROR GAME : (error message will follow backtrace)
> 	(@0x5a672e[cataclysm-tiles.exe+0x1a672e]), 
> 	(@0x5a6d5a[cataclysm-tiles.exe+0x1a6d5a]), 
> 	(@0x6ada1b[cataclysm-tiles.exe+0x2ada1b]), 
> 	(@0x6b03d4[cataclysm-tiles.exe+0x2b03d4]), 
> 	(IMG_LoadWEBP_RW+0x558da8@0x1547d48[cataclysm-tiles.exe+0x1147d48]), 
> 	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
> 	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
> 	(BaseThreadInitThunk+0x14@0x7ff81cd83dc4[KERNEL32.DLL+0x13dc4]), 
> 	(RtlUserThreadStart+0x21@0x7ff81f173691[ntdll.dll+0x73691]), 
> Backtrace emission took 0 seconds.
> src/game.cpp:4145: game:monmove: feral hunter can't move to its location! (33:125:0), willow tree
> 16:04:29.768 ERROR GAME : src/game.cpp:4145: game:monmove: zombie can't move to its location! (21:125:0), willow tree
> 16:04:39.317 ERROR GAME : src/game.cpp:4145: game:monmove: zombie can't move to its location! (21:89:0), willow tree
> 16:05:55.261 ERROR : (error message will follow backtrace)
> 	(@0x5a672e[cataclysm-tiles.exe+0x1a672e]), 
> 	(@0x5a6d5a[cataclysm-tiles.exe+0x1a6d5a]), 
> 	(@0x5aa136[cataclysm-tiles.exe+0x1aa136]), 
> 	(IMG_LoadWEBP_RW+0x1180f6@0x1107096[cataclysm-tiles.exe+0xd07096]), 
> 	(@0x8b65c8[cataclysm-tiles.exe+0x4b65c8]), 
> 	(@0x8c8172[cataclysm-tiles.exe+0x4c8172]), 
> 	(@0x8c833a[cataclysm-tiles.exe+0x4c833a]), 
> 	(@0x6b0398[cataclysm-tiles.exe+0x2b0398]), 
> 	(IMG_LoadWEBP_RW+0x558da8@0x1547d48[cataclysm-tiles.exe+0x1147d48]), 
> 	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
> 	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
> 	(BaseThreadInitThunk+0x14@0x7ff81cd83dc4[KERNEL32.DLL+0x13dc4]), 
> 	(RtlUserThreadStart+0x21@0x7ff81f173691[ntdll.dll+0x73691]), 
> Backtrace emission took 0 seconds.
> src/map.cpp:8055 [size_t map::get_nonant(const tripoint&) const] Tried to access invalid map position at grid (12,-1,0)
> 16:14:16.664 ERROR : (error message will follow backtrace)
> 	(@0x5a672e[cataclysm-tiles.exe+0x1a672e]), 
> 	(@0x5a6d5a[cataclysm-tiles.exe+0x1a6d5a]), 
> 	(@0x5aa136[cataclysm-tiles.exe+0x1aa136]), 
> 	(IMG_LoadWEBP_RW+0x1180f6@0x1107096[cataclysm-tiles.exe+0xd07096]), 
> 	(@0x8b65c8[cataclysm-tiles.exe+0x4b65c8]), 
> 	(@0x8c8172[cataclysm-tiles.exe+0x4c8172]), 
> 	(@0x8c833a[cataclysm-tiles.exe+0x4c833a]), 
> 	(@0x6b0398[cataclysm-tiles.exe+0x2b0398]), 
> 	(IMG_LoadWEBP_RW+0x558da8@0x1547d48[cataclysm-tiles.exe+0x1147d48]), 
> 	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
> 	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
> 	(BaseThreadInitThunk+0x14@0x7ff81cd83dc4[KERNEL32.DLL+0x13dc4]), 
> 	(RtlUserThreadStart+0x21@0x7ff81f173691[ntdll.dll+0x73691]), 
> Backtrace emission took 0 seconds.
> src/map.cpp:8055 [size_t map::get_nonant(const tripoint&) const] Tried to access invalid map position at grid (12,-1,0)
> 16:16:11.202 ERROR : (error message will follow backtrace)
> 	(@0x5a672e[cataclysm-tiles.exe+0x1a672e]), 
> 	(@0x5a6d5a[cataclysm-tiles.exe+0x1a6d5a]), 
> 	(@0x5aa136[cataclysm-tiles.exe+0x1aa136]), 
> 	(IMG_LoadWEBP_RW+0x1180f6@0x1107096[cataclysm-tiles.exe+0xd07096]), 
> 	(@0x8b65c8[cataclysm-tiles.exe+0x4b65c8]), 
> 	(@0x8c8172[cataclysm-tiles.exe+0x4c8172]), 
> 	(@0x8c833a[cataclysm-tiles.exe+0x4c833a]), 
> 	(@0x6b0398[cataclysm-tiles.exe+0x2b0398]), 
> 	(IMG_LoadWEBP_RW+0x558da8@0x1547d48[cataclysm-tiles.exe+0x1147d48]), 
> 	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
> 	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
> 	(BaseThreadInitThunk+0x14@0x7ff81cd83dc4[KERNEL32.DLL+0x13dc4]), 
> 	(RtlUserThreadStart+0x21@0x7ff81f173691[ntdll.dll+0x73691]), 
> Backtrace emission took 0 seconds.
> src/map.cpp:8055 [size_t map::get_nonant(const tripoint&) const] Tried to access invalid map position at grid (-4,10,0)
> 16:16:11.203 ERROR : src/map.cpp:8055 [size_t map::get_nonant(const tripoint&) const] Tried to access invalid map position at grid (-4,11,0)
> 16:16:11.203 ERROR : src/map.cpp:8055 [size_t map::get_nonant(const tripoint&) const] Tried to access invalid map position at grid (-4,12,0)
> 16:16:11.203 ERROR : src/map.cpp:8055 [size_t map::get_nonant(const tripoint&) const] Tried to access invalid map position at grid (-2,5,0)
> 16:16:11.203 ERROR : src/map.cpp:8055 [size_t map::get_nonant(const tripoint&) const] Tried to access invalid map position at grid (-2,6,0)
> 16:16:11.203 ERROR : src/map.cpp:8055 [size_t map::get_nonant(const tripoint&) const] Tried to access invalid map position at grid (-2,7,1)
> 16:16:11.203 ERROR : src/map.cpp:8055 [size_t map::get_nonant(const tripoint&) const] Tried to access invalid map position at grid (-1,4,0)
> 16:16:11.203 ERROR : src/map.cpp:8055 [size_t map::get_nonant(const tripoint&) const] Tried to access invalid map position at grid (-1,4,1)
> 16:16:11.203 ERROR : src/map.cpp:8055 [size_t map::get_nonant(const tripoint&) const] Tried to access invalid map position at grid (-1,4,2)
> 16:16:11.203 ERROR : src/map.cpp:8055 [size_t map::get_nonant(const tripoint&) const] Tried to access invalid map position at grid (-1,4,3)

**The error type in the last several lines repeats a few hundred times**

**Comment by KorGgenT** [comment]
add a save file. and add the other requisite information the form tells you to add.

**Comment by Regularitee** [comment]
Found the cause. Experimental Z-level vision was toggled on, and I suspect was causing a host of pathfinding issues.
