### ISSUE TITLE
fast metabolism + crafting can kill you in ~1 hour

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#31717]
I was trying to craft a workbench with my fast metabolism character and just died because of dehydration. I then repeated my attempt with stuffing him to the point where he was forced to drink and he still died. And he was also drunk during that process, if that detail matters.

![food1](https://user-images.githubusercontent.com/430076/59957020-39ae2080-949d-11e9-9470-7be542a68603.png)
![food2](https://user-images.githubusercontent.com/430076/59957024-3d41a780-949d-11e9-99b0-3f2d966c7198.png)

I assume this a bug, because it is kinda ridiculous that it only takes 1 hour from fully fed to being dead.

Note: this was compiled at 8fd4c4ade0a5b7434dea2697a652e3834b397c94 . And I added 1 more patch that reverse this commit - fae7865c393ca68ccf58c4d2b603edf5186d7118 because it crashes the game when interacting with bathtubs.

**Comment by Metalsoul212** [comment]
Same as #31657 , I think it has to do with alcohol and recent the time change
