### ISSUE TITLE
Stamina depleting during mundane behavior

### ISSUE THREAD

**Issue by SleeperJack** [CleverRaven/Cataclysm-DDA#31722]
# Describe the bug

Stamina is depleted by normal walking for no apparent reason. Stamina only regenerates while standing completely still but begins depleting after normal movement. 

# Steps To Reproduce

1. Do not know how to reproduce this affect.

# Expected behavior

Expect stamina to not deplete from normal walking movement.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-4854-g63258af [64-bit]
- Graphics Version: Tiles
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3316526/save.zip)

 - Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Mythological Replicas [nw_pack],
    More Survival Tools [More_Survival_Tools],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

No mouth encumbrance at time of bug. Movement mode was set to Walking. Stripping everything off did not restore stamina regeneration to normal behavior. I've attached the affected save file.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3316527/save.zip)

**Comment by DemAvalon** [comment]
This is due to a change on stamina regen to change it to 1-second turns, It got reverted, just wait a while and get the new version with the revert when it becomes available.

**Comment by Night-Pryanik** [comment]
Closing then.
