### ISSUE TITLE
Switching fire mode on weapons causes crash

### ISSUE THREAD

**Issue by archigo** [CleverRaven/Cataclysm-DDA#31727]
# Describe the bug

Switching fire mode one H&K MP5 causes crash

# Steps To Reproduce

1. While firing a H&K MP5 (probably all weapons), press "s" to switch fire mode.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-4874-gd07de6a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Mythological Replicas [nw_pack],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3316630/save.zip)

**Comment by ZhilkinSerg** [comment]
I confirm the crash, but it is not reproducible when game is built with VS and run under debugger.

**Comment by ZhilkinSerg** [comment]
Further tests showed it is related to bayonet (attached combat knife) - game crashed whenever you cycle to bayonet gun mode and if you deattach it there are will be no crash.

**Comment by Zireael07** [comment]
Didn't we have a similar issue recently (bayonet causing crashes when cycling through gun modes)?

**Comment by anothersimulacrum** [comment]
Yes, #30676
