### ISSUE TITLE
Can't place rollmat inside of tent

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#31739]
# Describe the bug

Can't (a)ctivate rollmat inside of a tent.

OK looking into it a bit more I think it's cause the middle of the tent was on a tall grass tile.

# Steps To Reproduce

1. Start as bionic sniper
2. (a)ctivate tent
3. Try to do the same with the rollmat into the 1 tile in the middle of the tent, get message (this is not a suitable spot)

# Expected behavior

For these 2 items to be able to work together, or why do you get both with this start?

# Versions and configuration

 - OS: W10
 - Game Version: 9207
 - Graphics version: Tiles
 - Mods loaded: DDA, No NPC needs.

**Comment by Regularitee** [comment]
Yeah, tent floors seem to work as a different than regular ground. You get the same issue when trying to park a small vehicle (shopping cart, scooter) inside a tent; driving on the canvas floor destroys it as if it were an obstacle and not... just ground.

**Comment by Zombiemanpig** [comment]
> Yeah, tent floors seem to work as a different than regular ground. You get the same issue when trying to park a small vehicle (shopping cart, scooter) inside a tent; driving on the canvas floor destroys it as if it were an obstacle and not... just ground. Which ruins the tent as a whole.

I played around with it a bit and got it to work, I think tall grass is the problem.

**Comment by TechyBen** [comment]
IIRC you can place things in the middle, but not at the "door" tile. Is there a larger 2x2 tent yet?

**Comment by Regularitee** [comment]
@TechyBen The Large Tent has a 3x3 internal space.

**Comment by zacklucky7** [comment]
Tall grass is the problem as Zombiemanpig says -- if you try to place it on dirt or grass (the tile underneath the tent floor), you'll see that it places. Still, the tent floor should override whatever's beneath it if it can be placed...

**Comment by TechyBen** [comment]
> @TechyBen The Large Tent has a 3x3 internal space.

@Regularitee Thanks. I will check out the tent mechanics then (never got a large tent in my games lol), and see if furniture/use is nice and realistic/player expectant/gameplay helpful, or if I find any weird inconsistencies.

**Comment by TechyBen** [comment]
Camp chair and Tourist table cannot be used. Roll mat now works, but on the large tent only on the center square, not any of the other 3x3. If this is a large domed tent, then perhaps all 3x3 cells could be used for tourist table and chairs. If not (if instead a cone shaped one), then only the center cell should be used, and the roll may on all 3x3 cells.

I think the smaller candle/gas stoves (for heating food only) could possibly be setup inside. Not the brazier or hobo stove for obvious reasons.

Would it be good for me going through the items and seeing what can be reasonably added to the list of things to go in a tent? If it's just a json flag I could look at doing an edit to them.

**Comment by Night-Pryanik** [comment]
All tent indoor squares are of furniture type and therefore won't allow placing any other furniture on them.

Related: #26374 and #26638.

**Comment by Zombiemanpig** [comment]
> All tent indoor squares are of furniture type and therefore won't allow placing any other furniture on them.
> 
> Related: #26374 and #26638.

Weird I got the rollmat working fine inside as long as the tile I put it on isn't tall grass

**Comment by anothersimulacrum** [comment]
The rollmat is a trap, not furniture.

**Comment by Night-Pryanik** [comment]
It seems that the issue here is possibility to place tents on terrains that unsuitable for them, such as long or tall grass.
