### ISSUE TITLE
Western Boots cost 9 leather patches and salvage into 12

### ISSUE THREAD

**Issue by stopple** [CleverRaven/Cataclysm-DDA#31737]
# Describe the bug

Western Boots cost 9 leather patches and salvage into 12

# Steps To Reproduce

Craft western boots.  Salvage western boots.

# Expected behavior

The potential return of salvaging western boots should be less than the cost of creating them

# Screenshots

![boots_cost](https://user-images.githubusercontent.com/19255442/59965838-4a808580-94e1-11e9-9b1c-87ce92f6f496.PNG)
![boots_salvage](https://user-images.githubusercontent.com/19255442/59965840-4c4a4900-94e1-11e9-89dd-e07cefe428ce.PNG)

# Versions and configuration

- OS: Windows 10.0 1809
- Game Version: 0.D-4578-gf477339 [64-bit] Tiles
- Mods loaded:  Dark Days Ahead [dda],  Disable NPC Needs [no_npc_food]

**Comment by Zombiemanpig** [comment]
Thanks for letting me know about this method of converting thread into leather.
