### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Max191293** [CleverRaven/Cataclysm-DDA#31731]
I've tried several times already, but in a few minutes I'm going to crash.
Error (1) first and then (2)
![CDDA](https://user-images.githubusercontent.com/52102010/59963276-8293c280-94f9-11e9-8107-7de577f9be9a.jpg)

**Comment by Night-Pryanik** [comment]
Please don't neglect the issue template and fill it with all the required info about your OS, version of your game and what were you doing before the crash.

**Comment by Max191293** [comment]
**Steps To Reproduction**: 
I started a new game, walked near the place of appearance, then pressed "x" to see the bush and the game collapsed.

**Versions and configuration:**
OS: Windows 7 64bit
Game Version: 0.D-4088-g34de662
Mods loaded: DDA, Disable NPC Needs

**Additional context :**
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3317516/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3317517/crash.log)
There is no preservation of the game as it was crushed a couple of minutes after the start of the game, it did not have time to save.

**Comment by Night-Pryanik** [comment]
Your version is rather old. Did you try to install a new version from a clean slate and import your save in it?

**Comment by Max191293** [comment]
> Your version is rather old. Did you try to install a new version from a clean slate and import your save in it?

Если я правильно понял вы понимаете русский язык, мне сложновато всё правильно изложить на английском, поэтому отвечу так и ниже переведу на анг. :
Сохранения нету так как игра крашнулась до момента автосохранения, было 2 случая подобного краша, это не постоянно у меня. Но 2 раза было в начале игры, спустя ~ 5 - 10min, сейчас я уже обновился до более поздней версии и пока-что подобных крашей не наблюдал.
Eng:
I don't have a save, the game simply hasn't had time to make it, now I'm playing on a newer version of the game and I don't see anything like that.

**Comment by Night-Pryanik** [comment]
Ок, тогда иссуй будет закрыт, пока (и если) не появятся повторные краши.

Ok, closing the issue until (and if) crashes would appear again.
