### ISSUE TITLE
Switching movement modes while swimming doesn't change swimming speed but affects stamina

### ISSUE THREAD

**Issue by hdggDalton** [CleverRaven/Cataclysm-DDA#31740]
# Describe the bug
When you swim around in deep water (move from 1 tile to another) you can change your movement modes, doing so doesn't affect swimming speed, but it does affect stamina, so if you were to set it to running then your stamina would run out quickly but if you set it to crouching you move at the same speed and you even regenerate your stamina.

# Steps To Reproduce

1. Start a game
2. Strip your character down to the point where they don't sink in water
3. Find a river, jump in the deep water
4. Switch movement mode to running
5. Move around in the river
6. Observe the stamina go down very quickly despite swimming taking the same amount of moves
7. Switch movement mode to crouching
8. Move around in the river
9. Observe the stamina slowly regenerate despite swimming taking the same amount of moves as it did when movement mode was at running

# Expected behavior
I would expect that if moving in one mode takes the same amount of moves as in another mode, it would deplete the same amount of stamina, OR switching to faster movement modes would make you swim faster but act similarly to running on land, becoming slower as your stamina depletes.

# Screenshots

**If applicable**, add screenshots to help explain your problem.
![cddaswimc](https://user-images.githubusercontent.com/30754603/59966251-9249e180-94ce-11e9-84f2-3ae3d095c3d2.PNG)
![cddaswimr](https://user-images.githubusercontent.com/30754603/59966252-9249e180-94ce-11e9-9404-b96ba465b1ff.PNG)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-4123-g37a6167
 - Graphics version: Tiles
 - Mods loaded: dda, StatsThroughSkills, no_filthy_clothing

# Additional context

I modded the base game a bit, but it's just small item tweaks like making lawnmowers and toasters into deadly weapons of mass destruction. (100 bash dmg)

**Comment by Night-Pryanik** [comment]
@davidpwbrown any progress on this?
