### ISSUE TITLE
Recursive Beans Recipe

### ISSUE THREAD

**Issue by kasanryukin** [CleverRaven/Cataclysm-DDA#31744]
# Describe the bug
In the recipe for "raw beans" the only ingredient is 1 "raw beans" and it creates 2 "raw beans".

I was unable to locate the recipe in the JSONs (core and mods included) so I'm not sure where it is, but there it is.  This also appears to be overwriting the "seed_beans" recipe I did find in the JSON.
# Steps To Reproduce

Have Survival 2, and an unkown level of cooking (mine is 5).  
Have at least 1 "raw beans" in inventory.
Craft "raw beans" endlessly.

# Expected behavior
Raw beans as a recipe shouldn't probably exist at all in its current form.  

# Versions and configuration

 - OS: Windows 10
 - Game Version:  0.D-4736-g0f5bd17
 - Graphics version: Tiles (exists in the terminal version)
 - Mods loaded: DDA, CRIT, GardenPots, Makeshit Items, More Survival Tools, Modular Turrets, Salvaged Robots, Hydroponics, MMA, More Locations, Fuji's Buildings, Vehicle Additions, Tanks, Folding Vehicles, StatsThroughSkills, SpeedyDex

**Comment by Night-Pryanik** [comment]
We have raw beans as a "food", ready to eat, and raw beans as "seeds", ready for planting. I guess our best bet here is to rename one of them to differentiate them.
