### ISSUE TITLE
Can't see character in the dark

### ISSUE THREAD

**Issue by lmaolollmao** [CleverRaven/Cataclysm-DDA#31747]
# Describe the bug

I cannot see my character when in the dark during night.

# Steps To Reproduce

1. Make a character and enter a house.
2. Wait/Sleep till its night time.
3. Once you wake up you cannot see your character 

# Expected behavior

I should see my character

# Screenshots

![alt text](https://cdn.discordapp.com/attachments/252368751016542218/592100397364281344/unknown.png)
![alt text](https://cdn.discordapp.com/attachments/252368751016542218/592100452938678316/unknown.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4881-ge421845 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Craftable Gun Pack [craftgp],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Fast Healing [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    sees-player icon, +attitude [sees_player]
]

# Additional context

If you enter a house during the day your character is visible and if you exit a house your character is visible

**Comment by Kilvoctu** [comment]
Are you wearing eyewear with glare protection? You can't see in the dark if that's the case.

**Comment by lmaolollmao** [comment]
the problem isnt that, its that my character sprite isnt visible

**Comment by Kilvoctu** [comment]
My character sprite isn't visible when I have glare protection 2 in a very dark room, which I thought was a reasonable thing to happen.

**Comment by DemAvalon** [comment]
The thing is being actually blinded (wearing a blindfold for example) does not render one's own sprite invisible, it seems odd that not being able to see in the dark would.

This does happen, just get your eyes very encumbered (like having low perception as a prototype cyborg does this) and walk into the darkness.

**Comment by lmaolollmao** [comment]
yeah not seeing around me isnt the problem its that i cant see myself, and what DemAvalon said with the blindfold it doesnt make any sense and it didnt happen before

**Comment by KorGgenT** [comment]
this also happened when i was in the bottom of a mine.

**Comment by SomeDeadGuy** [comment]
When you at the bottom of the mine you just need to reload your helmet. Being completely blind it is how it would feel being in complete darkness. I like this change.

**Comment by YakumoChen** [comment]
From a gameplay perspective though one needs to actually know where their sprite is, it hampers the game too much especially when you can shift the game screen around and possibly lose track of where your character is.

**Comment by Brambor** [comment]
I had this problem too. The gas mask you say? Well, it isn't communicated to the player very well.
