### ISSUE TITLE
Initial Day advances evolution and food rot

### ISSUE THREAD

**Issue by Kennoot** [CleverRaven/Cataclysm-DDA#31745]
# Describe the bug

Both "Initial day" and "Spawn delay" in worldgen cause evolution and rot to advance, despite "Initial day" explicitly stating that it doesn't

# Steps To Reproduce

1. Generate a world with initial day set to a large value.
2. Food will have begun to rot and monsters will have evolved.

# Expected behavior

Quite simply, it shouldn't advance rot and evolution because it says it doesn't.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4881-ge421845 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Fast Healing [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Battery Migration for Existing Games [Battery_Overhaul_Legacy_Mode],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    Mutation Changes [Mutation_Changes],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by ZhilkinSerg** [comment]
Thanks for reporting. We already know this - see #30224.
