### ISSUE TITLE
Pipebomb explosion generates an error.

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#31756]
# Describe the bug

after a pipe bomb explodes an error window will pop up, choosing to ignore will allow me to keep playing, this does not happen all the time as the first time I did the error popped up two times in a row and later only the second bomb produced the error.

# Steps To Reproduce

1. spawn a pipe bomb and something to light it with.
2. light it and throw it.
3. (optional) take cover.

# Expected behavior

the error not showing up at all.

# Screenshots

![pipebomb error](https://user-images.githubusercontent.com/29681506/59973259-bc091400-9573-11e9-8830-494ee6e26134.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4881-ge421845 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

like I said it might not happen the first time, also don't know if this happens with other explosives.
Edit: also happened with the Mininuke, the RDX sand Bomb and the RDX Charge.

It did not happen with the grenade or nail bomb.

**Comment by eilaattwood** [comment]
... maybe we should call it "segmentation grenade" ...

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.D-8431. Closing for now, ping me if this is still an issue.
