### ISSUE TITLE
Jackhammer craft: use more types of engine

### ISSUE THREAD

**Issue by archigo** [CleverRaven/Cataclysm-DDA#31755]
**Is your feature request related to a problem? Please describe.**  
Currently, you need a [small 1-cylinder engine](http://cdda.chezzo.com/1cyl_combustion_small) to craft a jackhammer. These can only be gotten from other jackhammers, hedge trimmers or chainsaws. This is very restrictive considering all the types of small engines we have available.

**Describe the solution you'd like**  
I'd like the possible engines in the recipe to include other small engines, such as the ones found in lawnmowers and motorbikes

**Comment by archigo** [comment]
I was apparently looking on the stable branch. The lawnmower engine has already been added on experimental. I will leave it up for motorbike engines, such as the two cylinder one.

**Comment by kevingranade** [comment]
I'm pretty sure the motorcycle engines are too big to mount on a handheld jackhammer, it's possible to make such a monstrosity, but it's going to be an entirely different beast.
