### ISSUE TITLE
Nail Bomb is harmless.

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#31760]
# Describe the bug

the nail bomb is completely harmless.

# Steps To Reproduce

1. Spawn a nail bomb and something to light it.
2. Light it and drop it at your feet.
3. Marvel at its pitifulness.

# Expected behavior

it would go boom and hurt and launch shrapnel.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4881-ge421845 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

if you look at the nail bomb's description you will see that it only has 12 power at the epicenter.

**Comment by alkemann** [comment]
<img width="325" alt="Screenshot 2019-08-28 at 17 45 58" src="https://user-images.githubusercontent.com/48854/63871205-c7394f80-c9bb-11e9-8eef-e15adce989d6.png">

I activated a nail_bomb and dropped it at my feet and it killed my character instantly.

**Comment by Night-Pryanik** [comment]
Closing until re-confirmed.
