### ISSUE TITLE
Raft and kayak in boat rental are useless

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#31777]
# Describe the bug

It's impossible to pull them from the shore into the deep water (the survivor lets them go when he goes to a deep water tile), and otherwise they don't move, complaining about the lack of wheels.

# Expected behavior

It should be possible to push/pull rafts and kayaks into water that is suitable for floating.

# Versions and configuration

0.D-4881-ge4218458ba-dirty

**Comment by Night-Pryanik** [comment]
> It should be possible to push

It is. 

Tested right now - I was able to successfully push the kayak into deep water, get inside it and row away.

**Comment by l29ah** [comment]
Oh, i see, you have to orient it properly first, otherwise you climb on it instead of pushing it.

**Comment by l29ah** [comment]
[test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3318491/test.zip)
Grab the kayak and see it's not being pushed.

**Comment by Night-Pryanik** [comment]
Tested it and was able to perfectly push the kayak into the water.
![изображение](https://user-images.githubusercontent.com/11132525/59992860-e2f04480-965e-11e9-8e7c-0d3b92bfecc2.png)

**Comment by l29ah** [comment]
On Sun, Jun 23, 2019 at 10:03:40PM -0700, Anton Burmistrov wrote:
> Tested it and was able to perfectly push the kayak into the water.
> ![изображение](https://user-images.githubusercontent.com/11132525/59992860-e2f04480-965e-11e9-8e7c-0d3b92bfecc2.png)

Do you grab it and push diagonally from the place you were standing on the game load?

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Night-Pryanik** [comment]
> Do you grab it and push diagonally from the place you were standing on the game load?

Yes, exactly. After game loads, I `G`rabbed it and pushed it diagonally.

**Comment by l29ah** [comment]
On Mon, Jun 24, 2019 at 10:45:56AM -0700, Anton Burmistrov wrote:
> > Do you grab it and push diagonally from the place you were standing on the game load?
> 
> Yes, exactly. After game loads, I `G`rabbed it and pushed it diagonally.

It doesn't work for me. I'm using a terminal interface though.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments
