### ISSUE TITLE
Radiation effects too quick?

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#31774]
# Describe the bug

Possible bug... or possible feature change. Radiation as it stands now, does nothing to character's hidden health stat until it hits 200 rads. And then for each point onwards it decreases health modifier by -1 instantly. That means 1 second/turn after the character hits 300 rads (~31 irradiated) the health mods drops to -100. In response to that change the health stat drops accordingly over the span of just as few as 3 hours to corresponding minus value and will damage all body parts overtime accordingly.

This makes even Irradiated 30+ hard to deal with for ill equipped characters and 60 near unsurvivable for anyone without good stash of meds and healthy diet or Rad Scrubber.

First, I'm not sure whether such quick changes are are result of turn changes or were such to begin with - hence the bug report.

Secondly, 300 rads/3 Gy is not so high rediation exposure to warrant immediate effect on health and hitpoints. src: https://en.wikipedia.org/wiki/Absorbed_dose

# Versions and configuration

 - OS: Reproduced on Windows 7, Windows 10, Android
 - Game Version: 0.D-4674-g2e5c67a
 - Graphics version: Tiles
 - Mods loaded: [dda], [alt_map_key], [no_npc_food]

# Additional context

Proposal: make radiation sickness have more gradual effect on health with latent period dependent on severity, with slower acting Prussian Blue and Rad Scrubber CBM slow removal procedural bionic, like Leukocyte Breeder instead of instant 5 rad removal.

Edit: I realize mortality rates for these exposures are high, but this IS a game that has things like Radiation Scrubbing and mutations that consume rads and generate radiation to boot. It's impossible to follow real life accuracy in this case, but I think it's possible to strike more balance into this equation.

**Comment by nexusmrsep** [comment]
Are you sure it's rads not mSv?

**Comment by gotnoface** [comment]
It's the only unit that would make sense with those numbers, besides Sievert wouldn't even make sense. Read the article on the unit, we don't nead dose equivalent, but absorbed dose in the body.

**Comment by kevingranade** [comment]
The sudden change is an issue, but the dosage isn't in any particular units, so that's a non issue.

**Comment by gotnoface** [comment]
I see. Well I only guessed them and they alone were not an issue. But as you said, the sudden changes to health modifier really seem to need some rebalancing or an update.

Sadly I can't pull my weight in C. But some function like natural log, which would govern how severely would radiation affect health modifier over time seems like possible solution. But that may be more work than it's worth.

**Comment by kevingranade** [comment]
Mega stale issue that us pinned by being assigned.
