### ISSUE TITLE
Folding vehicle change mass in certain conditions

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#31772]
# Describe the bug

After unloading my folding cart, I fold it back up only to find that its mass is anomalously high. I can work around it in some situations, but this is still a bug.

# Steps To Reproduce
1. Create a foldable vehicle that can store things. A cart will work fine.
2. Fill the vehicle with things.
3. Unload all the things from the vehicle using AIM. Do not do anything between this step and the next.
4. Fold up the vehicle. Observe that its mass is very high.

# Expected behavior
I expect the folding vehicle to not have an anomalously high mass

# Screenshots
N/A

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4902-gdc3475c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Ants [No_Anthills],
    No Fungal Monsters [No_Fungi],
    No Rail Stations [No_Rail_Stations],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins]
]

# Additional context
If any time passes between when you finish unloading the cart and when you fold it, this bug does not occur.

**Comment by l29ah** [comment]
Yeah, i confirm that. I've created a cart, loaded it with heavy duty frames, walked around with it, unloaded it and folded it, and the folded item is insanely heavy.

**Comment by EvgenijM86** [comment]
I have encountered this today, When unfolded my cart weights 14Kg, when I folded it after a trip to town it weighted 90+kg, and when I unfolded/folded it again the bug disappeared and weighted 13.5 kg (I guess it rounds the value on the vehicle screen).
