### ISSUE TITLE
Poured item has no defined temperature

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#31775]
![image](https://user-images.githubusercontent.com/30208401/59980981-8abc3280-95cb-11e9-9b5f-a89e1b99c723.png)

This makes whatever container with liquid you pour it into become frozen.

steps to reproduce: `U`nload a container with clean water in it from the ground into a canteen you're wearing.

Pulled from latest master.

**Comment by Hirmuolio** [comment]
I can't reproduce on build 9211.

This happend on CDDA you built yourself? Can you reproduce on a build downloaded from releases or with a launcher?

I recently tested a self built CDDA I noticed a really strange bug could cause this kind of thing.
Containers on ground with food in them would never get their temperatures processed.
This only happened on the version I built and never happened on downloaded build. If the item was in inventory it would behave normally but the container on ground didn't get processed at all. I used visual studio 2019 to build.

Spawn food in container (liquid for example) and drop it instantly. Use debug mode to look at it. The item should spawn with -10 specific energy and that value should update after one turn. If the food stays at -10 specific energy then it is not getting processed for some strange reason.

**Comment by KorGgenT** [comment]
yes, this happened on a version i built with VS2019. i will try to get around to testing it on a release version then.

**Comment by KorGgenT** [comment]
ok, i'll close this as it's a duplicate.
