### ISSUE TITLE
Player Faction Camp - Farm Upgrade Completes Into Non-Functioning Farm

### ISSUE THREAD

**Issue by cosdavis** [CleverRaven/Cataclysm-DDA#31782]
# Describe the bug

For the Player's faction camp, upgrading the Farm expansion 3(?) ("we could build a something something to something additional seeds")  times results in a non-working farm upon completion of the upgrade. The Farm Expansion visually is four pits in the ground and can not take an plant/plow actions from the faction camp menu.

# Steps To Reproduce

1. Create a player faction camp
2. Add a Farm expansion
3. Plant some seeds in the first level farm. Unclear if this is a required step.
4. Upgrade the farm expansion two or three times.
5. Upon completion of an upgrade the farm remains in a non-working state with no crops or available actions, visual appearance stays in in-construction state.

# Expected behavior

Upon completion of Farm upgrades Farm remains in working condition.
v9047 Windows x64 Tiles

 - OS: Windows [64-bit]
    - OS Version: 10.0 1803
 - Game Version: 0.D-3458-gd4f4dc9
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs, Garden Pots, Makeshift Items Mods, Medieval and Historic Content, More Survival Tools, Modular Turrets, Salvaged Robots, Alternative Map Key, Urban Development, More Locations, Boats, Safe AutoDoc, Simplified Nutrition

# Additional context

Save File: https://drive.google.com/open?id=1qtiixGVjWlkQaPFjBfhZwvBXhf3rkpSF

**Comment by mlangsdorf** [comment]
It looks like the code is getting confused because you have two farm expansions.  Exploring this now.

**Comment by mlangsdorf** [comment]
Nope, that wasn't it.  Updating two farm expansions works fine.  I can see the screwed camp in the save file, but I can't reproduce it in my own testing.

**Comment by mlangsdorf** [comment]
I also can't recover any of NPCs on upgrade missions, even though I can recover the NPCs from other missions.  The entire save seems to be in really shaky shape.
