### ISSUE TITLE
Butcher times too fast

### ISSUE THREAD

**Issue by Llama3013** [CleverRaven/Cataclysm-DDA#31793]
# Describe the bug

Butcher times are too short and used to be longer. It is likely to be related to the change in issue #30018 

# Expected behavior

Butcher times to be 6 times as long.

# Screenshots

Old butcher times
![Screenshot from 2019-06-24 13-16-28](https://user-images.githubusercontent.com/51986409/59989901-59536d80-9684-11e9-9178-f553a87ab493.png)

New butcher times
![Screenshot from 2019-06-24 13-07-15](https://user-images.githubusercontent.com/51986409/59989891-4ccf1500-9684-11e9-961c-92353166d6bc.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.2 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-4902-gdc3475c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [Dark Days Ahead [dda], Disable NPC Needs [no_npc_food]]

# Additional context

I've liked being able to dissect in 7 minutes but I think that it is a bit fast and not really that realistic.

**Comment by esotericist** [comment]
For what it's worth, #31781 also fixes this, as part of reworking how stamina and butchery interact.
