### ISSUE TITLE
Bleeding broken since 6 to 1 second time change

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#31792]
# Describe the bug

Not 100% sure on this but been playing a lot of stable D recently and noticing my heli crash guy isn't losing his limbs due to bleeding like they do in unstable.

# Steps To Reproduce

1. Start heli crash
2. Lose limbs to bleeding.
3. Load up stable, repeat, do not lose limbs.

# Expected behavior

Same between D and unstable.

# Versions and configuration

 - OS: W10
 - Game Version: 9213
 - Graphics version: Tiles
 - Mods loaded: dda

**Comment by sammy202020** [comment]
yup bleeding since the 1 second update is broken. you now HAVE to carry stuff to stop bleeding if you dont want to bleed out

**Comment by Zombiemanpig** [comment]
> yup bleeding since the 1 second update is broken. you now HAVE to carry stuff to stop bleeding if you dont want to bleed out

Cause my arm bleeding will damage it till it breaks instead of drain me of blood causing completely different effects...

The time change changed the crash landed start greatly, made it much harder, should be CHALLENGE and given an extra point or something than.

**Comment by misterprimus** [comment]
Yes, bloodloss needs to be its own attribute separate from limb condition, like a second "torso" that only takes damage from bleeding, cannot be bandaged or treated directly, and is fatal just as torso damage.
