### ISSUE TITLE
Talking to NPC using weapon that take UPS power causes segfault

### ISSUE THREAD

**Issue by jmattspartacus** [CleverRaven/Cataclysm-DDA#31791]
# Describe the bug

If an NPC is equipped with a weapon that uses UPS power, and the player talks to him/her, it causes a segfault. A crash log with a stacktrace is attached below.

This corresponds to npc::decide_needs() where it is finding the ammo type, I presume because it cannot find the ammo type corresponding to UPS. I'm not familiar enough with this area of the code to fix it atm.

# Steps To Reproduce

1. Create a new character and spawn or find an NPC that can be a follower
2. Spawn a weapon that uses UPS power for ammo, and a UPS power supply (advanced UPS is easiest to replicate with)
3. Trade the UPS to them
4. Ask them to use the weapon
5. End the conversation
6. Talk to them again, produces seg fault

# Expected behavior

UPS powered weapons should be usable by NPC's the same as PC's, without causing crashes.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-4913-g275d8a7
 - Graphics version: Tiles
 - Mods loaded: Dark days ahead, Disable NPC needs

# Additional context

The crash I originally was hunting was in Cata++, but I managed to replicate this in a minimal world, so it's relevant enough to worry about.

In the attached save, the NPC already has an advanced UPS, and the player has a laser pistol to aid replication of the error.
[CDDA crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3319112/CDDA.crash.zip)
[CDDA crash save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3319115/CDDA.crash.save.zip)
[Crash with stacktrace.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3319126/Crash.with.stacktrace.zip)

**Comment by ZhilkinSerg** [comment]
I cannot reproduce the issue now, so it was probably fixed already. Please ping me to reopen if it is not.
