### ISSUE TITLE
Structure orientation leads to weird road connections

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#31797]
# Describe the bug

It's a minor, but noticeable thing:

Many buildings seem to be locked in a position facing some particular direction with no relation to their environment. It's very noticeable specially with the new version of the shelters, which while nice, have the issue of the main entrance always pointing northwards, a thing in turn leading to the connecting road snaking all around the shelter before reaching its parking lot or creating loops, knots, twists and turns even while the straight access to the building seems unobstructed.

# Steps To Reproduce

1. Start a new game on a fresh/reset map, with character starting in a shelter
2. Retry several times
3. Notice patterns

# Expected behavior

Adjustment of road generation to avoid unnecessary turns and making road-connected "wilderness" structures have a high chance of facing closest settlement or main road to avoiding the latter looping around would be nice.

# Versions and configuration

 - OS: Win 7
 - Game Version: 0.D-4923-gf26f75a (experimental build 9214)
 - Graphics version: Tiles
 - Mods loaded:   "dda", "ew_pack", "blazemod", "Tanks", "No_Fungi", "no_flaming_weapons", "StatsThroughSkills"

**Comment by ZhilkinSerg** [comment]
Evac shelter was never rotatable and was always faced north. #31616 didn't make it any worse.

Try removing `"flags":[ "NO_ROTATE" ]` from its overmap terrains and `"rotate": false` from overmap specials and it should start rotating.

**Comment by Night-Pryanik** [comment]
> Try removing "flags":[ "NO_ROTATE" ] from its overmap terrains and "rotate": false from overmap specials and it should start rotating.

I tried that, but for some weird reason stopped recognizing `shelter` overmap terrain and popped up an error on game start, so I left `NO_ROTATE` flag and didn't change `"rotate": false`.

**Comment by ZhilkinSerg** [comment]
> 
> 
> > Try removing "flags":[ "NO_ROTATE" ] from its overmap terrains and "rotate": false from overmap specials and it should start rotating.
> 
> I tried that, but for some weird reason stopped recognizing `shelter` overmap terrain and popped up an error on game start, so I left `NO_ROTATE` flag and didn't change `"rotate": false`.

Yes, I forgot one more thing - you need to add direction suffixes to overmap terrain ids in overmap special definition (see example here - https://github.com/CleverRaven/Cataclysm-DDA/pull/21211/files#diff-159a08a42909fbde9aae992dd5a86751). Usually it would be `_north`, but could be different if mapgen is drawn with a different direction.

**Comment by Night-Pryanik** [comment]
I tried that too, and it popped up another error
![изображение](https://user-images.githubusercontent.com/11132525/60015270-1ac5af00-9694-11e9-9921-45e1f1be2e95.png)

![изображение](https://user-images.githubusercontent.com/11132525/60015273-1e593600-9694-11e9-9759-20d693d43ebe.png)

**Comment by ZhilkinSerg** [comment]
> 
> 
> I tried that too, and it popped up another error
> ...

You need to remove `NO_ROTATE` flag from all overmap terrains used in overmap special definiton (i.e. `shelter_under` and `shelter_roof` too).
