### ISSUE TITLE
Player character is described as the source of the car's honking

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#31806]
# Describe the bug

Upon repeated use of a car horn attempts, a weird message appears suggesting it's the player's character that makes all the beeping noise. Also, said message ends both with an exclamtion mark and a full stop symbol.

# Steps To Reproduce

1. Start driving a functional car
2. Repeatedly activate car horn
3. Marvel at character's realistic and loud noise-making abilities rivaling those of mi-gos

# Expected behavior

Under any circumstances, the noise should be described as coming from the horn if described at all. Also, in case of the latter, it should settle for either the exclamation mark or the full stop.

# Screenshots

![beep](https://user-images.githubusercontent.com/38487938/60041180-fdf0a200-96ba-11e9-9e5f-5944f8fca8b2.png)

# Versions and configuration

 - OS: Win 7
 - Game Version: 0.D-4923-gf26f75a (experimental build 9214)
 - Graphics version: Tiles
 - Mods loaded:   "dda", "ew_pack", "blazemod", "Tanks", "No_Fungi", "no_flaming_weapons", "StatsThroughSkills"

**Comment by Fris0uman** [comment]
My bad, that's from foodperson PR #30987. Sounds of type `Alarm` that come the player's tile are described this way instead of not being described like other sound coming from the player's tile.
