### ISSUE TITLE
Reduce frequency of "high-magic" nether creatures

### ISSUE THREAD

**Issue by mark7** [CleverRaven/Cataclysm-DDA#31801]
# Describe the bug

Recently, my games have included a high rate of powerful nether creatures spawning, enough to greatly-affect gameplay.  Other players have also unhappily commented on this, as they significantly change game balance (e.g. I have a hard time playing without taking Robust Genetics with yuggs showing up frequently from the early game, as they dominate sources of mutation and are rather-harder to avoid being surprised by).  My understanding from discussion in the first link is that this was an unintentional side-effect of jsonizing nether creatures in commit 38b4022c809d83a2687a3ee8b20e0704c385216d rather than an intentional game rebalancing of spawn rates, and thus some reduction would not be controversial:

https://www.reddit.com/r/cataclysmdda/comments/bq6ujs/anyone_else_notice_the_uptick_in_nether_creatures/

https://www.reddit.com/r/cataclysmdda/comments/bqmllc/will_yugg_darts_continue_to_mutate_you/

https://discourse.cataclysmdda.org/t/no-more-yuggs-mod/20332

https://www.reddit.com/r/cataclysmdda/comments/bx768t/found_a_yugg_have_robust_genetics_and_now_im_a/

https://www.reddit.com/r/cataclysmdda/comments/bzeu3h/say_what/

https://github.com/CleverRaven/Cataclysm-DDA/issues/31594

I'd appreciate some guidance from @ZhilkinSerg, the author of the commit, as to the intent behind the commit (e.g. was your change done with the intent of making NETHER show up commonly, or to be a rare and powerful collection of monsters?  Were you happy/unhappy with the existing game balance?).

If having more creatures from the nether faction *is* desirable and was the intent of the commit, then I'd like to add some sort of weaker, "low magic" nether critters dominating the nether spawns.  Presently, my experience is that yuggs in particular show up frequently in the early game and affect the balance, but polyps are also fairly-frequent.  Historically, in the game, krecks and mi-gos were the most-common nether creatures, I'd occasionally seen a flaming eye, and I'd never seen a yugg, and I was fairly happy with this situation.  I am not very familiar with the Lovecraft works in whole, but I suppose that things like fish-men would at least be closer to "low magic" beings (at least they were described as showing up in hordes under certain conditions in his world).

From what (little) I've read in Lovecraft, much of his world is intended to be based on psychological horror.  That is, it is mood and build-up to a creature that establishes much of the flavor, and the idea that even encountering much of his fauna might drive a human to madness and is to be avoided at all costs.  The description on C'thluhu Mythos creatures in the game is in line with this -- they seem to be expected to be awe-inspiring, rarely-seen beings.  Seeing otherworldly horrors on a regular basis in the game is rather at odds with that thematically -- the creatures become mundane and unexceptional to a player.  This contrasts with zombies, which *are* generally-expected to be common in fictional worlds where they show up.

# Expected behavior

A lower rate of powerful C'thulu Mythos creatures spawning.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster); Release: 10; Codename: buster; 
- Game Version: 0.D-4919-gd5e13517a7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Mythological Replicas [nw_pack],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Hydroponics [hydroponics],
    Garden Pots [growable-pots],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Alternative Map Key [alt_map_key],
    sees-player icon, -attitude [sees_player_less_attitude],
    [DP_MOD] Indicators: Xotto [DP_XOTTO_INDICATORS],
    Classes and Scenarios Mod [more_classes_scenarios],
    Simplified Nutrition [novitamins],
    StatsThroughSkills [StatsThroughSkills],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Crazy Cataclysm [crazy_cataclysm]
]

**Comment by FulcrumA** [comment]
Regarding yuggs, I'd advocate first and foremost balancing their darts. The creature itself is okay, but the darts penetrate even light armor to cause mutation. Making it weak enough to require exposed skin or at most lightly clothed bodypart for the dart to penetrate would alleviate that particular issue.

I do agree however that in general the balance changed as it's not only yuggs but many other creatures that early game just seem out of place and cannot be countered that became now much more common. Things like flaming eyes still have no effective, even mid or late game defense against their gaze, becoming a challenge that's simply unsuitable for early game, given in how many places now they spawn. It's not always bad - sometimes said additional challenge actually adds to the enjoyment and the theme of the cataclysm, but often the randomness of the above and their effects can severely mess an otherwise succesful game with no fault on the player's part.

Stuff like that led to creation of, among other things, "no yugg" mod but it's an issue that should probably be resolved also in vanilla.

**Comment by mark7** [comment]
On the thematic side, it looks like according to:

https://en.wikipedia.org/wiki/Yugg

Yuggs are from "Out of the Ages".  There is a (copyright-infringing) PDF someone has online of this at https://thetrove.net/Books/Call%20of%20Cthulhu/Misc/The%20Xothic%20Legend%20Cycle.pdf and it provides a bit of context as to how rare and dangerous the things should be:

> At that moment, the wild-eyed man...apparently saw the thing in the surf-- and much clearer than did either of the officers.  For he staggered back with a horrible wailing screech that one of the officers, who has beenn both a prison guard at San Quentin and a security guard for an insane asylum, describes as the cry of a damned soul -- the "most horrible sound I ever heard come from a human throat," he said, swearing and pale.
>
> As the two patrolmen waded out to him, Dr. Blaine fell on his knees in the foaming surf and clapped both hands over his face, covering hiis eyes, screaming hoarsely: "God! God!  Horrible--I have seen a Yugg!  A Yugg!--Jesus--God--a Yugg!--God--Ia!  Zoth-Ommog!--cf'ayak ghaaa yrrl'th tho-Yuggya!  Yaaaaaa-n'gh--"...The police closed with him and grappled with him; he reportedly made no resistance, but was so shaken with uncontrollable spasms of trembling that he could not stand and had to be carried to the patrol car...Dr. Blaine then collapsed in utter exhaustion and was admitted to Mercy Hospital Psychiatric Emergency Ward at 3 o'clock in the morning.  He has been there now for two months; in all that time he has not spoken a single word, except for a gobbling sound he repeats over and over, which sounds like "Yugg--Yugg-Yugg!"
>
> He is now kept under forcible restraint for his own protection.

That is, if one is to follow C'thulhu Mythos canon, even a brief, clear glimpse at night glimpse of part of a Yugg is supposedly enough to render a person essentially incapable of doing anything, to be rendered mostly-incomprehensible, to go into spasms, and to be permanently driven insane.  The player's character is supposed to be more-or-less an ordinary Joe, and clubbing the things to death on a regular basis does seem like a bit of a stretch.

**Comment by gotnoface** [comment]
I happen upon yuggs or multiple eyes regularly nowadays, usually in first two weeks of any character I start. Not sure how frequent it was in the past, since I came back to CDDA just a few months ago after many years.

On another note, is it normal that eyes flash you ever 12 seconds? Yugg darts and grabs also seem more frequent. Is this another fragment of turn=1 second update?

**Comment by mark7** [comment]
The grabs are unrelated, and I believe part of a separate and I believe rebalancing; I'd prefer to not address that in this issue.  For your benefit, you can no longer be bitten (and infected) unless grabbed, but grabs are more-common.  The game does not make this mechanic particularly clear at the moment.

**Comment by ZhilkinSerg** [comment]
That commit has nothing to do with balance - it was just unhardcoding. Update monster groups if you see spawns were changed compared to a previous state.

**Comment by mark7** [comment]
@ZhilkinSerg: Thanks, much obliged.

**Comment by mark7** [comment]
Okay, at this point, I'm gonna aim to just produce the pre-commit spawn behavior.  @gotnoface, you probably want to take your gameplay questions to the forum at https://www.reddit.com/r/cataclysmdda and @FulcrumA I'm gonna hold off on a revamp of the nether faction, since I think that that's probably out-of-scope for this (my aim here is just to retain the pre-commit game playability).  That might be a valid separate balance issue to open.
