### ISSUE TITLE
Magiclysm no damage to zombies with elemental spells.

### ISSUE THREAD

**Issue by DatBandy** [CleverRaven/Cataclysm-DDA#31822]
So for some reason my spells, that deal elemental damage, don't damage zombies at all. They deal proper damage to NPC, but zombies aren't even shown in combat logs. Tested with multiple characters, with spellcraft and spell levels ranging from 0 to 20. The only time I was able to deal damage with burning hands, is with one character lvl 2 spellcraft and lvl 0 burning hands. But after dealing damage my spell immediately leveled up and after that - 0 damage. When my character is 20/20 spells have 0% chance to fail. I also don't loose concentration. Lvl 20 burning hands deal ~60 dmg to any geared survivor, so I don't believe, that crawling zombie has that hight resistance. Tested with 10 different spells. Physical spells (smite etc) seems to be working fine. Game itself is of a latest build. Tested on 2 different devices.

1. Make a character of any kind
2. Learn any elemental spell
3. Try casting it on zombies for no damage
![Screenshot_20190625-085839](https://user-images.githubusercontent.com/52183665/60061666-55355780-9739-11e9-9cb2-234cc54ba0fd.png)

Expected behavior
Elemental spells should deal damage to zombies.

Versions and configuration

 - OS: Android 
    - OS Version: Manufacturer: Huawei; Model: Honor 8x; Release: 8.2;
 - OS: Android
    - OS Version: Manufacturer: motorola; Model: Moto G (4); Release: 7.0; Incremental: 3; 
- Game Version: 0.D-4923-gf26f75a [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Disable NPC Needs [no_npc_food],
    Sleep Deprivation [sleepdeprivation],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/60061958-35644c00-96c5-11e9-97ac-dc69a77e7043.png)

**Comment by KorGgenT** [comment]
are you just reporting that the message isn't happening? is there an obstruction between the epicenter and the target?

**Comment by DatBandy** [comment]
Okay I spent a few hours yesterday testing it. Did it on an open field. Message is not an issue, zombies simply don't take any damage. I spent 6000 mana on fire hands in total at lvl 20/20. After that a standard zombie still was at full health. Similar with other spells of elemental damage.

**Comment by KorGgenT** [comment]
![burning hands](https://user-images.githubusercontent.com/30208401/60062476-575ece00-96c7-11e9-8721-aa088ef98a24.gif)

**Comment by DatBandy** [comment]
Okay, just updated game. Unfortunately can't record proper video from phone, but here is the same situation.
![Screenshot_20190625-093300](https://user-images.githubusercontent.com/52183665/60063064-1d74e280-972e-11e9-9677-7314062be82f.png)
![Screenshot_20190625-093253](https://user-images.githubusercontent.com/52183665/60063065-1e0d7900-972e-11e9-8d16-35e1c3724212.png)
![Screenshot_20190625-093222](https://user-images.githubusercontent.com/52183665/60063066-1e0d7900-972e-11e9-9b87-875e8bd6a112.png)

**Comment by KorGgenT** [comment]
could you try it with only magiclysm in order to test it please? maybe it has something to do with android or something

**Comment by DatBandy** [comment]
Did that, created new world, new character. Ice spells deal damage now. Fire and acid still don't

**Comment by ZhilkinSerg** [comment]
Works fine for me now - zombies are getting damaged. Please ping me if it still not working for you on latest version.
