### ISSUE TITLE
Make DETONATE death_function clearer

### ISSUE THREAD

**Issue by mark7** [CleverRaven/Cataclysm-DDA#31829]
**Is your feature request related to a problem? Please describe.**  
Currently, zombie grenadiers and other monsters with the DETONATE death_function arm their remaining explosives when they die.

Neat mechanic, but it's not necessarily clear to the player that this is actually what's happening when it happens ("The %s's hands fly to its remaining pockets, opening them!"), which means that it essentially requires a stupid death (at least) to figure out what the message means.

A player just complained about this behavior at https://www.reddit.com/r/cataclysmdda/comments/c4yo9g/im_not_playing_cdda_blind_anymore/ and it seems like a reasonable point to me.

I'll put up a PR shortly.

**Describe the solution you'd like**  
Update the death message to indicate that explosives are being armed.

**Comment by anothersimulacrum** [comment]
Both the monsters with this death function are obsolete (they shouldn't spawn), and replaced with robots. I do not think this is an issue anymore.

**Comment by mark7** [comment]
Ah, thanks, you're right.
