### ISSUE TITLE
Option for Picking up items with 'e'xamine menu to show on the right as it used to

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#31828]
**Is your feature request related to a problem? Please describe.**  
I simply find the current system very awkward to use vs what it used to be in regards to information processing, ease of reading.
Maybe I find it wastes space on the left when it can just replace the right panel while I'm in the menu?

**Describe the solution you'd like**  
A simple option for things to default to the right sidebar instead of creating a new space on the left for ease of information processing, less screen clutter, just as it used to work.

**Describe alternatives you've considered**  
Being distracted by the screen  clutter on the existing method

**Additional context**  
I don't really expect anyone to care all that much, but anyone that implements this would have my eternal gratitude!

**Comment by anothersimulacrum** [comment]
Duplicate of #29415

**Comment by dissociativity** [comment]
my bad
