### ISSUE TITLE
Damage from poison damages bandages

### ISSUE THREAD

**Issue by hdggDalton** [CleverRaven/Cataclysm-DDA#31825]
# Describe the bug
While poisoned, I expect to take some damage, but one time when it damaged me a message popped up saying "bandages on your torso were damaged!" It even degraded the bandage quality from average to poor. I was sewing in the refugee center so I was completely safe.

# Steps To Reproduce

1. Make a player with bandages
2. Open debug menu and hurt your torso a little bit
3. Apply bandages to torso
4. If you can debug poison, do it, otherwise just chug down unclean water until you get poisoned (not just food poisoned, the kind of poison that does dmg)
5. Wait, if it doesn't happen repeat steps 4-5 until it does

# Expected behavior
Poison is internal damage so it shouldn't tear your bandages like a zombie would

# Screenshots
character sheet
![poisband1](https://user-images.githubusercontent.com/30754603/60064559-ab60b700-96b5-11e9-90c1-9a9cb7d0db00.PNG)
message log
![poisband2](https://user-images.githubusercontent.com/30754603/60064560-abf94d80-96b5-11e9-858f-ed2e5d4406d3.PNG)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-4123-g37a6167 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    StatsThroughSkills [StatsThroughSkills],
    No Filthy Clothing [no_filthy_clothing]
]

# Additional context
I modded the game a little bit to make ordinary things like toasters and lawnmowers deal ludicrous amounts of damage, but that has nothing to do with poison or bandages

**Comment by TechyBen** [comment]
Bandages also do health though, and would heal the poison "damage". So we do have a conflict here so it might be more complex than just preventing bandages getting damaged?

**Comment by kevingranade** [comment]
We do, but it's a pervasive problem of dealing with HP as an abstract
aggregate instead of a list of individual wounds.

**Comment by Night-Pryanik** [comment]
Your version is REALLY old. Have you tried this on latest experimental? #31328 should have fixed this.

**Comment by Leland** [comment]
Closing per above, @hdggDalton, try testing on a newer experimental and if this is still around, @ one of us on this thread to reopen. Thanks!
