### ISSUE TITLE
Certain Lab Consoles Failing to Open Doors

### ISSUE THREAD

**Issue by Noodleboom** [CleverRaven/Cataclysm-DDA#31833]
# Describe the bug

Specific consoles are not opening their attached metal shutters in labs on a successful hack, despite displaying the success message. They do produce penalties on a failed hack (console shutdown, electric shock, releasing bots). 

So far I've had this issue with the following consoles:
- Magazine access (barracks work as expected)
- Bionic storage rooms (the small rooms with six display shelves, console with a manifest)
- Mutagen storage room (as above)

The following consoles are working as expected:
- Barracks
- prison access
- prisoner release
- autodoc access
- autodec cell release

# Steps To Reproduce

1. Spawn into a lab with high computer skill
2. Successfully hack the above-listed consoles
3. The console displays a success message
4. However, the metal doors remain closed and locked

# Expected behavior

The doors open, as the successful hack indicates.

# Screenshots

![Hacked console](https://user-images.githubusercontent.com/28692644/60086439-4c706180-96f8-11e9-98e0-30f95b6d7cad.png)

![Closed shutters](https://user-images.githubusercontent.com/28692644/60086603-9f4a1900-96f8-11e9-852a-d6cb757f1f3e.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4929-gdd1dfac [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Azumgi** [comment]
Tried 2 labs with 30 computers skill. Hacked every single computer. Could not reproduce

**Comment by davidpwbrown** [comment]
Tested lots of labs - magazine access and mutagen and bionic access correctly opened doors ona  succesfull hack
Can not reproduce.
