### ISSUE TITLE
Lost target item of ACT_MOVE_ITEMS

### ISSUE THREAD

**Issue by ProfoundDarkness** [CleverRaven/Cataclysm-DDA#31839]
# Describe the bug

When moving *some* corpses via dragging items I get the following:

An error has occurred!  Written below is the error report:
DEBUG: Lost target item of ACT_MOVE_ITEMS
FUNCTION: void move_items(player&, const tripoint&, bool, std::vector<item_location>&, std::vector<int>&)
FILE: src/activity_item_handling.cpp
LINE: 694

Additionally the corpse is not moved.

# Steps To Reproduce

1. Create a new character on build 9219, preferably one that is set out of the gate for combat.
2. Spawn in a Zombie Dog nearby.
3. Kill it.
4. Try to drag it's corpse.

# Expected behavior

I expect the corpse to be shifted from where the character was to where the character now is just like every other item (and corpse) I've encountered while dragging.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-4963-g3eec9d8 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I hadn't encountered a zombie dog in an older (0.D experimental) version as yet so I don't have any reference for when this might have cropped in.

I haven't done a lot of item dragging since updating so I don't know if anything else triggers the error.  Some last second testing suggests this might not be restricted to zombie dog corpses.  I loaded up my regular game and went to drag a zombie screamer corpse and got the error, interestingly I did NOT get the error for the zombie dog corpse.  Out of curiosity I loaded up the save attached and still got the error while dragging.

Even though this is really easy to recreate with a new game, here's a log and save zip.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3325649/save.zip)

(Edit)I goofed around for a while in my regular game and found one other item which wouldn't move, a plastic bottle of cream soda.  Additionally if I picked up (going to inventory or going to wielded) and then set down to the same place or elsewhere I became able to drag the items.  At least the tests I did with new characters was/still is darned consistent or I'd be looking at deleting this issue.(/edit)

**Comment by Lerzan** [comment]
I've had other objects with the same issue, and I can't really tell a pattern. I wanted to move some corpses out and halfway to the door one out of 3 regular zombie corpses suddenly wouldn't haul. I also had the issue with some beavers, and after the error hit I couldn't butcher them either, saying there was no corpse to butcher.

**Comment by ProfoundDarkness** [comment]
Just before stopping for the day (messing with another issue) I noticed this come up when using move all in advanced inventory.  There generally seems to be one item in a stack that won't move.

**Comment by maxestorr** [comment]
I'm on build 9220, I deconstructed the water tank on the evac shelter's roof, took a 60L tank and filled it with water, when I attempted to drag the filled 60L tank I get the same error and after continuing my character stops dragging.

**Comment by jbytheway** [comment]
@ifreund has found a probable cause of this related to an interaction of #31796 with active item processing.
