### ISSUE TITLE
Acid type zombie JSON update.

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#31835]
Mods active:
No acid zombies

### Expected behavior
No acid Zombies

### Actual behavior
Military acid zombies appear

### Steps to reproduce the behavior
Play with No acid zombies, roam around.

No acid zombies mod currently works by blacklisting individual monsters by name. Recent expansions to add soldier based acid zombies (and perhaps others) mean it would need updating as and when.

Suggestion; add some type of "ACID" flag to monster Json. Could future proof for other things. Then switch No acid zombies to blacklisting by flag. Could also add No acid anthill spawning to this mod.

**Comment by FirebrandCoding** [comment]
There are multiple problems with blacklist mods in the current *Cataclysm*. I had the issue addressed [on the forum](https://discourse.cataclysmdda.org/t/mods-and-respect-setting-parameter/20084), with a proposal for future-proofing the game not unlike your own.
