### ISSUE TITLE
<vehicle's tires> runs over something spam

### ISSUE THREAD

**Issue by ProfoundDarkness** [CleverRaven/Cataclysm-DDA#31836]
# Describe the bug

Every time I move my cart via (G)rab I get 'The Storage Cart's 4" casters runs over something.'

Also get similar spam (per tire) from the Armored Car I found, ie:
'The Armored Car's 32" armored wheel runs over something.'

# Steps To Reproduce

1. Spawn a dragable vehicle
2. Move the dragable vehicle around.

NOTE: Steps were generated using [New Game] [Play Now! (Fixed Scenario)].
(Technically can also test with a vehicle that you can drive but a dragable vehicle is something you can do on the first turn.)

# Expected behavior

NOT getting said message spam when moving a vehicle, except perhaps if rolling over an actual trap.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-4963-g3eec9d8 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Filthy Clothing [filthy_morale],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins]
]

# Additional context

Encountered this after updating from build 9208 to 9219.

As a test I remarked out the following section and recompiled, no more message spam.  Though I suspect that isn't the proper fix for this.

https://github.com/CleverRaven/Cataclysm-DDA/blob/3eec9d8b2a4f50ee5323d1941f9f1ea7a0007d38/src/vehicle_move.cpp#L813-L820

**Comment by IvanShestakov** [comment]
Seeing that message as well.
GAME REPORT: 
- OS: Linux
    - OS Version: Distributor ID: LinuxMint; Description: Linux Mint 18.3 Sylvia; Release: 18.3; Codename: sylvia; 
- Game Version: 0.D-4518-g4563cc4-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    Mutant NPCs [mutant_npcs],
    Folding Parts pack [deoxymod]
]

**Comment by Canivir** [comment]
Happens to me as well. In fact, it happened to me while trying to replicate another bug, so I have a savefile around in case it is needed and the bug isn't happening to everyone. It does happen even with no mods on as well.
[Test.World.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3327527/Test.World.zip)

 - OS: Win 7
 - Game Version: 0.D-4964-ga26ac8d
 - Graphics version: Tiles
 - Mods loaded: None

**Comment by SleeperJack** [comment]
Im having this issue with driving any vehicle.
