### ISSUE TITLE
Eliminate excess CPU usage due to unnecessary wakeups on the main menu

### ISSUE THREAD

**Issue by mark7** [CleverRaven/Cataclysm-DDA#31847]
**Is your feature request related to a problem? Please describe.**  
Presently, Cataclysm uses CPU time while idling on the main menu.  There's no reason for Cataclysm to be doing any work at all on the main menu other than in response to a keystroke/window resize or playing background music, if that is enabled.

This should hopefully be the first in a series of PR's I'm putting in to reduce Cataclysm's CPU usage (and hence battery usage on portable devices, like laptops and Android devices).

See #22375 for some existing related discussion.

**Describe the solution you'd like**  
* If background music is silent, Cataclysm does not wake up at all on the main menu.
* If background music is enabled, Cataclysm only wakes up to play music and does not repaint the screen.

Closing this issue should entail that, at least:

* Cataclysm should properly paint the title screen before going to sleep waiting for key events (it doesn't, currently, as it requires a timeout and finishes redrawing on that today)

* Should properly paint the title screen on window resize without waiting for another wakeup (I vaguely recall looking into this some time back and I don't think that it did that, though I may be misremembering).  Note that there are also some graphical issues with resizing/redrawing; I don't intend to address all of those.  Just the ones that require a timeout to repair themselves.

* Timeouts for the main menu code should be set to 0 (off).

* Should properly paint the title screen on keypress without waiting for another wakeup.  As far as I know, this works fine today, but it should be checked-for.

**Additional context**  

#30654 is similar to this (and, really, the only reason I'm filing a new bug rather than asking for that one to be reopened is because I want to be able to work on this and edit the bug, and I want to be more-specific in what I intend to accomplish).  I think that that one was probably closed in the erroneous belief that #22375 fully-overlapped it.  The wakeups on the main menu are really independent of the wakeups in the game world (main_menu::handle_input_timeout()).  It's true that the expensive redraws are probably something of a shared issue between the main menu and in-game environment, but the issue I'm filing now will not attempt to decrease redraw cost, but merely the number of redraws that occur; it will not touch the portion of #22375 that overlaps.

**Comment by Night-Pryanik** [comment]
I'm closing this for now, on 0.F-10563 on my rig in idle mode the game consumes ~1.5% of CPU, I think that's negligible. If this is still an issue, ping me to reopen.
