### ISSUE TITLE
Not able to butcher corpse

### ISSUE THREAD

**Issue by roaringjohn** [CleverRaven/Cataclysm-DDA#31840]
# Describe the bug

When going to butcher a corpse that is stood on, the full time of the butchering is used, but returns that no corpse is available to butcher.

# Steps To Reproduce

1. Stand over corpse
2. Try to butcher or dissect

# Expected behavior

Once you go to butcher, it should butcher the corpse you're standing on.

# Additional context

I haven't gotten the chance to see this bug, but multiple others have, and yet there's not an issue for it. Until I experience the bug, I won't have any more information.

**Comment by BenlyAZ** [comment]
Additionally, it returns the message "There's no corpse to butcher!" after the butchering time has passed. Corpses also can't be dragged using \ which may or may not be related.

**Comment by IvanShestakov** [comment]
I'm having the same issue here.

GAME REPORT: 
- OS: Linux
    - OS Version: Distributor ID: LinuxMint; Description: Linux Mint 18.3 Sylvia; Release: 18.3; Codename: sylvia; 
- Game Version: 0.D-4963-g3eec9d8 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Mutant NPCs [mutant_npcs],
    Folding Parts pack [deoxymod]
]

**Comment by berangus** [comment]
Just checking in to say I also have this issue. I'm in a lab currently, and from my limited ability to test it seems to happen somewhat randomly, and also seems like mostly CBM-containing enemies have this problem (although that might just be coincidence as those are mostly the ones I attempt to butcher).

I got "There's no corpse there to butcher!" first when trying to dissect a zombie shocker, and later on a couple zombie scientists. In one case, a save-and-quit and reload let me dissect a scientist that I previously couldn't. I have successfully "quick butchery'd" a zombie grabber, and also successfully dissected a zombie screecher (even yielding a pheromone).

Also worth noting that the most recent zombie scientist I was unable to dissect, currently has a Soporific Induction CBM on the tile with his corpse. I didn't notice if that was there before I tried to dissect or not.

GAME REPORT:

- OS: Windows 7 Ultimate 64-bit
- OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-4963-g3eec9d8 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    StatsThroughSkills [StatsThroughSkills],
    Magiclysm [magiclysm],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Mythological Replicas [nw_pack]
]
![butchery bug](https://user-images.githubusercontent.com/51548372/60130717-ca1e8680-9765-11e9-9563-3fb854f1fe24.PNG)

**Comment by jagoly** [comment]
this doesn't seem to happen if you move the corpse onto a tile with no other items before butchering, so that's a temporary workaround until this is fixed

**Comment by berangus** [comment]
> this doesn't seem to happen if you move the corpse onto a tile with no other items before butchering, so that's a temporary workaround until this is fixed

I just tested this and I was still unable to dissect a zombie scientist after moving the corpse onto its own tile with no other items. Workaround not confirmed :(

**Comment by ifreund** [comment]
The rework of active item processing to use `safe_reference` after #31796 should fix this as well.
