### ISSUE TITLE
Lost target item of ACT_DROP

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#31846]
# Describe the bug

After updating from experimental build 9218 to 9219 and continuing saved game, I regularly stumble upon the error in the title, at random and inconsistently when picking up items. Details below. 

# Steps To Reproduce

1. Examine a tile with several items lying on it.
2. Select several items.
3. Confirm to attempt to pick them up.

# Expected behavior

Picking up items works without errors.

# Versions and configuration

- OS: Win 7
 - Game Version: 0.D-4963-g3eec9d8 (experimental build 9219)
 - Graphics version: Tiles
 - Mods loaded:   "dda", "ew_pack", "blazemod", "Tanks", "No_Fungi", "no_flaming_weapons", "StatsThroughSkills"

# Additional context

Error message:
 DEBUG    : lost target item of ACT_DROP
 FUNCTION : bool Pickup::do_pickup(std::vector<item_location>&, std::vector<int>&, bool)
 FILE     : src/pickup.cpp
 LINE     : 320

Debug log file:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3326676/debug.log)

**Comment by SleeperJack** [comment]
I've had similar error when hauling items as well. I think it is primarily with perishable items when it changes between frozen and unfrozen, or does one of the checks for it.

**Comment by jbytheway** [comment]
@ifreund has found a probable cause of this related to an interaction of #31796 with active item processing.
