### ISSUE TITLE
Corpse won't stay in coffin when sealed

### ISSUE THREAD

**Issue by ProfoundDarkness** [CleverRaven/Cataclysm-DDA#31848]
# Describe the bug

After constructing a coffin and dropping a corpse in it I then seal the coffin.
When the construction task is complete the corpse is now sitting beside the coffin.

# Steps To Reproduce

1. Make a player with enough skill to create a corpse from an NPC or something like a dog (neutral creature).
2. Spawn in a creature/NPC if one isn't readily available.
3. Kill the creature/NPC.
4. Wish for enough resources and tools to build and seal a coffin.
5. Build the coffin.
6. Drop the corpse into the tile where the coffin was constructed.
7. Choose to seal the coffin.

# Expected behavior

Corpse stays in the coffin after being sealed... or corpse is deleted, same thing from user perspective.  Basically that the corpse/other stuff I just put in the coffin before sealing isn't sitting next to the now sealed coffin.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-4963-g3eec9d8 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Most of my testing involved a neutral dog creature but it also happened with NPC corpses.

I was able at one point to get the coffin to seal with a corpse by placing a random cell phone from a previous scavenging run into the coffin with the dog corpse.  I wasn't able to repeat this with any reliability though and was one test in about 10 attempts of varying things a little.

Included a save which should just require picking up and putting the corpse down into the casket then doing the seal casket construction.  I say should as I don't know what it was that allowed it to work one time in multiple tests.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3326968/save.zip)

Slightly aside, I thought from reading the PR that added coffins that the contents were supposed to be kept yet the one time the items didn't get pushed to one side on sealing the coffin, when I opened the coffin back up (crowbar) there was nothing inside.  Granted I didn't get very far into that PR so not sure if that functionality ever made it in.

**Comment by davidpwbrown** [comment]
THis is due to the unfinished construction task, which because items can somehow find their way onto the construction site, when the construction is finished, it pushes them to the side incase the finished construction is one where items cannot reside there.

I didn't think of coffins and the fact they are designed around having an item inside.

I can add an exception to this, but a more elegant solution may need to be found.

**Comment by snipercup** [comment]
Reading davidpwbrown's comment this might explain why firewood is moved when constructing a firewood source on top of a pile of firewood (or anything). I would expect the firewood to stay but I don't know if this will be an issue for other construction recipes.

**Comment by davidpwbrown** [comment]
> Reading davidpwbrown's comment this might explain why firewood is moved when constructing a firewood source on top of a pile of firewood (or anything). I would expect the firewood to stay but I don't know if this will be an issue for other construction recipes.

Yep, thatd be the same thing. I'll have to enumerate certain constructions as being ones that are "item-on-tile" friendly, and ones that arent I guess, but firewood  spot and crafting spot and target practice spot should probably use the zone system rather than a construction.

**Comment by ProfoundDarkness** [comment]
It might not be the right approach but why not a flag?
If this flag is present on a construction, don't move the items out of the way.
A flag seems like a better approach than specific task checking. (though maybe not best.)
I'm gonna play with the idea...

**Comment by ProfoundDarkness** [comment]
I guess the flag idea was acceptable, the PR submitted/merged allows the corpse to stay on the construction tile and when the coffin is re-opened the corpse is still present.  Also other construction tasks still move items off the tile as expected.

Gonna close this since it appears to be fixed.
