### ISSUE TITLE
Question on new martial arts

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#3185]
Just read over the commits for the new martial arts system and was just wondering, how do you actually learn them in game?  It removes the starting traits to get them, and NPCs are still too buggy to be an option.  I'd rather not go back to the situation where debug is the only way to access martial arts.  Can't we bring the starting traits back?

**Comment by qbradq** [comment]
As this was a question that has been sufficiently answered, please close.
