### ISSUE TITLE
Segfault crash when trying to repair a moving vehicle

### ISSUE THREAD

**Issue by Canivir** [CleverRaven/Cataclysm-DDA#31854]
# Describe the bug

When trying to use repair to find the most damaged part in a moving Vehicle while no part is damaged on the tile currently in view, a crash occurs and a Segfault error message appears.

# Steps To Reproduce

1. Create a new Character.
2. Spawn any vehicle (I used a Bus and a Limousine for testing).
3. Get said vehicle moving.
5. While it is moving, examine the vehicle to enter the vehicle view.
6. Make sure the tile you're looking at has no damaged (repairable) part, and hit repair.
7. You should now have crashed.

# Expected behavior

Hitting repair while in a moving vehicle should behave the same way as when the vehicle is stationary. I.e. not crash.

# Screenshots

# Versions and configuration

 - OS: Win 7
 - Game Version: 0.D-4964-ga26ac8d
 - Graphics version: Tiles
 - Mods loaded: None

# Additional context

When you hit repair in a moving vehicle while a part under the cursor is damaged, the bug seems to be fixed for that vehicle. It still occurs with a new vehicle, however.
It also does not seem to matter if the engine is currently running or if you're currently controlling the vehicle.
Whether there even is a damaged part on the vehicle also does not seem to matter.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3327498/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3327499/debug.log)
The debug log seems to have a bunch of the crash in it, some with mods, some without, which accumulated when I was trying to pin down the bug.

[Test World.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3327500/Test.World.zip)
This is setup so you can just hit examine vehicle and hit repair in order to crash.

**Comment by Canivir** [comment]
On another note, the test world savefile also exhibits the bug https://github.com/CleverRaven/Cataclysm-DDA/issues/31836. So everytime the vehicle moves a space I get the message that I ran something over.

**Comment by brannamm** [comment]
Doesn't trying to examine a moving vehicle just give you a warning dialog that you can't do that in 0.D? If so, the only bug might be that the dialog isn't showing properly.
