### ISSUE TITLE
Zombies attacking fish fill ponds 

### ISSUE THREAD

**Issue by EricFedrowisch** [CleverRaven/Cataclysm-DDA#31853]
# Describe the bug

Zombies chase fish but can't move through water well. The result is that a single fish in a pond will lure all zombies in sight and trap them in the water. 

# Steps To Reproduce

1. Go to a pond.
2. Hide so enemies won't target you.
3. Wish up a fish or zombies as needed.
4. Watch zombie sink in pond chasing fish.

# Expected behavior

This seems like an edge case more than a bug. Zombies should chase neutral creatures. Zombies should chase creatures in the water. Maybe fish are too obvious in the water currently. From far away many fish just look like glints of metal in murky water. This may not be an obvious sign of life for unthinking creatures. I would expect zombies to either ignore fish or attack only fish that are within a few spaces because at that range it becomes more obvious that the fish is alive.

# Screenshots

![LakeZs](https://user-images.githubusercontent.com/5952322/60138667-0949d900-9760-11e9-8a1d-19050156d333.png)

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14.5; Build: 18F203; 
- Game Version: 0.C-42408-g044439e888 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Filthy Clothing [filthy_morale],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    Necromancy [necromancy],
    Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    Boats [boats],
    Aftershock [aftershock],
    Garden Pots [growable-pots],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct]
]

**Comment by misterprimus** [comment]
Might make sense to have the range at which zeds start chasing be based on several factors, like creature size. Otherwise you'll have 100 zeds chasing a fly.

**Comment by EricFedrowisch** [comment]
Good point @misterprimus. The size of the animal being chased should influence how much effort zombies would put into catching it. A dog might be worth chasing but a fly or lizard probably isn't worth the effort.

**Comment by FulcrumA** [comment]
Arguably zombies should ignore smallest of fauna in general since it doesn't have enough mass to really work well infected. By comparison, zombies ignoring huge spiders and cockroaches is kinda weird.

**Comment by Zireael07** [comment]
IMHO zombies other than swimmers ought to ignore aquatic creatures, for the same reason.

**Comment by nexusmrsep** [comment]
With the reasonable exclusion for zombified aquatic life like zombie sharks, zombeavers etc.
