### ISSUE TITLE
Support directed explosions

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#31862]
**Is your feature request related to a problem? Please describe.**  
Currently the explosion code only supports undirected spherical explosions.

**Describe the solution you'd like**  
Explosion code should be modified to support directed explosions. These should resemble a circle sector with angle defined in the explosive item's definition and the direction specified by the player when the charge is placed. This would allow for shaped charges and claymores and such which would open up some interesting options for the player.

**Comment by kevingranade** [comment]
This is roughly the same solution as #12182

**Comment by ymber** [comment]
#28766 related.
