### ISSUE TITLE
Game crashed during an autosave

### ISSUE THREAD

**Issue by Table99King** [CleverRaven/Cataclysm-DDA#31874]
# Description:

Game crashed during an autosave 

# Steps To Reproduce:

1. Wait for an autosave 

# Expected behavior

Autosave without a game crash 

# Versions and configuration

 - OS: Windows 10
 - Game Version:  0.D-4979-g6a0f1c8
 - Graphics version: Tiles x64
 - Mods loaded: Dark Days Ahead, disable npc needs.

# Additional context

[CrashDebugLogs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3330013/CrashDebugLogs.zip)
[SaveBeforeCrash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3330015/SaveBeforeCrash.zip)
[SaveAfterCrash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3330016/SaveAfterCrash.zip)

**Comment by IvanShestakov** [comment]
Could be a manifest of what I've described in #31960 ?

**Comment by Table99King** [comment]
> Could be a manifest of what I've described in #31960 ?

Yes, it happened to me during normal quicksaves

**Comment by int-ua** [comment]
#32358
