### ISSUE TITLE
Possibility of some instant healing items or healing options? [Feature Request]

### ISSUE THREAD

**Issue by TechyBen** [CleverRaven/Cataclysm-DDA#31871]
**Is your feature request related to a problem? Please describe.**  
Some players like the idea of having the ability to heal quicker. This is not unreasonable in a gameplay perspective. Some players like a consistent risk/reward cycle. In the likes of FPS games, this is 30 or so seconds (Halo for example is a perfect example where levels where the flow is good, and levels where it is poor... cough *flood hallways* cough... are clear).

CDDA is very flexible, and has many different play styles. It can be played well, with slow and waiting gameplay. But some now feel the quicker style is suffering.

Would a healing item or two, help balance this out? How would we balance out that effect, while also allowing the slower more planned style of gameplay?

**Describe the solution you'd like**  
A healing item that also has drawbacks. This would hopefully allow quicker gameplay for some players, but have a limiting factor or a resulting risk/debuff.

And example of this could be:

> Blob Globs can now offer faster healing for short times if eaten. The have a large moral debuff. They risk a bad mutation.

Players could then decide, "do I rest up, and heal easily but slowly, or eat this glob to heal quicker, but risk needing to find purifier." Or alternatively, other types of risk (nausea etc) could be applied (guaranteed or percentage based).

**Describe alternatives you've considered**  
There is already the option to mod this, or have healing rate as a setting (traits exist etc). Adding new items would need new balancing. So there is that problem.

Another alternative could be having healing options with NPCs/camps. "Rest at the camp until healed" would advance time automatically (jump? and not slow calculated?) to you healed. The NPCs would give you the food/protection during this time. To the player/gamer, it would be "instant heal", but in the game world, the correct timescales would have passed. This would allow a faster *feeling* gameplay style, while also keeping the current realistic rates and simulations. :)

**Additional context**  
The comments on Reddit etc, seem to suggest that it's the slowing down/prevention of some gameplay styles that worries people. Not the healing rate. They would like to continue to search through a town/lab/area, without making the character rest for days. So brainstorming how to allow a faster paced style gameplay.

[Edited paragraph order]

**Comment by Zireael07** [comment]
"Rest at the camp until healed" actually sounds like an excellent idea.

**Comment by glenmack** [comment]
The problem with speeding up the game-play by resting until healed is that it negates the penalty of taking damage ENTIRELY. I don't particularly like the recuperation, but the fact that taking damage really means something should be held onto.

IF an instant heal should be implemented, it should involve USB medisoft and an autodoc. Probably a small amount of first aid skill and a chance of failure, not death but a less effective heal. It should also probably put the autodoc out of commission. For RP purposes the 8 hour operation fries the autodoc or something. But with 6+ first aid it's a 100% overnight heal.

To be honest if you can train up first aid, and you actually make medicine and heal before bed the heal times aren't currently that bad and it actually gives another good reason to learn first aid, besides dissection.

**Comment by TechyBen** [comment]
> The problem with speeding up the game-play by resting until healed is that it negates the penalty of taking damage ENTIRELY. I don't particularly like the recuperation, but the fact that taking damage really means something should be held onto.

Thanks, can you explain it to me more broadly? Currently, you can run to a NPC camp and rest at that location and heal. Right? Would adding an option to timeskip the part some players find boring change the risk reward negatively? Thinking a little more about the option of NPC camps "rest until healed", I wondered about adding requirements for morale actions etc. Like each day requiring talking to NPCs/doctor/reading books to regain morale points. It would add things to do between "waiting" and watching a HP bar increase.

Basically, adding tasks a player can do between "fights" if their HP is low, and they cannot fight as much. Currently I have no personal worry about crafting/sneaking the 5 days or more to heal up in game. But also do understand it as a gameplay roadblock to some extent. NPC camps has added a lot of nice varied content, that hopefully other systems can pull from and benefit from too. :)

I also would see the "item heal" option as just speeding up, as disinfectant/bandages do currently. But those two have near zero negative traits (a little pain from the disinfectant?). An in lore/gameplay "boost" to that would theoretically have a downside (IIRC, the stim/health boosts already in game from high tech items have "adrenaline crash" or addiction risks, right?).

Actually, I've not used the medical ampoule since the update. I guess I should test it out to see how that plays. :P

I agree the heal times are not bad. They just change a gameplay flow that many are used to. (I love "turtling" down and surviving, but many have different styles of play)

**Comment by kevingranade** [comment]
Your "alternatives" seems to indicate that this is a proposal for the main dda setting. If so, this is a non-starter. Instant healing items were removed for the same reason healing rate was reduced, because instant healing is not an effect that exists in reality, and because the impact on pacing in the game is intentional.
So even though the setting allows for instant healing as a precious hypertech effect, we don't actually want it in the game.

**Comment by BenlyAZ** [comment]
The timeskip option is appealing, though, if it's technically feasible. The real time a player spends waiting isn't a good balancing feature; the cost could (and I think should) instead be the supplies consumed during a downtime when you're not able to work for more, the risk of something hazardous happening during that time, and the opportunity cost of not doing what light work you can (studying, crafting) during time you're devoting to recovery.

**Comment by Zireael07** [comment]
Where were instant healing *items* mentioned? I think the issue is merely from the player's point of view (sitting around waiting to heal isn't fun), and not the game universe point of view, hence the timeskip proposed.

**Comment by TechyBen** [comment]
> Your "alternatives" seems to indicate that this is a proposal for the main dda setting. If so, this is a non-starter. Instant healing items were removed for the same reason healing rate was reduced, because instant healing is not an effect that exists in reality, and because the impact on pacing in the game is intentional.
> So even though the setting allows for instant healing as a precious hypertech effect, we don't actually want it in the game.

Sorry it seemed that way. As said, I used disinfectant as an example. In game it speeds up the rate, it is not instant (anymore). So other items that have CDDA lore/gameplay ability to speed it up past disinfectant rates, seems reasonable.

The other aspect (NPC/camp actions/missions) may already be on the development board. I've no idea if a camp "hospital" would exist, but the way the current system is going (farming/scavenging/building), I could see it happening. Thus either building ones own camp, or finding the refugee center/faction camps could allow a player to timeskip to a point their health is back (note, that's not instant, it just changes the flow of gameplay to the player). :)

I understand that such a suggestion is more a long term goal. With individual items being more a stop gap (going to camp to get a healing speed boost, or finding one in a lab), of for players not using any camp/faction interactions, but still a limited resource.

As said, nice seeing the massive progress made in the camp/faction systems. And the changes to the healing systems. Looking at how these dynamics work, or possible adjustments, is still interesting. :)

**Comment by Regularitee** [comment]
Can we just make a worldgen variable that pushes the `healing_factor` (or whatever that variable is called) up or down? That way everyone can play the way they want to, like with seasons or city sizes. Those who want overnight healing can have it, those who want realism can have it. Problem solved.

**Comment by anothersimulacrum** [comment]
We already do. That's what was adjusted in the healing rate PR.

**Comment by kevingranade** [comment]
Just to repeat, instant heal or very fast heal items are right out, it doesn't fit the setting and it doesn't fit the gameplay.
The healing system is already adjusted to where we want it to be, asking for special items to accelerate it more is just a roundabout way of asking for the healing rate to be adjusted, which we've already addressed.
> New players/occasional raids into a city would have a little bit of a rebound time for healing (one night) of a few more HP points.

This is a bit different, if you read the original rate change PR, one of the proposals was to have healing rate be non-linear, so while the nominal "1HP to full HP" healing time might be around 10 days, the nominal "half health to full health" healing time might be 3 days, and the nominal "3/4 health to full health" rate might be overnight. However, I have to point out that if you're talking about "occasional raiding", this is irrelevant anyway, you go raid, get hurt, go home, do other stuff, it doesn't matter how long it takes if your combat activities are actually occasional.

We're working on making time skipping a viable option through various forms of optimization, and making that time spent productive via automatically executed activities such as sleeping, eating, crafting and studying.

Looping back around to the problem statement:
> CDDA is very flexible, and has many different play styles.

We do not in fact support arbitrary playstyles in the core game, if you want to support a different playstyle in a mod, that's fine, but, "I want to play this certain way in mainline" is not justification for making changes to the core game.

**Comment by remawapasu** [comment]
My suggestion is that if you think the healing rate is too slow, then you fire up the debug console, open the mutate menu, and give your character Fast Healer/Very Fast Healer/Regeneration. Need a bigger buffer of hit-points? Get the HP line of mutations (Tough/Durable/Unbreakable). None of those push you past a threshold.

It's not cheating if you roleplay! :*)

**Comment by CataphractPrime** [comment]
I disagree that instantaneous or near-instantaneous healing doesn't fit the setting. It's neither more nor less realistic than the sci-fi nonsense that is mutagen.
It seems absurd that it's perfectly acceptable and entirely believable to drink/inject a concoction that allows you to, for example, grow a tail from nothing, but doing the same to regrow flesh from an injury is unrealistic and impossible because it's not an effect that exists in reality.

**Comment by anothersimulacrum** [comment]
That means mutagen needs to change, not healing.

**Comment by TechyBen** [comment]
@kevingranade Yeah. I see that now with the mechanics and game plans. Reading between the lines, I think I can see where the development is now. I did not previously, and only had the existing game as a guide of it's mechanics and theme.

Nice to hear the Camps/NPCs are hopefully going to get fully filled out with options. A NPC "protect and help me heal and rest here" dialog/mission/system would also mitigate some of the perceived gameplay flow interruptions. Plus a hospital/camp "rest here/wait 10 days" option, if possible (simulated and timeskipped/jumped or similar) would also open up a lot of things. Like waiting out an entire year and seeing how the world around the camp changed, waiting out the "healing" knowing the character could not do anything (if broken limbs etc), and has lost that time/resource gain, to the progression of the world outside.

I'll see how things develop, and only add some modding items for fun/test/etc if I really see my char needs them. But I was interested in others opinions and the mechanics of the systems. :)

**Comment by dkargin** [comment]
I guess you can make instaheal items using magic effects from magiclysm. Spell effects (actual implementation in code) are already mainlined. So you can make a mod with some healing poitions, with lines like:
`... "use_action": {"type": "cast_spell", "spell_id": "light_healing", "no_fail": true, "level": 1 },`

**Comment by TechyBen** [comment]
@dkargin Thanks. I'll keep that knowledge in mind for any future item abilities if needed. But none of the ideas I was musing over were for instant heal, just understanding if stop gaps were needed for game flow. Or if game flow is specifically going in a different direction (it seems it will be, with the nice additions of camps and NPC interactions).

**Comment by kevingranade** [comment]
This discussion was concluded.
