### ISSUE TITLE
NPC ordered to construct blueprint can eventually switch to his/her long term goal and run away.

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#31872]
# Describe the bug

NPC ordered to construct blueprint can eventually switch to his/her long term goal and run away.
Usually that happens when they are interrupted.

# Steps To Reproduce

1. Spawn NPC
2. Define construction blueprint zone and provide required tools and materials. Constructions should be time-consuming.
3. Order NPC to complete blueprint.
4. Wait until NPC interrupts building (for example, goes to bed)
5. Watch him run away after waking up.

# Expected behavior

NPC returns to the activity before interrupt and stays on the base.

# Screenshots
N/A
# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-4979-g6a0f1c8
 - Graphics version: Tiles
 - Mods loaded: [ "dda", "no_npc_food", "filthy_morale", "craftgp", "safeautodoc", "aftershock", "realguns", "More_Survival_Tools", "Medieval_Stuff", "makeshift", "modular_turrets", "Salvaged_Robots", "Mining_Mod", "mutant_npcs", "alt_map_key", "cityside", "more_locations", "FujiStruct", "Urban_Development", "boats", "blazemod", "deoxymod", "Tanks", "DP_REMIX_INDICATORS", "EngineeringEssentials", "StatsThroughSkills", "sleepdeprivation", "more_classes_scenarios", "manualbionicinstall" ]

# Additional context

Save file from #31799 can be used to track down this problem.

**Comment by davidpwbrown** [comment]
This should be fixed by #31696  I've included the bugfix for this happening in there.

**Comment by sdp0et** [comment]
I've seen this from telling an NPC to follow after leaving them on guard duty for a while.
