### ISSUE TITLE
Pulping three corpses depletes stamina and causes severe pain

### ISSUE THREAD

**Issue by b0urgeoisie** [CleverRaven/Cataclysm-DDA#31891]
# Describe the bug

When pulping three (possibly/probably more?) corpses in the same square depletes stamina completely and begins to stack pain. With full stamina was brought to severe pain. Does not stop to catch breath like dissection for example.

# Steps To Reproduce

Put three corpses in a square, press s.

# Expected behavior

Stamina drain seems too high, or at least would stop to catch breath as happens with dissection. Would expect at least a prompt to warn about what'll happen.

# Versions and configuration

<!-- Please complete the following information; you can now go to:
 
- OS: Windows 10
 - OS Version: 10.0 1803
- Game Version: 0.D-5005-gc88b7db [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Classes and Scenarios Mod [more_classes_scenarios],
    Simplified Nutrition [novitamins],
    StatsThroughSkills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct]
]

**Comment by DeeUnderscore** [comment]
Seems to be the same issue as #31889

**Comment by ifreund** [comment]
Closing as a duplicate
