### ISSUE TITLE
Overland Specials with invalid names

### ISSUE THREAD

**Issue by sdp0et** [CleverRaven/Cataclysm-DDA#31897]
# Describe the bug
When loading a save or starting a new game generates errors like:
`invalid overmap terrain id "cabin_strange_b_north"`
but for several different variations of terrain ids.

For loading the save I was able to ignore and play for a while until it crashed.  I was driving near unexplored areas so I assume I entered an area where one of these specials needed to be placed. I got the same error as when loading the map.

diffing the json directory with the prior version shows that several overmap_specials were changed

Old:
`{
    "type": "overmap_special",
    "id": "Strange Cabin",
    "overmaps": [ { "point": [ 0, 0, 0 ], "overmap": "cabin_strange" }, { "point": [ 0, 0, -1 ], "overmap": "cabin_strange_b" } ],
    "locations": [ "forest" ],
    "city_distance": [ 20, -1 ],
    "city_sizes": [ 0, 12 ],
    "occurrences": [ 1, 1 ],
    "rotate": false,
    "flags": [ "CLASSIC" ]
  }`

New:
`{
    "type": "overmap_special",
    "id": "Strange Cabin",
    "overmaps": [
      { "point": [ 0, 0, 0 ], "overmap": "cabin_strange_north" },
      { "point": [ 0, 0, -1 ], "overmap": "cabin_strange_b_north" }
    ],
    "locations": [ "forest" ],
    "city_distance": [ 20, -1 ],
    "city_sizes": [ 0, 12 ],
    "occurrences": [ 1, 1 ],
    "flags": [ "CLASSIC" ]
  }`

The overmap ids were changed and the rotate flag was removed.

In data\json\overmap\overmap_terrain\overmap_terrain.json the ids were not changed (still ex "cabin_strange" without the "_north" suffix) and the NO_ROTATE flag was removed

A file "data\json\obsolete_terrains.json" was added in the new version which contains the old names of the items (I didn't confirm every single one, but some I picked from the log were all there).

# Steps To Reproduce

Load existing or start new game

# Expected behavior

load or create map with correct terrain ids

# Screenshots

# Versions and configuration

 GAME REPORT: 
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-5015-g3fb8798 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Paul's Stuff [paulsstuff],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Magiclysm [magiclysm],
    Draco's Dog Mod [DracoDogMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    PKs Rebalancing [PK_REBALANCE],
    Alternative Map Key [alt_map_key],
    Fast Healing [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Vampiric Stuff [vamp_stuff],
    Arcana and Magic Items [Arcana],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, +attitude [sees_player],
    EXTENDED_BUILDINGS [ext],
    Jury-Rigged Robots [jury_rigged_robots],
    Classes and Scenarios Mod [more_classes_scenarios],
    StatsThroughSkills [StatsThroughSkills],
    Battery Migration for Existing Games [Battery_Overhaul_Legacy_Mode],
    Necromancy [necromancy],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex]
]

# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3332377/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3332378/debug.log)

The attached save is a few turns  before the crash.  Character is driving, just let a 2-3 turns pass

**Comment by sdp0et** [comment]
I zipped the save directory but it was too big to attach.  It doesn't seem like the save would help with this, but if it does I can find an alternate method to share it.

**Comment by anothersimulacrum** [comment]
I think the problem here is that the alternate map key mod was not updated.

**Comment by ZhilkinSerg** [comment]
Zip your `mods` and `save` folders and upload it somewhere else - e.g. https://zippyshare.com/.

**Comment by sdp0et** [comment]
I thought I made a copy of the the game directory before rolling back (9226->9201), but it turns out I copied the "previous_version"(9201).  The save there might require moving around to get to the crash, but if loaded in 9226 should still have the same ignorable errors on load.  I'd have to re-update to 9226 to get the mods folder.  Unless I've got something unique going the errors were happening during worldgen of a new world.

@anothersimulacrum There were not differences for the alternate map key mod, but unless I'm misunderstanding the relationship between overmap_terrain.json an overmap_specials.json, the ids were mismatched there as well.  

If nobody else has experience this by this point though I'll try again.  maybe something weird happened with the launcher during update.

**Comment by sdp0et** [comment]
I updated (9224->9231) and have the same issue.  I noticed in this diff that Aftershock mod (not used in this save) had changed its overmap_terrain.json and overmap_specials.json in the same way and that the ids did not match, so maybe that points to me incorrectly assuming they were supposed to.  The alt map key mod was still unchanged so maybe that is the issue.

save.mods from the 9231 update.  error and crash should happen if you just pass a few turns while driving.

https://www19.zippyshare.com/v/WWJkJNsO/file.html

**Comment by TheThingG** [comment]
The bug is caused by this PR
https://github.com/CleverRaven/Cataclysm-DDA/pull/31831/

**Comment by ZhilkinSerg** [comment]
That is issue of Arcana and PKs mods - they should make affected overmap terrains rotatable.

**Comment by sdp0et** [comment]
@ZhilkinSerg would you mind explaining so that I understand it more and know how to bring it up in those repos? The error is  ```invalid overmap terrain id "cabin_strange_north"```
but the only file that contains that id in my data directory data/json/overmap/overmap_special/specials/json where it references the id that doesn't seem to be defined anywhere,  is the "_north" suffix used to tell the game to created that terrain at runtime, in which case they'd just need to remove ```"flags": [ "NO_ROTATE" ]``` from the overap_terrain definitions they are overwriting so that the game can generate the tile when the overmap_specials definition in the core json 
uses a direction suffix?

**Comment by sdp0et** [comment]
For anyone else who lands here, I experimented with the assumption above and modified the PK mod files and was able to generate a new world (my existing save was still affected.  Some of the affected terrains were just replaced with "nothing" but others still cause a CTD if I get to close to where one needs to be generated)

I explained the process I went through here: https://github.com/dissociativity/PKs_Rebalancing/issues/18

**Comment by ZhilkinSerg** [comment]
> 
> 
> The bug is caused by this PR
> #31831

No, it is not. It is caused by incompatible third-party mods.

**Comment by ZhilkinSerg** [comment]
> 
> 
> @ZhilkinSerg would you mind explaining so that I understand it more and know how to bring it up in those repos? The error is `invalid overmap terrain id "cabin_strange_north"`
> but the only file that contains that id in my data directory data/json/overmap/overmap_special/specials/json where it references the id that doesn't seem to be defined anywhere, is the "_north" suffix used to tell the game to created that terrain at runtime, in which case they'd just need to remove `"flags": [ "NO_ROTATE" ]` from the overap_terrain definitions they are overwriting so that the game can generate the tile when the overmap_specials definition in the core json
> uses a direction suffix?

It is described in several comments here: <https://github.com/CleverRaven/Cataclysm-DDA/issues/31797>.

Rotatable overmap terrains should not have `NO_ROTATE` flag. Rotatable overmap specials should have value of `rotate` node set to `false` (or omitted to have default value of `false` set automatically).

Rotatable overmap terrains used in overmap specials should have direction/rotation suffix added to their ids (usually ` _north`, but can be different depending on mapgen).
