### ISSUE TITLE
Magiclysm: finger firelighter can be unequipped, lasts forever

### ISSUE THREAD

**Issue by anonym** [CleverRaven/Cataclysm-DDA#31909]
@KorGgenT, there's a small issue with you recent addition:

# Steps To Reproduce

1. Cast Finger Firelighter
2. Unequip `finger firelighter`
3. Notice how its turn counter stops while it is unequipped, making it last forever while providing infinite lighting for crafting/reading

# Expected behavior

* Best solution: unequipping the `finger firelighter` should make it disappear immediately
* Mediocre solution: an unequipped `finger firelighter` still expires after the normal amount of turns
* Bad solution: `finger firelighter` is unequippable (must wait until it expires)

**Comment by Lazasar** [comment]
it's not just the firelighter, its all the summoned items

**Comment by KorGgenT** [comment]
i'm thinking it has something to do with process_item in inventory. i will try to investigate this weekend.
