### ISSUE TITLE
second hub mission causing crash

### ISSUE THREAD

**Issue by b0urgeoisie** [CleverRaven/Cataclysm-DDA#31900]
# Describe the bug

Upon accepting 2nd hub quest and receiving items, game goes through a series of errors and ultimately crashes.

# Steps To Reproduce

Accept 2nd hub quest.

# Expected behavior

I would expect that it not crash the game.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5005-gc88b7db [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Classes and Scenarios Mod [more_classes_scenarios],
    Simplified Nutrition [novitamins],
    StatsThroughSkills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct]
]

# Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3332698/crash.zip)

**Comment by ralreegorganon** [comment]
This is fixed in #31883.
