### ISSUE TITLE
Being exposed to Tear Gas is now a death sentence

### ISSUE THREAD

**Issue by Kirefire** [CleverRaven/Cataclysm-DDA#31907]
# Describe the bug

Due to the changes to stamina in Experimental build 9224, Tear Gas, especially from tear gas hacks now causes the player to die from the winded effect if not treated. using an oxygen tank prevents you from dying if applied fast enough. Stamina increasing perks do not increase survivability.

# Steps To Reproduce

1. Get exposed to tear gas
2. Die horribly from winded debuff due to not having oxygen tanks

# Expected behavior

Tear gas to not be essentially cyanide.

# Versions and configuration

 - OS: All OS's
 - Game Version: Experimental 9224 onwards
 - Graphics version: Tiles
 - Mods loaded: DDa

**Comment by DeeUnderscore** [comment]
Related issue: #31889
