### ISSUE TITLE
Stamina management and player agency

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#31915]
I express this opinion as an avid player of the game and with a great deal of respect to @nexusmrsep who is an excellent programmer;

Following the stamina rework and much recent play in the last few builds, and reading the issues list, it seems @nexusmrsep thinks the solution is to tone down the effects of the winded status, in order to fix the numerous stamina related problems.

I don't entirely disagree but it seems clear to me that this was not thought through, especially in relation to the pain mechanics, which also need an overhaul and with respect to stamina and player agency.

What it brought to light is that stamina management, (which Vormithrax often says is the thing that kills most new players.) is not actually being considered in terms of player agency, just "realism". It seems there are no plans to make all the things that drain stamina do so at the will of the player, or at the level the player desires, even when time is available to do them in a manner that would conserve stamina.

I believe there is no point in implementing it in the way it is currently being implemented. It basically hasn't changed combat much, but has made everything else more tedious. With hauling (items not found), butchering (corpse not found), and traveling (winded on bike after four tiles) all broken the current build is unplayable.

An example of the lack of thought to players is a how an early game fight, before you have a knife used to work. You beat a zombie, hit (s)mash hit a direction, move on. Stamina regenerates as you walk, no issue.

Current system, I beat a zombie, hit wait, hit down (from set an alarm to recover breath), hit enter, recover stamina, hit (s)mash, hit a direction, hit wait again, hit down again, hit enter again, and we've gone from two key presses to carry on game-play to 8. Smashing a zombie takes two thirds of my characters stamina. At 12 STR.

The butchery is a similar thing, draining stamina. Now not only do we have multiple key presses, we need to stop the flow to consider stamina management?

**How to address this;**

Yes, stamina management should be important, however, the difference is we should be allowed to spend stamina as and when we wish. With running and combat, as I mentioned Stamina hasn't changed much. It retains its tactical nature with running, melee and stamina depletion. However, just carrying out activities, constantly needing to stop for breath is incredibly tedious. The game needs to be as streamlined as possible between combat, and is currently getting VERY bogged down.

Combat and dangerous areas should be the ONLY place I need to actively manage stamina. Walking, butchering, jogging, bike riding, can all drain fatigue, but should clearly be able to be effectively managed by just doing the thing slower, and that should be the default state. It should not take extra key presses to manage, and should not interfere with traveling.

It should, however be as painful, and as detrimental as winded was before it was decided that winding was the problem, IF the player decides they need to get the thing done quicker. This is where it should be difficult and costly. Draining stamina for a quick smash vs. a normal smash when that necromancer is just out of sight range should have a tactical choice associated with it, and this is where extra key presses should be involved. Mundane tasks should be mundane until they need to be done in a dangerous area and time is a concern.

In the thread on pain recovery I suggested that doing the action while in run mode would hasten it, and would keep down key presses, giving butchery/smashing/picking up items a "tactical mode", allowing the player to actively wind themselves, while choosing to use stamina as a resource. Which you would only really choose to do in dangerous situations, where time was a concern. This is basically already the case with running and melee.

I know and understand this is basically another overhaul in regards to the programming, but I really think it needs to happen.

Again, I hope this comes across in the correct manner as @nexusmrsep is a great contributor, I just strongly disagree with the current implementation.

**Comment by kevingranade** [comment]
You have a point, but this is a bug tracker, not a forum or soap box, so please refrain from making verbose conversational issues like this and stick to the facts instead of rhetoric.

**Comment by 7illian** [comment]
A player should not have to (w) to recover stamina _unless its fully depleted or deep in the red_. It should regenerate *much* quicker than it currently does, assuming you have't gone 'all out' in whatever action you've been doing. 

(W) should be reserved for situations where the character is functionally bent over panting, not slightly worked up. 

'Realistically', if your character is capable of running a couple hundred meters on 3 bars of remaining stamina, he shouldn't need to walk 2 miles to recover the remaining two.
