### ISSUE TITLE
Magiclysm: Owlbears show up way too early and way too often

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#31916]
I get that Magic brings a lot of power into the hands of the player, and increasing the danger is appropriate, but I am running into Owlbears right away, within moments of starting that game.

**Comment by RocketPapaya413** [comment]
Could you add some more details such as the version of the game you're playing on and what other mods you're using? I've heard similar reports from at least one other person, but I've also heard the spawns seem fine from other people and haven't been able to observe any issues myself.

**Comment by Lazasar** [comment]
No other mods. Latest experimentals from the last 2 days

**Comment by YakumoChen** [comment]
I can back this up, although I was using several unrelated mods, went into the forest on the first day and ran into an owlbear not far in.
