### ISSUE TITLE
Hide Bag Occupies 'Normal' Worn Layer

### ISSUE THREAD

**Issue by Randonx** [CleverRaven/Cataclysm-DDA#31929]
**# Describe the bug**

The item `hide bag` upon being worn occupies the `Normal` layer.

**# Expected behavior**

I would expect a bag item to be worn in the `Strapped` layer of equipment.  For reference, the item `plastic shopping bag` which is essentially the same thing made from a different material already occupies this layer upon wearing.

# Screenshots

![hidebag](https://user-images.githubusercontent.com/50780860/60309370-4e0d7580-9902-11e9-8800-fb7934c74b73.PNG)
![plasticshoppingbag](https://user-images.githubusercontent.com/50780860/60309374-4fd73900-9902-11e9-8e9f-2bfc3a1f686b.PNG)

# Versions and configuration

 - OS: Windows 10 Pro
 - Game Version: 0.D-5043-gaa96c09 (tiles)
 - Mods loaded: 
  "dda",
  "no_npc_food",
  "crt_expansion",
  "magiclysm",
  "growable-pots",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "alt_map_key",
  "hydroponics",
  "MMA",
  "national_guard_camp",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "deoxymod",
  "blazemod",
  "necromancy",
  "DP_Old_Floor",
  "DP_REMIX_INDICATORS",
  "sees_player_less_attitude",
  "no_religious_Texts",
  "manualbionicinstall",
  "no_filthy_clothing",
  "no_reviving_zombies",
  "safeautodoc",
  "speedydex",
  "StatsThroughSkills",
  "PK_REBALANCE",
  "Cata++",
  "Mining_Mod",
  "No_Rail_Stations",
  "more_classes_scenarios",
  "RL_Classes"

**Comment by l29ah** [comment]
Wait a minute, hide bag takes 30mL? Cool.

**Comment by glenmack** [comment]
Had a look at the issue, I think it's because the item is perishable and needs to be in the comestible category, the armor flags are identical to plastic shopping bag, which should put it on strapped, but because the item isn't in the "armor" category it can't be strapped?

Was going to add correct flags but issue looks more complicated.
