### ISSUE TITLE
Game development and censorship

### ISSUE THREAD

**Issue by micage** [CleverRaven/Cataclysm-DDA#31934]
after filing a bug concerning rapid stamina loss which led to a situation where you cannot longer play the game, the developers or some of them decided to close my issue.

My issue (rapid stamina loss and after this severe or more pain and as a consequence of this the inability to move or run away) is totally valid.

This is censorship. Shame on you.

**Comment by kevingranade** [comment]
You opened a rant instead of a meaningful issue about a known issue, bye.
