### ISSUE TITLE
This game gets screwed by some developers

### ISSUE THREAD

**Issue by micage** [CleverRaven/Cataclysm-DDA#31933]
Realism is a good concept- Gameplay is another.

Stamina is an important concept. You cannot do everything. Even in best condition and best armor. That's ok. Having a break in a squatted house and heal up. But when breaks in game become breaks in real life there is something wrong.

Sleeping. A coffee break in real life.
Pulping corpses. 50% stamina loss. Let's have abreak.
Fighting easy zombies. Boah. Let's have a break.
As for now CDDA let's have a break.

**Comment by Zireael07** [comment]
This is not a place for rants and vents.

There are performance improvements planned for sleeping and other activities that advance game time.

As for the rest, I believe a fix for bugged winded effect has just been merged.

**Comment by micage** [comment]
This is just the right place. Or should I better talk to my grandma about this?

**Comment by esotericist** [comment]
If you have an actual bug that isn't already reported, this is the place.

If you have a concrete feature request that isn't already stated somewhere, and is in keepings with the intentions of the projects, this is the place.

If you just want to express yourself, this is not the place.

You should try the discourse, discord, or reddit.
