### ISSUE TITLE
Books should not train skills, but instead give bonuses to skill training

### ISSUE THREAD

**Issue by Zmedaris** [CleverRaven/Cataclysm-DDA#31931]
**Is your feature request related to a problem? Please describe.**  
It's kind of silly that if you happen upon the right set of books for a skill, you can train from being a wet-behind-the-ears novice to a master of that skill with just some days of reading words off pages.

**Describe the solution you'd like**  
A proposed solution to this problem would be to have reading books apply a skill training bonus for a decent amount of time, so that when you go to train with that skill, your level advances a lot faster.

This is a lot more realistic, and would also improve gameplay as books become less a source of cheese, and more of a compliment to actually putting in the work and resources to improve your character's abilities.

One special exception: computers has no really practical way to train the skill, so it'd be acceptable to leave in book-based training for this until that skill is more fleshed out, with more uses and/or significantly buffed skill gains on the uses that already exist.

**Comment by kevingranade** [comment]
This is the current plan https://discourse.cataclysmdda.org/t/practice-makes-perfect/3509?u=kevin.granade

**Comment by Zmedaris** [comment]
> This is the current plan https://discourse.cataclysmdda.org/t/practice-makes-perfect/3509?u=kevin.granade

Didn't even know there was a 'dev blog' of sorts.

Well, forget my idea. I like this one a lot more.

**Comment by IvanShestakov** [comment]
I tried to learn a martial art in latest build - we're used to read a book 15 minutes and become a Shaolin master, but no, it took me about 6 hours of repeated attempts before it actually happened.
The game log spewed messages like "practice makes perfect" "you're back to repeating basic moves" etc. I like it!
