### ISSUE TITLE
Joint Servo CBM penalties seem to make it impractical

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#31949]
Trying this out for the first time, I recorded these effects on a character:

**Running cost:**
Natural: 36
CBM offline: 41
CBM online: 32

**Walking cost:**
Natural: 73
CBM offline: 79
CBM online: 69

When you consider the very short duration it can run (energy drain per step is 10 for walking, 20 for running), and the fact it inflicts an otherwise permanent movement debuff, the CBM probably ends up giving the character a reduction in average speed overall.  Not to mention the very marginal speed increase over natural speed (~5%?) when it is active is probably too tiny to actually have much impact in most situations.

It's one of the few CBMs I would recommend people actively avoid because it seems more harmful than beneficial. And its benefits don't seem anywhere near good enough to be worth taking a permanent penalty to your character's stats.

**Comment by TechyBen** [comment]
What are the effects, they are not labeled?

**Comment by Regularitee** [comment]
Sorry, should have made it clearer. The CBM decreases run/walk costs when active, increases it when inactive. And costs energy when running.

**Comment by kevingranade** [comment]
Expected result and actual result are mandatory, please provide them in future.
I'm going to guess that your expected result is, "this CBM should be better", and on that basis I'm closing the issue, since that's not a valid reason for an issue.

**Comment by kevingranade** [comment]
If you're interested in making a case for this, read the discussion in #28574 and address the issues brought up there.

**Comment by I-am-Erk** [comment]
@Regularitee this is the exact problem I was just telling you about on the discord. The template for how to post an issue or a pull request isn't there for fun, it serves an important purpose. It is not a coincidence that when you ignore it your stuff keeps getting closed.
