### ISSUE TITLE
Repeatable (Segment crash) Reloading Mossberg 500 crash when using up all of 1 ammo type from shelf.

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#31943]
# Describe the bug

Reloading the Mossberg 500 from a shelf with one ammo type causes a crash when the remaining ammo is of a different type. if I remove all the ammo into my inventory or floor it's fine and it never crashes. But if I attempt to reload from the shelf it will crash upon exhausting the last of that ammo type and only has a different type remaining. If i remove the other type of ammo from the shelf i,e the birdshot it won't crash if i continue to reload the mossberg shot rounds from the shelf. the problem lies when there is another ammo type and the game gets confused or something to that effect.

# Steps To Reproduce

1. Equip the Mossberg 500
2. Pickup both the 2 remaining shot rounds and 20 birdshot rounds.
3. Place both ammo into a shelf/container i,e utility shelf or cupboard that happens to be nearby in save.
4. Start reloading the "shots" into the mossberg.
5. The game will crash when it attempts to chamber the last "shot" round.

# Expected behavior

Not to crash when reloading from a shelf.

# Screenshots
(Clarification image)
![image](https://user-images.githubusercontent.com/5264667/60366071-55a44b80-99e2-11e9-9251-0e6f34e287f9.png)

(Original crash image)
![image](https://user-images.githubusercontent.com/5264667/60364099-466ecf00-99dd-11e9-9251-9ecfa799b444.png)

 - OS: Win7/64bit
 - Game Version: 0.D-5062-g7f06d55]
 - Graphics version: [Tiles ]
 - Mods loaded: [ "dda", "Medieval_Stuff", "More_Survival_Tools", "RL_Classes", "SD_Magcrafting", "StatsThroughSkills", "blazemod", "Tanks", "Urban_Development", "ZSFIXED_cddaxp", "boats", "craftgp", "deoxymod", "ew_pack", "filthy_morale", "makeshift", "more_classes_scenarios", "mutant_npcs", "national_guard_camp", "npc_traits", "Tolerate_This", "modular_turrets", "Salvaged_Robots", "Bootleg_Walkers", "DracoDogMod", "DP_AMAZING_CHEST_INDICATORS", "aftershock", "Arcana", "more_locations", "FujiStruct", "growable-pots", "hydroponics", "MMA", "vamp_stuff", "vamp_stuff+arcana", "secronom", "magiclysm", "crt_expansion", "speedydex", "no_npc_food" ]

# Additional context

Crash/debug/save files

[crashNDebugTXT.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3340428/crashNDebugTXT.zip)
[Zakhadia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3340429/Zakhadia.zip)

**Comment by nexusmrsep** [comment]
Unable to reproduce with provided save. Probably fixed.
