### ISSUE TITLE
GNU++2a compliance

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#31945]
**Is your feature request related to a problem? Please describe.**  
Compiling cdda on GCC 10 with gnu++2a set only gives two, very fixable errors, and otherwise compiles fine.

**Describe the solution you'd like**  
Currently, as of 7f06d55b2ddafd620b5c5f453f7ca1df23df2104 
1. In: behavior_strategy.h,  ` "#include <string>"` needs to be defined
2. in: vehicle_use.cpp, on line 109, implicit use of "`[ = ]`" is depreciated. Replacing it with "`[=, this]`" fixes.

**Describe alternatives you've considered**  
There's really no reason besides future-proofing, and maybe if someone wants to use any of the newer functions I guess, to actually do this. gcc 9 isn't even mainlined, let alone gcc10

**Comment by Leland** [comment]
Probably too minor to keep around as an issue. To you or anyone else, feel free to open a PR however!
