### ISSUE TITLE
Taste Modifier bionic doesn't counter the mushy morale penalty

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#31956]
While the description suggests otherwise.

0.D-5069-g6be2679ca8

**Comment by Rivet-the-Zombie** [comment]
This sounds like it's WAI; mushiness is a texture, not a flavour.

**Comment by Night-Pryanik** [comment]
Well, Taste Modifier should affect the texture too.

**Comment by misterprimus** [comment]
Toy need mouth anesthetic to get rid of texture sensation.
