### ISSUE TITLE
Zombies Ignore Stairs Position When Changing Z Levels

### ISSUE THREAD

**Issue by Magikjak** [CleverRaven/Cataclysm-DDA#31955]
# Describe the bug

Zombies appear to climb directly downwards or upwards when changing Z levels, this means when climbing down stairs that aren't aligned they will end up in the tile directly below them, not at the matching stairs. I've been trying to survive inside a basement in a city, one of the survivor basements with the M240 spawn and zombies keep appearing in the bedroom instead of the entry hallway.

# Steps To Reproduce

1. Lure horde of zombies into an area with stairs. Make sure that the stairs are not aligned between Z levels
2. Go down the stairs where the zombies would usually follow you.
3. Zombies will move down the stairs and appear at the X,Y coordinates directly below the upper stairs, instead of at the lower stairs.

# Expected behavior

Zombies should move from one set of stairs to the other regardless of initial X,Y coordinates of stairs.

# Screenshots

Above
![Above](https://user-images.githubusercontent.com/7457168/60379994-cb062f80-9a67-11e9-8a4c-7918fc6f8c79.jpg)

Below
![Below](https://user-images.githubusercontent.com/7457168/60379995-ce99b680-9a67-11e9-97ec-528a71e4dbdc.jpg)

Bedroom
![Bedroom](https://user-images.githubusercontent.com/7457168/60379998-d22d3d80-9a67-11e9-8f56-69ab9c52684c.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5069-g6be2679 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi]
]

**Comment by glenmack** [comment]
Can confirm, this is why I had zombie scientists appearing in the middle of a locked room with only stairs in the corner.

**Comment by l29ah** [comment]
I think if the "Align up and down stairs" world option is enabled, zombies are sometimes stuck as well.

**Comment by l29ah** [comment]
Repro: 
[2019.07.17.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3402223/2019.07.17.zip)

**Comment by KorGgenT** [comment]
closed via #35392
