### ISSUE TITLE
Extreme performance hit heading into city with 3d FOV enabled

### ISSUE THREAD

**Issue by esotericist** [CleverRaven/Cataclysm-DDA#31952]
# Describe the bug

While testing some changes to fix monster evolution erroneously increasing with changes in cataclysm start date, I went into town and found the game taking in excess of 1 real-life wall-clock second for every step, sometimes as much as 2 or 3 seconds.

# Steps To Reproduce

1. Load attached savefile
2. Try to move around (waiting doesn't seem to have the same impact)
3. Watch it sluggishly attempt to do things

# Expected behavior

Ideally, it should be just as fast in town as it is when out of town. With 3d FOV, some slowdown is probably inevitable, this seems a bit much.

# Screenshots

Profiler!
![image](https://user-images.githubusercontent.com/1569754/60378593-453ba300-99d9-11e9-82c0-08f7c74d2828.png)

# Versions and configuration
- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14.5; Build: 18F132; 
- Game Version: 0.D-5069-g6be2679ca8-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
# Additional context

Save file.
[evolutiontest.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3341310/evolutiontest.zip)

**Comment by esotericist** [comment]
Options, in case you need them:

[options.json.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/3341329/options.json.txt)

**Comment by Midaychi** [comment]
[Shady Side.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3342731/Shady.Side.zip)

Simply walk east to load in the farm multi-zlevel silos and observe this slowdown.

GAME REPORT: 
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 18.0.4; Codename: Illyria; 
- Game Version: 0.D-5099-gdc2cc104eb-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    DinoMod [DinoMod],
    Hydroponics [hydroponics],
    Mythical Martial Arts [MMA],
    sees-player icon, +attitude [sees_player],
    Urban Development [Urban_Development],
    More Locations [more_locations],
    Mapgen Demo [mapgen_demo],
    Fuji's More Buildings [FujiStruct],
    Beta National Guard Camp [national_guard_camp],
    Disable Mutagens [no_mutagen],
    No Survivor Armor [no_survivor_armor],
    Bionic Slots [cbm_slots],
    Sleep Deprivation [sleepdeprivation],
    NPC traits [npc_traits],
    Mutant NPCs [mutant_npcs],
    More Survival Tools [More_Survival_Tools],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod]
]

**Comment by Midaychi** [comment]
as of 0.D-5531-gdcd9f1d5b5
one or more of the changes in the last day and a half has significantly improved performance around zlevel buildings when zlevel vision and zlevels are enabled. The speed isn't 100% to how it was before this issue cropped up but it's close enough that it's very playable.

**Comment by kevingranade** [comment]
This should be fixed by #32012
Overhauling the algorithm is certain to replace any existing errors with all new errors.

**Comment by kevingranade** [comment]
I'm removing this from the 0.E blockers because 3D_FOV is still not default-on, we will definitely be shooting for that for 0.FoV, and because we have basically no prospect of addressing it in a timely fashion.

**Comment by esotericist** [comment]
should be fixed as of #42835
