### ISSUE TITLE
Deer locked in a room produces >25 footsteps per turn

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#31961]
Unlike a free-running one.

![](https://pstbin.ru/f/97457/)

# Versions and configuration

0.D-5069-g6be2679ca8

# Additional context

[2019.06.28-2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3341667/2019.06.28-2.zip)

**Comment by FulcrumA** [comment]
I'd like to request a Crazy Cataclysm deer, which, once bored - tapdances.

**Comment by capSAR273** [comment]
Could add a flag to allow animals to idle instead of using up all their movement turns while they have some left.

**Comment by alkemann** [comment]
I believe https://github.com/CleverRaven/Cataclysm-DDA/commit/87275b4b88919c37e5a5f9583b80268e5931e9c5 and specifically https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/monmove.cpp#L735  is relevant to this. If I change that `moved = true;` to `moved = false;` it fixes the deers without seeming to cause undue effect to their behaviour, but Zombies are much less agressive in following you around.

**Comment by alkemann** [comment]
So after several failed atttempts at fixes I have added sufficient debug msg to see that the deer is able to move back and forth between two tiles at a move cost of only 2. This because the distance one way is equal to the distance the other, causing a minimal staggering of 0.01f.

**Comment by alkemann** [comment]
I also found out that the deer inside has picked a target destination outside the house. See screensto with the green deer trying having picked the red circled tile outside as it's destination.

![image](https://user-images.githubusercontent.com/48854/64495111-e5ddf700-d295-11e9-9033-bea4ebdcf355.png)

Note that the bug does NOT happen with the player inside as shown in screenshot.
