### ISSUE TITLE
acetylene torch with 10 unlimited charges

### ISSUE THREAD

**Issue by b0urgeoisie** [CleverRaven/Cataclysm-DDA#31970]
# Describe the bug

Have an acetylene torch that can be used to repair car parts (haven't tried with other crafting applications). Torch charges ticked down normally until it hit 10, now it won't use up any of the charges and just keeps on going.

# Steps To Reproduce

Get an acetylene torch to 10 charges and repair your heart out.

# Expected behavior

Torch would use remaining 10 charges.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5062-g7f06d55 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Classes and Scenarios Mod [more_classes_scenarios],
    Simplified Nutrition [novitamins],
    StatsThroughSkills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Disable Religious Texts [no_religious_Texts],
    Safe Autodoc [safeautodoc]
]

# Additional context

[Escalante.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3342095/Escalante.zip)

**Comment by ZhilkinSerg** [comment]
Working properly on current `master` now - 10 charges are spent until 0.
