### ISSUE TITLE
Map Spawn Error: Hazardous Waste Sarcophagus

### ISSUE THREAD

**Issue by Xindii** [CleverRaven/Cataclysm-DDA#31972]
# Describe the bug

The overmap area 'Hazardous Waste Sarcophagus' produces an error when approaching it. After wading through the error spam, the area where the hazardous waste buildings should be is replaced by empty fields.

# Steps To Reproduce

1. Load up the included save.
2. Walk South down the road a bit until you reach the Hazardous Waste Sarcophagus. (It's visible on my map if you somehow get lost).
3. Enter the area it's supposed to be.

# Expected behavior

The hazardous waste sarcophagus to show up.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version (latest Win 7 update)
- Game Version: 0.D-5086-g93da2fd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Cars to Wrecks [cars_to_wrecks],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Xotto [DP_XOTTO_INDICATORS],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    EXTENDED_BUILDINGS [ext],
    Urban Development [Urban_Development]
]

# Additional context

 DEBUG    : map::saven grid (0,0,0) uninitialized!
 
 FUNCTION : void map::saven(int, int, int)
 FILE     : src/map.cpp
 LINE     : 6676

 DEBUG    : failed to generate a submap at 223,276,0
 
 FUNCTION : void map::loadn(int, int, int, bool)
 FILE     : src/map.cpp
 LINE     : 6788

#Save file
[CDDA HazWasSarc Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3342189/CDDA.HazWasSarc.Save.zip)

**Comment by Xindii** [comment]
I am not good at techie things. I hope I got all the information needed down.

**Comment by Necrosian** [comment]
Same happened to me some while ago.

**Comment by SleeperJack** [comment]
I've had a HWS spawn on my last map as triangle shaped asphalt floor that repeated in a 2x4 pattern. Maybe something with the mapgen?
