### ISSUE TITLE
Bad Save JSON

### ISSUE THREAD

**Issue by SleeperJack** [CleverRaven/Cataclysm-DDA#31980]
# Describe the bug

Upon loading save after crash, save fails to load and crashes CDDA.

# Steps To Reproduce

1. Do not know how to reproduce

# Expected behavior

The save file to load.
![Bug](https://user-images.githubusercontent.com/52094357/60389670-e4fd3d80-9a7a-11e9-9fca-ba10403fd192.JPG)
[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3342326/crash.zip)

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-5086-g93da2fd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Mythological Replicas [nw_pack],
    More Survival Tools [More_Survival_Tools],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    StatsThroughSkills [StatsThroughSkills]
]
Mod list also includes Modular Turrets, Salvaged Robots, and Hydroponics mods. I couldnt pull the affected savefile's game report.
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3342332/Save.zip)

# Additional context

Recent instability on that game file, numerous crashes usually when interacting with inventory, however this crash happened during normal movement.

**Comment by Ivan-Shestakov** [comment]
#31960 describes same issue, @jbytheway is looking into it. Thanks!

**Comment by SleeperJack** [comment]
Thanks, missed it when I was searching for similar entries.

**Comment by jbytheway** [comment]
Fix merged #31992.
