### ISSUE TITLE
Deactivating the Integrated Toolset's powered functions...

### ISSUE THREAD

**Issue by AnderHammer** [CleverRaven/Cataclysm-DDA#3199]
The Integrated Toolset bionic is handy for a lot of recipes, but by the time you get the CBM, you also tend to have a lot of the 'proper' tools for the job, and installing the CBM adds an extra keypress to recipes you don't intend to craft any differently, like cooking meat when you usually use a hotplate or fire, or doing vehicle work when you have a welding rig.

Could it be set up so that the Integrated Toolset can be 'depowered' by deactivating it in the bionics menu, thus only allowing its uses that don't require charges?

**Comment by BevapDin** [comment]
Implemented by #11459, isn't it? This should be closed then.
