### ISSUE TITLE
Batch crafting for food is broken

### ISSUE THREAD

**Issue by Zmedaris** [CleverRaven/Cataclysm-DDA#31993]
Batch crafting for most food items seems broken right now. I am only able to select '1x' and '20x' for any food item I've checked so far, and no other amounts, regardless of the materials I possess.

Note: the screenshots show 'boiled egg' recipe, but I've confirmed the exact same situation for 'clean water' and 'cooked meat' as well. Exact same appearance and function - amounts of mats are shown correctly, but unable to select proper craft batches.

# Steps To Reproduce

1. Make character.
2. Spawn in the tools and mats to create a food item in batches, such as cooked meat or clean water.
3. Check the batch amounts.

# Expected behavior
Should be able to craft amounts relative to the correct amount of materials I possess.

# Screenshots
![Screenshot (1847)](https://user-images.githubusercontent.com/12032854/60395361-f2501180-9ae6-11e9-9f56-3fe11c11c153.png)
![Screenshot (1848)](https://user-images.githubusercontent.com/12032854/60395362-f2501180-9ae6-11e9-9165-cc88690a2a14.png)
![Screenshot (1849)](https://user-images.githubusercontent.com/12032854/60395363-f2501180-9ae6-11e9-9368-b45a931f4a6e.png)
![Screenshot (1850)](https://user-images.githubusercontent.com/12032854/60395364-f2e8a800-9ae6-11e9-9a4f-a74997f60f67.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5096-gb537172 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    No Rail Stations [No_Rail_Stations]
]

**Comment by ifreund** [comment]
Whoops, looks like I broke this with #31844.  Will investigate a fix.

**Comment by Zmedaris** [comment]
> Whoops, looks like I broke this with #31844. Will investigate a fix.

Thanks buddy. You're awesome.
