### ISSUE TITLE
Dark tiles not updating properly

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#31994]
# Describe the bug

When traversing dark locations, like underground lab, character repeatedly is stumbling upon "walls of darkness" - tiles that do not light up despite being in the closest proximity (one of 8 squares next to the character itself). However, if those tiles are empty (for example, it's an empty corridor), upon stepping on one of them, both it and the surrounding tiles will update till another such "wall" is stumbled upon.

# Steps To Reproduce

1. Create average perception (8 - 9) character
2. Enter underground laboratory, dark sections
3. Walk around

# Expected behavior

All tiles in the "closest proximity visibility aura" range (tiles closest to the character) should be visible once coming into that range.

# Screenshots

![sight](https://user-images.githubusercontent.com/38487938/60395399-22250680-9b33-11e9-9ac7-c9bbac7f5e64.png)

# Versions and configuration

 - OS: Win7
 - Game Version: 0.D-5092-ga6a2bce (experimental 9243)
 - Graphics version: Tiles
 - Mods loaded:  "dda", "ew_pack", "blazemod", "Tanks", "No_Fungi", "no_flaming_weapons", "StatsThroughSkills"

**Comment by Hirmuolio** [comment]
May be related to #31851

**Comment by sammy202020** [comment]
this has been an issue for a long time. just a heads up

**Comment by Night-Pryanik** [comment]
Maybe related to #26830?

**Comment by Leland** [comment]
Also see @Hirmuolio's  screenshots in #31851. This happens with certain walls, apparently.

> ![alt text](https://i.imgur.com/iCKcZpf.png "a")
>
> Seemingly random spots of the wall become visible earlier.
> ![alt text](https://i.imgur.com/N3oggRw.png "a")


Steps to reproduce:

>  Enable z-levels (everything looks normal with z-levels disabled).
> Approach a lab (spawn one with debug menu if you can't find one).
> The walls don't become visible until you are very close.

**Comment by anothersimulacrum** [comment]
I believe Hirmulio's bug there is because there is furniture (barbed wire) on the z level above.

**Comment by FulcrumA** [comment]
I should point out that my bug happened without Z-levels enabled if that makes a difference.
