### ISSUE TITLE
ERROR : src/faction.cpp:363 [faction* faction_manager::get(const faction_id&)] Requested non-existing faction ''

### ISSUE THREAD

**Issue by TychaiosIlithios** [CleverRaven/Cataclysm-DDA#32019]
# Describe the bug
ERROR : src/faction.cpp:363 [faction* faction_manager::get(const faction_id&)] Requested non-existing faction '' 
Start of game, do few missions for initial npc, next follow up mission is "MISSION_RECRUIT_TRACKER" 
agreeing and accepting this mission results in such a bug
# Steps To Reproduce
if the save works adress npc - and accept mission, else
editing up the next mission to be recruit tracker. 

# Expected behavior
same bug

# Versions and configuration
9241 then 9249
    - Please update your OS version with a more precise version. -->
Win7-64
 - Game Version:  0.D - 5125-ge42e973
 - Graphics version: [Tiles 
 - Mods loaded dda, speedydex - others are item collections

# Additional context

[Ivanovo.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3343587/Ivanovo.zip)

**Comment by installgentoo** [comment]
just put     "faction": "wasteland_scavengers" into tracker entry in npc.json to fix.
