### ISSUE TITLE
Pain and some first-aid activities should create sound from PC

### ISSUE THREAD

**Issue by Zmedaris** [CleverRaven/Cataclysm-DDA#32014]
**Is your feature request related to a problem? Please describe.**  
It's a little surprising the PC never makes any noise when experiencing pain, whether through having a bite taken out of their arm, being shot, disinfecting nasty wounds, or sticking a searing hot piece of metal into their body to try and close nasty wounds.

**Describe the solution you'd like**  
Some types of damage, possibly via a pain threshold for the cause of pain itself, will cause the PC to emit varying levels of sound. So getting scratched by a regular zombie might make you 'grunt', whereas say, getting shot might make you yelp or scream in pain.

Also, some first-aid activities, like disinfecting bite wounds or limbs with a lot of damage, as well as cauterizing just about anything, will create sound. Not only does this add to the realism of the PC's woes, but it'll make tending to your damage more sketchy when there are things that can hear nearby.

**Comment by JeanLucVanDamme** [comment]
I like this idea, as long as it preserves realistic sound-muffling, as already happens with clothing on the mouth - for example, muffled yelling when wearing a bandana.

**Comment by kasanryukin** [comment]
Shock and adrenaline can go a long ways to dull the pain to a level you might not realize is as bad as it is.  That said there are many different thresholds for pain tolerence: one person's agonizing broken arm could be anothers throbbing but managable ache (using an anecdotal example.)

**Comment by Zmedaris** [comment]
> Shock and adrenaline can go a long ways to dull the pain to a level you might not realize is as bad as it is. That said there are many different thresholds for pain tolerence: one person's agonizing broken arm could be anothers throbbing but managable ache (using an anecdotal example.)

True enough. Maybe there would be a way to add that sort of depth later. Like perhaps a higher strength = less sound for pain thresholds, to simulate your 'endurance'. Or maybe a skill, like Survival or, um... well, that's about the only one I could think of that might give a person the ability to 'stuff their voice' when experiencing pain. None of the others really line up with this.

**Comment by kasanryukin** [comment]
I might actually take a look at this. Would be a fun simple minor addition
to help familiarize myself with the code mode since it deals with the
player and that's been a scary code subject for me this far.
