### ISSUE TITLE
NPC goes on an unexpected journey

### ISSUE THREAD

**Issue by esotericist** [CleverRaven/Cataclysm-DDA#32020]
# Describe the bug

I had an NPC in my faction assigned to work on constructing some palisade walls, noticed he'd wandered off to sleep in the greenhouse of all places.

When I went to check on him, he suddenly took off running to the southwest. When I managed (with the assistance of debug stuff) to catch up to him and ask him to stop his current activity, he was no longer marked as one of my followers.

# Steps To Reproduce

1. Load attached save
2. Head west to the greenhouse
3. `C` to talk to Lamont and wake him up
4. Exit conversation
5. Run, Forrest, run

# Expected behavior

NPC not going on a cross-country hike, and either following me or getting back to helping with construction?

# Screenshots

Debug output showing NPC state, kinda:
![debug output](https://cdn.discordapp.com/attachments/511623330227421184/595065640608464907/unknown.png)

# Versions and configuration

Note: this is technically a custom build, since I've been pulling pulling PRs into it for testing before they end up in master. Right now I believe the only unmerged patch I have is ifreund's batch crafting fix, and I'm running `-O3` optimizations.

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14.5; Build: 18F132; 
- Game Version: 0.D-5172-g591f0ff8ae [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    sees-player icon, +attitude [sees_player],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Folding Parts pack [deoxymod],
    Magiclysm [magiclysm]
]

# Additional context

Save file:
[Cassandra.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3343645/Cassandra.zip)

**Comment by davidpwbrown** [comment]
Same as https://github.com/CleverRaven/Cataclysm-DDA/issues/31872

will be fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/31696

**Comment by esotericist** [comment]
Apparently this is a duplicate and I failed at searching, closing as such. XD
