### ISSUE TITLE
Lit charcoal kiln is an infinite portable light source

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32021]
0.D-5119-g9265810de1

[2019.06.28-2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3344064/2019.06.28-2.zip)

**Comment by Regularitee** [comment]
Possibly related, but I've noticed that when I dropped smartphones with low batteries on the ground, they would continue to emit light seemingly forever (or at least for days on end, despite only having 3% power left; remaining power would remain fixed and never change). This issue did not occur when they were in the player inventory, however.
