### ISSUE TITLE
Impossible to insert meat into a smoker from a nearby vehicle fridge

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32025]
# Steps To Reproduce

1. Load the save.
2. `e`xamine the metal smoking rack.
3. `f Insert food for smoking... remaining capacity is 15.00 L`
4. Select chunks of meat, agree with 30 pieces.
5. `e`xamine it again and see nothing changed, even though the log says that `You carefully place 30 chunks of meat in the rack.`

# Versions and configuration

0.D-5136-g62721bf65d

# Additional context

[2019.06.28-2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3344651/2019.06.28-2.zip)

**Comment by Night-Pryanik** [comment]
Cannot confirm on 0.D-8431. Loaded your save, put chunks of meat in the rack, inspected the rack. The meat is here.
![изображение](https://user-images.githubusercontent.com/11132525/66706566-67b5ba00-ed45-11e9-823f-dfe41542370f.png)

Closing for now, ping me if this is still an issue.
