### ISSUE TITLE
Crafting fails when crafting with UPS modded tool outside of inventory

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#32039]
# Describe the bug
Crafting stops at 4% with message: "You no longer have a none and can't continue crafting"
Happens when using UPS modded tool and the tool or UPS itself is outside of inventory.

# Steps To Reproduce

1. Make a player with a chunk of meat, food dehydrator, ups mod, ups and disposable heavy battery.
2. Mod dehydrator with ups mod, reload ups. Drop all items.
3. Try to craft dehydrated meat.

# Expected behavior

Crafting should work.

# Versions and configuration

 - OS:: Windows 7
 - Game Version: 0.D-5150-g645d84c (tiles), build 9253, pretty sure it started with 9244
 - Graphics version: Tiles
 - Mods loaded: default, tested on new world, new game

**Comment by ipcyborg** [comment]
Can't reproduce in 0.D-8386-g311109a0ea.
Probably fixed by this PR #33194.

**Comment by RDru** [comment]
Yes, looks like fixed.
