### ISSUE TITLE
Zombies smash ground when they chase you.

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#32032]
For some reason any zombie will punch the ground when they chase you. With soundpack on it sound annoying and it just plain weird.

**Comment by l29ah** [comment]
Zombies like smashing anything for the fun of it. Sometimes a zombie is bored and smashes some car it happened to walk near, and that produces a sound that excites other zombies to come to the sound source and smash anything blocking the way, until the car is reduced to rubble.

**Comment by matt32106** [comment]
This is also very useful in preventing you from using your shopping cart as a shield!

**Comment by FulcrumA** [comment]
It's possible that it was meant to simulate shuffling and stumbling of the zombies, them bouncing from barely noticed obstacles etc but indeed, in practice it's more like zombies randomly smashing stuff around them full force and a reason why many locations populated by them are messed up.

**Comment by SomeDeadGuy** [comment]
But they also punch pavement if there is nothing there. They also punch and destroy gravel.
It is like they chase you, stop, bend over, slap what ever is (even if it is sidewalk) in front of them and keep going.

**Comment by glenmack** [comment]
Not sure how the attack system currently works for zombies, but it probably needs to run a check for furniture/structure/vehicle/player before committing to the smash. I actually like them smashing the ground, but it happens way too often, it can make combat weird, as I've had a a zombie stand 2 spaces away and bash the ground in front of me three times in a row.

If I was reprogramming it, I would probably have them check for a structure at the location and then if not, only smash the ground maybe 2% of the time. Possibly also grounding the zombie (simulation of them falling down?).

**Comment by Zombiemanpig** [comment]
Don't forget when they smash a tile with a stack of your stuff on it and everything is instantly destroyed by the one punch zombie.

**Comment by l29ah** [comment]
Not everything, just glass stuff. And i find it's a good point: you should guard your junk from zombies.
