### ISSUE TITLE
Corrupt map files - new player questions

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#32034]
The issue:
I play on 2 PCs, my desktop at home and a laptop that I take for business trips. To get the state of my current game I use an USB stick to copy the save/<my current game> directory from one machine to the other. It works but I have noticed that after 6/7 copies some of my map files have become corrupted. I made a small python script to detect the bad files and copied them from a previous save but this is really long and am not sure it completly fixes the save.

Questions:

1. Is there away to secure the copy from one machine to the other to prevent file corruption?
2. Are there any utilities around that can help detect corrupted files? (I assumed that testing for non ascii chars in maps files was good enough but it does not cover all cases)
3. Any other advice from multi-PC players?

**Comment by ZhilkinSerg** [comment]
If corrupt maps appear in destination after copying it is probably environmental issue. I suggest making archive for copying, copy it and unpack on destination - if copying would fail, it won't be possible to unpack archive. Alternatively use some utility to create and test checksum of copied files. If you are familiar with Python, you can even use your own scripts to calculate and test checksums.

**Comment by matt32106** [comment]
I agree, making a zip file of the save is probably the best way to make sure everything is ok and with the way usb works on linux it is much faster to zip & copy 1 file than copy 7200 small files.

**Comment by kevingranade** [comment]
Additionally if you use an archive manager like zip or tar, itcwill checksum your data.
