### ISSUE TITLE
second hub mission not giving required items to complete

### ISSUE THREAD

**Issue by b0urgeoisie** [CleverRaven/Cataclysm-DDA#32035]
# Describe the bug

Accepting second mission from the intercom opens a trade menu with only a crossbow in it, says "you can't afford it!" when exited out from. Does not supply the two items to complete the quest.

# Steps To Reproduce

Accept second quest from the intercom @ hub.

# Expected behavior

Would provide you with two items required to complete the quest.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5116-gaef757f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Classes and Scenarios Mod [more_classes_scenarios],
    Simplified Nutrition [novitamins],
    StatsThroughSkills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Disable Religious Texts [no_religious_Texts],
    Safe Autodoc [safeautodoc]
]

# Additional context

[Escalante.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3346574/Escalante.zip)

**Comment by casswedson** [comment]
I can't really find much info on pull request related to this, but I just completed the first Hub 01 mission and was given the items necessary for the second mission.
![image](https://user-images.githubusercontent.com/58050969/113433084-27685280-93a4-11eb-9b6c-c2a89f2b2827.png)
- Game Version: 0.E-10188-gd02fc13 [64-bit]

**Comment by b0urgeoisie** [comment]
uh this was a long ass time ago. i'm just gonna close it.
