### ISSUE TITLE
Yugg attack bugs

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#32046]
Yugg attacks appear to have a number of issues:

* They do not trigger a warning prompt if they fire mutagen darts at you during a task (e.g., "You are hurt! Do you wish to abort the task?")
* Their mutagen darts appear to function as a vision attack (like the Flaming Eye; it only needs line of sight, and completely bypasses bulletproof glass without breaking it). However, this appears to contradict the combat log, which states that they fire a physical projectile, and projectiles should either be stopped by (or destroy) materials like bulletproof glass.
* Despite being supposedly "non-lethal", the attacks can still damage equipment and gear.

**Comment by kevingranade** [comment]
Follow the issue template
