### ISSUE TITLE
Cutting Log into planks consumes no time.

### ISSUE THREAD

**Issue by lgordon85** [CleverRaven/Cataclysm-DDA#32048]
# Describe the bug
*Using* a Wood axe to cut a log into planks is a zero time action, time is not advancing at all.

# Steps To Reproduce

Wield Wood Axe
Activate Wood Axe
Select Cut a log into planks

# Expected behavior

Some amount of time passes each time you split a log into planks.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-5165-g5122325 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Bootleg Walkers [Bootleg_Walkers],
    Garden Pots [growable-pots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Fungal Monsters [No_Fungi],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by l29ah** [comment]
55213a08266985ceb636d9c7434d552597e063c4 is the first bad commit

**Comment by l29ah** [comment]
`p.moves -= <moves>` doesn't work as it expected to, spending 81.(81) less time than specified.

**Comment by l29ah** [comment]
Ok, i see it, fix is going in shortly.
