### ISSUE TITLE
Unfolding a folded vehicle in another vehicle results in the folded vehicle vanishing

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32057]
# Steps To Reproduce

1. Load the saved game.
2. Unfold the `folded BUDDY`.
3. Enjoy.

# Versions and configuration

0.D-5165-g5122325667

# Additional context

[2019.06.28-2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3349135/2019.06.28-2.zip)

**Comment by Inglonias** [comment]
This seems like a pretty simple problem to me. You can't have two vehicles occupying the same tile at the same time. Fixing that seems like a hassle. Maybe just make it so that if you try to unfold the cart inside a vehicle, the game just says "don't do that"

**Comment by jasonmbrown** [comment]
> This seems like a pretty simple problem to me. You can't have two vehicles occupying the same tile at the same time. Fixing that seems like a hassle. Maybe just make it so that if you try to unfold the cart inside a vehicle, the game just says "don't do that"

Hopefully whoever does fix this bug, Doesn't literally use "don't do that" as the string. Id suggest something along the lines of "[Vehicle Name] is too large to unfold here." or "You cant see how [Vehicle Name] can fit here, and keep it folded."

**Comment by Inglonias** [comment]
I mean, in certain instances dragged vehicles collide with errors in the movement code, and trying to mop a space you are standing in causes the universe to implode and reform around you. "Don't do that" is pretty mild by comparison.

I agree with you, I just wanted to share these other absurdities, honestly.
