### ISSUE TITLE
Taking items from broken/inaccessible location

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#32060]
# Describe the bug

I found a crashed heli. Its stowaway board tile was broken and thus in theory unable to hold items - but it somehow did (MRE ravioli and a battery IIRC) despite no indication (I've decided to examine the tile anyway and was surprised by "Get items" option).

Upon an attempt to get those items, an error message appeared as pasted below.

# Steps To Reproduce

1. Attempt to get items from a broken, volume-holding tile of a vehicle.

# Expected behavior

Items in a tile that shouldn't be able to hold them anymore are automatically dropped on the ground

OR

Items can be pulled out of the wreck but cannot be put in. Either/both without any error messages.

# Screenshots

Location in question. Bonus in form of really garbled examine message. Also, notice the tile indicating no stored items (lack of green exclamation mark) but they are there. Sitting. Teasing me with unattainable ravioli goodness.

![stowaway](https://user-images.githubusercontent.com/38487938/60504624-3b0ff200-9cc2-11e9-8607-f78874aefe8f.png)

# Versions and configuration

 - OS: Win7
 - Game Version: 0.D-5172-g0d99a68 (experimental 9257)
 - Graphics version: Tiles
 - Mods loaded:  "dda", "ew_pack", "blazemod", "Tanks", "No_Fungi", "no_flaming_weapons", "StatsThroughSkills"

# Additional context

 DEBUG    : Tried removing item from object which did not contain it
 FUNCTION : item visitable<T>::remove_item(item&) [with T = vehicle_cursor]
 FILE     : src/visitable.cpp
 LINE     : 504

(Edit) Also, apparently items one attempts to pick up do land in one's inventory. They just are duplicated though per every attempt to pull items from the tile. Reporting it here since technically it's all effects of a single bug.

**Comment by ProfoundDarkness** [comment]
Huh... I just noticed this myself, ended up with about a dozen small batteries from a military vehicle storage compartment.

**Comment by Night-Pryanik** [comment]
Ok, closing for now, ping me if this is still an issue.
