### ISSUE TITLE
active items on map do not appear to process correctly

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#32079]
# Describe the bug

Items on the map do not appear to be processed correctly. The thing that brought this to my attention is investigation into a bug that was reported to me in Magiclysm: if an ethereal item is dropped on the ground it will no longer count down its turns.
(related bug report https://github.com/KorGgenT/Cataclysm-DDA/issues/77)

I checked this with a regular flashlight with batteries, and it did not count down while on the map either, so something is going on with one of the various map::process_items() functions.

note: i did not check if this is true in vehicles, but it likely is and could be a related function.

# Steps To Reproduce

drop a flashlight with batteries in the on state on the ground and wait. don't just spawn an on one in, because that one has infinite batteries.

# Expected behavior

active items and items that return true in item::need_processing() to be processed while on the map.

# Versions and configuration

 - OS: Windows 10
 - Game Version: pulled from latest master 
 - Graphics version: [Tiles]
 - Mods loaded: [dda, Magiclysm, no_npc_needs]

**Comment by Hirmuolio** [comment]
Did you try to reproduce that poured item has no defined temperature bug on game not built on VS? This sounds like they could be caused by same thing.

**Comment by Inglonias** [comment]
I noticed that some foods not in my inventory would not defrost or cool off in a recent game. Possibly related?

**Comment by KorGgenT** [comment]
actually not related, but i also think that may be fixed already. make a new issue if it still exists though @Inglonias

**Comment by BevapDin** [comment]
It does work just fine, it's just very, very slow.

The active flashlight has "power_draw" set to 10,000 ("data/json/items/tool/lighting.json") and the game assumes one battery charge equals 1,000,000 "power_draw" charges ("src/item.cpp").

The numbers are converted with code that is essentially `roll_remainder` (so 100,000 power draw means the item consumes 1 charges every 10 turns (in average)). So a flashlight (power draw 10,000) will consume one charges every 100 turns (in average).

Note: testing this with a lightstrip and an electric carver shows it works.

----

So the actual problem (if any) is probably on of:
- some items consume way too few power (requires more or less only changing some JSON), or
- there is not enough feedback that power is actually consumed (e.g. batteries should not store number of Kilojoule but some smaller unit).

**Comment by KorGgenT** [comment]
All ethereal items spawned from magiclysm are supposed to count down every single turn. This may or may not be related to power draw at all, but it definitely shows that the items are only getting processed every once in a while

**Comment by BevapDin** [comment]
According to https://github.com/KorGgenT/Cataclysm-DDA/issues/77#issuecomment-508591355 it is already fixed for the magic items. And I have just tested it and the magic light counts down and is removed even when on the floor.

**Comment by KorGgenT** [comment]
oh that's great!
