### ISSUE TITLE
No triffids mod obsolete?

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#32081]
Currently the no triffids mod is obsolete, despite apparently being updated at the start of the year to conform with terrain blacklisting. It was not made active at this time. Was reverting obsolescence an oversight or is there an issue with the current mod as it stands?

**Comment by ZhilkinSerg** [comment]
Obsolete mods are not visible in UI for selection, but are still working in savegames started prior to obsoletion thus they are supported and should receive required bugfixes.

**Comment by glenmack** [comment]
That doesn't explain why it is obsolete now, nor does any of the changes in the past.

**Comment by Zireael07** [comment]
@ZhilkinSerg: I believe the OP's question would better worded as "why the mod is obsolete"?

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/19124:

```
Four mods are marked obsoleted:

    Animatronics (minimal popularity, outdated)
    Dino mod (minimal popularity, outdated)
    Mundane zombies (list oudated and hard to maintain, nearly duplicated by only wildlife)
    No triffids (minimal popularity)
```

**Comment by glenmack** [comment]
The irony of this is the fact that I went looking into the mod files because none of the "No X monster" mods are seemingly being maintained, despite being popular. Of those four listed, two are no longer obsolete, and the reason I asked why No triffids was obsolete was because I want to fix it, if something is wrong.

**Comment by ZhilkinSerg** [comment]
Mods that are not being maintained are getting obsolete. When someone picks them up, fix bugs or adds features - they are getting deobsoleted. Alternatively one can pick obsolete mod, put it to separate repo and maintain there.

I personally do not like the whole idea of multiple "No X" mods. IMO we need world options UI which allows blacklisting and whitelisting monsters by ids, flags, factions, species, etc. with possibility to save/load templates - basically "create your own mod UI".

**Comment by Zireael07** [comment]
@ZhilkinSerg: I believe such a whitelisting/blacklisting idea was raised a couple of times but I can't find it atm.

**Comment by kevingranade** [comment]
This isn't a forum for questions about the game, ask elsewhere.
