### ISSUE TITLE
Meat Overhaul

### ISSUE THREAD

**Issue by roaringjohn** [CleverRaven/Cataclysm-DDA#32087]
**Is your feature request related to a problem? Please describe.**  
I sometimes think about the fact that, no matter what animal you butcher, you get "chunks of meat". No differences between dark, white, or red meat. No differences between pork, chicken, beef, or any other kind of animal meat, even "cockroach meat" apparently. There aren't even differences between the organs of very different animals.

**Describe the solution you'd like**  
I suggest a major overhaul of the meat that is harvested based on the animal it comes from. Beef should be beef, for example, and not be interchangeable with chicken, two _very_ different kinds of meat. This may be gradually implemented of need be, maybe even put off for 0.E experimental builds. This overhaul of meat will allow for a more diverse array of recipes and items that make sense. A future recipe, for example "ham and cheese sandwich", would make more sense if it were made of actual pork, not "chunks of meat".

**Describe alternatives you've considered**  
Because of the amount of work likely to be involved, it could be simplified to merely "dark meat", "white meat", and "red meat", if need be. Or, of course, it could all just remain "chunks of meat".

**Comment by TechyBen** [comment]
Sounds a sound argument. Though as for most recipes, you can interchange meats. Ham sandwiches, minced meat (beef sausages, chicken etc exist), Pork burgers etc.

There are times when only a type of meat fits, Kentucky fried beef is probably not totally doable, due to texture differences (though chinese style fried beef is).

So I;m not sure if red/white/dark as you say is easier/more applicable... or not. :/

**Comment by YakumoChen** [comment]
Most meat is game animal though. While I suppose it can make sense to limit a few recipes to bird meat only, for instance, the vast majority of meat collected is not going to be from your traditional livestock. 

This is one instance where I think it's fine to have some amount of abstraction beyond, perhaps, separating birds from other animals for recipes.

**Comment by roaringjohn** [comment]
That is probably a good compromise, then, bird meat being its own thing.

I did say, however, that this could be "gradual". Pushed off for later, if need be. It doesn't need to be implemented within a week or whatever.

**Comment by kevingranade** [comment]
It sounds like an absolutely gigantic amount of work (adding a lot of meat types, and tons of recipes, as well as new recipe outputs) for a more or less nonexistent benefit. The reality is that most meats are more or less interchangeable from our point of view, it doesn't much matter whether it's Kentucky Fried Chicken or Kentucky Fried beef the reality is it has some amount of protein in some amount of fat and it tastes pretty good. We already have a system for adjusting the output of recipes based on the inputs, so we can capture that kind of thing with just different meat types, which is the smallest amount of work.

**Comment by FulcrumA** [comment]
I'd like it if the game would track the source of the meat but I'd also like the recipes to require items of particular type rather than specific IDs in every case. If one would have just to add huge list of all meats to every recipe, it'd be a horrible bloat.

**Comment by sdp0et** [comment]
While getting too detailed would just add more stuff for the engine to track I do see benefits to separating out some meat:

- insect/arachnid meat could come with a joy penalty
- shellfish could have a higher joy bonus than regular meat
- it would allow more specific allergies (shellfish)
- different decay rates (fish becomes impalatable faster than red meat).
- meats that require higher cooking skill to consume safely (bird/reptile meat is more likely to have Salmonella contamination, pork could be more likely to have parasites than other meats)

a full separation by type could have other potential affects:
- joy or concentration debuffs for the religion leader templates 
-- pork(imam/rabbi)
-- shellfish(rabbi)
-- beef(priest on day numbers that are multiples of 7)
- specific meat allergies (I know two people who are allergic to beef but not other meats)
- giant lone star tick that afflicts a long term but temporary allergy to certain meats
