### ISSUE TITLE
Map file numbering logic explained somewhere?

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#32093]
Is the map numbering logic described somewhere? I would like to be able to figure out which map file starts where with regard to my character's position (e.g. file x.y.0.map starts 5 squares left of my character's position). 

Thanks

**Comment by anothersimulacrum** [comment]
This isn't a forum to ask questions on, this is a bug reporting page. 
If you are saying that the map file numbering is not documented somewhere, that is a legitimate concern.

**Comment by kevingranade** [comment]
Other than in the code, it is not.
