### ISSUE TITLE
Crash when trying to load save after update

### ISSUE THREAD

**Issue by illneverrememberthislogin** [CleverRaven/Cataclysm-DDA#32090]
# Describe the bug
Crash when trying to load save after update

 DEBUG    : Error: line 55:20: no such item type

        "M": [ { "item": "magic_shop_books", "chance": 40 }, { "item": "magic_shop_potions", "chance": 60 } ],
        "C": [
          { "item":
                   ^
                    "basement_utility_closet", "chance": 55, "repeat": [ 1, 2 ] },
          { "item": "magic_shop_potions", "chance": 15, "repeat": [ 1, 2 ] }
        ],

 
 FUNCTION : bool main_menu::load_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 980

# Steps To Reproduce

1. Load a save

# Expected behavior
Save loads

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

<!-- Please complete the following information; you can now go to:
CRASH LOG FILE: config/crash.log
VERSION: 0.D-5172-g0d99a68
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x590265[cataclysm-tiles.exe+0x190265]
    @0x590D32[cataclysm-tiles.exe+0x190D32]
    SMPEG_error+0x4B034@0xF02770[cataclysm-tiles.exe+0xB02770]
    _C_specific_handler+0x98@0x7FF8148D7C58[msvcrt.dll+0x27C58]
    _chkstk+0x11D@0x7FF814EEF7DD[ntdll.dll+0x9F7DD]
    RtlWalkFrameChain+0x13F6@0x7FF814E5D856[ntdll.dll+0xD856]
    KiUserExceptionDispatcher+0x2E@0x7FF814EEE70E[ntdll.dll+0x9E70E]
    @0x86BAE9[cataclysm-tiles.exe+0x46BAE9]
    @0x9220F0[cataclysm-tiles.exe+0x5220F0]
    initterm_e+0x1AB@0x7FF8148EA2BB[msvcrt.dll+0x3A2BB]
    @0x89F743[cataclysm-tiles.exe+0x49F743]
    IMG_LoadWEBP_RW+0x55E72B@0x1552D0B[cataclysm-tiles.exe+0x1152D0B]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FF814164034[KERNEL32.DLL+0x14034]
    RtlUserThreadStart+0x21@0x7FF814EC3691[ntdll.dll+0x73691]

 - OS: Windows 10
 - Game Version: [0.D-5172-g0d99as68 (tiles)]
 - Graphics version: Tiles - Dead People
 - Mods loaded: [ 
![image](https://user-images.githubusercontent.com/52499911/60599773-40297b80-9d6c-11e9-8da7-841f5b547806.png)
]

**Comment by KorGgenT** [comment]
what build are you on?
can you provide the save please?

**Comment by illneverrememberthislogin** [comment]
Troubleshooting:
Clean install, new world, new character: Success
Clean install, legacy world, new character: Success
Clean install, legacy world, legacy character: Success w/ ignore-able errors flagging if I spoken to NPCs previously or not.

Concluding I must have overwritten something in the config backup I pushed back into the main CDDA folder when trying to preserve keybindings. Please disregard issue.

**Comment by illneverrememberthislogin** [comment]
Closed due to troubleshooting finding resolution
