### ISSUE TITLE
Disturbing frequency of suicide among mobile home population

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#32116]
# Describe the bug

Presumably due to lack of variation in trailer park design despite its commonality, one regularly stumbles upon it, with one of the trailers holding barricaded uninfected corpse. A much more common version with no such would be useful as "one mandatory barricaded suicide/murder victim per trailer park" takes away from immersion rather than adding to it.

# Steps To Reproduce

1. Explore trailer park locations

# Expected behavior

Suicide/murder victims do not appear in exactly the same place in every instance of the location

# Versions and configuration

 - OS: Win7
 - Game Version: 0.D-5196-g2660168
 - Graphics version: Tiles
 - Mods loaded: "dda", "ew_pack", "blazemod", "Tanks", "No_Fungi", "no_flaming_weapons", "StatsThroughSkills"

**Comment by kevingranade** [comment]
Requests for more content variety is not an issue worthy topic.

**Comment by FulcrumA** [comment]
It's not a request for variety. It'd be one way to solve it but the issue _is_ that currently, even if due to lack of variety the corpse keeps appearing at every trailer park.
