### ISSUE TITLE
Idea: towel hanger

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32129]
**Is your feature request related to a problem? Please describe.**  
It's uncomfortable to find and use towels in your RV that is full of loot.

**Describe the solution you'd like**  
It would be nice to have a "towel hanger" vehicle part that is, like a faucet, can be interacted with `e`xamine to towel yourself up. Also it would dry out faster, since the towel(s) are distributed, allowing better air exchange. "towel dryer" that dries towels at expense of electric energy would be cool too.

![](https://www.sohohome.com/media/catalog/product/cache/5/image/2000x/bcf7ce64d63d93f1f374273bba74938d/f/a/farm-towel-rack.jpg)

**Comment by kevingranade** [comment]
We have one thousand, three hundred seventy one issues open right now. What leads you to believe that it is reasonable to open a content request for a window dressing item?

**Comment by l29ah** [comment]
Because it's one of the most annoying things in cdda for me atm.
