### ISSUE TITLE
Sourdough starter consumes glass jars

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32125]
# Describe the bug

`juvenile sourdough starter` asks for a glass jar that is impossible to reclaim after it's done and finally turned into bread.

0.D-5232-g7da821f239-dirty

**Comment by FulcrumA** [comment]
The former jar's glass shards are for that extra crunch?

**Comment by TychaiosIlithios** [comment]
Nice find - the whole sourdough idea seems to be for whoever is meticulous enough to find this thing in recipes and start cycles of cooking the stuff to be able to save a bit of dough cooking bread, otherwise (i.e. wasting instead of saving) the thing has little to no sense.

**Comment by I-am-Erk** [comment]
The jar contains the split sourdough you get after making bread, which can be used ad infinitum to keep making more bread every time you split it.

Someone could make a use action to empty the sourdough starter out and get a clean jar back, but it's not something you should be getting out of making bread. You never wind up with an empty jar after making bread with sourdough starter.

**Comment by l29ah** [comment]
I've grinded my cooking skills using those jars, but now i need them back!

**Comment by I-am-Erk** [comment]
Someone on discord pointed out that a disassembly recipe for the jars would probably be the answer.
