### ISSUE TITLE
Foodperson mask is 16 liters?!

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#32128]
# Describe the bug
Foodperson mask is 16L? That seems pretty big for a mask.

# Steps To Reproduce

1. Spawn a foodperson mask
2. It's 16L!

# Expected behavior
Should be the size of a mask?

# Screenshots
N/A

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5228-g9520615 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Ants [No_Anthills],
    No Fungal Monsters [No_Fungi],
    No Rail Stations [No_Rail_Stations],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins]
]

# Additional context
N/A

**Comment by l29ah** [comment]
```
Covers: The head. The eyes. The mouth.
Coverage: 100%  Warmth: 50
Encumbrance: 30
```
suggests it's a huge and awkward thing that's supposed to be an entertaining costume part used for advertisment.

**Comment by ifreund** [comment]
Yeah I'm picturing something like this:
![image](https://user-images.githubusercontent.com/12723818/60680880-609d2700-9e8d-11e9-8caf-74c313ae8ab7.png)

Pretty sure this is intended, so I'm gonna go ahead and close this

**Comment by Inglonias** [comment]
Fair enough. The description was not clear on the mask's size.

**Comment by Fris0uman** [comment]
I made the calculation using a guide to make a DeadMau5 helmet.
