### ISSUE TITLE
Friendly bugs spawned by artifacts aren't pets

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#32127]
**Is your feature request related to a problem? Please describe.**  
One of the possible artifact actions is summoning giant flies/bees/wasps that are firendly (code in iuse.cpp at 5048). These pretty creatures aren't considered player's pets and can't be played with. This is distressingly lame and disappointing.

**Describe the solution you'd like**  
Friendly bugs spawned by artifacts should be spawned as player's pets.

The code that spawns bugs is in iuse.cpp at line 5077. Please add a line that registers these new monsters as pets (b->add_effect( effect_pet, 1_turns, num_bp, true ) between lines 5077 and 5078 of iuse.cpp; taken from static function petfood from iuse.cpp at line 1483).

**Describe alternatives you've considered**  
No reasonable alternatives.

**Additional context**  
Please don't make me learn all this incredibly confusing github business just to commit one new line to the code. I've outlined the solution above, please consider it.

EDIT: Ok, this isn't a single line commit. I guess I'll try to submit a proper pull request myself after all.

**Comment by Night-Pryanik** [comment]
> Please don't make me learn all this incredibly confusing github business just to commit one new line to the code. I've outlined the solution above, please consider it.

Just a friendly advice for the future - requests like this ("Please do some thing that I don't want to do myself") are considered as a bad tone and have a very high chance to be completely ignored, even if the proposed solution is good by itself.
