### ISSUE TITLE
Disassemly on surface

### ISSUE THREAD

**Issue by communistkiro** [CleverRaven/Cataclysm-DDA#32135]
**Is your feature request related to a problem? Please describe.**  
Disassembling of heavy-ish thing- engines, any kind of bot, requires you to hold it. Having even 32 Str doesn't allow me to wield a 140kg nurse bot. There's few items in the game that would require ludicrous amounts of str, but this only strengthens the point for all chars and playstyles not having much str. 

**Describe the solution you'd like**  
Even though the nurse bot isn't required for a any recipe, there being an uncraft recipe, and being unable to (s)mash it into at least some of those components, I'm left wishing for disassembly on a table, workbench, or floor, without having to (w)ield it. 

If you're looking for realism, no mechanics is hugging an engine while working on it, no engineer is hugging the robot he's working on, etc., etc.

**Describe alternatives you've considered**  
Debug myself into even more STR, say, 100 for bot disassembly; edit bot weights?

The reworked options surfaces are great, and I believe this would be a decent edition- `e`xamine a surface with some uncraftable, and/or allow `d`isassembly of all valid items on person, and on all adjacent tiles 1--9.

**Comment by BevapDin** [comment]
You can disassemble it by "butchering" it: stand on top of it (when it's only the ground) and press the butcher key (default `B`).

**Comment by anothersimulacrum** [comment]
You can also hold heavy things when you are near something with suitable lifting quality. If you have a boom crane nearby, and you are wielding an engine, you will not have any weight penalties from the engine.

**Comment by communistkiro** [comment]
Haven't ever found or constructed a crane myself, but now I'll know to have one nearby, or an air jack, which is with the vehicle rather than underground in the labs.
