### ISSUE TITLE
Grenades aren't detonating in some lab rooms

### ISSUE THREAD

**Issue by jda03806** [CleverRaven/Cataclysm-DDA#32133]
# Describe the bug

# Steps To Reproduce

1. Make a player with a gun, magazine, and some ammo.
2. Try to aim at a wall.
3. There's no way to increase aim level.

# Expected behavior

Ideally also describe *why* you expect it to happen.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by jda03806** [comment]
Version is 9272.

I crafted a fresh EMP grenade and threw it at a turret, and it never detonated.  It's sitting on the ground as and "active EMP grenade (2/3)".  If I pick it up, it will detonate, but otherwise it never seems to advance the timer.  Only seems to happen in certain lab rooms.

Open the attached save file, town is Bargersville, character is Billy.  I'm in the room with the grenade, it's right next to me.

[Bargersville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3360478/Bargersville.zip)

**Comment by Regularitee** [comment]
I had the exact same problem a few hours with C-4 attempting to blow down a wall between the lab and a subway. Like the above poster the timer would only freeze in the lab -- when I teleported to the other side of the wall and placed C-4 there (outside the lab, in the subway tunnel, only 2 tiles away from the original location), the time functioned as intended.

**Comment by yellowcrescent** [comment]
I had this exact same issue about a week ago. But when I was in the process of submitting a github issue for it and trying to recreate the issue-- spawned in a new EMP grenade via debug mode, activated, and threw it-- it seemed to work fine.

I just tested it again (spawning in an EMP grenade via debug menu). It seems that if I throw the grenade in an area that is currently visible, it works fine. BUT if I throw the grenade in an area that I cannot currently see (eg. dark section of a lab), the grenade timer never starts counting down-- even when I can see it again.

**Comment by glenmack** [comment]
Can also confirm an occurrence of throwing an active EMP into a Lab finale and having to pick it up again before it would continue countdown.

**Comment by Edgar-cy-Lee** [comment]
Quiet interesting. I am currently in the process of clearing the city(as in, any open ground. So this is not an issue yellowcresent is describing) and I am having this issue all the time.

I should mention that if multiple grenades are thrown, all of them will stop working.
For example, if I throw 3 pipe bombs, all 3 pipe bombs in the area will stop counting down.
And if 1 of them starts working, all of them starts working. Perhaps it is linked to the active items or an area?

**Comment by EvgenijM86** [comment]
I can confirm this bug. This happened to me 1 day ago with latest git pull at that time.
