### ISSUE TITLE
Fix solar array positioning for vehicles

### ISSUE THREAD

**Issue by shotgunfrenzy** [CleverRaven/Cataclysm-DDA#32147]
# Describe the bug
Solar arrays, should be on the roof extra layer, not where they currently are

When installed in a vehicle, solar arrays take up the floor/wall layer of a vehicle, so they limit movement inside a vehicle. This being said, they also can have a roof installed over the top and can even have another solar or upgraded solar installed above them as well

# Steps To Reproduce

1.  rip out a floor in any vehicle
2.  install a solar array
3.  make sure a roof is above said solar array
4. install a normal solar panel above that solar array
5. boom the dreaded unbalanced word

# Expected behavior

Solar arrays state that they are  set on a chassis reaching several meters high, since there are no bridges we can drive under, it wouldn't be absurd if we could install these on the roof of a car. Further more, we could have a second option in the vehicle menu to add a 'roof solar array', which can be installed like a normal solar panel, not take up the floor layer and/or maybe decrease the rebar/pipe requirement in the recipe to craft it.

# Screenshots

Vehicle menu
![8kx2WclPnd](https://user-images.githubusercontent.com/32794174/60719698-d37ccf80-9f6b-11e9-94a1-4e8a2c68fef0.png)

inside the vehicle (note solar array is an impassible tile)
![JLVQs2Fugj](https://user-images.githubusercontent.com/32794174/60719742-eee7da80-9f6b-11e9-9ae4-cc8273b1f399.jpg)

Outside of vehicle (roof solar panel is clearly shown in the same spot)
![4YnvvNBQTm](https://user-images.githubusercontent.com/32794174/60719790-01faaa80-9f6c-11e9-8dbb-a0aafb455b56.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-5245-gaca7cde [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Garden Pots [growable-pots],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Icecoon's Arsenal [ew_pack],
    Mutant NPCs [mutant_npcs],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Advanced Gear [adv_gear]
]

#Save File
[Northwest Harbor.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3362522/Northwest.Harbor.zip)

**Comment by Maddremor** [comment]
Since the solar array is larger than the standard panel, it would need a more sturdy structure to keep it from collapsing. From a balance standpoint, what would be the downside of having an array instead of a single panel if the array didn't take up more space?

**Comment by shotgunfrenzy** [comment]
hell i'd be okay with it being a 3x3, if thats even possible

**Comment by Lorith** [comment]
The idea behind it, from my understanding, was that it was a floor to ceiling object that also extended above the roof.  Unfortunately you can only pick one location per component, not multiple.  Extending it to be multiple tiles is also currently not possible and would require a lot of work.

**Comment by shotgunfrenzy** [comment]
Absolutely
So having a second option in the vehicle menu to install it like a normal panel wouldn't be completely crazy, also because of its weight and such, having a requirement of a heavy duty frame or something could also be included, so you can't just put this on a normal car, for example

**Comment by sdp0et** [comment]
I think the array taking up the internal volume of the tile makes sense.  If the array can't take up the roof slot as well can they be made to check for a roof above them to determine if they are active?  In that case, installing a roof/panel over them would disable the array underneath.  Maybe a part could be added for a sunroof from a pane of glass that would allow light through (which could also enable reading/crafting in a section of the vehicle with no wall windows.
