### ISSUE TITLE
Stone axe seems to burn forever

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#32140]
# Describe the bug

Stone axe (and potentially other items) can "burn" forever.

# Steps To Reproduce

1. Make a player with a brazier, some planks, and a stone axe. Also give him some matches.
2. Deploy the brazier.
3. Drop some planks and a stone axe into the brazier and light it.

# Expected behavior

An item should either be consumed by the flames eventually and burn OR it should be fireproof and NOT be counted as fuel for purposes of checking if the fire should continue to burn or be extinguished.

# Versions and configuration

 - OS: Win7 x64
 - Game Version: 0.D-5232-g7da821f
 - Graphics version: Tiles
 - Mods loaded: None

# Additional context

I bet this has something to do with checking if an item has "wood" as its component, while also being fireproof. I dropped a few planks of wood into the brazier, but the estimates of how long it would burn for kept growing every day, from a few hours, to a day, to 2-4 days. I eventually dragged the brazier to a road, took it down, and found on that tile the brazier and a stone axe (I decided to get rid of it once I was able to craft an entrenchment tool).

**Comment by l29ah** [comment]
Yeah, i've just encountered it too. I need to re-light the fire since it goes out after a few dozen minutes, but stone axes aren't consumed.

**Comment by Ramza13** [comment]
Just tried and was unable to reproduce.  The stone axe burned into ash and pebbles

**Comment by misterprimus** [comment]
> Just tried and was unable to reproduce. The stone axe burned into ash and pebbles

It's possible it was fixed. This issue over half a year old and plenty of things have been fixed since then.
