### ISSUE TITLE
Report: zombies strangely enamored with cars full of smoke

### ISSUE THREAD

**Issue by AnderHammer** [CleverRaven/Cataclysm-DDA#3215]
For context: my current game has lasted nearly a 'year' and has spawns set to 2.0.

Zombies still come crashing out of buildings all the time, but it seems that when I generate an area but don't clear it out, then come back later, many cars have a smoker or two inside or nearby and have drawn every zombie in the area to mill around in/outside. 

This might be caused by zombies losing interest in me and going to investigate that mysterious smoke-obscured noise that was just a zombie getting stuck on an impassable vehicle part. 

This also happens sometimes, but less frequently, when a smoker is not near the vehicle.

This is also... weird.

Is this an issue or a feature?

**Comment by qbradq** [comment]
So can this be closed?
