### ISSUE TITLE
Proper Golfing

### ISSUE THREAD

**Issue by Ganymedeio** [CleverRaven/Cataclysm-DDA#32150]
**Is your feature request related to a problem? Please describe.**  
While it's not a problem, per se, it's tantalizing that Golfers start with clubs, tees, and golf balls, but can't actually use these objects in conjunction with each other.

**Describe the solution you'd like**  
I'm curious about the implementation of a way to tee-off and smack a golfball into a creature, dealing considerable bashing damage if they're far enough away to properly set it up by the time they draw nearer.  Other users on Discord suggested the ability to put things like grenades on the tee.

**Describe alternatives you've considered**  
I realize the tees and balls can be scrapped for material, but I think actual golfing is a satisfying alternative use of these items.

**Additional context**  
I was told this idea would appeal to Korg especially.  I'm kind of wondering if mechanically it could be done by just playing with/tweaking the existing mechanics for throwing or aiming.  I'm also SUPER new to the game, and apologize if that was made evident in my post.

**Comment by EirenexTheDragon** [comment]
same idea might be great for Baseball bat and baseball

**Comment by TychaiosIlithios** [comment]
Sorta reminded me of slungshots and various weapon+slungshot hybrids like kusarigama. Would be great to. But there's a problem - they require damage conversion to have ranged attack blunt and melee different. But knuckle plus slungshot seems moddable - thanks, gonna get that. 

And to contribute exactly to your subject - if it were feasible to add 'shooting with a high chance of damaging' then baseball bats could be used to fire stones and.. grenades - but if your skill check fails and you fail the launch - you've got a really sweet homerun inspiration.
