### ISSUE TITLE
Ants spawn rate and panting

### ISSUE THREAD

**Issue by Heikelol** [CleverRaven/Cataclysm-DDA#32161]
Game version: 9274 (9 hours ago)

Operating system: win10

Tiles or curses: Tiles

Mods active: magiclysm, CRIT

### Expected behavior

Panting should take only some instants, and not days.
Ants spawning rate may be too high, if they can keep spawning at a faster pace that a player could kill them.

### Actual behavior

Panting after taking a step and fighting 400 ants for 20 hours. I got an stamina lock of the UI and after I killed all the ants with counter-attacks, I keep panting even after sleep.

### Steps to reproduce the behavior

Just play the save, I keep panting.
[Wyoming.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3363437/Wyoming.zip)

**Comment by kevingranade** [comment]
Player should have collapsed and become helpless from extreme stamina drain long before this.
Even before that, counters and dodging should have become ineffective.

**Comment by KorGgenT** [comment]
maybe after the winded effect gets up to a certain duration it should advance to some other worse effect, or have another intensity or something.

**Comment by Heikelol** [comment]
Winded and stamina drawcan become very extreme playing an unarmed build in long fights. 

Maybe the stamina draw from unarmed attacks could scalate with the unarmed skill, that would prevent UI locks from winded effect.

Killing less than 10 ants with unarmed 7 draws all you stamina. After that, you can only kill any remaining enemies by autoattacking with counters while the UI is locked if they swarm you. Given that an ant lab can have more than 400 ants in a single floor, that would be a problem for an unarmed character.

**Comment by ifreund** [comment]
>Given that an ant lab can have more than 400 ants in a single floor, that would be a problem for an unarmed character.

Yes, that is 100% intentional.  If killing 400 giant ants with your bare hands *wasn't* a problem *that* would be a bug.

**Comment by Heikelol** [comment]
The problem is that after you became winded for the first time, you keep dodgind and counterattacking the incoming swarm, and you cannot just wait to recover stamina for fleeing, as every new counterattack draws more and more stamina and increases the winded effect. You are UI locked.

**Comment by kevingranade** [comment]
Yes counter-based UI lock is a known issue, see #25859
``The problem is that after you became winded for the first time, you keep dodgind and counterattacking the incoming swarm``
I agree, you should stop dodging and counterattacking and the ants would overwhelm you if you can't get away.

**Comment by I-am-Erk** [comment]
The fact that you can counterattack and dodge while out of stamina is definitely a bug.

I'd suggest that the fix should be that your chance to counterattack or dodge is multiplied by sqrt(fraction of remaining stamina)

So if you have 90% of your stamina left, your chance to dodge is sqrt(0.9) or 95 percent full.
If you're down to half stamina, your chance to dodge is down to 70% of what it is when you're at full.
By ten percent stamina, you have about 1/3 your usual chance to dodge/counter.
If you hit zero stamina, your chance to dodge is zero.

**Comment by Heikelol** [comment]
> The fact that you can counterattack and dodge while out of stamina is definitely a bug.

> I'd suggest that the fix should be that your chance to counterattack or dodge is multiplied by sqrt(fraction of remaining stamina)

Thats a point, but maybe counterattacking should not have a stamina cost (you only do it when there is an opening and when you find it easy). Anyway it's not an action from the player and it's random, so I feel a little unfair giving a stamina cost to that.

**Comment by I-am-Erk** [comment]
You can always switch to a technique that doesn't use counterattacks.

**Comment by Heikelol** [comment]
If the UI is locked, then you can't, thats the point. Anyway I see you have noticed the problem before as kevingrenade shows.

**Comment by TychaiosIlithios** [comment]
I'll throw in a sudden idea here. Have stamina being a protecting stat for different problematic checks every now and then. 
Above 75% all checks passed.
Above 50% swimmer sometimes says he's not so sure about swimming. (about 1% per turn to trigger, no more often than once per 5 turns), penalties to climbing chances even if parkour expert
Above 25% - heavy panting and suggestion to take a break, hit and dodge penalties, rare proc for skate falling
Above 10% - panic messages higher% but no more often than once in 10 turns, high dodge etc penalties, huge panalties to climbing and avoiding falls, proc to stumble, proc to fall in melee, proc to fall while dodging, actions like butchering will request 'continue/slow per stamina/abort' prompts.
Below 10% - all above plus procs to faint, becoming very high in percentage at 0%
Using rest action or driving not only skips time resting but prevents procs - it's not that pressing to fall down when you're sitting.

Alzo - if this sys were to be considered then focus could become a proactive stat, significantly boosting checks below 25%
Alzo - besides focus extra perks could be implemented for managing such conditions from simple percentile gains to second breath kind of thing resulting in buff with perfect stamina for 50 turns then 'winded' for an hour. 

Reasons for such suggestion is to ever again give a feel of gambling, interactivity and meaning to stats and conditions - in this case stamina and focus. Alzo this might result in next wave of attention to combat stimulants and possible buffs they provide vs zombie hordes and stamina strain they impose.
