### ISSUE TITLE
Repairing vehicle parts requires no components

### ISSUE THREAD

**Issue by Rogal-Dorn** [CleverRaven/Cataclysm-DDA#32172]
# Describe the bug
When repairing vehicle parts on a vehicle if it still has some health then it only requires electricity to repair it. If you remove the same part and try to repair it with the same tool, it will require components.

# Steps To Reproduce
1. Make a character with a makeshift welding rig and batteries (I assume it works for anything)
2. Find a damaged battery
3. Try to repair it in your inventory. Fail as it requires plastic chunks
4. Install it onto anything, repair it with no plastic chunks

# Expected behavior

Repair of items to remain consistent

 

# Screenshots
![z3P9DQ0 1](https://user-images.githubusercontent.com/52333807/60746429-b1c02000-9f4c-11e9-9998-4905e8c025c7.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-5269-g1b27404 (tiles)
 - Graphics version: Tiles
 - Mods loaded: None

# Additional context

**Comment by Edgar-cy-Lee** [comment]
I should also add that, some components may require different ingredients to fix.

Seatbelt - which is short rope - is fixed with duct tape/superglue when attached to the vehicle.
In short rope form, it takes threads from tailors kit instead.

**Comment by TychaiosIlithios** [comment]
I'd like to mention here the simple basics of plastics repair for anyone caring to read. 'cuz fully realistic plastic repair is already close and easy to being done by the game engine.

point zero - optional - there are 5 main kinds of plastic, and being a complete reality freak, could ask for at least a couple of types to be implemented. (different types of plastic don't weld together well)
1)  polishing - before fixing the damage, the surface should be polished or whatever used for gluing will fail to grab
2) should the damage be extensive, first a hot staple gun is used to insert metal wires to hold the cracked part in place.
3) then a piece of plastic (of the same type/optional) is melted (with a soldering tool) to fill the majority of the gap. 
4) lastly glue can be used to cover any leftover dents 
(and speaking of glue, hot glue gun and sticks are nowdays anywhere, and should they be found and powered, glue and duct tape problems should be lessened by a degree)

so in theory a completely realistic plastic repair could look like 
less than 100%? Hot glue gun/glue (not really sure about duct tape)
less than 75%? +polisher, solder and plastic
less than 40% AND item heavier than 5kg? +hot staple gun (you really would not use it to fix a plastic bottle)

ofc there are plenty more real tools for this job, but irl in workshops about 90% of plastic (and 50+% rubber) non-cosmetic work is done or can when need be be done with this toolset.

**Comment by hexagonrecursion** [comment]
> Repairing vehicle parts requires no components

This has been fixed by #53431

I'll split out specific cases of repair inconsistency into their own issues to make it easier to keep track of progress.

**Comment by anoobindisguise** [comment]
This can be closed now right?
