### ISSUE TITLE
Crashing everytime loading a save (Crash whilst driving to new map sector?)

### ISSUE THREAD

**Issue by knyghte** [CleverRaven/Cataclysm-DDA#32173]
# Describe the bug

I was driving down the road and perhaps encountered a new "map sector" which proceeded to complain about not being able to generate things. Continued through it but crashed as soon as it got back into game world. Cannot load save game from there on in, crashes everytime.

# Steps To Reproduce

Attempt to load the save game.

# Expected behavior

It should load?

# Screenshots

 DEBUG    : map::saven grid (0,0,-2) uninitialized!
 
 FUNCTION : void map::saven(int, int, int)
 FILE     : src/map.cpp
 LINE     : 6664

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-5270-g43d7a86
 - Graphics version: Tiles

# Additional context

[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3364089/logs.zip)
[Cyberworld.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3364091/Cyberworld.zip)

**Comment by knyghte** [comment]
`22:43:59.712 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: robot_dispatch_second (robot dispatch center)`

This line appears in the debug.log but even when disabling the mod through the mods.json file in the save game folder doesn't appear to stop the problem from happening.

**Comment by KorGgenT** [comment]
closing as this is a duplicate. see #32169 for related issues, and proposed fix.
