### ISSUE TITLE
Add item category filter to auto-pickup rules

### ISSUE THREAD

**Issue by snake-eater911** [CleverRaven/Cataclysm-DDA#32186]
At the moment you can filter auto- or NPC-pickup by item materials, but it would be nice to also filter items based on their category, for example
```
cat:vehicle parts
cat:armor
```
and so on...
And it would also be neat to have compound filters like:
`m:cotton&cat:clothing`

**Comment by TychaiosIlithios** [comment]
And it would be even more fun to have such switch carried to external file so that whoever feels nerdy about micromanaging stuff, can mod the life out of this file till his own precious lists are purr-fect.
