### ISSUE TITLE
Oxygen Tank Useless / Not Balanced for 1 sec/1 turn

### ISSUE THREAD

**Issue by RedPine91** [CleverRaven/Cataclysm-DDA#32184]
# Bug

Oxygen Tank requires 10 seconds to use, and grants no noticeable increase in stamina gain.  This is likely due to the 1 sec/1 turn rebalance which adjusted turn times and inflated the stamina pool.

# Steps To Reproduce

1. Run until winded (a single red ":" on the stamina bar)
2. Look at the in game time.
3. Use an oxygen tank.
4. Watch as you waste 10 seconds to refill less than a single stamina bar.

# Expected behavior

IIRC, before the 1 sec/1 turn change, oxygen tanks could be used to refill stamina while you ran from enemies.  In any case, the item is currently useless.

# Possible Fix

Increase the amount of stamina regained.  Current time to use is fine if the stamina regained is very significant, otherwise the time to use should be drastically reduced.  

# Versions and configuration

Experimental 9272, windows 10.

**Comment by I-am-Erk** [comment]
This is a strange use of oxygen tanks anyway and should just be removed. Hypoxia isn't why you run out of stamina.

**Comment by chaisawlajatang** [comment]
I-am-Erk,
https://www.ncbi.nlm.nih.gov/pubmed/28775065
>Exercise performance is determined by oxygen supply to working muscles and vital organs

>In studies performed near sea level in healthy subjects, as well as in patients with PH, maximal performance during progressive ramp exercise and endurance of submaximal constant-load exercise were substantially enhanced by breathing oxygen-enriched air

**Comment by Metalsoul212** [comment]
I disagree with Erk. Seeing as stamina drain has been increased significantly in recent builds and also considering how deadly it is I think the use of oxygen tanks is a nice counterbalance. Maybe, instead of an instant boost to stamina, just having it end or even prevent the winded effect on use and perhaps apply an 'Oxygenated' effect that slightly increases stamina regeneration for a short time.

**Comment by I-am-Erk** [comment]
From that paper, you see my argument displayed eloquently: [the effect of hyperoxigenation on performance in healthy individuals is measurable, but miniscule](https://www.physiology.org/na101/home/literatum/publisher/physio/journals/content/jappl/2017/jappl.2017.123.issue-6/japplphysiol.00186.2017/20171226/images/medium/zdg9991723590004.gif). The current benefit of the oxygen tank roughly represents how much difference it actually makes.  You'll note that the authors of the paper rather conspicuously tall about their results being "significant" but don't talk about the magnitude of the difference when they can possibly avoid it.  I don't think there's a lot of value to simulating that

**Comment by kevingranade** [comment]
> IIRC, before the 1 sec/1 turn change, oxygen tanks could be used to refill stamina while you ran from enemies.

You do not remember correctly, the oxygen tank does not have this effect.  What it does do is cure the, "winded" effect immediately, which is also a debatable use.

**Comment by Yuzuke** [comment]
this is a stupid fix, just remove the o2 tank out of the game.
