### ISSUE TITLE
Game watch doesn't lose charge

### ISSUE THREAD

**Issue by Redbox12236** [CleverRaven/Cataclysm-DDA#32191]
Game watch doesn't lose battery charge after being played. 

# Steps To Reproduce

1. Make a player with a game watch
2. Try to play any game (Tested on Robot Finds Kitten and Snake )
3. See that the charge is still (50/50)

# Expected behavior

The item should lose charges after being used.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-5320-g20d2ce3 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Safe Autodoc [safeautodoc],
    Bens GF recipes [Tolerate_This],
    Extended Realistic Guns [realguns],
    Garden Pots [growable-pots],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    NPC traits [npc_traits],
    Zetsukaze's Hair Extensions! [zets_hair_extensions],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Disable Religious Texts [no_religious_Texts],
    No Fictional Guns [no_rivtech_guns],
    No Flaming Weapons [no_flaming_weapons],
    No Medieval Items [no_medieval_items],
    No Sci-Fi Equipment [no_scifi],
    No Survivor Armor [no_survivor_armor]
]

#Additional context
The game watch was filthy, so maybe it affects the problem somehow.

**Comment by BevapDin** [comment]
I can't reproduce this. It works fine fine, battery charges are consumed.
