### ISSUE TITLE
Zone construction tasks only doing initial variant.

### ISSUE THREAD

**Issue by ProfoundDarkness** [CleverRaven/Cataclysm-DDA#32194]
**Is your feature request related to a problem? Please describe.**  
When I lay out a construction zone that has more than 1 variant (more than one possibility/stage on the right pane) player (shift-o)/NPCs will ONLY work on the first variant.

**Describe the solution you'd like**  
Would be nice if the other variants were either handled automatically or were specify-able when setting the zone.

**Describe alternatives you've considered**  
\<shrug\> Mostly I just end up doing these with the construct menu but the zone system allows me to hit one key to pick the next task, also NPCs can work on zones or I have to do a LOT of keypresses to start work then tell the NPC to finish.

**Additional context**  
I wasn't sure if this belonged as a bug or a feature.  Since the base variant construction zones seem to be working well, figured feature request template was the better choice.

The easiest example I can think of to test against is removing grass.  There are several variants of the task, depending on the tile.  One can stand next to some grass (with a shovel or something in hand) and hit semi-colon (toggle unavailable constructions) to see which variants are nearby.  If you set a 'Remove Grass' construction zone only variant 1 ('grass' tiles) will be worked on automatically.  Beyond that nothing happens with shift-o and NPCs report having finished instantly after telling them to start (yes I gave the NPC a shovel).  Doing other variants of construction seems to work just fine through construction menu.

I also encountered the 'first variant only' when trying to put in some armored windows on my base.  The NPC happily put in the first stage but there were 3 more stages that didn't get touched.

**Comment by davidpwbrown** [comment]
Working on it currently to enable 3-stage constructions from blueprint zones.
