### ISSUE TITLE
Game crash after selecting eyeglasses for barter

### ISSUE THREAD

**Issue by communistkiro** [CleverRaven/Cataclysm-DDA#32225]
# Describe the bug

Selecting one or two pairs works as expected, a stack of 5 w/ same item damage, as well as a debugged in stack of 8 `pair of eyeglasses` results in crashing. The exact amount could be lower.

# Steps To Reproduce

1. Vanilla erything, rando toon;
2. Find a refugee center (haven't test with other barterable NPCs);
3. Offer at least 5 `pair of eyeglasses`, 

# Expected behavior

1 works,  2 works- you'd expect >=3 to work as well. Didn't test with other items, only the eyeglasses. I've been picking them up for barter because low weight volume and their price.

# Versions and configuration

 - OS: win7
 - Game Version: 0.D-5343-ga7c1bed
 - Graphics version: [Tiles]

# Additional context

Empty world an rando toon with 5 pairs of glasses in front of a merchant along with the crash and debug logs from offering the pairs: https://www114.zippyshare.com/v/xkee5n4i/file.html

#

**Comment by AMurkin** [comment]
Not happening on latest version.
Fixed by #32392.
