### ISSUE TITLE
Crash when i try to drink something frozen

### ISSUE THREAD

**Issue by iamlawn** [CleverRaven/Cataclysm-DDA#32229]
# Describe the bug
When i try to drink a frozen drink and have nothing eatable or drinkable i get a game crash

# Steps To Reproduce

1. Create character
2. Press 'e' to try and drink something frozen
3. press enter
4. crash
5. repeat :)

# Expected behavior
Nothing should happen or get some error message that it's frozen

# Screenshots

![frozen_crash](https://user-images.githubusercontent.com/50532317/60767384-89086980-a0b7-11e9-815a-2dadc75fd6a4.png)

# Versions and configuration

- OS: Windows
- OS Version: 10.0 1809
- Game Version: 0.D-5374-g7a08874 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Magiclysm [magiclysm]
]

# Additional context

[crash_debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/336552/crash_debug.zip)

**Comment by falsewall** [comment]
Confirmed. Tried with no mods, got the same thing.
Its not eating frozen food (you cant select frozen food)
It is the selection of nothing that causes it.

Open the activation menu. Filter it with some random silly word so nothing shows up.
Then press enter.  Then press enter to select the nothing before you.  Crash city. Same error.

**Comment by ipcyborg** [comment]
Can't confirm on 0.D-6061-g36d443a.

>Open the activation menu. Filter it with some random silly word so nothing shows up.
Then press enter. Then press enter to select the nothing before you.

After filtering there is an empty window. Pressing Enter or selection something with arrow keys - still nothing happens.

**Comment by ZhilkinSerg** [comment]
Cannot reproduce on latest version.
