### ISSUE TITLE
Enable to store sling in other belts and introduce a pebbles ammo pouch

### ISSUE THREAD

**Issue by Contemplator11** [CleverRaven/Cataclysm-DDA#32230]
**Is your feature request related to a problem? Please describe.**  
It seems weird that a sling can only be stored in a leather belt. A sling is a very simple thing - two string attached to a small leather patch. It can be tucked in any kind of a belt - for example, in a tool belt, police duty belt, survivor belt. Also ammo pouch for pebbles would also be nice.

**Describe the solution you'd like**  
Enable a sling to be stored in a tool belt, police duty belt, survivor belt and survivor utility belt.
Add "pebble pouch" recipe, the same as leather pouch, but activated to store up to 60 pebbles.

**Describe alternatives you've considered**  
Just ignore this issue.

**Additional context**  
Since the healing speed decrease, ranged combat has become a much more attractive prospect. IMHO, a sling remains useful for any survivor who has not yet found crossbow recipe. Being able to store a sling in more advanced belts will add some consistency.

**Comment by bandti45** [comment]
Have you made sure the sling is the proper volume for soring in the other belts? currently working on the pouch and would like to know to save time

**Comment by bandti45** [comment]
The inability for a sling to be holstered on other belts is on purpose from the code and the belts descriptions but a pouch that can contain pebbles and more will be showing up in a PR soon so I hope you enjoy

**Comment by Contemplator11** [comment]
Thank you! 
This was my first time I used debug console and studied jsons. Maybe I have done something wrong.

I looked up a Sling in ranged.json. It has volume 1 (0.25), weight 96. It has "BELT_CLIP" flag. In-game sling description says it can be stored in leather belt only.
Leather belt in jewelry.json and armor.json has use_action, type: holster, with "flags": [ "BELT_CLIP" ], max volume 2, max weight 400.
Tool belt in armor.json has use_action, type: holster, with "flags": [ "BELT_CLIP" ], max volume 4, max weight 1000. I tried to store a sling into a tool belt, but the game said that "You have no suitable weapons".
Survivor belt has use_action: type": "holster, but it does not have flag [ "BELT_CLIP" ]. I assume that's why it's impossible to tuck a sling into it. I tried to store a sling into a survivor belt, but the game said that "You have no suitable weapons".
Police duty belt in armor.json has use_action, type: holster, with "flags": [ "BELT_CLIP" ], max volume 9, max weight 3600. I tried to store a sling into a police duty belt, but the game said that "You have no suitable weapons".
Firefighter belt in armor.json has use_action, type: holster, with "flags": [ "BELT_CLIP" ], max volume 8, max weight 3600. I tried to store a sling into a police duty belt, but the game said that "You have no suitable weapons".

**Comment by Contemplator11** [comment]
> The inability for a sling to be holstered on other belts is on purpose from the code and the belts descriptions but a pouch that can contain pebbles and more will be showing up in a PR soon so I hope you enjoy

Maybe you know, why it's the case that the sling can't be holstered in other belts on purpose? I'm sincerely puzzled by this.

**Comment by bandti45** [comment]
The tool belt I can understand and might tackle another day, though changing the minimum volume might allow items that shouldn't be tucked in it to be tucked in it. But with the survivor belts in their description, they have a sheath specifically for knives to be stored so I don't want to allow the ability to store more items in them.
I do hope you enjoy the ammo pouch when it's been merged though.

**Comment by Contemplator11** [comment]
> The tool belt I can understand and might tackle another day, though changing the minimum volume might allow items that shouldn't be tucked in it to be tucked in it. But with the survivor belts in their description, they have a sheath specifically for knives to be stored so I don't want to allow the ability to store more items in them.
> I do hope you enjoy the ammo pouch when it's been merged though.

Thank you! I looked at the ammo that this new pouch can store and, if I'm not mistaking, can store crystallized mana and BB! It's great! Thank you kindly!

**Comment by bandti45** [comment]
NP I am unable to make it  allow the number of items based on volume so I went with an even 60 and limited it to ammunition that will be within a normal leather pouche's volume limits at the max number
