### ISSUE TITLE
root strike doesn't hit all targets in range

### ISSUE THREAD

**Issue by b0urgeoisie** [CleverRaven/Cataclysm-DDA#32239]
# Describe the bug

root strike spell will list X targets in the aoe, but will only damage 2-3 at a time.

# Steps To Reproduce

cast root strike on a group of several zombies.

# Expected behavior

all targets in aoe would take damage

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5400-gd56ea51 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable NPC Needs [no_npc_food],
    Classes and Scenarios Mod [more_classes_scenarios],
    Simplified Nutrition [novitamins],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills]
]
# Screenshots
![image](https://user-images.githubusercontent.com/52261571/60771254-24e3a680-a0b3-11e9-9dd3-8b6591553612.png)
![image](https://user-images.githubusercontent.com/52261571/60771256-2e6d0e80-a0b3-11e9-80ee-1b7410147e66.png)
![image](https://user-images.githubusercontent.com/52261571/60771257-33ca5900-a0b3-11e9-8df4-d79193c86a06.png)

# Additional context

[Desert Center.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3365888/Desert.Center.zip)

**Comment by KorGgenT** [comment]
please provide screenshots

**Comment by b0urgeoisie** [comment]
> 
> 
> please provide screenshots

done

**Comment by b0urgeoisie** [comment]
with some debug spawning, this will only happen when there are multiple zombie types in the aoe. spawning all normal zombies will hit all in aoe. adding in swimmer zombies in addition to normal zombies will result in only swimmer zombies being hit.

**Comment by b0urgeoisie** [comment]
more debug spawning shows it's not multiple types, but that some specific types will stop the aoe from hitting everything.

spawning in all (even multiple types) of "don't block" zombies will propagate aoe across all targets.
![image](https://user-images.githubusercontent.com/52261571/60771887-2bc2e700-a0bc-11e9-9b93-0969506ec4b5.png)
![image](https://user-images.githubusercontent.com/52261571/60771890-3b423000-a0bc-11e9-9bfd-5ccee667838d.png)

it seems like >=3 mobs from the "block" group causes the aoe to fail.
![image](https://user-images.githubusercontent.com/52261571/60771943-ebb03400-a0bc-11e9-8b5e-a3076d5495d2.png)
![image](https://user-images.githubusercontent.com/52261571/60771947-f5d23280-a0bc-11e9-863a-098160eb339d.png)

<=2 spawns from "block" group does not cause issues
![image](https://user-images.githubusercontent.com/52261571/60771968-329e2980-a0bd-11e9-8fec-418677d27ce0.png)
![image](https://user-images.githubusercontent.com/52261571/60771970-39c53780-a0bd-11e9-906c-a8175b45b447.png)






# don't block
scarred zombie
gasoline zombie
zombie
brainless zombie
zombie brute
zombie cop
corrosive zombie
crawling zombie
listener zombie
fat zombie

# block
swimmer zombie
acidic zombie
wrestler zombie
nightstalker zombie
tough zombie
zombie dog

**Comment by b0urgeoisie** [comment]
after looking through and comparing various json files in \data\json\monsters, then spawning in a selection from within, it looks like monsters with a dodge stat will break the aoe in numbers greater than 2, and in cases of high dodge scores (i tested broken cyborg @ 6 dodge) it will break it with just 2 of them.

will break the aoe
> {
    "id": "mon_zombie_screecher",
    "type": "MONSTER",
    "name": "screecher zombie",
    "description": "A thin corpse, its chest is swollen in what appears to be preparation.  A thick black ooze drips from its open mouth.",
    "default_faction": "zombie",
    "bodytype": "human",
    "species": [ "ZOMBIE", "HUMAN" ],
    "diff": 2,
    "volume": "62500 ml",
    "weight": 81500,
    "hp": 85,
    "speed": 100,
    "material": [ "flesh" ],
    "symbol": "Z",
    "color": "magenta_cyan",
    "aggression": 100,
    "morale": 100,
    "melee_skill": 5,
    "melee_dice": 3,
    "melee_dice_sides": 4,
    "melee_cut": 5,
    "dodge": 2,
    "vision_day": 50,
    "vision_night": 8,
    "harvest": "zombie",
    "special_attacks": [ [ "SHRIEK_ALERT", 20 ], [ "SHRIEK_STUN", 1 ], [ "scratch", 20 ] ],
    "death_drops": "default_zombie_death_drops",
    "death_function": [ "NORMAL" ],
    "burn_into": "mon_zombie_scorched",
    "flags": [ "SEES", "KEENNOSE", "STUMBLES", "WARM", "BASHES", "GROUP_BASH", "POISON", "NO_BREATHE", "REVIVES", "FILTHY" ]
  },

will not break the aoe
> {
    "id": "mon_zombie_shady",
    "type": "MONSTER",
    "name": "shady zombie",
    "description": "An uncanny shadow envelops this creature, as if light itself were too repulsed to touch it.  All you can make out is its shambling, human shaped outline.",
    "default_faction": "zombie",
    "categories": [ "CLASSIC" ],
    "bodytype": "human",
    "species": [ "ZOMBIE", "HUMAN" ],
    "volume": "62500 ml",
    "weight": 81500,
    "hp": 80,
    "speed": 70,
    "material": [ "flesh" ],
    "symbol": "Z",
    "color": "light_gray",
    "aggression": 100,
    "morale": 100,
    "melee_skill": 4,
    "melee_dice": 2,
    "melee_dice_sides": 3,
    "melee_cut": 0,
    "vision_day": 3,
    "vision_night": 40,
    "harvest": "zombie",
    "special_attacks": [ { "type": "bite", "cooldown": 5 }, [ "GRAB", 7 ], [ "scratch", 20 ] ],
    "death_drops": "default_zombie_death_drops",
    "death_function": [ "NORMAL" ],
    "burn_into": "mon_zombie_scorched",
    "flags": [
      "SEES",
      "HEARS",
      "SMELLS",
      "STUMBLES",
      "WARM",
      "BASHES",
      "GROUP_BASH",
      "POISON",
      "BLEED",
      "NO_BREATHE",
      "REVIVES",
      "PUSH_MON",
      "NIGHT_INVISIBILITY",
      "FILTHY"
    ]
  },

**Comment by b0urgeoisie** [comment]
all of them get hit by effect_str

**Comment by b0urgeoisie** [comment]
after testing them all out the only AOE spell that will work correctly is windstrike (and probably seismic stomp but it gives me CTD).

windstrike and seismic stomp both utilize `downed `as an `effect_str`

if i change rootstrike `effect_str` to `downed` it will begin to work as expected. if i take a spell like fireball without `effect_str` and add `"effect_str": "downed"` it'll work as expected.

**Comment by KorGgenT** [comment]
closed via #34262
