### ISSUE TITLE
Mannwurst cannot be cooked from frozen components

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32236]
# Describe the bug

Unlike bratwurst that is non-human counterpart of the recipe.

[2019.07.06.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3365855/2019.07.06.zip)

0.D-5362-ga8d0753359-dirty

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.D-8431.
![изображение](https://user-images.githubusercontent.com/11132525/66706685-07c01300-ed47-11e9-98f2-511ed33344cb.png)
![изображение](https://user-images.githubusercontent.com/11132525/66706704-3342fd80-ed47-11e9-930d-5cf38e2617de.png)
![изображение](https://user-images.githubusercontent.com/11132525/66706710-481f9100-ed47-11e9-8c88-daed5f07df76.png)

Closing for now, ping me if this is still an issue.
