### ISSUE TITLE
Defrosting steel drum (200L) of water takes as much tinder as a small bottle

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32231]
# Describe the bug

Using a `hobo stove`.

# Expected behavior

Fuel requirements scaling with the mass of the heated object.

# Versions and configuration

0.D-5362-ga8d0753359-dirty

**Comment by TechyBen** [comment]
This might be a big ask... but what are the reasonable assumptions of being able to melt small amounts, both in code and in real life?

Or would it need to be an entire (batch as in game/code) tank at a time?

**Comment by l29ah** [comment]
IRL you could smash the ice with a `1 hammering` and melt as much as you need in a separate container.

**Comment by NetSysFire** [comment]
Not reproducible anymore since we now have other physics, which calculate this appropriately.
