### ISSUE TITLE
Remove Psychopath Trait from Political Prisoner

### ISSUE THREAD

**Issue by MamuelMamington** [CleverRaven/Cataclysm-DDA#32249]
**Is your feature request related to a problem? Please describe.**  
The political prisoner profession is forced into taking the Psychopath trait as with all other prison starting professions, and it just doesn't seem in line with the character described in their blurb.

**Describe the solution you'd like**  
Remove this trait and optionally add something else like "pacifist" to keep the profession interesting.

**Describe alternatives you've considered**  
Chalk it up to simply being a representation of the "steel will" that each prisoner develops and change nothing.

**Additional context**  
A pretty simple change but it does take me out of the game a bit when the supposedly noble whistleblower has the same trait as an embezzler or a crazed rat prince.

Edit: Checking again I see this is only a problem in the standard prison break scenario and not the island prison break scenario, which I'm guessing is an oversight.

**Comment by TychaiosIlithios** [comment]
Side note - political prisoners can be different. Some might be rational and non-violent up to tender levels, but some might as well come from mind frozen political activism groups and movements, fueled via shady schemes by agencies through funds - and such people might be by degrees more cynical than your average ms13 dork. - up to consciously meeting all criteria of being a psychopath.

**Comment by Inglonias** [comment]
The claim I see being made here is "not all political prisoners are psychopaths," which I feel is a fair claim. If you want to add that trait yourself, feel free to take that trait during chargen.

As for fixing this, it is very simple to do. Just JSON required here.

**Comment by SomeDeadGuy** [comment]
I would argue what not all prisoners as of whole are psychopaths.
