### ISSUE TITLE
Allow time_duration to measure time on move scale

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#32250]
**Is your feature request related to a problem? Please describe.**  
Counting time in integer moves requires converting `time_duration` objects and unnecessarily complicates the code.

**Describe the solution you'd like**  
Make `time_duration` store time in moves. `turns_` should become a 64 bit integer `moves_` so we don't end up reducing the maximum value by changing units. `INDEFINITELY_LONG` should be scrapped as `INDEFINITELY_LONG_DURATION` (#32244) would be safe for working with moves. At this point all code working with time on any scale could be refactored to use `time_duration`.

**Comment by kevingranade** [comment]
I really don't like this adjustment because there is no stable mapping between seconds and moves (it's mediated by character speed), and the jump to a 64 bit value is somewhat egregious.

**Comment by ymber** [comment]
That's a problem. Currently the conversion functions in `time_duration` assume 100 moves to a turn.  Are we calculating time wrong anywhere `to_moves` or `from_moves` are used without accounting for character speed?

**Comment by kevingranade** [comment]
That's the thing, we need to make that determination on a case by case basis, if we start using time durations instead of moves everywhere it would cover up places where it's not correct.
