### ISSUE TITLE
Millionaire trait is too costly

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32258]
# Describe the bug

It costs 3 points while it's less useful than a Bookworm, Scout or Thick-Skinned that cost one, since pretty much everything you can buy these days you can get by whacking hard enough.

**Comment by KorGgenT** [comment]
i think the debt trait should be 0 points at least. possibly even the millionaire trait as well, since the impact of it is much reduced since factions use their own currency now.

**Comment by kevingranade** [comment]
I'd go one step further and say the traits should be reverted, they don't
meaningfully impact the game any more since pre-cataclysm money is mostly
unusable now.

**Comment by nexusmrsep** [comment]
The idea was for the fluff mostly, so why not make it stay at 0 cost?

**Comment by kevingranade** [comment]
The top level trait could stay as flavor, but the underlying bank account
manipulation should go.

**Comment by sdp0et** [comment]
Or add some other effect.  I took debt once hoping some NPC mobsters would show up to take my stuff because I still owed their boss and money was no longer valuable.  Instead it just took a few extra cash cards to be able to start consolidating them.

**Comment by TychaiosIlithios** [comment]
Mobster npcs during apocalypse - that's some real serious approach to gangsta business, BUT - in situation of total digital population control, it would be far more realistic to have character in debt databases and after a certain time send robots after him.

As far as I understood bot methods - they are employed to automatically cuff suspects or stun them and alert the proper human police - be that during mass riot or singular targets. So having bots coming to you from time to time, electroshocking or applying restraints to you and sounding an alarm would imo be just dandy during apoc.
