### ISSUE TITLE
Skeleton Juggernaut gets insta-killed by a mushroom.

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#32254]
I saw Skeleton Juggernaut gets insta-killed by a mushroom (I am using latest git pull at the time of this post). This is a rare boss-type mob and it is kinda silly seeing him die in a single turn against a mushroom. Maybe super strong zombie should put up a little bit more fight than that? For example: instead of getting insta-killed he should receive a debuff that can turn him into a mushroom after X number of turns. And the probability of him turning into a mushroom could depend on the number of times he was pollinated with spores during debuff duration.

**Comment by nexusmrsep** [comment]
Insta-killed or insta-converted?

**Comment by EvgenijM86** [comment]
Insta-converted to a regular mushroom zombie.

**Comment by jeremyshannon** [comment]
This is why you need 100% coverage on your armor, Mr. Naut. Armor plating won't stop Mr. Spore unless it's complete.

**Comment by Necrosian** [comment]
Top level zombies should have some sort of defense against Mycus.

**Comment by nexusmrsep** [comment]
Beside the disputable ability of non-default zombies to fungalization, one more thing seems obvious to me: non-default zombies, like juggernauts should not devolve into default-fungal-zombies but to some kind of special fungal hybrids with unique characteristics, like fungal juggernauts, fungal hulk's, dark shrooms etc. That would open up a whole new branch of creatures to interact with.

**Comment by Fracture64** [comment]
Convert zeds approximately based on size? That way there could be just few types: fungal child (all kids), fungal zombie (all human sized zombies), fungal brute (brute line), fungal hulk (hulk / juggernaut).

**Comment by TechyBen** [comment]
> Beside the disputable ability of non-default zombies to resist fungalization, one more thing seems obvious to me: non-default zombies, like juggernauts should not devolve into default-fungal-zombies but to some kind of special fungal hybrids with unique characteristics, like fungal juggernauts, fungal hulk's, dark shrooms etc. That would open up a whole new branch of creatures to interact with.

As long as for flavour the shrooms stay slow. They should be dynamically different, else we are just doing palette (colour) swaps.

Perhaps buff the health, but make them slower. Make them divide into smaller mobs when destroyed. Thus they are not exact copies of juggernauts. Are not easily destroyed with heavy fire (they split up into smaller mobs like blobs do) and while slow, still spread the fungus and are a risk if up close.

**Comment by Mecares** [comment]
One could wonder how the blob is supposed to fight back if his agents get Insta converted.

**Comment by nexusmrsep** [comment]
That might in fact lead to development of some specialized counter-fungql
zombie types. I'd love to see some.

wt., 9 lip 2019, 14:34 użytkownik Mecares <notifications@github.com>
napisał:

**Comment by TechyBen** [comment]
Relevant thread in the forums, with some artwork. Mainly might be an alternative eminy, but IMO could be incorporated into a flavour of fungus: https://discourse.cataclysmdda.org/t/the-flesh-forest/18801/51

**Comment by TychaiosIlithios** [comment]
The only thing possibly suggested is phases of fungal transformation - passive cocoon, weak initiate and full on fungal mob. - For mobs with not specified timers have default powers and abilities in proportion to original, but have option to manually write transformation time and mob parameters for each phase.

This could actually be worth it in modding if such a feature would be implemented to json not only related to fungus, but for any possible modded transformation desires. Lycantropy, facehugging alien pregnancy, gremlins in the rain or funny player made chemicals - if that were possibly moddable through open transformation tags and transformation triggers -maybe someone would be inspired to creatively mod the ... out of that. ...'cuz you don't always need to make mod that covers all mobs to make a difference, sometimes a mod that gets a single mob to infect and transform a single mobtype might be a game changer like currently the zombie master is.
