### ISSUE TITLE
Tied friendly monster cannot fight for its life

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32253]
# Steps To Reproduce

1. Tie your favourite horse near the entrance of a grocery store and go shopping.
2. Return and find it dead with a few zombies near the corpse at full health.

# Expected behavior

Horse beating shit out of zombies or freeing itself and running away (tying consumes zero time so i'd expect it to be really weak and not constraining the beast's limbs in the first place).

# Versions and configuration

0.D-5416-g50a3b99e00-dirty

**Comment by ZhilkinSerg** [comment]
Exactly one horse was harmed during confirmation of this bug.

**Comment by Maleclypse** [comment]
Tied dogs will still fight zombies.  However, animals that attempt to flee first will not fight back when tied up
