### ISSUE TITLE
Roof tiles not falling down

### ISSUE THREAD

**Issue by roaringjohn** [CleverRaven/Cataclysm-DDA#32260]
# Describe the bug

When burning down a building, some tiles above it are kept there. **_This is unrealistic._**

# Steps To Reproduce

1. Burn down a building

# Expected behavior

Whenever a building is burned down, all the tiles above it should fall down as well.

# Screenshots

![](https://cdn.discordapp.com/attachments/252368987210514433/597969112295276565/unknown.png)

# Additional context

**_We need realism to be applied to all roofs so they don't defy gravity!_**

**Comment by Zireael07** [comment]
Do you have z-levels on?

**Comment by roaringjohn** [comment]
It does indeed occur with z-levels on.

**Comment by Zireael07** [comment]
I believe roofs falling down is limited to z-levels only. Probably for performance reasons.

**Comment by roaringjohn** [comment]
That game has z-levels enabled, though?

**Comment by Zireael07** [comment]
Your first post says it doesn't happen, your second post says "it does indeed occur with z-levels on", so I assumed you didn't have z-levels on for the first post.

**Comment by roaringjohn** [comment]
I don't know if that first world had z-levels on (it's not mine, after all). I could check without z-levels.

**Comment by roaringjohn** [comment]
That first world had z-levels on, now that I've asked the guy.

**Comment by roaringjohn** [comment]
They also don't fall without z-levels, which makes sense.
