### ISSUE TITLE
Weapon mods should go on more weapon types

### ISSUE THREAD

**Issue by mvm900** [CleverRaven/Cataclysm-DDA#32266]
**Is your feature request related to a problem? Please describe.**  
Certain weapon modifications seem to be arbitrarily locked from going on other weapon types. A prominent example here is shotguns being unable to mount certain scopes and underbarrel attachments, even if the weapon would in reality have the ability to mount it. Such as the ACOG scope which just... can't go on shotguns, despite most having the same pitcanny rails topside. 

**Describe the solution you'd like**  
A relook at what mods can go to what guns, assuming mounts are similar where applicable. Which, they'd have to be to fit on so many guns in the first place. Pitcanny rail is and has been the dominant mounting system for a long while now for attaching weapon accessories. Weapons already have the slots, and there only looks to be a few outliers where this might not make sense, like the underbarrel slot, which don't have to be touched with the current system if that's what it takes for this to be acceptable. 

**Describe alternatives you've considered**  
Changing the mod system to include what type of mount in addition to location. For example, dovetail sight slot or pitcanny underbarrel slot. Which would allow greater flexibility in what modification goes where and to what weapons. And, while being more realistic, would also allow greater differentiation in certain weapons, for both balance and flavor.

**Comment by kevingranade** [comment]
An issue asking for a content audit isn't valid, if you're interested, just do it, ideally with sources.
