### ISSUE TITLE
Random Tree-Chopping Related Radiation Poisoning

### ISSUE THREAD

**Issue by greaterguardian** [CleverRaven/Cataclysm-DDA#32277]
# Describe the bug

Without any evident sources, radiation has been reaching lethal levels around this one  specific cabin, particularly when chopping some of the oak trees north of the building, but also at random when moving in the vacinity of the cabin.

# Steps To Reproduce

Chop down trees north of the cabin, suffer massive radiation poisoning. Alternatively, move around the cabin without any specific direction, notice "irradiation" rise at random intervals.

# Expected behavior

"Irradiation" status should reach damaging levels.

# Screenshots

Before logging:
![Before](https://user-images.githubusercontent.com/52706532/60905757-14b2ff00-a24c-11e9-8ce3-d37558420c6a.jpg)

After logging:
![After](https://user-images.githubusercontent.com/52706532/60905763-1aa8e000-a24c-11e9-94ae-53722a6f6511.jpg)

Map of the surroundings:
![Map](https://user-images.githubusercontent.com/52706532/60905772-1da3d080-a24c-11e9-9fe6-75f59c74000c.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version - Win 7 Pro, don't know why it didn't recognize the OS.
- Game Version: 0.D-5457-g40e3a64 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Sleep Deprivation [sleepdeprivation],
    StatsThroughSkills [StatsThroughSkills],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    SpeedyDex [speedydex]
]

# Additional context
Stuff possibly related to the issue that i own: Undamaged atomic reading light, undamaged microreactor, non-radioactive spiral stone.

# Savegame right before screenshots:
[Hernandez.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3373948/Hernandez.zip)

**Comment by TechyBen** [comment]
Some areas are randomly radiated. Are you able to spawn in a geiger counter/use debug to test?

**Comment by Edgar-cy-Lee** [comment]
So I spawned geiger counter and played around with it.

Your house, your front porch area especially are incredibly irradiated. 

I suggest you to find some lead vests.
