### ISSUE TITLE
Smoking Causes Nicotine Overdose

### ISSUE THREAD

**Issue by ANickelN** [CleverRaven/Cataclysm-DDA#32279]
# Describe the bug
Smoking a single cigarette causes the "Nicotine (2)" debuff

# Steps To Reproduce
Smoke a cigarette and check the player sheet to see "Nicotine (2)"

# Expected behavior
Smoking a single cigarette shouldn't make you sick.

Windows 10, Build 9300, Tiles Version

**Comment by zsebastian** [comment]
I don't know, if you have no tolerance smoking a single cigarette might make you dizzy at the least.

**Comment by EirenexTheDragon** [comment]
It is because it is not adjusted to the new second effect. a cigarette also lasts for far longer than it should, and the player just massinhales alot in a few seconds

**Comment by Bulletfang** [comment]
I can confirm this bug too, my character vomits all over the place and gets nauseous for a very long time after using a single charge from an electronic cigarette.
