### ISSUE TITLE
Medisoft item use

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#32272]
**Is your feature request related to a problem? Please describe.**  
As far as I'm aware, the medisoft item has no use.

**Describe the solution you'd like**  
Allow use of medisoft in a craft recipe to add a flat 10% bonus to CBM installation. Gating it behind the control laptop makes sure it's end game content. Think of it as an autodoc upgrade, or coding it better to suit your biology.

**Describe alternatives you've considered**  
I think 10% is a reasonable amount (opinions may vary), I considered it frying on use, but there aren't "end game" electrical components besides plutonium fuel, and it's not THAT rare. Also it doesn't make sense to use fuel for this as I think of it more as a module. Adding a blood requirement for use, coding it to your DNA?

**Additional context**
I can do the recipe myself; I envision something like
Medisoft Module:
Tools required
>Screwdriver set
>Control Laptop
>Medisoft USB

Components Required
>Processor board
>2 Ram
>1 signal receiver
>8 copper wire
>4 solder

The problem will be getting it to interface with the autodocs, whether they have a module slot, or you just need it in your inventory, I would need help with that aspect.

**Comment by kevingranade** [comment]
We've discussed this extensively elsewhere, CBM or CBM category specific software or hardware to improve installation chance would be fine, but a blanket, "make installation better" is problematic.
