### ISSUE TITLE
Incendiary grenade activates in fire but doesn't explode

### ISSUE THREAD

**Issue by NeviNovat** [CleverRaven/Cataclysm-DDA#32276]
# Describe the bug

As stated, if you trow a incendiary grenade in a fire it activates, and you can pick it up and reuse it like it was a normal one. 

# Steps To Reproduce

1. Spawn a molotov and a incendiary grenade.
2. Activate molotov and trow it to make fire.
3. Trow the grenade in fire, wait.
4. Pick the (active) incendiary grenade up and walk away.

# Expected behavior

It should activate and explode or not activate at all. I don't know what behavior was intended because there is a lack of information about the "ACT_IN_FIRE" flag that produces this behavior.
It looks like it was meant to make the grenade explode ( or "use_action": "GRENADE_INC_ACT", but all it dose is mark it as active ).

# Screenshots

Picking up the active grenade:

![incendiary_grenade-bug](https://user-images.githubusercontent.com/51816321/60902830-f4e60000-a278-11e9-881a-ab169abdfcbe.png)

Walking away with active grenade:

![incendiary](https://user-images.githubusercontent.com/51816321/60902853-fe6f6800-a278-11e9-915b-f5b3db93b7a5.png)

Suspected problem code:

![code3](https://user-images.githubusercontent.com/51816321/60902925-1cd56380-a279-11e9-8aa7-0e37e5ddd994.png)

# Versions and configuration

- OS: Windows
    - OS Version: Windows 10
- Game Version: 0.D-5457-g40e3a64 [64-bit] (Build 9298)
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

When I was testing code for fixing #32275 and #32274 I saw the suspected flag and tried to use it thinking it will make the grenade activate and explode when in fire or at least make the non-active grenade active and providing a more realistic time before detonation of grenades ( since it'll take time before it explodes in real life ). But what i got was an item with a tag "(active)" but won't explode or act, it behaves like a normal item but with a changed name.
I strongly suspect that this flag is part of the problem.

I think that just removing it is not enough, the flag should be fixed and proper information added.

**Comment by nexusmrsep** [comment]
Not only I've confirmed it, but I can add to that that other explosive items that you activate are sometimes not processed if dropped on map tiles. This behavior is inconsistent, some unrevealed factor sometimes make it work, sometimes not. But if one item "ticks" other will and if one doesn't others won't too. Items will "tick" the moment you pick them up. Teleport out and back will tick again.

Probably something in active item cache.
