### ISSUE TITLE
Military Operations Map marks incorrect locations

### ISSUE THREAD

**Issue by ANickelN** [CleverRaven/Cataclysm-DDA#32280]
Describe the bug
After reading any "Military Operations" category map, you will notice that regular silos and animal shelters are marked.  I assume that this is related somehow to the fact that it checks for "nuclear silos" and "evacuation shelters", and the other locations are getting caught in that check.

1. Start a new character with an unexplored map.
2. Spawn in a military operations map.
3. Read it and check the map screen.

Expected behavior
The military should have no interest in animal shelters and regular silos, therefore they shouldn't be marked.

Screenshots
https://i.imgur.com/YhVZKUJ.png
https://i.imgur.com/8MZctLR.png

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5441-g5f096ff [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Rail Stations [No_Rail_Stations],
    [DP_MOD] Hide DEBUG [DP_No_Debug_Tile],
    No Fungal Monsters [No_Fungi]

**Comment by ZhilkinSerg** [comment]
This happens because maps use partial match (`ot_match_type::contains`) when revealing targets:

https://github.com/CleverRaven/Cataclysm-DDA/blob/502b391f2140031187839602def378668b35f585/src/iuse_actor.cpp#L1086-L1094
