### ISSUE TITLE
Cannot craft CBM's that require precision solderers in crafting recipe

### ISSUE THREAD

**Issue by gavin1337** [CleverRaven/Cataclysm-DDA#32291]
# Describe the bug

Cannot proceed past 4% crafting on multiple different CBM crafting recipes, error message reads "you no longer have none and can't continue crafting"

# Steps To Reproduce
Try to craft a CBM or try to continue to craft the already made CBM's in the savefile.

# Expected behavior

CBM crafting should proceed past 4% crafted and be completed eventually without being interrupted by the lack of "none" in player inventory or surrounding

# Screenshots

![Untitled](https://user-images.githubusercontent.com/15938735/60942787-8cfbdd80-a2a9-11e9-833f-bec13aa71500.png)

# Versions and configuration

- OS: Windows
    windows 10 ver. 10.1809 64-bit home basic
- Game Version: 0.D-5487-g17141af [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

Savefile:
[Pukwana.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3375855/Pukwana.zip)

**Comment by RDru** [comment]
Do you sue UPS modded tools? There is a bug like that with UPS items outside of inventory:  #32039

**Comment by gavin1337** [comment]
no, all the required items to work on crafting said CBM are in my inventory.

![image](https://user-images.githubusercontent.com/15938735/61014559-afdfcd80-a34d-11e9-9af3-b1cdc86a583f.png)

here's the crafting recipe

![image](https://user-images.githubusercontent.com/15938735/61014588-d56cd700-a34d-11e9-986a-19842773c8c6.png)

the only item that requires charge to craft is the soldering iron, which has plenty of charge in my inventory according to the first screengrab, it is not UPS modified and it has enough charge in the item itself, it was also reloaded with a different battery and does not work with either battery. It does not consume either internal power or soldering iron power when crafting fails and it is stuck at 4%

**Comment by gavin1337** [comment]
addendum: checked aftershock crafting recipe and can confirm that there is no json issue with the programming in the crafting recipe itself

![image](https://user-images.githubusercontent.com/15938735/61015931-698d6d00-a353-11e9-88b6-2e0597a53e51.png)

**Comment by gavin1337** [comment]
when crafting precision solderer CBM, crafting was successful.
![image](https://user-images.githubusercontent.com/15938735/61020044-fa6b4500-a361-11e9-85dc-d702d3c9748a.png)

 The difference between precision solder CBM and unsuccessful CBM's appears to be the precision solderer CBM requirement for crafting recipies like the power storage mk 2 CBM, screenshot above, error is also reproducible with other CBM's that require precision solderer CBM such as Cranial Flashlight

![image](https://user-images.githubusercontent.com/15938735/61020165-5b931880-a362-11e9-8912-44325e9513b9.png)

This may have a similar issue to #32039 where crafting object is not "on person" if game considers player-installed CBM to be "off person" as well.

**Comment by Edgar-cy-Lee** [comment]
This is interesting, how come your crafting recipes do not display charge requirement?
![image](https://user-images.githubusercontent.com/8914956/61020662-7a96a800-a36c-11e9-9cf7-fe91cb887d07.png)

And if this is the cause, would crafting end successfully if you had enough power?

**Comment by gavin1337** [comment]
the crafting recipes do not list precision solderer CBM's as having a charge requirement because the precision solderer CBM does not use active charge, as it is considered a passive CBM.

![image](https://user-images.githubusercontent.com/15938735/61020834-af066600-a364-11e9-8674-fba54d9c28d0.png)

when a power storage CBM was debug spawned in and installed, and enough power was consumed to be able to complete it if there was some sort of power charge requirement for precision solderers, it still gave the crafting error and refused to continue crafting beyond 4%

![image](https://user-images.githubusercontent.com/15938735/61021170-f2150900-a365-11e9-8ae3-7e2b2e59c4e5.png)

**Comment by Edgar-cy-Lee** [comment]
Hmm.... does changing recipe to something like this work?
'"tools": [ [ [ "afs_solderers_item", -1 ], [ "toolset", -1 ] ] ],'
to
'"tools": [ [ [ "afs_solderers_item", 1 ], [ "toolset", 1 ] ] ],'

**Comment by gavin1337** [comment]
Testing it now

here is the modified and saved code highlighted below
![image](https://user-images.githubusercontent.com/15938735/61070323-02fc6380-a3d4-11e9-989e-bed11b065303.png)

when the change occured, the crafting screen pops up and allows me to select either integrated toolset (which is odd because I do not have that bionic installed) and it increments crafting by one turn but it doesn't close the window asking which tool to use, effectively haulting crafting. it also for some odd reason detects two copies of integrated toolset and precision solderers, one on my person and one nearby which is odd. I genuinely don't know what would be causing this glitch.

![image](https://user-images.githubusercontent.com/15938735/61070674-e1e84280-a3d4-11e9-8b2c-96900331ae47.png)

here's a screenshot showing that I do not have an integrated toolset CBM installed on my person

![image](https://user-images.githubusercontent.com/15938735/61070718-f75d6c80-a3d4-11e9-8abf-053802009364.png)

I can confirm that it is not due to NPC's nearby who may or may not have an integrated toolset as I moved all NPC's away far enough to ensure that they are not in the detectable crafting radius.

![image](https://user-images.githubusercontent.com/15938735/61070816-2673de00-a3d5-11e9-9eef-fd8e743e5776.png)

**Comment by Edgar-cy-Lee** [comment]
Looks like actual issue, and more than just CBM:
https://discourse.cataclysmdda.org/t/buggy-crafting-menu-while-trying-to-craft-clean-water/20736

**Comment by gavin1337** [comment]
well, as I don't have any other types of solutions and it appears that this is a manifestation of different bugs that are already known of, I'm going to call this closed for now.

**Comment by zachary-kaelan** [comment]
Still an issue 2 months later. Having the exact same problem.

**Comment by Night-Pryanik** [comment]
CBM crafting is no longer possible in vanilla. I think this bug with CBMs isn't reproducible on latest experimental. 
What were you crafting when the bug happened?

**Comment by AntMatriarch** [comment]
Problem still persists, bumping it.

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12062-ge7271b0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Fuji's Military Profession Pack [fuji_mpp],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player icon, retrodays [sees_player_retro],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by gavin1337** [comment]
spawning a "none" item using debug allows you to complete the recipe without using the "none" item, seems like it's some oddity with the crafting recipe.

**Comment by ERRORCODE509** [comment]
Still an issue, as of writing this. Only solution seems to be spawning in the "none" item from the debug menu.
