### ISSUE TITLE
Gravel tiles are handled incorrectly

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#32308]
# Describe the bug

Gravel tiles are handled incorrectly for dragging and resource purposes.

# Steps To Reproduce

1. Make a player with a shovel and a nearby table.
2. Try to drag the table or recover rock from the gravel tile.
3. There's no way to get rock from the tile and the table collides with it.

# Expected behavior

A table, or anything else for that matter, should by just as easy to drag across gravel are across grass. Likewise, gravel should serve as a special rock resource tile, much like sand tiles and clay tiles already do for their respective material.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: Win7x64
 - Game Version: 0.D-5509-g59be6a4
 - Graphics version: Tiles
 - Mods loaded: none

# Additional context

Looks like gravel is presently treated as a construction, which doesn't really make much sense since it's really terrain. The fact that it's construction is what causes the dragged item crashing. Deconstruction actually does yield some rocks, though apparently only sharp rocks.

**Comment by I-am-Erk** [comment]
Gravel should be easy to drag things across. However I don't think it should be an infinite source of rocks. Rocks in the game are large stones that can be used as fairly damaging weapons or stacked to build walls and fireplaces. Gravel implies significantly smaller stones, or it wouldn't be easy to walk across.

**Comment by misterprimus** [comment]
Well, I don't know how to fix the dragging issue. It would have to be a total redo to get rid of gravel generating in the world and add gravel generating as terrain. Deconstructing gravel reveals rock floor, and I think adding this to construction.json allows you to extract rock:

```
    {
    "type": "construction",
    "description": "Extract Rocks",
    "category": "OTHER",
    "required_skills": [ [ "survival", 0 ] ],
    "time": "30 m",
    "qualities": [ [ { "id": "DIG", "level": 1 } ] ],
    "byproducts": [ { "item": "rock", "count": [ 5, 9 ] } ],
    "pre_terrain": "t_rock_floor",
    "post_special": "done_extract_maybe_revert_to_dirt"
  },
```

**Comment by l29ah** [comment]
YEAH THIS SUCKS

**Comment by wapcaplet** [comment]
Confirmed in 0.E-6285-g 419ee84b88 - a table cannot be dragged across gravel, saying "The table collides with something".

**Comment by sTiKyt** [comment]
Still can't move my tables across gravel, just reminder
