### ISSUE TITLE
Map Notes Off by Default

### ISSUE THREAD

**Issue by Vzor-** [CleverRaven/Cataclysm-DDA#32313]
# Describe the bug
Currently the "Toggle Map Notes" option is off by default. This is a strange and presumably unintended change. It is very confusing for new players, and players unaware of the toggle option. If it was intended, then we can at least document and discuss the reasoning behind it here. 

Evidence that this confuses people: 
https://github.com/CleverRaven/Cataclysm-DDA/issues/31415

# Steps To Reproduce
Make a game, check map. Toggle Map Notes will be off

# Versions and configuration

0.D-Windows-Tiles-9308

**Comment by ZhilkinSerg** [comment]
> and players unaware of the toggle option

Eh? "Toggle Map Notes" is literally on the screen.

**Comment by Vzor-** [comment]
Lots of things are on that screen, it's map! I would suggest changing it to "Toggle Notes" (I read right past it at first) and it should really be on by default. I think most players come to use notes.

**Comment by ZhilkinSerg** [comment]
People not reading what's displayed on the screen is really not a very good argument that something is broken.

**Comment by Vzor-** [comment]
Interface design is about making things easy, it is not 'broken' by any means. But on top of that, notes being off by default is not intuitive. If I have to manually place a note, why would it default to not showing that note to me?

**Comment by NickGrease** [comment]
It's been default on since time immemorial. If anyone needs to defend this change, it's not the people that expect it to be on, but whoever turned it off.

If someone adds a note, would it not be reasonable to automatically turn on the display of notes? Would that be any different than having default on in the first place?

**Comment by ZhilkinSerg** [comment]
> Interface design is about making things easy, it is not 'broken' by any means. But on top of that, notes being off by default is not intuitive. If I have to manually place a note, why would it default to not showing that note to me? Default should be the state most commonly needed, how many people need to hide notes?

I am not arguing about default state of this toggle. I've just got confused by "players unaware of toggle option", while the "Toggle Map Note" is on the screen.

***

> It's been default on since time immemorial.

That is not a good argument - for years there was not a separate command to toggle map notes until it was added recently.

> If anyone needs to defend this change, it's not the people that expect it to be on, but whoever turned it off.

I am not sure which change we are talking about and who's arguing about it - nobody created a one-line pull request to fix anything yet.

> If someone adds a note, would it not be reasonable to automatically turn on the display of notes? Would that be any different than having default on in the first place?

I don't know - we don't have that, so you should probably go with A/B testing and tell us which is liked better.
