### ISSUE TITLE
Quivers not consuming arrows, sometimes

### ISSUE THREAD

**Issue by MiguelANunes** [CleverRaven/Cataclysm-DDA#32320]
# Describe the bug

In my current game I have a large quiver that is loaded with simple metal arrows that aren't consumed when fired, how ever they were when I was playing yesterday, under the exact same conditions.
I didn't mess around with the game's files, nor did I do anything with the arrows or bow in game, aside from crafting more arrows when needed.
This happened with both the large and normal quiver, and with the longbow, self bow, and small bow.

# Steps To Reproduce

I don't know how to reliably reproduce this bug.

# Expected behavior

Arrows to be consumed from the quiver whenever fired

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5457-g40e3a64 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Bens GF recipes [Tolerate_This],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Sleep Deprivation [sleepdeprivation],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    sees-player icon, -attitude [sees_player_less_attitude]
]

# Additional context

The following errors happened in when I tried to fired the bow:

15:19:50.090 ERROR : src/visitable.cpp:504 [item visitable<T>::remove_item(item&) [with T = map_cursor]] Tried removing item from object which did not contain it

15:19:50.135 ERROR : src/ranged.cpp:330 [int player::fire_gun(const tripoint&, int, item&)] Attempted to fire zero or negative shots using <color_c_light_green>|| </color>longbow+1

Those happened one after the other, and when they did, the bow didn't fire, however, time passed as if it did.
When they did happen the quiver was full, and after continuing to play the bow fired normally.
Here's the save file where this is happening, as well as the debug.log file.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3383508/save.zip)

**Comment by alkemann** [comment]
Can it be related to having used `F` to select arrow in advance? Maybe a different arrow type then you have?

**Comment by MiguelANunes** [comment]
> Can it be related to having used `F` to select arrow in advance? Maybe a different arrow type then you have?

If I recall from when I was playing this save, I was selecting arrows on the 'f' menu, and it did happen with different arrow types, although which arrows are those I don't remember.
