### ISSUE TITLE
No ammo in downed choppers - EVER

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#32327]
There's never ammo in crashed choppers.

# Steps To Reproduce

1. Locate a downed chopper or start with the helicopter crash scenario.
2. Search the chopper.
3. Never find any ammo.

# Expected behavior

Choppers should be like destroyed Humvees/armored cars: potentially with unspent ammo in the miniguns.

# Versions and configuration

 - OS: Win7x64
 - Game Version: 0.D-5531-gdcd9f1d
 - Graphics version: [Tiles]
 - Mods loaded: none

# Additional context

I'm not too familiar with the code, but I think the issue is with these:
`"part": "mounted_m134" },`
in `helicopters.json`.
Perhaps all instances of that should be replaced with:
`"part": "mounted_m134", "ammo": 80, "ammo_types": [ "308" ], "ammo_qty": [ 0, 500 ] },`
Am I understanding that right? 80 is the chance, ammo types is the ammo type, and ammo qty is the range of ammo that could potentially be found in it?

**Comment by misterprimus** [comment]
https://github.com/misterprimus/Cataclysm-DDA/commit/db1df84183eff5933ac896d24882db2b2ce995e8

**Comment by ZhilkinSerg** [comment]
Closed in #32328
