### ISSUE TITLE
Lettuce is too big

### ISSUE THREAD

**Issue by YakumoChen** [CleverRaven/Cataclysm-DDA#32330]
# Describe the bug
Lettuce is too big. It comes in stacks of 10, and each leaf is a full .25L.
![image](https://user-images.githubusercontent.com/10399117/61118574-89727d00-a488-11e9-8a13-cd6ab8317e49.png)
(pictured: 4 farmed tiles of lettuce)
Each leaf also has almost no nutritional value in contrast and you only need one for any given meal, making it pointless to farm more than one at a time.

# Steps To Reproduce
Step 1: Lettuce
![image](https://user-images.githubusercontent.com/10399117/61118538-752e8000-a488-11e9-9b38-f8afcfe5bc5a.png)

# Expected behavior
I get a lettuce is bigger than, say, an onion, but a few lettuces shouldn't take up half my minifridge.
Speaking of onions, a single onion is also .25L, the same size as a 10th of a lettuce.

# Versions and configuration

 - Game Version: 0D-5452-gf8ee22c
 - Mods loaded: I don't think any mods have to do with lettuce

# Additional context

Onions in game are the same size as a single lettuce leaf. That means a single head of lettuce is as big as 10 onions.

**Comment by roaringjohn** [comment]
I think the problem here is that fridges are too small, not that lettuces are too big.
The lettuces are actually _**realistically**_ sized, by my calculations of a head of lettuce being around 4-6 inches in every dimension, which will equal around 2-3.5 liters, and 1/10th of that is around 250 mL, the exact size they are now.

**Comment by adamkad1** [comment]
what about the onions?

**Comment by Night-Pryanik** [comment]
> fridges are too small

[Here](https://discourse.cataclysmdda.org/t/realistic-fridge-sizes-mod/20585/4?u=valiant) I provided some proofs they ain't.

**Comment by bandti45** [comment]
I've looked into unions, a medium union are actually around 8 oz which is roughly 250 mL making both lettuce leaves (assume there a whole leaf) and unions (assuming it's about average-sized) correctly sized
