### ISSUE TITLE
Available backpacks are too small

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32332]
IRL backpacks come with volumes of 5-120L or more, while the backpacks used by tourists in autonomous settings are 70L+, but the biggest backpack available in cdda is 30L, making real backpacker experience unworkable in cdda without incurring crippling penalties of wearing multiple shitty backpacks at once.

![modern 80L backpack](https://www.deuter.com/assets/products/backsystem_hotspots/10411_Traveller70plus10-7400-15-back.jpg)

**Comment by ZhilkinSerg** [comment]
Existing backpack description says: "A small backpack.  Good storage for a little encumbrance."

**Comment by floodie24** [comment]
adding several types of bigger variants of backpacks would be the best solution

**Comment by TychaiosIlithios** [comment]
Just a friendly reminder about double backpacks i.e. both back and belly pack. This might be a good volume/encumbrance combination along with a sheath/holster.

**Comment by Rivet-the-Zombie** [comment]
IRL, a standard kid's school backpack holds about 25 liters and a standard MOLLE rucksack holds 82. All of our backpacks are currently waaaaaay undersized.

**Comment by SolarMoney2112** [comment]
But a full 120L pack would come with a fuck ton of weight

**Comment by tinukedaya** [comment]
> But a full 120L pack would come with a fuck ton of weight

Well I think that is ok. IRL the real problem IS weight and not volume.

**Comment by floodie24** [comment]
the reason you need big backpacks IRL is because what you carry around is usually light but takes a lot of volume, like a sleeping bag, roll mat, light weight tent and clothing alone takes up a whole lot of the volume but is not that heavy. Ofc if you want to fill your huge trecking backpack with scrap metal, that is where the overburden mechanic kicks in ;)

**Comment by l29ah** [comment]
By the way, the current backpacks incur severe penalties on dodging even being empty, scaling with volume, while in fact even an empty touring 110L backpack weighs ~2kg, is soft and hides behind your back, so it doesn't prevent you from bending and jumping around an enemy in a melee. I'm not sure what would be the right way to add the bigger backpacks: 100 encumbrance on torso would cripple even an advanced melee fighter. 

OTOH, now that the stamina got nerfed into oblivion, can we just tell that backpack loads are simulated adequately by the carried weight that impacts stamina regen and lower the encumbrance values?

**Comment by floodie24** [comment]
Encumbrance reflects how much a piece of equipment bothers you while moving around, not the size or weight.

To give an example from when i was in the army, as a recruit they loved to bother us with OLD gear from WW1. it was unhandy, could not carry that much gear, would cause you pain and had terrible center of gravity. Later when not recruits we ofc got the modern gear, that could most likely carry 5 times more stuff, would not cause pain and you could carry a lot more gear without noticing.
![image](https://user-images.githubusercontent.com/52832089/61172003-5959d580-a57f-11e9-9fa8-842a3db8d453.png)
![image](https://user-images.githubusercontent.com/52832089/61172024-8d34fb00-a57f-11e9-9847-fff2dc84e229.png)

to not over complicate things i think this should be done in 3 parts.
first overhaul the different types of backpacks and such, let their encumbrance reflect how well designed they are, and at the same time add the bigger size backpacks as well
second part should be looking at how the  volume of gear carried affects the encumbrance of your backpack
and last there should be a look at what gear can be crafted, how difficult it is to craft.
remember a modern trecking backpack is made of strong lightweight material that is not just a bunch of scrap welded together with a bag made of random rags

**Comment by FuelType-Memes** [comment]
Encumbrance right now is just random. A fitted blazer is 10 enc, but plate armour is 10 enc too

**Comment by CafeineCawfee** [comment]
Creating some backpacks and adjusting the values for them.
![Screenshot (2354)](https://user-images.githubusercontent.com/51116144/61174692-a02ae800-a5de-11e9-8539-c5395e50adc2.png)
![Screenshot (2355)](https://user-images.githubusercontent.com/51116144/61174693-a1f4ab80-a5de-11e9-9168-a8adf02cbe64.png)
![Screenshot (2356)](https://user-images.githubusercontent.com/51116144/61174696-a3be6f00-a5de-11e9-91ca-c70c0d47952e.png)
![Screenshot (2357)](https://user-images.githubusercontent.com/51116144/61174697-a4ef9c00-a5de-11e9-81e0-d79db6c8caf6.png)
![Screenshot (2358)](https://user-images.githubusercontent.com/51116144/61174698-a6b95f80-a5de-11e9-81eb-e9e2dd892191.png)

**Comment by DemAvalon** [comment]
does the Pet pack have the same function as a pet carrier cause if so that would be awesome!

**Comment by CafeineCawfee** [comment]
Yeah I made the petpack be able to capture animals with the SMALL tag and found out through testing you can strap a petpack with an animal in it to other animals. And I am not sure about the survivor backpack adjustments. Do you mean increase the holding capacity for the survivor backpacks?

**Comment by DemAvalon** [comment]
either that or make survivor variants of the really big ones, also on the petpack: That is fantastic and adorable, I cannot wait to carry my pets around, thank you so much for doing this!

**Comment by CafeineCawfee** [comment]
Was planning on making 6 more backpacks if I can get these in. Maybe ill make two or three new survivor packs.

**Comment by chriseich21** [comment]
How does belly backpack function? Doesn't it auto equip on the back or can you 'change side'?

**Comment by bandti45** [comment]
weight, volume, and encumbrance aren't correct right now for a lot of items, that's a slow process that people with real numbers need to find and determine, but backpacks being closer to real-life would be nice.
