### ISSUE TITLE
knife spear is missing from Sōjutsu fighting style

### ISSUE THREAD

**Issue by sammy202020** [CleverRaven/Cataclysm-DDA#32343]
# see title. simple knife spear is useable with Sōjutsu fightings style but knife spear cant (the new version without the flimsy tag) 

# Steps To Reproduce

1.  pull up the fighting style Sōjutsu
2. read the weapons you can use
3. notice that knife spear inst there but simple knife spear is 

# Versions and configuration

windows 10
0.D-5547-gbf89376 (tiles)

so to fix this someone just needs to add "knife spear" to the list of weapons that can be used with  Sōjutsu fighting style

**Comment by LaVeyanFiend** [comment]
Swiggity swoon, there be a fix for it soon. ^_^
