### ISSUE TITLE
add a option in the menu so the user can adjust the hp regain and stamina rate  

### ISSUE THREAD

**Issue by sammy202020** [CleverRaven/Cataclysm-DDA#32344]
**Is your feature request related to a problem? Please describe.**  
not really i just am tired of seeing arguments about the hp and stamina change, and this solution would allow both "sides" of this issue to be happy. it allows people to still use what ever the default is but also allows people to who want a easier game to raise the rate they heal / recover stamina or those who want a harder game to reduce it

**Describe the solution you'd like**  
i want a option in the menu when setting up the world like the zombie density option but for healing and stamina 
**Describe alternatives you've considered**  
well honestly the only alternative is to make mods and this is just annoying work around. 

**Additional context**  
well if anyone wants an idea of to do this. just look at the menu and copy how you set the amount of zombies spawn. honestly i just want this so we can control the health regain and stamina recovery instead of being simi at the whims of what ever the current setting is post an update.  i understand if this never gets done but honestly the update to health and stamina really showed there needs to be some control on the users end of these settings that isn't pulling of the code and changing it on our end. plus this will stop most of the fighting over these type of changes in the future.

**Comment by ZhilkinSerg** [comment]
We have these options already - see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/game_balance.json

**Comment by sammy202020** [comment]
we dont have these options ingame though a menu and what you link to is a mod

**Comment by sammy202020** [comment]
> We have these options already - see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/game_balance.json

we dont have what i asked for. we have a mod that allows the stamina to be changed as you play and kill more zombies. i just wanted a ingame  option in a menu to set the values for stuff in game

**Comment by ZhilkinSerg** [comment]
There are in-game options that control stamina and health regain rates, thus you can control these rates. The thing that they lack in-game UI is insignificant and is not an issue.

**Comment by sammy202020** [comment]
I'll have to disagree with you.

**Comment by sammy202020** [comment]
I know i can change anything in the game if I pull the code up but the issue is it's a pain and there is next to no reason not to have an UI for this since it doesnt take away much by adding it. All it does is allow people who dont want to pull up note pad and tweak the code a little, to be able to change these settings whitch got changed to some peoples opinion way much.

**Comment by Night-Pryanik** [comment]
The game options menu already could be considered as over-cluttered. And in light of already existing ability to modify game settings by editing game_balance.json, we try not to add another arbitrary options in the menu not to clutter it further.

**Comment by SolarMoney2112** [comment]
oh, actually. This would make testing damage values and speed a lot easier. (Example: I make a new creature, spawn it in and let it attack me for a few turns. Then I regen to full in one sleep, and can continue testing without issues)

**Comment by sammy202020** [comment]
Not to argue to much more but only reason I even posted this is that health and stamina are fairly core mechanics that are fairly heated points of contention anytime there is a massive change like there has been lately. And putting the option in the menu does clutter it up a little bit more but it allows people who want a easyer game to make it easier and those who want it hard to make it harder without having to pull up the game_balance.json just to change it. And having to do so again at a later time if they change there mind or if they updated. I'll drop this just to not waste any more time arguing over this since it's clear never me nor you two will likely change our stance on it :p.
