### ISSUE TITLE
magiclysm - casting seismic stomp crashes the game

### ISSUE THREAD

**Issue by b0urgeoisie** [CleverRaven/Cataclysm-DDA#32369]
# Describe the bug

casting seismic stomp crashes to desktop

# Steps To Reproduce

cast seismic stomp

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5599-gfd556e6 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable NPC Needs [no_npc_food],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

[crashdebugsave.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3389274/crashdebugsave.zip)

![image](https://user-images.githubusercontent.com/52261571/61177164-74870e00-a59c-11e9-8908-beb1dd9f6710.png)

**Comment by ZhilkinSerg** [comment]
It does not crash now for me when run under debugger, but it shows following error message:

```
 DEBUG    : Tried to access invalid map position at grid (11,5,0)
 
 FUNCTION : get_nonant
 FILE     : c:\projects\cataclysm-dda\src\map.cpp
 LINE     : 8141
```
