### ISSUE TITLE
Vehicle part additional requirements are inaccurate if viewed with Bad Back

### ISSUE THREAD

**Issue by Canivir** [CleverRaven/Cataclysm-DDA#32361]
# Describe the bug

When removing/installing parts the requirements for strength (e.g. Lifting 1 or 10 Strength) are different if you have Bad Back, but still display old values but in red. I.e. I have 11 Strength and Bad Back and I want to remove a Heavy Duty Frame (req. Lifting 1 or Strength 10), it tells me I don't meet the requirement for 10 Str (shown in red) while I very clearly have 11 Strength.

# Steps To Reproduce

1. Make a Character with a Hacksaw, 10 Mechanics, 10 Strength and Bad Back
2. Spawn a Vehicle that uses Heavy Duty Frames.
3. Try to remove a Heavy Duty Frame and observe that it doesn't let you, while telling you that you need 10 Str (which you have).
4. Use Debug to remove Bad Back.
5. Observe that it is now possible to remove the Heavy Duty Frame.

# Expected behavior

For the Requirements listed to be the ones (and only ones) to remove parts.
Either make Bad Back not factor in here, change the requirement to be displayed differently depending on whether the player has Bad Back, or change the requirement displayed to be based on max weight capacity (and thus factor in bad back).

# Screenshots

![Bug1](https://user-images.githubusercontent.com/42702533/61173322-210fc280-a592-11e9-8859-b82f22b36b77.PNG)
![Bug2](https://user-images.githubusercontent.com/42702533/61173323-2240ef80-a592-11e9-9460-fac36a34c3df.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-5590-gabbd9f7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Alternative Map Key [alt_map_key],
    Folding Parts pack [deoxymod],
    Prevent Zombie Revivication [no_reviving_zombies],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Vehicle Additions Pack [blazemod],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by AlexanderUldall** [comment]
This is still an issue in the  current experimental version 10012.

Attached save game with character with strength 20 and bad back mutation. It is not possible to remove the storage battery from the vehicle he is standing in.

[El Verano.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3968873/El.Verano.zip)
