### ISSUE TITLE
Houses burn for a long time

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#32378]
# Describe the bug
Houses on fire used to burn down within two to three hours. Now, they burn for a much longer period. Possibly indefinitely.

# Steps To Reproduce

1. Set a house on fire
2. pass time in the rality bubble of the house.
3. indefinitely long zombie BBQ.
4. Also, no way to go get the rocks and nails :(

Latest experimentals

**Comment by kevingranade** [comment]
Need a source establishing houseburn times to call this a bug.

**Comment by Necrosian** [comment]
For me it's random, most of the time 2h are enough, but every now and then they burn for  a day

**Comment by Necrosian** [comment]
> 
> 
> Need a source establishing houseburn times to call this a bug.

Does, [this count](https://www.disastercompany.com/quickly-fire-spread/)?

**Comment by kevingranade** [comment]
No, AFAICT it just sets out a timeline for how quickly it engulfs a home.
Though it's a good resource for trying to adjust how quickly it spreads in the first place.

**Comment by Necrosian** [comment]
> 
> 
> No, AFAICT it just sets out a timeline for how quickly it engulfs a home.
> Though it's a good resource for trying to adjust how quickly it spreads in the first place.

Well in [this timelapse](https://www.youtube.com/watch?v=SueFx7x67Fc) it takes 90 mins if description ca be believed.

Apologies if i am bothering you.

**Comment by kevingranade** [comment]
I just tried this in game, and the majority of the house stopped burning in about an hour, so I'm not sure where you're getting indefinitely from.

**Comment by Necrosian** [comment]
It happened to me few times, not always but rarely. I even made a reddit thread when i was stuck in basement for  a day or so.

**Comment by kevingranade** [comment]
You need to include details like, "happens rarely" in the bug report.
Do you have the z-levels option enabled? If you don't it's working as expected since fire fields don't get updated outside the current level.

**Comment by Necrosian** [comment]
Since my post was closed i'll just paste my save here directly.
Save:
[Morgan Mill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3407305/Morgan.Mill.zip)
