### ISSUE TITLE
Clairvoyance doesn't doesn't negate crafting-related darkness

### ISSUE THREAD

**Issue by communistkiro** [CleverRaven/Cataclysm-DDA#32381]
# Describe the bug

Got a clairvoyance helm spawned recently, and noticed I can't craft or construct when it's dark- `You can't see to craft.` 

# Steps To Reproduce

Haven't tested, but gonna assume it's the same everywhere
1. Artifact with 10 or 11 worn/carried effect, that is, (super)clairvoyance.
2. Have it be dark.
3. Try and craft/construct sth.

# Expected behavior

The fact there's color and huge visibility (even thru walls with superclair), and being able to spot every single item on the ground with the `list all items around player` in a 40 tile radius- one would assume you have enough visual capability to boil some water. 

Either make it so it's not dark with regards to crafting and construction, or take out the color, like the IR vision or something similar. 

# Versions and configuration

 - Game Version: 0.D-5617-gb272735, build 9328
 - Graphics version: [Tiles]
 - Mods loaded: only mod with artifact things is CRT_EXPANSION, I believe, but it doesn't chance how they work, I think.

**Comment by kevingranade** [comment]
Working as intended, you can see items, monsters and other features well enough to identify them, but not well enough to craft.
