### ISSUE TITLE
Crafted clean water stays (hot) for far too Iong.

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#32388]
Game version: Latest as of 14th July 

Operating system: Win10

Tiles or curses: Tiles

Mods active: Cataclysm DDA, Disable NPC Needs, Simplified Nutrition

### Expected behavior
Water cools down to ambient temperatures or freezes if they're sufficiently low.
### Actual behavior
Water keeps the (hot) status for a very long time (up to a week as of current observations), even in freezing temperatures, and stays drinkable. 
### Steps to reproduce the behavior
1. Craft clean water at a brazier (?)
2. Put clean water in gallon jug.
3. Observe that it stays hot for 5 days to a week before cooling down.

**Comment by sammy202020** [comment]
just a heads up this happens with most things ive noticed if they spawn in hot and you walk away so there not inside your bumble of reality

**Comment by Bulletfang** [comment]
While it's true that things don't change outside the reality bubble, I've definitely and easily spent a hundred times more time right next to the hot water than it would realistically take to cool down from its (hot) status, even if the temperatures weren't freezing.

**Comment by kevingranade** [comment]
It might be related to my perf changes to item processing which should be adressed in #32376

**Comment by baldamundo** [comment]
> It might be related to my perf changes to item processing which should be adressed in #32376

Can confirm that this issue is still present in the latest experimental versions. Crafting clean water in a cold underground location in containers that aren't insulated, and have had multiple days pass without the "hot" tag dropping.
