### ISSUE TITLE
Survivor's logbook

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#32386]
**Describe the solution you'd like**  
Each time the character goes to sleep, a popup window offers him to enter his notes for the day. Those notes are stored with a time stamp in a log file "character's name logbook.txt". 
I think this will improve the "story" aspect of the game and may lead to some interesting reads from other players.

**Addt'l details**
The player should be able to enter several lines of text, ideally the number of lines should not be limited.
This feature will need to be set as a game option (disabled by default), this option is used only for new games (if enabled new games have the logbook prompt feature enabled). That part is not a priority if the following point is implemented.
It should also be possible to activate/deactivate it on a per game basis (for a particular save) without changing the game option default.
As an aide for the player entering the notes, a summary of the day's events can be shown (weather, character condition, kills, town discoveries...).
When the character dies, his/her logbook.txt must be kept somewhere and not deleted, for instance it could be saved in a dedicated folder not linked to the saves (e.g. 'logbooks').

**Describe alternatives you've considered**  
The notetaking could be an action triggered by the player ('write to logbook') but I think it is better to be prompted each time the character goes to bed. 

EDIT: added some details

**Comment by tinukedaya** [comment]
Very nice idea... Might also help getting back to older saves... I tend to have the problem with older worlds to which I want to return, that I forget what am I actually doing there, or what have I done already. Reading thru the log might help getting me up to speed. 

And I bet it will indeed result in some awesome stories being written.

**Comment by ZhilkinSerg** [comment]
We already automatically write memorial log which is kinda similar:

```
Game History
| Year 1, Spring, day 0 08:00:00 | fire station | Dania 'Coco' Hamrick began their journey into the Cataclysm.
| Year 1, Spring, day 0 08:16:06 | road | Stepped on a land mine.
| Year 1, Spring, day 0 08:16:06 | road | Dania 'Coco' Hamrick was killed.
```

**Comment by matt32106** [comment]
> We already automatically write memorial log which is **kinda similar**

The feature request is first and foremost for keeping track of the player's notes (system info should be secondary).

**Comment by ZhilkinSerg** [comment]
Memorial log does not contain system info. It is log of things that happened with player.

**Comment by FirebrandCoding** [comment]
Memorial log names its purpose in its name: it's a track of what happened to a *dead* character. The feature request is for player's active notetaking, which is meant to enhance roleplay and/or storytelling, and has nothing to do with the programming definition of a log.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Memorial log names its purpose in its name: it's a track of what happened to a _dead_ character.

Incorrect. Nothing happens with dead character. It is a log of what happened while character was alive.

**Comment by FirebrandCoding** [comment]
Fair enough. I'd only seen those in the game folder, of all the dead adventures I had accidentally slain.

This doesn't negate the purpose of the suggestion, nor does it diminish its importance or value to players.

**Comment by Inglonias** [comment]
A compromise would be to allow us to view the memorial log without actually dying, perhaps?

**Comment by tinukedaya** [comment]
> A compromise would be to allow us to view the memorial log without actually dying, perhaps?

And to add manual entries...
