### ISSUE TITLE
Port lua mods: Assault, Ebook

### ISSUE THREAD

**Issue by 4n0n4** [CleverRaven/Cataclysm-DDA#32385]
Hi all.
Could you port these interesting lua mods to the game:
**Assault** - alternative/addition to hordes, very customizable.
**Ebook** - scanning books into electronic format.
[Assault_MOD_Daiginjo_0.D_Ebook_v0_2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3389952/Assault_MOD_Daiginjo_0.D_Ebook_v0_2.zip)
Good day.

**Comment by kevingranade** [comment]
We're aware of the mods, but our issue tracker is entirely too jammed to keep wishlist issues about big content imports around.
