### ISSUE TITLE
Idea: Sadistic AI director ((c) Pj Zomboid)

### ISSUE THREAD

**Issue by TychaiosIlithios** [CleverRaven/Cataclysm-DDA#32389]
**Is your feature request related to a problem? Please describe.**  
Lack of endgame challenge for those who want it.

**Describe the solution you'd like**  
Fist and foremost I'd like to stress that such features are intended to be togglable and aim to provide 'fun' in endgame for whoever chooses to have it. From the many intended features I'd like to focus on ones already present in PJ Zomboid and Rimworld for easier reference.
1) Zomboid only - separate dates for game start and monster peak dates. Separate numbers for game start monster numbers and mob# peak monster numbers. Also besides currently standard evolution add linear switches to game start and peak date monster health and monster speed. And have all parameters gradually change from start to peak. Intended result is different 'fun' for start and end, with higher mob health adding much more reason to have high damage items like law and .50 cal or heavy mutated limb melee set. 

2) Both PJ-Z and Rimworld idea of Sadistic AI Director/Storyteller - form of AI overwatch over player condition and provision of 'fun' for whenever life's too easy. Fun can come in a lot of forms from 7dtd hordes to all manner funocalypses known to Rimworld storytellers.

Once again the idea is to have --optional feature-- allowing player to have something shake his lonely bubble with 'fun'.

**Describe alternatives you've considered**  
Alternatives mostly revolve around idealistic idea of sandbox providing all the fun off it's own mechanics or such thing as miniquests possibly generated State of Decay style by for example faction base.

**Additional context**  
The conflict is in player reality bubble being relatively narrow, and in case of player farming static location little to no sources of incoming fun. So more things must happen in the overmap like zombie hordes and at least optionally things should happen regardless of whether the nearby locations have been recently cleared. 

To add a pixel of realism and justification - incoming enemy organisms are parts of factions which share biology and partly might share neural functions, possibly resulting in ability to self-organize and maybe even react to intruder in manner similar to immune system.

Alzo possible system of AI Director could allow more utility for faction relations or possible police sanctions resulting in bot/drone attacks happening not when you actually meet drones, but when they are supposed to happen. Even with Z-levels off this could result in a number of climbing/flying units coming in a wave to that secret roof farm from time to time.

Thanks for reading.

**Comment by kevingranade** [comment]
We have plans to handle this in a world-oriented way with horde migration, competition with NPC factions, spreading alien/mobster factions, extensive monster evolution, resource decay, and timed world events.

**Comment by TheEventHorizon** [comment]
> 
> 
> We have plans to handle this in a world-oriented way with horde migration, competition with NPC factions, spreading alien/mobster factions, extensive monster evolution, resource decay, and timed world events.

Love the direction is going. When all those features are implemented it will be one hell of game!

**Comment by TychaiosIlithios** [comment]
Thanks for answering, although 'resource decay' sounds disturbing, as might mean many things, the rest means really juicy sandbox. 

With that in mind hope there will be some compensation for possible losses. For example implants in radio stores getting corroded in a few years, but hey-ho to skynet-screamer manufacturing of self delivering microchips! GJ, GL.
