### ISSUE TITLE
Power Armor not working with simple UPS

### ISSUE THREAD

**Issue by Bulaleks** [CleverRaven/Cataclysm-DDA#32396]
Power Armor successfully engages with simple UPS in inventory, but on next turn disengages. Happens only with simple UPS. Advanced UPS works just fine.

1. Make a player with a simple UPS and some Power Armor.
2. Activate Power Armor.
3. Power Armor deactivates itself on next turn.

Expected behavior:
Power Armor should work fine with simple UPS, because that stated in the simple UPS item description and in message log hint, when trying to activate Armor without power source.

![1](https://user-images.githubusercontent.com/15330166/61190137-1a6f7100-a6a0-11e9-842e-0e037c6a4b51.jpg)
![2](https://user-images.githubusercontent.com/15330166/61190139-20655200-a6a0-11e9-861c-23f0dda0c579.png)
![3](https://user-images.githubusercontent.com/15330166/61190140-22c7ac00-a6a0-11e9-88dc-3c263582edd1.png)

 - OS: Windows 10
 - Game Version: 0.D-5621-g65cbcde
 - Graphics version: Tiles
 - Mods loaded: DDA, disable NPC needs, Modular Turrents, Salvaged Robots, Urban Development, Vehicle Additions Pack, Tanks and Other Vehicles.

**Comment by Inglonias** [comment]
The fact that it activates but doesn't stay on suggests that this got missed with my previous iuse fixes. I'll see if I can take a look but considering today is the first day I wore pants besides sweatpants since my injury, I can't say when I can actually look.

**Comment by Ivan-Shestakov** [comment]
Yep, I see this too in my game. 
The advanced UPS (which requires plutonium cells) doesn't disengage, but still won't reduce encumbrance when activated - same as described in #32459.

**Comment by misterprimus** [comment]
Happens with invisibility cloak as well
