### ISSUE TITLE
Problem with construction menu

### ISSUE THREAD

**Issue by Aeiouuu01234** [CleverRaven/Cataclysm-DDA#32400]
# Describe the bug

the prompt of "fill pit with dirt" cannot be activated, even when the line selected in the construction menu shows that the materials, tools and requirements are at hand

# Steps To Reproduce

1. Make a player with any tools with 2 and upper digging quality. 
2. Dig a deep pit.
3. Open Construction menu, go to the line "Fill Pit With Dirt"

# Expected behavior

It's supposed to create the construction, filling the pit and consuming the soil next to it 

# Screenshots

**If applicable**, add screenshots to help explain your problem.

![Captura de pantalla (25)](https://user-images.githubusercontent.com/52901609/61194452-09fecc80-a687-11e9-97d2-b77da7fd8acd.png)
![Captura de pantalla (26)](https://user-images.githubusercontent.com/52901609/61194453-0a976300-a687-11e9-9da1-6eda90e920a1.png)
![Captura de pantalla (27)](https://user-images.githubusercontent.com/52901609/61194454-0a976300-a687-11e9-9b98-a3b3787458bd.png)
![Captura de pantalla (24)](https://user-images.githubusercontent.com/52901609/61194455-0a976300-a687-11e9-903f-7aac331c60c4.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-5621-g65cbcde [64-bit]
- Graphics Version: Tiles
- Mods loaded:
[ Dark Days Ahead [dda] ]

# Additional context

i don't think that it needs more

**Comment by BevapDin** [comment]
A requirement for that construction is "check_empty", which checks that the target tile is empty. This check includes traps (if there is a trap, it's not empty).

But deep pit always have a trap, they *are* deep pit traps.

**Comment by Aeiouuu01234** [comment]
it's fixable?

**Comment by Aeiouuu01234** [comment]
> A requirement for that construction is "check_empty", which checks that the target tile is empty. This check includes traps (if there is a trap, it's not empty).
> 
> But deep pit always have a trap, they _are_ deep pit traps.

It's Fixable?
