### ISSUE TITLE
Reload times haven't been updated for new turn times

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#32403]
# Describe the bug
`item::info` has code displaying reload times that still uses the 16.67 divisor constant from when turns were 6 seconds. I found that in 66441f1 but we should check all the code doing the timing calculations as well as the code displaying them to make sure everything is calculated accurately for 1 second turns.

# Expected behavior
All code is updated for 1 second turns.

# Versions and configuration
Affects up to at least commit cf1bfcf0ff39823ee154d4010eae76a447ca0619 in the master branch (latest master at time of writing).

**Comment by Qrox** [comment]
I think this also happens to the spoiling time of food, which now displays as 6 times larger than before. Not sure if the actual spoiling time is affected.

**Comment by kevingranade** [comment]
the one-second change was also blocking us from revisiting reload times in a more realistic way, now that it's done we can adjust reload times to more closely match reality.

**Comment by Leland** [comment]
Fixed by #33272

@Raschert0 correct me I'm wrong

**Comment by Raschert0** [comment]
I'd say that #33285 fixed display bug in better way. So, that is fixed. But I also thought that this issue is more about reload times in general (because many guns now reload 6 times faster (if we measure time in seconds)) so I haven't marked it as fixed in my PR. Correct me if I'm wrong.
