### ISSUE TITLE
Error while trying to make changes in the options menu

### ISSUE THREAD

**Issue by CafeineCawfee** [CleverRaven/Cataclysm-DDA#32401]
# Describe the bug

Starting the game crashes the game and once launching the game again options reset and trying to results in an error 

# Steps To Reproduce

1. Start game on latest build.
2. After crash relaunch the game go into options menu edit a setting and exit saving the edits.

# Expected behavior

Game should save your settings and not crash or result in a error.

# Screenshots

![Screenshot (2369)](https://user-images.githubusercontent.com/51116144/61195277-ec227d80-a701-11e9-9f9f-37f3ca7f40fc.png)
![Screenshot (2370)](https://user-images.githubusercontent.com/51116144/61195284-f5abe580-a701-11e9-9e64-fc2539063543.png)
![Screenshot (2371)](https://user-images.githubusercontent.com/51116144/61195289-00667a80-a702-11e9-923e-410eef521822.png)

# Versions and configuration

 - OS: Windows 100
 - Game Version: 0.D-5664-ged568d9
 - Graphics version: Tiles
 - Mods loaded: None

# Additional context

Trying to create a new world will result in an error.
Trying to force fullscreen, or trying to resize the window will result in a crash.

[crash and debug.ZIP](https://github.com/CleverRaven/Cataclysm-DDA/files/3390826/crash.and.debug.ZIP)

**Comment by roaringjohn** [comment]
This supposedly happens when trying to save anything.

**Comment by glenmack** [comment]
Looks like introduced in build 9333, perhaps something to do with "change file writing to go to temporary file" confirmed for me on build 9333 onward.

**Comment by BevapDin** [comment]
It works fine on a Linux system, but I can reproduce the error with the Windows build on Windows.

I suspect it has something to do with our own `rename_file` functions, specifically with the call to `rename` in it. Maybe Windows own `rename` function does not handle a path with leading "." or with "/"?
