### ISSUE TITLE
Obsolete the paper cartridge pouch, change professions starting with it to ammo pouch

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#32419]
**Is your feature request related to a problem? Please describe.**  
With the addition of the ammo pouch, the paper cartridge pouch is obsolete in function.
-Lower capacity(14 vs. 60)
-Lower variety(paper shot and blunderbuss only vs. 45 different types, including paper shot)

Side note: Why is the blunderbuss ammo so big? _One_ shot is a quarter liter in volume, versus most ammo capping at .01 to .03l per.

-Worse crafting requirements(Tailor 3/marksman 1 vs. Tailor 2/Surv 1)
-Equal tools and materials required.
**Describe the solution you'd like**  
Move the paper cartridge pouch to obsolete.json, and change all professions that have it to the new ammo pouch instead.

**Describe alternatives you've considered**  
Buffing the paper cartridge pouch to hold more than the ammo pouch, restricted to original ammo types. Since the ammo restriction would then become arbitrary, this is not a good option.

**Comment by brannamm** [comment]
Are you talking about "leather pouch" when you say "ammo pouch"? That is the only item I could find that has the skill and material requirements that you mention.

If so, the paper cartridge pouch does have an advantage over the leather pouch - it is faster to pull ammo out of the paper cartridge pouch.
