### ISSUE TITLE
Crafting clean water does not use dirty water

### ISSUE THREAD

**Issue by goralight** [CleverRaven/Cataclysm-DDA#32411]
# Bug Description

When crafting clean water from the crafting menu, the dirty water does not deplete. Resulting in infinite water. Also notice, that when looking at the "Components required" area for clean water, it will say I will use 1 of 2,147,483,647. Some reason it seems to be assigning it the max value of int?

# Steps To Reproduce

1. Have a container with dirty water in your inventory along with a method of cooking it. Test used wood stove.
2. Bring up the crafting menu and find the recipe for clean water. Notice how it is using the max value of int.
3. Either batch craft or single craft (test used both) the recipe and store the crafted clean water in a container
4. notice how the container storing the dirty water has not reduce the amount you specified and remains the max value of int. Thus, unlimited water.

# Expected behavior

When crafting clean water, the dirty water's amount is reduced by the amount specified and it is not possible to infinitely create clean water.

# Screenshots

![Infinite clean water bug](https://i.imgur.com/7R9ABH7.jpg)

# Versions and configuration

```
- OS: Windows 10
    - OS Version: 10.0 1903
- Game Version: 0.D-5673-g1a12348 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Garden Pots [growable-pots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics]
]
```

# Notes

It seems this was fixed in `#29532` but ...

**Comment by LaVeyanFiend** [comment]
And you're not near a pool of shallow water? Usually you only see that high number from crafting while near a water source.

**Comment by goralight** [comment]
Sorry should have mentioned this. No I was just next to a wood stove underground, within a LMOE shelter. Unless the LMOE gives free water wherever you are within the shelter?

**Comment by ZhilkinSerg** [comment]
> 
> 
> Sorry should have mentioned this. No I was just next to a wood stove underground, within a LMOE shelter. Unless the LMOE gives free water wherever you are within the shelter?

Aren't there shallow water tiles south of the stove?

**Comment by goralight** [comment]
I will double check when I am back at my computer. Hopefully not a derp moment 👀

**Comment by kevingranade** [comment]
Whether that's the problem or not, I wonder if we can shim in a message
somewhere that says you pulled the water from a ground source to make it
obvious what's happening

**Comment by goralight** [comment]
Turns out there was a water pump in the corner of the room which I completed ignored :( Sorry for wasting your time. If you want to use this report for an enhancement for detailing where the water is coming from, by all means.

Sorry again
