### ISSUE TITLE
Impossible to remove fouling from firing black powder ammunition

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#32414]
# Describe the bug

Unable to clean out fouling from firing black powder ammo from any gun, and thus makes any fouled gun fouled permanently.

# Steps To Reproduce

1. Shoot gun using blackpowder ammo until it clogs from fouling.
2. Attempt to remove fouling with pipe cleaner or repair kit.
3. There is no action to declog on either item. Repairing with kit just accurizes the gun.

# Expected behavior

An action for "clear fouling" on the pipe cleaner or repair kit.

# Screenshots

Not applicable.

# Versions and configuration

Windows x64, Tiles Version
Version: Experimental 9338/0.D-5673-g1a12348
Mods loaded: CDDA, Magiclysm, Disable NPC Needs.

# Additional context

None.

**Comment by Edgar-cy-Lee** [comment]
I have tested this. Only way to clear the fouling is to use "mend" after clicking the gun.

Not so sure why you would ever want blackpowder ammo though, since my testing clogged my gun even before firing it.(used burst 5)

**Comment by LaVeyanFiend** [comment]
> Not so sure why you would ever want blackpowder ammo that can foul(I think it is limited to 9mm blackpowder ammo) though, since my testing clogged my gun even before firing it.(used burst 5)
That's just a bug with some of the ammo not being flagged as blackpowder, it should be covering _everything_ that uses black powder ammo.

**Comment by Edgar-cy-Lee** [comment]
Then you can expand my comments to every blackpowder ammo that can clog. It is more unreliable than old knife spear.

**Comment by Rail-Runner** [comment]
Yeah, fouling cleaning is done via "mend" action on the guns, while having a pipe cleaner or a firearm/gunsmith repair kit.

As for gun fouling up with blackpowder before making even one shot, I've noticed this somewhat weird logic and already fixed it in #31485 , though it's unmerged yet.
