### ISSUE TITLE
can't dig up Clay

### ISSUE THREAD

**Issue by TJKing293** [CleverRaven/Cataclysm-DDA#32417]
# Describe the bug
can't dig Clay

# Steps To Reproduce

when using a shovel 4 options appear
1. clear rubble
2. dig pit
3. fill pit/tamp ground
4. Upturn earth

# Expected behavior

need an option to dig up clay or allow the previous options to perform the action, so that the extract clay action in the construction menu

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.C-33156-gd0fe67e
 - Graphics version: Tiles
 - Mods loaded:  "dda",
  "no_npc_food",
  "alt_map_key",
  "More_Survival_Tools",
  "boats",
  "no_mutagen",
  "no_religious_Texts",
  "No_Acid_Zombies",
  "No_Explosive_Zombies",
  "novitamins",
  "StatsThroughSkills",
  "no_reviving_zombies"

**Comment by Aeiouuu01234** [comment]
extract clay is in the construction menu

**Comment by ProfoundDarkness** [comment]
BTW, now you now need to find a clay terrain tile as well.  It's an actual terrain item.  They occur occasionally along rivers.  Also there is supposedly a chance that extracting clay from a tile will exhaust the supply of clay there (though I haven't had it happen yet, I haven't dug up a lot of clay either).
