### ISSUE TITLE
completeing the ranch quests when the ranch map special is spawned a certain way causing constructions to spawn incorrectly

### ISSUE THREAD

**Issue by JJuniorJr** [CleverRaven/Cataclysm-DDA#32424]
# Describe the bug

completeing the ranch quests when the ranch map special is spawned a certain way causes the constructions to spawn incorrectly

# Steps To Reproduce

The bug only shows up when the garage tile of the ranch is situated on the left or right side. Top or bottom facing garages dont have the bug. The foreman and carpenter will have spawned outside of the garage, on the mounds of dirt directly behind it.

1. Accept the second refugee questline that spawns the foreman and carpenter.
2. Complete quests provided by foreman.
3. See the the constructions are spawned incorrectly (i.e. lone door and wall spawned outside of the barn, beds spawned over the walls of the barn)

# Expected behavior

The foreman and carpenter usually spawns inside of the garage, and the constructions usually dont break the barn area.

# Screenshots

![map](https://user-images.githubusercontent.com/48772725/61253246-53eebd80-a72e-11e9-8edf-f8cde0fa41a3.png)

![outside](https://user-images.githubusercontent.com/48772725/61253254-58b37180-a72e-11e9-8324-994a5b2ea4f2.png)

![planks](https://user-images.githubusercontent.com/48772725/61253258-5cdf8f00-a72e-11e9-9eae-57f6fc7291ec.png)

![blankets](https://user-images.githubusercontent.com/48772725/61253268-68cb5100-a72e-11e9-836e-896436f94869.png)

![nails](https://user-images.githubusercontent.com/48772725/61253275-6f59c880-a72e-11e9-856a-fb14b6247681.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5683-gcd6579b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    PKs Rebalancing [PK_REBALANCE],
    Mutant NPCs [mutant_npcs],
    Zetsukaze's Hair Extensions! [zets_hair_extensions],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    PK - No Doom Monsters [PK_No_Doom],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes]
]

I'm using the unofficial patched version of pk's mod

**Comment by SunshineDistillery** [comment]
I've seen a version of this bug too.  Something in mapgen_updates causes it to get confused by tiles rotated 90 or 270 degrees.,
