### ISSUE TITLE
Faulty bionic removal crashes

### ISSUE THREAD

**Issue by communistkiro** [CleverRaven/Cataclysm-DDA#32435]
# Describe the bug

Trying to remove certain bionics, but not all, of the faulty ones results in crashing. I couldn't remove one, and saw something in the log that made me thing the tileset was not up to date or something... I'd recently downloaded the undead edition, to see if there were any noticeable differences- changing it back to the default of MSX++DeadPeople let me uninstall the bionic. However, only that one, the Acidic Discharge crashes on both editions, as well as ChestHole32, and ASCIITiles.

# Steps To Reproduce

1. Broken cyborg in lab.
2. Debug in anesthesia, an autodoc and its chair.
3. _Successfully_ try to remove the first one- `Acidic Discharge`.

# Expected behavior

Normal removal.

# Versions and configuration

 - OS: win7
 - Game Version: 0.D-5687-g805314, build 9340
 - Graphics version: MSX++DeadPeople, UNDEADPEOPLE, ASCII, and another one, all crash
 - Mods loaded: none

# Additional context

Save file with crash and debug logs [save.7z](https://www71.zippyshare.com/v/WQQnxwTS/file.html)

**Comment by Fris0uman** [comment]
```
src/cata_tiles.cpp:594: tile t_chainfence_season_winter has no (valid) foreground nor background
17:31:54.332 ERROR SDL : src/cata_tiles.cpp:594: tile t_chainfence_h_season_winter has no (valid) foreground nor background
```
As far as I understand the log suggest the crash is unrelated to the CBM, but is due to the chain fence not being set properly.

**Comment by Fris0uman** [comment]
I can't reproduce the crash, not with ASCIITiles not with deadpeople and not with MS32Moded.
I also tried to place a chainfence  in winter and it didn't do anything.

**Comment by anothersimulacrum** [comment]
I can reproduce the crash, on Linux.
It seems to occur on line 2919 of activity_handlers.cpp
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3398019/crash.log)

**Comment by communistkiro** [comment]
Hm, strange. Redownloading the save I tried to remove the acidic discharge, however it failed so it continued.
Trying again, it failed with same crashlog.

**Comment by Fris0uman** [comment]
Probaby caused by #31763 then.

**Comment by communistkiro** [comment]
Then it should be error to debug in Acidic Discharge and install it, right? Starting as a lab technician in the labescape scenario, by luck, in the same location so autodoc and anesthesia already in place. I could successfully install it. Upon trying to uninstall it however the same crash log.

**Comment by communistkiro** [comment]
Increase day by 5 let me remove one I previously could not.

**Comment by AMurkin** [comment]
> Probaby caused by #31763 then.

I left a comment there. @Fris0uman
