### ISSUE TITLE
Normal medical bionics

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#32430]
**Is your feature request related to a problem? Please describe.**  
There are a lot of bionics for punching monsters, but not many for medical purposes.  You would expect that there would be more bionics out there for fixing humans rather than enhancing them.  

**Describe the solution you'd like**  
Add some consumer-level medical bionics to water down the loot pool.  

**Describe alternatives you've considered**  
If you wanted them to have a game function, you could have them work like telescope eyes and nearsighted work now.  

1. Add some debilitating medical traits
2. Have bionics that remove said traits
3. Make a reverse faulty-cyborg profession, a faulty human that wants bionics.

**Comment by glenmack** [comment]
It's not entirely necessary to add any medical problems. We have several without a "fix" right now.

- Deafness - Enhanced hearing CBM I don't think currently will heal being deaf, which it probably should.
- Asthma - Some nano-fiber lung bionics could heal asthma. Might be good for water breathing?
- Food Intolerance and weak stomach - Expanded digestion should probably cure this in every case.
- Bad Back/Bad knees - Kinetic shock absorber? I think that slots legs and torso, should probably cure this.

There are at least three good contenders there to augment existing CBMs and traits to test feeling on this.

**Comment by Amoebka** [comment]
Food intolerances are presumed to be mental blocks, not actual medical conditions. CBMs shouldn't fix those.

**Comment by Mister-Cultist** [comment]
How about a trait that gives heart problems that can cause chest pain/loss of stamina and you can get a bionic heart that removes the problems and gives you enhanced stamina regen

**Comment by nexusmrsep** [comment]
Farsightedness and shortsightedness are certainly possible candidates for optical adjusting CBM.

**Comment by nexusmrsep** [comment]
Also, on the far end, I'd like to see actual CBM prosthetics, and the feature to actually lose a limb or have it mangled in a way that only replacement with prosthetic would recover it's functions. Lost an eye? Eye CBM to the rescue. Zombear has mangled your leg and broken bones healed with a faulty or vicious union? Leg CBM to the rescue.

**Comment by Zireael07** [comment]
We don't need imagined medical conditions, we have plenty of real life conditions in the game.

The hearing cbm I believe fixes deaf effect, and similarly, getting one of the eye cbms (unsure which one) cures short/farsightedness.

Asthma and some sort of a lung cbm would be a great fit.

I think we do have some sort of a blindness effect (poison? artifact?), this is also a candidate for getting fixed via CBMs.

Oh, I just thought of some more traits that probably qualify as real life medical conditions, that is Heavy Sleeper and the insomnia mutation/trait, they could also be negated by a proper cbm (some sort of a melatonin dispenser). Also Thin Skin is a real life condition, and Armor Plating CBM should probably negate it, and we could also get a skin cbm of some sort that negates the trait and gives a minor bonus to hp.

Albinism is also an existing medical condition that we do have in game, but not sure how a cbm could heal it.
