### ISSUE TITLE
Magiclysm - trait duplication at character creation

### ISSUE THREAD

**Issue by MWalcz4k** [CleverRaven/Cataclysm-DDA#32434]
# Describe the bug
This bug allows creation of character with multiple magic professions such as "Animist" or "Stormshaper". I was able to create a character like on the screenshot below without using debug menu.
![pic rel](https://media.discordapp.net/attachments/252368751016542218/600696659348946963/Screenshot_81.png?width=623&height=676)

# Steps To Reproduce

1. Start creating new character
2. Create any character with a profession
3. Start a game
4. Load up preset character
5. Change profession
6. Poof! You have 2 professions!

# Expected behavior
Not duplicate professions...

# Screenshots
Screenshot is above

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5687-g8058314 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Filthy Clothing [filthy_morale],
    Bens GF recipes [Tolerate_This],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Acid Zombies [No_Acid_Zombies],
    No Explosive Zombies [No_Explosive_Zombies],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Dark Days Ahead: Lua [dda-lua],
    Magiclysm [magiclysm]
]

# Additional context
n/a
@KorGgenT

**Comment by chriseich21** [comment]
Currently Magiclysm also adds mana traits into character creation, even if the mod is selected. Not a big deal but if you do random player, sometimes you get something for mana efficiency and have to go back and replace it. Like CRIT, it should only add the traits if you choose to use the mod

**Comment by KorGgenT** [comment]
what? those traits are in the mod files, so i have no idea how they're getting loaded if you aren't loading the mod also

**Comment by chriseich21** [comment]
Sorry was going to post it as an issue instead since these are different, but I'm not using magiclysm and it's loading, one sec I'll post screenshot

**Comment by KorGgenT** [comment]
yes, please post it in a new issue. i was just incredulous that it happened at all.

**Comment by chriseich21** [comment]
Disregard, somehow magiclysm was in mod list, must've accidentally clicked it last time I remade

**Comment by BenlyAZ** [comment]
As a consequence of this, it's impossible for a character in the Wizard's Apprentice start to take up Kelvinism - Novice Stormshaper is the selected profession by default as soon as you choose the scenario, so any character who is created with this scenario will have the Stormshaper trait regardless of what profession you choose.
