### ISSUE TITLE
The Electric Car's engine fails to start

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32439]
Electric engines should start reliably regardless the damage. An electric engine either starts or it doesn't IRL, there's nothing to pre-spin, heat, pressurize and ignite.

**Comment by tinukedaya** [comment]
I don't get what is the problem...

> ... An electric engine either starts or it doesn't IRL, ... 

So... if it doesn't start... doesn't it mean that it fails to start?

**Comment by l29ah** [comment]
No, it means it's broken for good.

**Comment by bandti45** [comment]
it would be nice if an article or some other evidence could be provided for this issue especially since there are more parts to an electrical engine working (because of the electronic nature) then a gas-fueled engine
