### ISSUE TITLE
.600 Nitro Express revolver request

### ISSUE THREAD

**Issue by Mister-Cultist** [CleverRaven/Cataclysm-DDA#32437]
When it comes to late game, hand guns become less and less viable againt the kevlar hulks roaming the land, as a solution I propose we introduce the "Pfeifer Zeliska .600 Nitro Express revolver". The ultimate in over compensation. A pistol being able to fire Nitro express rounds would be a perfect holdout weapon for the late game, that and it would be somthing to look foreward to finding. If it was implemented you'd probably want to give it so much recoil to almost be unusable unless you were incredibly strong and skilled. Honestly just a fun idea all in all.
![73786557b8023d8b00e5a41f3d7b4422](https://user-images.githubusercontent.com/44286709/61315426-11b6a080-a842-11e9-9906-093dfb028b2a.jpg)

**Comment by anothersimulacrum** [comment]
Why don't you just [add it](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors)? It's a simple JSON addition.

**Comment by Bulletfang** [comment]
Absolutely yes, please. Make it damage your wrist if your strength is below a certain threshold too, just for the hell of it.

**Comment by Mister-Cultist** [comment]
> 
> 
> Why don't you just [add it](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors)? It's a simple JSON addition.

yeah I probably should try, I'm just utterly garbage when it comes to sorting through the game's code.

**Comment by anothersimulacrum** [comment]
JSON isn't code, it's basically text. That guide should cover it pretty well, but there are also some things that are covered in the files in `doc/`.

**Comment by kevingranade** [comment]
Do be aware that we try to respect real life rarity of items, so there
should probably not be more than one or two of these within range of the
PC, and you could go 100 games without seeing one.

**Comment by FulcrumA** [comment]
With that in mind, it should also be noted that it won't really solve the kevlar hulk problem. Which is fine because those were meant to be hard mod monsters that average gun would not deal with too easily. In a way it's a non-issue.

**Comment by NickGrease** [comment]
"hand gun" 🤣
