### ISSUE TITLE
What should be the standard for dialog description?

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#32433]
**Is your feature request related to a problem? Please describe.**  
Currently, dialog with NPCs are entirely verbalized, what I mean by that is that people don't shake their heads to say no, don't wave their hands while saying hi, that kind of thing.

**Describe the solution you'd like**  
Create a standard for descriptions of actions during dialog with NPCs like so:
![example](https://user-images.githubusercontent.com/29681506/61293395-f8faac00-a7a9-11e9-8df8-a73e599c0be5.jpg)

This would allow writers a lot more freedom when writing dialog, this is doable now, but I bring this up so we may decide what would be the standard way of doing this, do we make *descriptions italics?*, do we put it between *s?, do we [encase it like the above example?], something that would also be great for this would be having description text display in a different color.

**Describe alternatives you've considered**  
there are myriad ways of doing this, so there are many alternatives or we could have dialog be entirely verbalized but that seems too limiting.

**Additional context**  
Greg schmuck:
[Greg sees you and begins waving his arms enthusiastically, his comb-over swaying from side to side]

"Player my doll, where have you been? I wanted to discuss my newest zombie killing machine with you!"

a "Hi Greg what is it?"
b "This one isn't going to set the half the building on fire too, will it?"
c [Hide your face with your hand and pretend you don't know him]

**Comment by FulcrumA** [comment]
As I'v stated on the channel when you brought this subject, it'd be nice if there'd be a way to color text in dialogue windows. Then we could make a standard for various colors to denote certain things, like default white for spoken lines, yellow for gestures, descriptions of actions and circumstances (overall narration), blue for robotic/radio voices etc.

It'd work both for actual dialogue lines and for choices.

**Comment by SunshineDistillery** [comment]
In the examples in NPC.md and TEST_TALK.json brackets are used for noting a player's ability.  Like 
[PER 10] I see some stuff.   
I was going by that.

I think adding *foo makes text light red and &foo does something.  When a trial could make an NPC hostile it is automatically in red an gives a pop up.  So it's there, it just needs to be standardized in the doc and maybe have some stuff moved to json.  But, yeah. I think colors are preferable to punctuation.
