### ISSUE TITLE
Craftable Acetylene

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#32441]
**Describe the solution you'd like**  
After some digging, it looks like acetylene is eminently craftable, so I'm dropping my notes in case someone gets the urge to implement it.
Following the guide here: https://panam1901.org/miscbuildings/acetylene/acetylene_article.htm
Crafting Calcium Carbide (CAC2) requires:
`` Ground coke and lime are intimately mixed in the proper proportions and placed in the electric furnace-, the result is that fifty-six parts of lime and thirty-six of coke will make sixty-four parts calcium carbide and liberate twenty-eight parts carbon monoxide.``
The furnace is heated to ~4,500F, so it's a pretty serious furnace.
The resulting ingot is relatively stable except in contact with water, so it can be handled more or less normally with just a sealed container or even a wrapping.
So materials list:
Heavy-duty furnace
Coke
Lime
From there, generating and capturing Acetylene via CAC2 / H2O reaction is relatively straightforward as outlined here:
https://chestofbooks.com/home-improvement/repairs/Mechanics-Household/Types-Of-Acetylene-Generators.html
This part is potentially more involved as it involves some fairly heavy looking metalwork, but it results in a fairly renewable acetylene source for welding, and perhaps for other uses such as lighting and heating.

**Comment by DeltaEpsilon7787** [comment]
Honestly, even if you do manage to synthesize acetylene, mixing it with oxygen is an entirely different matter altogether.

The best substitute by far would probably be an electrolysis cell with consumable electrodes to produce a perfect oxyhydrogen mix that works just as well as oxyacetylene. The torch itself probably doesn't care.

**Comment by l29ah** [comment]
There also needs to be a way to pressurize the gas to fill the existing tank items. On the other hand, the torch can be hooked to the acetylene generator that consumes water and CaC2 without intermediate gas storage (but it's less controllable, and you need to make sure the gas generator doesn't explode due to underutilization).

**Comment by l29ah** [comment]
Acetylene is mixed with oxygen in the torch itself. It's impossible to store acetylene and oxygen premixed, since they explode on contact.

**Comment by DeltaEpsilon7787** [comment]
>Acetylene is mixed with oxygen in the torch itself.

Then somehow you need to connect an oxygen tank and an acetylene tank together. Guess something like a railgun that consumes both battery power and a rail rod, but with oxygen and acetylene.

**Comment by DeltaEpsilon7787** [comment]
That reminds me that Ca2C is a pretty common find in mechanical shops for exactly this reason. Oxyacetylene torches are relatively rare, but Ca2C isn't.

**Comment by kevingranade** [comment]
> the torch can be hooked to the acetylene generator that consumes water and CaC2 without intermediate gas storage (but it's less controllable, and you need to make sure the gas generator doesn't explode due to underutilization).

This is what I was envisioning, this gets you a relatively clean source of Acetylene gas at a constant pressure, but it's very much not portable, for that you need a whole different setup downstream of the generator to handle pressurization.  Actually the reaction itself provides pressure, so you MIGHT not need a pump.

> Then somehow you need to connect an oxygen tank and an acetylene tank together.

I believe this is in-progress, but also you can do something like figuratively but not literally combine the gasses by reloading your generator with water, Ca2C, and oxygen and having it produce fake "OxyAcetylene gas" that gets used by the torch.

**Comment by kasanryukin** [comment]
I'm half asleep, but my brain is telling me you could pressurize the gas to a a couple atmospheres at least with a mashed setup of a bike pump and a homemade check valve out of leather or rubber, similar to what a real bellows uses.   The gas would have atmosphere gas contamination and wouldn't burn as clean as pure acetylene, but since acetylene burns with atmospheric oxidation anyway the only penalty would be a loss of efficiency in a welding application.

Gimme a couple hours and a cup of coffee and I can mock up some .json entities for debate.

**Comment by kasanryukin** [comment]
First pass done, covers creation of calcium carbide with associated code and json entries.  Making a PR for review before I move on to the acetylene side.

**Comment by communistkiro** [comment]
Wouldn't it be fun if you could get deaded from carbon monoxide if you don't have a fume hood or aren't outdoors/have an open door/window :D

**Comment by communistkiro** [comment]
By the way, very easily you can get oxygen creation via electrolysis kit and a battery, it's kinda expensive irl, but would be a reason to reduce somewhat the amount of (emergency) oxygen tanks in-game.  [https://en.wikipedia.org/wiki/Electrolysis_of_water#Thermodynamics](water electrolysis wiki), platinum's already in-game. 
So the idea- change `platinum grille` to just `platinum catalyst`, or add in a platinum plate (created with a forge w/ only platinum), 
Double amount of hydrogen as a byproduct, which you could just pour on the ground, where it'd dissipate, until any recipes with hydrogen get added.

**Comment by DeltaEpsilon7787** [comment]
It should be noted electrolysis is _very_ inefficient and quite slow. You can't just stick platinum sticks into water and expect much result from it. You need _a lot_ of surface area to have any significant production and of course a fairly high amount of energy.

**Comment by DeltaEpsilon7787** [comment]
As it stands, I still suggest producing oxygen from hydrogen peroxide.

**Comment by communistkiro** [comment]
> As it stands, I still suggest producing oxygen from hydrogen peroxide, it's way faster and it gives another use to it as opposed to adding another item in game just for an essentially single craft that's not even all that relevant since electric welding is still way more efficient.

A small bottle of 30% (what I usually find as conc. hydrogen peroxide solution) would be 2.45 mol H2O2, w/ standard decomp. route you'd get 1.225 mol O2, which is either a lot or very little depending on the application or need. I also don't know the assume pressure of any of the tanks in game, be tank the welding one, (emergency) oxygen, hydrogen ones.

**Comment by kasanryukin** [comment]
At the moment I intend to use existing emergency oxygen packs as an input as well as raw acetylene. I haven't worked out what numbers i want since I need to dig a little into what values recipes are calling for when using weldgas instead of an arc welder.  On the subject of acetylene I'm envisioning an item that functions like the smoking rack. Takes input in the form of a 2L tank, water, and CaC2 and outputs a 2L tank of raw acetylene.

Thoughts? That's where I'm at with the code and json at the moment and would like some feedback before I dive in.

**Comment by kasanryukin** [comment]
Final version is up for review/playtesting.  I'd appreciate anybody interested in this feature to test it and give feedback on how balanced it is, or isn't.
