### ISSUE TITLE
“More Survival Tools”, “Salvaged Robots” and Classes and Scenarios" Mods - Add or remove various base professions after Build#9335

### ISSUE THREAD

**Issue by Corvus-Dismas** [CleverRaven/Cataclysm-DDA#32444]
# Describe the bug

The Mods “More Survival Tools” and “Salvaged Robots” remove all professions in the Wilderness Scenario besides the ones they add themselvs after the changes of Build#9335 / https://github.com/CleverRaven/Cataclysm-DDA/pull/31661  which allowed all professions in the Wilderness Scenario.

The Mod “Classes and Scenarios Mod” allows all professions in the "High Tech, Low life" Scenario. Did not happen befor Build#9335 (intended?)

# Steps To Reproduce

1. Add above mentioned mods
2. Create world with mods active
3. Choose Wilderness or High Tech, Low life Scenarios
4. See that only the added professions from "More Survival Tools" or "Salvaged Robots" are enabled as professions choices and nothing else for the Wilderness Scenario (Wanderer, Prehistoric Hunter, Robo Hunter)
5. See all the professions allowed for High Tech, Low life, instead of a limited selection.

# Expected behavior

Wilderness Scenario should have alle the professions allowed as stated in: 

https://github.com/CleverRaven/Cataclysm-DDA/pull/31661 

or at least the ones that were allowed befor that. Not only the ones "More Survival Tools" and "Salvaged Robots" add. It is expected since these professions are "added" and have nothing to do with scenario specific profession selection. 
Also, with only "Dark Days Ahead" enabled it works as expected.

In the High Tech Low Life Scenario with "Classes and Scenarios Mod" enabled, all professions are allowed, even professions like "elementary student". It seems weird that these professions are allowed in shaddy and probably illegal offices. The scenario flavor text says it all. The scenario should have only a specific selection of professions like befor Build#9335.
With only "Dark Day Ahead" enabled it works as expected.

# Screenshots

In Build 9330 with all 3 Mods enabled:

High Tech, Low Life
![Build 9330 - High Tech low Life - All 3 Mods enabled](https://user-images.githubusercontent.com/52969927/61344392-61e92f00-a851-11e9-83f1-e4fd7d845c28.PNG)

Wilderness
![Build 9330 - Wilderness Scenario - All 3 Mods enabled](https://user-images.githubusercontent.com/52969927/61344393-61e92f00-a851-11e9-9fdc-a578ee6904ad.PNG)

In Build 9341 with all 3 Mods enabled:

High Tech, Low Life
![Build 9341 - High Tech low Life - All 3 Mods enabled](https://user-images.githubusercontent.com/52969927/61344394-61e92f00-a851-11e9-8f1d-eeb4c730392d.PNG)

Wilderness
![Build 9341 - Wilderness Scenario - All 3 Mods enabled](https://user-images.githubusercontent.com/52969927/61344396-6281c580-a851-11e9-8ecb-abdb70e3322d.PNG)

# Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3399961/debug.log)

 - OS: [Windows 10]
 - Game Version: [from the main menu, e.g. 0.D-5688-g896b189]
 - Graphics version: [Tiles - RetroDays]
 - Mods loaded: [Dark Days Ahead, Modular Turrets (dependency for S.R.), Salvaged Robots, More Survival Tools, Classes and Scenarios Mod]

Sry if this issue doesn't belong here, this is my first post so please redirect me if this is the case.

**Comment by ZhilkinSerg** [comment]
Probably need to change value of `add_professions` node in affected scenarios of affected mods.
