### ISSUE TITLE
Idea for mood changes and/or restrictions when installing CBMs 

### ISSUE THREAD

**Issue by Relyksboa** [CleverRaven/Cataclysm-DDA#32447]
Roleplay-wise installing CBMs should affect the character's mood, rather than the zero it currently does.

My idea for this is a mood bonus/malus for installing CBM's succesfully running off base dificulty for the installation

Alternative ideas include:
-not implementing this mechanic due to lack of gameplay need
-traits that augment the mood changes (E.G. transhumanists liking success more)
-restrictions on installing CBMs based on traits (body purists not installing cbms entirely)

**Comment by kevingranade** [comment]
No compelling need.
