### ISSUE TITLE
Enemies teleporting during aiming

### ISSUE THREAD

**Issue by Vzor-** [CleverRaven/Cataclysm-DDA#32443]
# Describe the bug
[Searingtown.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3399379/Searingtown.zip)
While playing I encountered a situation where enemies were seemingly teleporting into melee with me while I was aiming. 

# Steps To Reproduce

Besides this save file I have never seen the issue, I not do I know how to truly reproduce it.
To reproduce the behavior with the save:
1. Load the included save
2. Run away from enemies until a gap of 4-5 tiles is achived
3. Use '.' to aim a few times

***Edit, To reproduce this in a new game, run until low stamina and aim at an aggressed zombie.

# Expected behavior
Enemies should take incremental steps to approach, unless leaping occurs.

# Versions and configuration

Windows 10, vanilla version:Windows_x64-Tiles-9295

**Comment by baraba3** [comment]
happened several time to me mostly when stamina is low.

**Comment by kevingranade** [comment]
Low stamina? I wonder if it's triggering a wait for breath in there.

**Comment by Vzor-** [comment]
I can verify this is stamina related

**Comment by Zombiemanpig** [comment]
This is consistently happening to me when I do prison island start as a police officer using the pistol on all brutes, they will just time skip and bash me into a wall and if I press ignore pain then they once again time leap and bash me again.
