### ISSUE TITLE
Items in Cargo Dimension (Vehicle Additions Pack mod) should not add weight to vehicle

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#32449]
**Is your feature request related to a problem? Please describe.**  
It's some other dimension. It's logical that items inside of it should not add weight to vehicle. And it's already very rare item to find.

**Describe the solution you'd like**  
Items in Cargo Dimension (Vehicle Additions Pack mod) should not add weight to vehicle.

**Comment by TychaiosIlithios** [comment]
Two parts seen here - feature request and balancing
Feature's an idea to add container flags for weight reduction to game framework. 
No objections here - more json features = more fun modding.

Balancing is to make specific containers lighter and better.
Also no objections - closer to endgame where such containers happen to be without cheating, their weight does not matter much, but anyway no prob if someone mods a lighter container, others might as well mod a heavier one.
