### ISSUE TITLE
River tile valid for pathing in autotravel

### ISSUE THREAD

**Issue by Maddremor** [CleverRaven/Cataclysm-DDA#32446]
# Describe the bug

Current implementation of autotravel has a path to the destination calculated on the overmap. The character then navigates through the middle of every overmap tile in the path. Problem arises then the riverside overmap tile is included in the path, as it is mostly covered with deep water aside from a small strip of land. This causes the character to try to enter the river, causing the prompt to enter deep water to interrupt the journey.

# Steps To Reproduce

Attempt to travel with the path covering a river edge. Behaviour discovered when character overmap pathing preferred the riverside over adjacent swamp tiles.

# Expected behavior

Riverside overmap tiles are considered impassable for autotravel OR riverside tiles have special conditions for navigation.

# Screenshots

No screenshots now, but could be provided, should description not suffice.

# Versions and configuration

Cross complied from Linux to windows on 2019-07-16

# Additional context

I suspect (but have not confirmed) that the same issue would arise if autotravel attempted to path from a non-road land tile onto a bridge.

**Comment by Night-Pryanik** [comment]
Autotravel was overhauled recently. @Maddremor is this still an issue?

**Comment by I-am-Erk** [comment]
Closing as stale and unconfirmed
