### ISSUE TITLE
vehicle lights don't function

### ISSUE THREAD

**Issue by TJKing293** [CleverRaven/Cataclysm-DDA#32457]
# Describe the bug
vehicle lights don't work

# Steps To Reproduce

the ability to turn on lights from vehicle controls

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.C-33156-gd0fe67e
 - Graphics version: Tiles
 - Mods loaded:  "dda",
  "no_npc_food",
  "alt_map_key",
  "More_Survival_Tools",
  "boats",
  "no_mutagen",
  "no_religious_Texts",
  "No_Acid_Zombies",
  "No_Explosive_Zombies",
  "novitamins",
  "StatsThroughSkills",
  "no_reviving_zombies"

**Comment by ZhilkinSerg** [comment]
We do not accept bug reports for `0.C` after `0.D` is out. Please update to latest version and see if issue is still reproducible.
