### ISSUE TITLE
RM13 Combat Armor doesn't update player encumbrance when activated

### ISSUE THREAD

**Issue by daydreamer0000** [CleverRaven/Cataclysm-DDA#32459]
# Describe the bug

When wearing RM13 Combat Armor, player encumbrance doesn't update a turn after activating, only updating after the player wears/takes-off something else. This goes both ways, allowing the player to have low encumbrance when off, or high encumbrance when on.

Probably caused by the performance update that reduced updates to player/npc encumbrance. This may extend to other activated clothing such as  the riot helmet with facemask, or containers that change encumbrance when holding things like waterskins or magazine straps.

# Steps To Reproduce

1. Wear RM13 Combat Armor, note encumbrance.
2. Activate armor, wait a turn, note encumbrance hasn't updated.
3. Wear/take-off some other item, note encumbrance has updated.
4. Activate armor, wait a turn, note encumbrance hasn't updated.

# Expected behavior

When the armor is activated, encumbrance updates immediately or one turn later.

In previous versions, it would update one turn later either because encumbrance was updated at the end/beginning of every turn, or to stop the player abusing the armor by activating it for less than one turn, gaining its benefits without using fuel cells.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5683-gcd6579b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable Religious Texts [no_religious_Texts],
    No Survivor Armor [no_survivor_armor],
    No Fungal Monsters [No_Fungi],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by Amoebka** [comment]
This also happens with normal power armours, by the way.

**Comment by KaillSlater** [comment]
I can confirm that this is occurring with RM13 combat armor on my game, build 9346.  I found this issue report because I independently encountered this issue.

**Comment by KaillSlater** [comment]
I would also note that it appears to update the encumbrance when z-levels are traversed.

**Comment by berangus** [comment]
> 
> 
> I would also note that it appears to update the encumbrance when z-levels are traversed.

It also appears to update encumbrance when you toggle a bionic on or off.
