### ISSUE TITLE
Metal as Natural Resource, Iron Bog

### ISSUE THREAD

**Issue by floodie24** [CleverRaven/Cataclysm-DDA#32450]
i think the game is lacking a natural resource of metal, especially for wilderness play, and is not unrealistic at all:

Dig Shallow pit in swamps to get Bog Iron

![image](https://user-images.githubusercontent.com/52832089/61372831-6b49ba00-a898-11e9-938e-390e5988d6ce.png)

Process Bog iron in Bloomery Furnace to

![image](https://user-images.githubusercontent.com/52832089/61372794-55d49000-a898-11e9-8f20-0d409207dc5f.png)

Wiki reseouce : 
https://en.wikipedia.org/wiki/Bog_iron
https://en.wikipedia.org/wiki/Bloomery

New Resource to be added : Bog Iron, from shallow pit in swamp
New Construction: Bloomery, made of clay
Process Bog iron in Bloomery fueled with charcoal to get scrap metal

**Comment by bandti45** [comment]
Although I would really enjoy this being added, I must say that the industrial-grade steel that is made these days is grades above what someone could do in an apocalypse. but being able to make budget steel would be nice

**Comment by anothersimulacrum** [comment]
This will probably be only of use to players playing 'inna-woods' games, who don't have access to civilization. For players with access to civilization, it will be far quicker to just break down something to get metal.

**Comment by Throwaway-name** [comment]
If DangerNoodle weren't banned before their [mining mod](https://github.com/CleverRaven/Cataclysm-DDA/pull/18459) merged, this would be easier to add. Their updated mod has a spawn location for bog iron [here](https://github.com/DangerNoodle/mining-mod/blob/5633fda8b895a41500075111b19ec4140a779b80/Mining_Mod/mapgen_surface.json#L1)

**Comment by floodie24** [comment]
yeah the point for this is exactly for the "inna-woods' games, where right now you are cut off from way too many things CDDA has to offer.

**Comment by kevingranade** [comment]
@Throwaway-name don't interject unrelated commentary into issues.

**Comment by Inglonias** [comment]
I personally do not play innawoods, but this sounds like an excellent addition.

**Comment by kevingranade** [comment]
A quick look at [wikipedia](https://en.wikipedia.org/wiki/Bog_iron#Colonial_North_America) indicates that the readily available supplies of big iron in New England are exhausted.
I'm also sceptical about yields, how much bog do you need to dig through to get how much ore to get how much iron?

I can see this being worthwhile for a dedicated innawoods mod, but if one doesn't exist it doesn't seem worthwhile based on my current understanding of yields and process.

**Comment by jeremyshannon** [comment]
From what I've read on the subject, it was done for centuries in early Medieval Englad, mostly by poor people and it was mostly viable because mined iron was not always available. You'd have some poor serf walk around barefoot in waist-deep cold, muddy water, feeling with his toes for the little beads of iron that well up out of the ground, and by the end of the day, he'd have maybe a small handful of iron. Like half a "Chunk of Steel" in CDDA terms. You could probably make nails with it, but you're not building a deathmobile out of bog iron.

**Comment by floodie24** [comment]
yeah the amounts given should be fairly low, only interesting for a innawoods character to go for, and the purpose should not be to build a deathmobile, but to be able to get somewhat decent weapons and maybe armor

**Comment by kevingranade** [comment]
> somewhat decent weapons and maybe armor.

Bog iron is not a path to weapons and armor, more like a few metal tools and nails.

**Comment by floodie24** [comment]
the result should be a great deal more than that.
If you look at the bog harvest link i shared earlier you can see the great quantities they pull out of a relative small area.
and : "Bog ores are very easily converted into iron, and when they can be procured to mix with other kinds of ore, they produce a very beneficial effect, both in the running of the furnace and in the quality of the iron. For these reasons, as also for the cheapness with which they are obtained, it is an object to have them at hand, though they seldom yield more than 30 to 35 per cent. of cast iron."
quoted from : https://en.wikisource.org/wiki/The_American_Cyclop%C3%A6dia_(1879)/Bog_Ore

**Comment by kevingranade** [comment]
> The pig metal obtained from it, called cold short, is so brittle that it breaks to pieces by falling upon the hard ground;

I.e. unless you have other inputs, it's wortless.

Also I'd like a source a *little* more recent than 140 years old...

**Comment by kevingranade** [comment]
Here's some...
https://www.reddit.com/r/AskHistorians/comments/8y6u5g/how_iron_mining_differed_from_bog_iron_harvesting/

"Medieval English mining appears to have averaged about 15-20kg of ore extracted per working day per miner (refs 1,2).

Based on modern experimental archaeology, it's possible to collect 10kg of bog iron in an hour. Carrying the ore can be a larger part of the labour involved than the actual harvesting of the bog iron."
If we're talking just extraction, including short distances of walking.

**Comment by floodie24** [comment]
10 kg ore pr hour sounds reasonable with that ending up being about 3 kg / 60 units of scrap metal ?
I think that is a decent amount to make it usable for a 'innawoods' scenario or that Challenge where just just need that bit of iron to get out of a situation

**Comment by kasanryukin** [comment]
Some friends of mine smelt iron from bog or surface discards monthly. 150lbs of ore yields on average 8-10lbs of meidium to high carbon steel using a bloomery and around 200lbs of hard wood charcoal. Process takes (not including making the charcoal and if needing it, crushing the ore into small pieces the size of an american dime) roughly 9 hours and has to be manually tended to. The bloom as its called then requires around 30 minutes of heavy hammer work to initially compress it while it's still near molten.  Most blooms are cut in half during this process to make workable sized pieces.

**Comment by danielkwinsor** [comment]
I would like to request this re-opened, as I am playing what you guys seem to call innawoods.  Skipping personal details, I'd really like this and maybe others would as well.  Also: besides bog iron, there appear to be real iron veins that were mined in NE.  So far, this is the best resource I've found on the matter: https://www.vtarchaeology.org/wp-content/uploads/200_years_ch3_optimized.pdf

**Comment by anothersimulacrum** [comment]
This issue is still valid, but unless you're going to actively work on it, it's pointless to re-open it - it'll just be closed again in 60 days.

**Comment by kevingranade** [comment]
The stalebot process is specifically set up such that it makes stale issues, as opposed to invalid issues, easy to find in case someone is looking for something to add.

Having said that, I've been looking into this issue, and upon further review it very much looks like a chain of bog iron to wrought iron to steel should be *possible* but not *practical*.

Bog iron harvesting is reasonable, constructing a bloomery from memory seems reasonable, working sponge iron to (useful) wrought iron seems reasonable, but the next step of transforming wrought iron to steel from memory does not seem remotely reasonable for someone who wasn't a steel worker or chemist before the cataclysm.

**Comment by kasanryukin** [comment]
Steel is regularly made by hobbyists all over the world using bloomery
furnaces. The pure act of melting big iron or crushed iron ore creates
medium to high carbon steel due to impregnation of carbon during the
refining process. I could link you to dozens of scholarly papers written by
these ametures about their successes and failures as well as videos (one
even of me doing it), groups dedicated to the art, and reenactment
societies that preserve the method.

Yes it's steel and we make everything from tools to weapons from it, but no
it isn't the same quality as blast furnace steel coming from a mill.

**Comment by Vzor-** [comment]
When I watch videos of this online, trial and error seems to be the main theme in iron smiting. This could be a good use for the proficiency system. We could make an iron smelting and a steel fining proficiency. Give it a low time multiplier but a giant failure multiplier. 

I'm not making any statements on the feasibility of steel-making though.
