### ISSUE TITLE
Unending fire with z-levels enabled.

### ISSUE THREAD

**Issue by BevapDin** [CleverRaven/Cataclysm-DDA#32452]
# Describe the bug

With z-levels enables fires spread to the above, but they also fall down.

See "src/map_field.cpp" for processing of fire.

There is one section that makes it fall down, which can create a raging (level 3) fire below.

There is also a section (only used with zlevels enabled) that makes the fire go up. And that section unconditionally decreases the age of the fire above, and does not change the fire below, effectively creating fire out of nothing.

And that probably leads to infinite fire.

# Steps To Reproduce

Try it out: on an open field, nothing but air above z-level 0, create a single raging fire field. Wait an hour or so and see it has risen up to a tower of raging fire.

# Expected behavior

Fire should eventually burn out. Fire spreading should result in same total "amount" of fire on the map. Fire consuming stuff (items/terrain/...) should be separate and should increase/decrease the "amount" of fire. (Note sure how we can measure "amount" of fire.)

**Comment by Night-Pryanik** [comment]
Same as #32378?

**Comment by BevapDin** [comment]
> Same as #32378?

There could be a connection, but when I burned down houses, the remaining fires where all above z-level 0. The ground floor (where the house used to be) was free of fire and only some shadowy areas (shadow from the smoke above) remained.

So the house **did** stop burning down.

**Comment by free-coffee** [comment]
I don't know where the z-levels play a role, but this part in map_field.cpp/1000-1022 seems like it resets fires to 3 intensity once they reach 0?:
```
if( curtype == fd_fire_vent ) {
       if( cur.get_field_intensity() > 1 ) {
                if( one_in( 3 ) ) {
                       cur.set_field_intensity( cur.get_field_intensity() - 1 );
                 }...
       } else { ...
                  add_field( p, fd_flame_burst, 3, cur.get_field_age() );
                  cur.set_field_intensity( 0 );
       }
 }
if( curtype == fd_flame_burst ) {
       if( cur.get_field_intensity() > 1 ) {
                cur.set_field_intensity( cur.get_field_intensity() - 1 ); ...
        } else {...
                 add_field( p, fd_fire_vent, 3, cur.get_field_age() );
                 cur.set_field_intensity( 0 );
        }
}
```
If it starts out as a fire-vent it'll change -> burst(3) -> vent(3) within this block as well.

**Comment by free-coffee** [comment]
This should be closed, but the pull-request didn't have the keyword fix at the time.

**Comment by free-coffee** [comment]
Hey @BevapDin i think this and #34171 should be resolved. I forgot to use the fix keyword on the merged fix im sorry.
