### ISSUE TITLE
Impossible to pry a door using fire axe

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32455]
# Describe the bug

Even though it `Has level 3 prying quality.`

[2019.07.17-2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3402867/2019.07.17-2.zip)

0.D-5688-g896b189257-dirty

**Comment by TRScheel** [comment]
![cataclysm-tiles_2019-07-20_16-56-54](https://user-images.githubusercontent.com/846738/61584571-8d00a680-ab0f-11e9-865a-49083e07080d.png)

I couldn't reproduce this.

**Comment by Night-Pryanik** [comment]
There isn't an option to pry by activating it, but it is possible by examining the tile.

**Comment by l29ah** [comment]
Nah it still doesn't work by examining the door in the attached save file.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Nah it still doesn't work by examining the door in the attached save file.

![image](https://user-images.githubusercontent.com/16213433/61590459-65b6e180-abc2-11e9-9d0e-e7524969ecc3.png)

**Comment by l29ah** [comment]
Ouch.
