### ISSUE TITLE
Spilled Liquids evaporate/dry up, However they do not Clear themselves when at 0 portions

### ISSUE THREAD

**Issue by jasonmbrown** [CleverRaven/Cataclysm-DDA#32469]
# Describe the bug
Advanced Inventory management crashes when moving spilled liquids with 0 portions

# Steps To Reproduce

 1) Spill some water (1 or 2 Portions) on ground, (I am not sure if other liquids cause this).
 2) Wait in game a few days Till water dries up
 3) Use Advanced inventory management on the water and try to move it
 4) Game Crashes Here (Regular Get or Examine Does not crash and just removes the water)

# Expected behavior
Spilled Liquids should clear themselves upon reaching 0 portions rather then staying on a tile.

# Versions and configuration
    OS: Windows 7 64bit Home Premium
    Game Version: 0.D-5703-g850f19c (I Think). Build #9344
    Graphics version: Tiles
    Mods loaded: "dda", "no_npc_food", "makeshift", "More_Survival_Tools", "mutant_npcs", "hydroponics", "more_locations", "cityside", "FujiStruct", "Urban_Development", "deoxymod", "blazemod", "Tanks", "safeautodoc", "novitamins", "stats_through_kills", "alt_map_key"

# Additional context

PS: I apologize I don't have a save that causes this, It should be fairly quick to setup though (Then Just in game waiting for a few days). If its absolutely needed I will make one and add it later. Also I will obtain a crash log at that time If required (I had 2 crashes happen and don't know which one the log I have is for).

**Comment by ipcyborg** [comment]
It looks like the save is really required.
I have not found anything about water evaporation or drying in the code yet. 

Tried to reproduce this behavior as stated above, but failed. After a season of waiting (summer, outside) still have "1 water (dirty)" on the ground. Also tried to advance game turns, change seasons, etc. Still no luck.

**Comment by OliveChukar** [comment]
Tested in ver 0.E-9111-gd1e702b-dirty. Spilled water on ground outside then waited for ten days. Water did not change amount did not decrease. Burned 1000 units of coal one tile from water again no change. Attempted  to move water with advanced inventory manager but just got a message saying spilled liquids cannot be moved try mopping it up instead.

**Comment by int-ua** [comment]
@jasonmbrown please comment if this issue is still relevant and I'll reopen
