### ISSUE TITLE
Manual CBM Install lacks confirmation/success chance

### ISSUE THREAD

**Issue by AndrasZodon** [CleverRaven/Cataclysm-DDA#32462]
# Describe the bug

When activating CBMs to perform a manual installation, the installation happens instantly without prompting you to confirm, or giving chances of success.

# Steps To Reproduce

1. Navigate to CBM in inventory or use 'a'ctivate
2. Activate the CBM.

# Expected behavior

Manual Installation should prompt a confirmation before proceeding, and should give at least an estimate of success. Why: This is how it worked previously, and how it works currently with the autodoc.

# Screenshots

https://i.imgur.com/gGB7qGE.png
https://i.imgur.com/4iphb24.png

Can't show that something doesn't exist in a screenshot, but Activating the CBM causes the log events seen in second screen

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version   ((Windows 7))
- Game Version: 0.D-5599-gfd556e6 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Fast Healing [fast_healing],
    Hydroponics [hydroponics],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classic Roguelike Classes [RL_Classes],
    **Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],**
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

Character is a mod-added profession (C.R.I.T. Night-Walker) with numerous traits/mutations, and zero bionics, in a lab start. The last 5 mods on the list (including Manual Installtion andSafe Autodoc) were added post world-gen. Doing so threw a few errors at me, but otherwise the game seems to perform as expected.

**Comment by kevingranade** [comment]
Why do you need a chance of success and confirmation if you have safe installation enabled?

**Comment by Fris0uman** [comment]
Caused by #31763, where most prompt were moved to the menu, but the installation menu only appear for the surgeon and the autodoc.

**Comment by I-am-Erk** [comment]
This is the result of running mods that intentionally backtrack to features that were changed months (years?) ago. I don't think we can keep up bug maintenance on that sort of thing for obvious reasons.

**Comment by AndrasZodon** [comment]
> Why do you need a chance of success and confirmation if you have safe installation enabled?

Manual Installation =/= Safe Autodoc
