### ISSUE TITLE
glass roof or skylight for solar panels

### ISSUE THREAD

**Issue by TJKing293** [CleverRaven/Cataclysm-DDA#32460]
nuff said

**Comment by l29ah** [comment]
what

**Comment by I-am-Erk** [comment]
It really isn't.

**Comment by TJKing293** [comment]
sorry, it's supposed to be a feature suggestion

**Comment by l29ah** [comment]
what
https://github.com/CleverRaven/Cataclysm-DDA/issues/7409

**Comment by TJKing293** [comment]
for buildings

**Comment by I-am-Erk** [comment]
When you clicked "new issue", there was a big template asking you a bunch of questions about your suggestion. We generally require at least most of that information. We don't have any clear idea what you're suggesting here.

Take a look at any other suggestion post for examples.
