### ISSUE TITLE
Kiting broken by z-level sound and smashing?

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#32471]
I've experienced this on multiple sessions recently.

Frequently in a lab start, you'll encounter a large group of blobs, and in order to thin the numbers, you may want to kite them somewhere with turrets or lasers. Lately I can't. It's not that it's difficult, I simply cannot.

What will happen is I'll get their aggro, move a step away and either they'll go back to ignoring or follow for 3-4 turns then without stopping, move back all the spaces they came.

If I gain aggro and go behind them then they constantly "attack" as they try to move back to original position, but if I move out of the way they return to starting area. I think z level sounds play a big part in this. My guess is they move towards a louder sound than me hitting them?

The inability to kite monsters as of late, and their propensity to "smash" floors has made early game VERY tedious on occasion. With me having to take 20-30 turns to move some mob 6 spaces as it takes the opportunity to smash the ground in front of me 4-5 times before moving. I think my current record was 7 consecutive ground pounds before movement.

**Comment by RDru** [comment]
Blobs were always pursuing their enemies (you) only if they were very close. I thought that this is intended since they are blobs, they don't have eyes or ears. As for zombies they go to nearest enemy they can see. If they can't see enemy they go to sound sources if they hear them. I write that from my observations, not from code knowledge.

**Comment by glenmack** [comment]
> Blobs were always pursuing their enemies (you) only if they were very close. I thought that this is intended since they are blobs, they don't have eyes or ears. As for zombies they go to nearest enemy they can see. If they can't see enemy they go to sound sources if they hear them. This is from my observations, not from code knowledge.

The behavior i'm describing with the blobs is happening with 1 tile of space between myself and the blobs. If they can't track an enemy at 1m they basically can't track at all, I've also tried smashing the ground in front of them to make sound for them to track, but in the cases I describe, they ignore this too.

As for zombies, again I'm talking about zombies above ground in daylight, one space away, hitting the ground one step away.

**Comment by kevingranade** [comment]
Needs re-confirmation, the ground smashing thing was adjusted by #35045

**Comment by ElonSatoshi** [comment]
I'd like to try to re-confirm this, can I have some steps to reproduce? @glenmack

**Comment by kevingranade** [comment]
I interacted with both blobs above a slime pit and blobs in a lab, in both cases they chased me around quite a bit with very little effort on my part.  This was in a lab where things were in fact being noisy both above and below the blob area.
