### ISSUE TITLE
Electric forge

### ISSUE THREAD

**Issue by bluewolf194** [CleverRaven/Cataclysm-DDA#32476]
Describe the bug
It would let me continue crafing an electric forge.

 Steps To Reproduce

1. Make an Electric forge without enough charges in welder.
2. Try to continue.

Expected behavior
when every to try to contunue crafting it ask what tool i want to use but it ask what tool i want to use so i select my welder what it dosent continue.

Versions and configuration

 - OS: Windows 10 
 - Game Version: 0.D-5707-g7fa6897 [64-bit]
 - Graphics version: Tiles
 - Mods loaded:
    Dark Days Ahead [dda],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    No Acid Zombies [No_Acid_Zombies],
    No Explosive Zombies [No_Explosive_Zombies],
    No Fungal Monsters [No_Fungi],
    StatsThroughSkills [StatsThroughSkills],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Urban Development [Urban_Development],
    Boats [boats],
    Craftable Gun Pack [craftgp],
    Safe Autodoc [safeautodoc],
    Folding Parts pack [deoxymod],
    Makeshift Items Mod [makeshift],
    Manual Bionic Installation [manualbionicinstall],
    Disable NPC Needs [no_npc_food],
    Prevent Zombie Revivication [no_reviving_zombies],
    Simplified Nutrition [novitamins],
    More Locations [more_locations],
    Magiclysm [magiclysm],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    Arcana and Magic Items [Arcana],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Gun Cotton [guncotton],
    Garden Pots [growable-pots],
    Bootleg Walkers [Bootleg_Walkers],
    Bens GF recipes [Tolerate_This],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Mundane Zombies [Mundane_Zombies],
    No Big Zombies [No_Big_Zombies],
    Classes and Scenarios Mod [more_classes_scenarios],
    No Filthy Clothing [no_filthy_clothing],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Sleep Deprivation [sleepdeprivation]

*Additional context

ERROR : (error message will follow backtrace)
	(@0x5ad52e[cataclysm-tiles.exe+0x1ad52e]), 
	(@0x5adb5a[cataclysm-tiles.exe+0x1adb5a]), 
	(@0x5b0f36[cataclysm-tiles.exe+0x1b0f36]), 
	(IMG_LoadWEBP_RW+0x111023@0x1120ef3[cataclysm-tiles.exe+0xd20ef3]), 
	(@0x781e62[cataclysm-tiles.exe+0x381e62]), 
	(@0x800f19[cataclysm-tiles.exe+0x400f19]), 
	(IMG_LoadWEBP_RW+0x2de751@0x12ee621[cataclysm-tiles.exe+0xeee621]), 
	(@0x7e37f6[cataclysm-tiles.exe+0x3e37f6]), 
	(@0xc38a5d[cataclysm-tiles.exe+0x838a5d]), 
	(@0xc4b36e[cataclysm-tiles.exe+0x84b36e]), 
	(@0xc4b62a[cataclysm-tiles.exe+0x84b62a]), 
	(@0xc4b949[cataclysm-tiles.exe+0x84b949]), 
	(@0x67683b[cataclysm-tiles.exe+0x27683b]), 
	(@0x6aaf2f[cataclysm-tiles.exe+0x2aaf2f]), 
	(@0x6c7f98[cataclysm-tiles.exe+0x2c7f98]), 
	(@0x6db621[cataclysm-tiles.exe+0x2db621]), 
	(@0x6b92a7[cataclysm-tiles.exe+0x2b92a7]), 
	(IMG_LoadWEBP_RW+0x566848@0x1576718[cataclysm-tiles.exe+0x1176718]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0x14@0x7ffdf47f7974[KERNEL32.DLL+0x17974]), 
	(RtlUserThreadStart+0x21@0x7ffdf761a271[ntdll.dll+0x6a271]), 
Backtrace emission took 0 seconds.
src/item.cpp:8690 [const recipe& item::get_making() const] 'The Bowyer's Buddy' is not a craft or has a null recipe

**Comment by bluewolf194** [comment]
Iv found out you have to k

**Comment by bluewolf194** [comment]
I'v found out that if you hold the button down to select the tool you want to use it will craft it.

**Comment by misterprimus** [comment]
I had this happen to me in a totally unmodded game in case anyone is interested. Same symptoms re: holding down the button to continue crafting.

**Comment by tinukedaya** [comment]
Happened to me as well when I had both welder and acetylene torch around. It felt like it was asking me every turn which of those two to use. Holding the button progressed VERY slowly thru the craft. When I brought the acetylene torch out of the crafting distance all worked nice.

**Comment by RogueYun** [comment]
Just had this happen to me as well, thanks for the tip about holding down the button.

**Comment by ZhilkinSerg** [comment]
Should've been fixed with #32607.
