### ISSUE TITLE
Temperature tags/statuses for clothes

### ISSUE THREAD

**Issue by Redbox12236** [CleverRaven/Cataclysm-DDA#32478]
**Is your feature request related to a problem? Please describe.**  
Currently a player can just wear lots of clothes and feel comfortable or warm indefinitely without any source of heat, which is not realistic, because in real life clothes only insulate and delay freezing, they don't produce warmth ( except for heated clothes ).

**Describe the solution you'd like**  
Clothes should have temperature statuses, just like the ones that consumable items have.  
These statuses will gradually change depending on the ambient temperature and affect the amount of "warmth" the clothes provide( e.g. 'warm' status will increase warmth by 50% i.e. if winter boots initially have 80 points of warmth, then with 'warm' status they will provide 120 points of warmth , 'cold' will decrease it by 50%, 'frozen' will decrease warmth by 100% ). The numbers will probably require some balancing and there should probably be more substatuses.

This change will make players more dependant on fires, electric thermal clothes and other portable heat sources.

**Describe alternatives you've considered**  
Alternatively, instead of clothes, body parts' temperature can slowly move towards the ambient temperature. 
Additionally, 'wet' status can be applied to specific clothes instead of being as the character's morale status

**Comment by TechyBen** [comment]
The body produces heat.

**Comment by Redbox12236** [comment]
> The body produces heat. But yes, to some extent some temperatures are not manageable by all types of clothing.

Oh, you're right. I completly forgot about this body function.
