### ISSUE TITLE
NPC needs bugged

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#32474]
# Describe the bug
Npcs needs are not active,thez dont get thirsty,hungry or tired.

# Steps To Reproduce

1. Sttart game
2. Recurit npc 
3. Wait and see thath his needs are irrelevant as he is always content.

# Expected behavior
Npc shoudl get hungry thirsty and tired

# Screenshots
http://prntscr.com/ogr4rj
day 2 needs of startign npc-same as on day one http://prntscr.com/ogr4rj

# Versions and configuration
last version 9346.npc needs disabled is disabled.

**Comment by BBlankie** [comment]
You might have the "Disable NPC Needs" mod on your world, it is turned on by default.

**Comment by baraba3** [comment]
nah its off.
i am not only one though
https://www.reddit.com/r/cataclysmdda/comments/ceqcyv/is_npc_hunger_and_thirst_bugged/

Are your npc ok regarding this ?do they normallz experince hunger,thirst or fatigue with last version of the game?
