### ISSUE TITLE
Show required components for modifying clothing

### ISSUE THREAD

**Issue by TannHaals** [CleverRaven/Cataclysm-DDA#32473]
Currently, we have no idea how many crafting components a certain clothing modification will consume, nor how many components we are lacking in the event we cannot perform the modification.

Suggestion: Add a part stating the number of components required in the clothing modification screen, i.e. "Pad with leather (Bash/Cut: x/x -> y/y, Encumbrance: a -> b; **needs X leather patches**)". Alternatively, just "Pad with **X leather patches** (...)" can work too.

**Comment by Petethegoat** [comment]
This is resolved now. Clothing mod UI shows how many items will be used.
