### ISSUE TITLE
Smoking fruits/vegetables doesn't reflect calories of input

### ISSUE THREAD

**Issue by TannHaals** [CleverRaven/Cataclysm-DDA#32477]
Dehydrated fruits and vegetables made with a dehydrator through the crafting menu have calorie values based on their inputs. However, processing the same fruits and vegetables with a smoking rack results in a standard dehydrated fruit/vegetable item which ignores the calorie value of the input.

Crafting dehydrated fruit using blueberries (89 kcal) and grapes (165 kcal) resulted in two sets of dehydrated fruit of 86 kcal and 165 kcal respectively. However, using a smoking rack to process the same fruits resulted in a single dehydrated fruit type with 100 kcal, when it should follow the values that the crafted version produces.

**Comment by TannHaals** [comment]
Related issue: crafting dehydrated vegetables with the crafting menu doubles the portions, i.e. 1x plant marrow (34 kcal) -> 2x dehydrated vegetables (17 kcal). On the other hand, smoking the same vegetable results in a 1:1 ratio of input to output, that is, 1x plant marrow (34 kcal) -> 1x dehydrated vegetables (34 kcal).

**Comment by DaviBones** [comment]
Fixed by #35267.
