### ISSUE TITLE
Hobo Stove Can Cook

### ISSUE THREAD

**Issue by roaringjohn** [CleverRaven/Cataclysm-DDA#32489]
**Is your feature request related to a problem? Please describe.**  
Hearing that hobo stoves can't cook in-game absolutely baffles me.

**Describe the solution you'd like**  
Make hobo stoves capable of cooking, even for smaller hobo stoves in the future (12 oz cans can cook too, you know! I could literally find a video and link it here to show they can!).

**Additional context**  
The hobo stove in the game currently is 1.5 L, which is a pretty damn huge hobo stove. It would most certainly produce a flame large enough to cook, especially since it can boil water. A 12 oz can can also produce a much larger flame than a lighter, as far as I know, even if only using tinder as fuel. There is no reason for it to be incapable of cooking food, especially if it can boil water.

Now, tinder should not be the only thing used for hobo stoves. Any liquid fuel should be possible, too. This last part can probably be done via a possible action to change the fuel it accepts, from what I've heard in discord. This will actually work, from what I've seen.

Videos of larger stoves:
[https://www.youtube.com/watch?v=x5UJjMiWxP0](url)
[https://www.youtube.com/watch?v=T08vmOl4hKQ](url)

Videos of smaller stoves:
[https://www.youtube.com/watch?v=2989imUHVtk](url) (boiling, sure, and not exactly a hobo stove, but still cooking food with just tinder)

**Comment by mdb45424** [comment]
at this point the hobostove is bascially useless

**Comment by CelestineSrS04** [comment]
The Hobostove in its current state is completely unrealistic, unreliable and only exists to create difficulty for the sake of difficulty. The prior hobostove was able to to perform the same functions as its real life counter part (Boiling water and cooking) made from far smaller cans and materials. 

The new hobostove should be reverted back to its original functions to actually make it a useful and realistic item within the game that serves an actual purpose early game.
