### ISSUE TITLE
Heat dependent mutation debuff doesn't match description

### ISSUE THREAD

**Issue by itsjustme3** [CleverRaven/Cataclysm-DDA#32485]
# Describe the bug

The heat dependent mutation description says -1% speed for every 5 levels below 65F. Currently a temperature of 25F produces a -40% debuff to speed. I debug mutated to Very Heat Dependent, and Cold Blooded and they were -12% and -20% respectively.

The JSON for COLDBLOOD has a temperature speed modifier of 1... It should probably be 0.2 when compared to the others. See below.

# Steps To Reproduce

1. Create a character with the Heat Dependent mutation.
2. Checks its speed.

# Expected behavior
Heat Dependent debuff description and actual debuff should match, preferably would be a smaller debuff than Very Heat Dependent and Cold Blooded.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-5714-gb644148 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],

**Comment by bandti45** [comment]
Do make sure you keep your clothing in the equation, being heat dependent would make it less helpful but it would still help keep you warm, even though it would more slow heat change in real life

**Comment by itsjustme3** [comment]
Yes. Clothes don't seem to make a difference. I tried it naked to make sure there wasn't some encumbrance effect calculated in that I wasn't aware of. I also debugged in all three levels of the mutation, and Heat Dependent's debuff is worse than Very Heat Dependent, and Cold Blooded.

**Comment by ZhilkinSerg** [comment]
Values were jsonized changed in #31707. Below are previous and current algorithms:

![image](https://user-images.githubusercontent.com/16213433/61514818-9d2e5e00-aa09-11e9-9c82-a977824b2707.png)

Previously `COLDBLOOD`, `COLDBLOOD2`, `COLODBLOOD3` and `COLDBLOOD4` gave penalties when player temperature was below 65F (speed was modified by 1/5, 1/3, 1/2 and 1/2 respectively). `COLDBLOOD4` also gave 1/2 bonus if player temperature was above 65F.

Current formulas are the same, but new temeperature modifiers in json are:

![image](https://user-images.githubusercontent.com/16213433/61515140-8e947680-aa0a-11e9-97e5-895af766654d.png)

So, yes `temperature_speed_modifier` for `COLDBLOOD` should be changed from 1 to 0.2 (or 1/5) to give previous results.
