### ISSUE TITLE
Spraycan Flamethrower can't be reloaded.

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#32484]
# Describe the bug

Spraycan Flamethrower can't be reloaded with neither gasoline nor diesel.

# Steps To Reproduce

1. Craft Spraycan Flamethrower.
2. Try to reload while having access to relevant ammo.
3. The ammo is not recognized.

# Expected behavior

Spraycan Flamethrower can be reloaded with gasoline or diesel.

# Screenshots

![Untitled](https://user-images.githubusercontent.com/45204409/61494766-5adc3100-a9b7-11e9-86ef-8383366bdf65.png)

# Versions and configuration

 - OS: [Windows 10]
 - Game Version: [0.D-5707-g7fa6897]
 - Graphics version: [Tiles]
 - Mods loaded: [Cataclysm Dark Days Ahead] (I checked the behavior of the bug in a debug world with nothing but this enabled)

**Comment by Rivet-the-Zombie** [comment]
For some reason the flamethrower handmade from scrap and garbage only accepts military grade napalm as fuel. It really ought to be using gasoline/diesel/lamp oil instead.

**Comment by Contemplator11** [comment]
Oh. I encountered the same bug, but thought it is a feature.

**Comment by floodie24** [comment]
well i don't think it should be able to reload at all.
Unless you first implement the tools to pressurize gas and liquids into the container first.
It makes sense as it it, a disposable weapon put together with a spray can, lighter and duct tape

**Comment by Rail-Runner** [comment]
Well, to start with, I think it should use actual spray cans as magazines, instead of being reloadable with gasoline.

**Comment by DemAvalon** [comment]
The simple flamethrower also won't accept gasoline or diesel as ammo.

**Comment by Leland** [comment]
Spraycan flamethrower was removed entirely in #33182, closing.

@DemAvalon, I imagine the same PR, which focused on flamethrower fuel in general, addressed your note too. Feel free to test and create a new issue if it's still around 😊
