### ISSUE TITLE
Advanced scenarios don't advance zombie evolutions

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#32480]
# Describe the bug

Sheltered and Next Summer scenarios don't advance zombie evolution like they used to.

# Steps To Reproduce

1. Make a character using Sheltered or Next Summer scenario.
2. Teleport to a city.
3. See unevolved zombies.

# Expected behavior

Scenarios advance the starting day, not the day of the Cataclysm. Zombies are evolved, like they used to be.

# Versions and configuration

 - OS: win10
 - Game Version: 0.D-5703-g850f19c
 - Graphics version: tiles
 - Mods loaded: none

# Additional context

Probably has something to do with either the scenario rework, or that band-aid fix for evolution advancing when changing the starting date. The scenario rework explicitly stated the two scenarios were supposed to stay the same as before.

**Comment by Bulletfang** [comment]
Coincidentally, changing the day of the cataclysm during world generation gives advanced evolution zombies :/

**Comment by Leland** [comment]
Not stale, seems like a bug worth fixing

**Comment by ipcyborg** [comment]
Can't reproduce in 0.D-8234-gfd911084b2
The zombie's evolution using "Next Summer scenario" is approximately the same, as just starting with "Play Now! (Fixed Scenario)" and then advancing time +1 year using debug menu.

**Comment by davidpwbrown** [comment]
can't reproduce, setting zombie evolution to fastest, and using next summer scenario, produces an amount of advanced zombies.
Was expecting more hulks and juggernauts, but still it is very noticeable, lots of wrestlers and predators and other "red" zombie names
