### ISSUE TITLE
Freed cyborg moved while under anesthetic coma

### ISSUE THREAD

**Issue by archigo** [CleverRaven/Cataclysm-DDA#32497]
# Describe the bug

After freeing and recruiting a prototype cyborg in a lab, i started to remove some CMB's from my new follower. I then went on to explore a bit while the coma wears off.

When i came back i discovered the follower was gone. I went to the map and saw the follower had left the lab and moved north. Chasing after the follower in a car i chased them down and found them in the middle of nowhere, still sleeping in a coma.

# Steps To Reproduce

1. put npc in autodoc induced coma
2. walk away
3. watch them move through the out of reality bubble movement.

# Expected behavior

The npc should stay put while in a coma

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-5622-g3d4a952 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills],
    Prevent Zombie Revivication [no_reviving_zombies],
    Classes and Scenarios Mod [more_classes_scenarios],
    No Fungal Monsters [No_Fungi]
]

# Additional context

Save
https://mega.nz/#!JUk2XIDA!0ZZF1_APgzSgCXtkItZ3eOozJpPYs8krvqt7hl-Eq7g

**Comment by Fris0uman** [comment]
Since #31763 NPC under anesthesia are processed instead of being ignored by the game. Maybe it makes them move when they re out of the realiry bubble
