### ISSUE TITLE
Extinguish controlled fires

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#32492]
**Is your feature request related to a problem? Please describe.**  
With new firewood source location, automatic actions can cause extended use of fire when not needed, using fuel, or requiring a fire extinguisher or dumping precious water to put out.

**Describe the solution you'd like**  
Controlled fires in a brazier, oven or other crafted structure should be extinguishable, without water, or a fire extinguisher by smothering with wood ash or other simple methods. Perhaps gate it behind survival skill 1, or require 100 wood ash to be present or something, definitely limit it to controlled fires. Takes around 5 minutes.

**Additional context**  
Already burnt wood ash is frequently used in fireplaces to smother later fires, removing oxygen. Small controlled fires can easily be put out by spreading out burning embers cooling the fire quickly, it's certainly an acquired skill but not a very difficult one.

**Comment by floodie24** [comment]
I agree that any controlled fires should be easy to extinguish.
An alternative solution could be a simple examine option "stop fueling the fire" so it will stop taking more fuel from the firewood source location. 

Also how to put out a fire would depend on where the fire is.
like a wood stove would have the option to just close for air intake and quench the fire.
why not craft your brazier to brazier with lid for easy ways of putting out the fire
