### ISSUE TITLE
NPCs generated with invalid items

### ISSUE THREAD

**Issue by MattAmmann** [CleverRaven/Cataclysm-DDA#325]
The starter NPC left our shelter to attack a dog. She was wielding a non-active pipe bomb. When she went to attack, however, I received these messages:

```
DEBUG: Attmpted to access item -1 in an inventory (size 11)
DEBUG: NPC didn't use its moves. Action 17. Turning on debug mode.
DEBUG: NPC Gianna Wright: target = 1, danger = 13, range = 1
```

*spammed spacebar to clear messages* (the three messages looped ~6-10 times)

```
Gianna Wright's brain explodes!
```

I looted her body without taking anything (16 items), and sure enough, letter 'l' was a "none" with no description.

**Comment by qbradq** [comment]
NPC items are now taken from item groups defined in the NPC type JSON files at data/json/npcs/NC_*.json . Please close this issue.
