### ISSUE TITLE
Electric tools' energy drain is much higher than possible

### ISSUE THREAD

**Issue by BugReporterA** [CleverRaven/Cataclysm-DDA#32503]
# Describe the bug

Tools like electric jackhammer and electric chainsaw use more energy that even possible to store in batteries for a single use. Most likely related to the 6 to 1 sec update.

Electric jackhammer uses 3.5k energy per use, and electric chainsaw drains in one use.

# Steps To Reproduce

1. Spawn an electric jackhammer or electric chainsaw
2. Use it
3. Observe the energy drain

# Expected behavior

Electric tools' energy drain should be corrected to normal values.

"Additional context" 

# Versions and configuration

 - OS: 
Windows 10
 - Game Version:
0.D-5723-g6790e59
 - Graphics version: 
Tiles
 - Mods loaded:

  "dda",
  "no_npc_food",
  "growable-pots",
  "craftgp",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "fast_healing",
  "hydroponics",
  "national_guard_camp",
  "blazemod",
  "Tanks",
  "alt_map_key",
  "safeautodoc"

**Comment by ymber** [comment]
We're working on this. See #30656. Chainsaws were set to 2kW power draw in that PR which is pretty typical for an electric chainsaw. They currently take medium type batteries which are about 500kJ so they can only power a 2kW chainsaw for 250 seconds. High power tools like that should probably be using larger batteries.

**Comment by kevingranade** [comment]
> High power tools like that should probably be using larger batteries.

Or gasoline, is a high power electric chainsaw even a thing?

**Comment by ymber** [comment]
I got the 2kW number from looking up typical electric chainsaws you can buy. I've only ever seen gasoline chainsaws used but presumably electric ones can run for more than 250 seconds.

**Comment by Hirmuolio** [comment]
One thing to note is that you won't be running the tool at full power constantly when you use it to do work.

The first battery powered chainsaw from google advertised beng able to cut up to 600x 5-7.5 cm logs with 6 Ah battery. Not sure wether this kind of metric is common for chainsaws or if small logs are used because it is low powered.

**Comment by ampersand55** [comment]
> I got the 2kW number from looking up typical electric chainsaws you can buy. I've only ever seen gasoline chainsaws used but presumably electric ones can run for more than 250 seconds.

250 seconds sounds about accurate.

Some popular cordless chainsaws models compared, assuming 2kW power drain:

* DEWALT DCCS670X1 - 60V * 3Ah /  2kW = 324 seconds.
* BLACK+DECKER LCS1020 - 20V * 3Ah = 108 seconds.
* Makita XCU03PT1 - 36V * 5Ah / 2kW = 324 seconds.
* Greenworks 16-Inch - 40V * 4 Ah / 2kW = 288 seconds.
* Zombi ZCS5817 - 58V * 4Ah / 2kW = 418 seconds.

**Comment by Edgar-cy-Lee** [comment]
> * DEWALT DCCS670X1 - 60V * 3Ah /  2kW = 324 seconds.
> * BLACK+DECKER LCS1020 - 20V * 3Ah = 108 seconds.
> * Makita XCU03PT1 - 36V * 5Ah / 2kW = 324 seconds.
> * Greenworks 16-Inch - 40V * 4 Ah / 2kW = 288 seconds.
> * Zombi ZCS5817 - 58V * 4Ah / 2kW = 418 seconds.
So I read this part and considered if it was true. Most power tool batteries take at least good half to full hour to recharge and only allows use down to 2 minutes or so?

This is from the customer review from amazon.ca of BLACK+DECKER LCS1020, which should logically only last for 3 minutes tops using full battery.


![image](https://user-images.githubusercontent.com/8914956/61616232-ebc04000-ac35-11e9-9135-0f3651a02fd4.png)

![image](https://user-images.githubusercontent.com/8914956/61616191-d3502580-ac35-11e9-97d4-757ad8d86878.png)

![image](https://user-images.githubusercontent.com/8914956/61616158-bfa4bf00-ac35-11e9-8ab0-a72035af3a15.png)

Most of them seems to suggest that battery lasts for more than 3 minutes. Unless this tool is constantly running at full power and is cutting something, it should probably last longer.

**Comment by ampersand55** [comment]
I think 1) is the major factor. 2kW is the maximum power load, and the smaller chainsaws like the BLACK+DECKER LCS1020 can probably output less than 2kW.

Some links for reference:

* https://www.wolframalpha.com/input/?dataset=&i=20+V+*+3+A+h+%2F+2+kW
* https://www.powerstream.com/battery-capacity-calculations.htm

**Comment by FuelType-Memes** [comment]
>     3. High-energy requirement Power tools shouldn't use tiny modular batteries and use built-in, UPS charged, cannot-be-unloaded batttery.(as seen with Smartphone)

I disagree. A lot of power tools use swap-able batteries, because it's much easier to just switch batteries and continue working than work for 20 minutes and take a 6hr break while your battery is charging:

[https://www.boschtools.com/us/en/boschtools-ocs/batteries-chargers-starter-kits-gxs18v-11n25-199624-p/](url)
