### ISSUE TITLE
Robots should not explode

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#32507]
# Describe the bug
Some robots explode when destroyed.

# Steps To Reproduce
1. Kill any turret type robot

# Expected behavior
Robots are not explosive.

# Versions and configuration
 - Game Version: Current master at 457d06c8aed70841a9bbb341a04247dc32c7e65b

# Additional context
These turrets are essentially the same as the remote weapon systems in use today but with autonomous targeting software. They don't contain any explosives except propellant in ammunition so the way they currently explode isn't justified.

**Comment by TychaiosIlithios** [comment]
Remember reading discussions regarding possible self destruct mechanisms in military bots, messing up possible capture. So it's sorta kinda interesting what current community view of self-destruct in different robot types is.

**Comment by floodie24** [comment]
i would say that any robot or turret that is designed to operate near friendlies would never have a self destruct mechanism. (every cop killed at roadblock because a turret was taken out)
A military robot designed to solo attack at front lines and the like would very likely have self destruct.

**Comment by kevingranade** [comment]
Theres a distinction between, "self destruct" and an explosion intended to
kill nearby enemies.  The former is somewhat reasonable, the latter is
unprecedented.

**Comment by misterprimus** [comment]
I'd say tanks/big walkers should self-destruct to prevent capture, like is done with modern tanks if they cannot be recovered. Also: warships. However, I doubt something this would be added to a turret. Too expensive/dangerous. I think this should fix it: https://github.com/CleverRaven/Cataclysm-DDA/pull/32544

**Comment by alkemann** [comment]
Closing this since it is fixed in #32544, turrents no longer explode on death
