### ISSUE TITLE
Blazemod - selecting diamond matrix in the crafting menuproduces an error

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#32511]
# Describe the bug

Selecting diamond matrix in the crafting menu produces the following error:

```
 DEBUG    : Tried to set invalid ammo of none for diamond matrix
 
 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 429
```

# Steps To Reproduce

1. Make a player
2. Debug "unlock all recipes"
3. Select "Diamond Matrix".

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.D-5733-g457d06c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by anothersimulacrum** [comment]
> Mods loaded: [
Dark Days Ahead [dda]
]

You're reporting an error with blazemod, but don't have it in your mod list

**Comment by ampersand55** [comment]
Oops.

Anyway, I just started a new world and character to reconfirm the error.

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.D-5733-g457d06c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Vehicle Additions Pack [blazemod]
]

**Comment by ampersand55** [comment]
Seems to be an easy fix. Removing the line `"ammo":` "NULL",` under `"id": "spiral_matrix"` in `blaze_test.json ` removes the error.


```

  {
    "id": "spiral_matrix",
    "type": "TOOL",
    "name": "diamond matrix",
    "name_plural": "diamond matrices",
    "description": "A sparkling diamond with a dazzling spiral pattern.  Small pieces of glittering crystal form on the edges as you hold it.",
    "weight": 250,
    "volume": 1,
    "price": 5000000,
    "to_hit": -5,
    "material": "diamond",
    "symbol": "*",
    "color": "white",
    "looks_like": "spiral_stone",
    "ammo": "NULL",
    "revert_to": "spiral_matrix",
    "use_action": {
      "target": "spiral_matrix",
      "msg": "Your senses dull as you gaze into the depths of this gemstone's center...",
      "moves": 60000,
      "type": "transform"
    }
  },
```
