### ISSUE TITLE
Zombies can smash the roofs of lower-z-level apartments

### ISSUE THREAD

**Issue by carlarctg** [CleverRaven/Cataclysm-DDA#32527]
If you let a zombie hulk or so roam around an apartment entrance, it begins destroying the place, including roofs causing the place to rain even though there's 5 other levels above it.

1. Spawn a hulk on an apartment
2. Run in terror upstairs and wait a few hours/days
3. Come back and get -60 wet debuff due to all the non-euclidean open space above your head

![image](https://user-images.githubusercontent.com/53100513/61587896-16909280-ab69-11e9-85f7-54d0b0fdca27.png)
![image](https://user-images.githubusercontent.com/53100513/61587899-1d1f0a00-ab69-11e9-8f84-3980360aa841.png)

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5687-g8058314 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Bens GF recipes [Tolerate_This],
    Garden Pots [growable-pots],
    Generic Guns [generic_guns],
    No Rail Stations [No_Rail_Stations]

**Comment by ipcyborg** [comment]
PR #34866 fixes this, right?

**Comment by mlangsdorf** [comment]
More or less.  You can still have a floor on z-level X+1 that isn't supported by a wall on z-level X, but fixing that is complicated.
