### ISSUE TITLE
Metal wreckages spawned during aircraft crash behave inconsistently

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32533]
# Describe the bug

They can share a tile with a vehicle, and this results in undesirable consequences:

* You can cut your limbs or clothing while walking on a vehicle
* You can effectively lose any items dropping them in a vehicle, since they cannot be picked up from the wreckage tile until it's cleared
* You can't clear them until you remove or destroy the vehicle tile coincident with the wreckage that can be really troubling in case of undamaged frames
* The game doesn't prompt whether you really want to step on them

0.D-5749-ga24f3b03bf-dirty

**Comment by tinukedaya** [comment]
You can actually clear a tile under vehicle using the actions menu > clear rubble.
Cutting limbs and clothing while going thru wrecked vehicle is also believable.   
The only problem I have with this is that you don't really see under which tiles the wreckage is and that the game sometimes prompts if you want to step on it and sometimes it does not.

**Comment by ANickelN** [comment]
I can confirm the issue where sometimes the tile will warn you about stepping on it, and other times it will completely ignore it resulting in accidental damage at times.  I think it may have something to do with whether or not you are on the vehicle, but I can't check that at the moment.
