### ISSUE TITLE
Reducing save file size through new mechanic: A feature request

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#32530]
**Is your feature request related to a problem? Please describe.**  
A clear and concise description of what the problem is. Ex. I'm always frustrated when [I play for long periods of time on the same character, and saving the game takes a very long time.]

**Describe the solution you'd like**  
The solution is simple: **Traveling**.
The problem is, that the map gets too big after a while, so it seems obvious that an in-game, lore-friendly, non-immersion breaking option to reset/delete the current map solves this. It can be a building like a traveling center or the rail-road station, where the player has the option to travel to a new, unexplored part of New England, possibly requiring to do some task to allow this like fixing the train or just bringing a car with lots of fuel. The player has the option to put everything he wants to take with them into a set room or a marked set of tiles or even a train wagon, activates a bulletin board and is then offered the option to be moved to a fresh world, along with their luggage.

**Describe alternatives you've considered**  
Since this is not an option for players that build camps and bases, and want to keep those, an alternative could be that the traveling has the player move through a series of generated, small places, with set exits, much like traveling through a canyon or a series of connected dungeons, that eventually give you the option to return to your old map. The "chunks" the player leaves can then be deleted and don't impact the size of the of the save file anymore. Doesn't diminish the size of the current world, but keeps it from growing.

An additional alternative I've considered would be an option during world creation:
Let's call it "The Mist". You can probably think of what I have in mind simply by reading the name. The overmap has a maximum vision range that can't be seen through, and everything outside of that range gets deleted. When the player returns to a place he should have already been, a new location is generated. The player is basically lost in a thick, otherworldly mist, goes great with Mi-Gos and Shoggoths chasing the player for additional flavor.

**Additional Context**
People already move their characters to new maps manually, but it's fairly tedious and complicated. Not everyone has the confidence in their technical know-how to look into this either, chances are that those people also don't play on very high-end systems, which can amplify this issue for them.

Thank you for reading.

**Comment by ZhilkinSerg** [comment]
Related https://github.com/CleverRaven/Cataclysm-DDA/issues/65
Related https://github.com/CleverRaven/Cataclysm-DDA/issues/10784

**Comment by TechyBen** [comment]
As a current workaround, if using Windows, NTFS seems to help with file sizes on disk. Mine are (checks) usually better than 50% compression (though I don't do massive map/saves anymore, and tend to keep the character local). So a 150mb save is only 60 odd mb on disk.

I think the file structure of the saves helps for modding, but I don't know if the devs would think the investment in a compression (and/or) cabinet type save file system would be worth it?

**Comment by kevingranade** [comment]
I'm 100% not interested in an in-game workaround for a technology problem.  If large file size are a problem, we need an in-engine fix for file sizes. 

There are innumerable technological fixes for this kind of thing, but we have received negligible reports of it being a problem.

**Comment by Bulletfang** [comment]
Hmm... okay. It **is** a negligible problem, no point in discussing this if you want to go the in-engine route, which is probably the better solution.
