### ISSUE TITLE
Stamina Growth

### ISSUE THREAD

**Issue by TRScheel** [CleverRaven/Cataclysm-DDA#32543]
_So it doesn't get buried in the wall of text below, this is a feature I'd be willing to attempt myself._

**Is your feature request related to a problem? Please describe.**  
Stamina is currently flat. You have a base amount multiplied against any mutations. A system to increase/decrease the stamina max would allow players to 'workout' and would also require players give some strategic thought to how they exert themselves throughout the day. 

**Describe the solution you'd like**  
Break stamina maximum into three different concepts: stamina_max, stamina_temporary_max, stamina_absolute_max.

- `stamina_max` would be your player's current maximum stamina. Imagine this is the most you can do without collapsing when waking up completely rested.
- `stamina_temporary_max` would be your current maximum stamina as you exert yourself throughout the day, and would only regen towards `stamina_max` while resting. Imagine this as if you went for a run this morning -- It would affect your ability to run this afternoon. Even exerting yourself a lot yesterday without proper rest would affect you today.
- `stamina_absolute_max` is the most you could build stamina_max to based off your stats, bionics, traits, and mutations. No matter how hard you train, you will never get more than this and approaching this maximum is difficult.

The stamina values would be in this hierarchy: 
`stamina` <= `stamina_temporary_max` <= `stamina_max` <= `stamina_absolute_max`

As you use your stamina throughout the day you'd start to lower your `stamina_temporary_max`. How much you lower your `stamina_temporary_max` is a function of how much you use. Barely using any of your maximum stamina will not drop it much, but bringing yourself to winded would really hurt your `stamina_temporary_max`. 

Only by lowering your `stamina_temporary_max` can you increase your `stamina_max` though. The more you use your `stamina_temporary_max` the more you increase your `stamina_max`. The inverse though, not exerting yourself so as to lower your `stamina_temporary_max`, would see your `stamina_max` start to decrease.  

`stamina_max` would see a logarithmic growth towards `stamina_absolute_max`, growing quickly at first but slowly reaching the maximum. It would see an exponential decline as you avoid physical effort, basically the closer to you are to the max the more you'd have to exert yourself to keep at that level and the faster it would drop.

**Describe alternatives you've considered**  
Increasing base stats based off usage (str, dex, etc). This was discard because they are not granular enough to have this sort of progression over time, but they are useful for defining the player stamina maximum.

Using a skill is also an option but `stamina` isn't a skill. Also, the idea of reading a book and being able to run longer seems odd (outside the most basic improvements in form). Also you'd want it to decline based off not using it by default.

**Additional context**  
Looking at the code this sort of overhaul shouldn't be difficult to implement unless I'm completely missing something and I am offering to tackle it myself if its approved. The largest hurdle I see is balancing, not implementation.

Code changes would include:
- another `regen` function would be added, similar to the one for health, but for `stamina_temporary_max`. It would also work to adjust `stamina_max` up or down based off current exertion.
- `update_stamina(int turns)` would be updated to progress towards `stamina_temporary_max`. It would also perform the math to adjust `stamina_temporary_max` down
- `get_stamina_max()` would include any sort of stamina growth the player has accrued (it would be returning the `stamina_max` concept in the description above)
- Adjust the `wait until you've caught your breath` to be looking to the `stamina_temporary_max` instead of `get_stamina_max()`
- Show your stamina growth/degeneration in the player sheet. I'd put it right under the weight field (You're weak/normal/built/ripped/etc). It would be a function of your `stamina_max` / `stamina_absolute_max` which would mean that a normal human would feel ripped at a much lower value than a mutated hulking freak.
- Have the sidebar stamina display be your current stamina over your `stamina_temporary_max` instead of `get_stamina_max()`
- Add the necessary save/loading of the supporting variables

**Comment by kevingranade** [comment]
Take a look at #24052
We never got it sorted out to our satisfaction, but this is the general approach we want to see.
The key differences are:
Physical development over time and long-term stamina modeling are not the same thing.
We want an explicit link between these stats and what they mean physically. Short term stamina as currently represented represents very short term metabolic reserves like oxygen and CO2 levels, longer term stamina should represent depletion of other metabolic reserves and/or muscle fatigue.

**Comment by Vasyan2006** [comment]
Part of this stamina PR was replaced by activity mechanic created by Korgent and Erk.

Here I already posted why this mechanic is much worse for both realism and gameplay:
https://github.com/CleverRaven/Cataclysm-DDA/pull/24052#issuecomment-493733856

Kicking a squirrel will start "combat" activity and will remove calories as if the character was in heavy melee combat for 30 minutes. This was merged.

In my PR single melee attack will remove calories only for one attack. This value will be modified by corresponding mutations, arm encumbrance, weapon weight and other factors.
But this is wrong approach and not realistic.

**Comment by Zourin2** [comment]
What about Cardio as a progressing/regressing Max Stamina modifier similar to Health, but taking average exercise level, health, and body weight into consideration. Up to 2x the stamina cap should be possible, but peak performance should be difficult to keep.

- Cardio updates once a day. It goes up if your daily activity average exceeds your 90?day exercise level, and goes down if you spent all day in bed/reading books. It does not change if your current daily activity level matches your average. Alternatively, if you like 'rest days', the highest activity level over the past 2-3 days.
- Cardio goes up more the lighter/healthier you are. This does not affect regression.
- Cardio naturally regresses faster when it is higher.
