### ISSUE TITLE
Closing Windows From Outside

### ISSUE THREAD

**Issue by Mrchache** [CleverRaven/Cataclysm-DDA#32547]
**Is your feature request related to a problem? Please describe.**  
You cannot close a window from the exterior if it has a curtain attached to it, closed or open.

**Describe the solution you'd like**  
In our lives, I'm certain at some point someone closed a window from the outside, regardless of curtain status.

**Describe alternatives you've considered**  
Using a clever pull-string to pull the blinds/window covers shut and then close the window with plunger cups (kidding).

**Additional context**  
I don't know how many time you've snuck out from your parents house but this is exactly what you do when you sneak out. Also, when my exit point from my base is a window point, I'd love to semi-secure it behind me.

**Comment by EddiTheBambi** [comment]
Would it be reasonable to have the acton of closing a window from outside take longer or is that just unnecessary checking for inside/outside?

**Comment by Mrchache** [comment]
Looks like someone snuck it in. Windows can be closed from outside now!

**Comment by Mrchache** [comment]
Premature. You can close windows without curtains currently. But windows with curtains cannot be closed from the outside.
