### ISSUE TITLE
Deconstructing earthbag barricade yields sandbags

### ISSUE THREAD

**Issue by rabidradioactiveraccoons** [CleverRaven/Cataclysm-DDA#32559]
# Describe the bug

Upon deconsructing earthbag barricade, the yield is sandbags instead of earthbags

# Steps To Reproduce

1. Construct earthbag barricade
2. Deconstruct earthbag barricade

# Expected behavior

That deconstructing a barricade will yield the same materials as the barricade

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-5751-g1015287 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Dark Days Ahead: Lua [dda-lua],
    Dark Days Ahead: Lua (Fun) [dda-lua-fun],
    Dark Days Ahead: Lua (Skills) [dda-lua-skills],
    Dark Days Ahead: Lua (Traits) [dda-lua-traits],
    Nechronica Redux [Nechronica_Redux],
    Add Rice [rice],
    Armor Up! PA Utilities [ArmUpPAUtil],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Armored Fursuit [afursuit],
    Arsenal Breach [arsenal_breach],
    Bens GF recipes [Tolerate_This],
    Bootleg Walkers [Bootleg_Walkers],
    Broken Admin's Makeshift Items [bsam],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Disinfectant Powder [powder_disinfectant],
    Fungus Fighter Kit [antifunguskit],
    Hybrid Crossbow [pistol_cross],
    Icecoon's Arsenal [ew_pack],
    Kingsman Umbrella [kingsman],
    More Survival Tools [More_Survival_Tools],
    Boats [boats],
    MST Extra [MST_Extra],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Armors [More_Armors],
    More Vehicles [mo_veh],
    Pressure Weapons [pressure_weapon],
    The Vermilion Mod [VermilionMod],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    Vampiric Stuff [vamp_stuff],
    Urban Development [Urban_Development],
    Classes and Scenarios Mod [more_classes_scenarios],
    Extra Scenarios [Ex_Scenarios],
    Manual Bionic Installation [manualbionicinstall],
    More Character Creation Choice [more_char_creation],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by anothersimulacrum** [comment]
> Dark Days Ahead: Lua [dda-lua],
Dark Days Ahead: Lua (Fun) [dda-lua-fun],
Dark Days Ahead: Lua (Skills) [dda-lua-skills],
Dark Days Ahead: Lua (Traits) [dda-lua-traits],

How are you even loading your game? LUA mods will crash your game when you try to load them.

**Comment by rabidradioactiveraccoons** [comment]
I honestly have no clue, I was not even aware that the LUA mods are supposed to crash the game.

**Comment by BevapDin** [comment]
> LUA mods will crash your game when you try to load them.

How are they going to crash the game? I thought Lua has been removed from the game, so what exactly does the game do, besides ignoring the Lua code?

**Comment by anothersimulacrum** [comment]
I've seen many, many occurrences of crashing when trying to load the game with LUA mods.
