### ISSUE TITLE
Pool of acid dose not disappear naturally.

### ISSUE THREAD

**Issue by Ezsk** [CleverRaven/Cataclysm-DDA#32566]
# Describe the bug
Pool of acid dose not disappear naturally.

# Steps To Reproduce
1. place an acid zombie.
2. just kill him and confirm the pool of acid has spawned.
3. wait for a day.
4. confirm the pool of acid being there.

# Expected behavior
pool of acid is disappear in few minutes. like a old versions.
I am not sure if this is the correct specification. However, this terrain is written as "half_life": "2 minutes" in field_type.json, so I am convinced that it is designed to disappear in few minutes.
Anyway we need a way to remove the acid pool.

# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.D-5805-g50eb478
 - Graphics version: Tiles
 - Mods loaded: "dda","no_npc_food"

# Additional context
The same problem can be confirmed from the version at least one month ago.

**Comment by ZhilkinSerg** [comment]
> The same problem can be confirmed from the version at least one month ago.

That is probably incorrect and first affected build should be 9261.

**Comment by NickGrease** [comment]
This video from Vorm shows the issue, and I believe shows smoke, acid and gas are affected.
https://www.twitch.tv/videos/454237247?t=04h56m06s

**Comment by ZhilkinSerg** [comment]
```
9d571156a61efe4a269ddddb41f4597378b7fb6c is the first bad commit
commit 9d571156a61efe4a269ddddb41f4597378b7fb6c
Author: ZhilkinSerg <ZhilkinSerg@users.noreply.github.com>
Date:   Tue Jul 2 11:45:36 2019 +0300

    Used field type class

:040000 040000 a41320b99078178ca98cfcf135f9b6b5b99371f2 3e58a2353fddfeaeb48560c982b1a9b9636b797e M      src
:040000 040000 c92c2b43f03198408d4b7601ca9747da1a4da4ec 99e23e8697fe2be4692c4df0f82960fc2dcb3e50 M      tests
```

**Comment by ZhilkinSerg** [comment]
Caused by: #31362
