### ISSUE TITLE
Rocks with "charges" bugs out all rocks.

### ISSUE THREAD

**Issue by TechyBen** [CleverRaven/Cataclysm-DDA#32569]
# Describe the bug

On save, then reload. Rocks are attempting to have a charge (possibly as they are "tools" for hammering etc?). As a rock cannot have a charge (though potatoes can power personality cores apparently), the game is not sure what to do with them. Any rocks in inventory (possibly in containers, though not double checked) will vanish into the ether.

# Steps To Reproduce

1. Start game. 
2. Save.
3. Reload.
4. See error on loading. Pick up rock.

# Expected behavior

Rocks should not teleport and "rock out" of existence.

# Versions and configuration

Latest version. Windows. Tiles.

# Additional context

Recent charges and crafting updates?

**Comment by chronicpayne** [comment]
Can also confirm this is happening. 
Possibly #32466

Rocks in containers seem fine, until you try to pick them up.

This kills the ~crab~ rock.

**Comment by BevapDin** [comment]
Rocks don't have charges. Are you using any mod (Blazemod for example)? This information belongs into your bug report.

Anyway, rocks in blazmod are strange: they *do* have charges (perhaps because they are ammo?) but they do not merge into a single item (they are not stackable). Therefor they *should* not have charges.

**Comment by ZhilkinSerg** [comment]
I believe it is mining mod issue.

**Comment by macrosblackd** [comment]
```
7:11:42.446 ERROR : src/savegame_json.cpp:2142 [void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]] Item rock was loaded with charges, but can not have any!
17:15:01.059 ERROR : (error message will follow backtrace)
	(@0x5ad29e[cataclysm-tiles.exe+0x1ad29e]), 
	(@0x5ad8ca[cataclysm-tiles.exe+0x1ad8ca]), 
	(@0x5b0ca6[cataclysm-tiles.exe+0x1b0ca6]), 
	(IMG_LoadWEBP_RW+0x111093@0x111f6a3[cataclysm-tiles.exe+0xd1f6a3]), 
	(IMG_LoadWEBP_RW+0x290f73@0x129f583[cataclysm-tiles.exe+0xe9f583]), 
	(@0xd0d1d5[cataclysm-tiles.exe+0x90d1d5]), 
	(@0xd156af[cataclysm-tiles.exe+0x9156af]), 
	(@0x9215f5[cataclysm-tiles.exe+0x5215f5]), 
	(@0x4f8cf3[cataclysm-tiles.exe+0xf8cf3]), 
	(@0x4fd053[cataclysm-tiles.exe+0xfd053]), 
	(@0x4fd381[cataclysm-tiles.exe+0xfd381]), 
	(@0x92233f[cataclysm-tiles.exe+0x52233f]), 
	(@0x9228eb[cataclysm-tiles.exe+0x5228eb]), 
	(@0x8d79f0[cataclysm-tiles.exe+0x4d79f0]), 
	(@0x8d8252[cataclysm-tiles.exe+0x4d8252]), 
	(@0x6a1d36[cataclysm-tiles.exe+0x2a1d36]), 
	(@0x6a2b57[cataclysm-tiles.exe+0x2a2b57]), 
	(@0x6a381e[cataclysm-tiles.exe+0x2a381e]), 
	(@0x6bdcf6[cataclysm-tiles.exe+0x2bdcf6]), 
	(@0x4a396a[cataclysm-tiles.exe+0xa396a]), 
	(@0x6dbb6e[cataclysm-tiles.exe+0x2dbb6e]), 
	(@0x6b92a7[cataclysm-tiles.exe+0x2b92a7]), 
	(IMG_LoadWEBP_RW+0x566cf8@0x1575308[cataclysm-tiles.exe+0x1175308]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0x14@0x7ffbd08c4034[KERNEL32.DLL+0x14034]), 
	(RtlUserThreadStart+0x21@0x7ffbd1fc3691[ntdll.dll+0x73691]), 
Backtrace emission took 0 seconds.
src/savegame_json.cpp:2142 [void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]] Item rock was loaded with charges, but can not have any!
17:15:07.856 ERROR : src/savegame_json.cpp:2142 [void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]] Item rock was loaded with charges, but can not have any!
```
MODS:
```
[
  "dda",
  "no_npc_food",
  "magiclysm",
  "growable-pots",
  "More_Survival_Tools",
  "DinoMod",
  "modular_turrets",
  "Salvaged_Robots",
  "hydroponics",
  "more_locations",
  "FujiStruct",
  "deoxymod",
  "blazemod",
  "Tanks",
  "sees_player",
  "DP_REMIX_INDICATORS",
  "No_Fungi",
  "no_filthy_clothing"
]
```

**Comment by TechyBen** [comment]
> Rocks don't have charges. Are you using any mod (Blazemod for example)? This information belongs into your bug report.
> 
> Anyway, rocks in blazmod are strange: they _do_ have charges (perhaps because they are ammo?) but they do not merge into a single item (they are not stackable). Therefor they _should_ not have charges.

Yeah, sorry, forgot to add mods. I generally only use blazmod for the mechanics additions, not the weps/weird materials... so often forget it mods those too. I guess I should get around to stripping it down to the essentials for my own games.
