### ISSUE TITLE
Save game or notify when attempting to close window

### ISSUE THREAD

**Issue by madmenyo** [CleverRaven/Cataclysm-DDA#32563]
**Is your feature request related to a problem? Please describe.**  
I just accidentally closed the window and lost a lot of progress.

**Describe the solution you'd like**  
Catch the closing event of the window and either auto-save or notify the player but stop the game from terminating immediately without saving.

**Describe alternatives you've considered**  
Well, I could be running the game full screen or borderless but I'd rather not.

**Comment by Hirmuolio** [comment]
Tip: Enable autosaving. It can be configured to save every X IRL time or after X number of moves.

**Comment by ZhilkinSerg** [comment]
I second using of autosave feature.

**Comment by glenmack** [comment]
Thirded: I set it to max of 1000 turns, and it doesn't bother me and I very rarely lose an annoying amount of progress.

**Comment by ampersand55** [comment]
This fix would also prevent save-scumming.

**Comment by ZhilkinSerg** [comment]
> 
> 
> This fix would also prevent save-scumming.

I doubt it - even if that won't be a configurable option, people would just use task manager to kill process.

**Comment by ampersand55** [comment]
I'll rephrase: It will be an obstacle for save-scumming.

**Comment by Leland** [comment]
> notify the player but stop the game from terminating immediately without saving.

I'm cool with this

**Comment by kevingranade** [comment]
We currently catch the linux kill application signal and prompt the player asking them what they want to do, this is a reasonable thing to do on windows as well.
