### ISSUE TITLE
Hand-crank charger won't stop on completing charging a battery

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32582]
# Steps To Reproduce

1. Insert a 49/50 battery in a hand-crank charger.
2. Start cranking it.
3. Observe yourself cranking it for hours even though it was fully charged long ago.

0.D-5805-g50eb478eb0-dirty

**Comment by glenmack** [comment]
Needs code for stop on fully charged indeed.
