### ISSUE TITLE
"Invalid effect, ID: stim_overdose"

### ISSUE THREAD

**Issue by vasgen40k** [CleverRaven/Cataclysm-DDA#32590]
# Describe the bug

```
DEBUG    : Invalid effect, ID: stim_overdose

FUNCTION : virtual void Creature::add_effect(const efftype_id&, time_duration, body_part, bool, int, bool, bool)
FILE     : src/creature.cpp
LINE     : 907
```

# Steps To Reproduce

1. Create new character with profession "Crackhead".
2. Activate item "zipper bag with crack"
3. Get debug message.

# Versions and configuration

 - OS: Arch Linux 5.0.9-zen1
 - Game Version: 0.D-5703-g850f19cd9a
 - Graphics version: Tiles
 - Mods loaded: dda

**Comment by kevingranade** [comment]
Looks like I somehow missed that this could still be applied, thanks for reporting.
Need to revert this commit to fix it
https://github.com/CleverRaven/Cataclysm-DDA/commit/265397f9665fe6941dc18450a886f6fabbca4a1d
