### ISSUE TITLE
Scrolling is slow in the "V" menu

### ISSUE THREAD

**Issue by rumly111** [CleverRaven/Cataclysm-DDA#32596]
# Describe the bug
When I open the list of nearby items (V), and try to scroll through them, there is a noticeable delay.

# Steps To Reproduce
1. Press "V" to open nearby items list
2. Scroll down/up through the items.

# Expected behavior
Scrolling should be mush smoother and faster.

# Versions and configuration
 - OS: Ubuntu 16.04 32-bit
 - Game Version: Not sure, but it was freshly built on 2019-07-14
 - Graphics version: Tiles
 - Mods loaded: dda, magiclysm, necromancy, No_Fungi, no_npc_food, StatsThroughSkills, no_reviving_zombies, more_locations, FujiStruct, No_Rail_Stations, alt_map_key, sees_player_less_attitude

# Additional context
The game was built with optimizations (-O3, -march=native -mtune=native)

**Comment by ZhilkinSerg** [comment]
Can you provide a savegame please?

**Comment by rumly111** [comment]
> Can you provide a savegame please?

I can't really. I think the problem might be the overall poor performance of the game. The developers should run it every now and then on a computer with a 2GHz 1- or 2-core CPU with 4Gb ram to see how it works.

**Comment by kevingranade** [comment]
Non-actionable bug.

**Comment by rumly111** [comment]
I see you're very efficient at closing bugs. Keep up the good work!

**Comment by ZhilkinSerg** [comment]
> > Can you provide a savegame please?
> 
> I can't really. I think the problem might be the overall poor performance of the game. The developers should run it every now and then on a computer with a 2GHz 1- or 2-core CPU with 4Gb ram to see how it works.

We can't profile a non-existing savegame. Subjective feelings of game being slow are irrelevant.
