### ISSUE TITLE
CVD Machine lab finale is always broken

### ISSUE THREAD

**Issue by FrozenSnowFox** [CleverRaven/Cataclysm-DDA#32605]
**Is your feature request related to a problem? Please describe.**  

The CVD Machine lab finale always seems to spawn with a number of zombies.  These zombies especially ones not killed by lab security roam around and trash the machine making it unusable.  Despite finding a CVD Machine several times I don't think I've ever found one that didn't have its console broken.  There's also a lesser issue that its extremely difficult to use anyway because the hydrogen must be found separately and is quite rare.

**Describe the solution you'd like**  

Other lab finales with sensitive items tend to not spawn enemies that can break them or tend to be protected by reinforced glass.  I think the CVD Machine finale should be reworked to be a proper room like the nanofabricator with limited enemy spawns, nice decorations, reinforced glass for protection and enough coal and hydrogen for 1 weapon of moderate size.

**Describe alternatives you've considered**  

Instead of reworking the CVD Machine spawning the machine components could simply be made unbreakable by standard zombies.  The machine could be surrounded by reinforced glass or problematic enemies could have their spawning removed.

**Comment by glenmack** [comment]
There's a version of the finale that spawns with crappy pistols and low level ammo, even those are gated behind reinforced glass.

I've not done map JSON stuff yet, but I think I could definitely Surround it in reinforced glass.

**Comment by Bulletfang** [comment]
I've been playing CDDA for over 2 years now, fairly actively, and have never ever even once found the hydrogen. At this point, I doubt it spawns at all. It's just a ghost in the code that some players spawn through the debug console and then claim they found it.

**Comment by 81Denton** [comment]
@Bulletfang If I looked it up correctly, hydrogen canisters only spawn in the "science" item group with a low overall chance:
https://github.com/CleverRaven/Cataclysm-DDA/blob/319f9e189e00c0b2b3e7e92506f199f9cbba51f6/data/json/item_groups.json#L7221

IRL hydrogen has plenty of uses in chemical and petroleum industries, so maybe it would make sense to make them more available?

**Comment by FrozenSnowFox** [comment]
> There's a version of the finale that spawns with crappy pistols and low level ammo, even those are gated behind reinforced glass.
> 
> I've not done map JSON stuff yet, but I think I could definitely Surround it in reinforced glass.
> 
> edit: That would be if I could find it. Isn't it supposed to be in lab_floorplans_finale1level?
> double edit:It's in one of the hardcoded mapgen.cpp files, not JSON. Will take me a fair bit longer.

Well if you decide to go through the trouble of updating it I hope you decide to take the time to do a proper redesign rather than just slap some reinforced glass around it.  It's an old area that could really use some love to bring it up to the standard of newer areas.  Hell most of the lab finales could probably do with a new coat of paint so they don't look so dull.

> I've been playing CDDA for over 2 years now, fairly actively, and have never ever even once found the hydrogen. At this point, I doubt it spawns at all. It's just a ghost in the code that some players spawn through the debug console and then claim they found it.

I've been playing the game on and off for a year or more now.  In my most recent game I actually found 100 units of hydrogen which I believe was 2 spawns.  It is the only time I have ever found it since playing.  It was found in military bunker vault which looks like it was redesigned and had its spawns adjusted.  It had proper shelves and more loot than previously.  So I think now there might be a chance you can actually find it.  Still considering how rare the CVD Machine is its pretty harsh to have to find them separately.

**Comment by glenmack** [comment]
@81Denton 
>IRL hydrogen has plenty of uses in chemical and petroleum industries, so maybe it would make sense to make them more available?

It isn't JUST hydrogen, it's hydrogen that's been pressurized in a special ammo canister. Compatible with certain plasma weapons and the CVD machine. That's why it's rare.
Hydrogen can be found in bunkers, in crates in labs, spider basements and at Science body sites. It is indeed super rare though.

@FrozenSnowFox 
>Well if you decide to go through the trouble of updating it I hope you decide to take the time to do a proper redesign rather than just slap some reinforced glass around it. It's an old area that could really use some love to bring it up to the standard of newer areas. Hell most of the lab finales could probably do with a new coat of paint so they don't look so dull.

I agree, but I think the chances of them spawning and the criteria are why they are tied to the mapgen.cpp I would think it would make sense to JSON-ify them and bring them up to date, but it's beyond my capabilities if it's tied to map conditions.
