### ISSUE TITLE
craft search of hidden recipes returns no results

### ISSUE THREAD

**Issue by 8ctopus** [CleverRaven/Cataclysm-DDA#32611]
# Describe the bug

In build #9369 and older, craft search of hidden recipes returns no results. It was working fine 2 months ago.

# Steps To Reproduce

1. Open craft & menu
2. Hide any recipe by pressing s,
3. Next search (F key) and enter "h:yes".
4. It always returns 0 results when it should show all hidden recipes

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.D-5832-g319f9e1 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by TychaiosIlithios** [comment]
Btw that hidden part needs more subfolders or something - searching it by just alphabetical ordering becomes quite unpleasant quite fast.

**Comment by BevapDin** [comment]
Closing because searching for hidden recipes was removed in #32901 anyway.
