### ISSUE TITLE
Cotton balls double in volume when soaked with disinfectant

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#32626]
# Describe the bug

Cotton balls double in volume when crafted into disinfectant soaked cotton balls.

# Steps To Reproduce

1. Get some cotton balls. Four of them takes up 0.5L of space.
1. Craft them into disinfectant soaked cotton balls.
1. They now take up 1L of space!

Note that their weight does not change, only their volume.

# Expected behavior

Cotton balls remain the same size when soaked with disinfectant.

# Versions and configuration

OS: Ubuntu 16.04 LTS
Game version: a4acee28f41f741baca796b20fef4bb3246a0df7
Graphics: Tiles
Mods:

-   Dark Days Ahead [dda],
-   Disable NPC Needs [no_npc_food],
-   Filthy Clothing [filthy_morale],
-   Alternative Map Key [alt_map_key],
-   [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
-   sees-player icon, +attitude [sees_player],
-   Modular Turrets [modular_turrets],
-   Salvaged Robots [Salvaged_Robots],
-   Sleep Deprivation [sleepdeprivation],
-   Bionic Slots [cbm_slots]

# Additional context

Sorry for this being a bug report rather than a PR. Disinfectant soaked cotton balls inherit from regular cotton balls, but [change the number of charges to 1](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/comestibles/med.json#L1341). I don't know if that's the reason for the volume doubling, as I'm uncertain how charges work with regards to volume.

**Comment by glenmack** [comment]
Confirmed and working on a PR.

**Comment by pjf** [comment]
Hooray! Thank you, @glenmack!
