### ISSUE TITLE
 why was last firefighter start removed?

### ISSUE THREAD

**Issue by joe9000** [CleverRaven/Cataclysm-DDA#32623]
# Describe the bug

# Steps To Reproduce

1. Make a player with a gun, magazine, and some ammo.
2. Try to aim at a wall.
3. There's no way to increase aim level.

# Expected behavior

Ideally also describe *why* you expect it to happen.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by Rail-Runner** [comment]
> why was last firefighter start removed? 

You can now play the same start via choosing "Surrounded" scenario, then selecting a firefighter profession and a fire station as a starting location.

**Comment by Hymore246** [comment]
A lot of scenarios were simplified in #31661

As per the PR:
>The Last Firefighter: integrated into Surrounded.
