### ISSUE TITLE
FR: tank heater or insulted tanks 

### ISSUE THREAD

**Issue by sammy202020** [CleverRaven/Cataclysm-DDA#32636]
**Is your feature request related to a problem? Please describe.**  
the problem is that is annoying / time consuming to defrost water inside tanks.  and in real life there is things like water tank heaters or insulated  tanks. 

**Describe the solution you'd like**  
the solution could be to add a tank of each volume that can be installed with the insulation value of a mini fridge or higher to prevent water from freezing. a low level of power drain could be used to justify why the water doesn't freeze since there is a water heater running. 
**Describe alternatives you've considered**  
well the alternative could be just not add this. or well adding a water heater item into the game that can be installed in a vehicle on that same tile as a tank. but im unsure this could be done due the nature of this game

**Additional context**  
well ive done some minor testing and found a mini fridge has enough to stop stuff from freezing long as its turned off (since when turned on it cools items inside). i haven't had time to test adding insulation to a 60L tank since ive been busy. but im sure if someone tried this they would find this would work.

**Comment by Qrox** [comment]
I think you mean insulated tanks?

**Comment by sammy202020** [comment]
Qrox yea fat thumbed it and didnt notice.

**Comment by DeltaEpsilon7787** [comment]
Haven't I addressed this with #27824

**Comment by sammy202020** [comment]
Ehh its half addressed
