### ISSUE TITLE
Stats Through Kills: increasing intelligence does not stop "you are too stupid" message

### ISSUE THREAD

**Issue by Contemplator11** [CleverRaven/Cataclysm-DDA#32641]
# Describe the bug

When you increase intelligence via Stats Through Kills, reading complex books still prompts "The book is too complex for you to easily understand" message, and reading time is displayed in red.

# Steps To Reproduce

1. Generate a character with 10 Intelligence with Stats Through Kills enabled;
2. Get "Principles of Advanced Programming"
3. Increase your Intelligence to 11 via StatsThroughKills;
4. Read "Principles of Advanced Programming" and look at "The book is too complex for you to easily understand" message.

Note: PoAP standard reading time is 40 minutes. It took me 30 minutes to read when my character got 11 Intelligence from StatsThroughKills. I guess it is from inherent Intelligence quality that decreases reading time. The message pops nevertheless.

# Expected behavior

The message should not appear when you increase your Intelligence to appropriate level via StatsThroughKills
<img width="960" alt="Raina1" src="https://user-images.githubusercontent.com/52279819/61953970-65528800-afc0-11e9-9d23-f9fea630c939.PNG">

<img width="960" alt="Raina2" src="https://user-images.githubusercontent.com/52279819/61953980-6c799600-afc0-11e9-9ebd-7d619484cbdb.PNG">

**Comment by ZhilkinSerg** [comment]
Savegame?

**Comment by Contemplator11** [comment]
> Savegame?

Uploaded:
[Valhalla.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3436119/Valhalla.zip)

**Comment by ZhilkinSerg** [comment]
Confirmed.

**Comment by KorGgenT** [comment]
kills or skills? i just want to confirm which mod it is you're having issues with because the formatting and word you're using isn't consistent.

**Comment by Contemplator11** [comment]
> kills or skills? i just want to confirm which mod it is you're having issues with because the formatting and word you're using isn't consistent.

Kills. Sorry for typo, corrected it.
