### ISSUE TITLE
NPCs (W11 series of robots) can fire through reinforced glass

### ISSUE THREAD

**Issue by Sharkey-Ward** [CleverRaven/Cataclysm-DDA#32646]
# Describe the bug

The W11 series of robots can fire through reinforced glass as if it wasn't present, both with small arms (in this case Scar-Hs firing 7.62x51) and anti-tank rockets from the W11H NPC.

# Steps To Reproduce

1. Go into the underground level of a national guard camp
2. find reinforced glass with an NPC behind it
3. get shot at through said glass while being unable to fire back through that same glass utilizing the same weapon

# Expected behavior

Either the threshold for piercing the glass should be universal, so a player firing 7.62x51 should be able to shoot through the reinforced glass back at the NPCs, or the NPCs should also not be able to fire at the player through said glass.

# Screenshots
![image](https://user-images.githubusercontent.com/53281045/61973572-b8c1d780-afba-11e9-97a0-a13e4cd5a311.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-5855-ge8063b8
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC needs, C.R.I.T Expansion mod, Craft ammo and belt links, Craftable guns pack, deadleaves fictional guns, icecoon's arsenal, makeshift items mod, medieval and historic classes, more survival tools, modular turrets, salvaged robots, Beta National Guard camp, More Locations, Fuji's more buildings, Folding parts pack, Vehicle additions pack, Tanks and other vehicles, Safe autodoc, Statsthroughskills

**Comment by DemAvalon** [comment]
I was in a National Guard camp and I was also able to shoot through the glass with my guns, I think something is wrong with national guard camps or the reinforced glass.

**Comment by Edgar-cy-Lee** [comment]
As purveyor of guns in CDDA, you can indeed through reinforced glass. It has been that way for a while.

Doing so will reduce the damage of each shots, but it is indeed possible and reinforced glass will not break unless ammunition itself is very powerful.(try shooting it with .50 BMG)

**Comment by Night-Pryanik** [comment]
Reinforced glass is penetrable for player's weapons. The question is if it should be penetrable at all.

**Comment by ZhilkinSerg** [comment]
Closing in favor of #33374
