### ISSUE TITLE
Workstations spawned inside solid rocks during refugee center mission

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#32658]
# Describe the bug
During the mission to find and download data from workstations for the refugee center doctor, the workstations are nowhere to be found. Using debug clairvoyance reveals that the workstations were spawned inside solid rocks.

# Steps To Reproduce
1. Accept the mission to find and download data from workstations.
2. Get unlucky?

# Expected behavior
The consoles should spawn at accessible places.

# Screenshots
![image](https://user-images.githubusercontent.com/11890223/61993512-5d1d4a00-b09f-11e9-893f-cd40b85eb8e6.png)

The three consoles are all workstations, and according to the code only 4 are spawned for the mission. The fourth one was presumably destroyed by monsters, making the mission impossible to complete without using the debug menu.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.C-43469-ge8063b8aa7-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Fuji's More Buildings [FujiStruct],
    Beta National Guard Camp [national_guard_camp],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food]
]

# Additional context
The mission was accepted a few days ago, but there doesn't seem to be any change related to the bug since then, so I assume it still exist in the current version.

**Comment by Night-Pryanik** [comment]
I guess this has the same reason as in #27618.

**Comment by SunshineDistillery** [comment]
This might be the same as #32424

If the update mapgen from a mission is being applied to an overmap special (the research facility) which is rotated to 90 or 270 degress (East or West) then it will place it in the incorrect spot.

I'm not familiar with this mission or where the update mapgen is though.

**Comment by Qrox** [comment]
If this is caused by rotation of overmap specials, then #27618 probably has a different reason, see my comments there.
