### ISSUE TITLE
cdda latest Experimental Builds item spawn problem

### ISSUE THREAD

**Issue by shelak1** [CleverRaven/Cataclysm-DDA#32668]
# Describe the bug

item spawn factor doesn't work (only new over map)

# Steps To Reproduce

1. Make 0.01 item spawn rate world
2. old over map -> work (0 items)
3. new over map -> doesn't work (item spawned. like default value)

# Expected behavior

new over maps always ignore item spawn factor

# Screenshots

just play 0.01 spawn factor world
spawn relic and look around city

# Versions and configuration

 Windows (Graphical 64 bit Experimental)
 cataclysmdda-0.D-Windows_x64-Tiles-9380

mod : default

# Additional context

.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.D-8523. Set 0.01 item spawn modifier. Spawned my character in a new world, walked in town far away from starting location. Items spawn very rarely, as they should. Look at this empty house, for example.
![изображение](https://user-images.githubusercontent.com/11132525/66813965-d3b34080-ef46-11e9-9d17-0bfabd6d1a4a.png)

Closing for now, ping me if this is still an issue.
