### ISSUE TITLE
Disapearing Autoclave

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#32670]
# Describe the bug

Autoclave and content desapear if it runs out of battery before end of cycle and is outside of the player inventory.

# Steps To Reproduce

1. Get autoclave
2. Load with insufficient amount of battery (<8000)
3. Activate 
4. Put on the ground
5. Wait 
6. It desapears.

This does not happen if you keep the autoclave in your inventory.

# Expected behavior

Autoclave de-activate and CBM is spawned back on the same tile.

# Versions and configuration

 -  Windows 10 
 - build 9380
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [dda, NPCneeds]

# Additional context

**Comment by macrosblackd** [comment]
Confirmed - had this happen in my world as well.

**Comment by NEONZARIN** [comment]
+ This 
![image](https://user-images.githubusercontent.com/16442992/62137512-be872800-b2ee-11e9-94f9-4b3d94bb584b.png)

**Comment by Fris0uman** [comment]
It should be fixed by this PR.Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : votagif <notifications@github.com> Date : 30/07/2019  16:24  (GMT+01:00) À : CleverRaven/Cataclysm-DDA <Cataclysm-DDA@noreply.github.com> Cc : Fris0uman <sthapplz@gmail.com>, Author <author@noreply.github.com> Objet : Re: [CleverRaven/Cataclysm-DDA] Disapearing Autoclave (#32670) 
This



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CleverRaven/Cataclysm-DDA/issues/32670?email_source=notifications\u0026email_token=AJ3BNLABMEXOQBMCV57XXBLQCBFILA5CNFSM4IHKSC62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3EEOHA#issuecomment-516441884",
"url": "https://github.com/CleverRaven/Cataclysm-DDA/issues/32670?email_source=notifications\u0026email_token=AJ3BNLABMEXOQBMCV57XXBLQCBFILA5CNFSM4IHKSC62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3EEOHA#issuecomment-516441884",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Fris0uman** [comment]
The sterile filthy combo will be fixed by the PR that fix this issue.
For the rest I'm making an autocle vehicle part.
