### ISSUE TITLE
Crash when requesting items from NPC

### ISSUE THREAD

**Issue by Petethegoat** [CleverRaven/Cataclysm-DDA#32676]
# Describe the bug
Inconsistent crash presumably based on hitting a certain dialogue response. (or because they try to give me a certain item?)

# Steps To Reproduce
From my save:
Talk to Shauna House, Guard
  c: Anything I can do for you?
  b: A good word might be helpful.
  a: Tell me about it.
  a: I'll do it!
(next, repeat these steps until crash)
  c: Can you share some equipment?
  a: [PERSUADE 34%] Because I'm your friend! - Will crash on this line, eventually, as long as she doesn't actually give you anything.
  a: Okay, okay, sorry.

# Screenshots
Don't think there's anything here that isn't going to be evident from the description/log, but here's a screenshot.
![image](https://user-images.githubusercontent.com/734762/61999851-ddd44a00-b08f-11e9-911a-168628f8fb6c.png)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version (windows 7, x64)
- Game Version: 0.D-5917-g5f27169 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    More Survival Tools [More_Survival_Tools],
    Pete's Megamod [PG_Megamod],
    sees-player icon, -attitude [sees_player_less_attitude]
]

# Additional context
Save file and config/debug logs:
[npc_persuading_crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3438652/npc_persuading_crash.zip)

"Pete's Megamod" is my personal mod that just adjusts long grass so it doesn't spam me with messages. No relevant changes for this.

**Comment by hexagonrecursion** [comment]
I could not reproduce this bug with clang undefined behavior and address sanitizers. Note: I do not have More_Survival_Tools or PG_Megamod

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-2004-gada3852d39 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No name () [],
    No name () []
]
