### ISSUE TITLE
Infection recovery's "pass out" interruptions are tedious and annoying

### ISSUE THREAD

**Issue by jeremyshannon** [CleverRaven/Cataclysm-DDA#32672]
# Describe the bug
Recovery must be waited out, but passing out from it cancels all actions, and happens constantly, for days on end.

Infection and recovery includes a mechanic wherein you pass out at random times. This is frightening when you're infected and desperately searching for royal jelly or more antibiotics, but during recovery from infection, it becomes very irritating. Passing out and waking up can interrupt any action -- reading, waiting, crafting, sleeping, anything, and force you to restart it by hand. It can happen every 4-5 minutes, and the recovery period can last for three days, possibly more.  That's like 800 interruptions, followed by several keypresses to re-start whatever you were trying to do to pass the time, before you can start playing the game properly again.

# Steps To Reproduce

Get infected, get it cured without royal jelly. Enjoy passing two or three days waiting out your recovery, in roughly five minute intervals, telling it to restart, over and over again.

# Expected behavior

It should be possible to auto-resume your last action (reading, crafting, trying to sleep) when you pass out during it, we already have safe mode warnings for the case where a monster shows up while you were unconscious. I'm not sure the long recovery duration is a great idea, either, but that's a minor thing.
 
# Versions and configuration

Current master

# Additional context
I experienced this when I played a few days ago, and this guy just reminded me:
https://www.reddit.com/r/cataclysmdda/comments/ciawxy/recovering_from_infections_is_tedious/

**Comment by sammy202020** [comment]
yea i understand the reasoning behind the passing out but its stupid annoying once your cured to deal with it non stop for 2-3 days

**Comment by kazimuth** [comment]
Where is this effect actually implemented anyway? It looks like it used to be [here](https://github.com/CleverRaven/Cataclysm-DDA/commit/941ffacf6d5b1da50f91e248ab39d57d654a575d#diff-dc52f162280289dd2d4d97d82658362dR6859-R6865) but now that code's gone mysteriously missing

**Comment by jeremyshannon** [comment]
It's over in player_hardcoded_effects now.

**Comment by Arjan219** [comment]
This is still happening in 0.D-7694-g1b96c6f.
The constant nausea makes eating and drinking nearly impossible and you're sooner to die from dehydration than the actual infection.
Also i noticed that the pain during recovery can't be managed by painkillers.

**Comment by Night-Pryanik** [comment]
> The constant nausea makes eating and drinking nearly impossible

This is happening IRL too, you know.

**Comment by Berkyjay** [comment]
This is still happening.  I literally can't do anything in the game right now due to being in "recovery" which is causing every action I take to be interrupted.
