### ISSUE TITLE
Batteries drop on the floor instead of cargo.

### ISSUE THREAD

**Issue by MechaJeb** [CleverRaven/Cataclysm-DDA#32674]
**Is your feature request related to a problem? Please describe.**  
When I reload a tool that uses batteries, while standing over a cargo container with (or without) a recharging station, and pick 'Drop item' it drops on the ground, instead of the cargo.

**Describe the solution you'd like**  
For the battery to be dropped in cargo instead.

**Additional context**  
The storage container was not full. I did see a couple of other github issues mentioning this behavior from '18, then later saying this is no longer happening, but I guess this got un-fixed somehow along the way.

Thanks <3

**Comment by RarkGrames** [comment]
#30327 is also about this.
