### ISSUE TITLE
"Inactive dispatch" cant be dissasembled.

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#32680]
Broken dispatch can be dissasembled, inactive one can not. Just shot one with an EMP grenade and it became friendly.

If you need suggestions for the results, I'd just add 2 each of tear gas, grenades and C4 to the "broken dispatch" drops.

**Comment by roaringjohn** [comment]
I'd suggest this go with the mod "Salvaged Robots", in the form of a recipe with "reversible" set to "true". This would make it more in line with what's already in place.

**Comment by kevingranade** [comment]
Crafting recipes are now reversable.
