### ISSUE TITLE
Autoclave as vehicle part.

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#32688]
**Is your feature request related to a problem? Please describe.**  
Currently, the autoclave drains massive amounts of charges from batteries and when it runs out you have to start all over again, this means that to sterilize your CBMs you have to babysit the autoclave replacing batteries before it runs out.

**Describe the solution you'd like**  
Have the autoclave be installable in a vehicle so it can drain storage batteries power instead so the player can have the autoclave do its thing while they go do something else, just like with the washing machine.

**Describe alternatives you've considered**  
Leaving it as is which is terrible, lowering the autoclave's power consumption which will probably get rejected.

**Additional context**  
N/A

**Comment by kevingranade** [comment]
Sure, but this doesn't warrant an issue.
