### ISSUE TITLE
Smoking rack won't accept certain fruits

### ISSUE THREAD

**Issue by RarkGrames** [CleverRaven/Cataclysm-DDA#32698]
# Describe the bug
The smoking rack won't accept certain fruits for dehydration, while those fruits are part of the "sweet_fruit" crafting requirement group, and can be used for manual dehydration in the crafting menu.

The list:
Both normal and irradiated version:
- Banana
- Cherry
- Grapefruit
- Cranberry
- Elderberry
- Kiwi
- Mango
- Melon
- Orange
- Mulberries
- Papaya
- Pineapple
- Plum
- Pomegrenate
- Watermelon

The smoking rack takes irradiated pears for dehydration, but it doesn't take normal pears.

# Steps To Reproduce
Spawning in the fruits and trying to load the rack

# Expected behavior
They can be dehydrated just like with the crafting recipe

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-5942-g666b2ec [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Flaming Weapons [no_flaming_weapons],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    No Filthy Clothing [no_filthy_clothing]
]

**Comment by int-ua** [comment]
#27943

**Comment by Night-Pryanik** [comment]
> The smoking rack takes irradiated pears for dehydration, but it doesn't take normal pears.

Tested - the situation is right the opposite: normal pears are accepted, while irradiated don't. I fixed this in the PR.

**Comment by RarkGrames** [comment]
I didn't realize that smoking was solved with .json, otherwise I would have fixed it. Thanks for doing it anyway @Night-Pryanik.

**Comment by Night-Pryanik** [comment]
You're welcome.
