### ISSUE TITLE
Tree cutting fatigue is too high

### ISSUE THREAD

**Issue by battlepants86** [CleverRaven/Cataclysm-DDA#32701]
I've noticed that I have been getting very sleepy while cutting down trees. Found that this seems to scale upwards if the tree cutting quality goes up.

Steps to reproduce:
Electric chainsaw (tree cutting quality 4), cut down a few trees and you will be ready for bed, despite not much time being spent.

More extreme example:
C.R.I.T hatchet (tree cutting quality 10), cut down a few trees and you will be dead tired within 5 minutes. 

Expected result:
I'm thinking this should be hitting stamina more than fatigue - perhaps the wrong variable was used here?

Build in use: 
9387

Mods in use:
[
  "dda",
  "aftershock",
  "crt_expansion",
  "magiclysm",
  "craftgp",
  "growable-pots",
  "ew_pack",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "hydroponics",
  "MMA",
  "national_guard_camp",
  "more_locations",
  "FujiStruct",
  "deoxymod",
  "blazemod",
  "Tanks",
  "no_religious_Texts",
  "No_Explosive_Zombies",
  "No_Acid_Zombies",
  "manualbionicinstall",
  "no_reviving_zombies",
  "safeautodoc",
  "novitamins",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills"
]

Let me know if any further details are needed or if a copy of my world is desired.

**Comment by EvgenijM86** [comment]
With 1 second turn the game is very generous with the time it gives you per day. You can easily collect significantly more food than you will ever need. Being tired from chopping trees is at least one way that the game forces you to burn some time and some food.
