### ISSUE TITLE
Magiclysm: Inhuman Intelligence causes max mana integer overflow

### ISSUE THREAD

**Issue by Walkastray007** [CleverRaven/Cataclysm-DDA#32716]
# Describe the bug

Extremely High Intelligence causes integer overflow on max mana.

# Steps To Reproduce

0. Debug Menu > Mutate > get traits 'Greater Mana Efficiency' and 'Greater Mana Sensitivity'
1. Debug Menu > Player > set stat intelligence to 200 million
2. Observe your -2.17 billion max mana

# Expected behavior

I expect a proper number, that doesn't go into the negative.

# Easy Fix

Just change the max mana and mana value types to Long or Double.

# Screenshots

![IntegerOverflow](https://user-images.githubusercontent.com/51843249/62018000-0fbfdc00-b176-11e9-8824-f7c4412f8328.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-5942-g666b2ec [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]
]

# Additional context

N/A

**Comment by KorGgenT** [comment]
This... isn't really a bug. you're not supposed to have intelligence this high, and we don't support unintended results due to debug commands like settings stats.
