### ISSUE TITLE
Beaded curtains are impenetrable to furniture

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#32718]
# Describe the bug

Beaded curtains, even when open, prevent furniture from being pushed/pulled through it. While I understand the beads can be a bit awkward and can get all up in your face, I once built up the courage to carry a chair through a beaded curtain iRL.

# Steps To Reproduce

1. Find a beaded curtain
1. Open it.
1. Grab a nearby furniture (rubbish bin, chair, etc)
1. Try to move the furniture through the curtain.

# Expected behavior

Beaded curtains allow furniture to pass through, at least when open.

# Versions and configuration

Ubuntu 16.04, with tiles, on 5a6303b7d064d8601756789962b2a1d449a652ac.

# Notes

I suspect this is because beaded curtains are furniture, whereas regular doors are tiles.

**Comment by brannamm** [comment]
This probably also applies to canvas flaps since they are furniture + doors.

**Comment by Night-Pryanik** [comment]
> I suspect this is because beaded curtains are furniture, whereas regular doors are tiles.

This is it. You can't have two types of furniture on the same tile.
