### ISSUE TITLE
Cannot see wall that should clearly be in view

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#32712]
# Describe the bug

External walls to a lab are shown as "unknown", even though they are clearly in view.

# Steps To Reproduce

1. Open the attached save.
1. Notice the walls to the south block line of sight, but are not visible.

# Expected behavior

Survivors can see walls in plain view.

# Versions and configuration

- OS: Ubuntu 16.04 LTS 
- Game Version: 666b2ec9ecdf7ecf1bc5fa40a6f8b1d0274e4372 with MSX tilesets applied.
- Graphics Version: Tiles
- Mods loaded:
    - Dark Days Ahead [dda],
    -    Disable NPC Needs [no_npc_food],
    -    Filthy Clothing [filthy_morale],
    -    Alternative Map Key [alt_map_key],
    -    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    -    sees-player icon, +attitude [sees_player],
    -    Modular Turrets [modular_turrets],
    -    Salvaged Robots [Salvaged_Robots],
    -    Sleep Deprivation [sleepdeprivation],
    -    Bionic Slots [cbm_slots]

# Additional context

Savefile attached.

- [save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3439740/save.zip)

**Comment by Hirmuolio** [comment]
Same as #31851

**Comment by pjf** [comment]
D'oh, it is! Thanks @Hirmuolio.

Closing issue as dupe.
