### ISSUE TITLE
Magiclysm: debug menu 'Level a spell' crashes game

### ISSUE THREAD

**Issue by Walkastray007** [CleverRaven/Cataclysm-DDA#32715]
# Describe the bug

When using the Debug menu, trying to set a spell's level with a max of 30+ to an integer greater than 28 makes the game go unresponsive, in which it never recovers.

# Steps To Reproduce

0. Create world and character
1. Use Debug Menu > Player > 'Unlock all Spells'
2. Open Debug Menu > Player > 'Level a spell'
3. Attempt to set a spell's level in which the max is 30+, to a number greater than 28.

# Expected behavior

I expected the spell's level to be set to the value. 'cuz because.

# Screenshots

Right before crash.
![Before](https://user-images.githubusercontent.com/51843249/62017557-64faee00-b174-11e9-9edb-af515673ec47.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-5942-g666b2ec [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]
]

# Additional context

It didn't leave a crash log.

Debug log:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3439934/debug.log)

Save file:
[Pond Creek.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3439935/Pond.Creek.zip)

**Comment by ZhilkinSerg** [comment]
Cannot reproduce on latest master with provided save or new world.
