### ISSUE TITLE
The material check of bow scope recipe is illogical

### ISSUE THREAD

**Issue by gearforcer** [CleverRaven/Cataclysm-DDA#32711]
# Describe the bug

When I try to make a bow scope, even if I just got two high-quality lens, the recipe getting highlight in the craft list. Hit “enter”, Absolutely it report a bug.
Then I try to do it with three high-quality lens, it shows "you need another one", even if you got another one in hand, the dialog box repeats over and over again.
So I try to do it with two high-quality lens and a small high-quality lens, It finally works.
# Steps To Reproduce

1. Craft a bow scope with three high-quality lens, with recipe highlight, it report a bug and always shows "needs another one".
2. Do it with only two high-quality lens, recipe got highlight, absolutely illogical
3. Do it with two high-quality lens and a small one, done.
# Expected behavior

1.Two high-quality lens and a small one should be OK.
2.Three high-quality lens should also be OK.
3.Only two high-quality lens shouldn't be OK, the recipe shouldn't get highlight.

# Screenshots

![two](https://user-images.githubusercontent.com/42244110/62015024-6a8b1f00-b1da-11e9-80ad-c41b36572b52.png)

# Versions and configuration

 - OS: [Windows 10]
 - Game Version: [0.D-5939-g7a6b00b]
 - Graphics version: [Tiles]
 - Mods loaded: [DDA, Disable NPC Needs, Icecoon's Arsenal, Garden Pots]

**Comment by kasanryukin** [comment]
Per point 2, recipe highlights because technically you meet the requirements of needing 2 of 2 lenses, AND 1 of 1 lenses.  Your stack of two evaluates true for parts.

**Comment by gearforcer** [comment]
> 根据第2点，配方突出显示，因为从技术上讲，您可以满足2个镜头中的2个和1个镜头中的1个的要求。对于这两个部分，您的两个堆栈评估为true。

Highlight will be misleading,  it will lead player to a BUG and things never be done.

**Comment by NoLongerBreathedIn** [comment]
> Per point 2, recipe highlights because technically you meet the requirements of needing 2 of 2 lenses, AND 1 of 1 lenses. Your stack of two evaluates true for both parts.

Ah, I see. This is coded as and, when it's really tensor. This isn't going to be an easy fix, I can tell.
