### ISSUE TITLE
Pick up and drop items your not supposed to

### ISSUE THREAD

**Issue by Daedracian** [CleverRaven/Cataclysm-DDA#32728]
# Detailed description of bug

every-time you press a movement key your character and and the items beneath them come with you, like the move all option in the advanced inventory. i don't know whether movement or items are getting moved first it just moves the moment you do.

# Steps To Reproduce

1. wield a telescoping umbrella
2. pickup and wield survivors map (unread) get prompt
3. choose to drop the telescoping umbrella
4. read survivors map
5. pickup and wield tourists map (unread) get prompt
6. choose to drop survivors map (read)
7. read tourists map
8. pickup and wield previous telescoping umbrella get prompt
9. move to the left

# Expected behavior

i expect all items beneath you (so far just maps) to follow you and upon moving over an item it will begin moving with you as well.
the reason i believe this will happen is because i moved 1 to 2 hundred spaces discovered more then the maps were moving with me i checked and double checked because i thought it was funny but tolerable till i noticed i was losing 1-2 minutes a movement.

# Screenshots

i do not believe screenshots are applicable as they can be easily faked

# Versions and configuration

<!-- Please complete the following information; you can now go to:
    - i did not know you could generate a report

 - OS: windows 10
 - Game Version: 0.D
 - Graphics version: Tiles
 - Mods loaded: dark days ahead, disable npc needs, filthy clothing, simplified nutrition, extended realistic guns, makeshift items mod, medieval and historic content, more survival tools, mythological replicas, alternative map key, mutant npcs, Oa's additional buildings mod, urban development, folding parts pack, vehicle editions pack, tanks and other vehicles, (DP_RP) xotto indicators, no fungal monsters, classes and scenarios mod, classic roguelike classes, manual bionic installations, safe autodoc, statsthroughskills

# Additional context

I have not and did not replicate it for two reasons i butchered the used maps to see if changing the item did anything and it did not, reason 2 i don't know how to spawn items.

i ruined what i think was the only to get a save file because i reloaded it and the problem was gone items all did what they were supposed to and sat there without moving even if i walked over them.

it might work generic maps it also might work with just one but i wrote everthing up to the 
first movement, after which i butchered the maps hoping that'd solve it didn't.

i also didn't get any error prompt

i was standing indoors the spaces 1,2,4,7,8 were just flooring tile 5 was me and flooring tiles 3,6,9 were the desk of a motel lobby.

**Comment by Daedracian** [comment]
there is more but it isn't showing

**Comment by Qrox** [comment]
That sounds like item hauling toggle with the '\' key

**Comment by EddiTheBambi** [comment]
What @Qrox said, you must've unknowingly toggled item hauling or there is a bug where it's toggled automatically for some reason.

**Comment by kevingranade** [comment]
I'm going to assume the same, these exact symptoms are what happens if you toggle on hauling.

**Comment by Daedracian** [comment]
ok
