### ISSUE TITLE
Washboard Issue

### ISSUE THREAD

**Issue by QuickFixPony** [CleverRaven/Cataclysm-DDA#32729]
The washboard, when activated with contained water, does not detect the water - however, it does detect water when near an infinite water source.

I am not sure what caused this issue, but you obviously need to use the washboard for this to happen. The container that I initially filled with water and tried to use to clean was a condom.

I expected around 19 water to come up, as that was how much I had collected in containers.

![image](https://user-images.githubusercontent.com/53433363/62046799-33555600-b24c-11e9-9a9d-9d148e2c38eb.png)
![image](https://user-images.githubusercontent.com/53433363/62046831-42d49f00-b24c-11e9-8011-7c847d3ceb70.png)

    - - OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5823-g763c25c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Sleep Deprivation [sleepdeprivation],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by Night-Pryanik** [comment]
Could you please test if water is available if no tags like `(hot)`, `(cold)`, or `(frozen)` is applied to it?

**Comment by QuickFixPony** [comment]
I allowed the water to cool down until it was normal - not hot or cold - but it still did not show up.
![image](https://user-images.githubusercontent.com/53433363/62110633-2db24b80-b2f2-11e9-97ae-6854ec31179c.png)
![image](https://user-images.githubusercontent.com/53433363/62110686-4f133780-b2f2-11e9-8678-e32b3e543b27.png)

**Comment by Night-Pryanik** [comment]
Could you please retest it on ordinary water, not the clean one?

**Comment by QuickFixPony** [comment]
As far as I know I had a single unit of not-clean water upon initially receiving the bug and it did not recognise that previously, but my memory can sometimes be faulty, so I will test that when I can.

**Comment by rgeens** [comment]
I had this issue as well. What happened with me with that I had several plastic bottles and a gallon jug of clean water, theoretically enough water to clean a backpack with a washboard (16 units). However, in the multiclean dialog it showed 0 water. When I put a gallon jug of regular non-clean water next the other jug, the dialog detected the water and would allow the cleaning to continue. When it popped up asking which water to use, it gave both the clean and non-clean water as options. So it appears the multiclean dialog isn't recognizing clean water as water.

**Comment by rgeens** [comment]
Steps to reproduce, using version 0.D:

1. Start a new game in an evac shelter or similar safe space
2. Using the debug menu, spawn 100 plastic water bottles in one corner of the room
3. Spawn 100 plastic clean water bottles in another corner of the room
4. Spawn a washboard, some soap bars and a filthy piece of clothing. Maybe a flashlight if you need light.
5. Go to the corner with the regular water bottles and use the washboard. The multiclean dialog will show 200 available water. 
![Screenshot from 2019-08-14 10-19-37](https://user-images.githubusercontent.com/511604/63005612-2c9a2600-be7d-11e9-8508-456d90eeed7a.png)
6. Go to the corner with the clean water bottles and use the washboard. The multiclean dialog will show 0 available water.
![Screenshot from 2019-08-14 10-19-50](https://user-images.githubusercontent.com/511604/63005675-4a678b00-be7d-11e9-996a-f92e6bbe771d.png)

**Comment by rgeens** [comment]
My steps don't reproduce in the latest experimental build: https://github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-jenkins-b9488/cataclysmdda-0.D-Linux_x64-Tiles-9488.tar.gz (0.D-6523-g9857661). The dialog detects the clean water as available.
