### ISSUE TITLE
Gas Vents in mines don't work anymore.

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#32735]
# Describe the bug

All the Gas Vents in mines, which used to spread toxic gas, no longer spread anything at all.

# Steps To Reproduce

1. Find a mine.
2. Investigate Gas Vents.
3. They broken.

# Expected behavior

Gas Vents spread big green clouds of unhealthy air.

# Screenshots

![Untitled](https://user-images.githubusercontent.com/45204409/62056512-1dc93780-b21e-11e9-89a8-fe9798e8ae87.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5942-g666b2ec [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Flaming Weapons [no_flaming_weapons],
    Bionic Slots [cbm_slots],
    Simplified Nutrition [novitamins]
]

**Comment by kwl01skz** [comment]
Acid vent looks not  work , too (debug)

**Comment by ZhilkinSerg** [comment]
Probable cause #32491, but could be broken earlier.

**Comment by ZhilkinSerg** [comment]
Do you have a savegame to test? Debug spawned gas vents are working and spawn fields (maybe not in same amounts as previously, but still).

**Comment by Bulletfang** [comment]
The savegame is too large, over 500 mb.

**Comment by ZhilkinSerg** [comment]
Zipped?

**Comment by Bulletfang** [comment]
Zipped it's 77 mb, still way over the limit.
I've made a new character in a new world and debugged myself to the next mine, and saved right in front of a broken gas vent, hopefully this is helpful.
[Poplar Bluff.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3445011/Poplar.Bluff.zip)
