### ISSUE TITLE
Segmentation Fault Crash, Zombie Cop

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#32745]
Game crashed with the following message:
![Untitled](https://user-images.githubusercontent.com/45204409/62089853-d917bd80-b26a-11e9-9025-f0439a3a296c.jpg)

There was a similar error message directly prior to this one, something about invalid position because that spot was already occupied or something along those lines, I can't remember exactly.

# Steps To Reproduce

I don't know how to reliably reproduce this crash.

# Expected behavior

No crash, please.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5942-g666b2ec [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Flaming Weapons [no_flaming_weapons],
    Bionic Slots [cbm_slots],
    Simplified Nutrition [novitamins]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3444591/crash.log)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3444592/debug.log)

Save file is too large, over 600 mb, but would be obsolete anyway, because the error can't be reproduced reliably.

**Comment by Leland** [comment]
Without a save file or other means of reproducing this bug, it's gonna be hard to do very much here, unfortunately...

I'm closing this for now – if you or someone else experiences this again, please do ping me here and we'll reopen.
