### ISSUE TITLE
Extend time for fire to catch on to things

### ISSUE THREAD

**Issue by roaringjohn** [CleverRaven/Cataclysm-DDA#32747]
**Is your feature request related to a problem? Please describe.**  
A few times, I've had characters die within seconds just from being set aflame in one turn. This is a common problem, afaik.

**Describe the solution you'd like**  
Extend the time it takes for fire to set things aflame. Gasoline, alcohol and some other flammable liquids (and gases) should still be caught aflame within a second. I recommend adding the ability to douse things with gasoline/alcohol/whatever for purposefully setting things aflame quickly.

**Additional context**  
Nothing solid takes just one second to get caught aflame, not even paper. Paper can be caught aflame within seconds, but not in a single second. Wood takes a rather long time to get caught on fire, as well. I can source this from personal experience, as well as youtube videos that I could provide if need be. Zombies should probably not be capable of being set aflame in seconds, nor fungaloids. Fungaloids and fungus terrain, for balance reasons, should still be much more flammable than other monsters and terrain, though.

**Comment by jeremyshannon** [comment]
Yeah, this seems like something that was reasonable with the 6 second turn, but isn't reasonable anymore.
