### ISSUE TITLE
[FR] Emptying liquids into sinks makes them go away

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#32757]
**Is your feature request related to a problem? Please describe.**

There are often times when I want to dispose of a liquid, but right now anything poured out seems to stick around for a long time.

**Describe the solution you'd like**  

I'd like to be able to empty liquids into sinks and have it go away. This is how sinks work in real life.

**Describe alternatives you've considered**  

Using a mop, but every time I go to get the mop I find I'm distracted by something, and the liquids just sit there mocking me.

**Additional context**  

Players can't (currently) construct sinks, so there's no reality-breaking of sinks being where they shouldn't be.

**Comment by Rail-Runner** [comment]
Sinks should have an option to store liquid (like bathtubs do) in addition to that, I think, with the option to remove all the liquid inside them for both.
