### ISSUE TITLE
Game crashes when completing NPC mission.

### ISSUE THREAD

**Issue by Drack820** [CleverRaven/Cataclysm-DDA#32758]
# Describe the bug
When delivering the 150 stones for the NPC's mission that requires them the game will freeze for  5-10 seconds, then it will give a couple of errors like this:

```
 DEBUG    : Tried to access invalid map position at grid (0,0,-2147483648)
 
 FUNCTION : size_t map::get_nonant(const tripoint&) const
 FILE     : src/map.cpp
 LINE     : 8047 
```

or like this:

```
 DEBUG    : Tried to access invalid map position (11, 17, -2147483648)
 
 FUNCTION : submap* map::get_submap_at(const tripoint&) const
 FILE     : src/map.cpp
 LINE     : 8009
```

# Steps To Reproduce

1. Find an NPC with the mission that requires 150 stones.
2. Accept the mission and get 150 stones.
3. Complete the mission by giving the stones to the NPC.

# Expected behavior
The game should not crash when completing the mission.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5989-g03c9208 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bens GF recipes [Tolerate_This],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    More Locations [more_locations],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    sees-player icon, +attitude [sees_player],
    Bionic Slots [cbm_slots],
    Simplified Nutrition [novitamins],
    StatsThroughSkills [StatsThroughSkills],
    C.R.I.T Expansion Mod [crt_expansion],
    Cars to Wrecks [cars_to_wrecks]
]

# Additional context

World, crash.log and debug.log below:

[World Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3447085/World.Save.zip)
[Debug logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3447086/Debug.logs.zip)

The character has the stones in the inventory, simply talk to the NPC and deliver the stones to replicate the crash.

**Comment by davidpwbrown** [comment]
The only mission I can find thats similar to this, is the Isherwood farm mission to find 120 stones.
I just completed that mission, and the outbuilding was succesfully placed with the kilns.
Cant reproduce

**Comment by davidpwbrown** [comment]
Esotericist confirms in discord, they cannot reproduce either with this save.
appears to have been caused for a brief period of time when Isherwood farm missions were available to dynamic NPCs, and it coudnt find the map special to update, which now fails silently anyway.
