### ISSUE TITLE
Crash to desktop on pressing '@'

### ISSUE THREAD

**Issue by bleaky** [CleverRaven/Cataclysm-DDA#32767]
# Describe the bug

When pressing @ to go to the character screen, the game crashes, giving an error.

# Steps To Reproduce

1. make a character of any kind
2. press @

# Expected behavior

One expects the character screen rather than a crash

# Screenshots

N/A

# Versions and configuration

(note: i couldn't find the above report generator, so i did my best.)

 - OS: Windows 10
 - Game Version: O.D (stable)
 - Graphics version: Tiles (RetroDays)
 - Mods loaded: DDA, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Alternative Map Key, More Locations, Fuji's More Buildings

# Additional context

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3448406/save.zip)

**Comment by Jerakin** [comment]
Added additional info in the comment here https://github.com/CleverRaven/Cataclysm-DDA/issues/32832#issuecomment-517597384

**Comment by ZhilkinSerg** [comment]
Please try to reproduce on latest experimental version. I cannot reproduce it there.

**Comment by Jerakin** [comment]
Can confirm that it works as expected on latest experimental

**Comment by ZhilkinSerg** [comment]
Thanks for confirmation.
