### ISSUE TITLE
Electric jackhammer (UPS) have a battery, while not charging from CBM UPS

### ISSUE THREAD

**Issue by Runeerle** [CleverRaven/Cataclysm-DDA#32774]
The electric jackhammer (UPS) can not be powered via the bionic UPS system. At least when you have less than 3.5k bionic power (untested with 3.5k+).

One or more of the following changes might work:

* Remove the battery since its UPS after all, but the power usage can't be 3.5k then.
* Make it non-UPS, using the new battery system.
* Keep the battery, but allow charging and/or trickle charging from UPS sources. Ideally with some ways to prevent it from draining all your bionic power while having other UPS powered items active (mp3, light, guns).
* Fire the UPS marketing people.
* Make a UPS-Heavy standard (UPS-H) for power intensive systems with internal batteries, and make it clear that the bionic UPS do not support it.
* Make a UPS-Charge standard (UPS-C) for systems with internal batteries, with support for controlling recharge from an UPS source (power options: off, internal battery; external UPS only; trickle charge; fast charge; auto). Auto might use a priority system intended to work for people that don't care.

# Versions and configuration
- OS: Windows 7
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-5823-g763c25c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by Petethegoat** [comment]
I think this has been resolved in the past week. Could you try and reproduce it on the latest experimental build?

**Comment by Runeerle** [comment]
In the latest version the electric jackhammer do charge its battery, but it drain my tiny bionic reserve very quickly. Implementing some controls for this will be very nice. Either a charge rate setting on the tool, or a setting in the UPS source when used for charging. A reserve setting like 0/25/50/75% that is controlled from the bionic control meny sounds excellent.

**Comment by Zireael07** [comment]
Electric jackhammer has a massive power requirement (which is realistic). That said, a reserve setting on the UPS itself makes perfect sense, too.

**Comment by int-ua** [comment]
Please add a new issue or feature request, the OP issue looks resolved.
