### ISSUE TITLE
Crafting an anvil is not possible since it have a circular dependency (no surface access)

### ISSUE THREAD

**Issue by Runeerle** [CleverRaven/Cataclysm-DDA#32777]
Crafting an anvil requires an crucible. Crafting a crucible requires a steel frame. Crafting a steel frame requires a crucible.

When you don't have any cars available (lab start, and no way to escape via normal stairs) this becomes a barrier. I can make rail rifles, mp3 players and 200L steel drums, but not basic metal tools. Some more makeshift ways to make something so simple is needed, even if it requires several steps. 

It seems the simplest realistic fix is to make steel frame craftable from sheets of metal, pipes, wires, chunks of steel, lumps of steel and/or scrap metal. The exact materials needed should be more expensive in the sense it use more refined materiales than the current recipe.

- OS: Windows 7
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-5823-g763c25c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by anothersimulacrum** [comment]
You can make a clay crucible.

**Comment by curstwist** [comment]
You can make a clay crucible

**Comment by I-am-Erk** [comment]
I'm not certain that it needs to be possible to bootstrap everything from within a single building. I'm not all that convinced you could build a blacksmithy from scratch from within an abandoned underground laboratory.

**Comment by Runeerle** [comment]
I can't find any clay here, so its not an option. Still, making a steel frame sounds reasonable without using a crucible. But you can't use only scrap metal to do so of course.

**Comment by I-am-Erk** [comment]
A steel frame isn't really something that can be made from cobbled together scraps, it represents a very solid chassis.

There's a good argument that a steel frame is  a strange component for a crucible... But I don't think any more realistic alternatives are likely to be *more* craftable or accessible. Really the bootstrapping of a smithy from scrap bits is *waaaay* too easy already as far as I can tell from reading about it

**Comment by shadowsapex** [comment]
Can't you get steel frames in labs by disassembling heavy machinery?

**Comment by kasanryukin** [comment]
> I'm not certain that it needs to be possible to bootstrap everything from within a single building. I'm not all that convinced you could build a blacksmithy from scratch from within an abandoned underground laboratory.

David Gingery would like to spread the good word to you about building a machine shop starting with just sand/rock/cement, scrap metal, and some charcoal.

**Comment by kasanryukin** [comment]
> Can't you get steel frames in labs by disassembling heavy machinery?

Yes. And you can find them in crates.

**Comment by I-am-Erk** [comment]
I think regardless of questions of the crafting of crucibles, the fact that frames are available in labs is enough to close this specific issue
