### ISSUE TITLE
Vehicle Welding Rig powered through another vehicle using cable not usable as repair station

### ISSUE THREAD

**Issue by Muffindrake** [CleverRaven/Cataclysm-DDA#32771]
# Describe the bug

It's not possible to use the welding rig to repair things at all when installed into a vehicle powered by another vehicle through a cable. The option to 'use' the welding rig never comes up when examining it.

# Steps To Reproduce

1. Create vehicle with charged battery/ies
2. Create another vehicle with no batteries, install vehicle welding rig into it
3. Connect the vehicles using a heavy duty cable, put the heavy duty cable end on the powerless vehicle on the same tile as the welding rig
4. Attempt to examine the tile that the welding rig was installed into

# Expected behavior

Being able to repair at all using the welding rig. It will still be usable for crafting.

# Versions and configuration

 - OS: Gentoo Linux
 - Game Version: 0.D-6009-ged290b3a24
 - Graphics version: Terminal (urxvt)
 - Mods loaded: Magiclysm, Garden Pots, DeadLeaves' Fictional Guns, Makeshift Items Mod, Icecoon's Arsenal, More Survival Tools, Mythological Replicas, Crazy Cataclysm, Hydroponics, Mythical Martial Arts, Safe Autodoc

**Comment by chphilli** [comment]
I noticed a similar thing with components added via the new bike racks feature. I added a detachable welding rig to my RV but while it's connected I'm unable to actually use the welder until I detach it. Seems like it could be possibly related?

**Comment by Night-Pryanik** [comment]
#34325 should've fixed this.
