### ISSUE TITLE
Fabric materials affecting resistances (ex. || trenchcoat (nomex))

### ISSUE THREAD

**Issue by EddiTheBambi** [CleverRaven/Cataclysm-DDA#32785]
**Describe the solution you'd like**  
Generic `yard of fabric (material) [charges]` item that could have different fabric materials associated with it, e.g. cotton, velvet, nomex... that upon crafting would have the clothing item inherit the material which would modify the properties of the item (increase fire/environmental resistance, make it fancy) etc.

**Describe alternatives you've considered**  
Leaving the current system for simplicity, though the above would add much to the current tailoring system.

**Comment by Fris0uman** [comment]
How would the recipe work for something currently made of several materials?

**Comment by kevingranade** [comment]
You haven't made a case for why this would improve the game.  Your example
of a nomex trenchcoat is a great example of why this is a problematic idea,
you can't just swap out nomex for cloth or leather in a trenchcoat and have
it just work.

**Comment by EddiTheBambi** [comment]
> You haven't made a case for why this would improve the game.  Your example
of a nomex trenchcoat is a great example of why this is a problematic idea,
you can't just swap out nomex for cloth or leather in a trenchcoat and have
it just work.

Would extending the "pad with kevlar system" be a preferable alternative in that case then? The motivation behind this idea was that you could customise your gear more to your needs and/or preferences by making it look fancier or function better in certain situations without having to swap out pieces of your gear to jigsaw-puzzle a loadout. Essentially increasing player choice.

> How would the recipe work for something currently made of several materials?

I'm thinking we'd need to assign a crafting component as the "main component" when crafting and derive the material from that

**Comment by kevingranade** [comment]
No, that's not a reasonable thing to do for the same reason. I'm not aware of a way to evaluate what the impact of adding additional material layers to an article of clothing should be.  There are already some pretty nonsensical results that occur based on this system, I'm much more likely to reign it in further than to expand it.
