### ISSUE TITLE
Horses hum and make other engine noises when attached to a wagon

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#32791]
# Describe the bug

Horses make humming noises when used to drive a cart. Other messages also also refer to the horse as an engine ("you hear the engine start up").

# Steps To Reproduce

1. Attach a horse to a cart.
1. Drive the cart.
1. Vroom vroom!

# Expected behavior

Horses go 'clip-clop' or 'neigh'.

# Versions and configuration
- OS: Ubuntu 16.04 LTS
- Game Version: f95875f3eea4403333379d8a6d6e848c9d2ab837 with #32754, #32782 and MSX tiles applied.
- Graphics Version: Tiles
- Mods loaded:
```
    Dark Days Ahead [dda],
    Filthy Clothing [filthy_morale],
    Alternative Map Key [alt_map_key],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Sleep Deprivation [sleepdeprivation],
    Bionic Slots [cbm_slots],
    sees-player icon, -attitude [sees_player_less_attitude]
```

**Comment by EddiTheBambi** [comment]
https://www.youtube.com/watch?v=cJ5WN3yyEHc

**I am an engine HURRRR DURRRRR**

Worth noting: pretty sure `yoke_harness`, being the engine, is the source of those sounds and not the horse.

**Comment by pjf** [comment]
Well dang, clearly I didn't know this behaviour is 100% realistic for horses.

**Comment by Inglonias** [comment]
I think we close this without fixing it because it's really damn funny.

**Comment by l29ah** [comment]
Seems fixed now.

**Comment by l29ah** [comment]
I take it back: horses do hum, but only when you "start the engine", "let go of controls" and stand near them.
