### ISSUE TITLE
Being wet should make you get cold easier

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#32799]
Getting wet only produces morale penalties. The game is now modeling wind, and yet being wet doesnt make you lose temperature faster. This could be handled in many complex ways, considering how much water you absorbed, the ambient temperature, etc. But someone proposed in the discord a simple solution: Make being wet halve the "Warmth" level of your gear (that is not "Wet positive").

**Comment by gearforcer** [comment]
But we don't have suitable equipment to resist the rain as far. It doesn't work even with a raincoat

**Comment by l29ah** [comment]
I think wet clothes already have a penalty to warmth.

**Comment by Hirmuolio** [comment]
`warmth *= 1.0 - 0.66 * body_wetness[bp] / drench_capacity[bp];`
(`warmth` is the warmth of single worn item)

Fully wet clothes reduce cloth warmth by 66%. Being wet only reduces the effectiveness of worn clothes. It will not make you "colder".
Also wool items receive absolutely no penalty for their warmth.

----

Also wetness for frostbites:

`wetness_percentage = 100 * body_wetness[bp] / drench_capacity[bp]`

`Ftemperature = player_local_temp + warmth( bp ) * 0.2 - 20 * wetness_percentage / 100`

(those 100 * and / 100 seem to be unnecessary. temperatures in F probably)

If you are 100% wet it is same as if you were dry at 20 F cloder temperature. I guess this is the reason why players get frostbites when it isn't even close to freezing temperature.

----

* The penalty probably shouldn't be linear. Being even slightly wet is bad when it is cold.
* Being wet should effectively cool you below enviroment temperature.
* Wet clothes should be worse the colder it is.
* Wind should probably make wet penalties even worse. Wet clothes in wind is really bad for your warmth.

**Comment by Svankensen** [comment]
My bad then, we discussed it in discord and nobody knew it was a thing, incluying some devs. Maybe we should add some mentions in the log?
