### ISSUE TITLE
Make using hoods, pockets and collars an action, rather than automatic

### ISSUE THREAD

**Issue by FuelType-Memes** [CleverRaven/Cataclysm-DDA#32790]
**Is your feature request related to a problem? Please describe.**  
At the moment, if you're wearing a hoodie and nothing on your head your character automatically puts on the hood, but the moment you try to put on a fur hat, your hood is no longer used. This also leads to the possibility of adding more actions, like "unzip your windbreaker" to reduce it's warmth level and so on

**Describe the solution you'd like**  
An ability to (a)ctivate an article of clothing to bring up a menu with possible actions, for example:
1. Put on the hood (greyed out if head enc is too high)
2. Put your hands in pockets (prompts the unwield menu if you have anything in your hands)
3. Put the collar up

For 1 and 3 if you're already wearing something on that layer, that prevents you from wearing a second piece of clothing on that layer - make it greyed out

Maybe instead of creating multiple items for clothes, like "jacket (collar up, hood down), jacket (collar down, hood up)", modify it's coverage? So jacket with (torso, arms) becomes jacket with (torso, arms, head) when the hood is up?

**Describe alternatives you've considered**  
Leaving it as is and suffering during winter times

**Additional context**  
Leaving in a cold country showed me, that nothing stops you from wearing multiple hoods over your wool hat to increase your chances of making it home without freezing your ears off, sticking your hands in your pockets while wearing mittens to prevent your fingers from falling off and popping the collar in an attempt to stop the wind from penetrating your scarf and blowing off the skin off your throat

**Comment by Hirmuolio** [comment]
I was just thinking to suggest the opposite: Making other adjustable clothes automatic like hoods and pockets.

I don't think using-not using hood or pockets is a meaningful choice for the player. if it is cold then using the hood is good with no doubt. I think player should not be presented with choices where there is no decision to make and they should just be done automatically.

The using hood check could be made to allow hood usage even when the head has something worn on certain layers or up to certain encumburance.

**Comment by kevingranade** [comment]
I think you have your criteria for when a hood is usable mixed up with how using it is triggered.
> The using hood check could be made to allow hood usage even when the head has something worn on certain layers or up to certain encumburance.

This is a totally reasonable thing to do, there's no reason to move activation to a menu.
