### ISSUE TITLE
Impossible to continue interrupted deconstruction of a road barricade

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32809]
# Describe the bug

`e`xamining it results in rolling over it.

0.D-6053-g29927d7995-dirty

[2019.07.22.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3455952/2019.07.22.zip)

**Comment by anothersimulacrum** [comment]
Confirmed
![confirm](https://user-images.githubusercontent.com/42699974/63537436-42ef5400-c505-11e9-8ba9-4ff829c61a48.gif)

**Comment by alkemann** [comment]
Unable to reproduce on master here.

**Comment by ZhilkinSerg** [comment]
Can't reproduce either. Please ping to reopen if that's still an issue.

**Comment by anothersimulacrum** [comment]
Seems I accidentally fixed this in #34039

**Comment by ZhilkinSerg** [comment]
Damn accidental bugfixes!
