### ISSUE TITLE
start day and time are grossly inaccurate

### ISSUE THREAD

**Issue by Kirefire** [CleverRaven/Cataclysm-DDA#32803]
# Describe the bug

game start day and time are different in comparison to the options in the world config menu by being 9 days ahead of schedule and time being 12 am

# Steps To Reproduce

1. Create a new world or view a previously existing world's initial time and date config.
2. Create a new character (preferable with a timepiece) and see the date and time being incorrect.

# Expected behavior
to work as before build 9392

# Screenshots

![world start](https://user-images.githubusercontent.com/20845317/62259613-c664cc00-b3c3-11e9-8984-e4bb96f7baf7.PNG)

# Versions and configuration

 - OS: windows 10
 - Game Version: 0.D-6053-g29927d7
 - Graphics version: Tiles
 - Mods loaded: Dda, no npc needs.

# Additional context

**Comment by macrosblackd** [comment]
Confirmed - Happening on my new starts as well.

**Comment by misterprimus** [comment]
For me it happens with chopper crash, but not with random character.

**Comment by esotericist** [comment]
I'm able to reproduce this. Investigating.
