### ISSUE TITLE
Challenge start: Stuck in a skyscraper

### ISSUE THREAD

**Issue by FuelType-Memes** [CleverRaven/Cataclysm-DDA#32802]
**Is your feature request related to a problem? Please describe.**  
The recently added by awesome @Night-Pryanik "Prison Island" scenario added a great challenge, where you're stuck in a limited space with limited resources in the middle of a body of water. You can see that the freedom is so close, yet so far and you must use what resources you have to reach that freedom. That got me thinking about a scenario, where you're stuck in the middle of a city, but that city is unreachable to you - you're an unlucky survivor, who was left behind on the helipad on top of a skyscraper (or just high-rise). Your only way to escape is down. You must survive on what food and resources you find while scavenging supplies from the flats and office spaces. Maybe make a couple of floors unreachable because of collapsed stairs, meaning you have to go down via rope/ladder/jumping

**Describe the solution you'd like**  
Generate a very high apartment tower, make you start on top. Starting professions are usual city dwellers

**Describe alternatives you've considered**  
Not adding such scenario?

**Additional context**  
Might be a cool scenario to showcase, test and optimize z-levels?

**Comment by ZhilkinSerg** [comment]
We kinda already have this scenario - <https://github.com/CleverRaven/Cataclysm-DDA/pull/30678>

**Comment by kevingranade** [comment]
Feel free to add more, but the existing scenario already substantially implements the suggestion.
