### ISSUE TITLE
Please change the memorised area from brown to the old gray

### ISSUE THREAD

**Issue by gearforcer** [CleverRaven/Cataclysm-DDA#32807]
**Is your feature request related to a problem? Please describe.**  
In recent experimental game build, the color of memorised area has been changed to brown,  that makes most player terrible as i known.

**Describe the solution you'd like**  
I strongly suggest that we should change the color of memorised area from brown to the old gray.

**Comment by Zireael07** [comment]
An option is coming, that will let you choose between gray and sepia.

**Comment by ZhilkinSerg** [comment]
Revert to build 9386 or wait until build with #32713 is merged.
