### ISSUE TITLE
Light amp goggles don't use battery charges

### ISSUE THREAD

**Issue by Krisu001** [CleverRaven/Cataclysm-DDA#32814]
# Describe the bug

The light amp goggles basically don't use any charges or use them extremely slowly. I'm not sure whether this is intended or not.

# Steps To Reproduce

1. Get light amp goggles.
2. Reload with battery with charges.
3. Activate it.
4. Wait for a long time, like 6 hours. 

# Expected behavior

I slept for about an hour in game, and I thought the charge would go down but it didnt. 

# Screenshots

![Screenshot_20190801-070832_Cataclysm DDA](https://user-images.githubusercontent.com/49415093/62292277-ba145980-b42b-11e9-84a0-891aac56df70.jpg)

![Screenshot_20190801-070844_Cataclysm DDA](https://user-images.githubusercontent.com/49415093/62292313-c5678500-b42b-11e9-9e75-9685ad5f1620.jpg)

# Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G960U; Release: 9; Incremental: G960USQS5CSEA; 
- Game Version: 0.D-6053-g29927d7 [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    No Survivor Armor [no_survivor_armor],
    Classes and Scenarios Mod [more_classes_scenarios],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    NPC traits [npc_traits],
    Bens GF recipes [Tolerate_This],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Bionic Slots [cbm_slots]
]

**Comment by ymber** [comment]
See #30656

This system works as intended and we're working on improving it. They do actually draw power, but because their power draw is 375mW and a cata battery unit is 1kJ you'll only notice over longer periods. Also because of how I had to implement power draw to work with integer kJ units it's chance based whether it consumes a charge on any given turn, so they wont necessarily draw power at a consistent rate.

See also #32067
