### ISSUE TITLE
The spray-can flamethrower should start filled.

### ISSUE THREAD

**Issue by Xenomorph-III** [CleverRaven/Cataclysm-DDA#32829]
**Is your feature request related to a problem? Please describe.**  

The spray-can flamethrower is meant to be a disposable weapon, as logically, repressurizing a spray-can is impossible.

In addition, the spray-can flamethrower is unloaded when crafted. Where did the paint go?

**Describe the solution you'd like**  

The spray-can flamethrower should start filled with 'spray paint', (or even just gasoline) a new ammo type unobtainable by unloading. This could be accomplished with the "NO_UNLOAD" flag. I believe this could be done by setting its initial charges to 100.

To keep things consistent, I would increase the spray can's capacity to 100 and set the "charges_per_use" to 10.

**Describe alternatives you've considered**  

- Implement spray cans as magazines

**Additional context**  

I believe that the spray can flamethrower is already not reloadable.

**Comment by LaVeyanFiend** [comment]
> I believe that the spray can flamethrower is already not reloadable.
It's not reloadable **with gasoline** due to an adjustment to ``ammo_type`` breaking the use of both it and napalm. Bug is acknowleged as #32484.

**Comment by ZhilkinSerg** [comment]
Duplicate of #32484.
