### ISSUE TITLE
Wooden bodkin arrows/bolts are strictly worse than broadhead versions for high damage bows and crossbows.

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#32826]
**Is your feature request related to a problem? Please describe.**  
Wooden bodkin arrows/bolts do 1.12 times the damage + 3 armor piercing against armored enemies. Broadhead versions do 1.25 times the damage + 1 armor piercing. 

Solving 1.12x+3 - (1.25x+1) = 0 for x gives x = 200/13 ~= 15, i.e. for all weapons that do over 15 damage the bodkin versions are strictly worse, even against armored enemies. 

The affected weapons are:

crossbow - 17 damage
compound bow (medium/high)= 18/22 damage
composite crossbow - 20 damage
wooden greatbow - 20 damage
pneumatic bolt driver - 20
compound crossbow - 28 damage
compound greatbow - 40 damage
heavy crossbow - 50 damage

Bodkin arrows should be better against armored enemies for all weapons.

**Describe the solution you'd like**  

It's tricky as the damage from bows/crossbows range from 4 for the short bow to 50 for the heavy crossbow. I don't think different multipliers is going to work. 

I have two proposed solutions.

1) different damage types for broadhead and bodkin versions.

If it could be made so that broadhead arrows/bolts do 25% bash damage and 75% pierce damage and that bodkin arrows do 95% pure pierce damage it would make them better against armored enemies.

Game example:

The compound crossbow against a 6/6 enemy (e.g. firefighter zombie or police zombie) would do: 28x1.25 =  35 raw damage

The broadhead bolt would do 35x0.25=8.75 bash damage of which 6 would be absorbed, and 35x0.75=26.25 cut damage of which 6 would be absorbed for a total of 35-12 = 23 damage.

The bodkin bolt would do 0 bash damage and 35x0.95-6 = 27.25 piercing damage. 

I don't know if this would be hard to implement and require a whole new damage type.

2) different length arrows for various bows and crossbows.

The range of 4-50 damage makes it hard to balance just by tweaking numbers, but if for example greatbows used longer and heavier arrows than shortbows (which makes sense) it would make it easier to balance.

**Additional context**  
Disclaimer: The bodkin versions are technically not _strictly_ worse as they have lower dispersion and higher melee damage. That's not the point of bodkin versions though.

EDIT: Missed that the broadhead arrows also have 1 armor pierce.

**Comment by macrosblackd** [comment]
I would think that broadhead arrows would do about 70/30 cut/pierce while bodkin do 30/70 cut/pierce. Would those numbers fix the discrepancy?

**Comment by ampersand55** [comment]
That would make bodkin arrows strictly better. 

The desirable result is that broadhead arrows/bolts are more effective against low armor and bodkin versions more effective against high armor.
