### ISSUE TITLE
Crash on entering missile silo

### ISSUE THREAD

**Issue by Svistoplyaz** [CleverRaven/Cataclysm-DDA#32828]
# Describe the bug
I found missile silo location, killed turrets, destroyed one of the walls of the land building. Game crashes when I try to go downstairs. Couple of times I was lucky and I was able to go 1 levle down, but after this I crushed when I decided to go even deeper.

# Steps To Reproduce
Just go downstairs and it crashes

# Expected behavior
I expect it not to crush my game when I go downstairs.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D
 - Graphics version: Tiles
 - Mods loaded: "dda",  "no_npc_food",  "novitamins",  "growable-pots",  "More_Survival_Tools", "Medieval_Stuff",  "makeshift",  "DinoMod",  "alt_map_key",  "national_guard_camp",  "more_locations",  "FujiStruct",  "mapgen_demo",  "Urban_Development",  "oa_additional_buildings_mod",  "boats",  "blazemod",  "deoxymod",  "Tanks",  "no_religious_Texts",  "Mundane_Zombies",  "safeautodoc",  "no_reviving_zombies",  "more_classes_scenarios",  "manualbionicinstall",  "StatsThroughSkills".

# Additional context

I have enclosed archive with crash.log and debug.log.
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3458962/config.zip)
And here is my save.
[Classic Zombies.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3458966/Classic.Zombies.zip)

**Comment by kasanryukin** [comment]
0.D-6016 -  Crash doesn't exist in this version, but man are there a ton of loading errors involving the national guard camp and some leather working recipes.

**Comment by Svistoplyaz** [comment]
Okay, I need to download another version than the one on the main website? And so what causes the bug? Thanks for your answer:)
