### ISSUE TITLE
Mouse provides no tooltip

### ISSUE THREAD

**Issue by Svistoplyaz** [CleverRaven/Cataclysm-DDA#32839]
# Describe the bug

I have updated CDDA from 0.D to the last build and now when I hover over tiles or mobs with my mouse I have no tooltip appearing. Is it a bug or you just removed this feature?

# Expected behavior
I expect my mouse to show tooltip as in previous version.

**Comment by ZhilkinSerg** [comment]
It was probably changed in https://github.com/CleverRaven/Cataclysm-DDA/pull/28152.

Use `Look around` action (`X` by default).
