### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by eskoONE** [CleverRaven/Cataclysm-DDA#32840]
# Describe the bug

the game crashes with an error after hitting "launch game" in the launcher. 

# Steps To Reproduce

starting the game.

# Expected behavior

the game to start.

# Screenshots

--

# Versions and configuration

 - OS: Windows 10 Home 1903
 - Game Version: 64bit version
 - Graphics version: tiles
 - Mods loaded: none

# Additional context

i was tying around with visual studio 2017/19 before the game started crashing. i had uninstalled everything related to vs at that point. i thought that visual c++ libraries had to do anything with it, but i installed every version available and still have issue. 

whats bugging me is that msvcrt.dll and ntdll.dll seem to be the culprits of the issue but i cant figure out how to fix that. maybe it is related to the way of how visual c++ redistributables are going to be managed now? specifically 2015, 2017 and 2019, since these come packed in one package now.

this issue only occurs when on the 64bit tiles version of the game .

[crash_debug_log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3459779/crash_debug_log.zip)

**Comment by eskoONE** [comment]
i think i figured it out. 

for some reason rivatuner server statistics, a program i use to limit the frame rate of my games, crashes the 64bit version of the game. making an exception in the app solves the issue. 

i have no idea why that suddenly started happening, because i was running the game just fine before. it still probably has something to do with the v c++ libraries but i dont know enough about this stuff to be sure about it.

**Comment by ZhilkinSerg** [comment]
Unfortunately we can't do anything with apparently an environmental issue.
