### ISSUE TITLE
Character permanently 'Scorching!', not apparently on fire, and 'chilly' at the same time

### ISSUE THREAD

**Issue by madamimadam** [CleverRaven/Cataclysm-DDA#32861]
# Describe the bug

Accidentally lit the basement of a cathedral on fire. Oops. I didn't realize it until I went down in again and was surrounded by fire, although not standing in it.

I immediately went back up, and retreated from the (non-burning) ground level of the building. But although I got two map squares away, and five minutes later, I was still 'scorching' on all my body parts, and losing condition on them. Even while at the same time I was 'chilly' on most of my body as well.

# Steps To Reproduce

I haven't tried.

# Expected behavior

If I was on fire at the beginning (I don't know either way) I should have gone out. And either way I should have stopped losing condition when the surrounding air was no longer scorching and I wasn't on fire.

# Versions and configuration

Cataclysm-0.D-OSX-Tiles-9394.dmg

Cataclysm-0.D-OSX-Tiles-9394.dmg
- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.13.6; Build: 17G7024; 
- Game Version: 0.D-6005-g110f6f9 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

Unfortunately I can't provide the save. I seem to have accidentally quit without saving. (Didn't realize command-q did that, I thought it saved first.)

**Comment by MrOlaf** [comment]
Currently fire/heat damage is bypassing Fire Resistance on gear and Thermal Dissipation + Internal Climate Control can't keep up with hot air 1, hot air 2, hot air 3 stacks, when heat spreads with experimental z-levels. Tiles over and below the burning location seem to be subject to heat.

There needs to be a rework where heat is a scale between Freezing and Scorching! Right now it seems heat damage is stacking, while bypassing almost any defense a player has against it.

Steps to recreate: teleport to a strange temple fire corridor wearing fire resistance gear and aforementioned CBMs, wait 5-10 minutes with CBMs working, teleport to a different non-heated tile and notice scorching status does not seem to be affected much by CBMs or fire resistance gear.

**Comment by sdp0et** [comment]
I've had similar problems.  It seemed like my clothing was just overly good at insulating.  removing clothing instantly reset the temperature for that body part and didn't return to scorching when putting it back on.

**Comment by MrOlaf** [comment]
Still sounds like a bug. But thanks for the tip on taking off clothes.

**Comment by AMurkin** [comment]
Fixed by #36450?

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.
