### ISSUE TITLE
[i18n] 'sling' has different translations in different contexts.  

### ISSUE THREAD

**Issue by kwl01skz** [CleverRaven/Cataclysm-DDA#32863]
**Describe the solution you'd like**  

 Sling has different translations in different contexts.  I want to add context for gettext 'sling', Imitation /doc/TRANSLATING.md. 
I add context to the weapon sling，like this
/data/json/items/ranged.json

```JSON   
"id": "sling",
"type": "GUN",
"symbol": "(",
"color": "brown",
"name": { "ctxt": "weapon", "str": "sling" }
```
But the game can't read this json.
So which step are I missing?

**Describe alternatives you've considered**  
Another way is to add context to the gunmod sling, write it in cpp,  

/scr/itype.cpp
```CPP
std::string gunmod_location::name() const
{
    // Yes, currently the name is just the translated id.
    return pgettext( "gunmod", _id.data() );
}
```
It works. But is this too... wasted?

**Additional context**  

/doc/TRANSLATING.md
> `class translation` can also be read from JSON. The method `translation::deserialize()`
> handles deserialization from a `JsonIn` object, so it can be read from JSON
> using the appropriate JSON functions. The corresponding JSON syntax for strings
> with context is as follows:
> 
> ```JSON
> "name": { "ctxt": "foo", "str": "bar" }
> ```

**Comment by Qrox** [comment]
Translation context for json weapon names is not yet supported. You can refer to #26402 and implement it if you are inclined to do so.

**Comment by kwl01skz** [comment]
Thanks, I asked this issues because I was worried that modifying too much code would cause confusion, so I decided to use a relatively small alternative.
