### ISSUE TITLE
Going upstairs while riding a mechsuit gives a segfault crash

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#32872]
# Describe the bug

I tried to go upstairs while riding my recon mechsuit, then i got a segfault.
![image](https://user-images.githubusercontent.com/44106380/62412100-3c6d6b00-b630-11e9-822b-44cead5c094e.png)

# Steps To Reproduce

1. Ride a mechsuit
2. Try going upstairs
3. segfault

# Expected behavior

Should be able to go up with my mechsuit and not crashing

# Versions and configuration

 - OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-6123-g572044d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Whaleys Tattoos and Scars [TATTOOMOD],
    sees-player icon, -attitude [sees_player_less_attitude],
    sees-player icon, +attitude [sees_player],
    [DP_MOD] Hide DEBUG [DP_No_Debug_Tile],
    Necromancy [necromancy],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    Urban Development [Urban_Development],
    More Locations [more_locations],
    Mapgen Demo [mapgen_demo],
    Fuji's More Buildings [FujiStruct],
    Beta National Guard Camp [national_guard_camp],
    Zetsukaze's Hair Extensions! [zets_hair_extensions],
    Mythical Martial Arts [MMA],
    Mutant NPCs [mutant_npcs],
    Hydroponics [hydroponics],
    EZ-Mode Medical [fast_healing],
    Alternative Map Key [alt_map_key],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    DinoMod [DinoMod],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Makeshift Items Mod [makeshift],
    Icecoon's Arsenal [ew_pack],
    Garden Pots [growable-pots],
    Extended Realistic Guns [realguns],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Craftable Gun Pack [craftgp],
    Bens GF recipes [Tolerate_This],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Armor Up! PA Utilities [ArmUpPAUtil],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Safe Autodoc [safeautodoc],
    Manual Bionic Installation [manualbionicinstall],
    Advanced Gear [adv_gear],
    Cataclysm++ [Cata++],
    NPC traits [npc_traits],
    Zet's Hair - More Locations [zets_hair_ext_more_locations],
    Fun Clothes [ExClothes],
    PKs Rebalancing [PK_REBALANCE],
    Lighting Ammo [light_ammo],
    NPC Recruitment Options [recruitment_options],
    Mug NPCs [mug_NPCs],
    Morlock Village [morlock_village],
    Zet's Hair - PKs Rebalancing [zets_hair_ext_pk_rebalance],
    StatsThroughSkills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

I have z-levels enabled.

**Comment by anothersimulacrum** [comment]
Confirmed on Linux with only the `dda` mod.
Here's a stack trace.

> The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.D-6133-g141974c779
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

	./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x42) [0x5596d243eefa]
	./cataclysm-tiles(+0x4b52d9) [0x5596d24302d9]
	./cataclysm-tiles(+0x4b54ef) [0x5596d24304ef]
	/usr/lib/libc.so.6(+0x3a7e0) [0x7eff6885c7e0]
	./cataclysm-tiles(_ZNK5mtype5nnameB5cxx11Ej+0x8) [0x5596d27d3492]
	./cataclysm-tiles(_ZNK7monster4nameB5cxx11Ej+0x15a) [0x5596d27b2be6]
	./cataclysm-tiles(_ZNK7monster9disp_nameB5cxx11Eb+0x30) [0x5596d27b2c86]
	./cataclysm-tiles(_ZN16Creature_tracker10update_posERK7monsterRK8tripoint+0x398) [0x5596d2438972]
	./cataclysm-tiles(_ZN7monster6setposERK8tripoint+0x60) [0x5596d27b0d3e]
	./cataclysm-tiles(_ZN4game13vertical_moveEib+0x1167) [0x5596d24ec7c9]
	./cataclysm-tiles(_ZN4game13handle_actionEv+0xe1c) [0x5596d251ab94]
	./cataclysm-tiles(_ZN4game7do_turnEv+0x42a) [0x5596d24e3a12]
	./cataclysm-tiles(main+0x1248) [0x5596d2295b65]
	/usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7eff68848ee3]
	./cataclysm-tiles(_start+0x2e) [0x5596d22f39de]

	Attempting to repeat stack trace using debug symbols...
	debug_write_backtrace(std::ostream&)
	.../src/debug.cpp:621
	std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const
	/usr/include/c++/9.1.0/sstream:678
	log_crash
	.../src/crash.cpp:263
	signal_handler
	.../src/crash.cpp:292
	??
	??:0
	mtype::nname[abi:cxx11](unsigned int) const
	.../src/mtype.cpp:61
	monster::name[abi:cxx11](unsigned int) const
	.../src/monster.cpp:511
	monster::disp_name[abi:cxx11](bool) const
	.../src/monster.cpp:548
	std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > string_format<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int const&, int const&, int const&, int const&, int const&, int const&>(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, int const&, int const&, int const&, int const&, int const&, int const&)
	.../src/string_formatter.h:402
	void realDebugmsg<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int const&, int const&, int const&, int const&, int const&, int const&>(char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, int const&, int const&, int const&, int const&, int const&, int const&)
	.../src/debug.h:79
	Creature_tracker::update_pos(monster const&, tripoint const&)
	.../src/creature_tracker.cpp:126
	monster::setpos(tripoint const&)
	.../src/monster.cpp:267
	game::vertical_move(int, bool)
	.../src/game.cpp:10266
	game::handle_action()
	.../src/handle_action.cpp:1705
	game::do_turn()
	.../src/game.cpp:1434
	main
	.../src/main.cpp:688
	__libc_start_main
	??:?
	_start
	??:?
