### ISSUE TITLE
Sevaral errors on loading a new save; lawn dart, battery ups and item location lost target

### ISSUE THREAD

**Issue by Runeerle** [CleverRaven/Cataclysm-DDA#32874]
When updating to a new build I got several errors, but no crash or other visible bad effects:

 DEBUG    : Item lawn_dart was loaded with charges, but can not have any!
 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2145

 DEBUG    : Item battery_ups was loaded with charges, but can not have any!
 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2145

 DEBUG    : item_location lost its target item during a save/load cycle
 FUNCTION : void item_location::impl::ensure_unpacked() const
 FILE     : src/item_location.cpp
 LINE     : 97

I did not see anything wrong with any UPS items that I have. The extra info from the log file is copied in at the end.

# Steps To Reproduce
Unknown how to reproduce this, but the build I updated from was from 4 days ago.

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-6126-g27d66a7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context
...
12:29:58.847 ERROR : src/savegame_json.cpp:2145 [void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]] Item lawn_dart was loaded with charges, but can not have any!
12:30:28.760 ERROR : src/savegame_json.cpp:2145 [void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]] Item battery_ups was loaded with charges, but can not have any!
12:36:42.689 ERROR : (error message will follow backtrace)
	(@0x5b3b9e[cataclysm-tiles.exe+0x1b3b9e]), 
	(@0x5b41da[cataclysm-tiles.exe+0x1b41da]), 
	(@0x5b75c6[cataclysm-tiles.exe+0x1b75c6]), 
	(IMG_LoadWEBP_RW+0x111455@0x1135f55[cataclysm-tiles.exe+0xd35f55]), 
	(@0x7e4721[cataclysm-tiles.exe+0x3e4721]), 
	(IMG_LoadWEBP_RW+0x2cff70@0x12f4a70[cataclysm-tiles.exe+0xef4a70]), 
	(@0xd12a6c[cataclysm-tiles.exe+0x912a6c]), 
	(@0xd12ed0[cataclysm-tiles.exe+0x912ed0]), 
	(@0xd13c01[cataclysm-tiles.exe+0x913c01]), 
	(@0xcffcc1[cataclysm-tiles.exe+0x8ffcc1]), 
	(@0x4fd116[cataclysm-tiles.exe+0xfd116]), 
	(@0x5000e2[cataclysm-tiles.exe+0x1000e2]), 
	(@0x669b42[cataclysm-tiles.exe+0x269b42]), 
	(@0x67b1f9[cataclysm-tiles.exe+0x27b1f9]), 
	(@0x67b540[cataclysm-tiles.exe+0x27b540]), 
	(@0x6b97f0[cataclysm-tiles.exe+0x2b97f0]), 
	(IMG_LoadWEBP_RW+0x57a738@0x159f238[cataclysm-tiles.exe+0x119f238]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0xd@0x7786556d[kernel32.dll+0x1556d]), 
	(RtlUserThreadStart+0x1d@0x779c385d[ntdll.dll+0x5385d]), 
Backtrace emission took 0 seconds.
src/item_location.cpp:97 [void item_location::impl::ensure_unpacked() const] item_location lost its target item during a save/load cycle
12:46:50.150 ERROR : (error message will follow backtrace)
	(@0x5b3b9e[cataclysm-tiles.exe+0x1b3b9e]), 
	(@0x5b41da[cataclysm-tiles.exe+0x1b41da]), 
	(@0x5b75c6[cataclysm-tiles.exe+0x1b75c6]), 
	(IMG_LoadWEBP_RW+0x111513@0x1136013[cataclysm-tiles.exe+0xd36013]), 
	(IMG_LoadWEBP_RW+0x296963@0x12bb463[cataclysm-tiles.exe+0xebb463]), 
	(@0xd1e445[cataclysm-tiles.exe+0x91e445]), 
	(@0xd269ff[cataclysm-tiles.exe+0x9269ff]), 
	(@0x931bc5[cataclysm-tiles.exe+0x531bc5]), 
	(@0x4fb3f3[cataclysm-tiles.exe+0xfb3f3]), 
	(@0x4ff753[cataclysm-tiles.exe+0xff753]), 
	(@0x4ffa81[cataclysm-tiles.exe+0xffa81]), 
	(@0x93290f[cataclysm-tiles.exe+0x53290f]), 
	(@0x932ebb[cataclysm-tiles.exe+0x532ebb]), 
	(@0x8e8cb0[cataclysm-tiles.exe+0x4e8cb0]), 
	(@0x8e99f0[cataclysm-tiles.exe+0x4e99f0]), 
	(@0x6a4ba6[cataclysm-tiles.exe+0x2a4ba6]), 
	(@0x6a5a07[cataclysm-tiles.exe+0x2a5a07]), 
	(@0x6a6675[cataclysm-tiles.exe+0x2a6675]), 
	(@0x6bea43[cataclysm-tiles.exe+0x2bea43]), 
	(@0x4a50ba[cataclysm-tiles.exe+0xa50ba]), 
	(@0x6df73e[cataclysm-tiles.exe+0x2df73e]), 
	(@0x6b9c57[cataclysm-tiles.exe+0x2b9c57]), 
	(IMG_LoadWEBP_RW+0x57a738@0x159f238[cataclysm-tiles.exe+0x119f238]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0xd@0x7786556d[kernel32.dll+0x1556d]), 
	(RtlUserThreadStart+0x1d@0x779c385d[ntdll.dll+0x5385d]), 
Backtrace emission took 0 seconds.
src/savegame_json.cpp:2145 [void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]] Item lawn_dart was loaded with charges, but can not have any!

**Comment by ampersand55** [comment]
lawn_dart error is due to this: https://github.com/CleverRaven/Cataclysm-DDA/pull/32818

The bad news is that your stack of lawn darts have been merged into one.

The good news is that lawn darts are now faster to throw as you only equip one at a time.
