### ISSUE TITLE
game crashes when entering hazardous waste sarcophagus 

### ISSUE THREAD

**Issue by bigfixenergy** [CleverRaven/Cataclysm-DDA#32881]
# Describe the bug

Entering the building causes the game to immediately freeze up and crash the moment I enter. 

# Steps To Reproduce

1. Entering through any means such as a window or door causes this.
2. Game chokes and dies

# Expected behavior

I expected the game not to crash just from entering a building, especially because even just entering the "property" itself (e.g. climbing the fence) causes no issues or hiccups whatsoever

# Screenshots

The game crashes so quickly I don't even get the usual black screen error. It just cuts straight to crash window. I think it said something about segmentation error. 

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-6072-g4add125
 
 - Mods loaded:"dda", "no_npc_food", "novitamins", "no_religious_Texts", "No_Acid_Zombies", "No_Big_Zombies", "more_classes_scenarios", "manualbionicinstall", "StatsThroughSkills", "makeshift", "More_Survival_Tools", "modular_turrets", "Salvaged_Robots", "mutant_npcs", "more_locations", "FujiStruct", "Urban_Development", "boats", "deoxymod", "blazemod", "Tanks", "necromancy", "hydroponics", "DP_No_Status_Tiles", "DP_AMAZING_CHEST_INDICATORS"

**Comment by anothersimulacrum** [comment]
I can't reproduce this. Can you upload a save?

**Comment by bigfixenergy** [comment]
> I can't reproduce this. Can you upload a save?

I'm still not entirely familiar with which save files are which, however I tried using the debug menu to teleport myself in the building and oddly enough it didn't crash. It seems that there is some sort of "ring of death" surrounding the building with SRCF computer.

**Comment by bigfixenergy** [comment]
turns out reading a book found in a drawer crashed the game. It seems that its due to a "segmentation error"
worse yet, my game save right before crashing so now the file is unplayable...

**Comment by ZhilkinSerg** [comment]
Please provide a savegame before crash and ping me to reopen the issue.
