### ISSUE TITLE
Crash at the second floor of Research facility (again)

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#32885]
When spending long ammounts of time in the second floor of the research facility the game crashes. This usually happens when I deconstruct stuff. Have not managed to replicate it consistently, but If I dissasemble enough stuff up there it will happen. Seems to be related with messages similar to the ones in the screenshot, after which big waves of will appear in floor 1.

![image](https://user-images.githubusercontent.com/5623801/62416199-2053d480-b604-11e9-9ded-fb62ca51fcaa.png)

For reference, this possibly similar bug appeared on april and was closed.

https://github.com/CleverRaven/Cataclysm-DDA/issues/29323

Here is the save file. The name is unrelated.

[8clean.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3464235/8clean.zip)

EDIT: forgot to add the crash log 
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3464241/crash.log)
Edit2: using Build #9422 - August 3, 2019 at 5:43:47 AM -0400. The error message I screenshoted above happened in the previous build #9420 too, but I didnt spend enough time in that floor to know if the crash would happen there.

**Comment by Bulletfang** [comment]
This 'there's already a monster at X' is a very frequent crash in my experience, it's happening everywhere seemingly at random and isn't linked with the research facility specifically. I'm playing with 200% monster spawn though, so that could be a variable.
