### ISSUE TITLE
Random bow sling unholstering

### ISSUE THREAD

**Issue by Greysa** [CleverRaven/Cataclysm-DDA#32887]
Describe the bug

I have a compound bow in my bow sling and it  moves to my inventory after pressing 'r'with nothing in hand, sometimes causing items to drop.

Steps To Reproduce

1: Have bow in bow sling
2: Have nothing in hand
3: Press 'r'

Expected behavior

Bow should remain in bow sling unless explicitly removed or wielded.

Screenshots

![briefcasetumble](https://user-images.githubusercontent.com/52637570/62417616-4e362900-b697-11e9-80e2-8d88293d502e.png)
Pressing 'r with nothing in hand causes the bow to move to inventory, which, as a result, causes the briefcase to drop due to not enough volume in inventory.

Versions and configuration

- OS: Windows
    - OS Version: 10.0 1511
- Game Version: 0.D-6153-g89a33be [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    [DP_MOD] Alternative Floor Tiles [DP_Old_Floor],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Zetsukaze's Hair Extensions! [zets_hair_extensions],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    More Survival Tools [More_Survival_Tools],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    StatsThroughSkills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    Mining Mod [Mining_Mod],
    Hydroponics [hydroponics],
    Simplified Nutrition [novitamins]
]

**Comment by Zourin2** [comment]
I've come across this when using the Reload button (r), where if you Reload and it cannot complete the action, such as a full magazine, no items to reload, or no ammo to load into a weapon, it will begin unholstering items into your inventory., including bow slings and knife sheathes.
I'm assuming these issues are related.

**Comment by Greysa** [comment]
you are right, pressing 'r' with nothing in your hands places the compound bow in inventory. I will update the original comment.

**Comment by Night-Pryanik** [comment]
Pressing `r` opens reload menu, it doesn't automatically reload items.
