### ISSUE TITLE
Desert Region Mod broken

### ISSUE THREAD

**Issue by aierce** [CleverRaven/Cataclysm-DDA#32897]
Game crashes when trying to generate world with desert region mod on.

Error codes:

 DEBUG    : Error: data/mods//desert_region/desert_regional_map_settings.json: line 115:5: shore_extendable_overmap_terrain_aliases required

      "lake_size_min": 10,
      "shore_extendable_overmap_terrain": [ "forest", "forest_thick", "forest_water", "field" ]
    }
    ^
     ,
    "overmap_forest_settings": {
      "noise_threshold_forest": 0.5,

 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 812

build#: 9424

**Comment by aierce** [comment]
proposed fix:
insert this line
"shore_extendable_overmap_terrain_aliases": [  ]
between line 115 and 116 in data/mods//desert_region/desert_regional_map_settings.json

I have no idea what it does but it fixes error code

**Comment by AMurkin** [comment]
Introduced by #32724
