### ISSUE TITLE
CBM not sterile after floor change

### ISSUE THREAD

**Issue by MrOlaf** [CleverRaven/Cataclysm-DDA#32896]
# Describe the bug

Upon floor change packed sterile CBM changes status to (packed) so it can't be installed at an autodoc.

# Steps To Reproduce

1. autoclave a packed CBM to sterile via autoclave or mounted autoclave
2. go to floor -1 where an autodoc is located (with experimental z-levels on) 
3. check status of CBM - it reverts from sterile to packed

# Expected behavior

CBM should stay sterile despite floor changes.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-6153-g89a33be
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs

**Comment by Fris0uman** [comment]
Can you provide a save?

**Comment by MrOlaf** [comment]
After reloading game and the save, repackaging the CBM into a new autoclave bag (and sterilizing) - the feature works as intended when traveling between z-levels. Odd, maybe one-off bug.

**Comment by Fris0uman** [comment]
So it's not a bug, when you do the packaging step there's a skill check and if you fail it the packing is faulty and it will not keep the CBM sterile.

**Comment by MrOlaf** [comment]
Thanks for the tip. Did not consider a skill check at sterilization.
