### ISSUE TITLE
Stacked Fuel Insta-burn

### ISSUE THREAD

**Issue by Zourin2** [CleverRaven/Cataclysm-DDA#32890]
"Charge' fuel stacks such as charcoal, lamp oil, and tinder, when placed in a 'firewood source' location, are instantly consumed by nearby fire containers (eg, wood stoves/braziers), rather than doled out as needed like normal item stacks. 

1. Place a stack of charcoal (1000) on a Firewood Source
2. Light a nearby wood stove, fireplace, oven, or brazier.
3. The fire container instantly consumes all 1000 units of charcoal and burns as though only one unit were used. 

# Expected behavior
If using fuels such as Charcoal, Lamp Oil, or Tinder should be permitted to be used as a fire fuel source:  Fuels with compact stacking should be treated like normal stacked fuels when being used through the 'firewood source' mechanic. (I consider this ideal, as they could be a more versatile fuel source for long/short jobs than logs or splinters and require extra processing to obtain)

if using fuels such as charcoal, lamp oil, or tinder are NOT intended to be used as a fuel source for fires, do not allow Firewood Sources to use these items as fuel.

(edit: Removed comments about large amounts of ash being produced. This was reported in error.)

**Comment by alkemann** [comment]
Confirmed with steps described in master 2bda93b4da

**Comment by alkemann** [comment]
I think the change in this commit is responsible 79f33280fbefcec048addb2550e447bbc32e153e

The `drop_on_map` doesn't support moving 1 from stack? @ifreund

**Comment by Zourin2** [comment]
May also want to consider what to do with the fuel containers if doing so with plastic containers such as bottles and jerry cans. I can't positively confirm atm, but I'm sure they are destructible by fire and probably not something that should be thrown on a brazier.
