### ISSUE TITLE
Disable "recraft last recipe" while driving

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#32894]
I can only think of very rare situations where you would want to craft something while driving (makeshift bandage from rags while making a getaway and bleeding out). In spanish laptop keyboards at least, "." is right by "-". Hilarity ensues. So, make it ask for confirmation? Or disable.

**Comment by kevingranade** [comment]
Consider rebinding your keys if they have poor ergonomics, we're not going to second guess every keypress the player makes.

**Comment by Svankensen** [comment]
> Consider rebinding your keys if they have poor ergonomics, we're not going to second guess every keypress the player makes.

Not the point, I already did that. There is no need to have a key that on keypress makes you lose a ton of turns and puts you in danger when there is absolutely no need for it to work while driving.
