### ISSUE TITLE
Recipes Missing/Disappearing from crafting menu and books

### ISSUE THREAD

**Issue by terranaut1** [CleverRaven/Cataclysm-DDA#32904]
# Describe the bug

Some recipes seem to simply disappear as the game progresses. This includes autolearned things aswell as things from books and is tied to the character savefile somehow. In particular I noticed that light batteries and the survivor utility belt are not craftable. As far as the former is concerned, it is not even listed in books that should have the recipe, as if the recipe was missing from the save altogether. The utility belt appears again properly as autolearned recipe on a new character created in the same world with the same settings. It was available at least for a time on this character but sadly I can't quite pinpoint what made it disappear. I had a pretty bad case of food parasites and a cold for a long time which are the only real things that happened to me but I doubt that's related.

The recipe is still listed in the learned_recipes in my characters save file but does not show up in the ingame crafting menu.
It is NOT hidden using the crafting menu function, at least `h:yes` returns no results.
Importing the save to a different version does not alleviate the problem.

# Versions and configuration
Savegame: [Frenchville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3464979/Frenchville.zip)

- OS: Windows
    - OS Version: W10.0 1607
- Game Version: 0.D-6072-g4add125 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Garden Pots [growable-pots],
    Vehicle Additions Pack [blazemod]
]

**Comment by Domotdow** [comment]
How do you look up learned_recipes in characters save file. I am having a slimier problem where I am not getting recipes from a book I read.

**Comment by terranaut1** [comment]
> How do you look up learned_recipes in characters save file. I am having a slimier problem where I am not getting recipes from a book I read.

The .sav file in the worlds folder holds your characters information, among them a `learned_recipes` list. Keep in mind that that's referring to memorized recipes, reading a book generally doesn't memorize the recipes but just makes them available for crafting when you have the book within crafting range.

As for the issue at hand, further digging through the save file showed me that that, in the uistate.json, the survivor utility belt, was among the hidden_recipes list. Clearing that did indeed return it to my craftable items.
What that doesn't explain is why:
- Making a new character in the same world allowed me to craft the item
- Why I can't make light batteries (which should be available from low level electronics books which I have, at least according to the item viewer)
- Why filtering for h:yes didn't list it.

**Comment by Edixo1993** [comment]
I have the same issue - noticed when I suddenly couldn't make pine nuts, which is a BIG issue.

Attached save.

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3482199/save.zip)

**Comment by Zireael07** [comment]
Hidden recipes iirc are per-character, not per world, and concerning light batteries, the item viewer site is probably more than a bit outdated (batteries were changed a lot after 0.D)

**Comment by int-ua** [comment]
Please try reproducing it on latest version.
