### ISSUE TITLE
Question: Is there a reason why the tools in bashing.json are categorized as weapons?

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#32906]
**Is your feature request related to a problem? Please describe.**  

`recipes\weapon\bashing.json` consists of the following items:

battletorch (Louisville Slaughterer)
crowbar
halligan
claw_bar
iceaxe
makeshift_crowbar
torch

It seems to me that every item except for the battletorch is primarily a tool. You wouldn't craft any of these to use as a weapon (with the possible exception of the makeshift_crowbar) so it would be more intuitive to have them in the tools category.

**Describe the solution you'd like**  

Move the crowbar, halligan, claw_bar, iceaxe, makeshift_crowbar and torch to `recipes\other\tools.json` and reclassify them from `"category": "CC_WEAPON", "subcategory": "CSC_WEAPON_BASHING",` to `"category": "CC_OTHER", "subcategory": "CSC_OTHER_TOOLS"`.

**Describe alternatives you've considered**  
Remove bashing.json entirely and move the remaining weapon to `recipes\recipe_weapon.json`. But I assume that the plan is to eventually sort the weapons in that file into their respective jsons.

**Additional context**  
I could make a PR if this is confirmed.

**Comment by anothersimulacrum** [comment]
Please do make a PR, there isn't really a reason for this.

**Comment by ZhilkinSerg** [comment]
#32908
