### ISSUE TITLE
CRIT ( C.R.I.T. ) Breaks Wilderness start

### ISSUE THREAD

**Issue by bitassassin** [CleverRaven/Cataclysm-DDA#32909]
Game version: 0.D-6153-g89a33be (tiles)

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: 

- DDA
- Aftershock
- Crit
- Magiclysm
- --
- Bens GF
- Craftable Guns
- Garden Pots
- Icecoon's
- Makeshift Items
- Medieval Classes
- More survival tools
- --
- Modular Turrets
- Salvaged Robots
- Alternative Map Key
- Hydroponics
- Mutant NPCs
- Mythical Martial Arts
- --
- More Locations
- Fuji's
- Mapgen Demo
- No Rail Stations
- --
- Folding Parts Pack
- Vehicle Additions Pack
- Tanks and such
- --
- Necromancy
- --
- Battery Migration
- Classes and Scenarios
- Manual Bionics
- Safe Autodoc
- Sleep Deprivation
- Speedydex
- Stats through kills
- Stats through skills

### Expected behavior
More than just CRIT starts in the wilderness

### Actual behavior
Only CRIT starts in the wilderness

### Steps to reproduce the behavior
Look at scenarios, select wilderness, go to next page, be sad.

(Disabling crit fixes it.)

**Comment by ZhilkinSerg** [comment]
Probably introduced in #31661.

Should be resolved in a manner similar to #32612.
