### ISSUE TITLE
Severe lag in build 9424

### ISSUE THREAD

**Issue by Proxiehunter** [CleverRaven/Cataclysm-DDA#32907]
# Describe the bug

Build 9424 is suffering extreme lag when moving around town. Usual culprits such as slime pits, fungi, and anthills are nowhere to be found. I do have 3 NPC companions but no other NPCs are visible on the map.

# Steps To Reproduce
Play game, have lag.

# Expected behavior

Play game, _not_ have lag.

# Versions and configuration

 - OS: Windows 7
 - Game Version: Build 9424
 - Graphics version: Tiles
 - Mods loaded: [
  "dda",
  "no_npc_food",
  "Tolerate_This",
  "makeshift",
  "More_Survival_Tools",
  "no_freeze",
  "mutant_npcs",
  "deoxymod",
  "blazemod",
  "Tanks",
  "No_Big_Zombies",
  "more_classes_scenarios",
  "manualbionicinstall",
  "no_filthy_clothing",
  "novitamins",
  "StatsThroughSkills",
  "magiclysm",
  "Realistic_Fridge_Size",
  "alt_map_key",
  "sees_player",
  "No_Fungi",
  "stats_through_kills",
  "aftershock"
]

**Comment by ZhilkinSerg** [comment]
Savegame?

**Comment by kevingranade** [comment]
Not reproduceable
