### ISSUE TITLE
Multiple Segfaults in current build

### ISSUE THREAD

**Issue by bitassassin** [CleverRaven/Cataclysm-DDA#32910]
Game version: 0.D-6153-g89a33be (tiles)

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: 

- DDA
- Aftershock
- Crit
- Magiclysm
- --
- Bens GF
- Craftable Guns
- Garden Pots
- Icecoon's
- Makeshift Items
- Medieval Classes
- More survival tools
- --
- Modular Turrets
- Salvaged Robots
- Alternative Map Key
- Hydroponics
- Mutant NPCs
- Mythical Martial Arts
- --
- More Locations
- Fuji's
- Mapgen Demo
- No Rail Stations
- --
- Folding Parts Pack
- Vehicle Additions Pack
- Tanks and such
- --
- Necromancy
- --
- Battery Migration
- Classes and Scenarios
- Manual Bionics
- Safe Autodoc
- Sleep Deprivation
- Speedydex
- Stats through kills
- Stats through skills

### Expected behavior
Not having Segfaults

### Actual behavior
Having segfaults

### Steps to reproduce the behavior
On average play for about an hour and a half, and then game god smites you. Be sad.

See attached.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3465129/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3465130/debug.log)
[#R2lvdmFubmkgRmluY2g=.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3465131/R2lvdmFubmkgRmluY2g.log)
[crash (1).log](https://github.com/CleverRaven/Cataclysm-DDA/files/3465132/crash.1.log)
[debug (1).log](https://github.com/CleverRaven/Cataclysm-DDA/files/3465133/debug.1.log)

**Comment by ymber** [comment]
You need to follow the issue template and provide the information it asks for. Open a separate issue for each different case your game crashes in with a proper description of the problem and steps to reproduce it. We can't effectively work from logs alone, especially when the stack traces are from a build without debug symbols.
