### ISSUE TITLE
"Ye Scots Beuk o Cuikery, book" containing crafting recipes do not work.

### ISSUE THREAD

**Issue by Domotdow** [CleverRaven/Cataclysm-DDA#32928]
"Ye Scots Beuk o Cuikery, book" containing crafting recipes do not work.

[manual_BugYe Scots Beuk o Cuikery book containing crafting recipes do not work..zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3465784/manual_BugYe.Scots.Beuk.o.Cuikery.book.containing.crafting.recipes.do.not.work.zip)

when I learned with this book it did level up my cooking but I did not get the recipes it contains 

1. when level 3 read "Ye Scots Beuk o Cuikery" until level 4
2. try use recipes in book  "FAIL"

# Expected behavior
Get the recipes the books says it has

# Versions and configuration

 - OS: [Windows 10] 
 - Game Version: [0.D-6153-g89a33be]
 - Graphics version: [ChestHole32]
 - Mods loaded: 
[![20190804_201527](https://user-images.githubusercontent.com/32436906/62436849-cf240d80-b6f5-11e9-9d44-95e0666972f0.jpg)
![20190804_201744](https://user-images.githubusercontent.com/32436906/62436851-d21efe00-b6f5-11e9-862e-8046a6833f44.jpg)
![20190804_201755](https://user-images.githubusercontent.com/32436906/62436853-d4815800-b6f5-11e9-8539-cbfbb3b90cc8.jpg)
![20190804_201803](https://user-images.githubusercontent.com/32436906/62436854-d6e3b200-b6f5-11e9-8c7d-23633a708d2b.jpg)
![20190804_201809](https://user-images.githubusercontent.com/32436906/62436856-d8ad7580-b6f5-11e9-89f0-d9b6b0368f34.jpg)]

Okay thanks I hope you fix this soon.

**Comment by roaringjohn** [comment]
Generally, you need to be a level above the level required to craft whatever you want from that specific book.

**Comment by ZhilkinSerg** [comment]
1. Crafting can fail depending on skill levels and player stats.
2. Book recipes are not memorized automatically and you need to craft them having book in your possess until you memorize a recipe.

**Comment by Domotdow** [comment]
Aw that makes a lot of sense thanks, I will try that and see if that works.

**Comment by Domotdow** [comment]
I tried it with it in my inventory and wielding it. No such luck the recipe dose not show up at all. I haven't had this problem with any other books that I know of.

**Comment by sztosz** [comment]
What is the colour of the recipe in the book, when you look at the book? If its brown, I believe your skill is too low, and you will be able to craft that recipe when you level up in that skill.

**Comment by Domotdow** [comment]
Aw your right some the recipes are brown and I can't craft those. Thanks, I am only been play the game for the last couple of week so sorry for being a noob. Thanks for the help.

**Comment by ZhilkinSerg** [comment]
Yes, brown recipe means that you do not have all required skills - like there is a broadsword recipe in that book, but it doesn't need Cooking X to be craftable, but Fabrication 8 instead.

**Comment by Domotdow** [comment]
Um I have fabrication(4) and the crossbow needs fabrication(3) and its still not working. So there might be really a bug.

**Comment by ZhilkinSerg** [comment]
Can you upload a savegame?

**Comment by Domotdow** [comment]
I did before if you look at the top of my of my first message. I am kinda away from my base right now in the game so a new save won't give you access to the book right bow but here is a new save anyways 
[manual_BugYe Scots Beuk o Cuikery book containing crafting recipes do not work. 2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3475793/manual_BugYe.Scots.Beuk.o.Cuikery.book.containing.crafting.recipes.do.not.work.2.zip)

**Comment by Domotdow** [comment]
I can get you one where at the base when I get back there if that helps.

**Comment by sztosz** [comment]
You need `fabrication` at `6` to learn it from that book, probably because that book is a `semi-translated cookbook` and it's a `bit difficult to read`.

Relevant piece of JSON, look for `scots_cookbook` below.
```json
{
    "type": "recipe",
    "result": "crossbow",
    "category": "CC_WEAPON",
    "subcategory": "CSC_WEAPON_RANGED",
    "skill_used": "fabrication",
    "difficulty": 3,
    "time": "15 m",
    "reversible": true,
    "decomp_learn": 2,
    "book_learn": [
      [ "recipe_bows", 2 ],
      [ "manual_archery", 4 ],
      [ "book_archery", 3 ],
      [ "scots_cookbook", 6 ],
      [ "textbook_armschina", 5 ]
    ],
    "qualities": [ { "id": "SCREW", "level": 1 }, { "id": "WRENCH", "level": 1 } ],
    "components": [ [ [ "2x4", 2 ], [ "stick", 4 ] ], [ [ "scrap", 1 ] ], [ [ "string_36", 3 ] ] ]
  },
```

**Comment by Domotdow** [comment]
Aw that makes sense, Thanks.
