### ISSUE TITLE
Farm spawns are not balanced

### ISSUE THREAD

**Issue by RarkGrames** [CleverRaven/Cataclysm-DDA#32921]
# Describe the bug

Rural farm overmap specials are heavily out of balance. The ones added by  #31188 (farm_lot_wired_2x3, farm_lot_empty_3x2, farm_lot_forest, farm_lot_2x4) all have a 0, 15 occurrence. and they fill the countryside completely. The standard number is 0, 5, and even though the horse farm is at 0, 5, it is more commonly found than the rest.
The dairy farm is at 0, 3. After generating a couple of dozens of overmaps (for other testing purposes), I never encountered a single dairy farm. The apple orchard is the same. The original dogs-in-the-barn type farm is pretty rare also.

# Expected behavior

I would guess that all the agricultural locations should be spread out proportionally on a generated overmap.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-6153-g89a33be [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Victaria90** [comment]
From what I've seen 90% are all horse farms. I've seen 1 farm with sheep/pigs, 1 orchard, and about 5 horse farms

**Comment by AdonaiJr** [comment]
Farms.... Farms everywhere. I've spawn a couple of maps, revealed, and yes, there's some balance in need.

**Comment by anothersimulacrum** [comment]
This issue should have the stale tag removed, it was fixed in #32978

**Comment by RarkGrames** [comment]
Yes, that PR pretty much solved all the problems in this issue.
