### ISSUE TITLE
Segfault being dragged by nursebot in build 9424

### ISSUE THREAD

**Issue by Brettflan** [CleverRaven/Cataclysm-DDA#32929]
# Describe the bug

I was going through an ice lab and came across a nursebot that actually appeared to be aggro, unlike other nursebots I've seen, and the log indicated that "the nurse bot scans you and seems to detect something". I was curious, so I went up to the bot, which then grabbed me and started dragging me in the direction of the autodoc. Not wanting to lose this character in case it vivisected me or whatever, but wanting to see what happened, I saved and exited to make a backup of the save. Upon loading the save now, it consistently crashes with a segfault as soon as I disable safe mode and do anything. Passing time, trying to move away, or attacking the nursebot all cause a crash.

I tried debug teleport, which just added a couple lesser errors before the segfault, but then thankfully debug "kill all monsters" destroyed the nursebot and prevented the segfault. So if all else fails, that will work around it.

This save was started several version back, with me occasionally updating, so it's possible that's related. I have been playing on this version for a couple hours with no real incident, however.

# Steps To Reproduce

Possibly the above with having a nursebot decide to drag you, saving, then loading the save and continuing. Or it might be something specific to my save such as mods, I haven't tried reproducing it with a fresh unmodded game.

# Expected behavior

No crash.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

![cdda_segfault_next_turn](https://user-images.githubusercontent.com/592130/62438581-b6275680-b70d-11e9-940d-4b40ef870b44.png)

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1903
- Game Version: 0.D-6153-g89a33be [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context

Logs:
[cdda_segfault_logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3465901/cdda_segfault_logs.zip)
The save file was a bit big, so I uploaded to Mega:
https://mega.nz/#!Z8xWFCLB!c4wQw_vxFJrGzsl8UyV7Z5Yw7AwMQaZQwOKaftSfJoc

**Comment by ipcyborg** [comment]
Looks like `dragged_foe` is not properly saved/loaded.
