### ISSUE TITLE
Fertilizer Bomb doesn't ever go off.

### ISSUE THREAD

**Issue by Victaria90** [CleverRaven/Cataclysm-DDA#32936]
Most recent build.

Explosive - Fertilizer Bomb.

Once lit bomb shows active and 10 turn countdown. The timer only counted down while I was holding the bomb, once I threw it the bomb sat (lit) never exploding. 

The timer of the bomb was the same time from when it was thrown after 1hr of waiting in game.

**Comment by BaumgeistOne** [comment]
Happened to me too, with an EMP granade, but only when the granade was not on the same overmap tile as my character.

**Comment by Edgar-cy-Lee** [comment]
Sounds like issue is related to #32133. But it was fixed?

**Comment by BaumgeistOne** [comment]
Strange. This happened to me just a few days ago, and I am pretty sure that I was not on a version from 24+ days ago, but I can't seem to be able to reproduce it now.

**Comment by jeremyshannon** [comment]
Might be a dupe of #32276

**Comment by l29ah** [comment]
I've observed the same with an EMP grenade in a lab setting today. After saving and reloading, the grenade detonated.

**Comment by l29ah** [comment]
This bug makes ANFO charges useless: they tick only when you're in the blast zone.

**Comment by Nerezza** [comment]
I'm here to confirm that as of this latest Jenkins builds this is still a bug. I had this happen during an extensive lab clearing, despite using EMP 4 grenades with no problem before encountering the bug.

**Comment by davidpwbrown** [comment]
Can anyone provide a save where this is reproducible? Ive been thowing around fertilizer bombs for ages in-game, and cannot reproduce anymore ( although I know Ive seen it before personally )

**Comment by davidpwbrown** [comment]
> Can anyone provide a save where this is reproducible? Ive been thowing around fertilizer bombs for ages in-game, and cannot reproduce anymore ( although I know Ive seen it before personally )

Never mind this actually, a reproducible save is useless, as loading a savegame immediately fixes the issue .. :(
