### ISSUE TITLE
Auto excavate/dig

### ISSUE THREAD

**Issue by Victaria90** [CleverRaven/Cataclysm-DDA#32937]
I think that a Auto dig wreckage/rubble option is really needed. 

When the constant helicopter crashes, burnt buildings, and mole rat lab destruction digging through an area is extremely tedious. 

Would love it even more if could be turned to clear in a 3x3 area as you move just for less key presses.

**Comment by snipercup** [comment]
Good idea. Would use it on craters. Would like to see a option similar to auto pulp that, when enabled, only executes dig if the player has a tool with digging in their inventory or equipped.
