### ISSUE TITLE
move weight capacity modifier to json

### ISSUE THREAD

**Issue by akerigan** [CleverRaven/Cataclysm-DDA#32942]
**Describe the solution you'd like**  
I propose to add a json property which allows creating magic bags with high volume and high carrying weight.
This feature intented for modding purposes.

**Additional context**  
Currently weight capacity modifier is hardcoded.
Available modifiers are:
- trait "DEBUG_STORAGE" which marks your avatar as DEBUG in MSX++DEAD_PEOPLE tiles
- weight_capacity_modifier which sticks to mutations
- flag "AEP_CARRY_MORE" which adds only 22.5 kg
- bionic with "bio_weight" which adds only 20 kg

I can create bag with 1000 litres, but it is useless due to high overall weight of containing items.
I need some weight capacity modifier for my magic 1000 litres bag.
Target modded scenario - a mage who carries his things with him. Instead of creating another boring killer car.

**Comment by alkemann** [comment]
I tried looking into adding a flag that overrides the carry capacities by setting it to max and all sorts of things goes very wonky. Like you are knocked down and cant pick up matches. This issue may be a lot more involved and touch on many other parts of the code.
