### ISSUE TITLE
Change the "cutting" recipe for Sleeveless Leather Trenchcoats to level 2 Tailoring

### ISSUE THREAD

**Issue by Sgt-Cookie** [CleverRaven/Cataclysm-DDA#32957]
**Is your feature request related to a problem? Please describe.**  
Most trenchcoats can have their sleeves cut off at Tailoring 2. Leather Trenchcoats being the only anomaly, requiring Tailoring 5 to cut off the sleeves of an already-existing Leather Trenchcoat.

**Describe the solution you'd like**  
Change Leather Trenchcoats to also only needing level 2 to cut off the sleeves, to match the other trenchcoats. 

**Describe alternatives you've considered**  
Leaving the sleeveless Leather Trenchcoat recipe at level 5. That is to say, the recipe that uses a Cutting Tool to make the sleeveless version.

**Comment by Rail-Runner** [comment]
Is there a reason why cutting off the sleeves needs *any* skill, by the way?

**Comment by Xenomorph-III** [comment]
I don't think so. Anyone can take a pair of scissors to their clothing...
