### ISSUE TITLE
Flashlight rework suggestion

### ISSUE THREAD

**Issue by RarkGrames** [CleverRaven/Cataclysm-DDA#32952]
**Describe the solution you'd like**  
Flashlights that work like lanterns could be reworked to have a beam of light similar to a car headlight, to point in the direction of the last action.
For looking around without moving one or two keys could be assigned to rotate the direction of facing, for some minimal action points. This could be a function of the tool itself.

**Comment by Petethegoat** [comment]
This is something that Kevin has explicitly said won't happen- adding facing to the player character and NPCs is too much micromanagement to be desirable.

**Comment by RarkGrames** [comment]
Well, ok then. That problem got solved fast. :laughing:
