### ISSUE TITLE
Zone construction build wooden wall builds window instead.

### ISSUE THREAD

**Issue by ProfoundDarkness** [CleverRaven/Cataclysm-DDA#32965]
# Describe the bug

When a player or NPC does a Zone Activity - Construction - Build wooden wall, the result of construction is a Window instead.  (The wrong thing is built.)

# Steps To Reproduce

1. Make a player with the ability to construct wooden wall (fabrication 2)
2. Spawn in the necessary supplies (ie 100 planks, 20 wooden panels, 10000 nails)
3. Spawn in apt tool (ie toolbox)
4. Setup a construction zone for Wooden Wall near the supplies.
5. Attempt to execute the construction job.

# Expected behavior

Instead of a phase1 window I expect a phase 1 wooden wall since wooden wall is what I picked.

# Screenshots

![cdda-WallBuildsWindow](https://user-images.githubusercontent.com/13865432/62542473-b0666980-b810-11e9-91d5-21664d6c0b35.jpg)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-6227-gd8a9aea [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Test01-WallBuildsWindow.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3472385/Test01-WallBuildsWindow.zip)

Included a handy save though reproduction steps are easy. (The WallBuildsWindow character.)

**Comment by ipcyborg** [comment]
I have a fix for this. 
Unfortunately the build process seems to be broken now, so I will commit the fix as soon as the master is fixed.

It is just that I have to build from sources with git "HEAD detached", so I am not sure if I can create a branch and commit in this state.
