### ISSUE TITLE
[CAUSE FOUND] Memory leak and crash when falling asleep with a radio on

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#32968]
# Describe the bug

If you sleep with a radio in your inventory turned on, there is a memory leak and game crash.

Note that I'm referring to the tool with item id "radio" / "radio_on". Not a vehicle stereo or mp3 player.

# Steps To Reproduce

1. Make a new player
2. Create a radio via the debug menu (and battery, ambien, rollmat, earplugs if needed)
3. Turn on the radio
4. Sleep

Before sleeping open task manager or other memory monitoring program to check memory usage.

# Expected behavior

# Screenshots

# Versions and configuration

```
- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.D-6237-g7682029 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]
```

# Additional context

For other players:

If you are affected by this and autosave before sleeping you can turn off/remove the radio from the .sav file with a text-editor.

**Comment by perryprog** [comment]
I can't reproduce this after a 9 hour sleep. Memory sticked around at 634MB or about 2 to 4% usage. Could be OS specific?
```
- OS: macOS
    - OS Version: Name: macOS; Version: 10.14.6; Build: 18G84; 
- Game Version: 0.D-6239-ga1ada1a67e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```

**Comment by ampersand55** [comment]
Maybe. I don't currently have access to another OS to check.

New info: The radio itself causes the memory leak.

Simply waiting in-game with with the radio on makes the memory spike.

**Comment by Qrox** [comment]
Cannot reproduce on windows 10. Can you attach a save that reproduces the problem? I do noticed that radios do not seem to be producing sound and draining battery any more, but that's probably a separate issue.

**Comment by ampersand55** [comment]
Sure.

[Test world.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3475163/Test.world.zip)

**Comment by Qrox** [comment]
Nope, still cannot reproduce on the exact version as shown in your crash log.

**Comment by ampersand55** [comment]
Peculiar...

The problem persists for me after downloading a new version via the CDDA launcher.

Thanks for trying anyway.

**Comment by ZhilkinSerg** [comment]
Can you send us your `config` folder please?

**Comment by ampersand55** [comment]
I noticed that the error disappeared when deleting and resetting the config folder, so I did a little testing and it turns out that @'s soundpack caused the error.

@'s soundpack has 3-7 mb, 18-43 seconds long .wav files playing `inaudible_chatter ` as radio sound effects, which probably caused the memory spike when played in succession while sleeping/waiting.

From @'s soundpack `effects.json`

	{
	  "type": "sound_effect",
	  "id": "radio",
	  "variant": "inaudible_chatter",
	  "volume": 90,
	  "files": [
	    "effects/misc/radio_inaudible_chatter_1.wav",
	    "effects/misc/radio_inaudible_chatter_2.wav",
	    "effects/misc/radio_inaudible_chatter_3.wav",
	    "effects/misc/radio_inaudible_chatter_4.wav"
	  ]
	},

You could close this as it's not a fault within the main game, but I think limiting the game to only play 1-3 sound effects of a specific "variant" at a time would be good. I've also noticed that thunder gets extremely loud when sleeping and several thunder strikes are played at the same time.

@'s soundpack links:

* https://discourse.cataclysmdda.org/t/soundpack-s-soundpack-vehicle-sounds-licensed-music-and-more/20131
* https://github.com/damalsk/damalsksoundpack
* https://github.com/damalsk/damalsksoundpack/blob/master/effects.json
