### ISSUE TITLE
A boat has not enough wheels?

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#32976]
# Describe the bug

I'm unable to drive my little boat - appearently it does not have enough wheels.

# Steps To Reproduce

1. Build a boat out of a wooden frame, a wooden hull, a wooden seat and either a sail or oars.
2. Pull it into water and try to start it.
3. Enjoy the message "The (vehicle name) doesn't have enough wheels to move!"

# Expected behavior

I should be able to drive a floating boat using oars or a sail.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-6194-g365d69d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, +attitude [sees_player],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

Adding the boat hull on a vehicle tile does block me from adding wheels on the same tile, so I couldn't even add wheels if I wanted to.

Also, adding a sail anywhere in a multi-tile boat does block me from adding oars. Why? Wouldn't you want to have the option of rowing if there is no wind?

Also also, the description of a sail when installed in a boat says "If your vehicle consists of a single tile, this wheel is enough to allow it to move" - which is obviously not the case.

I'd be very thankful if someone could fix this - my criminal mastermind would like to escape his island prison...

**Comment by ymber** [comment]
Is the board tile of your boat on a deep or shallow water tile? This is expected behavior on a shallow water tile. Push your vehicle onto a deep water tile and it should work as expected. Shallow water tiles are considered land by the vehicle code and amphibious vehicles are supported so if you're driving on a tile considered land it will check for wheels, and if you're driving on a water tile (only deep water) it will check for boat boards.

**Comment by Qrox** [comment]
Perhaps the message should be made more clear, like "Your <vehicle name> doesn't have enough wheels to move on land!"

**Comment by BaumgeistOne** [comment]
Indeed, it works in deep water, thanks! :)

Boats used to work in shallow water, so I did not expect this to be the problem. The error message should probably reflect that - ideally mentioning "shallow water":

"The (vehicle name) needs more wheels to move in shallow water!"

Also, maybe boats should work in shallow water if they are light enough?

**Comment by BaumgeistOne** [comment]
#33692 should fix this.

Thanks, @mlangsdorf !
