### ISSUE TITLE
Autodrive doesn't path through manhole overmap tiles.

### ISSUE THREAD

**Issue by ProfoundDarkness** [CleverRaven/Cataclysm-DDA#32971]
# Describe the bug

Basically it seems auto-drive doesn't consider "road, manhole" tiles to be valid.  When trying to set a route directly onto said tile or if the only road path is through such a tile, autodrive fails to set a route.

# Steps To Reproduce

1. Make a new player capable of driving.  May need to check/regen map to have an apt tile nearby.
2. Spawn a vehicle.
3. Take control of the vehicle.
4. Open the map.
5. Locate a "road, manhole" tile and try to set a path to it with shift-w.
6. Bonus, if your map has a section of road that is only reachable by going through the manhole tile, try setting a route to the other side of the manhole tile from where you are.

# Expected behavior

That auto-drive will set a route and (attempt to) drive the path as if the manhole tile were a road (or bridge) for that matter.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-6227-gd8a9aea [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Test01-AutodriveAvoidsManholes.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3473305/Test01-AutodriveAvoidsManholes.zip)

Included a save (character AutodriveAvoidsManholes) since the setup can be finicky (I kinda goofed around more than needed to set it up).  There should be several manholes spread around the nearby towns, to the south-east (directly) there is a road stretch that requires going through a manhole tile to reach.

**Comment by ipcyborg** [comment]
What about "dirt road"? Probably `ROAD` flag is required for terrain, like existing `RIVER` flag?
