### ISSUE TITLE
designating a firewood source should not require light

### ISSUE THREAD

**Issue by joe9000** [CleverRaven/Cataclysm-DDA#32979]
currently, "constructing" a firewood source can't be done in the dark, which seems weird. suggest removing the requirement for lighting.

**Comment by ZhilkinSerg** [comment]
I would say this should be moved to zone management instead.

**Comment by joe9000** [comment]
i agree as a long term solution that adding a Loot: Usable Wood zone type and potentially a Loot: Usable Batteries and a Loot: Usable Liquid Fuels would be a great idea, replacing firewood source under construction.

not sure how much dev time would be needed for that solution, so i think removing the darkness requirement would be an adequate near term fix.

**Comment by wapcaplet** [comment]
Cannot reproduce in 0.E-9572-g483cd09a89 - it is possible to construct a firewood source in complete darkness. Appears to have been fixed by #33372
