### ISSUE TITLE
Cabin spawns items on the floor

### ISSUE THREAD

**Issue by Xenomorph-III** [CleverRaven/Cataclysm-DDA#32980]
# Describe the bug

Cabins with display racks (meant to hold items) dump their things on the floor.

# Steps To Reproduce

1. Load the save.
2. Go through the south door.
3. Items are spilled all over the ground.

# Expected behavior

Items are placed neatly on shelves.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

<img width="514" alt="cabin" src="https://user-images.githubusercontent.com/25373560/62581633-fb11df80-b8fd-11e9-9353-d72970ee2edd.PNG">

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-5751-g1015287
 - Graphics version: Tiles
 - Mods loaded: [e.g.dda, aftershock, no_npc_needs, safe-autodoc, manual_bionic_installation, no_ants, no_fungi]

# Additional context

Save file: [Centerview_zipped.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3474415/Centerview_zipped.zip)

**Comment by EirenexTheDragon** [comment]
The building itself is the cause of the problem. to check for yourself, try moving the shelves away and you can see, that under it is a cave wall of some sort.
