### ISSUE TITLE
Advanced Inventory Management causes CTD

### ISSUE THREAD

**Issue by ArcanErasmus** [CleverRaven/Cataclysm-DDA#32981]
# Describe the bug

When opening Advanced Inventory Management in the vicinity of certain items or tiles, a crash occurs.

# Steps To Reproduce

1. Load up the save file
2. Open the adv inventory management menu (default `/`)
3. Select the left side of the menu (`Tab`)
4. Clear the sort filter (`r`)

# Expected behavior

The menu should show all of the items in the vicinity. Instead, it crashes the game.

# Screenshots

![image](https://user-images.githubusercontent.com/8963206/62583987-b431d480-b880-11e9-9895-f0ae797be1e1.png)
Last screen before pressing `r` to clear the filter and causing the crash

# Versions and configuration

```
-----------------------------------------
19:31:33.258 : Starting log.
19:31:33.258 INFO : Cataclysm DDA version 0.D-6240-gd4a8eb0
19:31:33.305 INFO : Number of render drivers on your system: 4
19:31:33.305 INFO : Render driver: 0/direct3d
19:31:33.305 INFO : Render driver: 1/direct3d11
19:31:33.305 INFO : Render driver: 2/opengl
19:31:33.305 INFO : Render driver: 3/software
19:31:33.308 INFO : Language is set to: 'en'
19:31:33.824 INFO : SDL version used during compile is 2.0.5
19:31:33.824 INFO : SDL version used during linking and in runtime is 2.0.5
19:31:33.930 INFO : Active renderer: 0/direct3d
19:31:34.243 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
19:31:34.423 WARNING : opendir [./mods/] failed with "No such file or directory".
19:31:59.872 WARNING : opendir [./save/Brentwood/mods] failed with "No such file or directory".
19:32:05.761 INFO : Loaded tileset: MSX++DEAD_PEOPLE
19:32:14.851 :  GAME REPORT: 
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-6240-gd4a8eb0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Ants [No_Anthills],
    No Bees [No_Bees],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills],
    [DP_MOD] Alternative Floor Tiles [DP_Old_Floor],
    sees-player icon, -attitude [sees_player_less_attitude],
    SpeedyDex [speedydex]
]

19:32:20.828 : Log shutdown.
-----------------------------------------
```

 - OS: Windows 10
 - Game Version: 0.D-6240-gd4a8eb0 [64-bit]
 - Graphics version: Tiles
 - Mods loaded: See log list above

# Additional context

[AIM_CTD.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3474540/AIM_CTD.zip)
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3474541/config.zip)

 - This bug is NOT limited to this location, or to merely clearing the search filter. Opening the menu with no filter applied will cause the same crash.
 - This bug has happened to me for all of the past week (have not played on any other save files), across basically every build released during that time.
 - I have triangulated it to one or two tiles within the vehicle next to the player in the save file. However, the exact tile or tiles that cause the crash have migrated, and I am unsure whether it was due to changing the vehicle location, reorganizing items in the vehicle, or both.
 - Earlier on, I was able to trigger this bug by specifically having an A7 Laser Rifle and a CX4 Storm on the same tile, and opening the adv inv menu (after doing process of elimination on all of the items in the problematic tile many hours of play time ago).

**Comment by Edgar-cy-Lee** [comment]
I have tested this myself, and there is important factor missing from this report.
It is the sorting type. I have not seen this "ammo/charge type" sorting type before and new features are usually the ones with most issues.

And Voila, this can be reliably reproduced.
How to reproduce this issue:
1. Drop UPS draining weapon(A7 laser) on Advanced inventory management area.
There must be no item in the same area. IF there is, you will crash at step #2.
2. Set sorting type to "ammo/charge type".
3. Drop any item on the same location.
The game will crash.

Additional issues with Advanced inventory management sorting type to "ammo/charge type":
Having non-weapon and ammo using weapon will lead to "Invalid ammunition" error messages.

**Comment by ArcanErasmus** [comment]
Wow, thank you so much! I didn't even remember that the sort was there, and now I can at least avoid it for now.
