### ISSUE TITLE
Suggestion - Time Brake ("Break time")

### ISSUE THREAD

**Issue by Zourin2** [CleverRaven/Cataclysm-DDA#33002]
**Is your feature request related to a problem? Please describe.**  
A number of player initiated tasks take very, very long periods of time to complete, or may continue indefinitely until some mechanic stops you (like becoming too dark or too tired). 

Jobs such as 'do forever', reading, extremely long crafts (I've seen some up in the 24 hour range), mechanic work, etc, do allow you to press '5' to interrupt the process, but all too often this can result in extreme hunger, fatigue, burning of nearby fuel sources, or unexpectedly burning of daylight when the player may have other priorities to manage and not spend all day digging one hole. 

During these actions, the player has no control or input other than to press '5', and it's not hard to either forget, or see the clock go to AM to PM before you realize you had other things to do (like eat or do other gamey things). It's a little unfulfilling when I wake up, pound down breakfast, start a job, then a few RL moments later find it's dusk and I've done nothing but build half a screwdriver set and starve myself, or spent all day digging one pit.

**Describe the solution you'd like**  
A time brake feature that gives the player a Y/N/I prompt offering them to an interrupt/put down a long-running/indefinite job. Approximately 2 (in game) hours of continuous player non-
interaction seems appropriate. This can give a character some time to eat, consider other priorities, and plan time ahead to work on jobs a few hours at a time rather than commit to a dawn-to-dusk marathon.

**Describe alternatives you've considered**  
Leaving it as-is. It's not broke, but time management features could make it better.

**Comment by ZhilkinSerg** [comment]
It would be even better if player character would address their needs automatically during long actions by themselves.

**Comment by Zourin2** [comment]
The thing I'm mostly pointing at are those 8-24 hour long jobs, or the 'until darkness or death' activities where if you often start them without realizing you need to interrupt them. You can end up advancing a LOT of time, burning a lot of fuel or power, and possibly putting yourself in a 2am scramble with very little control.

I'm all for automatic consumption during long tasks, mind you, but that seems a little more complicated when you look at it. Which foods? How much and when? etc. It seems a lot easier to put in a 'take a break?' in than for the game to decide whether to eat the meat pie or the dogfood. What if you're very thirsty and all you have on you is hard booze?

**Comment by capSAR273** [comment]
Before the player starts a long craft the game could check their current needs, and then warn that they will need to be dealt with to prevent negative effects. Then the player can either ignore the warning, or let the game stop a craft to handle needs.

If we wanted to add some kind of automatic management with needs it could work like this:

**Auto Food/Drink**
We could let the player mark items that they are fine auto-consuming. This way really good items aren't consumed in case the player wanted to save them for later. 

**Auto Sleep**
When the player starts a long craft it could warn them they would need sleep during the process, then they have to either relocate near a sleeping spot to allow automatic rest, or ignore the prompt and continue anyways.

**Comment by kevingranade** [comment]
I could see a menu similar to the wait menu to set time to proceed before
hand, but interrupting periodically would be extremely annoying on very
long crafts.

You can do this currently by setting an alarm using the wait menu.

**Comment by kevingranade** [comment]
The proposal here is not ok, interrupting every craft periodically because the player as far as I can tell is simply not paying attention is not a reasonable tradeoff.

**Comment by esotericist** [comment]
> The thing I'm mostly pointing at are those 8-24 hour long jobs, or the 'until darkness or death' activities where if you often start them without realizing you need to interrupt them. You can end up advancing a LOT of time, burning a lot of fuel or power, and possibly putting yourself in a 2am scramble with very little control.

as Kevin said, this is what the alarm functionality is for. Have an alarm clock providing item (watch, phone, what have you) worn or in your inventory, press `|`, set a timeframe for when you want to be interrupted. Yes, if you want *frequent* interruptions you'll have to do this a few times, but the mechanism is there, for basically the exact problem you describe having.

> I'm all for automatic consumption during long tasks, mind you, but that seems a little more complicated when you look at it. Which foods? How much and when? etc. It seems a lot easier to put in a 'take a break?' in than for the game to decide whether to eat the meat pie or the dogfood. What if you're very thirsty and all you have on you is hard booze?

The plan is to set up a specific loot zone that auto-eating/auto-drinking pulls from, so it only goes after the stuff you actually put there. As for "when", it's possible to threshold based on character state. NPCs are capable of eating and drinking when they need to (provided food/drink are available and you haven't disabled NPC needs), so this can be solved.
