### ISSUE TITLE
Reducing the spawn of various locations on the map.

### ISSUE THREAD

**Issue by NEONZARIN** [CleverRaven/Cataclysm-DDA#33008]
**Is your feature request related to a problem? Please describe.**  
-  _Too many helicopters become uninteresting to the player. There is satiety from finding a helicopter, and this is very bad for the gameplay. Now finding a helicopter is no different from finding a pack of cigarettes._  - **Done**  https://github.com/CleverRaven/Cataclysm-DDA/pull/33032
And the absurd amount of ammunition .308 200+

-   Zombies kill themselves when they go there through the fragments of a helicopter. You can just stand and skip a move, wait until they die. 

- _Too many anthills on the map._- **Done** https://github.com/CleverRaven/Cataclysm-DDA/pull/33062

**Describe the solution you'd like**  
- ~~Reduce the number of generated helicopters by 60% or 70%. Finding a helicopter should be a very rare event, which in this case will bring the player some happiness.~~ - **Done**

- Reduce the amount of ammunition on the Helicopter crashes spawn. For example, no more than 45 ammunition in each turret of a helicopter.

- The zombies that are next to the helicopter should have some kind of protection against splintering on the ground. They should not just die when they go back and forth through shards.

~~- Reduce the number of anthills generated on the map.~~

**Describe alternatives you've considered**  
N/A

**Additional context**  
This issue is still under construction.
Todo: Fungal tower 1, Lab 1, Slime pit 1, Hive 1, Toxic waste dump?, Apartments building 1, Drugdeal?, Farm 1,

**Comment by TychaiosIlithios** [comment]
I'd even say reduce some helicopters by 90%, i.e. osprey should be a really rare sight, while some of the more frequent workhorses might be around and thus cut by only 60% or so.

As for ammunition there's a problem - it's military job to carry around ammo.. some use it up, some get looted, but to never see an ammo box? Well it's good for balance but defo against realism unless up until the very end the military is running in some sort of police mode and is restricted from above from carrying any comfortable amount of bullets - politics make such crap feasible, but should it be implemented in game balance, it has to be somehow supported in the story in newspapers, broadcasts and other notes.

**Comment by Petethegoat** [comment]
Are rounds even readily accessible on an Apache or something similar? I assume they're held internally somewhere that might require certain tools or equipment to load or unload?

**Comment by ZhilkinSerg** [comment]
Map extra spawn weights are easily configurable via json, so it would be great if you would come up with saner numbers:

https://github.com/CleverRaven/Cataclysm-DDA/blob/3597e0ffa80b6bdbc441ad398561269b9db09789/data/json/regional_map_settings.json#L409-L563

**Comment by NEONZARIN** [comment]
> Map extra spawn weights are easily configurable via json, so it would be great if you would come up with saner numbers:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/3597e0ffa80b6bdbc441ad398561269b9db09789/data/json/regional_map_settings.json#L409-L563

According to the experience of the game, a meeting with zombie soldiers in the forest and in other places away from cities is a rather rare event.
I think it will be good to set the same number as this line mx_military

```
       "mx_helicopter": 8, 
       "mx_military": 8, 
```

**Comment by NEONZARIN** [comment]
I also decided to reduce the spawn of other objects on the map.

**Comment by NEONZARIN** [comment]
Too many anthills on the map. Standard value screenshots    `"occurrences": [ 0, 3 ],`

![image](https://user-images.githubusercontent.com/16442992/62742123-0bcd6d00-ba46-11e9-8d51-a592d624c822.png)
![image](https://user-images.githubusercontent.com/16442992/62742150-20aa0080-ba46-11e9-8e31-c4c22427ad9e.png)
![image](https://user-images.githubusercontent.com/16442992/62742169-34edfd80-ba46-11e9-96bb-a690d00fe5f8.png)

Screenshots of my proposal `"occurrences": [ 0, 1 ],`
![image](https://user-images.githubusercontent.com/16442992/62742372-fe64b280-ba46-11e9-88b0-a15ec719f00c.png)
![image](https://user-images.githubusercontent.com/16442992/62742388-0de3fb80-ba47-11e9-8756-2a3396f0d117.png)

![image](https://user-images.githubusercontent.com/16442992/62742415-2d7b2400-ba47-11e9-9d57-950a1be9881f.png)

**Comment by FrozenSnowFox** [comment]
Both Triffids and Fungals can be pretty excessive too.  Then there's stuff like Labs, I had like 4 or 5 of them in one area not that long ago.  Considering how much has changed in the game and how many more overmap specials have been added it probably wouldn't be a bad idea to comb over the entire special file and make adjustments.

**Comment by NEONZARIN** [comment]
> Slime pits

This is also a problem, I counted 5! pit on my map.
![image](https://user-images.githubusercontent.com/16442992/62744114-d9c00900-ba4d-11e9-9515-b6b7965159ca.png)

**Comment by Zombiemanpig** [comment]
Definitely agree about the ant hills, every large city I find seems to have one in it.

**Comment by NEONZARIN** [comment]
So far I'm testing spawn Slime pits - Lab - Farm - Hive and other. Each location is generated once on an over map. So far, for me, everything looks more or less normal.

![image](https://user-images.githubusercontent.com/16442992/62747900-1f390200-ba5f-11e9-8a52-61cc6c024ab2.png)
![image](https://user-images.githubusercontent.com/16442992/62748030-c87ff800-ba5f-11e9-839d-f3f029253e54.png)
![image](https://user-images.githubusercontent.com/16442992/62748059-dc2b5e80-ba5f-11e9-8733-6334498e2750.png)
![image](https://user-images.githubusercontent.com/16442992/62748083-f107f200-ba5f-11e9-9c71-9cad07e1482a.png)
![image](https://user-images.githubusercontent.com/16442992/62748095-ffeea480-ba5f-11e9-9dbe-535518f966eb.png)
![image](https://user-images.githubusercontent.com/16442992/62748117-0f6ded80-ba60-11e9-92c5-4c45788ad908.png)

**Comment by FrozenSnowFox** [comment]
Is that before or after changing the numbers?  These two are taken from what I assume is the same overmap since I debug revealed it.  Pic 1 has 4 fungal areas, 1 lab, 1 strange temple, 1 triffid grove and 1 bee hive.  Pic 2 has 3 slime pits, 2 fungal areas, 2 bee hives and a strange temple.

![Pic 1](https://user-images.githubusercontent.com/44048645/62751186-1e778e80-baa6-11e9-931d-1f1e85382984.jpg)
![Pic 2](https://user-images.githubusercontent.com/44048645/62751192-22a3ac00-baa6-11e9-9c99-584da7aa5a8b.jpg)

**Comment by Petethegoat** [comment]
Maybe you could look into the overly common drug deal spawns as well? Very boring and predictable, and they pop up constantly as well.

**Comment by NEONZARIN** [comment]
Bee Hive, Slime Pit, Fungal Bloom, Fungal Tower, Fungal Flowers, Lab, Ice Lab, Strangle Temple spawn `"occurrences": [ 0, 1 ]`
![image](https://user-images.githubusercontent.com/16442992/62776830-584f9180-bab4-11e9-8f6a-af1b3b1e9b3e.png)
![image](https://user-images.githubusercontent.com/16442992/62776535-7f599380-bab3-11e9-8d60-99a932d7a15e.png)
![image](https://user-images.githubusercontent.com/16442992/62776265-b9766580-bab2-11e9-81dd-cf76713a6b27.png)
![image](https://user-images.githubusercontent.com/16442992/62776128-571d6500-bab2-11e9-9b2d-3fcd092c6ed6.png)

**Comment by NEONZARIN** [comment]
![image](https://user-images.githubusercontent.com/16442992/62794650-49310980-badd-11e9-82ea-7df483c79bc9.png)

**Comment by RarkGrames** [comment]
If the number of choppers gets reduced, the ammo problem will be solved. Sometimes you find a chopper and it is a treasure because you get a lot of ammo. But in general you don't swim in ammo, because you find choppers very rarely.

**Comment by FrozenSnowFox** [comment]
I checked through the map special file here's a list of a ton of others that spawn too much according to occurrences listed.  The big issue ones are the military stuff.

Motel, LMOE Shelter, Sewage Treatment Plant, Sugar House, FEMA Camp, Military Bunker, Military Outpost, Radio Tower (not sure about this one), Mine Entrance, Evac Shelter (multiple types each 1-3), Toxic Waste Dump, Sai (no idea what it is), Campsite (multiple types each 0-3-5), Regional Dump, Desolate Barn, 2fmotel,

**Comment by NEONZARIN** [comment]
![image](https://user-images.githubusercontent.com/16442992/63611677-190d5e80-c5e5-11e9-8b2e-6ef20510dc0c.png)
![image](https://user-images.githubusercontent.com/16442992/63611762-49ed9380-c5e5-11e9-8c9a-2639f626f322.png)
![image](https://user-images.githubusercontent.com/16442992/63611796-61c51780-c5e5-11e9-873b-0dc490f17694.png)

![image](https://user-images.githubusercontent.com/16442992/63611858-8620f400-c5e5-11e9-982f-fdd25ee11826.png)
![image](https://user-images.githubusercontent.com/16442992/63611893-9933c400-c5e5-11e9-8b15-3dbbc3437ef4.png)
![image](https://user-images.githubusercontent.com/16442992/63611915-a650b300-c5e5-11e9-9f93-71d6b0ab273c.png)
![image](https://user-images.githubusercontent.com/16442992/63611978-c7190880-c5e5-11e9-92cb-ed982b65dcb3.png)
![image](https://user-images.githubusercontent.com/16442992/63612008-d6985180-c5e5-11e9-82e3-a08d49d55ec0.png)
![image](https://user-images.githubusercontent.com/16442992/63612027-e57f0400-c5e5-11e9-847b-ad7e3e9564d1.png)



More changes spawn over maps.
