### ISSUE TITLE
i18n Keybindings: Key codes instead of character codes

### ISSUE THREAD

**Issue by akirashirosawa** [CleverRaven/Cataclysm-DDA#33004]
**Is your feature request related to a problem? Please describe.**  
When you play the game, you need to constantly switch between the local language and English. Local language for search translated items, and English for actions. Because all the keyboard shortcuts are English. I think, it's possible to get around needs constantly switch languages on keyboard. In other games, it does not matter which language (keyboard locale) is current, and if M key is a [M]ap, then even if the current locale is Russian or other, where on the M-key is not M-character (for example, 'Ь' char in Russian) the map will still open. 

**Describe the solution you'd like**  
It's possible to use key codes (they are constant, and not depends from current keyboard language), instead of char codes for shortcuts? Then playing the non-English version of the game would be SO MORE comfortable.

**Describe alternatives you've considered**  
Alternatively, may add automatically switch the keyboard language when cursor in input field to the selected in the settings, and then switch back to English, but this is not the best solution.

**Additional context**  
If you need to find something, you need to switch the language, enter text, switch the language, then press the hotkey, see that nothing comes, think that you forgot to switch the language - switch the language, and then it turns out that you already switched the language and just pressed the wrong key and switch the language again. Here's some gameplay like that...

**Example on browser js**
I don't have C/С++ at hand, so an example of what I mean right in the browser:
<img width="787" alt="chars and key codes" src="https://user-images.githubusercontent.com/38557723/62627611-62498700-b932-11e9-97a8-c676ad6294d3.png">
Char depends on keyboard local language, keyCode - not, so for shortcuts more comfortable to use key code. I’m not sure if it is comfortable to get locally-independent key codes in native C ++, or need to include some library, but I think, this is clearly possible.

**Comment by Qrox** [comment]
> may add automatically switch the keyboard language when cursor in input field to the selected in the settings, and then switch back to English, but this is not the best solution.

This is actually better for non-alphabet languages where you need an IME to input text. In this case it is very necessary to disable IME when not in a text input context, otherwise you'll also need to constantly switch between raw keyboard input and IME.

**Comment by akirashirosawa** [comment]
> it is very necessary to disable IME when not in a text input context

I didn't work with IME before, I tried it in the browser and in the OS desktop (macOS) - IME turns off automatically (probably by OS) when cursor not in input field and shortcuts and key codes works well with non-alphabet languages . Don't know how it's implemented on Cataclysm. Is it possible to give OS manage this?

**Comment by akirashirosawa** [comment]
> need to include some library

From dependencies in COMPILING.md, follows Cataclysm use SDL, that provides SDL_Scancode and SDL_Keycode:

> SDL_Scancode values are used to represent the physical location of a keyboard key on the keyboard.

> SDL_Keycode values are mapped to the current layout of the keyboard and correlate to an SDL_Scancode.

> The main difference between these two values comes into play in situations where the operating system is mapping the physical keyboard keys to different virtual letters. For instance, when a standard QWERTY keyboard is mapped to a German QWERTZ layout, the "Y" key will generate events with a scancode of SDL_SCANCODE_Y, but a keycode of SDLK_z. Which one to use is left to the application: scancodes are suited in situations where controls are layout-dependent (eg. the "WASD" keys as left-handed arrow keys), whereas keycodes are better suited to situations where controls are character-dependent (eg. the "I" key for Inventory).

url https://wiki.libsdl.org/CategoryKeyboard

So speaking in terms SDL: need to use scancode for keyboard shortcuts to be (local)character-dependent. I still don't know how this will work with IME - maybe fine.

**Comment by macrosblackd** [comment]
The biggest hurdle will be ncurses, which doesn't support keycodes as far as I can tell.

**Comment by Melodeiro** [comment]
I agree with every word, and would also add, that when you forget to switch back, you can missclick somethings because punctuation marks are being moved between different locations on a different layouts as well.

Would really love such update.
