### ISSUE TITLE
Town with no buildings

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#33016]
# Describe the bug

There is a town nameplate but no buildings.

# Steps To Reproduce

No idea.

# Expected behavior

Towns should have buildings duh.

# Screenshots
![image](https://user-images.githubusercontent.com/47362783/62666191-510f7300-b950-11e9-95f1-235d6e276085.png)

![image](https://user-images.githubusercontent.com/47362783/62666196-5967ae00-b950-11e9-8de7-cae57910c59e.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-6277-g87276a7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Manual Bionic Installation [manualbionicinstall]

**Comment by natovan** [comment]
Let's just imagine that this town was destroyed by cataclysm.

**Comment by alkemann** [comment]
> Let's just imagine that this town was destroyed by cataclysm.

Lacks ruins.
