### ISSUE TITLE
Character speaking under influence of traits is breaking immersion and roleplay in the game.

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#33028]
Traits like Killer Drive or Pyromaniac force character to speak and think lines what are completely unneceserry and usually break immersion and roleplay. What if I play as silent type of serial killer, what if my desire to murder acts differently, what if pyromaniac I play feel guilt when he set fires. All of this information should be completely dependent on the player.
As I wrote on discord "Killer drive should not define character, his/her way of speaking, his/her way of thinking. One thing killer drive should do is add buff or debuff  to character happiness dependent on did he or she killed something today or not."

I think all lines of dialog should be removed from traits and replaced by only  occasional game messages like "You didn't kill today. You fell bad about this." or "You crave fire." game should tell it to the player, not characters to themselfes.
Killers and arsonists comes in all shapes and sizes, and with their own unique to each personal way of speaking and thinking. Let players decide that, please.

**Comment by kasanryukin** [comment]
If your pyromanic feels guilt from setting fires then he clinically isn't suffering from pyromania.

**Comment by SomeDeadGuy** [comment]
@kasanryukin what if he feels mix of guilt and pleasure? There can be many mixed feeling and many ways to express those feeling.
I do not want to be locked on someone else's set of thoghts about that my character think and speaks.

**Comment by kasanryukin** [comment]
If there is any guilt, then it clinically isn't pyromania according to the DSM-V. I'm not saying you can't rp the way you want to rp; just that the example is a bad one due to rigid definitions of the impulse disorders.

**Comment by kevingranade** [comment]
It's not a bug that the game is opinionated about how to present a particular trait.
If we were trying to have a neutral depiction of these particular conditions, we wouldn't have them at all, and in fact I'm on the fence about keeping them at all.
