### ISSUE TITLE
UPS soldering iron cannot be used for disassembly

### ISSUE THREAD

**Issue by etnmich** [CleverRaven/Cataclysm-DDA#33029]
Game version: 0.D-6277-g87276a7

The disassembly menu doesn't recognize that you're carrying a charged UPS and a UPS-powered soldering iron, and instead shows the "You need a soldering iron with x charges" message.
As a workaround, UPS charge can still be used if there is a normal soldering iron with enough charges nearby.

**Comment by ampersand55** [comment]
Same for me.
