### ISSUE TITLE
Rendering problem on MacOS official builds

### ISSUE THREAD

**Issue by akirashirosawa** [CleverRaven/Cataclysm-DDA#33034]
# Describe the bug

In official builds for MacOS (on releases tab and jenkins-latest) when game is runing on the resolution of 16:10, there is a black bar at the bottom. I thought it was a feature of the Cataclysm, but when I build Cataclysm myself - the bar disappeared, fonts looks great (before they are cropped and shrunk), and two new renderings appeared (opengles2, metal).

# Steps To Reproduce
Download and run MacOS build on 16:10 display.
Settings:
Terminal width 160 (1280px)
Terminal height 50 (800px)

# Expected behavior
Run w/o bottom black bar.

# Screenshots
Official build **software** renderer: black bar and font cropped
<img width="1280" alt="build soft" src="https://user-images.githubusercontent.com/38557723/62707708-86709b00-b9fa-11e9-99ba-2f874cbcc3ac.png">

Official build **opengl** renderer: black bar and font shrunk
<img width="1280" alt="build opengl" src="https://user-images.githubusercontent.com/38557723/62707809-bd46b100-b9fa-11e9-8915-001a63c9d33a.png">

Self build `make app NATIVE=osx OSX_MIN=10.14.6 RELEASE=1 TILES=1 CLANG=1 USE_HOME_DIR=1 SOUND=1 LANGUAGES=all` all looks great
<img width="1280" alt="self build" src="https://user-images.githubusercontent.com/38557723/62708010-24fcfc00-b9fb-11e9-8f2d-b5ad04d22e5b.png">

# Versions and configuration
- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14.6; Build: 18G87; 
- Game Version: 0.D-6277-g87276a7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

All releases are most likely build on Linux server and this is probably a cross-compilation issue. But I hope it can be solved. Not everyone can build game for themselves. By the way, for some reason, downloaded build is 35% larger than my local build on mac with all languages (168 MB vs 228 MB).

**UPD**: In the official build, long actions take a lot of time in real time. When compiled on a Mac, long actions, such as sleeping or reading, become 10 times faster. It's like another game with a full screen without a black bar, with normal fonts and fast as hell! If only I knew about such differences!

**Comment by esotericist** [comment]
That's really weird about the rendering.

As for the speed: Some of that is optimization flags. We still support older versions of MacOS, and for builds that *can* run on 10.11 or earlier, we run into bugs in the standard library on macos that causes it to crash.

We don't really have a good way to fix it short of dropping support for old versions of macos for official builds, or adding a newer pair of builds to the matrix. :(

**Comment by akirashirosawa** [comment]
Closed by #46083

**Comment by BrettDong** [comment]
I just downloaded the latest OSX Tiles experimental version and it is still problematic:

On the first run, the game entered full screen, but everything were squeezed to top left corner:
<img width="1440" alt="螢幕截圖 2021-01-19 下午8 12 25" src="https://user-images.githubusercontent.com/21075502/105113438-f231b100-5a92-11eb-9ed9-e73fa813dfd5.png">

I quitted the game and opened it again. This time, there was a black bar region at the bottom, and everything seemed being vertically compressed:
<img width="1440" alt="螢幕截圖 2021-01-19 下午8 13 12" src="https://user-images.githubusercontent.com/21075502/105113504-11c8d980-5a93-11eb-9464-ab52b5ec814e.png">

**Comment by akemn** [comment]
> I just downloaded the latest OSX Tiles experimental version and it is still problematic:
> 

The official (not experimental) macOS tiles version also behaves exactly as you described.

**Comment by akirashirosawa** [comment]
I was compiling locally on macOS without `-march=native` flag and for some reason I thought the problem was gone. This is clearly not enough. Firstly, I did not remove the `OSX_MIN=11.1` parameter, and secondly, the official builds are build by cross-compilation on Linux. My bad.

**Comment by BrettDong** [comment]
I updated SDL libraries on narc0tiq's Jenkins build machine and then problem is solved (build 11385):
<img width="1440" alt="螢幕截圖 2021-01-21 下午12 33 16" src="https://user-images.githubusercontent.com/21075502/105388600-d76f5180-5be4-11eb-8cbe-7e15fe0f1f6d.png">
Metal renderer is also available:
<img width="1440" alt="螢幕截圖 2021-01-21 下午12 36 10" src="https://user-images.githubusercontent.com/21075502/105388984-4ba9f500-5be5-11eb-995c-d8197cf0e3cb.png">
