### ISSUE TITLE
World resets after segfaulting during save and coming back

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#33046]
# Describe the bug

After attempting to quicksave in my LMOE shelter, my game segfaulted. After re-launching the game and expecting no save, my character, action log, save was actually still there. However, I am covered in solid rock.

# Steps To Reproduce

1. Attempt to quicksave. Get segfaulted and crash.
2. Relaunch save.
3. You are now encased in solid rock.

# Expected behavior

Not segfaulting, and coming back to my LMOE shelter base.

# Screenshots

![image](https://user-images.githubusercontent.com/51099123/62727176-de9da200-b9e6-11e9-8377-ddadf02d078b.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-6301-g3597e0f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    No Survivor Armor [no_survivor_armor],
    Classes and Scenarios Mod [more_classes_scenarios],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3483164/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3483165/debug.log)
[Kezar Falls.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3483187/Kezar.Falls.zip)

**Comment by AMurkin** [comment]
Was this attempt to save the first after the generation of the world?

**Comment by LaVeyanFiend** [comment]
Correct.

**Comment by perryprog** [comment]
A possibly related issue that I just found could be related. When suiciding with `Q Y Y` I get a segfault. Using `<left> <enter>` instead of `Y` works fine, so I wouldn't be surprised if this is unrelated. I'll make a new issue if so, after a fix for this is made anyway.

**Comment by ZhilkinSerg** [comment]
Should be fixed in #33145
