### ISSUE TITLE
Put Fire out keybind is the same as smash, making it a fire hazard

### ISSUE THREAD

**Issue by curstwist** [CleverRaven/Cataclysm-DDA#33065]
# Describe the request
The "put fire out" menu command is `s`, so is `s`mash.  Some quick menu mis-navigation can result in players smashing their lit braziers instead of extinguishing them.

# Steps To Reproduce

1. set up brazier.
2. feed it wood.
3. get distracted and smash it instead of extinguishing it.
4. stop, drop & roll.

#Request:
Rebind key to something less potentially hazardous.

# Screenshots
Menu in question:
![menu](https://user-images.githubusercontent.com/39442864/62748242-e892c580-ba25-11e9-8787-1db328c6ada8.PNG)
 
dramatic re-enactment:
![fire](https://user-images.githubusercontent.com/39442864/62748251-f5afb480-ba25-11e9-8ab1-f137d660cfc5.PNG)

**Comment by Zombiemanpig** [comment]
I agree that some menus that cannot be custom keybinded should be able to.

One such is the work table menu.

**Comment by esotericist** [comment]
> I agree that some menus that cannot be custom keybinded should be able to.
> 
> One such is the work table menu.

Customized keybindings for this are extremely difficult and require substantial redesign of basically the entirety of how we handle transitory menus.

I understand the desire (I wouldn't mind it either), but it's not a trivial ask.
