### ISSUE TITLE
New labels sidebar mode display issue

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#33078]
# Describe the bug

New labels (wide) sidebar mode uses the same translated field names as in other modes.
At least for language set to Russian,
English in comparison with Russian and wide vs. narrow:
Russian words not so short in general.
And the sidebar uses one variant of the label for wide (have some space to pad) and narrow more (which have not much space to pad labels).
`Food :` is overwritten with lang=En too.

# Steps To Reproduce

1. Switch sidebar mode to labels.
2. See field labels and values overwriting each other.

# Expected behavior

Different field labels variants suited for different modes. Non overlapping fields.

# Screenshots

![image](https://user-images.githubusercontent.com/1931904/62784799-d14bea80-baae-11e9-8615-5c79d817fdfd.png)

# Versions and configuration

- OS: Linux
  - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.2 LTS; Release: 18.04; Codename: bionic; (that was WSL in Win 10)
- Game Version: 0.D-6376-gd7dc3df419 [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by alkemann** [comment]
This is not limited to translation. My preferred style "labels" does not do the needs well in english either.
![sidebar](https://user-images.githubusercontent.com/48854/64063978-2b4a5680-cbfc-11e9-81cb-d095f44490e2.jpg)

**Comment by alkemann** [comment]
Turns out that the "labels" view uses the "wide" part for the needs. Taking a look at making a PR for this now
