### ISSUE TITLE
Can't refill tank with a canning pot through the examine vehicle menu

### ISSUE THREAD

**Issue by RtosRtos** [CleverRaven/Cataclysm-DDA#33075]
# Describe the bug

You can't refill a car with a canning pot through the examine menu. The only way to do it is to unload the canning pot into a "nearby car" through the inventory menu, which could be problematic (although I haven't test it) if you want to pour into a specific tank.

# Steps To Reproduce

1. Siphon some gasoline into a canning pot.
2. Examine the car, press "f" to refill the tank.

# Expected behavior

You should be able to select the canning pot as a refueling container, just like with any other kind of container (bottles, etc.)

 - OS: WIN10
 - Game Version: 0.D stable
 - Graphics version:  Tiles
 - Mods loaded: Default ones (filthy cloth, etc)

**Comment by RarkGrames** [comment]
The situation is the same when you are canning large batches of jars and want to pour the water back into the kitchen unit's tank from the pot.
