### ISSUE TITLE
Recipes that can be quickly crafted become very difficult to learn

### ISSUE THREAD

**Issue by BQurious** [CleverRaven/Cataclysm-DDA#33081]
Recipes with high difficulty and low craft time have very low learn chance
Related: [#25074](https://github.com/CleverRaven/Cataclysm-DDA/issues/25074)
# Detailed description

Chance to learn a recipe from crafting is proportional to its craft time, resulting in quickly crafted items (like antiseptic powder) becoming very difficult to craft, even with high skills

(eg.: antiseptic powder crafted with cooking (11/6) and 12 intelligence has a learn chance of ~1/65... This is the average chance, meaning some unlucky players like myself may have to craft it hundreds of times)

# Expected behavior

Items, especially those where relevant skills far exceed those required, should have more reasonable chance to learn. Or there should be some other way to increase learn chance to more reliable levels. If anything, items that can be quickly made should also be easier to learn

# Possible alternatives

Make the time required to craft the item irrelevant (recommended, as it would make most sense in future with other recipes that are very quick to complete)
or
Set a floor on the minimum learn chance based on relevant skills/stats
or
Use batch time when checking learn chance

I can look into this issue and submit a PR if need be, although I'd be setting up a whole project for a (possibly) minor change. I would like the community's opinion on what needs to be done (if at all) before I start though

Relevant code: [/src/crafting.cpp #850](https://github.com/CleverRaven/Cataclysm-DDA/blob/b7869d869e7446aba5e2dee2e808a1ac46e39c60/src/crafting.cpp#L850)

# Versions and configuration

 - OS: Android 6.0.1
 - Game Version: 0.D
 - Graphics version: Tiles
 - Mods loaded: dda, GenericGuns, DisableNPCNeeds, FilthyClothing, SimplifiedNutrition, CraftableGuns, SafeAutodoc, BrightNights, Deadleaves' Fictional Guns, pots, boats, Makeshift Items, Medieval Tools, More Survival Tools, Mythological Replicas, Modular Turrets, Salvaged Robots, Mining, More Locations, Fuji's buildings, Folding parts, Vehicle Additions, Tanks, StatsThroughSkills

**Comment by kevingranade** [comment]
This is working as intended, there is certainly some nuance that could he
applied, e.g. seperating out "active crafting" time like preparing
materials and manipulating tools from "passive crafting" like waiting on
something to cook or preheating a forge, but "time spent crafting" is
exactly what we want to use for learn chance.

**Comment by BQurious** [comment]
So... it's acceptable for a recipe whose skill requirements are far
exceeded is still difficult to learn?
We don't even want to use batch times in the calculation?

**Comment by sztosz** [comment]
Shouldn't it be easier to craft/learn with each consecutive craft? If we want to keep it close to real life, practice make you remember how to craft stuff. And I believe the lest time-consuming things are easiest to remember, not the other way round.

**Comment by kevingranade** [comment]
It's not about understanding the recipe, it's about memorizing it, which makes relative skill level less or not at all important.
I'm not clear what you mean by, "use batch times in the calculation", do you mean if you craft multiple copies of an item you only have the chance to memorize it as if you had crafted it once? If that is happening it's a bug.

**Comment by sztosz** [comment]
I don't think there is any correlation between time of crafting and how easy it is to memorize given crafting recipe, at least not in real life, and i strongly believe that easy (little ingredients, little steps to achieve final product) and fast to make recipes, are easier to memorize, than the time-consuming ones. But it all depends on too many factors to be quantifiable. But still I guess we can agree that practice makes perfect. 

In current implementation `if( x_in_y( making.time, time_to_learn ) )`  I see that the longer it takes to craft something easier it is to memorize it, and if that how you (we?) want to gamify crafting, so be it. But if want to keep it realistic I think it should be the other way round, and also factor in how many ingredients there are and how many times before given recipe was crafted before.

**Comment by BQurious** [comment]
> I'm not clear what you mean by, "use batch times in the calculation", do you mean if you craft multiple copies of an item you only have the chance to memorize it as if you had crafted it once? If that is happening it's a bug.
I don't have the debugger and project set up yet, so I haven't verified.. But from code-diving and experimental testing, it seems the buggy behavior is the one in action.
Code in [/src/Crafting.h](https://github.com/CleverRaven/Cataclysm-DDA/blob/b7869d869e7446aba5e2dee2e808a1ac46e39c60/src/crafting.h#L39) seems to suggest that the 'recipe' object holds info for one item, with separate functions to handle batches

**Comment by jeremyshannon** [comment]
Huh. I guess this explains why Rob Keys with his 15 int still hasn't learned the antiseptic powder recipe, despite it being trivial (Cooking 12/6, first aid 6/1) and him making tons of the stuff. (He tends to leave "care packages" in shelters, and dump stuff off for refugee centers as he drives on by) 
 It's definitely strange and video-gamey that it's harder to learn a simple 1 minute recipe than a complicated 6 hour one.

**Comment by Edgar-cy-Lee** [comment]
This sounds like easy solution to fix in terms of both game and real life side. Just add flat crafting time to all un-memorized recipes. Say, +10 minutes to look up recipes, check if you are making it correctly, etc. So something like antiseptic powder would take 1+10 minutes to craft. After memorizing, you can use normal crafting time.

**Comment by jeremyshannon** [comment]
That's so simple, and it's brilliant.

**Comment by BQurious** [comment]
Sorry for the long delay, I have some issues with my ISP. Is adding a flat time to un-memorized recipes the resolution, then?

**Comment by baldamundo** [comment]
> "time spent crafting" is exactly what we want to use for learn chance.

Could you expand on the logic behind this? Doesn't seem at all intuitive to me (nor apparently to others in the thread).

**Comment by kevingranade** [comment]
If you spend an hour baking a cake and an hour baking a large number of cupcakes we expect you to be as likely to learn the cake recipe as the cupcake recipe assuming they're the same level of complexity.

**Comment by BQurious** [comment]
Having gone through the recipe several times over, wouldn't I have
memorized it better than if I had made it once? It's literally how I
memorize things in real life. Multiple quick refreshers
Skill gain, however, is proportional to the time spent on it. Having spent
so many hours mixing, I would start to notice several nuances that would
make me a pro baker, as opposed to having spent just a second at it

**Comment by sztosz** [comment]
If you spend hour backing your cake, mixing ingredients once, and then just watching oven, you probably waste your time, but still you did that only once. 

If you spend 6 x 10 minutes, six times mixing the same ingredients you have much bigger chance to remember how much of what you need to mix.
