### ISSUE TITLE
A soldering iron should not be able to repair materials that has a far higher melting point than it can reach. 

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#33109]
# Describe the bug

A soldering iron should not be able to repair materials that has a far higher melting point than it can reach. 

# Expected behavior

A soldering iron can currently repair aluminum, copper, hard steel, iron, kevlar, plastic and steel, of those only plastic is realistic.

The tip of a typical small battery-powered soldering iron reaches about 350-500 ºC. This is below the melting point of most metals.

A soldering iron should probably also not be able to repair kevlar either as it's a woven synthetic fibre. 

I would suggest letting a simple needle/sewing kit/tailor kit be able to repair kevlar as it's just a matter of attaching kevlar plates.

# Additional context

For reference:

Material | Melting point (ºC)
--- | ---
plastic (polyethylene) | 115-135
solder |  180-185
tin | 231.9
lead | 327.5
aluminium | 660.3
silver | 961.8
gold | 1064
copper | 1084
stainless steel | 1510
iron |  1538

Material | Decomposition temperature  (ºC)
--- | ---
neoprene | 200+
nomex | 400
kevlar | 450-500 

Some powered soldering irons:

* https://www.pcbtoolexpert.com/best-battery-powered-soldering-iron/

**Comment by ampersand55** [comment]
Should I just make a PR and just remove all repairable items except plastic from the soldering iron?

**Comment by MisterRIckson** [comment]
While many things that can be repaired with a soldering iron should not be, simply removing everything that a soldering iron could not melt ignores how soldering works. The idea is to melt the solder and let it flow into the cracks and joints between two materials. Soldering is primarily for electronics repair, but can be used for small steel objects like eyeglass, or copper pipes in a pinch.

**Comment by ampersand55** [comment]
That's true. But the game repairing system works by attaching scrap of that material onto the thing you want to repair. E.g. if you want to repair a copper knife you solder scrap copper onto it, and it doesn't consume solder.

We could maybe introduce a new material called "electronics" that you repaired with solder using the soldering iron.

**Comment by Moonsabrt** [comment]
A question 'w')
How would you repair everything else?
You have to maintain your equipment somehow or in someway.
If this does go through there should be a thing that lets players at least repair their stuff and let it go away to disrepair.  You need to repair your new sword or armor somehow!! Not giving players that option is kinda bad for gameplay disregarding 'reality'. 'w')

> While many things that can be repaired with a soldering iron should not be, simply removing everything that a soldering iron could not melt ignores how soldering works. The idea is to melt the solder and let it flow into the cracks and joints between two materials. Soldering is primarily for electronics repair, but can be used for small steel objects like eyeglass, or copper pipes in a pinch.

I agree with this and I think is the general perceived thing for how you can repair stuff with a solder 'w')

**Comment by ampersand55** [comment]
> 
> 
> A question 'w')
> How would you repair everything else?

Metals can still be repaired with a welder or acetylene torch.

**Comment by Moonsabrt** [comment]
> > A question 'w')
> > How would you repair everything else?
> 
> Metals can still be repaired with a welder or acetylene torch.

I see.
Well that at least makes that a viable thing, was worried. As for kevlar yeah i would say its less you using a soldering iron to put things into place and more stitching loops or 'buckles' to attach plates to or repairing holes and replacing them.
A thing I would also like to note is about 'epoxy' or 'glues' (like gorilla glue) you would attach to pieces of metal in a effort to repair them. Have a crack or missing a hole? Fill it in or attach piece one and piece two with this, let it harden and bam! 
I could see them spawning in houses or in garages and the like. Allowing early players to repair their fireaxe, looted sword or etc at a early game stage. I know most of the people I know keep a syringe or three of the stuff around.
Also forge welding is another 'low game' option where players with a decent fabrication and mechanics can attach piece one to piece two by hammering them into place :D

**Comment by Moonsabrt** [comment]
Sorry about that last part, came up with some ideas about alternatives for repairing stuff. 
But yeah with the kevlar issue moved to "sewing kit or tailors kit" i could see it essentially working like that. 'w')/
