### ISSUE TITLE
Memory / notes

### ISSUE THREAD

**Issue by devenv** [CleverRaven/Cataclysm-DDA#33119]
**Is your feature request related to a problem? Please describe.**  
I'm always forgetting what items I have at the base.

**Describe the solution you'd like**  
A keybinding which when pressed in the inventory view would add the highlighted item to a list (which can be opened by a different keybinding). May be with grouping, like food... When used/destroyed - it's greyed out so I can know to restock...

**Describe alternatives you've considered** 
An in-game notebook (a paper + q:writing as a prerequisite maybe?), actually I was sure it was in the game, as it sounds like a must-have, but couldn't find it :) correct me if I'm wrong...

**Additional context**  
Another semi-related issue is when I'm working on a project (e.g. to craft something) and keep forgetting what I need for that, or even what the project was (my short term memory is horrible). So adding the item to the list as greyed out would be useful.

**Comment by ampersand55** [comment]
Another solution is to be able to create a zone and have every item within that zone added to some sort of inventory list. Preferably a sortable list like the advanced inventory.

**Comment by sztosz** [comment]
I use actual real life pen and paper ;) But it would be nice to be able to add lists of items. And, not to break immersion having a paper (the one found in offices) and for example pen/pencil (new item) in inventory would be necessary to be able to write notes, any notes, or even draw accurate map, forgetting overmap just like you do forget detail of places you visited now.
