### ISSUE TITLE
Spawned in a locked underground room

### ISSUE THREAD

**Issue by Valbod-I-am-a-Swiftie** [CleverRaven/Cataclysm-DDA#33112]
# Describe the bug

I spawned in a underground shelter, and the room was completely locked and without doors.

# Steps To Reproduce

1. Select a scenario "Sheltered"
2. There's no way out.

# Expected behavior

I think, there should be doors in this room

# Screenshots

![изображение](https://user-images.githubusercontent.com/30054440/62821158-0de41880-bb79-11e9-8059-e7f26cbf322e.png)

# Versions and configuration

 - OS: Windows 10 1903
 - Game Version: 0.D-6405-g3439b4c
 - Graphics version: Tiles
 - Mods loaded: 
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food]

# Additional context
I tried to move these cabinets and racks in the room, but can't find the doors

**Comment by ZhilkinSerg** [comment]
Ladder?

**Comment by GrayAegis** [comment]
I'm pretty sure that LMOE shelters have secret doors in them that look like metal walls. Try walking into them.

**Comment by Valbod-I-am-a-Swiftie** [comment]
Thank you, GrayAegis, this shelter really has secret door. 
![изображение](https://user-images.githubusercontent.com/30054440/62825760-76eb8080-bbb9-11e9-87f3-e7d630871851.png)
