### ISSUE TITLE
Remove special food recipes and have food inherit qualities

### ISSUE THREAD

**Issue by FrozenSnowFox** [CleverRaven/Cataclysm-DDA#33127]
**Is your feature request related to a problem? Please describe.**  
If you want to make something gluten free or use human flesh you require a special recipe to do so.  This means you need a duplicate of every viable recipe which adds lots of clutter and is incompatible with further recipe additions.

**Describe the solution you'd like**  
I would like to see food inherit qualities from its ingredients.  So if you use gluten free ingredients its gluten free, if you use human flesh it has human in it, if you use cockroach meat it would probably taste less appetising.

**Describe alternatives you've considered**  
Sticking with having a separate recipe for every food item.

**Comment by kevingranade** [comment]
This means we would have to have a ui that recognizes what ingredient
differences are meaningful and prompts the player to make (potentially
many) decisions s about what ingredient to use.

That's not to say it's impossible, but it's a very involved change that
would have a lot of impact on the crafting ui.

**Comment by FrozenSnowFox** [comment]
I was initially thinking the current interface would work and it probably would for simple stuff like meat since its already picked by the player.  Although once you start adding gluten, dairy ect it gets a lot more complex and a lot less obvious.

Since the food changes the current cooking ui is already fairly inaccurate.  Results can vary quite wildly depending on your chosen ingredients.  I suppose something like this would be better suited after the cooking ui has been improved to be more informative and provide better feedback.
