### ISSUE TITLE
Integer Overflow on fire's duration

### ISSUE THREAD

**Issue by keldoclock** [CleverRaven/Cataclysm-DDA#33130]
Integer Overflow on fire's duration

# Steps To Reproduce

1. Put things in brazier
2. Light fire
3. Examine fire after a while

# Expected behavior

On Android experimental builds fires don't behave properly. They go out with material unburned. Adding fuel to a fire does nothing. Firewood source does not prevent fire from going out during crafting. 

# Screenshots

https://i.redd.it/i7y5jqq0jub31.jpg

# Versions and configuration

 - - OS: Android
    - OS Version: Manufacturer: Q-Innovations; Model: QS5509A; Release: 8.1.0; Incremental: v1A71-0; 
- Game Version: 0.D-6156-gcb9471d [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    C.R.I.T Expansion Mod [crt_expansion],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Crazy Cataclysm [crazy_cataclysm],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Sleep Deprivation [sleepdeprivation],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

Issue also reported in Reddit thread which screenshot is taken from
https://www.reddit.com/r/cataclysmdda/comments/cgceex/uh_how_long_exactly/

Also 

https://www.reddit.com/r/cataclysmdda/comments/cl609h/i_uhhhhh_guess_thats_good/

Seems related

**Comment by ipcyborg** [comment]
From Code Guidelines:

>Use int for everything.
>If you need an integral value larger than 32 bits, you don't. But if you do, use int64_t.
>Uint is also a problem, it has poor behavior when overflowing and should be avoided for general purpose programming.

But actually the signed int overflow is "undefined behavior".
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1407r0.pdf
https://stackoverflow.com/questions/16188263/is-signed-integer-overflow-still-undefined-behavior-in-c
https://en.cppreference.com/w/cpp/language/ub

While the unsigned int overflow handling is "modulo power of two".
https://en.wikipedia.org/wiki/Integer_overflow

Proof test case:
>TEST_CASE( "to_string_approx1" )
{
    int n = 2000000000;
    for(int i=0; i < 15; ++i)
    {
        n += 100000000;
        printf("i, n = %d, %d\n", i, n);
    }
}

Failed to compile:
error: iteration 1u invokes undefined behavior [-Werror=aggressive-loop-optimizations]

While this test compiles fine:

>TEST_CASE( "to_string_approx2" )
{
    int a = 2000000000;
    for(int i=0; i < 15; ++i)
    {
        a += 100000000;
        std::string s1, s2;
        printf("Approx = %d, %d, [%s] [%s]\n", i, a, s1.c_str(), s2.c_str());
    }
}


Running "to_string_approx2":
SIGSEGV - Segmentation violation signal

It could also lead to some strange situations. 
Like when the comparison in for-loop is always true ("i" is signed too in this example). 
So it just goes on and on with printing: "undefined behavior" could do some really bad things.

This one at least has no "undefined behavior". And still overflows, of course:

>TEST_CASE( "to_string_approx3" )
{
    unsigned int n = 2000000000;
    for(unsigned int i=0; i < 15; ++i)
    {
        n = n + 100000000;
        printf("i, n = %d, %d\n", i, n);
    }
}

Filters: to_string_approx3
i, n = 0, 2100000000
i, n = 1, -2094967296
i, n = 2, -1994967296
i, n = 3, -1894967296
i, n = 4, -1794967296
i, n = 5, -1694967296
i, n = 6, -1594967296
i, n = 7, -1494967296
i, n = 8, -1394967296
i, n = 9, -1294967296
i, n = 10, -1194967296
i, n = 11, -1094967296
i, n = 12, -994967296
i, n = 13, -894967296
i, n = 14, -794967296


And we can't just detect, catch and handle this overflow. We can expect and predict it - to avoid. 
Or just use a bigger integer to postpone it, which is not good.

**Comment by anothersimulacrum** [comment]
I can't reproduce this, can someone confirm this is still happening (is it android specific)?

**Comment by Lamandus** [comment]
> 
> 
> I can't reproduce this, can someone confirm this is still happening (is it android specific)?

Android specific

**Comment by anothersimulacrum** [comment]
Okay. Confirmed it there on the most recent build.

**Comment by claudiorodriguez** [comment]
It has also been happening on Mac OS X, just replicated on the latest build

**Comment by ZhamelSeh** [comment]
I am getting the same issue in the latest builds on Windows, I have seen this for gasoline and battery power on my vehicle(s).

**Comment by kevingranade** [comment]
@anothersimulacrum since you can reproduce it on your system, can you post your processor details? maybe there's some errata we can dig up that explains this.

**Comment by anothersimulacrum** [comment]
Okay, let me know if you need more info.
![img](https://user-images.githubusercontent.com/42699974/71649855-df511080-2cc6-11ea-8741-acd10264faf0.png)

**Comment by kevingranade** [comment]
My best guess at this is that something is actually causing runaway inflation of fire lifetime (technically making it more negative).  We might be able to knock it out by simply capping fire field lifetime at something reasonable like 24 hours.
