### ISSUE TITLE
faction ownership doesn't deter hungry player, guards oblivious

### ISSUE THREAD

**Issue by Petethegoat** [CleverRaven/Cataclysm-DDA#33134]
# Describe the bug

I'm allowed to cook, eat, and craft with owned items in direct view of members of the owning faction, without repercussions.

# Steps To Reproduce

Go to refugee center storage, and eat food right in front of the guards.

# Expected behavior
Guards and other NPCs berate me for trying to eat their food, and prevent it.

# Versions and configuration

Posting from phone, but win 7 on a very recent master.

**Comment by adamkad1** [comment]
id wager its because you dont actually pick up things when you use nearby items to craft
