### ISSUE TITLE
Random characters are almost always generated with fewer initial points than custom characters.

### ISSUE THREAD

**Issue by Vaylon** [CleverRaven/Cataclysm-DDA#3313]
After generating twenty random characters (New Game -> Random Character) in the stable 0.8 release for Windows, I found that the average number of initial points given to a random character is 3.5. I have vanilla settings (6 initial points).
- I was given 6 initial points four times.
- The most commonly-assigned number of initial points is 5.
- The lowest number of initial points given was -3, which I received on two generation attempts.
- I was never given more than 6 initial points.

Randomly generated characters are also never assigned skills or a profession; however, I don't know whether or not this is intended.
##

**Comment by mugling** [comment]
Considerable changes to chargen since issue opened
