### ISSUE TITLE
Thermal and night vision can be worn simultaneously

### ISSUE THREAD

**Issue by devenv** [CleverRaven/Cataclysm-DDA#33148]
**Is your feature request related to a problem? Please describe.**  

Thermal goggles and night vision can be used at the same time.
1. it's op
2. not realistic

**Describe the solution you'd like**  
Should behave like other non-compatible wearables.

**Additional context**  
See this in action here: https://youtu.be/pwpq_XK1ojA?list=PLMk50gTih9upJ6D9fV1Rp_LyvMFdjlzRC&t=2444

(I couldn't find if it was ever fixed or discussed, the video is from June)

**Comment by kholat** [comment]
But, you need NVGs to see all the normal zombies, and you need infrared to see shady zombies. I imagine my character has something like gpnvgs but 2 tubes are NV and 2 tubes are IR https://tnvc.com/shop/l-3-gpnvg-18/

**Comment by devenv** [comment]
Well, in this case it should be a craftable thing maybe?
