### ISSUE TITLE
You can be both near-sighted and far-sighted

### ISSUE THREAD

**Issue by sztosz** [CleverRaven/Cataclysm-DDA#33149]
# Describe the bug

You can be both near-sighted and far-sighted.

# Steps To Reproduce

1. Start creating new character
2. Choose near-sighted trait.
3. Choose far-sighted trait.
4. Start game.

# Expected behavior

You should not be able to choose both near-sighted and far-sighted

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-6452-gcdbd895fd4-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Beta National Guard Camp [national_guard_camp],
    No Rail Stations [No_Rail_Stations],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Simplified Nutrition [novitamins]
]

**Comment by Szara-ManOfHonor** [comment]
This isn't entirely correct.
It's uncommon, but a person can be nearsighted in one eye, and farsighted in the other. This condition is known as antimetropia.
Also, astigmatism is functionally (as far as the result on a person's visual acuity is concerned) nearsightedness and farsightedness at the same time. Seeing as there is no astigmatism trait (yet?), having both nearsightedness and farsightedness is the closest to replicating this condition that is achievable in CDDA.
