### ISSUE TITLE
Refugee Center broker dumps food on the ground

### ISSUE THREAD

**Issue by RarkGrames** [CleverRaven/Cataclysm-DDA#33142]
# Describe the bug

Upon selling food items to the Broker in the RC they get dumped on the floor. If you bring liquids, you get back the containers and the food will be spilled on the floor.

# Steps To Reproduce

1. Sell food to the broker.
2. It gets dumped on the floor.

# Expected behavior

The food items disappear.

# Versions and configuration

    OS: Windows
        OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
    Game Version: 0.D-6273-g40119a3 [64-bit]
    Graphics Version: Tiles
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
    ]

**Comment by mlangsdorf** [comment]
I have a couple of ways to fix this.

**Comment by I-am-Erk** [comment]
I will give him a debug merchant inventory
