### ISSUE TITLE
Mutation Bad Knees applies when walking diagonally.

### ISSUE THREAD

**Issue by SlackingSleeper** [CleverRaven/Cataclysm-DDA#33158]
# Describe the bug

The bad knees mutation applies when walking diagonally as if the increased travel time is because of rough terrain.

# Steps To Reproduce

1. Turn on circular distances.
2. Take an orthogonal step and a diagonal step and compare the travel time.
3. Mutate a character with Bad Knees.
4. Repeat step 2.

# Expected behavior

The travel time when walking diagonally should be roughly 1.4 times the orthagonal travel time in both cases. This is because of the pythagoran theorem.

# Versions and configuration

 - OS: Widows 8.2 and android 7.0
 - Game Version: Encountered both on 0.D android (CleverRaven) and 0.D-6421-gfd8e664.
 - Graphics version: Tiles
 - Mods loaded: [dda, disable NPC needs, more locations, Fuji's more buildings]

**Comment by ZhilkinSerg** [comment]
Remove `movecost_obstacle_modifier` from mentioned mutation and test again.

**Comment by SlackingSleeper** [comment]
> 
> 
> Remove `movecost_obstacle_modifier` from mentioned mutation and test again.

I have no idea where to even start, would you mind giving helping me out? Should I download the source, edit the mutation and build it?

**Comment by dunstad** [comment]
It looks like movecost_obstacle_modifier is a property of the bad knees mutation in data/json/mutations/mutations.json. Changes to JSON files don't require recompiling the game, so you should be able to see the effects as soon as you save the file and start the game up.
