### ISSUE TITLE
Gas Chainsaw/Circular Saw empties charges after one job.

### ISSUE THREAD

**Issue by Zourin2** [CleverRaven/Cataclysm-DDA#33152]
The power tool fuel consumption needs some work. 

Fill the tank (400 units) of a gas powered chainsaw, 
Turn it on and fell any tree. Even a dead one.
It's effectively out of gas after one use (consuming about 370-380 fuel in about seven minutes).

The circular saw has the same problem, emptying entire batteries for a single Log>plank job. Modded for storage batteries, it blows through 500 charges (small storage battery) and runs dry before finishing a single plank cutting job.

I'm pretty sure this isn't intended. I'd at least expect the chainsaw to get 1-2 full trees cut and logged on a tank to be even close to being competitive to a basic axe. That's about 6-12 full chainsaw tanks for an hours worth of work. It's burning about 1 charge per 'turn' (including the turn to turn it on), and it's rendered both as useless toosl.

It would be best if they were 'use-charge' items rather than 'burn-time' items, using ~20-50 units of gas per use, making it a valuable tool. The alternative is to just use a fire/wood axe and disassemble the power tools for parts.

**Comment by kevingranade** [comment]
Got any sources on how much fuel it takes to fall a tree with a chainsaw?  "Competitive with an axe" isn't a valid concern.

**Comment by ampersand55** [comment]
Assuming it has the fuel consumption of a Small 1-cylinder engine (as that's what you get when you disassemble it) it should consume about 10ml / minute. Chopping down a tree takes 7 minutes so it would make sense for it to consume 70ml units of fuel.

**Comment by pjf** [comment]
[This discussion](https://www.arboristsite.com/community/threads/tree-harvester-fellerbuncher-vs-man-chainsaw.176875/) with multiple forestry workers suggests that 100 trees/day is a reasonable rate of work with a chainsaw and no helpers. Let's approximate and call that 10 trees/hr.

[This discussion](https://www.arboristsite.com/community/threads/how-much-fuel-per-hour.64171/) suggests the time a chainsaw will run on a single tank seems to depend upon the saw. 20-40 minutes per tank seems typical. Let's take the middle and say 30 minutes per tank.

From this, I'd expect a chainsaw to fell in the order of 5 trees on a single tank of gas. Obviously cutting those trunks up into usable timber is more work and fuel.

**Comment by ampersand55** [comment]
That seems to correspond to my calculation of 70ml per use. 400 / 70 ~= 5.7 uses per tank.

I got that from a Small 1-cylinder engine running for 1 hour charging a storage battery with a truck alternator which consumed 637 ml gasoline.

**Comment by ampersand55** [comment]
Since both theory and practice seem to agree I'll make a PR.
