### ISSUE TITLE
 Newly Fed Sourdough Starter ready time is inconsistent with description

### ISSUE THREAD

**Issue by Edixo1993** [CleverRaven/Cataclysm-DDA#33160]
The description states that it should take a few hours for your sourdough starter to be usable again after feeding it, but it takes an entire week for it to be ready again, the same time it takes for a newly made one to become ready for use.

**Comment by alkemann** [comment]
I tested on master 2bda93b4da and after feeding a couple startes and waiting first 6 hours, and then another 6 hours, the starters were still "freshly fed". Then I waited another 21 hours and they are still "freshly fed".
