### ISSUE TITLE
USE_PLAYER_ENERGY flag of spell-casting items cannot work well

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#33162]
# Describe the bug

In my own mod I decided to write a spell-casting crystal which will cost the player's hp to throw a fireball. However, after I added the flag "USE_PLAYER_ENERGY" without which casting would cost absolutely nothing, a debugmsg broke out and told me "owner of spell does not know spell". Mages don't need to know a spell in a magic crystal when they activate it, do they? Maybe the judgment about whether the players know the spells should be moved to the timing when they try to cast them, not when they have casted it and try to cost the energy they need.

# Steps To Reproduce

1. Write an item with the use_action of cast_spell and the flag of USE_PLAYER_ENERGY.
2. Make a player with this item.
3. Try to activate this item and cast that spell.
3. The debugmsg appears.

# Expected behavior

Rewrite the function "can_cast()" in the src file magic.cpp.
Remove the judgment about whether the player knows the spell.
Ideally move this judgment to wherever it should be.(but not here!)

# Screenshots

**If applicable**, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/44523519/62875010-cdd98d00-bd54-11e9-8c6b-473d93e47089.png)
![~(W%K_B7WYSLEB%ZD~UP(F8](https://user-images.githubusercontent.com/44523519/62875048-e053c680-bd54-11e9-8645-38bae1c98acd.png)
![R5}`JWXDAB9V1$JK8T60 GF](https://user-images.githubusercontent.com/44523519/62875067-ecd81f00-bd54-11e9-9f31-5ee44f6cfe39.png)

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by RedShakespeare** [comment]
Sorry I missed the version and configuration part.....
OS: Windows 10 (though this bug is assumed to be on all OSs)
Game Version: 0.D-6227-gd8a9aea(though this function is still in this way till now)
Graphics Version: Tiles(though...)
Mods loaded: Any mod with a USE_PLAYER_ENERGY spell-casting item

**Comment by anothersimulacrum** [comment]
It would probably be very helpful if you could upload the mod.

**Comment by RedShakespeare** [comment]
> It would probably be very helpful if you could upload the mod.

Sorry I'm not quite familiar with the issue system <( _ _ )>
Could you please tell me how to upload files here? thx a lot

**Comment by anothersimulacrum** [comment]
https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

Thus may help.

**Comment by RedShakespeare** [comment]
thx! 

Since my mod is yet to be finished,  I wrote a simple test mod which can also cause this debugmsg.
(tho uploading failed for some unknown network problems,  I insert the modinfo.json code which is actually the whole testing mod)

`[
	{
		"type":"MOD_INFO",
		"ident":"test_asdasd",
		"name":"some test mod",
		"aothors":["RS"],
		"description":"a mod used to test a bug",
		"category":"items",
		"dependencies":["dda"]
	},
	{
		"id":"some_magic_crystal",
		"type":"GENERIC",
		"category":"spare_parts",
		"name":"crystal",
		"name_plural":"crystal",
		"symbol":"*",
		"color":"white",
		"weight":50,
		"volume":0,
		"price":0,
		"description":"activate this item to see the debugmsg\n\nblah blah blah",
		"flags":["USE_PLAYER_ENERGY"],
		"use_action":{
			"type":"cast_spell","spell_id":"some_spell",
			"no_fail":true,"level":5
		}
	},
	{
    "id": "some_spell",
    "type": "SPELL",
    "name": "Fireball",
    "description": "You hurl a pea-sized glowing orb that when reaches its target or an obstacle produces a pressure-less blast of searing heat.(just a copy from magiclysm)",
    "effect": "projectile_attack",
    "valid_targets": [ "self", "ally", "hostile", "ground" ],
    "flags": [ "SOMATIC",  "NO_HANDS" ],
    "max_level": 20,
    "min_damage": 24,
    "max_damage": 68,
    "damage_increment": 1.2,
    "min_aoe": 3,
    "max_aoe": 5,
    "aoe_increment": 0.1,
    "min_range": 6,
    "max_range": 20,
    "range_increment": 1,
    "spell_class": "NONE",
    "base_casting_time": 200,
    "base_energy_cost": 25,
    "energy_source": "HP",
    "difficulty": 4,
    "damage_type": "fire"
  }
]`
Just wish an item called crystal and activate it, and the debugmsg will burst out.

**Comment by RedShakespeare** [comment]
[somemod.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3495875/somemod.zip)
This is the testing mod's file above.
