### ISSUE TITLE
Hoarder Trait Bug Again

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#33167]
# Describe the bug

Player with the hoarder trait still gets negative morale even if there's no volumes left.

# Steps To Reproduce

1. Make a player with the hoarder trait.
2. Dress the player with some bag and then take off all the clothes.
3. Negative morale still exists.

# Expected behavior

After the player reaches the max volume the morale debuff should disappear according to the description of the trait.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [Either Android or Windows 10]
 - Game Version: [every version recently]
 - Graphics version: [Tiles]
 - Mods loaded: [dda]

# Additional context

**Comment by ipcyborg** [comment]
The hoarder trait adds moral penalty for 1 minute. So the effect is gone after step (3) and 1 minute of waiting. 
Confirmed in 0.D-6496-g63ef97c.

Is it still not working right and the effect needs to be removed right away after reaching 0 volume capacity?

**Comment by RedShakespeare** [comment]
Problem solved. 
Thx a lot.
