### ISSUE TITLE
Crafting dog food using empty canister results in a plain dog food

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33175]
# Expected behavior

A canned dog food that doesn't spoil readily.

# Versions and configuration

0.D-6477-gc3cf67ebaa-dirty

**Comment by jeremyshannon** [comment]
That's definitely not right, I patched this last week, and it was working when I tested it, and now it's not.The recipe still has "contained: true" set, so it should be appearing in a container. It's working for meat soup, but not for dog food or cat food, despite the json entires being practically identical.
 I must be missing something.

**Comment by jeremyshannon** [comment]
Okay, it's weird, but I found the problem. Will fix soon.
