### ISSUE TITLE
Segmentation Fault on [S]ave and Quit

### ISSUE THREAD

**Issue by RoyTheMaverick** [CleverRaven/Cataclysm-DDA#33185]
# Describe the bug

Whenever I start the game with the "Burning Building" scenario, I am given a segmentation fault error upon attempting to [S]ave and Quit.

![cataclysm-tiles_2019-08-12_23-51-19](https://user-images.githubusercontent.com/54052485/62914470-76401f00-bd5e-11e9-8d5c-5a7e0ee8654c.png)

Hitting "ok" on that window yields a runtime library window as follows.

![cataclysm-tiles_2019-08-13_00-08-59](https://user-images.githubusercontent.com/54052485/62914534-a8518100-bd5e-11e9-8055-38529fee7cab.png)

The game then Crashes To Desktop once I hit "ok". Upon starting up the game again, the character remains loaded into the world, but upon loading the character, it indicates the following error message:

![cataclysm-tiles_2019-08-13_00-10-25](https://user-images.githubusercontent.com/54052485/62914570-cc14c700-bd5e-11e9-9995-d3b4074591a1.png)

Then, upon pressing continue, another, different seg fault.

![cataclysm-tiles_2019-08-13_00-11-38](https://user-images.githubusercontent.com/54052485/62914619-01211980-bd5f-11e9-91f7-b94366334f89.png)

Upon pressing "ok", another runtime error message, same as before. Press "ok" and another CTD. Further attempts yield no new messages, just a repeat of the second seg fault, the runtime error and a ctd.

# Steps To Reproduce

1. Make a new world. The only mod I used in the world was Cataclysm: Dark Days Ahead.
2. Create a new custom character in the world. 
3. Select the "Burning Building" scenario. Whether you choose traits, stats, and skills should be irrelevant, since this error happens even if you do not choose any.
4. Spawn in.
5. Immediately press [S]ave and Quit.

You should then see the error.

# Expected behavior

I expected [S]ave and Quit to function normally, saving the world without causing a segmentation fault, and returning to the title menu without crashing the game. This is how the game works when I create a survivor using the "Evacuee" scenario without any traits.

# Screenshots

I left them in the description thing for context, but they weren't really necessary. Log below.

# Versions and configuration

 - OS: Windows 7 Home Premium, Service Pack 1. 
 - Game Version: 0.D-6470-g38912d4
 - Graphics version: Tiles
 - Mods loaded: Cataclysm: Dark Days Ahead

# Additional context

Below is an archive of the save file for the world after initial load in, the save file for the world after the first crash, and the save file for the world after the second crash, as well as the crash.log and debug.log files for the first and second crash. I hope it helps.

[Files.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3495360/Files.zip)

**Comment by ZhilkinSerg** [comment]
Duplicate of #33051.
