### ISSUE TITLE
Smoking rack doesn't work until game reload

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33187]
# Steps To Reproduce

1. Load the game.
2. Inspect the smoking rack.
3. Wait for a couple of hours.
4. Inspect it again and observe it is unchanged (and doesn't produce smoke).

Actually never mind, after reloading the game and retrying it actually works (but strangely so: first it reports that 6 hours is needed for completion, then produces a little smoke during the next few turns, then it's done, WTF.

[2019.08.06.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3496472/2019.08.06.zip)

0.D-6489-gfffed0be4b-dirty

**Comment by RarkGrames** [comment]
Sometimes it starts the smoking as normal, then two hours later gets stuck for a long time, and when I check it the next day (around 8-10 hours later), it is done. Other times it gets stuck right at the start. While stuck it gives the "you see some smoldering charcoals" message. It definitely takes more than six hours.

**Comment by misterprimus** [comment]
Mine's been "smoking" for 2-3 days.

**Comment by ymber** [comment]
This might be related to #32936 and all the other incarnations of that active item processing bug.

**Comment by davidpwbrown** [comment]
Does anyone have a savegame where this can be reproduced? I know its happened to me before, but right now im testing, and no matter what I do, I cannot get the smoker to stop smoking, so I cannot reproduce currently.

**Comment by l29ah** [comment]
The save is attached in the issue report.
