### ISSUE TITLE
Outfit sets

### ISSUE THREAD

**Issue by devenv** [CleverRaven/Cataclysm-DDA#33180]
**Is your feature request related to a problem? Please describe.**  
Picking up the right equipment for construction/mechanic work/night raid/day raid is a hustle.

**Describe the solution you'd like**  
I'd like to save outfit sets and then switch between wearing those quickly.

**Comment by Moonsabrt** [comment]
I wonder how that would work, would it have like a menu where you can like 'make' outfits for stuff?
Like you stand next to a pile and it essentially pulls up a inventory and you can specify what you want? 
You want your char to wear the maid outfit, a kevlar vest, armored underwear and those fancy iron greaves and gauntlets you found under 'outfit' set? 
What would happen if you don't have the items you specified? Would it try to complete it or would it say "dont have the items required".

**Comment by snipercup** [comment]
Right now you could mark your favorite gear with a survival marker or permanent marker (add a label). That allows you to rename the item, so you could make a set like this:
Jeans Raiding
Helmet Raiding
Vest Raiding
Glock Raiding
Steel toed boots Raiding
Backpack Raiding

And have another set like
Military rucksack Hauling
Lab coat Hauling
Cargo pants hauling
Sneakers Hauling
Shopping bah Hauling

Then using the advanced inventory you can filter for hauling or raiding and get those sets specifically. If you want any item in multiple sets you can rename it to say Backpack Raiding Hauling.


Given this maybe it would be interesting to use a marker to add 'set name' to a gear item and somehow filter by set?

**Comment by devenv** [comment]
Ha, nice trick... The only issue is replacing the clothes etc, you'll have to fully undress, open inv -> filter -> wear -> open inv -> filter -> wear -> ...
May be a "wear all" keybinding? Doesn't make sense except in this context :/

**Comment by devenv** [comment]
Or, take all marked by a label, and wear wear wear :)

**Comment by devenv** [comment]
> What would happen if you don't have the items you specified? Would it try to complete it or would it say "dont have the items required".

I guess "don't have the items required, try to wear available items?", another issue - what to do with the worn clothes? Like if I have leg warmers and pants on, and an outfit has only pants, should it replace both?

**Comment by snipercup** [comment]
> Ha, nice trick... The only issue is replacing the clothes etc, you'll have to fully undress, open inv -> filter -> wear -> open inv -> filter -> wear -> ...
> May be a "wear all" keybinding? Doesn't make sense except in this context :/

Not that many keypresses, open advanced inventory, select 'w' for the gear you are wearing, press , to store them in a container, then in the other pane filter for 'hauling' and press , to move them all to 'wearing'.

**Comment by devenv** [comment]
Hmm... Didn't know it's possible... May be a marker is a good enough solution... Looks like a history of labels would solve the issue of writing a lot :) wdyt?

**Comment by devenv** [comment]
After some thinking - marker labels are actually a better solution than outfits, this way you don't ruin immersiveness and it's part of the game exploration which is important...
Closing the issue... :)
