### ISSUE TITLE
Acetylene lamps use welding tanks as magazines

### ISSUE THREAD

**Issue by RarkGrames** [CleverRaven/Cataclysm-DDA#33198]
# Describe the bug

The old-school acetylene lamps (those ones you usually find in antique stores) use the same tanks as the oxyacetylene torches. They can be unloaded to loot welding tanks.

# Expected behavior

Probably a smaller tank, with fuel consumption adjusted to them. I'm not sure if they use the exact same gas as the welding torches.

# Versions and configuration

OS: Windows
    OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
Game Version: 0.D-6273-g40119a3 [64-bit]
Graphics Version: Tiles
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food]
]

**Comment by alkemann** [comment]
Tested in master 2bda93b4da, by placing on the floor all the tanks I could spawn from debug menu and choosing reload, I was given the option to use `small welding tank with oxyaceylene (60)` or `welding tank with oxyaceylene (240)`. It was possible to load and unload the bigger welding tank.

**Comment by anothersimulacrum** [comment]
I think the issue here is more that they take acetylene, whereas real lamps used calcium carbide and water.

**Comment by alkemann** [comment]
There seems to be real Oxy Acetylene lamps too?  But there doesn't seem to me that there is a bug here. A feature request to add more types of lamps maybe? Though an item being able to use small or large tanks interchangeable is a weird item i gues

**Comment by anothersimulacrum** [comment]
I can't find any reference of acetylene lamps that used gas instead of generating it with calcium carbide and water, so I don't think they should be able to be fuel with acetylene gas, and instead with calcium carbide and water.
