### ISSUE TITLE
 grappling hook needs a rework I think. 

### ISSUE THREAD

**Issue by Domotdow** [CleverRaven/Cataclysm-DDA#33204]
Okay I was playing the game and went up level in the mall. I found out you could get the zombies to fall down the opening the middle of the walk ways of the mall this was great way of getting rid of the zombies on the up levels only down side there are now ton of zombies below I had the bright idea of making a rope and climbing out one of the windows with it. But it did now work so then I tried making a grappling hook, hoping that would work no such luck. I looked up the grappling hook and the long rope. Turns out they are only good for if your in a pit / sink hole (not a z-level), as such you won't face any penalties if you get stuck in one and you can easily climb back out. With ropes however, they won't save you from a 1 or even 2 z-level fall.  also the case of broken staircases, i think you lose the grappling hook but in turn are able to move up and down that particular stairwell. 

The interesting game play that is lost here with cleverly ways of avoiding zombies with ropes and the grappling hooks. It would be great if you could use them also to get over gaps like going between roof tops with the grappling hook. 

 Now this me just rambling a bit but what also would be really fun is if that the item climbing gear hand the ability to scale up walls based on its own skill climbing. That your succeeds rate was based on your climbing gear, dex and your climbing skill and also there are books on climbing and its gear. I think would really help with passivism/trapper route or just would help with playing more cleverly instead of killing everything in your way.  

Thanks for taking the time to read this.

PS hang gliders would be cool to.

**Comment by ZhilkinSerg** [comment]
Please fill provided issue template properly before submitting an issue.

**Comment by Domotdow** [comment]
sorry I hit enter before I got to wright what I wanted to say.

**Comment by Domotdow** [comment]
I also just fix the gamer a bit.

**Comment by Domotdow** [comment]
I rushed it a bit trying to get you to see it.

**Comment by Zireael07** [comment]
Issue template is there for a reason. You just deleted it and replaced it with your rambling text.

**Comment by Domotdow** [comment]
O sorry I thought that the template was only for me to see as I wright it. Am I meant to leave it here with what I wright under each of the headers in in the template?

**Comment by Domotdow** [comment]
Okay when I have some time I open up a new one that is cleaner.
