### ISSUE TITLE
Hide NPCs or map features the player shouldn't know about or doesn't have full information about

### ISSUE THREAD

**Issue by antipin00** [CleverRaven/Cataclysm-DDA#33202]
**Is your feature request related to a problem? Please describe.**
When receiving 'Missing Caravan' or 'Kill Bandits' mission, the mission destination is marked on the map, and 5 map tiles around the marker are revealed. What also revealed is the presence of hostile NPCs (bandits, thugs, etc) the player has never met and should not know about (at least in the case with the caravan).

**Describe the solution you'd like**
Some kind of "known by player" flag for NPCs that controls their visibility on the world map. Set it to "true" when NPC comes into viewing distance or if the player receives some info on them (e.g. the Representative stating that there are 3 bandits in the cabin while giving the mission).

**Describe alternatives you've considered**
Add 'expected by player' information to the world tiles (expected tile features, expected NPCs).
This way, the player will have some vague information about map features and possible NPCs, but will not know exactly what is there at the moment.
E.g. using the console in an evac shelter will give the location of the refugee center and show tiles around the road, but not the anthills or beehives that have spawned there after the Cataclysm. 
As another example, speaking with NPCs at the refugee center (or reading maps) will reveal rumored map features and NPC locations, giving the player the opportunity to investigate these rumors (last known caravan site; a cabin with bandits who apparently got themselves two more members the quest-giver NPC knew nothing about; somebody's item stash they revealed to the player, but when they arrive everything's looted; rumored zombie horde locations; a gas station that was marked on a map but was destroyed when the bombs fell...)

I think this will make the exploration aspect of the game more interesting: seeing the world change compared to pre-cataclysm maps, investigating rumors or mission locations, tracking down NPCs, visiting your home town that got nuked while you were away, etc.

Some of this can be implemented by using labels, of course, but it would not work for large objects, e.g. a geographical map of the region that reveals forests, rivers and fields while not revealing post-Cataclysm features and government black sites.

And it shouldn't require heavy code modifications, since the rumored information doesn't affect anything except world map view, and is updated only by actions (speaking with NPCs, reading maps/consoles) or by visiting the world tile. It may be necessary to generate a simplified pre-Cataclysm copy of the world map that lacks post-Cataclysm features for consistency between various maps the player may find.

**Additional context**
A mockup for 'known by player' NPC flag that would improve the caravan mission
![caravan_before](https://user-images.githubusercontent.com/17460779/62968418-aa294c00-be13-11e9-944a-e0d40665bf79.png)
![caravan_after](https://user-images.githubusercontent.com/17460779/62968426-ae556980-be13-11e9-8f12-bf82f67bc3fb.png)

A mockup for a mission given by an NPC whose friend was captured by bandits and now needs rescue (this uses the 'expected features/NPCs' world chunk info):
![mockup_cabin](https://user-images.githubusercontent.com/17460779/62967522-c7f5b180-be11-11e9-90d7-8a992bd290c4.png)

A mockup for visual difference between rumored / explored map features after accessing evac shelter console
![mockup_map](https://user-images.githubusercontent.com/17460779/62964141-15baeb80-be0b-11e9-81ce-975d10818ba4.png)

A mockup for what player expects after reading a pre-Cataclysm map vs what they find after visiting the area
![region_hidden](https://user-images.githubusercontent.com/17460779/62969957-12c5f800-be17-11e9-96d5-d169a558d1d0.png)
![region_revealed](https://user-images.githubusercontent.com/17460779/62969973-16597f00-be17-11e9-853b-5e197d74c1af.png)
In this case, giving the player more geographical maps will remove the annoyance of not knowing the layout of forests/rivers while not discouraging actual exploration of the area

**Comment by RarkGrames** [comment]
The brown overlay could be used for explored but not personally seen tiles. It is really hard to figure out from a tower that a house in the distance is a house and not a gun store.
