### ISSUE TITLE
Magiclysm generating errors with recent content update (9478 and up)

### ISSUE THREAD

**Issue by Shotgunface** [CleverRaven/Cataclysm-DDA#33218]
# Describe the bug

Magiclysm mod is generating error messages on builds 9478 and up with it's recent content update.

# Steps To Reproduce

1. Install any build 9478 and up.
2. Build world with Magiclysm mod active

# Expected behavior

Error messages while building world hits Crafting Recipes, Crafting Requirements, and Items.

# Versions and configuration

 - OS: Windows 10 Home Version 1803
 - Game Version: 0.D-6489-gfffed0b (9478)
 - Graphics version: Tiles
 - Mods loaded: DDA and Magiclysm

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3500466/debug.log)

**Comment by Shotgunface** [comment]
I believe it's related to these changes:
https://github.com/CleverRaven/Cataclysm-DDA/commit/3169f91c4202450426710abe7ee38e37d3f3e6b8

**Comment by KorGgenT** [comment]
This is fixed via #33196
