### ISSUE TITLE
I think most of my NPC followers are Obese or Very Obese.

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#33220]
Game version:
Cataclysm: Dark Days Ahead - 0.D-6495-g278482c967-dirty
Operating system:

Manjaro Linux 64-bit
Tiles or curses:

Tiles
Mods active:

  "dda",
  "no_npc_food",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "hydroponics",
  "mutant_npcs",
  "national_guard_camp",
  "more_locations",
  "FujiStruct",
  "blazemod",
  "Tanks",
  "deoxymod",
  "no_rivtech_guns",
  "no_flaming_weapons",
  "more_classes_scenarios",
  "StatsThroughSkills",
  "growable-pots",
  "No_Fungi"

I'm playing with "No NPC Needs". Most of my NPCs are just standing around at my basecamp.
My basecamp has 312 days of food.
Save game:
[Meadowview.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3500800/Meadowview.zip)

**Comment by ZhilkinSerg** [comment]
And what's exactly the issue?

**Comment by Quintovir** [comment]
> And what's exactly the issue?

I would expect the NPCs to remain at a normal weight with the No NPC Needs mod.

**Comment by ZhilkinSerg** [comment]
I do not think that should be expected - last time "no npc food" mod was updated roughly a year before obesity changes went in and below is mod option description which doesn't tell anything about obesity:

https://github.com/CleverRaven/Cataclysm-DDA/blob/463affe156f727f60361066f3791d8cff661ec92/data/mods/No_NPC_Food/modinfo.json#L15

**Comment by Quintovir** [comment]
Has feeding NPCs become easy enough to make No NPC Needs not really necessary or whoever maintains the mod hasn't got around to changing it?

**Comment by ZhilkinSerg** [comment]
Nobody maintains this mod right now, so you can hop in and fix anything.

**Comment by Quintovir** [comment]
I looked at the mod and things related to nutrition and I don't think it's going to be a simple fix. If I contribute something I'll probably start with something easier to do.
