### ISSUE TITLE
Fruit wine must recipe doesn't require yeast

### ISSUE THREAD

**Issue by StrongEUW** [CleverRaven/Cataclysm-DDA#33223]
# Describe the bug

The recipe for fruit wine must doesn't require yeast (but does produce it after being placed in a fermenting vat).

# Steps To Reproduce

1. Go to fruit wine must recipe.
2. Observe lack of yeast in recipe

# Expected behavior

Fruit wine must recipe does require yeast.

# Screenshots

![2019-08-14 13_02_33-Cataclysm_ Dark Days Ahead - 0 D-6523-g9857661](https://user-images.githubusercontent.com/49459628/63020462-177dc100-be96-11e9-90ab-0efeb8cbf88e.png)

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-6523-g9857661
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Disable NPC Needs

# Additional context

Initially presumed that this was a typo of some sort, but it looks like it's been in since the introduction of brewing. In any case, seems like it should require the same amount of yeast as any other must/wort.

**Comment by anothersimulacrum** [comment]
Fruit wine is a source of yeast. My understanding is that the yeast that naturally lives one the fruit is what ferments the wine, and then can be recovered after it has been fermented.

**Comment by StrongEUW** [comment]
Ancient wines were able to be fermented from grapes specifically because grapes have yeast naturally in their skin, and said skins are left in the must. If the fruit wine must recipe only allowed for wild grapes to be used, that might be borderline fine (it's still going to be a far slower and more inefficient process than modelled, and it absolutely shouldn't produce the enormous surplus of yeast that it does in that case), but basically every other possible component in that recipe is going to 100% require an external source of yeast in order to ferment.
