### ISSUE TITLE
Security bot schematics is useless

### ISSUE THREAD

**Issue by Melodeiro** [CleverRaven/Cataclysm-DDA#33224]
# Describe the bug

Looks like, that schematic is missing a recipe for security bot. I have already found another schematics, and it had a recipe for another bot.

# Screenshots

![image](https://user-images.githubusercontent.com/2702567/63022224-1a36e100-beab-11e9-9ba3-3917f9fd4b2d.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.D-6496-g63ef97c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Garden Pots [growable-pots],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Disable Religious Texts [no_religious_Texts],
    No Fungal Monsters [No_Fungi],
    Safe Autodoc [safeautodoc],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Simplified Nutrition [novitamins],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

**Comment by dunstad** [comment]
It looks like recipe_electronics.json is missing a security bot recipe. I wonder if there used to be one that just got left behind somehow, or if we need to make one from scratch. I'll let you know if I find out.

**Comment by dunstad** [comment]
There's a list of security bot parts in recipe_deconstruction.json, so I should be able to make a recipe from that.
