### ISSUE TITLE
Oxygen cylinder is too dense

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33239]
147120kg/m³, seven times the density of plutonium.
0.D-6519-gc023e44bf2-dirty

**Comment by tenmillimaster** [comment]
Whoa, the normal size one is smaller than the smallest commercially available one (91.5 cubic inches vs 104.1 cubic inches). It's not even close to a reasonable sized one.

**Comment by tenmillimaster** [comment]
I'm going to rename the tiny Emergency pack to be one of those '5 minute escape" bottles, and then also put a medium sized bottle and a large sized bottle.

**Comment by snipercup** [comment]
@tenmillimaster Are you working on this issue? Need any help?

**Comment by tenmillimaster** [comment]
I needed to be reminded I was working on this >.>
