### ISSUE TITLE
refugee center npcs turning hostile

### ISSUE THREAD

**Issue by Mister-Cultist** [CleverRaven/Cataclysm-DDA#33247]
I was returning to the center with all my completed missions to turn in when the arsonist npc suddenly started getting angry and trying to attack me, I had done nothing to provoke it like stealing items in the center so I'm guessing it's a bug. I teleported her into a room nearby since the arsonist isn't that important. Later I realised a bunch of npcs had ran out of the center and were standing in a field for no reason (this has happened to me before, I think they just get lured by noise) so I went too them and started teleporting them back into the center to keep them safe, when I teleported back into the center to check their places Seena Camp turned hostile and tried killing me. Any idea what's going on?

**Comment by Bulletfang** [comment]
I've had a similar problem with the refugee center, certain NPCs turning hostile for no apparent reason  #29639

**Comment by kevingranade** [comment]
Most likely you acquired enough mutations to turn them hostile.

**Comment by Rivet-the-Zombie** [comment]
I recently was murdered by the arsonist NPC when starting out a fresh, mutation-free character.

**Comment by TechyBen** [comment]
> Most likely you acquired enough mutations to turn them hostile.

Interesting. Is this a soft or hard limit? I take it then, 1 or two mutations is ok? Oh, and does visible vs non-visible make a difference?

Thanks for implementing it in a dynamic way. :) I just aint got to a center (even long playthrough usually don't for me XD ) to test myself regularly with the changes.

**Comment by Mister-Cultist** [comment]
> 
> 
> Most likely you acquired enough mutations to turn them hostile.

I have no mutations, I started as an unwilling mutant but I never picked any actual mutant traits

**Comment by davidpwbrown** [comment]
This is linked to #32475 quite possibly, as some of the refugee centre NPCS belong to wasteland scavenger faction.
