### ISSUE TITLE
Finger-less gloves: warmth suggestion, liners, variety and ideas.

### ISSUE THREAD

**Issue by Shotgunface** [CleverRaven/Cataclysm-DDA#33242]
**Is your feature request related to a problem? Please describe.**  
I'm currently at a loss for using my unarmed focused bionic character during the cold seasons due to his finger-less glove options not even remotely helping with frostbite. Pockets help and are a great feature, but I do not see a reason why there are not any at least somewhat warm finger-less gloves without modification. The only options are leather ones with 10 warmth, armored ones with 5 warmth, and leather armor gauntlets with 15 warmth.  Right now the only way to insulate finger-less gloves  is to use the tailoring kit to add a liner. Since a tailoring kit isn't always easy to find it would a nice addition for characters that are unarmed focused with hand augmentations/mutations in the cold seasons.

**Describe the solution you'd like**  
Simply a version of glove liners that are finger-less so that you can wear finger-less gloves without freezing your hands off and still use augmentations or mutations to the hands. Alternatively maybe add a pair of mittens that fold back to fingerless gloves.
Some ideas are:
-The ability to cut off any pair of gloves fingers/fingertips.

-Fingertipless Gloves - Material cloth/leather/knit - has more warmth than it's close cousin the finger-less glove.
![fingertipless_gloves](https://user-images.githubusercontent.com/25081828/63073522-2cd70780-bef7-11e9-9e32-534c1b967f80.jpg)

-Mitten/Finger-less glove hybrid that when activated switch from finger-less to mitten and are encumbering when active (mitten mode) such as longer firing time, unable to shoot or added dispersion. something along those lines.
![Mitten_fingerless_glove_hybrid](https://user-images.githubusercontent.com/25081828/63072370-7cb2d000-bef1-11e9-9bd5-17008a24ce4a.jpg)

-Knit Finger-less gloves

-Cotton Finger-less glove liners
![fingerless_liners](https://user-images.githubusercontent.com/25081828/63072685-1b8bfc00-bef3-11e9-835e-fd0f7cb3b0b9.jpg)

-MMA Gloves
![mma_gloves](https://user-images.githubusercontent.com/25081828/63072569-7d983180-bef2-11e9-88f2-ff89ad6f0165.jpg)

-Tactical Finger-less gloves
![tac_fingerless_gloves](https://user-images.githubusercontent.com/25081828/63072573-8426a900-bef2-11e9-9a7d-3dac44d2d410.jpg)

**Comment by ZhilkinSerg** [comment]
Glove with 5 holes won't really help to insulate from cold.

**Comment by Shotgunface** [comment]
> Glove with 5 holes won't really help to insulate from cold.
@ZhilkinSerg 
If you've ever worn a decent pair of finger-less/fingertip-less gloves they actually are not that cold, only the very ends of your finger get cold. The whole premise of finger-less gloves is to keep your hands warm AND give you dexterity or they would be a pointless product.

**Comment by ZhilkinSerg** [comment]
But they are pointless products starting from any significantly cold temperature. I am pretty sure they were not invented for cold weather at all.

**Comment by Shotgunface** [comment]
The only one that really was made for the cold is the mitten/glove hybrid, that seems to be the only feasible one for actually preventing frostbite. Do we at least agree on that one?

**Comment by kholat** [comment]
I vote for the foldable mitten, that should be in game.
