### ISSUE TITLE
hobo stove (lit) (0/100) is an infinite portable light source

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33246]
# Describe the bug

It doesn't provide much light but enough to see zombies on that tile at night.

0.D-6519-gc023e44bf2-dirty

**Comment by jeremyshannon** [comment]
Might be related to #32021 and #32276 and the active item cache.

**Comment by Night-Pryanik** [comment]
It seems that lit hobo stove isn't consuming any charges over time.

**Comment by Night-Pryanik** [comment]
It seems that lit hobo stove isn't consuming any charges at all.
