### ISSUE TITLE
Segmentation when choosing profession for custom character

### ISSUE THREAD

**Issue by snipersmithy** [CleverRaven/Cataclysm-DDA#33257]
Game crashes every time the character creation tab switches to Profession. Tried with various mods and no mods enabled.

1 Create world.

2 After world creation, start new custom character then tab across to Profession.

Expected to set profession and begin game.

# Versions and configuration

 - OS: Win 10 pro
 - Game Version: 0.D - 8574
 - Graphics version: Tiles
 - Mods loaded: dda, disable npc needs, filthy clothing, simplified nutrition.

# Additional context

Tested with multiple mods and worlds
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3506949/save.zip)

All saves produce the same bug.

**Comment by ampersand55** [comment]
No error for me in the latest build (9499).

```
- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.D-6590-g7e04972 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Filthy Clothing [no_filthy_clothing],
    Simplified Nutrition [novitamins]
]
```

**Comment by snipersmithy** [comment]
I found that I don't experience crash when experimental Z levels is set to off.

**Comment by SeanMirrsen** [comment]
I have consistently experienced this kind of crash when I set the game viewport to be fullscreen, 960x540 at 2x scaling, direct3d mode. Setting it to fullwindow instead removed the crash - of note is that possibly the scaling was set in error for fullscreen, as the onscreen text was way larger than I expected for 2x scaling, and reverted to reasonable size after changing to fullwindow.

**Comment by ZhilkinSerg** [comment]
Please try to reproduce crash on latest version found [here](https://github.com/CleverRaven/Cataclysm-DDA/releases). If issues still persists - ping me to reopen this issue.
