### ISSUE TITLE
Crafting basic lab analysis kit

### ISSUE THREAD

**Issue by Kirefire** [CleverRaven/Cataclysm-DDA#33254]
**Is your feature request related to a problem? Please describe.**  
Despite giving an ingredients list in the description, and the items being able to spawn, you cannot craft it.

**Describe the solution you'd like**  
The ability to craft it, with the items listed in the description, perhaps under a skill wall

**Describe alternatives you've considered**  
none, as mere mortals should have the ability to put items in a box.

**Additional context**  
as from the description:
This hefty kit contains some basic things you should probably not try to do precise chemistry without: namely, a small balance scale, a spectrophotometer, a melting point apparatus, a pH meter, and a set of paper for thin layer chromatography.

**Comment by alkemann** [comment]
I guess a box is also needed :)
