### ISSUE TITLE
Disinfectant not listed in craft menu

### ISSUE THREAD

**Issue by Leland** [CleverRaven/Cataclysm-DDA#33265]
# Describe the bug

Despite leveling a character to First Aid level 2, the disinfectant recipe does not show in the crafting menu.

# Steps To Reproduce

1. Spawn any character
2. Debug, learn, or start with First Aid skill at any value ≥ 2
3. Spawn The Big Book of First Aid
4. Read the book
5. Attempt to find disinfectant in the crafting menu

# Expected behavior

Per the definition of the recipe, I should just need both the skill and book to be able to see this in the menu:

https://github.com/CleverRaven/Cataclysm-DDA/blob/40e3a64ad081cd12187bc19cd6e0008a81a84bb3/data/json/recipes/other/medical.json#L55-L63

# Screenshots

![image](https://user-images.githubusercontent.com/714017/63144059-08863400-bfa6-11e9-9542-f610626bd9d1.png)

# Versions and configuration

 - OS: macOS 10.14.2 (18C54)
 - Game Version: 0b1a661742b1f1998afc858d08ac386dafabf541
 - Graphics version: Tiles
 - Mods loaded: dda

Here's a simplified example. For good measure, I'm adjacent to a loaded Chemistry Set. I don't think that affects the visibility of a recipe, but hey...

[North Wilkesboro.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3508093/North.Wilkesboro.zip)

**Comment by LaVeyanFiend** [comment]
``skills_required`` notes _secondary_ skills that are required, not the primary(cooking). You can use the book to craft it at cooking 2, not first aid 2.

**Comment by Leland** [comment]
Gah, good catch. We really need a way to denote these things in the books to teach the skills.
