### ISSUE TITLE
Make environmental protection reduce smell radious

### ISSUE THREAD

**Issue by Feniks-Gaming** [CleverRaven/Cataclysm-DDA#33268]
**Is your feature request related to a problem? Please describe.**  
At the moment character smells the same no matter what.  It makes sense that if character is wearing clothes that stop dangerous chemicals from coming in they should stop them from getting out. 

**Describe the solution you'd like**  
Cover x environmental protection should reduce how much character smells. Someone wearing hazmat suit should be odorless 

**Describe alternatives you've considered**  
No real alternatives I can think off

**Additional context**  
NA

**Comment by TychaiosIlithios** [comment]
Great attention to detail. Although at the same time it should be noted that some pieces of clothing have their own level of smell and noise. But that's for later, cuz making such traits properly dynamic would require full revamp of the current dirt mechanics, i.e. ideally clothes could have certain levels of dirts and smells, inherented when contacting certain objects, effects and fields, and not just static but changing on the go. Clothing could start to smell bloody should meat be carried or butchered, smoky should crafting or etc be done near smoke or even something exotic like smell markers from boomer attacks, gradually wearing down to a certain minimum as time passes.
