### ISSUE TITLE
Hot air propagates North-West indefinitely through solid rock and walls underground

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#33275]
# Describe the bug

![2019-08-16-153050_1920x1080_scrot](https://user-images.githubusercontent.com/1585431/63167970-834d5e80-c03b-11e9-8a8c-261a11cef1c3.png)

# Steps To Reproduce

1. Spawn vehicle heater, mount it and turn on.
2. Switch on debug temperature display.

# Expected behavior

Metal walls conducting _some_ heat doors letting some through seems reasonable, but it should work in all directions, obviously. I'm perfectly ok with any barrier not letting hot air through too.

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.2 LTS; Release: 18.04; Codename: bionic;
- Game Version: 0.D-6153-g89a33be [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by ZhilkinSerg** [comment]
Nice bug.

**Comment by KorGgenT** [comment]
This bug looks really familiar: i have the same issue with AOE spells! maybe that means something of the underlying infrastructure has an issue?

**Comment by ZhilkinSerg** [comment]
And this one could also be related: #33936

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/65612789-e3acb580-df82-11e9-8986-7e5f4eb48653.png)
Casting cone of cold (magiclysm) as you can see, the top left corner is exaggerated. if you level the spell more, it'll exaggerate more (and it looks to try to be the corner of a box)

**Comment by KorGgenT** [comment]
this is top left for comparison
![image](https://user-images.githubusercontent.com/30208401/65613233-a563c600-df83-11e9-9ef1-fcc67b04fa23.png)
