### ISSUE TITLE
missing dialog

### ISSUE THREAD

**Issue by OctavusTao** [CleverRaven/Cataclysm-DDA#33291]
# Describe the bug

So this bug showed after I talked to the person inthe exact dialog option below, missing the dialog file I assume.

# Steps To Reproduce

talked to this npc and chose the dialog option 'I just had some questions'

# Screenshots

![dialog bug](https://user-images.githubusercontent.com/50324839/63205336-f6bd9300-c070-11e9-9616-accf21a1e290.png)

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1809
- Game Version: 0.D-6597-ga611f45 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

save file attached
[Askov.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3511590/Askov.zip)

**Comment by anothersimulacrum** [comment]
Could you please fill out the template on the issue? You can get it back by starting a new issue, then copy the template and cancel the issue.

**Comment by OctavusTao** [comment]
# Describe the bug

missing dialog

# Steps To Reproduce

talked to this npc and chose the dialog option 'I just had some questions'

# Expected behavior

I did expect him to not give me an error and continue the dialog


# Screenshots

Posted above

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1809
- Game Version: 0.D-6597-ga611f45 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]


# Additional context

Add any other context about the problem here.

**Comment by OctavusTao** [comment]
save file attached
[Askov.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3511590/Askov.zip)

**Comment by ZhilkinSerg** [comment]
That is not a bug. There are dialog stubs reserved for future expansion.

**Comment by BevapDin** [comment]
> That is not a bug.

Than why does it say "BUG" quite literally in the screenshot?

**Comment by Leland** [comment]
@OctavusTao moved your additional info into this issue's original text, thanks for adding that

**Comment by mlangsdorf** [comment]
Fixed in #33822
