### ISSUE TITLE
New Backpacks Need Adjusting

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#33292]
**Is your feature request related to a problem? Please describe.**  
New Backpacks were added.  They need balanced.

**Describe the solution you'd like**  
The new backpacks need some tweaking.  All have material_thickness of 6 which gives some of them pretty ridiculous protection values (compared to other storage items and their recipe cost)

They also are all auto-learned recipes, and I believe some should be locked into books.  

Similarly, the recipes could probably use some looking at.  For instance, the Travelpack requires 5 rags and gives 25 liters of storage.  Compared to the backpack, which requires 20 rags and gives 10 liters of storage.  These recipes need to be balanced against the existing recipes in-game, or, alternatively, the old items need to be balanced against the new items.  

Additionally, I believe their coverage should be looked at.  Specifically, the high-volume rucksack has 95% coverage.  Combining this with its 24 bash and 24 cut protection, this is quite an item.  I understand it gives 100 encumbrance, but it's still too much, in my opinion.

**Describe alternatives you've considered**  
None.  They need to be balanced against existing storage items or, alternatively, the old storage items need to be balanced against the new items.

**Additional context**  
I hate the new packs.  They're OP.  I'm uncertain of whether I've been objective in this request, so if I wasn't, I apologize.  I thought about changing them myself, but I wasn't sure how to go about this.

**Comment by jeremyshannon** [comment]
There are definitely some problems like that 95% coverage, and their durability and craftability, but our old backpacks were stupidly small compared to modern off-the-shelf gear. A full rebalance of backpacks is what we need, adjusting size and encumbrance and so forth, and ensuring a separation between crudely made backpacks you stitched together for yourself out of rags and machine built commercial/military ones made with space-age materials and computer-assisted design involving a team of engineers.

**Comment by TheMurderUnicorn** [comment]
That's one of the main reasons I didn't make any changes myself.  Looking at some of the older storage/recipes I figured it would be a combination of balancing the old and the new, which is beyond the scope of my ability/knowledge of the dev direction.

Expanding player made bags into their own items is also interesting, and I did not consider that.

**Comment by ampersand55** [comment]
I like the new packs, but I agree back pack storage needs to be completely reworked from the ground up.

I'd say that old packs are not really tuned to represent real volume.

E.g. A in-game duffel bag is 30 litre and a medium size North Face Base Camp Duffel Bag is [71 litre](https://www.thenorthface.se/shop/en-gb/tnf-se/base-camo-duffel-m-3etp), while the XXL version is [150 litres](https://www.thenorthface.se/shop/en-gb/tnf-se/base-camp-duffel-xxl-3ets).

I think the encumbrance/storage capacity ratio is fine where 1 litre of storage represents 1 encumbrance for non-survivor backpacks.

For material use and weight, I think a good starting point would be to assume that storage capacity is proportional to volume and material use and weightis proportional to surface area.

If we for the sake of simplicity assume that the backpacks are cubical and call the length of a size L. The surface area is 6L<sup>2</sup>, the volume is L<sup>3</sup> and the ratio between encumbrance and surface area is 6L<sup>2/3</sup>.

Backpack | Volume  (L) (encumbrance)| Surface area (m<sup>2</sup>) (material use) | Side Length (m)
-- | -- | -- | --
backpack | 10 | 0.278 | 0.215
military Rucksack | 20 | 0.442 | 0.271
travelpack | 25 | 0.513 | 0.292
duffelbag | 30 | 0.579 | 0.311
hiking pack | 55 | 0.868 | 0.380
large tactical backpack | 65 | 0.970 | 0.402
high-volume rucksack | 100 | 1.293 | 0.464

**Comment by TheMurderUnicorn** [comment]
It's cool if you want to talk about a full bag rework.

But a much smaller, easier, and immediate solution to a lot of what I complained about would be reducing their absurd protection values/coverage and nerfing their recipes.  That would be an acceptable hold over until a significant project like a bag overhaul would take place.

It wouldn't take more than a few minutes and I just don't know what 'acceptable values' are, I just know these are laughably incorrect, particularly that you can make a high end backpack out of five rags and some string.

**Comment by jeremyshannon** [comment]
I don't know that there are any rules or guidelines for "acceptable values." In fact, these ludicrous values were accepted, so "acceptable" seems pretty broad.
 I'd say just think it over, make what you think are reasonable changes and submit a PR, and it's probably fine.
