### ISSUE TITLE
Make recharging station recipe autolearned and lower level

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#33306]
**Is your feature request related to a problem? Please describe.**  

Crafting a recharging station requires electronics 6 and is locked behind mechanics or electronics books. Creating a charger in real life requires a full wave rectifier and a voltage regulator to work from AC, and only a voltage regulator to work from DC (like a car battery). These are very simple circuits that anyone familiar with electronics has seen and are commonplace in many household apliances. A version of this should also be present in any car with a working alternator/battery pair.  Admittedly, modern rechargers also require microcontrollers if you want to prevent them from possibly overcharging batteries, but that is a risk most of us braved in the 90s without ill consequences. And since we already have perfect information about the level of charge in the batteries, such microcontrollers can be assumed to be built in the batteries themselves. There are more primite alternatives like timers or just having a lower charge speed to make them safer.

**Describe the solution you'd like**  

Make the recipe autolearned and level 3 or 4. That's when you start being able to build battery conversion mods, which is the same technology but used to control output instead of input.

**Describe alternatives you've considered**  

Make it a "slow recharging station" that doesnt use the 2 processor boards of the original recipe, charges half as fast (to protect from overcharging the batteries, should consume a bit of power if left on, even if its not actively charging anything), and can be upgraded to the original one at level 6 or 5 by adding said boards.

**Additional context**  

Recharging stations are essential to transition to mid/late game. They are currently tied to RNG drops from either books or vehicles, and they are a simple technology that would be a high priority to reach for any survivor in real life. It isnt something that "I didnt about that!".

With the ubiquity of battery powered devices (every background starts with a phone), recharging stations should be in every household.

While gathering information, I noticed Aftershock did this already by just lowering the recipe to lvl 3 and making autolearned.

Here's a video of a well known electrician purposedly fumbling through the process. He burnt a battery charging circuit by not using a voltage regulator directly from a variable output source. That would be like hooking a battery directly to the alternator with just a full wave rectifier.
https://www.youtube.com/watch?v=wdgiTQffiwk

**Comment by Citizen-of-Arcadia** [comment]
Could also split up rechargers into groups, usage-wise and battery type.
Every battery type has their own recharging station. 
Homes would sometimes have low-end battery recharging stations, whilst labs, industrial and military areas could have better battery recharging stations.
"Better" could be anything from faster recharging to lower weight, multiple battery type rechargers, installable in a car, etc...

**Comment by kevingranade** [comment]
Some of these assumptions are fair and some are not for example assuming that charge limiters and such were built into the batteries is not in any way warranted. That's an artifact of the battery model being relatively simple and just trying to make things user-friendly. It should not be taken as an indication that these batteries are somehow significantly more advanced than conventional batteries.

Instead of lowering crafting difficulty, it makes more sense to introduce a new charger that is only capable of charging relatively simple batteries with a lower difficulty, and leave the existing charger as a more advanced and flexible machine that can charge any battery type.

**Comment by TechyBen** [comment]
A makeshift scavenged or more versions to find would make sense. As in, phone chargers are 10 to the dozen, right?

**Comment by Svankensen** [comment]
Just wanted to clarify that a low tech, low power charger would prevent any damage to the batteries. An overcharged battery simply gets hot in proportion to the power being pumped into it. This can completely destroy a battery or even make it explode under certain circumstances, but a low power charger prevents this by not providing enough energy to heat up batteries much (which is why those old cheap AA battery chargers would take 4 or 5 times as much as a good charger to charge a battery). Such a charger would need to limit its output in a way that even the smallest battery it can charge can dissipate such an ammount of energy without causing evaporation of liquids or transformation of the materials, so it would charge all batteries, and in particular larger ones, very slowly, or even practically imperceptible. Unless designed specifically for larger batteries. 

It is important to point that batteries that do have controllers can reject very low voltages, and refuse to be charged. Hell, devices refuse to charge unless certain conditions unrelated to the power are met (propietary charges sometimes require a specific voltage in data communication lines for example). As a reference, laptop batteries usually have  built in controlers, while cellphone batteries usually have the controller in the cellphone instead.

**Comment by TechyBen** [comment]
My chargers have a switch (chemical type for rechargeable AAA/AA batts), and others a "sense" of voltage (12v or 6v).

It would be fun if some cars had "phone chargers" (UPS in game? But a "small UPS" so only accepting phones). Then the player would/could run around running engines/swapping chargers to power a phone to get light/charge. With the risk of being spotted/noise and running the fuel low.

Would give a use to stranged, but working engines/cars, before the player gets mechanics to strip/repair them. :D

Risk/reward stuff, so hopefully can be balanced. 

> As a reference, laptop batteries usually have built in controlers, while cellphone batteries usually have the controller in the cellphone instead.

Are you sure? I've seen nearly all the current phones/batteries have the controller in them. This is to prevent fires from the li-pos. Older batteries (your Nokia 3210s etc), did not, because they were nicad/etc.

**Comment by Zourin2** [comment]
What about installing hand cranks as an alternator-class vehicle part?  This could breathe a little bit of life in small motor assemblies and realistically be a means of converting mechanical energy into rechargeable battery power before you have access to mass-charging?

**Comment by alkemann** [comment]
If almost all houses have batteries in them, why wouldn't most of them also have charges. In my apartment there are dozens and dozens of charges that are compatible with anything from AAA, through phone and battery packs all the way to a charging state that can charge bigger stuff (I fly quad copters) and car batteries. Granted, most of these are set up to be plugged into a socket, but provided some electrical practice and a wealth of spares, it should be possible for a survivor to change the wall socket for the other sources of el power they have.

Maybe this mostly comes down to a balance issue of creating a scarcity of a resource?
