### ISSUE TITLE
Repairing with firearm repair kit takes almost no time

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#33305]
# Describe the bug

I repaired several guns with a firearm repair kit, and each repair action took only about 5-10 seconds.

# Steps To Reproduce

1. Spawn a firearm repair kit with battery.
2. Acquire a damaged gun.
3. Repair the gun with the firearm repair kit, observe how little time it takes.

# Expected behavior

Since it requires specialized equipment (firearm repair kit) and costs 100 battery charges, I would expect it to take a lot longer than a few seconds to repair a gun.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-6613-ge23659d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, +attitude [sees_player],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

Possibly related: #33027

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.D-8522. Repairing my damaged gun (from `|/` to `||`) took almost a minute on level 2 mechanics. Repairing from more damaged level (from `|.` to `|/`) took 2+ minutes. It surely could take slightly more time, but it's definitely not 5-10 seconds as in OP.
