### ISSUE TITLE
Tiny electric motor ingredients do not match weight of the item

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#33315]
# Describe the bug
The weight of the materials used in creating the tiny electric motor do not match the weight of the final product.

# Steps To Reproduce
1. Gather ingredients
2. add weight
3. Observe the total weight does not match the resulting item

# Expected behavior
2 options:
1. the resulting item matches the weight of the ingredients
2. the ingredients matches the weight of the resulting item

I think the weight of the tiny electric motor was well discussed here:
https://github.com/CleverRaven/Cataclysm-DDA/pull/27335
If we go by the conclusions from that discussion and the weight of the tiny electric motor is correct, then there should be more ingredients to match the weight as specified.

# Screenshots

![image](https://user-images.githubusercontent.com/50166150/63218116-08c43200-c154-11e9-9c98-f45e8daa37a8.png)

The ingredients used could not possibly add up to the weight of the tiny electric motor.
![image](https://user-images.githubusercontent.com/50166150/63218134-6d7f8c80-c154-11e9-96f2-fbdf5b75645f.png)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-6613-ge23659d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Mining Mod [Mining_Mod],
    Folding Parts pack [deoxymod],
    Simplified Nutrition [novitamins],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    More Locations [more_locations],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Hydroponics [hydroponics],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Bens GF recipes [Tolerate_This],
    Icecoon's Arsenal [ew_pack],
    Cataclysm++ [Cata++],
    Urban Development [Urban_Development],
    Mythological Replicas [nw_pack],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]

**Comment by Fris0uman** [comment]
Can you actually do the math and propose a list of ingredient? Then I could adjust the recipe if you don't want to deal with making a PR.

**Comment by snipercup** [comment]
Make the list of ingredients the same as above but add:
5 electronics scrap
5 lump of steel OR 20 Chunk of steel OR 100 scrap metal

That should take care of the weight.
