### ISSUE TITLE
Few problems with UPS modified tools

### ISSUE THREAD

**Issue by Melodeiro** [CleverRaven/Cataclysm-DDA#33319]
# Describe the bug

UPS modified tools aren't available at Item Action Menu (% key).
Also you can't craft using UPS modified tools, at the nearest tiles, like you do with regular versions of these tools.

# Steps To Reproduce

1. Apply UPS conversion mod on a welder
2. Press %, "Repair metal, ..." is not available
3. Drop welder on the ground
4. Try to craft recipes, that require welder

# Expected behavior

Well, since welder+UPS works fine, when you are holding it in inventory, using bionic energy (with CBM), and also probably with UPS batteries, i expect doing it the same way, when the tool is on the ground.

In addition to it, would be very cool if it could use UPS batteries and vechile charging station at the same tile, where the tool is. Then just give it more priority, than the batteries on characters inventory, or bionic energy

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.D-6568-gffec12f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Garden Pots [growable-pots],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Disable Religious Texts [no_religious_Texts],
    No Fungal Monsters [No_Fungi],
    Safe Autodoc [safeautodoc],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Simplified Nutrition [novitamins],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

**Comment by Shotgunface** [comment]
Same thing happens with the forge and a installed ups conversion.
