### ISSUE TITLE
Weight test for crafting recipes

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#33327]
**Is your feature request related to a problem? Please describe.**  
I just read #33315 and thought that this problem could've been automatically detected - the weight of a crafted item should always be less or equal to the combined weight of the ingredients.

**Describe the solution you'd like**  
All recipes should automatically be tested if the weight of the result(s) is less or equal to the ingredient(s).

**Describe alternatives you've considered**  
Leave everything the way it is.

**Additional context**  
none

**Comment by Kodiologist** [comment]
An additional test should be that if a recipe is fully reversible (i.e., you can disassemble the item to get everything you used to craft it), the total ingredient mass should be preserved exactly. For example, currently, a turban weighs 110 g, but is made of, and can be disassembled into, 8 * 80 g = 640 g of rags.

There may be at least some exceptions to the rule that a recipe result shouldn't weigh more than its ingredients, in cases where a recipe notionally uses  something that isn't represented in-game. In real life, heating various metals will increase their mass, but Cata certainly doesn't represent the mass of air that you use in a metalworking recipe.

**Comment by snipercup** [comment]
I think this is an interesting problem and I created a tool that analyses recipes and their weight. You can find it here:
https://github.com/snipercup/CCDA-JS-data-browser
It's not perfect but it can produce a result like this:

![image](https://user-images.githubusercontent.com/50166150/67119477-87d2f680-f1e7-11e9-95f2-55698529d08f.png)


From this you can conclude that the weight matches if the glass sheet is created from glass shards but not from glass flasks or glass jar. This can be used to start adjusting items and/or recipes so we are prepared should there be an automatic check in the future.
