### ISSUE TITLE
Limited range of listing items is crippling the game interface needlessly

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33334]
# Describe the bug

The player can get information on whatever items it sees no matter the range, while the range of listed items is limited:
```
    ///\EFFECT_PER increases range of interacting with items on the ground from a list
    const std::vector<map_item_stack> items = find_nearby_items( 2 * u.per_cur + 12 );
```
requiring the player to manually `;` and move around every item seen to find out what's there, so the mechanics doesn't add any real limitation but adds a layer of boring micro-management that an effective player has to perform.

# Steps To Reproduce

1. `V` in a cluttered space.
2. Observe that it doesn't list the farther items.

# Expected behavior

`V` listing every item seen.

# Versions and configuration

0.D-6646-ge4d3314a42-dirty

**Comment by anothersimulacrum** [comment]
I suggest just making this a flat value, like 60 (the size of the reality bubble), or if that can be too intensive to search, some low value, like 40.

**Comment by rah-jain** [comment]
I currently am suffering from a situation where I was "Hauling items along ground" (default bound to backslash) a corpse too heavy to carry through a forest and used the overmap's "W" command to auto-walk the remainder of the way home. I should have expected my hauled item to be left behind, but it didn't even occur to me. Would this change to the "Look around" command allow me to figure out where in the forest I had left behind this corpse? I don't see items on the ground in Look mode, just "Unseen".

Should I report the fact that my hauled items were left behind when auto-walking via the overmap as a separate issue (maybe a warning and confirmation would be ok behavior here, but ideally I'd be able to not have to play a navigation minigame to get my kill home...)

**Comment by anothersimulacrum** [comment]
> Would this change to the "Look around" command allow me to figure out where in the forest I had left behind this corpse? I don't see items on the ground in Look mode, just "Unseen".

No.
