### ISSUE TITLE
Foods receive massive ammount of negative rot if starting day is not zero

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#33338]
# Describe the bug

Foods that spawn from mapgen have massive negative rot.

# Steps To Reproduce

Create new world with the default start date (day 30).  
Find perishable food in a house.  
Enable debug mode.  
Look at the food. It has -20513822 turns of rot.

As the item rots the rot value increases. This effectively means that the food can rot for 237 days (longer in cold) before it reaches the normal "fresh" state.

If the starting day is smaller the negative rot will be smaller too.  
For example if game starts on day 1 the items will have -1374051 rot (-16 days).

# Expected behavior

Scavenged food should have rot from the start from catalyst to the current time. ( Slightly negative ammount of rot is possible due to 20% rot variation).

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-6613-ge23659d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

Foods seem to rot just fine during gameplay. Something goes wrong in the place where the food is placed on map maybe.

**Comment by Leland** [comment]
@kevingranade mentioned #32603 & #32948 in duplicate issue #32520. Might be worth taking a look at those
