### ISSUE TITLE
Construction scaling doesn't apply to vehicles

### ISSUE THREAD

**Issue by Feniks-Gaming** [CleverRaven/Cataclysm-DDA#33342]
# Describe the bug

Construction scaling doesn't affect the speed at which player constructs vehicles 

# Steps To Reproduce

1. Reduce construction scaling from 100 to 1 see times to construct building change but times to construct vehicles not.

# Expected behavior

Vehicles are constructions as player starts them up with construction menu [*], if player wants faster constructions he likely wants faster construction of vehicles too. 

# Screenshots

N/A

# Versions and configuration

 - OS: Win 10
 - Game Version: [9493
 - Graphics version: [Tiles]
 - Mods loaded: None

# Additional context

There are 2 solutions to this either make construction scaling affect vehicle component installation speed or add vehicle installation scaling as option in world settings

**Comment by alkemann** [comment]
I certainly assumed it worked like this for as long as I have played!

**Comment by Malkeus** [comment]
Yo, bot, this is still an issue.

**Comment by kevingranade** [comment]
Yo Malkeus, don't bump issues.
