### ISSUE TITLE
Frozen drinks show up as ammunition for bows.

### ISSUE THREAD

**Issue by Sgt-Cookie** [CleverRaven/Cataclysm-DDA#33348]
# Describe the bug

Frozen drinks show up as possible ammuniton when using a bow. The drinks do not actually _do_ anything when selected.

# Steps To Reproduce

1. Get a bow
2. Get a frozen drink of some kind.
3. Attempt to fire the bow

# Expected behavior
Only arrows show up as ammunition.

# Screenshots

![Uhhhhhhh](https://user-images.githubusercontent.com/53803539/63230839-6024d980-c20a-11e9-8665-a16a0ccb6bdc.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-6662-gd99872d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Extended Realistic Guns [realguns],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    StatsThroughSkills [StatsThroughSkills],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context

Tested with Recurve, Self and Short Bow. All three gave frozen drinks as ammo.

**Comment by EddiTheBambi** [comment]
**What, you mean I shouldn't be abe to shoot milk at my enemies!?**

Okay, this is my bad. Will look at this ASAP 🤦‍♂
