### ISSUE TITLE
Faction base recipe from SD-card

### ISSUE THREAD

**Issue by Melodeiro** [CleverRaven/Cataclysm-DDA#33349]
# Describe the bug

I just got a weird recipe from Science SD-card

# Steps To Reproduce

Probably it just randoms any recipes, including fake ones from faction bases

# Screenshots

![image](https://user-images.githubusercontent.com/2702567/63231545-c1a67180-c225-11e9-8398-4c47c36f5079.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.D-6568-gffec12f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Garden Pots [growable-pots],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Disable Religious Texts [no_religious_Texts],
    No Fungal Monsters [No_Fungi],
    Safe Autodoc [safeautodoc],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Simplified Nutrition [novitamins],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

**Comment by Leland** [comment]
Weirdly, that recipe is set to `never_learn`:

https://github.com/CleverRaven/Cataclysm-DDA/blob/9f59a937629ab7103616d8882e489572d740060e/data/json/recipes/basecamps/recipe_primitive_field.json#L722-L729

...which is supposed to prevent this from being learned at all, regardless of where it's been included:

https://github.com/CleverRaven/Cataclysm-DDA/blob/9f59a937629ab7103616d8882e489572d740060e/src/player.cpp#L10453-L10459

Wonder how this happened.

**Comment by Melodeiro** [comment]
Where is the DEBUG word from then? Maybe that recipe is not from json, but hardcoded somewhere?

**Comment by Melodeiro** [comment]
I guess, you need to add `never_learn` check here: https://github.com/CleverRaven/Cataclysm-DDA/blob/ec26a7eaacc6fb391fb9f341314c4ce1b2b9af8e/src/iuse.cpp#L5955

I don't see any checks when recipe is added to e-ink
