### ISSUE TITLE
Segfault when "Y"es to pain-caused disassembly interrupt

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#33358]
# Describe the bug

Segfault when "Y"es to pain-caused disassembly interrupt.

# Steps To Reproduce

1. Make a player with a car battery and the means to disassemble it in freezing conditions.
2. Disassemble the car battery.
3. When the frozen battery acid is generated, it automatically hits the ground and causes pain.
4. Hit "Y"es to interrupt the disassembly.
5. Segfault.

# Expected behavior

Disassembling an item with battery acid should either give the option to pour it into a container (which does indeed happen at room temperature) or should drop a frozen, non-harmful item called concentrated acid at your feet along with the other components.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

Screenshot of crash.log:
![image](https://user-images.githubusercontent.com/45959491/63237178-ea6f3c80-c20e-11e9-8407-a5d2f796aee6.png)

# Versions and configuration

 - OS: Win7x64
 - Game Version: 0.D-6621-gd201308
 - Graphics version: [Tiles]
 - Mods loaded: [none]

# Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3514077/config.zip)

**Comment by ZhilkinSerg** [comment]
Cannot reproduce on latest version.
