### ISSUE TITLE
Jenkins username give away private information

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#33359]
Found that Jenkins update information showed my private email address name even if I had hidden it in my github settings. I'm not quite sure if this is alright, so could anyone do me a favor and replace it with my github nickname or sth? Thx a lot.

**Comment by AMurkin** [comment]
Do you have **Keep my email addresses private** enabled in your [email settings](https://github.com/settings/emails)?
If you add `.patch` at the end of your PR URL you'll be able to see what info was provided by git.

**Comment by RedShakespeare** [comment]
> Do you have **Keep my email addresses private** enabled in your [email settings](https://github.com/settings/emails)?
> If you add `.patch` at the end of your PR URL you'll be able to see what info was provided by git.

Yes, definately I have selected that option if I didn't get it wrong.
![image](https://user-images.githubusercontent.com/44523519/63260885-ba7a7480-c2b4-11e9-8f21-1f3d64910e3b.png)
Besides, there **is** my private email address in my pr patch even when I change my primary email to another one. I wonder why.

**Comment by AMurkin** [comment]
As noted: it covers _web-based_ Git operations, and your local Git should be configured accordingly.

**Comment by ZhilkinSerg** [comment]
I am pretty sure it is not Jenkins fault - it just fetches data grom Github repo, so there is probably some misconfiguration on your local git client that exposes address that you do not want to be shown in commits.

**Comment by AMurkin** [comment]
Definitely not Jenkins.

**Comment by ZhilkinSerg** [comment]
Can you please link Jenkins page which exposes your email? I can't find it.

**Comment by RedShakespeare** [comment]
> Can you please link Jenkins page which exposes your email? I can't find it.

https://ci.narc.ro/asynchPeople/
The one with two '_' in the username.

**Comment by RedShakespeare** [comment]
Appreciated for all replies...
Feel so ashamed now for these basic github questions.
I shall close this issue after I check out my local git configs.

**Comment by RedShakespeare** [comment]
The problem is caused by my modification to the /.git/config when I met a "Please tell who you are" message...Now solved.
Thanks a lot for all the replies again. (Could you please change my old user_id on jenkins by the way...? @ZhilkinSerg I'd be so very appreciated for that.)

**Comment by ZhilkinSerg** [comment]
I think I can edit/delete user, but we probably need to do something with commits too.

**Comment by RedShakespeare** [comment]
> I think I can edit/delete user, but we probably need to do something with commits too.

Yes....
Sorry for bringing extra work....

**Comment by esotericist** [comment]
Unfortunately, this isn't actually feasible to address.

Once a commit reaches a public repository that has any meaningful number of people interacting with it, the very nature of git means the information is irrevocably in the wild.

While it is possible to rewrite the commit history of a single repository, this does nothing for any other forks or clones, and Cataclysm has a very, very large number of those. Even if we were to do all we could, it would do very little to mitigate the problem for anyone looking.

Details about why can be found [in this Github document here](https://help.github.com/en/articles/removing-sensitive-data-from-a-repository).
