### ISSUE TITLE
Multipage inventory doesn't refresh screens properly

### ISSUE THREAD

**Issue by minakitty** [CleverRaven/Cataclysm-DDA#3336]
If you have enough items in the first column of your inventory to make multiple pages, and some of those lines go into the space for the second column, the screen doesn't delete the overflow when you go to the second page.  In this case, follow the (4) on line & .. the veggie pizza
![screenshot from 2013-09-28 14 39 18](https://f.cloud.github.com/assets/5273418/1232074/b6e8f7c0-2886-11e3-9ea4-283bc90da5f0.png)
![screenshot from 2013-09-28 14 39 31](https://f.cloud.github.com/assets/5273418/1232075/b700305c-2886-11e3-97da-48be85cd7417.png)

**Comment by BevapDin** [comment]
Does this still happen? I can't reproduce it.

**Comment by OzoneH3** [comment]
Since these item names are now printed with `trim_and_print()` this can't happen anymore.
