### ISSUE TITLE
"Disinfectant" should be called "Antiseptic"

### ISSUE THREAD

**Issue by kazimuth** [CleverRaven/Cataclysm-DDA#33368]
# Describe the bug

On current master, "disinfectant" is used to clean wounds. Medically speaking, this is a bad idea -- a disinfectant is typically a strong solution of some biocide, intended for disinfecting *nonliving* surfaces like railings, tables, or scalpels. Using it on an open wounds will likely cause tissue damage and hurt more than it helps.

The stuff that you use to disinfect open wounds is called *antiseptic*, a much weaker solution that's safe for human consumption. Yes, this is pointlessly confusing, but hey, that's English.

In the game currently, "disinfectant" actually behaves like antiseptic. The closest thing to an actual disinfectant in the game is probably the concentrated hydrogen peroxide you find in labs.

([Source](https://www.healthline.com/health/what-is-antiseptic). Also, the [wiki](http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Disinfectant) has a note about this.)

# Expected behavior

I'd suggest renaming the current "disinfectant" item to "antiseptic".

Downside is this might confuse players just for the sake of realism, but that's sorta this game's MO so I think it's worth it.

As an extension, disinfectant could also be added back in, perhaps as a cheaper but less effective alternative to autoclaves. If the game did more tracking of filth on tiles or the player, it could also be used to clean that off, but I don't know if that's a feature anyone's clamoring for.

**Comment by Leland** [comment]
Note that we also do have an antiseptic powder which possesses the exact same healing properties as the game's "disinfectant":

https://github.com/CleverRaven/Cataclysm-DDA/blob/b87e4cd0a5e78a8c027a52995f96ac1933f83321/data/json/items/comestibles/med.json#L174-L187

Ditto for hydrogen peroxide:

https://github.com/CleverRaven/Cataclysm-DDA/blob/b87e4cd0a5e78a8c027a52995f96ac1933f83321/data/json/items/comestibles/med.json#L256-L267
