### ISSUE TITLE
Zones, weapons and subcategorys   

### ISSUE THREAD

**Issue by Domotdow** [CleverRaven/Cataclysm-DDA#33379]
**Is your feature request related to a problem? Please describe.**  
I was trying to get in zone so I could have rifles separate from all the other weapon and and ammo with the custom filter. I got all the items with riffle in there name and some ammo but I couldn't get it so all my riffles moved there.

**Describe the solution you'd like**  
So if there was a way that you could set up zone for different types of weapons or preset zones for different weapons this would solve this problem I would also like to see more filters for the custom zones to use. 

**Describe alternatives you've considered**  
For the time being I am just going to set up a zone that is ignored and I will manually drop my rifles there. 

**Additional context**  
I think all you would need to really fix this is to add subcategorys in the custom filter  
with a simple description on how to use it  

Like this
{
s: sub category 
Examples riffle, piercing, explosives 
}

This could really clean up the menu those who rather just type the subcategory instead of selecting it throw a big list. But a combination of both options is probably the best. Just put the custom filter at the top of the list for ease of use and it would be golden.

**Comment by ZhilkinSerg** [comment]
There are custom filter loot zones - see https://github.com/CleverRaven/Cataclysm-DDA/pull/32754. See if it helps in what you want to achieve and ping me to reopen if not.

**Comment by BaumgeistOne** [comment]
@ZhilkinSerg He did mention using the custom filter. I think what he wanted to achieve is to automatically sort all weapons which use the "rifle"-skill into one tile, and I don't think that is possible right now.

**Comment by ZhilkinSerg** [comment]
There is no such thing as item subcategory. If it will be added - filters can be easily expanded to use it.

**Comment by Domotdow** [comment]
Yeah that what I was thinking BaumgeistOne.  This was feature request to solve that.
I am really hoping they do add that feature.

**Comment by sdvhunter** [comment]
I would love to see this feature implemented. It will really help with sorting 40 page loot piles since you currently need a couple of custom loot zones to get specific items out there. More sub-category examples: "not/is a craft component", "dissasembleable/cuttable".
