### ISSUE TITLE
Magiclysm +Mi-go (encampment or slaver?) crash game.

### ISSUE THREAD

**Issue by curstwist** [CleverRaven/Cataclysm-DDA#33373]
# Describe the bug
Getting a segfault/CTD when I try to approach a mi-go encampment while using the magiclysm mod.  

CTD

# Steps To Reproduce

1. Make a world with Magiclysm enabled and try to approach an encampment.  This may be triggered by just the slavers, but I'm not sure.  
2. Use saved provided by Vormithrax for quick testing.  Load and head north, you'll get a crash within 3 tiles of the encampment.

# Expected behavior
Harmony between the mod & mi-go slavers.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-6662-gd99872d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Magiclysm [magiclysm]
]

# Additional context
I tested Vorm's world settings without the mod and was able to approach the camp.  I also tried my own magiclysm modded world and it crashed when I approached.

oops forgot the save:

[Dead Evil.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3517491/Dead.Evil.zip)

**Comment by KorGgenT** [comment]
What's happening here is the mi-go slaver is trying to cast a spell with no data. I do not know why the loaded data is turning into garbage, however.

**Comment by KorGgenT** [comment]
Also confirmed that this only happens with Magiclysm enabled.
