### ISSUE TITLE
Remove negative enjoyability from common foods

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#33381]
**Is your feature request related to a problem? Please describe.**  
Walnuts have negative enjoyability. I have come across this problem with other foods, but with most I could at least see an angle. Walnuts are sweet nuts, unless they are unripe, in which case they are bitter. But eating unripe food is not great no matter the food, so it should not be a factor. This sounds like someone added them and thought people only eat them for health benefits or something? People aint stupid, most dont eat disgusting stuff and pay a high price for it on a daily basis. 

**Describe the solution you'd like**  
Any commonly sold food that is frequently eaten as is should at worst have a zero enjoyability value. 

**Describe alternatives you've considered**  
Randomize some foods at char gen so that every character likes and dislikes some completely at random. +3 to -3? Maybe make a picky eater trait? Gives you a 10% chance for any food to have its enjoyability reduced by 5?

**Comment by ZhilkinSerg** [comment]
Random food affinity would be great, but there are unarguably bad tasting foods - like blue cheese, or goat meat, or sushis 👅 🛑

**Comment by Leland** [comment]
> Any commonly sold food that is frequently eaten as is should at worst have a zero enjoyability value.

This issue needs a list of "common foods" with negative enjoyability, otherwise it can't really be fixed.

Walnuts... anything else?

**Comment by Svankensen** [comment]
> This issue needs a list of "common foods" with negative enjoyability, otherwise it can't really be fixed.

I'm doing this list from the debug menu manually, so I'm sorry if I missed some:

Carrot
Elderberry (never tasted these, they dont exist in my country)
All of the MRE entrees
Boiled stomach
Cooked sweetbread
Cooked kidney (YMMV, I imagine this one could be bad if handled poorly)
Cooked liver
Mushroom (Most raw mushrooms are very nice. A few have a weird texture that some may find offputting or cant be eaten raw)
Cabbage
Canned liver
Hazelnuts (not sure if these are eaten raw normally)
Mashed pumpkin

**Comment by Petethegoat** [comment]
Tofu as well.

**Comment by Zourin2** [comment]
Tofu should be a depressant.

**Comment by Zourin2** [comment]
> Tofu as well.

I'm pretty sure straight-to-mouth Tofu is a depressant in the American Northeast, as it tastes of both sadness and the stubborn refusal to acknowledge that meat is a much tastier source of protein.

**Comment by anothersimulacrum** [comment]
Please try to remain topical, your opinions on tofu aren't relevant to this issue.

**Comment by Zireael07** [comment]
MREs are supposedly genuinely disgusting (rations in general often are, my grandfather used to be a soldier and that was one of his recurring complaints), and I wouldn't call them common, since they're, uh, military rations after all.
I honestly have no idea about boiled stomach/kidney, but we do have cooked/canned liver in my country and it's definitely not disgusting even when not seasoned with salt. I have never tried elderberry either. 
Mushrooms are hit/miss depending on exact variety (some are genuinely disgusting, but the majority is neutral/nice). Cabbage might put some people off, but more likely due to smell rather than taste.

**Comment by Svankensen** [comment]
Hmm. I may be biased, since I watch one of those youtube channels where someone tries MREs from the whole world and he likes them very much.
