### ISSUE TITLE
Hacked prototype cyborgs can't be operated in an Autodoc

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33399]
# Describe the bug

I've just hacked one, disabled one and reenabled it again right after. Now the autodoc says `No patient found located on the connected couches.  Operation impossible.` when the cyborg is on the couch.

# Steps To Reproduce

1. Load the game.
2. Try fixing the cyborg.

[2019.08.06.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3521955/2019.08.06.zip)

0.D-6693-g367f3a8960-dirty

**Comment by Fris0uman** [comment]
What do you mean by reenable?

**Comment by l29ah** [comment]
You can convert a hacked cyborg into an item by going into it, just like a turret or a manhack, and then re`activate` it.
So how am i supposed to fix the cyborg then?

**Comment by Fris0uman** [comment]
Put the inactive cyborg on the couch

**Comment by l29ah** [comment]
Ouch, yes, it works, thank you. Somehow i failed to do this too at first and decided it's an expected behaviour.
