### ISSUE TITLE
Existing crossbows shouldn't give rubber hose when deconstructed

### ISSUE THREAD

**Issue by devenv** [CleverRaven/Cataclysm-DDA#33390]
**Is your feature request related to a problem? Please describe.**  
Rubber hoses are not part of a real crossbows.

**Describe the solution you'd like**  
Only makeshift crossbows (which do not exist in the game right now) should have hoses, existing crossbows should not.

**Comment by Svankensen** [comment]
It does seem that thread/sinew/plant fibers would be a better fit for crafting, and a long string should be the result when dissasembling (albeit a very unusual one).
https://medievalcrossbow.info/bow-string/

**Comment by ZhilkinSerg** [comment]
Better yet remove rubber hose recipe.

**Comment by kevingranade** [comment]
Yea the rubber hose isn't a valid component for any crossbow.

**Comment by alkemann** [comment]
I tried to recreate this issue, but trying to disassemble crossbow in game does not give me any hoses. I do not find any reference to hose in recipes for any crossbow. 

Invalid issue?

**Comment by ZhilkinSerg** [comment]
This could be related to some mods ot specific game version. Issue template (which was not followed) is there for reason.

**Comment by ZhilkinSerg** [comment]
Closed as we cannot reproduce the issue on latest master without mods. Please report game version that you use and list of mods (if any).

**Comment by devenv** [comment]
Yeah, apparently it was fixed a long time ago (https://github.com/CleverRaven/Cataclysm-DDA/pull/7919)
I'll test it on latest build next time :)

**Comment by ZhilkinSerg** [comment]
Were you in cryogenic sleep for 5 years or what, lol? :D
