### ISSUE TITLE
JSON contains circular dependency

### ISSUE THREAD

**Issue by stibbons01** [CleverRaven/Cataclysm-DDA#33391]
# Describe the bug

After creating a new world and starting a new game the following debug message appears during the "Finalizing" stage:

```
 DEBUG    : JSON contains circular dependency. Discarded 3 objects:
{
    "type": "overmap_terrain",
    "id": "sewage_treatment",
    "copy-from": "sewage_treatment",
    "name": "sewage treatment",
    "sym": "s",
    "color": "yellow"
  },{
    "type": "overmap_terrain",
    "id": "sewage_treatment_hub",
    "copy-from": "sewage_treatment_hub",
    "name": "sewage treatment",
    "sym": "s",
    "color": "i_yellow"
  },{
    "type": "overmap_terrain",
    "id": "sewage_treatment_under",
    "copy-from": "sewage_treatment_under",
    "name": "sewage treatment",
    "sym": "s",
    "color": "i_yellow"
  },
 
 FUNCTION : void DynamicDataLoader::load_deferred(DynamicDataLoader::deferred_json&)
 FILE     : src/init.cpp
 LINE     : 131
```
After pressing "Space" the game still starts. The same message appears after saving this game and loading it up again.
Already tried that with a completly fresh installation through the launcher and got the same result.

# Steps To Reproduce

1. Create New World
2. Play Now! (Fixed Scenario) or Load Savegame

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-6737-g9f59a93 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key]
]

# Additional context

[Debug Log](https://github.com/CleverRaven/Cataclysm-DDA/files/3520472/debug.zip)
[Savegame](https://github.com/CleverRaven/Cataclysm-DDA/files/3520478/Gradyville.zip)

**Comment by Leland** [comment]
Likely culprit in #33339

**Comment by ZhilkinSerg** [comment]
Alternative Map Key should be updated.

**Comment by stibbons01** [comment]
> Alternative Map Key should be updated.

Can confirm that it only happens if "Alternate Map Key" is enabled. Thanks!
