### ISSUE TITLE
Morale boosts for surviving dangerous situations

### ISSUE THREAD

**Issue by devenv** [CleverRaven/Cataclysm-DDA#33392]
**Is your feature request related to a problem? Please describe.**  
Killing kids has a morale debuff, but there is no morale boost for killing dangerous/multiple enemies, escaping a horde after being surrounded, pulling three criticals in a row, etc

**Describe the solution you'd like**  
A message in the log + morale buff for various scenarios, TBD.

**Additional context**  
This can act as incentive to take risks, and give a feeling of arcade, if you (the player) feel good about surviving hell, why shouldn't the character?

**Comment by Heaper327** [comment]
maybe even add a trait to go with it, like "risk taker" or "thrill seeker"

**Comment by Svankensen** [comment]
Maybe have it have similar triggers as the adrenaline rush one has? Except it triggers 20 minutes after or something. It would be nice to get a morale boost the first time you kill an enemy, proportional to its risk. "Killed a Shoggoth" should make you extastic, something like +50, while the first zombie you kill should probably give you a +5?

**Comment by ebolite** [comment]
I like this idea a lot. I feel like a reverse GUILT flag for tough enemies like hulks, shoggoths, etc. would be awesome.

**Comment by kevingranade** [comment]
Player doesn't need arbitrary additional rewards for survival, surviving is the reward.

**Comment by devenv** [comment]
It's not only about rewarding the risk but immersiveness too. A character standing in a sea of blood and the only thought they have is "how nice, I ate at a table" makes the character look a bit like a psychopath (unless they have a psychopath trait that is)... More reactions in morale to the events in the game would make the game better IMO...
