### ISSUE TITLE
turret related bugs&flaws from "PSA #1"

### ISSUE THREAD

**Issue by free-coffee** [CleverRaven/Cataclysm-DDA#33401]
# Describe the bug

There are the following bugs/issues talked about in [PSA #1](https://www.youtube.com/watch?v=M3VWiKTt60k&feature=youtu.be) by Vormithrax:
* Turret night vision range 4 instead of 3.
* antimaterial turret: attack range 39 instead of 40
* turret placement random offset in labs (within 4x4 or whole room).
* negative impact on lab escape scenario.

# Additional context

Some players are frustrated by this as seen in [reddit](https://www.reddit.com/r/cataclysmdda/comments/ct171x/cataclysm_psa_1_turret_changes_in_build_9503/).

**Comment by kevingranade** [comment]
At a top level:
1. Do not turn reddit complaints into issues, follow the template, which outlines what is necessary for a valid issue. If you can't do that *you do not have a valid issue*.
2. Do not fold multiple issues into a single issue.

Point-by-point:  
This is just the way night vision works, they have the default daylight range of 40 and a night vision range of 3, to determine actual vision range it does linear interpolation between these two values, if there is any light at all (which there always is), that max range of 40 will contribute a little.
Effective night vision range of 4 is not a problem in of itself.

Off-by one in attack range is similarly not intrinsically a problem.

The turret placement issue (which needs a lot more significant documentation than this to be actionable) is a seperate issue.

Negative impact on lab escape is not an issue.

"Some players are frustrated by this" is also not necessarily an issue.

**Comment by free-coffee** [comment]
I'm sorry for this. Although i don't understand how we process feedback from players then, if we do.
