### ISSUE TITLE
Wait until Dusk|Dawn should mean waiting until it is Dark|Light

### ISSUE THREAD

**Issue by alkemann** [CleverRaven/Cataclysm-DDA#33410]
The term _dusk_ usually refers to the the Astronomical Dusk, the darkest part of twilight before night begins. The sun no longer provides any direct light as it is 18 degrees below the horizon. I as a player (and I would assume most) expect from a "technical correct", but also what is actually game mechanically useful, that the "Wait until" features are letting you wait until it is dark (so you can sneak) or light (so you can see).

I would like the times when waiting stops to be at the time that light level from the sun changes.

Alternatively, should there be disagreement as to what the terms Dusk and Dawn refer to in the game, I would like the `Wait until Dawn/Dusk` be replaced with `Wait until Night/Day` or `Wait until dark/light`. Or as a further option add Dark/Light in addition to Dusk/Dawn

**Comment by ebolite** [comment]
Agreed. It's just annoying to have to wait another 5 minutes until you can _actually_ start seeing things. Especially so now that turns are intervals of 1 second, because it's that much longer.

**Comment by alkemann** [comment]
I used a "wait 5 minutes" and still light.  Then I just ran with it and after 35 minutes it was still bright and I have had several scary zombie chases. I believe it became dark after near 40 minutes. I would say this issue is bigger than a annoyance of a small additional wait.

**Comment by ipcyborg** [comment]
Currently it is working like this:
Dawn = Starting of morning twilight. It will be light in 1 hour.
Dusk = Starting of evening twilight. It will be dark in 1 hour.
(1 hour = `twilight_duration`)

"Technical correct", yes, and probably usefull in some cases.

>Wait until Night/Day or Wait until dark/light

What if we add this as new options? Note that it could be light/dark enough before this extra 1 hour is finished.

Wait until Night = wait until dawn + 1 hour
Wait until Day = wait until dask + 1 hour

**Comment by alkemann** [comment]
The definition from a simple google or a lookup in wikipedia or dictionaries says that Dusk means the time it becomes dark, the END of twilight. That the word dusk is mostly understood to refer to 

> astronomical dusk, or the darkest part of twilight before night begins.

See: https://en.wikipedia.org/wiki/Dusk

**Comment by alkemann** [comment]
I was saying that we should change it to be both more technically correct AND that it makes more sense from a usefulness. Not that it was technical correct the way it is.

**Comment by ipcyborg** [comment]
Ok, so it will be something like this:
Wait until Dawn = Start of morning twilight. It will be light in 1 hour (unchanged)
Wait until Dusk = End of evening twilight, darkness (add +1 hour here)

And no change in names, no additional wait options. Seems fine to me, more usefull than current state. 
Right?

**Comment by alkemann** [comment]
Yes, though I would argue for also changing dawn for consistency and usefulness even if dawn is more commonly talking about the start of twilight. We could ofc save all that by just changing it to "Wait for nightfall" and "Wait for daylight" so it can be both straightforward and useful ;)

**Comment by alkemann** [comment]
Turns out these are pretty complicated model in the code and are called sunset and sunrise, which explains why it is bright at "dusk" (it is still 18 degrees more before dark), but doesnt explain why you have to wait longer for light at dawn (it is at 0 degrees, while twilight starts at -18). So you shouldnt have to wait an hour from Dawn, you should have had an hour of sunlight already.

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/calendar.cpp#L71

**Comment by alkemann** [comment]
Trying to look at the code, changing anything there could have other consequences, I now favor changing to "Wait for daylight" and "Wait for darkness" or simply "Wait for night". Trying to code it to test.

**Comment by alkemann** [comment]
Kinda works? Maybe split up from a inline if to actually either set alarm for dusk/dawn or wait until dark/light?

https://github.com/CleverRaven/Cataclysm-DDA/compare/master...alkemann:dusk_is_dark
