### ISSUE TITLE
Telescope sight crafting cannot work well

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#33418]
# Describe the bug

When the player with enough components tries to craft "tele_sight","tele_sight_pistol"or "bow_scope", there will be a bug report.

# Steps To Reproduce

1. Make a player with components and skills required to make any of the three scopes above. .
2. Try to make the sight.
3. There's no way you can do it.

# Expected behavior

The player can make the scopes like any other items.

# Versions and configuration

 - Game Version: [0.d-6692-gcf4ce7d or 0.d-9512]
 - Mods loaded: [dda]

# Additional context

I'm quite sure this problem is caused by the recipes of these scopes where a material "lens" appears twice.
![image](https://user-images.githubusercontent.com/44523519/63410396-cd608680-c425-11e9-9d33-35e051de0c14.png)

 Since the crafting mechanism checks out whether the materials is enough line by line, it seems that only two lens can fit both of the requirements and thus this problem occurs.

**Comment by ymber** [comment]
#33395 should fix this.

**Comment by AMurkin** [comment]
#33395 is merged.

**Comment by ZhilkinSerg** [comment]
Should be closed by #33395
