### ISSUE TITLE
Returning a NPC from a camp mission with large food debt

### ISSUE THREAD

**Issue by Melodeiro** [CleverRaven/Cataclysm-DDA#33432]
**Problem**  
First of all, it warns you that bad things might happen, but thats somewhere at the ingame guide, or at NPC dialogs. Also the problem it is implemented so unreal and unclear to a player. After finishing a mission with large food debt, everyone in a camp has turned hostile, and that understandable. But also it means, that every follower NPC on the world would turn hostile as well, and also that leads to a weird situation, when you are trying to invite new NPCs to be your follower, he agrees, and then immediately turning hostile. That all literally means you can't have followers anymore, and that feels quite weird.

**Solutions**  
- Changing the opinion of the certain NPC instead of the whole faction, so he will turn hostile. Also fail the camp mission, if debt is too large, if you want to avoid abuse
- Warn the player, that he is missing X amount of calories for this mission, and bad things will happen

**Alternatives**  
Maybe changing the opinion of all NPC who is in the current camp (securing or working). Or changing opinions of all current followers, but doesn't touching the newcomers.

**PS**: an example, of what might happen is that issue: #29246 I have opened the master.gsav from the save file, he uploaded, and here we go, followers faction has `"likes_u": -11, "respects_u": -299,`. Thats almost the same values, like i have right now, after failing camp mission, but i might be wrong, because i checked that value after killing some NPCs in my camp. So thats probably an example of misunderstanding

**Comment by RedShakespeare** [comment]
Well, according one of my friends this bug still exists and has caused him quite a trouble. Hope someone could notice this.

**Comment by mlangsdorf** [comment]
There's only one faction of your_followers.  Fixing this will be complicated.  Probably the best thing to do would be to move people who really hate you into a new faction your_ex_followers and then 0 out the likes_u and respects_u values.

**Comment by baldamundo** [comment]
Another weird quirk of this is last I checked you can still send hostile followers on missions. Had this happen to me on my last save by accident (I did actually have enough food in reserve, just hadn't committed it), and ended up able to continue by just keeping all the NPCs permanently on missions. Every time they'd return they'd be hostile again, but if I had enough food I could just immediately send them out again before they could attack me.

**Comment by ShinWinddreamer** [comment]
> 
> 
> Another weird quirk of this is last I checked you can still send hostile followers on missions. Had this happen to me on my last save by accident (I did actually have enough food in reserve, just hadn't committed it), and ended up able to continue by just keeping all the NPCs permanently on missions. Every time they'd return they'd be hostile again, but if I had enough food I could just immediately send them out again before they could attack me.

yeah thats how i kept mine busy. As of the more recent patch i wasnt in a position to reproduce the bug without cheating but I should get around to it sometime. Spawn in some npc's, make a faction home after recruiting them and then let the calories run out on purpose to see what happens after that.
