### ISSUE TITLE
Too long item names in trading interface

### ISSUE THREAD

**Issue by Feuerhai** [CleverRaven/Cataclysm-DDA#33434]
# Describe the bug

When you want to trade an item with a long name very long name, you sometimes can't see the space to enter the number of items you want to trade. It still works without a problem.

# Steps To Reproduce

1. Create multiple small plastic bottles of non-drowsy cought syrup (5/5).
2. Create an NPC.
3. Trade with the NPC and sell him you bottles.

# Expected behavior

You can see how many items you want to trade, no matter how long the item name is.

# Screenshots

![Trade items](https://user-images.githubusercontent.com/25032400/63449937-48836600-c441-11e9-9068-f93fcaac5e06.PNG)

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1803
- Game Version: 0.D-6816-g59d443e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    sees-player icon, +attitude [sees_player]
]

# Additional context

The small plastic bottle of non-drowsy cought syrup (5/5) has to be one of the longest names in the game.

**Comment by Zourin2** [comment]
A lot of container+liquid names are exceptionally long, making it hard to see what it is you're handling in some interfaces. Is there some way to shorten these, or perhaps reverse the naming convention so you can see the contents and qty first and the type of container second?
