### ISSUE TITLE
ESC. out of the harness animal prompt causes an assertion failed error

### ISSUE THREAD

**Issue by ThatWeasel** [CleverRaven/Cataclysm-DDA#33438]
# Describe the bug
When going into the harness animal prompt, hitting escape when selecting the direction of an animal to harness will cause an 'Assertion failed, Program : (EXE path) file : src/optional.h, line 45 Expression : Full' error pop up

# Steps To Reproduce
Attempt to harness an animal then change your mind and hit escape

# Expected behavior
Message goes away, game continues to run

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-6568-gffec12f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3526891/Log.zip)

**Comment by alkemann** [comment]
Unable to reproduce. I could escape the examine and the "choose harness" windows without problems. Also there doesn't seem to be any requirement to "select the direction" when harnessing animals?

Further the log speaks to a problem with a zombie that cant move to its location.

**Comment by davidpwbrown** [comment]
> Unable to reproduce. I could escape the examine and the "choose harness" windows without problems. Also there doesn't seem to be any requirement to "select the direction" when harnessing animals?
> 
> Further the log speaks to a problem with a zombie that cant move to its location.

when you examine the harness, it will prompt for where the animal is you want to harness.
the harness is a vehicle part.

This is the dialogue you were testing, yes?

**Comment by davidpwbrown** [comment]
I just tested it , and it escaped out of that diretional prompt fine though, yes.

**Comment by alkemann** [comment]
Ah, I was testing applying inventory harness
