### ISSUE TITLE
Chunk loader - Reality Bauble extender

### ISSUE THREAD

**Issue by MaciejGorczycaGD** [CleverRaven/Cataclysm-DDA#33442]
**Is your feature request related to a problem? Please describe.**  
Currently players reality bubble extends around player and nowhere else. While things like farming and energy storage etc work outside of reality bubble other things will not. Some of the things that don't work are fire spread, mob movement etc. Sometimes player will want those things to still work even when they are not in proximity. 

**Describe the solution you'd like**  
I would like an item or construction that extends reality bubble around itself like a player does maybe with smaller range say 1 map square. Player could activate it drop it on the map where required and leave area while chunk loader works. 

Ideally chunk loader would have some sort of power supply to prevent player from accidentally lagging himself by dropping too many. 

Risk player is facing here is lag due to much greater number of entities loaded at the same time.  However as this is something player can choose to do or not it is good trade off and players with better specs could use more of it while players on lower specs could play without it fine. 

**Describe alternatives you've considered**  
Ability to select from map menu a squares that player wants loaded is another alternative.

**Comment by kevingranade** [comment]
This is a very hard no, there is no good reason to have the player interact directly with chunk loading like this.
