### ISSUE TITLE
Trading items outside your inventory that have quantities listed in () will make the remaining quantity disappear.

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#33458]
# Describe the bug

Trading items that have quantities listed in () like "bandage (3)" will cause any remaining quantity to disappear. This only happens when trading items that are not in your inventory.

# Steps To Reproduce

1. Talk to a follower or refugee merchant and start a trade.
2. Select an item on the ground near you that has its quantity listed in parenthesis.
3. Type a quantity less than the total amount.
4. Accept the trade.
5. Start a trade with the same person.
6. Notice how the remaining quantities of the item you traded have disappeared.

# Expected behavior

Items with quantities listed in parenthesis from outside of your inventory should not cause any remaining quantity to disappear.

# Screenshots

N/A

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 18.0.4; Codename: Illyria; 
- Game Version: 0.D-6819-g5687d45c35-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    No Fictional Guns [no_rivtech_guns],
    No Flaming Weapons [no_flaming_weapons],
    Classes and Scenarios Mod [more_classes_scenarios],
    Garden Pots [growable-pots],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Save File
[West Jefferson.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3529710/West.Jefferson.zip)

**Comment by l29ah** [comment]
I can confirm on 0.D-7431-g0d20828957-dirty: sometimes some of the nearby items just vanish when "trading" with an allied NPC at least.
