### ISSUE TITLE
Feature request: finer mass granularity

### ISSUE THREAD

**Issue by tenmillimaster** [CleverRaven/Cataclysm-DDA#33466]
In order to properly support my reloading rework project, I'd like to get JSON support for masses down to a centrigram, ideally a milligram.

A grain is about .065 grams.

The cartridge with the lightest amount of powder in the base game is currently .22CB (0 grains), the heaviest is 700 nitro at 252 grains.  Mods, of course, have more. The base game could reasonably have 20mm rifles added, or vintage artillery pieces  (Bofors cannons), if the metric of reasonableness is civilian ownership.

If you look at the handgun loads, you'll see that many use around 3 charges.

What should be happening here is pulling bullets to get max efficiency out of the loads (e.g. pulling all the .32 ACP and 9mm to load into 10mm or something), but often this doesn't really change how much powder goes in/out due to lack of granularity. As such, the above feature request.

**Comment by Fris0uman** [comment]
So basically being able to do `"weight": "65 mg"` is what you need?

**Comment by tenmillimaster** [comment]
@Fris0uman yes. Preferably `"weight": 0.065`, but I'll take what I can get.

**Comment by Fris0uman** [comment]
Ok, but if we mess with weight we might has well also move it to use strings.

**Comment by Fris0uman** [comment]
Alright so it's doable, I've made a nattempt that resulted in making every item weighting milligrams instead of grams. But once #33740 is merged and all item weights are edited to use string then it will be safe to do the change.

**Comment by forspamnstuff** [comment]
@tenmillimaster  Why not request weight in grains if it makes life easier? It is straightforward to implement now.

**Comment by tenmillimaster** [comment]
Decimal grains is what is more appropriate, which is a little silly to work with.
