### ISSUE TITLE
There is a idea about Feline

### ISSUE THREAD

**Issue by howmokas** [CleverRaven/Cataclysm-DDA#33463]
the cat can't drink the milk  but  why i see the wiki that the Feline not a mutation about that, i want to add a  Lactose Intolerance for the Feline

**Comment by TychaiosIlithios** [comment]
In theory not a problem - it is neither too unrealistic nor too necessary, but it brings a question - feline as it is is a rather ineffective set of mutations already and technically adding yet another negative to the line is further nerfing, so howobowut...:
Also a set of advanced post threshhold retractable claws giving an extra set of togglable special attacks and maybe climbing bonuses? Cuz cats trump dogs by trading more sleep for more limbs in combat - and currently it's good but singular set of teeth and hard as duck to get retractable claws which actually do not provide an attack worthy of a top feline for all the negatives in sleep and appearance that the feline gets.

**Comment by howmokas** [comment]
OK, i got it

**Comment by shadowsapex** [comment]
There's really no reason why the cat person should lose their lactase for being a cat person when they previously had the lactase

**Comment by RedShakespeare** [comment]
Actually cats themselves have got lactose intolerance so tho unnecessary it's reasonable for people to catch the idea, especially for those who keep cats at home.

**Comment by RedShakespeare** [comment]
Besides, climbing-improved claws or something like that seems really impressive to me.
