### ISSUE TITLE
Debug command to give all components needed to do a craft or construct

### ISSUE THREAD

**Issue by alkemann** [CleverRaven/Cataclysm-DDA#33469]
**Is your feature request related to a problem? Please describe.**  
When doing tests of issues with crafting and construction it can be cumbersome to have to manually give yourself all the components.

**Describe the solution you'd like**  
It would be great to have a command where you select a craft recipe or construction task and the game would give you enough tools and items (including all alternatives) you need to execute the craft/build yourself. 

**Describe alternatives you've considered**  
-

**Additional context**  
-

**Comment by G3Kappa** [comment]
This might be related to #25265 & family, but since it's a debug command for an individual item it should not be particularly demanding in terms of system resources.

**Comment by ampersand55** [comment]
Doesn't the Debug Hammerspace mutation address these problems?

**Comment by Zireael07** [comment]
@ampersand55: Nope, as you still have to debug in every item you need (which can be quite a lot for more complex crafts/constructs)

**Comment by kevingranade** [comment]
Hammer space overrides the crafting requirements and makes you able to
craft with no tools or materials.

Having said that, it is not a good test of the crafting code itself, so
it's only meaningful for creating things that can't be debugged in
otherwise, like vehicles with specific parts.
