### ISSUE TITLE
Recon mech always spawns (wanders?) outside the armored prototype chamber

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33472]
So it's frequently destroyed by nearby kevlar hulks and other fluffy critters.

0.D-6821-ga45ab51b18-dirty

**Comment by davidpwbrown** [comment]
ehhh, I worried this might happen , it's a pain in the ass to test lab finales.  I musta teleported to like 20 of them.
you got a save I can look at to see how far off it is?

**Comment by l29ah** [comment]
I hope a screenshot will do. I haven't moved it.
![](https://pstbin.ru/f/45428/)
