### ISSUE TITLE
Allow player to select which auto notes they want to see.

### ISSUE THREAD

**Issue by Feniks-Gaming** [CleverRaven/Cataclysm-DDA#33483]
**Is your feature request related to a problem? Please describe.**  

Currently auto notes are all or nothing system. Player can choose to have all of them or non. While useful it's not ideal solution 

**Describe the solution you'd like**  

In settings allow player to choose which map extras they want auto notes to mark

**Describe alternatives you've considered**  
There is no alternative as this is fairly simple issue

**Additional context**  
N/A

**Comment by ZhilkinSerg** [comment]
It is a json setting, so one can create mod with their preferred settings.

**Comment by Feniks-Gaming** [comment]
But why create a mod for 50 different combinations of possible settings when simple setting option would work better. 

Also sometimes you will want to change things as you play. Early on maybe those dead collage kids are useful late game they are just clutter. Being able to control it in game rather than editing json every time you want to change it is much more useful.

**Comment by nshcat** [comment]
I think I will give implementing this a try.

**Comment by nshcat** [comment]
@ZhilkinSerg This issue may now be closed due to the merging of #33560

**Comment by ZhilkinSerg** [comment]
Thanks.
