### ISSUE TITLE
All furniture storage became 1000L

### ISSUE THREAD

**Issue by gogis79** [CleverRaven/Cataclysm-DDA#33486]
# Describe the bug

All furniture storages in all my worlds have 1000L volume now. Vehicle storages work fine

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-6903-g9119b82 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classic Roguelike Classes [RL_Classes],
    No Filthy Clothing [no_filthy_clothing],
    Simplified Nutrition [novitamins],
    StatsThroughSkills [StatsThroughSkills],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    More Locations [more_locations],
    Beta National Guard Camp [national_guard_camp]
]

**Comment by gogis79** [comment]
Apparently caused by 33367

**Comment by ampersand55** [comment]
Yes.

I have a revert branch ready;

https://github.com/ampersand55/Cataclysm-DDA/tree/revert_furniture_max_storage

But it would be better to make furniture able to handle metric units for `max_volume` solution.
