### ISSUE TITLE
NPC trade, items nearby bug

### ISSUE THREAD

**Issue by curstwist** [CleverRaven/Cataclysm-DDA#33497]
# Describe the bug
NPC's should be able to trade with you from items they own within a reasonable distance (LOS).

NPC's will only recognize items directly next to them as trade goods.  Also, player can sell those same goods.

# Steps To Reproduce

1. Visit an NPC shopkeeper with items nearby.  I used Jack Isherwood.
2. Start trade.  If you are next to items (even of owned by their faction) you can trade them.
3. Move some items within 1 square of NPC
4. Now items are tradeable by both player and NPC.

# Expected behavior
NPC's can sell items within their LOS, in particular, items owned by their faction.
Player not able to sell items owned by a different faction.

# Screenshots
player only next to items:
![trade 1](https://user-images.githubusercontent.com/39442864/63630666-7c9a8a80-c5eb-11e9-9a51-6f09f0002533.PNG)

both next to a floor item:
![trade 2](https://user-images.githubusercontent.com/39442864/63630669-802e1180-c5eb-11e9-9c3a-73a012c2e725.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-6895-ge888867 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by devenv** [comment]
@kevingranade I think free roaming NPCs (not traders) can trade stuff on the floor now... Like corpses... I'll try to recreate once I have time on the latest build, saw it in this Vormithrax's video (recent build) - https://youtu.be/0KlamamFxtM?t=2955

**Comment by devenv** [comment]
The PR closed this bug too, right? https://github.com/CleverRaven/Cataclysm-DDA/pull/33685
