### ISSUE TITLE
Sprayable fungicide doesn't affect fungal creatures

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33496]
# Describe the bug

And doesn't even remove fungal beds it seems.
As used from the `makeshift chemical thrower` on some fungal flowers.

0.D-6896-g3825c9575b-dirty

**Comment by ipcyborg** [comment]
Can't reproduce in 0.D-6916-g566c2ba3a6.
Used `makeshift chemical thrower` loaded with `sprayable fungicide`. 
One shot is usually enough to deal with `fungal bed`. One or two for `fungal flower`. Also affects `fungal trees`, etc.

**Comment by l29ah** [comment]
Okay, rechecked it, and it in fact removes the fungal bed (but fungal haze/hazy cloud reestablishes it right after the fungicidal cloud vanishes). The fungal blossoms are in fact damaged.
Makeshift fungicidal grenades are much more effective for the buck tho.
