### ISSUE TITLE
Rivet Driver in CRIT expansion can only be used to kill yourself

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#33509]
# Describe the bug

In CRIT expansion mod a gun named Rivet Driver is added which has got a range of only 7 but an explosion range of 15 or more, which makes it totally nothing but a suiside choice. 

# Steps To Reproduce

1. Make a player with a Rivet Driver.
2. Try to aim at something at its max range and shoot it.
3. You die.

# Expected behavior

The explosion range should be less than the aiming range. 

# Screenshots

![image](https://user-images.githubusercontent.com/44523519/63637644-1d06b280-c6b1-11e9-8763-21e307b21285.png)
![image](https://user-images.githubusercontent.com/44523519/63637648-27c14780-c6b1-11e9-9283-3ef7ff0ba888.png)

# Versions and configuration

 - Game Version: [0.d-6866-g2bda93b or 0.d-9530]
 - Mods loaded: [dda, CRIT expansion]

# Additional context

Maybe the author should test his mod for at least one time instead of just uploading some astonishing items or features like this.

**Comment by Leland** [comment]
CC @Soupster89

**Comment by ZhilkinSerg** [comment]
Can you please retest whether it is still actual after #31090 is merged?

**Comment by Soupster89** [comment]
Uhm. Ok?

I'll fix it, but you don't have to be so snappy?

**Comment by RedShakespeare** [comment]
> Uhm. Ok?
> 
> I'll fix it, but you don't have to be so snappy?

Well, it's not personal... just some bad mood of private reason when this issue was edited. I'm sorry if I said something offensive.

**Comment by RedShakespeare** [comment]
> Can you please retest whether it is still actual after #31090 is merged?

Problem still exists...Maybe in the next few version it would be fixed. Thank you.

**Comment by kevingranade** [comment]
Keep your personal problems out of the repo, thanks.

**Comment by RedShakespeare** [comment]
> Keep your personal problems out of the repo, thanks.

The "bad mood" saying is some sort of polite language.  The bug **does** exist while the personal problem doesn't. No need to accuse maybe. :)
