### ISSUE TITLE
Fixing deafness using Autodoc

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33508]
**Is your feature request related to a problem? Please describe.**  
Certain explosions and house/lab cave-ins result in prolonged deafness. My character have accumulated 250 days worth of deafness just diving into the labs and shooting his railgun. 

**Describe the solution you'd like**  
It would be cool if an Autodoc could do an operation on ears that would replace the accumulated deafness with a fixed-duration one (a couple of days to reflect recovery). Would this be a reasonable addition to CDDA?

**Describe alternatives you've considered**  
https://github.com/CleverRaven/Cataclysm-DDA/issues/29261
Making deafness effect non-stacking.

**Comment by Zireael07** [comment]
Deafness effect should probably stack up to a certain ceiling (I assume 2-3 days?).
Alternately, excessive accumulated lengths should probably be treated as permanent. Yes, our sense of hearing is ridiculously easy to damage, but in most cases it heals by itself in a couple of days. Anything else, and you've permanently damaged it, usually by rupturing the membrane.

**Comment by tenmillimaster** [comment]
So, some kind of tympanoplasty?

**Comment by Zireael07** [comment]
@tenmillimaster yeah, something like that. IIRC we have stem cell treatment in CDDA, so that's an order of magnitude less complex.

**Comment by TychaiosIlithios** [comment]
Well then there should also go the bad back and all sight defects without implants - cuz they are more or less curable even now.

**Comment by kevingranade** [comment]
The stacking effect is probably something that needs fixing, temporary hearing loss should be meaningfully temporary.

Though if you were right on top of a large explosion, it *should* result in permanent deafness.

As for a tympanoplasty, a brief look says that kind of thing might be a reasonable option for an autodoc, which just leaves the question of what kind of hearing damage is treatable via this procedure.

In principle though, sounds like a viable option

**Comment by l29ah** [comment]
By the way, adding permanent deafness would demand some way to communicate with NPCs. Now it's impossible for deaf characters.

**Comment by Fris0uman** [comment]
Regarding #29261 it seems that turning bio_ears on make `is_deaf()` return false so in a way it already fix deafness.
I'm not clear on why it should fix deafness while off.

**Comment by ImportTaste** [comment]
@ZhilkinSerg Due to #34034, I think this should be re-opened.
