### ISSUE TITLE
Faction currency non-functional

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [CleverRaven/Cataclysm-DDA#33500]
# Describe the bug

 Both effects of defining a faction's currency (valuing the item at price instead of price_postapoc, and automatically populating shopkeeper inventory with currency) do not work. Bit important since dialogue and mission rewards make a big deal out of Free Merchants valuing Merch at $50, instead of $3.20.

# Steps To Reproduce

Trade with Evac Merchant, note absence of Merch in his inventory (has a chance of spawning other factions currencies due to them being explicitly added), also debug spawn in some Merch and note sale price when trading with him.

# Expected behavior

Faction NPCs would honor their specified currency at the value their dialogue claims they honor it at, shopkeepers would generate faction currency in inventory automatically as #31584 claims: faction shopkeepers always restock with some faction currency

# Screenshots

![image](https://user-images.githubusercontent.com/16777044/63631630-3693f580-c5f0-11e9-8e2a-1468d0034e08.png)

# Versions and configuration

Versions tested with: builds 9418 and 9535

Mods used: Dark Days Ahead, Disable NPC Needs

OS: Windows 10, 64-bit

# Additional context

Relevant links: 
https://github.com/CleverRaven/Cataclysm-DDA/pull/31584 (the PR that adds Flatcoin and such to Evac Merchant's inventory confirms that bug has been present since at least June, if not earlier)

**Comment by mlangsdorf** [comment]
Free Merchants Merch is worth $3.20 and there is nothing in the dialogues that claim or imply otherwise.

NPC Merchants restock their faction currency the second time they restock, but not on their initial restock.  I have no idea why but am looking into it.

**Comment by mlangsdorf** [comment]
randomize() was resetting the last restock time.  Restock times were not always being calculated correctly.  Patch should fix this.
