### ISSUE TITLE
Taze spell should drain mana, not bionic energy.

### ISSUE THREAD

**Issue by SlackingSleeper** [CleverRaven/Cataclysm-DDA#33517]
**Is your feature request related to a problem? Please describe.**  
The taze spell currently drains bionic energy. I thought it was a bug that I couldn't cast it until I checked the JSON and saw that it costs bionic energy rather than mana. It doesn't state that it does anywhere.

**Describe the solution you'd like**  
The spell should drain mana instead of bionic energy.

**Describe alternatives you've considered**  
Otherwise, the description should be altered to properly indicate that it costs bionic energy.

**Comment by LaVeyanFiend** [comment]
Not a bug, that's the flavor of Technomancer spells.

**Comment by KorGgenT** [comment]
not a bug
