### ISSUE TITLE
NPCs with Gasmasks/PBA won't path through gas clouds

### ISSUE THREAD

**Issue by curstwist** [CleverRaven/Cataclysm-DDA#33511]
# Describe the bug
NPC's won't move through gas clouds when wearing appropriate protection. I outfitted NPC's with an active PBA mask, and one had a hazmat suit, the other an ANBC suit.  They won't follow me through gas clouds.  I first encountered this at the Mi-Go encampment, but also tested in the mines.

# Steps To Reproduce

1. Spawn in an NPC, give them an active mask and suit to wear.
2. Try to lead them through gas vents like those found in mines.

# Expected behavior
NPC's should recognize their environmental protection.

# Screenshots
encampment /w temperature overlay:
![migo gas](https://user-images.githubusercontent.com/39442864/63638734-29abec00-c65a-11e9-8e66-263f5769b963.PNG)

mines:
![image](https://user-images.githubusercontent.com/39442864/63638744-37617180-c65a-11e9-9855-acaa6eb04fb6.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-6895-ge888867 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by mlangsdorf** [comment]
npc::sees_dangerous_field() checks Character::is_immune_field()
```
    bool immune_by_body_part_resistance = false;
    for( const std::pair<body_part, int> &fide : ft.immunity_data_body_part_env_resistance ) {
        immune_by_body_part_resistance = immune_by_body_part_resistance &&
                                         get_env_resist( fide.first ) >= fide.second;
    }
    if( immune_by_body_part_resistance ) {
        return true;
    }
```

so NPCs won't move through fields unless their last body part is immune to the field, which it will never be because immune_by_body_part_resistance is always false and the second part is never checked.

the logic should probably be:
```
    bool immune_by_body_part_resistance = true;
    for( const std::pair<body_part, int> &fide : ft.immunity_data_body_part_env_resistance ) {
        immune_by_body_part_resistance &= get_env_resist( fide.first ) >= fide.second;
    }
    if( immune_by_body_part_resistance ) {
        return true;
    }
```

**Comment by ZhilkinSerg** [comment]
> 
> 
> npc::sees_dangerous_field() checks Character::is_immune_field()
> 
> ```
>     bool immune_by_body_part_resistance = false;
>     for( const std::pair<body_part, int> &fide : ft.immunity_data_body_part_env_resistance ) {
>         immune_by_body_part_resistance = immune_by_body_part_resistance &&
>                                          get_env_resist( fide.first ) >= fide.second;
>     }
>     if( immune_by_body_part_resistance ) {
>         return true;
>     }
> ```
> 
> so NPCs won't move through fields unless their last body part is immune to the field, which it will never be because immune_by_body_part_resistance is always false and the second part is never checked.
> 
> the logic should probably be:
> 
> ```
>     bool immune_by_body_part_resistance = !ft.immunity_data_body_part_env_resistance.empty();
>     for( const std::pair<body_part, int> &fide : ft.immunity_data_body_part_env_resistance ) {
>         immune_by_body_part_resistance &= get_env_resist( fide.first ) >= fide.second;
>     }
>     if( immune_by_body_part_resistance ) {
>         return true;
>     }
> ```

I've just came to same results.
