### ISSUE TITLE
"Reload" with bow in inventory will only attempt to reload bow with other options removed

### ISSUE THREAD

**Issue by StudleyKansas** [CleverRaven/Cataclysm-DDA#33515]
# Describe the bug

With a bow in inventory, whether equipped, strapped, or just sitting in inventory, hitting the reload key default "r" attempts to reload the bow, and does not bring up the normal reload screen giving the player the choice of what to reload.

# Steps To Reproduce

1. Pick up any bow (not crossbows, they work as expected)
2. Pick up at least one arrow or a quiver with at least one arrow in it
3. Pick up something else that you might want to reload, such as an empty plastic bottle
4.  Hit the reload key and notice that a couple seconds pass in game, but the "Reload item" menu doesn't appear

# Expected behavior

I would like the "Reload item" menu to appear while holding a bow, so that I can reload other items through this convenient menu rather than other methods.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-6930-ge1e05ce [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Beta National Guard Camp [national_guard_camp]
]

# Update

I just learned that switching my "r" key from "Reload wielded item" to "Reload item" reliably brings up the "Reload item" menu with a bow in my inventory.  I'll probably want to switch it back to "Reload wielded item" when I'm using guns or crossbows, but this serves just fine as workaround.

**Comment by Night-Pryanik** [comment]
I think this could be considered resolved after #32798.
