### ISSUE TITLE
FB51 Optical Cloak powers off immediately after activation

### ISSUE THREAD

**Issue by AlexanderBodnya** [CleverRaven/Cataclysm-DDA#33522]
Description:

The next turn after cloak activation, cloak deactivates, no matter what you do.

# Steps To Reproduce

1. Wear charged UPS and optical cloak
2. Activate cloak.
3. Do anything (wait, walk etc), cloak will deactivate, no power from UPS will be consumed.

# Expected behavior

Cloak should not deactivate, it should make you invisible and consume UPS power every turn

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-6936-ge442b42 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Bens GF recipes [Tolerate_This],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    No Acid Zombies [No_Acid_Zombies],
    No Ants [No_Anthills],
    No Bees [No_Bees],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

On the side note cloak should cover head also, not only torso and limbs (otherwise it would be strange)

**Comment by alkemann** [comment]
I were able to use the cloak just fine, were unable to recreate (world didn't match mods setting though).

**Comment by AlexanderBodnya** [comment]
was able to repro woth only
 - OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-6965-g20d267b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion]
]

Also here's link with video - https://drive.google.com/file/d/1LL6RxNzQGxaOiOk5eUG2VEHYoucKlTp9/view?usp=sharing

**Comment by alkemann** [comment]
Your build is 6965?  Current build is 9544. Maybe update the game?

**Comment by AlexanderBodnya** [comment]
The version inside the game does not match with the build version. I will upload a video a few minutes later to demonstrate it. Or, you can check for yourself, you know.

**Comment by AlexanderBodnya** [comment]
Also as you can see at build info

https://ci.narc.ro/job/Cataclysm-Multijob/9545/

revision `20d267b` checks out.

**Comment by AlexanderBodnya** [comment]
It even reproduces on android.

**Comment by alkemann** [comment]
Is it only when you wear the UPS?

**Comment by AlexanderBodnya** [comment]
It happens if UPS in inventory and if you are wielding it. If you don't have charged UPS it shows message that you need one, so that part works as intended.

**Comment by AlexanderBodnya** [comment]
Additional information - it works with UPS CBM, however it does not work with regular UPS

**Comment by Rhyssia** [comment]
Win 7 (1701?) (64b)
0.D-7354-ge42b8d2 (tiles)

Works when UPS is in inventory, does not work if UPS is worn.

![Cloak](https://user-images.githubusercontent.com/24862205/64469468-b3e75c00-d100-11e9-854e-07e3d2b771ef.jpg)

**Comment by dunstad** [comment]
I'm pretty sure the UPS can't be worn in the base game, so is this a bug with Aftershock perhaps?
