### ISSUE TITLE
Can't craft at low skill levels with paws

### ISSUE THREAD

**Issue by shadowsapex** [CleverRaven/Cataclysm-DDA#33521]
# Describe the bug

At tailoring (and I assume also electronics and mechanics) level 1 a craft I attempt will never progress and will destroy all my materials with failures, while staying at 0%. This also means I can never gain experience and therefore can't skill up to level 2, where the issue doesn't seem to exist.

# Steps To Reproduce

1. Make a player with paws mutation
2. Increase tailoring to level 1
3. Spawn in hundreds of rags and thread and try to craft arm warmers
4. You'll run out and never make progress

# Expected behavior

The craft to progress. Some limits on the craft failure penalty so it can't consume 50 or so material would also be good.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-6930-ge1e05ce [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Maddremor** [comment]
To clarify: Do you think that an unskilled crafter should be capable of completing a craft regardless of impediments to fine manipulation, or that paws should not put you below that threshold?

**Comment by shadowsapex** [comment]
There needs to be, at least, a way to skill up, cause with no progress being made you'll never gain exp. Also, it just seems unreasonable and not too realistic that a craft with high penalties can use up hundreds of materials (I tried a duffel bag and used like 500 rags before I gave up).

**Comment by Maddremor** [comment]
But if you are clumsy enough, would you be able to actually craft anything to learn from? If using up too much materials is the problem, getting a popup informing the player of that or even graying the recipe out in the menu is a possibility.

**Comment by shadowsapex** [comment]
I am not going to play at tailoring 1. That is not reasonable to me

**Comment by shadowsapex** [comment]
On second thought I doubt anyone runs into this issue who's not playing wacky debugged characters for fun, so it doesn't really matter
