### ISSUE TITLE
Tacoma Commune faction missions are still hard-coded and require an unrotated map

### ISSUE THREAD

**Issue by TJKing293** [CleverRaven/Cataclysm-DDA#33525]
# Describe the bug

When turning in the "collect 300 salt" quest from the ranch foreman everything is normal until I exit the dialog menu. Then the foreman and the other npc with him vanish along whith the tractor. I get this

DEBUG    : Tried to access invalid map position at grid (172,180,0)
 
 FUNCTION : size_t map::get_nonant(const tripoint&) const
 FILE     : src/map.cpp
 LINE     : 8075

# Steps To Reproduce

attempt to complete the mission

# Expected behavior

To not go away
[save_file.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3537645/save_file.zip)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-6936-ge44b42
 - Graphics version:Tiles
 - Mods loaded:   
. "dda",
  "no_npc_food",
  "No_Rail_Stations",
  "Mining_Mod",
  "hydroponics",
  "fast_healing",
  "alt_map_key",
  "More_Survival_Tools",
  "no_mutagen",
  "No_Acid_Zombies",
  "No_Big_Zombies",
  "No_Explosive_Zombies",
  "No_Fungi",
  "no_filthy_clothing",
  "no_reviving_zombies",
  "novitamins",
  "StatsThroughSkills"

# Additional context

**Comment by smackdabinthemiddle** [comment]
I came across the exact same problem, in build 9547, Windows x64.

The Foreman and Carpenter, along with the Plow Tractor vanish from the barn for a couple of turns. The Tractor returns (after 5 min of waiting, with the diesel fuel dropped on the floor, while the NPCs are teleported elsewhere, next to a Carpenter NPC, which in my save is a couple of tiles away from the farm itself.
Here's the [save](https://github.com/CleverRaven/Cataclysm-DDA/files/3541642/save.zip) if it's of any use.

**Comment by smackdabinthemiddle** [comment]
In my case, yes. The ranch is north of the field, and the garage east of the ranch.

**Comment by TJKing293** [comment]
It's oriented house north pond south. So yeah it is.

**Comment by mlangsdorf** [comment]
The Tacoma Commune upgrade missions that are still hardcoded will update the map in strange ways if the ranch is rotated.

I think the short term solution is to make the refugee ranch map non-rotatable.

**Comment by mlangsdorf** [comment]
Removing this from the 0.E tracker - we have a work-around that's good enough for 0.E but will need to go back and fix it properly later.
