### ISSUE TITLE
Make faulty bionics dissasemblable

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#33529]
**Is your feature request related to a problem? Please describe.**  
Since the last craftable bionics were removed, faulty bionics do nothing more than taunt the player. 

**Describe the solution you'd like**  
Have them be dissasemblable and drop, for example: Micro motor, bioplastic (same stats as plastic chunks), copper wire, amplifier circuit, electronic scraps x3, signal transceiver?

**Describe alternatives you've considered**  

If dissasembly is capable of having random "drop rates" we could make disassembling faulty bionics a fun source of rarer stuff that is somehow related to bionics. 5% drops of plutonium from the internal reactor, high quality lens from diamond cornea, 1% chance of teleporter with 1 charge, etc.

**Comment by Xenomorph-III** [comment]
You'd do good to clean them with an autoclave/dishwasher, first. They're gonna be covered with filth after ripping them from your flesh.

But, I support this idea.

**Comment by Fris0uman** [comment]
Should be doable through some simple json edit: https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors
