### ISSUE TITLE
Introduce a penalty when operating vehicles while crouching 

### ISSUE THREAD

**Issue by EirenexTheDragon** [CleverRaven/Cataclysm-DDA#33533]
**Is your feature request related to a problem? Please describe.**  
One of the easiest way to not get spotted in a vehicle from far, is to simply crouch while operating a vehicle. its very useful when dealing with deadly mini tanks or other monsters you dont want to be seen with. ofcourse it should be rather weird though when handling a vehicle while you are crouching. there is no difference in crouching or sitting in a vehicle normally ,so its only best to crouch while using it, unless you want to be seen.

**Describe the solution you'd like**  
A penalty to the driving skill, while crouched, or making it harder to take turns, or even have the sight reduced while crouching in a vehicle. you cant see all the way to the end when your head is closer to the ground than before. anything that requires your feets on pedals,it should drain more stamina while using it. 

**Describe alternatives you've considered**  
making it impossible to use crouching while operating the vehicle.

**Additional context**  
I know its possible to crouch down in a vehicle and still use it, its like putting a small child to steer a car while its sitting normally, so i think the penalty to driving might be the best solution here. maybe reduce it by -5 or around that number.

**Comment by Lamandus** [comment]
makes sense, but rather than driving penalty (even with 0 you can drive okey), you should have a very limited view, if any. I mean, the enemy sees you the way you see him. So if you don't want to get spoted, dive, but drive blind. Which makes interesting choices when driving through cities...
Although our map rememberance is so good, we can just peek a boo the way out of the mess...

**Comment by EirenexTheDragon** [comment]
> 
> 
> makes sense, but rather than driving penalty (even with 0 you can drive okey), you should have a very limited view, if any. I mean, the enemy sees you the way you see him. So if you don't want to get spoted, dive, but drive blind. Which makes interesting choices when driving through cities...
> Although our map rememberance is so good, we can just peek a boo the way out of the mess...

drive blind is quite interesting to say though! i think thats a good solution in addition to a driving penalty still
