### ISSUE TITLE
Segfault when turning in 'gather 120 rocks' 

### ISSUE THREAD

**Issue by JacobKessler** [CleverRaven/Cataclysm-DDA#33539]
# Describe the bug

I met a random NPC who asked me to gather 120 rocks for a kiln. When I did that, they 
started looking for a map tile at MIN_INT, and then the game crashed.

# Steps To Reproduce

Encounter a random NPC who gives the 'gather 120 rocks for a kiln' mission
Complete the mission

# Expected behavior
The mission is turned in successfully. Maybe a kiln is built?
Alternately, since this looks like it's part of the "Isherwood farm" mission string, and seems to be trying to find something, there might be a problem with completing the mission before finding the farm. If that's the case, then random NPCs shouldn't give the mission.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-67`7-g55206497c6. This is a local branch, the last Master commit is 367f3a8
 - Graphics version: Tiles
 - Mods loaded: 
[
  "dda",
  "no_npc_food",
  "crt_expansion",
  "ArmUpSurvEx",
  "craftgp",
  "growable-pots",
  "ew_pack",
  "Medieval_Stuff",
  "nw_pack",
  "SM",
  "DinoMod",
  "hydroponics",
  "mutant_npcs",
  "MMA",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "blazemod",
  "Tanks",
  "deoxymod",
  "DP_XOTTO_INDICATORS",
  "manualbionicinstall",
  "Nonperishable_Overhaul",
  "rmod",
  "safeautodoc",
  "stats_through_kills",
  "StatsThroughSkills",
  "speedydex"
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3538298/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3538299/debug.log)

I can provide the save if needed, but that seems potentially less useful since it's not on a 'real' version

**Comment by curstwist** [comment]
Yeah, so it was a random npc? Thanks for reporting it.

**Comment by ZhilkinSerg** [comment]
Should be fixed in #33541.
