### ISSUE TITLE
Friendly NPC vision merge

### ISSUE THREAD

**Issue by Muntari** [CleverRaven/Cataclysm-DDA#33544]
NPC walk in dark tiles are hard to account for & instruct, merging the NPC vision with the player's makes it also viable to order them to guard entrances\exits while rummaging indoors.

Walking into NPCs in the dark does seem bit wonky since the game prompts interaction with an invisible NPC.

**Comment by Qrox** [comment]
> merging the NPC vision with the player's
That's probably not very realistic. How's the player supposed to know right away everything the NPC is seeing? A better solution IMO is to add an NPC command to let them describe what they are seeing (monsters, items, etc).

> the game prompts interaction with an invisible NPC
Add some message about you bumping into something and finding out it's your friend?

**Comment by Muntari** [comment]
Perhaps limit the range to NPCs within your earshot?

I suppose making the NPC describe its environment needs to be updated when things are added to the game and it's time consuming just to read what the NPC is reporting because alot of things could be listed like items, monsters, vehicles, etc...
Ultimately its the same as having their vision.

**Comment by Qrox** [comment]
They probably won't describe everything they are seeing, only those that is significant at the moment. For example, if they see a kevlar hulk ten meters away, then they won't report a crawling zombie that is barely visible at the horizon. Or you can ask them and select a specific tile for them to describe.

**Comment by DarianLStephens** [comment]
Perhaps it could be a periodic update for your map memory (Lore-wise, they're telling you if anything's changed), and live tracking of nearby enemies that they can see? (Perhaps anything they'd otherwise call out 'Watch out for that x' for?)
I could see an argument for that 'live feed' cutting out when they actually engage in combat with them, as well.

**Comment by DarianLStephens** [comment]
My thought process for it updating map memory is that it won't give you that much info anyway. You'd only really know if a vehicle moves or a house burns down; some kind of tile change.
As for monster tracking, even without knowing the exact location, it could perhaps work similar to the way sounds do when you can't see their source; a radius around the area it actually originates from.

I agree that you'd want it to be something you tell them to do, or perhaps you mean something that only updates when you ask for it?
I'd like it to be a new mode you can command, like 'Stand Guard and Give Updates', so they'll autonomously keep you updated without having to explicitly ask for it each time, though upon reflection I _can_ see the enhanced realism and potential value in that.
My main concern with it being merely a dialogue option is that you'll have to call out to them or use a radio, navigate the conversation menu, ask for the update, then probably say 'Goodbye' again, which is a bit annoying to do regularly.
Or perhaps the idea is that you'd only ask for updates if you hear something or they tell you something's going on over radio? Then you'd ask for them to describe the situation and you'll get a map memory update or begin tracking the rough location of a monster.

Maybe it could be an addition to the memory; temporary monsters, the 'last known location', but that might be beyond the scope of this request.

**Comment by dynst** [comment]
Getting brief pseudo-clairvoyance by requesting a report over a `two_way_radio` from a guarding/scouting NPC would make sense if it also has a chance for the request to make the NPC bored or irritated, refusing to give anything more detailed than a map terrain update.

Or having an NPC's POV for the spectating player in #81834 might be good.
