### ISSUE TITLE
Merge Vehicle tiles with Map Memory while driving

### ISSUE THREAD

**Issue by Muntari** [CleverRaven/Cataclysm-DDA#33545]
Vehicle tiles out of vision are hard to account for when driving, making reverse driving & sensitive tasks like parking more difficult.

Adding the vehicle tiles to Map Memory if possible shouldn't reveal any info the player doesn't normally know when the tile is out vision, like items in that tile for instance.

**Comment by nshcat** [comment]
I am also for this. There is no reason this should not be added in my opinion, it's such a quality-of-life improvement.

**Comment by kevingranade** [comment]
Why don't rear-view mirrors cover this use case?

If you don't arrange for improved visibility, this is absolutely a situation that crops up IRL, so I'm not particularly inclined to work around it in the UI like this.

**Comment by BaumgeistOne** [comment]
I agree. Rear-view mirrors are easy enough to find, plus they can be used as inboard mirrors too.

**Comment by ZhilkinSerg** [comment]
Disable map memory and see whether you can see a whole vehicle. I bet not.
