### ISSUE TITLE
Extend Batch Craft Limit

### ISSUE THREAD

**Issue by ebolite** [CleverRaven/Cataclysm-DDA#33563]
**Is your feature request related to a problem? Please describe.**  
Now that in-progress crafts are a thing and you can be interrupted while you craft without having to start over, the limit of 20 batch productions is unnecessary. Furthermore, with the addition of batch savings, it can be frustrating to only be able to make 20 items. For example, mutagen's batch savings currently only kicks in after 20 units, so the batch limit prevents you from ever saving time.

**Describe the solution you'd like**  
Increase the maximum batch amount to 50.

**Describe alternatives you've considered**  
If increasing the maximum batch amount to 50 makes navigating the UI difficult, a crafting UI change could be implemented. Instead of being able to select how many items you would like to batch craft, you could be able to type in a number before crafting the item (or some other method) to decide how many you would like to make. This input should tell you what the maximum amount of items you are currently able to craft is. In addition to extending the batch limit, this also seems more intuitive than selecting from 1 of 20 options in a drop-down.

Another alternative is changing the batch savings cut-offs of certain recipes to reflect 20 units being the maximum batch size (namely mutagen). It is also very possible that mutagen's (currently broken) batch savings cut-off is unintentional, and instead of increasing the batch amount, recipes in this vein could be changed to function instead.

**Additional context**  
How the UI could potentially display item/times costs after a [b]atch number has been chosen (alternative 2)
![mockup](https://user-images.githubusercontent.com/22662047/63684487-a1952600-c7c2-11e9-84d3-34cc82f67e96.png)

Also, the exact number that the limit should be raised to could be different. 50 simply seems like a round and reasonable value.

**Comment by ZhilkinSerg** [comment]
Not that it fixes the issue, but you can "recraft last recipe" and "craft as long as possible":

![image](https://user-images.githubusercontent.com/16213433/63685893-2c990f00-c809-11e9-83c9-bee94f293741.png)

**Comment by kevingranade** [comment]
In order to enable larger batches, there need to be some configurable limits on it based on resources, like number of heat sources or containers.
