### ISSUE TITLE
Automatically update overmap if forest is burned

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#33565]
**Is your feature request related to a problem? Please describe.**  
So I have the habit of burning the fungus where ever I see it, and if it is in a forest, well, then more often than not the forest has to go too. I then mark every overmap tile that is completely burned down with a user note (so I'm able to remember which part of the forest is cleared for driving), which is quite tedious.

**Describe the solution you'd like**  
Moving into an overmap tile which is marked as "forest", but does not contain any trees, should change the overmap marking to "field".

**Describe alternatives you've considered**  
Checking every overmap tile in the "reality bubble", but I don't know how feasible that would be.

Since "fields" can contain a few trees, maybe the check should not look for "no trees", but for "less than x trees".

**Additional context**  
The basecamp mission "chop wood" does change tiles from "forest" to "field", maybe one could use some code from there.

**Comment by zeziba** [comment]
I like this idea. I would suggest though that it something where like the feature that labels the map with special features that it also scans the map for any fire and labels them appropriately. Then if a structure is damaged enough it changes it then.

This would allow a user to run around with the pyro trait and as he/she starts the map ablaze it would automatically update it as most fires can be seen from a very long distance off. Plus a building would appear decrepit once it reaches a certain level of damage from fire.
