### ISSUE TITLE
Path blocked while sorting freeze the game

### ISSUE THREAD

**Issue by SlackingSleeper** [CleverRaven/Cataclysm-DDA#33581]
# Describe the bug

When initiating a sort the game instantly froze. When attempting to recreate the bug the message log started filling up with messages about something being in the way before the game froze.

# Steps To Reproduce

Load the character in the provided savefile.
Sort (O->o)

# Expected behavior

The player should stop sorting and there should appear a prompt or message in the log that explains why the sorting was stopped.

# Versions and configuration

- OS: Windows
    - OS Version: Win 8.1
- Game Version: 0.D-7009-gd8f806f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Icecoon's Arsenal [ew_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

# Additional context

[SortBug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3545466/SortBug.zip)

**Comment by davidpwbrown** [comment]
confirmed. and fix PRed
