### ISSUE TITLE
Coughing during a cold prevents sleeping even when Dead Tired

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33588]
# Describe the bug

This is certainly not your usual cold :)

[2019.08.27.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3547167/2019.08.27.zip)
0.D-7016-gf918a1454e-dirty

**Comment by howmokas** [comment]
may be it wake because of the sound

**Comment by l29ah** [comment]
No, it wakes me up even if i enable Sound Dampeners.

**Comment by Zombiemanpig** [comment]
I agree this is not realistic, no way a cold wakes you up every hour cause of coughing.
