### ISSUE TITLE
idea for carnivore/herbivore rework

### ISSUE THREAD

**Issue by Relyksboa** [CleverRaven/Cataclysm-DDA#33580]
**Is your feature request related to a problem? Please describe.**  
The carnivore traits and herbivore traits are poorly thought out, as they both seem only to just be giant filters on what the player can eat ( this is more pronounced for carnivore) without any adaptation to the new diet before hand.
**Describe the solution you'd like**  
Therefore the traits should be reworked into a chain of traits that increase enjoy-ability, health values, and allow raw meat or veggies to be more easily edible. while decreasing enjoy-ability, health values and cause nausea and eventually loss of edibility.

**Describe alternatives you've considered**  
leaving the loss of edibility to obligate herbivores (such as bovines) or obligate carnivores (felines and raptors), shortening the chain of mutations to two or three.

**Additional context, Edited: lowered the chain size 'cause four really is too much**  
Examples:
Carnivorus:eating meats is healthier (+1) and makes you happier (+1), plants have a 20-30% chance to cause nausea and are less healthy (-1) and less happy (-1) side note: maybe have eating foods with both meat and veggies having the option to trigger the current carnivore ability od eating meat?
Obligate carnivore: meat is even more healthy (+2) and you lose chance of food sickness from raw meats, you still wont enjoy eating raw meat but it will be a healthy alternative until you can cook it again.
For herbivores, same thing, but plants are good and meat is bad

**Comment by kevingranade** [comment]
Ok so carnivores don't have many healthy food options.  So adding a health boost to meat will pretty much resolve this issue won't it? It's kind of irrelevant whether this happens in the carnivore trait or a new trait.

Sudden onset or, "massive fist to the face" isn't really a problem, I wouldn't object to someone breaking down carnivore or herbivore into pieces, but you're going to transition from omnivore to carnivore or herbivore at some point, and that's going to be sudden no matter how it's handled.

**Comment by Relyksboa** [comment]
Increasing meat product health gain would help solve part of the issue.

>but you're going to transition from omnivore to carnivore or herbivore at some point, and that's going to be sudden no matter how it's handled

Rather than stating that like disintegration, spreading these into more mutations out would make it less sudden and arguing further. I will close the issue and wait until the proposed changes to mutations to make them appear over days rather than instantly start happening and suggest this or maybe pr it then.
