### ISSUE TITLE
ASCII mojibake in console

### ISSUE THREAD

**Issue by Kodiologist** [CleverRaven/Cataclysm-DDA#33592]
# Describe the bug

Non-ASCII characters display as multiple nonsense characters, which are probably some kind of mojibake of their UTF-8 encoding.

# Steps To Reproduce

I can see some of this mojbiake in the default sidebar (like `M-b~F~Q` next to "Comfortable"; the `~F~Q` parts wraps down to the following line), but I'm not sure what characters are supposed to be there.

If I open the inventory, type `/` to search, and type a non-ASCII character, then I can type an ASCII character repeatedly to see the whole output. For examle, when I type `π` (via an XCompose setting), I get `M-O~@`.

# Expected behavior

Unicode should display as Unicode.

# Versions and configuration

 - OS: Lubuntu 19.04
 - Game Version: Compiled from source, commit f918a1454e97e7b2f488b47f43f3629605dd072c
 - Graphics version: Terminal

# Additional context

I see the issue on Konsole as well as xterm, and with `TERM` set to `xterm-256color` or to `xterm`. `LANG` is `en_US.UTF-8`.

**Comment by Kodiologist** [comment]
I figured it out wth the help of [this page](https://christiantietze.de/posts/2018/09/ruby-ncurses-macos-linux/). This is what you see when ncurses tries to print non-ASCII characters; ncursesw is necessary. If you compile Cata with `LOCALIZE=0`, as I did, then `ncurses5-config` is used in place of `ncursesw5-config`, probably on the assumption that the English-language version of Cata is ASCII-only. What should probably happen here is that the Makefile should unconditionally use ncursesw.

**Comment by gordon-quad** [comment]
I have same issue but by replacing ncurses with ncursesw by hand in ccmake config causes cataclysm to segfault.
Issue you described happens with my build even when I have `LOCALIZE=1`.

@Kodiologist, if you managed to fix it can I ask you to tell precise actions that you did to fix it?

**Comment by Kodiologist** [comment]
@gordon-quad, all I did was compile with `make LTO=1 LOCALIZE=1 -j8 RELEASE=1` and then everything was good. If you're still seeing mojibake, one thing to check is the environment variable `LANG`. It should probably end with `.UTF-8`. For example, my `LANG` is `en_US.UTF-8`.

**Comment by gordon-quad** [comment]
Thanks for your help. It seems cmake build is broken regardless of setting `LOCALIZE`. I build it through regular make without using cmake and now it works!

**Comment by kevingranade** [comment]
So transient build errors of various kinds, correct me if that is inaccurate

**Comment by Kodiologist** [comment]
@kevingranade I can't speak for the problems @gordon-quad was seeing with CMake, but the Makefile seems to incorrectly assume that ncurses, not ncursesw, suffices for English-only builds. In reality, ncursesw is necessary for correct display even in English.
