### ISSUE TITLE
Problem with "Last Character" preset

### ISSUE THREAD

**Issue by stibbons01** [CleverRaven/Cataclysm-DDA#33591]
# Describe the bug

If you select the "Last Character" preset for an existing world the following debug message comes up in the "Verifying" stage:

```
 DEBUG    : tried to set invalid id of a npc/player: -1
 
 FUNCTION : void Character::setID(character_id)
 FILE     : src/character.cpp
 LINE     : 168
```

The game starts regardless of the message after pressing "Space".

# Steps To Reproduce

1. Create a world
2. Create a character
3. Die / Suicide
4. Create a new game in the previous world 
5. Select Preset Character
6. Select Last Character
7. Start the game

# Expected behavior

This message should not appear.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-7009-gd8f806f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

- Debug Log: [debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3547393/debug.zip)
- Save File: [Nova.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3547392/Nova.zip)

**Comment by OzoneH3** [comment]
This pr is the culprit: #33344

Templates are saved with a character id of -1.
Loading a template uses the same load() function as when loading a character.
Maybe a solution would be to git templates an id of -2 to be able to differentiate?!

**Comment by jbytheway** [comment]
OK, there was a distinction between id 0 and id -1 before I did #33344.  I thought it was only relevant for legacy saves, but I guess it's also relevant for templates, so I broke this.  Will look into it.
