### ISSUE TITLE
Multicooker crashes the game

### ISSUE THREAD

**Issue by CorvetBlyat** [CleverRaven/Cataclysm-DDA#33593]
# Describe the bug

When using the Multicooker (from the inventory, not from the crafting menu), the game crashes

# Steps To Reproduce

1. Spawn a Multicooker and ingredients for any recipe compatible with it's auto-cooking
2. Use the Multicooker and try to choose a recipe (Whether with the bulk craft button or enter)
3. Crash

# Expected behavior
I have never successfully used it before. However i assume that after a time delay the food item is crafted and the Multicooker looses some charge.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-7009-gd8f806f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Test World.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3547640/Test.World.zip)
[Crash + Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3547641/Crash.%2B.Debug.zip)

**Comment by stibbons01** [comment]
Can confirm that. Tried it with the provided savegame and afterwards with a fresh world and character too. In both cases the game crashed after selecting the recipe with the multi cooker.
