### ISSUE TITLE
Cannot cut items up with bionic claws

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33597]
# Describe the bug

Even though they have `1 cutting` quality.

[2019.08.28.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3548198/2019.08.28.zip)

0.D-7016-gf918a1454e-dirty

**Comment by Night-Pryanik** [comment]
You don't forget to activate them before trying to cut things up, do you?
Tested right now - activated bionic claws and successfully cut the jumpsuit.
![изображение](https://user-images.githubusercontent.com/11132525/63855944-a53acf80-c9b1-11e9-9e37-ce81c748d444.png)

**Comment by l29ah** [comment]
![](https://pstbin.ru/f/20960/)

**Comment by Night-Pryanik** [comment]
So, claws in fact are able to cut things up, they just don't appear as a valid tool in the item actions menu.
