### ISSUE TITLE
Nuclear missile doesnt destroy fungal towers

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#33606]
# Describe the bug

After nuking a fungal tower site I teleported to check. The Fungal tower was still standing.

# Steps To Reproduce

Activate a nuclear silo. Aim at the tower. 

# Expected behavior

Nuclear Missile should annihilate it.

# Versions and configuration
 - OS: Windows 7
 - Game Version: 0.D-7022-g65f000a (tiles)
 - Graphics version: Tiles
 - Mods loaded: Beta National Guard, No NPC needs

# Aditional Context
![image](https://user-images.githubusercontent.com/5623801/63827397-fbb3f980-c930-11e9-93f4-5ae1a3556fbf.png)

Sadly I saved before teleporting, so I cant share a save with both the silo and the fungal bloom available.

**Comment by junknowny** [comment]
Just like in #13770, the problem is that the way nukes currently work just irradiates the place they target and replaces most of its terrain with rubble. They don't damage monsters at all.

**Comment by Night-Pryanik** [comment]
> Just like in #13770

It's not _exactly_ like in #13770, because nukes do kill all the NPCs in the affected area.

**Comment by kevingranade** [comment]
Disabling the nuke launch option is a completely reasonable fix for this
IMO.

**Comment by kevingranade** [comment]
Go ahead and try it if you think it'll work.

**Comment by zeziba** [comment]
I am looking into this as it seems cool.

https://discourse.cataclysmdda.org/t/nuclear-missle-damage-map-deformation/21235/7

I would really like to see the nuke actually destroying huge chucks of the map as it is so late game/difficult to obtain that it should have a last option feel to it.
