### ISSUE TITLE
Granularize Cartridge Reloading: Bullet Molds proposals

### ISSUE THREAD

**Issue by tenmillimaster** [CleverRaven/Cataclysm-DDA#33603]
As part of the ongoing powder rework project I've got going on, and as necessary to be able to produce factory quality reloads, it is necessary to make cast/bullet pulled projectiles more inline with reality. As such, a number of molds would be necessary to produce bullets of each caliber. 

**Describe the solution you'd like**  

These are the molds I intend to add. It would be assumed that each mold diameter can produce varying weights and geometries of projectiles. These would produce lead only balls, spitzers, wadcutters and hollowpoints, no jackets. 

Some planned caliber additions have been listed below, .350 legend, .223 BOZ, .243 winchester, etc.

| Diameter              | Caliber            | Can swage to?          | 
|-----------------------|--------------------|------------------------| 
| 0.180in. mold covers: |                    |                        | 
|                       | 4.6mm              |                        | 
| 0.220in. mold covers: |                    |                        | 
|                       | 5.45x39            |                        | 
| 0.224in. mold covers: |                    | .224 can swage to .220 | 
|                       | 0.223              |                        | 
|                       | 0.22               |                        | 
|                       | 5.7                |                        | 
|                       | .223 BOZ           |                        | 
| 0.243in. mold covers: |                    |                        | 
|                       | .243 winchester    |                        | 
|                       | 6mm ppc            |                        | 
| 0.251in. mold covers: |                    | .251 can swage to .243 | 
|                       | .25 ACP            |                        | 
| 0.270in. mold covers: |                    |                        | 
|                       | .270 Winchester    |                        | 
|                       | 6.8mm SPC          |                        | 
| 0.309in. mold covers: |                    |                        | 
|                       | 30.06              |                        | 
|                       | 7.62x51            |                        | 
|                       | 300 win            |                        | 
|                       | 300 BLK            |                        | 
|                       | 7.62x25            |                        | 
|                       | .30 Carbine        |                        | 
|                       | .30-30             |                        | 
| 0.311in. mold covers: |                    | .311 can swage to .309 | 
|                       | 7.62x39            |                        | 
|                       | 7.62x54R           |                        | 
|                       | .303 British       |                        | 
| 0.313in. mold covers: |                    | .313 can swage to .311 | 
|                       | .32 ACP            |                        | 
| 0.323in. mold covers: |                    |                        | 
|                       | 8mmx40             |                        | 
|                       | 8mm Mauser         |                        | 
| 0.355in. mold covers: |                    |                        | 
|                       | .38 Special        |                        | 
|                       | .357 Sig           |                        | 
|                       | .357 mag           |                        | 
|                       | 9x19               |                        | 
|                       | .380 Auto          |                        | 
|                       | .38 Super          |                        | 
|                       | .350 Legend        |                        | 
|                       | 9x39               |                        | 
| 0.365in. mold covers: |                    |                        | 
|                       | 9x18 mak           |                        | 
| 0.375in. mold covers: |                    |                        | 
|                       | .36 Cap and ball   |                        | 
| 0.400in. mold covers: |                    |                        | 
|                       | .40 S&W            |                        | 
|                       | 10mm Auto          |                        | 
| 0.410in. mold covers: |                    |                        | 
|                       | 410 'gauge'        |                        | 
| 0.430in. mold covers: |                    |                        | 
|                       | 44 magnum          |                        | 
| 0.455in. mold covers: |                    |                        | 
|                       | .460 rowland       |                        | 
|                       | .45LC              |                        | 
|                       | .45ACP             |                        | 
|                       | .45 Colt           |                        | 
|                       | .454 Casull        |                        | 
| 0.458in. mold covers: |                    |                        | 
|                       | .45-70             |                        | 
| 0.500in. mold covers: |                    |                        | 
|                       | 500 S&W            |                        | 
|                       | .50 BMG            |                        | 
|                       | .50 Beowulf        |                        | 
| 0.576in. mold covers: |                    |                        | 
|                       | 20 gauge slug      |                        | 
| 0.700in. mold covers: |                    |                        | 
|                       | 12 ga slug(foster) |                        | 
|                       | .700 nitro         |                        | 

**Describe alternatives you've considered**  
This is quite the array of bullet molds. Perhaps I could condense it down (merge all of .309 and .311, .220 and .224, .313 and .323, etc.

Or, we could go in the other direction, and not pretend that each mold is a 'multi-mold'. So you'd need a .355 HP mold to make JHP/HP rounds, a 'ball' mold to make balls for cap and ball, a 'wadcutter' mold to make .460 semi wadcutters, etc.

Or, we could just have a couple of mold sets.  

- 3-gun casting molds- .355, .224, and maybe .309 and .455
- Cowboy action shooter's casting molds- .576, .700, .355, .455, .453
- Cruffler's casting molds- .309, .311, .455, .323, .700, .313
- Russophile's casting molds- .311, .365, .220, .355, .313
- Shotgunner casting molds- .700, .576, .410
- Extended casting molds - everything

**Comment by ymber** [comment]
My preferred option would be to have a large number of very specific molds so we can have properly realistic crafting recipes. Most places they'd spawn are likely to have a variety of molds so there shouldn't be a problem with some molds being unreasonably hard to find. Could do mold sets like the toolbox where you have an item that's essentially a collection of other items.

**Comment by ymber** [comment]
All relevant details including geometry.

**Comment by tenmillimaster** [comment]
OK, here's where I think we're going to go with this. Thanks @kevingranade for the idea.

Player-made molds will have batch-time delays (fewer cavities) and commercial ones will be better optimized for batch reloading.
