### ISSUE TITLE
Recipes binder

### ISSUE THREAD

**Issue by akozhevn** [CleverRaven/Cataclysm-DDA#33601]
**Is your feature request related to a problem? Please describe.**  
It's kind of annoying to carry 20 books around just to keep all the recepies, and even if one book is fully contained in another nobody got time to check over 30 recipes to see if it's true.

**Describe the solution you'd like**  
A way to copy recipes from a book into a common storage. 
I was thinking to have sort of a binder system - if you have a pen (permanent marker?) and enough paper, you can copy recipes from a book and binder would grow in size. It would take maybe (1 min)*(recipe lvl) and 5*(recipe lvl) from marker charges. (just for fun these numbers could be based on item description length =) )

**Describe alternatives you've considered**  
Another interesting solution would be to just have like a memorize action, maybe it takes all the same resources as above, but doesn't add to any binder, just marks recipe as memorized.

**Additional context**  
Also adds some uses for pen and papers, which are almost useless as of now.

**Comment by BX442** [comment]
I also dream that the necessary / all recipes could be recorded for example on sd-card using a tablet or laptop.

**Comment by alkemann** [comment]
Certainly makes you think that the [Encyclopedia Britannica DVD](https://www.amazon.co.uk/Focus-Multimedia-Ltd-1615355211-Encyclopedia/dp/1615355219) (or similar CD) could be the most valuable loot in all of New England. I would be lost without the internet to google for. A disk version of encyclopedia would be OP!

**Comment by snipercup** [comment]
Good idea but if we are talking about complex recipes, i suppose you would be able to copy it given enough time, but it takes a long time to copy electronics recipes with their complex diagrams.

**Comment by vlad1492** [comment]
There was a mod for imaging books to an e-ink tablet... 
https://www.reddit.com/r/cataclysmdda/comments/9bx2zq/two_very_interesting_mods_from_japan_translated/
