### ISSUE TITLE
Set a time to the farm task 

### ISSUE THREAD

**Issue by howmokas** [CleverRaven/Cataclysm-DDA#33614]
We can do the farm task any time ,but the farmer is likely dead in the cataclysm.So i have an opinion to set a time for the farm test. if we miss the time ,the shelter‘s npc will not 
trust us.

**Comment by ZhilkinSerg** [comment]
Are you saying we need a time limit for missions?

**Comment by howmokas** [comment]
right

**Comment by ZhilkinSerg** [comment]
It is fairly easy to implement using `deadline_low` and `deadline_high` properties, though I am not sure how it would work balance wise.

See example below:

https://github.com/CleverRaven/Cataclysm-DDA/blob/4b7a996c8ccb9bd538d069241f90f8036e3340cd/data/json/npcs/missiondef.json#L82-L117

**Comment by howmokas** [comment]
Good，but I don't understand

**Comment by ZhilkinSerg** [comment]
Try reading following guide if you want to implement this, but don't know how:

https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-modders:-New-Missions

**Comment by howmokas** [comment]
OK

**Comment by howmokas** [comment]
It seems is easy to set up a time for missions.But what are the consequences of failure？If it is the robber took the farm.How can I ensure the robber to occupy the original farm.Rather than other.And i need complete
the mission than i can complete the next. It is a mission link

**Comment by SunshineDistillery** [comment]
Look at the example above.  The effects listed under 'end' are for success, and under 'failure' are for failing.  So, under failure add a mapgen_update that adds hostile npcs to the farm.  (to do this you can't use a random location when assigning a target, you'd have to pick the closest farm, so it picks the same spot twice in a row)

I believe, if you fail one mission, you fail the whole chain.  Quest chains don't really fork.  I don't know if there's a way around that.  But you could have a variable added to the player for failure, and then have that variable unlock a _different_ mission chain offered by a _different_ quest-giver NPC.
