### ISSUE TITLE
different minig byproduct

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#33618]
# Describe the bug
When mining from "%"-action menu (directly beneath) there are some byproducts like rocks, clay and so on.
But when digging pit from "*"-building menu no byproducts appear

# Expected behavior

There should be byproducts when "*" digging pit.

# Versions and configuration

0.D-7024-ga16c90f

**Comment by howmokas** [comment]
Such as washing clothes with dirty water

**Comment by RedShakespeare** [comment]
Well, that's pretty strange because you can directly activate your shovel to dig and get byproducts like dirt and stones. Maybe someone should just delete the digging option from the "*" list just like the 
old option to cut down a tree.

**Comment by RedShakespeare** [comment]
Sorry...just reminded that this problem has already been solved in #31209.
Updating to the latest version can be a good choice.

**Comment by alkemann** [comment]
closing issue as solved in #31209
