### ISSUE TITLE
Tying down a pet with short rope repairs it

### ISSUE THREAD

**Issue by XygenSS** [CleverRaven/Cataclysm-DDA#33611]
# Describe the bug

When a damaged short rope is used to tie down a pet like a dog, it is repaired completely when removed.

# Steps To Reproduce

1. Tame a dog using dog food
2. Obtain damaged short ropes, e.g. from vehicle seatbelts
3. With damaged ropes in inventory, approach the dog and tie it down
4. Untie the dog and see that the rope is now repaired

[Optional save with complete test environment](https://github.com/CleverRaven/Cataclysm-DDA/files/3549766/Vanillaville.zip)

# Expected behavior

The returned rope is still damaged and must be repaired.
OR, damaged ropes cannot be used to tie down pets in the first place.

# Versions and configuration

<img width="698" alt="Screen Shot 2019-08-28 at 4 38 55 PM" src="https://user-images.githubusercontent.com/27952407/63835987-981ee000-c9b3-11e9-9d99-36a72e3a318a.png">

 - Game Version: 0.D - Stable
 - Graphics version: Tiles
 - Mods loaded: None (dda)

**Comment by AMurkin** [comment]
Fixed in the experimental by the #32068.
