### ISSUE TITLE
Tear gas can be deadly even in small doses

### ISSUE THREAD

**Issue by daydreamer0000** [CleverRaven/Cataclysm-DDA#33636]
# Describe the bug

A standard character with no mouth protection will cough their lungs out and die after being in tear gas for more than one or two turns.

# Steps To Reproduce

1. Make a player with an unencumbered face, summon tear gas somehow, stand in it for 3 turns then retreat.
2. From the wait menu select wait to catch your breath
3. It is highly likely you will not catch your breath, and instead die from a coughing fit.

# Expected behavior

I would expect coughing fits from tear gas to be very painful, but cause minimal damage, if any, similar to how electric shocks work. It instead does the opposite, breaking your ribs with mild pain.
 
The tooltip for tear gas grenades state they will deal damage to those entering the cloud. Though a cursory google search shows tear gas is nonlethal, only being possibly deadly to those with asthma. I guess it's unclear what you should expect to happen. You wouldn't expect to die with so little exposure though, even if it is intended to deal damage.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-7053-gdfe287e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Survivor Armor [no_survivor_armor],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

* This might just be a stamina/winded issue.

**Comment by Svankensen** [comment]
Just for context. Been exposed to tear gas plenty of times (was a member of student council during the 2011 education protests in chile): Very short exposure is quite incapacitating, basically blinding you for minutes and causing lots of pain, except for short momments where you blink to find your way (5-10 for the blinding to subside, pain lasts about 30-60). Takes around 10 seconds to kick in. Just being closeish (50 meters) to where the clouds billow out has that effect too, but it takes longer for it to affect you.  I've been trapped in tear gas clouds for a minute or two. Totally incapacitating for a long while after exposure, you do feel like you are going to die, absolutely out of breath, face burns, can barely crawl.

**Comment by EirenexTheDragon** [comment]
i think this is an issue that the tear gas isnt adjusted to the turns-to-second change either.

**Comment by Szara-ManOfHonor** [comment]
I've been exposed to tear gas once, and agree with Svankensen's detailed assessment.

**Comment by jeremyshannon** [comment]
Aww man, I fixed this once already! Will try to look into this, hopefully tomorrow.
