### ISSUE TITLE
AIM "move all items" action is broken again

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33633]
# Describe the bug

When multiple items are present at different directions in `a` AIM display, `,` misbehaves.

52d144aa331ab3ed8fd5f2d456b7e1a180cbb284 is the first bad commit

**Comment by Qrox** [comment]
Probably a mishandled merge? It outright reverted the fix I did a month ago...

**Comment by davidpwbrown** [comment]
Probably, my bad. Had to keep solving merge conflicts and rebasing to keep that PR up to date, and there was lots of gnarly conflicts to try and unpick.
