### ISSUE TITLE
Item duplication on pick up to wield

### ISSUE THREAD

**Issue by Highmongrel** [CleverRaven/Cataclysm-DDA#33646]
# Describe the bug

When picking up partial stacks of items it is possible to duplicate them

# Steps To Reproduce

1. Create a stackable item with total volume being much more than you can carry
2. Pick up a portion of the item stack that is exceeds your current max volume
3. Choose to wield item on prompt
4. The full stack is now being weided, but only the portion you took is gone from the original stack

# Expected behavior

Items not to suddenly duplicate

# Screenshots

![image](https://user-images.githubusercontent.com/47551519/63929102-b7def400-ca05-11e9-9a52-bd6710021df6.png)

![image](https://user-images.githubusercontent.com/47551519/63929177-da710d00-ca05-11e9-9499-dd61ec20ef9f.png)

![image](https://user-images.githubusercontent.com/47551519/63929214-e52ba200-ca05-11e9-97a4-89da8c20f578.png)

![image](https://user-images.githubusercontent.com/47551519/63929259-f7a5db80-ca05-11e9-84cc-4f7dd1bf2f9d.png)

# Versions and configuration

- OS: Windows
    - OS Version: Windows 7
- Game Version: 0.D-7076-g10d28ac [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Accidently found the bug while trying to move charcoal into my smoking rack, though I tested it with other items such as tin powder and sausages in my test world.

**Comment by SunshineDistillery** [comment]
Yeah, I've seen this bug.

**Comment by starytroll** [comment]
Same problem here (0.D-7085-g6831dd6), just wanted to add new issue but found this one.
