### ISSUE TITLE
Add intensity levels for effects to NPC Dialog

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#33642]
**Is your feature request related to a problem? Please describe.**  
Currently you can add or remove an effect with NPC dialog, but can't set or change the intensity level of the effect.

**Describe the solution you'd like**  
Either a new way to increase or reduce an intensity level, or have u_add_effect add one intensity level, the way it works for comestibles.  Drink four times to get level four drunk.  

There would also need to be a way to reference the intensity level as well, for dialog conditions. 

**Additional context**  
Being able to add different levels of diseases or injuries might be useful on its own, but it's really for having a counter.  For example, I could add an effect for faction missions, and at the end of each mission add or increase the intensity level by one.  Once the effect level reached a certain point, like ten missions, it would allow for a new set of dialog options.  If it were a player effect, it would then work even if you met new people in that faction.

You could kind of do this with variables now, but it would take a lot of work.

**Comment by ralreegorganon** [comment]
While I do think there's probably value in allowing specifying intensity for the effects and providing a condition for checking them, this is the second request I've seen that really just wanted a counter, and I think that's better handled with variables. There's some complexity and implicit relationships with effects between their duration and intensity that aren't worth tackling just for a counter.

I've got a PR I'm putting together right now which will provide effects for adjusting the value of a variable (incrementing and decrementing by a user defined value) and a condition to do comparisons of the stored value with a user provided value. If that lands, we can revisit the effect intensity issue (which I *do* think is worth tackling) solely on its own merits.

**Comment by SunshineDistillery** [comment]
Great.  
My only question would be if variables will be given a duration.  Really that seems to be the main reason to use effects, for various cooldowns and wait periods.

**Comment by ralreegorganon** [comment]
No, I don't think variables will be given a duration. Internally the variables are just a real simple key/value store for strings on a creature, and I don't see adding more infrastructure to that.

Like I had mentioned, I do think there's value in your original issue here of exposing more effect functionality to the talk/mission effect system (and I don't think you needed to close it) .

I just also already had the variable adjustment stuff in the works and that should help address the use case of having a counter that you can increment/decrement and check.
