### ISSUE TITLE
There is not enough clean water left to siphon it?

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#33648]
# Describe the bug

Trying to use the option "Fill a container with water" from the vehicle kitchen menu results in the message "There is not enough clean water left to siphon it", although there is clean water in the vehicle, and the option "have a drink" works.

# Steps To Reproduce

1. Construct a vehicle with a RV kitchen unit
2. Fill a vehicle tank with clean water
3. Examine the kitchen unit and try to use the option "Fill a container with water"

# Expected behavior

I would expect to able to fill a bottle with clean water if there is any clean water left.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-7053-gdfe287e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, +attitude [sees_player],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

I only have a few liters of clean water inside the vehicle tank, but a lot of big water storage around - maybe that is connected to this somehow.

**Comment by EddiTheBambi** [comment]
Possibly related to changes from #32763? Perhaps check with other liquids and possibly with liquids of a different phase?

**Comment by BaumgeistOne** [comment]
I can't - the option "Fill a container with water" in the RV kitchen examine menu explicitly targets "clean water", nothing I can do about it.

The bug is still there, just checked with a build from yesterday.
