### ISSUE TITLE
crash when using mapgen_update as the generator for map extras

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#33640]
# Describe the bug

I was trying to use the new functions of #31682 by adding map extras wholly by editing the jsons.  It works, but there were occasional crashes when first generating and loading a world.  I figured out it was only happening when the player first spawned in the shelter and the extras appeared somewhere in his reality bubble. 

# Steps To Reproduce

1. Add mapgen extras.
2. Start new game.
3. crash

# Expected behavior
No crashes. 

# Versions and configuration
 - OS: Windows
 - Game Version: 9544
 - Graphics version: Tiles
 - Mods loaded: vanilla + experiment

# Additional context
I don't have a save, because it crashes on inital load.  I'm uploading the mod I was experimenting with, but I have edited it so road extras spawn with a chance of 2, so 50% of all roads will have an extra, and set the weight for an offending extra super high.  This basically guarantees that it will crash if you spawn in a shelter or other spot next to a road.  
[Extra_Bandits.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3553891/Extra_Bandits.zip)

**Comment by ZhilkinSerg** [comment]
Confirmed. Game tries to build cache of non-existing submap. Probably something is wrong with coordinates.

![image](https://user-images.githubusercontent.com/16213433/63918188-e0d2a980-ca44-11e9-97ec-2f97f0ab91d4.png)

![image](https://user-images.githubusercontent.com/16213433/63918344-327b3400-ca45-11e9-8e47-22e90f839da8.png)
