### ISSUE TITLE
Mixed gunpowder recipe is unreasonable 

### ISSUE THREAD

**Issue by gearforcer** [CleverRaven/Cataclysm-DDA#33656]
# Describe the bug
The mixed gunpowder recipe needs adjustment. Take crafting 1 reloaded .300 win mag as an example, 1 smokeless rifle powder can craft 454 mixed gunpowder(seriously?) and 16 mixed gunpowder can craft 1 bullet, but 16 smokeless rifle powder should only produce 1 bullet? I bet no one wants to use 16 smokeless rifle powder as raw material for making 1 reloaded bullet.

# Steps To Reproduce

1. Get 1 smokeless rifle powder and tools to craft  mixed gunpowder and produce 454 of it.
2. Use 454 mixed gunpowder to craft 1 reloaded .300 win mag, find only 16 of it needed.
but also find 16 smokeless rifle powder could only produce 1 bullet.

# Expected behavior
Mixed gunpowder should have more complex composition, at least not only 1 smokeless rifle powder. Or any other reasonable way.

# Screenshots
![20190830002243](https://user-images.githubusercontent.com/42244110/63964635-1ff70e00-caca-11e9-95e8-559386d819f9.png)
![20190830004740](https://user-images.githubusercontent.com/42244110/63964671-2c7b6680-caca-11e9-9922-0e42da98f1d4.png)

# Versions and configuration

 - OS: Windows 10 
 - Game Version: 0.D-7024-ga16c90f
 - Graphics version: Tiles

**Comment by ymber** [comment]
There's an open project that will fix this. See #33466.

**Comment by tenmillimaster** [comment]
This looks like a bug, let me check it out. It's supposed to be a 1:1 conversion currently.

**Comment by tenmillimaster** [comment]
Should all be fixed.
