### ISSUE TITLE
NPC uses installed CBM as a bashing weapon

### ISSUE THREAD

**Issue by crazykiddeath** [CleverRaven/Cataclysm-DDA#33650]
After installing a chain lightning CBM into a NPC, the NPC processed to use it as a melee weapon and would cause a crash when spoken to.

1) Install chain lightning into a NPC
2) Allow NPC to attack an enemy
3) Talk to them to produce a crash

Expected behavior:

NPC not to use installed CBMs as melee weapons (unless it's an actual bionic weapon and uses it as intended) 

Screenshots:

![bugged npc](https://user-images.githubusercontent.com/47288183/63939123-66af1e80-ca5e-11e9-8c6d-ea5ad0641f48.PNG)

 Versions and configuration:
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-6692-gcf4ce7d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Armor Up! PA Utilities [ArmUpPAUtil],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Zetsukaze's Hair Extensions! [zets_hair_extensions],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    [DP_MOD] No Highlight [DP_No_Highlight],
    Stats Through Kills [stats_through_kills]
]
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3555468/debug.zip)
[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3555463/crash.zip)
I've tried uploading a copy of my save but it said it's too big, if you need one just let me know somewhere I can dump a 86mb zip file and i'll upload it there.

The version above and in the crash/debug log is the version I first got this bug but after updating to the latest build (Game Version: 0.D-7080-g95e823e [64-bit]) the bug is still present and still acts the same. Removing the chain lightning CBM fixes the issue and the NPC goes back to acting as expected.

**Comment by madamimadam** [comment]
It's a ... vivid mental image.

**Comment by ZhilkinSerg** [comment]
Savegame would help. Please use dropbox, zippyshare or something.
