### ISSUE TITLE
Start the Cataclysm NOW

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#33655]
Ok, this idea is more than unnessary, since every user can do it by themselves, but, maybe someone has the muse to actually put it in.

What if there is an option to start the cataclysm at the exact moment. As in, it takes the Date from your system, same with the time and puts it in the "starttime". Of course you need to consider that the 1st day of spring is not the 1st of January, morelike the 21th of March. (maybe we need some Calendar function someday for those who use default 91 days per season)

I know it is rather specific, and I won't be too surprised to be hammered down for it. But hey, why not try? Ey?

**Comment by ZhilkinSerg** [comment]
In game calendar is different from real life calendar.

**Comment by Lamandus** [comment]
> 
> 
> In game calendar is different from real life calendar.

that is what I said, yes. 1st of January would be still in Winter somewhere.

**Comment by ZhilkinSerg** [comment]
What in game impact do you expect from that?

**Comment by Lamandus** [comment]
none, it is just fluff. But we added fluff before, no? It was just a "idea for people with too much spare time"

**Comment by ZhilkinSerg** [comment]
How is it different from your mental image of "cataclysm started today"? What do you expect to see in game (user interface, books, text snippets, etc) reflecting this date?

**Comment by Lamandus** [comment]
aaah, sorry, now I get you. The year stays the same. It is just the starting time that changes. Day of year and time. All else would stay the same. Sorry, thought it would be a nice little addition for those, who want to experience it. as a gag.
