### ISSUE TITLE
MP7 is ridiculously large

### ISSUE THREAD

**Issue by asdfzxc920** [CleverRaven/Cataclysm-DDA#33664]
# Describe the bug

The MP7 currently takes up a whopping 3587ml, making it bulkier than even an M240.

# Steps To Reproduce

1. Wish for an MP7.
2. Wish for any of the other machine pistols (MAC-10, Uzi, Calico).
3. Note the huge size difference.

# Expected behavior

The MP7 in real life falls somewhere between a MAC-10 (750ml) and Uzi (1250ml) in size, so I'd expect a volume in that range. A bit of googling shows that it can be easily carried in a normal-sized thigh holster, which has an in-game size limit of 1250ml.

# Versions and configuration

 - OS: Windows 7
 - Game Version: nightly r9554 (2019-08-27)
 - Graphics version: any
 - Mods loaded: dda

# Additional context

n/a

**Comment by tenmillimaster** [comment]
Fixed in #33617.

Any new discrepancies you might see should be because the same volume recalculations haven't been applied to the other firearms.
