### ISSUE TITLE
Tear in reality spawning ground outside of research facility on upper floors.

### ISSUE THREAD

**Issue by tiger8255** [CleverRaven/Cataclysm-DDA#33669]
# Describe the bug

Tear in reality spawned outside of the third floor of a research facility, spawning dirt beneath it.

# Steps To Reproduce

Unsure how exactly you could reproduce it, but save is included here:
[Wolflake.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3558311/Wolflake.zip)
Facility in question is at 0'130, -1'70

# Expected behavior

Either the tear in reality wouldn't spawn dirt tiles in open air, or the tear wouldn't spawn there at all.

# Screenshots

![cataclysm-tiles_2019-08-29_23-19-03](https://user-images.githubusercontent.com/45727688/63993782-bcfc7b80-cab7-11e9-95f3-533d06b61af5.png)

# Versions and configuration

 - OS: Windows 10.0.17134
 - Game Version: 0.D-7073-g4b22a02
 - Graphics version: Tiles
 - Mods loaded: dda, no_npc_food, magiclysm, crt_expansion, makeshift, More_Survival_Tools, hydroponics, national_guard_camp, blazemod, Tanks, more_classes_scenarios, speedydex, stats_through_kills, StatsThroughSkills

**Comment by Night-Pryanik** [comment]
This should have been fixed by #33645?

**Comment by BevapDin** [comment]
Fixed by #33645.
