### ISSUE TITLE
Crude welding mask turns in to normal welding mask when you raise it and then lower it. 

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#33674]
also crude welding mask not lower your vision when lowered, not sure if this bug or not, but normal welding mask limits vision completely

**Comment by SomeDeadGuy** [comment]
Oh no! Raised crude welding mask limits your vision! Someone mixed up THAT ORDER! :joy:

**Comment by SomeDeadGuy** [comment]
Um, this problem was not fixed as of build 9566.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Um, this problem was not fixed as of build 9566.

Who says it should've been?

**Comment by SomeDeadGuy** [comment]
Build 9567 just released. Masks raise normally, but crude welding mask to not hinder vision at all. Weird.

Nobody says nothing. PR were merged several hours ago, so latest experiment build should include it, I was guessing.

**Comment by ZhilkinSerg** [comment]
> 
> Nobody says nothing. PR were merged several hours ago, so latest experiment build should include it, I was guessing.

You can check [build changelog](https://ci.narc.ro/job/Cataclysm-Matrix/9566/) to see what is included to it.

**Comment by SomeDeadGuy** [comment]
Ah, I see.

**Comment by SomeDeadGuy** [comment]
Ah, I see.

**Comment by Rail-Runner** [comment]
> crude welding mask to not hinder vision at all

That's intended (or the welding goggles need to hinder vision too). Crude welding mask is made from welding goggles, which don't hinder vision either.
