### ISSUE TITLE
Publish CDDA on flathub

### ISSUE THREAD

**Issue by rohanlean** [CleverRaven/Cataclysm-DDA#33682]
**Is your feature request related to a problem? Please describe.** 

Flathub is a popular repository for flatpaks -- application bundles that are portable across many different linux distributions. It would be convenient for users if CDDA were published there.

**Describe the solution you'd like**

A maintainer on the release team should make a submission to flathub (https://github.com/flathub/flathub/wiki/App-Submission) and update it whenever a release is made.

**Describe alternatives you've considered**  

A person not as closely affiliated with the project could make the submission.  This is a worse solution, because it compromises the (perceived) authenticity of the app, and releases are not guaranteed to propagate in a timely manner.  Flathub also prefers for the maintainers to be in charge of submissions.

**Additional context**  

#33658 has updated the manifest `org.cataclysmdda.CataclysmDDA.json` so that it can essentially be submitted on its own and as-is. Flathub guidelines (https://github.com/flathub/flathub/wiki/App-Requirements) suggest not just a tag but also a commit to be specified, but this seems not to be a requirement, and it would be a trivial fix that can be applied on submission.

A more serious obstacle is that the Appstream data `data/xdg/cataclysm-dda.appdata.xml` are missing:
- release information,
- screenshots,
- a content rating.

This needs to be fixed, and the fixed Appstream data referenced by a submission of any release that predates the fix.  For example it could be included in the submission, together with a slightly adapted manifest.

I feel that I am not in the best position to select screenshots and a content rating, but I have given the content rating a try:

>  <content_rating type="oars-1.1">
    <content_attribute id="violence-fantasy">intense</content_attribute>
    <content_attribute id="violence-desecration">intense</content_attribute>
    <content_attribute id="violence-worship">intense</content_attribute>
    <content_attribute id="drugs-alcohol">moderate</content_attribute>
    <content_attribute id="drugs-narcotics">moderate</content_attribute>
    <content_attribute id="drugs-tobacco">moderate</content_attribute>
    <content_attribute id="sex-themes">moderate</content_attribute>
    <content_attribute id="sex-appearance">moderate</content_attribute>
    <content_attribute id="language-profanity">intense</content_attribute>
    <content_attribute id="language-humor">mild</content_attribute>
  </content_rating>

You can generate your own at https://hughsie.github.io/oars/index.html.

The guidelines for screenshots are found in here: https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html.  I suggest involving the larger community in selecting screenshots.

**Comment by rohanlean** [comment]
This ended up sounding less actionable than I had anticipated -- I went through the requirements only as I was writing this issue -- and perhaps that explains the lack of engagement?

I could open another issue for the selection of promotional screenshots and submit a [CR] PR for the content rating. Once those two are taken care of I can give short and explicit instructions on how to perform the submission (and keep it up to date).  Would that help?

**Comment by kevingranade** [comment]
I'm 100% ok to do the actual submission, but setting up the actual metadata and such would be so far down on my list of priorities that you can pretty much count on it never happening if you leave it to me.

**Comment by hexagonrecursion** [comment]
Can this be reopened? I want to work on getting cdda into flathub.

**Comment by anothersimulacrum** [comment]
@hexagonrecursion Still interested?

**Comment by skossan** [comment]
I would love to see this on Flathub. Would be awesome if someone would make it happen!

**Comment by barthalion** [comment]
The manifest itself looks good, but the appdata file is going to need some changes, specifically it misses screenshots. @skossan, why don't you follow the steps described at https://github.com/flathub/flathub/wiki/App-Submission? We will figure out who from Cataclysm team would like write access to the Flathub repo as part of the review.

**Comment by a-chancey** [comment]
I'm going to look into this a bit, maybe early next week. trying to read up on flatpak, as i just got my steam deck heh

**Comment by a-chancey** [comment]
Ok, reporting back now that i had a bit of time to mess around with it. I had to update the manifest to match the version of FreeDesktop I have installed, but the build works, installs and launches properly.
I'll review the app submission steps for FlatHub and figure out what's missing (other than the aforementioned screenshots), then get things set up for submission.
One caveat - FlatHub only allows stable builds, so I don't know if we'll be able to host the flatpak experimental builds here or how we'd handle them.

**Comment by barthalion** [comment]
My understanding is that nightly builds of CDDA is what many people use. I don't think such submission would be rejected, as long as there's some biweekly or weekly update schedule; it would make sense to me submit it separately so users can install both versions at the same time.

**Comment by Aman9das** [comment]
> One caveat - FlatHub only allows stable builds, so I don't know if we'll be able to host the flatpak experimental builds here or how we'd handle them.

There is the beta branch of flathub too. As described here: https://github.com/flathub/flathub/wiki/App-Maintenance

**Comment by a-chancey** [comment]
> > One caveat - FlatHub only allows stable builds, so I don't know if we'll be able to host the flatpak experimental builds here or how we'd handle them.
> 
> 
> 
> There is the beta branch of flathub too. As described here: https://github.com/flathub/flathub/wiki/App-Maintenance

Yeah, though over [here,](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) they explicitly state that it's for semi-stable beta builds and not nightly, and our experimental branch is/can be more frequent than nightly. 

[here's a slightly more recent discussion re:nightly/development snapshot builds that largely reflects the same policy.](https://github.com/flathub/flathub/issues/2975#issuecomment-1087266934)

When I've got a little more time, I may look into updating the build action for flatpak to list the stable, just haven't gotten to it yet

**Comment by barthalion** [comment]
It's true, but we're flexible when it makes sense. Projects like Citra, Yuzu and Ryujinx are updated almost daily with our blessing.

**Comment by RustoMCSpit** [comment]
any update?

**Comment by grisha765** [comment]
Hello, could you add png screenshots from this repository https://github.com/grisha765/flathub/tree/org.Cataclysm.DDA.Tiles to the project repository so that it can be accepted into flatpak? Also, probably, you need to add a desktop file and xml metainfo. 
Here is the request: https://github.com/flathub/flathub/pull/5488#pullrequestreview-2226574885

**Comment by RustoMCSpit** [comment]
should this be closed now
