### ISSUE TITLE
Separate melee stamina from running stamina

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#33689]
**Is your feature request related to a problem? Please describe.**  

Melee'ing causes your character to not be able to run anymore. Anyone who has been in a fight and losing knows that even if your arms are tired you can still run away.

**Describe the solution you'd like**  

Separate melee stamina from running. Make each have their own stamina. As a graphic you can keep the same size bar on the UI just have two different colors representing each.

**Describe alternatives you've considered**  

Never engage in melee combat.

**Additional context**  

Arms get sore before you run out of breath. Most the boxing / MMA matches you see and they are all tired and moving slower, it's cause they get sore, not cause they run out of breath.

**Comment by kevingranade** [comment]
Invalid expected results.

```even if your arms are tired you can still run away.``` is a vacuous statement, in-game stamina has nothing to do with your arms getting tired, but cardiovascular exhaustion.

**Comment by davidpwbrown** [comment]
> Arms get sore before you run out of breath. Most the boxing / MMA matches you see and they are all tired and moving slower, it's cause they get sore, not cause they run out of breath.

Are you serious?
