### ISSUE TITLE
Melee / Dodge skill should lower stamina costs for fighting

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#33687]
**Is your feature request related to a problem? Please describe.**  

Stamina use in fighting is unrealistic. You should still be able to run after swinging a sword around. Right now you fight a bit, lose all your stamina, and are deadmeat.

**Describe the solution you'd like**  

A simple change would be to make skills affect stamina costs for actions associated with them. The simplest one that comes to mind is melee and dodge when it comes to melee combat. Someone who fights a lot will have more trained arm muscles which should lower the stamina cost of swinging a bat / sword.

Also Stamina regeneration should just be buffed in general (unlike how it was nerfed in past patches) maybe by a combination of skills.

**Describe alternatives you've considered**  

Never fight in melee against more than 3 enemies.

**Additional context**  

https://www.youtube.com/watch?v=wqNjAFiH4CM

Here is a guy swinging around a very large sword and moving around with it in his arms. Notice how he is not out of breath while doing it? I bet only his arms are sore after this.

If you guys ask nicely I will make and post a video of me swinging a katana 200 times and then run in a circle for 5 minutes and not be out of breath after either of these events being done in succession.

**Comment by Quintovir** [comment]
I think an MMA fight would be a better example to gauge stamina use.

**Comment by davidpwbrown** [comment]
> If you guys ask nicely I will make and post a video of me swinging a katana 200 times and then run in a circle for 5 minutes and not be out of breath after either of these events being done in succession.

Please do this.

**Comment by mlangsdorf** [comment]
There's a huge difference between doing a practice drill, at what is probably one-third or one-quarter normal speed, and fighting.  Find a youtube video of someone doing HEMA fighting in full gear for 5 minutes and that's beginning to be relevant.

**Comment by kevingranade** [comment]
Again, bad premise, please stop posting poorly thought out issues you've been told are invalid.
