### ISSUE TITLE
Android Port doesn't start (Black Screen)

### ISSUE THREAD

**Issue by Rainoutt** [CleverRaven/Cataclysm-DDA#33694]
# Describe the bug
After opening the app on my tablet Samsung Galaxy Tab 3 8.0 on Android 4.4 the app opens and a black screen appears, but nothing else happens.
Im unable to use logcat on the app with adb, like it never opened.
Im using latest release, with a rooted Android

# Steps To Reproduce

1. Install latest release.
2. Open the app on the android launcher
3. Black screen and the app frozes on it.

# Expected behavior
CDDA starts with the menu like on my Android Pie phone.

# Versions and configuration

Android 4.4
Cataclysm-DDA experimental build #9568 (but happenes with many more experimental versions.)

I also tested with the stable app, same thing happens.

# Additional context

If I install a custom OS on my tabled (Android Nougat 7.1) I am able to start the app normally, but the Custom os is to unstable to be used regularly.

**Comment by ZhilkinSerg** [comment]
Unfortunately there were numerous reports that app is behaving poorly on older Android 4.x versions.

**Comment by NetSysFire** [comment]
@ZhilkinSerg since this is two years ago and android 4.4 is unsupported now, can this be closed?
