### ISSUE TITLE
Magiclysm mod causing an error from build 9567 to current build (9568 at time of posting)

### ISSUE THREAD

**Issue by Proxiehunter** [CleverRaven/Cataclysm-DDA#33693]
When attempting to create a new character using the magiclysm mod it generates an error and returns to the title screen. First reported [here](https://discourse.cataclysmdda.org/t/cannot-load-character-stops-at-magiclysm/21213/3) including an attempt where magiclysm was the only mod in use. Debug log below.

-----------------------------------------
15:26:20.895 : Starting log.
15:26:20.896 INFO : Cataclysm DDA version 0.D-7123-g0abcd23
15:26:21.051 WARNING : opendir [./sound/] failed with "No such file or directory".
15:26:21.062 INFO : Number of render drivers on your system: 4
15:26:21.062 INFO : Render driver: 0/direct3d
15:26:21.062 INFO : Render driver: 1/direct3d11
15:26:21.062 INFO : Render driver: 2/opengl
15:26:21.062 INFO : Render driver: 3/software
15:26:21.069 INFO : Language is set to: 'en'
15:26:21.715 INFO : SDL version used during compile is 2.0.5
15:26:21.715 INFO : SDL version used during linking and in runtime is 2.0.5
15:26:21.921 INFO : Active renderer: 3/software
15:26:22.192 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
15:26:22.802 WARNING : opendir [./mods/] failed with "No such file or directory".
15:26:43.688 ERROR : (error message will follow backtrace)
	(@0x5c107e[cataclysm-tiles.exe+0x1c107e]), 
	(@0x5c16ba[cataclysm-tiles.exe+0x1c16ba]), 
	(@0x5c4aa6[cataclysm-tiles.exe+0x1c4aa6]), 
	(IMG_LoadWEBP_RW+0x1125f4@0x1178544[cataclysm-tiles.exe+0xd78544]), 
	(@0x8e41e9[cataclysm-tiles.exe+0x4e41e9]), 
	(@0x8e7579[cataclysm-tiles.exe+0x4e7579]), 
	(IMG_LoadWEBP_RW+0x5bb7f5@0x1621745[cataclysm-tiles.exe+0x1221745]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0xd@0x76c3556d[kernel32.dll+0x1556d]), 
	(RtlUserThreadStart+0x1d@0x76d9385d[ntdll.dll+0x5385d]), 
Backtrace emission took 0 seconds.
src/main_menu.cpp:815 [bool main_menu::new_character_tab()] Error: data/mods//Magiclysm/modinfo.json: line 12:3: member not found: display_category

    "dependencies": [ "dda" ]
  },
  {
  ^

    "type": "skill",
    "ident": "spellcraft",

15:27:03.177 : Log shutdown.
-----------------------------------------

**Comment by alkemann** [comment]
We have a PR to fix this: #33690

**Comment by Proxiehunter** [comment]
Glad to hear it. I didn't see any other reports here, just someone mentioning it on the discourse channel, and assumed from the title of the PR it was related to something else.

**Comment by alkemann** [comment]
We can keep the issue open until the PR is merge to avoid duplicates
