### ISSUE TITLE
Drop item window works incansistently in regards of keymapping.

### ISSUE THREAD

**Issue by MindScriptAct** [CleverRaven/Cataclysm-DDA#33695]
# Describe the bug

Drop item action window reacts only to UP/DOWN/LEFT/RIGHT. 
If those are removed, drop window does not react to "Move north"/"Move South" key mappings. (Does not work with Numberpad 8/Numberpad 2.)

# Steps To Reproduce

1 - Remove keymaping for Move North/Move South.
2 - Add global keymaping to Move north - Numpad 8, Move South - Numpad 2.
3 - Try to drop item with 'd'
4- try to navigate item list up/down. (nothing works.)

# Expected behavior

Drop action window should react to global seting move North/Move South. Not only Up/Down.

# Versions and configuration

Default install, Build 9568

**Comment by ZhilkinSerg** [comment]
I am not really sure it is a proper issue. Unless I am missing something, ou are basically expecting some keybindings to work in a different context.
