### ISSUE TITLE
Game doesn't work

### ISSUE THREAD

**Issue by pabrams** [CleverRaven/Cataclysm-DDA#33706]
What did you guys do?  This "Stable" version is worse than any experimental version I've ever tried.  

1.  Download game (0.D)
2.  Extract files
3.  Extract CDDA-Soundpack to data/sound
4.  Run cataclysm
5.  Switch to full screen and restart game
6. Try to set some other options
7.  Keyboard acts really weird, like every time I press a key it registers the previous key I pressed....
8.  I alt-tab and eventually this pops up: 

![image](https://user-images.githubusercontent.com/1376688/64062360-66746780-cbb3-11e9-8a02-01dad8d88844.png)

**Comment by ZhilkinSerg** [comment]
We do not backport any patches to previous stable releases. Test whether you stumble upon same issue on latest experimental version.
