### ISSUE TITLE
Sorting items results in a recursive, unbreakable movement loop.

### ISSUE THREAD

**Issue by CEG86** [CleverRaven/Cataclysm-DDA#33703]
# Describe the bug

Upon sorting all possible items into respective areas, the player moves between two tiles infinitely until the game freezes.

# Steps To Reproduce

1. Get some items and place zones.
2. Sort all

# Expected behavior

Everything to get sorted without the game looping in an effort to sort something that isn't there.

# Screenshots
![image](https://user-images.githubusercontent.com/28743169/64059943-c6f3ac80-cb93-11e9-8845-95a7d0b639f9.png)

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS:Windows 10 
 - Game Version: [0.D-7136-g5c581e4]
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs, Makeshift Items Mod, Stats through kills, statsthroughskills

**Comment by BaumgeistOne** [comment]
Just happened to me too.

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-7136-g5c581e4 [64-bit]

**Comment by CEG86** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/33598
