### ISSUE TITLE
Road barricades (and others) consume moves when examining.

### ISSUE THREAD

**Issue by BevapDin** [CleverRaven/Cataclysm-DDA#33707]
1. When examining a road barricade (or any other terrain with the "CLIMB_SIMPLE" flag), the player character *automatically* vaults over them. There is no way to prevent that action, the game does not even query for it. Note that this *action* is triggered by *examining* the terrain!

In other words: examine == activate (which is not intuitive). Note that road barricades are represented as '#', as are other furniture / terrain types. If it's dark, the player won't be able to distinguish them based on their color (and even that is ambiguous), so they *will* examine it to detect what it actually is.

2. When standing on top of a climbable terrain (chain link fence, road barricade, probably more), you can examine the terrain right below your feet. The game asks you to "Climb \<terrain\>?", even as you are already on top of it. And when saying yes, the character does not move, but move points are consumed anyway. With road barricades it even worse: there is no query, but move points are consumed anyway.

**Comment by Night-Pryanik** [comment]
#22185 is the culprit.
