### ISSUE TITLE
feature request - ex/import player

### ISSUE THREAD

**Issue by FONZACUS** [CleverRaven/Cataclysm-DDA#33716]
**Is your feature request related to a problem? Please describe.**  
i know its been posted before but i cant find the post requesting 'move region', where the map resets itself, simulating the player moving to a new region. is it possible to have an ingame exporter where our character (and hopefully more later on) can be extracted, and imported to the same world (again, more later on)?

**Describe the solution you'd like**  
moving to canada, i hear the zombies there are polite :D

**Describe alternatives you've considered**  
debugging everything in to simulate moving to a new area, including friends (npcs) and family (cars).

**Additional context**  
should help shave a ton of save data, update map contents to newer builds, up/downloading saved games.

**Comment by ZhilkinSerg** [comment]
It is kinda already possible to do using external file manipulations.

**Comment by FONZACUS** [comment]
yep, its still possible to do it when following the [wiki](//cddawiki.chezzo.com/cdda_wiki/index.php?title=Savegame_Editing). i havent updated the game for a long time though (9255), it might not be true for recent versions.

still itd be nice to have an ingame debug menu option to handle these for non technical folks. im pretty sure most of us wouldnt mind it as a low priority wishlist item.

**Comment by baldamundo** [comment]
There's a third-party script floating around somewhere that does this for you automatically, but I have a feeling it could do with an update
