### ISSUE TITLE
Segmentation fault on firing XM34 EMP projector

### ISSUE THREAD

**Issue by harakka** [CleverRaven/Cataclysm-DDA#33719]
# Describe the bug
Game crashes when firing XM34 EMP projector in the included save. From a quick check it didn't reproduce on a clean world and fresh survivor with all default world and character settings, so it's something more particular to the conditions in this save.

# Steps To Reproduce
1. Load provided save (world "Happiness", character "Thelma").
2. Press f twice.

# Expected behavior
Game not crashing.

# Versions and configuration
- OS: Windows 10
    - OS Version: 10.0 1903
- Game Version: 0.D-7168-g20a9323 [64-bit] (build 9572)
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    sees-player icon, -attitude [sees_player_less_attitude],
    Stats Through Kills [stats_through_kills]
]

# Additional context
[xm34-crash2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3562763/xm34-crash2.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3562761/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3562762/debug.log)

**Comment by Mooses2k** [comment]
Functioning as intended.

**Comment by anothersimulacrum** [comment]
Did you comment on the wrong issue? I don't think a segfault is ever intended behavior.

**Comment by Mooses2k** [comment]
He didn't take the time to aim. He EMPed his computer.

**Comment by ZhilkinSerg** [comment]
Successfully reproduced the crash on latest `master`:

![image](https://user-images.githubusercontent.com/16213433/64920585-37b8dc80-d7c2-11e9-89a7-f44ee398b935.png)
