### ISSUE TITLE
Segfault when switching fire modes in a spectre recon mech

### ISSUE THREAD

**Issue by ArcanErasmus** [CleverRaven/Cataclysm-DDA#33725]
# Describe the bug

When opening up the 'fire' menu and attempting to `s`witch firing modes, game segfaults.

# Steps To Reproduce

1. Open the save file.
2. Open the `f`ire menu.
3. Attempt to `s`witch firing modes.

# Expected behavior

Firing mode switches or nothing happens (I don't actually know if it has other weapons).

# Screenshots

![image](https://user-images.githubusercontent.com/8963206/64070915-c282ce80-cc3b-11e9-8e6d-650ed2020e98.png)
Firing screen right before pressing `s` to switch firing modes, which causes crash.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-7185-ge4fd06f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills],
    [DP_MOD] Alternative Floor Tiles [DP_Old_Floor],
    sees-player icon, -attitude [sees_player_less_attitude],
    SpeedyDex [speedydex],
    Prevent Zombie Revivication [no_reviving_zombies],
    Hydroponics [hydroponics],
    Makeshift Items Mod [makeshift],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Manual Bionic Installation [manualbionicinstall],
    CGPersonal [cgpersonal]
]

The "CGPersonal" mod is my personal rebalance mod (I am Closet Goth on discord, hence the initials), and *all* it does is modify the storage capacity of vehicle autoclaves.

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3563019/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3563020/debug.log)
[segfault_recon.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3563021/segfault_recon.zip)

**Comment by davidpwbrown** [comment]
confirmed
