### ISSUE TITLE
[CR] Adding two new clothing layers

### ISSUE THREAD

**Issue by SourSlime** [CleverRaven/Cataclysm-DDA#33729]
**Is your feature request related to a problem? Please describe.**  
I have a plan to expand the clothing layers in the game, by adding two new ones. This will have a side-effect of closing #23459.

I'm making an issue about this first because I would like to get some feedback. It's particularly important in this case, because sorting through all the armor files in the game and then having to redo it is something I want to avoid.

**Describe the solution you'd like**  
Reorganise the three clothing layers (Skintight, Normal and Outer) into five layers of clothing. The old Skintight and Outer layers are split into two layers each, to categorise clothing more effectively.

Layer - Examine Description
Skintight - This clothing lies against the skin
Inner - This clothing is worn beneath regular clothing
Normal - The same as it currently is
Middle - This clothing is worn above regular clothing
Outer - This gear is generally worn over all other clothing

Examples of where certain clothes fit:
Skintight - underwear, swimwear, tights (primarily underwear, which can be worn with almost any clothing)
Inner - singlets, socks, breeches, tank tops (things that are worn close to the skin, but not necessarily skintight, or that are worn over underwear)
Normal - shirts, some hats, shorts/tight pants (everyday clothing, like shirts or shorts that aren’t that bulky)
Middle - hoodies, soft jackets/jumpers, shoe protectors, beanies, thin scarves, loose pants, some hats (bulky normal clothing or clothing that is typically worn over normal clothing)
Outer - raincoats, armor, helmets, most shoes/boots, thick scarves (primarily armour, or clothing that is worn over all other clothing, like raincoats or bulky coats)

Here is a good real-life example of 5-layer clothing, a man in the army:
https://previews.123rf.com/images/shivanetua/shivanetua1201/shivanetua120100004/11890184-soldiers-in-full-gear-patrol-the-area-in-the-desert.jpg
The man in the photo is wearing an armor on the outside, but strapped gear could still fit over the top. He is wearing a middle-layer clothing (army jacket of some kind) underneath, and beneath that there is enough room to comfortably wear a shirt/long-sleeved top, singlet and some kind of skintight top.

A similar example is available for the legs (but without an image). 
Some kind of skintight pants (underwear/swimmers), boxer shorts, soft/slim shorts, a set of bulky/baggy long pants (army pants, baggy tracksuit pants) and a trenchcoat.

**Additional context**  
I don't think that having 5 normal clothing layers is such a bad idea. If it causes too many balance problems, clothing can increase in encumbrance slightly to make up for it. Boxers and briefs would no longer be worn on the same layer, but as a result, the unfitted encumbrance could raise from 0 to 1 or 2.

I'm also taking suggestion for the names of the outer 2 layers.

It could be argued that armor is worn on a sixth layer, above things such as trenchcoats, lab coats or bulky jackets, but I think five layers is enough. I think the best way to implement a sixth layer would be a second strapped layer, for armors that have straps

**Comment by kevingranade** [comment]
In short, no.
You're going to need to make a much stronger argument for why this is a good idea than supplying examples of people wearing clothing that conflicts.

**Comment by EddiTheBambi** [comment]
I'd say that the categories presented in the issue description are sound though more examples and arguments for why it makse sense could be useful. I live in a colder country and would definitely *not* say that wearing the following
* a pair of regular underwear
* thermal underwear
* a pair of regular trousers
* ski pants
* a long warm coat on top

would conflict with eachother. Sure, it's quite encumbering and running is not going to be very effective, but the layers do not in any way contribute significantly to extra encumbrance in combination with eachother.

**Comment by CoroNaut** [comment]
@kevingranade Can you explain what more criteria/examples you are looking for? I feel like this would be a nice addition and allow for many more clothing combinations than before while adding balance. The balance would come from the limit on how many clothes per layer there is currently and give more control to the developers to fine tune the line between overpowered and underpowered clothing sets.

**Comment by esotericist** [comment]
> Can you explain what more criteria/examples you are looking for? 

Kevin didn't ask for "criteria" or "examples", Kevin effectively asked for a *rationale*. You have not yet managed to put forth a convincing argument that this is actually beneficial to the game.

A list of statements about what could be done isn't presenting a case that we need those things, or that they would materially improve things over what we have now.

**Comment by Fris0uman** [comment]
So with this system you could have your socks, your sneakers on top, and then put some shoes protection on them before finally snugly putting your feet in a boot without layer penalty? That doesn't sound right.

**Comment by mlangsdorf** [comment]
@EddiTheBambi do you feel you can run as fast with all that on, or would removing the ski pants or long coat make things simpler?  My memories of living in cold areas suggest the latter.

**Comment by SourSlime** [comment]
Thanks for all the responses.

@mlangsdorf
I don’t think @EddiTheBambi meant that it would be as easy to run with all those clothes on than with less clothes. The encumbrance from all worn clothes would still apply, even if this change goes through. The penalty from wearing clothes that are currently worn on the same layer would be removed, so wearing underwear and thermal underwear at once would not give any bonus encumbrance, but the base encumbrance from both would still apply.

If you meant that moving faster should cause encumbrance penalties to be more severe, I agree, but that’s an issue that is out of scope.

 @Fris0uman
Thanks for pointing that out. If this becomes a PR, I’m hoping that others will give feedback on my layer choices (especially with fictional clothing such as the RM13 combat armor)

From a realism point of view, I believe this is the next step for the current clothing system. It fixes many conflict issues that the current system suffers from (I gave some examples earlier). As @EddiTheBambi pointed out, there is evidence from personal experience that this will be a more realistic system than the current implementation. I could give more examples if they’re required, but here’s a comparison of the current system with real-life clothing choices. An image showing this kind of clothing is linked in my first post.

(All clothing is fitted + reinforced)
Woman’s spring/summer army gear (example):
1x Bra (skintight)
1x Short-sleeved underwear top (inner)
1x T-shirt (normal)
1x Army jacket (middle) 
1x MBR vest (kevlar plates) (outer)
Gives 25 torso encumbrance; 16 comes from item encumbrance while 9 comes from layering penalties.
I think 16 encumbrance sounds right for wearing 5 seperate pieces of clothing, but the extra 9 from layering penalties is too high.

I can also attest to extra encumbrance penalties IRL. I have worn 4 layers of clothing on my chest a few times (singlet, long-sleeved shirt, soft jumper, big coat), and it was quite warm and comfortable. I never felt that those seperate layers added extra encumbrance to my body.

On the other hand, when I have worn 2x pairs of cargo shorts/1x shirt and 1x long sleeved shirt, I have definitely felt more restricted and uncomfortable, which is how I imagine extra encumbrance penalties would feel like.

I mentioned it in my first post, but this will also resolve existing issues such as breeches and boots conflicting with each other.

From a balance point of view, this might not be the best choice, since it lets players wear more armor with less penalty. However, I’ve always thought realism is the most important factor in adding new features to CDDA, and that balancing comes afterwards.
If balancing is a large issue though, 0 encumbrance items can all be increased to 1 or 2 (which would be reduced after refitting).
The layering penalties still exist, so wearing more than one item on a clothing layer still gives penalties.
Since clothing still gives the base encumbrance and warmth, wearing extra layers might not be a good idea at all.

There are gameplay reasons for adding this new feature as well.
It supports roleplay, allowing players to pursue more realistic clothing styles, or to model their everyday clothing.
If underwear remains at it’s current encumbrance of 0, it encourages wearing it (or some other skintight thing) like most people do IRL.
Adding more layers means adding more meaningful choices; more clothing can be worn, but is it worth the encumbrance/warmth?

As @CoroNaut mentioned, this addition will also diversify clothing, giving clothing designers more room to differentiate different types of clothing.

There is a limitation of the current layering system which the proposed PR will not address. That is wearing multiple rigid items, such as two plate armors on top of each other.

I really would like to get this PR merged, so if this isn’t a good enough argument for this addition, please tell me what I’m missing. I don’t see any serious problems with this idea; the way I see it, there’s only benefits to improving the current system this way.

**Comment by kevingranade** [comment]
> there is evidence from personal experience that this will be a more realistic system than the current implementation.

This is not an argument, it's explicitly a fallacy.

> Example drawn from someone in full military gear.

This is a pretty terrible example, these guys are HEAVILY over-encumbered, it's a known and chronic problem, but they don't care because personal encumbrance just isn't that big of a deal in a shooting fight.  The vast majority of that stacking comes from the jacket + chest rig (you didn't add the backpack, even though that would also conflict), and it seems totally reasonable to me that it would be harder to move with those layers that are in fact conflicting with each other.

> "gameplay" benefits
These all boil down to "being more permissive is better", which is not a benefit.  People CAN wear their usual clothes, including underwear, but if those end up being a problem for some reason so be it.  I don't expect people's everyday wear to be representative of post-apocalyptic wear, so I don't see how this is supposed to be beneficial.
On top of that, your examples call out underwear stacking as being a problem, but they contribute totally negligible amounts of encumbrance, so there's an even weaker case for adding this extra inner layer than for the outer layer.

> That is wearing multiple rigid items, such as two plate armors on top of each other.

I don't know why you even bring this up, this seems like an obviously bad idea.

What you're still missing is a compelling argument for why this is necessary, a big part of the problem here is you haven't identified any specific issues where the current system is falling short in a systematic way, so there's a vague problem statement that it's difficult to say anything about one way or the other, then there's a huge logical leap that ends up with your proposed solution.

So you imply one specific and meaningful thing, which is "I think an army jacket and a MBR vest shouldn't conflict", but there we immediately run into a problem, because I DO think they should conflict.

I want to stress again though, even if I 100% agreed with you on jacket x vest, what I'd be telling you is to look for more examples as well as a different solution for addressing them, because adding more layers is a really big hill to climb.  It doesn't help that you're blithely saying things like, "If balancing is a large issue though, 0 encumbrance items can all be increased to 1 or 2 (which would be reduced after refitting).", which implies a pretty huge amount of work to both make the changes and review them.

**Comment by kevingranade** [comment]
Requested rationale was not supplied.
