### ISSUE TITLE
Can't change position with NPC when mounted

### ISSUE THREAD

**Issue by RedShakespeare** [CleverRaven/Cataclysm-DDA#33726]
# Describe the bug

You can't change position with any NPC when on an animal or on a mechbot.

# Steps To Reproduce

1. Make a player with an allied NPC and a tamed/authorized mountable creature like a horse or a mechbot.
2. Ride/climb on the creature.
3. Try to change position with the NPC.
4. Debugmsg breaks out.

# Expected behavior

You can change position with the NPC no matter mounted or not.

# Screenshots

![image](https://user-images.githubusercontent.com/44523519/64071114-50df6a80-cca5-11e9-9ba9-6a5c6d55c871.png)
↑try to swap when on a horse
![image](https://user-images.githubusercontent.com/44523519/64071119-72d8ed00-cca5-11e9-8e24-8ff7fd15a97a.png)
↑try to swap when on a mechbot 

# Versions and configuration

 - Game Version: [0.d-7185-ge4fd06f or 0.d-9573]

**Comment by RedShakespeare** [comment]
Actually it seems that trials to swap with any ally will cause this problem.

**Comment by davidpwbrown** [comment]
This will be fixed by #33550 as that PR required me to change the swapping positions code anywy to disallow it when either a) player is riding, or b) NPC is riding - precisely because of these kinds of problems.
