### ISSUE TITLE
extra light quarterpanel is more durable than quarterpanel

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33732]
# Describe the bug

96@1.2kg vs 95@6kg
0.D-7185-ge4fd06fd24-dirty

**Comment by l29ah** [comment]
It isn't fixed. Extra-light quarterpanels are still stronger and lighter than the proper steel ones. Also, #35228 doesn't even do what it tells us it does: wooden quarterpanels are still less durable than extra-light ones.

**Comment by arijust** [comment]
>It isn't fixed.

Yes, it is. Look at boards.json from line 105 to line 128.
Wooden quarterpanels durability is proportional to wooden plates durability.
110 * 0.8 + 16 = 104
Sorry for not explaining it right, before.

**Comment by l29ah** [comment]
I don't understand what do those JSON lines mean, but i observe that in game a `quarterpanel` has `Durability: 95`, `extra light quarterpanel` has 96, and `wooden quarterpanel` has 87 at ae829afdcdea9d4d7eecebff0, while your PR title suggests otherwise.

**Comment by arijust** [comment]
I see.
I need to tweak numbers again.

**Comment by l29ah** [comment]
I find it worrying that a quarterpanel now is 24% more durable than an extra-light one while being 400% heavier, but okay.

**Comment by l29ah** [comment]
Reopen plz, the bug is back at 0.E-62-g1f7e4acc1b

**Comment by l29ah** [comment]
The pull request is effectively reverted in c1f35fec56652167770f9b7d700cab0189d655fd
@Karthas077 why did you do that?

**Comment by l29ah** [comment]
[mandatory lecture about why you should only make atomic commits]

**Comment by Karthas077** [comment]
In my defense, if you check the commit log on my PR you can see I had finished my changes and merged from master 4 days before that other branch was even open. If a conflict was introduced before it was merged I was not the one who resolved it.
