### ISSUE TITLE
Looting a dynamic NPC turns all dynamic NPCs hostile 

### ISSUE THREAD

**Issue by EmilPetecki** [CleverRaven/Cataclysm-DDA#33731]
# Describe the bug

Taking items from dead dynamic NPCs causes all dynamic NPCs to become hostile, calling player a 'bandit' and shooting without warning. 

As a second bug, if you kill a dynamic NPC and another, non-related dynamic NPC notices you, he will treat you like a thief. 

# Steps To Reproduce

1. Spawn an NPC.
2. Kill him.
3. Loot his body - see the message about stealing
4. Try to spawn other NPCs.

EDIT: I tried to use the debug menu to change the opinion of an NPC I just spawned. He would talk to me, but "get angry" immediately afterwards.

# Expected behavior

You will get a message about stealing and later on all dynamic NPCs will turn hostile.

Master.gsav lists my relationship with scavengers as "factions": [ { "id": "wasteland_scavengers", "likes_u": -46, "respects_u": -46, "known_by_u": true, "size": 100, "power": 104, "food_supply": 172800, "wealth": 2500000, "opinion_of": 

Changing values to positive makes dynamic NPCs work as usual. 

# Versions and configuration

Cataclysm-DDA experimental build #9573

 SAVE: https://www.filedropper.com/showdownload.php/hiltonia

**Comment by davidpwbrown** [comment]
Thats odd, that should only happen if other witnesses of that faction are present.

And tbh the idea that all dynamic NPCs belong to the same faction is a bit silly, I can look into this today, as im looking at another thievery related bug anyway.

**Comment by davidpwbrown** [comment]
Yeah this is because of that other dynamic NPC witness present in your save, which somehow telepathically informs all other members of "wasteland scavengers" faction that you are a thief, and all dynamic NPCs are members of that faction, until we disengage dynamic NPC spawning from that faction ill just disallow wasteland scavengers from the witnessing code.

**Comment by davidpwbrown** [comment]
This is actually part of a wider problem with dynamic NPCs, I suspect if you kill one, all further dynamic NPCs will be hostile, as per #32475

**Comment by EmilPetecki** [comment]
It’s a big problem since apparently killing and/or looting dynamic NPCs who attack you or try to rob you triggers it.
