### ISSUE TITLE
Zipper bags should be (r)eloadable.

### ISSUE THREAD

**Issue by Proxiehunter** [CleverRaven/Cataclysm-DDA#33749]
**Is your feature request related to a problem? Please describe.**  

Currently you can (U)nload a zipper bag of cocaine, heroin, etc. but you can not (r)eload it and are instead left with an empty zipper bag that you are unable to do anything with.

**Describe the solution you'd like**  

Zipper bags are (r)eloadable just like bottles or gallon jugs which is only logical. In real life unless a zipper bag is torn there's no reason you can't transfer contents from one to another or put things into an empty one. It would be nice to consolidate all my heroin or cocaine into one bag instead of having to carry multiple baggies.

**Comment by Qrox** [comment]
That's a general issue with non-liquid items, afaik: they can be unloaded from their containers but cannot be put back.

**Comment by chriseich21** [comment]
You could also make recipes that use plastic bags also take zipper bags (maybe x2 due to size difference) so they're not useless once unloaded.

**Comment by baldamundo** [comment]
> That's a general issue with non-liquid items, afaik: they can be unloaded from their containers but cannot be put back.

afaik not only is there no benefit to putting items in non-wearable containers, it's normally actually disadvantageous, since the bag takes up extra volume. So even if you could reload these containers, with the current implementation I don't think there's ever any reason to do so?
