### ISSUE TITLE
Tailoring window not showing tailoring dialogs

### ISSUE THREAD

**Issue by reed501** [CleverRaven/Cataclysm-DDA#33748]
# Describe the bug

When in the main tailoring window (activated the tool, picking which clothing to work on) if a dialog is called to the log it won't appear until you go to a different window, notably not having enough rags/patches/etc. If you don't have enough rags, for example, the cursor returns to the first item and you aren't told what is going on. If you leave that menu, either hitting Esc or even tailoring something else that you do have equipment for the messages all appear at once as if the game had been paused. The messages can also stack.

# Steps To Reproduce

1. Try to tailor something you don't have patches for
2. Leave the menu

# Expected behavior

When attempting to tailor something there should be notice of why it failed.

# Versions and configuration

 - OS: ChromeOS 76
 - Game Version: O.D-7177-gd2c5b8f
 - Graphics version: Tiles
 - Mods loaded: None

**Comment by Petethegoat** [comment]
This is a very annoying issue. I did look into it, but I didn't have any luck figuring out how to refresh the main message panel while in the tailoring UI.

**Comment by DSeyka** [comment]
It's also a regression, since it used to work properly.
