### ISSUE TITLE
Infinite Cooking when resuming craft

### ISSUE THREAD

**Issue by reed501** [CleverRaven/Cataclysm-DDA#33746]
# Describe the bug

When resuming a craft of clean water I was given every possible option of cooking tools, many of which I did not have. Using one I did not have resulted in free boiling of the water.

# Steps To Reproduce

1. Begin crafting clean water
2. Quit part of the way through
3. Continue work on craft

# Expected behavior

When finishing up a craft, the tools used should be tools I have, not ones I don't.

Not really in the scope of this issue but should we be able to partially boil water? Should all crafts have a partial state? Or should some crafts just fail if your fire burns out or your cooking stick burns up?

# Screenshots

![Screenshot 2019-09-01 at 13 33 10](https://user-images.githubusercontent.com/12606597/64082038-e71f8a80-ccbd-11e9-9bb2-bdfdb1598b51.png)

# Versions and configuration

 - OS: ChromeOS 76
 - Game Version: O.D-7177-gd2c5b8f
 - Graphics version: Tiles
 - Mods loaded: None

**Comment by ipcyborg** [comment]
Can't reproduce in 0.D-8000-gb59c207aa3.
1. Try to boil water using survivor mess kit. 
2. Interrupt the process of crafting. 
3. Drop the survivor mess kit far away. 
4. Continue the process of crafting.

It has failed with the correct error: "Missing survivor mess kit". When the survivor mess kit is reacquired it is possible to continue.

**Comment by davidpwbrown** [comment]
Yep, cant reproduce, cant even get the error described above - the partial craft can be worked on to completion even after the survivor mess kit has been moved far away.
