### ISSUE TITLE
stereo system doesn't work

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33744]
# Steps To Reproduce

1. Load the game.
2. Spend some time.
3. There's no sound or morale buff even though the stereo system is turned on.

[2019.07.09.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3563845/2019.07.09.zip)
0.D-7185-ge4fd06fd24-dirty

**Comment by sztosz** [comment]
Have you tried taking off ear plugs from your ears? ;)

**Comment by l29ah** [comment]
Ouch, that was an accident! :D
