### ISSUE TITLE
Android keyboard bug and caused crash

### ISSUE THREAD

**Issue by gearforcer** [CleverRaven/Cataclysm-DDA#33740]
# Describe the bug

When I started the game and tapped return button using keyboard to type a world name, I just found both Delete and Enter button didn't work. So I tried to tap return button once to retract keyboard, then it caused crash. I can't play the game totally.

# Steps To Reproduce

 1.Run the game and tap return try to type something.
2.Find Delete and Enter button on the keyboard don't work.
3.Tap return once then cause crash.

# Expected behavior

All the keyboard and return button should work well, and never cause crash.

# Versions and configuration

 - OS: [Android 9]
 - Game Version: [0.D-7207-g9a3586a]
 - Graphics version: [Tiles]

**Comment by ZhilkinSerg** [comment]
Did you try non-stock keyboard?

**Comment by gearforcer** [comment]
Yeah, I tried. Tap return twice then crash, It occurs on recent several Android versions.

**Comment by gearforcer** [comment]
Many other players  also confirmed this issue.

**Comment by gearforcer** [comment]
> Did you try non-stock keyboard?

Many other players also confirmed this issue.

**Comment by ZhilkinSerg** [comment]
Duplicate of #33781
