### ISSUE TITLE
Map Memory should use a frequency-based cache rather than LRU

### ISSUE THREAD

**Issue by chphilli** [CleverRaven/Cataclysm-DDA#33741]
**Is your feature request related to a problem? Please describe.**  
A player can spend a huge amount of time near "home", but a single quick out-and-back trip to anywhere causes map memory back at home to be completely cleared out. It's not reasonable that you remember places you've visited only briefly better than the place you've been living for an extended period of time.

**Describe the solution you'd like**  
Cache replacement policies are pretty well defined and come in various degrees of complexity. The simplest fix for this is to replace the LRU with a simple LFU policy. This could be implemented with a simple drop-in replacement for `lru_cache` with the same interface to use in `map_memory`. 

This would trade the out-and-back problem for a new one -- places you _didn't_ spend much time in would be hard to learn compared to your "home". So if you ran out to explore a city and then back home, you'd likely forget much of the city but when you came back home you'd still remember the area very well. 

A very slightly more complex but still very low-impact solution would be to _add_ an LFU cache to `map_memory` rather than replacing the LRU cache. This would result in a pretty natural combination of remembering familiar places well but also places that you were at very recently. 

The dual-cache scheme might also require also adjusting the max number of memorized tiles (potentially independently for each cache) to tune total number of remembered tiles. But given that the caches would often have a high amount of overlap, such a change might not even be necessary.

**Describe alternatives you've considered**  
I spent a good deal of time reviewing other more complicated replacement policies (e.g. https://en.wikipedia.org/wiki/Cache_replacement_policies lists several and links to research describing them) but the amount of change & risk required to implement the more complicated policies seems unwarranted for this case.

**Additional context**  
The only complication I see with adding an LFU policy is that in order to account for frequency we need to actually increment a frequency counter in the cache when we re-visit a tile. If I'm reading correctly, this is currently guarded against with calls to `map::check_and_set_seen_cache` in every place that `avatar::memorize_tile` is called. This was added in #27457 to prevent expensive cache updates as we re-visited tiles. 

If, rather than guarding the call to `avatar::memorize_tile`, we instead passed the result of `map::check_and_set_seen_cache` into `memorize_tile`, we could use that fact to only update the frequency counter and only do the more expensive cache maintenance operations when we're visiting a tile that wasn't previously cached.

**Postscript**
I apologize if this has already been discussed -- I searched quite a bit and didn't find any specific references to _why_ an LRU cache was used. If a change along these lines isn't desired, maybe this issue will help someone else not need to go down this route of investigation as well. 

If there's interested in a solution like this, and I can get my Windows build environment working, I think I could put together an implementation. My c++ is a bit rusty, but this area of the codebase seems new and clean enough that I could re-educate myself based on the surrounding areas.

**Comment by kevingranade** [comment]
The LRU cache handles the primary purpose of recalling recently visited terrain while exploring with no player intervention pretty perfectly. I don't want to mess with that use case at all.
For the "remembering details of home base" use case, I'd prefer to have a seperate data structure that either has manual intervention of some kind or a much coarser tracking system, perhaps a LFU, that acts at a submap scale and is therefore able to operate efficiently without the special handling I added for the LRU cache.
> passed the result of map::check_and_set_seen_cache into memorize_tile, we could use that fact to only update the frequency counter and only do the more expensive cache maintenance operations when we're visiting a tile that wasn't previously cached.

If I remember correctly we couldn't afford a hash table lookup per tile per turn, much less any associated updates.
