### ISSUE TITLE
Stacking Items are inconsistent

### ISSUE THREAD

**Issue by reed501** [CleverRaven/Cataclysm-DDA#33750]
# Describe the bug

Picking up a stack of items can be pretty random in the result if you already have a stack of that item. A few examples:
 - Picking up a soap bar (10) when you have a soap bar (10) makes soap bar (20)
 - Picking up a soap bar (10) when you have a soap bar (9) gives you two soap bars of (10) and (9)
 - Aspirin doesn't do this, if you have any number you can just add to it
 - Unless aspirin is favorited, then it's a separate quantity
 - Duct tape, nails, and more similar items may or not combine I haven't figured out the formula yet.

# Expected behavior

Picking up more of an item should always produce the same behavior, either creating another item or mixing it with your current item. I'd personally prefer the latter but as long as it's consistent I'm happy.

# Versions and configuration

 - OS: ChomeOS 76
 - Game Version: O.D-7177-gd2c5b8f
 - Graphics version: Tiles
 - Mods loaded: None

**Comment by Hirmuolio** [comment]
At least one cause is items having `"ENCUMBRANCE_UPDATE"` flag on them.
