### ISSUE TITLE
Broke Ass camp

### ISSUE THREAD

**Issue by thestalker12** [CleverRaven/Cataclysm-DDA#33752]
AH yes a shit post description because its really that small of a stupid issue
god

# Describe the bug:
Every time I try to add food to my camp and then sort said food it says displayed "0" cals distributed

Broke ass camp

# Steps To Reproduce

1 Put food in litreally all "food zones". Both missions and Loot type
2. Access board
3. "YOU HAVE DISTRIBUTED 0CALS"

# Expected behavior
it works and allows me to do the first camp missions

# Screenshots
https://gyazo.com/87156e0b74884a1b4935223b627aa705
https://gyazo.com/cf8f4270fdaac159a63f02bac88d81e8
https://gyazo.com/52503655f627f22acd13ba7a1daf8263
https://gyazo.com/2ab5c2d4f647eb5d5000e53460c5d564
https://gyazo.com/c969b14c3a0709e681eee209b23ff4bb

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration
 - OS: Window 10
 - Game Version: 9577
 - Graphics version: Not really applicable
 - Mods loaded: 
FUCK ill post the file since im to tired to try to play mod copy copy 

# Additional context
I was told this is hell to fix 
heres the shit hole mod list. aaaaa

https://mega.nz/#!tjgVwShZ
Mod list
https://mega.nz/#!tjgVwShZ
WORLD FILE AAAAA
https://mega.nz/#F!Vy4xFQ

**Comment by ZhilkinSerg** [comment]
Your links are encrypted.

**Comment by EddiTheBambi** [comment]
Could you refrain from shitposting in the github issues? "A clear and concise description of what the bug is." is more likely to get attention and actually be fixed.

**Comment by jeremyshannon** [comment]
Did you go to the bulletin board and select "distribute food" from the menu? Because you can't just drop it in the sorting zone, you have to actually hand it out from the bulletin board.

**Comment by kevingranade** [comment]
If you can't be bothered to write a proper issue we can't be bothered to keep it open.
