### ISSUE TITLE
Sensible martini servings

### ISSUE THREAD

**Issue by BenlyAZ** [CleverRaven/Cataclysm-DDA#33759]
The martini recipe creates a single indivisible half-liter serving with over 1000 calories. This is way too much martini for one serving. 

**Describe the solution you'd like**  
A martini is 3-4 oz (about 90-120ml). Given that there are no additional mixers in the martini recipe and for general convenience's sake it would make sense to divide the 500ml martini recipe into five 100ml servings.

**Describe alternatives you've considered**  
Four 125ml servings would also be reasonable if we presume survivors are especially thirsty.

**Comment by Maddremor** [comment]
100 ml seems like a reasonable rounding point, although 125 would fit better with current container volumes that generally comes in multiples of 250 ml. Then again, given that the old volumes were set before the current metrification, perhaps we should not feel beholden to the 250 ml convention.
