### ISSUE TITLE
NPC's stuck in overworld map and won't reappear in actual game.

### ISSUE THREAD

**Issue by ShinWinddreamer** [CleverRaven/Cataclysm-DDA#33757]
# Describe the bug

NPC's are "stuck" in the overworld map and won't appear as physical NPC's in the actual gameworld to interact with after reaching target destination (my faction camp). So now the 4 NPC's are shown as "busy travelling" and can not be hailed via radio as they count as on a mission. This also is a request for  a feature to allow players to cancel missions  not only over the factions board (because, in this particular case, orders to travel somewhere can't be cancelled that way) but to directly hail them and simply tell em to stop what they are doing.

# Steps To Reproduce

This is where it get's tricky. I don't know IF this will reproduce it exactly as NPC's are a fickle thing but here is the whole story:
I free'd 4 NPC's of a prison and recruited them. I told all 4 NPC's to go towards my faction home. After a good 2 weeks ingame time I noticed that they haven't moved at all on the overworld map so I drove there and found them on the road. 
I talked to each of them and told them to guard position then follow me into my van so I manually transported them to my faction camp.
Upon arrival to said camp i told them to guard the area in the dining hall after having equipped each one with a fully charged two way radio and then they moved out and then were gone.

I can't assign them to any tasks. They show on the overworld map over the faction camps position but I can neither see them or interact with them via radio or faction board. Now they get more and more hungry and will, most likely, knowing the system, drop the reputation of my followers so far that they will start attacking despite the factioncamp having 100k stored calories.

Send halp

# Expected behavior

For the NPC's to stay in the guarded position and not pickup a mission that i hoped i had cancelled or overridden by telling them to guard an area.

# Screenshots

https://imgur.com/a/WJHto7Y

As displayed in the screenshot the NPC's are not interactable and are in transit despite having, technically, reiched their transit destination long ago and won't come out of it.

# Versions and configuration

current build used there is 9576 and version is: O.D-7207 -g9a3586a

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-7207-g9a3586a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Filthy Clothing [no_filthy_clothing],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills]

**Comment by jtriddle** [comment]
Experiencing the same bug.
Also caused by telling NPC to go to location and then giving them a lift there (by first telling to guard, and then to follow).
Mods: "dda", "mutant_npcs", "no_olg_guns", "MMA", "national_guard_camp", "no_npc_food"

**Comment by devgs** [comment]
Same issue. Asked NPC to travel to me by accident (mistype), while being at the camp, cancelled the request (ESC) but it still said he's travelling. Asked him to guard then to follow me. Went to sleep and boom, he's gone.

**Comment by KoRv117** [comment]
Told an NPC to follow me, she wouldn't and when I went to talk to her she kept seeming like she was in a camp activity like fishing or guarding. Told her to travel to my camp, she has now disappeared except on the overmap, says she's travelling but she's yet to arrive.

**Comment by davidpwbrown** [comment]
I'll look into this.
