### ISSUE TITLE
Bipods suddenly require MOUNTABLE flag to be fired

### ISSUE THREAD

**Issue by chriseich21** [CleverRaven/Cataclysm-DDA#33769]
# Describe the bug
Currently in build 9577, bipod weapons (specifically m2010 ESR) require you to be on MOUNTABLE terrain in order to fire at all. You should have either a penalty or no benefit (as before) from a bipod that isn't deployed but not completely remove the ability to fire. I did not see this mentioned as a change but it worked fine in build 9569. 

# Steps To Reproduce
1. Spawn as Sheltered as Bionic Sniper. 
2. Wield the default weapon (m2010 ESR w/bipod) and attempt to fire. 
3. Receive a prompt to be on MOUNTABLE terrain in order to shoot. 

# Expected behavior
You should have either a penalty or no benefit from a bipod (as before) that isn't deployed but not completely remove the ability to fire the weapon. 

# Versions and configuration
 - OS: Android 9.0
 - Game Version: Build 9577 (version 0.D-7213-ga0159bf) 
 - Graphics version: Tiles
 - Mods loaded: [DDA, CRIT Exp, Garden Pots, Makeshift Items, Medieval and Historic, More Survival Tools, Mythological Replicas, Dinomod, Modular Turrets, Salvaged Robots, Alt Map Key, EZ Medical, Hydroponics, Beta National Guard, More Locations, Fujis More Buildings, Urban Development, Folding Parts, Vehicle Additions, Tanks and Other, Necromancy]

**Comment by anothersimulacrum** [comment]
Yep, my bad. Will be fixed in #33761

**Comment by chriseich21** [comment]
> Yep, my bad. Will be fixed in #33761

No problem! Thank you good sir!
