### ISSUE TITLE
Can't install 32' armored wheels anymore

### ISSUE THREAD

**Issue by ShinWinddreamer** [CleverRaven/Cataclysm-DDA#33785]
As it says in the title. I uninstalled the wheels of my vehicle now can't reinstall them anymore. I looked if i may need a specific mount or mechanism first now as you seem to need now for 17', 24' and bike/motorbike wheels but I can't seem to find it

Edit:Apparently you need the heavy hub assembly. Problem is: all the armored vehicles in current map (sadly a huge one where it'll take a while to get to unexplored places) have no installed heavy hub assembly to take out and install in my own vehicle and apparently my character isn't able to craft it himself despite 11 mechanics and similar stats in fabrication and electronics. I'd appreciate some help in the matter

# Steps To Reproduce

Examine vehicle/ Install part with 32' armored wheel nearby/ won't show up in craftinglist

# Expected behavior

Well, for it to be installed in the appropriate slot or there be a way to have a suitable mount.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-7252-gb56478c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Filthy Clothing [no_filthy_clothing],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills]

**Comment by Hirmuolio** [comment]
Your car had a 32" wheel installed and after the update it did not have heavy hub assemblies installed? Does it have any hub assemblies installed?

In my old save the spawned mechanized infrantry carriers and such did get the new hub assemblies so old spawned vehicles should have them. Also new spawned vehicles have them.

**Comment by ShinWinddreamer** [comment]
> 
> 
> Your car had a 32" wheel installed and after the update it did not have heavy hub assemblies installed? Does it have any hub assemblies installed?
> 
> In my old save the spawned mechanized infrantry carriers and such did get the new hub assemblies so old spawned vehicles should have them. Also new spawned vehicles have them.

I checked in on that. I found assemblies on the vehicles now though still would appreciate a way to make them myself or be able to learn the recipe via book or be able to disassemble them to learn it that way. As of vehicles not having them, that was an error on my part as they do have them now from what I can tell thus far.
