### ISSUE TITLE
Backwards facing headlights, 360° high powered lightsource for vehicles, Tesla turret.

### ISSUE THREAD

**Issue by ShinWinddreamer** [CleverRaven/Cataclysm-DDA#33784]
Basically what it says on the tin. With larger vehicles and cameras along with turrets you can only really fire your turret 360 degrees when it's daylight. At night none of your lightsources will illuminate backwards and so the cameras and with it you, can't see and aim at targets. That does work ,to a degree, if you are setting the turrets to aim automatically but i found that , in the case of the tesla turret so far, it can hurt yourself more then the enemy if you move and the turret shoots ahead of you while you move into the electricity in the same turn with the vehicle. 
I don't know how many affected by that particular issue but the Tesla turret definitely is a self hazard despite it being mounted on top of  the vehicle you, as a player, can be hurt inside the vehicle anyways.
Not really asking for a new fancy lightsource but simply being able to place current head- and floodlight's in a way that make it possible.  Whenever it ask me to press a direction when installing a headlighter I tried countless times but they will always only shine forwards. If I am just dumb please help me understand what I am doing wrong.

**Comment by Rhyssia** [comment]
@ShinWinddreamer 
Afaik (For directional placed lights) You need to install the item, and use the "enter" key to confirm the message, and then the "enter" key again to set the direction. If you use any other key to confirm placement they will default to straight ahead of the vehicle (top portion in vehicle examine menu.)

**Comment by jeremyshannon** [comment]
Floodlights are omnidirectional. It's what I would use for night-time turret use. The Tesla thing definitely sounds buggy though.

**Comment by ShinWinddreamer** [comment]
![grafik](https://user-images.githubusercontent.com/54183288/64204868-f0b01a80-ce96-11e9-90a2-5777f0a1d64a.png)

This prompt would need fixing then as it wont say anything about pressing enter to confirm so it would explain why it never works. I tried it now with enter and it does work as intended so a minor fix to make the prompt be fitting for the situation would be great and ty again for the heads up.
