### ISSUE TITLE
Show progress bar in sidebar for long running crafting/construction

### ISSUE THREAD

**Issue by Widdershin** [CleverRaven/Cataclysm-DDA#33789]
**Is your feature request related to a problem? Please describe.**  
The problem I have is that it's often hard to understand how far through crafting something I am whilst crafting. Additionally it's frustrating to have to note the crafting time, the start time, the end time and the current time to manually estimate progress. I often forget to consult the crafting time and have no idea if I'll be waiting 20 minutes or 4 hours.

**Describe the solution you'd like**  
Whilst crafting or constructing, or really performing any long running operation, there should be a progress bar displayed on screen. I think a good location could be at the bottom of the message log by default.

**Describe alternatives you've considered**  
Could also have a modal pop up with a progress bar but that feels far messier.

**Additional context**  

Here is a super rough mockup:
<img width="1440" alt="Screen Shot 2019-09-04 at 2 06 53 AM" src="https://user-images.githubusercontent.com/398365/64180678-51e8e580-ceb9-11e9-9e26-78c12f4ea35c.png">
It could also display a time estimate directly in line (eg 13 minutes remaining).

If this feature is desired I'd be willing to have a crack at implementing it. I'm not super well versed in C++ but I've done a lot of dev in different languages so should be able to figure it out. I mostly just made this issue to make sure that this wasn't something that had been proposed and rejected before.

**Comment by Widdershin** [comment]
It could also just be a single line of text like `Crafting Bone Flute - 32% (40 minutes remaining)`

**Comment by chriseich21** [comment]
If you are wielding the item you are crafting it gives a percentage complete already, but not a time remaining. However if you are crafting on a surface, like a workbench or table, then there is no way to know your progress until it is completely finished and says "you place X on the table"

**Comment by Petethegoat** [comment]
This is a great idea, but I'd base it off of the waiting popup instead of a sidebar thing.

**Comment by anothersimulacrum** [comment]
This looks good in to me, I'd say you should open a PR.

**Comment by alkemann** [comment]
Now you can actually press `.` to abort the crafting, inspect the in progress item, look at the watch, eat a banana and drink some water and then continue the craft by activating the table or wielded item.
