### ISSUE TITLE
You are still stuck in rubble even if you clear it with a shovel after getting stuck in it.

### ISSUE THREAD

**Issue by Qydra** [CleverRaven/Cataclysm-DDA#33801]
# Describe the bug
If you use a shovel to clear rubble that you are stuck in, you still have to struggle to get out of the rubble afterwards.

# Steps To Reproduce
1.Collapse a ceiling on top of your character.
2.Use a shovel and the period (.) key to clear the rubble on the tile you are standing on.
3.Try to move.  The game will act like you're stuck in rubble even though you just dug yourself out.

# Expected behavior
If you use a shovel to clear rubble that you are stuck in, you should be able to just walk away--not have to struggle to get out of rubble that doesn't exist anymore.

# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.D-8574
 - Graphics version: Terminal

**Comment by snipercup** [comment]
I have also experienced this.
