### ISSUE TITLE
Burner Zombie drops way too much napalm.

### ISSUE THREAD

**Issue by Luiizz** [CleverRaven/Cataclysm-DDA#33807]
# Describe the bug

Burner Zombies drip (250) every so often, but there is no limit too how much they can actually drip, witch means a burner zombie could coat an entire city in napalm.

# Steps To Reproduce

1. Spawn a Burner Zombie in a locked glass room.
2. Wait for a while.
3. The zombie will have dropped way more napalm than he could possibly have in it's flamethrower.

# Expected behavior

There is a point where the zombie would not drip anymore, or maybe not even drip at all since he has a explosive attack that would require fuel and his flamethrower never drops empty.

# Screenshots

![Too_much_napalm](https://user-images.githubusercontent.com/39201027/64280735-1f2a0600-cf28-11e9-85a9-3390917f4772.png)

![Way_too_much_napalm](https://user-images.githubusercontent.com/39201027/64280748-23eeba00-cf28-11e9-92b0-411ce4bb1a54.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-7294-ga7a4710
 - Graphics version: Tiles
 - Mods loaded: DDA, Magiclysm, No Rail Stations, Bionic Slots, Disable NPC Needs, SpeedyDex, Stats Through Kills

# Additional context

I was living at the top of the nearby church and the burner wandered into my reality bubble from somewhere I never saw since I have wander spawns turned on.

**Comment by alkemann** [comment]
Hey. So I have this working now, but there is the question of how much they actually should drip. Both in terms of each time and how much in total. The current implementation I have set up is 10% chance to drop 50mL and it has 1000mL to start with. I also reduced the amount that will be left in the flamethrower if the Z is killed to compensate for the liquid on the ground
