### ISSUE TITLE
Unable to use any type of jumper cable for intended purpose.

### ISSUE THREAD

**Issue by Rhyssia** [CleverRaven/Cataclysm-DDA#33805]
# Describe the bug

Unable to use any type of jumper cable for intended purpose. Cannot park two vehicles together with a single tile gap and hook one jumper cable to one, and use again to attach to the other vehicle.

If I debug install the cable charger CBM, then cables will work as intended.

# Steps To Reproduce

1) Start new map with fresh character
2) Spawn Golf Cart
3) Take three steps to the right
4) Spawn Golf Cart
5) Take one step to the left
6) Spawn Jumper Cables or Heavy Duty Cable
7) (A)ctivate cable, attach to left or right.
8) (A)ctivate cable a second time.
9) Only option is to "Detach and re-spool the cable"

# Expected behavior

To be able to attach a jumper cable from one vehicle, to another. In a normal fashion expected in previous versions.

# Screenshots

**N/A** Do not feel that it would be important for this issue.

# Versions and configuration

 - OS: Windows 7 (64b)
 - Game Version: 0.D-7294-ga7a4710
 - Graphics version: Tiles
 - Mods loaded:   
"dda",
"No_Fungi",
"no_npc_food"

# Additional context

Save:
[TEST WORLD.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3575715/TEST.WORLD.zip)

Possibly related to changes:
https://github.com/CleverRaven/Cataclysm-DDA/commit/adf6a8a782849dfbfb596dbf02ded8ea78369500#diff-74bb173f819041f82ce1da375b45569c

**Comment by Rhyssia** [comment]
Additionally you cannot attach the cable to a UPS that is carried, worn, or on your tile. It gives the option but returns that "You don't have any UPS". If on tile, no UPS option is present.

**Comment by UnmitigatedDisaster** [comment]
I am encountering this issue as well.  I tested it and found that it occurs in builds starting #9587
