### ISSUE TITLE
Items piled up beyond a tile's limit can pass through walls to fall onto the nearest tile with enough space to hold them.

### ISSUE THREAD

**Issue by Qydra** [CleverRaven/Cataclysm-DDA#33815]
# Steps To Reproduce

1. Stand in a corner such that the only tiles you can drop items in are the one you are standing on and the three to your west, south, and south-west respectively.
2. Fill those four tiles with 1000L of items.
3. (Possibly) Also fill the tiles two to the west and two to the south of your initial position in step 1.
4. Keep filling the corner tile with items such that they slide off onto other tiles.  Soon, you will find that items have passed through the wall to the other side.  The piles have not flowed around the wall--they have flowed through it.

# Expected behavior

Overflowing items should not pass through walls while moving to rest in an available tile.  In extreme cases, items with nowhere to go could find the flimsiest window, door, or wall and break through it.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-8574
 - Graphics version: Terminal

**Comment by forsaken-qubit** [comment]
Can confirm. My easiest reproduction was trench digging with a faction camp. 

Have six tents, have some bloke dig the NESW trench, (the corners make less), and dirt, rocks, pebbles, clay and sand will spill into your tents.

My experience was in 9585-Win10-Tiles.
