### ISSUE TITLE
Certain menus won't let you do actions with heavy items while you can do them manually

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33813]
# Describe the bug

You can't `R`ead, `(`disassemble, `a`ction and so on with any item outside of your inventory when you're overburdened, but it's perfectly fine to place the items in your inventory manually and execute the action. This adds a lot of dumb micromanagement for low-strength characters that spend all their "free" weight limit on armor and sit at their base/in their deathmobile surrounded by items.

# Expected behavior

The survivor using/picking up things regardless of their weight like they do in AIM. 

# Screenshots

![](https://pstbin.ru/f/80829/)

# Versions and configuration

0.D-7223-gbdba80a3fa-dirty

**Comment by Soul5hadows** [comment]
It's the same deal with items that are too big to pick up. Like that smoking rack in your image. Although with items that are too big to pick up, I've been able to work around it by dropping and clearing what's in my hands. Not sure if the same applies to "too heavy" items.
