### ISSUE TITLE
NPC faction plus 6NPC's gone after recent patch

### ISSUE THREAD

**Issue by ShinWinddreamer** [CleverRaven/Cataclysm-DDA#33823]
# Describe the bug
After the most recent patch [#9590] in which following issue was resolved:

stop dynamic NPCs remembering wrongs as they dont have a normal faction

My factioncamp/faction was deleted as well as the 6 followers (4 of them bugged as seen here:
https://github.com/CleverRaven/Cataclysm-DDA/issues/33757
were simply removed. The buildings the camp has been constructed with via missions are still there but yeah the NPC's and faction is gone. If i make a new faction on the same position i still have to reconstruct everything despite all buildings still standing there. I is a major issue for me as I devoted my entire character and playthrough to be revolving around that : Building a camp and gathering people. I spend a good 100hours on that so far and with this issue being there that has been effectively nullified.

# Steps To Reproduce

Cant exactly give reproduction info other then to have a: a savegame from build #9580 or earlier
B:have a factioncamp with 3 expansions. Kitchen, Blacksmith, Farms
C:2 working NPC's that aren't bugged out on the overworld map
D:4NPC's stuck on the overworld map and being constantly "busy in traffic" and unable to actually return to faction headquarters
E: Update game to newest version

# Expected behavior

Ideally to have 6 working NPC's and a factioncamp back or to, when refounding a camp at the same location, for it to account for the progress made on said  location and not having to repeat it.

# Screenshots

![grafik](https://user-images.githubusercontent.com/54183288/64340532-af2e8500-cfe6-11e9-9775-18348677bf14.png)
![grafik](https://user-images.githubusercontent.com/54183288/64340554-bbb2dd80-cfe6-11e9-833b-00f8e49d7d5f.png)
![grafik](https://user-images.githubusercontent.com/54183288/64340577-c4a3af00-cfe6-11e9-88b1-a5a7cc00b977.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-7308-g75995bc [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Filthy Clothing [no_filthy_clothing],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by ImportTaste** [comment]
If this bug doesn't exist with new saves then you're SOL. Coding in compatibility between versions is just too much of a hassle for a project this large.
