### ISSUE TITLE
Game crashes inconsistently but often when traveling.

### ISSUE THREAD

**Issue by DanteTorn** [CleverRaven/Cataclysm-DDA#33827]
# Describe the bug

When moving around the map by foot or vehicle, the game will randomly crash to desktop. It seems it may be related to a missing texture, but I can't tell exactly. It isn't any one particular area, it's very random.

# Steps To Reproduce

1. Move around map by foot or vehicle.
2. Game creates error window and crashes to desktop.

# Versions and configuration

- OS: Windows 7
- OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-7294-ga7a4710 [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    NPC traits [npc_traits],
    Zetsukaze's Hair - 0.D EDIT [zets_hair_extensions],
    Hydroponics [hydroponics],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Gasoline Boomers [No_Gasoline_Boomers-DANTE],
    Stats Through Kills [stats_through_kills],
    Safe Autodoc [safeautodoc]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3580170/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3580171/crash.log)
[Wroth Cherry.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3580176/Wroth.Cherry.zip)

**Comment by DanteTorn** [comment]
I've just tested making a world with no mods and driving around in it, and the same crash happens.

**Comment by DanteTorn** [comment]
I've done some more testing and the game seems more likely to crash whenever it's lagging. Turning off experimental z-levels made it last longer before crashing, but it still crashed when the game started lagging a bit when driving through a large city. I could be making false equivalancies though.

**Comment by Rhyssia** [comment]
@DanteTorn Have you tried checking your ram usage while playing? I only ask because you're using the 32 bit client with tiles. IIRC once you hit 2gb of ram usage the game will most likely crash.

**Comment by DanteTorn** [comment]
> 
> 
> @DanteTorn Have you tried checking your ram usage while playing? I only ask because you're using the 32 bit client with tiles. IIRC once you hit 2gb of ram usage the game will most likely crash.

Using the 64 bit version on the latest version doesn't seem to lag or segfault on me, so that seems like it is the issue. Thanks.
