### ISSUE TITLE
mi-go slaver beam goes through vehicle walls, sets all stats to zero, incurs severe pain and empties stamina instantly

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33820]
# Describe the bug

This doesn't seem to be balanced at all.

# Steps To Reproduce

1. Load the game.
2. Ride closer to the mi-go crowd on the nearby bridge that came out of the portal at the beginning of the game.
3. Observe the devastating effect.

# Versions and configuration

0.D-7223-gbdba80a3fa-dirty

# Additional context

[2019.09.02.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3578841/2019.09.02.zip)

**Comment by Firestorm01X2** [comment]
May be partially fixed with:
https://github.com/CleverRaven/Cataclysm-DDA/pull/33808

**Comment by l29ah** [comment]
wtf magic shit in my unmodded cataclysm

**Comment by kevingranade** [comment]
Magnitude of effects reigned in by #33808, the rest is working as intended.
