### ISSUE TITLE
NPCs won't chop logs into planks

### ISSUE THREAD

**Issue by Highmongrel** [CleverRaven/Cataclysm-DDA#33832]
# Describe the bug

NPCs will not chop logs into planks when given the task

# Steps To Reproduce

1. Aquire friendly NPC
2. Create Loot: Wood zone
3. Place logs in Loot: Wood zone
4. Give NPC an axe
5. Ask NPC to cut logs into planks
6. NPC will start, then immediatly finish

# Expected behavior

NPCs cut logs into planks when asked to.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-7308-g75995bc [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Pretty sure the problem is in activity_tem_handling.cpp. The section added in #33091

    if( act == activity_id( "ACT_MULTIPLE_CHOP_PLANKS" ) ) {
        //are there even any logs there?
        for( auto &i : g->m.i_at( src_loc ) ) {
            if( i.typeId() == "log" ) {
                // do we have an axe?
                if( p.has_quality( quality_id( "AXE" ), 1 ) ) {
                    return activity_reason_info::fail( NEEDS_CHOPPING );
                } else {
                    return activity_reason_info::fail( NEEDS_CHOPPING );
                }
doesn't seem to have a possible ok return. Can't compile and test currently though.

**Comment by mqrause** [comment]
They also don't return the tools they took for the task, it seems.

**Comment by hexagonrecursion** [comment]
> They also don't return the tools they took for the task, it seems.

@mqrause please report this as a separate issue instead of hijacking an existing thread - this makes it easier to keep track of troubleshooting and debugging efforts. Thank you.

**Comment by hexagonrecursion** [comment]
I could not reproduce this bug: an NPC chopped two logs into 3 planks and 31 splintered wood.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Highmongrel** [comment]
Believe this was fixed some time ago, was unaware it was still open.

Looking further it was fixed by #34192

**Comment by mqrause** [comment]
> @mqrause please report this as a separate issue instead of hijacking an existing thread - this makes it easier to keep track of troubleshooting and debugging efforts. Thank you.

Uh, first this was pretty much ancient and second it actually looks related to the issue.
