### ISSUE TITLE
Slow Reading and Sleeping

### ISSUE THREAD

**Issue by ituluwituluwzev** [CleverRaven/Cataclysm-DDA#33833]
# Describe the bug

When reading or sleeping, time passes as slow as manually holding down "." key.

# Steps To Reproduce

Read or sleep in the attached save.

# Expected behavior

Time should pass faster.

# Versions and configuration

 - OS: Ubuntu 16.04 LTS
 - Game Version: 0.D-6697-geb74cfd
 - Graphics version: Terminal
 - Mods loaded: default

**Comment by ituluwituluwzev** [comment]
The save doesn't show up although it was attached.

I was in a dairy farm. The only monsters nearby are 3-4 cows and a tamed horse. Items are less than 500. I don't know if there's ant tunnel or sewer underneath, but when I arrived at this place there was no slowing during reading or sleeping. It only appears after probably one or two in-game day.

**Comment by ituluwituluwzev** [comment]
Another try at attached save. The file is 4M so it shouldn't exceed size limit.

**Comment by ituluwituluwzev** [comment]
After my character went for a bike ride and came back, and read again, the slowing didn't exist anymore. Reading became at the normal, fast speed, again.

Is there anyway other way to upload a save? Dropbox etc won't work because regional restriction.

**Comment by ituluwituluwzev** [comment]
After my character went for a bike ride and came back to the dairy farm, the slowing didn't exist anymore. Reading is at the normal, fast speed now.

Is there any other way to upload a save? Dropbox won't work because of regional restriction.

**Comment by DanteTorn** [comment]
@ituluwituluwzev Drag and drop the zipped file into a comment.

**Comment by ZhilkinSerg** [comment]
We can't do anything without savegame. Please upload it and ping me to reopen.
