### ISSUE TITLE
Enchantment Values (Organization)

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#33837]
This Issue is a general organization issue for Enchantment Values. There are quite a lot of them, and they are scattered throughout the code, so it will be necessary to break it up into more than one PR.
The available enums, and therefore suggested values for enchantments are as follows:

- [X] STRENGTH,
- [X] DEXTERITY,
- [X] PERCEPTION,
- [X] INTELLIGENCE,
- [x] SPEED,
- [ ] ATTACK_COST,
- [x] ATTACK_SPEED,
- [x] MOVE_COST,
- [x] METABOLISM,
- [x] MAX_MANA,
- [x] REGEN_MANA,
- [x] SPELL_LEVEL,
- [x] BIONIC_POWER,
- [x] MAX_STAMINA,
- [x] REGEN_STAMINA,
- [x] MAX_HP,        // for all limbs! use with caution
- [x] REGEN_HP,
- [x] THIRST,        // cost or regen over time
- [x] FATIGUE,       // cost or regen over time
- [ ] PAIN,          // cost or regen over time
- [x] BONUS_DODGE,
- [ ] BONUS_BLOCK,
- [ ] BONUS_DAMAGE,
- [ ] ATTACK_NOISE,
- [x] SPELL_NOISE,
- [x] SHOUT_NOISE,
- [ ] FOOTSTEP_NOISE,
- [x] SIGHT_RANGE,
- [x] CARRY_WEIGHT,
- [x] CARRY_VOLUME,
- [ ] SOCIAL_LIE,
- [ ] SOCIAL_PERSUADE,
- [x] SOCIAL_INTIMIDATE,
- [x] ARMOR_BASH,
- [x] ARMOR_CUT,
- [x] ARMOR_STAB,
- [x] ARMOR_HEAT,
- [x] ARMOR_COLD,
- [x] ARMOR_ELEC,
- [x] ARMOR_ACID,
- [x] ARMOR_BIO,
            // effects for the item that has the enchantment
- [x] ITEM_DAMAGE_BASH,
- [x] ITEM_DAMAGE_CUT,
- [x] ITEM_DAMAGE_STAB,
- [x] ITEM_DAMAGE_HEAT,
- [x] ITEM_DAMAGE_BULLET
- [x] ITEM_DAMAGE_COLD,
- [x] ITEM_DAMAGE_ELEC,
- [x] ITEM_DAMAGE_ACID,
- [x] ITEM_DAMAGE_BIO,
- [x] ITEM_DAMAGE_PURE,
- [ ] ITEM_DAMAGE_AP,      // armor piercing
- [x] ITEM_ARMOR_BASH,
- [x] ITEM_ARMOR_CUT,
- [x] ITEM_ARMOR_STAB,
- [x] ITEM_ARMOR_HEAT,
- [x] ITEM_ARMOR_COLD,
- [x] ITEM_ARMOR_ELEC,
- [x] ITEM_ARMOR_ACID,
- [x] ITEM_ARMOR_BIO,
- [ ] ITEM_WEIGHT,
- [ ] ITEM_ENCUMBRANCE,
- [ ] ITEM_VOLUME,
- [ ] ITEM_COVERAGE,
- [ ] ITEM_ATTACK_SPEED,
- [ ] ITEM_WET_PROTECTION,

Suggestions and questions on this issue are encouraged.

**Comment by Fris0uman** [comment]
What about affecting : 
- Warmth ? Either warmth given by the armor or directly affecting warmth of the player
- Character height
- Character weight
Those are quite minor but could be usefull later, maybe an enchantement that makes your huge mutant small again to fit in vehicle could be usefull ^^ .

**Comment by foulman** [comment]
I'm not entirely sure what BIONIC_POWER is supposed to be, but if it's anything like say MAX_MANA then I would recommend a REGEN_BIONIC/POWER as well, and if that doesn't increase the power pool then consider adding a MAX_POWER value to go along with it, I can see that being useful for magic and tech items.

**Comment by foulman** [comment]
Also perhaps a DAYTIME and NIGHTTIME flag for the enchantment conditions?

**Comment by crazykiddeath** [comment]
Maybe To-Hit Bonus and on hit effects like blind/stun etc?

**Comment by KorGgenT** [comment]
that would be a separate thing. This list is for modifiable values only.

**Comment by foulman** [comment]
Ah, silly me for not including this sooner:  Skill values. Both positive and negative would be simply fantastic. Imagine boots of dodging or a knife that gave you 2 extra points in cutting weapons. Now that I think about it, this could also be used as a basis to do things like a cyberpunk skillchip as well. Need to make a homemade bomb? Pop in that chip of Cooking +3 you found on that scientist in the last lab. Or rifles +2 from the dead cyborg SpecOps sniper. Negative could obviously be used for cursed objects, or to simulate a reduction in some other skills due to your brain being forced to cognitively handle the extra knowledge on a skill you are enhancing.

**Comment by foulman** [comment]
ATTACK_COST,
MOVE_COST,
METABOLISM,
MAX_MANA,
REGEN_MANA,
BIONIC_POWER, (regen too?)
MAX_STAMINA,
REGEN_STAMINA,
MAX_HP, // for all limbs! use with caution
REGEN_HP,
SKILL_VALUE
BONUS_DODGE,
BONUS_BLOCK,
CARRY_WEIGHT,
CARRY_VOLUME,
FATIGUE, // cost or regen over time
PAIN, // cost or regen over time
BONUS_DAMAGE,
ATTACK_NOISE,
SPELL_NOISE,
FOOTSTEP_NOISE,
SIGHT_RANGE,
THIRST, // cost or regen over time

**Comment by foulman** [comment]
Effective spell level boost, including negative values. would be a good way to balance some magic items out. +1 means all spells cast at one level higher.

**Comment by foulman** [comment]
Now that I think about it, can we have conditions for specific classes/traits? 
A magic staff that does certain things for everyone that holds it.. and a few extra things for a Druid? Based on has_trait I guess.

**Comment by FirebrandCoding** [comment]
LEANING_SPEED,

BIONIC_REGEN, // passively regenerate or drain bionic power outside of the CBM interactions

CHARGE_REGEN, // passively regenerate or drain all battery charge items (including UPS, but not items depending on it) currently carried on the person

ITEM_REGEN, // passively regenerate the specified item (whether worn or not)

CLAIRVOYANCE, // where value is the range of sight behind walls

DRAW_SPEED, // as in "draw from your holster"

AIM_SPEED, // bonus to the weapon's base aim time(?)

BONUS_ACCURACY,

BONUS_RANGE, // for attacks

REPLENISH_AMMO_CHANCE, // chance to regenerate ammunition when firing for those weapons that have a magazine or internal ammo capacity (does not affect UPS, bows, or crossbows)

TRAP_DETECT // without increasing Perception

**Comment by KorGgenT** [comment]
BIONIC_REGEN, // passively regenerate or drain bionic power outside of the CBM interactions

CHARGE_REGEN, // passively regenerate or drain all battery charge items (including UPS, but not items depending on it) currently carried on the person

ITEM_REGEN, // passively regenerate the specified item (whether worn or not)

i'm not sure these three fit into the definition of a "value", because they seem to need additional data. especially ITEM_REGEN

**Comment by FirebrandCoding** [comment]
For the first two, I meant regeneration in general. You walk around, and your bionic power / charge in all your batteries changes by the specified value. No other parameters are necessary to make the value itself work. Or do you mean it needs additional code to make happen?

For ITEM_REGEN, I figured they'd be attached to an item anyway, so only spread the effect to this one particular item. I guess you might need to specify which item, either in the JSON definition or in the engine code. Prompting it 'cause I kinda need that for a mod, and I imagine self-healing materials could be used by other modders and by the game itself later. If this could still be used in a different way, that would be great.

Three more values:

BIONIC_FUEL_EFFICIENCY, // straight efficiency increase; setting it to 1 would mean that any power-generating CBM would inevitably break the laws of physics (1 + 0.625 = super-efficient)

BIONIC_FUEL_EFFICIENCY_MULT, // multiplicative modifier; setting it to 1 would leave everything as is, and to 2 - increase all efficiency to 200%

ITEM_ATTACK_PENETRATE_CHANCE // chance for the projectile to pass through the first target (still damaging it) and hit the target behind it

That last one feels like ITEM_REGEN in that it might not work as I expect it to, from your perspective, but I thought it was neat to suggest.

Wording on the fuel efficiency effects could be better.

**Comment by GuardianDll** [comment]
A lot of it was adressed, except maybe ITEM related one, if something is missed, i encourage them to make a separate issue
