### ISSUE TITLE
Error on load: "Missing item definition: artifact_0"

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#33836]
# Describe the bug

Updated the game to latest build and having this error on loading:

 DEBUG    : Missing item definition: artifact_0
  FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1210

# Steps To Reproduce

1. Load the game.

# Expected behavior

No errors

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-7331-ga97a9eb [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Classes and Scenarios Mod [more_classes_scenarios],
    StatsThroughSkills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Alternative Map Key [alt_map_key],
    Vehicle Additions Pack [blazemod]
]

Save: https://drive.google.com/open?id=1kCqj_tNQYB0QLj4FkIGOBrn-z_kBZH-t

**Comment by RDru** [comment]
Does not occur in latest build

**Comment by jeremyshannon** [comment]
I'm experiencing this with a save, on current master. What version did you successfully load your save in? All my artifacts are being replaced with unknown_artifact_## thanks to this.
