### ISSUE TITLE
Rifle Caliber HMG's are obsolete.

### ISSUE THREAD

**Issue by tenmillimaster** [CleverRaven/Cataclysm-DDA#33849]
**Is your feature request related to a problem? Please describe.**  
The Rivetech family of 8x40 firearms stretches reality. It's *BRAND NEW* and has, apparently, 0 functional issues. This is highly unusual in the real world.

It's one thing to hammer out 1 product and slap on a few different barrels/stocks for a 'family', but everything from revolvers to heavy machineguns stretches the limits of suspensions of disbelief.

Specifically: The Rivtech RM298 HMG should not be.

A heavy machine gun is one of two things: 

1. A machinegun that can deliver monstrous firepower appropriate for lightly armored vehicles and other materiel. Pictured below.

![](https://upload.wikimedia.org/wikipedia/commons/8/8a/Doushka_desert.jpg)
![](https://upload.wikimedia.org/wikipedia/commons/9/91/M2_Browning%2C_Musée_de_l%27Armée.jpg)
2. A machinegun that can deliver sustained firepower for almost forever. Pictured below.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Vickers_Machine_Gun_YORCM_CA78ac.JPG/1024px-Vickers_Machine_Gun_YORCM_CA78ac.JPG)
![](https://collections.royalarmouries.org/media/emumedia/0/646/large_DI_2014_2677.jpg)

The RM298 fails the first category, as it shoots what is ballistically very close to 8mm mauser, (7.92x57mm). which isn't energetic enough to fit that category.

The RM298 most closely fits in the second, as it fires a battle rifle round.

There are not many HMGs of that type in service in the world. `" durability and extreme volume of sustained fire under the worst possible circumstances"` are no longer acceptable tradeoffs in modern firearm design, as static, heavy entrenched positions are no longer effective in vehicular centric warfare, and smaller medium machineguns are more than capable of meeting the needs of this sort of application.

This is compounded by the caseless ammunition, which despite the heat mitigation techniques used by Dynamit Nobel, would still need to contend with the lack of heatsinking cases, in applications where `"durability and extreme volume of sustained fire under the worst possible circumstances"` are needed. A better design tradeoff is to use the cased ammunition for vehicular usage, and have a longer duration of fire available. Caseless ammunition is mostly useful for dismounted troops; vehicular usage is less able to realize its benefits.

Look at the M240 as an example; It's a GPMG that is used dismounted with a bipod, and mounted in a pintle mount. The guns, save for a few egress kit components, are mechanically identical. Dismounted or mounted, they are no more/less capable than the other at sustained fire.

**Describe the solution you'd like**  
Replace all RM298's with RM614 LMG's.

**Describe alternatives you've considered**  
Making trench warfare relevant again.

**Comment by NotFuji** [comment]
There is also the RM2000 SMG and RM88 Battle Rifle (and both pistols to a slightly lesser degree), which are suspect for largely the same reasons.
It might be sensible to add anti-materiel, full-power, and pistol sized caseless ammotypes instead of just relabeling the guns.

**Comment by tenmillimaster** [comment]
I don't picture that as the ideal scenario- I think all the R&D development of this bleeding edge stuff would be focused on 1 action, and 1 caliber. After all, only the G11 was really fully materialized.
I think the best solution here is to look at the G11 and see Which of the 8x40 family can be safely based off it.
I think the SMG, LMG, and battle rifle are appropriate here. 
The RM2000 SMG: A short barreled, short magazine, suppressed  up-sized G11 that has far less recoiling deadspace and no 3-round burst mechanism.
The Battle rifle is just the up-sized G11.
The LMG, I'm not so sure about. A longer+heavier barreled up-sized G11 with slightly longer magazines, and more spares?

**Comment by mlangsdorf** [comment]
I think a long-barreled G11 with a 300 round clip in the buttstock was hypothesized.  Add a quick change barrel and bipod mounted separately from the barrel (ie, not M-60 style), plus mounting hardware for a tripod, and you've got a light/general purpose MG.

The scout/designated marksman rifle based on the battle rifle makes sense, too.

Converting the existing HMG to a 12x70mm caseless round might make sense, and would give them a purpose for existing beyond being a convenient source of huge amounts of 8x40mm rounds.  And if you have a 12x70mm caseless round, why not go ahead and make an anti-material rifle?

**Comment by tenmillimaster** [comment]
Lugging around a bunch of 12x70 for anti-materiel sounds ok to me, but doing so for an HMG doesn't. M2's mostly get used for vehicular stuff, where things can spare the weight.

I couldn't find any info on how the LMG11's magazine 'packet' actually worked, and it looked like it'd take a significant amount of more H&K engineering to do. Perpendicular fed, 25-column magazine? Sounds extremely unreliable if it was bleeding edge.

![](https://www.hkpro.com/image/g11lmgfeed.jpg)

The fewer leaps we have to make from the G11, the better.

**Comment by mlangsdorf** [comment]
There's not much point in simplifying your supply chain to use caseless and then having a bunch of cased rounds for your HMGs.  The weight savings don't just help for the individual soldier, but also for your logistics chain.

**Comment by tenmillimaster** [comment]
That's 100% true, but if this stuff is so bleeding edge that they're still fielding M4's and M249's, then they wouldn't have gotten to the point where they can remove those items from the supply chain. I just don't think we can be present day and have this much caseless stuff around.

**Comment by jeremyshannon** [comment]
From a gameplay balance perspective, the caseless ammo is high-end loot and a good reason to raid military sites, so it's arguably a good thing if it's not widely available in huge piles thanks to HMG spawns.

**Comment by thethunderhawk** [comment]
In general I think it’s interesting to find ways to make cool game elements make sense. To that end: 

Big old static HMGs don’t make sense anymore I agree. The dynamics of modern combat don’t allow those weapons to be effectively brought to bear, they need big vulnerable vehicles to cart them around. However, if there were a sufficiently mobile armored platform that could chase down and put pressure on enemy infantry without making a static target of itself, that sustained fire capability could be made useful again. So maybe our mechs and power armor could revive the rifle-caliber HMG.

**Comment by Barhandar** [comment]
The guns are caseless for "can't make your own ammo" reasons. They're really powerful for the same reason. While with the "reality simulator" direction CDDA is taking this issue will likely get resolved by removing the HMGs, they're not intended to be realistic.

Also, zombies don't understand modern warfare, so entrenched positions are perfectly fine against them.

**Comment by anothersimulacrum** [comment]
> Also, zombies don't understand modern warfare, so entrenched positions are perfectly fine against them.

Sure, but why would these be made when zombies weren't a threat?
