### ISSUE TITLE
Turret able to penetrate reinforced glass

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#33844]
# Describe the bug

On a new run, I found the secret bunker under a gas station. Without opening the path forward, the turret was able to shoot me through the glass

# Steps To Reproduce

1. Have m249 autonomous CROWS II  next to reinforced glass.
2. Let it see you from other side of glass.
3. It will penetrate the glass with its .223

# Expected behavior

Bullets won't penetrate glass.

# Screenshots

![image](https://user-images.githubusercontent.com/51099123/64445220-f29af900-d0a3-11e9-98c4-579b6794b12b.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-7342-g1ac3bf9 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Survivor Armor [no_survivor_armor],
    Classes and Scenarios Mod [more_classes_scenarios],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by Nacarbac** [comment]
I believe this is a deliberate change. 9mm will still fail to penetrate, but .223 and up can be targeted and fired through glass - though it seems like the damage is reduced somewhat. 

Incidentally, .50 BMG will destroy metal doors but not actually penetrate beyond (targetting done via the electrodetection mutation), which is probably not intended - an intermediate step, like with damaged wooden doors is probably better.

**Comment by Night-Pryanik** [comment]
I guess this is a subversion of #33374.
