### ISSUE TITLE
Add a system for gases as items that can be stored

### ISSUE THREAD

**Issue by roaringjohn** [CleverRaven/Cataclysm-DDA#33842]
**Is your feature request related to a problem? Please describe.**  
Apparently gases, as items (or rather, what should be gases), don't actually have their own phase, or even a system to store them. Acetylene, for example, was given the liquid phase.

**Describe the solution you'd like**  
Add a gas phase, along with the ability to store them inside things, namely canisters. A system that should go along with this is when outside of a canister and not used for crafting (say, for example, it ruptures), they should cause effects (and "destroy" themselves as they cause said effects, or become effects, or whatever).

**Additional context**  
As was brought up before, acetylene is in-game, but it was given the liquid phase, instead of being gaseous. I am planning to add in a lot of chemicals in the near future in multiple PRs, and there are lots of gases one could realistically obtain.

**Comment by Rail-Runner** [comment]
In case anyone feels like salvaging it, seems like it was already implemented in #12979, though it wasn't merged.
