### ISSUE TITLE
Horses should be able to reproduce

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33848]
Copying `mon_cow_calf` should be straightforward, but i have no idea which values to put in `age_grow` and `baby_timer`. How quickly do horses grow and reproduce compared to cows?

**Comment by Night-Pryanik** [comment]
According to the [Wikipedia](https://en.wikipedia.org/wiki/Horse#Reproduction_and_development), a three-year horse is ready to reproduce.
