### ISSUE TITLE
Crafting with infinite water shows int max value

### ISSUE THREAD

**Issue by reed501** [CleverRaven/Cataclysm-DDA#33857]
# Describe the bug

When crafting with an infinite water source (a well in my case) the amount of water shown is 2^31-1. I think this looks bad and should say something like "infinite" or "from well."

# Expected behavior

Display water (1 of infinite) or water (1 from well) or water (1) or just water, others will have a better idea of what this should say to look good, 2147483647 just is not it.

# Screenshots

![Screenshot 2019-09-06 at 21 05 21](https://user-images.githubusercontent.com/12606597/64469676-614f7500-d0eb-11e9-9c0d-e257a1696bb0.png)

# Versions and configuration

 - OS: ChromeOS 76
 - Game Version: 0.D-7343-g8333e52d
 - Graphics version: Tiles
 - Mods loaded: None

**Comment by alkemann** [comment]
I believe this is because infinite in the game is implemented as max in, there is even a comment that says "large enough".  Maybe the interface could be aware of that exact value and translate it to "infinity"?
