### ISSUE TITLE
Crash on assigning NPC base mission.

### ISSUE THREAD

**Issue by Highmongrel** [CleverRaven/Cataclysm-DDA#33869]
# Describe the bug

Game crashes after assigning an NPC a base mission.

# Steps To Reproduce

1. Spawn NPC
2. Start faction camp
3. Assign any base mission that causes the NPC to disapear

# Versions and configuration

- OS: Windows
    - OS Version: Windows 7 Enterprise
- Game Version: 0.D-7331-ga97a9eb [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Some testing found that it's related to the NPC riding changes introduced in #33550. If the NPC is mounted the game will not crash.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3586703/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3586704/crash.log)

Save
[horse mission test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3586700/horse.mission.test.zip)

**Comment by davidpwbrown** [comment]
Damn this one was stupid even for me.

I made all NPCs dismount before a mission starts, but if they arent mounted, it didnt return early from the dismount function and just continued on with a dead pointer.

Fix coming.
