### ISSUE TITLE
A new idea about a monster

### ISSUE THREAD

**Issue by howmokas** [CleverRaven/Cataclysm-DDA#33865]
When we use the id_science,the turret will disappear in the lab.how about  use it like that.when we use something like id_science in a building. it will create a  monster,i think it is a great though use in the mi-go lab .It sounds like the tickets before fight the boss

**Comment by ituluwituluwzev** [comment]
It would be more realistic to lock the monster behind a gate and open the gate with the card.

**Comment by howmokas** [comment]
Like the temple opened  need the eye，When I summon the death knight need other things.Maybe I win some magic material can be obtained
