### ISSUE TITLE
Enhanced Memory Banks power consumption is extreme

### ISSUE THREAD

**Issue by vlad1492** [CleverRaven/Cataclysm-DDA#33880]
# Describe the bug
Enhanced Memory Banks drains bionic power at a very high rate for moderately high-skilled characters. 
 Example: With a bunch of 8's and 9's  just about 100 bionic power is lost each hour.

# Steps To Reproduce

1. Make a player with EMB and some stored bionic power. 
2. Turn on skill rust. (I use INT)
3. Console some skills to level 8
4. Pass time 

# Expected behavior
Keeping memory and skill retained should not require vast energy. We are talking wetware engram archiving kept fresh.  Running an electric forge off a built-in UPS takes seven hours and costs 450 power.  The example survivor's head is drawing 150% the power of an electric forge.  I think the current cost to run EMB is 10PU every time it is triggered and it triggers a *lot*.   Perhaps reduce it to 1PU per trigger?

# Versions and configuration- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-7342-g1ac3bf9 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Bionic Slots [cbm_slots],
    Sleep Deprivation [sleepdeprivation],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    PKs Rebalancing [PK_REBALANCE],
    Arcana and Magic Items [Arcana],
    No Survivor Armor [no_survivor_armor],
    No Sci-Fi Equipment [no_scifi],
    Aftershock [aftershock]
]

**Comment by mlangsdorf** [comment]
There needs to be a general effort to rebalance the energy costs of CBMs.  Doing it piecemeal is not going to work very well.

**Comment by Fris0uman** [comment]
Fixed by #34456 ?
