### ISSUE TITLE
COntinue dissecting corpse despite canceling it or being interrupted.

### ISSUE THREAD

**Issue by ShinWinddreamer** [CleverRaven/Cataclysm-DDA#33890]
# Describe the bug

As the title says. I start dissecting a corpse. Zombie shows up and i successfully do cancel the action BUT as son as I do an action with a timer, say, for example, i dismember a corpse after i dismember that corpse it will automatically queue back to dissecting the cropse that has been previously attempted to dissect but been interrupted. That also applies when that corpse has been already dismembered. Then time starts ticking down for the dissection and after that it'll put up a message in the event log that the corpse hasn't been found.- It's an issue that plagues me for a while and killed me a few times as well.

# Steps To Reproduce

1.Kill someone

2.Start dissection (dunno how relevant tools are but in my case i use a scalpel)

3.Get interrupted or force interruption of mentioned dissection.

4.Perform an action after interruption has been dealt with like hauling items, dismember corpse etc. So far has worked for a platora of actions that triggered time to pass in 5 min ticks.

# Expected behavior

That the dissection doesn't continue on it's own volition.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-7375-g1fbbe0a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    DinoMod [DinoMod],
    EZ-Mode Medical [fast_healing],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Filthy Clothing [no_filthy_clothing],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by starytroll** [comment]
I had a similiar issue but didnt post it, as wasn't sure how to reproduce it. In my case it was quick butchery I think, with a makeshift/stone knife probably. Additionally it succeeded in a place far away from the corpse, teleporting the results to the tile I was standing at.

**Comment by ShinWinddreamer** [comment]
> 
> 
> I had a similiar issue but didnt post it, as wasn't sure how to reproduce it. In my case it was quick butchery I think, with a makeshift/stone knife probably. Additionally it succeeded in a place far away from the corpse, teleporting the results to the tile I was standing at.

yep, same here

**Comment by BaumgeistOne** [comment]
Has been happening for a while: #33250

**Comment by jarmush** [comment]
Yep, it's really annoying, any longtime action causes character to continue dissection that was interrupted before

**Comment by StevenLesseps** [comment]
I have this happening on experimental 0.E-6333-g7f98932 (tiles), build 11044. 

Tried to butcher a cow. All mods are in the base game, except undeadpeople tileset. 
Tools are meat cleaver, butchering rack built from * menu and tourist table nearby. 
butchered a cow for like 11 hours, got dead tired, very hungry and thirsty and when tried to interrupt it would continue anyways no matter what.

**Comment by Ramza13** [comment]
Just tried to reproduce this using steps in initial report and in post above me and couldn't.  If anyone has a save or additional steps that would be helpful.

**Comment by TealcOneill** [comment]
Was not able to replicate on latest version.
- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-03-0220 abe3f76 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by GuardianDll** [comment]
closed as resolved by #73610
