### ISSUE TITLE
Crash when trying to move toilet water with move all command in advanced inventory management

### ISSUE THREAD

**Issue by HeinousTugboat** [CleverRaven/Cataclysm-DDA#33906]
# Describe the bug

Game crashes to desktop when trying to move water with move the all command in advanced inventory management when trying  to move from All tab to the center  square.

# Steps To Reproduce

1. Make a missed shower survivor.
2. Find bathroom, stand beside toilet.
3. Open AIM, set left pane to `A` and right pane to `5`.
4. Hit `,`  while on left pane.
5. Game either crashes immediately (I believe if toilet water is the only item on the left) *or* crashes when you re-open the inventory manager.

# Expected behavior

I would expect it to do nothing, or at least produce some sort of error.

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14.6; Build: 18G95; 
- Game Version: 0.D-7411-g92a1956 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3588219/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3588221/debug.log)
[McKeesport.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3588222/McKeesport.zip)

**Comment by ZhilkinSerg** [comment]
I cannot reproduce it on latest experimental version, so it was supposedly fixed sometime in the past. Please ping if you still experience this issue.
