### ISSUE TITLE
Some way to change the name of an existing om_terrain

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#33914]
**Describe the solution you'd like**  
Being able to change an om_terrain's name would help with some more complex types of missions or map_gen updates.  

Missions pick either the nearest om_terrain or a random, one, but then there's no way to refer to that same random spot again.  So if you want to pick a random farm for mission-one, then that same farm again for mission-two, it's not possible.  But by changing the om_terrain to a unique name in mission one, it would allow you target it later on.  

Conversely, there are times you might want to forbid a spot from ever being picked again.  Like a mission update that changed a farm's terrain would ensure that for other unrelated missions it wouldn't ever pick that farm.  For something like a Tacoma Commune, you could upgrade a field , change the name, and then ensure that spot would not be available to be upgraded and overwritten.   

**Describe alternatives you've considered**  
Maybe some kind of system for flagging a space?  It would amount to the same thing, but would require that missions and dialog could check for the flags.

**Additional context**  
I have no idea how the map code works.  It could be changing om_terrain causes lots of problems.  I know it's used in some way basecamps, but those are just fields.  Changing tiles in specials or that are rotated might cause weirdness.

**Comment by ZhilkinSerg** [comment]
Overmap terrain name and id are different things. I am pretty sure you can refer to some unique id in mission definitions, but have terrain with this id same name as non-unique terrains.
