### ISSUE TITLE
fake targeting NPC vehicle turret calls itself that name in message log

### ISSUE THREAD

**Issue by Mooses2k** [CleverRaven/Cataclysm-DDA#33929]
# Describe the bug
Says 'fake targeting NPC is shooting at blah blah' in the message log. That looks daft.

# Steps To Reproduce
Affix a Cerberus laser turret and accompanying parts to a vehicle and set it to autotarget.

# Expected behavior
Say the vehicle fires or the weapon name fires, not 'fake targeting NPC'.

# Versions and configuration
Vanilla build from two days ago, no mods.

**Comment by anothersimulacrum** [comment]
Fixed by #34103?
