### ISSUE TITLE
Black Pudding's acid attack does 63 damage, not 8 as intended by KorGgenT

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#33938]
This is mainly a reminder for KorGgenT so he doesn't forget about this error...

Describe the bug
According to discussion on discord, the Black Pudding's acid attack should being doing minimum bio_acidicspray damage of 8. It delivers 63 instead.

# Steps To Reproduce
Get attacked by a Black Pudding without wearing acid resistant armor.

# Expected behavior
Per KorGgenT, the Black Pudding should only deal 8 damage because it's using a level 0 version of the spell.

# Screenshots
https://cdn.discordapp.com/attachments/365907426270117888/620947561053945896/1568115040.png

# Versions and configuration
Build 9610 ish w/ Magiclysm mod

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/65648005-90605480-dfce-11e9-85d6-1e3484f03aa1.png)
i'm not able to reproduce this with puddings or nothics.

**Comment by Malkeus** [comment]
I can't reproduce this anymore, either. Closing this one down.

**Comment by pulpfreewater** [comment]
Save file for KorGgenT. Slightly out of date save file, but getting big (150+) damage numbers from Mr.Nothic.

https://drive.google.com/drive/folders/1m-sqOoNEya0PHS1F22fIgSw6af1QsWyE?usp=sharing

**Comment by arijust** [comment]
Is it actually possible for monsters to gain levels in spells?
If that's the case, adding in max-level in monster spells could fix that.

**Comment by KorGgenT** [comment]
it is not

**Comment by arijust** [comment]
I see.
Too bad.

**Comment by KorGgenT** [comment]
spent some time trying to reproduce again today, with no luck. I am unable to load @pulpfreewater 's save because there are a bunch of third party mods and i'm not gonna go hunt them down.

**Comment by LaVeyanFiend** [comment]
Also cannot replicate
![image](https://user-images.githubusercontent.com/51099123/70959561-98b6b180-204a-11ea-9921-b156a7998635.png)
![image](https://user-images.githubusercontent.com/51099123/70959585-ab30eb00-204a-11ea-8af3-569ed8059564.png)

**Comment by KorGgenT** [comment]
https://drive.google.com/file/d/1PPflaZQZet9W7F7jnCd7VBHf1z4C6BVQ/view
I got another report with a save file attached today. i'm reopening the issue as I may not be able to get to this today but i want to keep track of it.

**Comment by KorGgenT** [comment]
so it's probably better if i just revisit how i wrote fake_spell::get_spell(). obviously there's something weird goign on there in the monster attack logic.
