### ISSUE TITLE
MP3 Player does not caution turning off before you sleep.

### ISSUE THREAD

**Issue by Ezsk** [CleverRaven/Cataclysm-DDA#33933]
**Is your feature request related to a problem? Please describe.**  
We often forget that turn off the MP3 player before you sleeping. It is very annoying. not only consuming batteries, but also it cause unaware of zombies attack.

**Describe the solution you'd like**  
The sleep menu screen should be note the MP3 Player is active. (eg. like a shooting earmuffs.)

**Additional context**  
Possibly, I think it's better to make “WARN_SLEEP" tag to the item flags. it whould be good for expansibility and helpful for third party mods.

**Comment by SYPIAC** [comment]
Sometimes I forget to do this in real life too, seems realistic.

**Comment by chriseich21** [comment]
Why does the mp3 player attract zombies? Normally you use that with earphones
