### ISSUE TITLE
Generic "I updated to build 9612 and now X is broken" Issue

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#33941]
Ok, so Build 9612 has tightened up the standards for json error enforcement. This is going to cause a lot of issues with various mainline mods. Rather than issues being reported randomly as encountered and possibly duplicated, lets collect them all here for now. A specific issue for each error reported can then be made. Please read all the comments to make sure your issue hasn't already been reported. If you know of a fix, include that as well, please.

I'll start us off with the one making the rounds in discord right now about 
CRIT Expansion Mod:

```
 DEBUG    : Error: data/mods//CRT_EXPANSION/crt_materials.json: line 14:22: Expected string
    "elec_resist": 20,
    "chip_resist": 9,
    "repaired_with": [
                     ^
                       "plastic_chunk", "chunk_rubber" ],
    "salvaged_into": "chunk_rubber",
    "dmg_adj": [ "ripped", "torn", "shredded", "tattered" ],
 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 843

```
It seems "repaired_with" only accepts a single material. Who knew.
Fix is to replace 
"repaired_with": [ "plastic_chunk", "chunk_rubber" ],
with
"repaired_with": "chunk_rubber",

Lets get these all together and fixed ASAP. Try to only report issues with mainline mods here. Custom mods will need to be reported to their respective authors and/or fixed independently (please share your fixes on [discourse](https://discourse.cataclysmdda.org/t/build-9612-broke-all-my-mods/21302)).
That's all for now.

**Comment by Hirmuolio** [comment]
#33940 fixes several of these.

**Comment by Malkeus** [comment]
Good, that is good. Hopefully all the errors will be fixed by the time I get off work later. Still, this will give the people in discord and discourse a place to point people who are continually asking the same question about the same error. Thanks for your efforts :)

**Comment by Malkeus** [comment]
We can continue this discussion over on the discourse forum...
https://discourse.cataclysmdda.org/t/build-9612-broke-all-my-mods/21302

https://i.imgur.com/K3wKBn2.png
