### ISSUE TITLE
Missing Library for arm64-v8a.apk

### ISSUE THREAD

**Issue by ElSticker** [CleverRaven/Cataclysm-DDA#33945]
# Describe the bug

Missing library for arm64 apk: libhidapi.so

# Steps To Reproduce

Update or install game on Android with  using cataclysmdda-0.D-xxxx-arm64-v8a.apk, open game, error message appears. 

# Expected behavior

Game installs and runs without issue on arm64 device.

# Versions and configuration

Device info in attached PDF
[DroidInfo.pdf](https://github.com/CleverRaven/Cataclysm-DDA/files/3597239/DroidInfo.pdf)

**Comment by ZhilkinSerg** [comment]
See #33899

**Comment by ZhilkinSerg** [comment]
Should be resolved now after #33899 is merged.
