### ISSUE TITLE
The Next Summer spawns huge piles of shit under wildlife

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33958]
0.D-7542-ga5d33f6e61-dirty

![](https://pstbin.ru/f/87437/)

**Comment by Xenomorph-III** [comment]
Poor things were constipated for a year. 

The cataclysm must have destroyed all the laxatives.

**Comment by int-ua** [comment]
Had this issue while updating an existing world to build 9532 (from build 9424 AFAIU from my files). This was one of the problems that got me too tired of experimental bugs. Had several cows and excrements overflown several tiles.
