### ISSUE TITLE
New versions of autonomous turrets drop far too much ammo.

### ISSUE THREAD

**Issue by Xion350** [CleverRaven/Cataclysm-DDA#33951]
Currently the new named turrets have far and beyond more ammo than they could ever need, which imbalances player loot by giving players thousands of rounds of ammo to use for relatively little risk.

**Describe the solution you'd like**  
The real life MAARS drone carries 450 rounds of ammunition and has (I assume) a similar profile to the turret in CDDA.  It could easily be reduced to this amount and still retain its deadliness.

**Describe alternatives you've considered**  
Ammo counts below 100 would be ideal balancewise, but the turret would quickly run out of ammo after a few bursts.

Alternatively it could be made more difficult to get the ammo by requiring to `D`isassemble the turret in order to recover the unspent ammunition.

**Comment by ymber** [comment]
The capacities used in cata are the real capacities of the M153 CROWS II for different rounds. For ammo on disassembly we'd have to set and track different item states specifically for this use case and that's more work than it's worth.

**Comment by Zireael07** [comment]
While I understand the desire to be realistic, I have to agree that it unbalances the game. Maybe have some of the ammo be unrecoverable from turrets for some reason (stuck/jammed), or indeed require some sort of a long action, to prevent just picking up loose ammo with enemies around.

**Comment by Firestorm01X2** [comment]
> Maybe have some of the ammo be unrecoverable from turrets for some reason (stuck/jammed),

Or simply add separate stats for dropping ammunition from turret.separate from ammo count.

**Comment by Xion350** [comment]
> Even if if real life analog has some stats game don't have to maintain that stats exactly (in most cases it is literally impossible). Especially if it is hurts game.

It wouldn't be too hard to imagine that the CROWS setup before the cataclysm wouldn't have the full 1600 rounds that they were deployed with.  Firing them at the zombies and personnel in the initial outbreak, then random passerbys as it sits there.  Always having near max ammo count is actually less realistic.

**Comment by Firestorm01X2** [comment]
But we are still talking in the closed issue.

It is better to ask @kevingranade  to double check closing desicion.

**Comment by Night-Pryanik** [comment]
I'll reopen.

**Comment by BaumgeistOne** [comment]
I don't know if this is possible, but I would suggest turrets spawning into the game with a random amount of ammunition, ranging from 0 to the maximum mentioned above.

**Comment by Ezsk** [comment]
I think this is a serious issue for the game balance but seems to have not been paid enough attention in dev.
for example in my playing game, I fetched over 6000 rounds 5.56mm ammo in the few days. it mean ammo is like infinity now.

The same problem will occur with "mon_crows_m240", "mon_turret_rifle", and "mon_turret_bmg".

I suggest the number to 1/10 like this. it is enough.
```
    "id": "mon_turret_bmg",
    "name": "M2HB autonomous CROWS II",
    "starting_ammo": { "50bmg": 40 },

    "id": "mon_turret_rifle",
    "name": "M249 autonomous CROWS II",
    "starting_ammo": { "556": 160 },

    "id": "mon_crows_m240",
    "name": "M240 autonomous CROWS II",
    "starting_ammo": { "762_51": 100 },
```

but I am not sure how to creating pull request...  anyone?

**Comment by anothersimulacrum** [comment]
I'm not a big fan of arbitrarily reducing their ammo from realistic amounts - I think there are better solutions to this problem, a few of such are below:

- Like it does in butchering, damage reduces yield (this time of ammo)
- Making turrets harder to kill - increase their ranges to be equivalent to the player, their night vision too
- Following that, making turrets return fire in the direction from which they were  last attacked, making them more dangerous

I'm sure there are more, these just popped up to me.

**Comment by Night-Pryanik** [comment]
> Following that, making turrets return fire in the direction from which they were last attacked, making them more dangerous

Oh yeah!

**Comment by Ezsk** [comment]
> Like it does in butchering, damage reduces yield (this time of ammo)

I agree if those solutions result in a reduce of ammo to around 1/10.
perhaps the problem is not difficulty, problem is amount of ammo.

I think the road blocking turrets is not a special place worth it more than an ammo depot. The turrets role is just a hindrance.

**Comment by Xion350** [comment]
> * Making them spawn with a random amount of ammo, say `[ 500, 1600 ]`

I'd love to see this implemented but I don't know if the JSONs support random ammo.  Like I said before it's highly likely Turrets have shot up a lot of their ammo already.

**Comment by Night-Pryanik** [comment]
> if the JSONs support random ammo.

I tried that. It doesn't work.

**Comment by Lamandus** [comment]
I think arbitrary reducing the ammo count isn't the right way of dealing with it. Rather ask, why is the turret nearly full ammo. If you are able to hack it, cuddos to you, because you have the tech to deal with it. EMP also should leave it with a high ammo count, but you need to get near of it.

So my "solution" would be: make the turret more deadly, let it shoot from far away at any moving target and it will deplete its ammo enough to have "non balance breaking ammo counts" if you manage to survive, that is.
But all turrets should get the same treatment. Spawn them with full ammo, let them make the work.
Also increasing their bullets per burst count would also do the trick.

**Comment by anothersimulacrum** [comment]
> Also when destoyed by force (shooting) it should catch fire

Why?

**Comment by Lamandus** [comment]
> 
> 
> > Also when destoyed by force (shooting) it should catch fire
> 
> Why?

malfunctioning electronic may lead to fires... especially when those turrets also have ammo which may explode. And that would actually deal with the ammo drop...
My knowledge is not that high about turrets, but tell me, how are those turrets powered?

**Comment by Ezsk** [comment]
I made a mod for myself that reducing ammo to 1/10. it could made in few minutes and good enough for the fix issue. I do not feel problem in the game balance now.

I wonder why devs leaving this issue for a long time.

**Comment by Night-Pryanik** [comment]
> I wonder why devs leaving this issue for a long time.

Because reducing ammo from one fixed amount to another fixed amount doesn't solve the problem.

**Comment by Ezsk** [comment]
Since implemented the CROWS turret, I can easy to clear the big zombies city. Also even science lab, it became a easy task becouse I can get an ammo like a infinity. This is the issue.
I do not want to get much yeld of ammo,  no matter how turrets is dangerous and how hard to recover ammo from his wreckage.
So, In my opinion, reducing ammo is only way.

Anway, I said what I want to say and my issue has solved by my own mod. so I will be quiet. I hope a logical and fair decide.
