### ISSUE TITLE
Any tool that relies on ammo_remaining() is turned unusable with UPS toolmod

### ISSUE THREAD

**Issue by ave-** [CleverRaven/Cataclysm-DDA#33968]
# Describe the bug

Any tool that relies on `ammo_remaining()` to count charges inside is turned completely unusable if UPS toolmod is applied to it.

# Steps To Reproduce

1. Create a player with UPS  or bionic UPS (commercial cyborg prof can be used to test this).
2. Spawn something like radio, multi-cooker, portable game, etc.
3. Spawn an UPS conversion mod.
4. Insert this mod into the spawned item.
5. Try to use it.

# Expected behavior

Tool should be able to rely on UPS charges.

**Comment by dunstad** [comment]
I did a quick look through iuse.cpp and as far as I can tell, these are the tools that should still be affected:

radio, lajatang, tazer, portable, vibrator, tablet, electric handcuffs, foodperson mask, autoclave, multicooker

If there could be other occurrences of this kind of bug outside of iuse.cpp, let me know. 

A few of those are a bit weird. I'm not sure why you would ever make the handcuffs or foodperson mask run off UPS, but I don't mind making it possible. I'm also not sure if there's any UPS with enough power to handle the autoclave, although I suppose the UPS CBM might work in theory.

**Comment by dunstad** [comment]
Here's how my initial investigation went:

- radio: can turn on without power, seems to prompt when deactivating?

- lajatang: fails to turn on

- tazer: appears to work fine...

- game: fails to turn on

- vibrator: appears to work fine...

- tablet: appears to work fine...

- handcuffs: don't appear to use magazine style batteries at all, can't be UPS modded

- foodperson mask: UPS modding the mask, wearing + activating it, then removing the battery from the UPS crashes the game

- autoclave: refuses to start, even when the UPS is using a heavy plutonium battery (10k charges)

- multicooker: refuses to start

**Comment by dunstad** [comment]
> If you install the UPS mod on your e-ink tablet, it cannot play songs.
Source: https://www.reddit.com/r/cataclysmdda/comments/dfprxk/i_think_im_finished/

**Comment by sick-trigger** [comment]
the electric firestarters nobody uses are also affected

This tool doesn't have enough charges.
You can't reload a electric firestarer+1 (UPS)!

**Comment by kenneth-ellis** [comment]
I'm trying to use my **firearm repair kit+1 (UPS)** to craft an Ergonomic Grip for a gun, but it's telling me it doesn't have enough "charges" even though my UPS has plenty of charges.
![ergonomic-grip-UPS](https://user-images.githubusercontent.com/37091572/115351583-3fddb880-a16b-11eb-9345-5456e99c3945.PNG)
