### ISSUE TITLE
It isn't possible to make curdling milk from reconstituted milk.

### ISSUE THREAD

**Issue by MichaelEricOberlin** [CleverRaven/Cataclysm-DDA#33969]
Curdling milk, a necessary component for making cheese (which, in turn, is a necessary component for a host of other recipes) can't be made from reconstituted milk.

Drying milk leads to powdered milk, which can then be made drinkable 1:1 with clean water as "reconstituted milk". However, even though it is quite possible in reality, reconstituted milk can't be used to make curdling milk and eventually cheese.

This means that once milk has been dried for the sake of preservation, it is far less useful to the player.

1. Grant powdered milk and contained water to player.
2. Craft reconstituted milk.
3. Attempt to craft curdling milk, and note that reconstituted is not among the necessary ingredients.

# Expected behavior

Preserved milk should be just as applicable to cheese making as fresh milk.

True as of version 0.D-9601.

- OS: Linux
    - OS Version: Distributor ID: LinuxMint; Description: Linux Mint 19 Tara; Release: 19; Codename: tara; 
- Game Version: 0.D-7375-g1fbbe0a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

**Comment by anothersimulacrum** [comment]
Thanks for making this! Fix incoming.
