### ISSUE TITLE
Throwing items QoL and bugfixes

### ISSUE THREAD

**Issue by zachary-kaelan** [CleverRaven/Cataclysm-DDA#33987]
**Is your feature request related to a problem? Please describe.**  
Trying any sort of "throwing build" is incredibly painful. 

- Throwing axes make 3 hours to make *each*, and throwing knives take 4 hours to make. 
- No armor in the game lets the player store these items.
- The player has to select the item each time they want to throw it.
- The player unequips what they're holding in order to throw something. *You don't need two hands to throw a knife.*
- With some of the "throwables", each weapon makes its own stack in the inventory, filling up the screen.

**Describe the solution you'd like**  
- Make the crafting recipe return multiple items, like with arrows.
- Allow various pieces of armor to store certain throwing implements.
- Automatically target certain items when throwing, with a hotkey to cycle between them.
- If the current wielded weapon is one-handed, allow throwing with the other hand.
- Make the throwing implements stack consistently.

**Describe alternatives you've considered**  
Personally, I think most of the magazine pouches and bandoliers should also be able to store throwing implements.

The automatic selection should obviously pick "thrown" ammo types first. Though currently, this ammo type doesn't display on the throwing implements in-game. It should probably prioritize throwing implements worn on the person first (in the cycle list), then ones in the inventory, *then* a few other items commonly used for throwing, like rocks. Perhaps your throwing skill could allow you to see which items are better for throwing.

Throwing items are also difficult to find in the crafting menu, so I think a new crafting subcategory should be added somewhere.

In addition to, or alternatively to, making magazine pouches compatible, make the throwing implements stack like ammo, so that you can wield a bunch of them at once. Basically like you're holding a bunch of throwing axes in one hand and throwing them with the other. 

If you're holding something with the other hand, throwing might still be slower. I'd say based on their strength and the weight of the item - also, dexterity and throwing skill, for fumbling with your hands. 

**Additional context**  
The "fire" command interface, for reference:
![image](https://user-images.githubusercontent.com/30245333/64786767-362ab280-d53d-11e9-945f-3fa90b121928.png)

Throwing implements not stacking:
![image](https://user-images.githubusercontent.com/30245333/64788674-f796f700-d540-11e9-80e6-58d2f72a90c2.png)

The throwing implements were changed from `AMMO` to `GENERIC` due to issue #32818 - the throwing acted like you were throwing the weight of all the items in the stack at once. If we wanted them to stack like ammo, some code changes would likely be required to make it work.

**Comment by jeremyshannon** [comment]
The recipes for axes and knives used to return a stack of them, not one. That definitely doesn't sound right.

**Comment by zachary-kaelan** [comment]
> The recipes for axes and knives used to return a stack of them, not one. That definitely doesn't sound right.

I checked the JSONs and it does actually have it set to return multiple. I think that just doesn't work with items of that type.
