### ISSUE TITLE
Esc key is being treated as the Home key with Bluetooth keyboard

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#33983]
# Describe the bug

Using the iClever Bluetooth keyboard, model [IC-BK03](https://www.amazon.com/gp/product/B00YWLJNPQ/ref=ask_ql_qh_dp_hza), pressing Esc forces the game to minimize instead of the usual Esc function.

# Steps To Reproduce

1. Use any physical keyboard on Android.
2. Press Esc.
3. If Esc works as intended, the issue is specific to the model [IC-BK03](https://www.amazon.com/gp/product/B00YWLJNPQ/ref=ask_ql_qh_dp_hza) iClever Bluetooth Keyboard.

# Expected behavior

The issue seems to be exclusive to the Android port, all keys are functional except for the Esc key in game. Without the Esc key working, I am forced to double tap my screen to close menus. Pressing "q" seems to work as a decent alternative to Esc, however, this does not work with every menu.

# Screenshots
![image](https://user-images.githubusercontent.com/50155659/64769082-a8d56700-d518-11e9-9aed-a23306bddc95.png)

# Versions and configuration

 - OS: Android 9
 - Game Version: 0.D-7560-g3fd9491
 - Graphics version: Tiles
 - Mods loaded: Same issue with or without mods

# Additional context

This particular model is compressed and has support for multiple operating systems, the Esc and Home key share a button. Using Fn+Q swaps to the Android function keys (Home), using Fn+W swaps to the Windows function keys (Esc).

After connecting the Bluetooth keyboard to my PC, I found that swapping between keyboard OS functions works as intended with no issues, the Esc key also works no problem in game.

Tested the Esc key on other Android applications and it works fine.

**Comment by ZhilkinSerg** [comment]
Should be resolved with #35625
