### ISSUE TITLE
Limit Visibility of Items on Dead Bodies

### ISSUE THREAD

**Issue by capSAR273** [CleverRaven/Cataclysm-DDA#33998]
**Is your feature request related to a problem? Please describe.**  
While moving around the world, it is too easy for a player to see the entirety of a tile's contents. There's a dead body, clothing, equipment, weapons, food, etc. All contained in one space, and the player should not have access to this information without searching the body first. Clearly visible items from 15 feet away for example would be weapons and worn clothing. Only upon further searching would the player find the rest of the smaller items. Currently I can run around a pack of zombies, and see every item on the ground from tiles away, allowing me to go for only the best items reducing the risk moving closer.

**Describe the solution you'd like**  
The number of items a player can detect from a distance away should be reduced, until the player moves to the tile and searches the body/pile. Worn items should be visible, but items that would usually show up inside bags or pockets should stay hidden until searched. This would apply to driving around also, it could be even stricter due to the speed of a vehicle making it hard to tell the items on the ground from a distance.

**Describe alternatives you've considered**  
Nothing has come to mind.

**Additional context**  
A "search in this area" action could be made to automate the searching, reducing the number of keystrokes needed. As a side note, the behavior of items on shelves, or found while looting buildings should remain the same. This change would only apply to bodies on the ground.

**Comment by VReaperV** [comment]
There's no way to distinguish if the items are actually on the corpse or if they were just lying around, unless something has changed recently. And there's no containers that would allow for that or for some other things, like dropping your backpack and not spilling the items on the ground.

**Comment by Nacarbac** [comment]
This would be an enormous change to difficulty and play style. It'd definitely be more realistic, but I think it needs to be a toggleable option if done.

Perhaps the visibility limit for a distant tile could be crudely determined by item volume vs Perception? Clothing and weapons getting a +mod to their effective volume. 
Then a scale of vagueness. "There's something here", "Unidentified gun", "Many shinies".

**Comment by nshcat** [comment]
I personally also think that this should be something that the player can toggle on or off. It's just a huge change to the established gameplay.

**Comment by capSAR273** [comment]
> There's no way to distinguish if the items are actually on the corpse or if they were just lying around, unless something has changed recently. And there's no containers that would allow for that or for some other things, like dropping your backpack and not spilling the items on the ground.

Something Kevin mentioned was that on a monster's death the items are spawned, so we would know which ones are from a recently dead body and ones that are just lying around the world naturally spawned.

**Comment by kevingranade** [comment]
An action that you can trigger to search all the corpses in in an area on autopilot is a prerequisite for adding this feature but on the other hand I have no interest in adding an option for it, it's just the way things will work

**Comment by BaumgeistOne** [comment]
Maybe don't spawn the items until the body is searched. Or spawn only clothes at the time of death and spawn other items only if the body is searched.

**Comment by VReaperV** [comment]
> Maybe don't spawn the items until the body is searched. Or spawn only clothes at the time of death and spawn other items only if the body is searched.

Spawning items at the time of search is a bad idea, as it may introduce a lot of bugs. If, for example, there's a highly flammable item there, it should be spawned if that time catches fire. Explosives would need to, well, explode, under certain conditions. Searching is not the only action that interacts with those items.
