### ISSUE TITLE
Bike colliding with errors in movement code

### ISSUE THREAD

**Issue by reed501** [CleverRaven/Cataclysm-DDA#33994]
# Describe the bug

Duplicate of #23000 but it's been awhile and I might have more information.

I attached my bike to my solar car with bike racks and drove it really far. When I arrived at my destination I tried taking my bike off the rack and moving it. I initially grabbed the front of the bike and tried pulling it toward the front of the vehicle and getting "The bike collides with errors in movement code." I got this same error pulling it SW and S. Then I tried grabbing the saddle and pulling it S and SW and got the same error. It worked fine when I grabbed the back wheel and pulled it E.

# Screenshots

![Screenshot 2019-09-12 at 14 59 57](https://user-images.githubusercontent.com/12606597/64824433-d816c300-d56e-11e9-9e68-8398be8e0fcd.png)

# Versions and configuration

 - OS: ChromeOS 76
 - Game Version: 0.D-7343-g833e52d
 - Graphics version: Tiles
 - Mods loaded: None

**Comment by Night-Pryanik** [comment]
Moved your info to #23000.
