### ISSUE TITLE
You can stab things one z level above you even if there is a floor in between.

### ISSUE THREAD

**Issue by Bejofo** [CleverRaven/Cataclysm-DDA#34005]
# Describe the bug

I was trying to stab a few pesky rats in the sewers and spamming the f key when I noticed an odd message.  
"You fake a strike at the zombie cop".
There was no zombie cop anywhere in sight.

I was wielding a rifle with a combat knife attached, so I think this only works with polearm weapons.
# Steps To Reproduce

1.Enter sewer with a polearm.
2.Press f then < to target something above ground. 
3.Fire.

# Expected behavior

Not being able to hit things above ground.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-7358-gecc4826 [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Hydroponics [hydroponics],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Monsters [Only_Wildlife],
    No Spiders [No_Spiders],
    No Bees [No_Bees],
    No Ants [No_Anthills],
    No Fungal Monsters [No_Fungi],
    Whitelist [Whitelist] (Custom mod, but I fairly sure it wouldn't have broken this),
    Manual Bionic Installation [manualbionicinstall],
    No Filthy Clothing [no_filthy_clothing],
    Classic Roguelike Classes [RL_Classes],
    Classes and Scenarios Mod [more_classes_scenarios],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context

It was nighttime, I had full night vision as well as infrared vision. Using the aiming menu I could see things above ground even though I was in the sewers.

**Comment by SYPIAC** [comment]
Same for targeting things below you - you can fight zombies a level below by standing in a window and pressing tab/f or by pressing tab while standing on top of a stairway(which prevents enemies from going up).

**Comment by Nacarbac** [comment]
I think the bug here is more that you could percieve the target rather than attempt to stab it. Perhaps Infrared Vision is the culprit here? 

Thanks for the tip about stair-blocking enemies. That'll save some annoyance - and might be something worth adding to the message "...blocking the stairs! Try stabbing them with 'tab' or a reach weapon!".

**Comment by Aloxaf** [comment]
This bug seems to have been fixed -- you can't use `>` or `<` to switch z-level when aiming now.

**Comment by kevingranade** [comment]
You can still do that if 3d vision is enabled.

**Comment by anothersimulacrum** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/48245?
