### ISSUE TITLE
Bad_alloc/Seg fault after leaving base area

### ISSUE THREAD

**Issue by CodyHiltz** [CleverRaven/Cataclysm-DDA#34008]
Game version: #9622

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: N/A

### Expected behavior:

Driving around the map, or walking to new areas.

### Actual behavior:

After a certain distance of new tiles being rendered the game crashes with a bad_alloc/seg fault. noticed less memory usage with versions after #9610, the last version that doesn't contain the crash. It's acting like its running out of memory but my usage doesn't go passed 3.5gb and i have 12gb. version that works uses around 1gb more.

### Steps to reproduce the behavior:

Hop in a car and drive less than 250 turns away (always crashes before my autosave limit kicks in) usually i just drive down the road NW to make it happen, which it always does, but any direction will eventually cause it to crash.

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3610240/save.zip)

**Comment by ZhilkinSerg** [comment]
Are you using 32 bit or 64 bit executable?

**Comment by CodyHiltz** [comment]
well, that's embarrassing. 

I'll take this opportunity to thank for the reply and for continuing to update and support the game guys :)
