### ISSUE TITLE
Cursor moves two steps at a time while enabling "show all" in map editor

### ISSUE THREAD

**Issue by Aloxaf** [CleverRaven/Cataclysm-DDA#34000]
# Describe the bug

While enabling the "show all" option in the map editor, the cursor (with an 'X') will move two steps at a time, but the real cursor moves one step.

# Steps To Reproduce

1. Open the "Debug Menu".
2. Switch to the "Map editor".
3. Press "v" to enable the "show all" option.
4. Move you cursor
5. You will find the "X" move two steps at a time while the real cursor moves one step at a time.

# Expected behavior

The cursor moves one step at a time.

# Screenshots

![图片](https://user-images.githubusercontent.com/17017672/64837594-d2c68080-d621-11e9-9042-5fab404cb6bc.png)

# Versions and configuration

 - OS: Arch Linux
 - Game Version: 0.D-7578-g801a2925b3
 - Graphics version: Terminal
 - Mods loaded: [ "dda",  "no_npc_food" ]

# Additional context

0.D works well.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6416.
