### ISSUE TITLE
Hotkey conflict with "edit furniture" and "pan up-right"

### ISSUE THREAD

**Issue by Aloxaf** [CleverRaven/Cataclysm-DDA#34003]
# Describe the bug

In the map editor, both "edit furniture" and "pan up-right" use "u" as the hotkey, which causes confliction.

# Steps To Reproduce

1. Open map editor from debug menu.
2. Press 'u'
3. Sometimes it will open "edit furniture" menu, but at the most time it do the "pan up-right" action.

# Expected behavior

Considering that "pan up-right" is also useful in map editor, "edit furniture" should be assigned to another hotkey.

# Screenshots

![图片](https://user-images.githubusercontent.com/17017672/64843097-c0a30d00-d636-11e9-9c74-a8983464b3cd.png)

# Versions and configuration

 - OS: Arch Linux
 - Game Version: 0.D-7578-g801a2925b3
 - Graphics version: Terminal
 - Mods loaded: [ "dda", "no_npc_food" ]

**Comment by Aloxaf** [comment]
Related PR: #33619

**Comment by Night-Pryanik** [comment]
Just FYI, there's no need to open an issue if you already have a PR that fixes it.

**Comment by Aloxaf** [comment]
@Night-Pryanik Thanks for your advice.
I opened this issue because I thought I can't fix it at first -- my editing of `keybindings.json` make no effect. 
But soon I found it is because I had edited the default keybindings, so I need to delete `./config/keybindings.json` to let the new keybinding take effect.
