### ISSUE TITLE
Kitchen unit doesn't allow filling containers from tanks

### ISSUE THREAD

**Issue by reed501** [CleverRaven/Cataclysm-DDA#34016]
# Describe the bug

Attempting to refill your container with your vehicle tank's water from the kitchen unit results in "There is not enough clean water left to siphon it." I have 15L of clean water in my tank. I can 'd'rink from the unit just fine but not fill up my bottles with it. 

# Steps To Reproduce

1. Fill a vehicle tank with clean water
2. Attach kitchen unit in same vehicle
3. Attempt to (c) fill your container with clean water

# Expected behavior

The kitchen unit siphons water to your container with the normal liquid - container dialog. Also would be nice if you could use reload to do it as mentioned in #30229.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 9.11 (stretch); Release: 9.11; Codename: stretch; 
- Game Version: 0.D-7582-gc2913a1 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]

**Comment by adamkad1** [comment]
Apparently none of the kitchen vehicle parts work in this accord, i tried foodco and aftershock buddy, but none of them worked, not even when they were installed on same tile as tank

**Comment by BaumgeistOne** [comment]
Sounds like #33648
