### ISSUE TITLE
Lost skill level while actively using skill

### ISSUE THREAD

**Issue by Malorn-Des** [CleverRaven/Cataclysm-DDA#34019]
# Describe the bug

It would appear that practicing skills does not always prevent skill rust in all cases, or reset the related timers for having 'practiced' a skill. Using the setting for Int based rust, my character lost a skill rank in fabrication while actively engaged in a activity using that skill, interrupting the construction attempt. (Said skill, fabrication 5, had only been gained earlier that day.)

I am assuming that 'practice' is only given at the end of a task, as part of the completed item. This does make sense from a coding perspective, but it can lead to frustrating outcomes.

# Steps To Reproduce

1. Load a character with skills, with skill rust turned to 'Int'
2. Attempt a crafting activity which takes a long time, continue until you roll poorly.

# Expected behavior

I would expect that I would not lose a skill while actively using that skill. Since I am actively practicing the skill at the moment that I lost the rank, that would logically be 'practice'.

# Versions and configuration

<!-- Please complete the following information; you can now go to:
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-7603-g1b96ad1 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Malorn-Des** [comment]
Just a note, the exact same thing happened a second time, still on the same project (A rock forge). Just how fast does a skill become 'unpracticed'? Shouldn't it be at least a day after it was last used?

**Comment by Malorn-Des** [comment]
Third time, exact same thing. Same project, a rock forge. Elapsed time roughly one hour in-game between gaining level 5 in fabrication, and losing it while trying to build a rock forge.

![image](https://user-images.githubusercontent.com/46245363/64903385-84e36400-d685-11e9-868b-507e08539c41.png)

You can see in the log where the skill was gained, and when it was lost.

**Comment by Szara-ManOfHonor** [comment]
Skill rust was apparently never updated to the new 1 second turns, which is a shame because it otherwise works alright. Skill rust code is located in skill.cpp, if you know C++ it should be a fairly simple fix. Unfortunately I don't know C++ well enough to make a pull request myself.

**Comment by Malorn-Des** [comment]
Thank you very much for the information, that does sound like the problem. Sadly my skill with C++ is...not as good as I would like. I'll take a look and see if I can figure it out, but I don't have much hope.

**Comment by Malorn-Des** [comment]
Yeah, it is possible to gain and lose skills remarkably rapidly at the moment.

![image](https://user-images.githubusercontent.com/46245363/64945843-80fb4180-d83f-11e9-9c38-b0ee6a7bd7ec.png)

My current record for gain and loss, all of it happened in a single crafting attempt.

**Comment by snipercup** [comment]
I can produce the following result:
![image](https://user-images.githubusercontent.com/50166150/66004501-49300300-e4a9-11e9-9c41-80ab458e9176.png)

I just waited for days.
This is cataclysm vanilla skill rust turned on in debug menu in options. If we assume skill rust was not updated after the 1 second turn change, it should take 6 times as long?
