### ISSUE TITLE
Sponge requirement messes up wilderness settings

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#34010]
# Describe the bug

You got filthy glasses from a zombie. How do you clean it? Ofc you have to reach that city full of walking dead and search multiple houses for sponges instead of grabbing a random rag or scrubbing dirt off manually!

0.D-7603-g1b96ad13c5-dirty

**Comment by anothersimulacrum** [comment]
Feel free to add a hand crafted alternative to a sponge - the only reason sponge are the thing with this role are because rags already have a use action.

**Comment by tenmillimaster** [comment]
Wood scrub brushes, withered plants for moss, that sort of thing?

**Comment by l29ah** [comment]
Probably soap could be activated to wash things at 50% efficiency w/o sponge or washboard.

**Comment by l29ah** [comment]
OTOH i find the current soap rate of use too high.

**Comment by anothersimulacrum** [comment]
Fixed by the ability to use rags as sponges?
