### ISSUE TITLE
Mobile 0.D freezing on startup.

### ISSUE THREAD

**Issue by TheHopelessThrumbo** [CleverRaven/Cataclysm-DDA#34025]
# Describe the bug

I installed the Stable 0.D Android version, removing the old Play Store release completely. Running it doesn't change the screen orientation, and the screen remains black. A while later, the "App not responding" prompt comes up, dismissing it has no effect.

# Steps To Reproduce

Run the Stable 0.D version installed from .apk, on Samsung Galaxy Grand Neo, or respective device with Android 4.1.2

# Expected behavior

The game should boot up, giving the "Installing game data" popup, showing the progress of extracting game files to public storage, just like in 0.C build available in Play Store

# Screenshots

Not necessary, as it would feature the black screen and notification bar solely.

# Versions and configuration

 - OS: Android 4.1.2
 - Game Version: 0.D Stable, can't take the exact number for obvious reason
 - Graphics version: Tiles
 - Mods loaded: None, clear install

# Additional context

None, except for the fact the 0.C release worked flawlessly since the start.

**Comment by TheHopelessThrumbo** [comment]
Unpacking the files manually does nothing, and according to Task Manager, the game is stuck on 5MB of RAM and single CPU core loaded entirely. (25% usage all the time)

**Comment by ThomasLinkin** [comment]
as long as i can remember, the minimum OS you need to provide is 4.1.2 .

**Comment by TheHopelessThrumbo** [comment]
Current version on this device is 4.2.2, API Level 17.

**Comment by Night-Pryanik** [comment]
I guess this could be closed, as 0.D. isn't the latest stable on App Market. If the issue still exists, ping me so I will reopen it.
