### ISSUE TITLE
Tanning Leather Hide Recipe Missing

### ISSUE THREAD

**Issue by Dwane0Loki** [CleverRaven/Cataclysm-DDA#34023]
# Describe the bug
The recipe for Tanning Leather Hide "naturally learned" from gaining  3 survival and 2 cooking has disappeared.

# Steps To Reproduce

1. Make a Naturalist who should already have the recipe by default based on their starting stats 
2. Cheak your crafting menu
3. Note that the recipe for tanning pelts is there but not tanning hide

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-7610-gfaa20d1 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by LaVeyanFiend** [comment]
Cannot confirm on latest experimental.
![image](https://user-images.githubusercontent.com/51099123/64908938-981d2080-d6d3-11e9-9bf4-89579f43a3a2.png)

**Comment by Dwane0Loki** [comment]
Found out what I messed up in the report

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-7610-gfaa20d1 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    More Survival Tools [More_Survival_Tools],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]
I had the wrong world loaded up when I made the debug report

I.E I think this is a problem with more survival tools.

**Comment by kevingranade** [comment]
MST is unmaintained, use at your own risk.

**Comment by DalenTalas** [comment]
Requesting this issue to be reopened. Can confirm, character with 8 food handling and 5 survival is missing the tanning recipes.

Screenshot includes the results of the search for "c:raw pelt" in the crafting menu.

![image](https://user-images.githubusercontent.com/74809740/102036002-ce8e9300-3d8f-11eb-8598-3e0a16126d9a.png)

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8177-gaa9f4f8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by anothersimulacrum** [comment]
The recipe requires applied science 1 and survival 1 to autolearn.
