### ISSUE TITLE
Consistent crash/segfault on opening character info panel with scaling on

### ISSUE THREAD

**Issue by SeanMirrsen** [CleverRaven/Cataclysm-DDA#34047]
Opening the '@' character info panel with 2x scaling results in a crash.

Steps To Reproduce -
Set scaling factor to 2x in graphics settings.
Start or load a game and attempt to open the '@' character info panel.
Game immediately crashes, with or without displaying the crash info window.

Additional context -
I have a specific font setup, which I considered a possible factor, but the behavior persists despite reverting to standard fonts. The crash occurs regardless of renderer mode, window size, scaling mode, and fullscreen state, so long as the scaling factor is not 1x.

Versions and configuration -

(I was unable to find the debug menu. Activating debug mode made no difference. Do I need a debug build?)
Version is 0.D-8574-Win64-Tiles
OS: Windows 8 x64
Mods: cdda, simplified nutrition, no NPC needs, filthy clothing, vehicle parts pack, no flaming weapons

Relevant files:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3613422/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3613423/crash.log)
[Eagle Butte.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3613424/Eagle.Butte.zip)

**Comment by ZhilkinSerg** [comment]
> (I was unable to find the debug menu. Activating debug mode made no difference. Do I need a debug build?

You need to configure keybinding "Debug menu" to enable full debug menu.

**Comment by ZhilkinSerg** [comment]
Game does not crash for me on current `master`. Please try to reproduce on latest experimental version found [here](https://github.com/CleverRaven/Cataclysm-DDA/releases). If it is ping me here and attache your `config` folder (especially `font.json` and `options.json`).

**Comment by SeanMirrsen** [comment]
Alright, aside from moving font sizes into main config and thus needlessly complicating migration and distribution of hybrid tilesets, the latest experimental does indeed no longer have the crash, either with default fonts or my own mix.

Going to have to open a suggestion to re-enable loading font parameters from fonts.json, 'cause the game threw me for a bit of a loop, I almost thought bitmap font scaling was broken.
