### ISSUE TITLE
More decorative objects and curiosities to find and create.

### ISSUE THREAD

**Issue by DanteTorn** [CleverRaven/Cataclysm-DDA#34049]
**Is your feature request related to a problem? Please describe.**  
I feel it would add more flavor and realism if there were more non-practical objects in the game. Humans are sentimental creatures. We collect souvenirs, toys, pretty things.

**Describe the solution you'd like**  
We should add more objects such as theme park souvenirs, statues, toys, etc.

**Describe alternatives you've considered**  
Adding these items will bloat the game with more useless items, but we already have golf score pads, statues, standing mirrors, etc so this shouldn't be an issue.

**Comment by Maddremor** [comment]
On the creation side, you could carve wood figurines or something. Perhaps use a pen and paper to create generic-ish scetches.

**Comment by snipercup** [comment]
I tried to make one a souvenir but I could only think of one.
    
    {
        "id": "stuffed_animal",
        "name": "stuffed animal",
        "name_plural": "stuffed animals",
        "type": "GENERIC",
        "description": "A cute stuffed animal.  Probably cherished by its previous owner.",
        "copy_from": "basketball",
        "snippet_category": [
            { "id": "stanimal1", "text": "It has the shape of a giraffe.  Mostly brown with dark brown spots." },
            { "id": "stanimal2", "text": "Looks like the mascotte of a theme park." },
            { "id": "stanimal3", "text": "Looks like it was hand-made with a lot of love." },
            { "id": "stanimal4", "text": "It is actually kind of creepy.  It would take a spacial kind of person to love this." },
            { "id": "stanimal5", "text": "It has the shape of a blue dog.  It is missing its tail." }
        ]
    },

There is a itemgroup called toy_box but it does not contain an actual useless toy. You can make a toy similar to the above:
```
    {
        "id": "generic_toy",
        "name": "toy",
        "name_plural": "toys",
        "type": "GENERIC",
        "description": "Some kind of toy meant for kids.  It does not have much use nowadays.",
        "copy_from": "basketball",
        "snippet_category": [
            { "id": "gentoy1", "text": "Looks like a small car.  It has a red color and a smiley face on the front." },
            { "id": "gentoy2", "text": "Shaped like a human female. It was made to wear different clothes." },
            { "id": "gentoy3", "text": "If you place the tip on a flat surface and spin it, it will keep spinning untill it eventually topples over." },
            { "id": "gentoy4", "text": "Looks like a pink-colored slide.  Seems like a part of something bigger." },
            { "id": "gentoy5", "text": "Looks like someone's hero. You can bend the arms and legs to give it different stances." }
        ]
    },
```


If you have any inspiration, please add on to the above examples and I'll create the items to be added in-game.
