### ISSUE TITLE
Liquid transfer problem with aftershock kitchenmaster buddy

### ISSUE THREAD

**Issue by adamkad1** [CleverRaven/Cataclysm-DDA#34043]
# Describe the bug
It seems aftershock kitchenmaster buddy has a problem, when i try to drink from it, its fine, but when i try to transfer to container it says 'there is not enough clean water left to siphon it', which makes me think its trying to transfer water from its storage, not vehicle tank
Foodco doesnt work either

# Steps To Reproduce

Step 1- Examine kitchenmaster buddy and try to fill your canteen/waterskin/whatever
Step 2- error, there is no water!

# Expected behavior

Being able to fill my water container with water

# Screenshots

https://i.imgur.com/B4KkgGl.png

# Versions and configuration

0.D-7611-g21453a9

**Comment by Night-Pryanik** [comment]
I guess the culprit is the same as in #34016.

**Comment by adamkad1** [comment]
Huh, maybe they should switch their title to 'cant fill containers from vehicle kitchens' and i could close this. Also maybe i should try out buddy and see if it still works

**Comment by BaumgeistOne** [comment]
Sounds like #33648

**Comment by adamkad1** [comment]
thats even older... wow
