### ISSUE TITLE
fire drills take zero time to activate fire-dependent items

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#34063]
# Describe the bug

Even though it still takes a lot of time to set a piece of tinder on fire.

# Steps To Reproduce

1. Load the game.
2. Note the time.
3. Light either a candle or some furniture nearby.

# Expected behavior

Fire drill taking same time to use.

# Versions and configuration

0.D-7657-g3648a54071-dirty
[2019.09.16.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3616287/2019.09.16.zip)

**Comment by snipercup** [comment]
Cannot reproduce
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-8100-g334b20b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by l29ah** [comment]
Re-tested on a fresh master. A furniture consumes a few minutes as expected, a candle still consumes no time.

**Comment by Night-Pryanik** [comment]
Tested on latest experimental as of April 11 of 2021. Got a fire drill and a candle. Lit the candle, it consumed 3 seconds. 
@l29ah could you please retest?

**Comment by l29ah** [comment]
3 seconds is tiny compared to the time it takes to create fire with a fire drill, must be a bug.

**Comment by actual-nh** [comment]
Very small fires seem to be a difficulty in other ways - see #48466, for instance.

**Comment by Night-Pryanik** [comment]
> 3 seconds is tiny compared to the time it takes to create fire with a fire drill, must be a bug.

I'm not sure if it's a a bug.
Time cost of using firestarters, fire drill included, is based on flammability of items we're trying to light. Candle is considered very flammable, so we're using `moves: 500` field of `firestarter` `use_action`. For comparison, `moves_slow` field (used for hard to light items) has value of `25000` moves.
So we probably need to increase fast lighting (with `moves`) to something more sensible for a fire drill. On the other hand, directly consuming `moves` of a character makes him unresponsive and uninterruptible to all stimulus, and 500 moves is probably a maximum for such actions. Anything more should be converted to interruptible long actions, which is, of course, more work to do.
