### ISSUE TITLE
Zombies stand on zombies' heads

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#34067]
# Describe the bug

When a zombie falls down a level and stays there, another zombie can use it as a bridge and even fight while being on top.

[2019.09.16.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3617860/2019.09.16.zip)
0.D-7657-g3648a54071-dirty

**Comment by Nacarbac** [comment]
Pretty sure that's deliberate. And, if it isn't, I think it's a bonus feature - I was dumping mall zombies through a skylight, and was surprised to find that I'd piled them up so high they spilled back over onto the rooftop.

Then I tried testing to see if it meant I could run across the zombie pile myself, fell into the middle of it and was promptly eaten.

**Comment by kevingranade** [comment]
Not a bug, but also not necessarally ideal.
You cannot place two monsters in the same tile, so the resolution in place now is that a monster cannot fall into a square already occupied by another monster.

I recently came up with an idea for this, which is to have zombies trample each other, trampled zombies would turn into items on the ground that can turn back into a monster once the monster standing over them moves away.
