### ISSUE TITLE
error, zombie spawns on top of you (and many others)

### ISSUE THREAD

**Issue by FONZACUS** [CleverRaven/Cataclysm-DDA#34060]
# Describe the bug

in the included save, a feral runner will spawn on top of you (and more around). when lucky (finding bugs) it will also throw an error. not 100% reproducible though. im pretty sure the error relates to zombies and not wildlife.

# Steps To Reproduce

1. watch a runner spawn on top of you
2. reload a few times if hoping to find the bug

# Expected behavior

this tile aint big enough for the both of us

# Screenshots

would be easier to play test IMHO.

# Versions and configuration

(wandows 10 x64 with tiles x32, id rather have cdda crash)

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-7657-g3648a54 [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Abbe.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3614535/Abbe.zip)

sample error message
`src/creature_tracker.cpp:74 [bool Creature_tracker::add(monster&)] add_zombie: there's already a monster at 11,107,-1`

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed for more than a half-year.
