### ISSUE TITLE
Fishing rods reqiure no ammo (fish bait)

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#34085]
To use a fishing rod all you need to do is press "a" near water and your good to go.
If you want to use a fish trap you need bait as well which I think we should do for fishing rods also.

I wont go into to much detail here as it realy is not reqiured for this issue.

Thanks again to all that contribute you are awesome

**Comment by Qrox** [comment]
There is (fly fishing)[https://en.wikipedia.org/wiki/Fly_fishing] that only requires an artificial lure instead of live bait. Probably we can implement both.

**Comment by stk2008** [comment]
that would be awesome :).

P.S

I did add

"max_charges": 1,
"charges_per_use": 1,
"ammo": "fish_bait",

this made it so I had to load the rods up which was great but the problem was even after catching a fish the activity never stopped nor did the bait get removed.

I am no programmer ETC so not sure what else to do but was pretty chuffed I got it to even reqiure bait :P

**Comment by l29ah** [comment]
I never succeeded to catch anything using a fishing rod so i guess it's realistic :)

**Comment by Qrox** [comment]
From my experience there have to be actually some fish nearby for you to catch them.

**Comment by davidpwbrown** [comment]
Having no visible fish nearby severely reduces chances.
Having high survival skill and a pro rod helps significantly.

**Comment by scanevaro** [comment]
Fishing Rod should consume a Fish Bait every once in a while, though the player should have at least 1 Fish Bait in order to start fishing.

Also, for another issue/ticket, focus should hinder fishing when getting low.

**Comment by Proxiehunter** [comment]
In real life it's possible to catch fish on a bare hook. Bait makes it much easier though.
