### ISSUE TITLE
Graphical problem with steerable wheels.

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#34098]
Before there were two types of wheel in the wehicle. Steerable and non steerable.
That fact allowed tileset artists to make normal looking bikes and motorcycles by drawing controls on the steering wheel as it usually in the front. Now we do not have it, we only got steerable hubs, which are always under the wheel, so that make any bikes to look like two wheels and a seat without controls.
It would be great if some sort of solution would be implemented which will allow me to draw wheels on steerable hubs differently from wheels what are not on steerable hubs.

**Comment by int-ua** [comment]
Fixed by #46889
