### ISSUE TITLE
Allied NPC from an old game gets angry for no reason

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#34092]
# Steps To Reproduce

1. Load the save from https://github.com/CleverRaven/Cataclysm-DDA/issues/32809#event-2644602248
2. Wait a turn.
3. The NPC gets angry and proceeds to attack you.

# Versions and configuration

0.D-7691-g2e55fbb46d-dirty

**Comment by ZhilkinSerg** [comment]
Duplicate of #34084

**Comment by ZhilkinSerg** [comment]
Should be fixed in #34090
