### ISSUE TITLE
Smoking rack converts fried seeds into fried seeds

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#34104]
# Describe the bug

Put some in, add charcoal, light it, wait for it to finish, observe no change except the wasted charcoal. If it doesn't do anything useful to fried seeds, it shouldn't accept them like it does for everything else.

0.D-7718-g3040792b6b-dirty

**Comment by ZhilkinSerg** [comment]
Probably some flag inheritance problem.
