### ISSUE TITLE
Equipment still transferred to other faction

### ISSUE THREAD

**Issue by reed501** [CleverRaven/Cataclysm-DDA#34114]
# Describe the bug

See Issue #34084 and PR #34090 
The original issue was an error screen and transferred ownership of all things. After this PR on first load everything is happy. Then you save the game and leave, still normal. But then you open the game back up and load your save and now there's no error but everything is owned by the free merchants again. Subsequent loads are the same, only the first load works.

# Steps To Reproduce

1. Move your save to build 9638 or later
2. Load your save and have everything work normally
3. Quit and reload to have ownership change

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 9.11 (stretch); Release: 9.11; Codename: stretch; 
- Game Version: 0.D-7721-gc7937c3 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by ZhilkinSerg** [comment]
Which build you are moving your savegame from to build 9638? Can you upload it somewhere?

**Comment by RDru** [comment]
I can confirm this exists. I'm using 9634 but when I change to 9638 or later my car and all equipment in it changes to Hub001 faction.

**Comment by reed501** [comment]
[My save. Not sure which build.](https://drive.google.com/file/d/132-2SmiuY4SCCTgUnef5VlBK9SjFmp4i/view?usp=sharing)
