### ISSUE TITLE
Reproducible NPC crash

### ISSUE THREAD

**Issue by Dunkhan** [CleverRaven/Cataclysm-DDA#3411]
I have a crash to desktop issue which I believe to be caused by an NPC. I am unable to investigate it myself as I can't get the build to compile in VS. I will supply my save files and config in case anyone is interested in investigating it. 

Link to save: http://www.gametheatre.org/Cataclysm_Crash.rar

To reproduce:
Load the save
Walk south

There is an npc to the south and whenever I try to approach him the game crashes.

This issue was experienced on Cataclysm 0.8 "Romero" with the Hoder tileset

**Comment by qbradq** [comment]
As this issue is based on a very old save file, can we please close it?

**Comment by Dunkhan** [comment]
Yes, this issue is made obsolete by extensive changes to the NPC system. It was reported to help diagnose issues while those changes were being worked on. 

Closing
