### ISSUE TITLE
Let the crafted object have different durability.

### ISSUE THREAD

**Issue by Aloxaf** [CleverRaven/Cataclysm-DDA#34123]
**Is your feature request related to a problem? Please describe.**  
The crafting system is still too easy in some aspect:
1. The crafting time is too short for some object.
For example, [compound bow](https://www.google.com/search?tbm=isch&q=compound%20bow): I don't think anyone can make it from materials like "scrap metal" and "plastic chunk" within 4 hours. (Though it's not as powerful as a real-life one.)
But this is not the problem this feature plan to solve.
2. The player is too ...... good at crafting? I don't know how to describe it. 
Still take the compound bow for example: Maybe, a clever guy can make it within 4 hours. But in most cases, it's quality will not be as good as a factory-made one.

**Describe the solution you'd like** 
The durability of the object (mainly weapons and clothes) player crafted is depended on skill level, tool quality, mood or focus. 
In most case player won't craft a complex object which has the same durability as a factory-made one. 

Considering that an object can be repaired easily, which will make this feature less significant. 
A simple solution is to set the time for repairing action longer. But I prefer to set max durability for object: if an object is crafted with low durability, it can't be repaired to become higher. The player can only be disassembled it and craft a new one.

**Describe alternatives you've considered**  
I have considered adding some other modifiers to describe the quality of an object.
eg. "a shoddy compound bow", "a well-made compound bow". And the weapons/clothes with different modifiers will have different damage/armor.
But this may be a little complex to implement, and the object's name will be too long. And there is no need to invent a new system while we already have durability.

**Additional context**  
I'm not a native English speaker, sorry for my poor English.

**Comment by Alterforce** [comment]
I agree.
It is a bit silly that you can save XX short ropes by crafting them into a long rope.
