### ISSUE TITLE
When NPC dies, property is considered someone else's despite being in the 'your followers' faction

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#34144]
When NPC dies, property is considered someone else's despite being in the 'your followers' faction.
# Steps To Reproduce
1:Recruit your shelter friend
2:Go about your day looting and doing standard things
3:have your friend die of horrific infection or any other causes
4:Can't craft properly anymore due to ownership issues and have to pick up and drop 'steal' it all back into your ownership.

# Expected behavior
My property remains my property even if one of my allies die.

# Versions and configuration

7756, 21/09/2019.
last commit, this one with faction fixes: 
https://github.com/CleverRaven/Cataclysm-DDA/commit/8b59cb22b5e70bb7fc3d039328de8e64ae7f1c2d
Windows x64 tiles
mods loaded:
-   "dda",
-   "Tolerate_This",
-   "growable-pots",
-   "makeshift",
-   "More_Survival_Tools",
-   "Medieval_Stuff",
-   "modular_turrets",
-   "Salvaged_Robots",
-   "national_guard_camp",
-   "more_locations",
-   "FujiStruct",
-   "mapgen_demo",
-   "DP_REMIX_INDICATORS",
-   "sees_player_retro",
-   "cbm_slots",
-   "sleepdeprivation",
-   "No_Rail_Stations",
-   "no_npc_food"

# Additional context
save here:
https://mega.nz/#!zd13jaYI!8pJIaiklX__rh2L1tXgMYDiaMlXsVkmN6E4o7YO6jKQ

**Comment by ZhilkinSerg** [comment]
Maybe they had a will or something?

**Comment by dissociativity** [comment]
> 
> 
> Maybe they had a will or something?

mind you, that is an interesting quest idea, quests from wills on bodies

**Comment by davidpwbrown** [comment]
Yep so whts happening here is yet another way for factions to break in weird nd wonderful ways.

The player dosnt even belong to their own faction when the gmae is loaded, the NPCs are added to "your_followers" when they are convinced to join, but thats not the players faction.

Player is being assigned some weird faction on gmae start, related to the attempts to work around the loading order problem where items and vehicles were loaded before factions were.

Its an absolute mess, and it keeps getting worse, but im working on it.
