### ISSUE TITLE
'Query on  disassembly' setting in Options>Interface is not respected

### ISSUE THREAD

**Issue by Uesrnme** [CleverRaven/Cataclysm-DDA#34147]
# Describe the bug
When 'Query on disassembly' set to 'Yes' (default value), there will be no query in recent builds 

# Steps To Reproduce
Set 'Query on disassembly' to 'Yes', disassemble something.

# Expected behavior
Must be a query if the item should be disassembled.

# Versions and configuration
 - OS: Windows 7-32
 - Game Version: >0.D stable
 - Graphics version: Tiles
 - Mods loaded: dda

**Comment by Night-Pryanik** [comment]
Please fill in the issue template with **your** information.

**Comment by Ramza13** [comment]
So looking at the code this seems intentional.  Right now in the code it only will display the query if you are butchering things.  Should the option be renamed or changed?
