### ISSUE TITLE
The text in the main (i)nventory menu is replaced with error messages

### ISSUE THREAD

**Issue by remuluson2** [CleverRaven/Cataclysm-DDA#34159]
# Describe the bug

The volume and weight are replaced by error messages in the main inventory screen.

# Steps To Reproduce

1.make any character.
2. open the inventory with i
3. the weight and volume are replaced by error messages.

# Expected behavior

I believe that its a matter of missing lines of code related to that stringstream replacement today(09/21/2019).

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: Windows 10
 - Game Version: O.D-7798-g2da3f5e
 - Graphics version: Tiles
 - Mods loaded: [None]

# Additional context

**Comment by Honcharuk** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/15582553/65379441-91dd0480-dcd0-11e9-9987-3aa85749bfa5.png)
