### ISSUE TITLE
Error/Crash when attempting to (i)nstall on empty space

### ISSUE THREAD

**Issue by GroeneAppel** [CleverRaven/Cataclysm-DDA#34154]
# Describe the bug
Game produces an error/crash when attempting to (i)nstall while having pipes with you. When ignoring the error the game continues on without problem. In addition, the error re-appears whenever the object 'cart handle' is selected in the installation menu.

# Steps To Reproduce
1. Have pipes in inventory
2. (e)xamine a car
3. Attempt to (i)nstall.
4. Game produces an error.
5. When ignored: select cart handle in the menu to repeat the error.

# Expected behavior
No error popups when handling cart handles. 

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-7776-geba3646 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Fuji's More Buildings [FujiStruct]

# Additional context
I have uploaded my savefile to google drive as it is too large for github (32MB)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3638810/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3638811/crash.log)
https://drive.google.com/file/d/1FI_fXZDpir8JMdJRj-aDKTvdwvAHEY2Q/view?usp=sharing

-

**Comment by gogis79** [comment]
I can confirm that something happened with vehicle component installation on empty space. Just had hard crash once I tried to install wooden frame on empty space

**Comment by Entity-y** [comment]
It has something to do with that cart handle, presumably from the newly added grocery bot.

**Comment by anothersimulacrum** [comment]
Stack trace
> The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.D-7809-g168d57857b
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

	./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x43) [0x55e61d8ea165]
	./cataclysm-tiles(+0x531c0b) [0x55e61d8d9c0b]
	./cataclysm-tiles(+0x531e21) [0x55e61d8d9e21]
	/usr/lib/libc.so.6(+0x3a7e0) [0x7f74b45387e0]
	/usr/lib/libc.so.6(gsignal+0x145) [0x7f74b4538755]
	/usr/lib/libc.so.6(abort+0x125) [0x7f74b4523851]
	/usr/lib/libc.so.6(+0x25727) [0x7f74b4523727]
	/usr/lib/libc.so.6(+0x33026) [0x7f74b4531026]
	./cataclysm-tiles(_ZN4cata8optionalI11islot_wheelE3getEv+0x26) [0x55e61da8629e]
	./cataclysm-tiles(_ZN12veh_interact15display_detailsEPK10vpart_info+0x781) [0x55e61def6239]
	./cataclysm-tiles(_ZN12veh_interact10do_installERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x726) [0x55e61def92e6]
	./cataclysm-tiles(_ZN12veh_interact12do_main_loopEv+0x185) [0x55e61defa427]
	./cataclysm-tiles(_ZN12veh_interact3runER7vehicleRK5point+0x35) [0x55e61defa973]
	./cataclysm-tiles(_ZN4game12exam_vehicleER7vehicleRK5point+0x2b) [0x55e61d981593]
	./cataclysm-tiles(_ZN7vehicle13interact_withERK8tripointi+0x15b5) [0x55e61df4cc6d]
	./cataclysm-tiles(_ZN4game7examineERK8tripoint+0x213) [0x55e61d9a5299]
	./cataclysm-tiles(_ZN4game7examineEv+0x102) [0x55e61d9a58ee]
	./cataclysm-tiles(_ZN4game13handle_actionEv+0x11c9) [0x55e61d9dbb25]
	./cataclysm-tiles(_ZN4game7do_turnEv+0x439) [0x55e61d9a3331]
	./cataclysm-tiles(main+0x1248) [0x55e61d70a9bc]

	Attempting to repeat stack trace using debug symbols...
	debug_write_backtrace(std::ostream&)
	.../src/debug.cpp:621
	std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const
	/usr/include/c++/9.1.0/sstream:678
	log_crash
	.../src/crash.cpp:264
	signal_handler
	.../src/crash.cpp:293
	__restore_rt
	sigaction.c:?
	__GI_raise
	:?
	__GI_abort
	:?
	_nl_load_domain.cold
	loadmsgcat.c:?
	__GI___assert_fail
	:?
	cata::optional<islot_wheel>::get()
	.../src/optional.h:41 (discriminator 1)
	veh_interact::display_details(vpart_info const*)
	.../src/veh_interact.cpp:2545
	veh_interact::do_install(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
	.../src/veh_interact.cpp:930
	veh_interact::do_main_loop()
	.../src/veh_interact.cpp:340
	veh_interact::run(vehicle&, point const&)
	.../src/veh_interact.cpp:152
	game::exam_vehicle(vehicle&, point const&)
	.../src/game.cpp:5019
	vehicle::interact_with(tripoint const&, int)
	.../src/vehicle_use.cpp:1925
	game::examine(tripoint const&)
	.../src/game.cpp:5504
	game::examine()
	.../src/game.cpp:5397
	game::handle_action()
	.../src/handle_action.cpp:1769
	game::do_turn()
	.../src/game.cpp:1446
	main
	.../src/main.cpp:688
