### ISSUE TITLE
Error after killing zombie with shotgun

### ISSUE THREAD

**Issue by flesh420** [CleverRaven/Cataclysm-DDA#34155]
DEBUG    : Failed to wait until stamina threshold 3533 reached, only at 2109. You may not be regaining stamina.
 
 FUNCTION : void activity_handlers::wait_stamina_finish(player_activity*, player*)
 FILE     : src/activity_handlers.cpp
 LINE     : 2935

I was running away from two zombies with a splint on one leg and my stamina was depleted, so I wielded my shotgun and shot twice, then this error appeared.

# Versions and configuration

I'm using latest nightly.

**Comment by VReaperV** [comment]
Probably the same issue as with #32873 and #32049.
