### ISSUE TITLE
Crafting tiny electric motor takes much more ingredients than a small electric motor

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#34151]
# Describe the bug

While the small one is 10x bigger and 1.5x heavier, it takes 10x less steel to craft.
Meanwhile, the density of the tiny electric motor is insanely high: more than solid iron and copper.

# Screenshots

![](https://pstbin.ru/f/93669/)

# Versions and configuration

0.D-7761-g4f33ba412a-dirty

**Comment by NeviNovat** [comment]
Apparently the weight was discussed in #27335

**Comment by snipercup** [comment]
Will possibly be fixed after #34500 is implemented.

**Comment by l29ah** [comment]
Tested in 0.D-10040-ge8bfb5e29f, seems fixed.
