### ISSUE TITLE
Proposal for new nether faction: The Color

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#34168]
**Describe the solution you'd like**  
I would like to personally add a new dimensional entity/enemy somewhat resembling "the color out of space". I've been thinking about possible foes for a dimension ally warped lab, and thought that an entity similar to the color would pose an unique and interesting danger. 

Here's my idea described. It's a lot of text, but I tried to be as brief and concise as I could.

**What is the Color/and what are its forms**
Humans perceive the color as red-hued light, accompanied by a constant high-pitched hum. In reality, the color is more effectively described as subset of EM radiation.  Like light. gravity, or magnetism, color radiation can only be detected when something else interacts with it. 

A core tenet of the faction is that color radiation randomly manipulates basic aspects of reality. Within a color saturated structure, light, gravity, time and spatial dimensions might become warped or behave in unnatural ways.  Living creatures affected by the color might become the conduits for color reality-manipulation.

On very strange cases "creatures" comprised of pure color radiation might manifest, often taking the shape of mobile  mirror like spheres, its unknown if these are actually living things or just some exotic physical phenomena. 

**The Afflicted**
Creatures exposed to the color becoming color radiation emmiters and  become subservient on this radiation for survival. They exhibit prolonged periods torpor,  which are replaced by  an exaggerated "fight or flight" response when they are in the presence of the uninfected.  In their  excited state, the afflicted behave mostly like a healthy but highly stressed individual. For example, a diseased deer would run from you just like it were perfectly healthy, and an afflicted and properly trained human is perfectly capable of shooting at you (although not very proficiently, due to the heightened stress).  

Some afflicted and  all "pure forms", can exhibit powers related to the manipulation of gravity, light, time and/or space.  Whether they actually control such powers is unknown.

**Origins**
The color was first observed after X.E.D.R.A performed one of its first major Dimensional Breach experiments. The power used to create the portals was several orders of magnitude higher than required, and the experiment went terribly wrong, with the portals collapsing violently fractions of a second after their opening.

Ultimately, whether the color was created during the failed experiment or if it comes from somewhere else is absolutely unknown. Whether it is an entity with alien intelligence, or if it's is just a radiation is also unknown.  XEDRA scientists speculated that it was created by us, and that as such, it exists only on earth and on the unlucky dimension we briefly contacted, but in the end this is purely speculation.

**Spread/Progression**
The color spreads through all types of physical matter altering it into radiation emitter. Even short contact will result in permanent infection.  Thankfully, it's possible to inhibit the spread of the color through EM radiation,  a knowledge that X.E.D.R.A discovered  and used to contain the color within its lab. 

The color slowly spreads by twisting terrain into various radiation em miters that will propagate the field, and by using color afflicted creatures for the same purpose.  The player can destroy the color emitters, and kill the afflicted,  and can also use the extant XEDRA EM emmiters to contain color spread to new areas, but otherwise all infected areas are irrevocably lost and cannot be reclaimed.

Unlike the other big 3 nether factions, the color cannot jump between dimensions, and it can only infect physical matter as we know it, so it poses little danger to other nether factions.

**What is immune to the color**
Only nether beings, artifacts, and things made from equally otherworldly substances are naturally immune to the color. Pure form Blob is immune to the color, but normal zombies aren't (unless of course the blob mutates them radically) in the same manner, neither common triffids or fungaloids are immune. 

Rule-of-thumb, if you kill it and it melts, then it's immune to the color.

Normal matter is immune if its in the range of a containment EM emitter.

**Goals**
Uninhibited, the color spreads slowly but surely, if there's a purpose behind this is unknown.  In general, whether the color is an intelligence should be doubtful.  

Afflicted humans might experience visions and will generally believe that the color can show them "visions" and "speak to them" but the content of such experiences is not consistent, and reveals no intelligence or goals from the color.  Its likely that these phenomena are merely hallucinations.

**Interactions with the player/humanity**
Humans can't meaningfully communicate with color radiation, just as we cant have any sort of meaningful interaction with gravity or magnetism. 

The player can choose to break into the color warped lab, and if careless might compromise the containment mechanisms of the lab, and let loose one more apocalyptic horror upon the world. That and killing those afflicted are the only game play interactions that are possible with the color.

**Key Ideas/Defining Concepts**
The main concept to keep in mind is that the color is a physical phenomena/lifeform, and one whose nature is profoundly inimical to what we would consider normal reality.  The color exists at this is bad and wrong, but all else is a mystery.

**Comment by mlangsdorf** [comment]
Just on a player agency part, I'd dubious about an incurable affliction that doesn't kill you and that you can get without realizing it.  People are rightfully going to hate that.

I'm also not sure what the in-game, mechanically effects of the color's warping of reality are going to be, and it's hard to evaluate the proposal without that knowledge.

Assuming you can address the first issue, and that the mechanical effects are interesting, then I don't see a problem with adding another nether faction.

**Comment by John-Candlebury** [comment]
>Just on a player agency part, I'd dubious about an incurable affliction that doesn't kill you and that you can get without realizing it. People are rightfully going to hate that.

Yes I was thinking on making it analogous to highly irradiated areas. Which is to say safe if you are wearing adequate gear and deadly otherwise.  Since it would start contain within a lab, the player should have ample warnings to know what the are dealing with,

>I'm also not sure what the in-game, mechanically effects of the color's warping of reality are going to be, and it's hard to evaluate the proposal without that knowledge.

I recently made the map chunk placing traps for this purpose, which would allow a pre-infected location to have all sorts of unnatural shape warping as the player explores it. You can already check the micro-lab shifting hallway for an idea of how it would all feel.

Dynamically making chunks for locations that get infected during play seems a bit more difficult, but I think there are possible ways to achieve it.

**Comment by kevingranade** [comment]
So are you contemplating adding a for real end of world scenario? If so that's awesome.

**Comment by John-Candlebury** [comment]
Yes if the player messes up badly and allows the color out of containment, then thats definitively the end for the Earth. The spread at which the color spreads is still not set in stone (and will likely depend on how I actually implement it) but lore wise I would expect everything single cranny on the earth to be infected in less than a month. 

Of course, I have some doubts on how to actually handle the absolute end of the world through game mechanics. I guess just having the game end with a custom message would be adequate, otherwise I guess the player could  choose to stand around with nothing to do or fight,  role playing an actual afflicted.

**Comment by Nacarbac** [comment]
Might be fun trying to scramble together enough resources to survive (briefly) in a colour-blasted waste, pockets of tenuous reality held together by duct tape and plutonium. Occasionally braving a trip to raid a still-functioning lab or a Mi-Go observation bubble...
