### ISSUE TITLE
Smoke from burned down building persists and slows the game down

### ISSUE THREAD

**Issue by ZoolookCDDA** [CleverRaven/Cataclysm-DDA#34171]
Bug description:

I burned down a building but thin smoke and "hot air 3" persist in the ruins even days later, making the game very slow. After clearing rubble, smoke and hot air remain in the cleared area. I did experience at some point the smoke/hot air disappearing for a while after I cleared some of the rubble but then it came back a while later.

Steps to reproduce:

* Burn down a building
* Wait in the area to observe the thin smoke/"hot air 3" persisting
* As this bug might not happen every time these steps are executed, I provide a Dropbox link to a save game at the end of this message. The smoke/hot air is just to the right/east of the character

Expected behavior:

* Smoke/hot air should eventually disappear from a burned down building
* There should not be smoke/hot air in a cleared area for an extended period of time since nothing is there to generate it
* Burning down a building is a common action and should preferably not slow the game down that much even days after the fire is gone

Versions and configurations:

OS: Ubuntu 16.04
Graphics version: Tiles
Mods loaded: none

The following is generated from the Debug menu:

17:30:40.516 : Starting log.
17:30:40.516 INFO : Cataclysm DDA version 0.D-7763-g91773ed
17:30:40.517 INFO : Number of render drivers on your system: 3
17:30:40.517 INFO : Render driver: 0/opengl
17:30:40.517 INFO : Render driver: 1/opengles2
17:30:40.517 INFO : Render driver: 2/software
17:30:40.519 INFO : Language is set to: 'en'
17:30:40.800 INFO : SDL version used during compile is 2.0.4
17:30:40.800 INFO : SDL version used during linking and in runtime is 2.0.4
17:30:41.126 INFO : Active renderer: 0/opengl
17:30:41.166 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
17:30:41.228 WARNING : opendir [./mods/] failed with "No such file or directory".
17:30:44.398 WARNING : opendir [./save/Badlands/mods] failed with "No such file or directory".
17:30:49.925 INFO : Loaded tileset: MSX++DEAD_PEOPLE
17:32:07.492 : Log shutdown.
-----------------------------------------

[Link to save game](https://www.dropbox.com/s/8pbx7yvuvs1a726/Savegame.zip?dl=0)

**Comment by ZoolookCDDA** [comment]
For some reason, the link to my save game does not seem to work when clicking on it but copy-pasting the link should work. Here it is in plain text format:

https://www.dropbox.com/s/8pbx7yvuvs1a726/Savegame.zip?dl=0

**Comment by AMurkin** [comment]
You should write it like so:
```
[Link to save game](https://www.dropbox.com/s/8pbx7yvuvs1a726/Savegame.zip?dl=0)
```
It will turn into:
[Link to save game](https://www.dropbox.com/s/8pbx7yvuvs1a726/Savegame.zip?dl=0)

**Comment by ZoolookCDDA** [comment]
Thanks! I updated it.

**Comment by ZhilkinSerg** [comment]
Excessive map cache (light, seen, etc) rebuild due to fields processing:

![image](https://user-images.githubusercontent.com/16213433/65387140-f9389a00-dd4c-11e9-96bf-da315f11bdd1.png)

**Comment by BevapDin** [comment]
Don't mind me, I'm just causally dropping a link here #32452.

**Comment by ZoolookCDDA** [comment]
BevapDin: indeed it seems related. The problem in my save game is only there with experimental z-levels on which is consistent with what you describe. If I turn exp. z-levels off, the smoke/hot air is gone when reloading the save game. If I then turn exp. z-levels back on and reload the save, the smoke/hot air is back (even with no in-game time passing). There is no basement in the house I burned down but from your bug description, it seems that this problem can occur even in the middle of a field.

As I see it, there are two issues here (with your description not related to the second one):
* hot air/smoke should not persist in a cleared area,
* the game should not slow down to such a degree when the character is near smoke/hot air from, e.g., a burned down building.

 If the first issue can be dealt with, the second one seems less problematic to me since smoke should clear fairly quickly after the fire dies out.

**Comment by free-coffee** [comment]
This is #32452 - the firetowers start 2 levels above ground in your save. Since #34605 should terminate the issue i'd say this issue is closed.
