### ISSUE TITLE
Autosave failure then crash

### ISSUE THREAD

**Issue by Dunkhan** [CleverRaven/Cataclysm-DDA#34187]
# Describe the bug

The autosave function starting generating errors saying that it could not write the file. Unfortunately I kept playing and ignored it. After a few failed saves the game crashed and was unable to be loaded.

# Steps To Reproduce

Not known.

# Expected behavior

There should be no error messages, the game should not crash, saves should be able to be loaded.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: LinuxMint; Description: Linux Mint 19 Tara; Release: 19; Codename: tara; 
- Game Version: 0.D-7776-geba3646 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
# Additional context

Here is the crash on loading the save: https://pastebin.com/4RAnCLHr
Here is the debug log: https://pastebin.com/Abc4S2B1
Here is the save: [Bethel Acres.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3640050/Bethel.Acres.zip)

I had tried to set up a base camp at one point (the stack trace says something about basecamp) and had designated a tree cutting zone, a farming zone and a food zone. Not succeeding in working out what to do next I abandoned the idea leaving the zones.
Some time later I was inside a building and my npc went out to investigate a noise. I had forgotten to set him not to (can we change it to default?). He died and then I started getting messages that I was stealing when I accessed my shopping trolley, despite the npc never having touched it. I mention all this because I feel like a strange bug shortly before a crash could be relevant.

Possibly related to or duplicate of #29053

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed for more than a half-year.
