### ISSUE TITLE
Crash when looking around (x)

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#34201]
# Describe the bug

Game crashes

# Steps To Reproduce

- Load attached save
- press `x` (look around
- press and hold 9 (north-east)
- when you get roughly to the road, the game will crash

# Expected behavior

Game does not crash.
Because crashing is a bad user experience

# Versions and configuration

- OS: Windows
    - OS Version: Win 7
- Game Version: 0.D-7842-gcfc7f8a [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3641206/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3641207/debug.log)
[Lawnton.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3641208/Lawnton.zip)

**Comment by moxian** [comment]
Call stack:

```
>	cataclysm-tiles.exe!cata_tiles::draw(const point & dest, const tripoint & center, int width, int height, std::multimap<point,formatted_text,std::less<point>,std::allocator<std::pair<point const ,formatted_text> > > & overlay_strings, std::pair<enum SDL_BlendMode,std::multimap<point,SDL_Color,std::less<point>,std::allocator<std::pair<point const ,SDL_Color> > > > & color_blocks) Line 1207	C++
 	cataclysm-tiles.exe!cata_cursesport::curses_drawwindow(const catacurses::window & w) Line 1047	C++
 	cataclysm-tiles.exe!game::look_around(catacurses::window w_info, tripoint & center, const tripoint & start_point, bool has_first_point, bool select_zone, bool peeking) Line 6701	C++
 	cataclysm-tiles.exe!game::look_around() Line 6556	C++
 	cataclysm-tiles.exe!game::handle_action() Line 1650	C++
 	cataclysm-tiles.exe!game::do_turn() Line 1446	C++
 	cataclysm-tiles.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 688	C++
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	Unknown
 	cataclysm-tiles.exe!`dynamic initializer for 'land_use_code_wetland''() Line 40	C++
```

the crash occurs at https://github.com/CleverRaven/Cataclysm-DDA/blob/a495d62e13680206461481c9c1ecdf3af6f4bc99/src/cata_tiles.cpp#L1207 with `ch.visibility_cache` being a 132x132 array, and x/y being 174/-45 respectively...

I have no idea how this even works in the first place, and why it does not crash under normal play...

cc @Qrox who has been working on cata_tiles.cpp recently

**Comment by moxian** [comment]
I've partially bisected this to be introduced between 687b5346689348ce932f650e113d570a4dbbbe0d (good) and 687b5346689348ce932f650e113d570a4dbbbe0d (bad), both belonging to https://github.com/CleverRaven/Cataclysm-DDA/pull/33760
I'm not sure how much more time I'll be able to spend time on this today; will update if i find something else of interest.

Edit: the last several bisect steps turned out to be super quick, and said that bfee44d9d1261511d4dca55ba2d1d0ea5db082ec is the first bad commit.

**Comment by Qrox** [comment]
Oops, it seems I forgot to add bound check when moving the memory drawing code. Thanks, I'll look into it.
