### ISSUE TITLE
Explosives and tanks guns overhaul

### ISSUE THREAD

**Issue by zachary-kaelan** [CleverRaven/Cataclysm-DDA#34204]
**Is your feature request related to a problem? Please describe.**  
There's an item called "120mm HEAT shell" in the base game, that has an explosive power of 16000. There's a separate item called "120mm HEAT shell" in Tanks, that has an explosive power of 100. Neither of these are anywhere close to right.

Also, I've noticed a few compounds saying they're used for explosives, when they're not.

**Describe the solution you'd like**  
- Add various explosive materials and chemical mixtures to the game
- Do refactoring of code and JSONs
- Sort out tank and howitzer shells
- Add more recipes and uses for various components

**Describe alternatives you've considered**  
Some mixtures and compounds - if unlikely to be found or salvaged - don't need to be added to the game at all. Instead, they can use recipe groups or abstract JSON types.

Speaking of abstract JSON types, calculating the power of explosives based on materials is currently a pain; mixtures will only add to that. Allowing for explosion data to use the "proportional" and "relative" JSON members would make things significantly easier.

**Additional context**  
I've already started on this - been compiling a list of explosive components and their various parameters.
![image](https://user-images.githubusercontent.com/30245333/65427783-19b23400-dde1-11e9-91e6-65f811e6ddb0.png)

I found a 900-page military document with full specs on pretty much every shell in existence up to 2003. For instance, a type of 40mm HE shell used by the M79 grenade launcher weighs 0.503 lb, has a length of 3.89 in., a muzzle velocity of 76 m/s, and uses an explosive payload of 32g Composition B.
[ARMY AMMUNITION DATA SHEETS - ARTILLERY AMMUNITION: GUNS, HOWITZERS, MORTARS, RECOILLESS RIFLES, GRENADE LAUNCHERS, AND ARTILLERY FUZES](http://bulletpicker.com/pdf/TM%2043-0001-28,%20Artillery%20Ammunition.pdf#page=20)

**Comment by thethunderhawk** [comment]
Thing is about a HEAT shell, it’s not going to have a straightforward epicenter, it’s very much a directional thing, so if you’re abstracting that into a big circular blast there’s a lot of room for interpretation as to how powerful the explosion should be.

**Comment by NeviNovat** [comment]
I was thinking of the same thing for some time, also the Heavy Ordinance project (https://github.com/CleverRaven/Cataclysm-DDA/projects/29  ) has a similar aim to this suggestion.
I started to work on adding more makeshift explosives #34309 and your resources might help me.

**Comment by zachary-kaelan** [comment]
@NeviNovat Hell yeah dude. Match head powder (potassium chlorate) was one of the things in my notes.

Here's a Google Doc with some explosive material values: https://docs.google.com/spreadsheets/d/1LGB5Lj-vc6frYVeDnERpFHc3jWf1xtVPuriw0UxaWQ4/edit?usp=sharing

**Comment by zachary-kaelan** [comment]
One thing I'd like to do is support the use of plastic explosives. You activate them - which asks how many you want to place - then you put down that many portions of the plastic explosive putty, on a wall or on the ground. You use a gun, radio control, or fuse to detonate it.
