### ISSUE TITLE
Looting a dead npc causes a crash

### ISSUE THREAD

**Issue by shotgunfrenzy** [CleverRaven/Cataclysm-DDA#34212]
# Describe the bug

Whenever any random npc is killed, trying to loot the corpse causes an instant crash

1. set your npc spawn to something high, like 30
2. wait till one appears, watch it get killed by zombies or kill them yourself after they get scared of your mutant ass
3. Try to loot the corpse
(in save file there is a fresh npc kill to th eleft of player, crashes when attempting to loot it)

# Versions and configuration
 - OS: windows 10 version 1903
rest in debug log

[Logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3645899/Logs.zip)
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3645900/Save.zip)

**Comment by ZhilkinSerg** [comment]
No crash for me when looting corpse on an attached savegame on latest `master`. I guess this could be caused either by a third-party mods (`PK_REBALANCE` and/or `SD_Magcrafting`) which I lack on my system, or by using older version.

Please try to reproduce the issue w/o mods on latest available version and ping me to reopen if you succeed.

**Comment by ZhilkinSerg** [comment]
I've reproduced it myself without any mods.
