### ISSUE TITLE
slight adjustments to certain gun modifications

### ISSUE THREAD

**Issue by shotgunfrenzy** [CleverRaven/Cataclysm-DDA#34213]
**Is your feature request related to a problem? Please describe.**  
Ideas coming from other games, like escape from tarkov and the like, its annoyed me a bit that certain gun modifications, like laser sights, come in two different variants (e.g. rail and under barrel) when they more than likely are the same thing, just in different places on the certain gun rail positions, also the forward grip, depending on what type the devs want it to be, should count as using the grip slot in the attachments instead of the under barrel slot, like how the ergonomic grip is.

**Describe the solution you'd like**  
See if its possible for the action button (a) to be used on items such as the laser sight, and non magnification sights like the iron sights and red dot attachments to example: allow switching between underbarrel laser sight and rail laser sight, or iron sights and offset iron sights, thus also slightly decreasing the recipes as well, having one item that can switch between the two.

Also see if its feesable to have the forward grip attachment be used in the grip slot instead of the underbarrel slot, for anyone who's about to scream that you can't have a forward grip and for example, an underbarrel grenade launcher in the same spot, then have an option to activate the forward grip between its normal configuration, and the angled config like the image shown

![9yyazy3i6wg21](https://user-images.githubusercontent.com/32794174/65493740-c8946400-def6-11e9-88c1-42bff7980c5a.jpg)

**Additional context**  
depending on how extensive gun attachments will ever get in future, system could also be used on these.

**Comment by tenmillimaster** [comment]
Commerical laser sights like crimson trace, viridian, and military style AN/PEQ lasers are quite different.


That said, there are a handful of situations I'd like to see moveable gunmods.
