### ISSUE TITLE
About the effect of the forest on the body against temperature and sun glare

### ISSUE THREAD

**Issue by ThomasLinkin** [CleverRaven/Cataclysm-DDA#34225]
**Is your feature request related to a problem? Please describe.**  
My character has Albino,and since it's summer,i decided to ran into the forest to stop the sunlight,also to cool down the temperature. What i thought didn't happen

**Describe the solution you'd like**  
When you run into the forest, your temperature lowered and the sun glare won't affect you.

**Describe alternatives you've considered**  

**Additional context**  
I don't have any picture since that character died yesterday,but i will try to get some picture if my next one has Albino

**Comment by kevingranade** [comment]
Yes trees don't have upper regions, that is something we can look into.

**Comment by ipcyborg** [comment]
This could help with Albino skin irritation #34105 by using clothes (but not with glare effect).

**Comment by ThomasLinkin** [comment]
Using clothes is a method,but will bring more heat into your character's body,so i am seriously don't want to do that.
