### ISSUE TITLE
Grocery cart "collides with errors in the movement code"

### ISSUE THREAD

**Issue by Proxiehunter** [CleverRaven/Cataclysm-DDA#34223]
# Describe the bug

When pulling a grocery cart NPC followers will sometimes wind up standing on the handle causing the error message and being unable to pull the cart.

# Steps To Reproduce

1 Pull grocery cart
2 Enter tight area while NPC attempts to follow
3 NPC stands on the carts handle and the cart can not be pulled.

# Expected behavior

NPC does not stand on the carts handle.

# Versions and configuration
Version 9666

**Comment by Night-Pryanik** [comment]
Duplicate of #23000.
