### ISSUE TITLE
Some guns have a "X mount" slot instead of a "X" slot.

### ISSUE THREAD

**Issue by Hatfish** [CleverRaven/Cataclysm-DDA#34220]
# Describe the bug
Some guns have mislabeled mod slots, which prevent gun mods from being installed to those slots.  The ones I've found so far are sights mount, underbarrel mount, rail mount, and stock mount (instead of sights, underbarrel, rail, and stock respectively).

# Steps To Reproduce

1. Spawn an MP5-PDW or MP5A2 & a red dot sight, give self requisite skill to install the sight on the gun
2. Attempt to install the mod, realize that you cannot because the red dot sight can only be installed to a sights slot and not a sights mount slot

# Expected behavior

Gun mods should be installable if there is an open slot.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-7902-ga495d62 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Mutant Power Armor [Mutant_Power_Armor],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    sees-player icon, -attitude [sees_player_less_attitude],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes]
]

# Additional context

I only checked the 9mm category and there were a few leadworks guns with "X mount" slot types as well I think.  It isn't a problem for those since they have the gun mods built in but it might confuse contributors to have two similar but different sets of mod slots available.  The issue could also just lie with the red dot sight, I didn't really check any other gun mods against this (in retrospect I probably should have).

**Comment by tenmillimaster** [comment]
Did you spawn a sights mount?

**Comment by tenmillimaster** [comment]
Perhaps the 'x' mount naming is a bit confusing- it implies one could attach a rail, slot or lug to enable installation of such mods.

**Comment by Hatfish** [comment]
Wait, you specifically need to find or make a mount for gun mods now?

**Comment by shotgunfrenzy** [comment]
only for guns which don't have the mounts to start with, example old style revolvers

**Comment by tenmillimaster** [comment]
It depends on the specific firearm, but yes, that's the gist of it. I updated the MP5 and subvariants recently to have corrected stats; they cannot mount optics without a claw mount adapter.

The commercial copy, the PTR603, can, because it has a rail welded on.

**Comment by kevingranade** [comment]
Yep, please let us know if you can think of a way to make it more obvious what is happening here, but this is working as intended, these guns have a place where you can install a mount.
