### ISSUE TITLE
A debug menu command to make a CSV file with all missing graphics.

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#34231]
**Is your feature request related to a problem? Please describe.**  
It is very difficult to get a complete list of what is missing from a tileset, in a helpful format. This is a major boundary to making a complete tileset. The game does know how to produce this data, because it's pumped out in a hard-to-read debug file.

**Describe the solution you'd like**  
A debug menu command with several options to output missing graphics for:
* items (not worn/wielded)
* items (worn/wielded only)
* terrain/furniture
* monsters
* players/npcs and mutations
* vehicle parts

Each output would create a CSV entry with the following columns:
* ID of tile
* looks_like entry for tile
* Does the tile have a unique graphic?
* Does the tile have a looks_like graphic?
* Does the tile have _multiple_ graphics?

**Describe alternatives you've considered**  
This could be done with a script, but doing it in-game means the json entries are already parsed. Should be easier.

**Additional context**  
This is one of several suggestions to make graphical content contribution more accessible.

**Comment by mlangsdorf** [comment]
I'll look into this.  Do you want the data like this:
mjlonir, hammer_sledge, No, No, No, hammer_sledge, hammer, Yes, Yes, Yes,
or
mjlonir hammer_sledge No No No, hammer_sledge hammer Yes Yes Yes,

ie, should the CSV separate every value or just id groups?

also, should we try and spit out invalid ids, like overlay_worn_t_swater_winter

**Comment by I-am-Erk** [comment]
I think separate each value in case we want to sort by a particular value.
I'd include invalid ids, I assume that would be for things like scarves that are tight vs loose?

**Comment by snipercup** [comment]
@I-am-Erk you saw my post on Reddit. I started working on your idea. I published it here: https://github.com/snipercup/CCDA-JS-data-browser.  Follow the installation instructions and afterwards open tile_missing_sprite.html, select a item type and press OK. It will produce a list of items that do not appear in gfx\ChestHole16Tileset\tile_config.json. That's the file I should be comparing with right?

It is very limited right now. It's only checking for missing sprites of items, and only in the chesthole16 tileset. I'm just giving an update right now to see if i'm on track. Please provide feedback and correct anything that is not what you had in mind.

**Comment by anothersimulacrum** [comment]
Preferably this would be any tileset config file, but good work!

**Comment by snipercup** [comment]
@I-am-Erk Update: I added the option to select a tileset. Please review if this is what you want. Next step is to also include furniture, terrain and the rest.

**Comment by I-am-Erk** [comment]
I think it's a start... I'll take a look but I'm not sure I can get javascript to run on a work computer. Outputting to csv is something I really want so that I can make spreadsheet checklists of sprites needed

**Comment by snipercup** [comment]
@I-am-Erk I just checked and outputting to CSV is possible. Do you have another machine you can use it on?

**Comment by I-am-Erk** [comment]
OK, got it working on computer. Yeah, it does a good job of listing the tiles, but I was hoping for more information than this as described in the OP, and for the ability to export it all to a comma delineated spreadsheet which it sounds like you can work out.

Still it works well as a JS rather than a debug tool. If you can get it working for the other fields it would probably satisfy the requirements.

**Comment by snipercup** [comment]
It's not done yet, ill keep you updated on the progress.

**Comment by snipercup** [comment]
Update, added the following:
- Terrain tiles can now be matched against tile config
- The result can be exported to CSV although after doing that you have to rename the file to a .csv file
- Added looks_like to the results

If you select terrain you can ignore the item type. It will take any terrain and not a selection
I don't know where to get this info

> Does the tile have a unique graphic?
> Does the tile have a looks_like graphic?
> Does the tile have multiple graphics?

In what file should I look for that?
