### ISSUE TITLE
"pike" is ambiguous

### ISSUE THREAD

**Issue by Aloxaf** [CleverRaven/Cataclysm-DDA#34263]
# Describe the bug

There is a monster named "pike", and there is also a weapon named "pike".
And there is no context to distinguish them, which makes it impossible to create a correct translation for both in most language at the same time.
# Steps To Reproduce

1. Spawn an item "pike"
2. Spawn a monster "pike"
3. Change language to others (eg. Chinese)
4. You will find they have the same translation.

# Expected behavior

They should have different translation. So they should have different name, or in different context.

# Screenshots

N/A

# Versions and configuration

 - OS: Arch Linux
 - Game Version: 0.D-7905-g384dcdbbd3
 - Graphics version: Tiles
 - Mods loaded: [ "dda",  "no_npc_food" ]

# Additional context

The weapon "pike" was previously called "awl pike", see #30591

**Comment by ZhilkinSerg** [comment]
Just add context to both json files:

```JSON
"name": { "ctxt": "item", "str": "pike" }
```


```JSON
"name": { "ctxt": "monster", "str": "pike" }
```

**Comment by Qrox** [comment]
> Just add context to both json files:

It needs first updating the c++ code of `itype` and `mtype`.

**Comment by ZhilkinSerg** [comment]
> 
> 
> > Just add context to both json files:
> 
> It needs first updating the c++ code of `itype` and `mtype`.

Is it not using `translation` yet and treated as a plain string?

**Comment by Qrox** [comment]
Yes, and also because they have plural forms so I'll have to add plural support to the translation class.

**Comment by Barhandar** [comment]
Is explicit context declaration instead of it being inferred from the `TYPE` really necessary?

**Comment by Qrox** [comment]
It was necessary in #26402 where the same string in the same type of json object needed different translations in different contexts, so I'm doing it this way for consistency. Furthermore, there are thousands of item names. If the context was changed to be inferred from the type, translators have to re-confirm every translation of these strings.
