### ISSUE TITLE
Fuel cell bionic weird consumption behavior [Can be solved quickly]

### ISSUE THREAD

**Issue by VoidForge** [CleverRaven/Cataclysm-DDA#34270]
# Describe the bug
All bionics that use fuel (e.g. gasoline fuel cell CBM, blood power generator CBM of Magiclysm) have strange behavior when consuming fuel. After consumption, the amount of fuel stored in CBM equals the available amount of fuel (Character::get_fuel_capacity), which causes indefinite consumption.

# Steps To Reproduce
1. Make a player with gasoline fuel cell CBM and some gasoline, eat the gasoline
2. Turn on the fuel cell and wait for a few seconds, then switch off it
3. Eat more gasoline and see all of your precious gasoline lost into the void

# Expected behavior
Fuel cell bionics are correctly refueled

# Versions and configuration
Build: 9671

# Additional context
probably caused by `bool player::fuel_bionic_with( item &it )` in consumption.cpp

    const bionic_id bio = get_most_efficient_bionic( get_bionic_fueled_with( it ) );
    const int loadable = std::min( it.charges, get_fuel_capacity( it.typeId() ) );
    const std::string loaded_charge = std::to_string( loadable );
    it.charges -= loadable;
    set_value( it.typeId(), loaded_charge );// type and amount of fuel
    update_fuel_storage( it.typeId() );

# Apology
I do not know how to contribute on github, therefore I can't solve this bug on my own.  I am not a native speaker and please forgive my poor English.

**Comment by VoidForge** [comment]
Save file can be provided on demand

**Comment by Fris0uman** [comment]
I got it:
```cpp
    set_value( it.typeId(), loaded_charge );// type and amount of fuel
```
This overwrite the amount of stored fuel instead of adding to it. I'll push a fix soon.

**Comment by VoidForge** [comment]
> I got it:
> 
> ```c++
>     set_value( it.typeId(), loaded_charge );// type and amount of fuel
> ```
> 
> This overwrite the amount of stored fuel instead of adding to it. I'll push a fix soon.

Thanks a lot!
