### ISSUE TITLE
Crashing when trying to read a solo NPC's faction

### ISSUE THREAD

**Issue by FirebrandCoding** [CleverRaven/Cataclysm-DDA#34276]
# Describe the bug

On load, the game shows the same error multiple times, about being unable to get (what I presume is) the self-contained faction of an NPC I met since the last time I played. After pressing Space multiple times to continue, or pressing I to ignore the message, the game crashes.

# Steps To Reproduce

1. Load the save.
2. Wait until the error pops up: after everything loads, but before you're able to play the game proper.

# Expected behavior

Expected for the game to load without the error.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: Windows 7 Ultimate, Service Pack 1, 64-bit
- Game Version: 0.D-7696-g5316cef [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
	"dda",
	"no_npc_food",
	"aftershock",
	"crt_expansion",
	"adv_gear",
	"alt_map_key",
	"mutant_npcs",
	"P_Caches",
	"more_locations",
	"DP_No_Debug_Tile",
	"DP_REMIX_INDICATORS",
	"Mundane_Zombies",
	"No_Anthills",
	"No_Bees",
	"No_Fungi",
	"manualbionicinstall",
	"no_reviving_zombies",
	"safeautodoc",
	"novitamins",
	"sleepdeprivation"
]

# Additional context

- seems to be a world issue, rather than a character/save issue: creating a random character in the same world in order to generate the report causes the same errors;
- another error precedes the one causing the crash, and it was present in the previous save earlier (`expected string but found "o"`, visible in the supplied `debug.log`); continuing through it did not seem to cause issues in-game
- if at all possible, I'd like to be able to repair whatever's causing the issue so I could continue to play the character

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3663315/config.zip) (`crash.log` + `debug.log`)

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3663321/save.zip) (has so far crashed before properly loading, on old and new characters)

**Comment by ZhilkinSerg** [comment]
Should be fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/34217.

**Comment by davidpwbrown** [comment]
fixed by #34217

**Comment by FirebrandCoding** [comment]
Confirmed. The build to test this was only released 10 hours ago. Now the save loads without the issue.

Thank you for the fix.
