### ISSUE TITLE
Unable to clone wiki on windows due to invalid character in filename

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#34271]
# Describe the bug

Github cannot create this file: https://github.com/CleverRaven/Cataclysm-DDA/wiki/Want-to-help-with-development%3F-List-of-easy-jobs when cloning the repository locally on windows. This is due to the ? present in the filename.

# Steps To Reproduce

1. Clone the wiki repository on windows
2. Observe the error that github desktop throws

# Expected behavior
A succesful clone of the wiki files

# Versions and configuration
Github desktop version 2.1.3
Windows 8

# Additional context
```
(377/377), done.
error: unable to create file Want-to-help-with-development?-List-of-easy-jobs.md: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

```

If you are able to, please change the name of that page to fix this issue. For example to "Help with development - a list of easy jobs.md"

**Comment by ZhilkinSerg** [comment]
Try again and close if everything is fine.

**Comment by snipercup** [comment]
Thanks, I no longer have the issue.
