### ISSUE TITLE
auto travel suggestions

### ISSUE THREAD

**Issue by AllSystemsGo** [CleverRaven/Cataclysm-DDA#34272]
The short version: make the interrupt system more like crafting.

Suggestion 1: When auto travelling, if there's a lot of noises nearby, you are prompt spammed. It would be nice if there was an 'ignore all disturbances' option on the dialogue, similar to crafting.
--
When you spot a monster, you are prompted again if you wish to ignore it, However, this is true even for monsters very far away. If you choose to continue, you then might only be taken out of auto travel if a monster is blocking your path or if it grabs you.

Suggestion 2: Have a prompt for when a monster is "dangerously close", similar to the crafting interrupt dialogue.
--
This would be a nice middle ground between a prompt for a monster being over the hills and far away, or "I'm already in your face and eating it."

**Comment by ThomasLinkin** [comment]
Auto travel? Mind explain it further into details about how it works? Does it sounds like fast travel in almost every game nowadays?

**Comment by ThomasLinkin** [comment]
Besides, the worst thing that could happen if you can auto travel is that you happen to encounter a tank or a chicken walker. It won't be that easy to run if you have already had the red dot on you.

**Comment by thethunderhawk** [comment]
@ThomasLinkin Auto travel is already in, check the hotkey menu. All it does (afaik) is it automatically paths you around obstacles when you walk in a direction. Mostly useful for traveling through forests without constantly having to move around trees and such.

**Comment by AllSystemsGo** [comment]
> Besides, the worst thing that could happen if you can auto travel is that you happen to encounter a tank or a chicken walker. It won't be that easy to run if you have already had the red dot on you.

One step at a time.

These suggestions won't make it perfect, but I think it would be a lot better than it is now.

**Comment by ThomasLinkin** [comment]
Nah i suppose if that has already been inside the game,you should do something with it. The safe mode won't turned on until something different than what you are doing happens,and if those red dots shine on you,it has already been too late.

**Comment by mrkybe** [comment]
@AllSystemsGo There's an option in settings to adjust the distance at which safemode/auto-travel stops you.
