### ISSUE TITLE
Add Tactical Reload

### ISSUE THREAD

**Issue by ThomasLinkin** [CleverRaven/Cataclysm-DDA#34278]
**Is your feature request related to a problem? Please describe.**  
I would love it if someone add the "Tactical Reload" into the game. Suddenly thought of it whilst checking out the Heavy Ordinance section in the project tab

**Describe the solution you'd like**  
Add a tactical reload as a way to reduce the reload time abit in combat. A way to save your character in heat if enemies are surrounding you, as one extra bullet sitting in the chamber could clear the path,or having a bullet in the chamber will help you cut off the "ammo reload into the chamber" gesture and save some time. IRL that action would takes around 2-3 seconds.

**Describe alternatives you've considered**  
I am not a dev,so i don't know how hard would this be,but if there are a better reason to implement this into the game,i would love to take

**Comment by NotFuji** [comment]
You already can do "tactical reloads"  Dropping the empty magazine instead of putting it in your inventory saves a significant amount of time.

**Comment by ThomasLinkin** [comment]
That's not Tactical Reload my dude.go check that one on Google. The one i was talking of involve ammo and the gun,not the magazine and where to put it. Every characters of mine who live more than 50 days have chest rig,so i know what that is

**Comment by anothersimulacrum** [comment]
Could you please describe what you are requesting? Your post doesn't make it very clear.

**Comment by ThomasLinkin** [comment]
If you don't find it,here's how it work. 
Usually,a normal rifle (take that as an example) has 30 rounds in it's mag,right? So you see,everytime you put that magazine in,you always have to push the first rounds of the magazine into the chamber,so that the gun will have ammo inside it to start shooting,or else,even with the mag in,you won't be able to shoot. Now Tactical Reload is that you put a magazine in,clock the first round into the gun, and take a full 30 rounds mag to reload your gun,and your guns have 31 rounds : 30 in the mag and 1 in the gun.That way,everytime you reload the gun with a new mag,you won't have to clock the ammo into the chamber,just put the mag in and shoot.

**Comment by ThomasLinkin** [comment]
The first game i can think of which has that one is Black Squad.

**Comment by NotFuji** [comment]
I realize that, my point is it's already possible to get reloads down to
negligible times.  A one second time reduction is going to make very
little, if any, gameplay difference.

**Comment by NotFuji** [comment]
Furthermore, one-in-the-chamber isn't simulated currently, and isn't
planned to be, as again, it really doesn't make a difference.

**Comment by ThomasLinkin** [comment]
No my dude. 1 second when you are surrounded are seriously helpful. I usually found myself inside a giant horde (i put the spawn rate to 3.00) and all of my other mag (usually 3 or 4) are out.

**Comment by ThomasLinkin** [comment]
And if you don't think 1 make a difference,check my post again. I explained that one already

**Comment by ThomasLinkin** [comment]
I'm always running toward gun store in the game,so this will help me alot since i usually have shitload of ammo and guns,but don't have enough volume,or magazine to rush through the city

**Comment by NotFuji** [comment]
If you're surrounded by a giant horde, one second or one bullet, isn't going to save you.  If it does, prove it with evidence and testing.  Anecdotes don't help.

**Comment by ThomasLinkin** [comment]
Well,if you don't think it's a good idea,then okay. I can't find an evidence that helpful enough ,so this will have to do. At least i tried.

**Comment by ThomasLinkin** [comment]
Another post that has the same idea as mine
#34248

**Comment by Feuerhai** [comment]
Then this can stay closed and we keep the other one, which explains it a lot better

**Comment by ThomasLinkin** [comment]
Agree. But someone should consider my opinion in the function's usage in combat.
