### ISSUE TITLE
Tables are way too small.

### ISSUE THREAD

**Issue by Xion350** [CleverRaven/Cataclysm-DDA#34293]
# Describe the bug

Tourist Tables take up 25 L of space, while normal wooden tables only take up 10.5 L

# Expected behavior

As a table that is supposed to be foldable, I would expect in its folded state it would take up less space than an actual table.  Using some real world examples of foldable camping tables, the Tourist table takes up about as much space as would be expected while Wooden/Fancy Tables are way too small in the inventory.  Currently if you want a portable table for crafting purposes it's actually way easier to carry a full size table in your backpack than a foldable one.

# Screenshots

![image](https://user-images.githubusercontent.com/13670135/65814135-9bb8a900-e1a3-11e9-9951-a789b71a3ded.png)
![image](https://user-images.githubusercontent.com/13670135/65814136-9e1b0300-e1a3-11e9-9823-bd970547ce01.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-7979-g8d33113 [64-bit]
- Graphics Version: Tiles

# Additional Notes

This is something that's very easily fixed, I just would like to know what the proper values would be recommended for both, or if it's even intentional.

**Comment by moxian** [comment]
The first google link for "foldable tourist table dimensions" gets me to https://www.amazon.com/Collapsible-Aluminum-Foldable-Portable-Ultralight/dp/B0776VZ8JY which claims package size of:
6.5*5.5*2.5inch/ 42*14*6cm 1.9LB/ 0.88KG for small and
27.6*5.9*2.7inch/ 70*15*7cm 3.6LB/ 1.65KG for large variants.

That translates to ~3.5 and ~7.3 liters respectively, implying that cata's folding tourist tables are way too large (and too heavy)

Then again, second google link gives a "78cm  X 8.5cm X 97cm" package size table which is 64 liters...
I guess we can conclude that tables have a great variety of dimensions?...

**Comment by snipercup** [comment]
You compared it to a wooden table vehicle part, that cannot be deployed like a normal wooden table. I think it makes sense that the wooden table vehicle part is as small as it is. Although in comparison, the minifridge, minifreezer, dishwasher and washing machine vehicle parts are all125L. Then again, the RV kitchen unit, foodco kitchen buddy and onboard chemestry lab are 20L. Interestingly, a human corpse is 62L. Matress, 300L.Television, 3L (same as microwave), while being described as large.

My suggestion is to make the wooden table 20L and leave the tourist table as is, seeing as it's size is fine when compared to a human corpse.

**Comment by Xion350** [comment]
> cannot be deployed like a normal wooden table.

It can actually with the `*` Construction menu.  Plus I'm considering the fact that there's no extra work required for either adding to a vehicle or just deploying it as a table.

**Comment by Nacarbac** [comment]
Most folding tables that I've seen are designed to have a handle when folded - so making them wearable like a briefcase may be an idea.
