### ISSUE TITLE
Steel Mills have nothing in them whatsoever.

### ISSUE THREAD

**Issue by fluffe9911** [CleverRaven/Cataclysm-DDA#34307]
# Describe the bug
So I decided to visit a steel mill to see what was in it (hopefully steel) and when I went there to my surprise I found nothing whatsoever no zombies or items not even any paper scraps. This may not be a bug and I may just be unlucky but not sure. I also didnt check the metal container things with the shutters on them due to my lack of equipment to open them, so those may have items in them although still weird nothing else had anything.

# Steps To Reproduce

1. Find a steel mill
2. Search around the steel mill
3. Realize you been ripped off and there is no actual steel

# Expected behavior
I expected there to be steel or atleast something that says stuff is here or was here at one point I couldnt even find a single item whatsoever.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-8007-g5915b0e [64-bit]
- Graphics Version: Tiles
- Mods loaded:
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock],
    Bens GF recipes [Tolerate_This],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Draco's Pig Mod [DracoPigMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    Necromancy [necromancy],
    Mining Mod [Mining_Mod],
    Urban Development [Urban_Development],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm]

# Additional context
I did have a ton of base included mods and two nonbase included mod so one of them may have borked it or im just straight up unlucky who knows.

**Comment by fluffe9911** [comment]
Ok just looked at the original pr and apparently the author was planning on adding items/zombies in a second pr although its been a month since its been merged so *shrug*

**Comment by snipercup** [comment]
I'm going to work on this a bit more. I'll make it as the author of the steel mill describes in #33383
