### ISSUE TITLE
Gas Pumps Take Forever

### ISSUE THREAD

**Issue by SageB** [CleverRaven/Cataclysm-DDA#34306]
# Describe the bug

a: It takes over an hour in-game to fill a gallon jug with gas from a pump. 

b: Additionally, when attempting to refuel a Main Battle Tank with gas, the pump only refills one unit at a time, requiring you to select a vehicle tank and confirm for every single unit.

# Steps To Reproduce

a1. Get a gallon jug, a cash card, a timepiece and a gas station.
a2. Buy enough gas to fully fill the jug (3750)
a3. Watch the time. It takes just a few minutes over an hour.

b1. Attempt to fill a Main Battle Tank with gas.

# Expected behavior
For it to be much faster. I can fill up my car with several gallons of gas at a gas station and it only takes a few minutes IRL. Also, when I tell the pump to fill a vehicle tank, it should fill it until full or it gets interrupted.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-7930-gd10735f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    Classes and Scenarios Mod [more_classes_scenarios]
]

**Comment by ZhilkinSerg** [comment]
Please try reproducing on build 9678 or above.
