### ISSUE TITLE
Segmentation error when checking factions

### ISSUE THREAD

**Issue by starytroll** [CleverRaven/Cataclysm-DDA#34313]
# Describe the bug

The game crashes when I try to check factions. (# tab tab). My only follower is currently on a gathering mission. First time I got crash, I went to the camp, recalled my follower, asked him for training, for which he asked money and then disappeared. I found him near my home few tiles away and realised he is not my companion (at that time checking factions worked well) but I could give him commands like he were one. The crashed happened some time after conversation (perhaps I was checking factions as well, but not sure)

# Steps To Reproduce

1. Load save game.
2. Check factions (# tab tab)

# Expected behavior

Obviously, game not crashing.

# Screenshots

# Versions and configuration

 - OS: Windows 8.1
 - Game Version: 0.D-7950-ga718f4c
 - Graphics version: Tiles
 - Mods loaded: dda, disable NPC needs, generic guns, alternative map key, hydroponics, mining mod

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3666465/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3666466/debug.log)
[saveFile.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3666463/saveFile.zip)

**Comment by davidpwbrown** [comment]
Can you confirm if this is still happening on latest experimental?

**Comment by starytroll** [comment]
If I load the save on 8159-g6363709, it is still the same crash. Should I upload new crash log?

**Comment by davidpwbrown** [comment]
Confirmed on latest master. 
Possibly saved during the corrupted factions period, same gameplay would not cause it now, but will look into a fix for legacy savegames that might have a similar problem.
