### ISSUE TITLE
MP5 won't accept any sights or underbarrel mods

### ISSUE THREAD

**Issue by lllllllllllllllllllllllll** [CleverRaven/Cataclysm-DDA#34322]
# Describe the bug

The mp5 was modified recently so that it doesn't accept any underbarrel or sights mods. They were renamed from 'underbarrel' and 'sights' to 'underbarrel mount' and 'sights mount' on this gun only.

# Steps To Reproduce

1. Get MP5
2. Try to mount underbarrel mod (eg. Laser sight) or sights mod (eg. red dot sight, ACOG)

# Expected behavior

They should work

# Versions and configuration

Windows build 9687

# Additional context

The change was made in build 9638 commit named "mounts, while, and integral mods"

**Comment by ymber** [comment]
Intended behavior. The mod slots on the gun allow mount points to be attached to the gun and you can mount things on the mount points.
