### ISSUE TITLE
Crash on highlight 'cart handle' in vehicle build menu

### ISSUE THREAD

**Issue by Dunkhan** [CleverRaven/Cataclysm-DDA#34333]
# Describe the bug

The game crashes when highlighting the 'cart handle' item in the vehicle construction menu

# Steps To Reproduce

I am not sure that my save is required, it might work with a random new game. But the following steps are how I reproduce it:

1. Load the attached save
2. interact with a vehicle (works with both vehicles)
3. Move the cursor to a position with nothing built in it
4. scroll down the item list to the 'cart handle' item
5. Observe that the game crashes

# Expected behavior

Ideally also describe *why* you expect it to happen.

- OS: Linux
    - OS Version: Distributor ID: LinuxMint; Description: Linux Mint 19 Tara; Release: 19; Codename: tara; 
- Game Version: 0.D-7776-geba3646 [64-bit] (about 3 weeks old at time of posting)
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

https://pastebin.com/1iYyPY2L <- crash.log
https://pastebin.com/KV7n6fNC <- debug.log
[Lame Deer.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3667647/Lame.Deer.zip)

**Comment by Night-Pryanik** [comment]
Please update your game and retest it on latest experimental - I'm pretty sure this bug was already fixed.

**Comment by Dunkhan** [comment]
You are right. Sorry, I checked recent reports but not commits.
