### ISSUE TITLE
Debug Vision mutation non-functional.

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#34346]
#Describe the bug
My understanding of the debug vision mutation is that it acts like a clairvoyance artifact and reveals everything to the player, ignoring LOS and Light Level. It currently doesn't seem to do anything at all. 
 
# Steps To Reproduce
Load any world, debug mutate yourself, apply the Debug Vision mutation and wait a turn. Nothing changes.

# Expected behavior
The surroundings should be revealed, ignoring LOS and Light Level limitations.

# Screenshots
Night Time, no Debug Vision:
![image](https://user-images.githubusercontent.com/16219776/65883842-71aae680-e35d-11e9-9601-db0676721400.png)

Night Time, Debug Vision active:
![image](https://user-images.githubusercontent.com/16219776/65883776-54761800-e35d-11e9-9fe4-a15c0e1aaaf1.png)

Night Time, no Debug Vision, Clairvoyance Artifact in hand:
![image](https://user-images.githubusercontent.com/16219776/65884005-ae76dd80-e35d-11e9-8744-81e51ab9882f.png)

# Versions and configuration

 - OS: [Windows 10]
 - Game Version: [Cataclysm DDA version 0.D-8048-g7488d08]
 - Graphics version: [Tiles]
 - Mods loaded: [Cataclysm Fiddleheads]

# Additional context
Discovered while doing testing for the Add Ferns PR.

**Comment by Night-Pryanik** [comment]
It's working as it should.

Normal vision at night:
![изображение](https://user-images.githubusercontent.com/11132525/65888656-f115d580-e3b0-11e9-8cb0-5a5889dab5f4.png)

Debug night vision at night:
![изображение](https://user-images.githubusercontent.com/11132525/65888702-03900f00-e3b1-11e9-85f8-18c9fab22fef.png)

**Comment by Malkeus** [comment]
The description's a bit vague, isn't it? Ok then, thanks for taking the time to look into it.

**Comment by Night-Pryanik** [comment]
It's not meant to be super-clear, it's a debug mutation after all, devs could always look into the code to understand how it works.

**Comment by Malkeus** [comment]
Fair point, but all it would take is the addition of a single word to make
it clear. Any objections to me pushing a PR to that effect?

**Comment by anothersimulacrum** [comment]
I don't think anyone would object, but keeping an issue around about the issue is pointless.

**Comment by Malkeus** [comment]
I'm not at home, just replying to an email. *shrug*
