### ISSUE TITLE
Aiming Doesn't Display Fired Gun Sound Values Properly

### ISSUE THREAD

**Issue by GrandpuhTy** [CleverRaven/Cataclysm-DDA#34375]
# Describe the bug
After aiming a gun the sound display doesn't update properly to show the proper sound volumes of the weapon fired, it instead just displays '0'. When firing without aiming the display updates normally.

# Steps To Reproduce
1. Make a player with a gun, magazine, and some ammo.
2. Try to aim at a wall.
3. Fire gun, sound displays '0'
4. Fire without aiming
5. Sound displays correct value.

# Expected behavior
The sound display should update normally when aim-firing a gun.

# Versions and configuration

 - OS: W8.1
 - Game Version: 0.D-7906-g15709fa
 - Graphics version: Tiles
 - Mods loaded: 
"dda",
  "alt_map_key",
  "no_npc_food",
  "crt_expansion",
  "magiclysm",
  "FIC_Weapons",
  "growable-pots",
  "ew_pack",
  "makeshift",
  "More_Survival_Tools",
  "nw_pack",
  "modular_turrets",
  "Salvaged_Robots",
  "crazy_cataclysm",
  "hydroponics",
  "mutant_npcs",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "deoxymod",
  "blazemod",
  "Tanks",
  "necromancy",
  "DP_XOTTO_INDICATORS",
  "sees_player_retro",
  "manualbionicinstall",
  "safeautodoc",
  "StatsThroughSkills",
  "MST_Extra",
  "WildLiving",
  "cars_to_wrecks"

# Additional context
I had the game autosave after firing a weapon and while paused it displayed the correct sound value, but the game seemed to advance a few turns afterwards overwriting the displayed sound back to 0.

**Comment by ThomasLinkin** [comment]
Nah,if you checked correctly,it was during the shot are being taken does the sound took effect.or it's a bug no one figured out before,or it's related to ingame time did the shot take for the sound to display correctly

**Comment by Night-Pryanik** [comment]
Can't confirm. Spawned M14 with magazine and ammo. Aimed at the wall, fired, sound indicator show 257.
![изображение](https://user-images.githubusercontent.com/11132525/66036244-d3b24a00-e51d-11e9-82de-5189187dca1d.png)

**Comment by GrandpuhTy** [comment]
Here it is in action.
https://youtu.be/CnaBA9yI0oo

**Comment by Night-Pryanik** [comment]
Could you please test this on latest experimental, brand new world and brand new character and confirm if still an issue?

**Comment by GrandpuhTy** [comment]
Updated, tried with vanilla no mods and with same mod list. Can confirm it is still an issue. It seems that however the turns are processed due to time, it overwrites the sound display. 
As I mentioned in the main post, I didn't get it on camera, when the game paused to autosave it displayed the correct sound value for the gun I was firing but then exiting autosave it displayed '0'.

**Comment by Night-Pryanik** [comment]
Well, let's wait for confirmation from someone else.

**Comment by Myobu1** [comment]
Made a new world, new character, spawned a Remington 870 in, loaded it with 00-Shot, and fired at a wall several times. Sometimes, the sound would hit 159. Occasionally my ears would ring and I would wait to get my hearing back. Othertimes, the sound would be 0. I wasn't deaf either... I made sure to double check.

Also, are shotguns supposed to be able to destroy the walls of a house?
![Maple Calhoun __22-43-10_Eastern Standard Time](https://user-images.githubusercontent.com/44004977/66087228-bcd31e00-e544-11e9-87f9-3d03eced4710.png)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6416. Fired at the wall with and without aiming, sound indicator always displayed sound volume correctly.
Closing it for now. If this is still an issue, ping me and I'll reopen it.
