### ISSUE TITLE
It should be possible to build steerable vehicles without welding.

### ISSUE THREAD

**Issue by MalcolmRose** [CleverRaven/Cataclysm-DDA#34378]
PROBLEM STATEMENT:
Realism is, as far as I can tell, a priority in CDDA development. It is unrealistic that one cannot build a wooden cart, wagon, bicycle, etc without having welding tools. People had steerable vehicles long before the Industrial Revolution. As far as I can tell, the only way to get a steerable muscle-powered land vehicle (e.g. a bicicyle) is to either install controls, or wheel mounts - both of which require welding to be added to a vehicle. Even the default "wagon" vehicle inexplicably has "controls" even though it is a totally unpowered vehicle.

EDIT: After further testing, I've determined that controls actually aren't enough to make a vehicle steerable either.  Testing indicates that you do need wheel mounts, which indeed require welding.

PROPOSED SOLUTION:
There should be some sort of non-welding-required wooden alternative which makes vehicles steerable. Wooden axles, wooden wheel mounts, whatever.

**Comment by Xenomorph-III** [comment]
I mean a go kart of bike wheels and wooden planks, steered by rope would be possible, no 3 wooden frames, 2 axles and 4 bike wheels. And a "rope steering (short/long rope)

**Comment by kevingranade** [comment]
You need to be a bit more specific than, "some kind of vehicle". If you want to make e.g. a cart craftable, you need to outline what components are craftable from wood and how they are craftable etc.

Xenomorph's outline is a good start, though I'm skeptical of a muscle powered all wood gokart.

I'm not aware of any pure wood vehicles that are going to be particularly worthwhile, even wheelbarrows have metal hubs and rims.

**Comment by MalcolmRose** [comment]
Some examples of actual wooden vehicles that would be handy in escaping zombies IRL:

https://i.pinimg.com/originals/3f/bf/b1/3fbfb182f72d5dff3276b875866920cd.jpg (the wheel could just as easily be wooden in this picture)

The kind of wood wheel that could be used above: https://i.ytimg.com/vi/y0flRUfCpwo/maxresdefault.jpg

A wooden bicycle that a guy constructed which seems to work quite well:
https://www.youtube.com/watch?v=CcvFpbh2fjE

He uses aluminum rings for the chain but could just as easily be wood, the result would just be a little less durable. With the same exact concepts I don't see why you couldn't make a four wheeled wooden go-kart which is very helpful in toting around goods and escaping zombies. Momentum is a powerful thing.

With regards to wheelbarrows, I'm afraid you are incorrect. People have been using wheelbarrows (or wheelbarrow-like objects) to move stuff around basically since the dawn of agriculture. Here is a fully wooden wheelbarrow: 
https://images-na.ssl-images-amazon.com/images/I/71pERlGt4%2BL._SX355_.jpg

You can find many more examples of all-wood vehicles with a casual Google search. Real world justifications aside, I think what you're asking here is for specific implementation ideas. I think if it was me I'd just make wooden wheels steerable by default (sans mount) for simplicity's sake. Or I'd make a new type of fully-wooden-wheel that is steerable by default and maybe has less durability than a regular wheel. If this solution isn't amenable to you, I'm open to other ideas - at the end of the day I just know that you don't need to be able to do welding to make a muscle-powered steerable wooden vehicle, and I'd like that to be represented in game in some way or another.

**Comment by kevingranade** [comment]
The kickboards and bicycle are obviously toys, I'm not sure what kind of characteristics you're looking for here if you think those are valid examples. What are you imagining these things would be capable of, and how robust do you expect them to be?

>  I think if it was me I'd just make wooden wheels steerable by default

This is absolutely not happening, you still haven't provided any examples of robust steerable wooden wheels, but even if viable, they are not going to be the same level of complexity as a non-steerable wheel assembly.

**Comment by MalcolmRose** [comment]
> The kickboards and bicycle are obviously toys, I'm not sure what kind of characteristics you're looking for here if you think those are valid examples. What are you imagining these things would be capable of

I'm actually not sure what this is supposed to mean. Toys? Do you think that someone couldn't go faster with one of those objects - or rather, something like it - than with their own two legs? Or that they couldn't use the underlying concepts to at least build a simple cart to carry things for them? They could. To be clear, the point of those links was to demonstrate that this is clearly possible, not to give the most sturdy examples in existence.

> and how robust do you expect them to be?

Certainly less robust than something made of metal. Nevertheless still useful.

> you still haven't provided any examples of robust steerable wooden wheels

I don't understand what robust means in this context. All wheels break down over time. Are you really saying that it's impossible to build a viable, useful, steerable wooden wheel without welding technology? What about that wheelbarrow I posted? You said: "even wheelbarrows have metal hubs and rims." They don't have to - we can agree on that now based on what I posted, right?

How did human beings manage to farm large swathes of land for the many generations before welding existed? I mean, the acetylene torch was invented in 1836. If you're seriously suggesting that all wheeled vehicles - wagons, etc - were totally incapable of turning before this point, I don't know if I can say anything or offer any evidence to convince you otherwise. Exactly which part of an axle or wheel do you think can't be made out of wood instead of metal? Why not? Also, as an aside, it's worth mentioning that even if metal is involved in the construction, this doesn't necessarily mean that welding is required.

As a final note, as far as I can tell the game currently abstracts axles entirely.  Axles, swivel pins, "kingpins," linkages, etc are what actually allow a vehicle and its wheels to turn. Throwing a special "wheel mount" - or, as it is described in game, [b]"A piece of metal with holes suitable for a bike or motorbike wheel."[/b] onto a wheel is not really what lets it turn. If realism is important, perhaps this should be addressed.

Another great example of a very simple axle which requires no welding to construct: https://www.wikihow.com/Build-Your-Own-Kid%27s-Wagon

**Comment by esotericist** [comment]
point of order: welding has existed for a lot longer than the acetylene torch.

it's called "forge welding", and iron/steel components have been critical to useful vehicles for a very long time.

**Comment by Fris0uman** [comment]
>What about that wheelbarrow I posted?

But a wheelbarrow is not steerable, and you can already make one out of wood in game.

> to farm large swathes of land

This has nothing to do with steerable wheel. Horses are in the game and they are steerable

>currently abstracts axles entirely. 
Nothing to do with the point of wooden steerable wheels either

**Comment by MalcolmRose** [comment]
> point of order: welding has existed for a lot longer than the acetylene torch.
> 
> it's called "forge welding", and iron/steel components have been critical to useful vehicles for a very long time.

Okay, good point. Should forge welding be possible in game? If not, why not? 

> But a wheelbarrow is not steerable, and you can already make one out of wood in game.

Okay. Well, I was just correcting his false statement. Fair point that it's not an example of a wheel that turns.

> > currently abstracts axles entirely.
> 
> Nothing to do with the point of wooden steerable wheels either

Well, it has everything to do with it insofar as my main gripe is that welding is required to create a wooden vehicle that turns, and the current in-game-mechanical reason for that is that you need to weld in order to make a wheel mount. This bears pretty much no relation to the real world where you need axles, linkages, swivel pins, etc in order to turn a wheel.

**Comment by Fris0uman** [comment]
> a wheel mount

>elation to the real world where you need axles, linkages, swivel pins, etc in order to turn a wheel

The wheel mount is all those things, as far as I understand

**Comment by MalcolmRose** [comment]
> The wheel mount is all those things, as far as I understand

Is it? In game description: **A piece of metal with holes suitable for a bike or motorbike wheel**

>  does not bring proof that an entierly wooden steerable wheel is a viable idea

I'd like to reiterate that my main point is that welding shouldn't be required to make a steerable wheel, not that every single part of it needs to be made out of wood. See the little kid wagon I posted - at no point do the instructions suggest you should bust out a welder and throw on some welding goggles.

> Like we don't have a mechanic for it to get crushed under too much weight for exemple

Isn't there a weight mechanic in place? Even without code to destroy the wheels under such circumstances, couldn't you just have them apply a negative maximum weight modifier and make the vehicle incapable of moving above a certain limit?

**Comment by esotericist** [comment]
> Okay, good point. Should forge welding be possible in game? If not, why not?

Forge welding effectively is in the game. It's essentially part of the forging process for most hand-forged objects.

The current steerable wheel implementation abstracts away a lot of components, yes.

Kevin's assertions that things you linked are "toys" is because they are not, in fact, suitable for serious reliance. The bicycle above is a hilarious example of: yes, it's technically possible. No, it's not actually going to work for very long, or under real loads. You can actually hear and see it starting to come apart in the trial run.

If you want to submit a method of installing a non-steerable wooden wheel with hand-forged fittings which does not require welding tools, to make proper wheelbarrows, that's likely to be well-received.

Proper steerable wheels without explicit welding tools are *much* higher difficulty to fabricate than you seem to think, and are currently not seen as worth the trouble to model without a very strong argument in support of them. You have thus far failed to supply such an argument.

**Comment by MalcolmRose** [comment]
> Forge welding effectively is in the game. It's essentially part of the forging process for most hand-forged objects.

Going to have to disagree. Something on par with an acetylene torch is required for many recipes where forge welding would probably do the trick.

> Kevin's assertions that things you linked are "toys" is because they are not, in fact, suitable for serious reliance. The bicycle above is a hilarious example of: yes, it's technically possible. No, it's not actually going to work for very long, or under real loads. You can actually hear and see it starting to come apart in the trial run.

As I said, these were examples of the underlying techniques, not of robustness. Simply making the wooden bicycle wheels an inch wider would probably centuple its robustness. The bike itself was obviously built as a sort of model/replica, not an actual vehicle. Please, think abstractly here.

> Proper steerable wheels without explicit welding tools are much higher difficulty to fabricate than you seem to think

I've pointed out that it's possible and given several real world examples. Regarding difficulty: I'm no mechanical engineer, but if you gave me the materials, I could assemble an adult-size version of that children's wagon in a few hours. At a minimum I'd be able to carry all kinds of things in it. With a few minor modifications you could probably attach some pedals to it and turn it into a vehicle capable of carrying a person so that he can more easily enjoy the benefits of momentum. Do I need to make a video of me doing this for you to believe me? I can have my girlfriend dress up as a zombie and chase me while I run away from her in my steerable cart if you want.

> , and are currently not seen as worth the trouble to model without a very strong argument in support of them.

If I was a survivor in a zombie apocalypse I'd be doing literally anything I could to increase my speed in escaping zombies. This includes making rickety-but-effective wooden-wheeled carts if need be.

> You have thus far failed to supply such an argument.

I really don't think so. It's very unrealistic for this not to be possible, and it's very unrealistic that nobody would try it, especially if they were stuck in the woods with a bunch of raw materials and a need to raid nearby towns for medicine or food.

**Comment by I-am-Erk** [comment]
If your argument is that there should be more components manufactured in a forge that can be used to make wagon wheels and similar metal constructs, you might get some mileage. That is the only way forge welding would make sense for this. (Side note, we totally should be able to remove some damaged car parts and attempt to repair them in a forge rather than on the vehicle using a welder).

If your argument is still that you should be able to construct a functional standalone vehicle entirely out of wood, aside from things like travois and simple carts for light use, you're not going to get anywhere at all without references backing you up. You can make claims until you're blue in the face, but I've been a professional woodworker and am deeply skeptical such a thing would be possible in any way worth simulating.

As for necessity being the mother of invention, we're talking about a world swimming in metal vehicle parts here. Who on earth is going to spend weeks whittling an unshod wagon wheel that's going to break in half an hour when they could just use a bicycle wheel?

**Comment by MalcolmRose** [comment]
> If your argument is that there should be more components manufactured in a forge that can be used to make wagon wheels and similar metal constructs, you might get some mileage. That is the only way forge welding would make sense for this. (Side note, we totally should be able to remove some damaged car parts and attempt to repair them in a forge rather than on the vehicle using a welder).

This is a lot closer to what I'm arguing, yes. The bottom line of my argument is that modern welding technology should not be required to create a vehicle that is steerable. The way this currently shakes out in the game is that you need a welder or an acetelyne torch to make a vehicle capable of steering. Does this make sense to you? I've seen that primitive technology YouTube guy make forges out of random crap in the woods. https://www.youtube.com/watch?v=VVV4xeWBIxE

And these guys use similar techniques to create metal axes from scratch: https://www.youtube.com/watch?v=f0BjU20kU5E

It's pretty clear to me that crude steerable wheels could be created with similar techniques.

> If your argument is still that you should be able to construct a functional standalone vehicle entirely out of wood, 

I still think this is possible, but it's a lot less important to me than fixing the bigger issue of the modern welding requirement.

> Who on earth is going to spend weeks whittling an unshod wagon wheel that's going to break in half an hour when they could just use a bicycle wheel?

Probably me if getting ahold of the bicycle wheel means I have to contend with the actual living dead, but perhaps I'm overly fearful of getting my brains eaten.

**Comment by esotericist** [comment]
> Going to have to disagree. Something on par with an acetylene torch is required for many recipes where forge welding would probably do the trick.

Further demonstrating you have no idea what "forge welding" actually means any more than you understand any of the other things that have been discussed.

This isn't really going anywhere at this point. As I said earlier, if someone wants to submit the necessary bits to be able to manufacture a wheelbarrow without an explicit welding tool, that could be well received.

The rest is not sufficiently well argued. There is no reason to believe the random novelties you've linked are in any way fit for purpose (and a lot of reason to believe they are not), and more useful analogs would have effectively a higher bar than just getting welding going.

Just because something is technically possible doesn't mean it's actually worth implementing.

**Comment by MalcolmRose** [comment]
Well, that certainly was very disrespectful and rude.

**Comment by kevingranade** [comment]
The concept you're presenting, once toned down to things like wheelbarrows and carts, has some potential of being adopted, but this conversation is not productive.

There are significant tradeoffs inherent in all- or mostly- wood construction, we care about those tradeoffs, but you seem to be intent on pretending they don't exist or aren't important enough to consider, this is irreconcilable

**Comment by I-am-Erk** [comment]
> Well, that certainly was very disrespectful and rude. But hey, keep having a game where throwing random bits of metal onto a wheel magically makes it steerable. Seems very realistic. I bow to your wisdom and profusely apologize for my insufficiently well argued arguments.

Several people all came and talked to you about your idea and gave you a chance to state your case, dude. Eventually issues get closed, that's not disrespect, it's the way the project works. If you think multiple developers talking to you over the course of several hours is disrespectful because they don't bow to your suggestions, you aren't going to be able to work as part of a team.

**Comment by MalcolmRose** [comment]
> but you seem to be intent on pretending they don't exist or aren't important enough to consider, this is irreconcilable

I presented a clear and obvious problem to you: welding **shouldn't be required to make crude steerable vehicles because it isn't required for that in real life.** You seem to be intent on ignoring this obvious unrealistic flaw in the game,  if only because I haven't given a treatise regarding my thoughts on the tradeoffs. If you think that some sort of downsides should come with non-welded steerable vehicles, by all means, present them. I thought this was the purpose of threads like these, to collaboratively come up with solutions. 

> Eventually issues get closed, that's not disrespect, it's the way the project works. 

"Further demonstrating you have no idea what "forge welding" actually means any more than you understand any of the other things that have been discussed." That doesn't look disrespectful to you? Really?

**Comment by I-am-Erk** [comment]
Given that you have repeatedly demonstrated that you don't know what it means, of course it's not disrespect. It's a clear observation. You don't seem to have even been aware of the concept a few hours ago, so I don't know why you'd try to argue otherwise.

**Comment by bobchaos** [comment]
fwiw, I did some research on my end, came up with tons of examples of wooden vics, but all of them had 1 thing in common: a metal axle joint or however it's called. Even the "splinter", the most wooden car I could locate, describes every individual part being made of wood, but interestingly skips right over the description of the axle

**Comment by MalcolmRose** [comment]
I knew about it, I just didn't know that was the proper name for it. It's not exactly complicated: you basically just heat up two pieces of metal and hammer them together. Why are we pretending that this is too complex for my feeble little brain to grasp? *Frankly, this is further demonstrating you have no idea what I actually meant, any more than you understand anything else in the thread.* Hey, did that italics phrase seem insulting to you? That's basically what your colleague just said to me.

Anyway, I made it clear that welding *as it is currently depicted in the game* is a requirement for making steerable vehicles, and it shouldn't be.

I'd like to reiterate that this is less about 100% wooden vehicles than fixing the fact that a simple, primitive forge would let people make steerable vehicles from scratch. Please note that the title of the thread is: **"It should be possible to build steerable vehicles without welding."** To clarify, "welding" means "welding as it is currently depicted in the game."

**Comment by FaNToMKH** [comment]
FaNToM
![wooden carriage](https://user-images.githubusercontent.com/65818621/82733948-28f6d200-9d20-11ea-9fe4-762a9c07052d.png)

**Comment by ZhilkinSerg** [comment]
Can you please send as your drawing in Kompas 3D format, okay?

**Comment by FaNToMKH** [comment]
LoL Friend, 

If I had that software, or the skills to create any CAD design, I 'd be working in software engineering, mechanical engineering or whatever,, anyone without engineering skills (I believe) can understand the drawing. 
Maybe you unswered because you want to get some laughs.... and posted some smart ass request.

I ll try to make you a small scale design video with straws and cartons, just for the fun of it, if I get the time, since I have a full time job.

**Comment by ZhilkinSerg** [comment]
> LoL Friend,
> 
> If I had that software, or the skills to create any CAD design, I 'd be working in software engineering, mechanical engineering or whatever,, anyone without engineering skills (I believe) can understand the drawing.
> Maybe you unswered because you want to get some laughs.... and posted some smart ass request.
> 
> I ll try to make you a small scale design video with straws and cartons, just for the fun of it, if I get the time, since I have a full time job.

We all have jobs. Still you have to oblige our standards and send your drawings using an agreed filebformat.

**Comment by NegInfinity** [comment]
I've found this thread while googling after wondering why adding controls to a wooden cart with electric motor requires welding.

Here's a video of someone building a mostly wooden car. Axles are metal, and there's electric motor. 
https://www.youtube.com/watch?v=2mVt1FGYLr4
Now, there are two welded parts, but they belong to steerable wheel mount and could be attached using alternative methods (rivets, bolts, wires)

Her is an example of wooden car model with steering.
https://www.youtube.com/watch?v=qFu-Wer1dQg

Here's a wooden bicycle:
https://www.youtube.com/watch?v=0yJdz-kjfLk

**Comment by esotericist** [comment]
the controls object in-game is meant to represent specifically an automotive control set (modern steering wheel, accelerator, brake, etc). apparently our wagons use this (!), and that's incorrect; we should have some wooden analog for that. feel free to open something for it.

electric motor installation already requires other tools than welding.
