### ISSUE TITLE
Tardis spear strap

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#34380]
# Describe the bug

When using a spear strap which has a volume of 0,5 l and insert a spear into it, it stays at 0,5 l instead of adding up to at least a bit more than the volume of the spear itself.

# Steps To Reproduce

1. Have a spear (for example wooden) and a spear strap in your inventory
2. activate spear strap to put in spear
3. spear strap with content stays at 0,5 l Volume

# Expected behavior

Have at least the volume add up to the spear volume. Probably a few ml more.

# Screenshots
attached
![sep](https://user-images.githubusercontent.com/33199510/65989934-eb8cbe00-e48a-11e9-97c0-a5da61c8ef2a.jpg)
![tog](https://user-images.githubusercontent.com/33199510/65989935-eb8cbe00-e48a-11e9-8822-10b0bba571e8.jpg)

# Versions and configuration

Version 9699

**Comment by Night-Pryanik** [comment]
I don't understand what's an issue here. Your pics correctly show reduction in carried volume of your character after holstering the spear (1,75 -> 0,5). If you mean this volume:

![изображение](https://user-images.githubusercontent.com/11132525/66023355-f9c9f100-e501-11e9-8cf4-34c3219b1b80.png)

it just shows the volume of base item, without any content. I don't think it's a bug per se.

**Comment by Lamandus** [comment]
but then why is the wooden spear loosing its volume when inside the strap? That doesn't make any sense. The spear has a volume of 1,25 l by itself. So how is it when it is inside the strap 0 - 0,5 l?

**Comment by Night-Pryanik** [comment]
> why is the wooden spear loosing its volume when inside the strap?

That's intended behavior. Holstered spear isn't in your virtual "pockets" or "bags" anymore, so to say, so it doesn't occupy any volume.

**Comment by Lamandus** [comment]
> That's intended behavior. Holstered spear isn't in your virtual "pockets" or "bags" anymore, so to say, so it doesn't occupy any volume.
but that doesn't make any sense.
As you can see both items (spear and strap) are inside the travelpack. The wooden spear has a volume of 1,25 l. The strap of 0,5 l. It makes 1,75 l. (as seen in first of mine screenshots). When you put the spear into the strap, WHILE STILL IN THE TRAVELPACK(!), the volume magically decreases to 0,5 l. So tell me, how is it possible to lower the volume of a rigid item (wood spear) from 1,25 l to actually nill, While still in the travelpack?

**Comment by Night-Pryanik** [comment]
Oh, I get it. The volume reduction of holstered items should only occur for worn straps/holsters/etc.
