### ISSUE TITLE
ChestHole32 Missing

### ISSUE THREAD

**Issue by starfire213** [CleverRaven/Cataclysm-DDA#34385]
There isn't a chesthole32 tileset

# Expected behavior

For there to be a chesthole32 tileset

# Versions and configuration

 - OS: [Windows 10]
 - Game Version: [0.D-8109-ga8dfd59]
 - Graphics version: [Tiles]
 - Mods loaded: [N/A]

# Additional context

There *is* a chesthole16 but that is super pixelated

**Comment by I-am-Erk** [comment]
Chesthole was removed as it contained copyright violating material, as with many of the other tilesets. Artists are working on a solution.

**Comment by LaVeyanFiend** [comment]
Chesthole 32 is one of the tilesets under copyright violation. 16 is not.

![image](https://user-images.githubusercontent.com/51099123/66003913-60ed9400-e475-11e9-9e98-12468892562d.png)

Closing time.

**Comment by starfire213** [comment]
eh I fixed it by grabbing it on a earlier build
