### ISSUE TITLE
Error when NPC follower leaves a vehicle

### ISSUE THREAD

**Issue by AllSystemsGo** [CleverRaven/Cataclysm-DDA#34383]
# Describe the bug

When a melee NPC follower boarded a destroyed vehicle to kill a zombie, after leaving the vehicle I get this error every turn:

![image](https://user-images.githubusercontent.com/4836641/66000382-29babb00-e454-11e9-9fd0-29b2b7c1ac4d.png)

# Steps To Reproduce

1. Have a follower NPC board a vehicle's wreckage
2. Have the NPC then leave the vehicle
3. Witness the above error occur every turn.

# Expected behavior

This error should not occur when a follower leaves a vehicle

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

( **Note**: The in game 'generate report' feature does not report the correct game version. This can also be seen in the log below; I am not running '0.D-8109-ga8dfd59')

 - OS: WIndows 10
 - Game Version: Build #9699 64 bit
 - Graphics version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Vehicle Additions Pack [blazemod],
    Crazy Cataclysm [crazy_cataclysm],
    Tanks and Other Vehicles [Tanks],
    DinoMod [DinoMod],
    No Rail Stations [No_Rail_Stations],
    Safe Autodoc [safeautodoc],
    Disable NPC Needs [no_npc_food]
]

# Additional context

13:45:02.352 : Starting log.
13:45:02.352 INFO : Cataclysm DDA version 0.D-8109-ga8dfd59
13:45:02.448 INFO : Number of render drivers on your system: 4
13:45:02.448 INFO : Render driver: 0/direct3d
13:45:02.449 INFO : Render driver: 1/direct3d11
13:45:02.449 INFO : Render driver: 2/opengl
13:45:02.449 INFO : Render driver: 3/software
13:45:02.453 INFO : Language is set to: 'en'
13:45:03.026 INFO : SDL version used during compile is 2.0.5
13:45:03.026 INFO : SDL version used during linking and in runtime is 2.0.5
13:45:03.155 INFO : Active renderer: 1/direct3d11
13:45:03.495 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
13:45:03.651 WARNING : opendir [./mods/] failed with "No such file or directory".
13:45:07.422 WARNING : opendir [./save/Dying Light II/mods] failed with "No such file or directory".
13:45:18.525 INFO : Loaded tileset: MSX++DEAD_PEOPLE
14:00:15.552 ERROR : (error message will follow backtrace)
	(@0x5cb87e[cataclysm-tiles.exe+0x1cb87e]), 
	(@0x5cbeba[cataclysm-tiles.exe+0x1cbeba]), 
	(@0x5cf2a6[cataclysm-tiles.exe+0x1cf2a6]), 
	(IMG_LoadWEBP_RW+0x111425@0x118b6f5[cataclysm-tiles.exe+0xd8b6f5]), 
	(@0x917411[cataclysm-tiles.exe+0x517411]), 
	(@0xb57829[cataclysm-tiles.exe+0x757829]), 
	(@0xb57cc8[cataclysm-tiles.exe+0x757cc8]), 
	(@0xb5fe57[cataclysm-tiles.exe+0x75fe57]), 
	(@0xb63152[cataclysm-tiles.exe+0x763152]), 
	(@0x6de535[cataclysm-tiles.exe+0x2de535]), 
	(@0x6dfc94[cataclysm-tiles.exe+0x2dfc94]), 
	(IMG_LoadWEBP_RW+0x618ed8@0x16931a8[cataclysm-tiles.exe+0x12931a8]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0x14@0x7fff451b7bd4[KERNEL32.DLL+0x17bd4]), 
	(RtlUserThreadStart+0x21@0x7fff4712ce71[ntdll.dll+0x6ce71]), 
Backtrace emission took 0 seconds.
src/map.cpp:982 [void map::unboard_vehicle(const tripoint&, bool)] map::unboard_vehicle: vehicle not found
14:00:23.320 ERROR : src/map.cpp:982 [void map::unboard_vehicle(const tripoint&, bool)] map::unboard_vehicle: vehicle not found
14:00:25.417 ERROR : src/map.cpp:982 [void map::unboard_vehicle(const tripoint&, bool)] map::unboard_vehicle: vehicle not found
14:00:27.320 ERROR : src/map.cpp:982 [void map::unboard_vehicle(const tripoint&, bool)] map::unboard_vehicle: vehicle not found
14:00:29.689 ERROR : src/map.cpp:982 [void map::unboard_vehicle(const tripoint&, bool)] map::unboard_vehicle: vehicle not found
14:00:33.216 ERROR : src/map.cpp:982 [void map::unboard_vehicle(const tripoint&, bool)] map::unboard_vehicle: vehicle not found
14:00:34.403 ERROR : src/map.cpp:982 [void map::unboard_vehicle(const tripoint&, bool)] map::unboard_vehicle: vehicle not found
14:01:01.297 ERROR : src/map.cpp:982 [void map::unboard_vehicle(const tripoint&, bool)] map::unboard_vehicle: vehicle not found
14:01:09.752 WARNING : opendir [./save/Dying Light II/mods] failed with "No such file or directory".
14:01:15.574 INFO : Loaded tileset: MSX++DEAD_PEOPLE
14:01:21.177 ERROR : (error message will follow backtrace)
	(@0x5cb87e[cataclysm-tiles.exe+0x1cb87e]), 
	(@0x5cbeba[cataclysm-tiles.exe+0x1cbeba]), 
	(@0x5cf2a6[cataclysm-tiles.exe+0x1cf2a6]), 
	(IMG_LoadWEBP_RW+0x111425@0x118b6f5[cataclysm-tiles.exe+0xd8b6f5]), 
	(@0x917411[cataclysm-tiles.exe+0x517411]), 
	(@0xb57829[cataclysm-tiles.exe+0x757829]), 
	(@0xb57cc8[cataclysm-tiles.exe+0x757cc8]), 
	(@0xb5fe57[cataclysm-tiles.exe+0x75fe57]), 
	(@0xb63152[cataclysm-tiles.exe+0x763152]), 
	(@0x6de535[cataclysm-tiles.exe+0x2de535]), 
	(@0x6dfc94[cataclysm-tiles.exe+0x2dfc94]), 
	(IMG_LoadWEBP_RW+0x618ed8@0x16931a8[cataclysm-tiles.exe+0x12931a8]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0x14@0x7fff451b7bd4[KERNEL32.DLL+0x17bd4]), 
	(RtlUserThreadStart+0x21@0x7fff4712ce71[ntdll.dll+0x6ce71]), 
Backtrace emission took 0 seconds.
src/map.cpp:982 [void map::unboard_vehicle(const tripoint&, bool)] map::unboard_vehicle: vehicle not found
14:01:23.017 ERROR : src/map.cpp:982 [void map::unboard_vehicle(const tripoint&, bool)] map::unboard_vehicle: vehicle not found

**Comment by TealcOneill** [comment]
@GuardianDll Can't replicate. 👍
