### ISSUE TITLE
extra-dimensional entity powered locomotion (AKA the Zombie harness)

### ISSUE THREAD

**Issue by bobchaos** [CleverRaven/Cataclysm-DDA#34418]
**Is your feature request related to a problem? Please describe.**  
Yes, it's a horrible problem, I have to make poor horses pull my carriage when there's all the perfectly good zombies wandering about!

**Describe the solution you'd like**  
Essentially I would like to see existing harness mechanics be applicable to zombie slaves using a man-sized harness, perhaps adding to the "zombie" engine type a "meat" fuel type that deplete very very slowly and is stored in the harness proper (Basically, you hang a chunk of meat in front of them, and it's good until it decomposes).

**Describe alternatives you've considered**  
What more could any survivor want than infinite, renewable, and wonderfully ironic energy source? :D And the answer to that is of course a threadmill and a 7.5k generator, but that's for another day.

**Additional context**  
I'm willing to take a crack at writing the code but I'd need a bit of direction. I've been able to track down the harness examine action to here https://github.com/CleverRaven/Cataclysm-DDA/blob/a8dfd5986cc25918d0ef422d1737cec5a57671ab/src/vehicle_use.cpp#L1565 but zombie slaves would be currently excluded on account of not being technically friendly. The condition could be removed, or I could add an exclusion for zombie slaves, or we could decouple the function that handles zombies from the one that handles tame animals. Thoughts?

I haven't dug that deep yet but I also not a notion of harness body type, so presumably this would require a new item and matching vic part, along with the correct flags being added to zombie slaves and a new engine type. If I'm missing anything lemme know.

**Comment by kevingranade** [comment]
This should not provide direct movement control over a team of zombies. They would be "uncooperative" to say the absolute least, and in reality they would want nothing more than to turn around and try to kill the player, or start fighting anything else that comes near.

Regardless of you rendering them unable to harm you, that means they're going to be stumbling around trying to get at the driver instead of dragging the vehicle where you want it to go.

**Comment by bobchaos** [comment]
remove airways (so it can't smell), add blinkers and dangle food in front no? We're not counting on zombies being cooperative of course, but on having extremely predictable, and therefor controllable, behavior. Maybe this could be represented by requiring high skills to craft the harness, or require a special type of slave zombie used specifically to pull at stuff. A "brake" could come in the form of a rope around the legs, but above the knee so as to not trip the zombies, that can be tightened.

Worth a thought

**Comment by PaulBlay** [comment]
This could work, but only if you walk in front of them as a tasty, tasty, zombie treat.

Or maybe you could recruit an NPC and name him 'carrot'.

**Comment by RDru** [comment]
How about hanging a petpack with a small animal like cat or chicken in front of them? :)
The problem would be how to stop them.

**Comment by kevingranade** [comment]
> We're not counting on zombies being cooperative of course, but on having extremely predictable, and therefor controllable, behavior. 

That's exactly my point, they do NOT have predictable or controllable behavior.

They aren't food driven, they're killing driven, so a little chunk of meat isn't going to be particularly compelling, and even if you put something in front of them that they're willing to chase, they're still going to lurch around in random directions as they try to chase it at different speeds.

As far as simply slapping the "friendly" tag on them, that's a hard no.  If you want to implement this it needs to be a lot more nuanced and handle the zombies trying to escape, pulling in different directions, attacking each other, going off course, etc.

**Comment by bobchaos** [comment]
I've thought about this over night, here's my final pitch:
Having the zombies be uncooperative would be great, but I wouldn't know where to begin programming that, Cata's codebase is enormous. That said, sticking with (mostly) existing mechanics, I think controlling a zombie slave, with appropriate equipment, should be possible. The harness would be the key component, as it would be responsible for 2 key aspects: restricting the zombie's movements (ie: the brakes), and dulling the zombie's senses. I first talked about blinders, but now I'm thinking more of a full helmet being part of the harness, with some mechanism to "open" it, allowing the zombie to see some bait dangled in front (the accelerator if you will). The helmet in question would be airtight as to prevent the zombie from smelling, and include a pair of built-in earplugs. Whatever is used as bait would simply moved to the edge of the zombie's helmet restricted vision to "steer"

I imagine a contraption made of leather and steel, with mechanical components to allow opening and closing the visor remotely, along with constricting movement. Crafting the harness would require high fabrication (it does involve some precise metalsmithing) and mid level mechanics. Installing the harness would require mid-level mechanics.

If that doesn't describe something the maintainers find plausible I'll drop it, but I'm pretty convinced that this could work

**Comment by AMurkin** [comment]
Just let them push, and not pull. Player in front of Zs.

**Comment by tenmillimaster** [comment]
Alternate proposal: this being only viable on rails. Any movement they make is translated into either forwards or backwards, slightly more controllable.

**Comment by mouseturd** [comment]
Combine with zombie pheromones so they zombies aren't trying to lunge at you?
