### ISSUE TITLE
NPC has Venom Mob Protege despite Mythical Martial Arts not being installed

### ISSUE THREAD

**Issue by DanteTorn** [CleverRaven/Cataclysm-DDA#34412]
# Describe the bug

My NPC follower has the Venom Mob Protege trait despite the fact that I do not have Mythical Martial Arts installed.

# Steps To Reproduce

N/A, due to random nature of NPC traits.

# Expected behavior

VMP was removed from the game and moved to Mythical Martial Arts, which I do not have installed, therefore it shouldn't show up in NPCs.

# Screenshots

![idiot clothing 2](https://user-images.githubusercontent.com/35230199/66090472-69c88d80-e57b-11e9-9f4f-75a9fa3ecc35.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-7542-ga5d33f6 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Fungal Monsters [No_Fungi],
    No Gasoline Boomers [No_Gasoline_Boomers-DANTE],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    Stats Through Kills [stats_through_kills],
    Hair aka Rainbow [Hairs]
]

# Additional context

My zipped save file is too big to link here, sadly.

**Comment by ZhilkinSerg** [comment]
> My zipped save file is too big to link here, sadly.

Use dropbox, zippyshare or google drive.

**Comment by DanteTorn** [comment]
https://drive.google.com/open?id=12GbeqloL74TPDZzX3RWPNFuDR3C_dW95

**Comment by Night-Pryanik** [comment]
Venom Mob Protege still exists in vanilla (alongside with many other fictional martial arts). I'm not sure if it's an oversight - all fictional martial arts should be moved to a mod? Or it's intended, and fictional martial arts should sometimes spawn as a valid martial arts style for NPCs (and only NPCs)?

In any case, that's not a bug, and MMA mod isn't related, as this martial art exists in vanilla.
