### ISSUE TITLE
Fatal crash on neutral NPCs angered from deaf players when attacking

### ISSUE THREAD

**Issue by Axema** [CleverRaven/Cataclysm-DDA#34427]
# Describe the bug

A neutral NPC got angered from players not responding with `deaf` status, then crashes when  the NPC attacks. 

# Steps To Reproduce

1. Deafen yourself (grenade explosions, etc.)
2. Go and talk with a neutral NPC that spawned newly into the world.
3. The [crash log](https://imgur.com/a/Z6rpQ1e) will appear.

# Expected behavior

NPCs attacking the unable-to-respond `deaf` player should not lead to a fatal crash.

# Versions and configuration

 - OS: Windows 7 Ultimate
 - Game Version: 0.D-8176-ga35bb25
 - Graphics version: Tiles
 - Mods loaded: just a plain cdda

# Additional context

This is the [crash log](https://pastebin.com/3w0ptRUQ).

**Comment by ZhilkinSerg** [comment]
Confirmed. Possibly caused by #34110. I guess `is_npc` check is missing here:

![image](https://user-images.githubusercontent.com/16213433/66139843-c6728980-e609-11e9-901e-2ec40f947372.png)
