### ISSUE TITLE
Using Battery CBM to Eat batteries can result in them disappearing

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#34424]
If you 'Eat' the a battery down to the last charge point then it disappears.

# Steps To Reproduce

1. Take a battery, drop it on the ground. Make sure it has less charge than your maximum bionic power.
2. Use up a bunch of bionic power (welding repairs to wreck or whatever)
3. Stand over battery and 'E'at it to restore your bionic power.
4. Battery will vanish, instead of remaining with zero charge.
5. (Optional) *Burp*

You should have a flat battery left behind. Because your character does not literally chew, crunch up and swallow batteries with this CBM.

**Comment by RDru** [comment]
It won't disappear if you have it in your inventory. But I can confirm it disappears if you eat batter that is outside of your inventory.

**Comment by PaulBlay** [comment]
I was just about to add that.
