### ISSUE TITLE
When Pigs Flee

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#34439]
You like the title?  The title is why I'm posting it now, instead of stashing in a list of bugs to report later then never getting around to it.

# Describe the bug
On a newly discovered farm with (hostile) pigs inside a pig pen, I went to go fight a zombie.  Before I could, the zombie reached the pigs first and they were all fighting.  The pigs started fleeing, and they are able to pass right through the fence while fleeing.

# Steps To Reproduce

1. Watch pigs and zeds fight.
2. ...?
3. Profit

# Expected behavior
I expect the pigs to flee until they reach a barrier like a fence.  Then they should either bash through it or be kept inside and try to flee a different direction.
Expected behavior may be different for a horse.

# Screenshots

# Versions and configuration
9708, windows

# Additional context
Savegame after the fact is available upon request
Fences are all intact, no open gates.
White (farm) picket fence.

**Comment by Night-Pryanik** [comment]
Picket fence is perfectly traversable by every type of creature, so we probably should replace it with something more restraining, like chickenfence or chainfence.

**Comment by PaulBlay** [comment]
Possibly unrelated, but it looks like three pigs escaped through the fence at the Ranch. Getting in the way on the road.

**Comment by danielkwinsor** [comment]
Well, I also just saw chickens pass through chickenwire fence.
