### ISSUE TITLE
Crash upon examining water on ground.

### ISSUE THREAD

**Issue by Myobu1** [CleverRaven/Cataclysm-DDA#34437]
I deconstructed a water heater. I dragged the resulting materials away to my storage space and (e)xamined the water left behind. This caused my game to crash. The prompt mentioned a "SIGFPE: Arithmetical Error" when the crash happened.

1. Deconstruct filled water heater.
2. Examine the water left on the ground.
3. Experience game crash.

OS: Windows 10 Professional
Game Version: 0.D-8185-g1011e58
Graphics Version: Tiles
Mods loaded: No Flaming Weapons, No Survivor Armor, Disable NPC Needs

Debug and Crash Logs: [config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3688103/config.zip)
Screenshot:
![Screenshot (132)](https://user-images.githubusercontent.com/44004977/66164693-3b8d9100-e601-11e9-9c3b-455ab6ef3dcb.png)

**Comment by ZhilkinSerg** [comment]
Cannot reproduce on latest experimental version.
