### ISSUE TITLE
What is the max power level?

### ISSUE THREAD

**Issue by Pmm5000** [CleverRaven/Cataclysm-DDA#34449]
# Describe the bug
I wasn't really sure where to ask this, but I noticed  that the max power level has been capped in the recent update and I actually have a bionic that I made for my own personal use.

Here it is.
[
  {
    "id": "bio_power_storage_mkIII",
    "type": "bionic",
    "name": "Power Storage Mk. III",
    "capacity": 500000000,
    "description": "A Compact Bionics Module that increases your power capacity by 250000 units."
  }
]
 
The ridiculously high number for capacity was done to see just what the actual capacity that I can achieve is, and I got 1803 kJ. Which.....it irritatingly small considering the consumption of a large number of bionics. (On a cool note, it doesn't give me the error code stating that it is beyond what it can handle.)

So I guess what I'm trying to ask is, is 1803 kJ the maximum power I can get, and if so, how do I increase it? 

# Steps To Reproduce

1. Get a bionic with a large power capacity.
2. Observe Power levels. 
3. Use whatever method you desire to max it out. 
4. Note it down.

# Expected behavior

I was expecting a large power capacity. However, as explained above it's a mere 1803 kJ, which is no where near enough power for my entertainment. 

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-8187-g1acb13e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Personal Cheats [personal_cheats],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Modular Turrets [modular_turrets],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    PKs Rebalancing [PK_REBALANCE],
    Salvaged Robots [Salvaged_Robots],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    Alternative Map Key [alt_map_key],
    EZ-Mode Medical [fast_healing],
    Mutant NPCs [mutant_npcs],
    Hydroponics [hydroponics],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    No Antique Firearms [no_olg_guns],
    No Filthy Clothing [no_filthy_clothing],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Sleep Deprivation [sleepdeprivation],
    Stats Through Kills [stats_through_kills]
]

 
# Additional context

Nah, just a very curious player who cheats. A lot.

**Comment by ZhilkinSerg** [comment]
Maximum power level is `units::energy_max` (https://github.com/CleverRaven/Cataclysm-DDA/pull/34435). This number is dependent on `int` type capacity on your system, but should be at least 16 bits or (see https://en.cppreference.com/w/cpp/language/types).

**Comment by Pmm5000** [comment]
![image](https://user-images.githubusercontent.com/10760413/66263849-38400400-e7bf-11e9-9477-608cfe0525e2.png)


Sorry for opening this up again. So, I changed the values of my bionic for power capacity right? 
And based off what you said, I should at least get up to 2^16 max power or 65536 kJ in this case. 

However....I can't even get 2500 kJ max power. Actually, upon a variety of further resets involving the above mods, the best I've gotten was 2120 after setting my custom bionic to 2100 units, otherwise it goes straight to -2127.

Even after disabling almost every mod and just using Magiclysm and my personal cheat mod with no NPC starving, my limit is about 2120. I'm going to guess that the -2127 means that 2126 or so is my actual limit. 

I tried a version where I left my stats alone at regular values and same issue. How do I fix this?

**Comment by anothersimulacrum** [comment]
The most power you can have is 2^31 mJ of power, or about 2100 kJ.
Apply #34431 locally to increase that number.

**Comment by Pmm5000** [comment]
Oh. I recognize your name from my constant searches. 

So really nifty issue. 
I did this using the nearest bionic profession in the main profession list.
{
    "type": "profession",
    "ident": "bionic_prepper",
    "name": "Bionic Prepper",
    "description": "You knew the end was coming.  You augmented yourself with some basic bionics and got additional survival training.  Now the end has come, and it is time to see if your efforts have paid off.",
    "points": 6,
    "CBMs": [
      "bio_metabolics",
      "bio_power_storage_mkII",
	  "bio_power_storage_mkII",
		"bio_power_storage_mkII",
		"bio_power_storage_mkII",
		"bio_power_storage_mkII",
		"bio_power_storage_mkII",
		"bio_power_storage_mkII",
		"bio_power_storage_mkII",
		"bio_power_storage_mkII",
		"bio_power_storage_mkII",
      "bio_tools",
      "bio_flashlight",
      "bio_lighter",
      "bio_evap",
      "bio_climate",
      "bio_taste_blocker"
    ],
    "skills": [
      { "level": 4, "name": "survival" },
      { "level": 3, "name": "fabrication" },
      { "level": 3, "name": "cooking" },
      { "level": 2, "name": "firstaid" },
      { "level": 2, "name": "gun" },
      { "level": 2, "name": "rifle" },
      { "level": 2, "name": "melee" },
      { "level": 2, "name": "cutting" },
      { "level": 1, "name": "bashing" }
    ],
    "items": {
      "both": {
        "items": [
          "hat_boonie",
          "tshirt",
          "gloves_fingerless",
          "pants_cargo",
          "socks",
          "boots",
          "trenchcoat",
          "knit_scarf",
          "backpack",
          "canteen",
          "smart_phone",
          "wristwatch",
          "binoculars"
        ],
        "entries": [
          { "item": "crossbow", "ammo-item": "bolt_steel", "charges": 1, "contents-item": "shoulder_strap" },
          { "item": "bolt_steel", "charges": 20, "container-item": "quiver" },
          { "item": "machete", "container-item": "scabbard" }
        ]
      },
      "male": [ "boxer_shorts" ],
      "female": [ "sports_bra", "boxer_shorts" ]
    }
  },

Even just disabled all mods except for the base game.
And this happened. 

![image](https://user-images.githubusercontent.com/10760413/66264295-21ea7600-e7c8-11e9-9a2e-31ef23b1d6db.png)

**Comment by anothersimulacrum** [comment]
That profession does not exist in the base game?

**Comment by Pmm5000** [comment]
Really? Like I went into cdda game launcher>cdda>data>json, opened up professions.json and found it? And it's a pretty large file? 140 or so KB.  I literally was just looking for the first profession that used bionics, and it's the second one in the file after the all of the items it listed for some reason. Is it really not in the base game? Am I playing with some weird version?

**Comment by anothersimulacrum** [comment]
There is a profession with that id that is very similar, but does not have the same JSON definition as the one you posted.

**Comment by Pmm5000** [comment]
Oh. Yeah I gave him a bunch of mK II power storage to check to see if I was going crazy or if it was a random mod causing my power continuously going negative.
