### ISSUE TITLE
Crouching behind a visibility blocking terrain doesn't block visibility for player

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#34442]
# Describe the bug
Crouching behind low terrain blocks other characters' ability to see the player, but does not block the player from seeing past the terrain.

# Steps To Reproduce
1. Deploy a cardboard box
2. Crouch behind the box
3. See past the box while using it to sneak up on things that can't see you.
[example](https://media.giphy.com/media/mBoyMbacJ76ERAo1Ya/giphy.gif)

# Expected behavior
If you can't be seen from behind the terrain, you also can't see through it.

# Screenshots

https://media.giphy.com/media/mBoyMbacJ76ERAo1Ya/giphy.gif

# Versions and configuration

present in v9707 windows tiles.

# Additional context

Turrets should also return fire on any unseen attacker.

**Comment by LaVeyanFiend** [comment]
Ya gonna nerf my strategy to kill lab turrets by crouch-shooting behind a grabbed drawer are ya? 😛
