### ISSUE TITLE
Skills overhaul suggestion

### ISSUE THREAD

**Issue by SaltGin** [CleverRaven/Cataclysm-DDA#34440]
**Is your feature request related to a problem? Please describe.**  

It's too op to become a professional engineer after several days by reading books...
Related to that, it would be great if we reconsider the mechanism of skill rust.

**Describe the solution you'd like**  
Every single skill could separate into two values:

One is the "fake skill" value that you learned from books or NPCs, that allow you to achieve the skill requirement for complex tasks, like vehicle repairing or fabrication. It rusts fast and provide limited task speed bonus.

Another one we can call it "true skill", it is the skill value that player actually "learned", which provides full speed bonus just like the vanilla skill mechanism. Player can earn experience from doing tasks. As this kind of skill is so-called muscle memory, it would rust much slower.

**Additional context**  

I know it would cause a lot of code work, but it would provide an alternative approach for the skill rust, and encourage players to do the complex tasks, instead of doing the skill earning routine of "find books, read books, and level up" in the early game.

**Comment by ZhilkinSerg** [comment]
#31610
#28283
#12657
