### ISSUE TITLE
"Passenger (Bob) is already there" repeatable error (Bike Rack)

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#34454]
The bike rack can cause a debug error to be displayed when walking on to the saddle location of a bike that is loaded on a bike rack.

1. Load attached save file
2. Walk up (onto bike saddle)
3. Examine up (charging station)
4. Load Bike
5. Walk down (off bike)
6. Walk up (onto bike saddle)

Error message is displayed

 DEBUG    : map::board_vehicle: passenger (Bob) is already there
 
 FUNCTION : void map::board_vehicle(const tripoint&, player*)
 FILE     : src/map.cpp
 LINE     : 943

The save file is a new game with nearly no mods started for the purpose of testing when this error occurs.

[TestBikeRack.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3690185/TestBikeRack.zip)

 - OS: Windows 8.1
 - Game Version: experimental build 9711
 - Graphics version: Tiles (Retro)
 - Mods loaded: no_monsters

# Additional context

I was testing due to a game crash but I was not able to reproduce the crash in the test world.

**Comment by Shotgunface** [comment]
Having the same issue whenever you step on a mounted bikes' saddle.
