### ISSUE TITLE
Vehicle lighting not consistent or correct

### ISSUE THREAD

**Issue by reed501** [CleverRaven/Cataclysm-DDA#34451]
# Describe the bug

Upon loading the game inside my vehicle everything seems fine.
![Screenshot 2019-10-04 at 00 53 17](https://user-images.githubusercontent.com/12606597/66190939-05243600-e642-11e9-9363-cbbcdc0c46f4.png)

Everything makes sense and works the way it always has. I can even walk vertically and even open the door above me and close it and everything works as expected.
![Screenshot 2019-10-04 at 00 53 25](https://user-images.githubusercontent.com/12606597/66190991-1ec57d80-e642-11e9-9d9a-2d3e6ab924cf.png)
![Screenshot 2019-10-04 at 00 53 37](https://user-images.githubusercontent.com/12606597/66191016-27b64f00-e642-11e9-8af5-394ae33d666e.png)

Then I step one tile to the right and everything breaks. My entire interior is lit up with no rays extending outside the vehicle and walking around the vehicle you can never see inside, everything has a roof and the thing is normally light-sealed.
![Screenshot 2019-10-04 at 00 53 43](https://user-images.githubusercontent.com/12606597/66191146-8085e780-e642-11e9-9e5e-871d8675a779.png)
My vehicle is now lit up like this until I leave and load again, in which this process repeats.
![Screenshot 2019-10-04 at 00 53 58](https://user-images.githubusercontent.com/12606597/66191185-985d6b80-e642-11e9-83b0-85f0d5663215.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 9.11 (stretch); Release: 9.11; Codename: stretch; 
- Game Version: 0.D-8190-gfe5c733 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Little-119** [comment]
This seems to apply to buildings, too.

**Comment by PaulBlay** [comment]
In the latest (9711) I am getting "It's too bright to sleep" messages when it should be completely dark.
S = Stowboard
B = Bed
C = Curtain (closed)

SSS
CBS
CCS

Before I had no trouble sleeping through the day.

P.S. I checked there was a roof above all of those tiles.

**Comment by ZhilkinSerg** [comment]
Can you please provide a save?

**Comment by PaulBlay** [comment]
> 
> Can you please provide a save?

Sure. It's 26 MB ... I'll see if git is OK with uploading that much. Nope. Urgh. I'll try Mega (not used it for uploads before).

**Comment by danielkwinsor** [comment]
I can confirm that this existed prior to #34443

**Comment by PaulBlay** [comment]
> Can you please provide a save?

Mega was a wash. Hopefully this Google drive link will work. If you go to sleep after loading the file you should wake up from the bright light. 

https://drive.google.com/file/d/14KDrvjCUgeueLVOq0O1GLa88Wyp0h3gp/view?usp=sharing

I started a new world with no mods in 9711 and made a test bed setup but could not reproduce the bug. So it may be a mod interaction. There was also a lightning storm I think? Maybe that was the problem.

**Comment by reed501** [comment]
I use no mods so it must be base game. If 9708 has it it must be #34391 because that was 9707. I can reproduce it but my save is really really big so it'd be a hassle to post my save.

**Comment by Zepher79** [comment]
Here is a file where the same behavior is happening.
https://drive.google.com/open?id=11FJCz0XxS9oO7WIlQby00AEtl8VgWnvN
The vehicle is being driven, and pressing 5 will advance it one tile forward, triggering the interior to be lit up. The vehicle can also be halted, and stepping towards the front of the vehicle one tile will light up the interior as well. Stepping backwards will then turn the interior back to being dark.
Using Build: 9714, Windows x64

**Comment by reed501** [comment]
[save.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/3694183/save.tar.gz)

Walking a bit to the right triggers lighting that can't be turned off until the game is reloaded.

- Game Version: 0.D-8222-g9213915 [64-bit]

**Comment by ZhilkinSerg** [comment]
I confirm the issue is still here. And we need to ressurrect #31260 for easier debugging.

**Comment by reed501** [comment]
A bit of extra context if it helps:
It only happens in certain locations and it's extremely inconsistent when it happens. I found a specific location, literally a spot, where it works. As in, I drove my car one tile forward and the bug now happens one tile further back, as if it's the world tile that causes my car to light itself up for the remainder of the loaded game.
I also haven't been able to replicate it very often, and sometimes time affects it as far as I can tell. I moved my vehicle somewhere far away and had no issues for awhile, then randomly one day it happens again now. I occasionally move my vehicle to prevent this for now.
It happens in other vehicles sometimes, like a mostly working RV on the road. I'll tape up the curtains and rebuild the roof and now I have another example, but sometimes it doesn't work. I couldn't find an example when making a new test save which is weird.

Very weird issue overall, but it can mess with sleep so has some actual gameplay affect. Kevin also mentioned in discord that he saw this issue going back as far as he can get builds, but I've never encountered this until recently. I'm wondering if there's some relationship with the save as crazy as that sounds. There were some lighting changes and I update a lot so who knows what it could be.

**Comment by reed501** [comment]
[lightingissuebuilding.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/3696202/lightingissuebuilding.tar.gz)
And here's a save where it's happening in a building. So maybe #34467 wasn't successful either?

**Comment by ZhilkinSerg** [comment]
> 
> 
> [lightingissuebuilding.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/3696202/lightingissuebuilding.tar.gz)
> And here's a save where it's happening in a building. So maybe #34467 wasn't successful either?

Yes, it was missing one more place to add +1 when building sunlight cache.
