### ISSUE TITLE
Crash when trying to reload ammo for CBM

### ISSUE THREAD

**Issue by Aloxaf** [CleverRaven/Cataclysm-DDA#34475]
# Describe the bug

Trying to reload ammo for a CBM which can be used as a ranged weapon can cause a crash.

# Steps To Reproduce

1. Make a player with a EMP Projector CBM.
2. Activate it to aim.
3. Press 'o' to reload/switch ammo.

# Expected behavior

Nothing will happen, you can't reload it.

# Versions and configuration

 - OS: Arch Linux
 - Game Version: 0.D-8188-gedf3542c0f
 - Graphics version: Terminal
 - Mods loaded: [ "dda",  "no_npc_food" ]

# Additional context

[log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3693089/log.zip)

**Comment by Fris0uman** [comment]
On latest build I get
![image](https://user-images.githubusercontent.com/41293484/67625185-e0833e80-f83a-11e9-9233-01f0db96dc67.png)

But no crash, there's still a bug with the name displayed though
