### ISSUE TITLE
Autodrive needs work (Tries to drive off side of bridge)

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#34477]
Not always, but maybe one in five or six times, my bike will autodrive into the crash barriers on the side of a long, straight, and empty bridge. The save game file linked consistently produces a crash in the same spot (tested three times).

https://drive.google.com/file/d/11cTUIPaP2P2vFCCmhy7iGTGkwcrTH_pj/view?usp=sharing

1. Start your bike / car's engines on the road one side of a bridge.
2. Choose an autodrive destination some way on the other side.
3. Set off.

Sometimes crash happens. Will also sometimes decide your 'destination' is off the side of a road in a tree. I've seen my bike do a full loop-de-loop in the road once.

I don't expect miracles, it's an extremely handy feature to have even as is, but if someone thinks they can make it work a little more reliably that would be awesome.

![crash](https://user-images.githubusercontent.com/54060142/66253364-157e0300-e75f-11e9-89d8-4c12d23d0432.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 8.1
- Game Version: 0.D-8190-gfe5c733 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi],
    Craftable Gun Pack [craftgp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    EZ-Mode Medical [fast_healing],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

**Comment by davidpwbrown** [comment]
I dont think I have the ability to take the autodrive feature any further in complexity than I already took it.
If anyone wants to try and take it that next step up in safety and complexity though, I will be glad to assist them.
 I can confirm I've seen ( bikes especially ) go around in loops, and Ive seen all vehicles sometimes veer off drastically, I'm not entirely sure why it does this.

If anyone wants to take a run at this and improve this feature, please do so :)

**Comment by PaulBlay** [comment]
Quick note: It's a vehicular crash, not a game crash. Two quite different things. :)
