### ISSUE TITLE
BB guns can foul, despite not using gunpowder

### ISSUE THREAD

**Issue by Relyksboa** [CleverRaven/Cataclysm-DDA#34487]
# Describe the bug

BB guns can foul, despite firing pellets without using gunpowder, smokeless or otherwise

# Steps To Reproduce

1. Find or spawn BB gun
2. fire it a few times
3. notice it ticking the fouling meter unexpectedly

# Expected behavior

For a gun powder-less BB gun to not foul.

# Screenshots

**If applicable**, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/52992503/66257950-473d9c80-e754-11e9-8f8d-1a68f770d0e1.png)
as seen here, fouling BB gun

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: post fouling update
 - Graphics version: [Tiles]
 - Mods loaded: [DDA]

# Additional context

n/a

**Comment by snipercup** [comment]
Probably by #34240
This will be fixed by adding 

>     "effects": [ "NON-FOULING" ]

I think
