### ISSUE TITLE
Give railroad stations monsters and stuff

### ISSUE THREAD

**Issue by zachary-kaelan** [CleverRaven/Cataclysm-DDA#34485]
**Is your feature request related to a problem? Please describe.**  

Aboveground railroad stations are big, yet contain nothing. No monsters, no items, nothing.

**Describe the solution you'd like**  

Add spawns for monsters and items, perhaps using the subway stations for reference.

Put a train on the tracks.

**Describe alternatives you've considered**  

Disabling it until things are fully implemented.

**Comment by EirenexTheDragon** [comment]
I remember that its beeing said that the railroad is going to stay since experimental is supposed to be work in progress.
There is already a mod that  removes the aboveground railroad stations which people can use already

**Comment by chriseich21** [comment]
It's still stuff that would help the train station be a viable worldgen spawn in the meantime. Zombies and items don't hamper it until they get around to creating and linking track connections between stations, or whatever their goal is.

**Comment by snipercup** [comment]
Im going to work on this

**Comment by snipercup** [comment]
My PR is merged so there are now basic items. I'd like to see some items scattered around, maybe some items in the underground. Also monsters need to be added. I'll comment when i'll start working on this issue again, in the mean time anyone is free to work on this (please comment if you do).

**Comment by snipercup** [comment]
Im going to work on this
