### ISSUE TITLE
⍰ symbol in weapon names and on UI.

### ISSUE THREAD

**Issue by Myobu1** [CleverRaven/Cataclysm-DDA#34492]
For some reason, I've noticed a ⍰ symbol appear in-game. I first noticed it when I found a S&W 610 on the ground. It read as "⍰S&W 610" - However, guns spawned in using debug mode appear normal. The ⍰ symbol isn't appearing in the name of _every_ gun, but I managed to find a few after I teleported to several gunstores. The ⍰ symbol also appears next to "Calm" on the UI. I reinstalled the game and ensured my graphics drivers were updated, but the problem persists.

If I'm the only one with this issue, I'll assume that it's on my end and reinstall my OS.

![Screenshot (139)](https://user-images.githubusercontent.com/44004977/66260228-d7e29f80-e789-11e9-8714-83d734363a28.png)
![Screenshot (140)](https://user-images.githubusercontent.com/44004977/66260229-d7e29f80-e789-11e9-873b-206a54ab7ff0.png)
![Screenshot (141)](https://user-images.githubusercontent.com/44004977/66260230-d7e29f80-e789-11e9-98a4-927a64623b2f.png)

OS: Windows 10 Professional
Game Version: 0.D-8222-g9213915
Graphics Version: Tiles
Mods loaded: No Flaming Weapons, No Survivor Armor, Disable NPC Needs

**Comment by anothersimulacrum** [comment]
Culprit: #34240 
Specifically: https://github.com/CleverRaven/Cataclysm-DDA/pull/34240/files#diff-f7ca61cf749eba039da961e8a7be1630R3381-R3405

**Comment by snipercup** [comment]
It looks like this on my machine:
![image](https://user-images.githubusercontent.com/50166150/66261024-d1bee400-e7c6-11e9-872e-43747dac0333.png)

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-8206-gedf3542 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
I got windows 8.1


In the comments of the pr that anothersimulacrum is pointing to it says:

>     // these symbols are unicode square characeters of different heights, representing a rough
>     // estimation of fouling in a gun. This appears instead of "faulty"
>     // since most guns will have some level of fouling in them, and usually it is not a big deal.

Maybe there is a problem with some fonts? Is there an alternative to represent dirt level?

**Comment by anothersimulacrum** [comment]
> Is there an alternative to represent dirt level?

Put it in the description?

**Comment by Myobu1** [comment]
Well, I am using the font settings Vormithrax recommends - the "Whitrabt" and "Consolas Bold" fonts. However, if the only option to fix this issue is to revert to vanilla fonts... I guess I'll have to live with it.

Edit: Aparently setting my font back to Unifont fixes the issue. I shouldn't have to change my _font_ to have a feature display properly.

**Comment by anothersimulacrum** [comment]
Oh yeah, Whiterabbit doesn't have unicode support. So any font without unicode support won't work with this feature.

**Comment by ZhilkinSerg** [comment]
> But I shouldn't have to change my _font_ to have a feature display properly.

Your font has poor Unicode support (well, to be honest most fonts are not as good as unifont, so...).

**Comment by Myobu1** [comment]
I'm not using Whiterabbit for my typeface, just the map. I'm using Consolas Bold for everything else, and that isn't an uncommon font by any means. In addition, those fonts are far easier on the eyes for me to read than Unifont.

Again, why should being able to see if a weapon has been fouled be dependent on the font? Why not put it in the description or something? Somewhere that isn't dependent on the user's font? My eyes are absolute garbage, and Unifont looks like crap on my screen. It may look fine to you, but it doesn't look good nor clear to me.

**Comment by Qrox** [comment]
Is there a way to detect if a symbol is not supported by the current font and fallback to ascii symbols when in such case?

**Comment by ANickelN** [comment]
Going to add a +1 for putting it in the description.  Even with Unifont it still looks like an error/out of place.

**Comment by Qrox** [comment]
@Myobu Now that #36326 is merged, you can specify fallback fonts on the tiles build by changing the "typeface" value in `config/fonts.json` to an array. For example, since you're previously using Consolas Bold as the main font, now you can change `"typeface": "consolab"` to `"typeface": [ "consolab", "unifont" ]`, so that missing symbols from Consolas will be displayed using unifont instead. Let me know if this addresses your problem.

**Comment by ZhilkinSerg** [comment]
Unifont should be a default fallback probably.
