### ISSUE TITLE
UPS based weapons cause NPC to crash

### ISSUE THREAD

**Issue by x7GoSu** [CleverRaven/Cataclysm-DDA#34491]
# Describe the bug

Giving a NPC a UPS based weapon causes crash when trying to speak to them after they have it wielded. 

# Steps To Reproduce

1. Make a player with a A7 RIfle, with a loaded UPS in inventory.
2. Have a NPC follower.
3. Give UPS(loaded) to NPC.
4. Have NPC use A7 rifle. NPC will wield.
5. Try to talk to NPC.

# Expected behavior

Being able to equip a NPC with an A7 rifle. Having NPC be able to use A7 rifle. Being able to talk to npc after its equipped as normal.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8200-g1ba9252 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

 - 
[Crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3693640/Crash.zip)
# Additional context

**Comment by zeggz** [comment]
Same crash (i think) with the "crank survivor laser rifle" (not sure of the name). I comment here instead of opening a new issue since it look like it's the same bug.

**Comment by davidpwbrown** [comment]
confirmed.
