### ISSUE TITLE
gun mods with aimspeed > default

### ISSUE THREAD

**Issue by Sluggyguy1** [CleverRaven/Cataclysm-DDA#34493]
# Describe the bug

Not sure if this is actually a bug or not but thought i would post for verification.  I cant seem to see any difference between any aim speed faster than default when testing gun mods that should be faster.  

# Steps To Reproduce

1. spawn any gun and gun mod like underbarrel or rail laser
2. test aim speed/accuracy with and without mod

# Expected behavior

gun mod with higher speed should aim faster/more accurately in shorter time

# Additional context

https://www.reddit.com/r/cataclysmdda/comments/ddmquf/gun_mods_working/

**Comment by SirPendrak** [comment]
If your gun was heavily moddificated and huge, then above certain volume (i think about 3,75l) youre stuck with lowest possible aimspeed regardless of sights you use.

**Comment by Sluggyguy1** [comment]
my test was with an AR-15 and one mod at a time, as listed in the link, but i can test smaller rifles.  Also if mods can never effect a gun larger than 3.75l then there should probably be a rebalance or rethink there, as that doesn't make much logical sense, either in gameplay or in real world application

**Comment by Tadders1488** [comment]
The mods seems to help with aim time/accuracy with regards to recoil/steadiness.

**Comment by Sluggyguy1** [comment]
@Tadders1488 did you do new tests or look at my data?
