### ISSUE TITLE
No way to recruit the bone seer

### ISSUE THREAD

**Issue by fluffe9911** [CleverRaven/Cataclysm-DDA#34495]
# Describe the bug
Based off my understanding looking at the code after you do his gather 8 bones mission and finish his quest he is supposed to carve your hand and give you the mark that lets you recruit him, but it seems that you never actually get the mark and as such there is no way to actually recruit him.

# Steps To Reproduce

1. Talk to seer
2. Gather 8 bones
3. Go back to seer and talk to him again
4. Finish his quest where he says he will carve your hand
5. Try to recruit him and then he goes what carved hand I never carved your hand? begone nonbeliever! (not really but you get the idea)
6. Feel scammed

# Expected behavior
Finish the quest, get my hand carved and make him follow me

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-8222-g9213915 [64-bit]
- Graphics Version: Tiles
- Mods loaded:
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Draco's Pig Mod [DracoPigMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    Roadheader and other mining vehicles [Heavy miners],
    Necromancy [necromancy],
    Mining Mod [Mining_Mod],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Skills [StatsThroughSkills],
    Sleep Deprivation [sleepdeprivation]

**Comment by fluffe9911** [comment]
He was added in this pr by the way https://github.com/CleverRaven/Cataclysm-DDA/pull/33828

**Comment by UNOwenWasMe** [comment]
Noticed this too, and felt bummed out too!

You can circumvent this by going into the debug menu and give you the "Mark of the Seer", which is coded as a mutation, and then you can recruit her.

**Comment by kevingranade** [comment]
I believe this was adressed here https://github.com/CleverRaven/Cataclysm-DDA/commit/267c803d6c8291dd0abb10c53bb300f25f4b6d04
