### ISSUE TITLE
Siphoning tank selection keybindings and amount broken

### ISSUE THREAD

**Issue by zachary-kaelan** [CleverRaven/Cataclysm-DDA#34509]
# Describe the bug

When selecting a vehicle tank to siphon *to*, some of the keybindings given don't work. 

* `b`, which is bound to "Move Southwest" in the keybindings menu
 * It works if you move the cursor down once, and then works for all subsequent siphonings
* `c` which is bound to "Close Door"
* `g` which is bound to "Pick up Nearby Item(s)"
* `j` which is bound to "Move South"
 * It just scrolls down the list. 

Also, it's siphoning only 0.7L at a time, which doesn't seem right. Emptying a 60L tank would take mashing the `Enter` key 86 times.

# Steps To Reproduce

1. Siphon from one vehicle, to a second one that has multiple tanks.
2. Attempt every keybinding.

# Expected behavior

I expect all the listed selector keys to work properly, and I expect to be able to siphon a full tank without button mashing.

# Screenshots

![image](https://user-images.githubusercontent.com/30245333/66269143-f8a30780-e812-11e9-8d54-fe6aba224564.png)

![image](https://user-images.githubusercontent.com/30245333/66269273-a7941300-e814-11e9-804f-401097ff88ea.png)

# Versions and configuration

- OS: Windows 10 Home
    - OS Version: 10.0 1903 Build 18362
- Game Version: 0.D-8234-gfd91108 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    sees-player icon, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Sleep Deprivation [sleepdeprivation],
    Stats Through Skills [StatsThroughSkills],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    No Filthy Clothing [no_filthy_clothing],
    Simplified Nutrition [novitamins],
    Jury-Rigged Robots [jury_rigged_robots],
    Mythical Martial Arts [MMA],
    Hydroponics [hydroponics],
    Aftershock [aftershock],
    Classes and Scenarios Mod [more_classes_scenarios]
]

**Comment by TheMurderUnicorn** [comment]
Ran into this issue today.  Mine's siphoning in .5 liter increments.  A big peculiar that it's a different quantity from you, but it's definitely an issue.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6416.

![изображение](https://user-images.githubusercontent.com/11132525/156148766-e651d184-b323-4b45-8b60-9b6fe0031cf2.png)

I got a vehicle with several tanks. One of them was being keybinded to `c`. I pressed `c`, and game successfully siphoned fuel to that tank.

![изображение](https://user-images.githubusercontent.com/11132525/156149007-b2b12bd8-1a41-4695-b01a-19008ad48bad.png)

I also tested with `g` tank, and it worked as intended.
