### ISSUE TITLE
Turret shoot through the wall 

### ISSUE THREAD

**Issue by KIVix** [CleverRaven/Cataclysm-DDA#34506]
Laser turret on the chassis, trying to shoot through an opaque wall at the enemy.

# Steps To Reproduce

The turret is as in the screenshot, no matter how it stands, tries to shoot through the wall.

![2019-10-44](https://user-images.githubusercontent.com/11228323/66267487-a2ea5180-e84a-11e9-8d88-6b6a036ba299.gif)

# Expected behavior

Ideally also describe *why* you expect it to happen.

# Screenshots

![cataclysm-tiles_U9xrqOOscC](https://user-images.githubusercontent.com/11228323/66267381-99141e80-e849-11e9-9f7d-6bd6091ed9e6.png)

![cataclysm-tiles_5Ieal1ugZl](https://user-images.githubusercontent.com/11228323/66267382-9f09ff80-e849-11e9-81f6-d692b1526a6c.png)

![cataclysm-tiles_sxJ2vVkiNH](https://user-images.githubusercontent.com/11228323/66267384-a16c5980-e849-11e9-8c0b-c73754f9da71.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.D-8234-gfd91108 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Icecoon's Arsenal [ew_pack],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs],
    Hydroponics [hydroponics],
    EZ-Mode Medical [fast_healing],
    No Rail Stations [No_Rail_Stations],
    Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    Tanks and Other Vehicles [Tanks],
    Prevent Zombie Revivication [no_reviving_zombies],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[turetbug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3694207/turetbug.zip)

**Comment by Night-Pryanik** [comment]
Unless I'm mistaken, the turret is firing laser beam through the glass wall?

**Comment by KIVix** [comment]
Yes, laser can shoot through the glass wall, but after a normal wall, and steel dorr. In the room with auto doc, is clear.

**Comment by Night-Pryanik** [comment]
Seems to be fixed by #38730.
