### ISSUE TITLE
Player vision goes through floor/ceiling tiles

### ISSUE THREAD

**Issue by Lum4r** [CleverRaven/Cataclysm-DDA#34510]
Game version: 
0.D-8234-gfd91108 [64-bit]
Operating system: 
Windows
Tiles or curses: 
Tiles
Mods active: 
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food]

### Expected behavior
Floor/ceiling tiles should block player's view between Z-levels
### Actual behavior
The player can see tiles and items (but not monsters) on the Z-levels directly above and below them as if they were actually standing there.
### Steps to reproduce the behavior
Start a new game from an underground location, enter 'Look Around' mode, look up

**Comment by kevingranade** [comment]
I'm going to go out on a limb and say this was fixed by #36196 
Feel free to reooen if you can reproduce it.
