### ISSUE TITLE
SegFault

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#34516]
# Describe the bug

IIRC, I was reloading an ember holder (lit)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8232-g28221de [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    sees-player icon, -attitude [sees_player_less_attitude]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3694660/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3694661/debug.log)
[core.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3694662/core.log)
core.log is actually .core

**Comment by ZhilkinSerg** [comment]
Do you know specific reproduce steps? If not, there is nothing we can do with provided info.

**Comment by danielkwinsor** [comment]
I reproduced it 2 more times, here is a save.  Head up north to near the oven.  Stand SE of the firewood location, reload the embers.
[Daysville - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3694823/Daysville.-.Copy.zip)

**Comment by ZhilkinSerg** [comment]
Cannot reproduce it on latest master. Possibly was fixed in #34507.

Can you please test too with build 9723 and tell whether it is still crashing?

**Comment by danielkwinsor** [comment]
Yes, definitely fixed.
