### ISSUE TITLE
Recent restrictions to field dressing butchery should be reverted

### ISSUE THREAD

**Issue by BugBurgA** [CleverRaven/Cataclysm-DDA#34511]
**Is your feature request related to a problem? Please describe.**  
This https://github.com/CleverRaven/Cataclysm-DDA/pull/34221 recent change limited the field dressing type butchering to entities that actually dropped something upon successful butchery. This should be reverted because field dressing has uses besides harvest-able items. The description of field dressing states that it reduces weight of the corpse and slows down rot (I'm unsure if has a programmed effect however). Third and finally, it prevents zombies from raising without further damaging the corpse (helpful for bionic harvesting). These are all effects which have uses even if they don't yield items. Most entities would still have internal organs, even if they are not represented as an item drop in game.

**Describe the solution you'd like**  
Revert https://github.com/CleverRaven/Cataclysm-DDA/pull/34221.

**Describe alternatives you've considered**  
Keep the restriction in game.

**Additional context**  
Field dressing description.
![image](https://user-images.githubusercontent.com/51819091/66270440-2467d100-e897-11e9-9942-c91e40e19294.png)

**Comment by zachary-kaelan** [comment]
Yeah, after taking out cockroach nests, you have a LOT of corpses to deal with, and it's hard to prevent rot now.

**Comment by Qrox** [comment]
Or we can add butchery refuse as the product of field dressing zombies or animals without other field dressing products, to simulate the process actually removing something from them?

**Comment by KorGgenT** [comment]
that's what it did before. if this change is warranted, it'll just be flipping a boolean in that PR, not reverting it.

**Comment by BugBurgA** [comment]
> that's what it did before. if this change is warranted, it'll just be flipping a boolean in that PR, not reverting it.

What reasons would there be to keep the restriction?

**Comment by BugBurgA** [comment]
I just saw in [your reddit comment](https://old.reddit.com/r/cataclysmdda/comments/dax035/cdda_changelog_september_29_2019/f1vwlsp/?context=3) @KorGgenT that you wanted to prevent confusion. Perhaps a solution would be to warn that field dressing would yield nothing, rather than outright block it?

**Comment by kevingranade** [comment]
You list three things provided by field dressing.
1. Reduces weight of corpse.
This only makes sense in the context of removing worthless things and leaving useful things. If nothing is useful, what do you remove, what do you leave? Regardless of the answer for a particular creature, the general as l answer is, "you keep things that have harvest entries".
2. Preserve corpse.
Again, this only makes sense in the context of removing "trash" flesh from a warm-blooded animal so the remainder doesn't spoil as fast. If nothing is in the hsrvest entry, there's nothing to keep. Also it won't do anything for cold-blooded creatures.
3. Prevents zombie rectification without damaging bionics.
This is an oversight to be fixed, not a feature.

**Comment by BugBurgA** [comment]
For both 1 and 2, there are creatures that have no field dressing drops but do have regular yields. Best example are cockroaches from the previous comment. You cannot field dress them, but they yield precious meat and fat from regular butchery. Slowing down rot gives a survivor time to clear out a harvest. 

As for 3, perhaps prevent bionics being recovered from carcasses?

**Comment by kevingranade** [comment]
If roaches have butchery yields then that can be re-added, but that's an oversight, not a reason to revert the change.

Roaches are cold-blooded, so aren't subject to the rot prevention feature anyway.

**Comment by BugBurgA** [comment]
Some quick testing, it appears most insectiod creatures have no field dressing drops, but do drop edible meat and fat. 

> If roaches have butchery yields then that can be re-added, but that's an oversight, not a reason to revert the change.

That is reasonable.
> Roaches are cold-blooded, so aren't subject to the rot prevention feature anyway.

Even so, reducing the weight of carcasses allows to bring in a bigger haul.
