### ISSUE TITLE
Vehicle disappearing when grabbing another veh inside(?)

### ISSUE THREAD

**Issue by starytroll** [CleverRaven/Cataclysm-DDA#34514]
# Describe the bug

When I try to grab lifter (one-tile vehicle with pallet lifter) which is in the middle of another vehicle being deconstructed, the latter disappears entirely!

# Steps To Reproduce

1. Load provided savegame.
2. Go out (south) of the evac, go to the right vehicle and grab away the lifter.
3. Notice how the under-construction vehicle disappears.

# Expected behavior

Veh not disappearing obviously.

# Screenshots

![obraz](https://user-images.githubusercontent.com/54743246/66271844-f8325d00-e862-11e9-848e-691189b68c09.png)

![obraz](https://user-images.githubusercontent.com/54743246/66271854-01bbc500-e863-11e9-9110-4e198198988f.png)

# Versions and configuration

- OS: Windows 8.1
- Game Version: 0.D-7950-ga718f4c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key]
]

# Additional context

Save game:
[Earlings.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3694610/Earlings.zip)

**Comment by davidpwbrown** [comment]
Were you using NPCs and zones to work on that vehicle?
Is the "disappeared" vehicle actually been compressed to a one-tile vehicle somewhere? that you can examine?
If you drag the lifter around where the other vehicle used to be, does it hit any invisible barriers?

**Comment by starytroll** [comment]
> Were you using NPCs and zones to work on that vehicle?
Nope.
> Is the "disappeared" vehicle actually been compressed to a one-tile vehicle somewhere? that you can examine?
You are right, it is in the form of one tile veh a few tiles away, didnt notice with all those heavy duty frames lying around.
> If you drag the lifter around where the other vehicle used to be, does it hit any invisible barriers?
Actually, when I try to grab it, I can move it one tile and then grabbing stops saying it cannot find vehichle. After regrabbing, it repeats.

**Comment by davidpwbrown** [comment]
yeah, seen this before. I thought it might be related to NPC/ zone vehicle work, but apparently not.
It appears to be some kind of map caching thing, I tried and failed to find the cause before. but at least I know its reproducible.
There was something you could do on the compressed vehicle to make it suddenly un-compress and BAM its all there again, it was deeply weird, when you examine it, it should show all of its parts still intact, but on the map theres just one tile of it.

**Comment by SageB** [comment]
If you want to expand it, iirc you just need to remove a single part from it.

**Comment by starytroll** [comment]
That's true - when I examined it, it showed all the parts. Next time if it happens it is good to know I can expand it back. The only thing I did with NPC was trading and getting a mission from him (standard pal from evac).
