### ISSUE TITLE
Very Bad Day Start Alcohol Bug

### ISSUE THREAD

**Issue by MamuelMamington** [CleverRaven/Cataclysm-DDA#34523]
# Describe the bug

If you start with the very bad day start, the intoxicated state is bugged in a variety of ways. Firstly, for a few in game minutes, being completely shitfaced has no impact on your depressant value. Afterwards, the status depressants 101 permanently haunts you. Last time I suffered through this I slept for at least 12 hours and it didn't budge. 

# Steps To Reproduce

1. Start the game with the very bad day start.
2. Suffer.

# Expected behavior

The depressants value is consistent and goes away after a day of sobering up.

# Versions and configuration
 - OS:  Windows 10 
 - Game Version: 8243-ge0d55ca
 - Graphics version:Tiles 
 - Mods loaded: Graphical Mods

**Comment by snipercup** [comment]
It takes about 3-4 days for it to come down:
![image](https://user-images.githubusercontent.com/50166150/66326182-dac7c680-e928-11e9-8fc8-f775155f1b0d.png)

**Comment by MamuelMamington** [comment]
That clarifies the behavior but still shows a problem. Again the depressants 101 doesnt show up until after a few hours, and then you start falling all over the place. While gameplay wise it's nice that you get a head start, it really doesn't make any sense at all.
