### ISSUE TITLE
Able to light ember holder while empty of tinder

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#34520]
# Describe the bug

Able to light ember holder while empty of tinder

# Steps To Reproduce

1. Get ember holder empty, and a lighter
2. (a)ctivate the ember holder

# Expected behavior

Nothing to happen in game, error message

# Additional context

For ease of use, you may use the savegame at #34516 and sleep to let the holder expire.

**Comment by snipercup** [comment]
I can reproduce this issue:
![image](https://user-images.githubusercontent.com/50166150/66284392-ca333400-e8c7-11e9-9432-f32073ce96f2.png)

The hobo stove needs 25 charges first:
![image](https://user-images.githubusercontent.com/50166150/66284413-e040f480-e8c7-11e9-9a03-6554f614fb2c.png)

After waiting a while, the ember carrier does go out and you can light it again without charges

A lit hobo stove with charges:
![image](https://user-images.githubusercontent.com/50166150/66284444-05cdfe00-e8c8-11e9-87dc-531914f6a9b2.png)


A lit hobo stove without charges:
![image](https://user-images.githubusercontent.com/50166150/66284449-0feffc80-e8c8-11e9-84e1-948c7a4e67c8.png)


I saw the problem with the hobo stove so i added it to this issue.
