### ISSUE TITLE
Picking up multiple items while in a moving vehicle item loss / duplication

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#34528]
If you drive your motorbike over a pile of stuff and try to pick it up without stopping your vehicle you end up picking up, and not picking up, some of the objects resulting in item duplication. You can also lose objects this way as they 'fall into the cracks' between reality and irreality. (Does not actually cause a shimmering portal to appear, but maybe it should ;)

1. Put a pile of lots of stuff in the middle of the road.
2. Bike past it.
3. While over/adjacent to the pile of stuff pick it up.
4. Time passes while you are picking up stuff so by the time you finish you are no longer over the objects.
5. Game gets confused and throws out a debug error.

=> Result: Some of the stuff you picked up is still on the ground as well. But you can also lose something you tried to pick up.
=> Expected result: Not having stuff left behind as well as in your inventory.

Alternative: Just don't let people grab stuff from the ground while in moving vehicles.

![items](https://user-images.githubusercontent.com/54060142/66283702-66573e00-e8bc-11e9-9c71-3c27b42898d3.png)

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 8.1
- Game Version: 0.D-8234-gfd91108 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Monsters [Only_Wildlife]
]
# Additional context

Test save that shows the behavoir. Just load and try to pick up everything.

[Duplication.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3695470/Duplication.zip)

**Comment by mrkybe** [comment]
Yep.  Can replicate.  Also similarly:

If you put some items in a container, ie: back of a pickup truck, and drive past it and do a 'pickup' all action, it will continue doing it.  No duplication at least though.
