### ISSUE TITLE
Firestation base cannot craft items

### ISSUE THREAD

**Issue by Lucewithnootherideas** [CleverRaven/Cataclysm-DDA#34535]
the fire station camp cant craft any items like food or blacksmithing using survivors, they have both skills and materials but when press enter it exits the screen with no bug report, however building still works and i managed to almost fully build the fire station

# Steps To Reproduce
fire station camp try to make a survivor craft

# Expected behavior

they should be going away to craft the items

version 9724

# Additional context
i started this camp around 9690 so that might have something to do with it

**Comment by curstwist** [comment]
can you give more information?  When you say craft, do you mean the base upgrades or do you mean actual NPC crafting like for the food and blacksmith recipes?

**Comment by Lucewithnootherideas** [comment]
Yes sorry i updated the post with better context

**Comment by curstwist** [comment]
confirmed it's an issue on build 9735.

**Comment by Vollinger** [comment]
Items with `"building_type": "BASE"` can be crafted, so a hacky temporary fix is to set all groups in recipe_groups.json to BASE.
