### ISSUE TITLE
Inherited Maple Sap value makes Maple Syrup as calorie dense as 2 stalks of celery. 

### ISSUE THREAD

**Issue by DeviateScaleCodpiece** [CleverRaven/Cataclysm-DDA#34556]
# Describe the bug

Celery has 15kcal per .25L and player crafted maple syrup has 30kcal per .25L of maple syrup.  Maple sap has 1kcal per .25L, so 40 maple sap boils down to 2kcal/portion of maple syrup (apparently leftover kcal gets rounded down).  

# Steps To Reproduce

Tree spile some maple trees and wait a few days. Harvest sap. Boil sap.

# Expected behavior

For maple syrup to have more calories than celery. I expect this to happen because reality.

# Screenshots

https://cdn.discordapp.com/attachments/194465934273019906/631040614628196352/unknown.png

Maple Syrup after boiling.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-8299-ge6baeca
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead

# Additional context

Coffee Syrup also has 0 calories by default for some reason and this should be fixed too. Coffee syrup is not air.

**Comment by Kodiologist** [comment]
The JSON for maple syrup looks good, at least in terms of the energy per unit mass. One portion weighs 21 g and yields 54 kcal, which agrees with [FNDDS's finding](https://fdc.nal.usda.gov/fdc-app.html#/food-details/343954/nutrients) of 260 kcal per 100 g (260 * 21 / 100 = 54.6).

**Comment by y2s82** [comment]
(FNDDS's on Celery)[https://fdc.nal.usda.gov/fdc-app.html#/food-details/342606/nutrients] states that 100 grams of celery has about 95.4 grams of water.  That's 95 ml of volume in water alone at ground level pressure, which means the core problem of comparison here is the misrepresentation of the volume for the celery stick.

I do not know how this works in terms of game balance, of course.
