### ISSUE TITLE
Deduplicate town names

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#34555]
I would like town names on the map to be unique.  My current game has a Mount Vernon and Mont Vernon.  In a past game, I had the same town name 2 towns over, and have seen other duplicates.

**Comment by jeremyshannon** [comment]
It probably wouldn't be too hard to  make a randomized copy of the list of town names in the save directory with a counter at the top of it pointing to the next unused name, and then move the counter up one every time a town is needed. Then you'd only get repeats after every town name had shown up, which would take quite a while.
 I don't know if it would be weirder at that point to just let the town names be reused in the same order, or to reshuffle them and risk having some towns with the same names be right across from each other.

**Comment by Qrox** [comment]
Just save the existing town names in a set and skip these names when choosing a new town name.

**Comment by jeremyshannon** [comment]
Nah, that would use more processing power to achieve the same result.

**Comment by Qrox** [comment]
I don't think the performance difference would be noticeable. Furthermore, if new names are added to the game, my solution also allows these new names to be chosen.

**Comment by jeremyshannon** [comment]
It means every time a new town is generated, you have to run a diff between the name list and the used list (hope they're both sorted or else you have to do that first) to generate a new list, and randomly select a name from it. That's a lot of cycles wasted versus just grabbing one entry from a pre-randomized list and removing it.
 There's not gonna be a huge, noticeable difference between generating a list of names to pick from once versus doing it every time a town is generated, but given two approaches, the more wasteful method needs a good justification IMO.

  My way, any new town names would start to appear after you'd gone through the whole run. I suppose if the new names were appended to the end of the source list, you could keep the original byte/line count of the source in the random list's header and detect if the source list got new towns by checking its size, and then fold the new names into the random list.

  I'm not sure it's worth bothering, though. When was the last time new names were added to the town list, anyway? I'm pretty sure that list was imported from real world data all at once and has been static for years. (I'd be happy to be proved wrong though)

**Comment by kevingranade** [comment]
Anything that copies the entire town name list from the start and inflates the savegame by that amount is a problem.

Heres my proposal:
Add used names to world save.
When choosing a random name, keep picking randomly until you pick one that doesn't collide.
To handle the degenerate case when most names have been picked, switch the blacklist to a whitelist. Worst case we store half of the town names in the savegame.
Once the whitelist empties, disable this check, we just start tolerating duplicates because we have no choice.
