### ISSUE TITLE
Pet carrier / chicken cage disappearing after releasing animal

### ISSUE THREAD

**Issue by Enzo-Gaultier** [CleverRaven/Cataclysm-DDA#34554]
when I use a pet carrier / chicken cage to catch a chicken the pet carrier / chicken cage disappears when I release the animal

# Steps To Reproduce

1. catch a chicken with a pet carrier / chicken cage.

2. Free the chicken from the pet carrier / chicken cage.

3. The chicken is released and the pet carrier / chicken cage 
   does not return to the inventory as empty at all, It just disappears.

# Expected behavior

The pet carrier / chicken cage is supposed to return to inventory as empty.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-8299-ge6baeca
 - Graphics version: Tiles
 - Mods loaded: None
 - Build: 9728

# Additional context

Save Folder:
[Tests.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3700749/Tests.zip)

**Comment by curstwist** [comment]
I can confirm this in a vanilla +magiclysm world. Mine disappeared attempting to catch a cat, cat remained at large.
