### ISSUE TITLE
Segmentation Fault when moving into a map square with cows and calves.

### ISSUE THREAD

**Issue by fallout2077** [CleverRaven/Cataclysm-DDA#34561]
When entering a map square containing a couple cows and calves I receive a segmentation fault crash.  I actually walked and drove through that area earlier in the play session with no problems. Just now when driving through the area, taking screenshots along the way and while driving 4 mph (I usually drive through the area going ~20mph or so), the game didn't crash. So, perhaps a map-loading bug, or maybe an issue with map memory? I'll post the latest screenshot so you folks can catch a glimpse of what's on the map at the time the crash usually occurs.
![cdda1](https://user-images.githubusercontent.com/20364249/66392020-b60d3680-e99c-11e9-83a6-89968067cf0e.jpg)

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8316-g4feecd9 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Gun Cotton [guncotton],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Sleep Deprivation [sleepdeprivation],
    Stats Through Skills [StatsThroughSkills],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Cataclysm++ [Cata++],
    Urban Development [Urban_Development],
    Bionic Slots [cbm_slots],
    Classic Roguelike Classes [RL_Classes],
    SpeedyDex [speedydex]
]

Expected behavior - Pass through the area with no errors/crashes.

Actual behavior - Entering the map square causes a fatal seg fault crash.

Steps to reproduce the behavior - I'm not sure, as I'm not exactly certain as to what in particular is causing the crash. All I have gathered is that it has something to do with vehicle speed.

**Comment by ZhilkinSerg** [comment]
Please provide a savegame.

**Comment by fallout2077** [comment]
Okay, I was able to upload it to Google Drive. Here's the link. The crash occurs anywhere between coords "0'84, 0'140" and "0'84, 0,147" on Level 0. At the moment this save was uploaded, I am currently exploring a lab.

**Comment by ZhilkinSerg** [comment]
Cannot reproduce on current master yet, but I've tried without some of the third party mods, so maybe that's the culprit.

**Comment by fallout2077** [comment]
> ...but I've tried without some of the third party mods, so maybe that's the culprit.

Just so I know where to start looking, which of the mods did you not have loaded?

**Comment by fallout2077** [comment]
Oops, gosh darn "close and comment" button.

**Comment by fallout2077** [comment]
I'm testing again on the latest experimental (it crashed on the version I originally posted this bug report) and the issue isn't crash isn't occurring. Instead I'm seeing a "tried to get invalid activity type" error that I can ignore with no apparent issues.

**Comment by davidpwbrown** [comment]
That activity type error is known anda  fix is on the way, unrelated to this. can this be closed now?

**Comment by fallout2077** [comment]
> can this be closed now that it seems to be fixed on latest master?

The crash that I originally created this bug report for has been fixed? I read through the list of commits and I could not find any additions to master that relate to the crash I was experiencing.

**Comment by davidpwbrown** [comment]
You said the crash isnt occuring anymore on latest master? with the same savegame?
