### ISSUE TITLE
Smartphones won't show the time when music is played from them

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#34563]
When using a Smartphone for Musiclistening, you loose the possibility to check the time.

1. Take any UPS Smartphone
2. Check the time when it is not playing musik
3. Switch on the Music function
4. Try to check the time again.

# Expected behavior

You should check the time even when it plays music.

# Screenshots
![Smartoff](https://user-images.githubusercontent.com/33199510/66395986-06a28500-e9d9-11e9-9fe8-5e5804cde18e.jpg)
![Smarton](https://user-images.githubusercontent.com/33199510/66395985-06a28500-e9d9-11e9-9f05-f2ea91696257.jpg)

# Versions and configuration
dda
Version 9730

**Comment by curstwist** [comment]
also when using the light.

**Comment by AMurkin** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/4feecd9b3c55ebfe426dbf6de620ff218cebc8cf/data/json/items/tools.json#L1014-L1074

Smartphone flags:
`"flags": [ "WATCH", "ALARMCLOCK", "USE_UPS", "NO_UNLOAD", "NO_RELOAD" ]`
smartphone_music flags:
`"flags": [ "TRADER_AVOID" ],`
smart_phone_flashlight flags:
`"flags": [ "LIGHT_20", "CHARGEDIM", "TRADER_AVOID" ]`

**Comment by Lamandus** [comment]
so if the flag "WATCH" is added to those two other lines, it is fixed, right? Can someone do it pleaaase?
