### ISSUE TITLE
error with challenge-lab

### ISSUE THREAD

**Issue by Tenasa-vini** [CleverRaven/Cataclysm-DDA#34583]
I have gotten an error after choosing challenge-lab. the game sets my starting location as null and when i start game, i spawn at the evac shelter.

![1](https://user-images.githubusercontent.com/56329947/66448035-cf05fe00-ea15-11e9-9679-5348dad34415.PNG)

![Capture](https://user-images.githubusercontent.com/56329947/66447775-ed1f2e80-ea14-11e9-85bc-5aacb3a3ac8e.png)

i have these mods set in this world. disable npc needs, crit, makeshift items, more survival tools, moldular turrets, alter map key, cdda++,mutant npc, manual bionic installations, safe autodoc, mutation changes, spedydex. 

once the world is created, all you have to do is pick challenge-lab go to the finish character screen and it will give an error message about the labs and lab stairs. once spawned into the world, you will be put at the evac shelter

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8335-gcb7b4b0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Mutant NPCs [mutant_npcs],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Mutation Changes [Mutation_Changes],
    SpeedyDex [speedydex]

![Capture](https://user-images.githubusercontent.com/56329947/66447860-37081480-ea15-11e9-8057-41246b58d7aa.PNG)

**Comment by ZhilkinSerg** [comment]
Please try reproducing this issue without any third party mods.

"Challenge-Lab" scenario is not from vanilla.

**Comment by Tenasa-vini** [comment]
the lab challenge works fine without any mods. it may mutation changes mod thats is causing the issue. is the mod not updated for this version?

**Comment by anothersimulacrum** [comment]
If you can't reproduce it without Mutation Changes, Cata++, or the makeshift items mod, then this issue should be closed. We can't do anything about third party mods.
