### ISSUE TITLE
Magiclysm: translocate spell teleports into air causing fall damage.

### ISSUE THREAD

**Issue by Ansopedi** [CleverRaven/Cataclysm-DDA#34600]
# Describe the bug

Using the translocate spell apparently teleports me (at least) 1 tile above the gate, resulting in fall damage.

# Steps To Reproduce

1. Use the translocate spell in the given savefile (only one target available).
[Lecompte.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3709310/Lecompte.zip)

# Expected behavior

Arriving to the side of the translocator gate.

# Additional context

Using a modified version of the magiclysm mod (with everything but the translocator gates (and spell, etc) removed. It could technically be the cause of the issue but it is unlikely.
[Magiclysm.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3709311/Magiclysm.zip)

**Comment by KorGgenT** [comment]
note: this is happening because of the difference in Z level for the teleports. g->place_player() calls all of the functions that would have you take fall damage, and even when changed to player::setpo() you hit the ledge trap (for some reason) and take 1 z level's worth of fall damage.
