### ISSUE TITLE
Invalid Feather Mattress Furniture Error

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#34604]
# Describe the bug

Error whenever f_feather_mattress is referenced in crafting.

# Steps To Reproduce

1. Crafting menu.
2. Search for "c:feather"

# Expected behavior

No error.

# Screenshots

![image](https://user-images.githubusercontent.com/56372745/66530052-1652c400-ead4-11e9-9ad9-52d508e8f42b.png)

# Versions and configuration

 - OS: Win7
 - Game Version: 0.D-8373-gdea6b62 [64-bit]
 - Graphics version: Tiles
 - Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Player Mod [Player_Mod],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3709945/debug.log)

**Comment by snipercup** [comment]
Was fixed in #34694. Try updating the game?

**Comment by new02DAY** [comment]
I'd just created the account to post the issue and GitHub flagged my account, so this didn't show up in public. Glad to see it was fixed.
