### ISSUE TITLE
When a vehicle hub is destroyed, the car keeps it's tires

### ISSUE THREAD

**Issue by TheGamingFox1911** [CleverRaven/Cataclysm-DDA#34607]
# Describe the bug
When a hub is destroyed before the tire itself is destroyed, the car keeps it's tires as if nothing happened to it.

# Steps To Reproduce

find a car that's damaged or spawn a vehicle hub and damage it
Smash the part of the car with the hub and wheels.
The hub will get destroyed and the tire will remain

# Expected behavior

When the hub is destroyed, the tire should fall off as there is nothing to hold it in place.

# Screenshots
![car](https://user-images.githubusercontent.com/52058797/66531911-143c3580-ead3-11e9-93c4-24a92d2d5180.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8335-gcb7b4b0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm]
]

**Comment by PaulBlay** [comment]
You can also destroy a frame that holds two parts of the vehicle together and it will still act as one vehicle.

**Comment by Night-Pryanik** [comment]
I didn't test it (it's tricky to find destroyed car with only wheel without wheel hub), but looking at the code, wheels should fall off when wheel hub is destroyed. I guess this issue could be safely closed after almost 2 years, but I'm leaving it open for now in case anyone still encounters it. Removing Bug label so this issue will be auto-closed (without any activity) after 2 months.

**Comment by int-ua** [comment]
I think I've seen a wheel fall off one time.
