### ISSUE TITLE
Failed to build the faction_base_field_camp_blacksmith_0 upgrade.

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#34609]
# Describe the bug

Someone breaks the faction base blacksmith. Probably #34411. 

# Steps To Reproduce

1. Make a camp
2. Try to build blacksmithy survey.
3.  3 hours passed, get the error when finishing the job.

# Expected behavior

Either build the blacksmithy without error or properly remove it from the game.

# Screenshots

Have some but cant uploaded for some weird network reason.

# Versions and configuration

 - OS: Windows 10
 - Game Version: cataclysmdda-0.D-Windows_x64-Tiles-9741
 - Graphics version: Tiles
 - Mods loaded: dda

# Additional context

Maybe it is part of those save migration issue, but please please next time when you remove something from the game, at least test it with old save.

**Comment by devgs** [comment]
Issue is still unfixed. Can someone tell me how to fix my saves? I can't recover a bunch of followers due to this bug?
