### ISSUE TITLE
Tradeing is broken again

### ISSUE THREAD

**Issue by Lucewithnootherideas** [CleverRaven/Cataclysm-DDA#34614]
trading is broken again, traders dont look for items in reach and the refugee center trader crashes the game

# Steps To Reproduce
trade and try to trade at refugee center

# Expected behavior

traders should trade with whats around the and the refugee center shouldn't crash the game

# Screenshots

![image](https://user-images.githubusercontent.com/51459975/66554755-03eb8100-eafa-11e9-9ae6-14287868ae30.png)

# Versions and configuration

version 1941 64 bit windows

# Additional context
there is also an awful lot of lag at the refugee center

**Comment by ZhilkinSerg** [comment]
Please provide a savegame.
