### ISSUE TITLE
Everything is unseen underground

### ISSUE THREAD

**Issue by kekvaze** [CleverRaven/Cataclysm-DDA#34611]
Made a bottom of a mine character and all terrain is unseen this has also happened inconsistently while just going into basements and such during normal gameplay.
Not sure if there is actually anything to do about it since sometimes basements work fine sorry if this is a pointless issue.
![Capture](https://user-images.githubusercontent.com/56379754/66540641-671ce980-eae1-11e9-9d11-fb4cfbbe4931.PNG)
Using experimental build 9741 on windows 7 32bit
Mods: Dark Days Ahead, Aftershock, Cataclysm++, Magiclysm, Secronom, Dinomod. Draco's dog mod, Disable NPC needs, Vehicle additions pack, Tanks and other vehicles, Folding parts, Urban development, No rail stations, More locations, More city locations, Mythical martial arts, Mutant NPCs, Alternative map key, Modular turrets, Salvaged robots, Icecoon's arsenal, Makeshift items mod, Medieval and historical classes and weapons, More survival tools, Classes and scenarios mod, Mutation changes, Stats through skills, No filthy clothes, Arcana and magic items, Simplified nutrition

**Comment by ZhilkinSerg** [comment]
It is pitch dark underground. You need to use something to light up your surroundings.

**Comment by ThomasLinkin** [comment]
Yeah,it's a feature now btw. You can't expect your character to sit in the dark and still being able to see things.

**Comment by kekvaze** [comment]
Thank you sorry for the pointless bug report just thought it was my computer being weird cause like I said sometimes I would see just fine in a basement and other times everything would be unseen and since I had the night vision trait I assumed I would at least be able to see my character
