### ISSUE TITLE
A rat farted five meters down. Curl up in fetal position and cry? Y/N

### ISSUE THREAD

**Issue by Muffindrake** [CleverRaven/Cataclysm-DDA#34621]
**Is your feature request related to a problem? Please describe.**  
I am sure that by now, the vast majority of all players are incredibly annoyed when trying to either pick up multiple things in a noisy area or perform some lengthy task and have resorted to wearing ear plugs at all times, which they most likely forget to take off until they are reminded by attempts of talking to NPCs. This is infinitely worse if your character has improved hearing through some means or another.

**Describe the solution you'd like**  
I doubt your character has a reason to care about footsteps a z-level down, so either 1) sounds from different z-levels should be plainly ignored or 2) the game should check whether there are ramps/stairs within a reasonable range that could result in the player getting jumped on if not made aware of a sound.

**Describe alternatives you've considered**  
Forsake NPC interaction by wearing ear plugs and enjoy portable meat carriers. I am already doing this.

**Comment by EkarusRyndren** [comment]
Not sure how possible this would be but it may be prudent to have a handful of sounds not be able to be heard through floors all together.

**Comment by MalcolmRose** [comment]
He's making a rhetorical point about the nature of the problem, @ZhilkinSerg - it's obviously not a real message. Did you seriously think he was pasting a real message, or is this just mockery of the issue? Did you even read the post?

**Comment by ZhilkinSerg** [comment]
> 
> 
> > The message in the title is probably from some third party mod which we do not support here.
> 
> He's making a rhetorical point about the nature of the problem, @ZhilkinSerg - it's obviously not a real message. Did you seriously think he was pasting a real message, or is this just mockery of the issue? Did you even read the post?

One can go and practice all the rhetoric they want elsewhere.

**Comment by MalcolmRose** [comment]
>One can go and practice all the rhetoric they want elsewhere.

Okay. Well, I find it really unfortunate that you are more interested in policing people's tones and manner of speech than fixing a very serious playability issue with the game.

**Comment by ZhilkinSerg** [comment]
> 
> 
> > One can go and practice all the rhetoric they want elsewhere.
> 
> Okay. Well, I find it really unfortunate that you are more interested in policing people's tones and manner of speech than fixing a very serious playability issue with the game.

I don't owe nobody a thing.

**Comment by MalcolmRose** [comment]
> I don't owe nobody a thing.

Seems like a really bad attitude, especially since no one asked you for anything here. You just showed up and closed an issue with a sarcastic remark because you didn't like the way the issue was worded. Is this the normal process for this project? Pretty disturbing.

**Comment by ZhilkinSerg** [comment]
You've just showed up and implied I should be interested in fixing something. Then you showed up again and implied more things about my behavior and now you are disturbed about the project. Don't worry - we are doing fine.

**Comment by Destragon** [comment]
You don't have to be interested in fixing it, but you didn't have to close the issue either. The title is silly, but this is still an issue people are annoyed by.
I guess there should probably just be an "ignore all interruptions except for damage" option or somthing like that.

**Comment by kevingranade** [comment]
If you can't be bothered to curb your rudeness, we can't be bothered to keep your issue open. There are plenty of people willing to report issues without doing it in an annoying manner.

**Comment by MalcolmRose** [comment]
You have absolutely got to be kidding me if you think the OP is somehow rude but Zhilkin's sarcastic response + issue closure isn't. I feel like I'm in the Twilight Zone right now.

**Comment by jeremyshannon** [comment]
While I understand Zhilkin's lack of patience with silliness in bug reports, I have to agree that Muffindrake's bug report (informal and wacky as it may be) doesn't strike me as particularly rude in any way.
 The title should definitely be clearer, though.

**Comment by Night-Pryanik** [comment]
Just stop finding an excuse for Muffindrake's poor wording and open a new issue with a normal title if the issue really bothers you.
