### ISSUE TITLE
Gas Mask not protecting from Smoke.

### ISSUE THREAD

**Issue by Craftomega** [CleverRaven/Cataclysm-DDA#34620]
# Describe the bug

I have a gas mask on, its activated, it has a filter, but my character still breathes in smoke. It does not matter the density of smoke, Thin, Reg, Thick, I still breathe it all in.

# Steps To Reproduce

1. Get a gas mask with a filter.
2. Activate it.
3. Walk into any kind of smoke.

# Expected behavior

The mask should protect from some forms of smoke.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8386-g311109a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Mutant NPCs [mutant_npcs],
    Folding Parts pack [deoxymod],
    Arcana and Magic Items [Arcana],
    Necromancy [necromancy],
    Magiclysm [magiclysm],
    Classes and Scenarios Mod [more_classes_scenarios],
    Simplified Nutrition [novitamins],
    No Filthy Clothing [no_filthy_clothing],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Stats Through Skills [StatsThroughSkills]
]

[Lovell 2 - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3713109/Lovell.2.-.Copy.zip)

**Comment by AMurkin** [comment]
The same as #33511.

**Comment by ZhilkinSerg** [comment]
Duplicate of #33511. Would be fixed in #34613.
