### ISSUE TITLE
Item hybridbow is not being spawned, no recipes eighter

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#34639]
# Describe the bug
No references to the hybridbow

# Steps To Reproduce
1. Search hybridbow https://github.com/CleverRaven/Cataclysm-DDA/search?q=hybridbow&unscoped_q=hybridbow
2. Observe there are no references to the item aside from a tileset

# Expected behavior
It should eighter spawn, one should be able to create it or it should be obsoleted.

# Screenshots
N/A

# Versions and configuration
N/A

# Additional context
N/A

**Comment by anothersimulacrum** [comment]
It appears it was added in #25101, but doesn't actually spawn.
It should probably spawn somewhere.

**Comment by snipercup** [comment]
I will work on this
