### ISSUE TITLE
Magiclysm's Smite spell does not damage hostile target despite sucessful cast

### ISSUE THREAD

**Issue by Spiky-Thorn** [CleverRaven/Cataclysm-DDA#34633]
# Describe the bug

When using the "Smite" spell on a hostile target, the spell cast successfully but the damage is not dealt to the target.

# Steps To Reproduce

1. Make or debug a character with smite
2. Target a hostile target
3. Cast the spell and see if damage registered.
4. If damage was dealt, cast it again on the same or another hostile target to see if damage is being dealt consistently.

# Expected behavior

If the bug is reproduced, you should see on the log experience is gained for casting it, an explosion is heard but no damage is displayed, the target is perfectly healthy. 
This should be replicable across the entire range of the spell's level

However, occasionally, the spell does deal damage to the target, sometimes it doesn't deal damage again on the next cast, sometimes it deals damage several times in a row. 

I found that most of the time damage is dealt is when I declined the "Stop casting spell" menu that pops up when you enter ESC, but subsequent attempt using the same method usually results in the original problem.

Perhaps the dodge of the target is taken into consideration when calculating whether the spell hit the target or not.

# Screenshots

![image](https://user-images.githubusercontent.com/56420646/66620648-1ee0f280-ebd9-11e9-9554-2c234feaaf2a.png)
Result of "successful" smite cast

![image](https://user-images.githubusercontent.com/56420646/66620795-b9413600-ebd9-11e9-8392-b030230858a2.png)
Magic missile was use to make sure it wasn't force damage that was bugged and not registering

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-8390-g8c5d5fa [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Mythological Replicas [nw_pack],
    More Survival Tools [More_Survival_Tools],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Hydroponics [hydroponics],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Beta National Guard Camp [national_guard_camp],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player icon, retrodays [sees_player_retro],
    Battery Migration for Existing Games [Battery_Overhaul_Legacy_Mode],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Manual Bionic Installation [manualbionicinstall],
    Classes and Scenarios Mod [more_classes_scenarios],
    Safe Autodoc [safeautodoc]
]

**Comment by amystewart256** [comment]
Note: This also occurs with Magic Missile.

**Comment by amystewart256** [comment]
Figured it out: something's borked with "target_attack" spells. They will occasionally go off but most often successfully cast without dealing damage. Maybe miscalculated target coordinates?

I knew that Woodshaft (lel) worked from an earlier playthrough so changed Magic Missile's target_attack to projectile_attack and upon a successful cast, damage is dealt.

**Comment by FuelType-Memes** [comment]
Can confirm. Smite cast is successful, it even generates the "You hear explosion" message, but does no damage

**Comment by FuelType-Memes** [comment]
@KorGgenT I think there is a problem with ```in_spell_aoe```

Adding
```
    "min_aoe": 1,
    "max_aoe": 1,
```
To Smite seems to fix the problem

**Comment by FuelType-Memes** [comment]
Got to test it a bit more:

Build 9898:
It's enough to add `"min_aoe": 0,` or `"aoe_increment": 0.0,` to Smite spell definition to make it work. Same fix applies to some other target_effect spells such as Laze

Adding `"max_aoe": 0,` doesn't matter

After some snooping in magic.cpp I believe the culprit to be somewhere in aoe calculation, maybe `min_leveled_aoe()`

@KorGgenT you asked to add you a reminder
