### ISSUE TITLE
Trading adds/subtracts from NPC max volume/weight weirdly

### ISSUE THREAD

**Issue by molkero** [CleverRaven/Cataclysm-DDA#34649]
# Describe the bug

Trading stuff from NPCs affects their max volume/weight in the trade screen, so that they can go negative volume if you take items from them.

# Steps To Reproduce

1. Find and trade with an NPC.

# Expected behavior

Taking items from NPC would give them more space, giving them items would give them less space.

# Screenshots

This NPC has 2,5L of storage and a 2,5L canteen. Taking the canteen makes him go from 0 volume to -2,5L.
![20191011145055_1](https://user-images.githubusercontent.com/49575273/66650049-59c64300-ec38-11e9-8f6a-167a98989d0f.jpg)
Giving him stuff also gives him more available volume and weight.
![20191011145123_1](https://user-images.githubusercontent.com/49575273/66650093-73678a80-ec38-11e9-9058-1d25e9d3e1a2.jpg)

# Versions and configuration

 - OS: linux
 - Game Version: 0.D-8418-g126c27ba3e
 - Graphics version: tiles
 - Mods loaded: 
[
  "dda",
  "mutant_npcs",
  "boats",
  "blazemod",
  "Tanks",
  "sleepdeprivation",
  "cbm_slots",
  "magiclysm"
]

# Additional context

Noticed this because my NPC friend is a bear and can't wear much other than an XL jumpsuit with not much storage.

EDIT: Propably not related, but every time I visit the trade screen, I get a message "NPC drops a ." in the log.

**Comment by ANickelN** [comment]
Trading is borked right now, this is probably related to the game crash when trading at refugee center.
