### ISSUE TITLE
UI and dialog window positions confused when game loses focus

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#34650]
# Describe the bug

If you go from playing Cataclysm full-screen and ALT TAB to another program you will often find the right hand side of the game no longer displays the information it should. If you exit the game with 'S'ave the title screen will also have misplaced the menu options on the bottom of the screen.

# Steps To Reproduce

1. Start the game (full screen)
2. ALT-TAB to a different program.
3. Play some other game in full screen mode.
4. Exit other game.
5. ALT-TAB back to cataclysm

# Expected behaviour

Cataclysm should recognize when the monitor resolution has changed, and changed back. I think this is where it goes wrong.

# Alternative considered

Accept this as my rightful punishment for playing other games.

# Screenshots

![titlescreen](https://user-images.githubusercontent.com/54060142/66657950-6e0a4000-ec38-11e9-93f6-081d1048d5ff.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 8.1
- Game Version: 0.D-8405-gb915f8b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Qrox** [comment]
Should be fixed by the new ui_adaptor system.

**Comment by Night-Pryanik** [comment]
Ok, closing until reconfirmed.
