### ISSUE TITLE
Bionic power constant int overflow

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#34665]
# Describe the bug

```
void Character::mod_power_level( units::energy npower )
{
    power_level = clamp( power_level + npower, 0_kJ, max_power_level );
}
```

There is no check for overflow when adding power_level to npower.
Whenever there is bionic power gain there is a chance for overflow resulting in some "random" value of power. Or loosing all the power.
I tried fixing it but gave up :(

# Steps To Reproduce

1. Make a player with maximum bionic power.
2. Use some bionic power.
3. Eat battery with more charges than you used in point 2.

There are other places when overflow happens, not only battery eating.

# Versions and configuration

build 9478

# Additional context

#34431 should be merged and bionic power should be cut to defined value (for now)
Also we have batteries with more than 2k power. If we would want to use energy units for them we won't be able without int64.

**Comment by anothersimulacrum** [comment]
Looking into this.
