### ISSUE TITLE
Z-levels: Cannot see monsters below or above me when (x)looking or (f)shooting

### ISSUE THREAD

**Issue by GroeneAppel** [CleverRaven/Cataclysm-DDA#34676]
# Describe the bug
With Z-levels enabled the player cannot see any monsters on floors below him, or above him, when he should be able to.

# Steps To Reproduce
1. Create a world with Z-levels enabled and spawn with any character.
2. Go to a roof/window upstairs. 
3. press (x) to look around and  < or > to change z-level.
4. Notice that you can see surroundings objects, but no monsters. 

# Expected behavior
I expect to see monsters below me when looking down from a ledge, and for said monsters to be able to see me.

# Screenshots
Upstairs:
http://puu.sh/ErGu3/933151defd.png
Looking downstairs with (x):
http://puu.sh/ErGu8/1923387fc6.jpg
Seeing what is actually downstairs as I throw my poor testpuppet down the ledge:
http://puu.sh/ErGuX/774909fdac.jpg

# Versions and configuration
- OS: Windows 7
- Game Version: 0.D-8428-g254c7c2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: 
    Dark Days Ahead [dda]

# Additional context

For the sake of ease i've made a testworld and attached it to this post:
[BugTest.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3720581/BugTest.zip)
It contains the same world & character as shown in the screenshots.

**Comment by Night-Pryanik** [comment]
Cannot confirm on 0.D-8431.
![изображение](https://user-images.githubusercontent.com/11132525/66700926-51890900-ed07-11e9-8978-3d865fa363ec.png)

Do you have z-vision turned on?

**Comment by GroeneAppel** [comment]
@Night-Pryanik It turns out my Z-vision was off. 
I can see zeds on lower levels now without issue. Everything is working as intended.
