### ISSUE TITLE
You can damage spilled liquids by driving over them.

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#34714]
# Describe the bug

You can damage spilled liquids by driving over them.

# Steps To Reproduce

1. Pour gasoline onto the road
2. Drive a car over it.
3. Get message "The weight of your car damages the gasoline."
4. The gasoline patch then disappears.

# Expected behaviour

Either nothing happens, or a different message like "Your car splashes the gasoline around."

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 8.1
- Game Version: 0.D-8405-gb915f8b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by SageB** [comment]
Yeah, that happens, it's a known issue. Per #34598, 

> Testing of this PR revealed several issues with using chip resistance for map::smash_items(). Even light vehicles like the bicycle can deal damage to giant ant corpses, liquids can be run over and destroyed, etc... Ideally, another value representing crushing resistance would be added to existing materials, but that is outside the scope of this PR.

I do plan on fixing it, but I need to get more familiar with how the game loads/parses JSON.
