### ISSUE TITLE
Remove "master-cataclysm-dda-deprecated" from transifex

### ISSUE THREAD

**Issue by mdtrooper** [CleverRaven/Cataclysm-DDA#34739]
More or less one year ago, "Translate msgid "battery" bug in all *.po files in 4fa18e9 commit" #23561 appeared and the workaround was move the corrupt file to master-cataclysm-dda-deprecated.po.

And now the master-cataclysm-dda.po in several languages (I have been check spanish and spanish-argentinan) is updated. And master-cataclysm-dda-deprecated.po is useless.

Maybe it is a good time to delete this file from transifex.

**Comment by BrettDong** [comment]
You are right, that branch was created solely for backup purpose in case anything got screwed up, and it is totally useless now. I just tried to remove that on Transifex, but their UI doesn’t seem to respond after I press the delete button... 😨

**Comment by BrettDong** [comment]
Finally I managed to delete `master-cataclysm-dda-deprecated`. This is solved.

**Comment by mdtrooper** [comment]
Thanks @BrettDong  :beers:
