### ISSUE TITLE
Incorrect Error Message on Foot Pedals

### ISSUE THREAD

**Issue by Morat2255** [CleverRaven/Cataclysm-DDA#34737]
Game version:
9748
Operating system:
Windows 10
Tiles or curses:
0.D-8418-g126c27b (tiles)

### Expected behavior
When attempting to use a vehicle with foot pedals after neglecting to add a seat, the error message should reference the lack of seat, or at least should not falsely claim a different cause of error.

### Actual behavior
When using a vehicle with foot pedals but no seat, the error message received is "cannot use foot pedals with a broken leg".

### Steps to reproduce the behavior
Construct a vehicle with footpedals and no seat and attempt to start the vehicle. I tested with a 2 wooden frame vehicle, both with and without a battery, both with and without alternator. I did not test with wheels.

**Comment by AlexMooney** [comment]
I've also seen this bug on master cb7938ebf7.  In my case it was a due to badly damaged foot pedals, and after receiving the broken leg message, I was able to drive the bike with another `^` attempt.
