### ISSUE TITLE
Add trait "Animal Brethren" with significant benefits for a beast-tamer playthrough

### ISSUE THREAD

**Issue by MitztheKat** [CleverRaven/Cataclysm-DDA#34742]
I've always wanted to have a beast-tamer playthrough with 20 cows, 5 pigs and 300 cats at my side, but taming them is difficult and expensive. what if I could take an expensive trait and be the bob ross of animals?
The trait would make every animal essentially ignore you, and being around them for significant periods of time will automatically tame them.
alongside the auto-taming, playing with your pets will give a **much bigger** boost to morale than the usual. because, who doesn't like snuggling a big doggo or catto? these guys love to.
This trait would likely be very expensive, but, on the other hand, will provide beast tamers an excellent source of morale and party members.
You could easily upgrade a trait, which is also an option, so there's that.
_I wanna be a beast tamer!_
(I'm sorry if this is a dupe, I tried to look for it.)

**Comment by shadowsapex** [comment]
How is it difficult and expensive to make pet taming food

**Comment by kevingranade** [comment]
I'd be interested in more detailed taming stuff, including doing things to attract animals to you to attract them instead of having to chase them down, but the whole thing is way more abbreviated than it should be right now, making it even easier is over the top.
