### ISSUE TITLE
Silat can't be used unarmed after dropping wielded item.

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#34747]
# Describe the bug
Silat is an armed/unarmed fighting style. When reloading the game unarmed it recognizes it correctly, but when wielding something and then dropping it, you can't pick silat as style until reloading the game

# Steps To Reproduce

1. Start a character with meele training, pick Pencak Silat
2. check Style, should be Silat.
3. Pick Item up unfit for Silat, for example long stick, or rock
4. drop wielded object
5. check Style, now "No Style"
6. try to pick Silat as style -> Silat cannot be used unarmed.
7. Reload game, to have Silat again.

# Expected behavior

Pick Silat as unarmed style after droping stuff.

# Screenshots

![1](https://user-images.githubusercontent.com/33199510/66763234-ca26cb80-eea7-11e9-861b-d4e0e9550aa4.jpg)
![2](https://user-images.githubusercontent.com/33199510/66763242-cb57f880-eea7-11e9-87bc-2d6dbba69248.jpg)
![3](https://user-images.githubusercontent.com/33199510/66763245-cc892580-eea7-11e9-9a93-1ff984c6848a.jpg)
![4](https://user-images.githubusercontent.com/33199510/66763248-ce52e900-eea7-11e9-9289-088f0c9f80a1.jpg)

# Versions and configuration

dda
no NPC Needs
Version 9764

**Comment by reed501** [comment]
I don't think Silat is an unarmed style, but it is weird that it allows you to use it unarmed at all.
@Hymore246 do you have any input or corrections?

**Comment by Lamandus** [comment]
Eh, Silat is mostly an unarmed style. Weapons are used rarely. Especially the most common forms in Indonesia. Source: my wife is Indonesian and knows Pencak Silat.

**Comment by reed501** [comment]
If you wish to offer a potential balance/feature change you might want to make a new issue because this is definitely a bug report. Currently as of a recent balance patch, as well as before the patch, silat has been and is a melee style - There are no unarmed techniques. #34479 has more information. A similar issue has been brought up for Eskrima and there is also additional information there #33264

**Comment by Lamandus** [comment]
Ah, I wasn't aware that there weren't any hits with unarmed. My bad. Anyway, still the bug remains that unarmed is showing Silat as a style when reloading the game barehanded.

**Comment by Hymore246** [comment]
#34987 fixed this.

**Comment by Lamandus** [comment]
> 
> 
> #34987 fixed this.

yupp
