### ISSUE TITLE
Enhanced Memory Banks costs no power to use

### ISSUE THREAD

**Issue by WormGrill** [CleverRaven/Cataclysm-DDA#34745]
# Describe the bug
The Enhanced Memory Banks CBM costs no power to activate nor upkeep. In the bionics menu it also shows that it won't drain any power.

# Steps To Reproduce
1. Create a character with the Bionic Game Master class, which starts with the Enhanced Memory Banks CBM
2. Turn on the CBM
3. Observe that no power is drained to activate it nor to keep it active.

# Expected behavior
Unless the Enhanced Memory Banks CBM was changed recently to not cost any bionics power, it should be draining power. Or if it's intentional for it to be free, then it should be a passive CBM because there's no downside to having it active if it doesn't cost power.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8520-gcb7938e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Karthas077** [comment]
Enhanced Memory Banks is currently configured to use 2 Joule per second. Bionic power is usually measured in kJ, which means it should decrease by 1 every ~9 minutes.

**Comment by jtriddle** [comment]
Is this just a display issue?
I just went to sleep with Climate Control and Dielectric Capacitance ON and woke up with same amount of bionic power as before sleep. No power sources were active, power wasn't at max and it stayed the same after ~8 hours of sleep.

**Comment by KJVE** [comment]
I am having a similar problem where all bionics with power usage seem to be either 0x the cost to x10 the cost.
![cataclysm-tiles_lyKiLGa7Ub](https://user-images.githubusercontent.com/56508486/66866183-17369a80-ef99-11e9-9e61-7cc422089123.png)

Sorry if this is a known problem. This is just the first post that seemed to have the same issues.

**Comment by KJVE** [comment]
Currently have this issue with most CMB's, with no mods installed. 
![image](https://user-images.githubusercontent.com/56508486/66866594-e6a33080-ef99-11e9-9380-70fa23e0c4bf.png)

**Comment by Fris0uman** [comment]
Dielectric Capacitance should (If my math is correct) use 144kJ over 8h, and Climate Control should have used 2800kJ. So there might be something fishy with climate control at least, unless it doesn't draw power when the temperature is already good.

**Comment by Fris0uman** [comment]
Now that the UI will display stuff properly, this can be tested again, just to be sure.

**Comment by Fris0uman** [comment]
There is in fact a problem with bionic not drawing power, this issue can be reopen.
![image](https://user-images.githubusercontent.com/41293484/67143247-c9a48100-f269-11e9-88d8-34ef7f7e48c5.png)


```cpp
                // Try to recharge our bionic if it is made for it
                int cost = 0;
                bool recharged = attempt_recharge( *this, bio, cost, discharge_factor, discharge_rate );
                if( !recharged ) {
                    // No power to recharge, so deactivate
                    bio.powered = false;
                    add_msg_if_player( m_neutral, _( "Your %s powers down." ), bio.info().name );
                    // This purposely bypasses the deactivation cost
                    deactivate_bionic( b, true );
                    return;
                }
                add_msg( "cost: " + to_string( cost ) );
                if( cost ) {
                    mod_power_level( units::from_kilojoule( -cost ) );
                }
````
