### ISSUE TITLE
Mythological Replicas weapons don't work with martial arts

### ISSUE THREAD

**Issue by WormGrill** [CleverRaven/Cataclysm-DDA#34748]
# Describe the bug
The weapons from the mod Mythological Replicas don't work with the martial arts their base weapons work with. Laevateinn doesn't work with Medieval Swordsmanship and Ninjutsu, but the Arming Sword does. Gungnir doesn't work with Silat or Sojutsu, but the Steel Spear does.

# Steps To Reproduce
1. Debug learn all martial arts styles.
2. Spawn in Laevateinn, Gungnir, an arming sword, and a steel spear.
3. Observe that the arming sword and steel spear work with their respective martial arts, but the mythological replica's are not considered valid weapons for those styles.

# Expected behavior
The mythological replica's should still work with the martial arts styles of their base weapons, crafting them doesn't fundamentally change how they work from the base weapons. Really it's just adding gold/silver inlays into them.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8520-gcb7938e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Mythological Replicas [nw_pack],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock]
]

**Comment by Karthas077** [comment]
Weapons allowed for a martial art are currently extremely explicit. This falls under the problem of the creator of Mythological Replicas not extending the list of allowed weapons to include their variants.

**Comment by jeremyshannon** [comment]
Seems like some kind of "functions_as" tag could be useful.

**Comment by LaVeyanFiend** [comment]
Fix coming soon! 🎉
