### ISSUE TITLE
Un-Swappable Storage Batteries

### ISSUE THREAD

**Issue by Karthas077** [CleverRaven/Cataclysm-DDA#34741]
# Describe the bug

Storage batteries cannot be installed into their case without using a welder.

# Steps To Reproduce

1. Create a vehicle with a swappable storage battery case.
2. Have a nearby storage battery
3. Attempt to install the battery without a welder.

# Expected behavior

The storage battery can be installed provided you have the strength/lifting to do so.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-8505-gf66b63b
 - Graphics version: Tiles
 - Mods loaded: Alternative Map Key, No Antique Firearms, No Survivor Armor, Sleep Deprivation, Stats Through Skills

# Additional context

A change from six months ago #29595 made storage batteries use non-legacy requirements. As the code currently stands, this prevents the removable version from being installed without a welder. The "using" array remains present in the removable copy. I have a current naive solution working which uses the fact that a single string "using" will overwrite the array of the base object, but will submit a PR later this evening with a hopefully more robust solution.

**Comment by esotericist** [comment]
First off: Mods are never `N/A` when reporting a bug like this. Please include that information. As of experimental versions a while ago, game helpfully has a tool to populate the information needed for bug reports, when you hit `esc`, in the debug info.

Second: that change from six months ago cannot possibly be responsible for this problem, seeing as how I was installing swappable storage batteries for months afterwards.

**Comment by Karthas077** [comment]
I have added the mods I am using. As you can see, they clearly have zero impact on the relevant section of the game and are, as such, not applicable to this bug.

**Comment by esotericist** [comment]
I've already confirmed the bug without mods, I'm just stating that as a matter of policy for bug reports of this type, N/A is incorrect; it's always possible one of them does have impact and you just didn't realize it.

**Comment by Karthas077** [comment]
So in the future when I duplicate the bug in my modless testbed should I put "None" instead of N/A?

**Comment by esotericist** [comment]
> So in the future when I duplicate the bug in my modless testbed should I put "None" instead of N/A?

Yes, but I would request in such a case you explicitly state you tested it without mods; we've had instances in the past with users reporting "none" when they had an arbitrary mod they just assumed couldn't possibly be the problem and thus not worth mentioning (even though it turned out to be the problem). It's best to not have any ambiguity.

**Comment by esotericist** [comment]
I've narrowed the cause down to #34455 by @jbytheway.

I'm not sure what the correct fix is here, hopefully he can shed some light since he's been putting a lot of work into json parsing cleanup lately.

**Comment by Karthas077** [comment]
I have a workaround fix that "solves the problem" by requiring a screwdriver, but I have a better solution in mind that just requires me to go through the vehicle parts json files.

**Comment by kevingranade** [comment]
Could you outline that solution? I'm sceptical of a solution that requires you to edit anything  ut the involved code or parts.

**Comment by Karthas077** [comment]
I'm not sure where you got the idea that vehicleparts json files aren't involved as they are the reason that jbytheway made the changes to the "using" code that he did. By figuring out what needs to be changed on both ends, I can hopefully either reverse his change, or possibly render the entire legacy section of veh_type.cpp obsolete by updating the json.

**Comment by jbytheway** [comment]
I assume it must have been the change to `veh_type.cpp` in #34455 that caused this, but I don't understand how.  The welding requirement looks like it comes from `storage_battery` via a sequence of `copy-from`s, and I don't see how my change would have affected that...

**Comment by Karthas077** [comment]
`storage_battery_removable` has a requirements without a using.
With the original code, the lack of a using would trigger the attached `else`, which would cause the `reqs` container to be replaced.
Your change uses `emplace_back` to add a possible in-line requirement, causing the copied welder to persist.

**Comment by jbytheway** [comment]
Makes sense.
