### ISSUE TITLE
Disassembly of a blanket vs down-filled blanket is far too different

### ISSUE THREAD

**Issue by jrholliday94** [CleverRaven/Cataclysm-DDA#34757]
# Describe the bug

Time to disassemble blanket is 1 hour. Time to disassemble down-filled blanket is 2 minutes.

# Steps To Reproduce

Attempt to disassemble a blanket and down-filled blanket and observe the time required.

# Expected behavior

Disassembly time should probably be higher for down-filled blanket. Currently it is 30x quicker for a down-filled blanket to be disassembled vs a regular blanket.

# Screenshots

https://i.imgur.com/rFt1p9B.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8520-gcb7938e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable Religious Texts [no_religious_Texts],
    No Antique Firearms [no_olg_guns],
    No Acid Zombies [No_Acid_Zombies],
    No Explosive Zombies [No_Explosive_Zombies],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Zombie Nightvision [Zombie_Nightvision]
]

**Comment by snipercup** [comment]
These are the crafting recipe's and one uncraft recipe for the down_blanket:
![image](https://user-images.githubusercontent.com/50166150/66852168-a2edfe00-ef7c-11e9-9618-5193bb06d260.png)


There is a uncraft recipe for the down_blanket even though the recipe for down_blanket has 'reversible: true'

The first solution that comes to mind is to remove the uncraft recipe. I will work on it.
