### ISSUE TITLE
Crafting armor using poor-fitted clothing with no warning

### ISSUE THREAD

**Issue by Berkyjay** [CleverRaven/Cataclysm-DDA#34760]
# Describe the bug
Crafting apparel will use poor-fitted components before fitted components without any warnings.  

If I go to craft a "Light Survivor Suit" for example, and I have 3 "rain coats" in my inventory with one of those rain coats being poor fitted, the crafting process will consistently use the poor fitted component without warning.

# Steps To Reproduce
1. Spawn the items to produce a piece of clothing (Light Survivor Suit in my example.
2. Make sure you have a batch of one component and make one of them a poor-fitted item (rain coats in my example).
3. Craft the item and select to use a rain coat.

# Expected behavior
I would expect one of two results:
1. The crafting process will automatically use fitted components if available.
2. A warning that a poor-fitted component is being used and will cause the crafted item to be poor-fitted.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-8520-gcb7938e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by kevingranade** [comment]
Considering how hard this is to address within the crafting framework, I'm not sure that the feature to make results unfitted if the inputs are unfitted is worth keeping, this seems like a much bigger problem than the original issue, which IIRC was "cutting sleeves off a coat makes it automatically fitted".

**Comment by I-am-Erk** [comment]
What about just flagging particular recipes to not change the clothing fit? For most recipes it really doesn't matter, it's just the odd "cutting sleeves off a coat" thing that needs to not do it.

**Comment by KorGgenT** [comment]
i agree with erk here, adding a recipe flag seems to me like a reasonable fix to the _original_ issue of cutting sleeves off of a coat.
