### ISSUE TITLE
True Foodperson Mask Removal

### ISSUE THREAD

**Issue by Pynter** [CleverRaven/Cataclysm-DDA#34779]
If you use the Sort Armor menu and to remove armor then it's possible to remove the Foodperson Mask when playing as a True Foodperson.

# Steps To Reproduce

1. Spawn in as True Foodperson
2. Remove the Foodperson Mask using the Sort Armor menu.

# Expected behavior

To not be able to take the Foodperson Mask off.

**Comment by Fris0uman** [comment]
Can't reproduce the bug.
Did you forget to turn it on first?

**Comment by Pynter** [comment]
As the true foodperson you're not supposed to be able to take it off at all, if I understood the character right.

**Comment by Fris0uman** [comment]
You can remove it if it's not powered but you will get a mood debuff  and be unable to talk if you do.

**Comment by Pynter** [comment]
Then I must have misunderstood the character.

Don't mind me and my stupidity
