### ISSUE TITLE
0,0,0 map tile full of items: soil,tools,steel barrels

### ISSUE THREAD

**Issue by int-ua** [CleverRaven/Cataclysm-DDA#34776]
# Describe the bug
Yesterday experimental:
![2019-10-15-171446_1920x1080_scrot](https://user-images.githubusercontent.com/1585431/66839784-a5962680-ef6f-11e9-9c64-21008118cfdf.png)

# Steps To Reproduce

1. Teleport to 0,0,0 in any of your latest experimental saves.

# Expected behavior
Usual random tile.

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.3 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-8520-gcb7938e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    More Survival Tools [More_Survival_Tools],
    Disable Religious Texts [no_religious_Texts],
    No Antique Firearms [no_olg_guns]
]

**Comment by ZhilkinSerg** [comment]
Similar to #31648

**Comment by ZhilkinSerg** [comment]
Did you use any mods when starting game that you have changed before loading a savegame? Is it reproducible in new games too?

**Comment by ZhilkinSerg** [comment]
It can be reproduced back to build 9141, thus it was most probably caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/31295.

**Comment by int-ua** [comment]
No mods removal, first save I got this on was as vanilla as it gets: Play now was the first thing with config dir empty.

**Comment by AMurkin** [comment]
(0,0,0) in my world
![image](https://user-images.githubusercontent.com/1931904/66855648-b6a55e80-ef94-11e9-87a7-c895c22d27cd.png)
modlist:
```
[
  "dda",
  "no_npc_food"
]
```

**Comment by mlangsdorf** [comment]
It's clearly the `blueprint_autocalc` code gone crazy.  I wonder why this suddenly started appearing?

**Comment by ZhilkinSerg** [comment]
> 
> 
> It's clearly the `blueprint_autocalc` code gone crazy. I wonder why this suddenly started appearing?

It started long time ago in #31115

**Comment by fluffe9911** [comment]
Oh yeah I noticed this just figured it was one of those unmarked easter egg things you can find on the map like that cabin with the grave.

**Comment by Xenomorph-III** [comment]
I actually thought that was an easter egg too... like an abandoned base/unfinished base judging by all the tools and materials scattered about.

If there is a way to convert it into an actual, balanced map extra I'll be down with it.

**Comment by Little-119** [comment]
It's not a bug, it's a Feature™

**Comment by mlangsdorf** [comment]
Possible solution:
in `get_changed_ids_from_update()`, call `fake_load()` twice, first with `tinymap real_map` and then again `tinymap fake_map`.  Before the end of the function, explicitly save `real_map` which should contain the original map data.
