### ISSUE TITLE
Shoddy laser rifle can't use disposable batteries

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#34774]
Describe the bug
The shoddy laser rifle only accepts rechargeable batteries. At least most of the battery powered tools can also use disposable and plutonium batteries, so they appear to have no large differences in size or voltage.

1. Read the description of the shoddy laser rifle, note the compatible magazines.

Expected behavior
Shoddy laser rifle can use all heavy batteries.

Game Version: e.g. 0.D-8505-gf66b63b

**Comment by GroeneAppel** [comment]
I recall that you can't mod the shoddy laser to accept an UPS either.
