### ISSUE TITLE
"invalid recipe id " when Farming Plots (PR 9766)

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#34780]
# Describe the bug

 DEBUG    : invalid recipe id ""

 FUNCTION : const T& string_id<T>::obj() const [with T = recipe]
 FILE     : src/recipe_dictionary.cpp
 LINE     : 59

# Steps To Reproduce
 Attempting to use 'Farm plots' in Zone Activities menu results in the error. No seeds are in inventory aside from tools. 
Seeing a repeated "The required items are not available to complete this task. x(x)" message in the event log on the right after (I)gnoring the error and proceeding with the task even if "No Seed" is selected in the original Zone Designation.

# Expected behavior
Not too sure as to the cause but the tilling is attempted with a metal Shovel and there are Shrubs in the highlighted zone designed via Zone Manager in the Tilling zone which have not been removed prior.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-8522-gd1eeaf3 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    No Acid Zombies [No_Acid_Zombies],
    No Explosive Zombies [No_Explosive_Zombies],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    Urban Development [Urban_Development],
    Bionics Systems Mod [bio_mod],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Makeshift Items Mod [makeshift],
    Classes and Scenarios Mod [more_classes_scenarios],
    No Flaming Weapons [no_flaming_weapons],
    No Antique Firearms [no_olg_guns],
    Disable Religious Texts [no_religious_Texts],
    No Fictional Guns [no_rivtech_guns],
    No Sci-Fi Equipment [no_scifi],
    Extended Realistic Guns [realguns]

# Additional context
[Belen.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3730250/Belen.zip)

**Comment by davidpwbrown** [comment]
Im guessing the "no seed" farming zone tries to find an empty requirements id. I can add special handling for that type of farming zone to not do any planting or try and find any seeds for it ( I thought I did this before, but apparently not )
