### ISSUE TITLE
Trading an item to an NPC will delete any similar items you are wielding

### ISSUE THREAD

**Issue by benjaminmkos** [CleverRaven/Cataclysm-DDA#34795]
# Describe the bug

If I trade a repeating crossbow to an NPC while my player is wielding a different repeating crossbow, my wielded repeating crossbow is seemingly deleted out of existence.

This likely affects other weapons / items as well, but I discovered it with repeating crossbows specifically.

# Steps To Reproduce

1. Get two repeating crossbows and a friendly NPC.
2. Have your player wield one of the repeating crossbows.
3. Trade the other repeating crossbow from your inventory to the NPC.
4. Look at your wielded weapon.

# Expected behavior

Items that I do not trade to NPC's are not deleted out of existence when I trade with NPC's

# Screenshots

![cddatradingbug1](https://user-images.githubusercontent.com/6393606/66876666-a8e5de00-ef80-11e9-9c99-eda01f1c9dc5.png)
![cddatradingbug2](https://user-images.githubusercontent.com/6393606/66876672-aaafa180-ef80-11e9-9274-e23d86344879.png)
![cddatradingbug3](https://user-images.githubusercontent.com/6393606/66876678-ac796500-ef80-11e9-8122-5064c0538f5f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8521-g0c7d821 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by NotFuji** [comment]
Possibly related to #34708

**Comment by Tadders1488** [comment]
Can confirm with vibrator :^)
