### ISSUE TITLE
Regular Cellphone is an Infinite Flashlight

### ISSUE THREAD

**Issue by ANickelN** [CleverRaven/Cataclysm-DDA#34799]
# Describe the bug

The ordinary cellphone (NOT the smartphone) has a flashlight function.  That is all well and good, but the charge on it does not go down.

# Steps To Reproduce

Get a cellphone and activate it, then pass time.

# Expected behavior

The flashlight should drain the phone's battery.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8550-g637fed5 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    [DP_MOD] Hide DEBUG [DP_No_Debug_Tile],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food]
]

**Comment by ANickelN** [comment]
Looking at it again, it seems like it does go down over extended periods.  Still, the rate is ridiculously efficient for a cellphone flashlight.

**Comment by Tadders1488** [comment]
Yeah, it goes down eventually.  Maybe 20-30 mins per % .  Which should be more efficient, cell-phone flashlight or smartphone flashlight?

**Comment by Oddant1** [comment]
Regardless, ~25 minutes per percentage of battery decrease doesn't seem realistic. I feel like my phone dies much faster than that with the flashlight on, so I suppose the question becomes how much do we care about realism here?

**Comment by Xion350** [comment]
Both the Cellphone and Smartphone use the same battery usage.

https://github.com/CleverRaven/Cataclysm-DDA/blob/12dbcff92b7d8914538a027923b14099b31785cb/data/json/items/tools.json#L1016-L1024

https://github.com/CleverRaven/Cataclysm-DDA/blob/12dbcff92b7d8914538a027923b14099b31785cb/data/json/items/tools.json#L1072-L1083

I don't really think the power draw is totally unrealistic, the light produced isn't very much.  It seems less like the Flashlight app and more like you're just using the screen to light up the immediate area.

**Comment by ANickelN** [comment]
If it is meant to just be lighting up the screen, then it should be something like cloudy lighting only on the current tile...  If it is the phone's flashlight function then the current radius makes sense, but not the power drain.  You'd have to pick one or the other.

**Comment by Oddant1** [comment]
Yeah if it's just the screen then ~41.6 hours of battery life is SOMEWHAT reasonable. . . And it shouldn't light a very large radius. Although the screen would probably be turned up all the way making that time much less believable, and the flashlight definitely wouldn't last that long.
