### ISSUE TITLE
Taekwondo unhindered bonus errors

### ISSUE THREAD

**Issue by reed501** [CleverRaven/Cataclysm-DDA#34815]
# Describe the bug

Taekwondo unhindered is active while a weapon is wielded, and it also has an error and text issues.

# Expected behavior

Taekwondo unhindered only applies when no weapon is equipped.

# Screenshots

![Screenshot 2019-10-16 at 22 39 35](https://user-images.githubusercontent.com/12606597/66980636-5da5fb00-f066-11e9-86a4-83631c485e3a.png)
![Screenshot 2019-10-16 at 22 39 50](https://user-images.githubusercontent.com/12606597/66980640-60a0eb80-f066-11e9-8f98-f11f5f2a99b5.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 9.11 (stretch); Release: 9.11; Codename: stretch; 
- Game Version: 0.D-8583-g08353e3 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Zireael07** [comment]
Taekwondo is only kicks, so I think it is by design.

**Comment by Orinyau** [comment]
Taekwondo was recently updated so that its most powerful moves (and a buff iirc) require empty hands. "Unhindered" should only pop up if hands are empty.

**Comment by reed501** [comment]
Might have been a lack of clarity, should be fixed.
