### ISSUE TITLE
Single NPC acting contrary to rules and freezing game.

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#34814]
# Describe the bug

Specific NPC freezes game if you accept her quest to kill the zombie leader (necromancer?).
Ignores no pickup rules. Then picks up something different. Then goes out of her way to bash a window so she can pick up a glass shard when she has no bashing obstacles rules. 

[Totowa.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3737467/Totowa.zip)

No lofg files because game freezes without ever crashing

# Steps To Reproduce

1. Load game. Speak with Tennille. Accept quest to kill zombie leader.  Game freezes.  
2. Reload game
3. Walk around with her.  Witness he rulebreaking

# Expected behavior

Quest to start and game to continue running.  Rules set in character window to be adhered to. I suppose it's not a big deal.  I can go find a horde and let her charge at them.

# Screenshots

![pickup](https://user-images.githubusercontent.com/54345792/66979166-8cc66780-f07a-11e9-8ae8-fc4c7a07426a.jpg)
![rules](https://user-images.githubusercontent.com/54345792/66979168-8cc66780-f07a-11e9-821b-0cc17c150ca4.jpg)
![no felt but yes rags](https://user-images.githubusercontent.com/54345792/66979182-9354df00-f07a-11e9-8692-479972ba483e.jpg)

# Versions and configuration

 - OS: Win 7
 - Game Version: O.D 9766
 - Graphics version: [Tiles 
 - Mods loaded: [everything but generic guns and desert region, from mainline mods)

# Additional context

**Comment by Maleclypse** [comment]
She seems to both be a follower and have left my faction at the same time.

**Comment by zeggz** [comment]
Exact same bug here.

**Comment by davidpwbrown** [comment]
@Maleclypse has this particular save been created a while ago, or fairly recently?
