### ISSUE TITLE
Android version crashes instantly on startup

### ISSUE THREAD

**Issue by Acidifie** [CleverRaven/Cataclysm-DDA#34836]
# Describe the bug

Android version crashes instantly on startup

# Steps To Reproduce

Nothing else to add, start the game and instantly get "Cataclysm has crashed".
Of note, the game extracts data normally on first run, it crashes after selecting Software renderer, then crashes instantly on subsequent launches.

# Expected behavior

Game should run.

# Versions and configuration

Device: Shield Tablet K1
OS: LineageOS 14.1 (Android 7.1)
Versions tested: crashes happened on multiple tested versions starting from build [9633](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b9633) to most recent experimental. 
Builds [9632](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b9632) and prior aren't affected.

# Additional context

As stated above, crashes started to appear after build 9633 containing changes to libsdl.
[Logcat](https://pastebin.com/5piSEzMd) of the crash 
Might be related to https://github.com/CleverRaven/Cataclysm-DDA/issues/33781, but i can't confirm.

**Comment by ZhilkinSerg** [comment]
I am pretty sure there is the same root cause as in #33781.

**Comment by ZhilkinSerg** [comment]
Please try build 9785 and confirm it is not crashing.

**Comment by Acidifie** [comment]
9785 works fine now, thanks, although the redesigned title screen doesn't quite fit with the default terminal settings.
![](https://i.imgur.com/WDgzcY5.png)

**Comment by AMurkin** [comment]
Still crashes for me.
Clean install, no matter software rendering or not.
Redmi 3, Android 5.1.1.

**Comment by ZhilkinSerg** [comment]
Was it 32 or 64 bit version? Is there a stacktrace?

**Comment by AMurkin** [comment]
32 bit version. No stacktrace.

**Comment by AMurkin** [comment]
0.D-9792 didn't crash with an empty config folder.
And I'm able to load my savegame.
