### ISSUE TITLE
3/4ths of all real guns are heavily underweight.

### ISSUE THREAD

**Issue by Warriorcat49** [CleverRaven/Cataclysm-DDA#34830]
**Is your feature request related to a problem? Please describe.**  
Most firearms do not currently have accurate weights applied to them. While I do not yet have a comprehensive list made up, the theme seems to be ~3/4 of all real, brand-name guns (i.e. not RivTech or homemade) are underweight by ~10-20%, with some being up to half their real-world weight. Some are also overweight, but this is rarer.
While this does not necessarily break the balance of the game, it does completely ruin the balance of firearms with respect to each other, seeing as how weight directly affects aim time, recoil, etc.

**Describe the solution you'd like**  
Accurate weights should eventually be applied to all real firearms, especially the most egregious offenders. *cough cough* 416 *cough*

**Additional context**  
Google Sheets spreadsheet with all real firearms and their current modeled weights/real-world weights.
https://docs.google.com/spreadsheets/d/1amMgy_2Yq13aScDdUp7b8HSUS6mZLT9Ddjxoc9k3ruI/edit?usp=sharing
Please feel free to make comments.
UPDATE: Table now sort-able by percent difference between real and in-game weight, so you can easily see the worst of it.

**Comment by Warriorcat49** [comment]
Volumes are also probably wonky, but that's a lot more subjective to measure seeing as how guns aren't pure rectangles or circles, and manufacturers don't tend to give a concrete volume measurement, so I haven't included that yet.

**Comment by tenmillimaster** [comment]
Ar15's in base game are 20" barreled models as noted in the comments. 

We'd want 16" ones eventually.

Also see #33711, I've been trying to update volumes as I go along bu modelling all the guns as gun shaped-prisms.

Volumes are far from being done.

**Comment by zeggz** [comment]
If you plan on changing weapon volume you should also consider verify that holsters still work as intended since what they can hold is dictate by volume (if i understand things correctly).

**Comment by Warriorcat49** [comment]
> Ar15's in base game are 20" barreled models as noted in the comments.

What comments are you referencing here? I see nothing in-game to imply any specific build for any of these rifles, apart from inferences we can take from their weights, or to ask what the intention was of whoever put them in the game.
![AR-15comparison](https://user-images.githubusercontent.com/56670120/67118714-183f1600-f1ab-11e9-993a-54d9bb202788.png)
(Note I'm using DeadPeople for reference images of the guns, obviously it's not necessarily indicative of what the actual guns should be)

> We'd want 16" ones eventually.

Agreed. I'd argue that the more common AR-15 in-game should be the "standard" M4 carbine-styled ones, with a 16" M4 profile barrel.

> Also see #33711, I've been trying to update volumes as I go along bu modelling all the guns as gun shaped-prisms.

That's actually really great work, I like the systematic approach to it. Hell of a lot of work though.

> If you plan on changing weapon volume you should also consider verify that holsters still work as intended since what they can hold is dictate by volume (if i understand things correctly).

Yeah, that's one of the reasons I decided only to look at weights for now. Also, tenmillimaster seems to have a better grasp of the volume issue currently. #33711

**Comment by tenmillimaster** [comment]
>"This is assumed to be the standard model matching the (currently not in game) M16"

Line 30 in \json\items\gun\223.json

**Comment by Warriorcat49** [comment]
That's fair enough. I will admit that I have not gone digging in any .jsons yet, so I was kind of afraid that it might be some kind of derived value system rather than an empirical one.
And yes, I also am nothing if not a gun pedant, so I first noticed this when I (elatedly) found my first AR-15 and went "Wait, why is it twice as heavy as my 416? Something's not right here..." And the descriptions referencing bad reliability are... misinformed at best, but that's out of the scope of the issue at hand unfortunately.

**Comment by tenmillimaster** [comment]
Now that we have a fouling system, I have an idea of how to rectify the ar's low durability issue.

**Comment by Warriorcat49** [comment]
What's your idea? Also, table has been updated to make it easier to navigate, and references are being added.

**Comment by tenmillimaster** [comment]
Flag based on fouling to drop durability.
