### ISSUE TITLE
Antiseptic overuse

### ISSUE THREAD

**Issue by FunkleBlaze** [CleverRaven/Cataclysm-DDA#34840]
# Describe the bug

Antiseptic bottle can be used even when it contained antiseptic hit 0. Bottle will disappear after leaving game.

# Steps To Reproduce

1. Put bottle with antiseptic on floor.
2. Press 'E' to use it.
3. Repeat step 2 as long as you like.

# Expected behavior

Bottle should be unable to use after available doses hit 0.

# Screenshots

![95ec33f518efcf00552b149b976ea9f8cd926c4f_2_1035x519](https://user-images.githubusercontent.com/56731837/67105005-4c74ff80-f1c8-11e9-9e20-db33e9e35fec.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-8583-g08353e3 [64-bit]
 - Graphics version: Tiles 
 - Mods loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Hydroponics [hydroponics],
    Vehicle Additions Pack [blazemod],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

If you press 'E' when you have antiseptic in inventory then bug will not occur. (same with 'a')

[Oakhill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3744796/Oakhill.zip)

**Comment by FunkleBlaze** [comment]
Also using antiseptic when it is on floor with 'a' will not reproduce this bug.

**Comment by RDru** [comment]
Looks like my fault #34663
