### ISSUE TITLE
Vehicle welding rig doesn't allow using soldering iron for repair

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#34851]
# Describe the bug

Not sure if this should be a feature request rather than bug. The vehicle welding rig requires the welding component kit, which requires a soldering iron. The soldering iron applies to crafting, but can't be used to repair items via examine->use the welding rig. 

# Steps To Reproduce

1. Examine an installed vehicle welding rig.
2. No option to use soldering iron (for example, to repair a gas mask).

# Expected behavior

The vehicle welding rig requires the welding component kit, which requires a soldering iron, which should allow for using the soldering iron as a separate tool, for example for repair.

# Screenshots

# Versions and configuration

- OS: Windows
- OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-8589-g8ab1f9b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Player Mod [Player_Mod],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by JonnieCache** [comment]
I was also confused by this

**Comment by new02DAY** [comment]
Does anyone know if this is something that can be changed in JSON? Or does this require C++ changes?

**Comment by glenmack** [comment]
Relevant issue, should not be closed.

**Comment by EmberDragon** [comment]
Perhaps a related bug.

In the original issue it was noted that soldering irons worked for crafting the welding component kit.

I have three soldering irons that do not allow me to craft the welding component kit. I had to craft a new (fourth) soldering iron, and that soldering iron enabled me to craft the welding component kit.

**Comment by Moxanity** [comment]
Still present in stable.

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Moxanity** [comment]
> 
> 
> Perhaps a related bug.
> 
> In the original issue it was noted that soldering irons worked for crafting the welding component kit.
> 
> I have three soldering irons that do not allow me to craft the welding component kit. I had to craft a new (fourth) soldering iron, and that soldering iron enabled me to craft the welding component kit.

Are you sure those soldering irons were not loaded? Iirc items have to be unloaded to be considered for crafting. It's certainly the case for soldering irons.

**Comment by Moxanity** [comment]
This is ostensibly also present for the firearm repair kit, which takes the soldering iron as a component, and which you'd expect you could solder with.
