### ISSUE TITLE
New World Gen Megastore problem

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#34860]
# Describe the bug

Starting a new world has a circular dependency with megastores.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8643-g3b79f53 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    sees-player icon, -attitude [sees_player_less_attitude]
]

# Additional context

 DEBUG    : JSON contains circular dependency. Discarded 2 objects:
{
    "type": "overmap_terrain",
    "id": "megastore_entrance",
    "copy-from": "megastore_entrance",
    "name": "megastore",
    "sym": "M",
    "color": "i_magenta"
  },{
    "type": "overmap_terrain",
    "id": "megastore",
    "copy-from": "megastore",
    "name": "megastore",
    "sym": "m",
    "color": "i_magenta"
  },

 FUNCTION : void DynamicDataLoader::load_deferred(DynamicDataLoader::deferred_json&)
 FILE     : src/init.cpp
 LINE     : 133

**Comment by danielkwinsor** [comment]
Introduced in build 9778, build 9777 last known working

**Comment by zeggz** [comment]
I can confirm it happen also on old world with the same error message.

**Comment by new02DAY** [comment]
Have the same problem with an old world. @ZhilkinSerg started working on it according to his comment in [#34625](https://github.com/CleverRaven/Cataclysm-DDA/pull/34625#issuecomment-543766609), but it looks like someone will have to take a look at it further.

**Comment by tivec** [comment]
Isn't that circular dependency because of this part though?

> "id": "megastore",
> "copy-from": "megastore",

**Comment by ZhilkinSerg** [comment]
Linked PR is missing savegame migration vode and changes to alt map key mod.

**Comment by RDru** [comment]
The circular dependency warning/bug still occurs on game load. It's at least annoying.

**Comment by ZhilkinSerg** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/pull/34903
