### ISSUE TITLE
Crafting CBM Issue

### ISSUE THREAD

**Issue by Scottvrakis** [CleverRaven/Cataclysm-DDA#34875]
# Describe the bug

For some reason, crafting CBMs don't pass by 4% completed and the action log gives me a message saying "You no longer have a none and can't continue crafting".

# Steps To Reproduce

1. Make a player with the ability and materials to craft CBMs.
2. Attempt to craft any CBM.
3. CBM crafting progress does not increase.

# Expected behavior

I simply expected to be able to craft and use the CBM.
I expect it to happen because that's.. How crafting works? I'm not sure how to explain this bit.

# Screenshots

**If applicable**, add screenshots to help explain your problem.
![CBMBug](https://user-images.githubusercontent.com/49710683/67150346-67a54500-f284-11e9-9f24-ff63dad90a29.png)

# Versions and configuration

 - OS: [Windows 10]
 - Game Version: [0.D-8206-gedf3542]
 - Graphics version: [Tiles]
 - Mods loaded: ["dda",
  "no_npc_food",
  "aftershock",
  "crt_expansion",
  "magiclysm",
  "ArmUpPAUtil",
  "ArmUpSurvEx",
  "craftgp",
  "FIC_Weapons",
  "growable-pots",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "modular_turrets",
  "PK_REBALANCE",
  "Salvaged_Robots",
  "alt_map_key",
  "Cata++",
  "crazy_cataclysm",
  "fast_healing",
  "hydroponics",
  "my_sweet_cataclysm",
  "MMA",
  "zets_hair_extensions",
  "zets_hair_ext_pk_rebalance",
  "more_locations",
  "zets_hair_ext_more_locations",
  "FujiStruct",
  "deoxymod",
  "blazemod",
  "Tanks",
  "Heavy miners",
  "necromancy",
  "DP_XOTTO_INDICATORS",
  "TATTOOMOD",
  "Battery_Overhaul_Legacy_Mode",
  "more_classes_scenarios",
  "manualbionicinstall",
  "safeautodoc",
  "novitamins",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills"]

# Additional context
 N/A

**Comment by Destragon** [comment]
Did you have any broken limbs?

**Comment by Scottvrakis** [comment]
> Did you have any broken limbs?

No.

**Comment by Fris0uman** [comment]
Start a game with max skills
Spawn all the ressources
Get all the tools
Craft CBM
![image](https://user-images.githubusercontent.com/41293484/67637646-dca7f880-f8dc-11e9-975e-cd0f0d792171.png)

No error

**Comment by Scottvrakis** [comment]
> Start a game with max skills
> Spawn all the ressources
> Get all the tools
> Craft CBM
> ![image](https://user-images.githubusercontent.com/41293484/67637646-dca7f880-f8dc-11e9-975e-cd0f0d792171.png)
> 
> No error

I'm not quite sure what's going on then? I've tried everything I can *think* of?

**Comment by Scottvrakis** [comment]
Just tried to craft them again.. It worked? I have no idea what's going on, I guess it fixed itself at some point? Guess I'll close this unless it happens again.
