### ISSUE TITLE
Missile Silos have duplicate floors

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#34872]
# Describe the bug

Several floors are duplicates in the nuclear silo spawn. (Three entrances and one extra floor of missile and launch room)

# Versions and configuration

0.D-8646 on Windows 10

**Comment by Night-Pryanik** [comment]
Could you please describe in details what's the problem?

**Comment by zeggz** [comment]
I was going to make my own report for this problem.

For me the first underground level was a duplicate of the ground level with no way to go deeper. Here is a screenshot, it speek for itself i think: 

![Missible silo](https://user-images.githubusercontent.com/56718791/67150342-99cf9a80-f2b6-11e9-8c12-a39377b2a4cb.jpg)

Maybe a problem with the recent PR made to add enemies to the silo?

**Comment by RDru** [comment]
I encountered this before (1-2 months ago) so it's not recent. I just thought it's just unfinished or something.
