### ISSUE TITLE
NPCs abandon tasks after game reload

### ISSUE THREAD

**Issue by FunkleBlaze** [CleverRaven/Cataclysm-DDA#34874]
# Describe the bug

When you give task to NPC, he will do it until you reload game (quit and load). After this they will follow you as though you didn't tell them to do something.

# Steps To Reproduce

1. Give NPC task to do (tree chopping).
2. Quit game.
3. Load game.
4. NPC should abandon task and start follow you.

# Expected behavior

NPC should do his/her task as long as it isn't finished.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-8583-g08353e3 [64-bit]
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Hydroponics [hydroponics],
    Vehicle Additions Pack [blazemod],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

**Comment by zeggz** [comment]
I agree it's would be great if it worked perfectly like that, but this saved me many time from another bug witch put the npcs in an infinite loop and consequently the game killed them. I've been able to save scum and the fact that they end their activity on reload saved their lives. If the problem you describe has to be fixed, i think that the infinite loop problem has to be fixed first (for my sanity, npc are already really hard to keep alive...).

**Comment by FunkleBlaze** [comment]
Ah, yes, I read about this problem. So this was to prevent from it.

**Comment by davidpwbrown** [comment]
> I agree it's would be great if it worked perfectly like that, but this saved me many time from another bug witch put the npcs in an infinite loop and consequently the game killed them. I've been able to save scum and the fact that they end their activity on reload saved their lives. If the problem you describe has to be fixed, i think that the infinite loop problem has to be fixed first (for my sanity, npc are already really hard to keep alive...).

Are you playing latest experimental, and still encounter infinite looping?

**Comment by zeggz** [comment]
It's been a few version since i've assigned task to my npcs, i'll try  again when i have the occasion and report if it's still the case. I haven't see any PR trying to correct this issue recently, maybe i missed it.
And for additional context this bug only occured if when i re-enter the reality bubble where my npcs are working after i've been away.

**Comment by davidpwbrown** [comment]
Ah yes, reentering the reality bubble, thats a thorny problem I know about, still thinking on solutions.

**Comment by zeggz** [comment]
Ok. One temporary solution to the infinite loop problem could be to break the loop without killing the npc. I don't know if it could be done or not, i'm just thinking out loud.
