### ISSUE TITLE
Heavy Duty Doors and Hatches have high hp compared to Heavy Duty Boards

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#34880]
# Describe the bug

Heavy Duty Doors and Hatches have high HP compared to Heavy Duty Boards

Opaque Heavy Duty Hatch has 1000 HP and 75 resistance to all.
Heavy Duty Board has 450 HP and 75 resistance to all and 80 to cut and stab.

Before PR #32595, they had similar HP, but when resistances were added in that PR, Boards got HP reduced as consequence of the added resistance, but Door and Hatches didn't. I think this was an oversight of the PR, **I also noticed a *lot* of parts got free resistances with no HP reduction, so other parts may need to tweaks too.**

EDIT for added info: For some reason door/hatch is made from heavy duty frame (100kg) and boards from steel plating (13kg), the resistance PR probably based on that to make the HP changes, but still doesn't make any sense to have 100kg doors and just 10kg boards (besides the HP disparity).

# Steps To Reproduce

1. Compare part stats in-game from the UI or from JSON parts definitions

# Expected behavior
Boards should be the best in terms of HP, not Doors and Hatches.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8646-g556b355 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]

**Comment by KurzedMetal** [comment]
Sorry, edit in progress, I submitted by mistake.

**Comment by EkarusRyndren** [comment]
The higher resistances are there to represent them being things with internal structure rather than just a sheet of metal. Smashing/cutting your way through a door at a randomly chosen angle is going to be harder than smashing through just the sheet metal.

**Comment by KurzedMetal** [comment]
I understand why the resistances changed, but not the HP change, now doors and hatches are way more durable than boards.

I've already heard players in discord chat saying "is there any reason why I shouldn't replace all boards with hatches, they have more HP".

I think if the PR halved boards HP, should've halved door and hatches HP too with the same reasoning. I personally haven't reviewed other parts, like rams or roofs or armor, but I wonder if they got their HP balanced properly too.

**Comment by PaulBlay** [comment]
If heavy duty boards weigh a lot less than heavy duty doors / hatches, right? So you don't replace them all because it would make your vehicle too heavy and slow. Or if you don't care about that then do replace them all.

**Comment by EkarusRyndren** [comment]
> I understand why the resistances changed, but not the disparity in HP changes (half hp for some, full hp for others), now doors and hatches are way more durable than boards.
> 
> I've already heard players in discord chat saying "is there any reason why I shouldn't replace all boards with opaque hatches, they have more HP". That was what lead me to find this inconsistency.
> 
> I think if the PR halved boards HP, should've halved door and hatches HP too with the same reasoning. I personally haven't reviewed other parts, like rams or roofs or armor plating, but I wonder if they got their HP balanced properly too.

I can't really argue with that. Check if there are weight differences. The whole armor PR was meant to get cars functioning more like cars and not something you just smack the HP bar until it's gone.

**Comment by KurzedMetal** [comment]
Ok, I just noticed one door/hatch is made from heavy duty frame (100kg) and boards from steel plating (13kg).

Maybe doors should be made out of steel plating and made their hp reduced, or maybe we should have Boards made of heavy duty frame with higher HP.

Does anyone know why they are made from different materials like this?

**Comment by EkarusRyndren** [comment]
...If I remember right it's because car doors were made of frames when the heavy duty ones got added so it carried over.

**Comment by PaulBlay** [comment]
I would suggest recipe changes. Boards would be frame + sheet metal, doors would be frame + sheet metal (if opaque) or frame + sheet glass (if see through). Heavy duty doors, heavy duty boards would be heavy duty frame + steel plating, heavy duty doors the same or with reinforced glass if see through.
