### ISSUE TITLE
Vehicles Rework

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#34885]
**Is your feature request related to a problem? Please describe.**  
This will probably relate to half a dozen things so bare with me here. I've got a handful of ideas on how to handle rebalancing vehicles primarily without adding additional parts because frankly, that won't do anything beyond make vehicles more tedious and less fun.

**Describe the solution you'd like**  
First of all, maintenance. Using the existing faults (along with potentially adding a handful of others) engines will develop faults over time. Ideally, you'd see a system of using less than ideal fuels (Lamp Oil in Gas Turbine Engines for example) screwing up engines faster. A simple "The Check Engine light comes on, The Check Engine light starts blinking, The Check Engine light blinks faster while beeping" notification as the engine gets worse will do for notifying the player the vehicle needs some care. This will also give the player a reason to secure those assorted engine parts found lying around. As for additional faults, leaky gas pump leading to dumping however much the engine uses on the ground when turning off the engine, faulty sensors leading to increased consumption, dead computer leading to increased consumption but needing electronics or computers to repair rather than mechanics, and so on.
Second, Faulty tires. This may be a bit more difficult to implement but still worth doing. You're looking at Flat, Slow Leak, Old, and Bare. Flat will decrease vehicle handling and ideally eventually break off or damage the hub (If that's possible/easy enough to do.) Slow Leak will do the same but without the damage to the hub (Or potentially the tire in exchange eventually developing into "flat") Old will also decrease handling as well as reduce the "HP" of the tire by an appropriate amount (Ideally half) to represent dry-rot and more importantly just be all tires after a certain period of time in-game. (Not sure how long it takes for tires to go bad IRL but you get the idea.), and bare tires will simply reduce handling of the vehicle.
Third, and this one pains me personally, weight limits per frame. It's assumed (as I understand it) that various things are handwaved with vehicles, EG drive shafts and so on. Each type of frame should be capable of supporting a predefined amount of weight. So you can't stick 60 tons of weight on a light frame. Sure, this'll result in the larger vehicles using nothing but Heavy Duty Frames, but it's a step that's already done for the most part and the people who aren't are generally gaming the system or just don't know.
Fourth, quality of life. Crafting, storage, and sleeping in vehicles at the moment is STRONGLY in favor of the player. This mainly occurred to me while watching Forged In Fire and noticing the sheer amount of space needed to craft a Nodachi. This could also be applied to non-vehicle crafting but a "Space" requirement for crafting could go a long way towards forcing players to build a proper base (Mobile or otherwise) for crafting reasons. As for storage, I'm going to recommend a rather major change: mobility issues. A single tile can only hold so much stuff, as that tile fills it should be harder to move through and eventually become impassable and potentially something you can't see through. You'd be looking at tree tiers of difficulty then impassable and finally can't be seen through representing a completely full tile. This would defeat loot piles in both mobile and immobile bases but would also require a massive amount of reworking (presumably) as crafting currently does not path through impassable tiles regardless of it being a corner or something similar.
Next, Sleep. Sleeping in a vehicle currently is kind of wonky. A car seat isn't much more comfortable than a regular bed, this is a load of crap frankly. Having slept in a car seat myself  I can say that while yes, it's easy enough to fall asleep in a reclining car seat you wake up cramped and cranky. I'd suggest we also apply that to anyone sleeping in a car seat. A mild morale penalty, some mild pain upon waking, and maybe, maybe a stats penalty. Furthermore, I'd recommend we change the "sleeping" code (if that's a thing) so that if you're trying to sleep on a bed with less than 2 tiles there are cramping and falling asleep penalties to represent trying to sleep on too small a bed. Players who are smaller (mouse mutation tree) or larger (Beast and such) obviously requiring smaller/larger beds to get comfortable sleep.
Space is another issue in general. A fairly common build is to just stuff an APC with cargo spaces. While my earlier tile changes cover this to a degree I felt it worth mentioning nonetheless. I recommend we make it so that if the player doesn't move through, or stay in "comfortable" tiles in vehicles (Asiles, seats, etc) they start building up an invisible "cramp" stat. Eventually leading to the assorted problems with being a big mutant stuffed into a car.
Seventh, everything I mentioned in #34707 a quick recap; Quarter Panels are currently being used as stronger, lighter windows and that's just not what they are.
Eighth, the elephant in the room, shifting items. It's been argued in the past items should fall out of vehicles if they aren't secured. I'm torn on this issue. Logically, it's definitely a thing, mechanically it'd be a pain. If we're going to go through with it I'd recommend several high capacity storage options even if they require a closing option (Eg a weapons locker you have to manually "close" after you're done with it.) However, I'd recommend just for tedium's sake, we not make items fall from the non-contained storage options.
Next up, Fuel consumption. I'm not sure how engines work now, but for a lot of this to work I'd recommend fuel usage (and engine falting) depend on how much weight is trying to be moved by an engine. A Twin V engine is gonna have a harder time moving a motorcycle than a V12. Simple and forward. If this is already in the game then it may need some adjustment as loading one of my mega-trucks with several tons of gear doesn't seem to affect it at all.
Tenth Point, Solar Power. Solar power is a bit of a bitch to deal with in CDDA and I'm frankly not all that sure how the hell to deal with it. As it stands they're more than a little OP. Electric Vehicles have it a bit too easy. I'm not sure if that's due to realism or bad code. However, I'm gonna recommend battery faulting too regardless. However, I'm not sure battery faults can be fixed. So I'm gonna recommend Old (It's been recharged a "bajillion" times and as such has lost some of its charge), and finally splintered cells which'll decrease max capacity and have a **_SMALL_** chance of exploding. Ideally, these faults will increase with game time.
Skylights are something that could also be nice. Basically, a glass roof. Not too complex but worth mentioning nonetheless.
Lastly, some buffs. I'm gonna recommend some bathtub/shower, sink, toilet, etc tiles for vehicles that'd simply add buffs (for now.) Just some morale boosts and so on, nothing serious,

**Additional context**  
I hammered all of this out because as it stands most of the changes suggested for vehicles involve adding extra parts which, frankly, aren't that hard to get (such as drive shafts) and would just mean finding more parts rather than anything that adds extra challenge/reward. Beyond that, the main reason mobile bases beat static bases by a long-shot is that mobile bases _can move_. Since the world is infinite, there is no reason to remain static but there isn't much I can recommend to fix that, except one thing:

One of the NPCs in the Refugee Center mentions a "Wall of Zeds" after a distance that can "stop a tank" and all I can think of is a region that's just **_FULL_** of zombies to the point that the mega-ist of mega vehicles is stopped by them. However, that'd also effect non-vehicle players. So, consider at your discretion.

**Comment by ZhilkinSerg** [comment]
Ideas are neat, but it would not move anywhere until you start implementing them. Try decomposing to smaller tasks and fulfill them.

**Comment by EkarusRyndren** [comment]
A lot of this is probably code stuff and I know zero about C++. Plus this was kinda dreamed up as a drunken fever dream. I posted the whole thing here mainly in the hopes someone else could/would do it but also as a "don't forget it" kind deal.

**Comment by mlangsdorf** [comment]
Vehicle fuel consumption per second is the amount of fuel necessary to produce the required energy to move the vehicle that second.
required energy is engine power / engine thermal efficiency * strain
strain is current acceleration to maintain cruise speed (or specified acceleration) / available acceleration at current speed.
maintenance acceleration is -drag slowdown.
drag slowdown is vehicle specific drag coefficient * air density / * square of current velocity + mass * vehicle specific rolling resistance value + constant.
available acceleration is proportional to maximum speed / current speed (for complicated reasons involving gearing assumptions).

Long, long story short:
CDDA vehicles consume more fuel as you load them more heavily, but it's a complicated non-linear relation.  Also, most CDDA vehicles are driven at around 30-50 mph, and modern  gasoline engines can reasonably expect to run for 6-10 from a 60L tank at those speeds.

The rest of this proposal seems like pointless busywork that I'm not interested in implementing but someone else can.

My preferred solution for balancing vehicles is to increase the cost of welding, by requiring flux rods, scrap metal patches, and 90 battery charges per minute of welding work.

**Comment by kevingranade** [comment]
Faults - my plan for this was to enumerate engine sub-components that can break, a "malfunctioning X" fault can be mended by consuming the related component (fuel pump, water pump, radiator, etc), which you can harvest from similar engines by inflicting a "no X" fault on them.

Tire damage - this should particularly happen based on running over various hard items and obstacles.

Weight limits - this is something I've meant to add for years but haven't gotten around to it.  Also this might drive increasing weight for some of these frames (which of course makes things compound).

Crafting - I'm not sure how this turns into something actionable, does the crafting recipe just require X open spaces as a requirement?

Sleeping - I agree that sleeping in a driver seat should get nerfed, but I don't expect this to have much impact on mega vehicles as it's just some extra space.

Storage - one idea I had for this is that only the "top" X volume of items is visible and accessable in a given tile, which is tunable per tile type.  Pickup and advanced inventory would enumerate and allow access to additional items at an additional time cost, but crafting would not. I'm on board with the map-impacting aspects you suggest as well.

Cramped spaces - I think this is a valid but minor thing to add, but I'd go a step further and state that there are no such comfortable vehicle tiles right now, even most RVs don't allow an average height person to stand straight. A full height tile would require some exceptional measures to render them fully comfortable.

Item storage vs securing items - we should just audit storage spaces with the understanding that all vehicle storage is spending some volume on securing its contents, I suspect we are being far too generous with storage capacity right now.

We can re-examine the MPG to weight ratio of vehicles, but I suspect a major driver of this is that vehicles are simply far lighter than they should be, and that driving distances are unnaturally short.  Im not going to touch on the first issue again. There are two options I can see for the distance problem. Now that we have auto-drive, we can adjust mapgen to make distances more rational. Alternately we can manually compensate for this unnatural distance by dropping MPG based on the difference between in game distances and re as l world distances.

Solar is going to get fixed by real-world power consumption for various tasks. Movement is vastly under-charged as outlined above, welding is crazy cheap, etc.

Point of order for issues, for these to stick around, they need to either turn into a project, or a series of issues.

**Comment by ANickelN** [comment]
I think increasing the distances between locations would make much more sense than trying to tweak how heavy vehicles are.  Plus, increasing the distances would also buff cars in a way, as travelling on foot or mounted would take much more time.

**Comment by Night-Pryanik** [comment]
Cars are already way, way too overpowered, they don't need additional buffs.

**Comment by ANickelN** [comment]
I don't see how making the distances between locations more realistic would be considered a bad thing @Night-Pryanik.  Sure, it would make cars more important if you want to travel really long distances in a short amount of time.  I should not be able to walk to a neighboring town in something ridiculous like five or ten minutes.

**Comment by Night-Pryanik** [comment]
> I don't see how making the distances between locations more realistic would be considered a bad thing 

I didn't say anything about distances between locations.

**Comment by kevingranade** [comment]
If someone wants these ideas to turn into issues, they need to incorporate them into a series of issues and/or a project, omnibus issues like this are not workable.
