### ISSUE TITLE
Make the Shark Suit craftable

### ISSUE THREAD

**Issue by WormGrill** [CleverRaven/Cataclysm-DDA#34898]
**Is your feature request related to a problem? Please describe.**  
The shark suit is the only component available to make the Faraday shark suit, which seems like it'd be great for fighting against shocker zombies as it protects against electric discharge. However, it's only spawn is in a pawnshop, which is somewhat rare and even if you find one it's really unlikely to have it show up in there considering how much stuff can spawn in a pawn shop. The shark suit itself doesn't seem to be too complex to make it unfeasible for a survivor to craft it themselves, given a high enough skill level.

**Describe the solution you'd like**  
Make it possible to craft the shark suit, give it a suitably high tailoring level, and maybe have the recipe locked behind swimming or tailoring books, like the Water Survival Manual or the Clothing Designer's portfolio. The shark suit itself is described as a chainmail suit atop a wetsuit with hood, gloves, and boots, and looking online it seems like that's pretty accurate. It could be crafted with a full chainmail suit, wetsuit hood, wetsuit, pair of swimming gloves, and pair of swimming booties. Maybe a few extra chainlinks and chainmail sheets to accommodate the glove and feet portion of the suit, which currently do not have chainmail items associated with them.

**Describe alternatives you've considered**  
Leave the shark suit uncraftable, or make the Faraday shark suit directly craftable from the proposed components I listed above. Also maybe make the primary skill fabrication instead of tailoring, as that's what chainmail uses to make it, and make tailoring a secondary skill.

Alternatively, make it possible to make just a regular Faraday suit from a full set of chainmail armor, instead of tagging it on to the shark suit, unless there's some quality that the shark suit itself provides for dissipating electric charge. Although the lack of chainmail gloves/boots may make a full faraday suit a problem, so make chainmail gloves/boots as well or add extra chain links/sheets to the crafting recipe to substitute for that in place of adding in those new items.

**Additional context**  
[https://www.hammacher.com/product/chainmail-sharkproof-suit](url) Here's a store listing for a chainmail shark suit, complete with pictures to get an idea of what a shark suit would look like and the skill level required to craft it.

**Comment by kevingranade** [comment]
Your source doesn't give any indication of what materials, tools or skill are required to construct one of these. There's a reason it's not craftable, no one has presenting a source indicating how feasible it is.

**Comment by WormGrill** [comment]
I found these sources, a Smithsonian article and associated patent on an armored shark suit, which I believe the one in-game is actually based off of. The patent abstract is "A suit is provided having a flexible garment portion which mounts thereon, preferably at spaced intervals, a plurality of armor elements. The suit can be incorporated with a conventional wetsuit construction, or the armor can be imbedded in a chain mail garment worn exteriorly of a wetsuit." (1)

And here's a paragraph from the article detailing it as well:
"Sullivan’s wetsuit is made of chainmail or steel mesh. Plates made of tough plastic material are embedded into the suit in spots away from joints, to preserve the wearer’s mobility. The complete suit resembles a “tough, hard, lobster-like exterior shell.” The steel mesh deters curious sharks from biting down, and prevents, to an extent, their razor-sharp teeth from cutting into the wearer’s flesh if they do." (2)

The patent goes into some detail on it's construction, which includes hard plastic being melted and formed into plates atop and within the chainmail suit, which itself is placed on the wetsuit. Adding in a plastic mold, soldering iron or heat source, and some plastic chunks to my proposed recipe would fit, no? And does the patent go into enough detail to adequately approximate the skill level/tools/components need to craft this in-game?

(1): https://patents.google.com/patent/US4356569
(2): https://www.smithsonianmag.com/arts-culture/chainmail-metal-spikes-and-unbreakable-material-can-we-design-a-shark-proof-wetsuit-27310741/

**Comment by kevingranade** [comment]
The patent goes into enough detail to tell me that this is definitely not survivor craftable.
