### ISSUE TITLE
Internal Furnace CBM crash the game

### ISSUE THREAD

**Issue by zeggz** [CleverRaven/Cataclysm-DDA#34893]
# Describe the bug

CRASH LOG FILE: config/crash.log
VERSION: 0.D-8668-gf7c73e0
TYPE: Signal
MESSAGE: SIGFPE: Arithmetical error
STACK TRACE:
    @0x5C2255[cataclysm-tiles.exe+0x1C2255]
    @0x5C2D22[cataclysm-tiles.exe+0x1C2D22]
    SMPEG_error+0x4B0B1@0xFA15DD[cataclysm-tiles.exe+0xBA15DD]
    _C_specific_handler+0x9C@0x77587958[ntdll.dll+0x17958]
    RtlDecodePointer+0xAD@0x7759812D[ntdll.dll+0x2812D]
    RtlUnwindEx+0xBBF@0x7758855F[ntdll.dll+0x1855F]
    KiUserExceptionDispatcher+0x2E@0x775BBCB8[ntdll.dll+0x4BCB8]
    IMG_LoadWEBP_RW+0x4093D5@0x149C7A5[cataclysm-tiles.exe+0x109C7A5]
    @0x784CE9[cataclysm-tiles.exe+0x384CE9]
    @0x786242[cataclysm-tiles.exe+0x386242]
    @0x792AA7[cataclysm-tiles.exe+0x392AA7]
    @0x794CDE[cataclysm-tiles.exe+0x394CDE]
    @0x795E78[cataclysm-tiles.exe+0x395E78]
    @0x7961C3[cataclysm-tiles.exe+0x3961C3]
    @0x7962EE[cataclysm-tiles.exe+0x3962EE]
    @0x796388[cataclysm-tiles.exe+0x396388]
    IMG_LoadWEBP_RW+0x405271@0x1498641[cataclysm-tiles.exe+0x1098641]
    @0xEC3C4F[cataclysm-tiles.exe+0xAC3C4F]
    IMG_LoadWEBP_RW+0x312139@0x13A5509[cataclysm-tiles.exe+0xFA5509]
    @0x79754D[cataclysm-tiles.exe+0x39754D]
    @0x702F3E[cataclysm-tiles.exe+0x302F3E]
    @0x70921B[cataclysm-tiles.exe+0x30921B]
    @0x6CEDB5[cataclysm-tiles.exe+0x2CEDB5]
    @0x71AEC6[cataclysm-tiles.exe+0x31AEC6]
    @0x6F9F2D[cataclysm-tiles.exe+0x2F9F2D]
    IMG_LoadWEBP_RW+0x613228@0x16A65F8[cataclysm-tiles.exe+0x12A65F8]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0xD@0x774659CD[kernel32.dll+0x159CD]
    RtlUserThreadStart+0x21@0x7759A561[ntdll.dll+0x2A561]

# Steps To Reproduce

Activate Internal Furnace and press "E".

# Expected behavior

Not to crash the game. :-)

# Screenshots

![internal furnace](https://user-images.githubusercontent.com/56718791/67159849-6b030400-f34a-11e9-9a17-da8a36d47f41.jpg)

# Versions and configuration

VERSION: 0.D-8668-gf7c73e0
Windows 7

# Additional context

I guess it's related to the changes in bionic power and calculation of the power attached to consuming item.

**Comment by LaVeyanFiend** [comment]
Confirmed:

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8700-g7787bc0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Mythological Replicas [nw_pack]
]
Crash log:

CRASH LOG FILE: config/crash.log
VERSION: 0.D-8700-g7787bc0
TYPE: Signal
MESSAGE: SIGFPE: Arithmetical error
STACK TRACE:
    @0x5C2C75[cataclysm-tiles.exe+0x1C2C75]
    @0x5C3742[cataclysm-tiles.exe+0x1C3742]
    SMPEG_error+0x4B0B1@0xFA21DD[cataclysm-tiles.exe+0xBA21DD]
    _C_specific_handler+0x98@0x7FFBE8338048[msvcrt.dll+0x28048]
    _chkstk+0x11F@0x7FFBE97811FF[ntdll.dll+0xA11FF]
    RtlRaiseException+0x399@0x7FFBE974A289[ntdll.dll+0x6A289]
    KiUserExceptionDispatcher+0x2E@0x7FFBE977FE6E[ntdll.dll+0x9FE6E]
    IMG_LoadWEBP_RW+0x406275@0x149A245[cataclysm-tiles.exe+0x109A245]
    @0x785A99[cataclysm-tiles.exe+0x385A99]
    @0x786FF2[cataclysm-tiles.exe+0x386FF2]
    @0x793857[cataclysm-tiles.exe+0x393857]
    @0x795A8E[cataclysm-tiles.exe+0x395A8E]
    @0x796C28[cataclysm-tiles.exe+0x396C28]
    @0x796F73[cataclysm-tiles.exe+0x396F73]
    @0x79709E[cataclysm-tiles.exe+0x39709E]
    @0x797138[cataclysm-tiles.exe+0x397138]
    IMG_LoadWEBP_RW+0x402111@0x14960E1[cataclysm-tiles.exe+0x10960E1]
    @0xEC489F[cataclysm-tiles.exe+0xAC489F]
    IMG_LoadWEBP_RW+0x30EF79@0x13A2F49[cataclysm-tiles.exe+0xFA2F49]
    @0x7982FD[cataclysm-tiles.exe+0x3982FD]
    @0x703DDE[cataclysm-tiles.exe+0x303DDE]
    @0x70A0BB[cataclysm-tiles.exe+0x30A0BB]
    @0x6CFA85[cataclysm-tiles.exe+0x2CFA85]
    @0x71BC76[cataclysm-tiles.exe+0x31BC76]
    @0x6FABDD[cataclysm-tiles.exe+0x2FABDD]
    IMG_LoadWEBP_RW+0x610738@0x16A4708[cataclysm-tiles.exe+0x12A4708]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFBE83C7BD4[KERNEL32.DLL+0x17BD4]
    RtlUserThreadStart+0x21@0x7FFBE974CED1[ntdll.dll+0x6CED1]
