### ISSUE TITLE
M202A1 TALON UGVs immediately destroy military outposts.

### ISSUE THREAD

**Issue by Xion350** [CleverRaven/Cataclysm-DDA#34912]
# Describe the bug

These UGVs are loaded with incendiary rockets and shoot the zombies within the outposts, which in turn destroys the outposts, and the loot.

# Expected behavior

They should either not be in outposts at all, or spawn in a place where they won't immediately destroy everything.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-8668-gf7c73e0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Icecoon's Arsenal [ew_pack],
    Alternative Map Key [alt_map_key],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    Prevent Zombie Revivication [no_reviving_zombies],
    Sleep Deprivation [sleepdeprivation],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Mutation Changes [Mutation_Changes]
]

**Comment by RickyVanz** [comment]
talk about firepower overdose for them UGV's.. :rofl:
