### ISSUE TITLE
RM42 fighting knife is made out of an unrealistic material for a combat knife.

### ISSUE THREAD

**Issue by Relyksboa** [CleverRaven/Cataclysm-DDA#34913]
**Is your feature request related to a problem? Please describe.**  
Ceramic as a material is not suitable for a combat knife, as it is too brittle to put a dishwasher, let alone the rib cage of whatever animal you stab.

**Describe the solution you'd like**  
Change the material to something tougher such as super alloy or steel.

**Describe alternatives you've considered**  
Rather than changing the material, you could change the toughness from well made to flimsy as it would more accurately reflect the material.

**Additional context**  
Ceramic knives should stay in the kitchen, as they are more suited for that job.

**Comment by Night-Pryanik** [comment]
There are different types of ceramic, you know. I bet RM42's ceramic is not the same you found in a common kitchen knife.

**Comment by Relyksboa** [comment]
Yes, but ceramic is not used for combat knives. It just isn't. Super alloy makes more sense as Bionic claws (which does 16 stab damage) currently uses it.
