### ISSUE TITLE
Mi-go structures temperature too high for NPCs to live 

### ISSUE THREAD

**Issue by xnmh** [CleverRaven/Cataclysm-DDA#34914]
# Describe the bug

Contrary to #32055 which mentions the temperature to be around 56C, the actual temperature is usually in the low 100s

The NPCs inside should be dead due to the resin cages being unable to protect them from the heat & poison gas since according to its description it lets air through

# Steps To Reproduce

1. Make a player and teleport to a mi-go building
2. Wait around 2 minutes then spawn a thermometer or divers watch
3. Activate thermometer or divers watch to see the high temperature

# Expected behavior

The temperature would be at around 56C & the NPCs would be in some kind of containment
which prevents the heat and poison gas from going through unlike the current resin cages which
probably would let it through due to being able to let air through

Ideally also describe *why* you expect it to happen

The mi-go would not want their test subjects to die to the environment before they finish their testing or whatever reason they keep them alive in there
(Or maybe they want them to die to the environment? In which case they should be long dead to the gas and heat)

# Screenshots

![cddami-gotemp](https://user-images.githubusercontent.com/56813369/67178282-aeba4400-f404-11e9-9741-f4fe36bdbcee.PNG)

# Versions and configuration

 - OS: Windows
 - Game Version: 0.D-8668-gf7c73e0 [32-bit]
 - Graphics version: Tiles
 - Mods loaded: [dda], [growable-pots], [national_guard_camp]

# Additional context

None

**Comment by Xion350** [comment]
I don't have a lot of experience with the mapgen stuff, what exactly IS causing them to be so hot?  From what I can tell there's not a specific way to control temperature.  It's controlled mostly through the heat vents right?

**Comment by MrOlaf** [comment]
the heating "bulbs" seem to be causing the area to overheat. Based on Wikipedia "The minimum temperature that can cause a burn in a finite amount of time is 44 °C (111 °F) for exposure times exceeding 6 hours. From 44° to 51 °C (111° to 124 °F), the rate of burn approximately doubles with each degree risen. The burn would develop in less than a second if the exposure temperature is at least 70 °C (160 °F)." So the heat damage formula or the area need to be adjusted as being exposed 56C is not enough to cause burns in such a short amount of time.
