### ISSUE TITLE
Game crash when setting pulse laser turret to automatic targeting mode. 

### ISSUE THREAD

**Issue by GroeneAppel** [CleverRaven/Cataclysm-DDA#34923]
# Describe the bug

The game produces a crash when attempting to set a pulse laser turret to automatic targeting mode after installing a turret control unit. The game does not produce a crash however when attempting to do the same with a mounted A7 laser rifle.

Oddly when setting up a new world with the same mods and attempting to replicate the error, no crash occured. 

# Steps To Reproduce

1. Add a yet another turret mount to your deathmobile.
2. Install one of those fancy pulse lasers as a turret. (either manual or automated)
3. Add a turret control unit to your turret.
4. Try to set the pulse laser turret to automatic and watch the sky fall down as your game crashes. 
5. Notice that doing the same to your mounted A7 laser rifle doesn't cause any crashes.

# Expected behavior

To be able to enable my pulse laser to automaticly shoot any pests around my mobile fort without crashes. 

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-8700-g7787bc0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Roadheader and other mining vehicles [Heavy miners]

# Additional context
I've attached two savefiles to google drive. One which is the actual save where the crash occurs, and another where I attempt to replicate the crash but can't. Please take note that my save file is rather large, at 300mb+. 

[Crash and Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3752701/Crash.and.Debug.zip)

https://drive.google.com/open?id=12nWJzR6AWSeDHOpkBPPsmo6CbJR6_Cdb

**Comment by zeggz** [comment]
Was it on a new wolrd or an existing one?
This seems liked to this : #34831
To quote myself :
> There is definitively a weird problem with this new part wich is difficult to reproduce due to it's inconsistency. Maybe it's affecting only old saves, but maybe it could have unforceenable consequences in the future.

**Comment by GroeneAppel** [comment]
@zeggz 
It was on my current save a bunch of builds ago. 

I think i've just found the culprit, uninstalling the 5-point harness prevents the crash from occuring and lets me properly set the pulse laser to automatic. Removing the other parts has no effect on the crash. Re-installing the 5-point harness let's me produce a crash again when switching mode.

**Comment by zeggz** [comment]
Hope it works for you but i have serious doubt it will. As i said it's really inconsistent and sometime it work sometime it crash your game. In my game have harness installed on all seat in my vehicule and i've been able to make it work until it doeen't without touuching them. Other reports are with different configuration too. So for now, i just hope thant someone will look into that to find a solution.

**Comment by Night-Pryanik** [comment]
Closing as duplicate.
