### ISSUE TITLE
Wayfarer and mounting animals

### ISSUE THREAD

**Issue by Pancake11113** [CleverRaven/Cataclysm-DDA#34922]
# Describe the bug

Survivors with the wayfarer trait can mount animals but attempting to dismount returns the message, "You refuse to take control of this vehicle."

# Steps To Reproduce

1. Give survivor the wayfarer trait
2. Mount horse or cow
3. Attempt to dismount with "^" which returns the message, "You refuse to take control of this vehicle."

# Expected behavior

Either a wayfarer should not be able to mount animals or they should be able to dismount them normally

# Screenshots
![Screenshot (100)](https://user-images.githubusercontent.com/56843373/67231798-07420f00-f40e-11e9-82ce-e0e7084ca875.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-8700-g7787bc0
 - Graphics version: Tiles
 - Mods loaded: [
  "dda",
  "no_npc_food",
  "aftershock",
  "crt_expansion",
  "magiclysm",
  "Nechronica_Redux",
  "Cata++",
  "craftgp",
  "FIC_Weapons",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "modular_turrets",
  "Salvaged_Robots",
  "secronom",
  "alt_map_key",
  "hydroponics",
  "mutant_npcs",
  "MMA",
  "vamp_stuff",
  "Arcana",
  "national_guard_camp",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "deoxymod",
  "blazemod",
  "Tanks",
  "vamp_stuff+arcana",
  "necromancy",
  "jury_rigged_robots",
  "novitamins",
  "StatsThroughSkills",
  "speedydex",
  "safeautodoc",
  "manualbionicinstall",
  "no_reviving_zombies",
  "more_classes_scenarios",
  "RL_Classes"
]

# Additional context

none

**Comment by Fris0uman** [comment]
From what I understand: the way Wayfarer is implemented it disable the `^` ( or whatever is bind to control vehicle)

**Comment by kevingranade** [comment]
In other words it either needs an override for ^ for just dismounting, or it needs to also disable the mount action.
