### ISSUE TITLE
Text wrapping bug in the sidebar

### ISSUE THREAD

**Issue by adinsx** [CleverRaven/Cataclysm-DDA#34928]
# Describe the bug

In ncurses mode (I am unable to test Tiles) and with the "labels" or "labels-narrow" sidebar, if the item you are wielding has too long of a name it wraps over the next line.

With the classic sidebar, the fighting style overwrites parts of the item name in an awkward way (see screenshots below).

# Steps To Reproduce

1. Wield an item with a long name
2. Make sure your sidebar has the "Weapon" entry enabled.
3. It seems to be independent of font size.

# Expected behavior

One would expect the name of the item to either be truncated, or for a additional line to be added for extra-long names. Dynamically sized sidebar entries might not be easily implemented though, so the former would likely be easiest. The current behavior is unexpected because it could potentially completely obscure the fighting style information.

# Screenshots

With labels:
![image](https://user-images.githubusercontent.com/2461780/67250609-e931da00-f420-11e9-9513-e044c450f6b5.png)

With classic:
![image](https://user-images.githubusercontent.com/2461780/67250724-57769c80-f421-11e9-9c23-5e288a70d493.png)

# Versions and configuration

 - OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux bullseye/sid; Release: unstable; Codename: sid; (Last updated 2019-10-21)
- Game Version: 0.D-8681-g7787bc041a [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Might be related to, or even caused by the same underlying issue as, #27279.

**Comment by Briack** [comment]
I just replicated this in Windows as well.
- OS: Windows 10 Home (Version 1903, build 18362.592)
- Game: 0.D-12140-g92a81b5 [64-bit]

**Comment by BrettDong** [comment]
Is this bug still present in the latest experimental?

**Comment by BrettDong** [comment]
Cannot reproduce.
