### ISSUE TITLE
Would like a constructable single tile mono/train track

### ISSUE THREAD

**Issue by TJKing293** [CleverRaven/Cataclysm-DDA#34921]
per tile

Materials:  1 plank, 2 spikes and 1 pipe

tools:  hammer, arc welder, shovel

skills:   fabrication 3

time: 1 hours

**Comment by curstwist** [comment]
Why do you want it? Wouldnt at least 3 tiles wide be better? I do think current tracks are very wide.

Not sure variable track with would work well. 

Finally, couldn't you build a vehicle that only needs one of the two existing rails instead?

**Comment by kevingranade** [comment]
I'm not sure what you're planning on running on top of this rail, but the requirements for even light rail are much higher than what you're outlining.

If you're talking a mine cart style thing, you can probably get away with just two rails, a half dozen boards and a dozen spikes, but anything vehicle sized is going to need ground prep on top of that
