### ISSUE TITLE
Cutting a Tree Creates Ledges 

### ISSUE THREAD

**Issue by TheGoatGod** [CleverRaven/Cataclysm-DDA#34940]
self explanatory cutting down a tree creates ledges, i loaded my old save that i know didnt happen on its still existed 
![ledge](https://user-images.githubusercontent.com/56883303/67300420-d33a1d00-f4e5-11e9-87cd-53288f2767d6.png)

**Comment by PaulBlay** [comment]
This is probably related to the known bug that falling trees damage underground levels if you have experimental z-levels on. There must have been a cave or basement under there and you destroyed the ceiling.

**Comment by danielkwinsor** [comment]
I recently encountered this too, on a map where I had chopped nearby trees.  I updated to a newer version (build 9794), and I had this happen too.  Got an older save, reverted back to 9793, and did not have this problem.  I believe it's due to #34866

**Comment by TheGoatGod** [comment]
yeah the bug is in the update i dont get ledges in build 9793

**Comment by PaulBlay** [comment]
Maybe it's not actually a bug, then. Or the only bug is that the use of the word 'ledge' is confusing.

You just chopped down a tree right on top of an underground lab (or whatever) and now you have a new entrance. Provided you don't mind breaking a leg while climbing down.

**Comment by snipercup** [comment]
Then it should only create ledges if there is some room underground? Can anyone confirm if no ledges are created if there is only solid ground below?

**Comment by WormGrill** [comment]
I'm pretty sure ledges are still created even if there's just solid ground underneath, unless I just happened to chop down a tree right on top of two random empty spaces in solid rock.
![Delphine Barnhart __15-34-53_Eastern Standard Time](https://user-images.githubusercontent.com/56553016/67410022-73954d80-f589-11e9-968e-4ca5d89d8e37.png)
![Delphine Barnhart __15-35-06_Eastern Standard Time](https://user-images.githubusercontent.com/56553016/67410024-73954d80-f589-11e9-8f27-a63117699af0.png)

**Comment by PaulBlay** [comment]
So it is still a bug. 

Could you check down further levels? It would be interesting to know if it still happens if it is solid rock all the way down (10 levels).

I think this is still probably 
https://github.com/CleverRaven/Cataclysm-DDA/issues/14117
only showing in a different way now that the code for handling damage and collapses has changed a bit.

**Comment by TheGoatGod** [comment]
I tryed it away from there im not on my pc atm but it does the same thing
and thats an evac shelter im at i just spawned,

**Comment by danielkwinsor** [comment]
In the times when I jumped down the ledge, I was basically encased in rock.  I know of no underground lab anywhere nearby.

Here's another way of thinking of it: the tree is already there, along with all it's associated weight and strain.  Is it really so realistic that chopping down a tree breaks the ground through to some pre-existing underground spots?

**Comment by PaulBlay** [comment]
It's not just cutting down trees. Holes in the ground are formed when you blow up trees or walls with stray heavy rail rifle shots. It also happens when there is solid rock all the way down.

**Comment by DMFan79** [comment]
While we wait for the fix, is there a way to cover the holes?
