### ISSUE TITLE
Crash when crossing overworld tiles.

### ISSUE THREAD

**Issue by DatMeg** [CleverRaven/Cataclysm-DDA#34944]
# Describe the bug
Infrequent, but semi-repeatable crash when traversing the world. Unsure of the specific cause, but it seems more readily reproducible in urban areas. I have tested without mods on a new save as well, and was able to reproduce the crash, though not reliably.

# Steps To Reproduce

1. Make a player. A new save, which reproduced the bug, was the LMOE Sheltered start
2. Find a city?
3. Try to pass between overmap tiles.

# Expected behavior

The game shouldn't hard crash just for moving around

# Screenshots
Trying to cross Northeast from this tile seems to reproduce the crash semi-reliably (see included save file).
![cddacrashA](https://user-images.githubusercontent.com/17204395/67310686-3e76f580-f4cc-11e9-86a9-0dbe07621f53.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8720-gf7e743c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Craftable Gun Pack [craftgp],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Crazy Cataclysm [crazy_cataclysm],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Fuji's More Buildings [FujiStruct],
    Beta National Guard Camp [national_guard_camp],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]
# Additional context

CRASH LOG FILE: config/crash.log
VERSION: 0.D-8720-gf7e743c
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5C49D5[cataclysm-tiles.exe+0x1C49D5]
    @0x5C54A2[cataclysm-tiles.exe+0x1C54A2]
    SMPEG_error+0x4B034@0xFA4D30[cataclysm-tiles.exe+0xBA4D30]
    _C_specific_handler+0x98@0x7FFDDFF18048[msvcrt.dll+0x28048]
    _chkstk+0x11F@0x7FFDE05411FF[ntdll.dll+0xA11FF]
    RtlRaiseException+0x399@0x7FFDE050A289[ntdll.dll+0x6A289]
    KiUserExceptionDispatcher+0x2E@0x7FFDE053FE6E[ntdll.dll+0x9FE6E]
    IMG_LoadWEBP_RW+0x361491@0x13F8031[cataclysm-tiles.exe+0xFF8031]
    @0x62E3ED[cataclysm-tiles.exe+0x22E3ED]
    @0xAC3BDB[cataclysm-tiles.exe+0x6C3BDB]
    @0xAC3C91[cataclysm-tiles.exe+0x6C3C91]
    @0xA09E79[cataclysm-tiles.exe+0x609E79]
    @0xA0B3A0[cataclysm-tiles.exe+0x60B3A0]
    @0xABDF92[cataclysm-tiles.exe+0x6BDF92]
    @0x6FA797[cataclysm-tiles.exe+0x2FA797]
    @0x6FD2EC[cataclysm-tiles.exe+0x2FD2EC]
    IMG_LoadWEBP_RW+0x613DD8@0x16AA978[cataclysm-tiles.exe+0x12AA978]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFDDFFB7BD4[KERNEL32.DLL+0x17BD4]
    RtlUserThreadStart+0x21@0x7FFDE050CED1[ntdll.dll+0x6CED1]

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3757273/debug.log)
[Mindoro.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3757294/Mindoro.zip)

**Comment by zakhad** [comment]
I've had segment crashes around a lab which is repeatable and varies depending on the turret / zombies that i can hear sometimes it won't crash sometimes it will so i think it's related to the new 
#34866 change you might have an underground lab that you can't see?

**Comment by DatMeg** [comment]
> 
> 
> I've had segment crashes around a lab which is repeatable and varies depending on the turret / zombies that i can hear sometimes it won't crash sometimes it will so i think it's related to the new
> #34866 change you might have an underground lab that you can't see?

I did check for labs and other things above or below the particular tiles, and there was nothing. I had considered the labs being a problem, as they were changed recently.

**Comment by DatMeg** [comment]
Seems to have been resolved, was likely related to #34994, and thus probably fixed by #35005 as I can't reproduce the crash anymore.
