### ISSUE TITLE
Trying to search for an item that can't be disassembled hangs the game

### ISSUE THREAD

**Issue by DMFan79** [CleverRaven/Cataclysm-DDA#34949]
** Bug description **

In the "Disassemble" window, if I try to use the "Filter" to search for an item that can't be disassembled (either because it's too big to be picked up or because I lack the proper equipment) the game hangs.

** Steps To Reproduce **

1. Open the disassemble screen
2. Look for one or more items that show a red warning telling you they can't be disassembled
3. Use the filter to search for these items

** Expected behavior **

An empty window appears, on the bottom it shows the string "There are no available choices". The game hangs and produces no logs.

** Versions and configuration **

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8720-gf7e743c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    EZ-Mode Medical [fast_healing]
]

** Additional context **

[Porterville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3758779/Porterville.zip)

**Comment by tivec** [comment]
I am unable to reproduce this with your save, searched for each of the items you have in the area. Do you happen to have a specific item that you see causing this?

**Comment by DMFan79** [comment]
Try with the skitterbots: put "skitt" in the filter. It looks like the game doesn't hang everytime, but I couldn't find out why. Keep trying if it doesn't.

**Comment by tivec** [comment]
Still unable to get it to crash.. It has to be something else here. Have you tried it on one of the newest builds?

**Comment by anothersimulacrum** [comment]
The report doesn't describe a crash, only a hang.

**Comment by DMFan79** [comment]
I confirm we're talking about a hang and not a crash. My last reply was about a test I've done using the ZIP with the latest version. It might be hardware related, I'm on an AMD platform (Ryzen 7 3700x CPU).

**Comment by Night-Pryanik** [comment]
Can't reproduce it either. No hang at all. Just typed in "skitt" and the menu popped up immediately.
![изображение](https://user-images.githubusercontent.com/11132525/67617124-ef450380-f7f0-11e9-94eb-1d727ce1f647.png)

**Comment by DMFan79** [comment]
Ok, I tried again with build 9801.

Try this way.

1. download the zip and load the game
2. enter the "disassemble" screen
3. press "Up" to go to the bottom of the list
4. press "/" to open the filter menu
5. write "skitt" and press enter

The game should hang.

![screenshot 3](https://user-images.githubusercontent.com/56896614/67617797-33330b00-f7e7-11e9-80a8-6dd15c1654e6.png)

**Comment by Night-Pryanik** [comment]
Still can't reproduce, even on your save:
![изображение](https://user-images.githubusercontent.com/11132525/67619779-e9f7b100-f810-11e9-86cd-1905c707d8fb.png)

I think that's something wrong with your particular save on your particular rig.

**Comment by DMFan79** [comment]
I suppose it's on my end then. I'm closing this.

Thank you all.
