### ISSUE TITLE
Random Segfaults on 9794

### ISSUE THREAD

**Issue by gynther** [CleverRaven/Cataclysm-DDA#34950]
Game randomly segfaults with no appearant pattern, happened ~5 times since i updated and none before.

Last crash was reading a book, the one before that was running from some zeds.

`CRASH LOG FILE: config/crash.log
VERSION: 0.D-8720-gf7e743c
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5C49D5[cataclysm-tiles.exe+0x1C49D5]
    @0x5C54A2[cataclysm-tiles.exe+0x1C54A2]
    SMPEG_error+0x4B034@0xFA4D30[cataclysm-tiles.exe+0xBA4D30]
    _C_specific_handler+0x98@0x7FFA02A98068[msvcrt.dll+0x28068]
    _chkstk+0x11F@0x7FFA053D477F[ntdll.dll+0xA477F]
    RtlWalkFrameChain+0x14BF@0x7FFA05334BEF[ntdll.dll+0x4BEF]
    KiUserExceptionDispatcher+0x2E@0x7FFA053D34EE[ntdll.dll+0xA34EE]
    IMG_LoadWEBP_RW+0x361491@0x13F8031[cataclysm-tiles.exe+0xFF8031]
    @0x62E3ED[cataclysm-tiles.exe+0x22E3ED]
    @0xAC3BDB[cataclysm-tiles.exe+0x6C3BDB]
    @0xAC3C91[cataclysm-tiles.exe+0x6C3C91]
    @0xA883C8[cataclysm-tiles.exe+0x6883C8]
    @0xABDF92[cataclysm-tiles.exe+0x6BDF92]
    @0x6FA797[cataclysm-tiles.exe+0x2FA797]
    @0x6FD2EC[cataclysm-tiles.exe+0x2FD2EC]
    IMG_LoadWEBP_RW+0x613DD8@0x16AA978[cataclysm-tiles.exe+0x12AA978]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFA05257974[KERNEL32.DLL+0x17974]
    RtlUserThreadStart+0x21@0x7FFA0539A271[ntdll.dll+0x6A271]
`

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-8720-gf7e743c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

**Comment by gynther** [comment]
[Bamberg.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3758931/Bamberg.zip)

A save incase its needed, as mentioned the crash is random and i know of no way to trigger it.

**Comment by gynther** [comment]
Additional info, it seems to only happen in the city, while chilling in the apartment tower on the outskirts for several days ingame and hours realtime no crash was experienced, but when i got closer to the city center game segfaulted again. provided savegame are from an area known to segfaul.

**Comment by gynther** [comment]
[Bamberg_crash_go_east.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3761890/Bamberg_crash_go_east.zip)

Another save, game has segfaulted repeatedly when going east to the house there. during the last 4 attempts crash has occured within a few minutes of game load.

**Comment by GGgatherer** [comment]
Got this on 9794 too, but my crash is anything but random. In [attached save](https://github.com/CleverRaven/Cataclysm-DDA/files/3762649/River.Pines.9794.segfault.zip), do anything - even just wait around for <10 turns - and it always results in segfault to me.


- OS: Windows
    - OS Version: win7 (6.1.7601)
- Game Version: 0.D-8720-gf7e743c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by amystewart256** [comment]
Thirded, this happens on 9794 but did not on 9792.

**Comment by DMFan79** [comment]
I'm getting the same crash on 9797:

CRASH LOG FILE: config/crash.log
VERSION: 0.D-8739-g3c1831f
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5C49E5[cataclysm-tiles.exe+0x1C49E5]
    @0x5C54B2[cataclysm-tiles.exe+0x1C54B2]
    SMPEG_error+0x4B034@0xFA63E0[cataclysm-tiles.exe+0xBA63E0]
    _C_specific_handler+0x98@0x7FF8F55D8048[msvcrt.dll+0x28048]
    _chkstk+0x11F@0x7FF8F58E11FF[ntdll.dll+0xA11FF]
    RtlRaiseException+0x399@0x7FF8F58AA289[ntdll.dll+0x6A289]
    KiUserExceptionDispatcher+0x2E@0x7FF8F58DFE6E[ntdll.dll+0x9FE6E]
    IMG_LoadWEBP_RW+0x361651@0x13F98A1[cataclysm-tiles.exe+0xFF98A1]
    @0x62E3FD[cataclysm-tiles.exe+0x22E3FD]
    @0xAC3CEB[cataclysm-tiles.exe+0x6C3CEB]
    @0xAC3DA1[cataclysm-tiles.exe+0x6C3DA1]
    @0xAD62AA[cataclysm-tiles.exe+0x6D62AA]
    @0xAB71FA[cataclysm-tiles.exe+0x6B71FA]
    @0xABF359[cataclysm-tiles.exe+0x6BF359]
    @0x6FA7A7[cataclysm-tiles.exe+0x2FA7A7]
    @0x6FD2FC[cataclysm-tiles.exe+0x2FD2FC]
    IMG_LoadWEBP_RW+0x613F38@0x16AC188[cataclysm-tiles.exe+0x12AC188]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FF8F4E67BD4[KERNEL32.DLL+0x17BD4]
    RtlUserThreadStart+0x21@0x7FF8F58ACED1[ntdll.dll+0x6CED1]

**Comment by amystewart256** [comment]
For what it's worth, I'd look into roadblocks and/or turrets - wandering around a city the game crashed often around the vicinity of a roadblock. Kept saving, playing, etc - eventually the roadblock turret was destroyed and now I can freely wander the area sans crashes.

**Comment by CataphractPrime** [comment]
Turrets don't seem to be the problem.
I added all the turret monsters to the fungal blacklist mod, generated a world with maximum city size and density, and walked around with debug invincibility for a few minutes, and it still segfaulted eventually, with the same crash log as has been mentioned.

**Comment by EkarusRyndren** [comment]
Figured I'd throw in my two cents from sitting in the discord. A lot of the chatter there seems to point towards the lab stuff, may be related to #34866 but there doesn't seem to be any hard proof yet.

**Comment by gynther** [comment]
Downgraded to 9792 and all segfaults are gone. so its between 9792 and 9794.

**Comment by amystewart256** [comment]
Alright, I have a save where this happens reliably. A LOT is going on around the character, so it may be a bit difficult to isolate. Lots of mods too, sorry :\ The only ones not packaged are Cata++, PK's, and Arcana. 

The character is flying down a street on a dirt bike, the segfault happens a couple turns after that. Debug teleporting away prevents the segfault, so it's something in the immediate vicinity (which is a zombie/triffid war in the middle of a town). Hope this helps.

[Webbville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3769700/Webbville.zip)


OS: Windows 10 Home 64-bit
Graphics Version: Tiles

Mods:
DIsable NPC Needs
Magiclysm
Makeshift Items Mod
Icecoon's Arsenal
Garden Pots
DeadLeaves' Fictional Guns
More Survival Tools
Dinomod
Modular Turrets
Pk's Rebalancing
Salvaged Robots
Cataclysm++
Mythical Martial Arts
Zetsukaze's Hair Extensions (using DeadPeople)
Beta National Guard Camp
Roadheader and Other Mining Vehicles
Folding Parts Pack
Vehicle Additions Pack
Tanks and Other Vehicles
Arcana and Magic Items
Classes and Scenarios Mod
PK - No Radioactive Zombies

**Comment by GGgatherer** [comment]
> 
> 
> Downgraded to 9792 and all segfaults are gone. so its between 9792 and 9794.

Downgraded to 9793, no crashes in 2 days. It's definitely something in 9794.

**Comment by AplonisMagna** [comment]
Same here, started playing in the Lab on a new patch and game began to crash occasionaly without known reason.

**Comment by Wolfechu** [comment]
Same issue here, pretty much any game started after 9792 crashes at some point, typically when the game is 'busy', i.e. driving through a town with lots of mobs about.

**Comment by Tevrian** [comment]
I think this issue might have been fixed?
I created a world with big, close together cities, and 50 times monster spawn rate, so the streets are clogged with zombies.
In 9801, you can walk down the street without any issues whatsoever, asside from the inherent slowdown from hundreds of zombies getting in your way.
Rolling back to 9797, and the game segfaults in moments.
No idea how this was fixed, mind, just that it seems to have been.

**Comment by gynther** [comment]
There have been no reports about crashes here in several days, so i'm closing this.

my guess is that https://github.com/CleverRaven/Cataclysm-DDA/pull/35005 fixed it.
