### ISSUE TITLE
Closing Firestation door crashes game

### ISSUE THREAD

**Issue by User126** [CleverRaven/Cataclysm-DDA#34963]
# Describe the bug

Closing Firestation door crashes game.

# Steps To Reproduce

1. Walk to Firestation
2. Close garage door.

# Expected behavior

The game to not crash

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8720-gf7e743c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

My save and logs.

[New folder.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3759920/New.folder.zip)

**Comment by Night-Pryanik** [comment]
Could you please update to latest experimental and see if it's still and issue?

**Comment by User126** [comment]
It's still crashing

**Comment by User126** [comment]
a screenshot 
![crash](https://user-images.githubusercontent.com/36316526/67609007-4645db00-f7e7-11e9-81f6-1255f0ee1a36.png)

**Comment by ZhilkinSerg** [comment]
Would you please confirm that you have tried to close the door with monsters in the way? That's the only way I can reproduce it on latest experimental version.

![image](https://user-images.githubusercontent.com/16213433/71572562-cb53b600-2af0-11ea-9f82-ac82417fabc6.png)

**Comment by davidpwbrown** [comment]
Cant reproduce on latest master on Linux, closed the gate a hundred times with monsters in the way and not.

Didnt crash at any time.

**Comment by anothersimulacrum** [comment]
I reproduced this yesterday, but couldn't provide a save because the branch I was on made saves incompatible with current master.
