### ISSUE TITLE
Age of Character

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#34978]
Since we already have BMI, weight etc.. I think the next step would be adding age as a "trait" also since a season is 91 days now, noone should die of old age in a few gaming hours.

**Describe the solution you'd like**  
Every character has an age. Ranging from 18 to 70. In the character creation you should have the possiblity to pick the negative trait: middle aged (45-55) +1 and old aged (60-70) +2. Else, your age is around 18-35 (picked at random), with maybe the higest possiblity in around 20-25.
But what comes with age? I would say, the older you get, the slower you become. Maybe starting at 35 you start to get malus in speed, later in strengh and perception, even later (maybe) in intelligence(?).

Later on we can think about illnesses for older folks to happen... but that is a bit far fetched for now.

**Comment by ZhilkinSerg** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/issues/20281

**Comment by KorGgenT** [comment]
i don't think it should be a trait, rather it could be an editable field in character creation.

**Comment by Lamandus** [comment]
As in the options, like the name? Why not, but I was more thinking of XXL and xxs for weight, which aren't traits per se, but treated like neg traits.

**Comment by KorGgenT** [comment]
you know, i've given it some more thought and i think age should be separated from any negative or positive buffs - if you want to roleplay an old man who doesn't have any medical problems and still gets around like a young man, why should you be limited to that? The age number already can be appropriated to your metabolic rate, and you can add negative traits to act like you're old or young. A limit on the ages you can pick should definitely come into play, and i'm not really sure how young we should really let you play as...

**Comment by Alterforce** [comment]
How would professions affect and be affected by age if it was implemented?
For example, Senior Citizen and Elementary Student.  Would there be upper and lower limits on age depending on profession, or would they get replaced with more universal professions?

**Comment by Lamandus** [comment]
> 
> 
> How would professions affect and be affected by age if it was implemented?
> For example, Senior Citizen and Elementary Student. Would there be upper and lower limits on age depending on profession, or would they get replaced with more universal professions?

good question. I would say, the profession is bound to an age-range if defined.
