### ISSUE TITLE
Killing a  Dissoluted Devourer drops two corpses instead of one

### ISSUE THREAD

**Issue by TheGamingFox1911** [CleverRaven/Cataclysm-DDA#34988]
# Describe the bug

Killing a Dissoluted Devourer leaves two corpses instead of 1

# Steps To Reproduce

Spawn or find Dissoluted Devourer.
Kill the Disspluted Devourer.
It should drop two corpses

# Expected behavior

killing the zombie should only drop one corpse when you kill it

# Screenshots

![DD](https://user-images.githubusercontent.com/52058797/67444854-5f287380-f5d0-11e9-951b-f4f4c4e6c6ee.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8739-g3c1831f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Fuji's Military Profession Pack [fuji_mpp]
]

**Comment by Karthas077** [comment]
This is because the dissoluted devourer has scaling volume. After they've absorbed zombies, their volume is larger than base, and the code that creates corpses looks at that and concludes "I need to spawn twice as much volume of zombie corpse so that's two corpses".

I would argue that this isn't necessarily a bug as the dissoluted devourer is by description made up of multiple corpses.

"It's not a bug it's a feature"

**Comment by CataphractPrime** [comment]
Consider the following:
Spawn a Dissoluted Devourer.
Spawn a Necromancer.
Kill the Dissoluted Devourer.
Wait for the Necromancer to revive one of the corpses it leaves behind.
Kill it again and again and again until there are far too many corpses.
Kill the Necromancer and the final Dissoluted Devourer.
Butcher the many many many corpses left behind. Unlimited tainted flesh, tainted fat, and tainted bones.
This violates the conservation of matter, and should therefore probably be considered a bug.

**Comment by Karthas077** [comment]
@CataphractPrime 
I was under the impression that it was only dissoluted devourer's which had fused which were spawning two corpses. If that were the case, and one of them was coming pre-pulped, that would mean conservation of mass was conserved as the revived devourer would have needed to absorb more corpses (which actually erases matter from existence as it's currently written) . Having now tested it myself I see that that is not the case.

I need to see if my pending Dissoluted Devourer fix manages to address this issue, and if it doesn't I'll take a crack at fixing it.

**Comment by Karthas077** [comment]
Found and added to my pending fix.

**Comment by CataphractPrime** [comment]
A shame the fix means Dissoluted Devourers will no longer explode into gore.
