### ISSUE TITLE
Inconsistent use of Mark Firewood Source in the Dark 

### ISSUE THREAD

**Issue by ign1s-fatuus** [CleverRaven/Cataclysm-DDA#34982]
# Describe the bug

I have noticed that while in the dark you cannot mark a firewood source while in the build menu. But, if using the the manage zone menu, you can in fact mark a firewood source regardless of the level of light.

# Steps To Reproduce

1. While in darkness without a light try to set a firewood source using the build menu.
2. Repeat step 1 but use the zone manager.

# Expected behavior
I am not sure sure what the current reasoning is regard marking a firewood source in the darkness, but I feel that one should able to use the little amount of ambient light (the same light that characters use to see their surrounding in the dark) to make a mental note of where firewood is to be stored. As a firewood source doesn't require any physical construction, short of piling up wood/paper/etc., I feel that it should be a rather simple task which is no light dependent.   

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.D-8435-g5483ad5 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by KorGgenT** [comment]
it's because the construction menu is for building constructions, which you need to see in order to do them. the firewood source just used the construction menu as a way to be placed.

**Comment by wapcaplet** [comment]
I could not reproduce this in 0.E-9737-g511ddcb179. The `*` construction menu allows "Mark firewood source", as well as "Mark practice target" and "Make crafting spot" even while in darkness.
