### ISSUE TITLE
Segmentation Fault Upon Trying to Install a CBM in a Lab

### ISSUE THREAD

**Issue by benjaminmkos** [CleverRaven/Cataclysm-DDA#34991]
# Describe the bug

Tried to install the "Autonomous Surgical Scalpels" CBM to my character in a lab autodoc, the game crashes during the CBM installation. Per the crash.log it is a "Segmentation fault" specifically. Save and crash logs attached below.

The crash itself may be unrelated to the CBM installation and have to do with some other shenanigans happening elsewhere in the lab, but it just so happened that the game autosaved during the CBM installation and softlocked my save so I can't really investigate further.

# Steps To Reproduce

1. Load the attached save

# Expected behavior

The game should not crash when installing CBM's.

Ideally there might be a separate feature request to modify the autosave settings during things like CBM installation so that crashes do not softlock your save.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8739-g3c1831f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[CBM Install Crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3765770/CBM.Install.Crash.zip)

**Comment by benjaminmkos** [comment]
Looking at some of the other issues written up lately I may not be only one who has seen this.

This could potentially be closed as a duplicate, however my particular save reproduces the issue seemingly everytime.

**Comment by Fris0uman** [comment]
Jus loaded the save on the latest build and Installed all the available CBMs in the inventory and had no crash

**Comment by benjaminmkos** [comment]
This does indeed appear to have been fixed somewhere along the way.

Best guess is that https://github.com/CleverRaven/Cataclysm-DDA/pull/35005 fixed this.
