### ISSUE TITLE
Game crash 9797 build

### ISSUE THREAD

**Issue by Krokodealer** [CleverRaven/Cataclysm-DDA#35008]
# Describe the bug
Game crash due to Segmentation fault

# Steps To Reproduce
1. Pass turns by any way, like waiting, moving around, etc.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-8739-g3c1831f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Icecoon's Arsenal [ew_pack],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Makeshift Items Mod [makeshift],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Folding Parts pack [deoxymod],
    Tanks and Other Vehicles [Tanks]
]

# Additional context
-Crash log and save file included:
http://www.mediafire.com/file/7f8vcid0ia0c1wo/save1.7z/file

**Comment by amystewart256** [comment]
This is related to [#34950](url)

**Comment by amystewart256** [comment]
This is related to https://github.com/CleverRaven/Cataclysm-DDA/issues/34950
