### ISSUE TITLE
Magiclysm contains unlicensed content from Dungeons and Dragons

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [CleverRaven/Cataclysm-DDA#35024]
@kevingranade @KorGgenT @davidpwbrown 

# Describe the bug
Magiclysm contains nothics, black pudding monsters, bulettes and owlbears. Nothics, monstrous black puddings, bulettes and owlbears are fictional creatures created for the Dungeons and Dragons RPG series. 

# Additional context

Considering how much D&D's designers copied from Tolkien and anonymous Hong Kong toy makers, its probably karmic justice.

**Comment by I-am-Erk** [comment]
Nothics and likely bulettes are trademarks. Owlbears and black puddings are not.

**Comment by davidpwbrown** [comment]
why u ping me tho

**Comment by Zireael07** [comment]
http://www.d20srd.org/indexes/monsters.htm
Bulette is on the list, ergo it isn't trademarked (the license the SRD is under, the Open Game License, explicitly excludes trademarks such as illithids)

**Comment by KorGgenT** [comment]
i will rename Nothic to Krabgek. everything else is in the SRD under the open gaming license.

**Comment by Outta-my-way-burrocrat** [comment]
@I-am-Erk:

IANAL
Their descriptions+names are rather close to the D&D versions.

@davidpwbrown:

I didn't look deep enough to find all contributors potentially affected by any dispute over content in Magiclysm.

@Zireael07 
@KorGgenT 
@jeremyshannon 

IANAL
According to the OGL any OGL'd content must be clearly marked and a copy of the OGL must be included whenever OGL content is copied, modified and/or distributed.

**Comment by jeremyshannon** [comment]
The OGL content would be the stats and the text of their descriptions. Unless he's copying them verbatim, it should be good. There's a vast mountain of off-brand D&D systems out there that do the same, and WotC hasn't come after any of them.
