### ISSUE TITLE
Liquid duplication when picking up and spilling

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#35029]
# Describe the bug

Picking up a non-resealable container with liquid and spilling the contents, drinking the liquid or emptying the container into another one will spawn a pool of liquid in the same tile as the character.

# Steps To Reproduce

1. Place a filled, non-resealable container on the ground.
2. Pick it up and spill the contents.

# Expected behavior

No liquid appers at the character's feet.

# Versions and configuration

 - Game Version: [0.D-8763-gcf5a716]
 - Mods loaded: [dda, no npc needs]

# Additional context

You can stand on a toilet to use the spilled liquids.

**Comment by mrkybe** [comment]
Can confirm.  You can eat your cake and spill it too.
