### ISSUE TITLE
Kentucky Coffee Grounds keep (poisonous) tag after crafting

### ISSUE THREAD

**Issue by Retromo000** [CleverRaven/Cataclysm-DDA#35037]
# Describe the bug

When making Kentucky Coffee Grounds and Coffee Substitute, the (poisonous) tag remains on the item. Not a huge deal, as despite the tag the item doesn't actually seem to poison the player.

# Steps To Reproduce

Craft Kentucky Coffee Grounds and/or Coffee Substitute

# Expected behavior

Kentucky coffee pods aren't poisonous after being processed, and the tags should reflect this.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8435-g5483ad5 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    No Filthy Clothing [no_filthy_clothing],
    SpeedyDex [speedydex],
    Prevent Zombie Revivication [no_reviving_zombies]
]

**Comment by DaviBones** [comment]
Whoops, missed this in #34825, will take care of it shortly.
