### ISSUE TITLE
Very slow loading, especically on existing saves on 9803

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#35035]
# Describe the bug
I cannot load any saves, the game hangs on mapgen weights for strangely long even with no mods, then hangs for a long time on crafting recipes.

The game starts with both of these, albiet with the aformentioned oddly slow loading on a new world, and very long loading on an existing one.

This is all on a decent, fairly new SSD.
# Steps To Reproduce

Start new world with any mod setup, with or without
Save Game
Load Game
Game hangs on Crafting recipes in loading for a very long time and eventually makes it in game, windows believes the game isn't responding so I previously believed it to be a crash

# Expected behavior

Game loads as per normal.

# Versions and configuration
 - OS: Windows 8.1
 - Game Version: build 9803 from releases
 - Graphics version: Tiles
 - Mods loaded: same issue with only dda, or with my standard mod setup that comes with th game.

# Additional context
debug log zipped here, not sure how useful it'll be
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3774331/debug.zip)

**Comment by KorGgenT** [comment]
i pulled master less than an hour ago, and noticed a similar hang but it did not freeze entirely.

**Comment by new02DAY** [comment]
I noticed a slow-down on creating/loading a new world. Also noticed a pronounced hanging during loading an old world/save. It took ~20min to get past "Crafting Recipes", and then further hanging during "Verifying".

**Comment by anothersimulacrum** [comment]
Fresh compile on Linux at 50cb40a668 - noticeable hang at crafting recipes, but the save loaded.

**Comment by dissociativity** [comment]
I suppose I didn't have the patience to wait 20 minutes where normally it'd open fairly quickly, I'll edit to say it works, it just hangs for a long period of time

**Comment by new02DAY** [comment]
I actually gave up and reverted to 9801 after it hanged for 20+ on "Verifying". So I think there might be an issue with mods or the number of crafting recipes. I might try letting it run on 9803 overnight and see if it loads. 
 
My debug info in case anyone looking at this issue needs it:
- OS: Windows
- OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-8779-g5ad16b6 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Player Mod [Player_Mod], **Custom monster blacklist only**
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by KorGgenT** [comment]
i'll note the mods i had when i tried it were just magiclysm and dda.

**Comment by ZhilkinSerg** [comment]
#34938?

**Comment by ZhilkinSerg** [comment]
Or #34735?

**Comment by mft-dev** [comment]
Maybe related, on 9804 I notice a severe slowdown when going up/down stairs in a lab.

**Comment by new02DAY** [comment]
@ZhilkinSerg is right, I think. It took me an hour to load an old save and it generated a 73.2 MB debug.log on 9804. So I think the issue is compounded by the number of items in a save?

**Comment by RDru** [comment]
I gave up after 20min. I have 500MB save.

**Comment by KoRv117** [comment]
Yup, save size seems to affect loading. Save I just created still made a massive debug log but was able to load in very quickly, whereas my main game creates a HUGE debug log, and still didnt load after 20 minutes

**Comment by Kenan2000** [comment]
100% confirm this, even had to delete my old save thinking it got corrupted, luckily i can still use debug menu to relearn all the skills and make monsters evolution again
