### ISSUE TITLE
Bug with a soldering-iron

### ISSUE THREAD

**Issue by yoba712** [CleverRaven/Cataclysm-DDA#35044]
# Describe the bug
If the soldering-iron is modified "UBP Converter", then it does not receive energy from the Unified Energy System KBM
Same problem with any "Converter"-modified items

# Steps To Reproduce
Modify soldering-iron with "UBP Converter"
Activate Unified Energy System KBM
Try to craft

**Comment by Saicchi** [comment]
Assuming the user meant `UPS` instead `UBP`.
Can not reproduce using `0.E-10134-g9b256f63cd [64-bit]`, a soldering iron with UPS conversion kit installed is properly using the batteries when crafting and repairing.
