### ISSUE TITLE
Silo overmap view distance does not change with telescope or binoculars

### ISSUE THREAD

**Issue by ign1s-fatuus** [CleverRaven/Cataclysm-DDA#35059]
# Describe the bug

When climbing a silo while carrying either a survivor telescope or pair of binoculars the view distance does not change. This is to say that the default via distance, i.e. ground level, is used even when venturing to the top. This is in striking contrast to the boost in range gained from climbing single-story buildings/radio towers. 

# Steps To Reproduce

1) Equip survivor telescope/binoculars
2) Climb a silo found in farm locations
3) check map 

# Expected behavior

As with climbing to the second story of a building or to the top of a radio tower, one would expect an increase of field of view when climbing a silo while equipping a tool with the "ZOOM" flag, such as a survivor telescope or pair of binoculars.

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.D-8435-g5483ad5 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by zeggz** [comment]
That's not a silo specific related issue i think. There is a inconsistancies on the bonus applied to view distance when climbing above groung level. Sometime it just does'nt work and you have to walk around before the bonus kick in and sometime you have to go back down then then up again. Sometime it just does'nt work at all. That's strange, it seems like sometime under certain conditions the bonus view distance is not applied. I've not been able to narrow down the exact condition but yes it seems  to happen more frequently on farm silo.

**Comment by ign1s-fatuus** [comment]
Interesting. For whatever reason I have found that climbing to the top of radio towers works 100 percent of the time, at least in my experience. Alternatively, I have never had a farm silo register any bonus regarding view distance. I'll dig through the code tomorrow and see if I can get any idea as to what's going on.

**Comment by ign1s-fatuus** [comment]
> That's not a silo specific related issue i think. There is a inconsistancies on the bonus applied to view distance when climbing above groung level. Sometime it just does'nt work and you have to walk around before the bonus kick in and sometime you have to go back down then then up again. Sometime it just does'nt work at all. That's strange, it seems like sometime under certain conditions the bonus view distance is not applied. I've not been able to narrow down the exact condition but yes it seems to happen more frequently on farm silo.

Playing around a little and I can confirm that you are correct. After walking around onto of a silo and checking the map, eventually it registered and kicked in the stacking multipliers for posz height and has_optic. looking at the function, overmap_sight_range (in src/player.cpp), most of the code looks to be rather straight forward. There are a couple of if statements at the beginning that deal with sight_range and light_level that I am still trying to sort out. It is only a guess but it could be that something is causing the function to return the value of sight before any modifiers can be applied.

**Comment by AMurkin** [comment]
Does the problem persist when saving, quitting the game and loading?

**Comment by JonnieCache** [comment]
I have noticed this too, I thought at first I needed to step to the edge of the roof but that isn't it.

I'll try and submit a save next time I notice it.

**Comment by ign1s-fatuus** [comment]
> Does the problem persist when saving, quitting the game and loading?

Yes, I can confirm that it does persist, even after saving. At least in the tests that I have run.

**Comment by ign1s-fatuus** [comment]
Finally got around to doing a little debugging the issue. I thought that there might be something the overmap_sight_range function but after looking at the output of all the variables in the function, everything looks to be working as it should (as far as the stacking bonuses are concerned). I will still keep digging but have found in my debugging attempts that some tiles will seemingly always trigger the extended view while others will not. I am still familiarizing myself with the code but I now thinking that perhaps there is a line of sight issue. If anyone has any ideas or has an in-depth knowledge of how the overmap is revealed, such input would be more than welcome.

**Comment by ymber** [comment]
I'm taking a shot at this one. Should get it fixed for 0.E.
