### ISSUE TITLE
Deconstruct Without Light at Night

### ISSUE THREAD

**Issue by XardasTheDude** [CleverRaven/Cataclysm-DDA#35066]
Able to finish a complex furniture deconstruction project at night without a light source.

1. Turn on light source at night and begin deconstructing complex furniture
2. Stop the project and turn off light source
3. Resume and finish the project without a light source

Expected to be unable to resume the project without a source of light

- OS: Windows
    - OS Version: 10.0 1903 Windows 10
- Game Version: 0.D-8779-g5ad16b6 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Bootleg Walkers [Bootleg_Walkers],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Extended Realistic Guns [realguns],
    Craft Ammo Mags - ERG [SD_Magcrafting_Realguns_Extension],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Gun Cotton [guncotton],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Draco's Dog Mod [DracoDogMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    Big River Building Pack [BIGRIVER],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    No Fungal Monsters [No_Fungi],
    No Explosive Zombies [No_Explosive_Zombies],
    No Acid Zombies [No_Acid_Zombies]
]

**Comment by Morat2255** [comment]
Also applies to vehicle construction tasks I've noticed.

**Comment by LeeMartin77** [comment]
Just confirmed:

- OS: Ubuntu

    OS Version: 10.0 1903 Windows 10

- Game Version: 0.D-8779-g5ad16b6 [64-bit]
- Graphics Version: ncurses
- Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs
]

Will pick this up and see if I can figure it out.
