### ISSUE TITLE
Folding vehicle lowers weight.

### ISSUE THREAD

**Issue by TKTKO** [CleverRaven/Cataclysm-DDA#35064]
# Describe the bug

Built a vehicle with the intent of replicating a collapsible ladder to cross 2 or 3 cell gaps between roofs. Vehicle is 8x1, with nothing but Foldable-Light Frames. Each frame weighs 5 kg. Unfolded, vehicle weighs 40 kg, in line with the expectation based on frame weight.  Folding the vehicle creates  an object 20.00 L and 0.04 kg.

# Steps To Reproduce

Create an 8x1 vehicle out of Foldable-Light Frames, check vehicle weight. Fold vehicle and compare weight while folded.

# Expected behavior

Vehicle should continue to weigh 40 kg.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8779-g5ad16b6 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Armor Up! PA Utilities [ArmUpPAUtil],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Bens GF recipes [Tolerate_This],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    More Survival Tools [More_Survival_Tools],
    Boats [boats],
    MST Extra [MST_Extra],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Extended Realistic Guns [realguns],
    Craft Ammo Mags - ERG [SD_Magcrafting_Realguns_Extension],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Manual Bionic Installation [manualbionicinstall],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by KorGgenT** [comment]
well that's weird, it's off by exactly a factor of 1000.

**Comment by Inglonias** [comment]
See also #31772.
