### ISSUE TITLE
Persistent crashing (Arithmetical error)

### ISSUE THREAD

**Issue by Berkyjay** [CleverRaven/Cataclysm-DDA#35062]
I've been experiencing random yet persistent crashes in the game recently  They have been more frequent in city areas. 

# Steps To Reproduce

Load up the saved game and drive the vehicle forward (screen right).  The spot where the game crashes is a short distance ahead.  I get the same crash in various areas in the game.

# Expected behavior

Ideally also describe *why* you expect it to happen.

# Screenshots

![GameCrash](https://user-images.githubusercontent.com/5049386/67626050-0daffc80-f7fb-11e9-8302-32064f0e8d80.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-8761-g923c311 [64-bit]
- Build: 9799
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3775271/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3775272/debug.log)

Save file: 
https://drive.google.com/open?id=14EZkRCWpQnlIL0pzuF6vJMoV9PaN4b5J

**Comment by Berkyjay** [comment]
Damn, my entire save is borked.  Any movement I make loading that saved game ends up with the same crash.

**Comment by anothersimulacrum** [comment]
This has already been fixed, you need to update your game.

**Comment by Berkyjay** [comment]
I tried updating but the game hung every time I loaded up the save.  So I had to revert back.  But I guess it's a moot point now since my save is essentially lost.

**Comment by GroeneAppel** [comment]
No that's a bug too. 
9801 is a sweet spot right now.
Any later version has endless (20 min+) loading times, and before that has common segway crashes in city areas/labs.

**Comment by anothersimulacrum** [comment]
Either way, this issue isn't valid, because it's reporting an error that has been fixed.

**Comment by davidpwbrown** [comment]
> I tried updating but the game hung every time I loaded up the save. So I had to revert back. But I guess it's a moot point now since my save is essentially lost.

Your save is not lost, the arithmetical error is fixed, and the loading time error will be fixed.
once that is fixed,and you update, you can play your save again, in the meantime, just to be sure, you are backing up your saves when playing experimental anyway yes? because experimental is experimental.

**Comment by davidpwbrown** [comment]
closing as fixed by #35005
