### ISSUE TITLE
Fire Ring + Improvised Shelter dysfunctionality

### ISSUE THREAD

**Issue by MurderPenguin** [CleverRaven/Cataclysm-DDA#35072]
# Describe the bug

Cannot build Fire Ring on Improvised Shelter but can build Improvised Shelter on Fire Ring due to Improvised Shelter changing the ground under it from shallow pit to Improvised Shelter whereas the Fire Ring does not change the ground type.

# Steps To Reproduce

1. Make Improvised Shelter.
2. Try to build Fire Ring.
3. Cannot build.

# Expected behavior

Fire Ring should be build-able inside an Improvise Shelter as the purpose of the shelter is to either protect a player or a fire.

# Versions and configuration
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3775522/debug.log)

**Comment by Night-Pryanik** [comment]
The reason is the same as in (stale) #26638.
