### ISSUE TITLE
Crash when exploring city

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#35074]
# Steps To Reproduce

1. Open provided savegame ([save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3775547/save.zip))
2. Move East until it crash.

# Additional context

Crash / Debug Files:

* [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3775549/crash.log)
* [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3775550/debug.log)
* [config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3775554/config.zip) (EDIT: added my whole config folder, in case options are a factor)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8761-g923c311 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]

**Comment by Karthas077** [comment]
I strongly suspect this is the arithmetic error which was recently introduced and fixed. Have you tried updating the game?

**Comment by KurzedMetal** [comment]
Ups, I didn't, I was holding my version down a few builds because of the massive load times.

**Comment by KurzedMetal** [comment]
Yep, fixed by updating, sorry. Closing the issue.
