### ISSUE TITLE
Crash log on game exit

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#35089]
# Describe the bug

Get an error when I quit the game

# Steps To Reproduce

Quit the game.

# Expected behavior

No crash when quitting the game

# Screenshots

# Versions and configuration

 - OS: Windows 10
 - Game Version: 9810
 - Graphics version: Tiles
 - Mods loaded: DDA

# Additional context

CRASH LOG FILE: config/crash.log
VERSION: 0.D-8845-g32025a2
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5C55C5[cataclysm-tiles.exe+0x1C55C5]
    @0x5C6092[cataclysm-tiles.exe+0x1C6092]
    SMPEG_error+0x4B034@0xFA3370[cataclysm-tiles.exe+0xBA3370]
    _C_specific_handler+0x98@0x7FFA78767C58[msvcrt.dll+0x27C58]
    _chkstk+0x11D@0x7FFA7AE9ED2D[ntdll.dll+0x9ED2D]
    RtlWalkFrameChain+0x13F6@0x7FFA7AE06C86[ntdll.dll+0x6C86]
    KiUserExceptionDispatcher+0x2E@0x7FFA7AE9DC5E[ntdll.dll+0x9DC5E]
    IMG_LoadWEBP_RW+0x35F724@0x13F4904[cataclysm-tiles.exe+0xFF4904]
    @0xBC649C[cataclysm-tiles.exe+0x7C649C]
    @0x8CEE34[cataclysm-tiles.exe+0x4CEE34]
    @0x995200[cataclysm-tiles.exe+0x595200]
    initterm_e+0x1AB@0x7FFA7877A2BB[msvcrt.dll+0x3A2BB]
    @0x911FA3[cataclysm-tiles.exe+0x511FA3]
    IMG_LoadWEBP_RW+0x6138CB@0x16A8AAB[cataclysm-tiles.exe+0x12A8AAB]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFA788D3034[KERNEL32.DLL+0x13034]
    RtlUserThreadStart+0x21@0x7FFA7AE71461[ntdll.dll+0x71461]

Does anyone else get this?

**Comment by OrenAudeles** [comment]
Probably fixed with #35079 looks to be the same crash-on-quit issue mentioned in `Purpose for Change` section
