### ISSUE TITLE
aux flamethrower cannot be installed on pneumatic AR

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#35084]
# Describe the bug

Well, it's all in the subj, You cannot install aux flamethrower on pneumatic assault rifle despite it having open underbarrel slot and AFT being an underbarrel mod.

# Steps To Reproduce

Make pneumatic AR, make aux FT, try activating aux FT, get the message that pneumatic AR "doesn't have slot for this mod".

# Expected behavior

Either PAR shouldn't have underbarrel slot, or AFT should be attachable to it, whatever gods of balance deem reasonable. IMO it should be attachable - PAR isn't the most epic weapon of all times, and when you can make it you probably already have better ones.

# Screenshots

![cataclysm-tiles_2019_10_27_20_33_42_285](https://user-images.githubusercontent.com/56833396/67635514-e0e30e80-f8fa-11e9-9691-16d3d1584f11.png)
![cataclysm-tiles_2019_10_27_20_35_39_526](https://user-images.githubusercontent.com/56833396/67635516-e3456880-f8fa-11e9-9dc9-4282ba92119d.png)
![cataclysm-tiles_2019_10_27_20_36_35_641](https://user-images.githubusercontent.com/56833396/67635521-f5270b80-f8fa-11e9-90d8-c99b8868f127.png)

# Versions and configuration

- OS: Windows 7 (6.1.7601)
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-8845-g32025a2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]

**Comment by Night-Pryanik** [comment]
PAR has slot for **underbarrel mount**, not for simply **underbarrel**. You have to install underbarrel mount on PAR first to get underbarrel slot, and then aux flamethrower on top of it.
