### ISSUE TITLE
Can't constract Faction building out of Steel Plate as menue won't register steel plates in the vicinity

### ISSUE THREAD

**Issue by ShinWinddreamer** [CleverRaven/Cataclysm-DDA#35087]
Wanted to make my own faction camp and went ahead and founded it. Went to the billboard and had the loot zones sorted out before.
Select main building and it wont register the steel plates in the area apart from 3. Those 3 are always there even though , after removing all plates in the immediate vicinity, there shouldn't be any.
Here a few screenshots:

Steps to reproduce:

1. Create faction camp

2.Try to build the basecamp that requires steel plates

# Expected behavior

1.Create faction camp

2.Billboard registers available ressources correctly

3. Build main building out of steel plates.

4.Substract Steel plates from stocks

5.Finish the building step and work accordingly in future steps when utilizing steel plates as ressource

# Screenshots

1:  https://imgur.com/9cKEhlt

2: https://imgur.com/GUcZhxa

3: https://imgur.com/KbriyIq

4: https://imgur.com/lg9WEbH

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-8845-g32025a2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Filthy Clothing [no_filthy_clothing],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by AlexMooney** [comment]
On the map, is the basecamp label centered on your position, or is it a few tiles away?  I wonder if there are 3 steel plates somewhere kind of nearby that are found but the area you're standing isn't considered to be your base.

**Comment by ShinWinddreamer** [comment]
> 
> 
> On the map, is the basecamp label centered on your position, or is it a few tiles away? I wonder if there are 3 steel plates somewhere kind of nearby that are found but the area you're standing isn't considered to be your base.

It's directly centered. Your cam area usually is 3x3 maptiles and I stand right in the middle of it and nope, no other ressources nearby either. It's odd and ,as much trouble as i had in previous builds with npc's and faction home, the building worked in the sense that available ressources were shown.

![grafik](https://user-images.githubusercontent.com/54183288/67948558-49293d00-fbe6-11e9-8a87-a5fa3777dee3.png)

**Comment by mlangsdorf** [comment]
I can't reproduce: I have 100 steel platings near the bulletin board:
![MetalPlating_p2](https://user-images.githubusercontent.com/8007405/68076481-fafd7080-fd82-11e9-9559-ef8e31c4a1df.png)
and I can build a steel structure:
![MetalPlating](https://user-images.githubusercontent.com/8007405/68076483-02bd1500-fd83-11e9-9e2c-de2a136265cb.png)

**Comment by ShinWinddreamer** [comment]
> 
> 
> I can't reproduce: I have 100 steel platings near the bulletin board:
> ![MetalPlating_p2](https://user-images.githubusercontent.com/8007405/68076481-fafd7080-fd82-11e9-9559-ef8e31c4a1df.png)
> and I can build a steel structure:
> ![MetalPlating](https://user-images.githubusercontent.com/8007405/68076483-02bd1500-fd83-11e9-9e2c-de2a136265cb.png)

That's odd. For me the problem still persists. I also crafted the steel plates myself in batches of 20 if that matters I don't know but apart from that , I am clueless. The other building recipes do register nearby ressources correctly. Wood for wood buildings etc. but it's the steel building where it insists on only having 3 steel plates nearby even if theres a stack of 100 in the same tile or no ressources nearby at all. It's odd and rather puzzling.

**Comment by esotericist** [comment]
Could you please attach your save where you are experiencing this problem?

**Comment by ShinWinddreamer** [comment]
> 
> 
> Could you please attach your save where you are experiencing this problem?



https://drive.google.com/file/d/1OR4BLS6km-J-hZgzRsqLoH9tu7X4mphC/view?usp=sharing

**Comment by esotericist** [comment]
@ShinWinddreamer I can't access that, it's a private file.

Can you please attach a .zip file of your save directly to this issue, instead of linking to it in a third party site?

**Comment by ShinWinddreamer** [comment]
> 
> 
> @ShinWinddreamer I can't access that, it's a private file.
> 
> Can you please attach a .zip file of your save directly to this issue, instead of linking to it in a third party site?

I would but the Zip file goes over the file size limit of this page xD. My dropbox is full as well so the only thing I still had as an option was stuffing it in googledrive which I pretty much never used before to try and see if it's accessable.
