### ISSUE TITLE
Weird view obscureness

### ISSUE THREAD

**Issue by mykytak** [CleverRaven/Cataclysm-DDA#35096]
# Describe the bug

When close (1 tile) to transparent map objects, they behave as solid.

# Steps To Reproduce

1. Find bicycle/open window/table
2. Move 1 tile close
3. Watch it becomes solid wall

# Expected behavior

Be able to see over bicycle wheels/opened windows or tables all the time.

# Screenshots

![view_bug](https://user-images.githubusercontent.com/21195002/67641673-89e63500-f90c-11e9-8249-1b420be0b07e.png)
![view_bug_2](https://user-images.githubusercontent.com/21195002/67641674-8a7ecb80-f90c-11e9-90d7-0b7ad78dbea4.png)
![view_bug_3](https://user-images.githubusercontent.com/21195002/67641675-8baff880-f90c-11e9-89fc-a9a97ebd30f1.png)
![bicycle_vision_bug](https://user-images.githubusercontent.com/21195002/67641726-ff520580-f90c-11e9-9d3b-f671fcb1e5fc.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 16.04.6 LTS; Release: 16.04; Codename: xenial; 
- Game Version: 0.D-8845-g32025a2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    C.R.I.T Expansion Mod [crt_expansion],
    Garden Pots [growable-pots],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    No Fictional Guns [no_rivtech_guns],
    No Sci-Fi Equipment [no_scifi],
    Battery Migration for Existing Games [Battery_Overhaul_Legacy_Mode],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Vollinger** [comment]
Your character is crouching (the blue `(C)` after `Move` in the sidebar), he's not able able to see over tiles of certain height. (I think that's the `coverage` value when examining terrain)
Check the keybind for `Cycle move mode`, stand up, see if his vision improves.

Shameful admission: the only reason I know this is by accidentally switching to sprint mode all the goddamn time, running out of stamina and getting ate.

**Comment by mykytak** [comment]
@Vollinger Thanks! It's Not a Bug, It's a Feature :)

Poor Derick crouching for a few days by now. Chopped tree, made a few clothing under table, cooked some wild veggies, spent full day throwing paper wrapper into trash can. Even killed 2 zeds. But bicycle stopped that wonderful experience xD
