### ISSUE TITLE
No bees doesn't remove wasps

### ISSUE THREAD

**Issue by Brytenwalda** [CleverRaven/Cataclysm-DDA#35099]
# Describe the bug

The "no bees" mod doesn't remove giant wasps, and it probably should. 

# Steps To Reproduce

1. Create a new game using the latest version.
2. Use the "no bees" mod.
3. Giant wasps will still be in your game.

**Comment by Fris0uman** [comment]
Why should it remove wasp?
![image](https://user-images.githubusercontent.com/41293484/67643300-3d075c00-f916-11e9-9f64-db83c2dbc09e.png)
No bees removes bees, wasp are not bees, this seem to work as intended.

**Comment by Brytenwalda** [comment]
> 
> 
> Why should it remove wasp?
> ![image](https://user-images.githubusercontent.com/41293484/67643300-3d075c00-f916-11e9-9f64-db83c2dbc09e.png)
> No bees removes bees, wasp are not bees, this seem to work as intended.

Because they're almost the same thing, and I can imagine that most players who don't want bees, are unlikely to want wasps either. A separate mod removing wasps would probably be a better idea, though.

**Comment by Kodiologist** [comment]
Well, what's the purpose of a no-bees mod anyway? #27125 provides no hints, but I'm guessing the point was not to help you if you have a phobia of bee-like insects or something, but rather, to remove beehives if you find them to be boring and a waste of map. @Inglonias?

**Comment by kevingranade** [comment]
It does what it says, not a bug.

**Comment by Inglonias** [comment]
This is a little late, but yes. The main purpose of the mods was to remove beehives from the game, not bees entirely.

If you still want the mod to also remove wasps, adding them to the monster blacklist is relatively simple to do. Simply add `mon_wasp` into the monster blacklist in the modinfo.json file.
