### ISSUE TITLE
Auto-picklock does not work on wooden doors

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#35109]
**Is your feature request related to a problem? Please describe.**  
Since #35083 we can examine metal doors and pick them. That is not possible on wooden doors.

**Describe the solution you'd like**  
Examining doors that are locked should result in the door being picked.

**Describe alternatives you've considered**  
Giving wooden doors the locked_object_pickable examine action, but that won't work with the peephole door.

**Comment by MattD94** [comment]
This could be a separate bug, but I've found that examining locked doors results in 
"You attempt to pry open the closed door with your hammer...
"You can't get sufficient leverage to open that with your hammer"

Even though I don't have anything with any prying quality.

I did have a stone hammer one time, but it has no prying quality and I still got the message after leaving it out of sight radius.

Likewise, this occurs when when I do and don't have any lock-picks in my inventory.

(0.D-12286-ge47abc7, linux64)
