### ISSUE TITLE
Wilderness Clothing!

### ISSUE THREAD

**Issue by MurderPenguin** [CleverRaven/Cataclysm-DDA#35107]
**Is your feature request related to a problem? Please describe.**  
Naked Wilderness start is pretty rough as it is, but the game offers no clothing options short of a hat and shoes that can be made using materials from the wilderness.

**Describe the solution you'd like**  
Withered plant underwear!
Bark fiber clothing!
Wood armor?

**Describe alternatives you've considered**  
Turning bark/withered plants into yarn (with spindle) to make rags to make clothing.

**Additional context**  
The Primitive Technology youtube channel does a bunch of cool stuff including exactly what I'd like to see. Video link attached.
https://www.youtube.com/watch?v=ey68uVUuyvs

**Comment by snipercup** [comment]
I think it's a nice idea. The fiber_mat came to mind, I don't know of any other fabric made from plants. Maybe we can ask Rail-runner if something like this can be part of the total tailoring overhaul or maybe work out a seperate idea. Like making a fiber_mat from some fiber_patch crreated from withered plants.

**Comment by MurderPenguin** [comment]
There's the straw hat and a couple types of shoes that use bark, but other than that there's pretty much nothing.

Fiber_patch sounds like a good idea. Long crafting time is a definite, it takes a while to weave stuff by hand. I could also see low quality quick-craft perishable clothing, like a leaf skirt and a leaf bra.

I'd like to use bark more as well, it's so much easier to get bark than fiber but it has limited recipes. Ideally, the natural clothing progression would be something like this:
Perishable fast-craft raw plant ---> weak protection moderate-craft fiber-weave ---> moderate protection slow-craft fiber-weave+bark

**Comment by ANickelN** [comment]
MurderPenguin, can you upload some examples of that kind of clothing to reference?

**Comment by MurderPenguin** [comment]
**Plant Bikini**
-
Category: Clothing  |  Price: $0.00
Volume: 0.25 L  |  Weight: 0.07 lbs
Material: Plant
Covers: The torso
Layer: Close to skin
Coverage: 10%  |  Warmth: 5
Encumbrance: 1
Protection: Bash: 1  |  Cut: 0
Acid: 0  |  Fire: 0  |  Environmental: 0
A simple plant bikini top.
Cannot be repaired
Does not conduct electricity
Lies close to skin
Performs well when soaking wet
Cannot be refitted
Perishable, spoils within 3 days

Primary skill: Survival 0 (or 1?)
Other skills: none
Time to complete: 25 minutes
Batch time saving: none
Dark craftable?: Impossible
Tools required: 1 tool with cutting 1 or more
Components required: 20 withered plant + 8 plant fiber OR 16 withered plant


**Plant Loincloth**
-
Category: Clothing  |  Price: $0.00
Volume: 0.25 L  |  Weight: 0.07 lbs
Material: Plant
Covers: The legs
Layer: Close to skin
Coverage: 10%  |  Warmth: 5
Encumbrance: 1
Protection: Bash: 1  |  Cut: 0
Acid: 0  |  Fire: 0  |  Environmental: 0
A simple plant loincloth. Hides your modesty.
Cannot be repaired
Does not conduct electricity
Lies close to skin
Performs well when soaking wet
Cannot be refitted
Perishable, spoils within 3 days

Primary skill: Survival 0 (or 1?)
Other skills: none
Time to complete: 30 minutes
Batch time saving: none
Dark craftable?: Impossible
Tools required: 1 tool with cutting 1 or more
Components required: 20 withered plant + 8 plant fiber OR 16 withered plant

**Comment by MurderPenguin** [comment]
> MurderPenguin, can you upload some examples of that kind of clothing to reference?

Do you mean pictures and stuff, or in-game stats/concepts as shown just above?

**Comment by ANickelN** [comment]
Pictures with instructions or a video of someone making these things in real life.  I know that you can make simple linen/fiber fabrics, but those aren't nearly as easy to make as the recipes you propose would show.

**Comment by MurderPenguin** [comment]
The first post shows the making of some pants, but what I'm proposing is basically just rolled up plants (for rope) to attach leaves together. The same kind of process as banana leaf roofing.

**Comment by MurderPenguin** [comment]
![image](https://user-images.githubusercontent.com/57055033/67714856-21946380-f99f-11e9-9baa-2c9a0acfec64.png)

**Comment by MurderPenguin** [comment]
https://www.youtube.com/watch?v=vhsGSghiIJ0
