### ISSUE TITLE
Chesthole32 Revise tiles to remove copyright data

### ISSUE THREAD

**Issue by blockhead123** [CleverRaven/Cataclysm-DDA#35105]
Hi, guys really like using Chesthole32 i understand that we can't use it due to copyright issues, so I'm planning to revise the tileset to remove the copyright materials. I would like anyone's help to verify the copyright tiles. screenshots for each one would help and I will try to recreate a different version of it.

**Comment by AMurkin** [comment]
https://discourse.cataclysmdda.org/ would be more suitable for this IMO.

**Comment by KorGgenT** [comment]
yes, check out the discord or the discourse, possibly also Ultica or Cutieclysm to combine your efforts with people already working. Github isn't really the place for a post like this. Reddit would also be another spot to ask for help from the community.

**Comment by blockhead123** [comment]
great thanks
