### ISSUE TITLE
Wrong message displaying when wielding non compatible item while using silat

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#35111]
Oh no, the Silat guy again

# Describe the bug

When using a silat weapon and change it to something not silat compatible (in this case Pelmeni (don't judge me), it doesn't say "Pelmeni aren't a Silat weapon". But: "Silat cannot be used with weapons". Changig back to a Quaterstaff works fine and Silat is used. 

# Steps To Reproduce

1. Have Character with Silat. Have Silat weapon equiped.
2. Equip non Silat itam.

# Expected behavior
Have the display that "Item is not a Silat weapon"

# Screenshots
![silat](https://user-images.githubusercontent.com/33199510/67687559-c6f80900-f998-11e9-8c5e-ff6bf3add60b.jpg)

# Versions and configuration

9815

**Comment by Hymore246** [comment]
I have tried but I can't replicate this bug. That message should only appear if a martial arts style is marked as "strictly_unarmed" in martialarts.json and you equip an item. No martial art is "strictly_unarmed" right now. Does Silat have "strictly_unarmed" set to true in your martialarts.json?

Martial arts message method from martialarts.cpp
```
void character_martial_arts::martialart_use_message( const Character &owner ) const
{
    martialart ma = style_selected.obj();
    if( !ma.force_unarmed && !ma.weapon_valid( owner.weapon ) ) {
        if( !owner.has_weapon() && ma.strictly_melee ) {
            owner.add_msg_if_player( m_bad, _( "%s cannot be used unarmed." ), ma.name );
        } else if( owner.has_weapon() && ma.strictly_unarmed ) {
            owner.add_msg_if_player( m_bad, _( "%s cannot be used with weapons." ), ma.name );
        } else {
            owner.add_msg_if_player( m_bad, _( "The %s is not a valid %s weapon." ), owner.weapon.tname( 1,
                                     false ), ma.name );
        }
    } else {
        owner.add_msg_if_player( m_info, _( ma.get_initiate_avatar_message() ) );
    }
}
```

**Comment by Lamandus** [comment]
I checked again. It is still says "Silat cannot be used with weapons". And stricly_unarmed is not used in the file, true.

**Comment by Hymore246** [comment]
I updated to build 9846 and I still cannot trigger the bug
![Silat_bug](https://user-images.githubusercontent.com/11396600/67988818-193a6380-fbff-11e9-9213-a2d958ccc702.png)

If you are still get the bug after updating, you might have a mod running that is changing Silat. Other than that, I can't think of a reason why you are getting that message.

**Comment by Lamandus** [comment]
![New](https://user-images.githubusercontent.com/33199510/68017286-aaa8e480-fc96-11e9-80d0-934ac78bc6f6.jpg)
![new1](https://user-images.githubusercontent.com/33199510/68017287-aaa8e480-fc96-11e9-8d1d-ea8a8c29ab07.jpg)
As you can see, I run as clean as I get. Still getting the error.

**Comment by Lamandus** [comment]
even debugging silat in throws the same error.
![new2](https://user-images.githubusercontent.com/33199510/68017442-03787d00-fc97-11e9-8de7-66093c3d5a32.jpg)

**Comment by Lamandus** [comment]
![Silatnew](https://user-images.githubusercontent.com/33199510/68017768-bc3ebc00-fc97-11e9-8e45-2c272f6fa212.jpg)
ok, I installed a absolutly clean copy and used the "PC language" German. And as you can see, it throws the error still, just CDDA with no mods. Are you sure your Game is not "bugged"?

**Comment by Hymore246** [comment]
I'm pulling the code (build 9851) straight from Github, compile it, running it with a new world and character and I do not get the wrong error message. My last suggestion is to update the game and see if that fixes it.

Anyone else able to recreate this bug?

**Comment by Lamandus** [comment]
I used the lancher until now. I downloaded the game from the homepage, clean folder. Still same error.,
Please try using a download version from launcher or Homepage as well.

**Comment by Hymore246** [comment]
The bug DOES show up in the downloaded version. I have no idea why it appears in that version but not the raw version. This oddity has happened with others before and I'm asking some people if they know what causes it.
