### ISSUE TITLE
Different calculations of cannibalism penalties

### ISSUE THREAD

**Issue by TychaiosIlithios** [CleverRaven/Cataclysm-DDA#35114]
**Is your feature request related to a problem? Please describe.**  
Pretty simple - not realistic feeling means no immersion, not too good for game balance means no fun. Meaning a person eating human meat is still hella sad about it every time in a year of doing so. 

**Describe the solution you'd like**  
Replace static penalty set for consuming human materials with 1-3 pools of sentimental points (hidden). These pools have random and slowly regenerating amounts of humanity. Once someone does something anti-humanitarian, a random amount of points is taken from that pool and turned into a morale penalty. Once the pool is dry, there's also a random morale 'downfall' event from zero reaction to mega penalty curable by getting drunk, after which this pool no longer works.

So while there are several pools, the most 'tender' one applies the most steep set of randomly picked morale penalties. Once it's dry - the next one can very rarely apply just the same amount of depression, but mostly just meh - bad weather feelings. Then it's just same 'it'-different day.

**Describe alternatives you've considered**  
I understand that whole cannibalism thing is more of a cosmetic fetish than a real survival thing - but it seems to be a persistent and well cared for fetish - alternatives were to just leave it be but is it right?

**Additional context**  
Comeon, it only bugs people from time to time. We now have words like genocide and assault on human dignity, but few hundred years ago ppl would just visit hostile village, burn it, and extract fat of victims to fill 'napalm'  grenades for attacking the castle. Valuing human life is much more fragile than currently shown.

And pool system could be then further used for different things related to choices and morale control. Examples - killing zombie children is a problem, only until you dry the first pool. Then - no bits given. This could result in some psychic attacks related to fear factor be resisted better, but some psychic attacks related to demonic possession through images of shadows of the past be harder to resist and generally happiness would become rarer for a person who has the crap of life all over. Alzo religion and some other positive morale related ideas could become much more meaningful as actual choices in being the means to regenerate the pools without drying them up.

In other words a fluid mechanism of personality decision between vulnerable living and hardcore deadened survival.

**Comment by ANickelN** [comment]
This is a great idea, especially when applied to other subjects like you mentioned.

**Comment by Karthas077** [comment]
Regarding the specific mechanism you mentioned, while I agree that the current static system is very sub-par, humans really don't work the way you're describing. Yes, different people have different breaking points, but the system you're proposing would result in every person having exactly three breakdown events, each of which "can be solved" with alcohol. Which one - is not a healthy coping mechanism, and two - wouldn't actually SOLVE any sort of psychological fragility from engaging in acts that bother you.

> more of a cosmetic fetish than a real survival thing

I'm not sure I understand what you mean here.

**Comment by Kodiologist** [comment]
Note that it's already the case that the penalty from guilty kills, such as zombie children, decreases as you kill more of the monster type:

https://github.com/CleverRaven/Cataclysm-DDA/blob/8f0f6bb/src/mondeath.cpp#L454

**Comment by TychaiosIlithios** [comment]
Kodiologist - yup, but it's not interconnected with other ethics related issues and thus is an isolated entity.

Karthas077 - you are perfectly right about problems with fixed switching pools, and actually that's a systemic problem of the proposal. However the word random means random paradigm shift events, possibly even suicide checks. Aaaand really unique conditions to going back up through religious and other rare events. Like going from walker to vader = just an emo tantrum +- hundred dead kids and going back up - a long and sad story.

Also being in each of those pools might mean something similar to alignment. Examples imagined:
Top pool - sentimental, cheerful, open minded - bonuses to social skills and interactions, high vulnerability to negative morale effects but better regen of neg morale due to full power of perks like optimist and stylish. Bonuses to trust reaction.
Mid pool - focused, determined - bonuses to specific combat (ie by weapon type) and production skill training bonuses due to being focused on the job. Average effect of negative morale events and not the best regen - but a really big pool, so as long as activities are switched should be no prob.
Low pool - rough, direct - bonuses to general combat (melee attack, marksmanship) skill training, intimidate reactions and stamina regen - due to being free of restraining second thoughts when punching faces hard and fast. 
Negative morale to be extracted from pool with a strong reduction to make it really hard to go below zero, and if under - have another instance of evil/teleglow like sickness where depending on severity of depression has a set of different statuses i.e. if a whole bunch of negative points are accumulated there's a chance to use a whole ton of them to make character just shoot any living entity with a trigger happy like chance during the tantrum duration. Or another bunch of negative points just turn a character to severely socially hindered individual for a day.
..yep, when it was proudly said 'bonuses' - max like 10% on top of all other morale conditions just to add to the bunch and define the flavor.

Anyway as raw as it was - just an idea, just to compare to currently being oh so sad about eating human to save life after actually bashing human zombies with crowbars for weeks.
