### ISSUE TITLE
non GUNMOD type gunmods with gunmod_data cannot be installed

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#35117]
# Describe the bug
Gunmod items that have a `type` other than `GUNMOD` and have their properties defined in a `gunmod_data` object cannot be installed on a weapon.

# Steps To Reproduce
1. Spawn a combat knife and an M16A4.
2. Activate the combat knife and observe that no option is presented to install it as a gunmod. No such option exists in the % menu either.
3. Spawn a pistol bayonet and a Glock 17
4. Activate the pistol bayonet and observe that it can be installed on the Glock 17 as expected.

# Expected behavior
Non `GUNMOD` gunmods can be installed normally and behave as other gunmods do.

# Versions and configuration
 - OS: Arch Linux x86_64
 - Game Version: Current master at ffe470b975559b3c6a125aef7f237429ab655760
 - Graphics version: Tiles
 - Mods loaded: dda, no_npc_food

# Additional context
I bisected back a few days and found that #35067 was introduced in #34735. I can't tell if this issue was introduced by the same because #35067 makes it impossible to test for but I confirmed that this bug is not present in builds from one commit prior to #34735 (42e22fad5db2becfe5b368a27c54646281de108f).

**Comment by Karthas077** [comment]
The line responsible seems to be the edit which changed `load_slot_optional( def.mod, jo, "gunmod_data", src );` to `load_slot_optional( def.mod, jo, "mod_data", src );`

No corresponding change was made to the gunmod JSON entries, so any mods which relied upon that functionality stopped acting as gunmods.

**Comment by BT-naH** [comment]
Quick test by reverting the code change does appear to correspond with your analysis. I'm not convinced that'd be a 'fix' more than a bandaid though, perhaps a look at the data structure is pertinent?

**Comment by Karthas077** [comment]
Only five items make use of gunmod_data. Zero items make use of mod_data. The change was obviously an error, and while I agree that the data structure should be re-examined, that's a separate issue.
