### ISSUE TITLE
Shooting a metal locker shouldn’t destroy it

### ISSUE THREAD

**Issue by Brytenwalda** [CleverRaven/Cataclysm-DDA#35131]
# Describe the bug

Shooting a metal locker shouldn’t destroy it. In the latest version, one shot from the police officer’s gun (the one you start with), completely smashed it to pieces.

# Steps To Reproduce

1. Create a police officer.
2. Find a metal locker.
3. Shoot it.

# Expected behavior

Ideally, shots should pierce it but not destroy it. Perhaps shooting it with a shotgun or a large-caliber weapon would shatter it after a while, but not just a few pistol bullets.

**Comment by Karthas077** [comment]
Partial destruction of furniture is not yet implemented. As such the only current options are for the metal locker to be completely impervious to pistol fire, or capable of being destroyed as it currently is.

**Comment by Karthas077** [comment]
Furniture/terrain already has code for ballistic penetration. What you're describing is still the same state of "Impervious to small arms fire", which is even less realistic than ballistic glass remaining mostly intact despite bullet holes.
