### ISSUE TITLE
Certain building walls are invisible until stepping within two tiles

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#35133]
# Describe the bug

I have noticed that certain building walls are not visible unless the player is standing close to them. The tile next to the wall is also marked as "very dark" even during daytime. This seems to be larger buildings such as the zoo

# Steps To Reproduce

1. Find a zoo
2. Observe the lack of visible walls
3. Move closer to the wall and find the very dark tile and then the wall.

# Expected behavior
I expect to see the wall from a distance, and the tile next to it should be visible.

# Screenshots

![image](https://user-images.githubusercontent.com/717574/67743385-c4d88d80-fa1e-11e9-8e11-0f2042abe750.png)

![image](https://user-images.githubusercontent.com/717574/67743395-cdc95f00-fa1e-11e9-96bc-4b5a7c6f84c3.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8877-g5c100d7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    DinoMod [DinoMod],
    Hydroponics [hydroponics],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    sees-player icon, retrodays [sees_player_retro],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Fuji's Military Profession Pack [fuji_mpp],
    Sleep Deprivation [sleepdeprivation],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Nothing further to add.

**Comment by curstwist** [comment]
Migo scout tower does this too. Neither of these have roofs that overhang the walls, I checked.

**Comment by AMurkin** [comment]
Related to #31994.

**Comment by l29ah** [comment]
Some of the research facility walls have this strange property as well.

**Comment by int-ua** [comment]
Not sure if that's intentional but looks like all outer walls are invisible like this at least when viewed from a higher Z level.
