### ISSUE TITLE
Crash in item::toolmods() in refugee center

### ISSUE THREAD

**Issue by irwiss** [CleverRaven/Cataclysm-DDA#35140]
# Describe the bug

I'm getting crashes in refugee center, in item::toolmods() which gets called through npc::wield_better_weapon() though i suspect some inlining happens and it might not be the complete stack

The attached save has mods, if you don't have the exact mod set you can hold i while loading to ignore all mod-related errors

# Steps To Reproduce

1. Load attached save
2. Do any action that advances time - e.g. move 1 tile right

# Expected behavior

No crash

# Screenshots

![stack](https://i.imgur.com/ZvIzoqh.png)

# Versions and configuration

Not sure this is too relevant, as i've been seeing this crash over multiple commits for the past few days but;

 - OS: Windows 10
 - Game Version: last tested on commit 7047a47e179679db56f2f902f996fbc04899f3a9
 - Graphics version: Tiles
 - Mods loaded: "dda", "aftershock", "crt_expansion", "adv_gear", "makeshift", "nw_pack", "More_Survival_Tools", "FIC_Weapons", "craftgp", "SD_Magcrafting", "alt_map_key", "hydroponics", "mutant_npcs", "MMA", "more_locations", "FujiStruct", "No_Rail_Stations", "deoxymod", "blazemod", "Heavy miners", "Tanks", "Arcana", "no_npc_food", "no_olg_guns", "no_reviving_zombies", "No_Fungi", "novitamins", "_CustomTweaks"

# Additional context

[Primary.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3784662/Primary.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3784670/debug.log)

**Comment by irwiss** [comment]
Looks like one of the npcs wields a scabbard with scimitar (and has a scabbard on them?), deleting all items on that specific npc via debug menu prevents the crash

![image](https://user-images.githubusercontent.com/6560075/67791937-f97d3100-fa80-11e9-8872-282438bf0581.png)

**Comment by Night-Pryanik** [comment]
Cannot confirm on 0.D-9029. I tested without any mods, though, and on a brand new world. No crash. Could you please update to the latest version and/or check on a brand new world and see if this is still an issue?

NPC wielding scabbard with a scimitar AND having worn scabbard looks like a bug to me. Pinging @I-am-Erk.

**Comment by I-am-Erk** [comment]
Guneet does indeed have an extra scabbard, which I can fix easily enough, but he's never been bugged before and this isn't a new development.

**Comment by irwiss** [comment]
I'm testing on latest commit on master branch 26ddfe9d4305432c0c8603abb53370b5e590611c, attached save game still crashes. The scabbard might not be the cause for crash, but the scimitar appears as the item on the stack and deleting the items on that specific npc resolves the crash.

If you feel modded game is the thing that causes the crash i guess that's fair and you can close the issue

**Comment by ZhilkinSerg** [comment]
Probably fixed in #36506
