### ISSUE TITLE
Magiclysm "no such item group"

### ISSUE THREAD

**Issue by KoRv117** [CleverRaven/Cataclysm-DDA#35155]
Game version: 
0.D-8892-g0445b8b 
Patch 9826
Operating system:
 Windows 10
Tiles or curses: 
Tiles
Mods active: 
  "dda",
  "filthy_morale",
  "novitamins",
  "No_Fungi",
  "Tolerate_This",
  "craftgp",
  "FIC_Weapons",
  "realguns",
  "generic_guns",
  "ew_pack",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "mutant_npcs",
  "more_locations",
  "FujiStruct",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "more_classes_scenarios",
  "safeautodoc",
  "sleepdeprivation",
  "StatsThroughSkills",
  "magiclysm",
  "hydroponics",
  "MMA",
  "speedydex",
  "aftershock",
  "crt_expansion",
  "Mining_Mod",
  "WildLiving",
  "More_Armors"
### Expected behavior
Able to properly load my magiclysm game
### Actual behavior
Attempting to load the game gets error
![Korv Loading Bug](https://user-images.githubusercontent.com/56089860/67828246-1168ab00-faa9-11e9-9f67-a4510a86fa66.png)

### Steps to reproduce the behavior
Attempt to load game with magiclysm, but may be due to another mod not interacting well with magiclysm.

**Comment by anothersimulacrum** [comment]
Fixed about a minute ago in #35154

**Comment by esotericist** [comment]
Ships passing in the night.

**Comment by KoRv117** [comment]
gotcha, thank you
