### ISSUE TITLE
Remove crafting weight penalties on in-progress items

### ISSUE THREAD

**Issue by everythingisonfire** [CleverRaven/Cataclysm-DDA#35156]
If you craft a heavy item and stop midway, the in-progress item will inflict weight penalties on the player when trying to finish. With the weight penalties, finishing may take far longer than just crafting a new one.

Workbenches currently only help with crafting heavy items. So alternatively, they could be used to help finish heavy in-progress items as well.

**Comment by Karthas077** [comment]
If you end up holding an in-progress item, you can drop it on a workbench and 'e'xamine to resume crafting without picking it up.

**Comment by everythingisonfire** [comment]
> If you end up holding an in-progress item, you can drop it on a workbench and 'e'xamine to resume crafting without picking it up.

Whoops, I should have been more specific. This is an issue with vehicle workbenches, as they have a volume limit. If you try to place an in-progress item on it, it may be over the volume capacity and placed on the ground, providing no help.

I also like sdp0et's suggestion on a partial refund. Could this possibly be done through disassembly?

**Comment by Karthas077** [comment]
> Whoops, I should have been more specific. This is an issue with vehicle workbenches, as they have a volume limit. If you try to place an in-progress item on it, it may be over the volume capacity and placed on the ground, providing no help.

That sounds to me like a perfectly realistic example of "my workbench is too cluttered to work on this". Unless you're saying that there are items that exist which are too big for a vehicle workbench even if it's otherwise empty?

Regardless, the ability to abandon an in-progress craft definitely sounds like a reasonable idea.

**Comment by everythingisonfire** [comment]
Unless you're saying that there are items that exist which are too big for a vehicle workbench even if it's otherwise empty?

Yeah, that's what I'm referring to. The workbench on has 30-liter volume capacity, whereas some in-progress items are larger than that. Things like large storage batteries, steel drums, minifridges, autoclaves, etc.

**Comment by anothersimulacrum** [comment]
I think it's pretty reasonable for those things to be too big for an in-vehicle workbench.

**Comment by everythingisonfire** [comment]
> I think it's pretty reasonable for those things to be too big for an in-vehicle workbench.

The workbench helps when you're crafting them, so why wouldn't it help you finish an in-progress one?

**Comment by anothersimulacrum** [comment]
Yes, but vehicles aren't places that will have a lot of space. If you want more space, you should use a workbench that isn't in vehicle. A vehicle workbench should be usable for smaller crafts, but for larger ones, it shouldn't really be usable

**Comment by kevingranade** [comment]
I don't see a valid issue here, some workbenches (vehicular ones in particular) having limited capacity is intended. If you want to avoid the penalty for not having a good enough workbenches, get a good enough workbench.
