### ISSUE TITLE
Starting a game presents multiple errors

### ISSUE THREAD

**Issue by UndeadMoose** [CleverRaven/Cataclysm-DDA#35161]
# Describe the bug

When loading up a new or existing game you are presented with multiple errors.

# Steps To Reproduce

1. Start up a new or existing game

# Expected behavior

Starting a new or existing game shouldn't present these errors

# Screenshots

![Screenshot (107)](https://user-images.githubusercontent.com/56947231/67848946-ff3e4980-fb48-11e9-80ec-b69c5ce444bf.png)
![Screenshot (108)](https://user-images.githubusercontent.com/56947231/67848950-01a0a380-fb49-11e9-8281-8c0a9cc6516e.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D.8952.gcad9691
 - Graphics version: Tiles
 - Mods loaded: None

# Additional context

Trying to load a world with any mods at all will make the world unable to load at all.

**Comment by Brytenwalda** [comment]
I encountered these too, it’s impossible to start the latest build.

**Comment by levstk** [comment]
I got one of them, related to the "More Survival Tools" mod. Game loaded fine without that mod.
