### ISSUE TITLE
Save won't load on 9834

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#35170]
# Describe the bug

Multiple errors on attempting to load an old save. 1 error specific to mod More_Survival_Tools.
Please see attached debug and/or save. Save works on 9827.

# Steps To Reproduce

1. Attempt to load save.

# Expected behavior

No errors.

# Versions and configuration

- OS: Windows
- OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-8589-gcad9691 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Player Mod [Player_Mod], **(Personal monster blacklist)**
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[save_20191029221802_autumn_day_69.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3791122/save_20191029221802_autumn_day_69.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3791119/debug.log)

**Comment by OrenAudeles** [comment]
Update to 9836. I am not seeing the errors when comparing current files against the errors in provided debug.log

**Comment by new02DAY** [comment]
Thanks. Launcher won't let me download 9836, only 9834. Although the changes in 9835 looks like it might be related and might fix the issues. I'll give it a try when I can download the build.

**Comment by Proxiehunter** [comment]
I also don't seem to be able to download anything after 9834, it says the build is unavailable. And it's not just the launcher, nothing after 9834 is available [here](http://dev.narc.ro/cataclysm/jenkins-latest/Windows_x64/Tiles/) either. Also not available [here](https://cataclysmdda.org/experimental/) where the github page explicitly says to download it from.

**Comment by new02DAY** [comment]
9837 just finished and it solves the issue. If it's okay with the devs, I'll leave this open for another day, just so people who have this issue see it.

**Comment by Proxiehunter** [comment]
Still won't load my save because of an error with aftershock.
 

> DEBUG    : Error: data/mods//Aftershock/items/afs_armor.json: line 24:18: duplicate entry in json object
> 
>     "material_thickness": 2,
>     "flags": [ "BELTED", "ONLY_ONE", "LEAK_DAM" ],
>     "looks_like":
>                  ^
>                   "portal"
>   },
>   {
> 
> 
>  FUNCTION : bool main_menu::load_character_tab()
>  FILE     : src/main_menu.cpp
>  LINE     : 1015
> 

Seems to be the same as whatever was causing the armor error fixed in update 9837 but I'm not sure what that fix was and it's unclear to me from the message what needs to be fixed.

**Comment by DidNotZero** [comment]
> Still won't load my save because of an error with aftershock.
> 
> > DEBUG    : Error: data/mods//Aftershock/items/afs_armor.json: line 24:18: duplicate entry in json object
> > ```
> > "material_thickness": 2,
> > "flags": [ "BELTED", "ONLY_ONE", "LEAK_DAM" ],
> > "looks_like":
> >              ^
> >               "portal"
> > ```
> > 
> > 
> > },
> > {
> > FUNCTION : bool main_menu::load_character_tab()
> > FILE     : src/main_menu.cpp
> > LINE     : 1015
> 
> Seems to be the same as whatever was causing the armor error fixed in update 9837 but I'm not sure what that fix was and it's unclear to me from the message what needs to be fixed.

Was about to post this too, the only issue is when the new "looks_like" was added they forgot to get rid of the old one so there is a duplicate entry.

**Comment by Proxiehunter** [comment]
Just discovered that myself when I took a second look at the file. So yeah, anyone who's still having issues just delete either "looks_like": "portal" or "looks_like": "mollie pack".
