### ISSUE TITLE
Blank screen when tilesets enabled on Raspberry Pi 4

### ISSUE THREAD

**Issue by Viole7** [CleverRaven/Cataclysm-DDA#35174]
# Describe the bug

I compiled cdda from the latest build on github. I can navigate the interface and play without tiles enabled. When tiles are enabled, no matter which tileset I select, all I can see is a blank screen where tiles should be, the rest of the interface displays fine.

# Steps To Reproduce

1. Enable tiles in graphics options.
2. Start a game.
3. Tiles will not display properly.

# Expected behavior

The tilesets should be displayed.

# Screenshots

https://i.postimg.cc/qRnFc5Lp/2019-10-30-155823-1920x1080-scrot.png

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Raspbian; Description: Raspbian GNU/Linux 10 (buster); Release: 10; Codename: buster; 
- Game Version: 0.D-8892-g0445b8b1d7 [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Garden Pots [growable-pots],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks]
]

# Additional context

Save file:
[blankscreensave.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3791496/blankscreensave.zip)

I installed (cataclysm-dda-sdl/stable 0.C+git20190228.faafa3a-2 armhf) via apt during my debugging process and had the exact same issue. The only thing that I can think of is a missing dependency but I have no idea what it could be.

**Comment by ZhilkinSerg** [comment]
Did you resolve this issue by chance?

**Comment by Viole7** [comment]
> Did you resolve this issue by chance?

Nope, I never figured it out. Sorry.

**Comment by paulwratt** [comment]
I am seeing the same thing with both the latest repo builds, _and_ the distribution `0.C+git20190228.faafa3a`

I wounder if its the SDL2 versions:
```
ii  libsdl2-dev                          2.0.9+dfsg1-1+rpt1
ii  libsdl2-gfx-dev:armhf                1.0.4+dfsg-3
ii  libsdl2-image-dev:armhf              2.0.4+dfsg1-1+deb10u1
ii  libsdl2-mixer-dev:armhf              2.0.4+dfsg1-1
ii  libsdl2-net-dev:armhf                2.0.1+dfsg1-4
ii  libsdl2-ttf-dev:armhf                2.0.15+dfsg1-1
```

BTW the sound still works, and (just like the above screenshot) the minimap works. Well I guess everything works, except it does not show the gfx tiles (png?) - the toggle scent cloud works on current repo builds, and it works with ASCII when you change the Tileset option in the Graphics Options.
