### ISSUE TITLE
Debug message 

### ISSUE THREAD

**Issue by ifreund** [CleverRaven/Cataclysm-DDA#35191]
# Describe the bug
The following debug message is displayed when loading into a newly generated world with a new character and choosing the island prison start.
```
DEBUG    : Tried to set ammo of .300 AAC Blackouts without suitable magazine for AR-15+1

 FUNCTION : item &item::ammo_set(const itype_id &, int)
 FILE     : src/item.cpp
 LINE     : 457
```

# Steps To Reproduce

1. Create new world
2. Create new character
3. Select island prison start
4. load in to world
5. Observe debug message

# Expected behavior
No debug message

# Versions and configuration
```
- OS: Linux
    - OS Version: 5.3.7-arch1-2-ARCH
- Game Version: 0.D-9004-g15bd2e14c1 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.D-9029 on Windows 10 x64. Was able to start island prison scenario without any errors.
My guess is that game tries to spawn AR-15 with incorrect ammo or something like that.

**Comment by Night-Pryanik** [comment]
Yeah, seems like my guess is right:
![изображение](https://user-images.githubusercontent.com/11132525/68066399-bc4ec280-fd50-11e9-8272-1588198045f2.png)

**Comment by ymber** [comment]
The real bug here remains unfixed. See discussion in #35250.
