### ISSUE TITLE
electrohack bug

### ISSUE THREAD

**Issue by MrOlaf** [CleverRaven/Cataclysm-DDA#35195]
# Describe the bug

Electrohack checks if hack succeeded and then freezes the player for approximately 3 minutes in front of the hacked door.

# Steps To Reproduce

1. use electrohack on laboratory door 
2. See time pass (approximately 3 minutes)
3. Die to turret unless you stand out of turret line of sight ;)

# Expected behavior
Time spent hacking should pass before success/fail is rolled.

# Versions and configuration

 - OS:  Windows 
 - Game Version: [from the main menu, e.g. 0.D-8582-g5fc6532]
 - Graphics version: Tiles
 - Mods loaded: dda, disable npc needs,whaleys tattoos, zetsukaze's hair, no rail stations

**Comment by zeggz** [comment]
Can confirm.
When using electrohack the doors open before the hack is finished and expose the caracter to enemies while he can't move/act or stop the process.

**Comment by MrOlaf** [comment]
Thanks for swift action :)
