### ISSUE TITLE
Battery System CBM unusable.

### ISSUE THREAD

**Issue by Proman9000** [CleverRaven/Cataclysm-DDA#35208]
# Describe the bug

Battery System CBM not able to activate because of missing fuel in current build.

# Steps To Reproduce

1. Make new character with Battery CBM
2. Try to activate it
3. Watch it complain about missing fuel

# Expected behavior
Working CBM

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9019-gdfc081c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Fris0uman** [comment]
`E`at batteries first and then activate

**Comment by Proman9000** [comment]
Hmm, this works now. Could have sworn that I tried it and they didnt show up. Thanks.
