### ISSUE TITLE
Farms shouldn’t spawn with various produce

### ISSUE THREAD

**Issue by Brytenwalda** [CleverRaven/Cataclysm-DDA#35207]
**Is your feature request related to a problem? Please describe.**  
I know it will likely be an unpopular idea and that it would make the game harder, but farms shouldn’t spawn with various vegetables scattered around their fields. Depending on the start date it would make sense to place either crops or crop seeds, for something that’s actually farmed there. 

Scattered produce makes sense for community gardens and perhaps small gardens by the farms, but not fields. Also, as the game usually starts in early spring, they had no chance of actually growing through winter.

**Describe the solution you'd like**  
I’d like the produce to be removed from the fields and possibly community gardens as well. It will make them much more realistic.

I’m aware that it will make the game harder, but fields full of random vegetables make little sense.

**Describe alternatives you've considered**  
Fields could possibly spawn with seeds instead.

**Comment by anothersimulacrum** [comment]
If you'd like to do this, it'd be fairly easy to remove these and replace them with some stage of planted crops.

**Comment by Brytenwalda** [comment]
I'm not sure how to do that, I'm new to modding structures and palettes - while I would probably know how to code it, I have no idea which files to mod. I've noticed that farms have no mention of produce in the mapgen files, and yet it still spawns there.

**Comment by anothersimulacrum** [comment]
It's part of the palette (`data/json/mapgen_palettes/`), it tells items from the group `hydro` to spawn on dirt mounds.
To replace it with planted seeds of some sort, you need to use the `sealed_item` field. See `data/json/mapgen/mall.json` L 4889 for an example.

**Comment by davidpwbrown** [comment]
+1 for this , it makes little sense that farms would have harvested food just lying around the fields.

but planted seeds yes.
