### ISSUE TITLE
Countryside seems devoid of life

### ISSUE THREAD

**Issue by Brytenwalda** [CleverRaven/Cataclysm-DDA#35212]
**Is your feature request related to a problem? Please describe.**  
The game's countryside seems to devoid of life. Rural New England is indeed heavily forested, but IMHO the game doesn't place nearly enough farm fields - this makes the countryside less believable.

Also, there are not nearly enough farm fields, meaning that farms don't seem to be producing much. 

**Describe the solution you'd like**  
1) A higher farm field to farm ratio. There should be more farm fields in the vicinity of farms, creating clusters - a farm with a barn and a few fields nearby. 
2) Agricultural zones on map should be larger, and denser, mimicking the proximity of farms to each other, especially along rivers.
3) Country dirt roads are not as prevalent as they should be - farms should IMHO be connected to their fields using dirt roads. 

I know it's not really a priority, but a better countryside would make the world much more plausible.

**Comment by DaviBones** [comment]
Here's a table I put together with data sourced from the [Massachusetts 2017 Census of Agriculture](https://www.nass.usda.gov/Publications/AgCensus/2017/Full_Report/Volume_1,_Chapter_1_State_Level/Massachusetts/mav1.pdf). Note that I left out "woodland" (land designated for use for wood products e.g. wood, maple sap, christmas trees) which comprised about 194,189 acres, and land with agricultural buildings (including homes), roads, and ponds, which comprised 79,627 acres.

I'm not sure how this data actually compares to in-game farmland, but here are some assessments I'm pretty sure are accurate:
- There are *far* too many wheat fields in-game.
- There are probably too many vegetable fields in-game.
- There are *not nearly* enough hay fields in-game.

Land Use | Farms | Acres | % of Agricultural Land | % of All Land
-- | -- | -- | -- | --
Hay | 1,773 | 57,965 | 30.66% | 0.86%
Pastures | 3,203 | 46,341 | 24.51% | 0.69%
Other Veggies | 1,383 | 18,079 | 9.56% | 0.27%
Corn | 245 | 16,348 | 8.65% | 0.24%
Berries | 979 | 14,994 | 7.93% | 0.22%
Hops | 5 | 14,220 | 7.52% | 0.21%
Oats | 3 | 6,700 | 3.54% | 0.10%
Rye | 10 | 5,006 | 2.65% | 0.07%
Orchards | 614 | 4,704 | 2.49% | 0.07%
Popcorn | 11 | 3,682 | 1.95% | 0.05%
Tobacco | 15 | 461 | 0.24% | 0.01%
Soybeans | 6 | 317 | 0.17% | 0.00%
Beans | 9 | 205 | 0.11% | 0.00%
Barley | 8 | 46 | 0.02% | 0.00%
Wheat | 8 | Unavailable | Unavailable | Unavailable
Sorghum | 2 | Unavailable | Unavailable | Unavailable
Sunflower | 2 | Unavailable | Unavailable | Unavailable
**Total** | **8,276** | **189,068** | **100.00%** | **2.80%**

**Comment by thethunderhawk** [comment]
In general I wouldn’t expect to find much unused grassland at all in rural New England. I’m from the west coast not the east, but if it’s anything like here all the grassland should be plotted out in a tough grid, generally separated by cattle fences, connected by access roads, and dotted here and there with rural buildings of all types.

**Comment by DaviBones** [comment]
@thethunderhawk You're half right; there should be a lot less unused grassland than there is, but New England is very heavily forested (at least in eastern Massachusetts, where I live) and there are a fair amount of natural clearings in the forests that stay undeveloped, either due to being too deep in the forest or because they're part of designated nature reserves.

One thing I think would be cool is to see stuff like [this](https://www.google.com/maps/place/42%C2%B010'48.1%22N+71%C2%B033'54.3%22W/@42.1743846,-71.5666039,757a,35y,39.26t/data=!3m1!1e3!4m6!3m5!1s0x0:0x0!7e2!8m2!3d42.1800232!4d-71.5650865) -- a very long, narrow stretch of land that has been clear-cut (and stays that way due to constant maintenance) to make way for high-tension power lines.

**Comment by actual-nh** [comment]
> I think #46701 fixed this

@Venera3, your thoughts?

**Comment by Venera3** [comment]
Not really fixed yet, to be honest. Bringing worldgen a bit closer to real NE would need (based on some cursory Google Earthing, mind) way more forests, less fields and of those fields a lot more should be farmland bordered by ditches/treelines that make the willy-nilly offroading of today's survivor tends to do impossible. *That*, in turn would need roadgen that's a bit more diverse and offers alternate routes - as it stands every road leads from one city to another or dead-ends in a special, with intersections only existing in zombie-filled city centers that you would realistically want to avoid.

**Comment by Zireael07** [comment]
@Venera3: And a coast at one end of the world, y'know...

**Comment by actual-nh** [comment]
Perhaps a modified version of #48607 such that it tried to connect to a road sometimes even if it could find a city?

**Comment by stubkan** [comment]
I am pushing a pr soon that will add a lot of farms to the countryside on larger spacing.  But it does not fix the issue on normal spacing (which is unrealistically cramped anyway).  

I might make another edit soon after to make farm specials have a bigger weight, which should increase the amount of them.  Although that will come with the problem of having less room for non-farm specials, and cut back on the other more interesting specials, such as military bases, labs, factories that people might object to...  So...

**Comment by actual-nh** [comment]
@stubkan: BTW, have you taken a look at the associated project ([Mapgen and overmapgen improvements](https://github.com/CleverRaven/Cataclysm-DDA/projects/12))?

**Comment by LyleSY** [comment]
I just threw together a little PR to address the wheat piece of this. Is anything else needed to close this?
