### ISSUE TITLE
Clothing description is incomplete in latest experimental builds

### ISSUE THREAD

**Issue by simast** [CleverRaven/Cataclysm-DDA#35217]
# Describe the bug

Clothing description is incomplete in latest experimental. See screenshot below.

# Screenshots

![clothing-description-bug](https://user-images.githubusercontent.com/433527/68005691-bbe5f700-fc7e-11e9-99c0-3a333d8028fb.jpg)

**Comment by ZhilkinSerg** [comment]
What item is this?

**Comment by simast** [comment]
`pair of fit-over sunglasses` for example. I can reproduce this on many items.

**Comment by ZhilkinSerg** [comment]
That is `VARSIZE` flag which is missing `info` tag.

https://github.com/CleverRaven/Cataclysm-DDA/blob/9c02dee3c1ffb5166cb301c7b6ab2b866399011f/data/json/flags.json#L470-L475

**Comment by ZhilkinSerg** [comment]
Caused by #35217
