### ISSUE TITLE
Crash when opening inventory

### ISSUE THREAD

**Issue by DidNotZero** [CleverRaven/Cataclysm-DDA#35210]
# Describe the bug

At random the game would crash whenever I try to open an inventory screen, this one below was when I pressed d so I could drop something. It also crashed like this when I tried equipping a purse.

# Steps To Reproduce

1. Cross your fingers
2. Open an inventory menu

# Expected behavior

To open an inventory menu without crashing and to be able to leave it without crashing.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9019-gdfc081c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    sees-player icon, retrodays [sees_player_retro],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Fuji's Military Profession Pack [fuji_mpp],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3795937/config.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3795938/save.zip)

**Comment by levstk** [comment]
Happened to me when trying to examine an item on the ground, seems to be the same error. Can't go back to retry because the thing I picked up wasn't loaded yet at the time of the last save, but crash log anyway.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3796471/crash.log)

**Comment by ymber** [comment]
Similar report to #35171. Possibly the same issue.

**Comment by DidNotZero** [comment]
The other issue has been closed with a fix merged.

**Comment by DidNotZero** [comment]
Ok, the fix didn't work in build 9857, soda cans don't seem to crash anymore though. Got the same error again trying to pick up what looks like a glass jar of something.

**Comment by Zireael07** [comment]
I *think* the PR will only guard against generating more bugged containers of stuff, if you continue in the same world, previously generated stuff will still be bugged?

**Comment by DidNotZero** [comment]
> I _think_ the PR will only guard against generating more bugged containers of stuff, if you continue in the same world, previously generated stuff will still be bugged?

No, it's a new world. If something is broken I scrap the save and start over.

**Comment by DidNotZero** [comment]
No solution in sight, bug will remain for now.
