### ISSUE TITLE
Error on loading save

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#35215]
# Describe the bug

Upon loading my saved game, which had been created and played on build #9839, I was met with the following error:

![](https://cdn.discordapp.com/attachments/252368751016542218/639666414449459213/unknown.png)

Hitting space to load the game anyway, resulted in this:

![](https://cdn.discordapp.com/attachments/252368751016542218/639667156119715840/unknown.png)

The save log appears badly corrupted, with all stats set to default or zero, including all maximum HP values.

# Steps To Reproduce

Not possible to reproduce at this point.

# Expected behavior

That my character doesn't implode upon save load.

# Versions and configuration

Windows 10, running build #9845.

Modlist:   
"dda",
"no_npc_food",
"deoxymod"

**Comment by anothersimulacrum** [comment]
Fixed in #35185
If you still have the intact copy of the save, you could fix it by deleting that duplicate object.

**Comment by Solusphere** [comment]
Alas, I don't. I forgot to enable save backups in the launcher. Thanks for the tip though.

**Comment by BevapDin** [comment]
Closing as duplicate.
