### ISSUE TITLE
If Butchering is interrupted whilst catching breath certain actions automatically continue it, even when dangerous

### ISSUE THREAD

**Issue by mentos046** [CleverRaven/Cataclysm-DDA#35225]
# Describe the bug
If a player is in the middle of butchering something and an interruption occurs while the player character is catching breath, dropping an item or using a spell from Magiclysm will both automatically continue the catching breath and butchering, even if there is a threat nearby. The butchering continues even if the character is no longer near the corpses and this can produce errors. Additionally, the prompt to manually stop butchering often fails regardless of whether you press "Yes" or "No", leading to situations where you receive continuous damage because you cannot stop butchering.

# Steps To Reproduce

1. Load the attached save.

2. Attempt a butchery of the corpses on the plastic sheet. The type of butchery shouldn't matter.

3. When prompted to interrupt catching your breath because of the Tough Zombies, choose to do so.

Optional: Killing the Tough Zombies using the Debug Menu will result in fewer interruptions whilst trying to reproduce the issue.

4. Drop an item from the inventory, or attempt to cast Wooden Shaft then cancel. Successfully casting also does this.

# Expected behavior
When Butchering is interrupted, it will not resume without going back to the corpses and choosing to butcher them.

# Versions and configuration

 - OS: Windows 10 64-Bit
 - Game Version: 0.D-9039-g9c02dee
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Magiclysm

# Additional context
Don't know if it will be of any use, but here's the error message when it tried to butcher something on a different tile:

 DEBUG    : Tried removing item from object which did not contain it

 FUNCTION : item visitable<T>::remove_item(item&) [with T = map_cursor]
 FILE     : src/visitable.cpp
 LINE     : 506

[Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3798295/Test.zip)

If you haven't used Magiclysm before, the Spellcasting menu may not have a key bound to it, so you may need to go into Keybindings and set one before you can use Wooden Shaft to produce the issue.

There may be additional actions that trigger this issue; these are the only two I've found.

**Comment by new02DAY** [comment]
Could this issue on Reddit be related? https://www.reddit.com/r/cataclysmdda/comments/dpdl37/new_driving_ai_is_far_more_bugged_than_before/

**Comment by benjaminmkos** [comment]
I've anecdotally seen this when dissecting and pulping as well. Something strange in the catching breath logic.

**Comment by davidpwbrown** [comment]
Yes, something has changed in the activity resume code at some point, and ive seen sporadic report sof activities that were interrupted then resuming randomly when you start another activity.

Its not related to any specific activity it seems, but in the resume logic itself I bet, Ill take a look.
