### ISSUE TITLE
Can put chardonnay in inventory

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#35235]
# Describe the bug
Put liquid chardonnay from a tin cup in inventory. Is it because it is cold? When moving around it does not spill.

# Steps To Reproduce
1. Find a tin cup of chardonnay
2. Press U to unload
3. Observe the chardonnay is now in your inventory.

# Expected behavior
Should ask my if I want to put it in a container or consume it.
Spill it if it ends up in my inventory

# Screenshots
![image](https://user-images.githubusercontent.com/50166150/68050449-6db80e80-fce5-11e9-9bd8-d2ed78fc7134.png)

![image](https://user-images.githubusercontent.com/50166150/68050461-74468600-fce5-11e9-92f8-d15819b5d3bc.png)

![image](https://user-images.githubusercontent.com/50166150/68050500-84f6fc00-fce5-11e9-8000-bb813ed4b429.png)

This is the tin cup it came from:
![image](https://user-images.githubusercontent.com/50166150/68050625-cab3c480-fce5-11e9-85e4-555734b14781.png)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9040-g859e7e9 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Mining Mod [Mining_Mod],
    Folding Parts pack [deoxymod],
    Simplified Nutrition [novitamins],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    More Locations [more_locations],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Hydroponics [hydroponics],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Bens GF recipes [Tolerate_This],
    Icecoon's Arsenal [ew_pack],
    Cataclysm++ [Cata++],
    Urban Development [Urban_Development],
    Mythological Replicas [nw_pack],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]

# Additional context
N/A

**Comment by wapcaplet** [comment]
Could not reproduce in 0.E-9737-g511ddcb179. Trying to `U`nload Chardonnay (whether cold or not) from a tin cup or a bottle gives me a prompt to pour into a container or on the ground; I cannot pick up the liquid itself.

![image](https://user-images.githubusercontent.com/238395/108453485-cfc4bc00-7227-11eb-9cbf-37e898eb428e.png)
