### ISSUE TITLE
Crash when opening inventory

### ISSUE THREAD

**Issue by RickyVanz** [CleverRaven/Cataclysm-DDA#35237]
# Describe the bug

after i pick some items along the way, when i open the inventory menu the game crashed with Arithmetical Error.

# Steps To Reproduce

1. Pick some items
2. open inventory menu

# Expected behavior

inventory menu opened without crashing the game.

# Screenshots

# Versions and configuration

 - OS: Windows 7 64Bit
 - Game Version: 0.D-9039-g9c02dee
 - Graphics version: Tiles
 - Mods loaded:
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Bens GF recipes [Tolerate_This],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Mythological Replicas [nw_pack],
    Obscure Military Armory [armorytwist],
    DinoMod [DinoMod],
    PKs Rebalancing [PK_REBALANCE],
    Secronom [secronom],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Fuji's Military Profession Pack [fuji_mpp],
    Manual Bionic Installation [manualbionicinstall],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    Sleep Deprivation [sleepdeprivation],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3799462/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3799463/debug.log)
[savefile.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3799469/savefile.zip)

**Comment by DidNotZero** [comment]
Same deal as #35171 & #35210.

**Comment by RickyVanz** [comment]
it could be, because the crash happen right after i take some sodas from starting base's basement..

but i also found some possibility of a typo in item data loading when opening menu related to inventory.

**Comment by AlexanderBodnya** [comment]
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3800434/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3800435/debug.log)
Same, crash on soda can pickup

**Comment by foxboxpdx** [comment]
Same error, but with additional contexts: 
-Examining with 'e'
-Looking at all items in an area with 'V' (both immediately, and after scrolling through a large number of items)
-Trying to bring up the unload screen with 'U'

Been happening with every version since around build 9800.  Does not appear to be affected by mods.
