### ISSUE TITLE
Volume of carrying capacity sets to 0.25 L permanently

### ISSUE THREAD

**Issue by kmullinax** [CleverRaven/Cataclysm-DDA#35245]
Suddenly noticed out of the blue that my total carrying max volume changed to 0.25 L and my "current" carrying volume was 0.10 L, even though I was carrying a lot of stuff.
Dropped everything except what I'm wearing and both stats stayed the same 0.10/0.25L.
Can't pick anything back up because "Destination is full".
Saved game and reloaded with same result.
Save file ZIP is attached.
[Ploodo.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3800027/Ploodo.zip)

**Comment by anothersimulacrum** [comment]
Please follow the template, it's there for a reason.

**Comment by BevapDin** [comment]
The bug can't be reproduce with the given save. It also refers to unknown mods, which are not mentioned in the issue. The game version is not given either. The given save works fine: dropping the armor item with storage reduces the available storage to 0, wearing an item with storage volume 5l increases the available storage to 5l.
