### ISSUE TITLE
Examining gun mods throws "Missing item definition"

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#35254]
# Describe the bug

"Missing item definition"

```
 DEBUG    : Missing item definition: rifle

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1206
```

# Steps To Reproduce

1. Examine gun modification

# Expected behavior
No errors

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9059-gae829af [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Classes and Scenarios Mod [more_classes_scenarios],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Vehicle Additions Pack [blazemod]
]

# Additional context

**Comment by LaVeyanFiend** [comment]
Fixed in #35280, close please.
