### ISSUE TITLE
Glass item recipes are funky and erratic

### ISSUE THREAD

**Issue by Odieman1** [CleverRaven/Cataclysm-DDA#35265]
# Describe the ~~bug~~ inconsistency:

Is this a bug?  I don't know.  It's more or less just inconsistent recipes that have a lot of the same input material (glass shards).  It gave me a bit of a headache but I mostly fixed it, or at least I have the necessary math and info to give someone else an idea of what to do here.

I'd just like to say that, before this fix, 3L glass jars took less material than regular jars.  Even if my idea is terrible there's at least something wrong here.

- 3L Glass Jar - 0.80 lbs
- Glass Bottle - 0.44 lbs
- Glass Pipe - 0.97 lbs
- Glass Jar - 0.33 lbs
- Glass Flask - 0.11 lbs
- Sheet of Glass - 53.30 lbs
- **Shard of glass - 0.12 lbs** (this is our raw material)

Assume 4/1 ratio of raw material to product and we get...

- 3L Glass Jar - 27 shards
- Glass Bottle - 15 shards
- Glass Pipe - 32 shards
- Glass Jar - 11 shards
- Glass Flask - 4 shards
- Sheet of Glass - 1777 shards

_*I've supplemented everything but the glass sheet into the code below, if you decide to use it.
If not, I still have the line and .json bolded so you can find it and fix it however you deem necessary._

Sheets of glass are insanely heavy, and to better fit their current recipe should be around 10 lbs instead of 53.3 lbs.  An entire window frame the size of a small door weighs about 53 lbs at 3/16ths of an inch thick, I used a website to gather this info. [image](https://i.imgur.com/zOo8XIn.png).  That's a bigass pane of glass, and most houses actually use glass half as thick, which should assume half the weight.  [link](https://www.energyswingwindows.com/about-us/news-and-events/27217-what-is-the-thickness-of-glass-used-in-most-residential-replacement-windows.html).

The glass pipe is weird, considering it weighs almost a pound and in-game seems to be more of a crackpipe style thing, rather than an outright full sized bong.  I don't know though, I just see the weight and do the math.

This makes the mirror recipe weird as well, considering a mirror is incredibly light and requires a glass sheet in its recipe.

# Fix

I made a simple fix, it **starts at line 3148 in recipe_others.json**, ends at line 3251.  Forge values have NOT been changed and that's up to you guys if you want to change them.  They seem to follow a non-standard rate anyway so I doubt anyone would notice this sort of thing.

```

  {
    "type": "recipe",
    "result": "jar_3l_glass",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_CONTAINERS",
    "skill_used": "fabrication",
    "difficulty": 7,
    "time": "1 h 30 m",
    "book_learn": [ [ "glassblowing_book", 5 ] ],
    "qualities": [ { "id": "CHISEL", "level": 3 } ],
    "tools": [ [ [ "tongs", -1 ] ], [ [ "pipe", -1 ] ], [ [ "crucible", -1 ], [ "crucible_clay", -1 ] ], [ [ "forge", 150 ] ] ],
    "components": [ [ [ "glass_shard", 27 ], [ "flask_glass", 6 ], [ "jar_glass", 4 ] ] ]
  },
  {
    "type": "recipe",
    "result": "bottle_glass",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_CONTAINERS",
    "skill_used": "fabrication",
    "difficulty": 6,
    "time": "1 h",
    "book_learn": [ [ "glassblowing_book", 5 ] ],
    "qualities": [ { "id": "CHISEL", "level": 3 } ],
    "tools": [ [ [ "tongs", -1 ] ], [ [ "pipe", -1 ] ], [ [ "crucible", -1 ], [ "crucible_clay", -1 ] ], [ [ "forge", 75 ] ] ],
    "components": [ [ [ "glass_shard", 15 ], [ "flask_glass", 3 ], [ "jar_glass", 2 ] ] ]
  },
  {
    "type": "recipe",
    "result": "jar_glass",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_CONTAINERS",
    "skill_used": "fabrication",
    "difficulty": 5,
    "time": "40 m",
    "book_learn": [ [ "glassblowing_book", 4 ] ],
    "qualities": [ { "id": "CHISEL", "level": 3 } ],
    "tools": [ [ [ "tongs", -1 ] ], [ [ "pipe", -1 ] ], [ [ "crucible", -1 ], [ "crucible_clay", -1 ] ], [ [ "forge", 50 ] ] ],
    "components": [ [ [ "glass_shard", 11 ], [ "flask_glass", 2 ] ] ]
  },
  {
    "type": "recipe",
    "result": "flask_glass",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_CONTAINERS",
    "skill_used": "fabrication",
    "difficulty": 4,
    "time": "20 m",
    "book_learn": [ [ "glassblowing_book", 4 ] ],
    "qualities": [ { "id": "CHISEL", "level": 3 } ],
    "tools": [ [ [ "tongs", -1 ] ], [ [ "pipe", -1 ] ], [ [ "crucible", -1 ], [ "crucible_clay", -1 ] ], [ [ "forge", 25 ] ] ],
    "components": [ [ [ "glass_shard", 4 ] ] ]
  },
  {
    "type": "recipe",
    "result": "test_tube",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_CONTAINERS",
    "skill_used": "fabrication",
    "difficulty": 4,
    "time": "4 m",
    "book_learn": [ [ "glassblowing_book", 4 ] ],
    "qualities": [ { "id": "CHISEL", "level": 3 } ],
    "tools": [ [ [ "tongs", -1 ] ], [ [ "pipe", -1 ] ], [ [ "crucible", -1 ], [ "crucible_clay", -1 ] ], [ [ "forge", 5 ] ] ],
    "components": [ [ [ "glass_shard", 1 ] ] ]
  },
  {
    "type": "recipe",
    "result": "mirror",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_TOOLS",
    "skill_used": "fabrication",
    "difficulty": 5,
    "time": "30 m",
    "book_learn": [ [ "glassblowing_book", 5 ] ],
    "tools": [ [ [ "tongs", -1 ] ], [ [ "crucible", -1 ], [ "crucible_clay", -1 ] ], [ [ "forge", 75 ] ] ],
    "components": [ [ [ "glass_sheet", 1 ] ], [ [ "silver_small", 10 ] ] ]
  },
  {
    "type": "recipe",
    "result": "mirror",
    "id_suffix": "from_steel",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_TOOLS",
    "skill_used": "fabrication",
    "difficulty": 2,
    "time": "10 m",
    "autolearn": true,
    "qualities": [ { "id": "HAMMER", "level": 2 } ],
    "tools": [ [ [ "tongs", -1 ] ], [ [ "polisher", 20 ] ], [ [ "crucible", -1 ], [ "crucible_clay", -1 ] ], [ [ "forge", 50 ] ] ],
    "components": [ [ [ "steel_chunk", 3 ] ] ]
  },
  {
    "type": "recipe",
    "result": "pipe_glass",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_TOOLS",
    "skill_used": "fabrication",
    "difficulty": 6,
    "time": "1 h",
    "book_learn": [ [ "glassblowing_book", 6 ] ],
    "qualities": [ { "id": "CHISEL", "level": 3 } ],
    "tools": [ [ [ "tongs", -1 ] ], [ [ "pipe", -1 ] ], [ [ "crucible", -1 ], [ "crucible_clay", -1 ] ], [ [ "forge", 25 ] ] ],
    "components": [ [ [ "glass_shard", 32 ] ] ]
  },

```

# Versions and configuration

Build #9853 0.D

# Additional context

One last side-note: glass shards have a `"byproducts": [ [ "glass_shard", 33 ] ],`
If that means what I think it means, the recipe should just make 34 glass shards with no byproducts, to ease confusion.  As it stands, it looks like you're going through a convoluted process to make a single shard.

I'm only posting this here because @mlangsdorf told me to.

I also tried to make this easy to read, and since it's not really a bug I deviated from the standard template.  I figured the template would make this sort of issue more complicated than it needs to be.  If that's an issue, let me know and I'll re-do it in the standard template.

**Comment by tenmillimaster** [comment]
![image](https://user-images.githubusercontent.com/7764202/68103777-caf6c000-fe9d-11e9-8874-64f3dd7359ad.png)


To add to this: It appears after reading <https://www.nrel.gov/docs/legosti/old/5703.pdf>, you'll need to melt, then process your glass, possibly anneal too. 
This should cost a cool 5.043 * 10^6 BTU per US ton, or 5.559 KJ per g.

**Comment by Rivet-the-Zombie** [comment]
I feel that the mason jar recipes should also require a bit of metal to form the lid.

**Comment by Odieman1** [comment]
Maybe, I'm not really worried about all that.  I'm more or less taking a mathematical approach with respects to game-play.  At the end of the day, with the current system you are going to benefit logistically by making 3L glass jars.  It's slightly off balance and all I'm saying is, it feels wrong.
