### ISSUE TITLE
Crash while picking up items at the start of really bad day scenario

### ISSUE THREAD

**Issue by Sammmmm** [CleverRaven/Cataclysm-DDA#35275]
# Describe the bug
Not sure what causes it, but it seems to be related to cans.  Probably every other Really Bad Day start my game crashes when I'm picking up a random item in the house you start in.  Always when using the "E"xamine key to pick up items.  Always an Arithmetical Error. 

![image](https://user-images.githubusercontent.com/2768751/68079145-f300f900-fda1-11e9-86bd-055741382474.png)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3801149/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3801150/crash.log)

# Steps To Reproduce

1. Start a really bad day scenario in the latest build (#9853).  
2. Move around the house and "E"xamine all cans (of soda or empty) on the ground.  If there is no cans restart.
3. Game crashes on Examine

This doesn't seem to happen if I save and load prior to examining the soda, so I can't provide a save.

# Screenshots

![image](https://user-images.githubusercontent.com/2768751/68079169-8803f200-fda2-11e9-9428-709b4b815199.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-9025-g417c9ca
 - Graphics version: Tiles
 - Mods loaded:  D.D.A, Disable NPC Needs, StatsThroughSkills

# Additional context

**Comment by DidNotZero** [comment]
Has to do with the spawning of "empty" cans.

**Comment by Night-Pryanik** [comment]
Closing as a duplicate.

**Comment by Sammmmm** [comment]
:+1: thanks, I'll follow the other one, this is super annoying, and ruins a lot of good starts.
