### ISSUE TITLE
Crashing while moving around with NPC

### ISSUE THREAD

**Issue by purgatorios** [CleverRaven/Cataclysm-DDA#35273]
# Describe the bug

About every 10 minutes my game crashes to desktop, throwing up a pop-up error message.

# Steps To Reproduce

1. Open attached save.
2. Walk around for a while?  Normal gameplay.
3. Observe crashing.

# Expected behavior

No crashing.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9059-gae829af [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    Faster Stamina Regen [stamina_regen_buff]
]

# Additional context

[Johnsons Station zipped.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3801137/Johnsons.Station.zipped.zip)

[crash and debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3801138/crash.and.debug.zip)

**Comment by mlangsdorf** [comment]
I played for about 15 minutes without a crash.  I don't have the Faster Stamina Regen mod which isn't a mainline mod and might be the culprit.

**Comment by purgatorios** [comment]
Hmmmmm, I'll try a new character without that and see if I can
replicate, thanks
for testing!

**Comment by DidNotZero** [comment]
You don't suppose you tried to open your inventory in some way when it crashed? Drop, wield, eat, and regular menus, basically anything that would view items.

**Comment by purgatorios** [comment]
It was multiple crashes, I don't believe I was generally in-menu.  I'll
just play normally now with more attention to what I'm doing exactly right
before the crash.

**Comment by DidNotZero** [comment]
It's possible that it may have been fixed with #35253. It has only just been merged so I guess it's only a matter of time it is in a build. But I don't guarantee it.

**Comment by purgatorios** [comment]
Hope so!  Been playing for like 10 mins without crashing now, guess I'll
close this issue if it doesn't happen again today.

**Comment by purgatorios** [comment]
I just played for about an hour (recruited an NPC by killing a Jabberwocky which I'd never seen before!), no crashes.  No idea why, but I'll close this for now (I think that's the right procedure?) since even I can't replicate.
