### ISSUE TITLE
Missing item definition for SMG, launcher, etc

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#35283]
# Describe the bug

When scrolling trough the recipes list I got this error:
 DEBUG    : Missing item definition: launcher

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1206

 DEBUG    : Missing item definition: rifle

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1206

 DEBUG    : Missing item definition: shotgun

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1206

 DEBUG    : Missing item definition: smg

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1206

# Steps To Reproduce

1. Open the crafting menu
2. Select an item that concerns guns, for example a gunmod
3. Observe error

# Expected behavior
Show the correct item definition

# Screenshots
![image](https://user-images.githubusercontent.com/50166150/68087511-16d24680-fe57-11e9-89bb-ea095143c5eb.png)

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9062-gb6c286e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
windows 8.1

# Additional context
N/A

**Comment by ymber** [comment]
Fixed in #35280.
