### ISSUE TITLE
Arithmatical error crash

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#35289]
# Describe the bug

Game crashed when pressing V

# Steps To Reproduce

1. Load save file
~~2. Press V~~
~~3. Observe crash~~

Actually, the house where I experienced the crash did not generate the same again when I visited. I do have about 7 null items at the failed bio weapons lab:
![image](https://user-images.githubusercontent.com/50166150/68089843-586dec00-fe6d-11e9-8f14-f08b6e280c5d.png)

I reference the null items because the debug log seems to point to them.

# Expected behavior
Not crash, show the items around me when pressing V

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9062-gb6c286e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Mining Mod [Mining_Mod],
    Folding Parts pack [deoxymod],
    Simplified Nutrition [novitamins],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    More Locations [more_locations],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Hydroponics [hydroponics],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Bens GF recipes [Tolerate_This],
    Icecoon's Arsenal [ew_pack],
    Cataclysm++ [Cata++],
    Urban Development [Urban_Development],
    Mythological Replicas [nw_pack],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3801907/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3801908/crash.log)

https://ufile.io/t90jbozy save file

**Comment by anothersimulacrum** [comment]
This is from a version before 8dfe9694aaadacd539efb7c33e0becc224a3b044, which is supposed to fix this bug. Can you confirm it after this?

**Comment by snipercup** [comment]
Compiling right now. I'll provide more info after testing

**Comment by snipercup** [comment]
Cannot reproduce. I will reopen this issue if I get it again in the latest build. I only got this debug message but object none should not exist in the fist place so
 DEBUG    : Item 'none' with zero volume

 FUNCTION : int item::charges_per_volume(const volume&) const
 FILE     : src/item.cpp
 LINE     : 686
