### ISSUE TITLE
Implement liquid evaporation.

### ISSUE THREAD

**Issue by arijust** [CleverRaven/Cataclysm-DDA#35288]
**Is your feature request related to a problem? Please describe.**  
Spilled liquids stay around until you use mop to remove them.

**Describe the solution you'd like**  
Spilled liquids slowly evaporate.

**Describe alternatives you've considered**  
Make some items to directly remove liquids from floor.
For example vacuum cleaner with ability to contain certain amount of any liquid.
Which could allow for distillation to clean them.

**Additional context**  
Write function, which removes one unit of spilled liquid per certain amount of time.

**Comment by Lamandus** [comment]
if we go so far, I would also consider making it somewhat dependend on weather (sun drying? or even Raining), temperature (hot -> faster). And underground, because soil and grass shouldn't be affected by the used liquid too much, since most would enter the soil anyhow.

**Comment by arijust** [comment]
I wouldn't be opposed to that idea either. 
However, I would prefer to make it work first.

**Comment by tivec** [comment]
> Make some items to directly remove liquids from floor.
You can already use a mop for this.

I do like the idea of evaporation over time though. Wouldn't be *too* difficult, I think.
