### ISSUE TITLE
CRIT Expansion Mod: Energy Weapons foul despite not using any kind propellant other than Lorentz Force for plasma weapons.. 

### ISSUE THREAD

**Issue by EldritchSigma** [CleverRaven/Cataclysm-DDA#35290]
# Describe the bug

Using the CRIT mod, I found myself an Energy Rifle which is just a more powerful laser rifle. After firing a couple dozent bursts with it the gun got the fouling tag in its description. I am pretty sure energy weapons would not suffer through fouling. Worse of all. Cleaning it via pipe cleaner or gun repair kits is impossible. Other weapons affected are: The plasmacutter, any of the other energy weapons from CRIT and PK Rebalance BFG. All of which are beam weapons or plasma weapons. All of which should not suffer from fouling. The base game vanilla weapons are affected aswell after a quick test with a debug character.

# Steps To Reproduce

1. Go in with a character.
2. Acquire one of the CRIT mods weapons.
3. Acquire UPS and energy source
4. Fire said gun a couple dozent times into a horde of zombies.
5. Behold, you got a fouling tag on your energy weapon, THIS INCLUDES VANILLA/NONE MODDED ENERGY WEAPONS
6. Attempt to use: Gunsmith Repair Kit, Firearm Repair Kit, Pipe Cleaner: "You don't have anything to use this on" or "You cannot repair your weapon."

# Expected behavior

Energy weapons should not foul due to "blackpowder" being used since there is no propellant. Sure they should have some other mechanic making them require maintenance of some sort, e.g. having to swap out the capacitors every so often. But fouling should not affect those guns. Atleast they should be cleanable. Which they are not. Pipe cleaner is not doing anything nor are both of the gun repair kits.

# Screenshots

https://media.discordapp.net/attachments/585919978251747343/640634112012451841/This_should_not_rot.jpg?width=252&height=657

Proof of Vanilla Energy weapons being affected. Same Build, same mods loaded:

https://imgur.com/a/8NJP6UK

# Versions and configuration

 - OS: Win 7
 - Game Version: Current Build: 9855
 - Graphics version: Tiles, Dead People 
 - Mods loaded: PK Rebalance, CRIT Expansion, Aftershock, Magiclysm, Arcana

# Additional context:

Vanilla energy weapons ARE in fact affected aswell. The mods loaded should not affect the vanilla energy weapons. Hence I assume that one flag for "no fouling" was not properly applied to the energy weapons.

**Comment by EldritchSigma** [comment]
Alright quick update: I tested the vanilla A7 Laser Rifle as of now. Fired a couple hundred bursts into a spongy enemy (shoggoth). Then checked if it got the fouling tag. Yes it does. Seems like that "flag" or whatever is called that prevents fouling was not applied to energy weapons. Or for some odd reason the "ammo" of these guns are counted as blackpowder ammo for some reason.

**Comment by EldritchSigma** [comment]
Actually now that I have had some time to play arround with guns. That fouling mechanic seems to apply to alot more than just energy guns when it really shouldnt. Example: I have found a mint condition gun inside a lab. It has the fouling tag. I am completely unable to clean it with the suggested methods in the PR. Either I am doing something wrong and do not understand how to apply pipe cleaner or the gunsmith/firearm repair kit to guns to clean them or the function is just currently bugged. The only weapons that did not foul so far are rivtech weapons.

**Comment by esotericist** [comment]
Do you have the `"NON-FOULING"` flag on the weapons?
