### ISSUE TITLE
Two Hubs 01

### ISSUE THREAD

**Issue by Brytenwalda** [CleverRaven/Cataclysm-DDA#35297]
# Describe the bug

Creating a normal map in the Build 9855, I've noticed that the game created two Hubs on the map, and quite close to each other at that, less than 200 tiles away. 

# Steps To Reproduce

1) Create a new map.
2) There will be two hubs on the map. 

# Expected behavior

I would expect to see just one hub.

**Comment by anothersimulacrum** [comment]
I don't think this is an issue - at least, it's not the issue it claims.
An overmap is 180x180 tiles, only one hub will spawn per overmap.
Globally unique things would be great, but not something that'd be good for gameplay until there are problems that are solved.
