### ISSUE TITLE
No acid zombies mod doesn't prevent acidic zombies

### ISSUE THREAD

**Issue by Brytenwalda** [CleverRaven/Cataclysm-DDA#35298]
# Describe the bug

I've been playing the Build 9855 with the No Acid Zombies mod on, and yet I've encountered an acidic zombie, a wandering spawn it seems. 

# Steps To Reproduce

Just create a new game with the mod on and it should eventually appear. 

# Expected behavior

This mod should delete said zombie.

**Comment by Night-Pryanik** [comment]
Please fill in the template, it's here not without a reason.
