### ISSUE TITLE
Crash occasionally when viewing bookcases

### ISSUE THREAD

**Issue by Nymall** [CleverRaven/Cataclysm-DDA#35294]
# Describe the bug

Occasionally, when viewing a tile using the numpad + e and pressing the 3(se), game will crash.

# Steps To Reproduce

1. Find a bookcase,
2. View using e.
3. Crash.

# Expected behavior

Not to crash.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9062-gb6c286e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Crazy Cataclysm [crazy_cataclysm],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Fuji's Military Profession Pack [fuji_mpp],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3802123/config.zip)
# Additional context

This is hard to produce. I've managed to get it 2 times within 15 minutes, but revisiting both crash sites I have been unable to reproduce.

**Comment by anothersimulacrum** [comment]
You should update your game, this has already been fixed

**Comment by DidNotZero** [comment]
I wouldn't say it's fixed yet as build 9857 still crashed when I tried to pick up what looked like a jar.

**Comment by anothersimulacrum** [comment]
Bugged items will still exist, but new ones will not be created.
Because new bugged items will not be created, this issue should be closed.

**Comment by DidNotZero** [comment]
Can't say previously created items will exist in new saves.

**Comment by davidpwbrown** [comment]
@anothersimulacrum closing as per your knowledge of this issue.
