### ISSUE TITLE
Inconsistent plot tilling using zones vs using digging stick

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#35291]
# Describe the bug

When putting down a farm plot zone and using O followed by 'till farm plot' (in the dark), the player just moves a space and nothing happens. When using O followed by 'farm plots' in the dark, it says 'it's to dark to do this now'. Meanwhile, I can activate my digging stick to till plots and plant seeds in the dark just fine.

# Steps To Reproduce

1. Make a plot farm zone using some seeds
~~2. Wait until dark~~
3. Press O followed by t to till farm, observe nothing happens (in day or night
4. Press O followed by m to farm plots, observe it says it's to dark
5. Activate a digging stick and upturn earth and observe it works fine.

# Expected behavior
Eighter allow automatic farm plotting in the dark using zones, or disallow upturning earth using a digging stick.

# Screenshots
In the dark:
![getvehicleonrails](https://user-images.githubusercontent.com/50166150/68090892-a0930b80-fe79-11e9-806a-17dc232c72a1.gif)

In daylight:
![Tilling_farm_zone](https://user-images.githubusercontent.com/50166150/68091020-092eb800-fe7b-11e9-96ca-912b1391b192.gif)

Farm plot works, but it does not plot every field:
![Tilling_farm_plot](https://user-images.githubusercontent.com/50166150/68091070-8fe39500-fe7b-11e9-96ba-b8d9bbb9cd96.gif)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9062-gb6c286e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Mining Mod [Mining_Mod],
    Folding Parts pack [deoxymod],
    Simplified Nutrition [novitamins],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    More Locations [more_locations],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Hydroponics [hydroponics],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Bens GF recipes [Tolerate_This],
    Icecoon's Arsenal [ew_pack],
    Cataclysm++ [Cata++],
    Urban Development [Urban_Development],
    Mythological Replicas [nw_pack],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]

# Additional context
N/A

**Comment by snipercup** [comment]
Update, it tilling a plot does not work in daylight eighter

**Comment by davidpwbrown** [comment]
I'll look into this. problem is the multi-farm activity and the old zone tilling use different methods now.
Maybe old zone tilling can go. but ill investigate
