### ISSUE TITLE
Cooked Mutant Meat/Scrap of Meat require no tools.

### ISSUE THREAD

**Issue by AndrXi** [CleverRaven/Cataclysm-DDA#35307]
# Describe the bug

The cooking recipes for "Cooked Mutant Meat" and "Cooked Scraps of Mutant Meat" require no tools that regular meat and scraps do.

# Steps To Reproduce

1. Gain acess to said recipes and ingridients.
2. Cook.

# Expected behavior

It should have the same requirements as the non-mutant counterparts.

# Screenshots

Cooked Mutant Meat.
![Bug Evidence 1](https://user-images.githubusercontent.com/44873249/68114627-69127680-feee-11e9-88d6-d34b2117170b.png)
Cooked Scraps of Mutant Meat.
![Bug Evidence 2](https://user-images.githubusercontent.com/44873249/68114658-7d567380-feee-11e9-9054-8a73df0bb876.png)

# Versions and configuration

 - Game Version: 0.D-9090-gd1961e6

# Additional context

The "Mutant Tallow" and "Mutant Lard" seem to be working like they should.
![Bug Evidence 3](https://user-images.githubusercontent.com/44873249/68114855-f5249e00-feee-11e9-92a5-e3329c597d36.png)
![Bug Evidence 4](https://user-images.githubusercontent.com/44873249/68114860-f6ee6180-feee-11e9-8043-1b96cfc0714d.png)

**Comment by LaVeyanFiend** [comment]
Seems like an error with copy-from, waiting on a build with #35241 to see if this happens with cooked human meat as well before pushing my fix.
