### ISSUE TITLE
Pulp/smash zombie corpse bug (when auto pulp is enabled some corpses make your game crash)

### ISSUE THREAD

**Issue by TheGoatGod** [CleverRaven/Cataclysm-DDA#35314]
# Describe the bug
Crash when pressing s key when next to dead zombie (it worked before on the same save)
sometimes it gives you directions to smash/pulp
happens with all zombies

# Steps To Reproduce

1. find and kill zombie
2. press s
3. keep doing so untill ctd

# Expected behavior

i should get directions on where to smash/pulp not crash
it shouldnt crash when pulping

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-9090-gd1961e6
 - Graphics version: Tiles
 - Mods loaded: ["dda",  "no_npc_food",  "aftershock",  "magiclysm",  "ArmUpPAUtil",  "ArmUpSurvEx",  "afursuit",  "bioco",  "Bootleg_Walkers",  "SD_Magcrafting",  "craftgp",  "antifunguskit",  "light_ammo",  "More_Survival_Tools",  "MST_Extra",  "makeshift",  "More_Armors",  "Realistic_Fridge_Size",  "space_heater",  "can_mod",  "DracoDogMod",  "DracoPigMod",  "modular_turrets",  "mutant_animals",  "Salvaged_Robots",  "alt_map_key",  "Cata++",  "hydroponics",  "Mining_Mod",  "mutant_npcs",  "whaleys_tallbuild",  "more_classes_scenarios",  "poor_student",  "vamp_stuff",  "Arcana",  "vamp_stuff+arcana",  "P_Caches",  "Dorf_Life",  "more_locations",  "morlock_village",  "No_Rail_Stations",  "randomized_mall",  "water_towers",  "deoxymod",  "blazemod",  "Heavy miners",  "Tanks",  "jury_rigged_robots",  "no_olg_guns",  "no_rivtech_guns",  "national_guard_camp",  "RL_Classes",  "Ex_Scenarios",  "fuji_mpp",  "More_Military",  "Mutation_Changes",  "Nonperishable_Overhaul",  "safeautodoc",  "novitamins",  "StatsThroughSkills",  "crt_expansion",  "cityside",  "FujiStruct",  "recruitment_options",  "dried_fruits",  "stamina_regen_buff",  "Battery_Overhaul_Legacy_Mode",  "my_sweet_cataclysm",  "fast_healing",   "Medieval_Stuff", "necro_find" (properly too many mods)

# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3810419/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3810420/debug.log)

[Prairieburg.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3814848/Prairieburg.zip)
[Park View.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3814861/Park.View.zip)
[options.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3814876/options.zip)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3805651/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3805652/crash.log)
(old world^)
![smash crash](https://user-images.githubusercontent.com/56883303/68150085-eb268d80-ff36-11e9-99f8-0392aaf7acd8.png)

**Comment by TheGoatGod** [comment]
i noticed that if i have auto pulp on it happens, i havent ran into the bug when auto pulp is off

**Comment by esotericist** [comment]
So far, I've been unable to reproduce this. I'm not really sure what else to try at this point. :(

**Comment by wapcaplet** [comment]
Cannot reproduce in 0.E-9737-g511ddcb179 with auto-pulp enabled. Pulping (and auto-pulping) corpses is something players do all the time, so we almost surely would have heard about it again in the past year if it were still an issue.

If anyone can provide a reliable reproduction case, please comment and ping me, and we can reopen it.
