### ISSUE TITLE
Crafting skill requirement display glitch

### ISSUE THREAD

**Issue by levstk** [CleverRaven/Cataclysm-DDA#35336]
# Describe the bug

The crafting requirements displays the skill requirement in both primary and other skills lines for items that only use one skill.

# Steps To Reproduce

1. Open the crafting menu
2. Look at one of the crafting recipes that only uses one skill.

# Expected behavior

It should display NONE or some such as the "other skills" requirement.

# Screenshots

![Capture10](https://user-images.githubusercontent.com/42700492/68241036-41b2cb00-000e-11ea-9fdf-ac14d071ccae.PNG)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9137-g1e35a58 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

# Additional context

N/A

**Comment by akirashirosawa** [comment]
It is because of this f89eba8aceed2c1d43ad58837eebb2f6deff29c0
