### ISSUE TITLE
Loaded thread can’t craft

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#35346]
# bug description 
Thread loaded into bone needle. No loose thread. Went to craft boot quiver couldn’t craft. Unloaded bone needle and can now craft boot quiver. 

# Steps To Reproduce

I described it in bug description. Sorry I’m on phone. 

# Expected behavior

If thread needs to be unloaded to craft why would we even load needles?

# Screenshots

**If needed I’ll replicate this bug in a more appropriate format. 

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by ZhilkinSerg** [comment]
That is not a bug.
