### ISSUE TITLE
Aero Evaporator CBM power usage

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#35348]
# Describe the bug

Aero-Evaporator takes 720kJ to activate. 

# Steps To Reproduce

1. Make a bionic sniper, start with evaporator and mark 2 power storage. 
2. No way to activate starting profession CbM.

# Expected behavior

Don’t start with CBMs you can’t use. 

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

**Comment by AlexMooney** [comment]
I've solved this with https://github.com/CleverRaven/Cataclysm-DDA/pull/35258.
