### ISSUE TITLE
Aquatic Vehicle has a chance to spawn halfway inside the Boat Rental Building

### ISSUE THREAD

**Issue by Odieman1** [CleverRaven/Cataclysm-DDA#35357]
# Describe the bug

The half boat half car vehicle you can rarely find behind the boat rental place, it has a chance to spawn partially inside the boat rental place.  I didn't realize it at first as a bug, but thinking back on it, it probably was.

# Steps To Reproduce

This may be tricky as the points used in spawning the boat may be different from time to time.

1. Find a boat rental that has the aquatic vehicle as a spawned vehicle. 
2. Observe the wall, is it destroyed?  If yes, it used the spawn location that is problematic.
3. Not destroyed?  Repeat step 1 and 2.

# Expected behavior

I'd say the boat shouldn't spawn inside the building but maybe this is somehow intended behavior.

# Screenshots

No screenshot but I have made a [nice microsoft paint sketch](https://i.imgur.com/B43yrME.png) to display the problem.

# Versions and configuration

 - Game Version: [I think Build #9859]
 - Graphics version: [Undead People]
 - Mods loaded:
    Dark Days Ahead [dda],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Cars to Wrecks [cars_to_wrecks],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    No Survivor Armor [no_survivor_armor],
    No Ants [No_Anthills],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Fuji's Military Profession Pack [fuji_mpp],
    Manual Bionic Installation [manualbionicinstall],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    Sleep Deprivation [sleepdeprivation],
    SpeedyDex [speedydex]

# Additional context

When I first saw this, I didn't think it was a bug.  Thinking back on it, it probably was.  If I had the same character, I would have provided screenshots.

**Comment by Night-Pryanik** [comment]
I debug-spawned 20 boat rentals (`boat_rental` overmap location), and haven't observe any such issue. We need the exact list of mods you're using.

**Comment by Odieman1** [comment]
@Night-Pryanik Updated my mod list, keep in mind I was too dumb to understand how to generate a report before but after some gracious hand-holding I've got it down 👍

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed for more than a half-year.
