### ISSUE TITLE
NPC reading activity segfault

### ISSUE THREAD

**Issue by Vollinger** [CleverRaven/Cataclysm-DDA#35352]
# Describe the bug
NPC follower that was asked to read a book will crash the game if you take the book from his inventory or save/load occurs before he finishes reading a chapter.

# Steps To Reproduce
1. _Recruited starting NPC with raw charisma._
2. _Asked him to read about High Explosives._
3. _Saved and quit._
4. Load the attached world, wait about five minutes, game crashes with:
`src/item_location.cpp:97 [void item_location::impl::ensure_unpacked() const] item_location lost its target item during a save/load cycle`

**Alternatively**
4. Load the attached world, ask him to stop his current activity.
5. Ask him to read about High Explosives again.
6. Trade the High Explosives book off him using the trade dialog.
7. Wait ten minutes, game crashes, no debug message this time.

# Expected behavior
NPCs should keep proper track of their books in savefiles and cuss out shifty players who try to take books they're currently reading.

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 8a44139 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3812791/save.zip)
Doesn't seem to be a recent bug, all of my mystery builds from 2-3 weeks ago also segfault.

**Comment by davidpwbrown** [comment]
I can stop it crashing, I can make the NPC bail out of the activity if the item_location goes missing ( through trading etc )
What I cannot do is stop the debugmsg or the failure to re-find the item_location after a save/load cycle, @ifreund may have some insights into that area when they have some time, but other than that, im stumped on it tbh, item_location stuff is .... beyond me I think.
