### ISSUE TITLE
Some faulty bionics have wrong descriptions

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#35369]
# Describe the bug

bio_nostril, bio_pokedeye and bio_thumbs all claim to increase encumbrance by one or two in case of bio_thumbs, but in reality they increase encumbrance by 10 points. 
Its hard to realise without looking into game files, because player menu refuses to properly show encumbrance from bionics, and you dont get to see real incoming encumbrance when instaling the bionic, because its almost impossible to get this faulty bionic as an item, and when you do get it, is probably already taken out from your body. 

For this reason bio_stiff should tell its exact real encumbrance in its description too

**Comment by Fris0uman** [comment]
So do we edit the description to say 10 encumbrance or do we edit the encumbrance to be 1?

**Comment by SirPendrak** [comment]
I think leave encumbrance at 10 and change descrieptions of theese 4 bionics. 
1 encumbrance is completly non-noticeable, would not change gameplay at all and theese faulty bionics should be a burden. 10 enc. is mildly noticeable anyway.
