### ISSUE TITLE
Accidentally looted a Gun Safe

### ISSUE THREAD

**Issue by TKTKO** [CleverRaven/Cataclysm-DDA#35374]
# Describe the bug

Found a Gun Safe in a basement, used Loot Zones to pile up everything from the rest of the basement. Used 'g' to pull the Gun Safe towards the stairs and through the cell containing the rest of the salvage. When the Gun Safe crossed, it dropped the gun contained within and filled itself with some of the salvage. I did not open the Gun Safe in advance.

# Steps To Reproduce

Use 'g' to pull a Gun Safe over a cell full of items. The contents of the safe should drop and be replaced with contents from the cell.

# Expected behavior

The Gun Safe contents should not drop to the floor. The Gun Safe should not fill with the contents of any cell it is moved through.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9181-g73a137e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Armor Up! PA Utilities [ArmUpPAUtil],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Bens GF recipes [Tolerate_This],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Boats [boats],
    MST Extra [MST_Extra]
]

**Comment by ThomasLinkin** [comment]
that's a nice bug, seriously. but still, we don't want it.

**Comment by Mr-Badman** [comment]
As of O.E 11005, bug still replicatable through the same behavior. Drag safe over an item on the ground and it will eject the safe's contents, replacing it with the items it moved to.
