### ISSUE TITLE
Camp Bulletin Board Menu Delay

### ISSUE THREAD

**Issue by TKTKO** [CleverRaven/Cataclysm-DDA#35375]
# Describe the bug

Opening the Bulletin Board Menu in a Camp takes several seconds. (Timed repeatedly, 7 seconds on average)

# Steps To Reproduce

Start a camp, open Bulletin Board Menu to assign a job to an NPC.

# Expected behavior

Menu should load faster.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9181-g73a137e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Armor Up! PA Utilities [ArmUpPAUtil],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Bens GF recipes [Tolerate_This],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Boats [boats],
    MST Extra [MST_Extra]
]

# Additional context

Processor Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz 4.20 GHz
Installed RAM 16.0 GB

**Comment by Zireael07** [comment]
Hmm, as a first shot I would try to see if the problem also occurs in an unmodded game.

**Comment by davidpwbrown** [comment]
Can I have a savegame pls, to test to see if #35379 fixes it ( albeit with a slight alteration to where items are stored perhaps )

**Comment by TKTKO** [comment]
Issue is no longer present as of Build 9873.
