### ISSUE TITLE
About the actual limit of 4096 items per tile

### ISSUE THREAD

**Issue by DMFan79** [CleverRaven/Cataclysm-DDA#35398]
ref. https://github.com/CleverRaven/Cataclysm-DDA/issues/20483

**Is your feature request related to a problem? Please describe.**  

Lately I've been having an issue regarding the auto-sorting mechanic. I've amassed several hundreds rags, kevlar patches, leather patches and so on and I finally hit the 4096 items per tile limit. The dresser I've selected as storage for spare parts sits around 1500/2000 volume, but the sorting function simply goes on a loop because it can't put any more objects inside the pile. I have to manually stop the process and start removing stuff from the dresser and move it somewhere else.

****Describe the solution you'd like****  

I know, I shouldn't be such a hoarder and I'm actively trying to stop picking stuff up. I've noticed however that items like nails, gold, silver and such are written in the code like a single object. Is there a specific reason you've chosen to not do the same with rags and such? I mean, do we really need to keep track of, for instance, the damage a piece of rag has received?

****Describe alternatives you've considered****  

If you disagree with my suggestion, I believe it would be useful to take a look at the actual sorting function. The loop bug should be addressed, when the limit has been reached, the sorting should stop or at least skip that item and go to the next one. Also, It would be helpful to change the function to use other tiles, if available for sorting, for splitting stacks once the limit on a single tile has been reached. At the moment it just loops forever.

**Comment by ZhilkinSerg** [comment]
Changing items like rags to use stack size (like nails do) could be not a trivial task.

You can [compile](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING.md) game with increased limits in the meanwhile:

https://github.com/CleverRaven/Cataclysm-DDA/blob/1bb08dda5a21ca0681ef2e7587f2aaad928e6bde/src/game_constants.h#L25-L28

**Comment by DMFan79** [comment]
> 
> 
> Changing items like rags to use stack size (like nails do) could be not a trivial task.
> 
> You can [compile](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING.md) game with increased limits in the meanwhile:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/1bb08dda5a21ca0681ef2e7587f2aaad928e6bde/src/game_constants.h#L25-L28

It's not my intention to minimize the effort to apply this change. I just think that, if there's not a strong reason to have them as multiple objects, the game could greatly benefit with the change.

Kevin gave a solid answer regarding the limit, I'm going to adapt for the moment, without changing it.

**Comment by Night-Pryanik** [comment]
You're actually mixing several issues in one, and that's not very good. 
First is a bug with activity looping.
Second is a suggestion about making rags stack like nails or gold.
And finally, both of these issues have almost nothing to do with the actual limit of items in a tile.

**Comment by DMFan79** [comment]
Actually I have mixed nothing. Once I encountered the bug I searched for the reason behind it and discovered the thread I've linked on the top. Without the limit I wouldn't have made the suggestion to turn rags into a single stackable object. My suggestion could solve the matter and at the same time benefit the game. I've mentioned the bug as an alternative following the template. If the suggestion will be considered invalid, I'll close this thread and open another one about the bug.

**Comment by RDru** [comment]
> 
> Changing items like rags to use stack size (like nails do) could be not a trivial task.
>
I once tried changing something to ammo type and it worked, it changed from separate items to stack on current save. 

I'm also encountering this limit a lot. It's not hard when you are a hoarder :D

**Comment by kevingranade** [comment]
The sorting loop might have this bug, the remainder is unrelated.

**Comment by davidpwbrown** [comment]
Cannot reproduce the activity looping part anymore.
Fill up the destination loot square so its overflowing, then place an unsorted over all of it, perform activity, it stops immediately, as the target tile is full up.

Because it has the check for free space on the target tile in the activity.
