### ISSUE TITLE
Blind/in darkness crafting, sewing and repairing

### ISSUE THREAD

**Issue by Kenan2000** [CleverRaven/Cataclysm-DDA#35406]
**Is your feature request related to a problem? Please describe.**  
In real life we are capable of crafting, sewing, cooking and doing all sorts of manual activities, that's how visually impaired and blind people work and live as well, it is possible to do a lot of similar crafting-related activities blindfolded

I find it kinda weird how we are unable to craft and sew and repair at all in darkness or when blinded/blindfolded, that is not realistic considering that we are striving to make the game as realistic as it can get

**Describe the solution you'd like**  
Add an ability to craft, sew and repair in darkness albeit at a greatly decreased progress speed.

**Describe alternatives you've considered**  
Add an ability to craft, sew and repair in darkness albeit at a greatly decreased progress speed only after reaching a certain skill level.

**Additional context**  
None.

**Comment by snipercup** [comment]
idk about repairing, but if you can come up with some recipes that should have their dark craftable flag set to true, that would help and we can discuss those.

**Comment by Kenan2000** [comment]
@snipercup you mean adding new recipes that can be dark craftable?My idea is making all items dark craftable but depending on player skill and at a greatly reduced speed, like 3 or 4 times slower than with lights on, this number may decrease with increased skill level

**Comment by snipercup** [comment]
Some items cannot be crafted in the dark, im afraid that the survivor might get hurt when attempting to craft using a heat source (welder, soldering iron, forge) in the dark.

I don't know what penalties are applied when dark craftable is set to true. I suppose a longer craft time and double the regular skill is acceptable.

**Comment by Kenan2000** [comment]
Oh wow that's an awesome idea you got there, a chance to injure yourself while crafting using heat sources that works like diminishing returns with increased skill level, we can go really far with this idea

**Comment by IIverner** [comment]
Players can't use unremembered formula in the dark. He needs light source.

**Comment by IIverner** [comment]
Maybe some variant or CBM allows players to read books and use formula in the dark.

**Comment by Kenan2000** [comment]
The point i'm trying to make is that yeah, indeed, it might sound as a not really realistic thing that ANYTHING can be crafted in darkness, but in fact - it is true if one has been crafting the same object with a light source for hundreds of times (a very high-skilled person), it should be doable even if he has a chance to harm himself during the process

The **skill level should be tied to the ability to craft in darkness**, that's what i propose, with much higher skill level crafting in the dark should be possible with little to no harm and maybe even only a bit slower than with a light source

It is possible to do pretty much anything in darkness that requires manual work, but whether he harms himself, how fast he's gonna craft the object - all of this depends on the skill of the person. 

There are indeed blind people working with wood, sewing, fixing vehicle parts, doing some tinkering and manual construction, there are videos of people assembling and disassembling weapons blindfolded - of course they must have had months of repeated practice but that definitely **does not mean that it's plain impossible** 

For example, imagine if you are stuck in a house, you are surrounded by zombies in complete darkness, your machine gun jams, your only proper way to get out of there alive is to quickly clean your gun in the darkness, otherwise you're gonna die - that's how survival works, do seemingly impossible and absurd things to survive by **any means necessary**

**Comment by kevingranade** [comment]
This is a total non-starter, your reasoning is specious.
