### ISSUE TITLE
Bleach spawn randomization in science labs seems erroneous

### ISSUE THREAD

**Issue by Nekatydaerla** [CleverRaven/Cataclysm-DDA#35416]
# Describe the bug

Too many bleaches spawn with only 2 charges. Attached a screenshot from visiting 3 science labs with a debug character and looting all the bleach I could find. 3 or 4 are zombie scientist drops  - used "Kill All Monsters" to make game run quicker, rest are lab spawns.

# Steps To Reproduce

1. Go to science labs.
2. Search for bleach.

# Expected behavior

Distribution of charges is random.

# Screenshots
![2019-11-09 11_08_46-Cataclysm_ Dark Days Ahead - 0 D-9234-g5a117d8](https://user-images.githubusercontent.com/41083582/68522121-9c844500-02e2-11ea-8c8b-0fc7321b83ca.png)

# Versions and configuration

- OS: Windows
- OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9234-g5a117d8 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

Windows 7 SP1

# Additional context

Newer 1-floor labs don't seem to have this issue, although I didn't test them as much.
Locations other than science labs might be affected - while playing my non-debug character for hours I felt like there were only 2-bleaches around.

Ammonia seems to work properly, as seen in screenshot.

**Comment by RoyBerube** [comment]
I've noticed bleach with only 2 charges in my current game. No full jugs at all - always just 2 charges in a gallon jug. It makes it hard to make superglue.

This is without going into a lab yet.

**Comment by Funguss** [comment]
It's ammonia too, and includes all spawns as far as I can tell. Roy, you can make superglue with blob globs too, look around for a slime pit.

**Comment by dissociativity** [comment]
I seem to find this issue too with pretty much any bleach spawns, it's odd.
Ammonia too as the poster above said.

**Comment by RDru** [comment]
This is weird
`      { "item": "bleach", "prob": 20, "charges-min": 2 },`
2 and more works - it randomizes from 2 to 30
`      { "item": "bleach", "prob": 20, "charges-min": 1 },`
always spawns 2 charges
