### ISSUE TITLE
Cutting up Chitin armor gives more chitin than used to create it

### ISSUE THREAD

**Issue by SpellingSword** [CleverRaven/Cataclysm-DDA#35423]
# Describe the bug
Cutting up any part of chitin armor returns more chitin chunks than the amount necessary to create it in the first place. Particularly egregious with torso armor. 

Essentially grants infinite chitin.

# Steps To Reproduce

1. Make chitin armor
2. Cut it up

# Expected behavior

Cutting up armor doesn't result in excess material

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-8876-g35ce4d5 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by RoyBerube** [comment]
Can confirm. Chitinous armor takes 15 chitin to make. Cutting it up yielded 70 chitin.

**Comment by jnewl** [comment]
I’m thinking this is because chitinous armor is pretty big at 17 and a half liters and cutting stuff up gives materials from volume. Not sure what to do about it though, other than either increasing the cost or reducing the volume, and both of those don’t make any sense.

**Comment by anothersimulacrum** [comment]
This is the same issue as a few other ones, the problem here it that butchery return is a product of volume, not weight.

**Comment by KorGgenT** [comment]
possible suggestion for fix: increase the cost of crafting chitin armor to be slightly more than what you get by cutting it up

**Comment by capSAR273** [comment]
From testing, these are the current values for cutting up chitin armor:

helmet_chitin: Yields 8-10, costs 5
armor_chitin: Yields 67-70, costs 15
boots_chitin: Yields 15-17, costs 8
armguards_chitin: Yields 8-10, costs 4
gauntlets_chitin: Yields 5-7, costs 4

The yields vary by a few each time, I tested this with max skills cutting up 10 pieces each. The costs could be changed to:

Helmet: 12
Armor: 72
Boots: 20
Arm-guards: 12
Gauntlets: 10
