### ISSUE TITLE
Using item migrations for generic_x mods

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#35427]
**Is your feature request related to a problem? Please describe.**
Generic guns keeps getting out of date and when we give electronics and chemistry and such the same level of depth later down the line any generic_x mods people want to make for them will have the same problem.

**Describe the solution you'd like**
Generic item mods should define their own items and use item migration instead of blacklists. This way there would be no need to change itemgroups as whatever they spawn in core will be automatically genericized by the migrations.

**Describe alternatives you've considered**
A system for items inheriting a `simplifies_to` field from base items was discussed but it would be a lot of invasive data changes and some items would have to be special cases anyway.

**Additional context**
See #35359.
A new generic guns using item migrations may not be compatible with the old generic guns so we'd want to cut the old one after 0E.

**Comment by esotericist** [comment]
Still in progress.

**Comment by ymber** [comment]
With generic guns finished we can call this done now.
