### ISSUE TITLE
Missile Silo has the same area underground as it does topside.

### ISSUE THREAD

**Issue by mkikt4743** [CleverRaven/Cataclysm-DDA#35439]
# Describe the bug

Underground levels of missile silo are exactly the same as aboveground

# Steps To Reproduce

1.Go to a missile silo
2.Go 1 z-level down

# Expected behavior

The missile silo should have lower floors and a missile.

# Screenshots

![Missle](https://user-images.githubusercontent.com/56452763/68538510-793db200-0343-11ea-99e6-623d4a07fa3f.PNG)
![missile underground](https://user-images.githubusercontent.com/56452763/68538512-8064c000-0343-11ea-9730-a183177990f7.PNG)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-9280-g86b3adc
 - Graphics version: Tiles
 - Mods loaded: DDA, C.R.I.T Expansion, Makeshift Items Mod, More Survival Tools, Alternative Map Key, Vehicle Additions Pack, Roadheader and other mining vehicles, Stats through Skills, Icecoon's Arsenal

# Additional context

Silo was generated before version described

**Comment by Night-Pryanik** [comment]
This was fixed in #34892.
There is nothing we could do with locations generated in pre-fixed versions. I suggest you update to latest experimental and check some other silo.
