### ISSUE TITLE
Refugee Center NPC's Teleport After Handing in Quest

### ISSUE THREAD

**Issue by benjaminmkos** [CleverRaven/Cataclysm-DDA#35430]
# Describe the bug

Upon handing in the "Kill Bandits" quest to the Old Guard Representative a new NPC "Hunter" is spawned in the southwest corner of the refugee center. Most of the other refugee center NPC's who were previously there get teleported to the road outside of northwest wall of the refuge center. 

This "Hunter" had not been there before, I assume this "Hunter" in the refugee center is either a new NPC who got added in a recent update or is spawned upon completion of the "Kill Bandits" quest.

# Steps To Reproduce

1. Go to a refugee center and look at everyone happily standing around in the southwest corner.
2. Get the "Kill Bandits" quest from the Old Guard Representative in the southeast corner of the refugee center.
3. Complete and turn in the "Kill Bandits" and accept the next quest.
4. Go back to the southwest room of the refugee center.

# Expected behavior

Refugee Center NPC's should not be teleported onto the side of the road, excepting the very slim chance that this is actually the expected outcome of the "Kill Bandits" quest. I talked to a couple of the NPC's who were teleported and none of them had any dialogue referencing this movement.

# Screenshots

![cddarefugeecenterbug1](https://user-images.githubusercontent.com/6393606/68532805-cf810580-02ef-11ea-9fd1-4f655af0b8e8.png)
![cddarefugeecenterbug2](https://user-images.githubusercontent.com/6393606/68532806-cf810580-02ef-11ea-9575-7473b444261b.png)
![cddarefugeecenterbug3](https://user-images.githubusercontent.com/6393606/68532803-cf810580-02ef-11ea-99ce-4606b50a773c.png)
![cddarefugeecenterbug4](https://user-images.githubusercontent.com/6393606/68532804-cf810580-02ef-11ea-9df1-53062f3c3550.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9240-g1bb08dd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

I would've attached my save here but apparently my 41 MB save is too big for github, so screenshots will have to do.

**Comment by Odieman1** [comment]
Also had this happen with a character that has since been obliterated.  Though, for me I assumed it was because of the zombies in the other room, I figured they ran away from the noise or something.

**Comment by davidpwbrown** [comment]
got this too.
