### ISSUE TITLE
Crash when unloading RM451 into itself

### ISSUE THREAD

**Issue by tsorrells** [CleverRaven/Cataclysm-DDA#35443]
# Describe the bug

I noticed you can unload the napalm from an R451-2 canister, choose to pour it into a container, and then select the same container from the selection window.  This causes the game to crash.

# Steps To Reproduce

1. Have an RM451-2 canister filled with some amount of napalm
2. (U)nload this canister
3. Select Pour into container
4. Select the same RM451-2 canister from the selection window
5. Game crashes

# Expected behavior
Ideally you should not be able to unload a container into itself, the container you're pouring from shouldn't appear in the "pour into" selection window.

Alternatively you could have the game emit some silly description phrase instead of crashing, which would at least be an improvement.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9171-g8a44139 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Filthy Clothing [filthy_morale],
    Simplified Nutrition [novitamins]
]

**Comment by GediminasMasaitis** [comment]
> Alternatively you could have the game emit some silly description phrase instead of crashing, which would at least be an improvement.
I feel like this is the superior option, honestly.

**Comment by tivec** [comment]
This situation should be covered by this check, but maybe the container changes for some reason?

https://github.com/CleverRaven/Cataclysm-DDA/blob/fe55636ed2c7392ef72a44fe06d027c8d43328ff/src/handle_liquid.cpp#L196-L199

**Comment by tivec** [comment]
I'm unable to reproduce with a RM450-2 fuel canister, it just tells me I have no suitable containers to carry napalm. Do you have a save where it happens, and possibly a log?

**Comment by tsorrells** [comment]
![image](https://user-images.githubusercontent.com/1437138/68547162-dff2b800-03a3-11ea-8d0e-95ef9f80b67f.png)

Here's a screenshot of me messing around with it more.  I unloaded an RM450-4 canister from the RM451.  It has 3900/400 napalm loaded.  Then I Unloaded the RM451-4 and it clearly shows up in the  list allowing me the option of pouring it into itself.  I select that option (being the terrible person that I am) and then it asks me what to do with the "remaining amount".  So that check is clearly not preventing me from Unloading a container into itself.  Possibly important is that the napalm container is only PARTIALLY filled, not completely filled.

**Comment by tsorrells** [comment]
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3828694/debug.log)
I don't see anything useful inside, but here's the debug log after I crashed a few more times.
