### ISSUE TITLE
Trading a weapon to a friendly NPC while holding a similar weapon will cause the weapon you're holding to disappear

### ISSUE THREAD

**Issue by PotatoeChisps** [CleverRaven/Cataclysm-DDA#35441]
# Describe the bug
Trading a weapon to a friendly NPC while holding a similar weapon will cause the weapon you're holding to disappear

# Steps To Reproduce

Steps to reproduce the behaviour:
1. Wield one weapon and have a similar weapon in your inventory (in this case, it was two M1014 shotguns)
2. Trade with a friendly NPC one of your weapons (I used the weapon in my inventory, not the one I was wielding)
3. Your inventory weapon will be given to your NPC but your wielded weapon will disappear (even if it's in a sheath, harness or holster)

Side Note: Similar weapons in the inventory (not wielded) do not disappear when given to NPC's (tried with 4 Glock 18C's)

# Expected behaviour
I expect my wielded weapon to not disappear

# Versions and configuration

 - OS: Windows, 
    OS Version: 7 Professional, 7601
 - Game Version: 0.D-9271-g17dd261
 - Graphics version: Tiles
 - Mods loaded: [
Dark Days Ahead [dda], 
Aftershock [aftershock],
Cata++ [Cata++], 
Craftable Gun Pack [craftgp],
C.R.I.T Expansion Mod [crt_expansion], 
DeadLeaves Fictional Weapons [FIC_Weapons], 
Expanded Archery [ExArch], 
Garden Pots [growable-pots], 
Icecoon's Arsenal [ew_pack], 
Makeshift Items Mod [makeshift], 
Medieval and Historic Classes and Shields [Medieval_Stuff], 
More Survival Tools [More_Survival_Tools], 
Mythological Replicas [nw_pack], 
Modular Turrets [modular_turrets], 
Salvaged Robots [Salvaged_Robots],
EZ-Mode Medical [fast_healing], 
Hydroponics [hydroponics], 
Mutant NPCs [mutant_npcs], 
Mythical Martial Arts [MMA],
More Locations [more_locations], 
Fuji's More Buildings [FujiStruct], 
Mapgen Demo [mapgen_demo],
Urban Development [Urban_Development], 
Folding Parts pack [deoxymod], 
Vehicle Additions Pack [blazemod],
Tanks and Other Vehicles [Tanks], 
Roadheader and other mining vehicles [Heavy miners], 
Battery Migration for Existing Games [Battery_Overhaul_Legacy_Mode], 
Classes and Scenarios Mod [more_classes_scenarios], 
Disable NPC Needs [no_npc_food],
Manual Bionic Installation [manualbionicinstall], 
No Filthy Clothing [no_filthy_clothing], 
Prevent Zombie Revivication"no_reviving_zombies", 
Safe Autodoc [safeautodoc], 
Simplified Nutrition [novitamins], 
Slow Zombies [Slow_Zombies], 
Stats Through Kills [stats_through_kills]
]

# Additional context

Did not test with items, may or may not have the same problem as weapons

**Comment by Funguss** [comment]
I'm pretty sure this also happens when a weapon is on the floor and near enough to be included in trade and the NPC has a copy of that type, even if it's not part of the transaction and not even wielded.

**Comment by Ramza13** [comment]
Seems like #36477 should fix this

**Comment by int-ua** [comment]
Looks like it wasn't fixed, sadly: #38342 #39774
