### ISSUE TITLE
archery reworks needs to completed or undone

### ISSUE THREAD

**Issue by arijust** [CleverRaven/Cataclysm-DDA#35448]
**Is your feature request related to a problem? Please describe.**  
Archery and crossbows half-finished overhaul made them very erratic.
It decreased power of arrows, but it didn't increased power of bows/crossbows.
Some don't even make any damage and it's just annoying to actually use them/make new ones.(In JSON, not in-game)

**Describe the solution you'd like**  
Revert half-done archery overhaul.

**Describe alternatives you've considered**  
Complete archery archery overhaul, but it will complete pain even without going into detailed spreadsheet.

**Additional context**
It was mentioned/ranted on several websites, I personally use.
My botched archery run also made me annoyed enough to open this issue.

**Comment by Night-Pryanik** [comment]
"X isn't working right, and that's all I can say" is not a valid issue. Either describe in details what's working wrong AND how do you expect it to work, or we'll have to close such a vague issue.

**Comment by Destragon** [comment]
The issue is that the archery rework reduced the amount of damage arrows and bolts do, with the intention of later buffing the damage of the actual bow weapons to compensate for the damage reduction, but that second part of the rework famously never happened, because Darktoes quit.
OP is suggesting reverting the first archery rework, because people like to complain about the archery damage and reverting it is easier than actually finishing the rework properly.

**Comment by SavageBishop** [comment]
Instead of reverting a decent change, couldn't OP just take over and begin working on buffing the bows?

**Comment by arijust** [comment]
Decent changes, don't break several things at same time.

Also I probably will work on bow, if these changes won't get reverted.

**Comment by SirPendrak** [comment]
Wanst most of the data on archery rebalance ready, and only some problems with new reloading mods for crossbows need to be resolved?

**Comment by arijust** [comment]
>Wasn't most of the data on archery rebalance ready

I am sure it was deleted by archery contributor, when he left.

>some problems with new reloading mods for crossbows need to be resolved?

In the end, there will be need to do both without revert.

**Comment by Destragon** [comment]
Looking at #35460, seems like people are trying to fix it?

**Comment by Destragon** [comment]
Also, for additional context, this is the original closed archery PR that had unimplemented changes to bows and crossbows:
#30681
And some related issues (the last one was fixed already by Kevin):
#29941
#30026
#32958

**Comment by SirPendrak** [comment]
It would be nice to have it somewhat more finished for E. release. 
Even if archery red.3 was closed, its content is still available. 
It doesnt need to be 100% done and rushed, just dmg Ups for bows and crossbows would probably please most survivors.
