### ISSUE TITLE
Sweating and hygiene 

### ISSUE THREAD

**Issue by Kenan2000** [CleverRaven/Cataclysm-DDA#35451]
**Is your feature request related to a problem? Please describe.**  
This is one of my yet another suggestions to improve realism within the realm of CDDA.

In real life we sweat and become stinky and greasy with time, not using soap to wash our body properly, deodorant or something else to decrease temporarily sweating and give a better aroma, wearing same clothes for many days makes us dirtier with each day

If we strive for realism then hygiene should be greatly revamped

**Describe the solution you'd like**  
1. Make clothing become filthy with time due to a new parameter - **sweat** - forcing us to wash them more often
2. Allow us to wash hands and body with soap, regular soap bathing will **slightly decrease the rate** at which we **sweat** 
3. Add **deodorants** which will **moderately decrease sweat** rate along with the **smell** of the character
4. Running and fighting with low stamina should make our characters **sweat at a faster rate**
5. Possibly add **more ways to wash clothes**

**Describe alternatives you've considered**  
None.

**Additional context**  
None.

**Comment by anothersimulacrum** [comment]
From the [Frequently Made Suggestions](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions) 
> **Bathing/accumulating scent: mostly no**
> Every way we look at it, this seems like it would mostly be a pain to deal with for the player and not fun if it simply accumulated over time.
> One approach that might work would be specific monster attacks that make your scent stronger that you’d have to deal with somehow.

**Comment by Kenan2000** [comment]
Maybe this could be a mainlined mod like Filthy Clothing?So whoever wants to deal with this will do so, if you don't want to - just deactivate it
