### ISSUE TITLE
Random NPCs scale up with the player

### ISSUE THREAD

**Issue by Kenan2000** [CleverRaven/Cataclysm-DDA#35454]
**Is your feature request related to a problem? Please describe.**  
It seems quite unrealistic how our character is the only being in the entire game who is capable of becoming a power armor wearing demi-god destroying everything on it's way, it is intuitive that just like our character there are other survivors who might stumble upon high-tech technologies, artifacts, weapons and armor

It should be possible to automatically scale random NPC's skills, stats and gear along with the player, that will make possible meeting other humans like you, of similar strength

**Describe the solution you'd like**  
1. **Automatically scale random NPC's skills with player's**, example: if player has 7 marksmanship, 9 cooking and 10 fabrication, the randomly spawning NPC should have similar skill values, that does not mean that he should have same skills at same level, but different skills at same or close level
2. **Scale random NPC's weapons and armor with player's**, i think that this should be possible with all items that exist in both vanilla and mods, example: player is using survivor's gear - NPCs should be wearing gear that has similar stats in terms of defense and environmental resistance, it may be the same survivor's gear or something else with similar stats, same is true for both melee and ranged weapons (although flame and explosive weapons can be tricky to tackle in terms of balance)

**Describe alternatives you've considered**  
None.

**Additional context**  
None.

**Comment by Kenan2000** [comment]
Note that this does not automatically make other NPCs ONLY as strong as you are, it should be possible to meet weaker NPCs but at the same time survivors that are as strong as you in terms of power

**Comment by anothersimulacrum** [comment]
There are ways to do this, making random NPCs spawn with with skills and equipment similar to the player should not be the approach taken. Instead, as is covered in several other issues, random NPC actions should be simulated and then their equipment and skills should be determined by this.

**Comment by Kenan2000** [comment]
> There are ways to do this, making random NPCs spawn with with skills and equipment similar to the player should not be the approach taken. Instead, as is covered in several other issues, random NPC actions should be simulated and then their equipment and skills should be determined by this.

You mean like "scenarios" of some sort where random NPCs are more static by their nature?
Like Bandit - normal clothes, maybe kevlar vest, a shotgun, rifle or a handgun or a strong cutting melee weapon, Power Armor Soldier - power armor, laser or plasma or electric weapon

Like different classes, is that what you mean?

**Comment by anothersimulacrum** [comment]
It's been brought up before, such as in #28681, [this project](https://github.com/CleverRaven/Cataclysm-DDA/projects/17), #27226, and [this project](https://github.com/CleverRaven/Cataclysm-DDA/projects/7).

People are somewhat actively working on implementing it the way I suggested, which is why I did.
However, the way you suggested is very gamey - NPCs should advance independently of the player, the world shouldn't resolve around the player.

**Comment by Kenan2000** [comment]
Alright, i agree, it's way too gamey, i have not thought of this, ah, i guess i'm gonna close this one and continue to ponder about what fun and realistic additions could be made, so far all of my ideas have all failed, i guess i need to dig into some different direction, heh
