### ISSUE TITLE
Health and Health Modifiers rapidly drop as low as possible. No matter what they get set to

### ISSUE THREAD

**Issue by jasonmbrown** [CleverRaven/Cataclysm-DDA#35466]
# Describe the bug
Characters Health and Health modifier are essentially locked at -200/-190 respectively. (Unable to Heal limbs)

# Steps To Reproduce
Load Save https://www.dropbox.com/s/ps61ibtn6lmqhl7/Port%20Saint%20John.rar?dl=0
Consume anything that Gives Health boost (Gama Globulin (ground next to bed)/Pine Tea (vehicle tank), Force with Debug menu)
Wait in game 12 hours.
Check Health and Health Modifier stats on player. (Will be -200/-190 or near it)

# Expected behavior
Health and Health modifiers shouldn't change that fast, And I believe its supposed to default to 0

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9299-gc7c63d0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More City Locations [cityside],
    More Locations [more_locations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Prevent Zombie Revivication [no_reviving_zombies],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Simplified Nutrition [novitamins],
    No Fungal Monsters [No_Fungi]
]

**Comment by Nekatydaerla** [comment]
Your character is 'Morbidly Obese'. That caps your health at -200.

**Comment by jasonmbrown** [comment]
Well that explains that then... still that's a bit nuts. Thought it was bugged because I havent healed my limbs at all in almost 14 in game days, Excluding the autodoc splint

**Comment by SirPendrak** [comment]
Fat people are unable to naturally heal at all?

**Comment by jasonmbrown** [comment]
you heal with bandages and disinfectant, However if your limb is broken then your screwed it would seem.
