### ISSUE TITLE
Player gets drunk after consuming small amounts of alcoholic beverages.

### ISSUE THREAD

**Issue by Aphegis** [CleverRaven/Cataclysm-DDA#35462]
# Describe the bug

Player gets drunk after consuming small amounts of alcoholic beverages.

# Steps To Reproduce

1. Make a normal character.
2. Drink some alcohol.
3. Get drunk with extremely small amounts of beverage.

# Expected behavior

According to the size and natural tolerance of the character, the player should require higher amounts of alcohol to get drunk. 
Currently any character, doesn't matter the size and weight (amount of STR) gets drunk from having 0 alcohol in their system to "drunk" after ingesting 2 units of whiskey, 2 units of single malt whiskey 2 units of tequilla or 4 units of beer (i didn't tested with every alcohol beverage in the game but the behavior probably remains).

# Versions and configuration

 - OS: [Windows 7]
 - Game Version: [9885]
 - Graphics version: [Undead people]
 - Mods loaded: [Only disable npc needs]

# Additional context

2 Units of whiskey / tequila in the game corresponds to about 70ml of liquid in real life since a bottle in the game comports 21 units and have a total volume of 750ml.

**Comment by kevingranade** [comment]
Have any sources for what the number should be?

**Comment by Aphegis** [comment]
There's 2 options, a simple one (the objective of this issue I created) and a complex one (the ideal one, but long-term).

1 - The simple one: Increase the amount of "units" of alcoholic beverage necessary to make the player drunk and balance some negatives you receive when alcohol is consumed like the health modifier debuff. Also balancing the "substance tolerance" trait that increases the units necessary to get drunk from 2 to 5. Also adjust the 12 depressant that is given per unit.

Each unit of "strong alcohol" (whiskey, tequilla, gin, vodka, rum, brandy, single malt whiskey and triple sec) that you drink decreases your health modifier by 2, and each unit of "weak alcohol" (american pale ale, belgian ale, european pilsner, indian pale ale, barley wine, bee's knees, beer, homebrew beer and stout) decreases your health modifier by 1. It would be necessary to balance this because this value is really high. If you drink 2 units of strong alcohol, or 4 unit of weak alcohol, you are drunk and receive a -4 health modifier debuff (1 unit of strong alcohol = 35ml of alcohol = 1.2 oz of alcohol = 1 cigarrete in the game currently), if you are roleplaying a character that keeps drinking (moderately) for a few days your health regeneration will get a massive debuff (for instance players who choose the drunken master trait and frequently consume alcohol for the damage bonus). And given the fact that focus mechanic was reworked some time ago the joy bonus to the morale that the alcoholic beverage gives it's not high enough to make it worth the health modifier debuff.

But what is the amount that we should increase the units?

Using the "bathroom scale" item in the game with a completely new male character, naked, with no items in his inventory, it says the male character weights 78kg. (It doesn't matter the amount of Str, if you have 8 Str or 800 Str you keep weighting 78kg (171.9606 pounds), maybe it should be fixed in a future aswell). 
So we should use 78kg / 172 pounds as a reference weight.

There are a lot of blood alcohol online calculators but most of them are wrong because they assign a fixed ABV (Alcohol by volume) to each alcohol unit, and they don't factor in time, food consumed and so on the simple solution it should be well enough.

In this wikipedia page we have the amount of alcohol in some different beverages:
https://en.wikipedia.org/wiki/Alcohol_by_volume

Using this BAC (Blood Alcohol Calculator) https://www.alcohol.org/bac-calculator/ we can get some realistic values.

If a person consumes 2 units of strong alcohol in the game (= ~ 70 ml) it is about 2.463652 oz, but this calculator says 3 oz of liquor gives you a 0.06% BAC, according to this link https: //www.alcohol. org / effects / blood-alcohol-concentration /, 0.06% by no means makes you drunk. We should use 0.10%.

So to get to 0.10% of BAC levels you should drink =~ 4.8oz of a 40% ABV liquor, that corresponds to =~136ml of liquid instead of the current =~70. So i propose that we double the amount of "strong alcohol" necessary to get the player drunk, from 2 to 4 units (at a minimal of 3 units). The "weak alcohol" works a little bit different, because each unit in the game corresponds to 250 ml of liquid, so it should not be doubled, but increased by a 0.25 factor (or 0.5 factor).  So instead of 4 beers, 5/6 beers to a 78kg adult man to get drunk.

So after those values, characters with the substance tolerance trait should need to consume about 8 units of strong alcohol or 10-12 units of weak alcohol to get drunk. And the health modifier should be decreased a lot aswell in my opinion.


2 - The complex one: Make alcohol behave in a more realistic way taking into account: your sex, weight, and how full of food your stomach is. To be 100% accurate it would be necessary to take into account: sex, muscle mass, medications you are taking and how recently you until, but that amount of realism would be really hard to do the research and code it into the game. This would be the ideal one and maybe it should be made after the "simple solution" maybe in a conjunction with a whole drugs rebalance?

**Comment by I-am-Erk** [comment]
For removing this as a blocker I think we probably just need a reasonable effect level based on assuming the survivor is of average weight and alcohol tolerance, we can work in the fancy weight and tolerance effects later.
