### ISSUE TITLE
Player aparently takes only one sixth of fall damage.

### ISSUE THREAD

**Issue by Aphegis** [CleverRaven/Cataclysm-DDA#35461]
# Describe the bug

A character with 8 strength (84 hp in every limb) takes about =~ 45 limb damage after falling from the 6th floor of an apartment, but the text log of the game says: "You are slammed against the [insert terrain] for (in the case of this test) 286 damage,". Clearly there is some error in the calculation since the character i tested have no traits and no special equipment.

# Steps To Reproduce

1. Make a normal character.
2. Go to the 6th floor of an apartment.
3. Fall down and survive.

# Expected behavior

You should be instantly killed.

# Versions and configuration

 - OS: [Windows 7]
 - Game Version: [9885]
 - Graphics version: [Undead People]
 - Mods loaded: [Only disable npc needs]

# Additional context

Falling from 1 floor the log says: "You take 58 damage" but i took =~ 10
So maybe the game is only dealing =~ 1/5 of the total damage?

![Cata bug](https://user-images.githubusercontent.com/34956440/68571228-4a0d6a80-0441-11ea-9cfa-1f9291872500.png)

**Comment by SirPendrak** [comment]
Maybe it has something to do with player having 6 bodyparts total?

**Comment by Night-Pryanik** [comment]
Yeah, log shows total damage to all bodyparts, so total 286 damage is ~48 damage on every bodypart, which is WAY lower than it should be. 
The resulting damage is calculated roughly as follows: 
`effective force * rng( 60, 100 ) / 100`, where `effective force` is 60 for 6 stories. So even if rng rolls 100, damage to any bodypart would be ~60. Any armor reduces this value even further. 
We should tweak the formula for realistic amounts of damage from falling.

**Comment by SirPendrak** [comment]
Armor probably shouldnt matter here. I mean, if you fall on your stomach or chest from a few metters, then you would be better waering thick gambeson or something similar. But if you fall from 10 meters and land on your feet wearing for example heavy survivor suit, then its weight will only worsen damage to your bones. 

Anyway, curently you take damage to every body part from a fall? What about making it only damage your legs, but to a much higher degree than currently? And when you run out of leg hp, then rest of damage is transfered to torso. And when torso if at 0hp, and there is still some damage to redistribute, then it pulps your head and arms as well. Not that you care at this point anyway... 
So if you fall lets say from 4th floor, you break both your legs. If you fall from 6th floor, you die. Unless youre a mutant or have that one springy CBM.

**Comment by Night-Pryanik** [comment]
Such rework is feasible, of course, but for now I guess simple bugfixing could be enough.

**Comment by Funguss** [comment]
I thought this would be handled by the projectile mechanics? Or does that not deal with Z levels correctly yet?

**Comment by Night-Pryanik** [comment]
Projectile mechanics is completely unrelated to damage from falling.

**Comment by sdp0et** [comment]
I think armor should protect you. even if the weight of it adds to the total damage it protects against.  Looking at how helmets, elbow pads and knee pads reduce broken bones in falls and vehicle accidents makes it seem it would apply.  Since damage is abstract we're not worrying about which damage is actually your elbow breaking when it impacts concrete or abrasion on the skin of the knee or internal organs crashing into your rib cage, I think applying some percentage of the armor's blunt protection and/or a smaller percentage of cut/pierce damage would let a fall be different than a hit from a baseball bat but reflect that body parts are still cushioned and shielded from direct impact.
